### PR TITLE
std::net: Ipv4Addr and Ipv6Addr improvements

### PR DESCRIPTION
**Pull request by little-dude**
This is work in progress, but I'm opening the PR because I already have a few questions.

This PR:

- add a few methods to `Ipv4Addr`
- fixes `Ipv4Addr:is_global()`
- "fixes" `Ipv6Addr::is_unicast_link_local()` although as noted in https://github.com/rust-lang/rust/issues/27709 by @therealbstern, this "fix" is probably not what we want.

As I said I have a few questions:

- I'd like to add tests, but for that I need to be able to run them. I tried `./x.py -i test src/libstd  --test-args std::net` and a few variants, but on my laptop, those commands take more than an hour, so it's not viable. So how can I run the tests in ` src/libstd/net/ip.rs`?
- I added a few methods, and I think I need to mark them as unstable somehow. I see some methods are decorated with `#[stable(since = "1.7.0", feature = "ip_17")]`, but I'm not sure what `ip_17` stands for. Should I add `#[unstable]`?

### CODE REVIEW

**Comment by therealbstern** [comment]
ISTR from when I worked on `is_unspecified` that you can leave the `unstable` markings alone (neither adding nor deleting them).  I think that when someone approves the stability, they add the correct feature flags and delete the unstable decoration.

`ip17` is "We put this in `std::net::ip` in Rust 1.7.0" and we don't know which Rust will get this, so I think you should leave it alone too.

**Comment by TimNN** [comment]
@rust-lang/libs: This PR adds several new methods `Ipv4Addr` and, IIUC, changes the behavior of some methods. Could you take a look at this PR and also, if possible, assign someone familiar with this topic?

**Comment by alexcrichton** [comment]
It looks like these methods aren't stable yet so there shouldn't be any stability worries here, in which case seems fine to me to land!

**Comment by little-dude** [comment]
@alexcrichton this is not totally done yet sorry, I'll push [one more change](https://github.com/rust-lang/rust/issues/27709#issuecomment-400324755) for `Ipv6Addr`. Probably tomorrow, but maybe only this week-end if you don't mind waiting.

**Comment by alexcrichton** [comment]
Sure thing!

**Comment by TimNN** [comment]
Ping from triage, @little-dude: We haven't heard from you in a while, what is the status of this PR?

**Comment by pietroalbini** [comment]
Thank you for this PR @little-dude! Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please **reopen** this PR, we'll be happy to review it again!

**Pull request closed without merging**
