### PR TITLE
Reject a LHS formed of a single sequence TT during `macro_rules!` checking.

### PR DESCRIPTION
**Pull request by LeoTestard**
This was already rejected during expansion. Encountering malformed LHS or RHS during expansion is now considered a bug.

Follow up to #33689.

r? @pnkfelix

Note: this can break code that defines such macros but does not use them.

### CODE REVIEW

**Comment by pnkfelix** [comment]
@LeoTestard does this need to wait for #33713 to land before it can land?  Or are they independent?

**Comment by LeoTestard** [comment]
Ah, good point, they are independent but I'm afraid it will break it and require rebase. Let's wait then.

**Comment by LeoTestard** [comment]
I removed a test because the issue it was introduced for (#21350) involves code that seem to rely on the feature that this PR is removing. Thing is that the macro expander doesn't accept macros with this kind of LHS. I don't know why this issue was opened, maybe it was accepted by the expander at the time? Thoughts @cmr?

**Comment by pnkfelix** [comment]
@LeoTestard my interpretation is that we wanted to ensure we didn't ICE add a first priority

So you might move the original text to `compile-fail` and add the new error message for it. Or maybe your unit tests already cover it any way. 

----

this change *might* break crates in the wild (only ones that have macros with dead arms using the erroneous syntax I think) .  So we might want to put it through a warning cycle?

**Comment by LeoTestard** [comment]
@pnkfelix I'm pretty sure it's already covered.

**Comment by LeoTestard** [comment]
@pnkfelix Up? r?

**Comment by alexcrichton** [comment]
@bors: retry

* #33844

**Pull request merged**
