### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #98304 (Add MaybeUninit memset test)
 - #98801 (Add a `File::create_new` constructor)
 - #99821 (Remove separate indexing of early-bound regions)
 - #100239 (remove an ineffective check in const_prop)
 - #100337 (Stabilize `std::io::read_to_string`)
 - #100819 (Make use of `[wrapping_]byte_{add,sub}`)
 - #100934 (Remove a panicking branch from `fmt::builders::PadAdapter`)
 - #101000 (Separate CountIsStar from CountIsParam in rustc_parse_format.)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=98304,98801,99821,100239,100337,100819,100934,101000)

### CODE REVIEW

**Comment by nnethercote** [comment]
@rust-timer build 598629adb937afc7096511b6007db166eb6fe6e6

**Comment by nnethercote** [comment]
@rust-timer build 9c74cb3c63daa7e254a78a7695f6cf84ea5476c8

**Comment by nnethercote** [comment]
Looks like the second build command didn't work. I think I was supposed to put both in the same comment. I can redo the second build command once the first perf run is complete.

**Comment by nnethercote** [comment]
No need to run the second one, because the first run matches up almost perfectly with the run for the entire rollup. Which means that #99821 is responsible for all the improvements *and* regressions for this rollup.

**Comment by rylev** [comment]
@cjgillot FYI

I think given that the improvements outweigh the regressions we should mark this as triaged. However, if anyone is curious, we can spend some time trying to figure out the cause of the regressions. 

@rustbot label: +perf-regression-triaged

**Pull request merged**
