### PR TITLE
Added -all- x86 platform intrinsics

### PR DESCRIPTION
**Pull request by valarauca**
This patch adds all x86_86 platform intrinsic. The names are compliant with those used in the GCC, ICC, and MSVC. 

The x86.rs file is generated via a [rust program](https://github.com/valarauca/Decode-x86-SIMD/tree/master).

A ~4 months ago @sanxiyn [request](https://news.ycombinator.com/item?id=11839949) I add them to this commit when I got around to a submitting.

I realize this is directly modifying a _generated_ file. But this method allows for automated updates without hand modifying writing JSON. 

I can extend decode-simd to include the MIPS, Aarch, Arm, POWER8, (and even NVVC+AMDGPU) platforms if that is needed/wanted.

### CODE REVIEW

**Comment by rkruppe** [comment]
> I realize this is directly modifying a generated file. But this method allows for automated updates without hand modifying writing JSON. 

One can argue about whether the current JSON-based intrinsic specification is the best option or not. Maybe mining other projects like your program does is better. I don't know enough about the while `platform_intrinsics` infrastructure to have an opinion on that. But it would be quite unfortunate to have two different code generation tools for essentially the same job, especially if (as it seems to me) they know nothing about each other and thus can't cooperate very well.

**Comment by valarauca** [comment]
@rkruppe 
> But it would be quite unfortunate to have two different code generation tools for essentially the same job, especially if (as it seems to me) they know nothing about each other and thus can't cooperate very well.

This is a valid concern. I don't have a good solution. Although I would point out that GCC uses hand written C files for x86 SIMD, but Common LISP script for aarch64 SIMD. 

The main issue I had with patching the json files is there wasn't a good guide on how to merge changes from multiple files. It works fine for aarch and arm. But with x86 there are several separate files. And each one produces their own output (complete with header/match information). Furthermore it unifies feature sets like SHA1, SHA256, AES, the various flavors of AVX256 (F,BW,CD,DQ,ER,IFMA52,PF,VBMI, VL).

**Comment by retep998** [comment]
I believe you checked in some files unintentionally, specifically under `src/target`.

**Comment by valarauca** [comment]
@retep998 How do I remove them `git rm` and `git commit -amend` is just making life harder.

**Comment by valarauca** [comment]
So the most recent failure is coming down to type checking within the SIMD tests itself. 

I'd like to know how the community wants to proceed before we start editing tests because there will be A LOT of tests to add.

**Comment by retep998** [comment]
Your PR still contains several `src/target/debug/.fingerprint` files along with `src/target/debug/.cargo-lock `.

**Comment by valarauca** [comment]
Will close and re-submitted once rebased

**Pull request closed without merging**
