### PR TITLE
Less-than is asymmetric, not antisymmetric

### PR DESCRIPTION
**Pull request by taralx**
This has bothered me for a while. It's such a small nit, but...

### CODE REVIEW

**Comment by sfackler** [comment]
I believe the documentation is correct - less-than is an antisymmetric relation: https://en.wikipedia.org/wiki/Antisymmetric_relation.

**Comment by taralx** [comment]
`<=` is antisymmetric. `<` is asymmetric.

antisymmetric: if a <= b and b <= a, then a = b.

asymmetric: if a < b then not b < a.

**Comment by sfackler** [comment]
Ah right.

@bors r+ rollup

**Comment by RalfJung** [comment]
Asymmetry is a property of a single relation though, whereas really here we are talking about three related relations (heh). Not sure what the best terminology is there. But yeah, "asymmetric" seems to fit better than "antisymmetric".

Cc https://github.com/rust-lang/rust/issues/50230

**Pull request merged**
