### PR TITLE
Update tests names to start with `issue-`

### PR DESCRIPTION
**Pull request by henryboisdequin**
See @JohnTitor's [comment](https://github.com/rust-lang/rust/pull/82720#discussion_r586488083)

@rustbot label +C-cleanup

### CODE REVIEW

**Review by JohnTitor — CHANGES_REQUESTED** [review]
Note that `.stderr` contains file name so you should bless it.

**Comment by henryboisdequin** [comment]
@JohnTitor thanks, I forgot

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
@bors rollup
This is definitely safe to rollup.

**Comment by JohnTitor** [comment]
Sorry but I'm not part of the reviewers so r? @Mark-Simulacrum for final review.

**Comment by Xanewok** [comment]
Seems like a no-brainer and seems more in line with what we current have (even if we'll have to later rename it to a more meaningful name, as that's the approach we're slowly taking with issue # tests)

r? @Xanewok
@bors r+

**Pull request merged**
