### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #101936 (Migrating rustc_infer to session diagnostics (part 3))
 - #104081 (PhantomData layout guarantees)
 - #104543 (Migrate `codegen_ssa` to diagnostics structs - [Part 3])
 - #105128 (Add O(1) `Vec -> VecDeque` conversion guarantee)
 - #105517 (Fix process-panic-after-fork.rs to pass on newer versions of Android.)
 - #105859 (Point out span where we could introduce higher-ranked lifetime)
 - #106509 (Detect closures assigned to binding in block)
 - #106553 (docs: make `HashSet::retain` doctest more clear)
 - #106556 (rustdoc: remove no-op mobile CSS `.content { margin-left: 0 }`)
 - #106564 (Change to immutable borrow when cloning element of RepeatN)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=101936,104081,104543,105128,105517,105859,106509,106553,106556,106564)

### CODE REVIEW

**Comment by rylev** [comment]
Nothing really jumps out here as the most likely possibility of a regression. I think the following are possible (in rough order of likelihood):
* https://github.com/rust-lang/rust/pull/104543
* https://github.com/rust-lang/rust/pull/101936
* https://github.com/rust-lang/rust/pull/106509
* https://github.com/rust-lang/rust/pull/105859

I'll go through them and see if we can find the culprit.

@rust-timer build a6e41579df479fc55ec1cddab0bd3202f5eb7b8a

**Comment by rylev** [comment]
@rust-timer build f138838c2a5362ba79be51df5ff18845d94c2c4d

**Comment by rylev** [comment]
It looks like https://github.com/rust-lang/rust/pull/101936 is the reason for the performance regression. cc @IntQuant @compiler-errors @davidtwco

**Comment by Mark-Simulacrum** [comment]
Marking this as triaged and tagging #101936 instead with perf-regression.

**Pull request merged**
