### PR TITLE
Suggest the `pat_param` specifier before `|` on 2021 edition 

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Ran into this today after writing some Rust for the first time in a while.

r? @estebank

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
The test in the third commit seems to be the same as the one in the second. I guess one is supposed to not have `edition=2021`?

**Comment by joshtriplett** [comment]
Looks like a great improvement!

**Comment by estebank** [comment]
@ecstatic-morse yeah, that seems like a preexisting mistake (the path implies that these might be duplicated to begin with). I would remove the edition flag on one of them (and rename it to make it clearer it is <=2018).

r=me with that change and squashed commits.

**Comment by ecstatic-morse** [comment]
So there's already another pre-2021 test that is identical `macro-pat-pattern-followed-by-or-in-2021`.`macro-pat2021-pattern-followed-by-or` is different in a few places. I think we should just leave it.

**Pull request merged**
