### PR TITLE
Fix header of style's README using `%` instead of `#`

### PR DESCRIPTION
**Pull request by czipperz**

### CODE REVIEW

**Comment by czipperz** [comment]
This seems to affect alot of the readme.md files.  Not sure if this is intentional or not

**Comment by mitaa** [comment]
Looking at the travis log this seems intentional
```
rustbook: doc/style/index.html
invalid markdown file: expecting initial line with `% ...TITLE...`
```

**Comment by czipperz** [comment]
Strange. Thanks for that information!
I wonder why that is the chosen style

**Comment by alexcrichton** [comment]
Yes we currently use a custom renderer for markdown which has this... interesting limitation, so this is intentional. Thanks for the PR though!

**Pull request closed without merging**
