### PR TITLE
Make allocator_kind a query.

### PR DESCRIPTION
**Pull request by cjgillot**
Part of #85153

r? @Aaron1011

### CODE REVIEW

**Comment by cjgillot** [comment]
Let's be prudent this time.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Rebased
@bors r=Aaron1011

**Comment by klensy** [comment]
Perf run was before rebase, so something can be broken again.

**Comment by cjgillot** [comment]
Last perf run was done on top of https://github.com/rust-lang/rust/pull/85886. None of the more recently merged PRs involve `allocator_kind`.

**Comment by cjgillot** [comment]
Only `dist-x86_64-apple` failed, seems spurious.
@bors retry

**Comment by Aaron1011** [comment]
@cjgillot What's the status of this PR?

**Comment by cjgillot** [comment]
I added a commit for an implementation that I find a bit cleaner.
It's ready for review.

**Comment by Aaron1011** [comment]
@cjgillot: Can you resolve the merge conflicts?

**Comment by Aaron1011** [comment]
The performance regresions are quite small..

@bors r+

**Pull request merged**
