### PR TITLE
Add rotation animation on settings button when loading

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
As discussed, I added an animation when the settings JS file is loading (I voluntarily made the timeout at the end of the `settings.js` super long so we can see what the animation looks like):

https://user-images.githubusercontent.com/3050060/166693243-816a08b7-5e39-4142-acd3-686ad9950d8e.mp4

r? @jsha

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed merge conflict.

**Comment by jsha** [comment]
Can you put up a demo?

**Comment by GuillaumeGomez** [comment]
Unless you block the JS to be downloaded, you won't be able to see the rotation. Do you want me to put up a demo in any case?

**Comment by jsha** [comment]
Yep - devtools can do various things to simulate slow or offline loading. There's also a very simple expedient to test such things - turn of your Wi-Fi. :-)

**Comment by GuillaumeGomez** [comment]
The demo is now up [here](https://rustdoc.crud.net/imperio/rotation-animation/doc/foo/index.html).

**Pull request merged**
