### PR TITLE
Revert edition-guide toolstate override

### LINKED ISSUE #60929: Reinstate edition-guide toolstate check
This is a tracking issue for reverting the change introduced in #60791 which disabled the toolstate check for the edition-guide.

It is currently blocked on #60459 which is causing a test failure in the edition-guide.  I will reinstate the check as soon as that issue is fixed.

@Mark-Simulacrum has requested the labels t-release and I-nominated.

### PR DESCRIPTION
**Pull request by ehuss**
Closes #60929

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Does this need beta backport? r=me if not, otherwise we should not close that issue - r=me if closes is removed from the description

**Comment by mati865** [comment]
For the reference PR fixing the issue is nominated for beta https://github.com/rust-lang/rust/pull/61098

**Comment by ehuss** [comment]
I don't think it really matters that it is backported to beta.  For me, this is a "nice to have" to get early warning of breakage.  The chance that something new breaks it on stable or beta but not master I think would be close to zero.  But if the #61098 backport wants to include this, that would be fine, too.

**Comment by Mark-Simulacrum** [comment]
I've accepted for beta backport (but blocked on #61098, presumably).

@bors r+

**Pull request merged**
