### PR TITLE
Rollup of 16 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #24576, #24966, #25052, #25131, #25137, #25138, #25139, #25140, #25141, #25142, #25144, #25146, #25148, #25154, #25156, #25160
- Failed merges:

### CODE REVIEW

**Comment by steveklabnik** [comment]
prioritizing this since i'll be around for the next few hours

**Comment by Manishearth** [comment]
```
test net::tcp::tests::fast_rebind ... FAILED
```

this is network-dependent I presume?

**Pull request closed without merging**
