### PR TITLE
Rename `ErrorReported` -> `ErrorGuaranteed`

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @eddyb 

cc https://github.com/rust-lang/rust/pull/93222 https://github.com/rust-lang/rust/issues/69426

The idea is that we would like to use it for both errors and `delay_span_bug`. Its semantics indicate a _guarantee_ that compilation will fail.

### CODE REVIEW

**Comment by eddyb** [comment]
It was pretty late when I suggested this, and it amused me, so take that with a grain of salt.
We could probably let this sit to see if anyone else from @rust-lang/compiler has opinions on the bikeshed.

**Comment by jackh726** [comment]
Honestly, I think ErrorReported is more clear. Even with delay_span_bug, an error *does* get emitted (or it might be an ICE, I don't recall) even if a diagnostic isn't emitted.

**Comment by eddyb** [comment]
> Even with `delay_span_bug`, an error *does* get emitted (or it might be an ICE, I don't recall) even if a diagnostic isn't emitted.

The problem with the name is one of ordering/causality. With `delay_span_bug`, we want a value of this token, but *nothing happened yet*. In that case, it's a *promise*, that an error *will be* reported.

`ErrorInevitable` is probably closer, but it sort of gives the opposite (and also wrong) impression of "all errors are deferred". Being extremely literal, like `ErrorWasOrWillBeReported`, seems somewhat undesirable.

`CompileFailGuaranteed` (or the `DoomedCompilation` not-entirely-serious suggestion) makes more sense to me, since the purpose of the token isn't to indicate that small self-contained part of the compiler errored *itself*, but rather than *compilation will not succeed*, which gives leeway to do things that would be too expensive, or unsound, otherwise (or, alternatively, skip steps that serve no purpose for diagnostics).

**Comment by mark-i-m** [comment]
I don't have strong feeling here myself. I understand Eddy's point, but also think the usage with `DelaySpanBugEmitted` is uncommon enough that it's not too important.

**Comment by eddyb** [comment]
> but also think the usage with `DelaySpanBugEmitted` is uncommon enough that it's not too important

I wouldn't say that, given that `ty::Error` is based on "`delay_span_bug` is enough". That is, `ty::Error` *today* contains a "proof token" that an error *will be* emitted, not that one *was*.
AFAIK that's more pervasive than `ErrorReported` from actual errors (before #93222, at least).

**Comment by eddyb** [comment]
@jackh726 Do you think `ErrorGuaranteed` or something similar, that doesn't imply *when* the error was/will be reported, is enough? I don't have a big issue with `Error` in the name, more with `Reported`, really.

**Comment by jackh726** [comment]
ErrorGuaranteed sounds good

**Review by eddyb — APPROVED** [review]

**Review by oli-obk — APPROVED** [review]

**Comment by eddyb** [comment]
Forgot to leave a comment, but I meant to say that this LGTM, I just want more @rust-lang/compiler eyes on it.
You can r=me in a few days if nobody argues against it - this feels too small for a FCP, but there might still be disagreements.

**Review by lcnr — APPROVED** [review]

**Review by wesleywiser — APPROVED** [review]

**Comment by nikomatsakis** [comment]
I am nervous about this. In fact, this precise usage has gotten us into trouble before.

**Comment by nikomatsakis** [comment]
The problem is this:

* You have some code that gets into a situation where an error should be reported later. It emits `span_bug` and returns `ErrorGuaranteed`.
* The code which should report the error comes later -- it somehow observes this `ErrorGuaranteed` and says "well, I guess I can supresss reporting this error since the user has already been inundated". Or perhaps the code which should report the error never even runs!
* Then you get the delay-span-bug.

**Comment by mark-i-m** [comment]
@nikomatsakis That seems like an abuse of `ErrorGuaranteed` to me... I don't think it is meant as a signal about _what kind_ of failure will happen -- just a static guarantee that compilation will fail. i.e. it is meant to prove that the compiler will not do something, rather than a marker that the compiler has done something.

**Comment by nikomatsakis** [comment]
Well, that's the opposite of `ErrorReported` =) which is meant precisely to be a marker of something that *has happened*, which allows us to do arbitrary things later (like: skip parts of our safety checks or suppress potential duplicate errors) without fear of unsoundness.

**Comment by eddyb** [comment]
> without fear of unsoundness

Isn't that precisely why we have `delay_span_bug`? I don't think an ICE preventing unsound compilation is as bad as the respective unsoundness. It's suboptimal from an UX point of view, sure, but the only kind of "proof" we can encode today has to be obtainable from `delay_span_bug`, to be meaningful.

To avoid `delay_span_bug`, we would pretty much have to track every reported error that could possibly be relevant to something else, and propagate them that way (e.g. parse/name-resolution errors into HIR).

There's currently over 150 `delay_span_bug`s in the compiler, and some of them underpin `{Ty,Const}Kind::Error`, which were made to guarantee *at least* `delay_span_bug`, a while back (#69426 representing the finalization of that work, basically).

It seems much more work than what we can do more immediately, but maybe I'm missing a subtle detail.
I am curious about your dislike of `delay_span_bug`, since I view it as a relatively-low-overhead (infrastructure-wise) way to guarantee unsoundness in the presence of diagnostics that can't talk to eachother easily.

**Comment by jackh726** [comment]
I'm a bit confused about the case @nikomatsakis is worried about; is it when we've already emitted a `delay_span_bug`, but later on emit an error anyways (but now wouldn't because of some "stronger" guarantee?)? That feels not great, but I'm be curious if there are any places that we *actually* do that.

I guess one "cheap" way we can solve this is to make `ErrorGuaranteed` an enum: `Reported` or `NotReported`. It's not great, since to "propagate" that you've reported an error when you've already seen an `ErrorGuaranteed::NotReported` would be to replace the existing `Ty`, through folding or some other means.

Another alternative would be some kind of error code enum, for a little bit more precise matching. A benefit of this is we could in theory use that to deduplicate previously-emitted errors (so, if we slowly change `delay_span_bug`s to actually errors, we don't start getting duplicates).

I think a key difference between `delay_span_bug`s and real errors is their ability to "stop" compilation; the latter will stop wfchecking if coherence checking fails, for example, while the former wouldn't. Along these lines, `delay_span_bug`s are often used as a sort of "we're in a weird state, but otherwise okay".

I can understand @nikomatsakis's point, kind of. But I don't know the best way to solve it. Maybe a solution is to move any errors that are emitted solely from a `delay_span_bug` to be propagated separately, and leave `delay_span_bug` only as a "silent" check on unsoundness.

**Comment by nikomatsakis** [comment]
@jackh726 

> I'm a bit confused about the case @nikomatsakis is worried about; is it when we've already emitted a delay_span_bug, but later on emit an error anyways (but now wouldn't because of some "stronger" guarantee?)? That feels not great, but I'm be curious if there are any places that we actually do that.

To be clear, my example is not theoretical: we actually had this bug. I forget the precise details, but it went something like this:

Some parts of the code ran at many times. At some points they could see that a given situation would result in a region error, so they returned `ErrorReported`, which eventually became `ty::Err`.

But region inference had not run yet. When it did go to run, it observed the `ty::Err` and opted not to run, because there were other trait resolution errors and it was deemed highly likely that the region errors would be confusing and derivative.

**Comment by nikomatsakis** [comment]
@eddyb 

> Isn't that precisely why we have delay_span_bug? I don't think an ICE preventing unsound compilation is as bad as the respective unsoundness. It's suboptimal from an UX point of view, sure, but the only kind of "proof" we can encode today has to be obtainable from delay_span_bug, to be meaningful.

Hmm, ok, I agree that `delay_span_bug` is different from the case I am mentioning. It may be that I'm ok with this change but I think we should be very careful to document the limitations here and to not go *further* into "this will generate an error later".

**Comment by nagisa** [comment]
I'm personally quite happy with the name, but an alternative could be `FailureGuaranteed`. It does not necessarily imply the graceful error as much, I feel; maybe it'd be enough to convince Niko ^^

**Comment by nikomatsakis** [comment]
I think I am happy so long as we have a rustc-dev-guide chapter explaining when it is ok to use "error guaranteed" (and outlining when it is *not* -- i.e., the scenario I wrote above).

**Comment by mark-i-m** [comment]
I have rebased this PR and open a PR on the rustc-dev-guide to document `ErrorGuaranteed`, as per Niko's request above: https://github.com/rust-lang/rustc-dev-guide/pull/1316

@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

**Comment by oli-obk** [comment]
r? @oli-obk 

Assigning to myself as it was previously unassigned

**Comment by oli-obk** [comment]
r=me after a rebase

@bors p=1 bitrotty

**Comment by mark-i-m** [comment]
@oli-obk rebased!

**Pull request merged**
