### PR TITLE
impl ExactSizeIterator for [T; N] Flat{ten,Map}

### PR DESCRIPTION
**Pull request by tamird**
/cc @the8472

### CODE REVIEW

**Comment by the8472** [comment]
This can't work properly because the size calculation could overflow by expanding usize::MAX items into usize::MAX * N items. `ExactSizeIterator`  is unlike `TrustedLen` in that regard.

**Comment by tamird** [comment]
Right, but [`TrustedLen`](https://doc.rust-lang.org/stable/core/iter/trait.TrustedLen.html) is experimental. Is there a roadmap describing the relationship between `ExactSizeIterator` and `TrustedLen` and how they should be used that I can read?

**Comment by tamird** [comment]
[This section](https://doc.rust-lang.org/stable/core/iter/trait.ExactSizeIterator.html#when-shouldnt-an-adapter-be-exactsizeiterator) of `ExactSizeIterator`'s documentation seems to preempt what I wanted to do in this PR. I guess there's nowhere to go from here?

**Comment by the8472** [comment]
Not sure what your goal here is? Do you have something that needs `ExactSizeIterator` in a where clause? `TrustedLen` is only necessary for unsafe code and specialization.
If you neither need where bounds nor safety guarantees then you can check whether `size_hint` has tight bounds.

**Comment by tamird** [comment]
Yeah, I wanted `ExactSizeIterator` in a where clause so that I could serialize a payload's length ahead of its content.

**Comment by the8472** [comment]
Yeah, that's not possible if you also want to support `Flatten`. The best you can do in those circumstances is to check the `size_hint` and return an error/panic when it's not precise or do something like CBOR which can switch between prefix-length and end-token encoding depending on the input.

`TrustedLen` wouldn't really help here either since it can be larger than usize too which you then couldn't serialize either.

**Comment by tamird** [comment]
> Yeah, that's not possible if you also want to support `Flatten`.

Sorry, can you spell out why `Flatten` is a particular problem?

Anyhow, I'll close this since it seems that there's no way to do this statically.

**Comment by the8472** [comment]
Well, `ExactSizeIterator` (or any similar "determine length in advance" kind of trait) needs the iterator be A) of known length at any time B) the length must fit into a `usize`.
Both conditions can't be fulfilled in the general case.

A) is not known because the length of sub-iterators is dynamic, not represented in the type system
B) is violated when the sub-iterators can emit more than 1 item because a usize::MAX input iterator can get expanded to > usize::MAX items.

A) can be done for arrays, B) can be avoided by making the operation fallible. Which is what TrustedLen does. And even then it's fairly limited because it only works for arrays and basically nothing else because those are the only fixed-length iterables.

**Pull request closed without merging**
