### PR TITLE
Rollup of 29 pull requests

### PR DESCRIPTION
**Pull request by arielb1**
- Successful merges: #39202, #39820, #40092, #40146, #40199, #40225, #40239, #40259, #40278, #40287, #40297, #40311, #40315, #40319, #40324, #40340, #40344, #40345, #40372, #40373, #40379, #40385, #40386, #40389, #40400, #40404, #40410, #40422, #40423
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* presumed sccache failure https://github.com/rust-lang/rust/issues/40240

**Comment by arielb1** [comment]
```
Dist cargo stage2 (x86_64-pc-windows-msvc)
thread 'main' panicked at 'no entry found for key', C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libcore\option.rs:715
```

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/40432 which I believe has a fix

**Pull request closed without merging**
