### PR TITLE
Support multiple versions of MdBook for docs

### PR DESCRIPTION
**Pull request by jamesmunns**
Only the compatibility items from the embedded book PR. PR with embedded book components: https://github.com/rust-lang/rust/pull/56291

CC @steveklabnik, @ehuss, and https://github.com/rust-lang-nursery/edition-guide/pull/134

### CODE REVIEW

**Comment by jamesmunns** [comment]
Fixing some things locally, will push updates soon

**Comment by ehuss** [comment]
Just a heads up, this will likely fail the license check.  I think `arrayref` will need to be added to the exception list.  I'm pretty sure the other dependencies will be ok, but I'm not certain.

Am I correct that this can't really be used until the print.html issue is solved?

**Comment by jamesmunns** [comment]
@ehuss I was not aware of the license check

**Comment by jamesmunns** [comment]
This may work for you, depending on how you are doing links. It does not work for the style the embedded-book uses, but I am not sure if your changes will have an issue.

You could rebase your changes on this PR, and try running `python x.py test src/tools/linkchecker`?

**Comment by steveklabnik** [comment]
Hey @jamesmunns , thanks for this! I think this is a great step forward.

I:

* built your PR locally
* wrote a new book in tree with two pages, linking to each other
* built with mdbook1 and watched the linkcheck fail
* built with mdbook2 and watched only print.html fail

I'm not sure about the license check mention, given that travis passed here. @ehuss could you say more about the problem you see here?

Given that both of us are still running into https://github.com/rust-lang-nursery/mdBook/issues/828, here's what I'd like to propose:

1. I'm going to look into the print.html issue now
2. we let this PR sit over the weekend, I highly doubt that I'll have a bugfix ready in the remaining time I have today
3. Hopefully on Monday i'll have a patch and we can put out a new mdbook release, update this PR to include it, and then merge.

Sound like a plan?

Thanks again for working on this; I didn't realize that we could depend on both versions so easily!

**Comment by ehuss** [comment]
> I'm not sure about the license check mention, given that travis passed here. @ehuss could you say more about the problem you see here?

Yea, the license checks are only performed in the `distcheck` builder, which is not run on PRs.  I've wondered in the past if it might be possible to run a reduced job on PRs that only did license checks, but I'm not sure if `distcheck` is too different to get an accurate result quickly (`distcheck` requires generating a release tarball, extracting it, yadda yadda).  It's a pain because nobody knows about the problem until bors tries to merge.

AFAIK, it can be run locally using the following steps:
1. Run `cargo vendor`
2. Edit `config.toml` and set `vendor` to `true`.
3. `./x.py test tidy`

After it's done, don't forget to delete `.cargo/config` and unset `vendor` and maybe delete the `vendor` directory.

License rules and exceptions are stored in https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs.

**Comment by jamesmunns** [comment]
Hey @steveklabnik, I didn't see this (my inbox is a mess right now), but your plan sounds good! I'll be available during Berlin business hours this week as well if I can help with anything.

If you are able to fix the print.html issues, I can also get the embedded book PR fixed up ASAP!

**Comment by steveklabnik** [comment]
It's all good!

So, between Friday and this morning, I think I've found the culprit. Bad news is, I'm not sure the fix will be easy. I'll fill in more details on the mdbook issue.

**Comment by steveklabnik** [comment]
Good news! Not only has my local test been successful, but I applied https://github.com/rust-lang/rust/pull/56291 on top of it as well, and the tests seem to pass!

Next steps are to get https://github.com/rust-lang-nursery/mdBook/pull/866 reviewed, a release cut, and update this PR to use it.

Thank you again for sticking through this, it's been a journey but I'm *really* excited about it. This "two versions of mdbook" strategy is going to work out much more nicely than my initial "oh god do the work of updating all of the books at the same time" thing I thought I had to do.

**Comment by steveklabnik** [comment]
@jamesmunns I have released mdbook 0.2.3 with the fix; can you update this PR to use that version, and then we can merge 🎊

**Comment by jamesmunns** [comment]
Sure! I'll try to get to this in the next 2-3 hours!

**Comment by jamesmunns** [comment]
@steveklabnik updated to use the new 0.2.3 release. @ehuss I have also added a license exception for `arrayref`.

**Comment by jamesmunns** [comment]
Hey @steveklabnik, reping on this for the `r+` :)

**Comment by steveklabnik** [comment]
@bors: r+

Thanks so much again!

**Comment by jamesmunns** [comment]
I'll do my best to address this tonight. @steveklabnik I've sent you an invite to my fork if you'd like to commit directly there (before I have a chance)

**Comment by jamesmunns** [comment]
@steveklabnik this needs a re-up please!

**Comment by jamesmunns** [comment]
Looks like Cargo.lock is getting rowdy today. Fixed another merge conflict, I guess we wait another couple hours for CI.

**Comment by jamesmunns** [comment]
@steveklabnik okay, CI is green again! (sorry for the excess of pings, I want to get this merged before I get pulled away again)

**Comment by steveklabnik** [comment]
@bors: r+

Sorry about this @jamesmunns ! I thought I had r=me'd it and it had already landed. Let's get this in!

**Comment by jamesmunns** [comment]
Hey, I probably won't have time to fix this merge conflict until the end of this week.

**Comment by steveklabnik** [comment]
No problem; I'll do it later today <3

**Comment by jamesmunns** [comment]
I would like to rescind my :rocket: emoji.

**Comment by steveklabnik** [comment]
@bors: r+ 

@jamesmunns don't worry; I *will* get this through...

**Comment by jamesmunns** [comment]
🙏 Ganbatte @steveklabnik!!!

**Comment by ehuss** [comment]
Filed issue for spurious failure https://github.com/rust-lang/cargo/issues/6613.

**Pull request merged**
