### PR TITLE
Clarify when Cargo.lock is created by `cargo build` in the book

### PR DESCRIPTION
**Pull request by dirk**
Also remove a "finally" in the section about building for release to make it feel a bit friendlier.

### CODE REVIEW

**Comment by dirk** [comment]
This should close #31149 if/when it's merged.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

Thank you!

> This should close #31149 if/when it's merged.

For future reference: github will do this automatically if you include `Closes #31159` or `Fixes #31149` in your commit message.

**Comment by dirk** [comment]
D'oh. Forgot to include the "Closes #X" syntax in the message last night. Thanks for the reminder! 😛

**Pull request merged**
