### PR TITLE
Rename `adjustment::PointerCast` and variants using it to `PointerCoercion`

### PR DESCRIPTION
**Pull request by Noratrieb**
It makes it sounds like the `ExprKind` and `Rvalue` are supposed to represent all pointer related casts, when in reality their just used to share a little enum variants. Make it clear there these are only coercions and that people who see this and think "why are so many pointer related casts not in these variants" aren't insane.

This enum was added in #59987. I'm not sure whether the variant sharing is actually worth it, but this at least makes it less confusing.

r? oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
r=me after clippy compiles again

**Comment by Nilstrieb** [comment]
Already got a conflict since yesterday
@bors p=1

**Pull request merged**
