### PR TITLE
Add forwarding impls for Read, Write, Seek to Arc, Rc

### PR DESCRIPTION
**Pull request by eholk**
This adds forwarding impls for `std::io::Read`, `std::io::Write`, and `std::io::Seek` to `alloc:sync::Arc` and `alloc::rc::Rc`. This is relevant for types such as `std::fs::File`, `std::net::TcpStream`, and `std::os::unix::UnixStream` which [implement `Read`, `Write`, and `Seek` for `&T`](https://doc.rust-lang.org/stable/std/io/trait.Read.html#impl-Read-12).

It is currently possible to do this manually through wrappers (See the "Implement a forwarding wrapper by hand" section for an example), but providing forwarding impls makes this pattern nicer to use. In some cases this can also be done with an extra reference, as shown below:

```rust
let stream = TcpStream::connect("localhost:8080");
let stream = Arc::new(stream);

&stream1.write(b"hello world")?; // OK: Read is available for &Arc<TcpStream>.
stream1.write(b"hello world")?;  // Error: Read is not available for Arc<TcpStream>.
                                 // (Enabled by this PR)
```

The reason why we want `Arc<T>: Read where &T: Read` is because this enables `Arc<T>` to be passed directly into APIs which expect `T: Read`:

```rust
fn operate<R: Read>(reader: R) {}

let stream = TcpStream::connect("localhost:8080");
let stream = Arc::new(stream);
operate(stream);  // Error: `Arc<TcpStream>` does not implement `Read`
                  // (Enabled by this PR)
```

## Implement a forwarding wrapper by hand

These trait impls do not allow anything which wasn't allowed before. Dereferencing to the inner type to get `Arc<T>: Read` to work is already possible by creating an intermediate type, as shown here:

```rust
/// A variant of `Arc` that delegates IO traits if available on `&T`.
#[derive(Debug)]
pub struct IoArc<T>(Arc<T>);

impl<T> IoArc<T> {
    /// Create a new instance of IoArc.
    pub fn new(data: T) -> Self {
        Self(Arc::new(data))
    }
}

impl<T> Read for IoArc<T>
where
    for<'a> &'a T: Read,
{
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        (&mut &*self.0).read(buf)
    }
}

impl<T> Write for IoArc<T>
where
    for<'a> &'a T: Write,
{
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        (&mut &*self.0).write(buf)
    }

    fn flush(&mut self) -> io::Result<()> {
        (&mut &*self.0).flush()
    }
}

// forward `Clone`, `Seek` as well here
```

## References

- [IO trait delegation for `Arc` blog post](https://blog.yoshuawuyts.com/io-trait-delegation-for-arc/)
- [`async-dup` crate](https://docs.rs/async-dup/latest/async_dup/)
- [`io-arc` crate](https://docs.rs/io-arc/latest/io_arc/)

Joint work with @yoshuawuyts.

### CODE REVIEW

**Review by nrc — COMMENTED** [review]
I think this is a good addition, but it desperately needs some documentation! I'm not sure where the best place for that is, but either on the types or the impls or somewhere. I think it needs explaining that these impls exist, what they allow, how they can be used, some examples, etc. There should also be comments (i.e., not user-facing docs) explaining why the bound on the impl is the way it is (why not T: Read, etc) and probably a comment explaining why these are on Arc and Rc, not &Arc and &Rc.

**Comment by eholk** [comment]
@nrc - thanks for the suggestion! I added some doc comments on the impls, which I think also does a reason for the bound, etc. Let me know if you think this is clear enough, and if not I can add more detail.

**Review by nrc — APPROVED** [review]
lgtm, thanks for the docs!

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by m-ou-se** [comment]
At first glance seems to have the same issue as pointed out here: https://github.com/rust-lang/rust/pull/94744#issuecomment-1062114580, but the implementation in this PR implicitly requires `Sized`, meaning that `T = [u8]` is not accepted.

**Comment by tbu-** [comment]
> At first glance seems to have the same issue as pointed out here: [#94744 (comment)](https://github.com/rust-lang/rust/pull/94744#issuecomment-1062114580), but the implementation in this PR implicitly requires `Sized`, meaning that `T = [u8]` is not accepted.

Sounds like this should be explicitly documented as a pitfall as `T = [u8]` is probably not the only possible `Read` etc. implementation which might have this problem.

**Comment by dtolnay** [comment]
It's not clear to me that this PR is less problematic than #94744. The relevant distinction in #94744 was whether the impls mutate the incoming reference or not, not whether the reference is fat. Ruling out fat references as done here doesn't rule out impls which work by mutating the reference, in general.

Here is one counterexample:

```rust
use std::io::{Result, Write};

#[derive(Debug)]
enum Parity {
    Even,
    Odd,
}

impl Write for &Parity {
    fn write(&mut self, buf: &[u8]) -> Result<usize> {
        if buf.iter().map(|x| x.count_ones()).sum::<u32>() % 2 == 1 {
            match self {
                Parity::Even => *self = &Parity::Odd,
                Parity::Odd => *self = &Parity::Even,
            }
        }
        Ok(buf.len())
    }

    fn flush(&mut self) -> Result<()> {
        Ok(())
    }
}

fn main() {
    let mut parity = &Parity::Even;
    write!(parity, "###").unwrap();
    println!("{:?}", parity);  // Odd
    write!(parity, "###").unwrap();
    println!("{:?}", parity);  // Even
}
```

Are we saying these impls are not always correct but still useful enough in practice to include anyway?

@rfcbot concern behavior on impls that mutate the reference

**Comment by eholk** [comment]
Thanks for the example, @dtolnay. I think that's a really clear illustration of the issue. Here's what it looks like with this PR, going through an ARC:
```rust
use std::io::{Result, Write};
use std::sync::Arc;

#[derive(Debug)]
enum Parity {
    Even,
    Odd,
}

impl Write for &Parity {
    fn write(&mut self, buf: &[u8]) -> Result<usize> {
        if buf.iter().map(|x| x.count_ones()).sum::<u32>() % 2 == 1 {
            match self {
                Parity::Even => *self = &Parity::Odd,
                Parity::Odd => *self = &Parity::Even,
            }
        }
        Ok(buf.len())
    }

    fn flush(&mut self) -> Result<()> {
        Ok(())
    }
}

fn main() {
    let mut parity = Arc::new(Parity::Even);
    write!(parity, "###").unwrap();
    println!("{:?}", parity);  // Even
    write!(parity, "###").unwrap();
    println!("{:?}", parity);  // Even
}
```
Basically, the `write!` has no effect.

This feels like the sort of thing that should require `unsafe` to make happen, although I can see why it doesn't. It definitely looks like a footgun to me.

I'd love to find a more generic way of doing this than specializing for `File`, `AsyncStream`, and every other type that makes sense here. I guess we could add something like an `InteriorMutabilityIO` marker trait to make it easier to opt in, but that seems kind of ugly too.

One argument in favor of still merging this is that it doesn't do anything users can't already do on their own. That said, I think it makes sense to avoid adding known footguns to the standard library if we can avoid it.

**Comment by m-ou-se** [comment]
> It definitely looks like a footgun to me.

@rfcbot abort

**Comment by dtolnay** [comment]
@rfcbot cancel

**Comment by WaffleLapkin** [comment]
Since the proposal was canceled, should this PR be closed?

**Pull request closed without merging**
