### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by matklad**
r? @ghost

### CODE REVIEW

**Comment by tmandry** [comment]
What's the actual reason to use rollup=never? This doesn't affect toolstate or perf, as far as I know.

**Comment by matklad** [comment]
So far, success rate for “update ra” PRs is less than 50%, so rolllups are risky. 

The last three failures were:

* fail to compile on 32bit power which doesn’t have AromicU64
* trip LLVM assertion on 32bit riscv 
* fail to compile on Linux musl, which doesn’t have Glibc function we were using

**Pull request merged**
