### PR TITLE
Fix reborrows of &mut pointers

### LINKED ISSUE #28839: How to extract static reference from Option?
I have a `static Option<&'static mut Foo>` and I want to get the reference out of it. I know this is unsafe, but I can't seem to be able to figure out how to do this. First I tried this:

```
pub trait Foo { }

static mut _foo: Option<&'static mut Foo> = None;

pub fn get_foo() -> &'static mut Foo {
    unsafe { match _foo {
            Some(x) => x,
            None => panic!(),
    } }
}
```

The types should match, but I understand I'm trying to move `x`, which gives me this error:

> ```
> src/lib.rs:21:15: 21:19 error: cannot move out of static item [E0507]
> src/lib.rs:21         match _foo {
>                             ^~~~
> src/lib.rs:22:18: 22:19 note: attempting to move value to here
> src/lib.rs:22             Some(x) => x,
>                                ^
> src/lib.rs:22:18: 22:19 help: to prevent the move, use `ref x` or `ref mut x`
>                         to capture value by reference
> ```

So then I tried to use `ref mut x` to get a mutable reference, followed by `*x` to get the object back, but that also doesn't work:

```
pub trait Foo { }

static mut _foo: Option<&'static mut Foo> = None;

pub fn get_foo() -> &'static mut Foo {
    unsafe { match _foo {
            Some(ref mut x) => *x,
            None => panic!(),
    } }
}
```

> ```
> src/lib.rs:22:32: 22:34 error: cannot move out of borrowed content [E0507]
> src/lib.rs:22             Some(ref mut x) => *x,
>                                              ^~
> ```

Finally I tried to clone or copy the `&'static mut Foo`, which also failed.

How do I fix this?

I'm using Rust 1.5.0-nightly (6108e8c3e 2015-09-28).

---

P.S. While typing this post I figured I try it on the [Rust Playground](https://play.rust-lang.org/?gist=511f1bb362245df10cd3&version=nightly). It fails to compile on nightly, but succeeds on beta and stable? (I'm writing a kernel and need the nightly features.)

### PR DESCRIPTION
**Pull request by dotdash**
Fixes #28839

### CODE REVIEW

**Comment by nikomatsakis** [comment]
r=me with comment

**Comment by Manishearth** [comment]
```
---- [compile-fail] compile-fail/borrowck-loan-of-static-data-issue-27616.rs stdout ----
	
error: unexpected compiler error or warning: '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/test/compile-fail/borrowck-loan-of-static-data-issue-27616.rs:26:5: 26:23 error: cannot assign to `*s` because it is borrowed [E0506]'
status: exit code: 101
command: x86_64-apple-darwin/stage2/bin/rustc /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/test/compile-fail/borrowck-loan-of-static-data-issue-27616.rs -L x86_64-apple-darwin/test/compile-fail/ --target=x86_64-apple-darwin -L x86_64-apple-darwin/test/compile-fail/borrowck-loan-of-static-data-issue-27616.stage2-x86_64-apple-darwin.compile-fail.libaux -C prefer-dynamic -o x86_64-apple-darwin/test/compile-fail/borrowck-loan-of-static-data-issue-27616.stage2-x86_64-apple-darwin --cfg rtopt -L x86_64-apple-darwin/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/test/compile-fail/borrowck-loan-of-static-data-issue-27616.rs:26:5: 26:23 error: cannot assign to `*s` because it is borrowed [E0506]
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/test/compile-fail/borrowck-loan-of-static-data-issue-27616.rs:26     *s = String::new(); //~ ERROR use of moved value
                                                                                                                                           ^~~~~~~~~~~~~~~~~~
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/test/compile-fail/borrowck-loan-of-static-data-issue-27616.rs:23:38: 23:39 note: borrow of `*s` occurs here
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/test/compile-fail/borrowck-loan-of-static-data-issue-27616.rs:23     let alias: &'static mut String = s;
                                                                                                                                                                            ^
error: aborting due to previous error

------------------------------------------

```

**Comment by dotdash** [comment]
@bors r=nikomatsakis d96ef0b

The test originally said `cannot assign` but was in the wrong directory. It was adjusted to accept the new, wrong error message in #28519. I reverted it back to the original check.

**Comment by dotdash** [comment]
The failure on bors looks retry worthy, but I'm also getting a pretty failure locally, which I don't know how to fix.

```
running 1 test
test [pretty] run-pass/issue-28839.rs ... FAILED

failures:

---- [pretty] run-pass/issue-28839.rs stdout ----

error: pretty-printed source does not match expected source

expected:
------------------------------------------
// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

pub struct Foo;

pub fn get_foo2<'a>(foo: &'a mut Option<&'a mut Foo>) -> &'a mut Foo {
    match foo {

        // Ensure that this is not considered a move, but rather a reborrow.
        &mut Some(ref mut x) => *x,
        &mut None => panic!(),
    }
}

fn main() { }

------------------------------------------
actual:
------------------------------------------
// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

pub struct Foo;

pub fn get_foo2<'a>(foo: &'a mut Option<&'a mut Foo>) -> &'a mut Foo {
    match foo {


        // Ensure that this is not considered a move, but rather a reborrow.
        &mut Some(ref mut x) => *x,
        &mut None => panic!(),
    }
}

fn main() { }

------------------------------------------


thread '[pretty] run-pass/issue-28839.rs' panicked at 'explicit panic', /home/bs/src/rust/src/compiletest/runtest.rs:298
```

**Comment by dotdash** [comment]
@bors r=nikomatsakis 4da796f

Marked the test to be ignored by pretty, same bug as #23623

**Pull request merged**
