### PR TITLE
Account for immutably borrowed locals in MIR copy-prop and GVN

### PR DESCRIPTION
**Pull request by cjgillot**
For the most part, we consider that immutably borrowed `Freeze` locals still fulfill SSA conditions. As the borrow is immutable, any use of the local will have the value given by the single assignment, and there can be no surprise.

This allows copy-prop to merge a non-borrowed local with a borrowed local. We chose to keep copy-classes heads unborrowed, as those may be easier to optimize in later passes.

This also allows to GVN the value behind an immutable borrow. If a SSA local is borrowed, dereferencing that borrow is equivalent to copying the local's value: re-executing the assignment between the borrow and the dereference would be UB.

r? @ghost for perf

### CODE REVIEW

**Comment by cjgillot** [comment]
Perf report: weak effect on the benchmark suite in average. Crate metadata size is reduced up to 2 %. Binary size are slightly reduced too, up to 1.9%, but with some increases.

r? @oli-obk 
cc @rust-lang/wg-mir-opt

**Review by oli-obk — APPROVED** [review]

**Comment by Zalathar** [comment]
According to https://github.com/rust-lang/rust/issues/111883#issuecomment-1560061177 that ICE test shouldn't exist either way?

It was only recently added by #122997.

**Comment by fmease** [comment]
> ⌛ Testing commit [c19866f](https://github.com/rust-lang/rust/commit/c19866f335152cbdd3424b573e5a615963dbe80e) with merge [460356f](https://github.com/rust-lang/rust/commit/460356fe8b94d18fde00d2f167653e6f33513f09)...

That's a zombie.

@bors retry for good measure

**Comment by RalfJung** [comment]
How does this treat `addr_of!(local)`? This should be treated as allowing mutation of the local via the pointer.

**Comment by pnkfelix** [comment]
> How does this treat `addr_of!(local)`? This should be treated as allowing mutation of the local via the pointer.

Did this Q from @RalfJung get addressed, @cjgillot ?

**Pull request merged**
