### PR TITLE
Only enable ConstProp on opt level >= 1

### PR DESCRIPTION
**Pull request by zeevm**
r? @JakobDegen

### CODE REVIEW

**Comment by zeevm** [comment]
Fixes #98961

**Comment by JakobDegen** [comment]
Thanks for doing this!

Implementation looks good, only thing I'd suggest is running this on opt level 1 and above instead of 2. This is in line with what we currently do and const prop actually usually helps debug info I believe (see the `ConstDebugInfo` pass or whatever it's called).

r? @oli-obk as well


If you're interested in some more things to do, following up on this by doing some deduplication between the lint and non-lint versions of this pass is definitely a good next step. There's also some good opportunities around adding support for not invalidating CFG caches to `VisitorMut` and `MirPatch` - open a topic on Zulip if you're interested.

**Comment by zeevm** [comment]
Thanks Jakob, changed to opt level 1.

Will look into those 2 issues next.

**Comment by klensy** [comment]
Current title is wrong, it should be >= 1, not == 2?

**Comment by zeevm** [comment]
Should I squash the commits or will it happen when the PR completes?

**Comment by bjorn3** [comment]
Bors doesn't squash commits. Squashing is fine. I can re-approve it after you squash if you do it within the next 5 min or so. Otherwise keeping the commits separate is fine.

**Comment by klensy** [comment]
> Should I squash the commits or will it happen when the PR completes?

There is no auto squash.

**Comment by zeevm** [comment]
> Bors doesn't squash commits. Squashing is fine. I can re-approve it after you squash if you do it within the next 5 min or so. Otherwise keeping the commits separate is fine.

that's fine, I'll leave it as is.

I thought I had to squash it to complete the PR.

**Pull request merged**
