### PR TITLE
Rename ClosureKind variants and stop re-exporting them.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by oli-obk** [comment]
the commit message needs a `[breaking-change]`

**Comment by nikomatsakis** [comment]
I'm not convinced this sort of change out to be tagged with `[breaking-change]`. It's one thing to tag changes to libsyntax which (unfortunately, in my view) has a kind of "semi-stable" status, but the internals of rustc don't fall in that category.

**Comment by oli-obk** [comment]
it's reachable from late lints, I just assumed that any change observable from plugins would require the mark so we can find the commits easily

**Comment by Ms2ger** [comment]
I can see the argument for including it, but I haven't done that with similar changes I made earlier. Happy to go either way.

**Comment by eddyb** [comment]
Pretty! @bors r+

**Pull request merged**
