### PR TITLE
Add functions for converting IP to int and back

### PR DESCRIPTION
**Pull request by achanda**
Still haven't figured out how to do this for IPv6 properly

### CODE REVIEW

**Comment by nagisa** [comment]
This impl won’t work for Windows.

**Comment by Diggsey** [comment]
What about just providing an iterator over bytes? That will work seamlessly for both IPv4/IPv6 and seems to be what other libraries do (eg. .net)

**Comment by alexcrichton** [comment]
Could you expand on the rationale for this a bit as well? For example this should be possible via the existing constructors/`octets` method.

**Comment by achanda** [comment]
@alexcrichton I do not have anything very concrete, this looks like a bad idea in hindsight. I will work on using the octets to do this.

**Comment by alexcrichton** [comment]
Ok, thanks for the PR anyway @achanda!

**Pull request closed without merging**
