### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #39859, #39864, #39886, #39892, #39914, #39940, #39988, #40010, #40024, #40030
- Failed merges:

### CODE REVIEW

**Comment by cramertj** [comment]
@GuillaumeGomez This is failing because someone else added the error code I used in #39864. Is there a way to prevent that from happening?

**Comment by cramertj** [comment]
@GuillaumeGomez Should I force push with a new error code or just add another commit changing it?

**Comment by frewsxcv** [comment]
@cramertj When you have time, add a new commit to your branch that fixes the 'tidy' issue Travis encountered. If you need help with that, let us know

**Comment by cramertj** [comment]
@frewsxcv done.

**Pull request closed without merging**
