### PR TITLE
Update RELEASES.md after destabilization of non_modrs_mods

### PR DESCRIPTION
**Pull request by emilyalbini**
Backports the release notes update from stable to master.

r? @ghost

### CODE REVIEW

**Comment by kennytm** [comment]
Beta-nominating, this item exists on beta branched 2 days ago as well.

**Comment by pietroalbini** [comment]
There is no need to backport this to beta, since the current beta branch is the 1.30 one. Master will be promoted to beta in the weekend.

**Comment by kennytm** [comment]
Oh so beta is delayed 😐

**Pull request merged**
