### PR TITLE
Rename some crates and modules in the frontend

### PR DESCRIPTION
**Pull request by petrochenkov**
Migrate from `syntax_*` naming scheme to `rustc_*`.
See https://github.com/rust-lang/rust/pull/65324#issuecomment-551103396 and several comments below.

Renamed crates:
`syntax_expand` -> `rustc_expand`
`syntax_pos` -> `rustc_span` ([motivation](https://github.com/rust-lang/rust/pull/65324#issuecomment-552173320))
`syntax_ext` -> `rustc_builtin_macros`

Also one module in resolve is renamed for consistency and to avoid tautology.

r? @Centril

### CODE REVIEW

**Comment by petrochenkov** [comment]
TODO: Rename `syntax_pos` to `rustc_span` in source code. It's some big churn which is better done in a separate PR.

**Comment by petrochenkov** [comment]
cc @eddyb

**Comment by Centril** [comment]
> TODO: Rename `syntax_pos` to `rustc_span` in source code. It's some big churn which is better done in a separate PR.

Ideally that should be done soon tho because the new directory in the filesystem with the old crate name in code becomes confusing.

@bors r+

**Pull request merged**
