### PR TITLE
Add #[track_caller] to panicking Vec functions 

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Rework of #79323
(opened #83359 on rust-lang remote instead of my fork, so decided to create a new one instead)

r? @joshtriplett

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
merging as per [comment](https://github.com/rust-lang/rust/pull/83359#issuecomment-812739031) 

@bors r=joshtriplett

**Comment by the8472** [comment]
There have been some additional optimizations to some of those methods in the last few weeks and they are highly sensitive to perturbations, so another perf run might make sense.

**Comment by Dylan-DPC** [comment]
fair enough 

@bors r-
@bors try @rust-timer queue

**Comment by the8472** [comment]
Looks like there actually are fewer regressions compared to the run in #83359

**Comment by Dylan-DPC** [comment]
@bors r- 

oops forgot a few places

**Comment by the8472** [comment]
But those were in the previous PR? That could explain why there were fewer regressions.

**Comment by estebank** [comment]
Should this PR add a test to catch any potential regressions in the panic behavior?

**Comment by JohnCSimon** [comment]
merge conflicts

**Comment by Dylan-DPC** [comment]
closing this for the moment. will rework it later when I have the time for it

**Pull request closed without merging**
