### PR TITLE
Make unchecked_{add,sub,mul} inherent methods unstably const

### PR DESCRIPTION
**Pull request by clarfonthey**
The intrinsics are marked as being stably const (even though they're not stable by nature of being intrinsics), but the currently-unstable inherent versions are not marked as const. This fixes this inconsistency. Split out of #85017,

r? @oli-obk

### CODE REVIEW

**Comment by clarfonthey** [comment]
Added tracking issue for both the methods and the const-ness; figured it didn't make sense to have separate issues for them.

**Comment by oli-obk** [comment]
from the CI failure I'm guessing we already have a tracking issue for the methods' feature gate?

**Comment by clarfonthey** [comment]
Nope, it was a method on `Step`. I modified the tidy lint to make it easier to find.

**Comment by oli-obk** [comment]
Nice!

@bors r+

**Pull request merged**
