### PR TITLE
Enable profiler in dist-powerpc64-linux

### PR DESCRIPTION
**Pull request by ecnelises**

### CODE REVIEW

**Comment by Kobzol** [comment]
Hi, could you please provide a bit of context to this PR, like why was this change made? Thanks! :)

**Comment by ecnelises** [comment]
Hi, this is from https://github.com/briansmith/ring/issues/1679 . I'd like to add profiler builtin to CI build of powerpc64-linux (and powerpc-linux). Since powerpc64le-linux and other mainstream targets already have `--enable-profiler` in build flags, this will not bring maintainance burden I think.

I verified it from a cross build from x86_64-linux to powerpc64-linux and it generates LLVM profdata as expected.

**Comment by Kobzol** [comment]
Oh, I see that it's indeed already enabled for `le` PowerPC. Then this is fine. Feel free to send another PR for `powerpc` if you also need it.

@bors r+ rollup

**Comment by ecnelises** [comment]
Thanks!

**Pull request merged**
