### PR TITLE
Inline try_get_cached

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by jyn514** [comment]
context: https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/triage.202021-02-16/near/226566351

**Comment by cjgillot** [comment]
I guess we found the guilty party.
@bors r+

**Comment by jyn514** [comment]
```
Run src/ci/scripts/install-awscli.sh
Reading package lists...
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/storage.googleapis.com_bazel-apt_dists_stable_jdk1.8_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```
Seems spurious? cc @rust-lang/infra 

@bors retry

**Pull request merged**
