### PR TITLE
Add missing urls and few local rewrites

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @steveklabnik

### CODE REVIEW

**Comment by oli-obk** [comment]
tidy found some broken links:

```
core/iter/trait.Iterator.html:924: broken link fragment  `#tymethod.iter` pointing to `core/iter/trait.Iterator.html`

std/iter/trait.Iterator.html:924: broken link fragment  `#tymethod.iter` pointing to `std/iter/trait.Iterator.html`
```

**Comment by frewsxcv** [comment]
Linkcheck stage2 (x86_64-unknown-linux-gnu)
core/iter/trait.Iterator.html:924: broken link fragment  `#tymethod.iter` pointing to `core/iter/trait.Iterator.html`
std/iter/trait.Iterator.html:924: broken link fragment  `#tymethod.iter` pointing to `std/iter/trait.Iterator.html`

**Comment by GuillaumeGomez** [comment]
All good! :)

**Comment by frewsxcv** [comment]
Looks good, thanks! :sparkles:

@bors r+ rollup

**Pull request merged**
