### PR TITLE
Implement VEC_NEW internal lint

### PR DESCRIPTION
**Pull request by flip1995**
And another one. That was an easy one to implement, but the fallout was pretty big. Thanks to regex (`s/([\(\s])Vec::new()/\1vec![]/g`) this was quite pleasant to fix :)

cc https://github.com/rust-lang/rust/issues/49509#issuecomment-496813637

r? @oli-obk

### CODE REVIEW

**Comment by petrochenkov** [comment]
Seriously?
Why?

**Comment by flip1995** [comment]
I guess for consistency? 

But as stated above: This was easy to implement and not really much work to fix the fallout. We can throw this on the pile of internal lints, that didn't make it, no harm done. :)

**Comment by Mark-Simulacrum** [comment]
I'd be interested in knowing whether this has an impact on compilation times, as it leads to macro expansion occurring -- which internally will still call `Vec::new` or equivalent.

Maybe it makes sense to do the opposite or nothing here?

**Comment by flip1995** [comment]
The macro expands to `<[_]>::into_vec(box [])`, which is implemented here: 

https://github.com/rust-lang/rust/blob/85a360e0ea2f1629b8851e7c9b2903bbdbab42bf/src/liballoc/slice.rs#L145-L152

`Vec::new` calls `RawVec::new()` directly, which then has just a call to `Unique::empty()`. So I guess the `Vec::new` should be faster? (Maybe I should have checked this before implementing the lint. Well ¯\\\_(ツ)_/¯)

But if this is the case, wouldn't it make sense to add a special case for `vec![]` to the macro?

**Comment by Mark-Simulacrum** [comment]
Note, I don't mean the runtime cost -- I expect that to be equivalent -- I mean purely the macro parsing/expansion overheads. I don't think these are significant; but, well, if we're going to ban `Vec::new()` in favor of `vec![]` we should probably know :)

**Comment by flip1995** [comment]
> Note, I don't mean the runtime cost -- I expect that to be equivalent

Oh yeah of course. It's late here

Is there some way I can benchmark the compile times?

**Comment by Xanewok** [comment]
I actually looked for a similar lint in the Clippy and couldn't find it (to prefer `Vec::new`, however) - maybe it'd make sense for it to be a regular allow-by-default style Clippy lint?

**Comment by oli-obk** [comment]
cc @eddyb

**Comment by eddyb** [comment]
I prefer this but we should have some discussion and find some consensus.

@petrochenkov I would also prefer to avoid macros if we had a way to make `Vec::new(a, b, c)` work instead of `vec![a, b, c]` - it's longer, but we wouldn't have needed `vec!` in the first place I don't think.

As it stands, `vec![a, b, c]` to me is just a weird `[a, b, c].into()` (which maybe we should use const generics to make possible, and switch to? but unlike `vec!` it can't write the values in-place, sadly)

**Comment by petrochenkov** [comment]
@eddyb 
My logic is that vectors created with non-zero number of elements are not common outside of "examples" - tests / docs / comments (and even in examples they are often used [unnecessarily](https://github.com/rust-lang/rust/pull/22623)).
So, it's ok if they stick out.
Empty vectors *are* common, so they are better written in consistent style with code surrounding them, rather than with non-zero element vectors somewhere else.

**Comment by scottmcm** [comment]
Why does the compiler want it this way?  There's no justification in https://github.com/rust-lang/rust/issues/49509#issue-310061927

**Comment by joelpalmer** [comment]
Ping from Triage. Is any more review forthcoming or should this be back in the author's hands? @flip1995 @oli-obk @Mark-Simulacrum @eddyb

**Comment by flip1995** [comment]
I don't think we find a consensus here. I think this should be discussed in #49509 first and then picked up again.

**Pull request closed without merging**
