### PR TITLE
Add regression tests for #13727.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/13727.

### CODE REVIEW

**Comment by brson** [comment]
Seems like  src/test/compile-fail/issue-13727-2.rs  *must* be covered elsewhere in the test suite. The other test looks fine since it captures what the compiler actually does.

But is this the behavior we would actually expect from match patterns that are out of range? Do we actually guarantee that integers wrap at compile time (when we don't at runtime)?

**Comment by durka** [comment]
The first one may be covered by `compile-fail/enum-discrim-autosizing.rs`.

**Comment by brson** [comment]
It's also covered issue-15524. Can you remove the redundant test? r=me otherwise.

**Comment by frewsxcv** [comment]
> Can you remove the redundant test?

Done.

**Pull request merged**
