### PR TITLE
Bump Unicode to version 16.0.0

### PR DESCRIPTION
**Pull request by Marcondiro**
[Unicode 16.0.0 is out!](https://www.unicode.org/versions/Unicode16.0.0/)
This PR updates Unicode data embedded in `core`.

### CODE REVIEW

**Comment by Kobzol** [comment]
Let's see the binary size impact.

@bors try @rust-timer queue

**Comment by Noratrieb** [comment]
r? Manishearth

**Comment by Marcondiro** [comment]
Maybe `A-unicode` and `relnotes` tags should be added,
thanks

**Pull request merged**
