### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #38138, #38310, #38581, #38607, #38617, #38623, #38629, #38664, #38799, #38815, #38816
- Failed merges:

### CODE REVIEW

**Comment by pnkfelix** [comment]
Hmm, it seems I screwed up my fix to #38617 ; I recognize that old use of `token::intern` (that I think needs to become `Symbol::intern`).

I thought I had pushed the corrected version but obviously I did not.

**Comment by pnkfelix** [comment]
Aha: I *did* push a corrected commit: b8669dff556a03ca37b39cbb81be65c94d24defe

but bors interpreted my r+ here: https://github.com/rust-lang/rust/pull/38617#issuecomment-270419309 as if it was referring to 98218b3141802512f99f2e59f3ca8438ffc4814e (again!)

**Comment by sanxiyn** [comment]
Pull requests other than #38617 and #38629 are now merged. Closing.

**Pull request closed without merging**
