### PR TITLE
Normalize bounds fully when checking defaulted types

### LINKED ISSUE #73818: Regression in associated type checking for default impls
So I had a trait system in my (nightly) code for a while now that utilized specialization, but it no longer seems to be working after a recent update:

```rust
#![feature(specialization)]

trait Trait1 { type Selection: PartialEq; }

trait Trait2: PartialEq<Self> {}
impl<T:Trait2> Trait1 for T { default type Selection = T; }
```
```
warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/main.rs:1:12
  |
1 | #![feature(specialization)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information

error[E0277]: can't compare `T` with `<T as Trait1>::Selection`
 --> src/main.rs:6:31
  |
3 | trait Trait1 { type Selection: PartialEq; }
  |                -------------------------- required by `Trait1::Selection`
...
6 | impl<T:Trait2> Trait1 for T { default type Selection = T; }
  |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `T == <T as Trait1>::Selection`
  |
  = help: the trait `std::cmp::PartialEq<<T as Trait1>::Selection>` is not implemented for `T`
help: consider further restricting this bound
  |
6 | impl<T:Trait2 + std::cmp::PartialEq<<T as Trait1>::Selection>> Trait1 for T { default type Selection = T; }
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.
```

Now, I haven't been following the development of the specialization feature too closely, so it _is_ possible that this is somehow actually intended and I am missing something. However, given that this previously compiled and ran just fine a couple weeks ago and given that the specialization incomplete warning was only added recently, I am inclined to think that it is probably a regression of some sort.

### Meta things

compiler version:
```
$rustc --version --verbose
rustc 1.46.0-nightly (7750c3d46 2020-06-26)
binary: rustc
commit-hash: 7750c3d46bc19784adb1ee6e37a5ec7e4cd7e772
commit-date: 2020-06-26
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

### PR DESCRIPTION
**Pull request by tmandry**
When checking that the default type for `<T as X>::Y` is valid in this example:

```
trait X { type Y: PartialEq<<Self as X>::Y> }
impl X for T { default type Y = S; }
```

We will have to prove the bound `S: PartialEq<<T as X>::Y>`. In this case
we want `<T as X>::Y` to normalize to `S`. This is valid because we are
checking the default value specifically here. Add `<T as X>::Y = S` to the
ParamEnv for normalization _of the bound we are checking_ only.

Fixes #73818.

---

I noticed that adding this to the env for bounds checking didn't break any tests. Not sure if this is because we can't rely on it to prove anything, or because of missing test coverage.

r? @matthewjasper, @nikomatsakis

### CODE REVIEW

**Comment by tmandry** [comment]
Friendly ping, can I get a review?

**Comment by matthewjasper** [comment]
Can you try replacing the value of `concrete_ty_predicate` (line 1277) with `predicate.subst(tcx, rebased_substs)`. Most of the code there is manually normalizing things that should now be normalizable using the additional predicate.

**Comment by tmandry** [comment]
That worked!

Note that I now add the predicate unconditionally (removing the branch on `is_final()`) to avoid regressing an error message for a GAT outlives bound. Details are in the commit history.

**Pull request merged**
