### PR TITLE
Always print '_, even for erased lifetimes.

### PR DESCRIPTION
**Pull request by cjgillot**
Explicit lifetime arguments are now the recommended syntax in rust 2018 and rust 2021.  This PR applies this discipline to rustc itself.

### CODE REVIEW

**Comment by eholk** [comment]
r+

**Comment by eholk** [comment]
Ah, looks like a few more tests still need blessed, but you can r=me after they're passing.

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/102126)

**Comment by aliemjay** [comment]
> Explicit lifetime arguments are now the recommended syntax in rust 2018 and rust 2021.

I wonder if this if this is true in the `ValueNS` as well? I guess the convention there is to not . I mean I probably see `some_fn::<T>()` more than `some_fn::<'_, T>("")`.

**Comment by ChrisDenton** [comment]
It just needs the src/tools/miri test to be updated:

```
--- tests/fail\concurrency\windows_join_detached.stderr
+++ <stderr output>
... 8 lines skipped ...
    = note: BACKTRACE:
    = note: inside `std::sys::PLATFORM::thread::Thread::join` at RUSTLIB/std/src/sys/PLATFORM/thread.rs:LL:CC
~   = note: inside `std::thread::JoinInner::<'_, ()>::join` at RUSTLIB/std/src/thread/mod.rs:LL:CC
    = note: inside `std::thread::JoinHandle::<()>::join` at RUSTLIB/std/src/thread/mod.rs:LL:CC
 note: inside `main` at $DIR/windows_join_detached.rs:LL:CC
... 10 lines skipped ...
```

**Comment by saethlin** [comment]
I think you just need to run `./miri bless` then check in the diff.

**Comment by cjgillot** [comment]
@saethlin How do I run `./miri bless` from `x.py`?  Are there docs for this with the subtree?

**Comment by saethlin** [comment]
That would probably be a question for @oli-obk, I've never operated the Miri tests from `x.py`.

**Comment by RalfJung** [comment]
> How do I run ./miri bless from x.py? Are there docs for this with the subtree?

`./x.py test src/tools/miri --stage 0 --bless` -- except currently you have to use `--stage 1` due to a cargo bug (https://github.com/rust-lang/cargo/issues/11138).

I don't think we have those docs yet, where should they usually go?

**Pull request merged**
