### PR TITLE
CloneToUninit impls

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
As per #126799.

Also implements it for `Wtf8` and both versions of `os_str::Slice`.

Maybe it is worth to slap `#[inline]` on some of those impls.

r? @dtolnay

### CODE REVIEW

**Comment by workingjubilee** [comment]
> Maybe it is worth to slap `#[inline]` on some of those impls.

Yes.

**Comment by GrigorenkoPV** [comment]
> > Maybe it is worth to slap `#[inline]` on some of those impls.
> 
> Yes.

Which ones though?

**Comment by workingjubilee** [comment]
probably at least str?

**Comment by GrigorenkoPV** [comment]
> probably at least str?

Well, it goes kinda like this
```mermaid
graph LR;
    str-->u8["[u8]"]
    CStr-->u8
    Path-->OsStr
    OsStr-->Slice
    Slice-->|Windows/UEFI|Wtf
    Wtf-->u8
    Slice-->|Other platforms|u8
```

Each edge here is a trivial delegation[^1], so I guess it's either all `#[inline]` or none `#[inline]`?

[^1]: except for `CStr` -> `u8` in future, maybe. Right now `CStr` is a fat `[u8]` pointer with length, so delegation is trivial, but according to comments, there is a desire to make is a thin pointer (for ffi reasons), then the size would have to be calculated a-la `strlen(3)`.

**Comment by workingjubilee** [comment]
LLVM's inlining flow reverses those arrows.

**Comment by GrigorenkoPV** [comment]
> LLVM's inlining flow reverses those arrows, so LLVM will decide whether to inline from e.g. `[u8]` to `str` first.

So should I add `#[inline]` only for `str`, or for `Wtf8`, `Path`, `OsStr`, etc. too?

**Comment by workingjubilee** [comment]
Probably need to be added to `[T]` first.

**Comment by GrigorenkoPV** [comment]
I have pushed a commit that adds `#[doc(hidden)]` to `<T: Copy>` specializations (as per https://github.com/rust-lang/rust/issues/126799#issuecomment-2185754872) and `#[inline(always)]` to all `Unsized` folks except for `CStr`.

I have a feeling I am wrong about some or all of those.

**Comment by workingjubilee** [comment]
`inline(always)` is generally overdoing it.

**Comment by workingjubilee** [comment]
Hmm, I should have just referenced https://std-dev-guide.rust-lang.org/policy/inline.html from the beginning. I had forgotten it exists. Sorry about that.

**Comment by GrigorenkoPV** [comment]
I have force-pushed (twice).

First time changing `#[inline(always)]` to `#[inline]`.

Second time is a bit more interesting. Aside from rebasing on top of master (and swapping places of short `#[inline]` and long `#[cfg_attr(debug_assertions, track_caller)]` to please OCD), I have went ahead and done what https://github.com/rust-lang/rust/issues/126799#issuecomment-2186002850 suggests, i.e. moving specialization to a private trait. This has an additional benefit of no longer needing any `#[doc(hidden)]` to shove implementation details under the rug.

**Comment by GrigorenkoPV** [comment]
Sorry, had a bit of a skill issue with rustdoc, here go two more force-pushes

**Review by dtolnay — APPROVED** [review]
Thank you!

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

This PR has the immediate, stable consequence that [`Rc::make_mut`](https://doc.rust-lang.org/nightly/std/rc/struct.Rc.html#method.make_mut) and [`Arc::make_mut`](https://doc.rust-lang.org/nightly/std/sync/struct.Arc.html#method.make_mut) become usable with `Rc<str>`, `Rc<CStr>`, `Rc<OsStr>`, `Rc<Path>` and `Arc<_>` of the same 4 dynamically sized types.

All of these types are real types that are constructible via a variety of `From` and `Default` impls.

```rust
impl Default for Rc<str>;
impl From<String> for Rc<str>;
impl From<&str> for Rc<str>;

impl Default for Rc<CStr>;
impl From<CString> for Rc<CStr>;
impl From<&CStr> for Rc<CStr>;

impl From<OsString> for Rc<OsStr>;
impl From<&OsStr> for Rc<OsStr>;

impl From<PathBuf> for Rc<Path>;
impl From<&Path> for Rc<Path>;

// and all the same for Arc
```

After using `make_mut` to obtain a `&mut T`, the caller can go on to use APIs such as [`Path::as_mut_os_str`](https://doc.rust-lang.org/1.79.0/std/path/struct.Path.html#method.as_mut_os_str), [`OsStr::make_ascii_lowercase`](https://doc.rust-lang.org/1.79.0/std/ffi/struct.OsStr.html#method.make_ascii_lowercase), [`str::as_mut_bytes`](https://doc.rust-lang.org/1.79.0/std/primitive.str.html#method.as_bytes_mut), [`str::split_at_mut`](https://doc.rust-lang.org/1.79.0/std/primitive.str.html#method.split_at_mut).

Separately, this PR unblocks an upcoming change to reconcile the set of types usable with `Box::clone` and `Rc::make_mut` and `Arc::make_mut`. It makes sense having all those 3 methods support the same set of types, and shouldn't require 3 separate trait impls for each of our dynamically sized types. All 3 do basically the same thing with their generic inner type: create an allocation of the right size and clone the existing dynamically sized value into it.

**Comment by joshtriplett** [comment]
Verifying: there is no proposal to stabilize `CloneToUninit` itself, right?

**Comment by dtolnay** [comment]
Not currently. It may or may not happen later, in the current form or a different one.

**Comment by GrigorenkoPV** [comment]
This is quite sad that we have to manually implement this for every memcpy'able !Sized type.

Unfortunately `Copy: Clone` & `Clone: Sized` at the moment, so we cannot just do a blanket `impl<T: ?Sized+Copy> CloneToUninit for T`, which would have an additional benefit of working for user-defined !Sized types too.

Maybe it would make sense to do something like https://smallcultfollowing.com/babysteps/blog/2024/06/21/claim-auto-and-otherwise/#is-this-revisiting-rfc-936
> The real goal should be to disconnect “can be memcopied” and “can be automatically copied”



The most difficult part of making this entire thing easier and more pleasing is probably the CStr type, which we eventually want to be `!Sized` but have a thin pointer. But let's not think about this just yet.


Anyways, this all sounds like `CloneToUninit` begs to be renamed to `CloneUnsized`. Not sure if we actually want to make it a supertrait for `Clone`. Probably not, because it would make it annoying to derive things.

It also feels like `Memcpyable` to `CloneToUninit` is what `Copy` is to `Clone`. It's just the `?Sized` versions of those two.


Finally, I feel like this all just brings more light to the issue that we have with `Copy: Clone` & `Ord: PartialOrd` right now, and might start to have with `Clone: CloneToUninit` or `Memcpyable: CloneToUninit` in the future. Which is, sometimes we have `Subtrait: Supertrait` and then we want to have a canonical implementation like
```rust
impl <T: Copy> Clone for T {
    fn clone(&self) -> Self {
        *self
     }
}
```
or
```rust
impl <T: ?Sized, U: ?Sized> PartialOrd<U> for T
where
  T: Ord<U>,
{
    fn partial_cmp(&self, other: &U) -> Option<Ordering> {
        Some(<T as Ord<U>>::cmp(self, other))
    }
}
```
but we can't, because this is not how the language works.

Maybe it would be possible to introduce a thing like that to the language's type system? Maybe there has already been a failed RFC that I'm just unaware about?

Because if this works, it means we can add new supertraits without much trouble, and derives become way easier.

Just imagine, `#[derive(Ord)]` instead of `#[derive(Ord, PartialOrd, Eq, PartialEq)]`, or `#[derive(Copy)]` instead of `#[derive(Copy, Clone)]`.


Anyways, pardon my incoherent ramblings, but I just felt like I had to get this off of my chest.

**Comment by GrigorenkoPV** [comment]
Sigh, it is more complicated than I thought. (I mean the `impl<T: Subtrait> Supertrait for T` stuff)

```mermaid
flowchart TD
    CloneToUninit ==> Memcpyable & Clone ==> Copy
    Sized -.-> Clone
    PartialEq ==> Eq & PartialOrd ==> Ord
```

The thick edges here are the ones where we would potentially want to make a blanket implementation for supertrait based on subtrait. Sadly, they for a diamond. So how do we get a `PartialEq` from `Ord`? Through `PatialOrd` or through `Eq`? Or we do something like C's `inline` that tells the compiler "assume they are the same"?

**Comment by GrigorenkoPV** [comment]
While working on #128137, I've realized that while it seems to be *always* fine to impl Partial{Ord,Eq} via {Ord, Eq}, it is not so for (Partial)Eq via (Partial)Ord. For example: lexicographical order of variable-length slices. For equality, different lengths are enough to draw a conclusion (the slices are unequal), but for order we need to actually read the data in any case.

So, for `impl<T: Subtrait> Supertrait for T`
```mermaid
flowchart TD
    PartialEq == trivial ==> Eq
    PartialOrd == trivial ==> Ord 
    PartialEq -. not trivial .-> PartialOrd
    Eq -. not trivial .-> Ord 
```

That solves the diamond problem for this case.

**Review by dtolnay — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
perf regression looks likely to be within noise thresholds, though driven by bimodality that our automatic noise removal doesn't cope well with.

**Pull request merged**
