### PR TITLE
Rename Pin to PinMut, and some more breaking changes

### PR DESCRIPTION
**Pull request by RalfJung**
As discussed at [1] §3 and [2] and [3], a formal look at pinning requires considering a distinguished "shared pinned" mode/typestate.  Given that, it seems desirable to at least eventually actually expose that typestate as a reference type.  This renames Pin to PinMut, freeing the name Pin in case we want to use it for a shared pinned reference later on.

[1] https://www.ralfj.de/blog/2018/04/10/safe-intrusive-collections-with-pinning.html
[2] https://github.com/rust-lang/rfcs/pull/2349#issuecomment-379250361
[3] https://github.com/rust-lang/rust/issues/49150#issuecomment-380488275

Cc @withoutboats

### CODE REVIEW

**Comment by withoutboats** [comment]
r? @withoutboats

There are a few other breaking changes I'd like to see made to these APIs, and probably it makes sense to do them in the same merge. I could build off this, or you could if you're interested in @RalfJung. The main thing is changing the methods that currently take `&mut Pin` to take just `PinMut`, like `map` and I think a few others.

**Comment by RalfJung** [comment]
> The main thing is changing the methods that currently take &mut Pin to take just PinMut, like map and I think a few others.

I actually already have this prepared for `map`, just pushed that to this branch.

The only other candidate I can think of is `get_mut`. Did you have others in mind?

**Comment by withoutboats** [comment]
I think `get_mut` was the other, thanks!

**Comment by withoutboats** [comment]
calling it `reborrow` seems good.

**Comment by RalfJung** [comment]
Done.

**Comment by withoutboats** [comment]
@bors r+

cc @cramertj

**Comment by cramertj** [comment]
This LGTM, although I'd really like to solidify what `Pin` gives you v.s. `&PinMut`. If I really can't rely on `&PinMut` and `Pin` providing similar guarantees, then I think we should add `Pin` ASAP, as I need it for a small handful of things.

**Comment by RalfJung** [comment]
> This LGTM, although I'd really like to solidify what Pin gives you v.s. &PinMut. If I really can't rely on &PinMut and Pin providing similar guarantees

I'd think (but did not check in my model yet) that you can deref an `&'a PinMut<'b, T>` into a `Pin<'a, T>`.

**Comment by cramertj** [comment]
@RalfJung I'm confused-- to me it seems like that conflicts with your previous statements about `&` and `&Pin(Mut)` being equivalent.

**Comment by RalfJung** [comment]
Those statements (IIRC) were made under the assumption that the model does not have a "shared pinned" typestate. I have two models of all of this in my head:

1. Without "shared pinned". In this model, we can safely transmute between `&PinMut<T>` and `&&T`; shared references "forget" about pinning. I don't see a good reason for having shared pinned references in this model, they are not useful for e.g. intrusive collections.
2. With "shared pinned". Nobody likes model 1 because nobody thinks these transmutes should be legal and there is no other benefit. In this model, the transmute is *not* legal, and it makes sense to have a reference type that exposes this "shared pinned" typestate. This is the model I am assuming we will actually use, which is the reason I wrote this RFC.

**Comment by cramertj** [comment]
@RalfJung Ah, I was always assuming that we had "shared pinned" as a valid typestate-- that explains why I was so confused by your post on the subject. I never questioned that the typestate should exist, but rather whether it was necessary to include a built-in type for it (rather than just using `&Pin`).

**Comment by pythonesque** [comment]
@cramertj &Pin is *really* annoying to work with since you can't do field projections with it (because you need to get an `&&T` to the field somehow).

**Comment by RalfJung** [comment]
@cramertj Also see https://github.com/rust-lang/rust/issues/49150#issuecomment-381583720 where I essentially wrote what @pythonesque said above (I think @comex was the first to make this observation).

**Comment by cramertj** [comment]
You're both right, of course, and I've changed my mind after using it in practice :smile:

**Pull request merged**
