### PR TITLE
[beta] Update cargo

### PR DESCRIPTION
**Pull request by ehuss**
2 commits in 4f74d9b2a771c58b7ef4906b2668afd075bc8081..149022b1d8f382e69c1616f6a46b69ebf59e2dea
2020-07-08 17:13:00 +0000 to 2020-07-17 16:39:39 -0400
- [beta] Revert "Improve support for non-`master` main branches" (rust-lang/cargo#8503)
- [beta] Avoid colliding with older Cargo fingerprint changes (rust-lang/cargo#8488)

### CODE REVIEW

**Comment by ehuss** [comment]
@Mark-Simulacrum It looks like maybe #74406 needs to be backported to the beta branch.  Should I just include that in this PR, or do you want to do it? Or a separate PR and then roll them up together?  Let me know if I can help.

**Comment by Mark-Simulacrum** [comment]
Yeah, if you can include that here that'd be great. Alternatively you can just leave this and I can get to it in a few days, I usually do beta backports on Fridays/the weekend.

**Comment by ehuss** [comment]
OK, I have included #74406 and #74418 to fix CI.  

@bors r=Mark-Simulacrum

**Comment by Manishearth** [comment]
@bors retry yield

(p>5 if you want this landed quickly)

**Pull request merged**
