### PR TITLE
[Windows] Enable building rustc with "pthreads" flavor of mingw.

### PR DESCRIPTION
**Pull request by vadimcn**
Tested on mingw-w64 packaged with msys2.  

r? @alexcrichton

cc #40123

### CODE REVIEW

**Comment by alexcrichton** [comment]
r+ from me!

Let's see if we can land https://github.com/rust-lang/rust/pull/40524 though to rebase out the original commit (that PR has had some fixes/revisions as well)

**Comment by alexcrichton** [comment]
er, land that first though*

**Comment by TimNN** [comment]
I think the appveyor config still needs to be adjusted -- either to remove the custom mingw downloads or to replace the mingw downloads with the pthread versions (to make us independent from changes to the appveyor build environment).

**Comment by alexcrichton** [comment]
Ideally I'd actually prefer if we didn't have to change the toolchain because that would signify a large breaking change that'd be much more difficult to deal with. I think @vadimcn said though that the dll/staticlib were present in both toolchains, they'd just be ignored on the win32 threading one I think.

**Comment by TimNN** [comment]
Mh, wasn't the whole point of this that we could switch to the pthread toolchains, because they implement `std::thread` (which is currently needed for LLVM 4.0)?

**Comment by alexcrichton** [comment]
Ah true yes, we'll want to switch compiling the compiler to the pthreads toolchain. I'd like to see if this lands alone though because we should continue to be able to work with a win32 toolchain. Maybe one day we can add a bot for that but in the meantime we just need to make sure there's a transition path for win32 toolchain users to the pthread toolchain.

At the very least we can land the pthread compiler change for rustc in the llvm 4.0 PR, but I'd also be fine with a separate pr (after this one) to do that change independently.

**Comment by alexcrichton** [comment]
@bors: retry

* ar.exe error https://github.com/rust-lang/rust/issues/40546

**Comment by alexcrichton** [comment]
@bors: retry

* openssl failed to build https://github.com/rust-lang/rust/issues/40417

**Comment by alexcrichton** [comment]
@bors: retry

* sccache failue https://github.com/rust-lang/rust/issues/40240

**Comment by vadimcn** [comment]
Another sccache failure?

**Comment by TimNN** [comment]
Looks like it :(

```
ERROR:sccache::server: [Error(Msg("failed to spawn child"), State { next_error: Some(Error { repr: Os { code: 32, message: "Broken pipe" } }) })] 	lli.cpp.o
ERROR:sccache::server: [Error { repr: Os { code: 32, message: "Broken pipe" } }] 	lli.cpp.o
```

**Comment by alexcrichton** [comment]
@bors: retry

* spurious musl segfault https://github.com/rust-lang/rust/issues/38618

**Comment by TimNN** [comment]
@bors retry

* #40546

**Comment by alexcrichton** [comment]
This PR caused a few regression such as https://github.com/rust-lang/rust/issues/41416 and https://github.com/rust-lang/rust/issues/41607 so tagging relnotes at least. We haven't reverted yet and if we end up not doing so we'll want to mention this in compatibility nodes, namely:

* Tweaking the link order of local static/dynamic libraries (respecting the order on given rather than having the compiler reorder)
* Tweaking how MinGW is linked, so native code linked to dynamic libraries may require manually linking the gcc support library (for the native code itself)

**Pull request merged**
