### PR TITLE
Bump to 1.20.0 and update stage0 compiler

### PR DESCRIPTION
**Pull request by alexcrichton**
Betas are hot off the bots, let's get them while they're fresh.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
```
[00:03:22] tidy error: The Unstable Book has a 'library feature' section 'question_mark_carrier' which doesn't correspond to an unstable library feature
```

**Comment by BurntSushi** [comment]
@alexcrichton Could you find someone else to review this PR? I'm so unfamiliar with this code that I don't even know who to hand it off too. :P

**Comment by Mark-Simulacrum** [comment]
r=me with the tidy error fixed

**Comment by aidanhs** [comment]
```
[00:35:31] '/checkout/src/doc/unstable-book/src/library-features/question-mark-carrier.md' referenced from SUMMARY.md does not exist.
```

@bors r-

**Comment by Mark-Simulacrum** [comment]
I assume something with setup went wrong, so not retrying.

```
[00:00:29] error: failed to run `rustc` to learn about target-specific information
[00:00:29] 
[00:00:29] To learn more, run the command again with --verbose.
[00:00:29] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:00:29] Build completed unsuccessfully in 0:00:27
[00:00:29] Makefile:76: recipe for target 'prepare' failed
```

**Comment by Mark-Simulacrum** [comment]
On fuchsia:

```
[00:22:10] [1m[31merror[E0460](B[m[1m: found possibly newer version of crate `std` which `backtrace` depends on(B[m

[00:22:10]    (B[m[1m[34m--> (B[m/cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.10.0/src/lib.rs:369:1(B[m

[00:22:10]     (B[m[1m[34m|(B[m

[00:22:10] [1m[34m369(B[m (B[m[1m[34m| (B[mextern crate backtrace;(B[m

[00:22:10]     (B[m[1m[34m| (B[m[1m[31m^^^^^^^^^^^^^^^^^^^^^^^(B[m

[00:22:10]     (B[m[1m[34m|(B[m

[00:22:10]     (B[m[1m[34m= (B[m[1mnote(B[m: perhaps that crate needs to be recompiled?(B[m

[00:22:10]     (B[m[1m[34m= (B[m[1mnote(B[m: crate `std` path #1: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-35ad9950c7e5074b.rlib(B[m

[00:22:10]     (B[m[1m[34m= (B[m[1mnote(B[m: crate `std` path #2: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-35ad9950c7e5074b.so(B[m

[00:22:10]     (B[m[1m[34m= (B[m[1mnote(B[m: crate `backtrace` path #1: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libbacktrace-93e12210233f2ebd.rlib(B[m

[00:22:10] 

[00:22:10] [1m[31merror(B[m[1m: aborting due to previous error(s)(B[m

```

**Comment by alexcrichton** [comment]
@bors: retry

Urgh I can't reproduce locally after many attempts. Here's to hoping the next failure is more illuminating.

**Comment by alexcrichton** [comment]
Did some investigation, this is blocked on https://github.com/rust-lang/cargo/pull/4168, backported in Cargo in https://github.com/rust-lang/cargo/pull/4169 and we'll need to backport + bump the beta in rust-lang/rust eventually as well.

**Comment by alexcrichton** [comment]
Cargo update for beta is happening in https://github.com/rust-lang/rust/pull/42609

**Comment by alexcrichton** [comment]
@bors: r+

New betas are in! Let's see how this fares now.

**Comment by Mark-Simulacrum** [comment]
@bors r-
@bors r+

Just to not have your PR approved by you :)

**Comment by ishitatsuyuki** [comment]
Looks like Cargo has some jobserver bug.

The only lines with the "error" text:
```
make: *** internal error: invalid --jobserver-auth string '__rust_jobserver_semaphore_3474014446'.  Stop.
thread 'main' panicked at 'assertion failed: t!(cmd . status (  )).success()', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\lzma-sys-0.1.4\build.rs:140
note: Run with `RUST_BACKTRACE=1` for a backtrace.
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage0/bin\\cargo.exe" "build" "-j" "2" "--target" "x86_64-pc-windows-gnu" "--release" "--locked" "--color" "always" "--manifest-path" "C:\\projects\\rust\\src/tools\\rust-installer\\Cargo.toml"
expected success, got: exit code: 101
```

**Comment by ishitatsuyuki** [comment]
@alexcrichton, just confirming that you're aware of the merge conflict.

**Comment by Mark-Simulacrum** [comment]
```
[00:41:16] Generating unstable book md files (x86_64-unknown-linux-gnu)

[00:41:17] Rustbook (x86_64-unknown-linux-gnu) - unstable-book

[00:41:19] Build completed successfully in 0:02:29

[00:41:19] travis_fold:end:make-all
[0K

[00:41:19] travis_time:end:01ebea00:start=1497897604035345344,finish=1497899967377520223,duration=2363342174879
[0Ktravis_fold:start:make-check
[0Ktravis_time:start:0284f5b6
[0Kmake -j 4 check

[00:41:19]     Finished dev [unoptimized] target(s) in 0.0 secs

[00:41:20] error: failed to run `rustc` to learn about target-specific information

[00:41:20] 

[00:41:20] Caused by:

[00:41:20]   process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustc - --crate-name ___ --print=file-names -Zincremental=/tmp/rust-incr-cache --crate-type bin --crate-type rlib --target x86_64-unknown-linux-gnu` (exit code: 101)

[00:41:20] --- stderr

[00:41:20] error: the option `Z` is only accepted on the nightly compiler

[00:41:20] 

[00:41:20] 

[00:41:20] 

[00:41:20] 

[00:41:20] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--"
```

**Comment by Mark-Simulacrum** [comment]
```
[00:59:25] make: *** internal error: invalid --jobserver-auth string '__rust_jobserver_semaphore_1341763882'.  Stop.
```

**Comment by Mark-Simulacrum** [comment]
```
[00:55:11] running: "make" "-f" "win32/Makefile.gcc" "install" "prefix=/C/projects/rust/build/x86_64-pc-windows-gnu/stage2-tools/x86_
64-pc-windows-gnu/release/build/libz-sys-ee597c11ceb65fc3/out" "IMPLIB=" "INCLUDE_PATH=/C/projects/rust/build/x86_64-pc-windows-gnu/s
tage2-tools/x86_64-pc-windows-gnu/release/build/libz-sys-ee597c11ceb65fc3/out/include" "LIBRARY_PATH=/C/projects/rust/build/x86_64-pc
-windows-gnu/stage2-tools/x86_64-pc-windows-gnu/release/build/libz-sys-ee597c11ceb65fc3/out/lib" "BINARY_PATH=/C/projects/rust/build/
x86_64-pc-windows-gnu/stage2-tools/x86_64-pc-windows-gnu/release/build/libz-sys-ee597c11ceb65fc3/out/bin"
[00:55:11]
[00:55:11]
[00:55:11] command did not execute successfully, got: exit code: 2
[00:55:11]
[00:55:11]
[00:55:11]
[00:55:11] --- stderr
[00:55:11] make: *** internal error: invalid --jobserver-auth string '__rust_jobserver_semaphore_1394453852'.  Stop.
[00:55:11]
[00:55:11] Build failed, waiting for other jobs to finish...
[00:55:13] error: build failed
[00:55:13]
[00:55:13]
[00:55:13] command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage0/bin\\cargo.exe" "build" "-j" "2" "--target" "x86_64-pc-windows-gnu" "--release" "--locked" "--color" "always" "--manifest-path" "C:\\projects\\rust\\src/tools\\rls\\Cargo.toml"
[00:55:13] expected success, got: exit code: 101
```

**Comment by alexcrichton** [comment]
When [one fix isn't enough](https://github.com/alexcrichton/libz-sys/commit/58e4dcea89f3c765f8175238b20689752f1963ec) then you should just [try, try again](8a4b1e87e3d6bf9f25707a28691ed98fe2677003)

**Pull request merged**
