### PR TITLE
Implement -Z location-detail flag

### LINKED ISSUE #70580: Mitigate binary size impact of implicit caller location
Once we've [measured the size impact](https://github.com/rust-lang/rust/issues/70579) of [implicit caller location](https://github.com/rust-lang/rust/issues/47809), we need to decide what (if any) knobs to offer users to mitigate that impact.

The RFC originally proposed a [`-Zlocation-detail-control`](https://github.com/rust-lang/rfcs/blob/master/text/2091-inline-semantic.md#location-detail-control) flag for rustc which would allow users to control which fields of `Location` were preserved.

On the tracking issue [I also proposed](https://github.com/rust-lang/rust/issues/47809#issuecomment-605530430) an all-or-nothing flag like `-Zredact-caller-location` which would either preserve `Location`s or rewrite them all to be the same.

Note that both of these options are limited to controlling the locations reported by user code -- unless a user recompiles `std` with whatever flag we offer, there will always be "unredacted" locations in their binary.

I'm fond of ideas that would allow us to replace `Location`s with something smaller that can be "symbolized" similarly to the way a debugger for an embedded device can identify the source location for a program counter value in a stacktrace. I *think* most options in this direction require help from the linker that isn't available, but I'd love to be wrong.

### PR DESCRIPTION
**Pull request by hudson-ayers**
This PR implements the `-Z location-detail` flag as described in https://github.com/rust-lang/rfcs/pull/2091 . 

`-Z location-detail=val` controls what location details are tracked when using `caller_location`. This allows users to control what location details are printed as part of panic messages, by allowing them to exclude any combination of filenames, line numbers, and column numbers. This option is intended to provide users with a way to mitigate the size impact of `#[track_caller]`.

Some measurements of the savings of this approach on an embedded binary can be found here: https://github.com/rust-lang/rust/issues/70579#issuecomment-942556822 .

Closes #70580 (unless people want to leave that open as a place for discussion of further improvements).

This is my first real PR to rust, so any help correcting mistakes / understanding side effects / improving my tests is appreciated :) 

I have one question: RFC 2091 specified this as a debugging option (I think that is what -Z implies?). Does that mean this can never be stabilized without a separate MCP? If so, do I need to submit an MCP now, or is the initial RFC specifying this option sufficient for this to be merged as is, and then an MCP would be needed for eventual stabilization?

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
LGTM, r=me once these comments are resolved.

**Comment by korran** [comment]
How do you use this flag to disable ALL the location details?

When I set `-Z location-detail=` (an empty comma-separated list), the compiler complains:

```
incorrect value `` for unstable option `location-detail` - comma separated list of location details to track: `file`, `line`, or `column` was expected
```

**Comment by hudson-ayers** [comment]
I think I misunderstood how CLI option parsing works when implementing this, I thought passing an empty string to the option would pass `Some("")` to the parser, but that does not seem to be the case, so it is not possible to disable all the location details. I will followup with a fix and an additional test for this case soon

**Comment by hudson-ayers** [comment]
#99620 contains the fix

**Pull request merged**
