### PR TITLE
fix panic in Path::strip_prefix

### LINKED ISSUE #93586: `Path::strip_prefix` may panic when a path consists only of a prefix component
This code panics on Windows:

```rust
fn main() {
    std::path::Path::new("C:").strip_prefix("C:");
}
```

According to the documentation for `strip_prefix`, it should either succeed or return `Err(StripPrefixError)`. Instead, it panics due to an out-of-range index:

```
thread 'main' panicked at 'range start index 2 out of range for slice of length 0', library\std\src\path.rs:716:24
```

### Meta

`rustc --version --verbose`:
```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-pc-windows-msvc
release: 1.58.1
LLVM version: 13.0.0
```

The bug is also present in nightly.

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'range start index 2 out of range for slice of length 0', library\std\src\path.rs:716:24
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:107
   2: core::slice::index::slice_start_index_len_fail
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\slice\index.rs:34
   3: core::slice::index::impl$5::index
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\slice\index.rs:324
   4: core::slice::index::impl$0::index
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\slice\index.rs:15
   5: std::path::Components::include_cur_dir
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\path.rs:722
   6: std::path::Components::len_before_body
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\path.rs:657
   7: std::path::Components::trim_right
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\path.rs:774
   8: std::path::Components::as_path
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\path.rs:693
   9: std::path::impl$62::_strip_prefix::closure$0
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\path.rs:2242
  10: core::option::Option::map
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\option.rs:846
  11: std::path::Path::_strip_prefix
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\path.rs:2241
  12: std::path::Path::strip_prefix<str>
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\std\src\path.rs:2237
  13: test_path_panic::main
             at .\src\main.rs:2
  14: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\test-path-panic.exe` (exit code: 101)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by name1e5s**
close #93586

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This looks like a correct fix, I think, but I think it would be worthwhile to remove prefix_len as a distinct thing from prefix_remaining entirely -- it seems like it's essentially not a good idea to use that function (unless you know the state is Prefix, but then they have identical behavior).

Would you be up for making that refactoring? It looks like there are not that many users that would need to change and all have a trivially known state, if I look locally.

**Comment by name1e5s** [comment]
> This looks like a correct fix, I think, but I think it would be worthwhile to remove prefix_len as a distinct thing from prefix_remaining entirely -- it seems like it's essentially not a good idea to use that function (unless you know the state is Prefix, but then they have identical behavior).
> 
> Would you be up for making that refactoring? It looks like there are not that many users that would need to change and all have a trivially known state, if I look locally.

done

**Comment by Mark-Simulacrum** [comment]
Thanks, that looks great!

@bors r+ rollup=never (potentially perf-sensitive)

**Comment by matthiaskrgr** [comment]
@bors retry x86_64 msvc (probably) spurious failure:

````
[RUSTC-TIMING] unicode_width test:false 0.100
[RUSTC-TIMING] getopts test:false 3.213
[RUSTC-TIMING] proc_macro test:false 15.787
   Compiling test v0.0.0 (D:\a\rust\rust\library\test)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" "/DEF:C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rustcyYH2W9\\lib.def" "/NOLOGO" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\test-6464307edd00076d.test.06275a10-cgu.0.rcgu.o" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\test-6464307edd00076d.47fpacyqlqntgftt.rcgu.rmeta" "/LIBPATH:D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps" "/LIBPATH:D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\release\\deps" "/LIBPATH:D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\build\\compiler_builtins-d23c84560eca12a0\\out" "/LIBPATH:D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "kernel32.lib" "/WHOLEARCHIVE:\\\\?\\D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\libgetopts-04f14876bdd48cb7.rlib" "/WHOLEARCHIVE:\\\\?\\D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\libunicode_width-c74fe7d359ba4245.rlib" "/WHOLEARCHIVE:\\\\?\\D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\librustc_std_workspace_std-ac92d3dd0da3e4c2.rlib" "/LIBPATH:\\\\?\\D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps" "\\\\?\\D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\libcompiler_builtins-033009b95f350faf.rlib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "libcmt.lib" "/NXCOMPAT" "/LIBPATH:D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\test-6464307edd00076d.dll" "/OPT:REF,ICF" "/DLL" "/IMPLIB:D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\test-6464307edd00076d.dll.lib" "/DEBUG"
  = note: lib.def : error LNK2001: unresolved external symbol __rust_alloc

          lib.def : error LNK2001: unresolved external symbol __rust_alloc_zeroed

          lib.def : error LNK2001: unresolved external symbol __rust_dealloc

          lib.def : error LNK2001: unresolved external symbol __rust_realloc

          D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\test-6464307edd00076d.dll.lib : fatal error LNK1120: 4 unresolved externals
          

[RUSTC-TIMING] test test:false 17.556
error: could not compile `test` due to previous error
````

**Comment by matthiaskrgr** [comment]
ok might not be spurious after all :thinking:

**Comment by Mark-Simulacrum** [comment]
I have no sense of why this might be happening -- this particular patch seems like it should be near-identical in terms of functionality. Maybe we're no longer including some prefix due to the change in include_cur_dir, which is causing us to reference a different path in the link invocation somehow? That would be surprising to me, the behavior looks right I think with the new impl.

cc @the8472 since you've touched the path-related code recently and maybe can spot what I'm presumably overlooking here

**Comment by the8472** [comment]
Btw, did you run stage0 std tests under windows locally? I guess CI didn't even get that far, but if the testsuite doesn't catch whatever is failing here then we need more coverge.

**Comment by ChrisDenton** [comment]
I'm seeing these failures locally: `x.py test library/std --test-args path::tests`

```plain
---- path::tests::test_decompositions_windows stdout ----
thread 'path::tests::test_decompositions_windows' panicked at 'iter: Expected ["c:", "\\"], found ["\\", ":"]', library\std\src\path\tests.rs:523:5

---- path::tests::test_push stdout ----
thread 'path::tests::test_push' panicked at 'pushing "baz" onto "\\\\?\\foo\\bar": Expected "\\\\?\\foo\\bar\\baz", got "\\?\\foo\\bar\\baz"', library\std\src\path\tests.rs:1252:9
```

**Comment by name1e5s** [comment]
After testing on  my new device with windows 11 installed, I found the problem may belongs to the refactoring after the small fix. The fix itself is okay. I'll find out why the refactoring breaks 2 other tests.
Screenshot for testing on my branch:
90GWET4IMWQY~8G~RLKF%JE
The failing tests on my branch also failed on master, still investgating the reason.
Screenshot for testing on master:
SDON`GG_RO2LI65O{I~LONM

**Comment by ChrisDenton** [comment]
`test_windows_absolute` should be fixed by #94650. I'd guess `windows_exe_resolver` is failing for you because you don't have developer mode enabled in the Windows settings? In either case they shouldn't block this PR. Btw, you can use the `--test-args` parameter to only run relevant tests.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@name1e5s https://github.com/rust-lang/rust/pull/94650 has been merged - can you please post your status on this PR? 

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Pull request merged**
