### PR TITLE
Support stability and deprecation checking for all macros

### LINKED ISSUE #34079: able to invoke unstable macro 2.0
Stability checking for `macro_rules!` was fixed in https://github.com/rust-lang/rust/pull/48524, but uses of declarative macros 2.0 (`macro` items) are still not checked for stability.

#### ORIGINAL ISSUE:

Why does this compile?

``` rust
fn main() {
    __thread_local_inner!(i32, 42);
}
```

`__thread_local_inner` is marked `#[unstable(...)] #[allow_internal_unstable]`.

### LINKED ISSUE #49912: `#[deprecated]` has no effect on macros
The following code compiles successfully with no warnings, when it should be producing a deprecation warning.

https://play.rust-lang.org/?gist=aa4c719a14da2bb5cf3ddf8c3066f452&version=stable

### PR DESCRIPTION
**Pull request by petrochenkov**
RELNOTES: Deprecation attributes on macros now have effect.

Fixes https://github.com/rust-lang/rust/issues/34079
Fixes https://github.com/rust-lang/rust/issues/49912
Unblocks https://github.com/rust-lang/rust/pull/62086
Unblocks https://github.com/rust-lang/rust/pull/61000

### CODE REVIEW

**Comment by Centril** [comment]
RELNOTES: Deprecation attributes on macros now have effect.

**Comment by BO41** [comment]
Unblocks #61000 :heart:

**Comment by petrochenkov** [comment]
ping @pnkfelix, this PR is blocking some other work

**Review by matthewjasper — APPROVED** [review]
r? @matthewjasper 

This looks good. r=me with or without comments addressed.

cc #58705 (unstable macros are checked intra-crate).

**Pull request merged**
