### PR TITLE
Remove incorrect statement about the reference.

### PR DESCRIPTION
**Pull request by steveklabnik**
This is not true.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Or at least, I feel like this phrasing doesn't accurately convey what's going on. It might be _incomplete_, but it's not _inaccurate_. Maybe a replacement sentence is better? @rust-lang/docs

**Comment by GuillaumeGomez** [comment]
No need to debate upon this. Thanks for catching this @steveklabnik!

@bors: r+ rollup

**Comment by petrochenkov** [comment]
Wait, this is completely wrong.
The reference *is* out of date, it *is* incomplete and it *may be* inaccurate.

**Comment by steveklabnik** [comment]
@bors: r-

This morning, looking at it again, I agree with @petrochenkov ; let me re-word this properly.

**Pull request closed without merging**
