### PR TITLE
Rollup of 18 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #40387, #40433, #40452, #40456, #40457, #40463, #40466, #40467, #40495, #40496, #40497, #40500, #40503, #40505, #40512, #40514, #40517, #40520
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* spurious sccache failure https://github.com/rust-lang/rust/issues/40240

**Comment by frewsxcv** [comment]
@bors retry

mac things didn't even run

**Comment by alexcrichton** [comment]
@bors: retry

* spurious sccache failure

https://github.com/rust-lang/rust/issues/40240

**Comment by alexcrichton** [comment]
@bors: retry

* osx timeout https://github.com/rust-lang/rust/issues/40571

**Comment by alexcrichton** [comment]
@bors: retry

I saw one of the OSX bots hanging in compiling LLVM, presumably due to https://github.com/rust-lang/rust/issues/40240, so going to see how https://github.com/rust-lang/rust/pull/40575 fares for now.

**Comment by alexcrichton** [comment]
[hanging bot](https://travis-ci.org/rust-lang/rust/jobs/211773195)

**Comment by alexcrichton** [comment]
@bors: retry

* I give up...

https://github.com/rust-lang/rust/issues/40571

**Pull request closed without merging**
