### PR TITLE
in which the unused-parens lint comes to cover function and method args

### LINKED ISSUE #46137: Missing "unnecessary parentheses" warning
This program compiles without warnings:

```
fn main() {
    use std::ops::Range;
    fn foo(r1: Range<u32>, r2: Range<u32>) {
        for _ in r1 {}
        for _ in r2 {}
    }
    foo((0 .. 10), (0 .. 10)); // ***
    foo(0 .. 10, 0 .. 10);
}
```

I expected a "unnecessary parentheses" warning on the first call to foo() because #[warn(unused_parens)] is on by default.

### PR DESCRIPTION
**Pull request by zackmdavis**
Resolves #46137.

### CODE REVIEW

**Comment by zackmdavis** [comment]
Travis failure looks dubious

**Comment by kennytm** [comment]
Legit.

```
error: unnecessary parentheses around function argument
    --> src\librustc_apfloat\ieee.rs:1437:56
     |
1437 |         let exp_change = cmp::min(cmp::max(exp as i32, (-max_change - 1)), max_change);
     |                                                        ^^^^^^^^^^^^^^^^^ help: remove these parentheses
     |
note: lint level defined here
    --> src\librustc_apfloat\lib.rs:45:9
     |
45   | #![deny(warnings)]
     |         ^^^^^^^^
     = note: #[deny(unused_parens)] implied by #[deny(warnings)]
   Compiling rustc_binaryen v0.0.0 (file:///C:/projects/rust/src/librustc_binaryen)
error: aborting due to previous error
error: Could not compile `rustc_apfloat`.
```

**Comment by zackmdavis** [comment]
Yes, with regrets, it turns out that the "Eh, this looks right; I don't have to tie up my cores running the tests locally because Travis will catch any needed fixes for me without wasting any reviewer-minutes" PR strategy is less effective when Travis is broken. Force-push bff573c is more likely to be what we want (although my local test build is unrelatedly flaking late in the test process, after the ui/run-pass/compile-fail tests have apparently succeeded).

**Comment by kennytm** [comment]
Legit.

```
[00:35:01] error: unnecessary parentheses around function argument
[00:35:01]    --> src/libstd/sys/unix/thread.rs:314:14
[00:35:01]     |
[00:35:01] 314 |           Some((libc::pthread_get_stackaddr_np(libc::pthread_self()) as usize -
[00:35:01]     |  ______________^
[00:35:01] 315 | |               libc::pthread_get_stacksize_np(libc::pthread_self())))
[00:35:01]     | |___________________________________________________________________^
[00:35:01]     |
[00:35:01] note: lint level defined here
[00:35:01]    --> src/libstd/lib.rs:232:9
[00:35:01]     |
[00:35:01] 232 | #![deny(warnings)]
[00:35:01]     |         ^^^^^^^^
[00:35:01]     = note: #[deny(unused_parens)] implied by #[deny(warnings)]
[00:35:01] help: remove these parentheses
[00:35:01]     |
[00:35:01] 314 |         Some(libc::pthread_get_stackaddr_np(libc::pthread_self()) as usize -
[00:35:01] 315 |      libc::pthread_get_stacksize_np(libc::pthread_self()))
[00:35:01]     |
```

**Comment by alexcrichton** [comment]
ping @zackmdavis, just makeing sure this doesn't fall off your radar!

**Comment by zackmdavis** [comment]
(This is slightly embarrassing) updated

**Comment by kennytm** [comment]
Needs to update cargo...

```
   Compiling cargo v0.25.0 (file:///C:/projects/rust/src/tools/cargo)
error: unnecessary parentheses around method argument
   --> src\tools\cargo\src/cargo\ops\cargo_test.rs:123:52
    |
123 |         Ok((Test::Multiple, errors.into_iter().map((|(_, _, e)| e)).collect()))
    |                                                    ^^^^^^^^^^^^^^^ help: remove these parentheses
    |
note: lint level defined here
   --> src\tools\cargo\src/cargo/lib.rs:1:9
    |
1   | #![deny(unused)]
    |         ^^^^^^
    = note: #[deny(unused_parens)] implied by #[deny(unused)]
error: aborting due to previous error
error: Could not compile `cargo`.
To learn more, run the command again with --verbose.
```

**Comment by zackmdavis** [comment]
(updated)

**Comment by kennytm** [comment]
CI failed. I guess you need to run `cargo update -p cargo`.

**Comment by zackmdavis** [comment]
like this?? (updated)

**Comment by kennytm** [comment]
@bors r-

Something’s wrong with the new cargo @rust-lang/cargo.

```
[00:34:36] Cargo Book (x86_64-unknown-linux-gnu) - cargo
[00:34:36] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', libcore/result.rs:916:5
[00:34:36] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:34:36] 
[00:34:36] 
[00:34:36] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rustbook" "build" "/checkout/src/tools/cargo/src/doc/book" "-d" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc/cargo"
```

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/47280

**Comment by zackmdavis** [comment]
no. 47280 has landed; rebased

**Pull request merged**
