### PR TITLE
Do not silently truncate offsets for `read_at`/`write_at` on emscripten

### PR DESCRIPTION
**Pull request by tbu-**
Generate an IO error if the offset is out of bounds for the system call.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r-

This caused a [rollup failure](https://travis-ci.org/rust-lang/rust/jobs/377861762). I've attempted to [fix it in the rollup](https://github.com/rust-lang/rust/pull/50666/commits/094873c163834e4faa5a1b2ffca2b5a6e50aa2b4) so it's not necessary to update this PR if the rollup lands.

Also a friendly reminder to please test PRs, it looks like this was not tested on the target platform of the PR before being submitted.

**Comment by kennytm** [comment]
Oops, missing import.

```
[01:06:05] error[E0599]: no method named `try_into` found for type `i64` in the current scope
[01:06:05]   --> libstd/sys/unix/fd.rs:80:35
[01:06:05]    |
[01:06:05] 80 |             if let Ok(o) = offset.try_into() {
[01:06:05]    |                                   ^^^^^^^^
[01:06:05]    |
[01:06:05]    = help: items from traits can only be used if the trait is in scope
[01:06:05]    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
[01:06:05]            candidate #1: `use core::convert::TryInto;`
[01:06:05] 
[01:06:05] error[E0599]: no method named `try_into` found for type `i64` in the current scope
[01:06:05]    --> libstd/sys/unix/fd.rs:127:35
[01:06:05]     |
[01:06:05] 127 |             if let Ok(o) = offset.try_into() {
[01:06:05]     |                                   ^^^^^^^^
[01:06:05]     |
[01:06:05]     = help: items from traits can only be used if the trait is in scope
[01:06:05]     = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
[01:06:05]             candidate #1: `use core::convert::TryInto;`
[01:06:05] 
[01:06:05] error: aborting due to 2 previous errors
```

**Comment by alexcrichton** [comment]
I've decided to close the rollup, so this PR will need to be fixed

**Comment by alexcrichton** [comment]
(please be sure to test it to make sure the import suggestions work)

**Comment by tbu-** [comment]
Where do I find documentation for building the standard library for emscripten?

**Comment by kennytm** [comment]
@tbu- First, you enable `emscripten` in your `config.toml` with 

```toml
[rust]
codegen-backends = ["llvm", "emscripten"]
```

then, to build, you run

```sh
./x.py build --stage 1 src/libstd --target asmjs-unknown-emscripten
```

----

However, I believe you could quickly check for syntax error just using `x.py` in stage 0:

```sh
./x.py check src/libstd --target asmjs-unknown-emscripten
```

**Comment by tbu-** [comment]
Re `S-waiting-on-review`: The test compilation on my side hasn't finished yet.

**Comment by tbu-** [comment]
Oh nvm, now it has.

**Pull request merged**
