### PR TITLE
Give a better diagnostic for keywords with incorrect capitalization

### PR DESCRIPTION
**Pull request by hosseind88**
https://github.com/rust-lang/rust/issues/77149

### CODE REVIEW

**Comment by jyn514** [comment]
It looks like this had some regressions in other parts of the parser unfortunately:

```
---- [ui] ui/suggestions/issue-64252-self-type.rs stdout ----
diff of stderr:

-	error: expected one of `:`, `@`, or `|`, found `<`
-	  --> $DIR/issue-64252-self-type.rs:4:15
+	error: `"Box"` is not a keyword
+	  --> $DIR/issue-64252-self-type.rs:4:12
3	   |
4	LL | pub fn foo(Box<Self>) { }
-	   |               ^ expected one of `:`, `@`, or `|`
+	   |            ^^^ try `"box"` instead
6	   |
7	   = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
8	help: if this is a `self` type, give it a parameter name

14	LL | pub fn foo(_: Box<Self>) { }
15	   |            ^^^^^^
16	
-	error: expected one of `:`, `@`, or `|`, found `<`
-	  --> $DIR/issue-64252-self-type.rs:10:15
+	error: `"Box"` is not a keyword
+	  --> $DIR/issue-64252-self-type.rs:10:12
19	   |
20	LL |     fn bar(Box<Self>) { }
-	   |               ^ expected one of `:`, `@`, or `|`
+	   |            ^^^ try `"box"` instead
22	   |
23	   = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
24	help: if this is a `self` type, give it a parameter name
```

**Comment by estebank** [comment]
Hi @hosseind88! Thanks for PR! This is a great idea. Could you squash your commits? Looking at the change I like the intent but I am not sure about the specific. If you run `./x.py test src/test/ui --stage 1 --bless` you will see that some `.stderr` files will get updated as pointed out by @jyn514 and that new output is a slight regression. This would likely also happen with a parse error when a type called `For` or `Struct` goes. This approach has breath and catches a lot of cases, but if we try to go higher we could "complicate" the code by proactively checking for `Ident`s that where previously expected... Let me think about what that would look like 🤔

**Comment by JohnCSimon** [comment]
@hosseind88 - ping from triage. You please address the merge conflict and the comments?
 
@Rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by JohnCSimon** [comment]
@hosseind88 - ping from triage. You please address the merge conflict and the comments?

**Comment by hosseind88** [comment]
Hi, sorry I have been too busy since I opened this PR and I couldn't finish it, very sorry for this delay, I will try to work on it and fix issues and conflicts this week

**Comment by Dylan-DPC** [comment]
@hosseind75 
thanks for taking the time to contribute. I have to close this due to inactivity. If you wish and you have the time you can open a new PR with these changes and we'll take it from there. Thanks

**Comment by crlf0710** [comment]
@hosseind88 Ping from triage, any updates on this?

**Comment by JohnCSimon** [comment]
@hosseind88 Ping from triage. Unfortunately I'm going to close this as inactive. 
Please feel free to reopen this when you're ready to continue working on this.  Thank you!

**Pull request closed without merging**
