### PR TITLE
rustc_middle: Document which exactly `DefId`s don't have `DefKind`s

### PR DESCRIPTION
**Pull request by petrochenkov**
I don't currently have time to investigate when and how to create these missing HIR nodes, but if someone else could do that it would be great.

### CODE REVIEW

**Comment by cjgillot** [comment]
I'm not convinced this is the right direction. I'd suggest the opposite: all `LocalDefId`s must have a `DefKind`, and ICEing otherwise. `DefKind` is one of the primary ways to examine a `DefId` in many places. If a `LocalDefId` is missing HIR, the responsible code must provide it with a `DefKind` some other way.

**Comment by petrochenkov** [comment]
@cjgillot 
>all `LocalDefId`s must have a `DefKind`, and ICEing otherwise ... If a `LocalDefId` is missing HIR, the responsible code must provide it with a `DefKind` some other way.

But that's exactly what my FIXME comment says.
And I added ICEs for all cases except the one with anon consts that I'm not going to fix right now.

**Comment by cjgillot** [comment]
Indeed, I need to re-learn how to read...
@bors r+

**Pull request merged**
