### PR TITLE
adding Dragonfly x86_64 snapshot 235d774

### PR DESCRIPTION
**Pull request by dhuseby**
@alexcrichton please upload the following snapshot with this PR.

https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2016-03-18-235d774-dragonfly-x86_64-e790279a7b286ddf2e716ccd3bb1b7f0a386a5c7.tar.bz2

### CODE REVIEW

**Comment by dhuseby** [comment]
@mneumann ping.

**Comment by mneumann** [comment]
@dhuseby : I think the patch is wrong. It's for 02-17, not for the 03-18 snapshot. Probably a jetlag issue ;-)

**Comment by dhuseby** [comment]
@mneumann dang, i'll fix it today.  thanks for your patience.

**Comment by tamird** [comment]
Looks like this got obsoleted by #32942.

**Comment by alexcrichton** [comment]
Aha, indeed!

**Pull request closed without merging**
