### PR TITLE
Remove the everybody loops pass

### PR DESCRIPTION
**Pull request by bjorn3**
It isn't used anymore by rustdoc.

Split out of https://github.com/rust-lang/rust/pull/92895. There has been some previous discussion there.

### CODE REVIEW

**Comment by jyn514** [comment]
cc @pnkfelix

**Comment by jackh726** [comment]
I think the way forward here is just a compiler FCP.

**Comment by oli-obk** [comment]
> I have personally always found -Zeverybody-loops an oversized hammer. It only helps in reducing issues in very limited set of rustc components early in the pipeline (parser, resolver…). An ability to loopify bodies more selectively is definitely a technique that is helpful still, but -Zeverybody-loops ain't that.

> If the pass causes genuine pain maintaining other parts of the codebase, I'm probably in favour of removing it. 

Reproducing this comment by nagisa from the other PR as I find it a good summary of the situation.

@rfcbot fcp

**Comment by bjorn3** [comment]
Rebased

**Comment by jackh726** [comment]
Given the FCP, @bors r+

**Pull request merged**
