### PR TITLE
Use command line metadata path if provided

### LINKED ISSUE #85356: `--emit metadata=some/path/libfoo-abc-123.rmeta` doesn't work
I tried this code:

foo.rs:
```rust
pub fn foo() { println!("foo") }
```
```
$ mkdir out
$ rustc --crate-name foo --crate-type rlib --emit metadata=out/libfoo-abc-123.rmeta foo.rs
```

I expected to see this happen:
I expected this to output `out/libfoo-abc-123.rmeta`, as [documented](https://doc.rust-lang.org/rustc/command-line-arguments.html#--emit-specifies-the-types-of-output-files-to-generate) ("Each emission type may also specify the output filename with the form KIND=PATH, which takes precedence over the -o flag.").

Instead, this happened: 
It created `libfoo.rmeta` in the current directory.

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (8cf990c9b 2021-05-15)
binary: rustc
commit-hash: 8cf990c9b5c59f25c806fad9f4466f9d6509bbea
commit-date: 2021-05-15
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by jsgf**
If the command-line has `--emit metadata=some/path/libfoo.rmeta` then
use that.

Closes #85356

I couldn't find any existing tests for the `--emit TYPE=PATH` command line syntax, so I wasn't sure how to test this aside from ad-hoc manual testing. Is there a ui test type for "generated output file with expected name"?

### CODE REVIEW

**Comment by jsgf** [comment]
Looks like test failures are spurious.

**Comment by jsgf** [comment]
@estebank ping?

**Comment by estebank** [comment]
For the tests, you need to write a [`run-make`](https://github.com/rust-lang/rust/tree/master/src/test/run-make) test, which are involved to write but it's the best option for what you're checking here.

If you need a hand writing a new makefile test, ping me. r=me for the code itself as it is now.

**Comment by jsgf** [comment]
@estebank I've added run-make tests.

**Pull request merged**
