### PR TITLE
[beta] Clippy backport for stabilization of range_is_empty feature

### PR DESCRIPTION
**Pull request by flip1995**
Backport of https://github.com/rust-lang/rust-clippy/pull/5961

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, we don't usually backport changes to lints. Is there a reason you feel we should make this backport happen? As far as I can tell, this lint isn't for correctness or anything, so we could probably let it ride the trains?

**Comment by flip1995** [comment]
I don't have a particular reason, why we should backport this. The stabilization PR author @scottmcm asked about it: https://github.com/rust-lang/rust-clippy/issues/5956

It would get the stabilized behavior of the lint into the same release as the stabilization of the feature, which is nice to have, but not a must-have backport. So I would leave it up to you to decide if this should get backported or not.

**Comment by Mark-Simulacrum** [comment]
Okay, I'm going to beta-nominate for T-compiler to take a look at, but I personally feel that while we could backport this. It has a relatively small diff, which is nice.

**Comment by scottmcm** [comment]
(Commenting because of the ping) I'm happy whether or not this backport goes in.  I filed the clippy issue to make sure the lint was updated eventually, but I don't think there's any particular reason that this change to this lint _needs_ to go in the same train as the stabilization.  But this is also the first time I'd changed clippy, so I have no idea what the usual process is -- y'all should do what you think is best 🙂

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/93962weeklymeeting2020090354818.html#208974056) in T-compiler meeting, declined to backport.

@rustbot modify labels: -beta-nominated

**Pull request closed without merging**
