### PR TITLE
resolve: Fix false-positives from lint `absolute_paths_not_starting_with_crate`

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/56311 (stable-to-beta regression)

### CODE REVIEW

**Comment by pietroalbini** [comment]
cc @rust-lang/compiler for the beta nomination (stable-to-beta regression)

**Comment by pnkfelix** [comment]
discussed in T-compiler meeting. beta-accepted.

**Pull request merged**
