### PR TITLE
Bump compiler cc

### LINKED ISSUE #134657: x86_64 msvc: warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
On my native `x86_64-pc-windows-msvc` environment, I am observing the warnings:

```
   Compiling rustc_ast_passes v0.0.0 (X:\repos\rust\compiler\rustc_ast_passes)
   Compiling rustc_expand v0.0.0 (X:\repos\rust\compiler\rustc_expand)
   Compiling rustc_builtin_macros v0.0.0 (X:\repos\rust\compiler\rustc_builtin_macros)
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
   Compiling rustc_infer v0.0.0 (X:\repos\rust\compiler\rustc_infer)
   Compiling rustc_mir_dataflow v0.0.0 (X:\repos\rust\compiler\rustc_mir_dataflow)
   Compiling rustc_metadata v0.0.0 (X:\repos\rust\compiler\rustc_metadata)
   Compiling rustc_pattern_analysis v0.0.0 (X:\repos\rust\compiler\rustc_pattern_analysis)
```

This is probably related to the `cc` bumps we done recently... FYI @clubby789 :ferrisClueless: I have not tried to bisect this.

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #134657
Pulls in https://github.com/rust-lang/cc-rs/pull/1330

try-job: x86_64-msvc

### CODE REVIEW

**Comment by clubby789** [comment]
I don't see the warning in the log 🙂 cc @jieyouxu does this resolve it for you on your system?

**Comment by jieyouxu** [comment]
@clubby789 I can confirm that I no longer observe the warning on `x86_64-pc-windows-msvc` natively, thanks!

@bors r+ rollup

**Comment by jieyouxu** [comment]
BTW you mean https://github.com/rust-lang/cc-rs/pull/1330 right instead of pulling in the issue right?

**Comment by jieyouxu** [comment]
(rollup=always is fine because the only change was the inherit flag fix)

**Comment by clubby789** [comment]
Indeed - fixed, thanks

**Pull request merged**
