### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by m-ou-se** [comment]
@bors r-

This failed on `dist-x86_64-freebsd` in https://github.com/rust-lang/rust/pull/88605:

```
error: linking with `x86_64-unknown-freebsd11-clang` failed: exit status: 1
  |
  = note: "x86_64-unknown-freebsd11-clang" "-m64" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.0.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.1.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.10.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.11.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.12.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.13.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.14.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.15.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.2.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.3.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.4.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.5.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.6.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.7.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.8.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.rust_analyzer.4aadf416-cgu.9.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf.3y7ibxbucl5ju3lt.rcgu.o" "-Wl,--as-needed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib" "-Wl,-Bstatic" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libproc_macro_srv-e70f58bb183511f2.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblibloading-393c2af856b293a5.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtracing_tree-cd25cf509ea5db7d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libatty-b0ad6a0ca1ac3d1c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtracing_log-e7319e5aead3ff5c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libansi_term-ec132985b5781fec.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtracing_subscriber-cd11cfe48806dc78.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libthread_local-6c9eeff631babfaa.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsharded_slab-024faec7d18be336.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libmatchers-39537d9be900ea16.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libregex_automata-4404e9b5cc08e2d5.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libregex-d488fca458e1c71d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libregex_syntax-3b20e614d140dd33.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/librust_analyzer-627602b738cbfe29.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libthreadpool-cf6f9d96b0f947f9.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libvfs_notify-3d8a39ded1a691ad.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libnotify-5059517c41678d3b.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libmio-bd15cb6e788f8d70.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libfiletime-7d2947e58c2f8cfe.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libwalkdir-bc4804a27125bb28.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsame_file-f89002c71e77c375.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libkqueue-9df4b8dfad99daf8.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libkqueue_sys-d6271c3463352f8f.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libxflags-e9b865b7f6cfaa8c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblsp_types-a9892b156aafccc7.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libflycheck-7563cd524784d728.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libjod_thread-a82fdb38f1bf1b8f.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libproc_macro_api-369aa50552e8d91e.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsnap-c103f9a13881558d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libobject-f483dc5609e41e2d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libmemmap2-f38b35aaa33cf9be.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libide-c35bcfd4939bc667.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libide_diagnostics-1a13ad371c185282.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libide_completion-68689673f01ab651.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libdot-28b7dd2fd7b35b8d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libide_assists-202e1c62516ecf51.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liburl-38bdd8a3b546ffb0.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libidna-4f7768467463cc06.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libunicode_normalization-37341d48e6f72ec6.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtinyvec-495851fb1510a6b3.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtinyvec_macros-efcad49cc3bffdc5.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libunicode_bidi-ea014ae67df2bc84.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libform_urlencoded-76579150e8d0c079.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libpercent_encoding-2ae828d4305e0e9e.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libmatches-f8ce59006ffbabc9.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libpulldown_cmark_to_cmark-011d1a071be630e9.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libpulldown_cmark-58c9148018df3322.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libmemchr-ca7169391d11b3c7.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libunicase-65decf48be4e100d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libide_ssr-68a6998d4cf2dc93.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libide_db-b79f4da825a68e4a.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/librayon-1dc9372b1d91b1dc.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/librayon_core-de77a37275859d0b.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcrossbeam_deque-eb1bfdc5fb9973cc.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcrossbeam_epoch-add45435b693fe42.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libhir-2ccd0522fb7f9811.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libhir_ty-fd9a48719ef8ed77.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libchalk_recursive-e46b6f9a627bb659.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libarrayvec-7517dc9f1943a299.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libscoped_tls-9c80b96e7330af51.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libchalk_solve-6f4167b3de940589.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libena-255fb4fa82a1120a.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libpetgraph-eb01729e8e7d5138.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libfixedbitset-b6eaafde81898670.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtracing-fb0c27b057a360bb.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libpin_project_lite-cd9388bc9ab10a4e.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtracing_core-faa6211f2c522f95.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libchalk_ir-1d108b1ceb686cdd.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libbitflags-93469bdb99099749.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libhir_def-abcbd7ca1c1bc3d8.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libanymap-31d77361ed005b3e.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libhir_expand-690f65d79eb4b8ab.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libmbe-8af7380ed883c1fa.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblimit-e659f1d232cb0148.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libproject_model-549cdb8d0ab47039.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtoolchain-f641cb3d5ac8238d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libhome-668c707da7562d96.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcargo_metadata-898bd116124c1e95.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcargo_platform-775afe8bc16d66e2.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsemver-f37a8a424b73d203.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcamino-c327de4e5f96ffa5.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libbase_db-210d9c96741cf6c6.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtest_utils-df36908152bc3e96.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libdissimilar-04459fc53d3de352.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsalsa-d8b4fcbf74430f64.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liboorandom-825130eac5bb2b13.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libvfs-08d1b5796c0e33ba.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libfst-b8e5fa14eb7d760f.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsyntax-38367aa6ddbdcb3f.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libprofile-200392673cea3dbf.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libla_arena-9761cc5036189077.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcov_mark-e6f3a252e92819c8.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libitertools-64fe5b24e337c468.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libeither-fd6de90499dd5c83.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtext_edit-dcbf682759c481de.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libparser-4ca76d9ce6f5621e.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libdrop_bomb-57a17ddc6bf7884c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/librustc_ap_rustc_lexer-9b344d4245e04736.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libunicode_xid-d3926b946390b88b.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/librowan-2bab7c72a424fee9.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libmemoffset-21cb0f54adb93d5b.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtext_size-b55065e40177c3d7.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcountme-c1e64184b4c8f7e7.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libonce_cell-8bd437993dfb09be.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libdashmap-cbff546743893ae8.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libnum_cpus-dcca6eaa9a867502.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcfg-6a14a03f7283eb63.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/librustc_hash-54b1951e0f68f43c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libtt-4075df7681b69c6f.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsmol_str-7b86c88d873864b7.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libstdx-8aac6bad1f8d1b47.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libalways_assert-55ff9a72924c8c50.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libanyhow-24750e0664105842.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libpaths-4414e6eaf2e9886d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblsp_server-87b41d63e6844f0d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libserde_json-7dd6844449a0adf0.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libryu-665a7e26063c2198.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libitoa-b2dd719a9a05fd7c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libindexmap-e6aaaf357b53c9af.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libhashbrown-ce91282522c4bd8c.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcrossbeam_channel-af2116fb986c33c2.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcrossbeam_utils-6a1f2aab6cbb8c23.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblazy_static-9a5612c4ffa99001.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libserde-310e13bb6d875e61.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libparking_lot-e2754c62df5c1796.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libparking_lot_core-f6fe5d9860a37730.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblibc-4816ae2df154bcf8.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libsmallvec-fb50e08a522fd433.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblock_api-177f151344f4dd4f.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libscopeguard-3ca1ff91345ee529.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libinstant-ac0c9dd9c7cb24ed.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libenv_logger-1c9f58c3ee4ad324.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/liblog-25158b16f20055a9.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/libcfg_if-dc7ee0bd0a9e8e27.rlib" "-Wl,--start-group" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libstd-364d3b4e6025ca41.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libpanic_unwind-81f284557e87071e.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libminiz_oxide-387c0e2be2b9d8bd.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libadler-40b3641274497f52.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libobject-7577a45438104cae.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libmemchr-480d447e5b167c42.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libaddr2line-22f51ff911e3b56a.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libgimli-cc98e88c41139545.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libstd_detect-26bcae18fb229539.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/librustc_demangle-6d796e7b0d82f738.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libhashbrown-cb2165b05debd5b5.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/librustc_std_workspace_alloc-e8669aeb95c2086e.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libunwind-c2ea65b46dc73f38.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libcfg_if-d552ec2b0ef0e26d.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/liblibc-8bb272c92ab91b39.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/liballoc-f0621291da63dac4.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/librustc_std_workspace_core-222388273c11f823.rlib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libcore-40a63f4138175ec6.rlib" "-Wl,--end-group" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib/libcompiler_builtins-da8eb62249e6d183.rlib" "-Wl,-Bdynamic" "-lc" "-lrt" "-lutil" "-lexecinfo" "-lutil" "-lprocstat" "-lexecinfo" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lrt" "-lutil" "-lexecinfo" "-lutil" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-freebsd/lib" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-freebsd/release/deps/rust_analyzer-753b6b7bd99bfdcf" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-Wl,-rpath,$ORIGIN/../lib"
  = note: /usr/local/x86_64-unknown-freebsd11/bin/ld: cannot find -lprocstat
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `rust-analyzer` due to previous error
```

https://github.com/rust-lang-ci/rust/runs/3501286458

**Comment by lnicola** [comment]
Looks like we pull in `libprocstat` via `libc`, but I'm not sure what's up there.

**Comment by m-ou-se** [comment]
The rest of the rust repo is still on `libc 0.2.99`. Maybe something broke in `libc 0.2.100` on freebsd?

**Comment by m-ou-se** [comment]
This was added in 0.2.100: https://github.com/rust-lang/libc/pull/2313

**Comment by lnicola** [comment]
Yeah, I saw that PR. I'm trying to reproduce the compile error, but I'm not sure how to build for that target.

**Comment by m-ou-se** [comment]
Maybe it's easier to just downgrade to libc 0.2.99 for now, unless you need something from 0.2.100.

**Comment by lnicola** [comment]
Yeah, but it's a transitive dep and we'll have to remember not to upgrade it, so it would be better if rust-lang/rust upgraded instead.

**Comment by devnexen** [comment]
this is bizarre since libprocstat exists since freebsd 9 https://www.freebsd.org/cgi/man.cgi?query=libprocstat&sektion=3&format=html and as far as I remember I never needed to think of installing it.

**Comment by jyn514** [comment]
> Yeah, but it's a transitive dep and we'll have to remember not to upgrade it, so it would be better if rust-lang/rust upgraded instead.

You could pin it in Cargo.toml so cargo doesn't touch it when you run cargo upgrade.

**Pull request closed without merging**
