### PR TITLE
Unify FnKind between AST visitors and make WalkItemKind more straight forward

### PR DESCRIPTION
**Pull request by maxcabrajac**
Unifying `FnKind` requires a bunch of changes to `WalkItemKind::walk` signature so I'll change them in one go

related to #128974 & #127615 

r? @petrochenkov

### CODE REVIEW

**Comment by maxcabrajac** [comment]
@bors r=petrochenkov

Is this it? I had to look around in other merged PRs haha

**Comment by petrochenkov** [comment]
>Is this it? I had to look around in other merged PRs

It's it, it just needs someone with approval permissions.

@bors r+

**Pull request merged**
