### PR TITLE
make `TypeError` impl `Copy`

### PR DESCRIPTION
**Pull request by compiler-errors**
r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
Uh, I wonder if this is noise.

@rust-timer build e1fce0925985ca02299b27bba245048945cd0b22

**Comment by compiler-errors** [comment]
Ugh, can't re-run rust-timer? :s

**Comment by compiler-errors** [comment]
I'm gonna try one more time to see if that was just noise

**Comment by compiler-errors** [comment]
so it was just noise 💢

**Comment by compiler-errors** [comment]
r? compiler

**Comment by jackh726** [comment]
@bors r-
needs rebase

**Pull request merged**
