### PR TITLE
Separate unit tests

### PR DESCRIPTION
**Pull request by chansuke**
I'm working on #61097.

About half of the modules are done but dozens of modules are still remaining. I will rebase and squash the commits later.

### CODE REVIEW

**Comment by petrochenkov** [comment]
@chansuke 
Thanks!

r=me once the rebase is done and CI is green
Every transitioned test module has an immediate value, I'd personally benefit from libsyntax tests being transitioned [y](https://github.com/rust-lang/rust/pull/61669) [e](https://github.com/rust-lang/rust/pull/61616) [s](https://github.com/rust-lang/rust/pull/61541) [t](https://github.com/rust-lang/rust/pull/60965) [e](https://github.com/rust-lang/rust/pull/60740) [r d a y](https://github.com/rust-lang/rust/pull/60679).

r? @petrochenkov 
@bors p=1 (conflict-prone)
cc @rust-lang/compiler

**Comment by Centril** [comment]
@bors p=10

More conflict prone than you think.

**Comment by chansuke** [comment]
@petrochenkov Sorry for the late reply and thanks for the information (and about`libsyntax` too). I will handle that, and yes, I will `r=you` after that.

**Comment by petrochenkov** [comment]
@chansuke 
I've rebased this, fixed tidy issues and currently running testing.
I'll push to this PR and r+ after the testing is complete.

General hint for the following PRs - instead of
```rust
foo.rs

=>

foo/mod.rs
foo/tests.rs
```
you can use
```rust
foo.rs

=>

foo.rs
foo/tests.rs
```
This way you can avoid most of conflicts and won't have to rebase all the time.

**Pull request merged**
