### PR TITLE
Use pathdiff crate

### PR DESCRIPTION
**Pull request by FedericoPonzi**
I wanted to tackle a simple issue, and stumbled upon #67108: this pr removes the function which was exported to the external crate as required in the todo/issue.
I've tested it with:
```
./x.py build --stage 1 --keep-stage 1 src/librustc_codegen_ssa 
```
And it looks like it's compiling

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm going to r? @Manishearth as it's their crate -- I guess I'm not opposed but feels a little bit odd in some sense :)

Maybe this should be an unstable API on Paths? Based on the comment here it sounds like at some point itwas...

**Comment by Manishearth** [comment]
@bors r+

Yeah, it was at some point, and I made an external crate by copying out rustc's code to get access to it again.

**Comment by FedericoPonzi** [comment]
According to CI's logs:
```
Dependencies not explicitly permitted:
* pathdiff 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)
```
Unfortunatey I wasn't aware of this step. How can I request permissions for it?

**Comment by Manishearth** [comment]
@bors r- 


Oh yeah there's src/tools/tidy/src/deps.rs

**Comment by FedericoPonzi** [comment]
I've added the "pathdiff" package there, thanks!

**Comment by Manishearth** [comment]
For future reference, make sure to run `./x.py fmt` and `./x.py tidy`. I've fixed up the issues in the rollup so you're fine for now.

**Comment by FedericoPonzi** [comment]
Will do, sorry about that and thanks for giving this PR a more meaningful name!

> For future reference, make sure to run `./x.py fmt` and `./x.py tidy`. I've fixed up the issues in the rollup so you're fine for now.

Will do, sorry about that and thanks for giving this issue a more meaningful name

**Comment by eddyb** [comment]
> I've tested it with:
> ```
> ./x.py build --stage 1 --keep-stage 1 src/librustc_codegen_ssa
> ```

For the record, if you just want to make sure it compiles, `./x.py check src/librustc_codegen_ssa` (maybe even without the path, I don't know if it makes much of a difference), should be much faster.

But you can also replace `--stage 1 --keep-stage 1` with `--stage 0`, I am not aware of any benefits to building the compiler at stage 1 by using `--keep-stage`, only ~~pain and suffering~~ additional complexity.

**Pull request merged**
