### PR TITLE
Issue error on `compile-fail` header in UI test

### LINKED ISSUE #68732: compiletest: issue error on `compile-fail` in UI tests
Context: https://github.com/rust-lang/rust/pull/68728#discussion_r373783462.

In `src/test/ui` we should not allow:
```rust
// compile-fail

/* stuff */
```

This issue has been assigned to @Tyg13 via [this comment](https://github.com/rust-lang/rust/issues/68732#issuecomment-581102759).

### PR DESCRIPTION
**Pull request by Tyg13**
Fixes #68732 

r? @Centril

### CODE REVIEW

**Comment by Centril** [comment]
Can you double check that this passes with `--bless --pass check --compare-mode=nll`?

**Comment by Tyg13** [comment]
@Centril looks good

[test.log](https://github.com/rust-lang/rust/files/4143609/test.log)

**Comment by Centril** [comment]
Thanks! @bors r+

**Pull request merged**
