### PR TITLE
trans: Use LLVM's writeArchive to modify archives

### PR DESCRIPTION
**Pull request by alexcrichton**
We have previously always relied upon an external tool, `ar`, to modify archives
that the compiler produces (staticlibs, rlibs, etc). This approach, however, has
a number of downsides:
- Spawning a process is relatively expensive for small compilations
- Encoding arguments across process boundaries often incurs unnecessary overhead
  or lossiness. For example `ar` has a tough time dealing with files that have
  the same name in archives, and the compiler copies many files around to ensure
  they can be passed to `ar` in a reasonable fashion.
- Most `ar` programs found do **not** have the ability to target arbitrary
  platforms, so this is an extra tool which needs to be found/specified when
  cross compiling.

The LLVM project has had a tool called `llvm-ar` for quite some time now, but it
wasn't available in the standard LLVM libraries (it was just a standalone
program). Recently, however, in LLVM 3.7, this functionality has been moved to a
library and is now accessible by consumers of LLVM via the `writeArchive`
function.

This commit migrates our archive bindings to no longer invoke `ar` by default
but instead make a library call to LLVM to do various operations. This solves
all of the downsides listed above:
- Archive management is now much faster, for example creating a "hello world"
  staticlib is now 6x faster (50ms => 8ms). Linking dynamic libraries also
  recently started requiring modification of rlibs, and linking a hello world
  dynamic library is now 2x faster.
- The compiler is now one step closer to "hassle free" cross compilation because
  no external tool is needed for managing archives, LLVM does the right thing!

This commit does not remove support for calling a system `ar` utility currently.
We will continue to maintain compatibility with LLVM 3.5 and 3.6 looking forward
(so the system LLVM can be used wherever possible), and in these cases we must
shell out to a system utility. All nightly builds of Rust, however, will stop
needing a system `ar`.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 
cc @rust-lang/tools

**Comment by cmr** [comment]
cc @Kingsquee

**Comment by cmr** [comment]
I believe this should also remove the ability to specify an "ar" program in target specs.

**Comment by alexcrichton** [comment]
> I believe this should also remove the ability to specify an "ar" program in target specs?

Indeed! I haven't done so here as I suspect we'll want to leave them around for awhile to work with 3.5/3.6 (and perhaps bugs that come up in the LLVM implementation). We'll also probably want to just accept them as an option for forever and perhaps start emitting a warning one day saying "you don't need to do this any more".

**Comment by Kingsquee** [comment]
Beautiful!

**Comment by richo** [comment]
Does this bring us one step closer to not needing a bunch of flags for seamless cross compiling? (has it been tested for cross compilation?)

**Comment by alexcrichton** [comment]
@richo It should indeed, yes! I haven't tested this particular PR for cross compilation yet, but every time before I've used llvm-ar for cross compilation it works, so I suspect that this will also work.

We also may have to turn this off by default and put it behind a `-Z` flag if it becomes problematic, but that's what we have nightlies for :)

**Comment by alexcrichton** [comment]
@bors: r-

Investigating some failures on OSX

**Comment by alexcrichton** [comment]
re-r? @brson 

I've now discovered that there are multiple formats for archives (or at least various tweaks on flavors). The known formats (at least by LLVM) [are these](https://github.com/llvm-mirror/llvm/blob/89a5e2532d8284fe01992acd1e96b6fce4ffffb8/include/llvm/Object/Archive.h#L178-L183), and our current revision of LLVM can only emit archives in the GNU format. [Support has been added](https://github.com/llvm-mirror/llvm/commit/b13e877e27d6b85f598a8a95b746acafcfb26710) very recently for BSD formats (what I believe OSX uses), but it's not present in our LLVM version currently and we can't upgrade due to some assorted test failures.

I updated this to add an `archive_format` field to target specifications. Right now a value of "gnu" (which linux-like targets and MinGW all use) indicates that LLVM should be used, otherwise we fall back to the system `ar` tool. I'm hoping we can over time pull all targets into using LLVM so we don't have any lagging behind.

**Pull request merged**
