### PR TITLE
Add a precondition check for Layout::from_size_align_unchecked

### PR DESCRIPTION
**Pull request by saethlin**
Ran into this while looking into https://github.com/rust-lang/miri/issues/3679. This is of course not the cause of the ICE, but the reproducer doesn't encounter a precondition check and it ought to.

### CODE REVIEW

**Comment by joboet** [comment]
Good idea! This code is *highly* perf-sensitive though, so let's see what the impact of the extra MIR is.
@bors try @rust-timer

**Comment by saethlin** [comment]
@rust-timer build 5489321f47676a047199924cde6fecca98ff983f

**Comment by saethlin** [comment]
I see. We're playing this game again.

**Comment by saethlin** [comment]
I'm going to do some experiments, some of these commits might be janky.

**Comment by saethlin** [comment]
I don't trust the primary benchmark regressions.

The secondary regressions are real though, and they appear because we now have a new function that we need to instantiate in the compiled crate, because precondition checks are `#[inline]`. The new function that implements the check is rather large (90 lines of LLVM IR including blanks). I can probably reduce the regression by making the library code look worse, but my instinct is that libs prefers the library implementation to be clear, even if it has a touch of compile-time overhead for debug builds of tiny crates.

**Comment by joboet** [comment]
> I don't trust the primary benchmark regressions.
> 
> The secondary regressions are real though, and they appear because we now have a new function that we need to instantiate in the compiled crate, because precondition checks are `#[inline]`. The new function that implements the check is rather large (90 lines of LLVM IR including blanks). I can probably reduce the regression by making the library code look worse, but my instinct is that libs prefers the library implementation to be clear, even if it has a touch of compile-time overhead for debug builds of tiny crates.

Perf looks much better and I'd accept those regressions. However, I'd quite like to see what it would look like if you moved the validity checking (both alignment and size) into a separate function (`is_size_align_valid` or something like that), used it in both `from_size_align` versions and then initialized the `Layout` directly in both. That might get rid of some MIR while still being clear.

**Review by joboet — COMMENTED** [review]
I think the problem might be that we introduce the checks multiple times:
`from_size_align` calls `is_size_align_valid` and then calls `from_size_align_unchecked`, which calls `is_size_align_valid` itself. And `is_size_align_valid` calls `is_power_of_two` and then `Alignment::new_unchecked` which calls `is_power_of_two` again. And `Alignment::new_unchecked` is also called in `Layout::from_size_align_unchecked` so `is_power_of_two` is called 5 times in total! Obviously the optimizer will figure this out, but still, we shouldn't even generate that MIR. Could you try using `transmute`s here to create the `Alignment` once the checks have completed and maybe also in `Alignment::new`?

**Comment by saethlin** [comment]
> `Alignment::new_unchecked` which calls `is_power_of_two` again

That is not true. The precondition check in `Alignment::new_unchecked` is cfg'd out. The function is just a transmute wrapper in the distributed standard library.

**Comment by saethlin** [comment]
To be quite clear: The only instantiation that this PR adds is a tiny wrapper function. That's why it looks bad in instruction-counting micro-benchmarks. I do not think it is worth my or your time to pursue improvement on the above perf report. Adding debug checks regresses build times of tiny programs and I don't think that should be surprising to anyone.

I will continue to poke at this to mollify my reviewer, but that is all.

**Comment by joboet** [comment]
Sorry, I got too carried away microoptimizing this... Anyway, this looks great! Thank you for your patience.
@bors r+

**Comment by joboet** [comment]
As for performance:

All the `Layout` code is highly performance-sensitive. The UB check is worth its cost, and we even golfed that down to a minimum.

@rustbot label +perf-regression-triaged

**Pull request merged**
