### PR TITLE
Remove `#[rustc_deprecated]`

### PR DESCRIPTION
**Pull request by jhpratt**
This removes `#[rustc_deprecated]` and introduces diagnostics to help users to the right direction (that being `#[deprecated]`). All uses of `#[rustc_deprecated]` have been converted. CI is expected to fail initially; this requires #95958, which includes converting `stdarch`.

I plan on following up in a short while (maybe a bootstrap cycle?) removing the diagnostics, as they're only intended to be short-term.

### CODE REVIEW

**Comment by jhpratt** [comment]
(that's the failure I was expecting)

**Comment by jhpratt** [comment]
CI is green, but I'd still like to make a few more changes before this should be merged.

@rustbot author

**Comment by jhpratt** [comment]
After playing whack-a-mole with tests and running into a spurious error, CI is once again green. I'm happy with where this is now. Ready for review @joshtriplett!

@rustbot ready

**Comment by wesleywiser** [comment]
r? rust-lang/compiler

**Review by compiler-errors — APPROVED** [review]
Looks good to me

**Pull request merged**
