### PR TITLE
Removed ascii_ctype

### PR DESCRIPTION
**Pull request by hellow554**
This is stable since rust 1.24.0 and is no longer behind a feature gate

### CODE REVIEW

**Comment by mattico** [comment]
Reference: https://github.com/rust-lang/rust/issues/39658#issuecomment-342439907

Functions were initially implemented on AsciiExt, then moved to inherent impls on `u8` and `char`, then stabilized.

It's probably time to remove the old AsciiExt methods ([here](https://github.com/rust-lang/rust/blob/master/src/libstd/ascii.rs#L165)), but that doesn't have to happen in this PR.

**Comment by hellow554** [comment]
Didn't see that issue. I will adresse the other tasks as well (I hope), give me one day :)

**Comment by hellow554** [comment]
@mattico I may need your help here. 

```
error[E0407]: method `is_ascii_control` is not a member of trait `AsciiExt`
   --> libstd/ascii.rs:209:9
    |
209 |         fn is_ascii_control(&self) -> bool { self.is_ascii_control() }
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `AsciiExt`
...
218 |     delegating_ascii_ctype_methods!();
    |     ---------------------------------- in this macro invocation
```
Do I want to remove the macro at all? I'm not quiet sure.

```
error[E0407]: method `is_ascii_hexdigit` is not a member of trait `AsciiExt`
   --> libstd/ascii.rs:261:5
    |
261 | /     fn is_ascii_hexdigit(&self) -> bool {
262 | |         self.iter().all(|b| b.is_ascii_hexdigit())
263 | |     }
    | |_____^ not a member of trait `AsciiExt`
```

Same here. I'm not sure, why this fails. Am I missing something?

**Comment by mattico** [comment]
I think all you have to do is remove the `delegating_ascii_ctype_methods!()` macro.

**Comment by hellow554** [comment]
I'm sorry, but I cannot get this working. I'm not very sure what to do and which macro does what, because I'm not that deep into the codebase. I just tried to get rid of the feature flag in the doctests :) 
A PR based on https://github.com/rust-lang/rust/issues/39658#issuecomment-342439907 would be nice to see

**Comment by LukasKalbertodt** [comment]
@hellow554 Sorry for replying so late, I didn't see this thread. 

I wrote this macro to avoid boilerplate code and you should be able to remove it. I could offer some help/mentoring with the PR, if you want @hellow554? I'm by no means experienced in the compiler source, but I could help in this case, I think.

**Pull request closed without merging**
