### PR TITLE
de-stabilize unsized raw ptr methods for Weak

### PR DESCRIPTION
**Pull request by RalfJung**
@Mark-Simulacrum this is the patch re: https://github.com/rust-lang/rust/pull/80407.

I couldn't figure out the branch it needs to go on though, stable is still the old stable but beta already the new beta...?

### CODE REVIEW

**Comment by pthariensflame** [comment]
Does this need `relnotes`?

**Comment by RalfJung** [comment]
It landed just before the release, so it shouldn't need relnotes I think.

**Pull request merged**
