### PR TITLE
[EXPERIMENTAL] Bisect cmake bootstrap issue

### PR DESCRIPTION
**Pull request by clubby789**
r? @ghost
Investigating #134344
try-job: dist-apple-various

### CODE REVIEW

**Comment by clubby789** [comment]
0.1.50 is bad, trying 0.1.49
@bors try

**Comment by clubby789** [comment]
1.49 is bad - checking ba6b3bc4712af4cda5513f01699b00631248f576

@bors try

**Comment by clubby789** [comment]
[ba6b3bc](https://github.com/rust-lang/cmake-rs/commit/ba6b3bc4712af4cda5513f01699b00631248f576) good, trying [`edc139b77`](https://github.com/rust-lang/cmake-rs/commit/edc139b772553ba9ff7e47eee4b1b2670490e8cb)

@bors try

**Comment by clubby789** [comment]
[`edc139b77`](https://github.com/rust-lang/cmake-rs/commit/edc139b772553ba9ff7e47eee4b1b2670490e8cb) bad, trying [`d6688089`](https://github.com/rust-lang/cmake-rs/commit/d6688089f1e96f5bb0ecdb770b83da4994c4b3ef)

@bors try

Ths commit looks very likely to be the bad one, so let's make sure

**Comment by jieyouxu** [comment]
https://github.com/rust-lang/cmake-rs/commit/d6688089f1e96f5bb0ecdb770b83da4994c4b3ef bad, trying https://github.com/rust-lang/cmake-rs/commit/163d33f9f437c40f322c559b95795f959fe68de0

@bors try

**Comment by clubby789** [comment]
[`d66808`](https://github.com/rust-lang/cmake-rs/commit/d6688089f1e96f5bb0ecdb770b83da4994c4b3ef) confirmed bad. Will see if I can investigate a fix

**Comment by clubby789** [comment]
This should fix it - if this works and the most recent version of cmake works, let's try and land the bump
@bors try

**Comment by clubby789** [comment]
Oops, need to use the 'bad' version of cc

@bors try

**Comment by clubby789** [comment]
Hmm. Looks like telling Cmake we're using iOS causes it to run `iOS-initalize.cmake`, which errors because of

https://github.com/rust-lang/rust/blob/387b245664a81f58260a6b565aa0b2fdf19752fb/src/bootstrap/src/core/build_steps/llvm.rs#L400-L402

**Comment by clubby789** [comment]
Not sure why `-DCMAKE_OSX_SYSROOT=/" "-DCMAKE_OSX_DEPLOYMENT_TARGET=" "` is still being passed. I'll leave this for now until I have access to a Mac to iterate faster

**Pull request closed without merging**
