### PR TITLE
DO NOT MERGE (yet): Enable `-Zdrop-tracking` by default

### PR DESCRIPTION
**Pull request by eholk**
This is not quite ready to merge yet because we still need fixes for a couple of issues (See #97331 for details), but we can probably go ahead and kick off a crater run to see if there are any additional regressions we don't know about yet.

@bors r? @wesleywiser

### CODE REVIEW

**Comment by wesleywiser** [comment]
@bors try
@craterbot run mode=build-only

**Comment by wesleywiser** [comment]
@craterbot run mode=build-only

**Comment by jyn514** [comment]
@craterbot run mode=build-only

**Comment by eholk** [comment]
@craterbot run mode=build-only

**Comment by eholk** [comment]
Huh, that's weird that we're suddenly getting a bunch of new test failures. I wonder what changed in this code? Maybe #101692 had some effect here?

**Comment by cjgillot** [comment]
https://github.com/rust-lang/rust/pull/101692 has duplicated each generator test case to have the 3 variants (no drop tracking, drop tracking, and MIR drop tracking). This may be where the errors come from.

**Comment by Swatinem** [comment]
I believe this can be closed now that https://github.com/rust-lang/rust/pull/107421 has landed?

**Comment by eholk** [comment]
> I believe this can be closed now that #107421 has landed?

Yes! Sorry for the slow response!

**Pull request closed without merging**
