### PR TITLE
Add example for HashMap::entry()

### PR DESCRIPTION
**Pull request by bluss**
Add example for HashMap::entry()

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks so much!

**Comment by steveklabnik** [comment]
(also, please make sure to see the AUTHORs PR, so that you're in there)

**Comment by steveklabnik** [comment]
oh, @bluss , lol, I just replied because of highfive. I though @nrc said he fixed that bug?

**Comment by bluss** [comment]
I don't know, I use a non-unique email for my commits, that's probably what's messing things up.

**Pull request merged**
