### PR TITLE
Allow setting hashmap toml values in `./configure`

### LINKED ISSUE #108621: `./configure` doesn't allow setting hashmap toml values
I tried this code:

```sh
./configure --set llvm.build-config.LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=YES
```

I expected to see this happen: configure.py generates a toml file with the contents
```toml
build-config = {"LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN"="YES"}
```

Instead, this happened:
```
; ./configure --set llvm.build-config.LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=YES
configure: processing command line
configure: 
configure: llvm.build-config.LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN := YES
configure: build.configure-args := ['--set', 'llvm.build-config.LLVM_TEMPORARILY_ ...
Traceback (most recent call last):
  File "/Users/jyn/src/rust/./src/bootstrap/configure.py", line 486, in <module>
    configure_section(sections[section_key], section_config)
  File "/Users/jyn/src/rust/./src/bootstrap/configure.py", line 456, in configure_section
    lines[i] = "{} = {}".format(key, to_toml(value))
  File "/Users/jyn/src/rust/./src/bootstrap/configure.py", line 445, in to_toml
    raise RuntimeError('no toml')
RuntimeError: no toml
```

### Meta

HEAD is branched from 5423745db8b434fcde54888b35f518f00cce00e4.

### PR DESCRIPTION
**Pull request by KittyBorgX**
Fixes https://github.com/rust-lang/rust/issues/108621

### CODE REVIEW

**Comment by albertlarsan68** [comment]
This doesn't do the right thing, here is a quick replacement you can inspire from:
```python
"{" + ", ".join(map(lambda a: "{} = {}".format(to_toml(a[0]), to_toml(a[1])), value.items())) + "}"
```

**Comment by KittyBorgX** [comment]
> This doesn't do the right thing, here is a quick replacement you can inspire from:
> 
> ```python
> "{" + ", ".join(map(lambda a: "{} = {}".format(to_toml(a[0]), to_toml(a[1])), value.items())) + "}"
> ```

Thank you so much! 
I'm just curious : My code emmited `build-config = {'LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN' = 'YES'}` too, what was the mistake with it?

**Comment by albertlarsan68** [comment]
`to_toml({"a": "5", "b": "A"})` produced `{'a', 'b'=5,'A'}`, which is not valid.
Do you understand the difference between the old and the new?

**Comment by KittyBorgX** [comment]
> `to_toml({"a": "5", "b": "A"})` produced `{'a', 'b'=5,'A'}`, which is not valid. Do you understand the difference between the old and the new?

I hadn't given it much thought till now, I replicated a few examples and understood the difference 😅

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+ rollup

**Pull request merged**
