### PR TITLE
Make copy/copy_nonoverlapping fn's again

### PR DESCRIPTION
**Pull request by pnkfelix**
Make copy/copy_nonoverlapping fn's again, rather than intrinsics.

This a short-term change to address issue #84297.

It effectively reverts PRs #81167 #81238 (and part of #82967), #83091, and parts of #79684.

### CODE REVIEW

**Comment by pnkfelix** [comment]
oh wait I need a regression test too. :)

**Comment by pnkfelix** [comment]
> The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2749343743) [(plain)](https://github.com/rust-lang/rust/commit/85cb915b66ca51eacba916deb97aecdbd6c889e3/checks/2749343743/logs)
> Click to see the possible cause of the failure (guessed by this bot)
> 
> ```
> configure: rust.channel         := nightly
> configure: rust.debug-assertions := True
> configure: llvm.assertions      := True
> configure: dist.missing-tools   := True
> configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
> configure: writing `config.toml` in current directory
> configure: 
> configure: run `python /checkout/x.py --help`
> configure: 
> ---
>     Checking rand v0.7.3
>     Checking alloc v0.0.0 (/checkout/library/alloc)
>     Checking std v0.0.0 (/checkout/library/std)
>     Checking core v0.0.0 (/checkout/library/core)
> error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
>    |
>    |
> 60 |             ptr::write(&mut res as *mut _, 42);
> 
> 
> error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
>    |
>    |
> 84 |             (&mut res as *mut i32).write(42);
> 
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0015`.
> For more information about this error, try `rustc --explain E0015`.
> error: could not compile `core`
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "i686-pc-windows-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--locked" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/library/test/Cargo.toml" "--all-targets" "-p" "test" "-p" "panic_abort" "-p" "alloc" "-p" "core" "-p" "panic_unwind" "-p" "unwind" "-p" "term" "-p" "std" "-p" "proc_macro" "--message-format" "json-render-diagnostics"
> failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu --all-targets
> Build completed unsuccessfully in 0:00:31
> ```

weird, my local build+tests passed. Looking now.

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=1

Mostly just reverting some stuff, including unstable const-fn-ing, but seems good.

**Comment by JohnTitor** [comment]
```
2021-06-08T22:05:45.3809175Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2021-06-08T22:05:45.4311038Z Can't find any online and idle self-hosted runner in current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-06-08T22:05:45.5571495Z Found online and idle hosted runner in current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-06-08T22:05:45.7017989Z ##[section]Finishing: Request a runner to run this job
```

@bors retry

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/238009tcompilermeetings/52925weekly2021061054818.html#242213559)

@rustbot label +beta-accepted

**Comment by Mark-Simulacrum** [comment]
beta backported in #86203

**Comment by rylev** [comment]
@pnkfelix @Mark-Simulacrum This change led to some moderate [performance regressions](https://perf.rust-lang.org/compare.html?start=47d38752c65359e1f4558d7a06935982fb8b486f&end=eab201df7028ebb6812c0b1a01702ac6ecfcceed&stat=instructions:u). I imagine performance regressions are somewhat expected going from intrinsics to function calls as it seems LLVM might have more to process now. A quick look at where the regressions are happening shows it to be mostly in codegen. Any thoughts?

**Comment by Mark-Simulacrum** [comment]
This was a stopgap measure to fix regressions; it should be fixable in the long run. I don't think it makes sense to prioritize the work too much though.

**Pull request merged**
