### PR TITLE
Update mailmap

### PR DESCRIPTION
**Pull request by jonas-schievink**
https://github.com/rust-lang/team/pull/1071 / https://github.com/rust-lang/thanks/pull/58

### CODE REVIEW

**Comment by jhpratt** [comment]
For the purposes of rust-lang/thanks#58, I think it would be better if there were something differentiating different people. So "ghost1" for the email, for example. This avoids merging people that aren't actually the same person.

**Comment by oli-obk** [comment]
> This avoids merging people that aren't actually the same person.

I think that's fine. Just like github merges all deleted accounts to @ghost

r? @oli-obk 

@bors r+ rollup

**Comment by jhpratt** [comment]
@oli-obk The reason I say that is because it would affect rankings and whatnot.

**Comment by oli-obk** [comment]
We could stop showing `Ghost` at all in the rankings

**Comment by jhpratt** [comment]
I initially considered that, but that as well is objectively incorrect. There _is_ a person associated with it; they just don't want their name shown any more.

**Comment by oli-obk** [comment]
hmm... I did not consider that. I don't know what the right thing to do here is, but I also personally don't like the rankings anyway, so I should not really be part of the discussion of details.

For now it doesn't matter as we only have a single Ghost entry. We can start coming up with a new policy or just start numbering them as they come.

**Pull request merged**
