### PR TITLE
Backport some LLVM compile-time improvements

### PR DESCRIPTION
**Pull request by nikic**
Pick up two LLVM patches that reduce number of alias analysis queries, to see whether that gives any visible improvement.

r? @ghost

### CODE REVIEW

**Comment by nikic** [comment]
Minor improvements to opt builds and a 1.5% improvement on bootstrap.

r? @nagisa Does this seems worthwhile? If so, I'll push this to the branch and update the submodule reference.

**Comment by nagisa** [comment]
This does seem quite worthwhile yes. I'm comfortable with the LICM changes, since they have been landed upstream, but I wasn't able to find the diffs or commits corresponding to the `[Loads]` commits upstream. If they have been submitted, can the differential be referenced in the commit messages? If not, can we quantify the impact of the LICM change alone vs the improvements gained from the `Loads` commits?

**Comment by nikic** [comment]
@nagisa The upstream commits are https://github.com/llvm/llvm-project/commit/7c706aa0d88fa2ca99be7951073454b42e1891dd, https://github.com/llvm/llvm-project/commit/e0615bcd39fd863361ce8eb68aafdfcdcd8b067d, https://github.com/llvm/llvm-project/commit/3d8f842712d49b0767832b6e3f65df2d3f19af4e, https://github.com/llvm/llvm-project/commit/29034f38769cfced34c1758dd03e02991f2308ba. I should get into the habit of using `git cherry-pick -x`...

**Comment by nagisa** [comment]
Yeah LGTM then, r=me once these commits end up in a proper branch.

**Comment by leonardo-m** [comment]
This seems to have fixed some performance regressions (perhaps with the help of other things in the last week) introduced by LLVM12.

**Pull request merged**
