### PR TITLE
rustc: Forbid interpolated tokens in the HIR

### LINKED ISSUE #40946: warning: Quasi-quoting might make incremental compilation very inefficient: NtIdent(..)
I have a macro like this:

```rust
#[macro_export]
macro_rules! define_proc_macros {
    (
        $(
            $( #[$attr:meta] )*
            pub fn $proc_macro_name: ident ($input: ident : &str) -> String
            $body: block
        )+
    ) => {
        $(
            $( #[$attr] )*
            #[proc_macro_derive($proc_macro_name)]
            pub fn $proc_macro_name(derive_input: ::proc_macro::TokenStream)
                                    -> ::proc_macro::TokenStream {
                let $input = derive_input.to_string();
                let $input = $crate::_extract_input(&$input);
                $body.parse().unwrap()
            }
        )+
    }
}

pub fn _extract_input(derive_input: &str) -> &str {
    // …
}
```

When I use it, I get the warning in the title *twice* for every generated functions. When I move things into one crate to avoid "note: this error originates in a macro outside of the current crate", the span of the warning is on `$proc_macro_name` in `#[proc_macro_derive($proc_macro_name)]`.

Steps to reproduce: run`CARGO_INCREMENTAL=1 cargo +nightly build -p cssparser-macros` in https://github.com/servo/rust-cssparser/.

I don’t understand this warning and what I can do about it. What does quasi-quoting mean in this context? How bad is the inefficiency really? Is it possible to fix it while keeping this macro’s flexibility?

CC @michaelwoerister and @nikomatsakis for #37787 that added this warning.

### PR DESCRIPTION
**Pull request by alexcrichton**
Right now the HIR contains raw `syntax::ast::Attribute` structure but nowadays
these can contain arbitrary tokens. One variant of the `Token` enum is an
"interpolated" token which basically means to shove all the tokens for a
nonterminal in this position. A "nonterminal" in this case is roughly analagous
to a macro argument:

    macro_rules! foo {
        ($a:expr) => {
            // $a is a nonterminal as an expression
        }
    }

Currently nonterminals contain namely items and expressions, and this poses a
problem for incremental compilation! With incremental we want a stable hash of
all HIR items, but this means we may transitively need a stable hash *of the
entire AST*, which is certainly not stable w/ node ids and whatnot. Hence today
there's a "bug" where the "stable hash" of an AST is just the raw hash value of
the AST, and this only arises with interpolated nonterminals. The downside of
this approach, however, is that a bunch of errors get spewed out during
compilation about how this isn't a great idea.

This PR is focused at fixing these warnings, basically deleting them from the
compiler. The implementation here is to alter attributes as they're lowered from
the AST to HIR, expanding all nonterminals in-place as we see them. This code
for expanding a nonterminal to a token stream already exists for the
`proc_macro` crate, so we basically just reuse the same implementation there.

After this PR it's considered a bug to have an `Interpolated` token and hence
the stable hash implementation simply uses `bug!` in this location.

Closes #40946

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @nrc 

cc @jseyfried

**Comment by michaelwoerister** [comment]
Looks great! @jseyfried or @nrc, would you care to review this?

**Comment by TimNN** [comment]
@bors r-

* `compile-fail/hygiene/globs.rs` causes an ICE
* `compile-fail/hygiene/nested_macro_privacy.rs`: expected error not found: field `i` of struct `foo::S` is private

**Comment by kennytm** [comment]
@bors retry #43402

<details>

```
[01:21:38] failures:
[01:21:38] 
[01:21:38] ---- [run-make] run-make\issue-26092 stdout ----
[01:21:38] 	
[01:21:38] error: make failed
[01:21:38] status: exit code: 2
[01:21:38] command: "make"
[01:21:38] stdout:
[01:21:38] ------------------------------------------
[01:21:38] PATH="/c/projects/rust/build/x86_64-pc-windows-msvc/test/run-make/issue-26092.stage2-x86_64-pc-windows-msvc:C:\projects\rust\build\x86_64-pc-windows-msvc\stage2\bin:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Windows Kits/10/bin/10.0.14393.0/x64:/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64:/c/projects/rust/build/x86_64-pc-windows-msvc/stage0-tools/x86_64-pc-windows-msvc/release/deps:/c/projects/rust/build/x86_64-pc-windows-msvc/stage0-sysroot/lib/rustlib/x86_64-pc-windows-msvc/lib:/c/Program Files (x86)/Inno Setup 5:/c/Python27:/mingw64/bin:/usr/bin:/c/Perl/site/bin:/c/Perl/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files/7-Zip:/c/Program Files/Microsoft/Web Platform Installer:/c/Tools/GitVersion:/c/Tools/PsTools:/c/Program Files/Git LFS:/c/Program Files (x86)/Subversion/bin:/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn:/c/Program Files/Microsoft SQL Server/120/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/ManagementStudio:/c/Tools/WebDriver:/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.4:/c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/PrivateAssemblies:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI/wbin:/c/Ruby193/bin:/c/Tools/NUnit/bin:/c/Tools/xUnit:/c/Tools/MSpec:/c/Tools/Coverity/bin:/c/Program Files (x86)/CMake/bin:/c/go/bin:/c/Program Files/Java/jdk1.8.0/bin:/c/Python27:/c/Program Files/nodejs:/c/Program Files (x86)/iojs:/c/Program Files/iojs:/c/Users/appveyor/AppData/Roaming/npm:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/MSBuild/14.0/Bin:/c/Tools/NuGet:/c/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files/Microsoft DNX/Dnvm:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/130/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/c/Program Files (x86)/Apache/Maven/bin:/c/Python27/Scripts:/c/Tools/NUnit3:/c/Program Files/Mercurial:/c/Program Files/LLVM/bin:/c/Program Files/dotnet:/c/Program Files/erl8.3/bin:/c/Tools/curl/bin:/c/Program Files/Amazon/AWSCLI:/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/140:/c/Program Files (x86)/Yarn/bin:/c/Program Files/Git/cmd:/c/Program Files/Git/usr/bin:/c/ProgramData/chocolatey/bin:/c/Tools/vcpkg:/c/Program Files (x86)/nodejs:/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code:/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager:/c/Users/appveyor/AppData/Local/Yarn/bin:/c/Users/appveyor/AppData/Roaming/npm:/c/Program Files/AppVeyor/BuildAgent:/c/projects/rust:/c/projects/rust/handle" 'C:\projects\rust\build\x86_64-pc-windows-msvc\stage2\bin\rustc.exe' --out-dir /c/projects/rust/build/x86_64-pc-windows-msvc/test/run-make/issue-26092.stage2-x86_64-pc-windows-msvc -L /c/projects/rust/build/x86_64-pc-windows-msvc/test/run-make/issue-26092.stage2-x86_64-pc-windows-msvc  -o "" blank.rs 2>&1 | \
[01:21:38] 		grep -i 'No such file or directory'
[01:21:38] 
[01:21:38] ------------------------------------------
[01:21:38] stderr:
[01:21:38] ------------------------------------------
[01:21:38] make: *** [Makefile:4: all] Error 1
[01:21:38] 
[01:21:38] ------------------------------------------
[01:21:38] 
[01:21:38] thread '[run-make] run-make\issue-26092' panicked at 'explicit panic', src\tools\compiletest\src\runtest.rs:2433:8
[01:21:38] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:21:38] 
[01:21:38] 
[01:21:38] failures:
[01:21:38]     [run-make] run-make\issue-26092
```

</details>

**Comment by Manishearth** [comment]
This may have caused a regression wrt doc attributes

https://github.com/rust-lang/rust/issues/44730

**Pull request merged**
