### PR TITLE
Update rust-installer to fix rust-lang-nursery/rustup.rs#1092

### PR DESCRIPTION
**Pull request by brson**
r? @TimNN

cc @alexcrichton @ranma42

### CODE REVIEW

**Comment by brson** [comment]
p=1

**Comment by brson** [comment]
Fixes https://github.com/rust-lang-nursery/rustup.rs/issues/1092

**Comment by TimNN** [comment]
@bors retry

* `[02:17:18] test thread\mod.rs - thread::Thread (line 726) has been running for over 60 seconds`

**Comment by TimNN** [comment]
@bors retry

```
[01:11:04] failures:
[01:11:04] 
[01:11:04] ---- [debuginfo-gdb] debuginfo-gdb\borrowed-unique-basic.rs stdout ----
[01:11:04] 	NOTE: compiletest thinks it is using GDB without native rust support
[01:11:04] NOTE: compiletest thinks it is using GDB version 7010001
[01:11:04] 
[01:11:04] error: gdb failed to execute
[01:11:04] thread '[debuginfo-gdb] debuginfo-gdb\borrowed-unique-basic.rs' panicked at 'explicit panic', src\tools\compiletest\src\runtest.rs:1646
[01:11:04] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:11:04] 
[01:11:04] 
[01:11:04] failures:
[01:11:04]     [debuginfo-gdb] debuginfo-gdb\borrowed-unique-basic.rs
[01:11:04] 
[01:11:04] test result: FAILED. 95 passed; 1 failed; 11 ignored; 0 measured
```

**Comment by frewsxcv** [comment]
lets see if this is spurious

@bors retry

**Comment by alexcrichton** [comment]
@bors: retry

* the... compiler wedged? Don't think I've seen that one before

**Pull request merged**
