### PR TITLE
Prepare 1.61.0 beta release

### PR DESCRIPTION
**Pull request by emilyalbini**
Just a channel and RLS bump this time.

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Bumped RLS again to include https://github.com/rust-lang/rls/pull/1772.

@bors r+ p=1000 rollup=never

**Comment by ehuss** [comment]
@bors retry

x86_64-apple-2:
```
Received request to deprovision: The request was cancelled by the remote provider.
```

**Comment by ehuss** [comment]
Oh, I did not look at https://github.com/rust-lang/rls/pull/1772 closely enough.  Racer was not bumped on this side, and that PR effectively didn't do anything since that Cargo.lock is ignored here.

**Comment by pietroalbini** [comment]
Whelp, good catch! Bumped the `Cargo.lock` on the monorepo.

@bors r+ p=1000 rollup=never

**Pull request merged**
