### PR TITLE
submodules: update clippy from 66df92ae to c8e3cfbd

### LINKED ISSUE #65888: `clippy-driver` no longer builds after rust-lang/rust#65885
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#65885, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Changes:
````
travis: temporarily disable rustfmt ci check until #4742 is resolved
rustup https://github.com/rust-lang/rust/pull/65792/
Fix ICE #4579
Add regression test for ICE #4579
Run update_lints for Unicode lint
Re-add false positive check
Add raw string regression test for useless_format lint
Re-factor useless_format lint
Update Unicode lint tests
[Backported] Rustup to https://github.com/rust-lang/rust/pull/59545
````

Fixes #65888

r? @oli-obk @Manishearth

### CODE REVIEW

**Comment by lzutao** [comment]
Did you use the clippy on master branch? The clippy commits in this PR seems really old.

**Comment by Manishearth** [comment]
It was a merge-in of backport commits, they're supposed to be old

**Comment by matthiaskrgr** [comment]
Could we get a prio bump? Otherwise this might not land before clippy is broken again.

**Pull request merged**
