### PR TITLE
Fix nightly-only experimental API display

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Before:

screen shot 2017-02-23 at 12 53 09

After:

screen shot 2017-02-23 at 12 51 40

r? @frewsxcv

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Forgot to check tests. Will update as soon as I can.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Pull request merged**
