### PR TITLE
Bump Rustfmt and RLS

### LINKED ISSUE #78340: `rls` no longer builds after rust-lang/rust#78334
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#78334, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @jonas-schievink, do you think you would have time to do the follow-up work?
If so, that would be great!

### LINKED ISSUE #78341: `rustfmt` no longer builds after rust-lang/rust#78334
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#78334, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @jonas-schievink, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by ghedo**
Should hopefully fix #78341 and fix #78340.

### CODE REVIEW

**Comment by calebcartwright** [comment]
@Mark-Simulacrum - besides addressing the broken toolstate, the rustfmt update also include the bump of the rustc-ap-* crates that contain the changes from #77774 which fixed a panic on the rustfmt side.

I believe #77774 was, ostensibly, backported due to wanting to address that panic issue, so i'm not sure if there's a desire to do something similar here. Probably worth noting we've had a flood of duplicative reports about the same panic issue over in rustfmt.

**Review by Xanewok — APPROVED** [review]

**Comment by Xanewok** [comment]
CI says that RLS tests fail but I can't reproduce locally. However, I'm getting a Rustfmt compilation error:
```
error: this `#[deprecated]` annotation has no effect
   --> src/tools/rustfmt/src/lib.rs:276:1
    |
276 | #[deprecated(note = "Use FormatReportFormatter instead")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the unnecessary deprecation attribute
    |
    = note: `#[deny(useless_deprecated)]` on by default
```

**Comment by calebcartwright** [comment]
Wonder if this comes from #78626, as there weren't any related changes on the rustfmt side that would've introduced this

**Comment by calebcartwright** [comment]
@Xanewok - I'm going to have to cut a new release to address this, so another PR to RLS will be on your way shortly

**Comment by calebcartwright** [comment]
@ghedo - would you be willing to update the submods here to pull in the latest changes?

rustfmt should now be on the [rustfmt-1.4.24](https://github.com/rust-lang/rustfmt/tree/rustfmt-1.4.24) branch on commit https://github.com/rust-lang/rustfmt/commit/eb894d53708122a67762de9489881c11aa8ce257 and rls now up to https://github.com/rust-lang/rls/commit/dab1468d6aeed0e49f7d0569c1d2128b5a7751e0

**Comment by ghedo** [comment]
Sure, done. Let's see how it goes :crossed_fingers:

**Comment by Xanewok** [comment]
Last hurdle:
```
the following dependencies are duplicated although they have the same features enabled:
the following dependencies have different features:
  byteorder 1.3.4 (registry+https://github.com/rust-lang/crates.io-index)
    `rustfmt` additionally enabled features {} at "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libbyteorder-c5e2ae63a4128905.rlib"
    `rls` additionally enabled features {"default", "std"} at "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libbyteorder-286667693f43f34e.rlib"

to fix this you will probably want to edit the local src/tools/rustc-workspace-hack/Cargo.toml crate, as that will update the dependency graph to ensure that these crates all share the same feature set
```

**Comment by Mark-Simulacrum** [comment]
beta-nominating per https://github.com/rust-lang/rust/pull/78775#issuecomment-722478443

@bors r+

**Comment by Aaron1011** [comment]
This fixes the toolstate.

@bors p=1

**Comment by Aaron1011** [comment]
Spurious failure: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/apple-x86_64.20gha.20checks

@bors retry

**Pull request merged**
