### PR TITLE
rustbuild: support setting verbosity in config.toml

### PR DESCRIPTION
**Pull request by Keruspe**
Most if not all the configuration is settable trhough config.toml but the verbosity isn't yet.

This avoids having to pass -v to x.py on each command if you want verbosity to be always on.

### CODE REVIEW

**Comment by aturon** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
Could you also update `src/bootstrap/config.toml.example` with the new option, where it goes, and a short comment to what it does?

**Comment by Keruspe** [comment]
@alexcrichton Done (I basically copy-pasted the comment from flags.rs for the description)

**Pull request merged**
