### PR TITLE
Move some tests to more reasonable directories - 9

### PR DESCRIPTION
**Pull request by c410-f3r**
cc #73494
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
Could you make a new subdirectory named `stdlib-unit-tests`?
It will contain tests that need to be moved to standard library unit tests (or removed if they are redundant), but that move is not done yet.
And also one more subdirectory named `runtime` for testing the standard library runtime facilities.

After that:

alloca-from-derived-tydesc.rs - can be removed now
estr-uniq.rs - can be removed now
seq-compare.rs - stdlib-unit-tests
lazy-init.rs - borrowck
readalias.rs - can be removed now
writealias.rs - can be removed now
utf8_idents-rpass.rs - parser
commandline-argfile.rs - already moved in https://github.com/rust-lang/rust/pull/90560
running-with-no-runtime.rs - runtime
resolve-issue-2428.rs - resolve
use_inline_dtor.rs - drop
names-of-variants-in-std.rs - stdlib-unit-tests
expr-if.rs - expr/if
semistatement-in-lambda.rs - closures (or parser)
linkage1.rs - linkage-attr
reexport-should-still-link.rs - not sure, cross-crate, or can be removed
signal-alternate-stack-cleanup.rs - runtime
dead-extern-static-no-warning.rs - lint
use-crate-name-alias.rs - can be removed now
instantiable.rs - recursion
c-stack-returning-int64.rs - abi
purity-infer.rs - can be removed now
eq-multidispatch.rs - stdlib-unit-tests
syntax-impl-for-dotdot.rs - parser
export-import.rs - privacy, or can be removed (was testing a long removed export system)
export-multi.rs - can be removed now (was testing a long removed export system)
export-non-interference2.rs - can be removed now (was testing a long removed export system)
export-non-interference3.rs - can be removed now (was testing a long removed export system)
export2.rs - can be removed now (was testing a long removed export system)
similar-tokens.rs - parser
static_sized_requirement.rs - static
lifetime-before-type-params.rs - generics
object-lifetime-*.rs - object-lifetime
macro-quote-cond.rs - proc-macro
proc_macro.rs - proc-macro
while-let.rs - for-loop-while
type-in-nested-module.rs - can be removed now
default-alloc-error-hook.rs - alloc-error?
ranges-precedence.rs -> parser
shift-various-bad-types.rs -> binop?
crate-in-paths.rs -> resolve
attr-usage-repr.rs -> repr
out-of-stack.rs -> runtime
augmented-assignments-feature-gate.rs - can be removed now
builtin-clone.rs -> stdlib-unit-tests
istr.rs -> stdlib-unit-tests
ret-none.rs - can be removed now
question-mark-type-infer.rs - inference (there two similar subdirectories - inference and type-inference, but inference seems to be larger)
prim-with-args.rs - typeck
expr-block-unique.rs - can be removed now
owned-implies-static.rs - regions maybe
typeclasses-eq-example-static.rs - traits

\+

rt-explody-panic-payloads.rs - runtime
stdout-during-shutdown.rs - runtime

**Comment by c410-f3r** [comment]
> Could you make a new subdirectory named `stdlib-unit-tests`? It will contain tests that need to be moved to standard library unit tests (or removed if they are redundant), but that move is not done yet. And also one more subdirectory named `runtime` for testing the standard library runtime facilities.
> 
> After that:
> 
> alloca-from-derived-tydesc.rs - can be removed now estr-uniq.rs - can be removed now seq-compare.rs - stdlib-unit-tests lazy-init.rs - borrowck readalias.rs - can be removed now writealias.rs - can be removed now utf8_idents-rpass.rs - parser commandline-argfile.rs - already moved in #90560 running-with-no-runtime.rs - runtime resolve-issue-2428.rs - resolve use_inline_dtor.rs - drop names-of-variants-in-std.rs - stdlib-unit-tests expr-if.rs - expr/if semistatement-in-lambda.rs - closures (or parser) linkage1.rs - linkage-attr reexport-should-still-link.rs - not sure, cross-crate, or can be removed signal-alternate-stack-cleanup.rs - runtime dead-extern-static-no-warning.rs - lint use-crate-name-alias.rs - can be removed now instantiable.rs - recursion c-stack-returning-int64.rs - abi purity-infer.rs - can be removed now eq-multidispatch.rs - stdlib-unit-tests syntax-impl-for-dotdot.rs - parser export-import.rs - privacy, or can be removed (was testing a long removed export system) export-multi.rs - can be removed now (was testing a long removed export system) export-non-interference2.rs - can be removed now (was testing a long removed export system) export-non-interference3.rs - can be removed now (was testing a long removed export system) export2.rs - can be removed now (was testing a long removed export system) similar-tokens.rs - parser static_sized_requirement.rs - static lifetime-before-type-params.rs - generics object-lifetime-*.rs - object-lifetime macro-quote-cond.rs - proc-macro proc_macro.rs - proc-macro while-let.rs - for-loop-while type-in-nested-module.rs - can be removed now default-alloc-error-hook.rs - alloc-error? ranges-precedence.rs -> parser shift-various-bad-types.rs -> binop? crate-in-paths.rs -> resolve attr-usage-repr.rs -> repr out-of-stack.rs -> runtime augmented-assignments-feature-gate.rs - can be removed now builtin-clone.rs -> stdlib-unit-tests istr.rs -> stdlib-unit-tests ret-none.rs - can be removed now question-mark-type-infer.rs - inference (there two similar subdirectories - inference and type-inference, but inference seems to be larger) prim-with-args.rs - typeck expr-block-unique.rs - can be removed now owned-implies-static.rs - regions maybe typeclasses-eq-example-static.rs - traits
> 
> +
> 
> rt-explody-panic-payloads.rs - runtime stdout-during-shutdown.rs - runtime

Done

**Comment by c410-f3r** [comment]
It is worth noting that `parse` reached 1000 entries

**Comment by petrochenkov** [comment]
>It is worth noting that parse reached 1000 entries

I think we can add a tidy exception to `parser` for now, if it's necessary.
It's a much more reasonable subdirectory than `issues` and the root.
I have ideas how to split it, e.g. the lexer stuff can be moved to `lexer`, but it's a task for a separate PR.

shift-various-bad-types.rs -> binop
syntax-impl-for-dotdot.rs -> parser
similar-tokens.rs -> parser
ranges-precedence.rs -> parser

**Comment by c410-f3r** [comment]
> I have ideas how to split it, e.g. the lexer stuff can be moved to lexer, but it's a task for a separate PR.

Yes, please.

**Pull request merged**
