### PR TITLE
Move auxiliary directories to live with the tests

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is a step for enabling testing of cross-crate incremental compilation. The idea is that instead of having a central auxiliary directory, when you have a `// aux-build:foo.rs` annotation in the test `run-pass/bar.rs`, it will look in (e.g.) `run-pass/aux/foo.rs`. In general, it looks for an `aux` directory in the same directory as the test. We also ignore the `aux` directories when enumerating the set of tests.

As part of this PR, also refactor `runtest.rs` to use methods on a context, which means we can stop passing around context everywhere.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
:snowboarder:

**Comment by nikomatsakis** [comment]
(confusing why that rustdoc error occurs on travis; I didn't see it locally)

**Comment by nikomatsakis** [comment]
Rebased. I'm not sure what happened with that failure though, seems odd.

**Pull request merged**
