### PR TITLE
Rollup of 1 pull requests

### PR DESCRIPTION
**Pull request by Noratrieb**
Successful merges:

 - #126132 (config.example.toml: minor improves)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=126132)

### CODE REVIEW

**Comment by Nilstrieb** [comment]
image
@bors r+ p=1 rollup=never

**Comment by BoxyUwU** [comment]
Thanks for your hard work nora

**Comment by pietroalbini** [comment]
...

**Comment by Nilstrieb** [comment]
NOOOOOOOOOOOOOOOOOO PIETRO

**Pull request closed without merging**
