### PR TITLE
Document panicking cases for integer division and remainder

### PR DESCRIPTION
**Pull request by jturner314**
This PR documents the cases when integer division and remainder operations panic. These operations panic in two cases: division by zero and overflow.

It's surprising that these operations always panic on overflow, unlike most other arithmetic operations, which panic on overflow only when `debug_assertions` is enabled. The panic on overflow for the remainder is also surprising because a return value of `0` would be reasonable in this case. ("Overflow" occurs only for `MIN % -1`.) Since the panics on overflow are somewhat surprising, they should be documented.

I guess it's worth asking: is panic on overflow (even when `debug_assertions` is disabled) the intended behavior? If not, what's the best way forward?

### CODE REVIEW

**Comment by nikomatsakis** [comment]
[RFC 560](https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md) states:

> The operations `/`, `%` for the arguments `INT_MIN` and `-1` will unconditionally panic. This is unconditional for legacy reasons.

Exactly what legacy reasons I had in mind I'm not sure, that sentence kind of amuses me now. =) Nonetheless, I'd say it is clearly intentional, and I imagine that any change here would have to be done over an edition.

**Comment by ojeda** [comment]
Those operations' behavior can differ greatly between architectures (e.g. raising an exception vs. simply returning zero for integer division by zero), so perhaps you intended to normalize it to make things more portable/defined than e.g. C?

**Comment by jturner314** [comment]
> [RFC 560](https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md) states:
> 
> > The operations `/`, `%` for the arguments `INT_MIN` and `-1` will unconditionally panic. This is unconditional for legacy reasons.

Okay, thanks; I missed that statement in the RFC. Since the existing behavior is intentional, I don't propose changing it. I'd just like to describe the existing behavior in the API docs.

> Those operations' behavior can differ greatly between architectures (e.g. hardware exception vs. returning zero for integer division by zero), so perhaps you intended to normalize it to make things more portable/defined than e.g. C?

Woah, do you mean that in Rust, integer division by zero may return zero instead of panicking, or do you mean that this is a platform-specific internal implementation detail hidden by the language?

If Rust does not guarantee that division by zero panics, we should definitely document the set of possible behaviors for division by zero. I've been operating under the assumption that it always results in a panic, and I think I've written code that depends on the panicking behavior for correctness/soundness, which I now need to go and correct...

Would the following documentation be correct for division for signed integers?

> This operation rounds towards zero, truncating any fractional part of the exact result.
>
> #### Division by Zero
>
> Division by zero either panics or returns an incorrect result, such as `0` or `MAX`.
>
> #### Overflow
>
> Division *unconditionally* panics on overflow (i.e. `MIN / -1`), regardless of whether [`overflow-checks`](https://doc.rust-lang.org/rustc/codegen-options/index.html#overflow-checks) or [`debug-assertions`](https://doc.rust-lang.org/rustc/codegen-options/index.html#debug-assertions) is enabled.

**Comment by ojeda** [comment]
> Woah, do you mean that in Rust, integer division by zero may return zero instead of panicking, or do you mean that this is a platform-specific internal implementation detail hidden by the language?

The latter (i.e. I was answering to @nikomatsakis). For instance, under x86_64 a divide error is raised for both, which means in Linux you will get sent `SIGFPE` and your program terminated unless handled. However, under AArch64 you will get `0` (for division by zero) or `INT_MIN` (for `INT_MIN / -1`); and your program will go on its merry way. In C both situations are undefined likely for this reason.

Rust currently emits three branches to check for this and panic if needed, so it seems it is working as expected. I agree it would be nice to document this. :)

**Comment by jturner314** [comment]
Thanks for the clarification. I'm glad that the language guarantees panicking on integer division by zero. The proposed documentation in this PR is correct, then. As I see it, the remaining things to discuss before merging are code style (of the macro changes) and any desired adjustments to the wording in the docs (such as explicitly mentioning `overflow-checks`/`debug-assertions` or the fact that `MIN / -1` is the only case where overflow occurs).

**Pull request merged**
