### PR TITLE
improve "Doesn't live long enough" error

### PR DESCRIPTION
**Pull request by mikhail-m1**
I've fixed only with same case

issue #36537 part of  #35233 
r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
This direction feels like an improvement, though looking back at #36537 I recall we'd decided that it would be something like:

struct_span_error(line 5 at '}, ....)
span_label(line 4 at 'a', "borrow occurs here")
span_label(line 5 at '}',  "a dropped here while still borrowed")

It looks like you moved the span to the end of the block, which sounds right.  I didn't see the labels for some of the errors you updated.  You should add those, too, as I think they'll help the error messages be more readable.

You may also want to consider moving the tests you're updating to be UI tests.  You can see examples in src/test/ui.  They're pretty straightforward, the .stderr file just captures what the output is expected to look like.

**Comment by mikhail-m1** [comment]
@jonathandturner Should I move all changed tests to ui?

**Comment by jonathandturner** [comment]
@mikhail-m1 - feel free to move all the tests you're updating with this PR to UI

**Comment by mikhail-m1** [comment]
@jonathandturner I created new directory in ui, is it ok?

**Comment by jonathandturner** [comment]
@mikhail-m1 - you can put them in src/test/ui/span

**Comment by mikhail-m1** [comment]
@jonathandturner are moved

**Comment by mikhail-m1** [comment]
two new tests in master branch

**Comment by jonathandturner** [comment]
@bors r-

Yeah, looks like there are a few that need to be updated:

```
    [compile-fail] compile-fail/dropck_tarena_cycle_checked.rs
    [compile-fail] compile-fail/dropck_tarena_unsound_drop.rs
```

**Comment by mikhail-m1** [comment]
@jonathandturner  I cannot find this files in master branch. All cfail tests passes.

**Comment by mikhail-m1** [comment]
@jonathandturner Should I put tests from compile-fail-fulldeps in ui too? There is no ui-fulldeps.

**Comment by jonathandturner** [comment]
@mikhail-m1 you can leave the fulldeps tests where they are.  I'm not 100% sure they'll work as ui tests.

**Comment by mikhail-m1** [comment]
test [ui] ui/dropck/dropck-eyepatch-extern-crate.rs ... FAILED
test [ui] ui/dropck/dropck-eyepatch-reorder.rs ... FAILED
test [ui] ui/dropck/dropck-eyepatch.rs ... FAILED

**Comment by mikhail-m1** [comment]
@jonathandturner fixed

**Comment by jonathandturner** [comment]
@mikhail-m1 I think this is ready to land.

The wording for the temporary values can also be updated, but that can happen in a separate PR.

@bors r+

**Pull request merged**
