### PR TITLE
[DO NOT MERGE] Revert "WF-check all ty::Const's, not just array lengths."

### PR DESCRIPTION
**Pull request by lcnr**
checking for a perf regression noted in https://github.com/rust-lang/rust/pull/70107#issuecomment-639852000

Let's see if this automated revert passes CI before starting perf.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@rust-timer queue @bors try

**Comment by jonas-schievink** [comment]
@rust-timer queue 8db9e9bb497ce0b30e28b780f4412393c396d40f

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 8db9e9bb497ce0b30e28b780f4412393c396d40f

**Comment by mark-i-m** [comment]
It looks like reverting this makes very little difference :sweat_smile:

**Pull request closed without merging**
