### PR TITLE
rustdoc: Fix generating documentation from json

### LINKED ISSUE #25108: rustdoc --output-format json command seems broken
I tried this command:

```Shell
> rustdoc --output-format json src/sysinfo.rs
```

On this [repo](https://github.com/GuillaumeGomez/sysinfo).

Result:

```Shell
src/sysinfo.rs:13:1: 13:19 error: use of unstable library feature 'libc'
src/sysinfo.rs:13 extern crate libc;
                  ^~~~~~~~~~~~~~~~~~
src/sysinfo.rs:13:1: 13:19 help: add #![feature(libc)] to the crate attributes to enable
src/processus.rs:43:42: 43:47 error: use of unstable library feature 'libc'
src/processus.rs:43         unsafe { ::ffi::kill(self.pid as c_int, signal as c_int) == 0 }
                                                             ^~~~~
src/processus.rs:43:42: 43:47 help: add #![feature(libc)] to the crate attributes to enable
src/processus.rs:43:59: 43:64 error: use of unstable library feature 'libc'
src/processus.rs:43         unsafe { ::ffi::kill(self.pid as c_int, signal as c_int) == 0 }
                                                                              ^~~~~
src/processus.rs:43:59: 43:64 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:15:5: 15:41 error: use of unstable library feature 'libc'
src/system.rs:15 use libc::types::os::arch::posix01::stat;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/system.rs:15:5: 15:41 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:16:5: 16:17 error: use of unstable library feature 'libc'
src/system.rs:16 use libc::c_char;
                     ^~~~~~~~~~~~
src/system.rs:16:5: 16:17 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:17:5: 17:39 error: use of unstable library feature 'libc'
src/system.rs:17 use libc::funcs::posix01::stat_::lstat;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/system.rs:17:5: 17:39 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:279:35: 279:39 error: use of unstable library feature 'libc'
src/system.rs:279                     let mut buf : stat = unsafe { ::std::mem::uninitialized() };
                                                    ^~~~
src/system.rs:279:35: 279:39 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:280:90: 280:96 error: use of unstable library feature 'libc'
src/system.rs:280                     let res = unsafe { lstat(result.to_str().unwrap().as_ptr() as *const c_char, &mut buf as *mut stat) };
                                                                                                           ^~~~~~
src/system.rs:280:90: 280:96 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:280:115: 280:119 error: use of unstable library feature 'libc'
src/system.rs:280                     let res = unsafe { lstat(result.to_str().unwrap().as_ptr() as *const c_char, &mut buf as *mut stat) };
                                                                                                                                    ^~~~
src/system.rs:280:115: 280:119 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:280:40: 280:45 error: use of unstable library feature 'libc'
src/system.rs:280                     let res = unsafe { lstat(result.to_str().unwrap().as_ptr() as *const c_char, &mut buf as *mut stat) };
                                                         ^~~~~
src/system.rs:280:40: 280:45 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:282:40: 282:47 error: use of unstable library feature 'libc'
src/system.rs:282                     if res < 0 || (buf.st_mode  & S_IFMT) != S_IFLNK {
                                                         ^~~~~~~
src/system.rs:282:40: 282:47 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:282:51: 282:57 error: use of unstable library feature 'libc'
src/system.rs:282                     if res < 0 || (buf.st_mode  & S_IFMT) != S_IFLNK {
                                                                    ^~~~~~
src/system.rs:282:51: 282:57 help: add #![feature(libc)] to the crate attributes to enable
src/system.rs:282:62: 282:69 error: use of unstable library feature 'libc'
src/system.rs:282                     if res < 0 || (buf.st_mode  & S_IFMT) != S_IFLNK {
                                                                               ^~~~~~~
src/system.rs:282:62: 282:69 help: add #![feature(libc)] to the crate attributes to enable
src/ffi.rs:10:19: 10:24 error: use of unstable library feature 'libc'
src/ffi.rs:10 	pub fn kill(pid: c_int, signal: c_int) -> c_int;
              	                 ^~~~~
src/ffi.rs:10:19: 10:24 help: add #![feature(libc)] to the crate attributes to enable
src/ffi.rs:10:34: 10:39 error: use of unstable library feature 'libc'
src/ffi.rs:10 	pub fn kill(pid: c_int, signal: c_int) -> c_int;
              	                                ^~~~~
src/ffi.rs:10:34: 10:39 help: add #![feature(libc)] to the crate attributes to enable
src/ffi.rs:10:44: 10:49 error: use of unstable library feature 'libc'
src/ffi.rs:10 	pub fn kill(pid: c_int, signal: c_int) -> c_int;
              	                                          ^~~~~
src/ffi.rs:10:44: 10:49 help: add #![feature(libc)] to the crate attributes to enable
error: aborting due to 16 previous errors
thread '<unnamed>' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:192
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "rustc failed"', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729
```

So then I added the "missing" feature (that's weird by the way) and then I got:

```Shell
> rustdoc --output-format json src/sysinfo.rs 
thread '<unnamed>' panicked at 'Rust generated JSON is invalid: SyntaxError(EOFWhileParsingObject, 1, 99690)', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustdoc/lib.rs:525
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729
```

I guess rustdoc is broken somehow ? Here's my current rustdoc version:

```Shell
> rustdoc --version
rustdoc 1.1.0-nightly (ce1150b9f 2015-05-04) (built 2015-05-04)
```

### PR DESCRIPTION
**Pull request by mitaa**
fixes #25108

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR @mitaa! I've actually been somewhat wary about fixing this in the past as I'm not sure if we want to actually export a JSON interface to rustdoc. It's likely to be highly brittle, undocumented, and not really suitable for most purposes.

That being said, we should probably either make the decision to fix it or remove it altogether! This seems like as good a place as any to get the conversation started at least.

cc @rust-lang/tools, thoughts on JSON documentation in rustdoc? Perhaps we should just rip it out?

**Comment by nrc** [comment]
Do we know if anyone uses it? Or wants to use it?

**Comment by alexcrichton** [comment]
One reason I believe this comes up is that it's so prominently mentioned. The `rustdoc -h` page indicates that reading/writing json output is supported, and I suspect that some just try that out, see it doesn't work, and then submit a bug.

**Comment by brson** [comment]
I'm in favor of just removing it. If somebody wants to produce better docs they will probably just write rustdoc 3.

**Comment by brson** [comment]
cc @cmr

**Comment by cmr** [comment]
And thus the cycle repeats. All this has happened before, and all of it will happen again.

On April 6, 2016 7:16:02 AM GMT+10:00, Brian Anderson <notifications@github.com> wrote:
>I'm in favor of just removing it. If somebody wants to produce better
>docs they will probably just write rustdoc 3.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/rust/pull/32698#issuecomment-205986504

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alexcrichton** [comment]
We discussed this in the tools triage meeting today and the conclusion was that we probably just want to jettison this support for now. We can perhaps add it back later if need be but for now it's unstable enough and likely hasn't ever worked that it shouldn't break anything and we probably don't want to stabilize it.

Would you be ok preparing a PR for that @mitaa?

**Comment by mitaa** [comment]
Sure!

**Comment by UtherII** [comment]
Personally i planned to use it as a base to see if I could make a better looking documentation, but the generated json is pretty complex anyway. I will look if i can make rustdoc generate clean xml.

**Comment by alexcrichton** [comment]
@UtherII yeah that was the theoretical purpose of the JSON, but 60% of the work in rustdoc is just taking this JSON and render it, so it wouldn't be an easy task adding an entirely new frontend unfortunately :(

**Pull request closed without merging**
