### PR TITLE
doc: guarantee call order for sort_by_cached_key

### PR DESCRIPTION
**Pull request by digama0**
`slice::sort_by_cached_key` takes a caching function `f: impl FnMut(&T) -> K`, which means that the order that calls to the caching function are made is user-visible. This adds a clause to the documentation to promise the current behavior, which is that `f` is called on all elements of the slice from left to right, unless the slice has len < 2 in which case `f` is not called.

For example, this can be used to ensure that the following code is a correct way to involve the index of the element in the sort key:
```rust
let mut index = 0;
slice.sort_by_cached_key(|x| (my_key(index, x), index += 1).0);
```

### CODE REVIEW

**Comment by yaahc** [comment]
I cant think of any reasons we'd want to change the iteration order for how we setup the keys, so I see no reason not to commit to a stable iteration order and am happy to start the FCP.

@rfcbot merge

**Comment by joshtriplett** [comment]
I share @BurntSushi's concern here about potential future restrictions of such a guarantee. I'd like to see if we can guarantee less and still be useful; notably, I'd be in favor of the "at most once" guarantee.

**Comment by yaahc** [comment]
Sorry for the late update on this, but we reviewed this PR during our [libs-api team meeting](https://hackmd.io/3QZn0wUxTQKn9qjzHqvb3Q) on 2021/12/22 and concluded that we'd like to unblock this PR changing to the "at most once" guarantee mentioned by @joshtriplett.

**Comment by digama0** [comment]
Wording has been updated to remove the ordering guarantee and clarify the "at most once" part.

**Comment by yaahc** [comment]
@rfcbot resolve example-usecases

**Comment by yaahc** [comment]
Thank you again @digama0!

@bors r+ rollup

**Pull request merged**
