### PR TITLE
[beta] Update cargo on beta.

### PR DESCRIPTION
**Pull request by ehuss**
This brings in rust-lang/cargo#4940 which adds `"workspace_root"` to `cargo metadata` so that tools can resolve the new relative paths in symbols and compiler messages.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
So just to clarify, why are we backporting what seems like a simple feature? This seems unusual, and a cursory look didn't find any discussion (feel free to point me at it if it exists).

**Comment by eddyb** [comment]
@Mark-Simulacrum Paths in error messages and whatnot became relative to `src`, which broke basically everyone's workflow. However, #47280 might already include this, I'm not sure.

**Comment by alexcrichton** [comment]
@Mark-Simulacrum yes this is a minor new features which brings in a [fix for a bug on beta](https://github.com/rust-lang/cargo/issues/4933), and should be good to go!


@bors: r+

**Comment by alexcrichton** [comment]
Thanks @ehuss!

**Comment by alexcrichton** [comment]
@bors: retry

Apparently a [30 second timeout](https://github.com/rust-lang/rust/blob/3e49ada7528bf664b2ccc8516a9ef7d21849a70b/src/test/run-pass/tcp-stress.rs#L28-L32) isn't always enough...

**Comment by alexcrichton** [comment]
@bors: retry

* osx network issues

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/46903

**Comment by alexcrichton** [comment]
I'm gonna close in favor of https://github.com/rust-lang/rust/pull/47553 as the queue's a little backed up, hopefully when we land it we won't have to land much else in beta!

**Pull request closed without merging**
