### PR TITLE
remove workaround for make prepare and use dry-run build instead

### PR DESCRIPTION
**Pull request by onur-ozkan**
Removes an annoying hard-coded logic.

try-job: x86_64-msvc

### CODE REVIEW

**Comment by Kobzol** [comment]
Uhh, how does this not fail on the normal build. Maybe we should only do this check outside of dry run.

**Comment by onur-ozkan** [comment]
> Uhh, how does this not fail on the normal build.

I don't know honestly. Probably in normal mode we set up some executables but in dry-run mode we don't; so the binary check fails.

> Maybe we should only do this check outside of dry run.

[Done](https://github.com/rust-lang/rust/pull/130620/commits/126d3031a36a1210f592c1ed432eafd720412f9c) that.

**Comment by onur-ozkan** [comment]
> The job **`x86_64-msvc`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/10975960164/job/30476205582) [(plain)](https://github.com/rust-lang-ci/rust/commit/515be3bc45817ebc7a21a8c79137bed05b965c92/checks/30476205582/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)
> ```
> thread 'main' panicked at src\core\sanity.rs:360:17:
> 
> cmake does not support Visual Studio generators.
> 
> This is likely due to it being an msys/cygwin build of cmake,
> rather than the required windows version, built using MinGW
> 
> If you are building under msys2 try installing the mingw-w64-x86_64-cmake
> package instead of cmake:
> 
> 
> $ pacman -R cmake && pacman -S mingw-w64-x86_64-cmake
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Build completed unsuccessfully in 0:00:57
> make: *** [Makefile:98: prepare] Error 1
> Command failed. Attempt 2/5:
> Command failed. Attempt 2/5:
> ##[group]Building bootstrap
>     Finished `dev` profile [unoptimized] target(s) in 0.09s
> ##[endgroup]
> thread 'main' panicked at src\core\sanity.rs:360:17:
> 
> cmake does not support Visual Studio generators.
> 
> This is likely due to it being an msys/cygwin build of cmake,
> rather than the required windows version, built using MinGW
> 
> If you are building under msys2 try installing the mingw-w64-x86_64-cmake
> package instead of cmake:
> 
> 
> $ pacman -R cmake && pacman -S mingw-w64-x86_64-cmake
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Build completed unsuccessfully in 0:00:00
> make: *** [Makefile:98: prepare] Error 1
> Command failed. Attempt 3/5:
> Command failed. Attempt 3/5:
> ##[group]Building bootstrap
>     Finished `dev` profile [unoptimized] target(s) in 0.09s
> ##[endgroup]
> thread 'main' panicked at src\core\sanity.rs:360:17:
> 
> cmake does not support Visual Studio generators.
> 
> This is likely due to it being an msys/cygwin build of cmake,
> rather than the required windows version, built using MinGW
> 
> If you are building under msys2 try installing the mingw-w64-x86_64-cmake
> package instead of cmake:
> 
> 
> $ pacman -R cmake && pacman -S mingw-w64-x86_64-cmake
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Build completed unsuccessfully in 0:00:00
> make: *** [Makefile:98: prepare] Error 1
> Command failed. Attempt 4/5:
> Command failed. Attempt 4/5:
> ##[group]Building bootstrap
>     Finished `dev` profile [unoptimized] target(s) in 0.09s
> ##[endgroup]
> thread 'main' panicked at src\core\sanity.rs:360:17:
> 
> cmake does not support Visual Studio generators.
> 
> This is likely due to it being an msys/cygwin build of cmake,
> rather than the required windows version, built using MinGW
> 
> If you are building under msys2 try installing the mingw-w64-x86_64-cmake
> package instead of cmake:
> 
> 
> $ pacman -R cmake && pacman -S mingw-w64-x86_64-cmake
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Build completed unsuccessfully in 0:00:00
> make: *** [Makefile:98: prepare] Error 1
> Command failed. Attempt 5/5:
> Command failed. Attempt 5/5:
> ##[group]Building bootstrap
>     Finished `dev` profile [unoptimized] target(s) in 0.09s
> ##[endgroup]
> thread 'main' panicked at src\core\sanity.rs:360:17:
> 
> cmake does not support Visual Studio generators.
> 
> This is likely due to it being an msys/cygwin build of cmake,
> rather than the required windows version, built using MinGW
> 
> If you are building under msys2 try installing the mingw-w64-x86_64-cmake
> package instead of cmake:
> 
> 
> $ pacman -R cmake && pacman -S mingw-w64-x86_64-cmake
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Build completed unsuccessfully in 0:00:00
> make: *** [Makefile:98: prepare] Error 1
> The command has failed after 5 attempts.
> ```

What the hack. How this didn't happen with the previous `make prepare`..

**Pull request merged**
