### PR TITLE
Bring back `x86_64-sun-solaris` target to rustup

### LINKED ISSUE #85098: `x86_64-sun-solaris` target was removed without warning in Rust 1.52
#82216 removed the _alias_ of `x86_64-sun-solaris` to `x86_64-pc-solaris`, but as far as I can tell did not remove the target itself.

After inquiring on Zulip, it was pointed out that the `sun-solaris` target was demoted to tier three, meaning builds are no longer provided. It appears this was done with no discussion, warning, or even a mention in the release notes.

Given that the `pc-solaris` target hasn't been around for that long (I think? feel free to tell me I'm wrong), I think this change should be reverted. My CI unexpectedly failed after being unable to download the target, and the only solution that wouldn't involve a notable increase in complexity of the CI script is to outright remove the checks for Solaris/Illumos — a let loss for everyone.

cc @Mark-Simulacrum

### PR DESCRIPTION
**Pull request by kulikjak**
Change #82216 removed now deprecated target `x86_64-sun-solaris` from CI, thus making it no longer possible to use `$ rustup target add x86_64-sun-solaris` to install given target (see #85098 for details). Since there should be a period of time between the deprecation and removal, this PR brings it back (while keeping the new one as well).

Please, correct me if I am wrong; my assumption that these Docker scripts are being used to build artifacts later used by `rustup` might be incorrect.

Closes #85098.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Preemptively nominating for beta, but will need to review later.

**Comment by jhpratt** [comment]
If this is just an issue with the binary being available, this technically wouldn't need to be tied to a release, correct? I think having a build for Rust 1.52 would be useful, as otherwise there would be a seemingly arbitrary gap in the availability of the target.

**Comment by Mark-Simulacrum** [comment]
I don't think it's likely that we'll produce another point release this cycle, so there probably won't be 1.52 artifacts published. cc @rust-lang/release for thoughts on that.

**Comment by Mark-Simulacrum** [comment]
This PR looks OK to me otherwise, though I note it doesn't attempt to alter the build toolchain for the illumos target back to sun from pc, which changed in https://github.com/rust-lang/rust/pull/82216/files#diff-f7fe7525804df85adb4a03efa70e96ee893009d6260066cde665abb8088b8cbeR21.

I admit to not really knowing if the build toolchain makes any difference - I don't think that PR changed anything else. Certainly we don't ship -pc-illumos and -sun-illumos or anything like that...

cc @steveklabnik @jculow @pmooney

**Comment by jhpratt** [comment]
Perhaps I should be a bit clearer on what I was saying. Why does this need a point release at all? All this does is generate the binary that rustup then downloads, correct? If so, what's to prevent the creation of a binary for Rust 1.52.0/1.52.1? Checksums for something?

**Comment by Mark-Simulacrum** [comment]
We don't have the ability right now to partially edit an existing release, not sure whether it's completely impossible due to checksums, but not something we can do right now on an implementation level.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

Alright, let's get this merged in. I think it's an improvement -- not *quite* back to where we where before, particularly on the illumos target, but having not heard back there I'm inclined to let that stay as-is. It's not clear how much the toolchain that builds the compiler matters for those purposes, and regardless, further work is always possible in future PRs -- for now this should get the breakage in 1.52 due to a missing tier-2 target fixed.

Approving for beta backport so we only have one 'missing' release -- 1.52.

**Pull request merged**
