### PR TITLE
WIP: remove compiler plugin API for syntax transformers

### PR DESCRIPTION
**Pull request by matklad**
cc: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Removing.20.60Register.3A.3Aregister_macro.60.20compiler.20extension.20point

Things to check:

* make sure that servo doesn't break
* fix unstable book

### CODE REVIEW

**Comment by petrochenkov** [comment]
This doesn't remove the fundamental possibility to add syntactic plugins, only helper functions, so r=me after updating the docs/examples/etc.

**Comment by matklad** [comment]
>This doesn't remove the fundamental possibility to add syntactic plugins

Hm, I am confused by this statement. `register_syntax_extension` is the only thing that writes to `syntax_exts` field, and it is being removed. the field is public, but plugin writers are not supposed to use it, so it does remove fundamental ability from plugin writers?

**Comment by petrochenkov** [comment]
>the field is public

Well, that's what I meant.
If you have a plugin you still can migrate, technically.

**Comment by matklad** [comment]
Hm, https://github.com/rust-lang/rust/pull/64675 proposes to remove the whole compiler plugin infrastructure, so I think its best to just wait for that.

**Comment by Centril** [comment]
Seems we are not removing them as soon as I'd like so meanwhile we should remove some stuff. :)

**Comment by JohnTitor** [comment]
Ping from triage: @matklad any updates on this?

**Comment by Mark-Simulacrum** [comment]
@matklad visiting for triage -- this would be good to rebase and land, I think.

Ideally we'd entirely remove syntactic extension plugins -- I _believe_ all or almost all use cases are replaceable via proc macro today (though possibly in an unstable way, but plugins are unstable anyway) -- so we should be able to make that move. Servo, Clippy, etc. don't appear to use it.

**Comment by joelpalmer** [comment]
Ping from triage: @matklad any updates on this?

**Comment by matklad** [comment]
Heh, I think empirical evidence shows that I am swamped with rust-analyzer task at the moment :( 

Let's close this for now: I plan to get back to this, but I can't give any ETA at the moment.

**Pull request closed without merging**
