### PR TITLE
Mark `Parser::eat`/`check` methods as `#[must_use]`

### PR DESCRIPTION
**Pull request by compiler-errors**
These methods return a `bool`, but we probably should either use these values or explicitly throw them away (e.g. when we just want to unconditionally eat a token if it exists).

I changed a few places from `eat` to `expect`, but otherwise I tried to leave a comment explaining why the `eat` was okay.

This also adds a test for the `pattern_type!` macro, which used to silently accept a missing `is` token.

### CODE REVIEW

**Comment by compiler-errors** [comment]
lol rustfmt 🤦

**Review by jieyouxu — APPROVED** [review]
The compiler changes look reasonable to me, not sure what the rustfmt change procedure is.

**Comment by compiler-errors** [comment]
I'll push a commit on top for rustfmt. I will just suppress the warnings rather than affect any logic.

**Review by jieyouxu — APPROVED** [review]
Thanks, r=me once PR CI is green

**Comment by Kobzol** [comment]
@rust-timer build 61c9d375755ed3fe33f71520ecc99cd4ef9c8fc6 (just testing the collector)

**Pull request merged**
