### PR TITLE
Get rid of double indirection in string interner

### PR DESCRIPTION
**Pull request by petrochenkov**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

cc @rust-lang/libs, just a heads up about this unstable API. Seems fine for compiler perf but I think it's something we'll want to handle regardless one day anyway.

**Comment by bluss** [comment]
Will the sized deallocation even be correct? This code is a bit Jackie than the standard for libs.

**Comment by bluss** [comment]
Hackier.

**Comment by petrochenkov** [comment]
@bluss 
>Will the sized deallocation even be correct?

Yes, deallocation size (`size_of_val`) and allocation size (`(2 + aligned_len) * sizeof(usize)`) are supposed to be equal, that's why I set the "metadata" part of the fat pointer and align up the allocation size.
It'd be nice to have some safer (non-coercion) way to create DST structs, but there's none at the moment (to my knowledge).

**Comment by petrochenkov** [comment]
@bluss 
I've added an assert for allocation/deallocation sizes.

**Comment by bluss** [comment]
Oh cool, I see. I didn't realize even the trailing end would be rounded up to alignment.

**Comment by petrochenkov** [comment]
Aha, buildbot is alive again.
@bors r=alexcrichton

**Pull request merged**
