### PR TITLE
`get_or_insert` for HashMap and more

### PR DESCRIPTION
**Pull request by DasLixou**
this adds a little helper method to HashMap for inserting a value if it isn't contained yet.

also planned with `get_mut` and other types like `Vec` or `HashSet`

---

this is my first PR so I'm looking forward for feedback :3

### CODE REVIEW

**Comment by DasLixou** [comment]
> Hi there!
> 
> This feature is already available using `Entry` API: you can obtain an `Entry` object via call to [`entry()`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry) and then update the value using various methods such as [`or_insert(V)`](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.or_insert).

Would it be smart to make inline functions which refer to those?

**Comment by JarvisCraft** [comment]
I don't think so: having one such shorthand for Entry's method may lead to a reasonable question "Why not to add other shorthands for Entry methods", thus it would be logical to duplicate all other methods which looks like a bad idea.

IMO current Entry API is already good enough.

Note: I am not a core libraries developer and this is just my personal opinion.

**Comment by davemilter** [comment]
> IMO current Entry API is already good enough.

In fact it is really bad, for keys like `String` you need to allocate memory every time
 you use "entry api", instead of creating key only if insert is nessesary.
But "get_or_insert" didn't solve this problem.

**Comment by JarvisCraft** [comment]
> In fact it is really bad, for keys like String you need to allocate memory every time
you use "entry api", instead of creating key only if insert is nessesary.

Look at [`or_insert_with`](https://doc.rust-lang.org/stable/std/collections/hash_map/enum.Entry.html#method.or_insert_with) which creates the value on demand.

**Comment by DasLixou** [comment]
Ok then I’ll close this

**Comment by pronebird** [comment]
> > In fact it is really bad, for keys like String you need to allocate memory every time
> > you use "entry api", instead of creating key only if insert is nessesary.
> 
> Look at [`or_insert_with`](https://doc.rust-lang.org/stable/std/collections/hash_map/enum.Entry.html#method.or_insert_with) which creates the value on demand.

`entry()` takes value and not reference so the key is always allocated. `or_insert_with` has nothing to do with this.

**Pull request closed without merging**
