### PR TITLE
Remove feature gated examples from the reference

### LINKED ISSUE #24573: Examples in beta docs using unstable features
http://doc.rust-lang.org/1.0.0-beta.2/reference.html#match-expressions
Unstable features are not allowed in beta/stable, so examples should be probably redoed.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #24573

### CODE REVIEW

**Comment by alexcrichton** [comment]
I can see where we may want to remove as many feature-gated examples as possible, but some of these seem like they may still be useful? For example the one showing off slice patterns is probably good to keep.

**Comment by pnkfelix** [comment]
maybe we should move them to an isolated section of the documentation?  That way the examples are preserved, without having them in the middle of the text that users on the beta or release channels are reading?

**Comment by steveklabnik** [comment]
> maybe we should move them to an isolated section of the documentation?

Yes, so the reason I just killed these examples is that we have a specific unstable section of the book for describing unstable features. And I'm not sure it's worth time finding alternate examples of things when the reference needs a general cleaning up anyway, which is where I'd go over things like 'does this deserve an example'

**Comment by alexcrichton** [comment]
Ok, but some of these I believe can be updated to not use feature gates, so perhaps they could be tweaked to stay wherever possible?

**Comment by steveklabnik** [comment]
@alexcrichton seems legit. I've fixed up the examples, and moved the slice patterns one out. Only one or two got totally axed, because they were about box patterns, primarily.

**Pull request merged**
