### PR TITLE
Add a generic `From<&Borrow>` impl for `Cow`

### PR DESCRIPTION
**Pull request by burtonageo**
This commit removes the ad-hoc impls of `From<&Borrow> for Cow`, and replaces them with a generic `From` impl across all `&Borrow<T>`. I am unsure of how the stability attributes should work, so I will need some guidance to get this in good shape to submit.

The practical effects of this commit are:
- There are now `From<&Borrow>` impls derived for `Cow<CStr>` and `Cow<OsStr>`, as well as any other ecosystem types that can be borrowed (e.g. [ascii types](https://crates.io/crates/ascii))
- `From<&Owned>` is now auto implemented. This fixes some issues with using `Into<Cow<T>>` in generic situations, as shown in [this playground](https://play.rust-lang.org/?gist=c208363beb1408c4b019f33429420665&version=stable).

Some other issues:
- I attempted to add an `impl<T: ToOwned> From<T::Owned> for Cow<T>`, however it conflicted with the reflexive `From` impl in core. Thus, those impls will still have to be implemented in an ad-hoc way until maybe specialization could solve it.

### CODE REVIEW

**Comment by egilburg** [comment]
Does this replace a stable function with an unstable one?

**Comment by egilburg** [comment]
@burtonageo Fair enough, it's just that currently the code is marked "unstable", so is the marker even needed if it's not actually taking effect, and especially since it logically needs to be stable to preserve existing behavior?

**Comment by burtonageo** [comment]
@egilburg It was just a way to mark it as WIP, but I guess there's not much point marking it as unstable, so I'll update it now

**Comment by shepmaster** [comment]
Ping from triage, @alexcrichton — will you be able to give this a review sometime soon?

**Comment by Mark-Simulacrum** [comment]
I believe @alexcrichton is mostly absent for a few weeks, so r? @BurntSushi

**Comment by alexcrichton** [comment]
Thanks for the PR @burtonageo! I think technically this is a breaking change, right? As such, I think we may want to get a crater run to assess breakage, but would want to confirm first you agree that it's a breaking change.

**Comment by burtonageo** [comment]
@alexcrichton Thanks for the review! According to the [rfc on breaking changes](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#signatures-in-functions) (under the section "generalising to generics"), I believe this counts as a minor semver change. However, that section does state that this change could create type inference failures, and thus I agree that this is a breaking change.

**Comment by withoutboats** [comment]
I believe this is a breaking change (not one we usually allow). It would be incoherent with implementations like this, which are allowed:

```rust
#[derive(Clone)]
struct X;

impl<'a> From<&'a X> for Cow<'a, X> {
    fn from(x: &'a X) -> Self {
         Cow::Borrowed(x)
    }
}
```

**Comment by Mark-Simulacrum** [comment]
Crater started

**Comment by Mark-Simulacrum** [comment]
Crater results: http://cargobomb-reports.s3.amazonaws.com/pr-48191/index.html. 'Blacklisted' crates (spurious failures etc) can be found
[here](https://github.com/rust-lang-nursery/crater/blob/master/blacklist.md).
If you see any spurious failures not on the list, please make a PR against that file.

**Comment by alexcrichton** [comment]
Thanks for the crater run! I glanced at all the git-related logs at the bottom and they're all breaking due to this change, so unfortunately looks like we won't be able to do this.

**Pull request closed without merging**
