### PR TITLE
rustbook chapters/sections should be an ordered list.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
These are in the left sidebar of the rustbook generated HTML.

**Comment by steveklabnik** [comment]
Can you show what this looks like rendered? They're already numbered, I want to make sure that this isn't gonna end up screwing that up.

**Comment by frewsxcv** [comment]
screen shot 2016-08-30 at 11 10 05 am

**Comment by steveklabnik** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
