### PR TITLE
Stabilize `extern_crate_item_prelude`

### PR DESCRIPTION
**Pull request by petrochenkov**
Closes https://github.com/rust-lang/rust/issues/55599

### CODE REVIEW

**Comment by petrochenkov** [comment]
## Stabilization report

Feature name: `#![feature(extern_crate_item_prelude)]`
Version target: 1.31 (2018-12-07) aka 2018 edition release

Implemented in https://github.com/rust-lang/rust/pull/54658 and landed 23 days ago.
Tracking issue is https://github.com/rust-lang/rust/issues/55599.
Documentation issue is https://github.com/rust-lang-nursery/reference/issues/466.
Tests for the feature can be found in `src/test/ui/imports/extern-prelude-extern-crate-*.rs` and `src/test/ui-fulldeps/proc-macro/extern-prelude-extern-crate-*.rs`.

### Why this is desirable to stabilize for the edition release

The feature provides the same usage model for "normal" crates (passed with `--extern` or `core`/`std`) and crates that cannot be passed with `--extern` on stable like `proc_macro`, `alloc` or `rustc_*` crates.

As a result this code "just works" on 2018 edition:
```rust
extern crate proc_macro;

use proc_macro::TokenStream;
```

If this is not stabilized for the edition release, nothing too terrible happens, but users of the aforementioned crates will have to use them like something from the local crate for some time (e.g. until the next release).

```rust
extern crate proc_macro;

use crate::proc_macro::TokenStream;
```

### What is being stabilized

If item `extern crate orig_name as rename;` is placed into the crate root, then it adds name `rename` into the "extern prelude".
If item `extern crate orig_name;` is placed into the crate root, then it adds name `orig_name` into the "extern prelude".

If the name `foo` is in extern prelude, then 1) it's in scope in the whole crate including inner modules and 2) absolute paths on 2018 edition can refer to it.
```rust
extern crate foo;

mod m  {
    use foo; // OK
    use ::foo; // OK

    let x = foo::bar; // OK
    let x = ::foo::bar; // OK
}
```

### Some details and corner cases

If `extern crate` is placed in non-root module, then it doesn't add anything into extern prelude.
This means there's opt-out from this feature:
```rust
mod inner {
    pub(crate) extern crate foo;
}
use inner::foo;
```

If `name` is first added to extern prelude with `--extern name` and then with `extern crate other_totally_unrelated_crate as name`, then the second one wins and `name` will refer to the other totally unrelated crate.

Macro expanded `extern crate` items still add names to extern prelude, however such items cannot override names passes with `--extern` (there's a dedicated error). This is a special case of a [more general rule](https://github.com/rust-lang/rust/pull/53778#issuecomment-419224049).

Interactions of the feature with unstable macros 2.0 are buggy (https://github.com/rust-lang/rust/issues/55668), but the bug is already fixed in https://github.com/rust-lang/rust/pull/55884.

**Review by Centril — APPROVED** [review]

**Comment by Centril** [comment]
I propose that we stabilize `#![feature(extern_crate_item_prelude)]` in 1.31 (-> `beta` branch) per the report given in https://github.com/rust-lang/rust/pull/56032#issuecomment-439652611.

@rfcbot merge

**Comment by alexcrichton** [comment]
@bors: p=1

beta nominated

**Comment by nikomatsakis** [comment]
(I checked @pnkfelix as they are on PTO)

**Pull request merged**
