### PR TITLE
ci: fix wrong shared.sh import for publish_toolstate

### PR DESCRIPTION
**Pull request by emilyalbini**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I think toolstate is working right now - is there some context I'm missing? Maybe we can drop the import entirely?

**Comment by pietroalbini** [comment]
Oh, yeah, I should've added context, sorry.

https://github.com/rust-lang/rust/pull/67733 broke it: when I originally made the PR, `publish_toolstate.sh` was in `src/ci/scripts`, but you moved it to `src/ci`, so the import path is wrong. See https://github.com/rust-lang/rust/pull/67733#issuecomment-571955268 for the failure.

**Comment by Mark-Simulacrum** [comment]
Ah, cool, okay! @bors r+ then. (I guess maybe we should bump priority, or just roll this up?)

**Comment by pietroalbini** [comment]
@bors p=100

Feel free to roll this up.

**Pull request merged**
