### PR TITLE
Stabilize rustdoc `--test-run-directory`

### LINKED ISSUE #84674: Tracking Issue for rustdoc `--test-run-directory`
### Summary

This is a tracking issue for the `--test-run-directory` flag in rustdoc.  This flag changes the directory where doctests are run. This was added to support changing the directory used while running `rustdoc --test` in a Cargo workspace. See https://github.com/rust-lang/cargo/issues/9427 for more information.

### Unresolved Questions

None at this time.

### Implementation history

* #81264 — Initial PR.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

cc @Swatinem

### PR DESCRIPTION
**Pull request by Swatinem**
This should resolve https://github.com/rust-lang/rust/issues/84674

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@jyn514 Since you were the one who approved this option, is there anything we need to check beforehand or is it ready to go through FCP?

Also, cc @rust-lang/rustdoc since it's a stabilization PR.

**Comment by jyn514** [comment]
I don't want to be involved with this decision.

> Also, cc rust-lang/rustdoc since it's a stabilization PR.

This is not how stabilization PRs work. There should be an FCP with checkboxes

**Comment by GuillaumeGomez** [comment]
I wanted to get some insight from you before starting FCP (as I mentioned in my comment) but it's fine.

@Swatinem: Can you write a stabilization report before we move any further please?

**Comment by Swatinem** [comment]
> Can you write a stabilization report before we move any further please?

I wrote that up here: https://github.com/rust-lang/rust/issues/84674#issuecomment-1295165955

While doing so I realized that `--test-run-directory` is just an implementation detail of the cargo `doctest-in-workspace` flag that itself is fixing an inconsistency between doctests and other types of tests, and I would want to eventually make that the default in the future.

I’m not sure if its possible to fix that behavior in stable cargo without having to first stabilize the rustdoc flag?

**Comment by GuillaumeGomez** [comment]
The cargo team seems to be on board for this change based on [this comment](https://github.com/rust-lang/cargo/issues/9427#issuecomment-1296326215). I copy the stabilization report here from [this comment](https://github.com/rust-lang/rust/issues/84674#issuecomment-1295165955):

# Request for Stabilization

I opened https://github.com/rust-lang/rust/pull/103682 with the aim to stabilize this rustdoc flag, primarily to facilitate the cargo `doctest-in-workspace` flag, and to eventually making it the default.

## Summary

The `--test-run-directory` flag in combination with `--test` allows specifying an explicit directory in which rustdoc will *run* the compiled doctests. The default, without this explicit flag, is to run the resulting doctest binaries in the same current working directory as rustdoc itself.

This flag is primarily the building block for the `doctest-in-workspace` cargo flag (See https://github.com/rust-lang/cargo/issues/9427).

With that flag, doctests are handled consistently to unit- and integration tests: They will be *compiled* relative to the cargo workspace root, but they are *run* in the crate directory.

## Documentation

The flag is currently *not* documented as part of the [unstable rustdoc features](https://doc.rust-lang.org/rustdoc/unstable-features.html).

## Tests

- [src/test/rustdoc-ui/run-directory.rs](https://github.com/rust-lang/rust/blob/a9ef10019fd3be6e03afb4b213368f4af1917f9b/src/test/rustdoc-ui/run-directory.rs) -- highlights usage with cwd-sensitive `std::fs` functions inside doctests.
- [cargo tests/testsuite/doc.rs](https://github.com/Swatinem/cargo/blob/6c1bc24b8b49d4bc965f67d7037906dc199c72b7/tests/testsuite/doc.rs#L1845-L1919) -- shows indirect usage via the cargo `doctest-in-workspace` flag.

## Unresolved questions

- Similar flags that allow hooking into or observing the side effects of rustdoc test compilation, such as [`--run-tool`](https://github.com/rust-lang/rust/issues/64245) or [`--persist-doctests`](https://github.com/rust-lang/rust/issues/56925) are not stable yet, and there does not seem to be a push to stabilization either.
- The usefulness of this flag when invoking `rustdoc` manually might be limited. But it is a requirement for the cargo `doctest-in-workspace` flag.
- ☝🏻 Is there maybe a better alternative to solve the compile/run directory inconsistency that exists in cargo workspaces today?

@rfcbot merge

**Comment by ehuss** [comment]
@CraftSpider @Nemo157 @camelid @jsha Checking in to see if you have any questions on this stabilization.

**Comment by camelid** [comment]
I have no concerns about this addition, but unfortunately I haven't had time to review it properly yet.

**Comment by CraftSpider** [comment]
I've become an alumni since the FCP started, so someone 
else can check my box. For what it's worth, the stabilization reason seems compelling enough to me.

**Comment by Swatinem** [comment]
I pushed a rebase, wasn’t aware this was blocked on a merge conflict. Lets get this going then, its been almost half a year :-)

**Comment by GuillaumeGomez** [comment]
Can you add documentation for this option into the rustdoc book please? (in `src/doc/rustdoc`)

**Comment by Swatinem** [comment]
I added some more documentation for the new flag, as well as another `file!()` assertion to the test. I hope that is stable across all the test platforms. I will check Windows later today.

**Comment by Swatinem** [comment]
Well, CI is already unhappy about asserting `file!()` output, so I removed that.

**Comment by Swatinem** [comment]
@GuillaumeGomez Docs for this option were added. Is there another blocker for moving this along?

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
No all good. Just forgot to come back to it, sorry about that. Thanks for this PR!

@bors r+ rollup

**Pull request merged**
