### PR TITLE
[perf experiment] Enable DeduplicateBlocks

### PR DESCRIPTION
**Pull request by saethlin**
It looks to me like all this really does is delete duplicated empty `unreachable` blocks, and the occasional `StorageDead + drop` block. Perhaps something unexpected turns up in perf.

r? @ghost

### CODE REVIEW

**Comment by saethlin** [comment]
Cachegrind diffs indicate that a change in the codegen of this function is entirely responsible for the regressions:
```
--------------------------------------------------------------------------------
Ir          
--------------------------------------------------------------------------------
173,178,186  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir           file:function
--------------------------------------------------------------------------------
176,073,369  ???:<rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>
```

https://github.com/rust-lang/rust/blob/a2112fcb0ad7327b9f1ee618c18567d74fc084b1/compiler/rustc_data_structures/src/obligation_forest/mod.rs#L413

Which is interesting. I have never seen a case like this where the whole regression is accounted for by a codegen change in one function.

**Comment by saethlin** [comment]
Compiling rustc, here is the size of the blocks that get deduplicated:
```
(  1)     9855 (91.4%, 91.4%): 0
(  2)      597 ( 5.5%, 96.9%): 2
(  3)      260 ( 2.4%, 99.3%): 1
(  4)       55 ( 0.5%, 99.8%): 3
(  5)        7 ( 0.1%, 99.9%): 4
(  6)        1 ( 0.0%, 99.9%): 5
```
And with DestinationPropagation enabled, this distribution slants much more towards 0.

The limit of this pass was previously set at 10. Things must have been very different back in the day to justify setting it that high. I'm setting the limit down to 3.

@bors try @rust-timer queue

**Comment by saethlin** [comment]
Adding a tighter to this seems to have removed our improvements but hardly altered the regressions. I would not have expected that. So if I remove the limit entirely, I should see huge regression due to making `optimized_mir` slow, but what else will show up?

@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
Marking as waiting on author because it's still a draft.

**Comment by saethlin** [comment]
https://github.com/rust-lang/rust/pull/106428 enabled deduplicating unreachable blocks. The distribution of block sizes now looks like this (it used to be dominated by 0):
```
(  1)     5006 (63.2%, 63.2%): 1
(  2)     1469 (18.5%, 81.7%): 0
(  3)     1301 (16.4%, 98.1%): 2
(  4)       62 ( 0.8%, 98.9%): 3
(  5)       54 ( 0.7%, 99.6%): 4
(  6)        9 ( 0.1%, 99.7%): 6
(  7)        6 ( 0.1%, 99.8%): 5
(  8)        3 ( 0.0%, 99.8%): 7
(  9)        2 ( 0.0%, 99.9%): 8
( 10)        1 ( 0.0%, 99.9%): 9
```
It looks like most of the 0-statement blocks are `drop` terminators. the 1-statement blocks are split between `_0 = ` + `goto` and `StorageDead` + `goto`.

I suspect that this distribution will be significantly reshaped by jump threading or whatever other passes land, and since this pass isn't deleting enough MIR to produce a benefit, I'm closing this.

**Pull request closed without merging**
