### PR TITLE
Build compiletest with in-tree libtest

### LINKED ISSUE #59264: compiletest should be built with the stage2 compiler not the stage0 compiler
See #57709. Unfortunately the "fix" to that bug breaks the build when building using 1.31.0 and you have to unapply the patch to make it work against 1.31.0.

e.g. from https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=amd64&ver=1.32.0%2Bdfsg1-1&stamp=1548672224&raw=0 :

~~~~
rustc command: "LD_LIBRARY_PATH"="/usr/lib:/<<BUILDDIR>>/rustc-1.32.0+dfsg1/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/deps:/usr/lib" "/usr/bin/rustc" "--crate-name" "compiletest" "
~~~~

The problem here is that if stage0 is 1.31.0 then the patch MUST be unapplied, if stage0 is 1.32.0 then the patch MUST be applied. Obviously we can't do both at once.

However in both Debian and Fedora we occasionally use either the current or the previous version of rustc to build a given version of rustc, and both of these versions should work.

cc @cuviper

### PR DESCRIPTION
**Pull request by cuviper**
This updates compiletest to build in `Mode::ToolStd`, using the locally-built crates for `std` and especially `test`. This way we're immune to unstable differences in the bootstrap compiler crates, whether that's a prior-release stage0 or a current release local rebuild. Fixes #59264.

As a minor cleanup, this also removes the unused `llvm_tools` flag.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
One thing that I had wanted was to ban non-test use in compile test... But that can be left for the future, I guess.

@bors r+

**Comment by cuviper** [comment]
> One thing that I had wanted was to ban non-test use in compile test...

Is there a technical way to do that? Or did you just want a comment in the source?

**Comment by Mark-Simulacrum** [comment]
I was thinking a comment might suffice :)

I'm also not sure how much benefit compiletest gets from depending on libtest -- it might be worth trying to just duplicate and minimize the code instead.

**Comment by cuviper** [comment]
OK, there's a comment for you...

**Comment by Mark-Simulacrum** [comment]
Great! Somehow I thought we were using more features (but maybe they've been stabilized since).

@bors r+

**Pull request merged**
