### PR TITLE
Ship LLVM-C.dll on Windows

### PR DESCRIPTION
**Pull request by Zoxc**
cc @denzp

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm ok so on the surface I have extremely little information as to why this is being proposed. The PR title, PR message, and commit message don't give any information and there's simply a comment in the code saying we're shipping something on Windows for rust-ptx-linker. The context I'm missing is why we're doing this change at all, why it's only on Windows, and why it's the best solution to a problem I'd probably have to dig around to find.

Can this be expanded more? This seems like an odd thing we'd do to ship unrelated artifacts that are likely somewhat unstable. We do that currently in `*-preview` components like `llvm-tools-preview`, but I'm not sure we'd ship that with the standard components.

**Comment by Zoxc** [comment]
Currently `rust-ptx-linker` uses LLVM's C API through `rustc_codegen_llvm`, but https://github.com/rust-lang/rust/pull/59752 changes `rustc_codegen_llvm` to no longer export this API.

We do currently ship the full LLVM library on macOS and Linux as part of the `rustc` component, which `rust-ptx-linker` can link to instead, but we don't ship anything on Windows.

I also see that we rename the LLVM lib to `libLLVM-8-rust-1.35.0-nightly.so`, which this PR doesn't do for the DLL.

**Comment by alexcrichton** [comment]
That all makes sense but it's still missing *why*. Why are we shipping this for `rust-ptx-linker`? 

We aren't shipping the full LLVM library for `rust-ptx-linker` to use on other platforms, we're using it since it's a technical requirement of our distribution artifacts.

**Comment by nagisa** [comment]
This seems like a repeat of https://github.com/rust-lang/rust/pull/35113 to me. The comments there seem as applicable today as they were in 2016.

**Comment by jonas-schievink** [comment]
Visiting for triage. Is this something desirable or should this PR be closed?

**Pull request closed without merging**
