### PR TITLE
Improve display for "copy-path" button, making it more discreet

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
As suggested by @Nemo157 [here](https://github.com/rust-lang/rust/pull/85118#issuecomment-838887670):

Screenshot from 2021-05-18 11-18-49
Screenshot from 2021-05-18 11-15-06
Screenshot from 2021-05-18 11-18-54
Screenshot from 2021-05-18 11-15-00
Screenshot from 2021-05-18 11-18-58
Screenshot from 2021-05-18 11-19-00

r? @jsha

### CODE REVIEW

**Comment by Nemo157** [comment]
It could be nice to have a highlight on hover too, since there's no longer the border changing color.

**Comment by GuillaumeGomez** [comment]
I was thinking about it and thought that the cursor change would be enough. What do you suggest? Making the color a bit lighter?

**Comment by Nemo157** [comment]
Lighter on the dark themes, darker on the light theme (which would require making the base color on ayu a bit darker so it has somewhere to lighten towards).

**Comment by GuillaumeGomez** [comment]
I updated the screenshots. The difference is very easy to spot when using it but with just the screenshots, not that much... (mostly on light and dark themes)

**Comment by jsha** [comment]
This looks good, but why the complex CSS filter? Why not just set a different color?

**Comment by GuillaumeGomez** [comment]
Because of the svg, we can't change its color easily, we have to use tricks. But since it's only grey, we can simply use `filter`. Need to update it.

**Comment by GuillaumeGomez** [comment]
Simplified the rules for the same result (and also re-updated the screenshots).

**Pull request merged**
