### PR TITLE
coverage: Simplify parts of coverage graph creation

### PR DESCRIPTION
**Pull request by Zalathar**
This is a combination of three semi-related simplifications to how coverage graphs are created, grouped into one PR to avoid conflicts.

There are no observable changes to the output of any of the coverage tests.

### CODE REVIEW

**Comment by Zalathar** [comment]
Notes on the `CoverageSuccessors` change, from #132379:

> There are two minor differences implied by this change:
> - A `SwitchInt` terminator with exactly one target is now eligible to be chained.
>   - The previous behaviour didn't have any strong rationale, and this gets rid of a special case.
> - A terminator with no coverage-relevant successors is now always marked as “not out-summable”.
>   - This is more correct, because (for example) a `Return` terminator has no successors (so their sum of execution counts is 0), but the return itself can have a non-zero execution count.
>   - The existing code that checks this flag doesn't care either way, but this is likely to matter in the future.

**Comment by Zalathar** [comment]
While we're here, might as well shorten `std::mem::take` to `mem::take` [(diff)](https://github.com/rust-lang/rust/compare/d568510a77f6977aeda66b65ae43d4e58e075df2..4a70f4bee0baa203636a259fb04929718ee7d0e0).

**Comment by jieyouxu** [comment]
r? jieyouxu

**Review by jieyouxu — APPROVED** [review]
Thanks looks like a nice cleanup, thanks!

**Pull request merged**
