### PR TITLE
[crater] Remove LArrow

### PR DESCRIPTION
**Pull request by compiler-errors**
🔪 

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by Skgland** [comment]
Rust-for-Linux appears to uses `<-` in a macro e.g. <https://github.com/Rust-for-Linux/linux/blob/rust-next/rust/kernel/sync/condvar.rs#L99>

**Comment by compiler-errors** [comment]
@Skgland: This shouldn't affect that macro unless it's actually choosing between `<-` and `< -` in the macro definition, which it seems it doesn't.

The only side-effect is that it causes `field < - expr` to work, since `<-` is now two tokens.

**Comment by compiler-errors** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-118920/retry-regressed-list.txt

**Comment by compiler-errors** [comment]
There are real crate breakages here. I don't believe we will be able to remove LArrow from the language without breaking existing macros.

**Comment by petrochenkov** [comment]
I don't think we need to remove it in the first place.
It's a good looking operator with a high chance of being used in the future.

**Pull request closed without merging**
