### PR TITLE
Copy an example to PartialOrd as well

### PR DESCRIPTION
**Pull request by azdavis**
In https://github.com/rust-lang/rust/pull/88202 I added an example for deriving PartialOrd on enums, but only later did I realize that I actually put the example on Ord.

This copies the example to PartialOrd as well, which is where I intended for it to be.

We could also delete the example on Ord, but I see there's already some highly similar examples shared between Ord and PartialOrd, so I figured we could leave it.

I also changed some type annotations in an example from `x : T` to the more common style (in Rust) of `x: T`.

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
This says two contradictory things. The first sentence says it's based on discriminant order, and the second sentence says it's based on source order.

When those two are not the same thing, I feel like it's the job of exactly this documentation you're touching to make it clear what the behavior of the derived impl is.

```rust
#[derive(PartialEq, Eq, PartialOrd, Ord)]
enum N {
    Two = 2,
    One = 1,
}
```

**Comment by azdavis** [comment]
That's a great point. I think we could improve the part about "top-to-bottom discriminant order".

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
