### PR TITLE
explain the options bootstrap passes to curl

### PR DESCRIPTION
**Pull request by lolbinarycat**
also fixes a discrepancy where the rust side doesn't use -L

docs are only on the rust side, since duplicated prose has a tendancy to get out-of-sync, and also because there are talks of removing the python script all together eventually.

### CODE REVIEW

**Review by the8472 — COMMENTED** [review]
To increase descriptiveness you could use the long-form options instead. `--show-error`  instead of `-S` etc.

**Review by albertlarsan68 — CHANGES_REQUESTED** [review]
Could you switch the flags from short to long please?
If you don't want or can't do it now, please open an issue to have it changed in the future.

**Review by albertlarsan68 — APPROVED** [review]
LGTM

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+

**Pull request merged**
