### PR TITLE
CTFE: use binary_op to compare integer with match disriminant

### PR DESCRIPTION
**Pull request by RalfJung**
This is needed to unblock https://github.com/solson/miri/pull/401: There is code in the Windows initialization functions that uses `match` to test whether a pointer is NULL.

I will add a testcase in miri; I was not sure where to add a testcase in Rust itself.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
Test case inside rustc:

```rust
    let _: [u8; 0] = [4; {
        match &1 as *const i32 as usize {
            0 => 42, // should not have "a raw memory access tried to access part of a pointer value as raw bytes" here, any other error is expected and fine
            n => n,
        } 
    }];
```

**Comment by RalfJung** [comment]
That says "error[E0018]: raw pointers cannot be cast to integers in constants"

**Comment by oli-obk** [comment]
but on master it additionally says "a raw memory access tried to access part of a pointer value as raw bytes", on the `0 =>`, which in your branch it won't.

**Comment by RalfJung** [comment]
Done.

**Comment by oli-obk** [comment]
r=me with ui test updated to reflect the line changes

@bors delegate

**Comment by RalfJung** [comment]
Dang, sorry -- forgot to `--bless` again after adding the license...

**Pull request merged**
