### PR TITLE
Stabilize short error format

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @oli-obk 

Added in https://github.com/rust-lang/rust/pull/44636

### CODE REVIEW

**Comment by oli-obk** [comment]
Does this have a tracking issue?

**Comment by GuillaumeGomez** [comment]
No, it's just a format I added a long time ago. I think it's time to stabilize it now.

**Comment by oli-obk** [comment]
@rfcbot merge

This is a simple addition that is very useful for simple IDEs without rls support or just getting a good overview of all errors without the "noise" of details. I don't know of any open questions about it, except that some errors display very badly (e.g. `mismatched types` doesn't show the types). This is true for rls rendering, too, and we don't give guarantees on diagnostic output stability, so we can fix it in the future.

An output example can be found in https://github.com/GuillaumeGomez/rust/blob/3ac4f6d7a41caebdf612c079d0bf13b0f54bee74/src/test/ui/short-error-format.stderr

**Comment by oli-obk** [comment]
@rfcbot fcp merge

This is a simple addition that is very useful for simple IDEs without rls support or just getting a good overview of all errors without the "noise" of details. I don't know of any open questions about it, except that some errors display very badly (e.g. `mismatched types` doesn't show the types). This is true for rls rendering, too, and we don't give guarantees on diagnostic output stability, so we can fix it in the future.

An output example can be found in https://github.com/GuillaumeGomez/rust/blob/3ac4f6d7a41caebdf612c079d0bf13b0f54bee74/src/test/ui/short-error-format.stderr

**Comment by nrc** [comment]
@rfcbot concern weight

Is this pulling its weight? Are people and/or tools using it? Do we have reports that it is satisfying their needs properly and is not just a stop gap for them?

**Comment by nrc** [comment]
@rfcbot concern details

Many errors don't make sense without the details (the secondary diagnostics), or at least are not very clear. Is this a problem here? Would the short form be better if it included these, but excluded the code snippets and some other stuff?

(Having registered both these concerns, my inclination is still to stabilise, however, I do want to check we're doing the right thing).

Also cc @rust-lang/dev-tools

**Comment by GuillaumeGomez** [comment]
> Is this pulling its weight? Are people and/or tools using it? Do we have reports that it is satisfying their needs properly and is not just a stop gap for them?

I know a few who are using it yes (the ones who asked for it). They use it to avoid getting huge rustc output mainly, not for tooling.

**Comment by petrochenkov** [comment]
I tried it today and yesterday and I like it, in general.
Some errors are not adapted for this diagnostic style though and give completely useless messages like "type mismatch" without any details, but they may be improved.

**Comment by nikomatsakis** [comment]
I have no idea what is being "stabilized" here. Surely not the text of the messages. Something about the format? If so, what? It'd be nice to see some documentation to that effect.

**Comment by nikomatsakis** [comment]
(Personally, I feel this could have merited an RFC, also.)

**Comment by estebank** [comment]
> Do we have reports that it is satisfying their needs properly and is not just a stop gap for them?

There's a vocal small group of people that _really_ like this feature. The increase in complexity is fairly contained.

> Some errors are not adapted for this diagnostic style though and give completely useless messages like "type mismatch" without any details, but they may be improved.

I'm yet to write down a proposal pointing out (been offline for two weeks), but I want to formalize the way all errors are written to make short errors always make sense. Labels and notes should provide extra context and guidance, not be mandatory for understanding, although for the type mismatch errors we might want to wait until we have a way to use "shorter" (local namespace) type names to avoid overly long messages.

As to @nikomatsakis' comments, I feel that the improvement of the text to fit this format can be tackled progressively over time and the feature is small and obscure enough (I foresee few people to use it on a regular basis, and the ones that do are more likely to accept the growing pains until we improve the messages) to not be a problem to stabilize it as presented.

**Comment by Manishearth** [comment]
Perhaps we can add a ~/.cargo/config key for this? You can already do this as a rustflags key but a dedicated key should be nice.

IMO folks should not be interacting with Rust flags directly as much as possible.

**Comment by pietroalbini** [comment]
Ping from triage @rust-lang/compiler! How's the discussion going for this?

**Comment by nikomatsakis** [comment]
Also, how it is tested =)

**Comment by nikomatsakis** [comment]
Some more discussion on IRC [here](https://botbot.me/mozilla/rustc/2018-04-26/?msg=99430628&page=5). Specifically, I would like to know:

- We are stabilizing some kind of flag that selects this output. What is that flag? Is there an environment variable? How does it work?
- Are we stabilizing *anything* about the output? The fact that it is one line per error? A regex that will match to extract filename/line number? Nothing at all?

Presumably we are *not* stabilizing the specific text of error messages, which I guess we would never do.

Is there documentation, or a plan to document? Are there tests?

**Comment by QuietMisdreavus** [comment]
Here's what i know about this feature. @GuillaumeGomez can fill in more specifics if i'm missing something.

* This adds a new option to the `--error-format` flag: `short`.
* Passing `--error-format short` to rustc is like `--error-format human`, but it will omit everything but the "first line" of an error. Help messages, span displays, supplementary info, things like that. When rustc emits an error under this format, it only prints the file, line, column, and the initial error message.
* *Right now*, before this PR, if you wanted to pass `--error-format short`, you also needed to pass `-Z unstable-options`. The flag was made unstable since it was a new implementation, in case we wanted to change how it was named or something significant about its implementation or something like that. The unstable requirement was added in https://github.com/rust-lang/rust/pull/44636. This PR removes that.
* When the flag was initially implemented, i opened a PR to Cargo to add this option to their `--message-format` flag to match, but it was closed since the option was so new and needed to be marked unstable. Presumably, if this PR is merged and the unstable requirement is lifted, that PR can be reopened.

If there are other implications to adding an error format, i haven't considered them. I personally think it's harmless to add, but i also didn't write it. :grin:

**Comment by nikomatsakis** [comment]
So I would specifically like to know if we are committing to:

```
file.rs:LL:CC - error[E0308]: XXX
```

I think we should consider adopting one of the [standard gnu formats](https://www.gnu.org/prep/standards/html_node/Errors.html), which I think we *almost* do, except that we should say `file:LL:CC:`.

**Comment by nikomatsakis** [comment]
@rfcbot resolved what-is-being-stabilized

thanks @QuietMisdreavus !

**Comment by nikomatsakis** [comment]
@rfcbot concern gnu-compatible

I think the output should be compatible with the [standard gnu formats](https://www.gnu.org/prep/standards/html_node/Errors.html), which I think we *almost* do, except that we should say `file:LL:CC:` (i.e., colon after the column number). Not sure what happens for more complex line/column information.

**Comment by nikomatsakis** [comment]
@rfcbot resolve what-is-being-stabilized

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus: That's exactly this, thanks for summing it up!

**Comment by estebank** [comment]
One thing that we haven't addressed with this, as you correctly point out, is how to deal with diagnostics that have more than one primary span. The correct thing to do would be to emit one line per primary span, but that is not the current implementation.

**Comment by GuillaumeGomez** [comment]
It can be added. I just prefer to wait for a consensus before doing anything.

**Comment by nikomatsakis** [comment]
To clarify my position: I am in favor of stabilizing something here and supporting this output mode, I just want us to have good docs for what is stable before we do so.

I specifically think we should stabilize the "basics" of the format, so that people can use grep. I further think it [should be a GNU-compatible format](https://github.com/rust-lang/rust/pull/49546#issuecomment-384717500) but that is perhaps less critical.

**Comment by nikomatsakis** [comment]
How do people feel about the "GNU compatible format" thing? If there is general agreement, maybe @GuillaumeGomez you can implement it? Seems easy enough...

**Comment by oli-obk** [comment]
It costs us little to be compatible. so let's do it.

**Comment by GuillaumeGomez** [comment]
@nikomatsakis: Is it as you expected?

**Comment by oli-obk** [comment]
@rfcbot resolve gnu-compatible  https://github.com/rust-lang/rust/pull/49546/commits/0be4cb980fed0a773649f480e4cf9bb861c5462b

**Comment by oli-obk** [comment]
@rfcbot resolved gnu-compatible

**Comment by nikomatsakis** [comment]
@rfcbot resolved gnu-compatible

**Comment by nikomatsakis** [comment]
Still got a few concerns to resolve from @nrc -- details and weight. Not sure what steps are needed for those. =)

**Comment by nrc** [comment]
@rfc-bot resolved details

**Comment by nrc** [comment]
@rfc-bot resolved weight

**Comment by GuillaumeGomez** [comment]
Is something supposed to happen now?

**Comment by cramertj** [comment]
@nrc you messaged @rfc-bot, not @rfcbot.

**Comment by nrc** [comment]
@rfcbot resolved details

**Comment by nrc** [comment]
@rfcbot resolved weight

**Comment by GuillaumeGomez** [comment]
Ok, and now? :)

**Comment by cramertj** [comment]
@michaelwoerister, @nagisa, and @pnkfelix still have unchecked boxes.

**Comment by michaelwoerister** [comment]
Box checked.

**Comment by GuillaumeGomez** [comment]
@cramertj: Is it required? It's said that as long as majority agrees and no ones objects, it's good enough.

**Comment by nikomatsakis** [comment]
@GuillaumeGomez technically we have to wait for the FCP to expire (10 days). But I don't anticipate a lot of controversy here =)

**Comment by GuillaumeGomez** [comment]
Didn't have merge conflict apparently but rebased just in case...

**Comment by nagisa** [comment]
This is a 2nd time i see bors reporting a timeout error incorrectly.

**Comment by Manishearth** [comment]
Iirc this happens when a previous stuck build eventually times out (on the
bors side -- usually it's died ages ago on Travis but bors doesn't notice
and keeps it around)

**Pull request merged**
