### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #129194 (Fix bootstrap test `detect_src_and_out` on Windows)
 - #129217 (safe transmute: check lifetimes)
 - #129223 ( Fix wrong argument for `get_fn_decl`)
 - #129235 (Check that `#[may_dangle]` is properly applied)
 - #129245 (Fix a typo in `rustc_hir` doc comment)
 - #129271 (Prevent double panic in query system, improve diagnostics)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=129194,129217,129223,129235,129245,129271)

### CODE REVIEW

**Comment by pnkfelix** [comment]
sole primary regression of 0.2% icount is to helloworld doc-full. not worth investigating

@rustbot label: +perf-regression-triaged

**Comment by lqd** [comment]
Let's see if this caused the huge artifact size regression maybe

@rust-timer build 43e22166b4f2a58ac6e7713f900e83fd19f763bd

**Comment by lqd** [comment]
that's crazy 😆

**Pull request merged**
