### PR TITLE
Bump to 1.67.0

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It looks like we're failing here because the version bump caused us to need a rebuild of LLVM for all the builders that are caching it (as of https://github.com/rust-lang/rust/pull/99967). Normally that's not a problem, but `python3 "$X_PY" test --stage 2 src/tools/miri --target i686-pc-windows-msvc` currently at least is breaking on that. It seems possible we don't actually need an LLVM build here and the check/download of it is just too eager, but that will need to be fixed in a follow-up PR.

**Comment by nnethercote** [comment]
These "regressions" are just noise, the relevant benchmarks have been noisy lately.

@rustbot label: +perf-regression-triaged

**Pull request merged**
