### PR TITLE
Revert #86853

### PR DESCRIPTION
**Pull request by usbalbin**
Should fix issue found in #89432

### CODE REVIEW

**Comment by eddyb** [comment]
For the record, while I'm not going to open my own PR, I was able to get a simpler revert by reverting the *merge commit* instead of every single commit (https://github.com/eddyb/rust/commit/5345239be2e347dae1c5bc887959b8b7813c7aa6), using:
```sh
git revert -m 1 c6007fdc7059c677a6c089e8d2915b264c0d1326
```

**Comment by usbalbin** [comment]
Oh, thanks :)

**Comment by usbalbin** [comment]
Should I add some sort of regression test like the one mentioned [here](https://github.com/rust-lang/rust/issues/89432#issuecomment-932539620)? If so where should I put it?

**Comment by oli-obk** [comment]
Yea, that seems useful, but it could also wait for the real fix PR. I'm not sure where we have the tests for const trait bounds, but probably in src/test/consts

**Comment by oli-obk** [comment]
r? @oli-obk 

@bors delegate+

Feel free to r=oli-obk in case you add a test

**Comment by usbalbin** [comment]
> Yea, that seems useful, but it could also wait for the real fix PR. [...]

If the highest prio is getting the revert landed, then I'll wait for another PR/the fix PR. :)

**Pull request merged**
