### PR TITLE
Add read_exact_at and write_all_at methods to FileExt on unix

### PR DESCRIPTION
**Pull request by drrlvn**
This PR adds `FileExt::read_exact_at()` and `FileExt::write_all_at()`, which are to `read_at()` and `write_at()` as `read_exact()` and `write_all()` are to `read()` and `write()`. This allows the user to not have to deal with `ErrorKind::Interrupted` and calling the functions in a loop.

I was unsure as to how to mark these new methods so I marked them `unstable`, please let me know if I should have done it differently.

I asked in Discord and was told that as this change is small it does not require an RFC.

### CODE REVIEW

**Comment by drrlvn** [comment]
Reassigning as advised on Discord.

r? @alexcrichton

**Comment by alexcrichton** [comment]
Looks great to me, thanks! Mind opening a tracking issue and filling in the number? I can take care of the necessary tags on the issue

**Comment by drrlvn** [comment]
@alexcrichton great, thanks!

Opened #51984 and added a commit filling it in.

**Pull request merged**
