### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #104001 (Improve generating Custom entry function)
 - #104411 (nll: correctly deal with bivariance)
 - #104528 (Properly link `{Once,Lazy}{Cell,Lock}` in docs)
 - #104553 (Improve accuracy of asinh and acosh)
 - #104554 (Use `ErrorGuaranteed::unchecked_claim_error_was_emitted` less)
 - #104566 (couple of clippy::perf fixes)
 - #104575 (deduplicate tests)
 - #104580 (diagnostics: only show one suggestion for method -> assoc fn)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=104001,104411,104528,104553,104554,104566,104575,104580)

### CODE REVIEW

**Comment by lqd** [comment]
@rust-timer build e243339f19ed4d6675ac5ee1f15043a903b2e81d

**Comment by lqd** [comment]
At least #104411 is involved, for 2 of the 3 regressions.

**Comment by rylev** [comment]
cc @lcnr who authored #104411. The regressions are few enough in number that I don't think this is necessarily worth looking into.

@rustbot label: +perf-regression-triaged

**Pull request merged**
