### PR TITLE
Ignore VS Code settings directory

### PR DESCRIPTION
**Pull request by vadimcn**
r? @steveklabnik

### CODE REVIEW

**Comment by killercup** [comment]
Just fyi, this should probably (also) be in your system-wide gitignore.

**Comment by retep998** [comment]
I am opposed to system specific gitignores. If you have something platform or IDE specific, then it really only belongs in your personal gitignore. In my opinion the only stuff that should be in a project's gitignore are things produced normally as a result of building and running that project.

**Comment by vadimcn** [comment]
That's fine by me, but in that case rust's .gitignore could use some serious cleaning...

**Comment by steveklabnik** [comment]
I personally prefer to put them all in the project, but let's make this a @rust-lang/compiler decision, not mine.

What do you all want?

**Comment by alexcrichton** [comment]
Oh I've always felt the ship has long since sailed on this, there's no way our .gitignore is "clean", so no need to have a big decision on new items, seems good to just let anything reasonable sail thorugh at this point

**Comment by nikomatsakis** [comment]
seems fine.

**Pull request merged**
