### PR TITLE
Add PeekMut::pop

### PR DESCRIPTION
**Pull request by sfackler**
A fairly common workflow is to put a bunch of stuff into a binary heap
and then mutate the top value until its empty. This both makes that a
bit more convenient (no need to save a boolean off and pop after to
avoid borrowck issues), and a bit more efficient since you only shift
once.

r? @alexcrichton 

cc @rust-lang/libs

### CODE REVIEW

**Comment by alexcrichton** [comment]
Sounds reasonable to me! Could you add a comment on the struct definition of `PeekMut` though indicating that it's intended to be leaked, and therefore shouldn't contain any allocations? (just to try to future-proof ourselves)

**Comment by alexcrichton** [comment]
Or better yet I wouldn't mind a boolean flag to manage this.

**Comment by sfackler** [comment]
Updated

**Comment by alexcrichton** [comment]
Alright let's merge! 

@sfackler r=me with a tracking issue updated

**Comment by arthurprs** [comment]
Any reason for making it a static function instead of a member function that takes Self? The later is shorter and doesn't require importing.

**Comment by sfackler** [comment]
`PeekMut` implements `Deref` so a non-static `pop` method would shadow the `pop` method of the wrapped type. We do the same for methods on `Rc`, `Box`, etc.

**Comment by arthurprs** [comment]
Got it, thanks.

**Pull request merged**
