### PR TITLE
Reintroduce box syntax where needed

### PR DESCRIPTION
**Pull request by steveklabnik**
Otherwise, this line is a lie.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
It seems strange to recommend a feature-gated pattern. We should perhaps at least clarify that this is feature-gated?

**Comment by steveklabnik** [comment]
Well it wasn't gated originally and it's one of the primary reasons to remove the gate. Is it worth adding that sentence when the gate is gonna end up coming off soon anyway?

**Comment by pnkfelix** [comment]
@steveklabnik It is not clear when the gate will come off.

**Comment by steveklabnik** [comment]
Gotcha. I'll add a note about the gate, I guess, then.

**Comment by steveklabnik** [comment]
Updated.

**Pull request merged**
