### PR TITLE
ship tools with sysroot

### LINKED ISSUE #81431: `cargo fmt` and other tools don't work for a linked toolchain.
This is derived from [this issue](https://github.com/rust-lang/rustup/issues/2548), in which we concluded that the bug should be filed against rustc, as it's an `x.py` problem.

In rustc:
```
$ ./x.py build --stage 1 src/tools/rustfmt/
...
$ find 'build' -name rustfmt
build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/rustfmt
build/x86_64-unknown-linux-gnu/stage1-tools-bin/rustfmt
build/x86_64-unknown-linux-gnu/stage0/share/doc/rustfmt
build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt
build/tmp-rustbuild-tests/main/tmp/tarball/rustfmt
build/tmp-rustbuild-tests/main/tmp/tarball/rustfmt/B/image/share/doc/rustfmt
```

Then in a project using this toolchain via a rustup link:
```
$ cargo fmt
error: 'cargo-fmt' is not installed for the toolchain 'yk-stage1'
note: this is a custom toolchain, which cannot use `rustup component add`
help: if you built this toolchain from source, and used `rustup toolchain link`, then you may be able to build the component with `x.py`                                                                           
```

But note that `cp build/x86_64-unknown-linux-gnu/stage1-tools-bin/rustfmt build/x86_64-unknown-linux-gnu/stage1/bin/rustfmt` does not make this work either, so there is probably more to it?

Thanks

### LINKED ISSUE #97762: `x build src/tools/miri` doesn't install miri as part of the built toolchain
Running `x build src/tools/miri` doesn't include miri as part of the built rust toolchain, meaning that `cargo +custom-toolchain miri` doesn't work

cc @jyn514

### LINKED ISSUE #110625: symlinking is not working as expected on `x build`
Because of the early return here:
https://github.com/rust-lang/rust/blob/3d7a091c647ef8644bfa8487434d27c9c02aa59a/src/bootstrap/compile.rs#L1331-L1335

symlinking phases are bypassed which causes tools like `miri` can't find `rust-src`.

### PR DESCRIPTION
**Pull request by onur-ozkan**
Provides tool binaries under the sysroot which can be used/tested with `cargo +custom-toolchain $tool`

Clippy and fmt works without any problem.

But can't say the same for miri:

```sh
  ~/devspace/.other/chunk-list  stable $ cargo +stage2 miri setup
Running `"rustup" "component" "add" "rust-src"` to install the `rust-src` component for the selected toolchain.
error: stage2 is a custom toolchain
fatal error: failed to install the `rust-src` component for the selected toolchain
```

it's looking for `$sysroot/lib/rustlib/src/rust/library` and that simply doesn't exists for `x build`.

cc @jyn514 (I thought you might be interested on this, since you did few review iterations on previous PRs of adding tools to sysroot)

--

**Update**

Now we are able to use `miri` as well.

After running `x b miri cargo-miri --stage 2`, I am able to run `cargo +stage2 miri setup` which works as expected.

Resolves #110625
Resolves #97762
Resolves #81431

### CODE REVIEW

**Comment by ozkanonur** [comment]
I decided to write tests for this @rustbot author

**Comment by jyn514** [comment]
> it's looking for `$sysroot/lib/rustlib/src/rust/library` and that simply doesn't exists for `x build`.

it should be possible to add this, right? We can make a symlink from `rust` to the root of the repository. I thought we already did that today actually but maybe I'm thinking of something else.

**Comment by ozkanonur** [comment]
> it should be possible to add this, right? We can make a symlink from `rust` to the root of the repository.

I wasn't sure if we should do it or not, will do it then. 

> I thought we already did that today actually but maybe I'm thinking of something else.

Maybe something changed/broke it? I don't know how this error didn't raise on the [previous PR](https://github.com/rust-lang/rust/pull/102010).

**Comment by ozkanonur** [comment]
> I decided to write tests for this

This turns out not to be worth doing it. It will require quite some time for just checking if the binaries are in the correct place after `x b $tool` command which requires compilation. I think it's worth adding this one into https://github.com/rust-lang/rust/issues/102563#issuecomment-1510497718 which I will start start working on that soon.

**Comment by ozkanonur** [comment]
`cargo +stage2 miri test` gives the following in simple cargo project:

```
  ~/devspace/.other/chunk-list  stable $ cargo +stage2 miri test
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CargoMetadata { stderr: "error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel\nSee https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.\n" }', src/tools/miri/cargo-miri/src/util.rs:224:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which seems like an expected result if I am not mistaken?

**Comment by jyn514** [comment]
Try installing nightly cargo so it gets further (`rustup install nightly`), or set RUSTC_BOOTSTRAP=1 so the stable cargo works.

**Comment by ozkanonur** [comment]
> Try installing nightly cargo so it gets further (`rustup install nightly`), or set RUSTC_BOOTSTRAP=1 so the stable cargo works.

OOps. Why I didn't do that lol.

here we go:
```sh
  ~/devspace/.other/chunk-list  stable $ cargo +stage2 miri test
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
   Compiling chunk-list v0.1.0 (/home/nimda/devspace/.other/chunk-list)
    Finished test [unoptimized + debuginfo] target(s) in 0.06s
     Running unittests src/main.rs (target/miri/x86_64-unknown-linux-gnu/debug/deps/chunk_list-b3b731111ba842c5)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by jyn514** [comment]
this looks amazing! r=me after a rebase :)

**Pull request merged**
