### PR TITLE
Remove rustc's std copy

### PR DESCRIPTION
**Pull request by Zoxc**
This removes rustc's std copy if we're statically linking `std` into `rustc_driver`. This copy is not needed after https://github.com/rust-lang/rust/pull/122362.

try-job: dist-x86_64-linux
try-job: dist-x86_64-msvc

### CODE REVIEW

**Comment by Kobzol** [comment]
Could you please comment [this line](https://github.com/rust-lang/rust/blob/9f7e049744bcbc77150c66f5ab39fd46c074a22c/src/ci/github-actions/jobs.yml#L71) in this PR, to enable post-optimization tests in the x64 Linux dist runner? Then we can try the dist tests in try builds.

**Comment by lqd** [comment]
This PR is still a WIP in order to run tests/debug/try alternatives on builders, right? As it currently looks like https://github.com/rust-lang/rust/pull/122362/commits/dd3f7578ee52af74de732f8a8e6dc5d02b284daa which failed in the previous PR.

**Comment by Kobzol** [comment]
Yeah, post-optimization tests essentially take the sysroot created in the `dist` step, and try to run tests with it (using the "allow stage0 sysroot" hack). It is implemented [here](https://github.com/rust-lang/rust/blob/f8060d282d42770fadd73905e3eefb85660d3278/src/tools/opt-dist/src/tests.rs#L63).

**Comment by Kobzol** [comment]
It seems like this could progress after https://github.com/rust-lang/rust/pull/129941. I tried it locally and we can remove the `stage != "0"` check and do [this](https://github.com/rust-lang/rust/commit/61438ebac776276e63d255b4e5cb0423f0a14706). And then see what tests break :)

**Comment by Kobzol** [comment]
Posted https://github.com/rust-lang/rust/pull/131188 with some additional modifications.

**Comment by lqd** [comment]
Ah so we still don’t really know what’s going on to fix it "properly" on windows as well?

**Comment by Kobzol** [comment]
I have no idea why the tests fail on Windows :( https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Failing.20incr.20tests.20on.20Windows.20when.20std.2Edll.20is.20missing/near/474507064

**Comment by Kobzol** [comment]
Probably can be closed now that https://github.com/rust-lang/rust/pull/131188 was merged.

**Pull request closed without merging**
