### PR TITLE
Fix non-clickable urls

### LINKED ISSUE #57695: Implementors in documentation aren't clickable
Compare:

https://doc.rust-lang.org/stable/std/panic/trait.RefUnwindSafe.html
https://doc.rust-lang.org/nightly/std/panic/trait.RefUnwindSafe.html

It's not possible to click on `AtomicBool` in `impl RefUnwindSafe for AtomicBool` anymore, while it is possible on stable and beta.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #57695

I didn't find anywhere where this rule was useful. Why did you add it @JohnHeitmann?

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@bors rollup

r=me, but i want to hold off actually putting this into the queue until we hear back from @JohnHeitmann.

**Comment by JohnHeitmann** [comment]
I believe that was to fix an issue with the "Important traits for..."
tooltip getting partially z sorted behind parts of the main block. I'm
looking at it now to refresh my memory...

**Comment by JohnHeitmann** [comment]
+1 to your change. Thanks for handling that, and sorry for the breakage!

Here's what happened:

Prior to my changes that selector was setting the z-index to a positive number-- I'm not sure why. When I simplified the markup, for some reason that positive z-index caused the code headers to bleed into the "Important traits..." tooltip like this (I just repro'd this to be sure):

screen shot 2019-01-17 at 9 45 24 pm

I don't know why I set it to a negative value instead of deleting it. I'd guess it was just a quick 'n dirty fix I forgot to revisit before submission. I just tested your change in a few scenarios and don't see any problems with it.

For the future: another easy to miss z problem happens in the mobile overlay menus. I tested to be sure and your patch doesn't re-break those either.

**Comment by GuillaumeGomez** [comment]
Ok, so now I know where the issue is. :)

**Comment by tspiteri** [comment]
@GuillaumeGomez @QuietMisdreavus Should this be backported to beta? Currently the beta docs have non-clickable method names. (I guess the highlighting will be fixed when #57859 is eventually backported.)

**Comment by QuietMisdreavus** [comment]
Oof, i didn't realize this issue was on beta. Nominating (and immediately accepting) backport.

**Pull request merged**
