### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #91938 (Add `std::error::Report` type)
 - #92277 (rustc_metadata: Stop passing `CrateMetadataRef` by reference (step 1))
 - #92334 (rustdoc: Preserve rendering of macro_rules matchers when possible)
 - #92535 (Allow unwinding from OOM hooks)
 - #92703 (RELEASES.md: Add 1.58 release note for `File::options` stabilization)
 - #92707 (Extended the note on the use of `no_run` attribute)
 - #92720 (Fix doc formatting for time.rs)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=91938,92277,92334,92535,92703,92707,92720)

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors retry

Yield to the stable release.

**Comment by hkratz** [comment]
I don't think the timeout of `dist-x86_64-msvc-alt` is spurious, the build hangs at the same point during the stage 1 rust-analyzer build: [1](https://github.com/rust-lang-ci/rust/runs/4770421709?check_suite_focus=true), [2](https://github.com/rust-lang-ci/rust/runs/4766573495?check_suite_focus=true).  Looking back rollup #92593 hat the exact same timeout: [3](https://github.com/rust-lang-ci/rust/runs/4721304130?check_suite_focus=true). The only shared PR is #92535, so it seems likely that that is at fault.

**Comment by camelid** [comment]
Yeah, when I retried it, I wondered if it could be that PR, but I thought it was worth retrying in case it was spurious.

**Comment by ehuss** [comment]
Closing out a stale rollup.

**Pull request closed without merging**
