### PR TITLE
rustdoc: add --deny-doctest-warnings option

### PR DESCRIPTION
**Pull request by pshc**
Collaboration with @rylev! Addresses #20787.

We kind of brute forced this flag into the call path for `maketest`, so we're soliciting better designs :facepunch: 

Also, we're wondering if we should turn this into a generic `-D` option, like @brson was saying. What would that look like? Would we have to implement all four flags (W, A, D, F)?

### CODE REVIEW

**Comment by brson** [comment]
Do you mind trying to turn this on for the in-tree doc tests as well? It looks like these are the lines to edit:

* https://github.com/rust-lang/rust/blob/7541f82faba6b2839b5e640605d7caab6cc6ec4f/mk/tests.mk#L818
* https://github.com/rust-lang/rust/blob/7541f82faba6b2839b5e640605d7caab6cc6ec4f/mk/tests.mk#L857

There's a chance that with the current state of the tree there will be a great number of warnings. If so we'll have to decide how to deal with them. `make check-docs NO_MKFILE_DEPS=1` will run the doc tests quickly without rebuilding the whole tree because of the makefile change.

**Comment by brson** [comment]
@alexcrichton What do you think of this command-line flag and having to support it indefinitely?

**Comment by pshc** [comment]
I'll give it a shot!

**Comment by pshc** [comment]
It is done. :wind_chime:

**Comment by alexcrichton** [comment]
Would it be possible to use the same `-D foo` syntax that the compiler uses? That way this would actually just be `rustdoc -D warnings ...` and would mirror the compiler well (plus setting different various levels).

The options would have to be documented, however, as only applying to doctests rather than documentation in general.

**Comment by pshc** [comment]
@alexcrichton Sure thing.

**Comment by pshc** [comment]
@alexcrichton Oh, I didn't notice you said "option**s**" the first time. Should I just hardcode `-D warnings`, or also provide `-F` and `-A` and `-W`?

**Comment by alexcrichton** [comment]
I would probably add flags for all of `-A`, `-F`, `-W`, and `-D` to rustdoc and then our build system can pass `-D warnings` by default.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Pull request closed without merging**
