### PR TITLE
Fix RPITITs in default trait methods (by assuming projection predicates in param-env)

### LINKED ISSUE #107002: Unexpected behaviour when calling associated async function of a trait with default implementations
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e1f645e0ffe95f137fc42c12e783488b

```rust
#![feature(async_fn_in_trait)]

trait AsyncTrait {
    async fn default_impl() -> &'static str {
        "A"
    }

    async fn call_default_impl() -> &'static str {
        Self::default_impl().await
    }
}

trait SyncTrait {
    fn default_impl() -> &'static str {
        "A"
    }

    fn call_default_impl() -> &'static str {
        Self::default_impl()
    }
}

struct AsyncType;

impl AsyncTrait for AsyncType {
    async fn default_impl() -> &'static str {
        "B"
    }
}

struct SyncType;

impl SyncTrait for SyncType {
    fn default_impl() -> &'static str {
        "B"
    }
}

#[tokio::main]
async fn main() {
    let a = AsyncType::call_default_impl().await;
    let b = SyncType::call_default_impl();
    println!("{a}, {b}");
}
```

I expected to see this happen:
`SyncType::call_default_impl` calls `default_impl` from `impl SyncTrait for SyncType`.
My expectation was the same for `AsyncType::call_default_impl` of the same pattern.

Instead, this happened:
`AsyncType::call_default_impl` calls `default_impl` from the trait's default implementation,
instead of the one in `impl AsyncTrait for AsyncType`.

So the code prints `A, B`

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (afaf3e07a 2023-01-14)
binary: rustc
commit-hash: afaf3e07aaa7ca9873bdb439caec53faffa4230c
commit-date: 2023-01-14
host: x86_64-pc-windows-msvc
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Instead of having special projection logic that allows us to turn `ProjectionTy(RPITIT, [Self#0, ...])` into `OpaqueTy(RPITIT, [Self#0, ...])`, we can instead augment the param-env of default trait method bodies to assume these as projection predicates. This should allow us to only project where we're allowed to!

In order to make this work without introducing a bunch of cycle errors, we additionally tweak the `OpaqueTypeExpander` used by `ParamEnv::with_reveal_all_normalized` to not normalize the right-hand side of projection predicates. This should be fine, because if we use the projection predicate to normalize some other projection type, we'll continue to normalize the opaque that it gets projected to.

This also makes it possible to support default trait methods with RPITITs in an associated-type based RPITIT lowering strategy without too much extra effort.

Fixes #107002
Alternative to #108142

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? types

**Comment by jackh726** [comment]
I like this. Not sure if you had anyone else in mind that you wanted to look at this?

r=me if not

**Comment by compiler-errors** [comment]
I don't think so, I already discussed the idea with @lcnr and it seems to have worked. We can always remove it later.

@bors r=jackh726

**Comment by fasterthanlime** [comment]
This [did the trick](https://github.com/hapsoc/hring/pull/86) for hring, thanks for the fix!

**Pull request merged**
