### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #88368 ( Improve error when an .rlib can't be parsed)
 - #88546 (Emit proper errors when on missing closure braces)
 - #88578 (fix(rustc): suggest `items` be borrowed in `for i in items[x..]`)
 - #88632 (Fix issues with Markdown summary options)
 - #88639 (rustdoc: Fix ICE with `doc(hidden)` on tuple variant fields)
 - #88732 (RustWrapper: avoid deleted unclear attribute methods)
 - #88745 (Allow missing code examples in trait impls.)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=88368,88546,88578,88632,88639,88732,88745)

### CODE REVIEW

**Comment by Emilgardis** [comment]
Doesnt https://github.com/rust-lang/rust/pull/88546 contain a merge commit?

**Comment by GuillaumeGomez** [comment]
Well, it failed CI so that resolves the problem. :)

**Comment by scrabsha** [comment]
> 
> 
> Doesnt #88546 contain a merge commit?

Yes, sorry for that. I'll force push and squash my work as soon as possible

**Comment by GuillaumeGomez** [comment]
@scrabsha Thanks!

**Comment by jyn514** [comment]
It's strange that this failed test-various when it succeeded on x86_64-gnu-llvm-10 ... maybe it's related to cross-compiling somehow?

**Comment by jyn514** [comment]
> +    = note: extern location for bar is of an unknown type: $DIR/auxiliary/libbar.so
+    = help: file name should be lib*.rlib or *..wasm

Oh, this is the issue - apparently the wasm target doesn't recognize .so files.

**Pull request closed without merging**
