### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #40154, #40222, #40226, #40258, #40283, #40292, #40293, #40316
- Failed merges:

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: retry

seems like a spurious network error

**Comment by steveklabnik** [comment]
@bors: retry

couldn't get packages from crates.io

**Comment by frewsxcv** [comment]
Since when do we use ruby?

**Comment by frewsxcv** [comment]
Regardless, seems like a spurious rubygem failure?

@bors retry

**Comment by steveklabnik** [comment]
```
Build completed successfully in 1:59:50
```

😭 

We don't use ruby, it's travis stuff

**Comment by arielb1** [comment]
```
cp: error writing '/checkout/obj/build/tmp/dist/rust-docs-nightly-i586-unknown-linux-gnu/rust-docs/share/doc/rust/html/rustdoc.css': No space left on device
```

**Pull request closed without merging**
