### PR TITLE
Deny future duplication of rustc-ap-syntax

### LINKED ISSUE #53005: Deduplicate Cargo in the RLS on CI
Once https://github.com/rust-lang/rust/pull/52919 lands we'll have updated the RLS which updates `racer`, and `racer` has recently picked up a dependency on the `cargo` crate. Unfortunately though this is a `cargo` crate from crates.io, which differs from the `src/tools/cargo` crate in-tree. This means that when we build the RLS it's linking against *two* optimized versions of Cargo, which not only takes up a good deal of space but also takes up a good deal of build time.

In talking with @nrc on IRC one solution here would be to avoid using racer's `cargo` feature. The RLS already depends on `cargo`-the-crate and should be able to provide the functionality necessary for racer, for example implementing [racer's `ProjectModelProvider` trait](https://github.com/racer-rust/racer/blob/18bd2c510a195bb21fe520c73c43a4ed9515e6c7/src/racer/project_model.rs#L33-L39)

### LINKED ISSUE #53006: Deduplicate rustc-ap-syntax in the RLS
As of https://github.com/rust-lang/rust/pull/52919 we'll be updating to a version of the RLS which depends on racer which depends on `rustc-ap-syntax`. Unfortunately we're bringing in two different versions of `rustc-ap-syntax`, 209 and 211, right now.

These should be deduplicated as they take a good deal of time to build on CI, and then we should also add a `tidy` check which ensures that there's only one version of `rustc-ap-syntax` in our workspace.

cc @nrc

### PR DESCRIPTION
**Pull request by alexcrichton**
Enable the tidy check to forbid this!

Closes #53006

### CODE REVIEW

**Comment by kennytm** [comment]
This should be closing #53006 (I've fixed the PR description but the commit message still refers to #53005).

**Comment by alexcrichton** [comment]
Oops should be updated now!

**Pull request merged**
