### PR TITLE
librustc_typeck => 2018

### PR DESCRIPTION
**Pull request by taiki-e**
Transitions `librustc_typeck` to Rust 2018; cc #58099

TODO: elided_lifetimes_in_paths

r? @Centril

### CODE REVIEW

**Comment by petrochenkov** [comment]
Any crate that uses `TyCtxt` should opt out of `elided_lifetimes_in_paths` IMO.
`TyCtxt<'_, '_, '_>` is not the way to go.

**Comment by Centril** [comment]
@petrochenkov We can leave that change out of this PR cause I just want to get all crates migrated... However, `Formatter` or `TyCxt` will become distinctly unidiomatic and hopefully quite deprecated soon and I don't think that rustc should block that.

**Pull request merged**
