### PR TITLE
snapshot + s/range(a, b)/a..b/g + s/Show/Debug/g cleanup

### PR DESCRIPTION
**Pull request by japaric**
Note: Do not merge until we get a newer snapshot that includes #21374

There was some type inference fallout (see 4th commit) because type inference with `a..b` is not as good as with `range(a, b)` (see #21672).

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me whenever this is ready, nice work @japairc!

cc @aturon, we may be able to remove `range` from the prelude soon (or at least deprecated it). May want to get #21672 dealt with though.

**Comment by alexcrichton** [comment]
r=me with a deprecation warning about `derive(Show)` (talked about on IRC)

**Comment by tshepang** [comment]
I see a bunch of `u` suffixes which should be `us`.

**Comment by japaric** [comment]
@tshepang yes, there are bunch of places where the `i`/`u` suffixes are still being used. I sticked to either keep the suffix as it is, or add either `u`/`us` based on what the surrounding code was using. I think someone was already working on/sent a PR updating the suffixes though. If not, it can be done afterwards :-).

**Pull request merged**
