### PR TITLE
rustc_typeck: remove the "preload all impls ever" workaround in coherence.

### LINKED ISSUE #22068: Compiling hello world on RPi spends 4 seconds in coherence checking
My `rustc` is from @japaric's [nightlies](http://www.reddit.com/r/rust/comments/2v3xin/unofficial_rust_and_cargo_nightlies_for_arm_again/).  It's pretty slow overall, but what stands out is that we spend nearly 4s on coherence checking.

```
pi@inky /tmp $ rustc --version
rustc 1.0.0-dev (d3732a12e 2015-02-06 23:30:17 +0000)
pi@inky /tmp $ cat hello-world.rs 
fn main() {
    println!("Hello, world!");
}
pi@inky /tmp $ time rustc -Z time-passes hello-world.rs
time: 0.004     parsing
time: 0.000     recursion limit
time: 0.008     gated macro checking
time: 0.000     configuration 1
time: 0.001     crate injection
time: 0.127     plugin loading
time: 0.000     plugin registration
time: 0.069     expansion
time: 0.000     complete gated feature checking
time: 0.000     configuration 2
time: 0.000     maybe building test harness
time: 0.000     prelude injection
time: 0.000     checking that all macro invocations are gone
time: 0.000     assigning node ids and indexing ast
time: 0.000     external crate/lib resolution
time: 0.002     language item collection
time: 0.176     resolution
time: 0.000     lifetime resolution
time: 0.000     looking for entry point
time: 0.000     looking for plugin registrar
time: 0.000     region resolution
time: 0.000     loop checking
time: 0.000     static item recursion checking
time: 0.003     type collecting
time: 0.000     variance inference
time: 3.853     coherence checking
time: 0.025     type checking
time: 0.069     check static items
time: 0.000     const marking
time: 0.000     const checking
time: 0.001     privacy checking
time: 0.000     stability index
time: 0.000     intrinsic checking
time: 0.000     effect checking
time: 0.001     match checking
time: 0.000     liveness checking
time: 0.105     borrow checking
time: 0.008     rvalue checking
time: 0.000     reachability checking
time: 0.000     death checking
time: 0.000     stability checking
time: 0.000     unused lib feature checking
time: 0.002     lint checking
time: 0.000     resolving dependency formats
time: 0.201     translation
  time: 0.003   llvm function passes
  time: 0.003   llvm module passes
  time: 0.122   codegen passes
  time: 0.007   codegen passes
time: 0.243     LLVM passes
  time: 6.600   running linker
time: 6.611     linking

real    0m12.263s
user    0m7.510s
sys     0m0.720s
```

### PR DESCRIPTION
**Pull request by eddyb**
The loop to load all the known impls from external crates seems to have been used because `ty::populate_implementations_for_trait_if_necessary` wasn't doing its job, and solely relying on it resulted in loading only impls in the same crate as the trait.

Coherence for `librustc` was reduced from 18.310s to 0.610s, from stage1 to stage2.
Interestingly, type checking also went from 46.232s to 42.003s, though that could be noise or unrelated improvements.

On a smaller scale, `fn main() {}` now spends 0.003s in coherence instead of 0.368s, which fixes #22068.
It also peaks at only 1.2MB, instead of 16MB of heap usage.

### CODE REVIEW

**Comment by eddyb** [comment]
@brson Any chance this can make it into 1.0? I don't mind it personally, but I've seen some interest on IRC for having the (minor IMO) compile-time wins here in 1.0.

**Comment by bstrie** [comment]
@eddyb, you're my hero :heart_eyes_cat:

**Comment by pnkfelix** [comment]
(Regarding 1.0, I'm inclined to say the risk/reward here does not pay off; there are other lower risk PR's that also have UX impact that we declined much earlier in beta cycle)

**Comment by pnkfelix** [comment]
Cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Without reading too closely, this looks great to me, and I agree with @pnkfelix's assessment that this is not a good candidate for backporting.

**Comment by killercup** [comment]
Nice, those are some serious speedups! Looks like 1.1 will already improve compile speed.

**Pull request merged**
