### PR TITLE
Organize `never_type`  tests

### PR DESCRIPTION
**Pull request by Centril**
Extracted from https://github.com/rust-lang/rust/pull/65355.
This just moves some tests around to make things better categorized.

r? @varkor

### CODE REVIEW

**Comment by Centril** [comment]
Would be nice! Let me see if that can be done. :)

**Comment by Centril** [comment]
@varkor I moved the `run-fail/never_type` tests to `ui/never_type`. The remainder of `run-fail/` should also be moved but I think we can do that in a follow up to categorize them properly.

**Comment by varkor** [comment]
r=me after squashing when CI passes.

**Pull request merged**
