### PR TITLE
syntax: unbox MacResult

### PR DESCRIPTION
**Pull request by ljedrz**
This was an adventure.

It should reduce the number of allocations. Can we do a perf run?

I haven't adjusted the tests yet, but I'd like to make sure it is an improvement before I do those; a `try` build should work.

### CODE REVIEW

**Comment by ljedrz** [comment]
Perf looks unaffected; still, I think this change can be a nice cleanup. I'll just clean *it* up a little bit first.

**Comment by ljedrz** [comment]
Done; I think it's an improvement to always know what the possible `MacResult`s are and not to have to shuffle `Box`es all around the place.

**Comment by petrochenkov** [comment]
@ljedrz 
Please make sure run-pass-fulldeps tests pass before the PR is reviewed.

At least in some places `dyn MacResult` is used because macro results are supposed to be an open set, not a closed enum like `MacroResult`, so that legacy proc macros can implement it without touching our libsyntax.
This PR is probably not a right place to un-support legacy proc macros in general.

You could see e.g. the move of `ConcatIdentsResult` from `libsyntax_ext` to `libsyntax` as a bad sign - a syntax extension that previously was self-contained now requires libsyntax to know about it.
Syntax extensions outside of this repo cannot do that.

**Comment by petrochenkov** [comment]
Basically, a legacy proc macro should be able to define its own macro result type (like `concat_ident` did) and still continue working.
(You can actually add a test for this if there's none yet.)

**Comment by ljedrz** [comment]
@petrochenkov hmm, this makes things a bit more complicated. Since there is a `Self: Sized` bound on `MacResult`, I see no simple way of mixing a generic implementor of `MacResult` with `MacroResult`.

I fixed the `run-pass-fulldeps` tests; I'd be happy to adjust the PR if anything is salvageable.

**Comment by oli-obk** [comment]
> I fixed the run-pass-fulldeps tests; 

I think you forgot to push those changes

**Comment by petrochenkov** [comment]
@ljedrz 
>I'd be happy to adjust the PR if anything is salvageable

You should be able to keep everything that doesn't require changing interfaces of `TTMacroExpander` and `IdentMacroExpander`.
(I'm not sure whether it's an empty set or not.)

**Comment by ljedrz** [comment]
@oli-obk I did, I just squashed the fixes; [github can show these changes](https://github.com/rust-lang/rust/compare/e81dec5317a3e93c27aebf46f8477ffc2378902a..7635ee6dc0a4e02ae0b00d836b28327aa9ed25a6).

**Comment by ljedrz** [comment]
@petrochenkov that's a no then ^^.

**Pull request closed without merging**
