### PR TITLE
test: Move run-make tests into compiletest

### PR DESCRIPTION
**Pull request by alexcrichton**
Forcing them to be embedded in makefiles precludes being able to run them in
rustbuild, and adding them to compiletest gives us a great way to leverage
future enhancements to our "all encompassing test suite runner" as well as just
moving more things into Rust.

All tests are still Makefile-based in the sense that they rely on `make` being
available to run them, but there's no longer any Makefile-trickery to run them
and rustbuild can now run them out of the box as well.

### CODE REVIEW

**Comment by pnkfelix** [comment]
@alexcrichton why did you surround `$(CC_$(1))` with single quotes, producing `'$(CC_$(1))'` in the makefile?

From what I can tell, this breaks my use of `--enable-ccache` (because it works by putting e.g. `ccache clang` in as the `CC` variable, but now those single quotes are causing the whole string `"ccache clang"` to be interpreted as the program name by the shell.

Is this to accommodate Windows or something?

**Comment by alexcrichton** [comment]
Yes the single quotes were to accomodate windows where cl.exe has lots of spaces in the path, currently.

**Pull request merged**
