### PR TITLE
include_bytes! now registers the file included

### PR DESCRIPTION
**Pull request by tbelaire**
This is a little bit tricky, since with include_str!, we know that we
are including utf-8 content, so it's safe to store the source as a
String in a FileMap. We don't know that for include_bytes!, but I don't
think we actually need to track the contents anyways, so I'm passing "".

new_filemap does check for the zero length content, and it should be
reasonable, howeven I'm not sure if it would be better to pass None
instead of Some(Rc::new("")) as the src component of a FileMap.

Fixes bug #24348

### CODE REVIEW

**Comment by tbelaire** [comment]
Thanks @nicholasbishop, your [test case][1] was really helpful.

[1]: https://github.com/nicholasbishop/cargo-includes-bug

**Comment by alexcrichton** [comment]
Thanks! Could you add a test for this as well?

**Comment by tbelaire** [comment]
I have no idea how to test this, I'm sorry.  Help?

**Comment by tbelaire** [comment]
I mean, I did test using cargo and seeing if it rebuild the target when the input changed, but I don't know how to integrate that with rust's tests.

**Comment by nagisa** [comment]
> howeven I'm not sure if it would be better to pass None instead of Some(Rc::new("")) as the src component of a FileMap.

No, because then the file won’t be included into the list of dependencies.

**Comment by alexcrichton** [comment]
You'll probably want to add a `run-make` test which generates a `dep-info` file with a source that has `include_bytes!`, and then you can check to make sure the emitted `.d` file indeed has the file name as expected.

**Comment by tbelaire** [comment]
Alright, I think I understand how the tests work.  How this look?

**Comment by alexcrichton** [comment]
@bors: r+ e4b3fac

Thanks!

**Comment by krh** [comment]
Hi, sorry to crash the discussion 6 years later, but is there a way now that this kind of dependency can be logged from custom, user-written macros? I'd like to write a macro that parses an xml spec and generates code on-the-fly, but I'd want to be able to log this kind of dependency so that when the spec is edited, the rust file that includes it is recompiled.

**Comment by jonas-schievink** [comment]
Please ask questions on https://users.rust-lang.org/, not on the issue tracker

**Pull request merged**
