### PR TITLE
Bootstrap: reorder tools to properly reflect their build order

### PR DESCRIPTION
**Pull request by mati865**
Noticed in https://github.com/rust-lang/rust/issues/74016#issuecomment-653714914

RLS depends on Clippy and Rustfmt.

### CODE REVIEW

**Comment by mati865** [comment]
Also cc @ehuss

**Comment by Mark-Simulacrum** [comment]
I don't have time to repeat @ehuss' investigative work here, so let's r? @ehuss

**Comment by ehuss** [comment]
This doesn't actually change the order, at least for `x.py`. The order is defined by the [Extended step](https://github.com/rust-lang/rust/blob/1d919c9377f4602d991ca1c7ba852e7555943740/src/bootstrap/dist.rs#L1740-L1760).

Although changing the order can help a little, I still think it is more important to merge #74046, which should significantly reduce the rebuilds.

It looks like rust-analyzer is also causing some issues, I'm going to investigate that more.

**Comment by mati865** [comment]
Order in `get_step_descriptions` matters for `test` subcommand and I assumed `dist` would also follow it. Sorry for the noise.

**Pull request closed without merging**
