### PR TITLE
rustdoc: Unindent doc fragments on `Attributes` construction

### PR DESCRIPTION
**Pull request by petrochenkov**
`Attributes` can be constructed at arbitrary points, even after the `unindent_comments` pass.
`Attributes` that are constructed too late end up unindented.

All doc fragments need to be eventually indented before use, so there are no reasons to not do this immediately during their construction.

Fixes https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/.60unindent_comments.60.20cannot.20work.20as.20a.20separate.20pass.
I'm not sure how to make a minimized reproduction, but unindenting the fragments during their construction should fix the issue.. by construction, and I also verified that all doc strings now hit the `resolver_caches.markdown_links` cache in https://github.com/rust-lang/rust/pull/94857.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks for working on this! I think it'll be positive for perf so let's confirm it!

@bors try @rust-timer queue

**Comment by GuillaumeGomez** [comment]
I wonder if there is a possibility that attributes are cleaned more than once in some cases...

**Comment by petrochenkov** [comment]
Maybe.
I've seen something that could be it when debugging https://github.com/rust-lang/rust/pull/94857.
If there's no explicit check against it then it's quite possible.

**Comment by GuillaumeGomez** [comment]
Since it was a pass, there was no need for it. Maybe you might know more about this @camelid ?

**Comment by camelid** [comment]
The regression is only on artificial benchmarks (I include `helloworld` amongst those), so it doesn't seem to matter much in practice.

I'm not sure why there's a regression; I would've expected perf improvement. The only thing I can think of is what you said, that it's being cleaned multiple times.

**Comment by petrochenkov** [comment]
>I'm not sure why there's a regression; I would've expected perf improvement.

Well, we are applying `unindent_comments` to more attributes after all, the delta is attributes that are created after the `unindent_comments` pass and weren't previously unindented, that's kind of the purpose of the PR.

**Comment by GuillaumeGomez** [comment]
I'm not sure it's only the new types getting unindented that have this impact. I think it's called more than once, but let's worry about it in another PR as this is already a nice improvement. Can you open an issue to investigate about this so we don't forget please @petrochenkov ?

@bors: r+ rollup=never

**Comment by rylev** [comment]
Given there is an issue to investigate this further and the regressions are relatively small and confined to non-real-world crates, I'll mark this as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
