### PR TITLE
Migrate crate-search element to CSS variables

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
There should no UI changes.

r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed lint.

**Comment by Manishearth** [comment]
note: there's a chance this will have a conflict with https://github.com/rust-lang/rust/pull/104168

**Comment by GuillaumeGomez** [comment]
Thanks for the notification! It's common for the CSS migration PRs, I'll just rebase once the conflict is reported.

**Pull request merged**
