### PR TITLE
fix make check-stage1

### PR DESCRIPTION
**Pull request by arielb1**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
As [I've mentioned](https://github.com/rust-lang/rust/pull/27417#issuecomment-132652235) on #27417 let's just take the route of removing `-Z no-landing-pads` for now, it's by far the easiest and doesn't require separate code paths. Requiring a stage2 compiletest requires compiling the entire stage1 compiler before `check-stage1-rpass` can be run which is pretty unfortunate.  This PR also uses features like `#[thread_local]` (not portable) and `rt::unwind::register` (super unstable) which I would prefer to avoid.

**Comment by arielb1** [comment]
separate code paths?

**Comment by nrc** [comment]
r? @alexcrichton 

kicking back to acrichto - I'm not familiar with the background here. Also cc @rust-lang/tools.

**Comment by alexcrichton** [comment]
Closing due to inactivity, and given the discussion on the [discuss thread](https://internals.rust-lang.org/t/stage1-tests-and-landing-pads/2606/9) I've opened https://github.com/rust-lang/rust/issues/28710 to track this.

**Pull request closed without merging**
