### PR TITLE
Use `Arc` as `Lrc` for parallel compiler

### PR DESCRIPTION
**Pull request by SparrowLii**
part of https://github.com/rust-lang/rust/pull/101566

Test perf of `Lrc` and make optimization

### CODE REVIEW

**Comment by jackh726** [comment]
@SparrowLii what do you want to do with this PR?

@rustbot author

**Comment by SparrowLii** [comment]
Yea, since use `Arc` as `Lrc` doesn't impact the perf, I think we can just do this

**Comment by SparrowLii** [comment]
I think we can just unmerge it and wait until the other work of parallel compilation is done.

**Comment by jackh726** [comment]
I'm not sure it's worth leaving this open for some undefined period of time. Perf seems good enough to merge if you'd like to do that. Otherwise, I think we should just close it.

**Comment by SparrowLii** [comment]
That makes sense. We'd better close it now

**Pull request closed without merging**
