### PR TITLE
Fix async-std by special-casing rustdoc in typeck

### LINKED ISSUE #75100: Fix rustdoc hack allowing async-std docs to build
Original issue surfaced in: https://github.com/async-rs/async-std/pull/845 by @dignifiedquire. It appears that sometime after `2020-05-01` nightlies are no longer able to build  `async-std` docs. https://github.com/rust-lang/rust/pull/73566 appears to be a likely cause for this regression.

We use a fairly elaborate macro to generate docs, so we're not particularly surprised that a big refactor may have caused issues there. But it'd still be nice if we could get it to work again.

## Error

The error message is fairly long and probably not worth posting in full. Luckily it does not appear to be an ICE, just a regression. This is the build that fails: [link](https://github.com/async-rs/async-std/pull/845/checks?check_run_id=932478962).

### PR DESCRIPTION
**Pull request by jyn514**
This is the same sort of idea as #73566, but for typeck instead of resolve. I don't claim this is anywhere close to a _good_ solution, but hopefully it's enough to unbreak async-std until we find a more principled fix.

On the bright side, unlike everybody_loops, this allows errors in _any_ `impl Trait`, not just `async fn`.

Fixes https://github.com/rust-lang/rust/issues/75100.

### CODE REVIEW

**Comment by jyn514** [comment]
<details><summary>Failures</summary>

```
Check compiletest suite=rustdoc-ui mode=ui (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 59 tests
....................FF.....FFFFFF...........i..............
failures:

---- [ui] rustdoc-ui/error-in-impl-trait/async.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/error-in-impl-trait/async.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/async" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition=2018" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/async/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------


---- [ui] rustdoc-ui/error-in-impl-trait/closure.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/error-in-impl-trait/closure.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/closure" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/closure/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------


---- [ui] rustdoc-ui/error-in-impl-trait/generic-argument.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/error-in-impl-trait/generic-argument.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/generic-argument" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/generic-argument/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------


---- [ui] rustdoc-ui/error-in-impl-trait/impl-keyword-closure.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/error-in-impl-trait/impl-keyword-closure.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/impl-keyword-closure" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/impl-keyword-closure/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------


---- [ui] rustdoc-ui/error-in-impl-trait/impl-keyword.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/error-in-impl-trait/impl-keyword.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/impl-keyword" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/impl-keyword/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------


---- [ui] rustdoc-ui/error-in-impl-trait/trait-alias.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/error-in-impl-trait/trait-alias.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/trait-alias" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/trait-alias/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------


---- [ui] rustdoc-ui/error-in-impl-trait/trait-alias-closure.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/error-in-impl-trait/trait-alias-closure.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/trait-alias-closure" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/error-in-impl-trait/trait-alias-closure/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------


---- [ui] rustdoc-ui/infinite-recursive-type.rs stdout ----
diff of stderr:

-	error[E0072]: recursive type `E` has infinite size
+	error: internal compiler error[E0391]: cycle detected when computing `Sized` constraints for `E`
2	  --> $DIR/infinite-recursive-type.rs:1:1
3	   |
4	LL | enum E {

-	   | ^^^^^^ recursive type has infinite size
-	LL |
-	LL |     V(E),
-	   |       - recursive without indirection
+	   | ^^^^^^
9	   |
-	help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `E` representable
+	   = note: ...which again requires computing `Sized` constraints for `E`, completing the cycle
+	   = note: cycle used when evaluating trait selection obligation `E: std::convert::From<E>`
+	
+	error: internal compiler error: TyKind::Error constructed but no error reported
11	   |
-	LL |     V(Box<E>),
-	   |       ^^^^ ^
+	   = note: delayed at /home/joshua/rustc/src/librustc_session/session.rs:436:27
14	
-	error: aborting due to previous error
+	thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
+	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
16	
-	For more information about this error, try `rustc --explain E0072`.
+	error: internal compiler error: unexpected panic
+	
+	note: the compiler unexpectedly panicked. this is a bug.
+	
+	note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
+	
+	note: rustc 1.47.0-dev running on x86_64-unknown-linux-gnu
+	
+	note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z unstable-options -C debuginfo=0
+	
18	


The actual stderr differed from the expected stderr.
Actual stderr saved to /home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/infinite-recursive-type/infinite-recursive-type.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args infinite-recursive-type.rs`

error: 1 errors occurred comparing output.
status: exit code: 1
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "/home/joshua/rustc/src/test/rustdoc-ui/infinite-recursive-type.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-o" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/infinite-recursive-type" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/rustdoc-ui/infinite-recursive-type/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: internal compiler error[E0391]: cycle detected when computing `Sized` constraints for `E`
  --> /home/joshua/rustc/src/test/rustdoc-ui/infinite-recursive-type.rs:1:1
   |
LL | enum E {
   | ^^^^^^
   |
   = note: ...which again requires computing `Sized` constraints for `E`, completing the cycle
   = note: cycle used when evaluating trait selection obligation `E: std::convert::From<E>`

error: internal compiler error: TyKind::Error constructed but no error reported
   |
   = note: delayed at /home/joshua/rustc/src/librustc_session/session.rs:436:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z unstable-options -C debuginfo=0


------------------------------------------



failures:
    [ui] rustdoc-ui/error-in-impl-trait/async.rs
    [ui] rustdoc-ui/error-in-impl-trait/closure.rs
    [ui] rustdoc-ui/error-in-impl-trait/generic-argument.rs
    [ui] rustdoc-ui/error-in-impl-trait/impl-keyword-closure.rs
    [ui] rustdoc-ui/error-in-impl-trait/impl-keyword.rs
    [ui] rustdoc-ui/error-in-impl-trait/trait-alias-closure.rs
    [ui] rustdoc-ui/error-in-impl-trait/trait-alias.rs
    [ui] rustdoc-ui/infinite-recursive-type.rs

test result: FAILED. 50 passed; 8 failed; 1 ignored; 0 measured; 0 filtered out
```

</details>

**Comment by jyn514** [comment]
> Maybe we could have a reachability pass for rustdoc that's separate from the one for rustc? #73566 (comment)

This seems like the easiest fix to me for the `impl trait` error - to avoid having two passes, we could have a 'ignore impl trait' parameter to the current one.

The hard thing is going to be fixing the cycle on types with infinite size. If any compiler team member has ideas, please let me know.

**Comment by jyn514** [comment]
lol, I can't find the errors in `run-make-fulldeps` because the compiler ICEs while building itself

```
error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:802:9: cannot create local mono-item for DefId(93:23 ~ unicode_security[b1e3]::confusable_detection[0]::char_prototype[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:915:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z macro-backtrace -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=8 -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib
```

**Comment by jyn514** [comment]
UI test failures are fixed so this might actually be feasible. Need to figure out how to fix the cycle error somehow.

**Comment by jyn514** [comment]
This is the same sort of idea as #73566, but for typeck instead of resolve. I don't claim this is anywhere close to a _good_ solution, but hopefully it's enough to unbreak async-std until we find a more principled fix.

On the bright side, unlike everybody_loops, this allows errors in _any_ `impl Trait`, not just `async fn`.

**Comment by Manishearth** [comment]
@yoshuawuyts @dignifiedquire. Stuff should be fine in the next nightly! You can try it out now if you'd like with [RTIM](https://crates.io/crates/rustup-toolchain-install-master), and please let us know if things are still broken.

**Pull request merged**
