### PR TITLE
Remove unnecessary `to_string` and `String::new`

### PR DESCRIPTION
**Pull request by TaKO8Ki**
https://github.com/rust-lang/rust/pull/96468/commits/73fa217bc11fbac76f730223f6766c8e03513b5e changed the type of the `suggestion` argument to `impl ToString`. This patch removes unnecessary `to_string` and `String::new`.

cc: @davidtwco

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by coolreader18** [comment]
I know this is not the place where the change was made, but why `ToString` and not `Into<String>`? I know there's probably some allocation elision that happens so or doesn't really matter but then String would just be called w/ the identity function, not clone

**Pull request merged**
