### PR TITLE
Add some regression tests

### PR DESCRIPTION
**Pull request by jooert**
Add several regression tests and remove some unnecessary FIXMEs.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 4e4e3000f0432311c21d8b1c7880cc0a2dc6bc53

Thanks!

**Comment by jooert** [comment]
The failing code is in vec-fixed-length.rs:
```Rust
if cfg!(target_pointer_width = "64") {
    assert_eq!(size_of::<[u8; (1 << 32)]>(), (1 << 32));
}
```
Perhaps we should replace the `if cfg!(...)` with a `#[cfg(...)]` so that this code isn't compiled (and doesn't error) on 32 bit platforms?

**Comment by jooert** [comment]
Hm, that doesn't work either, because RFC 16 wasn't implemented fully. I have added a quite nasty workaround (introduced a test function whose implementation is different dependent on `target_pointer_width`).

@alexcrichton retry?

**Pull request merged**
