### PR TITLE
Account for incorrect `impl Foo<const N: ty> {}` syntax

### LINKED ISSUE #84946: Incorrect const parameter declaration on an impl block yields an uninformative syntax error
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d0465e600e53454e427193c5065552f7)): 

```rust
struct NInts<const N: usize>([u8; N]);
impl NInts<const N: usize> {}
```

The current output is fairly uninformative:

```
error: expected one of `>`, a const expression, lifetime, or type, found keyword `const`
 --> src/lib.rs:2:11
  |
2 | impl NInts<const N: usize> {}
  |           ^^^^^ expected one of `>`, a const expression, lifetime, or type
```

Ideally the output should look something like this (perhaps with slightly clearer wording :sweat_smile:):

```
error: generic parameter declarations on `impl` blocks must be attached to `impl`
 --> src/lib.rs:2:11
  |
2 | impl NInts<const N: usize> {}
  |            ^^^^^^^^^^^^^^ cannot declare a const parameter here
help: move the generic parameter declaration
  |
2 | impl<const N: usize> NInts<N> {}
  |     ----------------       -

```

### PR DESCRIPTION
**Pull request by estebank**
Fix #84946

### CODE REVIEW

**Comment by varkor** [comment]
Error message looks good to me!

@bors r+

**Comment by varkor** [comment]
cc @estebank: this is waiting on a rebase.

**Comment by JohnCSimon** [comment]
Ping from triage:
@estebank returning to author to address failed test

**Comment by estebank** [comment]
I believe I just fixed the Span issue.

@bors r=varkor rollup=never

**Comment by estebank** [comment]
I'm at a loss at how I'm breaking `rustfmt` here :-/

**Review by nagisa — COMMENTED** [review]
I would like to see more exhaustive tests for areas of code this PR may touch. e.g. AFAICT this PR should affect diagnostics for something like

```
fn banana(a: <T<const N: usize>>::BAR) {}
```

or 

```
fn chaenomeles() {
    path::path::Struct::<const N: usize>()
}
```

via various calls to `parse_path_*`; etc.

**Comment by nagisa** [comment]
Looks good otherwise, though.

**Comment by estebank** [comment]
Added the requested tests, and fixed the necessary rebase moving some code to the more appropriate `diagnostics.rs`, so the happy path is now a bit cleaner as a result.

@bors r=nagisa,varkor

**Comment by estebank** [comment]
Forgot to `fmt`

@bors r=nagisa,varkor

**Pull request merged**
