### PR TITLE
Only show methods that appear in `impl` blocks in the Implementors sections of trait doc pages

### PR DESCRIPTION
**Pull request by ebarnard**
In the "Implementors" and "Implementations on Foreign Types" sections, only show methods that appear in the `impl` block for that type. This has the benefit of
- Reducing the size of the Iterator page, and other large trait documentation pages.
- Retaining documentation on the `impl` blocks and functions in the `impl` blocks.
- Indicating which provided methods are overridden.
- Making the documentation match the structure of the code being documented.
- Being a small change that can be easily backed out if issues arise.

A set of Rust stdlib docs build with this change are [available here](https://ebarnard.github.io/2019-06-03-rust-smaller-trait-implementers-docs/).

The size of the [`Iterator` doc page](https://ebarnard.github.io/2019-06-03-rust-smaller-trait-implementers-docs/std/iter/trait.Iterator.html) is reduced from 14.4MB (latest nightly) to 724kB.

Before:
Screenshot 2019-06-03 at 23 12 17

After:
Screenshot 2019-06-03 at 16 41 27

cc #55900

### CODE REVIEW

**Comment by Stargateur** [comment]
Perfect I think you have found the best solution. Very cleaver. Can't wait to have this in prod.

**Comment by lzutao** [comment]
cc @GuillaumeGomez

**Comment by ebarnard** [comment]
@Stargateur Based on how #55900 has progressed I think there's support for keeping docs on items in `impl` blocks. Only showing functions with docs could be a bit confusing as it would be the only instance of this behaviour.

"Show hidden undocumented items" does take up a lot of space and could be condensed somehow but I would leave that to a follow up PR.

**Comment by Stargateur** [comment]
@ebarnard  You right about the confusion, so I will simply propose we only keep associate item type and let people click on the struct that implement the trait for full detail of implementation. Just some my through of course.

**Comment by GuillaumeGomez** [comment]
I really like this solution like I already said on the issue and the code looks good. We still need other approval from @rust-lang/docs and @rust-lang/rustdoc people.

**Comment by lzutao** [comment]
This is awesome. I had built this PR locally and the rust Iterator doc page
is really reduced like you said.

**Comment by lzutao** [comment]
Ping from triage: Are there any updates here @rust-lang/docs and @rust-lang/rustdoc 
members?

I eagerly to see this land on nightly so people can benefit from this PR.

Hm, I cannot ping those teams: ping @steveklabnik, @rylev, and @ollie27 .

**Comment by GuillaumeGomez** [comment]
I'll ping them for you. :)

cc @rust-lang/docs @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
Considering how much time has passed, I guess we can just move forward... Thanks!

@bors: r+

**Pull request merged**
