### PR TITLE
Actually walk into lifetimes and attrs in `EarlyContextAndPass`

### PR DESCRIPTION
**Pull request by compiler-errors**
Visitors that don't also call `walk_*` are kinda a footgun...

I believe all the other early lint functions walk into their types correctly at this point.

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks. I also feel like actually `walk`ing the lifetime and attr seems like a more “systemic” fix, as is done here. You can r=me after PR CI is green.

**Comment by compiler-errors** [comment]
hahaha

**Comment by jieyouxu** [comment]
💀

**Review by jieyouxu — APPROVED** [review]

**Pull request merged**
