### PR TITLE
Rework reserve assumes for Vec and String

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Code:

```rust
pub fn zzz(v: &mut Vec<u8>, s: &[u8]) {
    v.reserve(s.len());
    v.extend_from_slice(s);
}
```

```rust
pub fn zzz_str(v: &mut String, s: &str) {
    v.reserve(s.len());
    v.push_str(s);
}
```

Before:

```
.section .text.tracing_tracy::zzz,"ax",@progbits
        .globl  tracing_tracy::zzz
        .p2align        4, 0x90
        .type   tracing_tracy::zzz,@function
tracing_tracy::zzz:
        .cfi_startproc
        push r15
        .cfi_def_cfa_offset 16
        push r14
        .cfi_def_cfa_offset 24
        push r12
        .cfi_def_cfa_offset 32
        push rbx
        .cfi_def_cfa_offset 40
        push rax
        .cfi_def_cfa_offset 48
        .cfi_offset rbx, -40
        .cfi_offset r12, -32
        .cfi_offset r14, -24
        .cfi_offset r15, -16
        mov rbx, rdx
        mov r15, rsi
        mov r14, rdi
        mov rax, qword ptr [rdi]
        mov r12, qword ptr [rdi + 16]
        sub rax, r12
        cmp rax, rdx
        jb .LBB20_1
        cmp rax, rbx
        jb .LBB20_3
.LBB20_4:
        mov rdi, qword ptr [r14 + 8]
        add rdi, r12
        mov rsi, r15
        mov rdx, rbx
        call qword ptr [rip + memcpy@GOTPCREL]
        add r12, rbx
        mov qword ptr [r14 + 16], r12
        add rsp, 8
        .cfi_def_cfa_offset 40
        pop rbx
        .cfi_def_cfa_offset 32
        pop r12
        .cfi_def_cfa_offset 24
        pop r14
        .cfi_def_cfa_offset 16
        pop r15
        .cfi_def_cfa_offset 8
        ret
.LBB20_1:
        .cfi_def_cfa_offset 48
        mov rdi, r14
        mov rsi, r12
        mov rdx, rbx
        call alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
        mov rax, qword ptr [r14]
        mov r12, qword ptr [r14 + 16]
        sub rax, r12
        cmp rax, rbx
        jae .LBB20_4
.LBB20_3:
        mov rdi, r14
        mov rsi, r12
        mov rdx, rbx
        call alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
        mov r12, qword ptr [r14 + 16]
        jmp .LBB20_4
```

```
.section .text.tracing_tracy::zzz_str,"ax",@progbits
        .globl  tracing_tracy::zzz_str
        .p2align        4, 0x90
        .type   tracing_tracy::zzz_str,@function
tracing_tracy::zzz_str:
        .cfi_startproc
        push r15
        .cfi_def_cfa_offset 16
        push r14
        .cfi_def_cfa_offset 24
        push r12
        .cfi_def_cfa_offset 32
        push rbx
        .cfi_def_cfa_offset 40
        push rax
        .cfi_def_cfa_offset 48
        .cfi_offset rbx, -40
        .cfi_offset r12, -32
        .cfi_offset r14, -24
        .cfi_offset r15, -16
        mov rbx, rdx
        mov r15, rsi
        mov r14, rdi
        mov rax, qword ptr [rdi]
        mov r12, qword ptr [rdi + 16]
        sub rax, r12
        cmp rax, rdx
        jb .LBB27_1
        cmp rax, rbx
        jb .LBB27_3
.LBB27_4:
        mov rdi, qword ptr [r14 + 8]
        add rdi, r12
        mov rsi, r15
        mov rdx, rbx
        call qword ptr [rip + memcpy@GOTPCREL]
        add r12, rbx
        mov qword ptr [r14 + 16], r12
        add rsp, 8
        .cfi_def_cfa_offset 40
        pop rbx
        .cfi_def_cfa_offset 32
        pop r12
        .cfi_def_cfa_offset 24
        pop r14
        .cfi_def_cfa_offset 16
        pop r15
        .cfi_def_cfa_offset 8
        ret
.LBB27_1:
        .cfi_def_cfa_offset 48
        mov rdi, r14
        mov rsi, r12
        mov rdx, rbx
        call alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
        mov rax, qword ptr [r14]
        mov r12, qword ptr [r14 + 16]
        sub rax, r12
        cmp rax, rbx
        jae .LBB27_4
.LBB27_3:
        mov rdi, r14
        mov rsi, r12
        mov rdx, rbx
        call alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
        mov r12, qword ptr [r14 + 16]
        jmp .LBB27_4
```

After:

```
.section .text.tracing_tracy::zzz_vec,"ax",@progbits
        .globl  tracing_tracy::zzz_vec
        .p2align        4, 0x90
        .type   tracing_tracy::zzz_vec,@function
tracing_tracy::zzz_vec:
        .cfi_startproc
        push r15
        .cfi_def_cfa_offset 16
        push r14
        .cfi_def_cfa_offset 24
        push r12
        .cfi_def_cfa_offset 32
        push rbx
        .cfi_def_cfa_offset 40
        push rax
        .cfi_def_cfa_offset 48
        .cfi_offset rbx, -40
        .cfi_offset r12, -32
        .cfi_offset r14, -24
        .cfi_offset r15, -16
        mov rbx, rdx
        mov r15, rsi
        mov r14, rdi
        mov rax, qword ptr [rdi]
        mov r12, qword ptr [rdi + 16]
        sub rax, r12
        cmp rax, rdx
        jb .LBB32_1
        test rbx, rbx
        js .LBB32_5
.LBB32_3:
        mov rdi, qword ptr [r14 + 8]
        add rdi, r12
        mov rax, rdi
        sub rax, r15
        neg rax
        mov rcx, rdi
        sub rcx, r15
        cmovbe rcx, rax
        cmp rcx, rbx
        jb .LBB32_6
        mov rsi, r15
        mov rdx, rbx
        call qword ptr [rip + memcpy@GOTPCREL]
        add r12, rbx
        mov qword ptr [r14 + 16], r12
        add rsp, 8
        .cfi_def_cfa_offset 40
        pop rbx
        .cfi_def_cfa_offset 32
        pop r12
        .cfi_def_cfa_offset 24
        pop r14
        .cfi_def_cfa_offset 16
        pop r15
        .cfi_def_cfa_offset 8
        ret
.LBB32_1:
        .cfi_def_cfa_offset 48
        mov rdi, r14
        mov rsi, r12
        mov rdx, rbx
        call alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
        mov r12, qword ptr [r14 + 16]
        test rbx, rbx
        jns .LBB32_3
.LBB32_5:
        lea rdi, [rip + .L__unnamed_40]
        mov esi, 71
        call qword ptr [rip + core::panicking::panic_nounwind@GOTPCREL]
.LBB32_6:
        lea rdi, [rip + .L__unnamed_11]
        mov esi, 166
        call qword ptr [rip + core::panicking::panic_nounwind@GOTPCREL]
```

```
.section .text.tracing_tracy::zzz_str,"ax",@progbits
        .globl  tracing_tracy::zzz_str
        .p2align        4, 0x90
        .type   tracing_tracy::zzz_str,@function
tracing_tracy::zzz_str:
        .cfi_startproc
        push r15
        .cfi_def_cfa_offset 16
        push r14
        .cfi_def_cfa_offset 24
        push r12
        .cfi_def_cfa_offset 32
        push rbx
        .cfi_def_cfa_offset 40
        push rax
        .cfi_def_cfa_offset 48
        .cfi_offset rbx, -40
        .cfi_offset r12, -32
        .cfi_offset r14, -24
        .cfi_offset r15, -16
        mov rbx, rdx
        mov r15, rsi
        mov r14, rdi
        mov rax, qword ptr [rdi]
        mov r12, qword ptr [rdi + 16]
        sub rax, r12
        cmp rax, rdx
        jb .LBB33_1
        test rbx, rbx
        js .LBB33_5
.LBB33_3:
        mov rdi, qword ptr [r14 + 8]
        add rdi, r12
        mov rax, rdi
        sub rax, r15
        neg rax
        mov rcx, rdi
        sub rcx, r15
        cmovbe rcx, rax
        cmp rcx, rbx
        jb .LBB33_6
        mov rsi, r15
        mov rdx, rbx
        call qword ptr [rip + memcpy@GOTPCREL]
        add r12, rbx
        mov qword ptr [r14 + 16], r12
        add rsp, 8
        .cfi_def_cfa_offset 40
        pop rbx
        .cfi_def_cfa_offset 32
        pop r12
        .cfi_def_cfa_offset 24
        pop r14
        .cfi_def_cfa_offset 16
        pop r15
        .cfi_def_cfa_offset 8
        ret
.LBB33_1:
        .cfi_def_cfa_offset 48
        mov rdi, r14
        mov rsi, r12
        mov rdx, rbx
        call alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
        mov r12, qword ptr [r14 + 16]
        test rbx, rbx
        jns .LBB33_3
.LBB33_5:
        lea rdi, [rip + .L__unnamed_40]
        mov esi, 71
        call qword ptr [rip + core::panicking::panic_nounwind@GOTPCREL]
.LBB33_6:
        lea rdi, [rip + .L__unnamed_11]
        mov esi, 166
        call qword ptr [rip + core::panicking::panic_nounwind@GOTPCREL]
```

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
The optimization only works with the inlines and assumes in the top function (unless you `inline(always)` the intermediate functions which probably isn't desirable).

**Comment by m-ou-se** [comment]
> unless you `inline(always)` the intermediate functions which probably isn't desirable

The functions are tiny though. Does `#[inline(always)]` produce any negative results?

**Comment by SUPERCILEX** [comment]
Maybe this is actually an LLVM bug? I just tried putting `inline(always)` on every single method in the call stack and it still doesn't optimize out the reserve. The only thing that works is putting an assert_unchecked inside the top-level reserve.

**Comment by JohnCSimon** [comment]
@SUPERCILEX 

ping from triage - can you post your status on this PR? This PR has not received an update in a few months.


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

Or if you're not going to continue, please close it. Thank you!

**Comment by SUPERCILEX** [comment]
Yeah, after all the fiddling I've done I think this is really just an LLVM bug, so I filed: https://github.com/rust-lang/rust/issues/123944.

**Pull request closed without merging**
