### PR TITLE
Replace unwrap calls in examples by expect

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Because no one should use `unwrap`!

r? @steveklabnik

### CODE REVIEW

**Comment by euclio** [comment]
I think it's OK to use `unwrap` for things that trivially cannot fail, like `CString::new()` on a literal, because the `expect` doesn't add any additional information beyond "it failed". I think `expect` should be used in cases where additional explanation of why it cannot fail is needed, like `expect("element was inserted above")` instead of `expect("get() failed")`.

**Comment by GuillaumeGomez** [comment]
@euclio: Beyond than just use `expect` when needed, we should ensure that people use `unwrap` as little as possible.

**Comment by euclio** [comment]
Right, I understand that we should be discouraging `unwrap`. But, I think that `unwrap` has its uses, and a blanket ban in `std` documentation seems too heavy-handed to me.

The _reason_ we want to discourage `unwrap` is twofold. First, you don't want to `unwrap` when you should be propagating or handling the error instead. `std` documentation already does this throughout, so it's not relevant to this PR. Second, `unwrap` doesn't provide any information about why we thought it was OK to `unwrap` in the case of failure. That's why `expect` exists: so we can display that reasoning. Using `expect` with a message like `expect("func() failed")` isn't much better than `unwrap`, because the only information it provides is that the method failed, which is what `unwrap` gives us. Instead, `expect` should contain the reasoning behind the `expect`, like I said above.

My second point is that if you're writing `expect` messages like that, then an expression like `CString::new("foo").expect("0 byte found in literal")` is redundant: obviously a 0-byte does not occur in the literal. At that point, the `expect` is just line noise, and I'd prefer `unwrap`.

**Comment by steveklabnik** [comment]
Yup, agreed with Andy here.

**Comment by TimNN** [comment]
Ping from triage, @GuillaumeGomez: what's the status of this?

**Comment by GuillaumeGomez** [comment]
Need to update.

**Comment by pietroalbini** [comment]
Ping from triage @GuillaumeGomez! It's been a while since we heard from you, will you have time to work on this again?

**Comment by GuillaumeGomez** [comment]
Yep, don't know when but yep.

**Comment by pietroalbini** [comment]
Frendly weekly ping from triage @GuillaumeGomez! `:)`

**Comment by GuillaumeGomez** [comment]
I'll update it some day! :D

**Comment by Aaronepower** [comment]
Triage: @GuillaumeGomez Have you been able to get back to this?

**Comment by GuillaumeGomez** [comment]
Soon, it'll take a bit of time.

**Comment by GuillaumeGomez** [comment]
So, made few improvements on some wordings. However:

> Right, I understand that we should be discouraging unwrap. But, I think that unwrap has its uses, and a blanket ban in std documentation seems too heavy-handed to me.

I don't agree with that statement for example: `expect` does exactly the same but in addition provides a message which is *information*. The more information the better, even more on a code written in a language which intends to have a reputation of never crashing (wether it's true or not).

> Using expect with a message like expect("func() failed") isn't much better than unwrap, because the only information it provides is that the method failed, which is what unwrap gives us

Yes but it is more clear (and you can add additional information).

Again, this is all about giving good habits to users. Even a message like "fuck it" would be super useful to find where the error comes from (unless you have a few of them of course).

In any case, I tried to improve messages a bit but I don't know how I could make them better at this point so any suggestion is very welcome if you think they could be improved. :)

**Comment by euclio** [comment]
> Again, this is all about giving good habits to users. Even a message like
"fuck it" would be super useful to find where the error comes from (unless
you have a few of them of course).

This is what the stack trace provides, no?

**Comment by GuillaumeGomez** [comment]
> This is what the stack trace provides, no?

Yes and no. Stack trace only indicates functions most of the time (it's already a good start but still lacking).

> Also, I would argue that using `expect` with a uninformative message is actually a bad habit.

I think this is more a question of opinion in here. I want an error message to be informative whereas I want a panic message to be easy to be grepped so I can fix it because a panic should never happen on the opposite of an error message.

**Comment by pietroalbini** [comment]
Ping from triage @GuillaumeGomez! It's been a while since we heard from you, will you have time to work on this again?

**Comment by GuillaumeGomez** [comment]
Debate is still going on. :)

**Comment by TimNN** [comment]
Ping from triage @GuillaumeGomez  / @steveklabnik. What is the status of this PR?

Is this blocked on some external issue?
Is this blocked on discussion in this PR?
Would it maybe help to split this PR into multiple smaller ones?
Should we nominate this for some team to discuss to resolve the discussion using "realtime communication" (rather than via comments every now and then)?

**Comment by GuillaumeGomez** [comment]
I don't know actually. The debate is "should expect sentences be more useful than easy to grep" basically?

**Comment by steveklabnik** [comment]
>  Would it maybe help to split this PR into multiple smaller ones?

I think so.  From the first comment:

> I think it's OK to use unwrap for things that trivially cannot fail, like CString::new() on a literal, because the expect doesn't add any additional information beyond "it failed". I think expect should be used in cases where additional explanation of why it cannot fail is needed, like expect("element was inserted above") instead of expect("get() failed").

If this were only the ones where things *can* fail, we could merge, it's the others that are controversial.

**Comment by GuillaumeGomez** [comment]
@steveklabnik Ok, I'll make a first PR for the mergeable one and open another one with the rest.

**Comment by TimNN** [comment]
Ping from triage! I'm marking this as "blocked" on the individual, smaller PRs.

**Comment by Dylan-DPC** [comment]
Ping from triage @GuillaumeGomez what's the update on this?

**Comment by GuillaumeGomez** [comment]
This PR is a bit behind. I need to cut it into small pieces to be merged separately.

**Comment by steveklabnik** [comment]
@GuillaumeGomez it's been a few months; since it's gonna get cut into pieces anyway, I'm going to close this to clear out my queue. thanks.

**Comment by GuillaumeGomez** [comment]
Sure, completely forgot about it!

**Pull request closed without merging**
