### PR TITLE
std::thread: follow-up #123913 removing unsafe on success for glibc.

### PR DESCRIPTION
**Pull request by devnexen**
follow up #123913

### CODE REVIEW

**Comment by Nilstrieb** [comment]
hm, this is needed for `unsafe_op_in_unsafe_fn`, right? why does this not fail to compile :thinking:, CI builders should be building this

**Comment by RalfJung** [comment]
> CI builders should be building this

Should they? That lint is denied in `alloc/src/lib.rs`, but in std it's only denied in some modules and `sys::pal` is not one of them.

**Comment by RalfJung** [comment]
> follow up #123913

That's a follup. Which of the PRs in there do you mean?


I don't think we should do this. Instead we should set `deny(unsafe_op_in_unsafe_fn)` in more and more places.

**Comment by devnexen** [comment]
I was not aware of this new lint, makes sense now.

**Comment by RalfJung** [comment]
Here's the issue for using this lint in std: https://github.com/rust-lang/rust/issues/73904.

**Pull request closed without merging**
