### PR TITLE
Emscripten: link with -sWASM_BIGINT

### PR DESCRIPTION
**Pull request by hoodmane**
When linking an executable without dynamic linking, this is a pure improvement. It significantly reduces code size and avoids a lot of buggy behaviors. It is supported in all browsers for many years and in all maintained versions of Node.

It does change the ABI, so people who are dynamically linking with a library or executable that uses the old ABI may need to turn it off. It can be disabled if needed by passing `-Clink-arg -sWASM_BIGINT=0` to `rustc`. But few people will want to turn it off.

Note this includes a libc bump to 0.2.162!

### CODE REVIEW

**Comment by hoodmane** [comment]
@sbc100 have you thought about making `-sWASM_BIGINT` the default in general? I guess the fact that it requires Safari 15 is the most onerous requirement but Safari 15 came out on September 20, 2021 a bit over 3 years ago. All versions of node that don't support it are EOL and the others browsers have supported it since 2019.

**Comment by juntyr** [comment]
If #131582 lands first, this PR should probably update the enabled WASM features section

**Comment by sbc100** [comment]
> > @sbc100 have you thought about making `-sWASM_BIGINT` the default in general? I guess the fact that it requires Safari 15 is the most onerous requirement but Safari 15 came out on September 20, 2021 a bit over 3 years ago. All versions of node that don't support it are EOL and the others browsers have supported it since 2019.
> 
> Yes, `-sWASM_BIGINT` should be the default pretty soon. And yes, that involves bumping the default min safari version, which we didn't want to do last time I looked into it. I think the time might be right. There are couple of other blockers for that too, such as wasm2js support.

See https://github.com/emscripten-core/emscripten/pull/19156 and

**Comment by alexcrichton** [comment]
I'm not an expert on the Emscripten side of things so in terms of "is this the right time?" I'd defer to the folks who know more, so sounds like this is a green-light there and good to go.

One question I would have though is that you mention that this changes the ABI. Does that mean that this would impact C/C++/Rust code being linked together (statically, not dynamically)? For example does the `cc` crate need to update to pass this flag by default as well to have Rust/C/C++ all interoperate after this PR lands?

**Comment by hoodmane** [comment]
It's only a link flag so no action is needed for static libraries. Any dynamic libraries also need to be linked with this flag.

**Comment by alexcrichton** [comment]
Ok great! If this is going to be the default in Emscripten soon though should rustc follow Emscripten's defaults rather than having its own configuration? If Emscripten switches by default then users would only "just" need to upgrade their Emscripten toolchain, right?

If we do go the rustc route though mind modifying the [target definition](https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/targets/wasm32_unknown_emscripten.rs) instead of the linker definition?

**Comment by hoodmane** [comment]
This flag does make a significant in the quality of the linked executable so people should be using it unless they have a reason not to. But we could indeed wait and stay with the Emscripten defaults if they are switching it soon.

**Comment by hoodmane** [comment]
Now I remember Rust dynamic libraries linked without `-sWASM_BIGINT` don't work at all and the recommended solution was to always link with `-sWASM_BIGINT`. So Rust is particularly seriously affected by this.
https://github.com/emscripten-core/emscripten/pull/16693

On this basis, I'd say we should move forward with merging this.

**Comment by workingjubilee** [comment]
@hoodmane Can you confirm whether we would want updates to the `cc` crate as well?

Obviously not when it becomes the default, so I think we're fine just merging this now, I just want a yes/no: is this conceivably breaking a build script that uses `cc` somewhere?

**Comment by alexcrichton** [comment]
> On this basis, I'd say we should move forward with merging this.

Sounds good to me! r=me assuming the answer to @workingjubilee's question is "no breakage" (which give my understanding is the answer, but would be good for @hoodmane you to confirm)

**Comment by hoodmane** [comment]
Yeah. `cc-rs` doesn't know how to link emscripten shared libraries and for static libraries no change is needed. We should probably teach it out to link emscripten shared libraries eventually and then we'll need to add this flag if we want it to work.

**Comment by hoodmane** [comment]
Actually, linking with `-lc -sWASM_BIGINT` also seems to be broken https://github.com/emscripten-core/emscripten/issues/22758. Emscripten really doesn't like it when you pass `-lc` @sbc100. It seems like that bug is a blocker.

**Comment by workingjubilee** [comment]
Cool, let's... Oh, we can't actually merge this? Damn.

**Comment by sbc100** [comment]
> Actually, linking with `-lc -sWASM_BIGINT` also seems to be broken [emscripten-core/emscripten#22758](https://github.com/emscripten-core/emscripten/issues/22758). Emscripten really doesn't like it when you pass `-lc` @sbc100. It seems like that bug is a blocker.

Yes, the explicit `-lc` is likely the issue.  I guess it kind of works but doesn't always select the correct variant of libc based on your settings perhaps?  If you can remove the `-lc` that that would a simple fix on the rust end.

**Comment by hoodmane** [comment]
Okay I opened an Emscripten PR to hopefully this: https://github.com/emscripten-core/emscripten/pull/22765

In the meantime, can we adjust the `EmLinker` to specifically drop `-lc`? I tried to make this change a few years ago, but it was rejected as being weird and hacky and generally concerning. Instead, we were passing `-Zlink-native-libraries=no` but that creates a different set of problems when there are packages other than libc which actually do need to be linked.
https://github.com/rust-lang/rust/pull/98303

I think if we insert this with a comment saying that it's a hack around https://github.com/emscripten-core/emscripten/issues/22758 and we can remove it when we drop support for Emscripten 3.1.69 it should be okay?
cc @petrochenkov who rejected that change before.

**Comment by hoodmane** [comment]
Also opened a PR to work around it on Rust's side:
https://github.com/rust-lang/rust/pull/131885

**Comment by hoodmane** [comment]
Cherry picking https://github.com/rust-lang/rust/pull/132720 on top of this, I get:
```
$ ./x.py test --target wasm32-unknown-emscripten ./tests/ui/
...
test result: FAILED. 17199 passed; 4 failed; 735 ignored; 0 measured; 0 filtered out; finished in 517.19s
```
so one fewer ui test failure than on the main branch. So @alexcrichton @workingjubilee if the bump to libc 0.2.162 is okay then I think this can be merged.

**Comment by hoodmane** [comment]
@alexcrichton @workingjubilee ping. Can we merge this?

**Comment by workingjubilee** [comment]
Yeah, I think we're good here.

@bors r+ rollup

**Comment by hoodmane** [comment]
Thanks @workingjubilee and @alexcrichton!

**Pull request merged**
