### PR TITLE
Type-annotate and simplify documentation of Option::unwrap_or_default

### PR DESCRIPTION
**Pull request by ghost**
Part of #100054

### CODE REVIEW

**Comment by joshtriplett** [comment]
This is certainly an improvement, and I'm going to go ahead and merge it as such:

@bors r+ rollup

However, this also doesn't seem like a very good documentation example, given that `Result::unwrap_or_default` exists and would be a better choice in this case.

Perhaps a better example would use an array and `slice::get`, or something like `Iterator::min`?

**Comment by GuillaumeGomez** [comment]
Wouldn't it be better instead to not need type annotation? For example:

```rust
let x: Option<u32> = None;
let y: Option<u32> = Some(12);

assert_eq!(x.unwrap_or_default(), 0);
assert_eq!(12.unwrap_or_default(), 12);
```

I find the usage of `Result` unneeded and it adds complexity for no benefit.

**Comment by gimbles** [comment]
We can always add a better example later on =)

**Comment by GuillaumeGomez** [comment]
Well, we could have done it correctly directly but it doesn't matter much. I'll just send a PR once this one is merged.

**Comment by gimbles** [comment]
I mean, I can probably extend this PR, right now :y

**Comment by GuillaumeGomez** [comment]
It's about to get merged so better not. :)

**Comment by GuillaumeGomez** [comment]
@gimbles Do you want to send a PR with the code I suggested instead?

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/rust/pull/102283 as a follow-up.

**Pull request merged**
