### PR TITLE
attempt to recover perf by removing `exports_all_green`

### PR DESCRIPTION
**Pull request by pnkfelix**
attempt to recover perf by removing `exports_all_green` flag.

cc #71248 

(My hypothesis is that my use of this flag was an overly conservative generalization of PR #67020.)

### CODE REVIEW

**Comment by pnkfelix** [comment]
we should probably at least *consider* rolling this in with the current beta, if we can, considering it is a high priority follow-up to PR #71131

On the other hand, given that we were willing to let PR #71131 land without the performance issue addressed, it would also be entirely fine if we let this PR ride the trains.

still, marking as beta-nominated to make it clear that that this is a question that we should try to resolve across the team, if we can do so quickly...

cc @rust-lang/compiler

**Comment by nagisa** [comment]
err, @bors r-, but r=me

**Comment by MaloJaffre** [comment]
Perf results have landed, but there was no notification from the bot.

**Comment by eddyb** [comment]
Assuming I've done this right, this is the outer/inner range breakdown:
* ["outer", i.e. before the regression to after the fix (this PR)](https://perf.rust-lang.org/compare.html?start=868b51be6f29d5b43d37c5d65bac1482d3a50ad8&end=afdbd8d1f31ef963fbfe54dc8a987f5bee3f1a29)
* ["inner", i.e. after the regression to before the fix (this PR)](https://perf.rust-lang.org/compare.html?start=318726b301db2a0718d05f166d3d6c578273189c&end=ce93331e2cf21ac4b72a53854b105955919114e7)

The difference between those two *should* be the remaining regressions, and they are:
* `2.9%` on `script-servo-opt` "patched incremental: debugging println in dependency"
* `1.2%` on `issue-46449-opt` "patched incremental: u32 3072"

**Comment by pnkfelix** [comment]
> @bors r+, but it would perhaps be great if we could explain _why_ it is fine to remove this in a way that isn’t just a hunch.

Yeah, I had some idle moments over the past few days wondering if this was truly justifiable, and if so, what the justification is.

With the code prior to this PR, the LTO optimization of a module is sensitive to (a.) what collection of modules it imports from (just as a set of names), (b.) what collection of modules it exports to (again, just as a set of names), (c.) whether the content of any of its imports has changed, and (d.) whether the content of any of the modules it exports to has changed.

With this PR in place, we keep conditions (a.), (b.) and (c.); only (d.) is removed.

We have lots of attached discussion justifying why we needed to add (a.) and (b.).

Condition (c.) has been there since the beginning, I think. The justification for (c.) is that LLVM is allowed to use the content of the modules we import from in the LTO optimization of the current module. (Otherwise there wouldn't be much point in doing link-time optimization, right?)

So the question is, *can* LLVM do optimizations based on the content of the modules that the current module exports to?
 * (What kind of optimization am I imagining here? One example would be if the current module is defining a function `foo` that takes a boolean `flag` as one of its argument, and then LLVM analyzes all of the client modules and determines that every one of them passes `false` for the value of `flag`; that knowledge would enable treating `flag` as a constant during LTO.)

Do I expect LLVM might be using this kind of optimization? I wasn't sure, so I decided to go check the docs. The docs then point to the [LLVM blog post on ThinLTO](http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html), where it *literally* says:

> any particular ThinLTO backend must be redone if and only if:
>
> 1. The corresponding (primary) module’s bitcode changed 
> 2. The list of imports into or exports from the module changed 
> 3. The bitcode for any module being imported from has changed 
> 4. Any global analysis result affecting either the primary module or anything it imports has changed. 

Note how items 2 and 3 there are written: item 2 corresponds exactly to conditions (a.) and (b.). Item 3 corresponds to condition (c.). And they do *not* say anything about changes to modules that we export *to*; that is, I think that serves as a promise from LLVM that we can drop condition (d.)

**Comment by pnkfelix** [comment]
I'll add a commit with a comment that restates the above, perhaps a bit more tersely.

**Comment by pnkfelix** [comment]
> Assuming I've done this right, this is the outer/inner range breakdown:
> 
>     * ["outer", i.e. before the regression to after the fix (this PR)](https://perf.rust-lang.org/compare.html?start=868b51be6f29d5b43d37c5d65bac1482d3a50ad8&end=afdbd8d1f31ef963fbfe54dc8a987f5bee3f1a29)
> 
>     * ["inner", i.e. after the regression to before the fix (this PR)](https://perf.rust-lang.org/compare.html?start=318726b301db2a0718d05f166d3d6c578273189c&end=ce93331e2cf21ac4b72a53854b105955919114e7)
> 
> 
> The difference between those two _should_ be the remaining regressions, and they are:
> 
>     * `2.9%` on `script-servo-opt` "patched incremental: debugging println in dependency"
> 
>     * `1.2%` on `issue-46449-opt` "patched incremental: u32 3072"

Thanks @eddyb ! I'll try to look into these cases next!

(But I think its safe to say that *these* regressions we are probably willing to stomach in exchange for correctness...)

**Comment by pnkfelix** [comment]
after discussion with @Mark-Simulacrum , I'm going to insta-beta-accept this (that is, I'm bypassing the beta-nomination process).

I'm also marking this I-nominated so that we remember to discuss this at this week's Thursday meeting, so that if someone wants to object (either to the PR itself or to the process I followed, we will give the opportunity to do so there.

(Or they can just post comments here if they object too...)

**Comment by Mark-Simulacrum** [comment]
Note that by that meeting it is highly likely we'll have already released this into stable -- so @rust-lang/compiler -- please chime in before then if you object to this getting released. (We can rebuild stable as late as ~Wednesday, most likely, though obviously the earlier the better).

**Pull request merged**
