### PR TITLE
Remove a FIXME in core/hash tests

### PR DESCRIPTION
**Pull request by wesleywiser**
Removes a FIXME

### CODE REVIEW

**Comment by BurntSushi** [comment]
@wesleywiser Thanks!

**Comment by wesleywiser** [comment]
> Deploying using S3 provider
Uploading artifact "e3f3825e13a2a35acf239b21ea6c4b7947e1a860/rust-analysis-nightly-i686-pc-windows-gnu.tar.gz" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/e3f3825e13a2a35acf239b21ea6c4b7947e1a860/rust-analysis-nightly-i686-pc-windows-gnu.tar.gz"
Uploading artifact "e3f3825e13a2a35acf239b21ea6c4b7947e1a860/rust-docs-nightly-i686-pc-windows-gnu.tar.gz" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/e3f3825e13a2a35acf239b21ea6c4b7947e1a860/rust-docs-nightly-i686-pc-windows-gnu.tar.gz"
Uploading artifact "e3f3825e13a2a35acf239b21ea6c4b7947e1a860/rust-mingw-nightly-i686-pc-windows-gnu.tar.gz" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/e3f3825e13a2a35acf239b21ea6c4b7947e1a860/rust-mingw-nightly-i686-pc-windows-gnu.tar.gz"
A WebException with status ReceiveFailure was thrown.

Seems unrelated IMO

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault https://github.com/rust-lang/rust/issues/38878

**Pull request merged**
