### PR TITLE
Encode more precise scoping rules for function params

### LINKED ISSUE #23338: RefCell::borrow does not pass borrow-check without a seemingly no-op let binding
When upgrading Rust in Servo, many usages of `RefCell::borrow` that were previously fine now cause borrow-check errors [like this](https://github.com/servo/servo/commit/7fbd43f0ad0ceab377403d7416934ee32feabc88?diff=unified#diff-016eef304e69674de212b7fbcd9330fdL678):
```
components/script/dom/xmlhttprequest.rs:678:9: 678:13 error: `self` does not live long enough
components/script/dom/xmlhttprequest.rs:678         self.status_text.borrow().clone()
                                                                               ^~~~
components/script/dom/xmlhttprequest.rs:677:39: 679:6 note: reference must be valid for the destruction scope surrounding block at 677:38...
components/script/dom/xmlhttprequest.rs:677     fn StatusText(self) -> ByteString {
components/script/dom/xmlhttprequest.rs:678         self.status_text.borrow().clone()
components/script/dom/xmlhttprequest.rs:679     }
components/script/dom/xmlhttprequest.rs:677:39: 679:6 note: ...but borrowed value is only valid for the block at 677:38
components/script/dom/xmlhttprequest.rs:677     fn StatusText(self) -> ByteString {
components/script/dom/xmlhttprequest.rs:678         self.status_text.borrow().clone()
components/script/dom/xmlhttprequest.rs:679     }
```

This error message makes no sense to me, the two blocks it talks about are the same.

This can be worked around by binding the result of `.borrow()` with `let` before using it, enough though such a change looks like a no-op:

```diff
 fn StatusText(self) -> ByteString {
-     self.status_text.borrow().clone()
+     let status_text = self.status_text.borrow();
+     status_text.clone()
}

### PR DESCRIPTION
**Pull request by pnkfelix**
Encode more precise scoping rules for function params

Function params outlive everything in the body (incl temporaries).  Thus if we assign them their own `CodeExtent`, the region inference can properly show that it is sound to have temporaries with destructors that reference the parameters (because such temporaries will be dropped before the parameters are dropped).

Fix #23338

### CODE REVIEW

**Comment by pnkfelix** [comment]
r? @nikomatsakis 

(note I have not yet done a full `make check` locally, so those test cases have not been fully vetted yet against our infrastructure.)

**Comment by pnkfelix** [comment]
make tidy fails due to the `TODO` that is sitting there.

and one of the tests got caught on a pretty printer bug, so I put in a workaround for that.

But once I fix the `TODO` (after I first try out what it suggests), this should be ready for landing (assuming it passes muster according to human review).

**Comment by pnkfelix** [comment]
Okay everything checks out; I've rebased and this should be ready to land whenever.

**Comment by nikomatsakis** [comment]
r+ -- though I'm curious about the `record_superlifetime` thing

**Pull request merged**
