### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Nadrieril**
Successful merges:

 - #116090 (Implement strict integer operations that panic on overflow)
 - #118811 (Use `bool` instead of `PartiolOrd` as return value of the comparison closure in `{slice,Iteraotr}::is_sorted_by`)
 - #119081 (Add Ipv6Addr::is_ipv4_mapped)
 - #119461 (Use an interpreter in MIR jump threading)
 - #119996 (Move OS String implementation into `sys`)
 - #120015 (coverage: Format all coverage tests with `rustfmt`)
 - #120027 (pattern_analysis: Remove `Ty: Copy` bound)
 - #120084 (fix(rust-analyzer): use new pkgid spec to compare)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=116090,118811,119081,119461,119996,120015,120027,120084)

### CODE REVIEW

**Comment by Kobzol** [comment]
Hmm, no idea what PR could cause this. Let's go one by one (unless someone has an idea).

@rust-timer build 0f778c8fc564b029403f60a61684e92aa76fc85b

**Comment by Kobzol** [comment]
@rust-timer build e96cc852ee1dfa4a7c7a27effd45b4b18d6f5d06

**Comment by Nadrieril** [comment]
Looking through them I'd guess it's https://github.com/rust-lang/rust/pull/119461 because it affects MIR opts. I probably shouldn't have rolled it up. Mayyybe https://github.com/rust-lang/rust/pull/118811 or https://github.com/rust-lang/rust/pull/120027. Can't imagine it's any of the others.

**Comment by Nadrieril** [comment]
Doesn't explain everything. https://github.com/rust-lang/rust/pull/120027 would be a likely culprit but we checked it for perf before the r+. Let's see https://github.com/rust-lang/rust/pull/118811.

@rust-timer build 564a5fbaea9377acaf35379a973da9110a97460c

**Comment by Nadrieril** [comment]
The rest of the regressions are on documentation, could it be https://github.com/rust-lang/rust/pull/116090?

@rust-timer build 363814c8317ee2dc48738276878e86a459eacd01

**Comment by Nadrieril** [comment]
Yup, that's it. In summary, the overall [rollup perf impact](https://perf.rust-lang.org/compare.html?start=867d39cdf625e4db4b381faff993346582e598b4&end=cb25c5bc3d526a8fb931314cb3a7849115134b04&stat=instructions:u) is explained by:
- https://github.com/rust-lang/rust/pull/119461 does [this](https://perf.rust-lang.org/compare.html?start=867d39cdf625e4db4b381faff993346582e598b4&end=e96cc852ee1dfa4a7c7a27effd45b4b18d6f5d06&stat=instructions:u) i.e. regresses deep-vector (secondary bench) by ~1.5%
- https://github.com/rust-lang/rust/pull/118811 does [this](https://perf.rust-lang.org/compare.html?start=867d39cdf625e4db4b381faff993346582e598b4&end=564a5fbaea9377acaf35379a973da9110a97460c&stat=instructions:u) i.e. regresses deep-vector (secondary bench) by ~1.8%
- https://github.com/rust-lang/rust/pull/116090 does [this](https://perf.rust-lang.org/compare.html?start=867d39cdf625e4db4b381faff993346582e598b4&end=363814c8317ee2dc48738276878e86a459eacd01&stat=instructions:u) i.e. regresses documentation time of a bunch of crates by a small amount.

That was my first rollup, it seems I wasn't careful enough about the `rollup=maybe` cases :')

**Comment by Kobzol** [comment]
@Nadrieril Thank you for the detailed analysis!

**Comment by Kobzol** [comment]
The two regressions on `deep-vector` seem to be noise, as the benchmark has been oscillating recently. The `doc` regressions are real, but they are simply caused by adding a bunch of new methods to the standard library.

@rustbot label: +perf-regression-triaged

**Pull request merged**
