### PR TITLE
Update RLS

### PR DESCRIPTION
**Pull request by Bobo1239**
Includes https://github.com/rust-lang-nursery/rls/pull/793 which fixes https://github.com/rust-lang-nursery/rls/issues/803.

### CODE REVIEW

**Comment by Bobo1239** [comment]
Rebased.

**Comment by nrc** [comment]
ping @Bobo1239 bors thinks this needs rebasing (though GitHub disagrees, which is weird)

**Comment by Bobo1239** [comment]
Done. (also updated to latest commit)

**Pull request merged**
