### PR TITLE
Give `ast::ExprKind::Paren` no-op expressions the same ids as their children.

### PR DESCRIPTION
**Pull request by jseyfried**
Having `ast::ExprKind::Paren` expressions share ids with their children
- reduces the number of unused `NodeId`s in the hir map and
- guarantees that `tcx.map.expect_expr(ast_expr.id)` is the hir corresponding to `ast_expr`.

This fixes the bug from #34327, which was introduced in #33296 when I assumed the above guarantee.

r? @nrc

### CODE REVIEW

**Comment by arielb1** [comment]
> guarantees that `tcx.map.expect_expr(ast_expr.id)` is the hir corresponding to `ast_expr`.

This does not sound like a guarantee we want to maintain.

**Comment by jseyfried** [comment]
@arielb1 
Hmm, do you have something in mind that would break that guarantee?
That is, what ast expression besides `ast::ExprKind::Paren` would not correspond to a unique hir node?

**Comment by arielb1** [comment]
@jseyfried 

We are planning to do a major refactoring of `ExprPath` and `PatPath` - there may be problems for patterns.

**Comment by jseyfried** [comment]
@arielb1 ok, I believe `save_analysis` only relies on the guarantee for expressions. If we do break the guarantee, it should be straightforward to fix the fallout in `save_analysis`.

**Pull request merged**
