### PR TITLE
rustdoc: Render new `self` syntax in `use`

### LINKED ISSUE #21442: Rustdoc still uses the old `mod` syntax in `use`
For example, [`std::prelude::v1`](http://doc.rust-lang.org/std/prelude/v1/) shows an import as `use option::Option::{mod, None, Some};`, when in fact it is using the newer `self` syntax in the code.

### PR DESCRIPTION
**Pull request by tomjakubowski**
Fix #21442

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could a new test be added for this as well?

**Comment by tomjakubowski** [comment]
Added a test (:heart: `htmldocck.py`).

**Comment by alexcrichton** [comment]
Looks like there's a tidy error :(

Thanks for writing a test though!

**Comment by tomjakubowski** [comment]
Fixed the tidy error I believe.

**Pull request merged**
