### PR TITLE
feat: allow direct calls after reverse

### PR DESCRIPTION
**Pull request by hirehamir**

### CODE REVIEW

**Comment by hamirmahal** [comment]
That makes sense. I appreciate the rationale.

**Comment by hamirmahal** [comment]
Should I go ahead and close this?

**Comment by workingjubilee** [comment]
Unless you have an alternative implementation in mind that takes into account all of the above factors. :^)

**Comment by hamirmahal** [comment]
Ha, I do not, at the moment.

**Comment by slanterns** [comment]
Also I think mutate the original slice by argument and return the reversed slice at the same time is confusing from an api view.

**Comment by workingjubilee** [comment]
While perhaps a odd-looking, it accepts the slice as `&mut [T]` and returns the slice as `&mut [T]` so it would be perfectly safe. I consider this change to be desirable, just impossible.

**Comment by joboet** [comment]
As explained by Jubilee, this change makes sense, but is breaking.

**Pull request closed without merging**
