### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by JohnTitor**
Successful merges:

 - #71633 (Impl Error for Infallible)
 - #71843 (Tweak and stabilize AtomicN::fetch_update)
 - #72288 (Stabilization of weak-into-raw)
 - #72324 (Stabilize AtomicN::fetch_min and AtomicN::fetch_max)
 - #72452 (Clarified the documentation for Formatter::precision)
 - #72495 (Improve E0601 explanation)
 - #72534 (Improve missing `@` in slice binding pattern diagnostics)
 - #72547 (Added a codegen test for a recent optimization for overflow-checks=on)
 - #72711 (remove redundant `mk_const`)
 - #72713 (Whitelist #[allow_internal_unstable])
 - #72720 (Clarify the documentation of `take`)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
Hmm, that's a shame toolstate doesn't give you the errors in case of a build failure

**Comment by JohnTitor** [comment]
@LeSeulArtichaut toolstate doesn't block PRs now unless it's regressed (see #69624) but Actions uses dummy toolstate repo so it fails unfortunately. Anyways actions isn't used as a gate and we could just ignore it.

**Comment by LeSeulArtichaut** [comment]
Oh, alright I thought that would make the PR fail 😄

**Pull request merged**
