### PR TITLE
Implement str::split_at (RFC 1123)

### PR DESCRIPTION
**Pull request by bluss**
Implement RFC rust-lang/rfcs#1123

Add str method str::split_at(mid: usize) -> (&str, &str).

Also a minor cleanup in the collections::str module. Remove redundant slicing of self.

### CODE REVIEW

**Comment by bluss** [comment]
Please see the RFC: rust-lang/rfcs#1123. It is not yet accepted.

Tacked on two changes that I found when I visited the file. Removing redundant slicing saves us nothing (I hope) but codegen and optimization time.

Inlining as_bytes() is just something I saw in by coincdence. Inling it should help optimizations where they're as most needed. A lot more str methods are marked inline in libcore, but I went for those that should be uncontroversial and important for optimizations.

**Comment by alexcrichton** [comment]
Looks good to me, thanks @bluss!

**Comment by bluss** [comment]
Rebased, tossed the inlining commit.

**Comment by alexcrichton** [comment]
Turning this into the tracking issue for https://github.com/rust-lang/rfcs/pull/1123. Thanks again @bluss!

@bors: r+ 37bbcc3

**Comment by bluss** [comment]
:sunny:

**Comment by bluss** [comment]
Fixed the doc example, sorry about that.

**Comment by bluss** [comment]
@bors: r=alexcrichton

Let's give this another go

**Pull request merged**
