### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #83507 (Implement RFC 2951: Native link modifiers)
 - #83553 (Update `ptr` docs with regards to `ptr::addr_of!`)
 - #84183 (Update RELEASES.md for 1.52.0)
 - #84442 (Unify rustc and rustdoc parsing of `cfg()`)
 - #84468 (Fix#84467 linker_args with --target=sparcv9-sun-solaris)
 - #84712 (Simplify chdir implementation and minimize unsafe block)
 - #84755 (Allow using `core::` in intra-doc links within core itself)
 - #84797 (Report coverage `0` of dead blocks)
 - #84808 (Account for unsatisfied bounds in E0599)
 - #84843 (use else if in std library )
 - #84851 (:arrow_up: rust-analyzer)

Failed merges:

 - #84803 (Reduce duplication in `impl_dep_tracking_hash` macros)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=83507,83553,84183,84442,84468,84712,84755,84797,84808,84843,84851)

### CODE REVIEW

**Comment by RalfJung** [comment]
Again the musl-g++ error
```
failed to execute command: "musl-g++" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m32" "-march=i686" "-Wl,-melf_i386" "-static" "-Wa,-mrelax-relocations=no" "-print-file-name=libstdc++.a"
error: No such file or directory (os error 2)
```
Maybe it's https://github.com/rust-lang/rust/pull/83507 ?

**Comment by RalfJung** [comment]
Intersection with https://github.com/rust-lang/rust/pull/84899, https://github.com/rust-lang/rust/pull/84924 and https://github.com/rust-lang/rust/pull/84932:
* #83553 (Update ptr docs with regards to ptr::addr_of!)
* #84468 (Fix#84467 linker_args with --target=sparcv9-sun-solaris)
* #84797 (Report coverage 0 of dead blocks)
* #84808 (Account for unsatisfied bounds in E0599)
* #84843 (use else if in std library )

**Comment by RalfJung** [comment]
The error seems to happen within 5min; https://github.com/rust-lang/rust/pull/84948 took almost 30min to fail... so if we exclude the PRs that were in that rollup, the remaining candidates are
* #84468 (Fix#84467 linker_args with --target=sparcv9-sun-solaris)
* #84797 (Report coverage 0 of dead blocks)

**Comment by klensy** [comment]
Maybe #84797 ? Other ones looks unrelated.

**Comment by hyd-dev** [comment]
The error seems coming from here: https://github.com/rust-lang/rust/blob/24acc388da2cdbe1ec79b6933402941b6fffb26b/src/bootstrap/compile.rs#L687

**Pull request closed without merging**
