### PR TITLE
Update CSS for future rustdoc merge

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc #33382

r? @steveklabnik 
cc @Manishearth 
cc @birkenfeld

### CODE REVIEW

**Comment by birkenfeld** [comment]
Thanks! One more issue I've noticed is that the "in-band"/"out-of-band" split is 60%/40%, which wastes a lot of space for long "impl X<foobar> for Y where Z" headers, whereas "[src]" takes only a small, and constant, amount of space.

**Comment by GuillaumeGomez** [comment]
I'm not sure to understand what you're talking about. Do you have a screenshot please?

**Comment by birkenfeld** [comment]
Sure! You can see that the `impl` lines would fit in one line easily, but the `out-of-band` span has `width: 40%` set, and `in-band` has `width: 60%`, so there is a lot of space wasted in the 40%.

2016-05-06-080647_3200x1080_scrot

**Comment by GuillaumeGomez** [comment]
Oh I see! I'll do something about it as well then.

**Comment by GuillaumeGomez** [comment]
@birkenfeld: So with the last commit I did:
* When "since" and "src" are on same item, "since" is left aligned to "src".
* Now, elements aren't 60% and 40% anymore, no wasted space.
* When you reduce browser's size, "since" and "src" goes *under* elements, avoiding ugly issues.

Do you mind testing it and giving me your feedback please? :)

**Comment by birkenfeld** [comment]
@GuillaumeGomez the style and positioning looks good to me now! I found three issues (Firefox 45 and Chromium 50, on Linux):

* there is a "1.0.0" in the upper right corner which I think wasn't there before (see 1st screenshot)
* in a very small range of window width, text is overlapping (this can probably be ignored, see 2nd screenshot)
* the more serious issue is that I can't click the links anymore :)  when removing the `position: absolute` they are clickable again (but of course not at the correct position)

2016-05-06-195527_3200x1080_scrot


2016-05-06-195440_3200x1080_scrot

**Comment by GuillaumeGomez** [comment]
> in a very small range of window width, text is overlapping (this can probably be ignored, see 2nd screenshot)

That's the goal. Look at my comment:

> When you reduce browser's size, "since" and "src" goes under elements, avoiding ugly issues.

> * there is a "1.0.0" in the upper right corner which I think wasn't there before (see 1st screenshot)
> * the more serious issue is that I can't click the links anymore :) when removing the position: absolute they are clickable again (but of course not at the correct position)

I'm on it!

**Comment by birkenfeld** [comment]
> That's the goal. Look at my comment:
>>  When you reduce browser's size, "since" and "src" goes under elements, avoiding ugly issues.

Ah. I was reading "under" as "vertically below". Makes sense.

**Comment by GuillaumeGomez** [comment]
Try to reduce browser window without my change, you'll understand better why I did this change. :wink:

**Comment by GuillaumeGomez** [comment]
Updated. So that's what it looks like now:

screenshot from 2016-05-05 17 17 08

@birkenfeld: I checked and remove some bugs I found but could you take another look please?

**Comment by birkenfeld** [comment]
Looks good! A very minor thing I noticed is that the "stable since" versions are styled differently, e.g. the "1.0.0" and the "1.9.0" in the first of my previous screenshots.

**Comment by GuillaumeGomez** [comment]
Didn't pay attention to it. I update it. Thanks for the feedback!

**Comment by GuillaumeGomez** [comment]
It was a font issue. Do you see anything else @birkenfeld?

**Comment by birkenfeld** [comment]
Nope, I'm happy :+1:

**Comment by GuillaumeGomez** [comment]
Great! :smile: 

cc @steveklabnik 
cc @Manishearth

**Comment by mitaa** [comment]
If the first-line of the top level doc-block is long enough it overlaps with the "stable since" annotation.

http://doc.rust-lang.org/nightly/std/fmt/fn.write.html
stability_overlap

> * When you reduce browser's size, "since" and "src" goes under elements, avoiding ugly issues.

Was this intended?

**Comment by GuillaumeGomez** [comment]
> Was this intended?

It is. But not in this precise case (I mean, it's not supposed to be removed if you don't reduce browser's size).

**Comment by GuillaumeGomez** [comment]
To avoid this issue, I propose, for the "first" since which appears normally in the paragraph describing the type/function/whatever to be put at the top. Like the following:

screen

This way, we avoid the overlap if the description is too long.

**Comment by birkenfeld** [comment]
I like it, this is more consistent with the other "since"s as well.

**Comment by steveklabnik** [comment]
I like it too!

**Pull request merged**
