### PR TITLE
interpret: fix alignment handling for Repeat expressions

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by oli-obk** [comment]
Is there some context that motivated this change?

**Comment by RalfJung** [comment]
It fixes a bug. :) The new testcase src/tools/miri/tests/pass/align_repeat_into_packed_field.rs is [currently accidentally UB](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d6ad28c78f621419ce51a5cb54fb21ec) but that should be allowed.

**Comment by oli-obk** [comment]
yea, I was just wondering if there was any discussion that made you realize that, but it seems to just be careful code reading 😆 

@bors r+

**Comment by RalfJung** [comment]
The full story is that I did some research for https://github.com/rust-lang/opsem-team/issues/11, then I found https://github.com/rust-lang/rust/pull/54547 which led me to https://github.com/rust-lang/rust/issues/56927 and https://github.com/rust-lang/rust/pull/57053 and reading that PR I realized I should double-check what Miri does and then found the problem in `Repeat` handling. :)

**Pull request merged**
