### PR TITLE
Resolve: fix scoping bug (fixes #31845) and improve unused import detection

### LINKED ISSUE #31845: Regression (?) in name resolution of items defined in functions/blocks
This code compiles on nightly, but is rejected by stable and beta compilers.
On nightly items defined in a block are visible from all modules defined in this block.
Such "pervasive" visibility is quite unusual and I suspect it was introduced unintentionally.
```
fn f() {
    struct S;

    fn g() {
        let s = S; // <- beta/stable/nightly - ok
    }
    mod m {
        fn h() {
            let s = S; // <- beta/stable - error: unresolved name `S` [E0425], nightly - ok
        }
        
        mod n {
            fn k() {
                let s = S; // <- beta/stable - error: unresolved name `S` [E0425], nightly - ok
            }
        }
    }
}

fn main() {
}
```

cc @jseyfried

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes a bug (#31845) introduced in #31105 in which lexical scopes contain items from all anonymous module ancestors, even if the path to the anonymous module includes a normal module:

``` rust
fn f() {
    fn g() {}
    mod foo {
        fn h() {
           g(); // This erroneously resolves on nightly
        }
    }
}
```

This is a [breaking-change] on nightly but not on stable or beta.
r? @nikomatsakis

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @petrochenkov

**Comment by nikomatsakis** [comment]
@jseyfried to be clear, by "breaking change" you mean "bug fix", right? Seems clear this was never intended to work.

**Comment by jseyfried** [comment]
Yeah, this is definitely a bug fix. I was using "[breaking-change]" in the narrowest sense, i.e. a change that can break code that used to compile, correctly or not. Is this not the intended meaning?

**Pull request merged**
