### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #66329 (Add unreachable propagation mir optimization pass)
 - #67784 (Reset Formatter flags on exit from pad_integral)
 - #67914 (Don't run const propagation on items with inconsistent bounds)
 - #68012 (Update some of Cargo's dependencies)
 - #68096 (Clean up some diagnostics by making them more consistent)
 - #68118 (perf: Eagerly convert literals to consts)
 - #68123 (Implement Cursor for linked lists. (RFC 2570).)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by JohnTitor** [comment]
image

Homu doesn't seem to get up...
@bors retry

**Comment by Dylan-DPC** [comment]
@bors r-  

closing this in favour of a fresher rollup

**Pull request closed without merging**
