### PR TITLE
Add f-string

### PR DESCRIPTION
**Pull request by trolleyman**
Hi! I've had this idea knocking around for a while of adding f-strings. I apologize for not going through the proper RFC process, but I thought it would be easier to get it working first and see what people thought informally, before going through that.

Demo:

```rust
let a = "test";
let b = "spam";
let text = f"Hello {a} {b}! {5 * 4 + 22}";
assert_eq!(text, "Hello test spam! 42");

let nested = f"foo { f"bar { f"baz { f"quux: {9 * 9}!" }" }" }";
assert_eq!(nested, "foo bar baz quux: 81!");
```

There are a lot of unresolved issues that I'd really appreciate feedback on!
- I've chosen "f-string", as a shorthand for "format string". This is to avoid confusion with the other meaning of format string (the string that is passed into the `format!` / `print!` macros), but up for changing it to just format string, to be easier to understand for users.
- This implementation doesn't have any addition of options, as I think it may conflict with type ascription: e.g. `f"{foo:x}"` could be trying to print `foo` with the hex option, or it could be ascribing type `x` to the `foo` expression.
  - As type ascription is unstable, this isn't a huge problem.
  - This could be solved by just automatically assuming this is a format option until otherwise proven - and `f"{foo:type:}"` could be used if people really want type ascription. This may be more tricky to implement though, so I'm leaving that until I get some feedback on this.
- A `Lexer` struct has been made, to replace `Cursor`, as it now needs to be stateful to keep track of the f-string nesting.
- There was a bit of back-and-forth on deciding if f-strings should be treated as "proper" literals or not. Currently this is the solution:
  - `rustc_lexer::TokenKind` and `rustc_ast::TokenKind` have `FStr` directly on them, as opposed to in `LiteralKind`. See `rustc_lexer/tests.rs` for the new f-string tests.
  - `rustc_ast::ExprKind` has a new `FStr` member too, but it is fully parsed at this point.
  - This then plugs directly into the existing `format_args!` machinery, with one change - `alloc::fmt::format` is now a lang intrinsic. To allow f-strings on non-std platforms in future, we could add an extra prefix to allow for getting `FormatArgs` directly from f-strings (e.g. `fa"foo {1 + 1}"` and/or `af"bar {2 + 2}"` would return `FormatArgs`)
- `rustc_expand::proc_macro_server` has been modified to add f-strings - would this be a breaking change? If so, how could it be changed in a backwards-compatible way? Editions?
- Should expressions f-strings support statements? i.e. should the parser treat the inner expression as a block? It is surrounded by braces, so it would fit. Would be quite cool (or hacky, depending on your opinion): `f"{ let a = 2; a }" -> "2"`
- Currently f-strings don't have suffixes, whereas other strings do. I think this is ok?
- There are various `// TODO`s around the diff, feedback appreciated :)

### CODE REVIEW

**Comment by workingjubilee** [comment]
Your `assert_eq!`s in the example in your PR notes don't actually have both an lhs and rhs.

> Should expressions f-strings support statements? i.e. should the parser treat the inner expression as a block? It is surrounded by braces, so it would fit. Would be quite cool (or hacky, depending on your opinion): f"{ let a = 2; a }" -> "2"

But a block _is_ an expression. It's a block expression. The following is a valid match expression:

```rust
match { let a = b * c; let d = e * f; a + d } {
    _ => "bloop",
}
```

I haven't read your entire implementation but what ExprKinds does it _not_ support?

> As type ascription is unstable, this isn't a huge problem.

Type ascription has been marked for removal by the acceptance of [De-RFC 3307](https://rust-lang.github.io/rfcs/3307-de-rfc-type-ascription.html).

Problems:
- greatly complicates the language to handle a magic string including source code
- which also greatly complicates parsing, highlighting, etc.
- probably could have been done in a library as a demo using a proc macro?
- probably *is* done in some library using a proc macro...?
- as this is not an RFC, has not addressed [the concerns raised in RFC 2795 about precisely this](https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html#alternative-solution---interpolation)

**Comment by workingjubilee** [comment]
I don't think any implementation of any feature of this nature should prioritize the std use-case over the embedded use-case. Using this without allocations, using `write!` and similar, so that the data could be streamed over a serial port, should be a primary concern here. I don't think this should have a separate way to write it for that use-case, either.

**Comment by jhpratt** [comment]
> I apologize for not going through the proper RFC process, but I thought it would be easier to get it working first and see what people thought informally, before going through that.

Speculative implementations are okay, but don't expect it to be merged unless there is _at an absolute minimum_ general indication from the lang team that it's a desirable feature. That has not happened here, so I strongly oppose merging this. The RFC process exists for a reason — to hash out details, explore other possibilities, and far more. That's not to say RFCs are easy! Having written two myself, they are _a ton_ of work. But it's essential.

**Comment by nehaaaa6** [comment]
name = "Alice"
age = 30
print(f"My name is {name} and I'm {age} years old.")

The output of this code would be:

My name is Alice and I'm 30 years old.

In the example above, the expressions inside the curly braces {} are evaluated and inserted into the string at runtime. This allows for more concise and readable code when combining strings with variable values.

To use f-strings in your own code, simply prefix a string literal with the letter "f" or "F" and include expressions inside curly braces {} where you want the values to be inserted. For example:

x = 5
y = 10
print(f"The sum of {x} and {y} is {x+y}.")
output
The sum of 5 and 10 is 15.

**Comment by trolleyman** [comment]
> Your `assert_eq!`s in the example in your PR notes don't actually have both an lhs and rhs.

Thanks, fixed.

> But a block _is_ an expression. It's a block expression.

Sorry, what I mean is that a block expression could be used directly, instead of right now where it has to be surrounded by braces. In the code it calls `parse_expr()` on the inner expression, but could be changed to call `parse_block()` directly.

> Type ascription has been marked for removal by the acceptance of [De-RFC 3307](https://rust-lang.github.io/rfcs/3307-de-rfc-type-ascription.html).

Ah great, thanks, I didn't know that.

> * greatly complicates the language to handle a magic string including source code
> * which also greatly complicates parsing, highlighting, etc.
> * probably could have been done in a library as a demo using a proc macro?
> * probably _is_ done in some library using a proc macro...?
> * as this is not an RFC, has not addressed [the concerns raised in RFC 2795 about precisely this](https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html#alternative-solution---interpolation)

Thanks for highlighting this, these are all valid points. I personally don't think it complicates the language unnecessarily, but I guess that's a debate to be had.

It probably should have been done as a proc macro, but I feel that it's sometimes easier to get stuck in first to see first hand what problems can arise. I accept that this won't be merged without an RFC, but I feel it's useful to get preliminary feedback.

Thanks for the link to that RFC. The perspectives in there are slightly orthogonal to the f-string debate - they are mentioned, but it's mostly from the perspective of arguing against adding full interpolation to `format!` strings, rather than adding f-strings standalone. I think that f-strings solve a few of the problems with adding interpolation to `format` strings, as they are a language-level syntax feature, they can be a lot more powerful, expressive, and intuitive than a macro-level solution. I agree that an RFC is needed.

**Comment by trolleyman** [comment]
> Speculative implementations are okay, but don't expect it to be merged unless there is _at an absolute minimum_ general indication from the lang team that it's a desirable feature. That has not happened here, so I strongly oppose merging this. The RFC process exists for a reason — to hash out details, explore other possibilities, and far more. That's not to say RFCs are easy! Having written two myself, they are _a ton_ of work. But it's essential.

Very fair points, thanks 🙂 I'll get started on an RFC.

**Comment by jhpratt** [comment]
Just to be clear in case my last comment came off as somewhat rude: I do not oppose this in principle. It is merely that there are processes that should be followed to ensure various issues are figured out. I'm honestly surprised the diff is as small as it is for such a significant change.

Feel free to ping me if/when you post an RFC; I'll review it.

**Pull request closed without merging**
