### PR TITLE
Add manual Sync impl for ReentrantLockGuard

### LINKED ISSUE #125526: ReentrantLockGuard's Sync impl is unsound
I tried running this code in miri:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4b45c8a022255be4404228c01922b632
```rust
#![feature(reentrant_lock)]
use std::cell::Cell;
use std::sync::ReentrantLock;
use std::thread::scope;

fn main() {
    let l = ReentrantLock::new(Cell::new(0u8));
    let lg = l.lock();
    scope(|s| {
        s.spawn(|| dbg!(lg.get()));
        lg.set(1);
    });
}
```

I expected to see this happen: compile error

Instead, this happened: compiled successfully and miri reported a data race

this is because the automatic `impl<T: Send> Sync for ReentrantLockGuard<T>` is incorrect:
https://doc.rust-lang.org/1.78.0/std/sync/struct.ReentrantLockGuard.html#impl-Sync-for-ReentrantLockGuard%3C'a,+T%3E

ReentrantLock's tracking issue: #121440

### PR DESCRIPTION
**Pull request by programmerjake**
Fixes: #125526
Tracking Issue: #121440

this impl is even shown in the summary in the tracking issue, but apparently was forgotten in the actual implementation

### CODE REVIEW

**Comment by workingjubilee** [comment]
@programmerjake Can you add a test for this? Something that fails to compile if ReentrantLock is not Sync, like I added in https://github.com/rust-lang/rust/pull/125392

Or something that fails to compile if ReentrantLock is `!Sync` or `?Sync`, if you're feeling silly, that's fine too.

**Comment by programmerjake** [comment]
@workingjubilee
> @programmerjake Can you add a test for this? Something that fails to compile if ReentrantLock is not Sync

done, except that this checks ReentrantLockGuard, not ReentrantLock.

**Comment by workingjubilee** [comment]
ah, yes, I did... :upside_down_face: thank you for doing what I meant instead of what I managed to say.

**Comment by workingjubilee** [comment]
cc @joboet

**Pull request merged**
