### PR TITLE
Incorporated Tracing Crate in some libraries

### PR DESCRIPTION
**Pull request by pawanbisht62**
Issue #74747

### CODE REVIEW

**Comment by bishtpawan** [comment]
@estebank can you please have a look at the PR as this is assigned to you. Thanks

**Comment by bishtpawan** [comment]
@oli-obk can you please have a look at this issue? As this PR is related to #74747.

**Comment by oli-obk** [comment]
@bors r+

apologies, I did not see this PR. Looks good to me, thanks!

**Pull request merged**
