### PR TITLE
update miri

### LINKED ISSUE #61662: `miri` no longer builds after rust-lang/rust#61625
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#61625, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @RalfJung, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @oli-obk, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/61662

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
Rebased.

@bors r=oli-obk

**Comment by mati865** [comment]
@oli-obk @RalfJung 
This PR will fail with something like:
```
Dependencies not on the whitelist:
 * fuchsia-cprng
 * rand_os
 * rdrand
```

See https://github.com/rust-lang/rust/pull/61597 which updates `Cargo.lock` and contains necessary changes.

**Comment by RalfJung** [comment]
Dang. Okay then let's let that land first.

@bors r- retry

**Comment by lnicola** [comment]
https://github.com/rust-lang/rust/pull/61597 was merged, you can probably rebase now.

**Comment by RalfJung** [comment]
Thanks for the ping! First I need to fix Miri for https://github.com/rust-lang/rust/pull/61722 though...

**Comment by RalfJung** [comment]
Fixed Miri upstream and rebased.

@bors r=oli-obk

**Pull request merged**
