### PR TITLE
rustdoc: Fix visibility of trait and impl items

### LINKED ISSUE #81274: Wrong `pub` modifier in each function of trait documentation
The [documentation of Iterator](https://doc.rust-lang.org/1.49.0/std/iter/trait.Iterator.html#tymethod.next) trait on 1.49.0 (current stable) doesn't contain `pub` modifier in function declaration of that trait.
image
However, on [beta](https://doc.rust-lang.org/beta/std/iter/trait.Iterator.html#tymethod.next) and nightly, there is `pub` modifier.
image

This is wrong because you cannot use `pub` modifier for each method/function in Trait definition.
Why is this important? People copy the method/function declaration in the documentation to their code
and see the compiler error: `error[E0449]: unnecessary visibility qualifier`. 

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

cc @jyn514 I think this might relate to some changes in visibility around macros ?

### PR DESCRIPTION
**Pull request by camelid**
Fixes #81274.

r? @jyn514

### CODE REVIEW

**Comment by camelid** [comment]
Beta-nominated since this is a regression from stable to beta. Not sure if it's worth backporting, but we should definitely consider it.

**Review by jyn514 — APPROVED** [review]
r=me with CI passing

**Comment by camelid** [comment]
CI caught a bug: `impl`s are not always trait impls!

**Comment by camelid** [comment]
@jyn514 CI *should* pass now, but I think you should re-review as the behavior has changed.

**Comment by jyn514** [comment]
@bors r+

Looks great, thanks!

**Pull request merged**
