### PR TITLE
WIP: Gate generating `mod` items in procedural macros

### PR DESCRIPTION
**Pull request by alexcrichton**
Discovered in https://github.com/rust-lang/rust/issues/50504 the hygiene here is super questionable, so we'll likely want to gate this by default for procedural macros and procedural attributes for sure. This is a PR to evaluate the impact for procedural derive as well.

### CODE REVIEW

**Comment by petrochenkov** [comment]
@alexcrichton 
We probably should apply the same restriction to macros generating `macro_rules!` items.

**Comment by Mark-Simulacrum** [comment]
Crater run finished: https://cargobomb-reports.s3.amazonaws.com/pr-50587/index.html.

**Comment by alexcrichton** [comment]
Alrighty-roo, thanks @Mark-Simulacrum! Definitely seems like we can't land this as-is, I'll file a follow-up.

**Pull request closed without merging**
