### PR TITLE
doc: no need for the reference

### PR DESCRIPTION
**Pull request by tshepang**
Also, we are well within line length limit

### CODE REVIEW

**Comment by kennytm** [comment]
Thanks for the PR @tshepang! 

Would you mind changing the code at line 1592 too? 

The examples for  `.inspect()` (lines 1184 and 1193), `.by_ref()` (lines 1234 and 1250), `.collect()` (lines 1291, 1308, 1322 and 1347) and `.partition()` (line 1397) may also be updated.

(The `&` for `try_fold()` needs to be kept though)

**Comment by tshepang** [comment]
Thanks for the thorough checking... I hopes I fixed it all.

**Comment by pietroalbini** [comment]
Ping from the release team. This PR doesn't have any assigned reviewer, assigning someone randomly from the docs team.

r? @frewsxcv

**Comment by frewsxcv** [comment]
looks great, thanks!

@bors r+ rollup

**Pull request merged**
