### PR TITLE
DO NOT MERGE: debug some CI issues

### PR DESCRIPTION
**Pull request by ethomson**
This has a build that removes all the complex bits - and even the simple ones - like sccache to help illustrate where the >3 hours build failures might be coming from.

### CODE REVIEW

**Comment by ethomson** [comment]
(Oops, I should have removed the travis configuration; sorry for tying up precious build agents.)

**Comment by ethomson** [comment]
Aaaaand I realize that AppVeyor isn't running on PR builds, so this was rather pointless anyway.

**Comment by pietroalbini** [comment]
@bors r+ p=1000

Please do **not** land, thx.

**Comment by pietroalbini** [comment]
Closed+reopened to fix bors weirdness.

**Comment by pietroalbini** [comment]
Thanks :heart:

**Pull request closed without merging**
