### PR TITLE
Inline `DebruijnIndex` methods

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Attempts to fix the perf regression from #79169. Could someone queue a perf run for this?

r? @nikomatsakis cc @rylev

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
This doesn't seem to fix the performance

**Comment by jackh726** [comment]
I wonder if it's the functions on `TypeFlags`?

**Comment by LeSeulArtichaut** [comment]
> I wonder if it's the functions on `TypeFlags`?

IIUC those already have `#[inline]` (see e.g. [`empty`](https://github.com/bitflags/bitflags/blob/c2ba43141307a97484518ad7728534855e1a51f2/src/lib.rs#L579))...

**Comment by LeSeulArtichaut** [comment]
What should I do with this? Should I close it? Should we merge it?

**Comment by rylev** [comment]
If this isn't improving performance, I don't see why we should merge it. Thoughts?

**Comment by LeSeulArtichaut** [comment]
Yeah, I'll just close this.

**Comment by jackh726** [comment]
With regards to #79169, the only other *function* that got moved out was the `hash_stable` on `DebruijnIndex`. Other than that, there's not a clear target for inlining.

**Pull request closed without merging**
