### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #123714 (Add test for fn pointer duplication.)
 - #124091 (Update AST validation module docs)
 - #127015 (Switch back `non_local_definitions` lint to allow-by-default)
 - #127016 (docs: check if the disambiguator matches its suffix)
 - #127029 (Fix Markdown tables in platform-support.md)
 - #127032 (Enable const casting for `f16` and `f128`)
 - #127055 (Mark Hasher::finish as #[must_use])
 - #127068 (Stall computing instance for drop shim until it has no unsubstituted const params)
 - #127070 (add () to the marker_impls macro for ConstParamTy)
 - #127071 (Remove (deprecated & unstable) {to,from}_bits pointer methods)
 - #127078 (Enable full tools and profiler for LoongArch Linux targets)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=123714,124091,127015,127016,127029,127032,127055,127068,127070,127071,127078)

### CODE REVIEW

**Comment by tgross35** [comment]
> ☀️ Test successful - [checks-actions](https://github.com/rust-lang-ci/rust/actions/runs/9721718739/job/26836312059) Approved by: matthiaskrgr Pushing [d38cd22](https://github.com/rust-lang/rust/commit/d38cd229b75a7a608e4971c46d1fb5a99343e430) to master...

🎉 Congrats Bors! Only took 2 days since the initial rollup with these PRs :)

**Comment by matthiaskrgr** [comment]
:crying_cat_face:

**Comment by lqd** [comment]
I was like "free perf!", but of course it's the lint machinery from https://github.com/rust-lang/rust/pull/127015

**Comment by pnkfelix** [comment]
@rust-timer build 970eefb2292c45cb2f90ec6e67308288651c32b0

**Comment by pnkfelix** [comment]
visiting for weekly rustc-perf triage


* all 7 primary regressions are variants of syn; all but one are incremental.
* skimming the detailed results reports for the top three regressing variants, I see the following queries at the top of the ordering by time-delta: incr_comp_persist_dep_graph, hir_crate, codegen_copy_ar\
tifacts_from_incr_cache, early_lint_checks...
* what in this rollup would have impacted those incremental-compilation related queries?
* PR #1270668 already had its own dedicated rustc-perf run.
* (is this potentially just fallout noise from internal API changes like that in PR #127071?)
* fired off a rust-timer build against that, just to scratch that itch.

**Comment by pnkfelix** [comment]
grasping at straws

@rust-timer build fba1e63e778a3ca8e37ce0978609392b25930a6d

**Pull request merged**
