### PR TITLE
fix sparc64 ABI for aggregates with floating point members

### LINKED ISSUE #86163: SPARC - passing argument from C++ to Rust issue
This was originally reported as Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1714064

But now it seems to be rather Rust issue.

Unfortunately I wasn't able to reproduce it outside of Firefox yet:

C++ code calls ```wr_dp_push_stacking_context()``` with parameter ```aParams.mFilterDatas.Length()``` which is zero (0):
 
https://searchfox.org/mozilla-central/rev/79d73b4aff88dd4a0f06dd3789e1148c49b0de60/gfx/webrender_bindings/WebRenderAPI.cpp#1028

But Rust code gets instead of ```0``` some nonsense number (e.g. 133081200598864):

https://searchfox.org/mozilla-central/rev/79d73b4aff88dd4a0f06dd3789e1148c49b0de60/gfx/webrender_bindings/src/bindings.rs#2455

I was able to limit the  ```wr_dp_push_stacking_context()``` to just:

```
#[no_mangle]
pub extern "C" fn wr_dp_push_stacking_context(
    bounds: LayoutRect,
    filter_count: usize,
    glyph_raster_space: RasterSpace,
    params: &WrStackingContextParams,
)  {
    debug_assert!(unsafe { !is_in_render_thread() });
    println!("XXX start {}", filter_count);
}
```
And the problem is still there. **But when I swap ```bounds: LayoutRect``` with ```filter_count: usize``` then ```filter_count``` is passed correctly!**

```LayoutRect``` is quite complicated (to me):
https://searchfox.org/mozilla-central/rev/79d73b4aff88dd4a0f06dd3789e1148c49b0de60/gfx/wr/webrender_api/src/units.rs#86
Important might be that it uses **floating numbers**!

Following is disassembled ```wr_dp_push_stacking_context``` function as defined above:

```
wr_dp_push_stacking_context:    save      %sp, -0x160, %sp
wr_dp_push_stacking_context+4:  call      +0x8          <wr_dp_push_stacking_context+0xc>
wr_dp_push_stacking_context+8:  sethi     %hi(0x3b05800), %i0
wr_dp_push_stacking_context+0xc:or        %i0, 0x3f8, %i0
wr_dp_push_stacking_context+0x10:       add       %i0, %o7, %i0
wr_dp_push_stacking_context+0x14:       stx       %i0, [%fp + 0x767]
wr_dp_push_stacking_context+0x18:       ldx       [%fp + 0x8af], %i0
wr_dp_push_stacking_context+0x1c:       st        %f1, [%fp + 0x787]
wr_dp_push_stacking_context+0x20:       st        %f3, [%fp + 0x78b]
wr_dp_push_stacking_context+0x24:       st        %f5, [%fp + 0x78f]
wr_dp_push_stacking_context+0x28:       st        %f7, [%fp + 0x793]
wr_dp_push_stacking_context+0x2c:       ld        [%fp + 0x787], %i0
wr_dp_push_stacking_context+0x30:       sllx      %i0, 0x20, %i0
wr_dp_push_stacking_context+0x34:       ld        [%fp + 0x78b], %i1
wr_dp_push_stacking_context+0x38:       or        %i0, %i1, %i0
wr_dp_push_stacking_context+0x3c:       stx       %i0, [%fp + 0x777]
wr_dp_push_stacking_context+0x40:       ld        [%fp + 0x78f], %i0
wr_dp_push_stacking_context+0x44:       sllx      %i0, 0x20, %i0
wr_dp_push_stacking_context+0x48:       ld        [%fp + 0x793], %i1
wr_dp_push_stacking_context+0x4c:       or        %i0, %i1, %i0
wr_dp_push_stacking_context+0x50:       stx       %i0, [%fp + 0x77f]
wr_dp_push_stacking_context+0x54:       stx       %i4, [%fp + 0x797]
wr_dp_push_stacking_context+0x58:       stx       %i5, [%fp + 0x7a7]
wr_dp_push_stacking_context+0x5c:       call      -0xae63cb0    <is_in_render_thread>
wr_dp_push_stacking_context+0x60:       stx       %i5, [%fp + 0x79f]
wr_dp_push_stacking_context+0x64:       ba        +0x8          <wr_dp_push_stacking_context+0x6c>
wr_dp_push_stacking_context+0x68:       st        %o0, [%fp + 0x773]
wr_dp_push_stacking_context+0x6c:       ld        [%fp + 0x773], %i0
wr_dp_push_stacking_context+0x70:       cmp       %i0, 0x0
wr_dp_push_stacking_context+0x74:       be        +0x38         <wr_dp_push_stacking_context+0xac>
wr_dp_push_stacking_context+0x78:       nop
wr_dp_push_stacking_context+0x7c:       ba        +0x8          <wr_dp_push_stacking_context+0x84>
wr_dp_push_stacking_context+0x80:       nop
wr_dp_push_stacking_context+0x84:       ldx       [%fp + 0x767], %i0
wr_dp_push_stacking_context+0x88:       sethi     %hi(0x35c00), %i1
wr_dp_push_stacking_context+0x8c:       add       %i1, 0x3b8, %i1
wr_dp_push_stacking_context+0x90:       ldx       [%i0 + %i1], %o0
wr_dp_push_stacking_context+0x94:       sethi     %hi(0x36000), %i1
wr_dp_push_stacking_context+0x98:       add       %i1, 0x50, %i1
wr_dp_push_stacking_context+0x9c:       ldx       [%i0 + %i1], %o2
wr_dp_push_stacking_context+0xa0:       call      +0x3c7726c    <PLT:_ZN4core9panicking5panic17he6543f3ddbf0355fE>
wr_dp_push_stacking_context+0xa4:       mov       0x33, %o1
wr_dp_push_stacking_context+0xa8:       ta        %icc, 0x5
wr_dp_push_stacking_context+0xac:       ldx       [%fp + 0x767], %i0
wr_dp_push_stacking_context+0xb0:       add       %fp, 0x797, %o0
wr_dp_push_stacking_context+0xb4:       stx       %o0, [%fp + 0x7ef]
wr_dp_push_stacking_context+0xb8:       stx       %o0, [%fp + 0x7f7]
wr_dp_push_stacking_context+0xbc:       sethi     %hi(0x1400), %i1
wr_dp_push_stacking_context+0xc0:       add       %i1, 0x190, %i1
wr_dp_push_stacking_context+0xc4:       call      +0x3c81028    <PLT:_ZN4core3fmt10ArgumentV13new17ha9bc9565de3aadf7E>
wr_dp_push_stacking_context+0xc8:       ldx       [%i0 + %i1], %o1
wr_dp_push_stacking_context+0xcc:       stx       %o0, [%fp + 0x757]
wr_dp_push_stacking_context+0xd0:       ba        +0x8          <wr_dp_push_stacking_context+0xd8>
wr_dp_push_stacking_context+0xd4:       stx       %o1, [%fp + 0x75f]
wr_dp_push_stacking_context+0xd8:       ldx       [%fp + 0x767], %i0
wr_dp_push_stacking_context+0xdc:       ldx       [%fp + 0x75f], %i1
wr_dp_push_stacking_context+0xe0:       ldx       [%fp + 0x757], %i2
wr_dp_push_stacking_context+0xe4:       stx       %i2, [%fp + 0x7df]
wr_dp_push_stacking_context+0xe8:       stx       %i1, [%fp + 0x7e7]
wr_dp_push_stacking_context+0xec:       sethi     %hi(0x36000), %i1
wr_dp_push_stacking_context+0xf0:       add       %i1, 0x58, %i1
wr_dp_push_stacking_context+0xf4:       ldx       [%i0 + %i1], %o1
wr_dp_push_stacking_context+0xf8:       add       %fp, 0x7af, %o0
wr_dp_push_stacking_context+0xfc:       mov       0x2, %o2
wr_dp_push_stacking_context+0x100:      add       %fp, 0x7df, %o3
wr_dp_push_stacking_context+0x104:      call      +0xe2a0c      <core::fmt::Arguments::new_v1::h337fca81b2e584b1>
wr_dp_push_stacking_context+0x108:      mov       0x1, %o4
wr_dp_push_stacking_context+0x10c:      ba        +0x8          <wr_dp_push_stacking_context+0x114>
wr_dp_push_stacking_context+0x110:      nop
wr_dp_push_stacking_context+0x114:      call      +0x3df5ab0    <PLT:_ZN3std2io5stdio6_print17h02792fbd1097b851E>
wr_dp_push_stacking_context+0x118:      add       %fp, 0x7af, %o0
wr_dp_push_stacking_context+0x11c:      ba        +0x8          <wr_dp_push_stacking_context+0x124>
wr_dp_push_stacking_context+0x120:      nop
wr_dp_push_stacking_context+0x124:      ret
wr_dp_push_stacking_context+0x128:      restore
```

### PR DESCRIPTION
**Pull request by psumbera**
Fixes #86163

### CODE REVIEW

**Comment by psumbera** [comment]
I have created this with some suggestions from @eddyb.

**Comment by nagisa** [comment]
This should have a regression test which tests both the LLVM-IR output and the assembly. One with `#[no_core]` and `compiler-flags: --target=sparc64-...` so that it runs on all hosts would be ideal.

See `src/test/codegen/sparc-struct-abi.rs` for an example of an LLVM-IR test and `src/test/assembly` for the assembly ones.

**Comment by psumbera** [comment]
@nagisa isn't extending src/test/codegen/sparc-struct-abi.rs enough? I don't know how to check these easily in assembler...

**Comment by nagisa** [comment]
I would say that LLVM IR is a pretty poor proxy for verifying the ABI is what we want it to be. Conventionally we would have a `run-pass` test which would call some [functions defined in C](https://github.com/rust-lang/rust/blob/master/src/test/auxiliary/rust_test_helpers.c), [like this](https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/src/test/ui/abi/cabi-int-widening.rs).

However since nobody is really able to run tests on a SPARC and the CI does not cover the architecture, a such a `run-pass` test would be pretty much always skipped (though adding one would still be appreciated!)

An assembly test therefore is the next best thing, I feel. As for how to construct such a test, I would start with emitting some assembly from clang for an equivalent call and then `FileCheck`ing the ABI instructions around… Kinda like this (taking the code from the issue):

```rust
// compiler-flags: -Copt-level=3 --target=sparc...

#[repr(C)]
pub struct Franta {
        a:f32,
        b:f32,
        c:f32,
        d:f32,
}

// CHECK-LABEL: callee
#[no_mangle]
pub extern "C" fn callee(arg: Franta) {
    // CHECK: fmovs   %f?, %f0
    // CHECK: call use
    use(arg.a); 
    // CHECK: fmovs   %f?, %f0
    // CHECK: call use
    use(arg.b); 
    // CHECK: fmovs   %f?, %f0
    // CHECK: call use
    use(arg.c);
    // CHECK: fmovs   %f?, %f0
    // CHECK: call use
    use(arg.d);
}

extern "C" {
    fn opaque_callee(arg: Franta, intarg: i32);
    fn use(arg: f32);
}

// CHECK-LABEL: caller
// CHECK: mov       0x3, %o2
// CHECK: fmovs     %{{.*}}, %f0
// CHECK: fmovs     %{{.*}}, %f1
// CHECK: fmovs     %{{.*}}, %f2
// CHECK: fmovs     %{{.*}}, %f3
// CHECK: call {{.*}}
pub unsafe extern "C" fn caller() {
    opaque_callee(Franta { a: 1.0, b: 2.0, c: 3.0, d: 4.0 }, 3);
}
```

Do note that I pretty much wrote this entire thing into the github's comment field from memory so there may be mistakes in the code above etc, but should give you a good starting point, hopefully?

**Comment by psumbera** [comment]
I think I that `asm` testing cannot reliable work. One time it uses `fmovs` instruction and another time `st` instruction.

Clang code below:
```
void calle(struct Franta a) {
  tst_use(a.a);
  tst_use(a.b);
  tst_use(a.c);
  tst_use(a.d);
}
```
generates:
```
calle:                                  ! @calle
! %bb.0:
        save %sp, -208, %sp
        st %f0, [%fp+2031]
        add %fp, 2031, %i0
        or %i0, 4, %i0
        st %f1, [%i0]
        st %f2, [%fp+2039]
        st %f3, [%fp+2043]
        ld [%fp+2031], %f1
        call tst_use
        stx %i0, [%fp+2023]
        ldx [%fp+2023], %i0                     ! 8-byte Folded Reload
        call tst_use
        ld [%i0], %f1
        call tst_use
        ld [%fp+2039], %f1
        call tst_use
        ld [%fp+2043], %f1
        ret
        restore
```

Where Rust code:
```
pub unsafe extern "C" fn callee(arg: Franta) {
    tst_use(arg.a);
    tst_use(arg.b);
    tst_use(arg.c);
    tst_use(arg.d);
}
```
generates:
```
callee:
        .cfi_startproc
        save %sp, -192, %sp
        .cfi_def_cfa_register %fp
        .cfi_window_save
        .cfi_register %o7, %i7
        st %f3, [%fp+2043]
        st %f2, [%fp+2039]
        st %f1, [%fp+2035]
        fmovs %f0, %f1
        call tst_use
        nop
        call tst_use
        ld [%fp+2035], %f1
        call tst_use
        ld [%fp+2039], %f1
        call tst_use
        ld [%fp+2043], %f1
        ret
        restore
```

**Comment by psumbera** [comment]
E.g. Following works. But I think it can change with next LLVM update:
```
// assembly-output: emit-asm
// needs-llvm-components: sparc
// compile-flags: --target=sparcv9-sun-solaris
#![crate_type = "lib"]

#[repr(C)]
pub struct Franta {
        a:f32,
        b:f32,
        c:f32,
        d:f32,
}

// CHECK-LABEL: callee
#[no_mangle]
pub unsafe extern "C" fn callee(arg: Franta) {
    // CHECK: st %f3, [%fp+2043]
    // CHECK: st %f2, [%fp+2039]
    // CHECK: st %f1, [%fp+2035]
    // CHECK: fmovs %f0, %f1
    tst_use(arg.a);
    tst_use(arg.b);
    tst_use(arg.c);
    tst_use(arg.d);
}

extern "C" {
    fn opaque_callee(arg: Franta, intarg: i32);
    fn tst_use(arg: f32);
}

// CHECK-LABEL: caller
// CHECK: ld [%i1], %f0
// CHECK: ld [%i2], %f1
// CHECK: ld [%i3], %f2
// CHECK: ld [%i0], %f3
// CHECK: call {{.*}}
// CHECK: mov     3, %o2
pub unsafe extern "C" fn caller() {
    opaque_callee(Franta { a: 1.0, b: 2.0, c: 3.0, d: 4.0 }, 3);
}
```

**Comment by nagisa** [comment]
I think it is fine if some tests change in output occasionally after a change as major as LLVM bump, so long as it is easy to tell that the test output did not become _wrong_. There are a couple ways to reduce the frequency of such changes too – first is using the highest optimization level available (`-Copt-level=3`), another is writing the `FileCheck` rules in such a way that the test is resilient to offsets on the stack changing, in some ways, for example. Adjusting the test to the following code makes me reasonably confident that maintaining this test won't be an issue. Here's what I came up with:

<details>
<summary>The code</summary>

```rust
// assembly-output: emit-asm
// needs-llvm-components: sparc
// compile-flags: --target=sparcv9-sun-solaris
#![crate_type = "lib"]
#![feature(no_core, lang_items)]
#![no_core]

#[lang = "sized"]
pub trait Sized {}
#[lang = "copy"]
pub trait Copy {}

#[repr(C)]
pub struct Franta {
    a: f32,
    b: f32,
    c: f32,
    d: f32,
}

// NB: due to delay slots the `ld` following the call is actually executed before the call.
#[no_mangle]
pub unsafe extern "C" fn callee(arg: Franta) {
    // CHECK-LABEL: callee:
    // CHECK: st %f3, [[PLACE_D:.*]]
    // CHECK: st %f2, [[PLACE_C:.*]]
    // CHECK: st %f1, [[PLACE_B:.*]]
    // CHECK: st %f0, [[PLACE_A:.*]]
    // CHECK: call tst_use
    // CHECK-NEXT: ld [[PLACE_A]], %f1
    // CHECK: call tst_use
    // CHECK-NEXT: ld [[PLACE_B]], %f1
    // CHECK: call tst_use
    // CHECK-NEXT: ld [[PLACE_C]], %f1
    // CHECK: call tst_use
    // CHECK-NEXT: ld [[PLACE_D]], %f1
    clobber();
    tst_use(arg.a);
    tst_use(arg.b);
    tst_use(arg.c);
    tst_use(arg.d);
}

extern "C" {
    fn opaque_callee(arg: Franta, intarg: i32);
    fn tst_use(arg: f32);
    fn clobber();
}

#[no_mangle]
pub unsafe extern "C" fn caller() {
    // CHECK-LABEL: caller:
    // CHECK: ld [{{.*}}], %f0
    // CHECK: ld [{{.*}}], %f1
    // CHECK: ld [{{.*}}], %f2
    // CHECK: ld [{{.*}}], %f3
    // CHECK: call opaque_callee
    // CHECK: mov     3, %o2
    opaque_callee(Franta { a: 1.0, b: 2.0, c: 3.0, d: 4.0 }, 3);
}
```

</details>

**Comment by nagisa** [comment]
Can you please squash the commits into 1 or 2 so that the commit history is meaningful once merged into the main branch?

**Comment by matthiaskrgr** [comment]
failed in a rollup: https://github.com/rust-lang/rust/pull/91232#issuecomment-979441451
@bors r-

**Comment by psumbera** [comment]
@nagisa no sure I follow what's happening now. Is there some real problem I should be looking at?

**Comment by bjorn3** [comment]
The codegen test failed on CI. It will need to be fixed. See https://github.com/rust-lang/rust/pull/91232#issuecomment-979441451 for the failure.

**Comment by psumbera** [comment]
If I see it right. The problematic test expects:

```define void @structfloatlongfloat_input(%FloatLongFloat* noalias nocapture dereferenceable(24) %a)```

but on test system it gets:

```define void @structfloatlongfloat_input(%FloatLongFloat* noalias nocapture readnone dereferenceable(24) %a)```

I wonder what ```readnone``` does mean and where it gets from. I don't see it on Solaris SPARC...

**Comment by nagisa** [comment]
`readnone` is likely introduced by an optimization pass and according to langref:

> On an argument, this attribute indicates that the function does not dereference that pointer argument, even though it may read or write the memory that the pointer points to if accessed through other pointers.

Specifying something like `-Cno-prepopulate-passes` for the codegen test might be the right approach here.

**Comment by psumbera** [comment]
I have removed last problematic test (where was the collision with ```readnone```). It seemed that ```-Cno-prepopulate-passes``` would add more complexity and previous tests would need to be rewritten (and became more complex).

**Comment by nagisa** [comment]
Hm, this is a confusing error given that we specifically specify the optimization level flag, but you could switch some of the `CHECK`s to `CHECK-DAG`s to permit the `st` instructions to appear in an arbitrary order.

**Comment by psumbera** [comment]
I have added `-Copt-level=3` as you have suggested earlier. I was able to reproduce the problem when I have added `-Copt-level=0`. Hopefully with level 3 on Linux test system we will get correct results...

**Comment by glaubitz** [comment]
@psumbera Thanks for fixing this!

**Pull request merged**
