### PR TITLE
submodules: update cargo

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
r? @ehuss 

I'd like to get https://github.com/rust-lang/cargo/pull/7768 into nightly.

**Comment by matthiaskrgr** [comment]
I've added a rls update to make sure the PR does not break rls toolstate.

**Comment by ehuss** [comment]
Thanks!

@bors r+

cc @Xanewok

**Comment by matthiaskrgr** [comment]
I've updated rls and cargo submodules again since looking at the queue, this is not going to merge very soon, and some more PRs/fixes were merged upstream...

**Comment by matthiaskrgr** [comment]
I guess I could update clippy as well while i'm at it, since it was just fixed...

**Comment by matthiaskrgr** [comment]
I've removed the rls update again since rls broke anyway and we need to wait for rustfmt to be fixed in order to get rls working again.

**Comment by ehuss** [comment]
I don't think it is a good idea to roll up clippy here.  Can you put that in a separate PR when it is ready?

**Comment by matthiaskrgr** [comment]
Right, I removed the clippy update as well.

**Comment by matthiaskrgr** [comment]
I added the dep to the list.

**Comment by ehuss** [comment]
I would prefer to not roll up clippy and cargo together.  Can you separate them into different PRs?

**Comment by calebcartwright** [comment]
I could be wrong (@topecongiro and @Xanewok would know definitively), but I think that the updates for rustfmt and rls need to be coordinated since they both have rustc-ap-* crates within their dependency trees, and I believe the versions of those crates need to be kept in sync. 

Rls currently has v610 (transitively via Racer) but rustfmt is, as of yesterday, on v642

**Comment by matthiaskrgr** [comment]
I removed everything but cargo again.
Looks like we need another couple of days before all tools are green again, sigh...

**Comment by matthiaskrgr** [comment]
looks spurious
```
2020-02-11T07:34:27.6435639Z test string::test_push_str ... ok
2020-02-11T07:34:27.6435988Z test string::test_replace_range ... ok
2020-02-11T07:34:27.6436223Z test string::test_replace_range_char_boundary ... ok
2020-02-11T07:34:27.6436420Z test string::test_replace_range_inclusive_out_of_bounds ... ok
2020-02-11T07:34:27.6436635Z test string::test_replace_range_inclusive_range ... ok
2020-02-11T07:34:27.6437157Z test string::test_replace_range_out_of_bounds ... ok
2020-02-11T07:34:27.6437501Z test string::test_replace_range_unbounded ... ok
2020-02-11T07:34:27.6437762Z test string::test_reserve_exact ... ok
2020-02-11T07:34:27.6438077Z test string::test_retain ... ok
2020-02-11T07:34:27.6438506Z test string::test_simple_types ... ok
2020-02-11T07:34:27.6438670Z test string::test_slicing ... ok
2020-02-11T07:34:27.6438999Z test string::test_split_off_ascii ... ok
2020-02-11T07:34:27.6439174Z test string::test_split_off_empty ... ok
2020-02-11T07:34:27.6439335Z test string::test_split_off_mid_char ... ok
2020-02-11T07:34:27.6439510Z test string::test_split_off_past_end ... ok
2020-02-11T07:34:27.6439897Z test string::test_split_off_unicode ... ok
2020-02-11T07:34:27.6440112Z test string::test_str_add ... ok
2020-02-11T07:34:27.6440286Z test string::test_str_clear ... ok
2020-02-11T07:34:27.6440440Z test string::test_str_truncate ... ok
2020-02-11T07:34:27.6440754Z test string::test_str_truncate_invalid_len ... ok
2020-02-11T07:34:27.6864408Z test string::test_replace_range_empty ... ok
2020-02-11T07:34:27.6865318Z test string::test_str_truncate_split_codepoint ... ok
2020-02-11T07:34:27.9561927Z died due to signal 11
2020-02-11T07:34:27.9563255Z error: test failed, to rerun pass '-p alloc --test collectionstests'
2020-02-11T07:34:27.9574706Z
2020-02-11T07:34:27.9575216Z
2020-02-11T07:34:27.9576649Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-Zconfig-profile" "--target" "arm-linux-androideabi" "-Zbinary-dep-depinfo" "-j" "2" "--release" "--locked" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/src/libtest/Cargo.toml" "-p" "alloc" "--"
2020-02-11T07:34:27.9576963Z expected success, got: exit code: 3
2020-02-11T07:34:27.9577105Z
2020-02-11T07:34:27.9577221Z
```

**Comment by mati865** [comment]
Possibly https://github.com/rust-lang/rust/issues/55861

**Comment by ehuss** [comment]
@bors retry
#55861

**Pull request merged**
