### PR TITLE
Move match_path from DefId to lint::LateContext

### PR DESCRIPTION
**Pull request by flip1995**
cc https://github.com/rust-lang/rust/pull/59316#discussion_r272351353

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
LGTM. r? @oli-obk or @Manishearth for where exactly to put it (I assume there may be more helper methods like this?)

**Comment by Centril** [comment]
@bors retry

Yielding prio to https://github.com/rust-lang/rust/pull/59724

**Pull request merged**
