### PR TITLE
Add note about change in bootstrap defaults

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Not a huge fan of the proposed wording, open to changes in that.

Per https://github.com/rust-lang/rust/pull/106886#issuecomment-1518325832.
cc @jonhoo 

r? @cuviper perhaps?

### CODE REVIEW

**Comment by cuviper** [comment]
Hmm, this seems like it would have bitten me, because I do list `tools` explicitly in Fedora, not including `rustdoc`, but it cam;e out of my builds just fine. So at the very least, I think there's some hole in "we will respect a missing rustdoc in that list." Just guessing, maybe that's because I also build docs, so it was already in the sysroot and then got picked up by the `cp_r(..."bin"...)`.

**Comment by Mark-Simulacrum** [comment]
Yeah, that seems plausible. It seems pretty likely that we'll build it implicitly in some cases but not others. I'm not sure how to better phrase this -- in general I think I would recommend that you and others _do_ explicitly add rustdoc to the tools list if you want it, since otherwise future iterations might e.g. error out saying "well, not asked for, refusing to build" or similar. (Particularly if/when we start looking into optimizing our CI, and e.g., cross-compiling parts from other builders or similar).

**Comment by jyn514** [comment]
I think a test failure like the one @jonhoo found is pretty bad, we should not have a supported configuration that fails tests. can we find some way for `x install` to *allow* disabling rustdoc, while still building it on demand if needed for doctests?

cc @dtolnay

**Comment by jyn514** [comment]
Ah wait I misunderstood, those are tests failing for some crate being built by the new toolchain, not for our own test suite.

Ok, that seems unavoidable if rustdoc's not installed. I think we can still have an easier transition though — @dtolnay would it be enough for `x install` to respect `--exclude src/tools/rustdoc`, without changing the default?

**Comment by Mark-Simulacrum** [comment]
I think the change in defaults is reasonable. Rustdoc is a tool, we have a list of tools, if you don't include it there you're signaling you don't need/want it.

**Comment by cuviper** [comment]
Rustdoc is a privileged tool though -- normally bundled with rustc rather than its own component. Distros keep them together too, at least on Debian and Fedora/RHEL, so I think it *will* be surprising to have to list it explicitly. Nevertheless, a compat note for what we already shipped seems appropriate, and I guess it doesn't matter if we nail down the specifics in that note.

@bors r+ rollup

**Pull request merged**
