### PR TITLE
Add root-path

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus 

cc @onur

I tested everything that came to my mind but I'm pretty sure I didn't think of a corner case where this feature could break. Any feedback/additional tests would be very appreciated. :)

### CODE REVIEW

**Comment by onur** [comment]
Hi @GuillaumeGomez, this is great, I haven't tested it yet but there are some issues:

1. This won't allow me to add a version subfix to commonly used files. It's still not compatible with theme picker. JavaScript portion of theme picker is only working with `dark.css` and `rustdoc.css`. That's the main reason why theme picker did break docs.rs. I have to add a rustc version to this files in order to keep compatibility between docs generated with the old versions of rustc.
2. `search-index.js` is usually different for each create, I am not moving it in docs.rs and keeping it in `doc/` directory of every crate.

I'll test it as soon as I find some time and return to you if I find anymore issue.

Your `--url` or `--replace` idea is actually exactly what I am looking for instead of generating this files in another location. But thanks to you I know where to look at for this feature now, maybe I can help with a solution.

**Comment by GuillaumeGomez** [comment]
Ok, writing a second PR which adds an `resource-suffic` option.

**Comment by shepmaster** [comment]
Ping from triage, @QuietMisdreavus !

**Comment by GuillaumeGomez** [comment]
I'll close this PR in favor of #48511.

**Pull request closed without merging**
