### PR TITLE
Use TLS to store a type context for pretty-printing types.

### PR DESCRIPTION
**Pull request by eddyb**
Pre-requisite for splitting the type context into global and local parts.
The `Repr` and `UserString` traits were also replaced by `Debug` and `Display`.

### CODE REVIEW

**Comment by huonw** [comment]
cc @rust-lang/compiler

**Comment by jroesch** [comment]
:+1:

**Comment by nikomatsakis** [comment]
wow, this is... pretty nice. r+ from me, modulo some comments:

- when `None` would be returned
- explain that the callback in 2445733 is there so we can ensure that the tcx is in tls

**Pull request merged**
