### PR TITLE
Update Miri

### LINKED ISSUE #80907: `miri` no longer builds after rust-lang/rust#80905
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#80905, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @JohnTitor, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by ghost**
Fixes #80907.

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
CI will fail with this, due to some further rustc changes -- I fixed the Miri side in https://github.com/rust-lang/miri/pull/1673; once that landed, can you update Miri here to the latest master commit?

**Comment by hyd-dev** [comment]
> CI will fail with this, due to some further rustc changes -- I fixed the Miri side in [rust-lang/miri#1673](https://github.com/rust-lang/miri/pull/1673); once that landed, can you update Miri here to the latest master commit?

OK. Sorry for missing the "further rustc changes".

**Comment by hyd-dev** [comment]
PR CI passed :rocket:

**Comment by RalfJung** [comment]
Thanks. :-)
@bors r+ p=1

**Pull request merged**
