### PR TITLE
Revert #111753

### PR DESCRIPTION
**Pull request by compiler-errors**
Reverts #111753, which was a perf regression. I had r+'d it but didn't catch that the perf results were negative.

r? @cjgillot

### CODE REVIEW

**Comment by cjgillot** [comment]
Uh... Is this a regression too?

**Comment by compiler-errors** [comment]
Maybe someone from @rust-lang/wg-compiler-performance can help tease out what's noise and what's a regression.

**Comment by Kobzol** [comment]
It looks like it did actually revert some of the benchmarks (tt-muncher, tuple-stress [this one was green before, but just slightly], html5-ever). The big `coercions` regression before was probably just noise, because the benchmark has been quite [noisy](https://perf.rust-lang.org/index.html?start=2023-07-02&end=866710c552e5a9b9ce6d0f8143ebe8d69f7dd451&benchmark=coercions&profile=debug&scenario=full&stat=instructions%3Au&kind=percentrelative) recently.

**Comment by cjgillot** [comment]
Should we close this PR, or do you still want to merge it?

**Comment by compiler-errors** [comment]
Seems like nobody particularly cares about this perf regression, so I'm gonna just close this.

**Pull request closed without merging**
