### PR TITLE
Unbreak the RLS

### PR DESCRIPTION
**Pull request by Xanewok**
Breakage was due to https://github.com/rust-lang/rust/pull/55937, which seems to have introduced a regression (tracked over at https://github.com/rust-lang/rust/issues/57280).
Clippy updates don't matter in-tree because we patch it with the in-tree version - https://github.com/rust-lang/rls/commit/085e9266e3336416cfa0dde2840a2c9afd6fef1c is the important change.

r? @nikomatsakis 

cc @nrc

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@Xanewok seems fine -- I expect we'll have a fix for the regression soon though. But I guess it makes sense to move forward anyway?

**Comment by Xanewok** [comment]
I think it doesn’t hurt to get this to unbreak the toolstate so there’s no pressure on the regression fix, but I have no idea - maybe it makes sense to wait, if the regression fix is important and will land soon!

**Comment by nikomatsakis** [comment]
Fix is in https://github.com/rust-lang/rust/pull/57304

**Comment by Xanewok** [comment]
Awesome, thanks! I’ll close this then, since the only thing this updates is working around this.

**Pull request closed without merging**
