### PR TITLE
 PGO: Add a run-make test that makes sure that PGO profiling data is used by the compiler during optimizations.

### PR DESCRIPTION
**Pull request by michaelwoerister**
From the tests comment section:
```
# This test makes sure that PGO profiling data leads to cold functions being
# marked as `cold` and hot functions with `inlinehint`.
# The test program contains an `if` were actual execution only ever takes the
# `else` branch. Accordingly, we expect the function that is never called to
# be marked as cold.
```

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

👍

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/60291#issuecomment-486895704, @bors r-

**Comment by michaelwoerister** [comment]
It looks like the `llvm-profdata` tool from LLVM's bin directory isn't found. I'm calling it via `$(LD_LIB_PATH_ENVVAR)=$(REAL_LD_LIBRARY_PATH) llvm-profdata`, replicating how it's done for similar calls (e.g. [here](https://github.com/rust-lang/rust/blob/3ee936378662bd2e74be951d6a7011a95a6bd84d/src/test/run-make-fulldeps/cross-lang-lto-clang/Makefile#L15)); but I don't really understand why this is necessary. Note that `$(LD_LIB_PATH_ENVVAR)` seems to expand to `PATH` and `$(REAL_LD_LIBRARY_PATH)` expands to an empty string, so it's not surprising that `llvm-profdata` can't be found with an empty path.

If I just call `llvm-profdata`, everything works fine (at least locally on Windows).

@Mark-Simulacrum, can you provide any insight here? Maybe we should not try to add the LLVM `bin` directory to the `PATH` and instead make `compiletest` define a `LLVM_BIN_DIR` env var that run-make tests can use?

**Comment by alexcrichton** [comment]
`LD_LIB_PATH_ENVVAR` is indeed PATH on windows yeah so that'd explain a lot :)

Adding something like `LLVM_BIN_DIR` should be fine to do and would probably be a good fix for this

**Comment by Mark-Simulacrum** [comment]
The intent of the PATH= was that otherwise we end up with stage0/bin in the path which causes these binaries to fail to run due to finding the libLLVM-*.so in that directory. In hindsight, I'm not sure how we were able to find llvm-objdump in the commit that added this (04679431a249570bb2ca6d5813ebb37db76cc9db). Maybe there's some defaults involved?

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, that test is only executed on a single Linux x86_64 because of the `#needs-matching-clang` directive. That probably explains it.

I'll look into an alternative solution for accessing LLVM tools from `run-make` tests.

**Comment by michaelwoerister** [comment]
I've changed things to not add LLVM's bin directory to the PATH and instead call tools directly from `run-make` tests. It seems to work for me locally but the only way to find out for other platforms is trying to merge, so I'm going ahead r+ it. If it goes through, we should take a look if there's further cleanup to do, @Mark-Simulacrum. 

@bors r=alexcrichton

**Comment by michaelwoerister** [comment]
Note: Do not add this to a rollup. It's quite possible that it fails.

**Comment by Mark-Simulacrum** [comment]
I suspect that this will fail; I believe we still need to clear out the PATH variable on Windows at least as otherwise it'll be inherited from Cargo and include stage0/bin. I could be wrong, though.

**Comment by michaelwoerister** [comment]
You expect llvm tools to load the wrong dylibs when executed?

**Comment by Mark-Simulacrum** [comment]
Yeah, that was the problem I was running into earlier, as the built-in rpath is read _after_ PATH/LD_LIBRARY_PATH, at least on Linux. I think the same is true on Windows/macOS. It might be that this is a non-issue some of the time because the LLVM library in beta (i.e., stage0/bin) is the same as the LLVM in master. Since we've somewhat recently beta-promoted that may well be the case.

**Comment by michaelwoerister** [comment]
> [01:28:47] ld.lld: error: Invalid summary version 6, 1, 2, 3 or 4 expected

OK, is suspect this error is because I removed LLD from the PATH. 

The `LD_LIBRARY_PATH` for the `rustc` invocation has `stage2/lib` before `stage0/lib`:
`LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/cross-lang-lto-clang/cross-lang-lto-clang:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib"`

**Comment by michaelwoerister** [comment]
Adding locally built LLD to the PATH of `run-make-fulldeps` tests specifically and trying again.
@bors r=alexcrichton

**Comment by michaelwoerister** [comment]
Seems like macOS doesn't have the `tac` command. But otherwise this looks pretty promising.

**Comment by michaelwoerister** [comment]
Try again with `tac` replacement for macOS:
@bors r=alexcrichton

**Comment by michaelwoerister** [comment]
Nice, it landed! 

@Mark-Simulacrum, do you know if there is any machinery left for doing the `REAL_LD_LIBRARY_PATH` work-around that might not be needed anymore?

Also, could you take a look if the solution implemented here is OK with you?

**Comment by Mark-Simulacrum** [comment]
It's possible there are still some bits around (a grep for REAL_LD_LIBRARY_PATH would be a good start, I think it shouldn't be needed).

I am however still at least somewhat confident that this change will not work if beta llvm doesn't sufficiently match the llvm on master (and same for beta/stable). I don't think we need to do anything about that right this minute: this PR is fine, indeed this looks better than what we had before.

**Pull request merged**
