### PR TITLE
Iterator::map_into method

### PR DESCRIPTION
**Pull request by vorner**
An iterator adaptor that passes each element through an `Into`
conversion.

I originally proposed this to the `IterTools` crate, but was asked to propose it here first (https://github.com/bluss/rust-itertools/pull/288) and that it wouldn't probably need an RFC. I'm not completely sure this feature is interesting/wanted enough to go into the standard library, but I'm OK with someone else making the decision, so here it goes.

However, I'm unsure about some things:

* The compiler mandates the stability attributes. I just made some up, as there's no RFC and no tracking issue for this ‒ is that OK?
* Even in the edited files the style differs from structure to structure a bit. I used something close to what rustfmt does now, but it probably introduces yet another variation of the style.
* Is the one little doc-test enough, or should I create some more?

If it is deemed useful and should go in, I'll happily provide some more examples and tests if needed.

### CODE REVIEW

**Comment by cuviper** [comment]
> The compiler mandates the stability attributes. I just made some up, as there's no RFC and no tracking issue for this ‒ is that OK?

If it's accepted, then you can just file a tracking issue and update the PR with that before it's merged.

**Comment by Mark-Simulacrum** [comment]
I'm personally not quite sure of the use case. `.map(|e| e.into())` or `.map(Into::into)` is not that much more verbose. It's also somewhat of a pattern I'd prefer to discourage due to the likelihood for either confusion or type inference breakage as impls are added...

**Comment by vorner** [comment]
> I'm personally not quite sure of the use case. .map(|e| e.into()) or .map(Into::into) is not that much more verbose. It's also somewhat of a pattern I'd prefer to discourage due to the likelihood for either confusion or type inference breakage as impls are added...

My motivation for this is that I often need to do some kind of slight type correction. This sounded similar to `.cloned()` ‒ just a convenience shortcut (one could argue that typing `.map(Clone::clone)` is not much verbose either). I'm not really afraid of the type inference breakage ‒ I usually add such step whenever the compiler already complains about types, so both producing type in the iterator and consuming type in the next step is already fixed.

But as I said, I'd fully understand if it was decided this has no place in std.

**Comment by clarcharr** [comment]
I also agree that `map(Into::into)` is more clear, and that this isn't really necessary. Additionally, you can do `map(T::from)` to help inference, and I'd argue that something like `map(String::from)` to convert `str` to `String` is a bit better and cleaner than `map_into()` with a type annotation.

**Comment by dtolnay** [comment]
I agree with @Mark-Simulacrum in https://github.com/rust-lang/rust/pull/51787#issuecomment-400097259 that `map(Into::into)` covers this use case well enough. I can see how `map_into()` or `map_into::<T>()` are convenient but I think people will be better off sticking with composable `map` / `Into::into` / `T::from` rather than learning `map_into` as a separate API. Thanks anyway!

**Pull request closed without merging**
