### PR TITLE
Fix repr pretty display

### LINKED ISSUE #70027: rustdoc has incorrect spacing for `repr` attributes
See https://github.com/rust-lang/rust/pull/69686/files#diff-21534ccecd1da87ab2d0cbabae0ca694R19 for an example.
```rust
#[repr(C, align (8))]
```
There should not be a space between `align` and the opening parenthesis.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #70027.

r? @varkor

### CODE REVIEW

**Comment by petrochenkov** [comment]
We need to take two tokens into consideration if we want to pretty-print token streams in a nicer way.
`(...)` doesn't always join with the previous token, e.g. in any arithmetic expressions it doesn't.
```rust
1 + (2 + 3)
```

**Comment by GuillaumeGomez** [comment]
I can check if the previous one is an ident (which would make sense). What do you think?

**Comment by GuillaumeGomez** [comment]
I updated it as suggested: I don't prepend a whitespace in case the previous token is an ident.

**Comment by petrochenkov** [comment]
r=me with squashed commits and green CI.

**Pull request merged**
