### PR TITLE
Protect crate metadata from corruption via SHA-256 hash

### PR DESCRIPTION
**Pull request by Aaron1011**
We now compute a SHA-256 of the raw (encoded) crate metadata,
and append it to the final crate metadata that we store on disk.
When we load the metadata, we compute the hash from the metadata
blob, and verify that matches the hash stored at the end of the
blob.

This allows us to detect on-disk corruption of the metadata file,
which might later cause a build failure much later in compilation.

If anyone is manually editing crate metadata on-disk,
they will need to re-compute and modify the hash at
the end of the blob.

This will allow us to determine whether or not crate metadata
corruption is causing some of the unusual incr-comp failures
we've been seeing. The incremental compilation data itself
will be hashed in a follow-up PR.

### CODE REVIEW

**Comment by cjgillot** [comment]
I am not really convinced why we need to do that, and in which cases this feature would be useful.
Should there be a way to activate this check, with a -Z option for instance?
Is the perf regression due to the initial hash computation or to the hash checking?
Can it be mitigated somehow?

**Comment by bjorn3** [comment]
Maybe use a faster non-cryptographically secure hash or maybe even just a crc or other kind of checksum?

> Is the perf regression due to the initial hash computation or to the hash checking?

Hash checking mostly. Probably because previously the crate metadata was lazily loaded. Now it has to be eagerly loaded for the hash check.

**Comment by michaelwoerister** [comment]
https://github.com/BLAKE3-team/BLAKE3 might be interesting for something like this. 
Also sccache has some interesting notes on performance: https://github.com/mozilla/sccache/blob/3f318a8675e4c3de4f5e8ab2d086189f2ae5f5cf/src/util.rs#L70-L83

**Comment by JohnCSimon** [comment]
Triage: 
@Aaron1011 what's the status of this PR? It's sat idle for months

**Comment by JohnCSimon** [comment]
@Aaron1011 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
