### PR TITLE
stage0 bootstrap bump

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @pietroalbini

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Also included RLS bump -- forward-porting from the beta change.

**Comment by Urgau** [comment]
When I run the stage0/cargo with this PR I'm seeing a version of `1.61.beta.7`, is that expected ? I would have expected the beta `1.62.*` something not `1.61`.
```
$ ./build/x86_64-unknown-linux-gnu/stage0/bin/cargo -V
cargo 1.61.0-beta.7 (a028ae4 2022-04-29)
```

**Comment by Mark-Simulacrum** [comment]
Hm, it might be that I didn't wait long enough for the beta to be pushed up. We'll want another bump anyway to pick up beta built with released stable, so I'll open another PR if necessary. We might want to list the version number, not just date, in the stage0.json to make this easier to catch.

**Pull request merged**
