### PR TITLE
rustfmt liballoc folder

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup

**Comment by srinivasreddy** [comment]
It is a Permission Denied error. Shall we need to retry? @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Yes we should.

@bors: retry

**Comment by GuillaumeGomez** [comment]
No, it's an external issue. We'll wait it's solved before retry.

**Comment by GuillaumeGomez** [comment]
@ bors: r+ rollup

**Pull request merged**
