### PR TITLE
Always quote program name in Command::spawn on Windows

### PR DESCRIPTION
**Pull request by ollie27**
[`CreateProcess`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425.aspx) will interpret args as part of the binary name if it
doesn't find the binary using just the unquoted name. For example if
`foo.exe` doesn't exist, `Command::new("foo").arg("bar").spawn()` will
try to launch `foo bar.exe` which is clearly not desired.

### CODE REVIEW

**Comment by retep998** [comment]
Alternatively, we could pass the binary name as the first parameter to `CreateProcessW` instead of having Windows be forced to dig it out of the second parameter.

**Comment by alexcrichton** [comment]
Looks good to me, thanks @ollie27! Would it be possible to add a test for this?

Passing the binary name explicitly sounds fine as well, so it sounds like we should just do both things?

**Comment by ollie27** [comment]
It looks like using the first parameter behaves very differently:

> In the case of a partial name, the function uses the current drive and current directory to complete the specification. The function will not use the search path. This parameter must include the file name extension; no default extension is assumed.

I guess I'll try to write a run-make test for this.

**Comment by ollie27** [comment]
Right, I've added a run-make test.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @ollie27!

**Comment by retep998** [comment]
So uh, I just did a quick test and when I passed a verbatim path as the *first* parameter to `CreateProcessW` I was able to specify paths that exceeded `MAX_PATH` while when I only specified the second parameter it would fail with `ERROR_FILENAME_EXCED_RANGE`. So even though using the first parameter has fairly different semantics than only using the second parameter, if we ever want to support long paths we'll need to use that first parameter.

**Pull request merged**
