### PR TITLE
rustdoc: stop space-splitting --test-args

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
The libtest harness allows you to filter out tests by specifying their name (or a substring) as arguments. Rustdoc allows you to specify arguments to the libtest main function via the `--test-args` argument, which can either be specified manually with `RUSTDOCFLAGS`/`cargo rustdoc` or is filled in automatically from loose arguments to `cargo test`. Rustdoc handles multiple `--test-args` arguments and stores them up to create the `args` list for the libtest runner.

However, it also whitespace-splits individual arguments to break them up, which causes problems because doctests have spaces in their names. You can't supply the full name to a test, because rustdoc will break up the name and supply it as multiple arguments. [And the test runner only takes the first filter argument when comparing against tests!](https://github.com/rust-lang/rust/blob/8c6fb028ca887dff9ec2fe0a90398b6d5bf5fb45/src/libtest/lib.rs#L557-L561) You're out of luck if you want to try to filter out all but one doctest, if another one lives on the same item.

This PR gives a fairly simple solution to the problem: Stop breaking up `--test-args`. The most common application of providing arguments to `--test-args` is via `cargo test`, which will already have properly parsed out arguments and provide them as separate `--test-args` arguments.

This has the possibility of breaking anyone who manually specified multiple arguments to `--test-args` in a single argument. I don't know if this practice was widespread, but it may be worth figuring out, since this is a change of behavior for a stable CLI flag.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It seems a bit awkward to call the parameter "args" and then only interpret it as one argument. Maybe we could leave the space-splitting behavior and add a new argument, `--test-arg`? I would personally be okay with it being insta-stable and updating Cargo to pass it immediately as such.

**Comment by malbarbo** [comment]
See a discussion in https://github.com/rust-lang/rust/issues/39789

**Comment by Mark-Simulacrum** [comment]
There appears to be no relevant discussion on that issue, beyond the mention of shlex by me -- but I tend to think `--test-arg` is better myself.

**Comment by GuillaumeGomez** [comment]
Looks good to me as is but since there seems to still have some debates so I'll wait a bit for the moment.

**Comment by QuietMisdreavus** [comment]
Seems like adding a new `--test-arg` flag and giving it this behavior is the best solution. Seeing both in documentation might be awkward, but with the right framing it could be fine.

cc @rust-lang/cargo since simulacrum suggested updating Cargo's behavior.

I'm a bit hesitant to make any new flag insta-stable, but maybe we can go one release cycle unstable, then stabilize it and switch Cargo's behavior then? I'm just wary about making sure our implementation is correct.

I'm curious what would be the best approach if both `--test-args` and `--test-arg` are seen on the same command-line? I don't think we can see what order they came in, so attempting to interleave them feels a bit too cumbersome. Ultimately, i don't think the final order that we hand to the test harness matters, *except* for situations where more than one "test filter" argument would be parsed out of the list. The way i see it, the most straightforward options are either (1) order one before the other in the final command-line, or (2) stop with an error if both are given. The first option could make things awkward, and the second could make handing arguments via `cargo test` difficult before Cargo switches over. Thoughts?

**Comment by czipperz** [comment]
What happened to the high-five bot?  Usually it's the first comment.  In any case this should be given a label `waiting-on-review` right?

**Comment by alexcrichton** [comment]
I think this is likely too much of a breaking change to land, but this was proposed to be fixed in rustc at some point for `-C link-args` by adding `-C link-arg`. (note the lack of `s` at the end). Could that be done here? Instead of reinterpreting `--test-args` could `--test-arg` be added which isn't space split?

**Comment by QuietMisdreavus** [comment]
@alexcrichton The `--test-arg` option was suggested by @Mark-Simulacrum [earlier in the thread](https://github.com/rust-lang/rust/pull/62341#issuecomment-508156692), haha. That does seem like the best option.

**Comment by gagan0723** [comment]
ping from triage, @QuietMisdreavus any updates on this?

**Comment by chocol4te** [comment]
Hello! Second ping from triage, @QuietMisdreavus please feel free to reopen when you have the time (Also note that pushing to the PR while it is closed prevents it from being reopened).

@rustbot modify labels to +S-inactive-closed, -S-waiting-on-author

**Pull request closed without merging**
