### PR TITLE
Sort auto trait and blanket implementations display

### LINKED ISSUE #63042: [docs] auto impl trait should be sorted
That'd make tests more accurate.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #63042

r? @kinnison

### CODE REVIEW

**Comment by kinnison** [comment]
@GuillaumeGomez Is there a useful way to add a test for this?

**Comment by GuillaumeGomez** [comment]
We could through the UI tests. Still kinda blocked for the moment until highfive is fixed...

**Review by kinnison — APPROVED** [review]
I can confirm that the code seems to provide sorted auto-trait and blanket impls.

I'm not fond of the `crate fn foo()` syntax, though I appreciate it's the style in the code at the moment, it'd be nice if new code were `pub(crate) fn foo()` in future.  No need to change things on this PR though.

**Pull request merged**
