### PR TITLE
[beta] Bump bootstrap compiler

### PR DESCRIPTION
**Pull request by emilyalbini**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Aaron1011** [comment]
There are a couple of `#[cfg(bootstrap)]` attributes that aren't removed by this PR:

https://github.com/rust-lang/rust/blob/5fb3394cbdf0622c9d0c292feb55db0f4c828dc3/library/core/src/macros/mod.rs#L854-L863

https://github.com/rust-lang/rust/blob/5fb3394cbdf0622c9d0c292feb55db0f4c828dc3/library/core/src/array/equality.rs#L128-L131

**Comment by Mark-Simulacrum** [comment]
This is for the beta branch - it shouldn't be changing cfg(bootstrap) at all. I presume a followup bump on master will happen soon.

**Comment by pietroalbini** [comment]
Yeah I plan to do the master bump tomorrow.

**Pull request merged**
