### PR TITLE
testcase about issue-18088

### PR DESCRIPTION
**Pull request by ParkHanbum**
this testcase is associated with issue #18088 . you can find that here. https://github.com/rust-lang/rust/issues/18088.

### CODE REVIEW

**Comment by TimNN** [comment]
Can you add the license text to the top of the file:

```rust
// Copyright 2016 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.
```

**Comment by die4taoam** [comment]
understand. I'll do my best.

**Comment by TimNN** [comment]
Awesome, thank you very much! 

This looks almost good now, can you squash all those commits down into one and (force) push that? If you need any help with that feel free to ask here or on [irc](https://www.rust-lang.org/en-US/community.html#irc-channels).

**Comment by ParkHanbum** [comment]
@TimNN  Pushed. thank you!

**Comment by TimNN** [comment]
This looks good now, thank you!

Someone from the Rust Team with the required privileges will soon review (and likely approve) this PR, afterwards the PR will be [queued](https://buildbot.rust-lang.org/homu/queue/rust) to be tested and then finally merged.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
