### PR TITLE
Stabilize `slice::repeat` (feature `repeat_generic_slice`)

### LINKED ISSUE #48784: `repeat` method for (byte) slices?
There exists a [`str::repeat`](https://doc.rust-lang.org/std/primitive.str.html#method.repeat) method, but no equivalent for (byte) slices. This would seem like a useful feature. Should we consider adding it to the stdlib?

### PR DESCRIPTION
**Pull request by tesuji**
Closes #48784
r? @SimonSapin

### CODE REVIEW

**Comment by SimonSapin** [comment]
Signature:

```rust
impl<T> [T] {
    pub fn repeat(&self, n: usize) -> Vec<T> where T: Copy {…}
}
```

Would we want to add a variation of this with `Clone` instead of `Copy`? If so what would the naming scheme be?

@rfcbot fcp merge

**Comment by sfackler** [comment]
I think we'd just have a single method with internal specialization for T: Copy.

**Comment by SimonSapin** [comment]
In that case the signature to stabilize is not this one.

**Comment by SimonSapin** [comment]
Oh never mind, I forgot that `Clone: Copy` so it should be fine to extend this later.

**Comment by yodaldevoid** [comment]
@SimonSapin Did you mean to say `Copy: Clone`?

**Comment by lzutao** [comment]
I have one question: Can we make it like Python [`itertools::cycle`][1] function? 
Which mean this `slice::repeat` function could return an iterator instead?
Should we rename it to `slice::cycle` instead?

[1]: https://docs.python.org/3/library/itertools.html#itertools.cycle

**Comment by SimonSapin** [comment]
@yodaldevoid Err, yes

**Comment by SimonSapin** [comment]
@lzutao We already have a `cycle` method on all iterators that implement `Clone` (which includes `slice::Iter`), though that one returns an infinite iterator.

**Pull request merged**
