### PR TITLE
Rollup of 21 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #73566 (Don't run `everybody_loops` for rustdoc; instead ignore resolution errors)
 - #73771 (Don't pollute docs/suggestions with libstd deps)
 - #73794 (Small cleanup for E0705 explanation)
 - #73807 (rustdoc: glue tokens before highlighting)
 - #73835 (Clean up E0710 explanation)
 - #73926 (Ignoring test case: [codegen] repr-transparent-aggregates-1.rs for aarch64)
 - #73981 (Remove some `ignore-stage1` annotations.)
 - #73998 (add regression test for #61216)
 - #74140 (Make hir ProjectionKind more precise)
 - #74148 (Move #[doc(alias)] check in rustc)
 - #74159 (forbid generic params in the type of const params)
 - #74171 (Fix 44056 test with debug on macos.)
 - #74221 (Don't panic if the lhs of a div by zero is not statically known)
 - #74325 (Focus on the current file in the source file sidebar)
 - #74359 (rustdoc: Rename internal API fns to `into_string`)
 - #74370 (Reintroduce spotlight / "important traits" feature)
 - #74390 (Fix typo in std::mem::transmute documentation)
 - #74391 (BtreeMap: superficially refactor root access)
 - #74392 (const generics triage)
 - #74397 (Fix typo in the latest release note)
 - #74406 (Set shell for github actions CI)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by jyn514** [comment]
Looks like the cargo test suite?
```
 failures:

---- build::close_output stdout ----
thread 'build::close_output' panicked at 'assertion failed: !status.success()', src/tools/cargo/tests/testsuite/build.rs:5016:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    build::close_output
```

**Comment by Manishearth** [comment]
I recall seeing that failure before!

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/74312#issuecomment-657964827

**Comment by Manishearth** [comment]
@bors retry

might be an intermittent, no common PRs

**Comment by jyn514** [comment]
Should we let the cargo team know?

**Comment by jyn514** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Intermittent.20test.20failures.20cause.20rollups.20to.20fail

**Comment by Manishearth** [comment]
Yes, once we've determined it's actually an intermittent

**Pull request merged**
