### PR TITLE
Move some tests to more reasonable directories - 1

### PR DESCRIPTION
**Pull request by c410-f3r**
The idea is to move `issues`/`ui` tests in small batches

r? @petrochenkov

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks good to me 👍

**Comment by petrochenkov** [comment]
cc https://github.com/rust-lang/rust/issues/73494

**Comment by petrochenkov** [comment]
@c410-f3r 
Have you tried to use the classifier tool, or its pre-collected results from https://github.com/rust-lang/rust/issues/73494#issuecomment-754293733?
I think it generally makes sense to start with tests with the highest confidence scores (>1, then >0), then we'll be able to re-train the classifier to get slightly better results for the remaining tests.

**Comment by petrochenkov** [comment]
Regarding specific changes:
- looks like `issue-10031.rs` isn't testing anything useful now and can be removed (or it can be moved to `structs` perhaps) (also the `cross-crate` subdirectory is pointless, we should move its contents to other directories)
- moving `issue-10200.rs` to `parser` is a mistake, I'd put it to `resolve` (even it's not the original purpose of the test)
- otherwise LGTM

**Comment by c410-f3r** [comment]
> @c410-f3r
Have you tried to use the classifier tool, or its pre-collected results from #73494 (comment)?
I think it generally makes sense to start with tests with the highest confidence scores (>1, then >0), then we'll be able to re-train the classifier to get slightly better results for the remaining tests.

I started the pre-collected list in a sequential order but yeah, starting with high confidence scores is indeed a better approach. Thanks!

> Regarding specific changes:
...
 
All suggested changes were made and more tests will be added in the following PR

**Comment by petrochenkov** [comment]
Thanks!
r=me after squashing commits.

**Comment by petrochenkov** [comment]
@c410-f3r 
I've regenerated the test list, now it's sorted by confidence scores.

@bors r+

**Pull request merged**
