### PR TITLE
[WIP] Always use `EvaluatedToOkModuloRegions` instead of `EvaluatedToOk`

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Aaron1011** [comment]
REgressions up to 33%, with many benchmarks regressing 1-10%

**Comment by dhardy** [comment]
The 33% regression is a doc build I think; I count 10 cases over 3% and 27 cases over 1%.

So not ideal but still far better than the barely usable mess nightly is at the moment?

**Comment by Aaron1011** [comment]
Superseded by https://github.com/rust-lang/rust/pull/85186

**Pull request closed without merging**
