### PR TITLE
Change description of no-stack-check (#34915)

### PR DESCRIPTION
**Pull request by abhijeetbhagat**
Original issue : #34915
Change explanation: #35027

### CODE REVIEW

**Comment by brson** [comment]
@abhijeetbhagat In addition to changing the help text as you've done here, can you also make it print that text as a warning, when the user passes it to the compiler? It looks to me like the right place to do it is somewhere in [`librustc_driver::handle_options`](https://github.com/abhijeetbhagat/rust/blob/24a2653e57871a9dd7afde9090425ef22285d147/src/librustc_driver/lib.rs#L927).

**Comment by abhijeetbhagat** [comment]
I am on it.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Pull request closed without merging**
