### PR TITLE
Don't ask for a specific branch in cargotest

### PR DESCRIPTION
**Pull request by lnicola**
Tentative fix for https://github.com/rust-lang/rust/pull/118592#issuecomment-1838180918.

`servo` [just renamed](https://github.com/servo/servo/pull/30788) their `master` branch to `main`, but `cargotest` does a `git fetch $URL master; git reset --hard $SHA`. Let's try to change that to `git fetch $URL $SHA; git reset --hard $SHA`, which appears to work, but I can't confirm for sure because I'm having some trouble with `x.py`:

```
 --> library/rustc-std-workspace-core/lib.rs:4:9
  |
4 | pub use core::*;
  |         ^^^^
  |
  = note: the following crate versions were found:
          crate `core` compiled by rustc 1.76.0-nightly (85a4bd8f5 2023-12-04): ./build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/libcore-70719e8645e6f000.rmeta
  = help: please recompile that crate using this compiler (rustc 1.76.0-nightly (5808b7248 2023-12-04)) (consider running `cargo clean` first)
```

### CODE REVIEW

**Comment by compiler-errors** [comment]
pls update description :)

**Review by onur-ozkan — COMMENTED** [review]
Removing hard-coded branch name seems good to me. However, you still need to bump the commit sha of servo as it no longer exists.

Copied from CI logs
```
Initialized empty Git repository in /checkout/obj/build/ct/servo/.git/
fatal: Could not parse object '785a344e32db58d4e631fd3cae17fd1f29a721ab'.
fatal: couldn't find remote ref master
```

**Comment by onur-ozkan** [comment]
> No, the commit exists:
> 
> ```
> commit 785a344e32db58d4e631fd3cae17fd1f29a721ab (HEAD -> master)
> Author: Anthony Ramine <nox@nox.paris>
> Date:   Wed Oct 16 14:07:39 2019 +0200
> 
>     Update rand to 0.7 (fixes #24448)
> ```
> 
> (also at https://github.com/servo/servo/tree/785a344e32db58d4e631fd3cae17fd1f29a721ab)
> 
> It's `master` that no longer does. I don't understand why it ends up showing that error.

I get it now. From the following code  we try to do hard-reset to specific commit hash, and in the initial iteration we haven't fetched the `servo` yet. This results in the mentioned error. 

I don't know why `fn clone_repo` had to be that complicated.

**Review by onur-ozkan — APPROVED** [review]

**Pull request merged**
