### PR TITLE
Implemented Add<char> for String

### PR DESCRIPTION
**Pull request by gsingh93**

### CODE REVIEW

**Comment by gsingh93** [comment]
I don't see why we shouldn't be able to add `char`s to `String`s.

**Comment by tbu-** [comment]
Because the current style of operator implementations is `(collection + collection)`, not `(collection + element)`.

**Comment by gsingh93** [comment]
@tbu- Sure, that might be the current style, it's not necessary the right style. Appending a character to a string with `+` seems like a very intuitive operation to me.

**Comment by tbu-** [comment]
@gsingh93 I feel like consistency is a big factor here. It doesn't work well with collections other than string, so I think providing it for `String` would be just inconsistent and surprising. There's already `push_char` to add a character.

On other collections it's hard to implement because of ambiguities:

     let vector: Vec<Vec<u16>>;
     vector + vec![]

Now, does that add an empty vector as an element or does that concatenate the two vectors?

**Comment by gsingh93** [comment]
While a string might be a collection of characters, I don't necessarily always think of it like one. There's a reason I don't just use `Vec<char>` and we have a special type for a `String`. Appending a character to a string with `+` seems more intuitive than appending it for other collections. I don't think the amount of inconsistency is big enough to warrant not adding this.

And if already having the method `push` for appending characters is a sufficient reason to not do this, then already having `push_str` is a sufficient reason to not implement `Add` at all, which would be fairly inconvenient.

**Comment by tbu-** [comment]
The reason for having the special type `String` next to `Vec<char>` is storage requirements: We store the string as UTF-8 (`String`) as opposed to UTF-32 (`Vec<char>`).

**Comment by gsingh93** [comment]
I see. Regardless of the technical reasons, I see `String` as a unique data type, and part of this data types interface is appending characters with `+`, which I don't see as necessarily part of the interface of other collection types.

**Comment by reem** [comment]
Strong -1 from me. This feels like a classic abuse of operator overloading. We have a `push` method, it isn't hard to use or unergonomic. Trying to save a few characters by overloading + is both less flexible (since it requires ownership of the String rather than an &mut String) and unnecessary given the presence of push.

**Comment by gsingh93** [comment]
Again, using `push_str` isn't hard to use or unergonomic either, but overloading `+` is more convenient. I understand the desire to not abuse operator overloading, but I believe this is a proper use of it.

**Comment by gsingh93** [comment]
I still strongly believe this is a good feature to have, but based on the comments so far it doesn't look like this has much support. @aturon, can you comment and merge or close this?

**Comment by aturon** [comment]
Sorry for the delay in looking at this.

I'm personally not opposed to this kind of API; I consider it to fit reasonably well with our existing uses of operator overloading.

However, I'd prefer to take this step in a broader way -- like @tbu-, I worry that we will not be able to provide a similar implementation for `Vec`, and the inconsistency would be unfortunate. There are also some intentions, if not concrete plans, to allow operators like `+=` to be overloaded (which is, I think the intended use here). I want to make sure we have a story that can fit all of these things together.

@gsingh93, would you be interested in writing a broader RFC that could discuss some of the above issues (or even propose to add `+=` and friends)? I'd be glad to help guide the effort.

**Comment by gsingh93** [comment]
@aturon I've never written an RFC before, but I'll give it a shot. I'll let you know when I have something concrete written down.

**Comment by aturon** [comment]
@gsingh93 Great! Feel free to ping me on IRC. I'm going to close this PR for the time being.

**Pull request closed without merging**
