### PR TITLE
Fix move checking for nested union fields

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/41126
r? @arielb1

### CODE REVIEW

**Comment by arielb1** [comment]
I'll rather r? @pnkfelix - he best understands the borrow checker.

**Comment by petrochenkov** [comment]
@arielb1 
>BTW, do we have an rpass test that shows what patterns are acceptable?

There are few tests, but they are mostly "compile-pass" style tests:
https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/borrowck/borrowck-union-borrow-nested.rs
https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/borrowck/borrowck-union-borrow.rs
https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/borrowck/borrowck-union-move-assign.rs
https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/borrowck/borrowck-union-move.rs
https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/borrowck/borrowck-union-uninitialized.rs (this one is a FIXME test)
https://github.com/rust-lang/rust/blob/master/src/test/run-pass/union/union-drop-assign.rs
https://github.com/rust-lang/rust/blob/master/src/test/run-pass/union/union-overwrite.rs

I didn't add many runtime tests for *partial* moves in the original PR due to [issues](https://github.com/rust-lang/rust/issues/36246) with dynamic drop flags that I couldn't fix quickly.

**Comment by pnkfelix** [comment]
This looks fine, in the sense that it is a natural extension of the logic that was previously implemented.

So I'm going to r+, but I also agree with [@arielb1's comment](https://github.com/rust-lang/rust/issues/41126#issuecomment-292715586) that we may want to revisit the rules regarding how borrows and unions interact.

**Pull request merged**
