### PR TITLE
CI run of code that triggers #105573

### PR DESCRIPTION
**Pull request by peter-lyons-kehl**
This PR is NOT a fix for #105573. Instead, it uses Rust CI to build code that triggered #105573 for me locally. (As per https://rustc-dev-guide.rust-lang.org/contributing.html#ci: "perfectly fine (and even encouraged!) to use the CI to test your changes if it can help your productivity").

Please don't review this PR. If possible, assign it back to me, or label it somehow so it won't waste time of reviewers.
Thank you in advance.

r? peter-kehl

### CODE REVIEW

**Comment by JakobDegen** [comment]
Fyi, `r? ghost` will prevent the PR from being assigned to anyone, and you can mark it as a draft to make it more obvious what it's for

**Comment by Dylan-DPC** [comment]
r? ghost

**Comment by peter-kehl** [comment]
Closing this PR. I'll create a new one, as draft.

**Pull request closed without merging**
