### PR TITLE
Stabilize `is_none_or`

### LINKED ISSUE #126383: Tracking Issue for is_none_or
Feature gate: `#![feature(is_none_or)]`

This is a tracking issue for `Option::is_none_or`.

### Public API

```rust
impl<T> Option<T> {
    pub fn is_none_or(self, f: impl FnOnce(T) -> bool) -> bool {
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/212
- [x] Implementation: https://github.com/rust-lang/rust/pull/126328
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by slanterns**
Closes: https://github.com/rust-lang/rust/issues/126383.

@rustbot label: +T-libs-api

r? libs-api

### CODE REVIEW

**Review by lnicola — CHANGES_REQUESTED** [review]
Note that r-a still has to build on 1.80 and maybe a couple of older versions, so we can't start using `is_none_or` right now.

**Comment by slanterns** [comment]
Right, I removed the changes on r-a.

**Comment by lnicola** [comment]
I guess you'll need to change `https://github.com/lnicola/rust-analyzer/blob/e37df4cd240d1bebbd61a0d2b5468ae7719a08c0/crates/hir-ty/src/display.rs#L1465` to `IsNoneOr::is_none_or(default_parameters.get(i), ...)`.

**Comment by slanterns** [comment]
Yeah, we should force it to use `IsNoneOr::is_none_or`, otherwise it will prioritize the inherent implementation after the stabilization 🙂.

**Review by dtolnay — APPROVED** [review]
Thank you!

**Comment by RalfJung** [comment]
This is already merged but still shows up in the bors queue?
@bors r-

**Comment by apiraino** [comment]
Unsure if this is the correct procedure but I'll label this to be mentioned in the release notes since #130575

@rustbot label +relnotes

**Pull request merged**
