### PR TITLE
Improve doc for `Result::unwrap()`

### PR DESCRIPTION
**Pull request by bombless**
Get rid of the confusion that what does "custom" mean in this context.

### CODE REVIEW

**Comment by bombless** [comment]
Ah, my fault, I think @alexcrichton would be more familiar with this code.
r? @alexcrichton

**Comment by bombless** [comment]
I just switched to the wrong PR, I was intended to change the reviewer of another PR :(
nvm

Former commit broke the 80-characters rule, fixed.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
