### PR TITLE
Make rustdoc respect `--error-format short` in doctests

### LINKED ISSUE #81662: Rustdoc does not obey --error-format for doctests error messages
I tried this code:

```rust
/// ```rust
/// foo();
/// ```
fn foo() {
    println!("Hello, world!");
}
```

I expected to see this happen: Running `cargo test --doc --message-format=short` uses short messages for all errors

Instead, this happened: The build failure for the doc test emits full error messages:

```console
> cargo test --doc --message-format=short
   Compiling foo v0.1.0 (/tmp/tmp.RZdiSTk0tC/foo)
src/lib.rs:4:4: warning: function is never used: `foo`
warning: 1 warning emitted
    Finished test [unoptimized + debuginfo] target(s) in 0.11s
   Doc-tests foo

running 1 test
test src/lib.rs - foo (line 1) ... FAILED

failures:

---- src/lib.rs - foo (line 1) stdout ----
error[E0423]: expected function, found crate `foo`
 --> src/lib.rs:2:1
  |
4 | foo();
  | ^^^ not a function

error: aborting due to previous error

For more information about this error, try `rustc --explain E0423`.
Couldn't compile the test.

failures:
    src/lib.rs - foo (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass '--doc'
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (0f6f2d681 2020-12-06)
binary: rustc
commit-hash: 0f6f2d681b39c5f95459cd09cb936b6ceb27cd82
commit-date: 2020-12-06
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### PR DESCRIPTION
**Pull request by poliorcetics**
Note that this will not work with `cargo test`, only with `rustdoc --test`, I'll have to modify `cargo` as well.

Fix #81662.

@rustbot label +T-rustdoc +A-doctests

### CODE REVIEW

**Comment by jyn514** [comment]
Can you add a UI test for this in src/test/rustdoc-ui?

**Comment by jyn514** [comment]
r=me with CI passing (please use `r=jyn514` instead of r+)

@bors delegate=poliorcetics

**Comment by poliorcetics** [comment]
Should it be rolled up ?

**Comment by jyn514** [comment]
I don't think it should be marked rollup=always, no, since it has logic changes. It can still get rolled up if someone chooses to.

@bors r+

**Pull request merged**
