### PR TITLE
Kind-less SessionDiagnostic derive

### PR DESCRIPTION
**Pull request by Xiretza**
From https://github.com/rust-lang/rust/pull/100730#discussion_r949712629:

> Hm, maybe we should expose some `sess.struct_$SOMETHING` (like `struct_diagnostic`?) that is generic over `EmissionGuarantee`, then make the `SessionDiagnostic` derive generic, i.e.
> 
> ```rust
> impl<'tcx> SessionDiagnostic for UnusedGenericParams {
>   fn into_diagnostic<T: EmissionGuarantee>( .. ) -> DiagnosticBuilder<'tcx, T> {
>     let mut diag = sess.struct_diagnostic(rustc_errors:..);
>     ..
>   }
> }
> ```

Discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/.23100717.20translation.20-.20kind-less.20derive).

### CODE REVIEW

**Comment by compiler-errors** [comment]
This is exactly what I wanted to see! :smile: I'll wait until CI is ready and then approve.

**Comment by compiler-errors** [comment]
Also, we probably need to adjust the rustc dev guide docs once again.

**Comment by Xiretza** [comment]
That's good to hear! :D The PR will conflict with all the diagnostics migration PRs currently open, so I suppose it will need a rollup=never with a relatively high priority or it'll fail bors until the end of time.

**Comment by Xiretza** [comment]
> Also, we probably need to adjust the rustc dev guide docs once again.

Already drafted: rust-lang/rustc-dev-guide#1440

**Comment by compiler-errors** [comment]
> The PR will conflict with all the diagnostics migration PRs currently open, so I suppose it will need a rollup=never with a relatively high priority or it'll fail bors until the end of time.

Yup makes sense. I was gonna wait until CI is green then approve.

> Already drafted: https://github.com/rust-lang/rustc-dev-guide/pull/1440

You're wonderful!

**Comment by compiler-errors** [comment]
@bors r+ p=1 rollup=never

(will likely not merge unless p=1)

**Comment by ChrisDenton** [comment]
CI has stalled so...

@bors retry timeout

**Comment by ChrisDenton** [comment]
Oh that didn't work, try

@bors force

**Comment by compiler-errors** [comment]
Thank you for checking on this @ChrisDenton. The bors queue has been awfully slow today...

**Comment by compiler-errors** [comment]
... is bors stalled again? :facepalm:

**Comment by Xiretza** [comment]
Something seems to be iffy with `x86_64-mingw-1`, I've seen it time out several times now.

**Comment by compiler-errors** [comment]
I don't think this is related to this PR, but the bors queue is terribly long right now, so I'm gonna kick this again.

@bors r-

**Review by davidtwco — APPROVED** [review]
This is fantastic, thanks for working on it!

**Comment by Xiretza** [comment]
Rebased, and fixed #100793 breakage.

@rustbot ready

**Comment by compiler-errors** [comment]
Ok this is ridiculous. I'm gonna stop landing this PR until T-infra can look into why this is making `i686-mingw-1` hang.

@bors r-

**Comment by Xiretza** [comment]
I think those hangs might not be related to this PR at all, since they're also occuring with other PRs - this one was just unfortunate enough to catch it three times in a row.

**Comment by compiler-errors** [comment]
Alright, let's try this again then.

@bors r+

**Comment by compiler-errors** [comment]
Wait... this needs rebase.

@bors r-

**Comment by davidtwco** [comment]
Thanks for working on this!

**Pull request merged**
