### PR TITLE
Add a note to duplicate diagnostics

### PR DESCRIPTION
**Pull request by Alexendoo**
Helps explain why there may be a difference between manual testing and the test suite output and highlights them as something to potentially look into

For existing duplicate diagnostics I just blessed them other than a few files that had other `NOTE` annotations in

### CODE REVIEW

**Comment by Alexendoo** [comment]
I've removed the `only-x86_64` from `tests/ui/consts/const-eval/union-const-eval-field.rs` also to bless it

It looks like it was ignored due to [outputting the raw bytes originally](https://github.com/rust-lang/rust/commit/49705e0709eb4d04b6d9fa8c43e0fb07b2939e44), but that no longer applies

**Comment by compiler-errors** [comment]
I like this idea a lot. please bless the tests tho :smiley_cat: 

r? compiler-errors
cc @rust-lang/wg-diagnostics

**Comment by Alexendoo** [comment]
Slowly getting through all the tests that were ignored/I didn't think to run locally 😄

**Pull request merged**
