### PR TITLE
Avoid generating empty closures for fieldless enum variants

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
For many enums, this avoids generating lots of tiny stubs that need to be codegen'd and then inlined and removed by LLVM. perf shows this to be a fairly small, but significant, win on rustc bootstrap time -- with minimal impact on runtime performance (which is at times even positive).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
The regression is not readily explainable -- the new code should perform ~equivalently or better. I suspect LLVM is optimizing worse since the closure isn't forcing unique instantiations per call site (which means the emit_usize in particular is going to be with a runtime, not constant, value).

Latest commit tries to force that question with a const-generic argument, which should still be cheap(er) than the closure - particularly since it'll be shared amongst like-numbered enums, hopefully.

@bors try @rust-timer queue

**Comment by Mark-Simulacrum** [comment]
r? rust-lang/compiler-contributors

Perf impact outside the self-bootstrap timing is likely to be not entirely noise, but is fairly small and IMO justified by the improvements in bootstrap time this patch gives.

**Review by davidtwco — APPROVED** [review]

**Pull request merged**
