### PR TITLE
Clean up small, surprising bits of code

### PR DESCRIPTION
**Pull request by bugadani**
This PR clean up a small number of unrelated, small things I found while browsing the code base.

### CODE REVIEW

**Review by pickfire — APPROVED** [review]
Looks good to me.

**Review by frewsxcv — APPROVED** [review]
thanks!

**Comment by frewsxcv** [comment]
first time i've attempted to approve a pr in a while, guess i lost privileges 😅

**Comment by frewsxcv** [comment]
oh and looks like it was already approved, oops

**Pull request merged**
