### PR TITLE
Tries to address the recent network issues

### PR DESCRIPTION
**Pull request by kennytm**
1. Set the DNS server to 8.8.8.8/8.8.4.4/1.1.1.1/1.0.0.1 to workaround the daily "Cannot resolve host" error these two weeks.
2. Remove the unnecessary command `gem update --system` (originally added as experiment of the "Could not find a valid gem" error, which turns out to be useless).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This looks good to me, r=me when ready.

**Comment by pietroalbini** [comment]
Do we know which DNS servers Travis was using before?

**Comment by kennytm** [comment]
@pietroalbini 169.254.169.254, which according to https://stackoverflow.com/a/32723910 is the same as the Google Public DNS for external domains, but I'm not sure if Travis has done some additional configuration in between.

**Comment by pietroalbini** [comment]
Hmm, if that points to the same resolver it _shouldn't_ make a difference using 8.8.8.8, but whatever, this change won't hurt, let's try it.

**Comment by kennytm** [comment]
Yeah that's also why I've included 1.1.1.1 as backup. Though if 8.8.8.8 really responded "cannot resolve" then the OS won't consult the remaining items.

**Pull request merged**
