### PR TITLE
[DO NOT MERGE] Enable parallel compiler by default

### PR DESCRIPTION
**Pull request by Aaron1011**
It's been over a year since we last tried this - let's see what the
performance looks like now.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Note that there are known scalability flaws, and that this is insufficient by itself - you need to flip https://github.com/rust-lang/rust/blob/master/src/librustc_session/options.rs#L1033 to a more reasonable default (iirc, it's annoying to get num CPUs there, so you might want to just put 6 or 12, which are the physical/virtual thread counts on perf.rlo's collector)

That said, it would be interesting to see the overhead of the worst case (locks enabled but useless) on modern rustc. Maybe best to do that after we've bumped parking lot and other crates to latest versions, though.

**Comment by mati865** [comment]
Instructions look not that bad. Wall-time and task-clock regress noticeably.

**Comment by joshtriplett** [comment]
@Aaron1011 Could you give this another run with a change to the default thread count, to use 12 (or num_cpus) by default?

**Comment by mati865** [comment]
Mix of massive wins and big regressions in wall-time.

**Comment by Mark-Simulacrum** [comment]
Closing -- I think this is perhaps something to look at, but I don't currently have the bandwidth to do so and it looks like @Aaron1011 doesn't either.

**Pull request closed without merging**
