### PR TITLE
Refactor: reduce length of issue-72933 and issue-74564 test

### PR DESCRIPTION
**Pull request by Skgland**
Part of #60302

### CODE REVIEW

**Comment by nagisa** [comment]
Do these new tests still reproduce the original issues properly? Please verify and mention this in the commit/PR description.

**Comment by Mark-Simulacrum** [comment]
I would also say - I'm not sure how much it matters for tests whether they are long or short, but rather I'd optimize for retaining clarity. I feel like adding a macro doesn't really do that for me, rather, makes it harder to understand the test...

**Comment by Skgland** [comment]
> Do these new tests still reproduce the original issues properly? Please verify and mention this in the commit/PR description.

Yes, I made sure they still reproduced with the Version that was mentioned in the Issue to have the regression

**Comment by Skgland** [comment]
> I would also say - I'm not sure how much it matters for tests whether they are long or short, but rather I'd optimize for retaining clarity. I feel like adding a macro doesn't really do that for me, rather, makes it harder to understand the test...

That sounds reasonable, in that case these files should be removed from https://github.com/rust-lang/rust/issues/60302#issuecomment-686153529 and this PR can simply be closed. Alternatively I could try adding a comment to explain what is being done/tested.

**Comment by Mark-Simulacrum** [comment]
Yeah, I think I'd prefer to just not do this.

**Pull request closed without merging**
