### PR TITLE
the foundation owns rust trademarks

### PR DESCRIPTION
**Pull request by liigo**

### CODE REVIEW

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/rust/issues/85291

**Comment by cuviper** [comment]
The Rust Foundation has not taken over project [governance](https://www.rust-lang.org/governance), but we should probably link the README to that page rather than just saying it's a core team.

**Comment by liigo** [comment]
> Or since that section is just about trademarks, maybe it shouldn't mention governance at all.

I've pushed a commit, now the trademark section don't mention governance.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Thanks!

**Comment by irelativism** [comment]
Any update on this? https://github.com/rust-lang/foundation-faq-2020/issues/35

**Comment by irelativism** [comment]
Given even thought this PR adresses wording on the matter it still links to excessively protective Mozzila mediaguide. Rust foundation should think about creating a Perl/Python like trademark policy, which still allows protections agaisnt copycats without being obnoxious on what contributors can and cannot do ;)

**Pull request merged**
