### PR TITLE
Update orphan and overlap rules for RFC 1023

### LINKED ISSUE #23086: Forward compatibility hazard from coherence rules
The current coherence rules are *too* smart. I think we should consider adding some limits to rein it in. In particular, imagine that crate A defines:

```rust
pub struct Foo { .. }
```

And crate B then defines:

```rust
extern crate A;
trait MyTrait { }
impl<T:Clone> MyTrait for T { }
impl MyTrait for A::Foo { }
```

This is currently accepted today, I believe. However, I think it should not be, because it means that now crate A cannot add an impl of `Clone` for `Foo` for fear of breaking crate B.

My proposed fix is to modify the coherence check so that you can't assume that a type from another crate won't implement a trait from another crate.

cc @aturon

### LINKED ISSUE #23918: Tracking issue for Rebalancing Coherence (RFC 1023)
https://github.com/rust-lang/rfcs/pull/1023

### PR DESCRIPTION
**Pull request by nikomatsakis**
This PR implements rust-lang/rfcs#1023. In the process it fixes #23086 and #23516. A few impls in libcore had to be updated, but the impact is generally pretty minimal. Most of the fallout is in the tests that probed the limits of today's coherence.

I tested and we were able to build the most popular crates along with iron (modulo errors around errors being sendable).

Fixes #23918.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
The integration of coherence checking into trait matching is a bit less clean than I would like -- it preserves the existing "intercrate mode". I'd like to rework select to remove that mode and instead consider that an impl like `A: Foo` without an associated where clause be considered ambiguous.

**Comment by nikomatsakis** [comment]
Ah, and I just remembered a potential bug around subtyping in the way that I implemented the orphan check. I'll patch that. But it shouldn't really affect much, so I'll leave the PR open to use for reference while considering rust-lang/rfcs#1023.

**Comment by nikomatsakis** [comment]
r? @pnkfelix 

Since we will remove variance for trait matching, that complication is resolved the easy way. My concern was that the overlap checking wasn't checking all 4 combinations that seem to be necessary with variance (that is, instantiate impl A with skolemized parameters, then check whether A <: B or B <: A, and vice versa). But with invariance you need only check whether A = B, which is reflexive.

**Comment by pnkfelix** [comment]
Okay, I left some notes, but its all truly minor nits that I only recommend you do if you already are rebasing this PR for some other reason.

So r+ from me.

**Comment by nikomatsakis** [comment]
Addressed nits.

**Comment by bluss** [comment]
This should have been marked breaking-change?

**Comment by tbu-** [comment]
Yup. Broke something for [rust-ascii](https://github.com/SimonSapin/rust-ascii/issues/5).

**Pull request merged**
