### PR TITLE
implement Send for process::Command on unix

### LINKED ISSUE #47751: Could process::Command implement Send ?
Hi,

Currently, we cannot send a `process::Command` to another thread because it does not implement `Send` (at least on Unix). The reason is the struct has a raw pointer field:

```rust
pub struct Command {
    // Currently we try hard to ensure that the call to `.exec()` doesn't
    // actually allocate any memory. While many platforms try to ensure that
    // memory allocation works after a fork in a multithreaded process, it's
    // been observed to be buggy and somewhat unreliable, so we do our best to
    // just not do it at all!
    //
    // Along those lines, the `argv` and `envp` raw pointers here are exactly
    // what's gonna get passed to `execvp`. The `argv` array starts with the
    // `program` and ends with a NULL, and the `envp` pointer, if present, is
    // also null-terminated.
    //
    // Right now we don't support removing arguments, so there's no much fancy
    // support there, but we support adding and removing environment variables,
    // so a side table is used to track where in the `envp` array each key is
    // located. Whenever we add a key we update it in place if it's already
    // present, and whenever we remove a key we update the locations of all
    // other keys.
    program: CString,
    args: Vec<CString>,
    argv: Vec<*const c_char>,
    env: CommandEnv<DefaultEnvKey>,

    cwd: Option<CString>,
    uid: Option<uid_t>,
    gid: Option<gid_t>,
    saw_nul: bool,
    closures: Vec<Box<FnMut() -> io::Result<()> + Send + Sync>>,
    stdin: Option<Stdio>,
    stdout: Option<Stdio>,
    stderr: Option<Stdio>,
}
```
According to @cuviper [it's probably possible to implement `Send` manually](https://users.rust-lang.org/t/would-it-be-possible-for-std-process-command-to-be-send/15254/2) though. Is this something you would consider?

### PR DESCRIPTION
**Pull request by little-dude**
closes https://github.com/rust-lang/rust/issues/47751

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Since `Command` contains a whole bunch of fields (even trait objects!) perhaps we could implement `Send` manually for a specific field rather than the whole struct? That way we could catch if we accidentally introduce a bug into one of the other fields.

Also, could you be sure to add a test for this as well?

**Comment by little-dude** [comment]
@alexcrichton thanks for reviewing! I added the test `src/libstd/process.rs` so that it does not only run for unix.

**Comment by alexcrichton** [comment]
@bors: r+

THanks @little-dude!

**Pull request merged**
