### PR TITLE
remove the #[inline] attribute from drop_in_place

### LINKED ISSUE #41696: Long compilation time due to LLVM creating excessive landing pads
Long compilation time (almost infinity on real project) with every nightly versions after 2017-03-18.

I tried this:
```
git clone https://github.com/not-fl3/incremental_bug
CARGO_INCREMENTAL=1 cargo build --release
```

I expected to see this happen: 
On 2017-03-18 it compiles for less than a second (in 0.59 secs on my machine)

Instead, this happened: 

With every version newer than 2017-03-18 it compiles for 389+ seconds on my machine. 

## Meta

`rustc --version --verbose`:
```
rustc 1.19.0-nightly (06fb4d256 2017-04-30)
binary: rustc
commit-hash: 06fb4d25642a3f223db1441972dd5962085cfba1
commit-date: 2017-04-30
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```

Also same behaviour on this versions:
```nightly-2017-03-28-x86_64-unknown-linux-gnu```
```nightly-2017-04-22-x86_64-unknown-linux-gnu```
```nightly-2017-04-30-x86_64-unknown-linux-gnu```

Backtrace:

log of -Z time-asses: https://gist.github.com/not-fl3/8c4ee411fe6c23d4b4abb9a3b6a263d0

### PR DESCRIPTION
**Pull request by arielb1**
Apparently LLVM has exponential code growth while inlining landing pads
if that attribute is present.

Fixes #41696.

beta-nominating  because regression.
r? @eddyb

### CODE REVIEW

**Comment by arielb1** [comment]
added a comment to test

@bors r=eddyb

**Comment by arielb1** [comment]
I want perf stats. Let's merge this out of rollup

@bors p=100

**Comment by alexcrichton** [comment]
> [00:49:09] test [run-pass] run-pass/issue-41696.rs has been running for over 60 seconds

**Comment by alexcrichton** [comment]
If that's because of an older LLVM bug then it's possible to tag this test with `// min-llvm-version` I believe

**Comment by nikomatsakis** [comment]
Accepting for beta; small patch, exponential code growth regression.

cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
Backport in https://github.com/rust-lang/rust/pull/42053

**Pull request merged**
