### PR TITLE
Bump `cc` for `bootstrap`

### LINKED ISSUE #111700: `rustc` fails to build for target `riscv64gc-unknown-linux-musl`
I'm trying to build `rustc` version `1.68.0` natively on RISC-V machine with target `riscv64gc-unknown-linux-musl` enabled. It fails when building `libunwind.a` for musl target in stage2.

Similar error also occurs in version `1.69.0`.

Configuration:

```toml
[target.riscv64gc-unknown-linux-musl]
sanitizers = false
musl-root = "/usr/lib/musl"
cc = "/usr/bin/musl-gcc"
cxx = "/usr/bin/musl-gcc"
```

Error log:

```plain
Building libunwind.a for riscv64gc-unknown-linux-musl
CXX_riscv64gc-unknown-linux-musl = None
CXX_riscv64gc_unknown_linux_musl = None
TARGET_CXX = None
CXX = None
CROSS_COMPILE = None
CXXFLAGS_riscv64gc-unknown-linux-musl = None
CXXFLAGS_riscv64gc_unknown_linux_musl = None
TARGET_CXXFLAGS = None
CXXFLAGS = Some("-march=rv64gc -mabi=lp64d -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -Wp,-D_GLIBCXX_ASSERTIONS")
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = None
running: "/usr/bin/musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=rv64gc" "-mabi=lp64d" "-mcmodel=medany" "-march=rv64gc" "-mabi=lp64d" "-O2" "-pipe" "-fno-plt" "-fexceptions" "-Wp,-D_FORTIFY_SOURCE=2" "-Wformat" "-Werror=format-security" "-fstack-clash-protection" "-I" "/build/rust/src/rustc-1.68.0-src/src/llvm-project/libunwind/include" "-nostdinc++" "-fno-exceptions" "-fno-rtti" "-fstrict-aliasing" "-funwind-tables" "-fvisibility=hidden" "-std=c++11" "-fvisibility-global-new-delete-hidden" "-D_LIBUNWIND_DISABLE_VISIBILITY_ANNOTATIONS" "-o" "/build/rust/src/rustc-1.68.0-src/build/riscv64gc-unknown-linux-musl/native/libunwind/Unwind-EHABI.o" "-c" "/build/rust/src/rustc-1.68.0-src/src/llvm-project/libunwind/src/Unwind-EHABI.cpp"
cargo:warning=cc1plus: error: unrecognized command-line option ‘-fvisibility-global-new-delete-hidden’
exit status: 1


error occurred: Command "/usr/bin/musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=rv64gc" "-mabi=lp64d" "-mcmodel=medany" "-march=rv64gc" "-mabi=lp64d" "-O2" "-pipe" "-fno-plt" "-fexceptions" "-Wp,-D_FORTIFY_SOURCE=2" "-Wformat" "-Werror=format-security" "-fstack-clash-protection" "-I" "/build/rust/src/rustc-1.68.0-src/src/llvm-project/libunwind/include" "-nostdinc++" "-fno-exceptions" "-fno-rtti" "-fstrict-aliasing" "-funwind-tables" "-fvisibility=hidden" "-std=c++11" "-fvisibility-global-new-delete-hidden" "-D_LIBUNWIND_DISABLE_VISIBILITY_ANNOTATIONS" "-o" "/build/rust/src/rustc-1.68.0-src/build/riscv64gc-unknown-linux-musl/native/libunwind/Unwind-EHABI.o" "-c" "/build/rust/src/rustc-1.68.0-src/src/llvm-project/libunwind/src/Unwind-EHABI.cpp" with args "musl-gcc" did not execute successfully (status code exit status: 1).
```

### PR DESCRIPTION
**Pull request by r-value**
Bump the version of dependency `cc` to `1.0.77` for `bootstrap`, syncing with `rust/Cargo.lock`

Resolves #111700

### CODE REVIEW

**Comment by jyn514** [comment]
@bors r+ rollup

Thanks!

**Comment by jyn514** [comment]
cc @thomcc, seems like something regressed between cc 1.0.73 and .77. any idea what might have changed?

**Comment by jyn514** [comment]
@r-value fyi i don't want to bisect this in a full bors merge because it'll get merged if the test succeeds - feel free to test with PR CI though: https://rustc-dev-guide.rust-lang.org/tests/ci.html#using-ci-to-test

**Comment by r-value** [comment]
> @r-value fyi i don't want to bisect this in a full bors merge because it'll get merged if the test succeeds - feel free to test with PR CI though: https://rustc-dev-guide.rust-lang.org/tests/ci.html#using-ci-to-test

Thank you very much for your suggestion! Actually, I'm pushing the commit because I think that if 1.0.74 works then it might have a chance to meet the merge window on May 26th so that we can resolve the issue ~1mo earlier. It's not a bisect because I'm not gonna push more commit if this fails :).
But I do need some suggestion about what should I do if 1.0.74 doesn't work. Should I force-push to undo the last commit, or append a new one to bump to 1.0.77, or just leave this branch unchanged?

**Comment by jyn514** [comment]
I don't want to merge 1.0.74. Let's figure out why this regressed and fix it either upstream or here.

>  I think that if 1.0.74 works then it might have a chance to meet the merge window on May 26th so that we can resolve the issue ~1mo earlier.

I don't mind beta-nominating the PR for a backport once we figure out the right fix.

**Comment by r-value** [comment]
> I don't mind beta-nominating the PR for a backport once we figure out the right fix.

Thanks! Then what should I do about this branch? a force-push or leave it alone?

**Comment by jyn514** [comment]
Once you figure out the problem, force-pushing the fix so it's one commit would be good. Anything you want to do with it in the meantime is fine since it won't get merged.

**Comment by r-value** [comment]
I'm not familiar with Apple dev/test environments, but I suspect that rust-lang/cc-rs#661 may have set a wrong `sdk_root` for `*-apple-ios` targets.

Here is a diff between config commands of a success and failed test run.

```diff
--- fail.txt    2023-05-23 09:20:37.218611111 +0200
+++ success.txt 2023-05-23 09:20:05.004982583 +0200
@@ -32,7 +32,7 @@ DESTDIR=""
 -m64
 -mios-simulator-version-min=7.0
 -isysroot
-/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
+/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk
 -fembed-bitcode
 -fdebug-prefix-map=/Users/runner/work/rust/rust=/rustc/llvm
 -miphoneos-version-min=10.0
@@ -42,7 +42,7 @@ DESTDIR=""
 -m64
 -mios-simulator-version-min=7.0
 -isysroot
-/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
+/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk
 -fembed-bitcode
 -fdebug-prefix-map=/Users/runner/work/rust/rust=/rustc/llvm
 -fembed-bitcode=off"
@@ -59,6 +59,6 @@ DESTDIR=""
 -m64
 -mios-simulator-version-min=7.0
 -isysroot
-/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
+/Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk
 -fembed-bitcode"
 "-DCMAKE_BUILD_TYPE=Release"
```

**Comment by r-value** [comment]
> Looks like you didn't tried latest version or master branch, maybe already fixed?

TBH I don't think it is fixed because it's still accepting `SDKROOT` unconditionally. I'll have a try anyway.

**Comment by r-value** [comment]
I found something interesting here: https://github.com/rust-lang/rust/blob/f3d597b31c0f101a02c230798afa31a36bdacbc6/src/ci/scripts/install-clang.sh#L30-L35
Maybe we need to set `SDKROOT` more precisely or just remove that since it will be ignored anyway if it has a mismatched value against current target.
I'll try to remove these code for now.

**Comment by ozkanonur** [comment]
PR was closed due to inactivity. If you plan to work on it again, you can reopen it.

**Pull request closed without merging**
