### PR TITLE
add sort_unstable to unstable book

### PR DESCRIPTION
**Pull request by steveklabnik**
cc #40585

### CODE REVIEW

**Comment by frewsxcv** [comment]
A bit of a pipe dream, but it'd be cool if we had some sort of lint to make sure all unstable features are in the unstable book

@bors r+ rollup

**Comment by alexcrichton** [comment]
Oh are we gonna track all unstable library features as well? We may be missing quite a few of those...

(I also figured that unstable library features would just have API docs)

**Comment by frewsxcv** [comment]
> Oh are we gonna track all unstable library features as well? 

I'm in favor of adding entries of all unstable things into the unstable book, though I don't feel strongly. For unstable library features, the body of that particular page (e.g. the one in the pull request) could link just directly to the API docs.

**Comment by steveklabnik** [comment]
Ah yeah, I forgot about the library vs non-library distinction here.

Basically, same as Corey; I don't feel super strongly about it, but it is
kinda nice to be able to browse _all_ unstable features.

**Pull request merged**
