### PR TITLE
Add help for E0514

### PR DESCRIPTION
**Pull request by ticki**
Part of #30520

### CODE REVIEW

**Comment by Ticki** [comment]
Fixes #30363

**Comment by arielb1** [comment]
This is a little unclear. Maybe "consider recompiling it with this compiler"?

**Comment by Ticki** [comment]
Well, it requires the user to explicitly removing the binaries, since they're compiled with an older compiler.

**Comment by arielb1** [comment]
"the binaries" in this case sounds like the intended binary output of *this* compiler.

**Comment by GuillaumeGomez** [comment]
@arielb1: Why not "consider recompiling it with your current rustc version"?

**Comment by steveklabnik** [comment]
:+1: to @GuillaumeGomez 's suggestion

**Comment by arielb1** [comment]
r=me to that modulo a rebase

**Comment by Ticki** [comment]
Sure thing.

**Comment by Ticki** [comment]
Rebased.

**Comment by Ticki** [comment]
goddammit lints.

**Comment by Ticki** [comment]
Rebased again.

**Comment by arielb1** [comment]
```
<syntax macros>:2:14: 2:70 error: no method named `span_help` found for type `&'a rustc::session::Session` in the current scope

<syntax macros>:2 { ( $ err ) . span_help ( $ span , & format ! ( $ ( $ message ) * ) ) ; } )
```

**Comment by Ticki** [comment]
The internal API must have changed. Have span_help! been renamed? If so, what is it named now.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with the build errors fixed!

**Pull request closed without merging**
