### PR TITLE
Use `is_some_and` quite a lot

### PR DESCRIPTION
**Pull request by camsteffen**
Tracking issue for `is_some_and`: #93050

### CODE REVIEW

**Review by camelid — APPROVED** [review]
Rustdoc changes look good to me.

**Comment by joshtriplett** [comment]
Looks great to me.

**Comment by camsteffen** [comment]
I'd be okay with holding this open while we discuss a possible signature change in the tracking issue, assuming we can come to a conclusion before very long.

**Comment by Dylan-DPC** [comment]
> I'd be okay with holding this open while we discuss a possible signature change in the tracking issue, assuming we can come to a conclusion before very long.

@camsteffen you don't need to since the feature is unstable. So changes can be made later before stabilisation

**Comment by Dylan-DPC** [comment]
@camsteffen any updates on this?

**Comment by camsteffen** [comment]
Honestly my main motivation for this was to weigh `&self` vs. `self`. Do folks think this is still worthwhile?

**Comment by wesleywiser** [comment]
> Honestly my main motivation for this was to weigh `&self` vs. `self`. Do folks think this is still worthwhile?

Compiler changes look fine to me but this seems like a question for @rust-lang/libs-api.

**Comment by camsteffen** [comment]
The question has already been resolved in the tracking issue.

**Comment by wesleywiser** [comment]
Sorry, I interpreted your question as asking if it was still useful to discuss `&self` vs `self`, not if the PR is useful. 

If you want to rebase the PR, I'd be willing to review and merge it but if the main goal was just to demonstrate the usage in the context of a larger codebase, then I think that's already been accomplished and it might not be worth resolving all of the merge conflicts just to get it in.

**Comment by camsteffen** [comment]
Yeah I'll just close this.

**Pull request closed without merging**
