### PR TITLE
Make `(A)Rc`/`Weak` `allocator_api` APIs more consistent

### PR DESCRIPTION
**Pull request by zachs18**
Make `Arc`/`sync::Weak`/`Rc`/`rc::Weak` unstable `feature(allocator_api)` APIs more consistent with other containers (well, `Box`), and with each other.

1. `fn into_raw_with_allocator` for all.
    - Pairs with `from_raw_in` (which already exists on all 4 types).
    - Name matches `Box::into_raw_with_allocator`.
    - Associated fns on `Rc`/`Arc`, methods on `Weak`s.
2. `fn allocator` for all.
    - For `Rc`/`Arc`, the existing associated fns are changed to allow unsized pointees.
    - For `Weak`s, methods are added.
3. Remove `where A: Clone` bound on (stable) `Rc::downcast` and `downcast_unchecked`, (unstable) `assume_init`s, and some (stable) trait impls
    - (`Arc::{downcast{,_unchecked}, assume_init}` were changed by #120445)
    - `downcast(_unchecked)` and `assume_init` semantically should not require cloning the allocator; they are essentially just ((un)checked) pointer casts.
    - Remove `A: Clone` bound from `From<Vec<T, A>> for Arc<[T], A>` (`Rc`'s already didn't have a `A: Clone` bound) ~~and `TryFrom<Arc<[T], A>> for Arc<[T; N], A>`~~ (done by #120445) (see below for `Rc`)
5. Make `TryFrom<Rc<[T]>> for Rc<[T; N]>` allocator-aware.

This is adding 6[^1] new unstable functions, changing the bounds on ~~6~~ 3 unstable functions, and changing the (unstable) bounds on ~~7~~ 5 stable functions, so I think it needs at least a libs-api FCP? If it also needs an ACP I can make one. (If the parts of this PR should be split I can do that too.)

@rustbot label +A-allocators +T-libs-api -T-libs

<details> <summary>Future PR</summary>

As a follow-on to this PR, I plan to make a PR/ACP later to move `into_raw(_parts)` from `Container<_, A: Allocator>` to only `Container<_, Global>` (where `Container` = `Vec`/`Box`/`Rc`/`rc::Weak`/`Arc`/`sync::Weak`) so that users of non-`Global` allocators have to explicitly handle the allocator when using `into_raw`-like APIs.

The current behaviors of stdlib containers are inconsistent with respect to what happens to the allocator when `into_raw` is called (which does not return the allocator)

| Type | `into_raw` currently callable with | behavior of `into_raw`|
| --- | --- | --- |
| `Box` | any allocator | allocator is [dropped](https://doc.rust-lang.org/nightly/src/alloc/boxed.rs.html#1060) |
| `Vec` | any allocator | allocator is [forgotten](https://doc.rust-lang.org/nightly/src/alloc/vec/mod.rs.html#857) |
| `Arc`/`Rc`/`Weak` | any allocator | allocator is [forgotten](https://doc.rust-lang.org/src/alloc/sync.rs.html#1464)(Arc) [(sync::Weak)](https://doc.rust-lang.org/src/alloc/sync.rs.html#2672) [(Rc)](https://doc.rust-lang.org/src/alloc/rc.rs.html#1313) [(rc::Weak)](https://doc.rust-lang.org/src/alloc/rc.rs.html#2924) |

In my opinion, neither implicitly dropping nor implicitly forgetting the allocator is ideal; dropping it could immediately invalidate the returned pointer, and forgetting it could unintentionally leak memory. My (to-be) proposed solution is to just forbid calling `into_raw(_parts)` on containers with non-`Global` allocators, and require calling `into_raw_with_allocator`(/`Vec::into_raw_parts_with_alloc`)

</details>

[^1]:  Technically 5 new and 1 renamed, since `rc::Weak::into_raw_with_allocator` is not newly added, as it was modified and renamed from `rc::Weak::into_raw_and_alloc`.

### CODE REVIEW

**Comment by zachs18** [comment]
@rustbot label -T-libs

r? rust-lang/libs-api

**Comment by zachs18** [comment]
Notes to self while rebasing:

Most of the `Arc` parts of this were done by #120445

@rustbot author

**Comment by zachs18** [comment]
@BurntSushi Friendly ping (I just realized that  the `r? libs-api` probably didn't send a notification)

**Comment by BurntSushi** [comment]
I'm not really dialed into the allocator work. Can you find someone who is to review this? Maybe @matthieu-m?

**Comment by BurntSushi** [comment]
Alternatively, if this PR can be split up into more digestible chunks, that might help get it reviewed more quickly.

**Comment by matthieu-m** [comment]
@BurntSushi From what I can tell, this PR does not require any Allocator specific knowledge, it doesn't actually even introduce any call Allocator methods (it eliminates calls to `clone`).

I think any libs member comfortable with API requests can tackle this review without issue.

_(I'm neither a libs member, nor am I well-versed in API guidelines)_

**Comment by zachs18** [comment]
I'll probably go ahead and split this into multiple PRs then. I probably won't have time to work on that for a week or so, so I'll leave this open if someone wants to reveiw it until then.

**Comment by zachs18** [comment]
Split into #124980 and #124981. Later PR will add `fn into_raw_with_allocator`.

**Pull request closed without merging**
