### PR TITLE
mem::forget docs: mention ManuallyDrop

### PR DESCRIPTION
**Pull request by RalfJung**
Cc @SimonSapin @Centril

### CODE REVIEW

**Comment by Centril** [comment]
Maybe we should deprecate `mem::forget`? :D

**Comment by RalfJung** [comment]
I was wondering the same thing but I am very far from sure that `ManuallyDrop` is *always* preferable.

**Comment by SimonSapin** [comment]
Deprecation warnings cause churn, so we should consider what we hope to gain in return.

If most maintainers who see this warning only want to make it go away and literally replace `forget(x)` with `ManuallyDrop::new(x);` (note the semicolon) which is exactly the implementation of `forget` these days, there’s no point.

If we want them to restructure their code to warp a value in `ManuallyDrop` “before transferring ownership” (which is a concept not easy to explain precisely IMO) we’d have to be very careful about how the deprecation message is phrased.

**Comment by JohnCSimon** [comment]
Ping from triage
@sfackler - can you please review this PR?
Thank you!

**Pull request merged**
