### PR TITLE
Removed most instances of vec!(..) and replaced them with vec![..]s

### PR DESCRIPTION
**Pull request by iirelu**
Everyone hates the old syntax. I hope. Otherwise this PR has some controversy I wasn't expecting.

This would be the perfect time to write a lint recommending `vec![..]` when you use another style.

Disclaimer: I _may_ have broken something. If I have, I'll fix them when the tests come in. Luckily the chance for a non-syntactical error is pretty low in all this.

### CODE REVIEW

**Comment by steveklabnik** [comment]
👍

**Comment by sanxiyn** [comment]
```
failures:
    [pretty] pretty/stmt_expr_attributes.rs
```

**Comment by iirelu** [comment]
Oh dear, looks like I hit some sort of snag in pretty printing. Looks like `vec![]` still pretty-prints as `vec!()` :(

Should I revert this single file's changes, or is there something else that needs fixing?

**Comment by Mark-Simulacrum** [comment]
I'd guess that'll be rather hard to fix--I don't believe pretty printing is "aware" of `vec!` specifically, and as such it doesn't know it should be `vec![...]` and not `vec!(...)`.

I'm not familiar with that part of the compiler though, so may be wrong.

**Comment by iirelu** [comment]
Never resolved a merge conflict before. Sure hope I did that right!

**Comment by retep998** [comment]
Typically the way merge conflicts are resolved is by rebasing your pull request on top of master, that way you don't have extra merge commits cluttering up the history.

**Comment by iirelu** [comment]
I fucked up my git history. :(

**Comment by iirelu** [comment]
Okay I completely fucked up everything. I'm just going to close this.

**Comment by steveklabnik** [comment]
@iirelu happy to help out if you need some; I think this is a good change, and would hate to see `git` be the reason it's not merged 😄

**Pull request closed without merging**
