### PR TITLE
Convert index operator to be by value

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is a [breaking-change]. When indexing a generic map (hashmap, etc) using the `[]` operator, it is now necessary to borrow explicitly, so change `map[key]` to `map[&key]` (consistent with the `get` routine). However, indexing of string-valued maps with constant strings can now be written `map["abc"]`.

r? @japaric
cc @aturon @Gankro

### CODE REVIEW

**Comment by nikomatsakis** [comment]
(Hmm, something seems to have broken in the rebase. It *WAS* passing `make check`. I'll fix it up tomorrow.)

**Comment by nikomatsakis** [comment]
OK, fixed the problem I was seeing locally -- rerunning make check now.

**Comment by nikomatsakis** [comment]
oh and cc @sfackler

**Comment by Gankro** [comment]
I'm not sure where we landed in discussion before. Longterm what's the strategy for recovering the old behaviour?

**Comment by nikomatsakis** [comment]
ok, make check passes.

**Comment by nikomatsakis** [comment]
@Gankro if we want to recover the `map[key]`, vs `map[&key]`, there are two options:

1. Optional autoref, probably applied uniformly to all by-value operators (that is, also to `+` and friends). (*)
2. Extending coherence in such a way that we can provide two impls.

I would prefer option 1 since I think we want to have optional auto-ref for `+`, and I think that the more we can make the operators act uniformly the better. (That said, I probably want to find ways to extend coherence too, but that's a complicated story...)

(All that said, my experience has been that I find the autoref on `map[key]` rather confusing. I can never remember whether I need an `&` or not, basically -- I expect `map.get(&key)` and `map[&key]` to act the same, but for the `Option` return type.)

(*) This may seem inconsistent with our conversation on IRC, since I think maybe (in retrospect) you were asking me about the prospects for "autoref" and I was saying "that's hard". There are indeed sometimes challenges about this sort of thing from inference; we'd have to see how well it works. But I think it'll work out ok in most cases, I guess.

**Comment by nikomatsakis** [comment]
@bors p=1 

important language change

**Comment by nikomatsakis** [comment]
@bors: retry

this test failure makes no sense!

**Pull request merged**
