### PR TITLE
once cell renamings

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This PR does the renamings proposed in https://github.com/rust-lang/rust/issues/74465#issuecomment-1153703128

- Move/rename `lazy::{OnceCell, Lazy}` to `cell::{OnceCell, LazyCell}`
- Move/rename `lazy::{SyncOnceCell, SyncLazy}` to `sync::{OnceLock, LazyLock}`

(I used `Lazy...` instead of `...Lazy` as it seems to be more consistent, easier to pronounce, etc)

@rustbot label +T-libs-api -T-libs

### CODE REVIEW

**Review by flip1995 — CHANGES_REQUESTED** [review]

**Comment by veber-alex** [comment]
`LazyLock` is kind of a strange name considering you still need a `Mutex` or a `RwLock` to get a mutable reference.

**Review by flip1995 — APPROVED** [review]
Clippy changes LGTM now :+1:

**Comment by m-ou-se** [comment]
Thanks! Looks good to me. Looking at the tracking issue, it seems like there's consensus for this change.

@bors r+

**Comment by est31** [comment]
This seems to have missed the removal of the `std::lazy` and `core::lazy` modules. Was this intentional? If not, I've filed #102812 to remove those modules.

**Comment by WaffleLapkin** [comment]
@est31 this wasn't intentional, thanks for filling the PR ❤️

**Pull request merged**
