### PR TITLE
Add midpoint function for all integers and floating numbers

### PR DESCRIPTION
**Pull request by Urgau**
This pull-request adds the `midpoint` function to `{u,i}{8,16,32,64,128,size}`, `NonZeroU{8,16,32,64,size}` and `f{32,64}`.

This new function is analog to the [C++ midpoint](https://en.cppreference.com/w/cpp/numeric/midpoint) function, and basically compute `(a + b) / 2` with a rounding towards ~~`a`~~ negative infinity in the case of integers. Or simply said: `midpoint(a, b)` is `(a + b) >> 1` as if it were performed in a sufficiently-large signed integral type.

Note that unlike the C++ function this pull-request does not implement this function on pointers (`*const T` or `*mut T`). This could be implemented in a future pull-request if desire.

### Implementation

For `f32` and `f64` the implementation in based on the `libcxx` [one](https://github.com/llvm/llvm-project/blob/18ab892ff7e9032914ff7fdb07685d5945c84fef/libcxx/include/__numeric/midpoint.h#L65-L77). I originally tried many different approach but all of them failed or lead me with a poor version of the `libcxx`. Note that `libstdc++` has a very similar one; Microsoft STL implementation is also basically the same as `libcxx`. It unfortunately doesn't seems like a better way exist.

For unsigned integers I created the macro `midpoint_impl!`, this macro has two branches:
 - The first one take `$SelfT` and is used when there is no unsigned integer with at least the double of bits. The code simply use this formula `a + (b - a) / 2` with the arguments in the correct order and signs to have the good rounding.
 - The second branch is used when a `$WideT` (at least double of bits as `$SelfT`) is provided, using a wider number means that no overflow can occur, this greatly improve the codegen (no branch and less instructions).

For signed integers the code basically forwards the signed numbers to the unsigned version of midpoint by mapping the signed numbers to their unsigned numbers (`ex: i8 [-128; 127] to [0; 255]`) and vice versa.
I originally created a version that worked directly on the signed numbers but the code was "ugly" and not understandable. Despite this mapping "overhead" the codegen is better than my most optimized version on signed integers.

~~Note that in the case of unsigned numbers I tried to be smart and used `#[cfg(target_pointer_width = "64")]` to determine if using the wide version was better or not by looking at the assembly on godbolt. This was applied to `u32`, `u64` and `usize` and doesn't change the behavior only the assembly code generated.~~

### CODE REVIEW

**Comment by falk-hueffner** [comment]
For unsigned integers, it might be worthwhile to consider a branchless version using the well-known fact that the average rounding down can be calculated by `((a ^ b) >> 1) + (a & b)`, e.g.
```rust
pub const fn midpoint(a: u64, b: u64) -> u64 {
    let b1 = b + ((b < a) as u64);
    return ((a ^ b1) >> 1) + (a & b1);
}
```
However, in many applications the branch will be perfectly predictable, in which case the method in this PR would probably be faster.

**Comment by Urgau** [comment]
I've done some comparisons on x86_64 with `-C opt-level=3` between my implementation and your proposed implementation:
 - [u16](https://godbolt.org/z/5GYr676T4): +1 instruction, 211 vs 342 cycles (for 100 iterations), more expensive
 - [u32](https://godbolt.org/z/zrPT7z1Gn): +1 instruction, 209 vs 333 cycles (for 100 iterations), more expensive
 - [u64](https://godbolt.org/z/3aro7MP45): -2 instructions, 407 vs 333 cycles (for 100 iterations), less expensive
 - [u128](https://godbolt.org/z/b9xd5asad): -5 instructions, -1 branch, 1404 vs 1403 cycles (for 100 iterations), similar
 - [i16](https://godbolt.org/z/W56xGMfjx): +2 instructions, 283 vs 433 cycles (for 100 iterations), more expensive
 - [i32](https://godbolt.org/z/3eGvs4rTx): +3 instructions, 233 vs 407 cycles (for 100 iterations), more expensive
 - [i64](https://godbolt.org/z/67MKcEazP): -2 instructions, 509 vs 408 cycles (for 100 iterations), less expensive
 - [i128](https://godbolt.org/z/vv9obeEW9): -6 instructions, -1 branch, 1604 vs 1505 cycles (for 100 iterations), similar

It seems that given the current optimization of LLVM (and GCC in a similar manner), my understanding of `llvm-mca` and `x86_64` (witch is not much) that your proposed implementation is better for `u64` and `u128` (and by incidence also `i64` and `i128`).

If you (@falk-hueffner) or @joshtriplett think this is worthwhile I'm happy to change my implementation to use your solution for `u64` and `u128`. (I may also if I find the time change it, just to simplify the code and remove the `#[cfg]`)

**Comment by Urgau** [comment]
I've rebase the branch, inline the implementation of the signed numbers and added the function to `NonZeroU{8,16,32,64,size}` (`NonZeroI{..}` is a bit tricky because of the opposites numbers that can output 0, so I left it out for now).

**Comment by cuviper** [comment]
FWIW, num-integer has similar methods in its [`Average`](https://docs.rs/num-integer/latest/num_integer/trait.Average.html) trait, offering `average_ceil` and `average_floor`. It does use the same branchless implementation from Hacker's Delight too. (cc rust-num/num-integer#31)

At least we won't collide names if we stick with `midpoint` here...

**Comment by Urgau** [comment]
> For unsigned integers, it might be worthwhile to consider a branchless version using the well-known fact that the average rounding down can be calculated by `((a ^ b) >> 1) + (a & b)`, e.g.
> 
> ```rust
> pub const fn midpoint(a: u64, b: u64) -> u64 {
>     let b1 = b + ((b < a) as u64);
>     return ((a ^ b1) >> 1) + (a & b1);
> }
> ```

@falk-hueffner I just realize that you're proposed solution isn't valid when `b=u64::MAX`, as it would overflow.

**Comment by yaahc** [comment]
I'm reassigning this PR because I'm taking a break from the review rotation for a little while. Thank you for your patience.

r? rust-lang/libs-api

**Comment by JohnCSimon** [comment]
Triage: 
@dtolnay this is still waiting on review

**Comment by dtolnay** [comment]
My current backlog is making it seem no longer plausible that I will ever get to this, so I need to reassign.
r? libs-api

**Comment by scottmcm** [comment]
> with a rounding towards `a` in the case of integers.

Out of curiosity, why is that rounding the best one?

I just happened to stumble on this today having recently noticed [`InstBuilder::avg_round`](https://docs.rs/cranelift/latest/cranelift/prelude/trait.InstBuilder.html#method.avg_round) which is spec'd to provide the same value as an infinite-precision calculation of `(x + y + 1) / 2`.

And my instinct is that `midpoint(a, b)` and `midpoint(b, a)` *ought* to give the same value.  The nicest answer might be banker's rounding for in-exact, though I don't know if that's efficiently feasible.

**Comment by Urgau** [comment]
> > with a rounding towards `a` in the case of integers.
> 
> Out of curiosity, why is that rounding the best one?

I will be honest, I don't know (or don't remember, it's been a long time).

I basically followed what the C++ `midpoint` function does:
> Half the sum of a and b. No overflow occurs. If a and b have integer type and the sum is odd, the result is rounded towards a. If a and b have floating-point type, at most one inexact operation occurs.

Here is the open-std discussion: [P0811R3: Well-behaved interpolation for numbers and pointers](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0811r3.html)

> I just happened to stumble on this today having recently noticed [`InstBuilder::avg_round`](https://docs.rs/cranelift/latest/cranelift/prelude/trait.InstBuilder.html#method.avg_round) which is spec'd to provide the same value as an infinite-precision calculation of `(x + y + 1) / 2`.
> 
> And my instinct is that `midpoint(a, b)` and `midpoint(b, a)` _ought_ to give the same value. The nicest answer might be banker's rounding for in-exact, though I don't know if that's efficiently feasible.

Yeah, we could say that it is equivalent. It would also simplify the code. I don't have opinion on it. Happy to change it if you prefer. 

> I'll also note that writing something obvious and leaving it up to LLVM gives a pretty good result:
> 
> [...]
> 
> Giving an implementation that's commutative and doesn't need any bitop tricks in the Rust code.

That's pretty nice. I would be happy to change the implementation if the rounding is decided to be the same.

**Comment by scottmcm** [comment]
> Here is the open-std discussion: [P0811R3: Well-behaved interpolation for numbers and pointers](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0811r3.html)

Thanks for the link!

Curiously, that doesn't seem to justify the semantics it picked.

It starts with 

>Computing the (integer) midpoint of two integer values via
> `(a+b)/2`
> can cause overflow for signed or unsigned integers as well as for floating-point values.

Which is symmetric, but then jumps to `a + (b-a)/2` instead without motivation.

Later, when discussing pointers it says

> As with integers, when the midpoint lies between two pointer values the one closer to a is chosen; for the usual case of a<b, this is compatible with the usual half-open ranges by selecting a when [a,b) is [a,a+1).

But "round towards `a`" and "round towards 0" and "round toward negative infinity" all have the property for pointers.

Interestingly, it also links to <https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0999r0.pdf> which at one point suggests describing the semantics for something

> as if the operation were performed in a sufficiently large signed integral type

So I'd be tempted to steal that wording for the Rust semantics: `midpoint(a, b)` is `(a + b) >> 1` as if it were performed in a sufficiently-large signed integral type.  That way it rounds towards negative infinity (`midpoint(-1, 0)` == `midpoint(0, -1)` == -1) to meet the `[a, a+1)` case, and that's the same as rounding towards zero for unsigned types, so if `(a+b)/2` doesn't overflow for positive `a` and positive `b`, `midpoint(a, b)` would return the same value as the obvious `(a+b)/2`.

**Comment by m-ou-se** [comment]
We briefly discussed this in today's libs-api meeting.

Looks like this was just stuck on someone reviewing the implementation. The API itself seems uncontroversial, except for the rounding mode. Towards zero, towards minus infinity, and towards the first argument could all make sense. There was no clear consensus on one rounding mode in the meeting.

We'd need to see use cases and discuss how those generalize to decide on the rounding mode. But that doesn't need to block this PR.

Feel free to add this as an unstable API, after [filing a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX) with the rounding question as an unresolved question.

**Comment by scottmcm** [comment]
@Urgau please add a tracking issue.

@rustbot author
r? @scottmcm

**Comment by scottmcm** [comment]
Thanks for sticking with this!  I'm excited to have it in nightly.

@bors r+

**Pull request merged**
