### PR TITLE
Partially stabilize RFC 1506 "Clarify relationships between ADTs"

### PR DESCRIPTION
**Pull request by petrochenkov**
Lifted restrictions on tuple structs/variants are stabilized, i.e. `S{..}` can be used with any structs and empty tuple structs are permitted without feature gate.
Numeric fields in struct expressions/patterns `S { 0: a, 1: b }` are **NOT** stabilized.
This was implemented 1.5 months ago in Rust 1.12, but this is a tiny technical change that could probably go even without RFC/stabilization period.

cc https://github.com/rust-lang/rust/issues/35626 https://github.com/rust-lang/rust/pull/36871
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @rust-lang/lang -- thoughts on stabilizing `Foo { .. }`?

**Comment by nrc** [comment]
Should this have an FCP cycle? I'm still in favour of the change but it does not seem like a no-brainer feature to me - it still gives me pause that braced structs can match tuple structs in patterns.

**Comment by nikomatsakis** [comment]
@nrc I was thinking it probably should, yes.

**Comment by alexcrichton** [comment]
ping, is this just waiting for the FCP on an issue to close?

**Comment by petrochenkov** [comment]
Yes, waiting for FCP.
Not sure though when exactly it's supposed to happen, before or after the next release.

**Comment by nikomatsakis** [comment]
@petrochenkov so FCP is over, care to rebase?

**Comment by petrochenkov** [comment]
Rebased.

**Pull request merged**
