### PR TITLE
Make Edition 2021 Stable

### PR DESCRIPTION
**Pull request by HTGAzureX1212**
An item of #87959.

This is an "on-demand" pull request, which means it will be merged when it is the right time to.

### CODE REVIEW

**Comment by ehuss** [comment]
I think https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/command-line-arguments.md#--edition-specify-the-edition-to-use also needs updating.

**Comment by HTG-YT** [comment]
I think so.

**Comment by Urgau** [comment]
Don't the constant [`LATEST_STABLE_EDITION`](https://github.com/rust-lang/rust/blob/9dd9ee55954d65e466811e23ebb56c799c05264b/compiler/rustc_span/src/edition.rs#L35) in `rust/compiler/rustc_span/src/edition.rs:35` also need to be changed to `Edition2021` ?

**Comment by m-ou-se** [comment]
Yes. I've rebased the branch updated LATEST_STABLE_EDITION, and fixed another 2021-stabilization related fixme.

**Comment by m-ou-se** [comment]
@bors p=10

This is blocking stabilization of Rust 2021 in cargo, which needs to happen asap.

**Comment by ehuss** [comment]
@bors retry
apple failed, no logs

**Pull request merged**
