### PR TITLE
Include scope id in SocketAddrV6::Display

### PR DESCRIPTION
**Pull request by tamird**
r? @tmandry 

I couldn't find any unit tests for these functions.

cc @ghanan94 @brunowonka

### CODE REVIEW

**Comment by tmandry** [comment]
@dtolnay Are there any issues with changing the Display impl here?

**Comment by dtolnay** [comment]
I think this is fine.

**Review by dtolnay — CHANGES_REQUESTED** [review]
Needs tests. Tests are in library/std/src/net/addr/tests.rs.

**Comment by tamird** [comment]
Added tests.

**Review by dtolnay — APPROVED** [review]
Thank you!

**Pull request merged**
