### PR TITLE
libsyntax: Merge OwnedSlice into ptr::P

### PR DESCRIPTION
**Pull request by petrochenkov**
Part of https://github.com/rust-lang/rust/pull/30095 not causing mysterious segfaults.

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
@bors: r+

I'm a big fan of the deprecation warning, thanks!

**Comment by petrochenkov** [comment]
Since this PR is not merged yet, I've added another well behaving part of https://github.com/rust-lang/rust/pull/30095 on top of it - alias `HirVec` for vector in HIR.

**Comment by petrochenkov** [comment]
Rebased.

**Pull request merged**
