### PR TITLE
add -Z pre-link-arg{,s} to rustc

### PR DESCRIPTION
**Pull request by japaric**
This PR adds two unstable flags to `rustc`: `-Z pre-link-arg` and `-Z
pre-link-args`. These are the counterpart of the existing `-C link-arg{,s}`
flags and can be used to pass extra arguments at the *beginning* of the linker
invocation, before the Rust object files are passed.

I have [started] a discussion on the rust-embedded RFCs repo about settling on a
convention for passing extra arguments to the linker and there are two options
on discussion: `.cargo/config`'s `target.$T.rustflags` and custom target
specification files (`{pre,,post}-link-args` fields). However, to compare these
two options on equal footing this `-Z pre-link-arg` feature is required.

[started]: https://github.com/rust-embedded/rfcs/pull/24

Therefore I'm requesting landing this `-Z pre-link-arg` flag as an experimental
feature to evaluate these two options.

cc @brson
r? @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks like this has a merge conflict.

**Comment by japaric** [comment]
@Mark-Simulacrum fixed

**Comment by aidanhs** [comment]
Ping @alexcrichton for review.

**Comment by alexcrichton** [comment]
@bors: r+

Oop sorry for the delay!

**Comment by alexcrichton** [comment]
@bors: retry

something tells me that libstd doesn't actually take an hour to compile

**Comment by alexcrichton** [comment]
@bors: retry

* [appveyor network issues](https://appveyor.statuspage.io/incidents/2g5jnq5cy1g1) #40474

**Pull request merged**
