### PR TITLE
miri: ICE on invalid terminators

### PR DESCRIPTION
**Pull request by RalfJung**
We've run a lot of MIR in Miri (including some generators) and never seen these.

@tmandry is it correct that `Yield` and `GeneratorDrop` get lowered away?

@eddyb @oli-obk what's with this `Abort` that does not seem to ever actually exist? Codegen *does* seem to handle it, so I wonder why Miri can get away without that. In fact, codegen handles it twice:

https://github.com/rust-lang/rust/blob/1d5241c96208ca7d925442b1a5fa45ad18717a6f/src/librustc_codegen_ssa/mir/block.rs#L796

https://github.com/rust-lang/rust/blob/1d5241c96208ca7d925442b1a5fa45ad18717a6f/src/librustc_codegen_ssa/mir/mod.rs#L296

### CODE REVIEW

**Comment by jonas-schievink** [comment]
> is it correct that `Yield` and `GeneratorDrop` get lowered away?

They get lowered by the generator transform, so if you run before that you'll still encounter them. If you run after it they should all be gone though.

**Comment by RalfJung** [comment]
Yeah we definitely run after that.

**Comment by matthewjasper** [comment]
`Abort` is used instead of `Resume` for functions annotated with `#[unwind(aborts)]` when compiling with `-Cpanic=unwind`.

**Comment by RalfJung** [comment]
@matthewjasper Ah! Here's a Miri reproducer then:
```rust
#![feature(unwind_attributes)]

#[unwind(aborts)]
fn panic_abort() { panic!() }

fn main() {
    panic_abort();
}
```

**Comment by RalfJung** [comment]
All right, I think this is ready now.
r? @oli-obk

**Comment by oli-obk** [comment]
Shouldn't the abort intrinsic also forward to this new machine hook?

You can probably run your miri repro under unleash, too.

**Comment by RalfJung** [comment]
> Shouldn't the abort intrinsic also forward to this new machine hook?

So far the core Miri engine knows nothing about the abort intrinsic. You want to see it added to `librustc_mir/interpret/intrinsics.rs`?

> You can probably run your miri repro under unleash, too.

Yeah but we don't actually support aborting in CTFE so I am not entirely sure about the point of that...^^

**Comment by RalfJung** [comment]
I added the abort intrinsic. At some point we should probably just move all the intrinsics from Miri to here... well, all except atomics and those requiring host floating point maybe.

**Pull request merged**
