### PR TITLE
hygiene: Do not treat `Self` ctor as a local variable

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/57523

### CODE REVIEW

**Comment by Centril** [comment]
Apparently bors hasn't rebooted yet...

@bors delegate=alexreg

**Comment by alexreg** [comment]
This is a small delta and looks totally fine to me, so I'm going to go ahead and r+ it. Travis would fail before Bors gets around to it anyway...

@bors r+

**Comment by petrochenkov** [comment]
@varkor 
The type alias case is necessary.
The `SelfTy` case is necessary only in corner cases when we have `Self` in type namespace, but not in value namespace (i.e. probably not necessary in practice).

**Pull request merged**
