### PR TITLE
Fix PEP8 style issues in bootstrap code

### PR DESCRIPTION
**Pull request by johnthagen**
This fixes PEP8 style issues (other than line-length) in the bootstrap Python code.

The most important fix is in the `set` function where the code was indented with 6 spaces instead of 4.

### CODE REVIEW

**Comment by carols10cents** [comment]
Actually, @aturon wasn't available last week and is on PTO this week, so let's try....

r? @alexcrichton

**Comment by johnthagen** [comment]
@alexcrichton I'll work on resolving these conflicts later today.

**Comment by johnthagen** [comment]
Conflicts resolved.

**Pull request merged**
