### PR TITLE
Document LTR vs RTL wrt trim_*

### LINKED ISSUE #30459: str's trim_left and trim_right implicitly assume LTR text
These functions and their `_matches` variants operate on the start and end of the string, which are only the left and right (respectively) of the displayed text when rendered left-to-right like English. For (readers/users of) RTL languages, `trim_right` is hinting that it will be trimming the prefix, but this is of course not the case (and similarly for `_left`).

These are stable and there is precedent in other languages for left/right e.g. Python (there's also significant precedent for start/end), so we may not be able/want to do anything here, but it seems worth noting.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #30459

Fun fact: i wanted to write "Arabic" and "Hebrew" in Arabic and Hebrew, but vim kept doing the copy/paste in the wrong direction.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Perhaps LTR and RTL could be expanded? Took me a second to figure out what that meant. Or it may be canonical enough and I could just be ignorant.

r=me either way!

**Comment by huonw** [comment]
I'm not sure this should close #30459: on one hand, it's as good as we can do wrt that issue for now, but, on the other, it'll be easy to loose track of it once we do get the tooling.

**Comment by steveklabnik** [comment]
> Or it may be canonical enough and I could just be ignorant.

I'm not sure either... they're canonical for people who talk about text, but do we want to assume that? I'm not sure. @SimonSapin what do you think?

> I'm not sure this should close #30459:

Ah, that's true. I guess I was seeing it through the docs lens, but you're probably right.

**Comment by SimonSapin** [comment]
I agree that not every reader of the docs is necessarily familiar with these acronyms, and not using them is easy here. “LTR vs RTL” could be replaced with “Text directionality” for example.

**Comment by SimonSapin** [comment]
And yes, not everyone is familiar with text directionality either, but it’s less obscure than acronyms and explained below.

**Comment by nodakai** [comment]
Can you add several doctests?  For example, [according to Wikipedia](https://en.wikipedia.org/wiki/Hebrew_language), a Hebrew word for Hebrew (language) is "עברית" and its romanization is "ivrit".  Its **last** character is ["ת" aka "tav"](https://en.wikipedia.org/wiki/Taw) which corresponds to a roman alphabet "t".

```rust
fn f(s: &str, fc: char, lc: char) {
    assert!(fc == s.trim_left().chars().next().unwrap());
    assert!(lc == s.trim_right().chars().last().unwrap());
}

fn main() {
    f("  English  ", 'E', 'h');
    f("  עברית  ",
'ע',
'ת');
}
```
- http://is.gd/BuuZ9

**Comment by steveklabnik** [comment]
re- r? @alexcrichton 

I've added the doc tests that @nodakai asked about :+1:

**Comment by steveklabnik** [comment]
@bors: r=alexcrichton rollup

I did a dumb thing, and it's fixed now.

**Pull request merged**
