### PR TITLE
Revert "Revert "std: Re-enable at_exit()""

### LINKED ISSUE #20012: Resolve at_exit strategy after std::thread lands
The [final step](https://github.com/rust-lang/rust/pull/19654) of runtime removal changes the threading/process model so that the process shuts down when the main thread exits. But several shared resources, like the helper thread for timeouts, are shut down when the main thread exits (but before the process ends), and they are not prepared to be used after shut down, but other threads may try to access them during the shutdown sequence of the main thread.

As an interim solution, the `at_exit` cleanup routine is simply skipped.

Ultimately, these resources should be made to safely handle asynchronous shutdown, usually by panicking if called from a detached thread when the main thread is ending.

### PR DESCRIPTION
**Pull request by alexcrichton**
This reverts commit aec67c2.

Closes #20012

This is temporarily rebased on #23245 as it would otherwise conflict, the last commit is the only one relevant to this PR though.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I should also point out that this has bounced many times on windows previously, but I've run it through my own windows VM and it passed through try with only win32 timing out (this has been seen before as well). Not to say that it'll actually pass though...

**Comment by Manishearth** [comment]
```
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:87:5: 87:26 error: unused import, #[deny(unused_imports)] on by default
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:87 use os::unix::prelude::*;
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:89:17: 89:24 error: unused import, #[deny(unused_imports)] on by default
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:89 use ffi::{CStr, AsOsStr};
                                                                                                                      ^~~~~~~
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:61:13: 65:14 error: unnecessary `unsafe` block, #[deny(unused_unsafe)] on by default
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:61             unsafe {
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:62                 let info = info();
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:63                 let diff = self.t as i64 - other.t as i64;
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:64                 Duration::nanoseconds(diff * info.numer as i64 / info.denom as i64)
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:65             }
error: aborting due to 3 previous errors
make: *** [x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/stamp.std] Error 101
```

**Comment by Manishearth** [comment]
(Could this perhaps be a legitimate test hanging?)

**Comment by Manishearth** [comment]
```
---- [run-fail] run-fail/rt-set-exit-status-panic2.rs stdout ----
	
error: failure produced the wrong error: exit code: 0
status: exit code: 0
command: PATH="i686-pc-windows-gnu/stage2/bin/rustlib/i686-pc-windows-gnu/lib;C:\bot\slave\auto-win-32-opt\build\obj\i686-pc-windows-gnu\stage2\bin;C:\program files (x86)\mingw-w64\i686-4.9.1-win32-dwarf-rt_v3-rev1\mingw32\bin;C:\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\msys64\usr\bin;C:\python27;C:\python27\scripts;C:\program files (x86)\inno setup 5;C:\program files (x86)\CMake\bin" i686-pc-windows-gnu/test/run-fail\rt-set-exit-status-panic2.stage2-i686-pc-windows-gnu.exe 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
ERROR:rt-set-exit-status-panic2: whatever
thread '<main>' panicked at 'explicit panic', C:/bot/slave/auto-win-32-opt/build/src/test/run-fail/rt-set-exit-status-panic2.rs:41

------------------------------------------

thread '[run-fail] run-fail/rt-set-exit-status-panic2.rs' panicked at 'explicit panic', C:/bot/slave/auto-win-32-opt/build/src/compiletest\runtest.rs:1479



failures:
    [run-fail] run-fail/rt-set-exit-status-panic2.rs
```

Progress!

**Comment by Manishearth** [comment]
@bors: retry

*shakes fist at buildbot*

**Comment by sfackler** [comment]
Seems like it's probably a legit problem at this point.

**Comment by Manishearth** [comment]
Yeah, probably.

**Comment by alexcrichton** [comment]
@bors: r=aturon 9c18736

(btw I would not recommend putting this PR into a rollup)

**Comment by Manishearth** [comment]
@bors: p=1

(not included in rollup, might as well prioritize it over the other rolled up PRs)

**Comment by alexcrichton** [comment]
40th time's the charm!

**Pull request merged**
