### PR TITLE
rustc_ast_passes: allow c-variadic associated fns

### PR DESCRIPTION
**Pull request by dlrobertson**
- Allow c-variadic associated functions
 - Add test for c-variadic functions in the Impl context

Related To: #44930 
CC: @jethrogb @sarvi 
r? @joshtriplett

### CODE REVIEW

**Review by joshtriplett — CHANGES_REQUESTED** [review]
Please also add some tests that the functions work as expected, retrieving passed variadic arguments.

Ideally, I would love to see the same tests away used for free functions applied to these cases too, perhaps with a macro to avoid duplication.

**Comment by dlrobertson** [comment]
> Please also add some tests that the functions work as expected, retrieving passed variadic arguments.
> 
> Ideally, I would love to see the same tests away used for free functions applied to these cases too, perhaps with a macro to avoid duplication.

Sounds good.

**Comment by dlrobertson** [comment]
@joshtriplett added a run-pass test. Is this what you're looking for?

**Comment by crlf0710** [comment]
@dlrobertson Ping from triage, could you address the review comments? thanks

**Comment by dlrobertson** [comment]
@crlf0710 thanks for the ping, I've also rebased on master.

@joshtriplett I added a run-pass test, but I didn't change the run-make tests. After looking into this a bit more I realized that if the output is a c library we're not going to make symbol `foo` visible for the function `Foo::foo`. So I think the only case that this is valid for is a case where the variadics are going to be used entirely within rust.

**Comment by Dylan-DPC** [comment]
@joshtriplett this is ready for review

**Review by joshtriplett — APPROVED** [review]

**Comment by dlrobertson** [comment]
Looking at this now... not immediately sure why this would fail on arm-android

**Comment by Dylan-DPC** [comment]
@dlrobertson any updates?

**Comment by crlf0710** [comment]
@dlrobertson Ping from triage: What's the current status of this?

**Comment by dlrobertson** [comment]
No updates on why this is failing on android, but after looking at this more I'm not sure why we would add this. A member function wouldn't be exported right? So really this would only be used for a Rust C-variadic function that was used in another rust function. Would that be considered an anti-pattern?

CC @joshtriplett

**Comment by tmiasko** [comment]
The `CStr::from_ptr` takes `*const c_char` as an argument. The sign of char type is implementation defined in C and on Android happens to be different from the one assumed in the test case here.

**Comment by joshtriplett** [comment]
@dlrobertson wrote:
> No updates on why this is failing on android, but after looking at this more I'm not sure why we would add this. A member function wouldn't be exported right? So really this would only be used for a Rust C-variadic function that was used in another rust function. Would that be considered an anti-pattern?

This isn't about member functions; this is about associated functions (which don't take `self`). There are good reasons to want to have a C-compatible associated function; you might pass such a function as a pointer, for instance.

**Comment by crlf0710** [comment]
@dlrobertson  Triage: I'm closing this due to inactivity. Feel free to reopen or create a new pr when you've got time to work on this again. Thanks!

**Pull request closed without merging**
