### PR TITLE
[WIP] make LUB of higher-ranked things actually do EQ

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is an experimental PR that I'm posting for the purposes of observing its effects via cargobomb (a crater run showed [no regressions](https://gist.github.com/nikomatsakis/5aaf3782b4332a3ba408315cc84f69bf)). The existing LUB/GLB code does some rather complex things around higher-ranked types (notably, grubbing about with region constraints) that I would like to move away from. I am not sure how often it is important in practice. This branch converts LUB/GLB of higher-ranked things into EQ.

r? @eddyb (this is just an experiment, don't really review =)

### CODE REVIEW

**Comment by eddyb** [comment]
cc @rust-lang/infra Cargobomb run requested.

**Comment by Mark-Simulacrum** [comment]
Marking as waiting on author since Travis failed. If these are intentional failures, please let us (infra team) know!

```
[01:07:43] running 23 tests
[01:07:43] ....FFFFFF.F.FFF.......
[01:07:43] failures:
[01:07:43]
[01:07:43] ---- test::glb_bound_free_infer stdout ----
[01:07:43]  thread 'test::glb_bound_free_infer' panicked at 'unexpected error computing LUB: RegionsInsufficientlyPolymorphic(BrAnon(1), '_#1r)', /checkout/src/librustc_driver/test.rs:418:22
[01:07:43] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:07:43]
[01:07:43] ---- test::glb_bound_free stdout ----
[01:07:43]  thread 'test::glb_bound_free' panicked at 'unexpected error computing LUB: RegionsInsufficientlyPolymorphic(BrAnon(1), ReFree(DefId { krate: CrateNum(0), node: DefIndex(0) => test_crate/8cd878b }, BrAnon(1)))', /checkout/src/l
ibrustc_driver/test.rs:418:22
[01:07:43]
[01:07:43] ---- test::glb_bound_static stdout ----
[01:07:43]  thread 'test::glb_bound_static' panicked at 'unexpected error computing LUB: RegionsInsufficientlyPolymorphic(BrAnon(1), ReStatic)', /checkout/src/librustc_driver/test.rs:418:22
[01:07:43]
[01:07:43] ---- test::glb_free_free_with_common_scope stdout ----
[01:07:43]  thread 'test::glb_free_free_with_common_scope' panicked at 'Unexpected error: mismatched types Expected: []', /checkout/src/librustc_driver/test.rs:78:12
[01:07:43]
[01:07:43] ---- test::lub_bound_bound_inverse_order stdout ----
[01:07:43]  thread 'test::lub_bound_bound_inverse_order' panicked at 'unexpected error in LUB: expected bound lifetime parameterBrAnon(2), found concrete lifetime', /checkout/src/librustc_driver/test.rs:410:26
[01:07:43]
[01:07:43] ---- test::lub_bound_free stdout ----
[01:07:43]  thread 'test::lub_bound_free' panicked at 'unexpected error in LUB: expected bound lifetime parameterBrAnon(1), found concrete lifetime', /checkout/src/librustc_driver/test.rs:410:26
[01:07:43]
[01:07:43] ---- test::lub_bound_static stdout ----
[01:07:43]  thread 'test::lub_bound_static' panicked at 'unexpected error in LUB: expected bound lifetime parameterBrAnon(1), found concrete lifetime', /checkout/src/librustc_driver/test.rs:410:26
[01:07:43]
[01:07:43] ---- test::lub_free_bound_infer stdout ----
[01:07:43]  thread 'test::lub_free_bound_infer' panicked at 'unexpected error in LUB: expected bound lifetime parameterBrAnon(1), found concrete lifetime', /checkout/src/librustc_driver/test.rs:410:26
[01:07:43]
[01:07:43] ---- test::lub_returning_scope stdout ----
[01:07:43]  thread 'test::lub_returning_scope' panicked at 'Unexpected error: mismatched types Expected: []', /checkout/src/librustc_driver/test.rs:78:12
[01:07:43]
[01:07:43] ---- test::lub_free_free stdout ----
[01:07:43]  thread 'test::lub_free_free' panicked at 'Unexpected error: mismatched types Expected: []', /checkout/src/librustc_driver/test.rs:78:12
[01:07:43]
[01:07:43]
[01:07:43] failures:
[01:07:43]     test::glb_bound_free
[01:07:43]     test::glb_bound_free_infer
[01:07:43]     test::glb_bound_static
[01:07:43]     test::glb_free_free_with_common_scope
[01:07:43]     test::lub_bound_bound_inverse_order
[01:07:43]     test::lub_bound_free
[01:07:43]     test::lub_bound_static
[01:07:43]     test::lub_free_bound_infer
[01:07:43]     test::lub_free_free
[01:07:43]     test::lub_returning_scope
```

**Comment by aidanhs** [comment]
Cargobomb run started. Sorry for the delay, we didn't have spare boxes and then I was away for a few days.

**Comment by Mark-Simulacrum** [comment]
Run is complete: http://cargobomb-reports.s3.amazonaws.com/pr-44211/index.html. 15 regressions straight off, but haven't triaged.

**Comment by eddyb** [comment]
@nikomatsakis Looks like no actual regressions to me, only some flaky tests and timeouts.

**Comment by arielb1** [comment]
Given that there were no regressions of crater, I think we can merge this.

However, I would like it if on an LUB failure, we could at least have a special error message warning on the new compiler update.

**Comment by eddyb** [comment]
@arielb1 from what @nikomatsakis was telling me, this branch is only an experiment to confirm that *a separate reimplementation strategy* could work without breaking existing code.

**Comment by nikomatsakis** [comment]
While @eddyb is correct, now that the experiment was successful, I've been contemplating landing (some variant of) this branch, just to pave the way for the future work. It should be possible to make a variant of this that offers a specialized error message, at least.

**Comment by aidanhs** [comment]
@nikomatsakis just pinging you for triage purposes to see how your contemplation of this PR mentioned in your last comment is going :)

**Comment by aidanhs** [comment]
@nikomatsakis ping again to see where this PR is up to! If this was just an experimental PR, maybe worth closing and reopening a fresh one with changes to be reviewed/merged?

**Comment by nikomatsakis** [comment]
@aidanhs I think we've decided to turn into something a bit more than experimental. I'm still hoping to refresh the approach in the next day or two, so I'm inclined not to close *just yet*.

**Comment by carols10cents** [comment]
> I'm still hoping to refresh the approach in the next day or two, so I'm inclined not to close just yet.

> 7 days ago

Triage ping! How's it going?

**Comment by nikomatsakis** [comment]
Some progress, got blocked by other things.

**Comment by shepmaster** [comment]
This has been inactive for 18 days, so I'm going to go ahead and close this to keep things tidy. As always, please reopen once some updates happen! Thanks!

**Pull request closed without merging**
