### PR TITLE
Add a test for trait solver overflow in MIR inliner cycle detection

### PR DESCRIPTION
**Pull request by saethlin**
This test is a combination of the reproducer posted here: https://github.com/rust-lang/rust/issues/128887#issuecomment-2314198229 and the existing test for polymorphic recursion: https://github.com/rust-lang/rust/blob/784d444733d65c3d305ce5edcbb41e3d0d0aee2e/tests/mir-opt/inline/polymorphic_recursion.rs

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
thank, i really appreciate the time you took to actually turn this into a test

@bors r+ rollup

**Comment by saethlin** [comment]
CI is happy
@bors r=compiler-errors

**Pull request merged**
