### PR TITLE
Move some tests to more reasonable directories - 8

### PR DESCRIPTION
**Pull request by c410-f3r**
cc #73494
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
Could you also update the limits in tidy?

**Comment by c410-f3r** [comment]
OK. I **think** I addressed all concerns but feel free to point any other misplacement.

**Comment by c410-f3r** [comment]
Couldn't reproduce the error locally for some reason

**Comment by petrochenkov** [comment]
issue-2748-b.rs (lifetime.rs after renaming) - still can be removed
byte-literals.rs - please don't remove this one
issue-16602-3.rs - please don't remove this one
issue-30355.rs -> unsized
issue-44005.rs - failing on CI, I think you can omit it from this PR

**Comment by c410-f3r** [comment]
> issue-2748-b.rs (lifetime.rs after renaming) - still can be removed byte-literals.rs - please don't remove this one issue-16602-3.rs - please don't remove this one issue-30355.rs -> unsized issue-44005.rs - failing on CI, I think you can omit it from this PR

Done

**Comment by c410-f3r** [comment]
```
  = note: LINK : fatal error LNK1201: error writing to program database 'D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\tmp\cit\t1287\foo\target\release\deps\test.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
```

Spurious error?

**Pull request merged**
