### PR TITLE
Updated error message E0388

### LINKED ISSUE #35339: E0388 needs to be updated to new format
From: src/test/compile-fail/E0017.rs

Error E0388 needs a span_label, updating it from:

```
error[E0388]: cannot borrow data mutably in a static location
  --> src/test/compile-fail/E0017.rs:16:39
   |
16 | static STATIC_REF: &'static mut i32 = &mut X; //~ ERROR E0017
   |                                       ^^^^^^
```

To:

```
error[E0388]: cannot borrow data mutably in a static location
  --> src/test/compile-fail/E0017.rs:16:39
   |
16 | static STATIC_REF: &'static mut i32 = &mut X; //~ ERROR E0017
   |                                       ^^^^^^ cannot mutably borrow in static
```

### PR DESCRIPTION
**Pull request by medzin**
Fixes #35339 as part of #35233.

r? @GuillaumeGomez

### CODE REVIEW

**Comment by arielb1** [comment]
The error can also be "cannot assign in a static". I think the label should be "bad mutation here".

Also, the label can apply to all the error codes in the function - put it before the `help`.

**Comment by jonathandturner** [comment]
@arielb1 - trying to come up with a good wording.  What do you mean by "cannot assign in a static".  You can assign to a static, no?  What are the cases you can't?

**Comment by medzin** [comment]
@arielb1 & @jonathandturner So, what should I change? I'm a little confused here.

**Comment by arielb1** [comment]
I would like the label "invalid mutation here".

**Comment by jonathandturner** [comment]
@medzin - sorry for the confusion!

We ended up chatting (and I also chatted with @nikomatsakis) and he had this suggestion: "cannot write data in a static definition"

Please use this for now.  If we need to update it later, we can do it in a different PR.

**Comment by medzin** [comment]
Message changed.

**Comment by jonathandturner** [comment]
Sorry for the delay!  I forgot I hadn't approved this one.

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
@bors: r-

@medzin: Please squash your commits.

**Comment by medzin** [comment]
@GuillaumeGomez Done

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
