### PR TITLE
[beta] rustdoc: fix line numbers display for [src] pages

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Backporting https://github.com/rust-lang/rust/pull/56498

Fixes https://github.com/rust-lang/rust/issues/56720

r? @GuillaumeGomez

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Something i found while looking at the CSS that i missed on the original PR: there's another `body:not(.source)` right below the rules that were changed in the original. Should we fix that on master and here?

https://github.com/rust-lang/rust/blob/f4b07e0713b2d82417968db08cd0575734cdac0d/src/librustdoc/html/static/rustdoc.css#L308-L310

**Comment by GuillaumeGomez** [comment]
Indeed, sending a PR right away!

**Comment by QuietMisdreavus** [comment]
I pushed a commit that includes the change from https://github.com/rust-lang/rust/pull/56844.

**Comment by pietroalbini** [comment]
Rolled this up.

**Pull request merged**
