### PR TITLE
only assemble alias bound candidates for rigid aliases

### LINKED ISSUE #77: alias-bounds for normalizable alias + deeply normalize ~> MIR typeck ICE
```rust
trait Trait {
    type Assoc: Clone;
}

fn is_clone<T: Clone>(_: *mut T) {}

fn foo<T: Trait<Assoc = U>, U>(x: *mut <T as Trait>::Assoc) {
    is_clone(x);
}
```
https://rust.godbolt.org/z/4WojT7KTW

This currently results in an ICE:
- in HIR typeck `<T as Trait>::Assoc: Clone` holds due to the alias bound candidate
- during writeback we deeply normalize, replacing `<T as Trait>::Assoc` with `U`
- MIR typeck checks `U: Clone` which does not hold, resulting in an ICE

### PR DESCRIPTION
**Pull request by lcnr**
fixes https://github.com/rust-lang/trait-system-refactor-initiative/issues/77

This also causes `<Wrapper<?0> as Trait>::Unwrap: Trait` to always be ambig, as we now normalize the self type before checking whether it is an inference variable.

I cannot think of an approach to the underlying issues here which does not require the "may-define means must-define" restriction for opaque types. Going to go ahead with this and added this restriction to the tracking issue for the new solver to make sure we don't stabilize it without getting types + lang signoff here.
 
r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
This ensures that the code I extracted from gimli works:

```
trait Reader: Default {
    fn read_u8_array<A>(&self) -> Result<A, ()>
    {
        todo!()
    }

    fn read_u8(&self) -> Result<u8, ()> {
        let a: [u8; 1] = self.read_u8_array::<_>()?;
        Ok(a[0])
    }
}

fn main() {}
```

Plz add it as a test, whether you want to minimize it further or not is up to you.

This has to do with taking `<Result<?0, ()> as Try>::Residual: Sized` and eagerly unifying it against `Self: Sized` in the param-env incompletely -- the old solver doesn't do this since it'll normalize `<Result<?0, ()> as Try>::Residual` to `?0` and the sized predicate will stall before erroneous inference is done to it.

**Comment by lcnr** [comment]
blocked on #117861

**Review by compiler-errors — APPROVED** [review]

**Pull request merged**
