### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #90001 (Make rlib metadata strip works with MIPSr6 architecture)
 - #91687 (rustdoc: do not emit tuple variant fields if none are documented)
 - #91938 (Add `std::error::Report` type)
 - #92006 (Welcome opaque types into the fold)
 - #92142 ([code coverage] Fix missing dead code in modules that are never called)
 - #92277 (rustc_metadata: Stop passing `CrateMetadataRef` by reference (step 1))
 - #92334 (rustdoc: Preserve rendering of macro_rules matchers when possible)
 - #92807 (Update cargo)
 - #92832 (Update RELEASES for 1.58.)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=90001,91687,91938,92006,92142,92277,92334,92807,92832)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors retry hang in i686-msvc1

````
Thu, 13 Jan 2022 15:29:49 GMT [TIMING] Crate { compiler: Compiler { stage: 2, host: TargetSelection { triple: "i686-pc-windows-msvc", file: None } }, target: TargetSelection { triple: "i686-pc-windows-msvc", file: None }, mode: Rustc, test_kind: Test, krate: "rustc_log" } -- 2.293
Thu, 13 Jan 2022 15:29:49 GMT [TIMING] CrateLibrustc { compiler: Compiler { stage: 2, host: TargetSelection { triple: "i686-pc-windows-msvc", file: None } }, target: TargetSelection { triple: "i686-pc-windows-msvc", file: None }, test_kind: Test, krate: "rustc_log" } -- 0.000
Thu, 13 Jan 2022 15:29:49 GMT Set({"compiler\\rustc_macros"}) not skipped for "bootstrap::test::CrateLibrustc" -- not in ["src/test/ui", "src/tools/linkchecker"]
Thu, 13 Jan 2022 15:29:49 GMT Testing rustc_macros stage1 (i686-pc-windows-msvc -> i686-pc-windows-msvc)
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] build_script_build test:false 0.905
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] unicode_xid test:false 0.206
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] build_script_build test:false 0.796
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] proc_macro2 test:false 2.331
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] quote test:false 0.879
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] syn test:false 21.828
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] synstructure test:false 2.608
Thu, 13 Jan 2022 15:29:50 GMT [RUSTC-TIMING] rustc_macros test:false 5.577
Thu, 13 Jan 2022 15:29:50 GMT    Compiling rustc_macros v0.1.0 (D:\a\rust\rust\compiler\rustc_macros)
Thu, 13 Jan 2022 18:52:15 GMT Error: The operation was canceled.
````
https://github.com/rust-lang-ci/rust/runs/4804580236?check_suite_focus=true

**Comment by ehuss** [comment]
@bors retry

arm-android hung

**Comment by matthiaskrgr** [comment]
Hm, a lot of regressions :/
@oli-obk do you think this could be related to https://github.com/rust-lang/rust/pull/92006 ?

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/pull/92928

**Pull request merged**
