### PR TITLE
Disallow underscore suffix for string-like literals.

### PR DESCRIPTION
**Pull request by qnighy**
This patch turns string/bytestring/char/byte literals followed by an underscore, like `"Foo"_`, to an error.

`scan_optional_raw_name` will parse `_` as a valid raw name, but it will be rejected by the parser. I also considered just stopping parsing when the suffix is `_`, but in that case `"Foo"_` will be lexed as two valid tokens.

Fixes the latter half of #41723.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Thanks for the PR! We'll periodically check in to make sure that @pnkfelix or someone else from the team review it soon.

**Comment by shepmaster** [comment]
I've pinged @pnkfelix on IRC as a reminder to review this PR. Fear not, @qnighy, you will get your review! 😺

**Comment by withoutboats** [comment]
I was curious what the original cause of this was, since it seems like the compiler explicitly allowed it, and [here it is](https://github.com/rust-lang/rust/pull/19103) (2014!). This was intended to just be future proofing for literal suffixes (probably so you could theoretically write custom string literal types). It looks like `_` was singled out to act as if it had no suffix (which makes sense), but that incidentally enabled it to parse.

**Comment by nrc** [comment]
@qnighy  Since this is technically a breaking change, it would be good to make this into a warning for a 6-week cycle before making it an error. It looks like that shouldn't be too hard to do here - you'd need to emit a warning in the `_` branch of the `if` expression here.

**Comment by qnighy** [comment]
@nrc It seems that we have to delay the check to `ast_validation` because `syntax` doesn't know `rustc_lint`?

**Comment by nrc** [comment]
Maybe someone else on @rust-lang/compiler will correct me, but I think it is fine to hard-wire a warning rather than use lints.

**Comment by qnighy** [comment]
It looks harder if we have to use lints instead of warnings. We would have to propagate suffix information to AST.

**Comment by qnighy** [comment]
OK, I will try to implement it using warnings.

**Comment by qnighy** [comment]
Implemented the warning cycle #42326 without lint. This would be sufficient unless lint is preferred.

**Comment by nikomatsakis** [comment]
Hmm, lints are preferred, but I agree that will be difficult since this message appears so early (in the lexer). I can live with the "hard warning" you have here. It does mean that we don't have the option the "deny by default" half-step -- we just have to move to a hard error, but that seems ok in this case.

(I guess we could continue issuing a warning if "cap-lints" is enabled, but that feels unnecessary).

**Comment by Mark-Simulacrum** [comment]
@nrc @nikomatsakis This looks like it's ready to go -- is that correct? I don't want to r+ since there may be some unresolved questions.

**Comment by nikomatsakis** [comment]
I agree, this is good to go.

**Pull request merged**
