### PR TITLE
Rename `config.toml.example` to `config.example.toml`

### PR DESCRIPTION
**Pull request by thomcc**
This had bothered me for a while as it leads to bad (missing) syntax highlighting in most editors I've used, and @jyn514 suggested I just make the change and that the compatibility concerns I had don't really matter.

I suspect it will be a contentious one, so will not be offended if the outcome of this is to close the PR.

### CODE REVIEW

**Comment by thomcc** [comment]
Does t-bootstap do FCPs? It doesn't seem like it, but if they do this should possibly have a needs-fcp tag.

**Comment by clubby789** [comment]
This also makes tab completing a bit easier:
`config.toml` -> `config.toml / config.toml.example`
to
`config.e` -> `config.example.toml`

**Review by jyn514 — APPROVED** [review]
I think this is a good idea. Can you also make a PR updating the dev guide?

**Comment by ozkanonur** [comment]
I think we should merge this once the dev-guide PR is ready and open

**Comment by tshepang** [comment]
why is this blocked @ozkanonur

**Comment by ozkanonur** [comment]
> I think we should merge this once the dev-guide PR is ready and open

We will have outdated docs if we merge this before updating dev guide.

**Pull request merged**
