### PR TITLE
Don't catch overflow when running with cargo doc

### LINKED ISSUE #100991: Recursion limit tripped in doc but not in other profiles
The diesel benchmark has been broken in some recent commit: https://perf.rust-lang.org/status.html.

ref: [zulip comment](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/.60diesel.60.20benchmark.20broken/near/295189845)

### PR DESCRIPTION
**Pull request by ouz-a**
Fixes #100991

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
The primary results look like the opposite of the perf results in #100705, and the rest is probably noise given the nature of the changes in this PR. This is fine to me.

@ouz-a, can you squash this into one commit, then r=me.

@bors delegate+

**Comment by compiler-errors** [comment]
I think this may just be noise, as far as I can tell @ouz-a didn't change the code since the last time we ran perf ^

**Comment by rylev** [comment]
The primary regressions do seem like noise (as they are reversed in the next perf run), but the secondary regressions seem like sustained regressions. 

GitHub does show a commit *after* the perf results so perhaps code was pushed by @ouz-a? However, the change is a single boolean check which makes this unlikely to be a reall issue.

**Comment by rylev** [comment]
I'm going to mark this as triaged since the biggest regressions are noise. Given this is a small change and a needed fix, I don't think we need to address this. 

@rustbot label: +perf-regression-triaged

**Pull request merged**
