### PR TITLE
Tidy up maybe_uninit_write_slice API

### PR DESCRIPTION
**Pull request by SUPERCILEX**
- Move methods to extensions

### CODE REVIEW

**Comment by scottmcm** [comment]
Thanks for the PR!

While I'm sometimes willing to add new APIs without libs-api assent, I'm much more worried about churning signatures without contacting them to see if they like them, since it would be a shame to find out they didn't and have to revert it and have impacted nightly users unnecessarily.

Could you please [file an ACP](https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html) for this set of changes (I think #103128 #103130 #103131 could probably all be one) to get a "yup, that seems better" from the team?

@rustbot author

**Comment by Dylan-DPC** [comment]
@SUPERCILEX any updates on this?

**Comment by SUPERCILEX** [comment]
I'm not quite sure what the status is: https://github.com/rust-lang/libs-team/issues/122#issuecomment-1320960065

We generally agreed that these slice methods shouldn't exist, but they'll probably be here for a while. I do think that if we end up stabilizing them, it should be like this, not as a static method. The hope would be that they never need to get stabilized though.

**Comment by SUPERCILEX** [comment]
See https://github.com/rust-lang/libs-team/issues/122#issuecomment-1385409719. These are a bit too heavy weight to become inherent methods. I still think they should be renamed, but that can be discussed before stabilization.

**Pull request closed without merging**
