### PR TITLE
Make rustdoc output comply with licenses

### PR DESCRIPTION
**Pull request by ruuda**
The output of rustdoc includes resources licensed under the SIL Open
Font License, the MIT license, and the Apache License 2.0. All of these
licenses permit redistribution provided that the license text is also
redistributed. Previously this was not the case, making rustdoc output
unsuitable for distribution by default. This resolves that problem by
including the license texts in rustdoc output.

See also: https://users.rust-lang.org/t/licensing-rustdoc-output/2880

### CODE REVIEW

**Comment by brson** [comment]
Thanks!

This looks fine to me as the simplest solution that will work. The only concern I have here is that it's not clear what MIT/Apache 2.0 apply to. Perhaps a top-level COPYRIGHT file (like in the rust tree), that explains more precisely which components are covered by what, and that the *content* is not covered. What do you think about that @ruud-v-a?

cc @alexcrichton @aturon

**Comment by ruud-v-a** [comment]
Good idea. Something like this?

**Comment by alexcrichton** [comment]
I've always personally on the side of just removing all our font business, it's ended up being a never-ending series of small paper cuts, but other than that this seems fine.

**Comment by Manishearth** [comment]
Updates?

**Pull request merged**
