### PR TITLE
added support for GNU/Hurd on x86_64

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by sthibaul** [comment]
Concerning the Tier 3 target policy, the answers are essentially the same as on https://github.com/rust-lang/rust/pull/115230 : I'll be maintainer, the triplet is the same as in llvm: x86_64-unknown-hurd-gnu, this is essentially the 64bit version of the existing i686-unknown-hurd-gnu target.

**Comment by Urgau** [comment]
@sthibaul Since there wasn't a MCP for adding this target *(not required for Tier 3)* and https://github.com/rust-lang/rust/pull/115230#issuecomment-1694023251 was strictly speaking only for `i686-unknown-hurd-gnu`, I think this at least requires a new [Tier 3 target policy](https://doc.rust-lang.org/rustc/target-tier-policy.html#tier-3-target-policy) fill out, even if it's mostly copy-pasted from the other one. It would great if you could post one.

@rustbot author
r? @Urgau

**Comment by sthibaul** [comment]
Ok, here it is:

> Tier 3 target policy
> 
> A tier 3 target must have a designated developer or developers (the "target maintainers") on record to be CCed when issues arise regarding the target. (The mechanism to track and CC such developers may evolve over time.)

We added myself as target maintainer.

> Targets must use naming consistent with any existing targets; for instance, a target for the same CPU or OS as an existing Rust target should use the same name for that CPU or OS. Targets should normally use the same names and naming conventions as used elsewhere in the broader ecosystem beyond Rust (such as in other toolchains), unless they have a very good reason to diverge. Changing the name of a target can be highly disruptive, especially once the target reaches a higher tier, so getting the name right is important even for a tier 3 target.

We used the same target named as used in llvm: x86_64-unknown-hurd-gnu

> Target names should not introduce undue confusion or ambiguity unless absolutely necessary to maintain ecosystem compatibility. For example, if the name of the target makes people extremely likely to form incorrect beliefs about what it targets, the name should be changed or augmented to disambiguate it.

GNU tools use x86_64-unknown-gnu and that indeed sometimes bring confusion, that's why we used the llvm triplet.

> If possible, use only letters, numbers, dashes and underscores for the name. Periods (.) are known to cause issues in Cargo.

That's alright here.

> Tier 3 targets may have unusual requirements to build or use, but must not create legal issues or impose onerous 
legal terms for the Rust project or for Rust developers or users.

The target legal terms are basically like the Linux ecosystem.

> The target must not introduce license incompatibilities.
> Anything added to the Rust repository must be under the standard Rust license (MIT OR Apache-2.0).

Agreed.

> The target must not cause the Rust tools or libraries built for any other host (even when supporting cross-compilation to the target) to depend on any new dependency less permissive than the Rust licensing policy.

GNU/Hurd uses the GNU toolchain, like Linux.

> Compiling, linking, and emitting functional binaries, libraries, or other code for the target (whether hosted on the target itself or cross-compiling from another target) must not depend on proprietary (non-FOSS) libraries.

The whole point of the GNU project is exactly that :)

> Host tools built for the target itself may depend on the ordinary runtime libraries supplied by the platform and commonly used by other applications built for the target, but those libraries must not be required for code generation for the target; cross-compilation to the target must not require such libraries at all. For instance, rustc built for the target may depend on a common proprietary C runtime library or console output library, but must not depend on a proprietary code generation library or code optimization library. Rust's license permits such combinations, but the Rust project has no interest in maintaining such combinations within the scope of Rust itself, even at tier 3.

This is the same situation as linux, since we use the GNU toolchain and libc.

> Neither this policy nor any decisions made regarding targets shall create any binding agreement or estoppel by any party.

That is also the kind of goals of the GNU project :)

> Tier 3 targets should attempt to implement as much of the standard libraries as possible and appropriate (core for most targets, alloc for targets that can support dynamic memory allocation, std for targets with an operating system or equivalent layer of system-provided functionality),

We do have core/alloc/std.

> The target must provide documentation for the Rust community explaining how to build for the target, using cross-compilation if possible. If the target supports running binaries, or running tests (even if they do not pass), the documentation must explain how to run such binaries or tests for the target, using emulation if possible or dedicated hardware if necessary.

The documentation was added. Running tests can be done in a qemu VM for instance, pre-built installed images are available.

> Tier 3 targets must not impose burden on the authors of pull requests, or other developers in the community, to maintain the target. In particular, do not post comments (automated or manual) on a PR that derail or suggest a block on the PR based on a tier 3 target. Do not send automated messages or notifications (via any medium, including via @) to a PR author or others involved with a PR regarding a tier 3 target, unless they have opted into such messages.

Ok, sure!

> Patches adding or updating tier 3 targets must not break any existing tier 2 or tier 1 target,

We believe our additions didn't break anything, and we will watch CI anyway.

> and must not knowingly break another tier 3 target without approval of either the compiler team or the maintainers of the other tier 3 target.

Sure!

> If a tier 3 target stops meeting these requirements, or the target maintainers no longer have interest or time, or the target shows no signs of activity and has not built for some time, or removing the target would improve the quality of the Rust codebase, we may post a PR to remove it; any such PR will be CCed to the target maintainers (and potentially other people who have previously worked on the target), to check potential interest in improving the situation.

Ok!

**Review by Urgau — APPROVED** [review]

**Comment by workingjubilee** [comment]
Sorry, this needs a rebase on latest.

**Comment by sthibaul** [comment]
@workingjubilee I'm not sure how the rebase will help, but done so

@rustbot review

**Comment by sthibaul** [comment]
Ah, sorry, I had assumed that a mingw profile build would have been unrelated. I see, now fixed.

**Comment by workingjubilee** [comment]
@sthibaul Ah, mingw-check happens to, for various reasons, fail first if anything is _generally_ incorrect with the Rust source. In this case you simply slid behind a commit that made applying the diff not pass anymore (because it applied a lint that your code didn't pass).

**Comment by workingjubilee** [comment]
Hrm,
@bors r-

**Pull request merged**
