### PR TITLE
librustc_data_structures: Speedup union of sparse and dense hybrid set 

### PR DESCRIPTION
**Pull request by 197g**
This optimization speeds up the union of a hybrid bitset when that
switches it from a sparse representation to a dense bitset. It now
clones the dense bitset and integrate only the spare elements instead of
densifying the sparse bitset, initializing all elements, and then a
union on two dense bitset, touching all words a second time.

It's not completely certain if the added complexity is worth it but I would 
like to hear some feedback in any case. Benchmark results from my machine:

```
Now:  bit_set::union_hybrid_sparse_to_dense ... bench:          72 ns/iter (+/- 5)
Previous: bit_set::union_hybrid_sparse_to_dense ... bench:          90 ns/iter (+/- 6)
```

This being the second iteration of trying to improve the speed, since I missed the return value in the first, and forgot to run the relevant tests. Oops.

### CODE REVIEW

**Comment by Centril** [comment]
@rust-timer build b7a0ff78ba2ba0b3f5e1a8e89464a84dc386aa81

**Comment by HeroicKatora** [comment]
Doesn't really seem conclusive either way, maybe the benchmark is not as representative of the usage of the operation as I thought. I'll investigate

**Comment by HeroicKatora** [comment]
@Centril Can we try again?

**Comment by Centril** [comment]
@bors try

*"Do, or do not. There is no try." -- Yoda*

**Comment by Centril** [comment]
@rust-timer build 9d4d0f349b24255dcb4c05d89a1a285c18127b01

**Comment by jonas-schievink** [comment]
Ping from triage @matthewjasper, this is waiting on your review. Feel free to assign someone else if you don't have time though.

**Pull request merged**
