### PR TITLE
bootstrap: Add missing cputype matching for sparc64

### PR DESCRIPTION
**Pull request by glaubitz**
Trying to configure rust natively on sparc64-unknown-linux-gnu currently fails with:

```
root@deb4g:/local_scratch/glaubitz/rust/rust# ./configure --host=sparc64-unknown-linux-gnu --enable-local-rust --local-rust-root=/usr/local
configure: processing command line
configure: 
configure: build.host           := ['sparc64-unknown-linux-gnu']
configure: build.rustc          := /usr/local/bin/rustc
configure: build.cargo          := /usr/local/bin/cargo
configure: build.rustc          := /usr/local/bin/rustc
configure: build.cargo          := /usr/local/bin/cargo
configure: build.configure-args := ['--host=sparc64-unknown-linux-gnu', '--enable ...
unknown cpu type: sparc64
root@deb4g:/local_scratch/glaubitz/rust/rust#
```

This is trivially fixed by defining sparc64 as a valid cputype.

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+ rollup

Thanks!

**Comment by kennytm** [comment]
@bors retry

Travis incident, no jobs starting. https://www.traviscistatus.com/incidents/xgpn2tq6mx7k

**Comment by alexcrichton** [comment]
@bors: retry

Seems like bors missed the first one

**Pull request merged**
