### PR TITLE
Document the heuristics IsTerminal uses on Windows

### PR DESCRIPTION
**Pull request by joshtriplett**
Suggested by @BurntSushi.

### CODE REVIEW

**Comment by thomcc** [comment]
Can you leave a link to <https://doc.rust-lang.org/nightly/std/io/index.html#platform-specific-behavior> and note that this documentation is not a guarantee and that the behavior may change in the future? (See [here](https://doc.rust-lang.org/nightly/std/env/fn.temp_dir.html#platform-specific-behavior) among many other place sfor another example of where we have such links).

**Review by BurntSushi — APPROVED** [review]
Love it, thank you!

**Comment by joshtriplett** [comment]
@thomcc Done.

**Comment by joshtriplett** [comment]
@BurntSushi Thanks!

@bors r=BurntSushi rollup

**Pull request merged**
