### PR TITLE
Fix typo in generics.rs

### PR DESCRIPTION
**Pull request by eltociear**
paramater -> parameter

### CODE REVIEW

**Comment by JohnTitor** [comment]
@bors r-
Failed in rollup: https://github.com/rust-lang/rust/pull/82352#issuecomment-782775884
Needs to bless the test.

**Comment by jyn514** [comment]
> Needs to bless the test.

@eltociear you can do this with `x.py test src/test/ui/const-generics --bless`, or just update the .stderr file by hand.

**Comment by crlf0710** [comment]
@eltociear Ping from triage, would you mind blessing the test suite with the changed output? Thanks!

**Comment by JohnCSimon** [comment]
@eltociear - Closing this as inactive - please reopen when you're ready to address the comments.

**Pull request closed without merging**
