### PR TITLE
derive: assume enum repr defaults to isize

### LINKED ISSUE #31886: very slow derived PartialEq/PartialOrd implementation of enum
The following code goes into an infinite loop or at least takes more than 10 seconds without optimizations. With optimizations it runs and the assertion fails. If anything but `0` and `0x8000_0000_0000_0000` are chosen for the discriminants, the code finishes instantly even in debug mode. [Playground](http://is.gd/C4V7iL)

```rust
#[derive(PartialEq, PartialOrd)]
enum Eu64 {
    Au64 = 0,
    Bu64 = 0x8000_0000_0000_0000
}

fn main() {
    assert!(Eu64::Bu64 > Eu64::Au64);
}
```

There's something odd going on anyway, as the discriminant is inferred to be `isize` instead of `u64` ([This unit test](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/enum-discrim-autosizing.rs) seems to suggest it should be `u64`)

cc #24290 @pnkfelix

### PR DESCRIPTION
**Pull request by durka**
derive: assume enum repr defaults to isize

Fixes #31886.

Spawned from #32139.

r? @alexcrichton

### CODE REVIEW

**Comment by durka** [comment]
@oli-obk is this fix now irrelevant given your PR?

**Comment by oli-obk** [comment]
well kindof.

I actually broke the following construct (explicitly, not accidentally) on 32bit

```rust
 enum Eu64 {
     Au64 = 0,
     Bu64 = 0x8000_0000_0000_0000
 }
```

because on 32bit rustc now errors at compiletime about the collision

Once we properly fix the automatic enum discriminant type detection, the issue might appear again.

**Comment by durka** [comment]
@oli-obk can you clarify what it means to properly fix discriminant detection, and what the current situation is? Is deriving correct in assuming that if the repr isn't specified than it will be isize (or smaller)?

**Comment by oli-obk** [comment]
@durka 

In list form, because I'm confusing myself when I'm writing it in text form.

1. `-9223372036854775808isize as u64` always was `0` on 32bit and still is.
2. `Eu64::Bu64 as u64` always was `0` on 32bit and still is
3. 2. makes zero sense, as the enum variant discriminants can't both be zero
4. `size_of::<Eu64>() == 8` on 32bit and 64bit
5. I broke the mentioned enum, because my typestrong const int branch ends up turning the discriminant of `Eu64::Bu64` to `0` early enough to allow rustc to detect the collision.
6. Now there's no way to specify a single value that ends up turning the discriminant to be 8 bytes. (the `Ei64` example uses two values, a negative one and a large positive one)
7. I'm not sure how to reproduce #31886 now, but `Ei64` is still 8 bytes, while the discriminant type is `isize`.

> can you clarify what it means to properly fix discriminant detection

well... the discriminant should be `i64` and `u64` imo, it should never assume `isize/usize` automatically, because that's really not portable at all. If someone wants pointer-size, then they should annotate it with `repr`. But that would technically be a breaking change for anyone ignoring the literal overflow warnings.

**Comment by durka** [comment]
@oli-obk the code given in #31886 still builds (and hangs) on nightly-2016-03-16.

**Comment by oli-obk** [comment]
oh.... I only tested on 32 bit... it obviously only collides on 32 bit... So yea, this change is still necessary for 64 bit.

**Comment by durka** [comment]
Okay, so I changed it back to `isize` since now @oli-obk's changes should prevent an enum with colliding variants from compiling.

Note that you can still write a program like this:

```rust
enum Eu64 {
    Au64 = 0,
    Bu64 = 0x8000_0000_0000_0001 //~WARN literal out of range for isize
}

fn main() {
    println!("{} {} {}", std::mem::size_of::<Eu64>(), Eu64::Au64 as isize, Eu64::Bu64 as isize);
}
```

which prints different answers on 32- and 64-bit (`1 0 1` and `8 0 -9223372036854775807` respectively).

**Comment by durka** [comment]
And combined with my other PR to use `discriminant_value` in `#[derive(PartialEq, PartialOrd)]`, the above enum will give different answers for `Au64 < Bu64`...

**Comment by alexcrichton** [comment]
Sorry I've gotten a bit lost with all the changes in flight. Is this ready to go? Did something about constants change how we want to do this?

**Comment by durka** [comment]
@alexcrichton what I believe is that is no longer possible to trigger #31886 on a 32-bit system because @oli-obk's const evaluator will catch the collision. However, my fix (as implemented currently, in this PR!) is still needed to avoid #31886 on 64-bit systems.

**Comment by alexcrichton** [comment]
@bors: r+ 9d0748f7eb75c422b61446f846251177faffeb45

Ok, thanks for the explanation @durka!

**Comment by oli-obk** [comment]
spurious failure

> Makefile:26: recipe for target 'clean' failed
Zombie process: "\Device\HarddiskVolume1\dojob.exe"
thread '<main>' panicked at 'fs::remove_dir_all(path) failed with Access is denied. (os error 5)', C:\bot\slave\auto-win-msvc-64-opt-rustbuild\build\src\bootstrap\build\clean.rs:34
note: Run with `RUST_BACKTRACE=1` for a backtrace.
make: *** [clean] Error 101

**Pull request merged**
