### PR TITLE
Register new snapshots (2015-07-26 a5c12f4).

### PR DESCRIPTION
**Pull request by eddyb**
FreeBSD i386 snapshot is missing, failed tests (possibly spurious).
r? @alexcrichton

### CODE REVIEW

**Comment by jroesch** [comment]
:+1:

**Comment by alexcrichton** [comment]
@bors: r+ 560ef00db003b87c3447c6f0782ec984293031c8

cc @dhuseby looks like the bitrig/freebsd64 builders succeeded, nice work!

**Pull request merged**
