### PR TITLE
Update occurences of as_slice to as_str in comments

### LINKED ISSUE #63792: `as_slice` -> `as_str` in the docs
`core::str::Str.as_slice()` has been renamed to `as_str()` as discussed in https://github.com/rust-lang/rust/issues/14433, but the old name is still referenced in the docs:

https://github.com/rust-lang/rust/blob/18630677cf6c7ac50e6786c504b35bc09501dbe2/src/libstd/primitive_docs.rs#L658

### PR DESCRIPTION
**Pull request by sebastinez**
Fix #63792

### CODE REVIEW

**Review by jonas-schievink — APPROVED** [review]
Thanks! The change looks good.

Can you edit the PR description so that it says "Fix #63792" or "Fixes #63792" instead of "Fix of #63792"? This will close the issue automatically when the PR is merged.

**Comment by sebastinez** [comment]
Thank you!
PR Description edited to “Fix #63792”

**Comment by jonas-schievink** [comment]
Great!

@bors r+ rollup

**Pull request merged**
