### PR TITLE
Further improve `space_between`

### PR DESCRIPTION
**Pull request by nnethercote**
`space_between` is used by `print_tts` to decide when spaces should be put between  tokens. This PR improves it in two ways:
- avoid unnecessary spaces before semicolons, and
- don't omit some necessary spaces before/after some punctuation symbols.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
Only 2 regressions of 6 are spurious.
@rustbot author

**Comment by nnethercote** [comment]
### odbc-futures-0.2.2 

[This line](https://gitlab.com/nazarmx/odbc-futures/-/blob/dev/odbc-futures-derive/src/lib.rs?ref_type=heads#L198) is the problem, it does substring matching with `"extern crate crate ;"`, and there is no longer a space before the semicolon.

The crate has only 438 downloads ever and hasn't been updated in 5 years.

### KittyCAD.kcl-lsp.844488870375d9e36254825ab04a2cfe5d5fd107 

Due to kcl-lib/derive-docs, as described [here](https://github.com/rust-lang/rust/pull/117433#issuecomment-1793881869). In short, this:
```
Result < Box < ExtrudeGroup >, KclError > {}
```
becomes this:
```
Result < Box < ExtrudeGroup > , KclError > {}
```
which breaks some string matching in a proc macro.

kcl-lib and derive-docs have had both had updates in the past two months.

### carghai.contain.be6f4b896c7594bac76ae43a2027ed7dd602a433 

Due to const-random use, seen before [here](https://github.com/rust-lang/rust/pull/114571#issuecomment-1813550126), so I'm surprised it's showing up here.
```
[INFO] [stdout] error: proc macro panicked
[INFO] [stdout]   --> src/encryption/base.rs:11:32
[INFO] [stdout]    |
[INFO] [stdout] 11 | const RANDOM_BYTES: [u8; 16] = const_random!([u8 ; 16]);
```

### gen-nested-iter-yield-0.1.3

Substring matching done [here](https://github.com/DominicBurkart/gen-nested-iter-yield/blob/d6a5a1b87de86aa969b192bf3ca04c82fb1e2ab2/src/lib.rs#L48) in the `nested_iter_yield` proc macro. I'm not sure the exact problem, probably `.` or `,` changes.

Crate has 3,376 total downloads ever, and was last updated almost 2 years ago.

### Malikazz.ProjectEuler.81ee5516c17a5425ef7b0b2dbf8ef010031deefc, tperdue321.rust_structs.c5244df34b978d5d014720c1fa42514cc89a7c37, Mallig.advent-of-code-2020.27889bb9ca6c8080172bef594543c49e52fc524c (fixed)

> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: unable to start unit "docker-937d68c71184d5335f9a4e5480e9d18bbcc3b5922aec6d9c73612f74bbdad7d2.scope

Seems unrelated to this PR, looks like temporary infra problems.

### lcdr.lu_packets.144e56d2c46043da7924ffa34705f763982676fc (fixed)
```
error[E0275]: overflow evaluating the requirement `BitWriter<endio_bit::endian::BigEndian, _>: std::io::Write`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`lu_packets`)
  = note: required for `BitWriter<endio_bit::endian::BigEndian, _>` to implement `EWrite<LittleEndian>`
  = note: required for `&'a [_]` to implement `for<'a> Serialize<LittleEndian, BitWriter<endio_bit::endian::BigEndian, _>>`
  = note: 125 redundant requirements hidden
  = note: required for `&Option<[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]>` to implement `Serialize<LittleEndian, BitWriter<endio_bit::endian::BigEndian, _>>`
  = note: the full type name has been written to '/opt/rustwide/target/debug/deps/lu_packets-8f97e4ad4ec14e69.long-type-5894850763885052302.txt'
```

Old failure was due to hitting the recursion limit. Unclear why it worked now, but seems unrelated to this PR.

**Comment by nnethercote** [comment]
> ### carghai.contain.be6f4b896c7594bac76ae43a2027ed7dd602a433
> 
> Due to const-random use, seen before [here](https://github.com/rust-lang/rust/pull/114571#issuecomment-1813550126), so I'm surprised it's showing up here.

This would make sense if crater is comparing this PR against release Rust, rather than against nightly Rust.

I filed https://github.com/tkaitchuck/constrandom/pull/33 to fix const-random, making the proc macro iterate over the token trees rather than using `to_string` and then matching substrings. This seemed a reasonable way to do it, but I've never done it before, so I'd be happy to hear if there is a better way. (The use of `syn` seems like overkill for that proc macro, because it's very simple.)

**Comment by nnethercote** [comment]
@petrochenkov: with https://github.com/tkaitchuck/constrandom/pull/33 filed, I think the only other breakage that matters is the `kcl-lib`/`derive-docs` case, where both crates are written by the same people.

I suggest we merge this PR and then I'll file an issue on `derive-docs`. And then perhaps add something to the release docs, as per #119875.

@rustbot reviewer

**Comment by petrochenkov** [comment]
Okay, seems reasonable.
@bors r+

**Comment by nnethercote** [comment]
I filed an issue on derive-docs: https://github.com/KittyCAD/modeling-app/issues/1339

**Comment by therealprof** [comment]
@nnethercote https://perf.rust-lang.org/compare.html?start=cb4d9a1902b3ea17e93872dafb76d24aa6295c47&end=80deabd0987201e1b8d060400f50e03309a0105e&stat=max-rss doesn't look great to me... Is the noticable increase in RSS expected?

**Comment by Kobzol** [comment]
(Discussion about that ongoing [here](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/max-rss.20variance)).

**Comment by Mark-Simulacrum** [comment]
Tagging relnotes for future compat notice. See https://github.com/rust-lang/rust/pull/120227#issuecomment-1911163178 for crater.

**Comment by trevyn** [comment]
This is hitting my `turbosql` crate, I think because of matching on ` ;` as above: https://github.com/trevyn/turbosql/actions/runs/7735113959/job/21090247508

**Comment by nnethercote** [comment]
> This is hitting my `turbosql` crate, I think because of matching on ` ;` as above: https://github.com/trevyn/turbosql/actions/runs/7735113959/job/21090247508

Looking at the code, I would guess [these regexes](https://github.com/trevyn/turbosql/blob/d547db1acd0b65eeab82ed946aff6fcd8bc6337d/turbosql-impl/src/lib.rs#L70-L73) are to blame.

For the first regex, changing this:
```text
^Option < \[u8 ; \d+\] >$
````
to this:
```
^Option < \[u8\s*; \d+\] >$
```
should fix the problem caused by this particular PR. Changing it to this:
```
^Option\s*<\s*\[\s*u8\s*;\s*\d+\s*\]\s*>$
```
would be more robust against possible future pretty-printing changes. But the awfulness of that regex shows the limits of substring matching for this purpose. The fully robust way to do this kind of thing is at the token level, like I did in https://github.com/tkaitchuck/constrandom/pull/33.

**Pull request merged**
