### PR TITLE
Add regression test for #40510

### LINKED ISSUE #40510: Returning upvar captured by mutable reference doesn't work
This works:
```rust
fn main() {
    let a = Box::new(8u8);

    || {
        &a
    };
}
```

This does not and gives a confusing error:
```rust
fn main() {
    let mut a = Box::new(8u8);

    || {
        &mut a
    };
}
```
The error:
```
error[E0495]: cannot infer an appropriate lifetime for borrow expression due to conflicting requirements
 --> <anon>:5:9
  |
5 |         &mut a
  |         ^^^^^^
  |
note: first, the lifetime cannot outlive the lifetime  as defined on the body at 4:7...
 --> <anon>:4:8
  |
4 |       || {
  |  ________^ starting here...
5 | |         &mut a
6 | |     };
  | |_____^ ...ending here
note: ...so that closure can access `a`
 --> <anon>:5:9
  |
5 |         &mut a
  |         ^^^^^^
note: but, the lifetime must be valid for the scope of call-site for function at 4:7...
 --> <anon>:4:8
  |
4 |       || {
  |  ________^ starting here...
5 | |         &mut a
6 | |     };
  | |_____^ ...ending here
note: ...so that return value is valid for the call
 --> <anon>:4:5
  |
4 |       || {
  |  _____^ starting here...
5 | |         &mut a
6 | |     };
  | |_____^ ...ending here
```

### PR DESCRIPTION
**Pull request by dsprenkels**
This pull request adds a test case for issue #40510.

Fixes #40510.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Could you add the other test cases in the issue as well? `issue-40510-{1,2,3}.rs` for the files is fine.

**Comment by dsprenkels** [comment]
I added some tests for the other error cases. Note that the bug only triggered in the case of `issue-40510-1.rs` and `issue-40510-3.rs`.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Thanks!

**Pull request merged**
