### PR TITLE
Move `rustllvm` into `compiler/rustc_llvm`

### PR DESCRIPTION
**Pull request by petrochenkov**
The `rustllvm` directory is not self-contained, it contains C++ code built by a build script of the `rustc_llvm` crate which is then linked into that crate.
So it makes sense to make `rustllvm` a part of `rustc_llvm` and move it into its directory.
I replaced `rustllvm` with more obvious `llvm-wrapper` as the subdirectory name, but something like `llvm-adapter` would work as well, other suggestions are welcome.

To make things more confusing, the Rust side of FFI functions defined in `rustllvm` can be found in `rustc_codegen_llvm` rather than in `rustc_llvm`. Perhaps they need to be moved as well, but this PR doesn't do that.

The presence of multiple LLVM-related directories in `src` (`llvm-project`, `rustllvm`, `librustc_llvm`, `librustc_codegen_llvm` and their predecessors) historically confused me and made me wonder about their purpose.
With this PR we will have LLVM itself (`llvm-project`), a FFI crate (`rustc_llvm`, kind of `llvm-sys`) and a codegen backend crate using LLVM through the FFI crate (`rustc_codegen_llvm`).

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc interested parties @cuviper @nikic @bjorn3 @eddyb @mark-i-m (I could forget someone else)

**Comment by lcnr** [comment]
:shrug: There aren't any obvious problems here but it's not up to me to decide if this change should be made.

r? @cuviper

**Comment by cuviper** [comment]
> The `rustllvm` directory is not self-contained, it contains C++ code built by a build script of the `rustc_llvm` crate which is then linked into that crate.
> So it makes sense to make `rustllvm` a part of `rustc_llvm` and move it into its directory.
> I replaced `rustllvm` with more obvious `llvm-wrapper` as the subdirectory name, but something like `llvm-adapter` would work as well, other suggestions are welcome.

This all sounds good to me.

> To make things more confusing, the Rust side of FFI functions defined in `rustllvm` can be found in `librustc_codegen_llvm` rather than in `rustc_llvm`. Perhaps they need to be moved as well, but this PR doesn't do that.

I think we could even move *all* of the FFI declarations to `rustc_llvm`, not just the `LLVMRust*` stuff -- as you said, this crate already acts like an `llvm-sys` kind of crate. Maybe even the whole `rustc_codegen_llvm::llvm` module should move.

> If this is merged, then the merge should probably be done after the compiler part of [rust-lang/compiler-team#316](https://github.com/rust-lang/compiler-team/issues/316) to avoid moving things around twice.

I'm personally not too worried about that, as this seems like a simple enough move that git's tracking should work, but it's ok if you want to wait and do it with the compiler move or soon after.

We should also remember to update [the config in highfive](https://github.com/rust-lang/highfive/blob/3b290170a6178e02b1d4f3b96ebc54c1e34bff40/highfive/configs/rust-lang/rust.json#L34).

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/74862.

**Comment by matklad** [comment]
> a FFI crate (librustc_llvm, kind of llvm-sys

Shall we perhaps just rename it to `llvm-sys`?

**Comment by mark-i-m** [comment]
Yes, I agree the naming between `librustc_llvm`, `rustllvm`, and `llvm-project` are not particularly clear...

**Comment by mark-i-m** [comment]
Also, this is no longer blocked, I think.

@rustbot modify labels: +S-waiting-on-author -S-blocked

**Comment by petrochenkov** [comment]
Rebased.
`src/librustc_llvm` is also moved to `compiler/rustc_llvm` consistently with https://github.com/rust-lang/rust/pull/74862.

It's not renamed to `llvm-sys` to keep naming scheme consistent with all other rustc crates.

`rustc_codegen_llvm::llvm` is not *yet* moved to `rustc_llvm` because it's somewhat intertwined with the rest of `rustc_codegen_llvm`, so untangling them would better be done in a separate PR.

**Comment by petrochenkov** [comment]
>It's not renamed to `llvm-sys` to keep naming scheme consistent with all other rustc crates.

It could be renamed from `rustc_llvm` to `rustc_llvm_ffi` for clarity though.

**Review by cuviper — APPROVED** [review]
Need to pick up the #75655 change, then `r=me`.

**Comment by tmandry** [comment]
Rolled up
@bors retry

**Comment by tmandry** [comment]
Rolled up again
@bors retry

**Pull request merged**
