### PR TITLE
Extend MIR inlining to all operand variants

### LINKED ISSUE #54193: MIR inlining should work with any `ty::FnDef` callee operand, not just constants.
This code:
https://github.com/rust-lang/rust/blob/994cdd918589535d705177545bf503cd0c3c5148/src/librustc_mir/transform/inline.rs#L96-L97

should not pattern-match on `func`, but rather call its `ty` method to get its type.

What this means is that `let f = foo; f();` should inline as well as `foo()` (but today it doesn't).

cc @nikomatsakis

### PR DESCRIPTION
**Pull request by pvdrz**
This fixes https://github.com/rust-lang/rust/issues/54193
r? @eddyb

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]
Code changes look good to me. Can you also write a test that shows that `let f = foo; f()` inlines correctly? (See `src/test/mir-opt/inline-closure-borrows-arg.rs` for an example)

**Comment by christianpoveda** [comment]
Of course! give me a couple minutes to do it :)

**Comment by christianpoveda** [comment]
Something like this
```rust
fn foo() -> i32 {
    let f = |x: i32, y: i32| x + y;
    f(1, -1)
}
```
would be a good test? Or did I misunderstood something?

**Comment by wesleywiser** [comment]
I *think* we want something like:

```
fn foo(x: i32, y: i32) -> i32 {
  x + y
}

fn main() {
  let f = foo;
  println!("{}", f(1, 2));
}
```

**Comment by christianpoveda** [comment]
Bad news, I'm getting
```
fn bar() -> i32{
    let mut _0: i32;
    scope 1 {
    }
    scope 2 {
        let _1: fn(i32, i32) -> i32 {foo};
    }
    let mut _2: fn(i32, i32) -> i32 {foo};
    bb0: {                              
        StorageLive(_1);
        _1 = const foo;
        StorageLive(_2);
        _2 = _1;
        _0 = move _2(const 1i32, const -1i32) -> bb1;
    }
    bb1: {                              
        StorageDead(_2);
        StorageDead(_1);
        return;
    }
    bb2: {
        resume;
    }
}
```
Which means inlining is not happening.

**Comment by wesleywiser** [comment]
Does adding an `#[inline(always)]` to `foo()` make a difference?

**Comment by christianpoveda** [comment]
Yeah it does! should I left the inline?

**Comment by wesleywiser** [comment]
Yeah, go ahead and leave it in. The goal is to verify `let f = foo; f()` can be inline regardless of whether or not the optimizer actually decides it's a good idea.

**Comment by christianpoveda** [comment]
Ok, I'll finish the test and commit again. Any name ideas for this test?

**Comment by wesleywiser** [comment]
I'd either go with `inline-any-operand.rs` or just plain old `issue-54193.rs` :slightly_smiling_face:

**Comment by wesleywiser** [comment]
Thanks!!

@bors r+

**Comment by christianpoveda** [comment]
It seems it was a connection problem inside appveyor: https://ci.appveyor.com/project/rust-lang/rust/build/1.0.9089/job/w3c09bbqp6akf7ie#L7208

**Comment by wesleywiser** [comment]
Spurious network issue cc #40474

@bors retry

**Pull request merged**
