### PR TITLE
Book: Fix link anchor in Syntax Index

### PR DESCRIPTION
**Pull request by floftar**
See: https://github.com/rust-lang/rust/issues/30397

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

Thank you so much!

**Comment by tshepang** [comment]
Merge commit should be removed

**Comment by fbergr** [comment]
@tshepang Thank you for pointing out my mistake.

**Comment by steveklabnik** [comment]
I dunno why bors didn't see this

@bors: r+ rollup

**Comment by tshepang** [comment]
@steveklabnik An additional commit was made after approval

**Pull request merged**
