### PR TITLE
[wip] Enable ThinLTO with incremental compilation.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR allows `rustc` to use ThinLTO and incremental compilation at the same time. In theory this should allow for getting compile-time improvements for small changes while keeping the runtime performance of the generated code roughly the same as when compiling non-incrementally.

### How does it work?

- ThinLTO computes the so-called `ModuleSummaryIndex`. This index contains a map of which module imported stuff from which other modules during ThinLTO. 
- The implementation in this PR takes this "import map" after it has been generated and saves it in the incr. comp. cache directory.
- In a subsequent compilation session, we load the previous import map and use it do enhanced cache invalidation: Because ThinLTO pulls in things from other modules we don't only have to re-compile an object file if its corresponding source code has changed but also if something has changed in a module that we imported something from. 
- The cache invalidation logic thus changes from `has_changed(module.inputs)` to `has_changed(module.inputs) || any(has_changed(imported_module.inputs))`.

### Performance

The effect on compile times can be seen here: https://perf.rust-lang.org/compare.html?start=68c39b9fec17846005da9a8e42991422c08c377c&end=02e01bd388a35a90002e37851aa26ba59c593a42&stat=wall-time

Some observations:

- The `baseline incremental-opt` case is always slower. This is expected since we are running ThinLTO now but didn't do so before.
- Some of the `patched incremental: println-opt` cases are *a lot* slower. E.g. `clap-rs-opt` which goes from 4.47s to 24.65s, i.e. it takes more than 5 times as long. The small change in these cases probably invalidates a module that many other modules import things from. 
- Some of the `patched incremental: println-opt` are hardly affected. E.g. `encoding-opt` goes from 0.38s to 0.42s, i.e. 8% slower. It is still 10 times faster than compiling from scratch, in theory without sacrificing runtime performance.
- Some of the `debug` builds are also negatively affected (e.g. `regex-debug / patched incremental: compile one`). I suspect this is because in it's current form, the PR allows for less parallelism during codegen. It first sequentially checks all modules for modifications and only then starts codegen and LLVM. Without this PR, modification checking is done more lazily, while LLVM is already running. This should not be hard to fix for the non-ThinLTO case.

### How to proceed?

- Bring back the performance for the incremental non-ThinLTO builds. This should be done before merging this PR.
- Find out how the heck to test this properly. This would also be good to do before merging.
- Maybe merge the PR and then ask people on irlo to compile their code with it. This way we would get us numbers on the *runtime* performance of code generated this way. It would be good to know if this is even worth the trouble. 
- Once we know that runtime performance is good, we can decide whether to turn incremental compilation on by default also for release builds. Just merging this PR won't do so.
- Investigate if we can make cache invalidation smarter. The ThinLTO import map tells us exactly which functions it imported into a given module, so we could try to check things at the function- instead of at the module-level. I'm sure though that that's not an easy task.

cc @rust-lang/compiler @rust-lang/wg-compiler-performance

~~This (work-in-progress) PR allows for combining ThinLTO and incremental compilation. I'll write up something more detailed once the kinks are worked out. For now, I'm mostly interested in what this does to compile times.~~

### CODE REVIEW

**Comment by cuviper** [comment]
The error is on llvm-emscripten, based on LLVM 4.0 which doesn't have `keys()`.  LLVM 5 does have it.

**Comment by michaelwoerister** [comment]
@rust-timer build 02e01bd388a35a90002e37851aa26ba59c593a42

**Comment by alexcrichton** [comment]
Looks like cache hits aren't happening?

**Comment by michaelwoerister** [comment]
I think the results are kind of expected because of how coarse-grained this still is. Right now if something changes in a module then all modules important *anything* from that module (even something that has not really changed) need to completely re-compiled.

There's room for improvement: If we track changes for every `CodegenItem` separately (instead of for whole `CodegenUnits` at a time) then we (probably) can use the more detailed information available in the ThinLTO import map.

**Comment by michaelwoerister** [comment]
I updated the PR description: https://github.com/rust-lang/rust/pull/52309#issue-201036336

@rust-lang/compiler @rust-lang/wg-compiler-performance

**Comment by Mark-Simulacrum** [comment]
In terms of testing, you could try to build the compiler incrementally with ThinLTO and see if it's tests still pass, potentially doing a local perf run to compare against a incrementally compiled compiler (w/o ThinLTO), as well.

**Comment by alexcrichton** [comment]
Thanks @michaelwoerister! I wonder though, I think that incremental ThinLTO upstream at least isn't supposed to have such bad performance, so I think we're missing a step in impelmenting this? I thought incremental ThinLTO would looks something like this:

* As usual, incrementally translate and optimize a bunch of LLVM modules. This may have a bunch of cache hits (especially in the println case)
* Next we calculate the ThinLTO module summary index for everything (unconditional work)
* Next we take this index and generate a unique hash for each module which includes items imported from other modules (unconditional work)
* If there is an object file matching this unique hash we use it from the cache, otherwise we generate a new object file via codegen.
* Finally, all the output object files here are linked together

It looks like the implementation here is invalidating too eagerly? The construction above would avoid retranslating/optimizing modules that depend on changed modules but don't import any of the changes. In that the cache invalidation needs to only happen for the ThinLTO passes, not the entire module's original optimization passes.

**Comment by michaelwoerister** [comment]
@alexcrichton, your approach would increase the size of our incr. comp. cache quite a bit (~50%) because we would have to cache LLVM IR before and after ThinLTO. Currently we only cache the later. I'm not strictly opposed to doing that but cache size already is a concern for big projects. It's certainly worth a try though.

Also note that we actually don't have to hash anything, or incr. comp. framework will tell us already which modules have changed. With some tweaking, it should also be possible to know exactly which items within a module have changed. I'll have another look at how the linker-plugins do it though.

**Comment by alexcrichton** [comment]
@michaelwoerister indeed! Although I think what I mentioned above is how incremental ThinLTO was designed to work? In that if you're using a linker plugin then all your intermediate files are the IR files and then the final link also has a cache directory with a lot of object files? I think we have some other various methods to greatly improve our cache directory sizes, for example we should probably be using thin archives which just point to the object files elsewhere on disk, and that way object files aren't copied around. (additionally we probably save way too much IR in too many places!)

Within our own incr. comp. framework I think ThinLTO would roughly look like:

1. There's a query to get the final set of object files. Each object file is the same as our already-existing scheme to partition into CGUs.
2. Each CGU's object file query queries for the pre-ThinLTO-IR of the object file (optimized) as well as the module summary for this object file.
3. Querying the module summary queries for the global module summary and then selectively queries for specific objects from other IR modules. Note that here you don't depend on the entire foreign IR module, just what you're importing.

While it's probably *possible* to integrate it into our own incr. comp. framework and have reuse "just work" it may also be good to shoehorn as close as we can to upstream incremental ThinLTO as that's how it's written to work in the sense of fixing bugs and getting future developments.

I sort of assumed that the way we'd implement incremental ThinLTO was to basically implement custom incrementality in ThinLTO passes (like upstream LLVM does) and basically just get the main incremental directory from the compilation session.

I do think we have to solve the problem here in the sense if I change one CGU that shouldn't force all CGUs which *may* import the item to be fully recompiled. Instead only those which are *known* to import the changed item should be recompiled (and even then, not fully recompiled, just post-ThinLTO-passes).

**Comment by SimonSapin** [comment]
> cache size already is a concern for big projects

It’s not just the incremental cache and it’s not just Rust code, but as a single data point I regularly fill the 500 GB on my desktop machine that is dedicated to compilation. Part of this is due to Cargo not having any garbage collection outside of `cargo clean`. Upgrading to a new Rust Nightly changes the hash in some directory names and can effectively double the size of `target/`.

**Comment by michaelwoerister** [comment]
> I do think we have to solve the problem here in the sense if I change one CGU that shouldn't force all CGUs which may import the item to be fully recompiled. Instead only those which are known to import the changed item should be recompiled (and even then, not fully recompiled, just post-ThinLTO-passes).

If by "item" you mean CGU then this is already what this PR does (except of course re-use the pre-ThinLTO optimization work because we don't cache it).

> I sort of assumed that the way we'd implement incremental ThinLTO was to basically implement custom incrementality in ThinLTO passes (like upstream LLVM does) and basically just get the main incremental directory from the compilation session.

That's what I think we should do too. This PR already makes LLVM IR generation not be a query anymore. It's pretty much a "standard ThinLTO" pipeline.

**Comment by michaelwoerister** [comment]
> The description leads me to believe that in the above scenario no matter what changes in B then A is fully recompiled unconditionally. 

That's the case. The PR does NOY yet implement change tracking at the function level. Do you know if linker-based LTO computes a hash per function? I don't have the code at hand at the moment. The description here sounds like no: http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html.

**Comment by alexcrichton** [comment]
Aha it appears I'm misremembering! I've gone off [this list](https://github.com/llvm-mirror/llvm/blob/6ab694dd51ed0103163d44c24cfb645b1dbe9199/lib/LTO/ThinLTOCodeGenerator.cpp#L344-L385) before, and you're right in that it only looks at entire modules, not hashes of imported contents.

In light of that I think there's still a "main thing" for this PR to implement, right? Which is that we shouldn't recodegen/reoptimize entire modules, but rather only rerun the ThinLTO passes when an input changes, right? Does that make sense?

**Comment by michaelwoerister** [comment]
> In light of that I think there's still a "main thing" for this PR to implement, right? Which is that we shouldn't recodegen/reoptimize entire modules, but rather only rerun the ThinLTO passes when an input changes, right? Does that make sense?

Yes, that makes sense. That should put `rustc` on par with the linker plugin.

**Comment by stokhos** [comment]
Ping from triage, @michaelwoerister we haven't heard from you for a while, will you have time to work on this PR?

**Comment by michaelwoerister** [comment]
This has been slightly de-prioritized until linker-plugin-based LTO is under wraps. Since this will need a little design work still, I'm going to close this PR for now.

**Pull request closed without merging**
