### PR TITLE
Use tracing spans in rustc_trait_selection

### PR DESCRIPTION
**Pull request by matthewjasper**
Spans are very helpful when debugging this code. It's also hot enough to make a good benchmark.

r? @oli-obk

### CODE REVIEW

**Comment by matthewjasper** [comment]
This is up to a 0.8% regression. I'll see if reducing the number of spans being used can help here.

**Comment by oli-obk** [comment]
@bors r+

looks like we actually got a small perf improvement out of it

**Comment by Mark-Simulacrum** [comment]
Final results confirm the perf [improvement](https://perf.rust-lang.org/compare.html?start=8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306&end=abbdec3be6cfce1175d0dc6737a2999cf43b530d&stat=instructions:u).

**Pull request merged**
