### PR TITLE
Revert "Do not consider method call receiver as an argument in AST."

### PR DESCRIPTION
**Pull request by compiler-errors**
Reverts #100232, including a few places where there were merge conflicts after this landed.

r? @pnkfelix 
cc @cjgillot 

cc #103430 the nightly workaround for this issue.

### CODE REVIEW

**Comment by pnkfelix** [comment]
LGTM.

@bors r+

**Comment by pnkfelix** [comment]
The intent here is that this will address the fallout that is documented on issue #103244 with respect to the 1.65 release. PR #103430 is how #103244 will be addressed for 1.66 and beyond (unless something better comes along, of course).

**Comment by compiler-errors** [comment]
@cjgillot, yes but only on beta (-> stable). Given that it's a pretty ancient bug, I'm fine with that personally, but perhaps someone else like @pnkfelix or you can weigh in on the risk.

**Comment by pnkfelix** [comment]
yes, I am also fine with treating #73663 as effectively resolved, due to 1. the fact that the ICE itself has been around since 202 and 2. the fix persisting on nightly even with this revert on beta.

**Pull request merged**
