### PR TITLE
Implement DoubleEndedIterator for CaseMappingIter

### PR DESCRIPTION
**Pull request by sugar700**

### CODE REVIEW

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by sfackler** [comment]
Could you give an example of when you'd want to use this?

**Comment by clarfon** [comment]
This was denied before in #38968.

**Comment by xfix** [comment]
There is no real point, it's mostly for consistency. About ExactSizeIterator, it was implemented in #58778.

**Comment by sfackler** [comment]
Our policy is generally to not take code that no one wants to use. Every new API imposes some cost, and we should at least be getting *some* value out of it.

**Comment by Centril** [comment]
cc @rust-lang/libs Can someone please review this? :)

**Comment by alexcrichton** [comment]
Looks like a [review was provided](https://github.com/rust-lang/rust/pull/60112#issuecomment-485132415) but since there [aren't compelling use cases](https://github.com/rust-lang/rust/pull/60112#issuecomment-485236398) for it and it's otherwise seen as perhaps a bit too much code for libstd for now, I'm going to close this.

**Pull request closed without merging**
