### PR TITLE
Default to sha256 for hashing source files

### PR DESCRIPTION
**Pull request by saethlin**
r? @ghost

### CODE REVIEW

**Comment by joshtriplett** [comment]
Would it be worth testing blake3 as well, to see if it helps with performance?

**Comment by Kobzol** [comment]
I tested blake3 a few months ago. There were perf. wins, but it didn't seem worth it in the grand scheme of things to introduce a new dependency.

**Comment by ChrisDenton** [comment]
I would ask why this was previously msvc only? If there was a reason for excluding other platforms then it'd be good to know if those reasons have been solved or if they're still outstanding.

**Comment by klensy** [comment]
https://github.com/rust-lang/rust/pull/113707

**Comment by saethlin** [comment]
_If_ this can be landed, it would need a lot of other improvements outside of rustc itself first. Maybe I'll poke DWARF about this; if MD5 isn't good enough for Microsoft I don't see why it should be good enough for DWARF.

**Pull request closed without merging**
