### PR TITLE
Only golden arches

### PR DESCRIPTION
**Pull request by workingjubilee**
A number of tests in the test suite have applied the somewhat comedic practice of ignoring *every* single target architecture that rustc has ever supported. This is silly, when they are clearly tests built around certain assumptions, primarily of the x86-64 architecture, or in one case when they are only relevant for a handful of 32-bit targets. This has even resulted, in one case, in the same architecture being ignored twice!

Document these better, and use a "revision + only-arch" idiom in the test headers to denote the "golden arches" that actually pass these tests.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Huh, I didn't know `only-*` was additive like that.

**Comment by workingjubilee** [comment]
@ChrisDenton It is not.

This pattern requires the use of revisions. The revision only applies a directive for that revision, and reruns the test (including ignoring it) for each revision.

**Comment by RalfJung** [comment]
Do multiple "only" not have the semantics "test runs if any of the architectures match"? That is the semantics I would expect (and it is what the ui-test crate does).

**Comment by workingjubilee** [comment]
Hmm, when I talked with someone who knows more about `ui_test` and `compiletest` than me, they said it didn't do unions of `only-*`, but now I'm hearing conflicting reports so...!

**Comment by RalfJung** [comment]
Ah, seems like I was wrong for ui_test

https://github.com/oli-obk/ui_test/blob/5065d1c71e3382e65f422919d020843fc63b6914/src/lib.rs#L1120

**Pull request merged**
