### PR TITLE
Some cleanups for core::fmt

### PR DESCRIPTION
**Pull request by sinkuu**

### CODE REVIEW

**Comment by joshtriplett** [comment]
Can you elaborate a bit on why the adapter isn't needed anymore?

**Comment by sinkuu** [comment]
Since `fn write_fmt(&mut self, ..)` creates an immutable binding `self` of type `&mut Self`, `write(&mut self)` will be an error. `&mut Adapter(self)` works because tremporaries are mutable (so the comment was wrong; this has nothing to do with unsizedness). We can just make `self` argument mutable as in this PR.

**Comment by pietroalbini** [comment]
@bors retry
AppVeyor... what's wrong with you today?

**Pull request merged**
