### PR TITLE
Document the size of bool

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
It *is* always 1, right?

**Comment by steveklabnik** [comment]
This is historically not guaranteed on purpose https://github.com/rust-lang/rfcs/pull/954

/cc @rust-lang/lang

**Comment by rkruppe** [comment]
Worth noting that https://github.com/rust-lang/rfcs/pull/954 proposed far more than documenting the size, it proposed guaranteeing a encoding of `true` and `false` as bytes and furthermore ties it to the C ABI (it's legal for the C compiler to make `_Bool` larger than one byte, although in practice that doesn't seem to be common).

In contrast, guaranteeing a `size_of` of 1 seems entirely harmless, because what else could it sensibly be? Even if future Rust compiler could sometimes packs bools in unused bits in aggregates, a `size_of` of 0 would break things such as `Box::new(true)`. A larger `size_of` would be legal, but would not be an "optimization".

**Comment by durka** [comment]
The values true=1, false=0 are documented: https://doc.rust-lang.org/reference/behavior-considered-undefined.html

**Comment by bluss** [comment]
The reference is not official rust docs and it is not a real reference yet, unfortunately.

**Comment by est31** [comment]
@bluss then remove that statement from the reference. And no it is official documentation. Otherwise why is it on the doc.rust-lang.org domain?

**Comment by bluss** [comment]
Nightly version has a better banner and a link to the nursery repo where it's developed: https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html

**Comment by durka** [comment]
Then we should close this PR as writing down the size of bool won't have any weight... is there a list of "decisions that have actually been made and can be trusted"?

**Comment by cramertj** [comment]
@durka IMO the authoritative Rust documentation is the standard library's documentation, as the guarantees it specifies are part of the library, and therefore part of Rust's stability guarantees.

**Comment by scottmcm** [comment]
Hmm, so the impact of this change would be to put the compile-time-validity of `transmute::<bool, u8>` inside the stability guarantee?  I understand writing code that relies on `size_of::<u8>() == 1`; is it particularly valuable to be able to rely on `size_of::<bool>() == 1` in `unsafe`?

**Comment by est31** [comment]
So as the ABI of bool seems to be not specified, please see my PR #46176 to lint about bool in FFI usage.

**Comment by egilburg** [comment]
Perhaps document `i128` and `u128` too?

**Comment by rkruppe** [comment]
It appears that C doesn't specify the size of `_Bool` (it just has to be able to store 0 and 1), so if we want to specify `bool` as being compatible with `_Bool` that would theoretically clash with documenting the size to be 1. I say "theoretically" because I'm not aware of a platform that makes `_Bool` larger (other than possibly architectures where `char` isn't 8 bit, but those aren't really supported by Rust anyway).

**Comment by withoutboats** [comment]
IMO the size of bool should be defined as the same as the size of `_Bool` on that platform, which we should helpfully document as being one byte essentially always.

**Comment by withoutboats** [comment]
Basically I think we should just accept RFC 954 at this point.

**Comment by Havvy** [comment]
I added the table in #44648 and checked what people said on IRC around the time. I'm not seeing any reference to `bool` in either location. Looks like I completely missed it on oversight.

I do have a reference PR where I added it though, but it looks like I'll have to remove that line. 😣 

About the UB section of the reference &mdash; it's immaterial to this discussion. It's stating that the valid values of `bool` are `0` and `1`. There's nothing about the size of the type. Or are we even saying that we can have `bool`s where `false` is not `0` and `true` is not `1`?

**Comment by vojtechkral** [comment]
> IMO the size of bool should be defined as the same as the size of `_Bool` on that platform

I wonder should `bool` be treated differently than integer types. With integer types, Rust defines its types such that they are as sane and consistent across platforms as possible (ie. `i32`, `usize` etc.) and relies on `libc` to provide C FFI interop types, which seems to work reasonably well. Why isn't the same strategy applied to `bool`? That is, keep it sane inside Rust (ie. sized 1) and provide a libc bool type for C FFI.

**Comment by withoutboats** [comment]
That also seems fine.

**Comment by SimonSapin** [comment]
hsivonen wrote in a thread that mentioned this PR:
> I'm so glad Rust committed to two's complement despite it ruling out FFI interop with some C implementations. I wish today's Rust had more of the “UTF-8 everywhere, two's complement everywhere” attitude.

I think that’s a good point, and we should decide that Rust’s `bool` always has the obvious representation. If they turn out to be real, FFI concerns can be addressed with conversions in the `libc` crate.

**Comment by aturon** [comment]
Nominated for lang team discussion.

**Comment by kennytm** [comment]
Hi @rust-lang/lang, triage ping. Is there any update on this? Should this PR (and also #46176) be kept open until a decision is reached?

**Comment by nicodemus26** [comment]
@vojtechkral It would seem that `bool` is already the C FFI interop type. A new one-sized type `u1` would maybe make sense, but would it complicate the ecosystem? `u1` and `bool` should be fully bijective but sometimes sized differently.

`bool` is to `usize` as `u1` is to `u64` on a 64-bit arch?

As an aside, it would be pretty nice to have `u1` arrays and slices compile to space-efficient bitmaps!

**Comment by SimonSapin** [comment]
> As an aside, it would be pretty nice to have u1 arrays and slices compile to space-efficient bitmaps!

You’re looking for https://crates.io/crates/bit-vec. This is not possible with `[T; N]` / `[T]` / `Vec<T>` because in these each element needs to have a distinct address because indexing returns `&T` or `&mut T`.

**Comment by scottmcm** [comment]
> As an aside, it would be pretty nice to have u1 arrays and slices compile to space-efficient bitmaps!

C++ has experience with that, and it turned out to be better as opt-in instead of magic: https://isocpp.org/blog/2012/11/on-vectorbool

**Comment by kennytm** [comment]
Triage ping @rust-lang/lang! It seems we still haven't got a clear decision...

**Comment by nikomatsakis** [comment]
Cross-posting from [the internals thread](https://internals.rust-lang.org/t/rusts-stability-story-should-apply-to-bool-in-ffi/6305/11?u=nikomatsakis):

We finally got around to discussing this in the @rust-lang/lang meeting. We had the following questions, perhaps someone may be in a position to answer authoritatively:

- Are there any extant platforms where `_Bool` in the C ABI is permitted to take values other than 0 or 1?
    - How I understood prior answers is "no, truth-y values will coerce to 1"
- Does the C standard **permit** platforms where `_Bool` is permitted to take values other than 0 or 1?
- Side question: are there extant platforms where `sizeof(_Bool) != 1` ?
    - We believe the C standard permits other sizes, but weren't clear if anyone took advantage of that freedom.

Our preference is to define `bool` as `_Bool`. This would be what most people expect and avoid massive breakage.  If the C standard requires values of 0 or 1, then there seems to be basically no drawback. Otherwise, it implies a potential performance pitfall on matches (matches on *bools*, mind you) but doesn't seem like a huge problem. Still, it'd be good to know the answers to those questions before reaching a final consensus.

**Relevant to this RFC**, @SimonSapin or others, do you think that defining `bool` to be **1 byte** everywhere is better than `_Bool`? If so, it'd be good to discuss the case for that further. (I confess to not having read every comment here, so I'd appreciate pointers into the discussion.)

**Comment by petrochenkov** [comment]
Additional question for the list:
- Are there any extant platforms where C++ `bool` and C `_Bool` have different ABIs?

C `_Bool` is a late addition to the language that is largely unused in C interfaces, so C++ `bool` should be much more important from practical FFI point of view.

**Comment by vojtechkral** [comment]
@nikomatsakis 

> Does the C standard permit platforms where _Bool is permitted to take values other than 0 or 1?

From N1570, §6.2.5:

> An object declared as type _Bool is large enough to store the values 0 and 1.

§6.3.1.2:

> When any scalar value is converted to _Bool, the result is 0 if the value compares equal
to 0; otherwise, the result is 1. <sup>59)</sup>

Ie. I believe from the standard's point of view `_Bool` can only have values 1 and 0.

[cppreference.com](http://en.cppreference.com/w/c/language/arithmetic_types#Boolean_type) also notes a consequence:

> Note that conversion to `_Bool` does not work the same as conversion to other integer types: `(bool)0.5` evaluates to `1`, whereas `(int)0.5` evaluates to ​`0`​.

**Comment by SimonSapin** [comment]
> @SimonSapin or others, do you think that defining bool to be 1 byte everywhere is better than _Bool?

(Replying since I’m mentioned by name. “Better” is a big word. I have no idea. I submitted this PR because it had not occurred to be that this could be otherwise.)

**Comment by est31** [comment]
The FCP has been resolved: https://github.com/rust-lang/rust/pull/46176#issuecomment-362351652

Please merge this now!

**Pull request merged**
