### PR TITLE
add playbot jokes to run-pass test

### PR DESCRIPTION
**Pull request by durka**
Some funny expressions that people pull out on IRC, that might actually be useful to test pathological parser behavior.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Tidy failed:

```
[00:02:51] tidy check (x86_64-unknown-linux-gnu)
[00:02:52] tidy error: /checkout/src/test/run-pass/weird-exprs.rs:82: line longer than 100 chars
[00:02:52] tidy error: /checkout/src/test/run-pass/weird-exprs.rs:97: trailing whitespace
[00:02:52] tidy error: /checkout/src/test/run-pass/weird-exprs.rs:105: line longer than 100 chars
[00:02:53] some tidy checks failed
```

**Comment by natboehm** [comment]
Hi @durka any news on the tidy failures?

**Comment by durka** [comment]
Sorry about that. Should be fixed now.

**Pull request merged**
