### PR TITLE
[Obligation Forest] Don't process cycles when stalled

### PR DESCRIPTION
**Pull request by jonas-schievink**
This improves the `inflate-0.1.0` benchmark by about 10% for me.

/me hopes this is sound

### CODE REVIEW

**Comment by arielb1** [comment]
That's the change I was talking about with @nnethercote 

@bors r+

**Comment by jonas-schievink** [comment]
According to Travis, it makes [this test](https://github.com/jonas-schievink/rust/blob/obligation-forest-the-quest-for-performance/src/librustc_data_structures/obligation_forest/test.rs#L413-L416) fail

**Comment by jonas-schievink** [comment]
It's probably because error nodes are handled like popped nodes, so we'd have to compress when an obligation errors.

**Comment by arielb1** [comment]
Sure 'bout that.

**Comment by nnethercote** [comment]
I just measured a stage1 compiler with compare.py and got this:
```
inflate-0.1.0    4.923s vs  4.274s --> 1.152x faster (variance: 1.011x, 1.011x)
```
Nice!

**Pull request merged**
