### PR TITLE
Prefer suggestion paths that are not `#[doc(hidden)]`

### PR DESCRIPTION
**Pull request by compiler-errors**
This is a revival of #87349

Maybe we don't even need to make it this complicated? I guess I could also just insert children that have `doc_hidden` parents using the same `fallback_map` I added a while back to filter out `use ... as _;` imports.

### CODE REVIEW

**Comment by compiler-errors** [comment]
(cc @In-line, I can also close this if you'd rather author this PR yourself. Just doing a diagnostics-related issue triage and I saw this PR got closed.)

**Comment by In-line** [comment]
I was planning to return to it, in some point. I don't care about who is author. If you have time to fix it, feel free to do it!

**Comment by jyn514** [comment]
Hmm, if rustc is going to add this logic I wonder if it can be shared with the existing code in https://github.com/rust-lang/rust/blob/e1d1848cc60a407d06f90fd16877a19bed6edd9b/src/librustdoc/visit_ast.rs#L51

**Pull request closed without merging**
