### PR TITLE
Store UNICODE_VERSION as a tuple

### PR DESCRIPTION
**Pull request by pyfisch**
Remove the UnicodeVersion struct containing
major, minor and update fields and replace it with
a 3-tuple containing the version number.
As the value of each field is limited to 255
use u8 to store them.

### CODE REVIEW

**Comment by pyfisch** [comment]
See discussion at #49726.

**Comment by behnam** [comment]
Thanks for getting this out, @pyfisch. Looks great!

**Comment by pyfisch** [comment]
@behnam Glad it helped you! Out of curiosity what are you using the constant for?

**Comment by behnam** [comment]
> @behnam Glad it helped you! Out of curiosity what are you using the constant for?

In [UNIC](https://github.com/open-i18n/rust-unic), I've been planning to have fallback to complier-level props, instead of the library-implemented ones, whenever the Unicode UCD version matches. We don't have that implemented yet, though.

**Pull request merged**
