### PR TITLE
Actually instantiate the opaque type when checking bounds

### PR DESCRIPTION
**Pull request by oli-obk**
Before this change, `instantiate_opaque_types` was a no-op, because it only works relative to the defined opaque type inference anchor. If it is a no-op, the for loop will not actually have anything to iterate over, and thus nothing is checked at all.

### CODE REVIEW

**Comment by cjgillot** [comment]
I don't know anything of that code.
@matthewjasper could you take over?

**Comment by oli-obk** [comment]
@bors try @rust-timer queue

realized that we should check perf first.

**Comment by oli-obk** [comment]
This regresses check_mod_item_types a bit, but that is expected as we are now double checking impl trait in return position. We don't have any problems due to not checking here, so I can't write a test, but it's very fragile to depend on ad hoc checks happening for impl trait (as evident in my currently unpublished PR), so I'd rather merge this PR with the slight perf regression.

**Review by nikomatsakis — APPROVED** [review]

**Comment by rylev** [comment]
Adding back the triaged label

@rustbot label: +perf-regression-triaged

**Comment by oli-obk** [comment]
> This regresses check_mod_item_types a bit, but that is expected as we are now double checking impl trait in return position. We don't have any problems due to not checking here *at present*, so I can't write a test, but it's very fragile to depend on ad hoc checks happening for impl trait (as evident in https://github.com/rust-lang/rust/pull/92007),

@rustbot label: +perf-regression-triaged

**Pull request merged**
