### PR TITLE
might_permit_raw_init: also check arrays (take two)

### PR DESCRIPTION
**Pull request by Aaron1011**
This is a revival of PR https://github.com/rust-lang/rust/pull/79296 for a fresh Crater run

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot test

**Comment by Aaron1011** [comment]
@craterbot build-and-test

**Comment by Aaron1011** [comment]
@craterbot run mode=build-and-test

**Comment by RalfJung** [comment]
Looks like a big one here is `hyper`:

https://github.com/hyperium/hyper/blob/52214f391c0a18dc66d1ccff9c0c004c5da85002/src/proto/h1/role.rs#L118

**Comment by camelid** [comment]
triage: What's the status of this?

**Comment by Aaron1011** [comment]
Now that Hyper has been fixed, it might be worth it to do another Crater run.

**Comment by camelid** [comment]
Ok, I'll start a try run for now. I think re-running crater sounds good if you think that'd unblock this PR.

@bors try

**Comment by camelid** [comment]
Seems this needs a rebase and update to fix compilation errors.

@rustbot author

**Comment by camelid** [comment]
@Aaron1011 Should we run crater now?

**Comment by Aaron1011** [comment]
@camelid: Sounds good

@craterbot check

**Comment by Aaron1011** [comment]
@craterbot cancel

**Comment by Aaron1011** [comment]
@craterbot abort

**Comment by Aaron1011** [comment]
@craterbot run mode=build-and-test

**Comment by Mark-Simulacrum** [comment]
@craterbot retry-report

**Comment by RalfJung** [comment]
So going just over the crates whose name starts with a, b, c, the failures are almost all (>80%) caused by hyper (versions before https://github.com/hyperium/hyper/pull/2545) and ancient crossbeam. I added that info to https://github.com/rust-lang/rust/issues/66151. It's probably not worth keeping the PR open; I am not sure if old hyper and crossbeam will ever go sufficiently out of use that we can break them entirely.

**Comment by oli-obk** [comment]
We could backport patches to these old crates... I'm sure we can get the maintainers to do that if we do the impl work

**Comment by RalfJung** [comment]
Patched that don't raise the MSRV might be tricky though.

**Comment by RalfJung** [comment]
Also, tons of lockfiles will reference the old versions. So we'd also have to convince crater to do `cargo update` before doing its thing.

(I am pretty sure it currently doesn't do that, seeing as how many different versions of hyper 0.14 I saw in the crater logs.)

**Comment by Mark-Simulacrum** [comment]
> 

That's correct, this is currently not done, somewhat intentionally -- when possible, we try to avoid breaking builds even if `cargo update` is enough to fix things. Ideally we'd get both statuses, but that's a bunch of extra Crater time.

**Pull request closed without merging**
