### PR TITLE
SplitInclusive is public API

### PR DESCRIPTION
**Pull request by eggyal**

### CODE REVIEW

**Comment by eggyal** [comment]
@rustbot modify labels to +A-visibility +T-libs
cc @rust-lang/release as I think this ought to be beta-nominated too?

**Comment by jyn514** [comment]
@eggyal 1.51 is being promoted to stable *today*, monday: https://forge.rust-lang.org/release/process.html.

cc @rust-lang/release - I don't know if this is worth dealing with at such a late point.

**Comment by Mark-Simulacrum** [comment]
Trying to figure out context here - looks like this was just overlooked when stabilizing or so, and SplitInclusive is only exposed in core and not std.

I'm going to unilaterally beta-accept (we've not released a stable with this omission yet so going to drop the stable-nomination. The beta-backport will apply to both 1.51 and 1.52, though.

cc @rust-lang/libs so y'all are aware of this

@bors r+ rollup

**Comment by jyn514** [comment]
> Trying to figure out context here - looks like this was just overlooked when stabilizing or so, and SplitInclusive is only exposed in core and not std.

Yes, it was missed in https://github.com/rust-lang/rust/pull/77858.

**Comment by ijackson** [comment]
Sorry, I did indeed not spot the missing `pub` so I didn't make that public in `std` in #77858.

I'm kind of surprised that you can have a stability attribute on a non-public item at all, without generating some kind of lint.

@eggyal Thanks for fixing this.

**Comment by eggyal** [comment]
No problem, @ijackson. Also as Mark mentioned above, `SplitInclusive` is only exposed in `core` not `std`—is that intentional?

**Comment by ijackson** [comment]
> No problem, @ijackson. Also as Mark mentioned above, `SplitInclusive` is only exposed in `core` not `std`—is that intentional?

Err, wait, that is different to the missing `pub`?  No, that is not intentional.  I am very confused, sorry!

**Comment by ijackson** [comment]
I properly UTSL with actual coffee today and, err, ISWYM.  MR in a moment.

**Pull request merged**
