### PR TITLE
always define opaque types outside of trait solver

### PR DESCRIPTION
**Pull request by lcnr**
this matches the intended behavior of the new solver, mostly opening for crater and for some ideas on how to deal with the remaining breakage.

r? @oli-obk @compiler-errors

### CODE REVIEW

**Comment by lcnr** [comment]
this fails because the following pattern stops working:
```rust
#![feature(type_alias_impl_trait)]
fn main() {
    assert_eq!(foo().to_string(), "foo");
}

type Foo = impl std::fmt::Display;
fn foo() -> Foo {
    "foo"
}
```
not yet 100% sure why

**Comment by Dylan-DPC** [comment]
@lcnr any updates on that?

**Comment by lcnr** [comment]
closing as it causes significant breakage

**Pull request closed without merging**
