### PR TITLE
Err codes

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @jonathandturner

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by jonathandturner** [comment]
Failure looks legit:

```

---- Rust_Compiler_Error_Index_329 stdout ----
	<anon>:3:1: 8:2 warning: enum is never used: `Foo`, #[warn(dead_code)] on by default 
<anon>:3 enum Foo {
         ^
<anon>:4:9: 4:27 error: literal out of range for isize 
<anon>:4     X = 0x7fffffffffffffff,
                 ^~~~~~~~~~~~~~~~~~
<anon>:2:12: 2:32 note: lint level defined here 
<anon>:2     #[deny(overflowing_literals)]
                    ^~~~~~~~~~~~~~~~~~~~
thread 'Rust_Compiler_Error_Index_329' panicked at 'Some expected error codes were not found: ["E0370"]', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustdoc\test.rs:297


failures:
    Rust_Compiler_Error_Index_329
```

**Comment by GuillaumeGomez** [comment]
Not really since it works locally. I really don't understand the difference between the two...

**Comment by GuillaumeGomez** [comment]
I removed the change for the problem. I'll go back on it later.

**Comment by jonathandturner** [comment]
@GuillaumeGomez - is it ready for r+?

**Comment by GuillaumeGomez** [comment]
Yes.

**Comment by TimNN** [comment]
@GuillaumeGomez I believe the default enum discriminant type is `isize` thus on 64bit platforms you get the expected error but on 32bit platforms the `deny(overflowing_literals)` lint triggers first, so a potential fix would probably be to mark the enum as `#[repr(i64)]`.

**Comment by GuillaumeGomez** [comment]
@TimNN: Great idea! Want to do it? :)

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by TimNN** [comment]
@GuillaumeGomez: I'm pretty sure that `compile-fail/E0370.rs` will now fail on 64 bit platforms.

**Comment by GuillaumeGomez** [comment]
Ah right. I need to add the repr.

**Comment by GuillaumeGomez** [comment]
NOW it should be done.

**Comment by TimNN** [comment]
@GuillaumeGomez shouldn't it be

```rust
#[repr(i64)]
enum Foo {
    X = 0x7fffffffffffffff,
    Y, //~ ERROR E0370
}

fn main() {}
```

?

**Comment by GuillaumeGomez** [comment]
Yes it should... Why did I change it?

**Comment by GuillaumeGomez** [comment]
And updated.

**Pull request merged**
