### PR TITLE
Update miri

### PR DESCRIPTION
**Pull request by TimDiekmann**
r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
To update the lockfile, please run `x.py` locally (without further arguments) and then amend the commit.

**Comment by RalfJung** [comment]
Also this overlaps with https://github.com/rust-lang/rust/pull/59783

**Comment by RalfJung** [comment]
Please make this entire PR one commit with message "update miri"; that is the trigger for Travis in this PR to test if Miri still passes the test suite.

**Comment by TimDiekmann** [comment]
I'll wait until #59783 and create a new commit if needed as soon as it lands.

**Comment by RalfJung** [comment]
Closing because this is included in https://github.com/rust-lang/rust/pull/59810

**Pull request closed without merging**
