### PR TITLE
Use a more lightweight cache for erase_regions

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 6284bc1b5909f6452af037b507190bbabb1a4d4d

**Comment by michaelwoerister** [comment]
I'd like to enable caches for dependency-less functions like this one but I'm not sure a debug assertion is enough. Can we instead of make sure at compile time that a function cannot have dependencies? One way to do that would be to not give it access to the `tcx` in the first place. From the looks of it, erasing types (and probably quite a few other things like it) only needs access to interners. Maybe we could split out a subset of the context that can do nothing expect for allocating stuff. That would be a safe and generic extension of the query system that might help performance in quite a few places. I'd prefer that to one-off solutions with manual checking.

**Comment by Zoxc** [comment]
> Can we instead of make sure at compile time that a function cannot have dependencies?

I don't see how, given that we allow access to `TyCtxt` in TLS. The debug-only dependency fixed in this PR doesn't have a `tcx` for example.

**Comment by michaelwoerister** [comment]
> I don't see how, given that we allow access to TyCtxt in TLS. The debug-only dependency fixed in this PR doesn't have a tcx for example.

Yeah, that's true `:(`

It would still be good to turn this into a generic, sanctioned pattern with safe-guards against foot gunning ourselves. Maybe:
- Allow a way of defining a dependency-less query where the provider only gets access to a restricted version of the `tcx` (e.g. just interners). That already gives a good indication that one should not use the `tcx`.
- Keep the debug-only runtime check from this PR in place for such queries.
- Add documentation to the rustc-guide of what these queries are and why they work the way they work.

The `tcx` would still be accessible through TLS at least we'd have documentation and a clear template that people can use without having to remember that they need to do their checking and what they are allowed to do and what not. 

cc @nikomatsakis, who (I think) mentioned wanting to support dependenciless functions in Salsa too.

**Comment by Zoxc** [comment]
This is also the only thing using anon queries, which I'd also like to remove since it doesn't make sense to me.

**Comment by michaelwoerister** [comment]
As I said, I'm not against doing something like this in principle. But this isn't a pressing issue (i.e. the current solution works and performance improvement nice but not stellar), so I'd prefer if we supported this pattern in a general way (along the lines I described above) instead of doing a one-off solution.

**Comment by Dylan-DPC** [comment]
ping from triage @michaelwoerister any updates on this?

**Comment by michaelwoerister** [comment]
re: triage: My suggestions on how to move forward here are still up-to-date.

**Pull request closed without merging**
