### PR TITLE
Beta next

### PR DESCRIPTION
**Pull request by brson**
- https://github.com/rust-lang/rust/pull/42521
- https://github.com/rust-lang/rust/pull/42512
- https://github.com/rust-lang/rust/pull/42482
- https://github.com/rust-lang/rust/pull/42481
- https://github.com/rust-lang/rust/pull/42480

r? @nikomatsakis remember to untag 'beta-nominated' on linked issues

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors retry

 - timed out

**Comment by brson** [comment]
I bumped the prerelease version.

@bors r+

**Comment by alexcrichton** [comment]
@bors: retry

* timed out

**Comment by Mark-Simulacrum** [comment]
@bors retry

 - osx timed out, again...

**Comment by alexcrichton** [comment]
I pushed a commit to update the cargo submodule with a few backport fixes as well, so...

@bors: r+

**Pull request merged**
