### PR TITLE
move `considering_regions` to the infcx

### PR DESCRIPTION
**Pull request by lcnr**
it seems weird to prove some obligations which constrain inference vars while ignoring regions  in a context which considers regions. This is especially weird because even for a fulfillment context with ignored regions, we still added region outlives bounds when directly relating regions.

tbh our handling of regions is still very weird, but at least this is a step in the right direction imo.

r? rust-lang/types

### CODE REVIEW

**Comment by oli-obk** [comment]
Hmm... can't get the details of this perf regression:

> collector error: did not manage to obtain toolchain 03d488b48af9f66b91e9400387f781b82411fa82

**Comment by lqd** [comment]
Maybe some temporary network/server issue ? rustup-toolchain-master successfully downloads 03d488b48af9f66b91e9400387f781b82411fa82 here.

**Comment by oli-obk** [comment]
aha! `rustup` changed its exit code from `101` to something else, and the collector doesn't know about this yet

**Comment by oli-obk** [comment]
```
 6,261,975  ???:rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::hir_attrs, rustc_query_impl::plumbing::QueryCtxt>
 6,241,533  /build/glibc-sMfBJT/glibc-2.31/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_sse2_unaligned_erms
-5,701,890  ???:rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_hir::hir::AttributeMap>>
  -920,230  ???:<rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::hir_attrs
   320,080  ???:<rustc_infer::infer::InferCtxtBuilder>::ignoring_regions
   240,060  /build/glibc-sMfBJT/glibc-2.31/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:memcpy@GLIBC_2.2.5
   160,032  ???:<rustc_infer::infer::InferCtxtBuilder>::enter::<core::result::Result<alloc::vec::Vec<rustc_middle::ty::Predicate>, rustc_errors::ErrorGuaranteed>, rustc_trait_selection::traits::do_normalize_predicates::{closure
   140,028  ???:rustc_trait_selection::traits::normalize_param_env_or_error
  -114,593  ???:core::slice::sort::choose_pivot::<(rustc_span::def_id::DefPathHash, &rustc_hir::hir::OwnerInfo), <[(rustc_span::def_id::DefPathHash, &rustc_hir::hir::OwnerInfo)]>::sort_unstable_by_key<rustc_span::def_id::DefPathHash, rustc_ast_lowering::compute_hir_hash::{closure
    99,845  ???:core::slice::sort::recurse::<(rustc_span::def_id::DefPathHash, &rustc_hir::hir::OwnerInfo), <[(rustc_span::def_id::DefPathHash, &rustc_hir::hir::OwnerInfo)]>::sort_unstable_by_key<rustc_span::def_id::DefPathHash, rustc_ast_lowering::compute_hir_hash::{closure
    40,020  ???:<rustc_middle::ty::context::TyCtxt as rustc_infer::infer::TyCtxtInferExt>::infer_ctxt
    33,862  /build/glibc-sMfBJT/glibc-2.31/string/../sysdeps/x86_64/strcmp.S:strcmp
   -20,004  ???:<rustc_middle::ty::context::TyCtxt>::lint_level_at_node
    19,968  ???:<rustc_middle::lint::LintLevelSets>::get_lint_level
```

**Comment by oli-obk** [comment]
let's try rebasing and running perf again, this diff looks really weird

**Comment by oli-obk** [comment]
@bors r+

the perf part seems like just some changes in how LLVM optimizes some memcpy

**Comment by pnkfelix** [comment]
* The secondary regressions were [already anticipated](https://github.com/rust-lang/rust/pull/99501#issuecomment-1191647607) by the PR reviewer. The primary regressions are both diesel and they look like blips in the data to me from the graph over time.
* Marking as triaged.


@rustbot label: +perf-regression-triaged.

**Pull request merged**
