### PR TITLE
Refactor task system for efficiency

### PR DESCRIPTION
**Pull request by Zoxc**
Split from https://github.com/rust-lang/rust/pull/56509

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@Zoxc, would you be OK with closing this PR? It changes quite a bit of code but the benefit of that is doubtful.

**Comment by Zoxc** [comment]
Could you make your objections a bit more concrete? I like that this splits up `with_task_impl` which is rather large currently, and that `ImplicitCtxt` is only changed once when executing a query.

**Comment by michaelwoerister** [comment]
My objections are:
- Changing code in a multi-user codebase comes at a cost. People who understood the code before have to invest time into understanding it again. A change also needs to be reviewed, which costs time and energy, especially if the change affects complicated logic. It might also introduce new bugs that are not spotted during review, causing follow-up work. So any (non-trivial) change starts out with a kind of a debt that it has to make up for in improved code quality/readability, improved runtime efficiency, or some other improvement. The changes in this PR don't make the code more efficient in practice, increase code duplication, and makes already too complicated logic a bit more complicated, so in my estimation it doesn't offset the debt it introduces.
- The current version of the code follows a kind of template pattern with `with_task_impl` giving a skeleton for the logic that needs to be executed for all kinds of task. This reduces code duplication and thus the risk of forgetting to update other the kinds of tasks, when fixing a bug in one. 
- It also gives the information that different kinds of tasks basically follow the same kind of logic, which is quite a big win for making the code more readable, I think. 
- The version in this PR increases the number of public `DepGraph::with_*` methods from 5 to 7, making it even harder to understand which one to use. I'd rather see the number reduced, if possible.
- The interaction between query system and task system becomes more circular than before, increasing the coupling of the two systems.
- It breaks the `ProfileQueriesMsg`calls, which to me seems like an indication that there is too much duplication of logic.

**Comment by Dylan-DPC** [comment]
ping from triage @michaelwoerister @Zoxc what's the update on this?

**Pull request closed without merging**
