### PR TITLE
TcpListener::bind_to_port and related changes

### PR DESCRIPTION
**Pull request by stepancheg**
- add `IPV6_V6ONLY` setsockopt constant
- use it on Windows on listening sockets, because on Windows, unlike other operating systems, socket listening on IPv6 doesn't accept IPv4 connections by default
- add `bind_to_port` shortcut to hide all those details from rust users

Note, I didn't try code on Windows. Only tried on OSX with `if cfg!(windows)` line commented out, in which case `setsockopt` is called and did nothing, but at least, it didn't fail, and tests passed.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Changes like this, however, should go through the RFC process instead of being made through a PR first. We do [plan on allowing](https://github.com/rust-lang/rfcs/blob/master/text/0517-io-os-reform.md#sockets) advanced configuration of sockets other than the high level convenience constructors of `TcpListener::bind` for example. I also don't mind creating an RFC issue to start tracking this sort of implementation as I'd love to start work on it sooner rather than later!

**Comment by stepancheg** [comment]
@alexcrichton could you please explain what exactly should I do? Create an issue in rust-lang/rfcs/? Write a new RFC or patch existing RFC 517?

Shouldn't I submit a new PR with first two patches of this RFC? I. e. patches that just unify `bind` behavior on Windows and other OSes.

**Comment by alexcrichton** [comment]
To add these now an RFC would be written, but I would recommend creating a "`std::net` wishlist issue" along the lines of that [for `std::fs`](https://github.com/rust-lang/rfcs/issues/939), we may consolidate these at one point into another umbrella issue but it's good to keep track of feature requests for `std::net`.

I don't think that we want the second patch for now, however. We've been recently moving a bit away from that sort of compatibility across OSes. For example the code to explicitly prevent opening a directory was removed along with special Windows-specific code to remove readonly files. We've been moving more in a direction that the implementation of the underlying primitive is clear and easy to understand without having any form of "magic" happening under the hood (e.g. setting some options only on some platforms). I do understand that this make is such that the precise behavior is not cross platform, but that is somewhat of an inevitability.

**Comment by stepancheg** [comment]
I've created a [long list of issues](https://github.com/rust-lang/rfcs/issues/957).

**Comment by alexcrichton** [comment]
Thanks!

**Pull request closed without merging**
