### PR TITLE
Enable coinduction support for Safe Transmute

### PR DESCRIPTION
**Pull request by bryangarza**
This patch adds the `#[rustc_coinductive]` annotation to `BikeshedIntrinsicFrom`, so that it's possible to compute transmutability for recursive types.

## Motivation
Safe Transmute currently already supports references (#110662). However, if a type is implemented recursively, it leads to an infinite loop when we try to check if transmutation is safe.

A couple simple examples that one might want to write, that are currently not possible to check transmutability for:
```rs
#[repr(C)] struct A(&'static B);
#[repr(C)] struct B(&'static A);
```

```rs
#[repr(C)]
enum IList<'a> { Nil, Cons(isize, &'a IList<'a>) }
#[repr(C)]
enum UList<'a> { Nil, Cons(usize, &'a UList<'a>) }
```

Previously, @jswrenn was considering writing a co-inductive solver from scratch, just for the `rustc_tranmsute` crate. Later on as I started working on Safe Transmute myself, I came across the `#[rustc_coinductive]` annotation, which is currently only being used for the `Sized` trait. Leveraging this trait actually solved the problem entirely, and it saves a lot of duplicate work that would have had to happen in `rustc_transmute`.

### CODE REVIEW

**Comment by compiler-errors** [comment]
This PR marks the `BikeshedIntrinsicFrom` ("the safe transmute") trait as coinductive.

We shouldn't be committing to too much by making this trait coinductive, given that 1. it's not intended to be user implementable and has no user-written implementations, 2. it has no supertraits, and 3. is unstable.

@rfcbot fcp merge

**Comment by BoxyUwU** [comment]
I think it would be good for lcnr to have a look at this since afaik they have a good understanding of coinduction.

**Comment by lcnr** [comment]
@rfcbot reviewed

**Pull request merged**
