### PR TITLE
Implement Eq for Thread

### LINKED ISSUE #21507: Tracking issue for std::thread::ThreadId
# Update description

Tracking issue for `std::thread::ThreadId`. Points to consider when stabilizing:
- Implementation of a mutex + u64, unconditional panic if space is exhausted
- Various traits on `ThreadId`, including `Copy`
# Original report

Not sure if it can be considered as bug but it sure cripples the existing threading API (e.g., makes it harder for a thread to identify itself or store/pass its identity). 

// it could also be nice if Thread was able to return a unique integer id() (or hash itself?..).

### PR DESCRIPTION
**Pull request by remram44**
Fixes #21507

This simply compares the Arcs in the Threads since there is one Inner struct per thread.

Will add tests if there is interest in this.

### CODE REVIEW

**Comment by eefriedman** [comment]
The idea and implementation seem reasonable.

**Comment by alexcrichton** [comment]
I would personally prefer an implementation route along the lines #29457, which is to say using the system primitives over our own abstractions, but I believe that today both will always yield the same results. 

Regardless, though, I'm gonna tag this with T-libs so it comes up during libs triage. Thanks for the PR @remram44!

**Comment by alexcrichton** [comment]
Oh wait that doesn't make sense as an implementation strategy, these only contain our own allocations, nevermind!

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and there was quite a bit of discussion and we didn't quite reach a conclusion. Some thoughts we had were:

* It may not be the case that we want to literally compare `Thread` structures but rather perhaps an opaque `ThreadId`. This opaque structure could then have all the necessary traits implemented.
* We weren't quite sure what the concrete use case was here. We could come up with some theoretical ideas, but we couldn't think of something we'd actually use it for in practice, so do you have something in mind for this?
* This is closely entangled with https://github.com/rust-lang/rust/pull/29448, so we'll probably want to coordinate among those two.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with the comments on this and #29448 addressed!

**Pull request closed without merging**
