### PR TITLE
Add a test that -fPIC is applied

### PR DESCRIPTION
**Pull request by brson**
r? @alexcrichton Can it really be this simple? I've tested it works, but still testing that it used to fail.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Let's find out!

**Comment by frewsxcv** [comment]
Fails on Windows https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1950/job/9mn79l0oheq3cus9

@bors r-

**Comment by brson** [comment]
comparing `UNAME` to `Windows` is bogus

**Comment by brson** [comment]
@bors r=alexcrichton

Picked a different env var.

**Comment by alexcrichton** [comment]
@bors: retry

* clone network error

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault #39003

**Pull request merged**
