### PR TITLE
MIR dominators: computed on-demand and cached

### PR DESCRIPTION
**Pull request by tmiasko**
* Cached inside MIR body - motivated by potential reuse opportunity when
  code generating different instantiations of the same generic code.

* Delayed until demanded in borrowck - motivated by observation that
  some check / metadata only builds, where dominator computation is hot,
  never query the dominator tree.

### CODE REVIEW

**Comment by tmiasko** [comment]
Separated part of changes into #106976 and #106975. Not sure if caching dominators globally is good time / memory trade-off.

**Comment by cjgillot** [comment]
I think this PR is a good idea. From the perf report, average effect on max-rss is almost 0, so we can't conclude that this caching has a significant memory impact, while it sure has a instr-count impact.

Borrowck is not the only place that may use dominators. https://github.com/rust-lang/rust/pull/106908 and https://github.com/rust-lang/rust/pull/106285 may benefit from this caching too.

**Comment by tmiasko** [comment]
If you are still interested in this, I can reopen and rerun perf after merging the borrowck changes in #106976, so the effect of caching is benchmarked in isolation.

**Comment by tmiasko** [comment]
Caching on its own is not an improvement right now. It might make sense to revisit this after #106908, #106285, #107172 land, if all those passes can indeed be organized to reuse the computation.

**Pull request closed without merging**
