### PR TITLE
update Miri

### LINKED ISSUE #83242: `miri` no longer builds after rust-lang/rust#82122
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#82122, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @bstrie, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/83242
Cc @rust-lang/miri r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
This PR doesn't change anything about coverage reports...?!?
@bors retry

**Comment by richkadel** [comment]
@RalfJung @tmiasko -

Are we seeing this failure in any other PRs? If so, then maybe the change @tmiasko just merged is related, but I don't (yet) see how that change would be related. That PR enabled support for higher `-Zmir-opt-level`s, but the test doesn't appear to enable it (AFAICT), unless `doctest` enables higher than default `mir-opt-level`s under the hood?

But it's possible the coverage failure is related to the MIRI changes in @RalfJung 's PR here. If the PR changes the generated MIR so that the `coverage` MIR transform has less information to work with, it might cause an issue.

@tmiasko - any thoughts about how your PR could have affected the coverage output in this situation?

Looks like coverage passed on at least some other platforms.

@RalfJung - Could your changes affect MIR on Windows different from Linux?

--- expected_show_coverage.doctest.txt	2021-03-18 13:45:52.989271700 +0000
+++ /d/a/rust/rust/build/x86_64-pc-windows-msvc/test/run-make-fulldeps/coverage-reports/coverage-reports/actual_show_coverage.doctest.txt	2021-03-18 14:40:14.025645000 +0000
@@ -74,13 +74,13 @@
    70|      1|/// doctest_crate::fn_run_in_doctests(3);
    71|      1|/// ```
    72|       |///
-   73|      1|fn main() {
-   74|      1|    if true {
-   75|      1|        assert_eq!(1, 1);
+   73|       |fn main() {
+   74|       |    if true {
+   75|       |        assert_eq!(1, 1);
    76|       |    } else {
    77|       |        assert_eq!(1, 2);
    78|       |    }
-   79|      1|}
+   79|       |}

**Comment by RalfJung** [comment]
This PR does not change the generated MIR. It has no effect at all on rustc. It just updates [Miri-the-tool](https://github.com/rust-lang/miri/), but leaves [the core CTFE interpreter engine](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir/src/interpret/) ("Miri engine") unchanged.

**Comment by richkadel** [comment]
Got it. I don't see how this could be spurious, but could you do a bors retry and confirm if the failure always happens?

**Comment by RalfJung** [comment]
Already did the retry, the next bors slot is ours.

**Pull request merged**
