### PR TITLE
Change visit api

### PR DESCRIPTION
**Pull request by spastorino**
r? @oli-obk 

In the [first commit](https://github.com/rust-lang/rust/commit/37386d366a816bc2e63749c7b6045108a6167135) of this PR, I'm changing `visit_place` to be the function that traverses the `Place` and have only that responsibility. Then there are two other functions `visit_place_base` and `visit_projection` which are the ones in charge of visiting the base and the projection. Visitor implementors can implement any of those.

In the [second commit](https://github.com/rust-lang/rust/commit/e786f631b815d171051279e0d6cfe055c75bec2e) we can already see some things that confuses me, which I think this division will make more clear. The old code, first checked if the place was a base, did something with it and then called `super_place` [here](https://github.com/rust-lang/rust/commit/e786f631b815d171051279e0d6cfe055c75bec2e#diff-d583e4efe1a72516e274158e53223633L678). `super_place` checks again if it's a base [here](https://github.com/rust-lang/rust/blob/master/src/librustc/mir/visit.rs#L679-L684) and in case is a local, visits the local and stuff like that. That's not very obvious on the code, and if I'm not wrong it's not needed. In this PR or we have [this](https://github.com/rust-lang/rust/commit/e786f631b815d171051279e0d6cfe055c75bec2e#diff-d583e4efe1a72516e274158e53223633R673) as I did or we can just do `- => self.super_place_base(...)` and that will be obvious that I'm letting the default implementation process the base.

### CODE REVIEW

**Comment by spastorino** [comment]
I've processed the rest of the `visit_place` implementations and most are unaffected because they do not even care about the default implementation and they roll their own way of traversing `Place`.

So this ends being a little change that I think it's a bit better but may not worth applying, unsure to be honest :).

**Comment by spastorino** [comment]
In particular, having `visit_place_base` help in cases like https://github.com/rust-lang/rust/commit/375489199209739911a0174a92c4bcd00009f482#diff-e682b38b565035a82f29560c3b79144bR208

**Comment by oli-obk** [comment]
> The old code, first checked if the place was a base, did something with it and then called super_place here. super_place checks again if it's a base here and in case is a local, visits the local and stuff like that. That's not very obvious on the code, and if I'm not wrong it's not needed. In this PR or we have this as I did or we can just do - => self.super_place_base(...) and that will be obvious that I'm letting the default implementation process the base.

I think just leaving a comment on the `_ =>` arm will clear up that logic way more than calling `super_place_base` without that actually being needed. Just leave a comment mentioning that `Local` has no relevance for the collector and a FIXME for `StaticKind::Promoted` as per https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/collector.20collects.20optimized.20out.20promoteds

**Comment by oli-obk** [comment]
> So this ends being a little change that I think it's a bit better but may not worth applying, unsure to be honest :).

I like it, and we're going to "need it" (in some form) anyway when moving to slice projections.

**Review by oli-obk — APPROVED** [review]

**Comment by pietroalbini** [comment]
The rand crate broke.
@bors retry

**Pull request merged**
