### PR TITLE
Deduplicate lines in long const-eval stack trace

### LINKED ISSUE #92796: Unconditional recursion in a `const fn` produces a massive diagnostic
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=254423b9c4227b5abdbd52f39176a2b4)):

```rust
#![allow(unused)]

const fn f<T>(x: T) {
    f(x);
}

const X: () = f(1);
```

The current output is:
<details>
<summary>Massive diagnostic</summary>

```
warning: function cannot return without recursing
 --> src/lib.rs:3:1
  |
3 | const fn f<T>(x: T) {
  | ^^^^^^^^^^^^^^^^^^^ cannot return without recursing
4 |     f(x);
  |     ---- recursive call site
  |
  = note: `#[warn(unconditional_recursion)]` on by default
  = help: a `loop` may express intention better if this is on purpose

error: any use of this value will cause an error
 --> src/lib.rs:4:5
  |
4 |     f(x);
  |     ^^^^
  |     |
  |     reached the configured maximum number of stack frames
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     inside `X` at src/lib.rs:7:15
...
7 | const X: () = f(1);
  | -------------------
  |
  = note: `#[deny(const_err)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
```
</details>

Ideally, the duplicate lines should be hidden:

```
warning: function cannot return without recursing
 --> src/lib.rs:3:1
  |
3 | const fn f<T>(x: T) {
  | ^^^^^^^^^^^^^^^^^^^ cannot return without recursing
4 |     f(x);
  |     ---- recursive call site
  |
  = note: `#[warn(unconditional_recursion)]` on by default
  = help: a `loop` may express intention better if this is on purpose

error: any use of this value will cause an error
 --> src/lib.rs:4:5
  |
4 |     f(x);
  |     ^^^^
  |     |
  |     reached the configured maximum number of stack frames
  |     inside `f::<i32>` at src/lib.rs:4:5
  |     [... inside N additional calls to `f::<i32>` ...]
  |     inside `X` at src/lib.rs:7:15
...
7 | const X: () = f(1);
  | -------------------
  |
  = note: `#[deny(const_err)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
```

@rustbot modify labels: +A-const-fn +D-verbose

### PR DESCRIPTION
**Pull request by compiler-errors**
Lemme know if this is kinda overkill, lol.

Fixes #92796

### CODE REVIEW

**Comment by oli-obk** [comment]
It's not overkill. We already have two huge tests in our test suite showing this, albeit with mutual recursion. Not sure how we could catch mutual recursion properly... ideas?

**Comment by compiler-errors** [comment]
What are the tests that show a mutually-recursive trace?

I could probably think of something more clever than this to detect those cases. Maybe some sort of windowed duplicate detection.

**Comment by oli-obk** [comment]
The examples are

* https://github.com/rust-lang/rust/blob/master/src/test/ui/infinite/infinite-recursion-const-fn.stderr
* https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/uninhabited-const-issue-61744.stderr

**Comment by compiler-errors** [comment]
I'll get around to this eventually... finding out how to print a nice output for repeating set of lines (N>1) is kinda hard. I have some ideas, but kinda lazy to write em out.

@rustbot author

**Comment by oli-obk** [comment]
@bors r+ rollup

Until then, this is already a good improvement

**Pull request merged**
