### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by ehuss**
3 commits in 79c769c3d7b4c2cf6a93781575b7f592ef974255..089cbb80b73ba242efdcf5430e89f63fa3b5328d
2020-06-11 22:13:37 +0000 to 2020-06-15 14:38:34 +0000
- Support linker with -Zdoctest-xcompile. (rust-lang/cargo#8359)
- Fix doctests not running with --target=HOST. (rust-lang/cargo#8358)
- Allow passing a registry index url directly to `cargo install` (rust-lang/cargo#8344)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@ehuss Does this re-enable doc tests for std? If so we might want to rollup=never and prioritize it.

**Comment by ehuss** [comment]
No, this re-enables doc-tests on nightly (affects the rest of the ecosystem that uses nightly).

Doc-tests for std will be re-enabled by #73411.

**Comment by Dylan-DPC** [comment]
let this merge individually 

@bors p=1 rollup=never

**Comment by Manishearth** [comment]
@bors r-

This is going to fail, there are some doctests that were never passing that need to be fixed

From https://github.com/rust-lang/rust/pull/73536#issuecomment-646969816


```
---
---- result.rs - result::Result<T, E>::as_deref (line 1157) stdout ----
error[E0658]: use of unstable library feature 'inner_deref'
 --> result.rs:1160:14
  |
6 | assert_eq!(x.as_deref(), y);
  |
  |
  = note: see issue #50264 <***/issues/50264> for more information
  = help: add `#![feature(inner_deref)]` to the crate attributes to enable
error[E0658]: use of unstable library feature 'inner_deref'
  --> result.rs:1164:14
   |
   |
10 | assert_eq!(x.as_deref(), y);
   |
   |
   = note: see issue #50264 <***/issues/50264> for more information
   = help: add `#![feature(inner_deref)]` to the crate attributes to enable
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
Couldn't compile the test.
Couldn't compile the test.
---- result.rs - result::Result<T, E>::as_deref_mut (line 1191) stdout ----
error[E0308]: mismatched types
 --> result.rs:1193:40
  |
5 | let y: Result<&mut str, &mut u32> = Ok("HELLO");
  |                                        ^^^^^^^ types differ in mutability
  = note: expected mutable reference `&mut str`
                     found reference `&'static str`

error[E0658]: use of unstable library feature 'inner_deref'
error[E0658]: use of unstable library feature 'inner_deref'
 --> result.rs:1194:14
  |
6 | assert_eq!(x.as_deref_mut().map(|x| { x.make_ascii_uppercase(); x }), y);
  |
  |
  = note: see issue #50264 <***/issues/50264> for more information
  = help: add `#![feature(inner_deref)]` to the crate attributes to enable
error[E0308]: mismatched types
 --> result.rs:1197:41
  |
  |
9 | let y: Result<&mut str, &mut u32> = Err(&42);
  |                                         ^^^ types differ in mutability
  = note: expected mutable reference `&mut u32`
                     found reference `&u32`

error[E0658]: use of unstable library feature 'inner_deref'
error[E0658]: use of unstable library feature 'inner_deref'
  --> result.rs:1198:14
   |
10 | assert_eq!(x.as_deref_mut().map(|x| { x.make_ascii_uppercase(); x }), y);
   |
   |
   = note: see issue #50264 <***/issues/50264> for more information
   = help: add `#![feature(inner_deref)]` to the crate attributes to enable
error: aborting due to 4 previous errors
```

**Comment by ehuss** [comment]
@Manishearth I think you may have this PR mistaken for #73411.  The in-tree Cargo is not used for anything (besides cargotest, which just started a few days ago).

@bors r+

**Comment by Manishearth** [comment]
@ehuss ah, i see

**Comment by ehuss** [comment]
@bors retry
The macOS x86_64 job inexplicably was running 2-3 times slower than normal (based on timing data).  No obvious hardware differences. 🤷

**Pull request merged**
