### PR TITLE
remove "much" from unicode diagnostic

### PR DESCRIPTION
**Pull request by euclio**
The English seems slightly awkward to me, and it's unnecessary.

### CODE REVIEW

**Comment by cuviper** [comment]
"X looks much like Y" is not an unusual construct.  It emphasizes a strong similarity.

**Comment by euclio** [comment]
Didn't mean to imply that it's unusual or incorrect. It just sounds a little odd to my ear. I figured that if you can get the same message across in fewer words, why not?

**Comment by arielb1** [comment]
Umm for some reason I was convinced this code was in libstd.

But it's in libsyntax.
@bors r+ rollup

**Pull request merged**
