### PR TITLE
Don't print the profiling summary to stdout when -Zprofile-json is set

### PR DESCRIPTION
**Pull request by wesleywiser**
cc rust-lang-nursery/rustc-perf#299

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I'm wondering if the better approach here is to profile if either `-Zself-profile` is passed or `-Zprofile-json` is passed and then you can pass both if you want both? Not sure that would be super easy to integrate though

**Comment by wesleywiser** [comment]
Ok. I that should be easy to do.

**Comment by wesleywiser** [comment]
Done

**Pull request merged**
