### PR TITLE
fix top level attr spans

### PR DESCRIPTION
**Pull request by mikhail-m1**
issue #36530
?r @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
LGTM

@bors r+ rollup

**Comment by jonathandturner** [comment]
@bors retry

Seems like something didn't get cleaned up from a previous build

**Comment by mikhail-m1** [comment]
@jonathandturner should I do something to merge the PR?

**Comment by jonathandturner** [comment]
@mikhail-m1 - I think you're probably okay.  I tried doing a few rollups but they failed because other PRs in the rollup failed.

**Comment by pmarcelll** [comment]
The linux buildbot [failed today](https://buildbot.rust-lang.org/builders/nightly-dist-rustc-linux/builds/658) because of this PR.

**Comment by TimNN** [comment]
The problem seems to be that the test during `distcheck` was run with a stable compiler (without a (valid) bootstrap key), I think.

**Comment by TimNN** [comment]
Never mind, the actual problem is that the missing lines are not printed when stability is overridden with a bootstrap key, I think.

**Pull request merged**
