### PR TITLE
add a panic-strategy field to the target specification

### LINKED ISSUE #36647: Panic=abort as a target option?
Let's assume a target with no unwinding support (e.g. a small system on a chip).  [RFC 1513](https://github.com/rust-lang/rfcs/blob/master/text/1513-less-unwinding.md) added a `-C panic=strategy` flag and a cargo profile option for disabling the unwinding machinery. However, even with those options, we still need dummy implementations for `eh_personality` and `_Unwind_Resume`. 

The reason is that the cross-compiled sysroot (e.g. via xargo) still contains references to those functions. We can avoid this by setting `RUSTFLAGS` to `-C panic=abort` when invoking `xargo`. This way, the sysroot is created without unwinding. This solution works, but feels a bit hacky.

We could solve this problem in an easier way if we added a option for `panic=abort` in the target json. Then we could express targets without unwinding support and xargo would automatically compile the sysroot correctly.

### PR DESCRIPTION
**Pull request by japaric**
Now a target can define its panic strategy in its specification. If a
user doesn't specify a panic strategy via the command line, i.e. '-C
panic', then the compiler will use the panic strategy defined by the
target specification.

Custom targets can pick their panic strategy via the "panic-strategy"
field of their target specification JSON file. If omitted in the
specification, the strategy defaults to "unwind".

closes #36647

---

I checked that compiling an executable for a custom target with "panic-strategy" set to "abort" doesn't need the "eh_personality" lang item and also that standard crates compiled for that custom target didn't contained undefined symbols to _Unwind_Resume. But this needs an actual unit test, any suggestion on how to test this?

Most of the noise in the diff is due to moving `PanicStrategy` from the `rustc` to the `rustc_back` crate.

r? @alexcrichton 
cc @phil-opp

### CODE REVIEW

**Comment by oli-obk** [comment]
travis failed, I think you need some stage1 cfg attributes

```
Testing librustc stage2 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling fmt_macros v0.0.0 (file:///build/src/libfmt_macros)
   Compiling syntax_pos v0.0.0 (file:///build/src/libsyntax_pos)
   Compiling rustc_errors v0.0.0 (file:///build/src/librustc_errors)
   Compiling syntax v0.0.0 (file:///build/src/libsyntax)
   Compiling build_helper v0.1.0 (file:///build/src/build_helper)
   Compiling serialize v0.0.0 (file:///build/src/libserialize)
   Compiling flate v0.0.0 (file:///build/src/libflate)
   Compiling rustc_llvm v0.0.0 (file:///build/src/librustc_llvm)
   Compiling rustc_const_math v0.0.0 (file:///build/src/librustc_const_math)
   Compiling rustc_macro v0.0.0 (file:///build/src/librustc_macro)
   Compiling rustc_data_structures v0.0.0 (file:///build/src/librustc_data_structures)
   Compiling rustc_platform_intrinsics v0.0.0 (file:///build/src/librustc_platform_intrinsics)
   Compiling rustc_bitflags v0.0.0 (file:///build/src/librustc_bitflags)
   Compiling syntax_ext v0.0.0 (file:///build/src/libsyntax_ext)
   Compiling rustc_back v0.0.0 (file:///build/src/librustc_back)
   Compiling arena v0.0.0 (file:///build/src/libarena)
   Compiling log v0.0.0 (file:///build/src/liblog)
   Compiling rustc v0.0.0 (file:///build/src/librustc)
   Compiling rustc_save_analysis v0.0.0 (file:///build/src/librustc_save_analysis)
error[E0308]: mismatched types
    --> src/librustc/session/config.rs:2311:25
     |
2311 |         opts.cg.panic = PanicStrategy::Abort;
     |                         ^^^^^^^^^^^^^^^^^^^^ expected enum `core::option::Option`, found enum `rustc_back::PanicStrategy`
     |
     = note: expected type `core::option::Option<rustc_back::PanicStrategy>`
     = note:    found type `rustc_back::PanicStrategy`

error: aborting due to previous error
```

**Comment by japaric** [comment]
@oli-obk Thanks for the heads up. I don't think we need a cfg here because this is a test which can't be run against stage0 (stage1 already has the change to Option<PanicStrategy>).

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @japaric!

**Comment by Ericson2314** [comment]
What happens when a Cargo file and target both specify the panic strategy? I'd prefer it if Cargo files specified a *set of allowed* panic strategies and then the target specification alone picked the one used.

[Also, would be convenient to specify a map of names to targets in a (virtual) workspace root.]

**Comment by japaric** [comment]
@Ericson2314 Under the current implementation of Cargo, `profile.*.panic` will be preferred over what the target specifies because Cargo passes `-C panic=$PROFILE` to its `rustc` invocations.

**Comment by Ericson2314** [comment]
Ok, that seems good enough for now

**Pull request merged**
