### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by steveklabnik**
- Successful merges: #25209, #25254, #25272, #25278, #25282, #25283, #25288, #25292, #25302, #25304
- Failed merges:

### CODE REVIEW

**Comment by michaelsproul** [comment]
Something weird going on with #25209. @llogiq?

**Comment by llogiq** [comment]
Strange, but I'm in vacation, so let's try again next Werk.

**Comment by llogiq** [comment]
Looking into it, it appears that I used print! In the tests, which triggered the error on pretty-printing. I'll change this to assert!s.

**Comment by llogiq** [comment]
Done the change. I'm still a bit puzzled why it failed, though.

**Pull request closed without merging**
