### PR TITLE
Remove internal liblog

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit deletes the internal liblog in favor of the implementation that
lives on crates.io. Similarly it's also setting a convention for adding crates
to the compiler. The main restriction right now is that we want compiler
implementation details to be unreachable from normal Rust code (e.g. requires a
feature), and by default everything in the sysroot is reachable via `extern
crate`.

The proposal here is to require that crates pulled in have these lines in their
`src/lib.rs`:

    #![cfg_attr(rustbuild, feature(staged_api, rustc_private))]
    #![cfg_attr(rustbuild, unstable(feature = "rustc_private", issue = "27812"))]

This'll mean that by default they're not using these attributes but when
compiled as part of the compiler they do a few things:

* Mark themselves as entirely unstable via the `staged_api` feature and the
  `#![unstable]` attribute.
* Allow usage of other unstable crates via `feature(rustc_private)` which is
  required if the crate relies on any other crates to compile (other than std).

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

Note that this is the first crates.io crate to be included in the compiler itself, but I believe that everything is ironed out!

Also note that we [have a test](https://github.com/rust-lang/rust/blob/master/src/test/run-make/sysroot-crates-are-unstable/Makefile) if a crate is used and the annotations above are forgotten. We also have [license checking](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs) for crates.io deps to get errors by default if were working with unusual licenses.

**Comment by rkruppe** [comment]
I seem to recall that the behavior of `debug!` diverged between these two logging libraries: the internal version (the one being removed here) strips them if `debug_assertions` are disabled, while the crates.io version doesn't. Is this correct, and if so, are we okay with changing that?

**Comment by alexcrichton** [comment]
@rkruppe for the compiler I've now enabled the `release_max_level_info` which I believe should have the same effect.

**Comment by alexcrichton** [comment]
(good catch!)

**Comment by alexcrichton** [comment]
@bors: r-

this breaks a number of crates

**Comment by steveklabnik** [comment]
> this breaks a number of crates

How did you determine this?

**Comment by alexcrichton** [comment]
Heh via wizardry :)

(the travis logs also indicate this)

I have suspicions for what's going on here and how to fix it, I don't have time to act on them just yet though.

**Comment by frewsxcv** [comment]
It looks like Travis hit an ICE. Is that related to these changes?

**Comment by alexcrichton** [comment]
No idea how, but my guess is yes :(

@bors: r-

**Comment by alexcrichton** [comment]
@bors: r+

@frewsxcv I wouldn't recommend rolling this up though...

**Comment by alexcrichton** [comment]
So the failure there is due to a difference in the internal liblog and the external liblog. The internal liblog is intended for one implementation of logging ever, what's now on crates.io as `env_logger`. The external liblog, however, is intended for multiple implementations of logging. A consequence of this is that if you specify `RUST_LOG=foo=debug` then the behavior is different for a non-`foo` module (aka the compiler).

With the internal version *nothing* will be executed in a `debug!` statement if `RUST_LOG=foo=debug` given. The check of `foo=debug` is rolled into the guard before anything is logged/executed. With the external version then liblog only has an absolute maximum log level, not a per-module maximum log level. This means that the `env_logger` crate configures this at the debug log level (as this was the maximum level of any module requested) and the per-module filter happens later in the actual logger implementation. Consequently the compiler will actually evaluate all `debug!` expression given `RUST_LOG=foo=debug` even though it doesn't actually print anything.

The failure is apparently an actual bug in the compiler (I believe fixed now thanks to @eddyb) but this is a pretty significant change which I doubt others have expected as well. In light of that I'd like to cc @rust-lang/compiler and get other opinions on this.

Is this just a non-starter? Is it possible that there are few enough "expensive" debug checks that they can be guarded with the `log_enabled!` macro? 

Also cc @sfackler

**Comment by alexcrichton** [comment]
The [external](https://github.com/rust-lang-nursery/log/blob/25e349c7389ab63a9f5303a9a6183aa9d723b0a0/src/macros.rs#L27) and [internal](https://github.com/rust-lang/rust/blob/244f893ed704a60841d4615445d540a21a8d7722/src/liblog/macros.rs#L61) versions both use `format_args!`. 

And right yeah the formatting implementations are never run in either liblog implementation (unless the logging is literally enabled), just the construction of the arguments to pass to `Debug`

**Comment by eddyb** [comment]
@alexcrichton I'm going to have some fun looking at all `debug!` statements 😆.
(It shouldn't be that bad, since the common case of all identifiers isn't really slow)

**Comment by eddyb** [comment]
I've found 3 groups of potentially-relevant `debug!` (out of 1616 total in my currently workdir):
* 87 `\bdebug!\("[^"]*$` (multi-line format string `debug!`)
* 99 `\bdebug!\("[^"]*",[^)]*\(` (single-line `debug!` with a call in an argument)
* 508 `\bdebug!\("[^"]*",[^)]*$` (multi-line `debug!` with single-line format string)

Multi-line regex technology could allow us to reach further (although matching parens would be ideal).

I've looked at about two thirds of them before I accidentally reset the last group's search, which changed the order, and I wasn't tracking my progress carefully. Oh well, still somewhat useful.

<details>
<summary>(Partial) breakdown of non-trivial operations in <code>debug!</code> (click to expand)</summary>

* 13 `item_path_str`
* 9 `def_id_to_string`
* 2 `node_path_str`
* 7 `node_to_string`
* 4 `node_to_pretty_string`
* 1 `item_to_string`
* 2 `pprust::to_string`
* 1 `token_to_string`
* 4 `span_to_string`
* 2 `path_name_i`
* 1 `names_to_string`
* 1 `module_to_string`
* 9 `bits_to_string`
  * can be expensive as the number of "bits" here is somewhat quadratic (defs * uses)
* 5 `mut_bits_to_string`
* 2 `bit_str`
* 7 `ln_str`
  * similar to `bits_to_string` but for liveness instead of borrowck dataflow
* 1 `live_node_kind_to_string`
* 5 `path_lps`
* 2 `frag_lps`
* 1 `buf_str`
* 2 `resolve_type_vars_if_possible`
* 1 `type_to_string`
* 5 `ty_to_string`
* 1 `variant_names`
* 1 `.crate_name(krate)` (on a `TyCtxt`)
* 1 `.trait_has_default_impl(trait_def_id)` (on a `TyCtxt`)
* 1 `.nodes()` (on a `DepGraphQuery`)
* 1 `.use_count()` (on a `def_use::Info`)
* 1 `.def_count()` (on a `def_use::Info`)
* 1 `.def_count_not_including_drop()` (on a `def_use::Info`)
* 6 `.to_string(scx.tcx())` (on a `TransItem`)
  * this can quite likely be made into a `Display` impl
* 4 `.to_raw_string()` (on a `TransItem`)
  * what is even the point
* 2 `.escape_default()` (on a `String`)
  * really should just use `{:?}` instead of `{}`
* 3 `(0..depth).map(|_| ' ').collect::<String>()`
  * formatting has "non-constant width via argument" for this purpose IIRC
* 2 `dep_node.map_def(|&def_id| Some(tcx.def_path(def_id))).unwrap()`
* 2 of these (for `invoke` and `call` on `Builder`):
```rust
               args.iter()
                   .map(|&v| format!("{:?}", Value(v)))
                   .collect::<Vec<String>>()
                   .join(", ")
```
  * printing each `Value` is linear for unnamed LLVM values (to reconstruct the integer index)
    * `O(Values * Calls * Arguments)` is pretty bad (quadratic or cubic, depends on context)
* 3 entire nested blocks ([1](https://github.com/rust-lang/rust/blob/244f893ed704a60841d4615445d540a21a8d7722/src/librustc_borrowck/borrowck/mir/gather_moves.rs#L325-L335), [2](https://github.com/rust-lang/rust/blob/244f893ed704a60841d4615445d540a21a8d7722/src/librustc/infer/type_variable.rs#L252-L261), [3](https://github.com/rust-lang/rust/blob/244f893ed704a60841d4615445d540a21a8d7722/src/librustc/middle/liveness.rs#L807-L814))
  * probably want `log_enabled!`

</details>
<br>

For more than a few of them, I'm not sure what to do, short of some `Lazy(|| ...)` wrapper to get the value - of course we could build wrappers for every specific case, but we'd need more than a dozen.

**Comment by alexcrichton** [comment]
Ok well it sounds like then we don't want this PR right now.

**Comment by alexcrichton** [comment]
On second though, I don't [buy the slowdown argument](https://github.com/rust-lang/rust/pull/40686)

**Comment by alexcrichton** [comment]
My plan is to land https://github.com/rust-lang/rust/pull/40686 first, verifies it fixes the regression in build times, and then land this. This will regress compiler performance *if* `RUST_LOG` is set, but we already do that so it's taking a slowdown to a bigger slowdown. No one wants the slowdown in the first place so fast compiles will continue to not set `RUST_LOG`.

**Comment by eddyb** [comment]
@alexcrichton Isn't it still going to be terrible when just debug-assertions are enabled, no `RUST_LOG`?

**Comment by alexcrichton** [comment]
No, with debug assertions on and RUST_LOG missing then performance will be the same.

**Comment by eddyb** [comment]
@alexcrichton As in, crates.io `liblog` doesn't *always* evaluate the arguments, like we thought?

**Comment by alexcrichton** [comment]
[Correct](https://github.com/rust-lang-nursery/log/blob/25e349c7389ab63a9f5303a9a6183aa9d723b0a0/src/macros.rs#L26-L28). It only does that when it has to query the logger what the log level is.

**Comment by alexcrichton** [comment]
@bors: retry

* looks like an sccache timeout
https://github.com/rust-lang/rust/issues/40240

**Comment by arielb1** [comment]
- #40821
@bors retry

**Comment by arielb1** [comment]
-  #40821
    @bors retry

**Comment by arielb1** [comment]
-  #40821
    @bors retry

**Pull request merged**
