### PR TITLE
Remove aws cli install.

### PR DESCRIPTION
**Pull request by ehuss**
All runner images have the AWS CLI 2 installed, so there isn't a really strong reason to install our own version anymore.

The version we were installing was 1.27.122. The runner images currently have 2.11.x (the exact version varies by image).

I do not have the means to really test if the new version has any issues. I looked at all the `aws` commands, and none of them seem to be doing anything unusual. The page at https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html contains a list of all the breaking changes, and I didn't see anything that looked important.

### CODE REVIEW

**Comment by ehuss** [comment]
The best I can tell from searching around is that error is generated because the v2 CLI now uses the IMDS service to determine the region, but for some reason it doesn't work on GitHub Actions. The solution is to specify the region so that it does not have to go discover it. 

An alternate solution is possibly to set `AWS_EC2_METADATA_DISABLED`, which disables the IMDS lookup. I believe it still initially contacts the "global" region and then gets redirected to the correct region. Setting the region avoids that global lookup and redirect.  I can try that solution as an alternate if you'd prefer to not hard-code the region.

Also, let me know if you would like the ability to set the region separately for artifacts versus caches.

From what I can tell, the buckets currently used in CI are rust-lang-ci-sccache2, rust-lang-ci-mirrors, and rust-lang-ci2.

I haven't tested on GitHub Actions if this actually solves the problem. I can do some testing on my own account if you would prefer to not blindly try things.

**Comment by pietroalbini** [comment]
Setting the AWS region should be enough.

@bors r+ rollup=never

**Comment by ehuss** [comment]
I'm not too familiar with the self-hosted runner. I forgot that it has its own environment. Is there a separate place where its environment is defined? Or should the CI script just manually install the `aws` cli for that runner?

**Comment by pietroalbini** [comment]
The image is defined in https://github.com/rust-lang/gha-self-hosted/tree/master/images/ubuntu/scripts.

I'd add a script in https://github.com/rust-lang/gha-self-hosted/tree/master/images/ubuntu/scripts to install AWS CLI into the image, and then register it in https://github.com/rust-lang/gha-self-hosted/blob/f9bc6794b8b27a22c7805c60b5ee98d9e79ce604/images/ubuntu/ubuntu.json#L30-L46.

**Comment by ehuss** [comment]
Thanks for the pointers!  I have posted https://github.com/rust-lang/gha-self-hosted/pull/18.

**Comment by Mark-Simulacrum** [comment]
@bors retry

Rebuilt the self hosted image with the patch above, so hopefully this should merge now.

**Pull request merged**
