### PR TITLE
Stable backports for 1.43.1

### PR DESCRIPTION
**Pull request by cuviper**
- Update openssl-src to 1.1.1g #71430
- Update stdarch submodule #71495

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by cuviper** [comment]
@Amanieu -- using the same `stdarch` commit as #71495 brings a few other things to stable too, that only reached beta so far. I was able to shim `llvm_asm!` to plain `asm!`, but please review whether the rest is safe for stable backport. Otherwise, we'll need a separate `stdarch` branch to use here.

**Comment by Amanieu** [comment]
The other commits only affect ARM instrinsics which are all unstable. So I think it should be safe to backport.

**Comment by Mark-Simulacrum** [comment]
I agree that the stdarch backport seems fine as-is.

I'm going to hold off on approving until Sunday to give some time for feedback (in case someone thinks of something else to include).

**Comment by Mark-Simulacrum** [comment]
@sfackler nominated https://github.com/rust-lang/cargo/issues/8151 (PR: https://github.com/rust-lang/cargo/pull/8175) for backport as well, which is waiting on Cargo team approval.

**Comment by cuviper** [comment]
OK, this PR should be open to maintainer pushes, if you want to add that.

**Comment by Mark-Simulacrum** [comment]
Yeah, I'd like someone from cargo team to sign off and then I'll do so before approving.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/71868, wasn't able to push to this branch for whatever reason.

**Pull request closed without merging**
