### PR TITLE
CTFE: support assert_zero_valid and assert_uninit_valid

### PR DESCRIPTION
**Pull request by RalfJung**
This ensures the implementation of all three type-based assert_ intrinsics remains consistent in Miri.

`assert_inhabited` recently got stabilized in https://github.com/rust-lang/rust/pull/90896 (meaning stable `const fn` can call it), so do the same with these other intrinsics.

Cc @rust-lang/wg-const-eval

### CODE REVIEW

**Comment by oli-obk** [comment]
r? @oli-obk 

r=me with the intrinsics made const-unstable.

If you want them to be stable immediately, then at least one caller should be stable, too and we should then nominate it for libs-api

**Comment by RalfJung** [comment]
> If you want them to be stable immediately, then at least one caller should be stable, too

Oh, I did not know of this policy.
If they remain unstable they need a separate feature gate which seems kind of silly... const-"stability" of intrinsics is a somewhat strange concept anyway and I can't see a good reason for why assert_zero_valid should be unstable while assert_inhabited is stable. (I almost think of these 3 intrinsics as one intrinsic with a "mode" argument, except having them as separate intrinsics is a lot easier to implement.)

**Comment by oli-obk** [comment]
Just use none for the tracking issue an invent a feature gate name.

Const stabilizing any intrinsic needs lang team sign off as stated at the top of the doc. Even if it is trivial in this case, as we already have an intrinsic that is basically the same. Maybe someone from t-lang can just merge this without an fcp?

r? rust-lang/lang

**Comment by RalfJung** [comment]
Well fair, I can also make them unstable.

(That "r?" does not seem to have done anything.)

**Comment by Mark-Simulacrum** [comment]
Nominating for T-lang discussion (which seems better than r?, regardless). But I'm not clear on the ask being presented, so it may be helpful for a more extensive summary to be put in the description.

It sounds like this is just intending to enable usage of these two intrinsics in const code, which on the surface seems pretty harmless, but if there are reasons to *not* to do this, it would be helpful to call those out explicitly.

**Comment by RalfJung** [comment]
Ah this is not worth the bureaucracy.^^ I will just make them unstable. Having the implementations all in rustc (rather than spread across rustc and Miri) is still worth it.

**Pull request merged**
