### PR TITLE
Remove duplicate notes from error on inter-crate ambiguous impl of traits

### LINKED ISSUE #99092: Duplicate 'upstream crates may add a new impl of trait' notes on inter-crate ambiguous impl of traits
Given the following code: 

```rust
struct S;

impl From<()> for S {
    fn from(x: ()) -> Self {
        S
    }
}

impl<I> From<I> for S
where
    I: Iterator<Item = ()>,
{
    fn from(x: I) -> Self {
        S
    }
}

fn main() {}
```

The current output is:

```
error[E0119]: conflicting implementations of trait `std::convert::From<()>` for type `S`
  --> foo.rs:9:1
   |
3  |   impl From<()> for S {
   |   ------------------- first implementation here
...
9  | / impl<I> From<I> for S
10 | | where
11 | |     I: Iterator<Item = ()>,
12 | | {
...  |
15 | |     }
16 | | }
   | |_^ conflicting implementation for `S`
   |
   = note: upstream crates may add a new impl of trait `std::iter::Iterator` for type `()` in future versions
   = note: upstream crates may add a new impl of trait `std::iter::Iterator` for type `()` in future versions

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
```

Ideally the output should look like:

```
error[E0119]: conflicting implementations of trait `std::convert::From<()>` for type `S`
  --> foo.rs:9:1
   |
3  |   impl From<()> for S {
   |   ------------------- first implementation here
...
9  | / impl<I> From<I> for S
10 | | where
11 | |     I: Iterator<Item = ()>,
12 | | {
...  |
15 | |     }
16 | | }
   | |_^ conflicting implementation for `S`
   |
   = note: upstream crates may add a new impl of trait `std::iter::Iterator` for type `()` in future versions

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
```

### PR DESCRIPTION
**Pull request by rhysd**
Fixes #99092

### CODE REVIEW

**Comment by compiler-errors** [comment]
The change looks good! Can you move the UI test somewhere different than `src/test/ui/issues`? There is probably a better directory for it to live.

r? @compiler-errors

**Comment by rhysd** [comment]
@compiler-errors Thank you for taking a look. I moved test to `src/test/ui/inter-crate-ambiguity-causes-notes.{rs,stderr}`.

**Comment by rhysd** [comment]
@compiler-errors CI passed and I confirmed all UI tests passed on my local machine. Would you review this patch again?

**Comment by compiler-errors** [comment]
This looks good to me. It's typically better to add new unit tests to subdirectories of `src/test/ui` instead of the top directory itself, so can you move that test you added to `src/test/ui/coherence`? Then I can approve. Thanks again.

**Comment by rhysd** [comment]
Thanks for your advice. I moved the test case again.

**Comment by compiler-errors** [comment]
Thanks!

@bors r+

**Pull request merged**
