### PR TITLE
fix typo in iterator.rs

### PR DESCRIPTION
**Pull request by Riahiamirreza**
I think there's a small typo in docs, just wanted to fix it.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Hi, thank you for the PR! This is not a type, what it means is that out of all the methods in the standard library, `collect` belongs to those that are more powerful than many other methods which are less powerful. I don't think "most" is more appropriate, but I do agree that the wording is not great. What do you think about just deleting this sentence?
The previous sentence is also not great, the word "iterable" is often used to refer to implementors of `IntoIterator` (which is called `Iterable` in Java, for example), but `collect` takes an iterator. Maybe that sentence could be deleted too, but I don't think it's entirely useless either. What do you think?

**Comment by saethlin** [comment]
> This is not a type

_cough cough_

**Comment by JohnCSimon** [comment]
@Riahiamirreza 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Comment by He1pa** [comment]
> Hi, thank you for the PR! This is not a type, what it means is that out of all the methods in the standard library, `collect` belongs to those that are more powerful than many other methods which are less powerful. I don't think "most" is more appropriate, but I do agree that the wording is not great. What do you think about just deleting this sentence? The previous sentence is also not great, the word "iterable" is often used to refer to implementors of `IntoIterator` (which is called `Iterable` in Java, for example), but `collect` takes an iterator. Maybe that sentence could be deleted too, but I don't think it's entirely useless either. What do you think?

How about deleting the second sentence and changing the first sentence to `collect() can take any iterator and turn it into the relevant collection.`?

**Pull request closed without merging**
