### PR TITLE
Fix #98260

### LINKED ISSUE #98260: Cycle detected error instead of invalid function signature on trait
Given the following code: [Link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e3b9befe19a57230e9fc9f93c005bcf4)

```rust
fn main() {}

trait A {
    fn a(aa: B) -> Result<_, B> {
        Ok(())
    }
}

enum B {}
```

The current output is:

```
   Compiling s1 v0.1.0 (/Users/forest/Documents/test/s1)
error[E0391]: cycle detected when computing function signature of `A::a`
 --> src/main.rs:3:5
  |
3 |     fn a(aa: B) -> Result<_, B> {
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
note: ...which requires type-checking `A::a`...
 --> src/main.rs:3:5
  |
3 |     fn a(aa: B) -> Result<_, B> {
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing the variances of `B`...
 --> src/main.rs:8:1
  |
8 | enum B {}
  | ^^^^^^
  = note: ...which requires computing the variances for items in this crate...
  = note: ...which again requires computing function signature of `A::a`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> src/main.rs:1:1
  |
1 | fn main() {}
  | ^^^^^^^^^

For more information about this error, try `rustc --explain E0391`.
error: could not compile `s1` due to previous error
```

I expected the compiler to let me know that function signature was wrong with the `_` in `Result<_, B>`. Once I changed this, it compiled fine.

### PR DESCRIPTION
**Pull request by yanchen4791**
Fixes https://github.com/rust-lang/rust/issues/98260

### CODE REVIEW

**Comment by compiler-errors** [comment]
@yanchen4791 this needs a test at least

**Comment by yanchen4791** [comment]
Please note that the fix is for https://github.com/rust-lang/rust/issues/98260 (not 98062).

**Comment by spastorino** [comment]
And you would need to `rustfmt` the changed file.

**Pull request merged**
