### PR TITLE
Make it an error to not declare used features

### PR DESCRIPTION
**Pull request by brson**
Also, on the beta/stable channels, it is an error to write `feature`.

I had to add two hacks to rustdoc to make the doctests support crate attributes correctly, and to avoid injecting 'extern crate' items that trip the unstable feature error for doctests inside the std facade. The latter of these adds a crate-level `#[doc(test(no_inject_crate))]` attribute, which is pretty ugly.

This is very prone to bitrot and will be hard to land.

### CODE REVIEW

**Comment by brson** [comment]
Oh, still doesn't quite pass.

**Comment by brson** [comment]
Well, I hit an ugly bug because of the hack I put in to make crate attributes work in doc tests. The rustdoc test runner wants to put 'extern crate' and 'main'  functions into the source, and it needs to do that after any crate attributes. To avoid putting explicit main functions into every test that declares a feature I made the test runner try to figure out the parts of the example that are outer attributes, and make them crate attributes.

Unfortunately, this appears in the book:

```
#![doc(html_logo_url = "http://www.rust-lang.org/logos/rust-logo-128x128-blk-v2.png",
       html_favicon_url = "http://www.rust-lang.org/favicon.ico",
       html_root_url = "http://doc.rust-lang.org/")];
```

And rustdoc now thinks it should turn it into something like:

```
#![doc(html_logo_url = "http://www.rust-lang.org/logos/rust-logo-128x128-blk-v2.png",
fn main() {
       html_favicon_url = "http://www.rust-lang.org/favicon.ico",
       html_root_url = "http://doc.rust-lang.org/")];
}
```

**Comment by brson** [comment]
Maybe I could just have rustdoc treat *only* `#![feature` specially as a hack to get this done.

**Comment by brson** [comment]
I've run into another major problem: https://github.com/rust-lang/rust/issues/23616. This isn't as close to ready as I thought.

**Comment by brson** [comment]
This has passed tests locally.

**Comment by aturon** [comment]
I had a couple minor nits but basically am OK trying to get this landed (due to the bitrot issues).

I do worry a bit about adding yet more ways that tests can pedantically fail, which can be very annoying...

**Comment by brson** [comment]
Rebased again.

**Comment by brson** [comment]
Doesn't pass on mac/win yet.

**Comment by alexcrichton** [comment]
I'm putting the rollup (#23654) ahead of this b/c it includes this inside of it. (just FYI)

**Comment by alexcrichton** [comment]
Rolled into #23654

**Pull request closed without merging**
