### PR TITLE
Implement `FromIterator` for `(impl Default + Extend, impl Default + Extend)`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Similarly to how https://github.com/rust-lang/rust/pull/85835 implemented `Extend` for `(impl Extend, impl Extend)`:
```rust
impl<A, B, AE, BE> FromIterator<(AE, BE)> for (A, B)
where
    A: Default + Extend<AE>,
    B: Default + Extend<BE>,
{ ... }
```

### CODE REVIEW

**Comment by cuviper** [comment]
As I mentioned in https://github.com/rust-lang/rust/pull/85835#issuecomment-851824207, rayon has a parallel version of this [here](https://docs.rs/rayon/latest/rayon/iter/trait.FromParallelIterator.html#impl-FromParallelIterator%3C(A%2C%20B)%3E-for-(FromA%2C%20FromB)), but it's based on inner `FromParallelIterator` rather than `Default + ParallelExtend`. I don't think the API allows splitting on `FromIterator` here though.

A nice benefit is that it composes well, like collecting `Option<(A, B)>` or `Result<(A, B), E>`, or nested `((A, B), (C, D))`.

**Comment by workingjubilee** [comment]
r? libs-api

Needs FCP.

**Comment by the8472** [comment]
This looks a lot like `iterator.unzip`. Could it just delegate to that impl?

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting today. We're happy to add this, but it should include a doc comment with an example.

@rfcbot fcp merge

**Comment by WaffleLapkin** [comment]
@the8472 somehow I've never seen `Iterator::unzip`, even though it's apparently it existed since forever O_o

Yes, this should be able to use `.unzip`. Tbh I'm not even sure how useful this is given a method exists...

**Comment by cuviper** [comment]
It still composes better than `unzip` alone, as I mentioned earlier. For example, you can `.collect::<Result<(A, B), E>>()` to unzip into types `A` and `B` while short-circuiting on error `E`.

**Comment by WaffleLapkin** [comment]
Ah, right, makes sense. I'll clean up the PR once the FCP finishes.

**Comment by cuviper** [comment]
@Amanieu was it an accident that you removed FCP labels? It looks like you might have RMW-raced with rfcbot.

**Comment by Amanieu** [comment]
Oops, I've added them back.

**Comment by BurntSushi** [comment]
@rfcbot concern doc-example

I'm just registering this to make sure this impl gets some docs _with an example_ before it's officially stabilized.

**Comment by WaffleLapkin** [comment]
@Amanieu @BurntSushi I've pushed a commit with documentation, does it look good? Does it resolve the concern?

**Comment by BurntSushi** [comment]
@rfcbot resolve doc-example

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
