### PR TITLE
[WIP] Switch rustc allocator to mimalloc

### PR DESCRIPTION
**Pull request by gnzlbg**
[Here](https://www.microsoft.com/en-us/research/publication/mimalloc-free-list-sharding-in-action/), strong claims are made about the performance of mimalloc against pretty much every other widely-used allocator.

This PR is the smallest-diff that hopefully allows us to do a perf run of rustc with mimalloc. 

Independently of the outcome, this is not intended to be merged upstream - hence tagged as WIP to prevent that.

r? @Zoxc

### CODE REVIEW

**Comment by gnzlbg** [comment]
@zoxc I would prefer to only run the tests of this PR on the target that is used by perf. Do you know which one is it? (is it x86_64-unknown-linux-gnu with builtin LLVM ?)

**Comment by Zoxc** [comment]
I'm not sure what you mean by that statement. I don't think try builds have much in the way of tests anyway.

I tried mimalloc in https://github.com/rust-lang/rust/pull/62073, but I just hooked the Rust allocation functions so LLVM was unaffected. Does this hook C functions too?

**Comment by Mark-Simulacrum** [comment]
Try builds do not have tests.

@bors try

**Comment by gnzlbg** [comment]
> Does this hook C functions too?

That's a good question. I'll do a full build and use `nm` to find out. `mimalloc` has some build options to override the malloc symbols. I'll try setting that up as well.

**Comment by Zoxc** [comment]
@rust-timer build f98cbb8400c7fe3cb8d9bf87130394c2239b7d88

**Comment by gnzlbg** [comment]
Can we abort ? I found a better way to statically link this, that overrides `malloc` completely. Should also do so for LLVM.

**Comment by mati865** [comment]
The interesting thing here is `wall-time` and it regressed very bad: https://perf.rust-lang.org/compare.html?start=8c6fb028ca887dff9ec2fe0a90398b6d5bf5fb45&end=f98cbb8400c7fe3cb8d9bf87130394c2239b7d88&stat=wall-time

**Comment by gnzlbg** [comment]
So that looks like this change managed to enable mimalloc properly. I'm going to push a commit that updates the mimalloc-sys version, since there are a couple of things enabled in its `--release` builds that shouldn't be part of it.

**Comment by gnzlbg** [comment]
So I've pushed a new commit that uses `mimalloc-sys` 0.1.4, which statically links mimalloc, and overrides all `malloc` symbols with the `mimalloc` ones. This should work for LLVM as well.

**Comment by gnzlbg** [comment]
Forgot to update the lock-file, fixed.

**Comment by mati865** [comment]
According to https://docs.rs/mimalloc-sys/0.1.4/mimalloc_sys/ you have to use it like `mimalloc_sys::mi_calloc` instead of `mimalloc_sys::calloc`. There is another issue, `aligned_alloc` and `posix_memalign` are not available at all.

**Comment by gnzlbg** [comment]
> According to https://docs.rs/mimalloc-sys/0.1.4/mimalloc_sys/ you have to use it like mimalloc_sys::mi_calloc instead of mimalloc_sys::calloc

Done.

> There is another issue, aligned_alloc and posix_memalign are not available at all.

They aren't exposed in the bindings, but they are part of the static library when `override` is enabled. They both call `mi_malloc_aligned`, see: https://github.com/microsoft/mimalloc/blob/1125271c2756ee1db1303918816fea35e08b3405/src/alloc-override.c#L138

**Comment by gnzlbg** [comment]
I've pushed `mimalloc-sys` 0.1.5 which exports the standard C and POSIX definitions when the override is enabled.

**Comment by mati865** [comment]
Ouch:
`(signal: 11, SIGSEGV: invalid memory reference)`

**Comment by gnzlbg** [comment]
@mati865 a couple of questions. 

That happens when building stage1, so I suppose the stage0 compiler built succesfully with mimalloc, is that correct ? 

Also, that happens after building stage1 for a while, right ?

Do you know whether stage0 is built in --release or debug mode ? Depending on how mimalloc is configured, it can enable some checks that might help.

**Comment by mati865** [comment]
> That happens when building stage1, so I suppose the stage0 compiler built succesfully with mimalloc, is that correct ?

Stage0 is linked to mimalloc but it wasn't really used yet. Crash in stage1 is when mimalloc is used.

> Also, that happens after building stage1 for a while, right ?

Yeah, standard builder ran for 107 seconds and alternative failed after 25 seconds.

> Do you know whether stage0 is built in --release or debug mode ? Depending on how mimalloc is configured, it can enable some checks that might help.

AFAIK it's neither debug or release. I can only guess it's built with both optimisations and some debug options enabled. You can see [here](https://github.com/rust-lang/rust/blob/b43eb4235ac43c822d903ad26ed806f34cc1a14a/src/ci/run.sh#L50-L59) about enabled debug options.
@Mark-Simulacrum surely knows better than I do.

**Comment by joelpalmer** [comment]
Ping from Triage: any updates on this PR @gnzlbg?

**Comment by gnzlbg** [comment]
I'm closing this until we find the root of the crashes. It's unclear at this point whether this is a mimalloc or a rustc issue.

**Comment by ArniDagur** [comment]
@gnzlbg I managed to reproduce the crash: I just needed to put "--set rust.jemalloc" in the `./configure` arguments. This script:
```bash
#!/bin/bash

# Clean up from previous build
rm -rf build

# Configuration which is always enabled
export RUST_RELEASE_CHANNEL=nightly
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --enable-sccache"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --disable-manage-submodules"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --enable-locked-deps"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --enable-cargo-native-static"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --set rust.codegen-units-std=1"

# Deploy configuration
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --release-channel=$RUST_RELEASE_CHANNEL"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --enable-llvm-static-stdcpp"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --set rust.remap-debuginfo"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --debuginfo-level-std=1"

RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --enable-llvm-assertions"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --set rust.verify-llvm-ir"

RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --enable-debug-assertions"
RUST_CONFIGURE_ARGS="$RUST_CONFIGURE_ARGS --set rust.jemalloc"

# Configure and make
./configure $RUST_CONFIGURE_ARGS
make -j $(nproc)
```
Produces this:
```
mimalloc: warning: mprotect error: start: 0x0x42a0beff000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf0f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf1f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf2f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf3f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf4f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf5f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf6f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf7f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf8f000, csize: 0x1000, err: -1
mimalloc: warning: mprotect error: start: 0x0x42a0bf9f000, csize: 0x1000, err: -1
error: Could not compile `rustc`.

Caused by:
  process didn't exit successfully: `/home/arni/src/rust-mimalloc/build/bootstrap/debug/rustc --edition=2018 --crate-name rustc src/librustc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C metadata=f648942e8bb9ba69 -C extra-filename=-f648942e8bb9ba69 --out-dir /home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps --extern arena=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libarena-ebc900195d83aa4d.rmeta --extern backtrace=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libbacktrace-f722349a2b3cfdff.rmeta --extern bitflags=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libbitflags-58e0dbae211d255d.rmeta --extern byteorder=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libbyteorder-c31e835416d3ff9d.rmeta --extern chalk_engine=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libchalk_engine-8c24322dc01837b3.rmeta --extern fmt_macros=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libfmt_macros-8515eb6d1fcab541.rmeta --extern graphviz=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libgraphviz-70da08ae09e4c746.rmeta --extern jobserver=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libjobserver-f8e516e6a924bac0.rmeta --extern lazy_static=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/liblazy_static-a1357debc52c144b.rmeta --extern log=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/liblog-09b8d7c33ca043bf.rmeta --extern measureme=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libmeasureme-04821d071e81439f.rmeta --extern num_cpus=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libnum_cpus-07a7b672ea534d8c.rmeta --extern parking_lot=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libparking_lot-0e0dd756a727d78f.rmeta --extern polonius_engine=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libpolonius_engine-459cd13d7ed8d19e.rmeta --extern rustc_rayon=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_rayon-74e7aa8a5023fbd2.rmeta --extern rustc_rayon_core=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_rayon_core-114a2a36aae6da4c.rmeta --extern rustc_apfloat=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_apfloat-fac7e66c915effcc.rmeta --extern rustc_data_structures=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_data_structures-5b591454e16cc41e.rmeta --extern errors=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_errors-1640a4e8e73821c6.rmeta --extern rustc_fs_util=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_fs_util-055a87fca5033c2d.rmeta --extern rustc_macros=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps/librustc_macros-09874915f7420f3f.so --extern rustc_target=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_target-98feb11063278230.rmeta --extern scoped_tls=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libscoped_tls-bbe59bc685d5bfcc.rmeta --extern rustc_serialize=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libserialize-eb2cf79e1d097189.rmeta --extern smallvec=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libsmallvec-29b1fb24aa27bec5.rmeta --extern syntax=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libsyntax-f69f9c56af06e538.rmeta --extern syntax_pos=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libsyntax_pos-cb972f90722f72c8.rmeta -C target-cpu=native -Zbinary-dep-depinfo --cfg always_verify_llvm_ir -L native=/home/arni/src/rust-mimalloc/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/build/backtrace-sys-00a11e73bbe3a3bf/out` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
mimalloc: warning: possibly trying to mi_free a pointer that does not point to a valid heap region: 0x0x420fc402000
(this may still be a valid very large allocation (over 64MiB))
mimalloc: warning: (yes, the previous pointer 0x0x420fc402000 was valid after all)
^C  Building [====================================================>  ] 155/158: rustc_mir
Build completed unsuccessfully in 0:23:26
make: *** [Makefile:18: all] Error 1
```

**Pull request closed without merging**
