### PR TITLE
Destabilize format_args! internals

### LINKED ISSUE #22953: Destabilise the internals of `format_args!`
https://github.com/rust-lang/rust/pull/22899 should mean that contents of `core::fmt::rt::v1` used by `format_args!` can probably be made `#[unstable]`.

cc @eddyb

### PR DESCRIPTION
**Pull request by rprichard**
Fixes #22953.

### CODE REVIEW

**Comment by rprichard** [comment]
cc @huonw

**Comment by alexcrichton** [comment]
Nice! r=me with a rebase

**Comment by rprichard** [comment]
@alexcrichton It's rebased.

**Pull request merged**
