### PR TITLE
Include inline attribute in rendered docs

### LINKED ISSUE #52182: Show "#[inline]" for every items in rustdoc
For now it seems to not be displayed on methods.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #52182.

Screenshot:

screen shot 2018-09-06 at 23 27 30

r? @QuietMisdreavus

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Shouldn't this remain an implementation detail instead of public documentation? I can imagine many libraries to become much noisier with this.

**Comment by GuillaumeGomez** [comment]
What do you have in mind more precisely? I have to admit that I don't like much the current rendering but since it was a feature ask a few times already...

**Comment by jonas-schievink** [comment]
I wouldn't expect `#[inline]` to show up in docs at all, because all it does is enabling more optimizations, unlike the other attributes in that list which change something about the ABI.

Also I think the `[+] [+]` rendering looks weird. Maybe there should just be the current, single `[+]` that displays the docs *and* attributes when clicked. Or only display `[+] Expand attributes` when the docs are already displayed. This would also save vertical space since the functions fit on single lines again.

**Comment by QuietMisdreavus** [comment]
I'm also skittish about showing `#[inline]` in the first place, so i'm going to pull in @rust-lang/docs for a second opinion. (We can maybe pull in libs-team if we want to pull in even more people, but i'll keep the pings to docs for now.)

I also agree with @jonas-schievink about the `[+] [+]` display. I would prefer the suggestion where the attributes show up at the same time the docs do (so there's only ever one fold/unfold button) but that does complicate things a lot. Otherwise i'm not sure how to deal with the problem of having multiple toggles right next to each other.

**Comment by Aaronepower** [comment]
Tirage; @QuietMisdreavus What's the current status of the review of this PR?

**Comment by GuillaumeGomez** [comment]
Still debating, but slowly.

**Comment by TimNN** [comment]
Ping from triage @QuietMisdreavus / @GuillaumeGomez: What is the status of this PR?

**Comment by GuillaumeGomez** [comment]
Haven't debated yet...

**Comment by QuietMisdreavus** [comment]
It's been a while since i brought it up on Discord, but i think the general reaction from @rust-lang/docs was noncommittal, but slightly against. (Though that "slightly against" might have been my own vote.) Should i try to bring it up again?

**Comment by QuietMisdreavus** [comment]
Ah, i found the logs:

```
[8:54 AM] QuietMisdreavus: question for docs folk: do we want to show #[inline] attributes on functions? https://github.com/rust-lang/rust/pull/54014
[8:54 AM] QuietMisdreavus: i'm leaning toward "no", but weakly enough that i'm seeking other opinions
[9:10 AM] steveklabnik: Hmm
[9:35 AM] imperio: @QuietMisdreavus just to bring into the debate: some other info: some other attributes are there
[9:39 AM] QuietMisdreavus: @imperio right, but those other attribute affect how people use the function in question
[9:40 AM] QuietMisdreavus: imo, #[inline] is an optimization that people generally don't care about
[9:46 AM] imperio: hum ok
[10:49 AM] steveklabnik: i think part of this question is "is removing #[inline] a breaking change?
[10:49 AM] steveklabnik: that is, is it part of the API guarantee?
[10:49 AM] steveklabnik: if it is, it should be documented
[10:50 AM] steveklabnik: if it's not, that's a good argument to not document it
[11:18 AM] imperio: @steveklabnik then I suppose it is
[11:18 AM] QuietMisdreavus: i think the answer depends on who you ask
[11:19 AM] QuietMisdreavus: iirc the compiler does a fair amount of inlining without needing the attribute, but i dunno how much that happens across crates
[11:20 AM] steveklabnik: yeah
[11:20 AM] steveklabnik: we don't have this as part of the stability rfcs, i don't think
[11:20 AM] steveklabnik: :/
[11:20 AM] steveklabnik: either way
[3:16 PM] imperio: @steveklabnik @QuietMisdreavus should we ask to other rust teams? They might have stronger opinions on this
[3:16 PM] imperio: if we can't decide it'll make things simpler :smile:
[3:46 PM] steveklabnik: yeah, most likely, maybe an internals post?
[4:20 PM] imperio: sounds like a good idea :smiley:
[5:23 PM] scottmcm: I don't think performance is ever part of a stability guarantee.  New versions can absolutely regress or improve performance, so I don't think that #[inline] is relevant
[5:23 PM] scottmcm: especially since you could always just make everything #[inline] as a thin wrapper that delegates to something expensive and non-inline underneath
[5:24 PM] scottmcm: I wouldn't want people to start getting bugs on their creates like "I was looking at the docs, and it looks like you only marked 4 of the 5 methods as inline"
[5:25 PM] scottmcm: (Also, if inline needs to be in the docs, things like cold also should be.)
[5:35 PM] Havvy: IMO, if it's doc-worthy that it's inlined, it should be in the prose.
```

Seems to me that the general reaction was against, but i don't know whether that internals post ever got made.

**Comment by GuillaumeGomez** [comment]
I don't think we can call this a decision. 🤣

**Comment by TimNN** [comment]
Ping from triage! I'll mark this PR as waiting-on-team.

**Comment by QuietMisdreavus** [comment]
Hi @rust-lang/docs! Let's revisit this PR. To bring everyone up to speed, the question at hand is **should rustdoc print the `#[inline]` attribute in crate docs?**

The basic arguments, so far, have been:

* If we consider `#[inline]` to be part of an API guarantee (i.e. if removing it is a breaking change), then yes. (This just changes the question to whether we consider `#[inline]` to be part of a crate's API, though...)
* `#[inline]` is effectively an implementation detail, and doesn't share the same concerns as the other attributes we already show. (For completeness, the other attributes we show are `#[export_name]`, `#[lang]`, `#[link_section]`, `#[must_use]`, `#[no_mangle]`, `#[repr]`, `#[unsafe_destructor_blind_to_params]`, and `#[non_exhaustive]`.)

I'm not sure enough discussion has happened to warrant a full FCP, but i would like some kind of vote to happen. My personal response is "no", but since the PR was opened in the first place i wonder how many people think it's useful enough to include.

**Comment by frewsxcv** [comment]
> If we consider `#[inline]` to be part of an API guarantee (i.e. if removing it is a breaking change), then yes. (This just changes the question to whether we consider `#[inline]` to be part of a crate's API, though...)

Has the libs team made a decision about this?

**Comment by GuillaumeGomez** [comment]
No.

**Comment by Dylan-DPC** [comment]
@rust-lang/docs any update on this?

**Comment by frewsxcv** [comment]
My (weakly held) position is that we shouldn't show the `#[inline]` attribute at all in generated documentation. It seems easy enough to determine if a function is inline in the source via the `[src]` hyperlink. It seems closer to an implementation detail than something worth calling out to all users on all docs pages. _But_, if the libs team did deem it to be an API guarantee, then I think I'd lean the the other way.

**Comment by QuietMisdreavus** [comment]
I generally agree with @frewsxcv, so we should bring in @rust-lang/libs to make sure they see it. See the previous comment for context.

**Comment by dtolnay** [comment]
I would be against. What is one situation in which someone would need to check whether a function is inline? If the only two are curiosity and performance debugging, I would prefer to leave those to the "[src]" link because chances are they would also be curious about the implementation or need to understand the implementation in order to understand the performance.

**Comment by sfackler** [comment]
`#[inline]` is an implementation detail. Changing it is *definitely* not a breaking change.

**Comment by frewsxcv** [comment]
Considering the recent comments, what do people think about removing display of `#[inline]` in non-src docs entirely? Could either pivot this PR or open a new one...

**Comment by GuillaumeGomez** [comment]
I can remove it or we can merge it. Either way, please someone give a definitive answer. :)

**Comment by frewsxcv** [comment]
Are there any arguments in favor of it?

**Comment by Centril** [comment]
For the aforementioned (https://github.com/rust-lang/rust/pull/54014#issuecomment-443808775, https://github.com/rust-lang/rust/pull/54014#issuecomment-443809617) reasons, I would remove it; -- Not up to me tho. :)

**Comment by GuillaumeGomez** [comment]
I agree with not putting `#[inline]` attribute.

**Comment by QuietMisdreavus** [comment]
+1 for removing the `#[inline]` attribute. Are there places where we emit it in generated docs? I thought the only attributes we printed were the ones in the list this PR is modifying.

**Comment by QuietMisdreavus** [comment]
Looks like all the comments for a while are either ambivalent or against it. I'm going to close this PR.

**Pull request closed without merging**
