### PR TITLE
[beta] Bump prerelease version

### PR DESCRIPTION
**Pull request by brson**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Timeout? Not sure what did it though..

@bors retry

```
[01:38:36] test io/error.rs - io::error::Error::into_inner (line 448) ... ok
[01:38:36] test io/error.rs - io::error::Error::last_os_error (line 261) ... ok
[01:38:37] test io/error.rs - io::error::Error::new (line 228) ... ok
[01:38:37] test io/error.rs - io::error::Error::raw_os_error (line 309) ... ok
[01:38:37] test io/error.rs - io::error::Result (line 36) ... ok


No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by Mark-Simulacrum** [comment]
@bors retry
  - temporary (I hope) appveyor failure due to GCE migration for network maintenance: https://appveyor.statuspage.io/incidents/2g5jnq5cy1g1

**Comment by Mark-Simulacrum** [comment]
@bors retry

Network failure? #40474...?

```
[02:59:53] Deploying using S3 provider
[02:59:53] Uploading artifact "d124caef49d2db8c05a948ecc50eab49bf682f71/cargo-beta-i686-pc-windows-msvc.tar.gz" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/d124caef49d2db8c05a948ecc50eab49bf682f71/cargo-beta-i686-pc-windows-msvc.tar.gz"
[02:59:54] Uploading artifact "d124caef49d2db8c05a948ecc50eab49bf682f71/rls-beta-i686-pc-windows-msvc.tar.gz" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/d124caef49d2db8c05a948ecc50eab49bf682f71/rls-beta-i686-pc-windows-msvc.tar.gz"
[02:59:54] Uploading artifact "d124caef49d2db8c05a948ecc50eab49bf682f71/rust-analysis-beta-i586-pc-windows-msvc.tar.gz" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/d124caef49d2db8c05a948ecc50eab49bf682f71/rust-analysis-beta-i586-pc-windows-msvc.tar.gz"
[02:59:54] Uploading artifact "d124caef49d2db8c05a948ecc50eab49bf682f71/rust-analysis-beta-i686-pc-windows-msvc.tar.gz" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/d124caef49d2db8c05a948ecc50eab49bf682f71/rust-analysis-beta-i686-pc-windows-msvc.tar.gz"
[02:59:55] Uploading artifact "d124caef49d2db8c05a948ecc50eab49bf682f71/rust-beta-i686-pc-windows-msvc.exe" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/d124caef49d2db8c05a948ecc50eab49bf682f71/rust-beta-i686-pc-windows-msvc.exe"
[02:59:57] Uploading artifact "d124caef49d2db8c05a948ecc50eab49bf682f71/rust-beta-i686-pc-windows-msvc.msi" (0 bytes) to S3 bucket "rust-lang-ci" as "rustc-builds/d124caef49d2db8c05a948ecc50eab49bf682f71/rust-beta-i686-pc-windows-msvc.msi"
```

**Comment by kennytm** [comment]
@Mark-Simulacrum It's just a regular build timeout after 3 hours.

**Comment by Mark-Simulacrum** [comment]
Sort of. We usually go until `2:59:59` if that's the case; the artifacts are also all uploading 0 bytes, which is odd.

**Pull request merged**
