### PR TITLE
[MIR] improve operand lifetimes

### PR DESCRIPTION
**Pull request by arielb1**
r? @eddyb

### CODE REVIEW

**Comment by arielb1** [comment]
cc @nagisa

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
@bors r-
```
/checkout/src/test/codegen/lifetime_start_end.rs:39:11: error: expected string not found in input
// CHECK: [[E_b:%[0-9]+]] = bitcast %"core::option::Option<i32>"** %b to i8*
          ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/lifetime_start_end.ll:37:2: note: scanning from here
 %9 = bitcast i32* %c to i8*
 ^
```

**Comment by frewsxcv** [comment]
Could this failure be related? https://github.com/rust-lang/rust/pull/40211#issuecomment-283725417

**Comment by frewsxcv** [comment]
Yes, Travis in this PR also has the fail

@bors r-

**Comment by arielb1** [comment]
Rebase damage.

@bors r=eddyb

**Comment by arielb1** [comment]
```
C:/projects/rust/mingw32/bin/ar.exe: unable to rename '../../../libLLVMSparcDesc.a'; reason: Permission denied
```

Looks spurious

@bors retry

**Pull request merged**
