### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #99212 (introduce `implied_by` in `#[unstable]` attribute)
 - #99352 (Use `typeck_results` to avoid duplicate `ast_ty_to_ty` call)
 - #99355 (better error for bad depth parameter on macro metavar expr)
 - #99480 (Diagnostic width span is not added when '0$' is used as width in format strings)
 - #99488 (compiletest: Allow using revisions with debuginfo tests.)
 - #99489 (rustdoc UI fixes)
 - #99508 (Avoid `Symbol` to `String` conversions)
 - #99510 (adapt assembly/static-relocation-model test for LLVM change)
 - #99516 (Use new tracking issue for proc_macro::tracked_*.)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=99212,99352,99355,99480,99488,99489,99508,99510,99516)

### CODE REVIEW

**Comment by pnkfelix** [comment]
* The 4 primary regressions, 3 are helloworld check, regressing by 2.5% to 2.7% on various incr scenarios. The last is ripgrep check but that only regressed by 0.36%.
* In any case, a broad swath of regressions are signalled for incremental check builds.
* Review of the perf-regression reported here leads me to hypothesize that it might have been injected by PR #99212.
* I'm going to leave a comment over in that PR asking them to double-check whether that PR might have regressed performance.

**Comment by rylev** [comment]
Going to try out the tooling introduced in https://github.com/rust-lang/rustc-perf/pull/701. Forgive any noise. 

@rust-timer make-pr-for https://github.com/rust-lang/rust/commit/857afc75e6ca69cc7dcae36a6fac8c093ee6fa31

**Comment by rylev** [comment]
Trying again! Forgive the noise!

@rust-timer make-pr-for https://github.com/rust-lang/rust/commit/857afc75e6ca69cc7dcae36a6fac8c093ee6fa31

**Pull request merged**
