### PR TITLE
rustc: Stabilize the `#![windows_subsystem]` attribute

### LINKED ISSUE #37499: Tracking issue for Windows subsystem support
Tracking issue for https://github.com/rust-lang/rfcs/pull/1665

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit stabilizes the `#![windows_subsystem]` attribute which is a
conservative exposure of the `/SUBSYSTEM` linker flag on Widnows platforms. This
is useful for creating applications as well as console programs.

Closes #37499

### CODE REVIEW

**Comment by alexcrichton** [comment]
Note that documentation, not currently present, was implemented in https://github.com/rust-lang-nursery/reference/pull/16 and is being pulled in as part of https://github.com/rust-lang/rust/pull/40864

**Comment by liigo** [comment]
Should wait for open issue https://github.com/rust-lang/rust/issues/37553 ?

**Comment by alexcrichton** [comment]
@nrc but I sent the PR :(

@liigo that would be a backwards compatible extension to the current attribute, so I don't see why it would block this.

**Comment by frewsxcv** [comment]
@bors r-

Any chance you could remove the relevant section from the Unstable Book?

If https://github.com/rust-lang/rust/pull/40694 lands before this, you'll get a tidy error for this PR as is.

**Comment by alexcrichton** [comment]
Certainly, I'll tackle that soon.

**Pull request merged**
