### PR TITLE
Fix regression: account for impl methods in arg count mismatch error

### LINKED ISSUE #47706: Compiler Unexpectedly Panicked, call function with wrong number of arguments
First of all, this only happens on nightly 

```
rustc --version --verbose
binary: rustc
commit-hash: 97520ccb101609af63f29919bb0a39115269c89e
commit-date: 2018-01-21
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 4.0
```

I tried to make the code as simple as possible, so it might look like something no sane person would write

```rust
pub struct Foo {
    foo: Option<i32>,
}

impl Foo {
    pub fn new(foo: Option<i32>, _: ()) -> Foo {
        Foo { foo }
    }

    pub fn map(self) -> Option<Foo> {
        self.foo.map(Foo::new)
    }
}
```

This is what i get as output
```
thread 'rustc' panicked at 'non-FnLike node found: NodeImplItem(ImplItem { id: NodeId(14), name: new, hir_id: HirId { owner: DefIndex(0:6), local_id: ItemLocalId(0) }, vis: Public, defaultness: Final, attrs: [], generics: Generics { params: [], where_clause: WhereClause { id: NodeId(15), predicates: [] }, span: src/lib.rs:1:1: 1:1 }, node: Method(MethodSig { unsafety: Normal, constness: NotConst, abi: Rust, decl: FnDecl { inputs: [type(Option<i32>), type(())], output: Return(type(Foo)), variadic: false, has_implicit_self: false } }, BodyId { node_id: NodeId(41) }), span: src/run_info.rs:6:5: 8:6 })', librustc/traits/error_reporting.rs:837:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #47706.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I don't think this should be a rollup -- it fixes a regression, after all.

**Comment by nikomatsakis** [comment]
Well, I guess it depends what rollup means. I tend to think of it as "it lands when it lands", but maybe that's not quite right.

**Comment by estebank** [comment]
My rationale was that it had a better chance of landing sooner without giving it a higher priority, given that it is a small change and didn't want to take a while slot for it. Feel free to change it removing the rollup and increasing the priority.

**Pull request merged**
