### PR TITLE
Move std::sys::{mutex, condvar, rwlock} to std::sys::locks.

### PR DESCRIPTION
**Pull request by m-ou-se**
This cleans up the the std::sys modules a bit by putting the locks in a single module called `locks` rather than spread over the three modules `mutex`, `condvar`, and `rwlock`. This makes it easier to organise lock implementations, which helps with https://github.com/rust-lang/rust/issues/93740.

### CODE REVIEW

**Comment by m-ou-se** [comment]
Since this touches a lot of platform specific code:

@bors rollup=iffy

**Review by dtolnay — APPROVED** [review]

**Comment by m-ou-se** [comment]
Third time's a charm? (:

@bors r=dtolnay

**Pull request merged**
