### PR TITLE
rustdoc: make doctest span tweak a 2024 edition change

### LINKED ISSUE #132203: regression: change in paths/CWD for rustdoc tests
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/better_embedded-0.4.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/code-path-0.3.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/gis_puller-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/haproxy-config-0.4.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/itf-0.2.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/minipng-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/stackdriver_logger-0.8.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/text-to-png-0.2.0/log.txt

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #132203

This is a compatibility hack, because I think the new behavior is better. When an A `include_str!` B, and B `include_str!` C, the path to C should be resolved relative to B, not A. That's how `include!` itself works, so that's how `include_str!` with should work.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Nice, thanks!

@bors r+ rollup

**Comment by compiler-errors** [comment]
Should this not be treated like any other edition 2024 change then, with a migration lint (or at least a best-effort attempt at detecting cases where users may be affected) and a section in the edition 2024 book? This seems a somewhat quick decision to gate this behind edition 2024, and presumably we shouldn't leave users in the dark when they're upgrading and their code suddenly breaks. cc @traviscross

**Comment by notriddle** [comment]
> Should this not be treated like any other edition 2024 change then, with a migration lint (or at least a best-effort attempt at detecting cases where users may be affected) and a section in the edition 2024 book?

This should definitely be in the edition 2024 book.

As for the lint, I couldn't think of a good way to suggest a fix. There's no way to fix it before you migrate, and after you migrate, there already is a suggestion, as you can see [in the crater reports](https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/better_embedded-0.4.0/log.txt).

<details>

# Rustdoc doctest nested `include_str!` change

🚧 The 2024 Edition has not yet been released and hence this section is still "under construction".
More information may be found at <https://github.com/rust-lang/rust/pull/132210>.

## Summary

When a doctest is included with `include_str!`, if that doctest itself
also uses `include!` / `include_str!` / `include_bytes!`, the path is
resolved relative to the Markdown file, rather than the Rust
source file.

## Details

Prior to the 2024 edition, adding documentation with
`#[doc=include_str!("path/file.md")]` didn't carry span information
into the doctests. As a result, if the Markdown file is in a different
directory than the source, any `include!`ed paths need to be relative
to the Rust file.

For example, consider a library crate with these files:

* Cargo.toml
* README.md
* src/
* * lib.rs
* examples/
* * data.bin

Let `lib.rs` contain this:

```rust
#![doc=include_str!("../README.md")]
```

And assume this `README.md` file:

````markdown
```
let _ = include_bytes!("../examples/data.bin");
//                      ^^^ notice this
```
````

Prior to the 2024 edition, the path in `README.md` needed to be
relative to the `lib.rs` file. In 2024 and later, it is now relative
to `README.md` iself.

## Migration

After migrating, you'll see the following error:

```text
error: couldn't read `../examples/data.bin`: No such file or directory (os error 2)
 --> src/../README.md:2:24
  |
2 | let _ = include_bytes!("../examples/data.bin");
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)
help: there is a file with the same name in a different directory
  |
2 | let _ = include_bytes!("examples/data.bin");
  |                        ~~~~~~~~~~~~~~~~~~~
```

</details>

**Comment by traviscross** [comment]
@bors r-

(Edition-related.  Comment to follow.)

**Comment by traviscross** [comment]
While this seems a sensible change, it is very late to be adding an edition item.  If this is to go into Rust 2024 at all, we need to follow some process to ensure this is ready for the edition before the change itself lands. Here's what needs to happen:

- [x] File an edition tracking issue for the change.  I've done this:
  - https://github.com/rust-lang/rust/issues/132230
- [ ] Complete the other required steps for an edition item.  In particular:
  - [ ] Confirm whether or not there is some edition migration lint needed here, and if there is, implement it.
  - [ ] Write up a chapter for the edition guide and have it approved.
  - [ ] Confirm whether there are any changes needed to the Reference, and if so, put up that PR.
  - [ ] Confirm that this is a decision by the @rust-lang/rustdoc team to request a Rust 2024 edition item.
    - I don't see an FCP or other similar consensus decision, but maybe this was discussed elsewhere.
  - [ ] Confirm with the edition team this can be accepted for the edition at the point these things are ready.
    - In particular, I want sign-off from @ehuss that this late change does not worry him too much with respect to how we test the edition with crater.
  - [ ] Then merge this PR landing the change in Rust 2024.

Hopefully this list doesn't seem too daunting.  On net, I probably would like to see this happen.  But there's some catch-up needed here if this is going to happen, and these items will need to all happen within a very short time -- days, not weeks.

Looking at the [breakage](https://github.com/rust-lang/rust/issues/132203), one alternative that the rustdoc team might want consider here is whether this bug might be fixed without making this an edition item at all.  Perhaps there is a way to issue a FCW if it seems a crate is relying on the bug?  Then PRs could be submitted to the affected crates.  After some time, then perhaps the change could be landed (in all editions).

Please let us know what you want to do here, in particular if you do plan to quickly complete the steps needed to make this an edition item.

**Comment by traviscross** [comment]
The edition guide change is merged.  There are no edition migration lints for this.  @GuillaumeGomez has confirmed the rustdoc team wants this as an edition item.

On the edition side, we've discussed and can fit this into our testing with it merging now, so let's get it in.

I would r+ this, but it looks like from the logs [above](https://github.com/rust-lang/rust/pull/132210#issuecomment-2440100242) that some tests here still need to be fixed.  When that's resolved, this is good to go, `r=me,GuillaumeGomez`.

**Comment by notriddle** [comment]
Okay, ignoring windows on the test that cares about path syntax.

**Comment by GuillaumeGomez** [comment]
Issue was approved so I'm planning on r+ing this PR by this evening. CI seems to have been cancelled so I'll wait for @notriddle to take another look here before doing anything.

**Comment by GuillaumeGomez** [comment]
CI is failing. Once fixed, please r=me. :)

**Pull request merged**
