### PR TITLE
Detect struct literal needing parentheses

### LINKED ISSUE #82051: Bad diagnostic: "error: struct literal body without path"
I tried to use a struct literal as part of a condition, and got a bad error message. Here's a reduced version that fails:

```rust
pub struct Example { a: i32 }

impl Example {
    fn is_pos(&self) -> bool { self.a > 0 }
}

fn one() -> i32 { 1 }

fn main() {
    if Example { a: one() }.is_pos() {
        println!("Positive!");
    }
}
```

[Playground link.](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=64a09cc9d03174b5a51cb7865adebabc)

This gives this rather poor error message which doesn't align with the actual problem:

```rust
Standard Error

   Compiling playground v0.0.1 (/playground)

error: struct literal body without path
  --> src/main.rs:10:16
   |
10 |     if Example { a: one() }.is_pos() {
   |                ^^^^^^^^^^^^
   |
help: you might have forgotten to add the struct literal inside the block
   |
10 |     if Example { SomeStruct { a: one() } }.is_pos() {
   |                ^^^^^^^^^^^               ^

error: expected one of `.`, `;`, `?`, `}`, or an operator, found `{`
  --> src/main.rs:10:39
   |
10 |     if Example { a: one() }.is_pos() {
   |                                      ^ expected one of `.`, `;`, `?`, `}`, or an operator
```

If I change the `one()` to a literal `1`, then it gives a much more useful error message:

```rust
error: struct literals are not allowed here
  --> src/main.rs:10:8
   |
10 |     if Example { a: 1 }.is_pos() {
   |        ^^^^^^^^^^^^^^^^
   |
help: surround the struct literal with parentheses
   |
10 |     if (Example { a: 1 }).is_pos() {
   |        ^                ^
```

So something about having a function call in the struct initializer breaks the diagnostic.

### Meta

Tested against the 
`rustc --version --verbose`:
```
1.52.0-nightly (2021-02-12 3f5aee2d5241139d808f)
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #82051.

### CODE REVIEW

**Comment by Naplues** [comment]
LGTM

**Review by Naplues — COMMENTED** [review]
LGTM......OK

**Review by davidtwco — APPROVED** [review]

**Pull request merged**
