### PR TITLE
Emit column info in debuginfo for non msvc like targets

### LINKED ISSUE #42921: Include column info in debuginfo
I think that we should include column info in debuginfo, so that backtraces become more informative.

Often you do multiple function calls on a line, like `ctr = ctr.inc().inc();` or `let foo = wrap((), wrap((),()))`.

If one of these function calls generates a panic or something else that causes a backtrace, you can't know immediately which of the function calls actually caused the issue.

Apparently, right now we are setting the column number to zero: ae6628573282855a9b93de266add64c69411b0b0

The reason *seems* to be that GCC/Clang don't emit column numbers either and apparently GDB had issues with it. See #9641 and #10966. However, the change was from 2013, and maybe GDB support has changed since. Also, maybe if we ask kindly, GDB could consider adding support. AFAIK we already ship our copy of GDB so we might not even have to wait for a release to enable this per default.

Note that this is separate from panic locations, which doesn't use the LLVM debug info system but uses our own system instead. I'm preparing a PR to add line number info for panic's (without the RUST_BACKTRACE input) and want to file it soon. EDIT: #42938

cc @eddyb @michaelwoerister

### PR DESCRIPTION
**Pull request by est31**
Fixes #42921 everywhere except MSVC. This mimics clang behaviour.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could a test be added for this?

**Comment by est31** [comment]
@alexcrichton no idea how to get tests out of this using lldb or gdb, which the debuginfo tests rely on. The only place lldb exposes column info that I am aware of is in underlining the column: https://reviews.llvm.org/rL282105

I could create something using gimli/addr2line but not sure if we want to add it for the test harness just for that :).

**Comment by est31** [comment]
Note that this underlining happens using ANSI control characters. It's not like rustc's span rendering.

**Comment by alexcrichton** [comment]
@bors: r+

Ok in that case seems fine to leave this as-is

**Pull request merged**
