### PR TITLE
[experiment] refactor `WorkerLocal` into enum for parallel compiler

### PR DESCRIPTION
**Pull request by deltragon**
Based on my suggestion in https://github.com/rust-lang/rust/pull/109478#discussion_r1144631591.

### CODE REVIEW

**Comment by SparrowLii** [comment]
> @SparrowLii Would it be possible to kick off a perf run for this?

Yeah sure. Sorry for the missing

**Comment by deltragon** [comment]
Thanks!

**Comment by SparrowLii** [comment]
I think the perf result in #109528 is nice(There is some increase in wall-time, but it has little effect on global effects). Thanks!

**Comment by deltragon** [comment]
Thank you, for your work on the parallel compiler!

**Pull request closed without merging**
