### PR TITLE
Remove x86_64-fuchsia and aarch64-fuchsia target aliases

### LINKED ISSUE #106649: Remove `x86_64-fuchsia` and `aarch64-fuchsia` target triple aliases
The aliases introduced in #106636 can be removed once downstream projects have time to migrate to the new target triples:

* `x86_64-unknown-fuchsia`
* `aarch64-unknown-fuchsia`

cc @djkoloski

### PR DESCRIPTION
**Pull request by arttet**
Closes #106649.

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
This seems reasonable to me given that sufficient time has passed since last time this was attempted, and since this is T2 target I don't think this needs an FCP. But I'll ask T-compiler leads to double check. In any case, this should get compatibility relnotes, and I'll cc the target maintainers.

**Comment by jieyouxu** [comment]
Dear Fuchsia team, are you okay with removing these target aliases? 
@rustbot ping fuchsia

**Comment by tmandry** [comment]
Yep this looks good, thanks for the cleanup!

**Comment by jieyouxu** [comment]
Since this is desired by the target maintainers themselves and this is removing Tier 2 target aliases in favor of the more unambiguous ones (with suitable relnotes to clearly communicate to users), I think this is good to go without needing a compiler FCP.

@bors r+ rollup

**Pull request merged**
