### PR TITLE
coverage: Harmonize the `coverage-map` and `run-coverage` test directories

### PR DESCRIPTION
**Pull request by Zalathar**
While exploring ways to merge these two separate test directories into one directory, I quickly found that an important first step is to harmonize the two directories so that their sets of enclosed `*.rs` files are *completely* identical, instead of just mostly-identical.

---

This has been split off into its own PR so that it can be reviewed independently as a smaller unit. ~~I’m still working on ways to actually combine these two test directories into one shared directory; that work will build on top of this PR.~~ The two directories will be fully unified by #117484, which builds on top of these changes.

---

Closed in favour of #117484, which incorporates all of these changes.

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]

**Comment by cjgillot** [comment]
Could we have a single directory doing both testsuites?

**Comment by Zalathar** [comment]
That's what I'm working towards, but I'll need to make some changes to compiletest for that to work properly.

So this PR is cleaning up the two test directories so that when I do make those changes, actually merging the two directories becomes a trivial step.

**Comment by Zalathar** [comment]
(E.g. right now bootstrap can't actually handle a test suite having a different name from its test directory, so the obvious approach of “just point two different suites at the same directory” doesn't actually work.)

**Comment by cjgillot** [comment]
> (E.g. right now bootstrap can't actually handle a test suite having a different name from its test directory, so the obvious approach of “just point two different suites at the same directory” doesn't actually work.)

What about a single directory = testsuite which runs the checks from both current testsuites?

**Comment by Zalathar** [comment]
I figured out how to make the necessary changes in bootstrap without touching compiletest at all, so I've filed the full unification as #117484.

**Comment by compiler-errors** [comment]
r? cjgillot

**Comment by Zalathar** [comment]
These changes have been incorporated into #117484, which has received an r+ but encountered test failures on Windows that have now been fixed.

So instead of approving this PR, it might make more sense to re-approve the combined PR and merge both parts in one go.

**Comment by compiler-errors** [comment]
Yeah, sounds good, let's close this PR then, if you don't mind.

**Pull request closed without merging**
