### PR TITLE
Rollup of 13 pull requests

### LINKED ISSUE #96847: internal error: entered unreachable code: in literal form when lowering mac args eq
I'm seeing an internal compiler error on the following input, found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc):

### Code

```rust
fn main() {
    for _ in [] {
        #![doc=""]
    }
}
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
warning: unused doc comment
 --> src/main.rs:3:9
  |
2 | /     for _ in [] {
3 | |         #![doc=""]
  | |         ^^^^^^^^^^
4 | |     }
  | |_____- rustdoc does not generate documentation for expressions
  |
  = note: `#[warn(unused_doc_comments)]` on by default
  = help: use `//` for a plain comment

thread 'rustc' panicked at 'internal error: entered unreachable code: in literal form when lowering mac args eq: Lit { token: Lit { kind: Str, symbol: "", suffix: None }, kind: Str("", Cooked), span: src/main.rs:3:16: 3:18 (#0) }', compiler/rustc_ast_lowering/src/lib.rs:903:17
```

This is not unique to `doc` attributes, it can be replaced by any other name, but I used `doc` in the example because I know it is imported by default. Affected versions: nightly 2022-05-07 is affected, but beta 1.61.0-beta.5 and stable 1.60.0 are not affected

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
warning: unused doc comment
 --> src/main.rs:3:9
  |
2 | /     for _ in [] {
3 | |         #![doc=""]
  | |         ^^^^^^^^^^
4 | |     }
  | |_____- rustdoc does not generate documentation for expressions
  |
  = note: `#[warn(unused_doc_comments)]` on by default
  = help: use `//` for a plain comment

thread 'rustc' panicked at 'internal error: entered unreachable code: in literal form when lowering mac args eq: Lit { token: Lit { kind: Str, symbol: "", suffix: None }, kind: Str("", Cooked), span: src/main.rs:3:16: 3:18 (#0) }', compiler/rustc_ast_lowering/src/lib.rs:903:17
stack backtrace:
   0:     0x7f7565767ead - std::backtrace_rs::backtrace::libunwind::trace::ha82e355503b775ae
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7565767ead - std::backtrace_rs::backtrace::trace_unsynchronized::h8e110267c4bde050
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7565767ead - std::sys_common::backtrace::_print_fmt::h5f563af01e258275
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f7565767ead - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hea5b1fa30c1333eb
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f75657c3b6c - core::fmt::write::h82dfb1eb62467416
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f75657595a1 - std::io::Write::write_fmt::h453cda435b3f142f
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/io/mod.rs:1655:15
   6:     0x7f756576abc5 - std::sys_common::backtrace::_print::hc8f28f28ca4dc2eb
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f756576abc5 - std::sys_common::backtrace::print::he50667b6c89ab0df
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f756576abc5 - std::panicking::default_hook::{{closure}}::hefe4dc9c157160a4
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:295:22
   9:     0x7f756576a839 - std::panicking::default_hook::h1376b5b10508fdef
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:314:9
  10:     0x7f7565f2bee1 - rustc_driver[5234e93807a03500]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f756576b396 - std::panicking::rust_panic_with_hook::h839908001643daf0
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:702:17
  12:     0x7f756576b197 - std::panicking::begin_panic_handler::{{closure}}::hf027c1af338d28cd
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:588:13
  13:     0x7f7565768364 - std::sys_common::backtrace::__rust_end_short_backtrace::h42726b9619ec7247
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f756576aec9 - rust_begin_unwind
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:584:5
  15:     0x7f7565730193 - core::panicking::panic_fmt::hecbeff60ca345ea1
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/panicking.rs:142:14
  16:     0x7f7567621501 - <smallvec[783a7bc302c18e9d]::SmallVec<[rustc_ast[8c13dfba7c39903e]::ast::Attribute; 8usize]> as core[6c67f8de41fca20a]::iter::traits::collect::Extend<rustc_ast[8c13dfba7c39903e]::ast::Attribute>>::extend::<core[6c67f8de41fca20a]::iter::adapters::map::Map<core[6c67f8de41fca20a]::slice::iter::Iter<rustc_ast[8c13dfba7c39903e]::ast::Attribute>, <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_attrs::{closure#0}>>
  17:     0x7f75675f03ee - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::expr
  18:     0x7f75682f17c2 - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_expr_for
  19:     0x7f75675ebbfe - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_expr_mut::{closure#0}
  20:     0x7f75675e80f2 - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_stmts
  21:     0x7f75675f401d - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_maybe_async_body
  22:     0x7f7567604da8 - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::with_hir_id_owner::<<rustc_ast_lowering[840f68559e06d09a]::item::ItemLowerer>::with_lctx<<rustc_ast_lowering[840f68559e06d09a]::item::ItemLowerer>::lower_item::{closure#0}>::{closure#0}>
  23:     0x7f756762ad99 - <rustc_ast_lowering[840f68559e06d09a]::item::ItemLowerer>::lower_node
  24:     0x7f7567603adc - rustc_ast_lowering[840f68559e06d09a]::lower_crate
  25:     0x7f7567fdac17 - <rustc_interface[259f7f2d687dc9cd]::passes::boxed_resolver::BoxedResolver>::access::<rustc_interface[259f7f2d687dc9cd]::passes::create_global_ctxt::{closure#0}, &rustc_hir[a682107990697923]::hir::Crate>
  26:     0x7f7567fd0e43 - rustc_interface[259f7f2d687dc9cd]::passes::create_global_ctxt
  27:     0x7f7567ff415d - <rustc_interface[259f7f2d687dc9cd]::queries::Queries>::global_ctxt
  28:     0x7f7567f9d172 - <rustc_interface[259f7f2d687dc9cd]::interface::Compiler>::enter::<rustc_driver[5234e93807a03500]::run_compiler::{closure#1}::{closure#2}, core[6c67f8de41fca20a]::result::Result<core[6c67f8de41fca20a]::option::Option<rustc_interface[259f7f2d687dc9cd]::queries::Linker>, rustc_errors[473276f074908285]::ErrorGuaranteed>>
  29:     0x7f7567fc559f - rustc_span[e19c93a5cc4d231b]::with_source_map::<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_interface[259f7f2d687dc9cd]::interface::create_compiler_and_run<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#1}>
  30:     0x7f7567f9df44 - rustc_interface[259f7f2d687dc9cd]::interface::create_compiler_and_run::<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>
  31:     0x7f7567f9b6f2 - <scoped_tls[7f40d5f18d3a19f0]::ScopedKey<rustc_span[e19c93a5cc4d231b]::SessionGlobals>>::set::<rustc_interface[259f7f2d687dc9cd]::interface::run_compiler<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>
  32:     0x7f7567fb276f - std[da27fefd8cd19b64]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[259f7f2d687dc9cd]::util::run_in_thread_pool_with_globals<rustc_interface[259f7f2d687dc9cd]::interface::run_compiler<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>
  33:     0x7f7567fb28a9 - <<std[da27fefd8cd19b64]::thread::Builder>::spawn_unchecked_<rustc_interface[259f7f2d687dc9cd]::util::run_in_thread_pool_with_globals<rustc_interface[259f7f2d687dc9cd]::interface::run_compiler<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>::{closure#1} as core[6c67f8de41fca20a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7f75657752e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd85bf70b078c05e8
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/alloc/src/boxed.rs:1872:9
  35:     0x7f75657752e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6a20ba204ab10b14
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/alloc/src/boxed.rs:1872:9
  36:     0x7f75657752e3 - std::sys::unix::thread::Thread::new::thread_start::h6522ecd8b15d879a
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7f75656a5609 - start_thread
  38:     0x7f75655be163 - clone
  39:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (ea92b0838 2022-05-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `playground` (bin "playground") generated 1 warning
error: could not compile `playground`; 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #93896 (rustdoc: make item-infos dimmer on dark theme)
 - #99337 (rustdoc: simplify highlight.rs)
 - #99421 (add crt-static for android)
 - #99500 (Fix flags when using clang as linker for Fuchsia)
 - #99511 (make raw_eq precondition more restrictive)
 - #99992 (Add `x.sh` and `x.ps1` shell scripts)
 - #100112 (Fix test: chunks_mut_are_send_and_sync)
 - #100203 (provide correct size hint for unsupported platform `CommandArgs`)
 - #100307 (Fix #96847)
 - #100350 (Stringify non-shorthand visibility correctly)
 - #100374 (Improve crate selection on rustdoc search results page)
 - #100392 (Simplify visitors)
 - #100418 (Add stability attributes to BacktraceStatus variants)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=93896,99337,99421,99500,99511,99992,100112,100203,100307,100350,100374,100392,100418)

### CODE REVIEW

**Comment by rylev** [comment]
Going to do perf runs for a few of these: 

@rust-timer build 5832462aa1d9373b24ace96ad2c50b7a18af9952 (https://github.com/rust-lang/rust/pull/100307)
@rust-timer build 23936af287657fa4148aeab40cc2a780810fae52 (https://github.com/rust-lang/rust/pull/100392)

**Comment by rylev** [comment]
If anyone is curious why this only kicked off one build: https://github.com/rust-lang/rustc-perf/issues/1396

**Comment by rylev** [comment]
And now the other one:

@rust-timer build 23936af287657fa4148aeab40cc2a780810fae52 (https://github.com/rust-lang/rust/pull/100392)

**Comment by rylev** [comment]
And one last one (as I finally noticed that most of the regressions were in rustdoc):

@rust-timer build f370320e21804276c98109442f99598af33d7cce (https://github.com/rust-lang/rust/pull/99337)

**Comment by rylev** [comment]
Definitely looks like #99337 is the cause of these perf regressions. We normally have a bit more tolerance for rustdoc perf regressions and these numbers are by no means large. 

cc @jsha @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'm surprised there is an impact on performance at all. But it was a code improvement change so I think it's still worth it and we expect that it will be reverted with the changes we're currently doing on this part of rustdoc.

**Comment by Mark-Simulacrum** [comment]
Marking as triaged. I think the regression is within the bounds we don't need to track the fix closely, though it's great that it sounds like there will be work that may improve things in this area.

**Pull request merged**
