### PR TITLE
Clean up jobserver integration

### PR DESCRIPTION
**Pull request by Zoxc**
cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me when you're satisfied with the testing, definitely much cleaner now!

**Comment by Zoxc** [comment]
@rust-timer build 29efa193a1a6b5480ece517b29cc2a2ad035aa25

**Comment by killercup** [comment]
@Zoxc wow, the perf diff in https://github.com/rust-lang/rust/pull/59804#issuecomment-481083119 looks… disconcerting. I assume this is an issue with the measurement system?

**Comment by Zoxc** [comment]
@killercup No they [look good](https://perf.rust-lang.org/compare.html?start=3750348daff89741e3153e0e120aa70a45ff5b68&end=29efa193a1a6b5480ece517b29cc2a2ad035aa25&stat=wall-time). It fixes the regression [seen previously here](https://perf.rust-lang.org/compare.html?start=2002b4b39a16760f37107cf02d7a91ff316d3073&end=e1f9d0488d052f77315c033b3b8bf47a4d8fdb11&stat=wall-time).

**Comment by Zoxc** [comment]
The effect of this PR being [approximately this](https://perf.rust-lang.org/compare.html?start=e1f9d0488d052f77315c033b3b8bf47a4d8fdb11&end=29efa193a1a6b5480ece517b29cc2a2ad035aa25&stat=wall-time).

**Comment by Zoxc** [comment]
Any reason for not rolling this up?

**Comment by Centril** [comment]
@Zoxc I was going to r- this as the cause of failure in https://github.com/rust-lang/rust/pull/59937#issuecomment-482830960 but wasn't sure.

**Comment by Zoxc** [comment]
Seems unlikely to me.

**Pull request merged**
