### PR TITLE
Only track mentioned places for jump threading

### PR DESCRIPTION
**Pull request by cjgillot**
This PR aims to reduce the state space size in jump threading and dataflow const-prop opts.

The current implementation walks the types of all locals, and creates a place for each possible projection. This can easily lead to a large number of places and tracked values, most being useless to the actual pass.

With this PR, we instead collect places that appear syntactically in the MIR (first commit). However, this is not sufficient (second commit), and we miss places that we could track in aggregate assignments. The third commit tracks such assignments to mirror place projections, see the inline comment.

This is complementary to https://github.com/rust-lang/rust/pull/127036

r? @oli-obk

### CODE REVIEW

**Comment by tgross35** [comment]
(s/mentionned/mentioned in the PR title before you merge)

**Comment by cjgillot** [comment]
Perf: for the 2 most prominent regressions (syn and ripgrep), the time passes in jump-threading is reduced -40%, and extra time is spent in LLVM.

**Review by oli-obk — APPROVED** [review]
r=me (needs rebase)

**Comment by cjgillot** [comment]
Second perf run to evaluate the effect of https://github.com/rust-lang/rust/pull/127036

@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Second perf run to evaluate the effect of https://github.com/rust-lang/rust/pull/127036

@bors try @rust-timer queue

**Comment by rylev** [comment]
The perf impact was expected given the pre-merge runs and is less severe than it was pre-merge.

@rustbot label: +perf-regression-triaged

**Pull request merged**
