### PR TITLE
Subtree update of `rust-analyzer`

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
CC @HKalbasi

**Comment by HKalbasi** [comment]
It seems the problem is that `default-features` are always included when the crate is added by the `rustc_private`. Is there any way to disable them? To unblocking the sync, we can ignore the CI breakage checking and unconditionally depend on the crates.io version for now.

By the way, what was the previous sync problem and how it got fixed?

**Comment by Veykril** [comment]
> CC @HKalbasi
> 
> Locally I get:
> 
> ```
>    --> crates/hir-def/src/data/adt.rs:181:10
>     |
> 181 |     Some(ReprOptions { int, align: max_align, pack: min_pack, flags })
>     |          ^^^^^^^^^^^ missing `field_shuffle_seed`
> ```
> 
> But I'm not sure I'm building it the right way.

That's because with the `nightly` feature, that field exists (as its type comes from `rustc_datastructures`), with it disabled it doesn't which is what we currently work with.

**Comment by lnicola** [comment]
> By the way, what was the previous sync problem and how it got fixed?

error[E0463]: can't find crate for hkalbasi_rustc_ap_rustc_abi

There was https://github.com/rust-lang/rust-analyzer/pull/15691, but I don't know if it's fixed or it just fails earlier now.

**Comment by hlopko** [comment]
@Veykril and @HKalbasi, could you please advice how we can move this PR forward? This sync is much needed, and the gap between RA and rust repos is growing larger and larger.

**Comment by HKalbasi** [comment]
I opened this zulip stream for discussion on the problem: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Depend.20on.20rustc_private.20crates.20without.20default.20features

If it ends up being unsolvable in a short time, we can disable this and unconditionally depend on the crates.io version to unblock the sync.

**Comment by lnicola** [comment]
Closing in favour of #117544.

**Comment by HKalbasi** [comment]
I made #117544 to just test if using path dependencies works, and it didn't due some problem with `Cargo.lock` which I don't understand really. I will close that PR.

I will try to go with making the `nightly` feature additive that was suggested in the zulip thread in the following days.

**Comment by lnicola** [comment]
Doesn't https://github.com/rust-lang/rust/pull/117544/commits/23f90772fbab7665137904761a6b6236bce54532 need a corresponding lockfile change?

**Comment by HKalbasi** [comment]
I updated the lockfile in https://github.com/rust-lang/rust/pull/117544/commits/a2bd9119cfdff63447dbc4489aa470d13a59129b but it didn't work.

**Comment by HKalbasi** [comment]
@lnicola Can you please create a new sync PR containing this (https://github.com/rust-lang/rust-analyzer/pull/15849) commit?

**Pull request closed without merging**
