### PR TITLE
Add long diagnostics for E0133.

### PR DESCRIPTION
**Pull request by meqif**
cc #24407

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 312b3013e291f297af0afbe4000941877b068526 rollup

Thanks!

**Comment by meqif** [comment]
Should I rebase and `push -f` the changes?

**Comment by michaelsproul** [comment]
@meqif: Yeah, do a rebase and a push, then I'll cherry-pick your commit into a roll-up with a few of the other extended error commits (otherwise we get horrendous merge conflicts).

**Comment by meqif** [comment]
@michaelsproul: Done, thank you.

**Comment by michaelsproul** [comment]
Thank you! :smile:

**Pull request merged**
