### PR TITLE
RFC 3550 data gathering

### PR DESCRIPTION
**Pull request by pitaj**
I have implemented four lints to gather data for rust-lang/rfcs#3550

r? traviscross

Please initiate a crater run. `check-only` seems appropriate, and the following lints need to be enabled:

- `deny(explicit_range)`
- `deny(trait_impl_range)`
- `warn(range_syntax)`
- `warn(range_bounds)`

I believe that equates to the following command, but please double check as I've never used crater myself.

```
@craterbot run mode=check-only +rustflags=-Dexplicit_range -Dtrait_impl_range -Wrange_syntax -Wrange_bounds
```

### CODE REVIEW

**Comment by pitaj** [comment]
Sample output from [`rand` crate](https://github.com/rust-random/rand):

```
RUSTFLAGS="-Dexplicit_range -Dtrait_impl_range -Wrange_syntax -Wrange_bounds" cargo +stage1 check

warning: usage of `RangeInclusive` range syntax
   --> rand_core/src/block.rs:202:33
    |
202 |             let data = &results[index..=index + 1];
    |                                 ^^^^^^^^^^^^^^^^^
    |
    = note: requested on the command line with `-W range-syntax`

warning: usage of `RangeFrom` range syntax
   --> rand_core/src/block.rs:232:64
    |
232 | ...   fill_via_u32_chunks(&mut self.results.as_mut()[self.index..], &mut dest[read_len..]);
    |                                                      ^^^^^^^^^^^^

warning: usage of `RangeFrom` range syntax
   --> rand_core/src/block.rs:232:89
    |
232 | ...   fill_via_u32_chunks(&mut self.results.as_mut()[self.index..], &mut dest[read_len..]);
    |                                                                               ^^^^^^^^^^

warning: usage of `RangeFrom` range syntax
   --> rand_core/src/block.rs:398:44
    |
398 |                 &mut self.results.as_mut()[self.index..],
    |                                            ^^^^^^^^^^^^

warning: usage of `RangeFrom` range syntax
   --> rand_core/src/block.rs:399:27
    |
399 |                 &mut dest[read_len..],
    |                           ^^^^^^^^^^

warning: `rand_core` (lib) generated 5 warnings
warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:161:14
    |
161 |     for _ in 0..drounds {
    |              ^^^^^^^^^^
    |
    = note: requested on the command line with `-W range-syntax`

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:172:9
    |
172 |     out[0..16].copy_from_slice(&results.0.to_scalars());
    |         ^^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:173:9
    |
173 |     out[16..32].copy_from_slice(&results.1.to_scalars());
    |         ^^^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:174:9
    |
174 |     out[32..48].copy_from_slice(&results.2.to_scalars());
    |         ^^^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:175:9
    |
175 |     out[48..64].copy_from_slice(&results.3.to_scalars());
    |         ^^^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:196:18
    |
196 |         for _ in 0..drounds {
    |                  ^^^^^^^^^^

warning: usage of `RangeFrom` range syntax
   --> rand_chacha/src/guts.rs:232:29
    |
232 |         c.write_le(&mut key[16..]);
    |                             ^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:247:35
    |
247 |                 read_u32le(&nonce[0..4])
    |                                   ^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:251:31
    |
251 |             read_u32le(&nonce[nonce.len() - 8..nonce.len() - 4]),
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: usage of `RangeFrom` range syntax
   --> rand_chacha/src/guts.rs:252:31
    |
252 |             read_u32le(&nonce[nonce.len() - 4..]),
    |                               ^^^^^^^^^^^^^^^^^

warning: usage of `RangeFrom` range syntax
   --> rand_chacha/src/guts.rs:255:48
    |
255 |         let key1: Mach::u32x4 = m.read_le(&key[16..]);
    |                                                ^^^^

warning: usage of `RangeFrom` range syntax
   --> rand_chacha/src/guts.rs:267:48
    |
267 |         let key1: Mach::u32x4 = m.read_le(&key[16..]);
    |                                                ^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:275:51
    |
275 |         let ctr_nonce1 = [0, 0, read_u32le(&nonce[16..20]), read_u32le(&nonce[20..24])];
    |                                                   ^^^^^^

warning: usage of `Range` range syntax
   --> rand_chacha/src/guts.rs:275:79
    |
275 |         let ctr_nonce1 = [0, 0, read_u32le(&nonce[16..20]), read_u32le(&nonce[20..24])];
    |                                                                               ^^^^^^

warning: `rand_chacha` (lib) generated 14 warnings
    Checking rand v0.9.0 (/home/peter/Dev/rand)
warning: usage of `Range` range syntax
   --> src/distributions/bernoulli.rs:100:14
    |
100 |         if !(0.0..1.0).contains(&p) {
    |              ^^^^^^^^
    |
    = note: requested on the command line with `-W range-syntax`

warning: usage of `Range` range syntax
   --> src/distributions/weighted_index.rs:224:18
    |
224 |         for i in first_new_index..self.cumulative_weights.len() {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/index.rs:393:14
    |
393 |     for j in length - amount..length {
    |              ^^^^^^^^^^^^^^^^^^^^^^^

warning: usage of `RangeInclusive` range syntax
   --> src/seq/index.rs:394:31
    |
394 |         let t = rng.gen_range(0..=j);
    |                               ^^^^^

warning: usage of `Range` range syntax
   --> src/seq/index.rs:419:20
    |
419 |     indices.extend(0..length);
    |                    ^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/index.rs:420:14
    |
420 |     for i in 0..amount {
    |              ^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/index.rs:421:36
    |
421 |         let j: u32 = rng.gen_range(i..length);
    |                                    ^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/index.rs:489:14
    |
489 |     for _ in 0..amount.as_usize() {
    |              ^^^^^^^^^^^^^^^^^^^^

warning: usage of `Range` range syntax
  --> src/seq/increasing_uniform.rs:53:45
   |
53 |             self.chunk = self.rng.gen_range(0..bound);
   |                                             ^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/mod.rs:179:41
    |
179 |         let distr = WeightedIndex::new((0..self.len()).map(|idx| weight(&self[idx])))?;
    |                                         ^^^^^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/mod.rs:297:41
    |
297 |         let distr = WeightedIndex::new((0..self.len()).map(|idx| weight(&self[idx])))?;
    |                                         ^^^^^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/mod.rs:497:41
    |
497 |                 let highest_selected = (0..lower)
    |                                         ^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/mod.rs:646:22
    |
646 |             for i in m..self.len() {
    |                      ^^^^^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/mod.rs:651:22
    |
651 |             for i in m..self.len() {
    |                      ^^^^^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/mod.rs:706:23
    |
706 |         rng.gen_range(0..ubound as u32) as usize
    |                       ^^^^^^^^^^^^^^^^

warning: usage of `Range` range syntax
   --> src/seq/mod.rs:708:23
    |
708 |         rng.gen_range(0..ubound)
    |                       ^^^^^^^^^

error: public trait impl involving `Range` type
   --> src/distributions/uniform.rs:328:32
    |
328 | impl<X: SampleUniform> TryFrom<Range<X>> for Uniform<X> {
    |                                ^^^^^^^^
    |
    = note: requested on the command line with `-D trait-impl-range`

error: explicit usage of `Range` type in public function
   --> src/distributions/uniform.rs:331:20
    |
331 |     fn try_from(r: ::core::ops::Range<X>) -> Result<Uniform<X>, Error> {
    |                    ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: requested on the command line with `-D explicit-range`

error: public trait impl involving `RangeInclusive` type
   --> src/distributions/uniform.rs:336:32
    |
336 | impl<X: SampleUniform> TryFrom<RangeInclusive<X>> for Uniform<X> {
    |                                ^^^^^^^^^^^^^^^^^

error: explicit usage of `RangeInclusive` type in public function
   --> src/distributions/uniform.rs:339:20
    |
339 |     fn try_from(r: ::core::ops::RangeInclusive<X>) -> Result<Uniform<X>, Error> {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: public trait impl involving `Range` type
   --> src/distributions/uniform.rs:385:56
    |
385 | impl<T: SampleUniform + PartialOrd> SampleRange<T> for Range<T> {
    |                                                        ^^^^^^^^

error: public trait impl involving `RangeInclusive` type
   --> src/distributions/uniform.rs:397:56
    |
397 | impl<T: SampleUniform + PartialOrd> SampleRange<T> for RangeInclusive<T> {
    |                                                        ^^^^^^^^^^^^^^^^^

warning: `rand` (lib) generated 16 warnings
error: could not compile `rand` (lib) due to 6 previous errors; 16 warnings emitted

```

**Comment by Amanieu** [comment]
@craterbot run mode=check-only +rustflags=-Dexplicit_range -Dtrait_impl_range -Wrange_syntax -Wrange_bounds

**Comment by Amanieu** [comment]
@craterbot run mode=check-only +rustflags="-Dexplicit_range -Dtrait_impl_range -Wrange_syntax -Wrange_bounds"

**Comment by Amanieu** [comment]
@craterbot run mode=check-only "+rustflags=-Dexplicit_range -Dtrait_impl_range -Wrange_syntax -Wrange_bounds"

**Comment by Amanieu** [comment]
@craterbot run mode=check-only start=master#158f00a1c5175648af6f6099b075f78d1d014a28 end=try#b4fc5dbf0bc33be331f9d893db5b3a794f29724a+rustflags="-Dexplicit_range -Dtrait_impl_range -Wrange_syntax -Wrange_bounds"

**Pull request closed without merging**
