### PR TITLE
syntax: consolidate function parsing in item.rs

### PR DESCRIPTION
**Pull request by Centril**
Extracted from https://github.com/rust-lang/rust/pull/65324.

r? @estebank

### CODE REVIEW

**Comment by petrochenkov** [comment]
The downside is that I find it progressively harder to find where the code is.
If previously I needed to just Ctrl+F in `parser.rs` now you have to either remember what code is where, or do file search in libsyntax directory.

In this case I'd personally keep the code in `item.rs` because functions are items and `item.rs` is far from being too large. (Plus move the function-related stuff from `parser.rs` to `item.rs`.)

**Comment by Centril** [comment]
>  If previously I needed to just Ctrl+F in `parser.rs` now you have to either remember what code is where, or do file search in libsyntax directory.

I recommend just setting up a keyword in Firefox `rustc myfun` that finds the function; it works quickly for me and I don't need to do a file search. It should also be relatively easy to find something function-parsing related by well... looking at the `fun.rs` file. :)

> and `item.rs` is far from being too large.

It would be roughly >2100 LOC which is imo too large for any file.

> (Plus move the function-related stuff from `parser.rs` to `item.rs`.)

So the reason I'm doing this change specifically is to facilitate the merging of parsing various variants of functions (free, extern, impl, and traits) as we've discussed before and then less logic would be exposed from `fun.rs`.

**Comment by petrochenkov** [comment]
>It would be roughly >2100 LOC which is imo too large for any file.

Ok, my personal limit is ~5000 LOC and tidy enforces 3000 which is a bit too small.

**Comment by Centril** [comment]
>  Either way, `item.rs` fits into it with a margin and I think it's more convenient to keep it together.

Can we at least keep it in one place inside `item.rs`? I found it a hindrance for my refactorings to jump between various locations when refactoring the function grammars.

**Comment by petrochenkov** [comment]
>Can we at least keep it in one place inside item.rs?

Sure! That would be great.

**Comment by Centril** [comment]
r? @petrochenkov Updated.

>  (I wouldn't want to achieve consistency by creating `enum.rs` and `every-other-item.rs` because that would mean many tiny files, which are also bad mkay.)

(Fwiw, I actually wanted to merge all the data type (`struct`, `union`, and `enum`) into a single file because they have relatively similar grammars and are related... also, the module wouldn't be tiny that way.)

**Comment by Centril** [comment]
(Moved one import just a bit to make the diff cleaner...)

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Pull request merged**
