### PR TITLE
Stabilize exact_size_is_empty feature

### LINKED ISSUE #35428: Add `is_empty` function to `ExactSizeIterator`
Tracking issue for functionality introduced in https://github.com/rust-lang/rust/pull/34357

### PR DESCRIPTION
**Pull request by tesuji**
FCP done in https://github.com/rust-lang/rust/issues/35428#issuecomment-260090722

Closes #35428

r? @Centril

### CODE REVIEW

**Comment by Centril** [comment]
r? @SimonSapin 

cc @rust-lang/libs 
cc @scottmcm -- you had concerns?

**Comment by scottmcm** [comment]
Note that `is_empty` was explicitly removed from the PR of the referenced FCP (https://github.com/rust-lang/rust/issues/35428#issuecomment-267400996), so I don't think this PR is a _fait accompli_.

I continue to feel that `.is_empty()` is too useful to be limited to just `ExactSizeIterator`s.

**Comment by SimonSapin** [comment]
At a risk of rehashing the previous thread, please expand on what you would prefer instead. If it should not be limited to that, then what should it be? That plus methods on other existing trait(s) and/or inherent methods on some types? A dedicated trait? Why? Would a dedicated trait be used in a bound in a generic context?

Having someone champion and argue for a counter-proposal could be a way to unblock this.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this PR as it seems like discussion can happen on the issue until we reach a conclusion (https://github.com/rust-lang/rust/issues/35428). Thanks for the PR, though!

**Pull request closed without merging**
