### PR TITLE
update miri

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
``
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
```
und
```
[01:25:45] 1 command(s) did not execute successfully:
[01:25:45] 
[01:25:45]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/nomicon/src/vec-final.md" "--test-args" ""
```
That's not introduced by this PR, is it?

**Comment by oli-obk** [comment]
cc @kennytm maybe related to all submodules successfully passing CI? :laughing:

**Comment by oli-obk** [comment]
@bors r+ p=1

let's see if bors likes this better

**Comment by oli-obk** [comment]
A bunch of tests are failing on windows:

```
error[E0080]: constant evaluation error
  --> C:\projects\rust\src\libstd\sys\windows\stack_overflow.rs:45:8
   |
45 |     if c::AddVectoredExceptionHandler(0, vectored_handler).is_null() {
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no mir for `std::sys::windows::c::::AddVectoredExceptionHandler`
   |
note: inside call to `std::sys::windows::stack_overflow::init`
  --> C:\projects\rust\src\libstd\rt.rs:44:9
   |
44 |         sys::stack_overflow::init();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside call to `std::rt::lang_start_internal`
  --> C:\projects\rust\src\libstd\rt.rs:74:5
   |
74 |     lang_start_internal(&move || main().report(), argc, argv)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```

**Comment by RalfJung** [comment]
Needs a fix on Windows, which is being developed at https://github.com/solson/miri/pull/401

**Comment by RalfJung** [comment]
Blocked by https://github.com/rust-lang/rust/pull/52400

**Comment by kennytm** [comment]
#52400 has been merged.

**Comment by RalfJung** [comment]
Yep, now this is blocked on https://github.com/solson/miri/pull/401 :)

**Comment by RalfJung** [comment]
```
[01:31:17] 2 command(s) did not execute successfully:
[01:31:17] 
[01:31:17]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/nomicon/src/vec-final.md" "--test-args" ""
[01:31:17] 
[01:31:17]   - "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/clippy/Cargo.toml"
```

Looks like miri worked fine?

**Comment by kennytm** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/52433#issuecomment-405326615

**Comment by RalfJung** [comment]
All right, miri should be fixed (again). Let's hope nobody else breaks it this time. ;)

**Comment by RalfJung** [comment]
Rebased.

@bors r=oli-obk

**Comment by nikomatsakis** [comment]
cc @alexcrichton -- any idea why @RalfJung doesn't have review privileges, given https://github.com/rust-lang/rust-central-station/pull/72?

**Pull request merged**
