### PR TITLE
Stabilize feature `cstr_is_empty`

### LINKED ISSUE #102444: Tracking Issue for CStr::is_empty
Feature gate: `#![feature(cstr_is_empty)]`

This is a tracking issue for adding an `is_empty()` method to `core::ffi::CStr`.

ACP: https://github.com/rust-lang/libs-team/issues/106

### Public API

```rust
// core::ffi

impl CStr {
	pub const fn is_empty(&self) -> bool;
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/102445
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/111043

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by jmillikin**
Fixes #102444

ACP: https://github.com/rust-lang/libs-team/issues/106

### CODE REVIEW

**Comment by BurntSushi** [comment]
@rfcbot fcp merge

This PR stabilizes [`CStr::is_empty`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.is_empty), which returns true if the underlying C string is empty. Note that this doesn't include a `CStr::len` method, as it's not clear that's something we want since it could become a costly operation in the future. But `CStr::is_empty` will never be costly.

**Comment by dtolnay** [comment]
@rfcbot fcp cancel

**Review by dtolnay — APPROVED** [review]
This already completed FCP in #102444.

**Comment by BurntSushi** [comment]
Hah, nice. I even participated in that discussion. That explains the déjà vu feeling. :rofl:

**Pull request merged**
