### PR TITLE
shrink doctree::Module

### PR DESCRIPTION
**Pull request by tdelabro**
helps https://github.com/rust-lang/rust/issues/76382

### CODE REVIEW

**Comment by tdelabro** [comment]
So I went with a provisional change to `hir::map` and now it's all good, except for one test: `src/test/rustdoc/redirect-rename.rs`.

**Comment by jyn514** [comment]
> But there is maybe a smart workaround I don't see here that allow us not to store anything in Module

If you know of one let me know :laughing: it annoys me that we have to store it in the `items` for everything else too.

**Comment by jyn514** [comment]
I think if you have to store `renamed` anyway there's not much point in removing the `name` field. I did that for the other items because it allowed reusing `hir::Item`, but we can't do that here.

Removing `where_outer` is still useful :)

**Comment by tdelabro** [comment]
> Removing `where_outer` is still useful :)

I pushed a new version, with just the removal of where_outer :)

**Pull request merged**
