### PR TITLE
update miri

### LINKED ISSUE #60533: `miri` no longer builds after rust-lang/rust#60462
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#60462, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @eddyb, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @petrochenkov, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
r? @oli-obk

Fixes https://github.com/rust-lang/rust/issues/60533

### CODE REVIEW

**Comment by RalfJung** [comment]
Dang, Miri is broken again.

**Comment by RalfJung** [comment]
All right, this should do it.

**Comment by Centril** [comment]
Prioritizing https://github.com/rust-lang/rust/pull/60885 over this one because only one PR can do lockfile changes; will put this PR in the next rollup.

**Comment by RalfJung** [comment]
And it broke again.

@bors r-

**Comment by RalfJung** [comment]
And fixed again.

@bors r=oli-obk p=1

**Comment by RalfJung** [comment]
Rebased.

@bors r=oli-obk

**Comment by RalfJung** [comment]
Actually, https://github.com/rust-lang/rust/pull/61278 will break Miri again.  So let's let that land first.

@bors r-

**Comment by RalfJung** [comment]
Finally...

@bors r=oli-obk

**Pull request merged**
