### PR TITLE
impl TryFrom<{integer}> for NonZero{integer}

### PR DESCRIPTION
**Pull request by jyn514**
I expected this to already exist and was surprised when it wasn't.

n.b. I don't think the UI tests are quite right, I can mess with them later today.

### CODE REVIEW

**Comment by jyn514** [comment]
This doesn't work, but I'm not sure how to fix it ...

```
---- [ui] ui/numeric/numeric-cast-3.rs stdout ----

error: ui test compiled successfully!
status: exit code: 0
command: "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/home/joshua/rustc/src/test/ui/numeric/numeric-cast-3.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/ui/numeric/numeric-cast-3" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/home/joshua/rustc/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/ui/numeric/numeric-cast-3/auxiliary" "-A" "unused"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------



failures:
    [ui] ui/numeric/numeric-cast-3.rs

test result: FAILED. 0 passed; 1 failed; 16 ignored; 0 measured; 9566 filtered out
```

**Comment by JohnTitor** [comment]
@jyn514 You should add `check-pass` flag to the test, like this:

```rust
// check-pass
use std::num::NonZeroUsize;
use std::convert::TryInto;
...
```

**Review by dtolnay — COMMENTED** [review]
Could you give a real world example where this impl would be needed?

The test shows `let a: NonZeroUsize = 1_usize.try_into().unwrap();` but this isn't actually a thing we would expect anyone to write, right?

**Comment by jyn514** [comment]
That's code that I tried to write just now, it's why I made the PR.

```rust
 181             match usize::from_str_radix(s, 10) {
 182                 Ok(0) => Ok(None),
 183                 Ok(i) => Ok(Some(NonZeroUsize::new(i).unwrap())),
 184                 Err(e) => Err(e),
 185             }
```

I _could_ use `unsafe` here but I'd really rather not.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/issues/22639 would also have fixed my problem.

**Comment by dtolnay** [comment]
I would recommend writing that snippet much more concisely as:

```rust
usize::from_str_radix(s, 10).map(NonZeroUsize::new)
```

Overall I'm not sure I buy the advantage of the genericism of TryFrom over the existing `new` constructors, so I'll go ahead and close this. Thanks anyway!

**Comment by jyn514** [comment]
That snippet is indeed a lot nicer, thank you!

**Pull request closed without merging**
