### PR TITLE
Make AtomicBool the same size as bool

### PR DESCRIPTION
**Pull request by Amanieu**
Reopening #32365

This allows `AtomicBool` to be transmuted to a `bool`, which makes it more consistent with the other atomic types. Note that this now guarantees that the atomic type will always contain a valid `bool` value, which wasn't the case before (due to `fetch_nand`).

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 915fa57a931d044005cdf749eb4cba43d7d3e67d

Thanks!

**Comment by alexcrichton** [comment]
Note that the libs team discussed this change during triage the other day and the conclusion was that we're amenable to this with the other recent changes to `std::sync::atomic`

**Comment by ubsan** [comment]
Is this a guarantee? Like, on all platforms, all compilers, AtomicBool can be transmuted to bool? Or just specific platforms?

**Comment by Amanieu** [comment]
As it is currently implemented, a transmute will work fine. However I am not sure whether we should make this guarantee to users. Note that currently, atomic-rs relies on `AtomicU{8,16,32,64}` being transmutable to & from their respective integer type.

**Comment by alexcrichton** [comment]
When discussed with the libs team, the conclusion was that `AtomicBool` will not be able to be transmuted to `bool`, or rather it's not a guarantee that's provided.

**Comment by durka** [comment]
This was a breaking change because people were previously transmuting usize to AtomicBool (see #33724).

**Pull request merged**
