### PR TITLE
Stabilize `main_separator_str`

### LINKED ISSUE #94071: Tracking Issue for MAIN_SEPARATOR_STR
Feature gate: `#![feature(main_separator_str)]`

This is a tracking issue for adding a static path separator str to match the static char already available.

### Public API

```rust
pub const MAIN_SEPARATOR: char = '/';
pub const MAIN_SEPARATOR_STR: &str = "/";
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/93976
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

Can we combine the char and str API into one type that `AsRef`s to char, str, u8 etc. as needed?

### PR DESCRIPTION
**Pull request by SUPERCILEX**
See reasoning here: https://github.com/rust-lang/rust/issues/94071#issuecomment-1279872605. Closes #94071.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@rfcbot merge

**Comment by SUPERCILEX** [comment]
Hmmm, looks like randos can't use the bot. No idea what the process is to request an FCP.

**Comment by Nilstrieb** [comment]
Someone from T-libs-api needs to start the FCP

**Comment by SUPERCILEX** [comment]
@Nilstrieb got it, thanks. It it ok to have this PR open then? Is it basically the equivalent of requesting someone consider starting an FCP?

**Comment by ChrisDenton** [comment]
Usually an fcp happens on the tracking issue before a stabilization PR is created because it can take a while to complete (iirc a minimum of 10 days, usually longer though). It's fine to have this PR open but it means you may have to rebase if other changes are made in the repository while the fcp is pending. Also it should be labelled as T-libs-api (which can be done using rustbot),

@rustbot label +T-libs-api -T-libs

**Comment by SUPERCILEX** [comment]
@ChrisDenton thanks for the explanation! I'll just leave this open since conflicts would be trivial to resolve.

**Comment by SUPERCILEX** [comment]
r? libs

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by dtolnay** [comment]
I'm marking @yaahc's box because she has stepped down from T-libs-api after the point that this PR got proposed for FCP.

**Review by dtolnay — APPROVED** [review]

**Comment by SUPERCILEX** [comment]
Woohoo, thanks!

**Pull request merged**
