### PR TITLE
Add pretty printer for &mut []

### LINKED ISSUE #30232: rust-lldb: add a pretty printer for &mut slices
Pretty printer for `&mut` slices doesn't work.

I tried this code:

```rust
fn main() {
    let mut v = vec![4, 6, 7, 8, 5, 1, 2, 3];
    slice_mut(&mut v);
}

fn slice_mut(a: &mut [u32]) {
}
```

In rust-lldb `p a` should print:
```
(&mut [u32]) $0 = &[4, 6, 7, 8, 5, 1, 2, 3]
```

Instead, it prints:
```
(&mut [u32]) $0 = &mut [u32] {
data_ptr: &0x10102b000, 
length: 8
}
```

## Meta

`rustc --version --verbose`:
```
rustc 1.6.0-nightly (a2866e387 2015-11-30)
binary: rustc
commit-hash: a2866e387eab59528466a040e815568e57b20850
commit-date: 2015-11-30
host: x86_64-apple-darwin
release: 1.6.0-nightly
```

### PR DESCRIPTION
**Pull request by untitaker**
Fix #30232

### CODE REVIEW

**Comment by untitaker** [comment]
BTW I've verified the new behavior manually using rust-gdb.

**Comment by alexcrichton** [comment]
Thanks! Can you add a test for this as well?

**Comment by untitaker** [comment]
I have added tests now, but haven't verified locally whether they pass because I have had enough of that experience while working on https://github.com/rust-lang/rust/pull/30250. IIRC I even found out a way to just run the lldb/gdb tests, but the testrunner still recompiled rustc every time.

**Comment by untitaker** [comment]
I've now also triggered extra builds to tests whether the tests are effective (I wouldn't know), because in #30250 I've had the CI pass even though it shouldn't.

Any hint on how to run the tests efficiently locally would be apprechiated.

**Comment by alexcrichton** [comment]
Looks good to me! If you want to squash I'll r+

**Comment by untitaker** [comment]
I don't understand why the tests pass for  b031de3

**Comment by untitaker** [comment]
Ah, it seems that Travis doesn't test this part of the system, only Bors does. Is there a different way to verify that the tests are effective?

**Comment by alexcrichton** [comment]
Oh it appears that travis doesn't have gdb installed, so it's not running gdb tests. I believe that's an error! If you'd like, you could modify `.travis.yml` to install gdb and verify they're running?

**Comment by untitaker** [comment]
This might be intentional as IIRC according to CONTRIBUTING, Travis only runs a subset of all tests.

On 12 January 2016 01:34:48 CET, Alex Crichton <notifications@github.com> wrote:
>Oh it appears that travis doesn't have gdb installed, so it's not
>running gdb tests. I believe that's an error! If you'd like, you could
>modify `.travis.yml` to install gdb and verify they're running?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/rust/pull/30249#issuecomment-170742940

-- 
Sent from my phone. Please excuse my brevity.

**Comment by alexcrichton** [comment]
That's somewhat outdated, there's no reason we *didn't* install gdb on travis afaik.

I'm fine with merging though, so if you want to squash we can send to bors

**Comment by untitaker** [comment]
I've now updated the PR to install gdb and lldb explicitly in Travis. The first commit contains the test and the changes to travis.yml, and should fail if Travis runs the tests correctly. The second commit contains the actual fix.

**Comment by alexcrichton** [comment]
Looks like the gdb tests did indeed run on travis, but it also looks like one of them failed.

**Comment by sfackler** [comment]
This looks like it's good to go?

**Comment by untitaker** [comment]
It seems that lldb tests are only run on OS X, so I have no way of verifying whether the tests I wrote are any good.

**Comment by Manishearth** [comment]
```

failures:

---- [debuginfo-lldb] debuginfo/vec-slices.rs stdout ----
	NOTE: compiletest thinks it is using LLDB version 310

error: line not found in debugger output: [...]$6 = &mut [64, 65]
status: exit code: 0
command: "/usr/bin/python2.7" "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/src/etc/lldb_batchmode.py" "x86_64-apple-darwin/test/debuginfo-lldb/vec-slices.stage2-x86_64-apple-darwin" "x86_64-apple-darwin/test/debuginfo-lldb/vec-slices.debugger.script"
stdout:
------------------------------------------
LLDB batch-mode script
----------------------
Debugger commands script is 'x86_64-apple-darwin/test/debuginfo-lldb/vec-slices.debugger.script'.
Target executable is 'x86_64-apple-darwin/test/debuginfo-lldb/vec-slices.stage2-x86_64-apple-darwin'.
Current working directory is '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/obj'
Creating a target for 'x86_64-apple-darwin/test/debuginfo-lldb/vec-slices.stage2-x86_64-apple-darwin'
settings set auto-confirm true

version
lldb-310.2.37 
command script import /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/./src/etc/lldb_rust_formatters.py
type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
type category enable Rust

breakpoint set --line 112
Breakpoint 1: where = vec-slices.stage2-x86_64-apple-darwin`vec_slices::main + 206 at vec-slices.rs:112, address = 0x0000000100000a4e 
run
Hit breakpoint 1.1: where = vec-slices.stage2-x86_64-apple-darwin`vec_slices::main + 206 at vec-slices.rs:112, address = 0x0000000100000a4e, resolved, hit count = 1 
Process 39175 launched: '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/obj/x86_64-apple-darwin/test/debuginfo-lldb/vec-slices.stage2-x86_64-apple-darwin' (x86_64) 
print empty
(&[i64]) $0 = &[] 
print singleton
(&[i64]) $1 = &[1] 
print multiple
(&[i64]) $2 = &[2, 3, 4, 5] 
print slice_of_slice
(&[i64]) $3 = &[3, 4] 
print padded_tuple
(&[(i32, i16)]) $4 = &[(6, 7), (8, 9)] 
print padded_struct
(&[vec_slices::AStruct]) $5 = &[AStruct { x: 10, y: 11, z: 12 }, AStruct { x: 13, y: 14, z: 15 }] 
print 'vec_slices::MUT_VECT_SLICE'
(int) $6 = 1279869765 
quit


------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[debuginfo-lldb] debuginfo/vec-slices.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/src/compiletest/runtest.rs:1505
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [debuginfo-lldb] debuginfo/vec-slices.rs

test result: FAILED. 90 passed; 1 failed; 10 ignored; 0 measured
```

**Comment by untitaker** [comment]
print 'vec_slices::MUT_VECT_SLICE'
    (int) $6 = 1279869765 

that seems unreal. Anybody knows what is happening there?

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with the test fixed!

**Comment by untitaker** [comment]
@alexcrichton I don't know how to fix the test failures and asked for help in the previous comment.

**Comment by untitaker** [comment]
Also sorry for the slow reply!

**Pull request closed without merging**
