### PR TITLE
Update RLS to set __CARGO_TEST_ROOT when running its tests.

### PR DESCRIPTION
**Pull request by eddyb**
That is, update RLS to include https://github.com/rust-lang/rls/pull/1138.

This fixes fallout from https://github.com/rust-lang/rust/pull/53586.

r? @alexcrichton cc @Mark-Simulacrum @nrc @pietroalbini

### CODE REVIEW

**Comment by alexcrichton** [comment]
This is an internal environment variable used by cargo and not intended for other users, is there another way to fix this or perhaps something that can be officially supported by cargo?

The double underscore was supposed to indicate that...

**Comment by eddyb** [comment]
@alexcrichton I was told to use that variable in https://github.com/rust-lang/rust/pull/53586#issuecomment-414894774 (and that PR already landed).

**Comment by alexcrichton** [comment]
@Mark-Simulacrum how come you suggested that? That should (like some others related to it) be an internal Cargo environment variable that isn't intended for use elsewhere.

**Comment by Mark-Simulacrum** [comment]
I did realize it was intended for Cargo-internal use but rustbuild is somewhat closely tied in anyway; I agree it's not too ideal of a state though. I mostly intended it as "this is one way" vs. "this is the right way" but perhaps I was misunderstood / that intent wasn't realized in "need to implement a more public option"

**Comment by eddyb** [comment]
I'm experimenting with `__CARGO_TEST_ROOT`-less solutions in #56194.

**Comment by eddyb** [comment]
@alexcrichton Given https://github.com/rust-lang/rust/pull/56194#issuecomment-441358535, what options do we have?

**Comment by alexcrichton** [comment]
@Mark-Simulacrum oh that's what the double underscores were supposed to imply 😢 

There just wasn't a way to fix this when rustbuild was originally written, hence the usage of `src` and not the root of the repository. I would not personally want to solve that problem by reaching into the internals of Cargo. 

AFAIK Cargo isn't actually that tied to rustbuild in the sense that rustbuild is only relying on public APIs of Cargo and other official ways to use it. There's been some bugs here and there over time but that's just because rustbuild exercises so much functionality.

@eddyb I don't know of solutions off the top of my head, which is why I never tried to move `Cargo.toml` out of `src`.

**Comment by eddyb** [comment]
Given that https://github.com/rust-lang/rust/pull/56194 worked, *including* unbreaking RLS' tests, I'll close this and revert rust-lang/rls#1138.

**Pull request closed without merging**
