### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
4 commits in 7bf43f028ba5eb1f4d70d271c2546c38512c9875..84b7041fd2745ee6b3b4a150314f81aabb78e6b2
2023-04-10 16:01:41 +0000 to 2023-04-13 20:08:40 +0000
- Stabilize `cargo logout` (rust-lang/cargo#11950)
- Add more information to HTTP errors to help with debugging. (rust-lang/cargo#11878)
- Use registry.default for login/logout (rust-lang/cargo#11949)
- Change -C to be unstable (rust-lang/cargo#11960)

### CODE REVIEW

**Comment by weihanglo** [comment]
r? @ehuss

rust-lang/cargo#11949 sneaked in. Do we want to make it into 1.70.0 as well?

**Comment by ehuss** [comment]
Yea, I think that's fine to include.  Can you also pull in https://github.com/rust-lang/cargo/pull/11950 once it merges?

**Comment by weihanglo** [comment]
Updated. I'll merge this now.

@bors r+ p=1

**Comment by ehuss** [comment]
Thanks!

**Pull request merged**
