### PR TITLE
Make write/print macros eagerly drop temporaries

### LINKED ISSUE #96434: [regression] println borrow check errors
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/Acrylic125.rust-tutorial/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/DreamLarva.learn-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/Francososa.threads/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/Jaco26.rust_chess/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/fangerm.adventofcode2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/reg/yaap-0.0.2/log.txt

https://github.com/rust-lang/rust/pull/94868 is likely cause (cc @dtolnay)

### PR DESCRIPTION
**Pull request by dtolnay**
This PR fixes the 2 regressions in #96434 (`println` and `eprintln`) and changes all the other similar macros (`write`, `writeln`, `print`, `eprint`) to match the old pre-#94868 behavior of `println` and `eprintln`.

argument position | before #94868 | after #94868 | after this PR
--- |:---:|:---:|:---:
`write!($tmp, "…", …)` | :rage: | :rage: | :smiley_cat:
`write!(…, "…", $tmp)` | :rage: | :rage: | :smiley_cat:
`writeln!($tmp, "…", …)` | :rage: | :rage: | :smiley_cat:
`writeln!(…, "…", $tmp)` | :rage: | :rage: | :smiley_cat:
`print!("…", $tmp)` | :rage: | :rage: | :smiley_cat:
`println!("…", $tmp)` | :smiley_cat: | :rage: | :smiley_cat:
`eprint!("…", $tmp)` | :rage: | :rage: | :smiley_cat:
`eprintln!("…", $tmp)` | :smiley_cat: | :rage: | :smiley_cat:
`panic!("…", $tmp)` | :smiley_cat: | :smiley_cat: | :smiley_cat:

Example of code that is affected by this change:

```rust
use std::sync::Mutex;

fn main() {
    let mutex = Mutex::new(0);
    print!("{}", mutex.lock().unwrap()) /* no semicolon */
}
```

You can see several real-world examples like this in the Crater links at the top of #96434. This code failed to compile prior to this PR as follows, but works after this PR.

```console
error[E0597]: `mutex` does not live long enough
 --> src/main.rs:5:18
  |
5 |     print!("{}", mutex.lock().unwrap()) /* no semicolon */
  |                  ^^^^^^^^^^^^---------
  |                  |
  |                  borrowed value does not live long enough
  |                  a temporary with access to the borrow is created here ...
6 | }
  | -
  | |
  | `mutex` dropped here while still borrowed
  | ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `MutexGuard`
```

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I suppose we want T-libs-api FCP here since this affects stable behavior, but r=me on the PR itself.

Also nominating for beta backport.

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

In the table above, I think everything other than the 1st and 3rd rows are an obvious improvement. These are all equivalent to #64856.

The 1st and 3rd row (how to treat the "writer" argument of `write!` and `writeln!`) are not as obvious. In particular I don't see a way to simultaneously support both of the following situations:

```rust
use std::fmt;

fn needs_late_drop() {
    struct Mutex;
    struct MutexGuard<'a>(&'a Mutex);

    impl<'a> MutexGuard<'a> {
        fn write_fmt(&self, _args: fmt::Arguments) -> &Self {
            self
        }

        fn lol(&self) {}
    }

    // NEEDS LATE DROP. Needs the MutexGuard temporary to drop at the nearest
    // semicolon _outside_ the write macro.
    let mutex = Mutex;
    write!(MutexGuard(&mutex), "").lol();
}

fn needs_early_drop() -> fmt::Result {
    struct Mutex;
    struct MutexGuard<'a>(&'a Mutex);

    impl<'a> Drop for MutexGuard<'a> {
        fn drop(&mut self) {}
    }

    impl<'a> MutexGuard<'a> {
        fn write_fmt(&self, _args: fmt::Arguments) -> fmt::Result {
            Ok(())
        }
    }

    // NEEDS EARLY DROP. Needs the MutexGuard temporary to drop at a semicolon
    // _inside_ of the write macro.
    let mutex = Mutex;
    write!(MutexGuard(&mutex), "") /* no semicolon */
}
```

If `write!` drops the writer inside of the macro, then `needs_late_drop` fails with:

```console
error[E0716]: temporary value dropped while borrowed
  --> src/main.rs:18:12
   |
18 |     write!(MutexGuard(&mutex), "").lol();
   |     -------^^^^^^^^^^^^^^^^^^-----
   |     |      |
   |     |      creates a temporary which is freed while still in use
   |     temporary value is freed at the end of this statement
   |     borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value
```

If `write!` does not drop the writer inside of the macro, then `needs_early_drop` fails with:

```console
error[E0597]: `mutex` does not live long enough
  --> src/main.rs:38:23
   |
38 |     write!(MutexGuard(&mutex), "") /* no semicolon */
   |            -----------^^^^^^-
   |            |          |
   |            |          borrowed value does not live long enough
   |            a temporary with access to the borrow is created here ...
39 | }
   | -
   | |
   | `mutex` dropped here while still borrowed
   | ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `needs_early_drop::MutexGuard`
```

In either case the fix required by the programmer is the same: just make a `let` for the writer.

```diff
-    write!(MutexGuard(&mutex), "").lol();
+    let writer = MutexGuard(&mutex);
+    write!(writer, "").lol();
```

```diff
-    write!(MutexGuard(&mutex), "") /* no semicolon */
+    let writer = MutexGuard(&mutex);
+    write!(writer, "") /* no semicolon */
```

My opinion is that in the two functions above, `needs_early_drop` is the one that should compile successfully and `needs_late_drop` is the one that should not. My rationale is that `needs_early_drop` is a situation that can happen with the ordinary io::Write and fmt::Write signatures (`fn write_fmt(&mut self, Arguments) -> io::Result<()>` and `fn write_fmt(&mut self, Arguments) -> fmt::Result`) while `needs_late_drop` is a situation that occurs only in contrived code with a highly unusual custom signature for `write_fmt`.

**Comment by joshtriplett** [comment]
@dtolnay Seeking clarification: can this ever change the semantics of *existing* code by changing when drop happens, or can it only ever make code that didn't compile start compiling.

**Comment by dtolnay** [comment]
Yes, it's about moving drops from the nearest end of statement outside the macro to inside the macro. So for example:

```rust
use std::fmt::{self, Display};
use std::ops::Add;

struct X(usize);

impl Display for X {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        formatter.write_str("X")
    }
}

impl Add<X> for () {
    type Output = ();
    fn add(self, _: X) -> Self::Output {}
}

impl Drop for X {
    fn drop(&mut self) {
        print!("{}", self.0);
    }
}

fn main() {
    print!("{}", X(0)) + X(1);
}
```

would go from `X10` to `X01`.

**Comment by dtolnay** [comment]
Un-nominating for backport and nominating #96490 instead.

Both PRs can land in nightly without conflicting, but only #96490 needs to be backported I think.

**Comment by dtolnay** [comment]
Failure is rustdoc-gui being flaky, unrelated to this PR. https://github.com/rust-lang/rust/issues/93784
```console
/checkout/src/test/rustdoc-gui/escape-key.goml escape-key... FAILED
[ERROR] (line 6) Error: The following CSS selector "#search h1" was not found: for command `wait-for: "#search h1" // The search element is empty before the first search `
```

**Pull request merged**
