### PR TITLE
Add fuzzing and loom to well-known cfgs

### PR DESCRIPTION
**Pull request by saethlin**
Just like `miri`, the cfgs `fuzzing` and `loom` are used for ecosystem-wide coordination. These are by definition well-known, so they should be included in the list.

### CODE REVIEW

**Comment by Nadrieril** [comment]
Implementation looks good. I don't know the policy for such changes though. @Urgau you seem to know about this :D wdyt?

**Comment by Urgau** [comment]
I have mixed feelings about adding those, not necessarily for the same for both.

First this would diverge from the T-compiler [FCP of the feature](https://github.com/rust-lang/rust/issues/82450#issuecomment-1965260165) where the rule that was proposed was:
>  1. User facing _(nightly or not)_ (rational: internal cfgs are by their name not to be shown)
>  2. Set by a **Rust Toolchain tool** (rational: `rustc` is not the only tool that sets cfgs, `rustdoc` sets `doc` and `doctest`, `cargo-miri` sets `miri`, docs.rs sets `docsrs`, ...)
> 3. Must be an immutable set of names and values (rational: if it's not immutable, `rustc` cannot possibly know the what to add; this excludes Cargo `feature` cfg)

As far as I know neither of them as set by any *Rust Toolchain tool*, failing the second point.

Secondly those two cfgs are very specific are IMO not very well known by the broad community and including them by-default for everyone is a really high bar that I don't think neither of them quite reach.

Thirdly they seems both related to crates.io (maybe `fuzzing` a bit less, but `loom` definitely) and including them in rustc seems very weird for projects that don't use crates.io or Cargo at all, like the Rust for Linux project.

Fourthly including `loom` would give some kind of "recommendation" (even if not intended) and would make the project liable for another project that we don't control.

However it seems that there is some desire in having them as well known cfgs, so I could be sold on having them as *compatibility cfg* (so no other ecosystem cfgs in the future).

One thing that would with my first and second would be to make them Cargo well known cfgs, like [`docsrs`](https://github.com/rust-lang/cargo/blob/cfbc4b766213a6288f7cdbb7ad5f15329eeacf13/src/cargo/core/compiler/mod.rs#L1351-L1358) is.

@rustbot label -S-waiting-on-review +S-waiting-on-author
cc @epage

----

As for the implementation in this PR it's missing two anti-regressions entries in [`well-known-values.rs`](https://github.com/rust-lang/rust/blob/bc2bb4f4e46e0c6584edb3ee9831453f093ffb8a/tests/ui/check-cfg/well-known-values.rs#L28-L29).

**Comment by epage** [comment]
Based on the conversation in #124800, I think having a PR up is premature.

**Comment by saethlin** [comment]
> As far as I know neither of them are set by any _Rust Toolchain tool_, failing the second point.

The point being raised in issues is that adding a build script to correct the false positives is an undue burden on the ecosystem, because every maintainer separately has to teach Cargo/rustc about all the well-known ecosystem cfgs that they use. It is entirely unclear to me if this was FCP'd with that concern in mind. I certainly can't find any evidence that it was discussed, so it seems rather dubious to point at the FCP here.

I'm happy to bring this up in a compiler team meeting, unless someone can point me to where the compiler team already discussed this concern.

And I see @workingjubilee has voiced the same feedback as I have, independently https://github.com/rust-lang/rust/issues/124800#issuecomment-2096947209

**Comment by epage** [comment]
imo this is a discussion better had on an Issue, rather than a PR

**Comment by saethlin** [comment]
> One thing that would help with my first and second point, would be to make them Cargo well known cfgs

Closing because of this. I agree. I might do a similar PR to Cargo later.

**Pull request closed without merging**
