### PR TITLE
Publish compiletest as a rustc-tools component

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
The goal of this PR is to just get the publishing working in a way that'll hopefully let clippy consume the resulting binary without too much trouble. If there's a desire to use compiletest as a library rather than a binary, I see no reason why we couldn't publish an rlib/.so/whatever, just like we do for std or the rustc libraries, that'll just take more plumbing. My hope is that the binary is a sufficient interface for now, since that works for rustc itself (bootstrap calls the binary), but if not, we can modify this PR to publish an rlib into the sysroot too, when the compiletest component is installed.

It looks like as-is clippy does use the library compiletest-rs as a library for its testing, I would need to do more digging to tell if that's an intrinsic dependency or not.

cc @Manishearth @oli-obk https://github.com/rust-lang/compiler-team/issues/536

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
I think we should hold off on merging this until we confirm with the clippy team this is the approach they want to take. No objection to doing this, just don't want it to be wasted work.

**Comment by Mark-Simulacrum** [comment]
Sure, that's fine with me -- in particular clarity on library vs. binary I think would be good.

Mostly wanted to open this so we can get a try build + a "fake" nightly published from it so it's easier to experiment with (for example) a clippy PR migrating to this.

**Comment by Manishearth** [comment]
cc @rust-lang/clippy

**Pull request closed without merging**
