### PR TITLE
Update RLS and Rustfmt

### LINKED ISSUE #74811: `rls` no longer builds after rust-lang/rust#74653
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#74653, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @petrochenkov, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### LINKED ISSUE #74812: `rustfmt` no longer builds after rust-lang/rust#74653
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#74653, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @petrochenkov, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by Xanewok**
Closes #74811
Closes #74812

r? @calebcartwright

### CODE REVIEW

**Comment by Xanewok** [comment]
Ran `./x.py test src/tools/{rls,rustfmt}` locally and all is green, so hopefully CI will agree as well.

**Review by calebcartwright — APPROVED** [review]
LGTM

**Comment by calebcartwright** [comment]
If there's a bors incantation needed from me (and I have requisite rights) please let me know

**Comment by Dylan-DPC** [comment]
will take care of it this time :P 

@bors r+ p=1

**Comment by calebcartwright** [comment]
Thanks @Dylan-DPC :smile: Can I do a `bors r+` with a PR like this that gets assigned to me? Sorry haven't done any reviews here before and not entirely sure how the `r+` or `r=` permissions work

**Pull request merged**
