### PR TITLE
change `download-ci-llvm` default from `if-unchanged` to `true`

### LINKED ISSUE #130515: x setup tries to check out src/llvm-project
This takes quite a while and will end up being wasted effort if the user ends up selecting a profile which uses download-ci-llvm=true anyway.

### PR DESCRIPTION
**Pull request by onur-ozkan**
Since https://github.com/rust-lang/rust/pull/129473 and https://github.com/rust-lang/rust/pull/130202, using `download-ci-llvm=true` is now the better default and it also fixes #130515.

### CODE REVIEW

**Comment by Kobzol** [comment]
Why does the default behave differently than setting true explicitly?

**Comment by onur-ozkan** [comment]
> Why does the default behave differently than setting true explicitly?

The default is "if-unchanged" which fetches the LLVM submodule, but setting it to `true` does not.

**Comment by Kobzol** [comment]
I meant after this PR. I thought that when you not set download-ci-llvm, it will behave as if you set it to true. But the code paths for "unset" and "true" look different.

**Comment by onur-ozkan** [comment]
Hmm. Yeah, that makes sense. Should we set it `true` unconditionally if it's not provided from `config.toml`?

**Comment by Kobzol** [comment]
Making it behave differently would introduce essentially another mode and would be unintuitive. When it's not set, it should IMO behave exactly thr same as if the user used "true".

We can just unify the logic by restructuring the pattern matching, I suppose?

**Comment by Kobzol** [comment]
I expressed myself badly :laughing: What I meant was that the code executed if `(self.channel == "dev" || self.download_rustc_commit.is_some())` holds should be the same as the code executed if the user sets `true`. Before, that was not the case, because the `llvm::is_ci_llvm_available(self, asserts)` call was missing.

That being said, just using true as the actual default value simplifies things, so if it's working, that's even better. I don't suppose that beta or stable contains local modifications to LLVM, so it should be fine, hopefully.

You can r=me once CI is green.

**Comment by onur-ozkan** [comment]
> That being said, just using true as the actual default value simplifies things, so if it's working, that's even better. I don't suppose that beta or stable contains local modifications to LLVM, so it should be fine, hopefully.

AFAIK building it from scratch is truly necessary only for distribution runners and the "dist" profile already overrides the default with `false`.

**Pull request merged**
