### PR TITLE
Error table reformatting (bikeshed demolished)

### PR DESCRIPTION
**Pull request by ijackson**
This is the first (no-overall-functional-change) part of #79965.  I am splitting it out because:
 * It generates many bad merge conflicts so I want to get it merged
 * There is a bikeshed issue blocking it which needs to be resolved one way or the other

This MR has <strike>three</strike> two kinds of change:
 1. Alphabetically sort various tables of `ErrorKind`s
 2. `use ErrorKind::*` and remove a lot of individual `ErrorKind::` qualifiers.

There was also a bikeshed issue which was impeding the progress of #79965.  <strike>I would like to resolve it one way or the other.  I request that @T-libs either (a) decide to merge this MR, accepting my bikeshed colour, or (b) formally close this MR to indicate a positive decision to colour the bikeshed the other way.  In case (b) I will resubmit it with the bikeshed repainted.</strike>

As discussed below, the bikeshed is now painted the colour which seems most popular.  I think the contents of this MR are now uncontroversial.

<strike>
### Bikeshed discussion

As might be expected with a style discussion, I have strong feelings :-).  While I recognise that that's (as ever) rather disproportionate to the issue at hand, I want to put forward my arguments in favour of my preferred colour.

I think the best argument is to tell a story about how item (2) - the defensive typesafety - came to be in this MR.  #79965 has been through a lot of discussion and modification.  Originally, it did not have the tabular reformatting.  I considered it but felt it would be controversial (and I was right...)

However, the discussion in #79965 produced many changes.  New error kinds, suggestions to merge or split them, etc.   I kept having to rework the mappng tables.  I found the non-tabular format meant I couldn't see the trees for the wood.  It was too hard to work with.

So I decided to pay the price of the controversy, and to propose to reformat these tables.  I naturally used semiautomatic means to do the actual reformatting.

After I had reformatted the Windows mapping table I found that it looked like this:
```
+        c::ERROR_TOO_MANY_LINKS                         => return TooManyLinks,
+        c::ERROR_FILENAME_EXCED_RANGE                   => FilenameTooLong,
```

This is a bug.  This bug was rendered almost invisibile by the previous formatting: everything being higgledy-piggeldy had obscured the underlying regularity of the code.  That made it easy for me to add an irregular, and incorrect, entry.

<strike>Since I love using Rust's type system to defend against my mistakes, I also added the defensive programming commit (item 2 in my bullet list).  But if I had not reformatted this, I wouldn't have spotted this and quite possibly neither would anyone else.</strike>

As @dtolnay points out, this bug would be caught by the type system when the code is compiled for Windows in the CI, even though it was not detected in my local build for Unix.  However, the difference in the visibility of the mistake is still very striking and IMO demonstrates that the non-tabular layout is seriously inferior.

#### Countrerarguments

 * *Tabular formats involve noisy and disruptive shuffling when the maximum size of entries changes.*  This is true if the table is made dense, with every column just wide enough for its contents (and if one insists on not having any deviations from the tabular layout).  However, in my proposal I have made the columns deliberately very wide so that they will fit foreseeable new entries.  Such a reformatting cannot be ruled out of course, but it seems to me that it will happen very rarely.
 * *This is contrary to Rust community style norms*.  I don't think it is.  There are existing places in `rust-lang/rust` where tables are rendered as-such.  Also, multiple people have requested that rustfmt gain a feature to more usefully manage the formatting of tabular code.
 * *Disabling rustfmt will make it harder to maintain these functions*.  There is almost no code in these functions other than the mapping tables.  It is true that adding a new `ErrorKind` will now involve manually inserting the right number of spaces.  I think this is a price well worth paying for being able to see what we're doing.
</strike>

### CODE REVIEW

**Review by kornelski — APPROVED** [review]

**Comment by joshtriplett** [comment]
I think, rather than push back on this, I'll just abstain and let others on @rust-lang/libs decide.

@rfcbot merge

**Comment by BurntSushi** [comment]
I don't have strong opinions either way myself, but the table is somewhat long, so I do find it being in a tabular format to make reading it marginally nicer. Particularly if we're going to be adding more variants soon. Although I am not fond of sprinkling `#[rustfmt::skip]` annotations everywhere. 

Also, this probably seems like a libs-impl decision. Not sure if they are spun up yet. I don't see a team name to ping.

**Comment by yaahc** [comment]
Reiterating [my comment](https://github.com/rust-lang/rust/pull/79965#issuecomment-840144649) from the parent thread, I'm still generally against the special cased tabular format change, but I have no issues with the alphabetical sorting.

> This is contrary to Rust community style norms. I don't think it is. There are existing places in rust-lang/rust where tables are rendered as-such. Also, multiple people have requested that rustfmt gain a feature to more usefully manage the formatting of tabular code.

Can you link the examples you're referring too? I couldn't find any examples of `rustfmt::skip` being applied to a match statement in std/core.

**Comment by ijackson** [comment]
> Can you link the examples you're referring too? I couldn't find any examples of `rustfmt::skip` being applied to a match statement in std/core.

In `library/` there are `rustfmt::skip`s for:
 * `tables of [u8]` with rectangular layout https://github.com/rust-lang/rust/blob/69b352ef7749825abde2d8f8e31c05f681e61a10/library/core/benches/ascii.rs#L280 https://github.com/rust-lang/rust/blob/69b352ef7749825abde2d8f8e31c05f681e61a10/library/std/src/io/tests.rs#L507
 * `let .. = "multi-line string literal"` and`let something = vec![ "multi-line", "string", "literals"` with ad-hoc hand formatting https://github.com/rust-lang/rust/blob/69b352ef7749825abde2d8f8e31c05f681e61a10/library/std/src/backtrace/tests.rs#L53
 * `vec![ (vec!...` structure with custom layout https://github.com/rust-lang/rust/blob/69b352ef7749825abde2d8f8e31c05f681e61a10/library/std/src/io/tests.rs#L507
 * `&[&str]` wrapped into paragraphs https://github.com/rust-lang/rust/blob/69b352ef7749825abde2d8f8e31c05f681e61a10/library/term/src/terminfo/parser/compiled.rs#L15

I haven't done a full survey of the rest of `rust-lang/rust` but a search for use on `match` statements did find quite a few uses on match statements eg https://github.com/rust-lang/rust/blob/69b352ef7749825abde2d8f8e31c05f681e61a10/src/tools/clippy/clippy_lints/src/double_comparison.rs#L70 and functions containing just match statements https://github.com/rust-lang/rust/blob/69b352ef7749825abde2d8f8e31c05f681e61a10/src/tools/clippy/tests/ui/implicit_return.rs#L20

**Comment by ijackson** [comment]
> Reiterating [my comment](https://github.com/rust-lang/rust/pull/79965#issuecomment-840144649) from the parent thread, I'm still generally against the special cased tabular format change

I want to reiterate that my primary goal here is to get a decision one way or the other.

**Comment by BurntSushi** [comment]
> I want to reiterate that my primary goal here is to get a decision one way or the other.

Even the folks (including myself) who said they wouldn't block this said they were hesitant about it. And others have chimed in with stronger feelings. As a suggestion if I were in your shoes, I'd change the PR to sort the variants lexicographically and just let the table formatting drop.

**Comment by dtolnay** [comment]
@rfcbot fcp cancel

**Comment by ijackson** [comment]
I think this is the decision I was asking for.  I will run rustfmt on this branch and rebase it.

**Comment by ijackson** [comment]
I have rebased onto #/85746.  I have not yet done a local build test, since my tree is a bit out of date and would probably spend an hour rebuilding llvm :-).  I'm hoping the CI will spot any build problems.

I did check that the MR contains only the things I expected, with the following runes:
```
$ git-diff io-error-other | grep '^-' | perl -pe 's/ErrorKind:://g; s/^-/+/' |sort >min
$ git-diff io-error-other | grep '^+' |sort >plus
$ diff -ub min plus |less
```

This shows:
 * Swapped `libc::EACCES | libc::EPERM` (to make them alphabetical)
 * Added `use ErrorKind::*` lines

By design this set of runes does not report reordering or removal of `ErrorKind::` prefixes.

**Comment by joshtriplett** [comment]
Looks good to me. There's a stray space after `libc::EACCES | libc::EPERM` that's causing the `tidy` check to fail; with that fixed, this is ready to merge.

**Comment by ijackson** [comment]
> Looks good to me. There's a stray space after `libc::EACCES | libc::EPERM` that's causing the `tidy` check to fail; with that fixed, this is ready to merge.

Fixed.  I haven't squashed that to simplify working on #79965.

NB that of course this MR should not be merged until the FCP for #85746 completes.  (I'm sure you're aware of that but it seemed worth mentioning.)

**Comment by joshtriplett** [comment]
@ijackson Of course. But as soon as the FCP completes, I intend to r+ both PRs.

**Pull request merged**
