### PR TITLE
`ty::tls` cleanups

### PR DESCRIPTION
**Pull request by Noratrieb**
Pull it out into a separate file, make the conditional compilation more obvious and give the internal functions better names.

Pulled out of #106311

r? cjgillot

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Shouldn't have a perf impact but just to be sure
@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
Oops, small mistake, it needs to be `ty::context::tls`, `ty::tls` doesn't work.
@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
This is noise that also showed up in other places this week, https://github.com/rust-lang/rustc-perf/pull/1516 (for example [here](https://perf.rust-lang.org/compare.html?start=005fc0f00f2d4ceaf523b67a8f9c5665b8ac5baf&end=52372f9c71d8ade4cb815524f179119656f0aa2e&stat=instructions:u)).

**Comment by cjgillot** [comment]
To verify this is noise.
@bors try @rust-timer queue

**Pull request merged**
