### PR TITLE
Remove SimpleDefKind

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Now that rustc_query_system depends on rustc_hir, we can just directly make use of the regular DefKind.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

(But even without a performance impact, might be a nice small refactor)

**Comment by Mark-Simulacrum** [comment]
Looks like no significant impact on overall runtimes, probably only worth it if it looks like a nice refactor regardless of bootstrap performance impact (which I suspect is there, just tiny). Might also try adding an inline(never) which could help.

**Comment by cjgillot** [comment]
`rustc_query_system` depends on `rustc_hir`. We can remove the `SimpleDefKind` datatype and use `DefKind` directly. Hence dropping completely `to_simple_def_kind`.

**Comment by Mark-Simulacrum** [comment]
FWIW, it looks like the only usage of SimpleDefKind is some [slight adjustments to cycle diagnostics](https://github.com/rust-lang/rust/blob/30b3f35c420694a4f24e5a4df00f06073f4f3a37/compiler/rustc_query_system/src/query/job.rs#L558-L575). I'm not personally convinced those are worth it -- but maybe they are. In any case, something to be considered separately I suppose, for now this just refactors to drop SimpleDefKind in favor of DefKind.

@bors try @rust-timer queue

I suspect this'll be largely performance neutral or a slight hit -- DefKind is likely larger by a few bytes at least -- but likely to not matter much.

**Review by davidtwco — APPROVED** [review]

**Pull request merged**
