### PR TITLE
Target builds for older macOS

### LINKED ISSUE #40481: No longer able to target older macOS
I'm using `MACOSX_DEPLOYMENT_TARGET=10.7` and `-Wl,-macosx_version_min,10.7` in my Rust application. In current nightlies this no longer works and I see a bunch of messages like:

```
ld: warning: object file (target/dist/x86_64-darwin/objs/absvdi2.o) was built for newer OSX version (10.12) than being linked (10.7)
```

and

```
ld: warning: linker symbol '$ld$hide$os10.4$___absvdi2' hides a non-existent symbol '___absvdi2'
```

The last good nightly was 2017-02-13. It was suggested that this may be due to a shift to a build system.

### PR DESCRIPTION
**Pull request by wagenet**
Fix #40481

### CODE REVIEW

**Comment by alexcrichton** [comment]
Is... travis not listening?

**Comment by wagenet** [comment]
@alexcrichton tried forcing a new commit to see if it picks it up.

**Comment by mzji** [comment]
Travis is missing pull requests: [status](https://www.traviscistatus.com/)

**Comment by wagenet** [comment]
Retrying with #40489.

**Comment by wagenet** [comment]
So the tests run fine until they time-out after 3 hours. They're not stuck and are still making progress at this point.

**Comment by alexcrichton** [comment]
@wagenet oh right yeah sorry now that I think about it I don't think we've gotten macs-on-PRs working yet (for... reasons unknown).

In any case I think it got past everything just fine that it needed to (bootstrapping the compiler), so I think we're in the clear here for this PR as-is.

So this gets the compiler itself to 10.8 but libstd as well. Would you still like to get libstd to 10.7 in this PR or would you like to save that for a follow-up PR?

**Comment by alexcrichton** [comment]
I'm also flagging this for a backport to beta as https://github.com/rust-lang/rust/issues/40481 affects beta

**Comment by alexcrichton** [comment]
@bors: r-

Oh actually can the `ALLOW_PR=1` be removed?

**Comment by alexcrichton** [comment]
@bors: p=1

(beta nominated)

**Comment by alexcrichton** [comment]
@bors: retry

* osx timeout https://github.com/rust-lang/rust/issues/40571

**Comment by alexcrichton** [comment]
@bors: retry

* spurious sccache failure https://github.com/rust-lang/rust/issues/40240

**Pull request merged**
