### PR TITLE
PhantomData layout guarantees

### PR DESCRIPTION
**Pull request by joshlf**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
The documentation already guarantees in the first sentence that PhantomData is a ZST. I'm going to r? libs-api though for a double check, I personally don't think we necessarily need an FCP here (more of a clarification rather than new surface area IMO).

**Comment by joshlf** [comment]
Thanks for the quick reply!

> The documentation already guarantees in the first sentence that PhantomData is a ZST.

Is your concern that this documentation is redundant, or are you just clarifying why this doesn't require FCP?

In either case, it's worth calling out that the alignment guarantee is new AFAICT. [A ZST can have alignment > 1](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=98bda41888dd7eb8eea5e21ade8a0558).

**Comment by Mark-Simulacrum** [comment]
No, only the first line about size is redundant (but also fine and reasonable to have together like this).

In practice I think the ask for no alignment changes to phantomdata feels *new* but not really, since changing it would probably break expectations anyway.

**Comment by ChrisDenton** [comment]
Would `#[repr(align(...))]` not be shown in the generated docs?

**Comment by joshlf** [comment]
> Would `#[repr(align(...))]` not be shown in the generated docs?

`repr(align(...))` only provides a lower bound, not an upper bound, so it's a moot point. That said, there's also no agreement about which attributes are considered part of a type's API. For example, the [`Wrapping`](https://doc.rust-lang.org/nightly/core/num/struct.Wrapping.html) type is defined as:

```rust
#[repr(transparent)]
pub struct Wrapping<T>(pub T);
```

...and yet, there's still a "Layout" section which documents what guarantees are made about `Wrapping`'s layout.

**Comment by m-ou-se** [comment]
The 'align == 1' part is new to this documentation, so let's do an FCP to be sure.

@rfcbot merge

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
