### PR TITLE
Link from literals to their encoding

### LINKED ISSUE #22152: Document float encoding in reference
How floats are encoded needs documentation. I suppose it would go in [reference: floating point](http://doc.rust-lang.org/reference.html#floating-point-literals). If not there, at least somewhere.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #22152

### CODE REVIEW

**Comment by huonw** [comment]
I don't quite understand what is meant by "encoding" here.

**Comment by steveklabnik** [comment]
That they are  `IEEE 754-2008` floats, specifically. As opposed to some other representation.

**Comment by steveklabnik** [comment]
@huonw ping? does that make sense?

**Comment by huonw** [comment]
> That they are IEEE 754-2008 floats, specifically. As opposed to some other **representation**.

Hm, I think I prefer that as a word; encoding feels a bit too much like e.g. encoding to/from json. Thoughts? (If you agree, r=me with representation instead.)

**Comment by steveklabnik** [comment]
@huonw agreed, and done. Thanks!

**Pull request merged**
