### PR TITLE
UTF-8 validation: Compute block end upfront

### PR DESCRIPTION
**Pull request by bluss**
Simplify the conditional used for ensuring that the whole word loop is
only used if there are at least two whole words left to read.

This makes the function slightly smaller and simpler, a 0-5% reduction
in runtime for various test cases.

### CODE REVIEW

**Comment by sfackler** [comment]
This seems fine to me, though the changes seem minimal enough that it's a bit weird that LLVM can't do as well with the original implementation.

**Comment by steveklabnik** [comment]
ping @sfackler , are you fine enough with this to merge it?

**Comment by bluss** [comment]
Thank you :) I do think the simplification of the conditional is a needed cleanup.

**Comment by alexcrichton** [comment]
@bors: retry

* #38878

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/39003

**Pull request merged**
