### PR TITLE
IoSlice/IoSliceMut should be Send and Sync

### LINKED ISSUE #70308: IoSlice and IoSliceMut should be Sync and Send
Since they contain `*mut u8` on many platforms, they are neither `Sync` + `Send` by default, but they're semantically just slices so they should!

### PR DESCRIPTION
**Pull request by withoutboats**
Closes #70308

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I wonder if this is the right approach - I would personally prefer to

**Comment by Mark-Simulacrum** [comment]
Hm, I wonder if this is the right approach - I would personally prefer to add them to each sys module where it's easier to audit (particularly when adding new things). What do you think about that? (Obviously more work)

**Comment by sfackler** [comment]
I think adding them at the top level is the right way to go - we're going to inevitably have this problem on random obscure targets going forward otherwise. The types are semantically just byte slices, so I can't imagine there would exist a platform that could possibly need to not have these impls.

**Comment by Mark-Simulacrum** [comment]
Hm, seems like the random target platform would be avoided with an assert that it's Send/Sync. But I agree that in this case it probably won't matter so I'm happy to approve this (with CI passing); r=me

**Pull request merged**
