### PR TITLE
Add rustc UX guidelines.

### PR DESCRIPTION
**Pull request by Havvy**
See https://github.com/rust-lang/rfcs/pull/1246 for discussion.

### CODE REVIEW

**Comment by brson** [comment]
I don't have an opinion about whether to add this, or the contents, but the doc directory is for user documentation, and it is converted to html and published. This does not look like that kind of documentation. I don't have a better suggestion of where to put it offhand, but it seems like wiki material to me.

cc @rust-lang/compiler 

r? @pnkfelix

**Comment by tshepang** [comment]
Maybe make it part of CONTRIBUTING.md

**Comment by Havvy** [comment]
It shouldn't be inside CONTRIBUTING.md, but there should be a link to it from there.

**Comment by nikomatsakis** [comment]
Dev dungeon!

**Comment by Havvy** [comment]
So, what's actually blocking on this?

Final Comment Period for the RFC?

Choosing which directory to put this file?

**Comment by nrc** [comment]
@Havvy where to put it - in particular it seems unclear who is going to make that decision :-(

**Comment by pnkfelix** [comment]
Well, what's really blocking it is that it was assigned to me and I need to bother to write `r+` ... honestly, we can always move it somewhere else if a better location presents itself.

**Comment by Havvy** [comment]
:heart: :green_heart: :yellow_heart: :blue_heart: :purple_heart:

**Pull request merged**
