### PR TITLE
adding lastest Bitrig snapshot by hand

### PR DESCRIPTION
**Pull request by dhuseby**
@alexcrichton this adds the latest Bitrig snapshot.  Please upload the corresponding snapshot: https://github.com/dhuseby/rust-cross-bitrig/blob/master/snapshots/rust-stage0-2015-03-17-c64d671-bitrig-x86_64-41de2c7a69a1ac648d3fa3b65e96a29bdc122163.tar.bz2

### CODE REVIEW

**Comment by dhuseby** [comment]
@alexcrichton any chance of this getting merged and the snapshot uploaded some time today?  I'm trying to get the Bitrig buildbot successfully completing builds.  I am waiting for this to go in before I can get back to fixing the issues the test pass found.

**Comment by alexcrichton** [comment]
Doing my best to land this as part of the rollup :)

**Comment by dhuseby** [comment]
@alexcrichton awesome, thank! do rollups happen daily?

**Comment by steveklabnik** [comment]
They happen whenever someone with commit initiates one, or when the queue is empty.

**Pull request merged**
