### PR TITLE
[stable] Add a few critical fixes to the 1.31.0 release

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR cherry-picks the following PRs to stable:

* #56467: Bump stack size to 32MB
* #56486: Propagate all closure requirements to the caller
* #56519: update edition guide

The changes will be included in the final 1.31.0 binary (to avoid a point release). To deploy the build to dev-static the old manifest needs to be removed from the bucket after the PR is merged.

cc @rust-lang/core @rust-lang/release @rust-lang/compiler 
r? @alexcrichton

### CODE REVIEW

**Comment by pietroalbini** [comment]
Added https://github.com/rust-lang/rust/pull/56519

@bors r+ p=1000

**Comment by Geal** [comment]
this might fix #55390, I'll test with this nightly

**Pull request merged**
