### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Noratrieb**
Successful merges:

 - #114079 (Use `upvar_tys` in more places, make it return a list)
 - #114335 (fix and extend ptr_comparison test)
 - #114347 (x.py print more detailed format files and untracked files count)
 - #114353 (Some parser and AST cleanups)
 - #114364 (Update cargo)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=114079,114335,114347,114353,114364)

### CODE REVIEW

**Comment by fmease** [comment]
#114253 failed CI: https://github.com/rust-lang/rust/pull/114253#issuecomment-1661932104

**Comment by lqd** [comment]
what do you mean ? #114253 is not r+ed nor in the rollup.

**Comment by Nilstrieb** [comment]
you messed up the number, but I see

**Comment by Nilstrieb** [comment]
it's #114353

**Comment by fmease** [comment]
yea, sorry copy/pasted the wrong thing, I meant #114353

**Comment by lqd** [comment]
Note that bors also messed up the rollup again, it mentions 5 PRs but has rolled up 3.

**Comment by Nilstrieb** [comment]
the follow-up got all 5: #114367 !!!

**Comment by Nilstrieb** [comment]
lol, #114353 was among the unlucky ones, so this rollup would have actually passed

**Pull request closed without merging**
