### PR TITLE
Move some tests to more reasonable directories - 7

### PR DESCRIPTION
**Pull request by c410-f3r**
cc #73494
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
issue-5791.rs -> can be removed, already tested in clashing-extern-fn.rs
expr-empty-ret.rs -> never_type
guards.rs -> match
issue-33498.rs -> match
enable-unstable-lib-feature.rs -> stability-attribute
backtrace-debuginfo.rs -> certainly not macros, not sure about the proper subdirectory, let's keep it in its old place
issue-41255.rs -> lint or match
issue-79744.rs -> lint
out-of-order-shadowing.rs -> macros
issue-78720.rs -> closures
use-self-in-inner-fn.rs -> resolve

(`binding` and `use` are confirmed to be garbage subdirectories)

Could you also update the test number limits in tidy?

**Comment by c410-f3r** [comment]
Done

**Comment by c410-f3r** [comment]
`enable-unstable-lib-feature`, `lint-stability` and `list-stability-deprecated` are all placed inside `lint` because of shared `aux-build:stability-cfg2.rs`.

**Pull request merged**
