### PR TITLE
slice: Stabilize IterMut::as_slice.

### LINKED ISSUE #58957: Tracking issue for slice::IterMut::as_slice and vec::Drain::as_slice
This issue tracks stabilization for 2 methods added in #58924:
- `core::slice::IterMut::as_slice`
- `alloc::vec::Drain::as_slice`

### PR DESCRIPTION
**Pull request by emilio**
Much like #72584.

As per #58957 there's no blocker for this, and I wanted to use this
today :-)

Closes #58957

### CODE REVIEW

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by pthariensflame** [comment]
Seems to need `relnotes`.

**Pull request merged**
