### PR TITLE
Rollup of leftover PRs in the queue

### PR DESCRIPTION
**Pull request by Manishearth**
I had most of these tested locally, why not  get them out of the way too?

### CODE REVIEW

**Comment by Manishearth** [comment]
```
---- [run-pass] run-pass/unwind-unique.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-unknown-linux-gnu/test/run-pass/unwind-unique.stage2-x86_64-unknown-linux-gnu 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<unnamed>' panicked at 'explicit panic', /home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/test/run-pass/unwind-unique.rs:18
thread '<main>' panicked at 'child thread None panicked', /home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/libstd/thread.rs:690

------------------------------------------

thread '[run-pass] run-pass/unwind-unique.rs' panicked at 'explicit panic', /home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/compiletest/runtest.rs:1466


---- [run-pass] run-pass/unwind-resource.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-unknown-linux-gnu/test/run-pass/unwind-resource.stage2-x86_64-unknown-linux-gnu 
stdout:
------------------------------------------
hiiiiiiiii
Hello!
About to send!
Sent!

------------------------------------------
stderr:
------------------------------------------
thread '<unnamed>' panicked at 'explicit panic', /home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/test/run-pass/unwind-resource.rs:35
thread '<main>' panicked at 'child thread None panicked', /home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/libstd/thread.rs:690

------------------------------------------

thread '[run-pass] run-pass/unwind-resource.rs' panicked at 'explicit panic', /home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/compiletest/runtest.rs:1466



failures:
    [run-pass] run-pass/unwind-resource.rs
    [run-pass] run-pass/unwind-unique.rs
```

**Comment by Manishearth** [comment]
Backed out the intermittent fix, added some more PRs so that this rollup stays beneficial.

**Comment by Manishearth** [comment]
(Not yet, need to push some fixes)

**Comment by Manishearth** [comment]
r+  e686fca

**Comment by Manishearth** [comment]
@bors: retry

*sigh* intermittents

**Comment by Manishearth** [comment]
Restarting on the rollup since stuff changed and Windows hates me.

**Comment by Manishearth** [comment]
@bors: r-

Oops, sorry, not an intermittent.

**Comment by Manishearth** [comment]
@bors: r+ 686648d

```
---- ops::Deref_0 stdout ----
	error: could not exec the linker `cc`: no such file or directory
error: aborting due to previous error
thread 'ops::Deref_0' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libsyntax/diagnostic.rs:151
```

Failure in a doctest, seems like an intermittent to me :/

**Comment by Manishearth** [comment]
@bors: try

Just in case, so that we can hammer out any failures on mac.

**Comment by Manishearth** [comment]
Seems to have merged into auto, not try. O.o

**Comment by barosl** [comment]
@Manishearth This is normal. Homu tests `try`ed PRs just as the normal PRs, using the `auto` branch. It just doesn't merge it. (So you didn't have to stop the other build.)

The intention of this behavior was to get the exactly same test results from both the normal procedure and the `try` procedure. But I was told that using `auto` requires much more resources than using the `try` branch, so I'm thinking of changing the behavior to use `try` instead.

The issue is tracked at barosl/homu#50, if you are interested. I already fixed it in my local repository, but didn't test it enough. I'm planning to push it soon, after the tests are done.

**Comment by barosl** [comment]
For now, you can just fast-forward the merge commit made by Homu (6c182b4) to `master`. As the exactly same tests are done, there would be no problems.

**Comment by Manishearth** [comment]
Thanks, @barosl :)

I closed the other PR because I was afraid that if those tests passed, homu would merge auto into master, and it would merge the wrong branch.

**Pull request merged**
