### PR TITLE
regression for issue 90847

### PR DESCRIPTION
**Pull request by cameron1024**
Adds a regression test for issue #90847

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This test seems like it may be in an odd directory? Could you move it to src/test/ui/const-generics/generic_const_exprs?

**Comment by JohnCSimon** [comment]
Ping from triage: 
@cameron1024

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot ready

**Comment by cameron1024** [comment]
Ah thanks for letting me know, didn't know about that 😁

**Pull request merged**
