### PR TITLE
Bump hashbrown to 0.4.0

### LINKED ISSUE #61357: hash_map::IterMut changed Send bounds with hashbrown
In 1.35, `IterMut`'s `Send` requires `K: Send`, but in 1.36-beta it requires `K: Sync`. Both are auto-derived, so it must be a change in their internals. Obviously, `hashbrown` is quite different than the old implementation.

https://doc.rust-lang.org/1.35.0/std/collections/hash_map/struct.IterMut.html#impl-Send
image

https://doc.rust-lang.org/beta/std/collections/hash_map/struct.IterMut.html#impl-Send
image

Ditto for `ValuesMut`. I'm not sure if there's any real impact in this, but it should be considered, and perhaps audit for other similar changes.

cc @Amanieu, as discussed on IRC.

### PR DESCRIPTION
**Pull request by Amanieu**
Fixes #61357

This also includes rust-lang/hashbrown#80.

### CODE REVIEW

**Comment by Amanieu** [comment]
This needs to be backported to beta before the 1.36 release which will include hashbrown.

**Comment by RalfJung** [comment]
This is on the critical path to fixing Miri.

@bors p=1

**Pull request merged**
