### PR TITLE
Dedupe regex

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @GuillaumeGomez (minifier updated)

@bors r+

**Comment by kennytm** [comment]
@bors r-

Lots of broken links. (Maybe linkchecker is incompatible with the new minifier?)

**Comment by GuillaumeGomez** [comment]
@kennytm: @Eijebong tested locally and it doesn't seem to be the minifier...

**Comment by TimNN** [comment]
Ping from triage, @Eijebong, @Mark-Simulacrum: Will one of you be able to investigate the travis failure?

@GuillaumeGomez: Did you notice anything when you tested locally that could point to the issue?

**Comment by Mark-Simulacrum** [comment]
I will not have the time to debug this travis failure soon; I think it might be best to close this unless someone's willing to do the legwork there.

**Comment by Eijebong** [comment]
Yup, that's it, I'll have a look at updating it at 0.2 then

**Comment by Eijebong** [comment]
People are already working that, I'll close this and will reopen once the mdbook bump is finished

**Pull request closed without merging**
