### PR TITLE
visit enum init when the enum variable doesn't have any parameters

### LINKED ISSUE #101208: Provide suggestion for error when `if let` used with enum variant whose values are not initialized
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ac515a35cf754b067d63ab16f3917383)

```rust
enum E {
    One(i32, i32)
}

fn main() {
    let var = E::One;
    if let E::One(var1, var2) = var {
        println!("{var1} {var2}");
    }
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:7:12
  |
7 |     if let E::One(var1, var2) = var {
  |            ^^^^^^^^^^^^^^^^^^   --- this expression has type `fn(i32, i32) -> E {E::One}`
  |            |
  |            expected fn item, found enum `E`
  |
  = note: expected fn item `fn(i32, i32) -> E {E::One}`
                found enum `E`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Ideally the output should suggest to the user that they need to initialize the enum variant's value in order to use the `if let`.

### PR DESCRIPTION
**Pull request by lyming2007**
this fix #101208

### CODE REVIEW

**Comment by petrochenkov** [comment]
This diagnostic is already reported in a very similar case
```rust
struct S(u8, u8);

fn main() {
    let _: S = S;
}
```
```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:4:16
  |
1 | struct S(u8, u8);
  | -------- fn(u8, u8) -> S {S} defined here
...
4 |     let _: S = S;
  |            -   ^ expected struct `S`, found fn item
  |            |
  |            expected due to this
  |
  = note: expected struct `S`
            found fn item `fn(u8, u8) -> S {S}`
help: use parentheses to construct this tuple struct
  |
4 |     let _: S = S(/* u8 */, /* u8 */);
  |                 ++++++++++++++++++++
```
, and it's not specific to tuple structs, it works for any function calls returning the expected type.

But for some reason it's not reported in cases like this
```rust
struct S(u8, u8);

fn main() {
    let S(_, _) = S;
}
```
```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:4:9
  |
4 |     let S(_, _) = S;
  |         ^^^^^^^   - this expression has type `fn(u8, u8) -> S {S}`
  |         |
  |         expected fn item, found struct `S`
  |
  = note: expected fn item `fn(u8, u8) -> S {S}`
              found struct `S`
```
I think we need to figure out why this `S(_, _)` doesn't correctly propagate the expected type in the old diagnostic instead of introducing a new diagnostic.
@rustbot author

**Comment by JohnCSimon** [comment]
@lyming2007 
ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by lyming2007** [comment]
> @lyming2007 ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!
> 
> FYI: when a PR is ready for review, send a message containing `@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

[petrochenkov](https://github.com/petrochenkov) was right about his comment. There was a similar case. But they're actually very different in terms of implementation. My fix was straight forward but maybe not a perfect one. So I still need more work on this. I'll update it later

**Comment by JohnCSimon** [comment]
@lyming2007 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
