### PR TITLE
CI: Enable overflow checks for test (non-dist) builds

### PR DESCRIPTION
**Pull request by hkratz**
They stay disabled for Apple builds though, which take the most time already due to running on slow hw.

### CODE REVIEW

**Comment by hkratz** [comment]
rustbot label -S-waiting-on-author  +S-blocked

**Comment by Mark-Simulacrum** [comment]
Do we have a recent-ish measurement of how much this would slow down the compiler if enabled by default? I feel like there was a measurement a few months (years?) back...

Even if we don't enable the overflow checks within std, it seems reasonable to enable them for the compiler only, if we can afford it.

**Comment by Mark-Simulacrum** [comment]
Thanks. Yeah, I recall those measurements now. Agreed we likely can't accept that hit just yet.

I'm fine with us merging this and we can evaluate the CI time impact if it becomes a problem, it seems reasonable to have our test builders run with more assertions where we can afford it.

**Comment by oli-obk** [comment]
will also fail the tools builder due to #89280 which breaks clippy tests

**Comment by hkratz** [comment]
#89280 has been fixed. I have tested this locally with `x.py test --stage 2` and `./src/ci/docker/run.sh x86_64-gnu-tools`.

@rustbot label -S-blocked +S-waiting-on-review

r? @Mark-Simulacrum

**Pull request merged**
