### PR TITLE
Detect unaligned fields via `aggregate.align < field.align`, instead of a `packed` flag.

### LINKED ISSUE #46423: Replace the internal notion of "packed" types with type vs field align/offset mismatch.

### PR DESCRIPTION
**Pull request by eddyb**
Closes #46423. cc @oli-obk

### CODE REVIEW

**Comment by kennytm** [comment]
#46428 has been merged, removing <kbd>S-blocked</kbd> tag.

**Comment by kennytm** [comment]
@bors retry 

"error: Could not compile `rustdoc`." without any reasons?

**Comment by kennytm** [comment]
@bors retry #33434

```
   Doc-tests core
error: test failed, to rerun pass '--doc'
command did not execute successfully: "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\stage0/bin\\cargo.exe" "test" "--target" "i686-pc-windows-gnu" "-j" "2" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "C:\\projects\\rust\\src/libstd/Cargo.toml" "-p" "std:0.0.0" "-p" "unwind:0.0.0" "-p" "alloc_system:0.0.0" "-p" "std_unicode:0.0.0" "-p" "libc:0.0.0" "-p" "compiler_builtins:0.0.0" "-p" "panic_abort:0.0.0" "-p" "alloc:0.0.0" "-p" "core:0.0.0" "--"
expected success, got: exit code: 3221225477
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap test
Build completed unsuccessfully in 1:58:02
Command exited with code 1
```

**Comment by kennytm** [comment]
Could not compile `rustdoc` for `i686-pc-windows-msvc` again. This PR may have introduced a change that caused this to fail with some probability. Not going to retry.

**Comment by eddyb** [comment]
Is it running out of memory by any chance?

**Comment by kennytm** [comment]
I don't know, the log doesn't track memory use 😞

**Comment by carols10cents** [comment]
Soooo who might have some insight on why rustdoc can't build on appveyor? @rust-lang/infra ? @rust-lang/docs ?

**Comment by GuillaumeGomez** [comment]
Without more logs, it's gonna be complicated...

**Comment by arielb1** [comment]
Could someone check this on a Windows machine?

**Comment by nagisa** [comment]
3221225477 is STATUS_ACCESS_VIOLATION.

**Comment by eddyb** [comment]
I may have found something that was wrong in the old code but not in an observable way.

**Review by oli-obk — APPROVED** [review]

**Review by oli-obk — COMMENTED** [review]
Threading through the alignments was the original idea. We scrapped it because we thought it would get too intrusive. With all the convenience methods on Align it seems good though

**Comment by oli-obk** [comment]
Just break miri. I want to refactor some of the ty arguments to layout arguments anyway, I'll just do that there

**Pull request merged**
