### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by dtolnay**
Successful merges:

 - #66818 (Format libstd/os with rustfmt)
 - #66819 (Format libstd/sys with rustfmt)
 - #66820 (Format libstd with rustfmt)
 - #66847 (Allow any identifier as format arg name)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by dtolnay** [comment]
Chocolatey is flaky. https://status.chocolatey.org/issues/2019-11-29-slow-and-intermittent-connection-issues/

@bors retry

**Comment by Centril** [comment]
Using as canary for windows builders; @bors r+ p=2000 rollup=never

**Comment by Centril** [comment]
let's try again... @bors retry

**Pull request merged**
