### PR TITLE
E0435, E0437 & E0438 New Error Format

### PR DESCRIPTION
**Pull request by shyamsundarb-arch**
Part of #35801 , #35802 and #35803 
r? @jonathandturner 

Hi! Please review the changes.

### CODE REVIEW

**Comment by shyaamsundhar** [comment]
@jonathandturner I have committed only file which is Lib.rs, the other commit "Merge remote-tracking branch 'refs/remotes/rust-lang/master'" is automatically getting committed in. Please advice.

**Comment by GuillaumeGomez** [comment]
Please add corresponding tests and squash your commits

**Comment by jonathandturner** [comment]
You can read about adding the additional tests in my [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html) in the "Extra credit" section.

**Comment by shyaamsundhar** [comment]
I went through the document. A small doubt, I could not find the files E0435, E0437 or E0438 under "rust/src/test/compile-fail", can I create files using the example provided in lubrustc_resolve\diagnostics.rs? Please advice.

**Comment by GuillaumeGomez** [comment]
They exist: [E0435](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/E0435.rs), E0437](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/E0437.rs) and [E0438](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/E0438.rs). Update your branch to last rust-lang/master version.

**Comment by shyaamsundhar** [comment]
I will create a new pull request with squashed commits.

**Pull request closed without merging**
