### PR TITLE
[beta] Fixes #46775 -- don't mutate the process's environment in Command::exec

### LINKED ISSUE #46775: std::os::unix::process::CommandExt::exec should be unsafe
This method assigns to `environ` outside of any lock, meaning that it's automatically unsafe for multi-threaded programs.

For single-threaded programs, if the `exec` fails, `environ` will point to memory that has been freed. The [documentation](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.exec) gives a false sense of security:
> The process may be in a "broken state" if this function returns in error. For example the working directory, environment variables, signal handling settings, various user/group information, or aspects of stdio file descriptors may have changed.

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a backport of the following PRs:

* https://github.com/rust-lang/rust/pull/55359 
* https://github.com/rust-lang/rust/pull/55569
* https://github.com/rust-lang/rust/pull/55304
* #55661

### CODE REVIEW

**Comment by alexcrichton** [comment]
I've also included https://github.com/rust-lang/rust/pull/55304 to help switch over our deploy credentials.

ping r? @Mark-Simulacrum or @pietroalbini

**Comment by pietroalbini** [comment]
Uh, wait, the actual backport is missing?

@bors r-

**Comment by alexcrichton** [comment]
@bors: r=pietroalbini

er yes, I didn't expect this branch hadn't been looked at yet...

**Comment by alexcrichton** [comment]
@bors: retry

* 3 hr timeout

**Comment by pietroalbini** [comment]
Can you also rollup the other beta-accepted PRs? Thanks!

**Comment by alexcrichton** [comment]
@bors: r+

I'm gonna pray that was spurious

**Comment by alexcrichton** [comment]
@bors: retry

Good ol' network failures

**Pull request merged**
