### PR TITLE
rustdoc: Break bounds if they are too long

### LINKED ISSUE #107283: Rustdoc 1.67.0 combining supertraits into single line even if it's 1000 characters long
I generated documentation for the fixed crate, and the issue is clear in the documentation for the `fixed::traits::Fixed` trait.

Version 1.66.1 (90743e729 2023-01-10) produces something like this:

image

Version 1.67.0-beta.10 (227644892 2023-01-22) produces something like this:

image

That's over a 1000 characters squashed into a single line.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/107283.

I'm not super happy with this fix, however, to do better, either we have to make the `display` implementation take into account a max length and therefore change how we render things completely or we could also parse HTML.

In this PR, I decided to take another approach: if there are more than 4 bounds on an item, these bounds are split each on their own line. We could also decide to group them by 2 or more.

I uploaded an example of it [here](https://rustdoc.crud.net/imperio/fix-long-bounds-display/foo/trait.Fixed.html).

r? @notriddle

### CODE REVIEW

**Comment by fmease** [comment]
The relevant issue states that rustdoc version 1.66.1 used to properly break the bounds into several lines meaning that the current state of affairs is a regression. Do you know which PR might have caused this regression? Why can't we do as before? Just curious.

**Comment by tspiteri** [comment]
In version 1.66.1 the bounds were not broken automatically; in the example that I showed they were broken up in the source. So the change in 1.67.0 is that it changes for example this source code
```rust
pub trait T
where
    Self: A + B + C,
    Self: D + E + F,
{
```
into
```rust
pub trait T
where
    Self: A + B + C + D + E + F,
{
```

**Comment by GuillaumeGomez** [comment]
@fmease: This is the PR which broke it: https://github.com/rust-lang/rust/pull/105183. So this regression is a side-effect.

**Comment by anden3** [comment]
Hello @GuillaumeGomez! I just want to ping you as part of the triage procedure as this PR has merge conflicts and CI failures :)

**Comment by GuillaumeGomez** [comment]
Doesn't seem like the right approach.

**Pull request closed without merging**
