### PR TITLE
turn `ManuallyDrop::new` into a constant function

### PR DESCRIPTION
**Pull request by japaric**
r? @sfackler

### CODE REVIEW

**Comment by sfackler** [comment]
@rfcbot fcp merge

This seems reasonable to me but let's make sure everyone's on board since it's insta-stable.

**Comment by SimonSapin** [comment]
This sounds fine, but don’t you need some other APIs to be `const` as well for this to be useful? What’s an usage example?

**Comment by japaric** [comment]
@SimonSapin 

> don’t you need some other APIs to be const as well for this to be useful?

Yes, `mem::uninitialized` (cf. #50150). But I just heard on that other PR that the plan is to deprecate `mem::uninitialized` in favor of `MaybeUninit`. Personally, I'd be OK with using `MaybeUninit` instead of `ManuallyDrop` + `mem::uninitialized` if the RFC gets accepted and/or if there concerns about insta-stabilizing `ManuallyDrop::new`. (In any case, I'm stuck with nightly until `const_fn` is stabilized).

> What’s an usage example?

Fixed capacity dynamic data structures (Vec, String, HashMap, etc) that you can put in `static` variables. See [heapless](https://crates.io/crates/heapless).

**Comment by SimonSapin** [comment]
What I had in mind is: it seems that `ManuallyDrop::new` is only useful if you can do anything with that value of type `ManuallyDrop` afterwards. The main APIs for that are `Deref` and `DerefMut`, but they’re not const. I’ve just now realized that you only want `const` to initialize a `static` item, and them use it at runtime.

This is a long way of saying: sounds good, never mind my previous comment :)

**Comment by kennytm** [comment]
You could make this not insta-stable via `rustc_const_unstable`. See [`TypeId::of`](https://github.com/rust-lang/rust/blob/cc794209681d6b11a63282bcd1513caa50127816/src/libcore/any.rs#L370).

**Comment by oli-obk** [comment]
Ping @japaric

**Pull request merged**
