### PR TITLE
Beta backports

### PR DESCRIPTION
**Pull request by nikomatsakis**
This PR aims to backport all the beta PRs.

Here is a list with their status:

- [x] #38268
- [ ] #38859 (not merged)
- [ ] #38855 (not merged)
- [x] #38833 
- [ ] #38817 (did not backport cleanly; will revisit -- or maybe @jseyfried can take a look)
- [x] #38708
- [x] #38770
- [x] #38783
- [x] #38793 
- [ ] #38792 (not merged)
- [x] #38737
- [x] #38689 
- [x] #38552 
- [x] #38537 
- [ ] #38815 (not merged)
- [ ] #38835 (not merged)
- [ ] #38858 (not merged)

cc @rust-lang/compiler @alexcrichton @brson #

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Argh. Seems like something didn't backport cleanly, probably the last PR.

**Comment by alexcrichton** [comment]
@nikomatsakis could you back out the backport of 4781eb315b7bcf11682d68aafac2ce4739bfe166 (the second commit of https://github.com/rust-lang/rust/pull/38708), we should only need the first commit I believe, specifically d0881eaec7d1300566607bb465acf614ce073b75

**Comment by alexcrichton** [comment]
@nikomatsakis your list also claims https://github.com/rust-lang/rust/pull/38792 was backported but the commits aren't showing up here for me?

**Comment by alexcrichton** [comment]
Ok I updated the list in the PR description to also reflect whether the PRs have been merged or not. We have less testing on beta than we do on master, so I personally prefer to wait for a merge to master before backporting, but we can also just re-backport fixes if necessary.

**Comment by alexcrichton** [comment]
I unchecked #38792 in the list above due to [this comment](https://github.com/rust-lang/rust/pull/38872#issuecomment-270951660)

**Comment by nikomatsakis** [comment]
@alexcrichton 

> your list also claims #38792 was backported but the commits aren't showing up here for me?

hmm, yeah, I somehow overlooked that one, but in the other case I had just forgotten to push

> could you back out the backport of 4781eb3 (the second commit of #38708), we should only need the first commit I believe, specifically d0881ea

will do

**Comment by nikomatsakis** [comment]
> could you back out the backport of 4781eb3 (the second commit of #38708), we should only need the first commit I believe, specifically d0881ea

done

**Comment by brson** [comment]
Wowee! This is amazing. Thanks @nikomatsakis

**Comment by alexcrichton** [comment]
Thanks @nikomatsakis!

**Pull request merged**
