### PR TITLE
Remove no_stack_check (#34915)

### PR DESCRIPTION
**Pull request by abhijeetbhagat**
Part of fixes for #34915

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Unfortunately I don't think we can remove this command line option as it's a stable compiler flag right now, so this runs the risk of breaking others' compilations. It may be worth issuing a warning indicating that this doesn't do anything any more, but perhaps for now just the help description could be updated to indicate this?

**Comment by brson** [comment]
Agree with @alexcrichton, sadly.

**Comment by nagisa** [comment]
> compiler team concluded… kill any compiler flag that exposing a similar thingie.

from https://github.com/rust-lang/rust/issues/34915#issuecomment-234369958

I guess it could go through a deprecation of some sort, though.

**Comment by brson** [comment]
Thanks for pointing that out @nagisa. @rust-lang/compiler This PR removes `-C no-stack-check` but that is a stable flag. Our policy is to not remove them so it's been proposed to make it a no-op. What say you?

**Comment by nrc** [comment]
Could we at least warn that it is a no-op - silently changing behaviour is bad

**Comment by eddyb** [comment]
@nrc Nothing actually checks `no_stack_check` though, there's no behavior to change.

**Comment by nrc** [comment]
That seems like even more reason to warn the user that they are doing something that is not going to have the effect which they expect.

**Comment by brson** [comment]
@abhijeetbhagat Can we go ahead and change this patch to instead print out a warning "the --no-stack-check flag is deprecated and does nothing"? Thanks for your patience.

**Comment by brson** [comment]
@abhijeetbhagat Oh, I see you opened another issue for this. I'll comment on that one.

**Pull request closed without merging**
