### PR TITLE
Make better use of stack space in BitSet

### PR DESCRIPTION
**Pull request by saethlin**
This nearly doubles the inline capacity of `FixedBitSet`, increasing it from 128 to 248 bits.

This implementation is very hacky and the whole strategy may potentially have a lot of downsides, right now I'm just trying to validate if this approach is even worth pursuing before I patch up, optimize, or delete the rest of the BitSet APIs.

_sigh_ forgot to request from ghost again, sorry.

### CODE REVIEW

**Comment by nehaaaa6** [comment]
According on the information provided, it appears that the implementation under discussion would increase FixedBitSet's inline capacity from 128 to 248 bits. This is being accomplished through a crude implementation, which might have drawbacks.

Before moving further, it is crucial to carefully assess the implications of this implementation. While raising the inline capacity may improve performance and memory use, there is a chance that it may also have drawbacks like greater complexity or decreased maintainability.

The creator of the implementation is currently determining whether it is worthwhile to continue with this strategy. To assess the prospective advantages, it might be useful for them to get input from other team members or authorities in the relevant field.

**Comment by saethlin** [comment]
I don't think there is any immediate value to the compiler here, so I'm closing this PR and I'm going to bake the implementation in its own repo.

**Pull request closed without merging**
