### PR TITLE
Stabilize dyn trait

### PR DESCRIPTION
**Pull request by pvdrz**
This PR stabilizes RFC 2113. I followed the [stabilization guide](https://forge.rust-lang.org/stabilization-guide.html).

Related issue: https://github.com/rust-lang/rust/issues/49218

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@TimNN btw that message doesn't seem to include the error =)

**Comment by christianpoveda** [comment]
I'm having trouble with llvm, I'm going to rebuild everything from scratch

**Comment by christianpoveda** [comment]
@nikomatsakis I think we are ready

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
r=me once travis is happy

**Comment by alercah** [comment]
Not sure if this is the best place to ask, but in the future, when a sub-feature is split off for separate stabilization, can we please ensure that docs PRs are filed for the sub-feature as a prerequisite? We have rust-lang-nursery/reference#279 for `dyn Trait`, but looking at the tracking issue #44662, it looks like it isn't stabilized, so it would otherwise slip through the cracks until the full feature was done. (cc @Havvy)

**Comment by steveklabnik** [comment]
We changed the requirement from a PR to an issue, but yeah, big 👍 to that

**Comment by steveklabnik** [comment]
@alercah for the stuff relating to the edition, we relaxed the requirement to "file an issue". I made issues for everything in RBE and the book, but I thought yinz were handling the reference your own way. If it's easier, you all may want to copy over https://github.com/rust-lang/book/issues?q=is%3Aopen+is%3Aissue+label%3A%22Blocking+Rust+2018%22, or I'm happy to do it too, whatever works for you all.

**Comment by alercah** [comment]
Oops sorry, yes, I meant issues, not PRs. @matthewjasper filed a number of issues for the reference for Rust 2018 features, and that's good, but there are always going to be stabilizations that aren't planned out like that. So the point that I was trying to make subtly, and apparently failed at because I mixed things up, was that I think that at some point someone should have asked "Do necessary issues exist on docs repositories?" before this got merged. It's not clear to me that it wasn't because we already have one for `dyn Trait` writ large, in which case it just slipped through, or that it's because nobody checked.

As a side note, the stabilization guide needs updating, which would probably reduce the likelihood of future miscommunication.

**Comment by steveklabnik** [comment]
> I think that at some point someone should have asked "Do necessary issues exist on docs repositories?" before this got merged. 

yes please! Agree 1000%.

**Pull request merged**
