### PR TITLE
coverage: Skip instrumenting a function if no spans were extracted from MIR

### LINKED ISSUE #118850: A used function should have had coverage mapping data but did not
The immediate symptoms of #118643 were fixed by #118666, but some users reported that their builds now encounter another coverage-related ICE:

https://github.com/rust-lang/rust/issues/118643#issuecomment-1849690436
https://github.com/rust-lang/rust/issues/118643#issuecomment-1849962689

```
error: internal compiler error: compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs:98:17: A used function should have had coverage mapping data but did not: _RNvMsl_NtNtNtCsl0gwtrD5SWs_5winit13platform_impl8platform15window_delegateNtB5_19WinitWindowDelegate21window_did_resign_key
```

### PR DESCRIPTION
**Pull request by Zalathar**
The immediate symptoms of #118643 were fixed by #118666, but some users reported that their builds now encounter another coverage-related ICE:

```
error: internal compiler error: compiler/rustc_codegen_llvm/src/coverageinfo/mapgen.rs:98:17: A used function should have had coverage mapping data but did not: (...)
```

I was able to reproduce at least one cause of this error: if no relevant spans could be extracted from a function, but the function contains `CoverageKind::SpanMarker` statements, then codegen still thinks the function is instrumented and complains about the fact that it has no coverage spans.

This PR prevents that from happening in two ways:
- If we didn't extract any relevant spans from MIR, skip instrumenting the entire function and don't create a `FunctionCoverateInfo` for it.
- If coverage codegen sees a `CoverageKind::SpanMarker` statement, skip it early and avoid creating `func_coverage`.

---

Fixes #118850.

### CODE REVIEW

**Comment by Zalathar** [comment]
Another thing I tried was having the `InstrumentCoverage` MIR pass take all those `CoverageKind::SpanMarker` statements and replace them with `StatementKind::Nop`.

However, that doesn't work because `Nop` isn't allowed during the phase that `InstrumentCoverage` runs in.

**Comment by Zalathar** [comment]
Either of the patches should fix the issue on their own, but I think they're both worthwhile.

(If we skip instrumenting a function with no spans, then the function won't have `FunctionCoverageInfo`, so `func_coverage` never gets created either way. But I had already been meaning to make marker statements not materialize `func_coverage` anyway.)

**Review by Swatinem — APPROVED** [review]

**Pull request merged**
