### PR TITLE
Move `sys_common::rwlock::StaticRWLock` etc. to `sys::unix::rwlock`

### PR DESCRIPTION
**Pull request by CDirkx**
This moves `sys_common::rwlock::StaticRwLock`, `RWLockReadGuard` and `RWLockWriteGuard` to `sys::unix::rwlock`. They are already `#[cfg(unix)]` and don't need to be in `sys_common`.

Part of #84187.

### CODE REVIEW

**Comment by CDirkx** [comment]
I was also thinking about removing `sys_common::rwlock` entirely, since `sys_common::rwlock::RWLock` doesn't provide any meaningful abstraction (just delegation to the `sys` implementation). However the comments about what is and isn't undefined behavior are useful to keep around.

**Review by dtolnay — APPROVED** [review]
Thanks, looks good.

Regarding `sys_common::rwlock::RWLock` &mdash; it looks to me like that wrapper type is serving exactly the purpose of a **trait**, i.e. a consistent set of methods with documented guarantees that the various implementations must provide. So how about replacing it with a `RWLock` trait instead? The trait would take the place of the current wrapper, in sys_common. The implementations would stay in sys, and would now have all their methods in a trait impl rather than inherent methods. The trait fulfills the current role of the wrapper type by ensuring that the various implementations all expose the same API.

**Comment by CDirkx** [comment]
Yeah using traits for that could be a good idea. I'll look into other types that may also be applicable to.

**Pull request merged**
