### PR TITLE
[WIP] rustc_typeck: make "global" WF requirements hard errors, in type aliases.

### PR DESCRIPTION
**Pull request by eddyb**
Based on #54033, a theory I want to test on crater.
Unlike #54033, this only errors on "unusable" aliases, as in, no choice of type parameters can make them WF, because they include nested non-WF types/constants.

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
@craterbot run start=master#f7f4c500b46603386e940f116b469c7adc043a6d end=try#f1a3f05968ed2a674e09b6efa4ad9df90816e2b6 mode=check-only

**Comment by eddyb** [comment]
@nikomatsakis Can you take a look at these results? I'm confused because I expected to not see any errors - maybe the crater run should've been done with `cap-lints=warn` so `#![deny(warnings)]` doesn't make the warning an error, but does that explain everything?

**Comment by Aaronepower** [comment]
Triage; @nikomatsakis Hello, are you able to review this PR?

**Comment by eddyb** [comment]
@Aaronepower This is not waiting on a review, I still have to finish the PR.

**Comment by nikomatsakis** [comment]
@eddyb 

> Can you take a look at these results? I'm confused because I expected to not see any errors 

Just saw this, sorry...

**Comment by nikomatsakis** [comment]
I'm going to close this PR for now. I do plan to start opening some PRs and issuing warnings, per the plan discussed in https://github.com/rust-lang/rust/issues/55222

**Pull request closed without merging**
