### PR TITLE
remove associated_consts feature gate

### PR DESCRIPTION
**Pull request by seanmonstar**
Currently struggling to run tests locally (something about jemalloc target missing).

cc #29646

### CODE REVIEW

**Comment by seanmonstar** [comment]
Sure, though as to where and how, I have no idea. And it seems all the possible places to move that file are actually submodules...

**Comment by bstrie** [comment]
I'd suggest perhaps just leaving the page in the unstable book for now so that we don't forget that documentation exists for it, after all, it *is* still unstable until the 1.20 release. Docs are low-risk to backport to beta, if it comes to that.

**Comment by bstrie** [comment]
I don't think it's worth holding up this PR for this next comment, but there's a postponed RFC from 2015 that was gated on associated consts that could be worth discussing now ( https://github.com/rust-lang/rfcs/pull/1168 ), but for the sake of backcompat it wants to reserve two legal identifiers for associated consts for future use. Again, not worth holding up this PR for, but something that ought to be considered before this makes it into beta.

**Comment by seanmonstar** [comment]
`make tidy` fails if I leave the page in the unstable-book.

**Comment by arielb1** [comment]
Travis failure is spurious. r? @nikomatsakis

**Comment by nikomatsakis** [comment]
@seanmonstar sorry for the delay! 

Before stabilizing, we *are* supposed to have doc PRs pending, at least. There are some details about how to do it in the [forge docs on stabilization](https://forge.rust-lang.org/stabilization-guide.html). I think the basic idea would be to move the existing material from the "unstable book" into the reference -- sparse as it is, it's better than nothing.

**Review by nikomatsakis — APPROVED** [review]
Other than the lack of a documentation PR, this seems good!

**Comment by seanmonstar** [comment]
Rebased again, and opened a PR against the reference to pull in the docs from the unstable book: https://github.com/rust-lang-nursery/reference/issues/75

**Comment by est31** [comment]
@seanmonstar just that you are aware for the case you want this to get into 1.20 : the beta branches in a week.

**Comment by seanmonstar** [comment]
@est31 oh, I know! After yet another rebase, I'll ping someone with merge permissions when travis is green.

**Comment by seanmonstar** [comment]
@nikomatsakis ok, so it's green, and the PR to the reference is approved waiting on this merge. We good to go?

**Pull request merged**
