### PR TITLE
[beta] Bump LLVM to a upstream 12.0 release

### PR DESCRIPTION
**Pull request by nagisa**
Currently the `beta` branch utilizes a release candidate of LLVM 12.0. Since then a large number of issues have been fixed upstream, including those that are known to affect Rust code.

It would be unfortunate if we released a stable Rust with all of those issues when we have the fixes in the actual LLVM release and/or our backports of commits that didn't make the release cut on top of it.

cc @cuviper / @nikic

### CODE REVIEW

**Comment by cuviper** [comment]
#84230 is already beta-nominated -- shouldn't we wait for that process?

You also pulled in the stack-probe dwarf change here, not sure if that was intentional.

**Comment by nagisa** [comment]
Yes, it was intentional to pull in that change, though, now that I think about it, the DWARF problem is in stable already so we don't really need to backport it like we should with the others.

**Comment by nagisa** [comment]
Ah, I was wrong. while it would've reached stable, it did not because of https://github.com/rust-lang/rust/pull/83412 and so it is valuable to consider this for backport, including separately from the other LLVM 12.0 backport.

**Comment by wesleywiser** [comment]
We discussed this in the compiler team triage meeting and decided to approve the backport.

**Pull request merged**
