### PR TITLE
More distinctive pretty-printing of function item types

### PR DESCRIPTION
**Pull request by steffahn**
Change the way “fn item” types are displayed: make them easier to distinguish from fn pointers.

My first point here is to figure out if CI passes, or how much more needs to be done to *make* it pass. (_Edit: It does pass 🥳_) Then there still needs to be discussion *if* we want such a change, and also *how exactly* they should best be rendered.

As you can see, this affects quite a lot of output. In particular, not only error messages but also pretty printed MIR (with types), as far as I can tell.

Context: https://internals.rust-lang.org/t/extending-implicit-coercion-of-function-items-to-function-pointers-during-trait-resolution/17093/6

My initial idea was to use something like ``[function item `guess`: for<'r> fn(&'r [Guess]) -> String]``, but `fn item` is more consistent with other parts of the error messages, and the backticks don’t look nice in an error message that also puts backticks around the whole type, so it became `[fn item {guess}: for<'r> fn(&'r [Guess]) -> String]`. I’ve also considered something like `[fn-item guess: for<'r> fn(&'r [Guess]) -> String]`, but the colon looks suboptimal after a longer path; wrapping the path into an extra set of parentheses works nicely IMO, and it could also be seen as a reference to the previous way of rendering the type, `for<'r> fn(&'r [Guess]) -> String {guess}`, which used the curly braces, too.

Really, all that changes now is: the order is switched, the thing becomes more clearly grouped as one coherent thing with the `[]`s (which are also meant to make the thing look more similar to a closure type, and more clearly different from a fn pointer type), and the thing becomes more self-describing (since it *is* special diagnostics-only syntax, after all) with the string “fn item” included.

As of now, there’s a minor downside that tuple-structs’ and tuple-struct-style-enum-variants’ constructors render as something like `[fn item {Foo}: u8 -> Foo]`, too, whereas something like e.g. `[tuple struct constructor {Foo}: u8 -> Foo]` might be nicer. It’s also already described as “'fn item`” currently though anyway, by error messages such as
```rs
struct Foo(u8);
fn f() {
    let _: () = Foo;
}
```
```
error[E0308]: mismatched types
 --> src/lib.rs:3:17
  |
3 |     let _: () = Foo;
  |            --   ^^^ expected `()`, found fn item
  |            |
  |            expected due to this
  |
  = note: expected unit type `()`
               found fn item `fn(u8) -> Foo {Foo}`
``` 

_(which would after this PR look like this instead:)_
```
error[E0308]: mismatched types
 --> src/lib.rs:3:17
  |
3 |     let _: () = Foo;
  |            --   ^^^ expected `()`, found fn item
  |            |
  |            expected due to this
  |
  = note: expected unit type `()`
               found fn item `[fn item {Foo}: fn(u8) -> Foo]`
```

### CODE REVIEW

**Comment by steffahn** [comment]
I’m wondering if there’s a way (and a desire) to (be able to) test colors of compiler output, for the highlighting logic.

**Comment by compiler-errors** [comment]
> As of now, there’s a minor downside that tuple-structs’ and tuple-struct-style-enum-variants’ constructors render as something like [...]

We have access to tcx in pretty printing, right? We should be able to check the `def_kind` and special case for constructors, if necessary. Though that can be done in a follow-up.

Otherwise, I do like this change, even if the output is a bit heavier.

cc @rust-lang/wg-diagnostics

**Comment by CAD97** [comment]
cc @estebank who [recently complained about the closure type display](https://github.com/rust-lang/rust/pull/99719#discussion_r929090094); this makes fn items more like closures.

Bikeshed: why don't we just call it `fn Foo(u8) -> Foo` / `for<'r> fn guess(&'r [Guess]) -> String`? This moves the "it's not a function pointer" earlier in the type, but I suppose still doesn't offer an obvious difference to `fn(u8) -> String` / `for<'r> fn(&'r [Guess]) -> String`.

Either way, I think the ideal situation (including [closure numbering](https://github.com/rust-lang/rust/pull/99719#discussion_r933624683)) would treat `fn name` and `fn {closure#0}` similarly, if not for the fact that closures can be `!Fn`.

Using the "type ascription" form would allow closures to use `: fn`, `: Fn`, `: FnMut`, or `: FnOnce` to communicate the most permissive coercion they provide.

**Comment by CAD97** [comment]
> I’m wondering if there’s a way (and a desire) to (be able to) test colors of compiler output, for the highlighting logic.

Current tests have no color output, and this is the correct default, provided by default `--color=auto` and not any explicit choice. It should be possible to set something like <code><a href="https://rustc-dev-guide.rust-lang.org/tests/headers.html#miscellaneous-headers">// compile-flags</a> <a href="https://doc.rust-lang.org/rustc/command-line-arguments.html#--color-configure-coloring-of-output">--color=always</a></code> to force the color ANSI into the test output. (Of course/unfortunately, this makes reviewing it as plaintext somewhere between difficult and impossible.)

**Comment by steffahn** [comment]
> We have access to tcx in pretty printing, right? We should be able to check the `def_kind` and special case for constructors, if necessary. Though that can be done in a follow-up.

Yeah, I thought follow-up.

**Comment by steffahn** [comment]
Anyone know how to run 32bit mir-opt test cases to bless them, while working on a 64bit machine?

**Comment by compiler-errors** [comment]
@steffanh I think you've gotta run `./x.py test --target=i686-unknown-linux-gnu src/test/mir-opt`

**Comment by steffahn** [comment]
Hmmm… I’m getting some errors `/usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory` with when trying either version of that.

**Comment by steffahn** [comment]
Well, it’s few enough changes that I can do it manually…

**Review by davidtwco — APPROVED** [review]
Implementation changes look good to me. I don't have a strong opinion on the actual changes being made, I'll let this sit for a little bit to see if anyone else has opinions.

**Comment by estebank** [comment]
Can we get a screenshot to see the highlighting?

**Comment by steffahn** [comment]
I’ve started working on differentiating between constructors and non-constructors, however, it’s running into problems in the ui test that runs `rustc` with `RUSTC_LOG=debug`, i.e. `src/test/ui/rustc-rust-log.rs`. Some kind of infinite looping or recursion or so; presumably because the call I’m making does some debug printing of the type, resulting in infinite recursion? Though I’ll have to investigate.

I also made some small further changes to the highlighting there… also I wouldn’t mind trying to get it to work and then integrate it into this PR already. In that case, @estebank, perhaps it makes most sense to show screenshots of the highlighting only after those changes since they change highlighting a little…

@rustbot author

---

Currently working on [this branch](https://github.com/steffahn/rust/commits/distinctive_function_item_types_printing_contd) (new commits: 65eb3401f62e78c38e4d7edd5a1688352346c94e and cb0db7f36a56185648e067f3fab327b6db4287c0); the relevant new call that’s presumably still causing problems is the one to `tcx.def_kind(did)`.

For fixing the problem, I’m considering either to look for an alternative to the `def_kind` call, or to find and disable the relevant debug-information printing in its implementation. In case someone has experience with such problems, feel free to give general advice.

**Comment by steffahn** [comment]
Indeed, I just overlooked `DefKind::AssocFn`. I’ll push new commits soon, and then upload screenshots of the highlighting, too.

For now, I’ve used `[constructor of {Foo}: fn() -> Foo]`-style printing for tuple constructors (not further distinguishing between enum and struct ones). (I.e. `fn item` becomes `constructor of`.)

**Comment by steffahn** [comment]
Here’s screenshots:
```rs
fn foo() {
    fn f() {}
    fn g() {}
    fn g2() -> u8 {
        0
    }
    fn g3(_: u8) {}

    fn h<T>() {}
    fn h2<T>(_: T) {}

    struct Struct();

    let mut x = f;
    x = || ();
    x = (|| ()) as fn();
    x = (|| 0) as fn() -> u8;
    x = (|_| ()) as fn(u8);
    x = g;
    x = g2;
    x = g3;
    x = Struct;

    let mut y = h::<()>;
    y = h::<u8>;

    let mut y2 = h2::<()>;
    y = h2::<u8>;

    let mut z = g3;
    z = (|| ()) as fn();

    let mut p = (|| ()) as fn();
    p = (|| 0) as fn() -> u8;
    p = (|_| ()) as fn(u8);
    let _: fn() -> u8 = g3;
    let _: fn() -> u16 = g2;
}

fn main() {}
```
Screenshot_20220802_175217
Screenshot_20220802_175244
Screenshot_20220802_175305

**Comment by steffahn** [comment]
CI is passing

@rustbot ready

I can re-order and squash some commits before merging if that’s desired

**Comment by compiler-errors** [comment]
All those "bless"/"update" commits could get squashed into their parents, since those aren't really functional changes.

**Comment by steffahn** [comment]
> All those "bless"/"update" commits could get squashed into their parents, since those aren't really functional changes.

I know. Also the multiple iterations on the highlighting logic aren’t really valuable to keep. My main conditional was not only about squashing *if* but (implicitly) also “only *when* it’s desired”, since squashing messes with reviews, especially since the first commits up to 7ce3e43ca5a6526d37a7b5fe91c63936c0959cd7 had already been reviewed.

**Comment by steffahn** [comment]
@compiler-errors 

Upon second read, what do you mean “into their parents”? I think it makes it *easier* to understand what’s going on if automatically-generated changes by `--bless` are kept separate from the changes that caused these tests to fail/change. I.e. the compiler-changes, …test-cases.rs-changes, and …test-cases.stderr-changes feel appropriate split up into 3 commits IMO.

I was mostly considering squashing the multiple iterations of test-case changes (due to the later addition of special-casing constructors; and perhaps due to upcoming changes if a somehow slightly different pretty-printing is desired) into a single set of change.

**Comment by compiler-errors** [comment]
I mostly meant "bless -> bless -> bless" could get squashed, but I guess this convo doesn't really matter -- my mistake for not reading "before merging" on your original diff. I trust that you can clean up the history sufficiently once it's approved.

**Comment by steffahn** [comment]
I just recalled why I remembered the highlighting logic that’s supposed to make comparing something like `fn(u8)` to `[fn item {foo}: fn()]` easier (in this case by highlighting the parentheses of the `fn(…)`s to pull attention to the mismatching signature in the `[fn item {foo}: fn()]`, too) to be more nontrivial than what I perceived it like today. I.e., I want to tweak this code further. @rustbot author

**Comment by steffahn** [comment]
Oh well… I think “fixing” the logic becomes unnecessarily complicated. For more context, I thought that a diff like
<code>fn<b>()</b></code>
<code>\[<b>fn item</b> {<b>foo</b>}: fn<b>(u32)</b>]</code>

would be nicer than

<code>fn()</code>
<code>\[<b>fn item</b> {<b>foo</b>}: fn(<b>u32</b>)]</code>

because the function signatures don’t line up at all, whereas for something like
<code>fn()</code>
<code>fn(<b>u32</b>)</code>

i.e. where it *does* line up, it’s clearer what the highlighted `u32` relates to.

But generalizing this “correctly” is too complex and not worth it, so those new complications are now removed entirely. The screenshots are outdated now…

**Comment by steffahn** [comment]
Screenshots, updated (same tests as before… perhaps some are slightly redundant now, since those were designed to *also* showcase some cases of the parentheses-highlighting logic, but more tests don’t hurt):
```rs
fn foo() {
    fn f() {}
    fn g() {}
    fn g2() -> u8 {
        0
    }
    fn g3(_: u8) {}

    fn h<T>() {}
    fn h2<T>(_: T) {}

    struct Struct();

    let mut x = f;
    x = || ();
    x = (|| ()) as fn();
    x = (|| 0) as fn() -> u8;
    x = (|_| ()) as fn(u8);
    x = g;
    x = g2;
    x = g3;
    x = Struct;

    let mut y = h::<()>;
    y = h::<u8>;

    let mut y2 = h2::<()>;
    y = h2::<u8>;

    let mut z = g3;
    z = (|| ()) as fn();

    let mut p = (|| ()) as fn();
    p = (|| 0) as fn() -> u8;
    p = (|_| ()) as fn(u8);
    let _: fn() -> u8 = g3;
    let _: fn() -> u16 = g2;
}
```
Screenshot_20220802_233522
Screenshot_20220802_233547
Screenshot_20220802_233620

**Comment by estebank** [comment]
First of all, I love the work you're putting on this. I have a couple of concerns. 1) I generally worry about changing the output too drastically all at once, due to users maybe losing on the familiarity they've built already. This is fine most of the time, and I don't think it applies here, but I wanted to mention it. 2) It seems like [the output for the case in line 17 is slightly easier to understand today](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3dabd539a774ac2b921602700db04045) than with the new output. I think we can improve the output by explicitly looking for cases where we have different signatures and if the signature were to be fixed, then the type error wouldn't happen because the coercion would successfully take over, and produce output that *only* mentions the signature (like a missing return type).

As a simultaneously more general and more bikesheddy feedback, my aesthetic preferences would change something like `[fn item {my_const_fn}: fn(u8) -> u8]` to `[item my_const_fn: fn(u8) -> u8]`.

Also, I know that @BoxyUwU was working on a different formatter for the output of mismatched arguments, where spaces are introduced to make the signatures vertically align, and it'd be great if we could look into introducing that into these cases, so that we could have something like (not too happy with it, but you get the idea):

```
   = note: expected fn item `[fn item foo::<u8>: fn(_, _) -> _]`
           found fn pointer `                    fn(_   ) -> _`
   = help: change the expected type to be function
```

**Comment by estebank** [comment]
You had a good point in the internals thread, about the distinction of `fn item` and `fn pointer` being too subtle and *not highlighted*. Maybe we should also modify that for all E0308 and highlight the parts of the item description that differs always?

**Comment by BoxyUwU** [comment]
I think you pinged the wrong person I wasn't working on that :sweat_smile:

**Comment by estebank** [comment]
HA! I was just looking back on zulip and it was @WaffleLapkin, not you 😅

**Comment by steffahn** [comment]
> It seems like [the output for the case in line 17 is slightly easier to understand today](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3dabd539a774ac2b921602700db04045) than with the new output. I think we can improve the output by explicitly looking for cases where we have different signatures and if the signature were to be fixed, then the type error wouldn't happen because the coercion would successfully take over, and produce output that _only_ mentions the signature (like a missing return type).

I don’t think line 17 is such a case. Maybe you mean lines 36 and 37?

In general, this seems to be impossible to determine in this highlighting logic alone. It’s called both in cases where coercion would be possible, and (e.g. recursively[^1]) in cases where it would *not* be possible. As a long-term improvement, maybe it’s possible to somehow link up highlighting and the type-checking that generated the error message in the first place, so that always *either only* the place that the actual error message talks about is highlighted, *or* such that this place is somehow highlighted stronger, perhaps with color, or maybe with an underline (which would also help in color-less environments). But I wouldn’t know how to pull that off, I haven’t looked at the relevant type-checking logic at all, so far.

---



[^1]: Except… maybe that’s the *only* case where coercion is not an option? In case that’s actually true, then an additional `bool` argument to `cmp` could track whether or not we are in a place where coercion is allowed (not a recursive call). Also last time I checked, there were actually *two* places in rustc source code that called the `cmp` function as an entry point (i.e. calls that aren’t recursive calls), I haven’t understood where the second one comes from yet, and whether or not it’s a place that supports coercion.<br>
I suppose, ***if*** it *is* possible to reliably recognize cases where coercion is possible, then one could both skip highlighting of the `fn item {path…}` part, and perhaps even simplify it to `fn item {_}` if coercion *is* possible and the signatures don’t match, and similarly, it might make sense to not highlight the function signatures at all in cases where coercion *isn’t* possible. Actually… even nicer for the former would be a dedicated error message about the “fn-item-to-fn-pointer” coercion failing, and then that error message only needs to print the function signatures.

> a different formatter for the output of mismatched arguments, where spaces are introduced to make the signatures vertically align, and it'd be great if we could look into introducing that into these cases, so that we could have something like (not too happy with it, but you get the idea):

I’d not a huge fan of introducing spaces like that. Vertically aligning stuff in Rust source code is super rare (because `rustfmt` is popular and it doesn’t align stuff), so from a familiarity standpoint I would thus consider something like
```
    = note: expected fn pointer `fn(Result<Option<[u8; 1024]>, std::io::Error>) -> _`
               found fn pointer `fn(                                          ) -> _`
```
to be rather hard to read. And once the type does no longer fit into a single line, the benefits are mostly lost, anyway.

---





> my aesthetic preferences would change something like `[fn item {my_const_fn}: fn(u8) -> u8]` to `[item my_const_fn: fn(u8) -> u8]`


> It might be that even `fn item` is redundant, it could be `foo::<u8>: fn(_, _) -> _`, as it shouldn't be _too_ confusing.

For the latter, this reads perhaps a bit too much like Rust syntax, suggesting that the type of `foo::<u8>` is literally `fn(_, _) -> _` (a function *pointer* type). The colon is in my approach, too, but only because I considered something like `[fn item {foo::<u8>} with signature fn(_, _) -> _]`, that’s more explicit that this is not specifying the *type* but only the *signature*  of `foo::<u8>`, a bit too lengthy.

For either approach, I don’t think that `path::to::some_function:` reads particularly well, since there’s so many colons in the path already. Also the longer the path becomes the more useful I feel the additional `{}` becomes as an easier-to-find visual indicator for where the end of the path is. E.g. here’s two examples from the changed test outputs:

```
[item <X as T>::bal: for<'r> fn(&'r X) -> usize]
```
vs.
```
[fn item {<X as T>::bal}: for<'r> fn(&'r X) -> usize]
```

and

```
<[item core::f32::<impl f32>::to_bits::ct_f32_to_u32: fn(f32) -> u32] as FnOnce<(f32,)>>::call_once
```
vs.
```
<[fn item {core::f32::<impl f32>::to_bits::ct_f32_to_u32}: fn(f32) -> u32] as FnOnce<(f32,)>>::call_once
```

The only potential problem with the syntax I see so far is the use of `[]`s (though that’s somewhat consistent with other unnamable types, i.e. closures and generators) because those can look like slices, e.g. in
```
error[E0308]: mismatched types
   --> src/main.rs:17:15
    |
 17 |         func: &foo, //~ ERROR mismatched types
    |               ^^^^ expected fn pointer, found fn item
    |
    = note: expected reference `&fn() -> Option<isize>`
               found reference `&[fn item {foo}: fn() -> Option<isize>]`
```

**Comment by estebank** [comment]
Just realized that we already show the description for the type, so we could include the fn name in it instead (which might be a bad idea for really long paths...):

```
   = note: expected fn item `foo::<u8>` `fn(_, _) -> _ {...}`
                       found fn pointer `fn(_) -> _`
```

We still need something (like the `{...}` above) to differentiate items from pointers because they can appear in nested places or in messages on their own, but when they appear in the message or a span label, they usually point at the problem anyways (so it shouldn't add additional confusion).

The problematic case is

```
error[E0308]: mismatched types
   --> src/main.rs:17:15
    |
 17 |         func: &foo, //~ ERROR mismatched types
    |               ^^^^ expected fn pointer, found fn item
    |
    = note: expected reference `&fn() -> Option<isize> {...}`
               found reference `&fn() -> Option<isize> {...}`
```

where now we imply we have two different functions with the same signature. Beyond this PR, we should detect such cases and emit the "you likely want an fn pointer instead" suggestion/help in these cases, but it presents a problem when eliding potentially useful info.

An option here would be to use *only* the name in the item signature, but the full path in the description. That would ensure a relatively short ident and give a fighting chance to users, but would still be terrible in a case where `a::foo` and `b::foo` have the same signature (but we already a similar problem for different crate versions in the dep tree).

*Edit: wait, what am I saying, the formatter for messages goes through pprint, while for E0308 goes through cmp, we can make them diverge.*

All of these cases *could* be checked for in E0308, and use that info to emit a note:

```
error[E0308]: mismatched types
   --> src/main.rs:17:15
    |
 17 |         func: &foo, //~ ERROR mismatched types
    |               ^^^^ expected fn pointer, found fn item
    |
    = note: expected reference `&fn [1]() -> Option<isize>`
               found reference `&fn [2]() -> Option<isize>`
   = note: fn item [1]: `a::foo`
           fn item [2]: `b::foo`
```

----

> I don’t think line 17 is such a case. Maybe you mean lines 36 and 37?

Yes, indeed, I got the expected/found swapped in my head.

>such that this place is somehow highlighted stronger, perhaps with color, or maybe with an underline (which would also help in color-less environments).

Right now the message highlighting only supports bolding (which might be enough), but there's no reason not to extend its feature set. It'd be a smaller change than adding highlighting in the first place was.


---

I know I'm somewhat derailing the conversation by exploring other alternatives in the output, but I'm sure we all agree we want this to be the best it can be :)

**Comment by WaffleLapkin** [comment]
Since I was tagged I would like to add my 2 cents :D

### Alignment

I think argument alignment is clearly out-of scope of this PR and should be done separately (hopefully I won't forget to do this lol). But alignment of signatures, i.e.
```text
   = note: expected fn item `[fn item foo::<u8>: fn(_, _) -> _]`
           found fn pointer `fn(_) -> _`
vs
   = note: expected fn item `[fn item foo::<u8>: fn(_, _) -> _]`
           found fn pointer `                    fn(_) -> _`
```
I think should be included in this PR, since otherwise it makes comparing signatures harder that it is today.

### Brackets

I slightly dislike the square brackets here. If for something like `[type error]` or `[closure...]` which includes "just words" it's somewhat clear that they just for word containment, something like `[fn item foo::<u8>: fn(_, _) -> _]` may be confused with a slice more easily.

Some options:
1. Not use brackets at all (problem: may be confusing with, for example, references `&fn item foo::<u8>: fn(_, _) -> _`)
2. Use angle brackets (problem: angle brackets are generally less readable, `<fn item foo::<u8>: fn(_, _) -> _>`)
3. (1+2) Use angle brackets, but only when otherwise can be confusing (`&<fn item foo::<u8>: fn(_, _) -> _>`, but `Struct<fn item foo::<u8>: fn(_, _) -> _>`)

### Verbosity

I'm slightly worried that by making the types too verbose users will skip-scan more. I know I ignore 80% of an error if it's too big :')

So I think we should try to find a way to make types as small as possible, while preserving the information. One idea that I have is maybe just add an "note: <whatver we've decided will be the syntax...> denotes a function item that has unique type and is different from function pointer (read more: <...>)" whatever fn item type shown in an error. I know that it's basically "let's make verbosity lower by adding more words", but by moving the verbosity to a separate `note` we can make the error easier to scan if you know what you are looking for while at the same time explaining in enough details if you don't know at all what to look for.

This would allow to have a comparatively short type (like `foo::<u8>: fn(_, _) -> _` or even `fn(_, _) -> _ {foo}` 😄 ), while still explaining what it means, so beginners don't struggle with it.

### Shorthand

When function-like things are directly compared, we should probably use what @estebank suggested with moving the "fn item" to description (+highlight `item`&`pointer`?):
```text
   = note: expected fn item `foo::<u8>` `fn(_, _) -> _`
                       found fn pointer `fn(_) -> _`
```
So that we don't use additional syntax when it's not needed.

### Conclusion?

For me, personally, I would want to see something like this, after this PR:

```text
   = note: expected fn item `foo::<u8>` `fn(_, _) -> _`
                       found fn pointer `fn(_) -> _`
   = note: to learn more about `fn` item/pointer difference see <link to docs or whatever>


   = note: expected reference `&fn foo() -> Option<isize>`
              found reference `&fn bar() -> Option<isize>`
   = note: `fn name(..) -> ..` denotes a fn-item which is different from fn-pointer
   = note: different `fn` items always have unique types, even if their signatures are the same
   = note: to learn more about `fn` items see <link to docs or whatever #2>


   = note: expected reference `&fn foo() -> Option<isize>`
              found reference `&    fn() -> Option<isize>`
   = note: `fn name(..) -> ..` denotes a fn-item which is different from fn-pointer
   = note: to learn more about `fn` item/pointer difference see <link to docs or whatever>
```

Maybe that's a little to much? idk...

### Uh

There is so much to tweak around, that I fear we'll soon get stuck in all these "600 words gh comments" 😅 
I wander how can we split this task into smaller ones.

**Comment by steffahn** [comment]
> ```
> = note: expected fn item `foo::<u8>` `fn(_, _) -> _`
>                        found fn pointer `fn(_) -> _`
>    = note: to learn more about `fn` item/pointer difference see <link to docs or whatever>
> ```

I don’t like this as it kills the clear distinction between fn item types and fn pointer types. There is many clear user experience, including from fairly experienced users, where the *lack* of clear visual distinction between fn pointer types and fn item types led to large confusion. Large confusion means, that the misinterpretation was not noticed, even after some reasonable thinking / reconsideration. There’s the experience of jonhoo in the linked IRLO thread. There’s a new issue that just linked to this one. And probably thousands of unreported additional cases. I believe the *default must* be that fn item types and fn pointer types look fundamentally different. Only in very special cases, i.e. when we’re 100% certain that the signature mismatch is *the only* problem (i.e. when coercion would otherwise be able to happen) can the error message hide the syntactic difference; I think the right principle for this is opt-out (of the clear distinction) though, not opt-in; so that all generic error messages mentioning the type become clearly understandable.

Another reason I hate `fn(args) -> return {path}` is that it looks like it’s official Rust syntax, even though it’s only a stand-in for a voldemort-type. This next proposal has the same problem:

  
> ```
> = note: expected reference `&fn foo() -> Option<isize>`
>               found reference `&fn bar() -> Option<isize>`
>    = note: `fn name(..) -> ..` denotes a fn-item which is different from fn-pointer
>    = note: different `fn` items always have unique types, even if their signatures are the same
>    = note: to learn more about `fn` items see <link to docs or whatever #2>
> ```

I don’t think we should invent non-existing syntax for types. `fn foo() -> Option<isize>` is not an actual type in Rust. Never. Rendering a voldemort-type should clearly be some clear non-syntax IMO. Inventing something “neat-looking” but non-existent is exactly the premise that leads to something like `fn() -> Option<isiz> {foo}` and thus exactly what leads to confusion. For short names, many people will overlook the difference between `fn foo() -> Option<isize>` and `fn() -> Option<isize>`, and with long names, something like

`
for<'a> fn <path::to::Type as other::path::to::Trait<some::type::Argument<u32>>>::method::<some::GenericArg>(&path::to::Type, &'a <path::to::Type as other::path::to::Trait<some::type::Argument<u32>>>::Associated) -> Result<u8, path::to::Error>
`

is not particularly easy to read, while 

`
[fn item {<path::to::Type as other::path::to::Trait<some::type::Argument<u32>>>::method::<some::GenericArg>}: for<'a> fn(&path::to::Type, &'a <path::to::Type as other::path::to::Trait<some::type::Argument<u32>>>::Associated) -> Result<u8, path::to::Error>]
`

isn’t very nice either, but IMO more easy to approach.

---

While notes such as “`fn name(..) -> ..` denotes a fn-item which is different from fn-pointer`” are useful in principle, they cannot be placed *everywhere* the type appears. Can be a mismatched types error message, can be a missing trait implementation, or others, there will always be cases where this helpful note is *not* available, so the fn item type should be understandable *without* extra notes, too.

Regarding short types, technically, the signature is not necessary at all. The thing could as well just be called `[fn item foo::bar::<Baz>]`. I’m currently liking to keep the signature because it means fewer changes, so fewer possibilities for regression in user experience. If some people used to rely on seeing the function signature in error messages mentioning fn items, then I would like to avoid breaking this. Also it’s a smaller change. As I already mentioned earlier, the change is really just three small things: 
* inverted order between path and signature
* additional `[]`s around the whole thing
* more self-descriptive by saying it’s a `fn item`. (I wouldn’t mind `function item` either, but that makes for some inconsistent-looking error messages, and also the item is literally called `fn` in Rust code, so yeah…)

This means that `SIGNATURE {PATH}` merely becomes `[fn item {PATH}: SIGNATURE]` which should be easy to understand for everyone used to the old notation.

---



> This would allow to have a comparatively short type (like `foo::<u8>: fn(_, _) -> _` or even `fn(_, _) -> _ {foo}`  ), while still explaining what it means, so beginners don't struggle with it.

I would like to emphasize that in my experience it’s ***not “just beginners”*** that can have problems. Rust does a ***really effective*** job at hiding the difference between fn items and fn pointers in its source code, by how similar function items and function pointer types look and with the implicit coercions in place, to the point where people who I would consider “non-beginners” might not have a clear understanding of it yet[^1] either; so there’s no need to continue this scheme in error messages, too.

[^1]: And even once they finally understand the distinction, they would then, as a subsequent step, need to learn the subtle way in which this distinction is expressed in compiler error messages.<br><br>I would prefer the opposite approach. Where you currently *first* need to (independently) learn enough about the language, to *then* be able to learn to spot the difference in error messages, instead the differences should be obvious and *drive* the learning experience that fn item types and fn pointer types are fundamentally different things.

---


> I slightly dislike the square brackets here. If for something like `[type error]` or `[closure...]` which includes "just words" it's somewhat clear that they just for word containment, something like `[fn item foo::<u8>: fn(_, _) -> _]` may be confused with a slice more easily.
> 
> Some options:
> 
> 1. Not use brackets at all (problem: may be confusing with, for example, references `&fn item foo::<u8>: fn(_, _) -> _`)
> 2. Use angle brackets (problem: angle brackets are generally less readable, `<fn item foo::<u8>: fn(_, _) -> _>`)
> 3. (1+2) Use angle brackets, but only when otherwise can be confusing (`&<fn item foo::<u8>: fn(_, _) -> _>`, but `Struct<fn item foo::<u8>: fn(_, _) -> _>`)

I agree with you and slightly dislike it, too. At least in contexts where there isn’t a reference type `&[fn item {foo}: fn()]` or `&mut [fn item {foo}: fn()]`, the potential for confusion should be limited. Or maybe more words could help. One potential scheme that comes to mind is to say something including “type of”

`[type of {foo::bar::<Baz>}: fn() -> Option<Baz>]`

alternative things I previously considered to make this more-clearly non-syntax:
* write the full word `function` as in `[function item {foo::bar::<Baz>}: fn() -> Option<Baz>]`
* use a hyphen, as in `[fn-item {foo::bar::<Baz>}: fn() -> Option<Baz>]`

I think I would like to reconsider in particular whether the hyphen could be an improvement.

Besides the outer `[]` braces, I’m also open for suggestions on alternatives for the `{}`s, though I do find those non-confusing and useful for readability; and also they can help people who were familiar with the old `fn() -> Option<Baz> {foo::bar::<Baz>}` style

---

> ```
>    = note: expected reference `&fn foo() -> Option<isize>`
>               found reference `&    fn() -> Option<isize>`
> ```

As noted above, I personally find additional spaces looks weird, as it’s really uncommon in rust code formatting. Also, if the spacing gets large and the line is broken, things get confusing.

imagine the lines are broken by the terminal…
```
   = note: expected reference `&fn <Foo<Bar, Baz> as Trait<Qux<A, B, C>, D>>::me
thod() -> Option<isize>`
              found reference `&                                                
  fn() -> Option<isize>`
```
or
```
   = note: expected reference `&fn <Foo<
Bar, Baz> as Trait<Qux<A, B, C>, D>>::me
thod() -> Option<isize>`
              found reference `&        
                                        
  fn() -> Option<isize>`
```
and even without line-breaks, super-large gaps in types can become weird
```
   = note: expected reference `&fn <Foo<Bar, Baz> as Trait<Qux<A, B, C>, D>>::method() -> Option<isize>`
              found reference `&                                                  fn() -> Option<isize>`
```

---


Though that’s a separate discussion; except that you suggested



> But alignment of signatures, i.e.
> 
> ```
>    = note: expected fn item `[fn item foo::<u8>: fn(_, _) -> _]`
>            found fn pointer `fn(_) -> _`
> vs
>    = note: expected fn item `[fn item foo::<u8>: fn(_, _) -> _]`
>            found fn pointer `                    fn(_) -> _`
> ```
> 
> I think should be included in this PR, since otherwise it makes comparing signatures harder that it is today.

And I’m not sure how that’s supposed to work exactly. The types might be mis-aligned in the first place. E.g.
```
  = note: expected tuple `(usize, fn(), fn())`
             found tuple `(u8, [fn item {f}: fn()], [fn item {g}: fn()])`
```
It woudln’t make much sense to introduce alignment here because the types *start out* as misaligned. Similarly, alignment would semi-randomly appear and disappear between cases that go through `.cmp` and cases that just pretty-print the types, e.g.
```
  = note: expected tuple `(fn(), fn(), u8)`
             found tuple `([fn item {f}: fn()], [fn item {g}: fn()])`
```

vs
```
  = note: expected tuple `(              fn() ,               fn() )`
             found tuple `([fn item {f}: fn()], [fn item {g}: fn()])`
```
whereas currently, such cases only differ more subtly in how much is or isn’t highlighted.

Finally, in most cases, the *main* difference is between function ptr vs function item anyways; aligning the signatures would suggest that the mismatching signatures are the main problem. (Highlighting the signatures does this already, partially, too, but I’m retaining the status quo in this regard. As in my previous answer’s footnote, if there’s a reliable way to detect and specially-handle (in terms of error messages) the cases where coercions *would* be possible, then in non-coercion settings, the signature could be completely non-highlighted or even hidden (e.g. with an `_`). But I consider this stuff for future PRs.)

**Comment by steffahn** [comment]
Given the large number of affected files, merge conflicts in test outputs are inevitable, and it won't make sense to fix them before there is agreement that this PR should be merged in the first place.

**Comment by estebank** [comment]
[We'll have](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-09-15/near/298983454) a t-compiler meeting to follow up on this.

There's a subset of this PR that I think is uncontroversial (and could be landed faster), but for the larger visible representation of the output I believe merits discussion.

**Comment by estebank** [comment]
Apologies, I failed to create a meeting to address this. I'll do so shortly.

CC #19939

**Comment by estebank** [comment]
Opened https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/More.20distinctive.20pretty-printing.20of.20function.20item.20types to try and arrive to agreement on what the output *should* be.

**Comment by apiraino** [comment]
I'll label this as `S-blocked` trying to signal that a consensus should be reached to move on.

@rustbot label S-blocked

**Comment by jackh726** [comment]
Changing this to waiting-on-team, since that's a more appropriate label than blocked (since there is no concrete item to unblock this)

**Comment by wesleywiser** [comment]
Visited during the compiler team triage meeting. There was some rough consensus that [@bstrie's suggestion from Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/More.20distinctive.20pretty-printing.20of.20function.20item.20types/near/316776018) might be a reasonable compromise between concerns:

> trying to highlight the difference between function pointers/function items solely by making their as-written-in-the-source-code types distinct (and then trying to future-proof that syntax) might be worse than just having a note like "note: foo is a function item, which is distinct from a function pointer". 

We think it would be useful to try implementing that informational note and then re-evaluate how well the diagnostics work after that.

**Comment by estebank** [comment]
CC https://github.com/rust-lang/compiler-team/issues/675

**Comment by apiraino** [comment]
[mcp#675](https://github.com/rust-lang/compiler-team/issues/675) has been accepted.

cc @steffahn for the next steps (also, a rebase)

@rustbot author

**Comment by Dylan-DPC** [comment]
@steffahn any updates on this? thanks

**Comment by steffahn** [comment]
Thanks for the ping. I missed that there was a call to action in the last reply. Sure, I can rebase and get this into working condition again, now with `{…}` instead of `[…]`.

**Comment by Dylan-DPC** [comment]
@steffahn any updates since the last check? thanks

**Comment by Dylan-DPC** [comment]
Closing this pr as it's been inactive for a long time. Feel free to reöpen if you plan on continuing otherwise preferably open a new pr and link the approved MCP.

**Pull request closed without merging**
