### PR TITLE
[WIP] Use `DefPath` instead of `Cache.stack` for `Cache.paths`

### PR DESCRIPTION
**Pull request by camelid**
All empty or anonymous segments are skipped.

After this, I'll be able to remove `Cache.stack`.

r? @ghost
cc @jyn514

### CODE REVIEW

**Comment by camelid** [comment]
I was having weird linker errors with some of (or all of?) the rustdoc `auxiliary` tests. I'm not sure what's going on, so let's see if they happen on CI.

**Comment by camelid** [comment]
CI did indeed fail, but without linker errors...

**Comment by jyn514** [comment]
Hi @camelid, are you planning to follow-up on this?

**Comment by camelid** [comment]
> Hi @camelid, are you planning to follow-up on this?

I tried to recently but got stuck trying to get the user-visible name for proc macro derives.

**Comment by jyn514** [comment]
Ah right, I remember seeing that. I glanced around rustc_expand briefly - I found `parse_macro_name_and_helper_attrs` which looks vaguely right, maybe you could use that by getting the attributes for the item if you know it's a proc-macro?

**Comment by camelid** [comment]
> Ah right, I remember seeing that. I glanced around rustc_expand briefly - I found `parse_macro_name_and_helper_attrs` which looks vaguely right, maybe you could use that by getting the attributes for the item if you know it's a proc-macro?

Hmm, okay, that looks potentially promising.

**Comment by camelid** [comment]
I'd like to get back to this at some point, but I'm going to close it for now so it doesn't just sit getting stale.

**Pull request closed without merging**
