### PR TITLE
Flatten/inline format_args!() and (string and int) literal arguments into format_args!()

### PR DESCRIPTION
**Pull request by m-ou-se**
Implements https://github.com/rust-lang/rust/issues/78356

Gated behind `-Zflatten-format-args=yes`.

Part of #99012

This change inlines string literals, integer literals and nested format_args!() into format_args!() during ast lowering, making all of the following pairs result in equivalent hir:

```rust
println!("Hello, {}!", "World");
println!("Hello, World!");
```

```rust
println!("[info] {}", format_args!("error"));
println!("[info] error");
```

```rust
println!("[{}] {}", status, format_args!("error: {}", msg));
println!("[{}] error: {}", status, msg);
```

```rust
println!("{} + {} = {}", 1, 2, 1 + 2);
println!("1 + 2 = {}", 1 + 2);
```

And so on.

This is useful for macros. E.g. a `log::info!()` macro could just pass the tokens from the user directly into a `format_args!()` that gets efficiently flattened/inlined into a `format_args!("info: {}")`.

It also means that `dbg!(x)` will have its file, line, and expression name inlined:

```rust
eprintln!("[{}:{}] {} = {:#?}", file!(), line!(), stringify!(x), x); // before
eprintln!("[example.rs:1] x = {:#?}", x); // after
```

Which can be nice in some cases, but also means a lot more unique static strings than before if dbg!() is used a lot.

### CODE REVIEW

**Comment by m-ou-se** [comment]
Looks like clippy's tests are now failing because clippy looks at the hir for its format_args!() lints. Now that rustc_ast_lowering flattens/inlines format arguments, many of its lints no longer trigger.

As soon as #106745 is merge, we should change clippy to use the new ast::FormatArgs instead, to unblock changes like this one.

**Comment by m-ou-se** [comment]
Very curious to see what direction the perf results will go. Things could improve because the fmt::Arguments get simpler, but it could also get worse because strings might now get duplicated. (Like the dbg!() expansion as explained above.) (If that's a problem, maybe we can just put a limit on the string length for inlining.)

**Comment by matthiaskrgr** [comment]
>but it could also get worse because strings might now get duplicated. 

Perhaps this could be disabled for `-Copt-level=z`?

**Comment by m-ou-se** [comment]
No, because things like `format_args!("{}{}{}", "a", "b", "c")` do get a lot smaller if they're turned into `format_args!("abc")`. Determining in which cases things get smaller vs bigger is quite tricky.

**Comment by matthiaskrgr** [comment]
Argh right.. Waiting for link-time mir optimizations then :smile:

**Comment by est31** [comment]
> ```rust
> println!("[{}] {}", status, format_args!("error: {}", 123));
> println!("[{}] error: {}", status, 123);
> ```

Wouldn't this get turned into `println!("[123] error: {}", status);` instead?

Also, you should maybe change the "string literal" into "literal" (dropping the string) in your PR's title, because the code seems to be inlining integer literals as well (but not float literals it seems).

**Comment by m-ou-se** [comment]
> Wouldn't this get turned into `println!("[123] error: {}", status);` instead?

Why? That'd be incorrect.

**Comment by m-ou-se** [comment]
Oh I didn't update the PR title and description yet for inlining integers. Updating now.

**Comment by est31** [comment]
> > Wouldn't this get turned into `println!("[123] error: {}", status);` instead?
> 
> Why? That'd be incorrect.

Oh sorry I meant `println!("[{}] error: 123", status);` of course :).

Thanks for the updates!

**Comment by m-ou-se** [comment]
Those results include the changes of #106745.

This is the diff of this PR relative to #106745: <https://perf.rust-lang.org/compare.html?start=e36affffe97378a0027b4bcfbb18d27356164ed0&end=b19488dba41be7ad94ed1d2933dd71ff8a300b37&stat=instructions:u>

**Comment by joshtriplett** [comment]
@m-ou-se Do you have code size numbers for the `eprintln` case involving filenames and line numbers? If you compile one, or ten, instances of that pattern, with and without this optimization, what are the net sizes of the code and data? Given how many calls to `write` this avoids, and invocations of format machinery, I'd expect it's a net win despite all the extra string constants. But in any case, we could use that to tune thresholds for things like optimize-for-size vs optimize-for-speed.

**Comment by m-ou-se** [comment]
@joshtriplett looks like you're be right. Quickly tried some example with 11 dbg!() statements, and it went down from a .text section of 12967 bytes to 9407 bytes.

**Comment by Kobzol** [comment]
[Here](https://perf.rust-lang.org/compare.html?start=0b90256ada21c6a81b4c18f2c7a23151ab5fc232&end=b19488dba41be7ad94ed1d2933dd71ff8a300b37&stat=size%3Alinked_artifact) are the binary size changes from the latest CI run of this PR.

**Comment by joshtriplett** [comment]
This looks great, overall. Performance generally gets better (the regressions don't seem important), size gets better...

I think, based on the data we have so far, we should just ship this.

**Comment by joshtriplett** [comment]
Tagging as perf-regression-triaged: it appears to be a larger win almost across the board, with a few much smaller regressions. Seems like a net win on balance.

**Comment by est31** [comment]
Just a note, this PR does have an impact on the ability to use some constructs in const panic. E.g. `panic!("{}", "Hello")` will become legal with this PR in const contexts. This doesn't mean that `const fn` is gaining any new capabilities though, as the transformation is happening very early on. Basically `format_args` is still a glorified macro, it just benefits from the fact of running its things post-expansion of all other macros (the compiler having parsed int/float literals helps too).

**Comment by m-ou-se** [comment]
> E.g. `panic!("{}", "Hello")` will become legal with this PR in const contexts.

`panic!("{}", ..)` specifically already happens to be legal (`"{}"` is special cased), but yeah, `panic!("hello {}", "world")` would also be accepted. That's still on my to do list for this PR to fix. But maybe it's time to start thinking about accepting all panic!() in const, regardless of whether the actual message can be formatted in const or not. I'll write something down about that option soon.

**Comment by clarfonthey** [comment]
> But maybe it's time to start thinking about accepting all panic!() in const, regardless of whether the actual message can be formatted in const or not. I'll write something down about that option soon.

#103639 at least is attempting a subset of this, so, might be worth comparing notes.

**Comment by Kobzol** [comment]
> This is the diff of this PR relative to #106745: https://perf.rust-lang.org/compare.html?start=e36affffe97378a0027b4bcfbb18d27356164ed0&end=b19488dba41be7ad94ed1d2933dd71ff8a300b37&stat=instructions:u

Just a note, comparing perf. runs like this can be a bit tricky, because they are measured against a different base (master) commit. Hopefully it will be possible to remedy this in a future bors update.

In other words, we should rerun perf, since https://github.com/rust-lang/rust/pull/106745 is merged now.

**Comment by nbdd0121** [comment]
> > E.g. `panic!("{}", "Hello")` will become legal with this PR in const contexts.
> 
> `panic!("{}", ..)` specifically already happens to be legal (`"{}"` is special cased), but yeah, `panic!("hello {}", "world")` would also be accepted and currently isn't. That's still on my to do list for this PR to fix. But maybe it's time to start thinking about accepting all panic!() in const, regardless of whether the actual message can be formatted in const or not. I'll write something down about that option soon.

There was #90488 which does that but was rejected.

**Comment by est31** [comment]
Sorry for furthering the off-topic discussion, but @nbdd0121 's PR also had a zulip thread [here](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/const.20panic!.20for.20all.20types.20.2390488), which contains some further discussion on the question. The core issue regarding allowing any type in const panic is the desire to require `const Display` impls for params in const contexts. That is actually quite quickly added: just add a `~const` to the `T: Display` bound of the `new_display` function.

I have worked on a [branch](https://github.com/est31/rust/tree/const_display) to figure out the current const eval system's limitations regarding supporting formatting panics to `const fn`. The `dyn Trait` problem I could avoid with an union (quite a hack but it works for panics), but the ultimate problem I've faced that I couldn't solve was the inability to call `fn` pointers in `const fn` (#63997).

One needs to have one of:
* no distinction between `fn` pointers and `const fn` pointers in the type system, plus the ability to call `fn` pointers in a `const` context, with a const eval error when the underlying function is *not* a `const fn`. The const eval system is already tracking fn pointers, const or not, all one needs to do is implement the "call a const fn" primitive in `compiler/rustc_const_eval/src/transform/check_consts/check.rs`.
* an existing distinction between `fn` pointers and `const fn` pointers, but then with the ability to transmute a `const fn` into a non `const fn` type and back, and then being able to call that `const fn` pointer in a const fn.

The `fn` pointer issue arises from the erasure step in the formatting internals. If you have e.g. a `{}` argument with data `v`, you'd have a `new_display(v)` call after lowering, which internally creates a `fn` pointer to `<T as Display>::fmt`, with predetermined `T`, passing it to a function that performs a type erasure, with the `fn` pointer for `T` being transmuted from taking `&T` into taking `&Opaque` (together with a similar transmute of the data to `&Opaque`). That function pointer is stored and later called.

If you want `format!` et al to work in general, then you'd also need const alloc and `dyn Trait` function calling support.

**Comment by m-ou-se** [comment]
> E.g. `panic!("{}", "Hello")` will become legal with this PR in const contexts.

That's fixed now.

I've turned `Arguments::new_v1` and `Arguments::new_v1_formatted` back into _non-const_ functions, and added a new const `Arguments::new_const` function that is only used if the format arguments _before_ flattening didn't have any arguments.

**Comment by m-ou-se** [comment]
Which means this PR is ready for rewiew!

r? @oli-obk

**Comment by m-ou-se** [comment]
@bors try @rust-timer queue

(Not sure if this is the best benchmark to test this PR, but let's see what we get.)

**Comment by m-ou-se** [comment]
Oh actually, this is completely blocked by https://github.com/rust-lang/rust-clippy/issues/10233, because Clippy currently digs through the hir to reconstruct the original format_args!() invocation.

**Comment by nbdd0121** [comment]
I'd like to see a test asserting
```rust
const C: i32 = 1;
assert!(format_args!("{}", C).as_str().is_none());
assert!(format_args!("{}", {""}).as_str().is_none());
let a = format_args!("A");
assert!(format_args!("{}", a).as_str().is_none());
```
and some others to ensure that these don't get accidentally changed.

P.S. the PR description only says string literal (without mentioning int) even though the PR title and the example shows int literals getting inlined.

**Comment by m-ou-se** [comment]
@rust-timer build 5e689d89b16f507b86bf703059ac94eab45b2686

**Comment by m-ou-se** [comment]
I've now put the flattening/inlining behind a new unstable flag (-Zflatten-format-args=yes) (see https://github.com/rust-lang/rust/pull/106824/commits/995e57b89efc00e967100d6e7c36b55315bf3cd7), so we can merge this without having to wait for the blockers, so people can try it out on nightly.

**Comment by m-ou-se** [comment]
Which means this should be ready for review now ^^

r? @oli-obk

**Comment by oli-obk** [comment]
r=me with a test that uses the flag and CI happy.

**Comment by nnethercote** [comment]
The few small secondary regressions here are outweighed by the few small primary improvements.

@rustbot label: +perf-regression-triaged

**Pull request merged**
