### PR TITLE
Reduce max hash in raw strings from u16 to u8

### PR DESCRIPTION
**Pull request by GrishaVar**
[Relevant discussion](https://rust-lang.zulipchat.com/#narrow/stream/237824-t-lang.2Fdoc/topic/Max.20raw.20string.20delimiters)

https://github.com/rust-lang/reference/pull/1180 is the corresponding reference change.

### CODE REVIEW

**Comment by nnethercote** [comment]
The changes are good, but there are some clippy changes still required, as showed by the CI failures. How are you building the compiler? A command like `./x.py build --stage 1 library/std` won't build clippy... just run `./x.py check` to compile everything, including clippy.

**Comment by GrishaVar** [comment]
Running `./x.py check` passes successfully, but the CI failed with the latest commit. It's a bit strange, the error the CI failed with is what the recent commit fixed.

**Comment by nnethercote** [comment]
I think you're still seeing the old CI results? Let's try this:

@bors try

**Comment by nnethercote** [comment]
I don't know why bors hasn't started running the tests, that should have worked.

@bors try

**Comment by nnethercote** [comment]
Well, the changes seem fine, let's see what happens if I approve it.

@bors r+

**Comment by Dylan-DPC** [comment]
failecd in [rollup](https://github.com/rust-lang/rust/pull/95322#issuecomment-1079541228)

**Comment by nnethercote** [comment]
Somehow the rollup didn't use the 3rd commit. Let's try again.

@bors rollup=always

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/95391#issuecomment-1080093191)

@bors r-

**Comment by nnethercote** [comment]
@GrishaVar It might be worth squashing the three commits into one. That way no commits can be missed when a rollup occurs...

**Comment by dtolnay** [comment]
FYI @rust-lang/lang in case anyone considers an FCP necessary for this.

Here is an example of a program that this would affect:

```rust
fn main() {
    let _ = r###################################################################################################################################################################################################################################################################" "###################################################################################################################################################################################################################################################################;
}
```

**Review by dtolnay — CHANGES_REQUESTED** [review]
The text in the diagnostic needs to be updated.

https://github.com/rust-lang/rust/blob/3badf5c51c33f15c3934ea0e91d27f60c8605024/compiler/rustc_parse/src/lexer/mod.rs#L595-L602

Also, the following comment no longer applies. Please remove the comment and add a ui test.

https://github.com/rust-lang/rust/blob/3badf5c51c33f15c3934ea0e91d27f60c8605024/compiler/rustc_parse/src/lexer/mod.rs#L592-L593

**Comment by scottmcm** [comment]
Apparently the last time this was brought up the lang team said 255 would be fine: https://github.com/rust-lang/rust/pull/50296#issuecomment-388160936

I agree with that; it fits my rough heuristic of "an order of magnitude more than any plausible situation" -- I think that by the time 20 or so isn't enough, 200 isn't really going to solve the problem, let along 20000.

That said, I'm surprised there isn't a perf report here to see max-rss or whatever.  So I'll try to kick off a

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
> That said, I'm surprised there isn't a perf report here to see max-rss or whatever.

No change is expected for memory usage. This is a pre-emptive "this might reduce memory usage in the future if some struct definitions change" situation.

**Comment by Dylan-DPC** [comment]
@nnethercote the third commit is in a submodule which could be a reason it was excluded

**Comment by dtolnay** [comment]
Close+reopen usually works for bors to pick up an updated state after outage.

**Comment by GrishaVar** [comment]
> Also, the following comment no longer applies. Please remove the comment and add a ui test.
> 
> https://github.com/rust-lang/rust/blob/3badf5c51c33f15c3934ea0e91d27f60c8605024/compiler/rustc_parse/src/lexer/mod.rs#L592-L593

I added a test for this in #94993. The 65k was changed to 255 in this PR

**Pull request merged**
