### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Zalathar**
Successful merges:

 - #131323 (Support `clobber_abi` in AVR inline assembly)
 - #133092 (Always set the deployment target when building std)
 - #133134 (Don't use a SyntheticProvider for literally every type)
 - #133538 (Better diagnostic for fn items in variadic functions)
 - #133590 (Rename `-Zparse-only`)
 - #133592 (Misc: better instructions for envrc, ignore `/build` instead of `build/`)
 - #133608 (Revert #133418 (Store coverage source regions as `Span`) due to regression #133606)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=131323,133092,133134,133538,133590,133592,133608)

### CODE REVIEW

**Comment by Zalathar** [comment]
I would like the revert in #133608 to land before the next nightly, but to be polite to the rest of the queue I've included it in this rollup first.

**Comment by jieyouxu** [comment]
Can't tell if genuine, retrying
@bors retry

**Pull request closed without merging**
