### PR TITLE
rustc_metadata: Deduplicate code between `encode_info_for_item`, `encode_info_for_foreign_item`, `encode_info_for_trait_item`, and `encode_info_for_impl_item`

### PR DESCRIPTION
**Pull request by pitaj**
For #77393 

r? @petrochenkov 

Todo:

- [x] Dedupe item and foreign_item
- [ ] Review for item/foreign_item dedupe
  - Function / parameter naming?
- [ ] Dedupe trait_item and impl_item
- [ ] Dedupe item_foreign_item_common and trait_impl_item_common

### CODE REVIEW

**Comment by petrochenkov** [comment]
@pitaj 
I'll look at this some time closer to the end of the week, most likely.

**Comment by petrochenkov** [comment]
I'm going to reassign this to r? @oli-obk who requested this change in https://github.com/rust-lang/rust/pull/77375#discussion_r498013190.
With so few things shared and so many boolean flags passed, I'm not sure this is an improvement.

**Comment by oli-obk** [comment]
Yea, these boolean flags do not make the code less fragile. I think we should still do this PR, but just remove all the boolean flags and keep the individual logic to each call site. We can also create multiple functions if we want to share more, but I think starting out with just the minimal implementation that deduplicates the code that is actually shared is the best way forward. Once that is a real improvement over the status quo, we can look at the call sites to see whether creating more functions for a subset of the call sites is helpful

**Comment by pitaj** [comment]
I've removed the boolean flags. Turns out they have 8 lines fully in common. All others are gated but I can see some opportunities to increase that number.

- `generics`, `explicit_predicates`, `inferred_outlives` are included in 9 other methods
  Only `encode_generics` is used on its own, all other instances have all three
- Could `encode_variances_of` be modified to ignore items without variances? (Or maybe the underlying `TyCtxt::variances_of`)
- Could `encode_item_type` be modified to ignore non-type items? (Or maybe the underlying `TyCtxt::type_of`)
- Maybe we could create `encode_fn_sig` that likewise ignores non-fn items (Or maybe the underlying `TyCtxt::fn_sig`)

**Comment by oli-obk** [comment]
We already have a conditional function like this: `encode_optimized_mir`. But I really dislike that (it caused some problems in a branch I wrote this week, so my dislike has a lot of bias and may be entirely unfounded). I'm actually moving away from the conditional version in my branch and changing the callers to decide whether to call it.

grouping generics, predicates and outlives bounds together does make sense. We could call it `encode_bounds` maybe?

**Comment by pitaj** [comment]
> grouping generics, predicates and outlives bounds together does make sense. We could call it `encode_bounds` maybe?

I added `encode_bounds`. I moved the bodies of `encode_explicit_predicates` and `encode_inferred_outlives` into `encode_bounds`, since they weren't used anywhere but in `encode_bounds` after the other changes.

> I'm actually moving away from the conditional version in my branch and changing the callers to decide whether to call it.

I seems to me that logic already exists in the `TyCtxt` methods. Consider `variances_of`, where the check occurs both in `rustc_metadata::encoder` and in `rustc_typeck::variance`

https://github.com/rust-lang/rust/blob/430feb24a46993e5073c1bb1b39da190d83fa2bf/compiler/rustc_metadata/src/rmeta/encoder.rs#L1378-L1384

https://github.com/rust-lang/rust/blob/430feb24a46993e5073c1bb1b39da190d83fa2bf/compiler/rustc_metadata/src/rmeta/encoder.rs#L1732-L1735

https://github.com/rust-lang/rust/blob/430feb24a46993e5073c1bb1b39da190d83fa2bf/compiler/rustc_typeck/src/variance/mod.rs#L48-L55

https://github.com/rust-lang/rust/blob/430feb24a46993e5073c1bb1b39da190d83fa2bf/compiler/rustc_typeck/src/variance/mod.rs#L69-L73

I'm not sure how possible it is to reuse this logic in encoder, but that would be pretty nice.

**Comment by oli-obk** [comment]
Ok, I see. Those kind of checks are okay. The case of `encode_optimized_mir` it was using `self.tcx.mir_keys(LOCAL_CRATE).contains(&def_id)` which seems very ad-hoc. The checks that you showed are explicitly checking for items that we should ignore/encode, so that's ok. Basically if the "root information" for making the decision is checked, I'm fine with it, but if it's just a symptom of the decision, that's too fragile imo.

**Comment by crlf0710** [comment]
@pitaj  Ping from triage! What's the current status of this?

**Comment by pitaj** [comment]
Thanks for checking in. I haven't forgotten about this, just been focused on other things.

**Comment by JohnCSimon** [comment]
triage: I'm closing this PR as inactive 

@pitaj - if this PR in progress, please feel free to reopen

**Pull request closed without merging**
