### PR TITLE
Hide default impls items

### LINKED ISSUE #54025: docs: hide undocumented items in trait impls
More info in #51885.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow up of #51885.
Fixes #54025.

cc @Mark-Simulacrum 

r? @QuietMisdreavus 

And screenshots of course:

screen shot 2018-09-12 at 23 30 35

screen shot 2018-09-12 at 23 30 42

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by Aaronepower** [comment]
Triage; @QuietMisdreavus Hello, are you able to review this PR?

**Comment by GuillaumeGomez** [comment]
@Aaronepower: Not ready yet so reviewing wouldn't be very useful for the moment...

**Comment by GuillaumeGomez** [comment]
Still need to be updated. Trying to do more urgent issues first.

**Comment by TimNN** [comment]
Ping from triage @GuillaumeGomez: it looks like some updates have been requested to your PR.

**Comment by GuillaumeGomez** [comment]
I'll update it in the next days.

**Review by QuietMisdreavus — APPROVED** [review]
r=me pending travis

**Comment by QuietMisdreavus** [comment]
```
[01:20:09] ---- [rustdoc] rustdoc/assoc-consts.rs stdout ----
[01:20:09] 
[01:20:09] error: htmldocck failed!
[01:20:09] status: exit code: 1
[01:20:09] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/assoc-consts" "/checkout/src/test/rustdoc/assoc-consts.rs"
[01:20:09] stdout:
[01:20:09] ------------------------------------------
[01:20:09] 
[01:20:09] ------------------------------------------
[01:20:09] stderr:
[01:20:09] ------------------------------------------
[01:20:09] 102: @has check failed
[01:20:09] 	`XPATH PATTERN` did not match
[01:20:09] 	    // @has - '//*[@class="docblock"]' "Docs for QUX_DEFAULT12 in trait."
[01:20:09] 
[01:20:09] Encountered 1 errors
[01:20:09] 
[01:20:09] ------------------------------------------
[01:20:09] 
[01:20:09] thread '[rustdoc] rustdoc/assoc-consts.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3284:9
[01:20:09] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:20:09] 
[01:20:09] 
[01:20:09] failures:
[01:20:09]     [rustdoc] rustdoc/assoc-consts.rs
```

This is the second `QUX_DEFAULT12`, the one from the impl. Is the code removing the override docs entirely, somehow?

**Comment by GuillaumeGomez** [comment]
I think the problem is a missing class here.

**Comment by GuillaumeGomez** [comment]
Updated the failing test accordingly.

**Pull request merged**
