### PR TITLE
[do not merge] Benchmark parallel queries on perf.rlo.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Let's see how they are doing these days.

cc @Zoxc @nikomatsakis

### CODE REVIEW

**Comment by Zoxc** [comment]
Probably won't get far if bors runs tests =P

**Comment by michaelwoerister** [comment]
> Probably won't get far if bors runs tests =P

I'm hoping that the try build will still succeed. At least for https://github.com/rust-lang/rust/pull/56287 it worked although tests were failing. We'll see.

**Comment by nikomatsakis** [comment]
@michaelwoerister argh

**Comment by michaelwoerister** [comment]
Closing in favor of #56765.

**Pull request closed without merging**
