### PR TITLE
Disable inactive enum variant drop elaboration optimization

### PR DESCRIPTION
**Pull request by ecstatic-morse**
In #74551, users of several tier 2 platforms have reported that the optimization in #68528 was causing a miscompilation. After that issue was filed, I double-checked my work and, as far as I can tell, that optimization is theoretically sound and implemented correctly. It's possible, however, that #68528 ends up triggering an LLVM or `rustc` codegen bug that results in invalid code on those platforms. It's also possible that the same codegen bug is lurking on tier 1 platforms, but does not present as a SEGFAULT.

This PR disables the optimization in #68528. This should be useful for a perf run and so that affected users can apply this patch to build Firefox using the latest `rustc`. However, it's not clear whether we should actually merge it. I'm not sure what the policy should be for disabling optimizations that cause unrelated bugs (assuming I'm correct that #68528 is sound) on tier 2 platforms. Do we disable it for everyone? No one? Only affected platforms? All architectures besides x86?

This PR is more complex than one might expect because there's a const-checking pass (#71824) that runs after drop elaboration and depends on the basic ideas of #68528 to allow certain functions (notably `Option::unwrap`) to be `const`. Now that drop elaboration no longer removes provably dead drop terminators in cases like these, I have to replicate some of the logic from drop elaboration in the const-checking module. If we decide to disable the optimization for all platforms, we could move these const checks back before drop elaboration to simplify the code somewhat. It was split up originally to avoid duplicating work.

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
r? pnkfelix

**Comment by ecstatic-morse** [comment]
@bors try
@rust-timer queue

**Comment by joshtriplett** [comment]
Looks like this is a substantial loss across the board.

**Comment by ecstatic-morse** [comment]
@joshtriplett Yes, there's a reason I'm trying quite hard to avoid disabling this :smile:. Ideally we would be able to find someone with the time, LLVM expertise and access to hardware needed to debug the root cause of #74551. Unfortunately, I think @pnkfelix no longer has the third one, and I've never had any of them.

I suppose we could disable this optimization only on affected platforms, but that sort of divergence feels pretty bad. Maybe we should nominate this for `T-compiler` discussion? #74551 was already discussed but that was a month ago.

**Comment by joshtriplett** [comment]
I'm not a fan of having optimization passes vary by target for reasons of brokenness. If it were a matter of "it helps on some platforms but not others", that'd be a good reason.

**Comment by Dylan-DPC** [comment]
@ecstatic-morse any updates?

**Comment by ecstatic-morse** [comment]
Nightly users (or ones who know about `RUSTC_BOOTSTRAP`) can disable this via a flag now (see #77423). I'll close this.

**Pull request closed without merging**
