### PR TITLE
Correct code for operations on empty `Vec`s

### PR DESCRIPTION
**Pull request by pczarn**
Corrected a few cases of using an invalid pointer `0x1`. Even taking an offset of 0 leads to undefined behavior.

### CODE REVIEW

**Comment by Gankro** [comment]
Does offsetting by `0` invoke UB, though?

**Comment by Gankro** [comment]
> If the inbounds keyword is present, the result value of the getelementptr is a poison value if the base pointer is not an in bounds address of an allocated object

- [LLVM reference](http://llvm.org/docs/LangRef.html#id195)

So yes this change seems to be necesssary

**Comment by Gankro** [comment]
LGTM

@bors r+

**Comment by pczarn** [comment]
There are many more changes needed in `core::slice`. I think it would be straightforward to make `heap::EMPTY` point to something. However, consts can't hold addresses of statics, is that right?

**Comment by Gankro** [comment]
CC @Aatch on the above language question.

**Comment by Gankro** [comment]
@pczarn ping

**Comment by Gankro** [comment]
Closing as inactive

**Pull request closed without merging**
