### PR TITLE
Use a crate to produce rustdoc tree comparisons instead of the `diff` command

### LINKED ISSUE #82409: Diff on rustdoc test failure does not work on Windows
When running `x .py test .\src\test\rustdoc` on Linux and a failure happens, a really nice diff of the output vs rustdoc-nightly is produced which very clearly shows the issue. This does not work on Windows for multiple reasons. 

One the call to `diff` fails:
```powershell
info: generating a diff against nightly rustdoc
warning: no pager configured, falling back to `diff --color`
help: try configuring a git pager (e.g. `delta`) with `git config --global core.pager delta`
thread '[rustdoc] rustdoc\sidebar-link-generation.rs' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\tools\compiletest\src\runtest.rs:2467:55
```

Second, the output from rustdoc-nightly seems to exactly match that from the local compiler making it not possible to do manual diffs.

### PR DESCRIPTION
**Pull request by notriddle**
It doesn't come with Windows, so bring [our own](https://github.com/notriddle/rust-unified-diff/).

Fixes #82409

image

### CODE REVIEW

**Comment by Nemo157** [comment]
Maybe it'd be worth replacing the _other_ diff function too, if `unified-diff` produces better results?

https://github.com/rust-lang/rust/blob/3d82ea37a5b2dc3aa233dd69270d21a82804d433/src/tools/compiletest/src/runtest.rs#L103-L206

**Comment by notriddle** [comment]
I expect both of them would produce very similar results, but slightly differently formatted.

I *don't* want to reformat all of the MIR diff files in the test suite. That sounds like a lot of churn for nothing.

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed a bit

**Comment by notriddle** [comment]
Okay, it's been rebased and squashed. @Mark-Simulacrum

**Pull request merged**
