### PR TITLE
Update and organize the Keywords table

### PR DESCRIPTION
**Pull request by mbrubeck**
- Add two missing keywords, `Self` and `proc`
- Fix some mis-alphabetized keywords

r? @steveklabnik

### CODE REVIEW

**Comment by mbrubeck** [comment]
For reference, my updated table exactly matches [the `keywords` module from token.rs](https://github.com/rust-lang/rust/blob/69e47c77b257360ec64e714eb97abf6c51475f27/src/libsyntax/parse/token.rs#L523-L582).

**Comment by steveklabnik** [comment]
`proc` should have been removed as a keyword by now, I thought? And is `Self` actually a keyword?

**Comment by mbrubeck** [comment]
`proc` is still a reserved keyword.  `Self` is a keyword:

```rust
fn main() {
    let Self = 1;
    let proc = 2;
}
```

```
<anon>:2:9: 2:13 error: expected identifier, found keyword `Self`
<anon>:2     let Self = 1;
                 ^~~~
<anon>:3:9: 3:13 error: `proc` is a reserved keyword
<anon>:3     let proc = 2;
                 ^~~~
```

**Comment by steveklabnik** [comment]
I swear that we removed `proc`. Guess not.

**Pull request merged**
