### PR TITLE
Fix UB in repr(packed) tests

### PR DESCRIPTION
**Pull request by TimNN**
r? @arielb1 

cc #37609 and #27060

### CODE REVIEW

**Comment by TimNN** [comment]
Actually, this is still no UB free I think -- as far as I can tell the initialisation of the fixed size array containing a packed struct does generate aligned loads, which is probably a bug in `rustc`?

**Comment by arielb1** [comment]
Yup there's a bug in loading/storing fields of pairs. I'll fix that tomorrow.

**Pull request merged**
