### PR TITLE
Normalize types and consts in MIR opts.

### PR DESCRIPTION
**Pull request by cjgillot**
Some passes were using a non-RevealAll param_env, which is needlessly restrictive in mir-opts.

As a drive-by, we normalize all constants, since just normalizing their types is not enough.

### CODE REVIEW

**Comment by JakobDegen** [comment]
@cjgillot can we also run the `reveal_all` pass unconditionally? Is there a reason we shouldn't?

**Comment by cjgillot** [comment]
I thought it was already on by default :facepalm:. No reason we shouldn't.

**Pull request merged**
