### PR TITLE
Add unused pre-interned symbols tidy check

### PR DESCRIPTION
**Pull request by DaniPopes**
Adds a tidy check that checks for unused pre-interned symbols, inspired by the comment in [`rustc_span::symbol`](https://github.com/rust-lang/rust/blob/23eb90ffa77943153d203c3d184c182490d758e7/compiler/rustc_span/src/symbol.rs#L122-L123).

This checks for `sym::*` references, which results in 35 unused symbols, although of these are commonly used even if not explicitly referred to, like `Future` or `CString`, with very few being actually unused.

When adding new symbols to the pre-intern list, they must also be added to an ignore list to pass this check if they are not explicitly referenced as `sym::*` anywhere in the compiler.

I personally don't think it's worth having this extra maintenance burden, but I'm opening this PR anyway for others' opinions on the matter, and for future reference.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
I agree that this tidy check is more effort than it's worth and we shouldn't add it.

**Comment by ozkanonur** [comment]
> I personally don't think it's worth having this extra maintenance burden

> I agree that this tidy check is more effort than it's worth and we shouldn't add it.

I agree also.

cc @rust-lang/bootstrap

**Comment by albertlarsan68** [comment]
This feels like too much effort for something that seems (at a first glance) quite brittle.

**Comment by jyn514** [comment]
I think t-compiler should make the decision here. Tidy is ultimately for their benefit, I don't think we're in a good position to decide how useful this check is.

That said Nils is on t-compiler, so I'm comfortable closing this.

Separately, @DaniPopes are you interested in making a one time PR that removes the unused symbols with no other changes? That seems to me like a good cleanup and not a maintenance burden.

**Pull request closed without merging**
