### PR TITLE
incr.comp.: Use an array instead of a hashmap for storing result hashes.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Doing so should result in some of the core tracking components being faster.

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
[Travis ICE looks legitimate.](https://travis-ci.org/rust-lang/rust/builds/318731924#L1936)

**Comment by michaelwoerister** [comment]
Seems like I was compiling with debug assertions off locally. Should be fixed now.

**Pull request merged**
