### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #88336 ( Detect stricter constraints on gats where clauses in impls vs trait)
 - #88677 (rustc: Remove local variable IDs from `Export`s)
 - #88699 (Remove extra unshallow from cherry-pick checker)
 - #88709 (generic_const_exprs: use thir for abstract consts instead of mir)
 - #88711 (Rework DepthFirstSearch API)
 - #88810 (rustdoc: Cleanup `clean` part 1)
 - #88813 (explicitly link to external `ena` docs)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=88336,88677,88699,88709,88711,88810,88813)

### CODE REVIEW

**Comment by Manishearth** [comment]
It feels like https://github.com/rust-lang/rust/pull/88709 is the only likely culprit but it's also feature gated. Unsure what's going on here

**Comment by Manishearth** [comment]
could also be https://github.com/rust-lang/rust/pull/88677 or https://github.com/rust-lang/rust/pull/88711 but everyone seems to find all of these candidates unlikely

**Comment by Mark-Simulacrum** [comment]
Focusing in on the top regression, inflate check full, cachegrind shows the regression centering on process_obligations:

```
$ ./target/release/collector diff_local cachegrind +9ef27bf7dc50a8b51435579b4f2e86f7ee3f7a94 +c7dbe7a830100c70d59994fd940bf75bb6e39b39 --include inflate --builds Check --runs Full
$ less results/cgann-9ef27bf7dc50a8b51435579b4f2e86f7ee3f7a94-c7dbe7a830100c70d59994fd940bf75bb6e39b39-inflate-Check-Full
72,907,279  ???:rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
23,931,248  ???:ena::unify::UnificationTable<S>::uninlined_get_root_key
```

From there, we want to check if the function is called more often or each call became more expensive. For this, callgrind is useful. Rerun the diff_local with callgrind:

```
$ ./target/release/collector diff_local callgrind +9ef27bf7dc50a8b51435579b4f2e86f7ee3f7a94 +c7dbe7a830100c70d59994fd940bf75bb6e39b39 --include inflate --builds Check --runs Full
```

Then, the default view doesn't show call counts, but you can pass `--tree=caller` to callgrind_annotate to get this:

```
$ callgrind_annotate --tree=caller results/clgout-9ef27bf7dc50a8b51435579b4f2e86f7ee3f7a94-inflate-Check-Full
2,960,080,594 (64.18%)  < ???:_ZN21rustc_trait_selection6traits7fulfill18FulfillmentContext6select17h80d1450895e486aeE.llvm.13260143977094445196 (34,057x)
2,220,443,052 (48.14%)  *  ???:rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations

  404,736,181 ( 8.78%)  < ???:rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations (8,826x)
  201,820,150 ( 4.38%)  *  ???:rustc_data_structures::obligation_forest::ObligationForest<O>::compress

$ callgrind_annotate --tree=caller results/clgout-c7dbe7a830100c70d59994fd940bf75bb6e39b39-inflate-Check-Full | less
3,056,791,553 (64.92%)  < ???:_ZN21rustc_trait_selection6traits7fulfill18FulfillmentContext6select17h80d1450895e486aeE.llvm.9518623118464054305 (34,057x)
2,293,350,331 (48.71%)  *  ???:rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations

  404,659,331 ( 8.59%)  < ???:rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations (8,826x)
  201,740,042 ( 4.28%)  *  ???:rustc_data_structures::obligation_forest::ObligationForest<O>::compress
```

We look at the numbers in (...) after the callers. In this case, they're the same, so each function got a little more expensive -- with thousands of calls, even a slight difference in instruction counts can blow up to a big change. No direct changes were made in the source code though.

There is an average of 2,840 more instructions per call (inclusive of functions called by process obligations), but it's not really clear what the cause is. A cursory inspection suggests that the new code has a larger stack allocation (up by 32 bytes), so presumably there's more load/spills... but the reason for the larger stack is unclear. It seems *plausible* that this is due to shifts in optimization choices made through PGO that in this case were "bad". Inflate is one of the benchmarks run in CI for PGO, but it's still possible for that to produce negative results. Reading the assembly to figure out what is causing the loads and spills without debuginfo doesn't seem worthwhile to invest into right now (and reproducing the build *with* debuginfo is probably hard).

My guess is that shifts elsewhere in the program slightly shifted the profile for this function or something along those lines and that caused this shift. It seems quite possible that no particular PR is actually fully responsible for this change.

**Comment by Mark-Simulacrum** [comment]
FWIW while looking into this I also filed https://github.com/rust-lang/rust/pull/89495 which may be of some help, but it's not a mitigation for this regression, just a sideline optimization.

**Pull request merged**
