### PR TITLE
Make rustc_dirty/clean annotations exhaustive by default

### LINKED ISSUE #45009: tracking issue for `rustc_dirty/clean` enhancements
cc @michaelwoerister 

this is partof #44924

I started this work in #44983, but I would like to break it out into three separate pull requests.

This feature will make it so that `rustc_clean(except="foo,bar")` will assert that ALL DefNode's are clean (which is different depending on which def-node it is) except for the ones given in `except=` (which it asserts are dirty)

Example syntax:
```
#[rustc_clean(except="Hir,HirBody,TypeOfItem", cfg="cfail2")]
#[rustc_clean(cfg="cfail3")]
struct Abc { ... }
```

Instead of how it is currently done:
```
#[rustc_dirty(label="Hir", cfg="cfail2")]
#[rustc_dirty(label="HirBody", cfg="cfail2")]
#[rustc_dirty(label="TypeOfItem", cfg="cfail2")]
#[rustc_clean(label="GenericsOfItem", cfg="cfail2")]
#[rustc_clean(label="PredicatesOfItem", cfg="cfail2")]
#[rustc_clean(label="Hir", cfg="cfail3")]
#[rustc_clean(label="HirBody", cfg="cfail3")]
#[rustc_clean(label="TypeOfItem", cfg="cfail3")]
#[rustc_clean(label="GenericsOfItem", cfg="cfail3")]
#[rustc_clean(label="PredicatesOfItem", cfg="cfail3")]
struct Abc { ... }
```

This should make testing incr-compilation more complete, less boilerplate and easier to read (but also an itty bit more magic)

This work is split into three parts:
1. [x] #44983: allow multiple nodes in `label=` to support that functionality in `except` in the future. This requires a couple of changes to `librustc`, so I want to merge it separately.
2. [x] #45104 add `except=` and  detect the `DefNode` and do correct assertions. Also use it in a couple of test files (continue to support `label=`)
    - To do this we want to match on the [`Node` enum][1], which can be gotten from [`hir.get`][2]. From there I will construct the expected fields that could change. The initial implementation will just use the ones suggested in https://github.com/rust-lang/rust/issues/44924
3. [ ] depricate `label=` and remove from all tests.

[1]: https://github.com/rust-lang/rust/blob/master/src/librustc/hir/map/mod.rs#L44-L68
[2]: https://github.com/rust-lang/rust/blob/master/src/librustc/hir/map/mod.rs#L501

Item 1 adds ` rustc::dep_graph::dep_node::label_strs` so that we can specify groups in this way:
```
const STRUCT_NODES: &'static str = [
    label_strs.Hir,
    label_strs.HirBody,
    label_strs.TypeOfItem,
    label_strs.GenericsOfItem
    label_strs.PredicatesOfItem
];
```

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes #45009

### CODE REVIEW

**Comment by jackh726** [comment]
I feel bad for doing r? @Aaron1011 but I'm not sure who's better at the moment

**Comment by Aaron1011** [comment]
@cjgillot: Are there any remaining uses of `#[rustc_dirty]`? If not, could you remove the attribute?

**Comment by Aaron1011** [comment]
cc @michaelwoerister - does this look good to you?

**Comment by michaelwoerister** [comment]
This looks good to me in general, yes. Thanks for the PR, @cjgillot!

**Comment by Aaron1011** [comment]
r=me with the merge conflicts addressed.

**Pull request merged**
