### PR TITLE
Resolve inherent associated functions & constants defined on function pointer types

### LINKED ISSUE #108270: Inherent associated functions and constants defined on function pointer types won't be found
Since only `core` & `std` are allowed to define functions and constants on function pointer types (like `fn()` or `for<'a> fn(&'a ()) -> bool`) and since they maybe never will, this issue is of low priority. For other primitive types like `!`, `()`, `bool` etc., inherent associated functions and constants are correctly resolved.

```rust
#![feature(rustc_attrs)]
#![rustc_coherence_is_core]

impl fn() {
    const X: () = ();
}

fn user() {
    <fn()>::X; //~ ERROR no associated item named `X` found for fn pointer `fn()` in the current scope
}
```

Note that the perma-unstable attribute `#![rustc_coherence_is_core]` is used in the reproducer which doesn't come with any language or stability guarantees. However, this issue is not about it but about the fact that `core` which uses this attribute internally and `std` (which can use `#[rustc_allow_incoherent_impl]`) would not be able to properly define associated items on those types. For the same reason, I'm not labeling this as <kbd>requires-nightly</kbd>. 

@rustbot label T-compiler A-resolve A-associated-items

### PR DESCRIPTION
**Pull request by fmease**
Fixes #108270.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Nothing's wrong with the impl, just two things:

1. Core doesn't currently use this, so we're kinda doing extra work for nothing?
2. Since we're doing extra work, there's a tiny risk that we're gonna cause a perf regression.

Let's see what rust-timer says, then go from there.

**Comment by fmease** [comment]
Closing for now due to the perf regression. Might re-open at some point once I have a vague idea how to speed things up.

**Comment by fmease** [comment]
Ah, I just saw https://github.com/rust-lang/rust/pull/103042#issuecomment-1440935097, so potentially `keccak` and `cranelift-codegen` are false positives after all. Let's wait and see and I might open this PR at some point w/o any adjustments.

**Comment by fmease** [comment]
It seems like #108815 fixed the `keccak` & `cranelift-codegen` performance ‘bimodalities’. See also [*`keccak` bimodility* (Zulip)](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/keccak.20bimodality).

If the above is true and if I understood the situation correctly, it's worth rechecking the perf of this PR.
@compiler-errors Could you kick off a timing check? That'd be great. Thanks in advance! :)

**Comment by compiler-errors** [comment]
Gonna FCP this for T-types -- The question here is whether or not we want to be able to write incoherent/core impls for fn ptrs. I think it's good for consistency, but not particularly useful (since we can't be generic over argument arity), but also I see no harm in allowing it -- seems along the same lines that we allow incoherent impls for tuples. cc #94963

@rfcbot fcp merge

**Comment by lcnr** [comment]
I cannot imagine us ever using this. Any impl for function pointers should go through the `FnPtr` trait instead :thinking: I guess this is fairly trivially correct so it doesn't matter too much

**Comment by oli-obk** [comment]
We could reject it with an error mentioning the FnPtr trait

**Comment by nikomatsakis** [comment]
I'm confused here -- we are *allowing* incoherent impls? I would be more comfortable using `FnPtr`, are there methods where that doesn't suffice?

**Comment by nikomatsakis** [comment]
@rfcbot concern fnptr

Nothing against this PR per se, but I'd prefer that we use the `FnPtr` trait and disallow incoherent fn-based inherent impls, and I want to better understand that option.

**Comment by fmease** [comment]
> we are *allowing* incoherent impls?

Not arbitrarily, only with `#![rustc_coherence_is_core]`, so effectively only in the `core` library.

`FnPtr` is definitely superior. This PR is mostly motivated by a drive towards consistency in the area of inherent impls.

**Comment by compiler-errors** [comment]
> Nothing against this PR per se, but I'd prefer that we use the FnPtr trait and disallow incoherent fn-based inherent impls, and I want to better understand that option.

I don't mind that approach either necessarily, but in that case, we probably should also reject inherent impls on tuples and maybe others...

**Comment by lcnr** [comment]
@rfcbot cancel

**Comment by lcnr** [comment]
talked about this in the planning meeting today https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-08-07.20planning.20meeting/near/382646902

We would prefer to completely forbid inherent impls on function pointers with a suggestion to use the `FnPtr` trait instead.

We are open to adding this once there is a valid use case here, but this feels quite unlikely as adding an impl for just one kind of function pointer is far from ideal.

**Comment by fmease** [comment]
Makes sense. I'm gonna close this PR then & create a new one for forbidding inherent impls on function pointer types.

**Pull request closed without merging**
