### PR TITLE
Stabilize clamp

### PR DESCRIPTION
**Pull request by Xaeroxe**
Tracking issue: https://github.com/rust-lang/rust/issues/44095

Clamp has been merged and unstable for about a year and a half now. How do we feel about stabilizing this?

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]

**Comment by KodrAus** [comment]
This seems reasonable to me!

This stabilizes the following methods on `Ord`, as well as `f32` and `f64`:

```rust
pub trait Ord {
    fn clamp(self, min: Self, max: Self) -> Self { .. }
}

impl f32 {
    pub fn clamp(self, min: f32, max: f32) -> f32;
}

impl f64 {
    pub fn clamp(self, min: f64, max: f64) -> f64;
}
```

We need to provide inherent methods on `f32` and `f64` because they don't implement the `Ord` trait. I don't _think_ we have any plans to implement `Ord` for floating points _directly_, but do have [some total ordering methods](https://github.com/rust-lang/rust/pull/72568) that showed up recently.

The methods were originally RFC'd [here](https://github.com/rust-lang/rfcs/pull/1961).

There was also an FCP open [here](https://github.com/rust-lang/rust/issues/44095#issuecomment-544393395) previously that went stale some time ago. It was suggested we just kick off a new one since the shape of Libs has changed a fair bit in the intervening years.

@rfcbot fcp merge

**Comment by scottmcm** [comment]
> We need to provide inherent methods on f32 and f64 because they don't implement the Ord trait. I don't think we have any plans to implement Ord for floating points directly, but do have some total ordering methods that showed up recently.

There's `Ord::min` and `f32::min` already, so I don't think having `Ord::clamp` and `f32::clamp` adds any new hazards here.

**Comment by scottmcm** [comment]
The code changes look good to me, so with the FCP completed without controversy,
r? @scottmcm 
@bors r+ rollup

**Comment by scottmcm** [comment]
```
fatal: unable to access 'https://github.com/BurntSushi/ripgrep/': Could not resolve host: github.com
thread 'main' panicked at 'assertion failed: status.success()', src\tools\cargotest\main.rs:96:13
```
@bors retry

**Pull request merged**
