### PR TITLE
Add rustc_on_unimplemented for Index implementation on slice

### LINKED ISSUE #31062: provide on_unimplemented hint for ops::Index
As discussed on IRC. cc @steveklabnik 

If you do `slice[2i32]` you get an error that tells you what is wrong (`Index<i32>` is not implemented for `[T]`) but not how to fix it (slices are indexed by usize). A quick fix would be to use `#[rustc_on_unimplemented]`; it would look [like this](http://is.gd/Wei0AV).

If you are indexing something that isn't `[T]` then the message would be a false positive.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #31062

### CODE REVIEW

**Comment by oli-obk** [comment]
is this error message testable?

**Comment by GuillaumeGomez** [comment]
Oh right, I'll add test. Thanks for notifying me @oli-obk!

**Comment by GuillaumeGomez** [comment]
It's getting longer and more difficult because the `rustc_on_unimplemented` flag needs to be improved in order to handle `impl` as well (so a trait has this flag and an implementation of this trait redefines it, the impl's one will be displayed instead).

**Comment by GuillaumeGomez** [comment]
I'm facing an issue here. For example, for the following code:

```Rust
#![feature(on_unimplemented)]

fn main() {
    let x : &[i32] = &[1, 2];
    x[1u32];
}
```

I cannot determine the impl trait used between:

* `Index<usize>`
* `Index<RangeTo<usize>>`
* `Index<RangeFrom<usize>>`
* `Index<RangeFull>`

How can I determine the good one?

cc @pnkfelix, @nikomatsakis, @arielb1, @eddyb

**Comment by nikomatsakis** [comment]
@GuillaumeGomez 

> It's getting longer and more difficult because the rustc_on_unimplemented flag needs to be improved in order to handle impl as well (so a trait has this flag and an implementation of this trait redefines it, the impl's one will be displayed instead).

Well, the whole point is that this message is displayed in cases where *is no* impl to apply, so that's a bit tricky. But that said the new obligation forest does, in principle, keep some backtraces that might give us the "most likely" impl that was supposed to apply, so I guess we could find the best message to use by walking the backtrace. I know @arielb1 was working on a PR to improve error message that would make use of the backtrace, not sure of the status of that work though -- seems like it would be a precursor that would do some of the required refactoring for you.

**Comment by GuillaumeGomez** [comment]
@nikomatsakis: That's a great news! Now, just have to wait that this functionality lands.

**Comment by nikomatsakis** [comment]
@GuillaumeGomez for the record, the issue I was referring to is https://github.com/rust-lang/rust/issues/30976

**Comment by GuillaumeGomez** [comment]
Still waiting to see how it'll be solved. Then I'll take their function.

**Comment by GuillaumeGomez** [comment]
I talked with @pnkfelix this evening and he proposed (correct me if I'm wrong) that since there wasn't that much movement on the function I need, instead of doing a global one, it'll be a more specific one. So what I have in mind is the following:
- Checking type size.
- Compare type's type (struct vs struct, enum vs enum, primitive vs primitive, etc...).
- Checking name (it'll be the last resort, and I'm actually not sure if it's needed).

I'll wait a few days then, if no ones has objection, I'll start to work on this.

**Comment by nikomatsakis** [comment]
@GuillaumeGomez I don't quite understand what you are proposing -- what is this type whose size etc you are checking and so forth? I do agree though that it seems fine to add a bit of special-case logic for the error messages around indexing.

**Comment by GuillaumeGomez** [comment]
Oh sorry, my message is a bit incomplete. So I was tried to explain was to "guess" what was the trait the user tried to use. So for example:

```
let s = &[0, 1];
s[0i32];
```

will span an error because index is implemented for `usize`, not `i32`. Now we have to look what trait implementation could have been used, and we have the choice between:

- Index<usize>
- Index<RangeTo<usize>>
- Index<RangeFrom<usize>>
- Index<RangeFull>

It seems obvious for humans that is `Index<usize>` but not for a computer, so we need to add the function. To guess the good type, I thought to first compare type's size (i32 is close to usize after all), type's type (i32 is primitive, usize is primite, others aren't), and in last resort the name.

Now I guess I added the missing part of my previous explanation. Very sorry about this.

**Comment by eddyb** [comment]
@GuillaumeGomez I've edited your comment to add the \`...\` necessary to avoid having `<...>` interpreted as HTML.

**Comment by GuillaumeGomez** [comment]
@eddyb: Thanks! :)

**Comment by eddyb** [comment]
@GuillaumeGomez I think the size and "is primitive" checks could be replaced by the "flavor" of type - `i32` and `usize` are both integers, whereas the `Range` types are `struct`s.

**Comment by GuillaumeGomez** [comment]
So remove my first point and keep the two others? Fine by me.

**Comment by nikomatsakis** [comment]
Yes, I agree with @eddyb -- checking the size seems like it may not be
that helpful. Probably we just want to specialize this message around
integer types in general, no? But otherwise, creating some rough
categories and checking for those is probably good.

**Comment by nikomatsakis** [comment]
@GuillaumeGomez I'm going to close this PR for the time being. Please feel free to open another at some later point :)

**Pull request closed without merging**
