### PR TITLE
Simplify [a]rc code a little

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Nothing interesting, just make [a]rc code a little nicer by using `byte_sub` ~~and `let`-`else`~~.

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
@thomcc Thanks for clarifying libs team intentions! I can remove the added use of let-else. 

I think that `byte_sub` change is still meaningful though (+ I plan to propose stabilizing it, so it won't be unstable for long, hopefully :D).

**Comment by Mark-Simulacrum** [comment]
At the very least, it would likely be a good idea to make an experience report comment linking to this PR on the byte_sub tracking issue -- IMO, the code is definitely nicer and more readable with it.

**Comment by WaffleLapkin** [comment]
Update: rebased to remove let-else commit.

**Pull request merged**
