### PR TITLE
submodules: update rustfmt and rls

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Apparently rustfmt depends on `dunce` now which is licensed under `CC0-1.0` and triggered CI failure.
I see there already is another exception for the same license, should I add an exception for dunce as well?
````
    ("constant_time_eq", "CC0-1.0"),        // rustfmt
````

**Comment by matthiaskrgr** [comment]
Mmh according to the cargo.lock, there are now two rustfmt-nightly versions with this pr..??

**Comment by calebcartwright** [comment]
> Mmh according to the cargo.lock, there are now two rustfmt-nightly versions with this pr..??

Looks like this is changing the rustfmt submod to the master branch, but it should be `rustfmt-1.4.19` https://github.com/rust-lang/rustfmt/tree/rustfmt-1.4.19

**Comment by matthiaskrgr** [comment]
Ah yes, I updated to the master branch, will fix in a bit.

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/pull/74760

**Pull request closed without merging**
