### PR TITLE
Update stdarch submodule

### PR DESCRIPTION
**Pull request by dpaoliello**
r? @Amanieu

### CODE REVIEW

**Comment by kadiwa4** [comment]
Fixes #103058.

**Comment by dpaoliello** [comment]
@Amanieu @heiher can you please help with the fix for this? Do we need to add `#![feature(loongarch_target_feature)]` to `core` (and `std`)? And should it be added only for doc builds?

**Comment by dpaoliello** [comment]
> Do we need to add `#![feature(loongarch_target_feature)]` to `core` (and `std`)? And should it be added only for doc builds?

Ok, I've found where the other target features are set in `core` and added `loongarch_target_feature`

**Pull request merged**
