### PR TITLE
Rename directive `needs-profiler-support` to `needs-profiler-runtime`

### PR DESCRIPTION
**Pull request by Zalathar**
The rest of the compiler mostly refers to this as `profiler_runtime`, so having a directive named `needs-profiler-support` was causing a lot of confusion.

r? jieyouxu

### CODE REVIEW

**Comment by Zalathar** [comment]
I should also think about renaming the `profiler_builtins` crate to `profiler_runtime`, but that can be left for a separate PR.

**Review by jieyouxu — APPROVED** [review]
Thanks, you can r=me after PR CI is green. As usual, please also update rustc-dev-guide about this 😄

**Comment by Zalathar** [comment]
CI is green.

@bors r=jieyouxu

**Comment by Zalathar** [comment]
Dev-guide update: https://github.com/rust-lang/rustc-dev-guide/pull/2095

**Comment by matthiaskrgr** [comment]
might have failed in  https://github.com/rust-lang/rust/pull/131438#issuecomment-2401742950 ? :thinking:

**Comment by Zalathar** [comment]
I'm pretty sure that failure is the thing #131434 was trying to fix, but that PR landed before the rollup failed ...

**Comment by jieyouxu** [comment]
Yeah, there was a bootstrap test that was broken

**Comment by Zalathar** [comment]
Anyhow, while it probably won't make a difference, I've rebased this PR for good luck.

@bors r=jieyouxu

**Pull request merged**
