### PR TITLE
serialize: rename to rustc_serialize.

### PR DESCRIPTION
**Pull request by eddyb**
In preparation for post-#49219 use of custom derives in rustc, we'll want to stop using `Rustc{Encodable,Decodable}` derives, and *at least* adapt the library to suit `rustc` better, before a full implementation of #36588 can be done.

This will break anyone using `extern crate serialize;` (on nightly) so let's do a crater run with a rename, just to see what things are like.

~~**EDIT**: I was going to test with `rustc_serialize` (which does work in terms of compiling) but I realized that `rustc-serialize` from crates.io might make that tricky if it ends up in our sysroot, so for the crater run let's go with something weirder (`rustc_ezilaires`).~~

~~**EDIT2**: had to remove `rustc_save_analysis` and `rls` to get rid of the crates.io `rustc-serialize` from Cargo.lock. Note that this is just for crater, just like the `rustc_ezilaires` rename.~~

**EDIT3**: cleaned up the PR, after crate run shows only one regression.

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
@rust-lang/infra Whenever nobody else needs crater, a `check` run would be nice.

**Comment by pietroalbini** [comment]
@craterbot run start=master#a49316ddc99d9d595193557fc899f6c52e4d9af9 end=try#32252761328f59ccfadb1bafb8148c685bc830b3 mode=check-only

**Comment by eddyb** [comment]
Only one regression from using `serialize`: [`mayer_multiple-0.0.1`](https://crates.io/crates/mayer_multiple/0.0.1) ([log](https://crater-reports.s3.amazonaws.com/pr-56323/try%2332252761328f59ccfadb1bafb8148c685bc830b3/reg/mayer_multiple-0.0.1/log.txt)).
Nothing crater checks appears to be using `rustc_serialize` from the sysroot, which is perfect.

**Comment by eddyb** [comment]
(I need to either move the test to a `run-make` one that uses `Cargo` with the `crates.io` `rustc-serialize` dependency, or maybe mock it in the test locally)

**Comment by nikomatsakis** [comment]
Er, @bors r-

**Comment by nikomatsakis** [comment]
r=me but I see travis is unhappy?

(To confirm: this affects only nightly users, and we only found 1 of those on the crater run, right?)

**Comment by eddyb** [comment]
@nikomatsakis Yeah, everyone else is using the out-of-tree `rustc-serialize` crate.
And I still need to fix https://github.com/rust-lang/rust/pull/56323#issuecomment-443505266, so no r+ for me just yet.

**Comment by Aaronepower** [comment]
Triage; @eddyb Hello, have you been able to get back to this PR?

**Comment by TimNN** [comment]
Ping from triage @eddyb: What is the status of this PR?

**Comment by Dylan-DPC** [comment]
ping from triage @eddyb Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again!

**Pull request closed without merging**
