### PR TITLE
adjust how closure/generator types are printed

### PR DESCRIPTION
**Pull request by RalfJung**
I saw `&[closure@$DIR/issue-20862.rs:2:5]` and I thought it is a slice type, because that's usually what `&[_]` is... it took me a while to realize that this is just a confusing printer and actually there's no slice. Let's use something that cannot be mistaken for a regular type.

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm, something somewhere is still printing `[closre@...]`, I'm seeing it in some ui tests.

**Comment by RalfJung** [comment]
Ah, what I changed was actually the rvalue printing (which doesn't seem to be exercised by the test suite), not the type printing.

**Comment by oli-obk** [comment]
Seems fine to me, please create an MCP for it so all of the compiler team gets informed about it.

**Comment by RalfJung** [comment]
@oli-obk how long do we want to wait from the MCP seconding to landing the PR?

**Comment by oli-obk** [comment]
MCPs are 10 days

**Comment by BoxyUwU** [comment]
the MCP has been accepted for 10 days now this can be merged after a rebase presumably

**Pull request merged**
