### PR TITLE
[DO NOT MERGE] Measure cost of per function section

### PR DESCRIPTION
**Pull request by bjorn3**
I was experimenting with using per function sections instead of a single `.text` section in cg_clif to see if it reduced binary size. It brings the size down for the test I used from 26MB to 15MB like the output of cg_llvm in debug mode. When I measured the linker time the result was a lot less positive: ~0.4s turned into ~0.7s. That is a 75% slowdown. It would be interesting to know what the cost is for cg_llvm over the full rustc-perf benchmark suite.

Can someone start a perf run for me?

### CODE REVIEW

**Comment by jyn514** [comment]
OMG that's infredi

**Comment by bjorn3** [comment]
Big wins of up to 20%. No regressions at all.

**Comment by jyn514** [comment]
(sorry, GitHub on mobile is awful)

**Comment by mati865** [comment]
> It brings the size down for the test I used from 26MB to 15MB like the output of cg_llvm in debug mode

Function sections are supposed to reduce the size of final binary since we pass `-Wl,--gc-sections` at the cost of linker having more work to do.
Maybe something went wrong?

**Comment by bjorn3** [comment]
That the final size got smaller when using per function sections as it is supposed to. I may have worded it a bit confusingly.

**Comment by eddyb** [comment]
(Changed this to a draft to make the "[DO NOT MERGE]" part even more clear)

**Comment by bjorn3** [comment]
It would also be nice to check the perf impact of not passing `--gc-sections`, but keeping -ffunction-sections enabled.

**Comment by bjorn3** [comment]
I have replaced disabling `-ffunction-sections` with disabling `--gc-sections`. This should be possible to enable by default in debug mode. Can I get another perf run?

**Comment by bjorn3** [comment]
As of https://github.com/rust-lang/rust/pull/78414 you can use `-Zfunction-sections=no` optionally combined with `cargo build -Zbuild-std` to also build the sysroot with this flag.

**Pull request closed without merging**
