### PR TITLE
Migrate some books to mdbook version 0.2

### PR DESCRIPTION
**Pull request by mati865**
There are 3 books still using old version but they need more effort so I hope to do them in subsequent PR if I find the time.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r=Centril,GuillaumeGomez

**Comment by ehuss** [comment]
Just for some context, the reference and cargo books are blocked on getting a new mdbook release made. Still trying to get ownership on crates.io to do that.  Hopefully will be able to remove the mdbook1 stuff soon!

**Comment by mati865** [comment]
Thanks for the info!
I think rustc book may be blocked on reference migration (gave me odd errors but I haven't investigated it deeply). Rust-by-example should be doable.

> Hopefully will be able to remove the mdbook1 stuff soon!

I hoped to get rid of it this/next week but looks like I'll have to be patient.

**Pull request merged**
