### PR TITLE
Remove Cycle::try_fold override

### LINKED ISSUE #56883: Missing iterations
The following code prints "foo" 4 times with stable and beta, but prints nothing with rustc 1.33.0-nightly (93c2f055b 2018-12-15).

```rust
fn main() {
    std::iter::once(0).cycle().skip(1).take(4).for_each(|_| println!("foo"));
}
```

Replacing `once()` by something else or replacing `for_each()` with `map()` exhibits the same behaviour.

### PR DESCRIPTION
**Pull request by sinkuu**
Fixes #56883

### CODE REVIEW

**Comment by sinkuu** [comment]
After fixing the bug, it no longer improves benchmark. So, now this PR just removes the override.

**Comment by bluss** [comment]
@bors r+ rollup

Makes sense. Thanks!

**Comment by nagisa** [comment]
IMHO this should be p=1 and landed ASAP, @bluss, not as part of rollup, as it fixes invalid behaviour in valid code (i.e. problem as bad as soundness issues).

**Comment by bluss** [comment]
@bors p=1 rollup-

Yes. Let's see if bors can do that. There are several bugfixes queued, but looks like we're not overtaking something more critical.

**Pull request merged**
