### PR TITLE
Remove Reflect

### LINKED ISSUE #27749: Tracking issue for `Reflect` stabilization
The `Reflect` trait is currently unstable. It was intended to narrow the use of things like `Any` for runtime introspection, to help retain parametricity properties. However, with [impl specialization](https://github.com/rust-lang/rfcs/pull/1210) these properties would go away anyhow, so it's not clear how useful the trait would be.

Thus, stabilization should wait at least until specialization is settled.

cc @reem @nikomatsakis @pnkfelix

### PR DESCRIPTION
**Pull request by est31**
PR for removing the `Reflect` trait. Opened so that a crater run can be done for testing the impact: https://github.com/rust-lang/rust/issues/27749#issuecomment-272665163

Fixes #27749

### CODE REVIEW

**Comment by est31** [comment]
I'm not 100% sure of the comment change in `src/librustc/traits/select.rs` (and generally I don't have much knowledge of the code involved, but the change seemed pretty straightforward). Correct me if I'm wrong.

**Comment by est31** [comment]
Rebased.

**Comment by est31** [comment]
@nikomatsakis [you said](https://github.com/rust-lang/rust/issues/27749#issuecomment-273226053) that you've started a crater run on this PR. Are there any results in yet? Also, will me rebasing this PR in any way inconvenience the crater run? I don't want to force-push and destroy something :)

**Comment by nikomatsakis** [comment]
@est31 let me check :) also, rebase away

**Comment by nikomatsakis** [comment]
@est31 something went wrong with my run :(

**Comment by est31** [comment]
@nikomatsakis rebased.

**Comment by brson** [comment]
I will crater it.

**Comment by brson** [comment]
[Crater says](https://gist.github.com/anonymous/08649e3e85edc63ded99e8704ea24c95).

**Comment by pnkfelix** [comment]
the three root regressions reported by crater all are pretty obvious (each crate is importing `Reflect` and so the compiler complains).

**Comment by nikomatsakis** [comment]
The feature is deprecated and removal is the plan, and the PR looks good; impact is minimal. So I gave r+!

**Pull request merged**
