### PR TITLE
Rewrite variadic-ffi pass to use test helper

### LINKED ISSUE #32305: Fix src/test/run-pass/variadic-ffi.rs test
This test is ignored on MSVC because MSVC does not have a sprintf function. 

We have a variadic function defined in test helpers, which should be used in this test as well. See [mir_trans_calls_variadic](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/mir_trans_calls_variadic.rs) for an example.

### PR DESCRIPTION
**Pull request by nagisa**
The sprintf used in this test previously isn’t available on some versions of MSVC.

Fixes #32305

r? @alexcrichton

### CODE REVIEW

**Comment by retep998** [comment]
I'd just like to take a moment to point out that there is actually in fact a printf you can link to. `legacy_stdio_definitions.lib` which is only available when you're using a new enough msvc to not have printf otherwise.

**Comment by alexcrichton** [comment]
We've had a lot of flaky tests recently, but that one actually looks legit

**Comment by retep998** [comment]
Yep, already discussed it with @nagisa on IRC, an `i32` is being passed to the variadic function where it actually expects an `int64_t`, which does matter for the 32-bit calling convention, thus causing UB.

**Pull request merged**
