### PR TITLE
Print rustdoc rendering warnings all the time

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @rust-lang/dev-tools

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
cc https://github.com/rust-lang/rust/issues/44229

IMO it's *way* too early for this, like shouldn't we be following that process? The next step is to print the warnings by default (instead of just when `--enable-commonmark` is given) and wait for a stabilization cycle. Has that happened yet?

**Comment by GuillaumeGomez** [comment]
Hum... I thought that the next step was to make the pulldown renderer the default one in the next cycle and to print the warnings by default (which makes sense). Didn't understood that it was two steps?

**Comment by QuietMisdreavus** [comment]
As far as i understand the intended process, we were supposed to warn people about the rendering changes *without changing the rendering output*. By switching the default renderer like this, we're warning them about the changes *while we mess up their docs*, which is what we set out to avoid by adding all this overhead.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by QuietMisdreavus** [comment]
Much better! Now we just print the warnings all the time, and begin our stability cycle for real.

**Comment by michaelwoerister** [comment]
r? @steveklabnik 

We discussed this in the dev-tools meeting. It seems like the next logical step. Thanks for the PR, @GuillaumeGomez!

**Comment by steveklabnik** [comment]
@bors: r+

thank you!

**Comment by ollie27** [comment]
Is there any reason that these warnings aren't emitted when using rustdoc on plain markdown files?

**Comment by GuillaumeGomez** [comment]
@ollie27: No idea. It should though... I think it's a separate issue. Can you open an issue so I can look into it later on please?

**Comment by ollie27** [comment]
done: #45365

**Pull request merged**
