### PR TITLE
Make rustdoc method HTML anchor IDs/links unique (#20700)

### PR DESCRIPTION
**Pull request by hinsley**
This pull request makes rustdoc's rendered method anchor IDs and links unique, so clicking on a particular method link will take you to that specific method description, and not the first similarly-named method description on the page, as is the current behavior.

The link anchors should now have a contextual prefix added to them, so each anchor is unique and refers only to the corresponding method.

This build was tested working under the most recent rust 1.0.0-nightly as of today.

Solves issue #20700.

### CODE REVIEW

**Comment by xnil** [comment]
Oops, didn't see the merge conflicts. Sorry about that; give me a bit.

**Comment by alexcrichton** [comment]
Right now it's pretty nice to have short anchors like `#method.fmt` because you can manually type it in sometimes if you like. Would it be possible just keep a thread-local cache per-page of IDs generated? The markdown ID generation does this and just appends 1, 2, 3, ... to the end (which keeps the memorable aspect mostly)

**Comment by Manishearth** [comment]
(needs rebase)

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Pull request closed without merging**
