### PR TITLE
[WIP] Remove fake IDs in rustdoc

### PR DESCRIPTION
**Pull request by jyn514**
They're confusing and cause crashes. Part of an ongoing effort to debug https://github.com/rust-lang/rust/pull/75176.

Not sure why the tests are failing, probably I'm not understanding why fake IDs were added in the first place.

### CODE REVIEW

**Comment by Aaron1011** [comment]
@jyn514: Fake DefIds exist to handle 'synthetic' auto trait impls, which don't have a real `DefId`.

**Comment by jyn514** [comment]
@aaron1011 do you know what the `param_env_def_id` represents, then? It's what `get_auto_trait_impls` is using to look up the synthetic impl.

**Comment by Aaron1011** [comment]
@jyn514: `param_env_def_id` represents the item we are creating a synthetic impl for, and used to obtain the corresponding `ParamEnv`.

**Comment by jyn514** [comment]
Closing this because I think it needs more design work in rustdoc (https://github.com/rust-lang/rust/issues/76382), the current approach isn't going to work.

**Pull request closed without merging**
