### PR TITLE
Fix typo in suggest.rs where f32 was used instead of f64

### LINKED ISSUE #114683: Potential typo in suggestion of E0689
This line looks like a typo to me, should it be `f64`?

_Originally posted by @sunmy2019 in https://github.com/rust-lang/rust/pull/94963#discussion_r1289520712_

Currently, it affects line 1684.
https://github.com/rust-lang/rust/blob/832db2fcee27ee1079608ac78f82b7c14394e89b/compiler/rustc_hir_typeck/src/method/suggest.rs#L1676-L1686

### PR DESCRIPTION
**Pull request by gurry**
Fixes #114683

### CODE REVIEW

**Comment by gurry** [comment]
@compiler-errors I could not come up with a test that would reproduce the impact of this typo unfortunately. It will have an impact only if `found_assoc(tcx.types.f32)` returns something different from `found_assoc(tcx.types.f64)`. As per my understanding both of them will always return the same value since `f32` and `f64` have the exact same inherent methods and implement the same traits.

I did try by implementing a custom trait of my own for `f64` which isn't implemented for `f32`, but in that case the compiler was able to unambiguously resolve the method and hence no compiler error occurred :(.

Please suggest a test I can add.

**Comment by gurry** [comment]
> A job failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5832902235/job/15819190882) [(plain)](https://github.com/rust-lang/rust/commit/e903752b4814d2d0eb78aa56a515173f286a6cc9/checks/15819190882/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)

Someone please help me resolve this. The error looks related to the build system itself:

`ERROR: process "/bin/sh -c curl -sL https://nodejs.org/dist/v16.9.0/node-v16.9.0-linux-x64.tar.xz | tar -xJ" did not complete successfully: exit code: 2`

Perhaps retrying the job is enough?

**Comment by klensy** [comment]
Just force push your branch to retry.

**Comment by compiler-errors** [comment]
Yeah, I guess this doesn't need a test. @gurry has a good point above about unambiguously resolving because there are only two float kinds.

**Comment by klensy** [comment]
This isn't merged, btw

**Comment by gurry** [comment]
Why didn't it get merged @klensy? It says about that I "closed this X hours ago", but I didn't do anything.

**Comment by gurry** [comment]
Ah, I did delete the branch in my repo. That was stupid. Let me try to reopen if I can.

**Pull request merged**
