### PR TITLE
Stabilize edition 2018; also updates Clippy, RLS and Cargo

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Supersedes https://github.com/rust-lang/rust/pull/53999 , https://github.com/rust-lang/rust/pull/53935
Clippy build was failing there because crate_visibility_modifier feature was taken out of edition 2018 and clippy used it.
The clippy update enables the corresponding feature explicitly.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Urgh, looks like rls needs to be fixed as well....

**Comment by ehuss** [comment]
@matthiaskrgr I think #53935 needs to merged first.

**Comment by matthiaskrgr** [comment]
@ehuss  Hm, why?

**Comment by ehuss** [comment]
RLS requires the update to Cargo (due to https://github.com/rust-lang-nursery/rls/pull/1048), and Cargo requires the update to RLS (since RLS is not allowed to be broken).

**Comment by matthiaskrgr** [comment]
Uff....
I might have to try pulling in a cargo update into this PR then..

**Comment by matthiaskrgr** [comment]
@ehuss I tried merging the cargo changes 53953 now.

**Comment by ehuss** [comment]
> @ehuss I tried merging the cargo changes of 53953 now.

👍 hopefully this can get through the queue before tuesday 😄

**Pull request merged**
