### PR TITLE
Stabilise link-self-contained option

### PR DESCRIPTION
**Pull request by mati865**
MCP has been accepted: https://github.com/rust-lang/compiler-team/issues/343

I'll add improved heuristic in next PR.

### CODE REVIEW

**Comment by mati865** [comment]
cc @petrochenkov

**Review by petrochenkov — APPROVED** [review]

**Comment by petrochenkov** [comment]
I'll assume that no comments from @rust-lang/compiler on https://github.com/rust-lang/compiler-team/issues/343 is a sign of silent approval and not just missing the notification.
r? @petrochenkov @bors r+

**Comment by lzutao** [comment]
Could you add a github milestone along with relnotes ?

**Comment by mati865** [comment]
Spurious:
```
Run src/ci/scripts/install-clang.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  516M    0  286k    0     0  7531k      0  0:01:10 --:--:--  0:01:10 7531k
  4  516M    4 25.0M    0     0  26.6M      0  0:00:19 --:--:--  0:00:19 26.6M
curl: (56) OpenSSL SSL_read: Connection was reset, errno 10054

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by joshtriplett** [comment]
What's the process for supporting link-self-contained on another platform? What steps would that take?

**Comment by mati865** [comment]
Which platform are you talking about? There is no list of common steps because it will differ a lot between platforms.

**Comment by joshtriplett** [comment]
@mati865 I'm interested in seeing it for aarch64-unknown-linux-gnu.

**Comment by mati865** [comment]
Assuming `ld.lld` works nicely for that target we would have to ship glibc and libunwind.
Glibc is the hard part here, should Rust build it's own glibc or copy one from the builder?
There is also licensing consideration, does LGPLv2.1 allow us to ship glibc and use it for linking?

I suppose you are aware that self-contained mode allows only building pure Rust crates (ones without dependencies on `cc` and similar crates)?

**Pull request merged**
