### PR TITLE
Add regression test for #22471

### LINKED ISSUE #22471: Internal error looking up a definition [E0242] with where clause on type alias
Trying to compile this:
```
type Foo<T> where T: Copy = Box<T>;
```
gives the following:
```
<anon>:1:22: 1:26 error: internal error looking up a definition [E0242]
<anon>:1 type Foo<T> where T: Copy = Box<T>;
                              ^~~~
```
I'm not entirely sure if this is actually legal, but regardless it seems odd that an "internal error" is exposed to the user in the same way that regular compiler errors are.

```rustc 1.0.0-nightly (b63cee4a1 2015-02-14 17:01:11 +0000)```

### PR DESCRIPTION
**Pull request by jooert**
Closes #22471.

### CODE REVIEW

**Comment by Manishearth** [comment]
The test stil fails. http://buildbot.rust-lang.org/builders/auto-linux-32-opt/builds/4772/steps/test/logs/stdio

**Comment by jooert** [comment]
I'm sorry I messed up the rollup PR! The weird thing is: When I run
```
make check-stage1-rpass TESTNAME=issue-22471
```
locally, the test passes, but it fails when I run
```
make check-stage1-pretty TESTNAME=issue-22471
```
However, when I run the exact same command that the test runner claims to compile the test with, compilation works without errors. Compiling with another (nightly f9e53c7f2 2015-04-24) locally installed version of rustc works fine too. Perhaps there is something I still don't understand about the testing system, but I thought if a test compiles fine using the just compiled rustc and using an older version, too, the test should be good to go.
Nevertheless, even though I don't understand what is failing here, I'm still sorry for the inconvience caused!

**Comment by Manishearth** [comment]
No problem.

Put an `// ignore-pretty` on the test, I suspect the literal is getting cropped. (See other tests with the ignore-pretty annotation to figure out how to do it).

**Comment by jooert** [comment]
Ok, I added the `// ignore-pretty`. So what is "pretty" supposed to do in comparison to the ordinary "run-pass"?

**Comment by Manishearth** [comment]
It runs the test through the prettifier (`-Z unstable-options --pretty=expanded`) and tries it again.

**Comment by jooert** [comment]
Ah, I see! In this particular case it turns
```Rust
type Foo<T> where T: Copy = Box<T>;
```
into
```Rust
type Foo<T> = Box<T> where T: Copy;
```
The latter fails with
```
error: expected one of `+`, `::`, or `;`, found `where`
type Foo<T> = Box<T> where T: Copy;
```
while the former compiles fine. Isn't that a bug in the prettifier if it transforms working code into non-compiling?

**Comment by Manishearth** [comment]
Yes, please file it! :)

**Comment by jooert** [comment]
Ok. :smiley:
Thank you for your patience and your explanations!

**Comment by jooert** [comment]
This can be merged now, as #25092 has landed.

**Pull request merged**
