### PR TITLE
Added tvOS as targets

### PR DESCRIPTION
**Pull request by simlay**
This is a first attempt of adding support tvOS as described in #48862. It's got a lot of overlap with [src/librustc_target/spec/apple_ios_base.rs](https://github.com/rust-lang/rust/blob/31dd4f4acbcbdb02b0745d2136399ed664a28050/src/librustc_target/spec/apple_ios_base.rs).

I thought about refactoring `apple_ios_base.rs` to include this as well but that would require each of the ios and tvos targets to be of the something like the form `let base = opts(AppleOS::TV, Arch::Arm64)?;` I also did the same thing for watchOS because from what I can tell, all three targets (iOS, tvOS, and watchOS) have the same logic but have different parameters being sent to `xcrun`. Thoughts?

As far as the `data_layout` and other parameters to `Target`, I did as much research as I could but it really seems that processor in the [iPhone 11 is the same as the apple TV](https://en.wikipedia.org/wiki/Apple-designed_processors) so I didn't change any of those parameters.

I did get this to build and tested that it's actually running the the below logic (because the parameter to `xcrun` is `appletvos` not `tvos`).

I didn't manage to get it to actually compile a file with `fn main(){}` because I don't have the stdlib for `aarch64-apple-tvos` compiled it seems. Is there documentation for this?

Similar to the ending of https://github.com/rust-lang/rust/pull/63467, I'm not sure what to do next.

### CODE REVIEW

**Comment by simlay** [comment]
I've got mixed feelings about this in general. Here's `diff librustc_target/spec/apple_ios_base.rs librustc_target/spec/apple_tvos_base.rs`:

```
12,13d11
<     Armv7,
<     Armv7s,
15d12
<     I386,
17d13
<     X86_64_macabi,
23,24d18
<             Armv7 => "armv7",
<             Armv7s => "armv7s",
26d19
<             I386 => "i386",
28d20
<             X86_64_macabi => "x86_64",
44,45c36,37
<             "iphoneos"
<                 if sdkroot.contains("iPhoneSimulator.platform")
---
>             "appletvos"
>                 if sdkroot.contains("TVSimulator.platform")
50,57c42,43
<             "iphonesimulator"
<                 if sdkroot.contains("iPhoneOS.platform") || sdkroot.contains("MacOSX.platform") =>
<             {
<                 ()
<             }
<             "macosx10.15"
<                 if sdkroot.contains("iPhoneOS.platform")
<                     || sdkroot.contains("iPhoneSimulator.platform") =>
---
>             "appletvsimulator"
>                 if sdkroot.contains("TVOS.platform") || sdkroot.contains("MacOSX.platform") =>
87,89c73,74
<         Armv7 | Armv7s | Arm64 => "iphoneos",
<         I386 | X86_64 => "iphonesimulator",
<         X86_64_macabi => "macosx10.15",
---
>         Arm64 => "appletvos",
>         X86_64 => "appletvsimulator",
114,115d98
<         Armv7 => "cortex-a8", // iOS7 is supported on iPhone 4 and higher
<         Armv7s => "cortex-a9",
117d99
<         I386 => "yonah",
119d100
<         X86_64_macabi => "core2",
126,127c107
<         Armv7 | Armv7s | Arm64 | I386 | X86_64 => vec!["MACOSX_DEPLOYMENT_TARGET".to_string()],
<         X86_64_macabi => vec!["IPHONEOS_DEPLOYMENT_TARGET".to_string()],
---
>         Arm64 | X86_64 => vec!["MACOSX_DEPLOYMENT_TARGET".to_string()],
```

Thoughts on combining iOS, tvOS, and eventually watchOS into something like `apple_arm_base` (or a better name)?

**Comment by estebank** [comment]
I'll wait until thursday's @rust-lang/compiler meeting.

**Comment by nagisa** [comment]
@simlay you’re welcome to take a shot at merging the `apple_ios_base` and `apple_tvos_base`. I would perhaps call it a `apple_sdk_base` as SDK detection between these targets is what”s being shared ultimately, I believe.

Otherwise this looks good to me. r=me. (lmk if you’re not merging the bases, I’ll inform bors accordingly)

**Comment by nagisa** [comment]
> I didn't manage to get it to actually compile a file with fn main(){} because I don't have the stdlib for aarch64-apple-tvos compiled it seems. Is there documentation for this?

The best way at this stage to get an stdlib for the target being added is to do the full `x.py dist` build I believe. I don’t think we have docs for this though. Your best bet will be probably looking at what CI invokes ultimately.

**Comment by JohnCSimon** [comment]
Ping from triage: @simlay - Can you please post your status on this PR. Can you address the comments or is this ready for review?

**Comment by simlay** [comment]
Thanks for the reminder! I’ll update this PR later this week to merge the comments about merging `apple_io_base` and `apple_watchtv_base` into `apple_sdk_base`.

**Comment by nagisa** [comment]
Looks like you’ll need to reformat the code, but otherwise LGTM.

**Comment by simlay** [comment]
@nagisa done!

**Comment by nikomatsakis** [comment]
@bors r=nagisa

(I'm interpreting @nagisa's comment as r=me...)

**Comment by nagisa** [comment]
Yeah, thanks. Sorry missed it.

**Comment by Centril** [comment]
Apparently it wasn't actually merged... @bors retry

**Comment by HindrikStegenga** [comment]
Hello there!

I'm interested in running Rust code on my Apple TV. Since rustup doesn't provide pre-built compiler and such, I have manually checked out and compiled rustc and applied some manual patches to both libc and std crates and overridden them with my modified versions for my local compiler toolchain. I can successfully get libc and std crates to compile for the aarch64-apple-tvos target, but actually linking the produced .a static library in Xcode gives me an error saying that it's a macOS library. However, inspecting it with lipo seems to indicate that it actually is an arm64 binary... Any pointers on how to run atleast something in Rust on my AppleTV? 

In terms of changes I did lo libc/std crates, I mostly sprinkled around` target_os = "tvos"` everywhere, since iOS and tvOS are very close in terms of base OS and libraries.

**Pull request merged**
