### PR TITLE
std::thread: fix get_name implementation for Linux/musl tier 2.

### PR DESCRIPTION
**Pull request by devnexen**
libc's crate fails to pass on arm/i686 linux/musl tier2 due to the abscence of pthread_getname_np support.

### CODE REVIEW

**Comment by ChrisDenton** [comment]
The lowest version glibc we support is 2.17. I believe `pthread_getname_np` was introduced in glibc 2.12.

**Comment by devnexen** [comment]
oh I misread the report, it s in fact linux/musl..

**Comment by devnexen** [comment]
but [we have it though](https://github.com/rust-lang/libc/actions/runs/8519943595/job/23335183246?pr=3646).

```rust
/rustc/1684a753dbca5d23b2e03568e6fbbb48eb72d0e6/library/std/src/sys/pal/unix/thread.rs:244:(.text.unlikely._ZN4core4cell4once17OnceCell$LT$T$GT$15get_or_try_init13outlined_call17hce693a6db7399e1fE+0x30): undefined reference to `pthread_getname_np'
          collect2: error: ld returned 1 exit status
```

**Comment by ChrisDenton** [comment]
For whatever reason, libc is testing [musl 1.1.24](https://github.com/rust-lang/libc/blob/a0f5b4b21391252fe38b2df9310dc65e37b07d9f/ci/install-musl.sh#L8). Which is earlier than the version rustc currently supports.

**Comment by devnexen** [comment]
ok so libc has to update its CI instead.

**Pull request closed without merging**
