### PR TITLE
Refactor libtest

### PR DESCRIPTION
**Pull request by popzxc**
## Short overview

`libtest` got refactored and splitted into smaller modules

## Description

`libtest` module is already pretty big and hard to understand. Everything is mixed up: CLI, console output, test execution, etc.

This PR splits `libtest` into smaller logically-consistent modules, makes big functions smaller and more readable, and adds more comments, so `libtest` will be easier to understand and maintain.

Although there are a lot of changes, all the refactoring is "soft", meaning that no public interfaces were affected and nothing should be broken.

Thus this PR (at least should be) completely backward-compatible.

r? @wesleywiser
cc @Centril

### CODE REVIEW

**Comment by popzxc** [comment]
Well, seems like I broken something =_= I will investigate it and fix tomorrow.

**Comment by popzxc** [comment]
Well, I forgot to re-export public `bench` interface. Everything is OK now (I hope).

**Review by wesleywiser — APPROVED** [review]
looks good and ci is green

**Comment by popzxc** [comment]
Hm. There was `cfg(unix)` attr for `get_concurrency` which was not required for `cfg(target_os = "redox")`.

Should be fixed now.

**Pull request merged**
