### PR TITLE
Migrate `symbols` to use declarative macro.

### PR DESCRIPTION
**Pull request by fee1-dead**
Pros:
 - faster build times
 - completion for IDE users
 - easier to understand

Cons:
 - check for duplicates and alphabetical order is moved to tidy

### CODE REVIEW

**Comment by bjorn3** [comment]
Another con: With a proc macro it would have been possible to precompute hashes of all symbols to make building the symbol interner faster.

**Comment by fee1-dead** [comment]
> With a proc macro it would have been possible to precompute hashes of all symbols to make building the symbol interner faster.

Yes, but how would that work with FxHashMap? With some improvements to CTFE I think this can be done in const contexts in the near future.


> IIRC, it was migrated from a declarative to procedural macro only 1-2 years ago.

Actually 3 years ago. It was #59655. You commented that if we could use `macro_rules` then we should use `macro_rules`.

We could also test the performance:

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
FxHashMap has the raw_entry api which allows providing the hash directly AFAIK.

**Comment by bjorn3** [comment]
> With some improvements to CTFE I think this can be done in const contexts in the near future.

Even if it could it may still be slower.

**Comment by Mark-Simulacrum** [comment]
I am not entirely convinced by this change -- the diagnostics cycle seems likely to be worse (a proc-macro gives you immediate feedback), and the macro itself is not as digestible to me. Proc macros are a little clunky, but macro-rules at least as it stands today forces into annoying and not easily comprehensible hacks like ____anchor here. (FWIW, it seems like using https://doc.rust-lang.org/nightly/std/mem/fn.variant_count.html should be a better fit there).

I think in terms of benefits, the strongest one is probably the completion for IDE users, but it was my recollection that rust-analyzer (and presumably eventually other IDEs) already support completion with proc-macros in some cases. Maybe there's something we can adjust to make that feasible? For example, with some adjustments, it might be possible to make most of this derive-macro capable, emitting some constants on the side to talk to the other macros -- that would probably greatly improve the IDE story?

**Comment by fee1-dead** [comment]
I am going to close this in favor of https://github.com/rust-lang/rust-analyzer/pull/11956 which would allow customizing how rust-analyzer runs build scripts and expands procedural macros. A followup PR after that to rustc should make IDE support a lot better for procedural macros.

**Pull request closed without merging**
