### PR TITLE
rustc: Stabilize the `proc_macro` feature

### LINKED ISSUE #35900: Tracking issue for "Macros 1.1" (RFC #1681)
Tracking issue for rust-lang/rfcs#1681.

cc @alexcrichton 
## Stabilization TODO

Litmus tests:
- [x] - Does diesel work? https://github.com/rust-lang/rust/issues/35900#issuecomment-251242313
- [x] - Does serde work? https://users.rust-lang.org/t/serde-transitioning-to-macros-1-1/7437

Features:
- Crate name, currently is `proc_macro`
- Crate type, currently `proc-macro`
- The `#[proc_macro_derive(Foo)]` attribute 
- Loading `proc-macro` crates with `-L` and `#[macro_use]` to load them
- shadowing is an error
- no hygiene
- passing a token stream for the entire struct and receiving it all back
- Cargo manifest attribute, currently `proc-macro = true`

Known bugs:

- [ ] - Panicking derive may have the wrong span - #36935
- [ ] - token streams with `mod foo` fail - #36691
- [ ] - docs aren't published for `proc_macro` - #38749
- [x] - custom attributes for multiple modes is hard - https://github.com/rust-lang/rust/issues/35900#issuecomment-252499766
- [x] - cargo test fails for proc macro libs - #37480
- [x] - order still matters - https://github.com/rust-lang/rust/issues/35900#issuecomment-252430957 (fxed by https://github.com/rust-lang/rust/pull/37067)
- [x] - Can't document rustc-macro crates - https://github.com/rust-lang/rust/issues/36820 (fixed in #36847)
- [x] - Cargo rebuilds too often - https://github.com/rust-lang/rust/issues/36625 (fixed in https://github.com/rust-lang/rust/pull/36776)
- [x] - Attributes generated by the compiler make custom derive authors' lives difficult - https://github.com/rust-lang/rust/issues/35900#issuecomment-245978831
  - [x] - Change order of expansions to users-first - https://github.com/rust-lang/rust/issues/35900#issuecomment-246840357 (fixed in https://github.com/rust-lang/rust/pull/36782)
## Implementation TODO
- [x] - Create a `rustc_macro` crate
  - [x] - Have `librustc_macro` link to `libsyntax`. Depend on `librustc_macro` in `librustc_driver`
  - [x] - Tag `rustc_macro` as unstable with our [standard header](https://github.com/rust-lang/rust/blob/master/src/libsyntax/lib.rs#L17-L25).
  - [x] - Only tag `rustc_macro` with `#![crate_type = "rlib"]`, do not produce a dylib.
  - [x] - Implement [the API](https://github.com/rust-lang/rfcs/blob/master/text/1681-macros-1.1.md#librustc_macro) of `rustc_macro` using `libsyntax`'s `TokenStream` internally
  - [x] - tag `rustc_macro` with a `TokenStream` lang item so the compiler knows about it.
- [x] - Add `rustc_macro_derive` attribute
  - [x] - validate it's of the exact form `foo(bar)`, no other arguments/formats
  - [x] - verify it's only applied to functions
  - [x] - verify it's only applied to functions in the root module
  - [x]  - verify the signature with the `TokenStream` lang item added above
  - [x] - encode all function symbols with `rustc_macro_derive` into metadata along with the derive mode they're used for.
- [x] - Add a `rustc-macro` crate type for other crates
  - [x] - wire it up to produce a dylib
  - [x] - ensure the dylib gets metadata
  - [x] - ensure `rustc-macro` crates **cannot be linked as dylibs**
  - [x] - ensure there are no _reachable_ items other than those tagged with `#[rustc_macro_derive]`
  - [x] - Add `cfg(rustc_macro)` as an unstable `cfg` directive, set it for the `rustc-macro` crate type
  - [x] - ensure that `rustc-macro` crates link dynamically to libsytnax
- [x] - Fill in `#[macro_use]` support for `rustc-macro` crates
  - [x] - extend library loader to find `rustc-macro` crates separately from dylib/rlib tracked today when loding crates
  - [x] - Parse metadata for `rustc-macro` crates to learn about symbol/derive mode pairings
  - [x] - `dlopen` the dylib
  - [x] - generate an error if any derive mode would shadow any other.
- [x] - Add cargo integeration
  - [x] - recognize `rustc-macro` similar to `plugin = true`
  - [x] - pass `--crate-type=rustc-macro` when depending on it
  - [x] - plumb the same host/target logic for rustc-macro crates as is present for plugin crates (e.g. always compile rustc-macro crates for hosts)
- [x] - Tests
  - [x] - smoke test loading a rustc-macro, dummy `#[derive]` trait 
  - [x] - name conflicts are an error
  - [x] - compiling for the wrong architecture is an error
  - [x] - cannot emit crate type rustc-macro and anything else (e.g. rustc-macro+dylib) is an error
  - [x] - span information not being horrendous
  - [x] - removing attributes from a struct, as well as fields
  - [x] - adding impls next to a struct
  - [x] - cross compilation looks for the host rustc-macro crate type
  - [x] - don't load vanilla dylibs as rustc-macro crate types
  - [x] - can't have public exports beyond macro derive functions in a rustc-macro crate
  - [x] - derive macros must have required signature
  - [x] - load two macro crates in one compilation

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit stabilizes the `proc_macro` and `proc_macro_lib` features in the
compiler to stabilize the "Macros 1.1" feature of the language. Many more
details can be found on the tracking issue, #35900.

Closes #35900

### CODE REVIEW

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
🎊🎉

**Comment by abonander** [comment]
`#[proc_macro_attribute]` uses the `proc_macro` feature flag AFAICT; we don't want to stabilize a feature that's not even implemented yet, right? Is anyone working on that? If not, I've started tinkering with it.

**Comment by nikomatsakis** [comment]
@abonander raises a good point! :) @alexcrichton, are there other users of `proc_macro` feature flag getting a free pass here?

**Comment by alexcrichton** [comment]
@abonander to clarify, is that implemented? I couldn't find `proc_macro_attribute` in the code base currently at least...

@nikomatsakis AFAIK nothing else is, no

**Comment by abonander** [comment]
I've started tinkering on it because I'd like to experiment with the feature. It actually looks pretty straightforward, mostly just copying custom derive.

**Comment by alexcrichton** [comment]
@abonander I'm still a little confused? I haven't been following all the proc-macro business that closely. What is `proc_macro_attribute`? Is it implemented today? Does this PR need to change?

**Comment by abonander** [comment]
https://github.com/rust-lang/rfcs/pull/1566

It is not currently supported in the compiler, though the pieces are (mostly) there. I'd have to read over the RFC again but I don't think it uses its own feature flag, though that can be changed trivially.

**Comment by alexcrichton** [comment]
Ok, sounds like that can just have a new feature gate if it isn't already implemented? I'm sort of confused, does this PR need to change?

**Comment by abonander** [comment]
I don't think so, we just need to make sure the feature gate for the other two proc macro kinds is different.

**Comment by nikomatsakis** [comment]
Marking as beta-accepted. The whole point is to backport this -- and anyway it's 99% marking stuff stable.

cc @rust-lang/compiler

**Pull request merged**
