### PR TITLE
Move clean types into their own file

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This PR is just about moving clean types into their own files to make the code more clear and keep all `Clean` trait implementations on their own.

r? @kinnison

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
ping @kinnison

**Comment by kinnison** [comment]
@GuillaumeGomez Okay, I've been through the commit sequence and it looks clean to me.  You can squash it down if you want, or else just let Bors know I approve.

**Comment by GuillaumeGomez** [comment]
Let's keep the commit history as is then, I kinda like the history flow as it is. :)

@bors: r=kinnison

**Comment by Centril** [comment]
Seems like it failed in https://github.com/rust-lang/rust/pull/67111#issuecomment-562827366 ? @bors rollup=never r-

**Comment by GuillaumeGomez** [comment]
I ran it locally and no issue. The block code which failed is:

```
/// Some documentation.
# fn foo() {}
println!("Hello, World!");
```

I don't see how it could fail. I think the error comes from somewhere else...

@bors: r=kinnison

**Pull request merged**
