### PR TITLE
Remove legacy grammar

### PR DESCRIPTION
**Pull request by XAMPPRocky**
Revival of #50835 & #55545

On the #wg-grammar discord there was agreement that enough progress has been made to be able to remove the legacy grammar.

r? @Centril @qmx 

cc @rust-lang/wg-grammar

### CODE REVIEW

**Comment by ehuss** [comment]
For `src/doc/grammar.md`, I would add a redirect, or a placeholder page that indicates where it may be found.  There are still a lot of links to it in the wild.  Maybe something like this:

> The Rust grammar may now be found in the [reference](https://doc.rust-lang.org/reference/). Additionally, the [grammar working group](https://github.com/rust-lang/wg-grammar) is working on producing a testable grammar.

**Comment by Centril** [comment]
r=me with redirect suggested by @ehuss set-up.

**Comment by XAMPPRocky** [comment]
@Centril Updated with suggestion.

**Comment by Centril** [comment]
Thanks! @bors r+

**Comment by XAMPPRocky** [comment]
@Centril TIL, that that is required. Updated the PR to keep the original `% Grammar`

**Pull request merged**
