### PR TITLE
add CString::from_vec_until_nul

### PR DESCRIPTION
**Pull request by ericseppanen**
This adds a fn that converts a `Vec` into a `CString`, without requiring the nul byte to be at the end of the Vec. It is intended for the case when an FFI function call wrote a string of unknown length, which `from_vec_with_nul` doesn't handle easily.

For example,
```rust
let mut buffer = vec![0u8; 32];
unsafe {
    some_c_function(buffer.as_mut_ptr(), buffer.len());
}
let result = CString::from_vec_until_nul(buffer).unwrap();
```

This is a companion to `CStr::from_bytes_until_nul` (#94984) , and shares the feature gate: `cstr_from_bytes_until_nul` (tracking issue #95027).

**Unresolved questions:**

I couldn't decide whether this fn should use its own unique error type, or whether it should share the error type with `from_vec_with_nul`. In this version I reused the existing error type, but I'm happy to change if that's the better choice.

### CODE REVIEW

**Comment by ericseppanen** [comment]
The biggest downside to sharing the error type is that the names obviously don't match:
```
pub fn from_vec_until_nul(mut v: Vec<u8>) -> Result<Self, FromVecWithNulError>
```
`FromVecWithNulError` also contains a `FromBytesWithNulErrorKind` enum which is not useful in this impl (because there's only one way this fn can fail.

I also find it odd that `FromVecWithNulError` returns the `Vec` that was input, but that member is private. I'm not sure why that choice was made originally-- maybe @poliorcetics would know?

**Comment by ericseppanen** [comment]
(fixed doc-test typo)

**Comment by poliorcetics** [comment]
> I also find it odd that `FromVecWithNulError` returns the `Vec` that was input, but that member is private. I'm not sure why that choice was made originally-- maybe @poliorcetics would know?

To allow extensibility of the internals, as unlikely as it is. There are functions on the type to access it IIRC

**Comment by petrochenkov** [comment]
I'm going to block this on https://github.com/rust-lang/rust/pull/94079 (which is almost ready), because all such changes have to be reapplied manually when rebasing https://github.com/rust-lang/rust/pull/94079.

**Comment by ericseppanen** [comment]
> I think the example on this issue is supposed to consume the buffer: `CString::from_vec_until_nul(&buffer)` -> `CString::from_vec_until_nul(buffer)`

Fixed, thanks.

**Comment by ericseppanen** [comment]
Apologies for accidentally closing this; I don't seem to be able to re-open it so I opened a new PR #96186 with the same content.

**Comment by jyn514** [comment]
@ericseppanen you need to force push back to d4c9367 to be able to reopen the PR. (I think GitHub does this to avoid having two simultaneous PRs open from the same branch.)

**Comment by ericseppanen** [comment]
> @ericseppanen you need to force push back to [d4c9367](https://github.com/rust-lang/rust/commit/d4c93674974e8ef0adc9f36d6cd613c25e598c6d) to be able to reopen the PR. (I think GitHub does this to avoid having two simultaneous PRs open from the same branch.)

I tried that but it didn't seem to do anything.

**Comment by jyn514** [comment]
I don't see a force push here. Did you remember to use `--force`?

**Comment by ericseppanen** [comment]
@jyn514 I did force push the branch to many different hashes, including the one you mentioned. Github stopped updating the "force-pushed from X to Y" message after the first one; I don't know why. After trying it a bunch of times I gave up and opened a new PR. I have updated the tracking issue to point to the new PR.

**Pull request closed without merging**
