### PR TITLE
Use spare_capacity_mut instead of invalid unchecked indexing when joining str

### PR DESCRIPTION
**Pull request by saethlin**
This is a fix for https://github.com/rust-lang/rust/issues/91574

I think in general I'd prefer to see this code implemented with raw pointers or `MaybeUninit::write_slice`, but there's existing code in here based on copying from slice to slice, so converting everything from `&[T]` to `&[MaybeUninit<T>]` is less disruptive.

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Looks good!

**Comment by pnkfelix** [comment]
This looks like just `inflate` flagging something again as it bounces up and down during different benchmark runs. It jumps back down again in #91766 (the successor PR). I plan to remove both PR #91680 and #91766 from this weeks' triage report.

@rustbot label: +perf-regression-triaged.

**Pull request merged**
