### PR TITLE
rename RcBox to RcInner for consistency

### PR DESCRIPTION
**Pull request by jdonszelmann**
Arc uses ArcInner too (created in collaboration with @aDotInTheVoid and @WaffleLapkin )

### CODE REVIEW

**Comment by jdonszelmann** [comment]
Fails in the one set of tests I cannot run locally. I'll fix it later today

**Comment by joboet** [comment]
Cool, thank you!

Could you also change the name in the function signatures (e.g. `rcbox_layout_for_value_layout`) and, for consistency's sake, in `src/doc/nomicon/src/leaking.md`

**Comment by WaffleLapkin** [comment]
yea I can (says Jonathan)

**Pull request merged**
