### PR TITLE
[DO NOT MERGE] Testing #70551 with de-abuse PRs

### PR DESCRIPTION
**Pull request by mark-i-m**
This is #70551 with #71930 and #71938 merged. I'm just using the CI to run tests because it's faster than my laptop...

Hopefully this confirms that those two PRs solve #70866...

### CODE REVIEW

**Comment by Nadrieril** [comment]
Try reverting "We don't use TyErr anymore", it should fix ci without changing anything else

**Comment by mark-i-m** [comment]
@Nadrieril Hmmm, that does seem to fix it.

**Comment by Nadrieril** [comment]
Yeah it does, but that's just a workaround. I could use that to get my own PR to build but the underlying bug might come back to bite us later

**Comment by mark-i-m** [comment]
Yes, and it also wouldn't resolve the abuse of tykind::err, which was the original point. At the same time, it would be nice to not have to fix this bug too before pushing in your changes...

**Comment by mark-i-m** [comment]
@Nadrieril I'm going to close this issue, but I can reopen and test other stuff if you want.

**Comment by Nadrieril** [comment]
It still solves the abuse of tyerr! The commit you reversed did something else that's not directly related to tyerr

**Comment by mark-i-m** [comment]
Oh, wow, I didn't even read the commit. Awesome!

**Pull request closed without merging**
