### PR TITLE
Use the correct mod name from the example

### PR DESCRIPTION
**Pull request by id4ho**
r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Why is this change needed? "Cleanup" is too vague.

**Comment by jackwilsonv** [comment]
@steveklabnik, you're right, sorry about that. I updated the title.

This change is not really a clean up so much as making the explanation match the state of the example. 

In the first `use` statement (in the example above the change) we import the `japanese::greetings` module not the `japanese::farewells` module.

**Comment by steveklabnik** [comment]
Ah thanks! I see now. Would you mind doing a quick amend of the commit message too, so that the history reflects this info, not just the PR? Happy to merge this after.

**Comment by jackwilsonv** [comment]
@steveklabnik sure thing, commit message updated! Sorry for the delay.

**Comment by steveklabnik** [comment]
No worries :) Thanks for the patch!

**Pull request merged**
