### PR TITLE
wasm64 build with target-feature=+simd128,+atomics

### LINKED ISSUE #126778: wasm64: std fails to build with `target-feature=+atomics`
I tried to build an example project for `wasm64-unknown-unknown` with `target-feature=+atomics`, but the `std` failed to build due to https://github.com/rust-lang/rust/blob/7a08f84627ff3035de4d66ff3209e5fc93165dcb/library/std/src/sys/pal/wasm/atomics/futex.rs#L1 and https://github.com/rust-lang/rust/blob/7a08f84627ff3035de4d66ff3209e5fc93165dcb/library/std/src/sys/pal/wasm/atomics/thread.rs#L22 hardcoding `wasm32` arch.

I could get `std` to build by adding `#![feature(simd_wasm64)]` to https://github.com/rust-lang/rust/blob/master/library/std/src/lib.rs, and a few `cfg` checks to import the correct module.

I could work on a PR if that's the right approach.

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (d7f6ebace 2024-06-16)
binary: rustc
commit-hash: d7f6ebacee13b6c03623c4b74197280454ede8de
commit-date: 2024-06-16
host: aarch64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by wooden-worm**
Fixes https://github.com/rust-lang/rust/issues/126778

### CODE REVIEW

**Comment by jhpratt** [comment]
r? libs

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed

**Comment by wooden-worm** [comment]
@Mark-Simulacrum I've squashed the commits.

**Comment by ehuss** [comment]
@bors retry

miri.exe`: The process cannot access the file because it is being used by another process.

**Pull request merged**
