### PR TITLE
rustdoc: redesign [+]/[−] controls

### LINKED ISSUE #60255: Docs rs "[+]" ui element does not afford usage clearly
In docs.rs, the UI has elements on the page similar to this screenshot:

Screen Shot 2019-04-24 at 07 56 31

The UI element is the light grey "[+]".

This element does not clearly afford it's usage: this means people do not see that it is first a UI element at all, and that it's operation is not clear. I and others had to be told how to interact with this as a UI element. (I actually believed it to be a list-item marker like a *).

This ability to understand clearly that elements are firstly part of the UI, and second what their function is, is an important aspect in the psycholocy of design and human interaction.

In this case, to assist with humans being able to determine on visual inspection the behaviour of the "[+]", it may be better to "document" the behaviour with a change such as "[+ expand]" and "[- collapse]". Not only does this now clearly show that the elements have a purpose, it shows obviously what the purpose is. This also may not be a perfect suggestion, but I think that something about this element should be improved.

I would propose that the element "[+]" be improved to more clearly indicate it's existence and operation to users.

See also original issue: https://github.com/rust-lang/rust/issues/60215

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #60255

## Preview

Web preview: http://notriddle.com/rustdoc-html-demo-6/plus-minus-december-2023/std/iter/trait.Iterator.html

Image preview (GitHub's downscaling makes it hard to see some of what I'm talking about, so you might want to open the image in a new tab):
image

Image preview of "toggle all" button:
image

## Description

This is a continuation of #107658 and #59851, making the toggles consistent with other buttons, instead of looking like syntax.

The tactics to improve the look of these controls:

* When the toggle is expanded, the minus sign remains as dark as before, but the border is lighter. The plus sign has a border that's the same color as the label (black, on the default theme). This makes expansion buttons more prominent, easier to tell apart from collapse buttons.
* The plus sign is slightly taller than wide, also to make it easier to tell apart from the minus sign.
  * The use of crispEdges has to get a bit strategic to make this come out right. I've tested it on Firefox, Safari, and Chromium, but it's a bit hard to be sure it works right on all setups.
  * Does anybody know some trick to do crispEdges on only the X axis, while still allowing antialiasing on the Y?
* The "toggle all" button is modeled after the Help and Settings buttons, with a matching border, width, and +/− label.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I think it's a great idea! A few comments now:

I find that the "toggle all" button attracts too much attention:

image

It has the same "level" of importance as the other buttons (help and settings). Also, its style differs from the other toggles.

For the other buttons, the `+` and `-` don't have the same look:

image

I think the appearance of the `-` makes it difficult to see. The appearance of the `+` is right on point for me. Also, I think they should have the same appearance.

**Comment by GuillaumeGomez** [comment]
> Should I make the "toggle all" button see-through on dark theme, like this?

Yep with background color of button being the same color as the "general" background, looks great (or just transparent, as you prefer).

> https://github.com/rust-lang/rust/pull/107658 claimed that the toggle design made it too hard to tell them apart from each other, so the color change was aimed at making the + and − easier to distinguish.
>
> Do you have any alternative suggestions?

I don't agree that this is an issue, quite the opposite when I see the result. My attention is bugged by this difference. Looking at the sign tells me if it's for expanding or collapsing, I don't think adding something to differentiate +/- buttons is a good idea. But as usual, we can see what the rest of the team thinks about it. I personally think it makes it more distracting than actually useful.

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks!

**Comment by GuillaumeGomez** [comment]
Don't forget to fix the CI failure. ;)

**Comment by Nemo157** [comment]
One tiny issue I see is that this makes the "Trait std::iter::Iterator" and "1.0.0 · source" text blocks even more misaligned, I wonder if it's possible to have them on the same baseline and keep the button looking good.

**Comment by Alexendoo** [comment]
The + is now very small, I find myself straining looking at it. Has the new design with the old size been tried?

image
image

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by jsha** [comment]
Thanks for working on this! It looks good. 

One question: In #107658 it seems like we had pretty good support for switching to a triangle disclosure widget ⏵ / ▼, which is aligned with what browsers do by default for `<details>/<summary>`, and I think it more common on the web in general. As far as I can tell from the history we never explicitly decided against that; the PR just succumbed to merge conflicts. What are your current thoughts on triangle widgets?

@rfcbot concern why-not-triangle

Also I'm still of the opinion that the default state should be "no disclosure widgets (until needed)". The disclosure widgets should only appear after (a) clicking the "collapse all" or (b) enabling one of the "auto-hide" settings. But that doesn't need to block this.

**Comment by GuillaumeGomez** [comment]
Small detail: I also appreciate that we keep the coherency between collapse/expand buttons text.

**Comment by tgross35** [comment]
I think this fixes (or could reference) https://github.com/rust-lang/rust/issues/60255

Re: why-not-triangle: see https://github.com/rust-lang/rust/pull/107658

**Comment by camelid** [comment]
Small suggestion: Could you make the `-` aligned with the vertical center of the text? Currently it looks a little uneven:

image

**Comment by GuillaumeGomez** [comment]
> I think this fixes (or could reference) #60255
> 
> Re why-not-triangle: see also #107658

We discussed about "why not triangle" yesterday at [rustdoc meeting](https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/meeting.2004-12-2023) and the conclusion was as follows: we'd prefer to use triangles, but we can't find a nice way to make the "toggle/collapse all" button work with triangles. So for the time being, we'll continue to use the +/- buttons.

**Comment by GuillaumeGomez** [comment]
> @camelid Which one?
> 
> The biggest source of grief with trying to make the out-of-band section look good is that it's got three different font sizes. Should I align it with "source" or with "1.0.0"? Or should I tweak them so that they both have the same font size?

can you show screenshots of the different possibilities? Simpler to decide when we can actually see the result. :)

**Comment by GuillaumeGomez** [comment]
Agreed. Thanks for sharing the results. What do you think @camelid ?

**Comment by GuillaumeGomez** [comment]
I forgot to resolve concern in [this comment](https://github.com/rust-lang/rust/pull/113074#issuecomment-1840500138).

@rfcbot resolve bigger-plus-sign

**Comment by GuillaumeGomez** [comment]
Wrong concern...

@rfcbot resolve why-not-triangle

**Comment by GuillaumeGomez** [comment]
Ah only original author can resolve the concern. Let's wait for @jsha then.

**Comment by jsha** [comment]
I'd still really like to figure out a way to make this work with triangles. It seems like we have common feeling on the team and elsewhere that triangles are the standard web way to make this type of interaction, and would be ideal. It sounds like the only thing blocking them is that the control in the top-right can't be a triangle (I agree), and if it's text, the layout moves around when the text changes. I think there are ways to solve those problems; for instance by making a text control that has a fixed size, and choosing words that are similar in size so that feels natural. Or even rethinking the top-right control entirely.

I feel bad holding up progress on something that has been more or less ready to go for a while now; I have been wanting to present a workable demo of the above ideas, and apologies for not dedicating the time so far to do so.

The reason I'm resistant to the incremental improvement now followed by a possible bigger improvement later is that the nature of docs.rs means we will have for a while some docs with the old `[-]`/`[+]` and some with the new, and later potentially with triangles. I think it's better to make our improvement all in one step so we can avoid unnecessary inconsistencies.

**Pull request closed without merging**
