### PR TITLE
rustdoc: Rename `Type::ResolvedPath` to `Type::Path` and don't re-export it

### PR DESCRIPTION
**Pull request by camelid**
The new name is shorter, simpler, and consistent with `hir::Ty`. It can't be
re-exported since the name would conflict with the `clean::Path` struct. But
usually enum variants are referred to using their qualified names in Rust anyway
(and parts of rustdoc already do that with `clean::Type`), so this is also more
consistent with the language.

r? @GuillaumeGomez 
cc @jyn514

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm afraid that the new name is too generic: we already have `clean::Path`, `ast::Path` and `hir::Path`. But as you mentioned, the biggest issue here is `clean::Path`. I'm really not sure if it's a good idea...

**Comment by camelid** [comment]
> I'm afraid that the new name is too generic: we already have `clean::Path`, `ast::Path` and `hir::Path`. But as you mentioned, the biggest issue here is `clean::Path`. I'm really not sure if it's a good idea...

It's the same name as `hir::TyKind::Path`, and it's just a wrapper for `clean::Path`. Also, I don't see why `ResolvedPath` is any less generic; all paths are resolved.

**Comment by GuillaumeGomez** [comment]
It's different, not less generic. That was the main point. Well, maybe I'm the only who thinks that. What do you think @rust-lang/rustdoc ?

**Comment by jyn514** [comment]
@camelid @GuillaumeGomez can you please use Zulip threads instead of pings for low-impact things like this? I get a *lot* of pings and this isn't a user-facing change.

**Comment by jyn514** [comment]
Anyway, I think this isn't worth worrying about until https://github.com/rust-lang/rust/pull/91195 is merged.

**Comment by camelid** [comment]
> Anyway, I think this isn't worth worrying about until #91195 is merged.

It's merged now ;)

**Comment by jyn514** [comment]
I don't think it's a bad idea given that it's only a variant *and* directly contains a `clean::Path`. I don't feel strongly either way though.

**Comment by GuillaumeGomez** [comment]
I don't have a strong opinion either. Well, I guess usage will tell. Unless you have something to do in this PR, r=me,jyn514.

**Comment by camelid** [comment]
Updated references to ResolvedPath.

@bors r=GuillaumeGomez,jyn514

**Pull request merged**
