### PR TITLE
Refactor error handling

### PR DESCRIPTION
**Pull request by nrc**
Should make it possible to add JSON or HTML errors. Also tidies up a lot.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Travis is still unhappy but I can't quite see why. Still, this looks fine -- mostly just shuffling things around, from what I can tell. r=me once travis errors are resolved.

I feel like the layering of emitters/handlers/etc always feels more complex (or maybe just less clear) than it seems like it needs to be, but that's certainly pre-existing.

**Comment by nrc** [comment]
The idea (aiui) is that to implement a new way of dealing with errors, you just have to implement `Emitter` (which is just a single emit method, really). `Handler` presents a much wider interface to users (`span_err`, `span_warn`, etc.). I guess this is kind of convenient, but it won't really work with structured errors, so the next step is probably to make all of those default methods on the `Emitter` trait, at which point there is not much left to `Handler` and it can probably go.

**Pull request merged**
