### PR TITLE
Audit C++ types in rustllvm

### LINKED ISSUE #35131: rustc/LLVM DiagnosticKind mismatch causes crash when bootstrapping unoptimized w/ MIR.
I'm unable to build rustc with MIR on my machine. I've tried to do a completely fresh build by running:

    $ git clone https://github.com/rust-lang/rust
    $ cd rust
    $ ./configure --enable-debug --disable-docs --enable-orbit
    $ make check-stage1

.. and rustc segfaults 

    rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore
    /home/shum/src/rust/rust/mk/target.mk:212: recipe for target 'x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.core' failed
    make: *** [x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.core] Segmentation fault

I'm running gentoo linux-3.14.14 x86_64 on a Core i7-2677M with 4GB of RAM.

### PR DESCRIPTION
**Pull request by arielb1**
cc @eddyb 

Fixes #35131

### CODE REVIEW

**Comment by badboy** [comment]
Oh nice! Thanks, @arielb1

**Comment by murarth** [comment]
I don't understand how you can say that the `ExecutionEngine` API may bitrot when it's being used by Rusti, an actively maintained project. You can see for yourself all the "Fix for nightly" commits in its history, which goes back over a year and a half.

**Pull request merged**
