### PR TITLE
Update the `cc` crate

### PR DESCRIPTION
**Pull request by alexcrichton**
Pulls in updated MSVC detection logic landed in alexcrichton/cc-rs#488

### CODE REVIEW

**Comment by alexcrichton** [comment]
Given bugs like https://github.com/alexcrichton/cc-rs/issues/493 I think this may also be a good candidate for backporting since it should be pretty low-risk and may be good to accelerate getting this out to users.

**Comment by Mark-Simulacrum** [comment]
Looks like the diff here is https://github.com/alexcrichton/cc-rs/compare/1.0.50...1.0.52 -- that all looks reasonable to me. I agree that the MSVC version detection logic being broken on at least some systems it seems good to backport this so I'm going to go ahead and nominate.

@bors r+

**Comment by pnkfelix** [comment]
discussed at [T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/27154weeklymeeting2020050754818.html#196775693). Accepted for beta-backport.

**Pull request merged**
