### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by workingjubilee**
Successful merges:

 - #121216 (Always emit `native-static-libs` note, even if it is empty)
 - #123726 (Clarify `Command::new` behavior for programs with arguments)
 - #125722 (Indicate in `non_local_defs` lint that the macro needs to change)
 - #126088 ([1/2] clean-up / general improvements)
 - #126390 (Fix wording in {checked_}next_power_of_two)
 - #126392 (Small style improvement in `gvn.rs`)
 - #126402 (Fix wrong `assert_unsafe_precondition` message for `core::ptr::copy`)
 - #126445 (Remove failing GUI test to stop blocking CI until it is fixed)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=121216,123726,125722,126088,126390,126392,126402,126445)

### CODE REVIEW

**Comment by workingjubilee** [comment]
This is a rollup of documentation-only, style-only, or diagnostic-only changes with the unblock-CI-PR of #126445 (which I am rolling up because the fix is trivial). If this fails I will eat my hat.

@bors r+ p=14 rollup=never

**Comment by workingjubilee** [comment]
what.

**Comment by workingjubilee** [comment]
if that wasn't just a network transmission failure resulting in corrupted data then I guess I better start picking out a sauce for my hat.

**Comment by lqd** [comment]
At least the rustdoc tests seem fixed, the builder passed in the PR itself, which is a good sign for keeping a hat-free healthy diet

**Comment by workingjubilee** [comment]
delicious hat, got it.

**Comment by workingjubilee** [comment]
annoying, this had already failed in https://github.com/rust-lang/rust/pull/126441 but I didn't notice.

**Pull request closed without merging**
