### PR TITLE
Don't leak the compiler's internal representation of scopes in error messages.

### LINKED ISSUE #27942: DestructionScopeData can leak into error messages
``` Rust
pub trait Resources<'a> {}

pub trait Buffer<'a, R: Resources<'a>> {
    fn select(&self) -> BufferViewHandle<R>; // should be BufferViewHandle<'a, R>
}

pub struct BufferViewHandle<'a, R: 'a+Resources<'a>>(&'a R);

fn main() {}
```

Post-RFC1214, this gives the not-particularly-comprehensible error message

```
<anon>:6:5: 6:45 error: mismatched types:
 expected `Resources<'_>`,
    found `Resources<'a>`
(lifetime mismatch) [E0308]
<anon>:6     fn select(&self) -> BufferViewHandle<R>;
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:6:5: 6:45 help: see the detailed explanation for E0308
note: the anonymous lifetime #1 defined on unknown free region bounded by scope DestructionScopeData { node_id: 9 }...
note: ...does not necessarily outlive the lifetime 'a as defined on unknown free region bounded by scope DestructionScopeData { node_id: 9 }
<anon>:6:5: 6:45 error: mismatched types:
 expected `Resources<'_>`,
    found `Resources<'a>`
(lifetime mismatch) [E0308]
<anon>:6     fn select(&self) -> BufferViewHandle<R>;
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:6:5: 6:45 help: see the detailed explanation for E0308
note: the lifetime 'a as defined on unknown free region bounded by scope DestructionScopeData { node_id: 9 }...
note: ...does not necessarily outlive the anonymous lifetime #1 defined on unknown free region bounded by scope DestructionScopeData { node_id: 9 }
error: aborting due to 2 previous errors
```

In general, debug output of compiler structs shouldn't leak into error messages (also see https://github.com/rust-lang/rust/issues/13998).

### LINKED ISSUE #37884: Received "note: first, the lifetime cannot outlive the anonymous lifetime #2 defined on unknown free region bounded by scope CodeExtent(9898/CallSiteScope { fn_id: NodeId(4519), body_id: NodeId(18425) })..."
Receiving info about MIR or some other intermediate form in a user error report.

I tried this code which most likely has some lifetime issue that I am yet to resolve:
```rust
pub fn accept_cmd(tcp_ctx: &Arc<RwLock<TCP>>, dl_ctx: &Arc<RwLock<DataLink>>, port: u16) {
    let s = (*tcp_ctx.write().unwrap()).v_socket();                                       
    {                                                                                     
        let tcp = &mut (*tcp_ctx.write().unwrap());                                       
        match s {                                                                         
            Ok(ref sock) => {                                                             
                match tcp.v_bind(dl_ctx, *sock, None, port) {                             
                    Ok(_) => {                                                            
                        match tcp.v_listen(dl_ctx, *sock) {                               
                            Ok(_) => trace!("v_listen() succeeded"),                      
                            Err(e) => error!("v_listen: {}", e),                          
                        }                                                                 
                    }                                                                     
                                                                                          
                    Err(e) => error!("v_bind: {}", e),                                    
                }                                                                         
            }                                                                             
            Err(ref e) => error!("v_socket: {}", e),                                      
        }                                                                                 
    }                                                                                     
    let sock = s.unwrap();                                                                
    let tcp_ctx_clone = tcp_ctx.clone(); // <------------- Error here
    thread::spawn(move || {                                                               
        loop {                                                                            
            match tcp::v_accept(&tcp_ctx_clone, sock, None) {                             
                Ok(socket) => trace!("v_accept returned {}", socket),                     
                Err(e) => error!("v_accept: {}", e),                                      
            }                                                                             
        }                                                                                 
    });                                                                                   
}                                                                                         
```

I should have received information about the scope defined by some part of my code or if the issue is with auto-generated code then possibly no information about an internal scope.

Instead, this happened:

```rust
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
   --> src/main.rs:128:33
    |
128 |     let tcp_ctx_clone = tcp_ctx.clone();
    |                                 ^^^^^
    |
    = note: first, the lifetime cannot outlive the anonymous lifetime #2 defined on unknown free region bounded by scope CodeExtent(9898/CallSiteScope { fn_id: NodeId(4519), body_id: NodeId(18425) })...
note: ...so that types are compatible (expected &std::sync::Arc<std::sync::RwLock<tcp::TCP<'_>>>, found &std::sync::Arc<std::sync::RwLock<tcp::TCP<'_>>>)
   --> src/main.rs:128:33
    |
128 |     let tcp_ctx_clone = tcp_ctx.clone();
    |                                 ^^^^^
    = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the type `[closure@src/main.rs:129:19: 136:6 tcp_ctx_clone:std::sync::Arc<std::sync::RwLock<tcp::TCP<'_>>>, sock:usize]` will meet its required lifetime bounds
   --> src/main.rs:129:5
    |
129 |     thread::spawn(move || {
    |     ^^^^^^^^^^^^^

```

## Meta

`rustc --version --verbose`:
```
rustc 1.15.0-nightly (ba872f270 2016-11-17)
binary: rustc
commit-hash: ba872f270781ada15426cfac7db20b30b81777dc
commit-date: 2016-11-17
host: x86_64-unknown-linux-gnu
release: 1.15.0-nightly
LLVM version: 3.9
```

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #37884 (actually fixes #27942, which was made worse by #37412) by handling more node types.
Ideally we'd turn the unknown node type situations into ICEs and fix them as they show up in errors.
But we might want to backport this patch so I was less aggressive.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Marked as beta-accepted: regr in diagnostics, low risk change.

**Comment by alexcrichton** [comment]
@bors: p=1

(beta nominated)

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Comment by eddyb** [comment]
How can that even happen? It almost sounds like one line was replaced with the previous line, musl bug?

**Comment by nikomatsakis** [comment]
@eddyb 

looks legitimate

```
   Compiling rustc v0.0.0 (file:///checkout/src/librustc)

error[E0531]: unresolved tuple struct/variant `hir::MethodTraitItem`

   --> /checkout/src/librustc/infer/error_reporting.rs:118:17

    |

118 |                 hir::MethodTraitItem(..) => "method body",

    |                 ^^^^^^^^^^^^^^^^^^^^

error[E0531]: unresolved tuple struct/variant `hir::ConstTraitItem`

   --> /checkout/src/librustc/infer/error_reporting.rs:119:17

    |

119 |                 hir::ConstTraitItem(..) |

    |                 ^^^^^^^^^^^^^^^^^^^

error[E0531]: unresolved tuple struct/variant `hir::TypeTraitItem`

   --> /checkout/src/librustc/infer/error_reporting.rs:120:17

    |

120 |                 hir::TypeTraitItem(..) => "associated item"

    |                 ^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors
```

**Comment by eddyb** [comment]
I think I'll keep changes that are needed solely to make the original patch on master, separate.
At least then the original commit should still apply on beta.

**Comment by eddyb** [comment]
@alexcrichton Do you have the build failure?

**Comment by alexcrichton** [comment]
@eddyb unfortunately no

**Pull request merged**
