### PR TITLE
Add `x.py check --stage 1`

### LINKED ISSUE #46955: Add `x.py check --stage 1`
When modifying the interface between platform-specific/non-platform-specific parts of the codebase, proper testing requires being able to build for every supported target, which is very impractical. Ideally `x.py` would support `cargo check` such that platform specific code could still be validated and type checked without needing the corresponding cross-compiling C toolchains.

This requires at least #44737 to be fixed to be useful.

### PR DESCRIPTION
**Pull request by jyn514**
This is useful for several cases:

- Checking changes to the standard library with `cfg(not(bootstrap))` (https://github.com/rust-lang/rust/issues/78466)
- Checking platform-specific changes to the compiler. In particular,
  checking with stage 1 doesn't require a cross-compiling C native
  toolchain, unlike building. (https://github.com/rust-lang/rust/issues/46955)
- Testing newly added internal lints without having to rebuild
  rustc_middle twice (this is what finally made me decide to work on it: https://github.com/rust-lang/rust/pull/80524)

It is also very easy to support.

Closes https://github.com/rust-lang/rust/issues/46955.

### CODE REVIEW

**Comment by jyn514** [comment]
cc @Diggsey - is this what you expected for https://github.com/rust-lang/rust/issues/46955 ?

**Comment by Diggsey** [comment]
Heh, that's an old issue 😄 - yeah it looks like this solves it.

**Comment by jyn514** [comment]
Yeah, I was triaging bootstrap issues a while ago and it popped up as something I'd want myself too :laughing:

**Comment by jyn514** [comment]
I don't know why I thought this would be easy :facepalm: 

```
error: internal compiler error: compiler/rustc_mir/src/monomorphize/collector.rs:826:9: cannot create local mono-item for DefId(1:1638 ~ std[338b]::env::var)

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

**Comment by jyn514** [comment]
Reporting on my progress so far, because I won't get it done tonight and I will definitely forget by tomorrow:

- The ICE comes from https://github.com/rust-lang/rust/blob/058a71016553f267ae80b90276ef79956457d51a/compiler/rustc_mir/src/monomorphize/collector.rs#L825. It happens because there's no MIR built for the standard library, only check metadata (because `x.py check` didn't build it). In particular, this only happens for build scripts and proc-macros, because they need to actually run.
- The way stage 0 solves this is with a 'snapshot sysroot': https://github.com/rust-lang/rust/blob/master/src/bootstrap/builder.rs#L1173-L1194. This works because the metadata generated by `x.py check`, `stage0-std`, is *separate* from the beta libstd, in `stage0`. This doesn't work for stage 1 because the beta libstd was built by beta, and the build scripts/proc macros are being compiled by stage1. It's not possible to compile the proc macros with stage 0 because the ABI is different and they need to link to the standard library with the stage1 compiler.
- A possible fix I thought of is to unconditionally build a standard library for the host with stage1. It will *only* be used for building build scripts/proc macros and nothing else; all other crates should use the library of the *target* instead.

I tried implementing that just now and it went badly. I'm planning to wait to hear from @Mark-Simulacrum about whether this is a good idea first and whether there's a good way to do this without rewriting half of bootstrap.

**Comment by Mark-Simulacrum** [comment]
- Checking changes to the standard library with `cfg(not(bootstrap))` (https://github.com/rust-lang/rust/issues/78466)

This sort of makes sense, but I think I'd prefer folks use `--keep-stage-std 0` for this case. They're going to need to build a compiler anyway, and the difference between checking and building std is relatively minimal.

- Checking platform-specific changes to the compiler. In particular,
  checking with stage 1 doesn't require a cross-compiling C native
  toolchain, unlike building. (https://github.com/rust-lang/rust/issues/46955)

I admit I don't fully follow this use case. I think there's very little platform-specific code in the cargo check phase of the compiler (indeed, other than differences between 32/64 bit, I can't obviously think of some). Maybe would be good to elaborate on this a bit.

- Testing newly added internal lints without having to rebuild
  rustc_middle twice (this is what finally made me decide to work on it: https://github.com/rust-lang/rust/pull/80524)

This, on the other hand, is where the value is much more likely to be. I've filed https://github.com/rust-lang/rust/pull/81064 to replace this PR, and set you as the reviewer. It looks like there's some configuration etc changes here which would be good to propagate, so feel free to push to my branch (or cherry-pick my commit, whatever).

**Comment by jyn514** [comment]
> I admit I don't fully follow this use case. I think there's very little platform-specific code in the cargo check phase of the compiler (indeed, other than differences between 32/64 bit, I can't obviously think of some). Maybe would be good to elaborate on this a bit.

I think the point is not that the *compiler* is platform specific but that the code being *compiled* is platform specific. @Diggsey probably knows more than I do, but it seems useful to check libstd for various different targets without having to have a cross-compiling C toolchain instead.

**Comment by jyn514** [comment]
Anyway, closing this in favor of https://github.com/rust-lang/rust/pull/81064, which I think is a better approach.

**Comment by Mark-Simulacrum** [comment]
Well, the intersection of cfg not bootstrap and target specific code is probably really low, so probably regular check should work ok for that.

**Pull request closed without merging**
