### PR TITLE
WIP: parse swapped pub and async

### PR DESCRIPTION
**Pull request by JohnTitor**
_This is a draft_

cc: #52790

r? @estebank

### CODE REVIEW

**Comment by estebank** [comment]
It's weird that your `hoge` error isn't being emitted. That makes me think that we're not touching the right code. I'll take a look at it later.

For now, I think that you're only changing the code for trait items, like

```
trait T {
    async fn foo() -> usize {}
}
```

but I think that will still not trigger because of it gets caught at [`missing_assoc_item_kind_err`](https://github.com/rust-lang/rust/blob/614add6397dfe7821011424a44a2936c8c2d0e25/src/libsyntax/parse/parser.rs#L6575-L6600) because of [a fall-through](https://github.com/rust-lang/rust/blob/614add6397dfe7821011424a44a2936c8c2d0e25/src/libsyntax/parse/parser.rs#L1544-L1548) for the trait declaration and [an early return](https://github.com/rust-lang/rust/blob/614add6397dfe7821011424a44a2936c8c2d0e25/src/libsyntax/parse/parser.rs#L6607) for the `impl` parsing, where the compiler thinks it should be [parsing a macro](https://github.com/rust-lang/rust/blob/614add6397dfe7821011424a44a2936c8c2d0e25/src/libsyntax/parse/parser.rs#L8400-L8433).

**Comment by JohnTitor** [comment]
yes, the expected error isn't appeared. If the process doesn't reach, we should touch other places, I think. What should I do?

**Comment by JohnTitor** [comment]
@estebank Uh, Should I close this PR once, or work on?

**Comment by estebank** [comment]
@JohnTitor sorry for not being more responsive, I've been away for a couple of weeks.

> If the process doesn't reach, we should touch other places, I think. What should I do?

I'll take a look at this sometimes this week to find where the right place to touch is, but you're certainly in the right "neighborhood".

**Comment by Mark-Simulacrum** [comment]
@estebank Can you take a look at this PR again? It looks like @JohnTitor still needs some help.

**Comment by JohnTitor** [comment]
I'm sorry but I can't have time to investigate at this time. Feel free to close this PR if we need to investigate more.

**Comment by Mark-Simulacrum** [comment]
No worries! Let us know if you decide to re-investigate so we can reopen this pull request or you can also just open a new one.

**Pull request closed without merging**
