### PR TITLE
Fixes #27805 - adds missing snapshots for Bitrig and FreeBSD

### LINKED ISSUE #27805: Missing snapshots for Bitrig, FreeBSD 32-bit and FreeBSD 64-bit
This issue is for adding the snapshots.

### PR DESCRIPTION
**Pull request by dhuseby**
@alexcrichton please upload these snapshots when landing this patch:

https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2015-08-11-1af31d4-bitrig-x86_64-739e0635cd5a1b3635f1457aae3ef6390ea9a7a8.tar.bz2
https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2015-08-11-1af31d4-freebsd-i386-3cd4a44fb97b3135be3d1b760bea604a381e85dc.tar.bz2
https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2015-08-11-1af31d4-freebsd-x86_64-de1f36592bac0eeb90c049a8421246652c511b9e.tar.bz2

### CODE REVIEW

**Comment by dhuseby** [comment]
doh!

**Comment by dhuseby** [comment]
@alexcrichton I really need to figure out why the snapshots are building and being included automagically.  Any ideas?  Is it just test pass/compile failures or is it second-tier status?

**Comment by alexcrichton** [comment]
We currently run `make check` on the snapshot bots, and I believe that because the auto bots are failing it means the snapshot bots will fail tests so the normal snapshot process doesn't work.

**Comment by dhuseby** [comment]
so the bitrig bot was working just fine until the new snapshots were made and added to src/snapshots.txt, then the compiles started failing because there wasn't a bitrig snapshot.  AFAICT, the bitrig build bot should be able to produce snapshots.  i'm less confident in the freebsd ones because there are some tests failing...at least on 32-bit for sure and maybe 64.

**Comment by alexcrichton** [comment]
Yeah it looks like bitrig *should* have produced a snapshot, but here's the logs for why it failed: http://buildbot.rust-lang.org/builders/snap3-bitrig-64/builds/130/steps/compile/logs/stdio. Notably:

```
command timed out: 1800 seconds without output running ['gmake'], attempting to kill
process killed by signal 13
program finished with exit code -1
```

Perhaps it was swapping when compiling librustc? I've noticed it's lagged behind quite a bit on auto builds. If it was running both an auto build and a snap build it may have failed (we may just want to throttle the number of builds on the bot)

**Comment by dhuseby** [comment]
ah yeah, i was having some stability issues last week with the bitrig buildbot vm.  it's been stable for the last week after upgrading the kernel and system libs.

**Pull request merged**
