### PR TITLE
Bump cargo for rust-lang/cargo#4000

### PR DESCRIPTION
**Pull request by jonhoo**
rust-lang/cargo#4000 recently landed, which fixes warnings about using `-Z` when `CARGO_INCREMENTAL` is set while running stable/beta builds. As #41751 has now landed, these warnings will turn to errors in the next release, so getting the cargo fix in place is necessary unless we want people confused about why they can no longer compile anything on stable/beta.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by jonhoo** [comment]
Due to #37107, this keeps being bumped down the homu queue :(
It'd be great to have this included in the next nightly (which if I remember correctly is built in ~2h). Any chance of a rollup?

**Comment by Mark-Simulacrum** [comment]
Legitimate failure, I believe:

```
[01:11:08] failures:
[01:11:08] 
[01:11:08] ---- cargo_compile_incremental stdout ----
[01:11:08] 	libdir: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib"
[01:11:08] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build -v`
[01:11:08] thread 'cargo_compile_incremental' panicked at '
[01:11:08] Expected: execs
[01:11:08]     but: expected to find:
[01:11:08] [RUNNING] `rustc [..] -Zincremental=[..][/]target[/]debug[/]incremental`
[01:11:08] 
[01:11:08] 
[01:11:08] did not find in output:
[01:11:08]    Compiling foo v0.5.0 (file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t11/foo)
[01:11:08]      Running `rustc --crate-name foo src/foo.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=e1a5230cf4545c49 -C extra-filename=-e1a5230cf4545c49 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t11/foo/target/debug/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t11/foo/target/debug/deps`
[01:11:08]     Finished dev [unoptimized + debuginfo] target(s) in 0.57 secs
[01:11:08] ', /cargo/registry/src/github.com-1ecc6299db9ec823/hamcrest-0.1.1/src/core.rs:31
[01:11:08] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:11:08] 
[01:11:08] 
[01:11:08] failures:
[01:11:08]     cargo_compile_incremental
[01:11:08] 
[01:11:08] test result: FAILED. 98 passed; 1 failed; 0 ignored; 0 measured
[01:11:08] 
[01:11:08] error: test failed, to rerun pass '--test build'
```

**Comment by jonhoo** [comment]
I'm quite confused. The same test passes just fine in the cargo repository...
Only thing I can think of is that `is_nightly` is defined as
```rust
        r.verbose_version.contains("-nightly") ||
            r.verbose_version.contains("-dev")
```
Whereas the cargo PR only checks for `contains("nightly")`. Could it be that `rust` compiles with `-dev`?

**Comment by jonhoo** [comment]
Ah, looks like I also missed updating the *other* `cargo` submodule at `src/tools/cargo`. I'll update the PR, and also separate file a cargo PR to update the nightly version matching.

**Comment by jonhoo** [comment]
It is slightly disturbing that all cargo tests passed in the cargo repo, but then one of them fails here. Suggests a mismatch in the setups that maybe we should look into. @alexcrichton any idea why this might happen?

**Comment by alexcrichton** [comment]
Heh I can name a zillion differences between the two, any one of which could cause tests to pass in one location and fail in the other. In any case rust-lang/cargo#4010 should fix this.

**Comment by jonhoo** [comment]
Hehe, fair. Well, that's the hope. If that fails I'm not entirely sure what else it could be. Let's wait and see.

**Comment by jonhoo** [comment]
I eagerly pushed a new commit using #4010 with the expectation that @bors will be happy with it.

**Pull request merged**
