### PR TITLE
rustdoc: update formatting of fn signatures and where clauses to match style rfcs

### LINKED ISSUE #41025: Rustdoc: odd wrapping in code blocks
Link to docs: https://doc.rust-lang.org/nightly/std/borrow/trait.Borrow.html
How it looks on my machine:

Notice the space before `{`. Also, that indentation: `where` is seemingly indented by two spaces, while `fn` is indented by four. However, if I copy the code and paste here, it looks normal:

```rust
pub trait Borrow<Borrowed> where Borrowed: ?Sized {
    fn borrow(&self) -> &Borrowed;
}
```

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Recent updates to style RFCs ([where clauses](https://github.com/rust-lang-nursery/fmt-rfcs/issues/38), [function definitions](https://github.com/rust-lang-nursery/fmt-rfcs/issues/39)) changed the "canonical" style for these items, so this is a rustdoc update to make it emit that style where necessary. This is mainly a conversion from visual indent to block indent, which helps out in situations where there was excessive indent causing lines to wrap regardless.

Samples:

std::iter::IntoIterator

excerpt from std::iter::Iterator

std::iter::FromIterator

std::cmp::min

some trait impls on std::collections::HashMap

`fn extract_code_blocks`, an example given in #40687

excerpt from itertools::Itertools

fixes #41025 and #40687

r? @rust-lang/docs

### CODE REVIEW

**Comment by steveklabnik** [comment]
@rust-lang/docs

**Comment by GuillaumeGomez** [comment]
Good for me. Thanks!

**Comment by QuietMisdreavus** [comment]
Okay, i think i have both passing tests and proper formatting this time.

If you want to browse a full rendering of std with this, [i've got that hosted here](https://shiva.icesoldier.me/custom-std-40687/std/index.html), at least while this PR is open. Some other examples, including some crates i picked out specifically to render with this, [are available as well](https://shiva.icesoldier.me/asdf/asdf/), again, at least while this PR is open. If you find some rendering weirdness (at least with where clauses and fn signatures), let me know.

**Comment by frewsxcv** [comment]
This looks great @QuietMisdreavus! :)

@bors r=frewsxcxv, GuillaumeGomez

**Comment by QuietMisdreavus** [comment]
Oh dear. Do i need to try merging this with a fresh master to see what it's talking about?

**Comment by frewsxcv** [comment]
Nah. This is a homu issue. You can remove the merge commit I'd you want. We'll need to restart bors

**Pull request merged**
