### PR TITLE
Support singleton (without key) compiler queries

### LINKED ISSUE #44699: support singleton queries
I was talking to @michaelwoerister the other day and he observed that a lot of our queries wind up (a) taking a `CrateNum` as argument and (b) only being valid for the `LOCAL_CRATE`. 

Some examples:

- `crate_variances`
- `typeck_item_bodies`
- `borrowck`
- `crate_inherent_impls`
- `crate_inherent_impls_overlap_check`

It seems like it might be nice to support *singleton* queries, where there is no key at all. These queries could forego the hashmap and just be stored in a `RefCell<Option<...>>`. They would be invoked like `tcx.crate_variances()`. 

[Mentoring instructions here.](https://github.com/rust-lang/rust/issues/44699#issuecomment-330908814)

### PR DESCRIPTION
**Pull request by versusvoid**
Fixes #44699 

I'm not very fond of using `Box` and yet another trait to create uniform interface for `GetCacheInternal`, but did not found another solution (except for cloning every `QueryValue` and returning `Vec`). Suggestions are very welcome.

### CODE REVIEW

**Comment by nagisa** [comment]
r? @nikomatsakis 

cc @michaelwoerister

**Comment by eddyb** [comment]
I think this is a step backwards, I chose `CrateNum` as keys not to privilege the "local crate" and in the long term, I want us to experiment with multiple crates in the same compiler session.

**Comment by nikomatsakis** [comment]
Argh, sorry @eddyb for not mentioning you on the original issue! I knew you would have opinions so I  ought to have done so.

Anyway, my assumption was that the compiler would always have a notion of the "local" crate, but that if multiple crates were being compiled at once, that would be handled externally, by something that routed the providers appropriately. 

That said, I don't care to debate it that much. I think it'd be ok to not do this change, in which case I apologize to @versusvoid for the wild goose chase, though I hope you it was helpful to at least learn a bit about how the compiler query mechanism works. =) We might be able to put that knowledge to use doing some of the other performance tweaks that @michaelwoerister and I have talked about from time to time.

**Comment by eddyb** [comment]
FWIW, as far as the actual change is involved, the impact should be minimal either way. And I believe we do have queries that don't include a `CrateNum`, they just have `HirId` or something, in which case, we could just go with this and figure out how to integrate something else later.

That is, I've already lost the argument due to all the querification in the past few months.

**Comment by arielb1** [comment]
Couldn't we add a `LocalCrate` unit type?

**Comment by eddyb** [comment]
@arielb1 I was just telling @nikomatsakis that our keys *could* be variadic and we can hide the tupling inside the macro, only using it for expressing the `HashMap` keys.

**Comment by nikomatsakis** [comment]
I like the idea of "variadic" queries. Maybe we should consider going that direction? It's always a bit awkward to create the tuples when a query takes multiple argments, it'd be nice to hide it.

**Comment by carols10cents** [comment]
@eddyb @nikomatsakis @arielb1 What's the status of this PR please? I'm having a hard time telling :)

**Comment by nikomatsakis** [comment]
Good question. My sense is that we're going to close it and revisit this topic later. I'll do that. (I also talked with @versusvoid offline.)

**Pull request closed without merging**
