### PR TITLE
Remove reference to NoSend in concurrency chapter of the book

### LINKED ISSUE #23052: Remove reference to NoSend in the concurrency guide
The concurrency section in the guide refers to the marker::NoSend trait, but that's been replaced with a negative impl on Send. This should be updated.

(A side note, I think the whole chapter is due for an update. The use of Arc and Mutex and how they got rid of compiler errors feels like magic to me. Furthermore, why does MutexGuard not implement Send in the first place? etc.)

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #23052

### CODE REVIEW

**Comment by Manishearth** [comment]
(This merged, https://github.com/rust-lang/rust/commit/e56fcbcd9959f3bbc0ff2c3f796dedc72c28c865)

**Comment by dotdash** [comment]
This was merged by #23200

**Pull request closed without merging**
