### PR TITLE
Canonicalize path when displaying a `FileName::Real`

### PR DESCRIPTION
**Pull request by basavesh**
Addresses #51349 (?)
Follow-up #68654

Currently, I see two rustdoc tests failing. Not sure If I should add test cases or modify something else.

r? @estebank

> Errors
> ---- [rustdoc] rustdoc/test_option_check/test.rs stdout ----
> 
> error: No test has been found... {"src/test/rustdoc/test_option_check/test.rs": [8, 15], "src/test/rustdoc/test_option_check/bar.rs": [6]}
> 
> ---- [rustdoc] rustdoc/test_option_check/bar.rs stdout ----
> 
> error: No test has been found... {"src/test/rustdoc/test_option_check/bar.rs": [6]}
> status: exit code: 0
> 
> failures:
>     [rustdoc] rustdoc/test_option_check/bar.rs
>     [rustdoc] rustdoc/test_option_check/test.rs

### CODE REVIEW

**Comment by basavesh** [comment]
The issue seems to be 
`f.rs:9:5` v/s `/checkout/src/test/run-make-fulldeps/libtest-json/f.rs:9:5`

>  {"type": "test", "name": "b", "event": "failed", "stdout": "thread 'main' panicked at 'assertion failed: false', f.rs:9:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n" }
> 3248
> 3249
>  { "type": "test", "name": "b", "event": "failed", "stdout": "thread 'main' panicked at 'assertion failed: false', /checkout/src/test/run-make-fulldeps/libtest-json/f.rs:9:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n" }

**Comment by basavesh** [comment]
@estebank Do you think it is worth fixing this?

**Comment by estebank** [comment]
It would be worth fixing this and adding tests specifically for the case being addressed. The tests failing now are because we now output the full path for files instead of the relative path. I think we would want the current behavior to remain and for the case of `extract/tests/query/../helper.rs` the output should be `extract/tests/helper.rs` instead of `/full/path/to/extract/tests/helper.rs`, which might not be a trivial thing to do.

**Comment by basavesh** [comment]
Closing this pull request for now.

**Pull request closed without merging**
