### PR TITLE
Move some tests to more reasonable directories - 2

### PR DESCRIPTION
**Pull request by c410-f3r**
All tests with a score equal or greater than 1.0 were moved to their respective directories by issuing

```bash
cat FILE | tr -s " " | tr -d '():' | sort -k3 | awk '$3 >= 1' | cut -d " " -f1-2 | sed 's;\\;/;g' | xargs -n2 git mv
```
**Observation**: The first column values is the only column with results greater zero

To attest the confidentiality of the model, some manual revision of at least of tests is needed and this process will be tracked in the following list:

* `src/test/ui/abi/issue-28676.rs` OK #28676
* `src/test/ui/array-slice-vec/issue-15730.rs` OK
* `src/test/ui/associated-types/issue-24338.rs` OK #54823
* `src/test/ui/associated-types/issue-48551.rs` Looks OK #48551
* `src/test/ui/associated-types/issue-50301.rs` Looks OK #63577

...

cc #73494
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
I've improved the report at https://gist.github.com/petrochenkov/3130672b9d5e6c4253a8fe2f34405703 with links to tests and issues for convenience.
I'll review the tests from this PR tomorrow.

**Comment by petrochenkov** [comment]
**Tests that can be removed:**
typestate-cfg-nesting.rs
non-built-in-quote.rs
issue-15881-model-lexer-dotdotdot.rs

**Misclassified tests, better moved elsewhere:**
issue-75599.rs -> parser
issue-8460.rs -> numbers-arithmetic
issue-45199.rs -> borrowck
issue-25916.rs -> binop
issue-17545.rs -> borrowck
issue-29844.rs -> dropck
issue-30018-nopanic.rs -> drop
issue-46471.rs -> borrowck
issue-30302.rs -> lint
priv-in-bad-locations.rs -> privacy
issue-28498-ugeh-with-lifetime-param.rs -> dropck
issue-28498-ugeh-with-trait-bound.rs -> dropck
issue-12582.rs -> pattern
issue-22546.rs -> pattern
size-and-align.rs -> pattern
issue-6449.rs -> pattern
issue-38940.rs -> autoref-autoderef
issue-28848.rs -> regions
issue-51345-2.rs -> nll
issue-14221.rs -> pattern

**Misclassified tests, not clear where to move, let's keep in issues for now:**
issue-65634-raw-ident-suggestion.rs
issue-33140-traitobject-crate.rs
issue-65284-suggest-generic-trait-bound.rs

**Comment by petrochenkov** [comment]
Some subdirectories that proved to be problematic - `binding` (a lot of misclassified tests), `did_you_mean` and `span` (pointless).
We'll need to dismantle them later once `issues` is dealt with.

**Comment by petrochenkov** [comment]
@c410-f3r 
Could you also update the file number limits in `src\tools\tidy\src\ui_tests.rs`?

**Comment by petrochenkov** [comment]
r=me after squashing commits.

**Comment by m-ou-se** [comment]
> Could you also update the file number limits in `src\tools\tidy\src\ui_tests.rs`?

Was it intentional that not even a single new ui test can be added in `src/test/ui/issues`? (E.g. https://github.com/rust-lang/rust/pull/81071 failed because it added a new test.)

**Comment by petrochenkov** [comment]
@m-ou-se 
It's better to move the test from #81071 to `ui/macros`.
We can relax tidy, but then one of the *next* added tests will trigger tidy, so there's probably not much difference.

**Pull request merged**
