### PR TITLE
Add "type_name" support in emulate_intrinsic()

### PR DESCRIPTION
**Pull request by TankhouseAle**
I did some dumb Git things and deleted my original fork repo semi-accidentally (but probably for the best as I'd messed up the history.)

This is the same issue as #61399, which was obviously auto-closed, to be clear.

### CODE REVIEW

**Review by oli-obk — CHANGES_REQUESTED** [review]
lgtm.

Please remove the `str_to_immediate` function, since it is now not necessary anymore (miri can remove its use of it)

**Comment by TankhouseAle** [comment]
> Please remove the `str_to_immediate` function, since it is now not necessary anymore (miri can remove its use of it)

I believe Ralf already did that, [in this commit](https://github.com/rust-lang/rust/commit/77be06b7ed147c80b4b8e035a877cea45ece9f3f#diff-470c35c1f39f9d3f8817435a63c73ad2L366),  made I believe shortly before I intially submitted this issue.

**Comment by oli-obk** [comment]
concurrency is hard :smile: 	thanks for the details!

@bors r+

**Comment by TankhouseAle** [comment]
> concurrency is hard 😄 thanks for the details!

No problem. Should the "changes requested" label be removed, or does it not matter now that Bors has the go-ahead?

**Review by oli-obk — APPROVED** [review]

**Pull request merged**
