### PR TITLE
[WIP] Allow macros in identifier position

### PR DESCRIPTION
**Pull request by bgamari**
This allows macros to be used in identifier position of items, making `concat_idents!` far more useful. This is very much a work in progress.

### CODE REVIEW

**Comment by vadimcn** [comment]
@bgamari, @alexcrichton: So why was this PR abandoned?  Were there any technical problems with it, or just the absence of an RFC?

**Comment by alexcrichton** [comment]
Ah sorry, my memory is a little hazy on this, but I believe it would definitely need to start out with an RFC today.

**Comment by eddyb** [comment]
There was an RFC and [it was rejected](https://github.com/rust-lang/rfcs/pull/215#issuecomment-54690417).
It seems a bit odd to me that it was, because we now have pattern macros and trait/impl interior macros (i.e. macros that can expand to methods or associated items).

**Comment by SiegeLord** [comment]
I don't quite understand how UFCS resolves the desired syntax sugar from my comment in that RFC (if it's meant to). I specifically want a sugaring that looks like this: `foo.bar!(a = 5)` and desugars into `foo.baz(5)` (or the UFCS equivalent). Deviations into `bar!(foo, a = 5)` are unacceptable, and `foo.(bar!(a = 5))` are unfortunate.

**Comment by eddyb** [comment]
@SiegeLord I don't see how that's relevant, you seem to want something which doesn't expand to a single identifier. I am talking about identifier macros in method **name** position, which caused some issues during the implementation of this, though I don't see them mentioned anywhere now.

**Comment by eddyb** [comment]
Oh, I think this was is about conflicts between ident macros and *hypothetical* method macros (which you seem to be referring to). In which case, what I meant about UFCS is that it removes the requirement for the former (you wouldn't use ident macros for methods outside of macros yourself, I wouldn't think), leaving the obvious syntax for the latter.

**Comment by vadimcn** [comment]
So shall we reopen the RFC (and this PR)?   Not being able to create new idents in macros is annoying.

**Pull request closed without merging**
