### PR TITLE
register snapshot 880fb89

### PR DESCRIPTION
**Pull request by flaper87**
r? @alexcrichton

cc @nikomatsakis @pnkfelix

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @dotdash I think this will unblock the `assume` PR?

**Comment by Manishearth** [comment]
c3b77ab41c7b2802d081d788dd020961895120a7 isn't in this :/

**Comment by Manishearth** [comment]
(I'm not keeping this in the rollup, so I gave it a higher priority)

**Pull request merged**
