### PR TITLE
Revert "Convert negate_unsigned feature gate to a warning"

### LINKED ISSUE #27141: negate_unsigned feature gate warning should be changed to feature gate.
negate_unsigned feature gate (librustc_lint/builtin.rs) currently emits a warning instead of actual feature_gate due to backwards [compatibility concerns][1]. After some time passes this warning should be converted to feature gate.

Basically, reverting the “Convert negate_unsigned feature gate to a warning” commit (0ca8e4994ee) from https://github.com/rust-lang/rust/pull/27026 and fixing up conflicts (if any) should do.

Note to any people who are planning to do this: ask somebody from language team whether enough time has passed since we started to emit the warning before submitting a PR.

[1]: https://github.com/rust-lang/rust/pull/27026#issuecomment-122787339

### PR DESCRIPTION
**Pull request by nagisa**
This reverts commit 0ca8e4994ee43ba9dfbded6e129b30ff5fe7a994.

Fixes #27141

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like there's a legit test failure on travis, but otherwise r=me.

**Comment by nagisa** [comment]
I believe I fixed it.

**Comment by alexcrichton** [comment]
Could you squash the commits together as well?

**Comment by nagisa** [comment]
Done.

**Comment by alexcrichton** [comment]
Tagging with relnotes for @brson as well

**Pull request merged**
