### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
10 commits in c91a693e7977e33a1064b63a5daf5fb689f01651..020651c52257052d28f6fd83fbecf5cfa1ed516c
2023-07-31 00:26:46 +0000 to 2023-08-02 16:00:37 +0000
- Update rustix to 0.38.6 (rust-lang/cargo#12436)
- replace `master` branch by default branch in documentation (rust-lang/cargo#12435)
- `#[allow(internal_features)]` in RUSTC_BOOTSTRAP test (rust-lang/cargo#12429)
- ci: rewrite bump check and respect semver (rust-lang/cargo#12395)
- fix(update): Tweak CLI behavior (rust-lang/cargo#12428)
- chore(deps): update compatible (rust-lang/cargo#12426)
- Display crate version on timings graph (rust-lang/cargo#12420)
- chore(deps): update alpine docker tag to v3.18 (rust-lang/cargo#12427)
- Use thiserror for credential provider errors (rust-lang/cargo#12424)
- Clarify in `--help` that `cargo test --all-targets` excludes doctests (rust-lang/cargo#12422)

r? @ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
Feel pretty safe to include this in a rollup. We'll see.

@bors r+ rollup=always

**Comment by Nilstrieb** [comment]
something's messed up in rustix on loongarch: https://github.com/rust-lang/rust/pull/114367#issuecomment-1662032786
@bors r-

**Comment by weihanglo** [comment]
Sorry @Nilstrieb. I thought it was safe to help unblock your PR. I'll take a look then.

**Comment by Nilstrieb** [comment]
https://github.com/rust-lang/libc/blob/28ab9b9e7bd04a5c5aca3f4d78583214f63d4002/src/unix/linux_like/linux/gnu/b64/loongarch64/mod.rs#L322 libc does indeed not have SYS_open for loongarch64

**Comment by Nilstrieb** [comment]
this was fixed in https://github.com/bytecodealliance/rustix/pull/751
@weihanglo

**Comment by weihanglo** [comment]
@heiher could you help fix this?
(Sorry you are the only one I know working on loongarch)

**Comment by heiher** [comment]
> @heiher could you help fix this? (Sorry you are the only one I know working on loongarch)
> 
> EDIT: guess just need a rustix bump.

Yeah. I think we just need a new release of rustix.

**Comment by weihanglo** [comment]
Thanks everyone.

Let's do it again.

@bors r+ p=1 rollup=never

**Pull request merged**
