### PR TITLE
Update clippy

### LINKED ISSUE #66150: `clippy-driver` no longer builds after rust-lang/rust#66143
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#66143, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #66150

r? @ghost

### CODE REVIEW

**Comment by lzutao** [comment]
Need another rustup here: https://github.com/rust-lang/rust-clippy/pull/4792

**Comment by lzutao** [comment]
Also you might need to update Cargo.lock.

**Comment by msizanoen1** [comment]
Please note that the clippy test still assume the test dependencies is in the host rlib directory. However this assumption was broken in rust-lang/rust-clippy#4714.
Also the rustbuild build system always passes the `--target` flag to cargo, which causes it to put the rlib into a separate directory, e.g.: `target/x86_64-unknown-linux-gnu/release/deps` instead of the host rlib directory: `target/release/deps`.
In order to fix this, both the target and host rlib directory must be in the search path.
The environment variable needed to support this is in rust-lang/rust-clippy#4786.

**Comment by msizanoen1** [comment]
https://github.com/rust-lang/rust-clippy/pull/4786 is merged, now you should reupdate clippy and set the TARGET_LIBS like this:
https://github.com/rust-lang/rust/pull/66158#issuecomment-550934090

**Comment by msizanoen1** [comment]
It's `fmt_macros` not found error according to the logs.

-------- Original Message --------

**Comment by msizanoen1** [comment]
https://github.com/rust-lang/rust-clippy/pull/4800

**Comment by msizanoen1** [comment]
```
2019-11-10T12:17:44.1061070Z curl: (56) SSLRead() return error -9806
2019-11-10T12:17:44.1635970Z clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang-refactor: Lzma library error: No progress is possible
2019-11-10T12:17:44.1672050Z tar: Error exit delayed from previous errors.
2019-11-10T12:17:44.1735010Z 
```

**Comment by Manishearth** [comment]
cc @pietroalbini something seems wrong there ^^

**Comment by msizanoen1** [comment]
https://developer.apple.com/documentation/security/1503828-secure_transport_result_codes/errsslclosedabort?language=objc

**Comment by msizanoen1** [comment]
Also it took an hour and 30 minutes before failing.

**Comment by Manishearth** [comment]
@bors retry

i guess that server is just wonky

**Comment by Manishearth** [comment]
@bors r-

needs https://github.com/rust-lang/rust-clippy/pull/4802

**Comment by Centril** [comment]
Updated to clippy HEAD. @bors r+ retry

**Pull request merged**
