### PR TITLE
[beta] master -> beta promotion for 1.37

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This includes the release note patch from stable.

r? @pietroalbini

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/62304 is **not** included in this PR; it will go through the normal beta-nomination/acceptance process.

**Comment by pietroalbini** [comment]
> #62304 is not included in this PR; it will go through the normal beta-nomination/acceptance process.

What's the reason for this? We basically have to backport it to beta anyway since it's on stable now.

**Comment by Mark-Simulacrum** [comment]
I'm not confident that we'll want the exact same patch for beta; at least @eddyb seemed uncertain on the PR. I can include it and we can revert/re-apply a different patch later on if you'd like me to.

**Comment by pietroalbini** [comment]
That would be nice.

**Pull request merged**
