### PR TITLE
Add src/test/ui regression testing for NLL

### PR DESCRIPTION
**Pull request by pnkfelix**
This PR changes `x.py test` so that when you are running the `ui` test suite, it will also always run `compiletest` in the new `--compare-mode=nll`, which just double-checks that when running under the experimental NLL mode, the output matches the `<source-name>.nll.stderr` file, if present.

In order to reduce the chance of a developer revolt in response to this change, this PR also includes some changes to make the `--compare-mode=nll` more user-friendly:

 1. It now generates nll-specific .stamp files, and uses them (so that repeated runs can reuse previously cached results).
 2. Each line of terminal output distinguishes whether we are running under `--compare-mode=nll` by printing with the prefix `[ui (nll)]` instead of just the prefix `[ui]`.

Subtask of rust-lang/rust#48879

### CODE REVIEW

**Comment by pnkfelix** [comment]
(Hmm it seems like the output from NLL may have changed even in the short time period between now and when I created rust-lang/rust#49861 ! Good thing we're putting this in now!)

**Comment by pnkfelix** [comment]
Whenever this gets r+'ed, it probably needs to have p=10 or something because clearly these .nll.stderr files can go stale **very** quickly

**Comment by pnkfelix** [comment]
(hmm, interesting; I had assumed that when I pushed the new commit, that would override the build associated with its parent commit and thus we wouldn't see any log for the build failure associated with that. Clearly that assumption was incorrect...)

**Comment by nikomatsakis** [comment]
@pnkfelix I am a bit nervous about the effect on bors cycle time. NLL is not known to be especially fast right now, and we'll also be running the tests more often. @rust-lang/infra, can we test that somehow?

**Comment by kennytm** [comment]
We could selectively enable this only on one fast image such as `x86_64-gnu`. This means the NLL compare mode should be configurable.

**Comment by Mark-Simulacrum** [comment]
If we're fine with the implementation let's just land it and we can go from there; I don't think there's a good way to analyze potential impact on cycle time before landing.

**Comment by pnkfelix** [comment]
Hmm, I just realized that `ui/span/dropck_vec_cycle_checked.rs` is taking an inordinately long time when compiling under NLL. (I'm doing a run under `time rustc` now to get a precise measure of how long it actually takes. Hopefully this isn't an infinite loop.)

(I had gotten warnings in my prototyping saying that it was running for over 60 seconds, but I was silly and ignored them, thinking that it might be some issue with my local setup.)

I don't think I can land this until at least *that* is resolved.

**Comment by pnkfelix** [comment]
Thanks to commits a771b0f and 1a4326d, this is no longer blocked by #49998.

**Comment by pnkfelix** [comment]
Also, to be clear: I am landing this based on earlier discussions with @nikomatsakis where he essentially said "if the infrastructure team is okay with us landing this, then we should do so, with high priority to avoid test rot", and my understanding from the infrastructure team is that we should go with a "attempt to land it, because there's no reasonable way for us to evaluate the performance impact *without* landing it."

**Comment by ehuss** [comment]
@pnkfelix I'm a little confused by something.  This change made it so that `stderr` files are now written directly to `src/test`.  Previously they were written to the `build` directory and you had to run `update-references` to copy it over.  Was that intentional?  The relevant lines are:

https://github.com/rust-lang/rust/blob/8830a0304327ba8c983555ac5d42cec0569c31bb/src/tools/compiletest/src/runtest.rs#L2883-L2885

Both `output_base_name` and `expected_output_path` are absolute paths, so it just resets to `expected_output_path`.

If not, I can update it in #49812 if you'd like.

**Comment by pnkfelix** [comment]
@ehuss you are correct, the fact that we are writing files to `src/test` was an error in my code. Filed as #50113.

I clearly got my logic wrong here. Will attempt to fix pronto.

**Comment by pnkfelix** [comment]
(also, I recognize that I made matters much worse here because I didn't request a review of the newer changes I had made, which included the bug I injected here. I'm sorry and I will try to do better; regression testing a feature like NLL, while important, was certainly not worth breaking a critical piece of infrastructure.)

On the plus side, hopefully the problem injected by my bug won't cause too much trouble in the short term, since people should hopefully notice that their stderrs are getting overwritten.

**Comment by pnkfelix** [comment]
@ehuss As for this other note you wrote in your comment:

>  Also, it doesn't seem to be working as expected for me. If I start with a test that has a difference with NLL (like augmented-assignments.rs), the first time you run it, it updates the base stderr file. The next time you run it, the NLL pass overwrites the stderr without the .nll portion, causing the base mode to fail again. These lines cause it to never create .nll files if they don't already exist:

I did not attempt to address this in PR #50117 (my fix for #50113). I know there were trade-offs I was considering when I wrote this (see discussion attached to commit 33bcb4ed16b01abeaa762c99e452da82c9c6275f ), but I didn't realize I had gotten things quite that bad. (But obviously I didn't realize a lot of problems in what I had done.)

**Comment by ehuss** [comment]
I think that #49812 fixes both issues.  It essentially always uses the fully-qualified filename (includes nll mode when running nll) when writing out the output (which is only written on failure).  Assuming the regular mode runs before nll, it seems to do the right thing for me.

**Pull request merged**
