### PR TITLE
rustdoc: Remove most fields from ExternalCrate

### PR DESCRIPTION
**Pull request by jyn514**
Once https://github.com/rust-lang/rust/issues/84304 is fixed, I can get rid of ExternCrate altogether in favor of CrateNum, but in the meantime, this shrinks ExternalCrate quite a lot.

This might hurt compile-times; if it does, I can add `primitive` and `keyword` queries. I expect this to improve compilemem.

Helps with https://github.com/rust-lang/rust/issues/76382.

r? GuillaumeGomez

### CODE REVIEW

**Comment by jyn514** [comment]
Interesting  - max RSS looks like noise, but up to -3.8% on instruction count.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by jyn514** [comment]
dist-x86_64-apple-alt failed without logs :/

@bors retry

**Pull request merged**
