### PR TITLE
stabilize `file_create_new`

### LINKED ISSUE #105135: Tracking Issue for `file_create_new`
Feature gate: `#![feature(file_create_new)]`

This is a tracking issue for [`std::fs::File::create_new(path)`](https://doc.rust-lang.org/std/fs/struct.File.html#method.create_new) function.  It is related to [RFC 1252](https://github.com/rust-lang/rfcs/pull/1252), but isn't part of the RFC.

### Public API

```rust
// std::fs

impl File 
    pub fn create_new<P: AsRef<Path>>(path: P) -> io::Result<File>
}
```

### Steps / History

- [X] Implementation: implemented in #98801
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by rursprung**
closes #105135

### CODE REVIEW

**Comment by rursprung** [comment]
@rustbot modify labels: +T-libs-api

note: i found a reference to this as well in this place, but i'm not sure what to do with it since it seems to be generated code (based on the path) and i didn't see what is generating it:
https://github.com/rust-lang/rust/blob/5810deef6941025e6f60bb9a5f7b2a6ca8a9bf76/src/tools/rust-analyzer/crates/ide-db/src/generated/lints.rs#L4703-L4713

**Comment by Nilstrieb** [comment]
This file is part of rust-analyzer, I think they regenerate it on syncs or whatever. Nothing you need to care about.

**Comment by thomcc** [comment]
I'm on vacation currently. But this is libs-api anyway, and needs an FCP.

r? @rust-lang/libs-api

**Review by dtolnay — APPROVED** [review]
Thanks for the PR!

FCP already finished in the tracking issue.

**Pull request merged**
