### PR TITLE
Account for late-bound lifetimes in generics

### PR DESCRIPTION
**Pull request by cjgillot**
Currently, functions have two kinds of lifetime parameters: early-bound (which appear in where clauses or do not appear in inputs), and late-bound. Late-bound lifetimes do not appear in generics, they only exist inside the function signature. For instance, take this code:
```rust
fn foo<'a, 'b, T>() where T: 'b {}
       ^^  ^^
     late  early
```
Then we have `generics_of(foo) = ['b, T]` and `fn_sig(foo::<'b, T>) = for<'a> fn()`.

This PR proposes to make all lifetimes on functions early-bound.
The main motivation is to simplify RPIT and async desugaring, to be submitted as a separate PR (https://github.com/rust-lang/rust/pull/103449).

To achieve that, all lifetimes are included when constructing `generics_of`.  The early vs late distinction is still saved in `GenericParamDefKind::Lifetime`.  The `fn_sig` query no longer returns an higher-ranked `fn` type, but a `fn` type with all lifetimes early-bound.  The higher-ranked version is computed by `Ty::fn_sig` function by rebinding lifetimes based on `GenericParamDefKind::Lifetime`.  The implicit decay from `FnDef` to higher-ranked `fn` is handled in type coercion.

This PR has to work around some the former difference in treatment between early- and late-bound lifetimes. Notably, **changing the amount of late-bound lifetimes between trait and impl is allowed**.
```rust
trait Foo<T> {
    fn foo(self, other: T);
}

impl<'a> Foo<&'a u8> for u8 {
    fn foo<'b>(self, other: &'b u8) {} // OK, even if `'b` did not exist in the trait.
}
```
This makes the current API around rebasing substs an impl to a trait a bit of a footgun.  I shifted the late-bound lifetimes to the end of the generics to mitigate the impact.  This may cause a issues with RPITIT, except if we disallow such liberties with RPITIT.

To simplify the implementation, I also make `late_bound_lifetime_arguments` lint (https://github.com/rust-lang/rust/issues/42868) a hard error.  That lint has been there for 5 years.

There are still a few edges to sand off here.  I'll file an MCP depending on reception by the types team.
Still TODO:
- [ ] verify what chalk does;
- [ ] fortify the subts `rebase_onto` API.

r? types

### CODE REVIEW

**Comment by spastorino** [comment]
r? types

**Comment by oli-obk** [comment]
we should probably land

> To simplify the implementation, I also make late_bound_lifetime_arguments lint (https://github.com/rust-lang/rust/issues/42868) a hard error. That lint has been there for 5 years.

in a separate PR so we can sign off on it there in parallel to reviewing this PR.

**Comment by Dylan-DPC** [comment]
> in a separate PR so we can sign off on it there in parallel to reviewing this PR.

Marking it as blocked on this, also note that that pr linked above has been closed

**Comment by jackh726** [comment]
We discussed this in the types team planning meeting today (https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-07-03.20planning.20meeting/near/372029871). We decided we'd like to have *two* deep dives related to this. First, a background on early/late lifetime distinctions, and second, a proposal on this change (or similar).

Going to unnominate for now, but we should definitely come back to this during the second deep dive.

**Pull request closed without merging**
