### PR TITLE
Translate MIR Repeat (arrays)

### PR DESCRIPTION
**Pull request by nagisa**
r? @nikomatsakis 

I went ahead and replaced repeat count with a `Constant`, because it cannot be non-constant to the best of my knowledge.

### CODE REVIEW

**Comment by nagisa** [comment]
Also, probably fixes https://github.com/rust-lang/rust/issues/29577?

**Comment by dotdash** [comment]
AFAICT `let x = [0; 5*5]` would mean that the repeat is an operand since the constant expression has not been evaluated yet.

**Comment by nagisa** [comment]
Ah, okay. I’ve reverted the Constant part.

**Comment by nikomatsakis** [comment]
This looks good --- I actually think a constant might have been the right choice here though.

**Comment by nikomatsakis** [comment]
(We would have to use the `const_eval` to convert the expression to a constant when building MIR though, not sure what your now-reverted patch was doing.)

**Comment by nikomatsakis** [comment]
@nagisa do you still have the constant part of your patch somewhere I could see it?

**Comment by nagisa** [comment]
@nikomatsakis This is about it (applied over current commit).

```diff
diff --git a/src/librustc_mir/build/expr/as_rvalue.rs b/src/librustc_mir/build/expr/as_rvalue.rs
index 23ca221..e351215 100644
--- a/src/librustc_mir/build/expr/as_rvalue.rs
+++ b/src/librustc_mir/build/expr/as_rvalue.rs
@@ -44,8 +44,8 @@ impl<'a,'tcx> Builder<'a,'tcx> {
             }
             ExprKind::Repeat { value, count } => {
                 let value_operand = unpack!(block = this.as_operand(block, value));
-                let count_operand = unpack!(block = this.as_operand(block, count));
-                block.and(Rvalue::Repeat(value_operand, count_operand))
+                let count = this.as_constant(count);
+                block.and(Rvalue::Repeat(value_operand, count))
             }
             ExprKind::Borrow { region, borrow_kind, arg } => {
                 let arg_lvalue = unpack!(block = this.as_lvalue(block, arg));
diff --git a/src/librustc_mir/repr.rs b/src/librustc_mir/repr.rs
index 89b1afa..4ab08f9 100644
--- a/src/librustc_mir/repr.rs
+++ b/src/librustc_mir/repr.rs
@@ -546,7 +546,7 @@ pub enum Rvalue<'tcx> {
     Use(Operand<'tcx>),
 
     // [x; 32]
-    Repeat(Operand<'tcx>, Operand<'tcx>),
+    Repeat(Operand<'tcx>, Constant<'tcx>),
 
     // &x or &mut x
     Ref(Region, BorrowKind, Lvalue<'tcx>),
diff --git a/src/librustc_mir/visit.rs b/src/librustc_mir/visit.rs
index b4d6075..9f214af 100644
--- a/src/librustc_mir/visit.rs
+++ b/src/librustc_mir/visit.rs
@@ -134,7 +134,7 @@ pub trait Visitor<'tcx> {
 
             Rvalue::Repeat(ref value, ref len) => {
                 self.visit_operand(value);
-                self.visit_operand(len);
+                self.visit_constant(len);
             }
 
             Rvalue::Ref(r, bk, ref path) => {
diff --git a/src/librustc_trans/trans/mir/rvalue.rs b/src/librustc_trans/trans/mir/rvalue.rs
index f3515c0..218edc2 100644
--- a/src/librustc_trans/trans/mir/rvalue.rs
+++ b/src/librustc_trans/trans/mir/rvalue.rs
@@ -51,9 +51,9 @@ impl<'bcx, 'tcx> MirContext<'bcx, 'tcx> {
 
             mir::Rvalue::Repeat(ref elem, ref count) => {
                 let elem = self.trans_operand(bcx, elem);
-                let size = self.trans_operand(bcx, count);
+                let size = self.trans_constant(bcx, count);
                 let base = expr::get_dataptr(bcx, lldest);
-                tvec::iter_vec_raw(bcx, base, elem.ty, size.llval, |b, vref, _| {
+                tvec::iter_vec_raw(bcx, base, elem.ty, size, |b, vref, _| {
                     build::Store(b, elem.llval, vref);
                     b
                 })
```

**Comment by nikomatsakis** [comment]
@nagisa ok, yeah, I think we should change it to a constant then, since indeed the value must be a compile-time constant

**Comment by nagisa** [comment]
@nikomatsakis updated. @dotdash’s case also seems to work without any changes and const-eval in MIR may be expanded as necessary in `as_constant`.

**Comment by nagisa** [comment]
@nikomatsakis re-review, please.

**Comment by nikomatsakis** [comment]
@bors r+

Thanks!

**Comment by ttemel** [comment]
Testing commit db89a75 with merge 94f8304...

**Pull request merged**
