### PR TITLE
Remove useless PhantomData<T> from Arc.

### PR DESCRIPTION
**Pull request by emilio**
It uses NonNull<ArcInner<T>>.

From https://doc.rust-lang.org/std/ptr/struct.NonNull.html:

> Unlike *mut T, NonNull<T> is covariant over T. If this is incorrect for your
> use case, you should include some PhantomData in your type to provide
> invariance, such as PhantomData<Cell<T>> or PhantomData<&'a mut T>. Usually
> this won't be necessary; covariance is correct for most safe abstractions,
> such as Box, Rc, Arc, Vec, and LinkedList. This is the case because they
> provide a public API that follows the normal shared XOR mutable rules of Rust.

So I _think_ this is not needed.

### CODE REVIEW

**Comment by Centril** [comment]
Please check in particular dropck and auto trait interactions :)

**Comment by emilio** [comment]
Huh, I guess it is needed after all for dropck but not for variance per se. The docs for `NonNull<T>` do seem to imply that `NonNull<T>` is the only thing needed for an `Arc<T>`-like container, but apparently that's not true...

Maybe a docs clarification would be on point, but this is clearly not correct. /cc @bholley

**Comment by emilio** [comment]
Ah, I see, it is indeed enough, as long as you don't use `#[may_dangle]` in the destructor. Well, sorry for the noise :)

**Comment by RalfJung** [comment]
Yeah, it's quite important to tell dropck that `Arc` *owns* a `T`. `NonNull` does not do that. (The comment you quote shows that `NonNull` is covariant, but if it were not then the `PhantomData` could not possibly make it covariant anyway.)

**Comment by RalfJung** [comment]
> Ah, I see, it is indeed enough, as long as you don't use #[may_dangle] in the destructor. Well, sorry for the noise :)

It is not -- `PhantomData` is also used for auto trait inference, so e.g. `UnwindSafe` might not behave properly without this `PhantomData`.

If your type "logically" *owns* a `T`, you really need a `PhantomData<T>`.

**Pull request closed without merging**
