### PR TITLE
Make issue references consistent

### LINKED ISSUE #62976: Make references to GitHub issues in diagnostics consistent
Some diagnostics include a link to GitHub issues. From the ui testsuite, I found at least these two patterns:

```
 = note: for more information, see https://github.com/rust-lang/rust/issues/51999
```

```
 = note: for more information, see issue #36887 <https://github.com/rust-lang/rust/issues/36887>
```

These should use the same format. My preference is for the latter:

> `see issue #XXXXX <https://github.com/rust-lang/rust/issues/XXXXX>`

/cc @varkor

### PR DESCRIPTION
**Pull request by matprec**
Fixes https://github.com/rust-lang/rust/issues/62976

cc https://github.com/rust-lang/rust/pull/63008

r? @varkor because you reviewed the original pr

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Failed in rollup
@bors r-

**Comment by matprec** [comment]
Rebased

**Pull request merged**
