### PR TITLE
Convert Dependency Graph Tasks from `in_task`s to `with_task`s

### PR DESCRIPTION
**Pull request by cramertj**
r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
Can we wait until the next release, so we can use closure to `fn` pointer coercions (#39817)?

**Comment by cramertj** [comment]
@eddyb That'd be a lot prettier, haha

**Comment by nikomatsakis** [comment]
It doesn't seem that different? we'd delete a line or two per case, basically, but we'd still wind up re-indenting and everything.

**Comment by nikomatsakis** [comment]
Anyway by the time we land this it'll probably be the next release anyway...

**Pull request closed without merging**
