### PR TITLE
Refactor `alloc/rc.rs` into separate files

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Similar to https://github.com/rust-lang/rust/pull/81269, this patch splits `alloc/rc.rs` into a submodule, tracking `Rc` and `Weak` in separate files making it easier to work on the individual types. Thanks!

## Changes

- `alloc::rc::Rc` now lives in `libraries/alloc/rc/rc.rs`
- `alloc::rc::Weak` now lives in `libraries/alloc/rc/weak.rs`
-  the majority of tests now live in `alloc/tests/arc.rs`
-  one test which tests internals is in `alloc/rc/rc.rs`

r? @KodrAus @Mark-Simulacrum

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Fixed the merge conflict.

If CI passes, I would appreciate a review on this. This is a rather large refactor, and keeping it up to date week over week can be challenging.

**Comment by KodrAus** [comment]
Thanks for working on this @yoshuawuyts!

It looks like we've got a `tidy` lint failure, but I'll run through the diff in the meantime.

**Comment by KodrAus** [comment]
I manually mapped the diff back into the original `rc.rs` file and everything looks like it found its way into the new structure. I'll check out the `tidy` error and try get this through.

**Comment by KodrAus** [comment]
@bors r+

Optimistically. I'll check back in here if the build fails.

**Comment by Mark-Simulacrum** [comment]
@bors rollup=never

These are frequently perf sensitive, unfortunately.

**Comment by KodrAus** [comment]
It looks like we've run into a few more merge conflicts. Sorry for the pain here @yoshuawuyts! Maybe what we could do here is either:

- Pick a time when we're both active and try shepherd this through together quickly
- Try splitting it up in phases, where each file gets its own PR to reduce the chance of conflicts appearing

**Comment by yoshuawuyts** [comment]
@KodrAus picking a time would have my preference. Let's chat on Zulip?

**Comment by crlf0710** [comment]
@yoshuawuyts Ping from triage, it seems CI is still failing here.

**Comment by yoshuawuyts** [comment]
More patches have been merged since. I'm going to shelve this for now (:

**Pull request closed without merging**
