### PR TITLE
Fix object safety checks for new RPITITs

### PR DESCRIPTION
**Pull request by spastorino**
This one goes on top of #108869

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
r=me once rebased

@bors rollup

**Comment by spastorino** [comment]
@compiler-errors, this one goes on top of #108869, maybe we can even close #108869 and just merge this one that contains the commits from #108869

**Comment by compiler-errors** [comment]
r=me, closed the other pr

**Review by compiler-errors — APPROVED** [review]

**Pull request merged**
