### PR TITLE
kmc-solid: Fix SOLID target

### PR DESCRIPTION
**Pull request by kawadakk**
This PR is a follow-up for #86191 and necessary to make the [`*-kmc-solid_*`](https://doc.rust-lang.org/nightly/rustc/platform-support/kmc-solid.html) Tier 3 targets actually usable.

 - Bumps `libc` to 0.2.106, which includes <https://github.com/rust-lang/libc/pull/2227>.
 - Applies the change made by #89324 to this target's target-specific code.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r-
Failed in a rollup
https://github.com/rust-lang/rust/pull/90415#issuecomment-955202105

Looks like the libc crate update causes some problems.

**Comment by kawadakk** [comment]
libc has been bumped to 0.2.106, which should fix the build failure on x86_64-apple (https://github.com/rust-lang/libc/issues/2484).

r? @Mark-Simulacrum

**Comment by kawadakk** [comment]
[The upstream issue](https://github.com/rust-lang/libc/issues/2498) has been fixed by <https://github.com/rust-lang/rust/pull/90495>.

r? @Mark-Simulacrum

**Pull request merged**
