### PR TITLE
Recognize the extra "LLVM tools versions" argument to build-manifest.

### LINKED ISSUE #51699: rustup can't update nightly
There seems to be a malformed URL in the rustup manifest since 1.27 got released today.

```sh
durska:rust alex$ rustup self update
info: checking for self-updates
durska:rust alex$ rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'beta-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-06-22, rust version 1.28.0-nightly (662c70a59 2018-06-21)
info: downloading component 'rustc'
error: failed to parse url: 1.28.0-nightly (662c70a59 2018-06-21)/2018-06-22/rustc-nightly-x86_64-apple-darwin.tar.xz
info: checking for self-updates

       stable-x86_64-apple-darwin unchanged - rustc 1.27.0 (3eda71b00 2018-06-19)
         beta-x86_64-apple-darwin unchanged - rustc 1.28.0-beta.1 (8e6052e77 2018-06-21)
  nightly-x86_64-apple-darwin update failed - rustc 1.28.0-nightly (990d8aa74 2018-05-25)

durska:rust alex$
```

### PR DESCRIPTION
**Pull request by kennytm**
Fix #51699.

### CODE REVIEW

**Comment by mati865** [comment]
It would nice to merge it today so next nightly installs properly (CI for many projects are broken today).
`llvm-tools` component can be fixed later.

**Comment by kennytm** [comment]
We've got 14 hours to wait for review 🙃 (nightlies are released around UTC 00:00)

**Comment by ZhangHanDong** [comment]
```rust
✗ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-06-22, rust version 1.28.0-nightly (662c70a59 2018-06-21)
info: downloading component 'rustc'
error: failed to parse url: 1.28.0-nightly (662c70a59 2018-06-21)/2018-06-22/rustc-nightly-x86_64-apple-darwin.tar.xz
info: caused by: relative URL without a base
```

**Pull request merged**
