### PR TITLE
Revert "Revert "Remove the return_address intrinsic.""

### LINKED ISSUE #34227: return_address intrinsic problematic with MIR and hard/impossible to use safely.
Servo currently can't compile with `-Zorbit` (see servo/servo#11706) and my suspect is `return_address`.

Even if that wasn't the reason, Servo's usage of `return_address` to create a rooting cycle only ever worked because it happened to get the final destination of the call, but with MIR, the call destination might be a temporary, so it's not the final destination anymore.
Servo has a lint for disallowing moves on the types that are being returned, but that analysis is wrong unless performed on *exactly* the MIR we translate.

We also could change the ABI at any time, so the indirect returns becomes direct (we can do this for any pair of pointer-sized values) which would also break Servo.
I'm not even sure how LLVM doesn't miscompile what Servo is doing, capturing an `sret` argument seems quite dubious to me, and some architectures also have an intermediary copy.

AFAIK, the eventual solution is to have proper stack map support, however that might be a long ways off and I don't want to block removing old trans on it.

cc @jdm @pcwalton @Manishearth @rust-lang/compiler

### PR DESCRIPTION
**Pull request by eddyb**
This reverts commit f698cd3a3663a459e459f530f76adef3eeb815fd.

Made possible by the merge of servo/servo#11872, this closes #34227 for good.

### CODE REVIEW

**Comment by jdm** [comment]
The Servo team are good with removing this once more.

**Comment by nagisa** [comment]
cc @rust-lang/core 

There has [been an intent](https://github.com/rust-lang/rust/pull/34491#issuecomment-229095781) from you to get your hands dirty with this, so here’s the ping.

**Comment by nagisa** [comment]
also @rust-lang/lang and @rust-lang/compiler

**Comment by nagisa** [comment]
Note: apparently there’s a bunch of libcore copies out there (e.g. in [redox](https://github.com/redox-os/redox/issues/660)), but the intrinsic is not actually used. These copies will begin to fail to build with nightlies once we remove the intrinsic, but in my eyes that’s acceptable.

**Comment by eddyb** [comment]
@nagisa AFAICT it's not a literal copy, but a submodule pointing to a fork of rust-lang/rust.
The fork appears to just be pinned to an arbitrary commit, with no additional commits of their own.

**Comment by aturon** [comment]
Given that the affected users have signed off (as far as I know, this is basically just Servo), +1 from me.

**Comment by nikomatsakis** [comment]
If servo is good, I'm good. 👍

**Comment by alexcrichton** [comment]
Apparently github didn't realize this was merged, closing.

**Pull request closed without merging**
