### PR TITLE
Remove unneeded tricky macro doc

### LINKED ISSUE #37684: [src] links in beta and nightly documentation are broken
At least some of the `[src]` links in the beta standard library documentation are currently broken. I tried https://doc.rust-lang.org/beta/std/iter/trait.Iterator.html and https://doc.rust-lang.org/beta/std/iter/trait.IntoIterator.html.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #37684.

Macros are still linked in the docs so I'm sure why such thing existed in the first place...

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
You sure? This isn't used by libstd docs, but have you checked libcore docs?
If these pose a problem, I'd suggest trying to remove the `#[cfg(dox)]` (as long as it has no visible effect outside the crate).

**Comment by GuillaumeGomez** [comment]
It's no longer in libcore docs for sure. I'll just remove the `#[cfg(doc)]` if you prefer.

**Comment by frewsxcv** [comment]
Do these changes result in https://github.com/rust-lang/rust/issues/36272 becoming an issue again?

**Comment by frewsxcv** [comment]
Relevant PR https://github.com/rust-lang/rust/pull/37325

**Comment by eddyb** [comment]
I don't want to cause #36272 again.

**Comment by GuillaumeGomez** [comment]
cc @eddyb

**Pull request closed without merging**
