### PR TITLE
Macro reform

### LINKED ISSUE #20008: Macro reform (Tracking issue for RFC 453)
This is a tracking issue for RFC rust-lang/rfcs#453, macro reform.

### PR DESCRIPTION
**Pull request by kmcallister**
Fixes #20008.

This is a [breaking-change].  I've written a [guide to migrating your code](https://gist.github.com/kmcallister/c9ae9b977a7718376c7f).

### CODE REVIEW

**Comment by steveklabnik** [comment]
Does any of this need `[breaking-change]`

**Comment by kmcallister** [comment]
@steveklabnik: Yeah. Since things change a few times in the Git history, maybe I'll just tag the doc commit and provide a link to the migration guide.

**Comment by kmcallister** [comment]
@nikomatsakis is going to review this.

**Comment by nikomatsakis** [comment]
f? @sfackler @cmr

**Comment by sfackler** [comment]
I'll start looking at this tonight.

One quick note from looking at the migration guide - The behavior of `#[plugin]` runtime linking the crate by default seems wrong. It pulls in a *huge* runtime dependency (the entire compiler), and all syntax extension libraries I can think of off the top of my head have separate plugin and runtime crates. My gut feeling is that `#[plugin]` should only link to it as a plugin, and users could have a second un-annotated `extern crate foo` if they actually want to do link to it at runtime.

Apologies if this was already discussed in the RFC, I didn't look at it too closely at the time.

**Comment by cmr** [comment]
All the code looks good, though to @sfackler's point, there is supposed to be a method on the `Registry`(or, I would assume, a flag instead, per-syntax-extension) that determines whether the crate gets linked at runtime.

**Comment by cmr** [comment]
(r=me with that fixed, and a rebase)

**Comment by sfackler** [comment]
It's not totally clear to me when a syntax extension would ever *want* to get linked at runtime, unless we add some machinery to build two versions of the crate, one with the rustc dependency and plugin_registrar and the other without.

**Comment by huonw** [comment]
@sfackler I could vaguely imagine some syntax extension that imports another one and uses its functionality for something.

**Comment by sfackler** [comment]
But then you'd only be importing it at runtime, not compile time in the extension, right? In any case, it seems like it'd make more sense to have the 99.999% case (not wanting to link at runtime) to be "automatic", not the other way around.

**Comment by kmcallister** [comment]
> there is supposed to be a method on the `Registry`(or, I would assume, a flag instead, per-syntax-extension) that determines whether the crate gets linked at runtime.

Yeah, this was the original plan, but it's a bit tricky to pull off.  I'm going to work on that during the alpha period. Plugins aren't part of the stable language, so I don't think the issue is worth blocking this PR with only 5 days left before 1.0-alpha.

**Comment by cmr** [comment]
Needs a rebase. r+.

**Comment by alexcrichton** [comment]
This may want to hold off on removing the `macro_rules` feature gate until https://github.com/rust-lang/rfcs/pull/550 is resolved.

**Comment by nikomatsakis** [comment]
I agree with @alexcrichton about feature gate and had planned to say the same thing.

**Comment by kmcallister** [comment]
> It isn't *required* to use `{...}` with macros, right? (fwiw, tuple structs are declared with `()` and `;`, so the existing usages were not so foreign.)

Correct, and that's a fair point about tuple structs.  Still I think `{...}` is the best style default.

**Comment by kmcallister** [comment]
> This may want to hold off on removing the `macro_rules` feature gate until https://github.com/rust-lang/rfcs/pull/550 is resolved.

I think it's fine to un-gate now, because we are committing to ungating for 1.0-final. In fact it would be bad if alpha users get a `warning: macros are experimental` message, as it implies they won't be available in 1.0.  rust-lang/rfcs#550 is an important issue for the long-term future-proofing of the language, but it's also something of a subtle detail that most users will never encounter during the alpha period.

I talked to @cmr briefly and he seemed roughly agreed with this.

**Comment by cmr** [comment]
Indeed.

On Mon, Jan 5, 2015 at 12:53 PM, Keegan McAllister <notifications@github.com
> wrote:

> This may want to hold off on removing the macro_rules feature gate until
> rust-lang/rfcs#550 <https://github.com/rust-lang/rfcs/pull/550> is
> resolved.
>
> I think it's fine to un-gate now, because we are committing to ungating
> for 1.0-final. In fact it would be bad if alpha users get a warning:
> macros are experimental message, as it implies they won't be available in
> 1.0. rust-lang/rfcs#550 <https://github.com/rust-lang/rfcs/pull/550> is
> an important issue for the long-term future-proofing of the language, but
> it's also something of a subtle detail that most users will never encounter
> during the alpha period.
>
> I talked to @cmr <https://github.com/cmr> briefly and he seemed roughly
> agreed with this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust/pull/20482#issuecomment-68746627>.
>



-- 
http://octayn.net/

**Comment by kmcallister** [comment]
Bisecting locally to find the Android build failure.

**Comment by kmcallister** [comment]
Pushed with a fix for the cross compilation issue in `creader: Load parts of plugin metadata on demand`, which makes that patch smaller.

**Comment by alexcrichton** [comment]
Landed in #20610

**Comment by alexcrichton** [comment]
Merge commit: https://github.com/rust-lang/rust/commit/7975fd9cee750f26f9f6ef85b92a20b24ee24120

**Pull request closed without merging**
