### PR TITLE
Unify binop wording

### LINKED ISSUE #60497: Unify binop errors wording
[The following](https://play.rust-lang.org/?gist=27c03aa1ea7239c56fb2ec66749ee2c4&version=nightly) [two errors](https://play.rust-lang.org/?gist=9bdfbdb401d5e39baf22a31ff125dae8&version=nightly) are actually the same problem but have different output because they are handled in different parts of the compiler. We should unify the output to have similar, if not the same, text.

```
error[E0277]: cannot add `std::option::Option<i8>` to `i8`
 --> src/main.rs:5:13
  |
5 | let sum = x + y;
  |             ^ no implementation for `i8 + std::option::Option<i8>`
  |
  = help: the trait `std::ops::Add<std::option::Option<i8>>` is not implemented for `i8`
```
```
error[E0369]: binary operation `+` cannot be applied to type `std::option::Option<i8>`
 --> src/main.rs:5:13
  |
5 | let sum = y + x;
  |           - ^ - i8
  |           |
  |           std::option::Option<i8>
  |
  = note: an implementation of `std::ops::Add` might be missing for `std::option::Option<i8>`
```

This issue has been assigned to @LeSeulArtichaut via [this comment](https://github.com/rust-lang/rust/issues/60497#issuecomment-562471788).

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Closes #60497 
r? @estebank

### CODE REVIEW

**Comment by estebank** [comment]
You will need to run `./x.py test src/test/ui --stage 1 --bless`

**Comment by LeSeulArtichaut** [comment]
@estebank Updated! Thanks a lot, I was going to rewrite every test by hand 😅

**Comment by LeSeulArtichaut** [comment]
@Dylan-DPC What should I modify?

**Comment by Dylan-DPC** [comment]
You need to fix the tests

**Comment by LeSeulArtichaut** [comment]
@Dylan-DPC I'm sorry, I don't understand what you want me to do. Do I need to write new tests?

**Comment by LeSeulArtichaut** [comment]
@estebank Could you maybe help me on this?

**Comment by estebank** [comment]
The tests are already passing. I have some small misgivings about that big block there, but it should be fine.

@bors r+

**Pull request merged**
