### PR TITLE
Beta rollups

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
- https://github.com/rust-lang/rust/pull/58649
 - https://github.com/rust-lang/rust/pull/58592
 - https://github.com/rust-lang/rust/pull/58574
 - https://github.com/rust-lang/rust/pull/58227
 - https://github.com/rust-lang/rust/pull/58056
 - https://github.com/rust-lang/rust/pull/57859
 - https://github.com/rust-lang/rust/pull/57710

A few of these are via https://github.com/rust-lang/rust/pull/58641.

r? @pietroalbini

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
(Why did highfive comment twice?)

**Comment by pietroalbini** [comment]
@bors r+ p=50

> (Why did highfive comment twice?)

That's a good question, I'll start looking for a good answer!

**Comment by Mark-Simulacrum** [comment]
Discussed on Zulip, will back out the PR that introduced this test: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/beta.20backports

**Pull request merged**
