### PR TITLE
Fix dropck issue of SyncOnceCell.

### LINKED ISSUE #76367: Soundness issue in Drop for SyncOnceCell
#75648 added `#[may_dangle]` to `T` in the `Drop` implementation of `SyncOnceCell`. This is correct for simple types like `T = &str`, but when `T`'s `Drop` implementation accesses borrowed data, this might lead to accessing already dropped data:

```rust
#![feature(once_cell)]

use std::lazy::SyncOnceCell;

struct A<'a>(&'a str);

impl<'a> Drop for A<'a> {
    fn drop(&mut self) {
        dbg!(self.0);
    }
}

fn main() {
        let cell = SyncOnceCell::new();
        {
            let s = String::from("hello world");
            let _ = cell.set(A(&s));
        }
}
```
```
[src/main.rs:9] self.0 = "\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{10}thread 'main' panicked at 'byte index 9 is not a char boundary; it is inside '\u{10}' (bytes 8..9) of `À`', library/core/src/fmt/mod.rs:2043:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes #76367.

### CODE REVIEW

**Comment by matklad** [comment]
Wow, this is super-nice find, thanks @m-ou-se!

Can we add `compile-fail` tests here (maybe just onto the PhantomData field)?

https://github.com/matklad/once_cell/blob/0b65b1523453a0cfbdeeb756a77e0b85e03ea7bf/src/lib.rs#L980-L994

**Comment by matklad** [comment]
And I guess the dropcheck test still passes, so that's good: https://github.com/rust-lang/rust/blob/578e7143936158a0130f17bedcc946cae62583f3/library/std/src/lazy/tests.rs#L316-L323.

r? @KodrAus 

This looks ~~good~~ awesome to me, but I will be traveling, so won't be able to r+

**Comment by matklad** [comment]
@m-ou-se out of curiosity, how did you found out about this issue?

**Comment by matklad** [comment]
Also, I guess cc @RalfJung :) I find it surprising that `UnsafeCell<MaybeUninit<T>>` and `PhantomData<T>`  differe in their effects on the drop check. Which of `UnsafeCell` / `MaybeUninit` / `ManuallyDrop` is responsible for that?

**Comment by m-ou-se** [comment]
> @m-ou-se out of curiosity, how did you found out about this issue?

Uh, I'm not sure. ^^' I have a lot of tabs open in my browser with interesting PRs I want to take a closer look at at some point, and #75648 was one of those. I don't remember why I had this one open. I guess I wanted to remind myself to take a closer look at how `#[may_dangle]` works? Came across it today while cleaning up my tabs, and played around with things a bit until it broke.

**Comment by m-ou-se** [comment]
> Also, I guess cc @RalfJung :) I find it surprising that `UnsafeCell<MaybeUninit<T>>` and `PhantomData<T>` differe in their effects on the drop check. Which of `UnsafeCell` / `MaybeUninit` / `ManuallyDrop` is responsible for that?

I think it's working as intended. It's perfectly safe to drop a `MaybeUninit<T>` with a dangling T, since it doesn't drop the T when dropped. Hard to discover problems like this though. Maybe the documentation of `#[may_dangle]` could use an extra warning about this situation.

**Comment by m-ou-se** [comment]
> Can we add compile-fail tests here (maybe just onto the PhantomData field)?

Sounds like a good idea. What's the best way of doing compile_fail tests in std? As a doctest on some private item, or does std have another preferred way of doing this?

**Comment by RalfJung** [comment]
> Also, I guess cc @RalfJung :) I find it surprising that `UnsafeCell<MaybeUninit<T>>` and `PhantomData<T>` differe in their effects on the drop check. Which of `UnsafeCell` / `MaybeUninit` / `ManuallyDrop` is responsible for that?

I guess its `ManuallyDrop` that has the effect here. dropck is about the code that runs on drop, and with `ManuallyDrop` there is no such code, so this makes sense (as @m-ou-se said). If a manual `drop` *anyway* drops some `T`, a `PhantomData` is required.

**Comment by m-ou-se** [comment]
I've added a `compile_fail` test in the doc comment on the `_marker: PhantomData`.

**Comment by KodrAus** [comment]
Nice find! I’ll update our forge docs on `#[may_dangle]` to include this as something to watch out for.

**Pull request merged**
