### PR TITLE
Fix WASI sleep impl

### LINKED ISSUE #65607: WASI target: thread::sleep() is panicing: unexpected result of poll_oneoff
Following code seems correct though will always panic when compiled to `wasm32-wasi`:

`fn main() {
    std::thread::sleep(std::time::Duration::new(0,5));
}`

compiled with nightly rust 1.40:
`>cargo +nightly build --target wasm32-wasi`

It fails at least in wasmtime and wasmer-js VMs (example https://github.com/dunnock/wabench/tree/master/poll_oneoff_test):
```
> wasmtime target/wasm32-wasi/debug/poll_oneoff_test.wasm

thread 'main' panicked at 'thread::sleep(): unexpected result of poll_oneoff', src/libstd/sys/wasi/thread.rs:61:18
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.
error: failed to process main module target/wasm32-wasi/debug/poll_oneoff_test.wasm
    caused by: Instantiation error: Trap occurred while invoking start function: wasm trap: unreachable, source location: @8f01
```

rustup show:
```
active toolchain
nightly-x86_64-apple-darwin (default)
rustc 1.40.0-nightly (0e8a4b441 2019-10-16)
```

### PR DESCRIPTION
**Pull request by newpavlov**
Closes #65607

@sunfishcode 
Is it fine to use 0 for the `identifier` field? What is this field used for?

### CODE REVIEW

**Comment by sunfishcode** [comment]
@newpavlov That `identifier` field is a historical artifact and isn't used by anything.

**Comment by newpavlov** [comment]
@sunfishcode 
Are there plans to remove it eventually? I think at the very least it's worth to add a deprecation notice to the Core [docs](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md).

P.S.: Slightly relevant to introducing changes to the Core API: can you please take a look at #64434? Are there indeed plans to change `fd_prestat_*` functions?

**Comment by sunfishcode** [comment]
@newpavlov I just submitted https://github.com/WebAssembly/WASI/pull/125 to start the process to remove it :-). And yes, we have just established a versioning scheme.

Concerning #64434, yes, there are changes to the `fd_prestat` functions planned, including adding support for [pre-opened files](https://github.com/WebAssembly/WASI/issues/91) and other resources.

**Pull request merged**
