### PR TITLE
Always enable MultipleReturnTerminators

### PR DESCRIPTION
**Pull request by saethlin**
When this pass was created, LLVM experts said that LLVM prefers a single return. But for example, this pass produces a lot of simplification of `Option::unwrap_or` (and thus possibly other matches?). Let's see what comes out of a perf run...

r? @ghost

### CODE REVIEW

**Comment by bjorn3** [comment]
Didn't know this MIR pass existed. I'm already effectively emulating it in cg_clif: https://github.com/bjorn3/rustc_codegen_cranelift/blob/97e2213c3c31909de388943ac3b1cb024decd6c2/src/base.rs#L310-L325

By the way I think your push caused rust-timer to not get informed about the finished try build.

@rust-timer build 312e3e2441955984d5701aa75594e7c07fdb1672

**Comment by saethlin** [comment]
That's basically what I expected. This PR breaks a lot of codegen tests, LLVM seems to really benefit from only having one return terminator.

But one benchmark gets a fair bit faster, though it is an artificial benchmark.

So I think we might be able to get some wins by running optimizations on the multiple return form, then converting back to the single return form before codegen. Ideally this would be a canonicalization done by LLVM or at whatever phase cranelift is doing its conversion.

**Comment by bjorn3** [comment]
cg_clif converts from single return terminator -> multiple return terminators while codegening jump terminators. AFAIK Cranelift doesn't canonicalize it back to a single return terminator. I never thoroughly benchmarked this change, but I know it improved runtime performance in some cases.

**Comment by saethlin** [comment]
Yeah. I'm saying that if multiple return terminators is better for MIR optimizations but one is better for LLVM, it would be best to handle that canonicalization somewhere LLVM-specific.

**Comment by saethlin** [comment]
Closing this in favor of work in https://github.com/rust-lang/rust/pull/106550 (which is very WIP but has more P than this)

**Pull request closed without merging**
