### PR TITLE
Clarify the difference between get_mut and into_mut for OccupiedEntry

### LINKED ISSUE #49745: Confusing lifetime on HashMap's Entry::get
The lifetime on the [`get()`](https://doc.rust-lang.org/std/collections/hash_map/struct.OccupiedEntry.html#method.get) method's return value is bound to the lifetime of `Entry`. This is intended, as far as I can tell; however, the `into_mut` method allows the `Entry` to be converted into a reference bound to the `HashMap`'s lifetime. But there is no way to get an _immutable_ reference bound to the `HashMap`'s lifetime.

This issue originally arose from [this reddit thread](https://www.reddit.com/r/rust/comments/8a5swr/why_does_hashmaps_entryoccupied_have_get_mut_and/dwxffja/). A minimal usecase example is:

```
fn get_symbol<'a>(symbols: &'a mut HashMap<u32, String>, id: u32) -> &'a str {
    match symbols.entry(id) {
        Entry::Occupied(e) => e.get().to_string(), // BAD! Should be e.into_mut().
        Entry::Vacant(e) => {
            // <snipped bookkeeping>...
            let new_symbol = "foobar".to_string();
            e.insert(new_symbol).as_str()
        }
    }
}
```
[Playground](https://play.rust-lang.org/?gist=12357511c761792681f4b51f679ae593&version=nightly)

From my understanding, it should be safe to add an `into_ref(self) -> &'a V` method to fill this hole. It would be implemented as:
```
pub fn into_mut(self) -> &'a mut V {
    self.elem.into_refs().1
}
```
because the underlying structure `FullBucket` already supports an `into_refs()` method (with the same safety reasoning as `into_mut_refs()`.)

It may also be useful to have an `into_key(self) -> &'a K` method. It should be just as safe (and would use basically the same implementation).

This was previously opened as an issue (#39099) but was self-closed when the poster found the `into_mut()` workaround.

I'd be happy to open a PR for this, but I want to make sure I'm not missing anything obvious here.

### PR DESCRIPTION
**Pull request by frewsxcv**
The examples for both hash_map::OccupiedEntry::get_mut and
hash_map::OccupiedEntry::into_mut were almost identical. This led to some
confusion over the difference, namely why you would ever use get_mut when
into_mut gives alonger lifetime. Reddit thread:
https://www.reddit.com/r/rust/comments/8a5swr/why_does_hashmaps

This commit adds two lines and a comment to the example, to show that the
entry object can be re-used after calling get_mut.

Closes https://github.com/rust-lang/rust/issues/49745

### CODE REVIEW

**Comment by frewsxcv** [comment]
This is a continuation of https://github.com/rust-lang/rust/pull/49743.

**Review by dtolnay — APPROVED** [review]
Looks good, thanks.

**Comment by frewsxcv** [comment]
Fixed the links in the latest force pushes

@bors r=dtolnay

**Comment by Phlosioneer** [comment]
Thank you @frewsxcv for finishing this.

**Pull request merged**
