### PR TITLE
provide various trait implementations for arrays up to 44 elements

### LINKED ISSUE #51192: Provide array impls for arrays up to length 44
Currently various traits are provided for arrays up to length 32: https://github.com/rust-lang/rust/blob/master/src/libcore/array.rs#L259-L264

I'm requesting this be extended up to length 44.

Why? Because bindgen relies on `AsMut<[T]>` for fixed-size arrays, and the linux kernel has some structs with 44-element arrays. Providing impls up to length 44 would permit bindgening the full kernel headers without needing to whitelist/blacklist elements. I realize this is vaguely whack-a-mole, but it's a valuable use-case in my, 100% biased, opinion.

If this idea is acceptable, I'm happy to prepare a patch.

### PR DESCRIPTION
**Pull request by alex**
fixes #51192

### CODE REVIEW

**Comment by alex** [comment]
(The bug has additional context and rationale for why this would be useful)

**Comment by TimNN** [comment]
cc @rust-lang/libs, This PR will probably need a decision from you.

**Comment by alexcrichton** [comment]
Historically the libs team has [decided to not change what we have](https://github.com/rust-lang/rust/pull/29395#issuecomment-155965986), although it's been awhile so we can revisit this decision during the next triage meeting as well.

**Comment by alexcrichton** [comment]
Ok the libs team discussed this yesterday and have reached the [same conclusion as before](https://github.com/rust-lang/rust/pull/29395#issuecomment-155965986), so I'm going to close this. Thanks regardless thoug hfor the PR @alex!

**Pull request closed without merging**
