### PR TITLE
Remove #[static_assert]

### LINKED ISSUE #6676: Better interface for static assert
In #6670 I add a basic form of static assertions (as suggested by graydon in #6568), but it's not nice to use. The biggest problem with it is you need a static variable with a name, that goes through trans and ends up in the object file.

@kud1ing suggested `static_assert!()`, which I think is a nice API but would need some invasive changed to the compiler (I think, uncertain).

### LINKED ISSUE #13951: Static assertions are marked as dead code
```
#[static_assert]
static a: bool = 1 == 1;

fn main() {
}
```
```
/tmp/sa.rs:2:1: 2:25 warning: code is never used: `a`, #[warn(dead_code)] on by default
/tmp/sa.rs:2 static a: bool = 1 == 1;
             ^~~~~~~~~~~~~~~~~~~~~~~~
```

### LINKED ISSUE #23008: static_assert silently passes all consts
No unused attribute warning, either.

```rust
#[static_assert]
pub const BLEH: bool = false;

fn main() { }
```

### PR DESCRIPTION
**Pull request by steveklabnik**
This was always a weird feature, and isn't being used in the compiler.
Static assertions should be done better than this.

Fixes #13951
Fixes #23008
Fixes #6676

This is behind a feature gate, but that's still a

[breaking-change]

(It's not entirely clear to me that this should or shouldn't have an RFC, but if it does, I'm fine blocking on such a thing.)

### CODE REVIEW

**Comment by GBGamer** [comment]
:+1:

**Comment by steveklabnik** [comment]
Brought this up in the meeting, RFC incoming

**Comment by steveklabnik** [comment]
Filed: https://github.com/rust-lang/rfcs/pull/1096

**Comment by steveklabnik** [comment]
@nikomatsakis I have rebased this PR.

**Pull request merged**
