### PR TITLE
Move query code outside macros and store query jobs separately from query results

### PR DESCRIPTION
**Pull request by Zoxc**
Based on https://github.com/rust-lang/rust/pull/50067

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks, @Zoxc!

Do you have any measurements how splitting the map affects memory usage and performance? In the cache miss case, it leads to a few more hashtable lookups than the current version, I think.

**Comment by Zoxc** [comment]
It uses 450MB when compiling syntex_syntax vs. 456MB before. Compile times seems to be slightly reduced, although that may just be due to noise.

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by Zoxc** [comment]
I did some microbenchmarks here too:
Before:
```
  time: 0.827; rss: 36MB        hot query (usize)
  time: 0.942; rss: 170MB       cold query (usize)
  time: 0.911; rss: 170MB       hot query (dummy DefId)
  time: 0.972; rss: 304MB       cold query (dummy DefId)
  time: 0.960; rss: 304MB       hot query (DefId)
  time: 0.953; rss: 438MB       cold query (DefId)
```
After:
```
  time: 0.367; rss: 36MB        hot query (usize)
  time: 0.717; rss: 136MB       cold query (usize)
  time: 0.498; rss: 136MB       hot query (DefId)
  time: 0.795; rss: 237MB       cold query (DefId)
  time: 0.379; rss: 237MB       hot query (dummy DefId)
  time: 0.706; rss: 338MB       cold query (dummy DefId)
```
Before (with incremental compilation):
```
  time: 0.958; rss: 40MB        hot query (usize)
  time: 3.165; rss: 638MB       cold query (usize)
  time: 1.080; rss: 638MB       hot query (dummy DefId)
  time: 3.286; rss: 1237MB      cold query (dummy DefId)
  time: 1.088; rss: 1237MB      hot query (DefId)
```
After (with incremental compilation):
```
  time: 0.511; rss: 40MB        hot query (usize)
  time: 2.584; rss: 605MB       cold query (usize)
  time: 0.680; rss: 605MB       hot query (DefId)
  time: 0.478; rss: 605MB       hot query (dummy DefId)
  time: 2.796; rss: 1170MB      cold query (dummy DefId)
```

**Comment by michaelwoerister** [comment]
Looks very promising, @Zoxc!

**Comment by Zoxc** [comment]
Looks green.
http://perf.rust-lang.org/compare.html?start=25749ad66de71ffb46e6b04fb0cccf1ae4fc5ed5&end=34c50be0a1c561e15f7d02e06c7e47b48a40e444&stat=instructions%3Au

I think I'm going to close https://github.com/rust-lang/rust/pull/50067 in favor of this.

**Comment by michaelwoerister** [comment]
:tada:

**Pull request merged**
