### PR TITLE
Fix ICE when rustdoc encounters certain usages of HRTBs

### LINKED ISSUE #51236: Internal compiler error when documenting `capnp`
Cargo.toml:
```
[dependencies]
capnp = "0.8.17"
```

Result when run `cargo doc`:
```
thread '<unnamed>' panicked at 'Unable to fulfill trait DefId(2/0:864 ~ core[b3f3]::marker[0]::Send[0]) for 'list_list::Owned<T>': [FulfillmentError(Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { substs: [T, ReStatic], item_def_id: DefId(0/0:1150 ~ lib[8787]::traits[0]::Owned[0]::Reader[0]) }, _)),depth=2),Ambiguity), FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<_ as std::marker::Send>)),depth=2),Ambiguity)]', librustc/traits/auto_trait.rs:218:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (5d0631a64 2018-05-30) running on x86_64-unknown-linux-gnu

error: Could not document `capnp`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name capnp /home/qwe/.cargo/registry/src/github.com-1ecc6299db9ec823/capnp-0.8.17/src/lib.rs -o /home/qwe/Desktop/upw/test_rustdoc/target/doc -L dependency=/home/qwe/Desktop/upw/test_rustdoc/target/debug/deps --extern byteorder=/home/qwe/Desktop/upw/test_rustdoc/target/debug/deps/libbyteorder-3355ea0a902fb6f6.rmeta` (exit code: 101)
```

rustc version: nightly-x86_64-unknown-linux-gnu (5d0631a64 2018-05-30)
Also happen in nightly-2018-05-29 and nightly-2018-05-23.

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #51236

Under certain circumstances, `AutoTraitFinder` could end up computing a `ParamEnv` involving two trait predicates that differed only in the region parameters involved. One of these parameters would be a HRTB, while the other would be a normal region parameter.

When this `ParamEnv` was later passed to `SelectionContext`, an `Ambiguity` error would occur, since the erased versions of these predicates would be identical. To solve the issue, we de-duplicate our list of predicates as we build it up. Whenever we encounter two predicates that differ only in their assignment of region parameters (a HRTB vs a normal lifetime parameter), we pick the HRTB. This corresponds to selecting a 'stricter' bound to display in the generated documentation: we're requiring that a particular type works for all possible lifetime parameters if it's going to implement a particular auto trait.

### CODE REVIEW

**Comment by eddyb** [comment]
cc @nikomatsakis We should probably rethink/redo this entire module at some point.
My intuition is that we can at least do something much simpler by ignoring lifetimes, and then maybe find a way to somehow recover lifetime requirements?

@bors r+

**Comment by earthengine** [comment]
It looks like solving this issue causes another. See #53420

**Comment by Aaron1011** [comment]
@earthengine: While the error message is similar, it appears to be a completely different issue. Both rustdoc and rustc make use of `SelectionContext` (which this PR did not modify). That issue is coming from rustc, not rustdoc.

**Pull request merged**
