### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
Biweekly Clippy update.

This includes a Cargo.lock update for the recent Clippy version bump.

r? @Manishearth

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
````
---- check_that_clippy_has_the_same_major_version_as_rustc stdout ----
thread 'check_that_clippy_has_the_same_major_version_as_rustc' panicked at 'failed to run `rustc --version`: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tools/clippy/tests/versioncheck.rs:37:14

````
Mmh, simply calling `rustc` does not work as part of `x.py test` :/

**Comment by flip1995** [comment]
> I'll need to figure out how x.py provides its rustc to the tools

@Matthias247  It should work with `RUSTC_REAL`. Let's wait for CI.

**Comment by matthiaskrgr** [comment]
>@matthiaskrgr It should work with RUSTC_REAL. Let's wait for CI.

Does that also work with our compiletest-based setup in the clippy repo?

**Comment by flip1995** [comment]
I just synced back 5dd64b3 locally and it passed the Clippy test suite. So yes, this works now for both repos, rust-clippy and rust.

**Pull request merged**
