### PR TITLE
Introduce a TargetTriple enum to support absolute target paths

### PR DESCRIPTION
**Pull request by phil-opp**
This PR replaces target triple strings with a `TargetTriple` enum, which represents either a target triple or a path to a JSON target file. The path variant is used if the `--target` argument has a `.json` extension, else the target triple variant is used.

The motivation of this PR is support for absolute target paths to avoid the need for setting the `RUST_TARGET_PATH` environment variable (see rust-lang/cargo#4905 for more information). For places where some kind of triple is needed (e.g. in the sysroot folder), we use the file name (without extension).

For compatibility, we keep the old behavior of searching for a file named `$(target_triple).json` in `RUST_TARGET_PATH` for non-official target triples.

### CODE REVIEW

**Comment by oli-obk** [comment]
Travis failure is legit

**Comment by phil-opp** [comment]
Thanks for the hint, I pushed a new version.

**Comment by phil-opp** [comment]
@pnkfelix I added a commit that appends a hash of the target path when a `TargetPath` is converted to a triple. This avoids collisions when two target files in different folders are named identically. It also allows to differentiate targets with the same name in error messages. For example:

```
error[E0461]: couldn't find crate `core` with expected target triple stm32f7-11703095894775286769
  |
  = note: the following crate versions were found:
          crate `core`, target triple stm32f7-10929095608748322303
```

**Comment by phil-opp** [comment]
Rebased

**Pull request merged**
