### PR TITLE
Rollup of 19 pull requests

### PR DESCRIPTION
**Pull request by alexcrichton**
- Successful merges: #47415, #47437, #47439, #47453, #47460, #47502, #47529, #47600, #47607, #47618, #47626, #47656, #47668, #47696, #47701, #47705, #47710, #47711, #47719
- Failed merges: #47455, #47521

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

assuming spurious...

**Comment by kennytm** [comment]
Same error. Fuchsia's server is flaky?

**Comment by kennytm** [comment]
@bors treeclosed-

Google claims [the issue](https://status.cloud.google.com/incident/cloud-networking/18004) has been resolved for most users, and indeed the `dist-various-2` image has downloaded the Zircon binaries successfully.

**Comment by kennytm** [comment]
Legit, but not sure which PR is the cause.

```
[00:51:47] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:476:22
[00:51:47] failures:
[00:51:47] 
[00:51:47] ---- [ui] ui/issue-45697.rs stdout ----
[00:51:47] 	diff of stderr:
[00:51:47] 
[00:51:47] 6	30 |         *y.pointer += 1;
[00:51:47] 7	   |         ^^^^^^^^^^^^^^^ assignment to borrowed `*y.pointer` occurs here
[00:51:47] 8	
[00:51:47] +	error[E0503]: cannot use `*y.pointer` because it was mutably borrowed (Mir)
[00:51:47] -	error[E0506]: cannot assign to `*y.pointer` because it is borrowed (Mir)
[00:51:47] 10	  --> $DIR/issue-45697.rs:30:9
[00:51:47] 11	   |
[00:51:47] 12	29 |         let z = copy_borrowed_ptr(&mut y);
[00:51:47] 
[00:51:47] +	   |                                   ------ borrow of `y` occurs here
[00:51:47] -	   |                                   ------ borrow of `*y.pointer` occurs here
[00:51:47] 14	30 |         *y.pointer += 1;
[00:51:47] +	   |         ^^^^^^^^^^^^^^^ use of borrowed `y`
[00:51:47] -	   |         ^^^^^^^^^^^^^^^ assignment to borrowed `*y.pointer` occurs here
[00:51:47] 16	
[00:51:47] 17	error: aborting due to 2 previous errors
[00:51:47] 18	
```

**Comment by alexcrichton** [comment]
@bors: retry

good ol' segfaults in git

**Comment by alexcrichton** [comment]
> There was an error while trying to fetch the log.

Gonna assume that was spurious

@bors: retry

**Comment by kennytm** [comment]
`x86_64-pc-windows-msvc`, legit.

```
[02:18:15] failures:
[02:18:15] 
[02:18:15] ---- [pretty] run-pass\trait-inheritance-cross-trait-call-xc.rs stdout ----
[02:18:15] 	
[02:18:15] error: auxiliary build of "C:\\projects\\rust\\src/test\\run-pass\\auxiliary\\trait_inheritance_cross_trait_call_xc_aux.rs" failed to compile: 
[02:18:15] status: exit code: 101
[02:18:15] command: PATH="C:\projects\rust\build\x86_64-pc-windows-msvc\stage2\bin;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64;C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-tools\x86_64-pc-windows-msvc\release\deps;C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-sysroot\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Program Files (x86)\Inno Setup 5;C:\Python27;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial;C:\Program Files\LLVM\bin;C:\Program Files\dotnet;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Tools\vcpkg;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\6.0.0;C:\Program Files\erl9.2\bin;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent;C:\projects\rust;C:\projects\rust\handle" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2\\bin\\rustc.exe" "C:\\projects\\rust\\src/test\\run-pass\\auxiliary\\trait_inheritance_cross_trait_call_xc_aux.rs" "-L" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass" "--target=x86_64-pc-windows-msvc" "-C" "prefer-dynamic" "--out-dir" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\native\\rust-test-helpers" "--crate-type" "dylib" "-L" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux"
[02:18:15] stdout:
[02:18:15] ------------------------------------------
[02:18:15] 
[02:18:15] ------------------------------------------
[02:18:15] stderr:
[02:18:15] ------------------------------------------
[02:18:15] error: linking with `link.exe` failed: exit code: 1104
[02:18:15]   |
[02:18:15]   = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux\\trait_inheritance_cross_trait_call_xc_aux.trait_inheritance_cross_trait_call_xc_aux0-8787f43e282added376259c1adb08b80.rs.rcgu.o" "/OUT:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux\\trait_inheritance_cross_trait_call_xc_aux.dll" "/DEF:C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustc.BPVBh8AAWRxZ\\lib.def" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux\\trait_inheritance_cross_trait_call_xc_aux.crate.metadata.rcgu.o" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux\\trait_inheritance_cross_trait_call_xc_aux.crate.allocator.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\native\\rust-test-helpers" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "std-8c525ca5930ac7cd.dll.lib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustc.BPVBh8AAWRxZ\\libcompiler_builtins-3d7fcf367f7cd6b3.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib" "/DLL" "/IMPLIB:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux\\trait_inheritance_cross_trait_call_xc_aux.dll.lib"
[02:18:15]   = note: LINK : fatal error LNK1104: cannot open file 'C:\projects\rust\build\x86_64-pc-windows-msvc\test\run-pass\trait-inheritance-cross-trait-call-xc.stage2-x86_64-pc-windows-msvc.pretty.aux\trait_inheritance_cross_trait_call_xc_aux.trait_inheritance_cross_trait_call_xc_aux0-8787f43e282added376259c1adb08b80.rs.rcgu.o'
[02:18:15]           
[02:18:15] 
[02:18:15] error: aborting due to previous error
[02:18:15] 
[02:18:15] 
[02:18:15] ------------------------------------------
[02:18:15] 
[02:18:15] thread '[pretty] run-pass\trait-inheritance-cross-trait-call-xc.rs' panicked at 'explicit panic', tools\compiletest\src\runtest.rs:2883:9
[02:18:15] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[02:18:15] 
[02:18:15] 
[02:18:15] failures:
[02:18:15]     [pretty] run-pass\trait-inheritance-cross-trait-call-xc.rs
[02:18:15] 
[02:18:15] test result: FAILED. 2846 passed; 1 failed; 59 ignored; 0 measured; 0 filtered out
```

**Pull request merged**
