### PR TITLE
Add a travis builder for wasm32-unknown-emscripten

### PR DESCRIPTION
**Pull request by malbarbo**
This commits add an entry to travis matrix that will execute wasm32-unknown-emscripten tests suites.

- Emscripten for asmjs was updated to sdk-1.37.13-64bit
- The tests are run with node 8.0.0 (it can execute wasm)
- A wrapper script is used to run each test from the directory where it is (workaround for https://github.com/kripken/emscripten/issues/4542)
- Some tests are ignore, see #42629 and #42630

### CODE REVIEW

**Comment by malbarbo** [comment]
This is an alternative to https://github.com/rust-lang/rust/pull/42059

**Comment by malbarbo** [comment]
r? @alexcrichton 

We are running out of builders... but testing wasm32 in the same builder of asmjs would take too much time.

**Comment by alexcrichton** [comment]
Looks awesome, thanks for this! I think that the cwd business could be fixed as well with https://github.com/rust-lang/rust/pull/42059, right?

Perhaps this could add a `disabled/wasm/Dockerfile` for now to land immediately and we could have a future PR to enable?

**Comment by malbarbo** [comment]
> I think that the cwd business could be fixed as well with #42059, right?

I think so.

> Perhaps this could add a disabled/wasm/Dockerfile for now to land immediately and we could have a future PR to enable?

Ok. Can we try this before to confirm it work on travis?

**Comment by alexcrichton** [comment]
Sure yeah! Want to just tag it with `ALLOW_PR=1` on this pr? That way the PR builds should run the travis build.

**Comment by alexcrichton** [comment]
[Timeout](https://travis-ci.org/rust-lang/rust/jobs/242568109) :(

If you run `./src/ci/docker/run.sh wasm` though that should be equivalent to Travis? (if that passes locally I'd be pretty confident it'd pass remotely)

**Comment by malbarbo** [comment]
It passes locally. I will move the image to disabled.

**Comment by malbarbo** [comment]
Done.

**Comment by Mark-Simulacrum** [comment]
@bors retry

Failure appears spurious, possibly git/network related #42117

**Comment by est31** [comment]
@bors retry

* spurious mac timeout

**Comment by alexcrichton** [comment]
@bors: retry

* osx timed out

**Pull request merged**
