### PR TITLE
[stable] 1.45.1 release

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
See RELEASES.md for details on what this contains.

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
#74539 is also stable-nominated, would it also go in this release if accepted?

**Comment by Mark-Simulacrum** [comment]
Yes, it should.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=99

This is targeting Thursday next week, so not super urgent, but I'd like artifacts as soon as possible.

**Comment by Manishearth** [comment]
Perhaps we should p=100 this since nothing else is happening right now? The fetch bug might not affect older branches as much

**Comment by mati865** [comment]
> The fetch bug might not affect older branches as much

It reproduces on 1.43: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/zlib.20errors/near/204837666

**Comment by ehuss** [comment]
Probably needs #74406 and #74418, similar to #74593.

**Comment by Mark-Simulacrum** [comment]
Seems likely to be spurious. @bors retry

**Pull request merged**
