### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This backports/rolls up:

*  Quick fix for #96223. #96679 
*  [beta] Revert #92519 on beta #96556 
*  [beta] Clippy backport ICE/infinite loop fix #96740 
*  Revert "Prefer projection candidates instead of param_env candidates for Sized predicates" #96593

### CODE REVIEW

**Comment by jackh726** [comment]
What about #96593 and #96970?

**Comment by jackh726** [comment]
I guess you're waiting for #96970 to land first, but #96593 has already landed.

**Comment by Mark-Simulacrum** [comment]
I'll roll them in. They're not appropriately tagged it looks like - prior to backport both nominated and accepted should be applied.

**Pull request merged**
