### PR TITLE
Update sysinfo version to 0.31.2

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I needed to update `memchr` version (which was pinned in https://github.com/rust-lang/rust/commit/36a16798f798eb59db21ff2a8a163135b4a599fe). So let's see if it triggers the linker issue.

try-job: x86_64-mingw

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems like it's fine?

r? @clubby789

**Comment by klensy** [comment]
You should try x86_64-pc-windows-gnu or x86_64-pc-windows-msvc?

**Comment by GuillaumeGomez** [comment]
I have set `try-job`. Let's give it a try.

@bors try

**Comment by clubby789** [comment]
Looks like the `sysinfo` API changed - not sure why the other jobs passed? 🤔

**Comment by GuillaumeGomez** [comment]
I'm wondering the same thing. Checking what changed...

**Comment by GuillaumeGomez** [comment]
Let's try again.

@bors try

**Comment by GuillaumeGomez** [comment]
Seems like there is no issue?

**Comment by klensy** [comment]
https://github.com/rust-lang/rust/issues/127890: `The dependency is pinned because the x86_64-pc-windows-gnu target fails`

**Comment by GuillaumeGomez** [comment]
Ah, so it was the other one. Trying it.

@bors try

**Comment by GuillaumeGomez** [comment]
@klensy: Do you know the name to be used for the try build?

**Comment by Kobzol** [comment]
You probably want [this one](https://github.com/rust-lang/rust/blob/9f7e049744bcbc77150c66f5ab39fd46c074a22c/src/ci/github-actions/jobs.yml#L399) for x64 Windows GNU CI job (`x86_64-mingw`).

**Comment by GuillaumeGomez** [comment]
Thanks! Let's try again.

@bors try

**Comment by klensy** [comment]
You're author of sysinfo, is it required to use latest versions of memchr?

**Comment by clubby789** [comment]
Discussion of the issue is on Zulip [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Stuck.20memchr.202.2E5.2E0.20saga)

**Comment by GuillaumeGomez** [comment]
> You're author of sysinfo, is it required to use latest versions of memchr?

I suppose it's not.

**Comment by ChrisDenton** [comment]
You could try using `version = "=2.5.0, 2.7.1"` to both satisfy rustc and allow other people to use the more recent version.

**Comment by GuillaumeGomez** [comment]
Actually I also needed to remove the `bstr` dependency. Well, I guess `sysinfo` will be faster to compile the first time, so not too bad in the end. ^^'

Let's try again.

@bors try

**Comment by GuillaumeGomez** [comment]
Seems like it's all good now!

**Pull request merged**
