### PR TITLE
Json merge prettyencoder and encoder

### PR DESCRIPTION
**Pull request by oli-obk**
@alexcrichton as per https://github.com/rust-lang/rust/pull/12936#issuecomment-37782264
removing ToJson is the next step.

this PR requires #19490 to be merged first, so ignore the first commit on this PR

### CODE REVIEW

**Comment by Gankro** [comment]
Needs rebase

**Comment by oli-obk** [comment]
can't be merged until  #19490 is merged

**Comment by alexcrichton** [comment]
@oli-obk needs a rebase. You may also prefer to just send this upstream to rustc-serialize (but up to you!)

**Comment by oli-obk** [comment]
i do prefer a lot :) done

**Pull request closed without merging**
