### PR TITLE
[beta] Prepare the 1.19.0 beta release

### PR DESCRIPTION
**Pull request by alexcrichton**
* ~~Update the cargo submodule~~
* Update the stage0 bootstrap to 1.18.0 release
* Update release channel to beta
* Disable the RLS (this'll happen next beta hopefully)

Closes https://github.com/rust-lang/rust/issues/42357

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=10

(this is the beta release)

**Comment by arielb1** [comment]
Looks like there is some incompatibility:
```
[00:56:54] error[E0308]: mismatched types
[00:56:54]    --> /checkout/src/tools/rls/src/build.rs:334:32
[00:56:54]     |
[00:56:54] 334 |                         return cmd.exec();
[00:56:54]     |                                ^^^^^^^^^^ expected struct `cargo::util::ProcessError`, found struct `cargo::CargoError`
[00:56:54]     |
[00:56:54]     = note: expected type `std::result::Result<_, cargo::util::ProcessError>`
[00:56:54]                found type `std::result::Result<_, cargo::CargoError>`
```

**Comment by alexcrichton** [comment]
@bors: r+

Looks like no submodule update for us

**Comment by manfredbrandl** [comment]
@alexcrichton travis seems not to recognice that the job 53769.33 has finished compiling.

**Comment by alexcrichton** [comment]
@bors: retry

* osx timed out :(

**Pull request merged**
