### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #115882 (improve the suggestion of `generic_bound_failure`)
 - #116537 (Fix suggestion span involving wrongly placed generic arg on variant)
 - #116548 (Improve handling of assertion failures with very long conditions)
 - #116549 (Simplify some mir passes by using let chains)
 - #116556 (Sync rustc_codegen_cranelift)
 - #116561 (Add a test for fixed ICE)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=115882,116537,116548,116549,116556,116561)

### CODE REVIEW

**Comment by oli-obk** [comment]
This will fail again, since it includes https://github.com/rust-lang/rust/pull/116548

**Comment by matthiaskrgr** [comment]
yeet!

**Pull request closed without merging**
