### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by JohnTitor**
Successful merges:

 - #98583 (Stabilize Windows `FileTypeExt` with `is_symlink_dir` and `is_symlink_file`)
 - #99698 (Prefer visibility map parents that are not `doc(hidden)` first)
 - #99700 (Add a clickable link to the layout section)
 - #99712 (passes: port more of `check_attr` module)
 - #99759 (Remove dead code from cg_llvm)
 - #99765 (Don't build std for *-uefi targets)
 - #99771 (Update pulldown-cmark version to 0.9.2 (fixes url encoding for some chars))
 - #99775 (rustdoc: do not allocate String when writing path full name)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=98583,99698,99700,99712,99759,99765,99771,99775)

### CODE REVIEW

**Comment by pnkfelix** [comment]
* Primary regressions were to clap (check full, check incr-full, and doc full), libc (doc full), hyper (check full, check incr-full, and doc full), image (doc full), and webrender (doc full).
* The significance factor points mostly to the clap cases (with 4.13x, 3.25x, and 7.15x respectively to each of the scenarios I listed above for clap).
* The [detailed query data](https://perf.rust-lang.org/detailed-query.html?sort_idx=-11&commit=e33cc71a61c91e1d510bf283e9d345067e64eed2&base_commit=b573e10d21b69ebfadf41aa9c2f0a27919fe4480&benchmark=clap-3.1.6-check&scenario=full) for clap check full indicates that the problem is mostly in `metadata_decode_entry_item_attrs` and `visible_parent_map`; those are the ones that had a significant time delta that end up explaining the overall time delta (0.003 + 0.003 > 0.005).
* `visible_parent_map` slowdown may be due to [PR #99698](https://github.com/rust-lang/rust/issues/99698).
* The slowdown to `metadata_decode_entry_Item_attrs` may be due to [PR #99712](https://github.com/rust-lang/rust/issues/99712) ? Hard to say.
* The secondary regressions are all to the projection-caching benchmark, which regressed by 1.2% to 2.9% in various scenarios. That regression seems to be to due [a combination](https://perf.rust-lang.org/detailed-query.html?sort_idx=-11&commit=e33cc71a61c91e1d510bf283e9d345067e64eed2&base_commit=b573e10d21b69ebfadf41aa9c2f0a27919fe4480&benchmark=projection-caching-check&scenario=full) of both the `metadata_decode_entry_item_attrs` and `visible_parent_map` regressions, as well as a little bit more time spent in `type_op_prove_predicate`, `evaluate_obligation`, and `normalize_projection_ty`. Not sure why though, I don't think those got touched by this rollup. Maybe just different execution paths from the stdlib changes that *did* come in with this rollup?
* Leaving comments on both the rollup PR and the two suspect PRs from the rollup. Not marking as triaged.

**Comment by compiler-errors** [comment]
Opened #99819 to test perf results. I wouldn't be surprised if #99698 is the reason for both `metadata_decode_entry_item_attrs` and `visible_parent_map` regressions.

**Comment by compiler-errors** [comment]
Bumping this again: #99819 shows that #99698 is the culprit for the regression. I can revert the original PR if needed.

**Pull request merged**
