### PR TITLE
Draw vertical lines correctly in compiler error messages

### LINKED ISSUE #66552: Account for unicode char width when calculating vertical label lines
In [ui/terminal-width/non-whitespace-trimming-unicode.stderr](https://github.com/rust-lang/rust/blob/master/src/test/ui/terminal-width/non-whitespace-trimming-unicode.stderr) we account for the visible char width when calculating the label and span positions, but we do not do so for the vertical bar tying them together, causing the following output:

```
error[E0308]: mismatched types
  --> $DIR/non-whitespace-trimming-unicode.rs:4:415
   |
LL | ...♬♭♮♯♰♱♲♳♴♵♶♷♸♹♺♻♼♽♾♿⚀⚁⚂⚃⚄⚅⚆⚈⚉4"; let _: () = 42;  let _: &str = "🦀☀☁☂☃☄★☆☇☈☉☊☋☌☍☎☏☐☑☒☓  ☖☗☘☙☚☛☜☝☞☟☠☡☢☣☤☥☦☧☨☩☪☫☬☭☮☯☰☱☲☳☴☵☶☷☸☹☺☻☼☽☾☿♀♁♂♃...
   |                                             --   ^^ expected (), found integer
   |                                                      |
   |                                             expected due to this
   |
   = note: expected type `()`
              found type `{integer}`

error: aborting due to previous error
```

where it should be

```
error[E0308]: mismatched types
  --> $DIR/non-whitespace-trimming-unicode.rs:4:415
   |
LL | ...♬♭♮♯♰♱♲♳♴♵♶♷♸♹♺♻♼♽♾♿⚀⚁⚂⚃⚄⚅⚆⚈⚉4"; let _: () = 42;  let _: &str = "🦀☀☁☂☃☄★☆☇☈☉☊☋☌☍☎☏☐☑☒☓  ☖☗☘☙☚☛☜☝☞☟☠☡☢☣☤☥☦☧☨☩☪☫☬☭☮☯☰☱☲☳☴☵☶☷☸☹☺☻☼☽☾☿♀♁♂♃...
   |                                             --   ^^ expected (), found integer
   |                                             |
   |                                             expected due to this
   |
   = note: expected type `()`
              found type `{integer}`

error: aborting due to previous error
```

(Found during https://github.com/rust-lang/rust/pull/66539/)

### PR DESCRIPTION
**Pull request by TheSamsa**
... with multiline annotations correctly when non-1space unicode characters are to the left

For this we use the correct calculation of the 'left' identation

closes #66552

### CODE REVIEW

**Comment by estebank** [comment]
Can you rebase against latest master and rerun `./x.py test src/test/ui --stage 1 --bless`?

**Comment by TheSamsa** [comment]
of course, as soon as get home today

**Comment by TheSamsa** [comment]
I am not sure why it failed in bors build, but I rebased again as before

**Pull request merged**
