### PR TITLE
PartialEq and PartialOrd between IpAddr and Ipv[46]Addr.

### PR DESCRIPTION
**Pull request by clarfonthey**
PartialEq was rather useful, so, I figured that I'd implement it. I added PartialOrd for good measure.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me, thanks for the PR!

@rfcbot fcp merge

**Comment by lfairy** [comment]
Could this lead to confusion down the line?

[IPv4 addresses can be mapped into IPv6 ones](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses), and so a user might expect e.g. `Ipv4Addr(192.0.2.128) == Ipv6Addr(::ffff:192.0.2.128)` to evaluate to `true`.

**Comment by clarcharr** [comment]
@lfairy that doesn't match the current implementation of `PartialEq` for `IpAddr` though. that sounds more like a fuzzy-matching than an equality comparison.

I tried coding a version of that type of match and I got: https://is.gd/6Yzorg

**Comment by lfairy** [comment]
@clarcharr My point isn't that fuzzy matching is a good idea (it probably isn't), but that a user may presume that it works that way. To someone who works on dual-stack IPv4/IPv6 code, the idea that `Ipv4Addr(192.0.2.128) == Ipv6Addr(::ffff:192.0.2.128)` may be as "obvious" to them, as the addresses being *not* equal is "obvious" to us.

**Comment by clarcharr** [comment]
@lfairy I feel like that's mostly a documentation change, though. it makes sense to me to document it if there is any fuzzy, inexact equality, but if it's just pure equality, I don't feel like that requires any documentation. right now that expression will be a compiler error

**Comment by sfackler** [comment]
@brson @BurntSushi speak now or forever hold your peace

@bors r+

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault https://github.com/rust-lang/rust/issues/38878

**Comment by alexcrichton** [comment]
@bors: retry

* network timeout to github

**Comment by KalitaAlexey** [comment]
@alexcrichton,
Can't we make a bot try to download it multiple times? For example three attempts.

**Comment by clarcharr** [comment]
@KalitaAlexey I think that that issue is Appveyor's, not Rust's

**Comment by alexcrichton** [comment]
@KalitaAlexey perhaps! I know just about as much as you probably do about AppVeyor, and PRs are always welcome!

**Comment by alexcrichton** [comment]
@bors: retry

* good ol' linker segfaults on OSX #38878

**Comment by alexcrichton** [comment]
@bors: retry

* OSX linker segfaulted #38878

**Pull request merged**
