### PR TITLE
Stabilize Unsafe Pointer Methods

### LINKED ISSUE #43941: Tracking issue for Unsafe Pointer Methods reform
This is a tracking issue for https://github.com/rust-lang/rfcs/pull/1966

@Gankro mind filling in this issue with a checklist of work items?

### PR DESCRIPTION
**Pull request by tinaun**
also minor doc fixes.

Closes #43941

### CODE REVIEW

**Comment by ArazAbishov** [comment]
Ping from triage @Kimundi :) Did you have a chance to take a look on this PR?

**Comment by shepmaster** [comment]
Ping from triage @rust-lang/libs ! We haven't heard from @Kimundi in a while, would you assign a new reviewer?

**Comment by alexcrichton** [comment]
Thanks for the PR @tinaun and sorry for the delay! It looks like there's a tidy error on travis but other than that looks good to me, I can r+ once the error is fixed up

**Comment by tinaun** [comment]
unless travis finds anything else this should be good

**Pull request merged**
