### PR TITLE
Add more tracing instrumentation

### PR DESCRIPTION
**Pull request by oli-obk**
I changed or added all this while working on a branch and pulled it out so we can merge it on its own.

### CODE REVIEW

**Comment by jackh726** [comment]
r=me with CI green

r? @jackh726

**Comment by jackh726** [comment]
@bors p=1

This is prone to bitrot.

**Comment by jackh726** [comment]
@bors rollup=never

Same reason

**Comment by oli-obk** [comment]
Uhhhh... why does instrumentation affect release builds?? I'll go through all attributes in this PR and check them again

**Comment by oli-obk** [comment]
Ok found it. The instrument attribute will still generate a wrapper function, even if the level is statically rejected. I will open a PR to tracing.

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rust/pull/89363 shows a path to fix this regression.

@rustbot label: +perf-regression-triaged

**Pull request merged**
