### PR TITLE
rustdoc: add an --edition flag to compile docs/doctests with a certain edition

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
To correspond with the 2018 edition, this adds a (currently unstable) `--edition` flag to rustdoc that makes it compile crates and doctests with the given edition. Once this lands, Cargo should be updated to pass this flag when the edition configuration option is given.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Once CI fixed, r=me.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/360464190). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
The job exceeded the maximum time limit for jobs, and has been terminated.
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/360464190). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
The job exceeded the maximum time limit for jobs, and has been terminated.
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by kennytm** [comment]
@bors retry 

3-hour timeout with `x86_64-gnu-incremental`.

**Comment by wigy-opensource-developer** [comment]
What is missing to get this --edition flag onto stable? 1 year later I still need to use edition2018 on doctests in a crate that has edition="2018" in its Cargo.toml

**Comment by QuietMisdreavus** [comment]
This flag was stabilized alongside the 2018 edition in https://github.com/rust-lang/rust/pull/54057. Cargo was passing it to rustdoc based on the Cargo.toml even earlier, starting in https://github.com/rust-lang/cargo/pull/5299. What problems are you having?

**Comment by wigy-opensource-developer** [comment]
I have a doctest with

```rust
/// ```
/// # use crate::SomeStruct;
/// let s= SomeStruct::new();
/// ```
```

which did not find SomeStruct without adding the edition2018 flag explicitly to each doctest with a `use crate::`. So this should work without the flag since 1.32 latest?

**Comment by QuietMisdreavus** [comment]
Is that the entire doctest? Where is `SomeStruct` defined? Doctests are compiled as separate standalone binaries that link to their containing crate, so that exact example shouldn't work in either case. What error are you getting?

**Comment by wigy-opensource-developer** [comment]
I have compiled this minimal example, please run it with `cargo test`:

```rust
#![allow(dead_code)]

struct SomeStruct {}

impl SomeStruct {
    /// Always returns true
    ///
    /// # Example
    ///
    /// ```edition2018
    /// # use crate::SomeStruct;
    /// let s = SomeStruct {};
    /// assert!(s.foo());
    /// ```
    fn foo(&self) -> bool {
        true
    }
}

fn main() {
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=37ebbb961c8e0f5cd494f2122ed48d14)

Works fine without any errors. If I remove edition2018 from line 10 though, it fails with

```
error[E0432]: unresolved import `crate::SomeStruct`
 --> src/lib.rs:11:5
  |
3 | use crate::SomeStruct;
  |     ^^^^^^^^^^^^^^^^^ no `SomeStruct` in the root
```

**Comment by QuietMisdreavus** [comment]
Adding just `edition2018` to the doctest actually causes the test to be ignored. Using the proper `rust,edition2018` marker causes rustdoc to give the proper output:

```console
$ rustdoc +stable --test f.rs --extern f=libf.rlib

running 1 test
test f.rs - SomeStruct::foo (line 10) ... FAILED

failures:

---- f.rs - SomeStruct::foo (line 10) stdout ----
error[E0432]: unresolved import `crate::SomeStruct`
 --> f.rs:11:5
  |
4 | use crate::SomeStruct;
  |     ^^^^^^^^^^^^^^^^^ no `SomeStruct` in the root

thread 'f.rs - SomeStruct::foo (line 10)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    f.rs - SomeStruct::foo (line 10)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

Note that this is the same as taking the marker off the doctest and compiling with `--edition=2018` passed directly to rustdoc:

```console
$ rustdoc +stable --test f.rs --extern f=libf.rlib --edition=2018

running 1 test
test f.rs - SomeStruct::foo (line 10) ... FAILED

failures:

---- f.rs - SomeStruct::foo (line 10) stdout ----
error[E0432]: unresolved import `crate::SomeStruct`
 --> f.rs:11:5
  |
4 | use crate::SomeStruct;
  |     ^^^^^^^^^^^^^^^^^ no `SomeStruct` in the root

thread 'f.rs - SomeStruct::foo (line 10)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    f.rs - SomeStruct::foo (line 10)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

For completeness, here is the output i received with your original sample:

```console
$ rustdoc +stable --test f.rs --extern f=libf.rlib

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by QuietMisdreavus** [comment]
The reason the test fails anyway is because the path `crate::SomeStruct` is not a valid path within that doctest - it's a separate crate, and `SomeStruct` is not declared within that "crate". You have to use the name of your original crate to properly reference `SomeStruct`.

**Comment by wigy-opensource-developer** [comment]
Wow, that was a big oversight from me. Thanks for helping out. Is there a way to reduce sensitivity of test code to crate renames? I tried `super::` without success, and it feels wrong to copy-paste the crate name all around its own crate.

**Comment by QuietMisdreavus** [comment]
Not that i know of - since the doctests are meant to be example code listed in documentation, it fits that they would need to use the public name for everything. (And the setup of always being compiled as a standalone binary means that no "relative" path would work, either - the items in the original crate are always treated as an external crate.)

**Pull request merged**
