### PR TITLE
Implement RFC #1260

### PR DESCRIPTION
**Pull request by bombless**

### CODE REVIEW

**Comment by bombless** [comment]
So the libsyntax/entry.rs need a little bit clean up to make those comments to be correct.
But tbh that `entry_point_type` function serve a different purpose, that is, to mark `main`-like function `#[allow(dead_code)]` and to remove `start` attribute.
But it's not really about entry point, rather, it can just remove all `start` attribute and make the dead_code lint ignore function named "main" in root namespace.
Therefore I suggest it's just improper at first place, and I'll improve it at next PR.

**Comment by bombless** [comment]
cc https://github.com/rust-lang/rust/issues/28937

**Comment by petrochenkov** [comment]
Can this RFC be reconsidered by the lang team?
This RFC adds a strange thing to the language and a special case to the compiler, and the motivation is very weak.

Also, @bombless, could you add a feature gate for this, so even if it's merged now it could be purged later?

**Comment by bombless** [comment]
Added the feature-gate and the bootstrap hit a problem.. need to fix it first.

**Comment by joshtriplett** [comment]
Why did this get closed?  I'd love to see this implemented; I have a library that would benefit from it.

**Pull request closed without merging**
