### PR TITLE
fix REGISTRY_USERNAME to reuse cache between auto and pr jobs

### PR DESCRIPTION
**Pull request by klensy**
see https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/reuse.20.28some.29.20docker.20images.20for.20pr.2Fauto.3F

### CODE REVIEW

**Comment by klensy** [comment]
```
  #8 importing cache manifest from ghcr.io/rust-lang-ci/rust-ci-cache:01e5dce032b4cb5cff218c2c014f191e067b96bc90fcb7496c728de8500b67931079f196268981fba0ecd0d2e478d77359a788fa39502030b72a3238337f5f87
  #8 inferred cache manifest type: application/vnd.oci.image.index.v1+json done
```
Looks working.

**Comment by Kobzol** [comment]
Oh wow, this really seems to help a lot (38m -> 35m for `mingw-check`, 73m -> 65m for `x86_64-gnu-llvm-18` and 52m -> 46m for `x86_64-gnu-tools`). Thanks for catching this! In hindsight, I should have made sure that the impact on CI times is not so large when I modified this... I think that it's the libgccjit build that was making the PR CI workflows so much slower.

@bors r+

**Comment by workingjubilee** [comment]
PR #132997 is having an unusually high rate of spurious MSVC CI fails, dividing out random PRs.

This one is time-sensitive in a sense anyways, so

@bors rollup=never

**Comment by workingjubilee** [comment]
rollup #132997 is having a high rate of spurious MSVC CI fails, dividing out random PRs.

This one is time-sensitive in a sense anyways, so

@bors rollup=iffy

**Comment by klensy** [comment]
Minus ~10 minutes from pull request CI https://github.com/rust-lang/rust/actions?query=is%3Asuccess+event%3Apull_request

**Comment by Kobzol** [comment]
Oh, I just remembered another reason why I did the original change, it made try jobs work in new bors =D Well, we will need to deal with that in another way, I guess.

**Pull request merged**
