### PR TITLE
Run InstSimplify before UnreachablePropagation

### PR DESCRIPTION
**Pull request by saethlin**
This is the pass ordering change I was musing about: https://github.com/rust-lang/rust/pull/122975#issuecomment-2025898699

r? @ghost

### CODE REVIEW

**Comment by saethlin** [comment]
The optimized MIR for `Result::clone`  changes from this:
```
    bb2: {
        StorageLive(_6);
        _6 = &(((*_1) as Err).0: E);
        StorageLive(_7);
        StorageLive(_8);
        _8 = &(((*_1) as Err).0: E);
        _7 = <E as clone::Clone>::clone(move _8) -> [return: bb5, unwind continue];
    }
```
To this:
```
    bb2: {
        _5 = &(((*_1) as Err).0: E);
        StorageLive(_6); 
        _6 = <E as clone::Clone>::clone(move _5) -> [return: bb5, unwind continue];
    }   
```

That is very surprising to me.

**Comment by saethlin** [comment]
Oh I see the problem. ReferencePropagation does this:
```diff
         _6 = &(((*_1) as Err).0: E);
         StorageLive(_7);
         StorageLive(_8);
-        _8 = &(*_6);
+        _8 = &(((*_1) as Err).0: E);
         _7 = <E as Clone>::clone(move _8) -> [return: bb5, unwind continue];
     }
```
Then `_6` is unused, but it has debuginfo, so SimplifyLocals won't remove it.

But if we move InstCombine before ReferencePropagation, InstCombine gets to see the reborrow and turns it into an assignment. Then SimplifyLocals considers optimizing out `_8` instead of `_6`, which it can, because `_8` has not debuginfo.

@cjgillot I only see this pattern crop up twice in `core`, but it seems worth doing something about. Do you think it's possible to get ReferencePropagation to behave the way we want here?

**Comment by cjgillot** [comment]
> Oh I see the problem. ReferencePropagation does this:
> ```diff
>          _6 = &(((*_1) as Err).0: E);
>          StorageLive(_7);
>          StorageLive(_8);
> -        _8 = &(*_6);
> +        _8 = &(((*_1) as Err).0: E);
>          _7 = <E as Clone>::clone(move _8) -> [return: bb5, unwind continue];
>      }
> ```
> Then `_6` is unused, but it has debuginfo, so SimplifyLocals won't remove it.
> 
> But if we move InstCombine before ReferencePropagation, InstCombine gets to see the reborrow and turns it into an assignment. Then SimplifyLocals considers optimizing out `_8` instead of `_6`, which it can, because `_8` has not debuginfo.
> 
> @cjgillot I only see this pattern crop up twice in `core`, but it seems worth doing something about. Do you think it's possible to get ReferencePropagation to behave the way we want here?

Reference propagation could absolutely do that transform. We'd lose some information about reborrows, but none we actually use, so that's OK.

**Comment by saethlin** [comment]
I'm going to close this because I think the action here is to not do what I was envisioning, but to improve ReferencePropagation.

**Pull request closed without merging**
