### PR TITLE
Revert "Auto merge of #57842 - gnzlbg:extract_libtest, r=gnzlbg"

### PR DESCRIPTION
**Pull request by xales**
This reverts commit 3eb4890dfe6db0279fdd3cda19f9643873ae3db9, reversing
changes made to 7a4df3b53da369110984a2b57419c05a53e33b38.

This is, as best I can tell, a clean revert of #57842. It retains some interim changes, like moving `black_box`, and otherwise brings libtest back in as it was before removal.

### CODE REVIEW

**Comment by xales** [comment]
r? @Manishearth 

cc @gnzlbg

**Comment by gnzlbg** [comment]
This LGTM. The change being reverted had many unforeseen consequences, and while there are some paths to fix those, it is unclear whether those paths are the right thing to do. After hacking on-and-off on it for a couple of weeks, this is something that we definitely want to get right, and we won't be able to do so with confidence before the next release, so reverting the change is the best we can do. 

We probably want to try to do this again in the future, and come up with a solution that fixes everything that this one broke. But when doing so we should definitely involve the clippy maintainers in the process, so that we can make sure that landing this won't break clippy in an unrecoverable way like it happened here. And if it lands and clippy breaks, we should probably prioritize a revert right away to avoid clippy from being broken for weeks on nightly.

**Comment by Manishearth** [comment]
@bors r+ p=10

high priority since we need to get this stuff through before the beta

**Comment by Manishearth** [comment]
I'll file an issue for moving libtest out that has a plan for doing this.

**Comment by RalfJung** [comment]
For the future, it would have been great to have [this comment](https://github.com/rust-lang/rust/pull/59766#issuecomment-480586326) be part of the PR description so that it gets embedded into the git history.

**Pull request merged**
