### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #102695 (Int and float inference variables are trivially copy)
 - #102847 (impl AsFd and AsRawFd for io::{Stdin, Stdout, Stderr}, not the sys versions)
 - #102856 (Only test duplicate inherent impl items in a single place)
 - #102914 (Migrate css highlight without change)
 - #102938 (Move some tests to more reasonable directories)
 - #103015 (fix a typo)
 - #103018 (More dupe word typos)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=102695,102847,102856,102914,102938,103015,103018)

### CODE REVIEW

**Comment by albertlarsan68** [comment]
One of the prs in this rollup is successfully merged outside of this rollup, wouldn't merging it a second time create problems ?

**Comment by Dylan-DPC** [comment]
Oh right didnt realise it got merged while this got retried. Thanks 
@bors r-

**Pull request closed without merging**
