### PR TITLE
macros: improve struct constructor field hygiene, fix span bug

### LINKED ISSUE #47311: Allow proc macro to initialize a private field with a def_site value
In a struct initializer expression `S { k: v }` generated by a procedural macro where the field `k` is private, it seems *both* `k` and `v` need to be spanned with call_site in order for the generated code to compile. I believe only `k` should be required to be call_site, and `v` should be allowed to be def_site or anything else.

This currently blocks a correct implementation of derive(Deserialize).

```rust
#![feature(proc_macro)]

extern crate mac;

struct S {
    unit: (),
}

fn main() {
    // Expands to `S { unit: () }`.
    mac::init_field_unit!(S unit);
}
```

```rust
#![feature(proc_macro)]

extern crate proc_macro;
use proc_macro::{TokenStream, TokenTree, TokenNode, Delimiter, Spacing, Span};

#[proc_macro]
pub fn init_field_unit(input: TokenStream) -> TokenStream {
    let mut iter = input.into_iter();
    let struct_name = iter.next().unwrap();
    let field_name = iter.next().unwrap();
    assert!(iter.next().is_none());

    // Expands to `$struct_name { $field_name: () }`.
    vec![
        struct_name,
        TokenTree {
            span: Span::call_site(),
            kind: TokenNode::Group(Delimiter::Brace, vec![
                field_name,
                TokenTree {
                    span: Span::call_site(),
                    kind: TokenNode::Op(':', Spacing::Alone),
                },
                TokenTree {
                    // Works if this is call_site, but in derive(Deserialize) I
                    // need to be able to use def_site variables here.
                    span: Span::def_site(),
                    kind: TokenNode::Group(Delimiter::Parenthesis, TokenStream::empty()),
                },
            ].into_iter().collect()),
        },
    ].into_iter().collect()
}
```

```
error[E0451]: field `unit` of struct `S` is private
  --> src/main.rs:49:5
   |
49 |     mac::init_field_unit!(S unit);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ field `unit` is private
```

@jseyfried

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #47311.
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
The issue was that we were privacy-checking fields in struct constructors/patterns using the hygiene of the span of the whole field expression, e.g. `x: 0`, not the hygiene of just the field name (the `x`).

**Comment by petrochenkov** [comment]
Some UI tests need to be updated for new spans.
r=me after that

**Comment by shepmaster** [comment]
Ping from triage, @jseyfried — will you be able to address the UI test failures sometime soon?

**Comment by jseyfried** [comment]
Yeah, weekend.
@bors r+

**Comment by Manishearth** [comment]
Might be your failure?

```
[01:34:13] failures:
[01:34:13] 
[01:34:13] ---- [pretty] run-pass/hygiene/issue-47311.rs stdout ----
[01:34:13] 	
[01:34:13] error: pretty-printed source does not typecheck
[01:34:13] status: exit code: 101
[01:34:13] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "-" "-Zno-trans" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/hygiene/issue-47311.pretty-out" "--target=x86_64-unknown-linux-gnu" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/hygiene/issue-47311.stage2-x86_64-unknown-linux-gnu.pretty.aux" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
[01:34:13] stdout:
[01:34:13] ------------------------------------------
[01:34:13] 
[01:34:13] ------------------------------------------
[01:34:13] stderr:
[01:34:13] ------------------------------------------
[01:34:13] error[E0433]: failed to resolve. Maybe a missing `extern crate m;`?
[01:34:13]   --> <anon>:21:14
[01:34:13]    |
[01:34:13] 21 |     fn f() { ::m!(S , x); }
[01:34:13]    |              ^^^ Maybe a missing `extern crate m;`?
[01:34:13] 
[01:34:13] error: aborting due to previous error
[01:34:13] 
[01:34:13] 
[01:34:13] ------------------------------------------
[01:34:13] 
[01:34:13] thread '[pretty] run-pass/hygiene/issue-47311.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2892:9
[01:34:13] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:34:13] 
[01:34:13] 
[01:34:13] failures:
[01:34:13]     [pretty] run-pass/hygiene/issue-47311.rs

```

**Comment by jseyfried** [comment]
@Manishearth Indeed, fixed.

**Pull request merged**
