### PR TITLE
Just pass in NodeId to FunctionContext::new instead of looking it up.

### LINKED ISSUE #34592: Segfault due to using return pointer directly
First reported at https://github.com/rust-lang-nursery/rustc-serialize/issues/154, it looks like the code in that issue will segfault on all platforms and isn't related to the allocator in question, it's just a bad free. It looks like the expansion of `#[derive(RustcDecodable)]` is the function that's segfaulting, specifically:

```rust
extern crate rustc_serialize;

use rustc_serialize::*;

pub struct Request {
    pub id: String,
    pub arg: String,
}

impl Decodable for Request {
    fn decode<D: Decoder>(d: &mut D) -> Result<Request, D::Error> {
        d.read_struct("Request", 2, |d| {
            Ok(Request {
                id: match d.read_struct_field("id", 0, Decodable::decode) {
                    Ok(v) => v,
                    Err(e) => return Err(e),
                },
                arg: match d.read_struct_field("arg", 1, Decodable::decode) {
                    Ok(v) => v,
                    Err(e) => return Err(e),
                },
            })
        })
    }
}
```

In this function the closure *should* detect that it has nested returns and therefore the closure should write intermediate results into a local alloca of what to return. Instead, though, no alloca is created an results are stored directly into the return pointer.

The fault looks like it happens when:

* The `decode` function is called, `read_struct` is called, then the closure is called.
* The first call to `read_struct_field` succeeds, so the string is stored in the `id` field *directly into the return pointer*
* The second call to `read_struct_field` fails, returning an error
* The compiler writes the result (`Err(D::Error)`) into the return pointer
* The compiler then attempts to free the string stored to `id`

Basically at that point it's freeing arbitrary data because the string has already been paved over. I have been unable to reproduce this with a smaller example because everything I do seems to trigger usage of an alloca for the return value (which should be happening here). Maybe someone else knows though how to trigger this with a smaller example.

In any case though this segafult happens on nightly/beta/stable, but would be very good to fix!

cc @rust-lang/compiler 

also nominating

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #34592.

### CODE REVIEW

**Comment by eddyb** [comment]
Ugh, the things we do for old trans. @bors r+

**Comment by alexcrichton** [comment]
Awesome, thanks for the fix @luqmana!

**Comment by alexcrichton** [comment]
Nominating for beta according to this comment: https://github.com/rust-lang/rust/issues/34592#issuecomment-235358766

**Comment by nikomatsakis** [comment]
Accepted for backport.

**Pull request merged**
