### PR TITLE
Don't build a broken/untested profiler runtime on mingw targets

### PR DESCRIPTION
**Pull request by Zalathar**
Context: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Why.20build.20a.20broken.2Funtested.20profiler.20runtime.20on.20mingw.3F

#75872 added `--enable-profiler` to the `x86_64-mingw` job (to cause some additional tests to run), but had to also add `//@ ignore-windows-gnu` to all of the tests that rely on the profiler runtime actually *working*, because it's broken on that target.

We can achieve a similar outcome by going through all the `//@ needs-profiler-support` tests that don't actually need to produce/run a binary, and making them use `-Zno-profiler-runtime` instead, so that they can run even in configurations that don't have the profiler runtime available. Then we can remove `--enable-profiler` from `x86_64-mingw`, and still get the same amount of testing.

This PR also removes `--enable-profiler` from the mingw dist builds, since it is broken/untested on that target. Those builds have had that flag for a very long time.

### CODE REVIEW

**Comment by Zalathar** [comment]
@mati865 mentioned that this change might require some extra manual checking, to verify that the profiler runtime in the dist builds is sufficiently broken that we can happily remove it.

There's no rush, so it's fine for this PR to sit around for a while until it's convenient for that to happen.

**Comment by nnethercote** [comment]
Looks ok to me though I am not familiar with any of these stuff. @mati865, if you could review as well that would be appreciated :)

**Comment by mati865** [comment]
Linked final binary with binutils:
```
$ cargo rustc -- -C instrument-coverage
    Updating crates.io index
  Downloaded whoami v1.2.1
  Downloaded 1 crate (11.0 KB) in 0.47s
   Compiling whoami v1.2.1
   Compiling hello v0.1.0 (D:\tmp\hello)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.39s

$ target/debug/hello.exe
bash: target/debug/hello.exe: cannot execute binary file: Exec format error`
```

LLD yields "less bad" result but since the library shipped by Rust is still miscompiled by GCC/Binutils the resulting profraw file is malformed (the binary itself works fine):
```
$ RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo llvm-cov
info: cargo-llvm-cov currently setting cfg(coverage) and cfg(coverage_nightly); you can opt-out it by passing --no-cfg-coverage and --no-cfg-coverage-nightly
   Compiling whoami v1.2.1
   Compiling hello v0.1.0 (D:\tmp\hello)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.58s
     Running unittests src\main.rs (target\llvm-cov-target\debug\deps\hello-637c13bc18a191d0.exe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

warning: D:\tmp\hello\target\llvm-cov-target\hello-18720-12256372789117787786_0.profraw: malformed instrumentation profile data: function name is empty
error: no profile can be merged
error: failed to merge profile data: process didn't exit successfully: `'C:\Users\mateusz\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\bin\llvm-profdata.exe' merge -sparse -f 'D:\tmp\hello\target\llvm-cov-target\hello-profraw-list' -o 'D:\tmp\hello\target\llvm-cov-target\hello.profdata'` (exit code: 1)
```

<details>
<summary>Some offtopic</summary>

Also noticed gnullvm targets might have regressed at some point (or this quickly created setup is not quite right which is more probable) but it doesn't matter for this PR:
```
$ cargo new --lib test_lib

$ cd test_lib/

$ PATH=~/.cargo/bin:/h/msys64/clang64/bin:$PATH cargo +stage1_gnullvm llvm-cov
info: cargo-llvm-cov currently setting cfg(coverage) and cfg(coverage_nightly); you can opt-out it by passing --no-cfg-coverage and --no-cfg-coverage-nightly
   Compiling test_lib v0.1.0 (D:\tmp\test_lib)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.32s
     Running unittests src\lib.rs (target\llvm-cov-target\debug\deps\test_lib-3d83b996113588e9.exe)

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Filename                      Regions    Missed Regions     Cover   Functions  Missed Functions  Executed       Lines      Missed Lines     Cover    Branches   Missed Branches     Cover
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                               0                 0         -           0                 0         -           0                 0         -           0                 0         -
```

</details>

**Comment by nnethercote** [comment]
I will be away for 3 weeks, but if/when this reaches a point where @mati865 is happy with it then you have my r+.

**Comment by mati865** [comment]
Sorry if it's not obvious enough but I have confirmed the profiler library shipped with Rust is hopelessly broken for this target and there is no point in shipping it.

**Comment by Zalathar** [comment]
Whoops, I had forgotten about this.

Rebased to account for #124175, which moved the job definitions out of `ci.yml` and into `jobs.yml`.

**Comment by Zalathar** [comment]
While doing the rebase I also noticed an unrelated bug in `tests/ui/instrument-coverage/coverage-options.rs`: the test file has header directives that refer to revision `[mcdc]`, but that revision wasn't declared in the revisions line. So I added a drive-by fix for that as well.

(I'm familiar with that test from #123409, so I can vouch for the fact that adding this revision is correct.)

**Comment by Zalathar** [comment]
@nnethercote According to @mati865 https://github.com/rust-lang/rust/pull/122613#issuecomment-2018984620 the shipped profiler is hopelessly broken on mingw, so we should be able to move forward with removing it.

**Comment by nnethercote** [comment]
Repeating my comment from above:

> if/when this reaches a point where @mati865 is happy with it then you have my r+.

:)

**Review by mati865 — APPROVED** [review]

**Comment by Zalathar** [comment]
> Repeating my comment from above:
> 
> > if/when this reaches a point where @mati865 is happy with it then you have my r+.
> 
> :)

I don't understand what you mean by this.

**Comment by nnethercote** [comment]
@mati865's last comment was this:

> Sorry if it's not obvious enough but I have confirmed the profiler library shipped with Rust is hopelessly broken for this target and there is no point in shipping it.

It wasn't clear to me if this was an approval or not. But @mati865 has now given an explicit approval, so:

@bors r+

**Comment by matthiaskrgr** [comment]
@bors r- 
https://github.com/rust-lang/rust/pull/126412#issuecomment-2166591685

**Comment by Zalathar** [comment]
OK, I think I see what's happening.

Because I removed `//@ needs-profiler-runtime`, this test is now running on jobs that weren't running it before, which is expected.

On `x86_64-gnu-nopt`, the lines expected by filecheck appear in the wrong order, so the check fails. They appear to be in the wrong order on other jobs as well, but this is masked by the presence of multiple CGUs, allowing filecheck to find and match the lines in order from different CGUs.

It should be fine to just change `CHECK:` to `CHECK-DAG:` so that filecheck will accept the lines in either order, because the order isn't actually significant.

**Comment by Zalathar** [comment]
I've pushed a fix, but I'm waiting for #114917 to confirm that the fix actually works.

**Comment by Zalathar** [comment]
The fixed version of `tests/codegen/instrument-coverage/instrument-coverage.rs` has been confirmed to work on `x86_64-gnu-nopt`.

Other than that and a rebase, no changes.

@rustbot ready

**Comment by nnethercote** [comment]
Fire when ready!

@bors delegate=Zalathar

**Pull request merged**
