### PR TITLE
Fix dead code lint for functions using impl Trait

### LINKED ISSUE #54754: No warning for unused function using `impl Trait` on beta and nightly
The following code only warns that `f` is unused on stable, not on beta or nightly:

```rust
trait Trait {}
impl<T> Trait for T {}

fn f() -> impl Trait {}
```

(apologies if this is a duplicate, but a quick search didn't turn anything up)

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes https://github.com/rust-lang/rust/issues/54754

This is a minimal fix that doesn't add any new queries or touches unnecessary code. Please nominate for beta backport if wanted.

### CODE REVIEW

**Comment by oli-obk** [comment]
You need to update a bunch of other tests' stderr files, too.

**Comment by jonas-schievink** [comment]
@oli-obk Ah I see. I wasn't able to run the full test suite because I messed up the LLVM build. Should be fixed now, though.

**Comment by jonas-schievink** [comment]
@oli-obk Is this what you had in mind? Looks like there's only 1 case where the unused function should have been called, I've moved all other tests to `ui` and made them `compile-pass` tests.

**Comment by oli-obk** [comment]
Perfect. Thanks!

@bors r+

**Comment by pnkfelix** [comment]
discussed at T-compiler weekly meeting. approved for beta backport.

**Comment by jonas-schievink** [comment]
Actual error:

    [01:07:28] thread 'main' panicked at 'failed to download openssl source: exit code: 6', bootstrap/native.rs:621:17

(spurious)

Also, is that builder building LLVM twice?

**Comment by nagisa** [comment]
@bors retry

as requested on IRC.

**Pull request merged**
