### PR TITLE
Only run check-linkchecker when actually building docs

### PR DESCRIPTION
**Pull request by infinity0**
Otherwise the build fails, when running tests but not building docs, e.g.:
https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=ppc64el&ver=1.17.0%2Bdfsg2-3&stamp=1497403375&raw=0

### CODE REVIEW

**Comment by aidanhs** [comment]
Thanks for the PR @infinity0, we'll make sure @alexcrichton or another reviewer gets to this soon!

**Comment by alexcrichton** [comment]
Thanks @infinity0! It looks like there's a stray jemalloc update here, but otherwise looks good to me! 

If you're feeling extra intrepid you could add a test at the end of `src/bootstrap/step.rs` as well which asserts that this step doesn't show up in the final list of steps for `--disable-docs` builds.

**Comment by infinity0** [comment]
Whoops, fixed the jemalloc thing. I thought that test was too minor to bother with, but instead I've done a more sophisticated test to check that none of the steps' dependencies contain "doc-" or "default:doc", this will catch any future targets too.

The test commit goes before the fix commit so you can check that it does indeed fail when the fix is not applied. Also, I'm not sure what Rust naming conventions are so I called it `build_` but of course would be happy to rename it.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
