### PR TITLE
regenerate libcore/char_private.rs

### PR DESCRIPTION
**Pull request by zackmdavis**
(filed separately from the work in #45569, because of this matter of the updated Unicode data; see also #45567)

char_private.rs is generated programmatically by char_private.py, using data retrieved from the Unicode Consortium's website.

The motivation here was to make `is_printable` crate-visible (with `pub(crate)`), but it would seem that the Unicode data has changed slightly since char_private.rs was last generated.

### CODE REVIEW

**Comment by estebank** [comment]
Sorry for the wide spam, @rust-lang/core, @rust-lang/libs, @rust-lang/docs not sure who to ask this.

This change will update Rust's unicode support from 9 to [10](http://www.unicode.org/versions/Unicode10.0.0/), IIUC. Is this something that can be updated matter of fact without an RFC? I'm inclined to r+ it, maybe changing the PR's name beforehand to make sure it's not lost in the shuffle in the corresponding release's notes.

**Comment by kennytm** [comment]
@estebank We *should* be already using Unicode 10 (#42999)... 

Similar previous PRs (e.g. upgrade entirely to Unicode 9 #34599) don't have RFCs, but they don't pass as a single-handed r+ either. 

However, the `char_private` module only defines the `is_printable` function, which in turn is only used in [`char::escape_debug`](https://doc.rust-lang.org/std/primitive.char.html#method.escape_debug) that has no stability guarantee on the Unicode version. So I guess it is fine to merge without deep inspection.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks for the extra info @kennytm!

**Comment by kennytm** [comment]
(I've removed the <kbd>relnotes</kbd> tag since it only affects `escape_debug` which doesn't seem to be a big point to mention.)

**Comment by Mark-Simulacrum** [comment]
I disagree - I think this change is worth mentioning in the compatibility section of the relnotes.

**Pull request merged**
