### PR TITLE
VecDeque: Use power of two capacity even for zero sized types

### LINKED ISSUE #28488: `VecDeque::push_back(())` does not work correctly.
http://is.gd/NY4tCl

```
use std::collections::VecDeque;
 
fn main() {
    let mut v = VecDeque::new();
    v.push_back(());                                                                                                         
    assert!(v.len() > 0 );   
}

thread '<main>' panicked at 'assertion failed: v.len() > 0', <anon>:6
```

### PR DESCRIPTION
**Pull request by bluss**
VecDeque: Use power of two capacity even for zero sized types

VecDeque depends on using a power of two capacity. Use the largest
possible power of two capacity for ZSTs.

Fixes #28488

### CODE REVIEW

**Comment by bluss** [comment]
WIP -- still running tests, they probably don't compile..

**Comment by Gankro** [comment]
r=me when you get that to compile

**Comment by bluss** [comment]
It compiled with one fix.

**Comment by bluss** [comment]
beta nominating as bug fix

**Comment by eddyb** [comment]
We don't have a "is power of 2" method? IIRC `x & (x - 1) == 0` works.

**Comment by bluss** [comment]
@eddyb Oh, we have is_power_of_two(). Didn't know that. It uses your method.

**Comment by bluss** [comment]
Updated to use is_power_of_two

**Comment by bluss** [comment]
I'm not sure why the debuginfo test failed on android, but I think it's safe to retry.

@bors retry

**Comment by alexcrichton** [comment]
The libs team decided to accept this for a backport to beta

**Comment by bluss** [comment]
@alexcrichton Has a stable patch / 1.3.1 been considered? Maybe this is not so serious after all(?). I don't know, but I like fixing bugs.

**Comment by alexcrichton** [comment]
No, but this doesn't seem serious enough to warrant the *first patch release in Rust ever*.

**Comment by bluss** [comment]
Well maybe it's the worst regression in stable rust ever?

**Pull request merged**
