### PR TITLE
rustc_codegen_llvm: remove some debuginfo cruft.

### PR DESCRIPTION
**Pull request by eddyb**
(The second commit passes tests locally but might not on older LLVM versions)

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
Travis CI passed tests and it uses LLVM 3.9 AFAIK, so perhaps the bug isn't in 3.9?
cc @michaelwoerister @alexcrichton

**Comment by alexcrichton** [comment]
Sure! May have been in 3.7? If it passes it passes :)

**Comment by michaelwoerister** [comment]
This is awesome `:)`

You can r=me unless you specifically want @nikomatsakis to take a look at it.

**Pull request merged**
