### PR TITLE
rustbuild: Assert directory creation succeeds

### PR DESCRIPTION
**Pull request by alexcrichton**
I've been seeing failures on the bots when building jemalloc and my assumption
is that it's because cwd isn't created. That may be possible if this
`create_dir_all` call change in this commit fails, in which case we ignore the
error.

This commit updates the location to call `create_dir_racy` which handles
concurrent invocations, as multiple build scripts may be trying to create the
`native` dir.

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @petrochenkov 

another instance of this failure happened at https://travis-ci.org/rust-lang/rust/jobs/208686112 and I'm hoping this'll fix it.

Unfortunately I can't reproduce locally so this is just a guess to a fix.

**Comment by brson** [comment]
@bors r+

Awesome function.

**Comment by petrochenkov** [comment]
My best guess is that maybe several processes try to create subdirectories in the `native` directory simultaneously. E.g. one job tries to create `native/libbacktrace` while another tries to create `native/jemalloc` and one of them fails somehow. So, `create_dir_racy` may help, or `native` could be pre-created in advance...

**Comment by alexcrichton** [comment]
@petrochenkov yes that's my belief as well. I didn't find a great spot to create the dir ahead of time so I just left it here

**Comment by alexcrichton** [comment]
@bors: p=1

I think this is also causing https://github.com/rust-lang/rust/issues/40358

**Comment by alexcrichton** [comment]
@bors: retry

* build timeout

**Pull request merged**
