### PR TITLE
Enable zlib for NetBSD

### PR DESCRIPTION
**Pull request by mati865**
NetBSD Docker dist job passed locally.

### CODE REVIEW

**Comment by nielx** [comment]
I am wondering whether we shouldn't add libz to all cross-compiled builds for all platforms by default, now that we know that that the LLVM option is enabled by default? 

This will increase the likelihood that cross-compiling rustc will work on any platform. 

Do we know platforms that do not ship libz? windows perhaps?

**Comment by Mark-Simulacrum** [comment]
I agree that option 2 seems like the best way, and we should surface the option in config.toml (probably in a target-specific section).

**Comment by Mark-Simulacrum** [comment]
That said, I'm going to r+ this since it does seem like a net-improvement to me for the time being.

@bors r+

**Comment by mati865** [comment]
Rebased.

**Comment by mati865** [comment]
This is going to fail because of https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/MSVC.20on.20CI.20has.20broke

**Pull request merged**
