### PR TITLE
resolve: change most backwards incompatible ambiguity errors to `legacy_imports` warnings

### LINKED ISSUE #38176: `use super::*` importing private members from parent module
Reproduction script: https://is.gd/qvbF0b

This code compiles on stable and beta but fails to compile on nightly. `use super::*` previously did not include private members. On nightly it is reported that "`Foo` is ambiguous"

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #38176.
r? @nrc or @nikomatsakis

### CODE REVIEW

**Comment by alexcrichton** [comment]
ping @nrc / @nikomatsakis, would be great to get this in before beta!

**Comment by alexcrichton** [comment]
Nominating for beta to ensure we don't forget about this if it misses the beta branch. Note that this should only go into 1.15.0 beta, not the current (as of this writing) 1.14.0 beta.

**Comment by nikomatsakis** [comment]
Marking as beta-accepted. Patch is kind of medium-ish, but this is a serious regression, and mostly the patch is converting errors into lints. cc @rust-lang/compiler

**Pull request merged**
