### PR TITLE
Don't display `mut` in arguments for functions documentation

### LINKED ISSUE #81289: rustdoc documents `mut self` as `mut self: Self`
Rustdoc on [nightly documents][1] methods have signature of `fn(mut self)` as `fn(mut self: Self)` while it only has to document it as `fn(self)`.
image

On [rustdoc stable][2], things are normal: 
image

### Meta

`rustc --version --verbose`: Version 1.49.0 (e1884a8e3 2020-12-29)

[1]: https://doc.rust-lang.org/nightly/std/io/struct.BufWriter.html#method.into_inner
[2]: https://doc.rust-lang.org/1.49.0/std/io/struct.BufWriter.html#method.into_inner

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
This mostly touches `rustc_hir_pretty`, I don't know who should review this.

Fixes #81289.
r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
@LeSeulArtichaut it looks the change might not have worked, the test is failing.

This looks good to me, but I know petrochenkov wants to use rustc_hir_pretty as little as possible, so

r? @petrochenkov 

Note that the alternative here is to rewrite half of rustc_hir_pretty (i.e. revert https://github.com/rust-lang/rust/pull/80799), so I would prefer not to do that.

**Comment by LeSeulArtichaut** [comment]
> @LeSeulArtichaut it looks the change might not have worked, the test is failing.

This is actually really dumb: I think the test is failing because of the source link to the file which contains `mut` 😆
I checked manually (after 53 minutes of compilation), and no `mut` is present in the function arguments

**Comment by petrochenkov** [comment]
I suggest reverting https://github.com/rust-lang/rust/pull/80799 instead and not using HIR pretty-printing in rustdoc (and perhaps simplifying `name_from_pat` to print less stuff).

The goal of HIR pretty-printing is to print something suitable for debugging, the goal of rustdoc is printing argument names in a way presentable to users.

**Comment by camelid** [comment]
@LeSeulArtichaut do you want to be the one to do the revert?

**Comment by LeSeulArtichaut** [comment]
Sure.

**Pull request closed without merging**
