### PR TITLE
[work in progress] Upgrade to musl 1.2.3

### PR DESCRIPTION
**Pull request by wesleywiser**
This PR is a companion PR to https://github.com/rust-lang/libc/pull/2088 which updates `libc`'s bindings to support musl 1.2.3. In this PR, we begin building & distributing musl targets with 1.2.3 and update the `libc` dependency to point to the new version (as the other PR has not yet been merged, I've pointed `libc` at my fork for now).

With this PR, we should be able to do a crater run of the musl upgrade. 

r? @ghost

### CODE REVIEW

**Comment by wesleywiser** [comment]
Starting with a small crater run just to make sure things are working correctly...

@craterbot run mode=build-and-test crates=top-100 name=musl_upgrade_test start=try#8dae881ac166f8debe04e17604ebbe2ab47083fd+target=i686-unknown-linux-musl end=try#e392e7b50913d5cb6e2c08d70cdeb72e56d289f9+target=i686-unknown-linux-musl+patch=libc=https://github.com/wesleywiser/libc=musl-1.2

**Comment by Mark-Simulacrum** [comment]
@craterbot abort

See https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/crater.20run.20for.20musl.20target

**Comment by wesleywiser** [comment]
Ok, let's try this again:

@craterbot run mode=build-and-test crates=top-100 name=musl_upgrade_test start=try#8dae881ac166f8debe04e17604ebbe2ab47083fd+target=i686-unknown-linux-musl end=try#e392e7b50913d5cb6e2c08d70cdeb72e56d289f9+target=i686-unknown-linux-musl+patch=libc=https://github.com/wesleywiser/libc=musl-1.2

**Comment by wesleywiser** [comment]
The single root failure detected is a result of `timespec` now containing private padding fields. I suspect we'll see similar issues in the wider crates ecosystem. Since this does prove that crater can now run `i686-unknown-linux-musl` correctly, I'll kick off the full run:

@craterbot run mode=build-and-test name=musl_upgrade_1_2 start=try#8dae881ac166f8debe04e17604ebbe2ab47083fd+target=i686-unknown-linux-musl end=try#e392e7b50913d5cb6e2c08d70cdeb72e56d289f9+target=i686-unknown-linux-musl+patch=libc=https://github.com/wesleywiser/libc=musl-1.2

**Comment by wesleywiser** [comment]
@craterbot run mode=build-and-test name=musl_upgrade_1_2 start=try#4fcdf349db8b40d1a4822a4ed58583c19dfb1cd3+target=i686-unknown-linux-musl end=try#26497e971afa70d947c89fcca5fff8e557e471b3+target=i686-unknown-linux-musl+patch=libc=https://github.com/wesleywiser/libc=musl-1.2

**Comment by wesleywiser** [comment]
@craterbot run mode=build-and-test name=musl_upgrade_1_2_take2 start=try#4fcdf349db8b40d1a4822a4ed58583c19dfb1cd3+target=i686-unknown-linux-musl end=try#26497e971afa70d947c89fcca5fff8e557e471b3+target=i686-unknown-linux-musl+patch=libc=https://github.com/wesleywiser/libc=musl-1.2

**Comment by wesleywiser** [comment]
@craterbot run mode=build-and-test name=musl_upgrade_1_2_take4 start=try#fc4ba03ef77ca5018fb78a097d3b924d30f15bfc+target=i686-unknown-linux-musl end=try#04c11acd339209418a0f193687aa4190c1b645cf+target=i686-unknown-linux-musl+patch=libc=https://github.com/wesleywiser/libc=musl-1.2

**Comment by jyn514** [comment]
@wesleywiser it looks like you continued this work in https://github.com/rust-lang/rust/pull/107129, so I'm going to close this PR - feel free to reopen if they're different in some way I haven't spotted.

**Pull request closed without merging**
