### PR TITLE
Allow trait method paths to satisfy const Fn bounds

### PR DESCRIPTION
**Pull request by fee1-dead**
r? @oli-obk

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
r=me unless you want a specific review from oli or something

**Comment by rylev** [comment]
Seems to be a whole lot of noise unfortunately... Reversed [here](https://github.com/rust-lang/rust/pull/106268#issuecomment-1367860862).

@rustbot label +perf-regression-triaged

**Pull request merged**
