### PR TITLE
[do not merge] Test performance impact of accessing the HIR map through a query

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 1b4896fdaa41877c2f40fdc6ebf7bc601ed919dc

**Comment by michaelwoerister** [comment]
This will be interesting. However, before you do any major work here, @Zoxc, the @rust-lang/compiler team should come up with a proper plan/architecture for end-to-end queries.

**Comment by Zoxc** [comment]
@rust-timer build 51828fff69562c203097c6c6e451a003ab74148c

**Comment by Zoxc** [comment]
@rust-timer build ac29eb5483d28d9e61b691331c9e7eb9ebad501c

**Comment by TimNN** [comment]
Ping from triage @Zoxc: What is the status of this PR?

**Pull request closed without merging**
