### PR TITLE
In `LexicalResolver`, don't construct graph unless necessary.

### PR DESCRIPTION
**Pull request by nnethercote**
A small but easy perf win.

r? @jackh726

### CODE REVIEW

**Comment by lqd** [comment]
r=me with the expected perf improvement

**Comment by nnethercote** [comment]
Weird results. It's easier to focus on just the `full check` measurements:
- [#110520](https://perf.rust-lang.org/compare.html?start=da481403e7e3c91878ef8fe3099c04dbb862a145&end=d82713eb111ca3622504573d2d910ff6a7a2cd35&stat=instructions%3Au&opt=false&doc=false&debug=false&incrFull=false&incrUnchanged=false&incrPatched=false&nonRelevant=true).
- [#110527](https://perf.rust-lang.org/compare.html?start=c7815840793b980d0aae7d5a2f5d9bb1fd6c0d1e&end=6afef3bc826bb1dbbb61b0357520d5233e630105&stat=instructions%3Au&debug=false&opt=false&doc=false&incrUnchanged=false&incrPatched=false&incrFull=false&nonRelevant=true)

The best results are better in #110527, e.g. `unused-warnings` improves from -0.58% to -0.72, and `libc-0.2.124` improves from -0.11% to -0.22%. Which aligns with what I saw locally, and makes logical sense: this PR is simply doing less work. But the results for #110520 are more uniformly green.

**Comment by nnethercote** [comment]
I will try another perf run, to see what happens.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Latest results are better, showing that the supposed sub-significance-threshold reds were just noise. I think it's reasonable to merge this now.

@bors r=lqd

**Pull request merged**
