### PR TITLE
[experiment] How expensive are doc comments?

### PR DESCRIPTION
**Pull request by petrochenkov**
What happens if they are interpreted as usual comments and not converted to attributes, and not stored in AST/HIR?

(This cannot be checked at lexer level, unfortunately, since some popular crates (`rayon`) rely on `/** text */` being matched by `#[$meta]` in macros.)

r? @ghost

### CODE REVIEW

**Comment by Centril** [comment]
@rust-timer build 87205d76d6934459076fbd079fe2791be5698028

**Comment by Centril** [comment]
Turns out they are pretty expensive...

**Comment by petrochenkov** [comment]
I had some optimization ideas for doc comments (https://github.com/rust-lang/rust/issues/60935, https://github.com/rust-lang/rust/issues/60936) and wanted to check how much effect they can have.

**Comment by nnethercote** [comment]
Note that my experiments indicate that the main part of the cost is decoding the attributes from metadata.

**Pull request closed without merging**
