### PR TITLE
Stable backport of #73613

### PR DESCRIPTION
**Pull request by wesleywiser**
This is the backport of #73613 to stable. 

r? @ghost

cc @Mark-Simulacrum 

In addition the tests added in the original PR passing, I've also confirmed that the test case in #74739 works correctly.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=1000 rollup=never

Thanks! I'll invalidate dev-static once this lands so we can get artifacts for testing.

**Comment by Mark-Simulacrum** [comment]
Well, that's not good.

```
2020-07-25T15:49:09.9502009Z error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
2020-07-25T15:49:13.2340695Z error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
```

cc @mati865

**Comment by mati865** [comment]
I won't have access to any desktop until tomorrow. I think this doesn't happen on nightly right?
If so check if my msys2 PR is present on stable. I'll try be available on zulip right now.

**Comment by mati865** [comment]
The PR https://github.com/rust-lang/rust/pull/73188

**Comment by mati865** [comment]
@Mark-Simulacrum I have checked and https://github.com/rust-lang/rust/pull/73188 is not present on stable. Do you want to backport it or should I search for band-aid workaround?

**Comment by Mark-Simulacrum** [comment]
I'm fine with backporting it, will do so sometime today. Thanks!

**Pull request merged**
