### PR TITLE
Remove unneeded body class selector

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus

### CODE REVIEW

**Review by QuietMisdreavus — APPROVED** [review]
Thanks! We need this to make sure the line numbers work on docs.rs.

**Comment by talchas** [comment]
This rebroke the display of line numbers again: `:not(.source)` is not in fact the same as `body:not(.source)`.

**Comment by GuillaumeGomez** [comment]
Indeed. sending a fix soon.

**Pull request merged**
