### PR TITLE
Beta backport of #40254

### PR DESCRIPTION
**Pull request by nagisa**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

(beta backport)

**Comment by alexcrichton** [comment]
@bors: retry

* failed to upload to S3

**Comment by alexcrichton** [comment]
@bors: retry

* sccache wedged https://github.com/rust-lang/rust/issues/39003

**Comment by brson** [comment]
@alexcrichton Shouldn't this PR include a version bump since every beta publishes? Landing this will publish a beta with the same number as previously.

**Comment by alexcrichton** [comment]
@bors: retry

* ???

**Comment by nagisa** [comment]
> Shouldn't this PR include a version bump since every beta publishes?

So how is it? Seems weird and error prone to make contributors to do this if that’s true.

**Comment by alexcrichton** [comment]
Oh sorry I meant to respond to that. 

No a version bump isn't necessary. The rust-central-station supports only publishes betas if the version changes, unlike nightlies where a version is published if the revision changes.

**Comment by alexcrichton** [comment]
@bors: retry

* sccache wedged #39003

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault #38878

**Pull request merged**
