### PR TITLE
Alter `Display` for `Ipv6Addr` for IPv4-compatible addresses

### PR DESCRIPTION
**Pull request by clarfonthey**
ACP: rust-lang/libs-team#239

### CODE REVIEW

**Comment by sladyn98** [comment]
@clarfonthey You might need to fix the tests for this one.

**Comment by clarfonthey** [comment]
Yup, I should have expected there to be tests for this.

**Comment by clarfonthey** [comment]
(Seems to be another PR that failed in the rollup.)

**Comment by sladyn98** [comment]
This looks good now !

**Comment by clarfonthey** [comment]
Should this be tagged as release notes?

**Comment by ChrisDenton** [comment]
There's no harm in adding the label even if you're not certain. IMHO it does seem worth mentioning.

@rustbot label relnotes

**Pull request merged**
