### PR TITLE
Stabilize the "IP" feature (continued from #76098)

### PR DESCRIPTION
**Pull request by saethlin**
I noticed the work in https://github.com/rust-lang/rust/pull/76098 seemed abandoned, so I'm reviving it here. I'm not particularly familiar with RFC 4291 but I'm no stranger to reading IETF RFCs.

I'm not totally clear on what still needs to be done. There's a fair bit of discussion in the preceding PR, but some if it seems outdated. Over the next few days I'll try to piece together what still needs to be done, but if anyone (@KodrAus, @CDirkx, @jyn514) knows better than I please point me in the right direction.

### CODE REVIEW

**Comment by jyn514** [comment]
@saethlin this is the latest update I know of: https://github.com/rust-lang/rust/pull/76098#issuecomment-776322105. I don't know the status other than that.

**Comment by CDirkx** [comment]
I think the best way forward for this PR is to split it up into several smaller pieces:

- Document `Ipv6MulticastScope` 
- Document the stability guarantees regarding new IETF RFCs
- Possibly remove `is_unicast_link_local_strict` (https://github.com/rust-lang/rust/pull/76098#issue-475853748)
- Decide what to do about unicast site local addresses (https://github.com/rust-lang/rust/pull/76098#issuecomment-774541259)
- Possibly introduce `Ipv6UnicastScope` (https://github.com/rust-lang/rust/pull/76098#issuecomment-735019872)
- Currently `is_global` doesn't take into account some addresses designated as "not globally reachable" (https://github.com/rust-lang/rust/pull/76098#discussion_r558690082)
- Decide which IPv6 methods should take IPv4-mapped addresses into account (`is_unspecified` (https://github.com/rust-lang/rust/pull/76098#discussion_r558679462) and `is_loopback` (https://github.com/rust-lang/rust/pull/76098#discussion_r528738546) no, `is_documentation` and others yes?)
- Decide if IPv4-mapped IPv6 addresses are globally reachable (https://github.com/rust-lang/rust/pull/76098#discussion_r558690082)
- Decide the behaviour of `to_ipv4` and whether to keep `to_ipv4_mapped`
- Possibly introduce the IPv6 equivalent of `is_ietf_protocol_assignment` and `is_benchmarking`, more? (https://github.com/rust-lang/rust/pull/76098#issuecomment-761271217)

**Comment by CDirkx** [comment]
I split everything up into several issues:
- #85604 IPv6 Unicast Interface, for discussion about the `is_unicast_` methods.
- #85609 IPv4-in-IPv6 Address Support, for discussion about which `Ipv6Addr` methods should also check IPv4-mapped addresses.
- #85612 IP Utility Methods, for discussion about which utility methods should be stabilized.

**Comment by CDirkx** [comment]
Directly actionable for anyone right now:
- Add the documentation that is already present in this PR to `Ipv6MulticastScope`
- Add the documentation that is already present in this PR regarding stability guarantees and new IETF RFCs.
- Make `is_loopback` take IPv4-mapped addresses into account (so match both `::1` and `::ffff:127.0.0.1`) fixing #69772. See #85609, this seems the only IPv4-mapped change that is non-controversial.

I think anything else will require addressing the open problems listed in the issues I opened, which will require gathering evidence for the best approach and reaching a consensus. So I don't see stabilization of the entire `ip` feature possible in the near future. I think it would be better to instead break it up into smaller features like `ipv6_unicast`, `ip_global` etc. to enable stabilization piece by piece.

**Comment by crlf0710** [comment]
@saethlin Ping from triage! There's merge conflict now. Would you mind rebasing this pr?

**Comment by saethlin** [comment]
@crlf0710 I appreciate the attention. I'll get to this soon.

**Comment by JohnTitor** [comment]
Triage: Marking as `S-blocked` as we're splitting this PR into smaller ones and triaging is unnecessary until it's done.

**Comment by saethlin** [comment]
Closing this because I have precious little expertise to offer here. It looks like there are much more capable contributors about, and I have other priorities.

**Pull request closed without merging**
