### PR TITLE
Remove the `cstore` reference from Session

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR removes the `CrateStore` reference from `Session` in preparation to control all `CrateStore` access through the `tcx`. This control will later be used to either interpose a `CrateStore` wrapper for dependency tracking or forcing all `CrateStore` access to go through queries.

### CODE REVIEW

**Comment by arielb1** [comment]
```
[01:05:41]    Compiling rustc v0.0.0 (file:///checkout/src/librustc)

[01:05:47] error: unused import: `DummyCrateStore`

[01:05:47]     --> /checkout/src/librustc/session/config.rs:1954:32

[01:05:47]      |

[01:05:47] 1954 |     use middle::cstore::{self, DummyCrateStore};

[01:05:47]      |                                ^^^^^^^^^^^^^^^

[01:05:47]      |

[01:05:47] note: lint level defined here

[01:05:47]     --> /checkout/src/librustc/lib.rs:20:9

[01:05:47]      |

[01:05:47] 20   | #![deny(warnings)]

[01:05:47]      |         ^^^^^^^^

[01:05:47]      = note: #[deny(unused_imports)] implied by #[deny(warnings)]

[01:05:47] 

[01:05:47] error: unused import: `std::rc::Rc`

[01:05:47]     --> /checkout/src/librustc/session/config.rs:1960:9

[01:05:47]      |

[01:05:47] 1960 |     use std::rc::Rc;

[01:05:47]      |         ^^^^^^^^^^^

[01:05:47] 
```

@bors r-

**Comment by alexcrichton** [comment]
Note that this is also likely to conflict quite a bit with #44142, where I think a lot of the `tcx.sess.cstore -> tcx.cstore()` may no longer be necessary after that lands

**Comment by michaelwoerister** [comment]
@alexcrichton I don't mind holding off on this PR until #44142 is merged.

**Comment by alexcrichton** [comment]
@bors: r-

Ok gonna r- this until #44142 lands. I feel bad though as that's gonna be a nasty merge, so I went ahead and did it!

I rebased this commit in https://github.com/alexcrichton/rust/commit/a00804b92340879d3e15b30c4889050ce856949c and then tacked https://github.com/alexcrichton/rust/commit/e3e88cdf37d5d915c2475d668103f81922c60df3 on top which makes `CrateStore` entirely private, yay!

**Comment by michaelwoerister** [comment]
Thanks, @alexcrichton! I'll close this then in favor of #44142.

**Comment by alexcrichton** [comment]
I've reopened this as https://github.com/rust-lang/rust/pull/44420

**Pull request closed without merging**
