### PR TITLE
Identify missing item category in `impl`s

### LINKED ISSUE #40006: Poor parser error message when item category missing (assumes input is a macro)
Consider this code ([playpen](https://is.gd/AkFshR)): 

```rust
struct S;
impl S { pub hello_method(&self) { println!("Hello"); } }
fn main() { S.hello_method(); }
```

It yields this error today: 

```
rustc 1.17.0-nightly (a17e5e294 2017-02-20)
error: can't qualify macro invocation with `pub`
 --> <anon>:2:10
  |
2 | impl S { pub hello_method(&self) { println!("Hello"); } }
  |          ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation

error: expected one of `!` or `::`, found `(`
 --> <anon>:2:26
  |
2 | impl S { pub hello_method(&self) { println!("Hello"); } }
  |                          ^

error: aborting due to previous error
```

In this case, the actual error is that the user left out the keyword after the visibility to indicate which kind of item they are trying to define here.

Our parser should be able to do a better job here. At the very least, if there is no trailing `!`, then instead of assuming that the input was a macro invocation, it should instead assume it was *some* item definition that is missing its keyword.

### PR DESCRIPTION
**Pull request by estebank**
```rust
struct S;
impl S {
    pub hello_method(&self) {
        println!("Hello");
    }
}
fn main() { S.hello_method(); }
```

```rust
error: missing `fn` for method declaration
 --> file.rs:3:4
  |
3 |     pub hello_method(&self) {
  |        ^ missing `fn`
```

Fix #40006. r? @pnkfelix CC @jonathandturner @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by jonathandturner** [comment]
This seems like a step in the right direction, though the help it's giving seems confusing.  Is there any way for us to detect if hello_method is a macro?  It seems at a glance that these macro messages are distracting the user from the key issue.

**Comment by estebank** [comment]
@jonathandturner I'll see if I can find a macro with the name and output the current output, otherwise output:

```rust
error: <ERROR>
 --> file.rs:3:4
  |
3 |     pub hello_method(&self) {
  |        ^ missing `fn` here for a method declaration?
```

What do you think the error message should be for this?

**Comment by jonathandturner** [comment]
@estebank - yeah, if we can get it down to that, that'd be great.

**Comment by estebank** [comment]
@jonathandturner updated output to

```rust
error: missing `fn` for method declaration
 --> file.rs:3:4
  |
3 |     pub hello_method(&self) {
  |        ^ missing `fn`
```

It doesn't check if the parsed path is a macro name as I couldn't see a way to check the context in the parser, so I just look ahead to see if a `!` is missing and assume it was meant to be a method.

**Comment by jonathandturner** [comment]
Hmm, that sounds best as a separate PR from this one.

**Comment by estebank** [comment]
Ping.

**Comment by GuillaumeGomez** [comment]
So for me it's fine as is, so I'll r+. Thanks!

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry

* centos network issues https://github.com/rust-lang/rust/issues/40474

**Pull request merged**
