### PR TITLE
Stabilize `#[unix_sigpipe = "sig_dfl"]` on `fn main()`

### LINKED ISSUE #46016: Spurious SIGPIPES when used in typical UNIX shell pipelines
~~~~
$ cat yes.rs 
fn main() { loop { println!("y"); } }
$ rustc yes.rs && ./yes | head -n1
y
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:692:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
$ yes | head -n1
y
~~~~

This was originally filed [here](https://github.com/sfackler/cargo-tree/issues/25) but @sfackler determined the cause:

> This is due to `println!` panicking on errors: https://github.com/rust-lang/rust/blob/f1ea23e2cc72cafad1dc25a06c09ec2de8e323eb/src/libstd/io/stdio.rs#L671.
> 
> C-based programs typically just get killed off with a SIGPIPE, but Rust ignores that signal.

Note that to see the backtrace, the data being piped has to be large enough to overflow the kernel pipe buffer.

### PR DESCRIPTION
**Pull request by Enselic**
I would like to propose that we stabilize `#[unix_sigpipe = "sig_dfl"]`.
This PR does that.

By my estimation, merging this PR will close https://github.com/rust-lang/rust/issues/46016.

Tracking issue is https://github.com/rust-lang/rust/issues/97889.

# Stabilization report

The `#[unix_sigpipe = "sig_dfl"]` attribute has been available in nightly since [`nightly-2022-09-04`](https://github.com/rust-lang/rust/pull/97802#issuecomment-1235978689) (17 months).

It is being used by [rustc](https://github.com/rust-lang/rust/blob/c29082fe7dc6e902169cacbae165562a7e4a1fd6/compiler/rustc/src/main.rs#L37) and [rustdoc](https://github.com/rust-lang/rust/blob/c29082fe7dc6e902169cacbae165562a7e4a1fd6/src/tools/rustdoc/main.rs#L3) themselves, and also by third party code ([1](https://github.com/moonrepo/espresso/blob/e3f429b01bfd9a0a8956f11b1bc9120084c42d3c/crates/cli/src/main.rs#L18), [2](https://github.com/trinitronx/intro-to-rust-kvstore/blob/2c26260a837c33f193cf26cecf49279675c3a6a3/src/main.rs#L8)).

I have monitored the keyword `sigpipe` on `rust-lang/rust` during all this time, and no problems have been reported regarding the attribute. To the contrary. It's infrastructure was used to implement a [bugfix](https://github.com/rust-lang/rust/pull/101077/files) in a [backwards compatible](https://github.com/rust-lang/rust/blob/bf4de3a874753bbee3323081c8b0c133444fed2d/library/std/src/sys/pal/unix/process/process_unix.rs#L360) way.

## Summary and examples

Everything you need to know about the stabilized attribute should be documented in the reference. [PR](https://github.com/rust-lang/reference/pull/1465). [Rendered](https://github.com/Enselic/reference/blob/unix_sigpipe/src/runtime.md#the-unix_sigpipe--sig_dfl-attribute).

## Test cases

https://github.com/rust-lang/rust/tree/master/tests/ui/attributes/unix_sigpipe

## Edge cases

None that I am aware of.

Note that using `#[unix_sigpipe = "sig_dfl"]` and receiving a `SIGPIPE` means destructors will not run since the process will be immediately killed. I documented this in The Reference.

## Unresolved questions

None. See [tracking issue](https://github.com/rust-lang/rust/issues/97889).

## Worth noting

This PR does NOT stabilize any other variant of the attribute, namely `#[unix_sigpipe = "sig_ign"]` and `#[unix_sigpipe = "inherit"]`.

There are many reasons for this:

* Avoids choice paralysis between leaving `SIGPIPE` be the default (`SIG_IGN`) and explicitly setting it to `SIG_IGN` with `#[unix_sigpipe = "sig_ign"]`
* I have found no one using `#[unix_sigpipe = "sig_ign"]` nor `#[unix_sigpipe = "inherit"]` in the wild, so they are much less tested, and there seems to be no desire for them.
* Stabilizing something means committing to its existence for all eternity, so we should not stabilize attributes that are not absolutely needed.
* It leaves the door open to change `fn lang_start()` `sigpipe` arg from `u8` to `bool` ("not set" or "set to sig_dfl"), enabling better lto. Only relevant if we end up deciding not to change the default, and not adding `#[unix_sigpipe = "inherit"]`.
* These variants have unresolved open questions. See tracking issue.

## Potential future work

There is a discussion about changing the default `SIGPIPE` handler. See [here](https://github.com/rust-lang/rust/issues/62569). Changing the default would likely require us to also stabilize `#[unix_sigpipe = "sig_ign"]`. But doing that and discussing changing the default is out of scope of this PR.

## Left to do

- [ ] Update the unstable book [page](https://doc.rust-lang.org/beta/unstable-book/language-features/unix-sigpipe.html) of `unix_sigpipe` if we merge this.

## FCP

Since we can't close the [tracking issue](https://github.com/rust-lang/rust/issues/97889) entirely yet, my hope is that we can do an FCP on this PR rather than on the tracking issue.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
Implementation looks good to me, will wait for the t-lang nomination.

**Comment by joshtriplett** [comment]
I do think we should stabilize "inherit". In particular, if we consider changing the default in a future edition, I'd propose changing the default to "inherit", not to "sig_dfl".

**Comment by kornelski** [comment]
I've mentioned in the forum that [I'm missing an option to ignore both the signal and panic-causing errors in println](https://internals.rust-lang.org/t/defusing-println-when-stdout-is-closed/20325).

If this attribute wasn't so transparent with low-level unix jargon, maybe it could be used to set the third strategy?

**Comment by Enselic** [comment]
> I do think we should stabilize "inherit". In particular, if we consider changing the default in a future edition, I'd propose changing the default to "inherit", not to "sig_dfl", so that we don't make the syscall at all.

I don't think we should stabilize `#[unix_sigpipe = "inherit"]`, because if we change the default in a future edition to be to not touch `SIGPIPE` at all we would have
* `fn main()` => `SIGPIPE` not touched
* `#[unix_sigpipe = "sig_ign"] fn main()` => `SIGPIPE` set to `SIG_IGN`
* `#[unix_sigpipe = "sig_dfl"] fn main()` => `SIGPIPE` set to `SIG_DFL`

Maybe we don't even need `#[unix_sigpipe = "sig_dfl"]` at all in that case. 

So maybe we need to make a decision on https://github.com/rust-lang/rust/issues/62569 after all, before we can stabilize anything. Perhaps summarizing https://github.com/rust-lang/rust/issues/62569 into an RFC is the best way forward here. I think it is, and I hope to get around to it in a not too distant future.

> If this attribute wasn't so transparent with low-level unix jargon, maybe it could be used to set the third strategy?

I replied to your post in the forum. In short: I don't think `#[unix_sigpipe = "..."]` will be useful for this.

**Comment by joshtriplett** [comment]
@Enselic What's the harm in stabilizing `inherit` even if it subsequently becomes the default?

We allow people to write `repr(Rust)`, or `pub(self)`, even though those are the defaults.

**Comment by Enselic** [comment]
@joshtriplett It is possible I am overestimating the harm of stabilizing an attribute that might not be needed long term. 10 years from now I just think it will be annoying to have to maintain an attribute variant that is not needed. It unnecessarily restricts us. 

If we can find a way to turn `sigpipe: u8` of `fn lang_start()` into a `sigpipe: bool`, we will achieve better lto. Meaning that the code for the call to `libc::signal` can more easily be removed [entirely](https://github.com/rust-lang/rust/pull/97802#discussion_r893965842).

If we want to stabilize `#[unix_sigpipe = "inherit"]`, I can't help but want to bikeshed the name a bit more. Looking at `man 7 signal` we can see that "inherit" happens during `fork()`:

> A  child  created  via  fork(2)  inherits a copy of its parent's signal dispositions.

so I don't think "inherit" is a slam-dunk name to use in our case, because the "inherit" mechanism has already been applied when the Rust `lang_start()` code runs.

Maybe `#[unix_sigpipe = "unchanged"]` is a better name?

**Comment by kornelski** [comment]
Maybe change the default on edition boundary, and only support a Boolean attribute that restores the old behavior for `cargo fix` to use?

**Comment by jstarks** [comment]
If we stabilize inherit and skip stabilizing dfl, then people who want dfl can explicitly make the call in main themselves. And then you can remove the dfl option altogether and get your lto win.

If we don’t stabilize inherit, then people who want standard UNIX behavior have **no** way to get it, other than wait for an unspecified new edition, I guess? Which in reality is another 3 years away, at least?

**Comment by joshtriplett** [comment]
Discussed in today's @rust-lang/libs meeting: libs does not consider ourselves a blocker for this stabilization.

**Comment by Enselic** [comment]
Rebased. Current status:

If we decide not to change the default `SIGPIPE` disposition which is my [recommendation](https://github.com/rust-lang/rust/issues/62569#issuecomment-1960809610), there are no blockers to FCP this PR to stabilize `#[unix_sigpipe = "sig_dfl"]`. 

If we want to change the default `SIGPIPE` disposition to `"inherit"` over an edition boundary, we *maybe* still want to stabilize `#[unix_sigpipe = "sig_dfl"]`, but it is less of a slam dunk because in practice `SIG_DFL` will be the default.

We can't stabilize `#[unix_sigpipe = "sig_ign"]` yet because [currently](https://github.com/rust-lang/rust/pull/121573) child processes get `SIG_IGN`, but arguably they should get `SIG_DFL` since that is what most programs assume, and we explicitly made it that way [before](https://github.com/rust-lang/rust/pull/25784). Note that we can implement this without running code right before `exec`, see https://github.com/rust-lang/rust/pull/121578 for the trick. This open question is mentioned in the [tracking issue](https://github.com/rust-lang/rust/issues/97889) now.

We can't stabilize `#[unix_sigpipe = "inherit"]` because we might want to rename it to e.g. `#[unix_sigpipe = "unchanged"]`. This open question is mentioned in the [tracking issue](https://github.com/rust-lang/rust/issues/97889) now.

**Comment by bstrie** [comment]
On behalf of the Edition 2024 Working Group, even though our soft deadline for accepting editions changes has passed, we're still willing to entertain changing the SIGPIPE default in the 2024 edition, but the hard deadline for the edition cutoff is the end of May, so please make a decision promptly. :)

**Comment by hypatian** [comment]
As someone who writes a lot of software that works by connecting things up with pipes: I _strongly_ encourage at least getting `#[unix_sigpipe = "sig_dfl"]` out of nightly.

After reading around in [62569](https://github.com/rust-lang/rust/issues/62569), I understand better now some of the concerns around changing the Rust signal-handling default behavior. While as a UNIX-style command-line tool dev I'd much rather _not_ have been surprised by this difference from other development environments on UNIX, it was not that hard to find out where the surprise was coming from and to resolve it.

Except, that is, for the fact that it's locked me into using nightly for basically all of my Rust development ever. That's really my only beef: it's been years, and I'm still using nightly _just for this_.

So change the default for edition 2024 or don't... but please, _please_, at least make it possible for developers of UNIX pipe-based tools to use stable instead of having to take on nightly _just_ to get back to their operating system's default behavior.

**Comment by Amanieu** [comment]
As a completely separate concern from what to do about the default behavior, I have some concerns about the attribute syntax itself.

Currently, the attribute describes the syscall that is being performed (setting the signal disposition for SIGPIPE), but this is a very low-level API that may be confusing to people not familiar with the weeds of UNIX pipes. Additionally, `#[unix_sigpipe = "sig_ign"]` would be misleading if #121578 lands since we won't actually be using `SIG_IGN` at all in that case.

I believe that the attribute should instead describe *what* it is actually achieving: in this case, changing the behavior of the program when a pipe is broken. Proposed syntax: `#[on_broken_pipe = "..."]` or `#[unix_on_broken_pipe = "..."]`.

Possible values for the attribute would be:
- `"inherit"` to inherit the behavior from the parent process.
- `"kill"` to kill the process with SIGPIPE.
- `"error"` to have writes return an error (EPIPE).

**Comment by m-ou-se** [comment]
I'm worried that stabilizing this attribute makes `std` even more special than it already is. See my comment on the tracking issue: https://github.com/rust-lang/rust/issues/97889#issuecomment-2007391597

**Comment by Enselic** [comment]
I will look into ways of removing the `sigpipe` arg on `fn lang_start()`. I will also look into renaming the attribute.

This means stabilization of this attribute will not happen near term, so I will close this PR for now. Thanks all for the feedback 👍

**Pull request closed without merging**
