### PR TITLE
Update vectors.md

### PR DESCRIPTION
**Pull request by ghost**
Feel silly because it's just one thing but it was bothering me that the documentation tells you what you're not going to learn now instead of linking to the item in question.  Am total noob pls assist, where is power button. :)

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you! I didn't do the linking in the past because I knew things might change around, but now that things are the way I like them, seems good!

**Comment by steveklabnik** [comment]
@rundrop1 why did you close this?

**Comment by rundrop1** [comment]
I told you I couldn't find the power button.  If you let me know when you're in the Twin Cities I'll be sure to snag you a beer for your efforts :).

**Comment by steveklabnik** [comment]
:)

**Pull request merged**
