### PR TITLE
const_evaluatable: consider sub-expressions to be evaluatable

### PR DESCRIPTION
**Pull request by BoxyUwU**
see [zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/const_evaluatable.3A.20subexpressions) for more info 

cc @lcnr 
r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
you need to rebase. I think your previous PR is not in the history of this one, so the call to `walk` from the other PR now also needs a `.root()` call.

**Comment by BoxyUwU** [comment]
The places that are erroring in that rollup dont seem to have any calls to walk_abstract_const on master branch so I think maybe one of the other PR's added them

**Comment by oli-obk** [comment]
You're right, it conflicts with https://github.com/rust-lang/rust/pull/79291

**Comment by oli-obk** [comment]
let's wait for the other PR to merge first

**Comment by BoxyUwU** [comment]
that PR seems to have been merged so fingers crossed there are no other PR's that use walk_abstract_const lurking around lol

**Pull request merged**
