### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by tgross35**
Successful merges:

 - #128107 (Migrate `raw-dylib-alt-calling-convention`, `raw-dylib-c` and `redundant-libs` `run-make` tests to rmake)
 - #128362 (add test for symbol visibility of `#[naked]` functions)
 - #128417 (Add `f16` and `f128` math functions)
 - #128638 (run-make: enable msvc for `link-dedup`)
 - #128647 (Enable msvc for link-args-order)
 - #128649 (run-make: Enable msvc for `no-duplicate-libs` and `zero-extend-abi-param-passing`)
 - #128766 (Trivial grammar fix in const keyword docs)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=128107,128362,128417,128638,128647,128649,128766)

### CODE REVIEW

**Comment by tgross35** [comment]
Looks like there are some networking issues

**Comment by tgross35** [comment]
Networking again

@bors retry

**Comment by Kobzol** [comment]
Trying https://github.com/rust-lang/rust/pull/128417, probably just a small doc regression caused by larger documentation of stdlib.

**Comment by Kobzol** [comment]
Yes, it was indeed caused by that PR.
 
@rustbot label: +perf-regression-triaged

**Pull request merged**
