### PR TITLE
fix building libstd with cfg(miri)

### PR DESCRIPTION
**Pull request by RalfJung**
Follow-up to https://github.com/rust-lang/rust/pull/60156 to fix the failure in https://github.com/rust-lang/miri/pull/721.

I *think* that build scripts get the same feature flags, but someone please correct me if I am wrong.

Also I wonder why this didn't cause https://github.com/rust-lang/rust/pull/60156 to fail...

### CODE REVIEW

**Comment by joshtriplett** [comment]
Can you explain a bit more about why this would only be needed for miri, and not for non-miri?

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/60156, we use `SecRandomCopyBytes` on macOS with Miri. But we also still need to be able to build the libstd so Miri can use it, [and that builds a dylib](https://github.com/rust-lang/rust/issues/56443), and I think that's what's failing here.

**Comment by RalfJung** [comment]
This now blocks https://github.com/rust-lang/rust/issues/60533

**Comment by RalfJung** [comment]
Cc @rust-lang/libs does this seem reasonable?

**Comment by SimonSapin** [comment]
Should `SecRandomCopyBytes` also be used in non-miri std?

**Comment by RalfJung** [comment]
No: https://github.com/rust-lang/rust/pull/59879

**Comment by alexcrichton** [comment]
This seems indicative of a deeper bug that would be better fixed than linking yet another framework in the build script. Why, when running with miri, is any artifact being linked? Presumably miri just needs full metadata, right?

**Comment by RalfJung** [comment]
@alexcrichton that would be https://github.com/rust-lang/rust/issues/56443

**Comment by alexcrichton** [comment]
I'm not sure that really answers my question though because that issue is about producing just an rlib, but that still feels wrong because miri doesn't need anything beyond metadata?

**Comment by RalfJung** [comment]
How can we build a metadata-only libstd? We can't even figure out how to build an rlib-only libstd.

**Comment by alexcrichton** [comment]
I don't really even know how you're building libstd to begin with. If you're using `cargo` it seems like you could use `cargo check` instead of `cargo build`. If you're doing something else it seems like you could presumably switch some flags...

I'm basically just asking that some elbow grease is applied somewhere by someone so we don't have to keep applying these hacks. I do not have the time to apply the elbow grease myself, and I can try to scrounge together enough time to at least review things. I'm sorry though but I'm not available for a back-and-forth design discussion over how to design builds of libstd for miri, that's just so far off my radar.

**Comment by joshtriplett** [comment]
This is decidedly outside my area of expertise; handing off to someone more familiar with miri.

r? @Centril

**Comment by Centril** [comment]
Also outside of my expertise; r? @oli-obk

**Comment by RalfJung** [comment]
> I don't really even know how you're building libstd to begin with. If you're using cargo it seems like you could use cargo check instead of cargo build. If you're doing something else it seems like you could presumably switch some flags...

Interesting idea, I'll put that on the list. However, at least the way things are right now, when Miri is built as a rustc tool it shares the libstd with the rest of the build, so we'd still have to also build the full thing.

If this PR here is considered too hacky, I can also just revert https://github.com/rust-lang/rust/pull/60156. This means `HashMap` will not work on macOS but it will work everywhere else.

**Comment by oli-obk** [comment]
My opinion is that this is ok, since it is a temporary hack anyway. It will go away once we figure out how to (fake-)open `/dev/random` in miri.

Until then I think it would be better to support `HashMap` on mac os. If you fear the hack will persisist, I think it would be reasonable to set a "kill the hack or revert and break HashMap on mac os" deadline so we miri folks have some pressure. Something like 6 months seems ok to me.

**Comment by alexcrichton** [comment]
Having a deadline for the removal of this seems reasonable to me, so I would be ok with that. Has this change been tested with miri? It seems like the previous one wasn't maybe and if you're using Cargo with RUSTFLAGS this change won't work (since build scripts don't get RUSTFLAGS), so I just wanted to confirm.

**Comment by RalfJung** [comment]
I don' have a Mac, so I am afraid I cannot test this.

**Comment by alexcrichton** [comment]
Ok but surely we can at least agree that before merging hacks into libstd we should at least have anyone testing to show that they do indeed satisfy the intended use case?

**Comment by RalfJung** [comment]
I agree with the sentiment, but don't have any idea how to do so.

Miri is currently broken, so that can't get worse. ;)  But I don't know if this could have an effect on the other tools, which I think are built by the same builder.

**Comment by oli-obk** [comment]
You could bump the miri submodule in this PR. That way the PR only merges if your change actually fixes miri (assuming we test miri on mac in CI)On 11 May 2019 00:01, Ralf Jung <notifications@github.com> wrote:I agree with the sentiment, but don't have any idea how to do so.
Miri is currently broken, so that can't get worse. ;)  But I don't know if this could have an effect on the other tools, which I think are built by the same builder.

**Comment by RalfJung** [comment]
Hm, that would help. However we don't build libstd the same way here on CI ans in standalone Miri.

**Comment by RalfJung** [comment]
Now this includes a Miri update.

But given that https://github.com/rust-lang/rust/pull/60156 was able to land, I don't think this actually tests if linking works -- though I don't know why.

Maybe it is easier to just revert https://github.com/rust-lang/rust/pull/60156...

**Comment by RalfJung** [comment]
I just realized I had entirely forgotten about https://github.com/rust-lang/cargo/issues/4423. So we won't see the `cfg(miri)` in the build script anyway -- the entire approach does not work.

**Pull request closed without merging**
