### PR TITLE
rustdoc: move collapse and unindent docs passes earlier

### LINKED ISSUE #58473: nightly: unexpected "could not parse code block" in indented block docs in presence of backticks
I believe this is a minimal example. Warning disappears if either:

- backticks are removed
- indentation is removed
- `///`-style formatting is used

```rust
// don't even need to be in `impl`, yeah
//pub struct Foo {}
//impl Foo {
    /**
    Does nothing, returns `()`

    yadda-yadda-yadda
    */
    pub fn foo() {}
//}
```

```
$ cargo doc
 Documenting rust-nightly-doc-wat v0.1.0 (/home/thriller/tmp/rust-nightly-doc-wat)
    Finished dev [unoptimized + debuginfo] target(s) in 1.08s
$ cargo +nightly doc
 Documenting rust-nightly-doc-wat v0.1.0 (/home/thriller/tmp/rust-nightly-doc-wat)
warning: could not parse code block as Rust code
 --> src/lib.rs:5:5
  |
5 | /     Does nothing, returns `()`
6 | |
7 | |     yadda-yadda-yadda
  | |_____________________^
  |
  = note: error from rustc: unknown start of token: `

    Finished dev [unoptimized + debuginfo] target(s) in 1.29s
```

```
$ rustc +nightly --version --verbose
rustc 1.34.0-nightly (e54494727 2019-02-13)
binary: rustc
commit-hash: e54494727855cd14229f5d456591ed2a2f027c46
commit-date: 2019-02-13
host: x86_64-unknown-linux-gnu
release: 1.34.0-nightly
LLVM version: 8.0
```
(straight from rustup)

### PR DESCRIPTION
**Pull request by euclio**
Moves these passes as early as possible so later passes will see the same markdown that is passed to the test collector.

Fixes #58473, and a similar issue with the private-doc-tests lint.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
I find it funny that this is required, since these two passes were what i considered the "canonical" late passes, in that i wasn't expecting anything that needed to run in the compiler context to depend on them. One consequence of this change is that the only late pass left is `propagate-doc-cfg`. Should we fold that one in too in its current position and get rid of the old pattern of passes that run without a DocContext?

**Comment by euclio** [comment]
I can do that. I don't think that the distinction is very useful after this change.

**Comment by euclio** [comment]
Pushed a new commit that removes the concept of early vs. late passes.

**Review by QuietMisdreavus — APPROVED** [review]
Looks good, thanks so much!

**Pull request merged**
