### PR TITLE
doc: this note is not needed

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is a convention even when there are only basic examples, for uniformity.

**Comment by tshepang** [comment]
You closed this too quickly... it isn't a convention if it's only used sometimes. In what cases does it apply exactly?

**Comment by steveklabnik** [comment]
As I go through, I am putting it in literally every `# Examples` block.

**Comment by tshepang** [comment]
I think we should remove these. They add nothing, unless a more advanced example is given. It's also not universal... I see it in iter docs, but not in Vec, for example.

**Comment by steveklabnik** [comment]
That's because I have not yet completed my pass over the docs.

I do think they add something: consistency between documentation with single examples and multiple examples.

less is not always better.

**Comment by tshepang** [comment]
I agree *less* is not always better, but in this case I see *more* as noise. Places that have multiple examples are rare.

**Pull request closed without merging**
