### PR TITLE
Change the title of if statement in trpl book.

### PR DESCRIPTION
**Pull request by loganchien**
Slightly change the title to make it look more consistent with other chapters (e.g. Match.)

### CODE REVIEW

**Comment by steveklabnik** [comment]
Actually, it should be the other way around. Care to fix `match` instead?

**Comment by steveklabnik** [comment]
(and thank you!)

**Comment by loganchien** [comment]
However, unfortunately, it seems that the backticks do not work in the title block of pandoc.  Unlike the backticks in the headings, the backticks in the title block will be left as-is (and won't be changed to the `<code></code>` tags.)  Is this the preferred result?

**Comment by steveklabnik** [comment]
Ugh. No. :(

I guess this patch works, then. Thank you!

**Pull request merged**
