### PR TITLE
resolve: fix label scopes

### LINKED ISSUE #37353: ICE "break to unknown label" when while has a labeled break of itself in condition
```rust
fn main() {
    loop { 'w: while break 'w { } }
}
```
ICEs with:
```
rustc 1.14.0-nightly (6e8f92f11 2016-10-07)
error: internal compiler error: ../src/librustc/middle/liveness.rs:1057: break to unknown label
 --> <anon>:3:19
  |
3 |         'w: while break 'w { }
  |                   ^^^^^^^^
```
Code like this was found in issue #21751.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #37353 (turns an ICE back into an error).
r? @nrc

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Marking for beta-accepted since this is a small, harmless-looking patch. It fixes an ICE (turns it back into a hard error). I could see a counter argument that such a change (since it is an error otherwise) doesn't merit a backport.

What say you, @rust-lang/compiler ?

**Comment by eddyb** [comment]
SGTM.

**Comment by michaelwoerister** [comment]
👍

**Pull request merged**
