### PR TITLE
Add libproc_macro to rust-src distribution

### LINKED ISSUE #55279: Add proc_macro crate sources to "rust-src" distribution
In IntelliJ-Rust we use "rust-src" rustup component to acquire standard crates sources (which we use for all IDE intelligence). And there is not proc_macro crate in the standard "rust-src" distribution. It results to the fact that our IDE know nothing about proc_macro crate and can't provide any IDE features in code that uses it.
So it would be very nice to add "proc_macro" to "rust-src" rustup component distribution =)

Is it enough to just add it to this list?
https://github.com/rust-lang/rust/blob/554b7874a9f720d1a1e83958f3137da4c8f3f33b/src/bootstrap/dist.rs#L858

I see proc_macro has a several dependencies: "libsyntax", "libsyntax_pos", "librustc_errors", "librustc_data_structures". Is it ok to not add them to the list?

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #55279

### CODE REVIEW

**Comment by TimNN** [comment]
Ping from triage @aturon: This PR requires your review.

**Comment by Mark-Simulacrum** [comment]
@bors r+

Cc @rust-lang/libs @rust-lang/lang just for awareness (but I don't see this as anything that needs a team decision - proc_macro is stably exposed).

**Comment by cuviper** [comment]
From #55279:
> I see proc_macro has a several dependencies: "libsyntax", "libsyntax_pos", "librustc_errors", "librustc_data_structures". Is it ok to not add them to the list?

@vlad20012, what did you find?  Is `libproc_macro` alone useful enough for your IDE, without its other dependencies?

**Comment by vlad20012** [comment]
@cuviper 
> Is libproc_macro alone useful enough for your IDE, without its other dependencies?

Certainly yes! It doesn't re-export its dependencies.
My question was just about your vision of source distribution (is it ok or not to distribute some crate sources without its dependencies). A for me - it's ok =)

**Comment by Mark-Simulacrum** [comment]
Yes, the rust-src component is purely intended for this sort of autocompletion etc -- if you want to build Rust, that's a separate component (i.e., the source code itself, in full)

**Pull request merged**
