### PR TITLE
rustc_codegen_llvm: Give each codegen unit a unique DWARF name on all platforms, not just Apple ones.

### LINKED ISSUE #88521: [DWARF] Crate Debug Info incomplete?
Hello.

To preface this. I know nothing about RUST and its compiler. I am coming to this issue on toolchain side BOLT/DWP and dealing with debug information that is produced.

### High level summary:
I am seeing multiple Skeleton CUs that have exact same DWO ID. So for example with ThinLTO when Split dwarf is enabled in main binary there are multiple CUs that point to different .dwo files, but have the same DWO ID.

Looking in to those files in to .debug_info.dwo section. They are either exactly the same, or differ by DW_AT_linkage_name.
Although LLVM can be changed to include DW_AT_linkage_name as part of the hashing algorithm, it won't solve the issue fully.

Tools like BOLT (https://github.com/facebookincubator/BOLT), or llvm-dwp rely on DWO ID to be unique. 
From DWARF 5 spec (when this was all standardized), but I think also applies to DWARF4

> dwo_id (unit ID)
> An 8-byte implementation-defined integer constant value, known as the compilation unit ID, that provides unique identification of a skeleton compilation unit and its associated split compilation unit in the object file named in the DW_AT_dwo_name attribute of the skeleton compilation.

### Digging a bit in to it:
Looking in to one of the cases where only difference was DW_AT_linkage_name.
There are multiple modules, crates in rust land?, that are created. They define the same templated functions, and import the same functions.

For example looking at LLVM IR of one of the modules and one of the functions:

> !74 = distinct !DISubprogram(name: "allocate_in<u8,alloc::alloc::Global>", linkageName: "_RNvMs_NtCsj2IQpe5qjeI_5alloc7raw_vecINtB4_6RawVechE11allocate_inCs**g6LRvGNwJvd**_41**foo_bar**", scope: !76, file: !75, line: 180, type: !96, scopeLine: 180, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !43, templateParams: !94, retainedNodes: !98)
> !75 = !DIFile(filename: "<>/rust/1.53.0/src/<>/build/rust/library/alloc/src/raw_vec.rs", directory: "", checksumkind: CSK_MD5, checksum: "70792e0964fbcac42a3928c645b54f9d")
> !76 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "RawVec<u8, alloc::alloc::Global>", scope: !53, file: !2, size: 128, align: 64, elements: !77, templateParams: !94, identifier: "900af9eff81db06f40b139cda685ab1")

We have a function:
alloc_in that is part of templated raw_vec
https://doc.rust-lang.org/src/alloc/raw_vec.rs.html#188
https://doc.rust-lang.org/src/alloc/raw_vec.rs.html#115

From LinkageName this is relavant?
`pub mod bar {
    pub use foo_bar::*;
}`

In a different module it will have:
> !74 = distinct !DISubprogram(name: "allocate_in<u8,alloc::alloc::Global>", linkageName: "_RNvMs_NtCsj2IQpe5qjeI_5alloc7raw_vecINtB4_6RawVechE11allocate_inCs**kK341NkcZ13**_41**foo_bar2**", scope: !76, file: !75, line: 180, type: !96, scopeLine: 180, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !43, templateParams: !94, retainedNodes: !98)
> !75 = !DIFile(filename: "<>/rust/1.53.0/src/<>/build/rust/library/alloc/src/raw_vec.rs", directory: "", checksumkind: CSK_MD5, checksum: "70792e0964fbcac42a3928c645b54f9d")
> !76 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "RawVec<u8, alloc::alloc::Global>", scope: !53, file: !2, size: 128, align: 64, elements: !77, templateParams: !94, identifier: "900af9eff81db06f40b139cda685ab1")

and on rust side:
`pub mod bar2 {
    pub use foo_bar2::*;
}`

I haven't looked in to cases where debug information is identical, beyond that it didn't have any functions just type information {DW_TAG_namespace , DW_TAG_enumeration_type , DW_TAG_enumerator}.

To me it seems that there is debug information missing on some level that represents what crate this CU belongs.
Any thoughts?

### PR DESCRIPTION
**Pull request by pcwalton**
To avoid breaking split DWARF, we need to ensure that each codegen unit has a
unique `DW_AT_name`. This is because there's a remote chance that different
codegen units for the same module will have entirely identical DWARF entries
for the purpose of the DWO ID, which would violate Appendix F ("Split Dwarf
Object Files") of the DWARF 5 specification. LLVM uses the algorithm specified
in section 7.32 "Type Signature Computation" to compute the DWO ID, which does
not include any fields that would distinguish compilation units. So we must
embed the codegen unit name into the `DW_AT_name`.

Closes #88521.

### CODE REVIEW

**Comment by pcwalton** [comment]
Note that this only causes a problem in practice if an external (non-rustc) linker is used, because rustc contains some logic to merge DWARF compilation unit entries that has the side effect of working around this bug.

**Review by davidtwco — APPROVED** [review]
Thanks for fixing this, I hadn't noticed #88521 but this explains the issue I ran into when trying to bootstrap rustc with Split DWARF (https://github.com/rust-lang/rust/pull/89819#issuecomment-944156113).

**Pull request merged**
