### PR TITLE
Specify that packed types must derive, not implement, Copy

### LINKED ISSUE #50826: "#[derive] can't be used on a non-Copy #[repr(packed)] struct" but struct is Copy
Reported by @retep998 at https://github.com/rust-lang/rust/issues/46043#issuecomment-389696974, here's a minimal example:
```rust
#[repr(packed)]
#[derive(Debug)]
struct Foo {
    x: usize,
}

impl Clone for Foo {
    fn clone(&self) -> Self {
        Foo { x: self.x }
    }
}
impl Copy for Foo {}
```
[play](https://play.rust-lang.org/?gist=ec60a3f40eaf5cc5f57dd4b206b15fba&version=stable&mode=debug)

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Comment by cramertj** [comment]
Are all of the autogenerated derive impls already smart enough to `Copy` out fields of packed `Copy` types when they use them? I would have assumed they'd still attempt to create references to the fields, which is unsound.

**Comment by Mark-Simulacrum** [comment]
I'm not sure; the error message though somewhat indicates that they should be... it looks like there's some code in libsyntax_ext which does something to take care of it, but I don't follow it well enough to be sure. It seems somewhat unrelated to this change though.

**Comment by cramertj** [comment]
I just checked the behavior with `--pretty-expanded` and it looks like adding `Copy` causes the compiler to omit references to fields. Thanks!

@bors r+

**Comment by cramertj** [comment]
Ah, wait no-- it only omits the reference if the `Copy` impl was in `derive`-- it doesn't omit it in the case of manual `Copy` impls. Either that should be fixed (hard, I think) or this PR should be amended to check for a `derive` of `Copy` (rather than that the type implements `Copy`).

@bors r-

**Comment by rkruppe** [comment]
@bors r-

If my understanding of derives isn't completely out of whack, derives can only look at the source code of the struct to determine if it's copy, so a completely separate `impl Copy` would be indistinguishable from not being Copy at all. Therefore this PR silences the warning even in cases where the fields are not copied out in the generated code, i.e., where there is still UB. This can be seen both by [looking at libsyntax_ext](https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/libsyntax_ext/deriving/generic/mod.rs#L436-L439) and the output of `--pretty=expanded` for the test case added in this PR.

**Comment by cramertj** [comment]
Sounds good to me. Thanks for the updates! r=me with travis passing.

**Comment by RalfJung** [comment]
Per @retep998's comment at <https://github.com/rust-lang/rust/issues/46043#issuecomment-389696974>, this breaks WinAPI.

**Comment by retep998** [comment]
It doesn't break `winapi` so much as simply document that things actually are broken.

**Pull request merged**
