### PR TITLE
Core features cleanup

### PR DESCRIPTION
**Pull request by m-ou-se**
This sorts and categorizes the `#![features]` in `core` and removes unused ones.

This is part of #87766

The following feature attributes were unnecessary and are removed:

```diff
// Library features:
-#![feature(bool_to_option)]
-#![feature(char_indices_offset)]
-#![feature(pin_deref_mut)]
-#![feature(str_split_as_str)]
-#![feature(str_split_inclusive_as_str)]

// Language features:
-#![feature(arbitrary_self_types)]
-#![feature(custom_inner_attributes)]
-#![feature(nll)]
```

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Nice!

**Comment by m-ou-se** [comment]
Rebased after another PR already removed `unwind_attributes` attriute.

@bors r=dtolnay

**Comment by jyn514** [comment]
dist-mingw failed without logs.

@bors retry

**Pull request merged**
