### PR TITLE
Fix ICE per #28172

### PR DESCRIPTION
**Pull request by alexispurslane**
This fixes the ICE, and makes it just a compiler error/warning. I'm not exactly sure that's whats wanted, so tell me if it isn't.

### CODE REVIEW

**Comment by arielb1** [comment]
@christopherdumas 

This leads to error triplication - one from `global_expr`, one from `const_eval` and the one you added. I would `const_eval` the sides, error-return if this failed, compare them, and then `global_expr` (the `global_expr` is needed to set up the flags).

**Comment by christopherdumas** [comment]
@arielb1 Can you elaborate a little more? I'm new to Rust, so this doesn't make much sense to me.

**Comment by arielb1** [comment]
@christopherdumas 

First, we add a test for every bug fixed in rustc. The tests we add are typically compiletests - these are `.rs` files which are compiled and the compilation result is checked. Because #28172 is erroneous code, your test will check that it is rejected with a correct error message - this is called a compile-fail test. All files in `src/test/compile-fail` are compile-fail tests.
```Rust
// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

fn main() {
    let x = 0;
    match 1 {
        0 ... x => {} //~ ERROR non-constant path
    };
}
```

The `//~` is how we check the correct error is emitted - you wouldn't like random changes to rustc to cause the test to break on an unrelated error (this was more important before 1.0, but still occurs).

Anyway, your change causes 3 errors to be emitted in that case, and that is just ugly.

**Comment by christopherdumas** [comment]
Ok whoops! Thanks for explaining.

**Comment by christopherdumas** [comment]
The second commit gives the proper behavior. As I said in #28178, there are two things wrong with the code, so two errors are necessary, but the third error (the ICE) is not.

**Comment by christopherdumas** [comment]
OK, @nikomatsakis I implemented that. It works just fine. BTW, is there any way I can familiarize myself more with the Rust codebase? This is one of my first pull requests to Rust, so I don't have much domain-specific knowledge.

**Comment by nikomatsakis** [comment]
@christopherdumas (sorry for the delay)

>  OK, @nikomatsakis I implemented that. It works just fine. 

Looks great, thanks. Can you maybe squash the commits?  Most of the history doesn't seem so relevant anymore.

> BTW, is there any way I can familiarize myself more with the Rust codebase? This is one of my first pull requests to Rust, so I don't have much domain-specific knowledge.

Hmm, I'm not sure of any great resource. I guess it's our job to let you know about these things :)

**Comment by nikomatsakis** [comment]
(our job as reviewers, I mean)

**Comment by christopherdumas** [comment]
@nikomatsakis Sorry about my delay, I'll squash the commits.

**Comment by christopherdumas** [comment]
@nikomatsakis I've squashed all the commits, and the tests are passing.

**Comment by christopherdumas** [comment]
@nikomatsakis I added a test, but since there are two errors on the same line, it fails. Do you know how to fix this?

**Comment by nikomatsakis** [comment]
@christopherdumas yes, you can do this:

```
/* offending-line */
//~^ ERROR error1
//~| ERROR error2
```

The `^` means "on the line above", and the `|` means "same line as the previous `ERROR`. 

Just for reference, you can put any number of `^`, so `//~^^` means "two lines above" and so forth.

**Comment by christopherdumas** [comment]
@nikomatsakis Awesome! Thanks!

**Comment by christopherdumas** [comment]
@nikomatsakis Is there a manual for the testing stuff that you showed me?

**Comment by christopherdumas** [comment]
Merge conflict!

**Comment by christopherdumas** [comment]
@nikomatsakis Can you make bors retry?

**Comment by christopherdumas** [comment]
@alexcrichton Why is bors' homu test failing?

**Comment by jonas-schievink** [comment]
```
failures:
    net::udp::tests::test_read_timeout
    net::udp::tests::test_read_with_timeout
```

Looks like a spurious failure, not caused by your PR

**Comment by arielb1** [comment]
@bors retry

@christopherdumas our buildbot is glitchy.
@alexcrichton what's the Geiger counter results on the buildbot?

**Pull request merged**
