### PR TITLE
Implement From<Vec<char>> for String

### PR DESCRIPTION
**Pull request by aochagavia**

### CODE REVIEW

**Comment by aochagavia** [comment]
Should I add an attribute like `#[stable(feature = "...", since = "...")]`? What should the values of `feature` and `since` be?

**Comment by Gankro** [comment]
This is really weird to support. What's the use case look like?

**Comment by Gankro** [comment]
(you can make up a feature and since should be the current nightly version)

**Comment by Diggsey** [comment]
This has a much higher overhead than I'd normally expect from a `From` implementation. Just using `.into_iter().collect()` explicitly seems like a better option, in that it doesn't hide the cost? (Implicit copying is very un-rustlike)

**Comment by aochagavia** [comment]
Thanks for the feedback!

My use case is the following: I had a `Vec<char>` that I wanted to turn into a `String` using `vec.into()` (it just looked straightforward). I found it surprising that it was not implemented... why shouldn't it? The only requirement is to implement `From`.

Although the documentation of `From` doesn't say anything about overhead, the fact that it is implemented to construct a `String` from a `&str` (allocating) shows that it doesn't matter that much. Additionally, the documentation of `Into` explicitly mentions that the overhead may be high or low.

Maybe I am missing something, but I think it is logical to expect that a `String` can be constructed from a `Vec<char>`

**Comment by remram44** [comment]
I also bumped into [char] to String (#22868), which isn't implemented either.

**Comment by Gankro** [comment]
At very least, Vec seems needlessly specific since char is Copy.

**Comment by nagisa** [comment]
Could this be `impl From<&[char]> for String` instead? Seems like it would cover strictly more cases and there’s no real reason for converting from explicitly `Vec`, because you don’t reuse the underlying allocation anyway (you totally could, though!).

**Comment by remram44** [comment]
> you don’t reuse the underlying allocation anyway (you totally could, though!)

`Vec<u8>` to `String` yes (but needs validation; this is what `String::from_utf8()` does), but not `Vec<char>`.

**Comment by Gankro** [comment]
Actually you could reuse the allocation for `Vec<char> -> String` since Vec<char> strictly consumes more bytes than the equivalent String. You'd have to backshift the bytes and probably have a *ton* of extra space on most strings but you could reuse the allocation.

**Comment by oli-obk** [comment]
related: http://stackoverflow.com/questions/29158406/creating-a-string-from-vecchar and http://stackoverflow.com/questions/23430735/how-to-convert-vecchar-to-a-string

**Comment by aochagavia** [comment]
I think I will just stick with `into_iter().collect()`, since it seems that the added value of a `From` implementation is not that much.

**Comment by nagisa** [comment]
For a future reference, I implemented [a non-allocating version][1]. I, personally, think this is non-trivial-to-implement functionality and could be provided by the standard library.

[1]: https://gist.github.com/nagisa/ef7df0a048504c23b9ac

**Pull request closed without merging**
