### PR TITLE
Reference: Mention `move` keyword for lambdas

### PR DESCRIPTION
**Pull request by angelsl**
From issue #36683

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks so much!

**Comment by angelsl** [comment]
I realise the example is rather trivial and doesn't actually _require_ `move` there...

But I can't think of one that isn't overly complex &mdash; I guess there isn't such an example, because to even need `move` the closure has to live longer than the values it captures i.e. the closure needs to be boxed and stored somewhere else.

**Comment by steveklabnik** [comment]
Yes. I think it's okay to show a simple example even if it's not strictly
_required_ here. If we can get a better one, I'm also up for updating it.
But "there's no mentoin" to "there's a mention that's not perfect" is still
a large improvement.

**Comment by frewsxcv** [comment]
From Travis CI:

```
failures:

---- Statements_and_expressions_16 stdout ----
	error[E0425]: unresolved name `ten_times`
 --> <anon>:3:1
  |
3 | ten_times(move |j| println!("{}, {}", word, j));
  | ^^^^^^^^^ unresolved name

error: aborting due to previous error(s)

thread 'Statements_and_expressions_16' panicked at 'Box<Any>', src/librustc/session/mod.rs:185
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    Statements_and_expressions_16

test result: FAILED. 94 passed; 1 failed; 18 ignored; 0 measured
```

**Comment by angelsl** [comment]
Right, I forgot docs are tested and context doesn't carry over. Oops.

**Comment by angelsl** [comment]
Alright, this should pass.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thank you!

**Pull request merged**
