### PR TITLE
Make `TypeFolder::fold_*` return `Result`

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Implements rust-lang/compiler-team#432.
This should be easier to review commit by commit.

r? @jackh726 cc @nikomatsakis

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
Interestingly, the results are not neutral. There are a few regressions up to 6.9%, but for most tests this looks like a slight improvement up to -2.5%.

**Comment by jackh726** [comment]
I think overall I'm 👍 on this. I'm not sure perf is something we can "fix"; it's kind of mixed anyways. Either way, we should wait for the FCP on the MCP should finish.

**Comment by nikomatsakis** [comment]
It is a slight performance hit. I wonder if we can dig a bit more into why -- feels like an opportunity for us to improve our mir optimizations or something.

**Comment by jackh726** [comment]
I'm 👍 on this PR, except for the perf. @LeSeulArtichaut are you still looking into the perf regression here?

**Comment by JohnCSimon** [comment]
Ping from triage: 
@LeSeulArtichaut - can you please address the merge conflicts?

**Pull request closed without merging**
