### PR TITLE
Stabilize slice_ptr_range.

### LINKED ISSUE #65807: Tracking issue for slice_ptr_range
Tracking issue for `slice_ptr_range` added by https://github.com/rust-lang/rust/pull/65806. See https://github.com/rust-lang/rfcs/pull/2791

### PR DESCRIPTION
**Pull request by m-ou-se**
This has been unstable for almost a year now. Time to stabilize?

Closes #65807.

@rustbot modify labels: +T-libs +A-raw-pointers +A-slice +needs-fcp

### CODE REVIEW

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Review by dtolnay — APPROVED** [review]

**Comment by jeekobu** [comment]
Stabilization report?

**Pull request merged**
