### PR TITLE
coverage: Format all coverage tests with `rustfmt`

### PR DESCRIPTION
**Pull request by Zalathar**
As suggested by <https://github.com/rust-lang/rust/pull/119984#discussion_r1452856806>.

Test files in `tests/` are normally ignored by `x fmt`, but sometimes those files end up being run through `rustfmt` anyway, either by `rust-analyzer` or by hand.

When that happens, it's annoying to have to manually revert formatting changes that are unrelated to the actual changes being made. So it's helpful for the tests in the repository to already have standard formatting beforehand.

However, there are several coverage tests that deliberately use non-standard formatting, so that line counts reveal more information about where code regions begin and end. In those cases, we can use `#[rustfmt::skip]` to prevent that code from being disturbed.

@rustbot label +A-code-coverage

### CODE REVIEW

**Comment by Zalathar** [comment]
cc @dtolnay @kpreid 

I have deliberately avoided touching `closure_macro_async.rs` so that this won't interfere with #119984, which also formats that file. There are some other files that are touched by both PRs, but those should hopefully merge cleanly.

**Review by dtolnay — APPROVED** [review]
Thank you for following up on this!

**Comment by dtolnay** [comment]
In case any other minor changes are needed to make this pass in CI, feel free to use r=dtolnay.

**Comment by kpreid** [comment]
FYI, I have decided to remove the formatting change in `closure_macro_async.rs` from #119984, simply because it is so much a separate issue and not getting it right already blocked merge once.

**Comment by Zalathar** [comment]
The formatting changes to `closure_macro_async.rs` have been removed from #119984, so I've updated this PR to also format that file [(diff)](https://github.com/rust-lang/rust/compare/5dcc3596323583716a4dd94241cc0fa4b602d217..99797bbd9fdb138dd59a782f156db8397d07943c).

r=dtolnay

**Pull request merged**
