### PR TITLE
Remove duplicated styling in main.css

### PR DESCRIPTION
**Pull request by Cldfire**
If nothing else, it saves a bit of data.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@bors: r-

`.current` wasn't a duplicate, only the following block should have been removed:

```css
.sidebar {
    background-color: #F1F1F1;
}
```

**Comment by Cldfire** [comment]
Oh.... are you sure?

The file currently looks like this:

```css
.sidebar {
	background-color: #F1F1F1;
}

.sidebar .current {
	background-color: #fff;
}

.sidebar {
    background-color: #F1F1F1;
}

.sidebar .current {
    background-color: #fff;
}
```

All I've done is remove the bottom two, which seem to be exact, letter-for-letter duplicates of the upper two.

Also, if you look at an element with the `.sidebar .current` class in devtools, you'll see that the style is being applied twice:

spectacle lh5161

If I'm tragically misunderstanding something about CSS here, I'd love to learn from this and correct my knowledge :)

**Comment by GuillaumeGomez** [comment]
Oh damn, you're absolutely, I stupidly looked at your file instead of the current one... My mistake. Just one thing to change though:

```css
.sidebar {
    background-color: #F1F1F1;
}

.sidebar .current {
    background-color: #fff;
}
```

The `.sidebar` is useless since the `background-color` is redefined just below. So we should just keep:

```css
.sidebar .current {
    background-color: #fff;
}
```

Could you update it this way in addition of your removal please?

**Comment by Cldfire** [comment]
So you want the `.sidebar` style class removed completely?

Sorry to double-guess you again, but doing that would mean that the only place the sidebar class would have to get a background-color from would be the `body` styling, which reverts the grey sidebar color change that was made recently...

spectacle lh6749

As you can see in the above screenshot of devtools for https://doc.rust-lang.org/nightly/std/.

Toggling off both `.sidebar` background color changes....

spectacle hf6749

...now gives `.sidebar` `body`'s color, which is white.

spectacle qq6749

**Comment by GuillaumeGomez** [comment]
And you're absolutely right, thought it had a comma... Sorry for the loss of time.

@bors: r=estebank rollup

**Pull request merged**
