### PR TITLE
Revert #48105 ("Implement excluding a build-step via --exclude")

### PR DESCRIPTION
**Pull request by kennytm**
This PR [reverts][1] #48105, since we found that the PR causes some tests not being run. In particular, the entire "toolstate" job has been [skipped][2]. 

r? @Mark-Simulacrum 

[1]: https://mozilla.logbot.info/rust-infra/20180215#c14310309
[2]: https://travis-ci.org/rust-lang/rust/jobs/341822487

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Actually, I'm fairly certain that I've come up with a patch that fixes the behavior... so closing.

**Comment by pnkfelix** [comment]
I think we should land this revert unless @Mark-Simulacrum 's patch (which was not linked and thus I do not know if there's even a PR for it) is also going to fix #48268

**Comment by pnkfelix** [comment]
Ah I assume that @Mark-Simulacrum 's patch is at PR #48252

**Pull request closed without merging**
