### PR TITLE
`Stdio::makes_pipe`

### PR DESCRIPTION
**Pull request by ChrisDenton**
Wrappers around `std::process::Command` may want to be able to override pipe creation. However, [`std::process::Stdio`](https://doc.rust-lang.org/std/process/struct.Stdio.html) is opaque so there's no way to tell if `Command` was told to create new pipes or not.

This is in some ways a more generic (and cross-platform) alternative to #97149. However, unlike that feature, this comes with the price of the user needing to actually create their own pipes rather than reusing the std one. So I think it stands (or not) on its own.

# Example

```rust
#![feature(stdio_makes_pipe)]
use std::process::Stdio;

let io = Stdio::piped();
assert_eq!(io.makes_pipe(), true);
```

### CODE REVIEW

**Comment by ChrisDenton** [comment]
r? rust-lang/libs-api

**Comment by the8472** [comment]
Shouldn't it be `makes_pipe` (interrogative) rather than `make_pipe` (imperative)?

**Comment by the8472** [comment]
Shouldn't it be `makes_pipe` (interrogative) rather than `make_pipe` (imperative)?

**Comment by ChrisDenton** [comment]
Good point, changed!

**Pull request merged**
