### PR TITLE
Obsolete the closure kind syntax

### PR DESCRIPTION
**Pull request by japaric**
Obsoletes the closure kind syntax (the `&:`, `&mut:` `:` in `|&:| {}`) as the compiler will now infer the right `Fn*` trait from the context.

To fix your code simply remove the `&:` annotations, and let the compiler do the magic.

[breaking-change]

### CODE REVIEW

**Comment by aturon** [comment]
:dart:

**Comment by alexcrichton** [comment]
r=me, nice work!

For posterity, the offending FIXMEs were all inserted in this commit: 2c91b5e9199b5b8631a74ac3d50359df54d745b7

**Comment by nikomatsakis** [comment]
Regarding the FIXMEs, those were known -- that is, there is still a bit of remaining work as described in #21805.

**Comment by japaric** [comment]
Should I change the FIXMEs to point to the issue for @nikomatsakis's follow-up work (is there one?), or should I remove them?

**Comment by nikomatsakis** [comment]
@japaric I think the issue is #16640 and it seems like it'd be good point at that.

**Comment by japaric** [comment]
Updated `FIXME`s to point to #16640

**Comment by japaric** [comment]
@bors: retry

(can't reproduce failure locally)

**Pull request merged**
