### PR TITLE
Access Session and OnDiskCache in rustc_query_system

### PR DESCRIPTION
**Pull request by cjgillot**
Reduces the boilerplace of implementing the `DepContext` trait.
The OnDiskCache is accessed directly through a dedicated trait.

### CODE REVIEW

**Comment by jyn514** [comment]
Just because queries are so hot:

@bors try @rust-timer queue

**Comment by jyn514** [comment]
Perf looks like mostly noise I think - improvements of up to 1.5% on instructions counts, but also losses up to .7%.

**Comment by crlf0710** [comment]
@cjgillot Triage: What's the current status of this?

**Comment by jyn514** [comment]
@crlf0710 this is waiting on review (although it needs a rebase at some point).

r? @wesleywiser maybe?

**Pull request closed without merging**
