### PR TITLE
no more `transmute<&List<Ty<'tcx>>, &List<GenericArg<'tcx>>>`

### PR DESCRIPTION
**Pull request by lcnr**
cc https://github.com/rust-lang/rust/pull/94799#issuecomment-1064900766
reverts the first commit of #93505.

let's see what's the perf and max-rss effect of this change.

### CODE REVIEW

**Comment by jackh726** [comment]
It is a very small regression, but I think it's worth it for the reduced complexity.

**Comment by lcnr** [comment]
i don't necessarily think so :thinking: I want to keep using `List<Ty<'tcx>>` for tuples and we already have a small negative perf impact from that and I don't want to make that one bigger.

Going to keep looking for the actual cause of that regression for now and then figure out where to go from there

**Comment by davidtwco** [comment]
> i don't necessarily think so 🤔 I want to keep using `List<Ty<'tcx>>` for tuples and we already have a small negative perf impact from that and I don't want to make that one bigger.
> 
> Going to keep looking for the actual cause of that regression for now and then figure out where to go from there

It doesn't sound like you're intending to land this, so I'll mark it as `S-waiting-on-author` and you can comment again if this should be reviewed so it can land.

**Pull request closed without merging**
