### PR TITLE
Improve memoization and refactor NLL type check

### PR DESCRIPTION
**Pull request by nikomatsakis**
I have a big branch that is refactoring NLL type check with the goal of introducing canonicalization-based memoization for all of the operations it does. This PR contains an initial prefix of that branch which, I believe, stands alone. It does introduce a few smaller optimizations of its own:

- Skip operations that are trivially a no-op
- Cache the results of the dropck-outlives computations done by liveness
- Skip resetting unifications if nothing changed

r? @pnkfelix

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by kennytm** [comment]
Perf result is great for those that can be compiled. The timings for **futures** and **serde** are missing though.

http://perf.rust-lang.org/compare.html?start=61d88318aa66669fba061e9af529365172d63cd0&end=757cd050fc1ef84d7235d6f4d9228189eed878cc&stat=instructions%3Au

**Comment by Mark-Simulacrum** [comment]
Compilation failures for serde/futures:

Serde

```
thread 'main' panicked at 'region_obligations not empty: [
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#16r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#17r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#18r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#19r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#20r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#21r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#22r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#23r, sup_type=M)
    ),
    (
        NodeId(
            18904
        ),
        RegionObligation(sub_region='_#24r, sup_type=M)
    )
]', librustc/infer/mod.rs:1057:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (757cd050f 2018-06-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z borrowck=mir -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

thread 'main' panicked at 'assertion failed: cmd.status().expect("failed to spawn").success()', collector/src/bin/rustc-fake.rs:33:17
```

futures
```
thread 'main' panicked at 'region_obligations not empty: [
    (
        NodeId(
            3805
        ),
        RegionObligation(sub_region=ReStatic, sup_type=U)
    ),
    (
        NodeId(
            3805
        ),
        RegionObligation(sub_region=ReStatic, sup_type=U)
    )
]', librustc/infer/mod.rs:1057:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (757cd050f 2018-06-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z borrowck=mir -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

**Comment by nikomatsakis** [comment]
Interesting. Thanks!

**Comment by pnkfelix** [comment]
(FYI I plan to start my review on Tuesday June 12th)

**Comment by nikomatsakis** [comment]
Minimized failure:

```rust
struct Map<A, F> where A: Future {
    a: A,
    f: F,
}

trait Future {
    type Item;
    type Error;

    fn tailcall(&mut self) -> Option<Box<Future<Item=Self::Item, Error=Self::Error>>>;
}

impl<A, F, U> Future for Map<A, F>
where
    A: Future,
    F: FnOnce(A::Item) -> U + Send + 'static,
    U: Send + 'static,
{
    type Item = U;
    type Error = A::Error;

    fn tailcall(&mut self)
                -> Option<Box<Future<Item=Self::Item, Error=Self::Error>>> {
        None
    }
}

fn main() {}
```

I found the bug, it is a pre-existing weirdness in the NLL checker that I have to think about the best way to fix. =)

**Review by pnkfelix — COMMENTED** [review]
just from skimming 956e2f8348fae25d725adc0058c8156cc9be6ac2 I'll just say it would be nice if the `rustfmt` runs were isolated to their own commits...)

((I am now experimenting with "ignore whitespace changes" to try to deal with this...))

(((oh, apparently there are commits that *are* factored out `rustfmt` runs. maybe 956e2f8348fae25d725adc0058c8156cc9be6ac2 is just the result of IDE auto-indent...)))

**Comment by pnkfelix** [comment]
The PR seems fine from what I saw. (Obviously I must have missed something since there is the aforementioned bug that niko is working on.)

**Comment by nnethercote** [comment]
This gave some big perf wins for NLL perf, but also lots of smaller improvements for non-NLL builds:
http://perf.rust-lang.org/compare.html?start=862703e05e275d77b0b594bb5d1a26a6340933f2&end=b36917b33104dc0af4d26d53899b7cd064a40b22&stat=instructions:u

Nice work.

cc @rust-lang/wg-compiler-performance

**Pull request merged**
