### PR TITLE
Partial implementation for UFCS trait-less associated paths.

### LINKED ISSUE #22563: Don't require impls next to structs
tracking https://github.com/rust-lang/rfcs/pull/735

### PR DESCRIPTION
**Pull request by eddyb**
Adds `<module::Type>::method` support and makes `module::Type::method` a shorthand for it.
This is most of #16293, except that chaining multiple associated types is not yet supported.
It also fixes #22563 as `impl`s are no longer treated as modules in resolve.

Unfortunately, this is still a _[breaking-change]_:
- If you used a global path to a primitive type, i.e. `::bool`, `::i32` etc. - that was a bug I had to fix.
  Solution: remove the leading `::`.
- If you passed explicit `impl`-side type parameters to an inherent method, e.g.:

``` rust
struct Foo<T>(T);
impl<A, B> Foo<(A, B)> {
    fn pair(a: A, b: B) -> Foo<(A, B)> { Foo((a, b)) }
}
Foo::<A, B>::pair(a, b)
// Now that is sugar for:
<Foo<A, B>>::pair(a, b)
// Which isn't valid because `Foo` has only one type parameter.
// Solution: replace with:
Foo::<(A, B)>::pair(a, b)
// And, if possible, remove the explicit type param entirely:
Foo::pair(a, b)
```
- If you used the `QPath`-related `AstBuilder` methods @hugwijst added in #21943.
  The methods still exist, but `QPath` was replaced by `QSelf`, with the actual path stored separately.
  Solution: unpack the pair returned by `cx.qpath` to get the two arguments for `cx.expr_qpath`.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
very cool, I will read.

**Comment by nikomatsakis** [comment]
@eddyb sorry for being slow. I spent some time reading into this two days back but yesterday got very busy. I expect to finish up today.

**Comment by nikomatsakis** [comment]
First off, some nits here: https://github.com/nikomatsakis/rust/commit/b6461f069483ae6d00e3e706966ee9d7bac37f1e

**Comment by nikomatsakis** [comment]
r+, awesome! But I did have some conditions and comments :)

**Conditions:**

- [ ] Nits at https://github.com/nikomatsakis/rust/commit/b6461f069483ae6d00e3e706966ee9d7bac37f1e
- [ ] More new tests! Surely there are new constructions to test here? Some thoughts:
  - the fact that inherent takes precedence over trait
  - distinction between `Trait::method` and `<Trait>::method`
  - inherent impls are, I guess, extensively tested already, but there are probably some variations on them that you enable that didn't work right before, right?
  - can you rename `const-polymorphic-paths` to something like `ufcs-trait-relative-paths` or just anything that begins with `ufcs`? I'm pretty sure I'd never find it with the current name, and (iiuc) it tests more than just consts.
- [ ] A comment or two about PartialDef and what the heck `depth` means (in resolve_path and friends) would be nice.

**Comments/Questions:**

I still feel like a reworking of resolve and the data structures around resolve (notably, Path and Def) could yield substantially cleaner code, but this seems to be overall a pretty reasonable approach.

One thing I noticed that stuck out at me: in resolve, if parsing `a::b::c::d`, it seems that you first try to parse the entire path, then you drop segments from the RHS one by one (so next try `a::b::c`, then `a::b`, etc) until you find a hit. This seems remarkably inefficient. I am assuming that this was the easiest way to shoehorn this work on top of resolve -- is there a deeper reason for this approach?

I also found the "suppress errors" flag a little bit suboptimal, compared to passing back an error as a result, but it's a relatively minor thing. In general I'd like to see resolution refactored into a "side-effect-free" lookup that returns errors / successful results, leaving it to the caller to decide what to do with those.

I was happy to see you integrated the lookup into probe.

**Comment by nikomatsakis** [comment]
@eddyb ok, so I finished reviewing as of 43bac21. Let's call them *concerns*, for the most part -- more than nits, but certainly not blockers. Anyway, I'd appreciate clarification about the potential for ICEs etc. I'd like to have a change to look over the patch once you address them -- or tell me why I am wrong --- but promise to make it quick presuming major changes aren't needed.

**Comment by eddyb** [comment]
p=2

**Comment by Manishearth** [comment]
Retryable.

**Comment by Manishearth** [comment]
```
/home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/libstd/collections/hash/set.rs:1182:21: 1182:40 error: unable to infer enough type information about `_`; type annotations required [E0282]
/home/ubuntu/src/rust-buildbot/slave/auto-linux-64-nopt-t/build/src/libstd/collections/hash/set.rs:1182         let empty = HashSet::<i32>::new();
                                                                                                                            ^~~~~~~~~~~~~~~~~~~
```

Not sure what's wrong here.

**Comment by Manishearth** [comment]
Needs rebase.

**Pull request merged**
