### PR TITLE
Extract suitable code from rustc_query_impl into a new crate rustc_query_misc

### PR DESCRIPTION
**Pull request by Zoxc**
This extracts code from `rustc_query_impl` into a new crate `rustc_query_misc` in order to reduce the compile time of `rustc_query_impl`. The compile time of the new crate is roughly 60% of the remaining `rustc_query_impl` .

I've picked code which should not impact performance or result in duplicate generic code generation. Encoding and decoding of query results and profiling handling is moved along with some other minor methods which use dynamic dispatch.

r? @cjgillot

### CODE REVIEW

**Comment by cjgillot** [comment]
I'm not sure I understand the benefit. This crate is still on the critical path `middle -> query_misc -> query_impl`, so at worst we could lose some codegen parallelism.

**Comment by bjorn3** [comment]
Thanks to build pipelining cargo can invoke rustc for a dependent crate while dependencies are still busy with codegen. Only crate metadata writing needs to have finished.

**Comment by Zoxc** [comment]
It's a benefit when compiling with `codegen-units=1` since `rustc_query_impl` and `rustc_query_misc` can each get a core for code generation instead of `rustc_query_impl` being stuck on one. I use that configuration locally for performance benchmarks and CI should switch to that soon as it compiles faster and results in higher code quality.

**Comment by cjgillot** [comment]
> It's a benefit when compiling with `codegen-units=1` since `rustc_query_impl` and `rustc_query_misc` can each get a core for code generation instead of `rustc_query_impl` being stuck on one. I use that configuration locally for performance benchmarks and CI should switch to that soon as it compiles faster and results in higher code quality.

So we split the crate in 2 codegen units, to counteract the fact we ask for only 1?

The split does not follow a functional separation of the crate. The large macro is still there, structured the same way. How should we chose in which crate code goes?

Is there a way to get rid of the dependency between query_misc and query_impl?

**Comment by Zoxc** [comment]
> So we split the crate in 2 codegen units, to counteract the fact we ask for only 1?

Basically, but we can do it without a performance hit, unlike the automatic partitioning.
 
> The split does not follow a functional separation of the crate. The large macro is still there, structured the same way. How should we chose in which crate code goes?

In general, hot direct calls stays in the same crate, while cold or indirect calls can cross crate boundaries.

> Is there a way to get rid of the dependency between query_misc and query_impl?

Yes, but it's not very beneficial as they mostly spend their time in code generation. It's also would require another copy of the macro mentioned.

**Comment by Zoxc** [comment]
[Here's a link](https://htmlpreview.github.io/?https://gist.githubusercontent.com/Zoxc/04330a91b787e59a221ca3a02e1b7562/raw/d1a2b6cf9dfa61d5832a946f1f2d6250c07a201b/result.html) to the new compilation timings. `rustc_middle` is back on top as the biggest crate. `rustc_borrowck` is the new tail.

**Comment by cjgillot** [comment]
Making my review in https://github.com/rust-lang/rust/pull/115118#issuecomment-1704046548 more explicit.

I think this PR introduces complexity with no reason beyond bootstrap time.
The query system is already very complex. Splitting into an additional crate should be justified by a reduction in that complexity.

I would accept a PR splitting `rustc_query_impl` along logical / API boundaries.
Even better, moving code between `rustc_query_system` and `rustc_query_impl` to help modularisation and decoupling.

**Comment by apiraino** [comment]
Flipping the review switch to the author, I think there are some design questions [at this comment](https://github.com/rust-lang/rust/pull/115118#issuecomment-1749086393) on how to proceed.

@rustbot author

**Comment by JohnCSimon** [comment]
Ping from triage: 
@Zoxc - can you please address the questions form `@apiraino` ? Thank  you.

**Pull request closed without merging**
