### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
r? @oli-obk Assigning you, because something broke with ui_test:

```
tests/ui/crashes/ice-7272.rs FAILED:
command: "<unknown>"

A bug in `ui_test` occurred: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

full stderr:

```

(and that 103 times)

Thought I would ping you, before starting to investigate. Maybe you know what's going on.

### CODE REVIEW

**Comment by flip1995** [comment]
Oh, in that case r? @Manishearth

**Comment by flip1995** [comment]
Also a new crate pulled in for the `ui_test` update is [not (yet?) allowed](https://github.com/rust-lang/rust/actions/runs/5968131837/job/16191280416?pr=115183#step:24:1475):

```
tidy error: invalid license `Apache-2.0` in `distance 0.4.0 (registry+[https://github.com/rust-lang/crates.io-index)`](https://github.com/rust-lang/crates.io-index)%60)
```

**Comment by flip1995** [comment]
And here is the error output: https://github.com/rust-lang/rust/actions/runs/5968131837/job/16191280755?pr=115183#step:24:3115

**Comment by Manishearth** [comment]
r=me but looks like we have CI issues

**Comment by oli-obk** [comment]
Looks like I messed up something with aux file paths: https://github.com/oli-obk/ui_test/blob/a18ef37bf3dcccf5a1a631eddd55759fe0b89617/src/lib.rs#L479

**Pull request merged**
