### PR TITLE
Moved struct and method-syntax docs up

### PR DESCRIPTION
**Pull request by xaocon**
struct and impl are talked about quite a bit in the ownership triplet.
It makes sense to go over what they are prior to that section.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks @xaocon ! Unfortunately,  I'm not sure I want this change. Not because I disagree with what you're saying, but because these kind of ordering issues are more than just that. This order _was_ correct, but as stuff has been added over time, it's caused this kind of thing to happen, and I don't want to randomly just shuffle a few chapters every few releases.

However, I'm also working on the second draft, which just makes all of these problems go away. So it's not clear to me that it's worth the time to re-read the entire old book and fix this kind of thing up, either.

**Comment by xaocon** [comment]
No problem, was just rereading some sections and noticed that it seemed out of place. Let me know if I can do something to help with the new book.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/book is the repo, please give it a read and
file bugs if the current text is confusing :)

**Pull request closed without merging**
