### PR TITLE
Reland changes replacing num_cpus with available_parallelism 

### PR DESCRIPTION
**Pull request by the8472**
Since #97925 added cgroupv1 support the problem in #97549 which lead to the previous revert should be addressed now.

Cargo has reapplied the replacement too https://github.com/rust-lang/cargo/pull/10969

Reverts 1ae4b258267462da0b1aae1badcf83578153c799 (part of #97911)
Relands #94524

### CODE REVIEW

**Comment by jyn514** [comment]
> Since #97925 added cgroupv1 support the problem in #97549 which lead to the previous revert should be addressed now.

Is there some way to test this?

**Comment by the8472** [comment]
You need an older linux, e.g. debian 9. Or systemd configured to use cgroupv1 instead of v2 (the latter is the default in recent versions).

**Comment by jyn514** [comment]
Ok, sounds like you have a good idea of the trade-offs, I'm going to assume someone's tested this :)

I seen in Cargo.lock that we still have nums_cpus somewhere in the dependency tree, do you mind figuring out where that comes from? r=me with that done (I expect it will be in RLS or something, just want to make sure it's intentional).

**Comment by the8472** [comment]
Yes, there was some manual testing done in #97925 by ehuss and me.

num_cpus is still used in

* tools/build-manifest; via rayon
* clippy;  dev_depencency; via tokio and compiletest_rs
* tools/rust-installer;  direct dependency
* rls; direct dependency

**Pull request merged**
