### PR TITLE
Add internal accessor methods to io::{Chain, Take}.

### LINKED ISSUE #29067: Allow pub access to underlying 'Read' member of Take or Chain
I asked this as [a question on StackOverflow](http://stackoverflow.com/questions/33114619/access-to-components-of-a-read-wrapped-by-take-or-chain), and it was suggested that I raise an issue.

I'm writing a Rust implementation of the Google Brotli decompression algorithm, which uses a fixed number of "implicit zeroes" at the end of the stream to enable certain optimisations.

The Google C implementation does this using a spaghetti code of various counters, but I'd like to use the adaptors in the Rust std::io library instead. Something like:

``` rust
pub struct StreamBitReader<R> {
    reader: Chain<R,Take<Repeat>>,
    ...
}
```

where 'R' is the underlying `Read` that the bit reader struct is wrapping. However, there are a number of cases where the decompression algorithm checks to see if it has "overrun" the stream, and it does this by checking the number of implicit zero bytes that have been read. This appears to be impossible in safe Rust, as there is no way to obtain a reference to the underlying components of `Chain`, unless I'm missing something.

When `Chain` is constructed, it takes ownership of (moves) the two `Read` structs, which then are hidden in private members.

Is there any way to construct the `Take<Repeat>` part such that I can continue to access the `limit()` fn of `Take` even after the `Chain` adaptor takes ownership?

If not, then there ought to be either public members or functions that allow access to the base Read members of all such adaptors, to allow this type of code.

### PR DESCRIPTION
**Pull request by SergioBenitez**
Resolves #29067.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me, thanks!

Could you also be sure to document on the `get_mut` case that care should be taken to not corrupt the stream? (e.g. doing your own reads/writes may mess up the internal state of these structs).

Other than r=me. Can you file a tracking issue and cc me? I'll be sure to tag it appropriately

**Comment by SergioBenitez** [comment]
Awesome, thanks @alexcrichton!

r=alexcrichton

**Comment by aturon** [comment]
@bors: r=alexcrichton

(Need r+ rights for this).

**Comment by SergioBenitez** [comment]
Ah, that makes sense. :) Thanks!

**Comment by alexcrichton** [comment]
@bors: r-

oh looks like some of the issue references are still `="0"`? though?

**Comment by alexcrichton** [comment]
oops didn't mean to close

**Comment by SergioBenitez** [comment]
Ah, of course! Did indeed forget those. They're in now.

**Pull request merged**
