### PR TITLE
Undo whitespace tweaks pending libbacktrace merge

### PR DESCRIPTION
**Pull request by mmcco**
These should probably be submitted upstream. They're inevitably going to
complicate merges, and because they're non-functional changes this just
isn't worth our time.

### CODE REVIEW

**Comment by eddyb** [comment]
@bors r-

Maybe we should wait on https://gcc.gnu.org/ml/gcc-patches/2016-01/msg00063.html.

**Comment by mmcco** [comment]
Agreed. I'll be far from shocked if that patch is ignored or rejected, but it's worth a shot.

**Comment by aarzee** [comment]
Sorry to see that these changes were causing issues :(, FWIW I'm entirely okay with them being reverted.

**Comment by mmcco** [comment]
At this point, I think we should merge this PR and reapply the whitespace fixes if upstream eventually accepts them. When that happens, I'll submit a PR to pull new changes from upstream.

**Pull request merged**
