### PR TITLE
Refactor linker code

### PR DESCRIPTION
**Pull request by bjorn3**
This merges `LinkerInfo` into `CrateInfo` as there is no reason to keep them separate. `LinkerInfo::to_linker` is merged into `get_linker` as both have different logic for each linker type and `to_linker` is directly called after `get_linker`. Also contains a couple of small cleanups.

See the individual commits for all changes.

### CODE REVIEW

**Comment by petrochenkov** [comment]
r=me with fulldeps tests fixed.

**Comment by bjorn3** [comment]
I would like to do a perf run first. I have been bitten by a perf regression during refactorings more than once.

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
Mostly improvements up to 0.7%. Only a couple regressions up to 0.4%.

**Comment by nagisa** [comment]
I would like to see the commit messages expanded with more of "why" in addition to "what". For example, what is the motivation to move `LinkerInfo` into `CrateInfo`? I would also like to see some discussion on why this is the overall direction we want to be taking.

**Comment by petrochenkov** [comment]
I think the changes are reasonable because `LinkerInfo` generally doesn't make sense as a separate structure.

Yes, it contains some pre-computed properties of the compilation session used when building linker invocation, but it's not clear why they should be separated from similar properties from (maybe misnamed) `CrateInfo`.

**Comment by nagisa** [comment]
Yeah I don't mean to push back against the changes it's just something that
makes it easier to understand them. Something like your comment is pretty
good and I think it's worthwhile to at least copy it over to the pr
description so that it at least ends up in the merge commit.

**Comment by bjorn3** [comment]
Edited the PR description to describe the reason behind some changes.

**Pull request merged**
