### PR TITLE
Manually run `clang-format` on `CoverageMappingWrapper.cpp`

### PR DESCRIPTION
**Pull request by Zalathar**
In the current version of #123409, there are several unrelated changes to `CoverageMappingWrapper.cpp` that seem to be the result of running `clang-format` on that file.

Instead of asking for those changes to be undone, I figure it's easier to just make them myself as a separate PR, since I was vaguely intending to do that at some point anyway.

In a few cases I've strategically added comments to make the grouping of parameters a little nicer, but mostly it doesn't matter much.

### CODE REVIEW

**Comment by Lambdaris** [comment]
Is it possible to add a .clang-format file to configure the whole llvm-wrapper? The exists code does not fit any preset styles of clang-format. I have asked at discord but get no response about what code convention the cpp code follows.

**Comment by Zalathar** [comment]
> Is it possible to add a .clang-format file to configure the whole llvm-wrapper? The exists code does not fit any preset styles of clang-format. I have asked at discord but get no response about what code convention the cpp code follows.

In my experience, the Discord is not very active for that sort of thing. You are more likely to get a response [on Zulip](https://forge.rust-lang.org/platforms/zulip.html).

Currently there is no automated system to format the C++ code (or check the formatting), so it tends to drift away from clang-format style until someone decides to manually clean it up again.

**Pull request merged**
