### PR TITLE
Render locals and their types in graphviz dataflow results

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Based on the existing logic in https://github.com/rust-lang/rust/blob/537ccdf3ac44c8c7a8d36cbdbe6fb224afabb7ae/src/librustc_mir/util/graphviz.rs#L167-L207.

### CODE REVIEW

**Comment by cramertj** [comment]
Do we have tests for the graphviz construction? If so, can we extend them to include coverage for this?

**Comment by ecstatic-morse** [comment]
`libgraphviz` has a few tests, yes. What would we be testing for?

**Comment by cramertj** [comment]
The new labels and text that this PR adds.

**Comment by ecstatic-morse** [comment]
I don't think it's necessary to test the exact output of diagrams that are only used for debugging. We can open an `E-easy` issue calling for tests, or we can close this PR and I'll just use it locally.

**Comment by Dylan-DPC** [comment]
Closing this pr due to inactivity (and per last comment)

**Pull request closed without merging**
