### PR TITLE
Allow redirecting subprocess stdout to our stderr etc. (redux)

### PR DESCRIPTION
**Pull request by ijackson**
This is the code from #88561, tidied up, including review suggestions, and with the for-testing-only CI commit removed.  FCP for the API completed in #88561.

I have made a new MR to facilitate review.  The discussion there is very cluttered and the branch is full of changes (in many cases as a result of changes to other Rust stdlib APIs since then).  Assuming this MR is approvedl we should close that one.

### Reviewer doing a de novo review

Just code review these four commits..  FCP discussion starts here: https://github.com/rust-lang/rust/pull/88561#issuecomment-1640527595

Portability tests: you can see that this branch works on Windows too by looking at the CI results in #88561, which has the same code changes as this branch but with an additional "DO NOT MERGE" commit to make the Windows tests run.

### Reviewer doing an incremental review from some version of #88561 

Review the new commits since your last review.  I haven't force pushed the branch there.

git diff the two branches (eg `git diff 176886197d6..0842b69c219`).  You'll see that the only difference is in gitlab CI files.  You can also see that *this* MR doesn't touch those files.

### CODE REVIEW

**Comment by pitaj** [comment]
I can understand splitting the refactor out from the rest, but I would recommend squashing the first, third, and fourth commits together since they each touch a different file and are tightly linked.

**Comment by pitaj** [comment]
> #88561 as initially submitted had the same commit structure and the maintainers didn't seem to object to it then

I don't think that really means anything. I don't think they care about commit structure at all until the very end, where they might ask for everything to be squashed.

> (When I'm a reviewer, I generally prefer the commits as small as possible.  It's always possible to review successive commits together if the submitter has split them up; whereas if the submitter has merged them, I can only review them in that form or ask for a resubmission.)

The way I see it commits 1, 3, and 4 are all part of the same change. Neither 1 nor 3 make sense without 4, so they should be combined. I would never have committed them separately in the first place.

But that's just my suggestion. Keep it how you like it.

**Review by dtolnay — APPROVED** [review]
Thank you! This is terrific.

T-libs-api FCP has completed in https://github.com/rust-lang/rust/pull/88561#issuecomment-1665727385.

Thank you for sticking with this over 2 years :open_mouth::clap: while our team has been so backlogged -- we're starting to make better progress again recently.

**Comment by ijackson** [comment]
Thanks for the review and the encouragement.

I've fixed WASM (with some flail).  Please LMK when you want me to squash this.  Hopefully it will turn out not to break some other platform too.

@rustbot reviewer

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
