### PR TITLE
Update hashbrown from 0.12.3 to 0.13.1 for std

### PR DESCRIPTION
**Pull request by Urgau**
This PR updates hashbrown from 0.12.3 to 0.13.1 for std.

r? @Amanieu

### CODE REVIEW

**Comment by Amanieu** [comment]
Looks like an overall improvement! However I'm planning on releasing version 0.14 soon (in the coming week hopefully) so maybe let's wait for that.

**Comment by Urgau** [comment]
> Looks like an overall improvement! However I'm planning on releasing version 0.14 soon (in the coming week hopefully) so maybe let's wait for that.

As you wish. I don't see any harm in waiting but I also don't see any harm in landing this now.

**Comment by Amanieu** [comment]
Fair enough.

@bors r+ rollup=never

**Pull request merged**
