### PR TITLE
Copyright years update

### PR DESCRIPTION
**Pull request by dnaeon**
This PR updates the copyright years.

Actual script used for generating the copyright years based on the Git commit logs can be found below.

``` bash
#!/usr/bin/env sh                                                                                                                                                              

PATTERN='// Copyright ([0-9\-]*) The Rust Project Developers. See the COPYRIGHT'                                                                                               
REPO_SRC='/home/mnikolov/PROJECTS/rust/src'                                                                                                                             

for f in $( egrep --recursive --files-with-matches "${PATTERN}" "${REPO_SRC}" ); do                                                                                            
    last_copyright_year=$( egrep "${PATTERN}" ${f} | awk '{ print $3 }' )                                                                                                      
    last_commit_year=$( git log -1 ${f} | grep 'Date' | awk '{ print $6 }' )                                                                                                   
    if [ "${last_copyright_year}" != "${last_commit_year}" ]; then                                                                                                             
        first_year=$( echo "${last_copyright_year}" | cut -d '-' -f 1 | sed -e 's|-||g' )                                                                                      
        new_copyright_year="${first_year}-${last_commit_year}"                                                                                                                 
        echo "Updating copyright years for ${f} to ${new_copyright_year} ..."                                                                                                  
        sed -i "s|Copyright ${last_copyright_year}|Copyright ${new_copyright_year}|g" ${f}                                                                                     
    fi                                                                                                                                                                         
done
```

### CODE REVIEW

**Comment by dnaeon** [comment]
Build fails because of incorrect license, although license appears to be correct.

```log
cfg: no pandoc found, omitting PDF and EPUB docs
cfg: including test rules
cfg: javac not available, skipping lexer test...
check: formatting
/home/travis/build/rust-lang/rust/src/test/run-pass/issue-9382.rs:1: incorrect license
```

Any ideas why license appears as incorrect?

**Comment by dnaeon** [comment]
License header fixed, test passed.

**Comment by frewsxcv** [comment]
Relevant discussion from a few months ago:

https://github.com/rust-lang/rust/issues/9070

in particular:

https://github.com/rust-lang/rust/issues/9070#issuecomment-72514411

**Comment by dnaeon** [comment]
@frewsxcv I wasn't aware that this has been discussed already, thanks for the links. I think we can close this PR.

**Pull request closed without merging**
