### PR TITLE
rollup of the error explanation patches

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
See #26396, #26400, #26399, #26398 and #26393.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Loving your work @GuillaumeGomez !

**Comment by GuillaumeGomez** [comment]
@michaelsproul; And it [continues](https://github.com/GuillaumeGomez/rust/commit/49bd3ef6466bc12e44da4f7c556b167e7564501e) !

**Pull request merged**
