### PR TITLE
Add Iterator::at_least() and Iterator::at_most() API

### PR DESCRIPTION
**Pull request by Folyd**
`at_least()` and `at_most()` are similar to `any()` and `all()`, these two methods test if at least/most `n` elements of the iterator matches a predicate. 

Although, we can simply use `iter.filter().count() > n` , `at_least()` and `at_most()` are short-circuiting, so it's more effecency than the simple filter in most cases.

I have created a benchmark project to demonstrate three versions of `at_least`, here is the [repository link](https://github.com/Folyd/iter-enhancement).

### CODE REVIEW

**Comment by the8472** [comment]
> Although, we can simply use `iter.filter().count() > n` , `at_least()` and `at_most()` are short-circuiting, so it's more effecency than the simple filter in most cases.

Well, that effect could also be achieved by adding a `take(n)` before the `count()`.

**Comment by Folyd** [comment]
@the8472 TIL. Good point. Thanks. 😄 

So I'm wondering why the implementation of `std::iter::any()` is based on `ControlFlow` ranther than something like `filter(|f| f()).take(1).count() > 0`?

**Comment by crlf0710** [comment]
Triage: There's merge conflicts now. @Folyd

**Comment by m-ou-se** [comment]
@Folyd Thanks for your PR!

Do you have some motivating examples? While `.any()` and `.all()` seem like very common operations to me, I can't think of many common situations where `.at_least()` and `.at_most()` would be used. Considering the very large amount of methods we  already have on `Iterator` and that `.filter().take()` already suffices in most (all?) of those situations, I'm hesitant to merge this.

**Comment by Folyd** [comment]
> @Folyd Thanks for your PR!
> 
> Do you have some motivating examples? While `.any()` and `.all()` seem like very common operations to me, I can't think of many common situations where `.at_least()` and `.at_most()` would be used. Considering the very large amount of methods we already have on `Iterator` and that `.filter().take()` already suffices in most (all?) of those situations, I'm hesitant to merge this.

Thanks, @m-ou-se. I agree with you. Let's close this. 👌

**Pull request closed without merging**
