### PR TITLE
Record query name when profiling "metadata_decode_entry"

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Aaron1011** [comment]
cc @Mark-Simulacrum: It is possible to get this to show up on perf.rust-lang.org?

**Comment by Mark-Simulacrum** [comment]
I don't think so. We could just concat! the query name though (e.g., metadata_decode_item_attrs)

**Comment by Aaron1011** [comment]
@Mark-Simulacrum: I've updated the PR to use `concat!`

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue include=helloworld

(Testing out new subset functionality; we shouldn't need a full build to test that this does what we expect)

**Comment by Mark-Simulacrum** [comment]
Looks like it's working, see for example https://perf.rust-lang.org/detailed-query.html?sort_idx=-5&commit=7534f1a4e75fd5e77b5db839bf19bb120e72935e&benchmark=helloworld-opt&run_name=full

I think this will indeed be useful to determine if regressions are coming from metadata loading or not -- right now it's hard to tell. We might even want to do some post-processing within perf to put these in a separate column, but I'm not sure about that.

@bors r+

**Pull request merged**
