### PR TITLE
Mark `f16` and `f128` as incomplete features

### PR DESCRIPTION
**Pull request by tgross35**
See https://github.com/rust-lang/rust/issues/116909#issuecomment-2227514184.

Unfortunately this will probably have a lot that needs to be updated, just getting this started to figure out exactly what that will be.

r? @scottmcm

### CODE REVIEW

**Comment by tgross35** [comment]
Is there any guideline for what constitutes an incomplete feature? The ABI issues and maybe missing symbols definitely seem to qualify this, but it seems that a missing trait impl/method relative to f32 & f64 (as per the original comment) wouldn't necessarily be in the same boat.

**Comment by tgross35** [comment]
I just saw that, but it looks like this is enabled in `core` so maybe it's okay? It is a bit unfortunate that you can't enable a specific list of incomplete features, since the reason they are incomplete is quite a range.

**Comment by workingjubilee** [comment]
Mmh.

**Comment by workingjubilee** [comment]
Please open a bug for "incomplete features that std should not depend on" vs. "incomplete features that std... has to implement..." and cc Boxy and Nils about it.

**Comment by tgross35** [comment]
Good idea, opened https://github.com/rust-lang/rust/issues/127741

**Comment by tgross35** [comment]
Unfortunately clippy uses these features too so that's another `allow(incomplete_features)` :(

**Comment by tgross35** [comment]
Ah, GH doesn't like me fixing a typo in my branch name. Reopened at https://github.com/rust-lang/rust/pull/127743

**Pull request closed without merging**
