### PR TITLE
look for python2 symlinks before bootstrap python

### PR DESCRIPTION
**Pull request by euclio**
Before this commit, if you're running x.py directly on a system where
`python` is symlinked to Python 3, then the `python` config option will
default to a Python 3 interpreter. This causes debuginfo tests to fail
with an opaque error message, since they have a hard requirement on
Python 2.

This commit modifies the Python probe behavior to look for python2.7 and
python2 *before* using the interpreter used to execute `x.py`.

### CODE REVIEW

**Comment by euclio** [comment]
Spurious network failure.

**Comment by alexcrichton** [comment]
Unfortunately I don't think that's spurious, I think that may be LLVM selecting a different (and incompatible) python for its build.

**Comment by euclio** [comment]
I see. I wonder if it's sufficient to blacklist the msys pythons, or to prefer `BOOTSTRAP_PYTHON` only for msys?

**Comment by alexcrichton** [comment]
Yeah I think the issue is that something like the msys python is being used (which is first in PATH) instead of the system python which we prefer (or something like that). I don't personally have a preference for how it's best solved.

**Comment by mati865** [comment]
What about changing shebang to `#!/usr/bin/env python2`?

**Comment by euclio** [comment]
@mati865 I think that would break `./x.py` for MacOS users, since they don't have a python2 symlink by default. `python2.7` could potentially work, but it's a little misleading.

**Comment by euclio** [comment]
Added some debug code to appveyor. Is it possible to run appveyor via try run or do I need an r+?

**Comment by mati865** [comment]
@euclio Appveyor doesn't check `try` runs but you can run Appveyor build on your fork.

**Comment by euclio** [comment]
@alexcrichton Found and fixed a bug in the PATH probing on Windows. Should be ready for another go.

@mati865 Thanks for the help!

**Comment by euclio** [comment]
Spurious, #58160.

**Pull request merged**
