### PR TITLE
FromIterator and Extend Cow for String

### PR DESCRIPTION
**Pull request by Eh2406**
This is a quick draft to start working on [#41351](https://github.com/rust-lang/rust/issues/41351).
I don't think I got the stable attributes correct, but it is good enuf to start a conversation.

### CODE REVIEW

**Comment by mrhota** [comment]
@Eh2406 can you respond to the comment on the linked issue? Why not `impl FromIterator<Borrow<str>> for String`?

**Comment by jmesmon** [comment]
On the stability attributes: Trait impls are (unfortunately) still insta-stable, they ignore stability attributes.

**Comment by Eh2406** [comment]
I'd love to use the more generic version. It will replace all existing impls. Do we just throw out the stability feature and versions?

**Comment by Eh2406** [comment]
char can not impl Borrow<str> thus the generic does not cover existing stable uses, but rust does not know that it will never impl it so it won't let us have the generic and the specific.

**Comment by Eh2406** [comment]
[leaving the impls for char](https://github.com/rust-lang/rust/pull/41454/commits/6563f4ab79885666cd8602f2e954e911d2477bc6) in lead to 
[conflicting implementations of trait `core::iter::FromIterator<char>`](https://travis-ci.org/rust-lang/rust/jobs/224577594#L782)

**Comment by Eh2406** [comment]
and if I [remove the impls for char](https://github.com/rust-lang/rust/pull/41454/commits/c215565557c88dc0aa62ea0982ebb9eefebaff1e) it corectly points out that [the trait `core::borrow::Borrow<str>` is not implemented for `char`](https://travis-ci.org/rust-lang/rust/jobs/224580077#L785). So I don't see how to do this genericly.

**Comment by jmesmon** [comment]
hmm, that is a shame about the conflicts. Can specialization be used here to allow this? (And I suppose the follow up is: do we want to use specialization for this case).

**Comment by Eh2406** [comment]
[conflicting implementations](https://travis-ci.org/rust-lang/rust/jobs/225302621#L780) but this is my ferst use of specialization. Did I use it wrong?

**Comment by arielb1** [comment]
Thanks for the PR! We'll make sure that @aturon (or someone else) helps you with the specialization and reviews this.

r? @aturon

**Comment by aturon** [comment]
Specialization can't be used to tackle this problem, because `char` does not implement the necessary trait (and hence the impl isn't a specialization).

The core problem is as @Eh2406 identified, which is that Rust is trying to defend against a future where `char` does impl the trait (this happens because `char` is defined in `core` while this impl must live in `std`).

I think this is the best we can do for the time being. Can you update the version numbers on the stability attributes, to 1.19?

Otherwise, r=me.

**Comment by Eh2406** [comment]
Fixed, rebased, and squashed.

**Comment by aturon** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
