### PR TITLE
Use "x86-64" as the target CPU for NetBSD and Bitrig on amd64.

### PR DESCRIPTION
**Pull request by jakllsch**
Using "generic" disables a number of features that are present on all
x86_64 cpus, the "x86-64" target cpu is the common denominator for that
arch.

Refs #20777

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I'm curious though, why not do this for all targets?

**Comment by jakllsch** [comment]
"All"?  As far as I can tell it's already been done for every other x86_64-based system. The Apple ones use "core2" instead of "x86-64".  On NetBSD there's a SSE-related test case failure this fixes because LLVM uses the generic lowest-common-denominator x86 instead of x86_64 which inherently has SSE2.

**Comment by nagisa** [comment]
I feel like it is a bug in LLVM that `generic` for `x86_64` is not `x86_64`, but otherwise I’m not opposed to this PR.

**Comment by alexcrichton** [comment]
@bors: r+ 1f86005fc09eceb6b19507c466b9674013425521

Ah ok, thanks! I didn't realize we'd already done this for other targets, and sounds like good motivation to me.

**Pull request merged**
