### PR TITLE
Warn if encountering infer variables when calculating generator interiors

### PR DESCRIPTION
**Pull request by Zoxc**
I'd like to turn this warning into an error to facilitate constructing MIR for computing generator interiors. It would be useful to know if there are any use cases which trigger this warning.

r? @arielb1

### CODE REVIEW

**Comment by arielb1** [comment]
@Zoxc

I think normal unresolved variables will cause a warning in your case - before the final `select_all_obligations_or_error` call:
```Rust
let x = None;
```

This of course causes an error later on, but we don't want the spurious warning.

**Comment by Zoxc** [comment]
You'd need to put that in a generator ;)

I changed to code to emit the warning later, if no errors occurred.

**Comment by alexcrichton** [comment]
ping @arielb1, I think this is good for another go!

**Comment by aidanhs** [comment]
Ping @arielb1 for review! Or, perhaps there's another reviewer @rust-lang/compiler could choose?

**Comment by arielb1** [comment]
Sorry for the delay.

I don't see how this pass fits within our picture of split typeck and MIR-based inference. In particular:
1. After MIR regionck lands, the writeback pass will be done before regionck, so generator inference could probably most naturally take place "at the same place as constant promotion", just before region checking.
2. After that, writeback will already ensure there are no type variables anywhere.
3. Currently, the code can cause errors if an inference variable is only resolved by generator inference, e.g.
    ```Rust
    trait Trait { fn foo(self); }
    impl<T: Sync> Trait for (T, u32) {}
    impl<T> Trait for (T, u64) {}
    (|| { yield; }, Default::default()).foo();
    ```
    With the new pass system, that would be a writeback error, because the inference variable can't be resolved without knowing whether the generator is `Sync` or not.

**Pull request closed without merging**
