### PR TITLE
update clippy to fix toolstate

### LINKED ISSUE #62558: Tools are not available on cross compiled platforms since #61861
Moved from https://github.com/rust-lang/rust-clippy/issues/4267

#61861 was merged in #61962, since then Rustfmt fails to build when cross compiling which is the case for almost all non Tier 1 platforms.
Clippy and RLS are failing with similar error.

Error on `aarch64-unknown-linux-gnu`:
```
[01:14:03] error[E0464]: multiple matching crates for `rustc_macros`
[01:14:03]   --> /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_target-491.0.0/abi/mod.rs:10:5
[01:14:03]    |
[01:14:03]    | use syntax_pos::symbol::{sym, Symbol};
[01:14:03]    |     ^^^^^^^^^^
[01:14:03]    |
[01:14:03]    = note: candidates:
[01:14:03]            crate `rustc_macros`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_macros-97bf1e9c420f9886.so
[01:14:03]            crate `rustc_macros`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/release/deps/librustc_macros-2f4546e1163449fb.so
[01:14:03] 
[01:14:03] error[E0461]: couldn't find crate `rustc_macros` with expected target triple x86_64-unknown-linux-gnu which `syntax_pos` depends on
[01:14:03]   --> /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_target-491.0.0/abi/mod.rs:10:5
[01:14:03]    |
[01:14:03] 10 | use syntax_pos::symbol::{sym, Symbol};
[01:14:03]    |     ^^^^^^^^^^
[01:14:03]    |
[01:14:03]    = note: the following crate versions were found:
[01:14:03]            crate `rustc_macros`, target triple aarch64-unknown-linux-gnu: /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/aarch64-unknown-linux-gnu/release/deps/librustc_macros-55389246a2ce204b.so
[01:14:03] 
[01:14:03] error: aborting due to 2 previous errors
```
https://api.travis-ci.com/v3/job/209363492/log.txt

@rustbot modify labels: T-dev-tools A-rustbuild

### LINKED ISSUE #66150: `clippy-driver` no longer builds after rust-lang/rust#66143
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#66143, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by tesuji**
Close #66150.
Close #62558 thanks to @msizanoen1 .

### CODE REVIEW

**Comment by lzutao** [comment]
cc @msizanoen1 in case they are interested.

**Comment by Manishearth** [comment]
This is because some of our tests import `clippy_lints` 

@Mark-Simulacrum we've got some tests for internal lints so we'd like to keep doing this, is there a way for us to continue to `extern crate clippy_lints` without triggering this error?

**Comment by Manishearth** [comment]
Opened https://github.com/rust-lang/rust-clippy/pull/4784 , however this means that we're unable to test internal lints.

Is there a reason why clippy is getting loaded as a plugin there? I can't reproduce this locally with rustup-tooclhain-install-master.

**Comment by msizanoen1** [comment]
I think I know why: the deprecated clippy plugin causes clippy_lints to be build twice - once in the host deps directory and the target deps directory.
After the plugin removal, clippy_lints is only built once into the target deps directory. However clippy tests expect it to be in the host deps directory.

**Comment by Manishearth** [comment]
The best path forward might be to only run the internals test on our CI and
not rust

**Comment by lzutao** [comment]
Could we add a new feature gate in clippy_lints for solely testing?

**Comment by msizanoen1** [comment]
How about this:
```diff
diff --git a/src/bootstrap/test.rs b/src/bootstrap/test.rs
index 60f0dccdb07..76a5c88b5f0 100644
--- a/src/bootstrap/test.rs
+++ b/src/bootstrap/test.rs
@@ -569,6 +569,7 @@ impl Step for Clippy {
             cargo.env("RUSTC_LIB_PATH", builder.rustc_libdir(compiler));
             let host_libs = builder
                 .stage_out(compiler, Mode::ToolRustc)
+                .join(&self.host)
                 .join(builder.cargo_dir());
             cargo.env("HOST_LIBS", host_libs);
             // clippy tests need to find the driver
```

**Comment by lzutao** [comment]
Testing this patch locally.

**Comment by lzutao** [comment]
It still failed with another error:
```diff
diff of stderr:

+error[E0463]: can't find crate for `clippy_mini_macro_test`
+  --> $DIR/procedural_macro.rs:4:1
+   |
+LL | extern crate clippy_mini_macro_test;
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
+
+error: aborting due to previous error
+
+For more information about this error, try `rustc --explain E0463`.
+
```

**Comment by msizanoen1** [comment]
rust-lang/rust-clippy#4786

**Comment by msizanoen1** [comment]
Wait, some change in rustc has broke clippy again: https://api.travis-ci.com/v3/job/253927833/log.txt

**Comment by msizanoen1** [comment]
Some change in rustc broke clippy again: https://travis-ci.com/rust-lang/rust-clippy/jobs/253927833

**Comment by msizanoen1** [comment]
rust-lang/rust-clippy#4787

**Comment by msizanoen1** [comment]
needs rust-lang/rust-clippy#4755

**Comment by lzutao** [comment]
Blocked on rust-lang/rust-clippy#4786

**Comment by Manishearth** [comment]
superseded by https://github.com/rust-lang/rust/pull/66207

**Pull request closed without merging**
