### PR TITLE
 Experiment: New fmt::Arguments implementation (2021)

### PR DESCRIPTION
**Pull request by m-ou-se**
Just testing some incomplete idea.

### CODE REVIEW

**Comment by bjorn3** [comment]
Up to 9.3% improvement for helloworld-opt incr-patched and up to 8.4% regression for webrender-wrench-check incr-patched. For full builds many regressions up to 6.8% and some improvements up to 2.0%.

**Comment by m-ou-se** [comment]
Yeah these results are all over the place. Not sure why.

fmt::Arguments was reduced from 6 pointers to 2 pointers in size, and the output of format_args!() didn't really change much in complexity.

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and close this since it seems like it's not likely to receive much further attention.

**Pull request closed without merging**
