### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #106699 ([drop tracking] Visit break expressions )
 - #106738 (Fix known-bug annotations)
 - #106891 (Tweak "borrow closure argument" suggestion)
 - #106928 (add raw identifier for keyword in suggestion)
 - #107065 (Clippy: Make sure to include in beta: Move `unchecked_duration_subtraction` to pedantic)
 - #107068 (autoderive Subdiagnostic for AddtoExternBlockSuggestion)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=106699,106738,106891,106928,107065,107068)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors retry
warning: spurious network error (2 tries remaining): failed to get successful HTTP response from `[https://crates.io/api/v1/crates/bitflags/1.3.2/download`](https://crates.io/api/v1/crates/bitflags/1.3.2/download%60), got 502

**Comment by GuillaumeGomez** [comment]
Isn't it unneeded now that there is #107105?

**Comment by matthiaskrgr** [comment]
@GuillaumeGomez  there are no overlapping PRs in these two :)

**Comment by GuillaumeGomez** [comment]
Oh indeed. Nevermind!

**Pull request merged**
