### PR TITLE
Rollup of 15 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #58021 (Fix fallout from #57667)
 - #58788 (Make migrate mode work at item level granularity)
 - #58789 (Update compiler_builtins to 0.1.7 to get windows/arm fix)
 - #58829 (librustc_interface: Update scoped-tls to 1.0)
 - #58848 (Prevent cache issues on version updates)
 - #58855 (std: Spin for a global malloc lock on wasm32)
 - #58872 (Adds help message in error for invalid `impl for T` syntax)
 - #58876 (Parse lifetimes that start with a number and give specific error)
 - #58938 (core: ensure VaList passes improper_ctypes lint)
 - #58941 (MIPS: add r6 support)
 - #59035 (When encountetring `||{}()`, suggest the likely intended `(||{})()`)
 - #59036 (Fix ICE in MIR pretty printing)
 - #59047 (resolve: Account for new importable entities)
 - #59056 (Use lifetime contravariance to elide more lifetimes in core+alloc+std)
 - #59072 (we can now skip should_panic tests with the libtest harness)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Centril** [comment]
I have zero clues as to why this is happening... cc @pietroalbini

**Comment by pietroalbini** [comment]
Wut. cc @rust-lang/rustdoc

**Comment by ollie27** [comment]
Caused by #58848.

**Comment by GuillaumeGomez** [comment]
#58848 needs to be merged after #58330.

**Comment by GuillaumeGomez** [comment]
It needs to be merged after #58330.

**Pull request closed without merging**
