### PR TITLE
Fix generic const order display in rustdoc

### LINKED ISSUE #61292: Send/Sync type parameters come after const parameters in docs
https://github.com/rust-lang/rust/blob/721268583759224d0f6476e0b8b196cc8afbdea0/src/test/rustdoc/generic-const.rs#L12-L13
Const parameters should always be trailing (at least with respect to type/lifetime parameters). I'm not sure whether this is specifically a rustdoc issue or not yet.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #61292.

r? @varkor

### CODE REVIEW

**Comment by varkor** [comment]
This corrects the order in rustdoc, but what is the underlying order in rustc? Is the reason the parameters aren't in the correct order a problem before it gets to rustdoc at all? If so, we should fix it at an earlier point.

**Comment by GuillaumeGomez** [comment]
I'm not completely sure about it. Also, is the generic parameters order important for rust internals? I'll check if it comes from rustdoc but I think it comes from the internals. If so, I'll just update the internals directly.

**Comment by varkor** [comment]
At the moment, the internal order is important, though eventually we'd like to change this: https://github.com/rust-lang/rust/issues/61334. I think rustdoc should be faithful to the internals, so that's where we should fix the issue if that's where it's originating.

**Comment by GuillaumeGomez** [comment]
Update: Still need to look into the internals.

**Comment by joelpalmer** [comment]
Hi @GuillaumeGomez, this is a ping from Triage. Please provide an update on this PR at your earliest convenience.

**Comment by GuillaumeGomez** [comment]
Still need to start digging in the compiler. Not much time currently though.

**Comment by varkor** [comment]
Maybe it'd be worth closing this pull request, as a proper fix is going to look quite different anyway.

**Comment by GuillaumeGomez** [comment]
Indeed. Let's close it then!

**Pull request closed without merging**
