### PR TITLE
Fix extern prelude failure in rustdoc

### LINKED ISSUE #50561: extern_prelude check is breaking rustdoc
See https://github.com/rust-lang-nursery/futures-rs/pull/1003#issuecomment-387658833

```
 Documenting futures-channel v0.2.1 (file:///home/travis/build/rust-lang-nursery/futures-rs/futures-channel)
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  |
  = help: add #![feature(extern_prelude)] to the crate attributes to enable
error: Could not document `futures-channel`.
Caused by:
  process didn't exit successfully: `rustdoc --crate-name futures_channel futures-channel/src/lib.rs -o /home/travis/build/rust-lang-nursery/futures-rs/target/doc --cfg feature="default" --cfg feature="futures-core" --cfg feature="std" -L dependency=/home/travis/build/rust-lang-nursery/futures-rs/target/debug/deps --extern futures_core=/home/travis/build/rust-lang-nursery/futures-rs/target/debug/deps/libfutures_core-c5293a3c307e0c7b.rmeta` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #50561.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by Manishearth** [comment]
Well, actually_rustdoc doesn't handle the difference between resolution that rustdoc has to do for compilation vs resolution for intra doc links.

**Comment by QuietMisdreavus** [comment]
Hmm, that's a good point, since this PR currently only enables the setting *after* the rest of the crate has passed resolution.

Still, i'm wondering whether there's a "proper" fix that's not "disable this check during intra-link resolution". What's actually going on here?

**Comment by Manishearth** [comment]
Actually the proper fix is make it such that we hit that call with record_used=true, since record_used is also "is this a speculative resolution" which is true in this case. Perhaps rename the parameter while you're at it.

Elsewhere I've proposed a more coherent abstraction for paths that also includes speculation but it's currently stalled on a decision from compiler folks think.

**Comment by pietroalbini** [comment]
Ping from triage @QuietMisdreavus! This PR needs your review.

**Comment by QuietMisdreavus** [comment]
I think we still needed to discuss what it would take to get to the solution @Manishearth mentioned. I'm not a fan of adding a new flag just to toss it into an existing if-clause somewhere.

**Comment by GuillaumeGomez** [comment]
Me neither so an alternative solution would come in handy.

**Comment by TimNN** [comment]
@QuietMisdreavus / @GuillaumeGomez: How do you plan to move forward with this PR?

**Comment by GuillaumeGomez** [comment]
We haven't talked about it since then (rustfest). We will come back to it.

**Comment by Mark-Simulacrum** [comment]
For when this is ready to go, @bors p=1

We should also make sure to backport this if necessary -- I've put the related issue on the tracking milestone.

**Comment by GuillaumeGomez** [comment]
Should we merge this meanwhile writing a better version?

**Comment by QuietMisdreavus** [comment]
Reading over this again, i'm willing to have the temp flag (even though i'm concerned it may not *stay* temporary). However, the location of the check should probably be moved. Right now, what this is doing is universally enabling the `extern_prelude` feature for *every* user of type-links, whether or not they actually intended for it, by bypassing the location where the error would have been emitted. Do we want this? It seems to me like the existing feature check is kinda late in the flow.

In fact, reading this over again, it looks like we can bypass the need for the new flag by moving the feature-flag check. Would it be possible to reconfigure this so that the block with `self.extern_prelude.contains(&ident.name)` doesn't get executed at all if the feature flag is absent? Or use that inner check to set some indicator and emit the error afterward? We can use the `ignore_extern_prelude_feature` check to silence the error then.

I've changed my mind a few times while writing this, but basically i want to make sure we don't eagerly use the `extern_prelude` feature if the crate doesn't have the feature flag set. Right now it will use it regardless.

**Comment by petrochenkov** [comment]
Temporary flag to avoid a feature gate error is okay, but I'd like to avoid this:

>don't eagerly use the `extern_prelude` feature if the crate doesn't have the feature flag set. 

We did the breaking change once in https://github.com/rust-lang/rust/pull/49789 making sure it caused no regressions and now people can't write code that would conflict with extern prelude when it's stabilized.
If extern prelude is completely ignored if `feature(extern_prelude)` is not specified, then we are opening one more time window for people to write such code that will be broken later.

**Comment by QuietMisdreavus** [comment]
@petrochenkov I'm not sure what you're suggesting. Are you wanting to keep this PR as-is, or make it do something different?

**Comment by petrochenkov** [comment]
"As is" LGTM.

**Comment by QuietMisdreavus** [comment]
Works for me! I was worried about exposing the feature more widely than it otherwise would have been, but if you're worried about breaking more code when it's fully stabilized, i won't hold it up. Thanks for commenting!

@bors r+

**Comment by GuillaumeGomez** [comment]
Rebased (and no conflicts of course...).

@bors: r=QuietMisdreavus

**Pull request merged**
