### PR TITLE
Improve span for `consider adding an explicit lifetime bound` suggestions under NLL

### PR DESCRIPTION
**Pull request by marmeladema**
Because NLL borrowck is run after typeck, `in_progress_typeck_results` was always `None` which was preventing the retrieval of the span to which the suggestion is suppose to add the lifetime bound.
We now manually pass the `LocalDefId` owner to `construct_generic_bound_failure` so that under NLL, we give the owner id of the current body.

This helps with #96332

### CODE REVIEW

**Comment by jackh726** [comment]
Looks good :) need to compare nll vs base before I r+ though

Why wouldn't this close #96332

**Comment by marmeladema** [comment]
> Why wouldn't this close https://github.com/rust-lang/rust/issues/96332

Because while I was investigating this, I realized that under NLL those suggestions are missing a part:
```
...so that the type `T` will meet its required lifetime bounds
```
but also a note:
```
note: ...that is required by this bound
  --> $DIR/regions-close-object-into-object-5.rs:13:17
   |
LL | struct B<'a, T: 'a>(&'a (A<T> + 'a));
```

I do believe this PR is a step in the right direction, but imo is not enough to recover everything lost under NLL.

**Comment by marmeladema** [comment]
> > Why wouldn't this close #96332
> 
> Because while I was investigating this, I realized that under NLL those suggestions are missing a part:
> 
> ```
> ...so that the type `T` will meet its required lifetime bounds
> ```

Actually, I think I've just solved that first problem with the second commit.

> but also a note:
> 
> ```
> note: ...that is required by this bound
>   --> $DIR/regions-close-object-into-object-5.rs:13:17
>    |
> LL | struct B<'a, T: 'a>(&'a (A<T> + 'a));
> ```
> 
> I do believe this PR is a step in the right direction, but imo is not enough to recover everything lost under NLL.

**Comment by jackh726** [comment]
I think this is a step in the right direction, but it doesn't touch any of the tests from [#96212](https://github.com/rust-lang/rust/issues/96212). It's an improvement though, so we can land.


@bors r+

**Pull request merged**
