### PR TITLE
[dev-nightly] Testing out rustc-dev

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This PR targets a non-official branch such that we can run full CI and eventually build a nightly from the branch on dev-static; this will hopefully allow us to iron out kinks prior to merging this PR's commits into master proper.

cc #64823 and #65337

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors rollup=never r+

This is per a conversation on Discord. We will "waste" a CI cycle on this but that's largely unavoidable. Self-approving as we are not merging into an official branch.

**Comment by Mark-Simulacrum** [comment]
@bors p=1

Since we would like to get these results sooner rather than later to enable testing and hopefully get the wins into beta at least.

**Comment by pietroalbini** [comment]
Kicked off the release process on this.

**Comment by pietroalbini** [comment]
Release available on `dev-static`.

**Pull request merged**
