### PR TITLE
Update RLS and Rustfmt

### PR DESCRIPTION
**Pull request by Xanewok**
refs: https://github.com/rust-lang/rls/pull/1701

cc @calebcartwright 

r? @dtolnay

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thank you!

**Comment by dtolnay** [comment]
Master is on 1.49.0 right now (since #77451), so I am nominating this for backport to beta 1.48.0 because the rustfmt bump includes support for some syntax that is newly introduced in 1.48.0. When adding syntax we should aim for the rustfmt which ships with the same version of rustc to not fail on the new syntax.

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/13767weeklymeeting2020100854818.html#212695510) in T-compiler meeting.

@rustbot modify labels: beta-accepted

**Pull request merged**
