### PR TITLE
Fix abi for wasm-bindgen

### LINKED ISSUE #81386: Breaking change in wasm32-unknown-unknown's ABI on nightly
Some tests in the wasm-bindgen project have started failing in nightly, and bisection points to https://github.com/rust-lang/rust/pull/80594 as the culprit. The minimization of this looks like:

```rust
#[repr(C)]
pub struct Foo {
    pub a: u32,
    pub b: u32,
    pub c: u32,
}

#[no_mangle]
pub extern "C" fn foo(a: Foo) {}
```

where before this compiles as:

```
$ rustc +before foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O && wasm2wat foo.wasm | grep 'func..foo'
  (func $foo (type 0) (param i32 i32 i32))
  (export "foo" (func $foo))
$ rustc +after foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O && wasm2wat foo.wasm | grep 'func..foo'
  (func $foo (type 0) (param i32))
  (export "foo" (func $foo))
```

### PR DESCRIPTION
**Pull request by bjorn3**
Hopefully fixes https://github.com/rust-lang/rust/issues/81386. @alexcrichton can you confirm this fixes wasm-bindgen?

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
I don't really understand https://github.com/rust-lang/rust/pull/80594 or why it would break wasm. Similarly I don't understand the code this is modifying in this PR at this moment to fix the issue. I would expect that this issue would get fixed in this file https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/abi/call/wasm32_bindgen_compat.rs, however.

**Comment by bjorn3** [comment]
Previously `PassMode::Direct` would be used first, some abi independent adjustments would be performed and then some abi dependent adjustments. I expected those to always result in `PassMode::Cast` or `PassMode::Indirect`, but for wasm32_bindgen_compat `PassMode::Direct` is kept in most cases, even when that would require LLVM to do it's own abi adjustments. Now for `Abi::Aggregate`, `PassMode::Indirect` is used, followed by some abi independent and dependent adjustments, which breaks the wasm32_bindgen_compat abi as it didn't do the expected adjustments. This fix reverts back to the old behavior for wasm32-unknown-unknown. Doing this in wasm32_bindgen_compat would require repeating all abi independent adjustments there.

**Comment by alexcrichton** [comment]
Sorry a short explanation won't really help me review this, to review this PR as-is I would have to dive in myself to understand things, which I don't have time to do right now.

There is already one specific location, however, which selects the wasm ABI:

https://github.com/rust-lang/rust/blob/7fba12bb1d3877870758a7a53e2fe766bb19bd60/compiler/rustc_target/src/abi/call/mod.rs#L634-L637

I don't think we should have two different checks for the ABI, and even less so two different checks. I hope that in the long-term the previous ABI (e.g. that on the stable/beta channel) will be the final ABI for wasm, in which case I don't think there should be a "if wasm do this" check in the middle of otherwise platform-independent code.

**Comment by bjorn3** [comment]
> I hope that in the long-term the previous ABI (e.g. that on the stable/beta channel) will be the final ABI for wasm

That would make it impossible to link against C code, which uses the official wasm C abi instead of the wasm-bindgen compat abi.

> I don't think there should be a "if wasm do this" check in the middle of otherwise platform-independent code.

There are already several target checks in the platform-independent code. For example some targets don't ignore ZST arguments, which the platform-independent code normally sets to ignore. (and it must always ignore them for the rust abi to make closure to fn-ptr casts work.)

**Comment by alexcrichton** [comment]
I'm thinking more broadly than what's the case right-this-red-hot-second. I would hope that Clang changes ABI as well.

Again, I can't review changes to this code as-is. One comment I would have, however, is that this is a different check that the one already existing in the codebase. Those two checks should probably not be different nor entirely isolated from one another.

**Comment by bjorn3** [comment]
I expect that the wasm-bindgen abi is slower due to making it impossible to construct large arguments in place and passing a pointer rather than requiring the wasm compiler to copy them to the arguments location. In addition as noted in https://github.com/rust-lang/rust/issues/81386#issuecomment-766991922 the abi is actually much more complex than it seems. LLVM does a lot of adjustments behind the back, including one for which I can't think of a clear rule as evidenced by the example there where a struct containing an i8 wrapped inside a struct and two standalone i32 turn into 6! i32 arguments at the abi level. I wouldn't expect more than three arguments.

**Comment by bjorn3** [comment]
> In addition as noted in [#81386 (comment)](https://github.com/rust-lang/rust/issues/81386#issuecomment-766991922) the abi is actually much more complex than it seems. LLVM does a lot of adjustments behind the back, including one for which I can't think of a clear rule as evidenced by the example there where a struct containing an i8 wrapped inside a struct and two standalone i32 turn into 6! i32 arguments at the abi level. I wouldn't expect more than three arguments.

I think I figured the abi out. There are 3 i8's used as padding in this case. These get promoted to i32.

```rust
#[repr(C)]
pub struct Bar {
    pub foo: u8,
}

#[repr(C)]
pub struct Foo {
    pub a: Bar,
    pub b: u32,
    pub c: u32,
}

#[no_mangle]
pub extern "C" fn foo(a: Foo) {}
```

```llvm
%Foo = type { [0 x i8], %Bar, [3 x i8], i32, [0 x i32], i32, [0 x i32] }
%Bar = type { [0 x i8], i8, [0 x i8] }

; Function Attrs: norecurse nounwind readnone
define void @foo(%Foo %0) unnamed_addr #0 {
start:
  ret void
}
```

I think the rule is that it will flatten nested structs and extend any i8 used as padding to i32. I don't think `cast_to` supports this extension of padding bytes. Looking at all `#[repr(C)]` structs in wasm-bindgen it seems that padding is never used though, so I think I can keep compatibility with wasm-bindgen using `cast_to`.

**Comment by bjorn3** [comment]
I pushed a new version that doesn't change the abi independent part. It should have the same ABI for all structs without padding. As far as I could see wasm-bindgen doesn't ever use any types with padding, nor could I find any code to handle padding, so this should be compatible with wasm-bindgen.

**Comment by bjorn3** [comment]
The more I think about it the less I am certain that defaulting `Abi::Aggregate` to `PassMode::Indirect` doesn't change the abi for more targets. I have switched it back to `PassMode::Direct`. At least for x86_64 `PassMode::Direct` will never be used for aggregates I think, so it shouldn't have much negative effects for cg_clif. I am now fairly certain that there are no latent changes to any non-rust target due to #80594.

**Comment by alexcrichton** [comment]
This is unfortunately well beyond my ability to review at this point.

**Pull request merged**
