### PR TITLE
Update Clippy submodule

### LINKED ISSUE #61071: `rls` no longer builds after rust-lang/rust#60740
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#60740, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @petrochenkov, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @nnethercote, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by phansch**
Changes:

```
Rustup to https://github.com/rust-lang/rust/pull/60740
Lifetimes UI test cleanup
tests: update needless_bool test stderr
Rustup to https://github.com/rust-lang/rust/pull/60965
```

Should fix #61071

### CODE REVIEW

**Comment by phansch** [comment]
huh that is weird:

```
[01:36:13] -   | |_____^ help: you can reduce it to: `{ !returns_bool() }`
[01:36:13] +   | |_____^ help: you can reduce it to: `!returns_bool()`
```

AFAIK nothing got changed in Clippy recently that could cause this. Maybe it's spurious, but I don't think so. I will be able to take a look in ~3 hours.

**Comment by mati865** [comment]
Maybe change in Rust?

**Comment by phansch** [comment]
There's another pending change needed in Clippy before we can update the submodule again at https://github.com/rust-lang/rust-clippy/pull/4134. Unfortunately I won't have time to update this PR until Monday, so I'm going to close it and leave it for someone else.

**Pull request closed without merging**
