### PR TITLE
Workaround unstable stmt_expr_attributes for method receiver expressions

### LINKED ISSUE #103244: regression: attributes on expressions are experimental
Seems like something about our detection here changed, doesn't look like the cases here *should* be errors at a glance.

* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/emily-signet.sleepyhead-kdl/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/mozilla.rust-parsepatch/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/gh/sampersand.quest2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/over-0.6.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/parsepatch-0.2.9/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/rlxc-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/snapshots-0.2.8/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/cismute-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.65-2/beta-2022-10-11/reg/vipers-2.0.6/log.txt

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/103244

cc @Mark-Simulacrum @ehuss

### CODE REVIEW

**Comment by jackh726** [comment]
Going to re-roll because I'm not familiar with this code.

r? rust-lang/compiler

**Comment by petrochenkov** [comment]
This seems to be a major overkill, I think adding only `fn visit_method_receiver_expr` and not calling `maybe_emit_expr_attr_err` in it in `InvocationCollector` should be enough?

**Comment by cjgillot** [comment]
This is the first thing I tried.
However, if the receiver is a macro expansion, we'll get an `AstFragment::Expr`, which does not know it comes from a method receiver.  So it will call the regular `visit_expr` method, which triggers the feature gate.
The simplest solution would be to stabilize the feature, but t-lang probably won't let us backport that :laughing:.

**Comment by petrochenkov** [comment]
Ugh and sigh.
@bors r+

**Comment by pnkfelix** [comment]
[Discussed in today's T-compiler triage meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-10-27/near/306462602)

We decided to first look into reverting PR #100232 (see in PR #103633) before falling back on risking a beta backport of this PR #103430.

**Comment by Mark-Simulacrum** [comment]
Dropping beta-nominated; we've reverted the problematic PR.

**Pull request merged**
