### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r- 
looks like `clippy_utils` is not building?!
````
 error[E0381]: use of possibly-uninitialized variable: `adt`
   --> src/tools/clippy/clippy_utils/src/ty.rs:580:55
    |
580 |         && let &[krate, .., name] = &*cx.get_def_path(adt.did)
    |                                                       ^^^^^^^ use of possibly-uninitialized `adt.did`

error[E0381]: use of possibly-uninitialized variable: `krate`
   --> src/tools/clippy/clippy_utils/src/ty.rs:581:51
    |
581 |         && let sym::libc | sym::core | sym::std = krate
    |                                                   ^^^^^ use of possibly-uninitialized `krate`

error[E0381]: borrow of possibly-uninitialized variable: `name`
   --> src/tools/clippy/clippy_utils/src/ty.rs:582:12
    |
582 |         && name.as_str() == "c_void"
    |            ^^^^^^^^^^^^^ use of possibly-uninitialized `name`

    Checking regex v1.5.4
For more information about this error, try `rustc --explain E0381`.
error: could not compile `clippy_utils` due to 4 previous errors
````

https://github.com/rust-lang/rust/runs/5323851801?check_suite_focus=true#step:26:780

**Comment by flip1995** [comment]
Argh. Those `let_chains`...

**Comment by flip1995** [comment]
Uhm, that is a bug in a [`debug_assertion_eq!`](https://github.com/rust-lang/rust/blob/ece55d416e65256e4da274988651c20e5d5cb4ea/compiler/rustc_lint/src/unused.rs#L244) in `rustc`.

This can be reproduced by compiling rustc with debug assertions on and then compiling this code:

```rust
fn main { (1, 2, (3, 4)); }
```

**Comment by flip1995** [comment]
@c410-f3r `let_chains` seem weirdly broken.  In this and the last sync I had to remove them from Clippy again, because I got that `possible uninitialized` error https://github.com/rust-lang/rust/pull/94329#issuecomment-1050192646. The weird part about this is, that this doesn't happen in the Clippy repo, only in the Rust repo. This also doesn't happen with `./x.py test src/tools/clippy`, only with `./x.py check src/tools/clippy`.

**Comment by c410-f3r** [comment]
The usage of `let_chains` in the Clippy repository is a surprise given the lack of Rustfmt support

> @c410-f3r `let_chains` seem weirdly broken. In this and the last sync I had to remove them from Clippy again, because I got that `possible uninitialized` error [#94329 (comment)](https://github.com/rust-lang/rust/pull/94329#issuecomment-1050192646). The weird part about this is, that this doesn't happen in the Clippy repo, only in the Rust repo. This also doesn't happen with `./x.py test src/tools/clippy`, only with `./x.py check src/tools/clippy`.

Uninitialized stuff usually means an incorrect MIR graph but in this case, I think the problem is related to the fact that bootstrap is using a old compiler version.

It is probably worth waiting for https://github.com/rust-lang/rust/pull/94290

**Comment by matthiaskrgr** [comment]
There might be something strange happening with what rustc version is used.
in the clippy repo, we use the pinned nightly, inside the rustc repo, I think `x.py test` uses rustc stage2 compiler but `x.py check` might use the beta that is also used to bootstrap rustc?

**Comment by flip1995** [comment]
Yes `x.py check` uses the bootstrap compiler. That's why I didn't mention this let_chains issue last time. I figured one the bootstrap compiler is bumped, the issue would go away.

But since #94290 isn't merged yet, it is probably still the same issue. I will check again once that is merged.

**Comment by matthiaskrgr** [comment]
bootstrap bump has merged :)

**Comment by flip1995** [comment]
Alright. re-synced. ``let_chains`` seem to work now 👍

**Pull request merged**
