### PR TITLE
Allow Vec's deref to be inlined

### PR DESCRIPTION
**Pull request by lqd**
This was hot in some local benchmarks, so let's see if this slight improvement will be interesting.

r? @ghost

### CODE REVIEW

**Comment by lqd** [comment]
I had the same feeling, but was surprised it wasn't marked inline already when seeing it (expectedly) didn't inline with debug assertions, so I tried it. It did seem to make a difference on the cranelift-codegen and keccak benchmarks (without debug-assertions) and I wondered if it'd reproduce. We'll see.

**Comment by lqd** [comment]
This was more of a win locally: 
image

Here, looking at check builds only to approximate runtime benchmarks, it looks like more of a regression instead. What do you think @thomcc ? Let's probably close it.

**Comment by thomcc** [comment]
Yeah, this doesn't seem justified.

**Pull request closed without merging**
