### PR TITLE
 remove rtp.rs, and move rtpSpawn and RTP_ID_ERROR to libc

### PR DESCRIPTION
**Pull request by BaoshanPang**
r? @alexcrichton

### CODE REVIEW

**Comment by BaoshanPang** [comment]
cc @n-salim

**Comment by BaoshanPang** [comment]
@alexcrichton 
Please help to nominate this one to beta too.

Thanks,
Baoshan

**Comment by alexcrichton** [comment]
@BaoshanPang that's possible yeah, but to clarify, we typically don't do backports unless they're for critical patches or critical fixes. We're not necessarily 100% strict about that and small features can get backported as well. We don't have a ton of backported "third party" patches in our history (such as for targets like vxworks which the main project doesn't maintain). 

I don't mind nominating one more to ensure they work together, but I don't think this is something that we'll want to do for a series of patches. Are there any more that need to be backported? Or is this the last one for 1.39?

**Comment by n-salim** [comment]
@alexcrichton Thanks for the clarification on the backporting policy. This patch will bring VxWorks support in 1.39 in sync with what we have in nightly. If we made further fixes on nightly we'll do so with the understanding that they probably cannot get backported to 1.39.

**Comment by alexcrichton** [comment]
Ok, sounds good! In that case I'm going to carry over the beta nomination/acceptance from https://github.com/rust-lang/rust/pull/64818 since it's all part of the same.

**Pull request merged**
