### PR TITLE
fix Layout struct member naming style

### PR DESCRIPTION
**Pull request by liangyongrui**

### CODE REVIEW

**Comment by camelid** [comment]
Hi @liangyongrui, thanks for your PR! rust-lang/rust follows a ["No-Merge Policy"](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy), so could you please [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) over upstream changes instead of merging? Thanks!

**Comment by liangyongrui** [comment]
@camelid OK. I have rebased.

**Comment by scottmcm** [comment]
Oh, if the `_`s aren't needed for something, this makes good sense to me!

@bors r+

**Pull request merged**
