### PR TITLE
Bump version to 1.48 and update cfg(bootstrap)s

### PR DESCRIPTION
**Pull request by emilyalbini**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by pietroalbini** [comment]
Also opened https://github.com/rust-lang/stdarch/pull/885 to eventually remove the `cfg(not(bootstrap))` from stdarch.

**Comment by Mark-Simulacrum** [comment]
It also looks like PR CI flaked on this somehow, but presumably unrelated?

**Comment by ollie27** [comment]
It looks like https://github.com/rust-lang/rust/blob/1f2dd3b56aec4d8f97eb0b0552c166ef549d3316/library/std/src/lib.rs#L250 was missed which explains the CI failure.

**Comment by pietroalbini** [comment]
Woops.

@bors r=Mark-Simulacrum

**Pull request merged**
