### PR TITLE
Avoid repeated re-initialization of the BufReader buffer

### LINKED ISSUE #102727: Performance regression in 1.64+ when `BufReader` inner reader doesn't fill the buffer
### Code

I tried this code:

```rust
use std::cmp::min;
use std::io;

const TOTAL_BYTES: usize = 16 * 1024 * 1024;
// runtime increases as the difference between these values increases
const BYTES_PER_READ: usize = 8 * 1024;
const BUFREADER_CAPACITY: usize = 256 * 1024;

fn main() {
    let mut reader = io::BufReader::with_capacity(BUFREADER_CAPACITY, Reader(TOTAL_BYTES));
    let count = io::copy(&mut reader, &mut io::sink()).unwrap();
    println!("copied {count} bytes");
}

struct Reader(usize);

impl io::Read for Reader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let len = min(min(buf.len(), self.0), BYTES_PER_READ);
        if len > 0 {
            buf[..len].copy_from_slice(&vec![0; len]);
            self.0 -= len;
        }
        Ok(len)
    }
}
```

I expected to see this happen:

```console
$ rustc -o slowio slowio.rs
$ time ./slowio
copied 16777216 bytes

real	0m0.015s
user	0m0.011s
sys	0m0.003s
```

Instead, this happened:

```console
$ rustc -o slowio slowio.rs
$ time ./slowio 
copied 16777216 bytes

real	0m8.909s
user	0m8.891s
sys	0m0.002s
```

The problem doesn't occur with optimization enabled.

### Version it worked on

It most recently worked on:

```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5
```

### Version with regression

```
rustc 1.64.0 (Fedora 1.64.0-1.fc36)
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.5
```

Also fails on:

```
rustc 1.66.0-nightly (01af5040f 2022-10-04)
binary: rustc
commit-hash: 01af5040fdada6ef8f1b749cda798d80a8590b2c
commit-date: 2022-10-04
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by saethlin**
Fixes https://github.com/rust-lang/rust/issues/102727

We accidentally removed this in https://github.com/rust-lang/rust/pull/98748. It looks so redundant. But it isn't.

The default `Read::read_buf` will defensively initialize the whole buffer, if any of it is indicated to be uninitialized. In uses where reads from the wrapped `Read` impl completely fill the `BufReader`, `initialized` and `filled` are the same, and this extra member isn't required. But in the reported issue, the `BufReader` wraps a `Read` impl which will _never_ fill the whole buffer. So the default `Read::read_buf` implementation repeatedly re-initializes the extra space in the buffer.

This adds back the extra `initialized` member, which ensures that the default `Read::read_buf` only zero-initialized the buffer once, and I've tried to add a comment which explains this whole situation.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
How difficult is it to write a test here? I suspect it would be pretty annoying, but maybe we can reasonably do it with some helper cfg(test) exposed bits...

**Comment by saethlin** [comment]
I'm proposing that rustc-perf add a runtime benchmark that targets a reasonably-real-world use case that tickles this code path: https://github.com/rust-lang/rustc-perf/pull/1460

Does that assuage your concern about testing?

**Comment by Mark-Simulacrum** [comment]
I guess it's not the worst way to do this, though it is a pretty weak signal (and doesn't stop us from landing regressions since runtime benchmarks are a ways away from automatically running).

Is it hard for us to directly expose the initialized variable in cfg(test) so we can just assert that it behaves properly?

I'm okay approving this (and also going to nominate for backport as a bad regression) without that, but it would definitely make me feel better to have that direct feedback mechanism.

**Comment by saethlin** [comment]
I added a test which asserts that the initialized members behaves the way it currently does. Honestly I'm entirely unclear on what "proper" behavior would be here, because this whole issue is about the initialization which is done by a default/provided impl of an unstable API. And moreover, this is about avoiding initialization which is being done by an API which was ostensibly designed to avoid initialization. And in any case, the problem here was that we deleted this mechanism entirely, because we totally didn't understand what it was for. I think the new comment is as good of protection against making that mistake again as any test I can write.

I'm not entirely sure benchmarks are a weaker signal than any kind of unit test we can write here. The problem reported was that some code became slower due to re-initialization of the buffer. This test is no protection at all against that. We don't have a way to detect that those bytes in the possibly-uninitialized region of the `Buffer`'s buffer have only been initialized only once.

So, if you have a better thing to test for, I would love to hear about it.

**Comment by the8472** [comment]
Shouldn't we also replace the manual fill with a memset (`ptr::write_bytes`)?

**Comment by saethlin** [comment]
I wouldn't object to improving the manual fill implementation, but I feel like that's another optimization on the side where here I'm just trying to fix the regression?

**Comment by Mark-Simulacrum** [comment]
I am happy with this PR now, happy to leave future improvements to the future.

@bors r+

**Comment by mati865** [comment]
I guess this should be candidate for backporting as well?

**Pull request merged**
