### PR TITLE
Implement From<OwnedFd/Handle> for ChildStdin/out/err object

### PR DESCRIPTION
**Pull request by vthib**
## Summary 

Comments in `library/std/src/process.rs` ( https://github.com/rust-lang/rust/commit/ab08639e5950f5c8a42a2870c9636181308c3686 ) indicates that `ChildStdin`, `ChildStdout`, `ChildStderr` implements some traits that are not actually implemented: `FromRawFd`, `FromRawHandle`, and the `From<OwnedFd>/From<OwnedHandle>` from the io_safety feature.

In this PR I implement `FromRawHandle` and `FromRawFd` for those 3 objects.

## Usecase

I have a usecase where those implementations are basically needed. I want to customize
in the `Command::spawn` API how the pipes for the parent/child communications are created (mainly to strengthen the security attributes on them). I can properly setup the pipes,
and the "child" handles can be provided to `Child::spawn` easily using `Stdio::from_raw_handle`. However, there is no way to generate the `ChildStd*` objects from the raw handle of the created name pipe, which would be very useful to still expose the same API
than in other OS (basically a `spawn(...) -> (Child, ChildStdin, ChildStdout, ChildSterr)`, where on windows this is customized), and to for example use `tokio::ChildStdin::from_std` afterwards.

## Questions

* Are those impls OK to add? I have searched to see if those impls were missing on purpose, or if it was just never implemented because never needed. I haven't found any indication on why they couldn't be added, although the user clearly has to be very careful that the handle provided makes sense (i think, mainly that it is in overlapped mode for windows).
* If this change is ok, adding the impls for the io_safety feature would probably be best, or should it be done in another PR?
* I just copy-pasted the `#[stable(...)]` attributes, but the `since` value has to be updated, I'm not sure to which value.

### CODE REVIEW

**Comment by sunfishcode** [comment]
I'm concerned that this exposes std code that isn't expecting to handle non-pipe file descriptors to non-pipe file descriptors. The current implementation of unix `AnonPipe` assumes it can set and clear the non-blocking flag and use `poll`, which looks like it would be some awkward surface area if `ChildStdout` et al supported other file descriptor types.

Independently of that, please do add implementations of the io_safety traits, `From<OwnedFd>` and `From<OwnedHandle>` for anything that gets `FromRawFd` and `FromRawHandle` implementations, so that we don't need to start keeping track of which things in std have one impl and not the other.

**Comment by vthib** [comment]
I have added implementations for `From<OwnedFd>` and `From<OwnedHandle>`.

As for your remark, I agree, but i'm not really sure how this is really handled in other modules. AFAICT FromRawFd is also implemented for other objects where you probably have to be careful about which fd you provide (TcpListener, UdpSocket, ...), so this MR doesn't appear to bring From impls that are too different from those.

**Comment by the8472** [comment]
> which looks like it would be some awkward surface area if ChildStdout et al supported other file descriptor types.

Isn't this already possible via https://doc.rust-lang.org/std/process/struct.Stdio.html#impl-From%3CFile%3E ?

**Comment by yaahc** [comment]
r? rust-lang/libs

**Comment by joshtriplett** [comment]
A potential policy question: now that we have OwnedFd/BorrowedFd, *should* we still provide RawFd-related types and traits in new additions?

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting.

For now, we'd like to just add the impls related to `OwnedFd` and `BorrowedFd`, and hold off on the `RawFd`-related impls for the time being. We can re-evaluate if someone specifically needs `RawFd`.

**Comment by ChrisDenton** [comment]
> although the user clearly has to be very careful that the handle provided makes sense (i think, mainly that it is in overlapped mode for windows).

I think this is a concern. The standard library needs to know whether the read or write method should perform async or synchronous read/write.

So I think our options are:

* commit to our side of process pipes always being async (and document that)
* provide a way for the user to specify whether the pipe is synchronous or async (so it couldn't simply implement the `From` traits)
* try to auto-detect the mode (using [`NtQueryInformationFile`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntqueryinformationfile) to get [`FILE_MODE_INFORMATION`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_mode_information)), but this may potentially fail.

In a reverted PR I did internally make the distinction between async and sync pipes. But the reason that was reverted was that people were already relying on it being async (via `AsRawHandle`). So we might effectively be promising this anyway and thus we're already committed to the first option.

**Comment by vthib** [comment]
I have removed the implementation for `RawFd`/`RawHandle`, keeping only those for `OwnedFd`/`OwnedHandle`.

**Comment by joshtriplett** [comment]
> provide a way for the user to specify whether the pipe is synchronous or async (so it couldn't simply implement the `From` traits)

We could document that by default they're async, and perhaps add methods to OwnedHandle to change to sync/async.

**Comment by ChrisDenton** [comment]
> We could document that by default they're async, and perhaps add methods to OwnedHandle to change to sync/async.

Hm, if we did that I do think we would need a way to both state that a handle is sync and a way to query sync/async for those that don't use the stdlib read/write methods. It would technically still be a breaking change but maybe the impact would be minimal if only user constructed ChildStd* objects could be sync.

**Comment by vthib** [comment]
r? libs-api

**Comment by vthib** [comment]
r? libs

**Comment by vthib** [comment]
What is the status on this PR @joshtriplett ? I have made the changes that were asked and afaict it is simply waiting for review.

**Comment by joshtriplett** [comment]
So, it's already possible to get a file descriptor or handle *from* these. If you do that, you are going to end up relying on whether it's in sync or async mode. Given that, I think that assumption is already present, and should be documented.

However, I also think that people will commonly have a file descriptor in sync mode and want to feed it into these types.

Nonetheless, if we handle it as if it were async, checking if it's ready before using it, that shouldn't *break* with a sync handle (unlike the other way around).

Given that assumption, I think it's reasonable to convert the other way. But I don't think we should *change* the non-blocking flag; we should just operate as if we need to poll.

Does that sound reasonable, @ChrisDenton?

**Comment by ChrisDenton** [comment]
I have been looking at this again. From a Windows implementation perspective I think adding `From` implementations would be ok but it's unfortunate that this is instantly stable.

Some notes:

* Currently, std's internal implementation of `Read` and `Write` for `ChildStd` will not work with synchronous handles. Which is fine implementation wise; there's no UB. We could enhance it to support synchronous handles but that can safely be left to future work.
* As has been said, stdlib's implementation of process pipes, etc is already leaky due to existing unsafe methods so I am currently of the opinion there's not much we can do about that. People rely on it to some extent so changes already risk breaking people's code.
* Third parties using `ChildStd*` already must assume async handles and so will break if new code creates synchronous `ChildStd*`. That's also fine. That could won't work either before or after the change.
* I guess the only risk would be to new code taking `ChildStd*` and using handles in a way that assumes they're synchronous, which would now be possible although perhaps unlikely.

**Comment by vthib** [comment]
So am I OK to assume this PR is fine as it is? I am not sure if other changes are expected before it can be merged. Is there anything blocking the merge?

**Comment by vthib** [comment]
@joshtriplett Is there anything I can do to make this PR progress? I'm sorry about the pings, i'd really like for this PR to be merged at some point and i'm not sure what else I can do.

**Comment by joshtriplett** [comment]
@ChrisDenton Is there a way, without substantial overhead, for us to operate on handles as-if they were asynchronous while still working if they're synchronous? Or is there no reasonable way to do that?

If we can do that, I think we should, for robustness. If we *can't* do that, or it would have excessive performance impact, then I think we should either convert to async within `From`, or use TryFrom and error on synchronous handles.

Does that seem reasonable?

**Comment by vthib** [comment]
@ChrisDenton any opinion on this?

**Comment by ChrisDenton** [comment]
Very sorry for the delay; it's been a busy month for me.

@joshtriplett Handles can't be converted between sync and async (except by e.g. reading from one handle and writing to another). The stdlib should be able to cope with either case (even if that sometimes means returning an error). My concern is more third party code that wraps standard library types and implements its own reading/writing, which is what makes it unfortunate that this is instantly stable,

But on balance I think it would be acceptable to simply document that this is something to be wary of. There are already issues with e.g. creating a `File` in async mode then passing it to a third party which implements its own I/O logic.

**Comment by vthib** [comment]
Where can I document it exactly? I cannot add docstrings on the From impl. Should I add docs on the ChildStd* types to specify that underlying file descriptor/handles are expected to be async, and to be wary of the From impl?

**Comment by vthib** [comment]
@joshtriplett @ChrisDenton

**Comment by the8472** [comment]
> I cannot add docstrings on the From impl.

Are you sure? We do have docs [on some trait impls](https://doc.rust-lang.org/std/convert/trait.From.html#impl-From%3Cu8%3E-for-char).

**Comment by vthib** [comment]
Oh interesting, my bad then, i'll do just that, thanks

**Comment by mejrs** [comment]
Yeah, trait impls can have docs. They'll be all the way down in the docs' Implementors section. (which unfortunately also means that people are unlikely to see it unless they're specifically looking for it)

**Comment by the8472** [comment]
Maybe rustdoc sould sort documented trait impls above the non-documented since they might be more noteworthy in some ways.

**Comment by vthib** [comment]
I have added some docstrings on the From implementations

**Comment by vthib** [comment]
@ChrisDenton @joshtriplett Does it look ok for you?

**Comment by vthib** [comment]
@joshtriplett Can you take a look when you can? thanks

**Comment by vthib** [comment]
@ChrisDenton can you look at it and say if this is ok for you?

**Comment by vthib** [comment]
r? libs

**Comment by m-ou-se** [comment]
@rfcbot merge

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
