### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #95316 (Rustdoc: Discriminate required and provided associated constants and types)
 - #95405 (Move name resolution logic to a dedicated file)
 - #95914 (Implement tuples using recursion)
 - #95918 (Delay a bug when we see SelfCtor in ref pattern)
 - #95970 (Fix suggestions in case of `T:` bounds)
 - #95973 (prevent opaque types from appearing in impl headers)
 - #95986 (Autolabel library PRs with T-libs)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=95316,95405,95914,95918,95970,95973,95986)

### CODE REVIEW

**Comment by pnkfelix** [comment]
Visiting for weekly performance triage.

This PR regressed diesel doc by 4.1%, and associated-items doc by 71% (!). Seems important.

Left comment on PR #95316 asking for further investigation.

(I'm not adding the -triaged label, at least not until after we see results of further investigation, or someone justifies the regression as worth it in order to reap associated benefits of the PR injecting the regression...)

**Comment by fmease** [comment]
The regression is indeed caused by my PR #95316 since rustdoc now evaluates and prints the default value of provided associated constants. Const evaluation is the culprit here.
[We decided](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Printing.20default.20assoc.20consts.20.E2.86.92.20performance.20regression) to keep this change.
Now of course the next goal is to attempt to optimize this.
In the course of the next week I will profile rustc/rustdoc and check if there are any low-hanging fruits. I can't promise anything.

**Pull request merged**
