### PR TITLE
Align android `sigaddset` impl with the reference impl from Bionic

### PR DESCRIPTION
**Pull request by thomcc**
In https://github.com/rust-lang/rust/pull/100737 I noticed we were treating the sigset_t as an array of bytes, while referencing code from android (https://github.com/aosp-mirror/platform_bionic/blob/ad8dcd6023294b646e5a8288c0ed431b0845da49/libc/include/android/legacy_signal_inlines.h) which treats it as an array of unsigned long.

That said, the behavior difference is so subtle here that it's not hard to see why nobody noticed. This fixes the implementation to be equivalent to the one in bionic.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
https://github.com/rust-lang/rust/pull/100828#issuecomment-1221486983

**Comment by thomcc** [comment]
@bors try

(I think this includes the stuff that failed?)

**Comment by matthiaskrgr** [comment]
This failed on the `dist-android` builder, so probably not :/

**Comment by thomcc** [comment]
Huh, I thought try ran the same tests that run on rollup (I guess I just assumed this. in my defense, this is more or less what try was used for on firefox).

Is there an easy way to make CI do that?

**Comment by thomcc** [comment]
I guess I can make it fail here with rollup=never, and at least this way it won't cause someone else trouble. Ideally I'd have a local android dev env set up, but mine broke a few months ago and I haven't gotten around to it.

@bors r=Mark-Simulacrum rollup=never

**Comment by matthiaskrgr** [comment]
Ouff, do we still have  bug that when we `bors try` and `r+` while the pr is compiling for `try` the `try` build would try to merge it right away because its "approved" now?

**Comment by Mark-Simulacrum** [comment]
OK, please don't try and then r+ in the future (until https://github.com/rust-lang/homu/issues/47 is fixed).

Otherwise I think @bors r=Mark-Simulacrum rollup=never is reasonable.

We can make try builds run android with some work -- there's some documentation here: https://rustc-dev-guide.rust-lang.org/tests/ci.html#using-ci-to-test

**Comment by thomcc** [comment]
> OK, please don't try and then r+ in the future (until [rust-lang/homu#47](https://github.com/rust-lang/homu/issues/47) is fixed

Noted, thanks, I didn't realize that bug existed.

**Pull request merged**
