### PR TITLE
Cleanup configure nits

### PR DESCRIPTION
**Pull request by mstewartgallus**
So, I'm doing more things to cleanup the configure script.

### CODE REVIEW

**Comment by sstewartgallus** [comment]
I did make this ready merge and change the parts talked about.

**Comment by brson** [comment]
I haven't seen this PR before. Will review tomorrow.

**Comment by brson** [comment]
r=me I'm sorry I forgot about this.

**Comment by tamird** [comment]
needs a rebase

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resend with a rebase!

**Pull request closed without merging**
