### PR TITLE
Add summary and reference to Rust trademark guide

### LINKED ISSUE #53287: Trademark restrictions?
Want to fix this bug? There are [instructions below](https://github.com/rust-lang/rust/issues/53287#issuecomment-479520262).

-------------------

This github repository does not contain a trademark file, and I am curious if https://www.rust-lang.org/en-US/legal.html still applies, as it would seem.

> Uses that require explicit approval
> 
>     **Distributing a modified version of the Rust programming language or the Cargo package manager and calling it Rust or Cargo requires explicit, written permission from the Rust core team.** We will usually allow these uses as long as the modifications are (1) relatively small and (2) very clearly communicated to end-users.
> 
>     Selling t-shirts, hats, and other artwork or merchandise requires explicit, written permission from the Rust core team. We will usually allow these uses as long as (1) it is clearly communicated that the merchandise is not in any way an official part of the Rust project and (2) it is clearly communicated whether profits benefit the Rust project.
> 
>     Using the Rust trademarks within another trademark requires written permission from the Rust core team except as described above.

Debian and some other distributions are applying patches against the Rust language and Cargo package. I assume this qualifies as something which requires explicit approval? 

If so, removing or restricting packages from Cargo would also be considered a modification. e.g. some distributions may wish to block access to Cargo downloads that are not in compliance with license standards.

Just wanted to get some clarification on this as it is not mentioned here in the repo and some folks seems to think that because there is no trademark "here" that rust-lang can be distributed with modifications without approval. I believe the only way such modifications would be allowed unrestricted, is if "rust" was not used at all in the package and it was clearly defined as a rebranded fork that is not affiliated with the official package - Otherwise the trademark policy is still enforced.

### PR DESCRIPTION
**Pull request by agnxy**
Fix #53287 
cc @steveklabnik

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @skade 

Would you be willing to review this?

**Comment by skade** [comment]
This looks okay, with the extension that we also have a licenses page: https://www.rust-lang.org/policies/licenses

It's quite important, as some media (especially pictures) on the page are used with permission and not owned by the Rust team.

**Comment by steveklabnik** [comment]
Thanks for this! I agree with @skade , adding a link to that would be great as well. Thanks so much!

**Comment by agnxy** [comment]
Hi @skade @steveklabnik ,
Thanks for your suggestions. I have added a link to the licenses page.

**Comment by skade** [comment]
@agnxy Perfect, thanks!

r+

/cc @alexcrichton

**Comment by Centril** [comment]
@alexcrichton Please rollup PRs such as this :)

@bors rollup

**Pull request merged**
