### PR TITLE
Dogfood `half_open_range_patterns`

### PR DESCRIPTION
**Pull request by Centril**
cc https://github.com/rust-lang/rust/issues/67264

r? @oli-obk

### CODE REVIEW

**Comment by Centril** [comment]
Bummer. Looks like rustfmt isn't supporting it yet, so I'll need to use a `::skip` for now.

@bors r-

**Comment by oli-obk** [comment]
> so I'll need to use a ::skip for now

I strongly prefer not to do that. `0` works just fine right now. Let's fix rustfmt instead.

**Comment by Centril** [comment]
Works for me; cc @topecongiro.

**Comment by Mark-Simulacrum** [comment]
To be honest, I find these much harder to read. Maybe I'm just not used to it yet, but it's entirely non obvious to me that we're omitting specifically a zero. It also seems largely useless as I can't really see a case where this is better (i.e. where the zero was in the way before).

I'm not sure what to do with this information. This feature was implemented without an RFC, as far as I can tell.

I think the fact that these ranges don't have iterator impls is part of it...

**Comment by Centril** [comment]
I'll close this for now then and you can consider what to do with the information. Personally, I think the feature adds a degree of consistency to patterns & expressions (and `X..` is generally useful but `..X` less so).

**Pull request closed without merging**
