### PR TITLE
Add Symbolic variant to Operand

### PR DESCRIPTION
**Pull request by pvdrz**
r? @oli-obk @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
This seems reasonable but not very useful on its own?

If you add the associated type to the `Machine`, you at least have a place to also put some docs about the purpose of this. It'll also become a much bigger patch though. Better do it after Tuesday (that's when Miri is allowed to break again), and after https://github.com/rust-lang/rust/pull/62173 lands.

Still, I am not sure about landing something that is entirely useless on its own.

**Comment by joelpalmer** [comment]
Ping from Triage: @oli-obk are there any updates on this PR?

**Comment by Dylan-DPC** [comment]
r? @RalfJung 

@christianpoveda any updates on this ?

**Comment by RalfJung** [comment]
I think Oli is the better reviewer for this, they made some plans in Zulip with @christianpovedas, so I am going to assign them again.

r? @oli-obk

**Comment by JohnTitor** [comment]
Ping from triage: any updates? @christianpoveda @oli-obk

**Comment by christianpoveda** [comment]
I believe I am closing this for now. This is not a priority and we can always come back to it later

**Pull request closed without merging**
