### PR TITLE
Port the reference to mdbook

### PR DESCRIPTION
**Pull request by steveklabnik**
Part of #39588.

This is only a work in progress. Still left to do:

- [x] double check contents weren't duplicated/lost with the move to individual pages (I'm going to do this)
- [x] fix up links [and footnotes](https://github.com/rust-lang/rust/pull/39855#issuecomment-280168170) (@frewsxcv has volunteered to help with this)
- [x] change `src/doc/reference.md` to redirect to the book
- [x] move the reference on the doc index to be part of the bookshelf

### CODE REVIEW

**Comment by petrochenkov** [comment]
Will it still be available as a single `Ctrl+F`-able page?

**Comment by steveklabnik** [comment]
@petrochenkov IIRC the "print" view gives you that.

And, if for some reason it doesn't, fixing it in mdbook is quite possible. There's already a ticket open for actual search, for example.

**Comment by petrochenkov** [comment]
>the "print" view gives you that.

Ha, indeed. I never noticed this little icon.
Can it get a huge label "click here for a single page view"?

The reference is mostly useless in multi-page format since it's primarily used for looking up stuff by keyword. I'd really like to see it single-page by default.

>There's already a ticket open for actual search, for example.

If this search is going to remind the Discource search in any way, then that ticked would better stay open.
I think, I have a better ticket to solve - actual single-page representation.

**Comment by steveklabnik** [comment]
One wrinkle I noticed while doing this; mdbook doesn't support rustdoc's footnote syntax, which is really only used in the reference, if I recall. We'll have to handle those too.

**Comment by steveklabnik** [comment]
@frewsxcv given https://github.com/azerupi/mdBook/issues/204 you might not want to mess with the links yet; if they change the way they're generated, you'd have to do a second pass...

**Comment by steveklabnik** [comment]
Hm, mdbook should support footnotes, given that pulldown-cmark does: https://github.com/google/pulldown-cmark/blob/master/tests/footnotes.rs

**Comment by steveklabnik** [comment]
I've sent in https://github.com/azerupi/mdBook/pull/207; let's see.

**Comment by steveklabnik** [comment]
I've built this off of my PR now; we'll see what's up.

@frewsxcv if you want to work on the links, fixing these ones should be fine; they'll be much more similar and less of them will be broken.

@alexcrichton I don't know how okay we are with working with forks of projects; I know @azerupi is busy at the moment, and it's been less than a day, so I don't want to rush him; I also don't know how long we want to block on upstream issues.

**Comment by steveklabnik** [comment]
Update, /cc @alexcrichton it looks like this is landing upstream soon, so I'll fix this up after it lands and we don't need to use my fork 😄

**Comment by alexcrichton** [comment]
👍

**Comment by alexcrichton** [comment]
Oh but yeah for now let's avoid github forks, let's stick to crates.io where we can

**Comment by steveklabnik** [comment]
Status: upstream is merged but needs a crates.io release.

**Comment by steveklabnik** [comment]
Updated mdbook PR made separately: https://github.com/rust-lang/rust/pull/39966

**Comment by steveklabnik** [comment]
Blocked on https://github.com/rust-lang/rust/pull/39976

**Comment by steveklabnik** [comment]
This is now ready to go; all we need are fixing up the links. @frewsxcv is on it! ❤️

**Comment by steveklabnik** [comment]
I've pushed a commit to deal with the footnotes, and opened https://github.com/azerupi/mdBook/issues/210 so we can address it upstream as well.

**Comment by steveklabnik** [comment]
At this point, all of the links in the reference itself are updated. Still gotta do the standard library and the book...

**Comment by steveklabnik** [comment]
This should now be good to go! 😄 

/cc @rust-lang/docs

**Comment by steveklabnik** [comment]
Given that both @frewsxcv and I worked on this, I guess

r? @GuillaumeGomez ❤️

**Comment by GuillaumeGomez** [comment]
Seems all good to me (that was quite the review...). Thanks to both of you!

@bors: r+

**Pull request merged**
