### PR TITLE
Update rls -> faccf0d

### PR DESCRIPTION
**Pull request by alexheretic**
Update rls -> https://github.com/rust-lang-nursery/rls/commit/faccf0d07cad4c84da20c5c0102a450fca9d0b6b using the latest clippy release

r? @nrc

### CODE REVIEW

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/364479538) ([raw log](https://api.travis-ci.org/v3/job/364479538/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:00:47] configure: rust.quiet-tests     := True
---
[00:01:23] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:23] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:23] Build completed unsuccessfully in 0:00:36
[00:01:23] make: *** [prepare] Error 1
[00:01:23] Makefile:81: recipe for target 'prepare' failed
[00:01:23] Command failed. Attempt 2/5:
[00:01:24]     Updating registry `https://github.com/rust-lang/crates.io-index`
[00:01:24] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:24] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:24] Build completed unsuccessfully in 0:00:00
[00:01:24] Makefile:81: recipe for target 'prepare' failed
[00:01:24] make: *** [prepare] Error 1
[00:01:24] Command failed. Attempt 3/5:
[00:01:24]     Updating registry `https://github.com/rust-lang/crates.io-index`
[00:01:24] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:24] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:24] Build completed unsuccessfully in 0:00:00
[00:01:24] Makefile:81: recipe for target 'prepare' failed
[00:01:24] make: *** [prepare] Error 1
[00:01:24] Command failed. Attempt 4/5:
[00:01:25]     Updating registry `https://github.com/rust-lang/crates.io-index`
[00:01:25] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:25] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:25] Build completed unsuccessfully in 0:00:00
[00:01:25] make: *** [prepare] Error 1
[00:01:25] Makefile:81: recipe for target 'prepare' failed
[00:01:25] Command failed. Attempt 5/5:
[00:01:25]     Updating registry `https://github.com/rust-lang/crates.io-index`
[00:01:25] error: the lock file needs to be updated but --locked was passed to prevent this
[00:01:25] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:25] Build completed unsuccessfully in 0:00:00
[00:01:25] make: *** [prepare] Error 1
[00:01:25] Makefile:81: recipe for target 'prepare' failed
[00:01:25] The command has failed after 5 attempts.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by alexheretic** [comment]
Looks like one of the appveyor jobs timed out

**Comment by oli-obk** [comment]
Timed out again.

I opened a clippy + rls update in https://github.com/rust-lang/rust/pull/49872

**Comment by alexheretic** [comment]
Ok I'll leave this to #49872 then

**Pull request closed without merging**
