### PR TITLE
Do not warn about unused arguments in default methods

### LINKED ISSUE #26487: unused_variables lint shouldn't warn for unused parameter to default method in trait
```rust
trait Foo {
    fn bar(&self, a: i32) {}
}

fn main() {}
```
```
<anon>:2:19: 2:20 warning: unused variable: `a`, #[warn(unused_variables)] on by default
<anon>:2     fn bar(&self, a: i32) {}
                           ^
```

The arguments to default methods in traits form part of the documentation, but it is not uncommon for a default implementation of a method to be a no-op that uses none of its arguments.

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #26487.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could the logic for the early return move into the `warn_about_unused_args` function? Other than that r=me, thanks!

**Comment by sanxiyn** [comment]
Isn't the logic analogous to the following? I don't think it is better to move the logic into the function.

```rust
if should_warn {
    warn();
}
```

**Comment by alexcrichton** [comment]
I figure it's good to keep the logic as localized as possible, for example if more stuff is added to the end of `visit_fn` it could be surprising that none of it is run for trait methods. By putting it all into the `warn_about_unused_args` function then the early-return is explicitly only affecting that one function which has less refactor-hazard of breaking something or missing being transferred with the function itself.

**Comment by sanxiyn** [comment]
I really don't want to move the logic into the function, because it does not make sense to me. I think simply avoiding early return and using if-else should address your "stuff is added to the end of the function" concern. Is that okay?

**Comment by brson** [comment]
I'm not sure I agree with the original issue. It may be getting too clever with the special cases. There are a lot of patterns where arguments go unused, and all arguments names are part of the documentation; default methods aren't especially unique here.

r-. Please convince me.

**Comment by sfackler** [comment]
What patterns are those? Why shouldn't we support them as well?

**Comment by brson** [comment]
@sfackler One example: higher-order functions that pass arguments that may not be necessary, e.g. iterators that pass indexes.

**Comment by Gankro** [comment]
Closing as inactive.

**Comment by sanxiyn** [comment]
As far as I can tell, this is active.

**Comment by bluss** [comment]
@rust-lang/lang Needs decision

**Comment by tbu-** [comment]
We also have to explicit ways to silence this warning, either do `let _ = (arg1, arg2, ...)` or `#[allow(unused)]`. I'd prefer this to making to making the unused warning not work in some cases.

**Comment by brson** [comment]
This is still probably worth discussion by @rust-lang/lang.

**Comment by tbu-** [comment]
I think you could try to do that explicitly instead, `let _ = (first, second, third);` or `let _ = only`. This way the lint can still catch accidently unused function parameters in default methods.

**Comment by pnkfelix** [comment]
triage: nominated

**Comment by nikomatsakis** [comment]
The original issue has definitely annoyed me in the past, though I think I just added an `#[allow]` to make it be be quiet. I believe that linters I've used from other languages simply do not warn about unused arguments ever which would be another approach -- but I've definitely found the lint useful in finding and pruning unnecessary arguments, so I'm not sure I would get behind *that*. I guess overall I'm of mixed minds here.

**Comment by nrc** [comment]
I don't see why default methods should be special - I would expect you to use the variables, and if not use a `_` prefix just like elsewhere. You can change the name of variables when you override, so there's no downside, aiui.

**Comment by sfackler** [comment]
@nrc it makes your rustdoc output a bit more gross.

**Comment by bluss** [comment]
@nrc The _-prefixed argument ends up in the trait’s docs, so you’d be forced to write something longer like this to have nice docs. I think it's a nice microimprovement.

```rust
trait Trait {
    fn default(&self, name: String) {
        drop(name);
    }
}
```

**Comment by nikomatsakis** [comment]
After some discussion in the lang team meeting, our feeling was that we ought to not make this change: it's just a bit too special-cased and subtle, and to be consistent the rules ought to apply to other kinds of public functions as well. Instead, the recommended course is to add an `#[allow]` declaration to your trait or default method.

**Pull request closed without merging**
