### PR TITLE
Document how recursion is handled for `ty::Ty`

### PR DESCRIPTION
**Pull request by camelid**
Based on this forum discussion:
https://internals.rust-lang.org/t/recursive-type-representation-in-rustc/15235/4

cc @estebank

### CODE REVIEW

**Comment by camelid** [comment]
r? rust-lang/compiler

**Comment by matthiaskrgr** [comment]
@bors r- 
failed in https://github.com/rust-lang/rust/pull/91458#issuecomment-984899335

**Comment by estebank** [comment]
@camelid r=me after fixing the linked type 😅

**Pull request merged**
