### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #74333 (Deny unsafe operations in unsafe functions in libstd/alloc.rs)
 - #74356 (Remove combine function)
 - #74419 (Add a thumbv4t-none-eabi target)
 - #74485 (More intra-doc links, add explicit exception list to linkchecker)

Failed merges:

 - #74486 (Improve Read::read_exact documentation)

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
This was a [perf loss](https://perf.rust-lang.org/compare.html?start=48036804d2bc461b243c5d291b850e44bcca68ef&end=d7f94516345a36ddfcd68cbdf1df835d356795c3&stat=instructions:u) of up to 6.4% on two rustdoc benchmarks. Presumably #74485 is the cause. @Manishearth, does that sound right? Is the perf loss expected?

**Comment by Manishearth** [comment]
@nnethercote I'm unsure how that can happen, the PR just added stuff to the stdlib docs, why would serde compile slower?

(maybe it's reexporting these things?)

**Comment by jyn514** [comment]
> (maybe it's reexporting these things?)

Even if that's the case, I'd be shocked to see a regression of this size just from intra-doc-links. I'd expect them to be little slower because rustdoc does name resolution, but not 6% on the whole crate!

**Pull request merged**
