### PR TITLE
Shrink `thir::Pat`

### PR DESCRIPTION
**Pull request by nnethercote**
r? @cjgillot

### CODE REVIEW

**Comment by nnethercote** [comment]
I'm not expecting big changes to perf, but let's check:

@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Silly question: why use `Box<Pat>` and not a map `pats: PatId -> Pat` and store `PatId`s?

**Comment by nnethercote** [comment]
> Silly question: why use `Box<Pat>` and not a map `pats: PatId -> Pat` and store `PatId`s?

The first commit log explains this:

> Ideally, `Pat` would be stored in `Thir` like `Expr` and `Stmt` and
referred to with a `PatId` rather than `Box<Pat>`. But this is hard to
do because lots of `Pat`s get created after the destruction of the `Cx`
that does normal THIR building. But this does get us a step closer to
`PatId`, because all the `Box<Pat>` occurrences would be replaced with
`PatId` if `PatId` ever happened.

**Comment by cjgillot** [comment]
Sorry, I forgot to look at the commit messages. Indeed, that was a silly question :smile:
https://github.com/rust-lang/rust/pull/101086 removes late creation of `Pat`s, and may allow us to fully migrate to `PatId`.

@bors r+

**Comment by nnethercote** [comment]
Not a silly question, a very relevant one :)  Before I did this PR I tried to introduce `PatId` and it was a mess. I will try again after #101086 is merged.

I always try to structure my commits carefully, and I often write "best reviewed one commit at a time", but I failed to do so on this PR.

**Comment by nnethercote** [comment]
I rebased to fix the conflicts.

@bors r=cjgillot

**Comment by nnethercote** [comment]
> #101086 removes late creation of `Pat`s, and may allow us to fully migrate to `PatId`.

Unfortunately not, because of this sequence:
```
ConstToPat::recur needs Cx
- called by ConstToPat::to_pat
  - called by PatCtxt::const_to_pat
    - PatCtxt::new
      - called by MatchVisitor::lower_pattern
        - MatchVisitor created by check_match
          - called by thir::pattern:::check_match
            - which is a provider method, and thus can't be given a Cx
```

**Pull request merged**
