### PR TITLE
Revert implementing `Iterator::nth[_back]` in terms of `advance_by[_back]`

### PR DESCRIPTION
**Pull request by timvermeulen**
See https://github.com/rust-lang/rust/pull/76909#issuecomment-704459025.

cc @ecstatic-morse @scottmcm

r? @ghost

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
@bors try
@rust-timer queue

**Comment by Mark-Simulacrum** [comment]
r? @scottmcm 

It looks like this does not fix the regression noted in https://github.com/rust-lang/rust/pull/76909#issuecomment-704459025. I am unsure if we want to revert that PR entirely or just eat this 15% loss. It would seem unfortunate to do so, but I suspect there may be nothing we can do.

**Comment by jyn514** [comment]
> I think that one will regress massively any time an object-safe method is added to Iterator, since it uses Box<dyn Iterator> so all those methods need to be codegened for the vtable. So I don't think reverting the nth changes will fix that part; we might just have to accept it -- unless we decide we just can't add another object-safe method ever again. (Also, that test is massively unrealistic because it's an empty iterator of ()s, and even changing it to an empty iterator of i32 already makes it take 30+ minutes, let alone making it actually have elements.)

Given that this doesn't fix the perf regression, I don't think there's any point in merging or keeping it open.

**Pull request closed without merging**
