### PR TITLE
Improve ptr::read docs

### LINKED ISSUE #21491: ptr::read docs are bogus
> Reads the value from `src` without dropping it.

But in fact this code *does* run the destructor:

```rust
use std::{ptr, mem};
  
struct Foo;
  
impl Drop for Foo {
    fn drop(&mut self) {
        println!("drop day");
    }
} 
  
fn main() {
    let x = Foo;
    unsafe {
        ptr::read(&x as *const Foo);
        mem::forget(x);
    }
} 
```

It's not clear what "without dropping it" means. I *suspect* the point is that it won't *mark* the target (hence `*const T`) as destroyed, from an era when this was more of a dynamic notion than today.  But at any rate, the docs should reflect reality.  As far as I know this is *the* way to explicitly run a destructor in Rust — a nice duality because `ptr::write` is the "placement new" for uninitialized memory.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #21491

r? @kmcallister @Gankro

### CODE REVIEW

**Comment by kmcallister** [comment]
How about "...leaves the memory in `src` unchanged, but runs the destructor"?  I think that's an important part.

**Comment by Gankro** [comment]
With non-zeroing drop, this would be an accurate description of a normal drop, no?

**Comment by huonw** [comment]
@kmcallister it doesn't run the destructor

**Comment by kmcallister** [comment]
@huonw: How else do you explain the behavior of my test program in #21491? afaik, `ptr::read` is the standard way to explicitly call a destructor in Rust.

**Comment by huonw** [comment]
The value is memcpy'd onto the stack and ignored, so the destructor is run there. Something like `let x: T = ptr::read(some_ptr);` runs no destructors: just copies the value into `x` on the stack.

**Comment by kmcallister** [comment]
Fair enough, I see what you mean. I feel like the idiom of discarding `ptr::read(some_ptr)` to run a destructor is too confusing if we don't mention it here, but I'm not sure.

**Comment by steveklabnik** [comment]
I'm happy to adapt this to whatever everyone decides is best :)

**Comment by Gankro** [comment]
How about "Copies the value behind the pointer regardless of whether it is Copy" or something to that effect.

**Pull request merged**
