### PR TITLE
Add regression test

### LINKED ISSUE #75777: The following error was constructed but not emitted: cannot infer an appropriate lifetime
### Code

```Rust
use futures::future::{self, BoxFuture};

fn inject<'a, Env: 'a, A: 'a + Send>(v: A) -> Box<dyn FnOnce(&'a Env) -> BoxFuture<'a, A>> {
    let fut: BoxFuture<'a, A> = Box::pin(future::ready(v));
    Box::new(move |_| fut)
}

fn main() {}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=30f4445ed0f97cf822a7510dd9f0af28)

### Meta
The bug does not appear on beta or nightly.

`rustc --version --verbose`:
```
rustc 1.45.2 (d3fb005a3 2020-07-31)
binary: rustc
commit-hash: d3fb005a39e62501b8b0b356166e515ae24e2e54
commit-date: 2020-07-31
host: x86_64-unknown-linux-gnu
release: 1.45.2
LLVM version: 10.0
```

### Error output

```
error: internal compiler error: the following error was constructed but not emitted

error: cannot infer an appropriate lifetime
 --> src/main.rs:5:14
  |
5 |     Box::new(move |_| fut)
  |              ^^^^^^^^^^^^

thread 'rustc' panicked at 'explicit panic', src/librustc_errors/diagnostic_builder.rs:416:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.2 (d3fb005a3 2020-07-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

### PR DESCRIPTION
**Pull request by JulianKnodt**
This adds a regression test for #75777, effectively closing it since it is solved on nightly and beta.

Closes #75777

### CODE REVIEW

**Comment by JulianKnodt** [comment]
cc: @Dylan-DPC 
Probs can just roll up, but I need to actually run the test on my machine.

**Comment by matklad** [comment]
Failed in rollup: 

https://github.com/rust-lang/rust/pull/76317

https://github.com/rust-lang/rust/pull/76317/checks?check_run_id=1070864339#step:23:1526

probably needs a rebase

**Comment by Dylan-DPC** [comment]
let's give this a try again

@bors r+

**Comment by JulianKnodt** [comment]
Ah this one looks real, I need to fix the output

**Comment by JulianKnodt** [comment]
Hm after running bless locally, it didn't seem to change the output, so maybe it's fine?

**Comment by Dylan-DPC** [comment]
let's check :P

@bors r+ rollup

**Comment by JulianKnodt** [comment]
🙃  I think it might just be failing on one specific target, but I'm not sure why this would be the case

**Comment by Alexendoo** [comment]
The error is different because of the `-Zborrowck=mir`, as it's running in the nll compare mode

You can create a separate `.nll.stderr` for that with `--compare-mode nll --bless`

**Comment by JulianKnodt** [comment]
ah ok I updated that test, so maybe now... it should be fine? Just curious, is there documentation for the nll mode? I should probably read up on it

**Comment by jyn514** [comment]
```
 ---- [ui] ui/issues/issue-75777.rs stdout ----
diff of stderr:

14	   |
15	LL |     Box::new(move |_| fut)
16	   |              ^^^^^^^^^^^^
-	   = note: expected `Pin<Box<dyn Future<Output = A> + Send>>`
-	              found `Pin<Box<(dyn Future<Output = A> + Send + 'a)>>`
+	   = note: expected `(Pin<Box<dyn Future<Output = A> + Send>>,)`
+	              found `(Pin<Box<(dyn Future<Output = A> + Send + 'a)>>,)`
```

**Comment by JulianKnodt** [comment]
It should be all good _hopefully_ since I blessed the output and it fixed the error

**Pull request merged**
