### PR TITLE
Bootstrap cleanup

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Each commit is (mostly) standalone and probably best reviewed as such. Nothing too major just some drive-by nits as I was looking through the code.

r? @alexcrichton

### CODE REVIEW

**Comment by mati865** [comment]
`armhf-gnu`:
```
[01:09:09]    Compiling remote-test-server v0.1.0 (/checkout/src/tools/remote-test-server)
[01:09:09] error[E0463]: can't find crate for `std`
```

**Comment by Mark-Simulacrum** [comment]
@bors r=alexcrichton

I forgot that the remote test server is intended for consumption on the "remote" so we can't usually build it with the bootstrap compiler (we don't have a std around).

**Pull request merged**
