### PR TITLE
Stabilize raw_dylib (`#[link(kind = "raw-dylib")]`)

### PR DESCRIPTION
**Pull request by tbu-**
This stabilizes the raw-dylib and link_ordinal features (#58713) for the remaining architecture: x86.

### CODE REVIEW

**Comment by tbu-** [comment]
Stabilization proposed in https://github.com/rust-lang/rust/issues/58713#issuecomment-1309377015.

The remaining mentions of `raw_dylib` are in src/tools/rust-analyzer. I assumed that I should not modify that because rust-analyzer has its own repository.

**Review by dpaoliello — APPROVED** [review]

**Comment by michaelwoerister** [comment]
Thanks for the PR, @tbu-! I'll take a closer on Monday -- I'll need some time to get up-to-speed with the current state of things.

**Comment by michaelwoerister** [comment]
Thanks for the PR, @tbu-!

I have some comments:
- Can you please post a [stabilization report](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#write-a-stabilization-report) to the tracking issue, listing the things that are added here on top of the previous stabilization?
- @dpaoliello has fixed the x86 name decoration problem in https://github.com/rust-lang/rust/issues/96534. However, I'm not sure if @joshtriplett's [comment](https://github.com/rust-lang/rust/pull/100732#issuecomment-1225873457) already counts as a lang-team approval for the `import_name_type` attribute (the compiler team already approved it via [MCP 525](https://github.com/rust-lang/compiler-team/issues/525)). But I think we'll need to add the lang-team to the FCP anyway. 
- Cross-compiling from `x86_64-pc-windows-gnu` to `i686-pc-windows-gnu` does not work yet, as reported in https://github.com/rust-lang/rust/issues/103939 by @mati865. This doesn't seem like an uncommon scenario, and I think we should have at least a PR with a fix before starting an FCP.
- The Rust Reference needs to be updated. This is the original PR introducing documentation: https://github.com/rust-lang/reference/pull/1244
- An i686-specific issue with `vectorcall` has been fixed in https://github.com/rust-lang/rust/pull/99476.
- We have some evidence that the feature works as expected for the windows-rs crate in https://github.com/microsoft/windows-rs/pull/2149. That's great news since windows-rs is likely to be a great stress test for the feature.
- It looks like rust-analyzer does indeed have test cases that will need to be updated. My guess is that @rust-lang/wg-rls-2 will take care of that once the stabilization is through.

**Comment by kennykerr** [comment]
Cross-compilation would also block windows-rs from going beyond experimental support. https://github.com/rust-lang/rust/issues/103939

**Comment by mati865** [comment]
> * Cross-compiling from `x86_64-pc-windows-gnu` to `i686-pc-windows-gnu` does not work yet, as reported in [Cross-compiling `raw-dylib` doesn't work on Windows #103939](https://github.com/rust-lang/rust/issues/103939) by @mati865. This doesn't seem like an uncommon scenario, and I think we should have at least a PR with a fix before starting an FCP.

@michaelwoerister I think there is one more problem related to the mentioned issue that maybe even should have blocked stabilization on 64-bit platforms.
`rustc` has `dlltool` flag to override path to `dlltool` binary which could have been used as a workaround to this issue. Sound cool but that flag is unstable (`-Z dlltool`) so on `windows-gnu` users can override things like linker but are stuck with first `dlltool` binary that is found in PATH with no ability to change it.
Both current dlltool hack and this flag are "temporary" until Rust can declare minimal supported Binutils version for `windows-gnu` recent enough it contains fix allowing it to link against short import libraries created by LLVM (this fix will be included in upcoming 2.40 version). Then the hack will become obsolete since all targets would use LLVM to generate import libs and and the flag will become obsolete.

**Comment by michaelwoerister** [comment]
Yes, good catch @mati865! I came across that too while taking a look at https://github.com/rust-lang/rust/issues/103939. 

As far as I can tell, the plan has always been to also stabilize the `-C dlltool` commandline option (unless we come up with a foolproof way of always finding the correct dlltool -- which we didn't 😉). When the option was introduced in https://github.com/rust-lang/rust/pull/90782, I asked on Zulip what the procedure would be [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Add.20-C.20dlltool.20for.20raw-dylibs.3F). That feedback was that we can just make the flag part of the stabilization FCP. So, I think we just have to make it visible in the stabilization report, that `-Z dlltool` becomes `-C dlltool`. 

But one open question there is if `rustc` should always use the specified `dlltool` if the option is explicitly set, even when it would normally go through LLVM. I think the answer is yes, because otherwise it would be confusing.

**Comment by bjorn3** [comment]
I think `-Cdlltool` should only be respected if rustc itself can't do it. This is similar to how we used to invoke an external archiver that you could specify using `-Car`, but have since deprecated this option and started ignoring it's value since rustc can do it on it's own now.

**Comment by michaelwoerister** [comment]
I think that would be confusing, no? If I explicitly add `-C dlltool` to my `rustc` invocation, I would expect it to use the tool I specified unconditionally (as opposed to "just some of the time under conditions that are undocumented implementation details"). My expectations would be different if the commandline option was called something like `-C fallback-dlltool`.

**Comment by bjorn3** [comment]
My suggestion is to stabilize `-Cdlltool` for now, but deprecate and ignore it once rustc has builtin support. This won't be the first case where rustc temporarily used an external tool until we gained builtin support. Keeping the external tool support only harms maintainability without any advantages that I know of.

* `-Car`: deprecated and value ignored
* cg_gcc uses ranlib: https://github.com/rust-lang/rust/pull/97485 should remove this
* `-Zno-integrated-as`: removed in https://github.com/rust-lang/rust/pull/70345
* dwarf split debuginfo: moved from llvm-dwp to the thorin crate before https://github.com/rust-lang/rust/pull/89819 was merged, but if that happened would likely have done so afterwards.

**Comment by michaelwoerister** [comment]
OK, I have no strong opinion here. Being able to remove the entire `dlltool` logic at some point does seem like an advantage. We just have to make sure to clearly document what the commandline option really does.

**Comment by apiraino** [comment]
hello, checking for progress. With regard to [this](https://github.com/rust-lang/rust/pull/104218#issuecomment-1313514829) comment and perhaps also [this](https://github.com/rust-lang/rust/pull/104218#issuecomment-1318720482) comment, can the update situation be posted here?

Namely if there is some more design/discussion needed or the review con move forward. I'll switch the review status to author for a feedback. @tbu- feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to create a new PR if interested in continuing with this.

**Pull request closed without merging**
