### PR TITLE
Update Error format for E0516, E0517, E0518

### PR DESCRIPTION
**Pull request by gavinb**
- E0518 Update error format #36111
- E0517 Update error format #36109
- E0516 Update error format #36108  
- Part of #35233

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good.  Once you fix the merge conflict, it should be ready.

**Comment by gavinb** [comment]
@jonathandturner Merge conflict resolved, ready to go.

**Comment by jonathandturner** [comment]
Looks good

@bors r+ rollup

**Comment by gavinb** [comment]
@jonathandturner updated again to resolve merge conflict.

**Comment by jonathandturner** [comment]
Great, looks good.

@bors r+ rollup

**Pull request merged**
