### PR TITLE
Warn on bare_trait_objects by default

### PR DESCRIPTION
**Pull request by memoryruins**
The `bare_trait_objects` lint is set to `warn` by default.
Most ui tests have been updated to use `dyn` to avoid creating noise in stderr files.

r? @Centril 

cc #54910

### CODE REVIEW

**Comment by memoryruins** [comment]
and now for level 2: updating run-pass suite.

**Comment by memoryruins** [comment]
@Centril ready for review! \o/

**Review by Centril — CHANGES_REQUESTED** [review]

**Comment by Centril** [comment]
@rust-lang/lang N.B. This PR implements the *"lint against bare trait syntax"* as specified in [RFC 2113](https://github.com/Ixrec/rfcs/blob/dyn-trait-syntax/text/2113-dyn-trait-syntax.md#migration). As we only move to a warning, I think we can dispense with a crater run for now and perhaps move to `deny` later in the year.

**Comment by joshtriplett** [comment]
On Tue, May 28, 2019 at 06:51:30AM -0700, Mazdak Farrokhzad wrote:
> @rust-lang/lang N.B. This PR implements the *"lint against bare trait syntax"* as specified in [RFC 2113](https://github.com/Ixrec/rfcs/blob/dyn-trait-syntax/text/2113-dyn-trait-syntax.md#migration). As we only move to a warning, I think we can dispense with a crater run for now and perhaps move to `deny` later in the year.

Note that under normal circumstances, I'd say we need a crater run to
assess the impact of even a new warning, as that *can* cause build
failures (`deny(warnings)`). However, as this was announced and
advertised as part of the Rust 2018 edition, I think we can reasonably
introduce it as an idiom lint, to be enabled as part of that family of
lints.

**Comment by memoryruins** [comment]
Rebased on top of master and addressed comments ^^

**Review by Centril — APPROVED** [review]

**Comment by Centril** [comment]
Thanks!

@bors r+ p=1 rollup=never

**Comment by memoryruins** [comment]
Updated nll stderr with `./x.py test --compare-mode nll --bless` and squashed into https://github.com/rust-lang/rust/pull/61203/commits/eb4580a570069175e1290b294d91042a09f9fde3. So close!

**Comment by alexcrichton** [comment]
It appears that this lint isn't automatically rust-fixable, is that correct?

If so I would prefer that this were reverted, it's generating thousands of warnings in just one local project, and without rustfix to fix the majority of these it seems like this is prematurely warning by default.

**Comment by Centril** [comment]
> It appears that this lint isn't automatically rust-fixable, is that correct?

I was able to rustfix this automatically in https://github.com/rust-lang/gll/pull/100. Did you use `cargo fix --edition-idioms`? `dyn Trait` is even included as an example in the edition guide, https://doc.rust-lang.org/nightly/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#writing-idiomatic-code-in-a-new-edition

**Comment by alexcrichton** [comment]
Since this is now an on-by-default warning it should not require `--edition-idioms`. It'd be great to make sure that these things are tested before landing.

Tweaking the `cargo fix` command locally it does look like these are automatically fixed, namely for me using `--all` worked since it only looks to fix in the local package otherwise.

**Comment by Centril** [comment]
@alexcrichton Ah; I assumed the `--edition-idioms` infrastructure simply set `-W rust_2018_idioms`. Can you upstream the fix (in cargo I assume?)?

> namely for me using `--all` worked since it only looks to fix in the local package otherwise.

But `--cap-lints` should apply so you shouldn't get warnings otherwise... or perhaps you had some interactions with macros?

**Comment by alexcrichton** [comment]
No fix was necessary, it's simply on by default and all that's needed is `cargo fix`. If there is more than one crate in a workspace you may need `cargo fix --all`. The `--cap-lints` argument isn't applied to workspace members.

**Comment by SimonSapin** [comment]
This change is proving disruptive: https://github.com/rust-lang/rust/issues/61963

**Pull request merged**
