### PR TITLE
indicate where to copy config.toml.example

### PR DESCRIPTION
**Pull request by durka**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm perhaps this could say "copy this file to the object directory" or something like that? I think we need to be a bit more specific than "../config.toml"

**Comment by durka** [comment]
Personally I wouldn't know where the "object directory" is. Or did that autocorrect from "parent directory"?

**Comment by durka** [comment]
The paragraph below makes it sound like you could run `bootstrap.py` from any directory and it would look for config.toml in the CWD. Is that so?

**Comment by TimNN** [comment]
@durka Yes

**Comment by alexcrichton** [comment]
Ah yeah "object directory" == "cwd of the invocation of `bootstrap.py`

**Comment by durka** [comment]
@alexcrichton some other tools (e.g. rustfmt) look up the directory tree if config.toml doesn't exist, so if you had several rust builds in a dir you could put a global config.toml above them or something like that. Would that be desirable behavior for rustbuild?

**Comment by alexcrichton** [comment]
Hm perhaps! I haven't thought too much about it but seems reasonable. Dealing with conflicting configuration though might be kinda unfortunate.

**Pull request merged**
