### PR TITLE
Error codes new

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #42229.

cc @Susurrus @frewsxcv @QuietMisdreavus

### CODE REVIEW

**Comment by Susurrus** [comment]
This looks good. Only comment I have on the text is whether this should include stating what the type was of the "something" that was called. I don't know if that'd every be useful to the user who sees this error in debugging though.

**Comment by QuietMisdreavus** [comment]
I'm wondering what the purpose of making these different error codes is. It seems more like E0618 is just a special case of E0619 at the moment. The latter looks like a catch-all "you called something that can't be called" error, while the former is specifically about unit types? Would it be a problem to make them use the same error code?

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus: I was wondering about this and I think I'll go this way.

**Comment by aidanhs** [comment]
Bunch of travis failures e.g.
```
[00:40:40] error: /checkout/src/test/compile-fail/E0618.rs:16: unexpected "error": '16:5: 16:15: expected function, found `X` [E0618]'
[00:40:40] 
[00:40:40] error: /checkout/src/test/compile-fail/E0618.rs:16: expected error not found: expected function, found `X::Entry` [E0618]
[00:40:40] 
```

**Comment by GuillaumeGomez** [comment]
Fixed CI.

**Comment by QuietMisdreavus** [comment]
Looks good to me!

@bors r+

**Pull request merged**
