### PR TITLE
Remove the `missing_copy_implementations` lint.

### PR DESCRIPTION
**Pull request by nnethercote**
This lint made a certain amount of sense for people writing code during the period leading up to to Rust 1.0. It doesn't make much sense today. There are many valid cases of types that could impl `Copy` but do not. The lint is extremely low value and moderately complicated. This commit removes it.

r? @lcnr

### CODE REVIEW

**Comment by nnethercote** [comment]
Like #126018, this will need an FCP.

**Comment by lcnr** [comment]
r=me on the code changes themselves, however, I am less certain about removing this lint.

I definitely wouldn't be in favor of adding it to rustc right now, but unlike `box_pointers`, I can at least imagine a somewhat coherent argument for why this lint should exist. There are some people who use it https://github.com/search?q=missing_copy_implementations+language%3ARust&type=code&l=Rust&p=3.

otoh, It does have false positives and if people are unhappy about us removing it, it can get added to clippy (where it belongs)

@rfcbot fcp merge

**Comment by nagisa** [comment]
Question is if we can add this to clippy from the get-go (are they interested in maintaining such a lint at all? is it technically feasible? is there something that makes this lint uniquely easier to implement in rustc?)

**Comment by petrochenkov** [comment]
There's a very similar lint called `missing_debug_implementations`, do you plan to remove it too?

>There are many valid cases of types that could impl `Copy` but do not.

Many of them are private though.
Both missing `Copy` and missing `Debug` are supposed to be used by people writing libraries with a stable public interface, and the lints only apply to that public interface.
That seems useful enough.

I'd be fine with putting these lints into clippy if the lints were new.
But since the lints are already in the compiler for long time, then it's better to keep things as is and not break existing code.

**Comment by nnethercote** [comment]
> There's a very similar lint called missing_debug_implementations, do you plan to remove it too?

No. I think the usefulness for public APIs is more obvious there. The motivation for this PR was the fact that the lint description talks about this lint existing to assist with a pre-1.0 behavioural change, which seems to not be of much relevance any more.

**Comment by nnethercote** [comment]
The API guidelines on [interoperability](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits) say "crates that define new types should eagerly implement all applicable, common traits" and specifically names `Copy`, `Clone`, `Eq`, `PartialEq`, `Ord`, `PartialOrd`, `Hash`, `Debug`, `Display`, and `Default`.

The API guidelines on [debuggability](https://rust-lang.github.io/api-guidelines/debuggability.html#all-public-types-implement-debug-c-debug) say "All public types implement Debug" and "If there are exceptions, they are rare."

A couple of possible reactions to that.
- Why do `Debug` and `Copy` get a lint when none of the other traits do?
- Having said that, `Debug` gets mentioned twice, and with arguably stronger language the second time, so if any single trait deserves a lint maybe it's the one?

**Comment by jhpratt** [comment]
I have personally found this lint to be useful in the past. I don't agree with the motivation at all.

**Comment by oli-obk** [comment]
> @rfcbot concern lint-actually-useful
> 
> From [comment](https://github.com/rust-lang/rust/pull/126293#issuecomment-2192690954): _I have personally found this lint to be useful in the past. I don't agree with the motivation at all_

bot wasn't listening

**Comment by oli-obk** [comment]
@rfcbot concern lint-actually-useful

    From https://github.com/rust-lang/rust/pull/126293#issuecomment-2192690954: I have personally found this lint to be useful in the past. I don't agree with the motivation at all

bot wasn't listening

**Comment by nnethercote** [comment]
There is enough opposition to this that I will close it.

**Pull request closed without merging**
