### PR TITLE
proc_macro/bridge: remove `Closure`.

### PR DESCRIPTION
**Pull request by eddyb**
*(Note: the first commit is from #97041, only based on it so I can build at all locally, will undraft as soon as that lands and is rebased over)*

This is mostly a potential step towards bridge internals friendlier wrt process-level or wasm-based isolation.
(Follow-ups would likely involve never passing buffers and instead having more of an `io::{Read,Write}` combo)

The main change here is the client->server FFI call (the `dispatch` field of `Bridge`), which no longer passes any data other than the `Buffer` itself - it's now effectively "global" (technically thread-local).

While this direction is arguably less Rust-y, the client having a pointer to server data could only work in the same address space anyway (and in practice was always pointing higher up the stack on the same thread), and it's additional representational complexity (if one were, say, trying to construct one of these C ABI `Closure`s from outside a wasm VM, to pass to code inside the wasm VM).

There's still a chance we can't do this, but it's down to performance (IMO at least) now.

cc @petrochenkov @mystor

### CODE REVIEW

**Comment by Urgau** [comment]
Perf bot is currently broken until https://github.com/rust-lang/rust/pull/97044 is merged. See https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/perfrlo.20broken for additional information.

**Comment by lqd** [comment]
> Perf bot is currently broken

note: only the bootstrap rustc benchmark is currently broken.

**Comment by eddyb** [comment]
So maybe the extra TLS isn't feasible after all :/

I might still want to keep some of the refactors (that streamline `ExecutionStrategy` to being only about `Buffer`-oriented request dispatch), but using `Closure` (like before this PR) instead of TLS.

**Comment by petrochenkov** [comment]
I don't have enough time or interest to figure out how the bridge works and what this PR does.
r? rust-lang/compiler

**Comment by wesleywiser** [comment]
I see this is marked as a draft PR. @eddyb I'm going to mark this as `S-waiting-on-author` under the assumption this isn't yet ready for review. Please let me know if that is incorrect!

**Comment by eddyb** [comment]
It's a slowdown so I'll just close it.

**Pull request closed without merging**
