### PR TITLE
Feature gate `rustc` attributes harder

### LINKED ISSUE #62116: Attributes starting with `rustc_` are supposed to be gated, but they are not always gated
Of course, the specific known built-in attributes like `#[rustc_copy_clone_marker]` are feature gated, but the `rustc_*` names are not reserved in general.
As a result, you can easily create a procedural macro attribute starting with `rustc_`.

As a result, introduction of a new built-in attribute is technically a breaking change even if the attribute starts with `rustc_`.

Q: Why is introduction of a new built-in attribute a breaking change.
A: Because built-in attributes will conflict with any other attributes in scope having the same name (see https://github.com/rust-lang/rust/pull/53913#issuecomment-418204136 for some technical details).

Possible solutions:
- Reserve (feature gate) any attributes starting with `rustc_`, including macros, run crater and see what happens.
- Do nothing, this is not a big deal.
    - Third party attribute names are unlikely to start with `rustc_`.
    - We are going to add new non-`rustc_*` built-in attributes anyway and go through the same technically breaking changes in process.

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/62116

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot run mode=check-only

**Comment by petrochenkov** [comment]
Damn.
@bors try

**Comment by petrochenkov** [comment]
@craterbot run mode=check-only

**Comment by petrochenkov** [comment]
The single regression is `#[rustc::attr(...)]` in tests in [remain](https://github.com/dtolnay/remain), and `#[rustc::foo]` attributes are certainly something we want to reserve.

Ok, I think I'll apply https://github.com/rust-lang/rust/pull/62243/commits/a0d792cbbc2589e9bdfa519b4d781704311ba446 to this PR (requires `rustc` to register its own attributes instead of using `feature(custom_attribute)`-style fallback from unresolved), and it's good to go.

**Comment by petrochenkov** [comment]
Updated.

**Review by eddyb — APPROVED** [review]

**Pull request merged**
