### PR TITLE
Revert "correct subtle bug in the type variable code"

### LINKED ISSUE #48660: Performance regression between 3/1 and 3/2
Per https://github.com/rust-lang/rust/pull/47861#issuecomment-369842167.

### PR DESCRIPTION
**Pull request by sgrif**
This reverts commit ccd92c2a4e5ed634bbbd6d3a5bd491c47b80f642.

This commit is the source of a major perf regression, and was not
intended to be included in #47861. At some point I must have
accidentally re-added the commit.

Fixes #48660.

r? @nikomatsakis

### CODE REVIEW

**Comment by kennytm** [comment]
@bors p=5

Because everything else is currently p=2 😄

**Comment by sgrif** [comment]
Thanks for the p bump @kennytm

**Pull request merged**
