### PR TITLE
Detect unused files in `src/test/mir-opt` and error on them in tidy.

### LINKED ISSUE #97564: Check for stale files in `src/test/mir-opt`
This folder currently contains a number of `inst_combine_deref*.diff` files that are completely unused - the associated `.rs` file that generated them was removed all the way back in #81101 . In addition to deleting these files, we should also add a check to compiletest that makes sure that the `mir-opt` folder contains no files that do not belong to any tests (with the exception of the readme).

@rustbot label +C-enhancement +A-test-suite +A-mir-opt

### PR DESCRIPTION
**Pull request by JakobDegen**
Closes #97564 .

Determining which files are generated by a given mir opt test is somewhat difficult. Because of this, we extract the logic for doing it out into a common crate that both compiletest and tidy can depend on. This avoids making compiletest a dependency of tidy which would negatively impact compile times for tidy.

Testing for this is that it catches 5 files that violated this lint (and removes them).

### CODE REVIEW

**Comment by jyn514** [comment]
The new tidy check seems good to me :+1:

@oli-obk can you or someone else on @rust-lang/wg-mir-opt confirm that just deleting these unused files is the right thing to do? Not sure if we should add a test that uses them or something.

**Comment by JakobDegen** [comment]
I had removed the test associated with these files in #100827 . There was a replacement test added at the time

**Comment by JakobDegen** [comment]
Rebased

**Pull request merged**
