### PR TITLE
[breaking change] update stdsimd

### PR DESCRIPTION
**Pull request by gnzlbg**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
For those following along PR is technically a breaking change. The change is outlined in the [stdsimd PR](https://github.com/rust-lang-nursery/stdsimd/pull/576) and described in [an issue](https://github.com/rust-lang-nursery/stdsimd/issues/575) as well. We've previously [performed a crater run](https://github.com/rust-lang/rust/pull/55538#issuecomment-434765784) which [discovered zero breakage](https://github.com/rust-lang/rust/pull/55538#issuecomment-435255806), thus motivating landing this technical breaking change.

@bors: r+

**Comment by gnzlbg** [comment]
The change has been merged in stdsimd upstream.

**Comment by alexcrichton** [comment]
@gnzlbg perhaps the wrong pr closed? (this one's needed to update stdsimd in rust-lang/rust)

**Comment by gnzlbg** [comment]
Oops!

**Pull request merged**
