### PR TITLE
change offset from u32 to u64

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
References #71696

r? @oli-obk 

(closed the earlier pr because the rebase got messed up)

### CODE REVIEW

**Comment by elichai** [comment]
Why not usize?

**Comment by pickfire** [comment]
Why shouldn't it be limited to `usize`?

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

The bump in PlaceElem size here for the very unlikely case of wanting more than 2^32 elements in a slice or so seems pretty unfortunate.

**Comment by elichai** [comment]
> Why shouldn't it be limited to `usize`?

Because it should support whatever offset the *target* supports.
So if you run rustc on a 32bit but target 64bit offsets can be 64bit, not 32bit.
I think this should be as big as the biggest architecture pointer supported.

**Comment by pickfire** [comment]
> Because it should support whatever offset the target supports.
> So if you run rustc on a 32bit but target 64bit offsets can be 64bit, not 32bit.
> I think this should be as big as the biggest architecture pointer supported.

Then why isn't it 128 bit?

**Comment by lzutao** [comment]
> Then why isn't it 128 bit

Rust hasn't ever supported 128 pointer width.

**Comment by Mark-Simulacrum** [comment]
Performance looks like a slight (maybe .1%) loss on most benchmarks. The original downsizing was in https://github.com/rust-lang/rust/pull/55589, by @oli-obk -- I suspect we didn't individually benchmark the various enums changing sizes, so maybe PlaceElem is not that important (or has become less important since  then).

**Comment by oli-obk** [comment]
Yea, from the perf results I'd say let's do this (since it reduces complexity and possible ICEs)

@bors r+

**Pull request merged**
