### PR TITLE
[beta] Prepare beta 1.34.0

### PR DESCRIPTION
**Pull request by emilyalbini**
Already force-pushed the beta branch.

r? @Mark-Simulacrum 
cc @rust-lang/release

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
We'll need to drop the Cargo update.


I think we should remove that step from the instructions, too - it's unlikely to be successful.

**Comment by pietroalbini** [comment]
@bors retry

Spurious network failure.

**Comment by pietroalbini** [comment]
Spurious RLS failure on Windows.

@bors retry

**Pull request merged**
