### PR TITLE
Replace `core::iter::AlwaysOk<T>` by `Result<T, !>`

### PR DESCRIPTION
**Pull request by kennytm**
#43278 has been fixed, so we don't need this struct anymore. 

(Actually we don't even need `.unwrap()` thanks to `#![feature(exhaustive_patterns)]`)

### CODE REVIEW

**Review by scottmcm — APPROVED** [review]
Thanks, @kennytm!

**Comment by shepmaster** [comment]
Ping from triage, @withoutboats !

**Comment by TimNN** [comment]
Ping from triage, @withoutboats / @rust-lang/libs, this PR needs your review!

**Pull request merged**
