### PR TITLE
linkchecker: Add support for <base> tag

### PR DESCRIPTION
**Pull request by ollie27**
Add support for the HTML <base> tag as used by mdBook so The Unstable
Book can be checked.

Also cleanup a few things:
* Stop checking the name attribute. It should never have been used and
mdBook has since been fixed not to use it.
* Make sure we only check html files.
* Remove a few unnecessary allocations.

Finally, dead links in The Unstable Book have been fixed.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 

Awesome thanks! FWIW linkchecker was written in a time w/ only the makefiles so we couldn't use crates.io, but nowadays we could enhance this to actually depend on, for example, html5ever, and have real html parsing! I'm not sure if it's necessary, but something to consider at least.

**Comment by Mark-Simulacrum** [comment]
@bors retry

 - #40474

```
set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
Invoke-WebRequest -Uri https://download.sysinternals.com/files/Handle.zip -OutFile handle.zip
Invoke-WebRequest : The operation has timed out.
At line:1 char:1
+ Invoke-WebRequest -Uri https://download.sysinternals.com/files/Handle ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
Command executed with exception: The operation has timed out.
cat %CD%\sccache.log || exit 0

```

**Comment by alexcrichton** [comment]
I've sent a PR to retry that HTTP request: https://github.com/rust-lang/rust/pull/41996

**Comment by Mark-Simulacrum** [comment]
@bors retry
 - #40474

**Comment by steveklabnik** [comment]
Thanks for this!

(I agree with @alexcrichton that we'll probably want to upgrade it even more in the future, but this is good for now)

**Pull request merged**
