### PR TITLE
Only accept xelatex for building PDF docs

### LINKED ISSUE #17220: make error, when generating doc/guide.pdf, LuaTeX
```
rustdoc: doc/guide.html
pandoc: doc/guide.tex
/usr/bin/pandoc --standalone --toc --number-sections --include-before-body=doc/version.tex --from=markdown --include-before-body=doc/footer.tex --to=latex /home/liigo/rust/rust/src/doc/guide.md --output=doc/guide.tex
latex compiler: doc/guide.pdf
This is LuaTeX, Version beta-0.70.2-2012070300 (TeX Live 2012/Debian)
 restricted \write18 enabled.
make: *** [doc/guide.pdf] Error 1
```

### PR DESCRIPTION
**Pull request by steveklabnik**
None of the others work, so let's remove them.

Fixes #17220.

r? @brson

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like there's a tidy error (makefiles won't parse).

Otherwise r=me

**Comment by steveklabnik** [comment]
```
$ git diff
diff --git a/mk/docs.mk b/mk/docs.mk
index 547ad96..71b2533 100644
--- a/mk/docs.mk
+++ b/mk/docs.mk
@@ -87,7 +87,7 @@ endif
 
 # Check for xelatex
 
-ifeq($(CFG_XELATEX),)
+ifeq ($(CFG_XELATEX),)
     CFG_LATEX := $(CFG_XELATEX)
     XELATEX = 1
   else
```

dammit, make

**Comment by steveklabnik** [comment]
r=alexcrichton 7d4f068

**Comment by steveklabnik** [comment]
This seems to have not be seen by @bors  :( @alexcrichton @barsol ideas?

**Comment by sfackler** [comment]
@bors: r=alexcrichton 7d4f068

maybe?

**Comment by sfackler** [comment]
Looks like that did it :confused:

**Comment by steveklabnik** [comment]
@sfackler: :heart: yeah, no idea there

**Pull request merged**
