### PR TITLE
Some update for vxWorks

### PR DESCRIPTION
**Pull request by BaoshanPang**
1. support crt-static
2. change armv7_wrs_vxworks to armv7_wrs_vxworks_eabihf.
3. change vx-cxx to wr-c++,  vx-ar to wr-ar and vx-run to wr-run.
4. code cleanup

r? @alexcrichton

### CODE REVIEW

**Comment by BaoshanPang** [comment]
@alexcrichton

We are supporting vxWorks targets in two modes:
pure static linking and pure dynamic linking.

The pure static linking is by default, if user doesn't specify any of "-C perfer-dynamic" or "-C target-feature=-crt-static", everything is  statically linked into the executable, no shared library will be used.
For pure dynamic linking, the user has to specify both "-C perfer-dynamic" and "-C target-feature=-crt-static", then all libraries will be used in dynamic form, no static library will be linked into executable.

We are thinking about to make it easier to user for "pure dynamic linking":
 When user specify "-C perfer-dynamic" then "-C target-feature=-crt-static" would be used automatically, and vice versa, i.e. tie the two options together. Can you give some suggestion how should we implement it?

Thanks,
Baoshan

**Comment by alexcrichton** [comment]
@bors: r+

Unfortunately static linking vs dynamic is pretty tricky in Rust (I think it's just tricky in general in terms of having tons of config over a build process) and we don't have great solutions right now. I don't have many recommendations one way or another, sorry :(

**Comment by BaoshanPang** [comment]
Do I need to do anything for this PR? I see the code has been merged into master branch:

https://github.com/rust-lang/rust/commit/b7311316fe8b6638d5d9dc07f18def8f60f0b9d2

**Comment by alexcrichton** [comment]
Nah you're good, this is just a bug in bors saying that it needs a rebase

**Pull request merged**
