### PR TITLE
Rename TyLayout to TyAndLayout.

### PR DESCRIPTION
**Pull request by anyska**

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
I think I'm missing some context here. Was this discussed somewhere?

r? @RalfJung

**Comment by RalfJung** [comment]
@eddyb mentioned this to me as a possibility, but I thought you might want to call this `Abi` instead or so... like, I expected some more bikeshedding.^^

r? @eddyb for now

**Comment by eddyb** [comment]
> I think I'm missing some context here. Was this discussed somewhere?

Sorry, I suggested it without making an issue, similar to #69700.

> but I thought you might want to call this Abi instead or so... like, I expected some more bikeshedding.^^

There's already a type named `Abi`, so that would have to be renamed first (which I'm not sure I want in the first place), but I agree we could use some bikeshedding.

Main reason I find `TyAndLayout` a slight improvement over `TyLayout` is that it's more truthful to this being first and foremost a `(Ty, &Layout)` pair, with some extra APIs.
When I originally called it `TyLayout` I was trying to keep it short, but in retrospect it wasn't worth it.

cc @oli-obk @nagisa @hanna-kruppe @bjorn3

**Comment by nagisa** [comment]
TyAndLayout does indeed make much more sense given what the type is. `TyLayout` immediately reads as a "type layout", but that’s really `Layout`.

**Comment by Dylan-DPC** [comment]
@anyska if you can resolve these conflicts, we can get it reviewed :)

**Comment by oli-obk** [comment]
@bors r+

Thanks!

**Pull request merged**
