### PR TITLE
Support Self for intra links paths

### LINKED ISSUE #49583: intra-rustdoc links: Consider supporting `Self`
`Self` is commonly used to avoid having to repeat the same type name over and over again. This makes renaming the type in the future, etc. easier, and DRY code is generally desirable.

Currently, the following produces a link with the literal text `self::new` instead of a correct link:
```Rust
/// Use [`new`] to create a new instance.
///
/// [`new`]: Self::new
pub struct Foo;

impl Foo {
	/// Creates a new instance.
	pub fn new() -> Self {
		unimplemented!()
	}
}

```

Ref #43466

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #49583.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
I don't see how this will work if there are more than one item with `self` links in them, or if the item with `self` links in them isn't the very last thing in the crate. The place where you're setting the item ID is well before it's used, since rustdoc doesn't bother cleaning the attributes until after the code in `visit_ast.rs` is completely finished.

A better solution would be to replace the `impl Clean<Attributes> for [ast::Attributes]` with a function that takes the `DocContext`, the attributes, and the ID you need, to make sure it's always available. It's going to be a tedious fix (since we save the attributes on nearly *everything*) but it's also foolproof and doesn't rely on making sure you've properly swapped the ID in and out.

**Comment by pietroalbini** [comment]
Ping from triage! What's the status on this?

**Comment by GuillaumeGomez** [comment]
It needs big changes.

**Comment by pietroalbini** [comment]
Weekly ping from triage @GuillaumeGomez! Just making sure this is not forgotten.

**Comment by TimNN** [comment]
Ping from triage, @GuillaumeGomez: We haven't heard from you in two weeks, so we are closing this for now to keep the PR queue clean. Feel free to reopen in the future!

**Pull request closed without merging**
