### PR TITLE
[PERF EXPERIMENT] Test out a Vec with no alignment requirements

### PR DESCRIPTION
**Pull request by GnomedDev**
I request a perf run on this branch, to see the trade offs of memory vs runtime of a Vec that has no alignment requirements. I've gated the actual `repr(packed)` behind only `x64` platforms, as others may respond a lot more negatively to unaligned values.

### CODE REVIEW

**Comment by GnomedDev** [comment]
Looks like further work is required to make this packed repr not regress performance, thanks for the perf runs.

**Comment by Nilstrieb** [comment]
(copying text I send somewhere else):

this is probably a regression because you made vec more complicated
making vec more complicated is horrible for compile time performance
because everyone uses it so rustc needs to instantiate vec all over the place
it doesnt actually capture the runtime performance different of making vec unaligned

And if this did make vec better for runtime use cases, the compile time regression can probably be mitigated in some ways or accepted.

**Pull request closed without merging**
