### PR TITLE
Consider references and unions potentially inhabited during privacy-respecting inhabitedness checks

### PR DESCRIPTION
**Pull request by varkor**
It isn't settled exactly how references to uninhabited types and unions of uninhabited types should act, but we should be more conservative here, as it's likely it will be permitted to soundly have values of such types.

This will also be more important in light of the changes at https://github.com/rust-lang/rust/pull/54125.

cc @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Is it possible to write tests that show examples of how this changes things?

**Comment by cramertj** [comment]
r=me with a test added.

**Comment by varkor** [comment]
I've added a test and removed one that I don't think should apply any more, because the infinite type errors kick in before the infinite uninhabitedness checking ones (as references were the only way to cause this kind of infinite checking).

**Review by Centril — CHANGES_REQUESTED** [review]

**Review by Centril — APPROVED** [review]

**Comment by varkor** [comment]
@cramertj: this required changing a few tests in the end, so it'd be great if you could re-check the changes!

**Comment by pietroalbini** [comment]
@bors r-

[Failed in the rollup](https://github.com/rust-lang/rust/pull/56325#issuecomment-442628605)

**Comment by varkor** [comment]
The error seems unrelated to the changes.

@bors retry

**Comment by Centril** [comment]
@varkor Same error seems to have turned up in https://github.com/rust-lang/rust/pull/56408#issuecomment-443453357 which included this PR.

**Comment by nikic** [comment]
@Centril This is a spurious failure introduced by #49878, with a fix at #56396. It's unrelated to this PR :)

**Comment by Centril** [comment]
@bors rollup

(was in https://github.com/rust-lang/rust/pull/56408)

**Comment by dlrobertson** [comment]
#56396 landed... Thanks for you patience, this is probably due for a retry

**Pull request merged**
