### PR TITLE
Rollup of 27 pull requests

### PR DESCRIPTION
**Pull request by eddyb**
- Successful merges: #33342, #33393, #33415, #33475, #33517, #33533, #33534, #33565, #33580, #33584, #33585, #33588, #33590, #33591, #33593, #33598, #33600, #33602, #33603, #33604, #33605, #33607, #33612, #33620, #33633, #33634, #33635
- Failed merges: #33578

### CODE REVIEW

**Comment by arielb1** [comment]
```

/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/librustc_const_math/lib.rs:31:14: 31:34 error: can't find crate for `syntax` [E0463]
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/librustc_const_math/lib.rs:31 #[macro_use] extern crate syntax;
                                                                                                                        ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/libsyntax_ext/lib.rs:28:1: 28:21 error: can't find crate for `syntax` [E0463]
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/libsyntax_ext/lib.rs:28 extern crate syntax;
                                                                                                     ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/librustc_back/lib.rs:44:1: 44:21 error: can't find crate for `syntax` [E0463]
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/librustc_back/lib.rs:44 extern crate syntax;
                                                                                                     ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```
?

@bors retry

**Comment by eddyb** [comment]
@arielb1 Yeah I have no explanation either, stage0 compiles but stage1 doesn't and they have the same Cargo.toml's and whatnot. No change in this rollup seems to actually affect any of that code and I can't see how my metadata change could do this.

@bors retry

**Comment by eddyb** [comment]
cc @alexcrichton because I'm dumbfounded again.

**Comment by alexcrichton** [comment]
Was Cargo.toml forgotten to be updated? (sorry on a phone hard to check)

**Comment by eddyb** [comment]
@alexcrichton I wish, but I can't find anything like that in the combined diff of the rollup.

**Comment by alexcrichton** [comment]
Looks like the cdylib PR failed for the same reason, I'd back that out and I can investigate it locally

**Comment by eddyb** [comment]
@alexcrichton Bummer, since I have the version of that from a couple days ago in my item_symbols removal PR. Let me know if you figure out what's wrong with it.

**Comment by eddyb** [comment]
Whatever, let's get something small going.

@bors r+

**Pull request merged**
