### PR TITLE
Remove problematic specialization from RangeInclusive

### LINKED ISSUE #67194: PartialEq implementation for RangeInclusive is unsound
The following code causes UB in stable without `unsafe` (as can be seen on playground).

```rust
use std::cell::RefCell;
use std::cmp::Ordering;

struct Evil<'a, 'b> {
    values: RefCell<Vec<&'a str>>,
    to_insert: &'b String,
}

impl<'a, 'b> PartialEq for Evil<'a, 'b> {
    fn eq(&self, _other: &Self) -> bool {
        true
    }
}

impl<'a> PartialOrd for Evil<'a, 'a> {
    fn partial_cmp(&self, _other: &Self) -> Option<Ordering> {
        self.values.borrow_mut().push(self.to_insert);
        None
    }
}

fn main() {
    let e;
    let values;
    {
        let to_insert = String::from("Hello, world!");
        e = Evil {
            values: RefCell::new(Vec::new()),
            to_insert: &to_insert,
        };
        let range = &e..=&e;
        let _ = range == range;
        values = e.values;
    }
    println!("{:?}", values.borrow());
}
```

Effects of executing this code are random, for instance, I once got this.

```
["`�d�\u{11}V\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}", "`�d�\u{11}V\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"]
```

### PR DESCRIPTION
**Pull request by CAD97**
Fixes #67194 using the approach [outlined by Mark-Simulacrum](https://github.com/rust-lang/rust/issues/67194#issuecomment-581669549).

> I believe the property we want is that if `PartialEq(&self, &other) == true`, then `self.next() == other.next()`. It is true that this is satisfied by removing the specialization and always doing `is_empty.unwrap_or_default()`; the "wrong" behavior there arises from calling `next()` having an effect on initially empty ranges, as we should be in `is_empty = true` but are not (yet) there. It might be possible to detect that the current state is always empty (i.e., `start > end`) and then not fill in the empty slot. I think this might solve the problem without regressing tests; however, this could have performance implications.

> That approach essentially states that we only use the `is_empty` slot for cases where `start <= end`. That means that `Idx: !Step` and `start > end` would both behave the same, and correctly -- we do not need the boolean if we're not ever going to emit any values from the iterator.

This is implemented here by replacing the `is_empty: Option<bool>` slot with an `exhausted: bool` slot. This flag is

- `false` upon construction,
- `false` when iteration has not yielded an element -- importantly, this means it is always `false` for an iterator empty by construction,
- `false` when iteration has yielded an element and the iterator is not exhausted, and
- only `true` when iteration has been used to exhaust the iterator.

For completeness, this also adds a note to the `Debug` representation to note when the range is exhausted.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can you run benchmarks locally as well? We should try to make sure this is not regressing performance (or at least be aware if it is). We could also verify that the codegen is nice (particularly that it still unrolls nicely).

I'm not running compiler perf tests here since that seems super unlikely to actually be influenced by this.

cc @kennytm

**Comment by CAD97** [comment]
Speaking of codegen issues...

I'll play with this locally now that I know what test to run. I ran libcore tests locally but apparently not the other relevant ones.

**Comment by CAD97** [comment]
I was unable to tweak the implementation to allow that codegen pass to pass. The other, smaller change approach I suggested trying [leads to an ICE](https://github.com/rust-lang/rust/issues/68843), so I can't test if it breaks the codegen test.

**Comment by Mark-Simulacrum** [comment]
Can you update the codegen tests (possibly just commenting out the broken tests for now)? I personally think we should land the soundness fix and then take another look at fixing the codegen. These codegen tests were always pretty brittle I think anyway.

**Comment by CAD97** [comment]
I disabled the failing codegen test.

Interestingly, of the three checks in the file, only one actually started failing. The internal iteration version obviously still works, as that was adjusted in #48012 to be more optimizable.

The interesting part is that the original example from #45222 continues to be optimized down to a `ret` while the simplified example isn't being optimized down.

<details>

```rust
// verify that LLVM recognizes a loop involving 0..=n and will const-fold it.

// Example from original issue #45222

fn foo2(n: u64) -> u64 {
    let mut count = 0;
    for _ in 0..n {
        for j in (0..=n).rev() {
            count += j;
        }
    }
    count
}

// CHECK-LABEL: @check_foo2
#[no_mangle]
pub fn check_foo2() -> u64 {
    // CHECK: ret i64 500005000000000
    foo2(100000)
}

// Simplified example of #45222

fn triangle_inc(n: u64) -> u64 {
    let mut count = 0;
    for j in 0 ..= n {
        count += j;
    }
    count
}

// CHECK-LABEL: @check_triangle_inc
#[no_mangle]
pub fn check_triangle_inc() -> u64 {
    // NO-CHECK: ret i64 5000050000
    triangle_inc(100000)
}

// Demo in #48012

fn foo3r(n: u64) -> u64 {
    let mut count = 0;
    (0..n).for_each(|_| {
        (0 ..= n).rev().for_each(|j| {
            count += j;
        })
    });
    count
}

// CHECK-LABEL: @check_foo3r
#[no_mangle]
pub fn check_foo3r() -> u64 {
    // CHECK: ret i64 500050000000
    foo3r(10000)
}
```
</details>

So... `next_back` is optimizing but `next` isn't? Changing the failing test to `for j in (0 ..= n).rev()` does indeed allow it to pass. If someone better at teasing out optimizations wants to look at it, here are those functions:

```rust
    #[inline]
    fn next(&mut self) -> Option<A> {
        if self.is_empty() {
            return None;
        }
        let is_iterating = self.start < self.end;
        Some(if is_iterating {
            let n = self.start.add_one();
            mem::replace(&mut self.start, n)
        } else {
            self.exhausted = true;
            self.start.clone()
        })
    }

    #[inline]
    fn next_back(&mut self) -> Option<A> {
        if self.is_empty() {
            return None;
        }
        let is_iterating = self.start < self.end;
        Some(if is_iterating {
            let n = self.end.sub_one();
            mem::replace(&mut self.end, n)
        } else {
            self.exhausted = true;
            self.end.clone()
        })
    }
```

**Comment by CAD97** [comment]
So as it turns out, codegen is bizarre, and flipping the check in `next` from `start < end` to `end >= start` causes it to get optimized properly https://twitter.com/CAD97_/status/1225167483264475136?s=20

**Comment by Mark-Simulacrum** [comment]
Those are also different conditions; I think we don't care in practice because is_empty would've already returned false if we were done, though, right?

**Comment by CAD97** [comment]
Whoops, that messes up a test

```rust
    r = RangeInclusive::new(127i8, 127);
    assert_eq!(r.next(), Some(127));
    assert_eq!(r.next(), None);
```

```
---- ops::test_range_inclusive stdout ----
thread 'ops::test_range_inclusive' panicked at 'assertion failed: `(left == right)`
  left: `Some(-128)`,
 right: `None`', src\libcore\../libcore/tests\ops.rs:50:5
```

Reverting for now, whoops

**Comment by CAD97** [comment]
I realized a potential reason why LLVM would do better optimizing the downward direction.

And the reason is that downward-inclusive iteration is a lot more common (in C/C++ code) than upward inclusive. Even a top-half-open range backwards is end-inclusive.

And while iterate up will typically be written in exclusive style (`for(i=0; i<count; i++)`), downwards iteration is still somewhat commonly used (`for(i=count; i-->0;)`) and sometimes in an inclusive style.

Because the reverse iterator is optimized here, I suspect LLVM can be taught to recognize the positive direction as well, though doing so might not be trivial nor reach us quickly.

**Comment by Mark-Simulacrum** [comment]
Okay, pushed up an update (just some changes to the comments) since I want to get this landed quickly.

@bors r+ rollup=never

Marking as non-rollup to make it easy to bisect regressions to this.

**Comment by Mark-Simulacrum** [comment]
Oh, also, I am not filing a new issue for the codegen regression as #45222 is still open anyway...

**Comment by CAD97** [comment]
Just FYI I've currently got a tree in my roof and no power, so I won't be able to touch this for a bit, at least until the power comes back on.

The comment annotations need to be hidden from the codegen test harness by removing them or adding characters, just commenting out the area isn't enough. That's why I used `NO-CHECK` in the version I pushed.

**Comment by Mark-Simulacrum** [comment]
❤️ No worries! I can definitely patch this up.

As to the NO-CHECK, makes sense. I guess we can't check if it's in a comment because it's always in a comment... Will fix that shortly.

**Comment by CAD97** [comment]
The other PR has removed the unsound specialization but leaves `RangeInclusive` in a state where `a == b` does not imply `hash(a) == hash(b)`.

That makes this PR no longer a soundness fix, but instead a correctness fix for the `PartialEq`/`Hash` disconnect, still at cost of the forward iteration optimization.

This representation is also simpler that the `is_empty: Option<bool>` that is currently used and the myriad of potential states of when it should be `None`, `Some(true)`, or `Some(false)`.

**Comment by Mark-Simulacrum** [comment]
Oh, I missed that something else landed...

I will rebase this (essentially overwriting changes from that PR) soon.

**Comment by Mark-Simulacrum** [comment]
@bors r+ 

Rebased.

**Comment by Mark-Simulacrum** [comment]
Hm, rebase errors were not the only changes in that file. Should be fixed now (and actually confirmed that x.py check at least passes).

@bors r+

**Comment by CAD97** [comment]
Am I able to

@bors r-

I found a version that optimizes!

```rust
#[inline]
fn next(&mut self) -> Option<A> {
    if self.is_empty() {
        return None;
    }
    let is_iterating = self.start < self.end;
    Some(if is_iterating {
        let n = self.start.add_one();
        mem::replace(&mut self.start, n)
    } else {
        // HACK(CAD97): This extra increment is required for LLVM to optimize the 
        // forwards iteration as of 2020-02-08.
        let n = self.start.add_one();
        self.exhausted = true;
        mem::replace(&mut self.start, n)
    })
}
```

This changes the exact semantics of `next` when at the final step, but the observable behavior is the same if you can't see `.start`/`.end`.

I've got internet back and the tree has been removed; I'm making the commit with the properly optimizing version presently.

**Comment by CAD97** [comment]
The failure previously was a rebase error.

Wait, I thought I tested this before the previous message... I re-implemented with this version of `next` and it doesn't pass all of the libcore tests after all. `iter::test_range_inclusive_exhaustion` tests the specific results of exhausting `RangeInclusive` (which is documented as unspecified), and `iter::test_range_inclusive_nth` revealed a disconnect between ending states (and thus equivalence) from different ways of exhaustion (next, nth, next_back, nth_back).

**Comment by Mark-Simulacrum** [comment]
Let's leave restoring the performance/codegen test to a future PR; I don't want to get bogged down in figuring it out exactly here, we should fix the Hash/Eq bug at least (which this is doing).

I'll wait till PR CI is passing before re-approving.

**Pull request merged**
