### PR TITLE
rustdoc: Clean up NestedAttributesExt trait/implementation

### PR DESCRIPTION
**Pull request by vacuus**

### CODE REVIEW

**Comment by jyn514** [comment]
r=me with the compile failure fixed

**Comment by camelid** [comment]
rust-lang/rust follows a ["No-Merge Policy"](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy). Could you please [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) over upstream changes instead of merging? Thanks!

**Comment by vacuus** [comment]
I'm still severely confused by how to do rebasing and all and it always seems like I followed the steps but clearly I didn't, since I only got it to work just now.
(more for my own reference, since I'll undoubtedly run into this problem later on)
the steps I did to get it working successfully (some may be extraneous):
1. git pull upstream master
2. git fetch upstream
3. git rebase upstream/master
4. git rebase -i $(git merge-base upstream/master HEAD)
5. git push --force-with-lease origin

Questions I have: should PRs rebase over upstream changes whenever upstream changes occur or only when there's a merge conflict? If there is no merge conflict, does it matter if the PR doesn't rebase over upstream changes?

**Comment by camelid** [comment]
> Questions I have: should PRs rebase over upstream changes whenever upstream changes occur or only when there's a merge conflict? If there is no merge conflict, does it matter if the PR doesn't rebase over upstream changes?

You only need to rebase when there are conflicts. Sometimes it's useful to rebase even when there aren't conflicts if the PR has been sitting for a while and may run into conflicts into the future (to reduce the future rebasde burden).

**Comment by Kobzol** [comment]
Just FYI, I'm not sure whether the `into_iter` calls weren't causing some of the slowdowns when using `has_word`. We should re-perf test https://github.com/rust-lang/rust/pull/92353 on top of this to see if it hasn't regressed.

**Pull request merged**
