### PR TITLE
Select Polonius algorithm via `POLONIUS_ALGORITHM` environment variable

### PR DESCRIPTION
**Pull request by vakaras**
This pull request allows selecting the Polonius algorithm being used by providing an environment variable `POLONIUS_ALGORITHM`.

Example usage:
```
POLONIUS_ALGORITHM=compare RUST_LOG=rustc_mir::borrow_check::nll=trace  ./x.py test --stage 1 --compare-mode polonius -- src/test/ui/nll/issue-47680.rs
...
stderr:
------------------------------------------
 INFO 2018-05-31T17:35:31Z: rustc_mir::borrow_check::nll: Using Polonius algorithm: Compare
 INFO 2018-05-31T17:35:31Z: rustc_mir::borrow_check::nll: Using Polonius algorithm: Compare

------------------------------------------
...
```

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Review by nikomatsakis — APPROVED** [review]

**Comment by lqd** [comment]
🤔 

```
---- net::tcp::tests::connect_timeout_unbound stdout ----
thread 'net::tcp::tests::connect_timeout_unbound' panicked at 'called `Result::unwrap_err()` on an `Ok` value: TcpStream { addr: V4(127.0.0.1:3648), peer: V4(127.0.0.1:3648), socket: 720 }', libcore\result.rs:945:5
```

**Comment by pietroalbini** [comment]
This seems to be spurious?

@bors retry

**Comment by vakaras** [comment]
```
ERROR:  Could not find a valid gem 'aws-sdk-core' (= 2.11.62) in any repository
ERROR:  Possible alternatives: aws-sdk-core
```
Was this some network issue?

**Comment by pietroalbini** [comment]
Yeah, that's a Travis failure.

@bors retry #44159

**Pull request merged**
