### PR TITLE
Enable building Cargo for aarch64-apple-darwin

### PR DESCRIPTION
**Pull request by shepmaster**
r? @ghost

### CODE REVIEW

**Comment by shepmaster** [comment]
@pietroalbini how would you feel about me submitting e51b507 and ddb8ed2 as a separate PR? TL;DR: they move the `try` job below all the other ones so that we can use a YAML anchor instead of copy-pasta the builder specs when we want to change what platforms are built by `try`. This is immensely helpful when trying anything besides the default x86-64 linux builds, which only take a few lines of config, compared to e.g. the macOS builders which are much more.

**Comment by pietroalbini** [comment]
> @pietroalbini how would you feel about me submitting e51b507 and ddb8ed2 as a separate PR? TL;DR: they move the try job below all the other ones so that we can use a YAML anchor instead of copy-pasta the builder specs when we want to change what platforms are built by try. This is immensely helpful when trying anything besides the default x86-64 linux builds, which only take a few lines of config, compared to e.g. the macOS builders which are much more.

Sounds good!

**Pull request merged**
