### PR TITLE
Add AArch64 features to whitelist

### PR DESCRIPTION
**Pull request by Amanieu**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me, thanks!

Looks like there's a travis failure though?

**Comment by Amanieu** [comment]
It should be fixed now.

**Comment by gnzlbg** [comment]
LGTM. We spoke about this on IRC and doing the same thing that clang and gcc do is the only reasonable thing that can be done here for the time being. If we ever get a backend with finer-grained control we can always add finer-grained features. 

Run-time feature detection would need to some of these as a bundle in `stdsimd` but that can be done.

**Comment by Amanieu** [comment]
Fixed merge conflict.

**Pull request merged**
