### PR TITLE
Remove one allocation for the file path in file opening

### LINKED ISSUE #22190: It's not possible to open a file without invoking allocations for the file name
`File::open` takes a `Path` object as reference, although it only clones it afterwards.

It's also impossible to re-use the allocation for the file path, because it's only dropped at the end.

### PR DESCRIPTION
**Pull request by tbu-**
Fixes #22190.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think this is definitely more in-line with today's I/O primitives and paradigms, so I'm ok with this change.

**Comment by aturon** [comment]
Yes, this is the direction we wanted to head in. old_io used this path for error messages, but that behavior wasn't carried over anyway.

@bors: r+

**Comment by Manishearth** [comment]
Needs https://github.com/Manishearth/rust/commit/253f2c5fcab3a65fd7f6230771a49ccd13058b96 to compile

**Comment by tbu-** [comment]
@Manishearth Sorry for the inconvenience and thanks for fixing my patch.

**Pull request merged**
