### PR TITLE
Fix E0284 to not use incorrect wording

### LINKED ISSUE #69683: Confusing error: cannot infer type for type `u8`
rustc gives confusing error, suggesting that I give b an explicit type when b already has an explicit  type.

Replacing `0u16.foo(b)` with `<u16 as Foo<[(); 3]>>::foo(0u16, b)` fixes it.

This may be a duplicate of #69123

## Source
``` rust
pub trait Element<S> {
    type Array;
}

impl<T> Element<()> for T {
    type Array = T;
}

impl<T: Element<S>, S> Element<[S; 3]> for T {
    type Array = [T::Array; 3];
}

trait Foo<I>
where
    u8: Element<I>,
{
    fn foo(self, x: <u8 as Element<I>>::Array);
}

impl<I> Foo<I> for u16
where
    u8: Element<I>,
{
    fn foo(self, _: <u8 as Element<I>>::Array) {}
}

fn main() {
    let b: [u8; 3] = [0u8; 3];

    0u16.foo(b);
    //<u16 as Foo<[(); 3]>>::foo(0u16, b);
}
```

## Log
```
$ rustc src/bin/type_param_demo.rs 
error[E0284]: type annotations needed for `[u8; 3]`
  --> src/bin/type_param_demo.rs:30:10
   |
28 |     let b: [u8; 3] = [0u8; 3];
   |         - consider giving `b` the explicit type `[u8; 3]`, where the type parameter `u8` is specified
29 | 
30 |     0u16.foo(b);
   |          ^^^ cannot infer type for type `u8`
   |
   = note: cannot resolve `<u8 as Element<_>>::Array == [u8; 3]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0284`.
```

## Meta
Same issue occurs in both latest and nightly and stable.

```
$ rustc --version --verbose
rustc 1.43.0-nightly (18c275b42 2020-03-02)
binary: rustc
commit-hash: 18c275b423f9f13c0e404ae3804967d2ab66337c
commit-date: 2020-03-02
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```
```
$ rustc --version --verbose
rustc 1.41.1 (f3e1a954d 2020-02-24)
binary: rustc
commit-hash: f3e1a954d2ead4e2fc197c7da7d71e6c61bad196
commit-date: 2020-02-24
host: x86_64-unknown-linux-gnu
release: 1.41.1
LLVM version: 9.0
```

### LINKED ISSUE #71584: Wrong error message for missed type inference
Code that asks for some type inference:
```
fn main() {
    let n: u32 = 1;
    let mut d: u64 = 2;
    d = d % n.into();
}
```
It gives:
```
error[E0284]: type annotations needed for `u64`
 --> ...\test.rs:4:11
  |
3 |     let mut d: u64 = 2;
  |         ----- consider giving `d` a type
4 |     d = d % n.into();
  |           ^ cannot infer type for type `u64`
  |
  = note: cannot satisfy `<u64 as std::ops::Rem<_>>::Output == u64`
```
The error message "consider giving `d` a type" refers to a "d" that is actually typed as u64.
Using rustc 1.44.0-nightly (3360cc3a0 2020-04-24).

### PR DESCRIPTION
**Pull request by estebank**
Fix #71584, fix #69683.

### CODE REVIEW

**Comment by estebank** [comment]
Nominating for backport because the current error can be incredibly misleading and the risk is low, but won't push for it too much as it is not critical.

**Review by davidtwco — COMMENTED** [review]
LGTM! 

Could you add tests for the cases in #71584 and #69683 so we can see the fixed error message? As far as I can tell, none of the stderr diffs here previously said "considering giving X a type" when it had a type (r=me after that).

**Comment by spastorino** [comment]
Adding `T-compiler` label to process the beta nomination.

**Comment by pnkfelix** [comment]
unilaterally accepting for beta-backport.

**Pull request merged**
