### PR TITLE
[beta] Update clippy

### PR DESCRIPTION
**Pull request by Manishearth**
Backports https://github.com/rust-lang/rust-clippy/pull/4101

Clippy backport PR is https://github.com/rust-lang/rust-clippy/pull/4104

r? @oli-obk @pietroalbini

### CODE REVIEW

**Comment by Manishearth** [comment]
Oliver approved the backport in https://github.com/rust-lang/rust-clippy/pull/4104

**Review by oli-obk — APPROVED** [review]
r? @pietroalbini

**Comment by lzutao** [comment]
> homu Test failed 

Is this OK?

**Comment by pietroalbini** [comment]
Everything passed on the rollup PR...

**Pull request merged**
