### PR TITLE
link.exe: Don't embed full path to PDB file in binary.

### LINKED ISSUE #87825: --remap-path-prefix doesn't map paths to `.pdb` files, even in release mode
Spawned off of https://github.com/rust-lang/rust/issues/87805#issuecomment-894202194

When passing `--remap-path-prefix C:\\path\\to\\project=nothing_to_see_here` to rustc I would expect all paths that start with `C:\path\to\project` to be replaced with `nothing_to_see_here`, instead a `C:\path\to\project\target\release\deps\crate_name.pdb` is still present. 

Note that this happens even in release mode, because rustc always tells the msvc linker to generate `.pdb` files.

This can be "fixed" by passing either `-Clink-arg=/PDBALTPATH:%_PDB%`, `-Clink-arg=/DEBUG:NONE` or `-Zstrip=debuginfo` to rustc, but doing so will break backtraces with `RUST_BACKTRACE='full'` (`RUST_BACKTRACE=1` already prints almost nothing in release mode). As a sidenote, do we really need backtraces in release mode, and by consequence `.pdb` files? They will break anyway if only the `.exe` is distributed or the `target` directory is deleted.

Moreover this shouldn't be needed in the first place since `--remap-path-prefix` promises to "remap source names in all output (compiler messages and output files)" (from the output of `rustc --help -v`), "including [...] debug information" (from the rustc book [here](https://doc.rust-lang.org/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output)). Also note that neither `rustc --help -v` nor the rustc book mention the need to pass one of those arguments to rustc to remap/remove the path to the `.pdb` file, which makes it harder for non-experts to know how to remove them.

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-pc-windows-msvc
release: 1.54.0
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR makes `rustc` unconditionally pass `/PDBALTPATH:%_PDB%` to MSVC-style linkers, causing the linker to only embed the filename of the PDB in the binary instead of the full path. This will help implement the [trim-paths RFC](https://github.com/rust-lang/rust/issues/111540) for `*-msvc` targets.

Passing `/PDBALTPATH:%_PDB%` to the linker is already done by many projects that need reproducible builds and [debugger's should still be able to find the PDB](https://learn.microsoft.com/cpp/build/reference/pdbpath) if it is in the same directory as the binary.

r? @ghost

Fixes https://github.com/rust-lang/rust/issues/87825

### CODE REVIEW

**Comment by michaelwoerister** [comment]
https://github.com/rust-lang/rust/pull/122306 updated backtrace-rs to a version that includes https://github.com/rust-lang/backtrace-rs/pull/584, so this is unblocked now.

@rustbot ping windows

r? compiler

**Comment by lcnr** [comment]
r? compiler

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @michaelwoerister for fixing this and landing that fix to backtrace-rs to unblock it!

@bors r+

**Comment by workingjubilee** [comment]
> However, backtrace-rs currently does not find the PDB. Consequently, this PR is blocked until https://github.com/rust-lang/backtrace-rs/pull/584 is merged.

Merged and backtrace has been updated, so this can land, yep.

**Comment by michaelwoerister** [comment]
r? @wesleywiser 

Let's see if this is the same i686 backtracing issue already encountered in https://github.com/rust-lang/backtrace-rs/pull/584, where backtracing was pretty flaky without frame pointers enabled.

**Comment by michaelwoerister** [comment]
I modified the test code in https://github.com/rust-lang/rust/pull/121297/commits/0a094bae28a00117b99262621ff22876796d2885, so that unwinding will more reliably produce a stack trace that actually contains frames from the test. Unwinding not always working is a pre-existing issue on `i686-pc-windows-msvc` and unrelated to the change in this PR.

**Review by wesleywiser — APPROVED** [review]

**Pull request merged**
