### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #94806 (Fix `cargo run tidy`)
 - #95011 (async: Give predictable name to binding generated from .await expressions.)
 - #95032 (Clean up, categorize and sort unstable features in std.)
 - #95251 (Reduce max hash in raw strings from u16 to u8)
 - #95298 (Fix double drop of allocator in IntoIter impl of Vec)
 - #95471 (Don't ICE when opaque types get their hidden type constrained again.)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=94806,95011,95032,95251,95298,95471)

### CODE REVIEW

**Comment by compiler-errors** [comment]
@dylan-dpc: I think this failure is due to `#![feature(associated_type_bounds)]` being removed in #95032?

**Comment by Dylan-DPC** [comment]
yes yes hold on :P

**Comment by compiler-errors** [comment]
lol, sorry for the ping, I was just being nosey.... carry on :sweat_smile:

**Comment by Dylan-DPC** [comment]
no nothing about being nosey, appreciate the help :)

**Pull request closed without merging**
