### PR TITLE
remove Clone trait implementation and use #[derive(Clone)]

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by eefriedman** [comment]
Hang on, are you sure this is right?  I thought the reason these were derived by hand is that derive(Clone) doesn't use the right bounds; as far as I know that hasn't been fixed.

**Comment by durka** [comment]
@eefriedman is correct -- this adds `T: Clone` bounds to the `Clone` impls that were not there before.

**Comment by srinivasreddy** [comment]
I want  to implement this correct.  Pointers please.

**Comment by durka** [comment]
@eddyb had thoughts about fixing this situation by elaborating trait bounds before the privacy checks. The problem is that `#[derive(Clone)]` needs to bound the impl by all the fields implementing `Clone`. But currently it can't simply list all the field types in the `where` clause, because it might get a "private type in public interface". So it goes with a sometimes-too-liberal strategy of bounding all type parameters. See #31518 and #33769.

**Comment by alexcrichton** [comment]
Yeah this is implemented correctly as-is to avoid the extra `Clone` bound on type parameters. There isn't really a "more correct" way to do this because this is indeed the "correct way to do this". As a result I'm gonna close this, but thanks for the PR!

**Comment by durka** [comment]
Well, a more correct way would be making the derived impls better. But that
can't be done without compiler support in some way.

**Pull request closed without merging**
