### PR TITLE
Don't throw away unused arguments of format_args

### LINKED ISSUE #115423: `format_args!` does not respect integer literals' type
When using the `1234i8` syntax in the Display format in formatting macros, the `i8` is ignored and treated as a `u128`.

I tried this code:

```rust
fn main() {
    println!("{}", 0x8Fi8);
}
```

I expected to see this happen: Getting an error that `0x8F` is out of the bounds for type `i8`.

Instead, this happened: This function compiles and prints `143`.

### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: x86_64-apple-darwin
release: 1.71.1
LLVM version: 16.0.5
```

</p>
</details>

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes https://github.com/rust-lang/rust/issues/115423

`format_args!("{}", 12345u8)` was accidentally accepted, even though that literal is out of range. The literal didn't end up in the expansion of `format_args!()`, because it got simplified to `format_args!("12345")`.

This change is simply to *not* throw away those 'inlined' arguments. This actually simplifies the code in several ways. :)

### CODE REVIEW

**Comment by m-ou-se** [comment]
I just realized that this has a subtle bug, so don't merge this yet. :)

**Comment by WaffleLapkin** [comment]
Have you seen https://github.com/rust-lang/rust/pull/116633 ? It's this a replacement of that PR?

**Comment by m-ou-se** [comment]
Ah, I didn't see that PR. Oops.

That PR fixes the issue too. (It seems to be stuck though?)

There's a subtle difference, and that is that with `#[allow(overflowing_literals)]`, `print!("{}", 1234u8)` with this PR will still result in `1234`, while that PR will result in `210`, which would be more correct.

I really don't understand why overflowing literals is a lint rather than a hard error though.

**Pull request closed without merging**
