### PR TITLE
Stabilize spin_loop_hint

### PR DESCRIPTION
**Pull request by ghost**
Stabilize `spin_loop_hint` in release `1.23.0`.
I've also renamed feature `hint_core_should_pause` to `spin_loop_hint`.

cc #41196

### CODE REVIEW

**Comment by carols10cents** [comment]
Review ping for you @sfackler !

**Comment by sfackler** [comment]
@alexcrichton Do you want to backport this to 1.23 or push it out to 1.24?

**Comment by alexcrichton** [comment]
Nah I'm personally ok leaving it with 1.24

**Comment by alexcrichton** [comment]
egad didn't mean to close...

**Pull request merged**
