### PR TITLE
Encode optimized MIR of generators when emitting metadata

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by hellow554** [comment]
hey @tmiasko 

does your PR also fix this:

```
#![feature(type_alias_impl_trait)]

use std::future::Future;

pub struct Task<F: Future>(F);
impl<F: Future> Task<F> {
    fn new() -> Self {
        todo!()
    }
    fn spawn(&self, _: impl FnOnce() -> F) {
        todo!()
    }
}

fn main() {
    async fn cb() {
        let a = Foo;
    }

    type F = impl Future;
    static POOL: Task<F> = Task::new();
    Task::spawn(&POOL, || cb());
}
```

**Comment by tmiasko** [comment]
Thanks, it looks like there are multiple issues there (and this PR fixes only one of them).

**Comment by hellow554** [comment]
Ok, I posted my code in #80998 and I see you altered your initial post. Thanks!

**Comment by rylev** [comment]
@tmiasko @oli-obk this has some fairly [significant performance regressions](https://perf.rust-lang.org/compare.html?start=a4f022e1099c712fdcc8555fd10caccb1a631877&end=7bb163095d8c751787f1449f3f3c245077f484e3&stat=instructions:u). Is there any way to mitigate that?

**Comment by oli-obk** [comment]
Not really, these performance regressions were "gained" in https://github.com/rust-lang/rust/pull/80718#issuecomment-759499161 due to us forgetting to encode something that is definitely necessary... at least for libraries, not sure whether it makes sense to emit most of this stuff for binaries, and not sure whether we do that at all, but it could be an easy win if we aren't doing it already.

**Pull request merged**
