### PR TITLE
Visit all attributes for feature collection

### PR DESCRIPTION
**Pull request by varkor**
Previously feature attributes were just collected on item-like "things" as well as exported macros and crate attributes. This ignored some places feature attributes could be specified, such as on enum variants.

Fixes https://github.com/rust-lang/rust/issues/53391.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@varkor this is kind of a regression, I suppose?

**Comment by varkor** [comment]
@nikomatsakis: this change potentially permits more features than before (for example the `future_atomic_orderings` feature in https://github.com/rust-lang/rust/issues/53391). It shouldn't disallow any that were previously allowed.

(I also imagine the current behaviour didn't miss many feature attributes, because most would have appeared in tests. `future_atomic_orderings` only didn't because it was deliberately perma-unstable.)

**Comment by nikomatsakis** [comment]
@varkor sorry, to be clear, what I meant is:

This PR is *fixing* a regression where we were previously getting errors about "unrecognized feature" when indeed the feature was legitimate?

In particular I was wondering if we want `p=1`

**Comment by varkor** [comment]
@nikomatsakis: oh, sorry, yes that is the case. `p=1` seems reasonable.

@bors p=1

**Pull request merged**
