### PR TITLE
Beta backport various arielb1 patches

### PR DESCRIPTION
**Pull request by nikomatsakis**
Backport of the following PRs:

- https://github.com/rust-lang/rust/pull/41651
- https://github.com/rust-lang/rust/pull/41828

cc @arielb1 @rust-lang/compiler

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors retry
 - Build just stopped

**Comment by alexcrichton** [comment]
@bors: r-

Looks like a legitimate error?

```
[00:48:58] test [run-pass] run-pass/issue-41696.rs has been running for over 60 seconds
...
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by nikomatsakis** [comment]
@arielb1 any idea why the backport [doesn't fix the problem for #41696](https://github.com/rust-lang/rust/pull/42053#issuecomment-3021006500? is it maybe specific to what version of LLVM the beta is using or something?

**Comment by nikomatsakis** [comment]
Removed #41920

**Pull request merged**
