### PR TITLE
rustdoc: set cfg(doctest) when collecting doctests

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Note: This PR builds on top of https://github.com/rust-lang/rust/pull/61199; only the last commit is specific to this PR.

As discussed in https://github.com/rust-lang/rust/pull/61199, we want the ability to isolate items to only when rustdoc is collecting doctests, but we can't use `cfg(test)` because of libcore's `#![cfg(not(test))]`. This PR proposes a new cfg flag, `cfg(doctest)`, specific to this situation, rather than reusing an existing flag. I've isolated it behind a feature gate so that we can contain the effects to nightly only. (A stable workaround that can be used in lieu of `#[cfg(doctest)]` is `#[cfg(rustdoc)] #[doc(hidden)]`, at least once https://github.com/rust-lang/rust/pull/61351 lands.)

Tracking issue: https://github.com/rust-lang/rust/issues/62210

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
How long do we intend to keep this as a nightly only feature?

**Comment by QuietMisdreavus** [comment]
It probably doesn't need to be unstable for long; users of `doc-comment` who can afford to include the feature flag can provide enough testing, if we're sure it won't interfere with libcore's doctests or the like again.

**Comment by QuietMisdreavus** [comment]
Updated. There was a CI error where the UI test i updated was flaky because the ordering was non-deterministic. I added `--test-threads=1` to the command-line, so that should be fixed now.

**Comment by GuillaumeGomez** [comment]
Once this is merged, I'll have to send "a few" PRs around. \*sigh\* Thanks for this anyway!

**Comment by QuietMisdreavus** [comment]
Force-pushed to resolve merge conflict.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Pull request merged**
