### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by Manishearth**
r? @centril

### CODE REVIEW

**Comment by Centril** [comment]
Not familiar with Clippy's codebase; r? @oli-obk

**Comment by Manishearth** [comment]
It's just a rustup; this is bumping clippy to the new master version. As long as it matches a commit in clippy master it should be fine.

**Comment by Manishearth** [comment]
Review for these is basically a formality

**Comment by Centril** [comment]
@Manishearth Uhm; okay... I guess... but If it is just a formality just r+ yourself :)

r? @Centril @bors r+

**Comment by Manishearth** [comment]
Wasn't sure if that was okay. Then again, we already do that for rollups so _shrug_

**Comment by Manishearth** [comment]
@bors r=centril

seems unrelated?

**Pull request merged**
