### PR TITLE
Fix a typo in the alloc::string::String docs

### PR DESCRIPTION
**Pull request by reedwoodruff**

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
I don't think this is a typo. Instead, I think this is a case of dropping "that" in a relative clause -- i.e. this should be read "The pointer points to an internal buffer [that] `String` uses to store its data."

The internal buffer is not named `String`, so I don't believe the correction is grammatical.

**Comment by workingjubilee** [comment]
I agree, this is not a fix.

**Comment by jhpratt** [comment]
As a native English speaker (as I believe others in this PR so far are), I agree with @compiler-errors. There is an implicit "that" that is omitted. Doing so is correct, but would probably be clearer to non-native speakers if present. I think that would be the change to make, if any.

**Comment by workingjubilee** [comment]
Yeah, that seems like it would be fine.

**Comment by reedwoodruff** [comment]
@compiler-errors 
My mistake, I misunderstood the intent of the sentence. Thank you for catching this. Maybe it would be clearer to change "an internal buffer" to "the internal buffer"? 

>The pointer points to an internal buffer `String` uses to store its data.
> The pointer points to ~~an~~ __the__ internal buffer __which__ `String` uses to store its data.

I think that is what threw me -- it felt like "String" was the name of the internal buffer. I agree now that it is technically correct as-is, but this might help reduce misunderstandings.

**Comment by workingjubilee** [comment]
@reedwoodruff Yeah, that sounds fine.

**Comment by workingjubilee** [comment]
This looks good to me. Thanks!

@bors r+ rollup

**Pull request merged**
