### PR TITLE
 rustc: do not raise the alignment of optimized enums to the niche's alignment.

### PR DESCRIPTION
**Pull request by eddyb**
This is the improved fix for #46769 that does not increase the size of any types (see also #46808).

### CODE REVIEW

**Comment by eddyb** [comment]
(don't mind me, just Travis-cycling the PR)

**Comment by kennytm** [comment]
#46808 has been merged.

**Comment by arielb1** [comment]
Could you please add a test that the size of a packed enum is what it's supposed to be?

@bors r-

**Comment by arielb1** [comment]
Something like this:
```Rust
// This struct has a single niche - the dealigned pointer within. Check that
// it is null-pointer-optimized correctly
struct Interesting {
    packed: Packed<&'static ()>,
    other: u8
}

assert_eq!(mem::size_of::<Interesting>(), mem::size_of::<Option<Interesting>>());
```

**Pull request merged**
