### PR TITLE
Removed superfluous comma

### PR DESCRIPTION
**Pull request by perlun**
This must be a mistake, no?

### CODE REVIEW

**Comment by killercup** [comment]
It's correct, in fact. You can have trailing commas on the last item in structs and enums. This can be helpful when adding new items -- you only have you add one line, not edit one, too. This makes diffs nicer.

**Comment by steveklabnik** [comment]
yes, and this is in fact considered good style. Rust will accept either.

Thank you for sending a PR though!

**Comment by perlun** [comment]
> yes, and this is in fact considered good style. Rust will accept either.

Interesting. This is something that [Rubocop complains about](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/TrailingComma) for Ruby code.

I can agree that it makes diffs nicer, but it makes the code uglier. :wink: 

Is there some tool similar to Rubocop for Rust btw? I mean, some form of basic linter/"best practices" checkup tool? And also, what *are* the agreed "best practices" for Rust? Is there something like [Ruby style guide](https://github.com/bbatsov/ruby-style-guide) for Rust?

**Comment by killercup** [comment]
There is this work-in-progress style guide:
http://doc.rust-lang.org/nightly/style/

I'm not sure there is a linter for style based issues yet. Some part are
default lints (e.g. snake case names for functions). There is rustfmt,
though, which might also fix dangling commas.


Per Lundberg <notifications@github.com> schrieb am Mo., 14. Sep. 2015 um
07:08:

**Comment by perlun** [comment]
And for those wondering where rustfmt is, [here](https://github.com/nrc/rustfmt) be the link.

**Pull request closed without merging**
