### PR TITLE
[DO NOT MERGE] default x64 linux target to x64-v2 for perf test

### PR DESCRIPTION
**Pull request by lqd**
Another perf test like #90440, but on x64-v2.

r? @ghost

### CODE REVIEW

**Comment by lqd** [comment]
Even if we somehow were able to bump to v2 minimum or distribute 2 x64 versions, it would not super interesting by itself. It could help with using SIMD in LEB128 encoding/decoding, or parsing (via pshufb), etc but there are no worthwhile perf gains due to the higher micro arch level itself (which makes sense, they should come mostly from autovectorization in this context, and that would start having noticeable improvements with the higher lane counts of AVX). 

Might as well have up-to-date x64-v3 results, on the new benchmarks and new LLVM, so:
@bors try @rust-timer queue

**Comment by lqd** [comment]
cc @nnethercote

**Comment by nnethercote** [comment]
So v2 has lots of 0.3% to 0.5% wins, while v3 has lots of 1%-3.5% wins.

**Comment by lqd** [comment]
We'd like to have up-to-date numbers for this after the recent LTO changes, so I'll reopen this for a new perf run soon.

**Comment by lqd** [comment]
We should have the data we need, so I'll close this one again.

**Pull request closed without merging**
