### PR TITLE
rust-src: include everything needed to compile libstd with jemalloc

### LINKED ISSUE #41952: rust-src component is incomplete in recent nightlies
The component is missing compiler-rt, jemalloc and other git submodules required to compile the `std` crate. This broke Xargo's use case of cross compiling the `std` crate.

Affected version: `nightly-2017-05-04` and newer

### Workaround

Switch to an older nightly version:

Known good version: `nightly-2017-04-27` (still bisecting)

cc @brson @alexcrichton Do you know of any changes that may have caused this? It seems that the `rust-src` component has been trimmed to not include rustc source?

### PR DESCRIPTION
**Pull request by RalfJung**
I am not very happy about all this `Path::new`, but did not find a nice way to avoid it. Also, this shouldn't be very performance-critical.

With this patch, rust-src-1.19.0-dev.tar.gz grows from 1.4 to 3.1 MiB (new uncompressed size: 15.5 MiB). Not great, but shipping incomplete sources is also not great, and this is still much smaller than pre-#41546. Excluding the entire `src/jemalloc/test` does not work, unfortunately; there is a file in there that is needed to build libstd. (And anyway there's just 190 KiB uncompressed left in that folder.)

In principle, we could try excluding the Rust test suite directories (that would be `libcore/tests` and `libcollection/tests`). I don't know enough about how this component is used to judge whether that would cause any problems. Anyway this is just 600 KiB uncompressed.

Fixes #41952

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

cc @cuviper

**Review by cuviper — APPROVED** [review]
LGTM, thanks!

**Comment by RalfJung** [comment]
I am working on re-basing the patch on top of current master.

**Comment by RalfJung** [comment]
All right, rebase done. @alexcrichton I guess this means I need a new r+?

**Comment by RalfJung** [comment]
Yay :) Maybe even in time for the next nightly :D

**Pull request merged**
