### PR TITLE
Stabilize `unsafe_cell_get_mut`

### PR DESCRIPTION
**Pull request by BoxyUwU**
Tracking issue: #76943 

r? @m-ou-se

### CODE REVIEW

**Comment by m-ou-se** [comment]
@rfcbot merge

This change stabilizes [`UnsafeCell::get_mut()`](https://doc.rust-lang.org/stable/std/cell/struct.UnsafeCell.html#method.get_mut).

**Comment by RalfJung** [comment]
Cc @rust-lang/lang since `UnsafeCell` is a language primitive, not just a library type -- but I agree that adding this operation makes sense.

**Comment by RalfJung** [comment]
@EllenNyan I also have a small proposal for a docs improvement:
> This is showcased by the .get_mut() accessor, which is a non-unsafe getter that yields a &mut T.

Why "non-unsafe"? I think it would make sense to avoid the double negation and just say "*safe*", in italics for emphasis.

**Comment by m-ou-se** [comment]
> Why "non-unsafe"?

That was the original wording added in https://github.com/rust-lang/rust/pull/76936. Looks like there was no discussion about that wording there.

**Comment by danielhenrymantilla** [comment]
Phrasing it as "non-`unsafe`" instead of as "safe" is something I usually do,

  - <details><summary>(For those curious as to why)</summary>

    `unsafe`, with _code_ formatting, has a very specific meaning, relating to the Rust guarantees _w.r.t._ memory (un)safety and contractual UB.

    Hence, non-`unsafe` inherits from this very specific meaning, whereas safe is kind of ambiguous. For instance, I'd rather say that [`::std::fs::remove_dir_all("/")`](https://doc.rust-lang.org/stable/std/fs/fn.remove_dir_all.html) "is not `unsafe`" or "non-`unsafe`", rather than saying it is safe 😉. 

    </details>

and which kind of slipped through my implementation PR, sorry. Since Rust's standard documentation does use "safe" without these concerns of mine, there is no reason not to do that here too, so feel free to rephrase it!

**Comment by BurntSushi** [comment]
@danielhenrymantilla I like that reasoning. I do tend to avoid using `unsafe` anywhere other than where it's actually used, because it means grep produces less noise when looking for uses of `unsafe`. :-)

**Comment by EllenNyan** [comment]
I changed the "non-`unsafe`" to "_safe_" since no-one seems to have any objections and this is more in line with the rest of docs :)

**Comment by m-ou-se** [comment]
@EllenNyan Congrats on getting your first stabilization PR merged! And thanks again!

**Comment by pthariensflame** [comment]
Does this need `relnotes`?

**Pull request merged**
