### PR TITLE
Make note of Hash in Borrow's docs

### LINKED ISSUE #27109: std::borrow::Borrow should have big fat warnings all over it
There are hidden assumptions around `Borrow` that don’t appear to be included in *any* of the documentation that I can find. Most notably, `HashMap`’s use of `Borrow` requires that `K` and `Q` (`where K: Borrow<Q>`) hash the same; if they don’t, your `HashMap` will be mysteriously broken when you try indexing it by `Q`.

I’d suggest making `Borrow` an unsafe trait, but unsafe doesn’t mean <sub>blah blah <sub>mumble mumble memory safety mumble</sub></sub> 😛

Anyway, we need some serious warnings on at least the `Borrow` documentation. Something including things like “if you are implementing `Borrow` and both `Self` and `Borrowed` implement `Hash`, they *must* produce the same result, for HashMap’s sake.”

### PR DESCRIPTION
**Pull request by steveklabnik**
This should be a bit more prominent.

Fixes #27109

### CODE REVIEW

**Comment by Gankro** [comment]
Hash, Eq, *and* Ord must be the same.

**Comment by Gankro** [comment]
Specifically, this is basically the only thing that differentiates it from Deref.

**Comment by steveklabnik** [comment]
@Gankro updated the wording

**Pull request merged**
