### PR TITLE
make use of pointer::is_null

### PR DESCRIPTION
**Pull request by tesuji**
r? @Mark-Simulacrum

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks! This is great.

**Comment by dtolnay** [comment]
r? dtolnay
@bors r+

**Comment by lzutao** [comment]
Removed unused ptr module in hermit, vxworks and wasi.

**Comment by Dylan-DPC** [comment]
@bors r-
(failed in rollup #68087)

**Comment by lzutao** [comment]
I pushed the new changes. Could be re-reviewed?

**Pull request merged**
