### PR TITLE
Stabilize checking of cfgs at compile-time: `--check-cfg` option

### LINKED ISSUE #82450: Tracking Issue for RFC 3013: Checking conditional compilation at compile time
This is a tracking issue for the RFC 3013: Checking conditional compilation at compile time (rust-lang/rfcs#3013).

Issues: https://github.com/rust-lang/rust/labels/F-check-cfg
Documentation: https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/check-cfg.html

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC (cc @rust-lang/compiler  -- can anyone write up mentoring instructions?)
- [X] Adjust documentation ([check_cfg - Unstable book](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/check-cfg.html))
- [ ] Stabilization PR (FCP: https://github.com/rust-lang/rust/issues/82450#issuecomment-1965328542)

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* Which cfgs should be implicitly included? See [this list in bootstrap](https://github.com/rust-lang/rust/blob/4800c7816ee1937d028407066d229f74b4673c92/src/bootstrap/lib.rs#L192) for an example of some values that need "adding in" atop compiler defaults. (Try to go to master in the link above; the list may have been updated since then).

### Implementation history
* #93915
* rust-lang/cargo#10408
* rust-lang/cargo#10428
* rust-lang/cargo#10486
* and [many more](https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3AF-check-cfg)

### PR DESCRIPTION
**Pull request by Urgau**
This PR stabilize the `--check-cfg` CLI option of `rustc` (and `rustdoc`) :tada:.

In particular this PR does two things:
  1. it makes the `--check-cfg` option stable
  2. and it moves the documentation to the stable books

FCP: https://github.com/rust-lang/rust/issues/82450#issuecomment-1965328542

Resolves #82450

@rustbot labels +S-blocked +F-check-cfg
r? @petrochenkov

### CODE REVIEW

**Comment by Urgau** [comment]
FCP has [finished](https://github.com/rust-lang/rust/issues/82450#issuecomment-2054294758) :tada:

@rustbot labels -S-blocked +S-waiting-on-review

**Comment by petrochenkov** [comment]
r=me after rebase.
@rustbot author

**Comment by Urgau** [comment]
Rebased. *(but don't have r+ rights)*

@rustbot ready

**Comment by Urgau** [comment]
Hurrah ! :tada: 

@rustbot label +relnotes

**Pull request merged**
