### PR TITLE
mk: actually run valgrind on x86_64-apple-darwin

### PR DESCRIPTION
**Pull request by tamird**
Since `darwin` is really `apple-darwin`, the valgrind-rpass tests were not actually being run with valgrind on mac before. Also, the `HOST` check was completely wrong.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 952348e39e18aee1f98cccc6ebd596911c0d822d

Hey if it gets past the bots that sounds good to me. Thanks!

**Comment by tamird** [comment]
Needs a retry

**Comment by tamird** [comment]
Can I get another retry? bors seems to have dropped this.

**Comment by pnkfelix** [comment]
@bors force retry

(Is force still a thing?)

**Comment by Manishearth** [comment]
http://buildbot.rust-lang.org/builders/auto-mac-64-opt/builds/7436/steps/test/logs/stdio

**Comment by tamird** [comment]
One of the failures is https://bugs.kde.org/show_bug.cgi?id=201216; can we get valgrind updated on the mac bots? This was fixed in 3.11 (see http://valgrind.org/docs/manual/dist.news.html).

I've updated for the other failures.

**Comment by alexcrichton** [comment]
I'm actually not sure the mac bots will be guaranteed to actually run newer versions of valgrind, they're all running older OSX versions (e.g. 10.7 or 10.8).

I've always thought that valgrind was a little sketchy on OSX?

**Comment by tamird** [comment]
It's sketchy, but it works (I think). We do have special OS X suppressions,
but otherwise things should be workable with 3.11.

**Comment by alexcrichton** [comment]
Unfortunately it's actually pretty nontrivial to upgrade valgrind right now on the OSX bots, can this land without doing that?

**Comment by tamird** [comment]
I suppose if we disabled `run-pass-valgrind/exit-flushes.rs` on OS X, then we could land this. Does that sound worth it?

**Comment by alexcrichton** [comment]
Yeah I think that'd be fine. Hopefully when we move to macstadium it should be easy to upgrade to a new valgrind (and have macs that are consistently online...)

**Comment by tamird** [comment]
OK, done! I'll be offline for the next week or so; I'll circle back and address comments if this doesn't land by then.

Happy holidays!

**Comment by pnkfelix** [comment]
Error message looks legit:

```
failures:

---- [run-pass-valgrind] run-pass-valgrind/osx-frameworks.rs stdout ----
	
error: test run failed!
status: exit code: 100
command: /usr/local/bin/valgrind --error-exitcode=100 --fair-sched=try --quiet --soname-synonyms=somalloc=NONE --suppressions=/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/etc/x86.supp --suppressions=/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/etc/apple-darwin.supp --tool=memcheck --leak-check=full x86_64-apple-darwin/test/run-pass-valgrind/osx-frameworks.stage2-x86_64-apple-darwin
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
==42057== 1,040 bytes in 1 blocks are possibly lost in loss record 337 of 352
==42057==    at 0x6DDC: malloc_zone_malloc (in /usr/local/Cellar/valgrind/3.10.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==42057==    by 0xA5C293: NXCreateMapTableFromZone (in /usr/lib/libobjc.A.dylib)
==42057==    by 0xA6FD40: nonMetaClasses() (in /usr/lib/libobjc.A.dylib)
==42057==    by 0xA61537: objc_registerClassPair (in /usr/lib/libobjc.A.dylib)
==42057==    by 0x96A68: __CFMakeNSBlockClasses (in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation)
==42057==    by 0x7E98E: __CFInitialize (in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation)
==42057==    by 0x7FFF5FC13255: ImageLoaderMachO::doImageInit(ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==42057==    by 0x7FFF5FC13756: ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) (in /usr/lib/dyld)
==42057==    by 0x7FFF5FC1006D: ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) (in /usr/lib/dyld)
==42057==    by 0x7FFF5FC0FFC3: ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&) (in /usr/lib/dyld)
==42057==    by 0x7FFF5FC0FEB9: ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) (in /usr/lib/dyld)
==42057==    by 0x7FFF5FC01FBF: dyld::initializeMainExecutable() (in /usr/lib/dyld)
==42057== 

------------------------------------------

thread '[run-pass-valgrind] run-pass-valgrind/osx-frameworks.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/compiletest/runtest.rs:1505
```

**Comment by tamird** [comment]
Updated to suppress this one.

**Comment by tamird** [comment]
Tidy error. Fixed.

**Comment by tamird** [comment]
ping @pnkfelix

**Comment by tamird** [comment]
Needs another retry :(

**Pull request merged**
