### PR TITLE
run rustfmt on librustc_lint folder

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Comment by GuillaumeGomez** [comment]
@ bors: r+ rollup

**Comment by srinivasreddy** [comment]
@GuillaumeGomez  roll up please. :smile:

**Comment by GuillaumeGomez** [comment]
First, please squash your commits. Then we wait for travis status and after that we roll it up! (The path to r+ is long and difficult but it's worth it haha.)

**Comment by srinivasreddy** [comment]
@GuillaumeGomez 

Haha.

**Comment by srinivasreddy** [comment]
@GuillaumeGomez  Done. roll up please.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Pull request closed without merging**
