### PR TITLE
Add AArch64 big-endian and ILP32 targets

### PR DESCRIPTION
**Pull request by Amanieu**
This PR adds 3 new AArch64 targets:
- `aarch64_be-unknown-linux-gnu`
- `aarch64-unknown-linux-gnu_ilp32`
- `aarch64_be-unknown-linux-gnu_ilp32`

It also fixes some ABI issues on big-endian ARM and AArch64.

### CODE REVIEW

**Comment by nagisa** [comment]
Are the underscore separation conventional in other toolchains? At least in Rust the existing be/le capable targets didn't use the underscore in the `arch` portion of the triple (e.g. `powerpc64` vs `powerpc64le`).

**Comment by Amanieu** [comment]
Both `aarch64_be` and `gnu_ilp32` are used by GCC for their target triples.

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/81620#issuecomment-770748741
libc update causes deprecate warnings, cc https://github.com/rust-lang/libc/issues/1848
@bors r-

**Comment by Amanieu** [comment]
I've updated libc to fix the issue.

I've also fixed some type definitions in `std::os::raw`. This is technically a breaking change, but the previous definitions were completely incorrect.

**Comment by pthariensflame** [comment]
Needs `relnotes`, yes?

**Comment by Amanieu** [comment]
Added.

**Pull request merged**
