### PR TITLE
rustbuild: Add rustbook/standalone doc support

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit implements documentation generation of the nomicon, the book, the
style guide, and the standalone docs. New steps were added for each one as well
as appropriate makefile targets for each one as well.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Would you like me to explore an alternate to this PR which uses mdbook instead? This is something that I've wanted to do for a long time anyway, and this new build system was what would have enabled it; maybe doing it from the start would be nice.

**Comment by alexcrichton** [comment]
It probably wouldn't really be an alternate PR but rather one to just layer on top of this. It'd just involve [changing this line](https://github.com/rust-lang/rust/blob/18f8143530e56a572eaac5ab9ee83023d74bec10/src/rustc/Cargo.toml#L30), perhaps [this source file](https://github.com/rust-lang/rust/blob/18f8143530e56a572eaac5ab9ee83023d74bec10/src/rustc/rustbook.rs), and then tweaking how the tool is actually invoked (just arguments and such).

Other than that, everything here will still be needed in terms of dependency tracking, freshness tracking, etc.

**Comment by steveklabnik** [comment]
Sorry, yes, "Alternate PR" was more like "I'll send a PR to this PR swapping out the bits that were specific to rustbook."

**Comment by alexcrichton** [comment]
Perhaps, we probably should do that incrementally, though. I haven't worked 100% through the flow of incorporating crates.io dependencies just yet beyond build dependencies, and I'd just want to be a little careful in doing so.

**Comment by steveklabnik** [comment]
I figured that might be it, which is why I asked. Sounds good to me.

**Pull request merged**
