### PR TITLE
Add `special_module_name` lint

### PR DESCRIPTION
**Pull request by ibraheemdev**
Declaring `lib` as a module is one of the most common beginner mistakes when trying to setup a binary and library target in the same crate. `special_module_name` lints against it, as well as `mod main;`
```
warning: found module declaration for main.rs
  --> $DIR/special_module_name.rs:4:1
   |
LL | mod main;
   | ^^^^^^^^^
   |
   = note: a binary crate cannot be used as library
   
warning: found module declaration for lib.rs
  --> $DIR/special_module_name.rs:1:1
   |
LL | mod lib;
   | ^^^^^^^^
   |
   = note: `#[warn(special_module_name)]` on by default
   = note: lib.rs is the root of this crate's library target
   = help: to refer to it from other targets, use the library's name as the path
   ```
   
Note that the help message is not the best in that it doesn't provide an example of an import path (`the_actual_crate_name::`), and doesn't check whether the current file is part of a library/binary target to provide more specific error messages. I'm not sure where this lint would have to be run to access that information.

### CODE REVIEW

**Comment by apiraino** [comment]
As per last week T-compiler meeting ([on Zulip](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bweekly.5D.202022-03-31.20.2354818.html#277290877)), I hope if it's fine if I go ahead and assign to a reviewer

r? @pnkfelix

**Comment by pnkfelix** [comment]
@ibraheemdev This looks good to me.

r=me once the tidy issue is resolved, which I think is this thing from the log output:

```
tidy error: /checkout/src/test/ui/modules/dummy.rs:1: CR character
```

(which might be an artifact of your development platform? Let us know if you need help resolving this.)

**Comment by ibraheemdev** [comment]
@pnkfelix this is ready to be merged.

**Comment by JohnCSimon** [comment]
ping from triage:
@ibraheemdev 


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot ready

**Comment by Dylan-DPC** [comment]
failed in [rollup ci](https://github.com/rust-lang/rust/runs/7452246623?check_suite_focus=true) 

@bors r-

**Comment by bjorn3** [comment]
@rustbot ready

(a force push kicked this out of the approval state, but it seems that the labels didn't get updated to reflect this)

**Pull request merged**
