### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
10 commits in 84976cd699f4aea56cb3a90ce3eedeed9e20d5a5..1cff2ee6b92e0ad3f87c44b70b28f788b2528b3c
2024-01-12 15:55:43 +0000 to 2024-01-16 16:56:57 +0000
- doc: add a heading to highlight "How to find features enabled on dependencies" (rust-lang/cargo#13305)
- fix(cargo-update): `--precise` accept arbitrary git revisions (rust-lang/cargo#13250)
- Strip debuginfo when debuginfo is not requested (rust-lang/cargo#13257)
- Update ahash dependency to 0.8.7 (rust-lang/cargo#13301)
- docs: add more links to pkgid spec chapter (rust-lang/cargo#13298)
- fix(metadata): Stabilize id format as PackageIDSpec (rust-lang/cargo#12914)
- Introduce `-Zprecise-pre-release` unstable flag (rust-lang/cargo#13296)
- Delete sentence about parentheses being unsupported in license (rust-lang/cargo#13292)
- Add guidance on setting homepage in manifest (rust-lang/cargo#13293)
- Clarify the function of the test options (rust-lang/cargo#13236)

r? ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
This is most likely the effect of https://github.com/rust-lang/cargo/pull/13257. But it's weird that binary size wasn't reduced :thinking:

**Comment by lqd** [comment]
Stripping by default feels significant enough that it could be mentioned in the release notes?

**Comment by weihanglo** [comment]
> Stripping by default feels significant enough that it could be mentioned in the release notes?

Yeah. The Cargo PR has already got relnote label.

**Comment by Kobzol** [comment]
Perf. wins outweigh the losses by a lot, and this was a Cargo update anyway, so not much we could do.

@rustbot label: +perf-regression-triaged

**Pull request merged**
