### PR TITLE
`bitflags!` uses associated constants

### PR DESCRIPTION
**Pull request by tamird**
Depends on #24888. r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Now that #24888 has landed, could you rebase this as well?

**Comment by alexcrichton** [comment]
Fascinating! Were the changes from constants like `0b001` to `1 << 0` stylistic or because of an ICE?

**Comment by tamird** [comment]
Done!

**Comment by tamird** [comment]
@alexcrichton stylistic :)

**Comment by tamird** [comment]
It's probably a bit of an anti-pattern to have a constant that represents the empty set of flags, since `bitflags!` provides that method. something to revisit in a subsequent PR

**Comment by alexcrichton** [comment]
Yeah it looks like there's a number of stylistic things that may want to be tweaked now that the flags are scoped. For example all of the LLVM attributes end with `Attribute` but now that they're scoped under the name `Attribute` that's a little redundant. It's fine to leave things like that to later though!

@bors: r+ 8c58fe1

**Pull request merged**
