### PR TITLE
Revert "Copy `bin/*` and `lib/*.dylib` files to `stage0-sysroot`"

### PR DESCRIPTION
**Pull request by albertlarsan68**
This reverts commit 6990ab9ad2cde9b67073ffac29ffecc2be8e722f (PR #107956).
Hopefully this reverts the right thing, first time I revert something.
r? @jyn514

### CODE REVIEW

**Review by onur-ozkan — APPROVED** [review]

**Comment by Kobzol** [comment]
@bors try @rust-timer queue

Testing if this fixes bootstrap measurement.

**Comment by jyn514** [comment]
apparently this wasn't even the problem :(
```
       thread 'main' panicked at 'self.symlink_file(&rustfmt_path, &legacy_rustfmt) failed with File exists (os error 17)', download.rs:346:17
```
I'm suspecting https://github.com/rust-lang/rust/pull/107834; cc @zephaniahong

**Comment by albertlarsan68** [comment]
This PR reverts the PR that caused the problem to appear and break perf, but I think there should be a fix.
Let's see if perf is fixed by this revert, and if so, we can land the revert while the correct fix is done.

**Comment by albertlarsan68** [comment]
But I think it is the combination of those two PRs that is the problem, each PR in isolation is good I think.

**Comment by zephaniahong** [comment]
> 



> apparently this wasn't even the problem :(
> 
> ```
>        thread 'main' panicked at 'self.symlink_file(&rustfmt_path, &legacy_rustfmt) failed with File exists (os error 17)', download.rs:346:17
> ```
> 
> I'm suspecting #107834; cc @zephaniahong

May I know what command you ran?

**Comment by KittyBorgX** [comment]
It did pass right?
image

**Comment by zephaniahong** [comment]
Any actions required by me?

**Comment by Kobzol** [comment]
It seems like this didn't help, as there are no bootstrap timings. The failure is probably not shown, because it also failed before this PR I think.

**Comment by albertlarsan68** [comment]
This likely didn't fix it, because the rustc step was less than a minute (I was monitoring the status page)

Does the runner gets a fully new env each time, or is some FS data kept across executions?

**Comment by Kobzol** [comment]
The `rust` directory with the downloaded compiler is maybe cached? But it shouldn't affect anything I hope. I tried to revert the other PR in https://github.com/rust-lang/rust/pull/108302, let's see if that helps. If not, we can also try to revert both of them at once.

**Comment by albertlarsan68** [comment]
This may be the problem, because it complains that the file already exists.
The fix would be to silently ignore this specific failure.

**Comment by Kobzol** [comment]
Where is this file located? I tried to clean the `build` directory of the downloaded `rust` directory locally, and the error persisted:
```
thread 'main' panicked at 'self.symlink_file(&rustfmt_path, &legacy_rustfmt) failed with File exists (os error 17)', download.rs:346:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/core/src/panicking.rs:64:14
   2: bootstrap::download::<impl bootstrap::config::Config>::maybe_download_rustfmt
             at ./src/bootstrap/download.rs:346:17
   3: bootstrap::config::Config::initial_rustfmt
             at ./src/bootstrap/config.rs:1562:28
   4: bootstrap::Build::initial_rustfmt
             at ./src/bootstrap/lib.rs:313:17
   5: bootstrap::Build::build
             at ./src/bootstrap/lib.rs:658:18
   6: bootstrap::main
             at ./src/bootstrap/bin/main.rs:55:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/9aa5c24b7d763fb98d998819571128ff2eb8a3ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
(This might be the second error though, it's a bit confusing).

**Comment by zephaniahong** [comment]
@Kobzol The symlink file should be in `./build/host/rustfmt/bin`

**Comment by Kobzol** [comment]
Aha, the problem is in another directory. From `rustc-perf`:
```console
$ rm -rf rust/build
$ RUST_BACKTRACE=1 cargo run --bin collector bench_local --id dc89a803d64fb6172c8406996831353bee18c3a7 /home/kobzol/.rustup/toolchains/nightly-2023-02-18-x86_64-unknown-linux-gnu/bin/rustc --bench-rustc --iterations 1 --cargo /home/kobzol/.rustup/toolchains/nightly-2023-02-18-x86_64-unknown-linux-gnu/bin/cargo --include await

(examined with strace)
[pid 40260] symlink("/projects/personal/rust/rustc-perf/rust/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt", "/projects/personal/rust/rustc-perf/target/debug/rustfmt") = -1 EEXIST (File exists)
```
So the problem is that `rustfmt` already exists in `target/debug`. Why is it trying to write something into `target/debug` of `rustc-perf` though? :thinking:

**Comment by albertlarsan68** [comment]
Does this has to do with (maybe) the fake Rustc shims?

**Comment by KittyBorgX** [comment]
> Aha, the problem is in another directory. From `rustc-perf`:
> 
> ```
> $ rm -rf rust/build
> $ RUST_BACKTRACE=1 cargo run --bin collector bench_local --id dc89a803d64fb6172c8406996831353bee18c3a7 /home/kobzol/.rustup/toolchains/nightly-2023-02-18-x86_64-unknown-linux-gnu/bin/rustc --bench-rustc --iterations 1 --cargo /home/kobzol/.rustup/toolchains/nightly-2023-02-18-x86_64-unknown-linux-gnu/bin/cargo --include await
> 
> (examined with strace)
> [pid 40260] symlink("/projects/personal/rust/rustc-perf/rust/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt", "/projects/personal/rust/rustc-perf/target/debug/rustfmt") = -1 EEXIST (File exists)
> ```
> 
> So the problem is that `rustfmt` already exists in `target/debug`. Why is it trying to write something into `target/debug` of `rustc-perf` though? 🤔

From my knowledge, It should ideally write to `build/host/stage0/bin/rustfmt` 
So the symlink should be: 
```
build/host/rustfmt/bin/rustfmt -> build/host/stage0/bin/rustfmt
```

**Comment by lqd** [comment]
> Does this has to do with (maybe) the fake Rustc shims?

I'd think so.

`build.rustc` is [`bootstrap-rustc`](https://github.com/rust-lang/rustc-perf/blob/master/collector/src/bin/bootstrap-rustc.rs) in the [rustc benchmark](https://github.com/rust-lang/rustc-perf/blob/9a84c57c925566771e5ccf518b53b94ba1e8ff5e/collector/src/execute/rustc.rs#L77-L79).

It's a local binary path, that makes bootstrap think `initial_rustc` is in `./target/{debug,release}` when trying to symlink, and `legacy_rustfmt`  is [then](https://github.com/rust-lang/rust/blob/3fee48c161a48b0c142d3998fff56faee96bd56c/src/bootstrap/download.rs#L344) thought to be in that local directory.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/108302 fixed perf, right? Does that mean we can close this revert?

**Comment by Kobzol** [comment]
Yes, this can be closed now.

**Pull request closed without merging**
