### PR TITLE
Remove rustc_mir dependency from rustc_borrowck

### PR DESCRIPTION
**Pull request by matthewjasper**
Also renames `rustc_borrowck` to `rustc_ast_borrowck` and removes all error reporting from it.

cc #59193

### CODE REVIEW

**Comment by varkor** [comment]
I don't think I'll have time to review something this large very soon, so I'm going to reassign.

r? @pnkfelix

**Comment by pnkfelix** [comment]
Sorry it’s taken me so long to see this 

The diff for at least one file (borrowck/mod.rs) seems  like github did not see the initial move due to the crate rename. Could we save the rename for a different PR? Or at least a separate commit in the series?

**Comment by matthewjasper** [comment]
This is now split into two commits

**Comment by pnkfelix** [comment]
r=me once merge conflicts are resolved. Sorry for taking so long to get back around to this.

**Pull request merged**
