### PR TITLE
publish_toolstate: don't use 'new' from inside the loop

### PR DESCRIPTION
**Pull request by RalfJung**
I think I made a mistake in https://github.com/rust-lang/rust/pull/61938 by using `new` outside the inner loop. This PR fixes that.

However, no issue got created at all for https://github.com/rust-lang/rust/pull/62003#issuecomment-504356964, and I don't know why that is.   The script should be [triggered by Traivs](https://github.com/rust-lang/rust/blob/56a12b2ad058f22f1ef090713df15598525ba4a4/.travis.yml#L240), and I can find no trace of that in [the build log](https://travis-ci.com/rust-lang/rust/jobs/209880042).

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @kennytm @rust-lang/infra

**Comment by RalfJung** [comment]
Oh I see, the push would happen elsewhere, namely when the branch actually hits master. That would be [this log](https://travis-ci.com/rust-lang/rust/builds/116404495). And that log contains `I/O error: HTTP Error 422: Unprocessable Entity`. Not sure why though.

**Comment by ehuss** [comment]
Yea, I noticed the same thing in https://github.com/rust-lang/rust/issues/61693. Clippy has never opened a new issue when it has failed.   Unfortunately the body of the error is not logged.  I recommend at least updating the error handling to do that to understand why it is hitting 422.

I thought about running the command locally with my own api key to see what the message is, but I was concerned about creating issues and pinging a bunch of people if it worked.

**Comment by RalfJung** [comment]
> I recommend at least updating the error handling to do that to understand why it is hitting 422.

How would I do that? I don't know the involved python libs very well.

**Comment by ehuss** [comment]
Something like the following should work.

```diff
diff --git a/src/tools/publish_toolstate.py b/src/tools/publish_toolstate.py
index 9e7c18b7f5..c7bfd8a1ab 100755
--- a/src/tools/publish_toolstate.py
+++ b/src/tools/publish_toolstate.py
@@ -164,6 +164,8 @@ def update_latest(
                         tool, new, MAINTAINERS.get(tool, ''),
                         relevant_pr_number, relevant_pr_user, pr_reviewer,
                     )
+                except urllib2.HTTPError as e:
+                    print("HTTPError: {0} {1}".format(e, e.read()))
                 except IOError as e:
                     # network errors will simply end up not creating an issue, but that's better
                     # than failing the entire build job
```

**Comment by RalfJung** [comment]
Okay, I added something like that.

**Comment by kennytm** [comment]
```json
{"message":"Validation Failed","errors":[{"value":"llogiq","resource":"Issue","field":"assignees","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/issues/#create-an-issue"}
```

🤔

**Comment by ehuss** [comment]
That's weird, perhaps the assignee must be at least a collaborator?  I can't find anything that mentions any restrictions like that.  However, that makes sense because if you go to a github issue and click "assign", the only options are members/collaborators.

I read that statement in the docs that if you don't have "push" access, all assignees will be dropped.  Presumably the bot has push access, but this is hitting the additional requirements.

**Comment by RalfJung** [comment]
Oooh so this is actually unrelated to my PR, and related to whether the author of the breaking PR is a team member? That explains so much! I had noticed a missing Miri issue some time ago already but it worked the next time so I thought it was fixed.

So probably having the PR author as assignee is not a good idea then?

**Comment by RalfJung** [comment]
@kennytm so this should fix the problem of not being able to assign non-team-members, and it also adds some more logging for the next time we have a problem. Does that seem reasonable?

**Pull request merged**
