### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by workingjubilee**
Successful merges:

 - #131669 (lint: change help for pointers to dyn types in FFI)
 - #133265 (Add a range argument to vec.extract_if)
 - #133733 ( compiletest: show the difference between the normalized output and the actual output for lines which didn't match)
 - #133955 (Pass the arch rather than full target name to windows_registry::find_tool)
 - #133967 ([AIX] Pass -bnoipath when adding rust upstream dynamic crates)
 - #133976 (Removed Unnecessary Spaces From RELEASES.md)
 - #133980 ([AIX] Remove option "-n" from AIX "ln" command)
 - #133987 (Define acronym for thread local storage)
 - #133992 (Actually walk into lifetimes and attrs in `EarlyContextAndPass`)
 - #133993 (Fix: typo in E0751 error explanation)
 - #133996 (Move most tests for `-l` and `#[link(..)]` into `tests/ui/link-native-libs`)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=131669,133265,133733,133955,133967,133976,133980,133987,133992,133993,133996)

### CODE REVIEW

**Comment by workingjubilee** [comment]
Can't be spurious...

**Comment by jieyouxu** [comment]
I thought this was #133955 too, but same failure on rollup that didn't include that PR.

**Pull request closed without merging**
