### PR TITLE
Bump version, upgrade bootstrap

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates the version number to 1.17.0 as we're not on that version of
the nightly compiler, and at the same time this updates src/stage0.txt to
bootstrap from freshly minted beta compiler and beta Cargo.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

Also cc @nagisa, @est31 about the i128 staging changes. Would be good to have a second pair of eyes!

**Comment by nagisa** [comment]
Changes look good to me.

**Comment by est31** [comment]
LGTM to me as well. But we'll only know for sure once bors says its okay :) Also, `impl LargeInt for u64` and `impl LargeInt for i64` could be removed from compiler builtins as well, if I'm not mistaken.

**Comment by alexcrichton** [comment]
@est31 removed!

**Comment by alexcrichton** [comment]
@bors: p=1

(requested by @nagisa)

**Comment by alexcrichton** [comment]
@bors: retry

* `cargo test` failed to delete a file... here's to praying it's spurious!

**Comment by alexcrichton** [comment]
@bors: retry

* sccache wedged #39003

**Comment by est31** [comment]
Hmm it seems like a spurious bug with Cargo. If [code that created this error](https://github.com/rust-lang/cargo/blob/609371f0b4d862a94e2e3b8e4e8c2a4a2fc7e2e7/src/cargo/ops/cargo_rustc/mod.rs#L460) gets executed with itself in parallel, then it can in theory both times assume that dst exists, leading to the remove being attempted. One instance will then succeed, while the other instance will fail as the file was already removed. According to this [playground example](https://play.rust-lang.org/?gist=1d3fbd4ae6abbc5b9fd2142afd13e631&version=stable&backtrace=0), attempting to non existent files leads in the NotFound error kind. Maybe ignore the error if that's the case?

Either way, it looks like the error is spurious, so a retry should be attempted.

**Comment by alexcrichton** [comment]
Thanks for the investigation @est31, I'll keep digging and see if I can't come up with a solution.

For now I've backed out the update to Cargo, filed https://github.com/rust-lang/rust/issues/39504 to track the future update, and otherwise let's land the removal of the i128 staging

@bors: r+

**Pull request merged**
