### PR TITLE
Remove lock guarantee from `std::env::{set_var, remove_var}`

### PR DESCRIPTION
**Pull request by tbu-**
CC #124866.
CC https://github.com/rust-lang/rust/pull/124636#discussion_r1613386094.

### CODE REVIEW

**Comment by RalfJung** [comment]
> I believe this lock guarantee does not give us anything on environments where accessing environment variables is unsafe, such as on Linux with glibc. Adding such a lock would be useful in a Rust-only target where libc is not linked.

It avoids UB in some cases, like safe Rust code where one `#[test]` reads the environment and another `#[test]` writes it and it happens to be the case that no C function is called anywhere (at least none that accesses the environment).
Given that this UB is *entirely our fault* (by pretending that the environment can be safely mutated), I don't think we should let our users suffer the consequences of our past mistakes.

So to me the question is -- is this a first step towards eventually actually removing the lock from the implementation?Because that is something I do not think should happen any time soon. With this PR the affected code "just" has library UB but is actually still well-defined in the op.sem, but once we remove the lock that would become language UB.

**Comment by tbu-** [comment]
> So to me the question is -- is this a first step towards eventually actually removing the lock from the implementation?Because that is something I do not think should happen any time soon.

I also do not want that to happen anytime soon, but maybe in 10 years or so, when environment variable modifications have largely been removed from Rust.

> It avoids UB in some cases, like safe Rust code where one `#[test]` reads the environment and another `#[test]` writes it and it happens to be the case that no C function is called anywhere (at least none that access the environment).

I'm unsure there's code out there that can somehow guarantee that no C function is called anywhere in the tests, but I can see the comment in the documentation leading people to believe that they can guarantee it.

**Comment by joshtriplett** [comment]
I don't think we should make this change. I think even decades from now we're not going to remove this synchronization (except on platforms where environment manipulation is already thread-safe). And given that, I think we should document the synchronization we do, together with the detailed set of caveats we already document.

**Comment by tbu-** [comment]
> I think even decades from now we're not going to remove this synchronization

Can you explain a **sound use case of this lock**? I can't think of any Rust application that could use it.

If we don't have any sound use case of the lock, why do we document it, even if it makes people think their use case is covered when it is not?

**Comment by workingjubilee** [comment]
In practice, open source libcs do not update environment variables implicitly and are fairly restrained in checking them.

They... also have opinions about the use of `getenv` and `setenv`. Not positive ones:

https://github.com/freebsd/freebsd-src/blob/04a191c251e5ef20deb14fcdcf628a589be5216a/lib/libc/net/nsdispatch.c#L347-L352

While they may be dedicated to maintaining their API and assigning blame for its misuse to the callers of the library, I do not think treating them as _pure adversary_ in this matter is correct. Just because they are, in some cases, averse to adopting nonstandard extensions does not mean they are _excited_ about their use of environment variables and inclined to recklessly do so.

I do not view documenting these locks as necessary, but neither would I want to remove them because the protection is "useless".

**Comment by carbotaniuman** [comment]
The Rust environment lock is a false sense of security, and the documentation should definitely remove any mention of it, although I would be loathe to remove the lock in practice.

Rust made a mistake here. It's great that we're fixing the mistakes, but attempting to hide the fact that we made a mistake by documenting the lock doesn't make sense.

I consider this similar to men::uninit here, in that while the lang "spec" (consensus, etc) may require locks around these functions (similar to the 0x1 filling), documenting that fact will only exacerbate the pain.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting. We don't feel that this diff is making either our guarantees or the use of this function any clearer. The current documentation accurately describes the current code, and removing that documentation will not change any assumptions *existing* code has made. Thus, we don't think this documentation change makes any difference for any future code change we might make.

This FCP close isn't making any decisions about any future code changes we might make regarding the lock.

@rfcbot close

**Comment by cuviper** [comment]
@rfcbot reviewed

... but did you mean this to be a libs-api FCP?

**Comment by tbu-** [comment]
> The current documentation accurately describes the current code, and removing that documentation will not change any assumptions _existing_ code has made.

(This doesn't really answer https://github.com/rust-lang/rust/pull/125937#issuecomment-2148079727, "can we find any way where existing code makes useful assumptions about the lock")

> This FCP close isn't making any decisions about any future code changes we might make regarding the lock.

I don't really understand this. AFAIUI, the documentation is usually what guarantees how stuff works, i.e. in my understanding, this documentation **does** prevent us from changing how the lock works in the future.

Anyway, would you accept a pull request that specifies this, saying that the lock isn't guaranteed (since apparently this documentation doesn't change whether you decide to make a code change or not)?

**Pull request closed without merging**
