### PR TITLE
bootstrap: Link LLVM as a dylib with ThinLTO

### PR DESCRIPTION
**Pull request by alexcrichton**
When building a distributed compiler on Linux where we use ThinLTO to
create the LLVM shared object this commit switches the compiler to
dynamically linking that LLVM artifact instead of statically linking to
LLVM. The primary goal here is to reduce CI compile times, avoiding two+
ThinLTO builds of all of LLVM. By linking dynamically to LLVM we'll
reuse the one ThinLTO step done by LLVM's build itself.

Lots of discussion about this change can be found [here] and down. A
perf run will show whether this is worth it or not!

[here]: https://github.com/rust-lang/rust/pull/53245#issuecomment-417015334

### CODE REVIEW

**Comment by alexcrichton** [comment]
@rust-timer build a8b3bd70936e9ce4e4db4aaf7b4a4cae6b8f3d39

**Comment by alexcrichton** [comment]
Ok, so here's some information about this PR now:

The first attempt, found in just the first commit, changes the Linux dist builders to build LLVM with ThinLTO but then links rustc against the dynamic library produced. This means that rustc doesn't rerun ThinLTO throughout the stages. It also means, though, that we need to copy around the LLVM dynamic library when creating the sysroot. This attempt's [benchmarks were pretty bad](https://perf.rust-lang.org/compare.html?start=041254b81495a5aa67af839e00b890e78ed0cbeb&end=a454167f2914c0ef3e34f7b63654485f8e276b78), though. Local profiling showed that this was most likely due to the fact that we [use `RTLD_NOW` when opening the codegen backend](https://github.com/rust-lang/rust/blob/d99a320cba42f661aebfa1293b7b2ec3603dda75/src/librustc_driver/lib.rs#L222-L228) and the dynamic linker was processing a whole lot more symbols (all in LLVM).

The second attempt, outlined in the second commit, eschews `RTLD_NOW` and instead just uses the normal `open` that we've implemented. Benchmarks [then confirmed that this change doens't regress performance](https://perf.rust-lang.org/compare.html?start=cb84844e83ee88684ef89cc02221a26abbf92530&end=a8b3bd70936e9ce4e4db4aaf7b4a4cae6b8f3d39), as expected. Apparently the dynamic linker can be a sizable portion of our runtimes! Probably not a good sign that we have so many dynamic libraries... In any case this commit broke tests because `RTLD_NOW` was explicitly added to enusre that our one test for an LLVM plugin kept working.

The current PR, outlined in the final commit, deletes the test that we can load an LLVM plugin at runtime. I feel like the writing has been on the wall for this test for quite some time now. LLVM plugins were always unstable and AFAIK aren't even used at all any more. When they *could* be used, they were extremely difficult to use.

Technically this PR is a regression in unstable functionality, but I personally feel that it's worth it. Taking a look at the [try build](https://travis-ci.org/rust-lang/rust/builds/469715608?utm_source=github_status&utm_medium=notification) compared against the [previous auto build](https://travis-ci.org/rust-lang/rust/builds/469249414) we see:

|  builder | time before | time after |
|---------|------------|-------------|
| dist-x86_64-linux | 2h13m | 1h45m |
| dist-x86_64-linux-alt | 2h19m | 2h1m |

Here we're seeing 20+ minute reductions in build time for these builders, thanks to the fewer runs of ThinLTO we're having them do. That alone is worth it I believe because these builders are some of the slowest on Travis.

**Comment by Mark-Simulacrum** [comment]
I agree that we should go ahead and do this; LLVM plugins are not something that we need to support and the wins are substantial. Plus, if necessary, we can revert.

I would also be interested in seeing if we could investigate the dynamic linker performance further to see if we might be able to get away with loading less symbols overall and perhaps speed up tests...

**Comment by michaelwoerister** [comment]
I'm also in favor of moving forward with this. The slight regression we see now is small compared to what ThinLTO'd LLVM gained us in the first place and this change should allow us to enable ThinLTO for LLVM on the other major platforms (right?). 

cc @rust-lang/wg-compiler-performance (so the slowdown for small crates doesn't come as a surprise)

Also, before r+ing, cc some LLVM folks who might be interested in the implications on LLVM plugins: @rkruppe @nikic (who else?)

Also, cc @tromey. I'm not sure if this will affect LLDB somehow (I suspect it won't).

Thanks a lot for looking into this, @alexcrichton! :heart:

**Comment by rkruppe** [comment]
Really nice wins! ❤️ 

Regarding impact on LLVM plugins, well, this is also true from the LLVM perspective:

> I feel like the writing has been on the wall for this test for quite some time now.

The new pass manager has never supported dynamically loaded passes and is getting closer and closer to becoming the default. As far as I know nobody stepped up to even design plugins for the new pass manager, let alone see through implementation.

**Comment by michaelwoerister** [comment]
Alright, sounds like we can do this.

@bors r+

**Comment by Centril** [comment]
@bors retry

(Included in https://github.com/rust-lang/rust/pull/57094)

**Pull request merged**
