### PR TITLE
ci: Bring back ninja for dist builders

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
The primary reason for this is that make can result in a substantial under utilization of parallelism (noticed while testing on a workstation), mostly due to the submake structure preventing good dependency tracking and scheduling.

In f758c7b2a78 (Debian 6 doesn't have ninja, so use make for the dist builds) llvm.ninja was disabled due to lack of distro package. This is no longer the case with the CentOS 7 base, so bring ninja back for a performance boost.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
If that's the case I suppose it won't be much different this time, though one benefit of this is that it's quite handy when you test CI builds on a high-core workstation (make can only achieve ~32 load average out of 128 cores).

**Comment by ishitatsuyuki** [comment]
Comparing the final build of LLVM (which doesn't hit the cache due to PGO) of this PR to a recent master build (https://github.com/rust-lang-ci/rust/actions/runs/3301120227/jobs/5447282596), this PR took 15m11s while the master build took 12m58s.

It looks like the CI machines suffers a lot from noisy neighbors though, hence I don't think we'll be able to get a conclusion of significance out of the timings.

Given the simplicity of doing this (we don't need extra build-from-source scripts unlike #96969) I still think this is worth doing, mainly for convenience of testing on many-core machines.

**Comment by Kobzol** [comment]
@bors try

(we should do multiple builds, preferably in rapid succession, to make sure that caches are primed)

**Comment by ishitatsuyuki** [comment]
Sure, a successive build would hit the Docker and first-stage LLVM cache, but what are we trying to measure here? Given the variance of CI machines, we'll need hundreds of builds to get a statistically significant comparison, which I don't think is worth the effort.

The timing I measured above is from the PGOed build, whose --instr-use flag explicitly disable sccache. I doubt cache is what that matters here.

**Comment by Kobzol** [comment]
Yeah it's not about statistical significance, just to see the final `dist` build number without the broken Docker cache, so that we can make sure that it stays in the same ballpark.

**Comment by mati865** [comment]
While comparing times you should also check CPU on particular runner (I think it's still logged). Discrepancy between slowest and fastest machines is rather big on GHA.

**Comment by ishitatsuyuki** [comment]
OK, sccache is hitting now, but the Docker one doesn't. Maybe the cache key is different for try builds?

**Comment by Kobzol** [comment]
@bors try

From my experience it's just a matter of running the build 2-3 times in a quick succession to make all caches work.

**Comment by ishitatsuyuki** [comment]
2h11m on Skylake, time looks fine.

**Comment by ishitatsuyuki** [comment]
Any opinions on whether this should be pushed forward?

**Comment by cuviper** [comment]
We use ninja on every other dist builder, so I see no reason why we shouldn't here.

@bors r+ rollup=never (because of the caching effects)

**Comment by cuviper** [comment]
Should be faster with the docker image now primed...

@bors retry

**Comment by cuviper** [comment]
Any idea what happened to perf? Perhaps this disrupted LTO/PGO?

**Comment by nnethercote** [comment]
Could be. @Kobzol, what do you think?

**Comment by ishitatsuyuki** [comment]
Note that only the `check` results are mainly disrupted (hence the regression is on the Rust code side). I'll take a day to see if I can find some obvious cause, but if I don't reply in 1 day please feel free to revert it until the root cause is figured out.

**Comment by Kobzol** [comment]
I have no idea why there should be regressions from switching to `ninja`. I'll file a revert to see if it helps.

**Comment by rylev** [comment]
Looks like the revert shows reverting the [performance regressions as well](https://github.com/rust-lang/rust/pull/103846#issuecomment-1299483877). Would it make sense to revert until we can figure out why?

**Comment by ishitatsuyuki** [comment]
Yes, I think we should go for the revert. I did look into the CI logs and tried to figure out if it's LTO or PGO, but I'm completely clueless and it seems unlikely I'll be able to reland this in the predictable future.

**Pull request merged**
