### PR TITLE
submodule: update clippy from 6ce78d1 to 3bda548

### PR DESCRIPTION
**Pull request by h-michael**
https://github.com/rust-lang/rust-clippy/compare/6ce78d1...3bda548

Rustup: unused trim result
Auto merge of #3727 - phansch:rustup_unused_trim, r=matthiaskrgr  …
Travis: Don't run integration tests on every PR commit  …
Auto merge of #3726 - phansch:some_renaming, r=oli-obk  …
Fix ICE in vec_box lint and add run-rustfix  …
Make vec_box MachineApplicable
Remove conditionals from base builds  …
Adding lint for too many lines.
Updating number of lines for the failing test to be > 100.  …
Running util/dev to update README/CHANGELOG
Reworking function logic, and adding doc example.  …
Moving tests to ui-toml to make use of clippy.toml
rustfmt
Adding back tests, but also reducing threshold by 1
Updating to just warn for one test.
Fix test broken by removing comment.
Skipping check if in external macro.
Adding lint for too many lines.
Updating number of lines for the failing test to be > 100.  …
Moving tests to ui-toml to make use of clippy.toml
rustfmt
Adding back tests, but also reducing threshold by 1
Updating to just warn for one test.
Fix test broken by removing comment.
Changing single character string to a character match.
Updated readme.
Updating code to ignore rustfmt issue.
phansch and avborhanian
Update clippy_lints/src/types.rs  …
Update clippy_lints/src/types.rs  …
Auto merge of #3732 - phansch:fix_ice_3720, r=oli-obk  …
Auto merge of #3731 - phansch:travis, r=phansch  …
Auto merge of #2857 - avborhanian:master, r=phansch  …
Fix breakage due to rust-lang/rust#58079  …
Auto merge of #3736 - mikerite:fix-build-20190203, r=phansch  …

related with: #58024

### CODE REVIEW

**Comment by h-michael** [comment]
@Xanewok I execute `./x.py build` and abort.
But nothing changes.

**Comment by Xanewok** [comment]
Ah, the Clippy version seems frozen, my bad.

Looks good, @oli-obk I hope you don’t mind me merging this ASAP; I’d like to unbreak the pending RLS update.

r? @Xanewok

@bors r+ p=1

**Comment by h-michael** [comment]
@Xanewok Could you retry?

**Comment by h-michael** [comment]
@Xanewok Did boars work?

**Pull request merged**
