### PR TITLE
Migrate `rlib-format-packed-bundled-libs` and `native-link-modifier-bundle` `run-make` tests to rmake

### PR DESCRIPTION
**Pull request by Oneirical**
Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

Please try:

// try-job: test-various (ATTEMPTED: IGNORE RESTORED)
try-job: x86_64-msvc
try-job: aarch64-apple
try-job: aarch64-gnu
try-job: x86_64-mingw
try-job: i686-mingw

### CODE REVIEW

**Comment by Oneirical** [comment]
As expected, only the last part of each test fails on MSVC. Instead of ignoring the whole test, I added an `!is_msvc()` check to run the final phase of each test. @rustbot ready

**Review by jieyouxu — APPROVED** [review]
Thanks, changes look good to me, need to run try-jobs to double check.

**Comment by jieyouxu** [comment]
r=me with a rebase

**Pull request merged**
