### PR TITLE
Update pulldown-cmark version

### LINKED ISSUE #59194: Update to last pulldown-cmark version
Last version (0.3.0) is finally here!

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #59194.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
```
[01:45:26] std/sync/atomic/struct.AtomicIsize.html:3: absolute path - /checkout/src/libcore/std/primitive.isize.html
[01:45:26] std/sync/atomic/struct.AtomicUsize.html:3: absolute path - /checkout/src/libcore/std/primitive.usize.html
[01:45:26] std/sync/atomic/struct.AtomicU32.html:3: absolute path - /checkout/src/libcore/std/primitive.u32.html
[01:45:26] std/sync/atomic/struct.AtomicI64.html:3: absolute path - /checkout/src/libcore/std/primitive.i64.html
[01:45:26] std/sync/atomic/struct.AtomicI32.html:3: absolute path - /checkout/src/libcore/std/primitive.i32.html
[01:45:26] std/sync/atomic/struct.AtomicU64.html:3: absolute path - /checkout/src/libcore/std/primitive.u64.html
[01:45:26] std/sync/atomic/struct.AtomicU8.html:3: absolute path - /checkout/src/libcore/std/primitive.u8.html
[01:45:26] std/sync/atomic/struct.AtomicU16.html:3: absolute path - /checkout/src/libcore/std/primitive.u16.html
[01:45:26] std/sync/atomic/struct.AtomicI16.html:3: absolute path - /checkout/src/libcore/std/primitive.i16.html
[01:45:26] std/sync/atomic/struct.AtomicI8.html:3: absolute path - /checkout/src/libcore/std/primitive.i8.html
[01:45:32] thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:41:9
[01:45:32] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:45:32] 
[01:45:32] 
[01:45:32] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/linkchecker" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc"
[01:45:32] expected success, got: exit code: 101
```

Why was the atomics doc change included in this PR?

**Comment by GuillaumeGomez** [comment]
I saw the error and I removed the useless full path. :-.

**Comment by GuillaumeGomez** [comment]
And fixed the error.

**Comment by GuillaumeGomez** [comment]
... Or maybe not...

**Comment by QuietMisdreavus** [comment]
```

[01:54:46] ---- [run-make] run-make-fulldeps/rustdoc-error-lines stdout ----
[01:54:46] 
[01:54:46] error: make failed
[01:54:46] status: exit code: 2
[01:54:46] command: "make"
[01:54:46] stdout:
[01:54:46] ------------------------------------------
[01:54:46] make[1]: Entering directory '/checkout/src/test/run-make-fulldeps/rustdoc-error-lines'
[01:54:46] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/rustdoc-error-lines/rustdoc-error-lines:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc' -L /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib --test input.rs > /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/rustdoc-error-lines/rustdoc-error-lines/output || true
[01:54:46] "/checkout/src/etc/cat-and-grep.sh" 'input.rs:7:15' < /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/rustdoc-error-lines/rustdoc-error-lines/output
[01:54:46] [[[ begin stdout ]]]
[01:54:46] [90m
[01:54:46] running 1 test
[01:54:46] test input.rs - foo (line 6) ... FAILED
[01:54:46] 
[01:54:46] failures:
[01:54:46] 
[01:54:46] ---- input.rs - foo (line 6) stdout ----
[01:54:46] error[E0308]: mismatched types
[01:54:46]  --> input.rs:8:15
[01:54:46]   |
[01:54:46] 4 | let x: char = 1;
[01:54:46]   |               ^ expected char, found u8
[01:54:46] 
[01:54:46] error: aborting due to previous error
[01:54:46] 
[01:54:46] For more information about this error, try `rustc --explain E0308`.
[01:54:46] thread 'input.rs - foo (line 6)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
[01:54:46] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:54:46] 
[01:54:46] 
[01:54:46] failures:
[01:54:46]     input.rs - foo (line 6)
[01:54:46] 
[01:54:46] test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:54:46] 
[01:54:46] [0m
[01:54:46] [[[ end stdout ]]]
[01:54:46] [1;31mError: cannot match: input.rs:7:15[0m
[01:54:46] Makefile:7: recipe for target 'all' failed
```

Looks like the test `run-make-fulldeps/rustdoc-error-lines` makes sure that the span information given from doctests is correct, but this change messed up the line numbers? The test is looking for the string "`input.rs:7:15`" in the output, but it looks like the actual string was "`input.rs:8:15`". [Looking at the test file being run](https://github.com/rust-lang/rust/blob/master/src/test/run-make-fulldeps/rustdoc-error-lines/input.rs), it looks like it's supposed to be line 7, so i'm going to guess that something in the update messed with line counting.

**Comment by Centril** [comment]
Ping from triage, @GuillaumeGomez, you need to rebase and also see https://github.com/rust-lang/rust/pull/59349#issuecomment-477170600.

**Comment by GuillaumeGomez** [comment]
I also need to update for a new pulldown-cmark release.

**Comment by QuietMisdreavus** [comment]
If we need to wait for upstream pulldown to update, should we even keep this PR open?

**Comment by GuillaumeGomez** [comment]
As you prefer?

**Comment by QuietMisdreavus** [comment]
If we expect it to be a while before the crate updates (and if we require the update to fix the test issue), i would rather close this PR so we don't have it dangling.

**Comment by GuillaumeGomez** [comment]
Let's close it then.

**Comment by marcusklaas** [comment]
pulldown-cmark 0.4.1 was published today: https://crates.io/crates/pulldown-cmark

**Comment by GuillaumeGomez** [comment]
Thanks for the notification. I'll make another PR.

**Pull request closed without merging**
