### PR TITLE
Update clippy

### LINKED ISSUE #65683: `clippy-driver` no longer builds after rust-lang/rust#65671
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#65671, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by tesuji**
Replaces #65690
cc  #65503
Closes #65683

### CODE REVIEW

**Comment by lzutao** [comment]
cc @flip1995 , @oli-obk, @Centril 
r? @Manishearth

**Comment by RalfJung** [comment]
Does this make enough types from libtest public again to fix https://github.com/laumann/compiletest-rs/issues/197 ?

**Comment by lzutao** [comment]
yes, at least for compiletest_rs v0.3.25.

**Pull request merged**
