### PR TITLE
Un-stabilize --extern-private option in rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #66211 

cc @kinnison 
r? @ollie27

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust/pull/66655

**Comment by GuillaumeGomez** [comment]
@jonas-schievink Indeed. But our codes diverge a bit... I wonder if my extra change is actually useful... cc @ollie27

**Comment by GuillaumeGomez** [comment]
No it's not, closing then!

**Comment by Dylan-DPC** [comment]
@GuillaumeGomez you ruined #66666 😂

**Comment by GuillaumeGomez** [comment]
Such a shame! :smiling_imp:

**Pull request closed without merging**
