### PR TITLE
fix capitalization inside sentense

### PR DESCRIPTION
**Pull request by rutsky**
r? @steveklabnik

### CODE REVIEW

**Comment by rutsky** [comment]
Oh, words after colons in English are capitalized in some cases. Didn't knew, sorry! :)

**Comment by steveklabnik** [comment]
Is that true? I actually would have thought this patch was correct.

**Comment by rutsky** [comment]
@steveklabnik I found that in some cases words after colons may be capitalized, e.g. one of discussions: https://english.stackexchange.com/questions/6931/capitalization-after-colon

If you think more correct way would be not capitalize (looks like it's more style/culture related, then forced by rules), please reopen this PR.

Also, I've found at least one more example of capitalized word after colon in the Rust documentation.

**Comment by steveklabnik** [comment]
> Also, I've found at least one more example of capitalized word after colon in the Rust documentation.

Please send me another PR to fix it :) Thanks so much for all of these fixes.

**Pull request merged**
