### PR TITLE
split rustc::metadata to a rustc_metadata crate

### PR DESCRIPTION
**Pull request by arielb1**
This improves bootstrap times because of better parallelism - though I need to measure how much - and allows metadata to be modified without triggering a full recompile. This also ensures that metadata handling and the rest of rustc remain decoupled, which is a first step for switching to a new metadata format.

This is a [breaking-change] to all plugin authors because of the following renames:
- `rustc::plugin` is now `rustc_plugin`
- `rustc::metadata` is now `rustc_metadata`
- Most data types from `rustc::metadata`, along with `LOCAL_CRATE`, are now in `rustc::middle::cstore`.
- The CStore methods were split between the `rustc::middle::CrateStore` trait (and trait object) and the `rustc_metadata::cstore::CStore`, with an `Rc<CrateStore>` stored in the `Session`. The inner `CStore` can be accessed via the inner `Any` bound, but this is deprecated.

r? @nikomatsakis

### CODE REVIEW

**Comment by alexcrichton** [comment]
:last_quarter_moon_with_face:

**Comment by nikomatsakis** [comment]
Yeah, I like this approach here.

**Comment by nikomatsakis** [comment]
this looks good. r=me on the commits so far if we add some kind of comment explaining that `Any` is a temporary hack to avoid regressing plugins that we plan to remove eventually.

**Comment by huonw** [comment]
Needs a rebase.

**Pull request merged**
