### PR TITLE
Make the slice iterator optimise better.

### PR DESCRIPTION
**Pull request by huonw**
Due to the null pointer optimisation, LLVM was leaving totally useless
null pointer checks in tight loops using this iterator. We compile
`Some(a_reference)` to a no-op, and matching against None in an
`Option<&T>` is just comparing against 0, this means that the `None`
branch in `match Some(a_reference) { None => ... }` (as appears
effectively in a loop using `slice::Iter`) can't be eliminated unless
`a_reference` is known to be non-null.

LLVM currently doesn't seem to understand this in every situation (often
due to inlining, I am told), particularly painfully in ones involving
this iterator, but using `assume` means it understands almost always.

```
for i in x {
    test::black_box(i);
}
```

Before:

```
.LBB0_4:
    leaq    4(%rcx), %rsi
    testq   %rcx, %rcx
    je  .LBB0_5
    movq    %rcx, (%rsp)
    #APP
    #NO_APP
    cmpq    %rsi, %rax
    movq    %rsi, %rcx
    jne .LBB0_4
```

After:

```
.LBB0_4:
    movq    %rcx, (%rsp)
    addq    $4, %rcx
    #APP
    #NO_APP
    cmpq    %rcx, %rax
    jne .LBB0_4
```

This leads to significantly better unrolling and vectorisation too.

### CODE REVIEW

**Comment by Gankro** [comment]
r+ a62c rollup

**Comment by huonw** [comment]
@bors r-

Hm, this appears to be aborting in the bootstrap. Debugging now.

**Comment by alexcrichton** [comment]
We may want to hold off on `llvm.assume` for now, it looks like it's causing a serious hit to compile times: https://github.com/rust-lang/rust/pull/21418#issuecomment-70925491

**Comment by huonw** [comment]
Woah, I noticed my builds were taking a while but I didn't connect that it was caused by `assume`. Sounds like this shouldn't land yet.

**Pull request closed without merging**
