### PR TITLE
Add example in docs for `std::thread::panicking`.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
I'm not mentally attached in any way to the example I wrote, so if anyone has better ideas, I'm very open to changing mine. This was prompted because it wasn't obvious to me what contexts `panicking` would be used, but after adding an example with `Drop`, I hope it clears up some confusion for others in the future.

**Comment by steveklabnik** [comment]
```

---- thread::panicking_0 stdout ----
	thread 'thread::panicking_0' panicked at 'test executable failed:
a: dropped while not unwinding
b: dropped while unwinding

thread 'main' panicked at 'explicit panic', <anon>:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.
', src/librustdoc/test.rs:312
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    thread::panicking_0

test result: FAILED. 475 passed; 1 failed; 14 ignored; 0 measured
```

This test needs to be marked `should_panic`.

/cc @rust-lang/libs is this a good example? Seems okay to me, but I have never used this method.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by frewsxcv** [comment]
> This test needs to be marked should_panic.

Done.

**Pull request merged**
