### PR TITLE
debuginfo: Build scope map for consts

### LINKED ISSUE #22432: Internal compiler error at compiling openssl-sys-0.4.0
```
$ RUST_BACKTRACE=1 cargo build --verbose
       Fresh gcc v0.2.1
       Fresh pkg-config v0.2.1
   Compiling openssl-sys v0.4.0 (file:///tmp/rust-openssl/openssl-sys)
     Running `rustc src/lib.rs --crate-name openssl-sys --crate-type lib -g -C metadata=dd0e973e71d408a3 -C extra-filename=-dd0e973e71d408a3 --out-dir /tmp/rust-openssl/openssl-sys/target --emit=dep-info,link -L dependency=/tmp/rust-openssl/openssl-sys/target -L dependency=/tmp/rust-openssl/openssl-sys/target/deps -L native=/usr/lib64 -L native=/tmp/rust-openssl/openssl-sys/target/build/openssl-sys-dd0e973e71d408a3/out -l ssl -l crypto -l static=old_openssl_shim`
src/lib.rs:1:1: 1:1 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 5326, node: ExprStruct(Path { span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: StaticMutex#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }, [Field { ident: Spanned { node: lock#0, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 5327, node: ExprPath(Path { span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: sys#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: MUTEX_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, Field { ident: Spanned { node: poison#0, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 5328, node: ExprPath(Path { span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: poison#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: FLAG_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }], None), span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } })
src/lib.rs:1 #![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
             ^
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /mnt/trash1/tmp/portage/dev-lang/rust-9999/work/rust-9999/src/libsyntax/diagnostic.rs:129

stack backtrace:
   1:     0x7fa97995e8e0 - sys::backtrace::write::he6b1641fd079577cfmB
   2:     0x7fa979984760 - <unknown>
   3:     0x7fa9798d60f0 - rt::unwind::begin_unwind_inner::h634afd378febd66detK
   4:     0x7fa976e432b0 - <unknown>
   5:     0x7fa976e43240 - diagnostic::SpanHandler::span_bug::h189abf680a7a28f874E
   6:     0x7fa97793d500 - session::Session::span_bug::h720ba33852c899b7rSs
   7:     0x7fa9787a8a10 - <unknown>
   8:     0x7fa9786d9700 - <unknown>
   9:     0x7fa978698f50 - <unknown>
  10:     0x7fa978698f50 - <unknown>
  11:     0x7fa9786999b0 - <unknown>
  12:     0x7fa978756fc0 - <unknown>
  13:     0x7fa97870d900 - <unknown>
  14:     0x7fa97873aef0 - <unknown>
  15:     0x7fa9786d9d30 - <unknown>
  16:     0x7fa97869a200 - <unknown>
  17:     0x7fa9786cea00 - <unknown>
  18:     0x7fa9786d50f0 - <unknown>
  19:     0x7fa9786dbb30 - <unknown>
  20:     0x7fa9786db080 - <unknown>
  21:     0x7fa97869a200 - <unknown>
  22:     0x7fa9786cea00 - <unknown>
  23:     0x7fa9786d50f0 - <unknown>
  24:     0x7fa9786dbb30 - <unknown>
  25:     0x7fa9786db080 - <unknown>
  26:     0x7fa97869a200 - <unknown>
  27:     0x7fa9786cea00 - <unknown>
  28:     0x7fa9786d3a90 - <unknown>
  29:     0x7fa9786dbb30 - <unknown>
  30:     0x7fa978698f50 - <unknown>
  31:     0x7fa978787d40 - <unknown>
  32:     0x7fa978698830 - <unknown>
  33:     0x7fa9786999b0 - <unknown>
  34:     0x7fa9786dbb30 - <unknown>
  35:     0x7fa978698f50 - <unknown>
  36:     0x7fa9786999b0 - <unknown>
  37:     0x7fa978756fc0 - <unknown>
  38:     0x7fa97870d900 - <unknown>
  39:     0x7fa9786dbb30 - <unknown>
  40:     0x7fa9786db080 - <unknown>
  41:     0x7fa97869a200 - <unknown>
  42:     0x7fa9786cea00 - <unknown>
  43:     0x7fa9786d50f0 - <unknown>
  44:     0x7fa9786dbb30 - <unknown>
  45:     0x7fa978698f50 - <unknown>
  46:     0x7fa9786999b0 - <unknown>
  47:     0x7fa9786dbb30 - <unknown>
  48:     0x7fa978698f50 - <unknown>
  49:     0x7fa9786999b0 - <unknown>
  50:     0x7fa978756fc0 - <unknown>
  51:     0x7fa9786887a0 - <unknown>
  52:     0x7fa978684210 - <unknown>
  53:     0x7fa97875dd80 - trans::base::trans_crate::ha8556e563b91ec61fQv
  54:     0x7fa979f5f250 - driver::phase_4_translate_to_llvm::hc334bfd7f2b08e6d2Oa
  55:     0x7fa979f384b0 - driver::compile_input::h6a09d1f5442479b9Eba
  56:     0x7fa97a007770 - run_compiler::h940da8caa9037102Bbc
  57:     0x7fa97a005d00 - <unknown>
  58:     0x7fa97a004be0 - <unknown>
  59:     0x7fa9799e1770 - <unknown>
  60:     0x7fa9799e1760 - rust_try
  61:     0x7fa97a004e90 - <unknown>
  62:     0x7fa979971e00 - <unknown>
  63:     0x7fa974614f70 - <unknown>
  64:     0x7fa97955d389 - clone
  65:                0x0 - <unknown>

Could not compile `openssl-sys`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name openssl-sys --crate-type lib -g -C metadata=dd0e973e71d408a3 -C extra-filename=-dd0e973e71d408a3 --out-dir /tmp/rust-openssl/openssl-sys/target --emit=dep-info,link -L dependency=/tmp/rust-openssl/openssl-sys/target -L dependency=/tmp/rust-openssl/openssl-sys/target/deps -L native=/usr/lib64 -L native=/tmp/rust-openssl/openssl-sys/target/build/openssl-sys-dd0e973e71d408a3/out -l ssl -l crypto -l static=old_openssl_shim` (status=101)
```
Rust version:
```
rustc 1.0.0-dev (81bce5290 2015-02-16) (built 2015-02-17)
binary: rustc
commit-hash: 81bce5290ff55b9a2eddd83d31b0778180904d7f
commit-date: 2015-02-16
build-date: 2015-02-17
host: x86_64-unknown-linux-gnu
release: 1.0.0-dev
```
OS: Gentoo Linux AMD64

### PR DESCRIPTION
**Pull request by klutzy**
Fixes #22432.

### CODE REVIEW

**Comment by klutzy** [comment]
cc @michaelwoerister

**Comment by klutzy** [comment]
This is fixup of #21744: it optimized `rustc_trans::trans::expr::trans_into` s.t. if expr is ExprPath referring const, get const expr and directly call `trans_into`. But debuginfo was not updated so it ignored const-ExprPath while building scope_map.

**Comment by eddyb** [comment]
My bad - but this needs a test, otherwise it could regress again.

**Comment by michaelwoerister** [comment]
Thanks for the PR. Unfortunately this solution will lead to wrong debug locations if the same constant is referred to more than once within the same function. The scope map uses node IDs as keys and for a constant expression these are always the same, regardless of where it gets expanded to. So later occurences will overwrite scope map entries of former ones.

I already have an idea how to solve this problem differently.

**Comment by michaelwoerister** [comment]
OK, so my idea is to provide `debuginfo::with_debug_loc_override()` function that allows to fixate emitted debug locations to a given value for a limited scope. This can then be used in `expr::trans_into()`, where it allows to set all emitted debug locations to the location of the constant's occurrence. To me this seems like a reasonably clean solution.

@klutzy Let me know if you have a better idea or want to implement my suggestion. Otherwise I'll implement it.

**Comment by michaelwoerister** [comment]
@klutzy Since I haven't heard from you, I implemented my suggested solution (PR #23074).

**Comment by klutzy** [comment]
@michaelwoerister I haven't have sufficient time to investigate this further, sorry. Thanks for making #23074!

**Pull request closed without merging**
