### PR TITLE
bump stdarch

### PR DESCRIPTION
**Pull request by RalfJung**
This lets us remove a hack from https://github.com/rust-lang/rust/pull/131349.

r? @Amanieu 

try-job: test-various

### CODE REVIEW

**Comment by RalfJung** [comment]
Damn, looks like we have to land https://github.com/rust-lang/rust/pull/131349 first...

Cc @compiler-errors

**Comment by RalfJung** [comment]
Testing whether https://github.com/rust-lang/stdarch/pull/1660 suffices to fix this.
@bors try

**Comment by compiler-errors** [comment]
Merge this into that PR, perhaps? Or does it need to happen before?

**Comment by RalfJung** [comment]
Having a stdarch update together with another big change does not sound great.

**Comment by RalfJung** [comment]
Yeah https://github.com/rust-lang/stdarch/pull/1660 seems to help. But https://github.com/rust-lang/rust/pull/131349 is on its way now so we can alternatively also just wait a bit.

**Comment by RalfJung** [comment]
@Amanieu I updated to latest stdarch master, this should be good to go again.

**Comment by RalfJung** [comment]
Some more `rustc_const_stable` that are not actually stable in in cfg'd parts of std.

@bors r=Amanieu rollup=iffy

**Comment by Kobzol** [comment]
One tiny regression from bumping a dependency, no need to do anything, I think.

@rustbot label: +perf-regression-triaged

**Pull request merged**
