### PR TITLE
[WIP] Move compiletest out of tree

### PR DESCRIPTION
**Pull request by djrenren**
This commit attempts to move `compiletest` to an external dependency. This was recommended as a first step to externalizing `libtest` itself. 

Currently everything is in personal git repos until we can get it all aligned and working.

The goal is to depend on an out-of-tree `compiletest` crate that depends on an externalized `libtest`. I'm currently hosting these under [djrenren/compiletest](https://github.com/djrenren/compiletest) and [djrenren/libtest](https://github.com/djrenren/libtest), but these will need to be migrated to official locations once everything is up and running.

It appears to be mostly working with a few spurious test failures on my machine that seem unrelated. I've created the PR so we can run bors and such.

Steps before merging

- [ ] Pass all appropriate tests
- [ ] Move `libtest` and `compiletest` into official locations
- [ ] Depend on them rather than git URLs.

### CODE REVIEW

**Comment by Centril** [comment]
At minimum, I think if we move compiletest out of tree then it
- needs to be under control of the compiler team, 
- must accomodate breaking changes whenever rust-lang/rust needs it
   - and I think crates on crates.io would not like that.

See https://rust-lang.github.io/compiler-team/procedures/crates/ for the compiler team's policy re. out of tree crates.

**Comment by gnzlbg** [comment]
> I'm also not entirely sure that there are enough wins from moving it out of tree: if the goal here is to decouple it from in-tree libtest, that's great, but should be orthogonal to moving it out of tree?

FWIW the goal here is to share the exact same compiletest version between rust-lang/rust, and other rust-lang projects like clippy. 

An alternative would be to leave the source code in this repo, publish it to crates.io, and have clippy and rust bootstrap pull it from crates.io.

**Comment by gnzlbg** [comment]
> That's ... a bit of an odd goal IMO? It's my opinion that there certainly exists space for something simpler than compiletest in the ecosystem (perhaps just targeting UI tests) but our version of compiletest is probably pretty clunky and such.

Maybe? What compiler plugins like clippy currently use is the `compiletest-rs` crate, which is a fork of rust-lang/rust compiletest . There might be a better solution to their problem.

---

> So I've taken a brief look at the build failures in the PR which moved libtest out of tree and they seem ... unexpected to me? That is, it looks like unstable surface area changed in that PR which isn't what I'd expect at all. 

Which PR did you look at? IIRC the PR that extracted libtest worked fine and passed all tests. What didn't work was the one tried to update the libtest dependency to a different libtest version and ran into linker issues.

**Comment by gnzlbg** [comment]
> Basically it is my opinion that if we're causing downstream breakage for clippy, we're probably causing it for many libtest-using crates and then the moving out bit is probably doing something not quite right.

_I think_ some crates started to use libtest 0.0.0 from crates.io which also caused them some issues, or issues mixing the libtest from crates.io with the libtest from another rust toolchain. Can't remember.

> It should be possible to change where the source code of libtest is without affecting anyone.

Sure, this can be added by just moving the code as is to a repo, and using a submodule. But the intent was for rust itself to pull in a libtest crate from crates.io. And that interacted badly with how Rust build process treats libtest specially. This changed a lot recently, from a 3 step to a 2 step process, so maybe the linking issues that appeared back then do not appear now.

**Comment by RalfJung** [comment]
Miri is also using compiletest-rs, and the fact that it lacks some features compared to rustc's compiletest is causing pain on a regular basis. On other occasions we'd also like to be able to customize things more, e.g. using a different rustc for aux builds vs the final build (only the final build should use Miri).

Maybe we should switch to trybuild entirely, though I am not sure if that is feasible.

**Comment by Centril** [comment]
Possibly crazy idea: move Miri in-tree?

**Comment by RalfJung** [comment]
That's not really the direction we have been taking with tools lately. And Miri is just the second example listed here, clippy being another.

**Comment by Centril** [comment]
@RalfJung The reason Clippy isn't being moved in tree is that @Manishearth wants to keep it out-of-tree for better  on-boarding through shorter build times. Other than that, I believe the bors queue is equipped to take on Clippy. How is the situation re. on-boarding re. Miri? Would moving Miri in-tree be detrimental to on-boarding efforts?

**Comment by RalfJung** [comment]
> How is the situation re. on-boarding re. Miri? Would moving Miri in-tree be detrimental to on-boarding efforts?

TBH I have no idea. We don't exactly have many contributors.

But speaking just for myself, I am quite happy every time hacking on Miri does *not* involve having to build rustc.

**Comment by gnzlbg** [comment]
> But speaking just for myself, I am quite happy every time hacking on Miri does not involve having to build rustc.

Is there anybody working on a component that's out of tree unhappy with that? 😄

**Pull request closed without merging**
