### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Successful merges:

 - #116446 (Yeet `mir::Const::from_anon_const`)
 - #116750 (Add Seek::seek_relative)
 - #117110 (Suggest field typo through derefs)
 - #117961 (Add `x suggest` entries for testing `mir-opt` and `coverage`)
 - #118020 (Fix links to `From<{OwnedHandle, OwnedFd}> for std::process::Child{Stdin, Stdout, Stderr}` in 1.74 release notes)
 - #118034 (bump few deps to fix unsoundness and drop few dup deps)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=116446,116750,117110,117961,118020,118034)

### CODE REVIEW

**Comment by compiler-errors** [comment]
@TaKO8Ki: Please triage the rollup failure before opening a new one. You should leave a comment on #116446 saying that it was the reason for failure.

**Comment by compiler-errors** [comment]
Please read https://forge.rust-lang.org/release/rollups.html#failed-rollups carefully

**Comment by TaKO8Ki** [comment]
@compiler-errors I have already read that document, and I thought this error was not due to the specific pull request being bad, but rather due to a conflict with other pull requests. But are you saying that's not the case this time?

**Comment by compiler-errors** [comment]
No, it's just due to #116446.

**Comment by TaKO8Ki** [comment]
@compiler-errors I understand. I've commented a link to the error message.

**Pull request closed without merging**
