### PR TITLE
Move `slice::check_range` to `RangeBounds`

### PR DESCRIPTION
**Pull request by dylni**
Since this method doesn't take a slice anymore (#76662), it makes more sense to define it on `RangeBounds`.

Questions:
- Should the new method be `assert_len` or `assert_length`?

### CODE REVIEW

**Review by pickfire — COMMENTED** [review]
Naming `for_length` looks non-intuitive but the movement looks good.

**Comment by dylni** [comment]
I don't like the name either. What do you think of `check_for_length`?

**Comment by pickfire** [comment]
> I don't like the name either. What do you think of check_for_length?

Since this is doing bound checking, how about naming it `check_bounds` which is exactly what is does? I wonder if there are other better names.

**Comment by dylni** [comment]
> Since this is doing bound checking, how about naming it check_bounds or check_len or assert_len (this may be weirder) which is exactly what is does? I wonder if there are other better names.

`assert_len` is a really great suggestion. I'll use that name.

**Comment by dylni** [comment]
@rust-highfive missed this PR, so randomly assigning to a libs member.

r? @joshtriplett

**Comment by joshtriplett** [comment]
@dylni I'm not a libs member.

**Comment by dylni** [comment]
Sorry @joshtriplett. I was looking at [this file](https://github.com/rust-lang/highfive/blob/bd777e250e624861873723b672c4f47dfa74b0a1/highfive/configs/rust-lang/rust.json#L7).

r? @KodrAus who reviewed the initial PR.

**Comment by joshtriplett** [comment]
@dylni Interesting, thanks for pointing me at that. :)

**Comment by dylni** [comment]
Not a problem. :) It's good to know I'm looking in the right place

**Comment by KodrAus** [comment]
> Since this method doesn't take a slice anymore (#76662)

Ah yikes! I'm going to have to spend some time digging into that regression properly.

This extra refactoring looks good to me though.

@bors r+

**Comment by dylni** [comment]
@KodrAus Thanks!

> Ah yikes! I'm going to have to spend some time digging into that regression properly.

I was surprised too. Ralf explains it well [here](https://github.com/rust-lang/rust/pull/75207#discussion_r487528528).

**Comment by dylni** [comment]
The failure still doesn't look related to this PR.

**Comment by dylni** [comment]
@joshtriplett Can you retry bors again?

**Comment by jyn514** [comment]
> GitHub Actions has encountered an internal error when running your job.

@bors retry

**Pull request merged**
