### PR TITLE
Haiku: fix initial platform support

### PR DESCRIPTION
**Pull request by jessicah**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Thanks for the PR! We’ll periodically check in on it to make sure that @pnkfelix or someone else from the team reviews it soon.

**Comment by jessicah** [comment]
Just found a few more changes I need to make, so not yet ready for merging.

**Comment by alexcrichton** [comment]
@jessicah this looks good to me, is it ready to merge?

**Comment by jessicah** [comment]
@alexcrichton yes, it's ready to merge :)

**Comment by jessicah** [comment]
Will it merge with the checks failed? I had pushed three commits, then undid the last one, so the second commit never got checked.

**Comment by alexcrichton** [comment]
Yeah that's ok, @bors will re-check against the latest master once this reaches the head of the queue: https://buildbot2.rust-lang.org/homu/queue/rust

**Pull request merged**
