### PR TITLE
Do not consider `&mut *x` as mutating `x` in `CopyProp`

### PR DESCRIPTION
**Pull request by cjgillot**
This PR removes an unfortunate overly cautious case from the current implementation.

Found by https://github.com/rust-lang/rust/pull/105274 cc @saethlin

### CODE REVIEW

**Comment by saethlin** [comment]
Nobody got assigned automatically :thinking: should someone be?

**Comment by saethlin** [comment]
FYI this perf run does not include https://github.com/rust-lang/rust/pull/105274 which _might_ be relevant.

**Comment by cjgillot** [comment]
Now that https://github.com/rust-lang/rust/pull/105274 is merged.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
r? compiler

**Comment by saethlin** [comment]
Does `&raw mut *x` deserve the same treatment?

**Comment by cjgillot** [comment]
This patch handles both cases by considering that a mutation of '*x' is not a mutation of 'x'.

**Comment by saethlin** [comment]
Ahhhhhhh that makes sense :+1:

**Review by JakobDegen — APPROVED** [review]

**Comment by eholk** [comment]
@RalfJung - Does this change have any stacked borrows implications?

@bors r? @JakobDegen

**Comment by eholk** [comment]
I took a quick look over the PR, and it seems reasonable to me, but I'd rather someone who knows this code better sign off.

@bors r? @wesleywiser

**Comment by RalfJung** [comment]
> Does this change have any stacked borrows implications?

That's hard to say without reverse engineering CopyProp. @cjgillot could you describe with some examples which new transformations this entails?

Stacked Borrows currently *does* consider `&mut *x` to be a write to `x`. Tree Borrows does not. But this is a pretty fundamental trade-off; Tree Borrows loses some optimizations due to this choice. However it's hard for me to say whether that is even relevant for CopyProp.

**Comment by JakobDegen** [comment]
Yeah, I feel pretty strongly that we need to allow this opt. The scenario in which it risks being wrong is if the `_2 = _1` actually modifies the value - that can be the result of implicit retags, but we should just not do those.

**Comment by cjgillot** [comment]
The regression in opt builds comes from LLVM doing more work, which is expected.

The regression for `serde_derive check` is a change in how `btree`'s `search_tree` over region constraints is codegened, and in the stable hasher.

**Comment by RalfJung** [comment]
> Yeah, I feel pretty strongly that we need to allow this opt. The scenario in which it risks being wrong is if the `_2 = _1` actually modifies the value - that can be the result of implicit retags, but we should just not do those.

Implicit retags *on assignments* specifically. I agree we shouldn't have those.

Retags on `Rvalue::Ref` are a different matter IMO.

**Pull request merged**
