### PR TITLE
Document implementing `try_fold` for iterators for internal iteration

### PR DESCRIPTION
**Pull request by czipperz**

### CODE REVIEW

**Comment by timvermeulen** [comment]
>which call `next` internally.  Each of these methods delegates to the `try_fold` implementation.

This seems a bit contradictory, maybe it's better to be more explicit about them delegating to `try_fold` which in turn has a default implementation that calls `next` repeatedly.

**Comment by scottmcm** [comment]
This seems like a good change, but overriding `try_fold` is still unstable, so I don't know whether the convention is to mention things that can't be used on stable in the documentation of stable things.

**Comment by czipperz** [comment]
@scottmcm Where is the unstable attribute?

**Comment by scottmcm** [comment]
@czipperz on the `Try` trait, which you have to mention in the signature.

**Comment by czipperz** [comment]
Mmh.

**Comment by czipperz** [comment]
I'm going to close this and post a comment on the tracking issues to reopen once it stabilizes.

**Pull request closed without merging**
