### PR TITLE
Update `ParamEnv` docs

### PR DESCRIPTION
**Pull request by BoxyUwU**
There is now a wealth of information in the dev guide about `ParamEnv` so we should explicitly link to it from the doc comments. I also added a caution against using `ParamEnv` and removed the comment about it being "suitable for type checking" as you should practically never use `ParamEnv::empty` for type checking

r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
thank u

**Comment by compiler-errors** [comment]
tragic, my day is ruined

@bors r-

r=me when fixed :3

**Comment by workingjubilee** [comment]
Yes, that should be correct.

**Pull request merged**
