### PR TITLE
Make print_crate_info public

### PR DESCRIPTION
**Pull request by MaikKlein**
I would like this method to be public. I need this in my custom compiler to make it work with cargo.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Sure... I guess why not. As long as you are aware that we still make no stability guarantees and may change it at will etc =)

@bors r+

**Comment by nikomatsakis** [comment]
PS, @MaikKlein, what "custom compiler" is this?

**Comment by nikomatsakis** [comment]
Also, cc @rust-lang/compiler -- am I being too cavalier in expanding our public API here? (Seems plausible.)

**Comment by MaikKlein** [comment]
@nikomatsakis  It is a for a mir -> spirv compiler. IIRC this function allows cargo to discover the rlib extension.

**Comment by eddyb** [comment]
I'd expect custom drivers to reuse `rustc_driver` - I guess that's not entirely possible here?

**Comment by MaikKlein** [comment]
@eddyb Oh hm. I think I can now access everything inside `print_crate_info`, IIRC that wasn't the case in the past. 

I haven't look to closely at `print_crate_info`, it seems specific to rustc and I probably should implement my own version of `print_crate_info` anyway.

Sorry I should have investigated a bit more before I pushed the PR.

**Comment by eddyb** [comment]
> I haven't look to closely at `print_crate_info`, it seems specific to rustc and I probably should implement my own version of `print_crate_info` anyway.

I doubt that, a backend generally should be orthogonal from the frontend.

**Comment by nikomatsakis** [comment]
Sooooo.....can I close this PR? Going to assume yes, correct me and re-open otherwise. =)

**Pull request closed without merging**
