### PR TITLE
Add tests for #26114

### PR DESCRIPTION
**Pull request by devonhollowood**
First step in fixing #26114

### CODE REVIEW

**Comment by devonhollowood** [comment]
Not sure why this keeps timing out. Should I try submitting this again as a fresh pull request?

**Comment by alexcrichton** [comment]
I think these are all from the `@bors: try` annotations, not from the actual tests themselves. This hasn't actually yet been approved.

**Comment by devonhollowood** [comment]
@alexcrichton I meant that I'm not sure why the `bors` tries keep timing out. Is there some issue with `bors` right now?

**Comment by Aatch** [comment]
I probably should have gotten to this earlier. Looks fine to me.

**Comment by Aatch** [comment]
I'm going to assume that it's the try bots being weird, since they don't get used much.

**Comment by devonhollowood** [comment]
It looks like this never re-entered the merge queue after @Aatch reviewed it. It still only has the [failed try run](http://buildbot.rust-lang.org/homu/queue/rust) on there.

**Comment by Manishearth** [comment]
Probably needed that retry there. back in the queue.

**Comment by devonhollowood** [comment]
@Manishearth thanks!

**Pull request merged**
