### PR TITLE
Return an indexmap in `all_local_trait_impls` query

### PR DESCRIPTION
**Pull request by pierwill**
The data structure previously used here required that `DefId` be `Ord`. As part of #90317, we do not want `DefId` to implement `Ord`.

### CODE REVIEW

**Comment by pierwill** [comment]
I tried this with `FxHashMap` and it caused `ui` test failures.

**Comment by michaelwoerister** [comment]
IndexMap is fine as long as it is constructed in a deterministic way. Do we know if that is the case here?

**Comment by pierwill** [comment]
> IndexMap is fine as long as it is constructed in a deterministic way. Do we know if that is the case here?

I'm not sure. Is this where the IndexMap ends up being constructed?

https://github.com/rust-lang/rust/blob/f5fe6cd27748d519f8c0751b62bc008595736733/compiler/rustc_middle/src/hir/mod.rs#L109

In that case, looks like the determinism would depend on [`rustc_middle::ty::context::TyCtxt::resolutions()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.resolutions). 🤔 Where is that defined? I'm still learning how the query system works.

**Comment by cjgillot** [comment]
`resolutions` is defined from `tcx.untracked_resolutions`, which is just data taken from the resolver and plugged as start conditions for the query system. Everything in `resolutions` is always checked by the query system (the query is both `eval_always` and `no_hash`), so it would not crash if it were non-deterministic. In this case, `trait_impls` is filled in `rustc_resolve::late`, which walks the AST in-order, so it is actually deterministic.

**Pull request merged**
