### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by workingjubilee**
Successful merges:

 - #129424 (Stabilize `Pin::as_deref_mut()`)
 - #131417 (Fix methods alignment on mobile)
 - #131424 (compiler: Stop reexporting enum-globs from `rustc_target::abi`)
 - #131426 (Fix quotation marks around debug line in `src/ci/run.sh`)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=129424,131417,131424,131426)

### CODE REVIEW

**Comment by workingjubilee** [comment]
hypothetically good to go after https://github.com/rust-lang/rust/pull/131434

so
@bors retry

**Comment by onur-ozkan** [comment]
> hypothetically good to go after #131434
> 
> so @bors retry

Don't we need to rebase this PR before trying again?

**Comment by jieyouxu** [comment]
I think we only need to rebase if there are conflicting choices, but not sure

**Comment by jieyouxu** [comment]
Guess we do then

**Comment by jieyouxu** [comment]
Going to try open a new rollup

**Pull request closed without merging**
