### PR TITLE
treat ref-to-raw cast like a reborrow: do a special kind of retag

### PR DESCRIPTION
**Pull request by RalfJung**
r? @oli-obk 

Cc @nikomatsakis

### CODE REVIEW

**Comment by oli-obk** [comment]
I like how everything is more explicit. So this PR lgtm, but without the corresponding miri-PR it's kind of hard to gauge the effect.

I'm fine with just r+ing this PR, since I'm gonna see the changes to miri later, but we might end up having to cycle back to rustc changes (unlikely though).

**Comment by RalfJung** [comment]
The corresponding miri PR is at https://github.com/solson/miri/pull/571

**Comment by RalfJung** [comment]
Sorry forgot to update the lockfile.

@bors r=oli-obk

**Comment by RalfJung** [comment]
Rebased.

@bors r=oli-obk

**Pull request merged**
