### PR TITLE
rustdoc: Get rid of `clean::TypeKind`

### PR DESCRIPTION
**Pull request by jyn514**
It does exactly the same thing as ItemType.

### CODE REVIEW

**Review by CraftSpider — APPROVED** [review]
Only question is, what's the reasoning for keeping ItemType over TypeKind? I'm guessing because TypeKind looks like it was only used as a brief stand-in for ItemType anyways. Otherwise looks good, will approve assuming tests pass.

**Comment by jyn514** [comment]
@CraftSpider `ItemType` has a custom Serialization impl that needs to match the JSON frontend: https://github.com/rust-lang/rust/blob/7f4afdf0255600306bf67432da722c7b5d2cbf82/src/librustdoc/formats/item_type.rs#L57

**Comment by JohnTitor** [comment]
@bors r-
This PR now has a merge conflict.

**Pull request merged**
