### PR TITLE
Remove storage markers if they won't be used during code generation

### PR DESCRIPTION
**Pull request by tmiasko**
The storage markers constitute a substantial portion of all MIR
statements. At the same time, for builds without any optimizations,
the storage markers have no further use during and after MIR
optimization phase.

If storage markers are not necessary for code generation, remove them.

### CODE REVIEW

**Comment by tmiasko** [comment]
Thanks for perf-run. At this point it is mostly an experiment.

r? @ghost

**Comment by tmiasko** [comment]
An improvement for full and incremental builds of larger benchmarks. A minor regression for very small benchmarks.

* full: style-servo-debug -1.2%, cranelift-codegen-debug -1.0%, cargo-debug -0.4%.
* incr-unchanged: style-servo-debug -1.4%, cranelift-codegen-debug -2.5%, cargo-debug: -1.5%
* a big regression in incr-patched for clap-rs-debug +33.9% as a result of an additional codegen unit (size estimates used for partitioning are based on the total number of statements, which are changed by this PR).

**Comment by tmiasko** [comment]
This a simple transformation removing storage markers at opt-level=0 where they won't have any further use. The [CTFE having its own dedicated MIR](#78407) will be unaffected.

r? @wesleywiser

**Comment by estebank** [comment]
Should do a perf run for the new code then?

**Comment by tmiasko** [comment]
A new perf run would be nice to have. Thanks.

**Comment by wesleywiser** [comment]
Nice improvement!

@bors r+

**Comment by tmiasko** [comment]
The enabled transformations now depend on opt-level, so I modified compiletest to use opt-level=1 for mir-opt tests by default. As a result mir-opt test suite will have test coverage for opt-level=0 only insofar it is used manually in compile flags. For other test suites like ui, we will test both variants, as long as they run on CI.

**Comment by wesleywiser** [comment]
cc @rust-lang/wg-mir-opt [mir-opt tests now run at `-Copt-level=1` by default](https://github.com/rust-lang/rust/pull/78360#issuecomment-759753306).

**Review by wesleywiser — APPROVED** [review]

**Comment by tmiasko** [comment]
Rebased and added `-O` flag to a `try_identity` codegen test that requires storage markers so that MIR optimization applies.

**Comment by RalfJung** [comment]
Storage markers are also used by Miri, and this caused some really strange test failures where we fail to detect some UB with optimizations enabled. I am not sure what is going on...

FWIW, would be good to ping @rust-lang/miri for MIR optimization changes that could affect UB detection. This is the second time in a week that I had to dig through rustc PR history to figure out why a test suddenly fails.^^

**Pull request merged**
