### PR TITLE
enforce unused-must-use lint in macros

### LINKED ISSUE #55516: `write!` is somehow masking the `#[must_use]` on its result
Hat tip to @shepmaster for finding this

[play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=267a47eba842626f4cce618ad89caa47)

```rust
fn main() {
    use std::fmt::Write;
    let mut example = String::new();
    write!(&mut example, "{}", 42);
}
```

is not triggering the `#[must_use]` lint on `Result`.

### PR DESCRIPTION
**Pull request by durka**
Fixes #55516 by turning on the UNUSED_MUST_USE lint within macros.

### CODE REVIEW

**Comment by petrochenkov** [comment]
I'm going to beta-nominate this to minimize the window in which `write!(...);` can be used without a warning. It's quite common and may cause too many warnings if the fix is applied too late.

**Comment by nagisa** [comment]
Discussed backport during the T-compiler meeting. Accepted for backport.

**Comment by nikomatsakis** [comment]
r=me but any idea why travis is upset? Is that spurious?

**Comment by alexcrichton** [comment]
r=me, but it looks like CI may be failing? It appears an unused result already snuck in!

**Comment by durka** [comment]
Actually relevant [part of the log](https://travis-ci.org/rust-lang/rust/jobs/449173937#L1531) (cc @TimNN):

```
[00:36:38]    Compiling rustc_resolve v0.0.0 (/checkout/src/librustc_resolve)
[00:36:43] error: unused `std::result::Result` that must be used
[00:36:43]    --> librustc_resolve/resolve_imports.rs:785:17
[00:36:43]     |
[00:36:43] 785 |                 write!(suggestion_choices, "`::{}`", name);
[00:36:43]     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:36:43]     |
[00:36:43]     = note: `-D unused-must-use` implied by `-D warnings`
[00:36:43]     = note: this `Result` may be an `Err` variant, which should be handled
[00:36:43]     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
[00:36:43]
[00:36:43] error: unused `std::result::Result` that must be used
[00:36:43]    --> librustc_resolve/resolve_imports.rs:793:17
[00:36:43]     |
[00:36:43] 793 |                 write!(suggestion_choices, "`self::{}`", name);
[00:36:43]     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:36:43]     |
[00:36:43]     = note: this `Result` may be an `Err` variant, which should be handled
[00:36:43]     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
[00:36:43]
[00:36:43] error: aborting due to 2 previous errors
[00:36:43]
[00:36:43] error: Could not compile `rustc_resolve`.
```

**Comment by durka** [comment]
Added in #54201 cc @eddyb. It's writing into `suggestion_choices` which is... a `String`. So we should probably just `unwrap` these? Is that allowed in the compiler?

**Comment by alexcrichton** [comment]
Looks like some tests may still be failing?

**Comment by durka** [comment]
I blessed all the UI tests but I guess there's more fallout... will fix
tonight.

**Comment by eddyb** [comment]
>  It's writing into `suggestion_choices` which is... a `String`. So we should probably just `unwrap` these? Is that allowed in the compiler?

Yeah, `write!(string, ...)` can use `unwrap`. I wish error type could be `!` in that case, oh well.

**Pull request merged**
