### PR TITLE
Adds new intrinsic declaration

### PR DESCRIPTION
**Pull request by aaishwarymishra**
This pr is for #132735 removes removes `extern "intrinsic"`

I think its the last block of this file and was kind of asking for advice how to handle other files as mentioned in the issue .

### CODE REVIEW

**Comment by saethlin** [comment]
> I think its the last block of this file and was kind of asking for advice how to handle other files as mentioned in the issue .

Are you asking about the changes to the compiler?

**Comment by BLANKatGITHUB** [comment]
> > I think its the last block of this file and was kind of asking for advice how to handle other files as mentioned in the issue .
> 
> Are you asking about the changes to the compiler?

yes

**Comment by saethlin** [comment]
For this PR, squash the commits together and then it's good.

I'll post some guidance on the issue about what to do (in a few hours).

**Comment by BLANKatGITHUB** [comment]
> For this PR, squash the commits together and then it's good.
> 
> I'll post some guidance on the issue about what to do (in a few hours).

thanks

**Comment by RalfJung** [comment]
There's still a ton of testcases that need to be ported. Might be worth porting at least most of them in a first step?

**Comment by BLANKatGITHUB** [comment]
@RalfJung well can I port 
`./library/core/src/ffi/va_list.rs
./library/core/src/intrinsics/simd.rs` as they also have `extern "rust-intrinsic"` and are last 2 files of library with the declaration before porting tests?

**Comment by BLANKatGITHUB** [comment]
Ok so like should I port those va_list or leave them for now?

**Comment by RalfJung** [comment]
Please do port them.

**Pull request merged**
