### PR TITLE
Stabilize Option::xor

### LINKED ISSUE #50512: Tracking issue for Option::xor
Today I got myself in a situation in which I had two `Option<T>` values, and I wanted to return the only one that was `Some`. If both of them were `Some`, then I'd rather return `None`. I think it would be perfect to have a `xor` method, very similar to the `or` method:

```Rust
impl<T> Option<T> {

    //...

    fn xor(self, optb: Option<T>) -> Option<T> {
        match (&self, &optb) {
            (&Some(_), &None) => self,
            (&None, &Some(_)) => optb,
            _ => None,
        }
    }
}
```

I think that would solve my problem nicely, and could be useful for a lot of people as well.

### PR DESCRIPTION
**Pull request by tesuji**
FCP done in https://github.com/rust-lang/rust/issues/50512#issuecomment-469527554 .

Closes #50512 .

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
FCP completed but @Amanieu and @withoutboats expressed doubts so I'm going to r? @Amanieu for final approval.

**Comment by lzutao** [comment]
Are there any updates on libs team?

**Comment by lzutao** [comment]
Hi, is there any update yet?

**Comment by Centril** [comment]
Would love to see this stabilized. I do think it brings clarity and ergonomics to the "I have several incompatible options, select one of them but only if that's the only one given"-usecase. I've hit that before when working on proc macro implementations.

**Comment by taiki-e** [comment]
@Centril
> I do think it brings clarity and ergonomics to the "I have several incompatible options, select one of them but only if that's the only one given"-usecase.

If I understand correctly, `Option::xor` can only be used if there are two options in this use-case.

**Comment by Centril** [comment]
> If I understand correctly, `Option::xor` can only be used if there are two options in this use-case.

@taiki-e Yeah that's true; In my cases I only had two options.

**Comment by lzutao** [comment]
@Amanieu Does the lib team have any updates?

**Comment by lzutao** [comment]
Spamming ping @Amanieu .

**Comment by SimonSapin** [comment]
Per FCP:

@bors r+

**Pull request merged**
