### PR TITLE
doc: format! may or may not handle streams in future

### PR DESCRIPTION
**Pull request by tshepang**
No need to talk about that here

### CODE REVIEW

**Comment by maximih** [comment]
I think you removed a bit too much text as it's important info that `format!` returns a String.

**Comment by brson** [comment]
If you are removing references to streams please remove the one from the first para too: "This macro is implemented in the compiler to emit calls to this module in order to format arguments at runtime into strings and streams."

@maximih that first paragraph also mentions that format returns strings so maybe is sufficient. @tshepang maybe this sentence can be changed to be more clear about creating `String`.

If we're removing irrelevant info, the detail that `format!` is implemented in the compiler is hardly the first thing I would call out in the docs.

**Comment by birkenfeld** [comment]
Isn't `write!()/writeln!()` what's used to write to streams? In that case it could just be linked to.

**Comment by tshepang** [comment]
@brson I don't understand this:

>If we're removing irrelevant info, the detail that format! is implemented in the compiler is hardly the first thing I would call out in the docs.

**Comment by brson** [comment]
@tshepang The second sentence of the description of `format!` begins with "This macro is implemented in the compiler". I was just saying that that bit of information is irrelevant to users.

**Pull request merged**
