### PR TITLE
Disable building rust-analyzer on riscv64

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
riscv64 has an LLVM bug that makes rust-analyzer not build. Should permit future rust-analyzer ups (e.g., https://github.com/rust-lang/rust/pull/74813) to land.

### CODE REVIEW

**Review by matklad — COMMENTED** [review]
bors r+

Thanks!

**Comment by matklad** [comment]
The other bors

@bors r+

**Comment by davidlt** [comment]
Is this still the case after so many LLVM releases?

**Comment by cuviper** [comment]
@davidlt if you would like to send a PR to re-enable it, we can try again with current LLVM. Maybe you can test that with a patch on the Fedora riscv infrastructure first?

**Comment by davidlt** [comment]
Thanks for the reminder. I will attempt enabling it in a few days (I will try my best to queue it later today).

**Comment by davidlt** [comment]
@cuviper
http://fedora.riscv.rocks/koji/buildinfo?buildID=222393
http://fedora.riscv.rocks/koji/rpminfo?rpmID=900443

It built. LLVM 15.0.6.

**Pull request merged**
