### PR TITLE
[stable] Prepare Rust 1.69.0

### PR DESCRIPTION
**Pull request by emilyalbini**
Last minute backports:

*  #109643
* #110135
* #109938 
* #109937
* #109266

This PR also bumps the channel to stable, and backports the release notes from master.

r? @ghost
cc @rust-lang/release

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors r+ p=1000 rollup=never

*Nice.*

**Comment by lukas-code** [comment]
https://github.com/rust-lang/rust/pull/109266, while fixing some rustdoc ICEs, also caused some more rustdoc ICEs (https://github.com/rust-lang/rust/issues/109282 https://github.com/rust-lang/rust/issues/109614 https://github.com/rust-lang/rust/issues/109424 https://github.com/rust-lang/rust/issues/109631), which seen quite unfortunate to have on stable. Is there any change we can also include last minute backports of https://github.com/rust-lang/rust/pull/109330 and/or https://github.com/rust-lang/rust/pull/109500, or do a revert of https://github.com/rust-lang/rust/pull/94857 instead?

**Comment by ehuss** [comment]
@bors retry

dist-x86_64-apple-alt Received request to deprovision: The request was cancelled by the remote provider.

**Pull request merged**
