### PR TITLE
Move `std::sys_common::alloc` to new module `std::sys::common`

### PR DESCRIPTION
**Pull request by CDirkx**
https://github.com/rust-lang/rust/blob/6b56603e35b39c9f6cc76782330e5e415f9e43d5/library/std/src/sys_common/mod.rs#L7-L13

It was my impression that the goal for `std::sys` has changed from extracting it into a separate crate to making std work with features. However the fact remains that there is a lot of interdependence between `sys` and `sys_common`, this is because `sys_common` contains two types of code:

- abstractions over the different platform implementations in `std::sys` (for example [`std::sys_common::mutex`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys_common/mutex.rs))
- code shared between platforms (for example [`std::sys_common::alloc`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys_common/alloc.rs))

This PR attempts to address this by adding a new module `common` to `std::sys` which will contain code shared between platforms, `alloc.rs` in this case but more can be moved over in the future.

### CODE REVIEW

**Comment by m-ou-se** [comment]
This looks good to me, but I'm a bit worried about the existence of both `sys::common` and `sys_common` being confusing. Could you add a comment to `sys/common.rs` and `sys_common/mod.rs` explaining the difference?

Thanks!

**Comment by CDirkx** [comment]
I agree on the confusion. Once all the common code is eventually split out of `sys_common` it might make sense to rename it to something like `sys_interface` or something, as at that point it would mostly only be a facade for `sys`. But that is for much later, I'll update the documentation in `sys_common` and add some in `sys::common`.

**Comment by CDirkx** [comment]
I added some documentation and set up #84187 to track the progress of moving over code from `sys_common` to `sys::common` in future PRs.

**Comment by m-ou-se** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
