### PR TITLE
Implementation of RFC 2086 - Allow Irrefutable If-Let patterns

### PR DESCRIPTION
**Pull request by Nokel81**
In the current state this will build when using the default `config.toml`. However, when I do a `test` it fails with `alloc_jemalloc v0.0.0`. I have not touched any part of that so I don't think it should be effected.

I am putting this here to show my progress so far.

### CODE REVIEW

**Comment by leodasvacas** [comment]
Could you update the title or the description to say what RFC 2086 is? Makes it easier for those passing by.

**Comment by alexcrichton** [comment]
cc @nikomatsakis, mind taking a look here or delegating to a different reviewer?

**Comment by arielb1** [comment]
r? @arielb1

Shouldn't you have a feature-gate so this doesn't become insta-stable? See [the new feature guide] for details on how to do it.

[the new feature guide]: https://forge.rust-lang.org/feature-guide.html.

**Comment by Nokel81** [comment]
I thought I did. Will go back and check again later today. Thanks

**Comment by Nokel81** [comment]
There was always a feature gate but I changed the version to the current nightly version

**Comment by arielb1** [comment]
@Nokel81 

But you can do `#[allow(irrefutable_let_pattern)]` without enabling any feature gates (or at least there's no test you can't).

**Comment by kennytm** [comment]
@Nokel81 Hi, could you take a look at the CI failure? 

```
[00:02:56] Expected a gate test for the feature 'irrefutable_let_pattern'.
[00:02:56] tidy error: Found 1 features without a gate test.
[00:02:56] Hint: create a file named 'feature-gate-irrefutable_let_pattern.rs' in the compile-fail
[00:02:56]       test suite, with its failures due to missing usage of
[00:02:56]       #![feature(irrefutable_let_pattern)].
[00:02:56] Hint: If you already have such a test and don't want to rename it,
[00:02:56]       you can also add a // gate-test-irrefutable_let_pattern line to the test file.
[00:02:56] tidy error: The Unstable Book has a 'language feature' section 'allow_irrefutable_lets' which doesn't correspond to an unstable language feature
[00:02:56] some tidy checks failed
```

**Comment by Nokel81** [comment]
I merged in Master to fix the merge conflicts, why is AppVeyor saying that there is still conflicting files?

**Comment by kennytm** [comment]
@Nokel81 Because `master` is updated again? Also, prefer rebase instead of merge to keep the history clean.

```sh
$ git checkout master
$ git pull origin master     # ensure master is really up to date

$ git checkout allow-irrefutable_patterns 
$ git rebase master          # insert your changes on top of the latest master

$ # fix rebase conflict...
$ nano src/librustc_const_eval/check_match.rs
$ git add src/librustc_const_eval/check_match.rs 
$ git rebase --continue
$ # fix rebase conflict...
$ nano src/libsyntax/feature_gate.rs
$ git add src/libsyntax/feature_gate.rs  
$ git rebase --continue
```

**Comment by arielb1** [comment]
This PR history is a bit messy.

Could you please rebase it with no merge commits so we can look at it?

**Comment by Nokel81** [comment]
Yup will get to it tomorrow as I have no time this evening

**Comment by kennytm** [comment]
😱 

screenshot_2018-03-15 09 04 40_a5kkwx

**Comment by Nokel81** [comment]
Ya, in the process of a rebase so that was the merge revert

**Comment by Nokel81** [comment]
Since I am having so much difficulty trying to fix this merge and do a rebase. Would it be better for me to create a new branch with my changes?

**Comment by kennytm** [comment]
@Nokel81 yes, sounds like it is better to just start from scratch 😅

**Pull request closed without merging**
