### PR TITLE
Replace AsRawFd implementations with generic AsInner<FileDesc>

### PR DESCRIPTION
**Pull request by l0kod**
Revamp the `AsRawFd` implementations using generics.

### CODE REVIEW

**Comment by l0kod** [comment]
The same thing could be done for Windows extension as well. I can do it (without testing) if interested.

cc @aturon

**Comment by alexcrichton** [comment]
This unfortunately makes the implementors of `AsRawFd` impossible to find in the documentation itself because the `AsInner` trait does not show up in the documentation, and hence you're unable to find the total list of of all implementors.

**Comment by steveklabnik** [comment]
This doesn't merge cleanly anymore, and will ned a rebase.

**Comment by l0kod** [comment]
> This unfortunately makes the implementors of `AsRawFd` impossible to find in the documentation itself because the `AsInner` trait does not show up in the documentation, and hence you're unable to find the total list of of all implementors.

Do I need to open an other issue for the documentation generation bug?

> This doesn't merge cleanly anymore, and will ned a rebase.

Commit rebased.

**Comment by alexcrichton** [comment]
Oh I'm sorry I actually meant to close this earlier. Unfortunately the documentation issue is not actually a bug but rather is a feature. Private traits like `AsInner` shouldn't be showing up in the documentation.

**Pull request closed without merging**
