### PR TITLE
Fix hygiene regression in patterns

### PR DESCRIPTION
**Pull request by petrochenkov**
Closes https://github.com/rust-lang/rust/issues/29746

### CODE REVIEW

**Comment by petrochenkov** [comment]
Hm, no, this breaks other things.
It looks like the change in https://github.com/rust-lang/rust/commit/40ce80484c636e525ac796a81f38a96c0ca8bf09, causing this regression, at the same time fixed some ICEs, like https://github.com/rust-lang/rust/issues/23891 and https://github.com/rust-lang/rust/issues/27320.
It needs further investigation.

**Comment by petrochenkov** [comment]
Ok, now all tests pass.
It's strange, however, that `mtwt::resolve` is needed during type checking.

**Comment by brson** [comment]
Nominating for backport. Linked issues says this is on beta. cc @rust-lang/compiler

**Comment by petrochenkov** [comment]
It looks like there are couple of very similar issues in rustc_trans and rustc_mir, in places where "first of bindings with the same name" is needed in `match`.
```
match x {
    pat1(a) | pat2(a) | pat3(a) => {}
         ^ the first `a` is here, `a`s have to be compared hygienically
}
```

**Comment by petrochenkov** [comment]
Updated with fixes for mir and trans.
Ideally, resolve should build some special table for these cases and save it for later, so mtwt tables could be cleared immediately after name resolution.

**Comment by nrc** [comment]
r+ with a rebase.

I am really unhappy about keeping the mtwt tables around longer than we have to - this will cause memory use and possibly compile time regressions. But I guess it is better to be slow and correct. I'll file an issue for a better fix.

**Comment by petrochenkov** [comment]
Rebased.

**Comment by nikomatsakis** [comment]
Accepted for beta because this is a regression.

**Comment by brson** [comment]
This doesn't cherry-pick cleanly at all. Can somebody else do it in the next week or so? @petrochenkov perhaps?

**Pull request merged**
