### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by Muscraft**
5 commits in a510712d05c6c98f987af24dd73cdfafee8922e6..499a61ce7a0fc6a72040084862a68b2603e770e8
2024-03-25 03:45:54 +0000 to 2024-03-26 04:17:04 +0000
- fix: do not borrow shell across registry query (rust-lang/cargo#13647)
- Do not strip debuginfo by default for MSVC (rust-lang/cargo#13630)
- chore(deps): update msrv (rust-lang/cargo#13577)
- Fix doc collision for lib/bin with a dash in the inferred name. (rust-lang/cargo#13640)
- refactor: Make lint names snake_case (rust-lang/cargo#13635)

r? ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
@Muscraft This doesn't have all the diffs in the tip-of-tree for cargo since weihanglo's last subtree sync today.

**Comment by workingjubilee** [comment]
Whee.

**Comment by workingjubilee** [comment]
It's not impossible I'm wrong and the generated PR description from the tool you're using simply left out a... kinda important one.

**Comment by RalfJung** [comment]
The PR does seem to contain the change mentioned in the description. But then it also contains more that's somehow not mentioned...

**Comment by workingjubilee** [comment]
We did some noodling on things and found the correct set of updates.

**Comment by weihanglo** [comment]
Thanks people for helping update the submodule!

**Pull request merged**
