### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by jieyouxu**
Successful merges:

 - #126841 ([`macro_metavar_expr_concat`] Add support for literals)
 - #126881 (Make `NEVER_TYPE_FALLBACK_FLOWING_INTO_UNSAFE` a deny-by-default lint in edition 2024)
 - #126921 (Give VaList its own home)
 - #127367 (Run alloc sync tests)
 - #127431 (Use field ident spans directly instead of the full field span in diagnostics on local fields)
 - #127437 (Uplift trait ref is knowable into `rustc_next_trait_solver`)
 - #127439 (Uplift elaboration into `rustc_type_ir`)
 - #127451 (Improve `run-make/output-type-permutations` code and improve `filename_not_in_denylist` API)
 - #127452 (Fix intrinsic const parameter counting with `effects`)
 - #127459 (rustdoc-json: add type/trait alias tests)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=126841,126881,126921,127367,127431,127437,127439,127451,127452,127459)

### CODE REVIEW

**Comment by compiler-errors** [comment]
Perf regression possibly due to the elaboration PR, testing here: https://github.com/rust-lang/rust/pull/127439#issuecomment-2216300499

If that is the root cause, I'd say we eat it, since it's mostly doc builds and likely due to the `AutoTraitFinder` which ought to be rewritten soon.

**Comment by compiler-errors** [comment]
(you might want to kick off some other perf runs to investigate some other PRs -- my advice is to start them in each of their respective prs and cross-link them to here)

**Comment by Kobzol** [comment]
Regression caused by https://github.com/rust-lang/rust/pull/127439. The regressions are mostly in `doc` builds, and this is apparently a necessary refactoring. Marking as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
