### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #121666 (Use the OS thread name by default if `THREAD_INFO` has not been initialized)
 - #121758 (Move thread local implementation to `sys`)
 - #121759 (attempt to further clarify addr_of docs)
 - #121855 (Correctly generate item info of trait items)
 - #121888 (style library/core/src/error.rs)
 - #121892 (The ordinary lowering of `thir::ExprKind::Let` is unreachable)
 - #121895 (avoid collecting into vecs in some places)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=121666,121758,121759,121855,121888,121892,121895)

### CODE REVIEW

**Comment by ChrisDenton** [comment]
`auto - x86_64-gnu-stable` seems to have hung?

**Comment by matthiaskrgr** [comment]
yeah, waiting to see if its just the output that is stuck or the entire job

**Pull request merged**
