### PR TITLE
miri unsizing: fix projecting into a field of an operand

### LINKED ISSUE #754: ICE with validation disabled
The following test passes normally but ICEs when validation gets disabled:
```rust
use std::cell::*;

fn main() {
    let cell: RefCell<[i32; 3]> = RefCell::new([1, 2, 3]);
    {
        let mut cellref: RefMut<'_, [i32; 3]> = cell.borrow_mut();
        cellref[0] = 4;
        let mut coerced: RefMut<'_, [i32]> = cellref;
        coerced[2] = 5;
    }
    {
        let comp: &mut [i32] = &mut [4, 2, 5];
        let cellref: Ref<'_, [i32; 3]> = cell.borrow();
        assert_eq!(&*cellref, comp);
        let coerced: Ref<'_, [i32]> = cellref;
        assert_eq!(&*coerced, comp);
    }
}
```

We don't test `-Zmiri-disable-validation` very much. But we also cannot test every flag...

### PR DESCRIPTION
**Pull request by RalfJung**
I don't know why this open-coded an operand field projection. Probably this code predates one or more of my refactorings.

Fixes https://github.com/rust-lang/miri/issues/754

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
Ouch, seems like when a PR is rolled up, the issues it mentions with "Fixes" do not get closed? Cc @Centril

**Comment by Centril** [comment]
That is strange... cc @kennytm

**Comment by kennytm** [comment]
You'll need to ask GitHub why 😅. But I guess it's because the rollup committer is @Centril who likely does not have write access to rust-lang/miri, so the issue isn't auto-closed.

**Pull request merged**
