### PR TITLE
Stabilize 'attr_literals' feature.

### PR DESCRIPTION
**Pull request by SergioBenitez**
RFC Issue: rust-lang/rfcs#1559
Tracking Issue: rust-lang/rust#34981

Reference PR: https://github.com/rust-lang-nursery/reference/pull/388.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Whoops! Forgot to update the UI output.

One of the tests is failing for seemingly unrelated reasons:

```
[00:42:54] thread '[ui] ui/issue-43925.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3149:9
[00:42:54] 
[00:42:54] ---- [ui] ui/parser/expected-comma-found-token.rs stdout ----
[00:42:54] diff of stderr:
[00:42:54] 
[00:42:54] -	error: expected one of `)` or `,`, found `label`
[00:42:54] -	  --> $DIR/expected-comma-found-token.rs:19:5
[00:42:54] +	error[E0601]: `main` function not found in crate `expected_comma_found_token`
[00:42:54] 3	   |
[00:42:54] -	LL |     message="the message"
[00:42:54] -	   |                          - expected one of `)` or `,` here
[00:42:54] -	LL |     label="the label"
[00:42:54] -	   |     ^^^^^ unexpected token
[00:42:54] +	   = note: consider adding a `main` function to `$DIR/expected-comma-found-token.rs`
[00:42:54] 8	
[00:42:54] -	error: aborting due to previous error
[00:42:54] +	error[E0232]: `#[rustc_on_unimplemented]` requires a value
[00:42:54] +	  --> $DIR/expected-comma-found-token.rs:17:1
[00:42:54] +	   |
[00:42:54] +	LL | / #[rustc_on_unimplemented(
[00:42:54] +	LL | |     message="the message"
[00:42:54] +	LL | |     label="the label"
[00:42:54] +	LL | | )]
[00:42:54] +	   | |__^ value required here
[00:42:54] +	   |
[00:42:54] +	   = note: eg `#[rustc_on_unimplemented = "foo"]`
[00:42:54] 10	
[00:42:54] +	error: aborting due to 2 previous errors
[00:42:54] +	
[00:42:54] +	Some errors occurred: E0232, E0601.
[00:42:54] +	For more information about an error, try `rustc --explain E0232`.
[00:42:54] 11	
```

This is the path that leads to this error:

```rust
        let result = if let Some(items) = attr.meta_item_list() {
            Self::parse(tcx, trait_def_id, &items, attr.span, true).map(Some)
        } else if let Some(value) = attr.value_str() {
            Ok(Some(OnUnimplementedDirective {
                condition: None,
                message: None,
                subcommands: vec![],
                label: Some(OnUnimplementedFormatString::try_parse(
                    tcx, trait_def_id, value.as_str(), attr.span)?),
                note: None,
            }))
        } else {
            return Err(parse_error(tcx, attr.span,
                                   "`#[rustc_on_unimplemented]` requires a value",
                                   "value required here",
                                   Some(r#"eg `#[rustc_on_unimplemented = "foo"]`"#)));
        };
```

For some reason, the `else` branch is being called as opposed to the first branch, as expected. This implies that the attribute's contents aren't parsing as a `meta_item_list()`. But this PR makes no changes to any parsing code, nor did it change this test, so I'm quite surprised that this is failing.

Taking a closer look now.

**Comment by SergioBenitez** [comment]
Rather interestingly, this PR has uncovered several issues and inconsistencies in the codebase when it comes to dealing with attributes and determining whether arbitrary tokens are allowed in them.

In particular, in https://github.com/rust-lang/rust/pull/40346, attribute syntax was expanded to allow for arbitrary tokens as input. This change was not part of any RFC and was made without either a new RFC or a new feature gate. In https://github.com/rust-lang/rust/pull/40346#issuecomment-284947604, @jseyfried notes that the change should only take affect when the `proc_macro` is enabled. That is, if `proc_macro` is not enabled, attributes should continue being restricted to meta-items.

The recently stabilization of `proc-macro` meant that this syntax was also implicitly stabilized, though strangely, the restriction continued being enforced when the `attr_literal` feature was enabled. I believe this was likely a mistake, and we _should_ continue enforcing meta-items everywhere, at least until a decision is made.

As such, I've decided to add a new feature, `arbitrary_attrs`, that enables arbitrary tokens in attributes. When the feature is enabled, attributes can contain any input.

**Comment by petrochenkov** [comment]
@SergioBenitez 
>in #40346, attribute syntax was expanded to allow for arbitrary tokens as input ... jseyfried notes that the change should only take affect when proc_macro is enabled.

This is outdated information, https://github.com/rust-lang/rust/pull/50120 restricts attribute grammar for *proc macro* attributes.

The "literals in attributes" RFC affects only *non-macro* attributes that are parsed as so called "meta-items" and have a separate very restricted grammar (ident + literal + list of idents/literals/lists).

As I [previously mentioned](https://github.com/rust-lang/rust/issues/34981#issuecomment-373219824) on the tracking issue, the whole situation is mess, but at least stabilization of arbitrary literals in addition to currently stable string literals will not make it worse, but simultaneous support for arbitrary tokens in meta-items certainly will.

**Comment by SergioBenitez** [comment]
@petrochenkov I'm not sure what you're proposing, if anything.

The situation is that there are tests that assume that arbitrary tokens are allowed and there are tests that check that arbitrary tokens are _not_ allowed. The only way I can see to make both situations work is to have a feature flag that determines when attributes are checked to be meta-items. Are you proposing that there's another way?

**Comment by petrochenkov** [comment]
@SergioBenitez 
I think I misinterpreted you suggestion about adding new `feature(arbitrary_attr_input)`. It's supposed to just replace the current `features.use_extern_macros()`-based gating, right?

>The situation is that there are tests that assume that arbitrary tokens are allowed and there are tests that check that arbitrary tokens are not allowed.

`run-pass-fulldeps/proc-macro/derive-b.rs` isn't actually supposed to work (even without the meta-item restriction only delimited token streams are allowed: `attr(arbitrary tokens)` - OK, `attr arbitrary tokens` - Not OK), it's good that this PR found it.
But if it continues being feature-gated it can be fixed later.

>I'm not sure what you're proposing

Ok, now I'm proposing to keep the patch as is, except for restoring the
```rust
        if self.context.features.use_extern_macros() && attr::is_known(attr) {
            return
        }
```
clause.
Other stuff is not really in scope for this PR.

(I'm working on blockers for stabilization of `use_extern_macros` right now, so I'll fix the attribute grammar issues as well as a part of that work.)

**Comment by SergioBenitez** [comment]
Alright, looks like the CI is happy!

**Comment by petrochenkov** [comment]
r=me after FCP in https://github.com/rust-lang/rust/issues/34981 is complete.

**Comment by SergioBenitez** [comment]
@cramertj @petrochenkov All's ready!

**Pull request merged**
