### PR TITLE
Update the stdsimd submodule

### PR DESCRIPTION
**Pull request by alexcrichton**
This brings in a few updates:

* Update wasm intrinsic naming for atomics
* Update and reimplement most simd128 wasm intrinsics
* Other misc improvements here and there, including a small start to
  AVX-512 intrinsics

### CODE REVIEW

**Comment by TimNN** [comment]
R=me if travis is green

**Comment by alexcrichton** [comment]
@bors: rollup- r=TimNN

Did some investigation locally and looks like the rollup may have gotten mixed up and forgot the last commit of stdsimd, which is needed to fix that failure (and is oddly enough present in this PR...)

**Comment by pietroalbini** [comment]
@bors retry

Trying to wake bors up.

**Pull request merged**
