### PR TITLE
Gate  unsigned unary negate

### PR DESCRIPTION
**Pull request by pnkfelix**
Feature-gate  unsigned unary negate.

Discussed in weekly meeting here: https://github.com/rust-lang/meeting-minutes/blob/master/weekly-meetings/2015-03-31.md#feature-gate--expr

and also in the internals thread here: http://internals.rust-lang.org/t/forbid-unsigned-integer/752

Also, one might rightfully point out that this is fallout from https://github.com/rust-lang/rfcs/pull/560 , which has tracking issue https://github.com/rust-lang/rust/issues/22020

### CODE REVIEW

**Comment by pnkfelix** [comment]
r? @nikomatsakis 

bootstraps

(and I'm running `make check` locally now.)

Obviously in need of a rebase too, though.

**Comment by pnkfelix** [comment]
(also I forgot to remove the `Neg` impl for unsigned types, as discussed in the internals thread.  I'll do that too.)

**Comment by nikomatsakis** [comment]
r+ if we remove the impl

**Comment by pnkfelix** [comment]
Removed the `Neg` impls and rebased, but still need to run `make check` locally now ... :(

@alexcrichton what is our rollup schedule?  I.e. what is expected deadline for beta, has it passed?

**Comment by alexcrichton** [comment]
We should be able to land everything so long as it's in the queue in the next 3.5 hours (and maybe even slightly after!)

**Comment by pnkfelix** [comment]
(adding to 1.0 beta milestone so that it does not get forgotten by accident.  Though it may well get discarded by choice, if this local bootstrap does not get finished soon... how on earth is the compiler so slow for me ...)

**Comment by pnkfelix** [comment]
@alexcrichton reports that this commit https://github.com/alexcrichton/rust/commit/6fe1233f618298c7a0594fb2971860ea1220fd1e gets him through `make check`; I am trying to cherry-pick that to my own repo now; will push in a minute...

**Comment by pnkfelix** [comment]
r=nikomatsakis  f86318d

**Pull request merged**
