### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #130209 (Stabilize `std::io::ErrorKind::CrossesDevices`)
 - #130254 (Stabilize `std::io::ErrorKind::QuotaExceeded`)
 - #132187 (Add Extend impls for tuples of arity 1 through 12)
 - #133875 (handle `--json-output` properly)
 - #133934 (Do not implement unsafe auto traits for types with unsafe fields)
 - #133954 (Hide errors whose suggestions would contain error constants or types)
 - #133960 (rustdoc: remove eq for clean::Attributes)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=130209,130254,132187,133875,133934,133954,133960)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors retry
 lets see if this is spurious, I don't see any codegen related changes in the prs, cant repro locally

**Comment by jieyouxu** [comment]
@matthiaskrgr this is one of the #133959 examples, specifically #110290 😸

**Comment by Mark-Simulacrum** [comment]
Regression is almost certainly due to https://github.com/rust-lang/rust/pull/132187, which rightfully causes more work for rustdoc by adding extra impls. Not something to be very concerned about in practice.

**Pull request merged**
