### PR TITLE
Fix check for globally routable IPv4 address

### LINKED ISSUE #24314: Some special IP addresses are being wrongly detected as globally routable
An example is the special broadcast address `255.255.255.255/32` which is being detected as globally routable

```
Abhishek@Abhisheks-MacBook-Pro:~/src/rust (master %=)$ cat ip-test.rs
#![feature(ip)]
use std::net::Ipv4Addr;

fn main() {
    let x = Ipv4Addr::new(255,255,255,255);
    println!("{0}", x.is_global())
}
Abhishek@Abhisheks-MacBook-Pro:~/src/rust (master %=)$ ./ip-test
true
Abhishek@Abhisheks-MacBook-Pro:~/src/rust (master %=)$ ./x86_64-apple-darwin/stage2/bin/rustc --version --verbose
rustc 1.0.0-dev (c897ac04e 2015-04-10) (built 2015-04-10)
binary: rustc
commit-hash: c897ac04e2ebda378fd9e38f6ec0878ae3a2baf7
commit-date: 2015-04-10
build-date: 2015-04-10
host: x86_64-apple-darwin
release: 1.0.0-dev
```

This is because the code [1] does not take into account these special class of address as defined by RFC 6890 [2].

[1] https://doc.rust-lang.org/src/std/net/ip.rs.html#119
[2] http://tools.ietf.org/html/rfc6890

### PR DESCRIPTION
**Pull request by achanda**
- Adds two more functions for broadcast address and special
  address classes reserved for documentation
- Modifies the globally routable IP check to include these
  new functions

Fixes #24314

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you add some tests for these as well?

**Comment by achanda** [comment]
@alexcrichton should I add a new file with the issue number like in https://github.com/rust-lang/rust/tree/master/src/test/run-pass
Still pretty new to the codebase :)

**Comment by alexcrichton** [comment]
That'll work, but it's more conventional to put unit tests at the end of the module itself, so feel free to add something like this to the end of the module:

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn foo() { /* ... */ }
}
```

**Comment by achanda** [comment]
@alexcrichton sorry, I deleted my earlier comment by mistake. I found existing tests for `ip.rs` in `src/libstd/net/addr.rs`, which looks like a wrong place for those tests. I think I will do this, add tests for the new methods in `addr.rs` and the move related tests to `ip.rs` in a separate commit. That way we do not clutter this commit. Let me know if this sounds good to you.

**Comment by alexcrichton** [comment]
Sounds great to me, thanks for the drive-by cleanup!

**Comment by achanda** [comment]
@alexcrichton this passes tests on my local machine. Please check.

**Comment by alexcrichton** [comment]
@bors: r+ f60f4b7d7cde90edb248159cf5e351816cce8d8a

Thanks!

**Comment by achanda** [comment]
@alexcrichton How will this PR be merged? I did not see any job being run for this PR in buildbot. Do I need to do something else? Sorry, still new here :)

**Comment by alexcrichton** [comment]
Ah right, this is now [in the queue](http://buildbot.rust-lang.org/homu/queue/rust) and when it reaches the top @bors will comment that it's being tested. After that @bors will comment with the test results afterwards.

**Comment by achanda** [comment]
:+1:

**Pull request merged**
