### PR TITLE
Fix bugs in Peekable and Flatten when using non-fused iterators

### PR DESCRIPTION
**Pull request by timvermeulen**
I fixed a couple of bugs with regard to the `Peekable` and `Flatten`/`FlatMap` iterators when the underlying iterator isn't fused. For testing, I also added a `NonFused` iterator wrapper that panics when `next` or `next_back` is called on an iterator that has returned `None` before, which will hopefully make it easier to spot these mistakes in the future.

### Peekable

`Peekable::next_back` was implemented as
```rust
self.iter.next_back().or_else(|| self.peeked.take().and_then(|x| x))
```
which is incorrect because when the `peeked` field is `Some(None)`, then `None` has already been returned from the inner iterator and what it returns from `next_back` can no longer be relied upon. `test_peekable_non_fused` tests this.

### Flatten

When a `FlattenCompat` instance only has a `backiter` remaining (i.e. `self.frontiter` is `None` and `self.iter` is empty), then `next` will call `self.iter.next()` every time, so the `iter` field needs to be fused. I fixed it by giving it the type `Fuse<I>` instead of `I`, I think this is the only way to fix it. `test_flatten_non_fused_outer` tests this.

Furthermore, previously `FlattenCompat::next` did not set `self.frontiter` to `None` after it returned `None`, which is incorrect when the inner iterator type isn't fused. I just delegated it to `try_fold` because that already handles it correctly. `test_flatten_non_fused_inner` tests this.

r? @scottmcm

### CODE REVIEW

**Comment by Amanieu** [comment]
> Furthermore, previously FlattenCompat::next did not set self.frontiter to None after it returned None, which is incorrect when the inner iterator type isn't fused. I just delegated it to try_fold because that already handles it correctly. test_flatten_non_fused_inner tests this.

I am concerned that the generated code is now substantially more complicated. Wouldn't it have been better to simply set `frontiter` to `None` after the `if`?

All the other changes look fine.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@timvermeulen  can you please address the comments from Amanieu? Thank you.

**Comment by timvermeulen** [comment]
Sorry, yep, I'll address them soon.

**Comment by timvermeulen** [comment]
@Amanieu Thanks for taking a look! I assumed that the generated code for `next` / `next_back` would be the same, but benchmarks show that this was indeed a regression, so I've fixed it in the way you suggested.

**Pull request merged**
