### PR TITLE
[beta] travis: Use upstream LLVM repositories for Fuchsia

### LINKED ISSUE #41396: Fuschia builds are going to block beta backports
In https://github.com/rust-lang/rust/pull/41365 we saw a travis failure because a URL was not a valid gz - https://travis-ci.org/rust-lang/rust/jobs/223417092#L991.

https://fuchsia.googlesource.com/third_party/llvm/+archive/5463083.tar.gz seems dead.

While the docker image is reused from the cache we can get by, but this is probably going to start blocking the queue shortly (I'm not currently clear what caused the linked PR to do the rebuild).

ping @tedsta @raphlinus

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a backport of https://github.com/rust-lang/rust/pull/41130 which...

Closes #41396

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r=aidanhs p=1

(beta backport)

**Comment by aidanhs** [comment]
```
Undefined symbols for architecture i386:

  "_OBJ_bsearch_ex_", referenced from:

      _sk_find in libcrypto.a(stack.o)

      _sk_find_ex in libcrypto.a(stack.o)

ld: symbol(s) not found for architecture i386
```
Possible variant of #40417? Definitely unrelated to this PR.

**Comment by arielb1** [comment]
Looks like it

@bors retry

**Comment by aidanhs** [comment]
Time limit exceeded. Looks like it rebuilt the docker image. sccache should have everything cached now so should work with a retry?

**Pull request merged**
