### PR TITLE
Remove  .iter() calling suggestion when Iterator isn't implemented

### LINKED ISSUE #50773: Don't suggest calling `.iter()` when unsatified `Iterator` bound does not originate from an expression
Demo:

```rust
struct S<I: Iterator>(I);
struct T(S<u8>);
fn main() {}
```

This will cause the strange suggestion:

```
error[E0277]: the trait bound `u8: std::iter::Iterator` is not satisfied
 --> src/main.rs:2:10
  |
2 | struct T(S<u8>);
  |          ^^^^^^ `u8` is not an iterator; maybe try calling `.iter()` or a similar method
  |
  = help: the trait `std::iter::Iterator` is not implemented for `u8`
note: required by `S`
 --> src/main.rs:1:1
  |
1 | struct S<I: Iterator>(I);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
```

There is no place to "call `.iter()`". That suggestion should be removed here.

### PR DESCRIPTION
**Pull request by csmoe**
Closes #50773
r? @estebank

### CODE REVIEW

**Comment by varkor** [comment]
This is not the correct fix. Often, when users try this, calling `.iter()` _is_ what they want to do. What you want to do instead is check to see whether it's _possible_ to call `.iter()`, and only suggest calling it if it's available. In other words, the suggestion should be contextual, otherwise we regress the error messages.

**Comment by csmoe** [comment]
@varkor this error lint only emits when `Iterator` is not implemented for given expr as the error message says `std::collections::Iterator` is not implemented for T.

**Comment by estebank** [comment]
The changes to the tests are a net improvement, but we would fail to recommend `iter()` when appropriate, which granted, I don't think is possible at the moment using `rustc_on_unimplemented`. Let me get back to this soon once I've had some time to think about it.

**Comment by stokhos** [comment]
Ping from triage! @estebank any update on this PR?

**Comment by TimNN** [comment]
Ping form triage, @estebank  / @rust-lang/compiler: This PR requires your review.

**Comment by estebank** [comment]
If we merge this change we'll need to cut a new ticket to go back to the drawing board and enable the compiler to suggest using `.iter()` when appropriate. @csmoe, do you mind if we keep this PR open until we come up with a clearer plan for that? Otherwise, at the very least we should add a `rustc_on_unimplemented` check [for array literals](http://play.rust-lang.org/?gist=e298b4d369d6146e9bc209fcd72c6e5c&version=nightly&mode=debug&edition=2015), where `.iter()` _is_ the right suggestion:

```
error[E0277]: the trait bound `[{integer}; 3]: std::iter::Iterator` is not satisfied
 --> src/main.rs:3:14
  |
3 |     for y in x {
  |              ^ `[{integer}; 3]` is not an iterator; maybe try calling `.iter()` or a similar method
  |
  = help: the trait `std::iter::Iterator` is not implemented for `[{integer}; 3]`
  = note: required by `std::iter::IntoIterator::into_iter`
```

Doing so would imply modifying the flags supported by `rustc_on_unimplemented` ([like in this PR](https://github.com/rust-lang/rust/pull/47613/files#diff-0e12890ad498e250783f40f88a8b8ec6)) to signal that the type is an array. This work can happen as a separate PR, but I would want to merge all of them within a short period of time to avoid a stable release with a regression in the suggestions.

**Comment by csmoe** [comment]
@estebank ok, I'll leave this open.

**Comment by TimNN** [comment]
Ping from triage! What is the status of the changes proposed here / the changes required to merge this PR?

Per our current [triage guidelines](https://forge.rust-lang.org/triage-procedure.html), a blocked PR will generally be closed after two weeks if no immediate progress is expected. Since there is no issue tracking the blockage of this PR, I wanted to ask about the current status before closing.

**Comment by estebank** [comment]
@TimNN created https://github.com/rust-lang/rust/issues/53766 to track the feature needed before being able to merge this PR.

@csmoe I'm closing this PR and will reopen it once the above ticket is fixed, to keep the queue clean. Will you have time in the future to rebase against master and introduce the use of the new filter into this?

**Comment by csmoe** [comment]
@estabank yes, I'll keep this in my todo until that happens.

**Pull request closed without merging**
