### PR TITLE
Enable `deny(unused_crate_dependencies)` in all `compiler/` crates.

### PR DESCRIPTION
**Pull request by nnethercote**
And remove a couple of unused dependencies that this found.

r? @jackh726

### CODE REVIEW

**Comment by nnethercote** [comment]
The false positives mentioned in the FIXME comments are annoying. I started a [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Unit.20test.20locations) to ask about that.

**Comment by nnethercote** [comment]
```
error: external crate `libc` unused in `rustc_data_structures`: remove the dependency or add `use libc as _;`
```
This error is because `libc` is used in `rustc_data_structures` for some platforms (Unix) but not for others (Windows). One way to fix would be to change the `Cargo.toml` file to list `libc` as a conditional dependency. The other way would be to add a `use libc as _` to the `lib.rs` file. Not sure which is better. I'm feeling quite ambivalent about this PR overall.

**Comment by ChrisDenton** [comment]
> One way to fix would be to change the Cargo.toml file to list libc as a conditional dependency. The other way would be to add a use libc as _ to the lib.rs file. Not sure which is better.

On the one hand I do prefer the former but on the other hand I don't really care *that* much...

**Comment by erikdesjardins** [comment]
I believe `libc` usage being removed on Windows was a deliberate change (cc @saethlin), so I'd suggest making it a conditional dependency so no future usages get added.

**Comment by saethlin** [comment]
Heh yes I wrote the PR to remove libc on Windows but the idea/motivation was @ChrisDenton.

**Comment by nnethercote** [comment]
Based on the discussion in Zulip I think this lint isn't quite reliable enough to be used en masse like this. Which is a shame. I've filed #126368 for removing a couple more unused dependencies.

**Pull request closed without merging**
