### PR TITLE
submodules: update clippy from fb33fad0 to d2f51228

### LINKED ISSUE #61287: `rls` no longer builds after rust-lang/rust#61274
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#61274, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Changes:
````
Rustup to https://github.com/rust-lang/rust/pull/61203
rustup https://github.com/rust-lang/rust/pull/60928
rustup https://github.com/rust-lang/rust/pull/61164 (which is included in https://github.com/rust-lang/rust/pull/61274)
````

Fixes #61287

r? @oli-obk

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r-
I'll need to do another update of this after https://github.com/rust-lang/rust-clippy/pull/4153 is merged

**Comment by matthiaskrgr** [comment]
Clippy updated again, should be good to go now // cc @oli-obk

**Comment by mzji** [comment]
#61203 breaks the build, it requires another clippy PR to fix this error

**Comment by kennytm** [comment]
@bors r-

Clippy UI tests failed to account for the newly enabled idiom lints (`dyn Trait`). 

&nbsp;&nbsp;&nbsp;&nbsp;*Ironic. It could lint others from bad code, but not itself.*

**Comment by matthiaskrgr** [comment]
Mh, it's not adding the `S-waiting-on-review` label :man_shrugging:

**Comment by ishitatsuyuki** [comment]
Here you go.

**Comment by mati865** [comment]
:crossed_fingers: for not breaking Clippy in next 6 hours.

**Comment by jens1o** [comment]
This means that it'll be included in tomorrows nightly release?

**Comment by mati865** [comment]
@jens1o yes, unless some other pull breaks it's build.

**Pull request merged**
