### PR TITLE
Move compile-fail tests that are rejected by the parser to parse-fail

### PR DESCRIPTION
**Pull request by fhahn**
This PR moves all `compile-fail` tests that fail at the parsing stage to a `parse-fail` directory, in order to use the tests in the `parse-fail` directory to test if the new LALR parser rejects the same files as the Rust parser (as suggested by @brson in #21452). I also adjusted the `testparser.py` script to handle the tests in `parse-fail` differently.

However during working on this, I discovered, that Rust's parser sometimes fails during parsing, but does not return a nonzero return code, e.g. compiling `/test/compile-fail/doc-before-semi.rs` with `-Z parse-only` prints an error message, but returns status code 0. Compiling the same file without `-Z parse-only`, the same error message is displayed, but error code 101 returned. I'll look into that over the next week.

### CODE REVIEW

**Comment by Potpourri** [comment]
You can also move here these two tests: `use-mod-4.rs` and `use-ends-with-mod-sep.rs`?

**Comment by nikomatsakis** [comment]
@bors r+ 4e544ca 

nice

**Comment by nikomatsakis** [comment]
very excited to see this infrastructure coming together

**Comment by brson** [comment]
Nice.

**Comment by fhahn** [comment]
@Potpourri done. But there are some more files that fail during the parse stage. I'll try to fix the bug mentioned in the description as soon as possible.

**Comment by alexcrichton** [comment]
Unfortunately I think that this actually stopped running all these tests: https://github.com/rust-lang/rust/pull/22118#issuecomment-73586615.

Don't sweat it too much, but I recommend doing extra tests on Makefile-based changes in the future, we unfortunately don't have automation in place to make sure tests are run!

**Pull request merged**
