### PR TITLE
docs: Add example, reference link for `type` keyword.

### LINKED ISSUE #114281: type keyword no generics example
### Location

https://doc.rust-lang.org/stable/std/keyword.type.html

### Summary

The docs don't provide an example of a type with a generic, for example:
```rust
type ArcMutex<T> = Arc<Mutex<T>>;
```
While it is fairly obvious, I think it'd be nice to have it documented.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Fixes #114281.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I originally had an additional example with a `where` clause, but since it failed and wasn't essential, I removed it.

**Comment by fmease** [comment]
> I originally had an additional example with a where clause, but […] it failed

Yeah, fyi, where clauses are not properly supported on type aliases. In a future edition they might be (currently available under `#![feature(lazy_type_alias)]`).

**Comment by waywardmonkeys** [comment]
@fmease Yes, it is slightly confusing after reading https://doc.rust-lang.org/reference/items/type-aliases.html and thinking they exist. :)

**Comment by fmease** [comment]
Right, that's only the grammar. Syntactically they are allowed, semantically they are mostly ignored. I admit it that it can be a bit confusing if you are not familiar with this. However, it's correct technically speaking ^^

**Comment by fmease** [comment]
Hmm, I dunno. Personally I quite like it and these pages typically link to the Reference, so I guess it's fine.

**Comment by cuviper** [comment]
LGTM!

@bors r+ rollup

**Pull request merged**
