### PR TITLE
[DO NOT MERGE] deny `array_into_iter` by default (for crater run)

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
In #66017 I had the idea of letting crater test all regressions from #65819 with the `array_into_iter` lint on deny. That way we would be able to find out if the lint catches all of the regressions. There is certainly code that could break with #65819 but isn't caught by the lint (see [this comment](https://github.com/rust-lang/rust/pull/66017#issuecomment-549593726)), but we don't know if strange code like that exists in the real world at all.

*However*, I assumed that we can tell crater to compile the exact version of all crates as in the previous run. Looking at [this comment](https://github.com/rust-lang/rust/pull/65294#issuecomment-546649012) it seems like we can only pass crate names (without version) to crater? So....

- ~~Can we tell crater which versions of crates to build?~~ [No](https://github.com/rust-lang/rust/pull/66201#issuecomment-555468991)
  - ~~Can we even tell crater something like "never use dependency versions released after date X"?~~ [No](https://github.com/rust-lang/rust/pull/66201#issuecomment-555468991)
- If we can't, should we run crater anyway since it's only a few thousand crates?
- Or is there a better we can test the coverage of the lint?

### CODE REVIEW

**Comment by joelpalmer** [comment]
Ping from Triage:  @davidtwco @LukasKalbertodt any updates?

**Comment by LukasKalbertodt** [comment]
From my side this is ready. We just have to decide if a crater run is useful and then someone needs to prepare a list of all crates that we want to test again and start crater. In my top post I list a few questions about crater; if someone can answer them, that would be helpful.

**Comment by davidtwco** [comment]
I'm not sure I'm the best person to review this, r? @Centril

**Comment by Centril** [comment]
cc @pietroalbini for the crater questions.
r? @withoutboats for the libs policy stuff

**Comment by pietroalbini** [comment]
> * Can we tell crater which versions of crates to build?
>   * Can we even tell crater something like "never use dependency versions released after date X"?

No.

**Comment by LukasKalbertodt** [comment]
Given that we can't test for specific versions, I will just close this PR now. I doubt testing "roughly the same set of crates" gives us any useful information.

**Pull request closed without merging**
