### PR TITLE
Document use of `compiler_builtins` with `no_std` binaries

### PR DESCRIPTION
**Pull request by ranweiler**
See discussion in #43264.

The docs for the `compiler_builtins_lib` feature were removed in
PR #42899. But, though the `compiler_builtins` library has been
migrated out-of-tree, the language feature remains, and is needed to
use the stand-alone crate. So, we reintroduce the docs for the
feature, and add a reference to them when describing how to create a
`no_std` executable.

### CODE REVIEW

**Comment by aidanhs** [comment]
Thanks for the PR @ranweiler! We'll check in now and again to make sure @frewsxcv or another reviewer gets to this soon.

However, it looks like our tidy check is currently failing with
```
[00:02:43] tidy error: The Unstable Book has a 'library feature' section 'compiler_builtins_lib' which doesn't correspond to an unstable library feature
```

**Comment by frewsxcv** [comment]
hmm, so it looks like the tidy check is failing because it doesn't know about this `compiler_builtins_lib`.

for reference [here's the code for the unstable book tidy lint](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/unstable_book.rs).

also, [here's the function that gets called to retrieve the unstable language features](https://github.com/rust-lang/rust/blob/1edbc3df0d051902916ead8e81db16a6f546f973/src/tools/tidy/src/features.rs#L214).

**Comment by ranweiler** [comment]
Ha, thanks @frewsxcv, I was just looking at that exact code. I found the problem. In the PR I cite above, we here add `src/libcompiler_builtins` to the list of directories to skip in `map_lib_features` [here](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/features.rs#L302). However, that directory is where the unstable library feature is defined. I'll add a commit to revert that change.

**Comment by ranweiler** [comment]
Ouch, I amended my commit to revert the blacklist, and it resulted in a whole slew of new tidy errors. Working on it locally.

**Comment by alexcrichton** [comment]
@ranweiler want to just [explicitly whitelist it](https://github.com/rust-lang/rust/blob/ae98ebfcb9ad5a5384fd229a6ee91315b02ca969/src/tools/tidy/src/unstable_book.rs#L96-L103) to avoid checking it?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by frewsxcv** [comment]
@bors rollup r-

```
[00:44:47] Linkcheck (x86_64-unknown-linux-gnu)

[00:44:53] unstable-book/print.html:1045: broken link - unstable-book/library-features/compiler-builtins-lib.html

[00:44:53] unstable-book/language-features/lang-items.html:248: broken link - unstable-book/library-features/compiler-builtins-lib.html

[00:44:54] thread 'main' panicked at 'found some broken links', /checkout/src/tools/linkchecker/main.rs:49:8
```

**Comment by ranweiler** [comment]
Alright, I think I had some stale local state, but everything looks good now!

r? @alexcrichton

**Pull request merged**
