### PR TITLE
Sync rustc_codegen_cranelift

### PR DESCRIPTION
**Pull request by bjorn3**
For cg_clif itself there have been a couple of bug fixes since the last sync, a Cranelift update and implemented all remaining simd platform intrinsics used by `std::simd`. (`std::arch` still misses a lot though) Most of the diff is from reworking of the cg_clif build system though.

r? @ghost

@rustbot label +A-codegen +A-cranelift +T-compiler

### CODE REVIEW

**Comment by bjorn3** [comment]
r? @joshtriplett

could you please double check that I correctly handled the vendoring in the last commit?

**Comment by joshtriplett** [comment]
@bjorn3 LGTM

**Comment by bjorn3** [comment]
Thabks for taking a look!

@bors r+

**Comment by matthiaskrgr** [comment]
might fail in a rollup, let's find out
@bors p=1 subtree sync

**Pull request merged**
