### PR TITLE
[beta] backports + bootstrap bump

### PR DESCRIPTION
**Pull request by cuviper**
Add pending backports:

* Revert accidental stabilization #94805 
* Do not recover from Ty? in macro parsing #94593 
* Fix cmake build. #95050 

And updates the bootstrap compiler to 1.59.0.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Mind pulling in the beta-backports, so we bundle the CI cycle into just one? Looks like there should be two: https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3Abeta-accepted+label%3Abeta-nominated

**Comment by cuviper** [comment]
Ok, I've added the two backports.

**Comment by Mark-Simulacrum** [comment]
Thanks!

@bors r+ rollup=never

**Comment by slanterns** [comment]
Seems https://github.com/rust-lang/rust/pull/95050 should also be included?

**Comment by cuviper** [comment]
Thanks @slanterns, I added it.

**Pull request merged**
