### PR TITLE
Unsupport `#[derive(Trait)]` sugar for `#[derive_Trait]` legacy plugin attributes

### LINKED ISSUE #29644: Tracking issue for `custom_derive` feature
Treats `#[derive(Anything)]` like `#[derive_Anything]`. Tracking for stabilization.

### PR DESCRIPTION
**Pull request by petrochenkov**
This is a long deprecated unstable feature that doesn't mesh well with regular resolution/expansion.

How to fix broken code:
- The recommended way is to migrate to stable procedural macros - derives or attributes (https://doc.rust-lang.org/nightly/book/first-edition/procedural-macros.html).
- If you are using `rocket 0.3.*` in particular, the recommended solution is to migrate to `rocket 0.4.*`.
- If that's not possible right now for some reason, you can keep code working with a simple mechanical replacement `#[derive(Legacy)]` -> `#[derive_Legacy]`.

Closes https://github.com/rust-lang/rust/issues/29644

r? @ghost

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Review by alexcrichton — APPROVED** [review]

**Comment by SergioBenitez** [comment]
We've migrated all of Rocket's derives to procedural macros. That being said, that migration is not yet part of an official release, so this would be a breaking change for almost all of Rocket's users.

If it's possible to delay this PR until Rocket sees a new release, which should happen in a matter of weeks as there is only a single blocking feature remaining, that would be much appreciated.

**Comment by petrochenkov** [comment]
@SergioBenitez 
Yeah, I think this can wait for a few weeks.
Is there any issue that I can subscribe to for tracking Rocket's release status?

**Comment by SergioBenitez** [comment]
@petrochenkov The [`0.4` milestone](https://github.com/SergioBenitez/Rocket/milestone/5) tracks the missing features. Converting all of Rocket's code generation to proc-macros is tracked in https://github.com/SergioBenitez/Rocket/issues/693.

**Comment by Centril** [comment]
@SergioBenitez what's the status now?

**Comment by SergioBenitez** [comment]
@Centril We are no longer using this in Rocket as of the the 0.4 release candidate. The GA of 0.4 has not yet been released; that should happen on the 14th. Ideally this wouldn't be merged until some time after the GA is available to give users a chance to migrate.

**Comment by nagisa** [comment]
Rocket 0.4 is still not GA (is currently on -rc2, which has been published yesterday).

**Comment by petrochenkov** [comment]
[Yay.](https://crates.io/crates/rocket/0.4.0)
@bors r=eddyb,alexcrichton

**Pull request merged**
