### PR TITLE
Stabilize doc_cfg feature

### LINKED ISSUE #43781: Tracking issue for `#[doc(cfg(...))]`
This is a tracking issue for the `#[doc(cfg(...))]` attribute introduced in #43348.

**Steps:**

- [x] Implement
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

(cc #1998)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #43781 

cc @Nemo157 
cc @dtolnay 
cc @rust-lang/rustdoc 

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
I think @Nemo157 is still working on some improvements to this - in particular, they're going to make it enabled by default whenever you use `cfg(...)`, so you don't have to write both `cfg` and `doc(cfg)`. I think we should wait until that happens before stabilizing.

**Comment by GuillaumeGomez** [comment]
Then definitely (that would be so awesome!). Keeping this PR open in the meantime so no one else is tempted to open another one (including me hehe).

**Comment by Nemo157** [comment]
Yeah, I'll try to get the PR to look at that up tomorrow. It'll probably need some testing with popular libraries and feedback whether it's a net positive (I was initially against it in the discussion on the tracking issue because I thought it would run into too many internal details, but with the ability to override the documented `cfg` like I have implemented it I think it might be plausible).

**Comment by Nemo157** [comment]
One thing I'm still slightly wary about is

> doctests will only run on the appropriate platforms

Because most (all?) non-std users of this have been gating it to only run while building docs on docs.rs I don't know whether we know how this will affect them; it seems likely that this will result in some doctests silently not running. And personally what I need is the ability to gate _individual_ doctests based on cfgs, not all doctests for a single item.

**Comment by jyn514** [comment]
> doctests will only run on the appropriate platforms

Could we change the standard library to use `cfg_attr(predicate, doc(include))` or something like that? Then we can turn this off in rustdoc and have doc_cfg only do one thing.

**Comment by jhpratt** [comment]
For the curious: it looks like #79341 is the PR to make `#[doc(cfg(…))]` implied.

**Comment by jyn514** [comment]
I'm going to close this until we implement `cfg` implying `doc(cfg)`.

**Comment by passcod** [comment]
Given #89596 was merged, should this be re-opened?

**Comment by GuillaumeGomez** [comment]
I think https://github.com/rust-lang/rust/issues/90497 is a blocker for it.

**Comment by LoganDark** [comment]
> EDIT: nevermind, it should be ready now.

Do you have an ETA for the new attempt at stabilizing doc_cfg? [One of my new crates](https://docs.rs/imgref-iter) has some experimental things that are only available with a cargo feature.

**Comment by GuillaumeGomez** [comment]
I opened #100883.

**Pull request closed without merging**
