### PR TITLE
[stable] 1.34.1 point release

### PR DESCRIPTION
**Pull request by emilyalbini**
The release date is April 25th.

Included in this point release:

* #59891: Fix the link to sort_by_cached_key
* #59989: Fix links to Atomic* in RELEASES.md 
* https://github.com/rust-lang/rust-clippy/pull/3805: Fix ICE https://github.com/rust-lang/rust-clippy/issue/3747
* https://github.com/rust-lang/rust-clippy/pull/3821: do not trigger redundant_closure when there is a difference in borrow...
* https://github.com/rust-lang/rust-clippy/pull/3844: Fix two missing_const_for_fn false positives

### CODE REVIEW

**Comment by pietroalbini** [comment]
Good catch, added!

**Comment by jethrogb** [comment]
That failure can be ignored. Tests don't build for target x86_64-fortanix-unknown-sgx until #59136 which is not in stable yet.

**Comment by pietroalbini** [comment]
Eeek?

@bors retry

**Comment by jonas-schievink** [comment]
> ImportError: No module named lldb

I had a similar error when running the tests on Arch Linux, for me the solution was to uninstall the system's LLDB. Not sure why this suddenly popped up on AppVeyor though.

**Comment by pietroalbini** [comment]
Wtf? AppVeyor wasn't scheduled.

@bors retry

**Comment by pietroalbini** [comment]
@bors treeclosed=2000 retry

[AppVeyor is broken.](https://help.appveyor.com/discussions/problems/23201-request-to-github-web-hook-has-been-made-from-prohibited-ip-address)

**Comment by pietroalbini** [comment]
@bors treecloded-

AppVeyor said to have fixed the issue.

**Comment by Mark-Simulacrum** [comment]
Appveyor updated their build images on April 14th, which involved an LLVM upgrade (to 8) and Python upgrades: https://www.appveyor.com/updates/2019/04/14/. With the theory that this might be responsible for our troubles, I've pushed a commit downgrading to the "previous" image.

@bors r+

**Comment by jethrogb** [comment]
Same failure as before

**Comment by pietroalbini** [comment]
I think the `image:` yaml key has to be at the top level, not inside `environment:`.

@bors r=Mark-Simulacrum p=1000

**Pull request merged**
