### PR TITLE
Attempt to debug 259 exit code on AppVeyor

### PR DESCRIPTION
**Pull request by alexcrichton**
Let's try to dig in a bit more and see where this is coming from, it
looks like AppVeyor is also unsure where this is coming from!

### CODE REVIEW

**Comment by nagisa** [comment]
NB: you can RDP directly into an appveyor machine, so perhaps setting that up would help?

**Comment by alexcrichton** [comment]
Unfortunately we don't typically get a chance to see and debug these failures until hours after the build has finished. Additionally they're often spurious, and we can't be watching every single build.

**Comment by pietroalbini** [comment]
Still happening, opened a tracking issue in https://github.com/rust-lang/rust/issues/58160.

**Pull request merged**
