### PR TITLE
Revert #46694 (Temporarily use the old Travis image)

### PR DESCRIPTION
**Pull request by kennytm**
This PR reverts #46694, and applies the solution recommended in https://github.com/travis-ci/travis-ci/issues/8891#issuecomment-353403729.

r? @aidanhs

### CODE REVIEW

**Comment by kennytm** [comment]
Travis is green. Though maybe we could wait a few more days before merging, to see whether those two commands will be folded into the official image.

**Comment by aidanhs** [comment]
This seems good, but I looked up the address suggested since I know very little about IPv6.

http://silmor.de/ipv6.address.php and https://en.wikipedia.org/wiki/IPv6_address suggest `2001:db8::/32` is for documentation purposes only. I suspect the author of that comment copied it from the [Docker documentation](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/#how-ipv6-works-on-docker).

Instead, can we use the link-local address? I.e. `{"ipv6":true,"fixed-cidr-v6":"fe80::/64"}`. I tested it on Docker locally and it seems to correctly assign an ipv6 address.

r=me once that's done.

**Comment by aidanhs** [comment]
(I'd merge rather than waiting I suspect they're not going to make ad-hoc changes like this when they'll be shorter-staffed due to xmas)

**Comment by kennytm** [comment]
@bors r-

Needs to limit those docker commands to Linux.

**Comment by kennytm** [comment]
@bors rollup-

This PR caused `sccache` to fail with "Address already in use" during docker image setup when rolled up with other PRs. But Travis is green here 😕.

Details: https://travis-ci.org/rust-lang/rust/builds/320656619

**Pull request merged**
