### PR TITLE
miri realloc: do not require giving old size+align

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
Oli is on vacation for two weeks.

**Comment by cramertj** [comment]
Ah, sure! I feel fine about the code here, but I have no idea what the context is for this change. If you're comfortable that this is in fact a change you actually want to make here, then r=me I suppose, unless there's someone else who knows this code / what's going on here well.

**Comment by RalfJung** [comment]
It's a rather small change for a Miri-only API that I do feel confident in. This is needed to enable https://github.com/rust-lang/miri/pull/817 to land.

Thanks!

@bors r=cramertj

**Pull request merged**
