### PR TITLE
std: Implement try_reserve and try_reserve_exact on PathBuf

### PR DESCRIPTION
**Pull request by Xuanwo**
Part of https://github.com/rust-lang/rust/issues/91789

Signed-off-by: Xuanwo <github@xuanwo.io>

### CODE REVIEW

**Comment by Xuanwo** [comment]
@kennytm, Hi, do you have time to review this PR? Thanks in advance.

**Comment by TennyZhuang** [comment]
r? @dtolnay 

Can you take a look with this PR? which is similar to #92338

**Review by dtolnay — APPROVED** [review]
This looks good. Not sure why this didn't get assigned to me after the comment above.

**Pull request merged**
