### PR TITLE
Switch to smaller msvc runners

### PR DESCRIPTION
**Pull request by ChrisDenton**
Some PRs seem to be unmergeable due to issues with our msvc runners. Let's see if this helps and what impact it has.

try-job: x86_64-msvc
try-job: i686-msvc

### CODE REVIEW

**Comment by arttet** [comment]
```
failed to remove file `D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\liballoc-c482042979883213.rlib`
2024-09-26T15:35:50.6402719Z 
2024-09-26T15:35:50.6454365Z Caused by:
2024-09-26T15:35:50.7548850Z   Access is denied. (os error 5)
```

**Comment by arttet** [comment]
Do we have a chance to handle this magic issue?

**Comment by ChrisDenton** [comment]
Doesn't look like this will work. Closing.

**Pull request closed without merging**
