### PR TITLE
Update jemalloc to include various fixes for OSX 10.12

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@glandium out of curiosity was this done to fix bugs seen in the wild? In the sense that should we consider this for a backport?

**Comment by alexcrichton** [comment]
(backport to beta, that is)

**Comment by glandium** [comment]
485c9210bbfa9d8fb98b5d3fbe33a7a7e2c4fec9 might be fixing issues in the wild, but I'm not entirely sure they actually exist as such.

d5a6ab562890b93fec765c5d42884ce4fa5c61a0 + 62d87fce391b5a0a8a0ede05e6ee8b808cd57d88 do fix a non theoretical issue that happens in Thunderbird, where the address book manager calls into the system CoreData library, which then does something like malloc_zone_batch_malloc(malloc_default_zone(), ...) and that crashes with a branch to 0x0. It doesn't seem there are much more of those things in the wild, at least affecting Firefox or Thunderbird, from a quick look at crash reports.

But, existing or future system libraries may do similar things at any time, and if it happens in a process where jemalloc is registered as zone allocator, crash follows.

Now, for rust, this involves some crate using some system library through FFI that does those kinds of things. That's a pretty limited risk, and it's not going to be random crashes either: if someone tries to use CoreData from rust and use whatever it is in there that triggers the behavior we work around here, they would have crashed already on 10.12. OTOH, they may not have attributed it to rust...

**Comment by alexcrichton** [comment]
Ok, thanks for the explanation!

**Pull request merged**
