### PR TITLE
[breaking change] Remove a rustdoc back compat warning

### PR DESCRIPTION
**Pull request by oli-obk**
This warning was introduced in https://github.com/rust-lang/rust/pull/62855 for users who use `rustdoc` directly on proc macro crates (instead of using `cargo doc`) without passing `--crate-type proc-macro` (which `cargo doc` passed automatically).

### CODE REVIEW

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/cargo/pull/7159#issuecomment-525509241

@Aaron1011 are you still doing PR reviews?

**Comment by Aaron1011** [comment]
Could you add a test where we run `rustdoc` without passing `--crate-type proc-macro`?

**Comment by oli-obk** [comment]
@craterbot run mode=rustdoc

**Comment by oli-obk** [comment]
There seems to be no code on crater that was ignoring this back compat warning

**Comment by estebank** [comment]
r=me after rebase

**Pull request merged**
