### PR TITLE
Update Clippy

### LINKED ISSUE #64215: `clippy-driver` no longer builds after rust-lang/rust#64209
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#64209, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/64215

r? @oli-obk

### CODE REVIEW

**Comment by lzutao** [comment]
cc @Manishearth

**Comment by mati865** [comment]
It passed locally yesterday so this is probably new breakage.
I won't be available for at least 2 hours so if somebody wants to take over feel free to do so.

**Comment by mati865** [comment]
Breakage introduced by https://github.com/rust-lang/rust/pull/64231, I won't be able to update Clippy for it.

**Pull request closed without merging**
