### PR TITLE
return the correct type for closures in `type_of`

### PR DESCRIPTION
**Pull request by lcnr**
A bit unhappy about the way `typeck::check_crate` works rn. Would have preferred to not change `CollectItemTypesVisitor` in this way. 

r? @nikomatsakis

### CODE REVIEW

**Comment by lcnr** [comment]
> In general, I feel like the way things are *expected* to work is that `type_of` returns the "generic template" for the type.

yes, that is also my mental model for `type_of`. But before this PR, that isn't actually the case.
Before this, `type_of` returned `ty::Closure` with substs containing the dummy params for closure_kind, closure_signature, and upvars. To my knowledge, there is not really anything sensible you can do these substs.

With this change you can now actually call `type_of(closure_def_id).subst(tcx, substs)` and get the expected result.
I am using this in some wip rework of polymorphization where this is needed. If you want, we can talk more about this in sync.

**Comment by nikomatsakis** [comment]
@lcnr that makes sense, but I'm a bit confused. Why did that not work before? I guess maybe the question is "what are these substs you are using". I would have expected them to be the closure substs, which would then give a value for those closure type arguments and so forth, right?

**Comment by lcnr** [comment]
here's an example in case that might help
```rust
fn foo<T: Into<i32>, U>(x: T) -> i32 {
    let x = |y: i32| y + x.into();
    x(3)
}
```
before this PR, the type returned by `type_of` for `|y: i32| y + x.into()` was
```
ty::Closure(def_id, [T, U, <closure_kind>, <closure_signature>, <upvars>])
```
while with this PR, the type returned by `type_of` for `|y: i32| y + x.into()` is
```
ty::Closure(def_id, [T, U, i32, extern "rust-call" fn((i32,)) -> i32, (T,)])
```

Before this PR, the only way `subst` would be correct for the type of `x` is that we first substitute `<closure_kind>, <closure_signature>, <upvars>` with their actual values and then , using the result, call subst on the type of `x`.

With this PR, we can simply call subst with arguments for `T` and `U`.

**Comment by lcnr** [comment]
added an issue for a more complex fix in #92617

@bors r=nikomatsakis rollup

**Pull request merged**
