### PR TITLE
Introduced `llvm-libtool` option

### PR DESCRIPTION
**Pull request by catap**
An idea to allow to control used `libtool` to build LLVM. Useful in attmept to build / bootsrap rust to old or wired systems.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Is this environment variable standard (e.g., read by cmake itself or something?) -- otherwise, I would prefer that if it needs to be configured, we do so via config.toml rather than an ad-hoc environment variable.

**Comment by catap** [comment]
@Mark-Simulacrum nope, it isn't a standard environment variable. Let me move to config when.

**Comment by catap** [comment]
@Mark-Simulacrum like this?

**Comment by catap** [comment]
@Mark-Simulacrum yes, you're right that I'm trying to make `rust` works on old system. In my case it is macOS 10.6.

My goal is quite simple: bring rust to old macOS via MacPorts. MacPorts provides a lot of modern software to old system which includes modern clang :)

Why? Because rust is starting to be popular platform to write new software. For example mozjs.

Right now I've bring a bit old rust (1.42) to macOS 10.6 and I'm just bootstrapping it one-by-one, it requires some time :)

Patch? Yes, I needed it but it is releativle small. Differences with `rustc-1.42.0-src` is:
```
24 files changed, 125 insertions(+), 15 deletions(-)
```

**Comment by Mark-Simulacrum** [comment]
My sense is that if you need to adjust a bunch of llvm building opts, it probably makes sense to build llvm out of tree and specify it with llvm-config - that'll let you configure more freely, and without as much pain trying to pipe options through here.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust/pull/93756. Thanks!

**Pull request closed without merging**
