### PR TITLE
Fix json flag in bootstrap doc

### LINKED ISSUE #103816: x doc --json flag not working
running 
```
./x doc library/std --json --stage 0
```
only builds the html doc, but
```
RUSTDOCFLAGS="-Zunstable-options --output-format=json" ./x doc library/std --stage 0
```
builds the json doc.

I expected the json flag to act as the documentation says (`./x doc --help`):
```
        --json          render the documentation in JSON format in addition to
                        the usual HTML format
```

### Meta

using the master branch of this repo commit 2afca78a0b03db144c5d8b9f8868feebfe096309

running with a library profile.

### PR DESCRIPTION
**Pull request by viandoxdev**
Fix the `--json` flag not working with x.py (Closes #103816)

While this works I'm not sure about the `should_run` of `JsonStd`, had to change it because https://github.com/rust-lang/rust/blob/ab5a2bc7316012ee9b2a4a4f3821673f2677f3d5/src/bootstrap/builder.rs#L334 would match with JsonStd and remove the paths that Std matched. So I did [this](https://github.com/viandoxdev/rust/blob/ffd4078264c4892b5098d6191e0adfe3564d62ca/src/bootstrap/doc.rs#L526-L534) but that looks more like a hack/workaround than anything. I'm guessing there's something to do with the default condition thing but idk how it works

### CODE REVIEW

**Comment by jyn514** [comment]
@viandoxdev I think https://github.com/rust-lang/rust/commit/9791b9f9826adea1078775afbaf66545b319b78d is a more principled fix than your second commit, I would prefer to use that.

**Comment by viandoxdev** [comment]
9791b9f9826adea1078775afbaf66545b319b78d doesn't really fix the issue, I still need a way to not run the JsonStd steps when the flag isn't set. Currently just applying the changes of that commit makes it do both html and json regardless.

**Comment by jyn514** [comment]
Hmm, ok. In that case maybe we should make it the same Step as Std and call `doc_std` with the appropriate mode based on the flag, instead of having a separate step.

**Comment by viandoxdev** [comment]
> Hmm, ok. In that case maybe we should make it the same Step as Std and call `doc_std` with the appropriate mode based on the flag, instead of having a separate step.

did that

**Comment by viandoxdev** [comment]
@jyn514 thoughts?

**Comment by jyn514** [comment]
@viandoxdev I don't have time to look at this right now, I'll make sure I let you know after I have a change to look.

**Review by jyn514 — APPROVED** [review]
this is very well done :) I hadn't thought to make `format` part of the Std struct itself, that's absolutely the right thing to do since it avoids breaking RustdocJSStd tests.

**Comment by matthiaskrgr** [comment]
probably failed in https://github.com/rust-lang/rust/pull/104010#issuecomment-1304587434 but I'm not entierly sure
@bors rollup=iffy

**Comment by viandoxdev** [comment]
Should be fixed by 900af414a3dfabab74357f5038371a08b1cb0db1, but not sure how to test @matthiaskrgr

**Pull request merged**
