### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by Manishearth**
One of our tests using the alloc crate broke because alloc was stabilized.

r? @oli-obk

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Clippy broke again in the meantime: https://github.com/rust-lang/rust/pull/59967#issuecomment-483049191

**Comment by Manishearth** [comment]
Ah, more HirIDfication

**Comment by Manishearth** [comment]
(I'm on it)

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust-clippy/pull/3961

**Comment by Manishearth** [comment]
Updated. r? anyone?

**Pull request merged**
