### PR TITLE
Range experiment

### PR DESCRIPTION
**Pull request by pitaj**
Meant for a crater run to see how much breakage we can expect outside of the Iterator methods themselves

https://internals.rust-lang.org/t/pre-rfc-fixing-range-by-2027/19936

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Is there any way a crater run outcome could affect your suggested changes? From the patches you had to make all over the place here it's obvious that this cannot be done in a breaking way. And if we're doing it in a non-breaking (edition) way, then I don't think it matters how many people use it.

**Comment by pitaj** [comment]
@Nilstrieb my intention here is to just get information. This PR is full of breaking changes and is not meant to be merged. I fully intend to follow up with an RFC that specifies how we can make this change on an edition boundary.

In the linked IRLO topic, @tgross35 suggested the crater run:

> It would be interesting to do a crater run with the changed impls to have an idea of how widespread the effects are.

I added every iterator method to the range types so that we will only see type errors. And I set this up with deprecation warnings so we can evaluate how many cases use mutating methods.

Essentially the idea is to evaluate how much manual intervention will be necessary to transition from old range to new range.

**Comment by Nilstrieb** [comment]
I'm still not sure whether this is actually useful, but if you think so:
@bors try

**Comment by Nilstrieb** [comment]
Oh I forgot that it still doesn't bootstrap fully, gotta fix that first

**Pull request closed without merging**
