### PR TITLE
Rename `TyS.sty` to `TyS.kind`

### LINKED ISSUE #64353: Rename `.sty` field on `TyS`
`.kind` makes more sense, but could be confusing, as it's not a [type-theoretic kind](https://en.wikipedia.org/wiki/Kind_(type_theory)). There's also the issue of having inconsistent ways to name a field containing a `*Kind`, e.g. `.node` and `.kind`. It would be good to make these consistent.

### PR DESCRIPTION
**Pull request by varkor**
Fixes https://github.com/rust-lang/rust/issues/64353.

r? @eddyb

### CODE REVIEW

**Comment by joelpalmer** [comment]
Ping from Triage: Hi @varkor, any updates?

**Comment by varkor** [comment]
@joelpalmer: I'm waiting on @eddyb to review. This will merge conflict frequently, so I'll rebase when there's some movement on the PR.

**Comment by eddyb** [comment]
Please PM me on Matrix/IRC/Discord if you have something that bitrots easily.

**Review by eddyb — APPROVED** [review]
r=me once this is ready

**Comment by varkor** [comment]
@bors r=eddyb p=1
(Bitrots quickly.)

**Comment by Centril** [comment]
I think we should follow this up with renaming `node` to `kind` as well to be consistent.

**Pull request merged**
