### PR TITLE
Add missing links to usize in docs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus

### CODE REVIEW

**Comment by Alexendoo** [comment]
Ping from triage, any updates? @QuietMisdreavus

**Comment by ProgrammaticNajel** [comment]
Ping from triage. @QuietMisdreavus any updates on this? Thanks.

**Comment by Centril** [comment]
The PR builder seems unhappy with the PR atm; let's reopen to make sure it's good.

**Comment by GuillaumeGomez** [comment]
I'm not sure it is. I think a few occurrences failed to get resolved for some intra-doc links dark reasons...

**Comment by JohnCSimon** [comment]
Ping from triage 
@GuillaumeGomez hi! What's the status of this doc PR?

**Comment by GuillaumeGomez** [comment]
Need to update it.

**Comment by JohnTitor** [comment]
Ping from triage: @GuillaumeGomez any updates on this?

**Comment by GuillaumeGomez** [comment]
Still need to update it.

**Comment by JohnTitor** [comment]
Ping from triage: @GuillaumeGomez any updates on this?

**Comment by GuillaumeGomez** [comment]
Not yet.

**Comment by JohnTitor** [comment]
Ping from triage: @GuillaumeGomez any updates on this?

**Comment by Dylan-DPC** [comment]
Closing this after having a discussion with @GuillaumeGomez

**Pull request closed without merging**
