### PR TITLE
Specialization is unsound

### PR DESCRIPTION
**Pull request by RalfJung**
As discussed in https://github.com/rust-lang/rust/issues/31844#issuecomment-617013949, it might be a good idea to warn users of specialization that the feature they are using is unsound.

I also expanded the "incomplete feature" warning to link the user to the tracking issue.

### CODE REVIEW

**Comment by RalfJung** [comment]
Turns out `feature(specialization)` is used in quite a few rustc crates. @matthewjasper I am not sure what the plan is for those, should they all move to `min_specialization`?

**Comment by matthewjasper** [comment]
They probably should, but I don't know how feasible it is. Once stage0 has `min_specialization` I could see how easy it is to switch.

**Comment by RalfJung** [comment]
> Once stage0 has min_specialization

That shouldn't be too long. :D

I am going to wait for some more feedback on this PR before trying to get the build through.

**Comment by RalfJung** [comment]
This is a rather conflict-heavy PR, would be good if I got quick feedback on this.

**Comment by RalfJung** [comment]
@matthewjasper stage 0 has `min_specialization` now. How do we proceed here? Should I add the `allow(incomplete_features)` for now (do people even want this PR), and you can remove it again when you get to porting those crates?

**Comment by RalfJung** [comment]
Rebased across my other PR which changes the message to include unsoundness.

@matthewjasper should I just add `allow(incomplete_features)` to the remaining rustc crates?

**Comment by matthewjasper** [comment]
Marking as blocked on #72707

**Comment by RalfJung** [comment]
@matthewjasper this is ready for review.

Outside docs and tests, there is exactly one use of full specialization left in the codebase:
```
src/libcore/lib.rs
116:#![feature(specialization)]
```
Is there an issue tracking this?

**Comment by matthewjasper** [comment]
I don't think that there is. The changes to `TrustedRandomAccess` I have are a mess, so I've been putting off opening a PR with them.

@bors r+

**Comment by RalfJung** [comment]
@rust-lang/infra there's not even a build log at https://dev.azure.com/rust-lang/rust/_build/results?buildId=32326&view=logs&j=9121965e-722b-5094-4a33-f061e41958d8&t=64b964f2-043e-5afc-0fc3-c41881c5cd34 ? Is there any way to figure out what went wrong here?

@bors retry

**Comment by pietroalbini** [comment]
> ##[error]We stopped hearing from agent Azure Pipelines 53. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610

I guess the underlying VM crashed. Please ping infra again if it starts to happen consistently.

**Comment by RalfJung** [comment]
Yield.
@bors retry

**Pull request merged**
