### PR TITLE
Move native thread name setting from thread_info to Thread

### LINKED ISSUE #21911: All rust process in `top` are called `<main>`
I think this is fallout of #21678, and it's somewhat unfortunate :(

cc @vojtechkral

### PR DESCRIPTION
**Pull request by vojtechkral**
Fixes #21911

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 45afaac rollup

Thanks!

**Comment by vojtechkral** [comment]
I think bors just doesn't like me...

**Comment by sfackler** [comment]
Needs a rebase

**Comment by vojtechkral** [comment]
Goddamnit. I'm sorry, will fix...

**Pull request merged**
