### PR TITLE
Replace libc::{type} with crate::ffi::{type}

### PR DESCRIPTION
**Pull request by Ayush1325**
Replace libc::{type} imports with crate::ffi::{type} outside of `std::sys` and `std::os`.

Signed-off-by: Ayush Singh <ayushsingh1325@gmail.com>

### CODE REVIEW

**Comment by Ayush1325** [comment]
@joshtriplett is there any interest in merging this, or should I close it?

**Comment by pitaj** [comment]
This PR looks pretty good to me. The T-libs PR backlog is just very long right now.

**Review by ChrisDenton — APPROVED** [review]
Hmm... for areas that don't otherwise need `libc` I think it definitely makes some sense to do this. For other code, I'd be slightly less convinced its worth the churn. But this PR is small and the changes modest so r=me if you rebase.

**Pull request merged**
