### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth 

A few days late, I was on a business trip, sorry.

### CODE REVIEW

**Comment by Manishearth** [comment]
```
clippy/development/lint_passes.html:194: broken link - `clippy/development/define_lints.html`
clippy/print.html:1827: broken link - `clippy/development/define_lints.html`
```

**Comment by flip1995** [comment]
We might want to include `linkchecker` from `rustc` into our CI.

**Pull request merged**
