### PR TITLE
Enable ASLR for windows-gnu

### LINKED ISSUE #16593: use high entropy ASLR on 64-bit Windows
MinGW-w64 doesn't expose the necessary flag yet, so I'll look into adding it to their linker. It should be as easy as adding support for an extra flag there and then passing the switch from the Rust compiler.

### LINKED ISSUE #17684: ASLR on Windows breaks thread-local variables
This appears to be a MinGW-w64 linker bug.

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/16514
Fixes https://github.com/rust-lang/rust/issues/16593
Fixes https://github.com/rust-lang/rust/issues/17684

Passes the tests for me with x86_64 toolchain.

### CODE REVIEW

**Comment by mati865** [comment]
LLD ignores `--high-entropy-va` when linking 32 bit binaries but LD apparently throws the error.

Force pushed to enable high entropy only on 64 bit targets.

**Comment by mati865** [comment]
Looks good but I don't know who would be the right reviewer here.
There are 2 weeks to beta so I think it would be nice if this landed soonish and was reverted for beta so we have more than 6 weeks of testing here.

**Comment by crlf0710** [comment]
Ping from triage, there's merge conflicts now.

**Comment by mati865** [comment]
FWIW [LLD recently enabled ASLR by default](https://reviews.llvm.org/rGe72403f96de7f1c681acd5968f72aa986412dfce) and [Binutils followed](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=514b4e191d5f46de8e142fe216e677a35fa9c4bb).

**Comment by Mark-Simulacrum** [comment]
I am inclined to just land this -- certainly seems like an improvement.

I agree that getting this tested for longer would be good; we can let it land in 1.50 (as opposed to 1.49) for example, though I am likely to forget about this by the time we promote master to beta in ~5 weeks.

@bors r+ rollup=never

**Comment by mati865** [comment]
> I agree that getting this tested for longer would be good; we can let it land in 1.50 (as opposed to 1.49) for example, though I am likely to forget about this by the time we promote master to beta in ~5 weeks.

I'll set up reminder if it lands.

**Pull request merged**
