### PR TITLE
Add unstable VecDeque::rotate_{left|right}

### PR DESCRIPTION
**Pull request by scottmcm**
Like the ones on slices, but more efficient because vecdeque is a circular buffer.

Issue that proposed this: https://github.com/rust-lang/rust/issues/56686

~~:bomb: Please someone look very carefully at the `unsafe` in this!  The `wrap_copy` seems to be exactly what this method needs, and the `len` passed to it is never more than half the length of the deque, but I haven't managed to prove to myself that it's correct :bomb:~~ I think I proved that this code meets the requirement of the unsafe code it's calling; please double-check, of course.

### CODE REVIEW

**Comment by dtolnay** [comment]
This does not hit the #30459 RTL naming issue right?

The implementation looks good to me. r? @alexcrichton for another look at the unsafe code.

r? @alexcrichton

**Comment by scottmcm** [comment]
I believe this doesn't hit the #30459 RTL issue because it's not on text, and thus is like the `rotate_left`/`rotate_right` on integers and slices.

I've pushed a new commit with a claim for why this is safe; please double-check it.

**Comment by ollie27** [comment]
[`VedDeque`](https://doc.rust-lang.org/stable/std/collections/struct.VecDeque.html) is front to back in Rust so for consistency with the rest of the API these methods should be named something like `rotate_forward` or `rotate_to_front`. `VedDeque` has no concept of a left or a right. This is in contrast to Python [`deque`](https://docs.python.org/3.7/library/collections.html?highlight=deque#collections.deque) which does use left to right.

**Comment by alexcrichton** [comment]
I'm not super familiar with the implementation of `VecDeque`, but this seems fine to me to at least land unstable. I'd ideally prefer to see more tests though especially as this has some unsafety, it looks like there's already internal branches but it may not be covered by tests so far? (things like zero len, over half, under half, etc).

It's true that `rotate_left` does match integers, but it seems prudent to try think of names at least which match the front/back naming @ollie27 mentioned that's already with `VecDeque`. Something like `rotate_to_front` and `rotate_to_back` would make sense to me too

**Comment by scottmcm** [comment]
I'll add some more tests.

Since [`[T]::rotate_left`](https://doc.rust-lang.org/std/primitive.slice.html#method.rotate_left) has been stable since 1.26, I think consistency with that is more important than "frontward" names.  See previous discussion of the `rotate`->`rotate_left` rename in https://github.com/rust-lang/rust/issues/41891#issuecomment-313483152

**Comment by CryZe** [comment]
rotate_to_front and rotate_to_back would be ambiguous anyway. The problem here is your viewpoint. Rotating to the back moves all the elements inside the VecDeque from the front to the back, but the ones that fall out of the back get moved to the front. So they traveled from the back to the front, even though the method name suggested we move from the front to the back. That's because rotating from point A to point B on a circle can be done either clockwise or counter clockwise. So from_a_to_b is ambiguous. So the naming would either have to be clockwise / counter_clockwise or left / right to not be ambiguous.

**Comment by alexcrichton** [comment]
Ah if `rotate_{left,right}` are already on slices then makes sense to me to leave the names as-is on `VecDeque`!

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/malept/crypto-hash/issues/6

**Pull request merged**
