### PR TITLE
Remove unused static_assert macro

### PR DESCRIPTION
**Pull request by est31**

### CODE REVIEW

**Comment by RalfJung** [comment]
Makes sense, but we better make sure we can still find this PR when/if we need the macro again.^^

**Comment by est31** [comment]
The macro isn't really that hard to replicate. And given the size of the rustc codebase (0.4 million lines!), if there's any need to use it, it would probably already have been used somewhere, if it were that needed/valuable. `static_assert_size` on the other hand is used 25 times, and `{debug_,}assert!` 1393 times inside `compiler/`.

**Comment by est31** [comment]
Also there are crates now that offer a much larger choice of static assert macros: https://crates.io/crates/static_assertions

**Pull request merged**
