### PR TITLE
rustc_trans: approximate ABI alignment for padding/union fillers.

### LINKED ISSUE #46449: Nightly rust hangs forever
When I tried to use nightly rust to compile my project [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust), it will hang forever.

Stable version works fine.

## Reproduce steps:

```bash
$ git clone https://github.com/shadowsocks/shadowsocks-rust.git
$ cd shadowsocks-rust
$ cargo install -f
  Installing shadowsocks-rust v1.6.10-nightly (file:///Users/zonyitoo/Projects/shadowsocks-rust)
 Downloading openssl v0.9.22
 Downloading serde v1.0.23
 Downloading num-traits v0.1.41
 Downloading openssl-sys v0.9.22
 Downloading foreign-types v0.3.2
 Downloading foreign-types-shared v0.1.1
    Blocking waiting for file lock on memchr-2.0.1.crate
   Compiling typenum v1.9.0
   Compiling unicode-width v0.1.4
   Compiling openssl v0.9.22
   Compiling lazycell v0.5.1
   Compiling strsim v0.6.0
   Compiling num-traits v0.1.41
... (many more logs)
   Compiling env_logger v0.4.3
   Compiling shadowsocks-rust v1.6.10-nightly (file:///Users/zonyitoo/Projects/shadowsocks-rust)
```

It will hang forever, but still consumes CPU.

`ps` shows a `rustc` process:

```plain
zonyitoo         14287  98.3  0.0 25306648   1012 s001  R+   10:36下午  17:20.50 /Users/zonyitoo/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/rustc --crate-name shadowsocks src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg feature="default" --cfg feature="libsodium-ffi" --cfg feature="sodium" -C metadata=fb046a911106e95e -C extra-filename=-fb046a911106e95e --out-dir /Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps -L dependency=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps --extern serde_urlencoded=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libserde_urlencoded-61a60925e70dcbe4.rlib --extern lazy_static=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/liblazy_static-a066899e4d28630a.rlib --extern byteorder=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libbyteorder-1cb3c8ca5707fac7.rlib --extern qrcode=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libqrcode-c4d0865acf488074.rlib --extern tokio_signal=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libtokio_signal-6fa3848f7558b050.rlib --extern url=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/liburl-42ffd8f1fd62548b.rlib --extern futures_cpupool=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libfutures_cpupool-32ced888700d9e3b.rlib --extern scoped_tls=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libscoped_tls-50ac73adf01c31a4.rlib --extern serde_json=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libserde_json-cc1e76046d610c86.rlib --extern openssl=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libopenssl-91c6f1f26b8759c6.rlib --extern subprocess=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libsubprocess-0a3efa9a446563ca.rlib --extern digest=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libdigest-c6d1d61fc5bc9bf0.rlib --extern libsodium_ffi=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/liblibsodium_ffi-f0ea0ac518324990.rlib --extern bytes=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libbytes-54eacfdfc8e87665.rlib --extern ring=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libring-6add70aa26956a4c.rlib --extern typenum=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libtypenum-fdfe19e18f298fbb.rlib --extern time=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libtime-37bf8783b022cc7e.rlib --extern md_5=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libmd_5-f51cf7bee16cb806.rlib --extern libc=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/liblibc-8e42d4cf8815835d.rlib --extern clap=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libclap-2f9d9629604ac78b.rlib --extern env_logger=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libenv_logger-37a09170e3cd67b7.rlib --extern futures=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libfutures-7614b080b7aa6bfa.rlib --extern byte_string=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libbyte_string-8e53eb4422822c2d.rlib --extern rand=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/librand-ba32c60615891fa3.rlib --extern tokio_io=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libtokio_io-0ba48e8839c90dec.rlib --extern log=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/liblog-db3a3cc0c4299968.rlib --extern base64=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libbase64-519a09b2f17b9fbf.rlib --extern tokio_core=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/deps/libtokio_core-c3e74c59a01ac9ad.rlib -L native=/usr/local/Cellar/libsodium/1.0.15/lib -L native=/usr/local/opt/openssl@1.1/lib -L native=/Users/zonyitoo/Projects/shadowsocks-rust/target/release/build/ring-c441a9fe61114cc0/out
```

## Meta
* rustc:
```
rustc 1.24.0-nightly (23032d0af 2017-11-30)
binary: rustc
commit-hash: 23032d0afa2b0e0c60a9b2ae62709f846d90007c
commit-date: 2017-11-30
host: x86_64-apple-darwin
release: 1.24.0-nightly
LLVM version: 4.0
```
* cargo: `cargo 0.24.0-nightly (6529d418d 2017-11-29)`

### PR DESCRIPTION
**Pull request by eddyb**
Before #45225 and after this PR, unions and enums are filled with integers of size and alignment matching their alignment (e.g. `Option<u32>` becomes `[u32; 2]`) instead of mere bytes.
Also, the alignment padding between struct fields gets this treatment after this PR.

Partially helps with some reduced testcases in #46449, although it doesn't solve the bug itself.

### CODE REVIEW

**Comment by arielb1** [comment]
So this needs some tests:
1. a codegen test so we can be aware of our LLVM output - looks important enough
2. perf.rl.o tests for the cases in #46449 - both the case that got faster in beta and the case that got slower in beta.

**Comment by kennytm** [comment]
Perf for the reduced test case added to rust-lang-nursery/rustc-perf#172.

**Comment by kennytm** [comment]
#### Not completely fixed yet.

Manually comparing the build time of the reduced test case (with `futures` dependency) on an ancient `x86_64-unknown-linux-gnu`:

| Size | Stable | Nightly | This PR |
|-----:|-------:|--------:|--------:|
| 1024 | 1.3s | 1.2s | 1.2s |
| 2048 | 1.2s | 1.7s | 1.6s |
| 3072 | 1.2s | 3.4s | 3.9s |
| 4096 | 1.1s | 6.6s | 5.9s |
| 5120 | 1.2s | 12.7s | 10.6s |
| 6144 | 1.2s | 20.1s | 17.6s |

The numbers are better but still exponential.

<details><summary>Meta</summary>

```
$ rustc +stable -vV
rustc 1.22.1 (05e2e1c41 2017-11-22)
binary: rustc
commit-hash: 05e2e1c41414e8fc73d0f267ea8dab1a3eeeaa99
commit-date: 2017-11-22
host: x86_64-unknown-linux-gnu
release: 1.22.1
LLVM version: 4.0

$ rustc +nightly -vV
rustc 1.24.0-nightly (6fa53b00e 2017-12-09)
binary: rustc
commit-hash: 6fa53b00e7450060a3af9b1ef63169db37e589c2
commit-date: 2017-12-09
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0

$ rustc +try-build -vV
rustc 1.24.0-nightly (e714aa603 2017-12-10)
binary: rustc
commit-hash: e714aa603990186aef4f596bca9e7a63c890d6ef
commit-date: 2017-12-10
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

</details>

**Comment by eddyb** [comment]
@kennytm Okay, I can confirm that, I was testing with the reduced testcase, do you happen to have something in between? It's not like there should be any cross-crate effects here.

**Comment by kennytm** [comment]
@eddyb sorry I don’t understand what you do mean by “in between” 😕. I just ran `cargo build +stable --release` and check the time elapsed.

**Comment by eddyb** [comment]
@kennytm I meant reduction-wise. I think I can try myself by adding the code of the test to the futures library and go from there.

**Comment by eddyb** [comment]
@arielb1 I've extended the scope of this PR to interfield padding, and no longer believe it's that relevant to #46449, but because it demonstrates some improvements, I still want to proceed with it.

**Comment by xerofoify** [comment]
if wanted == candidate.align(dl).abi() && wanted == candidate.size().bytes() 
Don't know if this is causing the breakage but if we are swapping them shouldn't it be:
 if wanted == candidate.align(dl).abi() && wanted == candidate.size(d1).bytes().
Aren't we required to have the bytes for both alignment and size equal not just one?

**Comment by eddyb** [comment]
Added a couple more assertions, although I'd be surprised if they fire at all.

**Comment by kennytm** [comment]
@eddyb Do we still need to backport this?

**Comment by eddyb** [comment]
@kennytm It brings us back to the situation before #45225, so LLVM shouldn't behave (much) differently, at least on enums that are optimized the same as they were before.

**Comment by xerofoify** [comment]
if wanted == candidate.align(dl).abi() && wanted == candidate.size().bytes() not having the size stated seems to be very dangerous. Is there a reason for this or was it just missed?

**Comment by eddyb** [comment]
@xerofoify I'm sorry but I don't understand what you mean. The code you quote is in a function that hasn't changed behavior *at all* (was just simplified now that `Integer` got its own `size` & `align` methods).

**Comment by xerofoify** [comment]
If that;s the sense then it's fine. That just seems to be a common mistake I see when refactoring code or fixing a regression. These can cause another regression but if you and I hope state that the refactor is correct it doesn't cause another regression. Not that I don't trust you but it's so common alongside doing double frees on error paths in C/C++ projects I was very skeptical about it.

**Comment by eddyb** [comment]
@xerofoify I *really* don't see what *could possibly* be the problem you're pointing to. The change in that function isn't *meant* to fix anything or modify its behavior, it's *purely* aesthetic.

**Comment by xerofoify** [comment]
Fine then if it's just that it's OK.

**Comment by arielb1** [comment]
I don't think we want to backport this until we find a solution to #46897

**Comment by eddyb** [comment]
@arielb1 But this was supposed to improve performance. If only LLVM didn't care about pointees...

**Comment by alexcrichton** [comment]
Looks like we forgot to backport this for 1.23.0 (sorry about that!) so removing beta tags

**Comment by eddyb** [comment]
@alexcrichton #45225 was backed out from that beta (IIUC) so there wasn't anything to backport.

**Comment by alexcrichton** [comment]
Ah ok, great!

**Pull request merged**
