### PR TITLE
Do not emit note in coerce if loop iterates at least once

### LINKED ISSUE #122561: Invalid note: "the function expects a value to always be returned, but loops might run zero times"
### Code

```Rust
fn is_function_block(cx: &LateContext<'_>, mut expr_hir_id: HirId) -> bool {
    for i in 0.. {
        // We get the parent block.
        if let Some(scope_id) = cx.tcx.hir().get_enclosing_scope(expr_hir_id)
            && let Node::Block(block) = cx.tcx.hir().hir_node(scope_id)
            // We check that there is no statements in the block.
            && block.stmts.is_empty()
            // We check that the return statements is the current expression.
            && let Some(expr) = block.expr
            && expr_hir_id == expr.hir_id
        {
            expr_hir_id = expr.hir_id;
        } else {
            return i != 0;
        }
    }
}
```

### Current output

```Shell
32 |   fn is_function_block(cx: &LateContext<'_>, mut expr_hir_id: HirId) -> bool {
   |                                                                         ---- expected `bool` because of return type
33 | /     for i in 0.. {
34 | |         // We get the parent block.
35 | |         if let Some(scope_id) = cx.tcx.hir().get_enclosing_scope(expr_hir_id)
36 | |             && let Node::Block(block) = cx.tcx.hir().hir_node(scope_id)
...  |
46 | |         }
47 | |     }
   | |_____^ expected `bool`, found `()`
   |
note: the function expects a value to always be returned, but loops might run zero times
  --> clippy_lints/src/transmute/missing_transmute_annotations.rs:33:5
   |
33 |     for i in 0.. {
   |     ^^^^^^^^^^^^ this might have zero elements to iterate on
...
45 |             return i != 0;
   |             ------------- if the loop doesn't execute, this value would never get returned
help: return a value for the case when the loop has zero elements to iterate on
   |
47 ~     }
48 +     /* `bool` value */
   |
help: otherwise consider changing the return type to account for that possibility
   |
32 ~ fn is_function_block(cx: &LateContext<'_>, mut expr_hir_id: HirId) -> Option<bool> {
33 |     for i in 0.. {
 ...
44 |         } else {
45 ~             return Some(i != 0);
46 |         }
47 ~     }
48 +     None
```

### Desired output

```Shell
It should not emit a warning in this case since the range can never not iterate
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.78.0-nightly (7d3702e47 2024-03-06)
binary: rustc
commit-hash: 7d3702e472b99be0f5de6608dd87af1df8f99428
commit-date: 2024-03-06
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gurry**
Fixes #122561

The fix is a bit conservative. It covers only the cases when it is easy to deduce the loop iteration count such as when the expr iterated over is a range or an array literal. It does not cover more involved cases such as when it is a local, a vec or a method call.

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
I don't think we should be suppressing this without replacing it with a better error message and suggestion.

For example, we should explain why Rust doesn't know that `0..10` won't loop at least once, and perhaps we should suggest adding an `unreachable!("...")` after the loop?

**Comment by gurry** [comment]
> I don't think we should be suppressing this without replacing it with a better error message and suggestion.
> 
> For example, we should explain why Rust doesn't know that `0..10` won't loop at least once, and perhaps we should suggest adding an `unreachable!("...")` after the loop?

Agreed. I'll make the changes.

**Comment by gurry** [comment]
Actually, the `for` loop failing to type check has nothing to do with iteration count. All the three functions shown below, for instance, fail with the exact same type mismatch error even though they have different iteration counts - infinite, finite but non-zero and zero:

```rust
fn infinite() -> bool {
   for _i in 0.. {
       return false;
   }
}

fn finite_atleast_once() -> bool {
   for _i in 0..3 {
       return false;
   }
}

fn zero_times() -> bool {
   for _i in 0..0 {
       return false;
   }
}
```
The error actually stems from the `for` loop desugaring. The peculiar structure of the desugaring makes the compiler think we're not returning on all code paths irrespective of iteration count. 

Since the error is unrelated to iteration count, the current note (`the function expects a value to always be returned, but loops might run zero times`) is entirely wrong and misleading. We perhaps need to change it to something that correctly identifies the problem without being too jargon-y for the user.

Thoughts @compiler-errors ?

**Comment by gurry** [comment]
> I will open a different PR with that change and close this one.

Here's the new PR: #123125

**Pull request closed without merging**
