### PR TITLE
fix(libstd/time): fix faulty comment in test

### PR DESCRIPTION
**Pull request by niklasad1**
In addition I removed the loop because it is needed anymore

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm not sure I fully understand this change (or the reasoning behind it) so r? @sfackler

**Comment by niklasad1** [comment]
Ok, I might misunderstood the comment abit but my main point is `Duration::from_secs(u64::max_value() + UNIX_EPOCH` will always panic because `time_t` is either i32 or i64 AFAIK

**Comment by sfackler** [comment]
What does this comment mean for platforms that don't have a time_t?

**Comment by niklasad1** [comment]
Good question, I did my homework poorly!

`cloudabi` represent time as `u64` and `sgx, wasm` as Duration so my comment is invalid and the existing comment is ok

**Pull request closed without merging**
