### PR TITLE
Add example of using the indexing operator to HashMap docs

### LINKED ISSUE #52575: Explicitly callout usage of bracket notation for item access in HashMap docs
Not a huge Rust user, but wasn't aware that square-bracket notation functions for HashMaps. I see now that it's due to operator overloading via the Index interface, but newcomers to the language aren't going to be familiar with that.

Probably worth making it obvious that it's doable in the HashMap documentation? https://doc.rust-lang.org/std/collections/struct.HashMap.html#examples-16 is currently the only place it shows up

### PR DESCRIPTION
**Pull request by fhartwig**
Fixes #52575

### CODE REVIEW

**Review by frewsxcv — COMMENTED** [review]
can you also add the same line to the `BTreeMap` docs? https://doc.rust-lang.org/std/collections/struct.BTreeMap.html

**Comment by TimNN** [comment]
Ping from triage @fhartwig: it looks like some changes have been requested to this PR.

**Comment by TimNN** [comment]
Ping from triage @fhartwig: It looks like your PR needs to be updated.

**Comment by frewsxcv** [comment]
I just pushed a commit w/ my suggestion, hope that's okay @fhartwig! Thanks for your contribution!

@bors r+ rollup

**Pull request merged**
