### PR TITLE
Preliminary work for incremental ThinLTO (CGU name edition)

### PR DESCRIPTION
**Pull request by michaelwoerister**
Bring back the first half of #52266 but hopefully without the performance regression.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@rust-timer build 51257c83d48484cb4a881bbc9a3c0cb0518f3301

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, it seems that commits get pushed to the front of the queue as fast as perf.rlo can benchmark them, so f45f52532a394d2d607fc5693364ad820049376d (the baseline of the try-build) won't be tested until bors runs into trouble and doesn't merge things for a while `:)` Can we do something about this?

**Comment by Mark-Simulacrum** [comment]
I've wanted to prioritize parent commits for a while, but haven't had a chance to do the legwork quite yet. Can you open an issue?

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum: https://github.com/rust-lang-nursery/rustc-perf/issues/271

**Comment by michaelwoerister** [comment]
OK, with the caching added, this seems like an overall improvement in compile times.

Maybe r? @alexcrichton, who already reviewed the previous version of this PR? The first three commits did not change wrt to #52266. The last one is the same as https://github.com/rust-lang/rust/pull/52266/commits/f6894ebe664d111259a91a2b5fcc1236ca413436, plus some caching for CGU name generation added.

There's nothing actually *directly* related to incremental ThinLTO in this PR.

**Comment by kennytm** [comment]
@bors retry [GitHub archive issue](https://status.github.com/messages).

> 10:48 HKT — We're currently experiencing elevated failure rates downloading repository archives.

**Comment by cramertj** [comment]
@michaelwoerister After this PR, I'm unable to link Fuchsia binaries. The error I get is [here](https://gist.github.com/cramertj/1d77970a88feb5871efce61bb88747fa). Any idea what might have caused this?

**Comment by michaelwoerister** [comment]
Interesting. The PR does change the names of object files when doing ThinLTO, but that shouldn't be a problem. Can you open issue? We should investigate further.

**Comment by cramertj** [comment]
@michaelwoerister Opened https://github.com/rust-lang/rust/issues/53794

**Comment by michaelwoerister** [comment]
:+1:

**Pull request merged**
