### PR TITLE
Make use of Travis's conditional jobs.

### PR DESCRIPTION
**Pull request by kennytm**
Conditional jobs: https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Jobs.

Jobs not matching the condition will not be scheduled at all. This allows us to get rid of `$ALLOW_PR`/`$ALLOW_TRY`/`$SKIP_BUILD` in `.travis.yml`, and perfectly prevent spurious PR failures due to flaky macOS machines.

### CODE REVIEW

**Comment by kennytm** [comment]
@bors try

Let me verify if the try build works before merging.

**Comment by kennytm** [comment]
OK try build works. The remaining thing is to ensure all 41 jobs are running during the actual test.

**Comment by Mark-Simulacrum** [comment]
r? @alexcrichton 

r=me, but I want to run this past you as well.

cc @rust-lang/infra as well.

**Comment by TimNN** [comment]
@kennytm:

> EDIT: Not sure if relevant, but the try build failed to download the cache archive. Maybe just due to removing the ALLOW_TRY=1/ALLOW_PR=1 from env.

That seems to be the case, see https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

**Comment by alexcrichton** [comment]
@bors: r+

Nice find!

**Pull request merged**
