### PR TITLE
Don't allocate `&str`s in driver on error.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
...why is this function marked `#[inline]`? It's called *at most* once per compilation, right?

**Comment by frewsxcv** [comment]
> ...why is this function marked #[inline]?

Not sure. Want me to change that as well?

**Comment by jonas-schievink** [comment]
Sure, if you want to.

Oh, and it looks like highfive didn't assign anyone to this PR.

**Comment by frewsxcv** [comment]
Changes have been made.

**Pull request closed without merging**
