### PR TITLE
Forbid non-`structural_match` types in const generics

### LINKED ISSUE #60286: Only permit `structural_match` types as const generic types
This should also allow us to clean up the implementation of https://github.com/rust-lang/rust/pull/60284.

### PR DESCRIPTION
**Pull request by varkor**
Fixes https://github.com/rust-lang/rust/issues/60286.

### CODE REVIEW

**Comment by petrochenkov** [comment]
IIRC, resolve had some hack making sure that generic parameters cannot be used in const generics.
It should be possible to remove it now because generic parameters are not `structural_match`.

**Comment by varkor** [comment]
@petrochenkov: just remembered this too — working on that now.

**Comment by Centril** [comment]
Shouldn't this use the mechanism in https://github.com/rust-lang/rust/pull/65519?

**Comment by Centril** [comment]
(cc @pnkfelix)

**Comment by varkor** [comment]
@Centril: this is compatible with that PR (up to rebasing).

**Comment by varkor** [comment]
@petrochenkov: I've removed the hack from resolve.

**Pull request merged**
