### PR TITLE
Untangle ZST validation from integer validation and generalize it to all zsts

### PR DESCRIPTION
**Pull request by oli-obk**
cc @RalfJung 

r? @wesleywiser

### CODE REVIEW

**Comment by wesleywiser** [comment]
Could you add some tests to https://github.com/rust-lang/rust/blob/8a87b945b27b5670ac5ed665bbb0fccc1b88a0a0/src/test/ui/consts/huge-values.rs for ZSTs that should trigger the new logic?

**Review by RalfJung — APPROVED** [review]
LGTM. Do we have a test making sure that a non-empty `&[!]` is an error?

**Comment by oli-obk** [comment]
> Do we have a test making sure that a non-empty &[!] is an error?

We do now

> Could you add some tests 

Done

**Review by RalfJung — APPROVED** [review]
r=me

**Pull request merged**
