### PR TITLE
cleanup: replace `as[_mut]_slice()` calls with deref coercions/slicing syntax

### PR DESCRIPTION
**Pull request by japaric**
r? @alexcrichton 
cc @eddyb

### CODE REVIEW

**Comment by gkoz** [comment]
In some cases `x.as_slice()` is replaced with `&x` and in others with `&x[]`. is that supposed to be so? It seemed to me that the latter syntax is redundant.

**Comment by bluss** [comment]
FYI &expr[] will be deprecated soon, after `..` is added and &expr[..] is the new way (or using deref coercions). See #21879

**Comment by japaric** [comment]
@gkoz you can't use deref coercions everywhere, one example is passing `&Vec<T>` where `U: Bound` is expected even if `&[T]` implements `Bound`. It also doesn't work with `match &x` when the patterns are string literals or slice patterns.

@bluss I have used deref coercions wherever it was possible, and used slicing syntax where it was not. I can change the `&x[]`s back to `as_slice()`s, if that helps you with the new `..` syntax. I count 127 occurrences in my patch, but I bet there hundreds more in the repo :P.

Alternatively, I could change the `&x[]` to `&*x`. (FWIW, I personally prefer `&*x` over `&x[..]`, but for some reason other rust devs find `&**x` unsightly)

**Comment by alexcrichton** [comment]
I'd be fine switching to `&*x` in the meantime to prevent churn when switching to `[..]`.

**Comment by alexcrichton** [comment]
Ah also, basically r=me when tests are passing, this is one beautiful patch :)

**Comment by eddyb** [comment]
@japaric maybe type ascription will solve that problem - seeing a type, even something "skeletal" like `&[_]`, seems more helpful IMO than `as_slice` or other *actions*.

**Pull request merged**
