### PR TITLE
Add existential type syntax

### PR DESCRIPTION
**Pull request by oli-obk**
This just adds the syntax. There's no logic behind it except for the feature gating.

tracking issue: #34511 
rfc: https://github.com/rust-lang/rfcs/blob/master/text/2071-impl-trait-type-alias.md

r? @pnkfelix

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @nikomatsakis

**Comment by pietroalbini** [comment]
Ping from triage @pnkfelix! This PR needs your review.
@oli-obk there are failing tests and merge conflicts.

**Comment by pietroalbini** [comment]
Ping from triage @pnkfelix! This PR needs your review.
@oli-obk there are failing tests and merge conflicts.

**Comment by pietroalbini** [comment]
Ping from triage! This PR needs a review, can @pnkfelix or someone else from @rust-lang/compiler review this?

**Comment by oli-obk** [comment]
I'll close for now, this might take another two or three weeks

**Pull request closed without merging**
