### PR TITLE
Two lexer tweaks

### PR DESCRIPTION
**Pull request by nnethercote**
19 days later, I haven't received a review of my commits in #36470. In an attempt to make some progress, I'm going to split up the changes. Here are the ones that don't relate to renaming things.

### CODE REVIEW

**Comment by nagisa** [comment]
This seems good to me.

**Comment by nrc** [comment]
#36470 has been r+'ed now, so I think this PR can be closed (it will have to go through the slightly longer syntax-breaking-change landing process though). We could land this PR directly since it does not change any API, but that would mean rebasing #36470. @nnethercote do you have a preference?

**Comment by nnethercote** [comment]
@nrc: At this point I'd prefer to land this and then rebase/redo #36470, because I want to change how things are done in #36470 And it's good to separate the non-breaking changes from the breaking changes.

**Pull request merged**
