### PR TITLE
mk: Prepare for a new stage0 compiler

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit prepares the source for a new stage0 compiler, the 1.10.0 beta
compiler. These artifacts are hot off the bots and should be ready to go.

### CODE REVIEW

**Comment by Manishearth** [comment]
Travis fails

**Comment by eddyb** [comment]
@alexcrichton This failure happened early enough to overlap with the `clean` step on other bots and this one left (at least) `auto-linux-64-opt-rustbuild` broken: http://buildbot.rust-lang.org/builders/auto-linux-64-opt-rustbuild/builds/1239/steps/clean/logs/stdio.
All of the `clean` steps on `auto-linux-64-opt-rustbuild` after that have been like this: http://buildbot.rust-lang.org/builders/auto-linux-64-opt-rustbuild/builds/1240/steps/clean/logs/stdio.

Looks like a very unlikely situation, but one we shouldn't miserably break on.

**Comment by eddyb** [comment]
@alexcrichton Looks like it fixed itself? Is it possible that bors went through the whole queue so fast that a single stale process was responsible for breaking `clean` on all of those attempts?

**Comment by alexcrichton** [comment]
@eddyb yeah I'm not really sure what happened, I'll try to investigate and see what went wrong.

**Comment by alexcrichton** [comment]
Ok, I fixed a bug where the snapshot download script didn't actually download the snapshot by accident. If this bounces we'll continue to see breakage, but hopefully we can smooth it out relatively quickly.

I think there are some more bugs, though, so I will keep combing logs.

@bors: r=nikomatsakis

**Comment by alexcrichton** [comment]
@bors: p=1

Just wanna try to get this landed while I'm here to watch the queue

**Comment by alexcrichton** [comment]
@bors: retry

* buildbot configuration bug

**Pull request merged**
