### PR TITLE
Port the `sysroot-crates-are-unstable` Python script to rmake

### PR DESCRIPTION
**Pull request by Zalathar**
New version of #126231, and a follow-up to #129071.

One major difference is that the new version no longer tries to report *all* accidentally-stable crates, because the `run_make_support` helpers tend to halt the test as soon as something goes wrong. That's unfortunate, but I think it won't matter much in practice, and preserving the old behaviour doesn't seem worth the extra effort.

---

Part of #110479 (Python purge), with this being one of the non-trivial Python scripts that actually seems feasible and worthwhile to remove.

This is *not* part of #121876 (Makefile purge), because the underlying test is already using rmake; this PR just modifies the existing rmake recipe to do all the work itself instead of delegating to Python. So there's no particular urgency here.

r? @jieyouxu 

try-job: aarch64-gnu
try-job: aarch64-apple
try-job: test-various
try-job: armhf-gnu
try-job: x86_64-msvc
try-job: i686-mingw

### CODE REVIEW

**Comment by Zalathar** [comment]
Updated: `env_var("TARGET")` → `target()` [(diff)](https://github.com/rust-lang/rust/compare/e24f62231ab2c7539b4de85b449cf9e9135339ea..8b990e35f423907d22cb7f386d40acc1599377ad)

**Review by jieyouxu — APPROVED** [review]
Thanks, this looks good, I'll run a couple of try-jobs for sanity checks before sending this off to full CI.

**Comment by jieyouxu** [comment]
Feel free to r=me if the try jobs come back green.

@bors delegate+ rollup=iffy (sysroot checks)

**Comment by Zalathar** [comment]
Try is green.

@bors r=jieyouxu

**Pull request merged**
