### PR TITLE
Do not suggest using a const parameter when there are bounds on an unused type parameter

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
The user wrote the bound, so it's obvious they want a type.

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
Looks like `hir::GenericParam::bounds` does not include bounds from `where` clauses. How can check for them too? I can use `GenericPredicates` but I don't know how to differentiate implicit bounds from explicit bounds.

**Comment by michaelwoerister** [comment]
Thanks for the PR, @ChayimFriedman2! Maybe someone from the diagnostics working group can help you.

r? rust-lang/diagnostics

**Comment by davidtwco** [comment]
> Looks like `hir::GenericParam::bounds` does not include bounds from `where` clauses. How can check for them too? I can use `GenericPredicates` but I don't know how to differentiate implicit bounds from explicit bounds.

You might be able to use [`explicit_predicates_of`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.explicit_predicates_of) (it's been a while but I think this includes all predicates from the user but none of the implicit ones).

**Comment by ChayimFriedman2** [comment]
Unfortunately, `explicit_bounds_of()` includes the implicit `: Sized` predicate:

https://github.com/rust-lang/rust/blob/450ef8613ce80278b98e1b1a73448ea810322567/compiler/rustc_typeck/src/collect.rs#L2179-L2185

I ended with rather ugly (IMHO) code that lazily lowers the types in the `where` clause (because there is no easy way to tell if a type is a generic parameter using HIR types). I'm not sure this is a good idea, but I don't have a better one. Do you have a better idea? Or do you think there is no reason to do it lazily?

**Review by davidtwco — APPROVED** [review]
I think this looks reasonable but I'm not familiar enough with typeck to know for sure, will reassign.

**Pull request merged**
