### PR TITLE
Use SliceIndex for str's Index/IndexMut impls

### LINKED ISSUE #55603: Implement `Index` for `SliceIndex` types for `str`
While writing a generic implementation today, I was surprised that you can't do `s[i]` for `i: SliceIndex<S>`, if `s` is of slice type `&S`. Doing `s.get(i).unwrap()` is an easy enough workaround, but feels really bad. Replacing the various explicit impls with one for `SliceIndex` would feel much nicer.

### PR DESCRIPTION
**Pull request by sfackler**
This was missed by accident when the initial implementation landed!

Closes #55603

### CODE REVIEW

**Comment by sfackler** [comment]
This did expose an issue with the on unimplemented message we have on SliceIndex: https://github.com/rust-lang/rust/blob/master/src/libcore/slice/mod.rs#L2372.

Specifically, strings can't be indexed, just subsliced. This was already a problem since str::get uses SliceIndex currently. Is there better phrasing we can use there, or should we just get rid of the attribute?

**Comment by alexcrichton** [comment]
@craterbot run start=master#e6c5cf923489f4aed6c9e36a170fab9b6179d8da end=try#32bb15d09bdec52daf41ad57d2d6c192d7c7a4e9 mode=check-only

**Comment by alexcrichton** [comment]
An impressive zero actual regressions! R=me with passing travis

**Comment by sfackler** [comment]
I went ahead and just removed the custom on_unimplemented attribute for now :(

**Comment by Mark-Simulacrum** [comment]
@sfackler Looks like CI here is failing, can you take a look?

**Comment by TimNN** [comment]
Ping from triage @sfackler: It looks like your PR is failing on travis.

**Comment by TimNN** [comment]
Ping from triage @sfackler !

**Comment by TimNN** [comment]
Ping from triage @sfackler: It looks like this PR hasn't received any updates in a while, so I'm closing it per [out guidelines](https://forge.rust-lang.org/triage-procedure.html). Thank you for your contributions and please feel free to re-open in the future.

**Pull request closed without merging**
