### PR TITLE
Optimize try_mark_green and eliminate the lock on dep node colors

### PR DESCRIPTION
**Pull request by Zoxc**
Blocked on https://github.com/rust-lang/rust/pull/56614

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Nice `:)` This is something I wanted to try out for a while. (I haven't looked at the specific implementation here yet though).

@rust-timer build 2897f68c5b419b38ac5e1a32910abe9112ea8a3c

**Comment by Zoxc** [comment]
@rust-timer build 2897f68c5b419b38ac5e1a32910abe9112ea8a3c

**Comment by michaelwoerister** [comment]
This is another case where measuring with parallel queries would be useful...

**Comment by michaelwoerister** [comment]
I know but that lock can only be really expensive with parallel queries because of contention, right?

**Review by michaelwoerister — COMMENTED** [review]
It would have been nice to have a performance comparison for the multi-threaded case but that's complicated and not really worth the effort. The changes already show a small win in single-threaded mode and it can only improve the situation with parallel queries, so let's go ahead and merge.

r=me with the nits addressed.

Great work, @Zoxc!

**Pull request merged**
