### PR TITLE
try to fix lvalue ops for real

### LINKED ISSUE #41726: nightly only: internal compiler error: broken MIR (Terminator ..
This (probably incorrect) program causes nightly rustc to panic:

```rust
use std::collections::HashMap;
fn main() {
    let things: HashMap<String, Vec<String>> = HashMap::new();
    for src in things.keys() {
        things[src.as_str()].sort();
    }
}
```

```
% RUST_BACKTRACE=1 rustc ice.rs
error: internal compiler error: broken MIR (Terminator { source_info: SourceInfo { span: ice.rs:5:9: 5:29, scope: scope4 }, kind: _17 = const std::ops::Index::index(_18, _19) -> [return: bb11, unwind: bb3] }): bad arg #0 (&std::collections::HashMap<std::string::String, std::vec::Vec<std::string::String>> <- &mut std::collections::HashMap<std::string::String, std::vec::Vec<std::string::String>>): Mutability
 --> ice.rs:5:28
  |
5 |         things[src.as_str()].sort();
  |                            ^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:376
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::span_bug
   7: rustc_mir::transform::type_check::TypeChecker::check_terminator
   8: rustc::infer::InferCtxtBuilder::enter
   9: <rustc_mir::transform::type_check::TypeckMir as rustc::mir::transform::MirPass<'tcx>>::run_pass
  10: <T as rustc::mir::transform::MirMapPass<'tcx>>::run_pass
  11: rustc::mir::transform::Passes::run_passes
  12: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::{{closure}}
  13: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  14: rustc_driver::driver::phase_3_run_analysis_passes
  15: rustc_driver::driver::compile_input
  16: rustc_driver::run_compiler
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  19: <F as alloc::boxed::FnBox<A>>::call_box
  20: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:658
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  21: start_thread
  22: __clone
```

```
% rustc --version --verbose
rustc 1.19.0-nightly (6a5fc9eec 2017-05-02)
binary: rustc
commit-hash: 6a5fc9eecec235312755e737fb5b984abe537f2e
commit-date: 2017-05-02
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```

On the beta, instead you get:
```
error: cannot borrow immutable indexed content as mutable
 --> ice.rs:5:9
  |
5 |         things[src.as_str()].sort();
  |         ^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable

error: aborting due to previous error

 rustc 1.18.0-beta.1 (4dce67253 2017-04-25)
```

### LINKED ISSUE #41742: ICE (re-trying op failed) when trying to use IndexMut with wrong index type
(Found while trying to reduce #41726, but I guess it is a different bug)

```rust
use std::ops::{Index, IndexMut};

struct S;
struct H;

impl S {
    fn f(&mut self) {}
}

impl Index<u32> for H {
    type Output = S;
    fn index(&self, index: u32) -> &S {
        unimplemented!()
    }
}

impl IndexMut<u32> for H {
    fn index_mut(&mut self, index: u32) -> &mut S {
        unimplemented!()
    }
}

fn main() {
    H["?"].f();
}
```

Error in nightly:

```rust
$ RUST_BACKTRACE=full rustc 1.rs
error[E0308]: mismatched types
  --> 1.rs:24:7
   |
24 |     H["?"].f();
   |       ^^^ expected u32, found reference
   |
   = note: expected type `u32`
              found type `&'static str`

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 're-trying op failed', src/libcore/option.rs:794
stack backtrace:
<snip>
   8:        0x10b01e97d - core::option::expect_failed::hf6ddaca0707dee4e
   9:        0x105eb9076 - rustc_typeck::check::method::confirm::ConfirmContext::convert_lvalue_op_to_mutable::h0a19643fe67bd473
  10:        0x105eb8024 - rustc_typeck::check::method::confirm::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::confirm_method::h9b8161ac9ec72016
  11:        0x105ecc2c7 - rustc_typeck::check::method::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::lookup_method::h56ef9ae2ed618970
  12:        0x105f0c021 - rustc_typeck::check::FnCtxt::check_expr_kind::ha9d720cdd9d40244
  13:        0x105f0b0f1 - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h4f8d554dc5adc888
  14:        0x105f16456 - rustc_typeck::check::FnCtxt::check_stmt::h1e4e8f5a38945d3e
  15:        0x105f16d9e - rustc_typeck::check::FnCtxt::check_block_with_expected::{{closure}}::h6f559beafce939e1
  16:        0x105f16801 - rustc_typeck::check::FnCtxt::check_block_with_expected::h84f076beaa14901c
  17:        0x105f0bd6a - rustc_typeck::check::FnCtxt::check_expr_kind::ha9d720cdd9d40244
  18:        0x105f0b0f1 - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h4f8d554dc5adc888
  19:        0x105f0771d - rustc_typeck::check::FnCtxt::check_return_expr::h66476709e0aa025f
  20:        0x105ef9187 - rustc_typeck::check::check_fn::hb2223142c4611e49
  21:        0x105ef7a88 - rustc_typeck::check::typeck_tables_of::h785f93dd2c741a2a
  22:        0x106f0dc45 - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get::hb0a5c702c688f9b2
  23:        0x106f252da - rustc::ty::maps::TyCtxtAt::typeck_tables_of::h7ee387f800510609
  24:        0x106f2246e - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of::h5646cf71d082673b
  25:        0x105ef688f - rustc_typeck::check::typeck_item_bodies::h1eba66163e21279e
  26:        0x106f0cdc9 - rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get::h5bf6b361e42fe78d
  27:        0x106f25166 - rustc::ty::maps::TyCtxtAt::typeck_item_bodies::hc87e6dcd01e3f40e
  28:        0x106f22432 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies::h7c99318169c1ed83
  29:        0x105f4f56e - rustc_typeck::check_crate::h137c39114e0bfc61
<snip>
```

```sh
$ rustc -vV
rustc 1.19.0-nightly (2d4ed8e0c 2017-05-03)
binary: rustc
commit-hash: 2d4ed8e0cbe2c5f3763273a5d8f6b15119473ba7
commit-date: 2017-05-03
host: x86_64-apple-darwin
release: 1.19.0-nightly
LLVM version: 4.0
```

------

Additionally, on stable 1.17.0 and beta 1.18.0-beta.1 this program prints the error E0308 twice,

```rust
error[E0308]: mismatched types
  --> 1.rs:24:7
   |
24 |     H["?"].f();
   |       ^^^ expected u32, found reference
   |
   = note: expected type `u32`
              found type `&'static str`

error[E0308]: mismatched types
  --> 1.rs:24:7
   |
24 |     H["?"].f();
   |       ^^^ expected u32, found reference
   |
   = note: expected type `u32`
              found type `&'static str`

error: aborting due to 2 previous errors
```

### LINKED ISSUE #41774: Borrow Checker allowing mutable and immutable reference out on a vec [Nightly]
When using array indexing, the borrow checking is allowing for both an immutable and mutable reference to be taken out on a vec.

Playground: https://play.rust-lang.org/?gist=558d7e98834c5e269eed35b335823220&version=nightly&backtrace=0

Version: rustc 1.19.0-nightly (59f1a2f94 2017-05-04)

Offending Code:
```
#[derive(Debug)]
struct Data {
    x: i32,
    y: i32,
}

impl Data {
    fn add(&mut self, other: &Data) -> &mut Data {
        self.x += other.x;
        self.y += other.y;
        return self;
    }
}

fn main() {
    let mut v = vec![
        Data{x: 0, y: 1},
        Data{x: 2, y: 3},
        Data{x: 4, y: 5},
    ];
    v[0].add(v[1].add(&v[2]));

    println!("{:?}", v);
}
```
Expected Result:
```
error[E0499]: cannot borrow `v` as mutable more than once at a time
  --> <anon>:21:14
   |
21 |     v[0].add(v[1].add(&v[2]));
   |     -        ^              - first borrow ends here
   |     |        |
   |     |        second mutable borrow occurs here
   |     first mutable borrow occurs here

error[E0502]: cannot borrow `v` as immutable because it is also borrowed as mutable
  --> <anon>:21:24
   |
21 |     v[0].add(v[1].add(&v[2]));
   |     -                  ^    - mutable borrow ends here
   |     |                  |
   |     |                  immutable borrow occurs here
   |     mutable borrow occurs here
```
Actual Result:
`[Data { x: 6, y: 9 }, Data { x: 6, y: 8 }, Data { x: 4, y: 5 }]`

### PR DESCRIPTION
**Pull request by arielb1**
Hopefully this is the last PR needed.

Fixes #41726.
Fixes #41742.
Fixes #41774.

### CODE REVIEW

**Comment by arielb1** [comment]
Beta-nominating because this fixes regression introduces in #41578 which is going into beta.

**Comment by nikomatsakis** [comment]
Accepting for beta. Small-ish patch, serious soundness regressions.

cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
Backport in https://github.com/rust-lang/rust/pull/42053

**Comment by brson** [comment]
Looks like this has been backported. Removed the nominated tag.

**Pull request merged**
