### PR TITLE
Apply resource-suffix to search-index and source-files scripts as well

### LINKED ISSUE #59771: --resource-suffix option isn't applied to search-index.js

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #59771.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
If you're changing the filename of `source-files.js`, make sure it's being linked correctly - IIRC the way it's included as an `extra_file` in the layout doesn't automatically add the resource suffix.

Moreover, i feel like this changes the meaning of the resource suffix a little. So far, there's been a bit of a separation between files that received the resource suffix, and those that didn't. As far as i know, the distinction was that "static" files that didn't change when run on a different crate (`rustdoc.css`, `main.js`, the theme CSS files, etc) got the suffix, but files that were generated with information that depended on the crate (`search-index.js`, `aliases.js`, `source-files.js`, etc) did not. Starting with this PR, we'll start adding the resource suffix to crate-specific files, that aren't also affected by `--static-root-path`.

It's worth noting why this PR was called for. Docs.rs has been having issues recently with the CDN caching files like the search index on URLs like `docs.rs/tokio/*/tokio/search-index.js`, and serving it even when the underlying file has changed. This was proposed as a solution to make the page reference a different URL, which would cause the CDN to cache a different file.

(Though, while typing this up, i also realized that a docs.rs-side solution that would also solve that problem is to always redirect non-exact versions to the latest version before serving the file. This would solve the issue by always serving the right version of the crate in the URL, thus never having the problem of *which* `search-index.js` is being served from the URL change over time. I'm leaning toward that solution instead of changing what files we add the resource suffix to, TBH.)

**Comment by GuillaumeGomez** [comment]
As far as I can tell, the links are done correctly. Only `source-files.js` has a "special" way to be generated through layout and this has been updated as well. Do you see anything else that might require changes?

**Comment by QuietMisdreavus** [comment]
Oh, i totally missed the part that added the resource suffix to the layout call.

The only other thing i would add is to do the same to `alises.js`, since it can have the same issue. Otherwise, this looks fine. Based on https://github.com/rust-lang/docs.rs/issues/316#issuecomment-482274857 i want to have this in anyway, since it will fix a specific problem that the "docs.rs-side solution" would not.

**Comment by GuillaumeGomez** [comment]
I added it for `aliases.js` as well.

**Review by QuietMisdreavus — APPROVED** [review]
Looks good, thanks so much! r=me when travis is green.

**Pull request merged**
