### PR TITLE
Fixed the link to the ? operator

### PR DESCRIPTION
**Pull request by JosephTLyons**
I'm working on updating all broken links, but figured I'd break up the pull requests so they are easier to review, versus just one big pull request.

### CODE REVIEW

**Comment by wesleywiser** [comment]
Thanks!

@bors r+ rollup

**Comment by JosephTLyons** [comment]
Not quite sure what this means.  Is it because the fork that this PR came from is now outdated?

**Comment by pietroalbini** [comment]
@bors retry

Nah, it's a really big infra failure, don't know what caused it yet.

**Pull request merged**
