### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #83507 (Implement RFC 2951: Native link modifiers)
 - #84328 (Stablize {HashMap,BTreeMap}::into_{keys,values})
 - #84712 (Simplify chdir implementation and minimize unsafe block)
 - #84851 (:arrow_up: rust-analyzer)
 - #84923 (Only compute Obligation `cache_key` once  in `register_obligation_at`)
 - #84945 (E0583: Include secondary path in error message)
 - #84949 (Fix typo in `MaybeUninit::array_assume_init` safety comment)
 - #84950 (Revert PR 83866)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=83507,84328,84712,84851,84923,84945,84949,84950)

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@bors r+ rollup=never p=5 

(created a partially-disjoint rollup so we can get the queue moving while I triage the earlier rollup later )

**Comment by klensy** [comment]
https://github.com/rust-lang-ci/rust/actions/runs/817115841

>auto (dist-aarch64-apple, ./x.py dist --stage 2, --build=x86_64-apple-darwin --host=aarch64-apple...
GitHub Actions has encountered an internal error when running your job.

**Pull request merged**
