### PR TITLE
BufRead::{split,lines}: don't eat trailing delimiters

### LINKED ISSUE #109907: BufRead::split eats last separator
I tried this code:

```rust
    let data = b"\nempty line:\n\ntrailing newline\n";
    let buf = BufReader::new(data.as_slice());
    let lines: Vec<_> = buf.split(b'\n').map(Result::unwrap).collect();
```

I expected to see this happen: each empty line in `data` corresponds to an empty element in `lines`: `lines == [b"", b"empty line:", b"", b"trailing newline", b""]`

Instead, this happened: the trailing newline is eaten: `lines == [b"", b"empty line:", b"", b"trailing newline"]`

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=04c3b5f7020f0abc7a802400127ba70a

This is quite annoying because this makes split an irreversible operation: information is lost and it is not possible to recover the content of the original buffer from its split content.

### Meta
Happens with stable and nightly on the playground, as well as my distro package (1.64):

`rustc --version --verbose`:
```
rustc 1.64.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6

```

### PR DESCRIPTION
**Pull request by symphorien**
this aligns behavior on &str::split

Fixes https://github.com/rust-lang/rust/issues/109907 and a similar issue with BufRead::lines.

### CODE REVIEW

**Comment by symphorien** [comment]
I have a hard time understanding the CI failure. Is it an unrelated failure?

**Comment by klensy** [comment]
> I have a hard time understanding the CI failure. Is it an unrelated failure?

You're changed behavior of stable feature, so now it's differs and broken code all around, no?

**Comment by jyn514** [comment]
I'm going to close this; at a minimum, breaking changes like this must be done across an edition, but even then you have to make a strong case that the new behavior is worth the breakage. We certainly can't just change it without warning.

**Comment by symphorien** [comment]
what do you think would be an acceptable course of action, then?

**Comment by jyn514** [comment]
See https://rust-lang.zulipchat.com/#narrow/stream/268952-edition-2021/topic/2024.20wishlist.3F for a list of changes in 2024, you can suggest this change there. See https://blog.rust-lang.org/2021/05/11/edition-2021.html for more background on editions in general.

**Pull request closed without merging**
