### PR TITLE
MultipleReturnTerminators + SingleReturnTerminator

### PR DESCRIPTION
**Pull request by saethlin**
`MultipleReturnTerminators` was added with the thinking that we would do better MIR optimizations with that form. But LLVM does better when there is a single return terminator. So adding a new pass which turns back into the single terminator form should give us the best of both worlds.

Locally, it looks like this change just rearranges/renames some things. If this doesn't look like an improvement in perf, I'm going to suggest that we remove `MultipleReturnTerminators`.

### CODE REVIEW

**Comment by saethlin** [comment]
Ah crap sorry I forgot to ask for review from ghost

@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Can the SingleReturnTerminator be done on-the-fly during codegen?
MultipleReturnTerminator can have a secondary effect of shrinking MIR, which makes encoding/decoding faster.
Having SingleReturnTerminator before encoding nullifies this second effect.

**Comment by saethlin** [comment]
I diffed the MIR for a number of crates in html5ever's dependency tree. It looks like a few of them end up with a lot of repeated return-only blocks with this pass, and actually compile to _more_ MIR with this pass. I think this happens because we propagate backwards into blocks which have all their statements eliminated. Normally, those would be cleaned up by SimplifyCfg because they are a goto chain, but now they aren't.

I'm also aware that generally, DeduplicateBlocks deletes a lot of duplicate unreachable blocks. So it might make sense to turn on the pass generally, in combination with MultipleReturnTerminators. If the perf here seems troublesome, I'll see if I can add something to SimplifyCfg to do the cleanup. That might be a bit more surgical.

**Comment by saethlin** [comment]
@rust-timer queue

**Comment by saethlin** [comment]
@rust-timer build cdbe287ec197b4df04fec87680c5779610f69a85

**Comment by Nilstrieb** [comment]
Marking as waiting on author given that it's a draft and has conflicts.

**Comment by saethlin** [comment]
The theoretical benefit of this pass is that it could reduce the size of our MIR. But based on the experimentation in this PR, it looks like this pass has a very marginal impact on the amount of MIR we produce. In addition, it looks to me like encoding/decoding MIR isn't a large enough fraction of our compile time to be concerned about marginal tweaks like this.

**Pull request closed without merging**
