### PR TITLE
Fixed #17823. Changed tests to work with fix.

### LINKED ISSUE #17823: Get rid of redundancy in type errors
```
error: mismatched types: expected `uint`, found `int` (expected uint, found int)  
```

I guess the parenthetical tells you about the outermost type constructors of the mismatch, e.g. "expected uint, found &-ptr". But in many cases it's redundant.  We should get rid of the parenthetical in cases where it's useless, and then add some explanatory text about what it's trying to tell you.

### PR DESCRIPTION
**Pull request by KalitaAlexey**

### CODE REVIEW

**Comment by nrc** [comment]
Could you amend the commit to give it a more descriptive name please?

**Comment by nrc** [comment]
r+ with a better commit message

**Comment by KalitaAlexey** [comment]
Which message do you want? I just think that current message is good.

**Comment by KalitaAlexey** [comment]
r+ simplify E0308 message for primitive types

**Comment by nrc** [comment]
"Changed tests to work with fix." doesn't really describe the commit. I like "simplify E0308 message for primitive types" much better.

```
git commit --amend -m "simplify E0308 message for primitive types"
git push origin <branch name> -f
```

should be all you need to do to update it.

**Comment by KalitaAlexey** [comment]
I made it @nrc.

**Comment by nrc** [comment]
Thanks!

@bors: r+

**Pull request merged**
