### PR TITLE
Use larger span for adjustment THIR expressions

### PR DESCRIPTION
**Pull request by Aaron1011**
Currently, we use a relatively 'small' span for THIR
expressions generated by an 'adjustment' (e.g. an autoderef,
autoborrow, unsizing). As a result, if a borrow generated
by an adustment ends up causing a borrowcheck error, for example:

```rust
let mut my_var = String::new();
let my_ref = &my_var
my_var.push('a');
my_ref;
```

then the span for the mutable borrow may end up referring
to only the base expression (e.g. `my_var`), rather than
the method call which triggered the mutable borrow
(e.g. `my_var.push('a')`)

Due to a quirk of the MIR borrowck implementation,
this doesn't always get exposed in migration mode,
but it does in many cases.

This commit makes THIR building consistently use 'larger'
spans for adjustment expressions. These spans are recoded
when we first create the adjustment during typecheck. For
example, an autoref adjustment triggered by a method call
will record the span of the entire method call.

The intent of this change it make it clearer to users
when it's the specific way in which a variable is
used (for example, in a method call) that produdes
a borrowcheck error. For example, an error message
claiming that a 'mutable borrow occurs here' might
be confusing if it just points at a usage of a variable
(e.g. `my_var`), when no `&mut` is in sight. Pointing
at the entire expression should help to emphasize
that the method call itself is responsible for
the mutable borrow.

In several cases, this makes the `#![feature(nll)]` diagnostic
output match up exactly with the default (migration mode) output.
As a result, several `.nll.stderr` files end up getting removed
entirely.

### CODE REVIEW

**Comment by Aaron1011** [comment]
Note that we don't currently explain that an autoderef/autoborrow was the cause of the borrow that resulted in an error. Doing so would require tracking additional information about THIR expressions / MIR statements, since we can't otherwise distinguish between a user-written `&mut_var`, and an adjustment-generated autoref.

However, I don't think this change makes the situation any *more* confusing. Previously, a user might be lead to incorrectly ask "Why does writing `my_var` trigger a mutable reference". With this change, they will hopefully instead by lead to ask "Why does writing `my_var.some_method()` trigger a mutable reference", which is the right question to be asking.

**Comment by estebank** [comment]
r=me after fixing the tests

**Comment by Aaron1011** [comment]
It looks like storing the additional span in `Adjustment` is causing a large number of new incr comp invalidations of typecheck results. I'll see if anything can be done about it.

**Comment by estebank** [comment]
If you somehow keep two spans around, I would love it if we could point at both the receiver and the call with different labels to maybe explain what's happening better, but that might be too involved for this PR.

**Comment by Aaron1011** [comment]
@estebank: I rewrote the implementation entirely - only `rustc_mir_build` needs to be modified now. Also, I've decreased the scale of this change slightly - it now only applies to method calls, rather than all adjustments.

**Comment by ehuss** [comment]
@bors retry
Issue with Windows LLDB

**Pull request merged**
