### PR TITLE
Add From<E: Error + Send> for Box<dyn Error + Send> impl

### LINKED ISSUE #62824: Tracking issue for From<E> for Box<dyn Error + Send> and Box<dyn Error + Sync>
[As explained in the Rust User forum](https://users.rust-lang.org/t/impl-e-error-from-e-for-box-dyn-error-send/30507), I noticed that the following impls are not available:
```rust
impl<'a, E: Error + Send + 'a> From<E> for Box<dyn Error + Send + 'a> {}
impl<'a, E: Error + Sync + 'a> From<E> for Box<dyn Error + Sync + 'a> {}
```
The first one is pretty useful when working with [rayon](https://crates.io/crates/rayon) and errors, which only need to be `Send` to be passed across threads. In theory, a stateful error with a `Cell` or a `RefCell` is a possible example of `dyn Error + Send + !Sync`.

The second impl is mainly for coherence and symmetry, I still do not have in mind a possible realistic situation.

In any case, IMHO this feature should not require a RFC. In that case I can create a PR and follow these steps:
- [ ] Implement the two impls
- [ ] Adjust the docs

It is the first time I contribute to Rust, and I am not sure if this feature should require a stabilization process. In this case just let me know, and I will update this document in order to include the addition of a feature gate and everything needed.

Any feedback is appreciated to make me do things nicely and your review less painful.

### PR DESCRIPTION
**Pull request by roblabla**
Adds the following implementation:

```rust
 impl<'a, E: Error + Send + 'a> From<E> for Box<dyn Error + Send + 'a>;
```

Partially fixes #62824 

Said issue also mentions adding an `impl<'a, E: Error + Sync + 'a> From<E> for Box<dyn Error + Sync + 'a> {}`, but I doubt its usefulness. AFAIK, a type that is `Sync + !Send` is extremely rare/shouldn't happen. Thus, `Send + Sync` and `Sync` are much the same.

### CODE REVIEW

**Comment by joshtriplett** [comment]
This seems reasonable, but someone from @rust-lang/libs needs to review it.

Also, you need to update tests.

**Comment by roblabla** [comment]
Yeah I'm on it (currently waiting for rust to compile, which is taking ages on my slow machine).

To make `Box<dyn Error + Send>` more consistent, I think the following impls should be added as well:

```rust
impl From<String> for Box<dyn Error + Send> {}
impl<'a> From<&str> for Box<dyn Error + Send + 'a> {}
impl<'a, 'b> From<Cow<'a, str>> for Box<dyn Error + Send + 'b> {}
```

On that note, I'm having a hard time understanding the lifetimes here... Take the following two impls:

```rust
impl From<&str> for Box<dyn Error>;
impl<'a> From<&str> for Box<dyn Error + Send + Sync + 'a>;
```

What's `'a`? The only lifetime I can think of that makes sense here is `'static`. And why are the two impls inconsistent in their lifetime usages?

**Comment by rodrimati1992** [comment]
> a type that is `Sync + !Send` is extremely rare/shouldn't happen

Well,there's [MutexGuard](https://doc.rust-lang.org/std/sync/struct.MutexGuard.html) , [RwLockReadGuard](https://doc.rust-lang.org/std/sync/struct.RwLockReadGuard.html) , and [RwLockWriteGuard](https://doc.rust-lang.org/std/sync/struct.RwLockWriteGuard.html) ,which I guess are rare. I also don't know how often they'd be put inside an error type.

**Comment by Dylan-DPC** [comment]
going to close this pr due to inactivity. If you wish, and you have a fix that resolves the error above you can submit a new pull request, and we'll take it from there. Thanks for taking the time to contribute :)

**Pull request closed without merging**
