### PR TITLE
Rustdoc: ignore deref-inherited static methods

### LINKED ISSUE #24575: Rustdoc inlined Deref impls should not include static methods.
As of #24396, rustdoc inlines Deref impls (:smiley:). However, static methods are also included. Static methods probably shouldn't be included as they can't be called through Deref. They also appear to mess with search results.

### LINKED ISSUE #25673: Methods from deref in rustdoc erroneously show static methods
An example (originally found in this [SO question](http://stackoverflow.com/questions/30362979/how-to-run-pathbufnew-with-an-argument)) is [PathBuf](http://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html) - it shows a static method on `Path` in the "Methods from Deref" section, but naturally static methods can't be called through `Deref` since it requires having an object.

### PR DESCRIPTION
**Pull request by aochagavia**
Fixes #24575 
Fixes #25673 

r? @alexcrichton

### CODE REVIEW

**Comment by aochagavia** [comment]
I am not sure on how to test this. At this moment I only know that it compiles...

**Comment by alexcrichton** [comment]
Could you modify the existing tests for #19190 in conjunction with the `@count` directive to ensure that none of these show up in the various cases tested by #19190? You should be able to just modify the contents of the `src/test/rustdoc` folder.

Also, could you upload a copy of the docs so they could be manually verified as well?

**Comment by aochagavia** [comment]
It seems that my changes aren't entirely correct. Hiding static methods works if the target type is a primitive (in this case `i32`), but doesn't if it is user-defined. I have checked the logic of the code (mainly the following functions: `build_deref_target_impls`, `build_deref_impls`, `build_impls`, `build_impls_helper`, `build_impl`) and I am unable to find the problem. Are there any other functions which could interact with this feature?

btw, I used `@!has` instead of `@count` to check that the static methods aren't shown. Is that ok?

**Comment by alexcrichton** [comment]
I think you may want to modify the [rendering function](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render.rs#L2261-L2282)  instead of the inlining functions as local `Deref` target `impl` blocks are not inlined (they're already in the AST) so they're not pruned already.

Also yeah using `@!has` is fine, I didn't even know it existed!

**Comment by aochagavia** [comment]
Thanks for your feedback! I have updated the PR and uploaded the documentation to http://aochagavia.github.io/rust/index.html

**Comment by alexcrichton** [comment]
@bors: r+ 2c79fb59bb76c72d44600af6ffd46edf815672db

Thanks!

**Comment by alexcrichton** [comment]
@bors: r-

er actually, could you squash the commits and a more descriptive commit message about this fix? Unfortunately `Fix #XXXXX` isn't too descriptive :(

**Comment by sfackler** [comment]
Ping?

**Comment by aochagavia** [comment]
Sorry, I won't have time to resolve the merge conflicts and test the patch again in the following weeks. Feel free to pick it up, though.

**Comment by bluss** [comment]
There's another tricky case, all types that deref to slice also show the method `fn into_vec(self: Box<[T]>) -> Vec<T>`. Is it possible to filter out that as well?

**Comment by aochagavia** [comment]
Finally I found time to rebase this. I think it would be better to create an issue for the case @bluss pointed out, since I will not be able to tackle it anytime soon.

@alexcrichton r+?

**Comment by bluss** [comment]
that's fine, I'm happy with every improvement to rustdoc, so thanks!

**Comment by bluss** [comment]
Also fixes dup #25673

**Comment by alexcrichton** [comment]
@bors: r+ 87038831f1d1eafe6978a823cdbb353d3a7d3f8d 

Thanks!

**Pull request merged**
