### PR TITLE
Issue #46589 - Kill borrows on a local variable whenever we assign ov…

### PR DESCRIPTION
**Pull request by Yoric**
…er this variable

This is a first patch for the issue, handling the simple case while I figure out the data structures involved in the more complex cases.

### CODE REVIEW

**Comment by bjorn3** [comment]
Issue #46589 (just to link it)

Could you add a test?

**Comment by pnkfelix** [comment]
The code looks fine to me; just add a test and we should be good.

**Comment by Yoric** [comment]
Note: problem appears even if we add a

```rust
let mut list = list;
```

**Comment by arielb1** [comment]
@Yoric 

That's because you haven't fixed this:
https://github.com/rust-lang/rust/blob/a9f047c048eac4f135dd6df5223b7195d651539d/src/librustc_mir/borrow_check/mod.rs#L335-L355

**Comment by Yoric** [comment]
Ok, thanks to @arielb1, this now seems to work.

**Comment by Yoric** [comment]
(oops, forgot to remove the obsolete test, this should now be fixed)

**Comment by Yoric** [comment]
As far as I can tell, the single failure is a timeout, which I imagine is not caused by this PR.

**Comment by Yoric** [comment]
Fwiw, `SYS_BITS=32, RUST_CONFIGURE_ARGS=--build=i686-pc-windows-gnu, SCRIPT=python x.py test, MINGW_URL=https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror, MINGW_ARCHIVE=i686-6.3.0-release-posix-dwarf-rt_v5-rev2.7z, MINGW_DIR=mingw32` timed out after 3 hr

**Pull request merged**
