### PR TITLE
Only export `__tls_*` on wasm32-unknown-unknown.

### PR DESCRIPTION
**Pull request by sunfishcode**
From talking with @abrown, we aren't planning to have hosts call these `__tls_*` functions; instead, TLS initialization will be handled transparently within libc. Consequently, these functions don't need to be exported.

Leave them exported on wasm32-unknown-unknown though, as wasm-bindgen does call them.

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
I am not familiar with this field. I prefer rerolling. r? compiler

**Comment by oli-obk** [comment]
Do you think anyone is relying on this right now? As in, will this break something? I know it's just Tier 2, but still.

**Comment by bjorn3** [comment]
Wasi doesn't support threads and I think emscripten doesn't allow directly using the wasm module, but requires using the javascript wrapper. In any case emscripten doesn't hit this linker path at all. Instead it uses emcc for linking.

**Comment by oli-obk** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
