### PR TITLE
Reland #132772: use `download-rustc="if-unchanged"` as a global default

### PR DESCRIPTION
**Pull request by onur-ozkan**
Relands https://github.com/rust-lang/rust/pull/132772 with the fix.

r? jieyouxu (knows the context).

### CODE REVIEW

**Comment by jieyouxu** [comment]
I'm afraid for whatever reason this still is not sufficient, a local stage1 compiler build with this PR's changes shows:

```
PS X:\repos\rust> rustc +stage1 -vV
rustc 1.84.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-pc-windows-msvc
release: 1.84.0-dev
LLVM version: 19.1.3
```

**Comment by onur-ozkan** [comment]
> I'm afraid for whatever reason this still is not sufficient, a local stage1 compiler build with this PR's changes shows:
> 
> 
> 
> ```
> 
> PS X:\repos\rust> rustc +stage1 -vV
> 
> rustc 1.84.0-dev
> 
> binary: rustc
> 
> commit-hash: unknown
> 
> commit-date: unknown
> 
> host: x86_64-pc-windows-msvc
> 
> release: 1.84.0-dev
> 
> LLVM version: 19.1.3
> 


You need to use different channel than "dev" in config.toml.

**Comment by jieyouxu** [comment]
> You need to use different channel than "dev" in config.toml.

... Right, I use compiler profile by default. Changed to:

```toml
profile = "compiler"
change-id = 999999

[llvm]
#assertions = true
download-ci-llvm = true

[build]
build = "x86_64-pc-windows-msvc"
#profiler = true

[rust]
channel = "nightly"
download-rustc = false
codegen-backends = ["llvm"]
deny-warnings = true
debug = false
debuginfo-level = 1
#debug-logging = true
debug-assertions = true
debug-assertions-std = true
```

and building local stage1 rustc to double-check `-vV` output.

FTR, I find it a bit strange that `dev`-channel rustc builds omit git info, because when I do compiler stuff I would like to sometimes know which commit the compiler was built with (especially if it's local changes).

**Comment by jieyouxu** [comment]
But anyway, I can confirm that `rustc +stage1 -vV` contains git info as expected by changing channel to something that's not `dev`, e.g. `nightly`:

```
PS X:\repos\rust> rustc +stage1 -vV
rustc 1.84.0-nightly (a9944bed3 2024-11-10)
binary: rustc
commit-hash: a9944bed3a8272cf6b1738d0d30aaf75ea7d079e
commit-date: 2024-11-10
host: x86_64-pc-windows-msvc
release: 1.84.0-nightly
LLVM version: 19.1.3
```

**Review by jieyouxu — APPROVED** [review]
The changes themselves LGTM and I did some manual testing and this seems to work properly for non-`dev`-channel builds.

**Comment by jieyouxu** [comment]
(Renamed PR title to be slightly more informative)

**Comment by Zalathar** [comment]
Question: Does this mean that `download-rustc="if-unchanged"` becomes the default for the `compiler` profile?

If so, that seems like the wrong default for users of that profile. For example, trying to build the compiler on `master` might waste time downloading rustc, instead of populating the build cache for further changes as the user intended.

**Comment by jieyouxu** [comment]
> If so, that seems like the wrong default for users of that profile. For example, trying to build the compiler on `master` might waste time downloading rustc, instead of populating the build cache for further changes as the user intended.

What do you mean by that? Wouldn't rustc download be skipped if rustc was modified?

**Comment by Zalathar** [comment]
E.g. if I do:

```sh
git checkout master
git reset --hard origin/master
git pull
./x build library
```

Would that build the compiler (as expected), or would it download a pre-built compiler instead?

**Comment by jieyouxu** [comment]
> Would that build the compiler (as expected), or would it download a pre-built compiler instead?

AFAIK that would download a pre-built compiler if `compiler/` tree has otherwise no local changes. Good point. I would've expected compiler profile to never `download-rustc` unless explicitly specified to be `true`, but `download-rustc = 'if-unchanged'" for other profiles is reasonable as default.

cc @onur-ozkan what do you think?

@bors r- (unresolved concerns)

**Comment by onur-ozkan** [comment]
> E.g. if I do:
> 
> ```shell
> git checkout master
> git reset --hard origin/master
> git pull
> ./x build library
> ```
> 
> Would that build the compiler (as expected), or would it download a pre-built compiler instead?

If you haven't modified the compiler tree and your configuration doesn't conflict with the pre-compiled rustc, why would you want to compile the in-tree compiler? I'm also unsure how many people would actually prefer that. If you still want to build the in-tree compiler without any changes, you can always set `download-rustc` explicitly to `false`. 

The goal here is to use the same default between library and compiler profiles to keep similar bootstrap behaviour on build process.

From @RalfJung on [Zulip thread](https://rust-lang.zulipchat.com/#narrow/channel/219381-t-libs/topic/.E2.9C.94.20How.20to.20debug.20miri.20errors.20on.20different.20platform/near/481295740):

> FWIW I think download-rustc=if-unchanged should also be made the right option for basically all cases, so there's no reason to have that different between "compiler" and "library" profiles, either

**Comment by jieyouxu** [comment]
> If you haven't modified the compiler tree and your configuration doesn't conflict with the pre-compiled rustc, why would you want to compile the in-tree compiler? I'm also unsure how many people would actually prefer that. If you still want to build the in-tree compiler without any changes, you can always set `download-rustc` explicitly to `false`.
> 
> The goal here is to use the same default between library and compiler profiles to keep similar bootstrap behaviour on build process.

I'll double-check with other compiler team members, but I would personally prefer if we kept `download-rustc = false` for compiler profile and `if-unchanged` for other profiles at least in this PR. I go around and ask compiler people if we have consensus, and I can send a follow-up to also make this the default for compiler profile if we do.

**Comment by RalfJung** [comment]
I think it would be a bad idea to use different settings for libs and compiler work. It is not uncommon for the same person to do both, and I certainly don't want to reconfigure my checkouts each time I switch between the two. We should provide a seamless transition for a new contributor to switch from a library patch to a compiler patch and vice versa.

A compiler dev will basically always change the "compiler" dir, so things will behave exactly as they should.

**Review by jieyouxu — APPROVED** [review]
Thanks for the preset changes. You can r=me after PR CI is green.

**Comment by lqd** [comment]
Noise of course.

@rustbot label: +perf-regression-triaged

**Comment by lqd** [comment]
https://github.com/rust-lang/rust/blob/dae7ac133b9eda152784c075facb31a6688c92b1/config.example.toml#L499-L507 needs to be updated to the new default

**Pull request merged**
