### PR TITLE
Changed "functional structure update syntax" to "structure update syntax"

### PR DESCRIPTION
**Pull request by alexispurslane**
per #28168. This is my first contribution. I don't know who to "r?" for source code changes.

### CODE REVIEW

**Comment by nrc** [comment]
@christopherdumas If you don't know who to r?, don't do anything and highfive will pick a suitable reviewer for you

**Comment by christopherdumas** [comment]
Thanks! I noticed from "nrc was assigned by rust-highfive 3 minutes ago" message.

**Comment by christopherdumas** [comment]
I'm really excited to start contributing to rust.

**Comment by steveklabnik** [comment]
:confetti_ball:

**Comment by bluss** [comment]
@bors r=nrc

@christopherdumas Don't forget to ping someone if you push an update to your PR. It should be on its way to merge now.

**Pull request merged**
