### PR TITLE
Update RLS and Rustfmt and Cargo

### PR DESCRIPTION
**Pull request by nrc**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@nrc with https://github.com/rust-lang-nursery/rls/pull/635 mind if I throw that plus the cargo update in here as well?

**Comment by nrc** [comment]
@alexcrichton sure! I can do that - I still have the branch ready

**Comment by alexcrichton** [comment]
I pushed an extra commit to update the git2 binding as well, but feel free to squash it away if something else on this branch changes

@bors: r=nrc

**Comment by kennytm** [comment]
@bors r-

I'm pretty sure the errors are legit. The failing test cases are:

1. [`https_something_happens`](https://github.com/rust-lang/cargo/blob/848eb156ef088bbfb60225e0d608a96471f29aef/tests/build-auth.rs#L133). The test tries to connect to `https://127.0.0.1:*/` which should be serving invalid response. It is expected to contain the string "failed to send request". Instead, the output was:

```
    Updating git repository `https://127.0.0.1:2858/foo/bar`
error: failed to load source for a dependency on `bar`
Caused by:
  Unable to update https://127.0.0.1:2858/foo/bar
Caused by:
  failed to clone into: C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\cit\t0\home\.cargo\git\db\bar-bb0ae0d2822494b3
Caused by:
  [35] SSL connect error (schannel: failed to receive handshake, SSL/TLS connection failed); class=Net (12)
', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

2. [`http_auth_offered`](https://github.com/rust-lang/cargo/blob/848eb156ef088bbfb60225e0d608a96471f29aef/tests/build-auth.rs#L18). Authorization failure (HTTP 401) happens as expected, but again, the error message differs.

```
 10 - |  failed to authenticate when downloading repository|
    + |  failed to receive HTTP 200 response: got 401; class=Net (12)|
 11 - |attempted to find username/password via `credential.helper`, but [..]|
    +
 12 - ||
    +
 13 - |To learn more, run the command again with --verbose.|
    +
```

**Comment by alexcrichton** [comment]
I think https://github.com/rust-lang/cargo/pull/4856 should fix that issue

**Comment by kennytm** [comment]
rustfmt is still broken.

```
[01:00:33] error[E0063]: missing field `recovered` in initializer of `syntax::ast::Block`
[01:00:33]    --> /checkout/src/tools/rustfmt/src/closures.rs:127:17
[01:00:33]     |
[01:00:33] 127 |     let block = ast::Block {
[01:00:33]     |                 ^^^^^^^^^^ missing `recovered`
[01:00:33] 
[01:00:36] error: aborting due to previous error
```

**Comment by alexcrichton** [comment]
Ok, I've approved https://github.com/rust-lang/rust/pull/46630 in the meantime to get the incremental-by-default builds out in Cargo, but @nrc if this ends up landing before that I'll close it!

**Comment by nrc** [comment]
> rustfmt is still broken.

Rustfmt has been broken again, to be precise :-(

**Comment by topecongiro** [comment]
rustfmt is fixed on 0.3.4.

**Comment by estebank** [comment]
> Rustfmt has been broken again, to be precise :-(

@nrc @alexcrichton that'd be my fault. I didn't push a PR to cargo to fix it because I didn't realize the new field had landed in rustc yet.

**Comment by kennytm** [comment]
Since rls and rustfmt has been updated in #47051 and cargo in #47052, this PR is no longer necessary. Closing.

**Pull request closed without merging**
