### PR TITLE
Underline multiple suggested replacements in the same line

### LINKED ISSUE #50977: Underline all the places where the substitutions have taken place
After #50943 exposes multiple substitutions in suggestions, we should improve the output of the diagnostic to underline all the places where the substitutions have taken place:

Before:

```
error[E0643]: method `foo` has incompatible signature for trait
  --> $DIR/impl-generic-mismatch.rs:18:12
   |
LL |     fn foo(&self, _: &impl Debug);
   |                       ---------- declaration in trait here
...
LL |     fn foo<U: Debug>(&self, _: &U) { }
   |            ^ expected `impl Trait`, found generic parameter
help: try removing the generic parameter and using `impl Trait` instead
   |
LL |     fn foo(&self, _: &impl Debug) { }
   |
```

After:

```
error[E0643]: method `foo` has incompatible signature for trait
  --> $DIR/impl-generic-mismatch.rs:18:12
   |
LL |     fn foo(&self, _: &impl Debug);
   |                       ---------- declaration in trait here
...
LL |     fn foo<U: Debug>(&self, _: &U) { }
   |            ^ expected `impl Trait`, found generic parameter
help: try removing the generic parameter and using `impl Trait` instead
   |
LL |     fn foo(&self, _: &impl Debug) { }
   |           ^           ^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by estebank**
screen shot 2018-05-22 at 21 06 48

Follow up to #50943.

Fix #50977.

### CODE REVIEW

**Comment by petrochenkov** [comment]
r=me after updating UI tests

**Comment by estebank** [comment]
Bizarre, I am not seeing those errors locally.

**Comment by kennytm** [comment]
@bors r- rollup-

This PR conflicts with the just-merged #50943, please rebase.

```
[00:43:56] ---- [ui] ui/impl-trait/impl-generic-mismatch.rs stdout ----
[00:43:56] diff of stderr:
[00:43:56] 
[00:43:56] 9	help: try removing the generic parameter and using `impl Trait` instead
[00:43:56] 10	   |
[00:43:56] 11	LL |     fn foo(&self, _: &impl Debug) { }
[00:43:56] -	   |
[00:43:56] +	   |          --           ^^^^^^^^^^
[00:43:56] 13	
[00:43:56] 14	error[E0643]: method `bar` has incompatible signature for trait
[00:43:56] 15	  --> $DIR/impl-generic-mismatch.rs:27:23
```

**Pull request merged**
