### PR TITLE
Introduce {Ref, RefMut}::try_map for optional projections in RefCell

### PR DESCRIPTION
**Pull request by udoprog**
This fills a usability gap of `RefCell` I've personally encountered to perform optional projections, mostly into collections such as `RefCell<Vec<T>>` or `RefCell<HashMap<U, T>>`:

> This kind of API was briefly featured under Open questions in #10514 back in 2013 (!)

```rust
let values = RefCell::new(vec![1, 2, 3, 4]);
let b = Ref::opt_map(values.borrow(), |vec| vec.get(2));
```

It primarily avoids this alternative approach to accomplish the same kind of projection which is both rather noisy and panicky:
```rust
let values = RefCell::new(vec![1, 2, 3, 4]);

let b = if values.get(2).is_some() {
    Some(Ref::map(values.borrow(), |vec| vec.get(2).unwrap()))
} else {
    None
};
```

### Open questions

The naming `opt_map` is preliminary. I'm not aware of prior art in std to lean on here, but this name should probably be improved if this functionality is desirable.

Since `opt_map` consumes the guard, and alternative syntax might be more appropriate which instead *tries* to perform the projection, allowing the original borrow to be recovered in case it fails:

```rust
pub fn try_map<U: ?Sized, F>(orig: Ref<'b, T>, f: F) -> Result<Ref<'b, U>, Self>
where
    F: FnOnce(&T) -> Option<&U>;
```

This would be more in line with the `try_map` method [provided by parking lot](https://docs.rs/lock_api/0/lock_api/struct.RwLockWriteGuard.html#method.try_map).

### CODE REVIEW

**Comment by RustyYato** [comment]
This could be renamed to `try_map` like `Iterator::try_fold` and return `Result<_, _>` so that you can pass back errors. You can still use `Option::ok_or` if you need to. In the future this could be generalized with `Try`

**Comment by KodrAus** [comment]
This seems like a reasonable addition to me. We could consider a method like `try_map`, but in that case I think it should return a `impl Try` rather than an `Option`:

```rust
fn try_map<F, U, R>(orig: Ref<'b, T>, f: F) -> Result<Ref<'b, U>, R::Error>
where
    F: FnOnce(&T) -> R,
    R: Try<Ok = &U>
```

What do you think?

**Comment by udoprog** [comment]
> This seems like a reasonable addition to me. We could consider a method like `try_map`, but in that case I think it should return a `impl Try` rather than an `Option`:
> 
> ```rust
> fn try_map<F, U, R>(orig: Ref<'b, T>, f: F) -> Result<Ref<'b, U>, R::Error>
> where
>     F: FnOnce(&T) -> R,
>     R: Try<Ok = &U>
> ```
> 
> What do you think?

Thanks for taking a look. This seems good to me. I'll take it for a spin!

**Comment by udoprog** [comment]
Updated and seems to work 🎉

**Comment by RustyYato** [comment]
@udoprog your current implementation is unsound! You cannot name the lifetimes like so:

```rust
fn try_map<F, U, R>(orig: Ref<'b, T>, f: F) -> Result<Ref<'b, U>, R::Error>
where
    F: FnOnce(&'b T) -> R,
    R: Try<Ok = &'b U>
```

Because this allows you to extract the value out of the `Ref` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=88183a32d3a694282febd06e18d932c5)). Note: the playground link uses a dummy implementation of `RefCell` and `Ref`, but the problem will persist in the real implementation.

Here's one (clunky and really bad) solution that works [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5486ea12ee3deb71df933316039a7141). But it doesn't play with closures well, so you'll need to use functions [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018). Or we could not generalize to `Try` in the first place, and be satisfied with `Result` or `Option` (my preferred option).

**Comment by udoprog** [comment]
@RustyYato doh, I had a feeling something was gonna go wrong with removing the HRTB's. Thanks for showcasing it!

FWIW, returning `Result<Ref<'b, T>, Self>` would be my preferred approach as well.

**Comment by udoprog** [comment]
For now I've at least pushed an impl that returns `Option<..>` which **should** be sound.

While working on it I noticed that a variant that returns `Result<..., Self>` would require a raw pointer since the error variant would need to reconstruct the guard from the mutable reference being passed in. I'll be pushing that on a separate branch, cause I'm not entirely sure it's a sound approach.

**Comment by RustyYato** [comment]
You can simplify the match a bit
```rust
match f(unsafe { &mut *value }) {
    Some(value) => Ok(RefMut { value, borrow }),
    None => Err(RefMut { value: unsafe { &mut *value }, borrow }),
}
```
But yes, this is sound (exactly because of HRTB :grin:)

**Comment by KodrAus** [comment]
Hmm, I don't think I'd want to stabilize `try_map` without `Try`, but if we wanted to punt on  use `Option` then we could just call it `filter_map`?

**Comment by udoprog** [comment]
> Hmm, I don't think I'd want to stabilize `try_map` without `Try`, but if we wanted to punt on it and use `Option` then we could just call it `filter_map`?

I'm fine either way. I do prefer one that produces `Result<Ref<'b, U>, Self>` because it allows reconstruction of the original value if the projection fails but have no idea what to call it if not `try_map` (see: [parking_lot](https://docs.rs/lock_api/0.4.2/lock_api/struct.RwLockReadGuard.html#method.try_map)).

But I'll defer to other peoples judgement. Tell me what to do and I'll do it.

**Comment by KodrAus** [comment]
> I do prefer one that produces Result<Ref<'b, U>, Self> because it allows reconstruction of the original value if the projection fails

Ah that's an interesting point 🤔 That might be a better way to go then since this is already a niche API. I'm still thinking `Ref::filter_map` is a more appropriate name than `try_map`, because we're not fallible inside the closure, it's just that what we're projecting might be `None`. That would align with a `Ref::map` method that can always project individual fields, and a `Ref::try_map` method (that we can't currently write generically) that's fallible.

So what do we think of:

```rust
pub fn filter_map<U: ?Sized, F>(orig: Ref<'b, T>, f: F) -> Result<Ref<'b, U>, Self>
where
    F: FnOnce(&T) -> Option<&U>;
```

**Comment by udoprog** [comment]
Using `filter_map` for the name now, which returns a `Result`.

**Comment by KodrAus** [comment]
Thanks @udoprog! I've opened #81061 as a tracking issue and updated the `#[unstable]` attributes to reflect that.

@bors r+

**Comment by scottmcm** [comment]
> `-> Result<Ref<'b, U>, Self>`

With a return type like that, I think it makes sense to do this in a way that doesn't use `Try` -- always using `Self` as the error type makes this materially different, to me, from something like `Iterator::try_find`.

So :+1: to phrasing this as filter_map and just supporting `Option`.

**Pull request merged**
