### PR TITLE
make `incoherent_auto_trait_objects` a hard error

### LINKED ISSUE #56484: Tracking issue for future-incompatbility lint `order_dependent_trait_objects`
This is the **summary issue** for the `order_dependent_trait_impls`
future-compatibility warning and other related errors. The goal of
this page is describe why this change was made and how you can fix
code that is affected by it. It also provides a place to ask questions
or register a complaint if you feel the change should not be made. For
more information on the policy around future-compatibility warnings,
see our [breaking change policy guidelines][guidelines].

[guidelines]: https://github.com/rust-lang/rfcs/blob/master/text/1122-language-semver.md

#### What is the warning for?

As in issue #33140, rustc sometimes treats "seemingly-identical" trait object types as different. For example, `Send + Sync` and `Sync + Send` are treated as different types.

This occurs because the first trait in a trait object is treated specially in the compiler, which means that `Send + Sync` has its "first trait" being `Send` and `Sync + Send` has its "first trait" being `Sync`. That is a bug that we want to fix.

However, because the compiler made this distinction, it was possible to implement a trait separately for each of these types, for example:

```Rust
trait Foo {
    fn xyz();
}

impl Foo for dyn Send + Sync {
    fn xyz() {
        println!("Hi I'm Send + Sync");
    }
}

impl Foo for dyn Sync + Send {
//~^ ERROR conflicting implementations
    fn xyz() {
        println!("Hi I'm Sync + Send");
    }
}

fn main() {
    <dyn Send + Sync>::xyz();
    <dyn Sync + Send>::xyz();
}
```

This obviously can't work if `Send + Sync` & `Sync + Send` are the same type! Therefore, it is being made into a coherence error.

To fix the warnings, remove all but one of the impls - e.g. the `Sync + Send` impl.

#### When will this warning become a hard error?
                    
At the beginning of each 6-week release cycle, the Rust compiler team
will review the set of outstanding future compatibility warnings and
nominate some of them for **Final Comment Period**. Toward the end of
the cycle, we will review any comments and make a final determination
whether to convert the warning into a hard error or remove it
entirely.

#### Status

 - introduced by #56481
 - changed to `deny`-by default and report in deps in #102635

### PR DESCRIPTION
**Pull request by lcnr**
needs a crater run, this lint exists since nearly 4 years now and the affected crate is not maintained anymore.

The current implementation for the lint will break with #102472, which is fixes caching for the trait system. Keeping this lint working with the current implementation will be non-trivial and imo not worth the cost.

closes #56484

r? types

### CODE REVIEW

**Comment by lcnr** [comment]
@craterbot check

**Comment by lcnr** [comment]
ok that looks wrong :thinking: cc @rust-lang/infra is that an issue with crater? i would have expected the `traitobjects` crate to be part of the regressed crates but i can't find it and there seem to be a surprising amount of unrelated failures

**Comment by jyn514** [comment]
@lcnr the newly failed builds are marked "build OOM"; I don't know the details of this change but it seems plausible to me it could be taking extra memory. They're marked as "spurious regressions"; you can see the root regressions (due to compiler errors) under "root results".

**Comment by jyn514** [comment]
ah, and `traitobjects` is under "regressed: dependencies"

**Comment by lcnr** [comment]
hmm, interesting that it doesn't fail as a root cause :thinking: only looked at the first 3 entries of "regressed: dependencies" which were all spurious '^^ should have maybe looked a bit further down :grin:

**Pull request closed without merging**
