### PR TITLE
stabilized iterator_for_each (closes #42986)

### LINKED ISSUE #42986: Tracking issue for the `iterator_for_each` library feature
This is to track the stabilization of `Iterator::for_each()`, added in #42782.

### PR DESCRIPTION
**Pull request by budziq**
Also updated clippy and rls as these use the iterator_for_each

I've made my first PR's today so most likely I've done something wrong. Sorry about that!

### CODE REVIEW

**Comment by kennytm** [comment]
Failed to start the CI. Please update `src/Cargo.lock`.

```
[00:00:49] error: the lock file needs to be updated but --frozen was passed to prevent this
```

**Comment by cuviper** [comment]
This needs to wait for completed FCP, right?

**Comment by kennytm** [comment]
@cuviper according to https://internals.rust-lang.org/t/stabilizing-apis-in-the-standard-library/5906, it is ready once all team member checked their boxes, there's no need to wait for the FCP to end.

> once all libs members have checked their checkboxes the issue is tagged with `final-comment-period` meaning it’s ready for stabilization.

**Comment by alexcrichton** [comment]
Looks great to me, thanks @budziq! Looks like some stray submodule updates were included though?

@cuviper yeah for APIs we don't wait for the FCP to end, we just go ahead and throw them in once the team has signed off.

**Comment by budziq** [comment]
> Failed to start the CI. Please update src/Cargo.lock.

@kennytm Updated with Cargo.lock. Sorry about that!

> Looks like some stray submodule updates were included though?

@alexcrichton The submodule updates were intentional due to rls and clipy depending on iterator_for_each. I've made PR's to their respective repos ([rls](https://github.com/rust-lang-nursery/rls/pull/479), [clippy](https://github.com/rust-lang-nursery/rust-clippy/pull/2051)) and updated the submodules to the PR commits according to [this section in CONTRIBUTING.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#external-dependencies)

I might have misunderstood the instructions so I will be glad to fix any problems!

**Comment by oli-obk** [comment]
> I might have misunderstood the instructions so I will be glad to fix any problems!

You're the first person to follow said instructions. Thanks! If any problems show up with the process it's with the instructions and not you ;) Travis seems to like it so far.

**Comment by alexcrichton** [comment]
@bors: r+

Ah ok, thanks!

**Comment by alexcrichton** [comment]
@bors: r-

Er actually, we prefer that our submodules are attached to long-lived commits which are at least somewhat relatively guaranteed to stick around into the future. In that sense the section of the contributing docs is wrong I believe in that we don't want to pin our submodules to PRs.

Does stabilization here cause build failures? If not can the submodule updates happen later on the master branch?

**Comment by budziq** [comment]
> Does stabilization here cause build failures?

The stabilization will cause build failure for rls and test failure in clippy. I believe that we have a chicken and egg problem here and the stabilization and submodule PR's should proceed in lockstep (submodules first to generate a long lived commit and shortly then the lang repo). But this is is actually a question to the maintainers :smile:.

**Comment by alexcrichton** [comment]
You can ignore clippy for now as we're not building it anyway, but for the rls we'll need to make a long-lived branch, which you can coordinate with @nrc for that

**Comment by alexcrichton** [comment]
@nrc can you make a branch of the RLS for this?

**Comment by budziq** [comment]
@alexcrichton The PR is already on a branch

**Comment by alexcrichton** [comment]
@bors: r+

Aha, great!

**Comment by budziq** [comment]
Rebased!

**Pull request merged**
