### PR TITLE
Number of filtered out tests in tests summary

### LINKED ISSUE #31905: Consider no matching named test a failure
Hello,
I was running a test to watch it fail but it was not. It turns out I typed the test wrong. It seems like that if a test name is provided but not found it should be a failure or at least a warning.
`cargo test test_something_that_is_typo`

Thoughts?
Becker

Closed: https://github.com/rust-lang/cargo/issues/2410

### PR DESCRIPTION
**Pull request by mersinvald**
Closes #31905

### CODE REVIEW

**Comment by mersinvald** [comment]
cc @Mark-Simulacrum 
r? @Mark-Simulacrum

**Comment by mersinvald** [comment]
I forgot to change tests according to the changes. Do not merge it just yet, IDK why Travis CI builds do not fail

Sorry for inconvenience, It's my first PR into rust :)

**Comment by Mark-Simulacrum** [comment]
Changes look good to me. Could you squash your changes into one commit? Thanks!

**Comment by mersinvald** [comment]
@Mark-Simulacrum I'm not sure how. "Merge pull request" button is not availible for me, I don't know other ways so squash commits in pull request other then this button's variant.

**Comment by Mark-Simulacrum** [comment]
Sorry about that. I should have provided instructions on how to squash.

Anyway, changes look good.

@bors r+

**Comment by mersinvald** [comment]
@Mark-Simulacrum no problem at all, I shouldn't have asking before googling in the first place :)

**Comment by kennytm** [comment]
Test failed due to Cargo. https://github.com/rust-lang/cargo/blob/d8fa3eb4/tests/bench.rs#L51

See https://github.com/rust-lang/rust/pull/41930#issuecomment-300987566.

**Comment by Mark-Simulacrum** [comment]
Would you mind sending a PR to cargo to add the expected output there?

**Comment by Mark-Simulacrum** [comment]
err, @mersinvald that is.

**Comment by Mark-Simulacrum** [comment]
@bors r-

(since this breaks Cargo's tests)

**Comment by mersinvald** [comment]
@Mark-Simulacrum sure, I will. I should just reference this issue in the PR to cargo, right?

**Comment by Mark-Simulacrum** [comment]
Yeah, that should be fine. I'm not entirely sure how the dance with the submodule will work, though, seeing as with your PR Cargo's tests will presumably fail. But once the Cargo PR is up, ping me and @alexcrichton on it, and we should be able to work it out.

**Comment by mersinvald** [comment]
@Mark-Simulacrum can you assist me through cargo testing process? How can I build cargo with my rustc version and run tests?

I have new rustc in my PATH:
```
$ rustc -V
rustc 1.19.0-dev (e6cde9f2a 2017-05-11)
```

When I do `cargo test` in directory with cloned cargo master, I get such errors:
```
$ RUSTC=/usr/local/bin/rustc LD_LIBRARY_PATH=/usr/local/lib cargo test bench_bin_implicit
error[E0514]: found crate `log` compiled by an incompatible version of rustc
 --> /home/mike/dev/rust/cargo/src/cargo/lib.rs:5:14
  |
5 | #[macro_use] extern crate log;
  |              ^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using this compiler (rustc 1.19.0-nightly (f1140a331 2017-05-08))
  = note: crate `log` path #1: /home/mike/dev/rust/cargo/target/debug/deps/liblog-b8e0bbfdccaf7d7a.rlib compiled by "rustc 1.19.0-dev (e6cde9f2a 2017-05-11)"
```

But cargo seems to use new rustc (I see N filtered out messages for other tests)
I did cargo clean.

How can I fix it?

**Comment by Mark-Simulacrum** [comment]
Oh, I'm sorry I somehow missed your comment! I'm not actually entirely sure how to best do that. @alexcrichton Could you provide some guidance here? I don't know how to sync up Cargo with rustc so that the tests pass there before we merge this and vice-versa.

**Comment by alexcrichton** [comment]
@mersinvald are you using rustup perhaps? If that's the case then the `cargo` wrapper there may be doing some extra funny business behind the scenes. Otherwise though it's probably ok if you just run `cargo test`, w/ the normal rustc b/c when the PR is sent to Cargo that's how the tests are run there.

**Comment by Mark-Simulacrum** [comment]
@mersinvald So I've talked to @alexcrichton on IRC, and for the Cargo PR, you should just change the tests to be less strict about libtest's output so they don't break on the current and the future output (with this PR).

**Comment by euclio** [comment]
Any opinions on using `filtered` over `filtered out`?

**Comment by mersinvald** [comment]
@Mark-Simulacrum currently tests check full output to match. How exactly I should make them less strict? 

I can just remove the last line from tests and match with str::starts_with, but it still can cause tests failures in the future. On the other side if I'll just remove output matching at all, tests will become useless.
Any ideas how to adjust tests without causing safety issues?

**Comment by mersinvald** [comment]
@euclio I think `filtered out` is decided to be used because in the codebase `filtered` tests are sinonim for `to be executed`. Hence, `filtered out` are the opposite.

**Comment by Mark-Simulacrum** [comment]
> I can just remove the last line from tests and match with str::starts_with, but it still can cause tests failures in the future. On the other side if I'll just remove output matching at all, tests will become useless.
Any ideas how to adjust tests without causing safety issues?

My thought is that str::starts_with is fine, cargo shouldn't really be picky about libtest's output beyond "it seems to produce the right results", and if you'd like you could revert the changes once we land submodule updates throughout.

> Any opinions on using filtered over filtered out?

I, for similar reasons to @mersinvald, think filtered out is better. I'm open to suggestions though; we could maybe do "testing 10/20 tests"?

**Comment by mersinvald** [comment]
@Mark-Simulacrum `testing` implies running process, i'd better pick `tested` in this case.

**Comment by Mark-Simulacrum** [comment]
Actually, I don't like the 10/20 idea -- it's not clear since we have both the filter and the ignore list.

Maybe the right approach is to change what filtering means to ignoring instead of "skipping", but that may have other repercussions -- I feel like you can filter to unignore or something? Uncertain.

**Comment by mersinvald** [comment]
@alexcrichton thanks for mentioning rustup, I got it to work by adding new toolchain as default:
```
$ rustup toolchain link rust-dev $PATH_TO_RUST_STAGE2
$ rustup default rust-dev
```

**Comment by mersinvald** [comment]
@Mark-Simulacrum hello! Can you give me update on merging process? Pull Request to cargo is merged now. Are there some difficulties in merging that one?

**Comment by Mark-Simulacrum** [comment]
I think you'll need to put up a PR that updates the cargo submodule in this repository. Once that's merged, I think we can try merging this.

**Comment by mersinvald** [comment]
@Mark-Simulacrum am I right that I just need to do `git pull` and checkout `$my_commit_hash` in the `src/tools/cargo` dir?

**Comment by Mark-Simulacrum** [comment]
I think so. I've never personally done it, but I believe the thing to Google for if that doesn't work is something along the lines of how to update a submodule.

**Comment by Mark-Simulacrum** [comment]
@bors r+

In theory this should work now...

**Comment by Mark-Simulacrum** [comment]
Seems to have timed out? Or ... something? I don't see any failures

@bors retry

**Comment by alexcrichton** [comment]
@Mark-Simulacrum ah yeah our time limit is 3 hours on AppVeyor, and the [failing build](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.3297/job/7ngri1rpk0tgb41h) ran for 3 hours, so likely a timeout.

**Comment by alexcrichton** [comment]
@bors: retry

This seems to keep getting unlucky :(

**Comment by kennytm** [comment]
Spurious 😂. Is there an exponential backoff between each retry? Looks like the 2nd – 5th retry just fail immediately. 

```
extracting C:\projects\rust\build\cache\2017-04-25\cargo-beta-i686-pc-windows-msvc.tar.gz
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/rust-lang/cargo`
    Updating git repository `https://github.com/rust-lang-nursery/rustfmt`
 Downloading cmake v0.1.23
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:01:06
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 2/5:
 Downloading rustc-serialize v0.3.24
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 3/5:
 Downloading filetime v0.1.10
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 4/5:
 Downloading filetime v0.1.10
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 5/5:
 Downloading num_cpus v1.4.0
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
The command has failed after 5 attempts.
```

**Comment by alexcrichton** [comment]
@bors: retry

* [appveyor network issues](https://appveyor.statuspage.io/incidents/2g5jnq5cy1g1) #40474

**Pull request merged**
