### PR TITLE
Fix ICEs when `Self` is used in type aliases

### LINKED ISSUE #62263: ICE "not a type parameter" on nightly (regression)
Repro:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c4a8f90dada13368b5749e84b7b01108

```rust
pub type PrivacyPolicy<E> =
    Vec<Box<dyn PrivacyRule<ViewerContext = Self::ViewerContext, Id = Self::Id, Err = E>>>;

pub trait PrivacyRule {
    type ViewerContext;
    type Id;
    fn can_see(&self, viewer: &Self::ViewerContext, id: &Self::Id) -> ();
}
```

This doesn't ICE on beta or stable but gives the following ICE on nightly:

```
error: internal compiler error: src/librustc/hir/map/mod.rs:517: ty_param_owner: ty PrivacyPolicy (hir_id=HirId { owner: DefIndex(12), local_id: 0 }) not a type parameter

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:643:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0-nightly (b25ee6449 2019-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.
```

### PR DESCRIPTION
**Pull request by alexreg**
I think it is right just to disallow this at resolution stage rather than let typeck produce a cyclic error. This is in line with previous behaviour. There was probably no need at all for the change that introduced this bug in #57428, so I've simply reversed it.

Fixes #62263, #62364, #62305.

r? @eddyb

### CODE REVIEW

**Comment by Centril** [comment]
@alexreg Can you add regression tests from the two issues this fixes?

**Comment by hellow554** [comment]
What about #62305? Should close this as well. Please also add a test for that

**Comment by alexreg** [comment]
Okay, ready for review & merge now. Anyone feel free to do so.

**Comment by alexreg** [comment]
Thanks @pnkfelix!

**Comment by pnkfelix** [comment]
Discussed at T-compiler meeting. accepted for beta backport.

**Pull request merged**
