### PR TITLE
[beta] stage0 bump and backports

### PR DESCRIPTION
**Pull request by cuviper**
- Bump stage0 to stable
- Revert to using `RtlGenRandom` as a fallback #108060 
- Fix `VecDeque::shrink_to` and add tests. #108475 
- Fix `VecDeque::append` capacity overflow for ZSTs #108462 
- Clippy: Fix array-size-threshold config deserialization error #108673 / rust-lang/rust-clippy#10423
- Yeet point_at_expr_source_of_inferred_type for now #108703 

r? @ghost

### CODE REVIEW

**Comment by cuviper** [comment]
cc @rust-lang/release
@bors r+ rollup=never p=1

**Comment by cuviper** [comment]
Several "GitHub Actions has encountered an internal error when running your job."

@bors retry

**Comment by cuviper** [comment]
Holding off so I can add a couple more...

@bors r-

**Comment by pietroalbini** [comment]
It seems like the backport of https://github.com/rust-lang/rust/pull/108673 is incorrect? You added the tests to `tests/ui-toml`, not `src/tools/clippy/tests/ui-toml`.

**Comment by cuviper** [comment]
Ah, whoops -- I just cherry-picked that, but actually #108673 had it that way too. I guess git-subtree confused things when grabbing it from the rust-clippy repo.

**Pull request merged**
