### PR TITLE
Rollup of 18 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #73269 (Enable some timeouts in SGX platform)
 - #73566 (Don't run `everybody_loops` for rustdoc; instead ignore resolution errors)
 - #73771 (Don't pollute docs/suggestions with libstd deps)
 - #73794 (Small cleanup for E0705 explanation)
 - #73807 (rustdoc: glue tokens before highlighting)
 - #73835 (Clean up E0710 explanation)
 - #73926 (Ignoring test case: [codegen] repr-transparent-aggregates-1.rs for aarch64)
 - #73981 (Remove some `ignore-stage1` annotations.)
 - #73998 (add regression test for #61216)
 - #74140 (Make hir ProjectionKind more precise)
 - #74159 (forbid generic params in the type of const params)
 - #74171 (Fix 44056 test with debug on macos.)
 - #74221 (Don't panic if the lhs of a div by zero is not statically known)
 - #74351 (Do not render unstable items for rustc doc)
 - #74359 (rustdoc: Rename internal API fns to `into_string`)
 - #74386 (Add RISC-V GNU/Linux to src/tools/build-manifest as a host platform)
 - #74391 (BtreeMap: superficially refactor root access)
 - #74395 (Bump version to 1.47 )

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors treeclosed=5

So that I can make sure this lands

**Comment by Manishearth** [comment]
i have no idea how that would happen

```
2020-07-16T16:35:36.7648931Z W�i�n�d�o�w�s� �S�u�b�s�y�s�t�e�m� �f�o�r� �L�i�n�u�x� �h�a�s� �n�o� �i�n�s�t�a�l�l�e�d� �d�i�s�t�r�i�b�u�t�i�o�n�s�.�
2020-07-16T16:35:36.7649189Z �
2020-07-16T16:35:36.7649669Z �
2020-07-16T16:35:36.7649930Z �D�i�s�t�r�i�b�u�t�i�o�n�s� �c�a�n� �b�e� �i�n�s�t�a�l�l�e�d� �b�y� �v�i�s�i�t�i�n�g� �t�h�e� �M�i�c�r�o�s�o�f�t� �S�t�o�r�e�:�
2020-07-16T16:35:36.7650115Z �
2020-07-16T16:35:36.7650242Z �
2020-07-16T16:35:36.7650398Z �h�t�t�p�s�:�/�/�a�k�a�.�m�s�/�w�s�l�s�t�o�r�e�
2020-07-16T16:35:36.7650821Z �
2020-07-16T16:35:36.7650978Z �
2020-07-16T16:35:36.7708043Z �
```

**Comment by jyn514** [comment]
Maybe from https://github.com/rust-lang/rust/pull/74395 ?

**Comment by Manishearth** [comment]
That's my guess too but I'm not sure how

**Comment by jyn514** [comment]
Could also be https://github.com/rust-lang/rust/pull/74386

**Pull request closed without merging**
