### PR TITLE
Fix MIR inlining of asm_unwind

### PR DESCRIPTION
**Pull request by nbdd0121**
The MIR inlining currently doesn't handle inline asm's unwind edge correctly.

This code will cause ICE:
```rust
struct D;

impl Drop for D {
    fn drop(&mut self) {}
}

#[inline(always)]
fn foo() {
    let _d = D;
    unsafe { std::arch::asm!("", options(may_unwind)) };
}

pub fn main() {
    foo();
}
```

This PR fixes this issue. I also take the opportunity to extract common code into a method.

### CODE REVIEW

**Comment by tmiasko** [comment]
Thanks!

**Comment by wesleywiser** [comment]
I believe `options(may_unwind)` is unstable and therefore this fix does not need to be backported to beta. Is that correct?

**Comment by nbdd0121** [comment]
That's correct.

**Comment by wesleywiser** [comment]
Great, thank you! 🙂

**Pull request merged**
