### PR TITLE
std::rand: adding solaris/illumos for getrandom support.

### PR DESCRIPTION
**Pull request by devnexen**
To help solarish support for miri https://https://github.com/rust-lang/miri/issues/3567

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @josephlr who just filed https://github.com/rust-random/getrandom/pull/417

**Review by josephlr — CHANGES_REQUESTED** [review]
Line 62 also needs to be updated to include illumos/solaris so that there's a definition of `getrandom`.

Otherwise, the implementation looks good. For the uses in libstd (generating random hashmap seeds), using `getrandom` with `flags = 0` is definitely the right call (on both illumos and Solaris). You also don't have to worry about maximum buffer size issues on Solaris as you will only be requesting 16 bytes at a time.

**Comment by RalfJung** [comment]
>  For the uses in libstd (generating random hashmap seeds), using getrandom with flags = 0 is definitely the right call (on both illumos and Solaris). You also don't have to worry about maximum buffer size issues on Solaris as you will only be requesting 16 bytes at a time.

Maybe there should be a comment explaining that. It seems confusing that this would use a different function than the getrandom crate.

**Comment by RalfJung** [comment]
This helps with https://github.com/rust-lang/miri/issues/3567.

(@devnexen when you open a PR that is related to some issue, please mention the issue in the PR description. That helps give context to the reviewer, and to whoever is looking at the issue it helps determine the current status. Generally, PRs should almost always have a description that explains what is done and why.)

**Pull request merged**
