### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #127857 (Allow to customize `// TODO:` comment for deprecated safe autofix)
 - #128410 (Migrate `remap-path-prefix-dwarf` `run-make` test to rmake)
 - #128828 (`-Znext-solver` caching)
 - #128873 (Add windows-targets crate to std's sysroot)
 - #129034 (Add `#[must_use]` attribute to `Coroutine` trait)
 - #129049 (compiletest: Don't panic on unknown JSON-like output lines)
 - #129050 (Emit a warning instead of an error if `--generate-link-to-definition` is used with other output formats than HTML)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=127857,128410,128828,128873,129034,129049,129050)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I think something is off with fuschia here. It's been failing a lot lately.


cc @rust-lang/infra

**Comment by MarcoIeni** [comment]
Yes. Discussion [here](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/.E2.9C.94.20Are.20fuchsia.20CI.20jobs.20broken.3F). It should be fixed now 👍

**Comment by GuillaumeGomez** [comment]
Awesome, thanks!

**Pull request closed without merging**
