### PR TITLE
[beta] Beta next

### PR DESCRIPTION
**Pull request by brson**
- https://github.com/rust-lang/rust/pull/40285
- https://github.com/rust-lang/rust/pull/40272
- https://github.com/rust-lang/rust/pull/40064
- https://github.com/rust-lang/rust/pull/39835
- https://github.com/rust-lang/rust/pull/40398

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1000

This is going probably bounce a few times...

**Comment by alexcrichton** [comment]
@bors: retry

* appveyor s3 failure https://github.com/rust-lang/rust/issues/39074

**Comment by alexcrichton** [comment]
@bors: retry

* s3 appveyor upload failure https://github.com/rust-lang/rust/issues/39074

**Comment by alexcrichton** [comment]
@bors: retry

* appveyor network error

**Comment by arielb1** [comment]
- #38878

@bors retry

**Comment by brson** [comment]
Not trying to land this via bors now. Just trying to get travis and appveyor to do a test against the pr.

**Comment by alexcrichton** [comment]
AppVeyor gives a [clean bill of health](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2318)

**Comment by alexcrichton** [comment]
Travis gives a [clean bill of health](https://travis-ci.org/rust-lang/rust/builds/209842520) except for OSX.

The OSX failures are, however, all spurious.

**Pull request merged**
