### PR TITLE
Relax bounds on HashMap/HashSet

### LINKED ISSUE #44777: Unnecessary trait bounds in HashMap (and BTreeMap)
There's a lot of unnecessary trait bounds in `HashMap` that could be pruned.

Examples:

  - `impl Default for HashMap<K, V, S>` really only needs `S: Default`
  - `impl Debug for HashMap<K, V, S>` really only needs `K: Debug` and `V: Debug`
  - Many of the methods only require one out of `K: Eq + Hash` or `S: BuildHasher`, or sometimes neither.

Most of this isn't a big deal, but for `Default` and `Debug` this is a nuisance because you can't use `#[derive(Debug, Default)]` on unconstrained types containing `HashMap`, e.g.

```rust
// won't compile
#[derive(Debug, Default)]
struct MyStruct<K>(HashMap<K>);

// your options are to either:
//
//   - needlessly constrain `K` directly on the struct itself,
//     which then infects everything involving MyStruct
//   - define Debug and Default manually with the redundant constraints;
//     downstream types that contain MyStruct are still screwed
```

One might argue that this would limit potential implementations, but for a lot them like `Default` or `.len()`, no sensible implementation should ever use `K: Eq + Hash` at all.

This also applies to `BTreeMap` to some extent (`Default` doesn't need `Ord`, for example).

Patch: https://github.com/Rufflewind/rust/commit/a1587a17b5807b80b48a6f9b12932cd388af7804

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
These APIs changed from the old bound listed to the new bound (possibly empty):

K: Hash + Eq -> K
* new
* with_capacity

K: Eq + Hash, S: BuildHasher -> K, S
* with_hasher
* with_capacity_and_hasher
* hasher

K: Eq + Hash + Debug -> K: Debug
S: BuildHasher -> S
HashMap as Debug

K: Eq + Hash -> K
S: BuildHasher + Default -> S: Default
HashMap as Default

Resolves #44777.

### CODE REVIEW

**Comment by Amanieu** [comment]
LGTM

@rfcbot fcp merge

**Comment by Mark-Simulacrum** [comment]
Test failure appears to be because it is now possible to create a HashSet from `[u8; 33]` whereas it wasn't before. I will rebless shortly.

**Comment by sfackler** [comment]
What's the rationale for allowing the creation of maps that can't be used?

**Comment by Mark-Simulacrum** [comment]
I think the primary rationale from my perspective (I am not the one who filed the original issue, nor do I have a use case myself) is to allow wrapping HashMap/HashSet in types that don't necessarily want to constrain themselves to using those always. I am not sure that I have a concrete use case -- most things I can come up with would know the type parameters (i.e., not actually be generic).

My loose idea is a type that wants to construct a HashSet/Map eagerly but may not use it except for some use cases (e.g., some graph data structure that caches nodes/edges if you call some methods, but can be used without those methods in some cases).

**Comment by Amanieu** [comment]
@bors r-

Oops, wrong window.

**Comment by alexcrichton** [comment]
IIRC this is a general guideline that we've used for libstd historically, only requiring bounds when absolutely necessary. While there's not much use in creating defunkt objects relaxing the bounds can often make generic programming much easier since you don't have to thread through so many bounds in so many places.

For example `Arc::new` doesn't require `Send+Sync` values, and while `Arc<T>` is more useful than `HashMap<K, V, NotAHasher>` I think roughly the same principle applies.

Now that being said there's also the point to be made of being conservative. I suspect these bounds were actually used at some point and refactorings have since enabled us to not need them. By removing them we're never going to be able to design a hash map where they're required for these methods. That being said the current hash table is quite good, so I suspect we won't have to worry about this too too much.

**Comment by Mark-Simulacrum** [comment]
> That being said the current hash table is quite good, so I suspect we won't have to worry about this too too much.

We already provide `iter()` without requiring anything (i.e., `K`, `V`, and `S` are boundless), so Debug is implementable atop that.

The construction methods are the only ones which are a bit up in the air -- I could see us wanting to use some property of the hasher to decide how much to allocate in the future (e.g., how many "spare bits" we need or so), but I don't think it's a huge concern as I'm not aware of cases where HashMaps specialize for the hasher being used in such a way.

**Comment by withoutboats** [comment]
I'm a bit concerned about doing this but I can't necessarily say why. It's always seemed like we were buying ourselves some cover for future compatibility by only allowing HashMaps to be constructed with hashable keys. I think I'd like to get more user feedback on this change before merging it, try to find if any community members have a compelling reason we shouldn't do this.

**Comment by Mark-Simulacrum** [comment]
@withoutboats Do you want me to pursue that in a material way? I'm not sure where we can ask for user feedback (or who you have in mind, if anyone).

I don't personally have any stake in this either so if we choose to close it, that's fine by me as well, but I'll then also close this issue that spawned this.

**Comment by withoutboats** [comment]
@Mark-Simulacrum Not sure. If no one feels strongly either way, I'd have no concern at all pruning the bounds on things other than constructors.

I'll try to figure out how to get more feedback on the constructors changes.

**Comment by dtolnay** [comment]
https://github.com/rust-lang/rust/pull/67642#issuecomment-573693522 sounds like it's referring to the `K: Eq + Hash` bounds on the constructors. I can't see us needing those because the only thing they do is give the constructor the ability to compare and hash keys, but a constructor would never have access to any keys that it might compare or hash. So if constructors don't possess any keys, anything they can do with an Eq + Hash bound can also be done without the bound.

https://github.com/rust-lang/rust/pull/67642#issuecomment-571191763 refers to the `S: BuildHasher` bound which I suppose is possible could be useful.

**Comment by Mark-Simulacrum** [comment]
A concrete proposal: let's re-add the `BuildHasher` bound, but drop the K/V bounds. I believe no one has given a reason for the K/V bounds (hard to imagine one, too, as keys and values aren't available at that point, not much you can Hash/Eq in that case), but the BuildHasher bound seems potentially useful.

@withoutboats how would you feel about this PR given that?

**Comment by withoutboats** [comment]
> sounds like it's referring to the K: Eq + Hash bounds on the constructors. I can't see us needing those because the only thing they do is give the constructor the ability to compare and hash keys, but a constructor would never have access to any keys that it might compare or hash. 

My point is that you can't construct a hashmap value today unless its are eq and hash. There were previous discussions (a long time ago, so the details are vague to me) in which this seemed to provide some forward compatibility leeway for desirable changes.

**Comment by withoutboats** [comment]
Since no one has brought anything up, I've checked my box, don't block on my vague concern.

**Comment by Mark-Simulacrum** [comment]
Okay, then I believe we are ready to go ahead with this. I'm not sure if @Amanieu meant the original "LGTM" comment as a review as well, so let's do r? @Amanieu for final review

**Comment by matklad** [comment]
For posterity, one specific case where we **don't** want the K: Hash + Eq bound on `new` is the hashbrown-style raw API, like [insert_with_hashing](https://docs.rs/hashbrown/0.7.1/hashbrown/hash_map/struct.RawVacantEntryMut.html#method.insert_with_hasher). It can be used to build this cute interner ([full impl](https://gist.github.com/CAD97/036c700fad1b4b159421eca089783122#file-complete_lib-rs)):

```rust
struct Span { lo: u32, hi: u32 }

struct Interner {
  interned: HashSet<Span>,  // equality & hash is determined by `&self.storage[span]`
  storage: String,
}
````

**Comment by Kixunil** [comment]
Damn, this ship has sailed, but I'm going to bring the argument about why this wasn't that great idea and hope to avoid such thing in the future.

Consider error messages for this program in different versions: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=38b035ac5545bc6fe2d7caa805571067

old: `the trait bound `Foo: std::cmp::Eq` is not satisfied`
new: `no method named `extend` found for struct `std::collections::HashMap<Foo, std::string::String>` in the current scope`

I think the old message was much clearer than the new one. :(

**Comment by dtolnay** [comment]
That would be a diagnostics bug. The program calls extend on a HashMap\<K, V\>. HashMap has an extend method but it requires K: Eq. Diagnostic should say so. Please file an issue to follow up.

**Comment by Kixunil** [comment]
OK, I filed the bug. Just note that these kinds of things become worse when combinators are used, as the resulting type gets complicated and the code that passed a wrong type is far away from the place at which rustc found the issue. This is also the reason why error messages from futures are so difficult to understand. That's why I opened https://github.com/rust-lang/api-guidelines/issues/217

I don't think that there's a general solution to such error messages. If there was, it might be a good reason to stop requiring types in (non-public) function signatures too.

**Pull request merged**
