### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #100556 (Clamp Function for f32 and f64)
 - #100663 (Make slice::reverse const)
 - #100697 ( Minor syntax and formatting update to doc comment on `find_vtable_types_for_unsizing`)
 - #100760 (update test for LLVM change)
 - #100761 (some general mir typeck cleanup)
 - #100775 (rustdoc: Merge source code pages HTML elements together v2)
 - #100813 (Add `/build-rust-analyzer/` to .gitignore)
 - #100821 (Make some docs nicer wrt pointer offsets)
 - #100822 (Replace most uses of `pointer::offset` with `add` and `sub`)
 - #100839 (Make doc for stdin field of process consistent)
 - #100842 (Add diagnostics lints to `rustc_transmute` module (zero diags))

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=100556,100663,100697,100760,100761,100775,100813,100821,100822,100839,100842)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
:sob: 
@bors retry
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: ci-mirrors.rust-lang.org
Error: Process completed with exit code 6.

**Comment by nnethercote** [comment]
Not sure why this was tagged as a regression when there was just a single relevant instruction count regression of 0.20%.

@rustbot label: +perf-regression-triaged

**Comment by rylev** [comment]
@nnethercote the reason this was marked as a regression is because it was considered a mix result (both regressions and improvements). Whether a run is considered mixed vs just an improvement/regression is based on percentages. I believe [this is the relevant calculation](https://github.com/rust-lang/rustc-perf/blob/b863b1abbac72ae79ce2d0a666899a99bdcd7e40/site/src/comparison.rs#L384).

**Pull request merged**
