### PR TITLE
inhibit enum layout optimizations under `#[repr(C)]` or `#[repr(u8)]`

### LINKED ISSUE #40029: #[repr(X)] should inhibit enum layout optimization
This is a regression stable to nightly (breaking nodrop and arrayvec at the moment; not their compilation but their tests, which indicate their implementation is not sound for element types like `&T` or `Vec<T>`).

Found by [cargobomb report](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-02-17/index.html)

Note that the regression applies to enums with `#[repr(u8)]` (and similar) but not `#[repr(C)]`.

PR #25651 was never merged, but it would document this aspect of `#[repr(u8)]`

Evaluating https://github.com/rust-lang/rust/pull/39595 for its impact. Thanks @eddyb for the pointers!

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #40029

### CODE REVIEW

**Comment by nikomatsakis** [comment]
no backport needed -- presuming we land before the next beta is branched

**Comment by eddyb** [comment]
@bors retry
* more S3 fallout?

**Comment by alexcrichton** [comment]
Actual error is:

```
error: failed to execute compile

caused by: failed to spawn child

caused by: Broken pipe (os error 32)

make[3]: *** [bin/not] Error 2
```

I believe it's more sccache flakiness. Not sure why.

**Pull request merged**
