### PR TITLE
Update Clippy, RLS and rustfmt

### PR DESCRIPTION
**Pull request by flip1995**
Update Clippy to rust-lang/rust-clippy@32ee306
Update RLS to rust-lang/rls@0d6f53e
Update rustfmt to rust-lang/rustfmt@d6829d6

r? @Manishearth @oli-obk

### CODE REVIEW

**Comment by flip1995** [comment]
Rebased on master and  re-updated Clippy and RLS

**Comment by Manishearth** [comment]
```
[00:04:16] crate `rustc-ap-syntax` is duplicated in `Cargo.lock`
[00:04:16]   * rustc-ap-syntax 306.0.0 (registry+https://github.com/rust-lang/crates.io-index)
[00:04:16]   * rustc-ap-syntax 366.0.0 (registry+https://github.com/rust-lang/crates.io-index)
[00:04:16] some tidy checks failed
```

**Comment by flip1995** [comment]
Also an update of rustfmt was required. This supersedes #58356 now.

**Comment by Xanewok** [comment]
@flip1995 Could we bump RLS version to https://github.com/rust-lang/rls/commit/6c0bbf5da2f72d5a7b354471c785e97ac3662291? This should still only pull v366 of `rustc-ap-*` crates but most importantly it also changes project layout to monorepo (pulling other `rls-*` crates) and while I tested it locally in Rust repo, I'd like to verify that this works as intended and doesn't break toolstate.

**Comment by flip1995** [comment]
@Xanewok Done!

**Comment by Xanewok** [comment]
```
error[E0277]: the trait bound `std::borrow::Cow<'_, str>: std::convert::From<core::str::EscapeDefault<'_>>` is not satisfiedprobe, termcolor, rustc-serialize, rustc-ap-syntax(build.rs), same-file, num-derive(build.rs), rayon-core(build.rs), hex, ansi...
   --> /home/xanewok/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-graphviz-366.0.0/lib.rs:542:44
    |
542 |                     (&*s).escape_default().into()
    |                                            ^^^^ the trait `std::convert::From<core::str::EscapeDefault<'_>>` is not implemented for `std::borrow::Cow<'_, str>`
    |
    = help: the following implementations were found:
              <std::borrow::Cow<'a, [T]> as std::convert::From<&'a [T]>>
              <std::borrow::Cow<'a, [T]> as std::convert::From<&'a std::vec::Vec<T>>>
              <std::borrow::Cow<'a, [T]> as std::convert::From<std::vec::Vec<T>>>
              <std::borrow::Cow<'a, std::ffi::CStr> as std::convert::From<&'a std::ffi::CStr>>
            and 11 others
    = note: required because of the requirements on the impl of `std::convert::Into<std::borrow::Cow<'_, str>>` for `core::str::EscapeDefault<'_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```
Well, this is unsettling. We need to do another coordinated rustc-ap-* bump to a version that has no more than 12 days it seems due to [this change](https://github.com/rust-lang/rust/commit/7a077804a3a58c93f690e382c86ccd4f1a8850af#diff-5df012de31a1bde391411c75eaa4fbfeR541),

and it seems clippy doesn't compile:
```
[01:15:52] [0m[0m[1m[32m   Compiling[0m clippy_lints v0.0.212 (/checkout/src/tools/clippy/clippy_lints)
[01:15:57] [0m[1m[38;5;9merror[E0599][0m[0m[1m: no method named `node_id_to_type` found for type `&'a rustc::ty::TypeckTables<'tcx>` in the current scope[0m
[01:15:57] [0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/tools/clippy/clippy_lints/src/utils/inspector.rs:130:65[0m
[01:15:57] [0m    [0m[0m[1m[38;5;12m|[0m
[01:15:57] [0m[1m[38;5;12m130[0m[0m [0m[0m[1m[38;5;12m| [0m[0m                println!("local variable of type {}", cx.tables.node_id_to_type(local.hir_id));[0m
```

**Comment by flip1995** [comment]
> and it seems clippy doesn't compile:

I fixed this in rust-lang/rust-clippy#3760. Just waiting for AppVeyor so it can get merged. This PR already points to the commit with the fix.

> We need to do another coordinated rustc-ap-* bump

Is there anything I can do to help with that?

**Comment by Xanewok** [comment]
It actually seems we need [v373](https://crates.io/crates/rustc-ap-graphviz/373.0.0) because it pulls exactly the commit we need: https://github.com/rust-lang/rust/commit/0f949c2fcc696d0260a99196d5e5400c59a26a54

> Is there anything I can do to help with that?

Unfortunately I think we need those changes both in Racer and Rustfmt :(

**Comment by Xanewok** [comment]
I believe versions in https://github.com/Xanewok/rust/commit/fa2b88a16ed235dc7b065df63f983f042d07672f should do the trick now

**Comment by mati865** [comment]
Clippy has broke again: https://github.com/rust-lang/rust-clippy/pull/3762#issuecomment-463539467

**Comment by flip1995** [comment]
@Xanewok The Clippy fix is on it's way: rust-lang/rust-clippy#3762. The Clippy commit in this PR points to the bors automerge commit on the auto branch of Clippy. RLS and rustfmt are updated to the commits of your update-tools branch. 

Let's hope, that this finally works :smile:

**Comment by Xanewok** [comment]
@flip1995 looks like https://github.com/rust-lang/rust-clippy/pull/3762 was merged! :tada: Mind updating Clippy submodule to point to the newest master for completeness' sake?

@bors delegate=flip1995
(I hope I didn't screw up the syntax...)

**Comment by Manishearth** [comment]
It already is since @flip1995 used the bors commit

@bors r+ p=2

**Comment by mati865** [comment]
I believe `CC0-1.0` is acceptable, going to open PR for it ASAP.

**Comment by flip1995** [comment]
I added `constant_time_eq` to the exception list of the tidy tool. This should make it possible to merge this PR. Though I'm not sure if this is the right way to do this.

**Comment by flip1995** [comment]
Updated Cargo.lock again. Let's go for take 5 (or 6?)

Does the delegate still apply?

@bors r=Xanewok

**Comment by mati865** [comment]
Network issue:
```
fatal: Could not parse object '57250b2b8fa63934f80e5376a29f7dcb3f759ad6'.
From https://github.com/servo/webrender
 * branch            master     -> FETCH_HEAD
fatal: Could not parse object '57250b2b8fa63934f80e5376a29f7dcb3f759ad6'.
fatal: unable to access 'https://github.com/servo/webrender/': Could not resolve host: github.com
thread 'main' panicked at 'assertion failed: status.success()', src\tools\cargotest\main.rs:116:13
```

**Comment by kennytm** [comment]
@bors r-

<details><summary>Please update clippy.</summary>

```
[01:09:39] error[E0004]: non-exhaustive patterns: `Const { .. }` not covered
[01:09:39]    --> src\tools\clippy\clippy_lints\src\lifetimes.rs:114:61
[01:09:39]     |
[01:09:39] 114 |     let types = generics.params.iter().filter(|param| match param.kind {
[01:09:39]     |                                                             ^^^^^^^^^^ pattern `Const { .. }` not covered
[01:09:39] 
[01:09:39] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:39]    --> src\tools\clippy\clippy_lints\src\lifetimes.rs:134:79
[01:09:39]     |
[01:09:39] 134 |                     let lifetimes = params.args.iter().filter_map(|arg| match arg {
[01:09:39]     |                                                                               ^^^ pattern `&Const(_)` not covered
[01:09:39] 
[01:09:39] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:39]    --> src\tools\clippy\clippy_lints\src\lifetimes.rs:317:67
[01:09:39]     |
[01:09:39] 317 |                 && !last_path_segment.args.iter().any(|arg| match arg {
[01:09:39]     |                                                                   ^^^ pattern `&Const(_)` not covered
[01:09:39] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\needless_pass_by_value.rs:235:87
[01:09:40]     |
[01:09:40] 235 |                                 .map(|params| params.args.iter().find_map(|arg| match arg {
[01:09:40]     |                                                                                       ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\ptr.rs:236:82
[01:09:40]     |
[01:09:40] 236 |                     if let Some(inner) = params.args.iter().find_map(|arg| match arg {
[01:09:40]     |                                                                                  ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\transmute.rs:498:72
[01:09:40]     |
[01:09:40] 498 |         if let Some(to_ty) = params.args.iter().filter_map(|arg| match arg {
[01:09:40]     |                                                                        ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\types.rs:224:67
[01:09:40]     |
[01:09:40] 224 |         if let Some(ty) = params.args.iter().find_map(|arg| match arg {
[01:09:40]     |                                                                   ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\types.rs:268:81
[01:09:40]     |
[01:09:40] 268 |                         if let Some(ty) = last.args.iter().find_map(|arg| match arg {
[01:09:40]     |                                                                                 ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\types.rs:279:87
[01:09:40]     |
[01:09:40] 279 |                         if let Some(boxed_ty) = last.args.iter().find_map(|arg| match arg {
[01:09:40]     |                                                                                       ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\types.rs:328:53
[01:09:40]     |
[01:09:40] 328 |                             .filter_map(|arg| match arg {
[01:09:40]     |                                                     ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\types.rs:341:53
[01:09:40]     |
[01:09:40] 341 |                             .filter_map(|arg| match arg {
[01:09:40]     |                                                     ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\types.rs:352:77
[01:09:40]     |
[01:09:40] 352 |                         for ty in params.args.iter().filter_map(|arg| match arg {
[01:09:40]     |                                                                             ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\types.rs:388:78
[01:09:40]     |
[01:09:40] 388 |                 if let Some(inner) = params.args.iter().find_map(|arg| match arg {
[01:09:40]     |                                                                              ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]     --> src\tools\clippy\clippy_lints\src\types.rs:2139:41
[01:09:40]      |
[01:09:40] 2139 |                 .filter_map(|arg| match arg {
[01:09:40]      |                                         ^^^ pattern `&Const(_)` not covered
[01:09:40] 
[01:09:40] error[E0004]: non-exhaustive patterns: `&Const(_)` not covered
[01:09:40]    --> src\tools\clippy\clippy_lints\src\use_self.rs:182:82
[01:09:40]     |
[01:09:40] 182 |                     !params.parenthesized && !params.args.iter().any(|arg| match arg {
[01:09:40]     |                                                                                  ^^^ pattern `&Const(_)` not covered
```

</details>

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust-clippy/pull/3786

**Comment by Manishearth** [comment]
Moving this to https://github.com/rust-lang/rust/pull/58571 since I don't want to wait for more things to break

**Pull request closed without merging**
