### PR TITLE
Fix bug in import resolution

### LINKED ISSUE #38535: Type inference regression
Servo compiles with rustc 71c06a56a120a0d5e3b224105ee3e6754f83e5fa 2016-12-18, but not with 439c3128d740af372dae163310f7292e999098e1 2016-12-21. Diff: https://github.com/rust-lang/rust/compare/71c06a56a...439c3128d7

The `style` crate fails to build with:

```rust
error[E0282]: unable to infer enough type information about `E`
  --> /home/simon/projects/servo/components/style/font_face.rs:65:9
   |
65 |         try!(self.family.to_css(dest));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `E`
   |
   = note: type annotations or generic parameter binding required
   = note: this error originates in a macro outside of the current crate
```

The `to_css` method being called here is:

```rust
impl ToCss for FontFamily {
    fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
        // ...
    }
}
```

Its return type is `std::fmt::Result` which is `type Result = std::result::Result<(), std::fmt::Error>;`. This call is in another impl of the same method of the same trait:

```rust
impl ToCss for FontFaceRule {
    fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
        try!(dest.write_str("@font-face { font-family: "));
        try!(self.family.to_css(dest));
        try!(dest.write_str(";"));

        // ...
    }
}
```

Adding an explicit type annotation works around this error, but only to uncover another very similar one, then another. The third one was in code generated by serde’s `derive(Serialize)`, so I gave up that approach.

```rust
        let r: fmt::Result = self.family.to_css(dest);
        try!(r);
```

So far I haven’t managed to reduce a test case smaller than "most of Servo", sorry.

I’m suspicious of 6ea1fbb52bc2f82a78d7b592bdfed2b05e6fb666 (which is part of #38099) because it’s commit message mentions inference. I’m not building a compiler #38099 to confirm.

### LINKED ISSUE #38556: ICE src/librustc/hir/def.rs:139: attempted .def_id() on invalid def: Err
Test case:

```rust
fn main() {}

pub mod a {
    pub struct FontFamily;

    impl FontFamily {
        pub fn to_css(&self) -> ::std::fmt::Result {
            Ok(())
        }
    }
}

macro_rules! reexport {
    () => {
        mod b {
            pub use a;
        }
    }
}

reexport!();

pub mod c {
    use b::a::FontFamily;

    pub fn d(_x: &FontFamily) {}
}
```

Compiles successfully on 58d58c24d, causes an ICE on 551cb0646f. Diff https://github.com/rust-lang/rust/compare/58d58c24d...551cb0646f contains only #38171, CC @jseyfried, @nrc.

Found while trying to minimize #38535, but filed separately since the error message is different and this one has a small test case.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #38535 and fixes #38556.
r? @nrc

### CODE REVIEW

**Comment by SimonSapin** [comment]
Confirm that this PR fixes these issues, I’ve managed to build Servo. Thanks @jseyfried !

**Comment by nox** [comment]
Could this get prioritised?

**Pull request merged**
