### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by alexcrichton**
- Successful merges: #48511, #48549, #48618, #48624, #48651, #48698, #48778, #48787, #48802
- Failed merges: #48669, #48710

### CODE REVIEW

**Comment by alexcrichton** [comment]
Added in #48669 and #48710

@bors: r+ p=100

**Comment by alexcrichton** [comment]
@bors: r+

removed cargo update

**Comment by kennytm** [comment]
`run-pass-fulldeps/issue-15149.rs` Failed on macOS…

```
[01:50:10] ---- [run-pass] run-pass-fulldeps/issue-15149.rs stdout ----
[01:50:10] 	
[01:50:10] error: test run failed!
[01:50:10] status: exit code: 101
[01:50:10] command: "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/run-pass-fulldeps/issue-15149.stage2-i686-apple-darwin"
[01:50:10] stdout:
[01:50:10] ------------------------------------------
[01:50:10] 
[01:50:10] ------------------------------------------
[01:50:10] stderr:
[01:50:10] ------------------------------------------
[01:50:10] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
[01:50:10] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:50:10] 
[01:50:10] ------------------------------------------
[01:50:10] 
[01:50:10] thread '[run-pass] run-pass-fulldeps/issue-15149.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2893:9
[01:50:10] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:50:10] 
[01:50:10] 
[01:50:10] failures:
[01:50:10]     [run-pass] run-pass-fulldeps/issue-15149.rs
```

**Comment by alexcrichton** [comment]
I've added https://github.com/rust-lang/rust/pull/48809 and looks like things are timing out b/c LLVM's cache was invalidated, so...

@bors: p=300

**Comment by alexcrichton** [comment]
@bors: retry

good ol' network issues

**Pull request merged**
