### PR TITLE
Refactor misc. "pure data structures" into their own crate

### PR DESCRIPTION
**Pull request by nikomatsakis**
I'm on a quest to slowly refactor a lot of the inference code. A first step for that is moving the "pure data structures" out so as to simplify what's left. This PR moves `snapshot_vec`, `graph`, and `unify` into their own crate (`librustc_data_structures`). They can then be unit-tested, benchmarked, etc more easily. As a benefit, I improved the performance of unification slightly on the benchmark I added vs the original code.

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
r+ with the nits about comments fixed

**Comment by Manishearth** [comment]
Side discussion: Should `librustc_*` be moved to `librustc/`; having a crate hierarchy sort of thing? Keeps the tree organized, though it might be a pain for makefiles.

**Pull request merged**
