### PR TITLE
refactor clippy in bootstrap

### LINKED ISSUE #122825: `x clippy` implementation is deeply coupled with the core bootstrap
It's not possible to run `x clippy` only on certain paths. When running `x clippy $tool`, clippy starts giving warnings on the entire compiler and library tree as well. Therefore we are unable to run clippy with different set of rules indivudually for each tool/path.

The root cause of this problem is that bootstrap overrides all the commands before invocations with clippy as seen here: https://github.com/rust-lang/rust/blob/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/src/bootstrap/src/core/builder.rs#L1291-L1300

And that is because clippy is sharing the same logic with `x check`: https://github.com/rust-lang/rust/blob/df8ac8f1d74cffb96a93ae702d16e224f5b9ee8c/src/bootstrap/src/core/builder.rs#L770-L783

To prevent this problem we can create a new build step for clippy and then remove clippy-specific conditions from the core bootstrap flow.

### PR DESCRIPTION
**Pull request by onur-ozkan**
Previously, using clippy in bootstrap was not very useful as explained in #122825. In short, regardless of the given path clippy would always check the entire compiler and std tree. This makes it impossible to run clippy on different paths with different set of rules. This PR fixes that by allowing developers to run clippy with specific rules on specific paths (e.g., we can run `x clippy compiler -Aclippy::all -Dclippy::correctness` and `x clippy library/std -Dclippy::all` and none of them will affect each other).

Resolves #122825

### CODE REVIEW

**Comment by onur-ozkan** [comment]
I was planning to run clippy on bootstrap and various other tools on CI, which means I will need to make some more changes to fix clippy warnings. As it makes this PR difficult to review, I will do that as a follow-up to this PR once it's merged.

r? bootstrap

**Review by albertlarsan68 — APPROVED** [review]

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+

**Comment by matthiaskrgr** [comment]
probably failing in https://github.com/rust-lang/rust/pull/124025#issuecomment-2059417187

**Comment by onur-ozkan** [comment]
> probably failing in [#124025 (comment)](https://github.com/rust-lang/rust/pull/124025#issuecomment-2059417187)

Rebased. @bors r=albertlarsan68

**Pull request merged**
