### PR TITLE
Refactor how SwitchInt stores jump targets

### LINKED ISSUE #65693: Consider merging `values` and `targets` fields on MIR `switchInt`?
Writing some kinds of MIR passes that care about `values` and `targets` on `switchInt` can be a bit messy (for example, passes that remove dead branches). @oli-obk has the idea:

> oli: I like it. The actual elimination is a bit convoluted, but I see no way around it. Maybe the values and targets fields of the SwitchInt variant could be merged into a single list, then one could use retain on the list

> oli: the otherwise branch would then need a custom field, but that would be fine I think

> oli: not sure how much other could would be affected by that (I think there's some code that just wants to know about all targets, but that could be helped by creating an accessor function returning an iterator)

### PR DESCRIPTION
**Pull request by jonas-schievink**
Closes https://github.com/rust-lang/rust/issues/65693

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Looks like no noticeable change so far, good. Let's try using `SmallVec` instead of the old setup.

**Comment by jonas-schievink** [comment]
Hmm, instructions went down, but cycles and clocks went up. Not sure if that's just noise.

**Comment by oli-obk** [comment]
cycles and clocks are always the least reliable. The change lgtm and without you mentioning it I wouldn't even have looked at anything but instructions.

@bors r+

**Comment by Mark-Simulacrum** [comment]
Perf results [after landing](https://perf.rust-lang.org/compare.html?start=abbdec3be6cfce1175d0dc6737a2999cf43b530d&end=afb4514c099fde6e3102373602bea9e6dacd4f88&stat=wall-time) are about as expected; I agree with @oli-obk that I would not want to change anything here and I think investigating is not warranted to prioritize right now.

**Pull request merged**
