### PR TITLE
Stabilize Duration::MAX

### PR DESCRIPTION
**Pull request by workingjubilee**
Following the suggested direction from https://github.com/rust-lang/rust/issues/76416#issuecomment-817278338, this PR proposes that `Duration::MAX` should have been part of the `duration_saturating_ops` feature flag all along, having been

0. heavily referenced by that feature flag
1. an odd duck next to most of `duration_constants`, as I expressed in https://github.com/rust-lang/rust/issues/57391#issuecomment-717681193
2. introduced in #76114 which added `duration_saturating_ops`

and accordingly should be folded into `duration_saturating_ops` and therefore stabilized.

r? @m-ou-se

### CODE REVIEW

**Comment by m-ou-se** [comment]
@rfcbot merge

(@workingjubilee can you rebase this? The first commit should now be included in the main branch.)

**Comment by workingjubilee** [comment]
Rebased!

**Comment by workingjubilee** [comment]
I have added a small remark clarifying that `Duration::MAX` may vary by platform, because `std` uses it for creating differences between `time::Instant`s (and so should fit such, and so the repr may vary slightly), so that this stabilization does not have to _unnecessarily_ constrain future adjustments to Duration's representation.

**Comment by m-ou-se** [comment]
> I have added a small remark clarifying that `Duration::MAX` may vary by platform, because `std` uses it for creating differences between `time::Instant`s (and so should fit such, and so the repr may vary slightly), so that this stabilization does not have to _unnecessarily_ constrain future adjustments to Duration's representation.

Considering we already have a stable `Duration::new()` accepting a `u64` for the seconds, I think we can safely guarantee it's at least 584,942,417,355 years. Otherwise it might seem like on 32 bit platforms MAX could be much lower.

**Comment by workingjubilee** [comment]
I removed the "64-bit" implication part of the remark, because you're completely right that it's not actually dependent on the target's hardware bitness.

Currently you can input values into `Duration::new` that cause it to panic already, and the nanoseconds may not actually matter on a given OS once you interact with it in any way. Duration is not unique in this: `Vec::with_capacity` is supposed to be abstract but you can't reserve more memory than you actually have, and File-oriented APIs use `u64` or `i64` even though 16777216 TiB (`u64::MAX` bytes) exceeds the 2 TiB capacity of the filesystems of most 32-bit targets.

But people expect that. Duration, however, is _supposed_ to be platform-agnostic, but it is actually Not, because `std` implicitly relies on the assumption that the range of Duration > range of Instant, and 128-bit numbers and their use are not a hypothetical anymore. I think if that assumption breaks in one direction, it is also worth reviewing whether it should still be valid in the other direction, or at least waiting and seeing for a little bit while the Year 2038 problem [and migrations because of it](https://github.com/rust-lang/libc/issues/2084) [remains an issue for current tier 2 targets](https://github.com/rust-lang/libc/issues/1848) and [the nature of other types `std::time` remains slightly underdocumented](https://github.com/rust-lang/rust/issues/79881).

**Comment by m-ou-se** [comment]
Yeah the situation is a bit weird with `Duration` sitting in `core` trying to be platform-independent, while `std` provides functions such as `SystemTime::duration_since` that can't report an overflow without panicking.

I don't think this description is very useful though:

>  At least equal to the number of seconds difference between the minimum and maximum std::time::Instant.

Because we don't provide any way to construct arbitrary big `Instant`s other than by sleeping for millions of years or adding a `Duration` to an `Instant`. The concept of a maximum and minimum `Instant` doesn't really have much meaning right now.

How about we just say that it might vary by platform, but right now it's 584,942,417,355 years on all platforms?

**Comment by workingjubilee** [comment]
I'm good with that! It sounds like the appropriate mix of Ominous and Reassuring.
You're right that "minimum" and "maximum" are erroneous concepts for Instant, I was thinking of it too much like an integer. I tried to reflect the actual details that might impact the value of MAX :
```rust
    /// May vary by platform as necessary. Must be able to contain the difference between
    /// two instances of [`Instant`] or two instances of [`SystemTime`].
    /// This constraint gives it a value of about 584,942,417,355 years in practice,
    /// which is currently used on all platforms.
```

**Comment by JohnTitor** [comment]
```
2021-04-26T11:14:16.8477608Z curl: (56) OpenSSL SSL_read: Connection was reset, errno 10054
2021-04-26T11:14:16.8525720Z 
2021-04-26T11:14:16.8526973Z gzip: stdin: unexpected end of file
2021-04-26T11:14:16.8528023Z tar: Unexpected EOF in archive
2021-04-26T11:14:16.8529006Z tar: Unexpected EOF in archive
2021-04-26T11:14:16.8530077Z tar: Error is not recoverable: exiting now
```

@bors retry

**Pull request merged**
