### PR TITLE
[DO NOT MERGE] Try setting __rust_probestack visibility back to hidden

### LINKED ISSUE #68794: TEXTREL in i686 since 1.41.0
Hello,

I'm in the process of upgrading Rust to 1.41.0 on Alpine Linux and it appears that a TEXTREL has been introduced in 1.41.0:

```
TEXTREL /usr/lib/librustc_macros-4cbed8a36ab240e8.so
```

The full build log is located here if it's of interest: https://gitlab.alpinelinux.org/Cogitri/aports/-/jobs/44396

### PR DESCRIPTION
**Pull request by tmandry**
This is to fix https://github.com/rust-lang/rust/issues/68794, but it may break some platforms. Uploading this change to test in CI.

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Try by default is just Linux, which seems unlikely to break (presumably you tested on it already). You can enable other builders - though please avoid more than 4 at a time total - by copying from src/ci/azure-pipelines/auto.yml to try.yml.

**Comment by tmandry** [comment]
Tests were successful, closing this in favor of the "real" change, https://github.com/rust-lang/rust/pull/69086.

**Pull request closed without merging**
