### PR TITLE
Allow slices to be used in field

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm not sure that these changes are backwards-compatible, and also seem to go against the reason for using a trait object (making the output code small). Why are we making this change? What specifically does it allow; what are the tradeoffs?

Overall, I don't think I'm the best reviewer for this, maybe r? @dtolnay 

Looks like Travis failed, too.

**Review by dtolnay — COMMENTED** [review]
For the gstreamer-sys change, would it work to use `&&self.v[..]` instead of `&self.v as &[i32]`? [Playground](https://play.rust-lang.org/?gist=8370c160763a6f298fe5113d950d8855)

**Comment by GuillaumeGomez** [comment]
@dtolnay: it would indeed, but sounds more like a trick. :-/ At least, with this, it'd be more "logical" (if we could combine trait objects, it'd be even simpler).

@Mark-Simulacrum: It fails because a test supposed to fail is now passing.  Also, I have no issue having a debate over this PR. It was just a fix for a specific situation after all.

**Comment by dtolnay** [comment]
I would prefer to stick with `&&self.v[..]` for now and follow up with the real fix which is allowing dynamically sized types to be trait objects. That may allow `&self.v as &[i32]` without this change. All of std::fmt uses trait objects extensively to help compile times and executable sizes.

**Comment by GuillaumeGomez** [comment]
That'd be awesome! Any follow-up issue for dynamically sized trait objects?

**Comment by dtolnay** [comment]
Hmm, it may be https://github.com/rust-lang/rfcs/issues/2035 with something like `&(Debug + ?Sized)` but I'm not sure.

**Comment by dtolnay** [comment]
Another possible fix would be a deref coercion where `&DynamicallySizedType` coerces to `&TraitObject` by implicitly doing `&` twice.

```rust
use std::fmt::Debug;

fn f(_trait_object: &Debug) {}

fn main() {
    f("str"); // does not compile today. would coerce to &&str
    f(&[1][..]); // does not compile today. would coerce to &&[{integer}]
}
```

That would also make `&self.v as &[i32]` work without changing the signature of DebugStruct::field. I filed https://github.com/rust-lang/rfcs/issues/2239 to follow up.

**Pull request closed without merging**
