### PR TITLE
rustdoc: Use conditional for _stripped fold

### PR DESCRIPTION
**Pull request by notriddle**
Followup: https://github.com/rust-lang/rust/pull/90475#discussion_r741405472

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by camelid** [comment]
`r=camelid,GuillaumeGomez` with CI passing

@bors rollup=never

**Review by camelid — APPROVED** [review]

**Comment by camelid** [comment]
@bors r=camelid,GuillaumeGomez rollup=never

(rollup=never because this may affect perf)

**Comment by camelid** [comment]
Hmm, this change actually caused some minor regressions.

**Pull request merged**
