### PR TITLE
trpl: Proofread "Rust Inside Other Languages"

### PR DESCRIPTION
**Pull request by zaeleus**
r? @steveklabnik

### CODE REVIEW

**Comment by zaeleus** [comment]
I can't seem to add a line comment to unchanged lines, but this is for [L140](https://github.com/zaeleus/rust/commit/49018c02ef98c0181b6267794c98befdcbcbec8d#diff-dacdbd83095596b4e3937b33387a6ec9L140).

> That first warning is because we are building a library. If we had a test
> for this function, the warning would go away. But for now, it’s never
> called.

Is this correct? Adding a test for `process()` would only affect `cargo test`, not `cargo build`.

**Comment by steveklabnik** [comment]
Hey @zaeleus , thanks for this patch!

I don't know how you made your comments, because they don't show up in the diff tab :/ i'll try to add more inline. also, as @bors mentions, this will need a rebase.

**Comment by steveklabnik** [comment]
Thank you! I have some nits, but otherwise, this looks great :)

**Comment by pnkfelix** [comment]
I'm going to assume that all of the nits have been addressed, since it seems like the commit has been rebased.  @steveklabnik , let me know my forthcoming r+ is off-base (given your prior comment).

**Comment by steveklabnik** [comment]
@pnkfelix :+1:

**Pull request merged**
