### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #126618 (Mark assoc tys live only if the corresponding trait is live)
 - #126746 (Deny `use<>` for RPITITs)
 - #126868 (not use offset when there is not ends with brace)
 - #126884 (Do not ICE when suggesting dereferencing closure arg)
 - #126893 (Eliminate the distinction between PREC_POSTFIX and PREC_PAREN precedence level)
 - #126915 (Don't suggest awaiting in closure patterns)
 - #126943 (De-duplicate all consecutive native libs regardless of their options)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=126618,126746,126868,126884,126893,126915,126943)

### CODE REVIEW

**Comment by tgross35** [comment]
Looks like gh networks are being a bit flaky currently, https://github.com/rust-lang/rust/pull/126955 failed too for something similar

**Comment by workingjubilee** [comment]
there are already now more than 7 rollup=always PRs.

**Comment by matthiaskrgr** [comment]
:thinking:  and?

**Comment by pnkfelix** [comment]
* regressions are all to serde incr-patched:println {check, debug, opt}.
* on its own, the regression is limited to instruction counts, and seems minor enough to not warrant deeper investigation.
* marking as triaged

**Pull request merged**
