### PR TITLE
New path of method offset

### PR DESCRIPTION
**Pull request by therustmonk**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think this is referring to [this function](http://doc.rust-lang.org/stable/std/primitive.pointer.html#method.offset), and while `ptr::offset` may not be 100% correct I think it's probably a little more right than `pointer::offset`. Perhaps this could be `<*mut T>::offset`?

**Comment by DenisKolodin** [comment]
I guess you were right! But there is also `* const`. Which implementation to prefer? All roads leads to `intrinsics::offset`. But `<T>` hints at the size, it's better. Do you want I'll rebase it to `<*mut T>::offset`?

**Comment by alexcrichton** [comment]
Yeah seems fine to mention `*const` as well, it's basically just saying the `offset` method on raw pointers (which would also be fine to just say in words)

**Comment by DenisKolodin** [comment]
What do you think about this explanation? I think it don't incite reader to search a non existent qualified path.

**Comment by alexcrichton** [comment]
@bors: r+ 5736c1d90ad89a72d217762d74fe53907448a558

Looks good to me!

**Pull request merged**
