### PR TITLE
Stabilize exclusive_range_pattern (v2)

### PR DESCRIPTION
**Pull request by dtolnay**
This PR is identical to #124459, which was approved and merged but then removed from master by a force-push due to a [CI bug](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/ci.20broken.3F).

r? ghost

Original PR description:

---

Stabilization report: https://github.com/rust-lang/rust/issues/37854#issuecomment-1842398130
FCP: https://github.com/rust-lang/rust/issues/37854#issuecomment-1872520294

Stabilization was blocked by a lint that was merged here: #118879

Documentation PR is here: rust-lang/reference#1484

@rustbot label +F-exclusive_range_pattern +T-lang

### CODE REVIEW

**Comment by dtolnay** [comment]
r? Nadrieril

**Comment by dtolnay** [comment]
We can copy the approval from https://github.com/rust-lang/rust/pull/124459#issuecomment-2094293242, right?

@bors r=davidtwco

**Comment by Nadrieril** [comment]
Thanks for doing this!

**Comment by RossSmyth** [comment]
Thanks!

**Pull request merged**
