### PR TITLE
Introduce `as_deref` to Option

### PR DESCRIPTION
**Pull request by JohnTitor**
This is re-submission for #59628.
Renames `deref()` to `as_deref()` and adds `deref_mut()` impls and tests.

CC #50264 

r? @Kimundi 
(I picked you as you're the previous reviewer.)

### CODE REVIEW

**Comment by JohnTitor** [comment]
Rebased

@rustbot modify labels: +S-waiting-on-review and -S-waiting-on-author

**Comment by Alexendoo** [comment]
Ping from triage, any updates? @Kimundi

**Comment by Dylan-DPC** [comment]
can anyone from @rust-lang/libs review this?

**Comment by alexcrichton** [comment]
Sorry for the delay @JohnTitor!

**Comment by H2CO3** [comment]
An interesting problem this should somehow solve but doesn't is converting `Option<&T>` to `Option<&<T as Deref>::Target>`. E.g. the following doesn't compile with the error saying that it's expecting a `str` but got a `String`:

[Playground link](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=6844a984f0215c1a4ff8c9ff66f209f1)

**Pull request merged**
