### PR TITLE
Prefer visibility map parents that are not `doc(hidden)` first

### PR DESCRIPTION
**Pull request by compiler-errors**
Far simpler approach to #98876.

This only fixes the case where the parent is `doc(hidden)`, not where the child is `doc(hidden)` since I don't know how to get the attrs on the import statement given a `ModChild`... I'll try to follow up with that, but this is a good first step.

### CODE REVIEW

**Comment by cjgillot** [comment]
The best way to access the attributes on a `ModChild` would probably to add a `DefId` to the `ModChild`.
In the mean time, this implementation looks good enough.
@bors r+

**Comment by jyn514** [comment]
> This only fixes the case where the parent is `doc(hidden)`, not where the child is `doc(hidden)` since I don't know how to get the attrs on the import statement given a `ModChild`... I'll try to follow up with that, but this is a good first step.

not sure how hard this is in rustc_metadata, but rustdoc does it like so: https://github.com/rust-lang/rust/blob/e1d1848cc60a407d06f90fd16877a19bed6edd9b/src/librustdoc/visit_ast.rs#L51

**Comment by pnkfelix** [comment]
@compiler-errors any chance that this contributed to the regression reported in https://github.com/rust-lang/rust/pull/99792#issuecomment-1196405997 ?

**Comment by compiler-errors** [comment]
Yes very likely.

**Pull request merged**
