### PR TITLE
Use mtijink's CGU size estimation function.

### PR DESCRIPTION
**Pull request by nnethercote**
r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
Walltime, max-rss, and binary size are metrics of interest here. Overall there are more regressions than improvements, so this doesn't seem worth doing.

**Comment by apiraino** [comment]
@nnethercote are you interested in another approach here, do you want to discuss the design or ... you just want to close it? :)

@rustbot author

**Comment by nnethercote** [comment]
Oh, this is a dead end, I think.

**Pull request closed without merging**
