### PR TITLE
No longer mark RTN as incomplete

### PR DESCRIPTION
**Pull request by compiler-errors**
The RFC is accepted and the feature is basically fully implemented. This doesn't mean it's necesarily *ready* for stabiliation; there's probably some diagnostic improvements to be made, and as always, users uncover the most creative bugs.

But marking this feature as incomplete no longer serves any purpose, so let's fix that.

### CODE REVIEW

**Comment by jackh726** [comment]
This would be a good time to make a blog post announcing the feature as ready for testing.

**Comment by compiler-errors** [comment]
@jackh726: That's the plan. Lifting this warning is important so that people don't test out the feature and are immediately nagged that the feature is not complete yet.

**Comment by jackh726** [comment]
cool, I'm looking forward to that!

@bors r+

**Pull request merged**
