### PR TITLE
Update LLVM to rust-llvm-2015-01-30

### PR DESCRIPTION
**Pull request by dotdash**

### CODE REVIEW

**Comment by dotdash** [comment]
@lucab Just a heads up because I saw you were likely also working on updating LLVM.

**Comment by dotdash** [comment]
There's a bug left in the debug info part. I updated `RustWrapper.cpp` to expose the underlying`LLVMMetadataRef` type, but the C API expects that to be wrapped in `MetadataAsValue`. The missing wrapping triggers an assertion compiling a run-pass test. I'll not get to fix that today, so I close this and will open a new PR when that's fixed.

**Comment by lucab** [comment]
@dotdash thanks. I'm not touching it right now, but you may want to coordinate with @michaelwoerister on #21512.

**Comment by michaelwoerister** [comment]
@dotdash Did you also run into an assertion in `LLVMSetMetadata()` at https://github.com/rust-lang/rust/blob/master/src/librustc_trans/trans/asm.rs#L153? I wasn't able to find out what the problem was there because everything looked like it should work. But maybe I introduced a bug somewhere along the way myself.

Feel free to cc me if you are discussing any debuginfo problems.

**Comment by dotdash** [comment]
@michaelwoerister That was a regression in LLVM which I fixed upstream, it's in the new rust-llvm snapshot I made yesterday.

**Comment by michaelwoerister** [comment]
@dotdash That's great. I thought that that might be the problem, but overlooked the part where the MDNode indirection was stripped away.

**Pull request closed without merging**
