### PR TITLE
Escape string literals when fixing overlong char literal

### LINKED ISSUE #103323: "Use double quotes" suggestion turns overlong char literal into unterminated string literal
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ffec1b4fc6294dc7bed929e256e73b47)):

```rust
fn main() {
    let _s = '"""';
}
```

The current output is:

```
error: character literal may only contain one codepoint
 --> src/main.rs:2:14
  |
2 |     let _s = '"""';
  |              ^^^^^
  |
help: if you meant to write a `str` literal, use double quotes
  |
2 |     let _s = """"";
  |              ~~~~~
```

Ideally the suggestion should look like:

```
help: if you meant to write a `str` literal, use double quotes
  |
2 |     let _s = "\"\"\"";
  |              ~~~~~~~~
```

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #103323

@rustbot label +A-diagnostics +A-suggestion-diagnostics

### CODE REVIEW

**Comment by clubby789** [comment]
Also fixing the case of `let _: char = "'"` becoming `let _: char = '''`

**Comment by compiler-errors** [comment]
Hm, this doesn't handle the case where we have already have an escaped literal like `"\'"`, right?

**Comment by compiler-errors** [comment]
Also, can you remove the intermediate commits like 51f2826f7fc866c29842cc541684dd6ce066ba88 where you tried something and it didn't end up working out? It's not useful to keep those in the commit history, imo.

**Comment by compiler-errors** [comment]
Thanks @bors r+ rollup

**Pull request merged**
