### PR TITLE
[crater] Try enabling `-Zgcc-ld=lld`

### PR DESCRIPTION
**Pull request by lqd**
To make progress towards using `lld`, this PR will test a `build-and-test` crater run enabling `-Zgcc-ld`, to see if it would cause issues on `x86_64-unknown-linux-gnu`.

### CODE REVIEW

**Comment by lqd** [comment]
Tested locally with a helloworld, `cargo clean && cargo +1b74e096b9bfb06f84a3007193dcd2f059cbdf6a build -q && readelf -p .comment target/debug/helloworld` seemed to work as expected:

```
String dump of section '.comment':
  [     0]  Linker: LLD 14.0.0
  [    13]  GCC: (Debian 10.2.1-6) 10.2.1 20210110
```

I'll run it over our extended benchmark suite.

In the mean time, we can make it go through the perf collector to see if something goes horribly wrong with the benchmarks that do involve linking.

@rust-timer build 1b74e096b9bfb06f84a3007193dcd2f059cbdf6a

**Comment by lqd** [comment]
According to https://github.com/rust-lang/compiler-team/issues/510#issuecomment-1102741002 there should be at least a few projects with incorrect `build.rs` even on x64 linux.

@craterbot run mode=build-and-test

The crater queue is empty enough that this won't delay anyone now. It can be de-prioritized if anyone has a more pressing run to do, like the ones for the betas.

**Comment by lqd** [comment]
And since the queue is still empty, let's now check for flakiness in the fixed cases.

@craterbot run mode=build-and-test crates=https://gist.githubusercontent.com/lqd/03ab4552c58faa97ff33a9b3f2f1dc68/raw/5427f95aa75dfb1e01202d9864641b96cf5ac015/pr-96025-retry-fixed-list.txt

**Comment by Mark-Simulacrum** [comment]
I'm going to close this PR but we can always reopen and re-run crater when/if needed, seems like we finished the initial collection though.

**Pull request closed without merging**
