### PR TITLE
Lexer tweaks

### PR DESCRIPTION
**Pull request by nnethercote**
Some cleanups and small performance improvements.

r? @chenyukang

### CODE REVIEW

**Comment by clubby789** [comment]
Doesn't seem to have triggered perf
@rust-timer build 3b5567919664e9283903559336c92c070a13f4b4

**Comment by marxin** [comment]
@nnethercote

After this PR, I noticed there are some broken links in the `rustc-dev-guide`:

```
exec mdbook-linkcheck2 
error: Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html
    ┌─ guides/editions.md:107:8
    │
107 │ Within [`StringReader`], tokens can be modified based on edition-specific behavior.
    │        ^^^^^^^^^^^^^^^^ Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html

error: Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html
   ┌─ overview.md:53:1
   │
53 │ [`StringReader`] `struct` is used at this stage to perform a set of validations
   │ ^^^^^^^^^^^^^^^^ Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html

error: Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html
   ┌─ the-parser.md:55:6
   │
55 │ both [`StringReader`] and [`Parser`] have lifetimes which bind them to the parent [`ParseSess`].
   │      ^^^^^^^^^^^^^^^^ Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html

error: Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html
   ┌─ the-parser.md:70:3
   │
70 │ - [`StringReader`] integrates [`rustc_lexer`] with data structures specific to
   │   ^^^^^^^^^^^^^^^^ Server returned 404 Not Found for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/lexer/struct.StringReader.html
```

Can you please take a look?

**Comment by nnethercote** [comment]
@marxin: sorry for the slow response, I just got back from vacation. I see the broken links have already been fixed in https://github.com/rust-lang/rustc-dev-guide/pull/2208.

**Pull request merged**
