### PR TITLE
Remove pretty-print compat hack for all crates

### PR DESCRIPTION
**Pull request by Aaron1011**
This PR removes the pretty-printing hack that changed how we printed types named `ProceduralMasqueradeDummyType`. This was added in https://github.com/rust-lang/rust/pull/73345, to avoid causing widespread ecosystem breakage in the ecosystem while making a change to proc-macro invocation,

It's been around a year and a half, and all of the affected crates have new versions out which no longer require this hack to compile. The crater run in https://github.com/rust-lang/rust/pull/93275#issuecomment-1024820474 (https://crater-reports.s3.amazonaws.com/pr-93275/index.html) shows three sources of regressions:

* The `rental` crate - while this crate is now unmaintained, its final versions `0.5.6` has a fix that allows us to compile without this hack. All affected crates should be able to bump their `Cargo.lock` to the latest version.
* The `cssparser` crate - this crate is still maintained, and all recent versions no longer depend on `procedural-masquerade` (which is what panicked without this workaround).
* `allsorts-rental` - this appears to be a fork of `rental` created by the `allsorts` projects (https://github.com/yeslogic/allsorts/pull/42). Confusingly, it has a version called `0.5.6` which is *not* the same as `rental` 0.5.6. However, the `allsorts` project no longer depends on `rental` since https://github.com/yeslogic/allsorts/commit/7b51ea85e27004b55ebdc86e60da24f149503fb5, so I think this crate is essentially a legacy from crates that haven't yet updated their `Cargo.lock`

Unfortunately, there are still 231 crates that transitively depend on one of these 3 crates. The vast majority of these crates appear to be small personal projects with their `Cargo.lock` committed. At this point, I think that waiting longer won't decrease the amount of breakage - the authors of these crates are probably not running the latest Rust, and will therefore not see the future-incompat-report message.

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
cc @rust-lang/lang @petrochenkov 

I propose that we remove this hack. The description of this PR contains a description of what this does, and what the expected fallout from removing this is.

If the amount of fallout is still judged to be too high, then I think we could 'partially' remove this - disable the hack on nightly, but revert it on beta. This should help catch any actively maintained projects that are depending on this (and are ignoring the cargo future-incompat-report message), while keeping our stable releases 'stable' for a little while longer.

**Comment by scottmcm** [comment]
Over a year seems like long enough to keep a "we were being nice" hack tome; let's see what everyone else thinks.

@rfcbot merge

**Comment by Aaron1011** [comment]
I think changes to the proc-macro infrastructure are generally handled by the compiler team. However, this will result in some amount of ecosystem breakage, so I wanted to see if the lang team had any objections.

**Comment by Mark-Simulacrum** [comment]
The future compatibility lint support will only land in 1.59 in Cargo, right? So stable users aren't seeing those warnings yet?

Can you confirm that in all cases (as found by Crater) we expect a cargo update -p some-crate to fix the issue? Can we change to a hard error, but with that recommendation for a cycle or so? In any case, it would be great to have the PR description contain the instructions for each case in a short snippet we can copy into release notes.

**Comment by camelid** [comment]
> The future compatibility lint support will only land in 1.59 in Cargo, right? So stable users aren't seeing those warnings yet?

triage: It's been several versions since 1.59, so it seems like this PR may be ready to be revisited.

**Comment by Aaron1011** [comment]
I'm trying a more minimal version of this in https://github.com/rust-lang/rust/pull/94063

**Comment by camelid** [comment]
Should this PR be closed since it's being superseded?

**Comment by Aaron1011** [comment]
This should be merged eventually, but it might need more time depending on the results of the other PR.

**Comment by jackh726** [comment]
Marking as blocked on #94063

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by jackh726** [comment]
@Aaron1011 I assume you'll triage the crater run and figure out if we can land this

**Comment by Aaron1011** [comment]
@craterbot check crates=list:https://crater-reports.s3.amazonaws.com/pr-93275/retry-regressed-list.txt

**Comment by Aaron1011** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-93275/retry-regressed-list.txt

**Comment by ForrestOfBarnes** [comment]
Any progress on this? Removing the pretty-print hack would remove one of the last two instances of Token::Interpolated in the entire compiler.

**Comment by Dylan-DPC** [comment]
Closing this as the crater run still needs to be triäged and it's inactive for a while now

**Pull request closed without merging**
