### PR TITLE
Use SOCK_CLOEXEC and accept4() on more platforms.

### PR DESCRIPTION
**Pull request by de-vri-es**
This PR enables the use of `SOCK_CLOEXEC` and `accept4` on more platforms.

-----

Android uses the linux kernel, so it should also support it.

DragonflyBSD introduced them in 4.4 (December 2015):
https://www.dragonflybsd.org/release44/

FreeBSD introduced them in 10.0 (January 2014):
https://wiki.freebsd.org/AtomicCloseOnExec

Illumos introduced them in a commit in April 2013, not sure when it was released. It is quite possible that is has always been in Illumos:
https://github.com/illumos/illumos-gate/commit/5dbfd19ad5fcc2b779f40f80fa05c1bd28fd0b4e
https://illumos.org/man/3socket/socket
https://illumos.org/man/3socket/accept4

NetBSD introduced them in 6.0 (Oktober 2012) and 8.0 (July 2018):
https://man.netbsd.org/NetBSD-6.0/socket.2
https://man.netbsd.org/NetBSD-8.0/accept.2

OpenBSD introduced them in 5.7 (May 2015):
https://man.openbsd.org/socket https://man.openbsd.org/accept

### CODE REVIEW

**Comment by m-ou-se** [comment]
> NetBSD introduced them in 6.0 (Oktober 2012) and 8.0 (**July 2018**):

Looks like the CI uses a NetBSD from March 2018:
https://github.com/rust-lang/rust/blob/9a13ef2251531d5856ca62dd8822c9b8139f479a/src/ci/docker/host-x86_64/dist-x86_64-netbsd/build-netbsd-toolchain.sh#L31

**Comment by de-vri-es** [comment]
Also note that NetBSD 7 is no longer supported since June 30 2020: https://www.netbsd.org/releases/formal.html#previous

So assuming 8.0 or later should be fine I think.

**Comment by m-ou-se** [comment]
Alright, sounds good. Let's see if it passes the CI. :)

@bors r+

**Comment by m-ou-se** [comment]
This failed in https://github.com/rust-lang/rust/pull/78589#issuecomment-719890827

@bors r-

**Comment by de-vri-es** [comment]
Interesting. The libc for Android (bionic) has had `accept4()` since API level 21:
https://android.googlesource.com/platform/bionic/+/refs/heads/master/docs/status.md

That corresponds to Android 5.0. So should we update the minimum android API level in CI or just not use `accept4()` on Android?

**Comment by de-vri-es** [comment]
Submitted #78601 to see if we can update the Android API level for CI. If not, I'll just remove Android from the list for `accept4()`.

**Comment by de-vri-es** [comment]
https://github.com/rust-lang/libc/pull/1968 got merged. Once it is released I'll update this PR.

**Comment by de-vri-es** [comment]
Apparently `std` can't simply update the libc crate because of backwards compatibility issues in the libc crate, so I just removed the use of `accept4` for Android for now.

It can be added again later when `libc` can be updated to a version with the fix.

**Comment by m-ou-se** [comment]
I suppose you could also just use `syscall(SYS_accept4, ..)` directly on Android then, until the libc issues are resolved.

**Comment by de-vri-es** [comment]
Good point, applied the same workaround here :)

**Pull request merged**
