### PR TITLE
Stabilize the `core::panic` module

### PR DESCRIPTION
**Pull request by SimonSapin**
`std::panic` is already stable.

`core::panic::PanicInfo` and `core::panic::Location` are stable and can be used through that path because of a bug in stability checking: #15702

### CODE REVIEW

**Comment by SimonSapin** [comment]
@rfcbot fcp merge

**Comment by SimonSapin** [comment]
Checkbox ping @Kimundi  @KodrAus @sfackler

**Comment by petrochenkov** [comment]
semi-offtopic: I haven't seen Kimundi participating for years (?) does it still make sense to ping him?

**Pull request merged**
