### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by matklad**
r? @ghost

### CODE REVIEW

**Comment by tmandry** [comment]
Yielding to rollup
@bors retry

**Comment by matklad** [comment]
spurious 

@bors r+

@Dylan-DPC rust-analyzer specifically is fine to rollup: it doesn’t depend on nightly features (so it is unlikely to fail the build) and it is not a critical part of infra yet (unlike cargo).

**Comment by matklad** [comment]
logs look like the CI didn't really run, and UI says that the build was cancelled by alexcrichton, so I assume this is spurious/yield as well

@bors retry

**Comment by mati865** [comment]
Clang could not be downloaded like in couple other PRs: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Installing.20Clang.20on.20CI.20fails

**Pull request merged**
