### PR TITLE
Build Fuchsia on 8 cores instead of 16

### PR DESCRIPTION
**Pull request by tmandry**
Requested in https://github.com/rust-lang/rust/pull/117771#discussion_r1421428277.

r? @tmandry

### CODE REVIEW

**Comment by tmandry** [comment]
Baseline is about 38m.

@bors try

**Comment by tmandry** [comment]
This causes the build to take just over an hour, so probably not worth it...

**Comment by Mark-Simulacrum** [comment]
The 16 core runner is 2x the cost of a 8 core runner, so if the build time isn't <=1/2 with 16 cores this is worth it. Just over an hour to me sounds like we're probably in the worth it range?

**Comment by tmandry** [comment]
@Mark-Simulacrum Hmm ok, well we should consider it alongside #119399 which finds more bugs but also increases the build time to 50m. Combining the two would probably make it too slow...

**Comment by tmandry** [comment]
I guess we should find out :)

@bors try

**Comment by tmandry** [comment]
@Mark-Simulacrum How would you feel about 1h 21m? Judging by recent builds, it looks like it's still over 30m away from being the long pole...

**Comment by tmandry** [comment]
Continuing in https://github.com/rust-lang/rust/pull/120358.

**Pull request closed without merging**
