### PR TITLE
Record proc macro harness order for use during metadata deserialization

### LINKED ISSUE #68690: Re-exported proc-macros are documented incorrectly
When multiple proc-macros are re-exported, their documentation is permuted in such a way that the docs for one macro become the docs for another. For a specific case, consider Rocket's proc-macros, defined in earnest in the `rocket_codegen` crate. The documentation for the `rocket_codegen` crate, which is rendered correctly and as expected, looks like:

```
|-----------------|----------------------------------------------------------|
| async_test      |                                                          |
| catchers        | Generates a Vec of Catchers from a set of catcher paths. |
| routes          | Generates a Vec of Routes from a set of route paths.     |
| uri             | Type safe generation of route URIs.                      |
| catch           | Attribute to generate a Catcher and associated metadata. |
| delete          | Attribute to generate a Route and associated metadata.   |
| get             | Attribute to generate a Route and associated metadata.   |
| head            | Attribute to generate a Route and associated metadata.   |
| options         | Attribute to generate a Route and associated metadata.   |
| patch           | Attribute to generate a Route and associated metadata.   |
| post            | Attribute to generate a Route and associated metadata.   |
| put             | Attribute to generate a Route and associated metadata.   |
| route           | Attribute to generate a Route and associated metadata.   |
| FromForm        | Derive for the FromForm trait.                           |
| FromFormValue   | Derive for the FromFormValue trait.                      |
| Responder       | Derive for the Responder trait.                          |
| UriDisplayPath  | Derive for the UriDisplay<Path> trait.                   |
| UriDisplayQuery | Derive for the UriDisplay<Query> trait.                  |
|-----------------|----------------------------------------------------------|
```

When these proc-macros are re-exported from `rocket` via `pub use rocket_codegen::*`, their documentation in `rocket` is rendered as:

```
|---------------------|----------------------------------------------------------|
| async_test          | Type safe generation of route URIs.                      |
| catchers            | Attribute to generate a Route and associated metadata.   |
| rocket_internal_uri | Attribute to generate a Route and associated metadata.   |
| routes              | Attribute to generate a Route and associated metadata.   |
| uri                 | Attribute to generate a Route and associated metadata.   |
| catch               | Generates a Vec of Catchers from a set of catcher paths. |
| delete              | Derive for the Responder trait.                          |
| get                 |                                                          |
| head                | Derive for the UriDisplay<Query> trait.                  |
| options             | Generates a Vec of Routes from a set of route paths.     |
| patch               | Derive for the UriDisplay<Path> trait.                   |
| post                | Derive for the FromForm trait.                           |
| put                 | Derive for the FromFormValue trait.                      |
| route               | Attribute to generate a Catcher and associated metadata. |
| FromForm            | Attribute to generate a Route and associated metadata.   |
| Responder           | Attribute to generate a Route and associated metadata.   |
| UriDisplayPath      | Attribute to generate a Route and associated metadata.   |
| UriDisplayQuery     | Attribute to generate a Route and associated metadata.   |
|---------------------|----------------------------------------------------------|
```

Clicking through an item leads to the documentation alluded to by the snippet which is similarly incorrect.

Note that `rocket_internal_uri` is `#[doc(hidden)]` in `rocket_codegen`; it erroneously appears in `rocket`. Also note that `FromFormValue` is missing in `rocket`. The expected rendering, of course, is one identical to the rendering for `rocket_codegen`.

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #68690

When we generate the proc macro harness, we now explicitly recorder the
order in which we generate entries. We then use this ordering data to
deserialize the correct proc-macro-data from the crate metadata.

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? @petrochenkov 
There's must be some other issue here, this shouldn't be necessary.
I'll look what happens a bit later.

**Comment by Aaron1011** [comment]
> this shouldn't be necessary.

The probably some way to fix the ordering mismatch, but I really don't think it's the right approach. We shouldn't have to care about the precise order in which we generate the harness - we've already been wrong twice.

Explicitly defining the order ensures that we'll never have to worry about this again. If we try to patch the visitation orders to match, I'm almost certain that we'll hit this kind of issue again. We might miss another weird corner case, or someone could change the AST/HIR such that the itertion order is different.

**Comment by petrochenkov** [comment]
(This will probably has to wait until the next weekend.)

**Comment by petrochenkov** [comment]
Ahaha, it turns out the [order of items in HIR](https://github.com/rust-lang/rust/blob/61d9231ff2604a0467987042d9ebf9ff9ea739b5/src/librustc_hir/hir.rs#L616-L622) is not related to the order of items in AST *at all*, any similarity is purely coincidental.

Me and alexcrichton used some [seriously outdated](https://github.com/rust-lang/rust/pull/29903) knowledge in https://github.com/rust-lang/rust/pull/64528.
This PR is doing the right thing, but needs some more comments.

**Comment by petrochenkov** [comment]
r=me with comments added to AST as well.

**Comment by Aaron1011** [comment]
@petrochenkov: I've added an additional comment.

**Comment by petrochenkov** [comment]
I won't revert this PR since it had already landed, but the error was actually in the encoder.
```rust
tcx.hir().krate().items

=>

tcx.hir().krate().module.item_ids
```
Item order in HIR *does* repeat the item order in AST, `Crate::items` was just a wrong list to walk (it accumulates all items from all modules in the crate in semi-arbitrary order).

**Pull request merged**
