### PR TITLE
Use escaped byte string representation for CString Debug

### LINKED ISSUE #26964: Debug for CString is lossy
CString should escape its contents like a byte string, not trying to show it as utf-8. Right now it does the latter via `to_string_lossy()`

### PR DESCRIPTION
**Pull request by bluss**
Use escaped byte string representation for CString Debug

Faithfully represent the contents of the CString and CStr in their Debug
impl, by treating them as byte strings with our default escaping to
ascii representation.

Add impl Debug for CStr.

Fixes #26964.

### CODE REVIEW

**Comment by bluss** [comment]
r? @alexcrichton 

Can I avoid somehow adding a new feature name? I understand we might not want to add anything to ascii::EscapeDefault -- but at the same time, it's safer to use `unsafe` to guarantee utf-8 safety in the same module, than somewhere else.

Also think about the result of displaying a partly iterated ascii::EscapeDefault (it will still be ascii safe, but display a partial string).

**Comment by alexcrichton** [comment]
> Can I avoid somehow adding a new feature name?

Currently, no, but it's fine to just invent a name like you have. Due to there being no current precedent for implementing `Debug` for iterators, can this avoid the implementation on `EscapeDefault` for now? Something like this should be equivalent, right?

```rust
for byte in self.to_bytes().iter().flat_map(|b| ascii::escape_default(*b)) {
    write!(f, "{}", byte as char);
}
```

**Comment by bluss** [comment]
It's actually Display for the iterator. I think it's pretty appropriate, but I understand we can avoid it

**Comment by bluss** [comment]
Updated!

**Comment by alexcrichton** [comment]
@bors: r+ 92c8a9439b82f56aabb2f42e485e8683e663aaff

Thanks!

**Comment by bluss** [comment]
Suggested relnote: *CStr now implements `fmt::Debug`.*

**Pull request merged**
