### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #61077 (Don't arena-allocate static symbols.)
 - #61094 (Make find_local iterate instead of recurse)
 - #61095 (Update cargo)
 - #61096 (tidy: don't short-circuit on license error)
 - #61103 (Make find iterate instead of recurse)
 - #61104 (Make eval_place_to_op iterate instead of recurse)
 - #61107 (Fix a couple docs typos)
 - #61110 (Revert edition-guide toolstate override)
 - #61111 (Fixed type-alias-bounds lint doc)
 - #61113 (Deprecate `FnBox`. `Box<dyn FnOnce()>` can be called directly, since 1.35)
 - #61116 (Remove the incorrect warning from README.md)
 - #61118 (Dont ICE on an attempt to use GAT without feature gate)
 - #61125 (Updated my mailmap entry)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors r- retry

Nothing wrong with the PR, I just need to configure a thing on the Azure side.

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rust/pull/61104 failed on travis

@bors r-

**Pull request closed without merging**
