### PR TITLE
Revert "Temporarily rename int_roundings functions to avoid conflicts"

### PR DESCRIPTION
**Pull request by jhpratt**
This reverts commit 3ece63b64e192146fcdd1724e25856a93d7626aa.

This should be okay because #90329 has been merged.

r? @joshtriplett

### CODE REVIEW

**Comment by joshtriplett** [comment]
@bors try

Let's do a crater run on this.

**Comment by joshtriplett** [comment]
@craterbot check

**Comment by jhpratt** [comment]
Don't think I am able to do this, but it can't hurt to try.

@bors retry

**Comment by jhpratt** [comment]
@craterbot retry

**Comment by the8472** [comment]
@craterbot retry

**Comment by nbdd0121** [comment]
Out of 7 regressed crates:
* 2 failures have `#![feature(int_roundings)]` enabled but uses extension method (not sure why).
* 1 failure uses method with `unstable_` prefix.
* 4 seems spurious.

So it should be okay to merge this.

**Comment by jhpratt** [comment]
@joshtriplett I think this fell by the wayside. Should be a simple r+ — it just reverts your earlier commit. Breakage is nearly nonexistent as should be the case.

**Pull request merged**
