### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #108843 (Instantiate instead of erasing binder when probing param methods)
 - #109985 (Add little `is_test_crate` function)
 - #110028 (Migrate `rustc_hir_analysis` to session diagnostic [Part 3])
 - #110095 (Migrate remainder of rustc_ty_utils to `SessionDiagnostic`)
 - #110108 (Add renaming of ignore-git to changelog)
 - #110114 (compiletest: Give a better error message if `node` isn't installed)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=108843,109985,110028,110095,110108,110114)

### CODE REVIEW

**Comment by compiler-errors** [comment]
Spurious?

```
error: failed to download from `[https://crates.io/api/v1/crates/derive-new/0.5.8/download`](https://crates.io/api/v1/crates/derive-new/0.5.8/download%60)

Caused by:
  failed to get successful HTTP response from `[https://crates.io/api/v1/crates/derive-new/0.5.8/download`](https://crates.io/api/v1/crates/derive-new/0.5.8/download%60), got 504
  body:
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
  <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
  <TITLE>ERROR: The request could not be satisfied</TITLE>
  </HEAD><BODY>
  <H1>504 ERROR</H1>
  <H2>The request could not be satisfied.</H2>
  <HR noshade size="1px">
  CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
  We can't connect to the server fo…
```

@bors retry

**Comment by ehuss** [comment]
@bors retry

crates.io network blip

**Comment by ehuss** [comment]
@bors treeclosed=10

crates.io is still failing

**Comment by ehuss** [comment]
@bors treeclosed-

Looks like it is resolved.

**Pull request merged**
