### PR TITLE
Fix CI LLVM to work on NixOS out of the box

### PR DESCRIPTION
**Pull request by matklad**
r? @Mark-Simulacrum 

Tested locally, seems to work!

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I worry that this is probably not enough. In particular, we also download FileCheck, and if we don't fix that it'll probably break during codegen tests (`x.py test --stage 1 src/test/codegen`).

For now I'm fine with just explicitly fixing both, though ideally we'd not hard code that..

**Comment by Mark-Simulacrum** [comment]
r=me with FileCheck fixed as well

**Comment by Nadrieril** [comment]
When building the compiler on NixOS with CI LLVM I get:
```
/.../rust/build/x86_64-unknown-linux-gnu/ci-llvm/bin/llvm-config: error while loading shared libraries: libz.so.1: cannot open
 shared object file: No such file or directory
```
This can be fixed by adding zlib to LD_LIBRARY_PATH. Is this expected, given that this PR says "out of the box"? Am I missing something?

**Comment by matklad** [comment]
Ah, I am just building with this "kitchen sink" shell.nix: https://github.com/matklad/config/blob/ed3acd6a99eebe5e91df4cf90fa07f35dcaa88dd/shell.nix

I *think* there's a bunch of libs rust needs to build on nixos (I rememeber some ncurses related failures, for example). Not sure if we can fix that in the build. Unlike elfpatching, those things require dependnecies to be installed somewhere.

**Comment by Nadrieril** [comment]
Oh I see, that makes sense. It's the first time I've had issues I think. Would it make sense to include a `shell.nix` in the rustc codebase? :angel:

**Pull request merged**
