### PR TITLE
Use the correct logic for nested impl trait in assoc types

### PR DESCRIPTION
**Pull request by oli-obk**
Previously we accidentally continued with the TAIT visitor, which allowed more than we wanted to.

r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — CHANGES_REQUESTED** [review]
I'm still pretty confused about the structure here. Why does an `ImplTraitInAssocTypeCollector` wrap an `OpaqueTypeCollector`? Can we not just have some `mode: CollectionMode` that switches on the walking/projection/etc behavior? Or could we just *completely* separate these codepaths altogether? I feel like there's unnecessary complication here motivated by code deduplication.

**Comment by oli-obk** [comment]
Yea, I guess I could use a runtime switch instead

**Comment by oli-obk** [comment]
much better

@rustbot review

**Pull request merged**
