### PR TITLE
Individual docs for {from,to}_*_bytes

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by llogiq** [comment]
Ping @steveklabnik

**Comment by pietroalbini** [comment]
Ping from triage @steveklabnik! This PR needs your review.

**Comment by llogiq** [comment]
@steveklabnik or anyone, please review this.

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
Sorry, I was away. Looks good; just need a rebase and then r=me

**Comment by llogiq** [comment]
rebased. r=@steveklabnik once travis is through.

**Comment by llogiq** [comment]
@steveklabnik Travis is through.

**Comment by llogiq** [comment]
@pietroalbini @steveklabnik @Mark-Simulacrum, can someone tell @bors r=@steveklabnik please?

**Pull request merged**
