### PR TITLE
Pull Request for #22721

### PR DESCRIPTION
**Pull request by munds**
This is my first time doing this, so not entirely sure if I'm doing it right. Please let me know if I made any blunders :)

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hey @mund!

Everything is right here, except one detail: this can't be merged, because there are some conflicts. It seems like you also have some extra commits you didn't intend to get here, as well. If you fix up your `master` branch and then force push, github will update the pull request.

**Comment by mund** [comment]
r? @steveklabnik

I reverted back to the only commit that was supposed to get here ... I think?

**Comment by gamazeps** [comment]
@mund you still have inapropriate commits.

What you could do is an interactive `rebase`, it's quite a powerfull feature of git. 
Here the command you could do is (according to your fork of rust)
`$ git rebase -i f0f7ca27de6 # tells git what is the last commit it should consider`
There it will open a file in your default editor, simply erase the line with the commits you do not want.
You should just keep the line: `Modified L1247 of src/libsyntax/ast.rs`

Eventually force push your updated `master` branch to github.

You should take a look at how to use branches and the rebase command, it will be of tremendous use for you in the long run :)

**Comment by steveklabnik** [comment]
This landed in https://github.com/rust-lang/rust/pull/23179. Thanks!

**Pull request closed without merging**
