### PR TITLE
Box ItemKind::Impl

### PR DESCRIPTION
**Pull request by jyn514**
This brings the size of ItemKind down from 128 to 88 bytes.
Hopefully this will have perf improvements.

Follow-up to https://github.com/rust-lang/rust/pull/79322#discussion_r555984558, cc @estebank

### CODE REVIEW

**Comment by jyn514** [comment]
@rust-timer queue

**Comment by jyn514** [comment]
@rust-timer build 764bf6c03d3cac0149069e4345da9fcaed5bc45d

**Comment by jyn514** [comment]
Those numbers are not very promising :(

**Comment by estebank** [comment]
I think that max-rss is noisy but there might be some value there... https://perf.rust-lang.org/compare.html?start=058a71016553f267ae80b90276ef79956457d51a&end=764bf6c03d3cac0149069e4345da9fcaed5bc45d&stat=max-rss

**Comment by estebank** [comment]
I guess that going through the heap just makes things slower, it's fine. It's good to try things out and verify :)

**Comment by bugadani** [comment]
Maybe allocating on an arena would help?

**Pull request closed without merging**
