### PR TITLE
impl From<bool> for AtomicBool

### PR DESCRIPTION
**Pull request by ollie27**
This seems like an obvious omission from #45610. ~~I've used the same feature name and version in the hope that this can be backported to beta so it's stabilized with the other impls. If it can't be I'll change it to `1.24.0`.~~

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Marked as beta nominated.

cc @rust-lang/libs -- what do you think about backporting this to beta?

**Comment by sfackler** [comment]
I don't really see any reason to backport this.

**Comment by alexcrichton** [comment]
Agreed that feature-wise this seems fine but I probably wouldn't do the backport

**Comment by ollie27** [comment]
Right, I've changed it to `1.24.0`.

**Comment by BurntSushi** [comment]
LGTM. @bors r+

**Comment by kennytm** [comment]
@bors treeclosed=1

Something's wrong with the macOS CI, investigating.

**Pull request merged**
