### PR TITLE
Improve tests and benchmarks for slice::sort and slice::sort_unstable

### PR DESCRIPTION
**Pull request by ghost**
This PR just hardens the tests and improves benchmarks.
More specifically:

1. Benchmarks don't generate vectors in `Bencher::iter` loops, but simply clone pregenerated vectors.
2. Benchmark `*_strings` doesn't allocate Strings in `Bencher::iter` loops, but merely clones a `Vec<&str>`.
3. Benchmarks use seeded `XorShiftRng` to be more consistent.
4. Additional tests for `slice::sort` are added, which test sorting on slices with several ascending/descending runs. The implementation identifies such runs so it's a good idea to test that scenario a bit.
5. More checks are added to `run-pass/vector-sort-panic-safe.rs`. Sort algorithms copy elements around a lot (merge sort uses an auxilliary buffer and pdqsort copies the pivot onto the stack before partitioning, then writes it back into the slice). If elements that are being sorted are internally mutable and comparison function mutates them, it is important to make sure that sort algorithms always use the latest "versions" of elements. New checks verify that this is true for both `slice::sort` and `slice::sort_unstable`.

As a side note, all of those improvements were made as part of the parallel sorts PR in Rayon (nikomatsakis/rayon#379) and now I'm backporting them into libcore/libstd.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
Looks like a legitimate failure?

```
[01:06:00] 
[01:06:00] failures:
[01:06:00] 
[01:06:00] ---- [run-pass] run-pass/vector-sort-panic-safe.rs stdout ----
[01:06:00] 	
[01:06:00] error: test run failed!
[01:06:00] status: exit code: 101
[01:06:00] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/remote-test-client run /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/vector-sort-panic-safe.stage2-arm-unknown-linux-gnueabihf
[01:06:00] stdout:
[01:06:00] ------------------------------------------
[01:06:00] uploaded "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/vector-sort-panic-safe.stage2-arm-unknown-linux-gnueabihf", waiting for result
[01:06:00] 
[01:06:00] ------------------------------------------
[01:06:00] stderr:
[01:06:00] ------------------------------------------
[01:06:00] thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', /checkout/src/test/run-pass/vector-sort-panic-safe.rs:151
[01:06:00] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:06:00] 
[01:06:00] ------------------------------------------
[01:06:00] 
[01:06:00] thread '[run-pass] run-pass/vector-sort-panic-safe.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2480
[01:06:00] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:06:00] 
[01:06:00] 
[01:06:00] failures:
[01:06:00]     [run-pass] run-pass/vector-sort-panic-safe.rs
[01:06:00] 
[01:06:00] test result: [31mFAILED(B[m. 2696 passed; 1 failed; 9 ignored; 0 measured; 0 filtered out
```

**Comment by stjepang** [comment]
The failure is apparently due to a codegen bug on ARM platforms.

I believe simply moving `let mut rng = thread_rng()` ([here](https://github.com/rust-lang/rust/pull/42882/files#diff-36541a4992a571892972ea115a6bba9cR147)) outside the innermost loop would work around the build failure. Moving that line of code is a good idea anyway, so... can we do that or should we wait until the codegen issue is resolved?

**Comment by alexcrichton** [comment]
@stjepang yeah sounds good to me!

**Comment by stjepang** [comment]
All right, let's see if it works this time...

**Comment by stjepang** [comment]
The new failures are spurious, it seems... three targets were not tested at all (they're marked with `!` rather than `X`). Perhaps retry?

**Comment by kennytm** [comment]
@stjepang Don't worry about the `travis-ci/pr` failure, it is fine as long as the `IMAGE=x86_64-gnu-llvm-3.7 ALLOW_PR=1 RUST_BACKTRACE=1` one passes.

**Comment by Mark-Simulacrum** [comment]
@bors r- This failed the rollup, with I think the same failure. Possibly will be fixed after the LLVM update, not sure.

```
[01:05:40] ---- [run-pass] run-pass/vector-sort-panic-safe.rs stdout ----
[01:05:40]
[01:05:40] error: test run failed!
[01:05:40] status: exit code: 101
[01:05:40] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/remote-test-client run /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/vector-sort-panic-safe.stage2-arm-unknown-linux-gnueabihftdout:
[01:05:40] ------------------------------------------
[01:05:40] uploaded "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/vector-sort-panic-safe.stage2-arm-unknown-linux-gnueabihf", waiting for result
[01:05:40]
[01:05:40] ------------------------------------------
[01:05:40] stderr:
[01:05:40] ------------------------------------------
[01:05:40] thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', /checkout/src/test/run-pass/vector-sort-panic-safe.rs:152
[01:05:40] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:05:40]
[01:05:40] ------------------------------------------
[01:05:40]
[01:05:40] thread '[run-pass] run-pass/vector-sort-panic-safe.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2479
[01:05:40] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:05:40]
[01:05:40]
[01:05:40] failures:
[01:05:40]     [run-pass] run-pass/vector-sort-panic-safe.rs
[01:05:40]
[01:05:40] test result: FAILED. 2697 passed; 1 failed; 9 ignored; 0 measured; 0 filtered out
[01:05:40]
[01:05:40] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:325
```

**Comment by stjepang** [comment]
It will be fixed after the update, yes.

**Comment by stjepang** [comment]
Ok, LLVM has been updated. Should I rebase now?

**Comment by alexcrichton** [comment]
@bors: r+

Nah should still apply cleanly!

**Pull request merged**
