### PR TITLE
proc_macro::Span::len and subspan

### LINKED ISSUE #48187: Span that can point to closing delimiter of a delimited group
The [`proc_macro::TokenTree`](https://doc.rust-lang.org/proc_macro/enum.TokenTree.html) data structure currently look like this.

```rust
enum TokenTree {
    Group(Group),
    Ident(Ident),
    Punct(Punct),
    Literal(Literal),
}

impl Group {
    fn span(&self) -> Span;
}
```

Every delimited group like `(`...`)` `[`...`]` `{`...`}` has only a single `Span` that covers the full source location from opening delimiter to closing delimiter. This makes it impossible for a procedural macro to trigger an error pointing to just the opening or closing delimiter. The Rust compiler does not seem to have the same limitation:

```rust
mod m {
    type T =
}
```

```
error: expected type, found `}`
 --> src/main.rs:3:1
  |
3 | }
  | ^
```

The best things we can do in a proc macro are point to the last token inside the block, point to the entire block, or point to the next token after the block, none of which is really what you want for an error like above.

### PR DESCRIPTION
**Pull request by dtolnay**
Before this addition, every delimited group like `(`...`)` `[`...`]` `{`...`}` has only a single Span that covers the full source location from opening delimiter to closing delimiter. This makes it impossible for a procedural macro to trigger an error pointing to just the opening or closing delimiter. The Rust compiler does not seem to have the same limitation:

```rust
mod m {
    type T =
}
```

```console
error: expected type, found `}`
 --> src/main.rs:3:1
  |
3 | }
  | ^
```

On that same input, a procedural macro would be forced to trigger the error on the last token inside the block, on the entire block, or on the next token after the block, none of which is really what you want for an error like above.

This commit adds `span.len()` and `span.subspan(range)` through which we can slice a span to point to some range of its original bytes.

```diff
  impl Span {
+     fn len(self) -> usize;
+     fn subspan<R: RangeBounds<usize>>(self, range: R) -> Span;
  }
```

For example in the following line of source code the span of the opening parenthesis would be `.subspan(..1)` of the span of the parenthesis token, and the erroneous format specifier would be `.subspan(9..12)` of the span of the string literal token.

```text
println!("{a} {b} {c}", a=1, b=2);
        ^         ^^^
```

Relevant to Syn as we implement real error messages for when parsing fails in a procedural macro: https://github.com/dtolnay/syn/issues/476.

Fixes #48187.
r? @petrochenkov 
cc @alexcrichton

### CODE REVIEW

**Comment by petrochenkov** [comment]
r=me if @alexcrichton has no concerns

I'm not entirely sure what is the idiomatic naming choice between `subspan` and `sub_span`, but the first looks better to me (`subspan` is a single word with prefix, not two words).

**Comment by petrochenkov** [comment]
cc @eddyb 
I hope you grand plans with span encoding don't make spans non-continuous or not knowing their size.

**Comment by alexcrichton** [comment]
Seems like a plausible API! I think this could definitely work for things like spans of string literals, but how does this work for spans of `Group` tokens? There's no way to know where subspans are within a larger span, and the integers here are byte positions in the source and the token stream doesn't know much about whitespace?

On another API note, does this handle pointing a byte position to the middle of a multibyte unicode character? Or would that perhaps cause an ICE later down the line?

**Comment by eddyb** [comment]
> Or would that perhaps cause an ICE later down the line?

I would suspect it does.

Frankly, I don't think we should expose *any* notion of "bytes" here. The fact that `Span` has one primary range of bytes is historical, related to the hack of concatenating all files into the source map.

I'm seeing two problems here: not having access to the `Span`s of delimiter tokens for `Group` and not being able to refer to specific parts of a literal token. They should, IMO, have targeted solutions.

**Comment by dtolnay** [comment]
Seems like we're full circle and back to #53902. What do you think of that one @eddyb?

**Comment by eddyb** [comment]
@dtolnay I prefer that but *ideally* it wouldn't be doing span manipulation at all.
OTOH, delimiters are special in that they can't be "transplanted" in any way, i.e. they must come from some original string source, so span manipulation is okay (**iff** you trust the `Group`'s span).

But also, let's say someone creates a `Group` out of thin air, what spans should that use? Seems like that should cause it to not have open/close delimiter spans *at all* (and have it return an `Option`).

**Comment by petrochenkov** [comment]
>The fact that Span has one primary range of bytes is historical, related to the hack of concatenating all files into the source map.

IMO, it would be quite reasonable to restrict `Span`s to being continuous ranges of source text from a single "logical file" (for anything else we have `MultiSpan`, etc).
Split of concatenated source map into multiple files won't affect spans in any way in this case.

**Comment by dtolnay** [comment]
> But also, let's say someone creates a `Group` out of thin air, what spans should that use? Seems like that should result in no open/close delimiter spans *at all* (and the methods should return `None`).

I started adding a `trusted_span: bool` field to [`struct Group`](https://github.com/rust-lang/rust/blob/b24330fb7d9e89d63eb03d81fe577172aad49525/src/libproc_macro/lib.rs#L609). That way we have the compiler set to true when building proc_macro tokens from what it knows is legit source code, and set to false when a user calls `set_span` to change the span associated with a group. The methods to access the span of open/close delimiter would only perform the slicing if `trusted_span` is true, otherwise return None.

But I realized that even when converting from internal `syntax::tokenstream::TokenStream` to `proc_macro::TokenStream` some of those spans could be untrusted because they came from an invocation of one procedural macro that expanded to an invocation of another procedural macro. Is the right behavior to have libsyntax also track which spans are legit and allowed to be sliced by the proc_macro API?

**Comment by eddyb** [comment]
> Is the right behavior to have libsyntax also track which spans are legit and allowed to be sliced by the proc_macro API?

We should probably just bite the bullet and keep track of the original delimiter token spans.
(we can make it cheap by using `Span` with `DUMMY_SP` indicating it's not present)

**Comment by dtolnay** [comment]
> We should probably just bite the bullet and keep track of the original delimiter token spans.

I added this to #53902. Let me know if this is what you had in mind. Also @petrochenkov I see the confused reaction, let me know if you have concerns about that approach.

**Comment by dtolnay** [comment]
Rebased on #53902, but closing because #53902 is sufficient for my use case so someone else is going to need to drive this change.

@petrochenkov's comment in https://github.com/rust-lang/rust/pull/53902#issuecomment-419707948 for context:

> I still think there's nothing wrong in guaranteeing that a `Span` is an arbitrary sliceable (possibly UTF-8 encoded) continuous byte range and providing the API from https://github.com/rust-lang/rust/pull/53930.

**Pull request closed without merging**
