### PR TITLE
Shrink metadata size

### PR DESCRIPTION
**Pull request by arielb1**
libcore.rlib reduced from 19121 kiB to 15934 kiB - 20% win.

The librustc encoded AST is 9013500 bytes long - for the record, librustc consists of about 2254126 characters. Might be worth looking at.

r? @eddyb

### CODE REVIEW

**Comment by arielb1** [comment]
@bors r-

still WIP

**Comment by arielb1** [comment]
<updated>

**Comment by bluss** [comment]
relnotes: Just nice to brag about improvements like this

**Comment by brson** [comment]
Nice wins.

**Pull request merged**
