### PR TITLE
Use generic trait implementations for Cursor when possible.

### PR DESCRIPTION
**Pull request by nwin**
This is a revival of #23364. Github didn’t recognize my updated branch there.

The cursor implementation now uses `AsRef` which means that fixed-sized array can now be used with `Cursor`. Besides that, the generic implementation simplifies the code as the macro can be avoided.

The only drawback is, that specialized implementation for fixed-sized arrays are now ruled out unless [RFC#1210](https://github.com/rust-lang/rfcs/pull/1210) is accepted & implemented.

`Box<[u8]>` cannot be used yet, but that should be mitigated by [implementing `AsRef` for `Box` and friends](https://internals.rust-lang.org/t/forward-implement-traits-on-smart-pointers-make-smart-pointers-more-transparent/2380/3). I will submit a separate PR for that later as it is an orthogonal issue.

### CODE REVIEW

**Comment by nwin** [comment]
rebased

**Comment by aturon** [comment]
@nwin, sorry for the reviewing delay -- I was away on vacation last week.

This change looks good to me, but I'd also like to get @alexcrichton's opinion. We don't currently use `AsRef` in this way in IO -- in many cases we can't -- but it seems pretty reasonable to do so here.

**Comment by alexcrichton** [comment]
I do feel somewhat more comfortable with this than before (using `AsRef` instead of `Deref`). I don't think this is a strictly backwards-compatible change though (in terms of coherence) because I could have `impl Read for Cursor<MyType>` locally I believe and this would start not compiling if `MyType` implemented `AsRef<[u8]>`. I'm currently running a crater run to see if this actually causes any breakage in practice.

Unfortunately this also doesn't enable things like `Cursor<Box<[u8]>>` because the `AsRef` trait isn't implemented for many smart pointers (and I think we ran into trouble doing so).

**Comment by nwin** [comment]
Do you remember what was holding back something like

```rust
impl<T: ?Sized, V: AsRef<T> + ?Sized> AsRef<T> for Box<V> {
    #[inline]
    fn as_ref(&self) -> &T {
        (&*self.0).as_ref()
    }
}
```

T would have been my next PR.

**Comment by alexcrichton** [comment]
I believe the killer aspect was that the meaning of `<Box<Option<T>>::as_ref` changed. Before it would return `Option<&T>` and after the addition of the trait impl it would return `&Option<T>`.

**Comment by alexcrichton** [comment]
Looks like this [causes one regression](https://gist.github.com/anonymous/acb236dfc772ae185650) on crates.io

**Comment by aturon** [comment]
That breakage seems acceptable under our semver guidelines.

@nwin, I'm wondering if you can elaborate on the motivation here. Is it mainly to clean up the implementation, or is there a use case you've run into that needs this additional flexibility?

**Comment by nwin** [comment]
@alexcrichton Ah the `Box` thing is annoying. On the other hand we are already having `impl<'a, T, U> AsRef<U> for &'a T where T: AsRef<U> + ?Sized, U: ?Sized` (which is causing this regression I guess), so it would be natural to have the same forward implementation for smart pointers.

@aturon As I already elaborated in  #23364, my main motivation was to enable the usage of `Box<[T]>`, `Arc<[T]>` etc. Initially I used `Deref` for that but it was brought up that `AsRef` is the more natural trait to do that as it also coverts fixed-sized arrays (currently only up to a length of 32 though :( ). Thus a follow-up PR would have been the [implementation of `AsRef` for `Box` and friends](https://internals.rust-lang.org/t/forward-implement-traits-on-smart-pointers-make-smart-pointers-more-transparent/2380/3). I didn’t get any feedback on this thread so I just went ahead.

As it appears now, this is not so trivial but we are also in the unfortunate situation that it is currently impossible to write generic code over `&[u8]`, `Vec<u8>` and `SmartPointer<[u8]>`. Afaik the first two types were part of the motivation to introduce `AsRef` in the first place.

**Comment by nwin** [comment]
I updated this PR such that is uses `Borrow` instead. I didn’t squash the commits yet.

**Comment by alexcrichton** [comment]
Thanks @nwin! I'm on board with this change as-is, but I'm gonna flag this with `T-libs` so it comes up during triage to get some more eyes on it.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today, and the conclusion was that we're currently pretty on-the-fence about this. @Gankro pointed out that the use of `Borrow` is out of line with how it's only used for collections today, and @aturon echo'd the thought indicating that `AsRef` really is the right solution here.

The conclusion was to reevaluate implementations of `AsRef` on smart pointers today with the help of crater. If the breakage (although present) is relatively minimal we may reconsider adding those implementations. As a result I'm going to do a crater run of adding `AsRef` implementations for smart pointers and report back with the results!

**Comment by Gankro** [comment]
(note that Borrow isn't *totally* a collections thing today -- Cow being the notable exception)

**Comment by alexcrichton** [comment]
Ok, the [crater report](https://gist.github.com/anonymous/0ba4c3512b07641c0f99) indicates a total of 5 root regressions, but 4 of those were timeouts (cc @brson, common to see?) and [only one of them](https://tools.taskcluster.net/task-inspector/#WZm3vhTPQFGlfOAzzTArDg/0) was related to the addition of `AsRef`. There were three regressions caused by dependencies on that one root regression which may also need to be investigated as well.

cc #26096, the original issue about the regression. This may be showing up more externally than on crates.io as well because the use of smart pointers tends to happen more in apps than libs perhaps.

**Comment by brson** [comment]
@alexcrichton Yeah, timeouts are common.

**Comment by alexcrichton** [comment]
As an update, the libs team talked about this and decided to move forward with `AsRef` and `AsMut` implementations on smart pointers (https://github.com/rust-lang/rust/pull/28811), so if that gets merged then this should be ok to merge going back to `AsRef`. Thanks for being patient @nwin!

**Comment by nwin** [comment]
Great. I removed my latest commit and rebased onto master.

`process::tests::test_inherit_env` fails it also doesn’t pass on master, probably some OSX 10.11 issue…

**Comment by alexcrichton** [comment]
OK, now that #28811 has merged, I'm going to r+ this, thanks again for the patience @nwin!

@bors: r+ ea1f886e502bc826cd4e241d06ffd0ad26e95d00

**Pull request merged**
