### PR TITLE
Added error documentation for write_fmt

### PR DESCRIPTION
**Pull request by alexs-sh**
This continuation of work at rust-lang#98861

### CODE REVIEW

**Comment by clubby789** [comment]
Since this just duplicates the error comment for `std::fmt::Write::write_str`, it might be better to add a 'See <link> for details', so the comments don't get out of sync if they're updated in future.

**Comment by alexs-sh** [comment]
Hi,@clubby789  Yes, I agree. It will be better. Thanks for your reply and your idea.

**Comment by alexs-sh** [comment]
@clubby789 I added a link to ```std::fmt::Write::write_str``` error. Could you please review it?

**Comment by scottmcm** [comment]
Looks good; thanks!

@bors r+ rollup

**Pull request merged**
