### PR TITLE
improve search tabs look

### LINKED ISSUE #55056: [rustdoc] discoverability of parameter and return type search results
spawned from https://github.com/onur/docs.rs/issues/241

The ability to search by parameter and return types sometimes goes undiscovered, even when the feature is desired (see the issue above). Part of this might be because the options do not appear until after the first search.

Currently, results look like the following. It seems benign if one knows to read it as "Results for PAddr In Names", but that might not be immediately obvious.

paddr_name

Some ideas:
Move the bar closer to the search bar (removed the "In"s). This change alone might not be entirely obvious either, although it gives the tabs more breathing space.
paddr_edit_2

To help show that the tabs affect the search results, we could change the tab titles to be read as actions.
paddr_edit

from @Havvy 
> I like both suggestions. I even have one more to add. In the "Results for X", it should say "Results for X in Parameters" when searching parameters. Though that won't help with discoverability. "Results for X in Names" would look weird though, so leave that one off.

Variation of the above:
```
Name Results for X
Parameter Results for X
Return Type Results for X
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #55056.

screenshot from 2018-10-16 19-06-48

screenshot from 2018-10-16 19-09-39

With this, I think it'll be more obvious.

cc @memoryruins 

r? @QuietMisdreavus

### CODE REVIEW

**Comment by memoryruins** [comment]
Thank you for trying out changes! The use of negative space tabs idea is clever, and does give more context to their purpose. The minimalism of the single line previously was clean, at least for those who know its there, but that subtlety might've been what made it easy to overlook. Currently in the above tabs, the text might benefit with some extra breathing room.

I was in the middle of a variation of your negative space idea, making ad-hoc changes with inspector, before realizing I had copied Firefox's tabs..

firedocs

**Comment by GuillaumeGomez** [comment]
Well, they look better than what I did so I can totally go for it (and I will)!

**Comment by GuillaumeGomez** [comment]
Here's the current look:

screen shot 2018-10-21 at 16 38 42

screen shot 2018-10-21 at 16 38 48

**Comment by QuietMisdreavus** [comment]
Wow, this looks really nice now!

@bors r+ rollup

**Pull request merged**
