### PR TITLE
Add new error code tests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
In case anyone is wondering - I'm using these to make sure we have coverage as we convert the new error codes.  After we're done, it probably makes sense for these to live in their own directory in `compile-fail`

**Comment by nagisa** [comment]
Won’t these essentially duplicate existing tests?

**Comment by GuillaumeGomez** [comment]
@nagisa: It's for #35233.

**Comment by GuillaumeGomez** [comment]
Updated (some errors have disappear or be replaced).

**Comment by nagisa** [comment]
I know what it is for. I'm wondering if there aren't already a test that
could be recycled for this. I'm pretty sure we already have a bunch o tests
for various error codes and messages.

**Comment by GuillaumeGomez** [comment]
@nagisa: They are, but they rarely target a specific error code.

**Comment by jonathandturner** [comment]
@nagisa - there may already be a tested, but it's difficult to see what our coverage is without literally searching for each error code.

One possibly future fix would be to include the error code in the unit test filename, so that we can see error codes that aren't being checked.  I noticed quite a few don't have tests that only got them because of @GuillaumeGomez's work.

We can also put them in a separate directory under `compile-fail` just like the borrowck errors, so they're not in the way, but I want to wait to do that until after people have updated them.

**Comment by jonathandturner** [comment]
Case in point:

```
jturner-23759:rust jturner$ git grep "E0230"
src/librustc_typeck/check/mod.rs:                                span_err!(ccx.tcx.sess, attr.span, E0230,
src/librustc_typeck/diagnostics.rs:    E0230, // there is no type parameter on trait
jturner-23759:rust jturner$ git grep "E0231"
src/librustc_typeck/check/mod.rs:                            span_err!(ccx.tcx.sess, attr.span, E0231,
src/librustc_typeck/diagnostics.rs:    E0231, // only named substitution parameters are allowed
jturner-23759:rust jturner$ git grep "E0232"
src/librustc_typeck/check/mod.rs:            span_err!(ccx.tcx.sess, attr.span, E0232,
src/librustc_typeck/diagnostics.rs:E0232: r##"
jturner-23759:rust jturner$ git grep "E0233"
src/librustc_typeck/diagnostics.rs://  E0233,
jturner-23759:rust jturner$ git grep "E0234"
src/librustc_typeck/diagnostics.rs://  E0234,
jturner-23759:rust jturner$ git grep "E0235"
src/librustc_typeck/diagnostics.rs://  E0235, // structure constructor specifies a structure of type but
jturner-23759:rust jturner$ git grep "E0236"
src/librustc_typeck/diagnostics.rs://  E0236, // no lang item for range syntax
jturner-23759:rust jturner$ git grep "E0237"
src/librustc_typeck/diagnostics.rs://  E0237, // no lang item for range syntax
jturner-23759:rust jturner$ git grep "E0238"
src/librustc_typeck/check/mod.rs:                span_err!(self.tcx.sess, span, E0238,
src/librustc_typeck/diagnostics.rs:    E0238, // parenthesized parameters may only be used with a trait
jturner-23759:rust jturner$ git grep "E0239"
src/librustc_typeck/diagnostics.rs://  E0239, // `next` method of `Iterator` trait has unexpected type
jturner-23759:rust jturner$ git grep "E0240"
src/librustc_typeck/diagnostics.rs://  E0240,
jturner-23759:rust jturner$ git grep "E0241"
src/librustc_typeck/diagnostics.rs://  E0241,
jturner-23759:rust jturner$ git grep "E0242"
src/librustc_typeck/diagnostics.rs://  E0242,
jturner-23759:rust jturner$ git grep "E0243"
src/librustc_typeck/astconv.rs:        span_err!(tcx.sess, span, E0243,
src/librustc_typeck/diagnostics.rs:E0243: r##"
jturner-23759:rust jturner$ git grep "E0244"
src/librustc_typeck/astconv.rs:        span_err!(tcx.sess, span, E0244,
src/librustc_typeck/diagnostics.rs:E0244: r##"
jturner-23759:rust jturner$ git grep "E0245"
src/librustc_typeck/astconv.rs:                span_fatal!(self.tcx().sess, path.span, E0245, "`{}` is not a trait",
src/librustc_typeck/diagnostics.rs:    E0245, // not a trait
jturner-23759:rust jturner$ git grep "E0246"
src/librustc_typeck/diagnostics.rs://  E0246, // invalid recursive type
jturner-23759:rust jturner$ git grep "E0247"
src/librustc_typeck/diagnostics.rs://  E0247,
jturner-23759:rust jturner$ git grep "E0248"
src/librustc_typeck/astconv.rs:                span_err!(tcx.sess, span, E0248,
src/librustc_typeck/diagnostics.rs:E0248: r##"
jturner-23759:rust jturner$ git grep "E0249"
src/librustc_typeck/diagnostics.rs://  E0249,
jturner-23759:rust jturner$ git grep "E0250"
```

So many error codes without any tests.  You'd think this would be duplicating work, and it probably will in some cases, but I think coverage is more important.

@bors r+

**Pull request merged**
