### PR TITLE
cargotest: Add xsv to tested crates

### PR DESCRIPTION
**Pull request by alexcrichton**
This was intended to land in #37149 but I ended up backing it out to land the
rollup (#38697) last night as I was itching to do so. This morning though xsv
has been fixed now (BurntSushi/xsv#53) so we should be able to add it!

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @brson this is something I'd expect to have gotten caught by cargobomb?

**Comment by nikomatsakis** [comment]
r=me I guess? :) Commit seems fine, but I dno't know a lot about the plans here.

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis

I'll take it!

**Comment by brson** [comment]
Yes cargobomb catches this.

**Pull request merged**
