### PR TITLE
Remove variances from traits and deprecate `PhantomFn`/`MarkerTrait`

### LINKED ISSUE #22806: Infinite recursion with a defaulted, contravariant trait
This test fails to compile:

```rust
unsafe trait MySend {
    fn dummy(&self) { }
}

unsafe impl MySend for .. { }

unsafe impl<T: MySend + ?Sized> MySend for Unique<T> { }

pub struct Unique<T:?Sized> {
    pointer: *const T,
}

pub struct Node<V> {
    vals: V,
    edges: Unique<Node<V>>,
}

fn is_send<T: MySend>() {}

fn main() {
    is_send::<Node<&'static ()>>();
}
```

the output is of the form:

```
...
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required because of the requirements on the impl of `MySend` for `Node<&'static ()>`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nmatsakis/tmp/22655b.rs:21:5: 21:33 note: required by `is_send`
/home/nmatsakis/tmp/22655b.rs:21     is_send::<Node<&'static ()>>();
```

This bug is branched off of #22655. It represents the underlying problem that caused #22655.

### PR DESCRIPTION
**Pull request by nikomatsakis**
There are still some remnants we could remove from the compiler (e.g. references to "subtraitrefs"; traits still have variance entries in the variance table), but this removes all user-visible bits I believe.

r? @pnkfelix 

Fixes #22806 (since such traits would no longer exist)

### CODE REVIEW

**Comment by pnkfelix** [comment]
anyway I'm still going to approve the PR

**Comment by nikomatsakis** [comment]
Update: @alexcrichton encountered some errors combining this PR with the `ty_relate` code introduced by https://github.com/rust-lang/rust/pull/23895.

**Comment by nikomatsakis** [comment]
I have to look more deeply, but perhaps that suggests variance on traits is more useful than originally anticipated -- particularly around lifetime parameters.

**Comment by nikomatsakis** [comment]
OK, I rebased and fixed the bad interaction.

**Comment by nikomatsakis** [comment]
Feeling a wee bit undecided about whether to take this patch, though I still lean in favor.

**Comment by nikomatsakis** [comment]
Decided to go through with this.

**Comment by nikomatsakis** [comment]
Basic explanation of reasoning:

1. Still no concrete example.
2. Current system is somewhat uneven -- you can get variance, but you really have to understand the rules. On the other hand, the price of MarkerTrait + PhantomFn is imposed on all users, and most people don't really grok what is necessary.
3. In particular, `Fn` traits are invariant, which is not good, since this is the poster child for variance.
4. Always possible, if awkward, to workaround:
  - either with HRTB or,
  - by introducing a wrapper (i.e., if you need a `Foo<'a>` trait where `'a` can be made shorter, then you can make a `FooAdapter<'a,'b> where 'a:'b` type that implements `Foo<'b>` given a `Foo<'a>`.

This adds up to: better to address trait variance more comprehensively in future and make `Fn` and friends opt-in.

**Comment by nikomatsakis** [comment]
@bors p=1

giving high priority because this is a backwards compat thing

**Comment by pnkfelix** [comment]
(I forced the retry in the hopes that the build products from the previous attempt would still be usable, but perhaps I was incorrect about that, since I think normally bors writes some notes here when it has discovered it can reuse build products from a previous attempt.)

**Pull request merged**
