### PR TITLE
`target_os = "custom"`: selecting/swapping platform-specific parts of the libstd at runtime

### PR DESCRIPTION
**Pull request by NathanRoyer**
On experimental kernels and other `no_std` platform, it can be desirable to use the standard library, either directly or in dependencies.

To do so, one currently needs to:
- clone this repository
- create a new directory in `library/std/src/sys`
- provide implementations for all the platform specific functions (maybe re-using the impl from `unsupported`)
- compile a toolchain
- linking it using rustup

As an alternative, this PR adds a "custom" value for `target_os`, which reduces this workflow to:
- add `"os": "custom",` to their `target.json`
- provide implementations for the platform specific functions that their use case requires (undefined functions simply panic)
- use the `build-std` feature of cargo (note: see "Built-in target definitions" below)

Suboptimal but cross platform implementations are included for thread local storage and locking primitives; additionally, an initial allocator is provided (with a fixed heap capacity of 16KiB).

### API

Here are [the built docs for this](https://www.theorozier.fr/assets/docs/bitsneak-custom-std/std/os/custom/).

### Design Decisions

For each subsystem, there is a singleton:
```rust
pub(crate) static IMPL: RwLock<Option<Box<dyn ThatSubsystemTrait>>> = RwLock::new(None);
```

In `library/std/src/sys`, functions use a macro call:
```rust
pub fn decode_error_kind(errno: i32) -> std_io::ErrorKind {
    custom_os_impl!(os, decode_error_kind, errno)
}
```

which translates to:
```rust
pub fn decode_error_kind(errno: i32) -> std_io::ErrorKind {
    let errmsg = "std::os::custom::os::IMPL has not been initialized at this point";
    let rwlock = &crate::os::custom::os::IMPL;
    let reader = rwlock.read().expect("poisoned lock");
    let some_impl = reader.as_ref().expect(errmsg);
    some_impl.decode_error_kind(errno)
}
```

Initially, the singletons contains `None`. Once a singleton is set (to `Some(_)`), runtime implementations cannot be removed, they can only be swapped: a singleton will never return to a `None` state.

This boxed design is not as efficient as a direct extern call, but for experimental projects which actually lead to something useful, the backing implementation can easily be moved into the stdlib later.

Additionally, if I had taken the path of static `extern` definitions for this project, I feel like that would have complicated the use in projects which have custom link scripts and linking procedures. Also, this would prevent runtime swapping of implementations, which I feel can be useful to follow the booting procedure of custom kernels. I'm not sure how the `global_allocator` thing work, does it use static `extern` definitions?

### Built-in target definitions

This PR doesn't add any target definition.
However, if we added built-in defs for common bare-bones environments:
- x86_64-unknown-custom
- aarch64-unknown-custom
- RISC-V?
- 32-bit arm?
- wasm? I'm not sure how the allocators work there, could there be complications specific to this target?

That would ease the use of this work even more for relevant projects.

### TLS: Inlined `__getit`

In `library/std/src/sys/common/thread_local/os_local.rs`, I cfg-gated the `inline` attribute for custom because for some reason, with the attribute, the `__getit` function had an invalid address or wasn't linked in the final binary (I'm not sure which one was happening). Anyway, without the `inline` attribute, it works fine, and I don't really understand the point of having this function inlined anyway since it's not ever called directly; it cannot be inlined, can it?

### Poison-check bypass in thread_local_key & default allocator

During panic handling, thread-local-storage and allocations are involved. However, the implementations that this PR brings use locking primitives, which have poison checks. These checks messed with panic handling and resulted in various sorts of double-panics and deadlocks. This was mostly a chicken and egg problem involving the initialization of `LOCAL_PANIC_COUNT`, which lives in TLS.

To deal with this I tried two approaches, and the one I kept is having special `lock/read/write` methods on `Mutex` & `RwLock`, which bypass poison checks. This works, and I think it's ok? Because thread_local_key and the allocator have no reason to panic except being out of memory, which is unrecoverable anyway.

### To-do

I'd like to get feedback before spending more time on this, but here are things I haven't done yet:
- documenting each trait method
- thread parking support
- thread-safe Once support
- invocation arguments (returns an empty iterator at the moment)
- `pipe::read2`
- `Command::output`
- `From<File> for Stdio`

### CODE REVIEW

**Comment by cuviper** [comment]
Rerolling -- I'm afraid I don't have time to review such a large PR, especially since I'm not aware of prior context.

r? libs

**Comment by thomcc** [comment]
I suppose I'm a reasonable choice for a reviewer since I maintain a [heavily patched out-of-tree libstd for a "custom" OS](https://github.com/tcdi/postgrestd).

I think whether we want to do this (and if this is the approach we want to take) should probably be discussed further though.

**Comment by NathanRoyer** [comment]
@thomcc thank you for your reply! I started a [zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/target_os.20.3D.20.22custom.22.20PR) for this minutes ago haha :)

**Comment by thomcc** [comment]
I'm going to be away for a few months, so I'm rerolling my PRs so that folks don't have to wait for me. Sorry/thanks.

r? libs

**Comment by Mark-Simulacrum** [comment]
I'm going to nominate this PR for T-libs and T-libs-api, since I agree with others on thread that doing this is a larger decision than any individual reviewer should probably make. My sense is that it may be a good idea to write up a full RFC proposing this (presuming the teams are generally onboard), particularly so that we have space to explore the design outside of a specific implementation, consider what other languages do in this space, etc.

**Comment by NathanRoyer** [comment]
> I'm going to nominate this PR for T-libs and T-libs-api, since I agree with others on thread that doing this is a larger decision than any individual reviewer should probably make. My sense is that it may be a good idea to write up a full RFC proposing this (presuming the teams are generally onboard), particularly so that we have space to explore the design outside of a specific implementation, consider what other languages do in this space, etc.

Yep. I don't when I'll be able to, but I do want to create an RFC for this.

**Comment by m-ou-se** [comment]
There are a lot of higher level questions that need discussion and answering before it makes sense to dive into one possible implementaiton like in this PR. (There is also ongoing work to clean up and refactor std::sys, which should happen before anything like this.)

It'd be great to have a better way to support operating systems out of tree, but we first need to have a discussion on the possible approaches and the relevant trade-offs. There are also questions around stability of this OS implementation interface.

I'm hopeful that some day we will have a feature like [proposed here](https://github.com/rust-lang/rfcs/pull/2492) that would allow the implementation of the OS-specific details to live outside std.

I think the right approach would be to first research the various options, including the what a solution would look like with a new language feature such as proposed in RFC 2492, perhaps as part of a (pre) RFC.

**Comment by NathanRoyer** [comment]
I fully agree that the proposal in RFC 2492 would allow for a better implementation of what I proposed here. I took the "runtime" approach but a compile-time one would certainly be better; I don't have enough knowledge on linkage to take such an approach.

I also agree to create an RFC for this. I no longer develop for `no_std` professionally though, so it's no longer a priority for me. If anyone wants to, feel free to link the RFC to this PR, one way or another.

**Comment by Dylan-DPC** [comment]
This requires a (pre-)RFC so it's better to close this and create a new PR if interested once the RFC is approved

**Pull request closed without merging**
