### PR TITLE
Update cc to 1.1.22 in library/

### PR DESCRIPTION
**Pull request by ChrisDenton**
r? @ghost

try-job: x86_64-msvc

### CODE REVIEW

**Comment by tgross35** [comment]
Oh, you beat me to it.

r=me if try passes

**Comment by ChrisDenton** [comment]
Oh yeah, sorry. I after my comment I thought "why don't I just try this" as it's fairly simple.

**Comment by arttet** [comment]
Let's merge it?

**Comment by ChrisDenton** [comment]
Fair enough!

@bors r=tgross35

**Pull request merged**
