### PR TITLE
Issue #66099 - Added the upper and lower bounds to the documentation of all integer types.

### PR DESCRIPTION
**Pull request by segfaultsourcery**
I quickly came to the realization that the only way to reliably get the numbers is to hard-code them and pass them through to the macros `int_module!` and `uint_module!`. I've changed the code, run through the tests, and seen that the documentation does update in the appropriate places.

### CODE REVIEW

**Comment by segfaultsourcery** [comment]
This is in response to issue 66099, https://github.com/rust-lang/rust/issues/66099

I'll gladly spend some more time refining this until it fits your style better.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@cramertj Can you please review this PR and provide any additional feedback to segfaultsourcery. Thanks.

**Comment by ohadravid** [comment]
I'm also trying to solve this more generally in https://github.com/rust-lang/rust/pull/66221

**Comment by cramertj** [comment]
This PR seems fine to me, but it might not be a bad idea to wait and see if #66221 can land, making this unnecessary.

**Comment by segfaultsourcery** [comment]
I can't believe I missed #66221. I hope it lands, it's a really nice idea.

**Comment by jplatte** [comment]
Since #66221 has been merged, I think this can be closed.

**Pull request closed without merging**
