### PR TITLE
[DONT MERGE] Always validate HIR ID for TypeckTables

### PR DESCRIPTION
**Pull request by Xanewok**
...and not only with `debug_assertions` compiled in - https://github.com/rust-lang/rust/pull/64250#issuecomment-529108106.

cc @Mark-Simulacrum @michaelwoerister 

Let's do a try run to see if this impacts perf anyhow?

r? @ghost

### CODE REVIEW

**Comment by Xanewok** [comment]
`dist` run failed as expected because that's what https://github.com/rust-lang/rust/pull/64250 is meant to fix but since I'm not sure if that generates artifacts that are enough to do a perf run (@Mark-Simulacrum does it?), I'm cherry-picking the patch from #64250 and `try`ing again

@bors try

**Comment by Mark-Simulacrum** [comment]
Uh, if the dist run failed then no artifacts would've been generated AFAIK.

**Comment by Xanewok** [comment]
@rust-timer build 647e87d6d5f99f6a8f2497a7af33393598398b67

**Comment by Xanewok** [comment]
I tried to pick an early base but I could only do with a date start: https://perf.rust-lang.org/compare.html?start=2019-09-06&end=647e87d6d5f99f6a8f2497a7af33393598398b67 (later commits are not available?)

Instruction-wise, `inflate` regressed ~2% and `keccak` ~1%, rest seems to be a noise?

@Mark-Simulacrum I'd appreciate another set of eyes on the perf results; do these seem reasonable?

**Comment by Xanewok** [comment]
Okay, the immediate results are in and I believe these look like noise, so maybe we can land it?

**Comment by Mark-Simulacrum** [comment]
Yeah, I'll go ahead and close this PR but the other PR should now not have any performance concerns.

**Pull request closed without merging**
