### PR TITLE
Update stdarch submodule

### PR DESCRIPTION
**Pull request by scottmcm**
To pick up https://github.com/rust-lang/stdarch/pull/1624 and unblock removing support for non-array-based-simd (https://github.com/rust-lang/compiler-team/issues/621).

### CODE REVIEW

**Comment by tgross35** [comment]
@scottmcm looks like this may have been fixed a couple of days ago https://github.com/rust-lang/stdarch/pull/1630

**Comment by lqd** [comment]
Mostly doc builds that get slower when core/std are updated.

**Comment by pnkfelix** [comment]
Visiting for weekly perf triage.

* primary regressions are to cratelift-codegen llvm-opt-full and helloworld llvm-doc-full
* from the graphs, the cranelift regression looks like a blip, and the helloworld regression seems tiny compared to other changes in its history -- I infer the auto-computed significance threshold is quite low here, probably because historically the build time for helloworld is very stable?
* In any case, doesn't seem worth investigating. Marking as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
