### PR TITLE
Add a new lint `unneeded_where_clauses`, suggests removing empty where clauses

### LINKED ISSUE #125242: Empty where clauses don't have an unused warning
```rs
fn foo() where {}
```

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #125242

### CODE REVIEW

**Comment by cjgillot** [comment]
Would this be better placed in rustfmt?

**Comment by mu001999** [comment]
> Would this be better placed in rustfmt?

In fact, I find rustfmt has covered this, it will remove the `where` if it's empty.

**Review by compiler-errors — CHANGES_REQUESTED** [review]
I don't believe this should be made a lint in rustc, at least not first. Perhaps move this to clippy? Or yeah, as @cjgillot said, it may be better just as a formatting option.

**Comment by mu001999** [comment]
I agree, and rustfmt has covered this. We can get `fn foo() {}` from `fn foo() where {}` after formatting. So I think I can just close this.

**Pull request closed without merging**
