### PR TITLE
Disable backtraces on OSX

### LINKED ISSUE #45731: cargo test with RUST_BACKTRACE causes SIGBUS
On nightly channel, having `RUST_BACKTRACE=1` or `RUST_BACKTRACE=full` when running cargo test throws this error on any panic:

```
error: process didn't exit successfully: `/.../target/debug/deps/test_a-...`
(signal: 10, SIGBUS: access to undefined memory)
```

## Repro
```
#[test]
fn test_1() {
    assert!(false);
}
```

## Setup
- Rust version: rustc 1.23.0-nightly (2be4cc040 2017-11-01)
- OS and version: Darwin Marv.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR is a revert of #44251 which disables backtraces via `RUST_BACKTRACE=1` on OSX. It was discovered in https://github.com/rust-lang/rust/issues/45731 that OSX binaries generating a backtrace started generating a segfault in the range of https://github.com/rust-lang/rust/compare/4279e2b4c...8493813cd. The most likely candidate PR in that range is https://github.com/rust-lang/rust/pull/45400 which switched to compiling libtest with ThinLTO. Furthermore it's probably mostly likely that libbacktrace is segfaulting due to https://github.com/rust-lang/rust/issues/45511, or otherwise bad DWARF data in libtest.

Now the bad DWARF information is certainly a bug with ThinLTO that needs to be fixed! Despite this, however, this is a presumed resurgence of https://github.com/rust-lang/rust/issues/21889 where you can feed arbitrary data to libbacktrace effectively, and if it segfaults that's presumably a security vulnerability. In that sense a fix to DWARF + ThinLTO is not enough, but this indicates a deeper underlying problem that OSX binaries may be vulnerable to the situation described in https://github.com/rust-lang/rust/issues/21889.

As a result, this PR reverts backtrace support for OSX, which can return once we're confident enough in the implementation of libbacktrace for OSX. I'm also going to nominate this for a beta backport as it's something we'll want to get out pretty soon.

Closes #45731

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @rust-lang/libs 
cc @JohnColanduoni

**Comment by kennytm** [comment]
cc #24346

**Comment by sfackler** [comment]
Is there a way of doing this that's less invasive to the libbacktrace source?

**Comment by JohnColanduoni** [comment]
It's worth noting that if the vulnerability is indeed in the DWARF parser it is likely on other platforms as well; there is no OS X specific code in the DWARF parser and its interactions with it are minimal (it just searches for the appropriate named sections).

**Comment by JohnColanduoni** [comment]
I [tracked down](https://github.com/rust-lang/rust/issues/45731#issuecomment-341920778) the crash in https://github.com/rust-lang/rust/issues/45731. It turns out the `SIGBUS` was due to an IO error (attempt to access page in empty `mmap`ed file), not an errant memory access.

**Comment by alexcrichton** [comment]
Thanks for the investigation @JohnColanduoni! Do you have a fix available locally for this? If so I think we can probably just apply that and avoid reverting.

@sfackler probably, I just did the easiest thing of reverting the PR rather than trying to pick-and-choose what happened.

**Comment by sfackler** [comment]
Ah gotcha, I didn't realize the OSX stuff was already a patch on top of libbacktrace.

**Comment by JohnColanduoni** [comment]
@alexcrichton This should do it: https://github.com/rust-lang/rust/pull/45866.

**Comment by alexcrichton** [comment]
Awesome! Closing in favor of that

**Pull request closed without merging**
