### PR TITLE
Add specialization of `ToString for char`

### LINKED ISSUE #73462: bad performance of char literal to_string() vs str literal to_string()
I was quite surprised when I found out that 
```rust
pub fn conv() -> String {
    'a'.to_string()
}
```
generates several times the instruction count of
```rust
pub fn conv() -> String {
    "a".to_string()
}
```
(according to godbold).
Checking the (debug) build size of `println!("{}", "a".to_string());` vs `println!("{}", 'a'.to_string());` revealed the `str` variant being ~20kb lighter.

When doing some quick-and-dirty benchmarks, the `str` variant was more than 2x faster than the char-variant. [benchmark code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8695b47b5c9e41313e69eafe0c84855f)

````
test tests::bench_char_to_string ... bench:      39,890 ns/iter (+/- 42,078)
test tests::bench_str_to_string  ... bench:      14,422 ns/iter (+/- 2,427)
````

Is this something that could be optimized?

### PR DESCRIPTION
**Pull request by tesuji**
Closes #73462

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, this is an interesting case where AFAIK, there's no way to know this impl exists other than performance. I'm inclined to say it doesn't need FCP then. @rust-lang/libs, what do you think?

@lzutao Have you checked that this fixes the associated issue? Or we're just assuming it should?

**Comment by sfackler** [comment]
Is the prohibition on new specializations still in effect?

**Comment by Mark-Simulacrum** [comment]
Cc @matthewjasper @nikomatsakis

I think this is just expanding an existing specialization-available trait so we probably don't need to worry too much?

**Comment by matthewjasper** [comment]
I'm fine with this specialization being added. We use `min_specialization` everywhere apart from `core`, so I think that "we have some checks in place" for this.

**Comment by sfackler** [comment]
r=me assuming there aren't any objections on the specialization.

**Comment by lzutao** [comment]
Yes. The assembly code after this PR:
```asm
check_stage1::foo:
 push    rbx
 mov     rbx, rdi
 mov     edi, 1
 mov     esi, 1
 call    qword, ptr, [rip, +, __rust_alloc@GOTPCREL]
 test    rax, rax
 je      .LBB1_1
 mov     byte, ptr, [rax], 97
 mov     qword, ptr, [rbx], rax
 movaps  xmm0, xmmword, ptr, [rip, +, .LCPI1_0]
 movups  xmmword, ptr, [rbx, +, 8], xmm0
 mov     rax, rbx
 pop     rbx
 ret
.LBB1_1:
 mov     edi, 1
 mov     esi, 1
 call    alloc::raw_vec::RawVec<T,A>::allocate_in::{{closure}}
 ud2
```

where:
```rust
pub fn foo() -> String {
    'a'.to_string()
}
```

**Comment by SimonSapin** [comment]
`[97]` is UTF-8 for `a`, so it looks like all of `encode_utf8` was constant-folded in this example! With a `char` parameter instead of a constant the assembly code for `String::from(c.encode_utf8(&mut [0; 4]))` is longer, but still shorter than going through `Display`.

**Pull request merged**
