### PR TITLE
sync thread_local key conditions exactly with what the macro uses

### PR DESCRIPTION
**Pull request by RalfJung**
This makes the `cfg` in `mod.rs` syntactically the same as those in `local.rs`.

I don't think this should actually change anything, but seems better to be consistent?
I looked into this due to https://github.com/rust-lang/rust/issues/102549, but this PR would make it *less* likely that `__OsLocalKeyInner` is going to get provided, so this cannot help with that issue.

r? @thomcc

### CODE REVIEW

**Comment by thomcc** [comment]
Yep, LGTM.

@bors r+

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/102801#issuecomment-1272248258)

@bors r-

**Comment by matthiaskrgr** [comment]
@bors r- 
Failed in https://github.com/rust-lang/rust/pull/102801#issuecomment-1272248332

**Comment by RalfJung** [comment]
@thomcc I realized there is a smarter way to avoid the warning about `__FastLocalKeyInner` being unused -- and added that to this PR, since it touches that code anyway. Could you take a look?

**Comment by thomcc** [comment]
LGTM

@bors r+

**Comment by RalfJung** [comment]
More cases of unused `register_dtor`...
@bors r=thomcc

**Comment by RalfJung** [comment]
@thomcc looks like there is a test that directly accesses the private key types internal to the thread-locals macro

https://github.com/rust-lang/rust/blob/3568bdc6cdf04da3bf8f1be02741ea731265a3da/src/test/ui/threads-sendsync/issue-43733.rs#L15

I simply disabled that on wasm now, it probably predates our wasm/TLS support...
The test seems to be about the unsafety checker, not anything target-specific.

@bors r=thomcc

**Pull request merged**
