### PR TITLE
Enable const casting for `f16` and `f128`

### PR DESCRIPTION
**Pull request by tgross35**
I have an open PR to the Miri repo adding tests for this behavior https://github.com/rust-lang/miri/pull/3688, but that unfortunately hits the ICE path here. The changes seem reasonably low risk that it might be okay to merge separately from the tests, and I tested the result locally against an older version of https://github.com/rust-lang/miri/pull/3688.

Cc @RalfJung

### CODE REVIEW

**Review by oli-obk — APPROVED** [review]

**Comment by oli-obk** [comment]
bors r plus

**Comment by tgross35** [comment]
That was fast 😆 thanks!

**Comment by oli-obk** [comment]
Technically you should be able to test this from const eval now, right?

**Comment by tgross35** [comment]
Yeah I think this unblocks the only exposed codepath, the remaining changes in miri are just intrinsics. Miri just has a good structure for casting tests so it seems easiest to make use of what is there

**Pull request merged**
