### PR TITLE
Fixes #30521 and #30627 by adding new snapshots

### LINKED ISSUE #30521: FreeBSD build broken
rustc: x86_64-unknown-freebsd/stage0/lib/rustlib/x86_64-unknown-freebsd/lib/libcore
    src/libcore/nonzero.rs:45:15: 45:21 error: expected identifier, found keyword `unsafe`
    src/libcore/nonzero.rs:45     pub const unsafe fn new(inner: T) -> NonZero<T> {
                                            ^~~~~~
    src/libcore/nonzero.rs:45:22: 45:24 error: expected `:`, found `fn`
    src/libcore/nonzero.rs:45     pub const unsafe fn new(inner: T) -> NonZero<T> {
                                                   ^~
    /src/rust/mk/target.mk:194: recipe for target 'x86_64-unknown-freebsd/stage0/lib/rustlib/x86_64-unknown-freebsd/lib/stamp.core' failed
    gmake: *** [x86_64-unknown-freebsd/stage0/lib/rustlib/x86_64-unknown-freebsd/lib/stamp.core] Error 101

`git bisect` points to cd1848a1a60f40f.

cc @alexcrichton

### PR DESCRIPTION
**Pull request by dhuseby**
@alexcrichton please upload the following snapshots when landing this patch:
- https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2015-12-18-3391630-bitrig-x86_64-6476e1562df02389b55553b4c88b1f4fd121cd40.tar.bz2
- https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2015-12-18-3391630-freebsd-i386-7e624c50494402e1feb14c743d659fbd71b448f5.tar.bz2
- https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2015-12-18-3391630-freebsd-x86_64-91724d4e655807a2a2e940ac50992ebeaac16ea9.tar.bz2

I'm still working on dragonfly bsd.  it needs some maintenance love. 

thanks!

### CODE REVIEW

**Comment by dhuseby** [comment]
Fixes #30627 too.

**Comment by sfackler** [comment]
Was this intentionally merged into master?

**Comment by mneumann** [comment]
@dhuseby I build the 2015-12-18 snapshot for DragonFly: 

http://www.ntecs.de/downloads/rust/rust-stage0-2015-12-18-3391630-dragonfly-x86_64-e74d79488e88ac2de3bd03afd5959d2ae6e2b628.tar.bz2

You only need to patch the SIGSTACKSZ thing, then it builds fine, IIRC.

I also have pushed some patches to https://github.com/rust-lang-nursery/libc, which should help with building more recent versions of Rust (it is broken on libc).

**Comment by mneumann** [comment]
@dhuseby : If you need help with setting up continuous builds for DragonFly, please let me know.

**Comment by dhuseby** [comment]
@mneumann i will for sure.  so far it seems to be going well.

**Comment by mneumann** [comment]
@dhuseby : cool! Also feel free to submit a patch to etc/snapshots.txt for DragonFly :)

**Comment by dhuseby** [comment]
@mneumann I will add the dragonfly snapshot as soon as I can figure out how to get it to build at the last snap rev.

**Comment by mneumann** [comment]
@dhuseby : Ok, IIRC I had to patch SIGSTACKSZ constant in rust's libc. I just had to unfold it manually to it's value.

**Comment by pnkfelix** [comment]
Did anyone answer @sfackler 's question above?  Was there a reason this was directly pushed to master rather than going through bors?  (And I don't see any r+'s... ?)

**Comment by pnkfelix** [comment]
(having said that, the change seems pretty innocent...)

**Comment by dhuseby** [comment]
@pnkfelix it's because i'm dumb sometimes and i clicked the "merge" button here in github.

**Comment by dhuseby** [comment]
@pnkfelix what's the correct way to merge a PR into bors?

**Comment by sfackler** [comment]
"@bors r+"

**Comment by dhuseby** [comment]
@sfackler thanks!

**Comment by alexcrichton** [comment]
Thanks for the snapshots @dhuseby and @mneumann!  It looks like @dhuseby's snapshots have been uploaded (by @brson I guess?), but @mneumann it looks like the DragonFly snapshot is still missing and your link unfortunately has a host name that doesn't resolve for me. (in the future as well, could you guys also paste the sha256 with the links as well?)

And yeah @dhuseby just be careful not to merge manually, but no worries!

**Comment by mneumann** [comment]
@alexcrichton : I pushed the snapshot to @dhuseby 's repo. Then we both opened a pull requests probably at the same time. Next time sha256 :+1:

**Comment by alexcrichton** [comment]
@mneumann cool, thanks! I've uploaded that snapshot now

**Pull request merged**
