### PR TITLE
Add an impl for From trait

### PR DESCRIPTION
**Pull request by achanda**
Converts a u8 slice to a Ipv4Addr
More discussion on this here: https://github.com/rust-lang/rfcs/pull/1498#issuecomment-191921655

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I'll tag this with `T-libs` to make sure we chat about this during triage, and we'll likely discuss it along with the RFC at the same time.

**Comment by sfackler** [comment]
Could you add an explicit stability tag? It'll make it easier to tell in what release this impl was added.

**Comment by achanda** [comment]
@sfackler done!

**Comment by alexcrichton** [comment]
The libs team discussed this yesterday and the decision was to merge!

@bors: r+ ee18d8e99b03a451f9dd549fd756ce006134bd73

**Pull request merged**
