### PR TITLE
Emit noalias on &mut parameters by default

### PR DESCRIPTION
**Pull request by nikic**
This used to be disabled due to LLVM bugs in the handling of
noalias information in conjunction with unwinding. However,
according to #31681 all known LLVM bugs have been fixed by
LLVM 6.0, so it's probably time to reenable this optimization.

-Z no-mutable-noalias is left as an escape-hatch to debug problems
suspected to stem from this change.

### CODE REVIEW

**Comment by eddyb** [comment]
Shouldn't this be gated on the LLVM version? I think we still support distros using 3.9.
cc @alexcrichton @Gankro

**Comment by nikic** [comment]
@eddyb Good point, I've conditioned the default behavior on LLVM >= 6.0 now.

**Comment by alexcrichton** [comment]
@bors: r+

Nice!

**Comment by steveklabnik** [comment]
It'd be very cool to see any before/after benchmarks for this. I'm really curious as to how much of an impact it actually has.

**Comment by Gankro** [comment]
This is removing the panic=abort stable opt in. Is firefox on a new enough llvm that it won't regress?

**Comment by nikic** [comment]
@Gankro I've added back the panic=abort check just in case. Apparently Firefox is stuck on old Rust due to LLVM 6 regression in #49873.

**Comment by scottmcm** [comment]
http://perf.rust-lang.org/compare.html?start=8319ef5b78a10b3a8de4109bb8b0e6d23fbe4de1&end=bdace29de04af4fe9e4317b73c3f7d6418a33de1&stat=instructions%3Au

Looks like the Rust part of the compiler is faster, but the LLVM part spends more time optimizing.  So it seems promising for runtime perf; hopefully lolbench will confirm that.

**Pull request merged**
