### PR TITLE
remove `&'static` bound from type_id intrinsic (RFC 1849)

### PR DESCRIPTION
**Pull request by Avi-D-coder**
Reapplying of https://github.com/zackmdavis/rust/commit/8368e7ab2b28c6fea7a28c982646a8a57f93020d. If were lucky the hashing issue has been resolved, if not I'll work on it.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/rust/issues/41875 @eddyb 

Also marking as T-lang.

**Comment by eddyb** [comment]
@Avi-D-coder Out of curiosity, can you share what your usecase for this is?
So far most uses people come up with for this feature have been unsound, which make me worried every time I see activity around this.

**Comment by Avi-D-coder** [comment]
@eddyb as a parameter to optimize a custom allocators. It's not technically sound since there could be hash collision, but alignment and size also would have to collide, so I'm not very worried.

**Comment by Avi-D-coder** [comment]
Bad news the hash is still broken.

**Comment by eddyb** [comment]
@Avi-D-coder So this is just for a heuristic and you're not actually erasing the type and tracking the lifetime through some other way?

Hash collisions aren't *more* of a problem by themselves, since e.g. `Any` already relies on the hash.

What I'm worried about is someone making `AnyWithLifetime<'a>`, which is known to be impossible to do soundly without using certain language features which avoid the need for this change altogether.

If you're using nightly already (for this change to matter), have you tried trait specialization? Or are you limited in terms of when you have access to the type at compile-time?

**Comment by Avi-D-coder** [comment]
@eddyb I am planning on utilizing specialization as well, but in this case I need to remove the static bound to satisfy the `Alloc` trait.

**Comment by Centril** [comment]
I would personally like to rescind the original RFC with @eddyb's comments as a justification or at least I would want a whole lot more elaboration on the use-case (with code) before any changes are made here.

**Comment by Avi-D-coder** [comment]
I'm going to reopen this when I have code to show.

**Pull request closed without merging**
