### PR TITLE
Stabilize attribute macros on inline modules

### PR DESCRIPTION
**Pull request by petrochenkov**
While still gating non-inline modules in proc macro input.

Split from https://github.com/rust-lang/rust/pull/63931
cc https://github.com/rust-lang/rust/issues/54727

### CODE REVIEW

**Comment by petrochenkov** [comment]
## Stabilization report

Macro attributes are now supported on inline module items (`mod m { ... }`), the behavior is the same as for attributes on any other items available on stable.

The feature is a part of the franken-feature `#![feature(proc_macro_hygiene)]`.
The feature was implemented together with all other proc macro attributes on items somewhere in 2017-2018.
Its current instability is a collateral damage from attributes on *out-of-line* modules, which actually have unresolved questions (like whether the `mod` file should be loaded before expanding the macro or after, and what should proc macros do if they need to load files themselves).

**Comment by JohnCSimon** [comment]
Ping from triage:
@Centril Can you please reviwe this pr?
Thanks.

**Comment by Centril** [comment]
(triage: I'll look at this PR during the weekend.)

**Comment by Centril** [comment]
Declaring reviewer bankruptcy on this PR (sorry!) and reassigning to r? @pnkfelix who is considering the macro related changes together.

(I'm a bit bummed by the visitor approach that is unfortunately necessary to land this. From a compiler POV it's trivial but from a spec POV it's not.)

**Comment by petrochenkov** [comment]
>I'm a bit bummed by the visitor approach that is unfortunately necessary to land this.

FWIW, that's the same approach that is used for gating macro-expanded `macro_rules` until https://github.com/rust-lang/rust/pull/64035 lands.

**Comment by JohnCSimon** [comment]
Ping from triage
@petrochenkov Can you please address the merge conflicts? 
Thanks

**Comment by petrochenkov** [comment]
>Can you please address the merge conflicts?

Will do, after a review and FCP.

**Comment by joelpalmer** [comment]
Ping from triage: @Centril @pnkfelix @petrochenkov any updates? Should this have an FCP label?

**Comment by petrochenkov** [comment]
It would be great to get this into Rust 1.40 together with other macro stabilizations.
FCP process may take several weeks, so it's time to start thinking about this now.

**Comment by pnkfelix** [comment]
The @rust-lang/lang team discussed this in their weekly meeting [last week](https://github.com/rust-lang/lang-team/blob/master/minutes/2019-10-17.md#triage)

As noted in the [stabilization report](https://github.com/rust-lang/rust/pull/64273#issuecomment-529155541), it is a little concerning that stabilizing this will mean that we have the feature available for inline modules (`mod inl { #![inner] ... }`) but not for out-of-line modules (`mod outl;`).

This naturally raised a series of questions.

Could stabilizing the inline module case wait until *after* we resolve the questions about the behavior for out-of-line modules?

If it should not wait until that point, why? What is the use case we are trying to address by stabilizing this part alone?

**Comment by petrochenkov** [comment]
>Could stabilizing the inline module case wait until after we resolve the questions about the behavior for out-of-line modules?

It could, but there's no good reason to delay it for so long.
I thinks the preferable solution for out-of-line modules is to work on "unloaded" modules (e.g. to be able to unconfigure them and avoid file dependencies, `cfg`-style), but that requires supporting a file loading interface in proc macro API and I don't expect it happening in the near future.

>If it should not wait until that point, why? What is the use case we are trying to address by stabilizing this part alone?

Pretty much the same use case as stabilizing attributes on modules in general.
This PR gives a fundamental possibility to apply attributes to modules + we already have other stable ways to load files, so attributes on out-of-line modules can mostly be emulated like this:
```rust
// lib.rs
include!("my_file.rs");

// my_file.rs
#[attr]
mod inline { /* ... */ }
```
Support for `#[attr] mod out_of_line;` is a convenience on top of that + a way to avoid loading the file if `#[attr]` wants it.

**Comment by petrochenkov** [comment]
Also, we need to land the feature gating part of this PR (https://github.com/rust-lang/rust/pull/64273/commits/10df935cbadca4d5df8993e641f92371acf8a1df) regardless of stabilization because it prevents something really unstable, even if it's a corner case (the current behavior differs from the desirable behavior).

**Comment by petrochenkov** [comment]
cc https://github.com/rust-lang/rust/issues/64197 (somewhat related issue).

**Comment by JohnTitor** [comment]
Ping from triage: @pnkfelix any progress on this?

**Comment by pnkfelix** [comment]
@petrochenkov if there’s a part of this already factored into its own commit that *really* needs to land, should that be its own PR? Is it something you would argue should be beta backported?

I am trying to best represent the various viewpoints of the lang team here. 

As I already stated above, the inconsistency in support for inline versus out-of-line modules was a concern for some. When I asked for a “use case”, I meant a specific motivating example for why we want to add support for inner-attributes on modules as a feature if it can *only* be applied in the inline module case.
 * More specifically, I imagine some people would be surprised to discover that they can no longer cut-and-paste the contents of an inline `mod foo { ... }` into a file `current_mod/foo.rs`. (I suppose there are other cases that break that transformation, probably involving `include!`, but I consider those exceptions to the general rule.)

**Comment by Mark-Simulacrum** [comment]
(We are almost out of time for beta backports, for what it's worth -- the plan is to promote beta into stable tomorrow, so if you're planning a last minute backport please notify me on Zulip/Discord so we can coordinate that).

**Comment by pnkfelix** [comment]
Reading over this again, I was tempted to suggest that we restrict the stabilization solely to outer-attributes on modules; then inline and out-of-line modules would offer the same set of functionality with respect to proc-macro attributes.

But then I realized that this “compromise” in the name of supposed consistency is really just trading one inconsistency (inline vs out-of-line modules) for another (inner vs outer attributes) ... and I have to admit that its a pretty weird trade off,

**Comment by pnkfelix** [comment]
Nominating for discussion at lang team meeting. I suspect that team members *will* appreciate that we want to stabilize support for *at least* outer-attributes (on either inline or out-of-line modules(, and that then just leads to the question, as I noted in my previous comment, of which kind of “inconsistency” does the least harm.

**Comment by Robbepop** [comment]
As for having a use case:
At Parity we develop an EDSL embedded into Rust to allow writing smart contracts for certain blockchains.
We use custom proc. macro attributes in order to integrate the EDSL seamingless into Rust.
Here is a link to one of the examples:
https://github.com/paritytech/ink/blob/robin-ink-lang2/examples/lang2/delegator/lib.rs
The huge advantage of custom attributes over normal proc macro invokation is that Rust tools such as rustfmt can handle it. Also syntactically the EDSL embedding looks more like natural Rust code.

Due to the known limitations we currently do not support multi-line projects but I think either of the proposed ways could work for us. (E.g. expanding out-of-line modules by the compiler or by ourselves via include_bytes) However, we hope for a robust, non-hacky solution to do this in the end.

**Comment by petrochenkov** [comment]
@pnkfelix 
Regarding inner attributes (`#![inner]`) - they are not a part of the stabilization here because they are unstable for unrelated issues (whether they are used with a `mod` item or not).
The tracking issue for them is https://github.com/rust-lang/rust/issues/54726.
There's a path to stabilization (https://github.com/rust-lang/rust/issues/54726#issuecomment-431931811), but it requires some implementation work.

So, this PR is only about outer attributes.

**Comment by petrochenkov** [comment]
@Mark-Simulacrum 
>We are almost out of time for beta backports, for what it's worth -- the plan is to promote beta into stable tomorrow

I don't think any of this targets 1.39 and needs a backport before the upcoming promotion.
We'll have to backport to 1.40 beta during the next 6 weeks at worst.

**Comment by pnkfelix** [comment]
> @pnkfelix
> Regarding inner attributes (`#![inner]`) - they are not a part of the stabilization here because they are unstable for unrelated reasons (whether they are used with a `mod` item or not).
> The tracking issue for them is #54726.
> There's a path to stabilization ([#54726 (comment)](https://github.com/rust-lang/rust/issues/54726#issuecomment-431931811)), but it requires some implementation work.
> 
> So, this PR is only about outer attributes.

Hmm I think the lang team was confused about this detail (or maybe just *I* was confused during that conversation).

All the better that this has been nominated for discussion again, in that case.

**Comment by pnkfelix** [comment]
> @Mark-Simulacrum
> 
> > We are almost out of time for beta backports, for what it's worth -- the plan is to promote beta into stable tomorrow
> 
> I don't think any of this targets 1.39 and needs a backport before the upcoming promotion.
> We'll have to backport to 1.40 beta during the next 6 weeks at worst.

(Yeah, that was my fault: I was not clear enough about *which* beta I was talking about hypothetically backporting to. Sorry about the confusion there @Mark-Simulacrum and @petrochenkov )

**Comment by JohnTitor** [comment]
Ping from triage: @pnkfelix what's the status of this PR? is there any discussion on the lang team?

**Comment by pnkfelix** [comment]
We discussed this in recent lang team meetings.

The general agreement was that in the long term, we should resolve the semantics for how expansion interacts with out-of-line modules, which raises issues (aka technical artifacts, aka warts) such as the ones documented at #64197.
  * The feeling of the room was that we probably want a "lazy loading" semantics for out-of-line modules
  * The decision there should probably be handled by some shepherded group (it does not need to involve the entire lang team).

But we don't have to solve the problem of out-of-line modules now: The semantics that is being stabilized here for attributes on inline modules seems like the reasonable one to adopt, and however we resolve the out-of-line module case should be compatible with what is being stabilized here.


The notes from the language team meeting include the following suggestion for the documentation: 
> Documentation: “Note that an out-of-line module, `mod foo;`, appears to any macro as just that item; the macro does not run over the contents of the module.”

 * I'll be honest here: I, pnkfelix, had thought (and still think) that the state proposed by this PR was that procedural macros simply could not be be *stably* applied to an item that contains any out-of-line module declaration. So I don't know if the above suggestion was meant to enhance documentation of the *unstable* feature, or if I actually misunderstand what is being stabilized here.
* In any case, we do need to make sure that the documentation for this includes some text about the behavior of how out-of-line modules declarations `mod foo;` within other items are treated, even if the answer is "It is a static error to have an out-of-line module declaration within an item that fed as input to a procedural attribute macro."

----

In case you cannot tell, I was writing the above up as notes to prepare an FCP merge command.

But given the questions I ended up posing to myself at the end of the notes, I want to hold off on actually issuing the FCP merge request until I have privately resolved my questions. I'm going to download this branch and play with it locally to try to ensure I understand the implications before firing off the FCP merge.

**Comment by pnkfelix** [comment]
Okay, I think I have reconciled the points that I noted in my earlier comment.

The reason it probably makes sense to include documentation about the current semantics, even though the feature is unstable, is that the proc-macro's **are** executed with the given inputs, before the stability error is issued. In other words, the macros observe the current token streams you get for out-of-line modules (and may exhibit some behavior based upon them), and thus it makes sense for us to document that.

I also double-checked the current test suite. The tests that are affected by this are:
 *  https://github.com/rust-lang/rust/blob/b19c72b838c0cae8fd1200bba8058430301118f0/src/test/ui/proc-macro/attributes-on-modules-fail.rs#L6-L27
 * https://github.com/rust-lang/rust/blob/b19c72b838c0cae8fd1200bba8058430301118f0/src/test/ui/proc-macro/attributes-on-modules.rs#L7-L10

It would be good for the test suite to be expanded to include the case of modules within non-module blocks, like this:

```rust
#[identity_attr]
fn bar() { #[path="outline_f.rs"] mod outline_f; }
```

But I do not think the addition of that test needs to hold this PR up.

(More information about what I did in the details block.)

<details>

I built this branch locally, made an attribute macro named `#[styx]` (that just clones the input, prints it, and returns the original input), and ran it on a test like this:

```rust
#[styx]
mod inline_a { }

// OKAY
#[styx]
mod inline_b { mod inline_b1 {  } }

// OKAY
#[styx]
fn foo() { mod inline_c { } }

// Got: error[E0658]: non-inline modules in proc macro input are unstable
#[styx]
mod outline_d;

// Got: error[E0658]: non-inline modules in proc macro input are unstable
#[styx]
mod inline_e { mod outline_e1; }

// FYI: Without a `path` attribute, this gets "Cannot declare a non-inline module inside a block unless it has a path attribute" (which seems good to me)
//
// Got: error[E0658]: non-inline modules in proc macro input are unstable
#[styx]
fn bar() { #[path="outline_f.rs"] mod outline_f; }

// OKAY
//
// Contains the text:
// ```
// use styx::styx;
//
// #[styx]
// mod inline_g1 { }
// ```
mod outline_g;
```

</details>

**Comment by pnkfelix** [comment]
I had originally written that merging this PR need not be held up on waiting for the addition of the test case I requested above. (And I still do believe that to be true.)

However, I do think the requested documentation addition *should* be part of the stabilization here.

I don't have time at the moment to try to figure out where that documentation addition belongs. 

@petrochenkov , if you have time in the next 24 hours or so to add that sentence in the appropriate place (and, if you can, the test I requested), then I'll issue an FCP merge request.

Otherwise, if you don't have time, I'll try to figure it out myself tomorrow.

**Comment by Robbepop** [comment]
> The reason it probably makes sense to include documentation about the current semantics, even though the feature is unstable, is that the procedural macros are executed with the given inputs, before the stability error is issued. In other words, the macros observe the current token streams you get for out-of-line modules (and may exhibit some behavior based upon them), and thus it makes sense for us to document that.

What probably some proc. macros might want to do is to load those out-of-line modules into their attributed module definition. Would it make sense to also provide documentation about how those users should probably be tackling this issues as long as there are no stable alternatives? Recommendations how to tackle this potentially very common use case might be of use.

**Comment by pnkfelix** [comment]
> What probably some proc. macros might want to do is to load those out-of-line modules into their attributed module definition. Would it make sense to also provide documentation about how those users should probably be tackling this issues as long as there are no stable alternatives? Recommendations how to tackle this potentially very common use case might be of use.

Hmm. Establishing what the best-practices/recommendations are for those scenarios sounds like something that *could* be done with this PR, but it could also wait until later, no?

Or at least, I personally don't feel comfortable trying to devise what the best-practices are there, but I also don't feel comfortable blocking stabilization of the *inline* module case on the development of those best-practices.

**Comment by pnkfelix** [comment]
Further discussion in tonight's lang team meeting led the T-lang members present to conclude that the FCP merge request does not need to be blocked on either of the points (the test I requested and the documentation addition).

So, having said that:

@rfcbot fcp merge

**Comment by petrochenkov** [comment]
Updated with the requested tests.

**Comment by petrochenkov** [comment]
@pnkfelix 
>The reason it probably makes sense to include documentation about the current semantics, even though the feature is unstable, is that the procedural macros are executed with the given inputs

I'm not even sure what the current semantics are, it may depend on whether expansion goes through pretty-printing or not, and whether nested modules are involved.
I don't want to spend time investigating the details now, but once https://github.com/rust-lang/rust/issues/64197 is implemented, the macros will certainly get tokens `mod name ;` as an input.

@Robbepop 
>What probably some proc. macros might want to do is to load those out-of-line modules into their attributed module definition. Would it make sense to also provide documentation about how those users should probably be tackling this issues as long as there are no stable alternatives?

https://github.com/rust-lang/rust/pull/64273#issuecomment-546607721 mentions a practice that can hardly be named "best", but works (including on stable, after this PR is merged).
```rust
// lib.rs
include!("my_file.rs");

// my_file.rs
#[my_attr]
mod inline { /* ... */ }
```

**Comment by petrochenkov** [comment]
Okay, I'm going to beta nominate this since there's still chance to get this into 1.40.

Q: Why we need to backport this to beta.
A: To get all the recent macro stabilizations into one release, which can be a new reference point for macro authors. This will also make a better announcement post.
The PR was submitted more than 3 months and 2 releases ago and was supposed to land together with other macro features (https://github.com/rust-lang/rust/pull/63931, https://github.com/rust-lang/rust/pull/64035, https://github.com/rust-lang/rust/pull/63674) that went through review faster.

Q: Why we can backport this.
A: The change (excluding tests) is tiny and trivial.

**Comment by Mark-Simulacrum** [comment]
If this is to get accepted into beta before branching (and I don't really want to, but do see that it could plausibly be done) it would need to happen in the next ~4 days or so before beta branches next week. It would likely be best to bring it up for acceptance at tomorrow's compiler team (planning) meeting; cc @pnkfelix @nikomatsakis

**Comment by nikomatsakis** [comment]
We decided against backport in [today's design meeting](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/design.20meeting.202019-12-13) on the basis of the the general rule of "don't backport stabilizations without a very strong reason".

**Comment by petrochenkov** [comment]
Sigh, okay.

**Pull request merged**
