### PR TITLE
Make the Entry API of HashMap<K, V> Sync and Send

### LINKED ISSUE #45219: std::collections::hash_map::{Entry, OccupiedEntry, VacantEntry} are never Send/Sync
Currently, the `HashMap` entry types are never `Send` or `Sync`. It seems to me that the `Entry` types should be `Send` whenever their key/value types are `Send` and `Sync` whenever their key/value types are `Sync`. Properly implementing `Send`/`Sync` for `OccupiedEntry` and `VacantEntry` will solve the problem for `Entry` as well. Is there any known reason why `Entry` and friends should *not* be `Send` or `Sync`?

### PR DESCRIPTION
**Pull request by nox**
Fixes #45219

### CODE REVIEW

**Comment by alexcrichton** [comment]
Would it be possible to place these impls at the root cause of why they're not send/sync today? Placing them so high up looks pretty tricky and error prone

**Comment by nox** [comment]
Not really, see [my comment](https://github.com/rust-lang/rust/issues/45219#issuecomment-462151983) in [the issue](https://github.com/rust-lang/rust/issues/45219):

If we make `table::RawBucket` `Send` and `Sync` itself, then `table::Iter` will have an auto implementation of `Send` where `K: Send, V: Send`, which is incorrect. I would rather have additional impls on the leafs (here `OccupiedEntry` and `VacantEntry`) than implementation at the root which can then cause error-prone auto implementations on other leaves.

**Comment by nox** [comment]
`BTreeMap` avoids this issue through a marker on `NodeRef`, but hash tables lack such a concept.

https://github.com/rust-lang/rust/blob/57d7cfc3cf50f0c427ad3043ff09eaef20671320/src/liballoc/collections/btree/node.rs#L348-L351

**Comment by alexcrichton** [comment]
@Amanieu having likely looked at the internals here more recently than I, would you be willing to review this?

**Comment by Amanieu** [comment]
`Entry` is already Send+Sync in hashbrown, so this change looks fine to me.

Do we want to gate this behind a feature or should we just make it immediately stable? I don't think this change is very controversial.

**Comment by alexcrichton** [comment]
We don't have a way to gate impls like these currently, so it'll be insta-stable. In that case though I'll...

r? @Amanieu

**Comment by Amanieu** [comment]
@nox Can you remove the unstable feature and just mark the Send/Sync impls as stable?

**Comment by Amanieu** [comment]
ping @nox

**Comment by nox** [comment]
What version number should I put in the attribute?

**Comment by Amanieu** [comment]
Since this really should have been done since 1.0, just use the same as the `Entry` API itself:

```
#[stable(feature = "rust1", since = "1.0.0")]
```

**Comment by nox** [comment]
Fixed!

**Comment by Elarnon** [comment]
Won't using `since = "1.0.0"` be confusing for people trying to figure out why sharing entries doesn't work with old versions of Rust when the official docs says it should?  I know I would be confused had I not stumbled on this issue by accident.

**Pull request merged**
