### PR TITLE
Rollup of 3 pull requests

### PR DESCRIPTION
**Pull request by workingjubilee**
Successful merges:

 - #129642 (Bump backtrace to 0.3.74~ish)
 - #129733 (Subtree update of `rust-analyzer`)
 - #129785 (Miri subtree update)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=129642,129733,129785)

### CODE REVIEW

**Comment by workingjubilee** [comment]
Allowing these to try to preempt the [beta bump](https://github.com/rust-lang/rust/pull/129790) on the hypothesis that these are already-tested code that may be fixing some regression somewhere. Indeed, [Veykril is already concerned about a backport].

It's not the end of the world if they don't go through, though, so there's not really much worry if they don't before the beta bump has landed.

**Comment by workingjubilee** [comment]
...can that replicate?
@bors retry

**Comment by workingjubilee** [comment]
...okay, that did not replicate.
That trap, uhh, if memory serves...
...I love it when my C frontend is probably hitting UB in its preprocessor expansion code!

**Comment by workingjubilee** [comment]
Eh, c'est la vie~

**Comment by matthiaskrgr** [comment]
partially merged  already in https://github.com/rust-lang/rust/pull/129809

**Pull request closed without merging**
