### PR TITLE
Update cargo, rls

### PR DESCRIPTION
**Pull request by ehuss**
26 commits in b3d0b2e545b61d4cd08096911724b7d49d213f73..5e85ba14aaa20f8133863373404cb0af69eeef2c
2018-11-15 19:13:04 +0000 to 2018-12-02 14:37:25 +0000
- ConflictStoreTrie: Faster filtered search (rust-lang/cargo#6366)
- Remove `cmake` as a requirement (rust-lang/cargo#6368)
- progress: display "Downloading 1 crate" instead of "Downloading 1 crates" (rust-lang/cargo#6369)
- Use expect over unwrap, for panic-in-panic aborts (rust-lang/cargo#6364)
- Switch to pretty_env_logger, under --features pretty-env-logger (rust-lang/cargo#6362)
- use allow-dirty option in `cargo package` to skip vcs checks (rust-lang/cargo#6280)
- remove clones made redundant by Intern PackageId (rust-lang/cargo#6352)
- docs: correct profile usage of `cargo test --release` (rust-lang/cargo#6345)
- Improve doc for `cargo install` (rust-lang/cargo#6354)
- Intern PackageId (rust-lang/cargo#6332)
- Clean only release artifacts if --release option is set (rust-lang/cargo#6349)
- remove clones made redundant by Intern SourceId (rust-lang/cargo#6347)
- Intern SourceId (rust-lang/cargo#6342)
- Tweak Layout to allow for non json file targets with internal "." (rust-lang/cargo#6255)
- Correct Target Directory command-line option (rust-lang/cargo#6343)
- Persistent data structures by im-rs (rust-lang/cargo#6336)
- Move command prelude into main library (rust-lang/cargo#6335)
- Distinguish custom build invocations (rust-lang/cargo#6331)
- Allow crate_type=bin examples to run (rust-lang/cargo#6330)
- Make verify-project honour unstable features (rust-lang/cargo#6326)
- Make autodiscovery disable inferred targets (rust-lang/cargo#6329)
- Add `c` alias for `check` (rust-lang/cargo#6218)
- Allow user aliases to override built-in aliases (rust-lang/cargo#6259)
- Fix renaming directory project using build scripts with cross-compiling. (rust-lang/cargo#6328)
- Fix add_plugin_deps-related tests. (rust-lang/cargo#6327)
- Add a glossary. (rust-lang/cargo#6321)

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by Centril** [comment]
`distcheck` isn't happy with the MPL 2.0 license in `im-rc` here which is why https://github.com/rust-lang/rust/pull/56427 failed.

**Comment by alexcrichton** [comment]
@bors: r+

Yeah this should be ok!

The `tidy` step only checks licenses if the sources are vendored, and the sources have to be pre-vendored IIRC. I think this largely only runs on the distcheck step.

It probably wouldn't be too hard to though to download a prebuilt `cargo vendor` on CI (by default, for all PRs) and run the check!

**Comment by ehuss** [comment]
Rebased, and also updated with the last week's worth of updates.

**Comment by ehuss** [comment]
Hm, I even ran `x.py test src/tools/rls` but because it exited 0 with success, I didn't see the error message.  It looks like it was intentionally changed to do that in #50123.

Is there some way I can force `x.py` to fail if rls fails to build and run tests?

RLS PR posted at rust-lang/rls#1160.

**Comment by kennytm** [comment]
@ehuss That's strange. `x.py test src/tools/rls` should have emitted with error during the "build" step, what #50123 does is do not ignore this error state when `--no-fail-fast` is provided.

**Comment by alexcrichton** [comment]
Hm it looks like this needs to update RLS?

```
[01:19:20] [0m[1m[38;5;9merror[E0053][0m[0m[1m: method `exec` has an incompatible type for trait[0m

[01:19:20] [0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/tools/rls/src/build/cargo.rs:413:5[0m

[01:19:20] [0m    [0m[0m[1m[38;5;12m|[0m

[01:19:20] [0m[1m[38;5;12m413[0m[0m [0m[0m[1m[38;5;12m| [0m[0m[1m[38;5;9m/[0m[0m [0m[0m    fn exec([0m

[01:19:20] [0m[1m[38;5;12m414[0m[0m [0m[0m[1m[38;5;12m| [0m[0m[1m[38;5;9m|[0m[0m [0m[0m        &self,[0m

[01:19:20] [0m[1m[38;5;12m415[0m[0m [0m[0m[1m[38;5;12m| [0m[0m[1m[38;5;9m|[0m[0m [0m[0m        mut cargo_cmd: ProcessBuilder,[0m

[01:19:20] [0m[1m[38;5;12m416[0m[0m [0m[0m[1m[38;5;12m| [0m[0m[1m[38;5;9m|[0m[0m [0m[0m        id: &PackageId,[0m

[01:19:20] [0m[1m[38;5;12m...[0m[0m   [0m[0m[1m[38;5;9m|[0m

[01:19:20] [0m[1m[38;5;12m608[0m[0m [0m[0m[1m[38;5;12m| [0m[0m[1m[38;5;9m|[0m[0m [0m[0m        Ok(())[0m

[01:19:20] [0m[1m[38;5;12m609[0m[0m [0m[0m[1m[38;5;12m| [0m[0m[1m[38;5;9m|[0m[0m [0m[0m    }[0m

[01:19:20] [0m    [0m[0m[1m[38;5;12m| [0m[0m[1m[38;5;9m|_____^[0m[0m [0m[0m[1m[38;5;9mexpected struct `cargo::core::package_id::PackageId`, found reference[0m

[01:19:20] [0m    [0m[0m[1m[38;5;12m|[0m

[01:19:20] [0m    [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: expected type `[0m[0m[1mfn(&build::cargo::RlsExecutor, cargo::util::process_builder::ProcessBuilder, cargo::core::package_id::PackageId, &cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode) -> std::result::Result<(), failure::error::Error>[0m[0m`[0m

[01:19:20] [0m               found type `[0m[0m[1mfn(&build::cargo::RlsExecutor, cargo::util::process_builder::ProcessBuilder, &cargo::core::package_id::PackageId, &cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode) -> std::result::Result<(), failure::error::Error>[0m[0m`[0m

[01:19:20] 

[01:19:21] [0m[1m[38;5;9merror[0m[0m[1m: aborting due to previous error[0m
```

**Comment by ehuss** [comment]
> @ehuss That's strange. `x.py test src/tools/rls` should have emitted with error during the "build" step, what #50123 does is do not ignore this error state when `--no-fail-fast` is provided.

There is an error, but `x.py` reports success.  I actually run it as part of a script, in this case it ran `x.py test src/tools/rls src/tools/cargo`, and the script only stops if it returns nonzero, and the error message had scrolled way off the screen so I didn't see it. It hits [this code path](https://github.com/rust-lang/rust/blob/7139e1c3ab0f6b912955f27a0f7df13c582ce5ec/src/bootstrap/test.rs#L283-L286) which does not report an error.

It looks like the only way to check for failure is to run `checktools.sh` which requires testing all the tools. Would it be feasible to have the Rls test step to check some option and report an error if it fails to build? I don't see how that PR involves `--no-fail-fast`, but that would be fine with me.  I tried running with that flag, but it still reported success.

> Hm it looks like this needs to update RLS?

@alexcrichton see above, I was waiting for the RLS PR to be merged.  It now is, and I have included the RLS update.

**Comment by kennytm** [comment]
@ehuss My point is when RLS failed to build it should have hit

https://github.com/rust-lang/rust/blob/9cd3bef4cfaaac2a608682d4b0834cda344249e0/src/bootstrap/tool.rs#L189-L191

and exit with code 1. The problem is RLS is considered an `is_optional_tool` and returned None instead. It should only continue when `--no-fail-fast` is passed.

**Comment by ehuss** [comment]
>  It should only continue when `--no-fail-fast` is passed.

I'm not sure I understand. Wouldn't that cause a problem, because none of the CI jobs pass that option (except for `checktools.sh`), they would always fail if rls fails to build?  

I realize my use-case is unique (I want to ensure cargo updates don't break rls before posting a PR). I'd be reluctant to add an option just for that, but I don't see any existing options that can be used safely.

**Comment by ehuss** [comment]
This should be ready to go, btw.

**Comment by ehuss** [comment]
`Could not resolve host: github.com` 😭

**Pull request merged**
