### PR TITLE
Change AdtDef's `PartialEq` and `Hash` impls to use `DefId`

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Note that due to merging https://github.com/rust-lang/rustc-perf/pull/1123, these runs may look quite bad -- once we get another master commit landed + benchmarked, re-running perf should make any noise there go away. It shouldn't affect non-incremental results, though, of course.

(Leaving this comment on all pending perf run PRs).

**Comment by Aaron1011** [comment]
Re-running to get accurate incremental perf results:

@bors try @rust-timer queue

**Comment by Aaron1011** [comment]
Merged as part of https://github.com/rust-lang/rust/pull/91924

**Pull request closed without merging**
