### PR TITLE
Introduce LinkedList::drain_filter

### PR DESCRIPTION
**Pull request by udoprog**
This introduces `LinkedList::remove_if`.

This operation embodies one of the use-cases where `LinkedList` would typically be preferred over `Vec`: random removal and retrieval.

There are a number of considerations with this:

Should there be two `remove_if` methods? One where elements are only removed, one which returns a collection of removed elements.

Should this be implemented using a draining iterator pattern that covers both cases? I suspect that would incur a bit of overhead (moving the element into the iterator, then into a new collection). But I'm not sure. Maybe that's an acceptable compromise to maximize flexibility.

I don't feel I've had enough exposure to unsafe programming in rust to be certain the implementation is correct. This relies quite heavily on moving around copies of Shared pointers to make the code reasonable. Please help me out :).

### CODE REVIEW

**Comment by kennytm** [comment]
This PR introduces a new method. Deferring the decision to the libs team. 

r? @dtolnay

**Review by dtolnay — CHANGES_REQUESTED** [review]
[`Vec::drain_filter`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.drain_filter) is a much more general and equally efficient form of `remove_if` where the caller can do whatever they want with the removed values (building a new LinkedList of them, as with `remove_if`, seems like an uncommon use case). The equivalent of your example code would be:

```rust
let mut d = LinkedList::new();
d.push_back(1);
d.push_back(2);
d.push_back(3);

let mut removed = LinkedList::new();
for node in d.drain_filter(|v| *v < 3) {
    removed.push_back(node);
}
assert_eq!(removed.len(), 2);
assert_eq!(d.len(), 1);
```

I would prefer to be consistent by providing the same API for LinkedList.

**Comment by udoprog** [comment]
@dtolnay will do, that also answers most of my questions. Thanks!

**Comment by udoprog** [comment]
Relates to rust-lang/rfcs#2140

**Comment by udoprog** [comment]
I ported all the tests on `Vec` for `drain_filter`. Would be nice to abstract them, but I felt that would be a change that is a bit too large for my taste.

All changes are now also associated with the `drain_filter` feature.

**Comment by bluss** [comment]
Consistency is important. Note however that Linked List can do this kind of operation -- remove some elements during the scan and string them together a resulting linked list of the removed elements -- _without any de/allocation_ of list nodes at all. It would be good to expose that functionality as well, but it is kind of its own kind of operation.

**Comment by udoprog** [comment]
The original patch did something like that. It could at some point be resurrected as a method on `DrainFilter` if it's deemed important.

I'd be curious to see how well the optimizer deals with the example provided by @dtolnay. I wouldn't be surprised if specialized methods aren't needed.

**Comment by bluss** [comment]
This could be covered with specialization. Imagine `LinkedList::extend(into iter)` and `LinkedList::extend(drain_filter)` (extend brings collect with it implicitly) both can get this specialization, to just reuse the list nodes. It's got an appeal of not needing any additional API design and it hits consistency as well.

**Comment by udoprog** [comment]
Since the extend approach is compatible with a draining iterator it can be introduced separately.

@dtolnay With this in mind, can I get another round of review?

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
