### PR TITLE
`rustc_on_unimplemented` supports referring to trait

### PR DESCRIPTION
**Pull request by estebank**
Add support to `rustc_on_unimplemented` to reference the full path of
the annotated trait. For the following code:

```rust
pub mod Bar {
    #[rustc_on_unimplemented = "test error `{Self}` with `{Bar}` `{Baz}` `{Quux}` in `{Foo}`"]
    pub trait Foo<Bar, Baz, Quux> {}
}
```

the error message will be:

```
test error `std::string::String` with `u8` `_` `u32` in `Bar::Foo`
```

### CODE REVIEW

**Comment by estebank** [comment]
Originally found that this would be a nice addition when working on #43001, to make sure that the path of the trait is always correct on the error message.

**Comment by Mark-Simulacrum** [comment]
```
[00:03:27] Expected a gate test for the feature 'on_unimplemented'.
[00:03:27] Hint: create a file named 'feature-gate-on_unimplemented.rs' in the compile-fail
[00:03:27]       test suite, with its failures due to missing usage of
[00:03:27]       #![feature(on_unimplemented)].
[00:03:27] Hint: If you already have such a test and don't want to rename it,
[00:03:27]       you can also add a // gate-test-on_unimplemented line to the test file.
[00:03:27] tidy error: Found 1 features without a gate test.
[00:03:27] some tidy checks failed
[00:03:27] 
[00:03:27] 
[00:03:27] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/tidy" "/checkout/src" "--no-vendor" "--quiet"
[00:03:27] expected success, got: exit code: 1
[00:03:27] 
[00:03:27] 
[00:03:27] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:27] Build completed unsuccessfully in 0:01:00
[00:03:27] make: *** [tidy] Error 1
[00:03:27] Makefile:74: recipe for target 'tidy' failed
```

**Comment by aidanhs** [comment]
@estebank looks like the tidy failure is still waiting on you? Might be worth getting it fixed before review in case it reveals any other test failures.

**Comment by aidanhs** [comment]
Oh wait, you just pushed a change :)

**Comment by aidanhs** [comment]
Some other test failures have been revealed
```
[01:09:26] error[E0232]: this attribute must have a value
[01:09:26]   --> $DIR/bad-annotation.rs:26:1
[01:09:26]    |
[01:09:26] 26 | #[rustc_on_unimplemented] //~ ERROR this attribute must have a value
[01:09:26]    | ^^^^^^^^^^^^^^^^^^^^^^^^^ attribute requires a value
[01:09:26]    |
[01:09:26]    = note: eg `#[rustc_on_unimplemented = "foo"]`
[01:09:26] 
[01:09:26] error[E0230]: there is no type parameter C on trait BadAnnotation2
[01:09:26]   --> $DIR/bad-annotation.rs:30:1
[01:09:26]    |
[01:09:26] 30 | #[rustc_on_unimplemented = "Unimplemented trait error on `{Self}` with params `<{A},{B},{C}>`"]
[01:09:26]    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01:09:26] 
[01:09:26] error[E0231]: only named substitution parameters are allowed
[01:09:26]   --> $DIR/bad-annotation.rs:35:1
[01:09:26]    |
[01:09:26] 35 | #[rustc_on_unimplemented = "Unimplemented trait error on `{Self}` with params `<{A},{B},{}>`"]
[01:09:26]    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01:09:26] 
[01:09:26] error: aborting due to 3 previous errors
```

**Comment by arielb1** [comment]
I don't think `rustc::traits` should be having an error reporting logic distinct from typeck, but let's leave that refactoring to a separate PR.

**Comment by arielb1** [comment]
LGTM

@bors r+

**Pull request merged**
