### PR TITLE
Miscellaneous refactors around how lints and typeck interact

### LINKED ISSUE #39495: Encapsulate used-trait-imports set from typeck into per-fn-node tables
**Background:** See the [general plan for skipping typeck](https://gist.github.com/nikomatsakis/0e225faaa35d5762e96d289cdfe1a4af).

Currently we write to a table in the tcx that is not tracked. We need to have each fn's results preserved somewhere so they can be reloaded from incr. state and recombined without re-running typeck.

Pending PR: https://github.com/rust-lang/rust/pull/39434

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is preparation for making incr. comp. skip typeck. The main gist of is trying to rationalize the outputs from typeck that are not part of tables:

- one bit of output is the `used_trait_imports` set, which becomes something we track for dependencies
- the other big of output are various lints; we used to store these into a table on sess, but this work stores them into the`TypeckTables`, and then makes the lint pass consult that
    - I think it probably makes sense to handle errors similarly, eventually, but that's not necessary now

r? @eddyb 

Fixes #39495

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@eddyb I reworked this branch substantially, so you probably want to take another look. In particular, I did the following

- tightened up `DepTrackingMap` (e.g., preventing duplicate writes in many situations)
     - it still permits some dynamic patterns I'd prefer to forbid, but that will take more work
- change the trait import strategy to something that will actually work for incremental
- fixed the `'tcx` thing you were complaining about

**Comment by eddyb** [comment]
@nikomatsakis r=me but some of the incremental tests are failing (see Travis).

**Comment by nikomatsakis** [comment]
@eddyb ah, strange, I thought they passed locally, but ... I'll figure it out.

/me grumpy.

**Pull request merged**
