### PR TITLE
Perform SimplifyLocals before ConstProp.

### PR DESCRIPTION
**Pull request by cjgillot**
MIR before `ConstProp` may have a lot of dead writes, this makes `ConstProp` do unnecessary work.

r? @ghost

### CODE REVIEW

**Comment by cjgillot** [comment]
r? compiler

**Comment by Mark-Simulacrum** [comment]
Regression appears to not be noise (at least in serde-derive). The previous perf run didn't show that regression, so I wonder if there were perhaps changes made after it, @cjgillot, that may have led to a regression were there wasn't one before?

**Comment by saethlin** [comment]
I saw commentary about this in the t-compiler meeting today.

I have seen fluctuations of almost exactly that magnitude in serde_derive opt+full. The syn opt+full benchmark has a pretty incredible significance threshold, and I think whatever instability is driving that is bleeding into serde_derive.

**Comment by saethlin** [comment]
Ah sorry I think I wasn't clear. I'm not saying this is _noise_. I'm saying that small perturbations to the input produce hard-to-predict swings of about this magnitude to this benchmark (examples of what I've seen below). And if that is the case, the regression in this benchmark is real, but the next perturbation to MIR optimizations is reasonably likely to accidentally cause the benchmark to swing back to its previous state.

https://perf.rust-lang.org/compare.html?start=7ac9572c48435b5342ad3550d6036bde835d37dc&end=11d6ba903e6762c93f69ccf2ece4c445cfc575ae&stat=instructions:u
https://perf.rust-lang.org/compare.html?start=7ac9572c48435b5342ad3550d6036bde835d37dc&end=ebf0d2d3df7ddf24af902c6cb1401231a299dc2d&stat=instructions:u
https://perf.rust-lang.org/compare.html?start=cc47b069983292e4ee8982d5dabe6301452c5f25&end=0c68d2596c4617e0a308139af6ad56d4ac858bf1&stat=instructions:u
https://perf.rust-lang.org/compare.html?start=657eefe2dcf18f76ac67a39945810128e101178c&end=8e6760e82a081fb624e777d52ef744c1def2f593&stat=instructions:u

**Pull request merged**
