### PR TITLE
Readd track_caller to Result::from_residual

### PR DESCRIPTION
**Pull request by yaahc**
This is a followup on https://github.com/rust-lang/rust/issues/87401 in and an attempt to move the issue towards resolution.

As part of the overhaul of the Try trait we removed the ability for errors to grab location information during propagation via `?` with the builtin `std::result::Result`. The previously linked issue has a fair bit of discussion into the reasons for and against the usage of `#[track_caller]` on the `FromResidual` impl on `Result` that I will do my best to summarize.

---
### For

- https://github.com/rust-lang/rust/issues/87401#issuecomment-915053533: Difficulties with using non `std::result::Result` like types
- https://github.com/rust-lang/rust/issues/87401#issuecomment-978355102: Inconsistency with functionality provided for recoverable (Result) and non-recoverable errors (panic), where panic provides a location and Result does not, pushing some users towards using panic

### Against

- https://github.com/rust-lang/rust/issues/84277#issuecomment-885322833: concern that this will bloat callers that never use this data

---

Personally, I want to quantify the performance / bloat impact of re-adding this attribute, and fully evaluate the pros and cons before deciding if I need to switch `eyre` to have a custom `Result` type, which would also mean I need `try_trait_v2` to be stabilized, cc @scottmcm. If the performance impact is minor enough in the general case I think I would prefer that the default `Result` type has the ability to track location information for consistency with `panic` error reporting, and leave it to applications that need particularly high performance to handle the micro optimizations of introducing their own efficient custom Result type or matching manually.

Alternatively, I wonder if the performance penalty on code that doesn't use the location information on `FromResidual` could be mitigated via new optimizations.

### CODE REVIEW

**Comment by cuviper** [comment]
> Alternatively, I wonder if the performance penalty on code that doesn't use the location information on `FromResidual` could be mitigated via new optimizations.

If the calls are inlined, it's likely that the unused location information will already be optimized away.

@bors try @rust-timer queue

**Comment by cuviper** [comment]
Looks like it might need some UI output review / blessing.

**Comment by scottmcm** [comment]
My big question here is whether it'd result in a de-facto stability guarantee, despite there not de-jure being one per https://github.com/rust-lang/rust/issues/88302#issuecomment-910614687.

For example, without this we could merge the "re-yeet" MIR blocks from multiple `?`s, but if they need to preserve all the line numbers that becomes very different.

**Comment by yaahc** [comment]
> My big question here is whether it'd result in a de-facto stability guarantee, despite there not de-jure being one per [#88302 (comment)](https://github.com/rust-lang/rust/issues/88302#issuecomment-910614687).
> 
> For example, without this we could merge the "re-yeet" MIR blocks from multiple `?`s, but if they need to preserve all the line numbers that becomes very different.

No matter what I think we've already made the explicit decision that we do not consider `#[track_caller]` location to be part of our stable API, so if some future consideration comes along that pushes us in the other direction we can always revert this change.

**Comment by cuviper** [comment]
The only negative perf results are in incremental builds, and even those are not too bad. I think it's acceptable.

@bors r+

**Pull request merged**
