### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #130005 (Replace -Z default-hidden-visibility with -Z default-visibility)
 - #130229 (ptr::add/sub: do not claim equivalence with `offset(c as isize)`)
 - #130773 (Update Unicode escapes in `/library/core/src/char/methods.rs`)
 - #130933 (rustdoc: lists items that contain multiple paragraphs are more clear)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=130005,130229,130773,130933)

### CODE REVIEW

**Comment by lqd** [comment]
> though it's not clear to me why

@rylev I believe it's because the PR introduced new unconditional query calls to compute the symbol visibility (even though it will still return the same default as before, until the default is switched to "protected" in some future). 

That is, we could gain the perf back, and delay this computation until that change is needed, most likely when lld is used on stable by default, so not right around the corner.

**Comment by rylev** [comment]
cc @davidlattimore @Urgau (author and reviewer of https://github.com/rust-lang/rust/pull/130005) for visibility ^^

**Comment by Urgau** [comment]
Yeah, we may want to re-add the fast path for `!did.is_local()`:
https://github.com/rust-lang/rust/blob/0999b019f8e0a96ca7aac9fd5ec095d59b0806ec/compiler/rustc_monomorphize/src/partitioning.rs#L916-L920

**Comment by lqd** [comment]
The query will be more costly than the `is_local()` check.

**Comment by Urgau** [comment]
Oh, yeah you're right, when the default visibility wasn't changed we just returned `Default` and did nothing else.
https://github.com/rust-lang/rust/blob/0999b019f8e0a96ca7aac9fd5ec095d59b0806ec/compiler/rustc_monomorphize/src/partitioning.rs#L906-L909

I completely overlook that.

**Pull request merged**
