### PR TITLE
Implement Eq/Hash/Debug etc. for unsized tuples.

### PR DESCRIPTION
**Pull request by qnighy**
As I mentioned in [the comment in #18469](https://github.com/rust-lang/rust/issues/18469#issuecomment-306767422), the implementations of `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Debug`, `Hash` can be generalized to unsized tuples.

This is consistent with the `derive` behavior for unsized structs.

```rust
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Default, Hash)]
struct MyTuple<X, Y, Z: ?Sized>(X, Y, Z);

fn f(x: &MyTuple<i32, i32, [i32]>) {
    x == x;
    x < x;
    println!("{:?}", x);
}
```

Questions:

- Need an RFC?
- Need a feature gate? I don't think it does because the unsized tuple coercion #42527 is feature-gated.
- I changed `builder.field($name);` into `builder.field(&$name);` in the `Debug` implementation to pass compilation. This won't affect the behavior because `Debug for &'a T` is a mere redirection to `Debug for T`. However, I don't know if it affects code size / performance.

### CODE REVIEW

**Comment by sfackler** [comment]
No RFC is needed, or a feature - trait implementations can't actually have feature gates applied to them.

@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by carols10cents** [comment]
ping @brson, you're the last checkbox needed here!

**Pull request merged**
