### PR TITLE
Add fused multiply-add vector intrinsics

### PR DESCRIPTION
**Pull request by ruuda**
This adds support for fused multiply-add and multiply-subtract vector intrinsics for 128 and 256-bit vectors of `f32` and `f64`. These correspond to the intrinsics [listed here](https://software.intel.com/en-us/node/523929) except for the `_ss` and `_sd` variants. The intrinsics added are:
- `fmadd`
- `fmaddsub`
- `fmsub`
- `fmsubadd`
- `fnmadd`
- `fnmsub`

The “fma” target feature must be enabled by passing `-C target-feature=+fma` to rustc when using these, otherwise LLVM will complain.

I verified locally that the `x86_mm256_fmadd_ps` and `x86_mm256_fmsub_ps` work.

### CODE REVIEW

**Comment by ruud-v-a** [comment]
cc @huonw, you wrote most of the other intrinsics and SIMD support, can you please have a look if you have the time?

**Comment by alexcrichton** [comment]
@bors: r+ a409076df4ac1e80d0e8b4ed55608cbd354129ef

Thanks!

**Comment by gnzlbg** [comment]
Is there a reason why fma 512 wasn't included? IIRC llvm also has support for these.

**Comment by ruud-v-a** [comment]
512-bit FMA instructions are part of AVX-512, not of the FMA instructions. I don’t have a CPU that supports AVX-512.

**Pull request merged**
