### PR TITLE
Change proc_macro::Diagnostics docs

### PR DESCRIPTION
**Pull request by tsoutsman**
With Rust 1.54 attributes can invoke function-like macros. This allows functions generated by macros to have non-generic documentation. This pull request changes the documentation of `proc_macro::Diagnostics` to be more specific and include a link to the level.
## Example
Before:
```markdown
Adds a new child diagnostic message to `self` with the level
identified by this method’s name with the given `message`.
```
After:
```markdown
Adds a new child diagnostic message to self with the [`Level::Error`]
level, and the given `message`.
```

### CODE REVIEW

**Comment by petrochenkov** [comment]
Could you wrap the lines to fit into the usual 100-character limit? `rustfmt` cannot do it automatically in this case. 

r=me after doing that and squashing commits.

**Comment by TypicalFork** [comment]
Hi, I'm not quite sure about the indentation so I just put it in line with `concat!`
r= @petrochenkov

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Comment by petrochenkov** [comment]
@tsoutsman 
Push to a pull request after approval (`@bors r+`) cancels the approval.
Also using rebases instead of merges is recommended to update pull request branches.
@bors r+

**Comment by tsoutsman** [comment]
> @tsoutsman 
> Push to a pull request after approval (`@bors r+`) cancels the approval.
> Also using rebases instead of merges is recommended to update pull request branches.

Sorry, I was just playing around with the repository. I'm not too familiar with git.

**Pull request merged**
