### PR TITLE
rustdoc: Fix a number of low-hanging-fruit problems

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit series starts out with more official test harness support for rustdoc tests, and then each commit afterwards adds a test (where appropriate). Each commit should also test and finish independently of all others (they're all pretty separable).

I've uploaded a [copy of the documentation](http://people.mozilla.org/~acrichton/doc/std/) generated after all these commits were applied, and a double check on issues being closed would be greatly appreciated! I'll also browse the docs a bit and make sure nothing regressed too horribly.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @aturon 

cc @tomjakubowski

**Comment by huonw** [comment]
Do we want to have some sort of feature gate for `doc(test(attr(...)))`?

**Comment by aturon** [comment]
I'll give this a thorough review in the morning, but just want to say: AMAZING WORK!

**Comment by alexcrichton** [comment]
@huonw that's a good question! I was a bit surprised to learn about `#![doc(test(no_crate_inject))]` as well, but in the grand scheme of things it's not necessarily such a bad attribute to stabilize in terms of future breakage. The failure mode is that the *doc tests* for a crate *may* fail (e.g. libstd just uses them to control lints), which may not be the worst in the world. Right now rustdoc is super lax about attributes and generally ignores anything that's malformed.

**Comment by glaebhoerl** [comment]
> It's somewhat common to impl traits for `&T` and `&mut T` so show these on the
pages for `T` to ensure they're listed somewhere at least.

Perhaps this behavior should track with `#[fundamental]`?

**Comment by nikomatsakis** [comment]
Nice!

**Comment by alexcrichton** [comment]
> > It's somewhat common to impl traits for `&T` and `&mut T` so show these on the
pages for `T` to ensure they're listed somewhere at least.
> 
> Perhaps this behavior should track with `#[fundamental]`?

Hm, that's an interesting idea! Currently the `#[fundamental]` types are references, function traits, and `Box<T>`. Of these, the only ones rustdoc is interested in is references and `Box<T>`, and of those the only one with an actual `#[fundamental]` attributes is `Box<T>`. This basically means that if you implement a trait for `Box<T>` it won't show up in the "Implemented Traits" section of the documentation of type `T`.

I think that the logic for detecting `#[fundamental]` on `Box<T>`, however, may be quite difficult. For example it needs to realize that the `Self` type for the `impl` is a path, it's then tagged `#[fundamental]`, it then has one type parameter, and that one type parameter is then the type we're interested in. I think for now we get some good wins by just picking up references (easy to detect), and we can certainly always expand more into other types later!

I suspect that if we start growing the set of `#[fundamental]` types we'll need to implement this logic, but for now it doesn't seem super pressing (but I could be wrong!)

**Comment by aturon** [comment]
OK, I've done a pass through the commits, confirming fixes in the generated dist docs whenever possible. This looks great!

I took note of a couple places where I didn't think the issue was fully addressed. Feel free to just leave the issues open (or, in some cases, split into separate issues) as appropriate. Otherwise, r=me!

**Comment by alexcrichton** [comment]
Thanks for the thorough review @aturon!

**Comment by Manishearth** [comment]
This seems to break android (but not the others)

http://buildbot.rust-lang.org/builders/auto-linux-64-x-android-t/builds/4360/steps/test/logs/stdio

**Comment by tomjakubowski** [comment]
Wooooooo! :confetti_ball:

**Pull request merged**
