### PR TITLE
bootstrap: Link LLVM as a dylib with ThinLTO (take 2)

### PR DESCRIPTION
**Pull request by alexcrichton**
When building a distributed compiler on Linux where we use ThinLTO to
create the LLVM shared object this commit switches the compiler to
dynamically linking that LLVM artifact instead of statically linking to
LLVM. The primary goal here is to reduce CI compile times, avoiding two+
ThinLTO builds of all of LLVM. By linking dynamically to LLVM we'll
reuse the one ThinLTO step done by LLVM's build itself.

Lots of discussion about this change can be found [here] and down. A
perf run will show whether this is worth it or not!

[here]: https://github.com/rust-lang/rust/pull/53245#issuecomment-417015334

---

This PR previously landed in https://github.com/rust-lang/rust/pull/56944, caused https://github.com/rust-lang/rust/issues/57111, and was reverted in https://github.com/rust-lang/rust/pull/57116. I've added one more commit here which should fix the breakage that we saw.

### CODE REVIEW

**Comment by tmandry** [comment]
@alexcrichton was there ever a perf run to see the impact on compiler performance?

I ask because we've seen as much as a 10-20% improvement from linking LLVM statically to clang. (cc @petrhosek)

I expect that something that large would have been noticed in the release perf run, but maybe there is a potential win here (at least, for someone who wants to build their own toolchain).

**Comment by petrhosek** [comment]
Would it be possible to provide an option to statically link LLVM even when using ThinLTO? I understand that you may not want to do this because of your CI resource constraints, but in our case it's something we would always want to use since CI resources aren't a problem.

**Comment by alexcrichton** [comment]
@tmandry hm this is long enough ago I don't quite remember, but might be good to check and see! The main motivation for this was CI time though, since statically linking LLVM to rustc means running all of LLVM through ThinLTO twice, once for it's own dylib and once for rustc, which can be extremely expensive on CI.

@petrhosek yeah definitely, we should definitely support this! We may already given various matrices of configuration options, but if not a PR to add one sounds great.

**Pull request merged**
