### PR TITLE
Make `core::mem::copy` const

### PR DESCRIPTION
**Pull request by jyn514**
cc https://github.com/rust-lang/rust/issues/98262, https://github.com/rust-lang/libs-team/issues/78

### CODE REVIEW

**Comment by thomcc** [comment]
Reassigning to someone on t-libs-api -- @jyn514 asked me to review via discord, but it's an API change, so someone on libs-api should sign off on it.

I'm not sure if this needs ACP or not. On the one hand, it's very small, the change is small. On the other hand, it does repaint a bikeshed -- in that it changes the name (and to be totally honest, I'm not 100% convinced about the name change -- the rationale of distinguishing it from `core::ptr::copy` seems solid enough, but I'm not sure the past tense in `core::mem::copied` makes sense to me).

r? @joshtriplett

**Comment by scottmcm** [comment]
Also, historically the `-d` naming was used for `Iterator::cloned` as distinct from `Clone::clone`, and thus also things like https://doc.rust-lang.org/std/option/enum.Option.html#method.copied.  So if this is the "primary" copy method, it's not obvious to me that it should use past tense like this.

(TBH, `copy` feels to me like it wants to be a `#[final]` method in the `Copy` trait, not a standalone, but that's a whole different conversation.)

**Comment by thomcc** [comment]
Oh, yeah, `Copy::copy` as a `#[final]` method seems exactly right (I had forgotten about these, since I don't think they exist yet).

**Comment by jyn514** [comment]
I am not sure the status of this PR. Should I wait for feedback from @joshtriplett that we want to make these changes?

**Comment by jyn514** [comment]
Ok, I changed this so it only makes the function const.

**Comment by jyn514** [comment]
@joshtriplett do you know when you'll have a chance to look at this?

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
