### PR TITLE
Use a hardcoded constant instead of calling OpenProcessToken.

### PR DESCRIPTION
**Pull request by smmalis37**
GetCurrentProcessToken is defined in processthreadsapi.h as:
```c++
FORCEINLINE
HANDLE
GetCurrentProcessToken (
    VOID
    )
{
    return (HANDLE)(LONG_PTR) -4;
}
```

Since it's very unlikely that this constant will ever change, let's just use it instead of making api calls to get the same information.

This also (I think) removes the need for rust binaries to directly link against advapi32. Let me know if some changes are needed in those build-related bits, that I'm much less sure on.

### CODE REVIEW

**Comment by joshtriplett** [comment]
cc @ChrisDenton 

Is this a reasonable assumption to make?

**Comment by smmalis37** [comment]
Unfortunately I don't know the answer to that. Will CI test Windows 7? Or does someone have a machine/vm to test on?

**Comment by smmalis37** [comment]
Dang, oh well.

**Comment by ChrisDenton** [comment]
It's undocumented but if it's only used as a fallback then it could be worth it.

On the other hand, `GetUserProfileDirectoryW` is only used by `env::home_dir` which is now deprecated. So the import should not appear in most Rust programs and can be avoided by using a third party implementation if it's needed.

**Pull request closed without merging**
