### PR TITLE
Re-enable hoedown by default

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @rust-lang/docs 

cc @aturon

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
To make this PR works when running "-Z unstable-options enable-commonmark", we need #41405 to be merged as well (but after if possible).

**Comment by steveklabnik** [comment]
I've r+'d that PR

**Comment by GuillaumeGomez** [comment]
Ok thanks. When merged, I'll update this one.

**Comment by aturon** [comment]
OK, I've confirmed that this indeed includes the old hoedown code as of [this commit](https://github.com/rust-lang/rust/blob/b0803d4aedc06504cb4cb86f63beb6650ff67a8e/src/librustdoc/html/markdown.rs), and properly threads through a new render type flag. Thanks @GuillaumeGomez! 

r=me when ready.

**Pull request merged**
