### PR TITLE
Remove noisy suggestion of hash_map

### PR DESCRIPTION
**Pull request by ayushmishra2005**
Removed import suggestion of `std::collections::hash_map::HashMap`
 #72642

### CODE REVIEW

**Comment by lzutao** [comment]
The stderr files are auto-generated. You might want to change Rust file instead.

**Comment by ayushmishra2005** [comment]
> The stderr files are auto-generated. You might want to change Rust file instead.

 I am looking into it.

**Review by davidtwco — CHANGES_REQUESTED** [review]
Unfortunately, this isn't enough to solve #72642. You've changed a `stderr` file, which is the output from the compiler for a test, which we use to make sure the compiler's output hasn't changed - changing it only makes the test fail, it doesn't change the output of the compiler.

You can grep to find that the "consider importing one of these items" help is constructed here in `show_candidates`:

https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L1498

`show_candidates` takes a `&[ImportSuggestion]`, which we can trace back to these lines:

https://github.com/rust-lang/rust/blob/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/librustc_resolve/late/diagnostics.rs#L213-L223

Going slightly deeper, `lookup_import_candidates_from_module` constructs the list of import suggestions:

https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L628-L635

You might consider experimenting with this function to de-duplicate the suggestions in some way if you're interested in addressing this issue.

**Comment by nikomatsakis** [comment]
Since this PR is presently empty, I'm going to close it for now -- @ayushmishra2005 feel free to re-open when it's ready for review :)

**Comment by ayushmishra2005** [comment]
> Unfortunately, this isn't enough to solve #72642. You've changed a `stderr` file, which is the output from the compiler for a test, which we use to make sure the compiler's output hasn't changed - changing it only makes the test fail, it doesn't change the output of the compiler.
> 
> You can grep to find that the "consider importing one of these items" help is constructed here in `show_candidates`:
> 
> https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L1498
> 
> `show_candidates` takes a `&[ImportSuggestion]`, which we can trace back to these lines:
> 
> https://github.com/rust-lang/rust/blob/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/librustc_resolve/late/diagnostics.rs#L213-L223
> 
> Going slightly deeper, `lookup_import_candidates_from_module` constructs the list of import suggestions:
> 
> https://github.com/rust-lang/rust/blob/0aa6751c19d3ba80df5b0b02c00bf44e13c97e80/src/librustc_resolve/diagnostics.rs#L628-L635
> 
> You might consider experimenting with this function to de-duplicate the suggestions in some way if you're interested in addressing this issue.

@davidtwco Thanks for your comment. Since I am new to Rust, so I would need more mentorship. I am still not able to figure out what is causing this issue and where `hash_map` is being inserted.

I also tried to check this function `lookup_import_candidates`.

**Comment by davidtwco** [comment]
@ayushmishra2005 I've responded [in this comment](https://github.com/rust-lang/rust/issues/72642#issuecomment-637441535) - feel free to follow-up questions, good luck!

**Pull request closed without merging**
