### PR TITLE
Stabilize `Iterator::intersperse`

### PR DESCRIPTION
**Pull request by jhpratt**
[FCP completed in #79524](https://github.com/rust-lang/rust/issues/79524#issuecomment-909663616)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Has something happened to mitigate the problems that caused us to revert this the last time? (https://github.com/rust-lang/rust/issues/88967)

**Comment by vacuus** [comment]
The linked FCP is the original, not a new one. There hasn't been recent discussion in that issue or the tracking issue, so if progress has been made, it should probably be referenced in one or both of the issues. It doesn't seem like anything has happened, though.

**Comment by ehuss** [comment]
I believe [rfc#3240](https://github.com/rust-lang/rfcs/pull/3240) was opened with `intersperse` being a prime example of needing some mitigating factor before it could be stabilized.  I believe that's where the most recent discussion went.

**Comment by jhpratt** [comment]
For reference, the primary reason I created this was to have a crater run (the queue is empty, so why not). This would let us judge whether anything has happened on the ecosystem side of things, not just the compiler's. It's been ~10 months since the previous crater run, so I just wanted an update on that front.

**Comment by vacuus** [comment]
It would be helpful for the PR title to have something like `[DONT MERGE]` or `[CRATER]` and explain more (if you think it's necessary) in the PR description.

**Comment by jhpratt** [comment]
The reason I _didn't_ do that is because it should be merged if crater comes back clean. Which, to be honest, is not expected — I presume there are still some root regressions.

**Comment by jyn514** [comment]
@craterbot run mode=build-and-test crates=list:https://crater-reports.s3.amazonaws.com/beta-1.56-2/retry-regressed-list.txt

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=build-and-test crates=https://crater-reports.s3.amazonaws.com/beta-1.56-2/retry-regressed-list.txt

**Comment by Mark-Simulacrum** [comment]
@craterbot run mode=build-and-test

**Comment by jhpratt** [comment]
I think it's safe to say that the situation has not improved since the last crater run. As such I am closing this. #88967 is probably the only way forward given the lack of "natural" progress towards disambiguation.

**Pull request closed without merging**
