### PR TITLE
Supporting backtrace for x86_64-fortanix-unknown-sgx.

### PR DESCRIPTION
**Pull request by VardhanThigle**
# Overview
Implementing following functions required by `libstd/sys_common` to support `backtrace`:
```
1. unwind_backtrace
2. trace_fn
3. resolve_symname
```
# Description:
The changes here are quite similar to the Cloudabi target `src/libstd/sys/cloudabi/backtrace.rs`
The first 2 functions are implemented via calls to libunwind.a that is linked to the `x86_64-fortanix-unknown-sgx` (#56979),  we have not implemented functionality needed by `resolve_symname`  (or `dladdr`) to reduce SGX TCB. Rather, we print the function address (relative to enclave image base) in `resolve_symname` which can be later translated to correct symbol name (say, via `addr2line`).

# Note:
For `x86_64-fortanix-unknown-sgx`, the `RUST_BACKTRACE` environment has to be set from within the program running in an enclave.
cc: @jethrogb 
r? @alexcrichton

### CODE REVIEW

**Comment by jethrogb** [comment]
```
[00:03:48] tidy error: /checkout/src/libstd/sys/sgx/backtrace.rs:90: line longer than 100 chars
```

**Comment by VardhanThigle** [comment]
@alexcrichton,
After approval, I had to push a small change to fix `tidy` line length failure.
Please have a look.

**Comment by VardhanThigle** [comment]
@alexcrichton 
Additional changes were made to expose image_base function, this was done so that we can add support for backtrace crate as well in coming days.

**Comment by pietroalbini** [comment]
@bors retry
AppVeyor... what's wrong with you today?

**Pull request merged**
