### PR TITLE
Add #[allow_internal_unstable] to track stability for macros better.

### PR DESCRIPTION
**Pull request by huonw**
Unstable items used in a macro expansion will now always trigger
stability warnings, _unless_ the unstable items are directly inside a
macro marked with `#[allow_internal_unstable]`. IOW, the compiler warns
unless the span of the unstable item is a subspan of the definition of a
macro marked with that attribute.

E.g.

```
#[allow_internal_unstable]
macro_rules! foo {
    ($e: expr) => {{
        $e;
        unstable(); // no warning
        only_called_by_foo!();
    }}
}

macro_rules! only_called_by_foo {
    () => { unstable() } // warning
}

foo!(unstable()) // warning
```

The unstable inside `foo` is fine, due to the attribute. But the
`unstable` inside `only_called_by_foo` is not, since that macro doesn't
have the attribute, and the `unstable` passed into `foo` is also not
fine since it isn't contained in the macro itself (that is, even though
it is only used directly in the macro).

In the process this makes the stability tracking much more precise,
e.g. previously `println!("{}", unstable())` got no warning, but now it
does. As such, this is a bug fix that may cause [breaking-change]s.

The attribute is definitely feature gated, since it explicitly allows
side-stepping the feature gating system.

---

This updates `thread_local!` macro to use the attribute, since it uses
unstable features internally (initialising a struct with unstable
fields).

### CODE REVIEW

**Comment by huonw** [comment]
r? @alexcrichton, @aturon

@alexcrichton this is the fix for the macro issues we were discussing on IRC a few days ago.

**Comment by aturon** [comment]
:trophy:

**Comment by alexcrichton** [comment]
Nice! This looks pretty great to me. Can this de-stabilize all of the internal fields of the thread local structs as well? (now that they can explicitly be left as unstable)

**Comment by huonw** [comment]
Updated, destabilising essentially everything in `thread_local` other than the main macro and the `Key` type.

**Comment by Manishearth** [comment]
This is awesome :D

**Comment by Manishearth** [comment]
`run-pass/macro-attributes.rs` needs a `#![feature(custom_attribute)]`

**Comment by Manishearth** [comment]
```

---- [run-pass] run-pass-fulldeps/plugin-args-1.rs stdout ----
	
error: auxiliary build of "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs" failed to compile: 
status: exit code: 101
command: i686-apple-darwin/stage2/bin/rustc /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs -L i686-apple-darwin/test/run-pass-fulldeps --target=i686-apple-darwin --crate-type=dylib -L i686-apple-darwin/test/run-pass-fulldeps/plugin-args-1.stage2-i686-apple-darwinlibaux -C prefer-dynamic --out-dir i686-apple-darwin/test/run-pass-fulldeps/plugin-args-1.stage2-i686-apple-darwinlibaux --cfg rtopt --cfg debug -O -L i686-apple-darwin/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs:49:9: 49:53 error: this function takes 3 parameters but 2 parameters were supplied [E0061]
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs:49         NormalTT(box Expander { args: args, }, None));
                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error

------------------------------------------

thread '[run-pass] run-pass-fulldeps/plugin-args-1.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/compiletest/runtest.rs:1466


---- [run-pass] run-pass-fulldeps/plugin-args-2.rs stdout ----
	
error: auxiliary build of "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs" failed to compile: 
status: exit code: 101
command: i686-apple-darwin/stage2/bin/rustc /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs -L i686-apple-darwin/test/run-pass-fulldeps --target=i686-apple-darwin --crate-type=dylib -L i686-apple-darwin/test/run-pass-fulldeps/plugin-args-2.stage2-i686-apple-darwinlibaux -C prefer-dynamic --out-dir i686-apple-darwin/test/run-pass-fulldeps/plugin-args-2.stage2-i686-apple-darwinlibaux --cfg rtopt --cfg debug -O -L i686-apple-darwin/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs:49:9: 49:53 error: this function takes 3 parameters but 2 parameters were supplied [E0061]
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs:49         NormalTT(box Expander { args: args, }, None));
                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error

------------------------------------------

thread '[run-pass] run-pass-fulldeps/plugin-args-2.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/compiletest/runtest.rs:1466


---- [run-pass] run-pass-fulldeps/plugin-args-3.rs stdout ----
	
error: auxiliary build of "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs" failed to compile: 
status: exit code: 101
command: i686-apple-darwin/stage2/bin/rustc /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs -L i686-apple-darwin/test/run-pass-fulldeps --target=i686-apple-darwin --crate-type=dylib -L i686-apple-darwin/test/run-pass-fulldeps/plugin-args-3.stage2-i686-apple-darwinlibaux -C prefer-dynamic --out-dir i686-apple-darwin/test/run-pass-fulldeps/plugin-args-3.stage2-i686-apple-darwinlibaux --cfg rtopt --cfg debug -O -L i686-apple-darwin/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs:49:9: 49:53 error: this function takes 3 parameters but 2 parameters were supplied [E0061]
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/auxiliary/plugin_args.rs:49         NormalTT(box Expander { args: args, }, None));
                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error

------------------------------------------

thread '[run-pass] run-pass-fulldeps/plugin-args-3.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/compiletest/runtest.rs:1466



failures:
    [run-pass] run-pass-fulldeps/plugin-args-1.rs
    [run-pass] run-pass-fulldeps/plugin-args-2.rs
    [run-pass] run-pass-fulldeps/plugin-args-3.rs
```

**Comment by huonw** [comment]
Updated; I've modified the approach and several extra commits (the `fixup! ...` ones are intended as corrections to earlier commits, I'll rebase and squash post review)

I've had to add *another* feature gating pass, because the post-expansion feature-gating pass ran before the second configuration pass, and so would miss custom attributes inserted by `cfg_attr`'s inside macro expansion: https://github.com/huonw/rust/commit/9360dca6bd11e92d79b20e8cc8b5bb63ab0f56c7. (I'm sure this can be done in a more rigorous way, but, it seems sensible to run feature gating on exactly the AST we compile, which this extra pass does.)

**Comment by alexcrichton** [comment]
This looks good to me, r=me.

Could you also knock out some [`#[stable]` attributes in `sys_common::thread_local`](https://github.com/rust-lang/rust/blob/3b3bb0e682c2d252e9f62dd9df5cff9552af91ad/src/libstd/sys/common/thread_local.rs#L87) as well as part of this PR? They're reexported through `std::thread_local::__imp` currently.

**Comment by theemathas** [comment]
What about `select! {}`?

**Comment by huonw** [comment]
`select!` is unstable.

**Pull request merged**
