### PR TITLE
Clean up rustdoc static files

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
The `html/static` of rustdoc was starting to be quite a mess... So I moved files in sub-folders to make it easier to follow. Here what remains in `html/static` folder:

```
$ ls
COPYRIGHT.txt  css  fonts  images  js  LICENSE-APACHE.txt  LICENSE-MIT.txt
```

cc @jyn514 
r? @Manishearth

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
It would be nice to clean up the generated code structure as well, but that doesn't have to be now.

**Comment by GuillaumeGomez** [comment]
It's kinda started with the templating (using tera). It's on pause until @jsha comes back. :)

**Comment by GuillaumeGomez** [comment]
Seems like I forgot to update the tests...

@bors: r-

**Review by Manishearth — APPROVED** [review]
feel free to r=manishearth when ready 😄

**Comment by GuillaumeGomez** [comment]
Normally this time it should be good. :)

@bors: r=Manishearth

**Pull request merged**
