### PR TITLE
rustdoc: Don't allow `#![feature(...)]` on stable or beta

### LINKED ISSUE #67647: rustdoc does not verify feature gates
This generates documentation with a stable rustdoc today without any warnings.

```rust
#![feature(raw)]

use std::raw::TraitObject;

pub fn bar() {}
```

Interestingly, rustdoc does seem to check that the feature gate is in the crate (i.e., `#![feature(raw)]` must exist), and will error if a feature gate has been removed (e.g., custom_attribute on nightly).

### PR DESCRIPTION
**Pull request by ollie27**
Fixes #67647

r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks! Any way to add a test for this?

**Comment by ollie27** [comment]
> Any way to add a test for this?

That's a good question but I couldn't think of a good way to add a test. I couldn't find any similar tests for rustc either. I did make a beta build locally to test this though.

**Comment by GuillaumeGomez** [comment]
This is a bit suboptimal. :-/ In the worst case, isn't possible to add a test running only on given kind of release? Maybe @Mark-Simulacrum would have an idea?

**Comment by Mark-Simulacrum** [comment]
I don't think so, at least not with today's compiler. We could make `RUSTC_BOOTSTRAP=0` make nightly behave like beta/stable, but I would rather not do that in this PR. I think if we've tested this, we're unlikely to break it, so I would not worry about testing it just yet.

**Comment by GuillaumeGomez** [comment]
Then let's go for it! Thanks @ollie27.

@bors: r+

**Pull request merged**
