### PR TITLE
Update RLS and Rustfmt

### LINKED ISSUE #76145: `rls` no longer builds after rust-lang/rust#76027
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#76027, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @davidtwco, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### LINKED ISSUE #76146: `rustfmt` no longer builds after rust-lang/rust#76027
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#76027, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @davidtwco, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #76145 and fixes #76146 

cc @Xanewok @topecongiro

### CODE REVIEW

**Comment by Xanewok** [comment]
Good timing, I just updated this locally as well :sweat_smile: 

I think you also need to set:
```diff
diff --git a/src/tools/rustc-workspace-hack/Cargo.toml b/src/tools/rustc-workspace-hack/Cargo.toml
index 351e2d4481c..11d61606ff5 100644
--- a/src/tools/rustc-workspace-hack/Cargo.toml
+++ b/src/tools/rustc-workspace-hack/Cargo.toml
@@ -69,7 +69,7 @@ serde = { version = "1.0.82", features = ['derive'] }
 serde_json = { version = "1.0.31", features = ["raw_value"] }
 smallvec-0_6 = { package = "smallvec", version = "0.6", features = ['union', 'may_dangle'] }
 smallvec = { version = "1.0", features = ['union', 'may_dangle'] }
-syn = { version = "1", features = ['fold', 'full', 'extra-traits', 'visit'] }
+syn = { version = "1", features = ['fold', 'full', 'extra-traits', 'visit', 'visit-mut'] }
 url = { version = "2.0", features = ['serde'] }
 
 [target.'cfg(not(windows))'.dependencies]
```

since `./x.py test src/tools/rls` was not happy otherwise.

Otherwise r=me

**Comment by calebcartwright** [comment]
> since ./x.py test src/tools/rls was not happy otherwise.

ahh good spot thanks. I only ran it for rustfmt locally :man_facepalming:

**Pull request merged**
