### PR TITLE
[beta] Revert "Disallow ambiguous attributes on expressions" on beta

### PR DESCRIPTION
**Pull request by lqd**
As discussed in [today's t-compiler meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-06-06/near/443079505), this reverts PR #124099 on beta to fix P-critical beta regressions #125199.

r? @wesleywiser 

This is the revert of #124099 on beta that I mentioned in #126101, in case that's what you also wanted. Opening as draft in case it's not.

I'm not well-versed in these backports, so I hope I did it right 😓

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
The revert looks correct to me so:

@bors r+

**Comment by wesleywiser** [comment]
@bors p=1 

Beta backport

**Comment by lqd** [comment]
> ERROR: failed to solve: process "/bin/sh -c /tmp/build-solaris-toolchain.sh x86_64  amd64   solaris-i386  pc" did not complete successfully: exit code: 1

no way, beta CI is borked and we may need to backport https://github.com/rust-lang/rust/pull/126011

the other beta backport also failed because of this

**Comment by workingjubilee** [comment]
This will be landing with #126093

**Pull request closed without merging**
