### PR TITLE
impl iter() for dyn Error

### PR DESCRIPTION
**Pull request by haraldh**
Examples:

```rust
let next_error_type_a = err
    .iter()
    .filter_map(Error::downcast_ref::<ErrorTypeA>)
    .next();
```

```rust
let source_root_error = err.iter().last();
```

Credit for the ErrorIter goes to reddit user /u/tdiekmann (Tim Diekmann)
https://www.reddit.com/r/rust/comments/aj3lpg/is_an_iterator_impl_over_errorsource_possible/

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks for the PR! I think this kind of functionality is definitely useful, but I think we'll want to tweak the API a bit. In particular, I think a method name like `sources()` or `iter_sources()` is more descriptive than simply `iter()`. The failure crate also provides iterators off of both the causes of the error as well as the error itself followed by the causes. Both of those are useful based on the specific context of what you're doing, so it seems like a good idea to do the same here: https://docs.rs/failure/0.1.5/failure/trait.Fail.html#method.iter_causes

cc @withoutboats

**Comment by haraldh** [comment]
agreed with `iter_sources()` .. changed the PR to `iter_sources()` and `iter_chain()`

**Comment by TimDiekmann** [comment]
I'd return `ErrorIter` directly instead of `impl Iterator`. This way it's possible to nest the type in other structs.

**Comment by haraldh** [comment]
Which would make `ErrorIter` pub.

**Comment by TimDiekmann** [comment]
Yes, this is intended. Otherwise you have to box it to store it.

**Comment by sfackler** [comment]
Ah yeah, we should return a concrete iterator type.

**Comment by haraldh** [comment]
Ok, `ErrorIter` is returned and `pub`

**Comment by haraldh** [comment]
More comments?

**Comment by haraldh** [comment]
@sfackler : What's the procedure for this to make it into stable?

**Comment by haraldh** [comment]
The usability is not very ergonomic though:

```rust
    let mut iter = (&b as &(dyn Error)).iter_chain();
    // or
    let b = Box::<Error>::from(b); let mut iter = b.iter_chain();
    // or
    let mut iter = <dyn Error>::iter_chain(&b);
    // but not
    let mut iter = b.iter_chain();
```

Where we already have a `Box<Error>` it's not a problem, but for other cases it feels a little bit clunky.

**Comment by TimDiekmann** [comment]
It may be better to implement it as a provided trait method.

**Comment by haraldh** [comment]
```rust
pub trait Error: Debug + Display {
…
    fn iter_chain(&self) -> ErrorIter
    where
        Self: Sized + 'static,
    {
        <dyn Error>::iter_chain(self)
    }
…
}
```

will give for:
```rust
    let mut iter = b.iter_chain();
```

```
247 |         <dyn Error>::iter_chain(self)
    |         ^^^^^^^^^^^^^^^^^^^^^^^ multiple `iter_chain` found
```

How can I call the `impl dyn Error` method explicitly?

**Comment by TimDiekmann** [comment]
I meant, don't implement the method in `impl dyn Error` at all, but only in `trait Error`. `dyn Error` is only needed for downcasting.

**Comment by haraldh** [comment]
if the ` impl for the type (dyn testerror::Error + 'static)` is removed

```rust
pub trait Error: Debug + Display {
…
    fn iter_chain(&self) -> ErrorIter
    where
        Self: Sized + 'static,
    {
        ErrorIter {
            current: Some(self),
        }
    }
…
}
```
will give for:
```
    let err: Box<Error> = b.into();
    let mut iter = err.iter_chain();
```

```
error: the `iter_chain` method cannot be invoked on a trait object
  --> src/lib.rs:592:20
   |
37 | let mut iter = err.iter_chain();
   |                    ^^^^^^^^^^
```

**Comment by TimDiekmann** [comment]
Ah, I see ...

**Comment by haraldh** [comment]
And with both in place returning ErrorIter:

```rust
    let err: Box<Error> = b.into();
    let mut iter = err.iter_chain();
```
```
37 | let mut iter = err.iter_chain();
   |                    ^^^^^^^^^^ multiple `iter_chain` found
   |
   = note: candidate #1 is defined in an impl for the type `(dyn Error + 'static)`
note: candidate #2 is defined in the trait `Error`
```
Where #2 cannot even be used :-1:

**Comment by haraldh** [comment]
Anyway, I could probably live with:
```rust
 let mut iter = Error::iter_chain(&b);
```

**Comment by haraldh** [comment]
Here is a playground to play with.
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9af7455ec2501f1ec41183b6445bc515

**Comment by withoutboats** [comment]
This needs a proper tracking issue to track stabilization and let people report feedback (the issue provided is to this pull request). I also think that `iter_chain` is out of the norm for std iterator methods and we should change it (IMO the deprecated failure API is more consistent with the std norm, in which this would probably be called sources).

**Comment by sfackler** [comment]
Oh right, whoops. Tracking issue fix: #58521

**Pull request merged**
