### PR TITLE
resolve: miscellaneous clean-ups

### PR DESCRIPTION
**Pull request by jseyfried**
This PR consists of some small, miscellaneous clean-ups in `resolve`.
r? @eddyb

### CODE REVIEW

**Comment by jseyfried** [comment]
The last commit is also groundwork for a prototype of [RFC 1560](https://github.com/rust-lang/rfcs/pull/1560) that I'm planning.

**Comment by eddyb** [comment]
LGTM, but I'd like @nrc to also look it at.

**Comment by jseyfried** [comment]
cc @petrochenkov

**Pull request merged**
