### PR TITLE
rustc: remove type & lifetime parameter names from the typesystem.

### LINKED ISSUE #50125: Clean up the checks for `Self` type parameters
per @eddyb in https://github.com/rust-lang/rust/issues/49889#issuecomment-381129654
> I don't think we should need `is_self` and `has_self_ty` (or the `gensym` hack altogether), and instead we should rely on knowing that e.g. the item in scope is a `trait` and thus index `0` is `Self`.

### PR DESCRIPTION
**Pull request by eddyb**
Everything that needs a name, for whatever reason, must get it from the `DefId`.

Fixes #50125 by replacing special-casing of `Self` (and the gensym hack) with getting the type for the `Self` parameter from the trait, and comparing types with that, instead.

Also removes AST pretty-printing for input position `impl Trait`, it now prints like `-> impl Trait`.
That is, the relevant `ty::Predicate`s are obtained on the fly from the definition and printed.

r? @nikomatsakis cc @michaelwoerister @varkor @oli-obk @GuillaumeGomez

### CODE REVIEW

**Comment by michaelwoerister** [comment]
This should be a big improvement for https://github.com/rust-lang/rust/issues/49300 :heart:

**Comment by varkor** [comment]
@rust-timer build bc159c404dc86f12fe6e0315841c8694ed5fa2ca

**Comment by lqd** [comment]
Perf results are ready

**Comment by eddyb** [comment]
@nikomatsakis @michaelwoerister I was worried about this (perf results are pretty bad).

First of all, querying `def_key` shouldn't be that expensive, do you know what's up with that?

Secondly, why would *names of generic parameters* be needed outside error messages?
~~Is it us printing Rust types to give names to LLVM types? Anything else?~~
Worst offender is `serde-check` so it can't be anything from `rustc_codegen_llvm`.

**Comment by eddyb** [comment]
So, by using #53677, I was able to determine that [the commits *after* the first two](https://perf.rust-lang.org/compare.html?start=8bb91571ea5e75db22742d30e8ccca58b0bda2ee&end=bc159c404dc86f12fe6e0315841c8694ed5fa2ca) look roughly neutral, whereas [the first two commits themselves](https://perf.rust-lang.org/compare.html?start=f87d9135b485a044b35a09ec9c17b3c2556567f5&end=8bb91571ea5e75db22742d30e8ccca58b0bda2ee) contain most, if not all, of the regression.

So it's really having the `DefId` in there that's slowing things down. Maybe making *a lot* of types in the interner suddenly unshared? That's one reason using *only* indices is nicer overall.

**Comment by nikomatsakis** [comment]
@eddyb 

> So it's really having the DefId in there that's slowing things down. Maybe making a lot of types in the interner suddenly unshared? That's one reason using only indices is nicer overall.

Interesting. As you know, I sort of want to have only indices *anyway*, but still, I'm a bit surprised to see the impact as large as it is, given that we already have names. I guess we only use a relative small set of names?

**Comment by michaelwoerister** [comment]
Looking at the first two commits, nothing jumps out immediately as being slow. Since the slowdown in serde is so visible, running things in a profiler might give a good indications where the slowdown comes from.

**Comment by TimNN** [comment]
Ping from triage @eddyb: What are your plans for this PR?

**Comment by eddyb** [comment]
@TimNN I'm not sure. Maybe if @michaelwoerister or @nnethercote can help me profile it, and we end up finding a problem somewhere else that's causing the slowdown, that'd be great?
But otherwise I'd have to make the jump to indices-only and that's much harder to get right.

**Comment by nnethercote** [comment]
@eddyb: https://github.com/rust-lang-nursery/rustc-perf/tree/master/collector has recently-improved docs on benchmarking and profiling. If you can use Cachegrind, that's probably best because you can get diffs between two different profiles, which is very useful for understanding regressions.

**Comment by eddyb** [comment]
> Callgrind collects the same information as Cachegrind, plus function call information. So it can be used like either Cachegrind or perf-record. However, it cannot perform diffs between profiles.

That's a shame, I like Callgrind. Anyway,  I might have a go at this, but not any time soon, due to time constraints on the edition.

**Comment by TimNN** [comment]
Ping from triage @eddyb: What is the status of this PR?

**Comment by TimNN** [comment]
Ping from triage @eddyb: Since we haven't heard from you on this PR in a while and since you stated yourself that you won't have time to work on this PR in the near future I'm closing this as inactive for the moment, in line with our [triage guidelines](https://forge.rust-lang.org/triage-procedure.html). Please re-open in the future and thanks for all your work on `rustc`!

**Comment by eddyb** [comment]
@nikomatsakis Did you have a concrete plan for something like `ParamEnv` but for a global concept of "generic parameters in scope" that's not semantically relevant, only used for diagnostics?
What should enter/exit it? Should we tie it to the query engine, just like `tcx.at(span)`?

**Pull request closed without merging**
