### PR TITLE
./x.py: add --only lint1,lint2 flag to ./x.py clippy which only runs specified lints and ignores all others

### PR DESCRIPTION
**Pull request by matthiaskrgr**
for example:
 ./x.py clippy --only or_fun_call,type_complexity
will only run these two clippy lints.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I guess this doesn't seem *bad* but feels like rustbuild is really the wrong place for it... I am wondering what you think about trying to propose this for clippy, at which point something like `CLIPPYFLAGS="--only foo" x.py clippy` would work. Presumably it's a more widespread need than just the rustc codebase?

If that feels wrong though this approach seems fine, not too complicated.

**Comment by matthiaskrgr** [comment]
In the clippy readme, we have already documented that one can run `cargo clippy -- -Aclippy::all -Wclippy::only_this_one` for a single project, but for `x.py`, simply putting this into `RUSTFLAGS` does not work unfortunately which is why I added the workaround
````
 error[E0602]: unknown lint: `clippy::all`
  |
  = note: requested on the command line with `-A clippy::all`
````

**Comment by Mark-Simulacrum** [comment]
Hm, I would like to fix this by fixing that - I'm not sure why it's not working, but seems plausible that it's because there's a non-clippy cargo running to build bootstrap itself. Could we do this with a general clippy args variable (or just `x.py clippy -- <args here>`)

**Comment by Mark-Simulacrum** [comment]
@matthiaskrgr I think I recently saw a comment to the effect of you having done this somewhere else, but maybe that was in this PR?

I am leaning towards closing this PR unless it switches to the "general arguments" shape i.e., `x.py clippy -- --any-args-here`.

**Pull request closed without merging**
