### PR TITLE
clean stage-specific artifacts using `x clean --stage`

### LINKED ISSUE #109313: `x clean --stage 1` silently does the wrong thing
I tried this code:

```rust
x clean --stage 1
```

I expected to see this happen: bootstrap only deletes stage 1 artifacts:
```
; ls build/x86_64-unknown-linux-gnu/stage1* -d
build/x86_64-unknown-linux-gnu/stage1        build/x86_64-unknown-linux-gnu/stage1-tools
build/x86_64-unknown-linux-gnu/stage1-rustc  build/x86_64-unknown-linux-gnu/stage1-tools-bin
build/x86_64-unknown-linux-gnu/stage1-std
```

Instead, this happened: bootstrap completely ignored the `--stage` flag and deleted everything in the `build` directory except for `cache`.

### Meta

HEAD is branched from 13afbdaa0655dda23d7129e59ac48f1ec88b2084

### PR DESCRIPTION
**Pull request by onur-ozkan**
fixes #109313

### CODE REVIEW

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+ rollup

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang-ci/rust/actions/runs/5707514313/job/15464267886#step:24:43815
https://github.com/rust-lang/rust/pull/114261

**Pull request merged**
