### PR TITLE
buffer lexer errors in rustdoc syntax checking

### PR DESCRIPTION
**Pull request by euclio**
The code isn't ideal (I really would like to display the errors inline), but this at least gets us to where we were before #63017.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It's a bit better, however we lost the context. It now just says "we have this error in this code block" but doesn't provide the line or anything. Can you provide more information for the users?

**Comment by euclio** [comment]
We could provide the line/col number, but doing anything more would be significant work that I would rather explore in a separate PR (I'm not sure that we can translate the spans in the general case).

To be clear, this is fixing a regression (we've reopened #53919) and bringing the output back to where it was in 1.34.0.

**Comment by GuillaumeGomez** [comment]
Then please add a TODO in the code and open an issue so we don't lose track of this. Then r=me. Thanks a lot!

**Comment by euclio** [comment]
@GuillaumeGomez Added a TODO and created the issue.

**Comment by euclio** [comment]
Rebased.

**Pull request merged**
