### PR TITLE
[beta] Beta backports

### PR DESCRIPTION
**Pull request by ehuss**
* Remove the unused-#[doc(hidden)] logic from the unused_attributes lint #98336 
* debuginfo: Fix NatVis for Rc and Arc with unsized pointees. #98137 
* Revert "remove num_cpus dependency" in rustc and update cargo #97911 
* Update LLVM submodule #97690 
* Revert #96682. #97636 
* don't do Sized and other return type checks on RPIT's real type #97431 
* Temporarily disable submodule archive downloads. #98423

### CODE REVIEW

**Comment by ehuss** [comment]
@bors p=1

Oh my, the queue is super long. 😦

**Comment by Dylan-DPC** [comment]
You will need to backport the CI fix as well

**Comment by ehuss** [comment]
Added #98423.

@bors r+

**Pull request merged**
