### PR TITLE
(Shot at) Fix endian bugs in i128 intrinsic impls

### PR DESCRIPTION
**Pull request by nagisa**
Attempt to fix the endianness issues on big-endian machines such as power pc. Could not test if it actually makes stuff work on the powerpc, because setting up cross-compiler for ppc seems to be nigh-impossible on arch.

### CODE REVIEW

**Comment by nagisa** [comment]
Since the buildbots do not run tests for powerpc, its hard to add tests (and the current tests would’ve caught the problem); I will manually check whether the issue gets fixed once nightlies with this commit come out.

**Review by eddyb — APPROVED** [review]

**Comment by nagisa** [comment]
Failure not caused by this PR.

**Comment by alexcrichton** [comment]
@bors: retry

* netbsd network failure #39097

**Pull request merged**
