### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by RalfJung**
Successful merges:

 - #72389 (Explain move errors that occur due to method calls involving `self`)
 - #72598 (Display information about captured variable in `FnMut` error)
 - #72804 (Further tweak lifetime errors involving `dyn Trait` and `impl Trait` in return position)
 - #72932 (Clarify the behaviour of Pattern when used with methods like str::contains)
 - #72936 (Upgrade Chalk)
 - #73044 (compiletest: Add directives to detect sanitizer support)
 - #73086 (Rename "cyclone" to "apple-a7" per changes in upstream LLVM)
 - #73267 (Use the built cargo for cargotest.)
 - #73290 (Fix links when pinging notification groups)
 - #73308 (pretty/asm.rs should only be tested for x86_64 and not AArch64)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by tmiasko** [comment]
#73044  failed in previous rollup.

**Comment by RalfJung** [comment]
I thought it was https://github.com/rust-lang/rust/pull/73065 that failed? I am confused.

**Comment by RalfJung** [comment]
*sigh* re-rolling-up *again*...

**Pull request closed without merging**
