### PR TITLE
Use diagnostics for trace_macro instead of println

### LINKED ISSUE #22597: trace_macros output should use span_note?

### PR DESCRIPTION
**Pull request by estebank**
When using `trace_macro`, use `span_label`s instead of `println`:

```rust
note: trace_macro
  --> $DIR/trace-macro.rs:14:5
   |
14 |     println!("Hello, World!");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: expands to `println! { "Hello, World!" }`
   = note: expands to `print! { concat ! ( "Hello, World!" , "\n" ) }`
```

Fix #22597.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Do we have any tests of this feature? Maybe make a `src/test/ui` test?

**Comment by durka** [comment]
That's... a *ton* of extra noise, compared to:

```
println! { "" }
print! { concat ! ( "" , "\n" ) }
```

especially if a macro has multiple expansion steps. What's the concrete benefit to users of the feature, here? Can you at least get rid of the "macro in external crate" bit?

**Comment by nikomatsakis** [comment]
@durka line numbers seem like a win, but if they're just repeated N times, perhaps less useful that way. We could presumably make these attached `notes` without spans, right? (I've never actually used this utility...)

**Comment by durka** [comment]
Maybe it's possible to attach all the expansion steps to one span? Like this:

```
note: trace_macro
  --> ../../src/test/run-pass/log_syntax-trace_macros-macro-locations.rs:27:5
   |
27 |     println!("");
   |     ^^^^^^^^^^^^^ expands to `println! { "" }`
   |     ^^^^^^^^^^^^^ expands to `print! { concat ! ( "" , "\n" ) }`
```

**Comment by nikomatsakis** [comment]
@durka yes that was roughly what I had in mind, but probably more like

```
note: trace_macro
  --> ../../src/test/run-pass/log_syntax-trace_macros-macro-locations.rs:27:5
   |
27 |     println!("");
   |     ^^^^^^^^^^^^^ tracing macro expansion here
   | note: expands to `println! { "" }`
   | note: expands to `print! { concat ! ( "" , "\n" ) }`
```

**Comment by arielb1** [comment]
@estebank - friendly ping to keep this on your radar

**Comment by estebank** [comment]
Updated.

**Review by nikomatsakis — APPROVED** [review]

**Pull request merged**
