### PR TITLE
Optimize `LexicalResolve::expansion`.

### PR DESCRIPTION
**Pull request by nnethercote**
A win for `unicode_normalization`.

r? @nikomatsakis

### CODE REVIEW

**Comment by nnethercote** [comment]
I tried a whole lot of different things to speed this up, but commit 2 was the only thing that helped. Commits 1 and 3 are just minor clean-ups.

**Review by nikomatsakis — APPROVED** [review]
This seems ok but I will probably have to undo it shortly, if I land https://github.com/rust-lang/rust/pull/65232. Well, perhaps *adapt* it is more correct -- there's probably a shortened test that would be equally efficient.

**Comment by nikomatsakis** [comment]
r=me

**Comment by nnethercote** [comment]
The rust-timer queue command seems to have failed. Let's try it the old-fashioned way:

@rust-timer build bb3defd56b91fd479b0d8deffea23a68f3936982

**Pull request merged**
