### PR TITLE
Use AllFacts from polonius-engine

### PR DESCRIPTION
**Pull request by spastorino**

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@spastorino you have to add the crate to [the whitelist](https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs#L58-L59)

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors delegate=spastorino 

r=me once travis is happy

**Comment by KiChjang** [comment]
:frog:

**Pull request merged**
