### PR TITLE
Track inlined items and merge their docstrings when creating clean attributes

### LINKED ISSUE #84619: Documentation on re-exports is ignored if the item is defined in the same crate
I tried this code:

```rust
mod inner_mod {
    /// docs from inner module
    pub fn g() {}
}

/// docs from outer module
pub use inner_mod::g;
```

I expected to see this happen: The documentation is added, like it is for cross-crate re-exports:
image

```rust
/// Some docs from outer crate
pub use inner::f;
```

Instead, this happened: The documentation is ignored:

image

### Meta

`rustdoc --version`: rustdoc 1.53.0-nightly (392ba2ba1 2021-04-17)

_Originally posted by @jsgf in https://github.com/rust-lang/rust/issues/84597#issuecomment-827215642_

### PR DESCRIPTION
**Pull request by lambinoo**
Fixes #84619

### CODE REVIEW

**Comment by camelid** [comment]
I think this will duplicate docstrings for non-local inlined items. I also think isn't the right approach. Can you try https://github.com/rust-lang/rust/issues/84619#issuecomment-855324802?

**Comment by lambinoo** [comment]
@camelid I did add a tracing::warn at the beginning when I was trying to understand when it was being called. With the example in the issue, it never gets called.

I think that's the call path that's relevant:
`try_inline < clean_use_statement < clean_maybe_renamed_item for each DocModule::items`

`DocModule::items` itself gets filled by `RustdocVisitor::visit_item()`. When it comes to `use statements`, it only adds them to the stack when they are not being inlined themselves by `maybe_inline_local`.

That's the reason I took this path of keeping track of every "inlined" items.

**Comment by Dylan-DPC** [comment]
@lambinoo any updates on this?

**Comment by Dylan-DPC** [comment]
Closing this as inactive

**Pull request closed without merging**
