### PR TITLE
PTX support, take 2

### PR DESCRIPTION
**Pull request by japaric**
**UPDATE** [Documentation](https://github.com/japaric/nvptx)

---

- `--emit=asm --target=nvptx64-nvidia-cuda` can be used to turn a crate
  into a PTX module (a `.s` file).

- intrinsics like `__syncthreads` and `blockIdx.x` are exposed as
  `"platform-intrinsics"`.

- "cabi" has been implemented for the nvptx and nvptx64 architectures.
  i.e. `extern "C"` works.

- a new ABI, `"ptx-kernel"`. That can be used to generate "global"
  functions. Example: `extern "ptx-kernel" fn kernel() { .. }`. All
  other functions are "device" functions.

~~[Example](https://github.com/japaric/cuda)~~ Outdated. The examples have been move. See link at the top.

### CODE REVIEW

**Comment by rkruppe** [comment]
This looks like a good start to me. Thank you so much for coming back to this, right when I'd given up hope :smile:

I am pleasantly surprised that core works now. Given that there were previously missing LLVM intrinsics, what changed? Did the LLVM backend just get better, or did something change on our end? (The diff doesn't include any obvious canidates.)

An built-in target would be nice eventually but given the stability issue I'd say it's best to punt on it now. Eventually, when we've solved other open issues and are ready to e.g. ship pre-built core binaries for it, we can talk about it again. For now, using this target is already more involved than ordinary targets, so lugging around a JSON file as well isn't a big burden.

**Comment by japaric** [comment]
Rebased.

@rkruppe 

> Given that there were previously missing LLVM intrinsics, what changed?

Apparently, it fixed itself. 😄

> An built-in target would be nice eventually but given the stability issue I'd say it's best to punt on it now. 

There's the unstable built-in target option though. It would not only help in this case, but could also be used for the WIP msp430 target.

**Comment by alexcrichton** [comment]
Awesome work @japaric! This all looks great to me. It's all unstable so I'd be fine landing as well.

@brson do you have thoughts on this?

**Comment by alexcrichton** [comment]
Ok discussed during tools triage today, and decision was to merge!

@bors: r+

**Comment by alexcrichton** [comment]
Ok well that's one that I haven't seen before. @japaric I think this is what you get for writing such long and detailed commit messages! The actual failure there was:

```
failures:
    process::tests::test_inherit_env
test result: FAILED. 757 passed; 1 failed; 4 ignored; 0 measured
error: test failed
```

Where if we check the logs we find:

```
thread '<unnamed>' panicked at 'output doesn't contain `APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED=...`
```

That message is super long because apparently AppVeyor put the whole commit message in an environment variable (escaped newlines and all). The weird part is that the env var *is* in the output. In Rust, however, we expect the env var value to end with `APPVEYOR_REPO_COMMIT_TIMESTAMP=2016-12-29T07:10:41.0000000Z`. In the output of the `set` command on Windows, however, the environment variable value ends with `USERDOMAIN_ROAMINGPROFILE=APPVYR-WIN`. 

So I'm reading that as:

* We didn't find the right output from `set`
* The output of `set` was the same as what we expected, except for what came after the very last `... Why should this be merged?\n\n-`.
* *Rust* expects to see something that's actually its own separate environment variable
* *`env`* expects to see something that's not an environment variable exactly but *looks* like an environment variable.

I just double-checked the implementation of `env::vars` on Windows and it looks ok. I have no idea where the bug would be if it's on our side, and I also have no idea if this is a bug either in `env` or how we're expecting `env` to behave.

I... guess we could try trimming the commit message and trying again?

**Comment by xen0n** [comment]
I believe the message included is in fact the PR description? One way to work around this may be moving the text into a commit, leaving the PR description minimal.

**Comment by japaric** [comment]
I have reduced the PR description to match the commit message, which is much shorter. I'll open a new thread with more details in the user forum after this lands and then add a link to that thread to the PR description.

@bors r=alexcrichton

**Comment by xen0n** [comment]
Er, I think the thread should be created and referenced *before* the PR lands, as the PR message would be frozen into git history at landing. So that people who prefer looking at commits could immediately link to the details without having to click through the branch information.

In short: please ensure that `'thread: 'auto_merge_commit`. ;-P

**Pull request merged**
