### PR TITLE
Update some minor dependencies

### PR DESCRIPTION
**Pull request by alexcrichton**
* run `cargo update`
* Update cargo submodule
* Update to the `cc` crate from `gcc`

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@bors r+

I'm guessing these travis failures are not legit, although it's *plausible* they could be (running make, it appears):

```
[00:55:53] make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[00:55:53] error: multiple input filenames provided
```

**Comment by kennytm** [comment]
The changeset here seems to be a subset of #44769. The CI failing reason is also the same.

**Comment by alexcrichton** [comment]
@kennytm I think that's due to a [technical breaking change](https://github.com/rust-lang-nursery/getopts/pull/53) in the `getopts` crate. This is basically something that's always been a bug in rustc, though, so I'm going to just fix the bug here.

**Comment by kennytm** [comment]
Same error as the roll up. `dist i686-apple-darwin` failed to build `fabricate`, as it tries to link to the 64-bit version of `liblzma.dylib`.

I think the problem is in the `xz2` crate.

<details>

```
[01:19:52]    Compiling installer v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/tools/rust-installer)
[01:20:01] error: linking with `cc` failed: exit code: 1
[01:20:01]   |
[01:20:01]   = note: "cc" "-m32" "-L" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/fabricate-3c62b36ee9e51931.0.o" "-o" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/fabricate-3c62b36ee9e51931" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/fabricate-3c62b36ee9e51931.crate.allocator.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps" "-L" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/release/deps" "-L" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/build/miniz-sys-e4d25a983ce954bb/out" "-L" "/usr/local/Cellar/xz/5.2.3/lib" "-L" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libclap-0230a9cb538dc003.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libtextwrap-b6d7886f4b0b9cf9.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libatty-eab333ee87c84859.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libstrsim-08d7961036884df3.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libansi_term-0b825afb3b7c5988.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libyaml_rust-fd217bbf88ed751d.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libunicode_width-fec6adfa89b5eeca.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libbitflags-c99c4172cfbf4ade.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libinstaller-44d3ce42f394a42d.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libxz2-34662535944e2d19.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/liblzma_sys-0b703c55032d517a.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libwalkdir-f09df3519321b93a.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libsame_file-9cb37239cb187c37.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libtar-aa5ad05876b78813.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libxattr-764b82d8f9a285ee.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libfiletime-b6b8e16649cffdd9.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/liberror_chain-5c54ea8e449cace7.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libbacktrace-3d2308bbfa4577fc.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/librustc_demangle-9096d2f407fc495e.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libcfg_if-cc2c205191b44d71.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libvec_map-4eb2b41675c3d103.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libflate2-0da96a052efd7371.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libminiz_sys-cd0452ee0df15cc0.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/libterm_size-a020674392ce8116.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools/i686-apple-darwin/release/deps/liblibc-a6042ed747f41a22.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/libstd-ef7c282e33080735.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/libpanic_unwind-67d3063a3e7b933e.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/libunwind-a5f8f2a65a894cab.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/liballoc_system-9da0d87cad7653ba.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/liblibc-5c2f4286c8e4e033.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/liballoc-e6fe1510f2126260.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/libstd_unicode-e5902c17d8af81cd.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/librand-d0443d9d990bafa4.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/libcore-36a7d07063913568.rlib" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-sysroot/lib/rustlib/i686-apple-darwin/lib/libcompiler_builtins-75463249b0d19986.rlib" "-l" "lzma" "-l" "System" "-l" "resolv" "-l" "c" "-l" "m" "-Wl,-rpath,@loader_path/../lib"
[01:20:01]   = note: ld: warning: ignoring file /usr/local/Cellar/xz/5.2.3/lib/liblzma.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/xz/5.2.3/lib/liblzma.dylib
[01:20:01]           ld: warning: could not create compact unwind for __ZN33_$LT$vec_map..VecMap$LT$V$GT$$GT$6insert17h985cf9a77a2756d2E: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN5alloc3str21_$LT$impl$u20$str$GT$5parse17h93606f9ca8cbf8b9E: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN4clap3app6parser6Parser7add_arg17h61eb849277d7b591E: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN4clap3app6parser6Parser16get_matches_with17h900270fa6169d5c5E: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN4clap3app4help4Help17write_subcommands17h6bd1a2a8e5e3978fE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN4clap3app3App11get_matches17h578e1f0f74470455E: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN126_$LT$clap..app..App$LT$$u27$a$C$$u20$$u27$a$GT$$u20$as$u20$core..convert..From$LT$$RF$$u27$a$u20$yaml_rust..yaml..Yaml$GT$$GT$4from17h9223771fce05e89eE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN4clap4args3arg3Arg9from_yaml17hdc001257201be01aE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN92_$LT$clap..app..parser..Parser$LT$$u27$a$C$$u20$$u27$b$GT$$u20$as$u20$core..clone..Clone$GT$5clone17hf5314030fafcc266E: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN9installer8combiner8Combiner3run17hd0d723c6e29c2277E: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN5alloc3str21_$LT$impl$u20$str$GT$5parse17h836ae9b4fe1aac7fE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN72_$LT$tar..archive..Archive$LT$std..io..Read$u20$$u2b$$u20$$u27$a$GT$$GT$7_unpack17h65ffef2b792ac39eE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN3tar7archive13EntriesFields14next_entry_raw17hffa574a8102e656eE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN92_$LT$tar..archive..EntriesFields$LT$$u27$a$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$4next17h6f192390644da25aE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN3tar7builder6append17h0faffa7eef7a83edE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN3tar7builder14append_dir_all17h722c448f9a6472ceE: stack subl instruction is too different from dwarf stack size
[01:20:01]           ld: warning: could not create compact unwind for __ZN3tar5entry11EntryFields6unpack17hbf7b719cc260d7a1E: stack subl instruction is too different from dwarf stack size
[01:20:01]           Undefined symbols for architecture i386:
[01:20:01]             "_lzma_code", referenced from:
[01:20:01]                 xz2::stream::Stream::process_vec::h6982d81691a74956 in libxz2-34662535944e2d19.rlib(xz2-34662535944e2d19.0.o)
[01:20:01]             "_lzma_easy_encoder", referenced from:
[01:20:01]                 xz2::stream::Stream::new_easy_encoder::h86de25ee252da727 in libxz2-34662535944e2d19.rlib(xz2-34662535944e2d19.0.o)
[01:20:01]             "_lzma_end", referenced from:
[01:20:01]                 core::ptr::drop_in_place::ha046c3757bcbed4b in libxz2-34662535944e2d19.rlib(xz2-34662535944e2d19.0.o)
[01:20:01]                 xz2::stream::Stream::new_easy_encoder::h86de25ee252da727 in libxz2-34662535944e2d19.rlib(xz2-34662535944e2d19.0.o)
[01:20:01]                 _$LT$xz2..stream..Stream$u20$as$u20$core..ops..drop..Drop$GT$::drop::heb90175cf1a7b342 in libxz2-34662535944e2d19.rlib(xz2-34662535944e2d19.0.o)
[01:20:01]           ld: symbol(s) not found for architecture i386
[01:20:01]           clang: error: linker command failed with exit code 1 (use -v to see invocation)
[01:20:01]           
[01:20:01] 
[01:20:01] error: aborting due to previous error
[01:20:01] 
[01:20:01] error: Could not compile `installer`.
```

</details>

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis p=1

We need to land this soon to get the rls component rename into nightlies and testing

**Comment by alexcrichton** [comment]
cc @est31, that may mean that something in libcompiler_builtins [updated here](https://github.com/rust-lang-nursery/compiler-builtins/compare/ef4951582f620c589cd9e18ec182538bf116bce3...789e8c159fc742295d8ade1c715d0d57108d555c) is botched.

**Comment by est31** [comment]
@alexcrichton if the issue persists, please back out the changes and dont let the PR be blocked by this. I'm not sure when I can give the issue enough attention for it to be fixed.

**Comment by kennytm** [comment]
RLS test failed,

```
[01:50:32] test test::test_handle_utf8_directory has been running for over 60 seconds
[01:54:52] test test::test_handle_utf8_directory ... FAILED
[01:54:52] 
[01:54:52] failures:
[01:54:52] 
[01:54:52] ---- test::test_handle_utf8_directory stdout ----
[01:54:52] 	thread 'test::test_handle_utf8_directory' panicked at 'Hit timeout', src\tools\rls\src\test\harness.rs:142:12
[01:54:52] 
[01:54:52] 
[01:54:52] failures:
[01:54:52]     test::test_handle_utf8_directory
[01:54:52] 
[01:54:52] test result: FAILED. 23 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:54:52] 
[01:54:52] error: test failed, to rerun pass '--bin rls'
[01:54:52] 
[01:54:52] 
[01:54:52] command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "test" "--target" "x86_64-pc-windows-msvc" "--release" "--locked" "--color" "always" "--manifest-path" "C:\\projects\\rust\\src/tools/rls/Cargo.toml"
[01:54:52] expected success, got: exit code: 101
```

Not sure if legit.

BTW could you update the rustdoc dependency `html-diff` to 0.0.5 in this PR as well?

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis

@kennytm I don't really know anything about `html-diff`, so that may be best left to a future PR

**Pull request merged**
