### PR TITLE
target abi

### PR DESCRIPTION
**Pull request by joshtriplett**
Implement cfg(target_abi) (RFC 2992)

Add an `abi` field to `TargetOptions`, defaulting to "". Support using
`cfg(target_abi = "...")` for conditional compilation on that field.

Gated by `feature(cfg_target_abi)`.

Add a test for `target_abi`, and a test for the feature gate.

Add `target_abi` to tidy as a platform-specific cfg.

Update targets to use `target_abi`

All eabi targets have `target_abi = "eabi".`
All eabihf targets have `target_abi = "eabihf"`.
`armv6_unknown_freebsd` and `armv7_unknown_freebsd` have `target_abi = "eabihf"`.
All abi64 targets have `target_abi = "abi64"`.
All ilp32 targets have `target_abi = "ilp32"`.
All softfloat targets have `target_abi = "softfloat"`.
All *-uwp-windows-* targets have `target_abi = "uwp"`.
All spe targets have `target_abi = "spe"`.
All macabi targets have `target_abi = "macabi"`.
aarch64-apple-ios-sim has `target_abi = "sim"`.
`x86_64-fortanix-unknown-sgx` has `target_abi = "fortanix"`.
`x86_64-unknown-linux-gnux32` has `target_abi = "x32"`.

Add FIXME entries for targets for which existing values need to change
once `cfg_target_abi` becomes stable. (All of them are tier 3 targets.)

Add a test for `target_abi` in `--print cfg`.

### CODE REVIEW

**Comment by nagisa** [comment]
I know I'm late to the party.

> Add an abi field to TargetOptions, defaulting to "".

Does that mean that for these targets `cfg(target_abi = "")` will be true? This would be, I believe, the first instance of this in the compiler.

> All eabi targets have target_abi = "eabi".
> All eabihf targets have target_abi = "eabihf".
> All softfloat targets have target_abi = "softfloat".

This makes me wonder if `target_abi` should be a zero-or-more kind of variable. For example, `softfloat` is a more general property that is shared with `eabi`.

**Comment by joshtriplett** [comment]
@nagisa I think it should be 0-or-more, yes. That would take an updated RFC to propose. In the meantime, this is forward-compatible; we can always make `target_abi` match multiple things.

**Comment by joshtriplett** [comment]
The test failure appears to be entirely unrelated.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/rust/pull/86419#issuecomment-877848693

**Pull request merged**
