### PR TITLE
Subtree update of `rust-analyzer`

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by Veykril** [comment]
The beta branch happened yesterday (I think?) So we need to backport this once merged as this contains a fix for a problematic proc-macro server issue.

**Comment by workingjubilee** [comment]
tagging per https://github.com/rust-lang/rust/pull/129733#issuecomment-2320787532 but maybe backporting a more minimal diff is more apropos? idk.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/17994 is the fix in this pull which should backport cleanly

(does rustbot let me do this?)
@rustbot label +beta-accepted

**Comment by compiler-errors** [comment]
@Veykril @lnicola: Can you identity the subset of commits that are needed to fix whatever beta issue? Those probably should be cherry-picked onto beta rather than this whole subtree sync. I fear that this will not merge cleanly on given that it contains a ton of other unrelated changes.

**Comment by compiler-errors** [comment]
Ah, I misread the linked PR :D

**Comment by lnicola** [comment]
Just to be sure, I don't need to do anything here because _someone_ will file a rollup backport PR which includes this?

**Comment by Veykril** [comment]
Okay, looking into trying to backport the commits it turns out I mixed things up, the current `beta` branch does not contain this issue. Whatever branched off on the 30th of August should have the problem though.

@rustbot label -beta-accepted -beta-nominated

**Pull request merged**
