### PR TITLE
Add test for #14875

### LINKED ISSUE #14875: Failing destructors leak resources
In this program, the local variable `_a` is leaked:

```rust
struct Foo;

impl Drop for Foo {
    fn drop(&mut self) { fail!(); }
}

fn main() {
    let _a = box 1;
    let _b = Foo;
}
```

### PR DESCRIPTION
**Pull request by cristicbz**
You can check this out in the playground https://is.gd/oVKC2T . It will fail on stable, but pass on nightly as @nagisa suggested on the issue.

Fixes #14875

### CODE REVIEW

**Comment by nagisa** [comment]
I feel like the test can be made considerably simpler and easier to understand [like this](https://play.rust-lang.org/?gist=e197e8f721360be414e921aa44d84015&version=nightly&backtrace=0), but I guess this approach is also good.

**Comment by cristicbz** [comment]
@eddyb As far as I can tell the only failure is

```
test [run-pass] run-pass/issue-36023.rs ... FAILED
```

My test passes

```
test [run-pass] run-pass/issue-14875.rs ... ok
```

```
test [pretty] pretty/issue-14875.rs ... ok
```

Could you please `@bors retry`?

**Comment by nagisa** [comment]
@cristicbz that’s the Travis failing (see https://github.com/rust-lang/rust/issues/36138). Bors will get to your PR regardless of travis status and build it itself. You can track your PR status with bors [here](https://buildbot.rust-lang.org/homu/queue/rust).

**Comment by cristicbz** [comment]
@nagisa D'oh! I thought @bors also set commit statuses, but I guess not, thanks!

**Comment by jonathandturner** [comment]
That error is a current bug in travis that's being looked at.

**Pull request merged**
