### PR TITLE
impl FusedIterator and a size hint for the error sources iter

### PR DESCRIPTION
**Pull request by Sky9x**
cc tracking issue #58520

### CODE REVIEW

**Comment by Sky9x** [comment]
r? libs-api

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by matthiaskrgr** [comment]
@bors r-
need x.py fmt

https://github.com/rust-lang/rust/pull/127196#issuecomment-2199357849

**Comment by Sky9x** [comment]
ok :(

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
