### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ydah**
This PR is fixes typo "avaiable" to "available".

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup

**Comment by klensy** [comment]
https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy, so no merge commit.

**Comment by GuillaumeGomez** [comment]
And it'd be nice to not push after an approval and not tell.

**Comment by ydah** [comment]
@GuillaumeGomez Sorry. I seem to have accidentally pushed a merge commit to this PR branch.
I have re-created the PR again.

**Comment by GuillaumeGomez** [comment]
Let's go again then!

@bors r+ rollup

**Pull request merged**
