### PR TITLE
Remove impls for `InternedString`/string equality.

### PR DESCRIPTION
**Pull request by nnethercote**
`Symbol` received the same treatment in #60630.

Also, we can derive `PartialEq` for `InternedString`.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
@rust-timer build 041ca93148340a96ff67871ddbf2b0422f6d9abe

**Comment by petrochenkov** [comment]
r=me once perf run is complete

**Comment by nnethercote** [comment]
It's a slight perf win.

@bors r=petrochenkov

**Pull request merged**
