### PR TITLE
Forbid nested opaque types to reference HRTB from opaque types.

### PR DESCRIPTION
**Pull request by cjgillot**
Avoids https://github.com/rust-lang/rust/issues/96194
Alternative to https://github.com/rust-lang/rust/pull/96970

r? @oli-obk

### CODE REVIEW

**Comment by jackh726** [comment]
This seems much nicer than #96970.

Crater run for this can happen in parallel, but let's get this in for the release train.

@bors r+ p=1

**Comment by Mark-Simulacrum** [comment]
Backported to beta via https://github.com/rust-lang/rust/pull/97040.

**Pull request merged**
