### PR TITLE
Allow plugins to register LLVM passes

### PR DESCRIPTION
**Pull request by kmcallister**
r? @brson

I'm using this to integrate rustc with [american-fuzzy-lop](http://lcamtuf.coredump.cx/afl/). Building with afl instrumentation is no different from loading any other plugin library.

I'd like this PR to include a `run-make` test with a custom LLVM pass; however I'm not sure it's worth the trouble of building C++ code and linking LLVM from the test suite (are there existing tests that do this?)

### CODE REVIEW

**Comment by brson** [comment]
This looks ok to me. Although I don't like exposing more LLVM-ness, this is already behind the plugin gate which is known to be problematic.

I want AFL to work.

**Comment by brson** [comment]
Waiting to hear what @nrc? thinks.

**Comment by kmcallister** [comment]
> I want AFL to work.

Then I have [good news for you](https://gist.github.com/kmcallister/9ba8deeb15f952cc1cf1).

**Pull request merged**
