### PR TITLE
Suggest pub instead of public for const type item

### LINKED ISSUE #101626: Edge case does not suggest changing invalid `public` with `pub`
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=30d2fb5d1b3b7cbfd0f9d377e0d0a11f)

```rust
mod test {
    public const X: i32 = 123;
}

fn main() {
    println!("{}", test::X);
}
```

The current output on stable 1.63.0:
```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!` or `::`, found keyword `const`
 --> src/main.rs:2:12
  |
2 |     public const X: i32 = 123;
  |            ^^^^^ expected one of `!` or `::`

error: could not compile `playground` due to previous error
```

The current output on Beta version 1.64.0-beta.6 (2022-09-09 25912c09710a2de2a97b):
```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!` or `::`, found keyword `const`
 --> src/main.rs:2:12
  |
2 |     public const X: i32 = 123;
  |            ^^^^^ expected one of `!` or `::`
  |
help: write `pub` instead of `public` to make the item public
  |
2 |     pub const X: i32 = 123;
  |     ~~~

error: could not compile `playground` due to previous error
```

The current output on Nightly version 1.65.0-nightly (2022-09-09 1d37ed661a6922e7a167):

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!` or `::`, found keyword `const`
 --> src/main.rs:2:12
  |
2 |     public const X: i32 = 123;
  |            ^^^^^ expected one of `!` or `::`

error: could not compile `playground` due to previous error
```

Since #99903 ( cc @gimbles ) is somewhat recent the help diagnostics improvement currently is only on beta. However, the latest nightly has regressions regarding the suggestion as shown above. Hence, the output should suggest changing `public` with `pub` as that is the desired output.

Note: base issue for improved diagnostics (`public` -> `pub`): #99653

Note: since this is technically a regression from beta to nightly, what should be the appropriate label to add? The one below this?
@rustbot label +regression-untriaged

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #101626

### CODE REVIEW

**Comment by Rageking8** [comment]
Is the missing `#` in front of the issue number this fixes intentional?

**Comment by chenyukang** [comment]
> Is the missing `#` in front of the issue number this fixes intentional?

no, just forget it, updated it now.

**Review by TaKO8Ki — COMMENTED** [review]
@bors r+ rollup

**Pull request merged**
