### PR TITLE
SVN version of LLVM is 3.7 now

### PR DESCRIPTION
**Pull request by jauhien**
Subj. Also, sould we change this check to something else? As it is a little bit annoying to fix it with every changing of LLVM version.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I know nothing of LLVM, re-assigning to @alexcrichton

**Comment by dotdash** [comment]
Seems a bit early to update that. We're using parts of LLVM that don't have a stable API, these might change between now and the time that 3.7 is actually released. So we shouldn't claim to be compatible with 3.7 just yet. I'd rather have that check only succeed for released LLVM versions. There could be a flag that skips the version check for those who want to build against LLVM trunk. Just my 2 cents.

**Comment by jauhien** [comment]
Yes, you are right. I was too optimistic, it fails with 3.7 atm.

**Comment by alexcrichton** [comment]
@jauhien would you be interested in adding the flag that @dotdash mentioned? Otherwise we may want to close this as it'll need some extra legwork to get up to date with 3.7

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/22147, but thanks again for the PR!

**Comment by jauhien** [comment]
@dotdash: thanks for adding a flag.

**Pull request closed without merging**
