### PR TITLE
added multidimensional array example in guide

### PR DESCRIPTION
**Pull request by ninjabear**
I've added a small example of what multidimensional arrays look like - I've had some trouble finding information on them myself. This could just serve as a prompt for someone with a bit more experience to put some information on n-dimensional arrays into the guide.

### CODE REVIEW

**Comment by steveklabnik** [comment]
I'm a tad conflicted here. Arrays actually _can't_ be multi-dimensional, but an array can contain other arrays. Beyond that, the Guide isn't intended to cover every single corner case, so while I _do_ think we should have something about doing this somewhere, I'm not 100% sure that this is the right place. For example, this is a great Rust by Example candidate.

So let me stew on it for a while. Any other thoughts?

(oh, and this would need to be four space indented)

**Comment by ninjabear** [comment]
I don't think a n-dimensional array has to be a contiguous block of memory for it to qualify - Java has been calling them multi-dimensional arrays for a long time and they're implemented as an object of objects (array is an object, albeit one with some syntactical sugar on top). If it looks and acts like a dog then its better to call it a dog than any other name imho.

As for to put it in the guide or not, well I haven't been around here long enough to make a quality call on something like that. However I will say that I personally expected to see something on it in there because the guide has been my gold standard so far. It also covers what I'd describe as "day to day" usage, which I think matrices are for a lot of people.

**Comment by Diggsey** [comment]
These are multidimensional arrays in every sense: they are contiguous in memory because they're nested fixed size arrays, and all the inner arrays have the same length, so it can't be confused with a jagged array.
The fact that the type is defined as it is rather than "[x, y]" or "[x][y]" is mostly a syntactic difference.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Comment by ninjabear** [comment]
@alexcrichton, I looked at rebasing this but the guide has been replaced with a placeholder to the rust book. The link in it also appears to be broken, but i'll double check and raise an issue if this is the case.

I left this merge request dangling because @steveklabnik wanted some time to consider. Perhaps it's in the book now?

In either case I won't reopen this as the guide is no longer the place for it.

**Comment by steveklabnik** [comment]
Yeah, it's not directly in the book. I'm still not sure if I'm being weirdly pedantic here or not. But it would need to be moved regardless.

**Comment by ninjabear** [comment]
Pedantic about it being a feature of rust or if it should go in the guide? If its a feature of rust then it should go somewhere in the docs (maybe not the book?). I got to this point through kind of guessing the syntax (after googling failed) which isn't ideal.

**Comment by steveklabnik** [comment]
Pendantic about how it's not a feature of Rust, an array can have any type
inside, including another array. A special thing about 'multi-dimensional
arrays' feels like something special, when it's not.

**Comment by ninjabear** [comment]
This is how the JLS describes them (http://docs.oracle.com/javase/specs/jls/se8/html/jls-10.html)

>All the components of an array have the same type, called the component type of the array. If the component type of an array is T, then the type of the array itself is written T[].
>
> ...
>
> The component type of an array may itself be an array type. The components of such an array may contain references to subarrays. If, starting from any array type, one considers its component type, and then (if that is also an array type) the component type of that type, and so on, eventually one must reach a component type that is not an array type; this is called the element type of the original array, and the components at this level of the data structure are called the elements of the original array.


Some kind of readable variation of this?

**Pull request closed without merging**
