### PR TITLE
[BOLT] Use CDSort and CDSplit

### PR DESCRIPTION
**Pull request by aaupov**
CDSort and CDSplit are the most recent versions of function ordering and function splitting algorithms with some improvements over the previous baseline (ext-tsp and two-way splitting).

### CODE REVIEW

**Comment by aaupov** [comment]
CC @Kobzol

**Comment by Kobzol** [comment]
Hi! I already tried `cdsort`, it provided no performance benefit. I haven't tried it with `.arg("-split-strategy=cdsplit")` though.

I think that we'd need to bump our LLVM version for this, as it's 17.0.4 currently, and that doesn't know about `cdsort`, AFAIK.

**Comment by aaupov** [comment]
> Hi! I already tried `cdsort`, it provided no performance benefit. 

Interesting, do you have a link with perf stats? We observed some improvements on large binaries in icache and itlb misses.

> I haven't tried it with `.arg("-split-strategy=cdsplit")` though.

CDSplit is separate from cdsort and could be beneficial with hfsort+.

> I think that we'd need to bump our LLVM version for this, as it's 17.0.4 currently, and that doesn't know about `cdsort`, AFAIK.

Sorry about not checking the LLVM version used. CDSplit is also very recent and was only upstreamed a month ago. If you don't use trunk BOLT, it will probably be in the next release.

**Comment by Kobzol** [comment]
I think that we have talked about this on [Discord](https://discord.com/channels/636084430946959380/930647188944613406/1176930826773078176) :sweat_smile:

The previous attempt was [this commit](https://github.com/rust-lang/rust/commit/a8d4863b7477694948fd97c1d3500e9b9edd99e8), the results are [here](https://github.com/rust-lang/rust/pull/112049#issuecomment-1822610385).

There were a few cycles wins, nothing too big though. We could switch to `cdsort` once we bump LLVM to 18.

**Comment by Kobzol** [comment]
Looking at the results again, there were some nice max RSS improvements, and bootstrap time was also improved by 5s, which isn't trivial. Maybe I was too harsh to `cdsort`, it looks like an actual improvement.

**Comment by Kobzol** [comment]
I would suggest to first try only `.arg("-split-strategy=cdsplit")` in this PR, I can start a perf. run for that (assuming that we don't need LLVM 18 for it).

**Comment by aaupov** [comment]
> I would suggest to first try only `.arg("-split-strategy=cdsplit")` in this PR, I can start a perf. run for that (assuming that we don't need LLVM 18 for it).

We do need trunk (or LLVM 18 rc) BOLT for CDSplit.

**Comment by Kobzol** [comment]
I would suggest waiting for LLVM 18 RC, and then we can try both options.

**Comment by Kobzol** [comment]
LLVM 18-rc1 has been [tagged](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.0-rc1), so perhaps we can try it. The change needs to be made [here](https://github.com/rust-lang/rust/blob/38ff91c453a36257dcc4e9f487520f96079da578/src/ci/docker/host-x86_64/dist-x86_64-linux/build-clang.sh#L7).

**Comment by Kobzol** [comment]
@aaupov We now have LLVM 18 as the host compiler on CI. I tried the new CDSort/CDSpltit flags [here](https://github.com/rust-lang/rust/pull/112049#issuecomment-1987050999) and they provide nice max RSS reductions and also some cycle wins.

Could you please rebase so that I can start another perf. run?

**Comment by Kobzol** [comment]
A slight LLVM/`rustc` artifact size increase, but also very nice Max-RSS improvements. Thank you! Let us know if you have any other useful BOLT flags up your sleeve :)

@bors r+

**Pull request merged**
