### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #40018, #41096, #41168, #41183
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* openssl error https://github.com/rust-lang/rust/issues/40417

**Comment by TimNN** [comment]
@bors retry

* #40546

**Comment by TimNN** [comment]
```
[00:00:00] +++dirname src/ci/init_repo.sh
[00:00:00] ++cd src/ci
[00:00:00] ++pwd
[00:00:00] +ci_dir=/Users/travis/build/rust-lang/rust/src/ci
[00:00:00] +. /Users/travis/build/rust-lang/rust/src/ci/shared.sh
[00:00:00] +REPO_DIR=.
[00:00:00] +CACHE_DIR=/Users/travis/rustsrc
[00:00:00] +cache_src_dir=/Users/travis/rustsrc/src
[00:00:00] +cache_valid_file=/Users/travis/rustsrc/cache_valid1
[00:00:00] +'[' '!' -d . -o '!' -d ./.git ']'
[00:00:00] +cd .
[00:00:00] +'[' '!' -d /Users/travis/rustsrc ']'
[00:00:00] +'[' '!' -f /Users/travis/rustsrc/cache_valid1 ']'
[00:00:00] +set +o errexit
[00:00:00] ++cd /Users/travis/rustsrc/src
[00:00:00] ++git status --porcelain
[00:00:00] ++wc -l
[00:00:01] fatal: Not a git repository: src/compiler-rt/../../.git/modules/src/compiler-rt
[00:00:01] +stat_lines='       0'
[00:00:01] ++cd /Users/travis/rustsrc/src
[00:00:01] ++git status
[00:00:02] ++echo 128
[00:00:02] +stat_ec=128
[00:00:02] +set -o errexit
[00:00:02] +'[' '!' -d /Users/travis/rustsrc/src/.git -o 0 '!=' 0 -o 128 '!=' 0 ']'
[00:00:02] +echo 'WARNING: /Users/travis/rustsrc/cache_valid1 exists but bad repo: l:       0, ec:128'
[00:00:02] +rm -rf /Users/travis/rustsrc
[00:00:02] WARNING: /Users/travis/rustsrc/cache_valid1 exists but bad repo: l:       0, ec:128
[00:00:15] rm: /Users/travis/rustsrc/src: Directory not empty
[00:00:15] rm: /Users/travis/rustsrc: Directory not empty
```

cc @aidanhs

**Comment by aidanhs** [comment]
```
adding /Users/travis/rustsrc to cache
creating directory /Users/travis/rustsrc
running `casher add/Users/travis/docker /Users/travis/rustsrc` took longer than 180 seconds and has been aborted
```
ok, restoring the cache was aborted. This is fine, the paranoia script will just nuke it, as it then attempted. But `rm -rf` printing things like "directory not empty" sounds like either a bad disk or a network drive. Looking at the partitions:
```
$ echo "#### Build failed; Disk usage after running script:"; df -h; du . | sort -nr | head -n100
    
#### Build failed; Disk usage after running script:
Filesystem      Size   Used  Avail Capacity  iused    ifree %iused  Mounted on
/dev/disk0s2   149Gi   71Gi   78Gi    48% 18580816 20530880   48%   /
devfs          176Ki  176Ki    0Bi   100%      608        0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0        0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0        0  100%   /home
[...]
```
`auto_home` sounds suspiciously like a network drive, especially after searching online.

I would submit a PR to remove caching logic from everywhere, but that wouldn't have helped in this case - the `git submodule deinit -f . && git submodule update --init` loop that existed previously would also have blown up. I've created #41201 to track this issue, I don't have any better immediate suggestion than a retry.

**Pull request closed without merging**
