### PR TITLE
Do not delete bootstrap.exe on Windows during clean

### PR DESCRIPTION
**Pull request by rylev**
Windows does not allow deleting currently running executables.

This an addition to @jyn514's change in https://github.com/rust-lang/rust/pull/80574.

### CODE REVIEW

**Comment by the8472** [comment]
I thought windows 10 introduced a way to use posix unlink semantics, can't we use that?

**Comment by rylev** [comment]
@the8472 I believe we could theoretically use [`_unlink`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/unlink-wunlink?view=msvc-160) on Windows 10, but this doesn't work on older versions of Windows which is why the std library doesn't use it. Do we want to limit bootstrapping to Windows 10?

**Comment by the8472** [comment]
I mean we could avoid skipping cleanup if the system supports unlink semantics.

**Comment by Mark-Simulacrum** [comment]
I don't think platform version specific logic is worth it, personally, but I would like for us to warn the user when we fail to fully clean - it might also make sense to still try to clean up most of the bootstrap directory, even if we can't quite get the bootstrap binary.

**Comment by rylev** [comment]
@Mark-Simulacrum I've added more handling so the user is informed when something goes wrong on Windows.

**Comment by ChrisDenton** [comment]
> I thought windows 10 introduced a way to use posix unlink semantics, can't we use that?

Not for running binaries, IIRC. Even with posix unlink semantics (which is now the default for `DeleteFileW`), Windows honours exclusive file locks. And last I checked the exe loader still loads the binary without the `FILE_SHARE_DELETE` permission so nobody else can delete it.

There's no harm in trying though.

**Comment by jyn514** [comment]
Rustup has had serious problems with this (cc @kinnison), so if you figure out a way please let them know. I'm inclined to think it's not worth messing with, though.

**Comment by ehuss** [comment]
> There's no harm in trying though.

I tried a quick test with `_unlink`, and it still fails if the executable is running.  I'm pretty sure it is not possible.

**Comment by ChrisDenton** [comment]
Yes, that it's not currently possible was the message I was trying to convey with my explanation. Obviously I worded that badly, sorry. To rephrase: The Windows executable loader (which is outside Rust's control) does not currently set `FILE_SHARE_DELETE` which makes the `.exe` impossible to delete.

My point in that last sentence was only that there is not a problem with attempting to delete and handling the expected failure. The worst case it fails gracefully and in the best case some future version of Windows allows deleting running applications.

**Pull request merged**
