### PR TITLE
update miri

### PR DESCRIPTION
**Pull request by matthewjasper**
cc #57609 

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r+ p=1
(tool update, unblocks other work)

**Comment by matthewjasper** [comment]
rls toolstate failed? cc @nrc @Xanewok

I'm hoping this is spurious because (a) the test passed on windows (b) it appears to have failed due to the order of things.

@bors retry

**Comment by RalfJung** [comment]
I've seen pretty much the exact same message on the last attempt to update Miri as well: https://github.com/rust-lang/rust/pull/58535. That PR took like 5 attempts to land.

**Comment by Xanewok** [comment]
Unfortunately `client_changing_workspace_lib_retains_diagnostics` fails once in a blue moon; this seems like a race condition in rustc build scheduling? I'm sorry for the trouble, didn't investigate that yet myself. Feel free to ignore that and retry :disappointed: :bowing_man:

**Pull request merged**
