### PR TITLE
Rollup of 21 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #56594 (Remove confusing comment about ideally using `!` for `c_void`)
 - #57107 (Add a regression test for mutating a non-mut #[thread_local])
 - #57340 (Use correct tracking issue for c_variadic)
 - #57357 (Cleanup PartialEq docs.)
 - #57370 (Support passing cflags/cxxflags/ldflags to LLVM build)
 - #57501 (High priority resolutions for associated variants)
 - #57551 (resolve: Add a test for issue #57539)
 - #57610 (Fix nested `?` matchers)
 - #57634 (Remove an unused function argument)
 - #57635 (use structured macro and path resolve suggestions)
 - #57636 (Fix sources sidebar not showing up)
 - #57646 (Fixes text becoming invisible when element targetted)
 - #57650 (librustc_metadata: Pass a default value when unwrapping a span)
 - #57654 (Add some links in std::fs.)
 - #57658 (Two HIR tweaks)
 - #57659 (Fix release manifest generation)
 - #57683 (Document Unpin in std::prelude documentation)
 - #57685 (Enhance `Pin` impl applicability for `PartialEq` and `PartialOrd`.)
 - #57698 (Fix typo bug in DepGraph::try_mark_green().)
 - #57720 (Fix suggestions given mulitple bad lifetimes)
 - #57725 (Use structured suggestion to surround struct literal with parenthesis)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Centril** [comment]
@mark-i-m The reasons why rollups fail are mainly a) timeouts b) travis being silly, c) something actually going wrong in PRs... I think rollups often fail due to a & b as any other PR does. When c) happens, the goal is to isolate the offending PR and `r-` it; it would have failed anyways when tested alone. When we do have 41 queued PRs, I think it pays off a lot if you can cut the queue size in half by merging 21 PRs. Ideally, we wouldn't have 41 queued PRs and I could use 5-7 PR rollups, but the queue size is too big atm.

**Comment by mark-i-m** [comment]
Would it reduce the likelihood of a failure to do many smaller rollups rather than one big one? On balance, if you bors r+ 5 times in a large rollup but only once in most small rollups then doing a two half-sized rollups would be more efficient, and it would be easier to isolate failures.

**Comment by Centril** [comment]
Sure, you'd reduce the risk but also the payoff. In this case there are also 17 PRs in the queue are in the "rollup" prio so people have indicated that these should be problem free to rollup together (tho that might not actualy be true...). I think the lionshare of the 5 times are actually CI failures so you'd probably need to r+ more times if you did smaller rollups.

**Comment by mark-i-m** [comment]
By CI failures you mean timeouts or other bizarre occurrences that have nothing to do with the code?

**Comment by Centril** [comment]
@mark-i-m Yeah basically timeouts, time travel, travis fuckups, etc.

**Pull request closed without merging**
