### PR TITLE
Prepare beta 1.51.0

### PR DESCRIPTION
**Pull request by emilyalbini**
cc @rust-lang/release 
r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Also needed to cherry-pick 483c1a83ca7 to make the build work. Will send a PR landing that commit on master in a bit.

@bors r+ p=1000 rollup=never

**Comment by pietroalbini** [comment]
Seems like rustfmt depends on an old version of `rustc-ap-rustc_arena`, which used the now-removed `array_value_iter` feature.

**Comment by Mark-Simulacrum** [comment]
Hm. cc @calebcartwright 

It looks like we'll probably want to either bump rustfmt or do some other fix, not really sure...

**Comment by ollie27** [comment]
Did you intend to apply this PR to the master branch?

**Comment by pietroalbini** [comment]
@ollie27 :sweat_smile: thanks!

**Comment by calebcartwright** [comment]
We've had a broken toolstate issue with rustfmt for a little while now (#81583)

Almost had it fixed (#81768) but then the auto publish crates got caught between the stabilization and subsequent reversion (#81727) of `int_bits_const` which forced us to restart the whole process. Halfway through that second round of updates

**Comment by Xanewok** [comment]
https://github.com/rust-lang/rust/pull/81768 has been merged and RLS/Rustfmt toolstate is green now.

**Comment by pietroalbini** [comment]
Thanks! Cherry-picked the following two PRs:

* update RLS and rustfmt #81768 (fixes the build)
*  bootstrap: Locate llvm-dwp based on llvm-config bindir #81955 (beta-accepted)

@bors r+ p=500 rollup=never

**Comment by Xanewok** [comment]
This is an instance of https://github.com/rust-lang/rust/pull/79132#issuecomment-729157204, which probably needs a https://github.com/rust-lang/rust/pull/79132/commits/7477867b01d5c59a5847633808088f1e53708f9e backport for now.

I'm sorry that RLS doesn't build on aarch64-pc-windows-msvc proper - this was somehow alleviated by https://github.com/rust-lang/rls/pull/1713 but not completely fixed - we ideally would upgrade to Tokio 1.0 (along with core jsonrpc-* deps) but that's not possible due to parity-tokio-ipc being blocked on https://github.com/NikVolf/parity-tokio-ipc/issues/30 (which is effectively blocked on Tokio design work in https://github.com/tokio-rs/tokio/issues/3118).

However, I believe the RLS should build (but not pass tests, as these unconditionally require Tokio) with `--no-default-features`: this disables (only) `ipc` feature, which allows RLS to spawn `rustc` as child processes rather than executing them all in-process. This offers considerable benefits when checking wide (package-wise) workspaces but ultimately is an optimization and should work correctly without it.

We might:
1) Try distributing RLS with `--no-default-features` on aarch64-pc-windows-msvc for the time being (without blocking the CI on RLS tests)
2) Backport the hack from https://github.com/rust-lang/rust/pull/79132/commits/7477867b01d5c59a5847633808088f1e53708f9e and wait for the Tokio named pipes design work to conclude in the meantime
3) Quickly write a hacky blocking IPC (sans Tokio) solution for named pipes, which I unfortunately don't have time for in the next couple of days

Solution no. 2 seems easiest and is proven to work (https://github.com/rust-lang/rust/pull/79132) but if we try going with solution no. 1, if we don't need to hack `dist.rs` much, then we might end up with working RLS for the aarch64-pc-windows-msvc target until we fix the `ipc` feature there.

**Comment by pietroalbini** [comment]
Backported 7477867b01d5c59a5847633808088f1e53708f9e.

@bors r+ p=500 rollup=never

**Pull request merged**
