### PR TITLE
Update libbacktrace

### PR DESCRIPTION
**Pull request by petrochenkov**
@dhuseby @semarie Please, confirm that all Rust-specific changes in the second commit are still required.
(It would be ideal to have an unpatched copy of libbacktrace straight from the gcc repo.)

Fixes https://github.com/rust-lang/rust/issues/28447

r? @alexcrichton

### CODE REVIEW

**Comment by dhuseby** [comment]
@petrochenkov those are still necessary since none of the Bitrig changes have been upstreamed.

I'm surprised about the OpenBSD shared library part of the patch. @semarie is that still necessary?

**Comment by petrochenkov** [comment]
Updated with a fix for https://github.com/rust-lang/rust/issues/28447

The reason was a pretty silly mistake in `pecoff.c`

4-byte length of COFF string table was read like this:
```
// uninitialized
size_t str_size;
// initialize str_size by copying 4 bytes from some localion
memcpy (&str_size, syms_view.data + syms_size, 4); 
```
After this initialization half of `str_size` could be filled with trash on 64-bit machines.

**Comment by alexcrichton** [comment]
@bors: r+ 55e2b7e1b4606ae0bc684293f011b7006d1f1258

Nifty! I wonder if we'll get better backtraces on GNU windows as a result then?

**Comment by petrochenkov** [comment]
@alexcrichton 
Yes, functions in backtraces have proper names instead of `<unknown>` after this fix.

**Comment by alexcrichton** [comment]
Nice!

**Comment by Diggsey** [comment]
If only it had been written in rust...

**Comment by ranma42** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69314

**Comment by petrochenkov** [comment]
@ranma42 
Thanks, I intended to submit the patch upstream, but I'm not familiar with the process.

**Pull request merged**
