### PR TITLE
Remove redundant code from copy-suggestions

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Follow up to #94375, just remove some code that is not necessary anymore. This may make the perf of such suggestions a little bit worse, but I don't think this is significant.

r? @estebank

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
well let's try it 

@bors try @rust-timer queue

**Comment by estebank** [comment]
r=me after rebasing

**Comment by WaffleLapkin** [comment]
Why rebase is required? I've already rebased to fix [the conflict](https://github.com/rust-lang/rust/pull/94698#issuecomment-1060855577) 4 days ago...

P.S. it seems like the rust-timer didn't run, because the queue got flushed

**Pull request merged**
