### PR TITLE
implement Error::source for Box<T: Error>

### LINKED ISSUE #61899: impl Error for Box lacks source() impl
the `Error` impl of `Box<T: Error>` does not include the `source` function, however it contains `cause`, causing different results when switching from `cause` to `source`.
A small code that demonstrates this is [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4678c4b076c5b710977ec2848a524350).

Solution: implement source() for `Box<T: Error>` by forwarding to `T::source()`

### PR DESCRIPTION
**Pull request by s3bk**
fixes https://github.com/rust-lang/rust/issues/61899

### CODE REVIEW

**Comment by Centril** [comment]
@s3bk Looks like you are closing the wrong issue in the description?

**Comment by Arnavion** [comment]
Should be https://github.com/rust-lang/rust/issues/61899

**Comment by s3bk** [comment]
@Centril, @Arnavion indeed. I had to fetch the rust repo locally to fix it. Slow connection, so it took a very long time…

**Comment by u32i64** [comment]
@s3bk I think you should remove the incorrect ~striked through~ issue reference, since it prevents GitHub from parsing the keywords to automatically close the correct issue when this PR is merged, because the issue number has to immediatly follow `fixes` (see [help.github.com/en/articles/closing-issues-using-keywords](https://help.github.com/en/articles/closing-issues-using-keywords)), and GitHub preserves edit history anyway.

**Comment by s3bk** [comment]
@u32i64 noted and fixed. Thanks!

**Pull request merged**
