### PR TITLE
Extend rust reference with section about subtyping and type coercions

### PR DESCRIPTION
**Pull request by lorenzb**
My main sources of information are [RFC401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md), the rust IRC channel, and a bunch of experiments to figure out what `rustc` currently supports.
Note that the RFC calls for some coercion behaviour that is not implemented yet (see #18469).
The documentation in this PR mostly covers current behaviour of rust and doesn't document the future behaviour. I haven't written about receiver expression coercion.

I would be happy to rewrite/adapt the PR according to feedback.

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks @lorenzb ! This looks fine to me, but I'd like @nikomatsakis to check it out too.

**Comment by nikomatsakis** [comment]
@bors rollup r+

Seems good, thanks.

**Comment by Manishearth** [comment]
Needs https://github.com/rust-lang/rust/commit/fd3b6ca508ed99004a11291ef1d2c64104102a41

**Pull request merged**
