### PR TITLE
hoedown: fix trigger of -Werror=misleading-indentation

### PR DESCRIPTION
**Pull request by intelfx**
See rust-lang/hoedown#6.

### CODE REVIEW

**Comment by intelfx** [comment]
Ah, assignment... Will it work from here?

r? @alexcrichton

**Comment by alexcrichton** [comment]
@bors: r+ 

Thanks!

**Comment by Manishearth** [comment]
Travis fails

**Comment by intelfx** [comment]
@Manishearth Travis fails, but it is not my fault. Take a look at the build log.

**Pull request merged**
