### PR TITLE
Add docs for intra-doc-links

### LINKED ISSUE #66000: Document intra-rustdoc links in the unstable book
https://github.com/rust-lang/rust/issues/43466

Also figure out where the docs belong when it stabilizes.

The implementation has diverged a bit from the original RFC (rust-lang/rfcs#1946). We should have some good docs on all the syntaxes supported.

cc @clarfon 

This issue has been assigned to @rcoh via [this comment](https://github.com/rust-lang/rust/issues/66000#issuecomment-605071840).

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes https://github.com/rust-lang/rust/issues/66000

Hmm, for some reason my push closed the previous PR

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks! r=me once the CI is happy.

**Review by pickfire — APPROVED** [review]

**Pull request merged**
