### PR TITLE
Rename AssociatedItems to AssocItems

### PR DESCRIPTION
**Pull request by 0xPoe**
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

Part of https://github.com/rust-lang/rust/issues/60163#issuecomment-605308641

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
@eddyb Could you please take a look? Thanks!

**Comment by hi-rustin** [comment]
Resolved conflicts.

Ready for review.

cc: @eddyb I don't know if this PR is still acceptable because it's been a long time.

**Comment by eddyb** [comment]
LGTM, r? @varkor

**Comment by hi-rustin** [comment]
The CI failed because: https://github.com/rust-lang/rust/pull/84394

**Pull request merged**
