### PR TITLE
Add support to intrinsics fallback body

### PR DESCRIPTION
**Pull request by celinval**
Before this fix, the call to `body()` would crash, since `has_body()` would return true, but we would try to retrieve the body of an intrinsic which is not allowed.

Instead, the `Instance::body()` function will now convert an Intrinsic into an Item before retrieving its body.

Note: I also changed how we monomorphize the instance body. Unfortunately, the call still ICE for some shims.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
> Unfortunately, the call still ICE for some shims.

do you have an example program that hits that ICE?

**Comment by celinval** [comment]
> > Unfortunately, the call still ICE for some shims.
> 
> do you have an example program that hits that ICE?

If you remove the if condition and run the ui-fulldeps/stable-mir suite, it will ICE in a few tests.

**Comment by oli-obk** [comment]
The problem was the anonymous constant in the array length, because without the `generic_const_exprs` feature gate, we don't give those anon consts any generics and instead rely on const eval and the rest of the compiler just handling anon consts whose body just returns a generic param

**Pull request merged**
