### PR TITLE
Update jemalloc to 4.0.0

### PR DESCRIPTION
**Pull request by alexcrichton**
Haven't updated jemalloc in awhile and they just released a new version, and
this also includes the upstream changes to support platforms like openbsd and
bitrig.

Follow up to #28173 which includes jemalloc (to debug on the windows builders)

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r=brson 5cbaf778b903f6d098fd36193d9c8e97f015c0ba

(carrying over r+ from #28173)

**Comment by brson** [comment]
@alexcrichton looks like spurious (but bad!) failure?

**Comment by alexcrichton** [comment]
I think this is legit, I'll try to investigate more when I get the chance.

**Comment by alexcrichton** [comment]
Unfortunately this looks like a legitimate crash, but I haven't had much luck tracking it down, so I'll just have to tackle this later :(

**Pull request closed without merging**
