### PR TITLE
[Perf experiment, do not merge] Run MIR-opt twice

### PR DESCRIPTION
**Pull request by simonvandel**
A quick experiment to see the performance characteristics of running MIR optimizations twice.
The test diffs are all over the place, since they are now showing the second round, not the first round of optimizations.

### CODE REVIEW

**Comment by klensy** [comment]
More interesting question: run mir opts until mir code stop changing.

**Comment by simonvandel** [comment]
ConstProp emits errors multiple times now. I'll probably just bless the tests now to get some perf results.

@klensy yeah, for sure. This was just an easy experiment to make that didn't require any tracking of when to stop. If this PR has any effect, a proper fixed-point iteration would be nicer.

**Comment by jackh726** [comment]
Bors try/perf doesn't need tests to build/run so

@bors try @rust-timer queue

**Comment by simonvandel** [comment]
Interpretation of the perf results:
The simple approach in this PR does not lead to any meaningful improvements. But the Opt builds show that time spent in LLVM is definitely reduced. So (unsurprisingly) there is room for some improvements in the ordering/iteration counts of the MIR-opt passes.

Closing the experiment.

**Pull request closed without merging**
