### PR TITLE
Properly handle ranges of signed enums using both extremums (fixes #49973)

### LINKED ISSUE #49973: Incorrect niche filling if enum contains both i32 min and i32 max variants
```rust
#![allow(dead_code)]

#[derive(Debug)]
#[repr(i32)]
enum E {
    Min = -2147483648i32,
    Max = 2147483647i32,
}

fn main() {
    println!("{:?}", Some(E::Min));
}
```

Rust 1.23.0 correctly prints `Some(Min)`. Rust 1.24.0 incorrectly prints `None`.

Mentioning @eddyb because this sounds potentially relevant to #45225 or follow-on optimization.

(Discovered by @udoprog in #rust.)

### PR DESCRIPTION
**Pull request by nox**
Fixes #49973.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Please add an assertion that `size_of::<Option<E>>() == size_of::<E>()`. I have not read the code but the use of `valid_range: min..=max` makes me slightly concerned that this may not be the case.

Or if that is too complicated to handle in this PR, please file an issue to follow up.

**Comment by nox** [comment]
> Please add an assertion that `size_of::<Option<E>>() == size_of::<E>()`. I have not read the code but the use of `valid_range: min..=max` makes me slightly concerned that this may not be the case.

It is indeed not the case, which is why I didn't put a test for that. It's a known issue, though, there is a todo and whatnot in the code that some enums' valid ranges are larger than necessary. I'll file an actual issue on GH linking to it.

**Comment by dtolnay** [comment]
Sounds good, thanks.

**Comment by eddyb** [comment]
@bors r+

Do we want to backport this?

**Comment by eddyb** [comment]
cc @rust-lang/compiler Regarding backporting (https://github.com/rust-lang/rust/pull/49981#issuecomment-382033654)

**Pull request merged**
