### PR TITLE
Move rustbook to its own workspace.

### PR DESCRIPTION
**Pull request by ehuss**
This moves rustbook (the wrapper around mdbook) to its own Cargo workspace. This is done for two reasons:

- Some users want to avoid having to check out documentation submodules if they are not working on documentation. These submodules are required for submodules that have Cargo dependencies in the tree (such as mdbook preprocessors).
- The [pinned `memchr`](https://github.com/rust-lang/rust/blob/eb72697e41b00e5d8723f14c64a969d59d9b9474/compiler/rustc_ast/Cargo.toml#L10) is causing problems with updating. That pin is only necessary for the standard library, but unfortunately it is affecting all other crates.

This will have some drawbacks:

- A slight increase in the vendor directory size. My measurement shows about a 14M increase (0.7%), but somehow the compressed filesize is smaller.
- The dependencies for rustbook now need to be managed separately. I have updated the cron job to try to mitigate this.
- There will be a slight dist build time penalty. I'm not sure what it will be, since it heavily depends on the machine, but I suspect in the 30-45s range.
- Adds more complexity to things like bootstrap and tidy.

There are a few other alternatives considered:

- Publish preprocessors on crates.io. This adds the burden of publishing every change, and ensuring those publishes happen and the sources don't get out of sync, and somehow syncing those updates back to rust-lang/rust during the automatic updates. This is also more work.
- Move the submodules to subtrees. These have the added burden of doing updates in a way that is more difficult than submodules. I believe it also causes problems with GitHub's `#NNNN` tagging and closing issues. This is also more work.

The only thing I haven't tested here is the cron job. However, there's a pretty decent chance this won't pass CI, or that I missed something.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me

**Comment by ehuss** [comment]
Thanks for the review. Not sure if you wanted to wait for something instead of issuing the approval directly? Regardless, I think this should be ready.

@bors r=Mark-Simulacrum rollup=never

**Comment by ehuss** [comment]
@bors p=1

This is blocking some reference changes.

**Comment by compiler-errors** [comment]
Did this PR break tidy? I can't run tidy and this seems relevant:

```
thread 'deps (.)' panicked at src/tools/tidy/src/deps.rs:557:24:
cmd.exec() failed with `cargo metadata` exited with an error: error: failed to load manifest for dependency `mdbook-trpl-listing`

Caused by:
  failed to read `/home/michael/programming/rust2/src/doc/book/packages/mdbook-trpl-listing/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

stack backtrace:
   0: rust_begin_unwind
             at /rustc/75ac3b6331873133c4f7a10f2252afd6f3906c6a/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/75ac3b6331873133c4f7a10f2252afd6f3906c6a/library/core/src/panicking.rs:72:14
   2: check
             at ./src/tools/tidy/src/lib.rs:32:23
   3: {closure#1}
             at ./src/tools/tidy/src/main.rs:87:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src/tools/tidy/src/main.rs:61:49:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

Because my `src/doc/book` submodule is empty... 🤔

**Comment by ehuss** [comment]
Yea, I'll post a PR.

**Pull request merged**
