### PR TITLE
Emit crate disambiguators in save-analysis data

### PR DESCRIPTION
**Pull request by Xanewok**
Needed for https://github.com/nrc/rls-analysis/issues/93.
Blocked by https://github.com/nrc/rls-data/pull/11. (For now, this pulls my branch [rls-data/crate-source](https://github.com/Xanewok/rls-data/tree/crate-source))

This will allow to disambiguate different crates types/versions when indexing resulting save-analysis data (most importantly allow to support bin+lib and different crate versions).

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
r+ once the rls-data PR lands and using the new rls-data version.

**Comment by Xanewok** [comment]
Resolved conflict and updated version using rls-data 0.12

**Comment by kennytm** [comment]
@Xanewok Is this PR still [WIP], or is it ready to be merged? 🙂

**Comment by Xanewok** [comment]
@kennytm it's ready!
@nrc in these cases should I do something like r=nrc with bors?

**Comment by Xanewok** [comment]
@nrc this failed on compiling rls (rls-data mismatch).
The rls needs to pull new rls-data 0.12, but with that it needs also the updated rls-analysis (PR pending https://github.com/nrc/rls-analysis/pull/106).
I pushed a branch upstream with a patch for rls: https://github.com/rust-lang-nursery/rls/tree/multiple-analysis, but that still has to pull my custom branch - not sure if rustbuild with `--frozen` will let me do that.

What should we do here to resolve this?

**Comment by Xanewok** [comment]
Updating rls submodule to [rust-45468](https://github.com/rust-lang-nursery/rls/tree/rust-45468) branch, so it can compile with these changes.

**Comment by Xanewok** [comment]
single test in rls failed:

```
failures:
---- server::test::test_use_root_uri stdout ----
	thread 'server::test::test_use_root_uri' panicked at 'Could not convert URI to path: ()', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    server::test::test_use_root_uri
test result: FAILED. 27 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '--bin rls'
```

**Comment by Xanewok** [comment]
`arm-android` CI build hung up on `libstd` test:
```
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by kennytm** [comment]
@bors retry #43283

```
[01:28:23] test process::tests::test_process_output_fail_to_start has been running for over 60 seconds


No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Pull request merged**
