### PR TITLE
Implement `use<>` formatting in rustfmt

### PR DESCRIPTION
**Pull request by compiler-errors**
This PR implements formatting for precise-capturing `use<>` syntax as proposed in https://github.com/rust-lang/rust/pull/126753.

The syntax is implemented as-if the `use<>` bound were a trait bound but with the `use` keyword as its path segment identifier.

I opted to develop this in the rust-lang/rust tree since I'm not certain when the next rustfmt subtree sync is going to be, and I'd rather not block landing nightly support for `use<>` on something I have no control over. If @rust-lang/rustfmt would rather I move this PR over to that repository, then I would at least like to know when the next rustfmt->rust subtree sync is going to be, since stabilizing `precise_capturing` without formatting will be disruptive.

This implementation is otherwise rather straightforward.

Tracking:

- https://github.com/rust-lang/rust/issues/123432

### CODE REVIEW

**Comment by compiler-errors** [comment]
CI failure looks unrelated.

**Comment by calebcartwright** [comment]
>  then I would at least like to know when the next rustfmt->rust subtree sync is going to be, since stabilizing precise_capturing without formatting will be disruptive.

Anticipating tomorrow (June 21st), depending on how the [topic discussed in zulip shakes out](https://rust-lang.zulipchat.com/#narrow/stream/357797-t-rustfmt/topic/new.20syntax.20support) timing wise

if this needs to land first that's fine, but may knock the sync back by a couple hours/days if this lands first (git subtree can be very fussy)

**Review by calebcartwright — APPROVED** [review]
lgtm and npm ci issues seem highly unrelated indeed :laughing:

feel free to r=me if this needs to get in before the sync, though even if the implementation goes ahead in this repo it would be nice if we could have bors land the subtree sync PR first and then this after, as we can't rebase on syncs

**Comment by compiler-errors** [comment]
I'll wait until after the next rustfmt->rust subtree sync, then land this PR on rust. I'm happy to wait a few days -- there's not that much urgency here.

Then this PR can get merged back into rustfmt's repo at your own pace with the next rust->rustfmt subtree sync. Don't want to cause any pains around this next subtree sync.

**Comment by compiler-errors** [comment]
OK this is ready and looks like the merge went through (https://github.com/rust-lang/rust/pull/126842).

@bors r=calebcartwright

**Pull request merged**
