### PR TITLE
Add rustc-guide as a submodule

### PR DESCRIPTION
**Pull request by mark-i-m**
Adding this as a submodule will allow two things:
- Linking to the guide from doc.rlo
- Doing a link check as part of the rust CI build

Key question: Do we want to wait for the book to be filled out more? e.g. do we ever want to move it out of the nursery?

r? @nikomatsakis 

cc @steveklabnik

### CODE REVIEW

**Comment by mark-i-m** [comment]
cc #56079

**Comment by mark-i-m** [comment]
CI is complaining that some lines are longer than 100 chars.... should I change tidy to not check this module? After all, we already run our own CI...

**Comment by steveklabnik** [comment]
>  should I change tidy to not check this module?

Generally, the book should be fixed, not make exceptions in tidy. That said, this one might be okay, as it's for a shell script, not for the contents itself.

> e.g. do we ever want to move it out of the nursery?

The nursery [is on its way out](https://internals.rust-lang.org/t/end-of-days-for-the-rust-lang-nursery/8750), so this will happen regardless.

**Comment by mark-i-m** [comment]
> Generally, the book should be fixed, not make exceptions in tidy.

The only lines longer than 100 characters are links and the script... does today currently account for this?

> That said, this one might be okay, as it's for a shell script, not for the contents itself.

Lol. Ironically, it is the script we use to check that lines are <=100 chars :P

> The nursery is on its way out, so this will happen regardless.

So we should wait or no?

**Comment by mark-i-m** [comment]
It looks like tidy is now passing :)

**Comment by nikomatsakis** [comment]
@mark-i-m I'm game to land this, but it's also fine to move the rustc-guide to rust-lang sooner rather than later I imagine. Github actually does a good job keeping links. Do you want me to do that move?

**Comment by mark-i-m** [comment]
@nikomatsakis That would be great :)

**Comment by mark-i-m** [comment]
Would Travis need to be updated too?

**Comment by nikomatsakis** [comment]
@mark-i-m done (e.g., rendered content is now at <https://rust-lang.github.io/rustc-guide/>) -- there are perhaps some links that need to be updated for this/

Regarding travis, I don't know what update you are contemplating.

**Comment by nikomatsakis** [comment]
PS @mark-i-m I invited you to be an admin, you may wish to confirm at [this page](https://github.com/rust-lang/rustc-guide/invitations)

**Comment by mark-i-m** [comment]
>  there are perhaps some links that need to be updated for this?

Yep, I will open a PR for that.

> Regarding travis, I don't know what update you are contemplating.

Mostly I'm wondering if we need to re-setup CI.

> PS @mark-i-m I invited you to be an admin, you may wish to confirm at this page

Thank you :smile:

**Comment by mark-i-m** [comment]
Ok, I updated the submodule path in this PR. I can open issues on the rustc-guide repo if we come across problems.

**Comment by nrc** [comment]
> Mostly I'm wondering if we need to re-setup CI.

Yes, you will need to do this.

I have created a redirect for the Pages site.

**Comment by nikomatsakis** [comment]
Travis seems to be re-enabled: 

https://travis-ci.org/rust-lang/rustc-guide

Not sure what that error is about though, perhaps relevant.

**Comment by mark-i-m** [comment]
Opened #56257

There is also a link in the reference that needs to be updated, but I have to go now...

**Comment by mark-i-m** [comment]
> Not sure what that error is about though, perhaps relevant.

It looks like there was a non-relative link somewhere...

**Comment by mark-i-m** [comment]
https://github.com/rust-lang/rustc-guide/pull/242

**Comment by mark-i-m** [comment]
@nikomatsakis I think this should be ready now. The guide CI is passing again, and I opened #56257 to fix links in this repo.

**Comment by nikomatsakis** [comment]
one question for the @rust-lang/infra team -- I know that in the buildup to a release, we prevent breaking tools. Presumably that policy is per-submodule, and would not apply here?

**Comment by steveklabnik** [comment]
It's not really what's ultimately intended, but it's easy enough to add after.

**Comment by mark-i-m** [comment]
There end goal will be to do some link checking with something like toolstate... but for now, just adding it is a good step.

**Pull request merged**
