### PR TITLE
tidy: Accept CC0-1.0 license

### PR DESCRIPTION
**Pull request by mati865**
It's very permissive license.

CC https://github.com/rust-lang/rust/pull/58337

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Cc @rust-lang/core

I don't personally know enough to approve this, will bring up at core team triage next week.

**Comment by carols10cents** [comment]
Are there currently dependencies that are licensed CC0 that we would like to use? If not, I would prefer not to add this until we have a specific example.

**Comment by mati865** [comment]
@carols10cents Rustfmt depends on `dirs` now and it indirectly pulls `constant_time_eq` with `CC0-1.0` license: https://github.com/rust-lang/rust/pull/58337#issuecomment-463708928

I can add `constant_time_eq` to exceptions but CC0 is compatible with most of open source licenses so I thought it'd be better to permit whole license.

**Comment by flip1995** [comment]
A fast decision would be great here, since it currently blocks a tool update, not only for rustfmt, but also for RLS and Clippy.

**Comment by mati865** [comment]
Given how much time it's going to take I'm leaning towards adding `constant_time_eq` to the exceptions.

@flip1995 I'll close this PR once you do it in #58337

**Comment by mati865** [comment]
Closing in favour of https://github.com/rust-lang/rust/pull/58337#issuecomment-464398019

Sorry for the noise. Could somebody review https://github.com/rust-lang/rust/pull/58337?

**Pull request closed without merging**
