### PR TITLE
fixes #28696

### LINKED ISSUE #28696: rustdoc searching doesn't clear list of results when X is pressed
When you search for something on the online docs (which I assume are generated using cargo doc) a list of results comes up. When you clear the search bar/press the X button it probably should clear the results to allow you to view the original page. Anyone know how to fix this?

### PR DESCRIPTION
**Pull request by marti1125**
Return to the default content when .search-input is empty
- Add a validation when input search is empty on top of "startSearch()"

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like the tabbing/indentation may have gotten a little off though?

**Comment by marti1125** [comment]
@alexcrichton I removed the spaces...

**Comment by alexcrichton** [comment]
Looks like the indentation is still off? (e.g. looking at "Files Changed" here)

It looks like (according to `make tidy` on travis) that you're using tab characters instead of spaces.

**Comment by marti1125** [comment]
@alexcrichton  sry problem with my repo...

**Pull request closed without merging**
