### PR TITLE
Add LLVM FunctionPass regression test using run-make.

### PR DESCRIPTION
**Pull request by frewsxcv**
Part of https://github.com/rust-lang/rust/issues/31185.

Similar to https://github.com/rust-lang/rust/pull/31391.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could this just get folded into the existing test? Would help deduplicate among them

**Comment by frewsxcv** [comment]
@alexcrichton Good idea! Latest force push has them merged into one rmake test

**Comment by Manishearth** [comment]
This may have cause the failure [here](http://buildbot.rust-lang.org/builders/auto-win-msvc-64-opt/builds/3103)

**Comment by frewsxcv** [comment]
My guess is that https://github.com/rust-lang/rust/pull/31672 is the problematic one here, but I'm not entirely sure why...

**Pull request merged**
