### PR TITLE
Rename `-Zparse-only`

### PR DESCRIPTION
**Pull request by nnethercote**
It's a misleading name.

r? @estebank

### CODE REVIEW

**Comment by nnethercote** [comment]
Individual commits have more details. Additional discussion [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/.60-Zparse-only.60).

**Comment by dev-ardi** [comment]
Is there a flag that actually does only the parsing (and the macro expansion)?

**Comment by nnethercote** [comment]
> Is there a flag that actually does only the parsing (and the macro expansion)?

`-Zno-analysis` does only parsing, macro expansion, and name resolution. So no type checking, borrow checking, codegen, etc.

**Pull request merged**
