### PR TITLE
Refactor borrowck liveness values

### PR DESCRIPTION
**Pull request by lqd**
This PR starts cleaning up `rustc_borrowck`, in particular around liveness values:
- refactors simple names that make no sense anymore: either referring to older structures using region elements, or to bitset containers and values.
- improves comments and fixes others
- removes unused return values and unneeded generic arguments

r? @matthewjasper

### CODE REVIEW

**Comment by cjgillot** [comment]
I'm trying to factor this type out in https://github.com/rust-lang/rust/pull/115291. This would require undoing part of this PR.

**Comment by lqd** [comment]
@cjgillot I'm not sure that it would:

Moving `RegionValueElements` and `PointIndex` looks good, but the borrowck and dest-prop use `LivenessValues` in different ways in #115291. The former depends on pretty printing that "shouldn't" be moved out. And I'm also looking into storing the live loans there (because various parts of the borrowck are actually pushing liveness data, and need to be updated to compute the live loans. This causes scope differences between NLLs and polonius and needs to be fixed) which is not something of interest for dest prop.

The common thing between the two is just a `SparseIntervalMatrix<N, PointIndex>` with some `Location` mapping, and as far as I can tell only the `contains` function in today's `LivenessValues` is used in dest prop. We could uplift such a point index matrix and use it in both `rustc_borrowck` and dest prop, it's not clear it'd be a huge improvement but why not. Similar results would probably be achieved by having a dataflow visitor that does the mapping to points, or a function converting `MaybeLiveLocals`'s results to a point index matrix, and so on, where `LivenessValues` itself wouldn't help.

Summary:
- I think most of the refactoring parts of #115291 should land, but not the `LivenessValues` move: `rustc_borrowck` doesn't need it (as-is it also breaks NLL MIR dumps), and dest prop does not use it more than a point matrix. It also causes suboptimal naming like `LiveValues<Local>` with `union_regions`.
- I think this PR should land: it doesn't impact your dest prop plans, and neither do the possible changes `rustc_borrowck` could need it.
- we could uplift the small data structure shared between borrowck and dest prop

**Review by jackh726 — APPROVED** [review]
LGTM, r=me if you'd like

**Comment by lqd** [comment]
Thanks Jack! I'd first like to give @cjgillot some time for his thoughts on my last comment.

**Pull request merged**
