### PR TITLE
Add missing Eq implementations

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #36301.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
r? @pnkfelix 
cc @alexcrichton

**Comment by brson** [comment]
The things here that are not part of a public interface don't need `Eq`. Just creates more work for the compiler. Looks like fmt::num, dec2flt::FloatErrorKind, flt2dec, IntErrorKind, liblog (though this should be fixed upstream), SafeHash,  path::State, pipe::State, are in that category.

**Comment by GuillaumeGomez** [comment]
I'll remove thos Eq impl then.

**Comment by GuillaumeGomez** [comment]
Updated.

**Pull request merged**
