### PR TITLE
Make more traits of the From/Into family diagnostic items

### PR DESCRIPTION
**Pull request by flip1995**
Following traits are now diagnostic items:
- `From` (unchanged)
- `Into`
- `TryFrom`
- `TryInto`

This also adds symbols for those items:
- `into_trait`
- `try_from_trait`
- `try_into_trait`

Related: https://github.com/rust-lang/rust-clippy/pull/6620#discussion_r562482587

### CODE REVIEW

**Comment by flip1995** [comment]
CI failure seems unrelated? At least I can't think of a reason, why adding symbols and `rustc_diagnostic_item`s produces a failure in `src/cargo`.

**Comment by matthewjasper** [comment]
cc #81378

**Comment by matthewjasper** [comment]
Tree is closed so I'll @bors r+ for when it reopens

**Pull request merged**
