### PR TITLE
Remove the trait selection impl in method::probe

### PR DESCRIPTION
**Pull request by arielb1**
This removes the hacky trait selection reimplementation in `method::probe`, which occasionally comes and causes problems.

There are 2 issues I've found with this approach:
1. The older implementation sometimes had a "guess" type from an impl, which allowed subtyping to work. This is why I needed to make a change in `libtest`: there's an `impl<A> Clone for fn(A)` and we're calling `<for<'a> fn(&'a T) as Clone>::clone`. The older implementation would do a subtyping between the impl type and the trait type, so it would do the check for `<fn(A) as Clone>::clone`, and confirmation would continue with the subtyping. The newer implementation directly passes `<for<'a> fn(&'a T) as Clone>::clone` to selection, which fails. I'm not sure how big of a problem that would be in reality, especially after #43690 would remove the `Clone` problem, but I still want a crater run to avoid breaking the world.
2. The older implementation "looked into" impls to display error messages. I'm not sure that's an advantage - it looked exactly 1 level deep.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
LGTM (modulo how it fares in the wild, which is yet to be seen) r? @nikomatsakis

**Comment by eddyb** [comment]
cc @rust-lang/infra Cargobomb requested.

**Comment by arielb1** [comment]
I think I'm comfortable with landing this refactor the way it is, provided crater agrees.

**Comment by aidanhs** [comment]
Cargobomb run has started.

**Comment by nikomatsakis** [comment]
I read over the changes and r=me once we see the cargobomb results.

**Comment by aidanhs** [comment]
Cargobomb results - http://cargobomb-reports.s3.amazonaws.com/pr-43880/index.html

**Comment by arielb1** [comment]
```
ai-0.1.0 test-pass test-fail - flaky
ceramic-0.3.0 test-pass test-fail - looks dubious?
hashconsing-0.3.0 test-pass test-fail - flaky
idna-0.1.4 test-pass test-fail - clone of libtest
ldap3-0.5.0 test-fail build-fail - interesting
nss-sys-0.1.9 test-pass test-fail - "error: An unknown error occurred"?
parking_lot_mpsc-0.1.5-alpha.1 test-pass test-fail - looks flaky?
rustc-test-0.1.5 test-pass build-fail - clone of libtest
rustc-test-0.2.0 test-pass build-fail - clone of libtest
yggie.mach.b1c15026e0f31117d0d54ee6eeaeadd3e94a3d92 test-pass test-fail
   - [quickcheck] TEST FAILED (runtime error). Arguments: (UnitVec3D(Vec3D { x: -0.08164979, y: 0.41588578, z: -0.905744 }), UnitQuat(Quat { r: -0.9998616, i: 0.00013082517, j: -0.012743562, k: 0.010695696 }))
    - looks spurious
```

I think this has to depend on #43690 because that should fix the `(benchfn.clone())` problem.

**Comment by arielb1** [comment]
LDAP report:
```
Aug 19 09:54:47.599 INFO testing ldap3-0.5.0 against try#b96d5eea76e758bdd82fd4169eb4d5f7e3ce4fe2 for pr-43880
Aug 19 09:54:47.599 INFO running: cargo +b96d5eea76e758bdd82fd4169eb4d5f7e3ce4fe2 build --frozen
Aug 19 09:54:47.599 INFO creating container for: cargo +b96d5eea76e758bdd82fd4169eb4d5f7e3ce4fe2 build --frozen
Aug 19 09:54:47.599 INFO running `"docker" "create" "-v" "/home/ec2-user/cargobomb/./work/local/test-source/pr-43880/try#b96d5eea76e758bdd82fd4169eb4d5f7e3ce4fe2:/source:ro,Z" "-v" "/home/ec2-user/cargobomb/./work/local/target-dirs/pr-43880/try#b96d5eea76e758bdd82fd4169eb4d5f7e3ce4fe2:/target:rw,Z" "-v" "/home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro,Z" "-v" "/home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro,Z" "-e" "USER_ID=500" "-e" "CMD=cargo +b96d5eea76e758bdd82fd4169eb4d5f7e3ce4fe2 build --frozen" "cargobomb"`
Aug 19 09:54:47.673 INFO blam! 9fc7035ce68cfa6644c99cbc35ad850fd22cb7666409104c55eb40cfa186023c
Aug 19 09:54:47.674 INFO running `"docker" "start" "-a" "9fc7035ce68cfa6644c99cbc35ad850fd22cb7666409104c55eb40cfa186023c"`
Aug 19 09:54:48.186 INFO kablam!    Compiling ldap3 v0.5.0 (file:///source)
Aug 19 09:54:49.482 INFO kablam! error[E0308]: mismatched types
Aug 19 09:54:49.482 INFO kablam!    --> src/ldap.rs:235:42
Aug 19 09:54:49.482 INFO kablam!     |
Aug 19 09:54:49.482 INFO kablam! 235 |             let result = self.inner.call((req, Box::new(move |msgid| *closure_assigned_msgid.borrow_mut() = msgid))).select2(timeout).then(move |res| {
Aug 19 09:54:49.482 INFO kablam!     |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected trait std::ops::Fn, found closure
Aug 19 09:54:49.482 INFO kablam!     |
Aug 19 09:54:49.482 INFO kablam!     = note: expected type `(ldap::LdapOp, std::boxed::Box<std::ops::Fn(i32) + 'static>)`
Aug 19 09:54:49.483 INFO kablam!                found type `(ldap::LdapOp, std::boxed::Box<[closure@src/ldap.rs:235:57: 235:114 closure_assigned_msgid:_]>)`
Aug 19 09:54:49.483 INFO kablam! 
Aug 19 09:54:49.489 INFO kablam! error[E0308]: mismatched types
Aug 19 09:54:49.489 INFO kablam!    --> src/ldap.rs:259:38
Aug 19 09:54:49.489 INFO kablam!     |
Aug 19 09:54:49.489 INFO kablam! 259 |             Box::new(self.inner.call((req, Box::new(|_msgid| ()))).and_then(|(tag, vec)| Ok(LdapResponse(tag, vec))))
Aug 19 09:54:49.489 INFO kablam!     |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected trait std::ops::Fn, found closure
Aug 19 09:54:49.489 INFO kablam!     |
Aug 19 09:54:49.489 INFO kablam!     = note: expected type `(ldap::LdapOp, std::boxed::Box<std::ops::Fn(i32) + 'static>)`
Aug 19 09:54:49.489 INFO kablam!                found type `(ldap::LdapOp, std::boxed::Box<[closure@src/ldap.rs:259:53: 259:64]>)`
Aug 19 09:54:49.489 INFO kablam! 
Aug 19 09:54:49.770 INFO kablam! error: aborting due to 2 previous errors
Aug 19 09:54:49.770 INFO kablam! 
Aug 19 09:54:49.793 INFO kablam! error: Could not compile `ldap3`.
Aug 19 09:54:49.793 INFO kablam! 
Aug 19 09:54:49.793 INFO kablam! To learn more, run the command again with --verbose.
Aug 19 09:54:49.796 INFO kablam! su: No module specific data is present
Aug 19 09:54:50.119 INFO running `"docker" "rm" "-f" "9fc7035ce68cfa6644c99cbc35ad850fd22cb7666409104c55eb40cfa186023c"`
Aug 19 09:54:50.136 INFO blam! 9fc7035ce68cfa6644c99cbc35ad850fd22cb7666409104c55eb40cfa186023c
```

**Comment by arielb1** [comment]
Now that the `Clone` issue is fixed, I think we can land this.

**Comment by arielb1** [comment]
Waiting for @Zoxc's generator PR to avoid conflicting with them.

**Comment by arielb1** [comment]
Ready for review, assuming higher-ranked function pointers will still impl `Clone` this release.

**Comment by nikomatsakis** [comment]
@bors r+

> assuming higher-ranked function pointers will still impl Clone this release.

That part in particular doesn't seem to be controversial, I think...?

**Comment by arielb1** [comment]
> That part in particular doesn't seem to be controversial, I think...?

It can't be, given that they are already `Copy`

**Comment by SimonSapin** [comment]
This broke Servo. With have a fix (https://github.com/servo/servo/pull/18327), but this does reject real code that was previously accepted. This should at least be noted in release notes.

**Comment by nikomatsakis** [comment]
@SimonSapin Indeed -- I'm trying to figure out what is going on in that PR. Can you dump the struct definition on which the traceable derive was failing?

**Comment by nikomatsakis** [comment]
@SimonSapin I opened https://github.com/rust-lang/rust/issues/44224 to discuss and decide on a resolution. Thanks for the regression report!

**Pull request merged**
