### PR TITLE
Add compile fail test for SIMD

### PR DESCRIPTION
**Pull request by danobi**
This completes the missing SIMD test task for issue #39059.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Looks great, thanks!

**Comment by alexcrichton** [comment]
@bors: retry


* network error

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Comment by alexcrichton** [comment]
@danobi want to rebase this to r+ again?

**Comment by danobi** [comment]
Done

**Pull request merged**
