### PR TITLE
Stabilize cmpxchg16b_target_feature

### PR DESCRIPTION
**Pull request by Nugine**
Tracking issue for target features
+ #44839

stdarch issue
+ https://github.com/rust-lang/stdarch/issues/827

stdarch PR
+ https://github.com/rust-lang/stdarch/pull/1358

reference PR
+ https://github.com/rust-lang/reference/pull/1331

It's my first time contributing to rust-lang/rust. Please tell me if I missed something.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
LGTM, but will hand-off to someone from t-libs to double-check.

**Comment by Amanieu** [comment]
LGTM But I believe this needs T-lang signoff.

r? rust-lang/lang

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by joshtriplett** [comment]
@rfcbot cancel

**Comment by joshtriplett** [comment]
Starting a lang FCP:

@rfcbot merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by ehuss** [comment]
Can you send a PR to https://github.com/rust-lang/reference to update the list at https://github.com/rust-lang/reference/blob/master/src/attributes/codegen.md?plain=1#L77-L81 to include this new target feature?

**Comment by Nugine** [comment]
> Can you send a PR to https://github.com/rust-lang/reference to update the list at https://github.com/rust-lang/reference/blob/master/src/attributes/codegen.md?plain=1#L77-L81 to include this new target feature?

Sure. Filed just now.

**Comment by WaffleLapkin** [comment]
The FCP is completed, can this be merged now?

**Pull request merged**
