### PR TITLE
Add E0602

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #42229.

cc @Susurrus

### CODE REVIEW

**Comment by Susurrus** [comment]
So you're making the command-line lint and the lint attribute errors separate errors then? Is this formatting in line when rustc emits errors for other command-line arguments? I wouldn't expect error numbers for command-line parsing issues, just for code-related errors (like the lint attribute error).

**Comment by eddyb** [comment]
Hmm, saw @Susurrus' comment too late. @rust-lang/compiler any opinions?

**Comment by Susurrus** [comment]
You can `r-` I believe to stop bors.

**Comment by eddyb** [comment]
@Susurrus Fiiine. @bors r-

I'm just annoyed that I can't delete the @bors r+ because it re-triggers @bors in silly ways.

**Comment by eddyb** [comment]
Oh you have to be kidding me. @bors r-

**Comment by Susurrus** [comment]
LOL. Glad that got sorted (don't worry, I have email proof!) ✉️

**Comment by GuillaumeGomez** [comment]
Yep, I still need to add the "code lint" error code, but it seems more logical for me in order to make better error explanation.

**Comment by Susurrus** [comment]
Sure, adding more details wouldn't be a bad thing. I think it's unnecessary, but I don't think it'd hurt for users not very comfortable at the command line (and general argument syntax).

Two questions:
 * Would it make sense to specify the name of the invalid lint?
 * Would it make sense to list all *valid* lints? I'm thinking about helping the user fix the issue. If they aren't positive of all the valid lints, I don't even know where I could look that info up!

**Comment by GuillaumeGomez** [comment]
The lint name is given iirc. And I don't giving the full lint name is a good idea since it's getting quite long. ;)

**Comment by arielb1** [comment]
Adding levenshtein-based suggestions would be nice, but I think it's a little bit to much.

@bors r+

**Pull request merged**
