### PR TITLE
Serialize dependency graph directly from DepGraph

### PR DESCRIPTION
**Pull request by tgnottingham**
Reduce memory usage by serializing dep graph directly from `DepGraph`,
rather than copying it into `SerializedDepGraph` and serializing that.

### CODE REVIEW

**Comment by tgnottingham** [comment]
Hm, I think the try request was dropped, maybe because the regular CI checks hadn't passed yet.

@bors try @rust-timer queue

**Comment by michaelwoerister** [comment]
Thanks for the PR, @tgnottingham! This looks good to me in general. I'll review properly next week.

**Comment by michaelwoerister** [comment]
Thanks for the PR, @tgnottingham! This looks like a step in the right direction. 

One thing I noticed while reading the code was that quite a bit of this data could be mapped from disk into memory as is (at least on little endian platforms) and already provides random access (DepNodes and Fingerprints don't use leb128 because that would actually waste space). So in the future, we might want to just define a proper binary file format for the dep-graph and make decoding lazy -- or partially lazy, depending on whether we can afford the additional disk space for encoding edge indices with 4 bytes instead of using leb128.

Anyway, getting rid of the memory spike is the right thing to do in any case.

@bors r+

**Comment by tgnottingham** [comment]
Thanks @michaelwoerister!

> we might want to just define a proper binary file format for the dep-graph and make decoding lazy -- or partially lazy, depending on whether we can afford the additional disk space for encoding edge indices with 4 bytes instead of using leb128.

As a reference point, the style-servo-opt incr-full benchmark creates almost 16 million edges. The LEB128 encoding of the `u32` numbers 0 to that number of edges is ~58MB, and the raw encoding is ~60MB. I was really surprised to see that, but it checks out. The majority (~13 million) of those edges use 4 byte LEB128 encodings, so the savings aren't substantial.

This isn't representative of the actual edge data space requirements, but it suggests that raw-encoding might not be so bad.

**Comment by michaelwoerister** [comment]
It would be awesome if we added `-Zself-profile` events for tracking this kind of data (i.e. file sizes) and made perf.rlo show them. That would make experimenting with things like this more convenient.

**Pull request merged**
