### PR TITLE
Make declarative macro expansion a part of query system (cont. of #125356)

### PR DESCRIPTION
**Pull request by futile**
This is a continuation of the effort to make declarative macro expansion a part of the query system from #125356 by @SparrowLii.

#### Description from that PR:

> This is an attempt to make the macro expansion a part of incremental compilation.
> 
> Processing of procedural macros is difficult since they may involve interactions with the external environment. Declaring macros is a good start.
> 
> **It is not yet possible to test the effect of this PR on incremental compilation since the new query is declared as eval_always.**

#### Status of this PR:

* It is rebased against a much more recent `master` commit
* It contains the original commits from #125356 (in a rebased form)
* It adds the missing implementation for retrying macro matching that provides (better) error diagnostics
  * This was done by refactoring `rustc_expand::mbe::diagnostics::failed_to_match_macro()` to only require a `ParseSess` instead of an `ExtCtxt`. Otherwise, `ExtCtxt` would need to be in the interface of `TcxMacroExpander`, which is not possible, because `ExtCtxt` is part of `rustc_expand`, which depends on the crate that contains `TcxMacroExpander`, `rustc_middle`, and thus would introduce a circular dependency.
  * This refactoring moved the retrying down into the `impl TcxMacroExpander for MacroRulesMacroExpander` (this is just a change compared to the original PR, otherwise not important to know).
* This PR passes `./x test tests/ui`, which produced errors before that were all due to the missing implementation of retry macro matching.
* This PR does **not** yet contain changes for the open discussions from #125356. I wanted to fix the tests first before tackling them, and I also need to figure out what the best solutions for them are. I'd welcome any help/support with this, e.g., opening up a corresponding discussion on this PR with a summary/the final decided fix if available :)

In general, I'm new to working on rustc, so would be thankful for a bit more background/explanations in discussions and comments :) Thanks! :)

(tangentially relevant: #99515)

### CODE REVIEW

**Comment by futile** [comment]
Did a rebase, to no longer contain changes to submodules (wow rust is moving fast :see_no_evil:).

**Comment by futile** [comment]
r? @petrochenkov 

Since you reviewed and self-assigned the original PR, I thought this would be ok/maybe a better fit than auto-assignment.

Please feel free to re-/unassign if that's not the case!

**Comment by futile** [comment]
Oof, no idea where that error comes from, seems a dependency is broken/flaky? It's in stage0-checking, so can't be due to my changes yet I think? :O

**Comment by compiler-errors** [comment]
You need to revert the changes you've made to submodules in this PR.

**Comment by futile** [comment]
> You need to revert the changes you've made to submodules in this PR.

Thank you very much! Was a bit finicky, but I think it's correct now, the changes don't appear in the commit that had them anymore.

**Comment by petrochenkov** [comment]
I'm not sure what I should do with this PR.
Do you plan to work on merging this change instead of @SparrowLii, test whether it actually enables incremental reuse, and answer the questions from https://github.com/rust-lang/rust/pull/125356? Then we can close that PR.

If some changes are refactorings orthogonal to https://github.com/rust-lang/rust/pull/125356, then we can merge them in a separate PR before https://github.com/rust-lang/rust/pull/125356 instead of on top of it (feel free to assign me).

**Comment by petrochenkov** [comment]
Hmm, we can actually run benchmarks on this versions, since there are no CI failures anymore.
@bors try @rust-timer queue

**Comment by futile** [comment]
Thanks for taking a look!

> I'm not sure what I should do with this PR. Do you plan to work on merging this change instead of @SparrowLii, test whether it actually enables incremental reuse, and answer the questions from #125356? Then we can close that PR.

I do intend to finish this, and have already started testing whether this enables incremental reuse (see https://github.com/futile/rust/compare/expand1-cont...futile:rust:cache-decl-macros), and am also up to (try to) answer the questions from the other PR. (~~I think incremental reuse will have to wait for https://github.com/rust-lang/rust/pull/124141 though, more on that below.~~ Actually might have found a way, see below.)

However, I want to make sure that I'm not taking away @SparrowLii's work here, but I haven't heard back from them yet, so not sure what to do about that.

> If some changes are refactorings orthogonal to #125356, then we can merge them in a separate PR before #125356 instead of on top of it (feel free to assign me).

Maybe the changes in `rustc_expand::mbe::diagnostics`, see [here](https://github.com/rust-lang/rust/pull/128605/files#diff-f83f1c26036477fedbd5aec17f8e295d6a63b515b12c06ede9fa6d67936835e9)?

They make the module depend less on `ExtCtxt`, and instead use `ParseSess` and `DiagCtx` directly. I can't judge how useful that refactoring is outside the scope of this PR, or if it's actually going in the wrong direction. But that would be one thing I see.

---

So, on the topic of incremental reuse. This will, somewhat obviously, require also making the macro arguments, a `TokenStream`, part of the key used for the query/caching. Otherwise changed arguments will not trigger recompilation, and instead reuse the old macro expansion result, which is wrong.

However. This will require us to somehow hash the `TokenStream`, which _I thought_ was not (easily) possible, due to `Nonterminals` (which can contain parts of the AST). This was also discussed in the original PR: https://github.com/rust-lang/rust/pull/125356#discussion_r1615815054.

In practice this triggered this panic when compiling `core`: https://github.com/rust-lang/rust/blob/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_ast/src/token.rs#L1054-L1061

However! If I, instead, stable-hash the `flattened` `TokenStream`, using `TokenStream::flattened()`, it seems to actually JustWork™. Meaning, `./x test tests/incremental` passes. Wow, just stumbled on that, awesome. I'll probably open a draft PR for the version with incremental reuse, to get full CI.

That said, I'm not sure if it might make sense to wait for https://github.com/rust-lang/rust/pull/124141 here anyway, since that should (trivially) enable stable-hashing the `TokenStream`. But I can't judge if using `TokenStream::flattened()` instead is wrong/slow/suboptimal for other reasons/etc.

Also ty for the perf run, hope it'll go well! :)

**Comment by petrochenkov** [comment]
>Maybe the changes in rustc_expand::mbe::diagnostics, see [here](https://github.com/rust-lang/rust/pull/128605/files#diff-f83f1c26036477fedbd5aec17f8e295d6a63b515b12c06ede9fa6d67936835e9)?

Yes, from a brief look that's the part that can be split.

>However! If I, instead, stable-hash the flattened TokenStream, using TokenStream::flattened(), it seems to actually JustWork™.

Yes, the flattening should work in the meantime.

**Comment by futile** [comment]
Dang, but yeah, makes sense that it's a regression, since the path through the query system probably adds some overhead/instructions compared to the direct path. But ~1% on average is sadly a pretty hard hit :see_no_evil: 

Let's wait what the perf results for #128747 will be, but having these results is nice to have a baseline for the caching cost.

But given these regressions it probably doesn't make sense to merge this without actual re-use, either through #128747, or another approach, which also shows an actual performance benefit.

**Comment by SparrowLii** [comment]
@futile Thank you very much for your work. I can't spend much time on continuing the incremental compilation work for the time being due to some other work. Feel free to #125356 this if your work can replace it. (Notify me or @petrochenkov )

(I was waiting for #124141 to be finished. According to oli's [opinion](https://github.com/rust-lang/rust/pull/125356#discussion_r1615803108), using TokenStream as the query input parameter may be a better way.)

**Comment by petrochenkov** [comment]
I'll close this in favor of https://github.com/rust-lang/rust/pull/128747 to reduce the number of open PRs.
Landing any of this (*) is premature anyway until the whole system is ready and gives some perf benefits.

(*) Except for refactorings (https://github.com/rust-lang/rust/pull/128605/commits/6134b01d1c01ec726673c2c40c42b3694d465bf8, maybe something else).

**Pull request closed without merging**
