### PR TITLE
Sized fastpath

### PR DESCRIPTION
**Pull request by arielb1**
r? @eddyb 

The change to `trans::common::type_is_sized` is because we currently abort, rather than return random results, on overflow.

### CODE REVIEW

**Comment by eddyb** [comment]
AFAICT there is no chance of leakage of cached results that depend on the parameter environment, though there might be other gotchas I'm not aware of.
LGTM but I'd really have r? @nikomatsakis on this.

**Comment by arielb1** [comment]
I am using the same caching logic as before.

**Comment by eddyb** [comment]
You're totally right, my bad. @bors r+

**Comment by arielb1** [comment]
Performance numbers:
```
Before:
573.72user 4.49system 7:34.47elapsed 127%CPU (0avgtext+0avgdata 1166328maxresident)k

After:
581.72user 4.75system 7:42.74elapsed 126%CPU (0avgtext+0avgdata 1176224maxresident)k
```

**Comment by eddyb** [comment]
@arielb1 is that saying it took... longer? @bors r-

**Comment by arielb1** [comment]
I mixed them up

**Pull request merged**
