### PR TITLE
Cleanup formatting code

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This removes a few leftover positional enum variants that were no longer used.

All details that are changed are unstable (and `#[doc(hidden)]`), so this should
not impact downstream code.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Test failure here looks expected -- it looks like `fmt::Formatter` is now Send (and maybe Sync?). I'm not sure if it makes sense to drop that requirement by adding in a PhantomData or not.

**Comment by Mark-Simulacrum** [comment]
(This is indeed waiting for review; we need to decide whether the test failure is acceptable. I think it is).

@Amanieu also redirected a different formatting-related PR to @dtolnay, so r? @dtolnay on this one as well.

**Review by dtolnay — COMMENTED** [review]
The code change looks good to me. Thanks! This is great.

Regarding the test failure -- the expected failure that is no longer failing is:

https://github.com/rust-lang/rust/blob/6250d56355d72264ece721e8d0dc95b16a6824b1/src/test/ui/async-await/async-fn-nonsend.rs#L39-L45

I don't think your assessment that fmt::Formatter is now Send and maybe Sync is accurate, since it still contains a &mut dyn Write which is neither; https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e02471e6cddb6a31241f2089e714a8da. Could you dig a bit deeper to find out what change in this PR is affecting the test? I would prefer not to have an autotrait impl appear unintentionally that we might have trouble preserving down the line.

If the same error from the test case just got bumped to a later "phase" of errors from rustc for some reason, then that's fine and we can move forward.

**Comment by Mark-Simulacrum** [comment]
I will try to bisect or something like that (at least run the test locally and play around with it). I agree with your assessment that Send/Sync should not have been affected due to the continued presence of `&mut dyn Write`.

**Comment by Mark-Simulacrum** [comment]
Pushed up one more commit (as well as rebasing, though there were no conflicts) which fixes the test in question. Turns out there was just a "duplicate" error (both for Void and the dyn Write), with the first of those being gone.

This is ready for review again (I'm not sure if you meant to say r=me in your comment). r? @dtolnay

**Comment by dtolnay** [comment]
Nice, I'm glad it turned out to be something simple. @Mark-Simulacrum it could be worth adding `impl !Send for Formatter` so that user-facing error messages stop referring to its internals.

@bors r+

**Comment by Mark-Simulacrum** [comment]
(I wonder if it makes sense to change the async/await error messages to not "look into" external types by default -- I think there are cases where you'd want to, but generally speaking it seems like "`Formatter is not Send`" would be a better error message than "`dyn Write` is not Send".)

**Pull request merged**
