### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #128596 (stabilize const_fn_floating_point_arithmetic)
 - #129199 (make writes_through_immutable_pointer a hard error)
 - #129246 (Retroactively feature gate `ConstArgKind::Path`)
 - #129290 (Pin `cc` to 1.0.105)
 - #129323 (Implement `ptr::fn_addr_eq`)
 - #129500 (remove invalid `TyCompat` relation for effects)
 - #129501 (panicking: improve hint for Miri's RUST_BACKTRACE behavior)
 - #129505 (interpret: ImmTy: tighten sanity checks in offset logic)
 - #129510 (Fix `elided_named_lifetimes` in code)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=128596,129199,129246,129290,129323,129500,129501,129505,129510)

### CODE REVIEW

**Comment by tgross35** [comment]
@bors retry

https://github.com/rust-lang/rust/issues/127883

**Comment by tgross35** [comment]
Hey Bors did two in a row! 🎉

**Comment by pnkfelix** [comment]
Visiting for weekly rustc-perf triage

* primary regressions are solely to various incremental scenarios for the bitmaps crate
* PR #129513 and PR #129546 seem to have recovered much of the losses here... but after review, they are probably just masking the loss introduced by PR #129521
* opened [discussion in zulip](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/numeric.20precision.20in.20rustc-perf.20detailed.20results/near/466074054) about how to actually dig more deeply into regressions like this.
* nothing here seems like it should have impacted incr-comp, and this regression seems minor enough that it does not warrant deeper investigation
* marking as triaged

@rustbot label: +perf-regression-triaged

**Pull request merged**
