### PR TITLE
Upgrade hashbrown to 0.12.3

### PR DESCRIPTION
**Pull request by Amanieu**
This fixes a double-free in the `clone_from` function if dropping an existing element in the table panics. See https://github.com/rust-lang/hashbrown/pull/348 for more details.

The indexmap crate is also updated to use the latest hashbrown version.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me on the bump itself

We should consider a beta backport, too, I think.

Can you say more about the relnotes label? Just that it's a soundness fix?

**Comment by klensy** [comment]
#99251 related, as it removes hashbrown 0.11 version entirely.

**Comment by Amanieu** [comment]
Yes the relnotes was just for the soundness fix. It can be removed if it's not appropriate.

#99251 is likely going to conflict with this PR.

**Comment by Amanieu** [comment]
It might be easier to fold the version upgrade into https://github.com/rust-lang/rust/pull/99251. cc @cuviper

**Comment by cuviper** [comment]
> This fixes a double-free in the `clone_from` function if dropping an existing element in the table panics. See [rust-lang/hashbrown#348](https://github.com/rust-lang/hashbrown/pull/348) for more details.
> 
> The indexmap crate is also updated to use the latest hashbrown version.

FWIW, I think that bug is irrelevant to `indexmap`, since it only uses `RawTable<usize>`. I would have rather seen the perf numbers of the hashmap upgrade alone, especially since that affects `std`.

> It might be easier to fold the version upgrade into #99251.

I've added it.

Note that `rustc_codegen_cranelift` and `rust-analyzer` also use independent `Cargo.lock` files -- I took the liberty of updating it for cranelift as well, but we can't directly do that for `rust-analyzer` since it's a submodule. But as far as backports are concerned, 1.63-beta doesn't enable `rust-analyzer` yet anyway.

**Comment by Mark-Simulacrum** [comment]
Hm. I think it may make sense to re-target this to beta -- looks like doing that via github UI isn't going to work.

**Pull request closed without merging**
