### PR TITLE
legacy_directory_ownership -> hard error

### LINKED ISSUE #37872: `legacy_directory_ownership` future-compatibility warnings
This is the summary issue for the `legacy_directory_ownership` future-compatibility warning and other related errors. The goal of this page is describe why this change was made and how you can fix code that is affected by it. It also provides a place to ask questions or register a complaint if you feel the change should not be made.

#### What is the warning for?

The `legacy_directory_ownership` warning is issued when
 - there is a non-inline module with a `#[path]` attribute (e.g. `#[path = "foo.rs"] mod bar;`),
 - the module's file ("foo.rs" in the above example) is not named "mod.rs", and
 - the module's file contains a non-inline child module without a `#[path]` attribute.

The warning can be fixed by renaming the parent module to "mod.rs" and moving it into its own directory if appropriate.

We are making this a warning so that the directory ownership rules apply more consistently to modules with `#[path]` attributes. This is described in more detail in #37602.

#### When will this warning become a hard error?

At the beginning of each 6-week release cycle, the Rust compiler team will review the set of outstanding future compatibility warnings and nominate some of them for Final Comment Period. Toward the end of the cycle, we will review any comments and make a final determination whether to convert the warning into a hard error or remove it entirely.

#### Current status
- [x] https://github.com/rust-lang/rust/pull/37602 introduces the `legacy_directory_ownership` lint as warn-by-default
- [x] https://github.com/rust-lang/rust/pull/42894 makes the `legacy_directory_ownership` lint deny-by-default
- [ ] PR ? makes the `legacy_directory_ownership` lint a hard error

### PR DESCRIPTION
**Pull request by Centril**
Closes https://github.com/rust-lang/rust/issues/37872.

r? @petrochenkov

### CODE REVIEW

**Comment by ehuss** [comment]
Apologies for butting in, but I have some questions about this.
Is this code path even possible?  I can't find any UI tests, and I can't figure out a way to trigger it. It looks to have been mostly removed in #46531.  The original tests were further removed via #47298.

**Comment by Centril** [comment]
I have no idea; I was also surprised there were no tests... I guess crater will show if anyone uses it or not =)

**Comment by ehuss** [comment]
AFAICT, there are two places where `UnownedViaMod` can be created: [`submod_path`](https://github.com/rust-lang/rust/blob/a45743345659c775b01484574af2818c46a2cb03/src/libsyntax/parse/parser.rs#L6541) and [`InvocationCollector`](https://github.com/rust-lang/rust/blob/a45743345659c775b01484574af2818c46a2cb03/src/libsyntax/ext/expand.rs#L1116).  Both only seem to create it when there is a valid `#[path]` attribute with a value that fails to produce a `file_name()` or `to_str()`, both which shouldn't be possible AFAIK (that is, invalid unicode, or an empty string or root path, all which should fail in other ways).

**Comment by Centril** [comment]
Rolled up into https://github.com/rust-lang/rust/pull/63247.

**Pull request closed without merging**
