### PR TITLE
Extract collections benchmarks to libcollections/bench

### PR DESCRIPTION
**Pull request by phungleson**
Good suggestion from @stjepang https://github.com/rust-lang/rust/issues/39484#issuecomment-277467765

r? @alexcrichton

### CODE REVIEW

**Comment by stjepang** [comment]
Thanks for the PR!

Just two concerns with this:

1. Naming the subdirectory "bench" instead of "benches" is inconsistent with Cargo's naming conventions - Cargo uses "tests" and "benches" rather than "test" and "bench".
2. Why do libcollectionstest and libcoretest live in their own directories rather than libcollections/test and libcore/test? Isn't that another consistency: having tests in their own directories but benches in subdirectories?

@alexcrichton Thoughts?

**Comment by alexcrichton** [comment]
@stjepang yeah using `benches` and `tests` sounds good to me! The libcoretest/libcollectionstest are historical artifacts at this point (thank the makefiles), they can be moved whenever though now at this point!

**Comment by phungleson** [comment]
@alexcrichton @stjepang I have extracted to `libcollections/benches` and `libcore/benches`.

`libcollections/tests` and `libcore/tests` perhaps can be a PR after this.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
