### PR TITLE
Replace `state_for_location` with `DataflowResultsCursor`

### PR DESCRIPTION
**Pull request by ecstatic-morse**
These are two different ways of getting the same data from the result of a dataflow analysis. However, `state_for_location` goes quadratic if you try to call it for every statement in the body.

### CODE REVIEW

**Comment by pnkfelix** [comment]
This change looks good to me.

I had a brief desire to attempt to find out if any open PR's are using `state_for_location`, but I don't think Github makes it easy to do a search like that...?

**Comment by ecstatic-morse** [comment]
#64207 is exporting most of `dataflow` for use in `clippy`. I believe the author is currently using `state_for_location` but I can help them switch to `DataflowResultsCursor`. Apart from that, no other open PRs show up when searching for "dataflow".

**Comment by ecstatic-morse** [comment]
The author has already changed #64207 to use the cursor.

**Comment by tmandry** [comment]
This also looks good to me. r+'ing so we can get it together with #64207. 
@bors r+

**Pull request merged**
