### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #64747 (Stabilize `Option::flatten`)
 - #65664 (`std::panic::Location` is a lang_item, add `core::intrinsics::caller_location` (RFC 2091 3/N))
 - #65792 (rustc, rustc_passes: reduce deps on rustc_expand)
 - #65849 (librustc_lexer: Enhance documentation)
 - #65873 (doc: explain why it is unsafe to construct Vec<u8> from Vec<u16>)
 - #65880 (Gather together usefulness tests)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
This caused [gigantic compile-time regressions](https://github.com/rust-lang/rust/compare/95f437b3cfb2fec966d7eaf69d7c2e36f9c274d1...9285d401a6070094747465962bc49969b93e14c5) for incremental debug and opt builds, of 100s and 1000s of percent.

I suspect #65664 or #65792 is the cause. The other changes are all small. @anp, @Centril: any thoughts?

cc @rust-lang/wg-compiler-performance

**Comment by nnethercote** [comment]
Note that a bunch of codegen queries (e.g. `LLVM_module_codegen_emit_obj`) are now happening on those incremental runs, they weren't happening before.

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/65792 seems unlikely as it is just moving some stuff, not actually changing the implementation.

**Comment by michaelwoerister** [comment]
Just from the title #65664 looks like it could introduce a dependency of machine code or MIR to span information, which is always bad news for incremental compilation.

**Comment by eddyb** [comment]
It's #65664, see https://github.com/rust-lang/rust/pull/65664#issuecomment-547360997 for more details.

**Pull request merged**
