### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #117586 (Uplift the (new solver) canonicalizer into `rustc_next_trait_solver`)
 - #118502 (fix: correct the arg for 'suggest to use associated function syntax' diagnostic)
 - #118694 (Add instance evaluation and methods to read an allocation in StableMIR)
 - #118715 (privacy: visit trait def id of projections)
 - #118730 (recurse into refs when comparing tys for diagnostics)
 - #118736 (temporarily revert "ice on ambguity in mir typeck")

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=117586,118502,118694,118715,118730,118736)

### CODE REVIEW

**Comment by Kobzol** [comment]
Hmm, kind of hard to guess for me here what could be the culprit. Let's try something:

@rust-timer build bcb464fcc52084cac1943238fa2bf0415f8ff03b

**Comment by Kobzol** [comment]
Bingo. @davidtwco were these regressions expected?

**Comment by davidtwco** [comment]
> Bingo. @davidtwco were these regressions expected?

I wasn't expecting them but they make sense. We do a little bit more work after that PR because the reachable set is slightly bigger and that in turn means more MIR gets encoded and things like that.

**Comment by Kobzol** [comment]
Ok. Marking as triaged then.

@rustbot label: +perf-regression-triaged

**Pull request merged**
