### PR TITLE
Mention raw-ident syntax

### PR DESCRIPTION
**Pull request by mark-i-m**
According to https://github.com/rust-lang/rust/pull/56419#pullrequestreview-180542790

Blocked on #56419

r? @Centril

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors r-

Blocked on #56419.

**Comment by Centril** [comment]
@mark-i-m Can you fix this PR to just include the last commit?

**Comment by mark-i-m** [comment]
@Centril I assume you mean the last two? I rebased.

**Comment by Centril** [comment]
@mark-i-m yeah; thanks

@bors r+ rollup

**Pull request merged**
