### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
22 commits in 8eb8acbb116e7923ea2ce33a50109933ed5ab375..d2f6a048529eb8e9ebc55d793abd63456c98fac2
2023-10-17 11:55:04 +0000 to 2023-10-20 18:25:30 +0000
- chore(deps): bump rustix from 0.38.18 to 0.38.19 (rust-lang/cargo#12851)
- refactor: centralize logic of getting max resolve version (rust-lang/cargo#12860)
- If there's a version in the lock file only use that exact version (rust-lang/cargo#12772)
- Make the precise field of a source an Enum (rust-lang/cargo#12849)
- fix(cli): Provide next steps for bad -Z flag (rust-lang/cargo#12857)
- fix(remove): Preserve feature comments (rust-lang/cargo#12837)
- docs: fix typo (rust-lang/cargo#12844)
- chore(triagebot): auto label when PR review state changes (rust-lang/cargo#12856)
- fix(add): Preserve more comments (rust-lang/cargo#12838)
- ci: big ⚠️ to ensure the CNAME file is always there (rust-lang/cargo#12853)
- docs(cargo-bench): `--bench` is passed in unconditionally to bench harnesses (rust-lang/cargo#12850)
- docs(contrib): generate redirection HTML pages in CI (rust-lang/cargo#12846)
- docs: remove review capacity notice (rust-lang/cargo#12842)
- fix(help):Clarify install's positional (rust-lang/cargo#12841)
- Adjust `-Zcheck-cfg` for new rustc syntax and behavior (rust-lang/cargo#12845)
- fix(replace): Partial-version spec support (rust-lang/cargo#12806)
- Print environment variables for build script executions with `-vv` (rust-lang/cargo#12829)
- fix(cli): Suggest cargo-search on bad commands (rust-lang/cargo#12840)
- docs(contrib): Policy on manifest editing (rust-lang/cargo#12836)
- ci/contrib: use separate concurrency group (rust-lang/cargo#12835)
- ci/contrib: do not fail on missing gh-pages (rust-lang/cargo#12834)
- Clarify flag behavior in `cargo remove --help` (rust-lang/cargo#12823)

r? ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
https://github.com/rust-lang-ci/rust/actions/runs/6594570522/job/17918585736#step:24:32176

>   error: flag -Zcheck-cfg does not take a value, found: `names,values,output`

Looks like we need to cherry-pick #116983?

**Comment by Urgau** [comment]
Hum, sorry for this. It's seems that the `opt-tool` (the PGO/BOLT pipeline tool) is using "nightly" Cargo when running the (final) "Run tests" section and this somewhat obviously doesn't work as `bootstrap` isn't aware of the new Cargo.
I think this failure is expected as we should always be using beta Cargo for building Rust.

**Comment by lqd** [comment]
@bors retry yielding to #117018

this won’t land before opt-dist is fixed in https://github.com/rust-lang/rust/pull/117018 and both have the same prio

**Comment by lqd** [comment]
This wasn’t meant to be closed…

**Pull request merged**
