### PR TITLE
Use a small runner for msvc-ext2 job

### PR DESCRIPTION
**Pull request by ChrisDenton**
Hopefully this should eliminate the errors from this job. The only question is how long it takes.

try-job: x86_64-msvc-ext2

### CODE REVIEW

**Comment by ChrisDenton** [comment]
2h 25m 34s on that run. That seems roughly in line with the other long running job. I guess it's reviewers choice on if this is ok. According to @ehuss's tests, I think this should eliminate the error on this runner. And since the errors on other runners are now much less frequent, it should be a noticeable improvement to CI success rates.

**Comment by Mark-Simulacrum** [comment]
r=me if we still need this

**Comment by ChrisDenton** [comment]
Looks like this is still needed

@bors r=Mark-Simulacrum

**Pull request merged**
