### PR TITLE
Make ongoing_codegen a query

### PR DESCRIPTION
**Pull request by Zoxc**
Builds on https://github.com/rust-lang/rust/pull/59338.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
ping from triage @michaelwoerister waiting for your review on this

**Comment by Mark-Simulacrum** [comment]
Visiting from triage, I'm closing the series of PRs here other than the first one since they will likely only make progress sequentially and it doesn't help to have all of them open. For reference, this is https://github.com/rust-lang/rust/pull/59404, https://github.com/rust-lang/rust/pull/59338, https://github.com/rust-lang/rust/pull/59282, and https://github.com/rust-lang/rust/pull/59205 which are (in that order) blocked on each other and eventually https://github.com/rust-lang/rust/pull/59064.

Feel free to reopen as those PRs merge and/or make progress.

**Comment by hdhoang** [comment]
ping from triage @Zoxc, any update on this PR and its series?

**Comment by JohnCSimon** [comment]
Ping from triage again @michaelwoerister @Mark-Simulacrum this has sat idle for months. Can you please resolve the merge conflicts? 
Thank you!

**Comment by JohnCSimon** [comment]
@Zoxc @michaelwoerister @Mark-Simulacrum 
Unfortunately I'm going to have to close this PR. I'm not sure what else can be done with this.

**Pull request closed without merging**
