### PR TITLE
Remove `proc`  from the language

### PR DESCRIPTION
**Pull request by nikomatsakis**
They are replaced with unboxed closures.

cc @pcwalton @aturon 

This is a [breaking-change]. Mostly, uses of `proc()` simply need to be converted to `move||` (unboxed closures), but in some cases the adaptations required are more complex (particularly for library authors). A detailed write-up can be found here: http://smallcultfollowing.com/babysteps/blog/2014/11/26/purging-proc/

The commits are ordered to emphasize the more important changes, but are not truly standalone.

### CODE REVIEW

**Comment by zesterer** [comment]
'proc' is a very useful keyword to have, particularly when one is writing an operating system. I suggest that it should no longer be a reserved word given that it no longer has semantic meaning.

**Comment by nikomatsakis** [comment]
@zesterer I agree. Care to open a PR? I think all you have to do is to remove this line:

https://github.com/rust-lang/rust/blob/a04b88d1941644df01fa5e31dd43e0f57c13d938/src/libsyntax_pos/symbol.rs#L317

If you do, add `r? @nikomatsakis` into the PR description.

**Comment by zesterer** [comment]
I've never opened a Rust PR before. Have you any advice on how best to word things?

**Comment by tshepang** [comment]
I would...

> remove 'proc' from keyword list
>
> 'proc' is a very useful keyword to have, particularly when one is writing an operating system. It is removed from reserve keyword, given that it no longer has semantic meaning.

**Comment by nikomatsakis** [comment]
@zesterer do you mean to word the PR description? If so, what @tshepang wrote sounds fine. We're not too formal on these sorts of things. =)

**Pull request merged**
