### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #40501, #40524, #40636, #40739, #40756
- Failed merges:

### CODE REVIEW

**Comment by frewsxcv** [comment]
```
[00:51:19] error: unable to get packages from source
```

Uhhh spurious I guess?

@bors retry

**Comment by arielb1** [comment]
```

[00:55:24] error: unable to get packages from source
[00:55:24] 
[00:55:24] Caused by:
[00:55:24]   failed to parse manifest at `/cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.7/Cargo.toml`
[00:55:24] 
[00:55:24] Caused by:
[00:55:24]   could not parse input as TOML
[00:55:24] 
[00:55:24] Caused by:
[00:55:24]   expected newline, found an identifier at line 14
[00:55:24] thread 'main' panicked at 'tests failed for https://github.com/iron/iron', /checkout/src/tools/cargotest/main.rs:98
[00:55:24] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
I've classified both those failures under https://github.com/rust-lang/rust/issues/40474

**Pull request closed without merging**
