### PR TITLE
Add Windows-specific comments to testing guide

### LINKED ISSUE #27936: Improve book support for windows
https://doc.rust-lang.org/stable/book/testing.html could be improved by mentioning `echo %errorlevel%` for use in Windows. Perhaps an appendix for Windows?

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #27936

### CODE REVIEW

**Comment by retep998** [comment]
Don't forget to mention that `%ERRORLEVEL%` is only when you're inside `cmd`. Inside an msys environment you use the same thing like you'd use on linux and OS X. In powershell you use either `$LASTEXITCODE` or `$?` depending upon whether you want an exist code or just a bool respectively.

**Comment by steveklabnik** [comment]
@retep998 updated, what do you think?

**Comment by retep998** [comment]
It's better.

**Pull request merged**
