### PR TITLE
Update fingerprint tests macros

### PR DESCRIPTION
**Pull request by CrockAgile**
Part of #44924

r? @michaelwoerister

### CODE REVIEW

**Comment by CrockAgile** [comment]
Between these and the previous updates I contributed, I gained decent deduction skills as to which artifacts (HirBody/MirValidated/etc) should change in response to certain code changes. This indicates to me that the mentor tagging system is working 👍

I did encounter one issue which confused my intuition and sparked a bit of curiosity. `while_let_loops.rs` and `while_loops.rs` test a common case of changing a `continue`'s label, but the dirty fingerprints are different:

```rust
// while_let_loops.rs
#[cfg(cfail1)]
pub fn change_continue_label() {
    let mut _x = 0;
    'outer: while true {
        'inner: while true {
            _x = 1;
            continue 'inner;
        }
    }
}

#[cfg(not(cfail1))]
#[rustc_clean(cfg="cfail2", except="HirBody, MirValidated")]
#[rustc_clean(cfg="cfail3")]
pub fn change_continue_label() {
    let mut _x = 0;
    'outer: while true {
        'inner: while true {
            _x = 1;
            continue 'outer;
        }
    }
}

// while_let_loops.rs
#[cfg(cfail1)]
pub fn change_continue_label() {
    let mut _x = 0;
    'outer: while let Some(0u32) = None {
        'inner: while let Some(0u32) = None {
            _x = 1;
            continue 'inner;
        }
    }
}

#[cfg(not(cfail1))]
#[rustc_clean(cfg="cfail2", except="HirBody, MirValidated, MirOptimized, TypeckTables")]
#[rustc_clean(cfg="cfail3")]
pub fn change_continue_label() {
    let mut _x = 0;
    'outer: while let Some(0u32) = None {
        'inner: while let Some(0u32) = None {
            _x = 1;
            continue 'outer;
        }
    }
}
```

In the "while loop" case, only HirBody and MirValidated are dirty. It is a little strange that only MirValidated is dirty and not MirOptimized, but I assume this is because optimization gives identical whether `continue` to either label.

But if this is the case for "while loops", why is it not for "while let loops"? Instead, "while let loops" give a dirty MirOptimized as well as TypeckTables. This may not be important, but since it was the only bit of code which gave me unintuitive results I thought I should bring it up.

**Comment by michaelwoerister** [comment]
Wow, thanks a lot, @CrockAgile! I'll review as soon as I find the time.

> I did encounter one issue which confused my intuition and sparked a bit of curiosity.

That's curious indeed. However looking at the MIR on [play.rust-lang.org](https://play.rust-lang.org/?gist=d077b670ed902aa417a73060c4bf819d&version=stable), both versions *are* the same for the vanilla `while` case and we get a warning that it is an infinite loop. I suspect that some optimization pass merges the two loops. The code generated from `while let` is a lot more complicated an the optimization doesn't kick in.

**Comment by michaelwoerister** [comment]
Looks good to me. Thanks, @CrockAgile!

@bors r+

**Pull request merged**
