### PR TITLE
Attempt to make the android emulator use less CPU

### PR DESCRIPTION
**Pull request by aidanhs**
I was playing around locally and noticed constant ~90% cpu usage of one core and found http://stackoverflow.com/questions/7297585/android-emulator-uses-100-cpu-even-if-nothing-i-running-on-it. Maybe this is one reason why Android builds are so slow?

Since the queue is empty I've set `ALLOW_PR=1` for android so we can if my theory is correct and the PR build is actually faster. I'll remove it before this gets merged.

r? @alexcrichton

### CODE REVIEW

**Comment by aidanhs** [comment]
This made no noticeable difference :( Closing.

**Comment by alexcrichton** [comment]
Oh right now the emulator is started at the beginning b/c I assumed it'd be idle the whole time, but if it's burning so much cpu perhaps we could delay starting it until we actually needed it?

We've already got a defined location where we start the qemu emulators (before tests), so maybe we could spin up the android emulator at that location as well?

**Comment by aidanhs** [comment]
When I looked more carefully, it actually only burns about 10% CPU and, if you compare the compilation finish time to (say) musl, the difference is within normal variance, i.e. 10% CPU overhead isn't making much of a difference.

The massive slowdown with Android is the tests, which seem to be about 4x slower. So, taking your thought, maybe if we delay the emulator boot then we can start it up with beefier settings (more cores/ram) and see if that helps the tests. I'll have a think about this.

**Comment by alexcrichton** [comment]
Oh so one easy optimization with Android would be pipelining tests as well. Right now we execute with `RUST_TEST_THREADS=1` which slows things down even more. This means that while we've got extra cores we still only compile one test at a time.

We could pursue a different strategy perhaps, like the QEMU tests, where a server is run on the Android device which allows concurrent execution. That way we could compile in parallel but still test serially (if needed). 

I wonder if maybe we could just run the QEMU test server on the device... Support for gdb would likely need to be added but other than that it may work!

**Comment by aidanhs** [comment]
Ok that helps explain why android is so slow if we're only using one core. I'm not familiar with how the android tests are run, so I'll go away and have a look at it.

**Pull request closed without merging**
