### PR TITLE
Outline `format_args` construction in `{span_,}bug`

### PR DESCRIPTION
**Pull request by Noratrieb**
I was inspired by #107181 which shows that this can apparently be perf sensitive in some way.

### CODE REVIEW

**Comment by compiler-errors** [comment]
r=me if perf comes back good

**Comment by Nilstrieb** [comment]
Let's see what impact this has on #107181
@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
Seems like this was not the cause of the regression.

**Pull request closed without merging**
