### PR TITLE
Rollup of 14 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #94467 (Add `special_module_name` lint)
 - #100852 (Use `getuid` to check instead of `USER` env var in rustbuild)
 - #101072 (bootstrap: Add llvm-has-rust-patches target option)
 - #101190 (Make docs formulation more consistent for NonZero{int})
 - #101245 (Remove unneeded where whitespace)
 - #101251 (Fix  bad target name in Walkthrough)
 - #101254 (rustdoc: remove unused `.docblock .impl-items` CSS)
 - #101256 (Fixes/adjustments to Fuchsia doc walkthrough)
 - #101270 (Update outdated comment about output capturing in print_to.)
 - #101271 (Fix filename of armv4t-none-eabi.md)
 - #101274 (Fix typo in comment)
 - #101279 (Fix doc_auto_cfg for impl blocks in different modules with different `cfg`)
 - #101285 (Do not suggest adding `move` to closure when `move` is already used)
 - #101292 (rustdoc: remove unneeded CSS `.content table td:first-child > a`)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=94467,100852,101072,101190,101245,101251,101254,101256,101270,101271,101274,101279,101285,101292)

### CODE REVIEW

**Comment by rylev** [comment]
The regressions are all in the doc profile. One test case I looked at showed a 734% increase to the `propagate-doc-cfg` query which #101279 touches. 

@rust-timer build d3191247b17a806e5df88fb740ba418926f29e27

**Comment by rylev** [comment]
@GuillaumeGomez @notriddle it indeed looks like https://github.com/rust-lang/rust/pull/101279 is responsible for these regressions.

**Comment by GuillaumeGomez** [comment]
Yes, a bugfix where some `cfg` attributes where not retrieved as expected on impl blocks. Fixed by browsing through parents and merging with their cfg attributes.

**Comment by rylev** [comment]
Since this was for a bug fix and we tend to be a bit more lenient with rustdoc regressions, I'll go ahead and mark this as triaged.

@rustbot label +perf-regression-triaged

**Pull request merged**
