### PR TITLE
explain how to search in slice without owned data

### PR DESCRIPTION
**Pull request by RalfJung**
Cc https://github.com/rust-lang/rust/issues/62367

### CODE REVIEW

**Comment by timvermeulen** [comment]
>If you only have a borrowed `T`, use `any`

`contains` takes a borrowed `T`, though. It's only when you have a `&U` with `T: PartialEq<U>` that you need to use `any` instead.

**Comment by RalfJung** [comment]
Good point. I tried to improve the comment.

**Pull request merged**
