### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #76669 (Prefer asm! over llvm_asm! in core)
 - #76675 (Small improvements to asm documentation)
 - #76681 (remove orphaned files)
 - #76694 (Introduce a PartitioningCx struct)
 - #76695 (fix syntax error in suggesting generic constraint in trait parameter)
 - #76699 (improve const infer error)
 - #76707 (Simplify iter flatten struct doc)
 - #76710 (:arrow_up: rust-analyzer)
 - #76714 (Small docs improvements)
 - #76717 (Fix generating rustc docs with non-default lib directory.)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
normally this should have merged within an hour or 2, guess i'll wait for 20-30 mins and retry

**Comment by alex** [comment]
The macOS builders on GHA blocking is relatively recent I think.

**Comment by Dylan-DPC** [comment]
yeah looking at the CI It looks like those are the ones pending

**Pull request merged**
