### PR TITLE
Preserve doc-comments when generating queries

### LINKED ISSUE #76812: Query descriptions aren't rendered in rustdoc documentation
There are comments on `fn inherent_impls`, both on [the implementation](https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/coherence/inherent_impls.rs#L29-L30) and [declaration](https://github.com/rust-lang/rust/blob/master/compiler/rustc_middle/src/query/mod.rs#L501-L509). Despite that,  [`TyCtxt::inherent_impls`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.inherent_impls) doesn't have any docs.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/76784#discussion_r489398026_

### PR DESCRIPTION
**Pull request by jyn514**
Closes https://github.com/rust-lang/rust/issues/76812

### CODE REVIEW

**Comment by jyn514** [comment]
Example outputs:
image
image

**Comment by jyn514** [comment]
Ping @davidtwco - do you have time to take a look at this? It should be a pretty simple review.

**Comment by davidtwco** [comment]
> Ping @davidtwco - do you have time to take a look at this? It should be a pretty simple review.

Oh, I have no idea how I missed this, will definitely get to this today. Sorry!

**Review by davidtwco — APPROVED** [review]
This is awesome, sorry for being slow on the review. LGTM.

**Pull request merged**
