### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #115345 (MCP661: Move wasm32-wasi-preview1-threads target to Tier 2)
 - #115602 (Don't report any errors in `lower_intrinsics`.)
 - #115604 (rustdoc: Render private fields in tuple struct as `/* private fields */`)
 - #115629 (Don't suggest dereferencing to unsized type)
 - #115633 (Lint node for `PRIVATE_BOUNDS`/`PRIVATE_INTERFACES` is the item which names the private type)
 - #115634 (Use `newtype_index` for `IntVid` and `FloatVid`.)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=115345,115602,115604,115629,115633,115634)

### CODE REVIEW

**Comment by klensy** [comment]
https://github.com/rust-lang/rust/pull/115602 already merged

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r-

**Comment by cjgillot** [comment]
Bors is stuck on this PR.
@bors r-

**Pull request closed without merging**
