### PR TITLE
In BTreeMap's merge function, adjust the length of the node before mo…

### LINKED ISSUE #31029: SIGILL in collectionstest
I'm getting a reproducable test failure with a SIGILL failures on Linux x86_64.

Backtrace:
```
Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff47ff700 (LWP 22366)]
0x00005555556974e6 in sys_common::unwind::begin_unwind_inner::h59e609190038c574Rbt ()
(gdb) bt
#0  0x00005555556974e6 in sys_common::unwind::begin_unwind_inner::h59e609190038c574Rbt ()
#1  0x0000555555697f19 in sys_common::unwind::begin_unwind_fmt::h3cefed2b0a5c8147Xat ()
#2  0x00005555556a6532 in rust_begin_unwind ()
#3  0x00005555556ee880 in panicking::panic_fmt::hacab3d7465b1a2ebRZL ()
#4  0x00005555556ee829 in panicking::panic::h246db642899fee22oYL ()
#5  0x0000555555588339 in btree::map::IntoIter$LT$K$C$$u20$V$GT$.Iterator::next::h3381813257745463815 ()
#6  0x0000555555587f6b in btree::map::BTreeMap$LT$K$C$$u20$V$GT$.Drop::drop::h3725823349679420947 ()
#7  0x0000555555587e82 in btree::map::test_basic_large::haadc38722012d61eXyb ()
#8  0x000055555566ff37 in boxed::F.FnBox$LT$A$GT$::call_box::h5492873241474973492 ()
#9  0x00005555556729ac in sys_common::unwind::try::try_fn::h1695233641128253362 ()
#10 0x00005555556a64c9 in __rust_try ()
#11 0x00005555556a163c in sys_common::unwind::try::inner_try::had5cb7522d108c40p8s ()
#12 0x0000555555672d2b in boxed::F.FnBox$LT$A$GT$::call_box::h2919579301942330468 ()
#13 0x00005555556a8284 in sys::thread::Thread::new::thread_start::hbbeaa7fe2a2abc9ditx ()
#14 0x00007ffff79c1284 in start_thread (arg=0x7ffff47ff700) at pthread_create.c:333
#15 0x00007ffff74e874d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

cc @Gankro

### PR DESCRIPTION
**Pull request by gereeter**
…ving elements into it.

Fixes #31029.

### CODE REVIEW

**Comment by Gankro** [comment]
Just to be clear: this wasn't actually a soundness issue, right? This was just tripping internal asserts because metadata was being updated too late?

**Comment by gereeter** [comment]
@Gankro  Yes, exactly - this was not a soundness issue.

**Pull request merged**
