### PR TITLE
GHA: enable running multiple try builds at the same time

### LINKED ISSUE #70569: Only one try build can happen at the same time on GHA
On Azure Pipelines we can run as many try builds as we want, since cancelbot only looks at the `auto` branch. On GitHub Actions instead we kill the build if a new commit is pushed on all workflows, including try. We should avoid using the cancel-outdated-builds action on the try branch.

### PR DESCRIPTION
**Pull request by emilyalbini**
While for auto, try and PR builds we only want the latest commit to be tested, that's not true for try builds: each commit pushed to the branch is a different PR being tested, and we want multiple PRs to be tested in parallel if there is enough demand.

Fixes #70569

### CODE REVIEW

**Comment by pietroalbini** [comment]
r? @Mark-Simulacrum 

...unless Niko wants to review CI PRs :)

**Comment by Mark-Simulacrum** [comment]
> ...unless Niko wants to review CI PRs :)

I thought we had fixed this in highfive recently? If not, can you do so?

r=me if testing succeeds

**Comment by pietroalbini** [comment]
@bors r=Mark-Simulacrum rollup

I'll send a PR to highfive soon.

**Pull request merged**
