### PR TITLE
Add right border bar to Dark and Light theme

### PR DESCRIPTION
**Pull request by tesuji**
Demo:
Light theme: https://github.com/rust-lang/rust/pull/74504#issuecomment-662491120
Dark theme: https://github.com/rust-lang/rust/pull/74504#issuecomment-662522446
Ayu theme: https://github.com/rust-lang/rust/pull/74504#issuecomment-662625685

### CODE REVIEW

**Comment by Cldfire** [comment]
So, I intentionally added this as a feature. The highlight color I used is very subtle (to keep contrast high on the text and make it easy to read), and I added the highlight bar to provide an "anchor" of sorts that you can quickly scan for with your eyes when scrolling through the page.

I've found it very handy in my own usage and I would be sad to see it go. I'm curious if other people agree that it is distracting, though :slightly_smiling_face:.

**Comment by lzutao** [comment]
Personally, I don't get used to this highlight color bar yet. The first time I saw this bar, I wonder why is it highlighted?
Is something special about this function? I keep asking myself about it. Another potential reason is that I don't find
the similar feature in generated docs like MSDN, MDN or Java Oracle, ...

That's just my reason. If people like the highlighted bar, let's keep it.

**Comment by Cldfire** [comment]
> The first time I saw this bar, I wonder why is it highlighted? Is something special about this function? I keep asking myself about it.

Hmm, interesting. My thinking here is that the bar appears alongside the highlight color which makes it clear that it's part of the highlighted function style.

**Comment by jyn514** [comment]
I like the highlight because it makes the function stand out a little more. Without the bar the yellow on black is a little hard to see.

**Comment by lzutao** [comment]
If we people like it, I would expect we make the highlighting bar on other themes too for consistences.

**Comment by lzutao** [comment]
How do we continue the discussion? Maybe I ping other rustdoc devs like @GuillaumeGomez , @ollie27 .

**Comment by GuillaumeGomez** [comment]
I have to admit that I like the right border highlighted too. So I'm curious what it would look like in the other themes as well.

**Comment by lzutao** [comment]
With the same CSS rule:
On Dark theme: 
image
On Light theme:
image

**Comment by GuillaumeGomez** [comment]
Looks to me. :)

Someone from @rust-lang/rustdoc wants to comment here maybe?

**Comment by jyn514** [comment]
I think adding the highlight bar to the light theme so it's consistent is a great idea :)

**Comment by jyn514** [comment]
I think adding the highlight bar to the light theme so it's consistent is a great idea :)

**Comment by lzutao** [comment]
Ok, I changed the patch to include CSS rule for Dark and Light theme.

**Comment by GuillaumeGomez** [comment]
On second thought: can you make the border color a bit less luminous in the dark theme please?

**Comment by lzutao** [comment]
My color picking is nightmare: Is #bb7410 OK ?
Old: 
image
New:
image

**Comment by GuillaumeGomez** [comment]
Oh nice! Just need to have @Cldfire ok with this since it's the ayu theme. Can you something equivalent with the dark theme too please? :stuck_out_tongue:

**Comment by Manishearth** [comment]
I have no opinion on the color choice, it seems fine.

**Comment by lzutao** [comment]
Dark them:
#ffb44c : 
image
 
#bb7410: image

**Comment by GuillaumeGomez** [comment]
Let's go for `#bb7410` then! :)

**Comment by Cldfire** [comment]
Looks great!

As far as my thoughts on the colors, I would say we should do the following:

1. `#ffb44c` for the light theme (because the theme is very bright and the border color needs to be bright to fit in there)
2. `#bb7410` for the dark theme (or whatever @GuillaumeGomez thinks is best)
3. `rgba(255, 180, 76, 0.85)` for the ayu theme:

Before:

Screen Shot 2020-07-22 at 2 48 15 PM

After:

Screen Shot 2020-07-22 at 2 47 54 PM

I would like to avoid using `#bb7410` for the ayu theme because that color has a different tone to it that doesn't mesh with the rest of the color set.

@lzutao can you try those three colors out please? 😄

**Comment by lzutao** [comment]
Update the PR.

**Comment by lzutao** [comment]
*Just a note: @Cldfire You have bors right in this PR, you could use `@bors r+` to approve this PR.*

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks a lot!

@bors: r+ rollup

**Comment by lzutao** [comment]
Rebased and added co-author commit.

**Comment by GuillaumeGomez** [comment]
Let's go again!

@bors: r+ rollup

**Pull request merged**
