### PR TITLE
Update Cargo and stdsimd submodules

### LINKED ISSUE #52403: Update stdsimd submodule to destabilize an accidental stabilization
This is a tracking issue for updating `stdsimd` to pull in https://github.com/rust-lang-nursery/stdsimd/pull/524, destabilizing a currently nightly-only API. Want to make sure we don't forget about this by accident!

### PR DESCRIPTION
**Pull request by alexcrichton**
Update Cargo to bring in some bug fixes and such, and update `stdsimd` to...

### CODE REVIEW

**Comment by RalfJung** [comment]
Would you mind updating the submodule again to include https://github.com/rust-lang/cargo/pull/5710 ? :D

**Comment by alexcrichton** [comment]
@bors: r=Mark-SImulacrum

done!

**Comment by RalfJung** [comment]
Thanks :)

**Comment by pitdicker** [comment]
This PR now only updates the Cargo submodule, not stdsimd?

**Comment by kennytm** [comment]
```
duplicate artfacts found when compiling a tool, this typically means that something was recompiled because a transitive dependency has different features activated than in a previous build:
the following dependencies are duplicated although they have the same features enabled:
  backtrace 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)
    `clippy-driver` ("C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage2-tools\\x86_64-pc-windows-gnu\\release\\deps\\libbacktrace-7dc4ef752c85274e.rlib")
    `cargo` ("C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage2-tools\\x86_64-pc-windows-gnu\\release\\deps\\libbacktrace-ab50bab4d87e7bbe.rlib")
the following dependencies have different features:
  winapi 0.3.5 (registry+https://github.com/rust-lang/crates.io-index)
    `clippy-driver` additionally enabled features {} at "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage2-tools\\x86_64-pc-windows-gnu\\release\\deps\\libwinapi-b494f3abb913a03b.rlib"
    `cargo` additionally enabled features {"userenv"} at "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage2-tools\\x86_64-pc-windows-gnu\\release\\deps\\libwinapi-e648ff91915e2746.rlib"
thread 'main' panicked at 'tools should not compile multiple copies of the same crate', 
```

`cargo` added `"userenv"` feature to `winapi`. needs to update clippy and RLS.

**Comment by alexcrichton** [comment]
@bors: r=Mark-Simulacrum

@pitdicker correct, the stdsimd update got merged in with https://github.com/rust-lang/rust/pull/52433

**Comment by kennytm** [comment]
@alexcrichton #52433 doesn't contain stdsimd, I've excluded it from the rollup due to https://github.com/rust-lang/rust/pull/52433#issuecomment-405529577.

**Pull request merged**
