### PR TITLE
Steal MIR for CTFE when possible.

### PR DESCRIPTION
**Pull request by cjgillot**
Some bodies, like constants, have CTFE MIR but no optimized MIR.
In that case, have `mir_for_ctfe` steal the MIR instead of cloning it.

### CODE REVIEW

**Comment by cjgillot** [comment]
instr-count is balanced, while cycle count and max-rss appear greener.
r? compiler

**Comment by lqd** [comment]
and the incremental compilation benchmarks have been quite noisy on bitmaps yesterday/today

**Pull request merged**
