### PR TITLE
Revert behaviour change for bootstrap doc command

### LINKED ISSUE #113101: source links in std are not relative
They all target `doc.rust-lang.org/nightly`, which isn't great.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/113101.

In https://github.com/rust-lang/rust/pull/111955 and more precisely in https://github.com/rust-lang/rust/commit/58e18ddf86e67a1210a60ab4a0ad5e1adfbbc819, the behaviour for `x.py doc std` changed: before it was generating docs for `core` and `alloc` alongside `std`, after it was only generating docs for `std`.

r? @jyn514

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
And of course I forgot to run `fmt`. Fixed. ^^'

**Comment by jyn514** [comment]
i don't think we should do this. `std` refers to a single crate. use `library` if you want to document all crates.

**Comment by GuillaumeGomez** [comment]
I don't want all crates, I want `std` and its dependencies.

**Comment by jyn514** [comment]
ok. for that you can use `x doc core alloc std`.

**Comment by jyn514** [comment]
by the way, the previous behavior *was* to document all library crates, so reverting the PR still won't get you whar you want.

**Comment by ChrisDenton** [comment]
So if this is reverted then I'm wondering how I would document only a single crate?

**Comment by ChrisDenton** [comment]
It's usually how I check doc changes to std now. It'd be kinda cool if I could only preview the specific page(s) I'm interested in but failing that the whole crate is good enough.

**Comment by GuillaumeGomez** [comment]
It adds around 3 extra seconds on my computer for documenting `core` and `alloc`. If it's an issue for you, we can add an extra option to bootstrap maybe so you can still only document one crate like `x.py doc std --no-deps`?

**Comment by jyn514** [comment]
I'm sorry I didn't tag you on the original PR. This change affects more than just the rustdoc team, though (as Chris shows).

I don't want to make the interface for `doc` different than the interface for all the other bootstrap commands. Right now is an unambiguous meaning for `std` and it is the same between `check`, `build`, and `doc`. Changing `doc` to use `--no-deps` means that it's inconsistent with the other commands.

**Comment by jyn514** [comment]
> I don't want all crates, I want `std` and its dependencies.

on my laptop, `x doc std` (with your PR) takes 15 seconds and `x doc library` also takes 15 seconds. So I'm not sure I see much downside to using `library` instead.

**Comment by GuillaumeGomez** [comment]
For coherency sake, it might be better indeed... For me it takes 1 extra second to build the other two libs, so not an issue either. The only problems remaining are:

 * changing a habit: I can write an alias, it's just an annoyance.
 * rustdoc search testing

You also mentioned the use case from Chris, but it seems to be much more specific and less needed than the rustdoc team needs. Well in any case, I'm super annoyed that this behaviour I wrote on purpose was removed. If you don't plan to accept this revert, please just close the PR.

**Comment by oli-obk** [comment]
Seems like we found sth that works for everyone. The takeaway: if in doubt, ping. unsubscribing is easy.

**Comment by GuillaumeGomez** [comment]
I didn't understand your comment. In any case, the current state is not great because it changes the behaviour of a command used by the rustdoc and the alternative is not doing exactly the same. Not great, we'll see if problems come from that, although I doubt it.

**Comment by Manishearth** [comment]
Worth pointing out: bootstrap is _extremely_ confusing and inconsistent. Any attempt to fix that will lead to changes in current behavior that people may have formed habits around. It's worth trying to notice those changes and keep people informed, but that can only be best effort. 

In general changes in habit are a temporary thing and the benefits of consistency far outweigh the annoyances, so as such changes happen in the future I do think the right decision is to lean towards self-consistency rather than attempting to keep old behavior and workflows. Workflows can be changed, if something that was previously possible and necessary is no longer possible it's worth properly interrogating and perhaps designing something for that use case from first principles.

**Pull request closed without merging**
