### PR TITLE
Search codegen backends based on target libdir instead of sysroot

### LINKED ISSUE #57014: Rustc_driver cann't correctly find codegen dirs with multiple subfolders in libdir.
When rust compiled and installed with multiple subfolders in libdir it cann't correctly found directory with codegen-backends. See https://github.com/rust-lang/rust-clippy/issues/3565

```rust
        // use `parent` twice to chop off the file name and then also the
        // directory containing the dll which should be either `lib` or `bin`.
        if let Some(path) = dll.parent().and_then(|p| p.parent()) {
```
https://github.com/rust-lang/rust/blob/master/src/librustc_driver/lib.rs#L302

It would be work if `rustc_driver` was placed in `/usr/lib64/librustc_driver-62d9b292bf74f4a6.so` so it get `/usr` as sysroot but it placed in `/usr/lib64/rust-9999/librustc_driver-62d9b292bf74f4a6.so` so it get incorrect `/usr/lib64`.

I suppose it could be two possible solutions: The first is about to iterate parents until root will be reached. The second is to calculate number of parents need to be removed with `find_libdir` from `filesearch.rs`. Which are better or there are some other ways to solve this?

P.S. Looks like it doesn't fail for system-wide installed rustc and clippy because `filesearch::get_or_default_sysroot` got correct `/usr` sysroot from binaries in `/usr/bin`. If them will be moved same way as `gcc` in Gentoo it will break as well:
```bash
$ echo `which gcc`
/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0/gcc
```

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #57014

Fixes cases with custom libdir when it consists of two or more parts.

### CODE REVIEW

**Comment by RalfJung** [comment]
Uh... any idea why this would affect Miri only on Windows, and what we could do about that?

The error is
```
error: failed to find a `codegen-backends` folder in the libdir candidates:
* C:\projects\rust\build\x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib
* \\?\C:\projects\rust\build\x86_64-pc-windows-msvc\stage2\bin
* \\?\C:\projects\rust\build\x86_64-pc-windows-msvc\stage2\bin\rustlib\x86_64-pc-windows-msvc\lib
```

**Comment by o01eg** [comment]
It's strange. What is correct place of codegen library?

**Comment by RalfJung** [comment]
I have no idea, I hoped you'd tell me.^^

**Comment by o01eg** [comment]
I suppose it could be broken because windows places dynamic libraries in the "bin" folder.

**Comment by o01eg** [comment]
I'm afraid other tools will fail as well but they were already broken.

**Comment by o01eg** [comment]
How are executable binaries and codegen and rustc_driver libraries placed on windows? It looks like it requires other way to calculate target libdir and codegen folder.

**Comment by o01eg** [comment]
I could try to fix it after tomorrow. I think it better to revert PR now and then I try to fix it.
But it better to make a test to prevent this breakage.

**Pull request merged**
