### PR TITLE
Add regression test for #26886

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by tbu-** [comment]
Could you modify that to include this?

    std::sync::{self, Arc};
    std::sync::Arc;
    std::sync;

The `self` thing is what originally triggered the bug.

**Comment by Manishearth** [comment]
Done

**Comment by tbu-** [comment]
Thanks!

**Comment by apasel422** [comment]
I assume the commit message for this should include `Closes #26886`?

**Comment by Manishearth** [comment]
Doesn't need to, but adding.

**Pull request merged**
