### PR TITLE
`Default`: Always inline primitive data types.

### PR DESCRIPTION
**Pull request by Jerrody**

### CODE REVIEW

**Comment by thomcc** [comment]
Seems fine. Lets make sure this doesn't have a weird perf impact though.
@bors try @rust-timer queue

**Comment by Jerrody** [comment]
> Seems fine. Lets make sure this doesn't have a weird perf impact though. @bors try @rust-timer queue

It shouldn't have I expect improvements. But yes, it's better to check.

**Comment by Jerrody** [comment]
Wow, interesting. It's regressed.

**Comment by Jerrody** [comment]
Wow, interesting result. What the reason?

**Comment by lukas-code** [comment]
Looks like the usual perf noise, nothing to worry about. The dip in instruction count is https://github.com/rust-lang/rust/pull/112476#issuecomment-1605939112 and now it's gone back up.

image
image

**Comment by Mark-Simulacrum** [comment]
See https://github.com/rust-lang/rust/pull/113024#issuecomment-1606268421 - dropping regression label.

**Pull request merged**
