### PR TITLE
Revert libbacktrace -> gimli

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This reverts 4cbd265c119cb1a5eb92e98d2bb93466f05efa46 028f8d7b85898683b99e05564cd2976c7e0d5b43 13db3cc1e8d2fd4b8e7c74d91002274d7b62801b d7a36d8964c927863faef5d3b42da08f37e5896c (and technically 79673d300915f846726c27b9e1974dc451013ee9 but it's made empty by previous reverts).

The current plan is to land this PR as a temporary change, so that we can get a better handle on the regressions introduced by it. Trying to fix/examine them in master is difficult, and we want to be better able to evaluate them without impact to other PRs being landed in the mean time.

That said, it is currently *my* belief that gimli, in one form or another, will need to land sometime soon. I think it's quite likely that it may slip a week or two, but I would personally push for re-landing it then "regardless" of the regressions. We should try to focus efforts on understanding and removing as much of the performance impact as possible, as everyone pretty much agrees that it should be quite minimal (and entirely in the linker, basically).

r? @nnethercote

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
When re-landing this we should be sure to include https://github.com/rust-lang/rust/pull/74591.

**Comment by nnethercote** [comment]
This [improved perf](https://perf.rust-lang.org/compare.html?start=2bbfa02b1b15974d5772b520aa027bf79f8c248e&end=371917ab218de72a625227ba6eed7e84e610a058&stat=instructions:u) as expected.

**Pull request merged**
