### PR TITLE
Stabilize `#[track_caller]`.

### LINKED ISSUE #68178: Calling unwind via function pointer leads to odd panic message
I was playing around with function pointers to `track_caller` methods (which [doesn't seem entirely implemented yet](https://github.com/rust-lang/rust/pull/65182#issuecomment-573649550)) and arrived at the following testcase:
```rust
fn call_it<T>(f: fn(T), x: T) {
    f(x);
}

fn main() {
    call_it(Result::unwrap, Err(0));
}
```
On stable, this behaves as expected:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 0', src/libcore/result.rs:1165:5
```
On the latest nightly though, the message is different:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libstd/panicking.rs:369:15
```
The line number points at this:
https://github.com/rust-lang/rust/blob/af958046e5855a4254831102b502f57dafa40f69/src/libstd/panicking.rs#L369

Two things seem odd here for me:
* I am actually surprised that this does not ICE, given that the `ReifyShim` stuff does not seem entirely implemented (at least [this test](https://github.com/rust-lang/rust/pull/65182/commits/b8414c13abf9dc994f9c0dccee848a8b0fb1b061#diff-576c0bfe42a59f60c74b63e865d59d1d) still ICEs).
* But the actual main bug here is that the comment about "always returns Some" seems wrong, so this panics at the wrong place. Clearly, the message shouldn't talk about `Option::unwrap()` when the actual panic is caused by a `Result::unwrap`.

Cc @anp

### PR DESCRIPTION
**Pull request by anp**
# Stabilization Report

RFC: [2091]
Tracking issue: https://github.com/rust-lang/rust/issues/47809

## Summary

From the [rustc-dev-guide chapter][dev-guide]:

> Take this example program:

```rust
fn main() {
    let foo: Option<()> = None;
    foo.unwrap(); // this should produce a useful panic message!
}
```

> Prior to Rust 1.42, panics like this `unwrap()` printed a location in libcore:

```
$ rustc +1.41.0 example.rs; example.exe
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value',...core\macros\mod.rs:15:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

> As of 1.42, we get a much more helpful message:

```
$ rustc +1.42.0 example.rs; example.exe 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', example.rs:3:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

> These error messages are achieved through a combination of changes to `panic!` internals to make use of `core::panic::Location::caller` and a number of `#[track_caller]` annotations in the standard library which propagate caller information.

The attribute adds an implicit caller location argument to the ABI of annotated functions, but does not affect the type or MIR of the function. We implement the feature entirely in codegen and in the const evaluator.

## Bottom Line

This PR stabilizes the use of `#[track_caller]` everywhere, including traits and extern blocks. It also stabilizes `core::panic::Location::caller`, although the use of that function in a const context remains gated by `#![feature(const_caller_location)]`.

The implementation for the feature already changed the output of panic messages for a number of std functions, as described in the [1.42 release announcement]. The attribute's use in `Index` and `IndexMut` traits is visible to users since 1.44.

## Tests

All of the tests for this feature live under [src/test/ui/rfc-2091-track-caller][tests] in the repo.

Noteworthy cases:

* [use of attr in std]
  * validates user-facing benefit of the feature
* [trait attribute inheritance]
  * covers subtle behavior designed during implementation and not RFC'd
* [const/codegen equivalence]
  * this was the result of a suspected edge case and investigation
* [diverging function support]
  * covers an unresolved question from the RFC
* [fn pointers and shims]
  * covers important potential sources of unsoundness

## Documentation

The rustc-dev-guide now has a chapter on [Implicit Caller Location][dev-guide].

I have an [open PR to the reference][attr-reference-pr] documenting the attribute.

The intrinsic's [wrapper] includes some examples as well.

## Implementation History

* 2019-10-02: [`#[track_caller]` feature gate (RFC 2091 1/N) #65037](https://github.com/rust-lang/rust/pull/65037)
  * Picked up the patch that @ayosec had started on the feature gate.
* 2019-10-13: [Add `Instance::resolve_for_fn_ptr` (RFC 2091 #2/N) #65182](https://github.com/rust-lang/rust/pull/65182)
* 2019-10-20: ~~[WIP Add MIR argument for #[track_caller] (RFC 2091 3/N) #65258](https://github.com/rust-lang/rust/pull/65258)~~
  * Abandoned approach to send location as a MIR argument.
* 2019-10-28: [`std::panic::Location` is a lang_item, add `core::intrinsics::caller_location` (RFC 2091 3/N) #65664](https://github.com/rust-lang/rust/pull/65664)
* 2019-12-07: [Implement #[track_caller] attribute. (RFC 2091 4/N) #65881](https://github.com/rust-lang/rust/pull/65881)
* 2020-01-04: [libstd uses `core::panic::Location` where possible. #67137](https://github.com/rust-lang/rust/pull/67137)
* 2020-01-08: [`Option::{expect,unwrap}` and `Result::{expect, expect_err, unwrap, unwrap_err}` have `#[track_caller]` #67887](https://github.com/rust-lang/rust/pull/67887)
* 2020-01-20: [Fix #[track_caller] and function pointers #68302](https://github.com/rust-lang/rust/pull/68302) (fixed #68178)
* 2020-03-23: [#[track_caller] in traits #69251](https://github.com/rust-lang/rust/pull/69251)
* 2020-03-24: [#[track_caller] on core::ops::{Index, IndexMut}. #70234](https://github.com/rust-lang/rust/pull/70234)
* 2020-04-08 [Support `#[track_caller]` on functions in `extern "Rust" { ... }` #70916](https://github.com/rust-lang/rust/pull/70916)

### From the RFC

> Currently the RFC simply prohibit applying #[track_caller] to trait methods as a future-proofing
> measure.

**Resolved.** See the dev-guide documentation and the tests section above.

> Diverging functions should be supported.

**Resolved.** See the tests section above.

> The closure foo::{{closure}} should inherit most attributes applied to the function foo, ...

**Resolved.** This unknown was related to specifics of the implementation which were made irrelevant by the final implementation.

### Binary Size

I [instrumented track_caller to use custom sections][measure-size] in a local build and discovered relatively minor binary size usage for the feature overall. I'm leaving the issue open to discuss whether we want to upstream custom section support.

There's an [open issue to discuss mitigation strategies][mitigate-size]. Some decisions remain about the "right" strategies to reduce size without overly constraining the compiler implementation. I'd be excited to see someone carry that work forward but my opinion is that we shouldn't block stabilization on implementing compiler flags for redaction.

### Specialization

There's an [open issue][specialization] on the semantics of the attribute in specialization chains. I'm inclined to move forward with stabilization without an exact resolution here given that specialization is itself unstable, but I also think it should be an easy question to resolve.

### Location only points to the start of a call span

https://github.com/rust-lang/rust/issues/69977 was resolved by https://github.com/rust-lang/rust/pull/73182, and the next step should probably be to [extend `Location` with a notion of the end of a call](https://github.com/rust-lang/rust/issues/73554).

### Regression of std's panic messages

#70963 should be resolved by serializing span hygeine to crate metadata: https://github.com/rust-lang/rust/issues/68686.

[2091]: https://github.com/rust-lang/rfcs/blob/master/text/2091-inline-semantic.md
[dev-guide]: https://rustc-dev-guide.rust-lang.org/codegen/implicit-caller-location.html
[specialization]: https://github.com/rust-lang/rust/issues/70293
[measure-size]: https://github.com/rust-lang/rust/issues/70579
[mitigate-size]: https://github.com/rust-lang/rust/issues/70580
[attr-reference-pr]: https://github.com/rust-lang/reference/pull/742
[wrapper]: https://doc.rust-lang.org/nightly/core/panic/struct.Location.html#method.caller
[tests]: https://github.com/rust-lang/rust/tree/master/src/test/ui/rfc-2091-track-caller
[const/codegen equivalence]: https://github.com/rust-lang/rust/blob/master/src/test/ui/rfc-2091-track-caller/caller-location-fnptr-rt-ctfe-equiv.rs
[diverging function support]: https://github.com/rust-lang/rust/blob/master/src/test/ui/rfc-2091-track-caller/diverging-caller-location.rs
[use of attr in std]: https://github.com/rust-lang/rust/blob/master/src/test/ui/rfc-2091-track-caller/std-panic-locations.rs
[fn pointers and shims]: https://github.com/rust-lang/rust/blob/master/src/test/ui/rfc-2091-track-caller/tracked-fn-ptr-with-arg.rs
[trait attribute inheritance]: https://github.com/rust-lang/rust/blob/master/src/test/ui/rfc-2091-track-caller/tracked-trait-impls.rs
[1.42 release announcement]: https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#useful-line-numbers-in-option-and-result-panic-messages

### CODE REVIEW

**Comment by joshtriplett** [comment]
Looks reasonable to me.

**Comment by anp** [comment]
Thanks! Per https://github.com/rust-lang/rust/issues/47809#issuecomment-619079124 I think this needs `T-libs` as well before an FCP starts.

**Review by dtolnay — COMMENTED** [review]
Reassigning for lang FCP on this thread. I made a separate libs FCP in https://github.com/rust-lang/rust/issues/72448.

**Comment by joshtriplett** [comment]
@dtolnay Separating the stabilizations and FCPs seems like a good idea, thank you.

For T-lang:
@rfcbot merge

**Comment by nikomatsakis** [comment]
Nominating just to call attention to the FCP here

**Comment by anp** [comment]
Since 1.45 will enter beta in 2 days, I've updated the stability attributes to reference 1.46.

**Comment by Aaron1011** [comment]
> Call chains share a span

> As noted in #69977, the spans reported by panics in call chains can be confusing today. A resolution to this will probably require improvements to MIR's span reporting in addition to the possible need to extend Location with the notion of an end span (maybe needs an RFC?).

@anp: Now that https://github.com/rust-lang/rust/pull/73182 has merged, the reported `Span`s are now more useful in call chains. However, I think it would be still useful to extend `Location` to contain both a start and end position.

**Comment by anp** [comment]
@Aaron1011 thanks for the heads up! Updated the message and filed https://github.com/rust-lang/rust/issues/73554.

**Comment by anp** [comment]
Noting here that the libs proposal to merge in https://github.com/rust-lang/rust/issues/72448 has exited final comment period. @dtolnay should we close that issue?

**Comment by oli-obk** [comment]
@bors r+

everything has been signed off by the appropriate teams, so I guess let's get this shipped!

**Comment by Manishearth** [comment]
@bors r-

```
thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:344:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------
stderr:
------------------------------------------
warning: the feature `track_caller` has been stable since 1.46.0 and no longer requires an attribute to enable
  --> /checkout/src/test/ui/asm/sym.rs:6:17
   |
LL | #![feature(asm, track_caller, thread_local)]
   |                 ^^^^^^^^^^^^
   |
   = note: `#[warn(stable_features)]` on by default

warning: 1 warning emitted


------------------------------------------



failures:
    [ui] ui/asm/sym.rs
```

**Comment by anp** [comment]
Oops! Fixed that up and did a search to make sure I didn't miss any others. There are some uses in `src/tools/miri` but IIUC those will be fixed up when that repo rolls its toolchain right?

**Comment by Manishearth** [comment]
```
5591774Z error: the feature `track_caller` has been stable since 1.46.0 and no longer requires an attribute to enable 2020-07-01T01:17:30.5592649Z --> src/librustc_save_analysis/lib.rs:4:12 2020-07-01T01:17:30.5593212Z | 2020-07-01T01:17:30.5593754Z 4 | #![feature(track_caller)] 2020-07-01T01:17:30.5594342Z | ^^^^^^^^^^^^ 2020-07-01T01:17:30.5594848Z | 2020-07-01T01:17:30.5595424Z = note: `-D stable-features` implied by `-D warn
```

@bors r-

**Comment by anp** [comment]
Hm, I'm confused actually. The [logs](https://github.com/rust-lang-ci/rust/runs/824734341#step:23:1742) point to:

```
 --> src/librustc_save_analysis/lib.rs:4:12
  |
4 | #![feature(track_caller)]
  |            ^^^^^^^^^^^^
  |
```

But I can't find that in my checkout. I rebased on top of tree and pushed again.

**Pull request merged**
