### PR TITLE
Make GlobalCtxt thread-safe

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Two questions:
- is this ready for review?
- and how does this relate to https://github.com/rust-lang/rust/pull/50699/?

**Comment by Zoxc** [comment]
You can review still, but ignore `Pretend interpret_alloc_cache is thread-safe` and `Add fixme to InterpretInterner` as those will be removed once https://github.com/rust-lang/rust/pull/50520 lands.

I think this PR is independent of https://github.com/rust-lang/rust/pull/50699

**Comment by michaelwoerister** [comment]
Thanks, @Zoxc!

@bors r+

**Comment by michaelwoerister** [comment]
@Zoxc, this would need a quick rebase.

**Comment by Zoxc** [comment]
@michaelwoerister This now adds a `Sync` impl for `Slice`.

**Review by nikomatsakis — APPROVED** [review]

**Pull request merged**
