### PR TITLE
Add builder for Solaris and merge it with Fuchsia's builder

### PR DESCRIPTION
**Pull request by bgermann**
The new Solaris builder can be used to build rust-std.

The dilos illumos distribution was chosen, because illumos is free software
as opposed to Oracle Solaris and dilos is the only illumos distribution that
supports x86_64 and sparcv9 at the same level.

### CODE REVIEW

**Comment by bgermann** [comment]
@alexcrichton Is there anything left that I can do to enable official rust-std builds for sparcv9-sun-solaris and x86_64-sun-solaris?

**Comment by alexcrichton** [comment]
Thanks for the PR @bgermann! In terms of getting these available through rustup that'd basically require adding some form of a dist builder on Travis. Unfortunately adding entire new builders typically requires a big investment (we haven't done this in awhile) but if you can squeeze onto an existing builder then it normally works well.

It looks like you're just looking for the standard libraries here which are "easy" to build in the sense that they don't consume many resources. It looks like our `cross` builder is getting a little full at 1h44m as the last cycle time, but we could consider folding the dist-fuchsia builder into this builder as well (maybe even with the android builder if we're enterprising?)

**Comment by bgermann** [comment]
You are right, I'm only looking for the standard libraries. To merge with dist-fuchsia sounds reasonable. Which name should the merged Docker environment have?

**Comment by alexcrichton** [comment]
How about `cross2`

**Comment by alexcrichton** [comment]
@bgermann Looks great! Could you also test out deleting the `if: branch = auto` temporarily? That'll allow us to see how long timing-wise this should take and ensure the builder passes before it reaches bors

**Comment by alexcrichton** [comment]
@bors: r+

Awesome, thanks @bgermann!

**Comment by malbarbo** [comment]
@bgermann Great work, thanks! Do you know [cross](https://github.com/japaric/cross) project?  Maybe you can add support for cross compiling to sparc. It would be awesome.

**Comment by bgermann** [comment]
I will have a look at it.

**Pull request merged**
