### PR TITLE
Bump version to 1.49.0

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @pietroalbini

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors p=0

It is not actually critical that this lands ASAP, just "sometime in the next few days" -- we'll be able to fork from the previous commit regardless. (Unless there's some reason you bumped priority I'm not seeing?)

**Comment by pietroalbini** [comment]
Oh, then it's fine, I just treated this as any other release PR implicitly.

**Pull request merged**
