### PR TITLE
Restore trait impl docs

### LINKED ISSUE #24838: Documentation text on trait impl methods is hidden in docs
I use documentation on my trait impls to tell users about how my types behave:

```rust
impl<N, E, Ty, Ix> Index<NodeIndex<Ix>> for Graph<N, E, Ty, Ix> where
    Ty: EdgeType,
    Ix: IndexType,
{
    type Output = N;
    /// Index the **Graph** by **NodeIndex** to access node weights.
    ///
    /// **Panics** if the node doesn't exist.
    fn index(&self, index: NodeIndex<Ix>) -> &N {
        &self.nodes[index.index()].weight
    }
}
```

This documentation is not rendered anymore. I expect to see it under the entry for the `Index` implementation of the `Graph` type.

I think this was lost after (the otherwise very awesome!) documentation changes by @alexcrichton

### LINKED ISSUE #26871: rustdoc: show the descriptions of traits’ implementations if any
Right now if one adds additional information to an implementation of a trait’s method, that information is not shown in the output of `rustdoc`. For instance, the [implementation](https://github.com/rust-lang/rust/blob/master/src/liballoc/rc.rs#L457-L482) of `Drop` for `Rc` has an elaborate description with an example; however, this information is [not accessible](http://static.rust-lang.org/doc/master/std/rc/struct.Rc.html#implementations) to the readers.

Regards,
Ivan

### PR DESCRIPTION
**Pull request by pierzchalski**
Currently, documentation on methods in trait implementations doesn't get rendered. This changes that;  trait implementations have all documentation associated with impl items displayed (documentation from the trait definition is ignored).

Fixes #24838
Fixes #26871

### CODE REVIEW

**Comment by steveklabnik** [comment]
Love this change conceptually, not great with rustdoc's codebase yet. r? @alexcrichton

**Comment by mitaa** [comment]
> manual trait implementations have their documentation displayed, however derived traits don't.

I think it would make sense to instead only render these impl-items if they have doc-comments (`item.attrs.value("doc").is_some()`)

Then you could remove the `render_docs: bool` parameter and instead change the behaviour based on `link: AssocItemLink`.

**Comment by mitaa** [comment]
Could you also add some tests in `src/test/rustdoc/`?

**Comment by GuillaumeGomez** [comment]
What the hell is happening in commits messages in here?! XD

**Comment by mitaa** [comment]
> and instead change the behaviour based on link: AssocItemLink.

Actually, I think the current match on `AssocItemLink` in `doctraititem` could just removed (and the if guard converted to a normal if..) since `html::render::document` already checks for `item.doc_value().is_some()` (it would render stability attributes too, but I think that's not really a problem).

So the only necessary change would be to make [here](https://github.com/rust-lang/rust/blob/bb66d91c98d83ac5fc453f120ef4a810bc8939a5/src/librustdoc/html/render.rs#L2543-2548).

**Comment by alexcrichton** [comment]
I'm on board with everything @mitaa has mentioned :)

**Comment by pierzchalski** [comment]
Applied both of @mitaa's suggestions. Currently this means derived implementations also print any associated docs. Is that an issue?

@GuillaumeGomez I don't know what you're talking about :D
For future reference, I force-pushed a clean branch because @mitaa's suggestions were basically a re-write of what I'd done (and also because I prefer to rebase off master than merging it in). Is that an acceptable practice for Rust PRs, or would a bunch of reversions/merges be preferable?

**Comment by mitaa** [comment]
> Currently this means derived implementations also print any associated docs. Is that an issue?

I would assume that they don't have any :smile:
(also from looking at the [source][0] just now it doesn't look that way)

> For future reference, I force-pushed a clean branch because @mitaa's suggestions were basically a re-write of what I'd done (and also because I prefer to rebase off master than merging it in). Is that an acceptable practice for Rust PRs, or would a bunch of reversions/merges be preferable?

Yes, that's completely fine.

[0]: https://github.com/rust-lang/rust/blob/4e8e607d8469a8882944233e4bb3ee45d2a6435a/src/libsyntax_ext/deriving/clone.rs#L28

**Comment by pierzchalski** [comment]
@mitaa I'm looking at the docs (well, what `make docs` outputs), and I'm seeing some weird behaviour. For instance on the derived `Clone` impls for `Option` and `Result`, the required method `clone` has no docblock but the provided method `clone_from` does have one, even though they both have docs in the source for `Clone`. Turns out this also happens on manual trait impls.

I've updated the test to demonstrate the intended vs. actual behaviour, and now I'm hunting through `html/render.rs` and `clean/mod.rs` looking for why provided methods get the `"doc"` attribute of their definition but manual methods don't (which is what I'm guessing is causing the issue).

**Comment by mitaa** [comment]
Nice catch!

For non-overridden default methods we actually render the method of the trait itself (which obviously has the doc attribute).
https://github.com/pierzchalski/rust/blob/restore_trait_impl_docs/src/librustdoc/html/render.rs#L2555-L2581

`doctraititem` probably needs a ~`is_default_item: bool` argument after all.

**Comment by mitaa** [comment]
Well, that coupled with checking that `link == Anchor::GotoSource(..)`. (we still want to show the docs on the trait itself)

**Comment by pierzchalski** [comment]
Done.

Also, it looks like the `AssocItemLink::Anchor` test was unnecessary since `doctraititem` is only called to render trait impls, and doesn't affect the rendering of trait definitions including default items.

**Comment by alexcrichton** [comment]
@bors: r+ ec5e0f81cf54ca287e6652923e1bf46f4fc1c783

Thanks @pierzchalski!

**Pull request merged**
