### PR TITLE
Windows: Fallback for overlapped I/O

### LINKED ISSUE #98947: Writing a sufficiently large string to a git bash pipe on windows regressed in 1.62
### Reproduction steps:
1. Be on windows.
2. `cargo new --bin something`
3. replace main.rs with [main.txt](https://github.com/rust-lang/rust/files/9048190/main.txt) and rename it back to main.rs.
4. Open git bash
5. Run `cargo run | cat`

I expected to see this happen: my really long string gets printed twice, followed by a clean exit

Instead, this happened: some amount of my really long string gets printed, followed by: 
`fatal runtime error: I/O error: operation failed to complete synchronously`

### Additional Details
- The test case, while simple, does appear to have a minimum size requirement to trigger this crash. Shrinking the string will cause it to stop crashing.
- I'm using `cat` in the steps for simplicity, but we've observed this happening with other programs at the end of the pipe too.
- Redirecting to a file instead of a pipe seems to not trigger this crash.
- Using `cargo run` is not necessary to trigger the crash, running the built executable directly also crashes.
- This PR added this new error condition: https://github.com/rust-lang/rust/pull/95469
- I am not the only one seeing this new error message: https://github.com/rust-lang/rust/issues/98700#issuecomment-1171654196

### Version it worked on
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-pc-windows-msvc
release: 1.61.0
LLVM version: 14.0.0
```

### Version with regression
```
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-pc-windows-msvc
release: 1.62.0
LLVM version: 14.0.5
```

@rustbot modify labels: +regression-from-stable-to-stable +O-windows

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #98947

### CODE REVIEW

**Comment by ChrisDenton** [comment]
r? rust-lang/t-libs

**Comment by ChrisDenton** [comment]
r? rust-lang/libs

**Comment by wesleywiser** [comment]
cc @jstarks in case you want to take a look as well

**Comment by jstarks** [comment]
LGTM

**Comment by jstarks** [comment]
Might be good to add a test, perhaps by creating (and connecting to) an overlapped named pipe and reading from it.

**Comment by ChrisDenton** [comment]
I added a test (note that the `anon_pipe` function actually creates named pipes, one end of which is `OVERLAPPED`). On my machine I confirmed it tests the new code path by replacing `io_pending_fallback` with a panic.

**Comment by jstarks** [comment]
Thanks.

On a side note, I am trying to get NtCreateNamedPipeFile documented, which would allow you to create an anonymous pipe pair with the properties you want without the retry dance. I'll let you know when this happens.

**Comment by ChrisDenton** [comment]
Ok, from what I can tell via observer behaviour, `GetOverlappedResult` calls `WaitForSingleObject` and then assumes that if it returns success then the I/O has completed. However, this will not be true if the file handle was signalled for some other reason. Thus using `GetOverlappedResult` does not fix the soundness issue in the original issue.

However, with this information I can use `WaitForSingleObject` directly and make sure the I/O has actually completed before returning (or else aborting if that's not possible). Which is what I've done in the new commits.

**Review by thomcc — APPROVED** [review]
So... this is pretty subtle. I think it's ultimately fine, but it took a lot of discussion with @ChrisDenton on Discord to convince me (but to be clear: I am on board with it now).

That said, for future reference, this is usually not how you're supposed to do it. For example, the documentation for [`GetOverlappedResult`](https://docs.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-getoverlappedresult) states:

> Use of file, named pipe, or communications-device handles for this purpose is discouraged.

My understanding is the "right" way to solve this is to first call `GetOverlappedResult` with `bWait == FALSE`, to reset the event, and then call `GetOverlappedResult` with `bWait == TRUE` to actually wait. Failing to do this would result in it not actually waiting, which is what was observed when we used a single `GetOverlappedResult(TRUE)` call rather than `WaitForSingleObject`. I believe this was also required prior to Windows 7, and in many cases it is still true, such as when a manual-reset event is used in the `OVERLAPPED` (although my experience has certainly been that you still sometimes need to do this even if you don't!)

In most cases, I still think that is how it should be handled (notably it is sometimes required, but correct and harmless even in the case where you don't need to go through with it). However, in this case, I think it would actually be pretty weird, and we're justified:

1. We don't actually have an event, we're using the one in the file handle (well, that would often be true either way). At least in theory this means we should not *need* to do the double GOR dance.
2. We're also not using `ReadFile`, we're using `NtReadFile`, and as a result, we don't even have an `OVERLAPPED` in the first place. We would need to fabricate one with the state we expect it to have after `ReadFile` which returned pending. This is a bit of an abstraction violation, to say the least.
3. We don't need any of the other information provided by `GetOverlappedResult`. What we need it to do is wait, so we should just perform the wait.

Anyway, that's all to say I think this is fine. @ChrisDenton has asked me to wait on the R+ for a bit (for a response from @jstarks), so I'll give that a day or so before letting bors know

**Comment by jstarks** [comment]
Wow, I did not expect that wait behavior out of `GetOverlappedResult`, but you're absolutely right, the code does not check for `STATUS_PENDING` unless you specify Wait = FALSE. Yikes!

The new approach is a good one, both for this reason and to avoid the abstraction violation. Thanks @ChrisDenton and @thomcc.

**Comment by ChrisDenton** [comment]
Yeah, I find that really surprising. At first I was convinced I'd made a mistake somewhere. I guess it really is intended to be used with a dedicated event object.

**Comment by thomcc** [comment]
Alright, let's go!

@bors r+

**Comment by cuviper** [comment]
The documentation on `File` still forbids `FILE_FLAG_OVERLAPPED` -- should that be updated?

https://github.com/rust-lang/rust/blob/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/fs.rs#L90-L92

**Comment by ChrisDenton** [comment]
Personally I think we should still warn against using files opened for async I/O here. This may help mitigate the issue if users are careful (esp. with regard to threads) but these methods are still intended for async I/O.

I guess the "must" language could be made slightly weaker. But this purely a "best effort" to attempt a workaround in that case so I do feel we should still strongly suggest people use other methods for async I/O.

**Pull request merged**
