### PR TITLE
Add two tests

### PR DESCRIPTION
**Pull request by c410-f3r**
Related to #116864 and #116749 .

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
Could you fix CI errors?

**Comment by c410-f3r** [comment]
> WARN rustc_trait_selection::solve::eval_ctxt unstable result: unstable certainty

Solver entered in a loop but funny enough, this behavior didn't happen locally.

**Comment by c410-f3r** [comment]
The new solver is still experimental but it probably doesn't hurt to get some attention.

Kindly pinging @lcnr

**Comment by c410-f3r** [comment]
Thank you @lcnr !

It is always nice to have more tests but at least for now, I will close this PR.

**Pull request closed without merging**
