### PR TITLE
Allow Float::ldexp to be called as a method

### LINKED ISSUE #22098: Float::ldexp should use the same format as everything else
[`std::num::Float::ldexp`](http://doc.rust-lang.org/std/num/trait.Float.html#tymethod.ldexp) has an unusual format: it takes `x: Self` as it's first parameter where everything else in the trait takes `self`. It should take `self` as it's first parameter for consistency with everything else.

It is located in [`std::num::mod`](https://github.com/rust-lang/rust/blob/master/src/libstd/num/mod.rs#L249)

### PR DESCRIPTION
**Pull request by milibopp**
Fixes #22098.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Needs a rebase

**Comment by aturon** [comment]
@aepsil0n Sorry this PR totally fell through the cracks in my inbox! (Feel free to ping me or others on IRC if you're not hearing anything).

Anyway, this looks good to me after a rebase.

**Comment by aepsil0n** [comment]
I wasn't around for the last days. Will rebase later.

**Comment by aepsil0n** [comment]
@aturon rebase is done.

**Comment by aturon** [comment]
Thanks!

@bors: r+ 316f7e8 rollup

**Comment by Manishearth** [comment]
```
/opt/rust/src/libstd/num/f32.rs:2369:5: 2378:6 error: duplicate definition of value `test_abs`
/opt/rust/src/libstd/num/f32.rs:2381:5: 2390:6 error: duplicate definition of value `test_abs_sub`
/opt/rust/src/libstd/num/f32.rs:2393:5: 2396:6 error: duplicate definition of value `test_abs_sub_nowin`
/opt/rust/src/libstd/num/f32.rs:2399:5: 2408:6 error: duplicate definition of value `test_signum`
/opt/rust/src/libstd/num/f32.rs:2411:5: 2420:6 error: duplicate definition of value `test_is_positive`
/opt/rust/src/libstd/num/f32.rs:2423:5: 2432:6 error: duplicate definition of value `test_is_negative`
/opt/rust/src/libstd/num/f32.rs:2435:5: 2449:6 error: duplicate definition of value `test_is_normal`
/opt/rust/src/libstd/num/f32.rs:2452:5: 2466:6 error: duplicate definition of value `test_classify`
/opt/rust/src/libstd/num/f32.rs:2469:5: 2486:6 error: duplicate definition of value `test_ldexp`
/opt/rust/src/libstd/num/f32.rs:2489:5: 2503:6 error: duplicate definition of value `test_frexp`
/opt/rust/src/libstd/num/f32.rs:2506:5: 2513:6 error: duplicate definition of value `test_frexp_nowin`
/opt/rust/src/libstd/num/f32.rs:2516:5: 2525:6 error: duplicate definition of value `test_integer_decode`
/opt/rust/src/libstd/num/f32.rs:2528:5: 2536:6 error: duplicate definition of value `test_sqrt_domain`
```

on Linux

**Comment by aepsil0n** [comment]
oops… I wasn't careful enough doing the rebase.

**Comment by aepsil0n** [comment]
fixed.

**Pull request merged**
