### PR TITLE
use shared scripts for init and sccache in cross image

### PR DESCRIPTION
**Pull request by venkatagiri**
cc #42201 
cc @malbarbo

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @venkatagiri!

**Comment by alexcrichton** [comment]
Eh the URLs there are different enough it may not be worth to do so, but I'd be fine either way!

**Comment by malbarbo** [comment]
Could you clarify what you mean by "Eh the URLs there are different enough it may not be worth to do so"?

My suggestion was to create two scripts, so that following the image build is easy because the reader is not distract by details. It would read, build-rumprun, build-arm-musl, install-mips-musl, install-mipsel-musl, etc.

**Comment by venkatagiri** [comment]
Yes. Even I thought I could move the install URLs into their own script.
But, since they weren't shared across images, wasn't sure if I need to.

If that's fine, I can go ahead and move them into scripts.

**Comment by alexcrichton** [comment]
Oh I'd be fine either way. I personally prefer for one-off scripts to just be in the `Dockerfile`, but I don't mind doing otherwise!

**Comment by venkatagiri** [comment]
@alexcrichton I have extracted the musl installation from Dockerfile into scripts.

**Comment by venkatagiri** [comment]
Fixed the tidy errors by splitting the URL into variables.

**Comment by alexcrichton** [comment]
@bors: r+

Looks great!

**Comment by Mark-Simulacrum** [comment]
@bors r-

```
[00:05:23] Step 11 : RUN ./install-mips-musl.sh
[00:05:23]  ---> Running in e58d0caf3c29
[00:05:23] /bin/sh: 1: ./install-mips-musl.sh: Permission denied
[00:05:23] The command '/bin/sh -c ./install-mips-musl.sh' returned a non-zero code: 126
[00:05:23] The command has failed after 5 attempts.
```

**Comment by venkatagiri** [comment]
@Mark-Simulacrum Fixed the file permissions.

**Comment by Mark-Simulacrum** [comment]
I seem to recall a `chmod +x` being necessary to do so -- but I may be wrong. I'm going to holdoff on re- r+ until someone more familiar comes along to re-review.

**Comment by venkatagiri** [comment]
Yes. I ran chmod +x on the files and merged them into last commit.
The file shows as "Executable file" now. https://github.com/venkatagiri/rust/blob/7acc999b4249a774dd617153524e3819b2ab9da7/src/ci/docker/cross/install-mips-musl.sh

**Comment by Mark-Simulacrum** [comment]
Ah, okay, I looked in the scripts and I think I was wrong -- we don't actually need to add +x beyond what we store in git.

@bors r=alexchrichton

**Pull request merged**
