### PR TITLE
tidy: Add a check for inline unit tests

### PR DESCRIPTION
**Pull request by petrochenkov**
As described in https://github.com/rust-lang/rust/issues/61097.

There's a large whitelist right now, because in many crates the tests are not outlined yet.
~This PR only outlines tests in one crate (`rustc_lexer`) as an example.~

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by petrochenkov** [comment]
This also needs to check for `#[bench]` + false positives like `" ... #[test] ... "` in diagnostic strings need to be worked around somehow + liballoc seems to have the same restrictions as libcore so it would be nice to enforce them in tidy.

**Comment by Mark-Simulacrum** [comment]
I think false-positives are presumably infrequent enough that we could work around them via `// ignore-tidy-` infrastructure (similar to length, etc.). Not sure how easy it is to thread that into a sub-pass of tidy, though.

Approach looks good to me. It might be nicer to an extent to use the same `ignore-tidy-` annotations for all files that we're ignoring instead of the custom skip list (at least outside of src/test, perhaps?) but that doesn't seem all that important.

**Comment by petrochenkov** [comment]
Updated.
- `#[bench]` attributes are checked as well
- restrictions on tests and benchmarks in `liballoc` are enforced (identical to `libcore`)
- `` `#[test]`` and `` `#[bench]`` (with a back quote) are ignored during checking, this is a good heuristic for allowing the attributes in diagnostic messages, so I didn't need to add an additional `ignore-tidy-...` annotation.
- the changes in `librustc_lexer` are removed for now to avoid possible conflicts.

>It might be nicer to an extent to use the same ignore-tidy- annotations for all files that we're ignoring instead of the custom skip list (at least outside of src/test, perhaps?) but that doesn't seem all that important.

Yeah, this is all temporary anyway, once this PR lands, I'll prepare another big PR moving the code, so it doesn't matter much.

**Comment by Mark-Simulacrum** [comment]
@bors r+

Looks good to me. I'm not entirely certain that the skip rules are correct, but since this is simply tidy we can correct that over time if we discover they're inaccurate.

**Pull request merged**
