### PR TITLE
Limit target endian to an enum instead of free string

### PR DESCRIPTION
**Pull request by tesuji**
This is #77604 revived.

### CODE REVIEW

**Comment by petrochenkov** [comment]
>If you're still not satisfied with that respond, I will remove them.

Yes, could you remove them.
Otherwise, LGTM.

**Comment by lzutao** [comment]
I removed the micro methods.
@rustbot label: -S-waiting-on-author +S-waiting-on-review

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Comment by petrochenkov** [comment]
>error: book maintainer @carols10cents is not assignable in the rust-lang/rust repo

@bors retry

**Pull request merged**
