### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by fmease**
Successful merges:

 - #126015 (Migrate `run-make/symlinked-rlib` to `rmake.rs`)
 - #126034 (Clarify our tier 1 Windows Server support)
 - #126035 (Some minor query system cleanups)
 - #126051 (Clarify an `x fmt` error.)
 - #126059 (Raise `DEFAULT_MIN_STACK_SIZE` to at least 64KiB)
 - #126068 (Revert "use `tcx.used_crates(())` more" before it reaches beta)
 - #126073 (Port `tests/run-make-fulldeps/obtain-borrowck` to ui-fulldeps)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=126015,126034,126035,126051,126059,126068,126073)

### CODE REVIEW

**Comment by jieyouxu** [comment]
@fmease do you mind if I schedule https://github.com/rust-lang/rust/pull/125736 ahead of this rollup? That PR is prone to merge conflicts from other run-make tests.

**Comment by fmease** [comment]
no worries, go ahead!

**Comment by fmease** [comment]
If this rollup and Guillaume's will become unmergeable after #125736 because it contains #126015, shoudn't #126015 be r-'ed until then and marked as blocked?

**Comment by jieyouxu** [comment]
> If this rollup and Guillaume's will become unmergeable after #125736 because it contains #126015, shoudn't #126015 be r-'ed until then and marked as blocked? This way, rollups won't be created unnecessarily.

I thought I marked that PR as blocked but apparently I didn't click "comment"... Sorry.

**Pull request closed without merging**
