### PR TITLE
Add trait bound styles

### PR DESCRIPTION
**Pull request by zonyitoo**
1. Add normal trait bound styles
2. Add `where` clause trait bound styles

### CODE REVIEW

**Comment by bluss** [comment]
Where does the recommendation to not use where clauses for single bounds come from?

**Comment by zonyitoo** [comment]
@bluss Because it is short, so you could write them in the front.

**Comment by bluss** [comment]
If we make style recommendations it must be discussed more widely.

I don't agree with the recommendation here, where clauses should be ok in all cases.

**Comment by zonyitoo** [comment]
Maybe I should change the word, you could always use the where clause, but if you decide to write them in the front, then it should be 1-3 type parameters with single bound

**Comment by zonyitoo** [comment]
@bluss Is that able to merge? :)

**Comment by bluss** [comment]
Need wider feedback. By the way, you have some submodule bumps in the PR by mistake, those need to be rebased out.

**Comment by steveklabnik** [comment]
I don't think we should be modifying the style guide with new recommendations without using the RFC process, or going through the RFC process to define one. As such, I'm going to give this one a close for now. Modifying the style guide will become a really big, important topic once rustfmt is further along.

**Pull request closed without merging**
