### PR TITLE
Fix spans for continues and breaks

### PR DESCRIPTION
**Pull request by marcusklaas**
Fixes https://github.com/rust-lang/rust/issues/28108.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Was the modified test broken by this change? It looks like that should probably still be passing?

**Comment by marcusklaas** [comment]
It still passes now, but may not be very future-proof: https://github.com/rust-lang/rust/pull/28106#discussion_r38276697

**Comment by alexcrichton** [comment]
Could this leave around the test for now and just add a new one for the spans?

**Comment by marcusklaas** [comment]
The new test does the exact same thing as the old one. There's no test for the new changes AFAIK, as the spans have shrunk.

**Comment by alexcrichton** [comment]
Although these may hit the same code path they're testing two distinct things:

1. The span of an unknown label
2. The span of a break/loop outside a loop

In general it's better to err on the side of more tests basically, so could this just add a new test instead of modifying an existing one?

**Comment by marcusklaas** [comment]
The test's original intention was never to check the span of the label, but to make sure that the keywords were included in the span: https://github.com/rust-lang/rust/pull/28106
As you and @nagisa correctly note, this isn't what was actually tested, hence the change.

The changes to `parser.rs` and the test are unrelated and I now realize I should've just created separate PRs for them. Shall I do that after all?

**Comment by nagisa** [comment]
@alexcrichton I approve that test change, if that means anything. For all its worth the labels thing has its own issue: https://github.com/rust-lang/rust/issues/28109, therefore the labels should eventually get a test for them anyway.

**Comment by alexcrichton** [comment]
Can you please leave the test case as is?  #28105 is a legit issue and #28108 should get its own test case as well.

**Comment by marcusklaas** [comment]
Reverted test, although I still believe that there is a misunderstanding here.

**Pull request merged**
