### PR TITLE
Typo in ownership.md

### PR DESCRIPTION
**Pull request by tincann**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 4d1e48e37610f421f30e098f2ae9ef98b85b66eb rollup

Thanks!

**Comment by tincann** [comment]
It's not much, but you're welcome. Quite enjoying the documentation style. Very easy to read.

**Comment by tshepang** [comment]
Needs an r+

@tincann next time just create a separate Issue if  the current one has been approved.

**Pull request merged**
