### PR TITLE
Start removing `Nonterminal`

### PR DESCRIPTION
**Pull request by nnethercote**
A second attempt at this; the first attempt was #96724.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
This is a successor to #96724, where I started doing this with `NtExpr` and then gave up because it was difficult. It is a necessary predecessor for fixing #67062.

So far I have removed `NtVis` and `NtTy`, both of which are easier than `NtExpr`. The pretty printing of `vis` and `ty` captures is now much worse. #114571 would fix that, by improving pretty printing of token streams.

It's unclear to me how to best stage this work, whether to do it in pieces, or all in a single huge PR.

cc @petrochenkov

**Comment by nnethercote** [comment]
The latest update removes `NtPat`.

**Comment by nnethercote** [comment]
The latest update removes `NtItem`. Doing this made me realize that removing `Token::Interpolated`/`Nonterminal` will remove [this restriction](https://doc.rust-lang.org/nightly/reference/macros-by-example.html#forwarding-a-matched-fragment), because a test about that restriction started passing.

**Comment by petrochenkov** [comment]
The PR is marked as draft, so marking is as waiting on author as well (I'll be busy for the next few days, and won't be able to review anyway).

Once this is ready I'll ask to split all the preparational commits + one of the smaller nonterminals (`NtVis`) to a separate PR.
@rustbot author

**Comment by nnethercote** [comment]
#114571 should be considered ahead of this one. It improves token stream pretty printing greatly, which helps minimize changes to tests in this PR.

**Comment by nnethercote** [comment]
The latest update removes `NtMeta`.

**Comment by nnethercote** [comment]
The latest update removes `NtPath`.

**Comment by nnethercote** [comment]
And now `NtBlock`.

**Comment by nnethercote** [comment]
The latest updates remove `NtExpr`, `NtLiteral`, `NtIdent`, `NtLifetime`, `Nonterminal`, and `Token::Interpolated`. The commit removing `NtExpr` and `NtLiteral` is rough, with lots of `njn:` comments and a couple of test failures. But it all basically works.

I haven't yet added handling of invisible delimiters from proc macros, which will be required to fix #67062.

@petrochenkov: it might be worth taking a look now, to see what you think of the overall approach.

**Comment by nnethercote** [comment]
That test failure above on the `bail!` call is a known one from the `NtExpr`/`NtLiteral` removal.

I have opened #114915 for all the preliminary cleanup commits.

**Comment by nnethercote** [comment]
W.r.t. #67062:
- When you have an invisible-delimited token sequence that came from a declarative macro expansion, it's easy to know how to parse them, because they are marked with the metavar fragment kind (e.g. `expr`, `ty`, `vis`, etc.)
- But with an invisible-delimited token sequence that came from a proc macro, there's no marker indicating what kind of language fragment it's supposed to be. A lot of the time this doesn't matter so much -- you just try to parse it as the appropriate kind depending on context.
- But there are tricky cases. E.g. a visibility can appear before an item. In an item context, if you see an invisible-delimiter token sequence from a proc macro, should you try to parse the sequence as a visibility? (Which might be empty.) Or as an item? You have to do some lookahead inside the sequence to know (by looking for `pub`). Which is doable, but makes the handling different to the handling of the declarative macro cases. And I'm not sure how many other situations like this exist.

**Comment by nnethercote** [comment]
> W.r.t. #67062:
> 
> * When you have an invisible-delimited token sequence that came from a declarative macro expansion, it's easy to know how to parse them, because they are marked with the metavar fragment kind (e.g. `expr`, `ty`, `vis`, etc.)
> 
> * But with an invisible-delimited token sequence that came from a proc macro, there's no marker indicating what kind of language fragment it's supposed to be. A lot of the time this doesn't matter so much -- you just try to parse it as the appropriate kind depending on context.
> 
> * But there are tricky cases. E.g. a visibility can appear before an item. In an item context, if you see an invisible-delimiter token sequence from a proc macro, should you try to parse the sequence as a visibility? (Which might be empty.) Or as an item? You have to do some lookahead inside the sequence to know (by looking for `pub`). Which is doable, but makes the handling different to the handling of the declarative macro cases. And I'm not sure how many other situations like this exist.

I'm hitting this same problem in a different case. `tests/ui/proc-macro/issue-75734-pp-paren.rs` has this code:
```rust
macro_rules! mul_2 {
    ($val:expr) => {
        print_bang!($val * 2);
    };
}

#[print_attr]
fn main() { 
    &|_: u8| {};
    mul_2!(1 + 1);
}
```
The `mul_2!(1 + 1);` line is expanded to `«1 + 1» * 2;`, which makes it a `StmtKind::Expr`.

If the `«1 + 1»` came from an `expr` metavar, we would know it's an expression, and `parse_stmt_without_recovery` would easily handle it as an expression.

But when the `«1 + 1»` comes from a proc macro, we don't know what kind of language fragment it is. The obvious thing (according to the current structure of the code) is to try to parse it as a statement. Indeed, `«1 + 1»` can be parsed as a `StmtKind::Expr`. But then the `* 2` is left over and causes a syntax error: "expected one of `;` or `}`, found `*`".

So it's a tricky case. We're looking for a statement, and we have an invisible-delimited sequence right in front of us that is a valid statement, but it must actually be parsed as an expression that will form part of a larger expression and statement. I can't think of a reasonable way to handle it.

**Comment by nnethercote** [comment]
With the `«1 + 1» * 2;` case above it might be possible to preserve the `expr` annotation from the declarative macro through the proc macro. Because the code fragment is just converted from internal form to proc macro form and back. That would be enough to get the above example working. But there would still be cases where code is built from scratch within the proc macro, and so doesn't have a kind annotation, that are difficult to parse.

**Comment by nnethercote** [comment]
The last commit partially implements removal of invisible delimiter skipping. This is enough to make the examples in #67062 work, but the problems mentioned above occur.

**Comment by nnethercote** [comment]
There are still some good ideas in here that I'd like to pursue, so I'll keep it open.

**Comment by nnethercote** [comment]
My next attempt at this is now in #124141.

**Pull request closed without merging**
