### PR TITLE
Recursively expand `TokenKind::Interpolated` in `probably_equal_for_proc_macro`

### LINKED ISSUE #68430: Rustc doesn't report line numbers for type errors within proc macro async fn within macro_rules macro
When using a macro to generate an async fn with a proc macro inside it, if the generated function includes a type error, rustc will not report any line number information. This makes finding and debugging type errors in large async applications extremely difficult.

I tried this code:

```
async fn foo() {}

macro_rules! gen_test {
    ($before:expr) => {
        #[tokio::test]
        async fn test_foo() {
            $before;
            let x: () = foo();
        }
    }
}

gen_test!(dbg!(4));
```

I expected to see this happen: 

Error including line number information (you will get this output if you just comment out the `$before`line in the test fn)

```
error[E0308]: mismatched types
  --> src/lib.rs:8:25
   |
8  |             let x: () = foo();
   |                         ^^^^^
   |                         |
   |                         expected (), found opaque type
   |                         help: consider using `.await` here: `foo().await`
...
13 | gen_test!(dbg!(4));
   | ------------------- in this macro invocation
   |
   = note: expected type `()`
              found type `impl std::future::Future`
```

Instead, this happened: 

Error including no line number information

```
error[E0308]: mismatched types
  |
  = note: expected type `()`
             found type `impl std::future::Future`

error: aborting due to previous error
```

## Meta

`rustc --version --verbose`: Tested on Playground with stable 1.40.0 and nightly 1.42.0 (2020-01-20)

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #68430

When comparing the captured and re-parsed `TokenStream` for a `TokenKind::Interpolated`, we currently treat any nested `TokenKind::Interpolated` tokens as unequal. If a `TokenKind::Interpolated` token shows up in the captured `TokenStream` due to a `macro_rules!` expansion, we will throw away the captured `TokenStream`, losing span information.

This PR recursively invokes `nt_to_tokenstream` on nested `TokenKind::Interpolated` tokens, effectively flattening the stream into a sequence of non-interpolated tokens. This allows it to compare equal with the re-parsed stream, allowing us to keep the original captured `TokenStream` (with span information).

This requires all of the `probably_equal_for_proc_macro` methods to be moved from `librustc_ast` to `librustc_parse` so that they can call `nt_to_tokenstream`.

### CODE REVIEW

**Comment by petrochenkov** [comment]
LGTM, but need to check perf.

**Comment by Aaron1011** [comment]
@petrochenkov: It looks like perf is unchanged

**Comment by Aaron1011** [comment]
@petrochenkov: Rebased. I ended up needing to add a `smallvec` dep to `librustc_parse`.

**Pull request merged**
