### PR TITLE
Specialize `Extend` to `append` for `{LinkedList, Vec}`

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Neat! Could you also add a few tests exercising these cases specifically just to make sure we have coverage in some fashion?

**Comment by apasel422** [comment]
Updated with tests.

**Comment by apasel422** [comment]
@alexcrichton Any idea what's going on with bors?

**Comment by alexcrichton** [comment]
I think bors is just being a little slow, this is [in the queue though](http://buildbot.rust-lang.org/homu/queue/rust)

**Comment by alexcrichton** [comment]
I interrupted this to hopefully push https://github.com/rust-lang/rust/pull/32944 through which can help us cache LLVM a little more aggressively and this hadn't gone for too long just yet, bors should return back soon though!

**Comment by apasel422** [comment]
Updated to hide trait docs.

**Pull request merged**
