### PR TITLE
Accept arbitrary expressions in key-value attributes at parse time

### LINKED ISSUE #52607: Creating a `doc` attribute from `stringify!` or `concat!` in a macro works in some situations but not others
# Summary

Although creating a `doc` attribute directly from a `stringify!` (or `concat!`) does not work, i.e.,
``` rust
#[doc = stringify!(Fails)]
pub enum Fails {}
```
fails with
```
error: unexpected token: `stringify`
```
it is possible to use a macro in some situations. For example, this code compiles correctly
``` rust
macro_rules! working {
    ($doc:expr, $id:ident) => {
        #[doc = $doc]
        pub enum $id {}
    }
}

working!(stringify!(Working), Working);
fn main() { }
```
and `rustdoc` creates the correct documentation.

# Code demonstrating the issue
``` rust
macro_rules! bug_helper {
    (#[$attr:meta] $id:ident) => {
        #[$attr]
        pub enum $id {}
    }
}

macro_rules! bug {
    ($doc:expr, $id:ident) => {
        bug_helper! { #[doc = $doc] $id }
    }
}

bug!(stringify!(Bug), Bug);
fn main() { }
```
The error message is similar to the one at the top of this report.
```
error: unexpected token: `stringify!(Bug)`
```

If the `stringify!(Bug)` is replaced with `"Bug"`, the code compiles correctly.

All of the above holds true if you replace `stringify!` with `concat!`.

# Expectation
I'd expect the second and third code samples above to either both produce an error message or neither. (Preferably, neither.)

# Versions
Both stable (rustc 1.27.2 (58cc626de 2018-07-18)) and nightly (rustc 1.29.0-nightly (874dec25e 2018-07-21)) have the same behavior.

### PR DESCRIPTION
**Pull request by petrochenkov**
Continuation of https://github.com/rust-lang/rust/pull/77271.

We now support arbitrary expressions in values of key-value attributes at parse time.
```
#[my_attr = EXPR]
```
Previously only unsuffixed literals and interpolated expressions (`$expr`) were accepted.

There are two immediate motivational cases for this:
- External doc strings (`#[doc = include_str!("my_doc.md")]`, eliminating the need in https://github.com/rust-lang/rust/issues/44732) and expanding macros in this position in general. Currently such macro expansions are supported in this position in interpolated `$expr`s (the `#[doc = $doc]` idiom).
- Paths (`#[namespace = foo::bar] extern "C++" { ... }`) like proposed in https://github.com/rust-lang/rust/pull/76734.

If the attribute in question survives expansion, then the value is still restricted to unsuffixed literals by a semantic check.
This restriction doesn't prevent the use cases listed above, so this PR keeps it in place for now.

Closes https://github.com/rust-lang/rust/issues/52607.
Previous attempt - https://github.com/rust-lang/rust/pull/67121.
Some more detailed write up on internals - https://internals.rust-lang.org/t/macro-expansion-points-in-attributes/11455.
Tracking issue - https://github.com/rust-lang/rust/issues/78835.

### CODE REVIEW

**Comment by SoniEx2** [comment]
does this solve the translatable docs problem?

**Comment by petrochenkov** [comment]
@SoniEx2 
No? But it may provide tools for a higher-level system to solve it.
Similarly to https://github.com/rust-lang/rust/issues/44732, this is a low-level feature, in theory in can be used to document crate with different `cfg`s and include different documentation depending on that `cfg`.

**Comment by SoniEx2** [comment]
`#[doc = include_str!("my_doc.md")]` looks nice but you'd have to be able to supply the path based on a build setting (uhh like `#[doc = include_str!(concat!(env!("doc_lang"), "my_doc.md"))]` maybe?)

**Comment by petrochenkov** [comment]
>`#[doc = include_str!(concat!(env!("doc_lang"), "my_doc.md"))]`

This should already work, I will add a test.

**Review by davidtwco — APPROVED** [review]
I'm not exceptionally confident in my understanding of this, but it looks broadly correct to me. r=me if you don't have other changes to make or are fine with just my review.

**Comment by m-ou-se** [comment]
This change will allow for finally cleaning up the `doc_comment` hacks in `core`: https://github.com/rust-lang/rust/pull/79150  :smiley:

**Comment by jyn514** [comment]
> External doc strings (#[doc = include_str!("my_doc.md")], eliminating the need in #44732) and expanding macros in this position in general. Currently such macro expansions are supported in this position in interpolated $exprs (the #[doc = $doc] idiom).

Before recommending this, someone should test how this interacts with `unindent_comments` (https://github.com/rust-lang/rust/pull/78400).

**Comment by jyn514** [comment]
(but to be clear: I'm strongly in favor of this, I'm always +1 for having features in rustc instead of special-casing rustdoc.)

**Comment by m-ou-se** [comment]
> Before recommending this, someone should test how this interacts with `unindent_comments`

@jyn514 Looks like that works just fine:

```rust
#![feature(extended_key_value_attributes)]

const _: &[u8] = compile_time_run::run_command!("sh", "-c", "echo '    .second(\"hello\")' > somefile");

/// You are supposed to call it like this
///
/// # Example
///
/// ```
/// let example = Example::new()
///     .first("hello")
#[cfg_attr(not(feature = "one"), doc = include_str!("../somefile"))]
///     .third("hello")
///     .build();
/// ```
pub struct Example {}
```

This results in:

image

**Comment by petrochenkov** [comment]
To lang team: this PR has lower priority than https://github.com/rust-lang/rust/pull/79078.

**Comment by Mark-Simulacrum** [comment]
We discussed this during the lang team meeting and felt that if this is just adding unstable surface area we can proceed here without a T-lang FCP. If there is something we're stabilizing then we'd like that called out more explicitly though and we can take another look :)

We also had a question around the hygiene behavior of the passed tokens -- do we handle those equivalently to other macro input? If so then no concerns.

**Comment by petrochenkov** [comment]
>We also had a question around the hygiene behavior of the passed tokens -- do we handle those equivalently to other macro input?

Yes, nothing changes with regards to hygiene.

**Comment by rylev** [comment]
@petrochenkov this PR caused some moderate regressions on the `match-stress-exhastive_patterns` perf benchmark which does have many key-value attributes in it (generated by [the macros module](https://github.com/rust-lang/rustc-perf/blob/master/collector/benchmarks/match-stress-exhaustive_patterns/src/macros.rs)). This might be worth looking into.

**Comment by petrochenkov** [comment]
@rylev 
https://github.com/rust-lang/rust/pull/80441#issuecomment-751843496 recovers some of the performance.

**Comment by m-ou-se** [comment]
The change this PR makes in `compiler/rustc_parse/src/parser/mod.rs` somehow makes `rustfmt` apply this formatting:

```diff
-macro foo($type_name: ident, $docs: expr) {
+macro foo($type_name:ident, $docs:expr) {
```

Without the `parser/mod.rs` changes of this PR, `rustfmt` leaves this line untouched and does not remove the spaces.

**Comment by m-ou-se** [comment]
Ah, apparently rustfmt doesn't format the macro parameters if it cannot format/parse the body. The full test case is:

```rust
macro foo($type_name: ident, $docs: expr) {
    #[allow(non_camel_case_types)]
    #[doc=$docs]
    #[derive(Debug, Clone, Copy)]
    pub struct $type_name;
}
```

The body contained a `#[doc=$docs]` which it couldn't understand before, but can be handled fine now with this change, causing it to no longer skip formatting of the entire macro definition.

Mystery solved.

**Comment by pthariensflame** [comment]
I passed over this issue the first time through the list, but…does this need `relnotes`?  On a closer look it seems like people would want to know about new capabilities for proc macros.

**Comment by petrochenkov** [comment]
@pthariensflame 
This is still only available on nightly, relnotes for new features are usually applied to stabilization PRs.

**Comment by pthariensflame** [comment]
Understood!

**Pull request merged**
