### PR TITLE
Speedup search loading when search url is received

### LINKED ISSUE #45971: Rustdoc: search page loads docs page before search results
E.g., if you navigate to https://doc.rust-lang.org/nightly/std/index.html?search=Vec, then you see the docs for the std page for a second or two (longer if you're internet is bad, I assume) before you get the search results for Vec.

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #45971.

r? @nrc

cc @rust-lang/docs

### CODE REVIEW

**Review by nrc — COMMENTED** [review]
This seems like an improvement since we won't see the 'main' page, but it doesn't seem like it will actually speed anything up. Questions:

* would it actually be possible to get the search results quicker, or is this as good as it gets?
* would it make any difference if we didn't download the 'main' page, rather than just not show it? Is that even possible to do?

So r+ for this, but curious if we can do better too.

**Comment by GuillaumeGomez** [comment]
> would it actually be possible to get the search results quicker, or is this as good as it gets?

To get results faster, we need the search to be faster. Other (opened) PRs of mine are improving this. However, there's no magic in here and unfortunately, I don't think we'll be able to be this much faster...

> would it make any difference if we didn't download the 'main' page, rather than just not show it? Is that even possible to do?

What is the 'main' page you're referring to? If you're talking about the docs, we cannot not have it.

**Comment by kennytm** [comment]
Triage — Hi @nrc, is @GuillaumeGomez satisfactory for r+?

**Comment by kennytm** [comment]
@nrc Ping for review again (on #rust-internals as well)!

**Pull request merged**
