### PR TITLE
Do out-of-tree build on Travis

### PR DESCRIPTION
**Pull request by sanxiyn**
In particular, mount the source directory read-only.

### CODE REVIEW

**Comment by Manishearth** [comment]
(travis on this wasn't triggered, and that's important for this PR)

**Comment by sanxiyn** [comment]
run-make tests are failing.

**Comment by nikomatsakis** [comment]
@sanxiyn do you know what the problem is? Should we keep this PR open?

**Comment by sanxiyn** [comment]
Yes, I know what the problem is. Please keep open.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with tests fixed!

**Comment by sanxiyn** [comment]
run-make tests were fixed in #37176 and build is out-of-tree since #37584.

**Pull request closed without merging**
