### PR TITLE
Pass no_integrated_as option to llvm

### PR DESCRIPTION
**Pull request by pftbest**
Workaround for #59077

cc @nikic

### CODE REVIEW

**Comment by nikic** [comment]
#62907 should also resolve the issue, so not sure if we want to change this.

**Comment by pftbest** [comment]
@nikic ok, please close this if #62907 will solve the problem

**Comment by edmilsonefs** [comment]
Hey! This is a ping from triage, we would like to know if you @nikic could give us a few more minutes to update here so we can move forward.

Could you confirm if we can close here?

Thanks.

**Comment by edmilsonefs** [comment]
Hey! This is a ping from triage, we would like to know if you @nikic, @cr1901, @pftbest or @eddyb could give us a few more minutes to double check here so we can move forward.

It seems that #62907 got merged, Could any of you guys confirm if we can close here?

Thanks.

**Comment by pftbest** [comment]
#59077 has been fixed with #62907, so this patch is no longer needed.

**Pull request closed without merging**
