### PR TITLE
`#[deriving(..)]` -> `#[derive(..)]` everywhere

### PR DESCRIPTION
**Pull request by suhr**
Subj.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Unfortunately this will need to wait until we get a new snapshot that understand `derive`, or otherwise stage0 won't build :(

**Comment by japaric** [comment]
A snapshot just landed, I think this is unblocked now.

**Comment by Gankro** [comment]
Needs a rebase :(

**Comment by suhr** [comment]
Looks like everything is fixed by https://github.com/rust-lang/rust/commit/351409a62287c7993bc680d9dfcfa13cba9c9c0c.

**Pull request closed without merging**
