### PR TITLE
Warn windows-gnu users that the bundled gcc can't compile

### PR DESCRIPTION
**Pull request by ljedrz**
Add a `DO NOT USE THIS gcc.exe FOR COMPILATION.txt` file to `lib\rustlib\*-pc-windows-gnu\bin` folders in `windows-gnu` installations in order to warn against attempting to use the bundled `gcc.exe` as a C compiler. I'm pretty sure that location is usually found manually, so this should be easily noticeable.

This mistake has been made plenty of times and has lead to misunderstandings:
Rust: [Bundled gcc (windows x64) is unable to build any c file](https://github.com/rust-lang/rust/issues/24418)
gtk-rs:    [Compiling on windows](https://github.com/gtk-rs/gtk/issues/625)
bzip2-rs: [Build failure at gcc level: blocksort.c not found](https://github.com/alexcrichton/bzip2-rs/issues/30)

Alternatives: rename the bundled `gcc.exe` to e.g. `rustc-gcc.exe` or `gcc-linker.exe`. This might require a more comprehensive change or break crates already using it as a linker.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder though if perhaps we could start out with a `README.txt` file or something like that? If that doesn't act as enough deterrent we can go I think with the "alarming filename"

**Comment by ljedrz** [comment]
I've thought about it, but it might not be visible enough - when someone finds `gcc.exe` they add that location to their `PATH` and later, when they receive a misleading error, they are not investigating GCC, but rather the affected library. The name could be a bit less aggressive and still arising suspicion, though - maybe `GCC WARNING.txt`?

**Comment by alexcrichton** [comment]
Ok! Although perhaps a dash in the middle as I'm not sure I trust out shell scripts to handle spaces in filenames :(

**Pull request merged**
