### PR TITLE
Fixed typo and example in the introduction.

### PR DESCRIPTION
**Pull request by ic**
Changed guaranteed for "quaranteed", and
Made failing/working examples look alike.

r? @steveklabnik

### CODE REVIEW

**Comment by alexandercampbell** [comment]
@ic I made a PR a couple days ago that fixed the typos in the same paragraph and it was just merged: https://github.com/rust-lang/rust/pull/22906

Sorry about the conflicts!

**Comment by ic** [comment]
@alexandercampbell Thanks for the note. It was a tiny typo anyway ;-)

How about the change to the concurrency example? The first time I read the section, I wished for more "connected" examples. Simple edit, and tested on nightly.

**Comment by steveklabnik** [comment]
@lc I agree making them more consistent is good, thanks! However, you have a merge commit in here, would you mind rebasing that out? r=me after.

**Comment by alexandercampbell** [comment]
@ic I like the change you made, but I'm not a maintainer or anything-- #22906 was my first PR

**Comment by ic** [comment]
@steveklabnik Thank you for the feedback. I have set the repository with a HEAD at the commit. I have also removed the conflicting commit related to @alexandercampbell' s change. I chose this way of proceeding, as pulling the master HEAD refuses to fast-forward right now. I did not investigate much yet. Please let me know as necessary.

@alexandercampbell Ok, thank you. Let's get some more in ;-)

**Comment by steveklabnik** [comment]
Looks good, thank you!

**Pull request merged**
