### PR TITLE
Add an intermediate representation to exhaustiveness checking

### PR DESCRIPTION
**Pull request by Nadrieril**
The exhaustiveness checking algorithm keeps deconstructing patterns into a `Constructor` and some `Fields`, but does so a bit all over the place. This PR introduces a new representation for patterns that already has that information, so we only compute it once at the start.
I find this makes code easier to follow. In particular `DeconstructedPat::specialize` is a lot simpler than what happened before, and more closely matches the description of the algorithm. I'm also hoping this could help for the project of librarifying exhaustiveness for rust_analyzer since it decouples the algorithm from `rustc_middle::Pat`.

### CODE REVIEW

**Comment by camelid** [comment]
Interesting, `issue-58319` doesn't seem to have a pattern match. I guess it regressed because it has a large `struct` definition that is being lowered?

**Comment by Nadrieril** [comment]
It's weird though, because patterns used to be lowered already via a `PatternFolder`, which I imagine traverses everythings and reallocates. So I didn't expect that my new lowering would be much slower

**Comment by Nadrieril** [comment]
Ok, some progress. My local measurements differ quite a bit from perf here, so I want to see what it says now.

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
Huh ok I found the main issue; commit [`180204f` (#88950)](https://github.com/rust-lang/rust/pull/88950/commits/180204f0e8f27ceb2c34ca62c82cf131c43416c7) fixes it. Apparently changing from an explicit for loop to the equivalent iterator expression killed perf specifically for match-stress-enum. The rest of the regression was because cloning my new struct is slower than copying a ref, so I arena-allocated my struct too.
I don't know how to stop the timer, let's hope rescheduling does it.

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
Oops, I confused rustc-timer, that's the benchmark for the previous branch head. Let's try again, I'm measuring only improvements locally.

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
Cleaned up, let's test again

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
Last perf run before this is reviewable :crossed_fingers: 

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
The small perf regression on one benchmark is made up for by the improvements on quite a few benchmarks.
@rustbot label: +perf-regression-triaged

Cool, this is ready for review! I would usually ask @varkor but he seems unavailable at the moment.
r? @oli-obk if you have the time

**Comment by Nadrieril** [comment]
Ohh I can trivialize the terrible mess that was `SubPatSet` now! Biig simplification, this was the most arcane part of the algorithm. Help I can't stop simplifying things :upside_down_face: . I'll have to stop when a reviewer comes by

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
@varkor remember the mess I introduced to solve https://github.com/rust-lang/rust/pull/80632? It's all in this cute function now https://github.com/Nadrieril/rust/blob/b7e358ee17a5794603b2324858de078c4586acfc/compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs#L1577-L1586 ! 7 lines of this do the job of about 250 lines of convoluted `SubPatSet` logic x)

**Comment by oli-obk** [comment]
😆 I'm getting to it right now

**Comment by oli-obk** [comment]
r=me unless you want to keep investigating the stress test perf regression

**Comment by Nadrieril** [comment]
Yay thanks!

Most (1%) of the regression comes from the last commit, presumably the part where we retraverse all the patterns. Since that didn't affect the more realistic benchmarks, and no real match has 8000 arms, I believe that retraversing the patterns takes negligible time in real cases. So I'll ignore that 1%.
Imo it's plenty worth it in code clarity anyways.
@rustbot label: +perf-regression-triaged

@bors r=oli-obk

**Comment by DevinR528** [comment]
Just want to second how much more readable the code is without `SubPatSet` (after https://github.com/rust-lang/rust/pull/88950/commits/b7e358ee17a5794603b2324858de078c4586acfc) everything looks better look forward to having to rebase :stuck_out_tongue_winking_eye:!

**Comment by BubbaSheen** [comment]
Hypothetical information in check. Move pawns forward to await checkmate
from King W VV.

**Pull request merged**
