### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #44625, #44765, #44785, #44786, #44789
- Failed merges:

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I have no idea what went wrong in here... Let's give it another try...

@bors: retry

**Comment by alexcrichton** [comment]
@bors: r-

No that's a legitimate error, let's please retry that.

This is likely https://github.com/rust-lang/rust/pull/44785

**Comment by GuillaumeGomez** [comment]
Ok, I'll just close it then.

**Pull request closed without merging**
