### PR TITLE
Removes Default for Box<Path>.

### PR DESCRIPTION
**Pull request by clarfonthey**
This was not supposed to be added. cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks great to me, thanks! r=me with a rebase

**Comment by clarcharr** [comment]
Just rebased, should work now!

**Comment by alexcrichton** [comment]
@bors: r+ p=1

(beta nominated)

**Comment by alexcrichton** [comment]
@clarcharr according to https://github.com/rust-lang/rust/pull/40550 a test may need an update as well?

**Comment by clarcharr** [comment]
Oh, whoops. Updated the PR.

**Pull request merged**
