### PR TITLE
Add suggestion to reborrow mutable references when they're moved in a for loop

### LINKED ISSUE #83924: Unhelpful / misleading error message and help message when using a reference to a vector
Hello,
There is a case where the Rust compiler error message is misleading. I tried this code :

```rust
fn main() {
    let mut values = vec![10, 11, 12];
    let v = &mut values;

    let mut max = 0;
    
    for n in v {
        max = std::cmp::max(max, *n);
    }

    println!("max is {}", max);
    println!("Converting to percentages of maximum value...");
    for n in v {
        *n = 100 * (*n) / max;
    }
    println!("values: {:#?}", values);
}
```

…which gives the following error message, and misleading « help » message :
```
error[E0382]: use of moved value: `v`
   --> src/main.rs:13:14
    |
3   |     let v = &mut values;
    |         - move occurs because `v` has type `&mut Vec<i32>`, which does not implement the `Copy` trait
...
7   |     for n in v {
    |              -
    |              |
    |              `v` moved due to this implicit call to `.into_iter()`
    |              help: consider borrowing to avoid moving into the for loop: `&v`
...
13  |     for n in v {
    |              ^ value used here after move
    |
```
Especially, the `help: consider borrowing to avoid moving into the for loop: '&v'` is the misleading part, does not help solve the problem at all, and sent me an a wrong path.
As I am new to Rust, this got me scratching my head for some time until someone explained it to me ([here](https://users.rust-lang.org/t/use-of-moved-value-when-using-a-reference-to-a-vector/57873/2)).
(And since the Rust compiler is most of the time very helpful, I did not even consider that its suggestion could be wrong haha. Hm.)
Maybe a short message explaining how to reborrow the reference in this kind of situation would be more helpful and less misleading ?
Thank you.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

### PR DESCRIPTION
**Pull request by SkiFire13**
Address #83924

### CODE REVIEW

**Comment by eggyal** [comment]
This is definitely a better diagnostic, but (as mentioned in the underlying issue) I wonder if it's not possible to fix the desugaring so that `&&Vec` etc are actually iterable.

**Comment by SkiFire13** [comment]
Even if `&&mut Vec` was iterable I don't think that would be what the user actually wants. Chances are that the code inside the loop expects the item to be some sort of mutable reference, so iterating over a `&&mut Vec` would still not work. If `&mut &mut Vec` was iterable then adding a `&mut` would also be another valid suggestion, but that's no different than suggesting to reborrow.

**Comment by eggyal** [comment]
> If `&mut &mut Vec` was iterable

To be completely clear, I did indeed mean to fix desugaring so that `&mut &mut Vec` (and indeed anything that can be deref-coerced to an iterable) is also iterable.

> then adding a `&mut` would also be another valid suggestion, but that's no different than suggesting to reborrow. 

Aye that's fair, although obviously it would also catch other scenarios too.

**Comment by estebank** [comment]
Let's not close the reporting ticket on merge so that an alternative desugaring can be explored to make this code Just Work™️.

**Pull request merged**
