### PR TITLE
Filter ui revision tests

### PR DESCRIPTION
**Pull request by bovinebuddha**
Updates UI test output filtering to also filter away test annotations for revisions:

Previously filtered: //~ ERROR [XXXX]
Now also filters: //[revision]~ ERROR [XXXX]

I reckon, if we have the one, we should have the other for consistency, its lack was probably an oversight (the existence of revision testing is not really well documented...)

### CODE REVIEW

**Comment by petrochenkov** [comment]
This is just an oversight, yes, thanks for fixing it.

You may want to check whether fulldeps tests and NLL tests are updated properly.
```sh
./x.py test --bless src/test/ui --compare-mode nll
./x.py test --bless src/test/ui-fulldeps
```
and otherwise search for accidental `//[revision]~`s in `.stderr` and `.stdout` files that could remain due to tests not running on all platforms.

r=me after that

**Comment by bovinebuddha** [comment]
r? @petrochenkov 

I applied some sed-magic to the test folder, hopefully this will fix all the tests I didn't/couldn't run.

**Comment by petrochenkov** [comment]
@bors r+ p=1

I suspect that these ones are just stray files and can be removed though
```
E0508.ast.stderr
E0508.mir.stderr
borrowck/borrowck-union-borrow.mir.stderr
```

**Comment by bovinebuddha** [comment]
@petrochenkov Do you want me to remove those files? Also, what is the common practice, should I squash the last two commits (and possibly the last one) into one commit? Or maybe noone cares?

**Comment by petrochenkov** [comment]
@bovinebuddha 
If you remove the tests, I'll re-r+.
In this case I don't think any squashing is required (people generally care to various degree, depending on reviewer).

**Comment by bovinebuddha** [comment]
I found 402 other stderr revision files which are no longer used.... I'd like to remove them all, but maybe I'll do that in another PR once this lands.

Would it be okay to add a makefile under src/test with a make command to remove these extraneous files? It was a 'simple' exercise of find, grep, sed. I did use bash-specific syntax though. Or should something maybe be added to x.py instead?

**Comment by petrochenkov** [comment]
@bovinebuddha 
>I found 402 other stderr revision files which are no longer used

Are you sure those are not produced by NLL tests or something?

>Would it be okay to add a bash script under src/test with a make command to remove these extraneous files?

We already have a check for unused files in `tools/tidy/src/ui_tests.rs`, it's run during `x.py test tidy` and can be expanded if necessary.

**Comment by bovinebuddha** [comment]
Ah, you were right of course. Those were all nll checks plus a few false positives by me. I didn't realize that revisions and the nll compare mode had the same mechanism for generating stderr files...

I pushed a commit which removed the files you mentioned, there were no other obsolete files I could find.

**Comment by bovinebuddha** [comment]
@petrochenkov Thanks for the help, and please r+ when you have the time :)

**Comment by bovinebuddha** [comment]
@petrochenkov 

How do you actually know which tests are executed for each compare mode? I was thinking about updating 'tools/tidy/src/ui_tests.rs' to check if the test actually specified the relevant revision. I don't know where to check to resolve mode/revision ambiguity though.

**Comment by petrochenkov** [comment]
I'm not entirely sure, but from what I can infer from code in `compiletest` the `.nll` versions of output are created only if they are different from non-NLL output.
So, each test in test suites that are run with NLL (i.e. `ui` and `run-pass`) can potentially produce an `.nll` file.

Revisions that are run for each specific test are specified in its `// revisions:` clause.

**Comment by bovinebuddha** [comment]
Hmmm, I see. I also find this fascinating 'ignore-compare-mode-nll' annotations in tests which actually specify nll as a revision. I guess any check would have to hardcode all possible compare modes for their possible existence.

**Pull request merged**
