### PR TITLE
Stabilize static lifetime in statics

### LINKED ISSUE #35897: Tracking issue for static lifetime in statics (RFC #1623)
Tracking issue for "static lifetime in statics", rust-lang/rfcs#1623, which defaults omitted lifetimes in statics to `'static`.

cc @llogiq

### PR DESCRIPTION
**Pull request by est31**
Stabilize the "static_in_const" feature. Blockers before this PR can be merged:

* [x] The [FCP with inclination to stabilize](https://github.com/rust-lang/rust/issues/35897#issuecomment-270441437) needs to be over. FCP lasts roughly three weeks, so will be over at Jan 25, aka this thursday.
* [x] Documentation needs to be added (#37928)

Closes #35897.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@est31 nice

**Comment by est31** [comment]
Rebased.

**Comment by est31** [comment]
Rebased on top of @eddyb 's PR. Its really great to see how the PR made this change much easier, so it was a good refactor!

**Comment by alexcrichton** [comment]
ping @nrc, would be a neat feature for 1.17!

**Comment by est31** [comment]
@alexcrichton its currently blocked by #37928

**Comment by est31** [comment]
Now that beta branched, I would like to ask for beta backport nomination, so that already 1.16 would have it stabilized.

**Comment by steveklabnik** [comment]
Backporting stabilizations is incredibly rare; I would prefer we didn't.

**Comment by nrc** [comment]
@bors: r+

I would also recommend against backporting - I don't think we should reduce stabilisation time in general.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/37928 is not yet closed, how is this being merged?

**Comment by est31** [comment]
The documentation PR got merged, this is ready to be r+ed!

**Comment by petrochenkov** [comment]
It took 2.5 months to document this (https://github.com/rust-lang/rust/pull/37928 was open at Nov 22, 2016).
Fantastic.

@bors r+

**Comment by alexcrichton** [comment]
Removing beta nomination as sentiment seems to be to not backport (also see #35897)

**Pull request merged**
