### PR TITLE
Fix typo in operands section

### PR DESCRIPTION
**Pull request by ab22593k**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
An `lvalue` is a value that identifies a memory location. I think this terminology was changed to "place" at some point, so maybe that would be better here.

**Comment by awh6al** [comment]
Misunderstanding thanks @jonas-schievink, should i close this PR.

**Comment by jonas-schievink** [comment]
You can also change it to say "place" instead, but I'm not sure how widespread that wording is either. It's documented in the reference at least: https://doc.rust-lang.org/reference/expressions.html?highlight=lvalue#place-expressions-and-value-expressions

**Pull request merged**
