### PR TITLE
Don't require the output from libtest to be valid UTF-8

### LINKED ISSUE #112273: Error when testing with x.py
(Sorry if this isn't the right template, I wasn't sure what to choose)

Hi, when I run tests with x.py from the command `python3 x.py test library/std` I get this error `thread 'main' panicked at 'failed to read output of test runner : stream did not contain valid UTF-8', render_tests.rs:97:29`.

### PR DESCRIPTION
**Pull request by jyn514**
On Windows this is sometimes not the case, for reasons I can't track down (maybe related to localization? the bug report had a french locale).

This works around the problem, although I'm not sure how to confirm we're not generating invalid build metrics in this case.

Fixes https://github.com/rust-lang/rust/issues/112273.

### CODE REVIEW

**Review by onur-ozkan — APPROVED** [review]
Solid fix! The change looks almost the same, except that it solves the problem. Looks good to me:)

**Comment by ozkanonur** [comment]
> This works around the problem, although I'm not sure how to confirm we're not generating invalid build metrics in this case.

Feel free to `r-/r+` if you want to leave a comment/fixme on the change

**Comment by jyn514** [comment]
mmm i'm not sure what i'd change - if @pietroalbini has thoughts i can change the behavior here, but otherwise i think it's ok as-is. non-utf8 output should be extremely rare anyway.

**Comment by the8472** [comment]
> This works around the problem

Does it though? Printing non-utf8 to a windows console will just error a bit later. https://doc.rust-lang.org/std/io/fn.stdout.html

> When operating in a console, the Windows implementation of this stream does not support non-UTF-8 byte sequences. Attempting to write bytes that are not valid UTF-8 will return an error.

**Comment by jyn514** [comment]
@the8472 https://github.com/rust-lang/rust/issues/112273#issuecomment-1575585172 says this fixed the problem :shrug:

**Pull request merged**
