### PR TITLE
Divide test run between multiple travis builds.

### PR DESCRIPTION
**Pull request by Yamakaky**

### CODE REVIEW

**Comment by Yamakaky** [comment]
What this PR does is dividing the testing work between multiple travis threads. It should shorten the push-build-edit loop, since the modified job is the one taking much longer that the others. I'll add some doc about the segmentation method when I see that it works.

**Comment by alexcrichton** [comment]
Could you elaborate on the motivation for such a PR? It looks like the current cycle time for the full test suite on this builder (on PRs today) is just under an hour, and it looks like the sharding here didn't bring an improvement as all the builders are still taking around an hour?

In general this is increasing the number of builders we need which increases stress on infrastructure capacity, so we just need to be sure to do so purposefully

**Comment by Yamakaky** [comment]
Hum, strange, I thought it would have a bigger effect. From better-backtrace, I had the impression that the tests were taking a long time.

**Comment by alexcrichton** [comment]
I'm going to close this due to inactivity, but if there's solid evidence that this can speed up the build please feel free to resubmit!

**Pull request closed without merging**
