### PR TITLE
Add Benchmarks for int_pow Methods.

### PR DESCRIPTION
**Pull request by NCGThompson**
There is quite a bit of room for improvement in performance of the `int_pow` family of methods. I added benchmarks for those functions. In particular, there are benchmarks for small compile-time bases to measure the effect of  #114390. ~~I added a lot (245), but all but 22 of them are marked with `#[ignore]`. There are a lot of macros, and I would appreciate feedback on how to simplify them.~~

~~To run benches relevant to #114390, use `./x bench core --stage 1 -- pow_base_const --include-ignored`.~~

### CODE REVIEW

**Comment by NCGThompson** [comment]
Surprisingly, at least on Aarch64, checked pow unwrapped is very slightly faster than wrapping pow, while checked pow unwrapped unchecked is among the slowest. I guessed the assume statement produced from the unwrap unchecked seems to be helping more than it is hurting. I found a way to unwrap it without generating an assume statement.
```rust
*option.as_slice().as_ptr().cast::<$t>()
```
When I benched it though, and it was significantly slower than the unwrap uncheck.

On Aarch64 but not x86_64, overflowing i128 is dramatically (~5x) slower than overflowing u128. This is because on Aarch64, signed overflowing multiply does a compuler-rt function call while unsigned overflowing multiply is inlined. I'll have to check what happens on other architectures with Compiler Explorer. To work around this, we can take advantage of the fact that any integer to an even power is non-negative. I've already wrote a similar algorithm in Rust before.

**Comment by NCGThompson** [comment]
`./x fmt` is the reason some `pow_bench_template!` calls are a single line and others have the arguments listed vertically. I know it is inconsistent. Should I leave it the way `./x fmt` likes it or should I somehow override it?

**Comment by NCGThompson** [comment]
@cuviper Updated based on your feedback. I also rebased and force-pushed it.

**Comment by cuviper** [comment]
Looks good, thanks!

@bors r+ rollup

**Comment by NCGThompson** [comment]
> @bors retry

Is this definitely a random error, or could it have anything to do with my changes? If I interpreted the logs correctly, it was the drift test that failed, and that seems unrelated to the changes.

**Comment by cuviper** [comment]
This message comes on occasionally on that particular runner, unrelated to any PR changes:

> ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

**Comment by NCGThompson** [comment]
@cuviper  Is there a way to run or view the results of the library benchmarks on all the platforms that the CI tests?

**Comment by cuviper** [comment]
Most of the targets are cross-compiled in CI, and AFAIK we don't even run those benchmarks on native targets in CI. They're really only useful for developers to run.

For more holistic benchmarking, see https://perf.rust-lang.org/ (source https://github.com/rust-lang/rustc-perf)

**Pull request merged**
