### PR TITLE
Make the `unix::net::SocketAddr` creation methods public

### PR DESCRIPTION
**Pull request by kleimkuhler**
## Motivation

Recently [tokio-rs/mio](https://github.com/tokio-rs/mio/) needed support for creating the
`std::os::unix::net::SocketAddr` type. While the type is currently public, it is
not possible to create one as both creation methods are private:

* [SocketAddr::new](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/ext/net.rs#L109)
* [SocketAddr::from_parts](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/ext/net.rs#L120)

The workaround was creating a `mio` specific `SocketAddr` that is equivalent to
this type.

A use of needing `SocketAddr::from_parts` is shown [here](https://github.com/tokio-rs/mio/blob/master/src/sys/unix/uds/listener.rs#L101).

## Details

This PR makes the creation methods public so that the already public type can be
created as well. Comments with examples have been added.

I did not feel an RFC process was needed for this; I hope that assumtion is
correct!

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

**Comment by jonas-schievink** [comment]
These need `#[unstable]` attributes

**Comment by KodrAus** [comment]
Hmm, in their current state I don’t think the `new` or `from_parts` methods are really suitable in the public API because they expose external `libc` types, and I find the signature for `new` a little surprising as anything but an implementation detail.

It looks like we do have some examples of defining `libc` types with friendlier names though, like [`RawPthread`](https://doc.rust-lang.org/std/os/unix/thread/type.RawPthread.html). The `sockaddr_un` type isn’t just a simple alias though.

So I think we’ll need to sketch out a more suitable public API for constructing `SocketAddr`s than what’s currently there first, that doesn’t publicly use `libc` and has appropriate safety.

**Comment by sfackler** [comment]
Why can't mio just use the standard library's UnixListener? https://doc.rust-lang.org/std/os/unix/net/struct.UnixListener.html

**Comment by kleimkuhler** [comment]
@sfackler It is mainly because `accept` on `Socket` which `UnixListener::accept` dispatches to does not set the `O_NONBLOCK` flag. It can be done with a separate `fcntl` call after the socket is returned, but then that is an additional call that needs to take place. We can use `accept4` on the  OSs that support it and set these flags atomically.

**Comment by kleimkuhler** [comment]
@KodrAus That is a good point. I found the signatures a little surprising when first looking at them. If exposing `libc` types is an issue, there would definitely need to be some additional design around the fields returned in `SocketAddr`. I can close this PR for now if additional discussion should take place in the issue? It would be nice to use `libstd` when possible, but this understandably isn't going to be solved just by making these methods public.

**Comment by KodrAus** [comment]
@kleimkuhler that sounds like a good plan me to! Maybe we can also look at whether it’s feasible for `mio` to move to the standard `UnixListener` and what might need to be added to support it?

**Comment by kleimkuhler** [comment]
@KodrAus So it's not just `UnixListener` that `mio` has to special case all this for, it's pretty much all the `net` resources that would be expected to not block when no read/write is available.

This ultimately is because the sockets need this additional flag set _as part_ of the socket creation instead of a separate call to `libstd`'s `set_nonblocking`. Maybe there is some design discussion for offering this through `libstd`, but it definitely would be a larger change!

Closing this PR per discussion above and further conversation can take place in #65275.

**Pull request closed without merging**
