### PR TITLE
Don't suggest `&mut mut`

### LINKED ISSUE #57431: `&mut &T` coerced to `&T` suggests `&mut mut x`
This code:
```rust
struct X;
impl X {
    fn mutate(&mut self) {}
}

fn main() {
    let term = Some(X);
    let term = match &term {
        Some(term) => &mut term,
        None => term.as_ref().unwrap(),
    };
    term.mutate();
}
```

Produces these errors:
```
error[E0596]: cannot borrow `term` as mutable, as it is not declared as mutable
 --> src/main.rs:9:23
  |
9 |         Some(term) => &mut term,
  |                       ^^^^^^^^^
  |                       |
  |                       cannot borrow as mutable
  |                       try removing `&mut` here

error[E0596]: cannot borrow `*term` as mutable, as it is behind a `&` reference
  --> src/main.rs:12:5
   |
9  |         Some(term) => &mut term,
   |                       --------- help: consider changing this to be a mutable reference: `&mut mut term`
...
12 |     term.mutate();
   |     ^^^^ `term` is a `&` reference, so the data it refers to cannot be borrowed as mutable

error: aborting due to 2 previous errors
```

Note that the second error suggests changing `&mut term` to `&mut mut term`, which obviously won't fix the issue.

### PR DESCRIPTION
**Pull request by saleemjaffer**
Don't suggest `&mut mut` for `&mut &T` coerced to `&T`; fixes rust-lang/rust#57431

### CODE REVIEW

**Comment by cramertj** [comment]
Can you add a UI test including the testcase from the original issue?

**Comment by NieDzejkob** [comment]
Comparing the code like this is a bad idea. Consider `& mut` - perfectly valid, if a bit unusual. Moreover, there's `&'a mut`. This should really be matched on some deeper level like the AST or MIR.

Take the above with a grain of salt, though, I'm not terribly familiar with this codebase.

**Comment by saleemjaffer** [comment]
@NieDzejkob Yeah you are right. [This](https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/.2357431) is where we are discussing how to solve this issue.

**Comment by pnkfelix** [comment]
I'm going to go ahead and close this PR. The issue itself even says [don't use regexp-matching](https://github.com/rust-lang/rust/issues/57431#issuecomment-461105743), which includes as (a special case) string-matching as was done here.

**Pull request closed without merging**
