### PR TITLE
std: use `sync::RwLock` for internal statics

### PR DESCRIPTION
**Pull request by joboet**
Since `sync::RwLock` is now `const`-constructible, it can be used for internal statics, removing the need for `sys_common::StaticRwLock`. This adds some extra allocations on platforms which need to box their locks (currently SGX and some UNIX), but these will become unnecessary with the lock improvements tracked in #93740.

### CODE REVIEW

**Comment by thomcc** [comment]
I'm not a fan of making this change (or the one in https://github.com/rust-lang/rust/pull/100579). Can we instead change StaticMutex/StaticRwlock to use the locks internally on platforms where that impl isn't worse?

**Comment by thomcc** [comment]
It looks like we use this for the environment lock, and for the panic hook. I don't really feel like either of these are likely to be hot enough for the extra allocation to matter, so I'm not sure how much I actually care here now that I look.

r? @thomcc

**Comment by thomcc** [comment]
This looks fine. This does actually introduce a branch even on OSes with the good locks (due to the poison error handling). I doubt it matters but is probably worth preventing a rollup as a result.

@bors r+ rollup=never

**Comment by thomcc** [comment]
And for good measure,

@bors delegate+

**Comment by joboet** [comment]
That looks like a spurious failure...
@bors r=thomcc

**Pull request merged**
