### PR TITLE
[WIP] Pietro's CI playground

### LINKED ISSUE #85042: Please ignore this issue
Need to experiment a bit with a feature, please ignore this, thanks!

### PR DESCRIPTION
**Pull request by emilyalbini**
Surprisingly there is nothing interesting going on here!

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Let's see how 14 cores perform.

@bors retry

**Comment by pietroalbini** [comment]
I'm back with the CI noise!

@bors try

**Comment by Dylan-DPC** [comment]
converted this as draft

**Comment by pietroalbini** [comment]
Wat.

@bors retry

**Comment by pietroalbini** [comment]
Gah.

@bors try

**Comment by jyn514** [comment]
@rustbot label: +this-label-does-not-exist

(for https://github.com/rust-lang/triagebot/issues/1066)

**Comment by jyn514** [comment]
Hmm, I think it may have crashed?

@rustbot modify labels +waiting-for-review

**Comment by JohnCSimon** [comment]
@pietroalbini 
Ping from triage: I'm closing this due to inactivity,

@rustbot label: +S-inactive

**Pull request closed without merging**
