### PR TITLE
 bootstrap: support target specific config overrides 

### PR DESCRIPTION
**Pull request by weihanglo**
Can't find any previous discussion about not supporting this,
so I get it done.

The motivation of this is from <https://github.com/rust-lang/rust/pull/125473#issuecomment-2129954990>.

### CODE REVIEW

**Comment by weihanglo** [comment]
> This PR modifies `src/bootstrap/src/core/config`.
> 
> If appropriate, please update `CONFIG_CHANGE_HISTORY` in `src/bootstrap/src/utils/change_tracker.rs`.

This doesn't really change any schema of `config.toml`, so probably don't need to update? Not sure though.

**Review by onur-ozkan — APPROVED** [review]
> This doesn't really change any schema of config.toml, so probably don't need to update? Not sure though.

Yeah, update isn't needed for this.

**Comment by weihanglo** [comment]
Thanks for the review!

@bors r=onur-ozkan rollup

**Comment by workingjubilee** [comment]
This is the only one that seems like it can explain the failure in `fixes_missing_ampersand`: https://github.com/rust-lang/rust/pull/125533#issuecomment-2131051546

but I still don't know how...

@bors iffy

**Comment by workingjubilee** [comment]
This is the only one that seems like it can explain the failure in `fixes_missing_ampersand`: https://github.com/rust-lang/rust/pull/125533#issuecomment-2131051546

but I still don't know how...

@bors rollup=iffy

**Comment by Urgau** [comment]
@workingjubilee I don't think it's this PR fault that the rollup failed. The more likely explanation given the [source code](https://github.com/rust-lang/cargo/blob/a8d72c675ee52dd57f0d8f2bae6655913c15b2fb/tests/testsuite/fix.rs#L504-L545) is https://github.com/rust-lang/rust/pull/125433.

**Comment by surechen** [comment]
> @workingjubilee I don't think it's this PR fault that the rollup failed. The more likely explanation given the [source code](https://github.com/rust-lang/cargo/blob/a8d72c675ee52dd57f0d8f2bae6655913c15b2fb/tests/testsuite/fix.rs#L504-L545) is #125433.

It certainly seems so. My PR would check 
```rust
fn main() { let mut x = 3; drop(x); }
```

Where should the repairs be made to make them suitable?

**Comment by Urgau** [comment]
> Where should the repairs be made to make them suitable?

In the Cargo repository, by submitting a PR fixing the test https://github.com/rust-lang/cargo/blob/a8d72c675ee52dd57f0d8f2bae6655913c15b2fb/tests/testsuite/fix.rs#L504-L545

**Comment by onur-ozkan** [comment]
> error: failed retrieving file 'mingw-w64-x86_64-headers-git-11.0.0.r547.g4c8123efb-1-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
> error: failed retrieving file 'mingw-w64-x86_64-gdb-14.1-1-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
> error: failed retrieving file 'mingw-w64-x86_64-crt-git-11.0.0.r547.g4c8123efb-1-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
> warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
> error: failed retrieving file 'mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst.sig' from mirror.umd.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
>  mingw-w64-x86_64-python-3.11.7-1-any downloading...
>  mingw-w64-x86_64-gcc-ada-13.2.0-3-any downloading...
>  mingw-w64-x86_64-gcc-objc-13.2.0-3-any downloading...
> warning: failed to retrieve some files

Seems like a temporary network problem. @bors retry

**Comment by workingjubilee** [comment]
@Urgau Oh.

Why don't we run that test in the PR CI...?

**Comment by weihanglo** [comment]
@workingjubilee 

It checks too much stuff I guess?

These are additional stuff we need to test 

https://github.com/rust-lang/rust/blob/606afbb617a2949a4e35c4b0258ff94c980b9451/src/bootstrap/mk/Makefile.in#L50-L82

**Pull request merged**
