### PR TITLE
Require Debug for Pointee::Metadata

### PR DESCRIPTION
**Pull request by stepancheg**
Useful for debugging.

### CODE REVIEW

**Comment by joboet** [comment]
r? libs-api

**Comment by jhpratt** [comment]
Diff LGTM, but I'll leave the decision to the team, as that's not my purview.

**Comment by the8472** [comment]
@Amanieu are you sure you got the right person or the right issue? I'm not -api


But since I'm looking at it I might as well comment. The feature is unstable and already requires `Hash` and `Ord` which may not be super-trivial so `Debug` doesn't seem too onerous on top. The only source of doubt I have is that I don't know which additional metadata types we might gain in the future (for custom DSTs? pointers wider than 2 usizes have been discussed somewhere...) and the fewer constraints we impose on those the better, maybe...

**Comment by Amanieu** [comment]
Sorry I should have clarified. I don't have any opinions on this, but I believe you did some work related to pointer metadata so you may have more context. If you're happy with this, you can just go ahead and merge it.

**Comment by the8472** [comment]
I'm working on niches for usize pointer metadata, which is only vaguely related since it doesn't affect the user-visible types. If you don't see any issues with API forward-compat then sure...

@bors r=the8472,Amanieu

**Pull request merged**
