### PR TITLE
Add option to enable MIR inlining independently of mir-opt-level

### PR DESCRIPTION
**Pull request by tmiasko**
Add `-Zinline-mir` option that enables MIR inlining independently of the
current MIR opt level. The primary use-case is enabling MIR inlining on the
default MIR opt level.

Turn inlining thresholds into optional values to make it possible to configure
different defaults depending on the current mir-opt-level (although thresholds
are yet to be used in such a manner).

### CODE REVIEW

**Comment by tmiasko** [comment]
Rebased.

**Comment by oli-obk** [comment]
Feel free to r=reviewer in the future when the sole change was a rebase and minor fixes

@bors r+

**Pull request merged**
