### PR TITLE
Check the number of arguments first in `is_recursive_call`

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Seems to have [entirely fixed the regression](https://perf.rust-lang.org/compare.html?start=563250a65c884c6767dc2ee2e2580360d33d561c&end=c8a909af71d1fc4059328c1f9f91b03e269f85e8) in #92889. Sweet!

@tmiasko could you add a comment to the early return indicating that it's for performance reasons? r=me when that is done.

**Comment by tmiasko** [comment]
Added comment describing performance rationale for the check.

Pull request CI failure is unrelated #93384.

@bors r=ecstatic-morse rollup=never

**Pull request merged**
