### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by brson**
- https://github.com/rust-lang/rust/pull/43068
- https://github.com/rust-lang/rust/pull/43043
- https://github.com/rust-lang/rust/pull/42745

The pick of https://github.com/rust-lang/rust/pull/42745/commits/143206d54d7558c2326212df99efc98110904fdb in https://github.com/rust-lang/rust/pull/43114/commits/cfa3b58f9c43143e71135dd11931ca1a25846da7 was not clean and needed a fair bit of surgery. It should probably be looked at closely.

Still testing locally.

### CODE REVIEW

**Comment by sfackler** [comment]
This should probably include #42991

**Comment by durka** [comment]
@sfackler you also said at #42991 you were going to un-revert the `Bounds` move, did that happen?

**Comment by brson** [comment]
Instead of picking the revert, I just removed the original pick, which was unclean and didn't build. @sfackler does this look right now?

**Comment by alexcrichton** [comment]
@bors: r-

tidy failure :(

**Comment by kennytm** [comment]
Please consider including #43198 as well, otherwise the Android CI will not pass.

**Comment by Mark-Simulacrum** [comment]
Pacified tidy and pulled in #43198.

@bors r+ p=50

**Comment by Mark-Simulacrum** [comment]
`[00:50:40] 'C:\projects\rust\src/doc\unstable-book\src\library-features/reverse-cmp-key.md' referenced from SUMMARY.md` I suspect it's all of them

**Comment by kennytm** [comment]
`dist-mips-linux` failed to deploy.

```
Installing deploy dependencies
ERROR:  Could not find a valid gem 'aws-sdk-core' (= 2.10.11) in any repository
```

**Pull request merged**
