### PR TITLE
Reduce a Code Repetition Related to Bit Operation

### PR DESCRIPTION
**Pull request by kenta7777**
This PR is related to [#49937](https://github.com/rust-lang/rust/issues/49937).
Should I do more commits about [`FIXME(49937)`](https://github.com/rust-lang/rust/search?q=FIXME%2849937%29&unscoped_q=FIXME%2849937%29) in this PR?

### CODE REVIEW

**Comment by kenta7777** [comment]
Could you review this PR? @oli-obk 
r? @oli-obk

**Comment by oli-obk** [comment]
> Should I do more commits

If you want. But we can also just rollup these PRs. Whatever suits you best

@bors r+ rollup

**Comment by kenta7777** [comment]
I don't know how to refactor [this](https://github.com/rust-lang/rust/blob/26b4cb48484382032522384318e70ceb0fbc4a41/src/librustc_mir/hair/pattern/_match.rs#L681). Prease give me some hints to resolve it.

**Comment by oli-obk** [comment]
Good question. I think those are already pretty ideal. As long as there aren't any other computations like these (in which case we should create new functions that deduplicate the code) we should just keep the code. At best you can rewrite the `max` computation as `let max = min - 1;`

**Comment by kenta7777** [comment]
Thank you for answering. 
Then, I'll rewrite `let max = (1u128 << (bits - 1)) - 1;` as `let max = min - 1;` and remove the comment.

**Comment by kenta7777** [comment]
I think there might be more code should be refactored, but I want to merge these commits because all the codes marked as [`FIXME(49937)`](https://github.com/rust-lang/rust/search?q=FIXME%2849937%29&unscoped_q=FIXME%2849937%29) were fixed.

**Comment by kenta7777** [comment]
thanks!

**Pull request merged**
