### PR TITLE
Update `compiler_builtins` to 0.1.39

### PR DESCRIPTION
**Pull request by JohnTitor**
This version contains the fixes of https://github.com/rust-lang/compiler-builtins/issues/390 and https://github.com/rust-lang/compiler-builtins/issues/391.
Also, rename features following https://github.com/rust-lang/compiler-builtins/pull/386.

### CODE REVIEW

**Comment by Amanieu** [comment]
Assembly code in compiler-builtins needs to be switched to use AT&T syntax since Intel syntax doesn't work on the old LLVM (8.0) used in CI.

**Comment by JohnTitor** [comment]
Failed on tidy but seems rust-lang/compiler-builtins#396 works fine anyway.

@Amanieu Sorry for requesting twice but could you make a new release? I think we can go ahead now.

**Comment by Amanieu** [comment]
Are you sure? The main CI job got canceled when tidy failed.

**Comment by JohnTitor** [comment]
Yeah, let's check the CI log:

1. The first build is stopped in building stage1 std: https://github.com/rust-lang/rust/runs/1526351720
2. This time building stage1 std is fine and the build is canceled when building stage1 compiler: https://github.com/rust-lang/rust/pull/79863/checks?check_run_id=1539786119

So the previous failure should be fixed and I think it's worth giving it a try.
If you want, I'm happy to remove the tidy check for testing, though.

**Comment by Amanieu** [comment]
Published 0.1.38

**Comment by JohnTitor** [comment]
Thanks! Now CI is green.

**Comment by JohnTitor** [comment]
Failed in https://github.com/rust-lang-ci/rust/runs/1543672364:

```
 rustc exited with signal: 11
error: could not compile `compiler_builtins`

Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name compiler_builtins /cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.38/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C codegen-units=10000 -C debuginfo=1 --cfg 'feature="c"' --cfg 'feature="cc"' --cfg 'feature="compiler-builtins"' --cfg 'feature="core"' --cfg 'feature="default"' --cfg 'feature="mem"' --cfg 'feature="rustc-dep-of-std"' -C metadata=11825feb351d960e -C extra-filename=-11825feb351d960e --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/aarch64-unknown-none-softfloat/release/deps --target aarch64-unknown-none-softfloat -C linker=aarch64-none-elf-gcc -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/aarch64-unknown-none-softfloat/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/release/deps --extern core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/aarch64-unknown-none-softfloat/release/deps/librustc_std_workspace_core-7dd4080a03583e8c.rmeta --cap-lints allow -Zmacro-backtrace '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Cprefer-dynamic -Cembed-bitcode=yes -Z binary-dep-depinfo -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/aarch64-unknown-none-softfloat/release/build/compiler_builtins-cf9517a58eb87178/out --cfg 'feature="unstable"' --cfg 'feature="mem"' --cfg '__absvdi2="optimized-c"' --cfg '__absvsi2="optimized-c"' --cfg '__absvti2="optimized-c"' --cfg '__addvdi3="optimized-c"' --cfg '__addvsi3="optimized-c"' --cfg '__addvti3="optimized-c"' --cfg '__clzdi2="optimized-c"' --cfg '__clzsi2="optimized-c"' --cfg '__clzti2="optimized-c"' --cfg '__cmpdi2="optimized-c"' --cfg '__cmpti2="optimized-c"' --cfg '__comparetf2="optimized-c"' --cfg '__ctzdi2="optimized-c"' --cfg '__ctzsi2="optimized-c"' --cfg '__ctzti2="optimized-c"' --cfg '__divdc3="optimized-c"' --cfg '__divsc3="optimized-c"' --cfg '__divxc3="optimized-c"' --cfg '__extenddftf2="optimized-c"' --cfg '__extendhfsf2="optimized-c"' --cfg '__extendsftf2="optimized-c"' --cfg '__ffsti2="optimized-c"' --cfg '__fixtfdi="optimized-c"' --cfg '__fixtfsi="optimized-c"' --cfg '__fixtfti="optimized-c"' --cfg '__fixunstfdi="optimized-c"' --cfg '__fixunstfsi="optimized-c"' --cfg '__fixunstfti="optimized-c"' --cfg '__floatditf="optimized-c"' --cfg '__floatsitf="optimized-c"' --cfg '__floatunditf="optimized-c"' --cfg '__floatunsitf="optimized-c"' --cfg '__int_util="optimized-c"' --cfg '__muldc3="optimized-c"' --cfg '__mulsc3="optimized-c"' --cfg '__multc3="optimized-c"' --cfg '__mulvdi3="optimized-c"' --cfg '__mulvsi3="optimized-c"' --cfg '__mulvti3="optimized-c"' --cfg '__mulxc3="optimized-c"' --cfg '__negdf2="optimized-c"' --cfg '__negdi2="optimized-c"' --cfg '__negsf2="optimized-c"' --cfg '__negti2="optimized-c"' --cfg '__negvdi2="optimized-c"' --cfg '__negvsi2="optimized-c"' --cfg '__negvti2="optimized-c"' --cfg '__paritydi2="optimized-c"' --cfg '__paritysi2="optimized-c"' --cfg '__parityti2="optimized-c"' --cfg '__popcountdi2="optimized-c"' --cfg '__popcountsi2="optimized-c"' --cfg '__popcountti2="optimized-c"' --cfg '__powixf2="optimized-c"' --cfg '__subvdi3="optimized-c"' --cfg '__subvsi3="optimized-c"' --cfg '__subvti3="optimized-c"' --cfg '__truncdfhf2="optimized-c"' --cfg '__truncdfsf2="optimized-c"' --cfg '__truncsfhf2="optimized-c"' --cfg '__trunctfdf2="optimized-c"' --cfg '__trunctfsf2="optimized-c"' --cfg '__ucmpdi2="optimized-c"' --cfg '__ucmpti2="optimized-c"' --cfg 'apple_versioning="optimized-c"' -l static=compiler-rt` (exit code: 254)
warning: build failed, waiting for other jobs to finish...
[RUSTC-TIMING] alloc test:false 3.366
[RUSTC-TIMING] core test:false 19.307
error: build failed
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "aarch64-unknown-none-softfloat" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--locked" "--color" "always" "-p" "alloc" "--manifest-path" "/checkout/library/alloc/Cargo.toml" "--features" "compiler-builtins-mem compiler-builtins-c" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap dist --host= --target asmjs-unknown-emscripten,wasm32-unknown-emscripten,x86_64-rumprun-netbsd,mips-unknown-linux-musl,mipsel-unknown-linux-musl,mips64-unknown-linux-muslabi64,mips64el-unknown-linux-muslabi64,arm-unknown-linux-musleabi,arm-unknown-linux-musleabihf,armv5te-unknown-linux-gnueabi,armv5te-unknown-linux-musleabi,armv7-unknown-linux-musleabihf,aarch64-unknown-none,aarch64-unknown-none-softfloat,sparc64-unknown-linux-gnu,x86_64-unknown-redox,thumbv6m-none-eabi,thumbv7m-none-eabi,thumbv7em-none-eabi,thumbv7em-none-eabihf,thumbv8m.base-none-eabi,thumbv8m.main-none-eabi,thumbv8m.main-none-eabihf,riscv32i-unknown-none-elf,riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf,riscv64imac-unknown-none-elf,riscv64gc-unknown-none-elf,armebv7r-none-eabi,armebv7r-none-eabihf,armv7r-none-eabi,armv7r-none-eabihf,thumbv7neon-unknown-linux-gnueabihf,armv7a-none-eabi
Build completed unsuccessfully in 0:22:57
```

@bors r-

**Comment by AaronKutch** [comment]
I removed `u128::count_ones` references from `compiler-builtins`. Can this make it into 1.51?

**Comment by JohnTitor** [comment]
Let's check the build on dist-various-1 and dist-various-2.
@bors try

**Comment by JohnTitor** [comment]
The try build is green, I think we could give it another try (and it lands hopefully) @Amanieu. Thanks @AaronKutch for fixing it.

**Comment by Amanieu** [comment]
@bors r-

Oops, need to publish a new release first.

**Comment by Amanieu** [comment]
Published 0.1.39

**Comment by JohnTitor** [comment]
Thanks! Updated to 0.1.39.

**Comment by bjorn3** [comment]
@bors r+ rollup=never

Compiler-builtins updates have historically caused problems, so don't rollup to help with bisecting.

**Pull request merged**
