### PR TITLE
Avoid some redundant work in GVN

### PR DESCRIPTION
**Pull request by cjgillot**
The first 2 commits are about reducing the perf effect.

Third commit avoids doing redundant work: is a local is SSA, it already has been simplified, and the resulting value is in `self.locals`. No need to call any code on it.

The last commit avoids removing some storage statements.

r? wg-mir-opt

### CODE REVIEW

**Comment by cjgillot** [comment]
r? wg-mir-opt

**Comment by cjgillot** [comment]
Shutdown signal, no visible reason.
@bors retry

**Comment by pnkfelix** [comment]
* primary regressions are regex-1.5.5 debug-full, opt-incr-patched:Job, incr-full, and exa opt-full.
* the exa regression looks like a blip. The regex ones were predicted during a try run for the PR. I assume they were deemed acceptable as they are offset improvements elsewhere (or dismissed as noise?)
* marking as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
