### PR TITLE
Remove str::Pattern impl for &[char]

### PR DESCRIPTION
**Pull request by Kimundi**
Provisional patch to address one of the issues in https://github.com/rust-lang/rfcs/issues/1039

[breaking-change]

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'm curious if there are many crates relying on this functionality today, because while I'd love to remove this, it's also not necessarily the worst thing in the world to live with. 

@brson, would it be possible to see if this regresses a large number of crates on crates.io?

**Comment by kballard** [comment]
As I just commented in rust-lang/rfcs#1039, I'm not convinced that we should be removing this. The ergonomics may not be as good as they used to be, but the functionality is still valid. I'd rather not have to use a function with a custom `match` just because I want to match either `'\r'` or `'\n'`.

**Comment by Kimundi** [comment]
@kballard: A pattern like `&['\r', '\n'][..]` can be equivalently be replaced with `|c| ['\r', '\n'].contains(&c)` or `|c| "\r\n".contains(c)`. No custom match function necessary.

**Comment by kballard** [comment]
@Kimundi Ok true, I don't need `match` specifically, but it's still not as nice. And in theory it's not as performant, as using `&['\r', '\n'][..]` detects that all the `char`s are ASCII, although that optimization seems to have vanished (`CharEqSearcher` still has the `ascii_only` field, but it's marked as dead code; I hope the intention was to resurrect that optimization later).

**Comment by alexcrichton** [comment]
Ok, it looks like there's some use cases for keeping this, and it's not doing much harm, so I think we're going to leave this in for 1.0. We can explore expanding the set of implementors on https://github.com/rust-lang/rfcs/issues/1039.

**Pull request closed without merging**
