### PR TITLE
Shrink `hir::Ty` and `hir::Pat`

### PR DESCRIPTION
**Pull request by nnethercote**
r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
There is a lot of noise in the benchmark suite at the moment, but after looking in detail at the cycles and max-rss results I am confident that there is a small but real performance improvement here, and it is worth proceeding.

r? @spastorino

**Comment by spastorino** [comment]
@nnethercote looks good. Saw that you have force pushed some stuff after running perf, unsure if you wanted to run perf again but in one case or another feel free to r=me when you think it's ready.

**Comment by nnethercote** [comment]
Ha ha, this one is ready, thanks!

@bors r=spastorino

**Comment by nnethercote** [comment]
Rebased.

@bors r=spastorino

**Comment by nnethercote** [comment]
The `html5ever` regressions are noise, otherwise, this is very slightly perf-positive.

@rustbot label: +perf-regression-triaged

**Pull request merged**
