### PR TITLE
Stabilize LocalKey::try_with

### LINKED ISSUE #27716: Tracking issue for `thread_local_state` stabilization
This feature allows you to query a thread-local variable for its state: http://static.rust-lang.org/doc/master/std/thread/enum.LocalKeyState.html, which will then tell you what may happen if you try to read from the variable.

The functionality is somewhat niche, but occasionally essential. The APIs appear to be in pretty decent shape as-is.

cc @alexcrichton

### PR DESCRIPTION
**Pull request by ghost**
The `LocalKey::try_with` method is now stabilized.

`LocalKey::state` and `LocalKeyState` marked as deprecated. Although, is there any reason to keep them - should we perhaps remove them completely?

Closes #27716 

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like there may be a tidy error though?

**Comment by stjepang** [comment]
I had to switch `LocalKey::try_with` from feature `thread_local_state` to a new feature `thread_local_try_with` because tidy wants the whole future either stabilized or not.

Should be ok now.

**Comment by alexcrichton** [comment]
Oh hm looks like libstd is still using the deprecated items?

**Comment by stjepang** [comment]
Passes on Travis now.

It seems `LocalKeyState` is only used by function [`print_to`](https://github.com/stjepang/rust/blob/c99f4c4c5b9f968b82037cf643b6662b140d9b1f/src/libstd/io/stdio.rs#L674), which is called from macros `print!` and `eprint!`.

Do you think I should purge `LocalKeyState` from `libstd`? Is there any reason to deprecate, but still keep it?

**Comment by alexcrichton** [comment]
Nah I'd actually personally be on board with a complete removal of `LocalKeyState` if we can, the `print_to` function looks like it can for sure use `try_with`!

**Comment by alexcrichton** [comment]
Looks like a libstd test may be failing?

**Comment by stjepang** [comment]
Fixed. It was just a silly misstake - I accidentally deleted the `HITS += 1` line.

**Pull request merged**
