### PR TITLE
Add `A: 'static` bound for `Arc/Rc::pin_in`

### PR DESCRIPTION
**Pull request by zetanumbers**
Analogous to https://github.com/rust-lang/rust/pull/79327
Needed to preserve pin's [drop guarantee](https://doc.rust-lang.org/std/pin/index.html#drop-guarantee)

### CODE REVIEW

**Comment by joshtriplett** [comment]
r? libs-api

**Comment by RalfJung** [comment]
This seems like something that needs a comment somewhere to explain these bounds -- someone just finding them in the code might be very confused about why they are needed.

**Comment by Amanieu** [comment]
@bors r-

@zetanumbers Can you add a comment explaining why this is needed? Also add it to the original `Box::pin_in`,

**Comment by zetanumbers** [comment]
So it's a bit tricky to argue what bounds should be on `Arc::pin_in` because I don't see any practical use of it (or `Pin<Arc<T>>` in general) *right now*.

So https://github.com/rust-lang/rust/pull/79327 was justified because it violates pin's [drop guarantee](https://doc.rust-lang.org/std/pin/index.html#drop-guarantee), which says that memory that holds pointee of a pinned (smart) pointer is allowed to be deallocated **only** after dropping the pointee, unless pointee is `!Unpin`. This guarantee to some extend can allow, for example, to send a pointer to a buffer allocated inside of the future's local state to write some data to it. It is also needed for [hypothetical](https://zetanumbers.github.io/leak-playground/leak_playground_std/) scoped async tasks and scoped thread join handles in particular to be able to safely capture references to future's local state (see proposal's [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/The.20destruction.20guarantee.20and.20linear.20types.20formulation)).

So why is there even `Arc::pin`? `Arc` does not implement `DerefMut`, so to be honest I hardly see any reasonable use case. Except for one hypothetical functionality:

```rust
fn pin_arc_get_mut(this: &mut Pin<Arc<T>>) -> Option<Pin<&mut T>> {
  // implementation
}
```

**Comment by zetanumbers** [comment]
So I say it would probably will never be less beneficial to have this bound, since `Pin<Arc<T>>` is useless otherwise anyway. That unless someone already deemed it reasonable to implement that `pin_arc_get_mut`. :)

**Comment by zetanumbers** [comment]
Actually I would like to add this `Arc::get_pin_mut` as a static method. I assume that would require RFC, right?

**Comment by Amanieu** [comment]
It would require an [ACP](https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html), along with a real use case for it.

**Comment by Amanieu** [comment]
It would require an [ACP](https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html), along with a real use case for it.

For this PR, I think just a simple sentence saying that `Pin` requires that the underlying allocation be leaked if a pinned object is leaked, which is only possible for `A: 'static`.

**Comment by zetanumbers** [comment]
> So why is there even `Arc::pin`? `Arc` does not implement `DerefMut`, so to be honest I hardly see any reasonable use case. Except for one hypothetical functionality:
> 
> ```rust
> /// This is kinda like `Arc::get_mut` but with `Pin`
> fn pin_arc_get_mut(this: &mut Pin<Arc<T>>) -> Option<Pin<&mut T>> {
>   // implementation
> }
> ```

I have come to a such feature would be unsound. Actually I believe `Arc::pin` is practically useless since you can unpin any arc with simple `Arc::clone`. Thus `Arc::pin` should be deprecated.

**Comment by RalfJung** [comment]
A comment in a closed PR is likely to be lost. It's better to open an issue or a discussion on Zulip - with more details on why the function is useless, maybe doing some code search on the web to find existing uses.

**Pull request merged**
