### PR TITLE
proc_macro bridge fxhash perf testing

### PR DESCRIPTION
**Pull request by lukas-code**
results:

* updating to `rustc-hash` v2: no changes: https://github.com/rust-lang/rust/pull/134434#issuecomment-2549663484
* replacing it with the default hasher: minor regression in a stress test: https://github.com/rust-lang/rust/pull/134434#issuecomment-2550052311

### CODE REVIEW

**Comment by lukas-code** [comment]
hmm, no changes at at all. let's see if we can just use the default hasher then: @bors try @rust-timer queue

**Comment by tgross35** [comment]
I wonder if the perf suite just isn't exercising proc macros very much. Using the builtin `HashMap` would be a nice cleanup if there aren't any significant regressions.

**Comment by lukas-code** [comment]
I was just about to close, but if you want to keep this, then r? @tgross35 i guess

**Comment by tgross35** [comment]
Well, the regressions aren't huge but probably enough that removing ~100 LOC isn't worth it. I guess you can close this if that was what you intended.

**Comment by lukas-code** [comment]
Alright, closing then.

**Pull request closed without merging**
