### PR TITLE
Edit error messages for `rustc_resolve::AmbiguityKind` variants

### LINKED ISSUE #79717: Ambiguous name error message has weird wording
```rust
mod serde {}

use serde::foo;
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f65bf7e111dd7ac8f3c871058e9b1b72))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0432]: unresolved import `serde::foo`
 --> src/lib.rs:3:5
  |
3 | use serde::foo;
  |     ^^^^^^^^^^ no `foo` in `serde`

error[E0659]: `serde` is ambiguous (name vs any other name during import resolution)
 --> src/lib.rs:3:5
  |
3 | use serde::foo;
  |     ^^^^^ ambiguous name
  |
  = note: `serde` could refer to a crate passed with `--extern`
  = help: use `::serde` to refer to this crate unambiguously
note: `serde` could also refer to the module defined here
 --> src/lib.rs:1:1
  |
1 | mod serde {}
  | ^^^^^^^^^^^^
  = help: use `crate::serde` to refer to this module unambiguously

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0659.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

The error message says:

> `serde` is ambiguous (name vs any other name during import resolution)

But what does it mean by "name vs any other name during import resolution"? I think this should be reworded or even deleted – it doesn't seem to add anything.

### PR DESCRIPTION
**Pull request by pierwill**
Edit the language of the ambiguity descriptions for E0659. These strings now appear as notes.

Closes #79717.

### CODE REVIEW

**Comment by camelid** [comment]
@pierwill you need to bless tests :)

**Comment by pierwill** [comment]
I'll take another look at these, @camelid.

**Comment by camelid** [comment]
Stepping back a bit, I think it might be better if these notes were displayed as actual `note`s, rather than in parentheses in the main message. I'm not sure what others think, but do you want to try changing that and see how it looks?

Basically, I'm envisioning something like this:

```
error: `foo` is ambiguous
   --> $INFO
    |
$LL | $SRC_CODE
    |
    = note: ambiguous due to conflicts between ...
```

**Comment by pierwill** [comment]
Tests pass locally with `err.note`. 🎉

**Comment by pierwill** [comment]
Whoops. Tagged for right before a new crop of failures. 😬

**Review by camelid — COMMENTED** [review]
I left a few comments on some changes that I felt could be made more informative. In general, some of the existing descriptions included "during import/macro resolution" or similar, which seems unhelpful and confusing. @petrochenkov i see you've assigned yourself on this PR; what do you think of removing the "during import/macro resolution" part?

**Review by camelid — APPROVED** [review]
`r=petrochenkov,camelid` with the below nits addressed and petrochenkov's approval. Thanks for making this change!

**Pull request merged**
