### PR TITLE
update mit-license and copyright

### PR DESCRIPTION
**Pull request by fay-jai**
Only made 2 changes:
1) Update the year to 2015 in LICENSE-MIT
2) Update the year in COPYRIGHT

No other changes were made.

### CODE REVIEW

**Comment by sfackler** [comment]
We should probably fill this in as well :) https://github.com/rust-lang/rust/blob/master/LICENSE-APACHE#L189

**Comment by fay-jai** [comment]
Whoops didn't see that when I was reviewing the License either!

**Comment by brson** [comment]
@sfackler That has been suggested many times, and I think that is just a template for 'how to apply this to your own work', i.e. it is not supposed to be filled in.

**Comment by alexcrichton** [comment]
All of these tests have passed, but @bors got a little confused, so merging manually.

**Pull request merged**
