### PR TITLE
Tentatively #[inline] Option::from

### PR DESCRIPTION
**Pull request by SoniEx2**
Probably not gonna have much of an impact because into can't be inlined. But let's try it?

(please perf run this whenever)

### CODE REVIEW

**Comment by joshtriplett** [comment]
@SoniEx2 I'd be *mildly* surprised that this isn't already being inlined. Do you have some code in release mode where this isn't being inlined?

Happy to put this through a perf run, but before doing so, do you have a godbolt link or similar showing that this *isn't* being inlined?

**Comment by SoniEx2** [comment]
we do not. we're just throwing stuff at the wall and seeing what sticks. tho we were surprised to find it not marked `#[inline]`. we wonder if it would do anything (maybe make things worse?).

**Comment by joshtriplett** [comment]
Usually LLVM manages to figure out inlining for tiny functions like this on its own; `#[inline]` and `#[inline(always)]` hints are useful when it *doesn't* figure things out.

I'd recommend trying some experiments with godbolt, typing code at rustc and seeing what the assembly looks like, and if you see a call to a tiny stub function that *should* be inlined but isn't, that's a good place to add `#[inline]`.

**Comment by Nilstrieb** [comment]
> 

Since this is a generic function, it gets duplicated into the codegen units of the caller anyways, making inlining possible. The inlinehint from it doesn't have too much of an impact usually and LLVM will just inline it.

**Comment by bugadani** [comment]
@Nilstrieb in that case why was [this](https://github.com/rust-lang/rust/pull/100733/files#diff-14800e8b76824724816091020061bbcd4860f1f43ba90a1ad6d52ec65e155255R559) useful?

**Comment by Nilstrieb** [comment]
`#[inline(always)]` gives stronger hint to inline it. Also, I'm not saying that adding `#[inline]` to generic functions is always useless, but it usually is.

**Comment by bugadani** [comment]
I guess my question should have been phrased as "Why was that function not inlined in the first place (without an inline attribute), since this is also generic?". Apologies for the poor formulation. Is there a difference between blanket impls and generic impls (i.e. `impl Foo for T` vs `impl Foo for Option<T>`)?

**Comment by Nilstrieb** [comment]
No, there is not difference between those. LLVMs inliner (and MIR inlining) just inline whatever their heuristics say should be inlined, which is often correct, but not always. Functions being generic just _allows_ inlining in the first place (because the function implementation has to by copied into the user codegen unit), whether it actually happens is up to the inliner.

**Comment by thomcc** [comment]
> @SoniEx2 I'd be _mildly_ surprised that this isn't already being inlined. Do you have some code in release mode where this isn't being inlined?

A lot of our generic methods don't end up getting inlined when optimizing for size. At a previous job I was doing a lot of embedded stuff, and at -Copt-level=z (even with -Zbuild-std) we'd frequently see dozens of copies of tiny generic functions. FWIW, this would only happen on certain targets (I guess the set of LLVM passes we run depends somewhat on the target? Since not all targets exhibited this issue), which makes the issue more annoying.

Some (but not all) of these would be inlined anyway, but end up in the output regardless, but this is an LLVM bug (some discussion in https://github.com/rust-lang/rust/pull/96624). This was never that big of a deal (cost was likely under a kilobyte of code total which didn't make a difference for us), so I never dug that deeply (also IMO ideally we wouldn't need to mark these with `#[inline]`, and hopefully won't in the future).

While I never saw Option::from, I suspect this is just because it doesn't get used much in that code, since this is absolutely the kind of thing we'd see copies of.

**Comment by nikic** [comment]
Because this is a recurring problem, I've spent some time trying to understand just why `#[inline]` makes a difference for generic functions, even though it ostensibly shouldn't. This is my conclusion: https://github.com/rust-lang/rust/issues/102539

Basically, if we ignore the opt-for-size case (where `-Z share-generics` causes extra issues), the relevant distinction is whether the function is instantiated per-crate or per-CGU. Generic functions are instantiated per-crate, while `#[inline]` functions are instantiated per-CGU.

**Comment by Kobzol** [comment]
@bors try @rust-timer queue

The queue is empty anyway, so it doesn't hurt to see what this does I suppose.

**Comment by Kobzol** [comment]
The cycle and RSS aren't real, the perf. run has hit a period where the perf. machine has a different config, but it's not reflected in master perf. results yet.

Seeing as there are no instruction count improvements, I'd be inclined to close this.

**Comment by JohnCSimon** [comment]
@SoniEx2 
Ping from triage: Can you please post the status of this PR? 

> Seeing as there are no instruction count improvements, I'd be inclined to close this.

Maybe close it?

Thank you.

**Pull request closed without merging**
