### PR TITLE
[debuginfo] Emit associated type bindings in trait object type names.

### LINKED ISSUE #86134: Debuginfo type names for `dyn` types are incomplete
The [current implementation](https://github.com/rust-lang/rust/blob/a50d72158e08e02cfc051b863017bdbd2c45b637/compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs#L133-L142) does not handle associated type bindings and auto-traits which leads to information about the type being lost. For example, `&dyn Iterator<Item=u32> + Send` will be mapped to `&dyn Iterator` and `&dyn Send + Sync` will be mapped to `& dyn '_`.

Some consumers of debuginfo (e.g. NatVis) rely on these type names to be unambiguous identifiers of the type they represent so we must not lose information about assoc type bindings and auto-traits.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR updates debuginfo type name generation for trait objects to include associated type bindings and auto trait bounds -- so that, for example, the debuginfo type name of `&dyn Iterator<Item=Foo>` and `&dyn Iterator<Item=Bar>` don't both map to just `&dyn Iterator` anymore.

The following table shows examples of debuginfo type names before and after the PR:
| type | before |  after |
|------|---------|-------|
| `&dyn Iterator<Item=u32>>` | `&dyn Iterator` | `&dyn Iterator<Item=u32>` |
| `&(dyn Iterator<Item=u32>> + Sync)` | `&dyn Iterator` | `&(dyn Iterator<Item=u32> + Sync)` |
| `&(dyn SomeTrait<bool, i8, Bar=u32>> + Send)` | `&dyn SomeTrait<bool, i8>` | `&(dyn SomeTrait<bool, i8, Bar=u32>> + Send)`  |

For targets that need C++-like type names, we use `assoc$<Item,u32>` instead of `Item=u32`:
| type | before |  after |
|------|---------|-------|
| `&dyn Iterator<Item=u32>>` | `ref$<dyn$<Iterator> >` | `ref$<dyn$<Iterator<assoc$<Item,u32> > > >` |
| `&(dyn Iterator<Item=u32>> + Sync)` | `ref$<dyn$<Iterator> >` | `ref$<dyn$<Iterator<assoc$<Item,u32> >,Sync> >` |
| `&(dyn SomeTrait<bool, i8, Bar=u32>> + Send)` | `ref$<dyn$<SomeTrait<bool, i8> > >` | `ref$<dyn$<SomeTrait<bool,i8,assoc$<Bar,u32> > >,Send> >`  |

The PR also adds self-profiling measurements for debuginfo type name generation (re. https://github.com/rust-lang/rust/issues/86431). It looks like the compiler spends up to 0.5% of its time in that task, so the potential for optimizing it via caching seems limited.

However, the perf run also shows [the biggest regression](https://perf.rust-lang.org/detailed-query.html?commit=585e91c718b0b2c5319e1fffd0ff1e62aaf7ccc2&base_commit=b9197978a90be6f7570741eabe2da175fec75375&benchmark=tokio-webpush-simple-debug&run_name=incr-unchanged) in a test case that does not even invoke the code in question. This suggests that the length of the names we generate here can affect performance by influencing how much data the linker has to copy around. 

Fixes https://github.com/rust-lang/rust/issues/86134.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
r? @wesleywiser 

@dpaoliello, do the changes here look good to you from an MSVC perspective?

**Comment by michaelwoerister** [comment]
Regarding the performance regression: I noticed that other parts of the compiler don't print generic arguments if they are equal to the default. Doing this for debuginfo type names too (which is sensible, IMO) might give a nice performance boost that makes up for the regression here. Let me know if I should add that to the PR.

**Review by wesleywiser — APPROVED** [review]
This looks good to me! If you think omitting default type parameters is pretty easy, I think it would be worth doing in this PR to see if we can improve the performance but if not, I'd be ok landing this as-is.

**Comment by michaelwoerister** [comment]
I'll look into it. For type arguments it should be straightforward.

**Comment by michaelwoerister** [comment]
It looks like omitting default arguments is not as straightforward as I had hoped (I don't understand the relationship between ty::Generics and ty::InternalStubsts well enough). I'll need to leave it for another PR. Let's see if the perf regression persists.

@bors r=wesleywiser

**Review by dpaoliello — APPROVED** [review]

**Comment by michaelwoerister** [comment]
Updated test cases. Let's see if I got all of them. My local CDB version is a bit newer than the one on CI and sometimes prints natvis visualizations where the one on CI doesn't.

@bors r=wesleywiser

**Comment by rylev** [comment]
Given the [comments](https://github.com/rust-lang/rust/pull/87153#issuecomment-881428994) on how one might address this performance issue, and the fact that it doesn't seem to have caused performance regressions after merging, I'm going to add the `perf-regression-triaged` label so this is not considered an active performance regression. 

@rustbot label +perf-regression-triaged

**Pull request merged**
