### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by fmease**
Successful merges:

 - #128004 (codegen `#[naked]` functions using global asm)
 - #131558 (Lint on combining `#[no_mangle]` and `#[export_name]`)
 - #133122 (Add unpolished, experimental support for AFIDT (async fn in dyn trait))
 - #133184 (wasi/fs: Improve stopping condition for <ReadDir as Iterator>::next)
 - #133456 (Add licenses + Run `cargo update`)
 - #133472 (Run TLS destructors for wasm32-wasip1-threads)
 - #133853 (use vendor sources by default on dist tarballs)
 - #133946 (coverage: Prefer to visit nodes whose predecessors have been visited)
 - #134010 (fix ICE on type error in promoted)
 - #134029 (coverage: Use a query to find counters/expressions that must be zero)
 - #134071 (Configure renovatebot)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=128004,131558,133122,133184,133456,133472,133853,133946,134010,134029,134071)

### CODE REVIEW

**Comment by folkertdev** [comment]
you should remove https://github.com/rust-lang/rust/pull/128004, I'm quite sure it caused the failure of https://github.com/rust-lang/rust/pull/134069

**Comment by fmease** [comment]
> although I did just push a commit that might fix it, so ?

well, even if you pushed something after the bors r+, it wouldn't be part of the rollup merge because r+ is only valid for the latest commit at the time of approval.

**Pull request closed without merging**
