### PR TITLE
Integrate attributes as part of the crate hash

### PR DESCRIPTION
**Pull request by cjgillot**
r? @Aaron1011

### CODE REVIEW

**Comment by Aaron1011** [comment]
cc @rust-lang/wg-incr-comp: I'd like someone else to look this over as well.

**Comment by Aaron1011** [comment]
LGTM

r? @wesleywiser for a final review, since they approved https://github.com/rust-lang/rust/pull/79519

**Comment by wesleywiser** [comment]
Perf results look slightly negative overall with a few small wins. Is that expected?

**Comment by Aaron1011** [comment]
Yes - we're now doing necessary work (hashing attributes) that we weren't doing before. This leads to issues like `https://github.com/rust-lang/rust/issues/83887`, where we don't re-compute a query on a foreign crate because the crate hash was unchanged.

**Comment by Aaron1011** [comment]
@wesleywiser: Does this look good to you? It would be really good to get this merged, since it fixes some ICEs with incremental compilation.

**Comment by wesleywiser** [comment]
@Aaron1011 thanks for the reminder! I will review tomorrow.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
`r=me` when rebased

**Comment by pnkfelix** [comment]
Visited for perf triage, there was [a regression](https://perf.rust-lang.org/compare.html?start=770792ff8d1ec542e78e77876ac936f43ffb8e05&end=467253ff6a2aecd008d273286315ac14ff8ad937&stat=instructions:u), seems roughly consistent with the results that we got from the perf run on the PR, so this regression was expected outcome.

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/41941steeringmeeting20210528fingerprintsand15384970.html#240614946) in steering meeting about incr-comp fingerprints.

beta backport approved.

**Comment by Mark-Simulacrum** [comment]
Do we have a test for this PR? It doesn't look like it backports cleanly (the crate_hash function was added after beta branched)

**Comment by cjgillot** [comment]
No test were written at the time. I am not sure how to make one, https://github.com/rust-lang/rust/issues/83887 had no MCVE.
On backporting, the crate_hash used to be computed during indexing. How should I make a backport PR?

**Comment by Mark-Simulacrum** [comment]
If you can, that'd be great. Happy to r+ that pretty quickly; it should target the current beta branch. Let me know if I should expect that by Monday -- otherwise I will invest effort over the weekend myself.

**Pull request merged**
