### PR TITLE
bootstrap: use git merge-base for LLVM CI download logic

### LINKED ISSUE #101907: Merge commits break LLVM CI download
While PRs are not allowed to have merge commits, they can still be useful locally (or for not rewriting history for longer-running branches). 

However, they break the commit detection logic for downloading CI artifacts.

### Steps to Reproduce

1. `git checkout <old-commit>`
2. `git merge --no-ff master`
3. `./x.py build library/std`

### Expected Result

Builds fine.

### Actual Result

~~~
...
downloading https://ci-artifacts.rust-lang.org/rustc-builds/<old-commit>/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
curl: (22) The requested URL returned error: 404      #                                                                               

error: failed to download llvm from ci

help: old builds get deleted after a certain time
help: if trying to compile an old commit of rustc, disable `download-ci-llvm` in config.toml:

[llvm]
download-ci-llvm = false

Build completed unsuccessfully in 0:01:43
~~~

### PR DESCRIPTION
**Pull request by RalfJung**
This re-lands https://github.com/rust-lang/rust/pull/113588, now that the perf issues are hopefully fixed by https://github.com/rust-lang/rustc-perf/pull/1684.
r? @lqd @Mark-Simulacrum 

Fixes https://github.com/rust-lang/rust/issues/101907

### CODE REVIEW

**Comment by lqd** [comment]
Let's see if things are indeed fixed on the server: @bors try @rust-timer queue

**Comment by lqd** [comment]
Looks like there's no issue on bootstrap anymore 🎉 

@bors r+ rollup=never

**Comment by RalfJung** [comment]
Thanks, let's hope it all works out this time. :)

**Comment by pnkfelix** [comment]
* this is a collection of spurious regressions to bitmaps-3.1.0
    * see e.g. [this graph](https://perf.rust-lang.org/index.html?start=2023-08-31&end=2023-09-05&benchmark=bitmaps-3.1.0&profile=check&scenario=full&stat=instructions%3Au&kind=raw) and note the blip.
* marked as triaged

@rustbot label: +perf-regression-triaged

**Pull request merged**
