### PR TITLE
Make FixedSizeArray an unsafe trait

### PR DESCRIPTION
**Pull request by alevy**
[breaking-change]

`FixedSizeArray` is meant to be implemented for arrays of fixed size only, but can be implemented for anything at the moment. Marking the trait unsafe would make it more reasonable to write unsafe code which operates on fixed size arrays of any size.

For example, using `uninitialized` to create a fixed size array and immediately filling it with a fixed value is externally safe:

```
pub fn init_with_nones<T, A: FixedSizeArray<Option<T>>>() -> A {
    let mut res = unsafe { mem::uninitialized() };
    for elm in res.as_mut_slice().iter_mut() {
        *elm = None;
    }
    res
}
```

But the same code is not safe if `FixedSizeArray` is implemented for other types:

```
struct Foo { foo: usize }
impl FixedSizeArray<Option<usize>> for Foo {
    fn as_slice(&self) -> &[usize] { &[] }
    fn as_mut_slice(&self) -> &mut [usize] { &mut [] }
}
```

now `init_with_nones() : Foo` returns a `Foo` with an undefined value for the field `foo`.

### CODE REVIEW

**Comment by bluss** [comment]
Can you put `[breaking-change]` (exactly) in the commit log or the PR message? Thanks.

This sounds good to me, but I don't think I can make the decision.

**Comment by alevy** [comment]
@bluss I added it to the PR message, hopefully correctly...

**Comment by petrochenkov** [comment]
Hm, if you break it anyway maybe you can make `T` an output parameter? `FixedSizeArray<T>` and `FixedSizeArray<U>` where `T != U` can never be implemented for the same type.

**Comment by alevy** [comment]
@petrochenkov Seems reasonable except I'm not able to write this such that it comiles atm:

```
unsafe impl<E, A: Unsize<[E]>> FixedSizeArray for A {
    type T = A;

    #[inline]
    fn as_slice(&self) -> &[Self::T] {
        self
    }
    #[inline]
    fn as_mut_slice(&mut self) -> &mut [Self::T] {
        self
    }
}
```

Results in a compile error citing E0207 -- that `E` is not bound by the impl trait, self type or perdicate. This may be a bug in RFC 447, which doesn't seem to consider bounds by other types (in this case, the type of `E` _is_ determined uniquely, I think)

**Comment by bluss** [comment]
@alexcrichton I'd like to do this

**Comment by petrochenkov** [comment]
@alevy
That's bad. There may be a workaround, but I don't know it (people on IRC may know). The patch looks good enough to me even without this change.

**Comment by alexcrichton** [comment]
Can you also expand the documentation to indicate why this trait is `unsafe`? e.g what guarantees must implementors uphold and what guarantees can code rely on?

I'm a little wary to continue to tweak perma-unstable traits like this because they're permanently unstable and lots of tweaks mean that the abstraction is useful and should perhaps live externally on crates.io first before moving into the standard library. This trait was added some time ago and there's no current usage in-tree, so there's no real reason this *can't* be external.

For now though an incremental improvement is fine.

**Comment by alevy** [comment]
@alexcrichton I expanded the documentation. Happy to revise if needed, though. Thanks!

**Comment by alexcrichton** [comment]
@bors: r+ b30d8969e86fa2c9dd3b8e2e28ddda2202331f0f

Thanks!

**Pull request merged**
