### PR TITLE
Simplify codegen for niche-encoded enums in simple cases

### PR DESCRIPTION
**Pull request by krdln**
Vast majority of niche-encoded enums have either a single niche-encoded variant or all their niche-encoded tags are greater than the whole untagged range, eg. with `enum E { A(bool), B, C }`  we have 0 | 1 → A, 2 → B, 3  → C. Currently get_discriminant accounts for various edgecases, like wrapping ranges, etc., but for such simple enum, we should be able to just determine whether an untagged value is stored by simple `<` comparison.

In pseudocode, before:
```rust
let relative_discr = tag.wrapping_sub(X);
if relative_discr < Y { Z } else { relative_discr + A }
```

after:
```rust
if tag < X { Z } else { tag - B }
```

Also:
* Noticed that doing all computation before cast to `cast_to` yields better codegen (perhaps LLVM has problems with `range` propagation when casting?).
* Adding `assume` that niche-encoded discriminant will never be the same as untagged discriminant helps a lot in cases when untagged variant is not the first one. Eg. in `enum E { A, B(bool), C }` LLVM would have to consider 0 | 1 | 3 as valid values for B) if not for this assumption.
* I remember trying slight variant of `tag < X` condition (`<=` or  just inverting the boolean? not sure now), but it resulted in LLVM getting too smart and recognizing the `if tag > X { 0 } else { tag - X }` as saturating-sub intrinsic too early in the process, which resulted in nice codegen, but stopped further optimization.

Despite some nice wins in generated assembly – [see the "enum-fair-opt" file in this gist][gist], I've seen only tiny (~0.03%) improvements on check scenarios in local perf testing on instr counts. The wins were quite consistent though, so I'd be happy to see a perf run – perhaps there's an improvement in cycles? (I couldn't get reliable values for cycles on local setup)

Pushing it as draft, because TODO
- [ ] ~~Cranelift~~ It could be done in followup PR, I guess
- [ ] Add test for non-simple cases (they are so rare now, so that this codepath is basically untested)
- [ ] Compare with https://github.com/rust-lang/rust/pull/102872 – perhaps combine the best of both approaches?

May help with https://github.com/rust-lang/rust/issues/101872

[gist]: https://gist.github.com/krdln/cefbb4a14d7ddfb5014099d1a0060916

### CODE REVIEW

**Comment by krdln** [comment]
<details>
<summary>Some before & after assembly:

</summary>

```rs
pub enum Foo {Bar(bool), Baz, Quux, Quux2}

pub fn baz(foo: Foo) -> bool {
    matches!(foo, Foo::Baz)
}

pub enum E {A, Other(char), B}

pub fn x(x: E) -> char {
    match x {
        Other(c) => c,
        _ => 'x',
    }
}


````

wins: before & after

```
0000000000000000 <enum_fair::bar>:
   0:	40 80 c7 fb          	add    dil,0xfb
   4:	40 80 ff fd          	cmp    dil,0xfd
   8:	0f 92 c0             	setb   al
   b:	c3                   	ret    

0000000000000000 <abx_bad::x>:
   0:	8d 8f 00 00 ef ff    	lea    ecx,[rdi-0x110000]
   6:	83 f9 01             	cmp    ecx,0x1
   9:	b8 78 00 00 00       	mov    eax,0x78
   e:	0f 44 c7             	cmove  eax,edi
  11:	83 f9 03             	cmp    ecx,0x3
  14:	0f 43 c7             	cmovae eax,edi
  17:	c3                   	ret    
```

```
0000000000000000 <enum_fair::bar>:
   0:	40 80 ff 02          	cmp    dil,0x2
   4:	0f 92 c0             	setb   al
   7:	c3                   	ret    

0000000000000000 <abx_bad::x>:
   0:	81 ff 00 00 11 00    	cmp    edi,0x110000
   6:	b8 78 00 00 00       	mov    eax,0x78
   b:	0f 42 c7             	cmovb  eax,edi
   e:	c3                   	ret    
```

And here, the case of ugly `movzx`es (note: x86_64 doesn't have 8-bit cmov, only 16, 32 and 64):

```rs
pub fn disco(foo: Foo) -> std::mem::Discriminant<Foo> {
    std::mem::discriminant(&foo)
}
```

before & after:

```
0000000000000000 <enum_fair::disco>:
   0:	40 80 c7 fe          	add    dil,0xfe
   4:	40 0f b6 cf          	movzx  ecx,dil
   8:	48 8d 51 01          	lea    rdx,[rcx+0x1]
   c:	31 c0                	xor    eax,eax
   e:	80 f9 03             	cmp    cl,0x3
  11:	48 0f 42 c2          	cmovb  rax,rdx
  15:	c3                   	ret    
```

```
0000000000000000 <enum_fair::disco>:
   0:	8d 47 ff             	lea    eax,[rdi-0x1]
   3:	31 c9                	xor    ecx,ecx
   5:	40 80 ff 02          	cmp    dil,0x2
   9:	0f b6 c0             	movzx  eax,al
   c:	0f 42 c1             	cmovb  eax,ecx
   f:	0f b6 c0             	movzx  eax,al
  12:	c3            
```

I'm not even sure if that's an improvement or regression, on one hand, critical path to cmp seems shorter – add-(movzx)-lea-cmp-cmov vs lea-cmp-(movzx)-cmov. On the other hand, I googled somewhere that `movzx` within the same register is a bad idea: https://github.com/InstLatx64/InstLatx64/issues/4

</details>

**Comment by krdln** [comment]
Build failure looks spurious to me
```
warning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `openssl-src v111.22.0+1.1.1q` failed to transfer more than 10 bytes in 30s)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `windows-sys v0.36.1` within 30s)
error: failed to download from `[https://crates.io/api/v1/crates/libnghttp2-sys/0.1.4+1.41.0/download`](https://crates.io/api/v1/crates/libnghttp2-sys/0.1.4+1.41.0/download%60)
```

**Comment by mikebenfield** [comment]
That's great, there's several ways LLVM's codegen seems to be suboptimal around this. In fact it seems to me it really could be doing the optimizations we're making on its own (just with some range data). 

That said, I'm not sure about the particular issue you filed. There's a surprising lack of clarity about this, but I think the x86_64 Sys V ABI does actually not require integer arguments in registers to be zero extended, and AFAICT gcc keeps in the `movzx` too.

**Comment by krdln** [comment]
@mikebenfield
> There's a surprising lack of clarity about this, but I think the x86_64 Sys V ABI does actually not require integer arguments in registers to be zero extended, and AFAICT gcc keeps in the movzx too.

The `cast` example turned out (as explained to me by @nikic) to be just a bad attempt in minimizing the repro. And it looks like both clang & gcc do emit just `mov eax, edi`, so I guess zeroextension is in the ABI? Anyway, the other example seems valid still.

**Comment by krdln** [comment]
@mikebenfield Turns out I was a bit overeager with the "tagged variant never has the same value as untagged" `assume` after all. Without such gating it was incorrectly assuming eg. `enum E { A(bool), B, C }` is never `A(true)`. Anyway, this assume doesn't seem to have any effect on rustc perfomance itself (although it improvents codegen _a lot_ for two-arms scenarios (to single cmp + jmp) where untagged variant is not the first one).

**Comment by krdln** [comment]
@nagisa I believe we've with @mikebenfield in #102872 converged on very similar approach, but can we do a perf run also on my PR? If it'll show the same results, I'll close my PR as redundant.

**Comment by krdln** [comment]
When toggling "show non-relevant results", looks like there's a small, but consistent improvements – instr counts are mostly green (esp. when looking only at full-check). Even better results with cycles. Bootstrap is also green-ish (not sure whether that's significant enough though). Looked at some profiles and `mir_borrowck` seems like a major contributor to the speedup.

The regressions I see are only in `incr-patched`/`incr-unchanged` scenarios. Tried to look at the profiles there, but don't understand the cause. Anyway, perhaps these regressions are acceptable?

I also found a small codegen regression (`enum Abc { B, A(bool), C }; matches!(Abc, B)`) – looks like the `assume` was pessimizing for some reason. Pushed a fix – changing location of the assume seemed to help. Now I think all the `is_x()`-like functions should compile down to a single cmp+set. [See this gist](https://gist.github.com/krdln/262f932d8ae75f19673bae3b2165f1c1) . Anyway – based on local testing I don't think this change would change the perf results significantly, but perhaps we can have a rerun, @nagisa?

@mikebenfield I've seen you have some regressions on your branch, sadly. Do you mind if I "steal" your tests and undraft my PR, or do you plan to debug the regressions on your PR?

**Comment by mikebenfield** [comment]
I do indeed plan to debug the regressions on my PR, although it's possible they won't be resolved until the LLVM issue I filed is fixed. 

Feel free to do as you wish and steal tests and whatever you want from me. I do find the cases I wrote a little cleaner and more general - AFAICT you only handle 1 out of the 4 cases I handle, but it is the common case. I'd ideally like to get all those cases in there, but whatever works is fine with me.

**Comment by krdln** [comment]
https://github.com/rust-lang/rust/pull/102872 was merged with the same idea :tada:. I think the codegen could be optimized even further though, will try to reopen.

**Pull request closed without merging**
