### PR TITLE
Replace MinGW library hack with heuristic controlling link mode

### LINKED ISSUE #68887: provide a way of overriding the MinGW library path
The recently landed #67429 introduced a heuristic to search for the system MinGW libraries relative to the cross-gcc (used as linker) itself. However, there are systems that do not follow this pattern. For example, on my Gentoo system:
- `/usr/bin/x86_64-w64-mingw32-gcc` is a symlink to `/usr/x86_64-pc-linux-gnu/x86_64-w64-mingw32/gcc-bin/9.2.0/x86_64-w64-mingw32-gcc`
- `/usr/x86_64-w64-mingw32/usr/lib/` is the directory with the actual libraries in the `/usr/x86_64-w64-mingw32` sysroot

It would be useful to have a way of overriding the heuristics and informing `rustc` about the correct library path manually. In the current configuration even `RUSTFLAGS="-L  /usr/x86_64-w64-mingw32/usr/lib/"` does not help because the rustc-provided libraries have higher priority.

### PR DESCRIPTION
**Pull request by mati865**
Depends on https://github.com/rust-lang/rust/pull/76158
Closes https://github.com/rust-lang/rust/issues/68887

### CODE REVIEW

**Comment by mati865** [comment]
Ugh, it detects `-C linker="rust-lld"` as native linker. I'll have to rethink it when I'm no longer ill and my brain works...

**Comment by petrochenkov** [comment]
LGTM, blocked on https://github.com/rust-lang/rust/pull/76158.

**Comment by mati865** [comment]
MacOS builder is on strike again...

**Pull request merged**
