### PR TITLE
Ignore files in .gitignore in mir opt check

### PR DESCRIPTION
**Pull request by joboet**
This caused `./x test tidy` to fail for me when Finder (macOS) added `.DS_Store` files. They are ignored by git, so tidy should ignore them, too.

### CODE REVIEW

**Comment by albertlarsan68** [comment]
I think there is a PR to ignore all files in .gitignore

**Comment by joboet** [comment]
Do you mean #106440? That unfortunately did not adjust the mir-opt check. This PR is just a cheap fix to get `git push` to work without having to delete the files all the time. Reimplementing the check using `walk_no_read` is probably the better solution, I'll see if I can do that.

**Comment by ozkanonur** [comment]
It looks pretty hacky that writing those files as hardcoded seperately from `.gitignore`. Which will cost maintaining multiple places for ignored files. And it will be worst and worst when we need to ignore more files. Can't we make it work with `.gitignore`?

**Comment by joboet** [comment]
I've rewritten this to use `walk_no_read`, so all files in .gitignore are now skipped.

**Comment by joboet** [comment]
Rebased to include #108772, which changed `walk_no_read`.

**Review by onur-ozkan — APPROVED** [review]
thanks for the fix!

**Pull request merged**
