### PR TITLE
Initial implementation of `str::from_raw_parts[_mut]`

### PR DESCRIPTION
**Pull request by Sky9x**
ACP (accepted): rust-lang/libs-team#167
Tracking issue: #119206

Thanks to @Kixiron for previous work on this (#107207)

@rustbot label +T-libs-api -T-libs
r? @thomcc 

Closes #107207.

### CODE REVIEW

**Comment by Sky9x** [comment]
r?

**Comment by Sky9x** [comment]
r? libs

**Review by dtolnay — APPROVED** [review]
Thank you!

**Comment by dtolnay** [comment]
I think there also needs to be a change in library/alloc/src/str.rs to re-export these functions into alloc::str and std::str.

**Pull request merged**
