### PR TITLE
Remove `no_integrated_as` mode.

### PR DESCRIPTION
**Pull request by nnethercote**
Specifically, remove both `-Z no_integrated_as` and
`TargetOptions::no_integrated_as`. The latter was only used for the
`msp430_none_elf` platform, for which it's no longer required.

r? @alexcrichton

### CODE REVIEW

**Comment by nnethercote** [comment]
Note that I'm not 100% certain that `msp430_none_elf` no longer needs `no_integrated_as`. #43099 was the PR that added that target, saying:
> Once the LLVM backend gains the ability to directly produce MSP430 object files
we can stop depending on msp430-elf-gcc for producing object files; when that
occurs the asm related fields will change. This change won't break existing
user code.

That was written in July 2017, and I'm hoping that the LLVM backend now has that ability. @japaric, are you able to confirm if it does?

**Comment by petrochenkov** [comment]
>The latter was only used for the
`msp430_none_elf` platform, for which it's no longer required.

Targets are not limited to those that are built-in and exist now though.
It is useful to be able to connect rustc to new LLVM backends in various stages of development (including proprietary ones), that may mean the lack of complete integrated assembler.

**Comment by jonas-schievink** [comment]
MSP430 no longer needs this, but like @petrochenkov said, external targets might. Is there any specific reason for removing support for this? Has the code been a big maintenance burden or slowed down development in other ways? If not I'd like to kindly request not to remove it.

**Comment by alexcrichton** [comment]
Code-wise this looks fine by me, thanks @nnethercote!

@jonas-schievink the codegen backend is currently a large and sprawling maze of lots of conditionals, so having extra ones "just because" is a burden on maintaining this because everyone new who looks at the backend has to understand themselves why there's all these odd cases and booleans for what to do.

@petrochenkov personally I don't disagree that it's great to work wherever possible, but there's a very real cost on maintenance here. If there's no clear benefit my opinion is that it should be removed, and at this time I think there's unclear benefit because there's no known target using this.

**Comment by Dylan-DPC** [comment]
@nnethercote @alexcrichton any updates on this? do we want to merge it ?

**Comment by alexcrichton** [comment]
@Dylan-DPC er it seems a bit early to be pinging about this? This PR itself is only 14 hours old and the last discussion was 4 hours ago. I'm not sure @nnethercote is even awake yet to continue discussion on this...

**Comment by Dylan-DPC** [comment]
@alexcrichton oops too many tabs open. Sorry :D

**Comment by nnethercote** [comment]
I have started looking at this codegen stuff because I am working on #66961. As Alex says, the codegen backend is complex and messy. I've already filed a couple of clean-up PRs as preliminaries: #70297, #70289. Alex suggested that `no_integrated_as` was unnecessary and as a newcomer to the codebase who is trying to understand it and clean it up, I am sympathetic to that view. But I've never worked on adding a new target platform and I am definitely not an expert on this stuff.

**Comment by alexcrichton** [comment]
I personally feel that if we need this functionality it should come back in a less-complicated form. For example we shouldn't have to plumb many different options around the compiler. Instead there should be a desire for an object file with one piece of configuration saying "instead of LLVM generating an object file, use this `Command` to generate an object file".

Having a small local `if` statement is much more easily maintained and understood than something which ends up being extremely rarely used yet sprawling over the codebase.

**Comment by hanna-kruppe** [comment]
FWIW, I have combined rustc with out-of-tree LLVM backends and also worked on LLVM support for new ISA extensions, and I have never had a need for this flag. Teaching LLVM to emit basic object files is usually simple compared to everything else that goes into backend development, and usually quite valuable. Certainly there are targets out there which don't prioritize it, but in my experience, being complete enough to be used with rustc but unable to produce object files is an anomaly rather than a normal stage in an LLVM backend's lifecycle.

**Comment by nnethercote** [comment]
FWIW, I rebased this code. After #70384 it's looking even nicer.

**Comment by alexcrichton** [comment]
@bors: r+

This looks like a great simplification to me in what's already pretty gnarly code. It's also relatively easy to revert if truly necessary and we can go back to the drawing board to figure out how to integrate this in a cleaner fashion. Because of that, I'm gonna r+ this.

**Comment by nnethercote** [comment]
@Centril: this PR removed a `-C` option, and so should be mentioned in release notes.

**Comment by cr1901** [comment]
A bit "too-little too-late" for me, but I've been trying to diagnose some [regressions](https://github.com/rust-lang/rust/issues/67819) that I suspect popped up in msp430 during the switch to an integrated assembler. It's taking a while because:

1. Well, the state of the world's pretty bad at the moment.
2. The best granularity I have, even after bisecting, is a dozen or so commits thanks to rollups.

Right now, I'm not sure if this'll be necessary, but @alexcrichton seems to imply it's easy to add this option back in in a less-complicated form as a workaround?

>I personally feel that if we need this functionality it should come back in a less-complicated form. For example we shouldn't have to plumb many different options around the compiler. Instead there should be a desire for an object file with one piece of configuration saying "instead of LLVM generating an object file, use this Command to generate an object file".

 I simply don't think I have the bandwidth to hack on LLVM, but would be interested in discussing re-enabling a `no-integrated-as` option cleanly if necessary.

**Comment by bjorn3** [comment]
> How does the removal of no_integrated_as interact with alternate backends?

At least rustc_codegen_cranelift didn't support it anyway. Cranelift only supports emitting machine code, not assembly. Also code that was removed in this PR was either in the LLVM backend, or was just some utils in the rustc_codegen_ssa. This means that it is possible to implement this in other backends without touching rustc.

**Comment by alexcrichton** [comment]
@cr1901 I don't know if it'll be easy per se, but I think it would be best to try to integrate it today in an ideally cleaner form. For example it would ideally be one local decision along the lines of "either have LLVM produce the object or have LLVM produce the asm and we run an external assembler". This previously touched a number of parts in the codebase (as can be seen here).

**Comment by cr1901** [comment]
>At least rustc_codegen_cranelift didn't support it anyway. Cranelift only supports emitting machine code, not assembly. Also code that was removed in this PR was either in the LLVM backend, or was just some utils in the rustc_codegen_ssa. This means that it is possible to implement this in other backends without touching rustc.

Ack.

@alexcrichton Right now, I'm not sure how I would add the option back in. But if you want it reintroduced in a cleaner form, then great! Let me figure out whether the change to an integrated assembler is to blame for my woes in the first place.

If it is, then I think I have some interest in reintroducing this option if someone can give me some guidance on how it can be done (under the assumption it's far less painful than hacking on llvm, _and_ it gives me a means to compare and contrast if I find new regressions).

Also,

>in my experience, being complete enough to be used with rustc but unable to produce object files is an anomaly rather than a normal stage in an LLVM backend's lifecycle.

Perhaps, but if the gnu assembler is perfectly good as-is for a target without an upstream llvm backend, not needing to implement the assembler means I can test Rust binaries in practice more quickly. :P

**Comment by alexcrichton** [comment]
Unfortuantely I don't personally have time to review/guide how to re-add this. Others on the compiler team may be able to help out though!

**Comment by petrochenkov** [comment]
Another example of a target without integrated assembler - https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Report.20patch.20for.20a.20new.20OS

**Pull request merged**
