### PR TITLE
Uplift fix for include! in doc tests to beta

### LINKED ISSUE #43153: Change in behavior of `include!` in doctests on nightly
I haven't had a chance to create a minimal repro case, but I'm seeing these in Diesel's builds: https://travis-ci.org/diesel-rs/diesel/jobs/252088111#L824. The issue only occurs on nightly, and it seems to only affect doctests which are more than 2 directories deep.

### PR DESCRIPTION
**Pull request by nrc**
Uplift https://github.com/rust-lang/rust/pull/43782 to beta. Fixes #43153.

r? @alexcrichton 

(approved by @rust-lang/dev-tools )

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Should we make this change on nightly as well? (I don't know if there is a backport strategy or equivalent.)

**Comment by nrc** [comment]
@GuillaumeGomez #43782 is this change on nightly.

**Comment by GuillaumeGomez** [comment]
Oh I see, great!

**Comment by aidanhs** [comment]
@bors retry
(prioritise rollup)

**Pull request merged**
