### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #41348, #41362, #41374, #41377, #41380, #41391
- Failed merges:

### CODE REVIEW

**Comment by aidanhs** [comment]
```
[00:51:18] Initialized empty Git repository in /checkout/obj/build/ct/xsv/.git/
[00:51:18] fatal: Could not parse object 'a9a7163f2a2953cea426fee1216bec914fe2f56a'.
[00:51:19] From https://github.com/BurntSushi/xsv
[00:51:19]  * branch            master     -> FETCH_HEAD
[00:51:19] fatal: Could not parse object 'a9a7163f2a2953cea426fee1216bec914fe2f56a'.
[00:51:19] From https://github.com/BurntSushi/xsv
[00:51:19]  * branch            master     -> FETCH_HEAD
[00:51:19] fatal: Could not parse object 'a9a7163f2a2953cea426fee1216bec914fe2f56a'.
[00:51:20] From https://github.com/BurntSushi/xsv
[00:51:20]  * branch            master     -> FETCH_HEAD
[00:51:20] HEAD is now at a9a7163 Merge pull request #53 from alexcrichton/fix-beta
[00:51:20] error: An unknown error occurred
```
Now that's interesting, we've seen this before (ctrl+f "corrupt download" on #40474) but [on appveyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2517/job/78c29lc858e7a0nh#L2110).

Spurious though.

**Comment by aidanhs** [comment]
Basically blocked on #41398.

**Comment by frewsxcv** [comment]
I'll open a new rollup with that

**Pull request closed without merging**
