### PR TITLE
Fix "field is never used" warning to take unions into account

### PR DESCRIPTION
**Pull request by joshtriplett**
When compiling code containing a union with an unused field, rustc says
"struct field is never used".

Rather than saying "struct or union", or adding logic to determine the
type of the item, just change the message to "field is never used",
dropping the "struct".

Update tests accordingly.

### CODE REVIEW

**Comment by sanxiyn** [comment]
Maybe add a test containing a union with an unused field?

**Comment by joshtriplett** [comment]
@sanxiyn Done.

**Pull request merged**
