### PR TITLE
traits with self-containing supertraits are not object safe

### LINKED ISSUE #38404: 3 line ICE on stable and nightly (Unexpected type in full type resolver)
the following generates a compiler error on all current versions:
```
trait A<T>: std::ops::Add +Sized  {}
trait B<T>: A<T> {}
trait C<T>: A<B<T, Output = usize>> {}
```
RUST_BACKTRACE hangs for me, but emits:
`error: internal compiler error: ../src/librustc/infer/resolve.rs:132: Unexpected type in full type resolver: FreshTy(0)
`
https://is.gd/lkcWgT

This is greatly cut down from a real world example, and a blocking issue for me

### PR DESCRIPTION
**Pull request by arielb1**
This should be the last time I fix this function.

Fixes #38404.

### CODE REVIEW

**Comment by arielb1** [comment]
This fixes the ICE, but we still permit stuff such as
```Rust
trait Q<T:?Sized> {}
trait Foo where u32: Q<Self> {}

fn main() {
    let f: Box<Foo> = ...;
}
```

That shouldn't cause an ICE because non-supertrait bounds are never used, but I still think I should future-compatibility-warning this.

**Comment by eddyb** [comment]
cc @rust-lang/compiler @brson We should probably gate this on Crater.

**Comment by arielb1** [comment]
The current patch is pretty non-aggressive, prohibiting only cases that tend to ICE. I think we want to crater a more aggressive version of it (cc #38604).

**Comment by arielb1** [comment]
now ready for crater

**Comment by nikomatsakis** [comment]
cc @brson -- can you run this through craterbomb?

**Comment by brson** [comment]
I'll run it through crater. Cargobomb isn't quite ready for this yet.

**Comment by brson** [comment]
Still cratering.

**Comment by brson** [comment]
Crater says https://gist.github.com/anonymous/3409c01561daa0670445c1ac9f967f6b

Some false positives but some legit errors.

**Comment by nikomatsakis** [comment]
Root regressions from @brson's run (I haven't analyzed them yet, hence the unchecked check boxes). We should try to and submit fixes or at least contact authors of affected crates and so forth.

* [ ] [objc-0.2.2](https://crates.io/crates/objc) ([before](https://tools.taskcluster.net/task-inspector/#3tnDQRilT_qkigwbhqOUSQ)) ([after](https://tools.taskcluster.net/task-inspector/#EMKC4Cy9SG2YA3s9yvznGA))
* [ ] [target_build_utils-0.1.2](https://crates.io/crates/target_build_utils) ([before](https://tools.taskcluster.net/task-inspector/#VuieZyD8RWOqF2NMeLtOTw)) ([after](https://tools.taskcluster.net/task-inspector/#Ok14n1eBShCI8lL7Rnm1dg))
* [ ] [theban_db_server-0.3.6](https://crates.io/crates/theban_db_server) ([before](https://tools.taskcluster.net/task-inspector/#oKTdxJmBQSC3S_eHpI2R9Q)) ([after](https://tools.taskcluster.net/task-inspector/#Cy2LgKPSRHOrSMtJIR6Pgw))
* [ ] [ferris-0.1.1](https://crates.io/crates/ferris) ([before](https://tools.taskcluster.net/task-inspector/#Trl5ekSzTQq9OGdpy2xYKQ)) ([after](https://tools.taskcluster.net/task-inspector/#W0G_wHs8QuieXJYtQ9AoLA))
* [ ] [hokaido-0.0.9](https://crates.io/crates/hokaido) ([before](https://tools.taskcluster.net/task-inspector/#5_k8IHMES2eK08A188T6jg)) ([after](https://tools.taskcluster.net/task-inspector/#jWV-B6-SRFm46e1MlNGy_A))
* [ ] [msgpacknet-0.1.1](https://crates.io/crates/msgpacknet) ([before](https://tools.taskcluster.net/task-inspector/#s6Xt5NEdTziMN4a8cTCJ5g)) ([after](https://tools.taskcluster.net/task-inspector/#_mx_tJ9TQF-Qrca7udAbPg))
* [ ] [neovim-lib-0.1.1](https://crates.io/crates/neovim-lib) ([before](https://tools.taskcluster.net/task-inspector/#ipGWAVIWSt2iAwDmrZSs0A)) ([after](https://tools.taskcluster.net/task-inspector/#NsHCwq1NRASp5GEg7cvhnw))
* [ ] [primer-0.1.0](https://crates.io/crates/primer) ([before](https://tools.taskcluster.net/task-inspector/#O-rKfX_JT_CUKwkgFT0ujg)) ([after](https://tools.taskcluster.net/task-inspector/#l44zLsvuSTeiP-3zg_sOAw))
* [ ] [fruently-0.7.1](https://crates.io/crates/fruently) ([before](https://tools.taskcluster.net/task-inspector/#zH9GAMFnTaKkGsP3Qtdxog)) ([after](https://tools.taskcluster.net/task-inspector/#OQJZ5UptSI6kwzSOUzoWcA))
* [ ] [terminal-0.0.2](https://crates.io/crates/terminal) ([before](https://tools.taskcluster.net/task-inspector/#lK9natFVTsqW3HGROlEwLg)) ([after](https://tools.taskcluster.net/task-inspector/#52QhgigwThiUKIUJHr5gcA))

**Comment by arielb1** [comment]
I am not sure what's behind the `rmt_serialize` errors, but resolution finishes before my new code runs so it shouldn't be me.

All other errors look spurious.

**Comment by nikomatsakis** [comment]
@arielb1 

> I am not sure what's behind the rmt_serialize errors, but resolution finishes before my new code runs so it shouldn't be me.

That *is* odd. Do you have a local build? Can you give this a spin locally?

**Comment by arielb1** [comment]
Looks like not our bug.

Compiling using the `Cargo.lock` in the repository works and uses the following versions:
```
   Compiling byteorder v0.3.13
   Compiling libc v0.2.8
   Compiling rustc-serialize v0.3.18
   Compiling rmp v0.7.3
   Compiling log v0.3.5
   Compiling rmp-serialize v0.7.0
   Compiling neovim-lib v0.1.1 (file:///home/ariel/Rust/neovim-lib)
```
While after a `cargo update`, or on crater, the following versions are used, triggering the error with both nightly and modified rustc:
```
   Compiling byteorder v1.0.0
   Compiling byteorder v0.4.2
   Compiling num-traits v0.1.36
   Compiling log v0.3.6
   Compiling rustc-serialize v0.3.22
   Compiling rmp v0.7.5
   Compiling rmp v0.8.1
   Compiling rmp-serialize v0.7.0
```

**Comment by nikomatsakis** [comment]
> Looks like not our bug.

So you get the same results both with and without this PR?

Since this is being used as a library, the `Cargo.lock` that is found in the repo isn't meaningful anyway. `Cargo.lock` is only respected for the final target, iiuc.

**Comment by arielb1** [comment]
@nikomatsakis 

Exactly. When you use the `Cargo.lock` from source control, it works with both the old and new rustcs, and when you `cargo update`, it does not work.

**Comment by nikomatsakis** [comment]
@arielb1 I'm sort of confused by what you meant when you wrote "not our bug"

**Comment by arielb1** [comment]
@nikomatsakis 

That's it's broken, but not by our changes.

**Comment by nikomatsakis** [comment]
OK, I misread this comment at first:

> When you use the Cargo.lock from source control, it works with both the old and new rustcs, and when you cargo update, it does not work.

Interesting.

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault https://github.com/rust-lang/rust/issues/38878

**Comment by alexcrichton** [comment]
@bors: retry

* canceled to prioritize rollup

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by alexcrichton** [comment]
@bors: retry

* canceled to prioritize rollup

**Comment by alexcrichton** [comment]
@bors: retry

* prioritizing rollup

**Pull request merged**
