### PR TITLE
Utilize Option::unwrap_or_default instead of verbose match

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by Gankro** [comment]
```
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/src/librustc/middle/traits/fulfill.rs:181:47: 181:66 error: no method named `unwrap_or_default` found for type `core::option::Option<&collections::vec::Vec<middle::traits::fulfill::RegionObligation<'_>>>` in the current scope
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/src/librustc/middle/traits/fulfill.rs:181         self.region_obligations.get(&body_id).unwrap_or_default()
                                                                                                                                                       ^~~~~~~~~~~~~~~~~~~
```

oops

**Comment by Gankro** [comment]
You probably want `unwrap_or_else(Default::default)`

**Comment by frewsxcv** [comment]
> You probably want unwrap_or_else(Default::default)

I don't think that will work if `unwrap_or_default` doesn't. I put together [an example demonstrating this](http://is.gd/PZRC5b). Is this a bug with types? I feel like all three options should be equally valid

**Comment by huonw** [comment]
Ah, the "problem" here is this code is relying on Deref coercions to take the `&Vec<X>` to a `&[X]`, which can't happen through `Option`. That is, `unwrap_or_default` is being called on an `Option<T>` with `T = &Vec<X>`, and there's no `Default` impl for that type. It works if you convert the `Option` to store a `&[X]` explicitly, [e.g.](https://play.rust-lang.org/?gist=3ed332492b5f0b1aff8b&run=1), `map.get("b").map(|x| &**x).unwrap_or_default()` but this is arguably less clear than the original.

**Comment by frewsxcv** [comment]
@huonw Ah, thanks for looking into it. I understand now

**Comment by huonw** [comment]
Nonetheless, thanks for the patch! The idea was great, but it's unfortunate it didn't quite work in practice.

**Pull request closed without merging**
