### PR TITLE
Add inline asm! tests for aarch64

### PR DESCRIPTION
**Pull request by adamgemmell**
Port many of the x86-only UI tests for inline asm! over to aarch64.

### CODE REVIEW

**Comment by Amanieu** [comment]
Rather than adding a `-x86_64` or `-aarch64` suffix, could you instead move the tests into `x86_64/` and `aarch64/` directories?

**Comment by adamgemmell** [comment]
Rebase & rebless fixes the test failure. This branch could probably do with squashing when merging

**Comment by Amanieu** [comment]
LGTM, can you squash the commits before merging?

**Comment by adamgemmell** [comment]
More conflicts/changes from master - I'll of course squash again once you've taken a look at them

**Comment by Amanieu** [comment]
LGTM

**Comment by Amanieu** [comment]
Note that webassembly has inline asm but doesn't have the `reg` register class. It uses `local` instead.

**Comment by JohnCSimon** [comment]
ping from triage:
@adamgemmell  
Returning to you to address merge conflicts and after that, please switch back to `S-waiting-on-review`.
thanks.

@rustbot label: +S-waiting-on-author -S-waiting-on-review

**Comment by adamgemmell** [comment]
Sorry for the delay on this one. Opted to disable tests requiring a `reg` class. There were also a few new test files posted upstream since the last update.

**Pull request merged**
