### PR TITLE
Reduce the size of the clone for people who just build rustc from source

### PR DESCRIPTION
**Pull request by dns2utf8**
This speeds up the download process for the user.

Tested on armhf and amd64.

### CODE REVIEW

**Comment by steveklabnik** [comment]
It does, but it also has downsides as well. You can't do all the stuff you can do with a 'real' checkout.

**Comment by tomjakubowski** [comment]
> It does, but it also has downsides as well. You can't do all the stuff you can do with a 'real' checkout.

At one point shallow clones were pretty broken compared to 'real' clones (you couldn't push/pull from/to shallow clones, for example), but the situation is much better as of git 2.0. See https://github.com/git/git/commit/82fba2b9d39163a0c9b7a3a2f35964cbc039e1a and https://blog.oio.de/2014/02/06/better-support-for-shallow-clones-in-git-1-9/

Of course, with a shallow clone one's options for digging through history are limited. But for someone who just wants to build, that may not be a big deal. 

My personal preference is to leave `--depth` out, though. Not everyone is on git 2.0 and the Rust README hardly seems like the right place for git education ;-)

**Comment by petevine** [comment]
This change is almost useless because the heaviest submodules are still going to be cloned later even when they're not needed.

Here's the main issue to solve:
https://github.com/rust-lang/rust/issues/30107

**Comment by brson** [comment]
I also have reservations about this. Knowledgeable developers will know this is an option. And as @petevine says you're still going to end up cloning LLVM.

**Comment by dns2utf8** [comment]
I agree.

I tried a reduced clone of llvm and the submodules, but it did not work anymore.

So close?

**Comment by alexcrichton** [comment]
Ah yeah I'm going to close this for the aforementioned reasons. Thanks for the PR regardless though!

**Pull request closed without merging**
