### PR TITLE
Revert switch of env locking to rwlock, to fix deadlock in process spawning

### LINKED ISSUE #82221: Tests frequently hang when running in CI
For example:

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/584397542

```
2021-02-20T15:11:57.9643919Z test src/unit.rs - unit::() (line 8) ... ok
2021-02-20T15:11:58.6669755Z test src/hash/mod.rs - hash::Hash (line 118) ... test src/hash/mod.rs - hash::Hash (line 118) has been running for over 60 seconds
2021-02-20T18:59:20.4859234Z ##[error]The operation was canceled.
```

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/582799710

```
2021-02-19T22:41:28.8405274Z test [ui] ui/zero-sized/zero-sized-btreemap-insert.rs ... [32mok(B[m
2021-02-19T22:42:14.7778690Z test [ui] ui/traits/inheritance/auto-xc-2.rs ... test [ui] ui/traits/inheritance/auto-xc-2.rs has been running for over 60 seconds
2021-02-20T03:14:01.0798295Z ##[error]The operation was canceled.
```

* i686-gnu-nopt, https://github.com/rust-lang-ci/rust/actions/runs/581261402

```
2021-02-19T12:06:02.9084847Z test src/unit.rs - unit::() (line 8) ... ok
2021-02-19T12:06:51.4775574Z test src/slice/mod.rs - slice::[T]::split_inclusive (line 1721) ... test src/slice/mod.rs - slice::[T]::split_inclusive (line 1721) has been running for over 60 seconds
2021-02-19T15:58:10.4810134Z ##[error]The operation was canceled.
```

* i686-gnu-nopt, https://github.com/rust-lang-ci/rust/actions/runs/580204602

```
2021-02-19T03:58:02.3058849Z test src/unit.rs - unit::() (line 8) ... ok
2021-02-19T03:58:06.5575267Z test src/num/f64.rs - f64::f64::to_int_unchecked (line 713) ... test src/num/f64.rs - f64::f64::to_int_unchecked (line 713) has been running for over 60 seconds
2021-02-19T03:58:06.6183037Z test src/num/f64.rs - f64::f64::to_radians (line 664) ... test src/num/f64.rs - f64::f64::to_radians (line 664) has been running for over 60 seconds
2021-02-19T03:58:06.8427828Z test src/num/mod.rs - num::i128::checked_mul (line 125) ... test src/num/mod.rs - num::i128::checked_mul (line 125) has been running for over 60 seconds
2021-02-19T08:25:13.4822002Z ##[error]The operation was canceled.
```

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/579652564

```
2021-02-18T23:18:51.6325844Z test src/unit.rs - unit::() (line 8) ... ok
2021-02-18T23:19:07.7022305Z test src/num/mod.rs - num::i8::overflowing_shl (line 101) ... test src/num/mod.rs - num::i8::overflowing_shl (line 101) has been running for over 60 seconds
2021-02-18T23:19:07.7025632Z test src/num/mod.rs - num::i8::overflowing_shr (line 101) ... test src/num/mod.rs - num::i8::overflowing_shr (line 101) has been running for over 60 seconds
2021-02-19T03:14:59.9520192Z ##[error]The operation was canceled.
```

* i686-gnu-nopt, https://github.com/rust-lang-ci/rust/actions/runs/578564764

```
2021-02-18T16:11:04.4681653Z test src/thread/mod.rs - thread::spawn (line 574) ... ok
2021-02-18T16:11:50.6625267Z test src/io/buffered/bufwriter.rs - io::buffered::bufwriter::BufWriter<W>::with_capacity (line 101) ... test src/io/buffered/bufwriter.rs - io::buffered::bufwriter::BufWriter<W>::with_capacity (line 101) has been running for over 60 seconds
2021-02-18T16:11:50.6628673Z test src/io/buffered/bufwriter.rs - io::buffered::bufwriter::WriterPanicked (line 342) ... test src/io/buffered/bufwriter.rs - io::buffered::bufwriter::WriterPanicked (line 342) has been running for over 60 seconds
2021-02-18T19:46:32.2739034Z ##[error]The operation was canceled.
```

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/574689947

```
2021-02-17T12:22:37.0787532Z test src/unit.rs - unit::() (line 8) ... ok
2021-02-17T12:23:15.3416508Z test src/ops/range.rs - ops::range::Range<Idx>::contains (line 108) ... test src/ops/range.rs - ops::range::Range<Idx>::contains (line 108) has been running for over 60 seconds
2021-02-17T12:23:15.3860771Z test src/ops/range.rs - ops::range::Range<Idx>::is_empty (line 135) ... test src/ops/range.rs - ops::range::Range<Idx>::is_empty (line 135) has been running for over 60 seconds
2021-02-17T12:23:15.3954939Z test src/ops/range.rs - ops::range::Range<Idx>::is_empty (line 143) ... test src/ops/range.rs - ops::range::Range<Idx>::is_empty (line 143) has been running for over 60 seconds
2021-02-17T15:58:57.7397418Z ##[error]The operation was canceled.
```

* i686-gnu-nopt https://github.com/rust-lang-ci/rust/actions/runs/574041064

```
2021-02-17T08:04:37.6421396Z test /checkout/obj/build/i686-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index::E0560 (line 10819) ... test /checkout/obj/build/i686-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index::E0560 (line 10819) has been running for over 60 seconds
2021-02-17T11:42:11.6753113Z ##[error]The operation was canceled.
```

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/571440802

```
2021-02-16T12:11:04.4309316Z test src/num/mod.rs - num::u128::overflowing_add (line 687) ... test src/num/mod.rs - num::u128::overflowing_add (line 687) has been running for over 60 seconds
2021-02-16T15:51:09.2838337Z ##[error]The operation was canceled.
```

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/569804832

```
2021-02-15T22:31:16.0693197Z test src/rc.rs - rc::Rc<str>::from (line 1677) ... test src/rc.rs - rc::Rc<str>::from (line 1677) has been running for over 60 seconds
2021-02-16T02:15:04.9960511Z ##[error]The operation was canceled.
```

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/568924798

```
2021-02-15T15:49:53.9346495Z test [rustdoc] rustdoc/async-fn.rs ... test [rustdoc] rustdoc/async-fn.rs has been running for over 60 seconds
2021-02-15T15:49:53.9347834Z test [rustdoc] rustdoc/auto_aliases.rs ... test [rustdoc] rustdoc/auto_aliases.rs has been running for over 60 seconds
2021-02-15T15:49:53.9351255Z test [rustdoc] rustdoc/blanket-reexport-item.rs ... test [rustdoc] rustdoc/blanket-reexport-item.rs has been running for over 60 seconds
2021-02-15T15:49:53.9355893Z test [rustdoc] rustdoc/cfg-doctest.rs ... test [rustdoc] rustdoc/cfg-doctest.rs has been running for over 60 seconds
2021-02-15T19:31:32.9773227Z ##[error]The operation was canceled.
```

* x86_64-gnu-distcheck, https://github.com/rust-lang-ci/rust/actions/runs/567687201

```
2021-02-15T07:23:52.7932514Z test process::tests::set_current_dir_works ... test process::tests::set_current_dir_works has been running for over 60 seconds
2021-02-15T07:23:52.7956236Z test process::tests::smoke_failure ... test process::tests::smoke_failure has been running for over 60 seconds
2021-02-15T07:23:52.8000422Z test process::tests::stdout_works ... test process::tests::stdout_works has been running for over 60 seconds
2021-02-15T07:23:52.8003330Z test process::tests::test_add_to_env ... test process::tests::test_add_to_env has been running for over 60 seconds
2021-02-15T11:31:04.8393216Z ##[error]The operation was canceled.
```

* i686-gnu-nopt, https://github.com/rust-lang-ci/rust/actions/runs/567078402 

```
2021-02-15T01:52:21.9305024Z test [ui] ui/const-generics/dyn-supertraits.rs#min ... test [ui] ui/const-generics/dyn-supertraits.rs#min has been running for over 60 seconds
...
2021-02-15T01:52:22.0950343Z test [ui] ui/const-generics/impl-const-generic-struct.rs#full ... test [ui] ui/const-generics/impl-const-generic-struct.rs#full has been running for over 60 seconds
2021-02-15T01:52:22.0979483Z test [ui] ui/const-generics/impl-const-generic-struct.rs#min ... test [ui] ui/const-generics/impl-const-generic-struct.rs#min has been running for over 60 seconds
...
2021-02-15T01:53:27.8003720Z test [ui] ui/wrong-hashset-issue-42918.rs ... [32mok(B[m
2021-02-15T07:27:19.1277356Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
```

* x86_64-gnu-tools, https://github.com/rust-lang-ci/rust/actions/runs/566396551

```
2021-02-14T18:48:05.5200384Z test [compile-fail] compile-fail/validity/cast_fn_ptr1.rs ... test [compile-fail] compile-fail/validity/cast_fn_ptr1.rs has been running for over 60 seconds
2021-02-14T18:48:05.5205371Z test [compile-fail] compile-fail/validity/cast_fn_ptr2.rs ... test [compile-fail] compile-fail/validity/cast_fn_ptr2.rs has been running for over 60 seconds
2021-02-14T22:27:40.1596769Z ##[error]The operation was canceled.
```

* i686-gnu, https://github.com/rust-lang-ci/rust/actions/runs/565453954

```
2021-02-14T08:22:02.1591402Z test [ui] ui/privacy/privacy-ns1.rs ... test [ui] ui/privacy/privacy-ns1.rs has been running for over 60 seconds
2021-02-14T08:22:02.1612224Z test [ui] ui/privacy/privacy-ns2.rs ... test [ui] ui/privacy/privacy-ns2.rs has been running for over 60 seconds
...
2021-02-14T08:22:17.5287557Z test [ui] ui/zero-sized/zero-sized-btreemap-insert.rs ... [32mok(B[m
2021-02-14T12:08:11.0576147Z ##[error]The operation was canceled
```

* i686-gnu-nopt, https://github.com/rust-lang-ci/rust/actions/runs/564715419

```
2021-02-14T00:07:06.7001285Z test src/num/mod.rs - num::i128::to_be_bytes (line 125) ... test src/num/mod.rs - num::i128::to_be_bytes (line 125) has been running for over 60 seconds
2021-02-14T00:07:07.0201166Z test src/num/mod.rs - num::i128::wrapping_rem_euclid (line 132) ... test src/num/mod.rs - num::i128::wrapping_rem_euclid (line 132) has been running for over 60 seconds
2021-02-14T04:54:10.0684435Z ##[error]The operation was canceled.
```

* i686-gnu-nopt, https://github.com/rust-lang-ci/rust/actions/runs/562391922

```
2021-02-12T23:03:12.7099769Z test [codegen] codegen/enum-bounds-check.rs ... test [codegen] codegen/enum-bounds-check.rs has been running for over 60 seconds
2021-02-12T23:03:12.7959650Z test [codegen] codegen/ffi-returns-twice.rs ... test [codegen] codegen/ffi-returns-twice.rs has been running for over 60 seconds
2021-02-12T23:03:12.7980559Z test [codegen] codegen/float_math.rs ... test [codegen] codegen/float_math.rs has been running for over 60 seconds
2021-02-13T02:47:57.6026816Z ##[error]The operation was canceled.
```

### PR DESCRIPTION
**Pull request by ehuss**
This reverts commit 354f19cf2475148994954b6783341620c7445071, reversing changes made to 0cfba2fd090834c909d5ed9deccdee8170da791b.

PR https://github.com/rust-lang/rust/pull/81850 switched the environment lock from a mutex to an rwlock. However, process spawning (when not able to use `posix_spawn`) locks the environment before forking, and unlocks it after forking (in both the parent and the child). With a mutex, this works (although probably not correct even with a mutex). With an rwlock, on at least some targets, unlocking in the child does not work correctly, resulting in a deadlock.

This has manifested as CI hangs on i686 Linux; that target doesn't use `posix_spawn` in the CI environment due to the age of the installed C library (currently glibc 2.23). (Switching to `posix_spawn` would just mask this issue, though, which would still arise in any case that can't use `posix_spawn`.)

Some additional cleanup of environment handling around process spawning may help, but for now, revert the PR and go back to a standard mutex.

Fixes #82221

### CODE REVIEW

**Comment by ehuss** [comment]
cc @the8472 @m-ou-se

**Comment by m-ou-se** [comment]
@bors r+

Thanks for investigating! Let's open an issue to check out the underlying problem that's probably still there with a Mutex. Once we fix that part, we can probably put the rwlock back. (Not unlocking in the child by mem::forget'ing the guard might already be enough.)

**Comment by m-ou-se** [comment]
Oh. Review race condition.

**Comment by ehuss** [comment]
> Let's open an issue to check out the underlying problem that's probably still there with a Mutex.

Filed #82879 to track this.

**Comment by JohnTitor** [comment]
I saw this failure on https://github.com/rust-lang/rust/pull/82847#issuecomment-792129983, spurious?
@bors retry

**Comment by ehuss** [comment]
@JohnTitor I can reproduce that error, so I filed #82886.

**Comment by ehuss** [comment]
@bors retry
#81890

**Comment by ehuss** [comment]
@bors retry
https://github.com/BurntSushi/xsv/issues/227

**Comment by m-ou-se** [comment]
@bors p=20

(To make it go in front of rollups.)

**Pull request merged**
