### PR TITLE
Update stdsimd to branch with breaking bugfix

### PR DESCRIPTION
**Pull request by gnzlbg**
**DO NOT MERGE**

---

This updates `stdsimd` to the `test-fix` branch containing this PR (https://github.com/rust-lang-nursery/stdsimd/pull/576) with a breaking soundness bugfix. 

The plan was to schedule a crater run before merging this PR into stdsimd upstream.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@craterbot run start=master#05812fa8c588473f03e3fa7cf59cd84f4f37c715 end=try#d7816399d50d407bbce1efe9dbadf8faaaf568fc mode=check-only

**Comment by gnzlbg** [comment]
@alexcrichton looks like there are two regressions, but they do look spurious.

**Comment by alexcrichton** [comment]
Agreed! I think this indicates that it should be safe to land the change. Shall we land the stdsimd PR on master, then update this one and land it?

**Pull request closed without merging**
