### PR TITLE
Print name of env var in `--print=deployment-target`

### PR DESCRIPTION
**Pull request by madsmtm**
The deployment target environment variable is OS-specific, and if you're in a place where you're asking `rustc` for the deployment target, you're likely to also wanna know the name of the environment variable. I myself wanted this for some code I'm working on in bootstrap, for example.

Behaviour before this PR:
```console
$ rustc --print=deployment-target --target=aarch64-apple-darwin
deployment_target=11.0
$ rustc --print=deployment-target --target=aarch64-apple-visionos
deployment_target=1.0
```

Behaviour after this PR:
```console
$ rustc --print=deployment-target --target=aarch64-apple-darwin
MACOSX_DEPLOYMENT_TARGET=11.0
$ rustc --print=deployment-target --target=aarch64-apple-visionos
XROS_DEPLOYMENT_TARGET=1.0
```

My _belief_ is that this option is extremely rarely used in general, and a GitHub search for "rustc print deployment-target" seems to confirm this, it revealed only the following actual pieces of code using this:
- https://github.com/PyO3/maturin/blob/b292ef69349f2a56cb8ab1b59fda0be3d3b9f138/src/build_context.rs#L1199-L1220
- https://github.com/rust-lang/cc-rs/blob/daab9244b03e244c4f2511944870d719c443f61f/src/lib.rs#L3422-L3426

`maturin` does `.split('=').last()`, so it will continue to work after this change, but `cc v1.0.84` did `.strip_prefix("deployment_target=")` since [this PR](https://github.com/rust-lang/cc-rs/pull/848), so it would break. That's _probably_ fine though, it was broken in a lot of scenarios anyway, and [got](https://github.com/rust-lang/cc-rs/pull/901) [reverted](https://github.com/rust-lang/cc-rs/pull/943) in `v1.0.85`.

So while this is _technically_ a breaking change, I really doubt that anyone is going to observe it, so it's probably fine.

@BlackHoleFox wdyt?

@rustbot label O-apple
r? compiler

### CODE REVIEW

**Comment by madsmtm** [comment]
This also makes it easier to use in shell scripts, you can now do:
```sh
export $(rustc --print=deployment-target --target=$MY_APPLE_TARGET)
# Or
env $(rustc --print=deployment-target --target=$MY_APPLE_TARGET) clang --target $MY_APPLE_TARGET foo.c
```

**Comment by madsmtm** [comment]
Rustbot didn't seem to pick it up the first time, so:

@rustbot label O-apple

**Comment by fee1-dead** [comment]
r? compiler

**Comment by madsmtm** [comment]
> iirc one of the reasons I made it print without the variable name is so it has a higher chance of working with non-Apple OSes whenever RFCs/interested parties get along to making `cfg()`s for configuring what version of Windows, Android, etc a Rust build should target. I don't think its set in stone those would have env variables to go along with?

That's fair reasoning, although then IMO it should've been called `rustc --print=target-os-version`, and honestly just returned it directly without the `deployment_target=` in front.

Given that we now have some cruft in the front _anyhow_, I think we might as well use it for something useful. Besides, if this is expanded to other targets, they can just use `deployment_target=` like done today.

**Comment by madsmtm** [comment]
https://github.com/rust-lang/rust/pull/133092 is what I wanted it for, btw

**Review by davidtwco — APPROVED** [review]
I think this makes sense, "deployment target" seems to be very Apple-specific terminology, so I think if we wanted to introduce a "target OS version" alternative that supported more platforms (and just returned the deployment target for Apple platforms) then we could still do that and keep this as Apple-specific.

**Comment by davidtwco** [comment]
Based on your description, it doesn't seem like this is likely to break anything, but we can always revert it if we get reports of issues.

@bors r+

**Comment by jieyouxu** [comment]
[Failed in rollup](https://github.com/rust-lang/rust/pull/133329#issuecomment-2493470678):

```
---- [run-make] tests/run-make/apple-sdk-version stdout ----
[trimmed]
--- stderr -------------------------------
thread 'main' panicked at /Users/runner/work/rust/rust/tests/run-make/apple-sdk-version/rmake.rs:30:70:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@bors r-

**Comment by madsmtm** [comment]
Oops, fixed now.

@rustbot ready

**Pull request merged**
