### PR TITLE
[beta] Rollup backports

### PR DESCRIPTION
**Pull request by emilyalbini**
Cherry-picked:

* #59886:  musl: do not compress debug section 
* #59891:  Fix the link to sort_by_cached_key 
* #59911: Revert "compile crates under test w/ -Zemit-stack-sizes" 
* #59978: rustdoc: Remove default keyword from re-exported trait methods  
* #59989: Fix links to Atomic* in RELEASES.md  
* #60186: Temporarily accept [i|u][32|size] suffixes on a tuple index and warn  
* #60309: Add 1.34.1 release notes

Rolled up:

* #60273: [beta] bootstrap; remove redundant imports. 

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
@jethrogb are we going to get the "build failed" on every beta backport?

**Comment by jethrogb** [comment]
Unless https://github.com/rust-lang/rust/pull/59857 also gets backported probably. I can look into disabling this for some branches, but we just look at changes to the `auto` branch in git to determine what to build.

**Comment by pietroalbini** [comment]
You can check if you're on nightly with:

```
grep RUST_RELEASE_CHANNEL=nightly src/ci/run.sh
```

**Comment by jethrogb** [comment]
Thanks! Now let's hope I remember to turn this back on when the next beta is forked...

**Comment by pietroalbini** [comment]
Bors seems stuck...

@bors retry

**Comment by jethrogb** [comment]
Well, I guess that didn't work ¯\_(ツ)_/¯

**Comment by pietroalbini** [comment]
Seems like a spurious link failure?

@bors retry

**Pull request merged**
