### PR TITLE
Document possible panics for `std::env::{set_var, unset_var}`

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by bluss** [comment]
The rules for both posix and windows do seem to include that the name must not contain `=`, still maybe it should say *may* panic, not guarantee panic.

In reality this API panics on any OS error from the operation. It's a bit tricky to document with certainty since the number of OSes that Rust supports will be growing.

**Comment by alexcrichton** [comment]
Wow I'm surprised by this, I had no idea this could happen! In retrospect it makes sense, however.

I agree with @bluss that we probably don't want to *guarantee* that it panics in these situations, but rather indicate that it may panic. It may also be worth noting that if there is a nul byte on Unix (and maybe on Windows?) a panic will happen as well. The last failure mode that I know of is OOM, but I think that's fine to not document.

**Comment by alexcrichton** [comment]
For anyone testing this locally as well, turns out on Unix a `set_var("", "")` also deadlocks, which https://github.com/rust-lang/rust/pull/29305 should fix.

**Comment by tbu-** [comment]
@alexcrichton Changed it to "*may* panic". Is it better like this?

**Pull request merged**
