### PR TITLE
move TestHelpers to test.rs and rename native.rs to llvm.rs

### PR DESCRIPTION
**Pull request by jkvargas**
Fixes issse #108240

### CODE REVIEW

**Comment by eggyal** [comment]
I presume this is addressing #108240?  If you put `Fixes #108240` (or any of the [other supported keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)) in the PR description then not only can reviewers follow links between the issue and this PR but GitHub will also automatically close the issue if/when this PR is merged.

**Comment by Mark-Simulacrum** [comment]
Please squash commits. r=me with that done.

@rustbot author

**Comment by Mark-Simulacrum** [comment]
Please squash commits. r=me with that done.

@rustbot author

**Comment by jkvargas** [comment]
Closing this since I created a new PR https://github.com/rust-lang/rust/pull/109649

**Pull request closed without merging**
