### PR TITLE
fix typo: "requests function in the same [way] as other"

### PR DESCRIPTION
**Pull request by rutsky**
r? @steveklabnik

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+ rollup

Sorry about the delay, and thanks!

**Comment by rutsky** [comment]
@Manishearth I have few more minor documentation fixes, should I include `r? @steveklabnik` in the commit message or it's not useful any more?

**Comment by steveklabnik** [comment]
You don't need to put it in the commit message, you can just put it in the PR.

I was sick the last three days, so that's why there was the delay. So sorry! :cold_sweat: :mask: :dizzy_face: 

In the future I'll be faster.

**Comment by rutsky** [comment]
> You don't need to put it in the commit message, you can just put it in the PR.

I made slip of the keyboard, of course in the PR, not in the commit message.

> I was sick the last three days, so that's why there was the delay. So sorry!

Get well soon!

**Pull request merged**
