### PR TITLE
Unstable Book: update `lang_items` page and split it

### LINKED ISSUE #110274: Outdated documentation for feature `lang_items`
### Location

[`src/doc/unstable-book/src/language-features/lang-items.md`](https://github.com/rust-lang/rust/blob/master/src/doc/unstable-book/src/language-features/lang-items.md) or https://doc.rust-lang.org/unstable-book/language-features/lang-items.html

### Summary

The examples don't compile and the list of `lang` items is outdated.

Should the list at the bottom of the page still be updated? The amount of language items has grown and there's already a list [here in the source code](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir/src/lang_items.rs#L148).

### PR DESCRIPTION
**Pull request by kadiwa4**
[`lang_items` rendered](https://github.com/kadiwa4/rust/blob/lang_items_doc/src/doc/unstable-book/src/language-features/lang-items.md), [`start` rendered](https://github.com/kadiwa4/rust/blob/lang_items_doc/src/doc/unstable-book/src/language-features/start.md)
Closes #110274
Rustonomicon PR: rust-lang/nomicon#413, Rust Book PR: rust-lang/book#3705

A lot of information doesn't belong on the `lang_items` page. I added a separate page for the `start` feature and moved some text into the Rustonomicon because the `lang_items` page should not be a tutorial on how to build a `#![no_std]` executable.
The list of existing lang items is too long/unstable, so I removed it. 

The doctests still don't work. :(

### CODE REVIEW

**Comment by carols10cents** [comment]
I realize this is a bit of a deadlock here, but before I merge the book PR, I'd like to know that this PR would get approved if CI were passing, to avoid having to revert the book PR or having an unhelpful link in the book for some amount of time.

Please let me know @JohnTitor !

**Comment by JohnTitor** [comment]
> I realize this is a bit of a deadlock here, but before I merge the book PR, I'd like to know that this PR would get approved if CI were passing, to avoid having to revert the book PR or having an unhelpful link in the book for some amount of time.

@carols10cents Sorry for the delay! Yeah, I'd r+ once the linked PR gets merged :)

**Comment by carols10cents** [comment]
Great, thank you! I've merged the book PR.

**Comment by kadiwa4** [comment]
Can I do a submodule update as part of this PR or do I need to open a separate one?

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Sorry for the delay! @bors r+ rollup

**Pull request merged**
