### PR TITLE
Fix ios compilation

### PR DESCRIPTION
**Pull request by tamird**
r? @alexcrichton cc @vhbit

### CODE REVIEW

**Comment by vhbit** [comment]
1. Such a huge whitespace/newline changes should be in a separate PR as they hide the intention and aren't relevant to iOS
2. I wouldn't change dragonfly behavior without knowledge how it works and which constants it uses, i.e. it should remain as it is until maintainer decides to change it.
3. Regarding iOS part everything is OK - this constant exists and while it practically useless, it's easier to enable it than to mess with conditional compilation on dependent modules.

**Comment by tamird** [comment]
> Such a huge whitespace/newline changes should be in a separate PR as they hide the intention and aren't relevant to iOS

Yeah, maybe. It's in a separate commit, we'll see what @alexcrichton says.

> I wouldn't change dragonfly behavior without knowledge how it works and which constants it uses, i.e. it should remain as it is until maintainer decides to change it.

I checked the dragonfly source, the constant is correct.

**Comment by alexcrichton** [comment]
Yeah could the whitespace changes be refactored into a separate PR? Other than that this looks great, thanks!

**Comment by tamird** [comment]
Done! https://github.com/rust-lang/rust/pull/23385

**Pull request merged**
