### PR TITLE
Add a script to automatically update Rust/Clang versions in documentation

### PR DESCRIPTION
**Pull request by jyn514**
From https://github.com/rust-lang/rust/pull/76402#issuecomment-687974508.

r? @elichai

### CODE REVIEW

**Comment by elichai** [comment]
Looks good :) Thanks! 
(I just hope I'll remember it's there in 3 months when I see it's outdated lool)

**Comment by jyn514** [comment]
Is there some way to make it more visible? I tried to put it as close to the table as possible so you'd see it.

@bors delegate=elichai

**Comment by elichai** [comment]
> Is there some way to make it more visible? I tried to put it as close to the table as possible so you'd see it.

Don't think so, I think it's the best we can do here

**Pull request merged**
