### PR TITLE
[Experiment] [WIP] Add clone_from to clone derive

### LINKED ISSUE #98374: Derived Clone implementations don't utilize `clone_from` implementations from field types
I tried this code:

```rust
struct A;

impl Clone for A {
    fn clone(&self) -> Self {
        println!("Basic clone");
        Self
    }

    fn clone_from(&mut self, other: &Self) {
        println!("Clone from");
        *self = Self;
    }
}

#[derive(Clone)]
struct B(A);

fn main() {
    let b = B(A);
    let mut bb = B(A);
    bb.clone_from(&b);
}
```

I expected to see this happen: prints `Clone from`

Instead, this happened: prints `Basic clone`

I think, this can lead to little losses for types which have multiple vector and string fields.

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0

rustc 1.63.0-nightly (5750a6aa2 2022-06-20)
binary: rustc
commit-hash: 5750a6aa2777382bf421b726f234da23f990a953
commit-date: 2022-06-20
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

### PR DESCRIPTION
**Pull request by AngelicosPhosphoros**
Fixes #98374

This is still just experiment to run perf, code needs some cleanup.

### CODE REVIEW

**Comment by AngelicosPhosphoros** [comment]
During last attemp ( #27939 ), there wasn't perf run so we can make more well-founded decision about implementing `clone_from` now.

**Comment by Kobzol** [comment]
It's already happening :) This PR is currently in the perf. bot queue, once it's done, we will get a comment here with the results of compile time benchmarks.

**Comment by scottmcm** [comment]
I'll note that this would change the [panic safety](https://en.wikipedia.org/wiki/Exception_safety#Classification) of it -- the `clone_from` that just calls `clone` is strongly exception safe (assuming no weird interior mutability usage) whereas if it calls `clone_from` then `panic`s in the middle could have different results.

So I'll toss this on the @rust-lang/libs-api radar in case they have thoughts about whether it should happen from a semantic perspective (separate from implementation/perf questions).

**Comment by AngelicosPhosphoros** [comment]
@scottmcm 

>I'll note that this would change the [panic safety](https://en.wikipedia.org/wiki/Exception_safety#Classification) of it

We already don't exception safe in some important `Clone::clone_from` implementations (notably, [`alloc::vec::Vec::clone_from`](https://github.com/rust-lang/rust/blob/fc96600bf6a52f92aeeee60a92a161a82b61c0ef/library/alloc/src/vec/mod.rs#L2557)) which can truncate own length and modify first values and got panic in the middle which cause tail part of vec remain same as it was.

So, probably, we should just document in trait definition that `clone_from` is not panic-safe and user shouldn't use `clone_from` if exception safety is desired.

**Comment by AngelicosPhosphoros** [comment]
Worst case regression (264.5% on issue-58319) is looks like made specifically against `clone_from`: huge struct with only `#[derive(Clone)]` on it.
Since this PR doubles amount of code generated in that case, I think, doubling compilation time should be expected here.

**Comment by Kobzol** [comment]
I'm not really sure what do you mean by that. The perf. suite that was executed checks how long does it take to compile various crates (both artificial stress tests and real-world crates like `syn`, `serde`, `clap` etc.).

So, for example, if this PR was merged, it would take ~1-5% longer to compile crates like `regex`, `diesel`, `hyper` etc. (per the benchmark results). Usually, such compile time regressions are not accepted, unless they fix e.g. some soundness hole or something like that.

Maybe we can do something to optimize the implementation here, but it will probably be quite different. We also currently don't have infrastructure for benchmarking compiled programs, to see if the `clone_from` change has any performance benefits. It would be nice to see some perf. gains from this change from the real world, so that we could assess it's utility.

**Comment by oli-obk** [comment]
So... this is not about `clone_from` codegen, as that happens regardless of this PR. Maybe we could realize at the point where we codegen the default impl and instead generate a shim that forwards `clone_from`

**Comment by AngelicosPhosphoros** [comment]
> Maybe we could realize at the point where we codegen the default impl and instead generate a shim that forwards `clone_from`

You mean in the call-site?

>I'm not really sure what do you mean by that.

I mean, we would get regression from `clone_from` (X%) removal and then regression from my changes (Y%). And `(X - Y)%` would show how other programs would benefit or lose from that.

Maybe it is better just to run some real-world code.

**Comment by nnethercote** [comment]
FWIW: a 100% result is a 100% increase in compile-time, i.e. a doubling in compilation time. A 264.5% regression is a 3.645x slowdown. It's a weirdly large slowdown.

**Comment by oli-obk** [comment]
> You mean in the call-site?

No, I mean the LLVM IR we generate for `clone_from` could be compiler generated without generating a function in the derive

**Comment by AngelicosPhosphoros** [comment]
@nnethercote Thanks for you remark!

I have just run profiling using `-Zself-profile` on `cargo check` with master branch and with my changes.

It seems that borrow checker and typechecker really don't like `match` expression based destructuring.

Diff with base and my changes:

| Item                                             | Self Time   | Self Time Change | Time        | Time Change | Item count |
|--------------------------------------------------|-------------|------------------|-------------|-------------|------------|
| mir_borrowck                                     | +102.1242ms | +493.29%         | +116.7532ms | +397.70%    | +1         |
| typeck                                           | +54.7115ms  | +140.62%         | +55.7778ms  | +138.41%    | +1         |
| metadata_register_crate                          | +11.6217ms  | +503.21%         | +23.0361ms  | +747.17%    | +0         |
| mir_built                                        | +10.1796ms  | +190.22%         | +12.6228ms  | +175.82%    | +1         |
| check_match                                      | +5.4782ms   | +155.51%         | +5.5142ms   | +156.15%    | +1         |
| hir_lowering                                     | +3.6431ms   | +109.64%         | +3.6431ms   | +109.64%    | +0         |
| expand_crate                                     | +3.5499ms   | +62.59%          | +15.1705ms  | +189.01%    | +0         |
| incr_comp_finalize_session_directory             | -2.4131ms   | -61.38%          | -2.4131ms   | -61.38%     | +0         |
| thir_body                                        | +2.4057ms   | +158.66%         | +2.4075ms   | +158.61%    | +1         |
| late_resolve_crate                               | +2.309ms    | +103.88%         | +2.309ms    | +103.88%    | +0         |

This values became much better when I manually rewrote Clone impl like
```rust
#[inline]
fn clone(&self)->Self{
   Self(::core::clone::Clone::clone(&self.0), ..., ::core::clone::Clone::clone(&self.613),)
}

#[inline]
fn clone(&self, other: &Self){
   ::core::clone::Clone::clone_from(&mut self.0, &other.0);
   ...
   ::core::clone::Clone::clone_from(&mut self.613, &other.613);
}
```

Results

| Item                                             | Self Time  | Self Time Change | Time        | Time Change | Item count |
|--------------------------------------------------|------------|------------------|-------------|-------------|------------|
| typeck                                           | +79.3904ms | +204.05%         | +82.0408ms  | +203.57%    | +1         |
| mir_borrowck                                     | +9.639ms   | +46.56%          | +17.071ms   | +58.15%     | +1         |
| parse_crate                                      | +8.7804ms  | +943.82%         | +8.7804ms   | +943.82%    | +0         |
| late_resolve_crate                               | +7.8287ms  | +352.20%         | +7.8287ms   | +352.20%    | +0         |
| mir_built                                        | +3.4026ms  | +63.58%          | +5.7975ms   | +80.75%     | +1         |
| check_match                                      | -3.3612ms  | -95.42%          | -3.3655ms   | -95.30%     | +1         |
| hir_lowering                                     | +3.2036ms  | +96.41%          | +3.2036ms   | +96.41%     | +0         |
| thir_body                                        | +2.3983ms  | +158.17%         | +2.4003ms   | +158.13%    | +1         |

As you see, change is nearly 10x on borrow check.

You are removing match statement in #98446 so maybe it is good idea retry perf after you merge that?
May you ping me after merging it?

**Comment by conradludgate** [comment]
I already started an impl on this 👀 https://github.com/rust-lang/rust/pull/97528

**Comment by m-ou-se** [comment]
Regardless of performancec impact, I'm not sure we can do this, since this changes the clone_from behaviour in a potentially breaking way in the presence of panics, as @scottmcm already mentioned.

**Comment by AngelicosPhosphoros** [comment]
@m-ou-se I made PR with clarification about that guarantees, probably should discuss it there?
https://github.com/rust-lang/rust/pull/98461

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting, and we decided not to make this change. People can hand-implement `clone_from` if they need the performance, but we shouldn't do so by default.

**Pull request closed without merging**
