### PR TITLE
Add `::BYTES` to `int_macros` and `uint_macros`

### PR DESCRIPTION
**Pull request by x4exr**

### CODE REVIEW

**Comment by tgross35** [comment]
Did this have an ACP? If not, you would need to file one. It is just an issue template at https://github.com/rust-lang/libs-team/issues where you can propose and justify the change.

**Comment by x4exr** [comment]
alright, but I would have to do this tomorrow. What is an ACP? And should I rewrite my commit from the latest versions of these files and squash as I forgot to pull my changes in my fork previously?

**Comment by tgross35** [comment]
An ACP is an application change proposal, which you submit by filling out a template at the link I posted. Take a look at some of the open issues with the relevant label for examples.

Squashing is always a good idea for all repos if you make changes and then fix them up. But the ACP takes some time so there is no rush.

**Comment by tgross35** [comment]
For the record, I am somewhat skeptical of this API being accepted because it is just `size_of`.

**Comment by x4exr** [comment]
Oh I forgot that existed. Mb Ill close this

**Pull request closed without merging**
