### PR TITLE
rustc_resolve: don't allow paths starting with `::crate`.

### PR DESCRIPTION
**Pull request by eddyb**
cc @aturon @joshtriplett 
r? @petrochenkov

### CODE REVIEW

**Comment by eddyb** [comment]
cc @nikomatsakis If we go down this path, chalk at least needs to be updated.
AFAIK `crate::...` without a leading `::` should work before this PR too.

**Comment by petrochenkov** [comment]
Implementation looks good to me, but I'd like to wait for other people's opinions.

I've seen an argument that `::crate` may be useful in scenarios like
```rust
macro m($crate_name: ident) {
   ::$crate_name::something();
}

m!(my_crate); // OK
m!(crate); // OK
```

**Comment by joshtriplett** [comment]
@petrochenkov Doesn't seem that hard to write `m!(::my_crate)` or `m!(crate)`, in that case.

**Comment by petrochenkov** [comment]
@joshtriplett 
>Doesn't seem that hard to write m!(::my_crate) or m!(crate), in that case.

Yes, this should be possible when https://github.com/rust-lang/rust/issues/48067 is implemented (paths cannot be easily concatenated in macros right now).

Anyway, prohibiting `::crate` is more conservative variant so we can do it now and re-allow again if it becomes necessary.

**Comment by petrochenkov** [comment]
Do we have a label "ping @rust-lang/lang, wait for a few days and then r+ even if nobody responded"?

**Comment by cramertj** [comment]
We discussed this in a previous meeting and I got the impression that there was consensus around `::<cratename>::..` being the one and only way to use leading-`::` in a path.

**Comment by Centril** [comment]
I second @cramertj. `::crate` should not be permitted; or at the very least I'd want to be conservative here.

**Comment by joshtriplett** [comment]
This still needs its build failures fixed (`s/::crate::/crate::/g` everywhere), but as soon as that happens, let's merge this.

**Comment by eddyb** [comment]
@rpjohnst The current interpretation isn't that, but rather that `crate` is a keyword just like `self` and `super`, that only appears at the start of a path, and changes it from the default mode (whichever it may be, Rust 2015 vs Rust 2015, with and without `uniform_paths`) to the root of the local crate.

**Comment by rpjohnst** [comment]
I get that interpretation, but the `::crate`/"`crate` is a crate name" mental model is a great way to explain the new system, and it would be a shame to lose it.

**Comment by rpjohnst** [comment]
Yeah, 2015 does make it messier. But perhaps allowing `crate` to resolve in the crate root makes sense there? That's where all the `extern crate` declarations go anyway, and `crate` really only needs to make sense in 2015 insofar as it's part of the transition path to 2018. :P

We could also allow `::crate` *only* in 2018, by allowing it to resolve in the 2018 root, if that feels less messy. Or maybe it makes it worse via interaction with the new prelude-like mechanism, I'm not sure how that works.

Regardless, `::` plays a smaller role in 2018, and that role doesn't intersect with `crate`, so maybe it doesn't matter.

**Pull request merged**
