### PR TITLE
Refactor supertrait handling

### PR DESCRIPTION
**Pull request by nikomatsakis**
The main gist of this PR is commit 1077efb which removes the list of supertraits from the `TraitDef` and pulls them into a separate table, which is accessed via `lookup_super_predicates`. This is analogous to `lookup_predicates`, which gets the complete where clause. This allows us to create the `TraitDef`, which contains the list generics and so forth, without fully knowing the list of supertraits. This in turn allows the _supertrait listing_ to contain references to associated types like `<Self as Foo>::Item`, which were previously impossible because conversion required having the `TraitDef` for `Foo`.

We do not yet support `Self::Item` in a supertrait listing. This doesn't work because to convert that, it attempts to expand out the full set of supertraits, which are in the process of being created. This could potentially be worked out by having the expansion of supertraits proceed in a lazy fashion, but we'd have to define shadowing rules for associated types which we don't currently have.

Along the way (in 9de9ec5) I also removed the restriction against duplicate bounds and generalized the code so that it can handle having the same supertrait multiple times with different arguments, e.g. `Foo : Bar<i32> + Bar<u32>`. This restriction was serving no particular purpose, since the same trait could be extended multiple times indirectly, and in the era of multidispatch it is actively harmful.

This is technically a [breaking-change] because it affects the definition of a super-trait. Anything in a where clause that looks like `where Self : Foo` is now considered a supertrait. Because cycles are disallowed in supertraits, that could lead to some errors. This has not been observed in any existing code.

r? @nrc

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @jroesch

**Comment by japaric** [comment]
> I also removed the restriction against duplicate bounds and generalized the code so that it can handle having the same supertrait multiple times with different arguments, e.g. Foo : Bar<i32> + Bar<u32>

:+1:

**Comment by nrc** [comment]
r+ with comments addressed

**Comment by nikomatsakis** [comment]
@bors r+ 9b332ff p=1

Giving higher priority because I believe this fixes a number of open associated type issues (probably more than I have tagged here).

**Comment by Manishearth** [comment]
@bors: retry

(Failed due to a force push, sorry)

**Pull request merged**
