### PR TITLE
library: Compute `RUST_EXCEPTION_CLASS` from native-endian bytes

### PR DESCRIPTION
**Pull request by workingjubilee**
This makes it appear correctly in hexdumps on both LE and BE platforms.

As discussed extensively in https://github.com/rust-lang/rust/pull/130381/files#r1760034980

### CODE REVIEW

**Comment by thomcc** [comment]
Nice. Not going to rollup this in case it causes issues and is needed to be identified in a bisection.

@bors r+ rollup=never

**Comment by nbdd0121** [comment]
Note that the Itanium exception ABI says that the convention is that high bit are for vendor and low bits are for language: https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html.

Perhaps put a relnote to say that the langauge is now renamed to MOZ? ;)

**Comment by workingjubilee** [comment]
> Note that the Itanium exception ABI says that the convention is that high bit are for vendor and low bits are for language: https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html.
> 
> Perhaps put a relnote to say that the langauge is now renamed to MOZ? ;)

:heavy_check_mark: MOZ from RUST

**Comment by RalfJung** [comment]
More like ZOM, no? "The low 4 bytes" would have a different order on little-endian than on big-endian.

If all other languages use `from_be_bytes`, then maybe we should, too?

**Comment by RalfJung** [comment]
Cc @rust-lang/libs

**Comment by purplesyringa** [comment]
Given that the class is modified anyway, should it be replace with `RUSTMOZ\0` instead for consistency?

**Comment by joshtriplett** [comment]
At the risk of bikeshedding, we could use `RUSTRUST`, since the vendor and language are now one and the same. :)

**Comment by RalfJung** [comment]
> Given that the class is changed anyway, should it be replaced with `RUSTMOZ\0` for consistency?

It's not changed, this PR just computes the same class in a different way.

**Comment by RalfJung** [comment]
> Note that the Itanium exception ABI says that the convention is that high bit are for vendor and low bits are for language: https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html.
> 
> Perhaps put a relnote to say that the langauge is now renamed to MOZ? ;)

In other words, we are now deviating from the official spec. That should have been discussed a bit more before it is shipped, IMO.

**Comment by purplesyringa** [comment]
I would advise against `RUSTRUST`, as it counterintuitively forces Rust compilers that use another ABI to replace "RUST". IMO, keeping MOZ would be more correct.

**Comment by workingjubilee** [comment]
@RalfJung We've already left the building: The only MUST there is that the de facto string includes `"C++\0"` if one is a C++ implementation and conforms exactly to the C++ exception-handling semantics.

As we have never exactly done so, it doesn't particularly matter how we handle the string because a C++ implementation won't recognize our exceptions as C++ exceptions, and probably shouldn't.

**Comment by nbdd0121** [comment]
Except the Itanium C++ exception ABI is the de facto standard for all unwinding on Linux and it specifies that "low 4 bytes indicate the language"?

**Comment by workingjubilee** [comment]
Which is Rust, yes.

And here it says:

>  Set the `exception_class` field in the unwind header. This is a 64-bit value representing the ASCII string "XXXXC++\0", where "XXXX" is a vendor-dependent string. That is, for implementations conforming to this ABI, the low-order 4 bytes of this 64-bit value will be "C++\0".

That's a "will".

So our real choices are to either say we're C++... which, again, we've never done, would be somewhat unusual, and we don't really have any proof that it's a good idea... or not.

And at that point what matters is that if someone examines the value they won't find "C++\0" in it.

**Comment by workingjubilee** [comment]
alternatively, on the subject of vendor vs. language bytes:
```rust
    println!("{}", "🦀".len()) // 4
```

**Comment by nbdd0121** [comment]
It also says
> The exception_class field is a language- and implementation-specific identifier of the kind of exception. It allows a personality routine to distinguish between native and foreign exceptions, for example. By convention, the high 4 bytes indicate the vendor (for instance HP\0\0), and the low 4 bytes indicate the language. For the C++ ABI described in this document, the low four bytes are C++\0.

And this what people do:

D sets it to DMD\0D\0\0\0: https://github.com/dlang/dmd/blob/4b94c9facf46a4167acfdc83ed9a92c5bc88c583/druntime/src/rt/dwarfeh.d#L139
GCJ sets it to GNUCJAVA (although this is no longer relevant because GCJ is dead).
GNAT sets it to GNU-ADA: https://github.com/gcc-mirror/gcc/blob/0b22f0585348335369298c7d39afd171758eebe9/gcc/ada/libgnat/s-excmac__arm.ads#L101
Probably there're other examples in the wild.

This can be useful for telling people what foreign exception is caught when we eventually support catching them. I don't think we gain much for not following the convention here.

**Comment by workingjubilee** [comment]
Does anyone pattern match on the language names that aren't their own?

**Comment by workingjubilee** [comment]
It's a fairly trivial change, so I'm not particularly fussed by which... ah... *end* we want to start from. My main drive was to actually compute it from the string data it is (written backwards though it may be) instead of having an inscrutable constant.

By the way, the ABI docs mention `HP\0\0` as the "example" vendor.

...the Itanium was bi-endian, and HP-UX uses big endian.

**Comment by RalfJung** [comment]
> Does anyone pattern match on the language names that aren't their own?

I don't think that matters. There is an existing recommendation in the spec, and it is widely followed by implementations. We shouldn't diverge from that without a really good reason, and IMO we don't have a good reason.

**Pull request merged**
