### PR TITLE
Unused doc comments blocks

### LINKED ISSUE #77030: doc comments on extern blocks are ignored
For the following snippet
```rust
/// Hey
extern "C" {
    /// Ho
    pub fn test();
}
```
`test` is documented with `Ho` but `Hey` is nowhere to be found. It probably makes sense to error/warn if doc comments are used on extern blocks

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #77030.

### CODE REVIEW

**Comment by estebank** [comment]
r=me. I wonder how much fallout there will be in the wild.

**Comment by GuillaumeGomez** [comment]
None normally since it's a warning. But I expect a few crates to now have this warning. :)

**Comment by GuillaumeGomez** [comment]
I failed pretty impressively the r+...

@bors: r=estebank

**Comment by matthiaskrgr** [comment]
@GuillaumeGomez is the stdarch submodule change intended?

**Comment by GuillaumeGomez** [comment]
Yes it was.

And you saw it so all good. :laughing:

**Pull request merged**
