### PR TITLE
Remove the push_unsafe! and pop_unsafe! macros.

### PR DESCRIPTION
**Pull request by nrc**
This is a [breaking change].

@brson could you do a Crater run with this PR please?

Lets not land till Crater says its OK.

This was discussed at https://internals.rust-lang.org/t/does-anyone-use-the-push-pop-unsafe-macros/2702

### CODE REVIEW

**Comment by alexcrichton** [comment]
I've scheduled a crater run

**Comment by nrc** [comment]
Thanks!

**Comment by alexcrichton** [comment]
Crater reports [one regression](https://gist.github.com/alexcrichton/b21416d2048163eb595e) but seems spurious/

**Comment by nrc** [comment]
Hmm, and the repo link is broken too - https://github.com/vberger/wayland-kdb

**Comment by nrc** [comment]
@bors: r=@pnkfelix

(y u no see r+?)

**Pull request merged**
