### PR TITLE
Use less syscalls in `FileDesc::set_{nonblocking,cloexec}`

### PR DESCRIPTION
**Pull request by tbu-**
Only set the flags if they differ from what the OS reported, use
`FIONBIO` to atomically set the non-blocking IO flag on Linux.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by nagisa** [comment]
`FIONBIO` is supported by pretty much every recent BSD as well.

**Comment by tbu-** [comment]
@nagisa It's hard to find docs on `ioctl`s, do you know any sources?

**Comment by nagisa** [comment]
@tbu- not really. This is a pretty obscure API and hence rarely documented. I know it to work because I had opportunity to test it out in an actual system.

[mio](https://github.com/carllerche/mio/blob/master/src/sys/unix/io.rs#L11) may be a good indicator it “works” as it uses this API unconditionally.

**Comment by joshtriplett** [comment]
You may also want to document, in the documentation for `set_cloexec`, that you often want to open with cloexec already set rather than setting it afterward, and show how to do that.  (Doing it within open avoids a race that can leak file descriptors to child processes.)

**Comment by tbu-** [comment]
@joshtriplett This is private API as far as I can tell, and it's only used in places where we already pass `O_CLOEXEC`. It's apparantly just for old kernels which are either unaware of `O_CLOEXEC` or have a bug relating to it.

**Comment by joshtriplett** [comment]
@tbu- Ah, OK; thanks for the clarification.

**Pull request merged**
