### PR TITLE
test: Ignore some problematic tests on sparc and sparc64

### PR DESCRIPTION
**Pull request by glaubitz**
This updates the list of tests which can be safely ignored on sparc and sparc64.

### CODE REVIEW

**Comment by glaubitz** [comment]
Hmm, I don't think that my changes should have any effect on the CI tests.

Can someone retry this?

**Comment by glaubitz** [comment]
Testsuite passes now. Anyone can pick this?

@shepmaster Could you pick this? I can then also take care of 51237.

**Comment by shepmaster** [comment]
See, I told you that the error locations changed ;-)

@bors r+ rollup

**Comment by glaubitz** [comment]
Jaja :P. It took me a while to understand what the problem was. Thanks for the review!

**Pull request merged**
