### PR TITLE
Guard against non-monomorphized type_id intrinsic call

### LINKED ISSUE #73976: TypeId doesn't match itself in generic function.
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=57bb53139f14a69326e005ea9d9f7cd7
```rust
#![feature(const_type_id)]

use std::any::TypeId;

pub struct GetTypeId<T>(T);

impl<T: 'static> GetTypeId<T> {
    pub const VALUE: TypeId = TypeId::of::<T>();
}

const fn check_type_id<T: 'static>() -> bool {
    matches!(GetTypeId::<T>::VALUE, GetTypeId::<T>::VALUE)
}

fn main() {
    assert!(check_type_id::<usize>());
}
```

I expected the code to run without errors

Instead, the assertion failed.

### Meta

Compiler version: 1.46.0-nightly (2020-07-01 f781babf87dea29c44f9)

### PR DESCRIPTION
**Pull request by nbdd0121**
This PR checks whether the type is sufficient monomorphized when calling type_id or type_name intrinsics. If the type is not sufficiently monomorphized, e.g. used in a pattern, the code will be rejected.

Fixes #73976

### CODE REVIEW

**Review by lcnr — APPROVED** [review]
Can you also add a test for `type_name`?

Something like
```rust
#![feature(const_type_name)]

fn test<T: 'static>() {
    let _ = [0; {
        std::any::type_name::<T>();
        7
    }];
    //~^ ERROR constant expression depends on a generic parameter
}
```

**Comment by lcnr** [comment]
We also probably want a test using `type_name` or `type_id` in a fully monomorphic pattern here to see that this doesn't break

**Comment by nbdd0121** [comment]
Added.

**Comment by lcnr** [comment]
Thanks @bors r+ rollup=always

**Pull request merged**
