### PR TITLE
Add `fs::append`

### PR DESCRIPTION
**Pull request by ibraheemdev**
```diff
- OpenOptions::new().create(true).append(true).open(path)?.write_all(contents)
+ fs::append(path, contents)
```

### CODE REVIEW

**Comment by joshtriplett** [comment]
@ibraheemdev Having a shorthand to open a file in append mode seems *potentially* reasonable, yeah. I don't think it's obvious that such a shorthand should include `create`, though. I could imagine having `File::append(path)` and `File::create_append(path)` helpers, just as we currently have `File::create(path)`. I'm not suggesting we add all combinations of options here, but those two helpers seem like potentially worthwhile shorthands.

**Comment by JohnCSimon** [comment]
ping from triage:
@ibraheemdev  
Returning to you to address reviewer comments.

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot author

**Comment by JohnCSimon** [comment]
Ping from triage: @ibraheemdev - can you continue with this PR?

**Comment by JohnCSimon** [comment]
@ibraheemdev 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
