### PR TITLE
update Miri

### LINKED ISSUE #99461: `miri` no longer builds after rust-lang/rust#99451
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#99451, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @Dylan-DPC, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/99461
r? @oli-obk because of lockfile changes (seems like serde is getting implicitly bumped)

### CODE REVIEW

**Comment by oli-obk** [comment]
Oh no, seems like I broke miri in rustc after all... my local testing must have picked up the rustc from rustup. I'll get this fixed tomorrow, should be straight forward

**Comment by RalfJung** [comment]
Argh
```
      error: failed to create directory `/checkout/src/tools/miri/target/test_dependencies`
      Caused by:
        Read-only file system (os error 30)
```

**Comment by RalfJung** [comment]
We are getting there, slowly. Just a bit more normalization:
```
Diff< left / right > :
 error: unsupported operation: can't call foreign function: epoll_create1
<  --> CARGO_REGISTRY/epoll.rs:LL:CC
>  --> /cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.4/src/sys/PLATFORM/selector/epoll.rs:LL:CC
```

**Pull request merged**
