### PR TITLE
Fix #31502

### LINKED ISSUE #31502: std::env::home_dir() is buggy on Windows
The underlying Win32 API `GetUserProfileDirectory()` is used in a wrong way:

- https://msdn.microsoft.com/en-us/library/windows/desktop/bb762280%28v=vs.85%29.aspx

It is the in/out parameter `lpcchSize` rather than the function return value that contains the number of bytes of the returned data.  As a result, when neither `HOME` nor `USERPROFILE` is set, `std::env::home_dir()` returns a truncated string `"C"` when it should return `"C:\Users\nodakai"`, for example.

I'd rather call this bug a result of a lack of idioms for robust interfacing with external C APIs than an instance of careless programming.

How do you like the idea of changing `std::sys::c::BOOL` to an enum with `repr(i32)` ?  That should be a zero-cost abstraction and `std::sys::c` will remains a thin wrapper of Win32 API.

### PR DESCRIPTION
**Pull request by retep998**
This is the simple solution. I know @nodakai was working on a more complex solution that overhauled the `fill_utf16_buf` stuff.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can you edit the commit message to explain what's going on as well? It helps to have some more context than just "Fix #XXXX" 

Otherwise looks good to me, though, thanks!

**Comment by retep998** [comment]
Renamed commit message.

**Comment by nodakai** [comment]
Can you extend the unit test to make sure the new version indeed fixes the bug?  How about calling [`is_dir()`](http://doc.rust-lang.org/nightly/std/fs/struct.FileType.html#method.is_dir)?  It should succeed on most environments.

**Comment by retep998** [comment]
The unit test won't actually test that branch since it requires `HOME` and `USERPROFILE` be unset.

**Comment by nodakai** [comment]
Take a look: https://github.com/rust-lang/rust/blob/master/src/test/run-pass/env-home-dir.rs#L33

**Comment by retep998** [comment]
Oh, I didn't notice we had a run-pass test specifically for that. I guess it could benefit from a more aggressive check. That said, since this PR already landed I'm rather unmotivated to adjust that test.

**Pull request merged**
