### PR TITLE
Change explicit BytesDeref impl into Cloned iterator

### PR DESCRIPTION
**Pull request by nagisa**

### CODE REVIEW

**Comment by bluss** [comment]
Thinking about the parallel .count() etc change to Bytes, I'm not sure we should do this. Can we specialize `.count()` on Cloned to bypass cloning and ask the inner iterator? The difference is user observable.

**Comment by nagisa** [comment]
@bluss https://github.com/rust-lang/rust/pull/28125

**Comment by bluss** [comment]
Thanks for the pointer

**Comment by nagisa** [comment]
I don’t have any idea why the test failed here.

**Pull request merged**
