### PR TITLE
Clean up rustdoc css

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @rust-lang/docs

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
To summarize a bit what I did:

 * Replacement of whitespaces with tabulations.
 * Move color attributes to the "color" file.

**Comment by steveklabnik** [comment]
> Replacement of whitespaces with tabulations.

I am not a fan of this, but if everyone else wants to, i will not fight it

**Comment by GuillaumeGomez** [comment]
It's css and it's already the case for almost every line.

**Comment by frewsxcv** [comment]
> It's css 

CSS doesn't need to use tabs. In fact, this is the first time I've seen CSS with tabs.

> it's already the case for almost every line

This argument makes more sense though. In general, I'm in favor of spaces over tabs, but in this case, consistency seems more important. We can discuss about potentially migrating to spaces in a different PR.

**Comment by ollie27** [comment]
`src/librustdoc/html/static/rustdoc.css` was mostly converted to tabs by #37134. `src/doc/rust.css` and `src/librustdoc/html/static/styles/main.css` both use spaces.

**Comment by GuillaumeGomez** [comment]
> CSS doesn't need to use tabs. In fact, this is the first time I've seen CSS with tabs.

Simply because they generally use minifier in order to reduce network impact. However, in CSS it's still the norm to use tabs as far as I can tell.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by frewsxcv** [comment]
Have you tested to make sure this doesn't affect the [new sidebar changes](https://github.com/rust-lang/rust/pull/40265)? If so, r=me

**Comment by GuillaumeGomez** [comment]
It just moves color setting from one file to another, nothing else. I can still confirm otherwise if you want to be absolutely sure. As your prefer.

**Pull request merged**
