### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by oli-obk**
r? @Manishearth

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @nrc also updating rls in here

**Comment by alexcrichton** [comment]
Hm it looks like this broke the RLS presumably because clippy is succeeding but the RLS is still using an older version? (but clippy succeeding causes rustbuild to enable clippy in the RLS I think).

cc @nrc

**Comment by oli-obk** [comment]
That shouldn't matter. Rls in the rustc repo uses the working one, not the crates.io one

**Pull request merged**
