### PR TITLE
Bump to 1.82

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
https://forge.rust-lang.org/release/process.html#bump-the-stable-version-number-t-6-days-friday-the-week-before

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by klensy** [comment]
Wait, there is error, why it merging?

**Comment by tgross35** [comment]
I don't think bors cares about errors from PR CI, but it will probably fail there too. Weird error

**Comment by tgross35** [comment]
Ah I commented half a second too late

**Pull request merged**
