### PR TITLE
Update cargo.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Pulls https://github.com/rust-lang/cargo/pull/7417/commits/f3c92ed52e65b10444020ea453c5823ab4d5ec37 into nightly Rust. 

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

(also cc @ehuss on this)

**Comment by jonas-schievink** [comment]
This probably deserves a mention in the next release's blog post, right? (since we mentioned PGO when it got stabilized)

**Comment by ehuss** [comment]
This will break RLS.  I normally wait for [the fix](https://github.com/rust-lang/rls/pull/1562) to merge and then update them together to reduce the churn and disruption.  It's not a big deal, but I feel like our process is not working well.

**Comment by Xanewok** [comment]
The fix has landed in the RLS so you can also update the RLS submodule as well.

**Comment by Xanewok** [comment]
Dear, fat-fingered this one. Sorry.

**Comment by tmandry** [comment]
@bors retry rolled up

Also: bors seems stuck, the queue page says it's building this PR but I don't see any notification here that it's building.

**Comment by tmandry** [comment]
This appears to have failed in #64966, see [this log](https://dev.azure.com/rust-lang/rust/_build/results?buildId=9630).
@bors r-

**Comment by alexcrichton** [comment]
@bors: r+

Included a fix for that failed test as well as an RLS update

**Pull request merged**
