### PR TITLE
don't suggest placing `use` statements into expanded code

### LINKED ISSUE #44210: Error suggestions for import contain erroneous `derive`
E.g.,
```
error[E0412]: cannot find type `Path` in this scope
  --> src/actions/compiler_message_parsing.rs:77:55
   |
77 | fn make_suggestions(message: &CompilerMessage, file: &Path) -> Vec<Suggestion> {
   |                                                       ^^^^ not found in this scope
   |
help: possible candidates are found in other modules, you can import them into scope
   |
20 | #[derive(use build::rustc::rustc::hir::Path;
   |
20 | #[derive(use build::rustc::syntax::ast::Path;
   |
20 | #[derive(use std::path::Path;
```

cc @oli-obk

### PR DESCRIPTION
**Pull request by oli-obk**
r? @nrc

fixes #44210

```rust
#[derive(Debug)]
struct Foo;

type X = Path;
```

will try to place `use std::path::Path;` between `#[derive(Debug)]` and `struct Foo;`

I am not sure how to obtain a span before the first attribute, because derive attributes are removed during expansion.

It would be trivial to detect this case and place the `use` after the item, but that would be somewhat weird I think.

### CODE REVIEW

**Comment by oli-obk** [comment]
I need a decision on how to continue here.

1. don't remove `derive` (currently causes infinite expansion, not sure how to fix)
2. remove derive contents (lints about `#[derive()]` being bad, can tag somehow or simply allow empty derives)
3. replace with `#[removed_attribute_placeholder]` and mark it as some internal NOP attribute which only exists for diagnostics

**Comment by petrochenkov** [comment]
@oli-obk 
Could you remind why issues like https://github.com/rust-lang/rust/issues/44210 happen in the first place.
Why isn't the suggestion attached to `Path`?

All I remember is that everything worked okay some time ago, but then some "suggestion diagnostics reform" happened and issues like this started to appear.

**Comment by oli-obk** [comment]
These things happen, because we are not producing help messages telling you what to insert, but we are producing suggestions, which contain a span that is supposed to be replaced. The human readable interface then applies the replacement and prints it. If the span is bogus, we get things like these.

Figuring out where to place things can be difficult. Much more than I anticipated when I did the original change. But doing this is the right thing imo, because it will allow IDEs to enable users to insert missing import statements with a click

**Comment by oli-obk** [comment]
> Why isn't the suggestion attached to Path?

What do you mean by that?

**Comment by petrochenkov** [comment]
>which contain a span that is supposed to be replaced

Ah, I see. So, the span for import suggestions is not span of `Path`, but span of the place (probably somewhere at the start of the file) into which these imports are supposed to be inserted.
This is good for tools, but it was a mistake to use this "insertion span" for user visible diagnostics, IMO.

**Comment by oli-obk** [comment]
> This is good for tools, but it was a mistake to use this "insertion span" for user visible diagnostics, IMO.

We could differentiate between insertion suggestions and replacement suggestions by not showing surroundings for insertion suggestions (at least if they insert a whole new line)

**Comment by oli-obk** [comment]
We can also merge this (it will solve the visual bugs, but not the structured placement of the suggestions), and fix https://github.com/rust-lang/rust/pull/44215#issuecomment-326986760 later

**Comment by oli-obk** [comment]
r? @arielb1 irc discussion seems to suggest some urgency on this. I can do changes until tuesday, then I'm on vacation.

My suggestion is to merge it as it is, and fix the structured json output later (the spans are wrong, the command line output can now never be wrong again barring missing expansion info on spans)

**Comment by oli-obk** [comment]
I will be on vacation starting now, so if there are any change requests, I won't be able to do anything about them until Rustfest.

The travis failure is bogus (not in the travis builder).

**Comment by arielb1** [comment]
r? @nrc

I don't know this area of the code

**Comment by arielb1** [comment]
This is, however, an annoying beta regression. The beta deadline is less than 2 weeks from now. It would be nice to see what can be done to get this fixed for beta.

**Comment by nrc** [comment]
Yeah, this fix looks good to me, we can address making the IDE case perfect later, but this is already much better than before.

**Comment by oli-obk** [comment]
Removed WIP from title

**Comment by nikomatsakis** [comment]
Nominating for backport as this fixes a stable-to-beta regression (https://github.com/rust-lang/rust/issues/44566)

**Comment by alexcrichton** [comment]
@oli-obk or @nikomatsakis would y'all be willing to help out with the backport here? Apparently[this doesn't apply cleanly](https://github.com/rust-lang/rust/pull/44823#issuecomment-332086317)

**Pull request merged**
