### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #72598 (Display information about captured variable in `FnMut` error)
 - #72804 (Further tweak lifetime errors involving `dyn Trait` and `impl Trait` in return position)
 - #72932 (Clarify the behaviour of Pattern when used with methods like str::contains)
 - #73044 (compiletest: Add directives to detect sanitizer support)
 - #73065 (Fix link error with #[thread_local] introduced by #71192)
 - #73086 (Rename "cyclone" to "apple-a7" per changes in upstream LLVM)
 - #73267 (Use the built cargo for cargotest.)
 - #73290 (Fix links when pinging notification groups)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
CI already failed but bors did not notice yet, or what is happening...?

**Comment by RalfJung** [comment]
Oh, the failing one is GHA, which we currently don't gate on. But let's assume the Azure runner will also fail.

**Comment by trevyn** [comment]
Where is the failing GHA?

**Comment by RalfJung** [comment]
Here: https://github.com/rust-lang-ci/rust/runs/767801939

@bors r- retry

**Comment by trevyn** [comment]
Ah, a bunch of sanitizer stuff. #73044?

**Comment by RalfJung** [comment]
Where do you see sanitizer stuff? https://github.com/rust-lang/rust/pull/73065 was identified by @tmiasko and I agree with that.

**Comment by RalfJung** [comment]
Oh there was a second one. But how did you get that from the link I posted?^^

**Comment by trevyn** [comment]
Was from azure :)

**Comment by RalfJung** [comment]
A link to the concrete log would have been very helpful. :)

**Pull request closed without merging**
