### PR TITLE
Stabilize native library modifier `verbatim`

### LINKED ISSUE #99425: Tracking Issue for native link modifier `verbatim`
This is a tracking issue for native link modifier `verbatim`, which is a part of RFC "Linking modifiers for native libraries" (https://github.com/rust-lang/rust/issues/81490, https://github.com/rust-lang/rfcs/pull/2951).
The feature gate for the issue is `#![feature(native_link_modifiers_verbatim)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps
- [ ] Implement the RFC - #83507
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

`-l:libfoo.a` is not entirely verbatim, there's still no way to pass a library by full path (without the `-l` option), like `/path/to/libfoo.a`, while still respecting relative order of passed libraries, `-C link-arg=/path/to/libfoo.a` will put the option at the end of the command line instead.
`-l link-arg=/path/to/libfoo.a` (https://github.com/rust-lang/rust/issues/99427) will likely help with this situation.

### PR DESCRIPTION
**Pull request by petrochenkov**
Stabilization report - https://github.com/rust-lang/rust/pull/104360#issuecomment-1312724787.

cc https://github.com/rust-lang/rust/issues/81490
Closes https://github.com/rust-lang/rust/issues/99425

### CODE REVIEW

**Comment by petrochenkov** [comment]
# Stabilization Report

This PR stabilizes native library modifier `verbatim`, a part of RFC 2951: "Linking modifiers for native libraries" (tracking issue https://github.com/rust-lang/rust/pull/99425).
The RFC was implemented about 1.5 years ago in https://github.com/rust-lang/rust/pull/83507.

## `verbatim` modifier

This modifier is compatible with all linking kinds.

`+verbatim` means that rustc itself won't add any target-specified library prefixes or suffixes
(like `lib` or `.a`) to the library name, and will try its best to ask for the same thing from the
linker.

For `ld`-like linkers supporting GNU extensions rustc will use the `-l:filename` syntax (note the
colon) when passing the library, so the linker won't add any prefixes or suffixes to it.
See [`-l namespec`](https://sourceware.org/binutils/docs/ld/Options.html) in ld documentation for
more details. \
For linkers not supporting any verbatim modifiers (e.g. `link.exe` or `ld64`) the library name will
be passed as is. So the most reliable cross-platform use scenarios for this option are when no
linker is involved, for example bundling native libraries into rlibs.

`-verbatim` means that rustc will either add a target-specific prefix and suffix to the library
name before passing it to linker, or won't prevent linker from implicitly adding it. \
In case of `raw-dylib` kind in particular `.dll` will be added to the library name on Windows.

The default for this modifier is `-verbatim`.

NOTE: Even with `+verbatim` and `-l:filename` syntax `ld`-like linkers do not typically support
passing absolute paths to libraries. Usually such paths need to be passed as input files without
using any options like `-l`, e.g. `ld /my/absolute/path`. \
`-Clink-arg=/my/absolute/path` can be used for doing this from stable `rustc` (and `-l link-arg`
from unstable rustc).

## Test cases

- `src/test/run-make/native-link-modifier-verbatim-*`
- `src/test/run-make/rlib-format-packed-bundled-libs-2`
- `src/test/run-make/raw-dylib-c`

## Documentation

https://github.com/rust-lang/reference/pull/1299

**Comment by petrochenkov** [comment]
@rfcbot fcp merge

**Review by wesleywiser — APPROVED** [review]

**Pull request merged**
