### PR TITLE
have on_completion record subcycles

### LINKED ISSUE #83538: Trait evaluation cache interacts badly with incremental compilation
PR https://github.com/rust-lang/rust/pull/83220 solved one issue with the trait evaluation cache, but I've found another one.

On the `perf` server, `syn` is currently causing the following ICE:

```
Compiling syn v0.11.11 (/tmp/.tmpnHQAja) ...

thread 'rustc' panicked at 'found unstable fingerprints for evaluate_obligation(e3352ed64d6e2ccd-c82ee1c6b3ce2c20): Ok(EvaluatedToOk)', /rustc/b8719c51e0e44483cff9b6975a830f6e51812a48/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (b8719c51e 2021-03-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z self-profile=/tmp/.tmpnHQAja/self-profile-output -C opt-level=3 -C embed-bitcode=no -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `quote::Tokens: std::marker::Unpin`
#1 [is_unpin_raw] computing whether `quote::Tokens` is `Unpin`
end of query stack
warning: 49 warnings emitted

thread 'main' panicked at 'assertion failed: status.success()', collector/src/rustc-fake.rs:76:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `syn`
```

I've created a standalone repository that reproduces this crash: https://github.com/Aaron1011/syn-crash

The following shell script can be used to reproduce the ICE: 

```
set -xe

cargo clean -p syn
cargo clean --release -p syn
git checkout ee2bcdef16fc2b23a7becdcd5dcb361e085db75a
cargo build --release -j 1
git checkout 9ba859003d06df084b860fa62780dbf9169870d6
cargo build --release -j 1
```

**EDIT**: This appears to be due to the way we handle caching for a coinductive cycle.

<strike>
The root cause appears to be here:

https://github.com/rust-lang/rust/blob/5e65467eff3d1da4712586d8402d1d2e1d6654bc/compiler/rustc_trait_selection/src/traits/select/mod.rs#L390-L407

The `evaluation_probe` method is used (among other things) to wrap the call to `evaluate_predicate_recursively` when we are trying to evaluate a root obligation. This means that *any* region constraints that get created during evaluation (including the recursive evaluation of other predicates) will cause us to return `EvaluatedToOkModuloRegions`.

However, whether or not we end up creating region constraints depends on the state of the evaluation cache - if we get a cache hit, we may skip creating a region constraint that would have otherwise been created. This means that re-running predicate evaluation during incremental compilation may produce a different result.

I see a few different ways of fixing this:
1. When we store a result in the evaluation cache, also store whether or not it caused any region constraints to get created. We then use this information when recursively processing predicates to ensure that we return `EvaluatedToOkModuloRegions` even if we got a cache hit.
2. Always return `EvaluatedToOk` when there are no erased regions in our original predicate (in this case, `quote::Tokens: Unpin`. I don't actually know if this is sound - there are no 'input' region variables to worry about, but I'm not sure if safe to ignore any 'internal' region constraints that get added.
3. Remove `EvaluatedToOk` entirely, and always return `EvaluatedToOkModuloRegions`. I'm not sure what the performance impact of doing this would be, or how much refactoring it would require. However, this would eliminate a large source of potential ICEs.

I'm not familiar enough with the trait evaluation code to know which, if any, of those options is the best choice.

</strike>

cc @nikomatsakis @matthewjasper

### PR DESCRIPTION
**Pull request by nikomatsakis**
have on_completion record subcycles

Rework `on_completion` method so that it removes all
provisional cache entries that are "below" a completed
node (while leaving those entries that are not below
the node).

This corrects an imprecise result that could in turn lead
to an incremental compilation failure. Under the old
scheme, if you had:

* A depends on...
   * B depends on A
   * C depends on...
       * D depends on C
 * T: 'static

then the provisional results for A, B, C, and D would all
be entangled. Thus, if A was `EvaluatedToOkModuloRegions`
(because of that final condition), then the result for C and
D would also be demoted to "ok modulo regions".

In reality, though, the result for C depends only on C and itself,
and is not dependent on regions. If we happen to evaluate the
cycle starting from C, we would never reach A, and hence the
result would be "ok".

Under the new scheme, the provisional results for C and D
are moved to the permanent cache immediately and are not affected
by the result of A.

Fixes #83538 

r? @Aaron1011

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@Aaron1011 maybe it would be good to do a talk through session -- this relates to my goal of building up expertise around the trait system. I'll leave a comment on Zulip.

**Comment by nikomatsakis** [comment]
OK, I finally found a way to test this issue in a satisfactory way. I've included tests both for the original problem and the ICE we found in rustdoc. I also spent some time talking over how it works with @jackh726, [which you can watch here](https://t.co/hEYmHtXb99?amp=1). 

r? @jackh726

**Comment by nikomatsakis** [comment]
Uuuuuggh :)

**Review by jackh726 — APPROVED** [review]

**Comment by jackh726** [comment]
Thanks @nikomatsakis for going over this with me (and for all those that watch the recording)

This is a surprising simple change for an extremely complex issue. It is subtle though, so regardless of perf results, I want to @bors rollup=never

That being said, r=me when perf is done.

**Comment by nikomatsakis** [comment]
Nominating for beta and stable backport. These incremental failures are a big problem.

**Comment by apiraino** [comment]
Both backports have been discussed and pushed to next week's T-compiler meeting ([Zulip log](https://zulip-archive.rust-lang.org/238009tcompilermeetings/21853weekly2021052054818.html#239599378))

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/41941steeringmeeting20210528fingerprintsand15384970.html#240615636) in steering meeting about incr-comp fingerprints

declining to backport for beta and likewise for stable.

**Pull request merged**
