### PR TITLE
Add `RefCell::take`

### PR DESCRIPTION
**Pull request by ThinkChaos**
Add `RefCell::take` to match `Cell` and `Option`.
I also changed a couple of calls to `.replace` to `.take`.

Tracking issue is #71395.

This is my first contribution, please tell me if there's anything I could improve, thanks!

### CODE REVIEW

**Comment by therealprof** [comment]
I don't think we should have the `#[inline]` attributes added here (unless there's a good reason to do it?) but the rest looks very good and useful to me.

**Comment by ThinkChaos** [comment]
I removed the inline attributes :)

**Review by LukasKalbertodt — CHANGES_REQUESTED** [review]
Thanks for your PR and please excuse my late response. Looks like a useful addition! Just one inline comment.

As this is a tiny feature, I think the doc example is sufficient as test. The PR adding `Cell::take` (#39287) also didn't add any tests.

**Comment by ThinkChaos** [comment]
No worries, thanks for the review!

I copied the docs from `RefCell::replace`.

**Review by LukasKalbertodt — APPROVED** [review]

**Comment by Dylan-DPC** [comment]
included in rollup, yielding 

@bors retry

**Pull request merged**
