### PR TITLE
Point to enclosing block/fn on nested unsafe

### LINKED ISSUE #39144: Explicit warning on nested unsafe blocks
When refactoring code, it's easy to accidentally end up with nested `unsafe` blocks. This can lead to confusing rustc errors.

```rust
unsafe fn very_dangerous() -> u64 {
    1
}

fn main() {
    unsafe {
        // lots of code...
        
        unsafe {
            very_dangerous();
        }
    }
```

The compiler says:

```
rustc 1.16.0-nightly (ff591b6dc 2017-01-15)
warning: unnecessary `unsafe` block, #[warn(unused_unsafe)] on by default
  --> <anon>:9:9
   |
9  |           unsafe {
   |  _________^ starting here...
10 | |             very_dangerous();
11 | |         }
   | |_________^ ...ending here
```

This is surprising at first glance, since `very_dangerous` requires an `unsafe` block but the message implies otherwise. Could we warn about nested `unsafe` blocks?

### PR DESCRIPTION
**Pull request by estebank**
When declaring nested unsafe blocks (`unsafe {unsafe {}}`) that trigger
the "unnecessary `unsafe` block" error, point out the enclosing `unsafe
block` or `unsafe fn` that makes it unnecessary.

Fixes #39144.

### CODE REVIEW

**Comment by estebank** [comment]
Another option is to use `span_label` instead of `span_help`:

**Comment by durka** [comment]
Might want to carve out an exception for unsafe blocks within macros.

**Comment by estebank** [comment]
cc @nikomatsakis @jonathandturner

**Comment by nikomatsakis** [comment]
@estebank this seems nice; but it'd be nicer still if we used a more targeted span (i.e., just the `unsafe` keyword).

**Comment by estebank** [comment]
@nikomatsakis There's only one reason I'm reticent to that suggestion: The current presentation will only be as shown if the block is less than 8 lines (showing only the first line that contains the keyword otherwise), *and* I'm looking into making the multiline presentation smarter about longer blocks (instead of using the first line, showing the first X and last Y lines). I feel it is useful to know both the start *and* end of the enclosing block (as not everyone will know about "jump to closing brace" in their editor) when possible. 

What do you think?

**Comment by nikomatsakis** [comment]
@estebank I think people can find the end of their blocks ok, personally. But also, I sort of like the "collapsed" error where both of the unsafe blocks are shown simultaneously, but 

- we should make sure to put a label on the primary span (i.e., `^^^ unnecessary unsafe block`), since it looks really weird otherwise 
- I guess it just seems kind of heavy with the ascii art; I'm very happy we have it, but I'd prefer for it to be more unusual

**Comment by arielb1** [comment]
Personally, I don't like errors with separate spans - it blasts the console too much.

**Comment by arielb1** [comment]
The code seems ok. I think r? @jonathandturner

**Comment by jonathandturner** [comment]
Seems like a legit failure:

```
error: no field `map` on type `rustc::ty::TyCtxt<'_, '_, '_>`

   --> /checkout/src/librustc_lint/unused.rs:194:36

    |

194 |             let parent_id = cx.tcx.map.get_parent_node(id);

    |                                    ^^^ unknown field

error: no field `map` on type `rustc::ty::TyCtxt<'_, '_, '_>`

   --> /checkout/src/librustc_lint/unused.rs:201:30

    |

201 |                 })) = cx.tcx.map.find(parent_id) {

    |                              ^^^ unknown field

error: no field `map` on type `rustc::ty::TyCtxt<'_, '_, '_>`

   --> /checkout/src/librustc_lint/unused.rs:219:41

    |

219 |                     db.span_note(cx.tcx.map.span(id),

    |                                         ^^^ unknown field

```

**Comment by rkruppe** [comment]
FYI: The fix for this is simply using `tcx.hir` instead of `tcx.map`.

**Comment by estebank** [comment]
@jonathandturner fixed merge conflict.

**Comment by estebank** [comment]
Rebased against master HEAD.

**Comment by estebank** [comment]
@jonathandturner [need](https://travis-ci.org/rust-lang/rust/jobs/208087340#L7862) a @bors retry

```
failed to execute command: "sh" "/checkout/src/liballoc_jemalloc/../jemalloc/configure" "--disable-fill" "--host=s390x-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu"
error: No such file or directory (os error 2)
```

**Comment by alexcrichton** [comment]
@bors: retry

cc @petrochenkov is that error perhaps related to the recently landed code for caching jemalloc across stages? An error like that would show up when cwd doesn't exist. Rustbuild is also a little nondeterministic in step execution order, which may explain why it's spurious.

**Comment by petrochenkov** [comment]
@alexcrichton 
The error is
```
failed to execute command: "sh" "/checkout/src/liballoc_jemalloc/../jemalloc/configure"
error: No such file or directory (os error 2)
```
This doesn't look related to caching since it can't find source and not build results.
This looks like maybe `jemalloc` submodule is not checked out in time, so there's no `configure`, but this is not confirmed by logs.
Moreover, `configure` seems to be in place just before running running the command:
```
cargo:rerun-if-changed=/checkout/src/liballoc_jemalloc/../jemalloc/configure
```
cwd doesn't seem to be used here, `CARGO_MANIFEST_DIR` is used instead.
Maybe `configure` is a red herring and there's no `sh`? o_O
Mysterious.

**Comment by alexcrichton** [comment]
@bors: retry

Seems like we got unlucky with caches...

**Comment by alexcrichton** [comment]
@bors: retry

* sccache failure https://github.com/rust-lang/rust/issues/40240

**Comment by alexcrichton** [comment]
@bors: retry

* sccache failure https://github.com/rust-lang/rust/issues/40240

**Pull request merged**
