### PR TITLE
Update Cargo.lock to use the latest `compiler_builtins`

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
A very tiny PR per the request of @alexcrichton : rust-lang-nursery/compiler-builtins#267 (comment)

Rewrite of #57414 

cc @Lokathor

r? @alexcrichton

### CODE REVIEW

**Comment by oli-obk** [comment]
Is there any particular reason why we're not bumping the version in the various `Cargo.toml`s? E.g. in

https://github.com/rust-lang/rust/blob/7ad470c0a64ed0801708cee6657e82be097a29ac/src/liballoc/Cargo.toml#L14

**Comment by alexcrichton** [comment]
@bors: r+

@oli-obk I see that as an optional but probably recommended step, I don't think we're trying to avoid that at all.

**Comment by Dylan-DPC** [comment]
@alexcrichton this is ready for merging

**Comment by Dylan-DPC** [comment]
@alexcrichton this is ready for a r+ before another PR knocks it down with a merge conflict again :smile:

**Pull request merged**
