### PR TITLE
bootstrap.py: Don't reject vendoring when using CARGO_HOME.

### PR DESCRIPTION
**Pull request by mikebenfield**

### CODE REVIEW

**Comment by mikebenfield** [comment]
I don't know if this is the correct thing to do, but I do know the vendoring/config setup I had that used to work was broken at some point in the recent past and this fixes it.

**Comment by jyn514** [comment]
We don't support any use of .cargo/config other than one that bootstrap generates in the `rust-src` component. I'm a little reluctant to accept this change, since I don't want to set a precedent of fixing things for .cargo.

**Comment by jyn514** [comment]
> I do know the vendoring/config setup I had that used to work was broken at some point in the recent past and this fixes it.

Do you know when it broke? Can you bisect, maybe?

**Comment by mikebenfield** [comment]
Although I still think there's something not quite right going on here, I no longer am working on the configuration with the problem, so I'm closing.

**Pull request closed without merging**
