### PR TITLE
Make MIR pass name a compile-time constant.

### PR DESCRIPTION
**Pull request by cjgillot**
Post-processing a compile-time string at runtime is a bit silly. This PR makes CTFE do it all.

### CODE REVIEW

**Comment by cjgillot** [comment]
r? compiler

**Comment by Nilstrieb** [comment]
Given that this is perf neutral, I don't think it makes sense to merge, as the runtime code is a lot nicer.

**Comment by cjgillot** [comment]
I agree the code is much uglier than the runtime implementation. I'd be glad to use the exact same code, but I had to wrestle the compiler into accepting this mess. 

Perf-wise, the improvement is tiny (<1%) but measurable. See the unfiltered results.

**Pull request merged**
