### PR TITLE
move enzyme flags from general cargo to rustc-specific cargo

### LINKED ISSUE #130637: tool builds with Enzyme/autodiff fails
A while ago we merged the first backend pr to enable automatic differentiation in Rust: https://github.com/rust-lang/rust/pull/129176.
This was good enough to add and enable the `enzyme` config in `config.toml` and run `x.py build --stage 1`.
We would now like to improve the integration to also successfully run `x.py dist --stage 1` (to use Rust in our autodiff compiler explorer).
@jedbrown and I looked into it for a while and while it seems like a simple linker issue, we didn't fully understood where it comes from and what's the best way to fix it. This commit has a few more changes (not yet upstreamed) that might help for understanding how enzyme is used https://github.com/rust-lang/rust/compare/master...EnzymeAD:rust:master. We also have documentation here: https://enzyme.mit.edu/index.fcgi/rust/

Back to the issue. We first build Enzyme (a git submodule) and then try to link it. To copy Jed's observations:
The code to add `-lEnzyme-19` is in `src/bootstrap/src/core/builder.rs` inside fn cargo.

```
if self.config.llvm_enzyme {
    rustflags.arg("-l");
    rustflags.arg("Enzyme-19");
}
```

Note that linking works correctly when building normal crates. Also, I find it odd that this one line of code yields so many repeat arguments (as in, `"-Wl,-Bdynamic" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lEnzyme-19" "-lgcc_s").`

Is there a better way to link Enzyme?
Should we prefer to elide Enzyme linking when it isn't needed or be more explicit with paths so it is always found?
A potentially related linking error only happens under MacOS: https://github.com/EnzymeAD/rust/issues/175

Related Zulip issue: https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Fixing.20x.2Epy.20dist.20linking.20issue

Tracking:

- https://github.com/rust-lang/rust/issues/124509

### PR DESCRIPTION
**Pull request by onur-ozkan**
Resolves #130637.

Tracking:

- https://github.com/rust-lang/rust/issues/124509

### CODE REVIEW

**Comment by ZuseZ4** [comment]
I can confirm that cherry-picking this pr (and a minor fix due to being 2 weeks behind) worked for the full rustc-ad fork, I could run all of our (not yet upstreamed) tests: https://github.com/rust-lang/rust/pull/130648/files

**Comment by ZuseZ4** [comment]
We don't (currently) build Enzyme/autodiff by default, so I think this could just be rollup=allways

**Comment by onur-ozkan** [comment]
> We don't (currently) build Enzyme/autodiff by default, so I think this could just be rollup=allways, since it won't affect the CI builds.

We usually rollup PRs unless they are explicitly tagged with rollup=never/iffy.

**Comment by ZuseZ4** [comment]
@onur-ozkan this was a good improvement, but I think it still needs to become a bit more precise, see e.g. the cranelift build failure: https://github.com/rust-lang-ci/rust/actions/runs/14826601681/job/41620576833

What would be the best way to solve this? Is cranelift trying to bootstrap itself here without LLVM and hence Enzyme? At least it looks suspicious that exactly the one project not needing llvm fails. At least locally I have Enzyme in a few locations, so generally it shouldn't be too hard to specify a suitable link even in /rustlib, where cranelift mostly seems to live. The strange thing is that I can't find a code path in the source code which would end with us adding `-lEnzyme-20`, without also adding the corresponding `-L` flag.
```
./stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libEnzyme-20.so
./stage1/lib/libEnzyme-20.so
./stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libEnzyme-20.so
./enzyme/lib/libEnzyme-20.so
./enzyme/build/Enzyme/libEnzyme-20.so
```

**Pull request merged**
