### PR TITLE
Use ManuallyDrop instead of Option in BinaryHeap Hole implementation

### PR DESCRIPTION
**Pull request by nikic**
The Option is always Some until drop, where it becomes None. Make this more explicit and avoid unwraps by using ManuallyDrop.

This change should be performance-neutral as LLVM already optimizes the unwraps away in the inlined code. However I've seen this pattern copied from here to other crates where it is not optimized away, so I think it would be good to change it.

### CODE REVIEW

**Comment by Gankro** [comment]
@bors-servo r+

let's find out if i have perms still

**Comment by nikic** [comment]
Looks like the build failed due to some kind of infrastructure issue?

**Comment by kennytm** [comment]
@bors retry

Failed to deploy.

**Pull request merged**
