### PR TITLE
Report unsafe for overriding link sections

### PR DESCRIPTION
**Pull request by ghost**
I'm not too sure about the lint wording here, but I couldn't think of anything better.

### CODE REVIEW

**Comment by 5225225** [comment]
This presumably will require a crater run to see how many things this breaks. I'd be surprised if there were that many crates that both forbid unsafe_code explicitly *and* set a link_section.

**Comment by davidtwco** [comment]
A check-only crater run is sufficient for this, right?

**Comment by 5225225** [comment]
Yep, just running `cargo check` causes compilation to fail if this lint is triggered.

**Comment by davidtwco** [comment]
@craterbot check

**Comment by davidtwco** [comment]
@craterbot check

**Review by davidtwco — APPROVED** [review]

**Comment by therealprof** [comment]
Overriding the link section is very typical for embedded code (which I can't imagine being part of the crate run). Not sure how common it is to forbid unsafe code though...

**Comment by Lokathor** [comment]
@therealprof I've got embedded code which overrides the link section on things and which is in public repos (so i assume crater sees it and builds it). I'm definitely not the only one.

**Comment by therealprof** [comment]
> @therealprof I've got embedded code which overrides the link section on things and which is in public repos (so i assume crater sees it and builds it). I'm definitely not the only one.

I thought crater would only pick up crates which can be built natively and tested on the builders...

**Comment by Lokathor** [comment]
In my case (GBA) a `cargo check` will work with just Nightly and build-std and no special non-rust tools. And if I were using a newer target even a full build will would work (GBA is too old to work with llvm's default linker).

I don't really know how crater works, but I hope it's able to try a cargo check on its own.

**Pull request merged**
