### PR TITLE
[Clippy] Swap `map_entry` to use diagnostic items instead of paths

### PR DESCRIPTION
**Pull request by GnomedDev**
Part of https://github.com/rust-lang/rust-clippy/issues/5393, just a chore.

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me when 🍏

**Comment by workingjubilee** [comment]
homu thinks this can be rolled up. homu is wrong.
@bors r-

**Comment by GnomedDev** [comment]
Merging this into a larger PR to avoid merge conflicts.

**Pull request closed without merging**
