### PR TITLE
Move with_globals setup from run_compiler to run

### PR DESCRIPTION
**Pull request by Zoxc**
An alternative to https://github.com/rust-lang/rust/pull/53526

Note this breaks some miri stuff and clippy since they call `run_compiler` directly, and they now need to also call `with_globals ` cc @rust-lang/dev-tools 

r? @oli-obk

### CODE REVIEW

**Comment by alexreg** [comment]
Does this solve all the issues in https://github.com/rust-lang/rust/issues/53420?

**Comment by nrc** [comment]
This will break RLS and Rustfmt too, I think.

**Comment by earthengine** [comment]
Although this passes the tests, but I am afraid that if the `monitor` itself captured an error and need to emit,   we would still have the same problem. This is the consideration I put the `with_globals` outside the `monitor` call.

**Comment by oli-obk** [comment]
does the monitor ever need to emit diagnostics?

**Comment by Zoxc** [comment]
The monitor does emit diagnostics, but it only uses dummy spans, which does not seem to access libsyntax globals. I've tested that the ICE printing still works locally.

**Comment by Zoxc** [comment]
@nrc [RLS uses `run`](https://github.com/rust-lang-nursery/rls/blob/9e4d8d520390c6aeebc33260026c6ae2946c67ac/src/build/rustc.rs#L93), so it doesn't need any changes. `rustfmt` doesn't seems to use the compiler at all, just `libsyntax`, so no changes should be needed.

**Comment by alexreg** [comment]
@Zoxc Didn't the patch I sent to you work? And avoid breaking other things?

**Comment by oli-obk** [comment]
I updated clippy. It should work with this PRs changes now. Can you update the clippy submodule to the current master? Then this PR doesn't break clippy at all

**Comment by alexreg** [comment]
@oli-obk Good stuff. How are you getting on with the underlying MIR issue?

**Comment by alexreg** [comment]
Looks like CI is failing because of the submodule update? Or is it just transient?

**Comment by oli-obk** [comment]
@bors r+

@earthengine If we ever want to stabilize this API we'd need to do so many other changes, this seems like the least of the worries I have with that.

We could rather check if we can merge `run` and `run_compiler` by looking at all use cases.

**Pull request merged**
