### PR TITLE
[beta-1.80] Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
1 commits in 34a6a87d8a2330d8c9d578f927489689328a652d..37629051518c3df9ac2c1744589362a02ecafa99
2024-06-04 15:31:01 +0000 to 2024-07-16 01:31:28 +0000
- [beta-1.80.0] chore: downgrade to jobserver@0.1.28 (rust-lang/cargo#14255)

try-job: dist-riscv64-linux

### CODE REVIEW

**Comment by weihanglo** [comment]
This should be done before beta cutoff.

@bors r+ rollup=never p=1

**Comment by weihanglo** [comment]
Doesn't look relevant.

@bors retry

**Comment by weihanglo** [comment]
Let's try again and see if it was just bad luck.

@bors try

**Comment by weihanglo** [comment]
Hmm… didn't really try RISCV. Maybe because there were some homu-ignore lines. Try again

@bors try

**Comment by ehuss** [comment]
@weihanglo `bors try` only ever does dist-x86_64-linux.

If you want to try a different target, the easiest thing to do is to edit [`jobs.yml`](https://github.com/rust-lang/rust/blob/HEAD/src/ci/github-actions/jobs.yml) and copy the job from the `auto` section into the `pr` section, and just push (don't bother with "try", that's only needed if you want to download the artifacts).

There are some docs for that at https://rustc-dev-guide.rust-lang.org/tests/ci.html#modifying-ci-jobs.

**Comment by weihanglo** [comment]
@ehuss 

`try-job:` in PR doesn't work? I read [rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/tests/ci.html?highlight=try-job#try-builds) and <https://github.com/rust-lang/rust/pull/127805>, and thought that would work without modifying YAML.

**Comment by ehuss** [comment]
Oh! Sorry, I didn't see that. You are right, that should work.

**Comment by weihanglo** [comment]
@nikic and @cuviper would you mind helping review whether the cherry-pick is correct? Thank you!

**Comment by nikic** [comment]
Looks good to me.

**Comment by weihanglo** [comment]
Nice. Thank you!

Going to merge this before beta cutoff.

@bors r+ rollup=never p=1

**Pull request merged**
