### PR TITLE
Turn `TrapUnreachable` off by default

### PR DESCRIPTION
**Pull request by jonas-schievink**
Now that https://github.com/rust-lang/rust/issues/28728 is fixed, there's no longer a risk of programs executing past the end of a function, so we don't have to put a trap instruction there anymore.

This should ever so slightly shrink the average Rust program.

(the second commit is a drive-by-fix that reverts an incorrect part of https://github.com/rust-lang/rust/commit/62e7331bd2bd592e30acf63467f140084684bc8f, which made the `alloc-optimisation.rs` test fail with my system's LLVM)

### CODE REVIEW

**Comment by nikic** [comment]
FWIW upstream is considering turning on TrapUnreachable or some variant thereof on by default, to at least prevent zero-size functions.

I think a more conservative step we can take is to enable the NoTrapAfterNoreturn option, which probably is the form in which the vast majority of unreachable appears in rust code (basically after every panic), and also the one where it has little practical benefit.

**Comment by oli-obk** [comment]
I don't know enough about the effects of this to review this properly.

r? @nikic

**Comment by JohnCSimon** [comment]
Ping from triage: 
@jonas-schievink  Can you please post the status of this PR?

**Pull request closed without merging**
