### PR TITLE
Revert #50105 until regression is fixed

### PR DESCRIPTION
**Pull request by alexcrichton**
Discovered at https://github.com/rust-lang/rust/pull/50105#issuecomment-388630750 it looks like this caused a regression with i686 musl, so let's revert in the meantime while a fix is worked out

### CODE REVIEW

**Comment by mixi** [comment]
Fair enough. It should be enough to just revert 6d9154a830dd9773fe8a4e34e1fc3dfb1ca6f935, though (and hopefully leave the fix for my original problem in).

The problem seems to be caused by the compiler searching in different directories for system libraries and start files (as with -m32 different start files are supposed to be linked in - and are somewhere to be found on the system, or else building for i686-glibc wouldn't work - but the library search path apparently only contains the start file directory for the x86_64 crt{begin,end}.o files).

**Comment by alexcrichton** [comment]
@mixi FWIW I don't think this is searching the wrong directories but it can also come up when the files are just missing I believe?

**Comment by mixi** [comment]
@alexcrichton Of course. I guessed they aren't missing because I assumed (without any reason to - i686-gnu isn't part of the tests) linking for i686-gnu worked on the same system. (Note for future reference: on Ubuntu 14.01, which travis may or may not use, the files are supposed to be in the package `lib32gcc-4.8-dev`)

**Pull request merged**
