### PR TITLE
[WIP] polonius: adapt to the new fact format

### PR DESCRIPTION
**Pull request by amandasystems**
Hopefully the final phase of the ordeal now known as The Great Renaming, in which the Polonius working group renames virtually all of their input facts.

This also extends fact generation to support full initialisation tracking and move analysis in Polonius.

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors delegate=albins 

r=me but travis is unhappy. @albins, I've delegated bors to you, so if you are able to [fix these errors](https://github.com/rust-lang/rust/pull/68993#issuecomment-583845954) you should be able to tell bors `r+` yourself!

**Comment by albins** [comment]
@nikomatsakis Thanks! It needs a new Polonius release (the PR I’m working on).

**Comment by albins** [comment]
Blocked waiting on https://github.com/rust-lang/polonius/pull/135

**Comment by lqd** [comment]
rust-lang/polonius#135 is now merged, and `polonius-engine` version `0.12.0` has been [published](https://crates.io/crates/polonius-engine/0.12.0)

**Comment by lqd** [comment]
Since Albin won't be able to do it for a while, I've rebased and finalized this PR in #69482, so I'll close this one.

**Pull request closed without merging**
