### PR TITLE
Export public scalar statics in wasm

### LINKED ISSUE #67453: Static variables are not exported in wasm
Repro https://github.com/EmbarkStudios/missing-symbols `rustc 1.40.0 (73528e339 2019-12-16)
`
```rust
// lib.rs
#[no_mangle]
#[used]
pub static FOO: u64 = 4242;
```
`cargo build --release --target wasm32-unknown-unknown`, the resulting wasm file doesn't have the symbol `FOO`.

```
(module
  (table (;0;) 1 1 funcref)
  (memory (;0;) 16)
  (global (;0;) (mut i32) (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048576))
  (global (;2;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "__data_end" (global 1))
  (export "__heap_base" (global 2)))
```
But if we compile with `-C link-dead-code`, the symbol is correctly exported in the wasm file.

`RUSTFLAGS="-C link-dead-code" cargo build --release --target wasm32-unknown-unknown`

```
(module
  (table (;0;) 1 1 funcref)
  (memory (;0;) 17)
  (global (;0;) (mut i32) (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048584))
  (global (;2;) i32 (i32.const 1048584))
  (global (;3;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "__data_end" (global 1))
  (export "__heap_base" (global 2))
  (export "FOO" (global 3))
  (data (;0;) (i32.const 1048576) "\92\10\00\00\00\00\00\00"))
```

Expected behavior: Public static variables should get exported by default.

We believe this is a regression from 1.39.0.

```
rustup override set 1.39.0
cargo build --release --target wasm32-unknown-unknown
```

Does correctly export static variables.

### PR DESCRIPTION
**Pull request by MaikKlein**
Fixes #67453 

I am not sure which export level statics should get when exporting them in wasm. This small change fixes the issue that I had, but this might not be the correct way to implement this.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think that the case for wasm can be removed entirely here since I believe the exported value is always the address of the variable in memory

**Comment by alexcrichton** [comment]
I think that this is probably ok to land, but can you add some wasm-specific tests (probably around `src/test/run-make`, copying existing ones), which assert that statics work as expected?

**Comment by MaikKlein** [comment]
Added a very basic test to `wasm-export-all-symbols`, instead of creating a new one.

**Comment by alexcrichton** [comment]
@bors: r+

Nice!

**Pull request merged**
