### PR TITLE
add const generics test

### PR DESCRIPTION
**Pull request by lcnr**
cc https://github.com/rust-lang/rust/pull/89829#issuecomment-948921310

r? rust-lang/project-const-generics

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me unless you actually want a const-generics group review (test seems OK to me but I'm not an expert)

**Comment by matthiaskrgr** [comment]
looks like this failed in a rollup.?
https://github.com/rust-lang/rust/pull/90710#issuecomment-963597552
might also be that some of the other PRs changes this prs output.
@bors r-
feel free to re-r+ if I'm wrong :sweat_smile:

**Comment by lcnr** [comment]
@bors r=Mark-Simulacrum rollup

it seems like the output didn't change on master :thinking:

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/91013#issuecomment-972992751
@bors r-

You should bless tests with `compare-mode=nll`.

**Comment by lcnr** [comment]
aaah, completely missed that :( thanks

@bors r=Mark-Simulacrum rollup

**Pull request merged**
