### PR TITLE
[WIP]  rustc_typeck: ensure type alias bounds are implied by the type being well-formed.

### LINKED ISSUE #21903: Trait bounds are not yet enforced in type definitions
Opening an issue since I could not find any information on when/if this will be enforced. Would be really useful for some generalizing I am trying for parser-combinators which I can't do currently without complicating the API.

Specifically I'd like to use a trait bound in a type definition to access an associated type to avoid passing it seperately but due to this issue I simply get a compiler error.

Simplified code which exhibits the error:
```rust
trait Stream {
    type Item;
}

trait Parser {
    type Input: Stream;
}

fn test<T>(u: T) -> T
    where T: Parser {
    panic!()
}

type Res<I: Stream> = (I, <I as Stream>::Item);

impl <'a> Stream for &'a str { type Item = char; }
impl <I> Parser for fn (I) -> Res<I> where I: Stream { type Input = I; }

//Works
//fn f(_: &str) -> (&str, char) {

//Errors
fn f(_: &str) -> Res<&str> {
    panic!()
}

fn main() {
    let _ = test(f as fn (_) -> _);
}

```

### PR DESCRIPTION
**Pull request by eddyb**
**NOTE**: this is mainly for crater, we'll only emit hard errors on Rust 2018.
This is the second half to a plan outlined in comment on #49441 (see #54033 for the first half).

Fixes #21903 (by disallowing currently unenforceable bounds instead of enforcing them).

This PR includes two hacks: first to not check (usually implied) `T: Sized` bounds, as they're a common source of breakage and would probably be too annoying in practice, and a second to remove some overlap with #54033, so adding missing bounds is *not* required to test this PR.
A decision should be made about the former hack, while the latter is only a temporary convenience.

r? @nikomatsakis

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
You should be able to start the crater run yourself via the bot, see directions here: https://github.com/rust-lang-nursery/crater/blob/master/docs/bot-usage.md

**Comment by Mark-Simulacrum** [comment]
@craterbot run p=1 start=master#f50b7758f4dc85dc1c5e38258adaa94213ac6ed1 end=try#3a2610c2a16575649896925631bf8cec4f4b1961 cap-lints=warn mode=check-only

**Comment by eddyb** [comment]
Most of the failures come from diesel, and are probably caused by the fact that this is only one half of the check. There are a few legitimate one. Overall, this seems like not a dent in the ecosystem.

**Comment by RalfJung** [comment]
About that `Sized` hack, can we make it so that `type Foo<T: Sized> = Box<T>` causes an error? I.e., just *implicit* `Sized` is ignored?

**Comment by eddyb** [comment]
@RalfJung I don't want to keep the `Sized` hack in, I'd rather have an automatically applicable suggestion to add `?Sized` - see also https://github.com/rust-lang/rust/issues/49441#issuecomment-421136550.

**Comment by eddyb** [comment]
(you can see above I opened 4 PRs - I want to reuse the `type_alias_bounds` lint name)

**Comment by TimNN** [comment]
Ping from triage! IIUC, this is waiting on some other PRs to be submitted, so I'm marking this as blocked.

**Comment by nikomatsakis** [comment]
I'm going to close this PR for now. I do plan to start opening some PRs and issuing warnings, per the plan discussed in https://github.com/rust-lang/rust/issues/55222

**Pull request closed without merging**
