### PR TITLE
[DO NOT MERGE] make before_exec an unsafe fn

### PR DESCRIPTION
**Pull request by RalfJung**
This is an experiment for https://github.com/rust-lang/rust/issues/39575.

### CODE REVIEW

**Comment by RalfJung** [comment]
@rust-lang/infra could we get a check-only crater run?

**Comment by pietroalbini** [comment]
102 regressions, including Cargo (and thus a ton of Cargo plugins).

**Comment by pietroalbini** [comment]
Ran [crater-tree](https://github.com/pietroalbini/crater-tree) on the results. As usual, the graph is far from perfect and it misses some things, but it can be useful anyway.

<details><summary>Results</summary>

```
cargo-disassemble
cargo-geiger
cargo-debstatus
cargo-tally
cargo-scriptify
mdbook-epub
stund
lateral
cargo-tree
cargo
| cargo-apk
| cargo-faircode
| cargo-bom
| cargo-sphinx
| cargo-outdated
| cargo-ebuild
| cargo-dinghy
| dinghy-lib
| cargo-clone
| cargo-authors
| dinghy
| cuo
| cargo-bitbake
| cargo-vendor
| cargo-travis
| cargo-raze
| cargo-pack
| | cargo-pack-docker
| oysterpack_built
| | oysterpack
| | oysterpack_log
| nannou-new
riffol
cargo-watch
watchexec
exclave
varlink-cli
sccache
rtq
initrs
tracetree
sinit
jobserver
tokio-pty-process
axon
cntr
process_viewer
tmux-hints
rtss
varlink_stdinterfaces
varlink
commandspec
tty
eloggr
runny
spawn-ptrace
pseudoterm
```

</details>

**Comment by kennytm** [comment]
The [cargo failure](https://crater-reports.s3.amazonaws.com/pr-56129/try%23aaadaed28c4f579449b007d5228f7e512be9af5f/reg/cargo-0.31.0/log.txt) was caused by jobserver, which the tree above doesn't show 🤔 

<details>

```
Nov 23 04:18:59.734 INFO [stderr] error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
Nov 23 04:18:59.734 INFO [stderr]    --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/jobserver-0.1.11/src/lib.rs:566:13
Nov 23 04:18:59.734 INFO [stderr]     |
Nov 23 04:18:59.734 INFO [stderr] 566 | /             cmd.before_exec(move || {
Nov 23 04:18:59.734 INFO [stderr] 567 | |                 set_cloexec(read, false)?;
Nov 23 04:18:59.734 INFO [stderr] 568 | |                 set_cloexec(write, false)?;
Nov 23 04:18:59.734 INFO [stderr] 569 | |                 Ok(())
Nov 23 04:18:59.734 INFO [stderr] 570 | |             });
Nov 23 04:18:59.734 INFO [stderr]     | |______________^ call to unsafe function
Nov 23 04:18:59.734 INFO [stderr]     |
Nov 23 04:18:59.734 INFO [stderr]     = note: consult the function's documentation for information on how to avoid undefined behavior
```

</details>

**Comment by pietroalbini** [comment]
Ok, did a simpler grep, and there are 32 crates actually failing (without counting dependencies):

<details><summary>List</summary>

```
axon
bind_spawn
cntr
commandspec
containers
fisher
initrs
jobserver
kickoff
lateral
mathsbot
minit
playlist_mgr
process_viewer
pseudoterm
ps-util
pty
repo-manager
riffol
rtq
rtss
runny
rush
sinit
spawn-ptrace
symare
tmux-hints
tokio-pty-process
tty
tydra
varlink
watchexec
```

</details>

**Pull request closed without merging**
