### PR TITLE
Convert UNIX `std::fs::remove_dir_all()` from recursive to looping

### PR DESCRIPTION
**Pull request by hkratz**
`std::fs::remove_dir_all()` is recursive and can run out of stack space for deep directory hierarchies. This uses @cuviper's looped implementation with an on-heap stack to avoid running out of stack space before running out of file descriptors. As a drive-by fix it reduces the Macos x86-64 special case code.

For easier review the Macos x86-64 commits are broken up in two. One removes the Macos x86-64 special case completely, the second adds more fine-grained special-case handling back.

Further work to make `remove_dir_all()` use only a fixed number of open file descriptors is planned, see #93160.

### CODE REVIEW

**Comment by cuviper** [comment]
+1 for consolidating macos -- always nice to see a net reduction in code!

**Comment by hkratz** [comment]
Needs to be rebased once #94446 is merged.

@rustbot author

**Comment by JohnCSimon** [comment]
@hkratz 
> Needs to be rebased once #94446 is merged.

Triage:  Looks like this is unblocked - can you post your status on this PR?

**Comment by hkratz** [comment]
Closed in favor of #95925.

**Pull request closed without merging**
