### PR TITLE
Remove in-tree regex/base64 support

### PR DESCRIPTION
**Pull request by alexcrichton**
The base64 support can be trivially removed (there are no in-tree users) and the regex support is a whopping 4k lines of code to maintain for a few non-critical uses in-tree. This commit migrates all current users in-tree away from regexes to custom matching code.

The most critical application affected by this migration is that the testing framework no longer considers filter arguments as regexes, but rather just a substring matching. It is expected that more featureful testing frameworks can evolve outside of the in-tree libtest version over time which can properly depend on libregex from crates.io.

[breaking-change]

### CODE REVIEW

**Comment by pczarn** [comment]
`src/grammar/verify.rs` remains to be migrated.

**Comment by steveklabnik** [comment]
Most of `src/grammar` is just vestigial.

**Comment by alexcrichton** [comment]
Ack I knew I forgot something! Thanks @pczarn for pointing that out, I've ported it over now.

**Comment by frewsxcv** [comment]
Needs a rebase

**Pull request merged**
