### PR TITLE
Implement `core::ptr::Unique` on top of `NonNull`

### PR DESCRIPTION
**Pull request by eduardosm**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/96010)*

Removes the use `rustc_layout_scalar_valid_range_start` and some `unsafe` blocks.

### CODE REVIEW

**Comment by eduardosm** [comment]
I wonder what is going on with failing tests
```
---- [ui] src/test/ui/box/issue-95036.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 101
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/box/issue-95036.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/box/issue-95036" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-O" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/box/issue-95036/auxiliary"
stdout: none
--- stderr -------------------------------
error: internal compiler error: /checkout/compiler/rustc_codegen_ssa/src/mir/operand.rs:125:32: deref of non-pointer OperandRef(Immediate((i8*:  %23 = load i8*, i8** %22, align 8, !nonnull !3, !noundef !3)) @ TyAndLayout { ty: std::ptr::NonNull<std::mem::MaybeUninit<[u8; 1]>>, layout: Layout { fields: Arbitrary { offsets: [Size { raw: 0 }], memory_index: [0] }, variants: Single { index: 0 }, abi: Scalar(Initialized { value: Pointer, valid_range: 1..=18446744073709551615 }), largest_niche: Some(Niche { offset: Size { raw: 0 }, value: Pointer, valid_range: 1..=18446744073709551615 }), align: AbiAndPrefAlign { abi: Align { pow2: 3 }, pref: Align { pow2: 3 } }, size: Size { raw: 8 } } })

thread 'rustc' panicked at 'Box<dyn Any>', /checkout/compiler/rustc_errors/src/lib.rs:1349:9
stack backtrace:
   0:     0x7f63758681bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd8aca151e67c8931
   1:     0x7f63758cc318 - core::fmt::write::hda5d9e6a9927afdc
   2:     0x7f6375858501 - std::io::Write::write_fmt::h6e9facd7b3f1e45b
   3:     0x7f637586b1de - std::panicking::default_hook::{{closure}}::h6f10d36904bdbc6e
   4:     0x7f637586ae14 - std::panicking::default_hook::hede5b607fbf63d68
   5:     0x7f63763b7d41 - rustc_driver[ca2c46528bdd3c4e]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7f637586ba3e - std::panicking::rust_panic_with_hook::h5e10068a4c2eb4c4
   7:     0x7f6378cd16e3 - std[fe45e4324dca75f5]::panicking::begin_panic::<rustc_errors[2766f829769489bc]::ExplicitBug>::{closure#0}
   8:     0x7f6378cd12a6 - std[fe45e4324dca75f5]::sys_common::backtrace::__rust_end_short_backtrace::<std[fe45e4324dca75f5]::panicking::begin_panic<rustc_errors[2766f829769489bc]::ExplicitBug>::{closure#0}, !>
   9:     0x7f63762d8eaf - std[fe45e4324dca75f5]::panicking::begin_panic::<rustc_errors[2766f829769489bc]::ExplicitBug>
  10:     0x7f6378aca546 - std[fe45e4324dca75f5]::panic::panic_any::<rustc_errors[2766f829769489bc]::ExplicitBug>
  11:     0x7f6378abd196 - <rustc_errors[2766f829769489bc]::HandlerInner>::bug::<&alloc[978f5700631692ba]::string::String>
  12:     0x7f6378abce50 - <rustc_errors[2766f829769489bc]::Handler>::bug::<&alloc[978f5700631692ba]::string::String>
  13:     0x7f6378ccbed5 - rustc_middle[8d48c6df689d05d1]::util::bug::opt_span_bug_fmt::<rustc_span[5a3e90cbbc7c42a5]::span_encoding::Span>::{closure#0}
  14:     0x7f6378cc8edb - rustc_middle[8d48c6df689d05d1]::ty::context::tls::with_opt::<rustc_middle[8d48c6df689d05d1]::util::bug::opt_span_bug_fmt<rustc_span[5a3e90cbbc7c42a5]::span_encoding::Span>::{closure#0}, ()>::{closure#0}
  15:     0x7f6378cc8e8c - rustc_middle[8d48c6df689d05d1]::ty::context::tls::with_opt::<rustc_middle[8d48c6df689d05d1]::util::bug::opt_span_bug_fmt<rustc_span[5a3e90cbbc7c42a5]::span_encoding::Span>::{closure#0}, ()>
  16:     0x7f6378ccbe19 - rustc_middle[8d48c6df689d05d1]::util::bug::opt_span_bug_fmt::<rustc_span[5a3e90cbbc7c42a5]::span_encoding::Span>
  17:     0x7f63762df91e - rustc_middle[8d48c6df689d05d1]::util::bug::bug_fmt
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
  18:     0x7f63765659f8 - <rustc_codegen_ssa[f10137ac22e0f29f]::mir::operand::OperandRef<&rustc_codegen_llvm[87c8104e5bc925bf]::llvm_::ffi::Value>>::deref::<rustc_codegen_llvm[87c8104e5bc925bf]::context::CodegenCx>::{closure#0}
  19:     0x7f6376560bc6 - <rustc_codegen_ssa[f10137ac22e0f29f]::mir::operand::OperandRef<&rustc_codegen_llvm[87c8104e5bc925bf]::llvm_::ffi::Value>>::deref::<rustc_codegen_llvm[87c8104e5bc925bf]::context::CodegenCx>
  20:     0x7f63766d57ed - <rustc_codegen_ssa[f10137ac22e0f29f]::mir::FunctionCx<rustc_codegen_llvm[87c8104e5bc925bf]::builder::Builder>>::codegen_place
  21:     0x7f63766c8648 - <rustc_codegen_ssa[f10137ac22e0f29f]::mir::FunctionCx<rustc_codegen_llvm[87c8104e5bc925bf]::builder::Builder>>::codegen_rvalue_operand
  22:     0x7f63766d0ff7 - <rustc_codegen_ssa[f10137ac22e0f29f]::mir::FunctionCx<rustc_codegen_llvm[87c8104e5bc925bf]::builder::Builder>>::codegen_block
  23:     0x7f63766c4426 - rustc_codegen_ssa[f10137ac22e0f29f]::mir::codegen_mir::<rustc_codegen_llvm[87c8104e5bc925bf]::builder::Builder>
  24:     0x7f63765453b6 - rustc_codegen_ssa[f10137ac22e0f29f]::base::codegen_instance::<rustc_codegen_llvm[87c8104e5bc925bf]::builder::Builder>
  25:     0x7f637669dff7 - <rustc_middle[8d48c6df689d05d1]::mir::mono::MonoItem as rustc_codegen_ssa[f10137ac22e0f29f]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[87c8104e5bc925bf]::builder::Builder>
  26:     0x7f63765ef6c4 - rustc_codegen_llvm[87c8104e5bc925bf]::base::compile_codegen_unit::module_codegen
  27:     0x7f63765ed977 - rustc_codegen_llvm[87c8104e5bc925bf]::base::compile_codegen_unit
  28:     0x7f6376543dcb - rustc_codegen_ssa[f10137ac22e0f29f]::base::codegen_crate::<rustc_codegen_llvm[87c8104e5bc925bf]::LlvmCodegenBackend>
  29:     0x7f637662a599 - <rustc_codegen_llvm[87c8104e5bc925bf]::LlvmCodegenBackend as rustc_codegen_ssa[f10137ac22e0f29f]::traits::backend::CodegenBackend>::codegen_crate
  30:     0x7f63764b1901 - <rustc_session[f527fa7acd786cb5]::session::Session>::time::<alloc[978f5700631692ba]::boxed::Box<dyn core[9d0d73d25bc79eb6]::any::Any>, rustc_interface[6039aff59812a2a9]::passes::start_codegen::{closure#0}>
  31:     0x7f63764ae352 - <rustc_interface[6039aff59812a2a9]::queries::Queries>::ongoing_codegen
  32:     0x7f6376341a35 - <rustc_interface[6039aff59812a2a9]::interface::Compiler>::enter::<rustc_driver[ca2c46528bdd3c4e]::run_compiler::{closure#1}::{closure#2}, core[9d0d73d25bc79eb6]::result::Result<core[9d0d73d25bc79eb6]::option::Option<rustc_interface[6039aff59812a2a9]::queries::Linker>, rustc_errors[2766f829769489bc]::ErrorGuaranteed>>
  33:     0x7f63763a4d3b - rustc_span[5a3e90cbbc7c42a5]::with_source_map::<core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>, rustc_interface[6039aff59812a2a9]::interface::create_compiler_and_run<core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>, rustc_driver[ca2c46528bdd3c4e]::run_compiler::{closure#1}>::{closure#1}>
  34:     0x7f6376342c32 - <scoped_tls[f83357d34eb529bc]::ScopedKey<rustc_span[5a3e90cbbc7c42a5]::SessionGlobals>>::set::<rustc_interface[6039aff59812a2a9]::interface::run_compiler<core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>, rustc_driver[ca2c46528bdd3c4e]::run_compiler::{closure#1}>::{closure#0}, core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>>
  35:     0x7f63763a21d9 - std[fe45e4324dca75f5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6039aff59812a2a9]::util::run_in_thread_pool_with_globals<rustc_interface[6039aff59812a2a9]::interface::run_compiler<core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>, rustc_driver[ca2c46528bdd3c4e]::run_compiler::{closure#1}>::{closure#0}, core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>>::{closure#0}, core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>>
  36:     0x7f637635c271 - std[fe45e4324dca75f5]::panicking::try::<core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>, core[9d0d73d25bc79eb6]::panic::unwind_safe::AssertUnwindSafe<<std[fe45e4324dca75f5]::thread::Builder>::spawn_unchecked_<rustc_interface[6039aff59812a2a9]::util::run_in_thread_pool_with_globals<rustc_interface[6039aff59812a2a9]::interface::run_compiler<core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>, rustc_driver[ca2c46528bdd3c4e]::run_compiler::{closure#1}>::{closure#0}, core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>>::{closure#0}, core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
  37:     0x7f637639d1d2 - <<std[fe45e4324dca75f5]::thread::Builder>::spawn_unchecked_<rustc_interface[6039aff59812a2a9]::util::run_in_thread_pool_with_globals<rustc_interface[6039aff59812a2a9]::interface::run_compiler<core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>, rustc_driver[ca2c46528bdd3c4e]::run_compiler::{closure#1}>::{closure#0}, core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>>::{closure#0}, core[9d0d73d25bc79eb6]::result::Result<(), rustc_errors[2766f829769489bc]::ErrorGuaranteed>>::{closure#1} as core[9d0d73d25bc79eb6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f63758767f3 - std::sys::unix::thread::Thread::new::thread_start::h42e16de5fda4c2d6
  39:     0x7f636fdc9609 - start_thread
  40:     0x7f63756dc163 - clone
  41:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (a81536072 2022-04-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -C codegen-units=1 -Z ui-testing -Z deduplicate-diagnostics=no -C prefer-dynamic -C rpath -C debuginfo=0

query stack during panic:
end of query stack
error: aborting due to previous error
------------------------------------------
```

**Comment by tmiasko** [comment]
You probably need to change the code generation by adding one additional `extract_field` / `project_field` when dereferencing a box (those correspond to the first field `Box`, the first field of `Unique`, and now in addition to that the first field of `NonNull`):

https://github.com/rust-lang/rust/blob/f38c5c8e5d76ea9a87fece143425ef7c703c706a/compiler/rustc_codegen_ssa/src/mir/place.rs#L450-L454

https://github.com/rust-lang/rust/blob/f38c5c8e5d76ea9a87fece143425ef7c703c706a/compiler/rustc_codegen_ssa/src/mir/place.rs#L465-L469

**Comment by eduardosm** [comment]
> You probably need to change the code generation by adding one additional `extract_field` / `project_field` when dereferencing a box (those correspond to the first field `Box`, the first field of `Unique`, and now in addition to that the first field of `NonNull`):

Thanks for the tip

**Comment by eduardosm** [comment]
It looks like it breaks printing some collections in gdb

**Comment by thomcc** [comment]
Hmm, yeah, never really did understand what the deal with Unique was, so I'm gonna to punt this to someone else. Naïvely, it looks fine.

r? rust-lang/libs

**Comment by tmiasko** [comment]
FYI: @antoyo, @bjorn3 this pull request modifies Box, in case `mini_core` or other backends need matching changes.

**Comment by eduardosm** [comment]
Can we run MSVC CI on this PR to test CDB without waiting for rollup?

**Comment by m-ou-se** [comment]
> Can we run MSVC CI on this PR to test CDB without waiting for rollup?

Not very easily. You'd have to temporarily modify `src/ci/github-actions/ci.yml` in this PR to include that test runner in the ones that run on PRs. (And run `./x.py run src/tools/expand-yaml-anchors/` to update `.github/workflows/ci.yml`.)

**Comment by eduardosm** [comment]
What is going on here? I thought this was a transient failure, but it has already happened three times in a row.

```
---- [ui] src/test\ui-fulldeps\stdio-from.rs stdout ----

Some tests failed in compiletest suite=ui-fulldeps mode=ui host=x86_64-pc-windows-msvc target=x86_64-pc-windows-msvc
error: test run failed!
status: exit code: 101
command: PATH="D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage0-bootstrap-tools\x86_64-pc-windows-msvc\release\deps;D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage0\bin;D:\a\rust\rust\ninja;D:\a\rust\rust\msys2\mingw64\bin;C:\hostedtoolcache\windows\Python\3.10.4\x64\Scripts;C:\hostedtoolcache\windows\Python\3.10.4\x64;C:\msys64\usr\bin;D:\a\rust\rust\sccache;C:\Program Files\MongoDB\Server\5.0\bin;C:\aliyun-cli;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS;C:\tools\zstd;C:\Program Files\Mercurial;C:\hostedtoolcache\windows\stack\2.7.5\x64;C:\cabal\bin;C:\ghcup\bin;C:\tools\ghc-9.2.2\bin;C:\Program Files\dotnet;C:\mysql\bin;C:\Program Files\R\R-4.1.3\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\hostedtoolcache\windows\go\1.17.8\x64\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\hostedtoolcache\windows\Ruby\2.5.9\x64\bin;C:\tools\kotlinc\bin;C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.322-6\x64\bin;C:\npm\prefix;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\PowerShell\7;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files\nodejs;C:\Program Files\OpenSSL\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.5\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GitHub CLI;C:\tools\php;C:\Program Files (x86)\sbt\bin;C:\SeleniumWebDrivers\ChromeDriver;C:\SeleniumWebDrivers\EdgeDriver;C:\Program Files\Amazon\AWSCLIV2;C:\Program Files\Amazon\SessionManagerPlugin\bin;C:\Program Files\Amazon\AWSSAMCLI\bin;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files (x86)\Microsoft BizTalk Server;C:\Program Files\LLVM\bin;C:\Users\runneradmin\.dotnet\tools;C:\Users\runneradmin\.cargo\bin;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\test\\ui-fulldeps\\stdio-from\\a.exe"
stdout: none
--- stderr -------------------------------
I/O error: operation failed to complete synchronously
thread 'main' panicked at 'assertion failed: child2.wait()?.success()', D:\a\rust\rust\src/test\ui-fulldeps\stdio-from.rs:50:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------
```

**Comment by klensy** [comment]
> What is going on here? I thought this was a transient failure, but it has already happened three times in a row.

This is some other issue #95759, not related.

**Comment by klensy** [comment]
> MSVC tests have finally passed, reverted PR CI changes

You can squash commits a little, instead of having unrelated ones in history.

**Comment by eduardosm** [comment]
> You can squash commits a little, instead of having unrelated ones in history.

Done

**Comment by pnkfelix** [comment]
* This seems like it introduced a regression into the compilation times for a lot of important crates.
* I'm not clear on what its buying us, it seems like internal code cleanup? That doesn't justify a >=1% compile-time regression to webrender and syn.

@eduardosm or @m-ou-se , do either of you have time to look into the cause of this? I'm tempted to suggest we revert it, unless someone can present an argument for why we need it.

**Comment by pnkfelix** [comment]
nominating for attention from T-libs, in the hopes that someone can address my concerns above.

**Pull request merged**
