### PR TITLE
Stabilize non capturing closure to fn coercion

### LINKED ISSUE #39817: Tracking issue for RFC 1558: Allow coercing non-capturing closures to function pointers
[RFC](https://github.com/rust-lang/rfcs/pull/1558)

Summary:

> A closure that does not move, borrow, or otherwise access (capture) local variables should be coercable to a function pointer (fn).

Outstanding issues:

- [x] https://github.com/rust-lang/rust/issues/41755 -- inference shortcomings
- [x] https://github.com/rust-lang/rust/issues/40204 -- ICE

### PR DESCRIPTION
**Pull request by est31**
Stabilisation PR for non capturing closure to fn coercion.

closes #39817

### CODE REVIEW

**Comment by steveklabnik** [comment]
> all the other criteria needed for stabilisation are met.

Docs criteria is met.

**Comment by est31** [comment]
As agreed to on IRC, asking for early review (before the remaining 7 days of FCP are over) due to the branch date of beta in 7 days, otherwise the feature might not make it into 1.19. We can always back out later.

r? @aturon

**Comment by aturon** [comment]
Let's go ahead and get this into the queue.

@bors: r+

**Comment by est31** [comment]
It got merged yeey!

I'm not sure though why the PR doesn't get shown as "merged" by this. Github bug?

**Comment by Mark-Simulacrum** [comment]
GH seems to recognize that it is merged afterwards though; I can't reopen -- "commits are already merged"

**Pull request closed without merging**
