### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by matklad**
Successful merges:

 - #75954 (Unstable Book: add links to tracking issues for FFI features)
 - #75994 (`impl Rc::new_cyclic`)
 - #76060 (Link vec doc to & reference)
 - #76128 (Use Arc::clone and Rc::clone in documentation)
 - #76229 (Add missing link in README)
 - #76273 (Move some Vec UI tests into alloc unit tests)
 - #76274 (Allow try blocks as the argument to return expressions)
 - #76291 (Rename IsJoint -> Spacing )
 - #76299 (Make `Ipv4Addr` and `Ipv6Addr` const tests unit tests under `library`)
 - #76302 (Address review comments on `Peekable::next_if`)
 - #76303 (Link to `#capacity-and-reallocation` when using with_capacity)
 - #76305 (Move various ui const tests to `library`)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by matklad** [comment]
https://github.com/rust-lang-ci/rust/runs/1071200217#step:23:20475

Seems like the order of tests run by rustdoc changed, but I have no idea what might have caused this

**Comment by matklad** [comment]
locally, the test passes :( @jyn514 do you by any chance know what might be the problem here?

**Comment by matklad** [comment]
run out of steam for rollups for today, so closing this one!

**Comment by jyn514** [comment]
```
diff of stdout:

1
2	running 2 tests
-	test $DIR/failed-doctest-output.rs - OtherStruct (line 21) ... FAILED
4	test $DIR/failed-doctest-output.rs - SomeStruct (line 11) ... FAILED
+	test $DIR/failed-doctest-output.rs - OtherStruct (line 21) ... FAILED
5
6	failures:
7

-	---- $DIR/failed-doctest-output.rs - OtherStruct (line 21) stdout ----
-	error[E0425]: cannot find value `no` in this scope
-	  --> $DIR/failed-doctest-output.rs:22:1
-	   |
-	LL | no
-	   | ^^ not found in this scope
-
-	error: aborting due to previous error
-
-	For more information about this error, try `rustc --explain E0425`.
-	Couldn't compile the test.
19	---- $DIR/failed-doctest-output.rs - SomeStruct (line 11) stdout ----
20	Test executable failed (exit code 101).
21

30	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
31
32
+	---- $DIR/failed-doctest-output.rs - OtherStruct (line 21) stdout ----
+	error[E0425]: cannot find value `no` in this scope
+	  --> $DIR/failed-doctest-output.rs:22:1
+	   |
+	LL | no
+	   | ^^ not found in this scope
+
+	error: aborting due to previous error
+
+	For more information about this error, try `rustc --explain E0425`.
+	Couldn't compile the test.
33
34	failures:
35	    $DIR/failed-doctest-output.rs - OtherStruct (line 21)
```
It looks like the order rustdoc runs doctests is non-deterministic? I'm not sure why though ...

**Comment by jyn514** [comment]
> locally, the test passes 

Might have something to do with the CI runner having so many cores, I think GitHub Actions has 64 or something insane like that

**Pull request closed without merging**
