### PR TITLE
Represent MIR composite debuginfo as projections instead of aggregates

### PR DESCRIPTION
**Pull request by cjgillot**
Composite debuginfo for MIR is currently represented as
```
debug name => Type { projection1 => place1, projection2 => place2 };
```
ie. a single `VarDebugInfo` object with that name, and its value a `VarDebugInfoContents::Composite`.

This PR proposes to reverse the representation to be
```
debug name.projection1 => place1;
debug name.projection2 => place2;
```
ie. multiple `VarDebugInfo` objects with each their projection.

This simplifies the handling of composite debuginfo by the compiler by avoiding weird nesting.

Based on https://github.com/rust-lang/rust/pull/115139

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by cjgillot** [comment]
No idea what failed.
@bors retry

**Comment by davidtwco** [comment]
Are you waiting on another review?

**Comment by cjgillot** [comment]
I changed the implementation a little to simplify formatting. See the first commit. Could you take a second look?
For the test failures, they appear to come from 2 different builders are 2 different places, so I have no reason to suspect them to be real.

**Review by davidtwco — APPROVED** [review]

**Comment by nnethercote** [comment]
@cjgillot: this change regressed binary size by a small amount across many benchmarks. Was that expected? Could it be avoided?

**Comment by cjgillot** [comment]
From the stats, I understand that the regression is mostly in metadata size. That can be explained by the data structure change. The representation is more general, but unfortunately less compact: it repeats the type several times. I'm not sure how to shrink it back though.

**Pull request merged**
