### PR TITLE
IPs from tuples

### PR DESCRIPTION
**Pull request by zackmdavis**
A formulaic response to #43460.

### CODE REVIEW

**Comment by zackmdavis** [comment]
@rust-highfive help 

where are you??

**Comment by scottmcm** [comment]
@bstrie When is the tuple more helpful?

`Ipv4Addr : From<[u8;4]>` makes sense because of the `octets` method returning that, but having the tuple too feels like excess TIMTOWTDI to me.

(And if this makes sense, then there should also be `Ipv6Addr : From<(u16,u16,u16,u16,u16,u16,u16,u16)>` for consistency, but that feels silly to me.)

**Comment by alexcrichton** [comment]
This looks great to me, thanks @zackmdavis!

Let's see what the rest of @rust-lang/libs thinks...

@rfcbot fcp merge

**Comment by BurntSushi** [comment]
Do we really want an impl like `impl From<(u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8)> for Ipv6Addr`? What is the use case? Do people commonly write IPv6 addresses as 16-tuples?

**Comment by dtolnay** [comment]
I agree with @scottmcm. The existing impls exist because [`octets()`](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html#method.octets) and [`segments()`](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html#method.segments) deal with those types.

Tuples seem strictly worse than arrays here. In particular, at least you can iterate over an array. Are there any cases where these new impls would be an improvement over what can already be expressed?

**Comment by clarcharr** [comment]
The only benefit that I could see is improving linting so that if someone does `Ipv4Addr::from((1, 2, 3, 4))` or similar, it points out that you could do `Ipv4Addr::from([1, 2, 3, 4])`. Which is a reasonable lint, at least for clippy.

Other than that I think that implementing these is not the answer.

**Comment by scottmcm** [comment]
The error message is pretty good already, actually.  The example from the issue gives
```rust
   Compiling playground v0.0.1 (file:///playground)
error[E0277]: the trait bound `std::net::IpAddr: std::convert::From<({integer}, {integer}, {integer}, {integer})>` is not satisfied
 --> src/main.rs:2:42
  |
2 |     let _x: std::net::IpAddr = (0,0,0,0).into();
  |                                          ^^^^ the trait `std::convert::From<({integer}, {integer}, {integer}, {integer})>` is not implemented for `std::net::IpAddr`
  |
  = help: the following implementations were found:
            <std::net::IpAddr as std::convert::From<[u16; 8]>>
            <std::net::IpAddr as std::convert::From<[u8; 4]>>
            <std::net::IpAddr as std::convert::From<std::net::Ipv6Addr>>
            <std::net::IpAddr as std::convert::From<std::net::Ipv4Addr>>
            <std::net::IpAddr as std::convert::From<[u8; 16]>>
  = note: required because of the requirements on the impl of `std::convert::Into<std::net::IpAddr>` for `({integer}, {integer}, {integer}, {integer})`
```
Where the the second listed impl is the desired one.  (And it's the first listed impl if the example is changed to use `Ipv4Addr`.)

**Comment by alexcrichton** [comment]
We discussed this during libs triage today  and the conclusion was to close, agreeing with @dtolnay's rationale and @scottmcm's message as well.

Thanks though for the PR @zackmdavis!

**Pull request closed without merging**
