### PR TITLE
Deprecate range-specific `step_by`

### PR DESCRIPTION
**Pull request by scottmcm**
Deprecation attributes and test updates only.

Was replaced by an any-iterator version in https://github.com/rust-lang/rust/pull/41439

Last follow-up (this release) to https://github.com/rust-lang/rust/pull/42110#issuecomment-303210138

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks great to me, thanks! I think there's one remaining CI error though?

```
[01:03:21] error: use of deprecated item: replaced by `Iterator::step_by`
[01:03:21]    --> /checkout/src/libcollections/../libcollections/tests/vec_deque.rs:513:21
[01:03:21]     |
[01:03:21] 513 |     let seq = (0..).step_by(2).take(256);
[01:03:21]     |                     ^^^^^^^
[01:03:21]     |
[01:03:21]     = note: #[deny(deprecated)] implied by #[deny(warnings)]
[01:03:21] note: lint level defined here
[01:03:21]    --> /checkout/src/libcollections/../libcollections/tests/lib.rs:11:9
[01:03:21]     |
[01:03:21] 11  | #![deny(warnings)]
[01:03:21]     |         ^^^^^^^^
[01:03:21] 
[01:03:21] error: aborting due to previous error(s)
[01:03:21] 
[01:03:21] error: Could not compile `collections`.
```

**Comment by scottmcm** [comment]
Oops, I missed a step.  Closing temporarily; will re-open after https://github.com/rust-lang/rust/pull/42315.

**Comment by scottmcm** [comment]
Reopening as https://github.com/rust-lang/rust/pull/42315 has landed, allowing some more tests to be moved over to `Iterator::step_by`.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @scottmcm!

**Pull request merged**
