### PR TITLE
Fixed PhantomData markers in Arc and Rc

### PR DESCRIPTION
**Pull request by olegnn**
Include owned internal structs in `PhantomData` markers in `Arc` (`PhantomData<T>` => `PhantomData<ArcInner<T>>`) and `Rc` (`PhantomData<T>` => `PhantomData<RcBox<T>>`).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This is probably a little above my head -- cc @RalfJung

and r? @alexcrichton

**Comment by RalfJung** [comment]
> It includes internal struct Node which is not exposed (in Arc and Rc structs ArcInner and RcBox aren't included in marker)

I'd argue that `Arc` and `Rc` should be changed then. This is not about "what is exposed" but about "what is owned".

> It includes Box which is actually consumed when value is stored in list and used only to allocate memory on push and deallocate on pop

Aren't these `NonNull` pointers `Box`es? In that case, it seems reasonable to say that this node owns a `Box` and that `PhantomData` should reflect that.

**Comment by olegnn** [comment]
Just to add candidate to be fixed: 

- In this example https://github.com/rust-lang/rust/blob/master/src/libcore/cell.rs#L142 `PhantomData` isn't specified. 

In case of `LinkedList,` unlike in `Arc` or `Rc`, we are sure that `NonNull` pointer may be only received from `Box::into_raw_non_null` call, so use of `PhantomData<Box<...>>` even if `Box` doesn't actually exist in our type system but takes place in memory ([PhantomData definition](https://github.com/rust-lang/rfcs/pull/738/files#diff-b07cc9bcb90929f9faf6739874ec7d28R234)) makes sense.

However `NonNull` received from `Box::into_raw_non_null` due to `std::mem::forget` used in `Box::into_unique` doesn't require any `PhantomData` to stop `dropck` from deleting value ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5d9ff91f220865c99868091b8628a614)), it's here just to indicate that `LinkedList` owns `T` and can call destructor on its value when `LinkedList` will be dropped.

**Comment by RalfJung** [comment]
What do you mean by "stop dropck from deleting value"? dropck needs to detect possible cycles and, in particular, it needs to know *which other types will be dropped* when this one is dropped. Dropping a `Node` in the linked list deallocates a `Box<T>`, potentially, right? If yes, there should be a `PhantomData<Box<T>>`.

**Comment by alexcrichton** [comment]
I think @RalfJung knows more about this than I do!

r? @RalfJung

**Comment by RalfJung** [comment]
Thanks, this looks right to me! Once CI is green, can you do `bors r=RalfJung`?

@bors delegate+ rollup+

**Comment by olegnn** [comment]
Sure! Thank you for the explanation.

**Pull request merged**
