### PR TITLE
Increase macro recursion limit to 1024

### LINKED ISSUE #22552: The macro recursion limit is too low
I started hitting the recursion limit with the following macro (which isn't actually complete yet either)

``` rust
    use nixtest::assert_errno_eq;
    use libc::c_int;

    macro_rules! check_errno {
        ($errno:ident) => {{
            assert_errno_eq(stringify!($errno), $errno as c_int);
        }};

        ($errno:ident, $($rest:ident),+) => {{
            check_errno!($errno);
            check_errno!($($rest),*);
        }};
    }

    check_errno!(
        EPERM,
        ENOENT,
        ESRCH,
        EINTR,
        EIO,
        ENXIO,
        E2BIG,
        ENOEXEC,
        EBADF,
        ECHILD,
        EAGAIN,
        ENOMEM,
        EACCES,
        EFAULT,
        ENOTBLK,
        EBUSY,
        EEXIST,
        EXDEV,
        ENODEV,
        ENOTDIR,
        EISDIR,
        EINVAL,
        ENFILE,
        EMFILE,
        ENOTTY,
        ETXTBSY,
        EFBIG,
        ENOSPC,
        ESPIPE,
        EROFS,
        EMLINK,
        EPIPE,
        EDOM,
        ERANGE,
        EDEADLK,
        ENAMETOOLONG,
        ENOLCK,
        ENOSYS,
        ENOTEMPTY,
        ELOOP,
        ENOMSG,
        EIDRM,
        ECHRNG,
        EL2NSYNC,
        EL3HLT,
        EL3RST,
        ELNRNG,
        EUNATCH,
        ENOCSI,
        EL2HLT,
        EBADE,
        EBADR,
        EXFULL,
        ENOANO,
        EBADRQC,
        EBADSLT,
        EBFONT,
        ENOSTR,
        ENODATA,
        ETIME,
        ENOSR,
        ENONET,
        ENOPKG,
        EREMOTE,
        ENOLINK,
        EADV,
        ESRMNT,
        ECOMM,
        EPROTO,
        EMULTIHOP,
        EDOTDOT,
        EBADMSG,
        EOVERFLOW,
        ENOTUNIQ,
        EBADFD,
        EREMCHG,
        ELIBACC,
        ELIBBAD,
        ELIBSCN,
        ELIBMAX,
        ELIBEXEC,
        EILSEQ,
        ERESTART,
        ESTRPIPE,
        EUSERS,
        ENOTSOCK,
        EDESTADDRREQ,
        EMSGSIZE,
        EPROTOTYPE,
        ENOPROTOOPT,
        EPROTONOSUPPORT,
        ESOCKTNOSUPPORT,
        EOPNOTSUPP,
        EPFNOSUPPORT
```

### PR DESCRIPTION
**Pull request by sirideain**
Fixes #22552

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
If you add `Fixes #22552` to your PR description, then that issue will automatically be closed once we merge this.

**Comment by Mark-Simulacrum** [comment]
Pinged @jseyfried on IRC for a review.

**Review by jseyfried — APPROVED** [review]

**Comment by sgrif** [comment]
Has this shipped? I'm still getting errors saying I need to increase the recursion limit to 128 when using the latest nightly

**Pull request merged**
