### PR TITLE
save_analysis: Migrate diagnostic

### PR DESCRIPTION
**Pull request by wonchulee**
* Migrate the `rustc_save_analysis` crate's diagnostic to translatable diagnostic structs.

Depends on https://github.com/rust-lang/rust/pull/100694 and https://github.com/rust-lang/rust/pull/100754 for #[fatal(..)] support, then https://github.com/rust-lang/rust/commit/aa68eb4179881ed25106e675a6a224746f8fad5f, https://github.com/rust-lang/rust/commit/f5219a396083b764f3741e9e105685323a745ce8, https://github.com/rust-lang/rust/commit/7da52f694a4ff7c4b9870415584f2c86cec5ce62 can be removed. (I copied commits from https://github.com/rust-lang/rust/pull/100754)

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
LGTM! r=me once all the dependencies have landed and those commits are removed, etc, etc.

**Comment by davidtwco** [comment]
fatal support has landed now, so you should be able to rebase and continue to work on this :)

**Comment by wonchulee** [comment]
rebased on top of latest master branch, note that it still depends on https://github.com/rust-lang/rust/pull/100754/commits/e6a3632bf3463dff83d9566ac11ea02cc2fcb687 commit in the https://github.com/rust-lang/rust/pull/100754 PR.

**Comment by davidtwco** [comment]
> rebased on top of latest master branch, note that it still depends on [e6a3632](https://github.com/rust-lang/rust/commit/e6a3632bf3463dff83d9566ac11ea02cc2fcb687) commit in the #100754 PR.

That's okay, I'll approve this and if it lands first then I'll rebase otherwise you can :)

@bors r+

**Pull request merged**
