### PR TITLE
Kill moved locals in borrowed locals analysis

### LINKED ISSUE #94067: MIR generation for generators considers any borrowed or assigned value as live across yield points
Consider an example such as this:

```rust
impl Agent {
    async fn handle(&mut self) {
        let mut info = self.info_result.clone();
        info.node = None;
        let element = parse_info(info);
        let _ = send_element(element).await;
    }
}

fn parse_info(_: Info) -> Element { ... }

fn foo(agent: Agent) {
    assert_send(agent.handle());
    //~^ cannot be sent between threads safely
}
```

Let's assume `info` is `!Send`. The future returned from `handle` is currently `!Send` as well, because the MIR generation for the generator considers `info` to be live across the await point, despite the fact that `info` is consumed by `parse_info`. The reason is because the generator step [explicitly considers any borrowed local as live across the suspend point](https://cs.github.com/rust-lang/rust/blob/e646f3d2a9541952310778288854943678738ea9/compiler/rustc_mir_transform/src/generator.rs?q=locals_live_across_suspend_points++#L512).

With the more precise drop tracking in the type checker, it would be nice not to have to capture these at the MIR level. Currently drop tracking has to be more conservative than necessary in order to match the MIR behavior.

### LINKED ISSUE #96084: rebinding values in an async function can double the memory usage
Rebinding a value within an async function can cause the generated future to require twice the memory for the value. This seems to only happen if the value was borrowed earlier:

```rust
use std::mem;

async fn foo() {
    let x = [0u8; 100];
    async {}.await;
    println!("{}", x.len());
}

async fn a() {
    let fut = foo();
    let fut = fut;
    fut.await;
}

async fn b() {
    let fut = foo();
    println!("{}", mem::size_of_val(&fut));
    let fut = fut;
    fut.await;
}

fn main() {
    assert_eq!(mem::size_of_val(&foo()), 102);

    // 1 + sizeof(foo)
    assert_eq!(mem::size_of_val(&a()), 103);

    // 1 + (sizeof(foo) * 2)
    assert_eq!(mem::size_of_val(&b()), 205);
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=d4f0c621befd754b4a52fe3cf8e1ce13).

I don't know if this counts as a bug but the behavior is a bit surprising.

The effect is present in both debug and release modes with rustc 1.60.0.

### PR DESCRIPTION
**Pull request by b-naber**
We currently solely rely on `StorageDead` statements when killing locals in the borrowed locals analysis. Killing locals when they're moved should be fine since the borrow checker guarantees that there aren't any used borrows after the move. Currently this change only kills locals corresponding to `Place`s that don't have any projections, though we could in principle also track moves of projections here. Not sure whether this is worth it given that we will be move to `drop-tracking` and `mir-drop-tracking` at some point. Still, the current change seems like an improvement to me until then.

Fixes https://github.com/rust-lang/rust/issues/96084
Fixes https://github.com/rust-lang/rust/issues/94067 (I think? I believe the example by @eholk was missing a `Send` impl on `Agent`)

r? @tmandry maybe?

### CODE REVIEW

**Comment by JakobDegen** [comment]
Unfortunately, we can't do this. Putting aside for a minute that post-drop elab Mir is not expected to pass borrowck (and doesn't), this is also wrong in other cases:

```rust
async {
    let x = String::new();
    let p = &x as *const _;
    let _y = x;
    something.await;
    dbg!(*p);
}
```

There's a UCG issue tracking whether such code is UB or not, but we should not be assuming otherwise in the compiler

**Comment by b-naber** [comment]
Thanks for pointing this out. 

> Putting aside for a minute that post-drop elab Mir is not expected to pass borrowck (and doesn't)

Can you maybe elaborate on this, please (sorry not really that familiar with mir optimizations)?

> this is also wrong in other cases:
> 
> ```rust
> async {
>     let x = String::new();
>     let p = &x as *const _;
>     let _y = x;
>     something.await;
>     dbg!(*p);
> }
> ```
> 
> There's a UCG issue tracking whether such code is UB or not, but we should not be assuming otherwise in the compiler

Do you happen to have a link for that issue? Is [this](https://github.com/rust-lang/unsafe-code-guidelines/issues/367) the one you're referring to (this doesn't seem to touch on whether the provided example is UB or not, but I couldn't find any other issue that seemed more relevant). 

I only skimmed [your proposal](https://hackmd.io/X2V_SjFTQfySaT07NK940w), but it seems to me that something like a generator table would solve the 'future sizes' problem?!

Alternatively (though I haven't had time to properly think this through): What if we were to track "live" borrows and raw pointers (and keep a borrow/raw ptr -> local map) in the dataflow analysis for borrowed locals? That should also provide sufficient information to let us infer whether to keep a local across a yield point I think... Is there a flaw in that thinking?

**Comment by JakobDegen** [comment]
rust-lang/unsafe-code-guidelines#188 is the issue.

> What if we were to track "live" borrows and raw pointers (and keep a borrow/raw ptr -> local map) in the dataflow analysis for borrowed locals? That should also provide sufficient information to let us infer whether to keep a local across a yield point I think... Is there a flaw in that thinking?

There's nothing inherently flawed about this - doing more careful analysis lets us do more complicated optimizations. The difficulty is only in doing that analysis correctly. I'd invite you to share on Zulip if you have some concrete ideas for what you want to try

**Comment by b-naber** [comment]
Thanks for the answer, I'll ping you on zulip.

I'll go ahead and close this PR.

**Pull request closed without merging**
