### PR TITLE
ci: debug network failures while downloading awscli from PyPI

### PR DESCRIPTION
**Pull request by emilyalbini**
This adds some random debug code to our CI script while downloading awscli, to *hopefully* pinpoint what's causing the network failures.

r? @Mark-Simulacrum 
cc #62967

### CODE REVIEW

**Comment by pietroalbini** [comment]
@Centril feel free to rollup this btw

**Comment by ethomson** [comment]
The debugging steps [in this issue](https://github.com/pypa/warehouse/issues/3885) might also be interesting:

```
dig pypi.org
dig files.pythonhosted.org
openssl s_client -connect pypi.org:443
openssl s_client -connect files.pythonhosted.org:443
```

**Comment by pietroalbini** [comment]
@bors r=Mark-Simulacrum p=100

@ethomson good call! Added those.

**Comment by alex** [comment]
(👋 from the Python Infra Team, let me know if there's any way I can be helpful -- our TCP termination all happens at Fastly.)

**Comment by pietroalbini** [comment]
@bors r-

Uh, it got stuck somewhere, let me investigate.

**Comment by pietroalbini** [comment]
Well, we need to close the OpenSSL connection sooner or later...

@bors r=Mark-Simulacrum p=100

**Comment by pietroalbini** [comment]
Ok, apparently every debug step I added except for pings (which don't work at all on Azure Pipelines) is fine both before and after pip failed to download awscli ([build log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4419/logs/829)).

@Mark-Simulacrum pointed out that we're running Ubuntu 16.04's own pip 8.1.1 while version 19.2.1 is available. We *could* try to land a pip self-update, but since pip is the one having trouble reaching the network I'm not sure how much it would help.

The other "solution" I'm thinking about is to vendor `pip wheel awscli` on our mirror bucket and skip pip's networking altogether. SInce `curl` to AWS still works after pip fails to connect that should work, but it would be best to get down to the cause of this.

@alex do you have any other debugging steps (other than `ping`, `curl`, `dig` and `openssl s_client`) you'd like us to add to the CI configuration?

**Comment by alex** [comment]
Can you grab a `traceroute`? I think that's the only item from our usual network access issues template that you don't already have: https://github.com/pypa/warehouse/issues/new?template=access-issues.md

**Comment by pietroalbini** [comment]
> Can you grab a traceroute?

Unfortunately no, I tried a traceroute on my personal test repo and Azure Pipelines just filters all the packets.

**Comment by pietroalbini** [comment]
Opened a PR to skip PyPI altogether and download the packages from our S3 bucket, which appears to be reachable: https://github.com/rust-lang/rust/pull/63050. It's unfortunate that I can't drill down more into this, but I'm out of ideas and getting the builds working has way higher priority.

**Pull request merged**
