### PR TITLE
Improve PR job names in Github Actions preview

### PR DESCRIPTION
**Pull request by jyn514**
Fixes https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/PR.20CI.20job.20names.

Before: `CI / PR (mingw-check, false, ubuntu-20.04-16core-64gb) (pull_request)`
After:  `CI / PR - mingw-check (pull_request)`

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
r? infra-ci cc @RalfJung

**Comment by Mark-Simulacrum** [comment]
Maybe we should apply this to the auto and try sections too? e.g., https://github.com/rust-lang-ci/rust/actions/runs/4589308533/jobs/8104110343 looks like it's named similarly whereas just matrix.name is probably fine.

**Comment by Mark-Simulacrum** [comment]
r=me

**Comment by jyn514** [comment]
this does start showing "CI / auto - ${{ matrix.name }} (pull_request) Skipped" on PRs instead of "CI / auto (pull_request) Skipped", but given that the job is being skipped anyway, that seems ok.

@bors r=Mark-Simulacrum rollup

**Pull request merged**
