### PR TITLE
Expand rustdoc theme chooser x padding

### PR DESCRIPTION
**Pull request by pickfire**
image
image

But I still think there is room for improvement considering mdbook.

image

CC @GuillaumeGomez @jyn514

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It feels weird. Could you also increase the top and bottom paddings as well please?

**Comment by pickfire** [comment]
@GuillaumeGomez I tried adding that but it feels even weirder.

image

**Comment by GuillaumeGomez** [comment]
Looks better to me haha.

cc @rust-lang/rustdoc

**Comment by jyn514** [comment]
I don't have a strong opinion, I think the change either before or after the padding looks better.

**Comment by Manishearth** [comment]
i like it

**Comment by GuillaumeGomez** [comment]
Well then, let's go forward with the current change. We can always add top/bottom padding afterwards if more people feel like it's needed.

@bors: r+ rollup

**Comment by jyn514** [comment]
Looks spurious.

@bors retry

**Pull request merged**
