### PR TITLE
Rollup of 23 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
Successful merges:

 - #52955 (Update compiler test documentation)
 - #53019 (Don't collect() when size_hint is useless)
 - #53025 (Consider changing assert! to debug_assert! when it calls visit_with)
 - #53051 (Emit error for pattern arguments in trait methods)
 - #53059 (Remove explicit returns where unnecessary)
 - #53165 (Add aarch64-unknown-netbsd target)
 - #53208 (Don't panic on std::env::vars() when env is null.)
 - #53210 (Deny future duplication of rustc-ap-syntax)
 - #53223 (A few cleanups for rustc_data_structures)
 - #53229 (Make sure rlimit is only ever increased)
 - #53230 ([nll] enable feature(nll) on various crates for bootstrap: part 4)
 - #53231 (Add let keyword doc)
 - #53233 (targets: aarch64: Add bare-metal aarch64 target)
 - #53235 (Feature gate where clauses on associated type impls)
 - #53236 (Stabilise raw_identifiers feature)
 - #53238 (Update RLS)
 - #53240 (Add individual documentation for <integer>`.swap_bytes`/.`reverse_bits`)
 - #53253 (Remove unwanted console log)
 - #53264 (Show that Command can be reused and remodified)
 - #53267 (Fix styles)
 - #53273 (Add links to std::char::REPLACEMENT_CHARACTER from docs.)
 - #53274 (Remove statics field from CodegenCx)
 - #53290 (Make LLVM emit assembly comments with -Z asm-comments)

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+ 

Added #53240, #53253.

**Comment by kennytm** [comment]
@bors retry 

Apparently still not fixed 😕.

**Comment by kennytm** [comment]
@bors r+

Removed #53129 (UI test differ from actual output)

Added #52955, #53230.

**Comment by kennytm** [comment]
@bors r+

Updated #53165.

**Comment by kennytm** [comment]
@bors r+

Removed #53234 (we may not need it for debugging 9696... waiting for Travis response.)

Added #53238.

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout

**Comment by kennytm** [comment]
@bors r+

(Spurious error, travis-ci/travis-ci#9696)

Added #53274, #53223, #53231

**Comment by kennytm** [comment]
@bors r+

Added #53264, #53273, #53270.

**Comment by kennytm** [comment]
@bors r+

Removed  #53270 (test failed).

Added #53051.

**Comment by ljedrz** [comment]
😭

**Comment by kennytm** [comment]
@bors r+

Added #53290, #53267.

**Comment by matthiaskrgr** [comment]
Only 19 more to break the current record  ([38](https://github.com/rust-lang/rust/commit/1727b2331740cb6fe684cf81b774e290eb875b6e)) of most PRs per rollup! :tada: :balloon:

**Comment by kennytm** [comment]
@bors retry treeclosed-

(I'm signing off now, let's allow bors to automatically determine if Travis has fixed the network issue with the rest of the queue.)

**Pull request closed without merging**
