### PR TITLE
Never inline C variadics, cold functions, functions with incompatible attributes ...

### LINKED ISSUE #67863: MIR inlining checks for impossible condition
https://github.com/rust-lang/rust/blob/abf2e00e38ad404d563f03acbcf06b08813fd086/src/librustc_mir/transform/inline.rs#L218-L222

The generator is always transformed, as only the output of `optimized_mir` is passed to `should_inline`.

### LINKED ISSUE #78859: Calls to C variadic functions are inlined by MIR inliner
```rust
#![feature(c_variadic)]

fn main() {
    let s = unsafe { sum(4u32, 4u32, 30u32, 200u32, 1000u32) };
    assert_eq!(s, 1234);
}

#[no_mangle]
#[inline(always)]
pub unsafe extern "C" fn sum(n: u32, mut vs: ...) -> u32 {
    let mut s = 0;
    let mut i = 0;
    while i != n {
        s += vs.arg::<u32>();
        i += 1;
    }
    s
}
```

```console
$ rustc v.rs -Zmir-opt-level=2
error: internal compiler error: compiler/rustc_middle/src/mir/tcx.rs:84:25: deref projection of non-dereferenceable ty PlaceTy { ty: u32, variant_index: None }
```

@rustbot modify labels: +A-mir-opt, +A-mir-opt-inlining

### PR DESCRIPTION
**Pull request by tmiasko**
... and fix generator inlining.

Closes #67863.
Closes #78859.

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors r+

very excited about the generator inlining. With this we'll be able to craft some MIR optimizations for async code

**Comment by m-ou-se** [comment]
@bors r-

This failed in https://github.com/rust-lang/rust/pull/78992#issuecomment-726260028: https://github.com/rust-lang-ci/rust/runs/1392022160

**Comment by tmiasko** [comment]
Ignored new generator test on wasm.

**Comment by novacrazy** [comment]
Does this PR have the potential to break this workaround in hashbrown? https://github.com/rust-lang/hashbrown/pull/209

**Comment by tmiasko** [comment]
@novacrazy Thanks, that is a great example of a pattern that patch here tries to enable.

Currently in MIR the cold attribute can be only attached to a function. If a call to a cold function were to be inlined in MIR, the fact that this is a cold path is lost to the LLVM. The changes here disable inlining of cold functions at MIR level precisely to preserve this information. 

That being said, the MIR inlining is disabled by default. So unless `-Zmir-opt-level` >= 2 is used, there will be no impact anyway.

**Comment by thomcc** [comment]
> Currently in MIR the cold attribute can be only attached to a function. If a call to a cold function were to be inlined in MIR, the fact that this is a cold path is lost to the LLVM.

Anecdotally, this happens when LLVM inlines cold functions too (which it does if you only have one call to it unless it's `#[inline(never)]` 😞).

**Pull request merged**
