### PR TITLE
CI: use free runner in dist-aarch64-msvc

### PR DESCRIPTION
**Pull request by marcoieni**
similar to https://github.com/rust-lang/rust/pull/133175

try-job: dist-aarch64-msvc

### CODE REVIEW

**Comment by MarcoIeni** [comment]
The previous run took too long to build llvm. Hopefully the next run will be better because of a warm cache
image

image

**Comment by klensy** [comment]
sccache not used for that runner, but we can try to build manually and apply it here.

**Comment by MarcoIeni** [comment]
From the logs, I can see that we build llvm 4 times. The first 2 times is free. The other times take 52 seconds.

I guess we do this for PGO reasons. Maybe in this case we can't use a cache for LLVM, therefore we can't use a free runner. Kobzol, what do you think? 🤔

**Comment by klensy** [comment]
A don't see opt-dist, so there no pgo?

**Comment by Kobzol** [comment]
Yeah there should be no PGO in this job. We only do that for x64 Linux and Windows.

**Comment by klensy** [comment]
Weird, i see `--enable-sccache` enabled, but no output from it. I'll try run in #133033

**Comment by klensy** [comment]
Looked at both runs again: they both was on different image versions, so second one didn't reuse sccache, thats the reason.

**Comment by MarcoIeni** [comment]
Took 2h and 20m.
Jakub, imo this could be acceptable because it's under the average of 2h 30m. But it's near the limit of course.

Maybe we can merge it and monitor the auto builds in the next week?

**Comment by Kobzol** [comment]
I'd say the average is more like 3+ hours right now, based on Datadog metrics. So in that sense this duration should be fine.

**Comment by klensy** [comment]
Btw, is datadog filters out try builds internally? Because i see that data sent in try builds too.

**Comment by Kobzol** [comment]
It allows us to filter all of that, yeah. I was looking at just auto builds.

**Comment by MarcoIeni** [comment]
> I'd say the average is more like 3+ hours right now, based on Datadog metrics. So in that sense this duration should be fine.

Great! I put this as ready for review.

I will review what jobs are the bottleneck after this is merged anyway 👍

**Pull request merged**
