### PR TITLE
Added support for armv7-unknown-linux-gnueabi/musleabi

### LINKED ISSUE #63101: Support armv7-unknown-linux-gnueabi and armv7-unknown-linux-musleabi (soft-float variants)
Currently for armv7 only the hardfloat variants (`armv7-unknown-linux-gnueabihf` and `armv7-unknown-linux-musleabihf`) are supported.

I'll try to open a pull request as this seems to be a small change.

### PR DESCRIPTION
**Pull request by adrian-budau**
Fixes #63101 

Some things that are not done and I hope someone can help me with:

* During the ci build of `armv7-unknown-linux-gnueabi` `openssl` must be built (to build cargo) but `openssl` does not yet support this target. This feels slightly like a chicken-and-egg problem, any feedback is welcome.
* Should I add any tests for any of these targets?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I think it's fine to add this target to the compiler, but unfortunately we don't have CI budget to create a whole new compiler for this target. We *may* be able to fit it on CI but for now I think even that is sort of bursting at the seams (especially for the overflowing amount of ARM targets supported). Perhaps this could be added to the compiler for now and the CI bits can be considered separately?

**Comment by adrian-budau** [comment]
So I should split this into two 2 PR then? One just with the target files and the second one with the CI changes?

Regarding the CI, is it too much to build the compiler itself (`core` + `std` + `rustc`) for that target, and would just `std` be more acceptable? Or even the std would be too much of a stretch?

**Comment by alexcrichton** [comment]
Building the whole compiler is definitely too far for now unfortunately. Building just `std` is more possible, yes. We ideally want all our builders to complete in under 2 hours and the two "build a bunch of targets" builders are [tracked here for their timing](https://alexcrichton.github.io/rust-ci-timing-tracker/#series=dist-various-1,dist-various-2), so adding them do dist-various-2 is fine to do.

**Comment by adrian-budau** [comment]
Moved only the std build to `dist-various-2`. The `armv7-unknown-linux-gnueabi` target is slightly different from the other `*-gnueabi` though. It's built using the generic `arm-linux-gnueabi-gcc` found in the `ubuntu:18.04` docker image (because building the whole toolchain would add too much pressure on the CI). Hopefully everything is in order.

I tested the musl binaries and everything seems in order. For the gnu ones i checked the binar generate and it is softfloat ABI and doesn't contain any operations touching VFP registers.

**Comment by alexcrichton** [comment]
@bors: r+

Looks good to me, thanks!

**Comment by adrian-budau** [comment]
Is there anything in particular that I need to here? The commit seems to be in master, the pull request is closed, but bors seems to insist I should fix some merge conflicts?

**Comment by alexcrichton** [comment]
Oh nah that's just a bug in @bors, this is good to go!

**Pull request merged**
