### PR TITLE
Feature/nth back chunks

### PR DESCRIPTION
**Pull request by wizAmit**
A succinct implementation for nth_back on chunks. Thank you @timvermeulen for the guidance.

r? @timvermeulen

### CODE REVIEW

**Comment by timvermeulen** [comment]
Looks good to me, although I don't have permission to approve PRs here. 🙂

Since the implementations for `ChunksExact`/`ChunksMut`/`ChunksExactMut` are so similar, wanna give those a try too?

**Comment by wizAmit** [comment]
Ya.. will do that in a separate PR... Thanks a lot!!

**Comment by scottmcm** [comment]
Thanks for including good tests!

@bors r+ rollup

**Pull request merged**
