### PR TITLE
Create promoted MIR fragments for `const` and `static`s

### LINKED ISSUE #65732: RFC 2203 not implemented inside a `const` block
Thanks to [RFC 2203](https://github.com/rust-lang/rust/issues/49147), code like the following compiles on nightly:

```rust
fn main() {
    let _: [Option<Box<i32>>; 4] = [None; 4];
}
```

However, [as pointed out](https://github.com/rust-lang/rust/issues/49147#issuecomment-526093579) by @RalfJung, the same code fails to compile in a `const` block ([Playground]()):

```rust
const _: [Option<Box<i32>>; 4] = [None; 4];
```

Currently, there's two distinct implementations for promotion of temps, one for `fn` and `const fn` and one for `const` and `static`. RFC 2203 is implemented for the first but not the second.

I didn't see an actual issue for this. I'll close this as a dupe if @RalfJung already opened one.

cc #49147

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Resolves #65732.

The previous strategy of removing `Drop` and `StorageDead` for promoted locals only worked for rvalue lifetime extension and only if no `loop`s were present. This PR applies the approach currently used for `fn` and `const fn`s to `const` and `statics`.

This may have some performance impacts.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
r=me after running perf

**Comment by ecstatic-morse** [comment]
@bors try
@rust-timer queue

**Comment by ecstatic-morse** [comment]
This appears to actually be faster for `ucd` and `html5ever`. Presumably mutating MIR bodies in place is slower than creating new ones?

@bors r=eddyb

**Comment by matthewjasper** [comment]
> This appears to actually be faster for `ucd` and `html5ever`. Presumably mutating MIR bodies in place is much slower than creating new ones?

I think it's more likely that promoted are (mostly) ignored by borrowck.

**Pull request merged**
