### PR TITLE
 rustc_mir: insert a dummy access to places being matched on, when building MIR.

### LINKED ISSUE #47412: Matching on uninhabited unsafe places (union fields, raw pointer dereferences, etc.) allowed in safe code.
With the following code

```rust
fn main() {
    #[derive(Copy, Clone)]
    enum Void {}
    union A { a: (), v: Void }
    let a = A { a: () };
    match a.v {
    }
}
```

it is possible to invoke undefined behaviour in safe code without using unstable features.

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #47412 by adding a `_dummy = Discriminant(place)` before each `match place {...}`.

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+

cc @pnkfelix -- hopefully we can do better once your work is done

**Comment by eddyb** [comment]
@bors retry
 * rubygems download failure

**Comment by eddyb** [comment]
@bors retry
  * appveyor timeout?

**Comment by eddyb** [comment]
@bors retry
  * #48116

**Comment by eddyb** [comment]
@nikomatsakis We should figure out the backporting situation ASAP.

**Pull request merged**
