### PR TITLE
[WIP] Add `optimized_to_const` intrinsic

### PR DESCRIPTION
**Pull request by nbdd0121**
This PR adds an `optimized_to_const` that is roughly equivalent to GCC's `__builtin_constant_p` -- returns true if the argument is folded to const and false is not.

Example::
```rust
#![feature(core_intrinsics)]

use core::intrinsics::optimized_to_const;

fn is_zero(x: &[u8]) -> bool {
    x.iter().all(|x| *x == 0)
}

#[inline(always)]
fn is_definitely_zero<const N: usize>(x: &[u8; N]) -> bool {
    if optimized_to_const(x) {
        is_zero(x)
    } else {
        false
    }
}

pub fn foo() -> bool {
    is_definitely_zero(&[0; 32])
}

pub fn bar() -> bool {
    is_definitely_zero(&[1; 32])
}

pub fn baz(v: &[u8; 32]) -> bool {
    is_definitely_zero(v)
}
```
This code snippet generates:
```objdump
Disassembly of section .text.example::foo:

0000000000000000 <example::foo>:
   0:	b0 01                	mov    $0x1,%al
   2:	c3                   	retq   

Disassembly of section .text.example::bar:

0000000000000000 <example::bar>:
   0:	31 c0                	xor    %eax,%eax
   2:	c3                   	retq   

Disassembly of section .text.example::baz:

0000000000000000 <example::baz>:
   0:	31 c0                	xor    %eax,%eax
   2:	c3                   	retq   
```

cc @scottmcm @Mark-Simulacrum

r? @ghost

### CODE REVIEW

**Comment by nbdd0121** [comment]
Unfortunately LLVM currently seems to have problem generating optimal code: if array size is raised to 64, then `foo` will still generate code that does some compute and eventually return `true` (because LLVM can't fold `is_zero` despite constant input).

I tried another coding style
```rust
#[inline(always)]
fn is_definitely_zero2<const N: usize>(x: &[u8; N]) -> bool {
    let zero = is_zero(x);
    if optimized_to_const(&zero) {
        zero
    } else {
        false
    }
}
```
This works similarly if size is 32, but if size is 64, then in this case it's even worse: both `foo` and `baz` will generate code now that does all compute and unconditionally return `false`. Run opt on the generated & optimized LLVM assembly for the second time will remove all the unwanted computation and replace with a single `false` return, though.

**Comment by the8472** [comment]
If it has already been folded to a const at that point, could it be turned into a const fn returning the value as const?

**Comment by the8472** [comment]
I meant would something like this be possible?

```rust
const fn precompute(x: u64) -> Option<u32> {
   return match x {
     1 => // special case
     2 => // special case
     _ => None
   }
}



fn foo(x: u64)  -> u32 {
   let precomputed = const { precompute(optimized_or_default(&x, u64::MAX)) }
   // magic happens here -------------------------------------^
   if Some(p) = precomputed {
      return p;
   }
   // runtime impl 
}
```

Actually, thinking about it, this looks a lot like `const_eval_select`, except that it would also apply to const-optimizations in non-const contexts?

**Comment by Dylan-DPC** [comment]
Closing this as it has been inactive for a long time. Feel free to open a new pr if required

**Pull request closed without merging**
