### PR TITLE
Emit less MIR for format_args! with just a str literal

### PR DESCRIPTION
**Pull request by saethlin**
With https://github.com/rust-lang/rust/pull/110705, this is the code we now emit for `panic!("ow")` in an optimized build build:
```
bb0: {
    StorageLive(_2);
    StorageLive(_3);
    _4 = const _;
    _3 = _4 as &[&str] (Pointer(Unsize));
    StorageLive(_7);
    StorageLive(_5);
    _5 = Option::<&[core::fmt::rt::Placeholder]>::None;
    StorageLive(_6);
    _7 = const _;
    _6 = _7 as &[core::fmt::ArgumentV1<'_>] (Pointer(Unsize));
    _2 = Arguments::<'_> { pieces: _3, fmt: move _5, args: move _6 };
    StorageDead(_6);
    StorageDead(_5);
    StorageDead(_7);
    StorageDead(_3);
    _1 = panic_fmt(move _2);
}
```
I would prefer to at least see this:
```
bb0: {
    _2 = const _;
    _1 = panic(move _2);
}
```

Currently this PR emits:
```
    _1 = begin_panic::<&str>(const "ow");
```

r? @ghost

### CODE REVIEW

**Comment by saethlin** [comment]
The objective of this PR is to reduce the amount of MIR that we generate in the function body that expands `panic!`. Simply constructing a `fmt::Arguments` at runtime is more expense than I'd prefer to see.

If `format_args!` expands to an inline const for string literals, maybe that would permit addressing this situation without touching the expansion of `panic!`.

**Comment by m-ou-se** [comment]
Note that in std you can use the [`panic` function](https://doc.rust-lang.org/stable/core/panicking/fn.panic.html) instead of the panic macro, if you want simpler mir. (Prefer `panic()` over `panic_str()`, because the latter accepts non-'static strings, which results in less efficient code.)

**Comment by saethlin** [comment]
Hah! Yesterday @scottmcm was telling me to PR changing all the `panic!` with a string literal in std to `panic(`. I might try that as a perf experiment.

> Or would even something like a `Some(&str)` be too much to construct?

That would be an improvement over what we have right now, but...

>  In one of my (not very finished) experiments, `fmt::Arguments` for a string literal without arguments has the exact same representation as the `&'static str`.

:sweat_smile: I think the game I'm playing here might be more arcane than I realized, so here's a godbolt demo of what I'm talking about: https://godbolt.org/z/4hWM9cY7b

Explanation:
The MIR in the PR description is from an inlined and optimized `fmt::Arguments::new_const`. All the components of that `fmt::Arguments` is consts. So if we expanded to `panic_fmt(const { Arguments::new_const(...) })`, we would move all of the MIR for constructing the `Arguments` out of the function that contains the `panic!` and into a constant item. I think simply moving the MIR out of the function like this _might_ produce similar wins to not generating it in the first place, because the panicking function becomes a better inlining candidate and thus inlining it may reveal that he panic path is dead code. And if we inline the function in multiple places but don't delete the panicking branch, we still don't instantiate the code from `Arguments::new_const` multiple times per inlining of the function that contains `panic!`.

**Comment by saethlin** [comment]
Two incremental tests now fail, and I'm not exactly sure why.

**Comment by saethlin** [comment]
@rust-timer queue ff9187b56dc906f349b06ad92fc36298f414dc67

**Comment by saethlin** [comment]
@rust-timer build ff9187b56dc906f349b06ad92fc36298f414dc67

**Comment by saethlin** [comment]
Ah 🤦 the problem with the backtrace is that I built the standard library without debuginfo.

**Comment by saethlin** [comment]
I think my idea here doesn't work because we don't optimize consts, so we actually end up with substantially _more_ code in the end, because the subsequent benefits of shrinking the inline code size here doesn't net out.

I also think that this general situation can be solved by better constant propagation. We should have that eventually.

**Pull request closed without merging**
