### PR TITLE
Change `asm-comments` to `verbose-asm`, always emit user comments

### PR DESCRIPTION
**Pull request by tgross35**
Implements what is described in https://github.com/rust-lang/compiler-team/issues/762

Tracking issue: https://github.com/rust-lang/rust/issues/126802

### CODE REVIEW

**Comment by ehuss** [comment]
r? compiler

**Comment by Amanieu** [comment]
r=me once MCP is complete

**Comment by tgross35** [comment]
Just rebased to fix the formatting change. It has been 10 days since the FCP so I think this can be merged, seems like the labels on the issue just don't update automatically.

**Comment by tgross35** [comment]
Made the test only check x86. @rusbot ready

**Pull request merged**
