### PR TITLE
Ignore should_panic tests on android

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
These tests currently segfault sometimes. Android is a tier-2 target so
this is fine to disable instead of fixing.

Unfortunately, this isn't quite enough as rustdoc doesn't currently
correctly interpret the --exclude-should-panic flag (i.e., ignores it).
That proved to be harder to fix than I had time for so we're going to
leave it and hope that at least some of the failures are fixed.

Hopefully alleviates #55861; I don't have the time to investigate fixing rustdoc.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I will also note that I have not tested that this code works locally beyond "it compiles" but it looks like it should do what we want it to.

**Review by kennytm — APPROVED** [review]
r=me after fixing tidy.

**Comment by Centril** [comment]
Probably failed in https://github.com/rust-lang/rust/pull/59043#issuecomment-471173934, @bors r-

**Comment by kennytm** [comment]
We don't need `-Z unstable-options`?

**Comment by Mark-Simulacrum** [comment]
I suspect it's being passed to the wrong tool. I'll try to investigate further today.

**Comment by TimNN** [comment]
Ping from triage @Mark-Simulacrum: What is the status of this PR?

**Comment by Mark-Simulacrum** [comment]
I will try to get back to this sometime this week.

**Comment by Mark-Simulacrum** [comment]
I don't think I'll have the time soon to take this on unfortunately so I'm going to close this.

**Pull request closed without merging**
