### PR TITLE
Don't run allowed lints

### PR DESCRIPTION
**Pull request by jyn514**
Partial implementation of https://github.com/rust-lang/rust/issues/74704.

Not sure exactly why some lints are still run - I think they're being added later with `register_lint_pass`? I don't understand the machinery in `rustc_lint` very well. However this still cuts off a solid percent of the runtime: https://github.com/rust-lang/rust/pull/74718#issuecomment-663781456 and further improvements can be done in follow-up PRs.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I worry that such a blanket run-prevention may cause problems, e.g., future compatibility lints should still be shown in dependencies sometimes.

Are we confident none of the lints are actually emitting hard errors? I would feel uncomfortable doing this without an audit (and ideally some machinery to prevent it entirely).

**Comment by jyn514** [comment]
I don't know how to measure the performance improvements for this, AFAIK rustc-perf only runs on the last crate, not on any dependencies. Maybe we could change one of the benchmarks to use `--cap-lints allow`?

**Comment by jyn514** [comment]
> Are we confident none of the lints are actually emitting hard errors? I would feel uncomfortable doing this without an audit (and ideally some machinery to prevent it entirely).

Hmm ... I kind of assumed that lints wouldn't ever emit hard errors, but I'm not sure whether that's actually the case. How would I find out?

**Comment by Mark-Simulacrum** [comment]
Well, they probably shouldn't be, but I don't know of a good way to do that. I guess we can try to check the number of errors emitted before/after the pass and ICE if that's different, but that's pretty not great, and is a runtime check so we won't catch interesting cases probably.

We could also try and manually look through all the lint impls but that seems likely to miss things (especially since they're constantly changing).

**Comment by jyn514** [comment]
> we can try to check the number of errors emitted before/after the pass and ICE if that's different

I can implement that for now and see if anything pops up.

**Comment by crlf0710** [comment]
Triage: There's merge conflicts now.

**Comment by jyn514** [comment]
The merge conflicts are not where the work is 😆 this needs a lot more work implementing https://github.com/rust-lang/rust/pull/75605#issuecomment-694886979 before it can even be reviewed.

**Comment by jyn514** [comment]
So I don't lose it: the zulip conversation about this was https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/lint.20avoidance

**Comment by Dylan-DPC** [comment]
marking this as draft

**Comment by jyn514** [comment]
I'm probably not going to get around to this.

**Pull request closed without merging**
