### PR TITLE
Fix ICE on `include!(line!())` (regression)

### LINKED ISSUE #41776: ICE regression: "missing expansion backtrace"
The following code ICE's on nightly and beta, but does not ICE on stable:

```rust
include!(line!());
```

For an example that doesn't give an immediate compile error (but later on bc it can't find the file):

```rust
include!(concat!("help-files/", file!()));
```

The ICE looks like:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'missing expansion backtrace', /checkout/src/libcore/option.rs:794

```

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #41776.
r? @nrc

### CODE REVIEW

**Comment by alexcrichton** [comment]
ping @nrc, mind taking a look at this?

**Comment by alexcrichton** [comment]
@bors: retry

* [appveyor network issues](https://appveyor.statuspage.io/incidents/2g5jnq5cy1g1) #40474

**Comment by brson** [comment]
Accepting for backport. Small fix.

**Pull request merged**
