### PR TITLE
Drop tracking: track borrows of projections

### LINKED ISSUE #93648: Drop tracking ignores borrows with projections
For example:

```rust
fn main() {
    let _ = async {
        let mut s = (String::new(),);
        s.0.push_str("abc");
        std::mem::drop(s);
        async {}.await;
    };
}
```

```console
$ rustc +nightly-2022-01-22 --edition=2021 b.rs
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:755:13: Broken MIR: generator contains type (String,) in MIR, but typeck only knows about {ResumeTy, impl Future<Output = [async output]>, ()} and []
```

The `TryFrom<&PlaceWithHirId<'_>> for TrackedValue` fails for places with projections, so in that case borrow is never recorded:

https://github.com/rust-lang/rust/blob/4c55c8362de32be1530b2441c3e3a51e73edeb21/compiler/rustc_typeck/src/check/generator_interior/drop_ranges.rs#L133-L143

https://github.com/rust-lang/rust/blob/4c55c8362de32be1530b2441c3e3a51e73edeb21/compiler/rustc_typeck/src/check/generator_interior/drop_ranges/record_consumed_borrow.rs#L93-L102

### PR DESCRIPTION
**Pull request by eholk**
Previous efforts to ignore partially consumed values meant we were also not considering borrows of a projection. This led to cases where we'd miss borrowed types which MIR expected to be there, leading to ICEs.

This PR also includes the `-Zdrop-tracking` flag from #93313. If that PR lands first, I'll rebase to drop the commit from this one.

Fixes #93648

### CODE REVIEW

**Comment by tmiasko** [comment]
Thanks!

Drop tracking remains disabled by default, so this should be fine to include in a rollup.

@bors r+ rollup=always

**Comment by lqd** [comment]
let's wait a bit for a review on #93313 first before landing it with this PR, so a temporary @bors r- 

once the other lands, feel free to r=tmiasko on it thanks to: @bors delegate+

**Comment by tmiasko** [comment]
> let's wait a bit for a review on #93313 first before landing it with this PR

The only commit from #93313 included here is the one adding the drop tracking flag, which is necessary for testing purposes. I don't think it requires an additional review, especially that the general direction has been discussed on the latest wg-async triage meeting.

**Comment by lqd** [comment]
Ok, this was not clear to me with the different PRs in-flight including parts of #93313. Then let's land this one first and rebase yours when it lands.

@bors r=tmiasko

**Pull request merged**
