### PR TITLE
Workaround for #28871

### PR DESCRIPTION
**Pull request by nikomatsakis**
Give preference to projections from where-clauses over those from trait definitions. This makes #28871 work again, though I think there's more to fix in this general area.

r? @arielb1 
cc @brson (fixes regression)

### CODE REVIEW

**Comment by brson** [comment]
@rust-lang/lang nominating this for backport to beta. I'd like to do so tomorrow.

**Comment by nikomatsakis** [comment]
Presuming we opt to land it, I'm ok w/ backporting this; it's a very minor patch, fixes a regression. (That was, indeed, the point.)

**Comment by arielb1** [comment]
@nikomatsakis 

I would prefer to normalize the projection's trait-ref (so they will deduplicate), but I guess this makes sense too.

**Comment by arielb1** [comment]
r+ modulo the test working.

**Comment by nikomatsakis** [comment]
@arielb1

> I would prefer to normalize the projection's trait-ref (so they will
deduplicate), but I guess this makes sense too.

In general I prefer that as well. I didn't have much time yesterday so I
added this as a quick fix, since it seemed to (as you say) also make sense.
It's certainly consistent with our strategy elsewhere, and I think that it
won't make any (useful) programs work that won't also work later as we
improve our strategy.

**Comment by nikomatsakis** [comment]
Given the time frame, I'm going to declare this beta-accepted, as I don't anticipate any objections from @rust-lang/lang members. Let me know if I am mistaken.

**Pull request merged**
