### PR TITLE
[beta] Backports

### PR DESCRIPTION
**Pull request by MaloJaffre**
Cherry-picked into beta:
- #47401
- #47494
- #47503
- #47507

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! It looks like the "lower link args" isn't cleanly backporting (build failure), mind fixing that up? If you're busy though I can take a look!

**Comment by MaloJaffre** [comment]
Thanks @alexcrichton for this info, I will take a look at it now!

**Comment by MaloJaffre** [comment]
The build should be fixed now.

**Comment by alexcrichton** [comment]
@bors: r+ p=5

Thanks!

**Pull request merged**
