### PR TITLE
fix bug in folding for constants

### PR DESCRIPTION
**Pull request by nikomatsakis**
These was a bug in the folding for constants that caused it to overlook bound regions. This branch includes some other little things that I did while trying to track the bug down.

r? @oli-obk

### CODE REVIEW

**Comment by varkor** [comment]
Is there a small regression test we could add here?

**Comment by nikomatsakis** [comment]
I was wondering the same thing. The only way I observed this problem was in tandem with other changes that exposed it, but those changes can't be landed yet.

**Comment by nikomatsakis** [comment]
@oli-obk this was responsible for the debug assertions you were telling me about

**Pull request merged**
