### PR TITLE
rustc_trans: don't write discriminants for uninhabited variants

### LINKED ISSUE #46519: Regression: "SIGFPE: erroneous arithmetic operation" while compiling Servo in release mode
Running `RUSTFLAGS="-Z time-passes" mach build --release -p style -v`, rustc 1.23.0-nightly (5041b3bb3 2017-11-19) succeeds, rustc 1.23.0-nightly (33374fa9d 2017-11-20) fails without an error message. Range: https://github.com/rust-lang/rust/compare/5041b3bb3...33374fa9d. #45225 seems to be the only compiler change in that range. CC @eddyb

Full output: https://gist.github.com/anonymous/e0881601130599a2c3853f876b5efc7a

Extract that seems most relevant:

```rust
$ RUSTFLAGS="-Z time-passes" mach build --release -p style -v
cargo build -p style --manifest-path /home/simon/servo3/ports/servo/Cargo.toml --release -v
       Fresh unicode-xid v0.0.4
[…]
       Fresh style_traits v0.0.1 (file:///home/simon/servo3/components/style_traits)
   Compiling style v0.0.1 (file:///home/simon/servo3/components/style)
     Running `rustc --crate-name […]`
  time: 0.113; rss: 82MB	parsing
[…]
    time: 0.115; rss: 1659MB	codegen passes [core-fmt-builders.volatile]
    time: 0.042; rss: 1659MB	llvm function passes [style-values-specified-font]
    time: 1.306; rss: 1660MB	llvm module passes [std-collections-hash-map.volatile]
    time: 1.213; rss: 1661MB	llvm module passes [style-properties-declaration_block]
    time: 0.514; rss: 1659MB	llvm module passes [core-result.volatile]
    time: 0.040; rss: 1662MB	llvm function passes [style-animation]
error: Could not compile `style`.

Caused by:
  process didn't exit successfully: `rustc --crate-name style […]` (signal: 8, SIGFPE: erroneous arithmetic operation)
```

`time-passes` is used to get some idea of what stage of compilation is happening.

So far I have managed to run rustc with correct arguments within gdb.

My daily "build servo with rust nightly" job did not catch this because this only happens in release mode.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes #46519.

Patch as suggested by eddyb: https://github.com/rust-lang/rust/issues/46519#issuecomment-349443519

### CODE REVIEW

**Comment by arielb1** [comment]
Test please

@bors r-

**Comment by SimonSapin** [comment]
Added a test that I confirmed failing in Nightly with:

```
$ rustc +nightly ~/rust3/src/test/run-pass/issue-46519.rs --test -O            
zsh: floating point exception (core dumped)  rustc +nightly ~/rust3/src/test/run-pass/issue-46519.rs --test -O
```

**Comment by eddyb** [comment]
@bors retry
* some spurious Ruby AWS failure

**Pull request merged**
