### PR TITLE
doc: Remove extra whitespace in the middle of lines to provide alignment

### PR DESCRIPTION
**Pull request by nhowell**
"Idiomatic code should not use extra whitespace in the middle of a line to provide alignment."
http://aturon.github.io/style/whitespace.html

I realize the linked page still needs an RFC, but the docs should be written in accordance with the guidelines nevertheless.

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is now out of date. I guess if that's our guideline, it's our guideline. r=me after the rebase.

**Comment by nhowell** [comment]
All done. Hopefully I did the rebasing correctly.

**Comment by steveklabnik** [comment]
Doing this manually as part of https://github.com/rust-lang/rust/pull/21300

**Pull request closed without merging**
