### PR TITLE
Add AIX platform support document

### PR DESCRIPTION
**Pull request by ecnelises**

### CODE REVIEW

**Comment by ecnelises** [comment]
CC'ing @bzeq

**Comment by JohnTitor** [comment]
Could you fix the CI failure?
@rustbot author

**Comment by ecnelises** [comment]
Maybe pending on https://github.com/rust-lang/rust/pull/116004?

**Comment by workingjubilee** [comment]
> ##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
rustc/platform-support.html:444: broken link - `rustc/platform-support/aix.html`
rustc/print.html:8369: broken link - `rustc/platform-support/aix.html`

It looks like this has an error when generating the html links.

**Comment by workingjubilee** [comment]
I have no idea how tho'...

**Comment by ecnelises** [comment]
Ah, I got it! The link should also be added to [SUMMARY.md](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/SUMMARY.md), otherwise in HTML files there won't be `aix.html`. Fixed.

**Comment by workingjubilee** [comment]
Oh! Thank you for figuring that out!

**Pull request merged**
