### PR TITLE
Add a test for #16403

### LINKED ISSUE #16403: LLVM assertion failure for creating extern fns with same name but different signatures
The following crashes rustc:

``` rust
fn main() {
    {
        extern fn foo() { }
    }

    {
        extern fn foo(_bar: uint) { }
    }
}
```

It doesn't even give the nice ICE message, just this:
```
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Users/rustbuild/src/rust-buildbot/slave/nightly-mac/build/src/llvm/include/llvm/Support/Casting.h, line 237.
Abort trap: 6
```

I am using `rustc 0.12.0-pre-nightly (4d4eb1023 2014-08-02 23:36:09 +0000)`. This issue looks similar to #5791?

### PR DESCRIPTION
**Pull request by nagisa**
Closes #16403

### CODE REVIEW

**Comment by nagisa** [comment]
Such space sensitive, much strict.

**Comment by apasel422** [comment]
Should the PR message have a `Closes #16403` in it?

**Pull request merged**
