### PR TITLE
[RFC] Implement `..` in tuple (struct) patterns

### PR DESCRIPTION
**Pull request by petrochenkov**
An implementation for https://github.com/rust-lang/rfcs/pull/1492
The sub-list bindings `pat..` are not implemented.
The code needs some cleanup, but otherwise works.

### CODE REVIEW

**Comment by alexcrichton** [comment]
(just making sure *some* assignment is given, sounds like this should wait for the RFC to land though)

**Comment by arielb1** [comment]
Here `match x { (..) => { /*..*/ } }` when the type of `x` is unknown unifies `x` with a tuple of size 0. I would prefer to emit a "the type of this value must be known" error.

**Comment by petrochenkov** [comment]
@arielb1 
Hm, I thought I did exactly that. If tuple pattern contains `..` then I call `structurally_resolved_type` to determine the expected tuple length and it requires the type for `x` to be known.

**Comment by arielb1** [comment]
Maybe I read the code wrong. Just be sure to add a test.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Comment by alexcrichton** [comment]
Oh right if this is waiting on https://github.com/rust-lang/rfcs/pull/1492 I'm just trying to clear out the queue, but feel free to resubmit as soon as the RFC is merged

**Pull request closed without merging**
