### PR TITLE
Improve Path and PathBuf docs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks! :smile: 

@bors: r+ rollup

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by jonathandturner** [comment]
@bors r-

From the best I can tell, this seems to fail bors.  https://buildbot.rust-lang.org/builders/auto-mac-64-opt/builds/10236/steps/test/logs/stdio

@GuillaumeGomez - can you confirm that this works on the latest Rust?  Some new error message went in recently that may have changed things.

**Comment by jonathandturner** [comment]
@bors r-

Looks like this might have some broken links on OS X.  This is from the latest rollup:

```
Linkcheck stage2 (x86_64-apple-darwin)
core/result/index.html:392: broken link - core/result/struct.Result.html
core/result/struct.IntoIter.html:54: broken link - core/result/struct.Result.html
std/path/struct.Path.html:474: broken link - std/path/ffi/struct.OsStr.html
std/path/struct.Path.html:496: broken link - std/path/fmt/trait.Display.html
std/path/struct.PathBuf.html:598: broken link - std/path/ffi/struct.OsStr.html
std/path/struct.PathBuf.html:620: broken link - std/path/fmt/trait.Display.html
std/result/index.html:392: broken link - std/result/struct.Result.html
std/result/struct.IntoIter.html:54: broken link - std/result/struct.Result.html
```

**Comment by GuillaumeGomez** [comment]
@bors: r-

Still link failure.

**Comment by GuillaumeGomez** [comment]
Updated links and checked manually after

```
make docs
```

All good now.

**Pull request merged**
