### PR TITLE
musl: build toolchain libs with -fPIC

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/59411

### CODE REVIEW

**Comment by pnkfelix** [comment]
Hmm. The only reason I could imagine to try to avoid doing this would be if we didn't want to apply position-independent code everywhere for MUSL, and the only reason I could imagine doing that would be if we thought there would be lost optimization opportunities.

But, given that we are seeing an important customer (ripgrep) fail to build, and this change fixes it, I'm going to go ahead and take the plunge here, approving the change without first trying to evaluation the performance impact (which I honestly suspect will be insignificant in most and maybe all cases).

**Comment by mati865** [comment]
In fact this PR sort of brings PIC back. Before https://github.com/rust-lang/rust/pull/58575 `x86_64-unknown-linux-musl` was build from this script: https://github.com/rust-lang/rust/blob/237bf3244fffef501cf37d4bda00e1fce3fcfb46/src/ci/docker/scripts/musl.sh.

The day will come when all binutils < 2.26 distros are EOL (for Ubuntu 14.04 it's end of the next month and for CentOS 6 it's end of 2020). That will be beautiful day because `PIC` and [another workaround](https://github.com/rust-lang/rust/pull/58575/files#diff-8467aca8e420f0c67d7f3f234b3edf62R41) can be dropped without causing breakage to supported distros.

**Comment by pnkfelix** [comment]
thanks @mati865 for the clarification!

**Pull request merged**
