### PR TITLE
Update to LLVM 19 rc2

### LINKED ISSUE #128555: Incremental compilation regression from 1.79 to 1.80: rustc-LLVM ERROR: Intervals are contiguous/overlapping
### Code

Repro repository and steps: https://github.com/rust-lang/rust/issues/128555#issuecomment-2266697909

I've bisected between 1.79.0 and 1.80.0:

searched nightlies: from nightly-2024-04-28 to nightly-2024-06-07
regressed nightly: nightly-2024-05-10
searched commit range: https://github.com/rust-lang/rust/compare/87293c9585a7fb2cc83ca9949ae79661d5d3c31a...8f9080db423ca0fb6bef0686ce9a93940cdf1f13
regressed commit: https://github.com/rust-lang/rust/commit/cb93c24bf36b3367714516fc2308cf6856916eeb

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.9</summary>

Host triple: x86_64-pc-windows-msvc
Reproduce with:
```bash
cargo bisect-rustc --start 1.79.0 --end 1.80.0 --preserve -- build --release -p <crate-name>
```
</details>

<details>
<summary>Old context</summary>

#### Context

It's a company project with a workspace that compiles ~680 crates on a clean compile.

From initial testing it seems like an incremental compilation bug :S `cargo build` works, `cargo build --release` fails, but when setting `incremental = false` in `[profile.relese]`, `cargo build --release` succeeds again.

`cargo build --release -p <crate-name>` also reproduces the issue, dropping the number of crates down to "only" 203.

This is our profile config:

```toml
[profile.dev]
debug = 0
incremental = true
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev.build-override]
codegen-units = 8
debug = 0
debug-assertions = false
opt-level = 2
overflow-checks = false

[profile.release]
debug = 1
# overwritten in xtask for production builds
incremental = true

[profile.release.build-override]
codegen-units = 8
debug = 0
debug-assertions = false
opt-level = 0
overflow-checks = false
```

</details>

### Meta

This reproduces on 1.80 and the current nightly (as of writing this ticket). This **does not** reproduce on 1.79.0.

`rustc --version --verbose`:
```
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: x86_64-pc-windows-msvc
release: 1.80.0
LLVM version: 18.1.7
```

and

```
rustc 1.82.0-nightly (8e86c9567 2024-08-01)
binary: rustc
commit-hash: 8e86c9567154dc5a9ada15ab196d23eae2bd7d89
commit-date: 2024-08-01
host: x86_64-pc-windows-msvc
release: 1.82.0-nightly
LLVM version: 19.1.0
```

### Error output

```
Intervals are contiguous
!40 = !{i8 -20, i8 -17, i8 4, i8 -20}
rustc-LLVM ERROR: Broken module found, compilation aborted!
error: could not compile `<crate name>` (lib)
```

There is no backtrace being printed, even with `RUST_BACKTRACE=1`.

### PR DESCRIPTION
**Pull request by nikic**
Update from ~rc1 to rc2.

Fixes https://github.com/rust-lang/rust/issues/128555.

### CODE REVIEW

**Comment by DianQK** [comment]
It seems like https://github.com/rust-lang/llvm-project/commit/ccf4c38bdd73f1a37ec266c73bdaef80e39f8cf6 hasn't been pushed?

**Comment by DianQK** [comment]
> It seems like [rust-lang/llvm-project@ccf4c38](https://github.com/rust-lang/llvm-project/commit/ccf4c38bdd73f1a37ec266c73bdaef80e39f8cf6) hasn't been pushed?

I have pushed. :p

**Comment by jieyouxu** [comment]
> The job **`dist-x86_64-msvc`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/10341580915/job/28623550763) [(plain)](https://github.com/rust-lang-ci/rust/commit/3f61072bb462e44435f34ce40998b82560db6a8d/checks/28623550763/logs)
> Click to see the possible cause of the failure (guessed by this bot)
> 
> ```
> error: linking with `link.exe` failed: exit code: 1104
> [...]
>   = note: LINK : fatal error LNK1104: cannot open file 'C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps\rustc_main-abe621a284360afc.exe'␍
> ```

Pinging back #127883.

**Comment by Mark-Simulacrum** [comment]
Perf results look like noise to me.

**Pull request merged**
