### PR TITLE
Update pulldown-cmark version to fix markdown list issue

### LINKED ISSUE #92971: rustdoc: some nested lists are rendered incorrectly
# Summary

Nested markdown lists as below are not rendered as nested lists, but as single-level lists.

Works as expected:

* stable (`cargo 1.58.0 (7f08ace4f 2021-11-24)`, `rustdoc 1.58.0 (02072b482 2022-01-11)`)
* beta (`cargo 1.58.0-beta (7f08ace4f 2021-11-24)`, `rustdoc 1.58.0-beta.3 (4aa9d237c 2022-01-08)`)

Produces unintended output:
* nightly (`cargo 1.60.0-nightly (358e79fe5 2022-01-04)`, `rustdoc 1.60.0-nightly (1bd4fdc94 2022-01-12)`)

Initially reported at <https://github.com/rust-lang/docs.rs/issues/1594>.

## Source input

```rust
//! * foo
//!     + bar
//!     + baz
```

## Expected output

* foo
    + bar
    + baz

With `cargo doc` (with stable toolchain):
screenshot-2022-01-17-011919+0900

## Actual output

* foo + bar + baz

With `cargo +nightly doc` with nightly toolchain:
screenshot-2022-01-17-011924+0900

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #92971.

r? @camelid

### CODE REVIEW

**Comment by camelid** [comment]
cc @rust-lang/clippy, but this is just a patch release

**Review by xFrednet — APPROVED** [review]
The Clippy part looks good to me :+1:

**Comment by GuillaumeGomez** [comment]
Should we approve it then?

**Comment by klensy** [comment]
Maybe bump mdbook too, to dedupe pulldown-cmark?

**Comment by GuillaumeGomez** [comment]
Updated in https://github.com/rust-lang/mdBook/pull/1729.

**Comment by klensy** [comment]
> Updated in [rust-lang/mdBook#1729](https://github.com/rust-lang/mdBook/pull/1729).

I'm talked about bumping it here in [rustbook ](https://github.com/rust-lang/rust/tree/master/src/tools/rustbook) crate, but it's good too.

**Comment by GuillaumeGomez** [comment]
> > Updated in [rust-lang/mdBook#1729](https://github.com/rust-lang/mdBook/pull/1729).
> 
> I'm talked about bumping it here in [rustbook ](https://github.com/rust-lang/rust/tree/master/src/tools/rustbook) crate, but it's good too.

It's not a direct dependency apparently. You meant to update it from one of its dependencies?

**Comment by klensy** [comment]
> It's not a direct dependency apparently. You meant to update it from one of its dependencies?


```
$ cargo update -p mdbook
    Updating crates.io index
    Updating mdbook v0.4.14 -> v0.4.15
    Removing pulldown-cmark v0.8.0

```

**Comment by GuillaumeGomez** [comment]
Done, thanks for the command!

**Review by camelid — APPROVED** [review]
Thanks!

**Comment by camelid** [comment]
This regression is on beta, so nominating for backport.

**Comment by camelid** [comment]
Backport accepted on Zulip [here](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/beta.20backport.202022-01-25).

**Pull request merged**
