### PR TITLE
Disable LLVM assertions on Nightly, enable them in "alt" builds.

### PR DESCRIPTION
**Pull request by SimonSapin**
Per IRC discussion https://mozilla.logbot.info/rust-infra/20171106#c13812170-c13812204

Background: https://internals.rust-lang.org/t/disabling-llvm-assertions-in-nightly-builds/5388/14

### CODE REVIEW

**Comment by aturon** [comment]
cc @rust-lang/infra, just to keep everyone in the loop on this change.

**Comment by kennytm** [comment]
I think we also need to update `.travis.yml` to point the `try` branch to the alt build so crater and perf can still test with assertion enabled.

**Comment by SimonSapin** [comment]
@kennytm I’ve pushed another commit. How does it look?

Though I don’t know if perf *should* have LLVM assertions, since that produces timings different from what everyone will use.

**Comment by kennytm** [comment]
@SimonSapin Unfortunately, unless we have two `try` branches we are stuck with either sacrificing perf or crater. At least enabling assertions allows the metrics be comparable before and after this PR.

@bors r=aturon

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum @alexcrichton Will we back-collect perf.rlo data after this (e.g. by compiling with the former "alt builds" for older nightlies)?

**Comment by Mark-Simulacrum** [comment]
Since this will require changes to perf.rlo anyway, I should be able to make it so that we properly collect non-alt before and alt now. Ideally, we'd add something like `@bors perf` which would output dedicated artifacts for perf (and then we wouldn't have to share between crater, which does want assertions, and perf, which doesn't). It's also worth thinking about tracking how "bad" assertions are.

**Comment by michaelwoerister** [comment]
> Ideally, we'd add something like @bors perf which would output dedicated artifacts for perf

I would be nice if perf.rlo tested with debug assertions disabled too since that is closer to how stable releases perform. Also, I'm quite liberal with debug assertions `:)`

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum 

> It's also worth thinking about tracking how "bad" assertions are.

by this do you mean running with assertions both enable and disabled and comparing the results?

**Comment by Mark-Simulacrum** [comment]
Yes, exactly.

**Comment by shepmaster** [comment]
@SimonSapin if you happen to push another commit, can you fix the typo "Nigthly"?

**Comment by oyvindln** [comment]
Is it a good idea to merge this as long as #45220 isn't solved, given that it may result in that ending up accessing out-of-bounds memory rather than panicking?

**Comment by SimonSapin** [comment]
```rust
[01:12:34] failures:
[01:12:34] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:331:21
[01:12:34] 
[01:12:34] ---- [run-make] run-make/sanitizer-memory stdout ----
[01:12:34]      
[01:12:34] error: make failed
[01:12:34] status: exit code: 2
[01:12:34] command: "make"
[01:12:34] stdout:
[01:12:34] ------------------------------------------
[01:12:34] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-memory.stage2-x86_64-unknown-linux-gnu:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib:" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-memory.stage2-x86_64-unknown-linux-gnu -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-memory.stage2-x86_64-unknown-linux-gnu  -g -Z sanitizer=memory -Z print-link-args uninit.rs | grep -q librustc_msan
[01:12:34] /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/sanitizer-memory.stage2-x86_64-unknown-linux-gnu/uninit 2>&1 | grep -q use-of-uninitialized-value
[01:12:34] Makefile:6: recipe for target 'all' failed
[01:12:34] 
[01:12:34] ------------------------------------------
[01:12:34] stderr:
[01:12:34] ------------------------------------------
[01:12:34] warning: unused variable: `y`
[01:12:34]   --> uninit.rs:15:9
[01:12:34]    |
[01:12:34] 15 |     let y = xs[0] + xs[1];
[01:12:34]    |         ^
[01:12:34]    |
[01:12:34]    = note: #[warn(unused_variables)] on by default
[01:12:34]    = note: to avoid this warning, consider using `_y` instead
[01:12:34] 
[01:12:34] make: *** [all] Error 1
[01:12:34] 
[01:12:34] ------------------------------------------
[01:12:34] 
[01:12:34] thread '[run-make] run-make/sanitizer-memory' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2505:8
[01:12:34] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:12:34] 
[01:12:34] 
[01:12:34] failures:
[01:12:34]     [run-make] run-make/sanitizer-memory
[01:12:34] 
[01:12:34] test result: FAILED. 163 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

I’m trying to reproduce locally.

**Comment by SimonSapin** [comment]
:(

```rust
$ ./x.py test src/test/run-make --test-args sanitizer-memory
[…]
running 1 test
test [run-make] run-make/sanitizer-memory ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 163 filtered out
```

**Comment by SimonSapin** [comment]
Ah, this test is entirely inside `ifdef SANITIZER_SUPPORT`. When building with `--enable-sanitizers` I get errors below. The relevant part seems to be `error: aggregate ‘sigaltstack handler_stack’ has incomplete type and cannot be defined`.

```c
[ 90%] Built target RTAsan_dynamic.x86_64
CMakeFiles/Makefile2:1636: recipe for target 'lib/asan/CMakeFiles/asan.dir/rule' failed
Makefile:632: recipe for target 'asan' failed

--- stderr
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/ubsan/ubsan_handlers_cxx.cc: In function ‘void __ubsan::HandleCFIBadType(__ubsan::CFICheckFailData*, __ubsan::ValueHandle, bool, __ubsan::ReportOptions)’:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/ubsan/ubsan_handlers_cxx.cc:111:15: warning: ‘CheckKindStr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   const char *CheckKindStr;
               ^~~~~~~~~~~~
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc: In function ‘int __sanitizer::TracerThread(void*)’:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:278:22: error: aggregate ‘sigaltstack handler_stack’ has incomplete type and cannot be defined
   struct sigaltstack handler_stack;
                      ^~~~~~~~~~~~~
make[3]: *** [lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/sanitizer_stoptheworld_linux_libcdep.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc: In function ‘__sanitizer::fd_t __sanitizer::OpenFile(const char*, __sanitizer::FileAccessMode, __sanitizer::error_t*)’:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:215:27: warning: ‘flags’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   fd_t res = internal_open(filename, flags, 0660);
              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/asan_interceptors.cc:265:0:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc: In function ‘__sanitizer::uptr __interceptor_ptrace(int, int, void*, void*)’:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:2810:21: warning: ‘local_iovec.__sanitizer::__sanitizer_iovec::iov_len’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __sanitizer_iovec local_iovec;
                     ^~~~~~~~~~~
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/asan_interceptors.cc:59:10: warning: ‘local_iovec.__sanitizer::__sanitizer_iovec::iov_base’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     uptr __offset = (uptr)(offset);                                     \
          ^~~~~~~~
In file included from /home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/asan_interceptors.cc:265:0:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:2810:21: note: ‘local_iovec.__sanitizer::__sanitizer_iovec::iov_base’ was declared here
   __sanitizer_iovec local_iovec;
                     ^~~~~~~~~~~
In file included from /home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/asan_interceptors.cc:265:0:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc: In function ‘__sanitizer::uptr __interceptor_ptrace(int, int, void*, void*)’:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:2810:21: warning: ‘local_iovec.__sanitizer::__sanitizer_iovec::iov_len’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   __sanitizer_iovec local_iovec;
                     ^~~~~~~~~~~
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/asan_interceptors.cc:59:10: warning: ‘local_iovec.__sanitizer::__sanitizer_iovec::iov_base’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     uptr __offset = (uptr)(offset);                                     \
          ^~~~~~~~
In file included from /home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/asan_interceptors.cc:265:0:
/home/simon/rust/src/libcompiler_builtins/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:2810:21: note: ‘local_iovec.__sanitizer::__sanitizer_iovec::iov_base’ was declared here
   __sanitizer_iovec local_iovec;
                     ^~~~~~~~~~~
make[1]: *** [lib/asan/CMakeFiles/asan.dir/rule] Error 2
make: *** [asan] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.26/src/lib.rs:599:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

thread 'main' panicked at 'command did not execute successfully: "/home/simon/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "8" "--release" "--features" "panic-unwind jemalloc backtrace profiler" "--manifest-path" "/home/simon/rust/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', src/bootstrap/compile.rs:882:8
```

**Comment by SimonSapin** [comment]
I tried running `src/ci/docker/run.sh x86_64-gnu` instead, but before I could get to the relevant test it stopped because of unrelated failure, which I suppose are due to Docker configuration issues.

```
panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', /checkout/src/libstd/net/tcp.rs:1014:27
panicked at 'received error for `UdpSocket::bind(&addr)`: Cannot assign requested address (os error 99)', /checkout/src/libstd/net/udp.rs:1066:25
```
```
failures:
    net::tcp::tests::clone_accept_concurrent
    net::tcp::tests::clone_accept_smoke
    net::tcp::tests::clone_while_reading
    net::tcp::tests::close_read_wakes_up
    net::tcp::tests::close_readwrite_smoke
    net::tcp::tests::connect_loopback
    net::tcp::tests::double_bind
    net::tcp::tests::fast_rebind
    net::tcp::tests::multiple_connect_interleaved_greedy_schedule
    net::tcp::tests::multiple_connect_interleaved_lazy_schedule
    net::tcp::tests::multiple_connect_serial
    net::tcp::tests::partial_read
    net::tcp::tests::peek
    net::tcp::tests::read_eof
    net::tcp::tests::shutdown_smoke
    net::tcp::tests::smoke_test
    net::tcp::tests::socket_and_peer_name
    net::tcp::tests::tcp_clone_smoke
    net::tcp::tests::tcp_clone_two_read
    net::tcp::tests::tcp_clone_two_write
    net::tcp::tests::write_close
    net::udp::tests::connect_send_peek_recv
    net::udp::tests::peek_from
    net::udp::tests::set_nonblocking
    net::udp::tests::socket_name_ip4
    net::udp::tests::socket_smoke_test_ip4
    net::udp::tests::udp_clone_smoke
    net::udp::tests::udp_clone_two_read
    net::udp::tests::udp_clone_two_write
```

**Comment by alexcrichton** [comment]
The [error in the test](https://github.com/rust-lang/rust/pull/45810#issuecomment-343664878) is hidden by the `run-make` test due to `2>&1 | grep ...`. That test should change from:

```make
a:
    foo 2>&1 | grep bar
```

to 

```make
a:
    foo 2>&1 | tee $(TMPDIR)/out
    grep bar $(TMPDIR)/out
```

That way we should see the error.

I don't know what the [sanitizer compilaton failure](https://github.com/rust-lang/rust/pull/45810#issuecomment-343681399) is, it may be C++ compiler oddities. I don't know if I've ever gotten them to compile locally myself.

The [docker error](https://github.com/rust-lang/rust/pull/45810#issuecomment-343694614) is IPv6 not being enabled. Something about docker disables ipv6 by default. Not sure why, but locally I had to do something to fix that.

**Comment by SimonSapin** [comment]
@alexcrichton I’ve added `tee` as you suggested, could you send this to Travis again?

I tried configuring `{"ipv6": true}` in `/etc/docker/daemon.json` and got `Error initializing network controller: Error creating default "bridge" network: could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network`

**Comment by SimonSapin** [comment]
I guess it was intermittent?

**Comment by kennytm** [comment]
@SimonSapin You mean the failure in https://github.com/rust-lang/rust/pull/45810#issuecomment-343664878?

**Comment by SimonSapin** [comment]
@kennytm Yes. This run only added some use of `tee` in a makefile to show more output and hopefully gain more info about that failure, but I didn’t do anything to fix it.

**Comment by kennytm** [comment]
Ok. I've recorded that as a spurious failure. We can debug that when it happens again.

**Comment by SimonSapin** [comment]
This time the log did not show any more info, I believe because libtest captures output and only shows it when a test fails.

```
[01:07:03] test [run-make] run-make/sanitizer-memory ... ok
```

**Comment by gnzlbg** [comment]
The comment in `.travis.yml` still says that alt-builds don't have assertions enabled, but it is actually the other way around 😆

**Comment by kennytm** [comment]
@gnzlbg Well PRs welcomed 😅

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/46330

**Comment by michaelwoerister** [comment]
@SimonSapin that's a comment you have to dereference twice in order to get to the actual content `:D`

**Pull request merged**
