### PR TITLE
Fix const prop miscompilations of references with projections.

### LINKED ISSUE #67529: Miscompilation with -Zmir-opt-level=2
Derived from https://github.com/rust-lang/rust/blob/26286c7ad0e8a5efc1e6a8ef88ffd64723112ae8/src/test/ui/dynamically-sized-types/dst-field-align.rs

```rust
struct Baz<T: ?Sized> {
    a: T
}

fn main() {
    let d : Baz<[i32; 4]> = Baz { a: [1,2,3,4] };
    assert_eq!([1, 2, 3, 4], d.a);
}
```

```bash
$ rustc -V
rustc 1.42.0-nightly (fc5deca21 2019-12-21)
$ rustc example/dst-field-align.rs && ./dst-field-align
$ rustc -Zmir-opt-level=2 example/dst-field-align.rs && ./dst-field-align
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[1, 2, 3, 4]`,
 right: `[0, 0, 0, 0]`', example/dst-field-align.rs:10:5
```

---

```rust
struct Baz<T: ?Sized> {
    a: T
}

fn main() {
    let d : Baz<[i32; 4]> = Baz { a: [1,2,3,4] };
    println!("{:?}", d.a);
}
```

```bash
$ rustc example/dst-field-align.rs && ./dst-field-align
[1, 2, 3, 4]
$ rustc -Zmir-opt-level=2 example/dst-field-align.rs && ./dst-field-align
[0, 0, 0, 0]
```

This issue has been assigned to @jumbatm via [this comment](https://github.com/rust-lang/rust/issues/67529#issuecomment-570098515).

### PR DESCRIPTION
**Pull request by jumbatm**
Closes #67529.

Previously, we only returned early out of const prop of uninitialised Refs to Places if they had no projection. This meant that for uninitialised Places with a projection, when we forced an allocation, we wouldn't have a value to initialise the allocation with, leading us to replace the Ref with an allocation which we would never (and could never) initialise.

This PR fixes this by early returning out of const_prop if the Place's base local is uninitialised for Refs with projections, too.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @wesleywiser

**Comment by oli-obk** [comment]
@bors r-

Ok, so new information from #67862 suggests that we're definitely doing the wrong thing here and should fix this properly.

Keeping this on hold until the discussion in #67862 reaches a conclusion

**Comment by oli-obk** [comment]
Thanks! The linked issues have been fixed by outright stopping to const prop references, so i'm closing this PR

**Comment by jumbatm** [comment]
Cool - no worries!

**Pull request closed without merging**
