### PR TITLE
Update older URLs pointing to the first edition of the Book

### LINKED ISSUE #42589: Some links in the API documentation point to the older URL of the Book
The first edition of the Book is moved from `/book` into `/book/first-edition`, but some links in the API documentation are not following the change. For example, in [`core::ops::Deref`][deref] documentation, there is a link to the '`Deref` coercions' page of the first edition, with older URL structure.

[deref]: https://doc.rust-lang.org/core/ops/trait.Deref.html

This makes kind of "broken link" in the documentation, though it's not a real broken link, because the pages under the older URL suggest that we try with the namespace added. However, it does add additional link that visitors should follow, which probably isn't what they want.

I think the solution is simple; adding `first-edition` namespace if the link pointing to the Book does not have any namespace. May I work on this issue?

### PR DESCRIPTION
**Pull request by tirr-c**
Fixes #42589.

### CODE REVIEW

**Comment by arielb1** [comment]
Thanks for the PR @VBChunguk! @steveklabnik (or someone else) will be reviewing your PR soon.

**Comment by steveklabnik** [comment]
r=me when travis passes. Thanks @VBChunguk !

**Pull request merged**
