### PR TITLE
Address diagnostics regression for `const_char_encode_utf8`.

### PR DESCRIPTION
**Pull request by bjoernager**
Relevant tracking issue: #130512

This PR regains full diagnostics for non-const calls to `char::encode_utf8`.

### CODE REVIEW

**Comment by bjoernager** [comment]
r? libs-api

**Comment by bjoernager** [comment]
I'm unsure whether this should be targeted libs-api but I assumed so after the previous PR. I apologise if this was the wrong decision.

**Review by dtolnay — APPROVED** [review]
Nice! Thank you.

**Comment by bjoernager** [comment]
Added fixme note as recommended by @RalfJung.

**Comment by RalfJung** [comment]
Thanks!

@bors r=dtolnay

**Pull request merged**
