### PR TITLE
Use the existing LLVM GitInfo for checking rebuilds

### LINKED ISSUE #59565: Nightly fails to build unless git is installed
Regressed by https://github.com/rust-lang/rust/pull/59303. Source archives don't have `.git` subdirectory, so missing `git` executable shouldn't be fatal.

```
thread 'main' panicked at 'Command::new("git").args(&["rev-parse", "--verify",
                           &format!("@:./{}" ,
                                    submodule)]).current_dir(&builder.src).output() failed with No such file or directory (os error 2)', src/bootstrap/native.rs:82:26
```

http://beefy9.nyi.freebsd.org/data/112amd64-default/497233/logs/errors/rust-nightly-1.35.0.20190330_1.log

### PR DESCRIPTION
**Pull request by cuviper**
Fixes #59565

### CODE REVIEW

**Comment by cuviper** [comment]
Hmm, except "dev" builds ignore git, which isn't what we want for LLVM...

https://github.com/rust-lang/rust/blob/fc8581d7420b63b2cc5eac1c57a40de785859448/src/bootstrap/config.rs#L649-L650

**Comment by Mark-Simulacrum** [comment]
I'm not sure, but perhaps we could add an argument to GitInfo new or something along those lines that would usually be the config.ignore_git but for LLVM just true.

**Comment by cuviper** [comment]
I just pushed a commit which roughly does that -- passing `ignore_git: bool` instead of `&Config`, always `true` for LLVM dirs.

**Comment by Mark-Simulacrum** [comment]
Looks good to me! Bumping priority since this fixes a regression.

@bors r+ p=1

**Pull request merged**
