### PR TITLE
Rollup of all extended-error PRs.

### PR DESCRIPTION
**Pull request by michaelsproul**
I did a manual merge of all the extended error PRs as we were getting merge conflicts yesterday. I think this is preferable to merging separately as I ended up having to manually merge @nham and @GuillaumeGomez's commits.

Rollup of #24458, #24482 and #24488.
#24482 and #24488 were already re-approved, and would need to be cancelled if this is merged instead.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 50f75f3

Thanks!

**Comment by killercup** [comment]
FYI, In the meantime #24552 was created that adds E0133.

**Comment by killercup** [comment]
Also, #24525 for E0018.

**Comment by michaelsproul** [comment]
@killercup: These are just already approved ones. I'll do another roll up once the two PRs you mentioned are approved.

**Comment by GuillaumeGomez** [comment]
@killercup: Mine still needs to be approved. It remains one sentence bad written.

**Pull request merged**
