### PR TITLE
Update to LLVM 17

### LINKED ISSUE #109671: LLVM 17 regression: tests/ui/abi/stack-protector.rs no longer actually attempts stack-smashing
LLVM change 0d4a709bb876824a0afa5f86e138e8ffdcaf7661 (https://reviews.llvm.org/D145210) appears to have broken the test for stack-protection. tests/ui/abi/stack-protector.rs fails both with and without stack protection enabled, because the test now makes it to the `TEST BUG: stack smash unsuccessful` panic, presumably because something new in LLVM's optimizations skips the stack smash.

Filing this bug and disabling the test in our Rust/LLVM HEADs CI for now so we see other (more urgent) breakage reliably.

### PR DESCRIPTION
**Pull request by nikic**
Expected LLVM 17.0.0 release date: Sep 5th
Rust 1.73 release date: Oct 5th

Compatibility changes in this PR:
 - Drop LLVM_RUSTLLVM check for target-cpu table, which no longer requires a patch with LLVM 17.
 - Update powerpc data layouts, which now include function alignment information. As usual, downgrade for older LLVM versions.
 - Adjust the stack-protector.rs test so that the stack smashing does not get optimized away.
 - Adjust path of crtbegin.c and crtend.c in compiler-rt.
 - Updated dist-riscv64-linux to use binutils 2.36 in order to recognize the zicsr feature, which is no longer part of the base ISA.
 - Fixed symlink for asm include directory on dist-various-2. We should use `/usr/include/x86_64-linux-gnu/asm` for the host, rather than `/usr/include/asm-generic`.

Upstream patches:
 - [x] https://reviews.llvm.org/D156525 (backported)

Perf run: https://perf.rust-lang.org/compare.html?start=f239bb6bea94d16d902c36d72b5cabdddefb3cab&end=8030d71a95a3ea79f5fc95232c32f9b78effb92d&stat=instructions:u

Fixes #109671.

Successful: dist-x86_64-linux, dist-aarch64-linux, dist-s390x-linux, dist-powerpc-linux, armhf-gnu, wasm32

### CODE REVIEW

**Comment by klensy** [comment]
>  CMake 3.20.0 or higher is required.  You are running version 3.17.5

but was bumped in #113714?

**Comment by Kobzol** [comment]
Probably https://github.com/rust-lang/rust/pull/113931 should be merged first to make sure that all build dependencies are fine with Ubuntu 22.04 (and no manual CMake installation).

**Comment by nikic** [comment]
Interesting results. We have nice improvements pretty much across the board -- plus massive regressions on incr-unchanged, where apparently LLVM artifacts fail to get reused.

**Comment by nikic** [comment]
Yes, that change is indeed the culprit. On a reduced test case, the first compile gives:
```
 INFO rustc_codegen_llvm::back::lto local module: 0 - 158l6g54xltqjdw1
 INFO rustc_codegen_llvm::back::lto local module: 1 - 2sil2f6ja82h010e
 INFO rustc_codegen_llvm::back::lto local module: 2 - 5395i5os48gea2td
 INFO rustc_codegen_llvm::back::lto local module: 3 - 42ftsl7374bdxwzq
 INFO rustc_codegen_llvm::back::lto thin LTO data created
 INFO rustc_codegen_llvm::back::lto thin LTO cache key map loaded
 INFO rustc_codegen_llvm::back::lto prev_key_map: None
 INFO rustc_codegen_llvm::back::lto curr_key_map: ThinLTOKeysMap {
    keys: {
        "2sil2f6ja82h010e": "8D73C589CF26C24E75E83F3E5629E62BDD94E3EC",
        "5395i5os48gea2td": "7C3EEE0BCDA2EC39CC5FD1DFABB19164BE8501E4",
        "42ftsl7374bdxwzq": "FF75215A91C52ED5D1A5D912BB0A598B784D0501",
        "158l6g54xltqjdw1": "338840040B48CF2B55CD6E762DE56A9DBE43B7C7",
    },
}
 INFO rustc_codegen_llvm::back::lto checking which modules can be-reused and which have to be re-optimized.
 INFO rustc_codegen_llvm::back::lto  - 158l6g54xltqjdw1: re-compiled
 INFO rustc_codegen_llvm::back::lto  - 2sil2f6ja82h010e: re-compiled
 INFO rustc_codegen_llvm::back::lto  - 5395i5os48gea2td: re-compiled
 INFO rustc_codegen_llvm::back::lto  - 42ftsl7374bdxwzq: re-compiled
```
And on the second:
```
 INFO rustc_codegen_llvm::back::lto upstream or cached module "42ftsl7374bdxwzq"
 INFO rustc_codegen_llvm::back::lto upstream or cached module "158l6g54xltqjdw1"
 INFO rustc_codegen_llvm::back::lto upstream or cached module "5395i5os48gea2td"
 INFO rustc_codegen_llvm::back::lto upstream or cached module "2sil2f6ja82h010e"
 INFO rustc_codegen_llvm::back::lto thin LTO data created
 INFO rustc_codegen_llvm::back::lto thin LTO cache key map loaded
 INFO rustc_codegen_llvm::back::lto prev_key_map: Some(
    ThinLTOKeysMap {
        keys: {
            "2sil2f6ja82h010e": "8D73C589CF26C24E75E83F3E5629E62BDD94E3EC",
            "5395i5os48gea2td": "7C3EEE0BCDA2EC39CC5FD1DFABB19164BE8501E4",
            "42ftsl7374bdxwzq": "FF75215A91C52ED5D1A5D912BB0A598B784D0501",
            "158l6g54xltqjdw1": "338840040B48CF2B55CD6E762DE56A9DBE43B7C7",
        },
    },
)
 INFO rustc_codegen_llvm::back::lto curr_key_map: ThinLTOKeysMap {
    keys: {
        "2sil2f6ja82h010e": "6A0F71E211ABFD89A3214A4124AC6F9C5E3751B5",
        "42ftsl7374bdxwzq": "FF75215A91C52ED5D1A5D912BB0A598B784D0501",
        "5395i5os48gea2td": "7C3EEE0BCDA2EC39CC5FD1DFABB19164BE8501E4",
        "158l6g54xltqjdw1": "338840040B48CF2B55CD6E762DE56A9DBE43B7C7",
    },
}
 INFO rustc_codegen_llvm::back::lto checking which modules can be-reused and which have to be re-optimized.
 INFO rustc_codegen_llvm::back::lto  - 42ftsl7374bdxwzq: re-used
 INFO rustc_codegen_llvm::back::lto  - 158l6g54xltqjdw1: re-used
 INFO rustc_codegen_llvm::back::lto  - 5395i5os48gea2td: re-used
 INFO rustc_codegen_llvm::back::lto  - 2sil2f6ja82h010e: re-compiled
```
The cache key calculation now depends on the module order, and it differs between the two runs (for "local module" and "cached module").

**Comment by scottmcm** [comment]
20 seconds better on bootstrap?!?  Amazing!

**Comment by scottmcm** [comment]
Is this ready to go now, other than a rebase to remove c30e55bfac9e9273ef34325994f099a6f97a70ff ?

**Comment by nikic** [comment]
Yes, I think this is ready. Ready for a long string of CI failures...

r? @cuviper

**Comment by scottmcm** [comment]
Dunno if it's transient, but the queue's short and it was a quick failure, so
@bors retry

**Comment by nikic** [comment]
Adjusted the path to crtbegin.c/crtend.c.

@bors r=cuviper

**Comment by nikic** [comment]
I believe what happened here is that the zicsr extension was split off from the base ISA (but is, at least for now, still enabled by default) and we now need a newer binutils that recognizes that extension.

**Comment by nikic** [comment]
Based on a local test, binutils 2.36 is sufficient.

@bors r=cuviper

**Comment by nikic** [comment]
Build fails due to undefined SYS_mmap, introduced in https://reviews.llvm.org/D151023, with a fix for 32-bit ARM in https://github.com/llvm/llvm-project/commit/82909f4e0529a0ac26adbd05eda7244b11d99cba.

The weird thing is that this is the LLVM build for the x86_64-unknown-linux-gnu host, so it should be available there. I suspect that this is due to this hack: https://github.com/rust-lang/rust/blob/89acdae9f243da15549c7a8bc737e6240c301790/src/ci/docker/host-x86_64/dist-various-2/Dockerfile#L131-L135

That means we use asm-generic for the host compiler as well, and I think we end up using `__BIT_PER_LONG=32` because of that.

**Comment by nikic** [comment]
Adjusted the path to the correct asm directory, which makes the dist-various-2 build succeed locally.

@bors r=cuviper

**Comment by nikic** [comment]
Lots of crashes like this on i686-gnu-nopt:
```
2023-07-30T22:30:52.4390992Z ---- [ui] tests/ui/abi/abi-sysv64-register-usage.rs stdout ----
2023-07-30T22:30:52.4391504Z 
2023-07-30T22:30:52.4392363Z error: test compilation failed although it shouldn't!
2023-07-30T22:30:52.4392834Z status: signal: 11 (SIGSEGV) (core dumped)
2023-07-30T22:30:52.4395837Z command: RUSTC_ICE="0" "/checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/abi/abi-sysv64-register-usage.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/i686-unknown-linux-gnu/stage2" "--target=i686-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/i686-unknown-linux-gnu/test/ui/abi/abi-sysv64-register-usage/a" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/i686-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/i686-unknown-linux-gnu/test/ui/abi/abi-sysv64-register-usage/auxiliary"
2023-07-30T22:30:52.4397940Z stdout: none
2023-07-30T22:30:52.4398574Z --- stderr -------------------------------
2023-07-30T22:30:52.4399549Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xaa8563)[0xeb91c563]
2023-07-30T22:30:52.4400202Z linux-gate.so.1(__kernel_sigreturn+0x0)[0xf7fa0560]
2023-07-30T22:30:52.4400921Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x8067097)[0xf2edb097]
2023-07-30T22:30:52.4401761Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x809d616)[0xf2f11616]
2023-07-30T22:30:52.4402532Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x809cced)[0xf2f10ced]
2023-07-30T22:30:52.4403394Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x7fd5ed3)[0xf2e49ed3]
2023-07-30T22:30:52.4404179Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x8065f1d)[0xf2ed9f1d]
2023-07-30T22:30:52.4404953Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x805c6c8)[0xf2ed06c8]
2023-07-30T22:30:52.4405903Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(_RNvMs5_NtCsaw8FpV7vQFb_12rustc_middle3mirNtB5_4Body3new+0x23f)[0xf2eca4bf]
2023-07-30T22:30:52.4406788Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5ac3518)[0xf0937518]
2023-07-30T22:30:52.4407553Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5ac0e46)[0xf0934e46]
2023-07-30T22:30:52.4408310Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6af0144)[0xf1964144]
2023-07-30T22:30:52.4409069Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6d3bf4f)[0xf1baff4f]
2023-07-30T22:30:52.4409828Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6e4842a)[0xf1cbc42a]
2023-07-30T22:30:52.4410593Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6d441df)[0xf1bb81df]
2023-07-30T22:30:52.4411598Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(_RNvMs1e_NtCsaw8FpV7vQFb_12rustc_middle2tyNtNtB6_7context6TyCtxt12instance_mir+0x423)[0xf2de91e3]
2023-07-30T22:30:52.4412503Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a3b76a)[0xf08af76a]
2023-07-30T22:30:52.4413259Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a381fc)[0xf08ac1fc]
2023-07-30T22:30:52.4414015Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a38709)[0xf08ac709]
2023-07-30T22:30:52.4414760Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a840f8)[0xf08f80f8]
2023-07-30T22:30:52.4415546Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a637bf)[0xf08d77bf]
2023-07-30T22:30:52.4416430Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a6933f)[0xf08dd33f]
2023-07-30T22:30:52.4417204Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a347c9)[0xf08a87c9]
2023-07-30T22:30:52.4417984Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x5a45f64)[0xf08b9f64]
2023-07-30T22:30:52.4418744Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6aeb6ea)[0xf195f6ea]
2023-07-30T22:30:52.4419521Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6d0964a)[0xf1b7d64a]
2023-07-30T22:30:52.4420312Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6df3e60)[0xf1c67e60]
2023-07-30T22:30:52.4421164Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0x6c74962)[0xf1ae8962]
2023-07-30T22:30:52.4422022Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xe7edb0)[0xebcf2db0]
2023-07-30T22:30:52.4423308Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(_RNvXs5_Cslnhb1zSX8al_18rustc_codegen_llvmNtB5_18LlvmCodegenBackendNtNtNtCs4dQkNv2goAX_17rustc_codegen_ssa6traits7backend14CodegenBackend13codegen_crate+0x142)[0xebc617a2]
2023-07-30T22:30:52.4424441Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xcc620c)[0xebb3a20c]
2023-07-30T22:30:52.4425477Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(_RNvNtCsdrDhzvGIJZf_15rustc_interface6passes13start_codegen+0x1ff)[0xebb0822f]
2023-07-30T22:30:52.4426390Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xc2939d)[0xeba9d39d]
2023-07-30T22:30:52.4427405Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(_RNvMs3_NtCsdrDhzvGIJZf_15rustc_interface7queriesNtB5_7Queries15ongoing_codegen+0x36)[0xebb370e6]
2023-07-30T22:30:52.4428342Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xa5c7c5)[0xeb8d07c5]
2023-07-30T22:30:52.4429134Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xaa883f)[0xeb91c83f]
2023-07-30T22:30:52.4429910Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xa5d905)[0xeb8d1905]
2023-07-30T22:30:52.4430677Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xac3b73)[0xeb937b73]
2023-07-30T22:30:52.4431465Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/librustc_driver-1b82875e73fd4b5c.so(+0xa8150a)[0xeb8f550a]
2023-07-30T22:30:52.4432341Z /checkout/obj/build/i686-unknown-linux-gnu/stage2/lib/libstd-d01cc46190adb88c.so(rust_metadata_std_f3a72662ef94173d+0xb9dd4)[0xead53dd4]
2023-07-30T22:30:52.4432886Z /lib32/libc.so.6(+0x85ff1)[0xeaaeaff1]
2023-07-30T22:30:52.4433259Z /lib32/libc.so.6(+0x120fac)[0xeab85fac]
2023-07-30T22:30:52.4433727Z ------------------------------------------
```

**Comment by nikic** [comment]
The reproducer for the crash is `fn main() {}` and the start of the backtrace is:
```
#0  0xf2d4b127 in <rustc_middle::mir::Constant as rustc_type_ir::visit::TypeVisitable<rustc_middle::ty::context::TyCtxt>>::visit_with::<rustc_middle::ty::visit::HasTypeFlagsVisitor> ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#1  0xf2b4bda6 in <rustc_middle::mir::syntax::Operand as rustc_type_ir::visit::TypeVisitable<rustc_middle::ty::context::TyCtxt>>::visit_with::<rustc_middle::ty::visit::HasTypeFlagsVisitor> ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#2  0xf2b4b47d in <rustc_middle::mir::syntax::TerminatorKind as rustc_type_ir::visit::TypeVisitable<rustc_middle::ty::context::TyCtxt>>::visit_with::<rustc_middle::ty::visit::HasTypeFlagsVisitor> ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#3  0xf2d5afe3 in <rustc_index::vec::IndexVec<rustc_middle::mir::BasicBlock, rustc_middle::mir::BasicBlockData> as rustc_type_ir::visit::TypeVisitable<rustc_middle::ty::context::TyCtxt>>::visit_with::<rustc_middle::ty::visit::HasTypeFlagsVisitor> ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#4  0xf2d49fad in <rustc_middle::mir::Body as rustc_type_ir::visit::TypeVisitable<rustc_middle::ty::context::TyCtxt>>::visit_with::<rustc_middle::ty::visit::HasTypeFlagsVisitor> ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#5  0xf2d41228 in <rustc_middle::mir::Body as rustc_middle::ty::visit::TypeVisitableExt>::has_type_flags ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#6  0xf2d3b01f in <rustc_middle::mir::Body>::new ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#7  0xf07b3628 in rustc_mir_transform::shim::new_body ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#8  0xf07b0f70 in _RNvNtCs4yIT6Gp0rL5_19rustc_mir_transform4shim9make_shim.llvm.14309728324964977118 ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#9  0xf17ac2b4 in rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_shims::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 4]>> ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#10 0xf193a61f in _RNvYNCNvNtNtCs2RrUaSKU2fb_16rustc_query_impl10query_impl9mir_shims13dynamic_querys0_0INtNtNtCs3K69LdXWBxX_4core3ops8function6FnOnceTNtNtNtCsh02QPfW2FXe_12rustc_middle2ty7context6TyCtxtNtNtB2a_8instance11InstanceDefEE9call_onceBa_.llvm.11675517649559473739 ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#11 0xf1b017ca in rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::instance::InstanceDef, rustc_middle::query::erase::Erased<[u8; 4]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false> ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#12 0xf194185f in rustc_query_impl::query_impl::mir_shims::get_query_non_incr::__rust_end_short_backtrace ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#13 0xf2c3be53 in <rustc_middle::ty::context::TyCtxt>::instance_mir ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#14 0xf06fb86a in rustc_monomorphize::collector::collect_used_items ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#15 0xf06f82fc in rustc_monomorphize::collector::collect_items_rec ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
#16 0xf06f8809 in rustc_monomorphize::collector::collect_items_rec ()
   from /checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/../lib/librustc_driver-1b82875e73fd4b5c.so
```

**Comment by nikic** [comment]
From a local test the i686 miscompile should be fixed by https://github.com/llvm/llvm-project/issues/64355.

**Comment by nikic** [comment]
Merged the current 17.x branch, which should resolve the i686 issue.

@bors r=cuviper

**Comment by nikic** [comment]
#114510 introduced a new version check against LLVM 17, but it's actually for LLVM 18.

@bors r=cuviper

**Comment by klensy** [comment]
`<html>
<body>


libLLVM.so ? | Library | 113.14 MiB | 163.72 MiB | 50.57 MiB | 44.696%
-- | -- | -- | -- | -- | --



</body>
</html>`

This lost previous size optimization?

**Comment by Kobzol** [comment]
It seems unfortunate, yeah. I'm not sure yet if it somehow undoes the recent BOLT optimization (we use the same BOLT version as before, for now), or if it's a genuine regression, I'll try to investigate.

**Comment by Kobzol** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/114297.

**Pull request merged**
