### PR TITLE
Compile LLVM with Clang on release builders

### PR DESCRIPTION
**Pull request by alexcrichton**
Attempting to cache in on some rustc compile time wins mentioned in https://github.com/rust-lang/rust/issues/49879#issuecomment-383602941

### CODE REVIEW

**Comment by alexcrichton** [comment]
Gonna run this through perf to see if we can verify the build improvements. Unfortunately I wasn't seeing much of an improvement locally, so I'm hoping that a more controlled environment like perf.r-l.o can show some better numbers perhaps.

**Comment by matthiaskrgr** [comment]
````
[01:41:01]    Compiling serde_derive_internals v0.23.1
[01:41:03]    Compiling serde_derive v1.0.40
[01:41:10] error: linker `cc` not found
[01:41:10]   |
[01:41:10]   = note: No such file or directory (os error 2)
[01:41:10] 
[01:41:10] error: aborting due to previous error
[01:41:10] 
[01:41:10] error: Could not compile `serde_derive`.
[01:41:10] 
[01:41:10] To learn more, run the command again with --verbose.
[01:41:10] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[01:41:10] Build completed unsuccessfully in 0:01:10
[01:41:10] make: *** [prepare] Error 1
[01:41:10] Command failed. Attempt 2/5:
[01:41:11]    Compiling serde_derive v1.0.40
[01:41:18] error: linker `cc` not found
[01:41:18]   |
[01:41:18]   = note: No such file or directory (os error 2)
[01:41:18] 
[01:41:18] error: aborting due to previous error
[01:41:18]
````

**Comment by alexcrichton** [comment]
perf run queued up

**Comment by ishitatsuyuki** [comment]
https://perf.rust-lang.org/compare.html?start=25749ad66de71ffb46e6b04fb0cccf1ae4fc5ed5&end=303d989cdce60b2a5981765d43726baf868cbe95&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
Those numbers are very green `:)`

I'm wondering though: Why are the `cargo check` results so much better? I wouldn't have expected C++ to have much effect on those.

**Comment by Mark-Simulacrum** [comment]
This did make our released binaries ~78 MB smaller; that might be a potential cause: we're at 448 MB, whereas master is at 526 MB.

**Comment by alexcrichton** [comment]
Most of the biggest wins are unfortunately fractions of a section (0.09s to 0.06s), and bigger projects like Servo's style crate are ~7% faster overall. @michaelwoerister this doesn't quite match what you saw in https://github.com/rust-lang/rust/issues/49879#issuecomment-384642779 but it sounds like we should probably land this regardless?

**Comment by michaelwoerister** [comment]
7% is a nice win! I'm in favor of landing it.

**Comment by alexcrichton** [comment]
Ok I'm going to take some time to get this working for OSX/Windows as well, and hopefully start also including the other distribution platforms.

**Comment by alexcrichton** [comment]
Ok I think let's stick with "tier 1" platforms for now and we can start covering other platforms later if need be.

r? @kennytm 

I'm semi-confident this is mostly ok. AKA this'll probably bounce on bors a few times, but would be good to get a second pair of eyes now.

**Comment by mati865** [comment]
> I don't think
> clang has an output mode compatible with MinGW that we need. If it does we
> should switch to clang for MinGW as well!

It does but there are numerous issues. Using some flags, like `-static` makes it even worse.

**Comment by kennytm** [comment]
Failed to build `stage2-cargo` (`curl-sys v0.4.3`) on `dist-x86_64-msvc`?

<details>

```
error: failed to run custom build command for `curl-sys v0.4.3`
process didn't exit successfully: `C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\release\build\curl-sys-b73519f46393e897\build-script-build` (exit code: 101)
--- stdout
first run of vcpkg did not find libcurl: Could not find library in Vcpkg tree C:\Tools\vcpkg\installed\x64-windows-static\lib\libcurl_imp.lib
second run of vcpkg did not find libcurl: Could not find library in Vcpkg tree C:\Tools\vcpkg\installed\x64-windows-static\lib\libcurl.lib
cargo:rustc-link-search=native=C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\build\curl-sys-663da4b9e1c8069d\out/lib
cargo:rustc-link-lib=static=curl
cargo:root=C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\build\curl-sys-663da4b9e1c8069d\out
cargo:include=C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\build\curl-sys-663da4b9e1c8069d\out/include
cargo:rustc-link-lib=ws2_32
cargo:rustc-link-lib=crypt32
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\nmake.exe" "/f" "Makefile.vc" "MODE=static" "ENABLE_IDN=yes" "DEBUG=no" "GEN_PDB=no" "ENABLE_WINSSL=yes" "ENABLE_SSPI=yes" "MACHINE=x64" "RTLIBCFG=static" "WITH_ZLIB=static" "WITH_DEVEL=C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\build\\libz-sys-54593970fe3e0acd\\out"
configuration name: libcurl-vc-x64-release-static-zlib-static-ipv6-sspi-winssl
Generating prerequisite files
* C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\build\curl-sys-663da4b9e1c8069d\out\build\Makefile
* C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\build\curl-sys-663da4b9e1c8069d\out\build\src\tool_hugehelp.c
Error: Unable to generate src\tool_hugehelp.c
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.
couldn't read the README infile docs\MANUAL at src\mkhelp.pl line 92.
couldn't read the README infile docs\MANUAL at src\mkhelp.pl line 92.
NMAKE : fatal error U1077: 'IF' : return code '0x1'
Stop.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2
build script failed, must exit now', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.4.3\build.rs:224:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
warning: build failed, waiting for other jobs to finish...
[RUSTC-TIMING] regex test:false 15.229
error: build failed
```

</details>

**Comment by alexcrichton** [comment]
Urgh forgot to upgrade curl-sys after the lockfile conflict

@bors: r=kennytm

**Comment by alexcrichton** [comment]
@bors: r=kennytm

OK, no clang-cl for curl

**Comment by kennytm** [comment]
rustc has heap corruption (error code 3221226356 = 0xc0000374) when running the LTO tests on [`x86_64-msvc`](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.7249/job/xiwsd3i8sr8chbtc)

<details>

```
failures:
---- [run-pass] run-pass\debuginfo-lto.rs stdout ----
	
error: compilation failed!
status: exit code: 3221226356
command: PATH="C:\projects\rust\build\x86_64-pc-windows-msvc\stage2\bin;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64;C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-tools\x86_64-pc-windows-msvc\release\deps;C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-sysroot\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Program Files (x86)\Inno Setup 5;C:\Python27;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial;C:\Program Files\LLVM\bin;C:\Program Files\dotnet;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Tools\vcpkg;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files\PowerShell\6.0.0;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\ProgramData\chocolatey\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Program Files\AppVeyor\BuildAgent;C:\projects\rust;C:\projects\rust\handle" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2\\bin\\rustc.exe" "C:\\projects\\rust\\src/test\\run-pass\\debuginfo-lto.rs" "-L" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass" "--target=x86_64-pc-windows-msvc" "-o" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\debuginfo-lto.stage2-x86_64-pc-windows-msvc.exe" "-Crpath" "-O" "-Zunstable-options" "-Lnative=C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\native\\rust-test-helpers" "-C" "lto" "-g" "-L" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-pass\\debuginfo-lto.stage2-x86_64-pc-windows-msvc.aux"
stdout:
------------------------------------------
------------------------------------------
stderr:
------------------------------------------
------------------------------------------

...

failures:
    [run-pass] run-pass\debuginfo-lto.rs
    [run-pass] run-pass\fat-lto.rs
    [run-pass] run-pass\lto-many-codegen-units.rs
    [run-pass] run-pass\lto-still-runs-thread-dtors.rs
    [run-pass] run-pass\panic-runtime\lto-abort.rs
    [run-pass] run-pass\panic-runtime\lto-unwind.rs
    [run-pass] run-pass\sepcomp-lib-lto.rs
    [run-pass] run-pass\stack-probes-lto.rs
test result: FAILED. 2945 passed; 8 failed; 23 ignored; 0 measured; 0 filtered out
```

</details>

**Comment by alexcrichton** [comment]
Y'know it'd probably be helpful if this PR actually did what it says it does on MSVC. It's been using `cl.exe` this whole time due to how sccache is implemented on MSVC...

**Comment by kennytm** [comment]
Could not build LLD for the Emscripten backend on `dist-x86_64-msvc` due to forward slash vs backward slash.

<details>

```
Building LLD for x86_64-pc-windows-msvc
running: "cmake" "C:\\projects\\rust\\src/tools/lld" "-G" "Ninja" "-DCMAKE_C_COMPILER=C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe" "-DCMAKE_CXX_COMPILER=C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe" "-DCMAKE_C_FLAGS=/nologo /MT -m64" "-DCMAKE_CXX_FLAGS=/nologo /MT -m64" "-DLLVM_CONFIG_PATH=C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\llvm\\build\\bin\\llvm-config.exe" "-DLLVM_INCLUDE_TESTS=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\lld" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe
-- Check for working C compiler: C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe
-- Check for working CXX compiler: C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Release VC++ CRT: MD
-- Performing Test SUPPORTS_BREPRO
CMake Error at C:/projects/rust/build/x86_64-pc-windows-msvc/lld/build/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (set):
  Syntax error in cmake code at
    C:/projects/rust/build/x86_64-pc-windows-msvc/lld/build/CMakeFiles/CMakeTmp/CMakeLists.txt:2
  when parsing string
    C:\projects\rust\build\x86_64-pc-windows-msvc\llvm\build\lib\cmake\llvm
  Invalid character escape '\p'.
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CheckCXXSourceCompiles.cmake:99 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CheckCXXCompilerFlag.cmake:50 (CHECK_CXX_SOURCE_COMPILES)
  C:/projects/rust/build/x86_64-pc-windows-msvc/llvm/build/lib/cmake/llvm/HandleLLVMOptions.cmake:383 (check_cxx_compiler_flag)
  CMakeLists.txt:56 (include)
-- Configuring incomplete, errors occurred!
See also "C:/projects/rust/build/x86_64-pc-windows-msvc/lld/build/CMakeFiles/CMakeOutput.log".
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1
build script failed, must exit now', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.30\src\lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
	finished in 8.075
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap dist
Build completed unsuccessfully in 0:56:45
Command exited with code 1
```

</details>

**Comment by alexcrichton** [comment]
Ok this is when we start to see prime examples of just how hilariously non-portable everything is. 

Sequence of steps causing this bug:

* When building LLD out-of-tree it executes `llvm-config --cmakedir` to find CMake utilities
* LLVM's `llvm-config` will forcibly replace `/` with `\` in the output paths
* Today, with `cl.exe`, this `cmakedir` is *never used*
* With `clang-cl.exe`, however, it [executes a check](https://github.com/llvm-mirror/llvm/blob/a244d9e3deb5e2043c9c1bcba62955dc75a1bd9d/cmake/modules/HandleLLVMOptions.cmake#L386-L413) that is clang-cl specific.
* As part of this check it executes `check_cxx_compiler_flag`
* This, internally emits something like `define(FOO, "a\b")`. The `a\b` comes from `--cmakedir` and isn't valid CMake because... well... backslashes.

It *just so happens* that using `cl.exe` doesn't execute any `check_cxx_compiler_flag` invocations so we get lucky and we don't hit this bug.

**Comment by kennytm** [comment]
[`i686-msvc-1`](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.7313/job/34lqla1091kcu4ff), can't compile LLVM because the target is somehow chosen as 64-bit, even both host and target should be 32-bit.

<details>

```
-- Check for working C compiler: C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler
    "C:/projects/rust/build/bootstrap/debug/sccache-plus-cl.exe"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: C:/projects/rust/build/i686-pc-windows-msvc/llvm/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"C:/projects/rust/ninja.exe" "cmTC_e85a1"
    [1/2] Building C object CMakeFiles\cmTC_e85a1.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_e85a1.exe
    FAILED: cmTC_e85a1.exe 
    cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_e85a1.dir --manifests  -- C:\PROGRA~2\MI0E91~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_e85a1.dir\testCCompiler.c.obj  /out:cmTC_e85a1.exe /implib:cmTC_e85a1.lib /pdb:cmTC_e85a1.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MI0E91~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_e85a1.dir\testCCompiler.c.obj /out:cmTC_e85a1.exe /implib:cmTC_e85a1.lib /pdb:cmTC_e85a1.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_e85a1.dir/intermediate.manifest CMakeFiles\cmTC_e85a1.dir/manifest.res" failed (exit code 1120) with the following output:
    LINK : error LNK2001: unresolved external symbol mainCRTStartup
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\kernel32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\user32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\gdi32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\winspool.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\shell32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\ole32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\oleaut32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\comdlg32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86\advapi32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\msvcrtd.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
    cmTC_e85a1.exe : fatal error LNK1120: 1 unresolved externals
    ninja: build stopped: subcommand failed.
   
``` 

</details>

**Comment by alexcrichton** [comment]
@bors: r=kennytm

The effort necessary for getting clang-cl to compile LLVM on MSVC is getting pretty absurd at this point, **nothing works by default** which means we're basically wrapping wrappers constantly...

**Comment by alexcrichton** [comment]
@bors: retry

Looks like a spurious network error...

**Comment by kennytm** [comment]
@bors retry p=29

3 hour timeout

**Comment by alexcrichton** [comment]
@bors: retry

> No output has been received in the last 30m0s

**Comment by kennytm** [comment]
Same error, maybe legit?

**Comment by alexcrichton** [comment]
Indeed yeah, it's a legit issue.

I can reproduce the hang locally, and hilariously enough the hang here is in a **build script for miniz-sys**. Turns out the build script just... never exits. It's not an sccache issue and it's not a the-build-script-executed-clang issue. Presumably it's a build-script-was-linked-by-clang issue, but that seems crazy.

Looking at `strace` one of the threads looks like it segfaults but doesn't take down the whole process. I'm extremely confused. Trying to narrow down what's happening.

**Comment by alexcrichton** [comment]
So we're not only compiling LLVM with clang but we're also compiling things like jemalloc with clang. The segfault was somewhere deep within jemalloc on an instruction which was moving from memory which I believe required at least 8 byte alignment (maybe 16?) and didn't have that alignment. That's what caused the segfault itself, and as to why the build script wasn't taken down I'm gonna chalk that up to "probably some glibc bug fixed in the last decade". 

Presumably clang is just making different assumptions about stack alignment than gcc is? Not entirely sure. In the meantime I'm now testing passing `-mstackrealign` which will tell clang to have each function realign the stack. Not exactly speedy but hey it's 32-bit linux anyway. If you want speed you're cross-compiling from 64-bit linux.

**Comment by alexcrichton** [comment]
@bors: r=kennytm

Seems to have fixed the issue

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout.

| Step | Duration |
|:-----|---------:|
| stage1-rustc | 37min |
| stage0-rustc | 24min |
| run-pass | 14min |
| run-pass-fulldeps | 9min |
| plain source tarball | 8min |
| test/core | 6min |
| llvm | 6min |
| another llvm 🤔 | 5min |
| test/std | 5min |
| stage0-rustbook | 5min |

**Comment by alexcrichton** [comment]
omg it worked!

**Comment by michaelwoerister** [comment]
The results for small crates are pretty spectacular and for larger crates they are rather good too:
http://perf.rust-lang.org/compare.html?start=95d0b9e96795aea20ac4a1fad9251982714d3c55&end=0a223d139cd26e5bfab23a478a5cad845eaab131&stat=wall-time

Thanks for all the work all of you have put into this PR!

**Comment by scottmcm** [comment]
Wow! That's an impressive amount of green!

**Pull request merged**
