### PR TITLE
[Experiment] Export generic instances from libstd.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This should resolve issue #64140. However it is unclear if there are detrimental effects. Let's test if there are performance improvements to be had.

r? @ghost

### CODE REVIEW

**Comment by bjorn3** [comment]
This seems to negatively affect at least linker performance.

**Comment by panstromek** [comment]
Without actually understanding anything - it's interesting that all regressed benchmarks are artificial little programs and stress tests, while the ones that improved are more "real" programs, like `cargo`, `style-servo`, `ripgrep` or `inflate`. Even though the page is full of red numbers, it's bit misleading because they all come from 50 LOC programs. Is that enough to even derive some conclusion?

**Comment by bjorn3** [comment]
ripgrep-opt clean incremental regresses by 1.9% (linker and some other things). cranelift-codegen-opt baseline incremental regresses by 1.2% (mostly LLVM). Both are "real" programs/libraries.

**Comment by michaelwoerister** [comment]
Yes, it looks like this change causes quite a bit of overhead for loading the list of generic symbols available in the standard library. Small programs that then do not use any of these newly available symbols don't get a chance for amortizing that overhead. 

> ripgrep-opt clean incremental regresses by 1.9% (linker and  some other things). cranelift-codegen-opt baseline incremental  regresses by 1.2% (mostly LLVM). Both are "real" programs/libraries.

I wouldn't rely too much on wall-time numbers when it comes to changes below 3%. They are rather noisy. 

I'm not quite sure how to proceed here. Those performance numbers clearly aren't a mandate to merge this `:)`

**Comment by bjorn3** [comment]
I was looking at the instructions count.

**Pull request closed without merging**
