### PR TITLE
Less allocations in rustdoc

### PR DESCRIPTION
**Pull request by rylev**
This change removes many temporary allocations when rendering items in rustdoc. Unfortunately this doesn't seem to have a big impact on speed performance when I test locally (rendering items remains at a comparable percentage of total time). This should help memory utilization a bit, but I've not been able to confirm this yet.

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
@rylev do you need help debugging the test failure? Do you think it's worth doing a perf run before it's fixed? I don't plan to review this in detail before a perf run because the diff is pretty big and this is not super useful without the memory decrease.

**Comment by GuillaumeGomez** [comment]
I'm really anti-`unwrap`, could you at least replace them with `expect` calls please (even if `write!` on `String` is **very** unlikely to ever fail)?

**Comment by jyn514** [comment]
Oh wow, this actually *increased* instruction counts and max-rss :confused:

**Comment by GuillaumeGomez** [comment]
That's quite a surprising result. O.o

I guess `write!` internals are doing much more than what we are currently doing...

**Comment by jyn514** [comment]
@rylev I don't really want to merge this as is ... I feel like there's a performance improvement hiding here somewhere, though. Maybe you could return a `Result` from `fn render` and only unwrap once where that's called, and hopefully that will have less code bloat? I'm not really sure what's taking more time in the first place though :/

**Comment by GuillaumeGomez** [comment]
To be honest, I don't think the performance bottleneck is here...

**Comment by rylev** [comment]
@GuillaumeGomez I agree - though my investigations into rendering show that there isn't really a single performance bottleneck. I'm very surprised this ends up slowing things down. We can certainly close this, but I would like to figure out why this made things slower.

**Comment by rylev** [comment]
hmmm there might be something wrong with perf.rlo. I get an error when trying to access the perf run results:
> error decoding response body: expected value at line 1 column 1

**Comment by GuillaumeGomez** [comment]
@rylev I'm curious as well (and I think @jyn514 is too), so please go ahead so we can understand better!

**Comment by jyn514** [comment]
> hmmm there might be something wrong with perf.rlo. I get an error when trying to access the perf run results:
> 
> > error decoding response body: expected value at line 1 column 1

Maybe perf was down briefly? It works for me now.

**Comment by rylev** [comment]
It's interesting to see the [code gen difference](https://godbolt.org/z/Mv6MdM) between using `format!` and `write!`. Because `format!` ultimately just goes through `core::fmt::format`, it does not need to generate nearly as much code. `write!` on the other hand is essentially like copy/pasting the internals of `core::fmt::format` (minus the allocation piece) where `write!` is used. This means that using `write!` a lot will probably mean a lot more code is generated, though (all things else being equal) it shouldn't be slower as `core::fmt::format` is doing the same thing as `write!` plus allocating memory. I imagine what we're seeing in the perf results is that more code is being generated which is only very marginally faster meaning we end up with more instructions but no real improvement in the performance of the code.

**Comment by jyn514** [comment]
> write! on the other hand is essentially like copy/pasting the internals of core::fmt::format (minus the allocation piece) where write! is used.

Could we change `write` to call a function instead? That seems like it could have performance benefits for other projects too.

**Comment by rylev** [comment]
@jyn514 `write!` does expand to a function call. For example, `write!(&mut string_buffer, "{}", 1)` expands to:
```rust 
(&mut string_buffer).write_fmt(/* More desuggaring from fmt_args! which is a compiler built in*/)
```
This seems to get inlined though into a call to `core::fmt::write`. I think the issue is that we took one very large `format!` call and broke it up into many calls to `write!`.

**Comment by jyn514** [comment]
It sounds like this specific change isn't going to help much with perf, so I'm going to close this.

**Pull request closed without merging**
