### PR TITLE
doc: Mention split_whitespace in split doc

### PR DESCRIPTION
**Pull request by JIghtuse**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 3120bfe1088346bce1512300b343782d02c9ea9a

Thanks!

**Comment by steveklabnik** [comment]
@JIghtuse would you mind writing a link to link this method to the definition, so users don't have to search for it?

    ///
    /// Use [`.split_whitespace()`][split_whitespace] for this behavior.
    ///
    /// [split_whitespace]: #method.split_whitespace

would follow the idiom.

Thanks! r=me after, @alexcrichton or anyone else

**Comment by JIghtuse** [comment]
@steveklabnik sure. I just didn't know how to do that.

**Comment by steveklabnik** [comment]
No worries! Thanks so much. :+1:

**Pull request merged**
