### PR TITLE
std: impl From<String> for Box<Error + Send>

### PR DESCRIPTION
**Pull request by Ryman**

### CODE REVIEW

**Comment by reem** [comment]
I've wanted this too, but if we're going to do this we should probably just take the clearer step conceptually of just implementing `Error` for `String`.

**Comment by alexcrichton** [comment]
@reem hm I'm a little confused, this intentionally does *not* implement `Error` for `&str` or `String`, just `From` into a `Box<Error+Send>`. Could you elaborate on what you're thinking a bit?

**Comment by reem** [comment]
@alexcrichton this feels like a weird half-step to me and has some drawbacks. For instance, this doesn't expose the exact underlying type of the error and can't be used with traits that inherit from Error, e.g. [rust-error](https://github.com/reem/rust-error).

**Comment by reem** [comment]
I'm saying that I think that implementing Error for String would be fine, and have more use cases than just this implementation.

**Comment by alexcrichton** [comment]
I personally feel that `Error for String` is too ambitious and would rather have a clear opt-in type for a "string-like error". I like these impls as-is as you have to explicitly ask for a string to be interpreted as an error. I also think that not exposing the underlying type is a *good* thing as it's one less thing to stabilize for now and it's possible to add it later if necessary.

**Comment by aturon** [comment]
Hm, I'm torn on the question of making `String` implement `Error`. My instinct, like @alexcrichton, is that `Error` is a meaningful designation that should only be applied to types that are specifically intended to represent errors, and that `Into<Box<Error>>` is a nice way of saying "can be interpreted as an error". But I'm struggling to say why, exactly, this seems important.

FWIW, taking the step here does not preclude us from making `String: Error` in the future, so I think regardless we should follow this conservative approach for now, and see how the idioms evolve over time before taking the next step.

**Comment by alexcrichton** [comment]
I agree with @aturon in that it should be backwards-compatible to add the `impl` (thanks to new coherence changes!), so it should be ok to take this step for now.

@bors: r+ 8b719eefc0a772986dc33d6d9193c2cfd04b82f7

**Comment by kballard** [comment]
I agree with @alexcrichton and @aturon as well, that a separate distinct type is appropriate and that we probably don't want to make `String: Error`.

**Pull request merged**
