### PR TITLE
trpl/traits: Make error message consistent with source code snippet

### PR DESCRIPTION
**Pull request by peferron**
The source code snippet uses `"whatever".as_bytes()` but the compilation error message uses `b"whatever"`. Both should be consistent with each other.

r? @steveklabnik

### CODE REVIEW

**Comment by alexcrichton** [comment]
In this case I think it's actually somewhat more idiomatic to use the `b"..."` syntax, perhaps the code snippet could be updated instead to use that?

**Comment by peferron** [comment]
As a Rust beginner who started two days ago, I'll take your word for `b"..."` being more idiomatic, but it would likely need a short explanation. `"...".as_bytes()` is self-explanatory and already introduced in the preceding [Strings](https://github.com/rust-lang/rust/blob/master/src/doc/trpl/strings.md) section, but `b"..."` would have sent me googling to confirm that it's indeed shorthand for `"...".as_bytes()`.

If `b"..."` is better then please confirm and I'll update the PR and add a short explanation.

**Comment by alexcrichton** [comment]
Ah yeah I think it'd be fine to add a few words saying that `b".."` is a byte-string and distinct from `&str`

**Comment by peferron** [comment]
@alexcrichton How about now?

**Comment by alexcrichton** [comment]
@bors: r+ a10d243dd46e84813819cca140a72ad9fcff951d rollup

Thanks!

**Comment by steveklabnik** [comment]
Thank you!

**Pull request merged**
