### PR TITLE
HirIdify hir::ItemId

### PR DESCRIPTION
**Pull request by Zoxc**
Version of https://github.com/rust-lang/rust/pull/59092.

r? @oli-obk

### CODE REVIEW

**Comment by ljedrz** [comment]
Oh, sweet - you were able to crack it :+1:.

**Comment by Zoxc** [comment]
@ljedrz Let's see if the tests pass before celebrating =P

**Comment by Zoxc** [comment]
I see impl Trait and async stuff also create items, so I guess I have to allocate the HIR counters for those too.

**Comment by Zoxc** [comment]
I changed the code to allocate the HIR id counters on demand. That seem to suffice for impl Trait, since it doesn't also create new `Def`s.

**Pull request merged**
