### PR TITLE
Gate if-let guard feature

### LINKED ISSUE #74232: if-let arm point to let_chains issue
I tried this code:

```rust
pub fn foo(a: &[u8], b: bool) -> bool {
    match b {
        true if let [1, 2, 3, ..] = a => true,
        _ => false,
    }
}
```

*I expected to see this happen:*
The compilation fails and error points out that if-let guard is not implemented
and being tracked at #51114

*Instead, this happened:*
The error points to `let_chains` feature, which is wrong and adding that feature gate
doesn't make the code compile.
```rust
error[E0658]: `let` expressions in this position are experimental
 --> <source>:3:17
  |
3 |         true if let [1, 2, 3, ..] = a => true,
  |                 ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
  = help: add `#![feature(let_chains)]` to the crate attributes to enable
```

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (8aa18cbdc 2020-07-08)
binary: rustc
commit-hash: 8aa18cbdc5d4bc33bd61e2d9a4b643d87f5d21de
commit-date: 2020-07-08
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
Compiler returned: 0
```

### PR DESCRIPTION
**Pull request by tesuji**
Enhanced on #74315. That PR is in crater queue so I don't want to push to it.

Close  #74232
cc #51114

### CODE REVIEW

**Comment by lzutao** [comment]
Will resolve your concern in https://github.com/rust-lang/rust/pull/74315#discussion_r455929541.

**Comment by estebank** [comment]
```
tidy error: Found 1 features without a gate test.
Expected a gate test for the feature 'if_let_guard'.
Hint: create a failing test file named 'feature-gate-if_let_guard.rs'
      in the 'ui' test suite, with its failures due to
      missing usage of `#![feature(if_let_guard)]`.
Hint: If you already have such a test and don't want to rename it,
      you can also add a // gate-test-if_let_guard line to the test file.
```

**Comment by estebank** [comment]
LGTM, letting @eddyb have final r+.

**Comment by lzutao** [comment]
Crater result in #74315 : https://github.com/rust-lang/rust/pull/74315#issuecomment-663560953

There are real repressions here.

This snippet now fails to compile when previous accepted:
```rust
#[derive(PartialEq)]
struct Foo {
    a: i32,
    b: f32,
}

let f = Foo { a: 42, b: 0.0 };
match () {
    () if f == Foo { a: 0, b: 0.0 } => {}
    //~^ ERROR: struct literals are not allowed here
    _ => {}
}
```

But note that the `if` expression has the same restrictions without this PR:

```rust
if f == Foo { a: 0, b: 0.0 } {
//~^ ERROR: struct literals are not allowed here
}
```

```rust
error: struct literals are not allowed here
  --> src/lib.rs:14:13
   |
14 |     if f == Foo { a: 0, b: 0.0 } {
   |             ^^^^^^^^^^^^^^^^^^^^
   |
help: surround the struct literal with parentheses
   |
14 |     if f == (Foo { a: 0, b: 0.0 }) {
   |             ^                    ^

error: aborting due to previous error
```

I guess we have to accept this fate and fallback to previous `parse_expr`.

**Comment by lzutao** [comment]
Updated.

**Comment by estebank** [comment]
> I guess we have to accept this fate and fallback to previous `parse_expr`.

Shame. We could maybe change that in 2021?

**Comment by lzutao** [comment]
There are 12 regressed crates out of 113052 crates tested.

Spurious:
* 2 is linker error:
  - artichoke/artichoke/1bd7af559015500752ae84f90df715cfbb8f6a09
  - tracing-attributes-0.1.9

* Network error:
  - corysabol.HyperFlo.cb68cc080eacf87a0f0737ece7c195dae1dd98ce
  - divy-work.deno-notify.f82302fc180ea17665d6b47b8de6666bab0aeb0b

Real regressions:
* librsvg: https://github.com/GNOME/librsvg/blob/85552f0ad25247f76a2f220b70078634c3d74dcf/rsvg_internals/src/xml.rs#L400-L407
  - oberien.pundoc.92313227dda7813cd9dc52cc86638793f83a56af
  - antoyo.buzzle.f3c98f8e00c9cf62ac6930e280dd498c7edcc8d0
  - antoyo.bview.6bedeeb50460e94ef5ebcef93a105c682984a956
* SuperTails.langcraft.36f631f8f0fc5686719a797de7003fead02971fd: already fixed upstream ?
* iameva.boardbots-rust.086843d02661324e3a7143b71bc0a0ba0160de4d: easy to fix
* museun.rcc.8d53bc74192718a2c9dddf1ad8648da5eb7f5a91: easy to fix
* async-tftp-0.2.0: easy to fix
* finchers-0.13.5: repository archived; easy to fix

---

There are breakages when disallowing struct literals in `match` guard.
The breakages is small and easy to fix
(I will fix them upstream if we agree on this move).
But disallowing struct literals on `match` guard
match restrictions on `if` condition and makes error reporting/parsing easier.

**Comment by lzutao** [comment]
This is [Underspecified language semantics](https://github.com/rust-lang/rfcs/blob/master/text/1122-language-semver.md#underspecified-language-semantics).

On [reference](https://doc.rust-lang.org/nightly/reference/expressions/match-expr.html#match-expressions), match arm guard is `if` expression, but `if` expr [doesn't allow](https://doc.rust-lang.org/nightly/reference/expressions/if-expr.html#if-expressions) struct expression.

Can I nominate this issue for T-lang or T-compiler?

**Comment by alercah** [comment]
The reason unwrapped `struct` expressions aren't allowed in `if` is due to ambiguity of `{`. There's no such ambiguity in a guard.

**Comment by lzutao** [comment]
> The reason unwrapped `struct` expressions aren't allowed in `if` is due to ambiguity of `{`. There's no such ambiguity in a guard.

Yes, I agree there are no ambiguity in the correct code. 
But with the incorrect code, parser has to recover and point out erroring span.
Take a look at this file to see the diagnostic: https://github.com/rust-lang/rust/blob/master/src/test/ui/parser/issue-15980.rs

**Comment by jyn514** [comment]
This doesn't seem like something that should be changed in a PR - this is a breaking change to the language itself. Can we try to improve the diagnostic instead?

**Comment by lzutao** [comment]
I don't change that in this PR. I will open a new issue for discussing it.

**Comment by lzutao** [comment]
Can we merge this PR, @eddyb ? This PR in current state doesn't break old code.

**Comment by jyn514** [comment]
You may want to find a different reviewer, I know that eddyb is very behind on github notifications 😅

**Comment by lzutao** [comment]
Thanks. I don't know what appropriate reviewers. I would wait a few days before finding another one.

**Comment by eddyb** [comment]
This seems to be a parsing change, so:
r? @petrochenkov

**Pull request merged**
