### PR TITLE
Add sparc64-unknown-netbsd target

### PR DESCRIPTION
**Pull request by jakllsch**

### CODE REVIEW

**Comment by japaric** [comment]
LGTM. (Except for the cabi stuff; I can't really review that. But if it looks like the cabi of other 64-bit target, it should be OK-ish)

Can you (cross) compile `std` with this PR? No libc changes were required? (That seems odd)

**Comment by jakllsch** [comment]
@japaric:

The cabi_sparc64 stuff was copy and pasted from cabi_powerpc64, and then modified to always assume big endian.

The rust-libc stuff for sparc64-unknown-netbsd was merged three weeks ago: https://github.com/rust-lang/libc/pull/467.

**Comment by japaric** [comment]
> The rust-libc stuff for sparc64-unknown-netbsd was merged three weeks ago: rust-lang/libc#467.

Great! I hope that the libc changes for sparc64-linux will be as simple as that (likely not).

Can `std` for this target be cross compiled from Linux? Or only from x86_64 netbsd?

**Comment by jakllsch** [comment]
@japaric: I believe I've compiled `std` for sparc64-unknown-netbsd before from x86_64-unknown-linux-gnu.  I'm checking again though.  It appears I've got a few more patches that may be required for it to all work.  Also required would be a NetBSD cross toolchain and some wrapper scripts for the three cross tools.  I need to document my setup... The basic procedure is to use NetBSD's build.sh to cross-build a `distrubtion`, and then wrap the `gcc`, and `g++` tools adding the `--sysroot=` argument to point the compilers at the `destdir` for the platform.  These two wrappers, as well as a no-argument-adjustment wrapper for `ar` should be given the names expected by the gcc-rs crate and placed in the `$PATH`.

**Comment by sanxiyn** [comment]
Merged in #38726.

**Comment by alexcrichton** [comment]
@sanxiyn this PR was not approved before it was merged, did you intend to merge this?

**Comment by sanxiyn** [comment]
Yes.

**Comment by brson** [comment]
@sanxiyn it's a bit confusing what happened here since you pushed to someone else's branch. In the future can you leave a comment explaining what you are doing, and r+ prs before merging them?

**Comment by Mark-Simulacrum** [comment]
As I understand it, this PR was used by @japaric as a base for #38726, which means that its contents were merged with the approval of that PR.

**Pull request closed without merging**
