### PR TITLE
rand use getrandom for freebsd (available since 12.x)

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It seems like this should wait for https://github.com/rust-lang/rust/issues/89058 to go through?

**Comment by devnexen** [comment]
indeed .. expecting all goes to plan🙂

**Comment by Mark-Simulacrum** [comment]
Okay, I'll mark as blocked for now. In general I'm not sure keeping this open ~indefinitely is helpful, at minimum please signal that it is in fact blocked when opening such PRs.

**Comment by workingjubilee** [comment]
That FCP completed and was accepted, buuut PR now needs rebase.

@rustbot author

**Comment by workingjubilee** [comment]
ope!
looks good!
@bors r+

**Comment by ehuss** [comment]
@bors r-

queue synchronize

**Comment by ehuss** [comment]
@bors r=workingjubilee

Re-adding to the queue, the previous error was due to a flaky test (#117097).

**Comment by workingjubilee** [comment]
Thanks for finding the flaky test!

**Comment by tgross35** [comment]
Shouldn't this still be blocked on https://github.com/rust-lang/rust/issues/89058?

**Pull request merged**
