### PR TITLE
compiletest: force GDB to print values in the Rust format.

### LINKED ISSUE #40557: Some debuginfo-gdb tests failing
On Linux, Ubuntu 16.10, GDB v7.11.90. The following tests fail:

```
    [debuginfo-gdb] debuginfo-gdb/limited-debuginfo.rs
    [debuginfo-gdb] debuginfo-gdb/simple-struct.rs
    [debuginfo-gdb] debuginfo-gdb/simple-tuple.rs
```

Seems to be an issue with output formatting/pretty printing, e.g.,

```
error: line not found in debugger output: $1 = simple_struct::NoPadding16 {x: 1000, y: -1001}
[...]
Breakpoint 1 at 0x92e: file /home/ncameron/rust1/src/test/debuginfo/simple-struct.rs, line 233.
$1 = {x = 1000, y = -1001}
```

This appears to be a regression - the same machine was passing tests last week (or maybe the week before).

cc @michaelwoerister

### PR DESCRIPTION
**Pull request by eddyb**
Based on @nodakai's https://github.com/rust-lang/rust/issues/40557#issuecomment-294368330 and @infinity0's https://github.com/rust-lang/rust/issues/40557#issuecomment-300133591.
Fixes #40557.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@bors r+

Thanks, @eddyb!

**Comment by nodakai** [comment]
```rust
         match &*self.config.target {
             "arm-linux-androideabi" |
             "armv7-linux-androideabi" |
             "aarch64-linux-android" => {
```

Should this branch be considered, too?

**Comment by eddyb** [comment]
@nodakai Android GDB with Rust support? I'm not sure - shouldn't matter for now anyway.

**Pull request merged**
