### PR TITLE
Various minor/cosmetic improvements to code

### PR DESCRIPTION
**Pull request by alexreg**
r? @Centril 😄

### CODE REVIEW

**Review by Centril — APPROVED** [review]

**Comment by alexreg** [comment]
@TimNN Why does @rust-highfive no longer hide CI log comments for out-of-date commits?

**Comment by alexreg** [comment]
Aghh, nll stderr files...

@bors r+ p=1

**Comment by scalexm** [comment]
I'm not sure I understand the added value of this PR, apart from forcing everyone to rebase, and I could not find any discussion about it prior to it being merged.

I agree one should always feel free to fix typos or spelling / grammatical errors, but I'm not sure we should somehow "impose" a writing style or whatever.

For example, I like to write the comma *before* the Latin locution "*i.e.*" because I believe this is correct English and moreover it mimics the usage in my own language, but I don't care if someone else likes another usage. The same goes for abbreviating the Latin locution "*nota bene*". Everyone has their writing style, and we are writing comments in a compiler, we are not writing a book.

I'm sure this PR will be totally stale in less than a few weeks because people will probably stick to their own writing style. So what will be the next steps? Are we opening a PR once a month to fix people comments? Or will we impose PR authors to fix their comments before any PR can be merged?

**Comment by alexreg** [comment]
@scalexm I personally would like to see a writing style agreed upon. I adopted a comma after Latin abbreviations because it is the U.S. English convention, and such conventions are used everywhere else. (Note, I'm actually British.) I also consider it more logical, because "e.g." and "i.e." are essentially abbreviated Latin translations of the phrases "for example" and "that is". It is *necessary* in grammatically-correct English to include the comma:

* For example, this is a sentence.
* That is, the comma is required.
* Note, one cannot dispense with the comma.

You make a fair point about the codebase diverging in style, however, which is why I feel a consensus on writing style, punctuation, and whatnot would be great at this point. Reviewers could then uphold it.

P.S. There's no requirement for any formal process on a PR like this, so I'm pretty sure no rules were broken. I dispute that it doesn't add value, though like I said above, it adds more value if people then stick to certain writing guidelines, and they're furthermore enforced.

**Comment by scalexm** [comment]
@alexreg That’s very fine but since it is a personal opinion, I’d like to see it discussed somewhere before imposing anything to the codebase, on the internals for example.

**Comment by alexreg** [comment]
I don't think there's any requirement to discuss it, as long as someone approves the PR... deciding on style guidelines is another matter. Do you want to create a thread for that, or should I?

**Pull request merged**
