### PR TITLE
save-analysis: use a decoupled representation for dumped data

### LINKED ISSUE #33348: save-analysis: use a decoupled representation for dumped data
Currently, the `Dump` trait exposes internal types of the compiler, which is undesirable. It also forces the trait's implementors to write lowering code (as can be seen in the current implementation of `json_dumper`).

### Proposed solution

1. Create a new module in `save-analysis` called `external_data` where the new `*Data` structs will live (they can be moved from `json_dumper`, along with the lowering code).
2. Modify the `Dump` trait to operate on `save_analysis::external_data::*` instead of on `save_analysis::data::*`.

### Some open problems

When getting a `DefId` from a `NodeId`, what should we do when `tcx.map.opt_local_def_id(node_id)` returns `None`? What does that mean? If we call the function with a `NodeId` provided by the compiler, should it always succeed? The current code doesn't make that assumption (see [data.rs](https://github.com/rust-lang/rust/blob/e1a575cb077d2070cc4527fa43bf9ef790f89f04/src/librustc_save_analysis/data.rs#L370))

### PR DESCRIPTION
**Pull request by aochagavia**
Closes #33348 

This will probably break any tool relying on the csv backend of save_analysis, for the following reasons:
1. Dumped spans don't contain extents anymore (`Dump` uses `SpanData` now instead of internal `Span`s). In case we still want to dump extents we could add them to `SpanData`.
2. `DefId`s are no longer dumped as a pair of `(ref_id, ref_crate)`. Instead, they are dumped as a single `Id`.

@nrc You said something about storing the id in a `u64`, but you didn't explain why. I kept using `u32` in this branch but I can change it if you prefer that.

r? @nrc 

By the way, the fact that this breaks tools relying on CSV may be a good occasion to start dumping CSV in a different way (i.e. using the serializer like in the JSON backend).

### CODE REVIEW

**Comment by nrc** [comment]
@aochagavia so I was thinking some more about ids, and I think what I started and which is continued here is bogus.

By using the index from the def_id and ignoring the crate num, we could have duplicate ids where two items have the same index, but are in different crates. My plan was to fix that by using a u64, where the low 32 bits would be the index and the high would be the crate num, but this doesn't work as an actual id - the client still has to do some work to convert local ids (i.e., those with crate num = 0) into non-local ones and to normalise crate numbers between crates. I feel like this is less obvious in a single id field, rather than having two fields for a def id, i.e., we're getting worse, not better. As far as I can see, there is no way to do this normalisation in the compiler and we must leave it to the client.

Sorry I didn't think of this earlier.

**Comment by aochagavia** [comment]
@nrc so the crux of the problem is normalizing crate numbers between crates. However, if the compiler itself doesn't have enough information to do it, how can we expect the clients to do it?

**Comment by nrc** [comment]
@aochagavia Once a tool has the crate dump for every crate, then a tool has all the info it needs to do the normalisation (this is what DXR does). The problem for the compiler is that it only has information on the current crate (and sort of earlier crates), but not any crates being compiler later.

Did you see my PR against this PR? https://github.com/aochagavia/rust/pull/1

**Comment by aochagavia** [comment]
@nrc I just merged your PR :)

**Pull request merged**
