### PR TITLE
Transition Travis CI to use rustbuild.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by sanxiyn** [comment]
Ugh. `issue-36023.rs` is failing because that particular LLVM bug in `simplifycfg` is present in LLVM 3.7...

**Comment by frewsxcv** [comment]
Yep, for now, this is blocked on https://github.com/rust-lang/rust/issues/36138.

**Comment by alexcrichton** [comment]
Ok, I've tried to fix that test in https://github.com/rust-lang/rust/pull/36198

**Comment by frewsxcv** [comment]
Temporarily cherry picked c6176f73049ecbc79662cb59ee3750fa750127f5

**Comment by frewsxcv** [comment]
Two failures:

```
test [run-make] run-make/atomic-lock-free ... FAILED
test [run-make] run-make/simd-ffi ... FAILED
```

**Comment by frewsxcv** [comment]
[The errors for those failed tests](https://gist.githubusercontent.com/frewsxcv/f41cdadab92c8b883fa14d00d2b37719/raw/013f58bd54b30e9972fef06b87654adab79107b2/gistfile1.txt).

**Comment by alexcrichton** [comment]
Aha, that's been fixed in the makefiles but not in rustbuild. Maybe [this patch](https://gist.github.com/alexcrichton/57c60611fbe516e7509aeded598526ad) will help?

**Comment by alexcrichton** [comment]
It's green!

If you want to back out the min-llvm-version commit and squash the other up, I'll r+

**Comment by frewsxcv** [comment]
Squashed.

**Pull request merged**
