### PR TITLE
Stop warning when doc testing proc macro crates

### LINKED ISSUE #39064: doc-tests don't work with macros 1.1
It looks like having `proc-macro = true` in `Cargo.toml` disables all doc-tests. However unit tests `#[test]` work fine.

# Steps to reproduce

1. `cargo new foo`

2. `edit Cargo.toml`
```toml
# ... the usual
[lib]
proc-macro = true
```

3. `edit src/lib.rs`
```rust
//! ```rust
//! fn main() { panic!() } /* <-- this test should fail */
//! ```

#![crate_type = "proc-macro"]
extern crate proc_macro;

#[proc_macro_derive(Foo)]
pub fn derive(_: proc_macro::TokenStream) -> proc_macro::TokenStream {
    unimplemented!()
}
```

4. `cargo test`
```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

### PR DESCRIPTION
**Pull request by keeperofdakeys**
Fixes #39064

Add the test option to the session struct that is passed
to phase_2_configure_and_expand function inside the
rustdoc test module.

This prevents the warning code from triggering when
parsing proc_macro_derive attributes, just like when
`--test` is normally invoked.

This change makes the warning disappear, but I'm not sure what else it might change. So this early PR is mainly to run the test suite, and to get feedback.

### CODE REVIEW

**Comment by keeperofdakeys** [comment]
Given the following error from the travis test, this PR definitely seems like the wrong approach.

```
error: macro undefined: 'assert!'
```

**Comment by keeperofdakeys** [comment]
@alexcrichton Do you have any thoughts on where to go from here? Adding the `test` flag for rustdoc seems like the wrong approach. Somehow I need another piece of state to tell the proc macro parser to abort early, and not trigger the warning. I don't feel like adding another flag to session::config::Options is the right approach.

**Comment by alexcrichton** [comment]
@keeperofdakeys I think we have a flag in options for "I am rustdoc please abort proc macro parsing early", could that be reused here?

**Comment by keeperofdakeys** [comment]
I've changed from using the `opts.test` flag, to the `opts.actually_rustdoc` flag, and all tests are now passing. I've also added a test for doctesting in proc-macro crates. This means all proc_macro parsing is skipped for `rustdoc --test`, which I don't think will cause any breakage.

**Comment by alexcrichton** [comment]
@bors: p=1

(fixing the regression here: https://github.com/rust-lang/rust/issues/37480#issuecomment-273724020)

**Pull request merged**
