### PR TITLE
Update the minimum external LLVM to 18

### PR DESCRIPTION
**Pull request by cuviper**
With this change, we'll have stable support for LLVM 18 and 19.
For reference, the previous increase to LLVM 17 was #122649.

cc @rust-lang/wg-llvm 
r? nikic

### CODE REVIEW

**Comment by nikic** [comment]
Can also remove this hack? https://github.com/rust-lang/rust/blob/f6bcd094abe174a218f7cf406e75521be4199f88/library/proc_macro/src/bridge/buffer.rs#L122-L123

r=me otherwise

**Comment by cuviper** [comment]
Reverted that hack -- cc #116088 @nbdd0121 

@bors r=nikic

**Comment by nbdd0121** [comment]
Hack revert LGTM

**Comment by cuviper** [comment]
Rebased to solve the merge conflict.

@bors r=nikic

**Pull request merged**
