### PR TITLE
lub: don't bail out due to empty binders

### PR DESCRIPTION
**Pull request by lcnr**
allows for the following to compile. The equivalent code using `struct Wrapper<'upper>(fn(&'upper ());` already compiles on stable. 
```rust
let _: fn(&'upper ()) = match v {
    true => lt_in_fn::<'a>(),
    false => lt_in_fn::<'b>(),
};
```
see https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7034a677190110941223cafac6632f70 for a complete example

r? @rust-lang/types

### CODE REVIEW

**Comment by jackh726** [comment]
This does allow more behavior, but I don't think there's anything that we don't *want* from a more "complete" system. Right?

**Comment by jackh726** [comment]
@rfcbot fcp merge

Do we want to commit to not inferring the LUB of `fn(fn(&'a ()))` and `fn(fn(&'b ()))` to `fn(for<'c> fn(&'c ()))` in the future?

**Comment by jackh726** [comment]
Let's try that again.

@rfcbot merge

Do we want to commit to not inferring the LUB of `fn(fn(&'a ()))` and `fn(fn(&'b ()))` to `fn(for<'c> fn(&'c ()))` in the future?

**Comment by jackh726** [comment]
@Mark-Simulacrum I guess we need to do something special for rfcbot?

**Comment by compiler-errors** [comment]
rust-lang/team#778

**Comment by compiler-errors** [comment]
Let's try this again:

@rfcbot merge

Do we want to commit to not inferring the LUB of `fn(fn(&'a ()))` and `fn(fn(&'b ()))` to `fn(for<'c> fn(&'c ()))` in the future?

**Comment by lcnr** [comment]
(as a side note, I don't expect this to be frequent enough that it would ever actually block us from inferring the lub to be higher ranked. People don't tend to have nested function pointers)

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

For future references, we had a detailed discussion [in the types team meeting](https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/meeting.202022-06-10), where we went over what was being proposed here, how it fit historically, and how it relates to the new subtyping algorithm that we are developing in a-mir-formality.

**Pull request merged**
