### PR TITLE
Remove all instances of fragment_infos and fragment sets

### PR DESCRIPTION
**Pull request by Nashenas88**
Remove unused fragment structs. This was suggested by @eddyb in IRC: [botbot link](https://botbot.me/mozilla/rustc/2017-05-23/?msg=86016574&page=2).

### CODE REVIEW

**Comment by aidanhs** [comment]
Thanks for the PR @Nashenas88! We'll keep an eye on it to make sure @eddyb or another reviewer gets to it soon.

**Comment by Nashenas88** [comment]
Looking into the failures now.

**Comment by Nashenas88** [comment]
So it seems the failing tests are just verifying the internal workings of the code that was just deleted (unless I misinterpreted them). Are there already tests for what replaced this (making these also candidates for deletion)? Or should these be modified to verify the functionality of the code that replaced fragment infos?

**Comment by eddyb** [comment]
@Nashenas88 Fragments were a dead-end in dynamic drop that never got used in practice.
MIR drop elaboration is more sophisticated and has its own tests etc. You can remove the fragment ones.

**Comment by Nashenas88** [comment]
@eddyb bump for merge?

**Comment by Mark-Simulacrum** [comment]
You can track this PR's progress through the queue here: https://buildbot2.rust-lang.org/homu/queue/rust; you are currently 9th.

**Pull request merged**
