### PR TITLE
Rename "Important traits" to "Notable traits"

### LINKED ISSUE #75245: Rename "important traits" to something better
A lot of the feedback on https://internals.rust-lang.org/t/feedback-on-important-traits-rustdoc-feature/12752  had better suggestions for the "important traits" feature.

Some options were:

 - Featured traits
 - Key traits
 - Notable traits

My personal preference is for "notable traits" because "important" is a much stronger value judgement whereas "notable" basically means "we thought you should know this" which is exactly what the feature does.

Thoughts? @rust-lang/rustdoc 

We should pick something and rename.

### PR DESCRIPTION
**Pull request by camelid**
Fixes #75245.

---

* Rename it in the UI
* Rename the CSS classes

### CODE REVIEW

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]
Please remove all the JS format changes.

**Comment by camelid** [comment]
@GuillaumeGomez Oops, thanks for catching that! VS Code must have done it...

**Comment by GuillaumeGomez** [comment]
Don't worry, it's just very complicated to see the actual changes in the middle of all the formattings. ;)

**Comment by camelid** [comment]
Fixed :)

**Review by Manishearth — APPROVED** [review]

**Review by GuillaumeGomez — APPROVED** [review]
Much better, thanks!

**Pull request merged**
