### PR TITLE
Parallel query tweaks

### PR DESCRIPTION
**Pull request by ljedrz**
- faster stack reversal in `remove_cycle`
- insert visited queries more eagerly
- simplify stack trimming in `cycle_check`
- minor refactoring in 2 spots

### CODE REVIEW

**Comment by Zoxc** [comment]
@ljedrz Did this pass tests locally with `[rust] experimental-parallel-queries = true`?

**Comment by ljedrz** [comment]
@Zoxc sure did; when I saw their recent performance wins O decided to keep it that way.

**Pull request merged**
