### PR TITLE
Make integer exponentiation methods unstably const

### PR DESCRIPTION
**Pull request by ecstatic-morse**
cc #53718

This makes the following inherent methods on integer primitives into unstable `const fn`:
- `pow`
- `checked_pow`
- `wrapping_pow`
- `overflowing_pow`
- `saturating_pow`
- `next_power_of_two`
- `checked_next_power_of_two`
- `wrapping_next_power_of_two`

Only two changes were made to the implementation of these methods. First, I had to switch from the `?` operator, which is not yet implemented in a const context, to a `try_opt` macro. Second, `next_power_of_two` was using `ops::Add::add` (see the first commit) to "get overflow checks", so I switched to `#[rustc_inherit_overflow_checks]`. I'm not quite sure why the attribute wasn't used in the first place.

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
So I found #45754, which removed `#[rustc_inherit_overflow_checks]` from `next_power_of_two` and added the call to `ops::Add::add`. I guess the attribute didn't work at that time? It seems to be working now, however. The test added in that PR passes with my changes. cc @scottmcm.

**Comment by oli-obk** [comment]
> It seems that this should be using #[rustc_inherit_overflow_checks] instead, so I'm not quite sure what's going on here.

That function likely outdates `rustc_inherit_overflow_checks` and was never adjusted

**Comment by oli-obk** [comment]
lgtm, we should remove the macro at some point, but that's not really a problem to leave around until someone discovers it.

I also don't know about the panic situation in that function. r=me with @scottmcm 's approval on that panic "change"

**Comment by scottmcm** [comment]
I have no horse in this race; I added it because I was asked to do so by @kennytm in https://github.com/rust-lang/rust/pull/45754#issuecomment-341884683

AFAIK that's just a matter of "use fewer `#[rustc*]` things where possible, so if it's not possible in this case and T-compiler is fine with it, I'm fine with it.

**Pull request merged**
