### PR TITLE
De-stabilize `thread::scoped` and friends

### PR DESCRIPTION
**Pull request by aturon**
Issue #24292 demonstrates that the `scoped` API as currently offered can
be memory-unsafe: the `JoinGuard` can be moved into a context that will
fail to execute destructors prior to the stack frame being popped (for
example, by creating an `Rc` cycle).

This commit reverts the APIs to `unstable` status while a long-term
solution is worked out.

(There are several possible ways to address this issue; it's not a
fundamental problem with the `scoped` idea, but rather an indication
that Rust doesn't currently provide a good way to ensure that
destructors are run within a particular stack frame.)

r? @alexcrichton

### CODE REVIEW

**Comment by aturon** [comment]
Per analysis on crates.io, we do not expect this change to impact much code in practice.

Note also that `scoped` is probably best offered in the long run as part of a framework for lightweight parallel tasks. It implies fork/join parallelism, which wants a pool at least, if not work stealing as well.

**Comment by aturon** [comment]
@alexcrichton Now with `spawn` adjustments and test fixes; re-r?

(Still running `make check` locally but it's pretty far along now.)

**Comment by seanmonstar** [comment]
Orly? This'll break hyper, at least. @reem

**Comment by aturon** [comment]
@bors: r-

There are some doc issues, need to rewrite the concurrency chapter.

**Comment by reem** [comment]
@seanmonstar our use in hyper can be adapted to spawn, but it does cost some additional `Arc`s where we can get away with `&` today.

**Comment by pythonesque** [comment]
Given that both of the proposed solutions (unless I'm missing something) change the required bounds of `Rc` and `Arc`, shouldn't they be destabilized as well?

**Comment by aturon** [comment]
@pythonesque

> Given that both of the proposed solutions (unless I'm missing something) change the required bounds of `Rc` and `Arc`, shouldn't they be destabilized as well?

Only one of the proposed solution involves changing these types, and for that approach to work it would need to be backwards-compatible anyway. Essentially, it would introduce a new marker trait that all existing types would satisfy automatically, and that was assumed automatically in most contexts (a bit like `Sized` is today). Adding such a bound to `Rc`/`Arc` would then not be a breaking change.

However, that's a fairly drastic piece of design, and a much simpler solution is just to not use RAII for `scoped`. You can instead use an API that works with an additional closure, executing the joins after the closure runs. For example, we used to have a "finally" API that did something like:

```rust
fn foo() {
    finally(|| {
        // code to run now
    }, || {
        // code to run afterwards, even on a panic
    }
}
```

We have some specific ideas about how to make a nice API along these lines work with `scoped`.

**Comment by pythonesque** [comment]
Perhaps I misinterpreted the comment about "like Arena" to mean that it would entail adding a lifetime to `Rc`.

The `Leak` solution is only backwards-compatible if it is made a special, compiler-supported trait, like `?Sized`.  The straightforward solution is to do it in userspace, but that only works if `Rc` and `Arc` are made to require the bound beforehand.

Absent such a solution, the existence of `Rc` and `Arc` means that a userspace library cannot even define its *own* set of safe abstractions that work like the old API, which is more flexible than a naive closure-based one.  For example: you can return a JoinGuard from a function, store it on the heap, or choose the order in which the guards are joined.  I guess I'd have to see what you had in mind for the new API.

The other reason I think it's worth considering Leak is that I suspect the ability to declare that a destructor really *does* have to be run (with the usual caveats around abort) is important for other cases than `JoinGuard`.  The fact that Rust doesn't guarantee that is kind of unfortunate and this would provide a way to recover that somewhat.

**Comment by alexcrichton** [comment]
Landed in #24433

**Pull request closed without merging**
