### PR TITLE
Lint against `&T` to `&mut T` and `&T` to `&UnsafeCell<T>` transmutes

### LINKED ISSUE #111229: mutable_transmutes lint should catch transmutes from a type without interior mutability to one with
I'm filing this as a regression, although the summary is worded in a feature request-ish way.

So, the regression itself is this: code that transmutes from a type without interior mutability to one with interior mutability leads to really bad outcomes after the bump to LLVM 16, because of the changes in https://github.com/llvm/llvm-project/commit/01859da84bad95fd51d6a03b08b60c660e642a4f. This is a pattern that happens in the wild, probably mostly around FFI. At least, that's how it happens in the Firefox codebase.

### Code

Here is a reduced testcase using a similar pattern to what Firefox is using:

```rust
pub struct Foo(std::cell::UnsafeCell<usize>);

pub struct Bar([u8; 0]);

pub fn foo(f: &Bar) {
    unsafe {
        let f = std::mem::transmute::<&Bar, &Foo>(f);
        *(f.0.get()) += 1;
    }
}
```

With rustc up to 1.69.0 in --release mode, this produces the following IR:
```llvm-ir
define void @_ZN10playground3foo17hc0e352349f95f9ecE(ptr noalias nocapture noundef nonnull readonly align 1 %f) unnamed_addr #0 {
start:
  %0 = load i64, ptr %f, align 8, !noundef !2
  %1 = add i64 %0, 1
  store i64 %1, ptr %f, align 8
  ret void
}
```

With rustc 1.70.0-beta.2 in --release mode, this produces the following IR:
```llvm-ir
define void @_ZN10playground3foo17h2141d3a0b5fe8d73E(ptr noalias nocapture noundef nonnull readonly align 1 %f) unnamed_addr #0 {
start:
  ret void
}
```

Note how everything is gone because the input pointer is marked as noalias readonly, and thus the code is not expected to change what it points to, so it's all removed. This is the typical example of undefined behavior leading to the optimizer doing unexpected things. I'm not arguing that there isn't undefined behavior. The undefined behavior existed before. But with LLVM 16, now the undefined behavior is actively dangerous.

Now, to come back to the feature-request-y summary I wrote, the following code does not compile:
```rust
pub struct Bar([u8; 0]);

pub fn foo(f: &Bar) {
    unsafe {
        let _ = std::mem::transmute::<&Bar, &mut Bar>(f);
    }
}
```

The produced error is:
```
error: transmuting &T to &mut T is undefined behavior, even if the reference is unused, consider instead using an UnsafeCell
```

I would argue that the code that is now compiled to nothing should also produce a similar error, and that error should be shipped in 1.70.0.

Cc: @pcwalton, @nikic

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
This adds the lint against `&T`->`&UnsafeCell<T>` transmutes, and also check in struct fields.

The code is quite complex; I've tried my best to simplify and comment it.

This is missing one parts: array transmutes. When transmuting an array, this only consider the first element. The reason for that is that the code is already quite complex, and I didn't want to complicate it more. This catches the most common pattern of transmuting an array into an array of the same length with type of the same size; more complex cases are likely not properly handled. We could take a bigger sample, for example the first and last elements to increase the chance that the lint will catch mistakes, but then the runtime complexity becomes exponential with the nesting of the arrays (`[[[[[T; 2]; 2]; 2]; 2]; 2]` has complexity of O(2**5), for instance).

Fixes #111229.

I've made this a deny-by-default and the wording says it's immediate UB, but from what I understand, under Tree Borrows this is not UB? CC https://github.com/rust-lang/unsafe-code-guidelines/issues/303. So maybe we should make this warn-by-default and make the wording less strong. But #111229 says it causes miscompilations... So I'm not sure what is really the situation.

This also doesn't handle other ways of doing the transmute, such as via pointer casts. A fix for that should be quite simple, but I left it out for future PR.

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
This is exactly the Tree Borrows error I was talking about... What am I supposed to do?

**Comment by ChayimFriedman2** [comment]
@Nilstrieb Indeed; that is why I said

> This also doesn't handle other ways of doing the transmute, such as via pointer casts. A fix for that should be quite simple, but I left it out for future PR.

Do you prefer to fix this on this PR?

**Comment by Nilstrieb** [comment]
I think it would be nice if this logic could be shared between mutable_transmutes and invalid_reference_casting so they both have this detection.

**Comment by ChayimFriedman2** [comment]
@Nilstrieb It turns out there isn't much to share: Only one function is similar enough, and even it is different enough to make sharing not worth it. I'm already on it, though, so I'll push this addition to this PR soon.

**Comment by Dylan-DPC** [comment]
@ChayimFriedman2 any updates on the changes requested above? thanks

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
