### PR TITLE
libsyntax: stop early enough if keyword is found instead of ident

### LINKED ISSUE #28439: Parser does not stop early enough if keyword is found instead of ident
For
```rust
enum A {
    enum A
}
```
and for 
```rust
struct A {
    mod A
}

```
2 errors are emitted for each
```
test.rs:2:5: 2:9 error: expected identifier, found keyword `enum`
test.rs:2     enum A
              ^~~~
test.rs:2:10: 2:11 error: expected one of `(`, `,`, `=`, `{`, or `}`, found `A`
test.rs:2     enum A
                   ^
```
and
```
test.rs:2:5: 2:8 error: expected identifier, found keyword `mod`
test.rs:2     mod A
              ^~~
test.rs:2:9: 2:10 error: expected `:`, found `A`
test.rs:2     mod A
                  ^
```

2nd error should not happen.

### PR DESCRIPTION
**Pull request by matklad**
fixes #28439

The signature of public function `check_strict_keywords` is changed. This function is used only once in rustc in `parse_ident`.

This breaks 9 tests in `parse-fail` category, because they expect two messages instead of one. I think it's safe just to fix the tests expectations.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like this has some regressions in the compile-fail tests which will need to be addressed.

I also think that the current behavior is fine, it's targeted at cases like:

```rust
enum Foo {
    Self(i32),
    // ...
}
```

In this case you'll get an error message about `Self` and nothing else, but the parser will keep going and try to emit more errors. In that sense I'm not 100% convinced that #28439 is indeed a bug.

**Comment by matklad** [comment]
> In that sense I'm not 100% convinced that #28439 is indeed a bug.

Same for me.

Cons:
  - the parser will not recover after `Self(i32)`
  - a public interface is changed
  - current behaviour is changed. 

Pros: 
  - if we actually look at the changed tests, https://github.com/matklad/rust/commit/95a87ba8e732a4794df8f41c555ab1496c45576b, parser recovery usually leads to some obscure error like this "ERROR expected one of `!`, `,`, `.`, `::`, `;`, `]`, `{`, or an operator, found `1`". I argue that reporting only one error in such cases is much better. The caveat is that though such cases form a significant majority in tests, nothing can be said about distribution in user's code. 
  - inconsistency between `check_strict_keywords` and `check_reserved_keywords` does not feel right: https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L548-L549


I have no strong opinion about what is best, but I am slightly in favor of change.

**Comment by matklad** [comment]
@alexcrichton so should I repair the test (and move it to parse-fail category), or this is a won't fix?

**Comment by alexcrichton** [comment]
In terms of recovering from parser errors, I think it makes the most sense to try to recover from errors that are likely to arise. For example it's expected that `enum Foo { ident }` is a valid declaration, so if `ident` is actually a keyword it may make the most sense for the parser to assume it was a bland identifier and just keep parsing as usual.

A lot of the parse-fail tests are either super old syntax or are just kinda semi-random syntax, which is bound to always give obscure parse errors. I suppose what I'm getting at is that I'm ok with obscure code giving obscure errors, it makes more sense to try to give high quality errors (and as many of them as possible) for almost-reasonable code as it's the most likely kind to be written by accident.

I also wouldn't worry too much about public interfaces here, everything is unstable so we're free to change at will.

**Comment by matklad** [comment]
So let's close the PR and the issue.

**Comment by alexcrichton** [comment]
Ok, thanks regardless for the PR @matklad!

**Pull request closed without merging**
