### PR TITLE
CFI: Break tests into smaller files

### PR DESCRIPTION
**Pull request by rcvalle**
Break type metadata identifiers tests into smaller set of tests/files, and move CFI (and KCFI) codegen tests to a cfi (and kcfi) subdirectory,

### CODE REVIEW

**Comment by compiler-errors** [comment]
Can you take all the tests prefixed `cfi` and move them into a `cfi/` subdirectory?

**Comment by rcvalle** [comment]
> Can you take all the tests prefixed `cfi` and move them into a `cfi/` subdirectory?

Done. (I also moved all KCFI tests to a kcfi subdirectory.)

**Review by compiler-errors — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
@bors r- rollup=iffy
https://github.com/rust-lang/rust/pull/122457#issuecomment-1996051828

**Pull request merged**
