### PR TITLE
Slightly micro-optimize derive of PartialOrd

### PR DESCRIPTION
**Pull request by thomcc**
When I was poking around here (for #109606), I noticed this was allocating a vec for no reason.

I also noticed that the compiler doesn't seem deduce the position/count loops can short-circuit early (at least in my tweaked test code it couldn't -- I don't know how to easily inspect asm for rustc itself), so I made them manually short-circuit by adding `take(n)` to the iterator chains. This is definitely more subtle/complex code but `#[derive(PartialOrd)]` is used a lot. I think the comments help avoid it being a maintenance hazard.

### CODE REVIEW

**Comment by thomcc** [comment]
Draft til perf comes back.

@bors try @rust-timer queue

**Comment by thomcc** [comment]
Crap, this is actually wrong.

**Comment by thomcc** [comment]
Will retrigger perf after local tests finish.

**Comment by thomcc** [comment]
Seems like mostly a wash. The "non-relevant metrics" under instructions/cycles seem to indicate it's positive, but it could be noise. Still, it feels wasteful to allocate a `vec![bool; num_variants]` for each enum, when we can just compute the same thing without doing so.

**Comment by apiraino** [comment]
reassigning review. Since the reviewer was autoassigned and never commented I think it's fine to switch over to someone else.

r? compiler

**Comment by compiler-errors** [comment]
If perf is unconvincing then I'm not sure if this should land or not. Maybe we can rebase this and retry? Otherwise, :shrug:

**Comment by apiraino** [comment]
yeah, probably makes sense to give it a try. Would you try a rebase @thomcc when you have some time? Thanks!

@rustbot author

**Comment by JohnCSimon** [comment]
@thomcc 
ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!

**Comment by oskgo** [comment]
@thomcc

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this.
Note: if you are going to continue please open the PR BEFORE you push to it, else you won't be able to reopen - this is a quirk of github.
Thanks for your contribution.

**Pull request closed without merging**
