### PR TITLE
Fix macro hygiene bug

### LINKED ISSUE #31856: Hygiene broken in multi-statement macros
Multi-statement macros (macros that expand to multiple statements) are hard to use because hygiene runs separately on each line, meaning it's very easy to "lose" identifiers.

[Here are some examples.](http://is.gd/sGjll7) The macro is trying to declare a variable in the scope where it was called, but it takes multiple statements to construct.

```rust
/*
// no good: $n declared in inner scope
macro_rules! m {
    ($n:ident) => ({
        let a = 1;
        let $n = a;
    })
}
*/

/*
// no good: hygiene throws away "a"
macro_rules! m {
    ($n:ident) => (
        let a = 1;
        let $n = a;
    )
}
*/

// workaround
macro_rules! m {
    ($n:ident) => (
        let $n = {
            let a = 1;
            a
        };
    )
}

fn main() {
    m!(b);
    println!("{}", b);
}
```

This is a long-standing bug, not a regression. I previously reported this [here](https://github.com/rust-lang/rust/pull/24155#issuecomment-126487021) and [here](https://github.com/rust-lang/rust/issues/10681#issuecomment-138968951) (can likely be closed) but it wasn't very visible. ping @Sgeo @chris-chambers

### LINKED ISSUE #32922: Macro hygiene bug
The following should print `1`, but it currently prints `0`:
```rust
fn main() {
    let x = 0;
    macro_rules! foo { () => {
        let x = 1;
        macro_rules! bar { () => {x} }
        println!("{}", bar!());
    }}

    foo! {};
}
```

For comparison, the following correctly prints `1`:
```rust
fn main() {
    let x = 0;
    macro_rules! foo { () => {{ //< note the added brace here
        let x = 1;
        macro_rules! bar { () => {x} }
        println!("{}", bar!());
    }}}

    foo! {};
}
```

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes #32922 (EDIT: also #31856, #10681, and #26223), macro hygiene bugs.
It is a [breaking-change]. For example, the following would break:

``` rust
fn main() {
    let x = true;
    macro_rules! foo { () => {
        let x = 0;
        macro_rules! bar { () => {x} }
        let _: bool = bar!();
        //^ `bar!()` used to resolve the first `x` (a bool),
        //| but will now resolve to the second x (an i32).
    }}
    foo! {};
}
```

r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
This could use a crater run (cf discussion in #32922).

**Comment by alexcrichton** [comment]
Starting a crater run

**Comment by alexcrichton** [comment]
Crater reports [one regression](https://gist.github.com/alexcrichton/a132ef73bf7960abba0a411b8d068bab), but it looks spurious, so essentially nothing from crater.

**Comment by jseyfried** [comment]
Great, thanks!

**Comment by nrc** [comment]
Could you add some of the tests from #31856 please? r+ with that

**Comment by jseyfried** [comment]
@nrc I added another test from #31856.

**Comment by jseyfried** [comment]
Fixes #10681.

**Comment by jseyfried** [comment]
Fixes #26223.

**Pull request merged**
