### PR TITLE
Stabilize fs::read and fs::write

### PR DESCRIPTION
**Pull request by mbrubeck**
As discussed in https://github.com/rust-lang/rust/issues/46588#issuecomment-373956283

### CODE REVIEW

**Comment by mbrubeck** [comment]
This fails tidy because the the still-unstable `fs::read_string` has the same feature name as these stabilized functions.  What's the preferred solution here?  Change the feature name in the new `#[stable]` attributes, maybe?  (Or we could change the feature for `read_string` but this would be slightly more disruptive to existing unstable code.)

**Comment by scottmcm** [comment]
I like just changing the feature to `fs_read_write_bytes` or something.  I don't think the feature name actually matters so, as you say, not breaking nightly seem nicer.

**Comment by mbrubeck** [comment]
> I like just changing the feature to `fs_read_write_bytes` or something.

Done.

**Comment by kennytm** [comment]
Remember to change the version to 1.26.0 if this merges before someone has got time to branch the beta.

**Comment by mbrubeck** [comment]
One of the appveyor jobs hit the 3 hour limit.  Can someone retry it?

**Comment by TimNN** [comment]
> Remember to change the version to 1.26.0 if this merges before someone has got time to branch the beta.

Oh, it looks like I misinterpreted one of the commits on the `beta` branch. It looks like we'll indeed need to change the versions.

**Pull request merged**
