### PR TITLE
[beta] Fixed issue with using `Self` ctor in typedefs

### PR DESCRIPTION
**Pull request by alexreg**
Corresponds to master PR #56850.

r? @petrochenkov

CC @Centril @Mark-Simulacrum

### CODE REVIEW

**Comment by alexreg** [comment]
AppVeyor is still borked, but this should be fine to merge.

**Comment by petrochenkov** [comment]
After the primary PR (https://github.com/rust-lang/rust/pull/56850) lands and is approved as beta-accepted, it will be cherry-picked to beta by release team (possibly as a part of beta-rollup to save CI time).

**Comment by alexreg** [comment]
Define "clean".

"Doesn't appreciate" comes across a bit rude. I'm not working for you, after all...

**Comment by Mark-Simulacrum** [comment]
First off, I apologise for any offense given: none was intended.

To address your points, I definitely clean as a rebase without merge conflicts and one that continues to compile/pass tests; in those cases there's no need for the pull request author to spend the time rebasing; they are of course welcome to do so, but we'll likely not merge such efforts individually to avoid using CI cycles on individual beta backports.

I'm not sure if you misread or are looking at the implied reverse of my statement, but to rephrase, by "does appreciate" I didn't mean that we don't appreciate it otherwise, just that it's not necessary for you (or others) to spend the time, since it'll be relatively easy for the release team to do the necessary work.

Happy to clarify further if I've left anything unclear!

**Comment by alexreg** [comment]
Okay, thanks for clarifying. That makes sense. I just thought I was saving you guys (a small amount of) work by doing this heh. Anyway, yes, merge conflicts were unavoidable unfortunately... at least one or two of them were. Minor though.

**Pull request closed without merging**
