### PR TITLE
update vergen

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/56576

r? @oli-obk

### CODE REVIEW

**Comment by pietroalbini** [comment]
Nominating for stable and beta backport, otherwise rustc can't be built from source.

**Comment by RalfJung** [comment]
Notice that miri failing to build does not block a release.  It is essentially coincidence that stable happened at a time when the miri toolstate was green, and there will likely be releases where miri does not build.  I think that's okay, miri is a low-priority nightly-only tool that shouldn't interfere with releases.

**Comment by RalfJung** [comment]
Looking at the build log, backporting to beta makes sense:
```
{"rustfmt":"test-pass","nomicon":"test-pass","rls":"test-pass","clippy-driver":"test-pass","rust-by-example":"test-pass","book":"test-pass","reference":"test-pass","miri":"test-pass"}
```
but backporting to stable does not because miri would not build anyway:
```
{"book":"test-pass","reference":"test-pass","clippy-driver":"test-pass","nomicon":"test-pass","rust-by-example":"test-pass","rustfmt":"test-pass","miri":"build-fail","rls":"test-pass"}
```

**Comment by oli-obk** [comment]
I think we should rather find a way not to build or include clippy in the packaged (stable) releases

**Comment by RalfJung** [comment]
@oli-obk you mean miri?

**Comment by RalfJung** [comment]
Rebased. This PR will be a lot of fun. I am taking bets how many rebases will be required ;)

@bors r=oli-obk

**Comment by pietroalbini** [comment]
Uh, woops, misread the original issue, [this is not critical](https://github.com/rust-lang/rust/issues/56576#issuecomment-445316246).

**Pull request merged**
