### PR TITLE
Sandwich MIR optimizations between DSE.

### PR DESCRIPTION
**Pull request by cjgillot**
This PR reorders MIR optimization passes in an attempt to increase their efficiency.

- Stop running CopyProp before GVN, it's useless as GVN will do the same thing anyway. Instead, we perform CopyProp at the end of the pipeline, to ensure we do not emit copy/move chains.
- Run DSE before GVN, as it increases the probability to have single-assignment locals.
- Run DSE after the final CopyProp to turn copies into moves.

r? @ghost

### CODE REVIEW

**Comment by cjgillot** [comment]
Now that https://github.com/rust-lang/rust/pull/119677 is merged.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Perf results: we get some nice speedups, near 2% for cargo, clap & ripgrep, which confirm the earlier perf run. On average, small improvements and small regressions balance out.
I propose to go ahead and merge this.
r? wg-mir-opt

**Comment by lqd** [comment]
As seen in the previous runs: some nice wins on bigger benchmarks, and overall gains outweigh the few losses.

@rustbot label: +perf-regression-triaged

**Pull request merged**
