### PR TITLE
DO NOT MERGE: map_split perf test

### PR DESCRIPTION
**Pull request by joshlf**
This PR represents the cherry-pick of https://github.com/rust-lang/rust/pull/51466 and https://github.com/rust-lang/rust/pull/51630 onto [b81da2](https://github.com/rust-lang/rust/commit/b81da278623d9dcda1776008612bd42e1922e9c3) (the commit just before https://github.com/rust-lang/rust/pull/51466). Comparing the performance of this PR to the performance of b81da2 should give us an apples-to-apples comparison of the optimized version of `map_split` against a previous world in which `map_split` doesn't exist, and refcounts can only represent a single writing reference.

cc @nnethercote @rkruppe @RalfJung @kennytm

### CODE REVIEW

**Comment by joshlf** [comment]
OK, I resolved the merge conflicts, so bors should be OK with it now.

**Comment by RalfJung** [comment]
> Comparing the performance of this PR to the performance of b81da2 should give us an apples-to-apples comparison of the optimized version of map_split against a previous world in which map_split doesn't exist, and refcounts can only represent a single writing reference.

It seems that bors merges master into this before running perf? So to actually compare apples with apples we'd have to take care that the two merges happen at the same time?

**Comment by joshlf** [comment]
> It seems that bors merges master into this before running perf? So to actually compare apples with apples we'd have to take care that the two merges happen at the same time?

I'm not sure what you mean by "two merges happen at the same time"?

**Comment by RalfJung** [comment]
I mean that if this PR gets merged into master and perf runs, and then 2 days later the other PR gets merged into master and perf runs, the difference could also come from stuff that has happened in master in the mean time.

Ideally, perf would run on the PR, not on the PR merged into master. Or maybe it does? I just inferred it would not from the fact that merge conflicts were an issue.

**Comment by Mark-Simulacrum** [comment]
Perf running for d8dd3b51bfd1c672a39e4bb912ecfa5b801b09db. @RalfJung is I believe correct that bors try will take the PR head and rebase it atop master before building.

**Comment by pietroalbini** [comment]
Ping from triage! @Mark-Simulacrum are the perf results ready?

**Comment by kennytm** [comment]
Perf is in fact ready http://perf.rust-lang.org/compare.html?start=ac8d1f7623f55746ff8f59d6b26f03c39cee5844&end=d8dd3b51bfd1c672a39e4bb912ecfa5b801b09db&stat=instructions%3Au

**Comment by kennytm** [comment]
Honestly I think the goal of the perf check is to show a -4% improvement to offset https://github.com/rust-lang/rust/pull/51466#issuecomment-398255276, not a strict apple-to-apple comparison. The perf result in https://github.com/rust-lang/rust/pull/51630#issuecomment-398481819 should be a sufficient signal to say the fix works.

**Comment by kennytm** [comment]
#51466 has been merged, so closing this PR now.

**Pull request closed without merging**
