### PR TITLE
Avoid re-resolving nested inference vars where possible

### PR DESCRIPTION
**Pull request by oli-obk**
It sometimes happens that we see an inference var (e.g. `_1`) that we then resolve to e.g. `(_2, u32)`, which then gets folded again to e.g. `(bool, u32)`. The problem is that we do this every time we resolve `_1` instead of just once. We may be able to save some cycles by caching the result of the inner folding.

This is very common for situations like

```rust
let x = 0;
[()][x];
```

Where the type of `x` is e.g. `_1`, but the type of `0` is `_2` (an inference var of the "integer" flavor). So resolving `_1` gave us `_2` before this PR, where now it gives us `usize` immediately.

r? @nnethercote

### CODE REVIEW

**Comment by bjorn3** [comment]
@rust-timer build 55c136ade2a4ca5e4e24681f4de314e963ce22d1

**Comment by oli-obk** [comment]
This seems like it doesn't actually improve anything. We rarely deeply resolve type variables, so this makes sense

**Comment by nnethercote** [comment]
Seems fine, r=me if you want it, but is it worth landing without any noticeable effect?

**Comment by oli-obk** [comment]
No, the extra complexity would only make sense if we'd see an improvement. I just kept this open to replace the entire PR witha comment in the right place explaining what's happening and that avoiding the nested resolving doesn't help anything

**Comment by oli-obk** [comment]
uh... I screwed up and did this change in the shallow resolver 🤦 that obviously won't do much. Let's try this again properly 😆

**Comment by oli-obk** [comment]
Neither of these changes affects anything, so it seems like this isn't common or costly enough to warrant updating the resolutions

**Pull request closed without merging**
