### PR TITLE
Inline StrSearcher::haystack()

### PR DESCRIPTION
**Pull request by alexbool**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ah I feel the [same as](https://github.com/rust-lang/rust/pull/42716#issuecomment-309228092) #42716, let's be sure we have numbers to justify this but otherwise let's hold off on `#[inline]`

**Comment by alexbool** [comment]
@alexcrichton I discovered this by accident when inspecting assembly of one of my programs in release mode. I was surprised to find lots of calls to that function here and there when it's just a getter to the field. I thought this method is an easy catch for the optimizer to inline (provided the attribute is there), basically 2 instructions to make a call to the function and 6 instructions in the function itself become 2 `mov` instructions. I have neither benchmarks nor numbers. Other impls of that trait have `#[inline]` on this method, so I filed this PR for the sake of consistency too.

**Comment by alexcrichton** [comment]
Oh don't worry, I understand how `#[inline]` works and how it's necessary for many small functions, and how it often can help performance quite a bit.

All I personally want is an anecdote or benchmarking showing the necessity of such tags. We have not always been so principled in the past, but it's very easy to go overboard with `#[inline]`. 

Sounds like you hit this when benchmarking, though, so sounds good to me, thanks!

@bors: r+

**Pull request merged**
