### PR TITLE
rustc_driver: Enable the `WARN` log level by default

### LINKED ISSUE #76824: Consider making RUSTC_LOG=warn the default (instead of just error).
We don't use `error!`/`warn!`/`info!` a lot, but they come in handy for "debugging `rustc` without a `debug-assertions` build" situations, e.g. we use `info!` to show the function being codegen'd (as it's low-overhead and really helpful for e.g. LLVM crashes).

While `info!` makes sense for off-by-default debugging helpers like that, `error!`/`warn!` seem closer to user-facing diagnostics, where the main difference is them being usable outside of code which has access to a `Session` (either due to running before the `Session` is created, or just in dependencies that have access to `log`/`tracing` but not any `rustc`-specific diagnostics APIs).

However, one surprising aspect is *only* `error!` is enabled by default, while `warn!` *is not*, meaning that, with the current defaults, one is forced to choose between `error!` (which would output the word "error" which sounds more dire than "warning") or `warn!` (which may never be seen by an user).

<hr/>

My usecase for `warn!` is in the upcoming `-Z self-profile` support for using hardware performance counters (which needs to be implemented in the separate `measureme` project), e.g. [this `warn!` instructs the user to open an issue](https://gist.github.com/eddyb/269491b0b59605f39f1d0a9dcf535c4a/025ee76590ad4e24a7dce9754080fb7c2b30df85#file-rdpmc-bench-rs-L565-L570) if they have an unrecognized (newer) CPU, but there's nothing preventing `-Z self-profile` from working (if the newer CPUs aren't drastically different), so showing "error" seems quite inappropriate.

Sadly, I don't think ~~`log`~~ `env_logger` itself will change this behavior, so even if we change `RUSTC_LOG`'s default, `measureme` might still have to use the less-appropriate `error!` if it wants to account for being used in other projects.

cc @Mark-Simulacrum @gdhuper @hawkw

### PR DESCRIPTION
**Pull request by hawkw**
This commit changes the `tracing_subscriber` initialization in
`rustc_driver` so that the `WARN` verbosity level is enabled by default
when the `RUSTC_LOG` env variable is empty. If the `RUSTC_LOG` env
variable is set, the filter string in the environment variable is
honored, instead.

Fixes #76824
Closes #89623

cc @eddyb, @oli-obk

### CODE REVIEW

**Comment by jyn514** [comment]
@lcnr do you know whether that `warn!` should be a proper user-facing error or just an `info!` log? `WARN rustc_mir_dataflow::rustc_peek peek_at: place=_1` doesn't seem very helpful for developers.

**Comment by hawkw** [comment]
Okay, I changed the `rustc_peek` traces to `INFO`. I also went through and changed a few existing warnings that used, essentially, tracing's structured fields formatting but in textual messages, so that they just emit structured fields.

If these changes aren't desired, I can back them out?

**Review by eddyb — CHANGES_REQUESTED** [review]

**Comment by lcnr** [comment]
> @lcnr do you know whether that `warn!` should be a proper user-facing warning or just an `info!` log? `WARN rustc_mir_dataflow::rustc_peek peek_at: place=_1` doesn't seem very helpful for developers.

I can't remember adding that `warn!` and also don't think that it is too helpful. Changing that to `debug` or `info` seems good to me

**Comment by hawkw** [comment]
> The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3831110405) [(plain)](https://github.com/rust-lang/rust/commit/0e79545c306ca173fc406b61a81ea4e14400d293/checks/3831110405/logs)
> Click to see the possible cause of the failure (guessed by this bot)
> 
> ```
> failures:
> 
> ---- [ui] ui/consts/const_in_pattern/issue-73431.rs stdout ----
> normalized stderr:
> WARN rustc_mir_build::thir::pattern::const_to_pat MIR const-checker found novel structural match violation. See #73448.
> 
> 
> The actual stderr differed from the expected stderr.
> Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const_in_pattern/issue-73431/issue-73431.stderr
> Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const_in_pattern/issue-73431/issue-73431.stderr
> To update references, rerun the tests and pass the `--bless` flag
> To only update this specific test, also pass `--test-args consts/const_in_pattern/issue-73431.rs`
> 
> error: 1 errors occurred comparing output.
> status: exit status: 0
> command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/consts/const_in_pattern/issue-73431.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const_in_pattern/issue-73431/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const_in_pattern/issue-73431/auxiliary"
> Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
> ------------------------------------------
> 
> ------------------------------------------
> stderr:
> stderr:
> ------------------------------------------
> WARN rustc_mir_build::thir::pattern::const_to_pat MIR const-checker found novel structural match violation. See #73448.
> ------------------------------------------
> 
> 
> 
> 
> failures:
>     [ui] ui/consts/const_in_pattern/issue-73431.rs
> 
> test result: FAILED. 12141 passed; 1 failed; 115 ignored; 0 measured; 0 filtered out; finished in 135.44s
> 
> 
> 
> command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-10/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "10.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86utils xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "nightly" "--color" "always"
> 
> 
> Build completed unsuccessfully in 0:14:29
> ```

I'm assuming that the solution here is just to update the UI tests to expect that stdout will contain warnings, but I wanted to make sure that was the case.

**Comment by hawkw** [comment]
🙌

**Pull request merged**
