### PR TITLE
Parallelize and optimize parts of HIR map creation

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
The addition of `ModuleItems` and iteration of module item-likes is the same code as in https://github.com/rust-lang/rust/pull/51487

**Comment by Zoxc** [comment]
Blocked on https://github.com/rust-lang/rust/pull/51487

**Comment by Zoxc** [comment]
> Would the work done here be obsolete once we implement end-to-end queries?

I'd need to know a more concrete plan to answer this, but it won't be obsolete assuming the HIR map is still around.

**Comment by michaelwoerister** [comment]
It's at least possible that there won't be a hir map in the current form, and that we rather build it lazily. There'd then be a bunch of queries providing the information that the map holds now (which automatically make building the map parallel). But I don't think anybody has a concrete design for this yet.

**Comment by michaelwoerister** [comment]
Ok, the changes here don't look too complicated. Let's do it!

@bors r+

Thanks,  @Zoxc!

**Pull request merged**
