### PR TITLE
Update `indexmap`

### PR DESCRIPTION
**Pull request by pierwill**
Update to version 1.7.0.

r? @cuviper

### CODE REVIEW

**Comment by bjorn3** [comment]
Rustc and cg_clif already specify 1.7.0 in their Cargo.lock. This bump in the Cargo.toml files doesn't hurt, but isn't necessary either.

**Comment by pierwill** [comment]
> Rustc and cg_clif already specify 1.7.0 in their Cargo.lock. This bump in the Cargo.toml files doesn't hurt, but isn't necessary either.

Ah okay, thanks! I do think it'd be nice to bump these. 😇

**Comment by calebcartwright** [comment]
The rustfmt files updated under the `tests` directory are dummy placeholders that are never actually compiled/wouldn't impact the root level lockfile, but I don't have any concerns or objections with those changes either

**Comment by cuviper** [comment]
I would like to merge a few `indexmap` PRs and publish a new release, and then we can actually make this a functional change with `rustc-rayon` support (bluss/indexmap#212) at least. I'll try to do that in the next few days.

**Pull request closed without merging**
