### PR TITLE
Stabilize unsafe extern blocks (RFC 3484)

### PR DESCRIPTION
**Pull request by spastorino**
# Stabilization report

## Summary

This is a tracking issue for the RFC 3484: Unsafe Extern Blocks

We are stabilizing `#![feature(unsafe_extern_blocks)]`, as described in [Unsafe Extern Blocks RFC 3484](https://github.com/rust-lang/rfcs/pull/3484). This feature makes explicit that declaring an extern block is unsafe. Starting in Rust 2024, all extern blocks must be marked as unsafe. In all editions, items within unsafe extern blocks may be marked as safe to use.

RFC: https://github.com/rust-lang/rfcs/pull/3484
Tracking issue: #123743

### Summary of stabilization

We now need extern blocks to be marked as unsafe and items inside can also have safety modifiers (unsafe or safe), by default items with no modifiers are unsafe to offer easy migration without surprising results.

```rust
unsafe extern {
    // sqrt (from libm) may be called with any `f64`
    pub safe fn sqrt(x: f64) -> f64;

    // strlen (from libc) requires a valid pointer,
    // so we mark it as being an unsafe fn
    pub unsafe fn strlen(p: *const c_char) -> usize;

    // this function doesn't say safe or unsafe, so it defaults to unsafe
    pub fn free(p: *mut core::ffi::c_void);

    pub safe static IMPORTANT_BYTES: [u8; 256];

    pub safe static LINES: SyncUnsafeCell<i32>;
}
```

## Tests

The relevant tests are in `tests/ui/rust-2024/unsafe-extern-blocks`.

## History

- https://github.com/rust-lang/rust/pull/124482
- https://github.com/rust-lang/rust/pull/124455
- https://github.com/rust-lang/rust/pull/125077
- https://github.com/rust-lang/rust/pull/125522
- https://github.com/rust-lang/rust/issues/126738
- https://github.com/rust-lang/rust/issues/126749
- https://github.com/rust-lang/rust/issues/126755
- https://github.com/rust-lang/rust/pull/126757
- https://github.com/rust-lang/rust/pull/126758
- https://github.com/rust-lang/rust/issues/126756
- https://github.com/rust-lang/rust/pull/126973
- https://github.com/rust-lang/rust/pull/127535
- https://github.com/rust-lang/rustfmt/pull/6204

## Unresolved questions

I am not aware of any unresolved questions.

### CODE REVIEW

**Comment by spastorino** [comment]
r? @traviscross 

I wasn't sure if I should leave this as a draft but would leave all this up to t-lang.

**Comment by oli-obk** [comment]
> default items with no modifiers are unsafe to keep backwards compatibility.

We don't need back compat when `unsafe` is added to the extern block, why do we have this rule?

**Comment by spastorino** [comment]
> > default items with no modifiers are unsafe to keep backwards compatibility.
> 
> We don't need back compat when `unsafe` is added to the extern block, why do we have this rule?

Well ... is not really about backwards compatibility and when I wrote this, I kind of knew that I wasn't properly explaining myself. What I meant was ... if we were to flip default safety to safe, it would not only be surprising but would may also led to end with something that was unsafe being safe when you migrate.
Imagine ...

```rust
extern "C" {
    fn foo();
    // foo is unsafe
}
```

When I migrate my code I do ...

```rust
unsafe extern "C" {
    fn foo();
    // now foo is safe
}
```

if the semantics of not providing safety is now being safe this would be a disaster.

This is what I meant in that text, but written really poorly :). If you want to suggest an edit, I'd be happy to apply it.

**Comment by oli-obk** [comment]
Why don't we just reject missing `unsafe` or `safe` and require one or the other if the extern block is marked `unsafe`?

**Comment by workingjubilee** [comment]
It is best to avoid the phrase "backwards compatibility", as it is clear that it means different things to different people. For some, it means to keep code that currently exists compiling. For others, they primarily mean preserving functional equivalence if the code is recompiled, but not necessarily allowing it to still compile (e.g. rejecting unsound code). For others, it means offering easy migration to a new paradigm that does not have surprising results.

**Comment by workingjubilee** [comment]
> Why don't we just reject missing unsafe or safe and require one or the other if the extern block is marked unsafe?

@oli-obk This feature has two functional changes that are being stabilized together because the 2nd does not make sense without the 1st:
1. We demand adding `unsafe` to `unsafe extern "C"` because the *mere declaration* is unsafe. It can make previously-sound programs unsound to add this declaration, because it can change how they are compiled and linked. An incorrect declaration is *very likely* to make your code unsound.
2. It adds the ability to distinguish `safe`-to-call functions. Now that the `unsafe` declaration obligation is discharged at the actual declaration site (where it should be, instead of every call site), programmers now may claim that certain functions are `safe`, despite being written in C.

Thus, "also reject fn in `extern "C" {}` that lack the `unsafe fn` qualifier" is an **additional** language change. [The RFC mentions it as an alternative](https://rust-lang.github.io/rfcs/3484-unsafe-extern-blocks.html#require-all-items-to-be-marked-as-either-safe-or-unsafe) but says that it was not selected as it is a worse migration story. One is simply "slap `unsafe` before every individual `extern "C"` block", the other is a lot more work, and has some additional possibilities. For instance, it might require adding `extern "C" { unsafe static IDENT: Type; }` to the language.

...actually, *do* we test for that? I can't see one for either accepting or rejecting them. It seems we test for (and now accept) `safe static`?

**Comment by workingjubilee** [comment]
Is it possible to write `k#safe` in previous editions? Did we ever commit to that prefix?

**Comment by workingjubilee** [comment]
Ah, we have this test:
```rust
unsafe extern "C" {
    unsafe static TEST1: i32;
    unsafe fn test1(i: i32);
}
```

So this does add the syntactic possibility of adding this qualifier on this.

...huh, wait, we're adding this keyword to earlier editions? Does that mean we're only parsing this keyword contextually? https://github.com/rust-lang/rust/blob/9a8888c0282cfa54dd786b1edd90329eefb0d086/tests/ui/rust-2024/unsafe-extern-blocks/safe-items.rs

**Comment by workingjubilee** [comment]
@spastorino Would you please update your stabilization report to explain the finer-grained implementation choices that have been made? e.g. why `safe` is now parsed in previous editions, and whether `safe` is a restricted keyword in later editions? The RFC focused on Edition 2024, mostly.

...and is `unsafe static` now accepted outside `extern "C"`?

**Comment by workingjubilee** [comment]
...yes, without a feature gate, on a recent nightly? And beta?

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a5e84d4d6df2b38d60fe18a44e1a2087

https://rust.godbolt.org/z/qdcreaqrh

**Comment by compiler-errors** [comment]
https://github.com/rust-lang/rust/pull/127943 fixes that last part.

**Comment by spastorino** [comment]
@workingjubilee, first I've updated the stabilization report to avoid mentioning backwards compatibility and explained in terms of avoiding surprising effects.

> why `safe` is now parsed in previous editions, and whether `safe` is a restricted keyword in later editions? The RFC focused on Edition 2024, mostly.

I did a short summary because I didn't want to repeat most of what is said in the RFC. Related to this very specific thing, from the RFC:

> In all editions, items within unsafe extern blocks may be marked as safe to use.

**Comment by spastorino** [comment]
@workingjubilee let me know if do you want me to explain/change something else, I'd be happy to fix/clarify things but my premise was to avoid what it is already in the RFC other than just sticking to a very short summary here.

**Comment by workingjubilee** [comment]
Ah, I was reading the RFC as I went, but I missed that, it seems.

**Comment by traviscross** [comment]
@rfcbot fcp merge

Thanks to @spastorino for pushing this forward.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by joshtriplett** [comment]
:+1: for the stabilization. Ideally, we'd also love to see a rustc allow-by-default lint with rustfix for inserting the explicit `unsafe` (and advising people to check whether it's `safe`). That is *not* a blocker for stabilization.

**Review by compiler-errors — APPROVED** [review]

**Comment by Kobzol** [comment]
@rust-timer build 6841bd34de5dcfdae38583d02b767cc55ff92291

**Comment by compiler-errors** [comment]
Probably has to do with the ungated edition check for extern block spans. I don't think this can be fixed 🤔

**Comment by Kobzol** [comment]
Understood, thanks. I'll mark the rollup as triaged then.

@rustbot label: +perf-regression-triaged

**Pull request merged**
