### PR TITLE
Never MIR inline functions with a different instruction set

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by tmiasko** [comment]
Do you think adding a mir-opt test would be worth it, given that running it
would require a target with multiple instruction sets, so it will be
inconvenient to update in the future?

**Comment by oli-obk** [comment]
hmm... yea, the difficulty of updating the test seems to me like a too high cost for the gain of a fairly straight forward test

@bors r+ rollup

**Comment by Aaron1011** [comment]
Is this required for soundness? If so, I think we should definitely add a test.

**Comment by tmiasko** [comment]
Added a `no_core` test. That shouldn't be too onerous to update, unless someone builds LLVM without required target.

**Comment by oli-obk** [comment]
@bors r+

holy :cow: I guess we should make more use of `no_core` tests

**Pull request merged**
