### PR TITLE
book: something does happen... the test passes

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by nixpulvis** [comment]
I think it's fair to say nothing happens, as that's exactly what `assert!` does. It `panic!`s if false. The fact that tests pass when there are no panics is a secondary fact.

**Comment by Manishearth** [comment]
I agree with @nixpulvis here. The test passing is a side effect. The assert macro itself does exactly nothing if the check is true.

**Comment by tshepang** [comment]
A statement executing is not *nothing*.

**Comment by Manishearth** [comment]
>  if the argument is true, nothing happens. 

The "if the argument is true" part already handles the execution of the condition. After that, nothing happens. The assert macro is implemented as:

```
if cond {
 // empty
} else {
 panic!(message)
}
```

(well, it's probably implemented as `if !cond`, but you get the idea)

**Comment by Manishearth** [comment]
```
macro_rules! assert {
    ($cond:expr) => (
        if !$cond {
            panic!(concat!("assertion failed: ", stringify!($cond)))
        }
    );
    ($cond:expr, $($arg:tt)+) => (
        if !$cond {
            panic!($($arg)+)
        }
    );
}
```

is the exact implementation. Does nothing if the condition is true.

The test passing, like I mentioned, is a side effect of the code not panicking. assert can be used in non test code too.

**Comment by tshepang** [comment]
Ok, good to know, thanks @Manishearth.
The claim is still not needed though, and it had to take an explanation what *nothing happens* could mean. It could also be taken to mean that the test passes, that there is no panic.

**Comment by Manishearth** [comment]
It's talking about the _macro_. The macro has nothing to do with the tests.

**Comment by Manishearth** [comment]
Maybe add a note after that line: "Tests pass if nothing panics, so a test will pass only if all of its asserts evaluate to true"

**Comment by tshepang** [comment]
Something like that is mentioned 2 paragraphs above

**Comment by Manishearth** [comment]
So ... is there a need for this change?

**Comment by tshepang** [comment]
I still want the change in, but it is too small for this much discussion.

**Pull request closed without merging**
