### PR TITLE
Do not fail if --emit≠link and there’s no main fn

### LINKED ISSUE #21813: rustc should not fail if emit≠link and main does not exist
There’s no reason for the compiler to fail if `--emit≠link` is specified and main function does not exist.

Relevant code appears to be `src/librustc/middle/entry.rs`.

### PR DESCRIPTION
**Pull request by nagisa**
Fixes #21813

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you also add a test for this? I suppose it could lead to weird errors if you're generating an object file (or generating IR and then using that to make an object later), but it seems like this may be worth it.

**Comment by nagisa** [comment]
@alexcrichton done.

**Pull request merged**
