### PR TITLE
Update miri

### LINKED ISSUE #63024: `miri` no longer builds after rust-lang/rust#63015
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#63015, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #63024

r? @RalfJung

### CODE REVIEW

**Comment by JohnTitor** [comment]
Ah, highfive doesn't seem to be here.

**Comment by RalfJung** [comment]
highfive is here, they assigned me to this PR. :)

Since you did r? in the OP, there is no need for the bot to post a message.

**Comment by JohnTitor** [comment]
Add https://github.com/rust-lang/miri/commit/af7570fced59a775da78492cb20a6f22982a1268 so this should pass the tests.

**Comment by RalfJung** [comment]
It finished less than 2min after the timeout. :/

@bors retry

**Comment by RalfJung** [comment]
That's odd, it is still failing for Linux...?

All tools are out-of-sync between Windows and Linux though: https://rust-lang-nursery.github.io/rust-toolstate/. So this is likely not a Miri issue.

**Pull request merged**
