### PR TITLE
Stabilize `const_float_classify`

### LINKED ISSUE #72505: Tracking issue for `#![feature(const_float_classify)]`
Tracking issue for the `#![feature(const_float_classify)]` feature gate, which makes the following methods on `f32` and `f64` `const fn`:

- `classify`
- `is_nan`
- `is_infinite`
- `is_finite`
- `is_subnormal`
- `is_normal`
- `is_sign_positive`
- `is_sign_negative`

These require #72447 (`#![feature(const_float_bits_conv)]`), so this is transitively blocked on https://github.com/rust-lang/rust/issues/57241.

### PR DESCRIPTION
**Pull request by eduardosm**
Tracking issue: https://github.com/rust-lang/rust/issues/72505

Also reverts https://github.com/rust-lang/rust/pull/114486

Closes https://github.com/rust-lang/rust/issues/72505

Stabilized const API:

```rust
impl f32 {
    pub const fn is_nan(self) -> bool;
    pub const fn is_infinite(self) -> bool;
    pub const fn is_finite(self) -> bool;
    pub const fn is_subnormal(self) -> bool;
    pub const fn is_normal(self) -> bool;
    pub const fn classify(self) -> FpCategory;
    pub const fn is_sign_positive(self) -> bool;
    pub const fn is_sign_negative(self) -> bool;
}

impl f64 {
    pub const fn is_nan(self) -> bool;
    pub const fn is_infinite(self) -> bool;
    pub const fn is_finite(self) -> bool;
    pub const fn is_subnormal(self) -> bool;
    pub const fn is_normal(self) -> bool;
    pub const fn classify(self) -> FpCategory;
    pub const fn is_sign_positive(self) -> bool;
    pub const fn is_sign_negative(self) -> bool;
}
```

cc @rust-lang/wg-const-eval @rust-lang/libs-api

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval -- this is entirely harmless, the methods just all use already-stable const facilities.

(Team pings only work when an org member writes them, AFAIK.)

**Comment by tgross35** [comment]
> Also reverts #114486

Nit: could you put this PR link and/or the relevant commit SHAs in that commit message? It's currently just a title so no crosslinking.

**Comment by RalfJung** [comment]
The PR link is in the PR description which bors will put into the merge commit message. So I think that will be covered.

**Comment by RalfJung** [comment]
FCP passed, so this is good to go. :)

@bors r+

**Pull request merged**
