### PR TITLE
Switch `mutable_borrow_reservation_conflict` lint to deny by default

### PR DESCRIPTION
**Pull request by marmeladema**
Lint `mutable_borrow_reservation_conflict` was added about a year and a half ago in warning mode by default. Issue #59159 states that at some point, it should be set to deny by default which this PR implements.

I am mainly creating this PR to start the discussion and try to help stabilizing full `nll`.
I also don't know if we need a crater run for this kind of change?

Assigning to @pnkfelix because of the tracking issue but feel free to re-assign to whoever might be better suited to review this change.

r? @pnkfelix

### CODE REVIEW

**Comment by Aaron1011** [comment]
The crater queue is pretty small, so let's kick off a run to see what the breakage looks like.

@bors try

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
Yielding to a very small re-test of https://github.com/rust-lang/rust/pull/76130

@craterbot retry

**Comment by marmeladema** [comment]
Hello @Aaron1011 and thank to have started the crater run.

I looked at various regressions and they all seem legit. Unfortunately the 117 are individual regressions which mean there is not a handful of crate to fix but rather all of them.
Compared to other similar changes, I don't know if 117 regressions is "acceptable"? Or should I provide a fix for all of the 117 crates? I can do that but that will definitely take a while.

Unrelated question, for how long is the crater report going to be available for?

**Comment by Aaron1011** [comment]
@marmeladema: I'm not sure what amount of breakage is considered acceptable for this lint - @nikomatsakis or someone else should weigh in.

@rust-lang/infra Are Crater reports hosted indefinitely?

**Comment by pietroalbini** [comment]
> Are Crater reports hosted indefinitely?

Yes. If we're going to ever start deleting them (which we don't plan to) we'll surely keep the past couple months of reports available.

**Comment by pnkfelix** [comment]
The lang team had agreed ([described here](https://github.com/rust-lang/rust/pull/58739#issuecomment-476387184)) that we need to do a more thorough evaluation of the semantic models before we convert this to a hard error.

I think several members of the lang team would be annoyed if we turned this into a hard error simply because "its been a warning for so long." We reached the compromise that we adopted in part because we promised we would not do that.

**Comment by pnkfelix** [comment]
(However, I'm also not sure whether turning this lint to deny-by-default needs to be coupled to turning on `feature(nll)` by default? maybe I misremember, but I had thought this lint was largely independent of all the other stuff turned on by `feature(nll)`...)

**Comment by pnkfelix** [comment]
nominating for discussion at T-lang meeting, so that we can ponder when/if we are going to have time to do the follow-on work of evaluating semantic models *et cetera* that was promised here.

**Comment by joshtriplett** [comment]
I agree that we shouldn't just switch to a hard error just because time has passed.

**Comment by nikomatsakis** [comment]
Update for next week's lang-team meeting:

* As described in the tracking issue https://github.com/rust-lang/rust/issues/59159, this highlights a particular case of two-phase borrows. This pattern was initially accepted when we landed NLL but we ultimately decided to reject it after the discussion in https://github.com/rust-lang/rust/issues/56254.
* To highlight what's going on: 
    * The original 2-phase borrow RFC was intended to permit code like `v.push(v.len())`, where `v` is borrowed mutably (as part of the call to `push`) but the resulting reference is not *used* until after a call to `v.len()` has completed. So 2PB permits a shared borrow (part of `v.len()`) to occur while a mutable borrow is live, but only if that mutable borrow has not yet been *activated*.
    * However, the implementation also accepted cases where the shared borrow **preexisted** the mutable borrow. So `let s = &v; v.push(s.len());`. This case was not discussed in the RFC. It caused complications for our (in progress) models for what is correct and incorrect unsafe code, because it could not be well-modeled with a stack. This led to https://github.com/rust-lang/rust/issues/56254 being filed.
* My recollection from that discussion is that part of the agreement was that we should issue warnings/deny-by-default but before we render a final decision on this point we wanted to have some follow-up discussion. I don't see this noted anywhere, however. I believe that @joshtriplett wanted to get a firmer understanding of the stacked borrows model and what kinds of optimizations were being enabled by ruling out this pattern, given that everyone agreed the code would be nice to accept, if we could find a way to model unsafe code that was not too messy.
* I can try perhaps to loop back with @RalfJung and get a good understanding of their current thinking here, or maybe @RalfJung can leave a comment.

**Comment by nikomatsakis** [comment]
@RalfJung that's quite helpful, thank you.

**Comment by nikomatsakis** [comment]
Update from meeting:

* A crater run to see impact might be useful
* Deny by default would not immediately break existing crates, so if we want to discourage folks from this pattern it is a logical step (even if we will ultimately allow it)
* @joshtriplett to leave a comment with more questions for @RalfJung =)

**Comment by Aaron1011** [comment]
> A crater run to see impact might be useful

This was done in https://github.com/rust-lang/rust/pull/76104#issuecomment-696983238

**Comment by joshtriplett** [comment]
@RalfJung Definitely looking forward to more advancements in Stacked Borrows, but no pressure on that in general; you're doing a lot of good work.

To clarify further: are you suggesting that it'd be 6+ months before you'd be able to evaluate if this lint steering people away from this pattern is still desirable or not? This warning should really either become an error or should get phased out, depending on if the pattern is problematic. Are you saying it'd be a long time before you can determine if this pattern is problematic at all?

**Comment by nikomatsakis** [comment]
@Aaron1011 Oh, thanks! I see the impact was non-trivial -- 117 regressions. Interesting. That definitely affects my opinion.

**Comment by RalfJung** [comment]
> To clarify further: are you suggesting that it'd be 6+ months before you'd be able to evaluate if this lint steering people away from this pattern is still desirable or not? This warning should really either become an error or should get phased out, depending on if the pattern is problematic. Are you saying it'd be a long time before you can determine if this pattern is problematic at all?

Whether it is problematic is ultimately a judgment call the lang team will have to make, once we have a better idea for which optimizations it is in conflict with. Figuring out the affected optimizations will require a better aliasing model.

I hope that answers the question... I don't think I entirely understood what you were asking.

**Comment by joshtriplett** [comment]
On Mon, Oct 19, 2020 at 03:15:47PM -0700, Ralf Jung wrote:
> > To clarify further: are you suggesting that it'd be 6+ months before you'd be able to evaluate if this lint steering people away from this pattern is still desirable or not? This warning should really either become an error or should get phased out, depending on if the pattern is problematic. Are you saying it'd be a long time before you can determine if this pattern is problematic at all?
> 
> Whether it is problematic is ultimately a judgment call the lang team will have to make, once we have a better idea for which optimizations it is in conflict with. Figuring out the affected optimizations will require a better aliasing model.
> 
> I hope that answers the question... I don't think I entirely understood what you were asking.

IIRC, we originally added this lint partly at your request, because the
stacked borrows model didn't want to support this pattern, and there was
some notion that we might want to reject it in the future so we wanted
to start linting against it. (I think at the time you asked if we could
directly start rejecting this pattern, and we ended up phasing that in
via a lint rather than moving directly to rejecting it.) So before
making a decision about this lint, we wanted to get your current
thoughts.

**Comment by RalfJung** [comment]
> IIRC, we originally added this lint partly at your request, because the
stacked borrows model didn't want to support this pattern,

Right, an earlier version of Stacked Borrows supported or seemed to support two-phase borrows but only without pre-existing borrows. I think for the later version I was unable to even find a way that made those cases work, and since the entire two-phase borrow situation was very unsatisfactory anyway, I decided to focus on the more clearly understood "normal" borrows.

So... I'm afraid that's really all I got. There is some indication that two-phase borrows are easier to model when there cannot be existing reservations, but even that was not good enough for latest Stacked Borrows. Intuitively it seems to me that two-phase borrows should really benefit from a more tree-like structure where several potentially conflicting children of some tag are tracked in parallel until an actual conflict arises. But whether pre-existing reservations still pose any problem with such a model, I cannot tell.

**Comment by joshtriplett** [comment]
On Tue, Oct 20, 2020 at 02:30:58PM -0700, Ralf Jung wrote:
> > IIRC, we originally added this lint partly at your request, because the
> stacked borrows model didn't want to support this pattern,
> 
> Right, an earlier version of Stacked Borrows supported or seemed to support two-phase borrows but only without pre-existing borrows. I think for the later version I was unable to even find a way that made those cases work, and since the entire two-phase borrow situation was very unsatisfactory anyway, I decided to focus on the more clearly understood "normal" borrows.
> 
> So... I'm afraid that's really all I got. There is some indication that two-phase borrows are easier to model when there cannot be existing reservations, but even that was not good enough for latest Stacked Borrows. Intuitively it seems to me that two-phase borrows should really benefit from a more tree-like structure where several potentially conflicting children of some tag are tracked in parallel until an actual conflict arises. But whether pre-existing reservations still pose any problem with such a model, I cannot tell.

Alright. Thank you for clarifying.

We'll need to talk about this further at a future lang team meeting,
then.

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum I might be reading this wrong, but this [crater report](https://crater-reports.s3.amazonaws.com/pr-76104/index.html) appears **to me** to suggest 113 regressions due to 'mutable borrow reservation conflict". From poking at random entries they all appeared to be root regressions.

I am starting to lean towards "let's just accept this pattern". I'd be interested @RalfJung to talk a bit more about what the impact of two-phase borrows is on optimizations under the stacked borrows as currently formulated (it sounds like you consider the initial mut borrow to be a raw pointer, although reading https://github.com/rust-lang/miri/pull/695 I didn't find much documentation to that effect).

**Comment by RalfJung** [comment]
Indeed, I [consider it a raw pointer](https://github.com/rust-lang/miri/blob/9a2cfbfc0a6029944fa87372da6870e147961187/src/stacked_borrows.rs#L552-L553). So the impact on optimizations for this reference under the current model is that basically no alias-based optimizations are possible. Mutable references later created from this (like the mutable reference inside the callee) are unaffected.

**Comment by Mark-Simulacrum** [comment]
> @Mark-Simulacrum I might be reading this wrong, but this crater report appears to me to suggest 113 regressions due to 'mutable borrow reservation conflict". From poking at random entries they all appeared to be root regressions.

Yeah, taking another look I think this is right. I will note that the vast majority are GitHub repositories, many of which are advent of code or similar -- I think that likely means that the lint has indeed discouraged new uses of this pattern forming in code people are actively touching (unsurprisingly).

It seems like all of the cases this lint touched that I saw in the code examples are quite simple and usually occur on just 1-4 lines without anything all that complicated in between (if anything), leading me to feel that in practice we're not likely to lose much without the definite aliasing information (since there's not much that could be done); furthermore I'd sort of expect that perhaps the aliasing information could be derived from the code in many cases as well through local analysis, even if it is not guaranteed by the language to always be there. Maybe I'm reading too much into these patterns though.

I am also inclined to remove/silence this lint, personally.

**Comment by nikomatsakis** [comment]
Update from @rust-lang/lang meeting: 

Last week @pnkfelix mentioned they'd look into some patterns. Removing nomination for now but we don't have agreement to go forward.

**Comment by nikomatsakis** [comment]
I think we should close this PR for now. The number of regressions is non-trivial and I am very interested in whether we can make this pattern be accepted by extending stacked borrows in some way (or perhaps our compilation into MIR). If not, I would be ok going forward, but it's obviously going to require a bit of a "phasing-in".

**Pull request closed without merging**
