### PR TITLE
Migrate `pdb-alt-path`, `mismatching-target-triples` and `mingw-export-call-convention` `run-make` tests to rmake

### PR DESCRIPTION
**Pull request by Oneirical**
Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

Needs MSVC try jobs.

try-job: x86_64-mingw
try-job: x86_64-msvc

### CODE REVIEW

**Comment by Oneirical** [comment]
Sweet. The errors here had nothing to do with Windows permissions/structure, just me doing some standard silly compilation errors and not realizing it because some of these tests only run on Windows. @rustbot review

**Comment by Kobzol** [comment]
Looks good, thanks!

@bors r+

**Pull request merged**
