### PR TITLE
Add a tidy check for files with over 3,000 lines

### PR DESCRIPTION
**Pull request by varkor**
Files with a large number of lines can cause issues in GitHub (e.g. https://github.com/rust-lang/rust/issues/60015) and also tend to be indicative of opportunities to refactor into less monolithic structures.

This adds a new check to tidy to warn against files that have more than 3,000 lines, as suggested in https://github.com/rust-lang/rust/issues/60015#issuecomment-483868594. (This number was chosen fairly arbitrarily as a reasonable indicator of size.) This check can be ignored with `// ignore-tidy-filelength`.

Existing files with greater than 3,000 lines currently ignore the check, but this helps us spot when files are getting too large. (We might try to split up all files larger than this in the future, as in https://github.com/rust-lang/rust/issues/60015).

### CODE REVIEW

**Comment by varkor** [comment]
cc @rust-lang/compiler to check this is something we actually want to do.

**Comment by estebank** [comment]
Let's make sure the error has a blurb about how to disable the check (that way feature work that barely pushes a file over the edge is not stopped, but the signal is sent that the file needs restructuring).

**Comment by Centril** [comment]
This seems like an extremely awesome PR and necessary to improve the quality of rustc. In particular, the easy way to disable the check for a file provides a way for us to incrementally improve things and find the problematic files quickly.

**Comment by matthewjasper** [comment]
r=me once the compiler team is happy with this.

**Comment by varkor** [comment]
Let's very quickly check everyone's happy with this in tomorrow's meeting.

**Comment by Centril** [comment]
[The consensus](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-04-25.20.2354818/near/164178132) from the T-compiler meeting seems to be that everyone's happy with this.

**Pull request merged**
