### PR TITLE
Stabilize `slice_first_last_chunk`

### LINKED ISSUE #90091: Tracking Issue for split_array
Feature gate: `#![feature(split_array)]`

This is a tracking issue for splitting slices and arrays into constant-length arrays.

### Public API

```rust
impl<T, const N: usize> [T; N] {
    pub fn split_array_ref<const M: usize>(&self) -> (&[T; M], &[T]);
    pub fn split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T]);

    pub fn rsplit_array_ref<const M: usize>(&self) -> (&[T], &[T; M]);
    pub fn rsplit_array_mut<const M: usize>(&mut self) -> (&mut [T], &mut [T; M]);
}

impl<T> [T] {
    pub fn split_array_ref<const N: usize>(&self) -> (&[T; N], &[T]);
    pub fn split_array_mut<const N: usize>(&mut self) -> (&mut [T; N], &mut [T]);

    pub fn rsplit_array_ref<const N: usize>(&self) -> (&[T], &[T; N]);
    pub fn rsplit_array_mut<const N: usize>(&mut self) -> (&mut [T], &mut [T; N]);
}
```

### Unresolved Questions

* [ ] Naming, see https://github.com/rust-lang/rust/pull/83233#pullrequestreview-780315524
* [ ] Array functions should return `[T; N - M]`, like so:
```rust
impl<T, const N: usize> [T; N] {
    pub fn split_array<const M: usize>(self) -> ([T; M], [T; N - M]);
    pub fn split_array_ref<const M: usize>(&self) -> (&[T; M], &[T; N - M]);
    pub fn split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T; N - M]);
}
```
However, const generics is not powerful enough for this today. See https://github.com/rust-lang/rust/pull/83233#issuecomment-947542204 and https://github.com/rust-lang/rust/pull/83233#discussion_r732722222. The array functions need to be here so the slice functions can be stabilized without forward compatibility concerns.

### LINKED ISSUE #111774: Tracking Issue for `slice_first_last_chunk` feature (`slice::{split_,}{first,last}_chunk{,_mut}`)
Feature gate: `#![feature(slice_first_last_chunk)]`

This is a tracking issue for the `slice::{split_,}{first,last}_chunk{,_mut}` API.

### Public API

2024-09-06: Most of this is stable now, except for the const-ness of the `mut` methods.

```rust
impl [T] {
    pub const fn first_chunk<const N: usize>(&self) -> Option<&[T; N]>;
    pub const fn first_chunk_mut<const N: usize>(&mut self) -> Option<&mut [T; N]>;
    pub const fn last_chunk<const N: usize>(&self) -> Option<&[T; N]>;
    pub const fn last_chunk_mut<const N: usize>(&mut self) -> Option<&mut [T; N]>;
    pub const fn split_first_chunk<const N: usize>(&self) -> Option<(&[T; N], &[T])>;
    pub const fn split_first_chunk_mut<const N: usize>(&mut self) -> Option<(&mut [T; N], &mut [T])>;
    pub const fn split_last_chunk<const N: usize>(&self) -> Option<(&[T; N], &[T])>;
    pub const fn split_last_chunk_mut<const N: usize>(&mut self) -> Option<(&mut [T; N], &mut [T])>;
}
```

Note that this mirrors the existing, already-stabilised API:

```rust
impl [T] {
    pub const fn first(&self) -> Option<&T>;
    pub const fn first_mut(&mut self) -> Option<&mut T>;
    pub const fn last(&self) -> Option<&T>;
    pub const fn last_mut(&mut self) -> Option<&mut T>;
    pub const fn split_first(&self) -> Option<(&T, &[T])>;
    pub const fn split_first_mut(&mut self) -> Option<(&mut T, &mut [T])>;
    pub const fn split_last(&self) -> Option<(&T, &[T])>;
    pub const fn split_last_mut(&mut self) -> Option<(&mut T, &mut [T])>;
}
```

### Steps / History

- [x] API change proposal (ACP)[^1]: rust-lang/libs-team#69
- [x] Implementation: #95198
- [ ] Final comment period (FCP)[^2]
- [ ] Wait until https://github.com/rust-lang/rust/issues/101804 is stable
- [ ] Stabilization PR

### Unresolved Questions

- [ ] Is this the best order for the tuple in `split_last_chunk`?  Consistency with `split_last` would have it be `-> Option<(&[T;N], &[T])>` as was ACPed, but it might be confusing to have the two slice-like things in the opposite order from every other API I can think of that returns two subslices of the original.  In https://github.com/rust-lang/rust/pull/95198#discussion_r1204824761, @scottmcm expected `-> Option<(&[T;N], &[T])>` for `split_first_chunk`, but for it to be `-> Option<(&[T], &[T;N])>` in `split_last_chunk` so the tuple is "in order", in some sense.
- ...

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html
[^2]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by tgross35**
This PR does a few different things based around stabilizing `slice_first_last_chunk`. They are split up so this PR can be by-commit reviewed, I can move parts to a separate PR if desired.

This feature provides a very elegant API to extract arrays from either end of a slice, such as for parsing integers from binary data.

## Stabilize `slice_first_last_chunk`

ACP: https://github.com/rust-lang/libs-team/issues/69
Implementation: https://github.com/rust-lang/rust/issues/90091
Tracking issue: https://github.com/rust-lang/rust/issues/111774

This stabilizes the functionality from https://github.com/rust-lang/rust/issues/111774:

```rust
impl [T] {
    pub const fn first_chunk<const N: usize>(&self) -> Option<&[T; N]>;
    pub fn first_chunk_mut<const N: usize>(&mut self) -> Option<&mut [T; N]>;
    pub const fn last_chunk<const N: usize>(&self) -> Option<&[T; N]>;
    pub fn last_chunk_mut<const N: usize>(&mut self) -> Option<&mut [T; N]>;
    pub const fn split_first_chunk<const N: usize>(&self) -> Option<(&[T; N], &[T])>;
    pub fn split_first_chunk_mut<const N: usize>(&mut self) -> Option<(&mut [T; N], &mut [T])>;
    pub const fn split_last_chunk<const N: usize>(&self) -> Option<(&[T], &[T; N])>;
    pub fn split_last_chunk_mut<const N: usize>(&mut self) -> Option<(&mut [T], &mut [T; N])>;
}
```

Const stabilization is included for all non-mut methods, which are blocked on `const_mut_refs`. This change includes marking the trivial function `slice_split_at_unchecked` const-stable for internal use (but not fully stable).

## Remove `split_array` slice methods

Tracking issue: https://github.com/rust-lang/rust/issues/90091
Implementation: https://github.com/rust-lang/rust/pull/83233#pullrequestreview-780315524

This PR also removes the following unstable methods from the `split_array` feature, https://github.com/rust-lang/rust/issues/90091:

```rust
impl<T> [T] {
    pub fn split_array_ref<const N: usize>(&self) -> (&[T; N], &[T]);
    pub fn split_array_mut<const N: usize>(&mut self) -> (&mut [T; N], &mut [T]);

    pub fn rsplit_array_ref<const N: usize>(&self) -> (&[T], &[T; N]);
    pub fn rsplit_array_mut<const N: usize>(&mut self) -> (&mut [T], &mut [T; N]);
}
```

This is done because discussion at #90091 and its implementation PR indicate a strong preference for nonpanicking APIs that return `Option`. The only difference between functions under the `split_array` and `slice_first_last_chunk` features is `Option` vs. panic, so remove the duplicates as part of this stabilization.

This does not affect the array methods from `split_array`. We will want to revisit these once `generic_const_exprs` is further along.

## Reverse order of return tuple for `split_last_chunk{,_mut}`

An unresolved question for #111774 is whether to return `(preceding_slice, last_chunk)` (`(&[T], &[T; N])`) or the reverse (`(&[T; N], &[T])`), from `split_last_chunk` and `split_last_chunk_mut`. It is currently implemented as `(last_chunk, preceding_slice)` which matches `split_last -> (&T, &[T])`. The first commit changes these to `(&[T], &[T; N])` for these reasons:

- More consistent with other splitting methods that return multiple values: `str::rsplit_once`, `slice::split_at{,_mut}`, `slice::align_to` all return tuples with the items in order
- More intuitive (arguably opinion, but it is consistent with other language elements like pattern matching `let [a, b, rest @ ..] ...`
- If we ever added a varidic way to obtain multiple chunks, it would likely return something in order: `.split_many_last::<(2, 4)>() -> (&[T], &[T; 2], &[T; 4])`
- It is the ordering used in the `rsplit_array` methods

I think the inconsistency with `split_last` could be acceptable in this case, since for `split_last` the scalar `&T` doesn't have any internal order to maintain with the other items.

## Unresolved questions

Do we want to reserve the same names on `[u8; N]` to avoid inference confusion? https://github.com/rust-lang/rust/pull/117561#issuecomment-1793388647

---

`slice_first_last_chunk` has only been around since early 2023, but `split_array` has been around since 2021.

@rustbot label -T-libs +T-libs-api -T-libs +needs-fcp
cc @rust-lang/wg-const-eval, @scottmcm who raised this topic, @clarfonthey implementer of `slice_first_last_chunk` @jethrogb implementer of `split_array`

Zulip discussion: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Stabilizing.20array-from-slice.20*something*.3F

Fixes: #111774

### CODE REVIEW

**Comment by clarfonthey** [comment]
I'm fine with reversing the order, although it is quite unfortunate that `split_last` is in the order it is. Ultimately, we'll have to deal with the inconsistency, since folks seem to prefer this version.

**Comment by tgross35** [comment]
> I'm fine with reversing the order, although it is quite unfortunate that `split_last` is in the order it is. Ultimately, we'll have to deal with the inconsistency, since folks seem to prefer this version.

I completely agree :( I think it's better to embrace the consistency with other ordered splitting things and probably the path we would prefer to keep in the future, but it is unfortunate that the inconsistency is with such a similarly named method.

**Comment by tgross35** [comment]
r? libs-api

**Comment by Xiretza** [comment]
Is it possible to stabilize these in a way that keeps the door open for infallible counterparts on arrays (once `generic_const_exprs` is viable)? It makes no sense to return `Option` for those methods, since the bounds check can be done entirely at compile time, but if the slice methods are stabilized like this, auto-deref means that the corresponding methods on arrays would need to be named differently. I think just adding unstable placeholder methods of the same name on arrays would be enough?

**Comment by tgross35** [comment]
That sounds reasonable. If we are happy with these names, I can just adjust the items from `split_array_ref` to match.

Although on second thought... I'm not sure the first_chunk / last_chunk names work quite as well when you wind up with two "chunks" (meaning array), rather than one chunk and one slice. Something to think about I suppose

**Comment by joshtriplett** [comment]
We discussed this in today's libs-api meeting, and agreed that we want to do the proposed stabilizations and changes:

@rfcbot merge

**Comment by compiler-errors** [comment]
@joshtriplett: I don't believe this requires a T-compiler FCP.

**Comment by compiler-errors** [comment]
@rfcbot fcp cancel

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by clarfonthey** [comment]
Small thing for clarity, even though the issue description clarifies it swaps the order of the `last` return tuples, it still shows the old order in the API summary.

**Comment by Xiretza** [comment]
I don't think the open concern in https://github.com/rust-lang/rust/pull/117561#issuecomment-1793388647 has been addressed?

**Comment by ChrisDenton** [comment]
> Do we want to reserve the same names on [u8; N] to avoid inference confusion?

This was discussed in the meeting but was decided that it would be better to have a different name for an array method. As you say, an array method would be infallible and checked at compile time which means it would have a different function signature. It's generally more confusing to have a type shadow a function on its deref target, except as purely an optimization.

**Comment by tgross35** [comment]
> Small thing for clarity, even though the issue description clarifies it swaps the order of the `last` return tuples, it still shows the old order in the API summary.

Thanks, I updated it

**Comment by tgross35** [comment]
@RalfJung / @oli-obk could you double check my const note from the top post?

> The const stabilizations include `#[rustc_allow_const_fn_unstable(slice_split_at_unchecked)]` which is an unstable function that uses pointer math (if there is a way to mark the `slice_split_at_unchecked` const stable for internal use, that may be better than using the attribute).

**Comment by RalfJung** [comment]
Does it work to make `slice_split_at_unchecked` const-stable while still being `#[unstable]`? That's what we do for intrinsics that we want to expose indirectly; not sure if our const-stability checks support doing the same for regular functions.

**Pull request merged**
