### PR TITLE
Add a `write_char` method to `std::fmt::Write`

### PR DESCRIPTION
**Pull request by SimonSapin**
as accepted in [RFC 526](https://github.com/rust-lang/rfcs/blob/master/text/0526-fmt-text-writer.md).

Note that this brand new method is marked as **stable**. I judged this safe enough: it’s simple enough that it’s very unlikely to change. Still, I can mark it unstable instead if you prefer.

r? @alexcrichton

### CODE REVIEW

**Comment by aturon** [comment]
I'm fine with this coming in as `#[stable]` (as you say, it's very unlikely to change).

That said, I don't think we'll cherry-pick this for 1.0, so can you please put `since = "1.1.0"`?

**Comment by SimonSapin** [comment]
Done. Is it still `feature = "rust1"`?

**Comment by Valloric** [comment]
No tests? :(

**Comment by ncm** [comment]
I am kind of out of the loop, here.  Is Rust perpetuating C's confusion of octets with characters?  Or does write_char write out enough octets to form a code point (which we can, informally, call a character because it's close enough for most purposes)?  If it just writes a byte, that seems like a worthy goal, but then the name is wrong.

**Comment by SimonSapin** [comment]
@ncm: I don’t think there is such a confusion. A `char` is a [Unicode scalar value](http://www.unicode.org/glossary/#unicode_scalar_value). The point of `std::fmt::Write` (as opposed to `std::io::Write`) is to only accept well-formed Unicode data, not arbitrary bytes.

[My goal](https://github.com/SimonSapin/rust-std-candidates/tree/0a0a9ccb3b3#the-textwriter-trait) here is to use this trait not just for formatting, but as a general-purpose Unicode-based stream. The default implementation of `write_char` is to write up to four bytes with `write_str`, but it could be the reverse (`write_char` is fundamental` and `write_str` uses it) in an implementation that’s not based on UTF-8.

**Comment by SimonSapin** [comment]
@Valloric My bad. #24688 adds a test.

**Pull request merged**
