### PR TITLE
Keep last redundant linker flag, not first

### PR DESCRIPTION
**Pull request by dcreager**
When a library (L1) is passed to the linker multiple times, this is sometimes purposeful: there might be several other libraries in the linker command (L2 and L3) that all depend on L1.  You'd end up with a (simplified) linker command that looks like:

```
-l2 -l1 -l3 -l1
```

With the previous behavior, when rustc encountered a redundant library, it would keep the first instance, and remove the later ones, resulting in:

```
-l2 -l1 -l3
```

This can cause a linker error, because on some platforms (e.g. Linux), the linker will only include symbols from L1 that are needed *at the point it's referenced in the command line*.  So if L3 depends on additional symbols from L1, which aren't needed by L2, the linker won't know to include them, and you'll end up with "undefined symbols" errors.

A better behavior is to keep the *last* instance of the library:

```
-l2 -l3 -l1
```

This ensures that all "downstream" libraries have been included in the linker command before the "upstream" library is referenced.

Fixes rust-lang#47989

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR @dcreager! 

I'm a little worried about this though in that libraries can change name/link kind via CLI flags, so it seems like the 'kind' of a library could change as we process it silently after this change? I think it sounds right to me to move everything to the end of the command line, but I think we may wish to keep the original warning if the kind is being updated perhaps?

**Comment by dcreager** [comment]
Thanks for the feedback Alex!  If I'm reading the old code right, we didn't print out the warning before if the kind changed; it was only printed if the second library reference was truly redundant.

**Comment by dcreager** [comment]
Sure thing!  The original problem that this is trying to fix is some linker errors when you have a particular pattern of dependencies in some C/C++ code.  I had put together minimal repro in [this repo](/dcreager/rust-cc-linking).

On Mac, the linker errors never occur.  On Linux, the linker error occurs before this patch, but not after.  For both platforms, a "redundant linker flag" warning was printed out before, but not after.

<details><summary>Before (Mac)</summary>

```
$ cargo build
   Compiling cc v1.0.26
   Compiling cc-02-broken v0.1.0 (/Users/dcreager/git/rust-cc-linking/cc-02-broken)
   Compiling cc-01-works-by-accident v0.1.0 (/Users/dcreager/git/rust-cc-linking/cc-01-works-by-accident)                                                                     
warning: redundant linker flag specified for library `c++`

warning: redundant linker flag specified for library `c++`

    Finished dev [unoptimized + debuginfo] target(s) in 3.13s
```
</details>

<details><summary>Before (Linux)</summary>

```
$ cargo build
    Updating crates.io index
  Downloaded cc v1.0.28
   Compiling cc v1.0.28
   Compiling cc-02-broken v0.1.0 (/home/dcreager/git/rust-cc-linking/cc-02-broken)
   Compiling cc-01-works-by-accident v0.1.0 (/home/dcreager/git/rust-cc-linking/cc-01-works-by-accident)
warning: redundant linker flag specified for library `stdc++`

warning: redundant linker flag specified for library `stdc++`

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.1kohxk4oy5bpc1tz.rcgu.o" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.1kp16pt7op8wd113.rcgu.o" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.3l6cjvlvoh2c3so3.rcgu.o" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.3nhkg8zoprl8ydjh.rcgu.o" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.3sj4jtttlglzuhf6.rcgu.o" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.4po5c5g0wu2dwvt4.rcgu.o" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.50dua0cq8wfcaoc6.rcgu.o" "-o" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d" "/home/dcreager/git/rust-cc-linking/target/debug/deps/cc_02_broken-3cc2faff0ce9900d.h8uijmbpxrzuyns.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/dcreager/git/rust-cc-linking/target/debug/deps" "-L" "/home/dcreager/git/rust-cc-linking/target/debug/build/cc-02-broken-b6be909df134df9e/out" "-L" "/home/dcreager/git/rust-cc-linking/target/debug/build/cc-02-broken-b6be909df134df9e/out" "-L" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lsmall" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lstdc++" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lbig" "-Wl,--no-whole-archive" "-Wl,--start-group" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-296aebc3a1e4ecfc.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-8cfe07ca425de5e2.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-8a74789e627c1a40.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-7e3f00e10075cd58.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-d3b3d6193d1b05b1.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-4c47fecb36fc2925.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c0c586c7cb2de27a.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-f1719f3d136282db.rlib" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-b22b3fc53f39823e.rlib" "-Wl,--end-group" "/home/dcreager/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ec6cc32e99245114.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: /home/dcreager/git/rust-cc-linking/target/debug/build/cc-02-broken-b6be909df134df9e/out/libbig.a(big.o): in function `big_function':
          /home/dcreager/git/rust-cc-linking/cc-02-broken/src/big.cc:8: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
          /usr/bin/ld: /home/dcreager/git/rust-cc-linking/cc-02-broken/src/big.cc:12: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(char const*)'
          /usr/bin/ld: /home/dcreager/git/rust-cc-linking/cc-02-broken/src/big.cc:14: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(char const*)'
          /usr/bin/ld: /home/dcreager/git/rust-cc-linking/cc-02-broken/src/big.cc:16: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
          /usr/bin/ld: /home/dcreager/git/rust-cc-linking/cc-02-broken/src/big.cc:8: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
          /usr/bin/ld: /home/dcreager/git/rust-cc-linking/cc-02-broken/src/big.cc:8: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
          /usr/bin/ld: /home/dcreager/git/rust-cc-linking/target/debug/build/cc-02-broken-b6be909df134df9e/out/libbig.a(big.o):(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `cc-02-broken`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
</details>

<details><summary>After (both)</summary>

```
$ cargo +local build
   Compiling cc v1.0.26
   Compiling cc-01-works-by-accident v0.1.0 (/Users/dcreager/git/rust-cc-linking/cc-01-works-by-accident)                                                                     
   Compiling cc-02-broken v0.1.0 (/Users/dcreager/git/rust-cc-linking/cc-02-broken)
    Finished dev [unoptimized + debuginfo] target(s) in 2.77s
```
</details><p>

I'm not familiar with changing the link type so I don't have any examples of that at my fingertips, but I'll try to put together a minimal example for that, too.

**Comment by dcreager** [comment]
Got a [before/after](/dcreager/rust-cc-linking/tree/master/cc-03-change-link-kind) for the "change library kind" behavior:

<details><summary>Before</summary>

```
$ cargo build -p cc-03-change-link-kind
   Compiling cc-03-change-link-kind v0.1.0 (/Users/dcreager/git/rust-cc-linking/cc-03-change-link-kind)                                                                       
    Finished dev [unoptimized + debuginfo] target(s) in 1.02s
```
</details>

<details><summary>After</summary>

```
$ cargo +local build -p cc-03-change-link-kind 
   Compiling cc-03-change-link-kind v0.1.0 (/Users/dcreager/git/rust-cc-linking/cc-03-change-link-kind)
    Finished dev [unoptimized + debuginfo] target(s) in 1.03s
```
</details><p>

That build script has a [flag](https://github.com/dcreager/rust-cc-linking/blob/a2f6b012bac907aaba58218cf108023b473a7520/cc-03-change-link-kind/build.rs#L13-L16) that updates the kind for the `small` library, and there is no warning either before or after.

**Comment by alexcrichton** [comment]
Ok thanks for the investigation! I'm realizing now I'm completely misreading the code, I thought it warned on `changed`, but actually it warns on `!changed`. My bad!

Out of an abundance of caution around linking things I'd like to run this through crater to ensure that we don't have any unexpected breakage. Linkage is always super subtle and really hard to predict what or what won't regress lots. I think this change is right, but would be good to be safe too!

@bors: try

**Comment by alexcrichton** [comment]
@craterbot run start=master#d9a2e3b1ccf16c6d43f56f503bd80c1ad137d523 end=try#5ce78cbe7028b830a57eb1611aaf93851a11929e mode=build-only

**Comment by pietroalbini** [comment]
Uhhh, wut.

@craterbot retry-report

**Comment by alexcrichton** [comment]
Ok looks like the only failure is spurious, or at least pretty unlikely to be related to this PR! 

In that case the final thing I'd wonder is if it would be possible to write a test to accompany this change? Such a test would probably be a run-make-fulldeps test I think

**Comment by Dylan-DPC** [comment]
ping from triage @dcreager any updates on this?

**Comment by Dylan-DPC** [comment]
ping from triage @dcreager 
Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again! Thanks for taking the time to contribute :)

**Comment by dcreager** [comment]
Sorry for the delay, life intervened!  I've pushed up a new commit with the requested test case, and verified that the test fails on `master` and passes on the PR branch.  Can we re-open this PR?  Or do I need to create a new PR now that this one is closed?

**Comment by Dylan-DPC** [comment]
I will reopen it no worries

**Comment by dcreager** [comment]
Thanks!

**Comment by kennytm** [comment]
@bors r-

The test `run-make-fulldeps\redundant-libs` failed on i686-msvc-1, likely legit. 

```
cl : Command line warning D9024 : unrecognized source file type 'C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs/libfoo.o', object file assumed
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Community\\VC\\Tools\\MSVC\\14.16.27012\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" "/LIBPATH:C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs\\main.main.7rcbfp3g-cgu.0.rcgu.o" "C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs\\main.main.7rcbfp3g-cgu.1.rcgu.o" "C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs\\main.main.7rcbfp3g-cgu.2.rcgu.o" "C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs\\main.main.7rcbfp3g-cgu.3.rcgu.o" "C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs\\main.main.7rcbfp3g-cgu.4.rcgu.o" "/OUT:C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs\\main.exe" "C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs\\main.4s37gsrti678ik8u.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/LIBPATH:C:/projects/rust/build/i686-pc-windows-msvc/test/run-make-fulldeps/redundant-libs/redundant-libs" "/LIBPATH:C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "bar.lib" "baz.lib" "foo.lib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libstd-9d3139aeef048807.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libpanic_unwind-e382974e690867be.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_demangle-6870de6f84dc6f64.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libunwind-1c9bbcee063e191d.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liblibc-93028efbe611c4da.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liballoc-f6dbb16f8c089c66.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_core-7b48d440fd6ff391.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcore-d9b7dce2bba244f9.rlib" "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage2\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcompiler_builtins-1de7c844b60e2faf.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'foo.lib'
```

**Comment by dcreager** [comment]
I pushed up a fix that I think might fix the Windows build error...is there a way for me to re-run the test on appveyor to double-check?

**Comment by alexcrichton** [comment]
Hm this is probably just gonna want to ignore the test on Windows. While it's possible to get the test working I don't think the most recent commit is going to fix the above error, and it'll likely require some local fiddling to make sure everything is aligned

**Comment by dcreager** [comment]
> Hm this is probably just gonna want to ignore the test on Windows.

Done!  (I think)

**Comment by kennytm** [comment]
@bors retry 

Yield priority for #59298

**Pull request merged**
