### PR TITLE
Clarify pattern-matching usefulness algorithm

### PR DESCRIPTION
**Pull request by Nadrieril**
This PR clarifies a bit the usefulness algorithm by emphasizing that each row of the matrix can be seen as a sort of stack from which we pop constructors. It also moves code around to increase separation of concerns.

This is part of my splitting of https://github.com/rust-lang/rust/pull/65160 into smaller PRs.

### CODE REVIEW

**Comment by Centril** [comment]
It would be difficult for you to rebase your way out of the first rustfmt commit now, but as a note for the future, please avoid running rustfmt unless a file contains entirely new content. :)

**Comment by Nadrieril** [comment]
@Centril Oh, I had understood that running rustfmt was ok from reading this bit of the rustc-guide: https://rust-lang.github.io/rustc-guide/conventions.html#how-to-structure-your-pr

**Comment by Centril** [comment]
Yes that definitely should be updated. :)

**Comment by varkor** [comment]
We should check this to make sure this doesn't reintroduce the regression from the previous PR.

@bors try

**Comment by varkor** [comment]
@rust-timer queue

**Comment by Nadrieril** [comment]
The small performance regression was due to a `filter_map` being accidentally converted to `flat_map`.  It should be fixed now.

**Pull request merged**
