### PR TITLE
Extend compiletest to support subdirectories

### PR DESCRIPTION
**Pull request by nikomatsakis**
You can now group tests into directories like `run-pass/borrowck` or `compile-fail/borrowck`. By default, all `.rs` files within any directory are considered tests: to ignore some directory, create a placeholder file called `compiletest-ignore-dir` (I had to do this for several existing directories).

r? @alexcrichton 
cc @brson

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hopefully we can use this to make it so that `compile-fail` and `run-pass` can actually be *listed* in GH again rather than surpassing some "don't show me this" threshold. :)

**Comment by pnkfelix** [comment]
Sweet!

We should move all of the internal data checking tests that use `rustc_fail` into their own dedicated sub directory after this lands!

**Comment by nikomatsakis** [comment]
@pnkfelix yeah, I was thinking that it'd be nice to:

- move the existing ad-hoc subdirectories into their own subdirectories, so that things are more obviously grouped;
- deprecate the existing auxiliary system for cross-crate tests and instead somehow package the crate together with subcrates in a subdirectory (that might require a bit more work though)

**Comment by nikomatsakis** [comment]
I want to do something like the latter point for incr. comp. tests, so I might wind up adding support for it, or at least the groundwork.

**Comment by sanxiyn** [comment]
Sorry to grumble here, but now I can't avoid feeling #20796 was unjustly closed.

**Comment by pnkfelix** [comment]
@sanxiyn fixed!

(I am kidding;  I do understand your underlying message here.   But,  to be fair,  these things happen,  I don't think amy ill will was meant,  and a closed issue with no comments beyond the description does not represent a huge amount of lost effort, at least compared to say if that had been a PR of yours that had been closed,  right?)

**Comment by steveklabnik** [comment]
These errors seem very odd:

```
C:/bot/slave/auto-win-gnu-64-nopt-t/build/src/test/compile-fail/borrowck\borrowck-while-cond.rs:13:11: 13:12 error: use of possibly uninitialized variable: `x` [E0381]
C:/bot/slave/auto-win-gnu-64-nopt-t/build/src/test/compile-fail/borrowck\borrowck-while-cond.rs:13     while x { } //~ ERROR use of possibly uninitialized variable: `x`
                                                                                                             ^
C:/bot/slave/auto-win-gnu-64-nopt-t/build/src/test/compile-fail/borrowck\borrowck-while-cond.rs:13:11: 13:12 help: run `rustc --explain E0381` to see a detailed explanation
error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
@steveklabnik it must be breaking because of the `\` messing up a regex or something...

**Comment by Manishearth** [comment]
(rollup)

**Comment by nikomatsakis** [comment]
@alexcrichton I think I have a fix to this problem

**Comment by alexcrichton** [comment]
@bors: r-

Maybe I'll stop blindly retrying things one day

**Comment by pitdicker** [comment]
I think the problem with auto-win-gnu-64-nopt-t is the same I had with #29497.
In `run_rustdoc_test` there is a `remove_dir_all` where the result is ignored, directly followed by `ensure_dir`.
This is currently racy on Windows...

**Comment by pitdicker** [comment]
Oops, of course not (`doctest` gives it away). But I have a branch that should remove the race problem with `create_dir_all`. Time to finish it.

**Pull request merged**
