### PR TITLE
chore: Bump compiler_builtins

### LINKED ISSUE #118079: (potential?) bug: AVR - Incorrect f64 handling
Hi there! I encountered a weird situation when writing a device driver using `embedded-hal`. Despite getting correct temperature readings in byte form from my thermocouple converter, all readings were incorrect after casting them to `f64` floats and applying some fundamental transformations.

After much confusion, I tried using `f32` instead and found it worked perfectly!

However, I knew the transformations should be correct either way: I tested this exact setup and formula using Linux and the `spidev` crate. 

That led me to test those transformations on a few different machines. Please take a look at the results below to gain better insight.

- Arduino Device
	- [Source code repo](https://github.com/onkoe/avr_f64_testing)
	- [Arduino MEGA 2560 R3 results](https://gist.github.com/onkoe/2d9936125812f917d2cbf5ec8e9c42c1)
- Other machines
	- [Shared source code](https://gist.github.com/onkoe/3cc2977cfc891711340da17ca23c9f49) for all below
	- MacBook Pro M1 on macOS and Asahi Linux (`aarch64`)
		-  Linux (`aarch64-unknown-linux-gnu`) [results](https://gist.github.com/onkoe/1eda11e69a75d6018a1057ab30bc3070)
		- macOS (`aarch64-apple-darwin`) [results](https://gist.github.com/onkoe/0de388b4be57ffad23b92e44e22169f8)
	- Ryzen desktop machine running Linux (`x86_64-unknown-linux-gnu`)[results](https://gist.github.com/onkoe/38f5ce12407f4118fd7f42900c03fad5)
	- Milk-V Duo (`riscv64gc-unknown-linux-musl`) [results](https://gist.github.com/onkoe/11313dbefb18418f916b65f6ac64381d)
	- I can do more if you'd like!

If there's any additional context I can give, or checking to be done, please let me know, and I'll happily look into it!

Also, I did check the `ufmt_float` crate to see if it was working properly! I assume that since the `f64 as u32` and ufmt_float'd `f64`are the same, it must be an issue with `f64` itself. Please see [the source](https://gist.github.com/onkoe/890253ce431e167fb4f9cfe219a48ead) and [serial output](https://gist.github.com/onkoe/703e76e64c42e84d93f2ef4be4d5dc50) of the original test to get more info.

Thank you for taking a look at my problem!

### PR DESCRIPTION
**Pull request by Patryk27**
Actually closes https://github.com/rust-lang/rust/issues/118079.

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? libs

**Comment by Patryk27** [comment]
cc @joshtriplett 👀

**Review by dtolnay — APPROVED** [review]
Thank you!

[Nils reviewed this also.](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/nils'.20reviews)

**Pull request merged**
