### PR TITLE
rustc_metadata: Make crate loading fully speculative

### LINKED ISSUE #55103: Speculative crate loading is not speculative enough
Speculative crate loading is performed as a part of speculative name resolutions (`fn maybe_process_path_extern`) which is used for various import suggestions, lints and similar things.

It's supposed to be silent and return `None` if the crate cannot be loaded, however it still reports an error if the crate path doesn't exist.
This shouldn't happen and crate path errors should be delayed until we know whether the crate loading is speculative or not.

After this issue is fixed, the test change in https://github.com/rust-lang/rust/pull/55102 needs to be reverted.

cc @davidtwco @eddyb

### LINKED ISSUE #56590: Spurious attempt to load a crate resulting in "multiple rlib candidates for `debug_unreachable` found".
I've reduced a triggering example to this:
```rust
use a::A;
type B<'a, T> = C<&'a T>;
```
Producing ([on playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=67d1e5afa43f3b28e938d58338479015), in Rust 2018 mode, only on nightly):
```
error[E0465]: multiple rlib candidates for `debug_unreachable` found
  |
note: candidate #1: /playground/target/debug/deps/libdebug_unreachable-dc2ba43f474707f3.rlib
note: candidate #2: /playground/target/debug/deps/libdebug_unreachable-fedb7fe62f71c3f0.rlib
```

The names in the testcase appear to not matter, but I can't figure out why both a lifetime and a type parameter need to be present, or any of the other details.

My guess this is from the `rustc_resolve` speculative loading of crates, to give better suggestions, which I must've not made foolproof (I *thought* I made all the errors lazy, but maybe this from a different spot that I missed).

cc @petrochenkov

### PR DESCRIPTION
**Pull request by petrochenkov**
Instead of reporting `span_err`s on the spot crate loading errors are now wrapped into the `CrateError` enum and returned, so they are reported only at the top level `resolve_crate` call, and not reported at all if we are resolving speculatively with `maybe_resolve_crate`.

As a result we can attempt loading crates for error recovery (e.g. import suggestions) without any risk of producing extra errors.
Also, this means better separation between error reporting and actual logic.

Fixes https://github.com/rust-lang/rust/issues/55103
Fixes https://github.com/rust-lang/rust/issues/56590

### CODE REVIEW

**Review by matthewjasper — APPROVED** [review]
This looks good, r=me with conflicts resolved.

**Comment by Mark-Simulacrum** [comment]
@rust-timer make-pr-for 43ba8409d7c7f93d6f0b3c22fe1b193788ff6162

**Comment by petrochenkov** [comment]
This PR shouldn't affect performance in theory, it can potentially execute less code but only when errors are reported.

**Comment by Mark-Simulacrum** [comment]
It was noted as a candidate for performance changes by @nnethercote in #74493; I'm also partially using this as a way to test the tooling for the auto-testing of already landed PRs.

**Pull request merged**
