### PR TITLE
Unify lints handling in rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This is a small cleanup. The goal is to unify a bit things to make the reading simpler.

r? @kinnison 

cc @rust-lang/rustdoc

### CODE REVIEW

**Review by kinnison — COMMENTED** [review]
While this is tidier, I think I'd benefit from a bit of documentation on the purpose and meaning of the arguments to, and results of, the `init_lints()` function.  I appreciate the behaviour doesn't appear to have changed, but that doesn't mean I understand it.

**Comment by GuillaumeGomez** [comment]
Good point, thanks for bringing it up! I'll document the function to make it as clear as possible.

**Comment by GuillaumeGomez** [comment]
I added more documentation to explain what's going on.

**Review by kinnison — APPROVED** [review]

**Comment by kinnison** [comment]
That doc helps me understand a good bit better, thanks.

@bors r+

**Pull request merged**
