### PR TITLE
Add MaybeUninit memset test

### LINKED ISSUE #96274: [MaybeUninit::uninit(); N] memsets memory
I tried this code (from https://github.com/rust-lang/rust/pull/93668#issuecomment-1104798567):

```rust
let mut p = [MaybeUninit::<u8>::uninit(); 571];
// VS
let mut p = MaybeUninit::<[u8; 571]>::uninit();
```

Godbolts: https://godbolt.org/z/341fEjqMd, https://godbolt.org/z/K9dMx8Whr

I expected to see this happen: no memset.

Instead, this happened: uninitialized memory is not actually uninitialized.

The docs explicitly say that these two should be equivalent: https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html#method.uninit_array

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Closes #96274

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
I'm fine just letting this sit until August FYI.

**Comment by JohnCSimon** [comment]
ping from triage:
@SUPERCILEX 
Returning to you to address broken build


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot author

**Comment by SUPERCILEX** [comment]
@JohnCSimon looks like llvm 13 is still used in CI even though #99464 happened, so I added a `// min-llvm-version: 15.0`. Is that fine? E.g. will the test actually be run at some point by CI on llvm 15?

**Pull request merged**
