### PR TITLE
Shrink `StatementKind`

### PR DESCRIPTION
**Pull request by nnethercote**
`StatementKind` occurs in significant amounts in Massif profiles.

### CODE REVIEW

**Comment by nnethercote** [comment]
Some `max-rss` results:
```
ucd-check
        avg: -2.0%      min: -4.3%      max: 1.4%
style-servo-check
        avg: -0.7%      min: -2.6%      max: 0.1%
webrender-check
        avg: -0.9%      min: -2.6%      max: -0.0%
cargo-check
        avg: -0.9%      min: -2.3%      max: -0.1%
piston-image-check
        avg: -0.7%      min: -1.8%      max: 0.0%
html5ever-check
        avg: -0.4%      min: -1.8%      max: 0.9%
regex-check
        avg: -0.4%      min: -1.7%      max: -0.0%
tuple-stress-check
        avg: 1.1%       min: -0.8%      max: 1.7%
sentry-cli-check
        avg: -0.6%      min: -1.6%      max: -0.1%
helloworld-check
        avg: -0.4%      min: -1.6%      max: 0.3%
serde-check
        avg: -0.8%      min: -1.6%      max: -0.2%
ripgrep-check
        avg: -0.7%      min: -1.4%      max: -0.1%
rust-unic-check
        avg: 0.1%       min: -0.8%      max: 1.3%
unify-linearly-check
        avg: -0.5%      min: -1.3%      max: 0.1%
crates.io-check
        avg: -0.6%      min: -1.3%      max: -0.2%
clap-rs-check
        avg: -0.5%      min: -1.2%      max: -0.0%
coercions-check
        avg: -0.3%?     min: -1.1%?     max: 0.2%? 
ctfe-stress-check
        avg: -0.5%?     min: -1.1%?     max: -0.2%?
futures-check
        avg: -0.4%      min: -1.0%      max: 0.0%
```
The instruction counts are mostly unchanged, but I will do a rust-timer run just to double check that.

**Comment by nagisa** [comment]
@nnethercote since you’re there, could you try making `Vec` in `StatementKind::Validate` a `Box<[]>` as well? In general nothing in MIR needs to be mutable as far as I can tell (since it is not usually mutable in place).

**Comment by nnethercote** [comment]
@rust-timer build c4a65be4c78642300db4949e944a5da3b5ecb33a

**Comment by nnethercote** [comment]
> could you try making `Vec` in `StatementKind::Validate` a `Box<[]>` as well?

It doesn't feel to me like a useful change, because it won't affect the size of `StatementKind`.

**Comment by nagisa** [comment]
> about a 1% instruction count regression

Are there any wall-clock time/cycle count comparisons as well? Instruction count comparisons, in my experience, are not great. Even if two distinct workloads do not differ by much, as depending on instruction order and instructions themselves, modern CPUs can easily retire wildly different number of instructions in same span of time. At the high end, I’ve seen a factor of 4 difference in a real-world work-load in an application doing the same job in same amount of time.

> it won't affect the size of StatementKind

Oh, I didn’t intend to make an impression that it would beneficial for performance. I meant it would be nice-to-have purely for consistency reasons.

@bors r+

**Comment by nnethercote** [comment]
As per https://github.com/rust-lang/rust/pull/54526#issuecomment-424194833, the other metrics (which includes `wall-time`, `cycles:u`, `task-clock`, and `cpu-clock`) are too noisy to be useful, unfortunately. You are right that instructions is not the ideal metric, but it's the default because it's far more stable than time-related ones.

**Pull request merged**
