### PR TITLE
privacy: Stabilize lint `unnameable_types`

### LINKED ISSUE #48054: Tracking issue for RFC #2145: Type privacy and private-in-public lints
This is a tracking issue for the RFC "Type privacy and private-in-public lints " (rust-lang/rfcs#2145).

**Steps:**

- [ ] Implement the RFC (cc @petrochenkov )
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [] It's not fully clear if the restriction for associated type definitions required for
type privacy soundness, or it's just a workaround for a technical difficulty.

- [] Interactions between macros 2.0 and the notions of reachability / effective
visibility used for the lints are unclear.

### PR DESCRIPTION
**Pull request by petrochenkov**
This is the last piece of ["RFC #2145: Type privacy and private-in-public lints"](https://github.com/rust-lang/rust/issues/48054).

Having unstable lints is not very useful because you cannot even dogfood them in the compiler/stdlib in this case (https://github.com/rust-lang/rust/pull/113284).
The worst thing that may happen when a lint is removed are some `removed_lints` warnings, but I haven't heard anyone suggesting removing this specific lint.

This lint is allow-by-default and is supposed to be enabled explicitly.
Some false positives are expected, because sometimes unnameable types are a legitimate pattern.
This lint also have some unnecessary false positives, that can be fixed - see https://github.com/rust-lang/rust/issues/120146 and https://github.com/rust-lang/rust/issues/120149.

Closes https://github.com/rust-lang/rust/issues/48054.

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @Bryanskiy

**Review by davidtwco — APPROVED** [review]
Implementation looks good to me, r=me after relevant sign-offs.

**Comment by joshtriplett** [comment]
We talked about this in today's @rust-lang/lang meeting. We're in favor of shipping this and working towards making it warn-by-default.

We had one suggestion for naming and application of this lint: if we fired the lint specifically *at the point where you are applying a non-pub visibility to a module with pub items*, and called the lint something like `suppressed_pub`, then that would allow for an explicit opt-in for "I'm intentionally suppressing public items" by writing `#[allow(suppressed_pub)]` on the point where you're applying the non-pub visibility to the module with pub items.

**Comment by joshtriplett** [comment]
I do think we should consider renaming this to `suppressed_pub` (or something that similarly focused on the fact that a type was pub in a module but an outer module prevents it from being exposed) before stabilizing it, personally.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

As evidenced by the discussion above, we discussed this on the lang call today, and while there was discussion about where to go from here, no one seemed opposed to stabilizing an allow-by-default lint.  The outcome is the proposed FCP merge, so we can unnominate this.

**Comment by petrochenkov** [comment]
@joshtriplett 
> I do think we should consider renaming this to `suppressed_pub` (or something that similarly focused on the fact that a type was pub in a module but an outer module prevents it from being exposed) before stabilizing it, personally.

What you are describing here looks like another already existing allow-by-default lint - `unreachable_pub`.
`unnameable_types` focuses on a different things - types that are indeed public, but cannot be explicitly named by users of the crate.

`unreachable_pub` - something is locally marked as `pub`, but not actually reachable from other crates.
`unnameable_types` - something that is reachable from other crates (which implies `pub`), but cannot be named.

**Comment by tmandry** [comment]
@petrochenkov It sounds like you are using a definition of "reachable" that is different from what I understood the term to mean (which is the same as how you are using "nameable"). Explaining the terms in error messages and docs would help.

My feeling is that we should just redefine `unreachable_pub` to include this lint. The distinction "can create a value of unnameable type" does not seem important enough to create a separate lint, when we can already do that with closures and async blocks. But this has already been RFC'd, so I will not block stabilization.

**Review by davidtwco — APPROVED** [review]
Implementation looks good to me, r=me once lang discussions resolved.

**Comment by petrochenkov** [comment]
@tmandry
>It sounds like you are using a definition of "reachable" that is different from what I understood the term to mean (which is the same as how you are using "nameable"). Explaining the terms in error messages and docs would help.

I used the naming used in the compiler (`struct EffectiveVisibility`)
- directly visible - both the item and all its parent modules are public, so the item can be referred by a direct path from the outside - `my_crate::my_mod::Item` (this is only used by rustdoc)
- reexported aka nameable - the item is either directly visible, or has a chain of public reexports leading to it, even if some of its direct parent modules are private - `my_crate::my_mod_reexport::Item`
- reachable - the item is either reexported, or is leaked from the crate in some other way - is returned by a public function, or by a public field, or occurs inside of some public type alias (basically it appears in a signature of something already reachable)

Also
- `pub` - something that has a local `pub` annotation, without considering any global properties like reexports or reachability

**Comment by petrochenkov** [comment]
So, summarizing again:

#### `unreachable_pub`

An item is locally `pub`, but it is neither reexported nor leaks to other crates in any way.

Recommended action: remove `pub`, or replace it with `pub(crate)`/`pub(super)`/etc.

This lint is reported for all entities because `pub` can be removed from anything.
(Although we probably need to tweak how this lint to not fire on fields of non-`pub` types, that's its main point of annoyance right now.)

#### `unnameable_types`

An item is reachable (leaks to other crates, this implies `pub`), but cannot be named because it's not reexported.

Recommended action: either reexport the item properly to make it nameable, or document that users are not supposed to be able to name it for one reason or another. In this case `pub` cannot be removed or changed to some more restricted visibility.

This lint is only reported for types and traits, because reporting it for other entities is redundant / not useful in nearly all cases.

This behavior is what many people expected from the old `private_in_public` lint, and were surprised because that lint didn't work like this.
- How `private_in_public` lint really worked: non-`pub` type/trait appears in a signature of a `pub` function.
- How some people expected it to work: "private" (actually unreachable) type/trait appears in a signature of a "public" (actually reachable/reexported) function. This matches `unnameable_types`.

**Comment by davidtwco** [comment]
Already reviewed the implementation and the FCP has finished, so will approve this now.

@bors r+

**Comment by nnethercote** [comment]
I have been playing with adding `#![deny(unreachable_pub)]` to the compiler. I find visibilities very important when reading and navigating the codebase, and I often make commits that reduce unneeded visibilities. So any tools that help automate that are very welcome.

Having said that, I do have one suggestion: `unreachable_pub` always suggests converting a `pub` to a `pub(crate)`, but sometimes it is possible to remove the visibility entirely. It would be much nicer if it was able to distinguish these two cases. I just went through the entire `rustc_codegen_llvm` crate doing the following:
- Add `#![unreachable_pub]`
- For every `pub` it complains about, just remove the `pub`. (Even though it suggests changing to `pub(crate)`.)
- Then recompile repeatedly, adding `pub(crate)` to all the cases that the compiler says need it.

A bit tedious, and would have been a lot easier if the lint could distinguish the two cases.

**Pull request merged**
