### PR TITLE
[needs perf run] Try to improve LLVM pass ordering

### LINKED ISSUE #45466: Can't optimize loop assignment into memset
https://godbolt.org/g/9uWCF8

```rust
pub fn memzero(data: &mut [u8]) {
    for i in 0..data.len() {
        data[i] = 0;
    }
}
```

```asm
example::memzero:
  push rbp
  mov rbp, rsp
  test rsi, rsi
  je .LBB0_13
  cmp rsi, 31
  jbe .LBB0_2
  mov rax, rsi
  and rax, -32
  je .LBB0_2
  lea r8, [rax - 32]
  mov ecx, r8d
  shr ecx, 5
  inc ecx
  and rcx, 7
  je .LBB0_5
  neg rcx
  xor edx, edx
  xorps xmm0, xmm0
.LBB0_7:
  movups xmmword ptr [rdi + rdx], xmm0
  movups xmmword ptr [rdi + rdx + 16], xmm0
  add rdx, 32
  inc rcx
  jne .LBB0_7
  jmp .LBB0_8
.LBB0_2:
  xor eax, eax
.LBB0_12:
  mov byte ptr [rdi + rax], 0
  inc rax
  cmp rax, rsi
  jb .LBB0_12
.LBB0_13:
  pop rbp
  ret
.LBB0_5:
  xor edx, edx
.LBB0_8:
  cmp r8, 224
  jb .LBB0_11
  mov rcx, rax
  sub rcx, rdx
  lea rdx, [rdi + rdx + 240]
  xorps xmm0, xmm0
.LBB0_10:
  movups xmmword ptr [rdx - 240], xmm0
  movups xmmword ptr [rdx - 224], xmm0
  movups xmmword ptr [rdx - 208], xmm0
  movups xmmword ptr [rdx - 192], xmm0
  movups xmmword ptr [rdx - 176], xmm0
  movups xmmword ptr [rdx - 160], xmm0
  movups xmmword ptr [rdx - 144], xmm0
  movups xmmword ptr [rdx - 128], xmm0
  movups xmmword ptr [rdx - 112], xmm0
  movups xmmword ptr [rdx - 96], xmm0
  movups xmmword ptr [rdx - 80], xmm0
  movups xmmword ptr [rdx - 64], xmm0
  movups xmmword ptr [rdx - 48], xmm0
  movups xmmword ptr [rdx - 32], xmm0
  movups xmmword ptr [rdx - 16], xmm0
  movups xmmword ptr [rdx], xmm0
  add rdx, 256
  add rcx, -256
  jne .LBB0_10
.LBB0_11:
  cmp rax, rsi
  jne .LBB0_12
  jmp .LBB0_13
```

This is normal before rustc 1.20, which is a performance  regression.

### PR DESCRIPTION
**Pull request by arielb1**
Fixes #45466

### CODE REVIEW

**Comment by arielb1** [comment]
Let's check the perf impact of this

**Comment by arielb1** [comment]
@Mark-Simulacrum 

Could you do a perf run on this?

**Comment by Mark-Simulacrum** [comment]
Not quite right now as I don't have a connection to the perf machine, I'm waiting on @alexcrichton for it... hopefully next week after all hands, though.

**Comment by alexcrichton** [comment]
Yes unfortunately the perf machine is offline right now, we'll have access to it again this coming Monday at the latest.

**Comment by kennytm** [comment]
@Mark-Simulacrum @alexcrichton Is the perf machine ready now?

**Comment by alexcrichton** [comment]
Ah yes, it is indeed back online.

**Comment by Mark-Simulacrum** [comment]
Perf run queued.

**Comment by kennytm** [comment]
http://perf.rust-lang.org/compare.html?start=2f351415e53b9214d9a536f84f232a58f46698b6&end=1e8a44a33d146447b90c16be3dd9d95aa69bcfd3&stat=instructions%3Au

Almost no impact in terms of `instructions:u` (all values within ±2%).

**Comment by arielb1** [comment]
@kennytm 

I *do* see a clear 1-2% regression in compile-time for opt builds

**Comment by arielb1** [comment]
Now with a more aggressive try.

I think this needs a merge of my PR on rust-lang/llvm, and then I can try?

**Comment by arielb1** [comment]
@Mark-Simulacrum 

Can I have a new perf run on this more aggressive pass ordering

**Comment by arielb1** [comment]
This also seems to fix #46542.

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by kennytm** [comment]
http://perf.rust-lang.org/compare.html?start=4a7c072fa61b42f96d8b75c37fc1edfd71172695&end=8a453b274af5c133ed55a5813e5b36f87afe33d3&stat=instructions%3Au

deep-vector-opt is 8% slower (6% more instructions), regex-opt is ~3% slower

**Comment by nikomatsakis** [comment]
Nominating for discussion in the @rust-lang/compiler meeting.

**Comment by nikomatsakis** [comment]
@bors r+

After discussion in the compiler meeting we decided to go forward with this PR. However, there is a sense that we need to develop a more comprehensive runtime perf suite so that we can have a better idea of the overall impact of changes like this.

**Comment by kennytm** [comment]
@bors retry #46903 3 hour timeout 

It is happening very frequently recently 😞

**Pull request merged**
