### PR TITLE
Make sufficiently old or low-impact compatibility lints deny-by-default

### PR DESCRIPTION
**Pull request by petrochenkov**
cc https://github.com/rust-lang/rust/issues/39216
cc https://github.com/rust-lang/rust/issues/36247
cc https://github.com/rust-lang/rust/issues/37872
cc https://github.com/rust-lang/rust/issues/38260
cc https://github.com/rust-lang/rust/issues/40107
cc https://github.com/rust-lang/rust/issues/42238

Needs crater run before proceeding.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Will start a crater run.

**Comment by nikomatsakis** [comment]
Crater checklist:

- [ ] [Building old compiler](https://tools.taskcluster.net/task-inspector/#__NdB07KRB2HIxRdlaNN3w)
- [ ] [Building new compiler](https://tools.taskcluster.net/task-inspector/#LJojP66LSjizXL4lMkMwvg/)
- [ ] Start crater test run (old)
- [ ] Start crater test run (new)
- [ ] Wait for quiescence

**Comment by nikomatsakis** [comment]
## Coverage

* 10074 crates tested: 7486 working / 2137 broken / 50 regressed / 14 fixed / 387 unknown.

## Regressions

* There are 49 root regressions
* There are 50 regressions

## Root regressions, sorted by rank:

* [arrayvec-0.3.23](https://crates.io/crates/arrayvec) ([before](https://tools.taskcluster.net/task-inspector/#20pJwYQ2QVy3Ts0lX3aTBw)) ([after](https://tools.taskcluster.net/task-inspector/#_5Ot5p_xTR6_q5rND1oPLw))
* [libimagutil-0.2.0](https://crates.io/crates/libimagutil) ([before](https://tools.taskcluster.net/task-inspector/#muk9fpa2Qy65MRgeafs0Uw)) ([after](https://tools.taskcluster.net/task-inspector/#yhX6cMmVQDKpjvHPhR7ZFA))
* [html5ever-0.18.0](https://crates.io/crates/html5ever) ([before](https://tools.taskcluster.net/task-inspector/#JGdiO8GvStynkvqw4aQhoQ)) ([after](https://tools.taskcluster.net/task-inspector/#fQg-9-yIQUKZjc335TBymQ))
* [rotor-0.6.3](https://crates.io/crates/rotor) ([before](https://tools.taskcluster.net/task-inspector/#WMdhlLPWQh2ZxvcGsbWwAg)) ([after](https://tools.taskcluster.net/task-inspector/#7pi3my7ZS760DG2rFBO15g))
* [users-0.5.2](https://crates.io/crates/users) ([before](https://tools.taskcluster.net/task-inspector/#E8smNN1oTbqnb8PuKlveCw)) ([after](https://tools.taskcluster.net/task-inspector/#vuQO1zknSC-epQ6yRhadHQ))
* [twox-hash-1.1.0](https://crates.io/crates/twox-hash) ([before](https://tools.taskcluster.net/task-inspector/#E42O8cLwS0GXZtS2jsO8pw)) ([after](https://tools.taskcluster.net/task-inspector/#pY4iAdCVRTafRE7H7XlzjA))
* [encoding_rs-0.6.11](https://crates.io/crates/encoding_rs) ([before](https://tools.taskcluster.net/task-inspector/#gsK4DiwZRBKcrGXh_4tDJA)) ([after](https://tools.taskcluster.net/task-inspector/#NgV9G_wrQ8KjdnEyYVwQhg))
* [leveldb-0.8.3](https://crates.io/crates/leveldb) ([before](https://tools.taskcluster.net/task-inspector/#vYxX5rnfQ7eV-25T4oxXog)) ([after](https://tools.taskcluster.net/task-inspector/#1EJvegqORh6RI3nkxJjxcA))
* [rl-sys-0.5.2](https://crates.io/crates/rl-sys) ([before](https://tools.taskcluster.net/task-inspector/#oE0ZJHa5Rj29ksXajZb5Yw)) ([after](https://tools.taskcluster.net/task-inspector/#jx48jfIITWuRN4b1NmzkNA))
* [font-atlas-0.1.3](https://crates.io/crates/font-atlas) ([before](https://tools.taskcluster.net/task-inspector/#EM1pJImGQUml1XyXVVrPJQ)) ([after](https://tools.taskcluster.net/task-inspector/#YAAOf9YdTLOJrylqMDwhOA))
* [atomic-0.3.3](https://crates.io/crates/atomic) ([before](https://tools.taskcluster.net/task-inspector/#YZNAX5DgSjKj-PJTFvvBVQ)) ([after](https://tools.taskcluster.net/task-inspector/#3Su4-KBzSUuYz-3SSd03tg))
* [theban_db-0.7.0](https://crates.io/crates/theban_db) ([before](https://tools.taskcluster.net/task-inspector/#vLX_B3BgRhe9OJZ3Sz5z9w)) ([after](https://tools.taskcluster.net/task-inspector/#TttfLvx-RW-V6GcVaUu4eA))
* [bitflags-associated-constants-0.6.0](https://crates.io/crates/bitflags-associated-constants) ([before](https://tools.taskcluster.net/task-inspector/#WrKQ2DtsQtei7yyQRZf4Yw)) ([after](https://tools.taskcluster.net/task-inspector/#zJ9vXre7R1iwthfAzBz85w))
* [once-0.3.2](https://crates.io/crates/once) ([before](https://tools.taskcluster.net/task-inspector/#2edJ0xvKRbeFenyJAWSi2g)) ([after](https://tools.taskcluster.net/task-inspector/#RicLPSe6RNWo3-pkFEkY4Q))
* [bitcoin-0.9.1](https://crates.io/crates/bitcoin) ([before](https://tools.taskcluster.net/task-inspector/#VWaf4jl6TNyTAaAN9L41gw)) ([after](https://tools.taskcluster.net/task-inspector/#Y4SLPF0lQlimjrrooOlRqQ))
* [popcorn-blas-0.1.0](https://crates.io/crates/popcorn-blas) ([before](https://tools.taskcluster.net/task-inspector/#wgJjWeRBSfebYHZ4a1qitQ)) ([after](https://tools.taskcluster.net/task-inspector/#bYHNCw0nRCGvA-DVuxgtdw))
* [ralloc_shim-0.1.1](https://crates.io/crates/ralloc_shim) ([before](https://tools.taskcluster.net/task-inspector/#RUhoMnXtS2ejeHhbEdos6w)) ([after](https://tools.taskcluster.net/task-inspector/#Iroo_0mSRtSaaQBEqz9ljw))
* [cronparse-0.5.1](https://crates.io/crates/cronparse) ([before](https://tools.taskcluster.net/task-inspector/#ptnbZO8bT4aH1g3dz0QpUw)) ([after](https://tools.taskcluster.net/task-inspector/#xIGo9p4cQ9em3H5eVf18Fw))
* [hado-0.1.0](https://crates.io/crates/hado) ([before](https://tools.taskcluster.net/task-inspector/#QFUwU__6Qte7VtmvCfHgvQ)) ([after](https://tools.taskcluster.net/task-inspector/#MHH2WWj3SC6vfHy8TvSOAg))
* [arthas_derive-0.1.0](https://crates.io/crates/arthas_derive) ([before](https://tools.taskcluster.net/task-inspector/#Sds2YO3yRwOrSwHLDx7CHA)) ([after](https://tools.taskcluster.net/task-inspector/#GIPrv8htQfC9iBdIV2mP9Q))
* [jlens-0.0.1](https://crates.io/crates/jlens) ([before](https://tools.taskcluster.net/task-inspector/#Bx0XvalkQTOnV_4P2YR87g)) ([after](https://tools.taskcluster.net/task-inspector/#8gQuI5VzQfSu_b8Nuv1YSw))
* [twiddle-0.3.0](https://crates.io/crates/twiddle) ([before](https://tools.taskcluster.net/task-inspector/#SPSjDQbIR1WG0P1Gk80J6A)) ([after](https://tools.taskcluster.net/task-inspector/#5uO1eSxaTvKtPFrop4rW_g))
* [zmtp-0.6.0](https://crates.io/crates/zmtp) ([before](https://tools.taskcluster.net/task-inspector/#YBUrVgNwSByr_eqzSnU6iA)) ([after](https://tools.taskcluster.net/task-inspector/#oCmKcSeIQ2WRQSr-PApCZg))
* [cfrp-0.0.4](https://crates.io/crates/cfrp) ([before](https://tools.taskcluster.net/task-inspector/#R_v2Lx-ITtCF9HmwUDY1qg)) ([after](https://tools.taskcluster.net/task-inspector/#68LR-o-mSVOTR9pttBEfVw))
* [hashpipe-0.1.1](https://crates.io/crates/hashpipe) ([before](https://tools.taskcluster.net/task-inspector/#emA0U74GRT-3OenMcWRYzg)) ([after](https://tools.taskcluster.net/task-inspector/#cA2AjQ67TDKu094rME6b2g))
* [hprose-0.1.0](https://crates.io/crates/hprose) ([before](https://tools.taskcluster.net/task-inspector/#17rwF1WwT5-Fj8jhgZvAAw)) ([after](https://tools.taskcluster.net/task-inspector/#JCX-nR9ZQtKD6qRb32ZGlw))
* [json_rpc-0.2.0](https://crates.io/crates/json_rpc) ([before](https://tools.taskcluster.net/task-inspector/#W5lURCuwRUC_bfDQ7TceOA)) ([after](https://tools.taskcluster.net/task-inspector/#tPey6iwLSA62gwlQNhKk-w))
* [altbitflags-0.1.0](https://crates.io/crates/altbitflags) ([before](https://tools.taskcluster.net/task-inspector/#2I5JjjhwTcK0Hf4YRrBuHw)) ([after](https://tools.taskcluster.net/task-inspector/#gASMwYtESm20jMoPTFHEqA))
* [cuticula-0.2.0](https://crates.io/crates/cuticula) ([before](https://tools.taskcluster.net/task-inspector/#fm0bSDloRYG9aOIi21v6Dw)) ([after](https://tools.taskcluster.net/task-inspector/#pDY9zXwKQQqB0W__9zlvEg))
* [nalgebra-lapack-0.4.0](https://crates.io/crates/nalgebra-lapack) ([before](https://tools.taskcluster.net/task-inspector/#-avc7pFXTfCWWjfR8dMudw)) ([after](https://tools.taskcluster.net/task-inspector/#C7pmPSnDS8mJmI0SmFUsYQ))
* [oniguruma-0.3.1](https://crates.io/crates/oniguruma) ([before](https://tools.taskcluster.net/task-inspector/#_9smZK1jT2uy6B8p5dQ3fQ)) ([after](https://tools.taskcluster.net/task-inspector/#NW4gqDorSJOXZkEaVwGmJg))
* [opal-0.1.1](https://crates.io/crates/opal) ([before](https://tools.taskcluster.net/task-inspector/#xj386ndvS5q1INe2McDVRA)) ([after](https://tools.taskcluster.net/task-inspector/#5QmJLOiRRsqE-wWYaV2Hrw))
* [qecs-0.0.7](https://crates.io/crates/qecs) ([before](https://tools.taskcluster.net/task-inspector/#zTdrNE9MR_ygY6Rnc9PLMg)) ([after](https://tools.taskcluster.net/task-inspector/#c9p55hBtR6uRvcvB1LhEQA))
* [rcmark-0.1.0](https://crates.io/crates/rcmark) ([before](https://tools.taskcluster.net/task-inspector/#ip8DPR35SMaaY-3GsvEflw)) ([after](https://tools.taskcluster.net/task-inspector/#LD26hU_nT5O6DdQQz8rt-A))
* [reep-optionparser-urlencoded-0.2.0](https://crates.io/crates/reep-optionparser-urlencoded) ([before](https://tools.taskcluster.net/task-inspector/#UjOZyAu4Qo6zjd8jCet9nw)) ([after](https://tools.taskcluster.net/task-inspector/#vGe2yrxaT8i30M_67YME_w))
* [rft-0.1.0](https://crates.io/crates/rft) ([before](https://tools.taskcluster.net/task-inspector/#0pTyQYfGTGaHbGmlWL32jA)) ([after](https://tools.taskcluster.net/task-inspector/#0oYKt_baS0mCBaHlkr2tzg))
* [rjq-0.3.0](https://crates.io/crates/rjq) ([before](https://tools.taskcluster.net/task-inspector/#g4SN5sP-SyS3XmB_MJtAlQ)) ([after](https://tools.taskcluster.net/task-inspector/#nu-eGrW1Spu4vjLftaPJeQ))
* [rss-rs-0.3.2](https://crates.io/crates/rss-rs) ([before](https://tools.taskcluster.net/task-inspector/#YLLJg-LdQ660KCrpI92snA)) ([after](https://tools.taskcluster.net/task-inspector/#eozVb5NuR9CtOhu-JlEbOg))
* [runwhen-0.0.3](https://crates.io/crates/runwhen) ([before](https://tools.taskcluster.net/task-inspector/#hS7nkNrqTSKVssLgoEYEtg)) ([after](https://tools.taskcluster.net/task-inspector/#oRQXw2brRbSs_P0qBWyndQ))
* [rusoto_ds-0.27.0](https://crates.io/crates/rusoto_ds) ([before](https://tools.taskcluster.net/task-inspector/#pFVlZXFVRHCZAO_CTFncdA)) ([after](https://tools.taskcluster.net/task-inspector/#hqDyGAzCR7S7L4J0JdKBZw))
* [rustbar-0.2.0](https://crates.io/crates/rustbar) ([before](https://tools.taskcluster.net/task-inspector/#BMMQ-aEqTnSlzCNk7LPiHg)) ([after](https://tools.taskcluster.net/task-inspector/#7OpXJLBzRV2R_G8mX9-oPQ))
* [rust_RIBBIT-0.0.1](https://crates.io/crates/rust_RIBBIT) ([before](https://tools.taskcluster.net/task-inspector/#s_OJFZkUTyqO8dod-HuHCg)) ([after](https://tools.taskcluster.net/task-inspector/#Bc2YG-lsSm2Md-HvE-RSdw))
* [esprit-0.0.5](https://crates.io/crates/esprit) ([before](https://tools.taskcluster.net/task-inspector/#E4nTwKi4RgOfqptYQushmA)) ([after](https://tools.taskcluster.net/task-inspector/#Mg85onFOTI-JA07EKGh6AQ))
* [sem-0.1.0](https://crates.io/crates/sem) ([before](https://tools.taskcluster.net/task-inspector/#Bb7dCg5cRWmJr1YTjJBIPw)) ([after](https://tools.taskcluster.net/task-inspector/#RzMd978WRJCTPTm0bvPZPA))
* [spatial-0.2.0-rc2](https://crates.io/crates/spatial) ([before](https://tools.taskcluster.net/task-inspector/#EADdkdorSvqzkrdv79xQDQ)) ([after](https://tools.taskcluster.net/task-inspector/#NjO6vsE_SFm0NsdpaR0vUw))
* [stdx-0.0.1](https://crates.io/crates/stdx) ([before](https://tools.taskcluster.net/task-inspector/#mEbUvAd_QYKfZCSP6gNU4w)) ([after](https://tools.taskcluster.net/task-inspector/#C4CnBZcOT8-YGFr-5B-k-w))
* [capi-0.0.3](https://crates.io/crates/capi) ([before](https://tools.taskcluster.net/task-inspector/#dIfXuxK3Q2GnGMZZOFhhSA)) ([after](https://tools.taskcluster.net/task-inspector/#Djlgx9_ORguAZVzfnV5yKA))
* [veb-rs-0.1.1](https://crates.io/crates/veb-rs) ([before](https://tools.taskcluster.net/task-inspector/#UDNOs0lkSKy6knlvwcaVfg)) ([after](https://tools.taskcluster.net/task-inspector/#o6hNQi2bQtiMcGUDiIGKYQ))
* [glitter-0.1.1](https://crates.io/crates/glitter) ([before](https://tools.taskcluster.net/task-inspector/#mR9-oEPbSLqB9KkttGqkRQ)) ([after](https://tools.taskcluster.net/task-inspector/#yJjcyJsqQqWPmZKJCcyKVQ))

**Comment by petrochenkov** [comment]
`patterns_in_fns_without_body`:
- libimagutil-0.2.0
- html5ever-0.18.0
- users-0.5.2
- leveldb-0.8.3
- theban_db-0.7.0
- popcorn-blas-0.1.0
- hado-0.1.0
- jlens-0.0.1
- zmtp-0.6.0
- cfrp-0.0.4
- hprose-0.1.0
- nalgebra-lapack-0.4.0
- opal-0.1.1
- rft-0.1.0
- rss-rs-0.3.2
- rustbar-0.2.0
- esprit-0.0.5
- spatial-0.2.0-rc2
- capi-0.0.3
- glitter-0.1.1

`pub_use_of_private_extern_crate`:
- rotor-0.6.3
- bitflags-associated-constants-0.6.0
- once-0.3.2
- json_rpc-0.2.0
- cuticula-0.2.0
- qecs-0.0.7
- stdx-0.0.1

`parenthesized_params_in_types_and_modules`:
- twox-hash-1.1.0
- encoding_rs-0.6.11
- font-atlas-0.1.3
- rust_RIBBIT-0.0.1

`safe_extern_statics`:
- rl-sys-0.5.2
- ralloc_shim-0.1.1
- oniguruma-0.3.1
- rcmark-0.1.0

`missing_fragment_specifier`:
- hashpipe-0.1.1
- runwhen-0.0.3
- sem-0.1.0

`legacy_directory_ownership`:
- atomic-0.3.3

`resolve_trait_on_defaulted_unit`:
- rjq-0.3.0

spurious:
- arrayvec-0.3.23
- bitcoin-0.9.1
- cronparse-0.5.1
- arthas_derive-0.1.0
- twiddle-0.3.0
- altbitflags-0.1.0
- reep-optionparser-urlencoded-0.2.0
- rusoto_ds-0.27.0
- veb-rs-0.1.1

**Comment by petrochenkov** [comment]
Looks like `patterns_in_fns_without_body` is going to stay warn-by-default and I'll send PRs with fixes for the remaining issues.

**Comment by alexcrichton** [comment]
ping @petrochenkov just wanted to make sure this didn't fall off your radar

**Comment by nikomatsakis** [comment]
Just been out of town. Working on my backlog now!

**Comment by nikomatsakis** [comment]
@petrochenkov ok r=me when you feel this is ready to go

**Comment by petrochenkov** [comment]
I'm going to send patches to affected crates this weekend, after that I'll land this PR then.

**Pull request merged**
