### PR TITLE
Stabilize `div_duration`

### LINKED ISSUE #63139: Tracking issue for div_duration
Rust PR: #62756

This feature adds the following methods to `Duration`:
- `div_duration_f64(self, rhs: Duration) -> f64`
- `div_duration_f32(self, rhs: Duration) -> f32`

### PR DESCRIPTION
**Pull request by newpavlov**
Closes #63139

### CODE REVIEW

**Comment by jhpratt** [comment]
This still needs FCP. Nominating for T-libs-api so they'll see it.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting. We were generally favorable towards adding these. But also, multiple people expressed a preference that these could be more accurate by doing the math in nanos rather than seconds.

That said:

@rfcbot merge

**Comment by newpavlov** [comment]
>these could be more accurate by doing the math in nanos rather than seconds

Hm, comparing the two expressions:
```rust
let s1 = (d1.secs as f32) + (d1.nanos as f32) / (NANOS_PER_SEC as f32);
let s2 = (d2.secs as f32) + (d2.nanos as f32) / (NANOS_PER_SEC as f32);
s1 / s2
```
```rust
let s1 = (d1.secs as f32) * (NANOS_PER_SEC as f32) + (d1.nanos as f32);
let s2 = (d2.secs as f32) * (NANOS_PER_SEC as f32) + (d2.nanos as f32);
s1 / s2
```
I guess the latter should be indeed slightly more accurate. The former will often lose precision in the nanos division, while in the latter case, if loss of precision has happened during multiplication, addition of nanos is unlikely to change the final result.

**Comment by jhpratt** [comment]
> Should I replace the methods implementation?

I'm indifferent. The `time` crate divides the nanoseconds as integers, just as the current implementation in `std` does. At most I'd imagine this would only differ by a single nanosecond, but I haven't checked that.

**Pull request merged**
