### PR TITLE
Add -Zinput-stats

### PR DESCRIPTION
**Pull request by nrc**
Emits loc, and node count - before and after expansion.

E.g.,

```
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore
Lines of code:             32060
Pre-expansion node count:  120205
Post-expansion node count: 482749
```

r? @nikomatsakis

### CODE REVIEW

**Comment by sanxiyn** [comment]
node_count.rs seems missing.

**Comment by nrc** [comment]
@sanxiyn thanks!

**Comment by nikomatsakis** [comment]
r+ once conflicts are resolved

**Pull request merged**
