### PR TITLE
Stabilize `min_const_fn`

### PR DESCRIPTION
**Pull request by oli-obk**
tracking issue: #53555

r? @Centril

### CODE REVIEW

**Review by Centril — APPROVED** [review]

**Comment by killercup** [comment]
You constantly surprise me, Oli: TIL git(hub) apparently works well with unicode branch names.

**Comment by Centril** [comment]
Extra points for a great branch name =P

/me considers branch names in Swedish now

**Comment by oli-obk** [comment]
r? @RalfJung 

The tracking issue has been FCPed and accepted for merging. @Centril already signed off.

**Comment by oli-obk** [comment]
Oh wait

@bors r=Centril

:smiling_imp:

**Comment by Centril** [comment]
🙏

**Pull request merged**
