### PR TITLE
ext/ucred: Support PID in peer creds on macOS

### PR DESCRIPTION
**Pull request by woodruffw**
This is a follow-up to https://github.com/rust-lang/rust/pull/75148 (RFC: https://github.com/rust-lang/rust/issues/42839).

The original PR used `getpeereid` on macOS and the BSDs, since they don't (generally) support the `SO_PEERCRED` mechanism that Linux supplies.

This PR splits the macOS/iOS implementation of `peer_cred()` from that of the BSDs, since macOS supplies the `LOCAL_PEERPID` sockopt as a source of the missing PID. It also adds a `cfg`-gated tests that ensures that platforms with support for PIDs in `UCred` have the expected data.

### CODE REVIEW

**Comment by woodruffw** [comment]
Gentle ping on this: any chance for a review?

**Comment by cramertj** [comment]
Sorry for the delay, but unfortunately I'm entirely the wrong person to review this.

Perhaps

r? @Kixunil

**Comment by woodruffw** [comment]
Woohoo!

**Pull request merged**
