### PR TITLE
Mention field punning in the docs for patterns

### PR DESCRIPTION
**Pull request by Marwes**
Adds a mention for the short form pattern syntax. Now without creating a PR to my own fork!
#25779

### CODE REVIEW

**Comment by brson** [comment]
r? @steveklabnik 

My only comment is that 'punning' is really jargony, and probably can't go without explanation.

**Comment by Marwes** [comment]
I considered not to mention it but it is the correct term for it so mentioning it is probsbly a good idea. Just calling it "short form" feels harder to remember as well.

**Comment by steveklabnik** [comment]
yeah, I am split on this, for the same reason as @brson. We've been trying to eliminate extra jargon as of late.

Also, is 'punning' truly correct here? http://en.wikipedia.org/wiki/Type_punning seems more in line with how i've seen this used.

I know we have a lint if you don't use this syntax, ie, `x: x`. What does that error message say?

Finally, if we do keep the jargon, it would be nice to put it in the Glossary and link to it.

**Comment by Marwes** [comment]
Both OCaml and Haskell calls it field punning though so I'd say it is correct. The warning only says that the field can be removed though. I can see why it should be removed though to reduce jargon since it does not help understanding the syntax in it is self. My main reason for adding the mention was more for the sake of it being a mnemonic since there did exist a term for it.

On another note, maybe its worth changing the later examples to use the same form as `x : x` display a style which is actively discouraged through warnings?

```
test.rs:3:16: 3:21 warning: the `x:` in this pattern is redundant and can be removed, #[warn(non_shorthand_field_patterns)] on by default
test.rs:3     let Test { x : x } = panic!();
```
https://realworldocaml.org/v1/en/html/records.html
https://downloads.haskell.org/~ghc/7.0.4/docs/html/users_guide/syntax-extns.html#record-puns

**Comment by steveklabnik** [comment]
> On another note, maybe its worth changing the later examples to use the same form as x : x display a style which is actively discouraged through warnings?

yes, I have been meaning to do that.

**Comment by Marwes** [comment]
Maybe introducing the rebinding as sugar on top of the shorter form would be better, something like this for example https://github.com/Marwes/rust/commit/120ec30f7fb4e8592862266276a5b1633a5ea53d.

**Comment by steveklabnik** [comment]
@Marwes yes, that's great. Would you mind updating this PR with that commit?

**Comment by Marwes** [comment]
Looks like I created an additional commit as well here due to merging. The high-five bot discouraged rebasing when adding commits so I guess I should leave it as is, or should I squash them?

**Comment by steveklabnik** [comment]
@Marwes squashing them is just fine. Thanks again!

r=me after

**Comment by Marwes** [comment]
@steveklabnik Done.

**Comment by steveklabnik** [comment]
Thanks so much!

**Pull request merged**
