### PR TITLE
Replace some instances of FxHashMap/FxHashSet with stable alternatives (mostly in rustc_hir and rustc_ast_lowering)

### PR DESCRIPTION
**Pull request by michaelwoerister**
Part of https://github.com/rust-lang/compiler-team/issues/533. We should be getting close to being able to remove the HashStable impl of HashMap.

### CODE REVIEW

**Comment by petrochenkov** [comment]
There are some maps here that may be performance critical.
@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
r=me if the perf run doesn't show regressions.

**Comment by michaelwoerister** [comment]
> r=me if the perf run doesn't show regressions.

Perf run looks good. Thanks for the review, @petrochenkov!

@bors r=petrochenkov

**Comment by lqd** [comment]
The cycles regressions have got to be noise?!

**Pull request merged**
