### PR TITLE
Set error handler output format as soon as possible

### PR DESCRIPTION
**Pull request by jieyouxu**
Should fix https://github.com/rust-lang/rust/pull/112692#issuecomment-1611585904.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
r? @davidtwco 
r=me once CI passes

**Comment by jieyouxu** [comment]
I uh... don't quite understand why these UI tests are failing even though the error messages look identical to me...?

**Comment by matthiaskrgr** [comment]
@bors r- failed in 
https://github.com/rust-lang/rust/pull/113157#issuecomment-1613287606

**Comment by jieyouxu** [comment]
So this is very cursed as to why it fails on Windows CI specifically:

- The test emits a *warning*.
- *Warnings*, and only warnings *specifically*, have a different 256-color between Windows and non-Windows hosts (other levels `set_intense(true)` unconditionally):

  https://github.com/rust-lang/rust/blob/e69c7306e2be08939d95f14229e3f96566fb206c/compiler/rustc_errors/src/lib.rs#L1792-L1794

Therefore, I added `// ignore-windows` test header to skip this test on Windows (it's sufficient to test color is enabled on at least one non-Windows host).

**Comment by fee1-dead** [comment]
Actually this seems to be the mips issue that was fixed. 

@bors r=davidtwco

**Pull request merged**
