### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #94939 (diagnostics: suggest missing comma in bad FRU syntax)
 - #95120 (Implement `apply_switch_int_edge_effects` for backward analyses)
 - #95364 (Add long error explanation for E0667)
 - #95366 (Remove test files with duplicated checksums)
 - #95368 (Fix typo in `String::try_reserve_exact` docs)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=94939,95120,95364,95366,95368)

### CODE REVIEW

**Comment by pnkfelix** [comment]
Visiting for weekly performance triage.

Changes to the primary benchmarks seem like a wash and probably ignorable (0.33% worse for unicode-normalization-0.1.19, 0.33% better for ripgrep-13.0.0).

Changes to the secondary benchmarks are slightly more concerning: namely, 3% worse for await-call-tree (on six scenarios).

If I had to guess, I'd assume that this impact was caused by PR #95120; the other PRs in this rollup seem very innocuous, while PR #95120 is (slightly(?)) more invasive.

I'm going to leave this as untriaged for now.

**Comment by Dylan-DPC** [comment]
@pnkfelix would trying a revert of #95120 and checking the perf be a good idea ?

**Comment by JakobDegen** [comment]
Pinging @pnkfelix to let you know that #96838 has been merged, which I believe should allow us to mark this as triaged, since it seems to recover the problematic 3% slowdowns

**Pull request merged**
