### PR TITLE
Implement more traits for function pointers

### PR DESCRIPTION
**Pull request by petrochenkov**
Closes https://github.com/rust-lang/rust/issues/26082

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can you measure the metadata size before/after this patch? I'm a little worried about these being so rarely used but having a relatively significant cost in terms of metadata size.

**Comment by petrochenkov** [comment]
Size of libcore.rlib:
before: 20,958,680 bytes
after: 26,644,788 byte
after with all ABIs except for "Rust" and "C" removed: 21,947,498 bytes
after with all ABIs except for "Rust" and "C" and functions with >5 arguments removed: 21,461,438 bytes

**Comment by alexcrichton** [comment]
How about we stick to just Rust, C, and <5 arguments for now? I think we can also cut down on the number of traits implemented to the bare bones as well, I don't think these necessarily need to be at the same parity as raw pointers (e.g. are we really using function pointers as keys in hash maps?).

**Comment by petrochenkov** [comment]
>How about we stick to just Rust, C, and <5 arguments for now?

Good, it was the back-up plan from the beginning.

>are we really using function pointers as keys in hash maps

We aren't, because they don't implement `Hash`!

>I think we can also cut down on the number of traits implemented to the bare bones as well, I don't think these necessarily need to be at the same parity as raw pointer

I'd prefer not to do this, libcore size is not a holy grail after all. What increase in size of libcore do you consider acceptable?
Here's my chart of usefulness for these impls.
`Clone` (+ 150kb) - was already implemented
`PartialEq`/`Eq` (+ 300kb) - was partially implemented
`Debug` (+ 150kb) - needed if you want to `assert_eq` that `PartialEq` above or derive `Debug` for a containing struct.
`PartialOrd`/`Ord` (+ 300kb) *or* `Hash` (+ 150kb) are needed to have any kind of set of fn pointers or structs containing them (hash set, tree set, sorted array).
`fmt::Pointer` (+ 150kb) - needed mostly for consistency with data pointers.

**Comment by alexcrichton** [comment]
OK, seems reasonable, I guess we can try to figure out how to control metadata size later.

@bors: r+ bc7c4304ab2af12e782945f139eb73e4842b9d68

Thanks!

**Pull request merged**
