### PR TITLE
Add Vec::dedup_by and Vec::dedup_by_key

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
In the spirit of https://github.com/rust-lang/rust/pull/35856.

(Separate commits show smaller diffs.)

**Comment by alexcrichton** [comment]
Seems like a reasonable addition to me!

cc @rust-lang/libs

**Comment by aturon** [comment]
I'm :+1: on this addition.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by alexcrichton** [comment]
Also we'll need to be sure to add a tracking issue for these, but I'm fine with that happening just before merge

**Comment by SimonSapin** [comment]
I’ll open a tracking issue and edit the PR to reference it when (if) this addition is accepted.

**Comment by alexcrichton** [comment]
@SimonSapin ok, want to update with an unstable issue reference? I'll r+ after

**Comment by SimonSapin** [comment]
Done: #37087.

**Comment by SimonSapin** [comment]
```
failures:

---- wrong_checksum_is_an_error stdout ----
	thread 'wrong_checksum_is_an_error' panicked at 'failed to remove dir C:\bot\slave\auto-win-msvc-64-cargotest\build\obj\build\ct\cargo\target\cit\t0\bar\target\debug\deps: The directory is not empty. (os error 145)', tests\cargotest\support\paths.rs:143
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    wrong_checksum_is_an_error

test result: FAILED. 6 passed; 1 failed; 0 ignored; 0 measured



command did not execute successfully: "C:\\bot\\slave\\auto-win-msvc-64-cargotest\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\cargotest.exe" "C:\\bot\\slave\\auto-win-msvc-64-cargotest\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "C:\\bot\\slave\\auto-win-msvc-64-cargotest\\build\\obj\\build\\ct"
expected success, got: exit code: 101


Makefile:51: recipe for target 'check-cargotest' failed
```

Is this an intermittent failure?

**Pull request merged**
