### PR TITLE
Add Node.js to PR CI image

### PR DESCRIPTION
**Pull request by ollie27**
This should allow the `rustdoc-js` and `rustdoc-js-std` test suites to run automatically on PRs.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Seems like a minimal and easy addition.

**Comment by ollie27** [comment]
> Seems like a minimal and easy addition.

If only. These test suites apparently never supported being run from a directory other than the source code root. I've pushed a commit to hopefully fix that.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I went to the quickest but this is really nice to make those tests being able to run with a given output folder. Were you able to test it locally without issues? If so, r=me.

Again, thanks a lot for making them easier to run!

**Comment by ollie27** [comment]
> Were you able to test it locally without issues?

Yeah, but more importantly the logs from the PR build: https://dev.azure.com/rust-lang/rust/_build/results?buildId=23190&view=logs&j=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5&t=a6ad31e5-07ba-5fd6-c0b6-53535f688400&l=3574 show that it successfully ran the tests.

@bors r=Mark-Simulacrum,GuillaumeGomez

**Pull request merged**
