### PR TITLE
Make unreachable_pub an epoch lint

### PR DESCRIPTION
**Pull request by Manishearth**
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Do we want this to be an epoch lint? This is basically enabled by the new `crate` keyword, right? It seems like the use of `pub` vs `crate` is something we just want to encourage generally.

I admit to feeling somewhat confused about the "lint for epoch" story here.

cc @rust-lang/lang

**Comment by Manishearth** [comment]
So am I, see #48796

We have two kinds of epoch lints, it's unclear how each should be handled

**Comment by Manishearth** [comment]
Thinking about this more, neither this nor the dynamic trait lint should be epoch lints; instead, both should be normal lints perhaps under a "rust_2018_idioms" group. Only the keyword lint should be an epoch lint

**Comment by Manishearth** [comment]
superseded by https://github.com/rust-lang/rust/issues/48796

(we also changed what we were doing here)

**Pull request closed without merging**
