### PR TITLE
Remove some unused functionality

### PR DESCRIPTION
**Pull request by bjorn3**
* Remove the `alt_std_name` option
* Make two functions private

### CODE REVIEW

**Comment by camsteffen** [comment]
> * Remove the everybody loops pass

I think this deserves a last laugh. teehee!

**Comment by lqd** [comment]
Why remove everybody loops btw, did it maybe stop working ? Isn't it still an interesting strategy for test case reduction, as documented by @pnkfelix in the classic [minimization strategies blog post](http://blog.pnkfx.org/blog/2019/11/18/rust-bug-minimization-patterns/#L..loopification.....via.pretty-printer) ?

**Comment by bjorn3** [comment]
It probably still works, but it is rather fragile (it has caused ice in the past) and it removes def id's **after** expansion, which requires various places to take this into account (eg https://github.com/rust-lang/rust/pull/92895/files#diff-b27a380db7c2a077975b81b162d8a7923c599d56b4f265427f2a9eecc77641b4L85-L86) My primary reason however was to reduce compiler complexity a bit.

> Isn't it still an interesting strategy for test case reduction, as documented by @pnkfelix in the classic minimization strategies blog post ?

Rust-reduce has a pass that does something similar: https://github.com/jethrogb/rust-reduce/blob/master/src/transforms/clear_blocks.rs

**Comment by lqd** [comment]
> Rust-reduce has a pass that does something similar: https://github.com/jethrogb/rust-reduce/blob/master/src/transforms/clear_blocks.rs

Sure, I know, I use it often. So it doesn't affect me that much but not everyone who uses everybody_loops does, or can, use rust-reduce, hence why I was asking. 

Probably not a big deal, of course, let's see what the others think.

**Comment by bjorn3** [comment]
I will hold off on rebasing until a decision is made if everybody_loops should be removed or not.

**Comment by jackh726** [comment]
cc @pnkfelix for thoughts on everybody loops

**Comment by jackh726** [comment]
Actually let's just ping @rust-lang/compiler for thought

**Comment by nagisa** [comment]
I have personally always found `-Zeverybody-loops` an oversized hammer. It only helps in reducing issues in very limited set of rustc components early in the pipeline (parser, resolver…). An ability to loopify bodies more selectively is definitely a technique that is helpful still, but `-Zeverybody-loops` ain't that.

If the pass causes genuine pain maintaining other parts of the codebase, I'm probably in favour of removing it. That said, I would also like to suggest to split out the removal of `-Zeverybody-loops` into a separate, well motivated PR, rather than bundling it together with other more obvious removals.

**Comment by jackh726** [comment]
Given the above comment and thumbs ups, r=me after rebase

**Comment by jackh726** [comment]
Err, well. Let's split this into two. r=me on the non everybody-loops change.

**Comment by bjorn3** [comment]
Dropped the everybody loops removal from this PR. Will make a separate PR for it shortly.

@bors r=jackh726

**Comment by bjorn3** [comment]
Split out the everybody loops removal to https://github.com/rust-lang/rust/pull/93913.

**Comment by klensy** [comment]
> Split out the everybody loops removal to #93913.

PR description not changed.

**Comment by bjorn3** [comment]
My bad. Fixed that now. The merge commit may not reflect it though if the current rollup succeeds.

**Pull request merged**
