### PR TITLE
[WIP] Force projection sub-obligations to `EvaluatedToOkModuloRegions`

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by nagisa** [comment]
I am a pretty poor reviewer for this change.

**Comment by nagisa** [comment]
r? rust-lang/compiler

**Comment by jyn514** [comment]
r? rust-lang/compiler-team

**Comment by michaelwoerister** [comment]
This seems to be an alternative to https://github.com/rust-lang/rust/pull/85868, right? I'm not qualified to review this.

r? @nikomatsakis

**Comment by jackh726** [comment]
Closing since #85868 was merged.

**Pull request closed without merging**
