### PR TITLE
Don't use fd-lock on Solaris in bootstrap

### LINKED ISSUE #103630: rust 1.64 now uses fd-lock->rustix->flock() for bootstraping where flock() is not available on Solaris
Seems that Rust now relies on fd-lock for bootstraping instead of using python code:

https://github.com/rust-lang/rust/commit/5a30316fc14ab6952ce9f925478c498c804a7b71

Solaris doesn't support flock(). Insetad more modern fcntl() interface is used.

So even when I was able to make rustix compile on Solaris (without flock() support) it doesn't help since fd-lock requires flock().

Therefore I'm not able to compile Rust 1.64.0 on Solaris now.

### PR DESCRIPTION
**Pull request by psumbera**
...as Solaris is missing flock()

fixes #103630

### CODE REVIEW

**Comment by albertlarsan68** [comment]
Can you add a line in the rustc dev guide to warn that on some platforms using rust-analyzer and x at the same time may corrupt things?
r=me once done.
@bors rollup

**Comment by psumbera** [comment]
> Can you add a line in the rustc dev guide to warn that on some platforms using rust-analyzer and x at the same time may corrupt things? r=me once done. @bors rollup

I would like to. But not sure where exactly it should belong. Also not sure about all consequences of not locking. Can you help me with it?

**Comment by albertlarsan68** [comment]
I would put it in https://rustc-dev-guide.rust-lang.org/building/suggested.html#visual-studio-code, warning that on Solaris and platforms other than Unix and Windows, having multiple x.py running at the same time in the same repo will likely corrupt files and/or do bad things.
You will want to rephrase, but it is the main part I want to add a warning about.

**Comment by psumbera** [comment]
> I would put it in https://rustc-dev-guide.rust-lang.org/building/suggested.html#visual-studio-code, warning that on Solaris and platforms other than Unix and Windows, having multiple x.py running at the same time in the same repo will likely corrupt files and/or do bad things. You will want to rephrase, but it is the main part I want to add a warning about.

I don't think it's good idea. Visual Studio is not available for Solaris. And all Visual Studio supported platforms do have working fd-lock.

**Comment by albertlarsan68** [comment]
Having it in the release notes for bootstrap is definitely a good thing.
Ignore what I said about the dev guide, since this is not likely to happen, and there is already a warning.

**Comment by albertlarsan68** [comment]
You should add a line in https://github.com/rust-lang/rust/blob/master/src/bootstrap/CHANGELOG.md.

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+

**Comment by gco** [comment]
Just a note to say I sent @psumbera a compatibility stub of flock implemented using lockf for traditional Unix systems a while back.

**Comment by psumbera** [comment]
> Just a note to say I sent @psumbera a compatibility stub of flock implemented using lockf for traditional Unix systems a while back.

Originally I was proposing this: https://github.com/rust-lang/rust/issues/103630 . But it was (reasonably) rejected because of different semantics.

Now there is also basic fcntl-style locking support in Rustix: https://github.com/bytecodealliance/rustix/pull/555

Maybe this can be later leveraged somehow (either directly or via fd-lock?!).

**Pull request merged**
