### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #87428 (Fix union keyword highlighting in rustdoc HTML sources)
 - #88412 (Remove ignore-tidy-undocumented-unsafe from core::slice::sort)
 - #89098 (Fix generics where bounds order)
 - #89232 (Improve help for recursion limit errors)
 - #89297 (Remove Never variant from clean::Type enum)
 - #89311 (Add unit assignment to MIR for `asm!()`)
 - #89313 (PassWrapper: handle function rename from upstream D36850)
 - #89315 (Clarify that `CString::from_vec_unchecked` appends 0 byte.)
 - #89335 (Optimize is_sorted for Range and RangeInclusive)
 - #89366 (rustdoc: Remove lazy_static dependency)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=87428,88412,89098,89232,89297,89311,89313,89315,89335,89366)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@rust-lang/infra Is the CI broken?

@bors retry

**Comment by ehuss** [comment]
@bors treeclosed=100
Windows is not building

**Comment by ehuss** [comment]
Recreated in #89386.

**Pull request closed without merging**
