### PR TITLE
document that the null pointer has the 0 address

### LINKED ISSUE #116895: Document that null is 0
This has come up in two places recently: https://github.com/rust-lang/rust/pull/115333#issuecomment-1767199388 and https://github.com/rust-lang/rust/pull/116675#discussion_r1357784439.

We should do the following:
- On `ptr::null()`, document that `ptr::null()` is equivalent to `0usize as *const _`
- Either before or after it lands, update the text in [#116675](https://github.com/rust-lang/rust/pull/116675) to document that "allocated objects" cannot contain the 0 address (alternatively, if that PR lands with text that says that an allocated object cannot contain the "null" address, update the text to mention that null is equal to 0)

Are there other places we should update too?

cc @the8472 @tmandry @RalfJung

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/116895

Will need t-lang FCP, but I think this is fairly uncontroversial -- there's probably already tons of code out there that relies on this.

### CODE REVIEW

**Comment by traviscross** [comment]
@rustbot labels +I-lang-nominated

I'm going to nominate even though FCP has been proposed so that this comes up at least once in the meeting.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by tmandry** [comment]
@traviscross Doesn't our agenda generator include proposed FCPs already?

We already have quite a long list of nominated issues; I don't think nominating every newly proposed FCP is helping with that.

**Comment by tmandry** [comment]
From https://github.com/rust-lang/rust/issues/116895#issuecomment-1772156933 it sounds like you've already considered the implications for provenance. With those aside I think we should go ahead and commit to this.

@rfcbot reviewed

**Comment by RalfJung** [comment]
Yeah, the good thing is that nobody expects to be able to load from a null ptr so provenance basically does not matter.

**Comment by joshtriplett** [comment]
This is *not* a blocker for this issue, but could we please get a comment somewhere appropriate that says what code should do in the rare case where it has memory mapped at 0 and needs to write to it? (e.g. low-level hardware programming, or weird userspace programming situations that need the zero page mapped.) We should identify what function will allow such a write without complaint, and point people to that.

**Comment by RalfJung** [comment]
Currently there is no way to write such code in Rust, you have to use inline asm. https://github.com/rust-lang/unsafe-code-guidelines/issues/29 tracks providing support for this.

**Comment by RalfJung** [comment]
@thomcc this should be ready to land then :)

**Review by WaffleLapkin — APPROVED** [review]
Since this is only a documentation change and the semantic was approved by T-lang, I'll go ahead and merge this. Feel free to r- if you think that a T-libs review is required.

**Pull request merged**
