### PR TITLE
Add some timings to expansion code

### PR DESCRIPTION
**Pull request by Aaron1011**
Currently, we just have a single `expand_crate` timing that covers all
expansion.

### CODE REVIEW

**Comment by petrochenkov** [comment]
@Aaron1011 
Could you explain a bit what you want to achieve?
Cover all `expand_crate` with smaller parts?
Measure just some specific subsets `expand_crate`? Why subsets used in this PR specifically?

Also I don't see `parse_ast_fragment` in the perf reports in https://github.com/rust-lang/rust/pull/81254#issuecomment-765093603 for some reason.

**Comment by Aaron1011** [comment]
My main goal is to provide more insight into `expand_crate` - the pieces I chose were somewhat arbitrary. However, I think it will be useful to see how the time spent invoking macros compares to the time spent parsing the output, especially when proc-macros are involved.

It is quite odd that `parse_ast_fragment` is missing - I'll look into that.

**Comment by Dylan-DPC** [comment]
Closing this due to inactivity

**Pull request closed without merging**
