### PR TITLE
Ship llvm-cov through llvm-tools

### PR DESCRIPTION
**Pull request by dalance**
`llvm-cov` is used to generate coverage report with LLVM InstrProf-based code coverage #34701.
So if `llvm-cov` is shipped through llvm-tools, users can try it easily accorging to the instruction of [The Rust Unstable Book](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/source-based-code-coverage.html).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @richkadel can you confirm this seems appropriate?

**Comment by richkadel** [comment]
Yes! 100%

You beat me to it. Thank you!

**Comment by richkadel** [comment]
@tmandry - As you suggested...  🎉

**Pull request merged**
