### PR TITLE
Make `Ipv4Addr` and `Ipv6Addr` const tests unit tests under `library`

### PR DESCRIPTION
**Pull request by CDirkx**
These tests are about the standard library, not the compiler itself, thus should live in `library`, see #76268.

### CODE REVIEW

**Comment by CDirkx** [comment]
Currently implemented as two big tests: `ipv4_const` and `ipv6_const`, although I could split the individual tests out.
However, the point of this test is to check that the API of `Ipv4Addr` and `Ipv6Addr` are usable in a const context. The only thing really being tested here is that the consts compile, to the point that technically all the asserts could even be removed.

**Comment by matklad** [comment]
Rather than adding a new *integration* test in src/test directory, let’s add the test to existing unit-test module: https://github.com/rust-lang/rust/blob/2906a60a4f6b417abd487f0d8c917532911fdd20/library/std/src/net/ip/tests.rs


Integration tests have essentially the same problem as run-pass tests — each integration test is a separately linked and run binary, so many integration tests = slow.

**Comment by CDirkx** [comment]
Ah I see, I moved the tests. I still kept the tests as `ipv4_const` and `ipv6_const` instead of integrating the const checks into the various other tests, to have a single place where the constness of the public API is tested.

**Comment by matklad** [comment]
LGTM!

Could you squash the commits to one here as well?

@bors delegate=CDirkx

**Comment by matklad** [comment]
@bors r+ rollup

Thanks!

**Pull request merged**
