### PR TITLE
hygiene: Fix identifier comparison in impl overlap check

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/58942

### CODE REVIEW

**Comment by Centril** [comment]
Seems like a crater (check) run is in order on this one?

**Comment by petrochenkov** [comment]
Or perhaps a usual beta run would be enough, this is a somewhat recent regression (https://github.com/rust-lang/rust/issues/58942#issuecomment-469842376).

**Comment by Centril** [comment]
(Roughly half a year old, `(33 - 29) * 6 / 52`)

**Comment by Dylan-DPC** [comment]
ping form triage @petrochenkov @cramertj what's the update on this?

**Comment by petrochenkov** [comment]
@craterbot run mode=check-only

**Comment by cramertj** [comment]
good enough for me!

@bors r+

**Comment by petrochenkov** [comment]
Argh, my own change hit me in the back.
This needs an update due to https://github.com/rust-lang/rust/pull/59044.

**Pull request merged**
