### PR TITLE
rustdoc: Get TyCtxt from self instead of passing as argument in AutoTraitFinder

### LINKED ISSUE #82137: Remove unnecessary `tcx` parameter to `param_env_to_generics`
You can get a tcx from `self.cx.tcx`, there's no need to pass it separately.

Note that this will conflict with https://github.com/rust-lang/rust/pull/82020/ so you may want to wait a day or two (or not, if you don't mind rebasing).

### PR DESCRIPTION
**Pull request by noslaver**
First contribution :crab:, let me know if anything is amiss.

Fix #82137.

### CODE REVIEW

**Comment by ehuss** [comment]
Just a tip, using a descriptive PR title and commit message is helpful.  When reading the git log, seeing something like "fix issue #82137" doesn't really have any context, and seeing a PR title also has similar issues. It can be helpful when commit messages stand on their own, where they explain what the change is and why it is being made.

Git has some [guidelines](https://git-scm.com/docs/SubmittingPatches#describe-changes) for commit messages.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me. Since it also changes some code in the compiler, I'll wait for someone from @rust-lang/compiler to approve it as well.

**Comment by nagisa** [comment]
r=me with ehuss' comment addressed.

**Comment by noslaver** [comment]
> r=me with ehuss' comment addressed.

Updated git comment, should I update the PR title as well?

**Comment by GuillaumeGomez** [comment]
Yes please.

**Comment by estebank** [comment]
There's now a merge conflict. You will have to checkout a recent master and rebase on top of it.

**Review by jyn514 — APPROVED** [review]
This is great, thanks!

**Pull request merged**
