### PR TITLE
[experiment] Crater 2021 edition rustfix

### PR DESCRIPTION
**Pull request by ehuss**
Test

### CODE REVIEW

**Comment by m-ou-se** [comment]
@craterbot check crates=top-1000

**Comment by m-ou-se** [comment]
@craterbot p=1

**Comment by m-ou-se** [comment]
@craterbot check crates=top-1000

**Comment by m-ou-se** [comment]
@craterbot p=1

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

**Comment by m-ou-se** [comment]
Four failures. All of them ICEs:

Three times: ([1](https://crater-reports.s3.amazonaws.com/pr-87190-1/try%23ae1c057e7e8aafa249c7dec04db21aa007317c37/reg/curl-0.4.38/log.txt) [2](https://crater-reports.s3.amazonaws.com/pr-87190-1/try%23ae1c057e7e8aafa249c7dec04db21aa007317c37/reg/object-0.26.0/log.txt) [3](https://crater-reports.s3.amazonaws.com/pr-87190-1/try%23ae1c057e7e8aafa249c7dec04db21aa007317c37/reg/rusb-0.8.1/log.txt))
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_mir_build/src/build/matches/mod.rs:1685:53
```

And one time: ([1](https://crater-reports.s3.amazonaws.com/pr-87190-1/try%23ae1c057e7e8aafa249c7dec04db21aa007317c37/reg/yew-0.18.0/log.txt))
```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: PlaceBuilder { base: Upvar { var_hir_id: HirId { owner: DefId(0:6694 ~ yew[9580]::virtual_dom::vcomp::tests::set_properties_to_component#1), local_id: 328 }, closure_def_id: DefId(0:6699 ~ yew[9580]::virtual_dom::vcomp::tests::set_properties_to_component#1::{closure#4}), closure_kind: Fn }, projection: [] }', compiler/rustc_mir_build/src/build/expr/as_place.rs:306:69
```

**Comment by m-ou-se** [comment]
That first one seems to be https://github.com/rust-lang/rust/issues/87426, which should be fixed.

**Comment by m-ou-se** [comment]
I'm unable to reproduce the other ICE.

**Comment by ehuss** [comment]
## ahash 0.7.4
Error is caused by defining `tests/map_test.rs` as both an integration test and a benchmark without a harness. Cargo warns that you should not do this. When `cargo fix` runs, it removes an import when fixing as a benchmark, because the required code is hidden behind a `#[test]` attribute (and since there is no harness, that code is removed).

I think this can be chalked up to improper configuration. An alternative is to add `#[cfg(test)]` on the import.

Also noticed another bad suggestion, unrelated to the edition: https://github.com/rust-lang/rust/issues/87973

## crossbeam-channel 0.5.1
Migration fails because there is a `macro_rules` macro that has a type with a trait object that is missing `dyn` (the select! macro). Because the macro is never used within the crate, it doesn't get fixed. However, it is used within an integration test, and the integration test fails because `dyn` is now required.

I don't think there is an issue for this pattern, but it is mentioned as a hazard in the edition guide here: https://doc.rust-lang.org/nightly/edition-guide/editions/advanced-migrations.html#migrating-macros

**Comment by m-ou-se** [comment]
` im 15.0.0` and `structopt 0.3.22` fail on https://github.com/rust-lang/rust/issues/87313

`crossbeam-channel 0.5.1`, `crate err-derive 0.3.0`, `text_io 0.1.9`, and `tracing 0.1.26` fail on a missing `dyn` in a macro expansion.

`err-derive` also runs into an incorrect suggestion:
```
[INFO] [stdout]  --> examples/enums.rs:9:17
[INFO] [stdout]   |
[INFO] [stdout] 9 | #[derive(Debug, Error)]
[INFO] [stdout]   |                 ^^^^^
[INFO] [stdout]   |
[INFO] [stdout]   = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)
[INFO] [stdout] help: add `dyn` keyword before this trait
[INFO] [stdout]   |
[INFO] [stdout] 9 | #[derive(Debug, dyn Error)]
[INFO] [stdout]   |                 ^^^
[INFO] [stdout] 
```

**Comment by ehuss** [comment]
I don't think the ICE linked in #87426 has been fixed.  On latest nightly (`rustc 1.56.0-nightly (ccffcafd5 2021-08-11)`) I am still seeing the ICEs in `curl 0.4.38`, `object 0.26.0`, `rustb 0.8.1`.  I'm also able to reproduce the ICE in `yew 0.18.0`.  Later today I'll try to narrow it down if nobody looks at it sooner.

**Comment by m-ou-se** [comment]
>  I'm also able to reproduce the ICE in yew 0.18.0

What steps did you take for that? I used the `yew 0.18.0` crate from crates.io and the rustc from the try build that was also used by the crater run, and couldn't reproduce it. (I probably missed something simple. ^^')

**Comment by ehuss** [comment]
For `yew` it only fails when building unit tests. Edit `Cargo.toml` to set the edition to 2021, and then on latest master run `cargo check --lib --profile=test` (or `cargo test --lib` if you want to actually build it).

**Comment by ehuss** [comment]
Filed #87987 for the yew issue.

**Comment by ehuss** [comment]
Filed #87988 for the other ICE.

**Comment by m-ou-se** [comment]
> For `yew` it only fails when building unit tests. Edit `Cargo.toml` to set the edition to 2021, and then on latest master run `cargo check --lib --profile=test` (or `cargo test --lib` if you want to actually build it).

Thanks! I can reproduce it. And I can confirm that with #88039 and #87996 applied, the ICE is gone.

**Comment by m-ou-se** [comment]
Updated the PR to include  #88039, #87996 and #88083.

@bors try

**Comment by m-ou-se** [comment]
Let's try a few more (10k instead of 1k). Hopefully we can do the full run soon once the ICE fixes are merged to the main branch.

@craterbot check crates=top-10000 p=1

**Comment by m-ou-se** [comment]
A lot of the failures are:

```
[INFO] [stderr] Running `cargo fix --edition`
[INFO] [stderr] error: failed to run `rustc` to learn about target-specific information
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --cap-lints=forbid --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 101)
[INFO] [stderr]   --- stderr
[INFO] [stderr]   thread 'rustc' panicked at 'failed to create jobserver: Custom { kind: PermissionDenied, error: "failed to increase jobserver pipe capacity from 4096 to 8192; jobserver otherwise might deadlock" }', compiler/rustc_data_structures/src/jobserver.rs:23:38
```

**Comment by ehuss** [comment]
Yea, #88091 is open with more information there.  😦

**Comment by m-ou-se** [comment]
Analyzing some of the results that do seem related:

Needs fixing / investigation:

- Failure to apply `assert!(.., format!(..))` suggestion: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/abortable_parser-0.2.4/log.txt
- Failure to apply `dyn` suggestion:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/pravega-wire-protocol-0.2.0/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/yew-router-0.15.0/log.txt
- Invalid suggestion to change `Trait::thing` to `<dyn Trait>::thing` without generic args:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/biofile-1.10.2/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/epoxy_streams-0.3.1/log.txt
- Invalid suggestion to chanage `<Trait>::..` to `<<dyn Trait>>::..`: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/extended-primitives-0.3.5/log.txt 
- Missing `dyn` with macro_rules:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/crossbeam-channel-0.5.1/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/text_io-0.1.9/log.txt
- Misssing `dyn` with proc macro, which is quite possibly using the wrong span:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/err-derive-0.3.0/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/miniserde-0.1.14/log.txt
- Difference in closure captures causes lifetime issues:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/finality-grandpa-0.14.3/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/tantivy-0.15.3/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/tetsy-finality-grandpa-0.13.0/log.txt
- `"{}", `-suggestion from non_fmt_panics lint gets applied seven times, somehow:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/image-0.23.14/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/mockers-0.21.0/log.txt
- Something with `non_fmt_panics`: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/nphysics3d-0.24.0/log.txt
- Something with `pat`/`pat_pattern`: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/stakker-0.2.4/log.txt

Broken due to fewer features enabled on dependency because of `resolver = "2"`:

- `syn`:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/asn1rs-model-0.2.2/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/cargo-sync-readme-1.1.0/log.txt
  -  https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/odata_client_codegen-0.1.0/log.txt
- `rand_core`: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/dusk-pki-0.8.0/log.txt
- `serde`: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/mavlink-0.9.0/log.txt

???:

- https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/dioxus-core-0.1.2/log.txt
- https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/libqaul-types-0.1.0/log.txt
- https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/rbx_binary-0.6.2/log.txt
- Two different issues. one about `;` in macros (??), and one about `non_fmt_panics` (?): https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/nphysics2d-0.24.0/log.txt
- https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/seq_io-0.4.0-alpha.0/log.txt
- 'overflow evaluating the requirement ..': https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/sv-parser-0.11.1/log.txt
- proc macro gets angry at migrated code: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/telebot-0.3.1/log.txt

Expected / probably won't fix:

- `#[deny(unused_qualifications)]` triggering with new prelude:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/ark-poly-commit-0.3.0/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/rio_xml-0.6.1/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/snarkvm-polycommit-0.7.8/log.txt
- `#![deny(warnings)]` triggering `unused_imports` with new prelude:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/earlgrey-0.3.0/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/if-watch-0.2.2/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/serde_url_params-0.2.1/log.txt
- `#![deny(unused_imports)]` with new prelude:
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/glucose-0.2.3/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/minicbor-0.10.0/log.txt
- `...` pattern syntax in generated code: https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/isbn-0.2.0/log.txt (already fixed upstream in the repo, but hasn't been published to crates.io yet)

**Comment by m-ou-se** [comment]
cc @rust-lang/wg-rfc-2229 for these three:

  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/finality-grandpa-0.14.3/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/tantivy-0.15.3/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/tetsy-finality-grandpa-0.13.0/log.txt

**Comment by m-ou-se** [comment]
@ehuss Any idea what's up with the `failed to automatically apply fixes suggested by rustc to crate` warnings? The same suggestions seem to work fine in other situations.

**Comment by ehuss** [comment]
`failed to automatically apply fixes suggested by rustc to crate` means that after applying the suggested fixes from rustc, it then runs `cargo check` again to validate them, and that `cargo check` returned an error.  You can then scan the output for an "error" message.

I can't reproduce the error with `abortable_parser` either.  I think an action item there is to enhance the error message to include the process exit code so we can see if there is an abnormal exit.  I'm a bit baffled on how that could happen.

**Comment by m-ou-se** [comment]
@ehuss Can you update/rebase your cargo 2021-crater branch to include the jobserver fix?

**Comment by ehuss** [comment]
@m-ou-se It should be updated now.

**Comment by m-ou-se** [comment]
@craterbot check p=1

**Comment by m-ou-se** [comment]
All "*regressed: root results*" and "*/tmp/fixit 'dependency' regressions*": https://hackmd.io/xltX-gYFRpO-2OHDAW9Sag

All other "*regressed: dependencies*": https://hackmd.io/go3uH7Y4T-ad6YbcNdvD8w

**Comment by camelid** [comment]
Rust 2021 has been stabilized on beta and is likely going to be released soon, so I think this PR can be closed, right?

**Comment by JohnCSimon** [comment]
> Rust 2021 has been stabilized on beta and is likely going to be released soon, so I think this PR can be closed, right?


Ping from triage: 
@ehuss what would you like to do with this PR?

**Pull request closed without merging**
