### PR TITLE
Add regression test for #74400

### LINKED ISSUE #74400: Type mismatch in function arguments E0631, E0271 are falsely recognized as E0308 mismatched types
Regression from `1.45.0-beta.4 (2020-07-13 e99e6422a2f799fc86a3)` to `1.46.0-nightly (2020-07-15 7e11379f3b4c376fbb9a)`.

The following code yields an incorrect error:
```rust
use std::convert::identity;

pub fn is_sorted_and_has_duplicates_by<T, S: PartialEq + PartialOrd>(
    data: &[T],
    key: impl Fn(&T) -> S,
) -> Option<&T> {
    unimplemented!()
}

pub fn is_sorted_and_has_duplicates<T: PartialEq + PartialOrd>(data: &[T]) -> Option<&T> {
    is_sorted_and_has_duplicates_by(data, identity)
}
```
On beta, this gives:
```
error[E0631]: type mismatch in function arguments
  --> src/lib.rs:11:43
   |
3  | pub fn is_sorted_and_has_duplicates_by<T, S: PartialEq + PartialOrd>(
   |        ------------------------------- required by a bound in this
4  |     data: &[T],
5  |     key: impl Fn(&T) -> S,
   |               ----------- required by this bound in `is_sorted_and_has_duplicates_by`
...
11 |     is_sorted_and_has_duplicates_by(data, identity)
   |                                           ^^^^^^^^
   |                                           |
   |                                           expected signature of `for<'r> fn(&'r T) -> _`
   |                                           found signature of `fn(_) -> _`

error[E0271]: type mismatch resolving `for<'r> <fn(_) -> _ {std::convert::identity::<_>} as std::ops::FnOnce<(&'r T,)>>::Output == _`
  --> src/lib.rs:11:5
   |
3  | pub fn is_sorted_and_has_duplicates_by<T, S: PartialEq + PartialOrd>(
   |        ------------------------------- required by a bound in this
4  |     data: &[T],
5  |     key: impl Fn(&T) -> S,
   |                         - required by this bound in `is_sorted_and_has_duplicates_by`
...
11 |     is_sorted_and_has_duplicates_by(data, identity)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected bound lifetime parameter, found concrete lifetime
```

On nightly, this:
```
error[E0308]: mismatched types
  --> src/lib.rs:11:5
   |
11 |     is_sorted_and_has_duplicates_by(data, identity)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected type `std::ops::FnOnce<(&T,)>`
              found type `std::ops::FnOnce<(&T,)>`
```

### PR DESCRIPTION
**Pull request by vandenheuvel**
Closes #74400 by adding a regression test.

### CODE REVIEW

**Comment by vandenheuvel** [comment]
@Mark-Simulacrum 

I'm trying to add a regression test for #74400 because it seems resolved: the nightly on the playground gives the right error, see [this comment](https://github.com/rust-lang/rust/issues/74400#issuecomment-909031339). Yet, when I add the test as in the PR linked above, I get the old, wrong error. I tried the same thing with a local project and latest nightly, and got the same result.

Could you help me understand, why running the test using `x.py` gives a different error?

**Comment by Mark-Simulacrum** [comment]
I pushed up a locally blessed version which I think should work in CI as well. I'm not sure, but it's possible you were locally creating the stderr file with an older master? It looks like it branched off in february, which may have been before the recent-ish improvements in the last month or so?

**Comment by vandenheuvel** [comment]
@Mark-Simulacrum I think this is ready.

**Pull request merged**
