### PR TITLE
Updating docs for std::sync::Weak #29377

### PR DESCRIPTION
**Pull request by projektir**
I will duplicate these changes for [`std::rc::Weak`] if they are approved.

[`std::rc::Weak`]: https://doc.rust-lang.org/std/rc/struct.Weak.html

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
At first blush, it looks okay, but you may want to pick a reviewer who is familiar with the Weak stuff.  Maybe @eddyb would know of someone.

**Comment by eddyb** [comment]
Well, cc @rust-lang/libs @rust-lang/docs

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @projektir!

**Comment by alexcrichton** [comment]
@bors: retry

* appveyor git faiulre https://github.com/rust-lang/rust/issues/40474

**Pull request merged**
