### PR TITLE
Fix an inconsistency in Linux version of TcpListener::accept

### LINKED ISSUE #67027: Linux version of nonblocking TcpListener::accept differs from other platforms
If `TcpListener` is in non-blocking mode then accepted streams inherit this property on all platforms except Linux, where `accept4` is used instead of `accept`.

This code (with commented out `stream.set_nonblocking(false)`)  unexpectedly works as expected on Linux only, because `stream` is in blocking mode.

```
 let listener = TcpListener::bind("0.0.0.0:3333").unwrap();
    listener.set_nonblocking(true).expect("set nonblocking");

    println!("Server listening on port 3333");
    loop {
        match listener.accept() {
            Ok((mut stream, _)) => {
                println!("New connection");
                //stream.set_nonblocking(false).expect("nonblock");
                stream
                    .set_read_timeout(Some(Duration::from_secs(10)))
                    .expect("set timeout");
                let mut data = [0 as u8; 2];
                match stream.read_exact(&mut data) {
                    Ok(_) => println!("Got message!"),
                    Err(e) => println!("Failed to receive data: {:?}", e),
                }
            }
            Err(_e) => {
                println!("Error: {:?}", e);
            }
        }
    }

```

`accept4` man page explains:
```
On Linux, the new socket returned by accept() does not inherit file status
flags such as O_NONBLOCK and O_ASYNC from the listening socket. 
This behavior differs from the canonical BSD sockets implementation.
Portable programs should not rely on inheritance or noninheritance
of file status flags and always explicitly set all required flags on the socket
returned from accept(). 
```

I agree that code above should also set non_blocking explicitly, at the same time it would be nice to behave the same way on all platoftms.

## Meta
rustc --version --verbose
rustc 1.37.0 (eae3437df 2019-08-13)
binary: rustc
commit-hash: eae3437dfe991621e8afdc82734f4a172d7ddf9b
commit-date: 2019-08-13
host: x86_64-unknown-linux-gnu
release: 1.37.0
LLVM version: 8.0

(but it applies to multiple versions)

### PR DESCRIPTION
**Pull request by hashmap**
If TcpListener is in non-blocking mode then accepted streams inherit
this property on all platforms except Linux, where accept4 is used
instead of accept.

This fix checks if a listener is in non-blocking mode and pass the
corresponding flag to accept4.

Fixes https://github.com/rust-lang/rust/issues/67027

### CODE REVIEW

**Comment by sfackler** [comment]
That implementation is racy with concurrent changes to the blocking-ness of the socket. It also doubles the number of system calls per accept call.

We generally try to expose the system primitive without a lot of extra stuff on top. "`TcpListener::accept` calls `accept4(2)`" is a lot simpler than "`TcpListener::accept` calls `accept4(2)` and then tries to patch other bits of the socket up". CLOEXEC is the ~one exception to this rule since it's so important.

**Comment by hashmap** [comment]
Agree reg race, I found unfortunate that `set_nonblocking` and friends don’t take a mutable reference, while it doesn’t mutate any state in rust code it does system wide. 

It also doesn’t allow to introduce any state to avoid extra syscall, however that design may be error prone. I think for non-blocking io in the majority of the cases we would have the same amount of syscalls, while doubling it for blocking io. 

I’m not sure about the last point. I think about complexity from api user point of view. How many people needs to know details of impl and how hard to figure it out? At the same time there are millions of users of this method and for them we have a complex story - “what you get depends on listener state unless you are on linux then you always get blocking stream”. Also there is no single hint that this call is platform-dependent.

**Comment by JohnCSimon** [comment]
Ping from triage: @hashmap can you please address the merge conflicts?

**Comment by JohnCSimon** [comment]
Pinging again from triage: @hashmap can you post the status of this pr? Thanks.

**Comment by hashmap** [comment]
Sorry, I've finally rebased this pr.

**Comment by sfackler** [comment]
I'm still not convinced that the standard library should be trying to fudge this.

@rfcbot fcp close

**Comment by RalfJung** [comment]
> Also there is no single hint that this call is platform-dependent.

Adding documentation to explain this better would probably makes sense, if the decision is to not change behavior.

**Pull request closed without merging**
