### PR TITLE
submodules: Update clippy

### PR DESCRIPTION
**Pull request by tesuji**
r? @Manishearth
Fixes clippy toolstate in https://github.com/rust-lang/rust/pull/63228#issuecomment-517886963

### CODE REVIEW

**Comment by flip1995** [comment]
Would you mind bumping clippy again to the newest commit? I'd really like to have rust-lang/rust-clippy#4337 in the next nightly :smile:

**Comment by lzutao** [comment]
cc @oli-obk

**Comment by lzutao** [comment]
Clippy broke again with #59369. Hence the PR description changed.

**Comment by lzutao** [comment]
It is ready again. cc @Manishearth

**Pull request merged**
