### PR TITLE
Use BOLT in CI to optimize `librustc_driver`

### PR DESCRIPTION
**Pull request by Kobzol**
Based on https://github.com/rust-lang/rust/pull/94381.

r? @ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
The cycle results are not bad, but nothing too impresive sadly. Maybe this isn't really worth it. I think that the Google team that tried this has similar experiences. I wonder if BOLT is less effective for Rust libraries vs C/C++ in general.

Another reason might be that BOLT is more effective for binaries than for shared libraries. I'll try to statically link rustc and apply BOLT to it, to see what happens.

**Comment by joshtriplett** [comment]
> Another reason might be that BOLT is more effective for binaries than for shared libraries. I'll try to statically link rustc and apply BOLT to it, to see what happens.

I'd love to see results for statically linking rustc in general, to see how much benefit that provides.

**Comment by lqd** [comment]
There are results of a few different variants involving static linking in https://github.com/rust-lang/rust/pull/97154

**Comment by Kobzol** [comment]
Hmm, cycle results aren't bad, but the instruction regressions are pretty scary. Although it seems that they only occur for the smallest crates 🤔

**Comment by nnethercote** [comment]
Wall-time results are pretty good, too.

**Comment by Kobzol** [comment]
@bors try @rust-timer queue

(running perf to test https://github.com/rust-lang/rustc-perf/pull/1490, nothing to see here)

**Comment by Kobzol** [comment]
It does work, it just didn't work at the time of posting that comment :)

**Comment by Kobzol** [comment]
The results don't look bad at all. I'll revisit this after https://github.com/rust-lang/rust/pull/115554

**Comment by chriswailes** [comment]
Android saw a 12% speedup from applying BOLT to `libLLVM` and `librustc_driver`.

**Comment by Kobzol** [comment]
Implemented in https://github.com/rust-lang/rust/pull/116352.

**Pull request closed without merging**
