### PR TITLE
Remove deprecated `collections` crate.

### PR DESCRIPTION
**Pull request by leoyvens**
The real `collections` was merged with `alloc`, this facade was introduced [in this PR](https://github.com/rust-lang/rust/pull/42720) to give `#[no_std]` users time to adapt. This was done at least two cycles ago, now we can consider removing it for good.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@leodasvacas Looks like Travis is failing here, which is probably because of [this line](https://github.com/rust-lang/rust/blob/942f31f5eacfc8cbd40c20bbcabc9d37add37410/src/bootstrap/doc.rs#L493). I think you should just be able to remove collections from there and this should work from there.

**Comment by leodasvacas** [comment]
@Mark-Simulacrum Thanks, fixed it!

**Comment by Mark-Simulacrum** [comment]
I think this is good to go, but I think we should at least get some signoff from the libs team.. @rust-lang/libs, thoughts? Feel free to run fcp if that's easier (I don't think I can start it).

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
