### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by jieyouxu**
Successful merges:

 - #126704 (Added SHA512, SM3, SM4 target-features and `sha512_sm_x86` feature gate)
 - #127095 (Migrate `reproducible-build-2` and `stable-symbol-names` `run-make` tests to rmake)
 - #127586 (Add `#[must_use]` to some `into_raw*` functions.)
 - #128161 (nested aux-build in tests/rustdoc/ tests)
 - #128303 (Enable `std::io::copy` specialisation for `std::pipe::{PipeReader, PipeWriter}`)
 - #128356 (Migrate `cross-lang-lto-clang` and `cross-lang-lto-pgo-smoketest` `run-make` tests to rmake)
 - #128368 (Formatting tweaks)
 - #128404 (Revert recent changes to dead code analysis)
 - #128483 (Still more `cfg` cleanups)
 - #128557 (chore: use shorthand initializer)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=126704,127095,127586,128161,128303,128356,128368,128404,128483,128557)

### CODE REVIEW

**Comment by jieyouxu** [comment]
Looks like average #127883.
@bors retry

**Comment by jieyouxu** [comment]
Have no clue which caused the failure...

**Comment by matthiaskrgr** [comment]
its https://github.com/rust-lang/rust/pull/128404

**Pull request closed without merging**
