### PR TITLE
Preserve UTF-8 + UTF-8 = UTF-8 for Wtf8Buf

### PR DESCRIPTION
**Pull request by workingjubilee**
When using `extend_from_slice` to add UTF-8 bytes that aren't statically verified as UTF-8 (by being `str`) to Wtf8Buf, this should make `is_known_utf8` remain `true` if the addition is also UTF-8.

r? @ghost

try-job: x86_64-msvc

### CODE REVIEW

**Comment by workingjubilee** [comment]
r? libs

**Comment by Amanieu** [comment]
What is the purpose of this? `is_known_utf8` is just a hint, if it's false then we check the whole string for being valid UTF-8 anyways.

**Comment by workingjubilee** [comment]
honestly? mostly it just bugs me on some level if you take two PathBufs that are UTF-8 and combine them together via `.join` or something, due to `AsRef<Path>` erasing the originals you started with (drilling down to the reference forms), you lose the hint even if one is a zillion bytes and the other is 1 byte.

**Comment by workingjubilee** [comment]
...while that absurdist case obviously doesn't happen, it does seem to me that many cases are long path + small path.

**Comment by Amanieu** [comment]
`is_known_utf8` is only used by `into_string` and `into_string_lossy`, so it's a bit of a waste to eagerly compute it if you never end up calling those methods.

If you still feel strongly about it, perhaps you could change it to `known_utf8_bytes` which indicates the number of leading bytes that are known to be utf-8. That way only the tail end of the string would need to be checked for utf8 when converting to a string.

**Comment by workingjubilee** [comment]
> is_known_utf8 is only used by into_string and into_string_lossy, so it's a bit of a waste to eagerly compute it if you never end up calling those methods.

ah, true.

> If you still feel strongly about it, perhaps you could change it to known_utf8_bytes which indicates the number of leading bytes that are known to be utf-8. That way only the tail end of the string would need to be checked for utf8 when converting to a string.

hmm. I feel like that's the wrong direction to go in terms of hypothetical overhead that Wtf8Buf imposes on a program. I think I basically wanted to open the PR _because_? to get some feedback, I guess? I don't particularly mind not landing this. thanks for review!

**Pull request closed without merging**
