### PR TITLE
Allow registering MIR-passes through compiler plugins

### PR DESCRIPTION
**Pull request by oli-obk**
depends on #31324

r? @nagisa

### CODE REVIEW

**Comment by nagisa** [comment]
This looks okay to me.

**Comment by nagisa** [comment]
Rebase?

**Comment by oli-obk** [comment]
done

**Comment by oli-obk** [comment]
no clue where that error came from:

```
error: error pattern ' build without -C codegen-units for more exact errors' not found!
status: exit code: 101
command: x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/test/compile-fail/asm-src-loc-codegen-units.rs -L x86_64-unknown-linux-gnu/test/compile-fail/ --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage2-x86_64-unknown-linux-gnu --cfg rtopt -C rpath -O -L x86_64-unknown-linux-gnu/rt -C codegen-units=2
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'error: codegen-1<inline asm>:1:2: error: invalid instruction mnemonic 'nowayisthisavalidinstruction'
        nowayisthisavalidinstruction
        ^
' panicked at 'Box<Any>', 
../src/libsyntax/errors/mod.rs:note607: 
build without -C codegen-units for more exact errorsnote: Run with `RUST_BACKTRACE=1` for a backtrace.

error: aborting due to previous error
error: aborting due to worker thread panic

------------------------------------------

thread '[compile-fail] compile-fail/asm-src-loc-codegen-units.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/compiletest/runtest.rs:1527
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [compile-fail] compile-fail/asm-src-loc-codegen-units.rs
```

**Comment by nagisa** [comment]
@bors retry

Seems spurious to me: the error message is 2 different error messages interleaved which makes the actual error we’re looking for invalid.

**Comment by nrc** [comment]
What is the motivation for this? It would be nice if changes like this could get some discussion - an internals thread, or even an issue being opened beforehand. I feel we have been burnt by llvm plugin passes and don't want to repeat that experience. At the very least this facility should be documented.

**Comment by oli-obk** [comment]
Sorry about that. Discussion start: https://internals.rust-lang.org/t/mir-compiler-plugins-for-custom-mir-passes/3166

**Pull request merged**
