### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors retry

don't see an actual failure?

**Comment by blyxyas** [comment]
Don't mind me, just doing an experiment

@bors try @rust-timer queue scenario=clippy

**Comment by blyxyas** [comment]
Hmmmm... It seems like bors is not even recognizing the command.
I'll try in a few days, when the new sync PR is open (before the merge) and let's see if that works.

**Comment by flip1995** [comment]
@blyxyas bors ignores all closed PRs

**Pull request merged**
