### PR TITLE
make core::str::next_code_point work on arbitrary iterator

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by alexcrichton** [comment]
These are in theory internal only functions that are only exported as an implementation detail between libcore/libcollections, but does this change mean that you're thinking of using them externally?

**Comment by strake** [comment]
I was considering to use `next_code_point` in some code i'm writing, but since recognized these functions assume valid UTF-8, and think i may rather need a function to return 0xFFFD for invalid input; see [this PR](https://github.com/rust-lang/rust/pull/33907). The comment in `next_code_point` says "performance is sensitive to the exact formulation here" so i doubt you would want these modified to do so. Nonetheless, i saw these functions only need an arbitrary `Iterator` or `DoubleEndedIterator` rather than a `[u8]::Iter`, and i think if we have a such a decoder in libcore it would make sense to also have a version assuming valid input.

**Comment by aturon** [comment]
This seems fine to me -- thanks for the PR!

@bors: r+

**Pull request merged**
