### PR TITLE
`has_typeck_results` doesnt need to be a query

### PR DESCRIPTION
**Pull request by compiler-errors**
self-explanatory

### CODE REVIEW

**Comment by jackh726** [comment]
r=me whether or not you want to check perf

**Comment by compiler-errors** [comment]
extremely doubt that this will be negative, but yeah, that's a good thing to check

@bors try @rust-timer queue

**Comment by compiler-errors** [comment]
huh???

**Comment by compiler-errors** [comment]
ah, rebase

@bors r=jackh726

**Comment by compiler-errors** [comment]
whoops forgot to reapprove after formatting

@bors r=jackh726

**Comment by compiler-errors** [comment]
wtf ci

@bors retry

**Pull request merged**
