### PR TITLE
ci: finish the migration to azure

### PR DESCRIPTION
**Pull request by emilyalbini**
This moves to azure the last builders as we discussed on Discord last night.

r? @alexcrichton

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
Unless you want a review specifically by Alex, r=me

**Comment by alexcrichton** [comment]
Fwiw I don't think we can delete Travis and appveyor yet since bors is still listening for those services to complete, so it may be best to just add one null job on both and we can later change bors after this lands

**Comment by pietroalbini** [comment]
Uh good point @alexcrichton, added a dummy job on each of them.

@bors r=Mark-Simulacrum retry

**Comment by Xanewok** [comment]
Now only Miri failed. @RalfJung is it spurious? Can we retry it or does it need an update?

**Comment by RalfJung** [comment]
This doesn't look spurious. I have never seen this failure before:
```
expected stdout:
args


diff of stdout:

 args
```
And only on Windows? Things work fine on our own AppVeyor CI.

What changed compared to the previous AppVeyor tools builder?

**Comment by pietroalbini** [comment]
> What changed compared to the previous AppVeyor tools builder?

Our configuration scripts are the same between AppVeyor and Azure, but the CI image is of course different. I don't know what are the exact changes though.

**Comment by RalfJung** [comment]
Looks like somehow ether the encoding of the process arguments into a Windows command string, or the decoding (inside the interpreted program) into a list again, fails now where it worked before. No idea how that can happen; differences in the host platform shouldn't "leak" into the interpreted program.

This is using the same architecture / target triple, right?

You could try updating Miri to [this branch](https://github.com/rust-lang/miri/tree/azure-debug). That will definitely fail to land, but it'll tell us a bit more.

Alternatively, if this is an Azure vs AppVeyor thing, it could help to have Azure CI for Miri. We probably eventually want that anyway. But I won't have time to set that up any time soon, I'm afraid.

**Comment by RalfJung** [comment]
Looking at this again... wait a second. "normalized" and "expected" stdout look the same, and still compiletest complains they are different?

Is this a `\n` vs `\r\n` thing? Does maybe the Miri git repo get clone with different settings so that the line endings in the reference file are different?

**Comment by mati865** [comment]
Clippy had similar CRLF vs LF issue when adding Windows based Travis job (Appveyor was working just fine). Possibly Windows Azure jobs have misconfigured `git` so it changes line endings when cloning the repo.
The workaround was to enforce line endings with `.gitattributes`: https://github.com/rust-lang/rust-clippy/blob/fffb2691a3d2d6bbd9521ff35d98301b2cdf4298/.gitattributes

**Comment by RalfJung** [comment]
Thanks! Let's try a `.gitattributes` for Miri as well then. https://github.com/rust-lang/miri/pull/816 is just waiting for an AppVeyor slot to land... those slots can be hard to get though. :/

**Comment by RalfJung** [comment]
The Miri PR made it. :)

So if you include that in here, maybe that helps with the line-ending problems?

**Comment by RalfJung** [comment]
@pietroalbini I think you have conflicts with master now? There was a Miri update there since this branch started.

**Comment by pietroalbini** [comment]
Thanks for noticing that @RalfJung...

@bors r=Mark-Simulacrum p=1000

**Pull request merged**
