### PR TITLE
Rollup of 28 pull requests

### PR DESCRIPTION
**Pull request by jhpratt**
Successful merges:

 - #132605 (CI: increase timeout from 4h to 6h)
 - #133042 (btree: add `{Entry,VacantEntry}::insert_entry`)
 - #133070 (Lexer tweaks)
 - #133136 (Support ranges in `<[T]>::get_many_mut()`)
 - #133140 (Inline ExprPrecedence::order into Expr::precedence)
 - #133248 (CI: split x86_64-msvc-ext job)
 - #133282 (Shorten the `MaybeUninit` `Debug` implementation)
 - #133304 (Revert diagnostics hack to fix ICE 132920)
 - #133326 (Remove the `DefinitelyInitializedPlaces` analysis.)
 - #133362 (No need to re-sort existential preds in relate impl)
 - #133367 (Simplify array length mismatch error reporting (to not try to turn consts into target usizes))
 - #133394 (Bail on more errors in dyn ty lowering)
 - #133410 (target check_consistency: ensure target feature string makes some basic sense)
 - #133411 (the emscripten OS no longer exists on non-wasm targets)
 - #133419 (Added a doc test for std::path::strip_prefix)
 - #133430 (Tweak parameter mismatch explanation to not say `{unknown}`)
 - #133435 (miri: disable test_downgrade_observe test on macOS)
 - #133443 (Remove dead code stemming from the old effects desugaring (II))
 - #133449 (std: expose `const_io_error!` as `const_error!`)
 - #133450 (remove "onur-ozkan" from  users_on_vacation)
 - #133454 (Update test expectations to accept LLVM 'initializes' attribute)
 - #133458 (Fix `Result` and `Option` not getting a jump to def link generated)
 - #133462 (Use ReadCache for archive reading in bootstrap)
 - #133464 (std::thread: avoid leading whitespace in some panic messages)
 - #133467 (tests: Add recursive associated type bound regression tests)
 - #133470 (Cleanup: delete `//@ pretty-expanded` directive)
 - #133473 (tests: Add regression test for recursive enum with Cow and Clone)
 - #133481 (Disable `avr-rjmp-offset` on Windows for now)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=132605,133042,133070,133136,133140,133248,133282,133304,133326,133362,133367,133394,133410,133411,133419,133430,133435,133443,133449,133450,133454,133458,133462,133464,133467,133470,133473,133481)

### CODE REVIEW

**Comment by BoxyUwU** [comment]
@bors retry

yielding to a last minute stable release backport as there is only a couple days before release

**Comment by BoxyUwU** [comment]
oh right p=28 is more than 20 lol...
@bors retry

**Comment by jhpratt** [comment]
I had just checked the queue and was about to decrease this to 10. Minor detail, all in all...definitely prioritize the backport.

**Comment by lqd** [comment]
Please correct me if I'm wrong but isn't this why rollups are defined to be at p=5 https://forge.rust-lang.org/release/rollups.html#making-a-rollup so that high-prio PRs needing to land can set p>5 and be sure to be in front of existing rollups and of rollups that would be created after the high-priority PR?

**Comment by compiler-errors** [comment]
rollups this size are way too large and better broken into several rollups that can merge one after the other (or begin testing immediately after one fails). the chances of a 30 PR large rollup merging even if it contains all rollup=always PRs is pretty slim lol

**Comment by jhpratt** [comment]
@lqd Looks like it should have been, my mistake. I've always seen it as the number of PRs included.

@compiler-errors Fair point! I saw the queue was nearly 50 PRs accepted and didn't consider splitting it into multiple rollups.

**Comment by BoxyUwU** [comment]
I think generally people don't really follow that forge reccomendation because i see p=12 p=9 whatever rollups all the time

**Pull request closed without merging**
