### PR TITLE
rustdoc: remove redundant CSS `#source-sidebar, #sidebar-toggle`

### PR DESCRIPTION
**Pull request by notriddle**
These two elements are always nested below `<nav class="sidebar">`, and will inherit the font from their parent.

These selectors were added in 93520d2ad145b791b1b1a6c71cdea65b1943ffb6, and became redundant in 07e3f998b1ceb4b8d2a7992782e60f5e776aa114 when the source sidebar elements became nested below `nav.sidebar`.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup

**Comment by Nemo157** [comment]
This is used in at least one place on docs.rs, not sure if there will be any styling issues without it

https://github.com/rust-lang/docs.rs/blob/66273eebf9c342bbed64508276c4deb762ab67db/templates/style/rustdoc-2021-12-05.scss#L43

**Comment by GuillaumeGomez** [comment]
It shouldn't be impacted. On docs.rs it's needed because of the docs.rs top navbar.

**Comment by Nemo157** [comment]
Ah, I should have looked at the diff, I thought it was removing the id from the html too :sweat_smile:

**Pull request merged**
