### PR TITLE
Enable combining `+crt-static` and `relocation-model=pic` on `x86_64-unknown-linux-gnu`

### PR DESCRIPTION
**Pull request by bossmc**
Modern `gcc` versions support `-static-pie`, and `rustc` will already fall-back to `-static` if the local `gcc` is too old (and hence this change is optimistic rather than absolute).  This brings the `-musl` and `-gnu` targets to feature compatibility (albeit with different default settings).

Of note a `-static` or `-static-pie` binary based on glibc that uses NSS-backed functions (`gethostbyname` or `getpwuid` etc.) need to have access to the `libnss_X.so.2` libraries and any of their dynamic dependencies.

I wasn't sure about the `# only`/`# ignore` changes (I've not got a `gnux32` toolchain to test with hence not also enabling `-static-pie` there).

### CODE REVIEW

**Comment by bossmc** [comment]
The build failure appears to be the fall-back logic from `-static-pie` to `-static` kicking in because (I assume) the linker doesn't support that flag.

I don't know what linker is being used in that build, if it's `clang-10` that supports the flag (it's been supported since `clang-9`) and if it's the standard `gcc` (which by default is `gcc-9` on focal) that also supports the flag (it's been supported since `gcc-8`).  

The test as written assumes that the linker supports `-static-pie` because it's fairly tricky to dynamically detect support (need to work out what linker `rustc` will use, and then work out if it supports the flag).

Is there a possibility to either upgrade the linker in the tests?  Or to provide a hint to the test scripts so they can expect the fall-back behaviour if appropriate?

**Comment by JohnCSimon** [comment]
Triage: 
@bossmc - this has sat idle for a few weeks - maybe try pinging the appropriate people again?

**Comment by bossmc** [comment]
I'm not sure who's the appropriate people for this change, I was trusting Liz Lemon that @estebank was a good choice, and I don't know if there's anyone else who would also be a sensible choice.

**Comment by crlf0710** [comment]
@bossmc Triage: I'd suggest you reach the t-compiler people on Zulip to move this forward. In the mean time, i'll convert this pr to draft to remove this from triage cycle.

**Comment by estebank** [comment]
Apologies for the unresponsiveness, I'd made a point of coming back to it and forgot.

The code changes look reasonable, but I am not the right person to help with the test failure.

Could someone in @rust-lang/compiler take a look?

**Comment by nagisa** [comment]
> Is there a possibility to either upgrade the linker in the tests? Or to provide a hint to the test scripts so they can expect the fall-back behaviour if appropriate?

Rust currently supports fairly ancient GCC and clang both for [building rustc](https://github.com/rust-lang/rust/#building-on-a-unix-like-system) itself as well as a toolchain. Bumping to fairly recent versions of  gcc/clang would likely be a [MCP-level material](https://forge.rust-lang.org/compiler/mcp.html) if not an entire RFC.

cc @rust-lang/release for opinions though.

**Comment by nagisa** [comment]
(in practice we've been okay with conditional support for certain toolchain features in the past, I don't see why we wouldn't do that here as well, after adding some support to compiletest to check if the linker supports the necessary features)

**Comment by bossmc** [comment]
Just to clarify - this `rustc` change doesn't _require_ a newer linker, it just enables taking advantage of the linker's `-static-pie` feature if it's available.

If we want CI to build with a minimal linker version then the test becomes a regression test rather than a feature test (testing that if the compiler is asked for static pie but the linker doesn't support it then it builds a static (non-pie) binary instead).  It might also be useful to have a newer linker in CI (as well?) to test the function when the linker _does_ support it?  At the very least we'd need to not break `x.py test` for people who's native toolchain _does_ support the function.

(your follow-up message has overlapped me writing this) I agree that this would be best with conditional support in `compiletest` - I'm happy to try and implement that as part of this MR if people agree that's the right direction to go.

**Comment by nagisa** [comment]
Adjusting CI to somehow allow for multiple linker versions might be an option too, but I don't know enough about our CI set up to tell for sure. @Mark-Simulacrum may have a better idea?

**Comment by Mark-Simulacrum** [comment]
CI for x86_64 tests with a Ubuntu 20.04 base image today (https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/x86_64-gnu/Dockerfile). I believe many other platforms do the same or similar; indeed, I'm not actually confident we run tests on the more ancient builders we use for dist jobs.

It sounds like we need a more modern gcc/clang for the test suite to pass; I think likely it makes sense to do this:

* Add support for something like a needs-gcc-version flag to compiletest (we already do this for LLVM, for example). Ideally we'd make sure that the test can run if *either* clang or gcc of the appropriate minimum is available. Since this is a make test it'd also be fine with me to add the support within the script, just exiting early from the test if we don't see a new enough gcc/clang available.
* Add a test that confirms the ambient environment 'works' with this PR (i.e., we successfully fallback to not supporting).

I can't really comment on the change itself, so not sure if it makes sense, but in terms of verifying it's support this seems like the reasonable approach. The second step there can plausibly be skipped, depending on how the code is laid out -- @nagisa or whoever reviews this can decide that :) Generally though progressively enhancing seems good; ideally we'd provide some signal to the user that they can get this combination working if they get a more modern linker. Not sure we have any nice way of doing that though, so may not be worth it -- eventually it'll just work for folks.

**Comment by bossmc** [comment]
(As a note to myself, but possibly interesting to others)

You can get the versions of `gcc`/`clang` with the `--version` flag, except that's very "human-oriented":

```
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
Ubuntu clang version 13.0.1-++20211027043036+08e3a5ccd952-1~exp1~20211027163603.15
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

So instead, one can use the "magic `#define` variables" that the two compilers use (and then abuse the pre-processor to get the values of those macros):

```
$ echo __GNUC__ __GNUC_MINOR__ __GNUC_PATCHLEVEL__ | gcc -x c -E - | grep -ve '^#'
9 3 0
$ echo __clang_major__ __clang_minor__ __clang_patchlevel__ | clang -x c -E - | grep -ve '^#'
13 0 1
```

In fact, for this test we just need to check the major versions (8 for `gcc` and 9 for `clang`) so this seems pretty easy to do in the Makefile (or more likely in a script that the Makefile calls).

**Comment by bossmc** [comment]
@Mark-Simulacrum I've added a first pass at what we've been discussing (I'm pretty sure I can commonize the `check_X_version` scripts but I wanted to check that you're happy with the direction this is going before I go down a rabbithole).

**Comment by Mark-Simulacrum** [comment]
The test looks good to me - a little on the unfortunate side that we have to do this version detection, but generally seems OK to me. We should make sure it actually does run in our CI environment -- did you manage to verify that yet? I suspect the llvm-12 builder on PR CI should have a relatively recent gcc or clang.

**Comment by bossmc** [comment]
Yeah, the version check is really a proxy for `rustc`'s built-in "does the linker support the `-static-pie` argument" code, which is the code we're (effectively) testing... in a perfect world we'd test that on older linkers we get a static, _non-PIE_ executable but that's not a guarantee, it's just a practicality of the fallback behaviour so testing for it seems overly specified.

How would I go about verifying this change on the CI environment?  I've tested this pretty heavily locally (by testing against `gcc-7`, `gcc-8`, `gcc-9`, `clang-8`, `clang-9` and `clang-13`) but maybe there's a quick way to kick off a "full CI" test run?

**Comment by Mark-Simulacrum** [comment]
I think just making the test itself fail, such that if the version check is succeeding (as we want) then we observe a CI failure, but if CI still passes that means we're not seeing the version check succeed (which is not what we want). PR CI should be sufficient to observe that, I think.

**Comment by bossmc** [comment]
https://github.com/rust-lang/rust/runs/4289582821?check_suite_focus=true is a build failing due to a deliberately added `exit 4` just after we've confirmed that (a) the linker in the CI is new enough to support `-static-pie` and (b) we've checked that `rustc` has built a relocatable, static ELF executable (i.e. just after the test has passed in the meaningful way).

I'll revert that change now so this MR is mergeable again.

**Comment by nagisa** [comment]
Seems reasonable to me, could you please squash the commit history to remove the testing commits?

r=me after.

**Comment by bossmc** [comment]
@nagisa - done, thanks!

**Comment by JohnCSimon** [comment]
triage: looks like this is ready for review

@rustbot label: -S-waiting-on-author +S-waiting-on-review

**Pull request merged**
