### PR TITLE
Properly detect overflow in Instance ± Duration.

### LINKED ISSUE #42622: Detect SystemTime overflow in debug mode
```rust
use std::time::{Duration, UNIX_EPOCH};
use std::u64;

fn main() {
    let t = UNIX_EPOCH + Duration::new(u64::MAX, 0) + Duration::new(2, 0);
    println!("{}", t.duration_since(UNIX_EPOCH).unwrap().as_secs()); // 1
}
```

For me (Linux + Rust 1.19.0-nightly) this program prints 1. In debug mode I would expect this overflow to be caught and panic, similar to `u64::MAX + 2`.

### LINKED ISSUE #44216: Receiver::recv_timeout() returns instantly when duration overflows
When Receiver::recv_timeout receives certain large values, it returns immediately. This is probably due to an overflowing value. Instead, when there is overflow, it should fall back to Receiver::recv.

```rust
use std::sync::mpsc::Receiver;
use std::time::Duration;

let max = Duration::from_secs(u64::max_value());
receiver.recv_timeout(max);
```

Instant should probably not overflow like this:

```rust
let now = Instant::now();
let end_of_time = Instant::now() + Duration::from_secs(u64::max_value());
println!("{:?}", now);
println!("{:?}", end_of_time);
println!("did we pass end of time? {}", now > end_of_time);
```

### PR DESCRIPTION
**Pull request by kennytm**
Fix #44216. 
Fix #42622

The computation `Instant::now() + Duration::from_secs(u64::max_value())` now panics. The call `receiver.recv_timeout(Duration::from_secs(u64::max_value()))`, which involves such time addition, will also panic. 

The reason #44216 arises is because of an unchecked cast from `u64` to `i64`, making the duration equivalent to -1 second. 

Note that the current implementation is over-conservative, since e.g. (-2⁶²) + (2⁶³) is perfectly fine for an `i64`, yet this is rejected because (2⁶³) overflows the `i64`.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Looks great, thanks!

**Comment by kennytm** [comment]
`armhf-gnu` failed, legit.

```
[01:13:00] failures:
[01:13:00] 
[01:13:00] ---- time::tests::system_time_math stdout ----
[01:13:00] 	thread 'time::tests::system_time_math' panicked at 'overflow when subtracting duration from time', /checkout/src/libcore/option.rs:839:4
[01:13:00] 
[01:13:00] 
[01:13:00] failures:
[01:13:00]     time::tests::system_time_math
[01:13:00] 
[01:13:00] test result: FAILED. 801 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
[01:13:00] 
[01:13:00] [m[m[31m[1merror:[m test failed, to rerun pass '--lib'
```

**Comment by kennytm** [comment]
@alexcrichton Failure should be fixed in ef8c204: 

```diff
diff --git a/src/libstd/time/mod.rs b/src/libstd/time/mod.rs
index 5b893505b3..bd96f2133e 100644
--- a/src/libstd/time/mod.rs
+++ b/src/libstd/time/mod.rs
@@ -498,7 +498,7 @@ mod tests {
                 let dur = dur.duration();
                 assert!(a > b);
                 assert_almost_eq!(b + dur, a);
-                assert_almost_eq!(b - dur, a);
+                assert_almost_eq!(a - dur, b);
             }
```

If I understand correctly, the original test is wrong.

**Comment by alexcrichton** [comment]
Hm no I don't believe that's the purpose of the test (that's a different equality). I know though that the arm setup has really weird clocks and it's not quite right in qemu, so it's fine to ignore the test there.

**Comment by kennytm** [comment]
@alexcrichton if the original test is correct that means we assert `a ≈ b + dur && a ≈ b - dur`? That's only possible if `dur ≈ 0`, which won't be true especially when the `SystemClock::now` is "weird". 

Do you mean we should revert ef8c204 and just `#[cfg]` out the test outside of x86?

**Comment by alexcrichton** [comment]
Ah sorry no I think I misread and I believe you're right in that this is the intended test! Let's see if this works...

@bors: r+

**Comment by Mark-Simulacrum** [comment]
I suspect that this is the cause of the following failure in the rollup (on armhf-gnu):

@bors r-

```
[01:11:59] 	thread 'time::tests::system_time_math' panicked at 'overflow when subtracting duration from time', /checkout/src/libcore/option.rs:839:4
[01:11:59] 
[01:11:59] 
[01:11:59] failures:
[01:11:59]     time::tests::system_time_math
[01:11:59] 
[01:11:59] test result: FAILED. 807 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
```

**Comment by kennytm** [comment]
Looks like the actual problem is that `time_t` on `armhf-gnu` is 32-bit, so 80 years is too long.

**Comment by kennytm** [comment]
@alexcrichton  Actual failure cause is found. As stated before, `time_t` on `armhf-gnu` is 32-bit, thus won't support a difference more than ~68 years (2<sup>31</sup> seconds). The two tests below will always fail:

```rust
        let eighty_years = second * 60 * 60 * 24 * 365 * 80;
        assert_almost_eq!(a - eighty_years + eighty_years, a);
        assert_almost_eq!(a - (eighty_years * 10) + (eighty_years * 10), a);
```

Previously the test passed because the computation is done at `i64` and unchecked-cast to `time_t` as the final step. The `a - (800 years)` test should overflow. 

Currently I disabled these tests when `time_t` is 32-bit. But would it make more sense we store the system time as `i64` unconditionally instead of `time_t`?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks for the investigation!

We may want to investigate a platform-independent representation of `Duration` and `Instant` in the future, yeah, but that's fine to happen in a separate PR.

**Comment by kennytm** [comment]
@alexcrichton  Filed issue #44394 for platform-indepndent representation of `SystemTime`. (`Duration` is already platform-independent. `Instant` have some tricky interaction on Windows which may be difficult to port.)

**Comment by alexcrichton** [comment]
Thanks!

**Comment by kennytm** [comment]
Legit. On macOS an Instant is represented by 64-bit nanoseconds, so `u64::MAX` seconds will overflow.

**Comment by kennytm** [comment]
@alexcrichton Fixed build failure. Sorry the import statement was wrong 😓.

**Pull request merged**
