### PR TITLE
Stabilize RFC 1560

### LINKED ISSUE #13598: `use self::b` has stopped consulting local non-pub `use` of `b`
I used to be able to do:

```
use a::b;
use D = self::b::C;
```

but now I cannot, at least not in all cases.

Here is a test case:

``` rust
mod a {
    pub mod b {
        pub type C = uint;
    }
}

#[cfg(variant1)]
mod variant1 {
    use a::b;
    use D = self::b::C;

    pub fn main() {
        let d : D = 3;
        println!("d: {}", d);
    }
}

#[cfg(variant2)]
mod variant2 {
    use D = a::b::C;

    pub fn main() {
        let d : D = 3;
        println!("d: {}", d);
    }
}

#[cfg(variant1)]
pub fn main() {
    variant1::main();
}

#[cfg(variant2)]
pub fn main() {
    variant2::main();
}
```

Here is a transcript of how this used to work (on a rustc v0.11-pre circa 2014-04-07) versus breaking now (on a rustc v0.11-pre circa 2014-04018).

```
% rustc --version
/Users/fklock/opt/rust-dbg/bin/rustc 0.11-pre (0deb16a 2014-04-07 02:26:37 -0700)
host: x86_64-apple-darwin
% rustc --cfg variant1 /tmp/n.rs && ./n
d: 3
% rustc --cfg variant2 /tmp/n.rs && ./n
d: 3
% ./objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc --version
./objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc 0.11-pre (ce2bab6 2014-04-18 04:11:19 -0700)
host: x86_64-apple-darwin
% ./objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc --cfg variant1 /tmp/n.rs && ./n
/tmp/n.rs:10:9: 10:24 error: unresolved import: could not find `b` in `variant1`.
/tmp/n.rs:10     use D = self::b::C;
                     ^~~~~~~~~~~~~~~
/tmp/n.rs:10:9: 10:24 error: failed to resolve import `self::b::C`
/tmp/n.rs:10     use D = self::b::C;
                     ^~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
% ./objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc --cfg variant2 /tmp/n.rs && ./n
d: 3
% 
```

Discussion with @alexcrichton leads me to think that this change may have been injected as part of PR #13409.

It may or may be a bug.  Whether you see it as a bug may depend on your view of how privacy and `use` interact.  (In particular, if you make a variant3 of variant1 where the `use a::b` is rewritten to `pub use a::b`, so that the `b` is now publicly exported from `self`, then things seem to work.)

My reasoning is that we should be able to do:

```
use a::b; // a non-pub import
use D = self::b::C;
```

because the way we resolve `use self::b::C`, we look for other non-pub things in `self`, such as a hypothetical non-pub `mod b` defined within `self`.

### LINKED ISSUE #23157: glob imports ignore private items
This is a bug if the importing module should be able to see the private items. E.g., 

```
struct Foo;

mod sub {
    import super::*;

    type Bar = Foo; // Error: use of undeclared type name Foo
}
```

I think there is a backwards compatibility hazard here, because if there is already an item called `Foo` in `sub` then we currently get no error, but we ought to get a name clash (unless we allow shadowing in this case).

triage: I-nominated

### LINKED ISSUE #32303: Importing private reexports does not work
Testcase:

``` rust
#![crate_type = "lib"]

use std::vec::Vec as Vec;

mod foo {
    use Vec;
}
```

This should seemingly go through with no issue, but instead:

rustc output:

```
foo.rs:6:9: 6:12 error: unresolved import `Vec`. There is no `Vec` in `???`. Did you mean to use `Vec`? [E0432]
foo.rs:6     use Vec;
                 ^~~
foo.rs:6:9: 6:12 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #13598, fixes #23157, fixes #32303.
cc #35120
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @nikomatsakis

**Comment by nrc** [comment]
We don't want to land this until the end of the cycle, right?

@nikomatsakis or someone else, can you start a Crater run with this please?

**Comment by jseyfried** [comment]
> We don't want to land this until the end of the cycle, right?

Right -- I think the implementation is ready to be stabilized now but there's little harm in waiting.

**Comment by jseyfried** [comment]
Rebased.

**Comment by nikomatsakis** [comment]
Started crater run from commit d34318dd538bf4c9175e4138b3e4188ea8211620 to dab9dd47a4504b068ee336ca4b809cc19380b680. Sorry for delay.

**Comment by nikomatsakis** [comment]
Crater run results (not analyzed): https://gist.github.com/nikomatsakis/559a17914ded85b6ff475eb11d39f954

## Root regressions, sorted by rank:

* [ ] [borealis-0.1.0](https://crates.io/crates/borealis) ([before](https://tools.taskcluster.net/task-inspector/#bMHaOHBtS8-WBZwz9FSM0A)) ([after](https://tools.taskcluster.net/task-inspector/#ySSAtzF-RC2RShfD1EmIdQ))
* [ ] [openal-sys-1.16.0](https://crates.io/crates/openal-sys) ([before](https://tools.taskcluster.net/task-inspector/#63Ckzr47TFKbz134RzV3EA)) ([after](https://tools.taskcluster.net/task-inspector/#lHjy6LFmTNie2JqhvvHTcw))
* [ ] [google-groupsmigration1-1.0.0+20140416](https://crates.io/crates/google-groupsmigration1) ([before](https://tools.taskcluster.net/task-inspector/#xkXpnTdwRz-e2ehgPu4mtA)) ([after](https://tools.taskcluster.net/task-inspector/#3U7_Oh5MRoGaw3I9Zd8xZQ))
* [ ] [climatempo-0.1.0](https://crates.io/crates/climatempo) ([before](https://tools.taskcluster.net/task-inspector/#vlM-MboFS7CjupjD14A3ZA)) ([after](https://tools.taskcluster.net/task-inspector/#yVorwlo2RcyLuP1IPerkzw))
* [ ] [network-constants-0.0.1](https://crates.io/crates/network-constants) ([before](https://tools.taskcluster.net/task-inspector/#6vhCJQK4SUG9vI7QCA74sg)) ([after](https://tools.taskcluster.net/task-inspector/#SCHESlpQRwm4Krmv9wAbuw))
* [ ] [rusty-0.0.2](https://crates.io/crates/rusty) ([before](https://tools.taskcluster.net/task-inspector/#mBdQB3tNQfGwQxZlfSlBjw)) ([after](https://tools.taskcluster.net/task-inspector/#KosW4GkvQQqSL9l7bQAVtg))

**Comment by bluss** [comment]
borealis → unlucky timing and got a now-yanked version of its dep html5ever, causing the error. So it's a false positive.

**Comment by alexcrichton** [comment]
The cycle ended recently, and with no regressions on crater, is this good to go? @jseyfried want to rebase and @nrc want to r+?

**Comment by nrc** [comment]
r = me

**Pull request merged**
