### PR TITLE
revised pointer example

### PR DESCRIPTION
**Pull request by leejunseok**
Revised an example in the Pointers chapter of TRPL (the guide) as per #21575.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks!

**Comment by steveklabnik** [comment]
(In the future, if you include "Closes #21575" in your commit message, it will automaticlaly close the issue when it's merged. :smile: )

**Comment by leejunseok** [comment]
Oh cool thanks :D

**Comment by leejunseok** [comment]
Sorry, @steveklabnik , seems like I messed bors up by trying to keep my branch in sync with upstream. Can you take a look?

**Comment by Manishearth** [comment]
r=steveklabnik 8e0e87fc326ac44f7b990ebb29e3b0ae7c6a84f8 rollup

Looks good to me!

**Comment by Manishearth** [comment]
@bors: r=steveklabnik 8e0e87f rollup

oops

**Pull request merged**
