### PR TITLE
Try to reduce space usage in dist CI

### PR DESCRIPTION
**Pull request by workingjubilee**
We have had recurrent CI problems as a result of GitHub adding a new version of Xcode to its runners[^0], which has consumed ~40GB of space which served as padding. Try to reduce the number of Xcodes on our systems, because we only use Xcode 14 in actual practice. Also, try to move files instead of pointlessly copy them when we're at the end of the job.

I could not resist addressing a few shellcheck lints while I was at it.

[^0]: https://github.com/actions/runner-images/issues/10511

### CODE REVIEW

**Comment by workingjubilee** [comment]
huh.

**Comment by workingjubilee** [comment]
Neat.

@bors try

**Comment by workingjubilee** [comment]
dist-aarch64-apple has gone green!

**Comment by workingjubilee** [comment]
...fascinating.

**Comment by RalfJung** [comment]
Given that self-approved PRs are not really a thing we do outside of tool updates (to my knowledge), would be good to link to some context here. I think that context is [this](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/.60dist-aarch64-apple.60.20failed.20with.20no.20space.20left).

**Comment by Kobzol** [comment]
> ...fascinating.

The tree being closed coincided with the collector borking measurement of the previous master commit. I believe that this perf. result is an artifact of that.

**Pull request merged**
