### PR TITLE
Fill out target-spec metadata for all targets

### PR DESCRIPTION
**Pull request by harmou01**
**What does this PR try to resolve?**

This PR completes the target-spec metadata fields for all targets. This is required for a corresponding Cargo PR which adds a check for whether a target supports building the standard library when the `-Zbuild-std=std` flag is passed ([see this issue](https://github.com/rust-lang/wg-cargo-std-aware/issues/87). This functionality in Cargo is reliant on the output of `--print=target-spec-json`. 

**How should we test and review this PR?**

Check that a given target-spec metadata has been updated with:
```
$ ./x.py build library/std
$ build/host/stage1/bin/rustc --print=target-spec-json --target <target_name> -Zunstable-options
```

**Additional Information**

A few things to note:
* Where a targets 'std' or 'host tools' support is listed as '?' in the rust docs, these are left as 'None' with this PR. The corresponding changes in cargo will only reject an attempt to build std if the 'std' field is 'Some(false)'. In the case it is 'None', cargo will continue trying to build
* There's no rush for this to be merged. I understand that the format for this is not finalised yet.
* Related: #120745

### CODE REVIEW

**Comment by harmou01** [comment]
Corresponding Cargo change here: https://github.com/rust-lang/cargo/pull/14183

**Comment by harmou01** [comment]
as far as i understood, the target-spec metadata format isn't 100% final? That's the only reason for it being a draft.
It is also a dependency for the cargo change i listed, but that one may be held up for a little while and this would need to be merged first anyway.

**Review by Noratrieb — APPROVED** [review]
some of the stds seem wrong to me (as in, things that probably should support std because the OS is supported have it as false), but I think it's fine to merge this for now.
that said, I don't think this data is ready for *erroring* -Zbuild-std yet, you should take another look over it and mark all those with an OS supported by std (like Linux) as supporting std if you wanna use this information in cargo for errors. for warnings it seems fine already.
i'm still gonna merge this, because most of it is good and this is clear progress.

thank your for doing all this work!

**Pull request merged**
