### PR TITLE
Stabilize the loop_break_value feature

### PR DESCRIPTION
**Pull request by emilyalbini**
Tracking issue: #37339.

Documentation PRs already sent to the various repositories.

### CODE REVIEW

**Comment by arielb1** [comment]
I think you forgot to update the tests:
```
[00:38:10] ---- [compile-fail] compile-fail/feature-gate-loop-break-value.rs stdout ----

[00:38:10] 	

[00:38:10] error: /checkout/src/test/compile-fail/feature-gate-loop-break-value.rs:13: unexpected "error": '13:15: 13:18: mismatched types [E0308]'

[00:38:10] 

[00:38:10] error: /checkout/src/test/compile-fail/feature-gate-loop-break-value.rs:13: expected error not found: `break` with a value is experimental

[00:38:10] 

[00:38:10] error: 1 unexpected errors found, 1 expected errors not found

[00:38:10] status: exit code: 101

[00:38:10] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /checkout/src/test/compile-fail/feature-gate-loop-break-value.rs -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/feature-gate-loop-break-value.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/feature-gate-loop-break-value.stage2-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers

[00:38:10] unexpected errors (from JSON output): [

[00:38:10]     Error {

[00:38:10]         line_num: 13,

[00:38:10]         kind: Some(

[00:38:10]             Error

[00:38:10]         ),

[00:38:10]         msg: "13:15: 13:18: mismatched types [E0308]"

[00:38:10]     }

[00:38:10] ]

[00:38:10] 

[00:38:10] not found errors (from test file): [

[00:38:10]     Error {

[00:38:10]         line_num: 13,

[00:38:10]         kind: Some(

[00:38:10]             Error

[00:38:10]         ),

[00:38:10]         msg: "`break` with a value is experimental"

[00:38:10]     }

[00:38:10] ]

[00:38:10] 

[00:38:10] thread '[compile-fail] compile-fail/feature-gate-loop-break-value.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:1129

[00:38:10] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by pietroalbini** [comment]
Woops! Removed that test.

**Comment by pietroalbini** [comment]
Seems like the reviewer is taking some time off.

r? @nikomatsakis

**Comment by nikomatsakis** [comment]
@pietroalbini thanks! Sorry for the delay, I've been traveling. This looks good though.

**Comment by pietroalbini** [comment]
Ugh. Something received SIGSEGV while testing the standard library I guess. Is this a random failure?

```
[01:01:32] Testing libstd stage2 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-musl)
{snip}
[01:04:32] error: process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-musl/release/deps/std-116dfe5a1b0286e7` (signal: 11, SIGSEGV: invalid memory reference)
[01:04:32] 
[01:04:32] To learn more, run the command again with --verbose.
[01:04:32] 
[01:04:32] 
[01:04:32] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-j" "4" "--target" "x86_64-unknown-linux-musl" "--release" "--locked" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--features" "panic-unwind jemalloc backtrace" "-p" "std:0.0.0" "-p" "libc:0.0.0" "-p" "rustc_lsan:0.0.0" "-p" "collections:0.0.0" "-p" "unwind:0.0.0" "-p" "rustc_msan:0.0.0" "-p" "rustc_tsan:0.0.0" "-p" "alloc_system:0.0.0" "-p" "compiler_builtins:0.0.0" "-p" "std_unicode:0.0.0" "-p" "rustc_asan:0.0.0" "-p" "rand:0.0.0" "-p" "core:0.0.0" "-p" "panic_abort:0.0.0" "-p" "alloc:0.0.0" "--"
[01:04:32] expected success, got: exit code: 101
```

**Comment by Mark-Simulacrum** [comment]
Yeah, that's #38618.

@bors retry

**Pull request merged**
