### PR TITLE
Upgrade to LLVM 14

### PR DESCRIPTION
**Pull request by nikic**
LLVM patch state:
 * [x] https://github.com/llvm/llvm-project/commit/a55727f334b39600bfc71144b11b42aae6b94e0b Backported.
 * [x] https://github.com/rust-lang/llvm-project/commit/c3c82dc12402dd41441180c0c6cf7aed7e330c53 Backported as https://github.com/llvm/llvm-project/commit/917c47b3bf0dfc45a2a5ba12c1397d647ecf4017.
 * [x] https://github.com/rust-lang/llvm-project/commit/6e8f9ab632d12271355d10d34c9835a7ba14e4b9 No plan to upstream.
 * [x] https://github.com/llvm/llvm-project/commit/319f4b2d52e31b000db75a0a2484b5f2ab90534a Backported.
 * [x] https://github.com/rust-lang/llvm-project/commit/8b2c25d321f877161f85218479e2d1317d770e18 No plan to upstream.
 * [x] https://github.com/rust-lang/llvm-project/commit/75fef2efd427362c8f16b2d09e6ebf44069e3919 No plan to upstream.
 * [ ] https://github.com/rust-lang/llvm-project/commit/adef757547de5a570d9f6a00d3e6ac16c666ab79 Upstreamed as https://github.com/llvm/llvm-project/commit/2d2ef384b2f6e723edb793d08f52e7f4dc94ba3a. Needs backport.
 * [x] https://github.com/rust-lang/llvm-project/commit/4b7c1b4910e9fa9e04f23f06be078e168ef4c0ee No plan to upstream.
 * [x] https://github.com/rust-lang/llvm-project/commit/3f5ab0c061adb723f25b94243828b6b5407720c8 No plan to upstream.
 * [x] https://github.com/rust-lang/llvm-project/commit/514d05500e0e15e358f05f5c4cec78a805858f8e No plan to upstream.
 * [ ] https://github.com/rust-lang/llvm-project/commit/54c586958564582b3341d1838a5de86541e5fecf Under review at https://reviews.llvm.org/D119695 and https://reviews.llvm.org/D119856.

Release timeline:
 * LLVM 14.0.0 final planned for Mar 15.
 * Rust 1.60.0 planned for Apr 7.

Compile-time:
  * https://perf.rust-lang.org/compare.html?start=250384edc5d78533e993f38c60d64e42b21684b2&end=b87df8d2c7c5d9ac448c585de10927ab2ee1b864
  * A slight improvement on average, though no big changes either way.
  * There are some larger max-rss improvements.

r? @ghost

### CODE REVIEW

**Comment by nikic** [comment]
RC1 has been tagged upstream. I think this is ready for review, we'll find remaining issues on a full bors run.

r? @nagisa cc @cuviper

**Comment by nikic** [comment]
Just distcheck doing it's job...

@bors r=nagisa

**Comment by cuviper** [comment]
> #93837 updates dist-arm-linux to a newer operating system, but we have a lot of others still on Ubuntu 16.04.

FWIW, I intend to file an MCP to raise the linux-gnu baseline, and in my initial prototype this allows moving to newer crosstools-ng and Ubuntu 20.04 across the board. That will cover host targets, at least, but there are still other targets that are using 16.04's own system tools as their ABI baseline.

**Comment by nikic** [comment]
Fixed another build issue...

@bors r=nagisa

**Comment by nikic** [comment]
Had to work around a number of issues to build compiler-rt on FreeBSD 11. #89083 would presumably resolve this.

@bors r=nagisa

**Comment by nikic** [comment]
Another build fix, this time for illumos...

@bors r=nagisa

**Comment by nikic** [comment]
Well, this looks annoying. https://reviews.llvm.org/D110413 changed the ABI for `__float` functions on win64, so these should no longer be marked as `#[unadjusted_for_win64]` in compiler-builtins: https://github.com/rust-lang/compiler-builtins/blob/73326c1727790a38ae73d6677975591deac2aaca/src/float/conv.rs#L112

**Comment by bjorn3** [comment]
Cg_clif will have to adjusted too if compiler-builtins gets changed.

**Comment by bjorn3** [comment]
Tidy doesn't run for try builds.

**Comment by nikic** [comment]
Looks like this fixed u128-as-f32.rs, but i128.rs and saturating-float-casts.rs are crashing now :(

**Comment by nikic** [comment]
I suspect this is because we don't implement the right ABI for `i128` returns: https://rust.godbolt.org/z/3afTqW8WP vs https://clang.godbolt.org/z/GGPbcGabz

**Comment by bjorn3** [comment]
i128 is not FFI safe due to this differing ABI. You can use `#[win64_128bit_abi_hack]` in the `intrinsics!` macro to make i128 passed as vector of two i64 like for clang.

**Comment by nikic** [comment]
Next try with updated compiler-builtins...

@bors r=nagisa

**Comment by nikic** [comment]
Merged in the upstream release branch, the musl issue has already been fixed by https://github.com/llvm/llvm-project/commit/2a2286e9859a518a46ead8e3ef5e283662766370 in the meantime.

@bors r=nagisa

**Comment by pnkfelix** [comment]
> 

Just to clarify, is the above a reference to issue #54341 ? Or are you referring to a different problem, @bjorn3 ?

**Comment by nagisa** [comment]
My understanding is that the two are broadly unrelated. The ABI used by compiler builtins tends to be pretty bespoke regardless of other issues. It was not all that uncommon a little while ago to see builtins that don't really follow any documented calling convention. That's the reason we have e.g. `unadjusted` calling convention in Rust.

The #54341 is entirely about the alignment mismatch.

**Comment by nikic** [comment]
@bors retry LLVM rebuild timeout

It looks like bors failed to kill the build here and it actually succeeded afterwards, and now bors is just stuck...

**Comment by briansmith** [comment]
> LLVM 14.0.0 final planned for Mar 15.
> Rust 1.60.0 planned for Apr 7.

If there isn't an urgent reason to upgrade to LLVM 14 then maybe it is worth waiting for the release? IMO three weeks between when LLVM 14 final is *expected* to ship is not enough window. There's a good chance that the LLVM 14 release won't be fully rolled out or people will otherwise have trouble upgrading to LLVM 14.

When Rust upgrades to an as-yet-unreleased LLVM version, this breaks some (many?) people's CI/CD code coverage measurement, as often the LLVM tools version has to match Rust's LLVM version exactly in order for the coverage data to be accurate. It is pretty difficult to acquire a pre-release version of LLVM tools on certain platforms. Not sure if this aspect was overlooked or if it is expected breakage.

**Comment by nikic** [comment]
@briansmith I took a look at your CI config, and it looks like switching https://github.com/rustls/rustls/blob/5bda754ac18f37eb39132f89fb5522494b6202eb/.github/workflows/build.yml#L185 to llvm-toolchain-bionic-14 should work fine? This is available for pre-releases as well.

We always update LLVM for nightly well in advance of the release to make sure that any issues we discover can actually make it into the release. Our timing is chosen such that a stable LLVM release is available by the time the update makes it into a stable Rust release.

In this particular instance, we may want to revert the upgrade from the beta branch once promotion happens, because it landed very close to promotion this time, and we may want to give it more time to bake in nightly.

By the way, I believe `-C instrument-coverage` was recently stabilized, so you should be able to use a stable toolchain (with a stable LLVM release) for coverage in the future.

**Comment by rylev** [comment]
Upgrading LLVM is always likely to produce performance changes. Luckily the perf improvements seem to outweigh the perf regressions considerably both in number and magnitude.

@rustbot label: +perf-regression-triaged

**Pull request merged**
