### PR TITLE
Update cargo/rls submodules and dependencies

### PR DESCRIPTION
**Pull request by alexcrichton**
Brings in a few regression fixes on the Cargo side, updates the rls to work
with the newer Cargo, and also updates other crates.io dependencies to pull in
various bug fixes and such.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This is a reopening of https://github.com/rust-lang/rust/pull/42668 but with more updates


r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Looks good to me.

@bors r+

**Comment by Mark-Simulacrum** [comment]
```
[01:06:58] error[E0432]: unresolved import `cargo::core::MultiShell`
[01:06:58]   --> src\tools\rls\src\build.rs:19:30
[01:06:58]    |
[01:06:58] 19 | use cargo::core::{PackageId, MultiShell, Workspace};
[01:06:58]    |                              ^^^^^^^^^^ no `MultiShell` in `core`
[01:06:58]
[01:06:59] error: aborting due to previous error(s)
```

**Pull request merged**
