### PR TITLE
Ignore invalid-punct proc macro tests for stage 1

### PR DESCRIPTION
**Pull request by spastorino**
r? @oli-obk

### CODE REVIEW

**Comment by petrochenkov** [comment]
What's the problem with them?

**Comment by spastorino** [comment]
@petrochenkov tests fail on stage 1. See https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/3.20ui.20tests.20fail.20for.20me.20locally

**Comment by petrochenkov** [comment]
This seems system-specific, the tests don't fail for me.

**Comment by petrochenkov** [comment]
Do they fail with `RUST_BACKTRACE` disabled?

**Comment by spastorino** [comment]
@petrochenkov you're right, they fail only with RUST_BACKTRACE enabled.

**Pull request closed without merging**
