### PR TITLE
Represent Option<bool> and Option<char> as 8bit and 32bit values

### LINKED ISSUE #5977: Option<char> should be represented as just one 32 bit value
A `char` is a `u32`, but Unicode is standardized to only take up 21bit, so there is more than enough space for that optimization.

Might be useful for specifying code page conversion tables with holes in them.

### PR DESCRIPTION
**Pull request by mrhota**
Closes #5977.

This is a rebase and re-issue of @Yoric's work from #31215.

CC @pnkfelix @luqmana -- anyone else?

### CODE REVIEW

**Comment by Aatch** [comment]
It looks ok to me, but I'd like some other @rust-lang/compiler people to look at it as well.

One possible concern is that we're currently trying to get rid of this code in favour of using the layout code in librustc.

**Comment by eddyb** [comment]
This is a problematic time to actually make changes to layout code, you'd at least want to wait for #36151, but I'll take a look.

**Comment by eddyb** [comment]
Ah, seems that you only changed `trans::adt` which will most definitely result in ICEs because it won't match `ty::layout`.
Also, this introduces new special-cases instead of generalizing old ones (the zero/nullptr optimization).
I can mentor a more robust implementation after #36151, if either @mrhota, @camlorn or someone else wants to work on it.

**Comment by luqmana** [comment]
Yea, aside from the missing `ty::layout` changes it looks good to me. But i'll defer to @Aatch and @eddyb and yea, it'd probably be best to at least wait for #36151 first.

**Comment by eddyb** [comment]
My thoughts from IRC:
> a proper niche optimization keeps track of the first niche with values to spare and goes looking for a second one after that one is full
> right now we do that with a boolean for nullable but we could always track an u64 range, until the range is full
>
> anything less will likely to have too much added complexity for the added benefits and will impact maintenance negatively
>
> thinking about it more, a further strength reduction would be using field offsets instead of paths
> this would even work with niches shared by multiple variants, even if they're different types

**Comment by camlorn** [comment]
I'll probably take a look at this if no one beats me to it, but I consider struct layout optimization to be more important and intend to try to do that first.

**Comment by arthurprs** [comment]
This is pretty cool. Good work!

**Comment by camlorn** [comment]
Just read this. It's interesting, and kind of goes in line with some other stuff I was bringing up on IRC.

It should be pretty easy to port this to layout.  If we're going to though, I think we should go all out and handle the case of `n` zero-sized variants and 1 variant with a forbidden field, as opposed to just one-and-one.  Unlike null pointer, we can do that here without much effort.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Pull request closed without merging**
