### PR TITLE
libcore: Inline `mem::forget()`.

### PR DESCRIPTION
**Pull request by pcwalton**
Was causing severe performance problems in WebRender.

r? @brson

### CODE REVIEW

**Comment by Aatch** [comment]
Given that `mem::forget` is generic, I'm surprised that it wasn't already inlined. We're not reusing monomorphisations from other crates yet, are we?

**Comment by dotdash** [comment]
It should be, the only exception I know of would be when using codegen units, in that case only one codegen unit will actually monomorphize a given instance of a generic function. This is a somewhat recent change made in #32469

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
I think that if something is tagged as `#[inline]`, as opposed to being merely generic, then it is made universally available, no?

**Comment by dotdash** [comment]
@nikomatsakis right. The change only affected generic functions that are not tagged `#[inline]`

**Pull request merged**
