### PR TITLE
Improvements to the #[should_panic] feature

### PR DESCRIPTION
**Pull request by keeperofdakeys**
Add more error checking for the `#[should_panic]` attribute, and print the expected panic string when it does not match.

Fixes https://github.com/rust-lang/rust/issues/29000

Eg:
```running 3 tests
test test2 ... ok
test test1 ... FAILED
: Panic did not include expected string 'foo'
test test3 ... FAILED

failures:

---- test1 stdout ----
	thread 'test1' panicked at 'bar', test.rs:7
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- test3 stdout ----
	thread 'test3' panicked at 'bar', test.rs:18

```

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I restarted the test which failed (for some reasons...).

**Comment by est31** [comment]
You should also add tests to check

* when the panic message doesn't match, the test fails
* when the panic message matches, the test succeeds

**Comment by keeperofdakeys** [comment]
> You should also add tests to check
> 
>     when the panic message doesn't match, the test fails
>     when the panic message matches, the test succeeds
> 

Aren't the tests that are already present covering this?
https://github.com/rust-lang/rust/blob/master/src/libtest/lib.rs#L1526-L1597

**Comment by est31** [comment]
@keeperofdakeys yes, but this only tests part of the code. The parts that you added aren't tested (extracting the string from the expected attribute). It would be nicer to test all of it.

**Comment by keeperofdakeys** [comment]
I've updated the `test_should_panic_bad_message` test so that it also checks the failed message.

**Comment by nrc** [comment]
Hmm, I suppose this is a back-compat breaking change because people who used the bad forms previously will get an error when there was none previously. Annoyingly, Crater will not pick up such errors. I think therefore that this needs to be a warning, rather than an error for one cycle.

**Comment by nrc** [comment]
LGTM, otherwise

**Comment by keeperofdakeys** [comment]
Since it seems you can't insert lints in libsyntax, I've changed the errors into warnings, and added notes about future changes.

**Comment by est31** [comment]
@keeperofdakeys that's still not fullfilling the complete potential of the test, It still doesn't test whether the thing you specify in `expected` is actually the string that's being used for the panic message, and not something else.

**Comment by keeperofdakeys** [comment]
@est31 I don't understand the exact point you're trying to make, could you elaborate?

**Comment by brson** [comment]
This looks good, except that I'm not sure about the new output:

```
test test1 ... FAILED
: Panic did not include expected string 'foo'
```

I don't think there's any other such inline output about what happened in the test for any other sort of test, and I'm reluctant to start the precedent here. Usually this type of information is printed to stderr, captured by the test runner, and printed as part of the final summary list of failures, and I'd prefer if this information could be presented similarly.

**Comment by est31** [comment]
@keeperofdakeys the unit tests you linked to use internal testing functions, and don't use the `#[should_panic]` attribute. If there is a bug in parsing of that attribute (the code you add in this PR), they won't detect it.

**Comment by keeperofdakeys** [comment]
I've updated the output to:
```
running 3 tests
test test2 ... FAILED
test test1 ... FAILED
test test3 ... FAILED

failures:

---- test2 stdout ----
	thread 'test2' panicked at 'bar', ./test.rs:12
Panic did not include expected string 'foo'
---- test1 stdout ----
	thread 'test1' panicked at 'explicit panic', ./test.rs:6
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Panic did not include expected string 'foo'
---- test3 stdout ----
	thread 'test3' panicked at 'explicit panic', ./test.rs:18
Panic did not include expected string 'foo'

failures:
    test1
    test2
    test3
```

@est31 Ah, thanks for clarifying. Since writing a unit test for `fn should_panic` in `libsyntax/test.rs` seems non-trivial, I'm thinking that a test in `src/test/run-fail` with a panic! that doesn't match the expected value would be the best.

**Comment by keeperofdakeys** [comment]
Whoops, looks like I accidentally made a heisentest. I've split it out into two files now.

**Comment by keeperofdakeys** [comment]
Strange, travis-ci failed before compilation.

**Pull request merged**
