### PR TITLE
Clean up unstable book

### PR DESCRIPTION
**Pull request by JohnTitor**
- #58402's feature was renamed to `tidy_test_never_used_anywhere_else` and it is now used for tidy only
- `read_initializer` link is wrong and the doc should be auto-generated so removed
- Add dummy doc for `link_cfg`
- Stop generating `compiler_builtins_lib` doc in favor of b8ccc0f8a60ac16fdc00f4b2e36e1a5db8b78295
- Make `rustc_attrs` tracking issue "None"

### CODE REVIEW

**Comment by JohnTitor** [comment]
@Dylan-DPC Would you mind my addressing the remaining things above in this PR? (Sorry, I should have marked this PR as WIP.)

**Comment by Dylan-DPC** [comment]
You can also do draft prs which are more noticeable

**Comment by JohnTitor** [comment]
Okay, the work is almost done.

@Centril `rustc_attrs` tracking issue still points to #29642. Could we create new one?

**Comment by Centril** [comment]
@JohnTitor `rustc_attrs` shouldn't have a tracking issue, it's only for internal use.

**Comment by JohnTitor** [comment]
Ah, okay! Then tracking issue can be None?

**Comment by Centril** [comment]
Yes.

**Comment by JohnTitor** [comment]
I think it's ready to review.

**Comment by JohnTitor** [comment]
I think almost should be fine but I'm not sure about tidy things, perhaps @Mark-Simulacrum thoughts?

**Pull request merged**
