### PR TITLE
Try to evalate obligation in fulfillment when we have no inference vars

### PR DESCRIPTION
**Pull request by Aaron1011**
Previously, we required that the predicate be 'global', which also
ruled out type parameters. As long as we don't have any inference
variables (meaning that that the fulfillment will never need to
constrain any inferene variables), we can use the `evaluate_obligation`
query.

### CODE REVIEW

**Comment by jackh726** [comment]
@Aaron1011 was this an alternative to #85868?

**Comment by Aaron1011** [comment]
This was an attempt at speeding up that PR - by itself, this PR doesn't fix any bugs. However, it appears that this approach actually hurts performance.

**Pull request closed without merging**
