### PR TITLE
Rollup of 21 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #33129, #33256, #33283, #33313, #33314, #33326, #33336, #33382, #33386, #33402, #33409, #33410, #33412, #33428, #33430, #33437, #33438, #33439, #33442, #33456, #33459
- Failed merges:

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fix in progress, don't merge for now.

**Comment by steveklabnik** [comment]
@bors: delegate=guillaumegomez

Just waiting on travis for this, and then it should be good. I might not be around, so delegating :smile:

**Comment by steveklabnik** [comment]
@GuillaumeGomez these failures look possibly legitimate to me; are we sure that broken links weren't introduced?

**Comment by GuillaumeGomez** [comment]
I'm cheking it right now.

**Pull request closed without merging**
