### PR TITLE
Fix #23808: dead_code lint: visit types in paths

### LINKED ISSUE #23808: Spurious `dead_code` warning when type is only used in path
foo.rs:
```rust
trait Bar {
    fn bar() {}
}

enum Foo {}

impl Bar for Foo {}

fn main() {
    Foo::bar();
}
```
Warning:
```
> rustc --version
rustc 1.0.0-nightly (199bdcfef 2015-03-26) (built 2015-03-27)
> rustc foo.rs 
foo.rs:5:1: 5:12 warning: enum is never used: `Foo`, #[warn(dead_code)] on by default
foo.rs:5 enum Foo {}
         ^~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by TimNN**
Fixes #23808, passes `make check-stage1` `run-pass` and `run-fail` locally.

### CODE REVIEW

**Comment by TimNN** [comment]
So, I had a look at the travis logs and it looks like the pretty test failed because pretty forces a `crate_type="lib"`, thus the main function is not called and the `#![deny(dead_code)]` triggers. 

What would be the best solution to fix this? Disable the test for pretty? How do I do that?

**Comment by TimNN** [comment]
Ok, so I think I fixed the issue by making `main` `pub`, `make check-stage1-pretty NO_REBUILD=1 TESTNAME=issue-23808` now also passes locally.

**Comment by nrc** [comment]
It would be nice if we didn't need `pub main` - that was a requirement for a while that was lifted and life has been much easier. Do you know why pretty makes the crate type lib?

**Comment by TimNN** [comment]
I have no clue, this is the first time I have worked on the rust compiler. The only other alternative I can think of is to disable pretty for this test. Or is it possible to use `#![crate_type="bin"]` to overwrite a `--crate-type=bin`?

**Comment by TimNN** [comment]
Alright, I removed the pub again, this now has to wait for #27567

**Comment by TimNN** [comment]
Alright, now that #27571 is merged this should build. I just rebased & pushed again to get travis to test it again.

**Comment by TimNN** [comment]
Alright, this doesn't compile at the moment due to some recent rust changes, I'll fix this now.

**Comment by TimNN** [comment]
Please don't r+ yet, I need to add another test case which came up on reddit:
https://www.reddit.com/r/rust/comments/3gmtpq/why_do_i_get_a_struct_never_used_here/

**Comment by TimNN** [comment]
Alright, I added the new test cases. They would probably not have been necessary, but I wanted to be on the safe side.

**Comment by TimNN** [comment]
@nrc: could you review again?

**Comment by nrc** [comment]
@bors: r+

@TimNN looks good, thanks for seeing through the changes

**Comment by TimNN** [comment]
@nrc could you retry? this passes make check locally (on linux) and I don't think there is any target dependent code in that part of the compiler.

**Comment by alexcrichton** [comment]
That doesn't look like it's spurious (may be #27583), but I don't think a retry will fix it. Can you reproduce locally? Perhaps on a 32-bit build?

**Comment by TimNN** [comment]
@alexcrichton I'm trying a local 32bit build now but I can't imagine how my changed could cause a test failure there, except if they just expose another bug.

If this turns out to be #27583, how would I go about fixing this? Just wait until the issue is fixed or add one of the workarounds from the issue to `ExprUseVisitor::new()`?

**Comment by alexcrichton** [comment]
Unfortunately I'm not sure if there's a fix, but #27856 is also block on this and @nikomatsakis [indicates](https://github.com/rust-lang/rust/pull/27856#issuecomment-132381037) that #27892 may fix it.

**Comment by TimNN** [comment]
Thanks for the additional links! I'll see if the local build will result in anything and wait for #27892 otherwise. I never imagined that this rather small pull request would cause so much trouble, even if it did take some (rather enjoyable) hours to figuring this fix out.

**Comment by TimNN** [comment]
Alright, so the local 32bit linux build failed as well, so I'll wait on #27892 and then try again

**Comment by TimNN** [comment]
Since #27892 has landed now, could someone retry please?

**Pull request merged**
