### PR TITLE
Rename all remaining compiler crates to use the `rustc_foo` pattern

### LINKED ISSUE #71177: libfmt_macros should be renamed to have a rustc_ prefix or moved into librustc_builtin_macros.
For historical reasons we have a crate that looks like it would be part of the standard library, but it's really just a parser for the implementation of `format_args!`.

cc @petrochenkov

### PR DESCRIPTION
**Pull request by petrochenkov**
libarena -> librustc_arena
libfmt_macros -> librustc_parse_format
libgraphviz -> librustc_graphviz
libserialize -> librustc_serialize

Closes https://github.com/rust-lang/rust/issues/71177 in particular.

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @rust-lang/compiler

**Comment by Mark-Simulacrum** [comment]
My guess is that this will break some of the autopublishing scripts for e.g. libarena but IMO that's fine, they don't need to always work. cc @alexcrichton though (we should probably also move those into infra's hands at some point).

I sort of half want to say we should MCP this but I'm feeling like we've historically agreed on this somewhere already, and the crates being moved here seem like they're pretty unambiguous anyway.

r=me

**Comment by bjorn3** [comment]
> libserialize -> librustc_serialize

This makes it easier to confuse it with the `rustc-serialize` crate on crates.io.

**Comment by Mark-Simulacrum** [comment]
We no longer ship the compiled rustc artifacts to most users, so I don't expect it to be a major point of confusion.

**Comment by petrochenkov** [comment]
No logs?
Looks like the "Run build" stage haven't even started.
Looks spurious.
@bors retry

**Pull request merged**
