### PR TITLE
[experiment] Get rid of `pending_obligations`

### PR DESCRIPTION
**Pull request by compiler-errors**
Currently has some issues:
- [ ] Autoderef still needs to do some fulfillment, to make sure that the autoderef chain doesn't stall on an inference variable
    - We may be able to move the fulfillment in `method_autoderef_steps` or somewhere else where this particularly matters...
- [ ] The `explicit_item_bounds` of an RPITIT need to be normalized before being registered
    - Probably all bounds could be normalized here, there are likely ways of making this break in RPIT too... 

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by jyn514** [comment]
@compiler-errors this has been open a while - are you still planning to follow up on it?

**Comment by compiler-errors** [comment]
Yeah

**Comment by Dylan-DPC** [comment]
Closing this as it has been inactive

**Pull request closed without merging**
