### PR TITLE
[Gate Tests] - marking feature tests

### PR DESCRIPTION
**Pull request by cseale**
Removal of the lang feature gate tests whitelist #39059

r? @est31

### CODE REVIEW

**Comment by est31** [comment]
@cseale you should remove those tests from the whitelist: https://github.com/rust-lang/rust/blob/6fe23719feb20c25a8b2693d1f196e72d8da9af5/src/tools/tidy/src/features.rs#L168-L175

**Comment by cseale** [comment]
@est31 done

**Review by est31 — APPROVED** [review]

**Comment by est31** [comment]
Its merged. Thanks @cseale !

**Pull request merged**
