### PR TITLE
[EXPERIMENT] Don't monomorphize things that are unused due to `if <T as Trait>::CONST`

### LINKED ISSUE #85836: dead-code optimize `if const { expr }` even in opt-level=0
`inline_const` tracking issue: https://github.com/rust-lang/rust/issues/76001

Inspired by @oli-obk's comment in https://github.com/rust-lang/rust/pull/85828#discussion_r642046617

For things like `if const { expr } { 0 } else { do something complex }` it'd be nice to not have to even give LLVM the code for the else branch to have to emit.  Ought to save time and binary size.

Tentatively marked mir-opt, since we presumably still need to make the MIR for it, in order to borrow-check and such the unreachable code.  But might need to be codegen-time instead to pick up on monomorphized inline constants.

Hopefully should be doable relatively easily when the const is an inline const, since that forces const folding already, and thus there should just be a `const true` in the MIR.

### PR DESCRIPTION
**Pull request by scottmcm**
Fixes #85836

MIR optimizations have long meant that we do this for concrete constants, but with this change it also applies for things like `<T as TrustedRandomAccess>::MAY_HAVE_SIDE_EFFECT`.

There's likely not enough of this stuff for the extra work to be worth it, but I'm curious to see anyway.

r? @ghost

### CODE REVIEW

**Comment by scottmcm** [comment]
Queue's empty, so...

@bors try @rust-timer queue

**Comment by the8472** [comment]
`MAY_HAVE_SIDE_EFFECT` doesn't seem like a particularly juicy target since it's mostly used in `Zip`.

The following could be a juicier one if it were extracted to an associated const if that works together with specialization

https://github.com/rust-lang/rust/blob/862962b90e59c5c1e217df74de80d3a81eee42f4/library/alloc/src/vec/source_iter_marker.rs#L24-L28

**Comment by scottmcm** [comment]
Hmm, interesting that the `try` failed.  I built a full stage2 locally without issue.  Oh well, TBH I *was* surprised that just referencing these things "worked", so I'll take a look at removing the references to them too.  Emitting less LLVM is always good.

-- 

@the8472 If you're excited to I'd happily take it in the branch, but this is still experimental enough that I can't honestly say that you *should*.  It's still perfectly likely that this will go nowhere, so I wouldn't want you to waste time.

Honestly this PR might not be worth it until inline consts work so that could just be
```rust
        if const {
            mem::size_of::<T>() == 0
                || mem::size_of::<T>()
                    != mem::size_of::<<<I as SourceIter>::Source as AsIntoIter>::Item>()
                || mem::align_of::<T>()
                    != mem::align_of::<<<I as SourceIter>::Source as AsIntoIter>::Item>()
        } {
            // fallback to more generic implementations
            return SpecFromIterNested::from_iter(iterator);
        }
```
instead, and not need a whole bunch of these little one-use traits.

But right now they're using the basic "sugar for `const` item" implementation strategy which doesn't allow generic parameters to be referenced, making them unhelpful here.

(The context for this PR was seeing if I could get https://github.com/rust-lang/rust/issues/85836 working.)

**Comment by the8472** [comment]
associated const PR over at https://github.com/scottmcm/rust/pull/3

**Pull request closed without merging**
