### PR TITLE
Move tests

### PR DESCRIPTION
**Pull request by c410-f3r**
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
issue-32709.rs -> try_trait (span is a meaningless subdirectory)
issue-3707.rs -> methods, I guess
issue-34721.rs -> moves (suggestions is a meaningless subdirectory)
issue-69225-SCEVAddExpr-wrap-flag.rs -> loops
issue-69225-layout-repeated-checked-add.rs -> loops
@rustbot author

**Comment by c410-f3r** [comment]
Done

**Comment by petrochenkov** [comment]
r=me after rebase.

**Comment by c410-f3r** [comment]
Done

**Pull request merged**
