### PR TITLE
Update LLVM to 19 327ca6c

### LINKED ISSUE #129887: SIGTRAP during compilation on MacOS
Unfortunately I don't have a *minimal* reproducible example, just a reproducible example. On MacOS Ventura 13.5 on an Apple M2 processor, the following steps reproduce it:

```bash
git clone https://github.com/pola-rs/polars --depth 1
cd polars
make build-opt
```

Said steps cause `rustc` to exit with a SIGTRAP signal, unfortunately all the way at the end of compilation.

### Meta

The above SIGTRAP is a *regression*, it occurs with `channel = "nightly-2024-09-02"` in `rust-toolchain.toml`, as well as with `nightly-2024-08-26`, but not with `nightly-2024-07-26`. I have not bisected it further.

The error does not occur when using `make build` instead of `make build-opt`. The difference between these two is the profile selected, `make build` uses the debug profile whereas `built-opt` uses the following profile:

```toml
[profile.debug-release]
inherits = "release"
debug = true
incremental = true
codegen-units = 16
lto = "thin"
```

### Error output

```rust
error: could not compile `py-polars` (lib)

Caused by:
  process didn't exit successfully: `/Users/orlp/.rustup/toolchains/nightly-2024-09-02-aarch64-apple-darwin/bin/rustc --crate-name polars --edition=2021 py-polars/src/lib.rs --error-format=json --json=diagnostic-re
ndered-ansi,artifacts,future-incompat --diagnostic-width=214 --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C lto=thin -C codegen-units=16 -C debuginfo=2 -C split-debuginfo=unpacked -C link-arg=-undefined
 -C link-arg=dynamic_lookup -C 'link-args=-Wl,-install_name,@rpath/polars.abi3.so' --cfg 'feature="all"' --cfg 'feature="build_info"' --cfg 'feature="clipboard"' --cfg 'feature="csv"' --cfg 'feature="default"' --cf
g 'feature="ffi_plugin"' --cfg 'feature="ipc"' --cfg 'feature="nightly"' --cfg 'feature="object"' --cfg 'feature="parquet"' --cfg 'feature="polars_cloud"' --cfg 'feature="sql"' --cfg 'feature="trigonometry"' --chec
k-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("all", "array_any_all", "array_count", "asof_join", "avro", "binary_encoding", "build_info", "clipboard", "cloud", "cross_join", "cse", "csv", "cutqcut", "decomp
ress", "default", "dtype-array", "dtype-i16", "dtype-i8", "dtype-u16", "dtype-u8", "dtypes", "extract_groups", "extract_jsonpath", "ffi_plugin", "find_many", "hist", "io", "ipc", "ipc_streaming", "is_in", "json", "
list_any_all", "list_count", "list_drop_nulls", "list_gather", "list_sample", "list_sets", "merge_sorted", "meta", "new_streaming", "nightly", "object", "operations", "optimizations", "parquet", "pct_change", "peak
s", "performant", "pivot", "polars_cloud", "propagate_nans", "regex", "repeat_by", "rle", "search_sorted", "sign", "sql", "streaming", "timezones", "top_k", "trigonometry"))' -C metadata=ea4eeeedc424a3d4 --out-dir
/Users/orlp/programming/rust/polars/target/debug-release/deps -C incremental=/Users/orlp/programming/rust/polars/target/debug-release/incremental -L dependency=/Users/orlp/programming/rust/polars/target/debug-relea
se/deps --extern jemallocator=/Users/orlp/programming/rust/polars/target/debug-release/deps/libjemallocator-ddd1e6f334ef7c27.rlib --extern libc=/Users/orlp/programming/rust/polars/target/debug-release/deps/liblibc-
42e938498c975329.rlib --extern polars_python=/Users/orlp/programming/rust/polars/target/debug-release/deps/libpolars_python-99e3509ba3962109.rlib --extern pyo3=/Users/orlp/programming/rust/polars/target/debug-relea
se/deps/libpyo3-8bd11066bcba163b.rlib -L native=/Users/orlp/programming/rust/polars/target/debug-release/build/jemalloc-sys-b8e69d721500db60/out/build/lib -L native=/Users/orlp/programming/rust/polars/target/debug-
release/build/lz4-sys-e43c007a0372d905/out -L native=/Users/orlp/programming/rust/polars/target/debug-release/build/ring-ff56c916aa4069c8/out -L native=/Users/orlp/programming/rust/polars/target/debug-release/build
/psm-6c1c5b5e6ef90509/out -L native=/Users/orlp/programming/rust/polars/target/debug-release/build/zstd-sys-a95d2f6c0a1c8f6d/out -L native=/Users/orlp/programming/rust/polars/target/debug-release/build/blake3-44100
89b8e8e51f2/out -L native=/Users/orlp/programming/rust/polars/target/debug-release/build/libz-ng-sys-220b3fe3c720fe48/out/lib -L native=/Users/orlp/programming/rust/polars/target/debug-release/build/libz-ng-sys-220
b3fe3c720fe48/out/lib64 --check-cfg 'cfg(allocator, values("default", "mimalloc"))'` (signal: 5, SIGTRAP: trace/breakpoint trap)
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/Users/orlp/programming/rust/polars/.venv/bin/python" PYTHON_SYS_EXECUTABLE="/Us
ers/orlp/programming/rust/polars/.venv/bin/python" "cargo" "rustc" "--profile" "debug-release" "--message-format" "json-render-diagnostics" "--manifest-path" "/Users/orlp/programming/rust/polars/py-polars/Cargo.tom
l" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/polars.abi3.so"`
make: *** [build-opt] Error 1
```

I've tagged this issue as an 'internal compiler error', even though it does not panic but actually SIGTRAPs. I thus don't have a Rust backtrace, but I did attach `lldb` to `rustc` before the sigtrap occurred and got the following backtrace:

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Process 62117 stopped
* thread #23, name = 'lto polars_parquet-a4434a04818ab16d.el3w6d8nkur84ww5qq4oo2yuv.r', stop reason = EXC_BREAKPOINT (code=1, subcode=0x10f889e50)
    frame #0: 0x000000010f889e50 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::DataLayout::getTypeSizeInBits(llvm::Type*) const
librustc_driver-5d5f1ff7b417ce42.dylib`llvm::DataLayout::getTypeSizeInBits:
->  0x10f889e50 <+460>: brk    #0x1

librustc_driver-5d5f1ff7b417ce42.dylib`std::__1::vector<llvm::Value*, std::__1::allocator<llvm::Value*>>::insert<llvm::Use*>:
    0x10f889e54 <+0>:   stp    x28, x27, [sp, #-0x60]!
    0x10f889e58 <+4>:   stp    x26, x25, [sp, #0x10]
    0x10f889e5c <+8>:   stp    x24, x23, [sp, #0x20]
Target 0: (rustc) stopped.
(lldb) bt
* thread #23, name = 'lto polars_parquet-a4434a04818ab16d.el3w6d8nkur84ww5qq4oo2yuv.r', stop reason = EXC_BREAKPOINT (code=1, subcode=0x10f889e50)
  * frame #0: 0x000000010f889e50 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::DataLayout::getTypeSizeInBits(llvm::Type*) const
    frame #1: 0x000000010e7ae570 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes()
    frame #2: 0x000000010e7b2a84 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::SLPVectorizerPass::vectorizeStoreChain(llvm::ArrayRef<llvm::Value*>, llvm::slpvectorizer::BoUpSLP&, unsigned int, unsigned int, unsigned int&)
    frame #3: 0x000000010e7b44b8 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::SLPVectorizerPass::vectorizeStores(llvm::ArrayRef<llvm::StoreInst*>, llvm::slpvectorizer::BoUpSLP&, llvm::DenseSet<std::__1::tuple<llvm::Value*, llvm::Value*, llvm::Value*, llvm::Value*, unsigned int>, llvm::DenseMapInfo<std::__1::tuple<llvm::Value*, llvm::Value*, llvm::Value*, llvm::Value*, unsigned int>, void>>&)::$_156::operator()(std::__1::set<std::__1::pair<unsigned int, int>, llvm::SLPVectorizerPass::vectorizeStores(llvm::ArrayRef<llvm::StoreInst*>, llvm::slpvectorizer::BoUpSLP&, llvm::DenseSet<std::__1::tuple<llvm::Value*, llvm::Value*, llvm::Value*, llvm::Value*, unsigned int>, llvm::DenseMapInfo<std::__1::tuple<llvm::Value*, llvm::Value*, llvm::Value*, llvm::Value*, unsigned int>, void>>&)::StoreDistCompare, std::__1::allocator<std::__1::pair<unsigned int, int>>> const&) const
    frame #4: 0x000000010e7b3b30 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::SLPVectorizerPass::vectorizeStores(llvm::ArrayRef<llvm::StoreInst*>, llvm::slpvectorizer::BoUpSLP&, llvm::DenseSet<std::__1::tuple<llvm::Value*, llvm::Value*, llvm::Value*, llvm::Value*, unsigned int>, llvm::DenseMapInfo<std::__1::tuple<llvm::Value*, llvm::Value*, llvm::Value*, llvm::Value*, unsigned int>, void>>&)
    frame #5: 0x000000010e7b05d0 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::SLPVectorizerPass::vectorizeStoreChains(llvm::slpvectorizer::BoUpSLP&)
    frame #6: 0x000000010e7afbac librustc_driver-5d5f1ff7b417ce42.dylib`llvm::SLPVectorizerPass::runImpl(llvm::Function&, llvm::ScalarEvolution*, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo*, llvm::AAResults*, llvm::LoopInfo*, llvm::DominatorTree*, llvm::AssumptionCache*, llvm::DemandedBits*, llvm::OptimizationRemarkEmitter*)
    frame #7: 0x000000010e7af614 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::SLPVectorizerPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)
    frame #8: 0x000000010f960f48 librustc_driver-5d5f1ff7b417ce42.dylib`llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)
    frame #9: 0x000000010f963a2c librustc_driver-5d5f1ff7b417ce42.dylib`llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&)
    frame #10: 0x000000010f96033c librustc_driver-5d5f1ff7b417ce42.dylib`llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&)
    frame #11: 0x000000010d5ae318 librustc_driver-5d5f1ff7b417ce42.dylib`LLVMRustOptimize
    frame #12: 0x000000010b1d20b4 librustc_driver-5d5f1ff7b417ce42.dylib`rustc_codegen_llvm::back::write::llvm_optimize
    frame #13: 0x000000010b203d04 librustc_driver-5d5f1ff7b417ce42.dylib`rustc_codegen_llvm::back::lto::run_pass_manager
    frame #14: 0x000000010b204af8 librustc_driver-5d5f1ff7b417ce42.dylib`rustc_codegen_llvm::back::lto::optimize_thin_module
    frame #15: 0x000000010b1c5ca4 librustc_driver-5d5f1ff7b417ce42.dylib`std::sys::backtrace::__rust_begin_short_backtrace::<<rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa::back::write::spawn_work<rustc_codegen_llvm::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>
    frame #16: 0x000000010b1c9f7c librustc_driver-5d5f1ff7b417ce42.dylib`<<std::thread::Builder>::spawn_unchecked_<<rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa::back::write::spawn_work<rustc_codegen_llvm::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
    frame #17: 0x000000010d4e5404 librustc_driver-5d5f1ff7b417ce42.dylib`std::sys::pal::unix::thread::Thread::new::thread_start::h4746909631f3e791
    frame #18: 0x000000018b05bfa8 libsystem_pthread.dylib`_pthread_start
```

</p>
</details>

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #129887.

r? nikic

### CODE REVIEW

**Comment by nikic** [comment]
beta is currently based on a pre-release version of LLVM 19. This updates to a newer (still pre-release) version, which fixes at least one P-high regression from the LLVM 19 upgrade.

**Comment by DianQK** [comment]
The changes related to us were generated by `git --no-pager log --pretty=format:"%s [%h](https://github.com/llvm/llvm-project/commit/%h)" 2b259b3c201f939f2ed8d2fb0a0e9b37dd2d1321...4b8d29c585687084bbcf21471e04f279d1eddc0a --stat  -- llvm/lib | sed -e 's/ (#[0-9]*)//g' -e 's/^[[:space:]]*//;s/[[:space:]]*$//'`.
Please note that this is only to help us quickly understand what changes in this PR.

<details><summary>Click me</summary>
<p>

[llvm][CodeGen] Resolve issues when updating live intervals in window scheduler [2651d09ec9c4](https://github.com/llvm/llvm-project/commit/2651d09ec9c4)
llvm/lib/CodeGen/ModuloSchedule.cpp | 3 +++
1 file changed, 3 insertions(+)

[AArch64] Disable SVE paired ld1/st1 for callee-saves. [5e1a55eaa0bb](https://github.com/llvm/llvm-project/commit/5e1a55eaa0bb)
llvm/lib/Target/AArch64/AArch64FrameLowering.cpp | 33 ------------------------
1 file changed, 33 deletions(-)

**[SLP]Fix PR107036: Check if the type of the user is sizable before requesting its size. [42f18eedc2cf](https://github.com/llvm/llvm-project/commit/42f18eedc2cf)**
llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp | 5 +++++
1 file changed, 5 insertions(+)

[RemoveDIs] Fix spliceDebugInfo splice-to-end edge case [11e2a1552f92](https://github.com/llvm/llvm-project/commit/11e2a1552f92)
llvm/lib/IR/BasicBlock.cpp | 12 ++++++++++--
1 file changed, 10 insertions(+), 2 deletions(-)

[AArch64] Remove redundant COPY from loadRegFromStackSlot [52e5a72e9200](https://github.com/llvm/llvm-project/commit/52e5a72e9200)
llvm/lib/Target/AArch64/AArch64InstrInfo.cpp | 4 ----
1 file changed, 4 deletions(-)

[AVR] Fix parsing & emitting relative jumps [830b7ebac09e](https://github.com/llvm/llvm-project/commit/830b7ebac09e)
llvm/lib/Target/AVR/AsmParser/AVRAsmParser.cpp     | 15 +++++++++++----
llvm/lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp | 12 +++++-------
2 files changed, 16 insertions(+), 11 deletions(-)

[DebugInfo][RemoveDIs] Find types hidden in DbgRecords [f3da9af3fd26](https://github.com/llvm/llvm-project/commit/f3da9af3fd26)
llvm/lib/IR/DebugProgramInstruction.cpp |  5 +++--
llvm/lib/IR/TypeFinder.cpp              | 14 ++++++++++++++
2 files changed, 17 insertions(+), 2 deletions(-)

[IndVars] Check if WideInc available before trying to use it [e594b284810c](https://github.com/llvm/llvm-project/commit/e594b284810c)
llvm/lib/Transforms/Utils/SimplifyIndVar.cpp | 28 +++++++++++++++++-----------
1 file changed, 17 insertions(+), 11 deletions(-)

[Instrumentation] Fix EdgeCounts vector size in SetBranchWeights [f131edf6fbe8](https://github.com/llvm/llvm-project/commit/f131edf6fbe8)
llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp | 14 ++++++++++----
1 file changed, 10 insertions(+), 4 deletions(-)

[RemoveDIs] Simplify spliceDebugInfo, fixing splice-to-end edge case [e1be8cf8723e](https://github.com/llvm/llvm-project/commit/e1be8cf8723e)
llvm/lib/IR/BasicBlock.cpp | 24 ++++++++++--------------
1 file changed, 10 insertions(+), 14 deletions(-)

[analyzer] Add missing include <unordered_map> to llvm/lib/Support/Z3Solver.cpp [894ec4e3a1d5](https://github.com/llvm/llvm-project/commit/894ec4e3a1d5)
llvm/lib/Support/Z3Solver.cpp | 1 +
1 file changed, 1 insertion(+)

[PowerPC] Fix mask for __st[d/w/h/b]cx builtins [ed699666de2d](https://github.com/llvm/llvm-project/commit/ed699666de2d)
llvm/lib/Target/PowerPC/PPCInstr64Bit.td |  4 ++--
llvm/lib/Target/PowerPC/PPCInstrInfo.td  | 12 ++++++------
2 files changed, 8 insertions(+), 8 deletions(-)

[AMDGPU] Remove one case of vmcnt loop header flushing for GFX12 [09cca6b1897d](https://github.com/llvm/llvm-project/commit/09cca6b1897d)
llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)

[AMDGPU] GFX12 VMEM loads can write VGPR results out of order [441fb41cb487](https://github.com/llvm/llvm-project/commit/441fb41cb487)
llvm/lib/Target/AMDGPU/AMDGPU.td            | 23 +++++++++++++++++------
llvm/lib/Target/AMDGPU/GCNSubtarget.h       |  3 +++
llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp |  7 ++++---
3 files changed, 24 insertions(+), 9 deletions(-)

[PowerPC] Respect endianness when bitcasting to fp128 [45b149d25319](https://github.com/llvm/llvm-project/commit/45b149d25319)
llvm/lib/Target/PowerPC/PPCISelLowering.cpp | 14 +++++++++-----
1 file changed, 9 insertions(+), 5 deletions(-)

[llvm][CodeGen] Address the issue of multiple resource reservations In window scheduling [54579830d81a](https://github.com/llvm/llvm-project/commit/54579830d81a)
llvm/lib/CodeGen/WindowScheduler.cpp | 1 -
1 file changed, 1 deletion(-)

[llvm][CodeGen] Fixed max cycle calculation with zero-cost instructions for window scheduler [5a164a28e37f](https://github.com/llvm/llvm-project/commit/5a164a28e37f)
llvm/lib/CodeGen/WindowScheduler.cpp | 16 ++++++++++------
1 file changed, 10 insertions(+), 6 deletions(-)

[llvm][CodeGen] Fixed a bug in stall cycle calculation for window scheduler [06d009789f77](https://github.com/llvm/llvm-project/commit/06d009789f77)
llvm/lib/CodeGen/WindowScheduler.cpp | 7 ++++---
1 file changed, 4 insertions(+), 3 deletions(-)

[llvm][CodeGen] Added a new restriction for II by pragma in window scheduler [7b86034dcb8c](https://github.com/llvm/llvm-project/commit/7b86034dcb8c)
llvm/lib/CodeGen/MachinePipeliner.cpp | 12 ++++++++++--
1 file changed, 10 insertions(+), 2 deletions(-)

[llvm][CodeGen] Added missing initialization failure information for window scheduler [e81188d58202](https://github.com/llvm/llvm-project/commit/e81188d58202)
llvm/lib/CodeGen/WindowScheduler.cpp | 5 ++++-
1 file changed, 4 insertions(+), 1 deletion(-)

[AArch64] Make apple-m4 armv8.7-a again (from armv9.2-a).  [eba1ef5a1b7a](https://github.com/llvm/llvm-project/commit/eba1ef5a1b7a)
llvm/lib/Target/AArch64/AArch64Processors.td | 7 ++++++-
1 file changed, 6 insertions(+), 1 deletion(-)

[DwarfEhPrepare] Assign dummy debug location for more inserted _Unwind_Resume calls [5f744ee5c770](https://github.com/llvm/llvm-project/commit/5f744ee5c770)
llvm/lib/CodeGen/DwarfEHPrepare.cpp | 7 +++++++
1 file changed, 7 insertions(+)

[MCA][X86] Add missing 512-bit vpscatterqd/vscatterqps schedule data (REAPPLIED) [cfe8eb89cbb8](https://github.com/llvm/llvm-project/commit/cfe8eb89cbb8)
llvm/lib/Target/X86/X86SchedIceLake.td       | 2 ++
llvm/lib/Target/X86/X86SchedSkylakeServer.td | 2 ++
2 files changed, 4 insertions(+)

[ConstraintElim] Fix miscompilation caused by PR97974 [3ff9d92aae09](https://github.com/llvm/llvm-project/commit/3ff9d92aae09)
llvm/lib/Transforms/Scalar/ConstraintElimination.cpp | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)

[DAGCombiner] Fix ReplaceAllUsesOfValueWith mutation bug in visitFREEZE [b6a562d90fa0](https://github.com/llvm/llvm-project/commit/b6a562d90fa0)
llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp | 22 ++++++++++++++++++----
1 file changed, 18 insertions(+), 4 deletions(-)

[AMDGPU] Disable inline constants for pseudo scalar transcendentals [43b455b2d2e5](https://github.com/llvm/llvm-project/commit/43b455b2d2e5)
llvm/lib/Target/AMDGPU/GCNSubtarget.h  | 6 ++++++
llvm/lib/Target/AMDGPU/SIInstrInfo.cpp | 4 ++++
llvm/lib/Target/AMDGPU/SIInstrInfo.h   | 8 ++++++++
3 files changed, 18 insertions(+)

[SPARC] Remove assertions in printOperand for inline asm operands [8ea372d8b628](https://github.com/llvm/llvm-project/commit/8ea372d8b628)
llvm/lib/Target/Sparc/SparcAsmPrinter.cpp | 51 -------------------------------
1 file changed, 51 deletions(-)


</p>
</details>

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-09-19/near/471494785). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted

**Pull request merged**
