### PR TITLE
Avoid accidentally enabling unstable features in compilers (take 2)

### PR DESCRIPTION
**Pull request by jyn514**
This allows rustbuild to control whether crates can use nightly features or not.
It also prevents rustbuild from using nightly features itself.

This is #92261, but I fixed the CI error.

### CODE REVIEW

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/92261#issuecomment-1030940502:

> Instead it fails because bootstrap unconditionally passes -Z flags to cargo:

Worked around that by passing `-Zallow-features=binary-bin-deps`. Unfortunately anyhow decides to do feature detection in build.rs :facepalm: which breaks when -Zallow-features later disallows it. With `backtrace` added to allow-features, everything seems to work though :)

**Comment by jyn514** [comment]
Oops, I pushed https://github.com/rust-lang/rust/pull/97277/commits/751ad4a0e9fc43a9e810cce69d4cef581323e79a right as you reviewed - do you want me to back that out for now?

**Comment by Mark-Simulacrum** [comment]
No, I saw it and it seems good to me.

**Pull request merged**
