### PR TITLE
bootstrap: compactify --check-cfg arguments

### PR DESCRIPTION
**Pull request by est31**
The current code creates more --check-cfg arguments than needed,
especially one argument per bare name. To save arguments,
we now collect the name specific arguments into one.

Before, the code this commit changes would have generated
these arguments for a typical compiler crate:

>    '--check-cfg=values(bootstrap)' '--check-cfg=values(parallel_compiler)' '--check-cfg=values(no_btreemap_remove_entry)' '--check-cfg=values(crossbeam_loom)' '--check-cfg=values(span_locations)'

Now it generates:

>    '--check-cfg=names(bootstrap,parallel_compiler,no_btreemap_remove_entry,crossbeam_loom,span_locations)'

### CODE REVIEW

**Comment by est31** [comment]
cc @Urgau

**Comment by Urgau** [comment]
Those are not equivalent, `values(bootstrap)` state that a key named `bootstrap` exist and that no values are associated with it and `names(bootstrap)` state that a key named `bootstrap` exist but we know nothing about the possible values associated with it. (Note: this is a little simplified because there could have been values inserted previously, but that's not the case here).

This change would allow someone to mistakenly write `cfg(bootstrap = "test")` without being detected, while it's currently detected as being unexpected and produce an error.

**Comment by est31** [comment]
Oh I see, I've thought they were. Thanks for your explanation. I wonder if there could be a `flags()` next to `names()` and `values()` as a shorthand for many `values(...)` calls. Personally, I feel that most `cfg` attrs in the wild are binary yes/no things so one should support them in a nicer fashion.

**Comment by Urgau** [comment]
> I wonder if there could be a `flags()` next to `names()` and `values()` as a shorthand for many `values(...)` calls. Personally, I feel that most `cfg` attrs in the wild are binary yes/no things so one should support them in a nicer fashion.

Maybe, but I don't think it's a big issue, most projects that will need to manually set `--check-cfg` args will only have a small number (<=2 ?) so I don't think it would be problematic to have multiples args; there isn't a way to do this with `--cfg`.

Also as we can see here the syntax implication is already not simple and I fear that adding another thing will only make things worse not better.

**Comment by jyn514** [comment]
I see both names() and values() in the diff. What's the state of this PR? Is it possible to use a shorter syntax while keeping the same meaning or should it just be closer?

**Comment by jyn514** [comment]
(I agree with @Urgau that making the invocation slightly shorter doesn't seem worth making the syntax more complicated.)

**Comment by est31** [comment]
Yeah let's close this. I'm still not happy about it, and the difference is only that `values()` also checks that you don't do `#[cfg(bootstrap = "yes")]`, which is way less likely to happen than a typo like `#[cfg(botstrap)]` or something. So it's only a detail but I guess it's not that costly to have the longer invocation...

**Pull request closed without merging**
