### PR TITLE
bootstrap: fix edition

### PR DESCRIPTION
**Pull request by ljedrz**
A byproduct of work on https://github.com/rust-lang/rust/pull/56595; done with `cargo fix --edition`.

### CODE REVIEW

**Comment by ljedrz** [comment]
Heh, seems like `cargo fix` is not `target_os`-agnostic ^^.

**Comment by ljedrz** [comment]
```
failed to resolve: could not find `TokenStream(/TokenTree...)` in `{{root}}`
```

That's weird; these *are* in the crate root 🤔...

**Comment by ljedrz** [comment]
I give up with `proc_macro` for now; it's either a bug or some intricate test-related stuff.

**Comment by alexcrichton** [comment]
@bors: retry

* CI automation hiccup

**Comment by pietroalbini** [comment]
@bors retry

Yielding priority.

**Pull request merged**
