### PR TITLE
add a -Z flag to guarantee that MIR is generated for all functions

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb 

cc @solson

### CODE REVIEW

**Comment by eddyb** [comment]
Could this be `-Z` instead? To avoid it being insta-stable. LGTM otherwise.

**Comment by oli-obk** [comment]
done

**Comment by oli-obk** [comment]
This now produces a working compiler (stage2 is building right now) without the flag enabled. It also allows me to compile miri and all its dependencies with the flag enabled (not that there's any point, but I didn't want to wait for an entire compiler to build with the flag enabled). So this is basically working now. I know it has no tests yet. I promise I will write them on monday. Would it be possible to r+ this PR without the tests?

**Comment by solson** [comment]
I successfully built stage2 with the newest code in this PR and the flag hardcoded to true.

**Comment by eddyb** [comment]
@oli-obk Testing this seems tricky, probably impossible w/o writing a plugin.
@bors r+

**Pull request merged**
