### PR TITLE
Closure capture cleanup & refactor

### PR DESCRIPTION
**Pull request by nbdd0121**
Follow up of #89648

Each commit is self-contained and the rationale/changes are documented in the commit message, so it's advisable to review commit by commit.

The code is significantly cleaner (at least IMO), but that could have some perf implication, so I'd suggest a perf run.

r? @wesleywiser
cc @arora-aman

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 141f36eb94d72f67dfd9c393c50026f544b48579

**Review by wesleywiser — APPROVED** [review]
Sorry for the delay in review, this looks really great!

**Pull request merged**
