### PR TITLE
Run some stuff in parallel

### PR DESCRIPTION
**Pull request by Zoxc**
Requires https://github.com/rust-lang/rust/pull/50699 to actually work correctly.

r? @nikomatsakis

### CODE REVIEW

**Comment by Zoxc** [comment]
@Mark-Simulacrum Can I get a perf run?

**Comment by nikomatsakis** [comment]
What exactly are you testing, given that #50699 didn't land yet?

**Comment by Zoxc** [comment]
This adds `Lock`s to mono item collection so I want to make sure this doesn't add overhead for single-threaded rustc.

**Comment by nikomatsakis** [comment]
Ah, of course. Sounds good!

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
r=me modulo perf results

**Comment by Zoxc** [comment]
I got rid of the `RefCell` which should avoid the performance regression without `cfg(parallel_queries)`. `MTRef<'a, MTLock<T>` maps to `&'a Lock<T>` with parallel queries and `&'a mut T` without.

**Comment by nikomatsakis** [comment]
@Zoxc r=me once rebased

**Pull request merged**
