### PR TITLE
Move Vec UI tests to unit tests when possible

### PR DESCRIPTION
**Pull request by poliorcetics**
Helps with #76268.

I'm moving the tests using `Vec` or `VecDeque`.

@rustbot modify labels: A-testsuite C-cleanup T-libs

### CODE REVIEW

**Comment by poliorcetics** [comment]
I'm sorry, I forgot to add WIP to the title, I'm not done at all with this PR

**Comment by poliorcetics** [comment]
It can be merged and I can open another but that would separate related work across two PRs

**Comment by poliorcetics** [comment]
I will look into before the end of the week, I'm currently busy with the survey's translation.

**Comment by poliorcetics** [comment]
I think this can be merged as is, more work can be done in another PR without problems and hitting more merge conflicts sounds painful.

**Comment by jyn514** [comment]
@bors r+ rollup

For posterity, `git show -w --reverse --color-moved=dimmed-zebra --color-moved-ws=allow-indentation-change dda2b5e3e260c14b868c494008af1c8981eaa5a8..` made this _so_ much easier to review.

**Pull request merged**
