### PR TITLE
Derive `Copy` for `VarianceDiagInfo`

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Aaron1011** [comment]
The performance improvements suggest that it might be worth trying to revive https://github.com/rust-lang/rust/pull/72409 in some form - the compiler shouldn't need a `#[derive(Copy)]` to perform these kinds of optimizations.

**Comment by klensy** [comment]
Improvement in one bench, but max-rss is red in most cases (given that max-rss bench results accuracy not high and can be scattered up and down).

**Review by davidtwco — APPROVED** [review]
LGTM, r=me if this is something you wanted to land and not just an experiment to check #72409's viability.

**Comment by Aaron1011** [comment]
This is intended to fix the performance regression caused by adding the variance diag info.

@bors r=davidtwco

**Comment by pnkfelix** [comment]
Thanks @Aaron1011 ! [End results](https://perf.rust-lang.org/compare.html?start=fecc65a19763364b8dafbbf1d23be562268bd387&end=47b2f15bba4544170e6e748910e7c01da467c897&stat=instructions:u) look good to me.

**Pull request merged**
