### PR TITLE
Remove `NodeState::{Waiting,Done}`

### PR DESCRIPTION
**Pull request by nnethercote**
An optimization, and then some clean-ups.

r? @nikomatsakis

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage
@nikomatsakis can you please review this PR?
Thanks

**Review by nikomatsakis — APPROVED** [review]

**Comment by nnethercote** [comment]
Actually, I'm going to do some more changes here.

@bors r-

**Comment by nnethercote** [comment]
The new commits subsume the old ones.

r? @nikomatsakis

**Comment by nnethercote** [comment]
Not sure what went wrong, and this passed tests locally, so let's try again.

@bors retry

**Review by nikomatsakis — APPROVED** [review]
r=me once perf results are known

**Comment by nnethercote** [comment]
@Centril: Is there a way to look at the log for the timed-out test? I can't see how to do it, which makes it hard to know if this is a problem with my PR or an infrastructure problem.

**Comment by Centril** [comment]
^-- @pietroalbini

**Comment by nnethercote** [comment]
In the absence of other obvious options, let's try again.

@bors retry

**Comment by nnethercote** [comment]
`find_cycles_from_node` could reprocess nodes in the new code. This caused some slight regressions on a couple of benchmarks. I've fixed it now. Doesn't seem like that could have caused timeouts, but who knows. Let's try once again.

@bors try

**Comment by pietroalbini** [comment]
> Is there a way to look at the log for the timed-out test? I can't see how to do it, which makes it hard to know if this is a problem with my PR or an infrastructure problem.

@nnethercote there should be a red "x" in the commit reference:



If you click it you'll be able to see the list of builders, and a link to the logs.

**Comment by nnethercote** [comment]
@pietroalbini: thank you! That link is well-hidden.

**Comment by nnethercote** [comment]
The perf run didn't seem to work, let's try again.

@rust-timer build 04d9ca79a007c33a733ef523601ab37661c3a28d

**Comment by nnethercote** [comment]
The perf results are in for the parent commit (14195e1f) but not for this commit (04d9ca79) and I don't see 04d9ca79 in the [queue](https://perf.rust-lang.org/status.html). I will rebase and try again.

**Comment by nnethercote** [comment]
Those perf results don't match my local results, which look like this:
```
inflate-check
        avg: -3.7%      min: -3.7%      max: -3.7%
keccak-check
        avg: -3.5%      min: -3.5%      max: -3.5%
regression-31157-check
        avg: 0.7%       min: 0.7%       max: 0.7%
cranelift-codegen-check
        avg: -0.5%      min: -0.5%      max: -0.5%
clap-rs-check
        avg: -0.4%      min: -0.4%      max: -0.4%
wg-grammar-check
        avg: 0.3%       min: 0.3%       max: 0.3%
unify-linearly-check
        avg: 0.2%       min: 0.2%       max: 0.2%
style-servo-check
        avg: -0.2%      min: -0.2%      max: -0.2%
serde-check
        avg: -0.1%      min: -0.1%      max: -0.1%
```
This mismatch is just like the mismatch in #67079. I am now wondering if something has gone wrong with rustc-perf, whether it could be not measuring what it says it is measuring.

**Comment by nikomatsakis** [comment]
> This mismatch is just like the mismatch in #67079. I am now wondering if something has gone wrong with rustc-perf, whether it could be not measuring what it says it is measuring.

cc @Mark-Simulacrum ☝️

**Comment by nnethercote** [comment]
I rebased. Let's try another perf CI run, see if the results have changed :/

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
The new results still don't really match what I got locally, but they do show it as a small win, so I'm going to land this.

@bors r=nikomatsakis

**Comment by nnethercote** [comment]
@bors rollup=never

(The rollup directive above was from an earlier version of this PR when the changes were much simpler.)

**Comment by sdroege** [comment]
This seems to have caused https://github.com/rust-lang/rust/issues/67454, which is maybe a duplicate of https://github.com/rust-lang/rust/issues/67331

**Pull request merged**
