### PR TITLE
Add #[inline] to small functions in core

### PR DESCRIPTION
**Pull request by saethlin**
I'm adding a new case to the definition of cross-crate-inlinable; we know that making the definition too broad causes huge regressions in incremental builds. So implementing broader heuristics as a machine-applicable lint means that I can `x fix --stage 1 library/core` to apply the new heuristic just to the standard library. I expect that applying the broader heuristic just to the standard library will have a different effect than applying the change globally.

### CODE REVIEW

**Comment by saethlin** [comment]
I'm going to try a slightly different approach just to see what happens- this time I'm adding `#[inline]` to non-generic functions that do not have a Call or Assert terminator.

**Comment by saethlin** [comment]
r? libs

**Comment by matthiaskrgr** [comment]
This really should be a compiler optimization... (yes I have seen the 116505)
I'm a bit worried, if someone happens to modify one of these functions to be a bit bigger, could this result in a blowup across tens of other functions and cause weird unexpected regressions because we suddenly now inline a lot of code?

**Comment by erikdesjardins** [comment]
@matthiaskrgr I'm not sure what exactly the situation you're envisioning is. If this were an optimization instead of explicit `#[inline]`, and someone made one of these functions a bit bigger, such that the optimization would then decide not to make it inlineable...there would still be a regression, the inverse of the improvement in this PR, due to the function not being inlined. You can't really avoid that.

Also note that this is `#[inline]`, not `#[inline(always)]`. LLVM and mir-opt still have size limits, so if one of these functions becomes huge, it won't get inlined.

**Comment by matthiaskrgr** [comment]
I was thinking of an inline function causing worse codegen than no inline at all of that function (perhaps preventing callers from being inlined).

Do we have something like opt remarkt like "hey, you tried to inline hugefn with more than 42 BBs, we didn't inline it actually"

**Comment by saethlin** [comment]
> I was thinking of an inline function causing worse codegen than no inline at all of that function (perhaps preventing callers from being inlined).

That just sounds like a bug in the optimizer. The inlining optimization is still done at the optimizer's discretion, and it has complete freedom when LTO is enabled.

**Comment by saethlin** [comment]
This might just be subsumed by the preceding PR since my last tweak.

**Comment by saethlin** [comment]
Ah, UI tests are going to fail all over because I've added warnings. oops
@bors try @rust-timer queue

**Comment by saethlin** [comment]
That looks like it might be moving in a good direction? Notably the big improvements are all in `helloworld` so I think the report looks better than the real-world impact would be.
@bors try @rust-timer queue

**Comment by saethlin** [comment]
Wow that is not the direction I expected.

**Comment by saethlin** [comment]
I'm not actually planning to move this PR forward; this was an experiment that resulted in adding `#[inline]` to derived Debug impls. I don't think there's much else to be gained here.

A lint that suggests `#[inline]` is a decent idea, but if I could figure out how to write that lint well I would also be able to improve `cross_crate_inlinable` and obviate the lint.

**Pull request closed without merging**
