### PR TITLE
Add BE8 support

### PR DESCRIPTION
**Pull request by WorksButNotTested**
Built using the following `/config.toml`
```
changelog-seen = 2

[llvm]
download-ci-llvm = false
skip-rebuild = true
optimize = true
ninja = true
targets = "ARM;X86"
clang = false

[build]
target = ["x86_64-unknown-linux-gnu", "armeb-linux-gnueabi"]
docs = false
docs-minification = false
compiler-docs = false
[install]
prefix = "/home/user/x-tools/rust/"

[rust]
debug-logging=true
backtrace = true
incremental = true

[target.x86_64-unknown-linux-gnu]

[dist]

[target.armeb-linux-gnueabi]
cc = "/home/user/x-tools/armeb-linux-gnueabi/bin/armeb-linux-gnueabi-gcc"
cxx = "/home/user/x-tools/armeb-linux-gnueabi/bin/armeb-linux-gnueabi-g++"
ar = "/home/user/x-tools/armeb-linux-gnueabi/bin/armeb-linux-gnueabi-ar"
ranlib = "/home/user/x-tools/armeb-linux-gnueabi/bin/armeb-linux-gnueabi-ranlib"
linker = "/home/user/x-tools/armeb-linux-gnueabi/bin/armeb-linux-gnueabi-gcc"
llvm-config = "/home/user/x-tools/clang/bin/llvm-config"
llvm-filecheck = "/home/user/x-tools/clang/bin/FileCheck"
```

The following `.cargo/config` is needed inside any project directory:
```
[build]
target = "armeb-linux-gnueabi"

[target.armeb-linux-gnueabi]
linker = "armeb-linux-gnueabi-gcc"
```

### CODE REVIEW

**Comment by jackh726** [comment]
Just going to reroll this - I'd rather try to get someone who can review this more promptly.

r? compiler

**Comment by WorksButNotTested** [comment]
> Just going to reroll this - I'd rather try to get someone who can review this more promptly.
> 
> r? compiler

I’m not precious about my commit. Just needed to add BE8 support as a feature. It’s working for me, but I’m not so familiar with the internals of rust to say I’ve gone about it in the right way. If anyone has a different or better way of doing it, then that’s just fine with me. Just wanted to make the PR to get some feedback.

**Comment by wesleywiser** [comment]
Hi @WorksButNotTested, thanks for the PR!

There's a few things you'll need to do before we can merge this:

- Please add an entry to the Tier 3 section in this document for the target [`src/doc/rustc/src/platform-support.md`](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support.md).
- We're also asking people to add a page to the `platform-support` directory in the same folder. You can find look at some of the other pages in that folder as an example (for instance [`src/doc/rustc/src/platform-support/wasm64-unknown-unknown.md`](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support/wasm64-unknown-unknown.md)). 
- Finally, please quote the corresponding requirements verbatim from the [tier 3 target tier policy](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-3-target-policy) to explain how the target meets those requirements (leaving a new comment here is fine). You can find an example of this in the PR description for #86191. 

Thank you!

**Comment by WorksButNotTested** [comment]
# Tier 3 target policy

At this tier, the Rust project provides no official support for a target, so we
place minimal requirements on the introduction of targets.

A proposed new tier 3 target must be reviewed and approved by a member of the
compiler team based on these requirements. The reviewer may choose to gauge
broader compiler team consensus via a [Major Change Proposal (MCP)][MCP].

A proposed target or target-specific patch that substantially changes code
shared with other targets (not just target-specific code) must be reviewed and
approved by the appropriate team for that shared code before acceptance.

- A tier 3 target must have a designated developer or developers (the "target
  maintainers") on record to be CCed when issues arise regarding the target.
  (The mechanism to track and CC such developers may evolve over time.)

  ***[@WorksButNotTested](https://github.com/WorksButNotTested)***

- Targets must use naming consistent with any existing targets; for instance, a
  target for the same CPU or OS as an existing Rust target should use the same
  name for that CPU or OS. Targets should normally use the same names and
  naming conventions as used elsewhere in the broader ecosystem beyond Rust
  (such as in other toolchains), unless they have a very good reason to
  diverge. Changing the name of a target can be highly disruptive, especially
  once the target reaches a higher tier, so getting the name right is important
  even for a tier 3 target.
  - Target names should not introduce undue confusion or ambiguity unless
    absolutely necessary to maintain ecosystem compatibility. For example, if
    the name of the target makes people extremely likely to form incorrect
    beliefs about what it targets, the name should be changed or augmented to
    disambiguate it.

  ***The target name follows the naming conventions adopted by the GNU toolchain, namely
    the host triplet `architecture-<vendor>-host-abi`. The vendor portion of this is optional
    and irrelevant in this case and hence omitted***

- Tier 3 targets may have unusual requirements to build or use, but must not
  create legal issues or impose onerous legal terms for the Rust project or for
  Rust developers or users.
  - The target must not introduce license incompatibilities.
    ***The target is dependent only on the GNU toolchains***
  - Anything added to the Rust repository must be under the standard Rust
    license (`MIT OR Apache-2.0`).
    ***The target requires only minimal changes and these are contributed under the MIT/Apache-2.0 license***
  - The target must not cause the Rust tools or libraries built for any other
    host (even when supporting cross-compilation to the target) to depend
    on any new dependency less permissive than the Rust licensing policy. This
    applies whether the dependency is a Rust crate that would require adding
    new license exceptions (as specified by the `tidy` tool in the
    rust-lang/rust repository), or whether the dependency is a native library
    or binary. In other words, the introduction of the target must not cause a
    user installing or running a version of Rust or the Rust tools to be
    subject to any new license requirements.
    ***The target does not introduce any dependencies for the use of other platforms***
  - Compiling, linking, and emitting functional binaries, libraries, or other
    code for the target (whether hosted on the target itself or cross-compiling
    from another target) must not depend on proprietary (non-FOSS) libraries.
    Host tools built for the target itself may depend on the ordinary runtime
    libraries supplied by the platform and commonly used by other applications
    built for the target, but those libraries must not be required for code
    generation for the target; cross-compilation to the target must not require
    such libraries at all. For instance, `rustc` built for the target may
    depend on a common proprietary C runtime library or console output library,
    but must not depend on a proprietary code generation library or code
    optimization library. Rust's license permits such combinations, but the
    Rust project has no interest in maintaining such combinations within the
    scope of Rust itself, even at tier 3.
    ***The target is dependent only on the GNU toolchains***
  - "onerous" here is an intentionally subjective term. At a minimum, "onerous"
    legal/licensing terms include but are *not* limited to: non-disclosure
    requirements, non-compete requirements, contributor license agreements
    (CLAs) or equivalent, "non-commercial"/"research-only"/etc terms,
    requirements conditional on the employer or employment of any particular
    Rust developers, revocable terms, any requirements that create liability
    for the Rust project or its developers or users, or any requirements that
    adversely affect the livelihood or prospects of the Rust project or its
    developers or users.
    ***The target does not introduce any additional licensing requirements***
- Neither this policy nor any decisions made regarding targets shall create any
  binding agreement or estoppel by any party. If any member of an approving
  Rust team serves as one of the maintainers of a target, or has any legal or
  employment requirement (explicit or implicit) that might affect their
  decisions regarding a target, they must recuse themselves from any approval
  decisions regarding the target's tier status, though they may otherwise
  participate in discussions.
  - This requirement does not prevent part or all of this policy from being
    cited in an explicit contract or work agreement (e.g. to implement or
    maintain support for a target). This requirement exists to ensure that a
    developer or team responsible for reviewing and approving a target does not
    face any legal threats or obligations that would prevent them from freely
    exercising their judgment in such approval, even if such judgment involves
    subjective matters or goes beyond the letter of these requirements.
- Tier 3 targets should attempt to implement as much of the standard libraries
  as possible and appropriate (`core` for most targets, `alloc` for targets
  that can support dynamic memory allocation, `std` for targets with an
  operating system or equivalent layer of system-provided functionality), but
  may leave some code unimplemented (either unavailable or stubbed out as
  appropriate), whether because the target makes it impossible to implement or
  challenging to implement. The authors of pull requests are not obligated to
  avoid calling any portions of the standard library on the basis of a tier 3
  target not implementing those portions.
  ***The target supports the normal `std` standard library***
- The target must provide documentation for the Rust community explaining how
  to build for the target, using cross-compilation if possible. If the target
  supports running binaries, or running tests (even if they do not pass), the
  documentation must explain how to run such binaries or tests for the target,
  using emulation if possible or dedicated hardware if necessary.
  ***Documentation on how to build a rust cross compiler for ARMBE8 is provided above***
- Tier 3 targets must not impose burden on the authors of pull requests, or
  other developers in the community, to maintain the target. In particular,
  do not post comments (automated or manual) on a PR that derail or suggest a
  block on the PR based on a tier 3 target. Do not send automated messages or
  notifications (via any medium, including via `@`) to a PR author or others
  involved with a PR regarding a tier 3 target, unless they have opted into
  such messages.
  - Backlinks such as those generated by the issue/PR tracker when linking to
    an issue or PR are not considered a violation of this policy, within
    reason. However, such messages (even on a separate repository) must not
    generate notifications to anyone involved with a PR who has not requested
    such notifications.
- Patches adding or updating tier 3 targets must not break any existing tier 2
  or tier 1 target, and must not knowingly break another tier 3 target without
  approval of either the compiler team or the maintainers of the other tier 3
  target.
  - In particular, this may come up when working on closely related targets,
    such as variations of the same architecture with different features. Avoid
    introducing unconditional uses of features that another variation of the
    target may not have; use conditional compilation or runtime detection, as
    appropriate, to let each target run code supported by that target.

If a tier 3 target stops meeting these requirements, or the target maintainers
no longer have interest or time, or the target shows no signs of activity and
has not built for some time, or removing the target would improve the quality
of the Rust codebase, we may post a PR to remove it; any such PR will be CCed
to the target maintainers (and potentially other people who have previously
worked on the target), to check potential interest in improving the situation.

**Comment by WorksButNotTested** [comment]
> Hi @WorksButNotTested, thanks for the PR!
> 
> There's a few things you'll need to do before we can merge this:
> 
>     * Please add an entry to the Tier 3 section in this document for the target [`src/doc/rustc/src/platform-support.md`](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support.md).
> 
>     * We're also asking people to add a page to the `platform-support` directory in the same folder. You can find look at some of the other pages in that folder as an example (for instance [`src/doc/rustc/src/platform-support/wasm64-unknown-unknown.md`](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support/wasm64-unknown-unknown.md)).
> 
>     * Finally, please quote the corresponding requirements verbatim from the [tier 3 target tier policy](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-3-target-policy) to explain how the target meets those requirements (leaving a new comment here is fine). You can find an example of this in the PR description for [Add SOLID targets #86191](https://github.com/rust-lang/rust/pull/86191).
> 
> 
> Thank you!

Thanks for the feedback. Hopefully the above is OK for the target policy? As you will see, it is pretty similar to the normal ARM little endian target definition, but with a few tiny changes. So I hope it won't introduce any problems. I have also added some docs as requested. Please let me know what you think.

**Comment by wesleywiser** [comment]
Yep, that looks good! 

The link checker is still reporting broken links. I think you might need to update [`src/doc/rustc/src/SUMMARY.md`](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/SUMMARY.md) to include the new file as well.

**Comment by wesleywiser** [comment]
> The target name follows the naming conventions adopted by the GNU toolchain, namely
the host triplet architecture-<vendor>-host-abi. The vendor portion of this is optional
and irrelevant in this case and hence omitted

I noticed most of our other similar targets include the `unknown` vendor portion. How would you feel about including that for consistency with the other existing target names?

**Comment by WorksButNotTested** [comment]
> Yep, that looks good!
> 
> The link checker is still reporting broken links. I think you might need to update [`src/doc/rustc/src/SUMMARY.md`](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/SUMMARY.md) to include the new file as well.

I think the link is working ok in the .md file, but is not working for generated HTML docs? Any idea what I’ve done wrong?

Thanks, I’ll take a look at the SUMMARY.md.

**Comment by WorksButNotTested** [comment]
> > The target name follows the naming conventions adopted by the GNU toolchain, namely
> > the host triplet architecture--host-abi. The vendor portion of this is optional
> > and irrelevant in this case and hence omitted
> 
> I noticed most of our other similar targets include the `unknown` vendor portion. How would you feel about including that for consistency with the other existing target names?

I can add that if you’d prefer. Not a problem.

**Comment by WorksButNotTested** [comment]
Does this look better?

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Looks great! Thanks for the PR @WorksButNotTested 🙂 

@bors r+ rollup

**Comment by WorksButNotTested** [comment]
> Looks great! Thanks for the PR @WorksButNotTested 🙂
> 
> @bors r+ rollup

No worries. Thanks for the feedback.

**Comment by WorksButNotTested** [comment]
Obviously I don't expect my little PR to influence your release schedule, but do you know if it will be incorporated into 1.64? I read that is to be released on 22/09 is that right?

**Comment by wesleywiser** [comment]
We use a 3 release system: stable, beta and nightly. This just landed in nightly (or, more precisely, it should be included in tonight's nightly release) so the next time a stable release happens (on September 22), the nightly release will be promoted to beta and then in 6 weeks the beta will be promoted to stable. rustbot tagged this with 1.65.0 so it will be included in that release on November 3.

**Comment by WorksButNotTested** [comment]
Awesome. Thanks for explaining for me. Just so I know when I can retire my downstream patches.

**Pull request merged**
