### PR TITLE
Implement `shrink_to` method on collections

### LINKED ISSUE #49385: Feature: more control over container (eg. Vec) capacities
Currently there is only one way to reduce the capacity of a `Vec` without clearing it completely: `vec.shrink_to_fit()`

However, often more control is needed. For example, it's common to want to shrink the capacity, but not below some threshold, eg. `vec.shrink_to(MIN_CAPACITY)`.

There are probably other cases where you would want to be able to more directly control the capacity too.

### PR DESCRIPTION
**Pull request by Diggsey**
Fixes #49385

### CODE REVIEW

**Comment by joshtriplett** [comment]
This seems reasonable to me.

@rust-lang/libs, does this seem like something that needs an RFC before it goes in?

**Comment by Diggsey** [comment]
I would like some feedback on whether panicking is the best approach here. (In the event that the requested minimum capacity is larger than the current capacity).

**Comment by alexcrichton** [comment]
@joshtriplett we're generally much more lax about unstable APIs, so this likely wouldn't require an RFC

**Comment by joshtriplett** [comment]
@alexcrichton Ah, OK.

Will the examples in the documentation automatically get run as tests? If not, this definitely needs some new tests.

**Comment by sfackler** [comment]
@joshtriplett they will be run, yeah.

**Comment by Amanieu** [comment]
This is missing a tracking issue.

**Pull request merged**
