### PR TITLE
Refactor uses of `objc_msgSend` to no longer have clashing definitions

### PR DESCRIPTION
**Pull request by madsmtm**
This is very similar to what Apple's own headers encourage you to do (cast the function pointer before use instead of making new declarations).

Additionally, I'm documenting a few of the memory management rules we're following, ensuring that the `args` function doesn't leak memory (if you wrap it in an autorelease pool).

Motivation is to avoid issues with clashing definitions, like described in https://github.com/rust-lang/rust/issues/12707#issuecomment-1570735643 and https://github.com/rust-lang/rust/issues/46188#issuecomment-1288058453, CC @bjorn3.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Alas I fear I'm also not who you're looking for. You'd need to go [even further back](https://github.com/rust-lang/rust/pull/14715) but tagging those on nearly 10-year-old PRs probably won't yield the best results.

**Comment by madsmtm** [comment]
r? rust-lang/macos

Closest team I could find to whom may be able to review this change.

**Comment by thomcc** [comment]
Really we should just be using `_NSGetArgc` and `_NSGetArgv`, it's exceptionally paranoid that we aren't. Anyway this looks fine.

@bors r+ rollup.

**Pull request merged**
