### PR TITLE
provide suggestion for incorrect deprecated syntax

### LINKED ISSUE #48271: rustdoc doc for deprecated doesn't contain hint about what use instead
Look for example to [bindgen hide_type method](https://docs.rs/bindgen/0.33.1/bindgen/struct.Builder.html#method.hide_type)

It is deprecated, and in source code there is hint what should be used instead:

```Rust
/// Hide the given type from the generated bindings. Regular expressions are
    /// supported.
    #[deprecated = "Use blacklist_type instead"]
    pub fn hide_type<T: AsRef<str>>(self, arg: T) -> Builder {
        self.blacklist_type(arg)
    }
```

but in generated html documentation there is no hint about `Use blacklist_type instead`

### PR DESCRIPTION
**Pull request by euclio**
Fixes #48271.

r? @estebank

### CODE REVIEW

**Comment by estebank** [comment]
I'd r+, but I'm worried about anyone out there incorrectly using `deprecated`, as it is [usable by 3rd party crates since 1.9.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-190-2016-05-26).

I'll do a crater run to make sure we don't blow anything up, otherwise happy with the change.

@bors try

**Comment by estebank** [comment]
@craterbot run start=master#adbfec229ce07ff4b2a7bf2d6dec2d13cb224980 end=try#bad365140e1e8233b42b21af70a407f14ce5fec5 mode=check-only

**Comment by estebank** [comment]
@euclio It seems like we'll have to turn it into a warning or (ideally) lint, and [reach out to `arc-swap` to fix their use of `deprecated`](https://github.com/vorner/arc-swap/issues/13).

**Comment by vorner** [comment]
Sorry for the problems :-|. I've released a fix for that.

But going through the crater report randomly, it seems there are other ones too.

**Comment by estebank** [comment]
@vorner no need to apologize, if we didn't want you to write the attribute that way we should have made it a hard error :)

@euclio do you think you'll be able to turn this into a lint? That way we can merge it as allow by default, and a few releases down the line enable it as warn and finally deny by default.

**Comment by Centril** [comment]
Hmm... Even tho it wasn't mandated by an RFC, given that `#[deprecated = "foobar"]` is already supported in the language, I think It'd rather have this fixed in `rustdoc` instead of removing `#[deprecated = "foobar"]` from the language. It seems harmless to support and it reduces churn in libraries.

cc @rust-lang/lang @rust-lang/libs

**Comment by cramertj** [comment]
Not only is it harmless, I think this is the only reasonable option-- lots of code has used `#[deprecated = "...."]` today without knowing that it was the "incorrect" way of writing that code. Starting to error on that code would be a breaking change for essentially no reason (this isn't unsound, difficult to support, etc. and it doesn't interact poorly with other language features AFAIK), which seems like a violation of our backwards-compatibility guarantees.

**Comment by euclio** [comment]
I would prefer going with a future-incompat lint here instead of deviating from the RFC. `deprecated = "1.2.3"` seems just as reasonable to me syntactically and that would be incorrectly interpreted as the note if we begin to accept that syntax. Furthermore, It's trivial to fix this with `cargo fix` during the warning period.

**Comment by Centril** [comment]
@euclio 

> I would prefer going with a future-incompat lint here instead of deviating from the RFC.

That has to be measured against a) the churn to libraries it will cause, b) the negative reputation wrt. stability. It does not seem clear to me that making it an eventual error is right.

> `deprecated = "1.2.3"` seems just as reasonable to me syntactically and that would be incorrectly interpreted as the note if we begin to accept that syntax.

I don't think `deprecated = "1.2.3"` is too problematic; the worst thing that could happen is that the user sees:

```
warning: use of deprecated item 'foo': 1.2.3
```

which while not obvious to everyone wrt. intent is still better than nothing.

We could also implement a heuristic in the compiler that understands the format `\d+.\d+(.\d+)?`.

Given @cramertj's concurrence I move that we:

@rfcbot close

**Comment by estebank** [comment]
@Centril I would still like to add it as a lint, so that individual projects can require the newer syntax at will. I don't think we could change this to deny-by-default until the next epoch.

**Comment by Centril** [comment]
> @Centril I would still like to add it as a lint, so that individual projects can require the newer syntax at will. 

I would be OK with an `allow`-by-default lint; The FCP is for not erroring.

> I don't think we could change this to deny-by-default until the next epoch.

I don't think we should change it even in Rust 2021.

**Comment by euclio** [comment]
To be clear, I don't think we should error either. I'm arguing for a warn-by-default future-incompat lint.

**Comment by Centril** [comment]
@euclio 

> To be clear, I don't think we should error either. I'm arguing for a warn-by-default future-incompat lint.

A warn-by-default `C-future-compatibility` lint would mean that we intend to eventually make it a hard error.

**Comment by euclio** [comment]
Yes, that would be my intention. Likely in the next edition.

**Comment by Centril** [comment]
Right; what I'm saying is that I don't think we should make it an error ever because the churn doesn't seem worth it. :)

**Comment by euclio** [comment]
I understand, but I'd prefer to stick with the syntax specified in the RFC. I'll defer to the Lang team's decision, however.

**Comment by vorner** [comment]
If I may add my humble 2 cents, there's something good on „one correct way to do things“ so if the `#[deprecated = "note"]` is somehow discouraged, I'd personally prefer that to be warn-by-default (and maybe leave it as that forever ‒ there are lints that never plan to become hard errors, like `dead-code` or deprecated items in the standard library).

**Comment by joshtriplett** [comment]
I'd be happy with keeping the deprecated syntax for deprecated, and treating it as the note, as long as we have a warn-by-default lint for the very specific case where the value looks like a semver.

**Comment by Centril** [comment]
@joshtriplett That seems fine to me tho I wonder if it will arise in practice?

**Comment by euclio** [comment]
How does this fit in with #57321 and the `ill_formed_attribute_input` lint? As I said before, I'm personally against deviating from the RFC so I would prefer to make this part of that lint. However, if the lang team instead wants to accept `#[deprecated = "note"]` then I can implement that instead. I'm just looking for consensus.

**Comment by nikomatsakis** [comment]
Discussed briefly in the @rust-lang/lang meeting today. All present agreed that we might as well "retcon" the `#[deprecated = "foo"]` syntax as a shorthand for `#[deprecated(note = "foo")]`, given that it is in widespread use.

**Comment by euclio** [comment]
Ok, I'll close this PR and open an implementation of the "retcon" shortly, then. Thanks for the input, everyone!

**Pull request closed without merging**
