### PR TITLE
[DO NOT MERGE]: Try out 128bit Metrohash for incr. comp. hashes.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This is just for performance testing on perf.rust-lang.org. It's not meant to be merged in this state.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
http://perf.rust-lang.org/compare.html?commit_a=fd8099f0ecc2fd3980469ec45cf834ae9a941ca3&commit_b=00beaf41c70916670fa9ef58944f59a9f0bc774c&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
And thanks again, @Mark-Simulacrum!

Here's the actual comparison (red/green vs red/green):
http://perf.rust-lang.org/compare.html?commit_a=d7e73e4b1abe120520d1894b89c0e25469f41e69&commit_b=00beaf41c70916670fa9ef58944f59a9f0bc774c&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
Closing, see follow-up here: https://github.com/rust-lang/rust/issues/41215#issuecomment-334408968

**Pull request closed without merging**
