### PR TITLE
Update compiler error 0034 to use new format.

### PR DESCRIPTION
**Pull request by athulappadan**
Part of #35233 
Addresses #35205 

r? @jonathandturner

### CODE REVIEW

**Comment by athulappadan** [comment]
I would like to know what could be the reason why the checks failed.

**Comment by sanxiyn** [comment]
Rust forbids tab characters in source code.

**Comment by jonathandturner** [comment]
Thanks for the PR!

I was just about to start releasing some of the older codes so more people could volunteer, and you beat me to it :)

Like @sanxiyn pointed out, you need to pass a `tidy` check for a patch to be accepted.  You can run this by doing:

```
python src/bootstrap/bootstrap.py --stage 1 --step check-tidy
```

You'll also need to update the unit test to check for this new label.  By default, labels are not tested.  You need to add at least one label for all labels in a test to be tested.  You can read about how to do this in my blog post under Extra Credit: http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html

**Comment by athulappadan** [comment]
Thanks for the reply. Will fix it soon.

**Comment by athulappadan** [comment]
I am finding it difficult to understand how to give the proper labels in the test cases, even after going through the blog. Please suggest some useful tips/materials to understand the same.

@jonathandturner

**Comment by jonathandturner** [comment]
@athulappadan - you can look at some of the PRs that have already gone through to see how.  For example:

https://github.com/rust-lang/rust/pull/35961/files

Notice how the files in src/test/compile-fail get updated to include testing for the new labels?  For each PR that updates the errors, we want to check for those labels using this technique.

**Comment by athulappadan** [comment]
should be fixed by  #36009

**Pull request closed without merging**
