### PR TITLE
rustc: Stabilize `-C target-feature=+crt-static`

### LINKED ISSUE #37406: Tracking issue for customizing CRT linkage
Tracking issue for https://github.com/rust-lang/rfcs/pull/1721
- [x] - Add the `crt-static` target-feature
- [x] - Update Cargo to pass through target-feature to build scripts - https://github.com/rust-lang/cargo/pull/3243
- [x] - Implement "lazy link attributes" and implement in a gated fashion in liblibc.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit stabilizes the `crt-static` feature accepted by the compiler. Note
that this does not stabilize the `#[cfg]` attribute for `crt-static` as
that's going to be covered by #29717. This only stabilizes a few small pieces:

* The `crt-static` feature as accepted by the `-C target-feature` flag, and its
  connection with the platform-specific definition of `crt-static`.
* The semantics of `--print cfg` printing out activated `crt-static` feature, if
  available.

This should be enough to get the benefits of `crt-static` on stable Rust with
MSVC and with musl, but sidsteps the issue of stabilizing #29717 first.

Closes #37406

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @rust-lang/tools

**Comment by alexcrichton** [comment]
ping @japaric for reviewing, or would you prefer to r? somone else?

**Comment by japaric** [comment]
Sorry for the delay @alexcrichton. LGTM

@bors r+

**Pull request merged**
