### PR TITLE
rustbuild: don't require network for vendoring libtest

### LINKED ISSUE #79218: x.py dist shouldn’t require network access
Since #78790 we run cargo vendor unconditionally to vendor libtest in libstd.
We should either pass it '--offline' or add a way to conditionally do so to avoid using network when unnecessary

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #79218

### CODE REVIEW

**Comment by Keruspe** [comment]
Hmm, it seems --offline isn't actually offline :(

**Review by Wangtt185 — APPROVED** [review]

**Comment by Keruspe** [comment]
I have a better fix currently testing, as `--offline` isn't offline at all, still tries to sync crate.io

**Comment by Keruspe** [comment]
So, trying with `--locked` made the actual error pop up.

`cargo vendor --offline` doesn't help as it's not `cargo vendor` that is at fault. it's the `Cargo.lock` generation.

**Comment by Keruspe** [comment]
I'll reopen another PR once I actually get a working solution.

**Pull request closed without merging**
