### PR TITLE
rustdoc: refactor how passes are structured, and turn intra-doc-link collection into a pass

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
This builds on https://github.com/rust-lang/rust/pull/52751 and should not be merged until that finally finishes the bors queue

Part 2 of my passes refactor. This introduces the concept of an "early pass", which is run right before exiting the compiler context. This is important for passes that may want to ask the compiler about things. For example, i took out the intra-doc-link collection and turned it into a early pass. I also made the `strip-hidden`, `strip-private` and `strip-priv-imports` passes occur as early passes, so that intra-doc-link collection wouldn't run on docs that weren't getting printed.

Fixes https://github.com/rust-lang/rust/issues/51684, technically https://github.com/rust-lang/rust/issues/51468 too but that version of `h2` hits a legit intra-link error after that `>_>`

r? @rust-lang/rustdoc

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
An analysis of the bug that caused `cfg-if` and `bytes` to break a bunch of crates once we turned resolution errors into a proper lint:

`cfg-if` v0.1.3 has the following at the top of its crate docs:

```rust
//! A macro for defining #[cfg] if-else statements.
```

`bytes` v0.4.8 has the following in its crate docs:

```rust
//! A `Bytes` handle can be created directly from an existing byte store (such as &[u8]
//! or Vec<u8>), but usually a `BytesMut` is used first and written to. For
//! example:
```

When rustdoc processes a crate, it currently processes intra-doc-links as soon as the item is "cleaned". This is fairly early in the process, and occurs before any decision of whether to show a given item's documentation has been made. (Sure, we have a sense of whether it's in a public module, but not whether it's been exported somewhere that *is* public.) Furthermore, whenever it finds a problem resolving a link, it reports an error immediately, again ignoring whether that item is relevant for the current doc run.

Generally, whenever we encounter an external item, we only import its definition and attributes once we know we're going to display it. Either it's being used in a `pub use` in a public module, or someone put a `#[doc(inline)]` on it. However, for `extern crate` statements, we process their attributes just like it were a struct or function. This is a problem only because rustc loads all the *inner* attributes of a crate and throws them in alongside the attributes tagged onto the `extern crate` statement. Including their docs.

Which brings us back to `cfg-if` and `bytes`. Whenever some project used either of those crates, those links would be treated as local (despite not being written locally) and the error would be reported. Combine this with crates that use `#![deny(warnings)]` and you have the error that brought down `h2` and a few more crates.

My original reading of the issue is still valid, though, even if it's not the bug that created the issue. The other test i added also demonstrates this. A private item with a bad link target on it will currently report an error, despite not appearing in the documentation to create a broken link.

**Comment by QuietMisdreavus** [comment]
Now that https://github.com/rust-lang/rust/pull/52751 is landed, i've rebased atop master so that commit doesn't show up in this one.

**Comment by GuillaumeGomez** [comment]
Then let's get it in!

@bors: r+

**Comment by QuietMisdreavus** [comment]
Rebased.

**Comment by QuietMisdreavus** [comment]
@bors p=1

It seems that any time someone touches the current intra-doc links functionality, this PR gets a merge conflict because of how it's moving the code around. I just had to rebase again.

**Comment by QuietMisdreavus** [comment]
```
------------------------------------------
stderr:
------------------------------------------
error: Unrecognized option: 'invalid-arg-foo'
error: kaboom
  --> compile-error.rs:12:5
   |
12 |     compile_error!("kaboom");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
error: kaboom
  --> compile-error.rs:12:5
   |
12 |     compile_error!("kaboom");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
thread 'main' panicked at 'encountered error with `-Z treat_err_as_bug', librustc_errors\lib.rs:478:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.30.0-dev running on x86_64-pc-windows-msvc
note: compiler flags: -Z treat-err-as-bug
error: Unrecognized option: 'invalid-arg-foo'
error: kaboom
  --> compile-error.rs:12:5
   |
12 |     compile_error!("kaboom");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
make: *** [Makefile:11: all] Error 1
------------------------------------------
thread '[run-make] run-make-fulldeps\exit-code' panicked at 'explicit panic', tools\compiletest\src\runtest.rs:3149:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    [run-make] run-make-fulldeps\exit-code
test result: FAILED. 187 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
```

...did i mess with rustdoc's exit code somehow? was that modified in the last week and i somehow missed it in my rebases?

**Comment by QuietMisdreavus** [comment]
Ohhhh, i see it now. The `run-make-fulldeps/exit-code` test tries to document a crate with this, so that it will exit with an error:

```rust
#![deny(intra_doc_link_resolution_failure)]

/// [intradoc::failure]
fn main() {
    println!("Hello, world!");
}
```

However, now that we're not running docs for private items, the lint that *was* being emitted there is no longer being emitted. I'll update the test.

**Comment by QuietMisdreavus** [comment]
```
Broadcast message from root@travis-job-d3ffdbb6-fb99-47ea-a99b-4def481baca7

	(unknown) at 4:28 ...




The system is going down for power off NOW!

[01:06:20] 
[01:06:20] Session terminated, terminating shell...make: *** wait: No child processes.  Stop.
[01:06:20] make: *** Waiting for unfinished jobs....
[01:06:20] make: *** wait: No child processes.  Stop.
[01:06:20]  ...terminated.
```

I'm restarting the travis build.

**Comment by QuietMisdreavus** [comment]
Travis is green, so let's get this rolling again...

@bors r=GuillaumeGomez

**Pull request merged**
