### PR TITLE
[9/n] rustc: move type information out of AdtDef and TraitDef.

### PR DESCRIPTION
**Pull request by eddyb**
_This is part of a series ([prev](https://github.com/rust-lang/rust/pull/37688) | [next](https://github.com/rust-lang/rust/pull/38449)) of patches designed to rework rustc into an out-of-order on-demand pipeline model for both better feature support (e.g. [MIR-based](https://github.com/solson/miri) early constant evaluation) and incremental execution of compiler passes (e.g. type-checking), with beneficial consequences to IDE support as well.
If any motivation is unclear, please ask for additional PR description clarifications or code comments._

<hr>

Both `AdtDef` and `TraitDef` contained type information (field types, generics and predicates) which was required to create them, preventing their use before that type information exists, or in the case of field types, *mutation* was required, leading to a variance-magicking implementation of `ivar`s.

This PR takes that information out and the resulting cleaner setup could even eventually end up merged with HIR, because, just like `AssociatedItem` before it, there's no dependency on types anymore.
(With one exception, variant discriminants should probably be moved into their own map later.)

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by michaelwoerister** [comment]
It's so nice to see these refactorings `:)`

**Pull request merged**
