### PR TITLE
Swap TargetOptions::linker_is_gnu default from false to true and update targets as appropriate.

### LINKED ISSUE #85519: 28x binary size regression in recent nightly
There seems to be a significant regression in binary size in the most recent nightly:

nightly-2021-05-19

```
$ size target/thumbv6m-none-eabi/debug/hello
   text	   data	    bss	    dec	    hex	filename
   6056	     48	   1032	   7136	   1be0	target/thumbv6m-none-eabi/debug/hello
```

nightly-2021-05-20

```
$ size target/thumbv6m-none-eabi/debug/hello
   text	   data	    bss	    dec	    hex	filename
 201372	     48	   1032	 202452	  316d4	target/thumbv6m-none-eabi/debug/hello
```

Steps to reproduce:

* Clone https://github.com/jonas-schievink/size-regression
* Install `thumbv6m-none-eabi` target
* Run `cargo build`
* `size target/thumbv6m-none-eabi/debug/hello`

Commits in that range: https://github.com/rust-lang/rust/compare/4e3e6db01...f94942d84

https://github.com/rust-lang/rust/pull/85274 looks suspicious (cc @luqmana)

### PR DESCRIPTION
**Pull request by luqmana**
#85274 gated the `--gc-sections` flag on targets that specified `linker_is_gnu` to stop us from passing it to incompatible linkers. But that had the unintended effect of the flag no longer being passed on targets for which it is valid and hence caused a regression in binary size. Given that most `ld`-style linkers are GNU compatible, this change flips our default for `linker_is_gnu` from false to true. That also means updating the targets that relied on the previous default:
* Apple
* Illumos
* L4Re (not sure about this one)
* MSVC
* NvtPtx
* Solaris

Fixes #85519

### CODE REVIEW

**Comment by petrochenkov** [comment]
Could you also remove all the `linker_is_gnu: true`s from the specs, since they are now inherited from the default?

**Comment by jamesmunns** [comment]
Thanks @luqmana!

**Comment by petrochenkov** [comment]
One more regression from this - https://github.com/rust-lang/rust/issues/85948.

**Pull request merged**
