### PR TITLE
implement RFC amendment 1462 (add `[` to FOLLOW(ty))

### PR DESCRIPTION
**Pull request by durka**
cc #31135 rust-lang/rfcs#1462 #30923 @retep998 
r? @pnkfelix

### CODE REVIEW

**Comment by durka** [comment]
@pnkfelix so it is correct to modify FOLLOW(path) as well? I wasn't clear on that from the RFC.

**Comment by pnkfelix** [comment]
@durka oh wait, I overlooked that.

@bors r-

**Comment by pnkfelix** [comment]
(man that is embarrassing, given that its pretty explciitly pointed out...)

**Comment by pnkfelix** [comment]
( the RFC as written does says FOLLOW(path) = FOLLOW(ty); I need to double check whether that still makes sense in this context.  it probably does, though, to be honest; I just need to double-check about the ramifications...)

**Comment by pnkfelix** [comment]
Actually thinking on it further, I can't see how it could be wrong to put `[` into FOLLOW of path.  We aren't going to add it to the grammar for path expressions. (Especially since it already has a role in `expr ` grammar)

**Comment by durka** [comment]
urgh, I forgot to update the Book.

**Pull request merged**
