### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #120077 (Add Set entry API )
 - #132144 (Arbitrary self types v2: (unused) Receiver trait)
 - #132297 (Document some `check_expr` methods, and other misc `hir_typeck` tweaks)
 - #132820 (Add a default implementation for CodegenBackend::link)
 - #132881 (triagebot: Autolabel rustdoc book)
 - #132912 (Simplify some places that deal with generic parameter defaults)
 - #132916 (Unvacation fmease)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=120077,132144,132297,132820,132881,132912,132916)

### CODE REVIEW

**Comment by workingjubilee** [comment]
@rust-timer build 7081e9bf2e1a28762c54e0935de652cf2666f37d

**Comment by lqd** [comment]
@rust-timer build 581afa08cc53466a5d7a06d8c6793a9acdfe2f0a

**Comment by lqd** [comment]
Most regressions are in doc builds, and these feel like because of the stdlib's docs once again. 

It's evidently not the Set entry API so maybe the Receiver is "to blame".

@rust-timer build ed4c1069f638cdfea1d0049363684c5d594c3af2

**Comment by pnkfelix** [comment]
To my eye it looks like @lqd 's hypothesis is correct and PR #132144 is the root cause of the primary doc regressions.

**Pull request merged**
