### PR TITLE
Upgrade env_logger

### PR DESCRIPTION
**Pull request by sfackler**
This restores module names to the logging output

### CODE REVIEW

**Comment by sfackler** [comment]
cc @nikomatsakis 

r? @alexcrichton

**Comment by alexcrichton** [comment]
@KodrAus [mentioned](https://github.com/rust-lang/rust/pull/47161#issuecomment-358105849) that `env_logger` is close to an 0.5 release (like in the next day or two), so r=me if we hold out for that and then update here.

**Comment by kennytm** [comment]
`env_logger 0.5.0` has been released. https://crates.io/crates/env_logger

**Comment by nikomatsakis** [comment]
my hero

**Comment by sfackler** [comment]
Updated!

**Comment by alexcrichton** [comment]
Urgh. By pulling in winapi 0.3 this'll be blocked on https://github.com/rust-lang/rust/pull/47280. I wonder though if that could be avoided for now?

**Comment by kennytm** [comment]
I think the winapi 0.3 problem won't affect this PR since cargo is not updated.

The winapi dependency chain is:

* env_logger 0.5.0 ← chrono 0.4.0 ← time 0.1.39 ← winapi 0.3.3

We could see if using an earlier version of `time` is possible...

**Comment by alexcrichton** [comment]
@kennytm unfortunately it was a problem if winapi is *anywhere* in the crate dependency graph, not just as a direct dependency :(

**Comment by sfackler** [comment]
We could manually downgrade time to a version that pulled in winapi 0.2. It might be a bit fragile to maintain though.

**Comment by kennytm** [comment]
@alexcrichton  Oh that's bad :( 

So we need to stick a `time = "0.1.38"` constraint somewhere, or is there any command to force the generated Cargo.lock to choose `time = "0.1.38"`?

**Comment by kennytm** [comment]
@sfackler It is just a temporary measure, after #47280 there should be no problem using `winapi 0.3`

**Comment by alexcrichton** [comment]
@sfackler yeah that's fine for now, this is just a temporary problem until https://github.com/rust-lang/rust/pull/47280 lands which is for sure to happen, I'd just want to uncouple these two changes for now.

**Comment by alexcrichton** [comment]
@kennytm we could have a constraint or just use `cargo update -p time --precise 0.1.38`

**Comment by sfackler** [comment]
Updated.

(If you find yourself needing to do this again for whatever reason, the magic phrase is `cargo update -p time --precise 0.1.38`)

**Comment by kennytm** [comment]
@bors r-

`run-pass/rustc-rust-log.rs` ICE'd. Log: https://travis-ci.org/rust-lang/rust/builds/329994627

<details>

```
[00:53:57] ---- [run-pass] run-pass/rustc-rust-log.rs stdout ----
[00:53:57] 	
[00:53:57] error: compilation failed!
[00:53:57] status: exit code: 101
[00:53:57] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass/rustc-rust-log.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/rustc-rust-log.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/rustc-rust-log.stage2-x86_64-unknown-linux-gnu.aux"
[00:53:57] stdout:
[00:53:57] ------------------------------------------
[00:53:57] 
[00:53:57] ------------------------------------------
[00:53:57] stderr:
[00:53:57] ------------------------------------------
<logs snipped>
[00:53:57] error: internal compiler error: unexpected panic
[00:53:57] 
[00:53:57] note: the compiler unexpectedly panicked. this is a bug.
[00:53:57] 
[00:53:57] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:53:57] 
[00:53:57] note: rustc 1.25.0-dev running on x86_64-unknown-linux-gnu
[00:53:57] 
[00:53:57] thread 'rustc' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:916:5
[00:53:57] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:53:57] 
[00:53:57] 
[00:53:57] ------------------------------------------
[00:53:57] 
[00:53:57] thread '[run-pass] run-pass/rustc-rust-log.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2884:9
[00:53:57] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:53:57] 
[00:53:57] 
[00:53:57] failures:
[00:53:57]     [run-pass] run-pass/rustc-rust-log.rs
[00:53:57] 
[00:53:57] test result: FAILED. 2875 passed; 1 failed; 16 ignored; 0 measured; 0 filtered out
```

**Comment by alexcrichton** [comment]
I've opened https://github.com/sebasmagri/env_logger/pull/57 to fix that

**Comment by alexcrichton** [comment]
@sfackler mind updating to 0.5.1 so we can try again?

**Comment by kennytm** [comment]
Since #47280 landed we could just update all the things!

**Comment by kennytm** [comment]
@bors r-

This PR brings in `chrono 0.4.0` as a dependency. When documenting this package ([the `strftime` module](https://docs.rs/chrono/0.4.0/chrono/format/strftime/index.html)) as part of the compiler, it was found to contain rendering difference between pulldown and hoedown.

I believe this is because hoedown/pulldown doesn't format to the same HTML.

<details>

```
[01:43:21] WARNING: documentation for this crate may be rendered differently using the new Pulldown renderer.
[01:43:21]     See https://github.com/rust-lang/rust/issues/44229 for details.
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[0]/td[1] One element is missing: expected: `strong`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[0] Unexpected element `td`: found: `<td><strong>DATE SPECIFIERS:</strong></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[4] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[4] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[9] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[9] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[12] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[12] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[17] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[17] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[20] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[20] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[24] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[24] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[26] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[26] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[31] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[31] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[32]/td[1] One element is missing: expected: `strong`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[32] Unexpected element `td`: found: `<td><strong>TIME SPECIFIERS:</strong></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[37] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[37] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[40] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[40] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[48] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[48] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[53] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[53] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[54]/td[1] One element is missing: expected: `strong`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[54] Unexpected element `td`: found: `<td><strong>TIME ZONE SPECIFIERS:</strong></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[58] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[58] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[59]/td[1] One element is missing: expected: `strong`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[59] Unexpected element `td`: found: `<td><strong>DATE &amp; TIME SPECIFIERS:</strong></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[62] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[62] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[64] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[64] Unexpected element `td`: found: `<td></td>`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[65]/td[1] One element is missing: expected: `strong`
[01:43:21] WARNING: rendering difference in ``strftime`/`strptime`-inspired date and time formatting syntax.`
[01:43:21]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.0/src/format/strftime.rs:4:0
[01:43:21]     /html[0]/body[0]/table[0]/tbody[0]/tr[65] Unexpected element `td`: found: `<td><strong>SPECIAL SPECIFIERS:</strong></td>`
[01:43:21] Aborting with 1 rendering differences
[01:43:21] [m[m[31m[1merror:[m Could not document `chrono`.
```

</details>

cc @GuillaumeGomez. I think we should fix pulldown or hoedown, instead of requiring chrono to update the docs.

**Comment by kennytm** [comment]
Now blocked by either:

* `chrono 0.4.1` gets released to include chronotope/chrono#211, or
* we ignore the markdown warnings when documenting the compiler.

**Comment by kennytm** [comment]
`env_logger` has been updated to 0.5.3 in #47729, so this PR should not be needed anymore. Closing.

**Comment by alexcrichton** [comment]
@kennytm oh note that the update there was just for Cargo not for rustc, so we may still need this for rustc itself?

**Comment by kennytm** [comment]
Err sorry @alexcrichton you're right, missed the rest of the changes

**Comment by alexcrichton** [comment]
I'm gonna close this in favor of https://github.com/rust-lang/rust/pull/48642 in the hopes that it gets through

**Pull request closed without merging**
