### PR TITLE
libtest: Fix padding of benchmarks run as tests

### LINKED ISSUE #104092: Strange indentation in libtest output
libtest output recently started indenting *some* but not all test results:
```
$./x.py test library/alloc --stage 0 --test-args "--format pretty" --no-doc
running 373 tests
test raw_vec::tests::allocator_param ... ok
test raw_vec::tests::reserve_does_not_overallocate ... ok
test raw_vec::tests::zst ... ok
test alloc::tests::allocate_zeroed ... ignored
test raw_vec::tests::zst_reserve_panic - should panic ... ok
test raw_vec::tests::zst_reserve_exact_panic - should panic ... ok
test alloc::tests::alloc_owned_small                         ... ok   <!----- notice this one!
test collections::binary_heap::tests::test_iter_rev_cloned_collect ... ok
[...]
test collections::linked_list::tests::test_drop ... ok
test collections::linked_list::tests::test_drop_panic ... ok
test collections::vec_deque::tests::bench_push_front_100     ... ok  <!---- and these!
test collections::vec_deque::tests::bench_push_back_100      ... ok
test collections::vec_deque::tests::bench_pop_back_100       ... ok
test collections::vec_deque::tests::bench_pop_front_100      ... ok
test collections::vec_deque::tests::test_swap_front_back_remove ... ok
test collections::vec_deque::tests::test_insert ... ok
test collections::vec_deque::tests::test_get ... ok
test collections::vec_deque::tests::test_get_mut ... ok
test collections::vec_deque::tests::bench_retain_whole_10000 ... ok
```
Seems like benchmarks are indented but regular tests are not.

### PR DESCRIPTION
**Pull request by Enselic**
### Summary

The first commit adds regression tests for libtest padding.

The second commit fixes padding for benches run as tests and updates the blessed output of the regression tests to make it clear what effect the fix has on padding.

Closes #104092 which is **E-help-wanted** and **regression-from-stable-to-stable**

### More details

Before this fix we applied padding _before_ manually doing what `convert_benchmarks_to_tests()` does which affects padding calculations. Instead use `convert_benchmarks_to_tests()` first if applicable and then apply padding afterwards so it becomes correct. 

Benches should only be padded when run as benches to make it easy to compare the benchmark numbers. Not when run as tests.

r? @ghost until CI passes.

### CODE REVIEW

**Comment by saethlin** [comment]
This is good work and very well-tested, but I'm not a member of the library team. I'm asking on Zulip about who should be approving this.

**Comment by thomcc** [comment]
Seems good to me! Thanks!

@bors r+

**Comment by Enselic** [comment]
I had to replace `\+` with `\{1,\}` in the normalization regex to make it work with both macOS/BSD sed and Linux/GNU sed.

@thomcc Can you r+ again please? Thanks! [Diff from what you already approved.](https://github.com/rust-lang/rust/compare/809b2ad47f68c1e30c4befff26e33c1c34ddd9f1..12e6bcfcabee7bfa9130bb5fcd4b8ab23172b1ee)

**Comment by Enselic** [comment]
@thomcc Friendly ping in case you missed my first ping (the [diff](https://github.com/rust-lang/rust/compare/809b2ad47f68c1e30c4befff26e33c1c34ddd9f1..12e6bcfcabee7bfa9130bb5fcd4b8ab23172b1ee) from what you already approved is trivial).

**Comment by ChrisDenton** [comment]
I'm happy to approve the diff.

@bors r=thomcc,ChrisDenton

**Pull request merged**
