### PR TITLE
Implement placement-in protocol for `Vec`

### PR DESCRIPTION
**Pull request by aidanhs**
Follow-up of #32366 per comment at https://github.com/rust-lang/rust/issues/30172#issuecomment-268099009, updating to latest rust, leaving @apasel422 as author and putting myself as committer. 

I've removed the implementation of `push` in terms of place to make this PR more conservative.

### CODE REVIEW

**Comment by nagisa** [comment]
The implementation looks fine to me. We might want to return a `&mut T` from the expression (i.e. set type of InPlace::Owner to &mut T), though; see https://github.com/rust-lang/rfcs/issues/1821.

Otherwise its mostly for somebody from libs team to r+ it.

**Comment by aidanhs** [comment]
@nagisa ah thanks, I did wonder about that since returning a reference seems strictly more useful than not, but decided to follow in the footsteps of `push` and `LinkedList::back_place`. However, I've now updated the PR to return `&mut T` given the new information.

**Comment by aturon** [comment]
cc @rust-lang/libs

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Pull request merged**
