### PR TITLE
Reverts rust-lang/rust#117206

### PR DESCRIPTION
**Pull request by erickt**
cc @cjgillot @tmiasko

This revert is based on the following report of a regression caused by this [PR](https://github.com/rust-lang/rust/pull/117206):

https://github.com/rust-lang/rust/issues/121094

In accordance with the compiler team [revert policy], PRs that cause meaningful regressions should be reverted and re-landed once the regression has been fixed (and a regression test has been added, where appropriate). [revert policy]: https://forge.rust-lang.org/compiler/reviews.html#reverts

Fear not! Regressions happen. Please rest assured that this does not represent a negative judgment of your contribution or ability to contribute positively to Rust in the future. We simply want to prioritize keeping existing use cases working, and keep the compiler more stable for everyone.

r? compiler

### CODE REVIEW

**Comment by erickt** [comment]
r=me

**Comment by compiler-errors** [comment]
A fix PR has been r+'d, I'll close this

**Pull request closed without merging**
