### PR TITLE
Add flow-graph visualization (via graphviz) to rustc

### PR DESCRIPTION
**Pull request by pnkfelix**
Passing `--pretty=flowgraph` makes rustc print a control flow graph.

In practice, you will also need to pass the additional options:
- `-o <FILE>` to emit output to a `.dot` file for graphviz, and
- `--pretty-node=<ID>` to specify the node-id for the block you want to print.

(You can only print the flow-graph for a particular block in the AST.)

These changes do not generalize the rest of the pretty-printer to
support the `--pretty-node=<ID>` option for printing subtrees of the
AST, but that is obviously a potential future feature that we could
add on.  It is orthogonal to flow-graph printing, though.

### CODE REVIEW

**Comment by xftroxgpx** [comment]
Is there any way to see the whole(or even part, like OP says) AST via graphviz output with current rustc ?
`--pretty=flowgraph` doesn't seem available anymore
```
$ rustc --pretty=flowgraph -o graphviz.dot -Z unstable-options ./main.rs 
error: argument to `pretty` must be one of `normal`, `expanded`, `identified`, or `expanded,identified`; got flowgraph
rustc 1.32.0-nightly (04fdb44f5 2018-11-03)
binary: rustc
commit-hash: 04fdb44f5ccb6f909cf0f768781afa483e97097c
commit-date: 2018-11-03
host: x86_64-unknown-linux-gnu
release: 1.32.0-nightly
LLVM version: 8.0

```

**Comment by xftroxgpx** [comment]
Thanks @eddyb ! I found the MIR stuff you were referring to here: https://github.com/rust-lang/rust/blob/f45f52532a394d2d607fc5693364ad820049376d/src/test/ui/mir-dataflow/README.md#L29
eg.
```
#![feature(rustc_attrs)]                                                        
...
#[rustc_mir(borrowck_graphviz_postflow="/tmp/suffix.dot")]                      
fn main() {
```
And it works! But as you said, it's not the AST. Would love to see AST graph, if that exists.

**Comment by eddyb** [comment]
@xftroxgpx Do you want an AST CFG, or just an AST? Also, may I ask what for?
We're planning to gradually remove most of the semantic handling on ASTs, and ASTs (specifically, HIR, which is a slightly desugared and name-resolved AST) will primarily be used for type inference and lowering to MIR (once type-inferred).

**Comment by xftroxgpx** [comment]
@eddyb Ah, just for learning purposes only. I was hoping that I could see, in a graph-way, how rust sees my vars, loans and assignments, but looks like it's just a `Control-Flow Graph` instead :( (just as you said)

**Comment by eddyb** [comment]
@xftroxgpx Ah, for that, you can just look at the textual MIR format.
We have no graph generation, AFAIK, that links together all the places a name (of a variable, for example) shows up - that would amount to a dataflow graph, I believe.

Maybe we *should* do a mixed control-flow and data-flow graph? Or even run a VSDG building algorithm on the MIR to get a data-flow graph that describes side-effects as linear "data".

**Pull request closed without merging**
