### PR TITLE
Rollup of 17 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
- Successful merges: #48052, #48072, #48082, #48083, #48084, #48106, #48123, #48157, #48185, #48197, #48198, #48206, #48208, #48221, #48258, #48314, #48335
- Failed merges:

### CODE REVIEW

**Comment by eddyb** [comment]
Please take #48052 out of rollups (how can we streamline that?).

**Comment by Manishearth** [comment]
I have to do it manually. I hav ea script.

**Comment by Manishearth** [comment]
@bors retry

appveyor reached time limit :|

**Comment by Manishearth** [comment]
wtf

**Comment by Manishearth** [comment]
@bors retry

time limit

**Comment by Manishearth** [comment]
(eddyb's MIR PR is not in the rollup so I'll let that land first)

**Comment by Manishearth** [comment]
Hmm. Perhaps one of these pull requests negatively affects cycle times? Better to not roll up in that case :|

Either that or we're just hitting the limits really often.

**Pull request closed without merging**
