### PR TITLE
Compile core crates before std

### PR DESCRIPTION
**Pull request by est31**
Right now, many crates used by `std` need to manually specify dependencies onto crates like `core`, as they need to be built after core has been built. For some crates from external sources, we provide our own Cargo.toml files so that we can write out that dependency (and other, rustbuild specific things).

This PR splits up the std compilation step in rustbuild into two semi-steps. One which compiles three `#![no_std]` crates `libcore`, `compiler_builtins`, and `libstd_unicode`, and a second step which compiles the remainder.

Thanks to this, it alleviates the need to specify dependencies onto those crates, and allows libstd to depend on `#![no_std]` crates from crates.io without modification.

Needed by #51408

r? @Mark-Simulacrum

### CODE REVIEW

**Review by Mark-Simulacrum — COMMENTED** [review]
Other than one nit I think this looks good (presuming it works).

**Comment by est31** [comment]
Hmmm this seems to break `x.py check`...

**Comment by est31** [comment]
So... it seems to fail building rustdoc. Lemme try finding a fix.

**Comment by Mark-Simulacrum** [comment]
We need to add `CoreLink` to the `force_use_stage1`  if for `Std`, otherwise core and related libraries aren't linked in to the stage2 sysroot.

**Comment by est31** [comment]
rebased. re-r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
You'll want to update https://github.com/rust-lang/rust/pull/51440/files#diff-e2a5ddcb8c7e32ab05929b0e42ff4719L30 to add `.path("src/libcore").path("src/liballoc").path("src/libcompiler-builtins")` or something like that...

**Comment by pietroalbini** [comment]
Ping from triage @est31! It's been a while since we heard from you on this, will you have time to work on this again?

**Comment by kennytm** [comment]
@bors r-

Wrongly requeued

**Comment by est31** [comment]
The period of my contributions to Rust upstream [has reached an end](https://gist.github.com/est31/de7f851ec80576d5cf7bccac3962aed7). Thus I'm unable to continue my work on this. I still think something like this is a great addition. I urge anyone interested in this change to adopt and continue it from here on. Thanks.

**Pull request closed without merging**
