### PR TITLE
update Miri

### PR DESCRIPTION
**Pull request by RalfJung**
I had to use a hacked version of josh to create this, so let's be careful with merging this and maybe wait a bit to see if the josh issue becomes more clear. But the history looks good to me, we are not adding duplicates of rustc commits that were previously mirrored to Miri.

Also I want to add some cross-testing of Miri in x.py.

### CODE REVIEW

**Comment by RalfJung** [comment]
There is something odd going on in 96737e3a52306192c23bf30b4108c568ec1f7701, which strangely has bf14e3196b4f340b5c2a57b902b01e07a7d7c3dc as parent even though that parent is much younger than the child. But these changes happened independently so josh really has no way of knowing which way the history would be, and I guess it doesn't use the time as a heuristic. Doesn't seem like too big a deal, as long as re-extracting the history works as it should (which I still need to test).

**Comment by RalfJung** [comment]
> as long as re-extracting the history works as it should (which I still need to test)

I confirmed that this works.

**Comment by RalfJung** [comment]
This now also does some cross-testing of Windows/Apple targets in Miri, which would have caught some of the recent breakage. (We still don't run the cargo-miri tests here though, so if something breaks *just* the test harness, bors CI will not notice. That's pretty rare though, so I'd say it's fine and we can reconsider if/when that actually occurs in practice.)

**Comment by RalfJung** [comment]
Actually, turns out a basic smoke test invocation of `cargo miri test` isn't that hard, so I added that, too. This is not quite as thorough as what Miri CI does, but it *will* notice when the test harness just stops working entirely (as it recently did on Windows targets).

**Comment by RalfJung** [comment]
I managed to reproduce the sync problem in a [small testcase for the josh devs](https://github.com/josh-project/josh/pull/965#issuecomment-1288146683), so looks like this is not some obscure side-effect of a bad sync, just a pattern josh does not know how to handle currently.

**Comment by oli-obk** [comment]
r=me with CI passing

**Comment by RalfJung** [comment]
Ah I need to re-sync due to more Windows changes in is_terminal.

**Comment by RalfJung** [comment]
That is some very strange log
```
     Running `build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo-miri.exe miri test --manifest-path D:\a\rust\rust\src/tools/miri/test-cargo-miri/Cargo.toml --target i686-pc-windows-msvc --tests --`
   Compiling byteorder v1.4.3
   Compiling exported_symbol_dep v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri\exported-symbol-dep)
   Compiling issue_rust_86261 v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri\issue-rust-86261)
   Compiling cargo-miri-test v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri)
   Compiling issue_1691 v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri\issue-1691)
   Compiling byteorder v0.5.3
   Compiling exported_symbol v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri\exported-symbol)
   Compiling issue_1567 v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri\issue-1567)
   Compiling cdylib v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri\cdylib)
   Compiling issue_1705 v0.1.0 (D:\a\rust\rust\src\tools\miri\test-cargo-miri\issue-1705)
    Finished test [unoptimized + debuginfo] target(s) in 1.30s
     Running unittests src\main.rs (build\x86_64-pc-windows-msvc\stage2-tools\miri\i686-pc-windows-msvc\debug\deps\cargo_miri_test-0f976196cd517b80.exe)

running 2 tests
test test::dev_dependency ... ok
test test::exported_symbol ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running tests\main.rs (build\x86_64-pc-windows-msvc\stage2-tools\miri\i686-pc-windows-msvc\debug\deps\main-991d0e7eee076530.exe)
imported main
     Running tests\test.rs (build\x86_64-pc-windows-msvc\stage2-tools\miri\i686-pc-windows-msvc\debug\deps\test-5a629d2bcf30ccfb.exe)

running 6 tests
test cargo_env ... ok
test deps ... ok
test do_panic - should panic ... ok
test does_not_work_on_miri ... ignored
test fail_index_check - should panic ... ok
test simple ... ok

test result: ok. 5 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out

[TIMING] test::Miri { stage: 2, host: x86_64-pc-windows-msvc, target: i686-pc-windows-msvc } -- 101.188
Build completed successfully in 0:01:46
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.12s
warning: the following packages contain code that will be rejected by a future version of Rust: ntapi v0.3.7
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 8`
thread 'main' panicked at '

couldn't find required command: "cc"

', sanity.rs:59:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
```
Which part of the build is trying to run `cc` here? This should just be doing `cargo miri test` and it works fine on Miri's CI...

The panic seems to come from bootstrap

https://github.com/rust-lang/rust/blob/fdb39551ddfb431ee1edb61731a68927a06649f7/src/bootstrap/sanity.rs#L59

but I don't know why.
Cc @jyn514

**Comment by RalfJung** [comment]
Oh, this is probably not from the `cargo miri test`, but from the next thing checktools does
```
python3 "$X_PY" test --stage 2 src/tools/miri --target aarch64-apple-darwin
```
Looks like some part of x.py decides that it makes no sense to run this command without `cc`. Sadly that heuristic is wrong, Miri tests work fine on any host and don't need such tools to be installed.

I think for now I will remove the apple part from CI here, that doesn't need to block the other parts of this PR.

**Comment by RalfJung** [comment]
Opened https://github.com/rust-lang/rust/issues/103519 to track the macOS testing.

@bors r=oli-obk

**Pull request merged**
