### PR TITLE
add a ui test for `.as_ref` suggestion

### LINKED ISSUE #90286: regression: rustc suggests `.as_ref()` at incorrect location and other spans have regressed
### Code

[Playground (regressed rustc version)](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=fb0cec09ebd743b2242ecb1168b9ca3e)

```rust
fn foo(opt: &Option<Box<i32>>) -> String {
    opt.map(|x| x.to_string()).unwrap_or_else(String::new)
}
```

### Output (stable 1.56.0, good)

```
error[E0507]: cannot move out of `*opt` which is behind a shared reference
 --> src/lib.rs:2:5
  |
2 |     opt.map(|x| x.to_string()).unwrap_or_else(String::new)
  |     ^^^ move occurs because `*opt` has type `Option<Box<i32>>`, which does not implement the `Copy` trait
  |
help: consider borrowing the `Option`'s content
  |
2 |     opt.as_ref().map(|x| x.to_string()).unwrap_or_else(String::new)
  |        +++++++++

For more information about this error, try `rustc --explain E0507`.
```

### Output (beta 1.57.0-beta.2, incorrect)

```
error[E0507]: cannot move out of `*opt` which is behind a shared reference
 --> src/lib.rs:2:5
  |
2 |     opt.map(|x| x.to_string()).unwrap_or_else(String::new)
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `*opt` has type `Option<Box<i32>>`, which does not implement the `Copy` trait
  |
help: consider borrowing the `Option`'s content
  |
2 |     opt.map(|x| x.to_string()).as_ref().unwrap_or_else(String::new)
  |                               +++++++++

For more information about this error, try `rustc --explain E0507`.
```

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Closes https://github.com/rust-lang/rust/issues/90286

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
Thanks! @bors r+ rollup

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
https://github.com/rust-lang/rust/runs/7939531718?check_suite_focus=true#step:25:1536
can you check if you can reproduce this? I don't understand why pre-merge ci does not catch that :/

**Comment by WaffleLapkin** [comment]
This was not caught by CI because the changes seem to have occurred after this PR 😄 
see https://github.com/rust-lang/rust/pull/100186 and specifically https://github.com/compiler-errors/rust/commit/e37565d2db8d7cf92a6d1df535343d4b2881fc35

**Comment by WaffleLapkin** [comment]
This suggestion already has tests, see https://github.com/rust-lang/rust/issues/90286#issuecomment-1222169459

**Pull request closed without merging**
