### PR TITLE
rustdoc: get back missing crate-name when --playground-url is used

### PR DESCRIPTION
**Pull request by liigo**
follow up PR #37763
r? @alexcrichton (since you r+ed to #37763 )

----

Edit: When `#![doc(html_playground_url="")]` is used, the current crate name is saved to `PLAYGROUND`, so rustdoc may generate `extern crate NAME;` into code snips automatically. But when `--playground-url` was introduced in PR #37763, I forgot saving crate name to `PLAYGROUND`. This PR fix that.

----

Update: 
- add test
- unstable `--playground-url`

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR, but could you describe what the bug is and how this is fixing it?

**Comment by liigo** [comment]
@alexcrichton I've updated the description of the PR. Thank you!

**Comment by ollie27** [comment]
My concerns from the previous PR still apply https://github.com/rust-lang/rust/pull/37763#pullrequestreview-8910183. At the very least this feature needs tests.

**Comment by liigo** [comment]
This pr simply fixes a bug found in previous pr.
I've tested by manual, and ensure it works well as before. But writing test harness code is difficult in this case IMHO.

**Comment by alexcrichton** [comment]
Yeah I do agree that if we're fixing bugs it's best if we have some tests for this. Could some tests be added to `src/test/rustdoc`?

**Comment by liigo** [comment]
Ok, I'll try to add some tests. Maybe need a little more time.

**Comment by ollie27** [comment]
@liigo you should be able to do something like https://github.com/rust-lang/rust/blob/master/src/test/rustdoc/playground.rs but with `// compile-flags: --playground-url=https://www.example.com/`.

@alexcrichton shouldn't new command line options for rustdoc at least start out as unstable?

**Comment by liigo** [comment]
Thank you!

**Comment by alexcrichton** [comment]
Ah yes actually I forgot that we had unstable options in rustdoc now. Can we make this an unstable option at the same time?

**Comment by liigo** [comment]
@alexcrichton Yes, Will do.

**Comment by liigo** [comment]
Done. r? @alexcrichton

**Comment by liigo** [comment]
updated to pass the tests

**Pull request merged**
