### PR TITLE
Rustdoc: Change all 'optflag' arguments to 'optflagmulti'

### PR DESCRIPTION
**Pull request by zachlute**
Because specifying these flags multiple times will never be discernibly different in functionality from specifying them a single time, there is no reason to fail and report an error to the user.

This might be a slightly controversial change. it's tough to say, but it's hard to imagine a case where somebody was depending on this behavior, and doing this seem actively better for the user.

This originally came up in discussion of a fix for  [Cargo #8373](https://github.com/rust-lang/cargo/issues/8373), in [Cargo PR #8422](https://github.com/rust-lang/cargo/pull/8422).

The issue is that Cargo will automatically add things like `--document-private-items` to binaries, because it's the only thing that makes sense there. Then some poor user comes along and adds `--document-private-items` to their `rustdoc` flags for the project and suddenly they're getting errors for specifying a flag twice and need to track down which targets to actually add it to without getting duplicates for reasons they won't understand without deep understanding of Cargo behavior.

We're apparently hesitant to inspect `rustdoc` flags provided by the user directly in Cargo, because they're supposed to be opaque, so looking to see if it's already provided before adding it is evidently a non-starter. In trying to resolve that, one suggestion I came up with was to just change `rustdoc` to support passing the flag multiple times, because the user's intent should be clear and it's not *really* an error, so maybe this is a case of 'be permissive in what you accept'.

This PR is an attempt to do that in a straightforward manner for purposes of discussion.

### CODE REVIEW

**Comment by jyn514** [comment]
I think this change is reasonable but it should also give a warning if the option was passed multiple times. That way people aren't confused that 'my private binary function shows up even without --document-private-items'.

**Comment by JohnCSimon** [comment]
ping from triage
@zachlute  - can you please address the merge conflicts?
thanks

**Comment by jyn514** [comment]
@johncsimon there's not much point fixing the conflicts until @rust-lang/rustdo

**Comment by zachlute** [comment]
Yeah, happy to clean this up and get it into mergeable shape provided there's consensus it would actually be merged. It was kind of a drive-by as a result of trying to fix a Cargo bug, so I'm hesitant to put much more work into it without some buy-in. :)

**Comment by JohnCSimon** [comment]
Ping from triage:
@zachlute - can you please update the status of this PR?
cc: @jyn514

**Comment by jyn514** [comment]
@JohnCSimon same status as last time, this is waiting on team and there's not much point fixing the conflicts until then.

**Comment by GuillaumeGomez** [comment]
I'm shared on this: wouldn't it be better instead to make the crate parsing the arguments warn in case a `optflag` is passed multiple times instead of fixing it on our side?

**Comment by Manishearth** [comment]
I'm not sure if warning is the right approach since it might not be possible to fix that warning, if the system is many-layered for example.

**Comment by jyn514** [comment]
Does this actually help with the original issue? When you set RUSTDOCFLAGS, does cargo pass those before or after it's own flags? If it passes them before, they'll just get silently overridden.

**Comment by Manishearth** [comment]
> Does this actually help with the original issue? When you set RUSTDOCFLAGS, does cargo pass those before or after it's own flags? If it passes them before, they'll just get silently overridden.

Does rustdoc have flags that overwrite each other?

**Comment by jyn514** [comment]
Yes, there can only be one --html-root-url per crate and only one --default-theme per invocation.

**Comment by jyn514** [comment]
I guess that doesn't matter for --document-private-items because it's strictly additive.

**Comment by zachlute** [comment]
Yeah, my understanding of all the changed items is that passing them twice could only ever mean "I wanted to enable this but accidentally did it twice, either myself or through layers of settings like cargo uses." It seemed safe to assume in that case that if you enabled it twice, you just meant to enable it, and we don't have to fail the call.

**Comment by zachlute** [comment]
@GuillaumeGomez may have a point though, that it makes more sense to fix it such that optflags treats this as a warning instead of an error. I'm not sure what the upstream implications are and if anything is depending on that being an error elsewhere. This is a pretty manageable set of flags where we can individually assess each and decide which are safe to allow passing multiple times.

That said, for the original issue, while it would help it would just kind of be annoying, because there would be no way for me to get rid of the warning other than to NOT pass the flag myself, since `cargo` is helpfully passing it for me only on some items. So my build wouldn't fail, but I would have a warning I couldn't meaningfully fix.

**Comment by GuillaumeGomez** [comment]
@zachlute If it's an issue to set it as the default handling, it can be optional to say "treat this as a warning" when setting up optflag.

**Comment by Manishearth** [comment]
Yeah I think we should error (not even warn) in cases of conflict, but if you set the same root url twice (or whatever) it should be fine.

At _least_ for flags like doc-private we should allow multiple

**Comment by jyn514** [comment]
I agree we should accept this silently (without warning). @zachlute are you up for implementing that? Sorry for the extended delay, I think this just needs a rebase :)

**Comment by zachlute** [comment]
Yeah, I can take a look at getting this cleaned up this weekend.

**Comment by zachlute** [comment]
Ugh, as usual, any time I need to do anything complicated with git I screw it up. Somehow in rebasing this I've ended up with a bunch of other random changes included in the list of changes in this PR? Sigh. I'll just create a new branch with the change, which is what I always end up doing anyway because git seems designed to make me look dumb regularly.

**Comment by zachlute** [comment]
Please look at PR #87039 instead of this one for the up-to-date change. Sorry for the inconvenience.

**Comment by zachlute** [comment]
Apologies for all the jumping around here. I had a smarter friend help me do this again and I believe the change should now be correct.

**Comment by ehuss** [comment]
@jyn514 Just FYI, the bors squash option is somewhat broken in that it strips authorship of the git commit (https://github.com/rust-lang/homu/issues/136) and can prevent GitHub from realizing the PR is merged. Not sure if most people care, but I think it should probably be avoided until it is fixed.  I also haven't looked, but I'm uncertain how it interacts with rollups.

**Pull request merged**
