### PR TITLE
Prepare beta 1.55.0

### PR DESCRIPTION
**Pull request by emilyalbini**
Included backports:

* https://github.com/rust-lang/rust/pull/86696
* https://github.com/rust-lang/rust/pull/87390 (squashed)

Reverted:

* #86623

cc @rust-lang/release @Mark-Simulacrum

### CODE REVIEW

**Comment by pietroalbini** [comment]
Also included backports.

@bors r+

**Comment by fee1-dead** [comment]
That spurious CI error looks exactly the same as [this](https://github.com/rust-lang/rust/runs/3085893360). See [the PR](https://github.com/rust-lang/rust/pull/87179) for more info.

**Comment by pietroalbini** [comment]
Hmm, that seems like it resolved itself in that PR? Let's try again.

@bors retry

**Comment by fee1-dead** [comment]
> Hmm, that seems like it resolved itself in that PR? Let's try again.
> 
I don't think so, because the PR's CI keeps failing, but bors' tests pass. For this PR it's the reverse I guess. I think you should just open another PR and see if it will resolve.

**Comment by pietroalbini** [comment]
Reverted #86623, which should be the cause of this issue.

@bors r+ p=1000 rollup=never

**Comment by pietroalbini** [comment]
The `x86_64-gnu-stable` job can't work on beta. Added the last commit to only run that job on nightly. r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
@bors r+

Please make sure that commit lands on master as well. However, we might want to explore making a different fix, that lets us test the stable branch while having dev: 1 -- I'm worried about beta->stable promotion failing if we don't have that.

**Comment by pietroalbini** [comment]
Opened the backport PR in https://github.com/rust-lang/rust/pull/87550.

**Pull request merged**
