### PR TITLE
Add support for PowerPC64 on FreeBSD

### PR DESCRIPTION
**Pull request by lenoil98**
These are changes to add support for powerpc64 on FreeBSD.

[patch-ppc64.txt](https://github.com/rust-lang/rust/files/2756610/patch-ppc64.txt)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
This should target `master`, not `stable`

**Comment by lenoil98** [comment]
my bad! Should've been against master.  Please change. tks!

**Comment by estebank** [comment]
> I don't think this can be changed after the PR is opened. Try opening a new one with the right branches.

It can. You need to `git rebase master` and once you're done with the rebase, `git push <your_origin> -f`.

**Comment by jonas-schievink** [comment]
@estebank I think that does something different - the problem here is that the PRs *target branch* was set to `stable` instead of `master`, which you can only configure through the GitHub UI

Oh and apparently the source branch is set to *this repos* `master` instead of the repo where the code to be merged is located.

**Comment by estebank** [comment]
[You can change the target branch](https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/), but for some reason here I can't change it to master, the list of commits is different to what I'd expect.

**Comment by lenoil98** [comment]
It's not letting me select master.  I'll close the PR and resubmit.

**Pull request closed without merging**
