### PR TITLE
update mem::discriminant test to use assert_eq and assert_ne over comparison operators

### PR DESCRIPTION
**Pull request by andrewbanchich**
Use assert_eq and assert_ne over comparison operators.

### CODE REVIEW

**Comment by joshtriplett** [comment]
The change looks reasonable. However, could you please use a more descriptive subject than "update test"? Don't leave all the details to the body of the commit message.

**Comment by andrewbanchich** [comment]
@joshtriplett Sure, all set! Let me know if you need anything else.

r? @joshtriplett
@bors r+ rollup

**Comment by andrewbanchich** [comment]
Whoops, so you meant I should add `r? @joshtriplett` and then you will `@bors r+ rollup` after you review? First time contributing to docs...

**Comment by Centril** [comment]
@andrewbanchich r=me generally means that someone with approval rights can do r=reviewer but if you don't have approval rights then you'll have to wait.

**Pull request merged**
