### PR TITLE
Added SHA512, SM3, SM4 target-features and `sha512_sm_x86` feature gate

### PR DESCRIPTION
**Pull request by sayantn**
This is an effort towards #126624. This adds support for these 3 target-features and introduces the feature flag `sha512_sm_x86`, which would gate these target-features and the yet-to-be-implemented detection and intrinsics in stdarch.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Please rebase.

**Comment by sayantn** [comment]
This feature is problematic because AArch64 also has a feature named `sm4`, and as the new feature will be unstable, we need to add `feature(sha512_sm_x86)` in core_arch first, but will also fail compiling stage0 if we don't add some `#[unstable(feature = "sha512_sm_x86"]` attributes in core_arch.  So we need to implement the runtime detection for these first, and then add these to rustc. I will send a PR to stdarch

**Comment by sayantn** [comment]
This needs to wait till the next beta release, as the stdarch submodule update uses the new VEX variants of AVX512, and stage0 is a beta toolchain

**Comment by sayantn** [comment]
This will wait until #117468 updates the stdarch submodule and #127209 adds the XOP target-feature, as that would generate another merge conflict

**Comment by michaelwoerister** [comment]
@Amanieu, would you be able to review this?

**Comment by sayantn** [comment]
This PR no longer depends on an stdarch bump

**Comment by Amanieu** [comment]
r=me once CI passes

**Pull request merged**
