### PR TITLE
conditional fallback for the `!` type

### LINKED ISSUE #66173: create a lint for tracking "tainted" fallback around abrupt expressions and `!` type
As part of https://github.com/rust-lang/rust/issues/65992, we want to create a lint that warns about cases where changing the fallback for type variables from `()` to `!` will create problems. This issue is tracking that implementation work.

Edit 2020-10-05: stream for work on this, https://rust-lang.zulipchat.com/#narrow/stream/259160-t-lang.2Fproject-never-type

## Current status and next steps

* [x] prototype lint and verify that it works on the example test cases
* [x] turn the lint to deny by default and make sure libstd builds
* [ ] create a helper function for adding to `dead_nodes` that explains what is going on, document that this function is invoked on the "way up" the tree, so that nodes are added to `dead_nodes` set if they diverge before completing (or they never start)
* [ ] test against the objc crate version that had problems
* [ ] run a "crater check" run and see the results
* [ ] improve the error message

### LINKED ISSUE #66757: Regression in Error conversion from Infallible
The following code:

```rust
use std::convert::{TryFrom, Infallible};

struct E;

impl From<Infallible> for E {
    fn from(_: Infallible) -> E {
        E
    }
}

fn foo() -> Result<(), E> {
    u32::try_from(1u32)?;
    Ok(())
}
```

[compiles on stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=497c2032a83849e5cf80c81e32eccf9c) but [fails to compile on nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=497c2032a83849e5cf80c81e32eccf9c) with:

```
error[E0277]: `?` couldn't convert the error to `E`
  --> src/lib.rs:13:24
   |
13 |     u32::try_from(1u32)?;
   |                        ^ the trait `std::convert::From<()>` is not implemented for `E`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following implementations were found:
             <E as std::convert::From<!>>
   = note: required by `std::convert::From::from`
```

This was discovered through https://github.com/bytecodealliance/wasmtime/issues/633

### LINKED ISSUE #67225: without fallback, never type introduces regressions
When we attempted to stabilize the never type (`!`) in #65355, we encountered unexpected regressions (https://github.com/rust-lang/rust/issues/66757). These regressions resulted from this canonical test, soon to be in the repo as `src/test/never_type/never-value-fallback-issue-66757.rs`. The heart of the test is:

```rust
struct E;

impl From<!> for E {
    fn from(_: !) -> E {
        E
    }
}

#[allow(unreachable_code)]
fn foo(never: !) {
    <E as From<!>>::from(never);  // Ok
    <E as From<_>>::from(never);  // Inference fails here
}
```

The problem here is that the `never` variable, when referenced, gets assigned a fresh diverging type variable as its type. In the second call, that type variable is unconstrained, and hence it falls back -- to `()`. This leads to a compilation error.

We need to resolve this. @SimonSapin did a great job of [outlining the alternatives here](https://github.com/rust-lang/rust/issues/66757#issuecomment-559771169). The current preference is probably to enable the new never type fallback. If that should fail, we could consider altering the fallback for rvalues of `!` type from those of diverging expressions, [as described here](https://github.com/rust-lang/rust/issues/66757#issuecomment-560571316), but that will require more discussion to reach consensus (there are other options too, see Simon's comment).

### PR DESCRIPTION
**Pull request by nikomatsakis**
This branch represents a proposed means to handle fallback for the `!` type. The intuition is that it *sometimes* falls back to `!` and sometimes `()`. We prefer to fallback to `!` but will fallback to `()` if the `!` type may escape into live code. 

Here is a write-up:

https://gist.github.com/nikomatsakis/7a07b265dc12f5c3b3bd0422018fa660

Fixes #66173
Fixes #67225
Fixes #66757

cc @rust-lang/lang 
r? @matthewjasper

### CODE REVIEW

**Comment by mark-i-m** [comment]
> Fixes #67255

Is this the right one?

Also am I correct in assuming that this paves away for finally stabilizing `!`?

**Comment by nikomatsakis** [comment]
@mark-i-m 

> Is this the right one?

Nope, fixed, thanks =)

> Also am I correct in assuming that this paves away for finally stabilizing `!`?

That is my hope, yes.

**Comment by nikomatsakis** [comment]
I'm thinking of preparing a variant of this PR that "stabilizes" the `!` type so we can run a crater run and see what the effect would be if we used this fallback

**Comment by joshtriplett** [comment]
That sounds like a great plan.

**Comment by nikomatsakis** [comment]
Created https://github.com/rust-lang/rust/pull/79470 for crater run

**Comment by Dylan-DPC** [comment]
@nikomatsakis do you still need this PR or we can close it and reopen later?

**Comment by nikomatsakis** [comment]
@Dylan-DPC I think we can close it, although @Mark-Simulacrum and I were talking about some possible extensions here. But I don't see that having this PR open is helping anything.

**Comment by Mark-Simulacrum** [comment]
Yeah, I don't think the PR being open is helpful. I still need to type up a summary of our discussion, but that'll go into a new issue.

**Pull request closed without merging**
