### PR TITLE
tests: fix filecheck typos

### PR DESCRIPTION
**Pull request by klensy**

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Mh not able to understand why this is a typo?

**Comment by klensy** [comment]
As noted in readme (https://llvm.org/docs/CommandGuide/FileCheck.html#the-check-label-directive), FileCheck require colon after directive, otherwise it will skip line.

**Comment by vincenzopalazzo** [comment]
>As noted in readme (https://llvm.org/docs/CommandGuide/FileCheck.html#the-check-label-directive), FileCheck require colon after directive, otherwise it will skip line.

Maybe better ad it as a commit body + PR description

**Comment by Mark-Simulacrum** [comment]
r=me

**Comment by Dylan-DPC** [comment]
@klensy any updates on this? thanks

**Comment by jieyouxu** [comment]
cc https://github.com/rust-lang/rust/pull/128018

**Pull request closed without merging**
