### PR TITLE
rustc_driver: style nit

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by Centril** [comment]
What's wrong with the code as written tho?

**Comment by davidtwco** [comment]
I agree with @Centril, I'm not sure this is worth changing.

**Comment by tshepang** [comment]
I thought it was not idiomatic, that it's a smell to have match with unused inner bindings?

**Comment by Centril** [comment]
We use that all over the place in the compiler; taking advantage of the power of `match` seems very idiomatic Rust to me. :)

**Pull request closed without merging**
