### PR TITLE
const-eval: error when encountering references to functions / vtables

### PR DESCRIPTION
**Pull request by RalfJung**
Such references sound like an exceedingly bad idea... just use raw pointers if you must do things like this.

But we should crater this, to be on the safe side.

### CODE REVIEW

**Comment by RalfJung** [comment]
Eh, sorry.
r? @oli-obk

**Comment by RalfJung** [comment]
@craterbot check

**Comment by RalfJung** [comment]
Okay two of these are legit regressions -- some people are actually creating references to vtables. oO

- https://crater-reports.s3.amazonaws.com/pr-121199/try%23aface909a877127f24c62858518cef2d593e2ea1/gh/ink-feather-org.trait_cast_rs/log.txt
- https://crater-reports.s3.amazonaws.com/pr-121199/try%23aface909a877127f24c62858518cef2d593e2ea1/reg/rattish-0.6.0/log.txt

I will have to check more closely if what they are doing makes any sense.

**Comment by oli-obk** [comment]
I'm gonna assume no one actually found it important to have it be a reference. It was just natural to assume that since we know the pointer is always valid, we can also just use a reference to statically signal that.

Then again... Why not permit references to vtables as long as the pointee type is an extern type? That seems like the one use case for it that is not going to be biting us

**Comment by RalfJung** [comment]
Clearly there is no UB here, since we allow such references to point even do bare integer addresses and soon to go out-of-bounds or even after-free.

This was meant more as a lint, an early warning system. If someone creates a reference to a vtable then maybe they think they can read/write it and that would be UB. But that would probably need a more targeted message. Not "this code has UB" but "you are doing something which is likely leading to UB elsewhere and here is why".

That would be a lot more work than this PR so yeah let's close this.

**Pull request closed without merging**
