### PR TITLE
adapt native-link-modifier-bundle test to use llvm-nm

### PR DESCRIPTION
**Pull request by krasimirgg**
No functional changes intended.

This updates the test case to use `llvm-nm` as an alternative to https://github.com/rust-lang/rust/pull/98424.

This fixes a test failure over at the experimental build of rustc with HEAD LLVM:
https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/11144#01814d0f-a46a-4c19-91cf-41e720edb6f9/684-691.

The issue is that this test uses the system nm, which may not be recent
enough to understand the bitcode produced by rustc when compiled against HEAD LLVM.

Similar to what we did for another test in https://github.com/rust-lang/rust/pull/94023.

### CODE REVIEW

**Comment by nikic** [comment]
Can you please squash the commits?

**Comment by nikic** [comment]
Well, no idea what went wrong, but closing and reopening helped :)

**Comment by mati865** [comment]
> /bin/sh: line 1: D:arustrustbuildi686-pc-windows-gnullvmbuildbin/llvm-nm: No such file or directory

Path to `llvm-nm` must have had mix of forward and backward slashes.

**Comment by krasimirgg** [comment]
> Path to llvm-nm must have had mix of forward and backward slashes.

I'll try escaping this differently. Not sure how to re-try the `i686-mingw-1` checks.

**Pull request merged**
