### PR TITLE
Remove braces from Rust 2015 panic macro

### LINKED ISSUE #7723: `if_then_panic` doesn't fire when edition is 2021
Lint name: if_then_panic

I tried this code:

src/main.rs
```rust
#![warn(clippy::if_then_panic)]

fn main() {
    if true { panic!("ABC"); };
}
```

Cargo.toml
```
[package]
name = "play_if_else_panic_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

I expected to see this happen: The lint to be triggered

Instead, this happened: Nothing. It's a false negative.

### Meta

**Rust version (`rustc -Vv`):**

```
rustc 1.57.0-nightly (fdf65053e 2021-09-07)
binary: rustc
commit-hash: fdf65053e99e8966f9bd83b5a8491326cb33d638
commit-date: 2021-09-07
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```
### Comments
I think the problem is that rustc produces different HIR for `panic!` in the 2021 edition and `clippy_utils::higher` doesn't handle it. It's possible that other lints will have similar problems.

### PR DESCRIPTION
**Pull request by nbdd0121**
I rediscovered #80846 myself when tweaking panic macros for const panics. I find this discrepancy between core panic, 2021 panic and 2015 std panic confusing and a little bit annoying.

Given that #80846 suggests that the braces is not there for purpose, and edition 2021 crater run does not seem to catch any crates depending on this behaviour (the difference is only triggered when using `&panic!()`), I think it shall be fine to remove this and align panic macros across editions.

Fix rust-lang/rust-clippy#7723

r? @m-ou-se

### CODE REVIEW

**Comment by m-ou-se** [comment]
@rfcbot merge

This removes the extra `{}` from the expansion of `std::panic!()` in Rust 2015 and Rust 2018. (It is already removed in Rust 2021.)

This is a subtle breaking change:

```rust
fn main() {
    let a: &usize;
    a = &panic!();
}
```
used to compile, and will now fail with:

```
error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
4 |     a = &panic!();
  |         ^^^^^^^^^ expected `usize`, found `!`
  |
  = note: expected reference `&usize`
             found reference `&!`
```

We didn't see any case of this during the 2021 crater run when switching to the 2021 panic macro, which also doesn't have this extra `{}`.

Grepping for `&(panic|todo|unimplemented|unreachable)!` through all `*.rs` on crates.io gives zero hits.

cc @rust-lang/lang

**Comment by Mark-Simulacrum** [comment]
I don't think we should be landing breakage without strong motivation, particularly when we are already using the edition mechanism to transition users to a space where they'll never encounter this inconsistency.

Can we elaborate on the reasoning to do this? The PR description says that the discrepancy is annoying, but it's not clear to me which context that's in; I wouldn't expect any Rust user to encounter it, and I feel like std doesn't really get simpler if we omit a couple of braces on a macro that's unlikely to get touched much. I think we need stronger justification. If we had the opportunity to fully align the macros across all editions, I think that would be a different discussion, but this PR at least doesn't unify any macros in core/std as far as I can tell... and from past discussions my understanding is that isn't possible.

**Comment by nbdd0121** [comment]
> I don't think we should be landing breakage without strong motivation, particularly when we are already using the edition mechanism to transition users to a space where they'll never encounter this inconsistency.

This inconsistency is not current migrated by `cargo fix`. If we don't fix the discrepancy there will be a perpetual gap for semantics in difference editions.

> Can we elaborate on the reasoning to do this? The PR description says that the discrepancy is annoying, but it's not clear to me which context that's in; I wouldn't expect any Rust user to encounter it, and I feel like std doesn't really get simpler if we omit a couple of braces on a macro that's unlikely to get touched much.
> I think we need stronger justification. If we had the opportunity to fully align the macros across all editions, I think that would be a different discussion, but this PR at least doesn't unify any macros in core/std as far as I can tell... and from past discussions my understanding is that isn't possible.

I actually discovered this subtle difference when I tried to align macros across all editions; I was experimenting doing thhe following in the rustc_builtin_macros for `panic!`:
* Check if edition is 2021 or the usage is compatible to 2021 panic:
  * Forward to 2021 macro if it is
* Otherwise it must be a `panic!(sth)`, issue a lint, and forward it to the legacy panic (i.e. panic_any or panic_str).

The rationale behind the attempted change is to simplify the logic of current non_fmt_panic so that it will only need to check for legacy panic calls rather than having to inspect the arguments again.

Appearantly when I make the change the tests break, and I realized this inconsistency, and 
a search leads me to #80846. I could change the code to forward 2015 panic to `{panic_2021!(...)}`, but I feel that we don't really need that discrepancy, and that discrepancy should be eliminated if we want to ensure an edition transistion is as smooth as possible.

**Comment by Mark-Simulacrum** [comment]
> This inconsistency is not current migrated by cargo fix. If we don't fix the discrepancy there will be a perpetual gap for semantics in difference editions.

It's expected that there are gaps forever in between editions; I don't think whether cargo fix changes this really matters for that? Most users (particularly those not upgrading to new editions) are not running cargo fix regardless.

> I could change the code to forward 2015 panic to {panic_2021!(...)}, but I feel that we don't really need that discrepancy, and that discrepancy should be eliminated if we want to ensure an edition transistion is as smooth as possible.

The transition would only be made more painful by breaking users on 2015, right? They'd not be able to run cargo fix, as it doesn't support by default running with a broken compilation in the baseline compiler. Edition migrations target the intersection of two editions, not immediately putting you into the new edition.

If there is a major benefit to compiler internals, then we could consider breaking users, so perhaps seeing the benefits there would be a good motivation -- if it's a fairly local increase in complexity, the edition mechanism was an explicit choice in tradeoffs that made the call that we're OK with more complex internals in favor of avoiding breakage.

**Comment by m-ou-se** [comment]
The other option is changing the language/compiler to make the version without braces work as well in this situation.

**Comment by nikomatsakis** [comment]
I agree with @Mark-Simulacrum that I would want to see more discussion of the motivation here. Why was this change in Rust 2021, for starters?

**Comment by nbdd0121** [comment]
> Why was this change in Rust 2021, for starters?

`core::panic!` never had the brace, and Rust 2021 aligns `std::panic! towards `core::panic!`.

**Comment by nbdd0121** [comment]
> Another option is changing the language/compiler to make the version without braces work as well in this situation.

I think this is a case where brace introduces an opportunity for coercion. It's similar to e.g. this case:
```rust
let x: &&dyn Any = &&1; // This doesn't work
let x: &&dyn Any = &{&1}; // This works
```

**Comment by m-ou-se** [comment]
> Why was this change in Rust 2021, for starters?

@nikomatsakis This is a difference between std::panic and core::panic in Rust 2015/2018, see https://github.com/rust-lang/rust/issues/80846. In Rust 2021, std::panic and core::panic are the same, removing this difference.

**Comment by nikomatsakis** [comment]
OK. I see now. I'm still feeling a bit skeptical-- as Marc says, the *point* of editions is not permit permanent differences between editions, and to ensure that users have to "opt-in" to see them. We don't necessarily mandate `cargo fix` for changes that are not especially significant, but I am still wary of subtle changes in semantics that will affect people, at least without strong motivation. I have to admit I don't really understand the motivation here yet -- it sounds like it will make the implementation simpler, but I'm not sure I understand how.

**Comment by Manishearth** [comment]
(clippy team member here) No, we definitely should not fossilize the panic implementation because of clippy, we should fix the resugaring

**Comment by Mark-Simulacrum** [comment]
Clippy has basically a bug, which should be fixed, buy the appropriate fix is in clippy, not changing the standard library implementation in a way that includes at least theoretical breakage. So it's not really motivation for this patch.

**Comment by crlf0710** [comment]
Closing according to https://github.com/rust-lang/rust/pull/88919#issuecomment-948077576 .

**Pull request closed without merging**
