### PR TITLE
Lowering cleanups [2/N]

### PR DESCRIPTION
**Pull request by oli-obk**
Double indirections are unnecessary

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try

We should benchmark this

**Comment by nikomatsakis** [comment]
r? @nikomatsakis

(@pnkfelix is not available right now)

**Comment by Mark-Simulacrum** [comment]
Link when perf is done: https://perf.rust-lang.org/compare.html?start=2808460e0f8082ac2724c9809d27990ca9cfefd8&end=cd6ea61038a3f140c638560c4d1f9da951e382a4&stat=instructions%3Au

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+ 

This actually shows some small wins (2% on syn), which I didn't really expect I have to admit. ;)

**Pull request merged**
