### PR TITLE
Add `core::iter::adapters::PeekMap` and `core::iter::Peekable::peek_map`

### PR DESCRIPTION
**Pull request by MiguelX413**
Add a feature called peak_map.
I need to add further documentation but do need guidance as it's my first time contributing to Rust.

### CODE REVIEW

**Comment by the8472** [comment]
You may want to [file an ACP](https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html) for discussion. It's not strictly required but it'll make it easier to separate API from implementation discussion.

**Comment by MiguelX413** [comment]
> You may want to [file an ACP](https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html) for discussion. It's not strictly required but it'll make it easier to separate API from implementation discussion.

I'll look into that! Thank you! @the8472

**Comment by the8472** [comment]
You can leave out the unsafe trait impls if they cause issues. They exist for perf optimizations and can be added later if necessary.

**Comment by the8472** [comment]
btw, you can run those tests locally with `./x check core --stage 0`

https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html

**Comment by MiguelX413** [comment]
> btw, you can run syntax-checking locally with `./x check core --stage 0`
> 
> https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html

Noted, thank you.

**Comment by Nilstrieb** [comment]
Have you made the ACP already? I don't see one linked. I'm gonna make this as waiting on you for the ACP to be accepted. Use `@rustbot ready` when it has been accepted.
@rustbot author

**Comment by Dylan-DPC** [comment]
@MiguelX413 any updates on creating the ACP? thanks

**Comment by Dylan-DPC** [comment]
Closing this as no ACP was created or linked to the pr

**Pull request closed without merging**
