### PR TITLE
DONOTLAND (perf-only): Disable potentially unsound int2ptr/ptr2int optimizations

### PR DESCRIPTION
**Pull request by thomcc**
See https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/Set.20flags.20to.20control.20pointer.20provenance.20related.20optimization for justification here. We'd like to measure the performance impact of this for various reasons, one of which being that it would be useful information for upstream.

r? @ghost

### CODE REVIEW

**Comment by thomcc** [comment]
Yes, yes, that failure is expected. The flag only exists in recent LLVM. Hopefully this doesn't impact the perf run.

**Comment by cuviper** [comment]
As long as "recent" includes our LLVM 14 submodule (:heavy_check_mark:), then try+perf should be fine.
(AFAICS that option was added in LLVM 13.)

**Comment by thomcc** [comment]
Yep, that sounds right to me as well.

**Comment by thomcc** [comment]
Interesting. This hurt quite a bit for `deep-vector`, and very little for anything else.

**Pull request closed without merging**
