### PR TITLE
[beta] backport rollup

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This includes a bunch of PRs:
 *  Fix redundant semicolon lint interaction with proc macro attributes #64387 
 *  Upgrade async/await to "used" keywords. #64875 
 *  syntax: fix dropping of attribute on first param of non-method assocated fn #64894 
 *  async/await: improve not-send errors #64895 
 *  Silence unreachable code lint from await desugaring #64930 
 *  Always mark rust and rust-call abi's as unwind #65020 
 *  Account for macro invocation in `let mut $pat` diagnostic. #65123 
 *  Ensure that associated `async fn`s have unique fresh param names #65142 
 *  Add troubleshooting section to PGO chapter in rustc book. #65402 
 *  Upgrade GCC to 8.3.0, glibc to 1.17.0 and crosstool-ng to 1.24.0 for dist-armv7-linux #65302 
 *  Optimize `try_expand_impl_trait_type` #65293 
 *  use precalculated dominators in explain_borrow #65172 
 *  Fix ICE #64964 #64989 
 *  [beta] Revert "Auto merge of #62948 - matklad:failable-file-loading, r=petro… #65273 
 *  save-analysis: Don't ICE when resolving qualified type paths in struct members #65353 
 *  save-analysis: Nest tables when processing impl block definitions #65511 
 *  Avoid ICE when checking `Destination` of `break` inside a closure #65518 
 *  Avoid ICE when adjusting bad self ty #65755 
 *  workaround msys2 bug #65762

### CODE REVIEW

**Comment by RalfJung** [comment]
@Mark-Simulacrum I saw that same SSL failure on 3 other CI runs. I bet it'll happen again here...

**Comment by RalfJung** [comment]
And there it is... @rust-lang/infra we got a persistent SSL failure in "Download and install ninja" (and a `aws: command not found` later?).

@bors treeclosed=1000

**Comment by Mark-Simulacrum** [comment]
@bors r=pietroalbini

Cherry-picked the msys2 workaround and will go beta approve it.

**Comment by Mark-Simulacrum** [comment]
@bors r=pietroalbini

Included another set of approvals.

**Comment by Mark-Simulacrum** [comment]
er, forgot to push

@bors r=pietroalbini

**Comment by kennytm** [comment]
@bors retry

```
2019-10-26T03:52:40.7401129Z  The remote server returned an error: (503) Server Unavailable. Service Unavailable
```

**Pull request merged**
