### PR TITLE
submodule: update rls from c9d25b to f331ff7

### PR DESCRIPTION
**Pull request by h-michael**
Update rls https://github.com/rust-lang/rls/compare/c9d25b667a...e2145d

https://github.com/rust-lang/rls/pull/1276 - h-michael:clippy, r=Xanewok
https://github.com/rust-lang/rls/pull/1269 - rust-lang:dependabot/cargo/rand-0.6.5, r=Xanewok
Remove extra backticks in contributing.md
https://github.com/rust-lang/rls/pull/1267 from h-michael/contributingmd
https://github.com/rust-lang/rls/pull/1268 from matthiaskrgr/rustup
https://github.com/rust-lang/rls/pull/1262 from rust-lang/dependabot/cargo/tokio-0.1.15
https://github.com/rust-lang/rls/pull/1264 - h-michael:pub-crate, r=alexheretic
https://github.com/rust-lang/rls/pull/1261 - rust-lang:dependabot/cargo/tokio-timer-0.2.9, r=Xanewok
https://github.com/rust-lang/rls/pull/1263 - Xanewok:update-clippy, r=Xanewok
https://github.com/rust-lang/rls/pull/1257 from Xanewok/architecture
https://github.com/rust-lang/rls/pull/1258 - rust-lang:dependabot/cargo/lsp-types-0.55.1, r=Xanewok
https://github.com/rust-lang/rls/pull/1255 - Xanewok:you-only-complete-once-fool, r=Xanewok
https://github.com/rust-lang/rls/pull/1252 - rust-lang:dependabot/cargo/cargo_metadata-0.7.0, r=alexheretic
https://github.com/rust-lang/rls/pull/1253 - rust-lang:dependabot/cargo/lsp-types-0.55.0, r=Xanewok
https://github.com/rust-lang/rls/pull/1254 - rust-lang:dependabot/cargo/serde_json-1.0.37, r=Xanewok
dependabot: Explicitly list default allowed_updates
dependabot: Add automerge strategy for clippy_lints
https://github.com/rust-lang/rls/pull/1251 - Xanewok:translate-deglob-test, r=Xanewok
https://github.com/rust-lang/rls/pull/1250 from alexheretic/master
https://github.com/rust-lang/rls/pull/1244 - Xanewok:translate-tests, r=alexheretic
https://github.com/rust-lang/rls/pull/1247 - alexheretic:register-more-clippy, r=Xanewok
https://github.com/rust-lang/rls/pull/1230 - emilio:testing-testing, r=Xanewok
https://github.com/rust-lang/rls/pull/1246 from alexheretic/did-save-manifest
Merge branch 'beta-version-bump' of https://github.com/rust-lang-nursery/rls

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Re-assigning to @Xanewok

**Comment by Xanewok** [comment]
@bors r+

Hoping that the tooltip tests won’t decide to hang again

**Comment by h-michael** [comment]
I'll try finding cause at night(UTC 20:00 +09:00)

**Comment by Xanewok** [comment]
Seems spurious

@bors retry

**Comment by mati865** [comment]
> [01:46:41] test test_tooltip_racer ... test test_tooltip_racer has been running for over 60 seconds
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.

The same test failed in the previous PR.

**Comment by Xanewok** [comment]
I’ll investigate later in the evening - it’s unfortunate since these don’t
hang in our Travis CI.

**Comment by Xanewok** [comment]
Could we update RLS to the version in https://github.com/rust-lang/rls/commit/e2145db5fa01f261138bbe1a6ca1c3ed05852d2d?

This also includes a [Racer update](https://github.com/rust-lang/rls/commit/d1fb662d0046bb2073e74c4fc0cdbcfc0342db25), which itself contains a fix for high CPU usage and hopefully may unhang the `test_tooltip` tests.

**Comment by Xanewok** [comment]
Failed on Rust test suite but this didn’t touch rustc so...

@bors retry

**Comment by Xanewok** [comment]
Ah, only now I got the message about tooltip failure yet again... :/

@bors r-

**Comment by Xanewok** [comment]
@h-michael please also include the unfortunate https://github.com/rust-lang/rls/commit/f331ff713917f6edb044c7e5c6c28c3845afebe7 commit - this disables these tests for now.

At the moment I can't reliably look into the underlying issue and I don't want to block nightlies because of the broken RLS toolstate. I'll look into the issue next week.

**Comment by h-michael** [comment]
@Xanewok I got it :)

**Comment by Xanewok** [comment]
Seems that Clippy fails to build?

```
[01:10:05] error[E0023]: this pattern has 4 fields, but the corresponding tuple variant has 5 fields
[01:10:05]    --> src\tools\clippy\clippy_lints\src\utils\mod.rs:376:9
[01:10:05]     |
[01:10:05] 376 |         PatKind::Binding(_, _, ref spname, _) => Some(spname.name),
[01:10:05]     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 5 fields, found 4
```

cc @matthiaskrgr @oli-obk

**Comment by h-michael** [comment]
I think current nightly can't build clippy.
There are same fail cases in clippy_lint CI.
https://ci.appveyor.com/project/rust-lang-libs/rust-clippy/builds/22083541

**Comment by h-michael** [comment]
@phansch OK I update clippy dependency. :)

**Comment by h-michael** [comment]
@phansch I'll also update rust clippy dependency with this PR.

**Comment by mati865** [comment]
@h-michael Rust build system patches dependencies to use checked submodules. Clippy version in RLS repository doesn't matter here. You should just update Clippy submodule in this (Rust) repository and refresh Cargo.lock with `./x.py` like you did before.

**Comment by h-michael** [comment]
@mati865 
Rls can't be built with current nightly because of clippy lint.
And I think we should clippy_lint of rls revision update after updating clippy of rust revision.
https://github.com/rust-lang/rls/pull/1287

Do I have a something misunderstood?

**Comment by mati865** [comment]
@h-michael Rust build system doesn't care about Clippy version set here: https://github.com/rust-lang/rls/blob/f331ff713917f6edb044c7e5c6c28c3845afebe7/Cargo.toml#L24

This line replaces `clippy_lints` version for all crates to the one which is checked at `src/tools/clippy/clippy_lints`: https://github.com/rust-lang/rust/blob/master/Cargo.toml#L71

**Comment by Xanewok** [comment]
Clippy PR landed.

@bors r+ p=1

**Comment by h-michael** [comment]
Thanks for all supporting me :)

**Comment by Xanewok** [comment]
And thank you for your work!

**Pull request merged**
