### PR TITLE
Suppress space after idents with "ModName" style in serialization of exported macros.

### PR DESCRIPTION
**Pull request by vadimcn**
... so that `super::foo` gets serialized as `super:: foo`, rather than `super :: foo`.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Can you add a test for this as well?

**Comment by vadimcn** [comment]
Done.  r?

**Comment by sfackler** [comment]
cc #20923

**Comment by alexcrichton** [comment]
Looks like there are some tidy errors, otherwise r=me, thanks!

**Comment by vadimcn** [comment]
ok, looks like tidy is happy now

**Pull request merged**
