### PR TITLE
Optimized error reporting for recursive requirements #47720

### LINKED ISSUE #47720: On recursive requirements, elide repeating output
When encountering [recursive requirements](https://play.rust-lang.org/?gist=c700819390969c7374e557e80157fe74&version=stable), elide some of the repeating output instead of having the following wall of text detailing every recursive step the compiler takes:

```
error[E0275]: overflow evaluating the requirement `Foo: std::marker::Sync`
 --> src/main.rs:5:1
  |
5 | / lazy_static! {
6 | |     static ref CHAR: Foo = unimplemented!();
7 | | }
  | |_^
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: required because it appears within the type `std::marker::PhantomData<Foo>`
  = note: required because it appears within the type `Bar`
  = note: required because it appears within the type `std::marker::PhantomData<Bar>`
  = note: required because it appears within the type `Foo`
  = note: required because it appears within the type `std::marker::PhantomData<Foo>`
  = note: required because it appears within the type `Bar`
  = note: required because it appears within the type `std::marker::PhantomData<Bar>`
  = note: required because it appears within the type `Foo`
  = note: required because it appears within the type `std::marker::PhantomData<Foo>`
  = note: required because it appears within the type `Bar`
8<8<8<8<8<8<8<
  = note: required by `lazy_static::lazy::Lazy`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

---

The following code

https://github.com/rust-lang/rust/blob/a0dcecff90c45ad5d4eb60859e22bb3f1b03842a/src/librustc/traits/error_reporting.rs#L1285-L1293

needs to be modified to pass down a vector of the `Ty`s `note_obligation_cause_code` has encountered on previous runs. I feel it is reasonable to delay the `note`s from being produced until the bottom has been reached, and prune the list then. The output should be something along the lines of

```
error[E0275]: overflow evaluating the requirement `Foo: std::marker::Sync`
 --> src/main.rs:5:1
  |
5 | / lazy_static! {
6 | |     static ref CHAR: Foo = unimplemented!();
7 | | }
  | |_^
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: required because it appears within the type `std::marker::PhantomData<Foo>`
  = note: required because it appears within the type `Bar`
  = note: required because it appears within the type `std::marker::PhantomData<Bar>`
  = note: required because it appears within the type `Foo`
  = note: required because it appears within the type `std::marker::PhantomData<Foo>`
  = note: ...and so on, these requirements repeat until reaching the recursion limit
  = note: required by `lazy_static::lazy::Lazy`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by hrvolapeter**
Fixes #47720

### CODE REVIEW

**Comment by kennytm** [comment]
Thanks for the PR! We’ll periodically check in on it to make sure that @pnkfelix  or someone else from the team reviews it soon.

**Comment by pietroalbini** [comment]
@pnkfelix ping from triage! This PR needs a review.

**Comment by kennytm** [comment]
@bors retry

3 hour timeout in `asmjs`.

**Comment by retep007** [comment]
@kennytm I think this got stuck

**Comment by kennytm** [comment]
@retep007 No the queue is normal. This PR was taken out to give way to more important ones (and the CI situation is not particularly healthy recently). Sorry for the delay.

**Comment by pietroalbini** [comment]
Known failure: #48116

```
[01:55:52] failures:
[01:55:52]     [compile-fail] compile-fail/rfc-2126-extern-in-paths/single-segment.rs
[01:55:52]     [compile-fail] compile-fail/use-keyword.rs
[01:55:52]     [compile-fail] compile-fail/use-mod-2.rs
```

**Pull request merged**
