### PR TITLE
Remove `box_syntax` usage

### LINKED ISSUE #109978: Unstable book uses box_syntax
https://github.com/rust-lang/rust/blob/4cb92cc83ac6b24d83f8a30763b276cadb8dc41d/src/doc/unstable-book/src/language-features/lang-items.md?plain=1#L19

There is no such thing as box_syntax anymore :D

### PR DESCRIPTION
**Pull request by ghost**
Fixes #109978

### CODE REVIEW

**Comment by Nilstrieb** [comment]
There are other uses of it here, for example in plugins.md as mentioned.

**Comment by GuillaumeGomez** [comment]
r? rust-lang/libs

**Comment by Nilstrieb** [comment]
r? Nilstrieb
This isn't really libs, I'll take it over

**Comment by Nilstrieb** [comment]
Did you check whether there are more usages of it?

**Comment by gimbles** [comment]
I did, yes, all other usages seem to be unrelated.

**Review by Noratrieb — APPROVED** [review]

**Pull request merged**
