### PR TITLE
Get LLVM using jemalloc and inline FNV hashing

### PR DESCRIPTION
**Pull request by alexcrichton**
Looking at some profiles of rustc recently, these seemed like two pretty easy wins we could get in terms of performance on the table.

### CODE REVIEW

**Comment by dotdash** [comment]
Do you have any numbers for this? Also, I seem to recall a huge discussion the last time the prefixes were to be dropped. Has that been resolved or is this a different change?

**Comment by bluss** [comment]
We should put in a release note if the jemalloc prefix changes. If anyone is experimenting with `JE_MALLOC_CONF` and so on, it's useful to know it has changed.

**Comment by alexcrichton** [comment]
@dotdash ah yeah sorry I forgot to copy them over into the PR description, but the two commits have:

jemalloc un-prefixing:

> Locally this took compile time for libsyntax from 95 seconds to 89 (a 6% improvement).

fnv inline:

> This commit made the hashing function disappear from a profiled version of the compiler, but that's likely because it was just inlined elsewhere. When compiling winapi, however, this decreased compile time from 18.3 to 17.8 seconds (a 3% improvement).

@bluss good point!

**Comment by dotdash** [comment]
@alexcrichton Thanks! You missed the prefix issue though. The old PR was #18678 which, besides the long discussion that led to it not being merged, also had it so that on iOS/OSX and Windows, the prefix is still present (which is the default for jemalloc).

**Comment by alexcrichton** [comment]
Aha yes, thanks for finding a link to that! I should have hunted that down and thrown that in here.

When that discussion happened we did not have the same support for swapping out allocators that we have today. The [RFC for custom allocators](https://github.com/rust-lang/rfcs/blob/master/text/1183-swap-out-jemalloc.md) was merged long after that discussion, and the [early conclusions](http://smallcultfollowing.com/babysteps/blog/2014/11/14/allocators-in-rust/) also pointed towards using jemalloc unprefixed in executables. The major difference between now and #18678 is that we *only* use jemalloc in executables, no static library or dynamic library in Rust uses jemalloc by default (they use the system allocator).

As a result, due to the change in landscape, many of the concerns raised in #18678 have since been solved. One of the major motivational factors for [RFC 1183](https://github.com/rust-lang/rfcs/blob/master/text/1183-swap-out-jemalloc.md) was indeed to land this change, I just forgot to get around to it until now!

**Comment by alexcrichton** [comment]
Oops!

**Comment by dotdash** [comment]
@bors r-

Seems that bors was a bit too happy to see this restored

**Comment by alexcrichton** [comment]
@bors: r=brson 51e0ee8

ok, let's try that again

**Comment by alexcrichton** [comment]
Looks like the failure on musl was legitimate, and it happened because:

1. Both liballoc_jemalloc and liblibc defined a function called `malloc`
2. When creating a binary with LTO, both rlibs were linked with `-Wl,--whole-archive`

This meant the linker found itself trying to include the same symbol twice, and rightly exited with an error. 

I believe that the compiler here is erroneous in passing `-Wl,--whole-archive` when we're linking an executable (that was just intended for a dylib), so I've added a commit to not do that (with a test added as well).

**Comment by alexcrichton** [comment]
ah and re-r? @brson

**Comment by alexcrichton** [comment]
Whelp, shoulda known that any segfault from unprefixing jemalloc is indicative of mixing allocators. Looks like on Android allocator replacement in libc somehow doesn't work. We call `realpath` with a `NULL` second parameter to indicate that it should return to us a buffer allocated with `malloc`. We then later call `libc::free` on the returned buffer. Presumably libc use the libc malloc, and we use the jemalloc free, hence badness!

I'll just re-prefix the symbols on android for now.

**Pull request merged**
