### PR TITLE
Remove implicit dependencies on syntax::pprust

### PR DESCRIPTION
**Pull request by Centril**
Part of https://github.com/rust-lang/rust/pull/65324.

The main goal here is to facilitate the eventual move of pprust out from libsyntax and because an AST definition typically should not depend on its pretty printer.

r? @estebank

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Historically I've looked at doing this but didn't see it as immediately actionable. Seems like pprust is still just as coupled with this commit. But I don't mind it, I guess, since it should make further decoupling easier (since you can handle each case separately, vs. an unknown number of cases through a Display/Debug impl).

**Comment by Centril** [comment]
(iirc there were rather few dependencies on pprust left in libsyntax after https://github.com/rust-lang/rust/pull/65324 so in a larger context this should bring us closer to that goal.)

r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
@bors r+

Changes look correct to me, and it seems to be passing CI. Some of the debug output is probably technically worse now but not in a way that seems immediately bad to me so we can probably leave it be for the time being.

**Pull request merged**
