### PR TITLE
Only allow `repr(i128/u128)` on enum

### LINKED ISSUE #74082: Compiler allows #[repr(i/u128)] on structs
I tried this code:

```rust
#[repr(i128)]
#[repr(u128)]
struct Foo;
fn main() {
    println!("{}", std::mem::size_of::<Foo>());
}
```

I expected to see this happen: compilation failure

Instead, this happened: Compiles, outputs "0"

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-pc-windows-msvc
release: 1.44.0
LLVM version: 9.0
```
Also: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a62809034300d238de36941eccd094bb)

This issue has been assigned to @nbdd0121 via [this comment](https://github.com/rust-lang/rust/issues/74082#issuecomment-654428556).

### PR DESCRIPTION
**Pull request by nbdd0121**
Fixes #74082

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Tagging as relnotes -- this is technically a breaking change (cc @rust-lang/lang) but I think a reasonable one. I don't think we need to run crater on this PR, we can rely on the beta crater run to catch potential regressions.

**Comment by petrochenkov** [comment]
The failure looks spurious.
@bors retry

**Comment by scottmcm** [comment]
This seems like it's closing an obvious gap, so personally I'm happy to see it happen without an FCP.

**Comment by joshtriplett** [comment]
Seems reasonable to me.

**Pull request merged**
