### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #92248 (Normalize struct tail type when checking Pointee trait)
 - #92490 (Move crate drop-down to search results page)
 - #92510 (Don't resolve blocks in foreign functions)
 - #92535 (Allow unwinding from OOM hooks)
 - #92568 (Add note about non_exhaustive to variant_count)
 - #92600 (Add some missing `#[must_use]` to some `f{32,64}` operations)
 - #92610 (Create CSS class instead of using inline style for search results)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=92248,92490,92510,92535,92568,92600,92610)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Looks like `dist-x86_64-msvc-alt`didn't start ._.

**Comment by inquisitivecrystal** [comment]
Yeah, I was just about to mention. It appears to be hung. Kill the build and start over?

**Comment by inquisitivecrystal** [comment]
I left T-infra a message about this. The latest spurious failure seems like the ordinary kind. Still, the first two failures were really strange.

**Comment by inquisitivecrystal** [comment]
I posted this on zulip as well, but uhhh. If you have a look at [this](https://github.com/rust-lang-ci/rust/runs/4741251687?check_suite_focus=true) and [this](https://pipelines.actions.githubusercontent.com/DhU3eyB11Ei4viT99vzh0CpKzg7REqx1Nup2tB9LzmxBcoHdbh/_apis/pipelines/1/runs/14812/signedlogcontent/14?urlExpires=2022-01-07T20%3A03%3A40.5719715Z&urlSigningMethod=HMACV1&urlSignature=8S8owHJ%2Bq25ehCmZU1Jn5QbWnKQ9uCC%2FT6tbYkaF8pg%3D), it seems that maybe all those times the CI actually was running after all? I don't know.

**Pull request closed without merging**
