### PR TITLE
Lower fingerprint alignment to reduce memory consumption

### PR DESCRIPTION
**Pull request by tgnottingham**

### CODE REVIEW

**Comment by tgnottingham** [comment]
There's a bit of a speed versus space trade-off here. Anxious to see what a full perf run tells us about it.

In local rustc-perf benchmarks, the improvement is mostly noticeable in the larger crates like style-servo, where it reduces memory consumption by 70-80 MB. Doesn't sound like a ton, but it adds up when you're building in parallel. I should measure the impact on something like rustc_middle.

**Comment by jyn514** [comment]
```
---- [ui] ui/associated-types/associated-types-incomplete-object.rs stdout ----
 stderr:
------------------------------------------
thread 'rustc' panicked at 'assertion failed: eps.array_windows().all(|[a, b]| a.stable_cmp(self, b) != Ordering::Greater)', compiler/rustc_middle/src/ty/context.rs:2419:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 query stack during panic:
#0 [object_safety_violations] determine object safety of trait `Foo`
#1 [typeck] type-checking `main`
end of query stack
```
Looks like this introduces a logic bug somewhere.

**Comment by tgnottingham** [comment]
There were two issues:

1) I had implemented `PartialOrd` but `#[derive]`'d `Ord`, and they were inconsistent with one another. Implemented `Ord` so that they're consistent. Improves performance too.

2) The order of some diagnostics in UI test output depends on the comparison ordering of `Fingerprint`s (`DefPathHash`s, really). They don't depend on it in a predictable way, since the hashes are random in a sense. But the ordering I've implemented for the sake of performance changes how some `Fingerprint`s compare to one another, and so changes the order of a couple diagnostics. Updated the `.stderr` files to account for this.

**Comment by tgnottingham** [comment]
Those are very different from the results I was getting locally. Will have to investigate.

**Comment by jyn514** [comment]
Max-rss seems to have gone down a lot though :)

**Comment by tgnottingham** [comment]
One cause of the regression, and possibly all of it, is that using a `[u8; 16]` representation causes aliasing pessimizations to kick in. I think some of those would go away if `-Z mutable-no-alias` were enabled, but we're not there yet (#54878).

It's possible to work around some of the pessimizations, but it's awkward, fragile, and incomplete, so I'm abandoning this approach. Hoping to post a new PR with a better approach shortly.

**Pull request closed without merging**
