### PR TITLE
rename InterpretCx -> InterpCx

### PR DESCRIPTION
**Pull request by RalfJung**
That's more consistent with InterpResult and InterpError.

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
Looks very much like the Miri update will land first, so let's avoid wasting CI time.

@bors r-

**Comment by RalfJung** [comment]
It's just 4h until it's Wednesday UTC, I feel confident this will not land fast enough to cause problems and I want to stop having to remember.^^

@bors r=oli-obk

**Comment by howaboutsynergy** [comment]
miri still broken?!

**Pull request merged**
