### PR TITLE
Added abs_diff for integer types.

### LINKED ISSUE #62111: Add a method for computing the absolute difference between unsigned integers
See discussion in https://github.com/rust-lang/rust/pull/62103#discussion_r296988078.

### PR DESCRIPTION
**Pull request by orlp**
Closes https://github.com/rust-lang/rust/issues/62111.

### CODE REVIEW

**Comment by the8472** [comment]
Does either of these compile to a `psadbw` (or equivalent SSE/AVX instructions for wider arrays) on x86?

```rust
fn sad_iter(a: &[u8; 8], b: &[u8; 8]) -> u32 {
  a.iter().zip(b).map(|&a, &b| a.abs_diff(b) as u32).sum()
}

fn sad_loop(a: &[u8; 8], b: &[u8; 8]) -> u32 {
  let mut sum = 0;
  for i in 0..a.len() {
      sum += a[i].abs_diff(b[i]) as u32;
  }
  sum
}
```

llvm does have some [pattern detection](https://lists.llvm.org/pipermail/llvm-dev/2015-February/081561.html) to generate psadbw, so we should make sure we fall into that.

**Comment by orlp** [comment]
@the8472 I can't get Rust to generate `psadbw` without intrinsics at all.

**Comment by the8472** [comment]
Yes, it's still there. Based on comments in tickets the pattern it expects for absolute difference should look like `abs(a - b)`, it must be in a loop that can be vectorized and the aggregation variable must be 32bit or 64bit wide.

https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/X86/sad.ll
https://raw.githubusercontent.com/llvm/llvm-project/main/llvm/lib/Target/X86/X86ISelLowering.cpp

**Comment by thomcc** [comment]
It's a really fragile optimization. I've never seen it in practice, but: https://godbolt.org/z/qffbWvh4v

**Comment by orlp** [comment]
@the8472 I've tried a bunch of things, and I can't generate it.

Note that `abs(a-b)` is not valid at all unless you widen the type first (which I've also tried without luck).

**Comment by the8472** [comment]
> It's a really fragile optimization. 

I suspect it's written to match C's integer conversion rules.

**Comment by orlp** [comment]
If we consider this worthwhile I could add that implementation for `u8` specifically. It does mean I have to pull out from the `uint_macros` and create a macro myself for to add the current implementation for everything except `u8`.

**Comment by the8472** [comment]
SAD is a really important in video processing. Yes, all serious implementations will use platform-specific intrinsics but they generally have non-assembly fallback paths and if those get used for any reason (wasm? riscv?) it should be in a pattern that optimizers recognize.

**Comment by orlp** [comment]
Interestingly, while exploring this I also found that generally this:

```rust
pub fn abs_diff2(slf: u32, other: u32)  -> u32 {
    slf.max(other) - slf.min(other)
}
```

generates better code than

```rust
pub fn abs_diff(slf: u32, other: u32)  -> u32 {
    if slf < other {
        other - slf
    } else {
        slf - other
    }
}
```

for Intel, both in standalone code as well as SIMD.

**Comment by orlp** [comment]
@the8472 Implemented `psadbw` support.

**Comment by m-ou-se** [comment]
This looks good to me.

Can you [open a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX), and add its number in the #[unstable] attributes? Thanks!

**Comment by orlp** [comment]
@m-ou-se [Done](https://github.com/rust-lang/rust/issues/89492).

**Comment by m-ou-se** [comment]
Thanks!

@bors r+

**Pull request merged**
