### PR TITLE
#53576 Renaming TyAnon -> TyOpaque

### LINKED ISSUE #53576: Rename "anonymized types" internally (TyAnon & friends) to "opaque types" (TyOpaque etc.).
~~Now that we're settling on "static existentials" for the generalized version of `-> impl Trait`, I think it's time to retire my original nomenclature and use the official(?) one uniformly in the compiler.~~

**EDIT**: going with "opaque", see below.

cc @cramertj @oli-obk @aturon @Centril

### PR DESCRIPTION
**Pull request by ms2300**
Fixes #53576

### CODE REVIEW

**Review by varkor — APPROVED** [review]
This looks great to me! (@eddyb might remember if there's anywhere else that needs changing, so I'll leave the final approval to them.)

**Comment by ms2300** [comment]
All good? Should I be doing anything else?

**Comment by TimNN** [comment]
Ping from triage @eddyb / @rust-lang/compiler: This PR requires your review.

**Comment by varkor** [comment]
> All good? Should I be doing anything else?

Sorry, I meant to get back to this, but somehow forgot! It all looks correct to me, so I'll approve, and @eddyb can add any additional comments afterwards if I've forgotten anything else! Thank you!

@bors r+

**Comment by varkor** [comment]
(Sorry, messed up with my comment.)

@bors r-

**Comment by ms2300** [comment]
I squashed into two commits, thanks for the update!

**Comment by varkor** [comment]
Thanks @ms2300! Sorry for the wait!

@bors r+

**Comment by ms2300** [comment]
Does anyone know what this error is referencing?

**Comment by oli-obk** [comment]
You updated the llvm submodule. Please revert that (That's also the source of the failure)

**Comment by ms2300** [comment]
Yeah for some reason I updated a lot of the submodules somewhere in the rebasing process and reverted all but that one. My bad it should work now

**Pull request merged**
