### PR TITLE
Drop 1.56 stabilizations from 1.55 release notes

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

(Not increasing priority; will be cherry picking this to stable/beta branches anyway).

**Comment by a1ien** [comment]
Same for 
>[`collections::{BinaryHeap, BTreeSet, HashSet, LinkedList, VecDeque}` now
  implement `From<[T; N]>`.][84111]

**Comment by jhpratt** [comment]
const transmute as well (#85769)

**Pull request merged**
