### PR TITLE
Add basic Serde serialization capabilities to Stable MIR

### PR DESCRIPTION
**Pull request by sskeirik**
This PR adds basic Serde serialization capabilities to Stable MIR. It is intentionally minimal (just wrapping all stable MIR types with a Serde `derive`), so that any important design decisions can be discussed before going further. A simple test is included with this PR to validate that JSON can actually be emitted.

## Notes

When I wrapped the Stable MIR error types in `compiler/stable_mir/src/error.rs`, it caused test failures (though I'm not sure why) so I backed those out.

## Future Work

So, this PR will support serializing basic stable MIR, but it _does not_ support serializing interned values beneath `Ty`s and `AllocId`s, etc... My current thinking about how to handle this is as follows:

1.  Add new `visited_X` fields to the `Tables` struct for each interned category of interest.

2.  As serialization is occuring, serialize interned values as usual _and_ also record the interned value we referenced in `visited_X`.

    (Possibly) In addition, if an interned value recursively references other interned values, record those interned values as well.

3.  Teach the stable MIR `Context` how to access the `visited_X` values and expose them with wrappers in `stable_mir/src/lib.rs` to users (e.g. to serialize and/or further analyze them).

### Pros

This approach does not commit to any specific serialization format regarding interned values or other more complex cases, which avoids us locking into any behaviors that may not be desired long-term.

### Cons

The user will need to manually handle serializing interned values.

### Alternatives

1.  We can directly provide access to the underlying `Tables` maps for interned values; the disadvantage of this approach is that it either requires extra processing for users to filter out to only use the values that they need _or_ users may serialize extra values that they don't need. The advantage is that the implementation is even simpler. The other pros/cons are similar to the above.

2.  We can directly serialize interned values by expanding them in-place. The pro is that this may make some basic inputs easier to consume. However, the cons are that there will need to be special provisions for dealing with cyclical values on both the producer and consumer _and_ global values will possibly need to be de-duplicated on the consumer side.

### CODE REVIEW

**Comment by oli-obk** [comment]
Please squash all commits, then this lgtm

**Comment by sskeirik** [comment]
Squashed as requested and all tests showing passing results.

**Comment by oli-obk** [comment]
Thanks

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
I think this is the PR which failed in https://github.com/rust-lang/rust/pull/127079#issuecomment-2196806342. I r- t but don't hesitate to re-approve it if I'm wrong.

@bors r-

**Comment by oli-obk** [comment]
@bors r+ rollup=iffy

that failure looks like a miri failure

**Comment by sskeirik** [comment]
@oli-obk Thanks again for your review!

I have two questions about the status of this PR:

1.  In your view, did the CI failures that appeared previously when evaluating the roll-up seem to be due to this PR?
2.  If no to (1), is it possible to try again to see if that resolves the issue? I am happy to rebase this to a later rustc version (or make any other adjustments) if that would be helpful.

Thanks much!

## CI Failure Log Notes

From reading the CI failure log, it looks like the `miri` build failed due to a file copy error (build failure copied below for your convenience).

As far as I can tell, this is either a sporadic CI issue or related to a different PR in the roll-up.

I'd love to know your thoughts!

```
2024-06-28T16:03:54.3104645Z ##[group]Building tool miri (stage1 -> stage2, x86_64-pc-windows-msvc)
2024-06-28T16:03:54.6987912Z [RUSTC-TIMING] build_script_build test:false 0.501
2024-06-28T16:03:54.6989562Z [RUSTC-TIMING] cfg_if test:false 0.070
2024-06-28T16:03:54.6990683Z [RUSTC-TIMING] autocfg test:false 1.079
2024-06-28T16:03:54.6992296Z [RUSTC-TIMING] ppv_lite86 test:false 1.100
2024-06-28T16:03:54.6993499Z [RUSTC-TIMING] siphasher test:false 0.478
2024-06-28T16:03:54.6995065Z [RUSTC-TIMING] cfg_if test:false 0.055
2024-06-28T16:03:54.6996620Z [RUSTC-TIMING] version_check test:false 0.930
2024-06-28T16:03:54.6997883Z [RUSTC-TIMING] regex_syntax test:false 9.921
2024-06-28T16:03:54.6999293Z [RUSTC-TIMING] getrandom test:false 0.328
2024-06-28T16:03:54.7000576Z [RUSTC-TIMING] memchr test:false 1.566
2024-06-28T16:03:54.7001866Z [RUSTC-TIMING] phf_shared test:false 0.414
2024-06-28T16:03:54.7003165Z [RUSTC-TIMING] build_script_main test:false 1.340
2024-06-28T16:03:54.7005134Z [RUSTC-TIMING] build_script_build test:false 0.351
2024-06-28T16:03:54.7007025Z [RUSTC-TIMING] windows_targets test:false 0.055
2024-06-28T16:03:54.7008317Z [RUSTC-TIMING] build_script_build test:false 0.320
2024-06-28T16:03:54.7010325Z [RUSTC-TIMING] build_script_build test:false 0.343
2024-06-28T16:03:54.7012294Z [RUSTC-TIMING] rand_core test:false 0.459
2024-06-28T16:03:54.7013545Z [RUSTC-TIMING] aho_corasick test:false 6.907
2024-06-28T16:03:54.7015027Z [RUSTC-TIMING] phf test:false 0.306
2024-06-28T16:03:54.7016361Z [RUSTC-TIMING] build_script_build test:false 0.487
2024-06-28T16:03:54.7018548Z [RUSTC-TIMING] rand_chacha test:false 1.279
2024-06-28T16:03:54.7019796Z [RUSTC-TIMING] regex_automata test:false 6.292
2024-06-28T16:03:54.7021026Z [RUSTC-TIMING] typenum test:false 1.819
2024-06-28T16:03:54.7022359Z [RUSTC-TIMING] getrandom test:false 0.397
2024-06-28T16:03:54.7023695Z [RUSTC-TIMING] smallvec test:false 0.616
2024-06-28T16:03:54.7024941Z [RUSTC-TIMING] scopeguard test:false 0.100
2024-06-28T16:03:54.7026254Z [RUSTC-TIMING] windows_targets test:false 0.054
2024-06-28T16:03:54.7027549Z [RUSTC-TIMING] rand test:false 2.140
2024-06-28T16:03:54.7028760Z [RUSTC-TIMING] regex test:false 1.091
2024-06-28T16:03:54.7030106Z [RUSTC-TIMING] generic_array test:false 2.099
2024-06-28T16:03:54.7031309Z [RUSTC-TIMING] siphasher test:false 0.549
2024-06-28T16:03:54.7032535Z [RUSTC-TIMING] rand_core test:false 0.703
2024-06-28T16:03:54.7033767Z [RUSTC-TIMING] windows_sys test:false 8.030
2024-06-28T16:03:54.7035053Z [RUSTC-TIMING] lock_api test:false 0.608
2024-06-28T16:03:54.7036382Z [RUSTC-TIMING] parking_lot_core test:false 1.199
2024-06-28T16:03:54.7037808Z [RUSTC-TIMING] phf_generator test:false 0.161
2024-06-28T16:03:54.7039516Z [RUSTC-TIMING] parse_zoneinfo test:false 0.871
2024-06-28T16:03:54.7040940Z [RUSTC-TIMING] crypto_common test:false 0.167
2024-06-28T16:03:54.7042162Z [RUSTC-TIMING] phf_shared test:false 0.589
2024-06-28T16:03:54.7043354Z [RUSTC-TIMING] inout test:false 0.229
2024-06-28T16:03:54.7044716Z [RUSTC-TIMING] num_traits test:false 2.793
2024-06-28T16:03:54.7046014Z [RUSTC-TIMING] ppv_lite86 test:false 1.038
2024-06-28T16:03:54.7047176Z [RUSTC-TIMING] option_ext test:false 0.085
2024-06-28T16:03:54.7048536Z [RUSTC-TIMING] phf_codegen test:false 0.206
2024-06-28T16:03:54.7049731Z [RUSTC-TIMING] cipher test:false 0.613
2024-06-28T16:03:54.7050932Z [RUSTC-TIMING] phf test:false 0.366
2024-06-28T16:03:54.7052134Z [RUSTC-TIMING] chrono test:false 5.245
2024-06-28T16:03:54.7053366Z [RUSTC-TIMING] dirs_sys test:false 0.243
2024-06-28T16:03:54.7054598Z [RUSTC-TIMING] rand_chacha test:false 2.658
2024-06-28T16:03:54.7055848Z [RUSTC-TIMING] parking_lot test:false 3.547
2024-06-28T16:03:54.7057109Z [RUSTC-TIMING] windows_sys test:false 7.753
2024-06-28T16:03:54.7058485Z [RUSTC-TIMING] chrono_tz_build test:false 0.628
2024-06-28T16:03:54.7059696Z [RUSTC-TIMING] log test:false 0.646
2024-06-28T16:03:54.7060938Z [RUSTC-TIMING] cpufeatures test:false 0.068
2024-06-28T16:03:54.7062204Z [RUSTC-TIMING] rustc_hash test:false 0.130
2024-06-28T16:03:54.7063550Z [RUSTC-TIMING] build_script_build test:false 0.417
2024-06-28T16:03:54.7065453Z [RUSTC-TIMING] rand test:false 3.088
2024-06-28T16:03:54.7066758Z [RUSTC-TIMING] directories test:false 0.583
2024-06-28T16:03:54.7067963Z [RUSTC-TIMING] ctrlc test:false 0.197
2024-06-28T16:03:54.7069367Z [RUSTC-TIMING] build_script_build test:false 0.274
2024-06-28T16:03:54.7071336Z [RUSTC-TIMING] aes test:false 3.843
2024-06-28T16:03:54.7072718Z [RUSTC-TIMING] measureme test:false 2.759
2024-06-28T16:03:54.7074182Z [RUSTC-TIMING] chrono_tz test:false 5.853
2024-06-28T16:03:54.7075460Z [RUSTC-TIMING] miri test:false 61.806
2024-06-28T16:03:54.7077431Z [RUSTC-TIMING] miri test:false 3.201
2024-06-28T16:03:54.7079854Z [1m[32m    Finished[0m `release` profile [optimized] target(s) in 0.38s
2024-06-28T16:03:54.7298453Z thread 'main' panicked at src/lib.rs:1712:17:
2024-06-28T16:03:54.7300791Z failed to copy `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-tools\x86_64-pc-windows-msvc\release\miri.exe` to `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-tools-bin\miri.exe`: The process cannot access the file because it is being used by another process. (os error 32)
2024-06-28T16:03:54.7303033Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-06-28T16:03:54.7361827Z ##[endgroup]
2024-06-28T16:03:54.7404982Z Build completed unsuccessfully in 0:00:14
2024-06-28T16:03:54.7710109Z   local time: Fri, Jun 28, 2024  4:03:54 PM
2024-06-28T16:03:55.0236728Z   network time: Fri, 28 Jun 2024 16:03:55 GMT
2024-06-28T16:03:55.0290448Z ##[error]Process completed with exit code 1.
```

**Comment by ehuss** [comment]
@bors r-

bors sync

**Comment by oli-obk** [comment]
> 1. In your view, did the CI failures that appeared previously when evaluating the roll-up seem to be due to this PR?

it seems likely considering they occurred twice, but I don't really know how that can happen. Try running miri tests locally to see if it reproduces

**Comment by celinval** [comment]
The failure seems specific to `x86_64-msvc-ext`.

**Comment by celinval** [comment]
I really don't see how this PR could be breaking CI. I also noticed that different runs presented similar errors (failed to copy an artifact because it is currently being used), however, with different artifacts.

Also, this PR (https://github.com/rust-lang/rust/pull/127096) was created without this change, and it had similar failure: https://github.com/rust-lang/rust/pull/127096#issuecomment-2197878530. A retry seemed to have fixed the issue.

@bors r+

**Comment by sskeirik** [comment]
@celinval Thanks for re-running this! Glad to get this merged so we can have an easy-to-consume representation of the stable MIR AST!

**Pull request merged**
