### PR TITLE
Clarify the docs for align_of and its variants

### PR DESCRIPTION
**Pull request by ghost**
It's okay to have unaligned raw pointers and then use `ptr::write_unaligned` and `ptr::read_unaligned`.
However, using unaligned `&T` and `&mut T` would be undefined behavior.

The current documentation seems to indicate that everything has to be aligned, but in reality only references do. This PR changes the text of docs accordingly.

r? @sfackler

### CODE REVIEW

**Comment by shepmaster** [comment]
Thanks for the PR! We'll get @sfackler (or someone almost as awesome) on the case!

**Comment by sfackler** [comment]
@rust-lang/lang is this the right phrasing to use here? I'm not totally sure on the exact semantics we want to require WRT alignment.

**Comment by nikomatsakis** [comment]
This phrasing seems correct. Not sure if it is perfect, but it's not *wrong*.

**Pull request merged**
