### PR TITLE
improve compiler&tool documenting and re-enable cranelift on CI

### PR DESCRIPTION
**Pull request by onur-ozkan**
First commit addresses the linking issue with compiler crates. Second one ensures that compiler crates are linked correctly (with later commits we added this check for tools as well), allowing us to detect these hard-to-catch bugs on CI. Following three commits cherry-picked from #117328 to re-enable the Cranelift backend on CI.

More info: https://github.com/rust-lang/rust/issues/117430

cc @bjorn3 @RalfJung

### CODE REVIEW

**Comment by bjorn3** [comment]
Thanks a lot for working on this!

Could you add the following patch? I found this unintended change while I was (unsuccessfully) trying to figure out the doc issue too.

```patch
Author: bjorn3 <17426603+bjorn3@users.noreply.github.com>
Date:   Sat Nov 4 12:47:05 2023 +0000

    Don't disable inline asm usage in compiler-builtins when the cranelift backend is enabled
    
    This was a leftover from when inline asm wasn't universally supported by
    the cranelift backend yet. It would cause the optimized inline asm
    intrinsics to be avoided for the standard library distributed with
    rustup now that we build the cranelift backend by default on nightly for
    several tier 1 targets.

diff --git a/src/bootstrap/src/core/build_steps/compile.rs b/src/bootstrap/src/core/build_steps/compile.rs
index 1eed534150b..8ab0ef61c50 100644
--- a/src/bootstrap/src/core/build_steps/compile.rs
+++ b/src/bootstrap/src/core/build_steps/compile.rs
@@ -413,11 +413,6 @@ pub fn std_cargo(builder: &Builder<'_>, target: TargetSelection, stage: u32, car
 
     let mut features = String::new();
 
-    // Cranelift doesn't support `asm`.
-    if stage != 0 && builder.config.default_codegen_backend().unwrap_or_default() == "cranelift" {
-        features += " compiler-builtins-no-asm";
-    }
-
     if builder.no_std(target) == Some(true) {
         features += " compiler-builtins-mem";
         if !target.starts_with("bpf") {
```

**Comment by onur-ozkan** [comment]
> Thanks a lot for working on this!
> 
> Could you add the following patch? I found this unintended change while I was (unsuccessfully) trying to figure out the doc issue too.
> 
> ```diff
> Author: bjorn3 <17426603+bjorn3@users.noreply.github.com>
> Date:   Sat Nov 4 12:47:05 2023 +0000
> 
>     Don't disable inline asm usage in compiler-builtins when the cranelift backend is enabled
>     
>     This was a leftover from when inline asm wasn't universally supported by
>     the cranelift backend yet. It would cause the optimized inline asm
>     intrinsics to be avoided for the standard library distributed with
>     rustup now that we build the cranelift backend by default on nightly for
>     several tier 1 targets.
> 
> diff --git a/src/bootstrap/src/core/build_steps/compile.rs b/src/bootstrap/src/core/build_steps/compile.rs
> index 1eed534150b..8ab0ef61c50 100644
> --- a/src/bootstrap/src/core/build_steps/compile.rs
> +++ b/src/bootstrap/src/core/build_steps/compile.rs
> @@ -413,11 +413,6 @@ pub fn std_cargo(builder: &Builder<'_>, target: TargetSelection, stage: u32, car
>  
>      let mut features = String::new();
>  
> -    // Cranelift doesn't support `asm`.
> -    if stage != 0 && builder.config.default_codegen_backend().unwrap_or_default() == "cranelift" {
> -        features += " compiler-builtins-no-asm";
> -    }
> -
>      if builder.no_std(target) == Some(true) {
>          features += " compiler-builtins-mem";
>          if !target.starts_with("bpf") {
> ```

It gives "fatal: empty ident name (for <>) not allowed" when I try to `git am` on the patch. Is it ok for you to `git apply` it directly (it will show my name instead of yours on the commit)?

**Comment by bjorn3** [comment]
You could try `git commit --amend --author "bjorn3 <17426603+bjorn3@users.noreply.github.com>"` to change the author of the commit. If that doesn't work, plain `git apply` is fine with me.

**Comment by onur-ozkan** [comment]
Seems like rustdoc and rustdoc_json_types docs are also missing. Let's block the PR until I fix them.

@rustbot blocked

**Comment by Mark-Simulacrum** [comment]
In general r=me, but happy to see this build docs in CI (via a try build, likely with a change like this to re-enable docs: https://github.com/rust-lang/rust/pull/117349/commits/43f592f7b6b9dd323768195f5a77d0c8d5fa5776) before we land it. Happy to re-review with the extra fix you mention (but not strictly needed if similar changes).

**Comment by onur-ozkan** [comment]
Here the try build that includes compiler docs: https://ci-artifacts.rust-lang.org/rustc-builds/dc8c8311ce31a9e8e92f63c098be23b53f2bfc21/rustc-docs-nightly-x86_64-unknown-linux-gnu.tar.xz. However, it's missing rustdoc pages. I will trigger bors for another try build (I can't debug this build locally, working with a laptop atm) to see if this issue gets resolved. If not, I will continue working on it tonight or early tomorrow on my desktop (so I can debug things faster).

**Comment by onur-ozkan** [comment]
It's ready now! Here is the build https://ci-artifacts.rust-lang.org/rustc-builds/d4862cdec9eae562e5318823f9a7374b10d6acb6/rustc-docs-nightly-x86_64-unknown-linux-gnu.tar.xz

**Comment by onur-ozkan** [comment]
> Happy to re-review with the extra fix you mention (but not strictly needed if similar changes).

No strict changes have been applied. Also, we are able to catch missing-doc problem for compiler and tool crates (like here https://github.com/rust-lang-ci/rust/actions/runs/6760207883/job/18373700086#step:25:28933), so it should be fine to r.


@bors r=Mark-Simulacrum rollup=never

**Pull request merged**
