### PR TITLE
RawPthread should use libc::pthread_t

### LINKED ISSUE #61425: Incorrect type of stable std::os::raw pthread_t type on musl targets
POSIX's `pthread_t` is defined in `sys/types.h` and is an opaque type that identifies a thread. 

On `glibc` it is a `c_ulong`, on `musl` it is a `*mut __thread_handle`, etc. 

However, libstd's `pthread_t` is a type alias to `libc::c_ulong`, which is incorrect on musl. AFAICT, fixing this would be a backwards incompatible change.

### PR DESCRIPTION
**Pull request by gnzlbg**
Closes #61425 .

### CODE REVIEW

**Comment by alexcrichton** [comment]
This is a breaking change because the `libc` crate used here is unstable and so this transparent `type`def actually leaks the unstable-ness of the `libc` crate. The types in libstd are effectively deprecated though and only provided out of necessity where necessary and the ABI probably isn't incorrect even if the typedef is slightly wrong.

**Comment by gnzlbg** [comment]
On many targets, pthreads_t is not an usize, and in POSIX it is an opaque
handle, so this should be an opaque struct with an usize field instead of a
type alias, and yes, that’s a breaking change.

**Comment by alexcrichton** [comment]
Do any targets we compile to today and support libstd on have `pthread_t` not as `usize`? If so those platforms should be corrected, but otherwise I don't think it's worth changing this.

**Comment by gnzlbg** [comment]
All the musl targets for example.

**Comment by mati865** [comment]
Maybe that's the reason why Guard pages don't work on musl.

**Comment by gnzlbg** [comment]
Essentially, `pthread_t` is an opaque handle to a thread. In musl it is a [`*mut __pthread`](https://github.com/cloudius-systems/musl/blob/00733dd1cf791d13ff6155509cf139a5f7b2eecb/include/alltypes.h.in#L49). It is unclear to me how to give this the appropriate type without having to define and expose [`__pthread`](https://github.com/cloudius-systems/musl/blob/00733dd1cf791d13ff6155509cf139a5f7b2eecb/src/internal/pthread_impl.h#L13) somewhere, which is a private musl type that's subject to change.

**Comment by gnzlbg** [comment]
We could make this a `struct pthread_t(...private...)` that has the appropriate layout, and require people to `transmute` it to their platform specific type when using it on FFI. That would make all code using this portable.

Otherwise, with the type alias approach, code that uses this on FFI "as is", is just not portable, because when calling an FFI function that takes a handle (which is probably the only reason to ever want to take a handle), they are going to get type errors in some platforms, and the code will "just work" on others. 

Re-exporting the `libc::pthread_t` type kind of fixes this, but only when the same libc version is used that libstd provides.

**Comment by alexcrichton** [comment]
I'm not saying that the types all match up, but what I mean is if there are different types such that the ABI is different? If not I don't think this is a problem that should be handled at this time and we can deal with it when it happens for a platform. Almost all platforms can't change their `pthread_t` type and *maybe* musl is an exception since it's so often statically linked, but I sort of doubt that it'll change any time soon anyway...

Sure if we made this today we'd probably do something like:

```rust
#[repr(transparent)]
pub struct pthread_t { /* ... */ }
```

but remember that this dates back to before 1.0, and we surely didn't have `repr(transparent)` back then. We just did the best we could with what we had.

**Comment by gnzlbg** [comment]
> I'm not saying that the types all match up, but what I mean is if there are different types such that the ABI is different? 

`libstd` does not expose any raw FFI declaration that takes `pthread_t` as argument or returns `pthread_t`, so at least right now `libstd` wouldn't be exposing an unsound API even if this were to matter.

The question is whether a user wanting to, e.g., write an extern "C" declaration can use `RawPthread` in place of `pthread_t`. 

Technically, the ABIs are different, e.g., the `usize` used by glibc, etc. has Integral class (in the Amd64 SysV ABI) while the `*mut __pthread` used by musl has Pointer class. Whether this matters in practice in some architecture or not, I don't know (probably not? cc @rkruppe).

Independently of whether this matters, chances are that users are not going to write these declarations by hand (in which case, they are kind of responsible to verify that they work), but will use them via other libraries, like the `libc` crate. AFAICT nowhere it is guaranteed that `RawPthread == libc::pthread_t`, and IIUC we are explicitly saying here that this does not necessarily need to be the case. That is, code that wants to use `RawPthread` to call `libc`, should probably use a `transmute` to be portable:

```rust
let pthread: RawPthread = ...;
libc::foo(mem::transmute(pthread));
```

since nothing guarantees that `libc::pthread` and `RawPthread` have the same type.

---

Proposed solution: we could, for example, change the type of `RawPthread` to `*mut c_void` for `musl`. That would fix the ABI for those who are using `RawPthread` in their FFI declarations. Sadly, this is exactly what the `libc` crate does, so that will mean that `libc::foo(pthread)` will work on musl if we make this change. I say sadly, because if libc ever uses something other than `c_void` here (e.g. `extern type __pthread;` or similar for `musl`), code not using the `transmute` will break. 

So I don't know, maybe the right thing here is to just not do anything, leave this as an `usize`, and tell people that want to write code that's portable to `musl` to always use `mem::transmute` when calling `libc`.

**Comment by mati865** [comment]
See also https://github.com/rust-lang/libc/issues/1396

**Comment by gnzlbg** [comment]
I tend to agree with @alexcrichton here that this might not be worth changing or fixing. Not fixing this means that codes that assumes that they can pass a `RawPthread` to a `libc` API expecting a `libc::pthread_t` works on some platforms, but is not fully portable. Making that code portable, e.g., by using a `mem::transmute` is trivial. 

I'm closing this and I'll send a PR that, instead, changes this type to use `*mut c_void` for `musl` targets. That is, future Rust code using a sufficiently new libstd version will be able to avoid the `mem::transmute` on musl. That feels like a better path forward than leaking a `libc` type here, or doing an even larger breaking change like using a `repr(transparent)` struct here.

**Pull request closed without merging**
