### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by fmease**
Successful merges:

 - #122192 (Do not try to reveal hidden types when trying to prove Freeze in the defining scope)
 - #124840 (resolve: mark it undetermined if single import is not has any bindings)
 - #125622 (Winnow private method candidates instead of assuming any candidate of the right name will apply)
 - #125871 (Orphanck[old solver]: Consider opaque types to never cover type parameters)
 - #125893 (Handle all GVN binops in a single place.)
 - #125911 (delete bootstrap build before switching to bumped rustc)
 - #125918 (Revert: create const block bodies in typeck via query feeding)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=122192,124840,125622,125871,125893,125911,125918)

### CODE REVIEW

**Comment by fmease** [comment]
spurious @bors retry

**Comment by fmease** [comment]
@workingjubilee do you know which PR was responsible for this failure? Catching up rn with the queue etc.

**Comment by workingjubilee** [comment]
I just woke up.

**Comment by fmease** [comment]
no worries >.< same here

**Pull request closed without merging**
