### PR TITLE
(minor) correct filepath in test comment

### PR DESCRIPTION
**Pull request by pushkine**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can you move assoc-oddities-3 into src/test/ui/parser instead?

**Comment by JohnCSimon** [comment]
Ping from triage: 
@pushkine Can you address the reviewer's comments? thanks.

**Comment by JohnCSimon** [comment]
@pushkine 

FYI: when a PR is ready for review, post a message containing 
`@rustbot ready` to switch the PR to `S-waiting-on-review` so the PR appears in the reviewer's backlog.

@rustbot ready

**Comment by Mark-Simulacrum** [comment]
Can you squash the commits here into one? I tried to do that for you, but it looks like I can't push to your branch.

r=me with that done.

**Comment by pushkine** [comment]
This branch `patch-1` was created automatically using the web github file editor; I'm having issues working with it locally too. 

I think it's better if someone else makes a PR, the change consists of a moved file:
`src/test/ui/assoc-oddities-3.rs` → `src/test/ui/parser/assoc-oddities-3.rs`

Apologies for the confusion

**Pull request closed without merging**
