### PR TITLE
[watchos] Fix broken target arm64_32-apple-watchos

### PR DESCRIPTION
**Pull request by vladimir-ea**
Issue #111217

### CODE REVIEW

**Comment by workingjubilee** [comment]
Are we sure that this is the right fix? To my understanding, watchOS **is** an AArch64-ILP32 target. The [PR adding it to LLVM certainly thinks so](https://reviews.llvm.org/D69008).

**Comment by vladimir-ea** [comment]
> 

The 'proper' fix is here: https://github.com/gimli-rs/object/pull/542. 

This is a workaround to revert to the previous behaviour, but I guess the previous behaviour was wrong, although it did 'work' (in the sense that it was possible to build and run rust libraries for arm64_32-apple-watchos).

Mybe I should close this Pr and wait for the 'object' change?

**Comment by workingjubilee** [comment]
I don't think it would be invalid to choose to revert to the previous behavior. Partly because it's not required that the target work, so switching from busted (doesn't compile) to busted (compiles at all, but might miscompile a random program) is permitted, strictly speaking.

This does imply there's also no mandate to get this target up and running immediately, and we know that both behaviors we can choose from without updating `object` are incorrect. What you just said suggests to me your inclination is in fact to wait for the `object` fix. So I would encourage you to follow your inclination.

Which also means that if you _do_ want to land this, then as far as I am concerned, by all means.

**Comment by compiler-errors** [comment]
Not sure if I have a strong opinion about this, so

r? @workingjubilee

**Comment by vladimir-ea** [comment]
Closing this since the fix to 'object' has been released. See: #111413

**Pull request closed without merging**
