### PR TITLE
llvm-wrapper: adapt for LLVM 20 API changes

### PR DESCRIPTION
**Pull request by krasimirgg**
No functional changes intended.

Adapts llvm-wrapper for the LLVM commits https://github.com/llvm/llvm-project/commit/0f22d47a7a1f70ec77ea8ccdf08a6487827937db and https://github.com/llvm/llvm-project/commit/d6d8243dcd4ea768549904036ed31b8e59e14c73.

@rustbot label: +llvm-main
r? @nikic

### CODE REVIEW

**Comment by nikic** [comment]
Could you please squash the commits?

**Comment by krasimirgg** [comment]
> Could you please squash the commits?

done

**Comment by krasimirgg** [comment]
Updated for a second commit that changed the interface a bit https://github.com/llvm/llvm-project/commit/d6d8243dcd4ea768549904036ed31b8e59e14c73.

**Pull request merged**
