### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #91264 (Add macro support in jump to definition feature)
 - #98184 (Give name if anonymous region appears in impl signature)
 - #98269 (Provide a `PathSegment.res` in more cases)
 - #98277 (Fix trait object reborrow suggestion)
 - #98283 (Point at private fields in struct literal)
 - #98305 (prohibit_generics: don't alloc error string if no error emitted)
 - #98310 (rustdoc: optimize loading of source sidebar)
 - #98337 ([RFC 2011] Optimize non-consuming operators)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=91264,98184,98269,98277,98283,98305,98310,98337)

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@bors p=1000
@bors retry

tree closed due to [504 issue](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/504.20in.20CI)

**Comment by compiler-errors** [comment]
```
curl: (22) The requested URL returned error: 504 
Command failed. Attempt 3/5:
```

Guess not :/

**Comment by lqd** [comment]
a try build has succeeded a short while ago, so let's see if this has been fixed altogether

@bors retry

**Comment by JohnTitor** [comment]
Closing as outdated.

**Pull request closed without merging**
