### PR TITLE
Place TLS initializers with relocations in .tdata

### LINKED ISSUE #70673: ICE compiling alloc-tls
When running `cargo test --no-run` on [this commit](https://github.com/ezrosent/allocators-rs/tree/dec3843358c3a06b7823f76c50d192729332bad8/alloc-tls) of the `alloc-tls` crate, `rustc` panics:

```text
$ RUST_BACKTRACE=1 cargo test --no-run
   Compiling alloc-tls v0.1.0 (<redacted>/allocators-rs/alloc-tls)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`', src/librustc_codegen_llvm/consts.rs:438:21
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: std::panicking::begin_panic_fmt
   9: rustc_codegen_llvm::consts::<impl rustc_codegen_ssa::traits::statics::StaticMethods for rustc_codegen_llvm::context::CodegenCx>::codegen_static
  10: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  11: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  12: rustc::dep_graph::graph::DepGraph::with_task
  13: rustc_codegen_llvm::base::compile_codegen_unit
  14: rustc_codegen_ssa::base::codegen_crate
  15: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  16: rustc_session::utils::<impl rustc_session::session::Session>::time
  17: rustc_interface::passes::start_codegen
  18: rustc::ty::context::tls::enter_global
  19: rustc_interface::queries::Queries::ongoing_codegen
  20: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

### Version

Platform: macos

```text
$ rustc --version
rustc 1.44.0-nightly (f509b26a7 2020-03-18)
```

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Should fix #70673, although I'm not sure how to test this. Perhaps @joshlf could find a MCVE?

Also adds more context to the FIXME.

r? @oli-obk

### CODE REVIEW

**Comment by joshlf** [comment]
I'll try to pull this and build and test locally. If you're developing on a Mac, you could also just try building `alloc-tls` as described in the original issue, and see if it both fails before this change and succeeds with this change.

**Comment by joshlf** [comment]
OK, I built your patch locally, and with it, `cargo test` succeeds in building and running `alloc-tls`. That's not an MCVE, but hopefully that gives a bit more confidence that this is correct.

**Comment by oli-obk** [comment]
I'd assume

```rust
#![feature(thread_local)]

#[thread_local]
static A: &u8 = &42;

fn main() {
    dbg!(*A);
}
```

would be a minimal repro, unsure how to test this without a mac though.

The PR looks fine to me, so

@bors r+

**Comment by joshlf** [comment]
@oli-obk Right you are! Tested your proposed repro locally, and it both crashes the current compiler and also doesn't crash with this PR applied.

**Comment by oli-obk** [comment]
Superb! Thanks for checking

@ecstatic-morse if you get around to it before this PR goes to bors, please add the repro to the test suite, if not let's keep the issue open as `needs-test`

**Comment by ecstatic-morse** [comment]
Added the regression test.

@bors r=oli-obk

**Pull request merged**
