### PR TITLE
Fix `std` compilation error for wasi+atomics

### LINKED ISSUE #109727: `std` compilation error when compiling for `wasm32-wasi` with `-C target-feature=+atomics,+bulk-memory`
In order to reproduce:

```
cargo new hello-world
cd hello-world
RUSTFLAGS="-C target-features=+atomics,+bulk-memory" cargo +nightly build -Z build-std=std --target=wasm32-wasi
```

This leads to:

```
   Compiling std v0.0.0 (/home/tomaka/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std)
error[E0308]: mismatched types
  --> /home/tomaka/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/wasi/../unsupported/once.rs:63:28
   |
63 |                       inner: OnceState {
   |  ____________________________^
64 | |                         poisoned: state == State::Poisoned,
65 | |                         set_state_to: Cell::new(State::Complete),
66 | |                     },
   | |_____________________^ expected `OnceState`, found a different `OnceState`
   |
   = note: `OnceState` and `OnceState` have similar names, but are actually distinct types
note: `OnceState` is defined in module `crate::sys::wasi::once` of the current crate
  --> /home/tomaka/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/wasi/../unsupported/once.rs:8:1
   |
8  | pub struct OnceState {
   | ^^^^^^^^^^^^^^^^^^^^
note: `OnceState` is defined in module `crate::sys_common::once::futex` of the current crate
  --> /home/tomaka/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/once/futex.rs:31:1
   |
31 | pub struct OnceState {
   | ^^^^^^^^^^^^^^^^^^^^

error[E0616]: field `set_state_to` of struct `sys_common::once::futex::OnceState` is private
  --> /home/tomaka/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/wasi/../unsupported/once.rs:69:60
   |
69 | ...p_to = f_state.inner.set_state_to.get();
   |                         ^^^^^^^^^^^^ private field

Some errors have detailed explanations: E0308, E0616.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `std` due to 2 previous errors
```

This happens with both `nightly-2023-03-28` and `nightly-2023-02-08`.

### PR DESCRIPTION
**Pull request by tomaka**
Fix https://github.com/rust-lang/rust/issues/109727

It seems that the `unsupported/once.rs` module isn't meant to exist at the same time as the `futex` module, as they have conflicting definitions.

I've solved this by defining the `once` module only if `not(target_feature = "atomics")`.
The `wasm32-unknown-unknown` target [similarly only defines the `once` module if `not(target_feature = "atomics")`](https://github.com/tomaka/rust/blob/01c4f319276da912dd2be768ae0ce9857ad6bb63/library/std/src/sys/wasm/mod.rs#L69-L70).

As show in [this block of code](https://github.com/tomaka/rust/blob/01c4f319276da912dd2be768ae0ce9857ad6bb63/library/std/src/sys_common/once/mod.rs#L10-L34), the `sys::once` module doesn't need to exist if `all(target_arch = "wasm32", target_feature = "atomics")`.

### CODE REVIEW

**Comment by tomaka** [comment]
As a heads up, I'll probably open another PR afterwards to make `wasm32-wasi` work properly with atomics on. I'm still trying to figure out how to test my custom std build.

**Comment by jyn514** [comment]
@tomaka right now you need to also build the compiler to use a local std in a dev toolchain, see https://github.com/rust-lang/rust/issues/101691. you can run `x build std --stage 1` and that should work (follow the instructions in https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rustup-to-use-nightly). you can also set `download-rustc = true` to avoid having to build the whole compiler and that should work if you pass --stage 2 instead of 1.

**Comment by tomaka** [comment]
> I'll probably open another PR afterwards to make wasm32-wasi work properly with atomics on

Or maybe not.
Thread-safe wasi seems to be a ton of history, and it's a bit too overwhelming for me to figure out what the situation is.
Since (there seems to be some movement](https://github.com/rust-lang/compiler-team/issues/574), I'll just wait.

Nonetheless, this small PR is still worth merging, since it moves the situation from "doesn't compile" to "compiles".

**Comment by jyn514** [comment]
How can I test this change? `RUSTFLAGS_BOOTSTRAP="-C target-features=+atomics,+bulk-memory" x build std --target=wasm32-wasi` tells me I'm missing a wasi-root key:
```
thread 'main' panicked at 'Target "wasm32-wasi" does not have a "wasi-root" key', compile.rs:276:17
```

**Comment by jyn514** [comment]
ah, using `check` instead worked:
```
; RUSTFLAGS_BOOTSTRAP="-C target-feature=+atomics,+bulk-memory" x check std --target=wasm32-wasi
```

@bors r+ rollup

**Pull request merged**
