### PR TITLE
Add missing urls and small nits

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @frewsxcv

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]
@bors r+ rollup

**Comment by frewsxcv** [comment]
@bors r-

```
Linkcheck (x86_64-unknown-linux-gnu)

std/collections/struct.VecDeque.html:301: broken link - std/collections/struct.Drain.html

std/collections/vec_deque/struct.VecDeque.html:147: broken link - std/std/primitive.usize.html

std/collections/vec_deque/struct.VecDeque.html:302: broken link - std/std/mem/fn.forget.html

std/collections/vec_deque/struct.VecDeque.html:347: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:361: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:379: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:393: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:411: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:448: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:466: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:489: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:531: broken link - std/std/option/enum.Option.html

std/collections/vec_deque/struct.VecDeque.html:572: broken link - std/std/primitive.usize.html

thread 'main' panicked at 'found some broken links', /checkout/src/tools/linkchecker/main.rs:49
```

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by GuillaumeGomez** [comment]
Strange, it works when tested with the generated docs...

**Comment by frewsxcv** [comment]
It's probably because the docs are generated in two places. The `collections` crate and `std::collections`.

**Comment by GuillaumeGomez** [comment]
Makes sense. So I guess we're stuck in here. I'll try to solve this issue later on.

**Comment by steveklabnik** [comment]
Let's give this one a close, since it's old and has problems. Thanks @GuillaumeGomez !

**Pull request closed without merging**
