### PR TITLE
Remove some imports to the rustc crate

### PR DESCRIPTION
**Pull request by Centril**
- When we have `NestedVisitorMap::None`, we use `type Map = dyn intravisit::Map<'v>;` instead of the actual map. This doesn't actually result in dynamic dispatch (in the future we may want to use an associated type default to simplify the code).

- Use `rustc_session::` imports instead of `rustc::{session, lint}`.

r? @Zoxc

### CODE REVIEW

**Comment by Zoxc** [comment]
I guess `type Map = dyn intravisit::Map<'v>;` needs to be changed to `type Map = &'static dyn intravisit::Map<'static>;` once https://github.com/rust-lang/rust/pull/68944 lands.

**Comment by Centril** [comment]
@Zoxc I don't think that will work. I had to introduce `pub struct ErasedMap<'hir>(&'hir dyn Map<'hir>);` to make things compile again (but that won't actually work without `::None`, but that's OK for now). I think we need GATs to make dynamic dispatch actually work for `::OnlyBodies(...)`.

r? @Zoxc

**Pull request merged**
