### PR TITLE
Add cdb debug info tests for some frequently used data types

### PR DESCRIPTION
**Pull request by nanguye2496**
This PR add several debug info tests to guarantee that the displays of fixed sized arrays, range types, cell types, threads, locks, and mutexes in CDB are correct.

It also updates CDB tests for slices in pretty-std.rs after string visualization in WinDbg is fixed by this PR: rust-lang#81898.

### CODE REVIEW

**Comment by nanguye2496** [comment]
@Mark-Simulacrum : Hi Mark, I wonder if these tests should be in their own files or should be added to some existing debug info test files?

**Comment by Mark-Simulacrum** [comment]
I'm not sure I follow the question - this PR looks reasonable to me I guess? We generally don't worry too much about whether tests are grouped up into same file or separate files.

**Comment by nanguye2496** [comment]
> I'm not sure I follow the question - this PR looks reasonable to me I guess? We generally don't worry too much about whether tests are grouped up into same file or separate files.

Yes, I meant to add if I should put these tests into existing test files. Thanks for the quick reply. If there is no need for further changes, I will merge my commits.

**Comment by Mark-Simulacrum** [comment]
Please do, thanks. I expect it'll be a bit before I take a look at this in more detail, so no rush!

**Pull request closed without merging**
