### PR TITLE
Use stdio in UWP apps

### LINKED ISSUE #103233: std lib compile errors for uwp-windows-msvc targets
Building std library (-Zbuild-std) with nightly for uwp-windows-msvc targets has been failing with compile errors since around after 17/10/22

```rust
   Compiling panic_abort v0.0.0 (C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\panic_abort)
error[E0425]: cannot find function, tuple struct or tuple variant `GetConsoleMode` in module `c`
  --> C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\io.rs:99:11
   |
99 |     if c::GetConsoleMode(handle, &mut out) != 0 {
   |           ^^^^^^^^^^^^^^ not found in `c`

error[E0425]: cannot find function, tuple struct or tuple variant `GetConsoleMode` in module `c`
   --> C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\io.rs:112:19
    |
112 |             && c::GetConsoleMode(std_handle, &mut out) != 0
    |                   ^^^^^^^^^^^^^^ not found in `c`

```

I expected to see this happen:

Last successeful build on 16/10:

https://github.com/korejan/ALXR-nightly/actions/runs/3257338692/jobs/5348560568

Instead, this happened:

Lastest failed build:

https://github.com/korejan/ALXR-nightly/actions/runs/3277318460/jobs/5394484131

### Version it worked on

It most recently worked on: rustc 1.66.0-nightly (bf15a9e52 2022-10-14)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (b8b5caee0 2022-10-16)
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #103233

This has been supported since Windows 10.0.16299. See https://learn.microsoft.com/en-us/uwp/win32-and-com/win32-apis#apis-from-api-ms-win-core-console-l1-1-0dll

### CODE REVIEW

**Comment by ChrisDenton** [comment]
r? thomcc

**Comment by ChrisDenton** [comment]
Oh lol, I check on uwp but not on non-uwp.

**Comment by thomcc** [comment]
What version of Windows do we require for UWP?

**Comment by ChrisDenton** [comment]
Eh, we don't. It's a tier 3 target with nobody really responsible for it.

**Comment by thomcc** [comment]
Oh, it is tier 3. I thought it was 2 for some reason.

**Comment by thomcc** [comment]
So, this extremely owns, and it's great to clean up that cruft. I'm a bit hesitant about deciding to change the supported version of UWP without any other sign-off. Do we have any idea what the supported version was before this?

**Comment by ChrisDenton** [comment]
I don't think the supported version was ever defined. It was added way before the current target tier policy. I think its continued support relies on it either being low maintenance or some people coming along who are committing to support a UWP target (which is increasingly unlikely since the reports of its demise). Windows 10 1709 (which is what SDK 10.0.16299 targets) is already out of support so I personally don't think we should worry about it for a tier 3 target.

Though if you'd rather this be discussed more widely within libs or other teams I'm certainly not opposed.

**Comment by thomcc** [comment]
Hm, seems fair to me. Tier 3 target where we never defined the official support and the new version is still old enough that the OS vendor no longer supports it seems unlikely to cause issues. This simplifies the code a lot, which is really worthwhile for a target like that.

@bors r+

**Pull request merged**
