### PR TITLE
force "HEAD" for non-CI and `git_upstream_merge_base` for CI environment

### PR DESCRIPTION
**Pull request by onur-ozkan**
When rust-lang/rust is configured as remote, some of the git logic (for tracking changed files) that uses get_closest_merge_commit starts to produce annoying results as the upstream branch becomes outdated quickly (since it isn't updated with git pull). We can rely on HEAD for non-CI environments as we specifically treat bors commits as merge commits, which also exist on upstream. As for CI environments, we should use `git_upstream_merge_base` to correctly track modified files as bors commits may be in `HEAD` but not yet on the upstream remote.

This is also an alternative fix for https://github.com/rust-lang/rust/issues/129528 since https://github.com/rust-lang/rust/pull/131331 reverts the previous fix attempts.

### CODE REVIEW

**Comment by onur-ozkan** [comment]
> thread 'main' panicked at /checkout/src/tools/build_helper/src/git.rs:134:54:
called `Result::unwrap()` on an `Err` value: "Cannot find any suitable upstream master branch"

Hmm... More work 
.

@rustbot

**Comment by onur-ozkan** [comment]
[Added](https://github.com/rust-lang/rust/pull/131358/commits/1aa5675d890f4c13308197c9834059e7b466ebea) new CI step that prepares remote upstream and adjusted the PR description.

@rustbot ready

**Comment by Mark-Simulacrum** [comment]
r=me if you think this is ready

**Comment by RalfJung** [comment]
FYI apparently this had to be [reverted on the stable branch](https://github.com/rust-lang/rust/pull/135162#issuecomment-2573748112), so something is off here.

**Pull request merged**
