### PR TITLE
[experiment] Test perf when unconditionally `EvaluatedToUnknown` on inductive cycles

### PR DESCRIPTION
**Pull request by compiler-errors**
https://github.com/rust-lang/rust/pull/114023#issuecomment-1688514709

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
Uhh...? Doesn't look like caching is the problem here either.

**Comment by aliemjay** [comment]
I think we can get away with no spans in the lint given that we spell out the failing predicate in the error message.

**Pull request closed without merging**
