### PR TITLE
rustc: keep a Span for each predicate in ty::GenericPredicates.

### PR DESCRIPTION
**Pull request by eddyb**
This should allow finer-grained diagnostics, including migration suggestions for #54090.
(Note that I haven't changed most of the users of `predicates_of` to use the new spans)

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
@rust-timer build b52271b1bac1d1dcc839f7242fd40a5264df021a

**Comment by eddyb** [comment]
Results are in, and it looks mostly like noise, AFAICT.

**Comment by Mark-Simulacrum** [comment]
Yes, this is probably just noise.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@eddyb (needs rebase)

**Comment by eddyb** [comment]
Okay this keeps happening, am I missing something in the logs?
cc @rust-lang/infra

**Pull request merged**
