### PR TITLE
Promote loongarch64-unknown-none* to Tier 2

### PR DESCRIPTION
**Pull request by heiher**
MCP: https://github.com/rust-lang/compiler-team/issues/664

### CODE REVIEW

**Comment by heiher** [comment]
Could you please trigger a try build?

**Comment by heiher** [comment]
Could you please trigger a try build?

**Comment by RalfJung** [comment]
Potential blockers:
https://github.com/rust-lang/rust/issues/115509
https://github.com/rust-lang/rust/issues/115609

**Comment by heiher** [comment]
@wesleywiser gentle ping

**Comment by heiher** [comment]
Now, #115509 has been resolved, and #115609 is still in progress.

Quote @cuviper's [comment](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Promote.20loongarch64-unknown-none*.20to.20Tier.E2.80.A6.20compiler-team.23664/near/389694530):

```
the -linux-gnu target is already tier 2, so I don't see why those issues would block -none
```

I request that #115609 is not considered a blocker.

**Review by wesleywiser — APPROVED** [review]
The compiler team has approved the MCP for promotion to Tier 2 and these changes look correct to me but the Infra team needs to sign off on the addition to CI.

**Comment by xen0n** [comment]
Looks like this PR narrowly missed the beta promotion? Do we still want to stuff it into beta?

**Comment by xen0n** [comment]
> It did not miss -- it merged before the version bump in #116302, so it was still auto-added to milestone 1.74.0.
> 
> But generally, no, we would not do a beta backport for a feature like this, only for high-impact bugs. The point of having frequent releases is that it should not be a big deal to wait for the next one.

Thanks for the explanation! I checked the beta branch previously but didn't see this commit, hence the question. (I'd agree with waiting for the next release if the change actually missed 1.74.0, though.)

**Pull request merged**
