### PR TITLE
derive: use discriminant_value in #[derive(Hash)]

### LINKED ISSUE #21714: `derive(Hash)` on enum causes hash collision on 32-bit system
```Rust
use std::hash::{hash, SipHasher};

#[derive(Hash)]
enum E {
    A = 1,
    B,
}

fn main() {
    let a = hash::<_,   SipHasher>(&E::A);
    let b = hash::<_,   SipHasher>(&E::B);

    println!("{}, {}, {}", a, b, a == b);
}
```

```
$ rustc a.rs --target=i686-unknown-linux-gnu && ./a
13715208377448023093, 13715208377448023093, true
```

Output of `-Z unstable-options --pretty=expanded` is:

```Rust
// snip
#[automatically_derived]
impl <__S: ::std::hash::Writer + ::std::hash::Hasher> ::std::hash::Hash<__S>
 for E {
    #[inline]
    fn hash(&self, __arg_0: &mut __S) -> () {
        match (&*self,) {
            (&E::A,) => { ::std::hash::Hash::hash(&1, __arg_0); }
            (&E::B,) => { ::std::hash::Hash::hash(&1us, __arg_0); }
        }
    }
}
// snip
```

Here `A` uses `1` (is `i32`) and `B` uses `1us` for hashing, thus they collide if they have same bit representation.

(was potential issue of #18573)

### PR DESCRIPTION
**Pull request by durka**
derive: use discriminant_value in #[derive(Hash)]

Fixes #21714.

Spawned from #32139.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ b938cf96e0dbf8928833e823572e4461ee9975ac

eh we'll see how bors orders this

**Comment by durka** [comment]
My pre-emptive efforts to avoid this merge conflict failed.

**Comment by durka** [comment]
@alexcrichton do you think it's real this time?

**Comment by alexcrichton** [comment]
Hm yes, that looks legit... not sure how though?

**Comment by durka** [comment]
I mean, start is a lang item, and lang items are stored in an enum that
derives Hash, so it's somewhat possible-ish? Am I barking up the right tree?

**Comment by alexcrichton** [comment]
Perhaps, yeah. It seems specifically related to the `c-dynamic-dylib` test as it looked like that was also failing on OSX. I'd start out by poking around at the symbols and such and just see what's up

**Comment by durka** [comment]
More data! I ran `check-stage2-rmake TESTNAME=c-dynamic-dylib` on a 64-bit Arch system, configured with `--build=i686-unknown-linux-gnu --host=i686-unknown-linux-gnu`. On master the test passes; on this branch (rebased on master) it doesn't.

Master:

```
# nm i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib/bar | grep lang_start
         U _ZN2rt10lang_start20h853db53228ff7fabATzE
```

Branch:

```
# nm i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib/bar | grep lang_start
         U _ZN2rt10lang_start20hdfbcc23f8b0cf0d20UzE
```

cc @eddyb (we talked on IRC) any thoughts?

**Comment by eddyb** [comment]
@durka The symbols would differ anyway, had you changed a single non-whitespace thing in any library.

**Comment by durka** [comment]
@eddyb ok. So do you know what "symbol lookup error" actually means? Who is
looking up the symbol and why would they have the wrong hash?

**Comment by eddyb** [comment]
@durka The dynamic linker is looking up symbols and it only reports the first failure. Most likely *none* of the symbols in there match the `libstd` it's trying to use (run `ldd` on it to see a bunch of info).

`rt::lang_start` is a common first symbol to fail looking up, it *usually* means "you're using the wrong library".

Now, since this is a hashing change, it *could* mean "you were *always* using the wrong library but *somehow* stage1 `libstd` and stage2 `libstd` don't have the same symbol names".

Which, well, *totally* makes sense! You're changing how `libsyntax` behaves, but that only kicks in when building stage1 `librustc` and friends, so the stage1 compiler uses the old scheme, while stage2 has the new scheme, therefore the libs don't match.

The only thing you need to do is get this into a snapshot (sad that I haven't looked into this in-depth and right now we're building one...) with the test disabled, and re-enable it afterwards.

**Comment by eddyb** [comment]
@durka Alternatively, you could try looking at the invocation that compiles `bar` and what `LD_LIBRARY_PATH` is set to when it runs - they will likely be different.
If it's an obvious mismatch (stage1 vs stage2), you could maybe try fixing the one that is (mistakenly) using stage1.

**Comment by durka** [comment]
@eddyb yep, you're right. Here is the log:

```
make[1]: Entering directory '/root/rust/rust/work-derive/src/test/run-make/c-dynamic-dylib'
ccache gcc -Wall -Werror -g -fPIC -m32  -c -o /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib/libcfoo.o cfoo.c
ccache gcc -Wall -Werror -g -fPIC -m32  -o /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib/libcfoo.so /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib/libcfoo.o -shared
LD_LIBRARY_PATH="/root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib:/root/rust/rust/work-derive/i686-unknown-linux-gnu/stage2/lib:/root/rust/rust/work-derive/i686-unknown-linux-gnu/llvm/Release/lib:" /root/rust/rust/work-derive/i686-unknown-linux-gnu/stage2/bin/rustc --out-dir /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib -L /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib -C codegen-units=8 foo.rs -C prefer-dynamic
LD_LIBRARY_PATH="/root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib:/root/rust/rust/work-derive/i686-unknown-linux-gnu/stage2/lib:/root/rust/rust/work-derive/i686-unknown-linux-gnu/llvm/Release/lib:" /root/rust/rust/work-derive/i686-unknown-linux-gnu/stage2/bin/rustc --out-dir /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib -L /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib -C codegen-units=8 bar.rs
LD_LIBRARY_PATH="/root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib:/root/rust/rust/work-derive/i686-unknown-linux-gnu/stage1/lib/rustlib/i686-unknown-linux-gnu/lib:" /root/rust/rust/work-derive/i686-unknown-linux-gnu/test/run-make/c-dynamic-dylib/bar
```

So it compiles everything with stage2 libs and then runs with stage1 libs.

**Comment by durka** [comment]
And

```
[root@li1424-173 work-derive]# nm i686-unknown-linux-gnu/stage1/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-9026086f.so | grep lang_start
000db210 T _ZN2rt10lang_start20hbfee00d943992dc10UzE
[root@li1424-173 work-derive]# nm i686-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-9026086f.so | grep lang_start
000db280 T _ZN2rt10lang_start20hdfbcc23f8b0cf0d20UzE
```

clearly it's looking for the stage2 symbol. So the question is where the mistake is in the maze of makefiles.

**Comment by durka** [comment]
I think I found the mistake in the maze of makefiles. In this [block of vars](https://github.com/rust-lang/rust/blob/master/mk/main.mk#L493-L496), shouldn't it be `TLIB$(1)` instead of `TLIB1`?

**Comment by durka** [comment]
With the above change there are 19 failures in a full `make check`. Running it again to find out what they are.

**Comment by durka** [comment]
Failures:

```
test [pretty] pretty/derive-totalsum-attr.rs ... FAILED
test [pretty] pretty/derive-totalsum.rs ... FAILED
test [pretty] pretty/issue-15778-pass.rs ... FAILED
test [pretty] pretty/issue_16723_multiple_items_syntax_ext.rs ... FAILED
test [pretty] pretty/lint-plugin-cmdline-allow.rs ... FAILED
test [pretty] pretty/llvm-pass-plugin.rs ... FAILED
test [pretty] pretty/macro-crate-does-hygiene-work.rs ... FAILED
test [pretty] pretty/macro-crate-multi-decorator.rs ... FAILED
test [pretty] pretty/macro-crate-outlive-expansion-phase.rs ... FAILED
test [pretty] pretty/macro-crate.rs ... FAILED
test [pretty] pretty/mbe_matching_test_macro.rs ... FAILED
test [pretty] pretty/mir-pass.rs ... FAILED
test [pretty] pretty/plugin-args-1.rs ... FAILED
test [pretty] pretty/plugin-args-2.rs ... FAILED
test [pretty] pretty/plugin-args-3.rs ... FAILED
test [pretty] pretty/plugin-lib-ok-in-plugin.rs ... FAILED
test [pretty] pretty/plugin-plus-extern-crate.rs ... FAILED
test [pretty] pretty/roman-numerals-macro.rs ... FAILED
test [pretty] pretty/syntax-extension-with-dll-deps.rs ... FAILED
test result: FAILED. 32 passed; 19 failed; 7 ignored; 0 measured
```

**Comment by eddyb** [comment]
@durka Those are the "pretty" versions of `run-pass-fulldeps` aka `rpass-full`. If `make check-stage2-rpass-full` still works, that means the pretty tests are compiled/ran incorrectly.

**Comment by durka** [comment]
Look at the output though, it's complaining about plugins not found which
seems worrying.

**Comment by eddyb** [comment]
No, they're complaining about plugins having mismatched symbols (i.e. mismatched dynamic libraries), which is quite common - `make check-stage1-rpass-full` always fails because stage0 and stage1 don't have matching libraries.

**Comment by durka** [comment]
Yeah, this doesn't work.

[make clean && make check-stage2-rpass-full](https://gist.github.com/durka/c60db639715e4078f748)

**Comment by eddyb** [comment]
@durka That works if you do `check-stage2` because it builds `liblog` from another dependency.
Might as well fix that missing explicit dependency on `liblog` bug in `mk/crates.mk`.

**Comment by durka** [comment]
@eddyb added the dependency of compiletest on liblog, but https://gist.github.com/durka/e2a7812e1bc684c01304 :(

**Comment by eddyb** [comment]
@durka Well, if hashing behavior changed between stage1 and stage2, this might be unavoidable and the tests would have to be disabled until another snapshot with these changes comes along - or the tests could be ran at stage3? Not sure about that last part.

Alternatively, you could hunt down the enums with explicit discriminants that may end up in the symbol hash.

**Comment by durka** [comment]
Hunting down those enums sounds like the _right_ thing to do but I have no idea where to look. Running a full `check-stage2` right now just in case there is some weirdness going on with `rpass-full`.

**Comment by eddyb** [comment]
@durka I got confused, yet again! The symbol names don't have to be stable... they never were!
The answer to the question "shouldn't it be `TLIB$(1)` instead of `TLIB1`?" is "it should be one less for plugins" which is why I wanted to add proper plugin crates a year ago but that was a flop because of the ridiculous Makefile complexity.

This should be relatively easy in `rustbuild`, but for now... You have to find a compromise.

**Comment by pnkfelix** [comment]
@eddyb do the makefiles not yet have a way to refer to the stage preceding a given argument stage number? 

That may not be hard to hack up if need be ....

**Comment by eddyb** [comment]
> That may not be hard to hack up if need be ....

Any second spent touching the makefiles is better spent getting rustbuild up to feature parity, IMO.

**Comment by durka** [comment]
Given my change to `mk/main.mk` and rebased on #32293, `make check-stage2` passes.

**Comment by durka** [comment]
#32293 landed so I undid the rebase. Let's see if I did it right.

**Comment by durka** [comment]
I got a couple of failures in unrelated tests when running make check locally. A bunch of debuginfo failures on x64-darwin. But the bots seem to have not even gotten that far.

**Pull request merged**
