### PR TITLE
Rename and allow `cast_ref_to_mut` lint

### PR DESCRIPTION
**Pull request by Urgau**
This PR is a small subset of https://github.com/rust-lang/rust/pull/112431, that is the renaming of the lint (`cast_ref_to_mut` -> `invalid_reference_casting`).

BUT also temporarily change the default level of the lint from deny-by-default to allow-by-default until https://github.com/rust-lang/rust/pull/112431 is merged.

r? @Nilstrieb

### CODE REVIEW

**Comment by Nilstrieb** [comment]
cc @rust-lang/lang not sure whether this needs any signoff

**Comment by Urgau** [comment]
> cc @rust-lang/lang not sure whether this needs any signoff

I don't think it needs another T-lang signoff, this is purely compiler changes (well, the lint level change is technically T-lang purview but it's deny->allow and it's temporary).

Anyway, I think it's better to get this PR merged into 1.72 and if T-lang wants to do another signoff they can do it in the other PR.

**Comment by Nilstrieb** [comment]
Question for T-lang: is the lint rename fine? (And also additionally, is T-lang input required for these sort of things?).

**Comment by scottmcm** [comment]
Lints aren't "one-way doors", so personally I'm not concerned here.  The worst thing that can happen is we end up with another lint name in the renamed or removed tables.  To me, the important thing is that lang agrees that whatever lang thing being linting about really is something that people oughtn't ever be doing -- which might be easy if it's definitely UB -- and if the compiler diagnostics folk think a different name is better for the lint then go for it.  (If we already have a bunch of things named `invalid` and this is like those, then great.)

I'll leave it nominated for the team to discuss Tuesday in case someone has strong objections to the name, but *I* don't think you need to wait for that input.

**Comment by Nilstrieb** [comment]
Looks like there were no objections and I agree, the new name is better.
@bors r+

**Comment by Nilstrieb** [comment]
I also want to nominate this for beta backport so that people don't need to deal with the lint rename by getting the new name directly. The lint does have false positives on master so it's possible that people would want to allow it. That said, maybe the rename coming to stable together with the false positive fixes would make people remove the allows.
I have no strong recommendation whether to accept but I think it's worth nominating.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-08-03/near/381497457)

@rustbot label +beta-accepted

**Pull request merged**
