### PR TITLE
Make `private_in_public` compatibility lint deny-by-default

### PR DESCRIPTION
**Pull request by petrochenkov**
In accordance with the [plan](https://internals.rust-lang.org/t/fcp-for-various-future-compatibility-warnings/3590/5?u=petrochenkov).

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Sorry for the delay in reviewing! I've been traveling but I ought to be around tomorrow. Two quick questions:

1. What issue does this link to again? I think once we move to error, it'd be nice to link to a good issue.
2. Should we keep this in "lint but error" mode, or should we just modify the code to emit a hard error? I had generally envisioned the former as a kind of "optional step" but maybe it's a good middle-ground, and it makes it easy to link to an existing issue with more details for the people who will all of a sudden start noticing what's going on.

**Comment by petrochenkov** [comment]
>What issue does this link to again? I think once we move to error, it'd be nice to link to a good issue.

This lint is old, it doesn't have a dedicated tracking issue. It "links" to `--explain E0446` at the moment.
I'll probably create one, the lint is still going to exist for at least few releases.

>Should we keep this in "lint but error" mode, or should we just modify the code to emit a hard error?

I want it to be a deny-by-default lint for at least one cycle, this is a change with large impact after all.
This is supposed to be merged before the upcoming beta, so I will (partially) turn it into error after that.
`deny` lints can uncover some unexpected cases, for example, nobody reads warnings in tests, so this change has caught a couple of private-in-public errors in our test suite.

`private_in_public` is a facade for several kinds of errors, the largest and the oldest ones are in `rustc_privacy`, some more recent ones are in resolve (e.g, `extern crate foo; pub use foo;`), they will stay lints for some more time, but will benefit from being `deny` by default too.

**Comment by nikomatsakis** [comment]
@petrochenkov 

>  I'll probably create one, the lint is still going to exist for at least few releases.

Sounds good. The main reason I didn't r+ right away is that I wanted to see a link to an issue that offers a good explanation of what's going on. Do you want to create such an issue first, or merge this PR first?

**Comment by petrochenkov** [comment]
@nikomatsakis 
Updated with a reference to https://github.com/rust-lang/rust/issues/34537

**Comment by nikomatsakis** [comment]
@petrochenkov ok -- but it seems like you suggested we wait until https://github.com/rust-lang/rust/pull/34193 is resolved, no?

**Comment by petrochenkov** [comment]
@nikomatsakis 
Sorry for the delay, I've updated https://github.com/rust-lang/rust/pull/34193, now everything should be in place.

**Comment by nikomatsakis** [comment]
r=me, but still waiting until #34193 merges

**Comment by petrochenkov** [comment]
Rebased.
ping @nikomatsakis, https://github.com/rust-lang/rust/pull/34193 has landed

**Comment by petrochenkov** [comment]
Spurious failure.

**Pull request merged**
