### PR TITLE
Emit an error when `rustc_doc_primitive` has an unknown value

### PR DESCRIPTION
**Pull request by tgross35**
Currently rustdoc silently does nothing. Change this to raise an error instead.

### CODE REVIEW

**Comment by tgross35** [comment]
> rustbot has assigned @fmease.

Right choice again 😄

**Review by fmease — APPROVED** [review]
Attribute validation usually happens way earlier in the pipeline, e.g., in `rustc_ast_passes` or `rustc_passes` for several reasons but given `PrimitiveType` is defined in `rustdoc`, this location makes sense. The error won't trigger on `rustc` invocations but hey, this error is meant for contributors only.

I have one nitpick, namely turning the `struct_span_err` into a `span_bug!`.
The latter is meant for contributors which is the case here. Note that that's fine because we are allowed to ICE under `rustc_attrs` (or under any internal feature for that matter).

`struct_span_err` is meant to get removed at some point to be fully replaced with the translatable diagnostic APIs -- and we definitely don't want to make this error translatable.

**Comment by fmease** [comment]
r=me with `struct_span_err` turned into a `span_bug!` and with the test removed (I don't think it's worth keeping it & normalizing its stderr).

@bors delegate+

**Comment by tgross35** [comment]
Even easier, thanks for the quick review!

@bors r=fmease rollup

**Pull request merged**
