### PR TITLE
docs: Vectors are to slices what String is to &str

### PR DESCRIPTION
**Pull request by nhowell**
This just doesn't sound right to me. I believe it's meant to say "arrays" instead of "slices". Slices aren't even mentioned until later in the page.

Please let me know if I'm just misunderstanding. Thanks

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is incorrect. Arrays own their data. `&str`s, like slices, do not.

**Comment by nhowell** [comment]
@steveklabnik I think this sentence needs reworded or explained then. I took it to refer to the growable aspect of Vectors compared to arrays, like Strings are to &str, and not about data ownership.

**Comment by steveklabnik** [comment]
Let's shop it in this PR then. Do you have a suggestion?

**Comment by nhowell** [comment]
Yeah, let me think it over and update this later (on mobile right now). Thanks.

**Comment by nhowell** [comment]
@steveklabnik What if we remove the sentence from this paragraph:

> A *vector* is a dynamic or "growable" array, implemented as the standard
library type [`Vec<T>`](../std/vec/) (we'll talk about what the `<T>` means
later). Vectors always allocate their data on the heap. ~~Vectors are to slices
what `String` is to `&str`.~~ You can create them with the `vec!` macro:

and incorporate it into this one?

> A *slice* is a reference to (or "view" into) an array. They are useful for
allowing safe, efficient access to a portion of an array without copying.
**In this way, slices are to arrays what `&str` is to `String`.** For example, you
might want to reference just one line of a file read into memory.
By nature, a slice is not created directly, but from an existing variable.
Slices have a length, can be mutable or not, and in many ways behave like
arrays:

Also, let me know if that's incorrect in any way.

**Comment by steveklabnik** [comment]
I like it. I would still say "vector" and not "array" in the revision: A `String` is a wrapper around `Vec<u8>`, just like `str` is a wrapper around `[u8]`. But seems good!

**Comment by alexcrichton** [comment]
r? @steveklabnik 

(reassigning)

**Comment by steveklabnik** [comment]
@nhowell are you interested in keeping up with this PR?

**Comment by nhowell** [comment]
Yeah, I still would like to change this, and especially with the new TOC, it just doesn't seem to belong there. But I haven't thought of the best way to word it/move it to yet. Saying vector instead of array there just doesn't fit with the paragraph... I'll have something this weekend.

**Comment by steveklabnik** [comment]
Okay :+1:

**Comment by nhowell** [comment]
I was just looking over the book again before doing anything with this PR and noticed that you've updated the way you present it. I quite like it now, so, I'll go ahead and close this PR.

Thanks!

**Comment by steveklabnik** [comment]
Ah yes! This PR did impact doing that though, so thanks :)

**Pull request closed without merging**
