### PR TITLE
Fixes ICE in sparc64 ABI (Issue #115399)

### PR DESCRIPTION
**Pull request by psumbera**
Fixes #115399

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
We don't need to add a test for this?

**Comment by psumbera** [comment]
> We don't need to add a test for this?

I hope test isn't necessary.

**Comment by TaKO8Ki** [comment]
@psumbera In my opinion, it would be great to add a ui test like:

https://github.com/rust-lang/rust/blob/a04d56b36d8f634abd7bdd64dd859a30655f1818/tests/ui/abi/compatibility.rs#L22.

**Comment by psumbera** [comment]
> @psumbera In my opinion, it would be great to add a ui test like this. Could you add it?
> 
> https://github.com/rust-lang/rust/blob/a04d56b36d8f634abd7bdd64dd859a30655f1818/tests/ui/abi/compatibility.rs#L22

I think I will need some help with it. The issue was that rustc hit assertion during compilation with certain rust code. What exactly should I do?

**Comment by TaKO8Ki** [comment]
@psumbera Could you read this documentation?

https://rustc-dev-guide.rust-lang.org/tests/ui.html

**Comment by Dylan-DPC** [comment]
@psumbera any updates on this? thanks

**Comment by psumbera** [comment]
> @psumbera any updates on this? thanks

Unfortunatelly no. The proposed fix doesn't seem to cover all situations as mentioned here:
https://github.com/rust-lang/rust/issues/115399#issuecomment-1866119045

Since then I haven't got enough time to focus on the issue.

(if it's matter we can close this pull request for now, while the bug remains open)

**Comment by Dylan-DPC** [comment]
Closing this as author has said they don't have time to complete this and current solution isn't acceptable

**Pull request closed without merging**
