### PR TITLE
rustdoc-json: Document and Test that args can be patterns.

### PR DESCRIPTION
**Pull request by aDotInTheVoid**

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
CraftSpider has retired from the rustdoc team (https://github.com/rust-lang/team/pull/897), rerolling review.

r? rustdoc

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
@pietroalbini Do you know why CraftSpider is still being picked by the bot?

@aDotInTheVoid: Thanks!

@bors r+ rollup

**Comment by aDotInTheVoid** [comment]
> Do you know why CraftSpider is still being picked by the bot?

CraftSpider was picked on Oct 14, when they were still on the team/r+ roation AFAIKT

**Comment by GuillaumeGomez** [comment]
Oh I see. Didn't notice this PR was open for so long...

**Pull request merged**
