### PR TITLE
check git in bootstrap.py

### PR DESCRIPTION
**Pull request by guanqun**

### CODE REVIEW

**Comment by guanqun** [comment]
in some cases when my path is misconfigured. the error output is very confusing. we'd better check it beforehand.

**Comment by Mark-Simulacrum** [comment]
Do we require git even when building from a tarball? I'd sort of expect that we shouldn't, though perhaps we do today...

**Comment by Mark-Simulacrum** [comment]
r=me with that question answered in positive, otherwise I think we should not do this

**Comment by guanqun** [comment]
good point. I see that at least in bootstrap.py file, git is only used for updating the submodules. so the place to check it is moved. please help review again.

**Comment by guanqun** [comment]
the tarball from release tab doesn't compile out of box as it's missing these submodules.

**Comment by mati865** [comment]
@guanqun I think they aren't meant to be used like that. You can find proper tarballs here https://forge.rust-lang.org/other-installation-methods.html#source

**Comment by Mark-Simulacrum** [comment]
r=me with tidy fixed, I think it's fine to land this if it only runs when we'd run git anyway

**Comment by guanqun** [comment]
Thank you @Mark-Simulacrum  The tidy error is fixed.

**Pull request merged**
