### PR TITLE
Disable Azure Pipelines except for macOS

### PR DESCRIPTION
**Pull request by emilyalbini**
Following up on https://github.com/rust-lang/rust/pull/74565, this PR disables most of Azure Pipelines except for macOS auto builds, practically switching us to GitHub Actions :tada: 

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by pietroalbini** [comment]
Let's see if this breaks try builds.

@bors try

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
@bors r+ 

Thanks! Excited for us to have faster queue times.

**Comment by pietroalbini** [comment]
@bors p=10

Let's get this merged soon!

**Comment by pietroalbini** [comment]
@bors treeclosed=1000

```
{
  "message": "API rate limit exceeded for user ID 7378925.",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

(the message is not shown in CI, made a request manually with highfive's token)

**Pull request merged**
