### PR TITLE
Alloc features cleanup

### PR DESCRIPTION
**Pull request by m-ou-se**
This sorts and categorizes the `#![features]` in `alloc` and removes unused ones.

This is part of #87766

The following feature attributes were unnecessary and are removed:

```diff
// Library features:
-#![feature(cow_is_borrowed)]
-#![feature(maybe_uninit_uninit_array)]
-#![feature(slice_partition_dedup)]

// Language features:
-#![feature(arbitrary_self_types)]
-#![feature(auto_traits)]
-#![feature(box_patterns)]
-#![feature(decl_macro)]
-#![feature(nll)]
```

### CODE REVIEW

**Comment by bjorn3** [comment]
> ```diff
> -#![feature(nll)]
> ```

These exist to test full nll mode. https://github.com/rust-lang/rust/pull/66498#issue-341885059

**Comment by m-ou-se** [comment]
If we really need to keep that in `alloc` and/or `core`, we should put a clear comment why it's there. Is there any documentation of what enabling this feature will change?

**Comment by bjorn3** [comment]
NLL is currently in migration mode by default, which still uses the old AST based regionck. `#![feature(nll)]` completes the transition to full NLL mode. https://github.com/rust-lang/rust/issues/57895 is the tracking issue for completing the transition. One of the last remaining blockers for completing the transition is https://github.com/rust-lang/rust/pull/86700 I think. By the way libstd used to require it at least at some point: https://github.com/rust-lang/rust/issues/66494#issuecomment-554761463

**Comment by yaahc** [comment]
LGTM once the NLL bit is sorted.

**Comment by dtolnay** [comment]
@bors delegate+

Looks good after a rebase and putting back `#![feature(nll)]`.

**Pull request merged**
