### PR TITLE
Update RLS and Rustfmt

### LINKED ISSUE #62803: `rls` no longer builds after rust-lang/rust#62679
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#62679, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @Xanewok, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Zoxc, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by Xanewok**
Supersedes https://github.com/rust-lang/rust/pull/62537.
Closes #62803.

Fixes fallout after https://github.com/rust-lang/rust/pull/62679.

r? @ghost

### CODE REVIEW

**Comment by Xanewok** [comment]
Except version bumps and internal cleanings from #62537 this also includes the fix for the tool breakage and updated itertools to 0.8 so I'll go ahead and r+ it myself per Centril's suggestion in the last PR:

@bors r+ p=1

**Comment by Xanewok** [comment]
Rebased, failure is spurious (`2019-07-19T18:33:41.2430692Z fatal: could not read Username for 'https://github.com': No such device or address`) so...

@bors r+

**Comment by Xanewok** [comment]
Rebased

@bors r+

**Comment by Xanewok** [comment]
Rebased :sob: 

@bors r+

**Comment by Centril** [comment]
@Xanewok Should this be r-ed?

**Comment by Xanewok** [comment]
Unfortunately `client_deglob` and `client_find_definitions` still remain spurious, despite reducing the general fail rate considerably. Would you mind keeping this in the queue? I'd like to fix the broken toolstate since #62679.

**Comment by Centril** [comment]
Sure, if it is spurious it's fine to keep it in. (I synced homu an ~hour ago so I'm checking all PRs to see if some PR got accidentally re-added to the queue)

**Comment by Xanewok** [comment]
Spurious failure strikes again...
@bors r+

**Comment by Xanewok** [comment]
I ignored the spurious `client_deglob` upstream (should be the last spurious test) so let's give it another try...

@bors r+

**Comment by Xanewok** [comment]
```
aws: command not found
```

@bors retry

**Comment by Xanewok** [comment]
AWS CLI not found again. @pietroalbini @Centril am I doing something wrong here or is it just spurious?

**Comment by ehuss** [comment]
See #62967, it just stopped my PR as well.

**Comment by Xanewok** [comment]
Thanks for the heads up, was beginning to wonder if it’s something on my side.

@bors retry

**Comment by Xanewok** [comment]
Rebased. Bumping prio slightly since it's P-high https://github.com/rust-lang/rust/issues/62803

@bors r+ p=2

**Comment by Xanewok** [comment]
Oh boy, this is fun - rustc-ap-arena v491 now doesn't build since `RawVec` doesn't have `cap` (was renamed to `capacity` in a recent PR) and now needs a coordinated update together with Racer and Rustfmt
cc @kngwyu @topecongiro

**Comment by topecongiro** [comment]
Updating rustfmt is blocked by https://github.com/rust-lang/rust/pull/63036.

**Comment by topecongiro** [comment]
@Xanewok Published rustfmt 1.4.0.

**Comment by kngwyu** [comment]
Looks we cannot build rustc-ap-* 541.0 by `rustc 1.38.0-nightly (4560cb830 2019-07-28)`

**Comment by topecongiro** [comment]
Looks like https://github.com/rust-lang/rust/pull/62550 introduced a breaking change to the Rust syntax. I will update the version of rustc-ap-syntax and release rustfmt 1.5.0 asap, though it is unlikely to happen before this weekend.

**Comment by topecongiro** [comment]
Released rustfmt 1.4.1 using rustc-ap-syntax 542.0.0. @rchaser53 thank you for the quick fix!

**Comment by Xanewok** [comment]
Thanks everyone for such quick response! I updated both libraries in RLS and also include now Rustfmt bump not to deduplicate rustc-ap-* libs (we use 542 now).

To not stall this any longer and since it fixes two tools now...
@bors r+ p=10

**Comment by Xanewok** [comment]
cc @Centril for the prio bump

**Comment by Xanewok** [comment]
Unified `crossbeam-utils` features used in tools and verified the fix locally:

@bors r+

**Comment by SimonSapin** [comment]
The rollup #63134 failed, most likely because of this PR:

```
2019-07-30T13:49:41.8022060Z duplicate artifacts found when compiling a tool, this typically means that something was recompiled because a transitive dependency has different features activated than in a previous build:
2019-07-30T13:49:41.8022610Z 
2019-07-30T13:49:41.8022740Z the following dependencies are duplicated although they have the same features enabled:
2019-07-30T13:49:41.8023220Z the following dependencies have different features:
2019-07-30T13:49:41.8024190Z   crossbeam-utils 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)
2019-07-30T13:49:41.8025120Z     `rustfmt` additionally enabled features {"nightly"} at "/Users/vsts/agent/2.154.3/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libcrossbeam_utils-6c8cd67381bcfe02.rlib"
2019-07-30T13:49:41.8026150Z     `cargo` additionally enabled features {} at "/Users/vsts/agent/2.154.3/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libcrossbeam_utils-683657da3f16e5d0.rlib"
2019-07-30T13:49:41.8026300Z 
2019-07-30T13:49:41.8027090Z to fix this you will probably want to edit the local src/tools/rustc-workspace-hack/Cargo.toml crate, as that will update the dependency graph to ensure that these crates all share the same feature set
```

**Comment by Xanewok** [comment]
@SimonSapin yep, fixed in https://github.com/rust-lang/rust/pull/62805/commits/1b61db706a3e16493b18de5ce9c70fc8335d72e2 (already being tested)

**Comment by ehuss** [comment]
Just a heads up, the toolstate publish isn't working for linux, so it will still appear to be build-fail until it's fixed.

**Comment by est31** [comment]
@ehuss what do you mean by that? Will the next nightly be available for rustup users who have rls enabled?

**Comment by ehuss** [comment]
I'm not 100% certain how rustup works, but I think it should be OK.  I think the main consequence is that https://rust-lang-nursery.github.io/rust-toolstate/ will show it is still failing.  I believe it will be fixed soon, regardless.

**Pull request merged**
