### PR TITLE
Add the x86_64-gnu-stable builder

### LINKED ISSUE #11: Run test suite with `--release-channel=stable`
This will help us catch failures that occur when the channel is not nightly, like in https://github.com/rust-lang/rust/pull/84950.

We could also run tests for `beta`, but there are diminishing returns there.

### PR DESCRIPTION
**Pull request by emilyalbini**
During the 1.52 release process we had to deal with some commits that passed the test suite on the nightly branch but failed on the beta or stable branch. In that case it was due to some UI tests including the channel name in the output, but other changes might also be dependent on the channel.

This commit adds a new CI job that runs the Linux x86_64 test suite with the stable branch, ensuring nightly changes also work as stable. To ensure the new job works the following other changes are present:

* The `ui-fulldeps/session-derive-errors.rs` test has been disabled on beta and stable, which required adding support for `// ignore-{channel}` and `// only-{channel}`.
* The `rustdoc/intra-doc/field.rs` has been fixed.

r? @Mark-Simulacrum 
fixes https://github.com/rust-lang/release-team/issues/11

### CODE REVIEW

**Comment by pietroalbini** [comment]
Ok this should be ready for review.

r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
This looks OK to me. Hopefully we won't have cases of someone gating behavior on beta vs. stable...

@bors r+ rollup=iffy

**Pull request merged**
