### PR TITLE
Fix enum_glob_use in rustc_lexer

### PR DESCRIPTION
**Pull request by practicalrs**
Hi,

This PR fixes the following clippy warnings

```
warning: usage of wildcard import for enum variants
 --> compiler/rustc_lexer/src/unescape.rs:7:5
  |
7 | use Mode::*;
  |     ^^^^^^^ help: try: `Mode::{Byte, ByteStr, CStr, Char, RawByteStr, RawCStr, RawStr, Str}`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_glob_use
  = note: requested on the command line with `-W clippy::enum-glob-use`

warning: usage of wildcard import for enum variants
  --> compiler/rustc_lexer/src/lib.rs:37:5
   |
37 | use self::LiteralKind::*;
   |     ^^^^^^^^^^^^^^^^^^^^ help: try: `self::LiteralKind::{Byte, ByteStr, CStr, Char, Float, Int, RawByteStr, RawCStr, RawStr, Str}`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_glob_use

warning: usage of wildcard import for enum variants
  --> compiler/rustc_lexer/src/lib.rs:38:5
   |
38 | use self::TokenKind::*;
   |     ^^^^^^^^^^^^^^^^^^ help: try: `self::TokenKind::{And, At, Bang, BlockComment, Caret, CloseBrace, CloseBracket, CloseParen, Colon, Comma, Dollar, Dot, Eq, Gt, Ident, InvalidIdent, InvalidPrefix, Lifetime, LineComment, Literal, Lt, Minus, OpenBrace, OpenBracket, OpenParen, Or, Percent, Plus, Pound, Question, RawIdent, RawLifetime, Semi, Slash, Star, Tilde, Unknown, UnknownPrefix, UnknownPrefixLifetime, Whitespace}`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_glob_use
```

Best regards,
Michal

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I don't think this is an improvement tbh

**Comment by workingjubilee** [comment]
I'm forced to agree, especially with the `use self::TokenKind::*;` change.

**Comment by practicalrs** [comment]
Ok, let's close this one.

**Comment by compiler-errors** [comment]
Hi @practicalrs: It seems like you've been opening a lot of PRs of the flavor "fix {one single clippy lint} for {one single compiler crate}". I think that's likely to lead to some churn. 

If you're interested in fixing some clippy lints, I encourage you to do so at the level of the *whole* compiler, but also please be mindful that most clippy fixes are likely not really improvements to readability and style, so I'd probably encourage you to batch these together and be incredibly scrutinizing about the changes before putting them up for review :)

**Pull request closed without merging**
