### PR TITLE
Add test for #24389

### LINKED ISSUE #24389: Self should be consistently usable within method bodies
The following code will fail to compile at "Self::new()" with the message, "error: failed to resolve. Use of undeclared type or module `Self`"
```rust
struct Foo;

impl Foo {
    fn new() -> Self { Foo }
    fn bar() { Self::new(); }
}
```

While either of the following will work:
```rust
    fn bar() { <Self>::new(); }
    fn bar() { let x: Self = Foo::new(); }
```

The first example should compile as-is.

### PR DESCRIPTION
**Pull request by apasel422**
Closes #24389.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 47c176e9d22827744c0afa866450a8bd2bc9575c

Thanks!

**Comment by apasel422** [comment]
The test failure is unrelated to this PR.

**Comment by apasel422** [comment]
Why did auto-mac-32-opt succeed with this but auto-linux-64-opt did not?

**Comment by apasel422** [comment]
It's unclear why this test failed in the first place (it's not related to the warning on stderr), so it seems to be spurious.

**Comment by alexcrichton** [comment]
@bors: retry

(signal 11 spurious failure)

**Comment by Diggsey** [comment]
:+1:

**Pull request merged**
