### PR TITLE
[beta] Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
1 commits in 7e484fc1a766f56dbc95380f45719698e0c82749..d65d197ad5c6c09234369f219f943e291d4f04b9 2022-10-27 15:20:57 +0000 to 2022-11-15 21:30:31 +0000
- [beta-1.66] Backport fix for git2 safe-directory disable (rust-lang/cargo#11381)

r? @ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
@ehuss please help check I do this correctly. Thank you!

**Comment by weihanglo** [comment]
I think it's fine to merge.

@bors r+

**Comment by ehuss** [comment]
Sorry for the delay, unfortunately this won't merge without some more work on the beta branch. There have been some changes that prevent it from compiling.

@bors r-

I'm hoping to get this rolled up into #104447.

**Comment by Mark-Simulacrum** [comment]
Yes, we'll roll this up, going to close this PR for now.

**Pull request closed without merging**
