### PR TITLE
[experiment] perf-test smallvec optimizations

### PR DESCRIPTION
**Pull request by the8472**
r? @ghost

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Looks like you added an old version of rust-analyzer to pr or something like that..?

**Comment by the8472** [comment]
"old" being a few hours old here. I de-submoduled it because cargo couldn't vendor it with the custom overrides that I want to test and the overrides can't be applied to a submodule.

But something went wrong somewhere.

**Comment by the8472** [comment]
redid the commits, locally it cleanly merges into master now.

@bors retry

**Comment by the8472** [comment]
Redoing the 2nd perf run now that #90996 has been merged. if that still skews more negative than the first one then my initial attempt will have been the best one and I'll propose that for inclusion in the small-vec crate.

@bors try @rust-timer queue

**Comment by Mark-Simulacrum** [comment]
Going to close this as a no-longer-relevant (I presume) perf experiment.

**Pull request closed without merging**
