### PR TITLE
PGO: Disable instrumentation pre-inlining pass by default.

### PR DESCRIPTION
**Pull request by michaelwoerister**
LLVM's IR-level instrumention feature (which is used for PGO) has a pre-inlining pass. This pass performs some initial inlining and other small cheap optimizations before adding the instrumentation counters to the IR. For C++ code compiled with Clang this seems to have pretty significant benefits (see e.g. [what happens](https://treeherder.mozilla.org/perf.html#/comparesubtest?originalProject=try&newProject=try&newRevision=abae111e31f27defe907c3f7449ace5d21f213ef&originalSignature=1905608&newSignature=1905608&framework=10&originalRevision=58d40a0c84accb901e96aae12dfe0f97ab1d007b) if pre-inlining is turned off for C/C++ code in Firefox). For Rust code, however, this does not seem to be true. 

So far, PGO seems to be rather ineffective for Rust code in general, but with pre-inlining enabled, it seems to even be detrimental to performance in most cases. E.g. when optimizing the `regex` benchmarks with PGO, I get the following [results](https://github.com/michaelwoerister/rust-pgo-investigation/blob/2d2ff6397d3019fd3a329aa0b09bd62fd81150a5/average-speedups-of-pgo.txt):

| PGO Settings | Speedup |
|---------------------------------------|----------------------------|
| pre-inlining threshold=75 (default) |  0.976 |
| pre-inlining threshold=300 | 0.997 |
| pre-inlining threshold=150 | 1.001 |
| pre-inlining disabled | 1.009 |

So PGO is able eke out a ~1% speedup, if pre-inlining is disabled, but if it is enabled, the benchmarks run usually slower than without PGO. For doing benchmarks with FF, the picture is similar.

PGO's effectiveness with Rust should be investigated more deeply in any case, but for now this PR defaults to disable pre-inlining. It can be enabled on a case by case basis via `-Cllvm-args`, if needed.

This PR also removes the `-Z disable-instrumentation-preinliner` flag since this setting is already available via `-C llvm-args=-disable-preinline` (even on stable).

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
r=me but also cc @alexcrichton

**Comment by michaelwoerister** [comment]
Actually, cc @rust-lang/compiler and @rust-lang/compiler-contributors -- in case somebody is interested in PGO.

**Comment by cramertj** [comment]
cc @petrhosek

**Comment by cramertj** [comment]
Did you happen to record any binary size numbers in addition to the raw perf stats you posted above? In our own testing, we've seen C++ binaries drop 5-7% when PGO is enabled.

**Comment by michaelwoerister** [comment]
The binaries in my test seem to be almost the same size:
```
no PGO:             13,205,680 bytes
PGO (default):      13,205,632 bytes
PGO (no-preinline): 13,205,656 bytes
```
which is kind of suspicious ...

**Comment by JohnCSimon** [comment]
Ping from triage 

@michaelwoerister @petrhosek @cramertj @eddyb 
Any update on this?

Thanks.

**Comment by michaelwoerister** [comment]
I'm closing this for now since I've gotten interesting leads on the llvm-dev mailing list on how to further investage PGO effectiveness. Thanks for the feedback!

**Pull request closed without merging**
