### PR TITLE
Subtree update of `rust-analyzer`

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
I don't really understand how `unexpected_cfgs` got enabled without causing a mess in the RA subtree.

**Comment by Urgau** [comment]
> I don't really understand how `unexpected-cfgs` got enabled without causing a mess in the RA subtree.

Glancing at all the `cfg`s used by r-a, I didn't see any "custom" cfgs (except in tests, but those probably don't count). So I'm not surprised it didn't cause any issues.

As for the `rust_analyzer` cfg, it is very recent (less than 2 weeks by the commit date), so yeah it will either need to be added to the exception list or changed to something else (preferably a Cargo feature).

**Comment by lnicola** [comment]
You're right,  the support for these was added back in September, but they weren't actually used until last week.

**Review by onur-ozkan — APPROVED** [review]
> r? @onur-ozkan for https://github.com/rust-lang/rust/commit/b8390da7e75e52cc3fe9c7e4a3493b04a7e8a85b.

LGTM

**Comment by lnicola** [comment]
I don't really understand how the steps work. Is there an easy way to pass an extra `--cfg` into https://github.com/lnicola/rust/blob/b8390da7e75e52cc3fe9c7e4a3493b04a7e8a85b/src/bootstrap/src/core/build_steps/dist.rs#L1132?

**Comment by onur-ozkan** [comment]
> I don't really understand how the steps work. Is there an easy way to pass an extra `--cfg` into https://github.com/lnicola/rust/blob/b8390da7e75e52cc3fe9c7e4a3493b04a7e8a85b/src/bootstrap/src/core/build_steps/dist.rs#L1132?

You don't need to do that.

In Rustc mode
https://github.com/rust-lang/rust/blob/57010939ed1d00076b4af0ed06a81ec69ea5e4a8/src/bootstrap/src/core/build_steps/dist.rs#L415-L416

`RustAnalyzerProcMacroSrv` is compiled which then uses `rust_analyzer` cfg. Adding `(Some(Mode::Rustc), "rust_analyzer", None)` should fix that.

**Comment by onur-ozkan** [comment]
Need `(Some(Mode::ToolStd), "rust_analyzer", None)` too for

https://github.com/rust-lang/rust/blob/21cce21d8c012f14cf74d5afddd795d324600dac/src/bootstrap/src/core/build_steps/tool.rs#L688-L699

**Pull request merged**
