### PR TITLE
Make `NonNull::new` `const`

### PR DESCRIPTION
**Pull request by lilasta**
Tracking issue: #93235

### CODE REVIEW

**Comment by woppopo** [comment]
r? @oli-obk

(is rust-highfive stopped...?)

**Comment by oli-obk** [comment]
lgtm, please add tests of this function being used in a const item (one for Some and one for None).

**Comment by woppopo** [comment]
Added.

**Comment by oli-obk** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
