### PR TITLE
Dogfood CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse in bootstrap

### LINKED ISSUE #108766: Dogfood CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse in bootstrap
Sparse-registry was recently stabilized and we've started testing it in CI: https://github.com/rust-lang/rust/pull/107543

It would be nice to also use it when running locally so that compile times are a bit faster (and to increase coverage). The code to change lives somewhere around https://github.com/rust-lang/rust/blob/390551716a5f16907e48b21934a66090fd8ef78d/src/bootstrap/builder.rs#L1889

### PR DESCRIPTION
**Pull request by KittyBorgX**
Fixes #108766

### CODE REVIEW

**Comment by albertlarsan68** [comment]
The current fix does not fixes the problem, since the registry cache is mainly updated when building bootstrap itself.
Thus the correct fix would be to set it in the Python side of things.

**Comment by ehuss** [comment]
I'm concerned that setting this will prevent users from configuring it themselves. That is, this would prevent it from allowing users to force it to some other value.

The default will be changing in nightly soon. That means that this won't be needed in 6 weeks. Would it be OK to wait until then?

**Comment by ozkanonur** [comment]
> That means that this won't be needed in 6 weeks. Would it be OK to wait until then?

I think so. But it would be better to hear confirmation from @jyn514

**Comment by jyn514** [comment]
👍 seems good to me

**Pull request closed without merging**
