### PR TITLE
Refactorings in preparation for #70951

### PR DESCRIPTION
**Pull request by cjgillot**
Split out of #70951 to investigate perf.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
Ok, so at least we know it's not related to moving it across crates, but just due to the dynamic dispatch (or most likely, due to the lack of inlining)

**Comment by bjorn3** [comment]
Big regressions of up to 7%.

**Comment by bjorn3** [comment]
Huge regressions of up to 7%.

**Comment by oli-obk** [comment]
The current changes look like a small improvement across the board. Though afaict there's no more trait objects now, but just a splitting of the traits used for generics?

**Comment by cjgillot** [comment]
I used this PR to bisect the changes. The most interesting half, is missing, explaining the perf results.

**Comment by cjgillot** [comment]
Without using a trait object.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Without using a trait object.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Reimplementation before introducing the trait object.
@bors try @rust-timer queue

**Comment by bjorn3** [comment]
Mixed small (up to 1%) improvements and regressions.

**Comment by JohnCSimon** [comment]
@Rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by Dylan-DPC** [comment]
@cjgillot if you can resolve the conflicts we can push this forward

**Comment by cjgillot** [comment]
Now that #81855 has been merged, and its perf has been validated:
@bors try @rust-timer queue

**Pull request closed without merging**
