### PR TITLE
Outdent example, preserving nested fence

### PR DESCRIPTION
**Pull request by felixrabe**

### CODE REVIEW

**Comment by felixrabe** [comment]
Still waiting for a local `./x.py doc` to produce a result... First time actually running that script, I thought it would just build the docs :/

**Comment by felixrabe** [comment]
`./x.py doc` finished in ~45 min. Local `build/x86_64-apple-darwin/doc/rustdoc/what-is-rustdoc.html` looks fine.

**Comment by steveklabnik** [comment]
Can you show me a screenshot? I'm surprised this works, though maybe that's because this was written before we used pulldown-cmark, and it can handle it.

**Comment by felixrabe** [comment]
The CommonMark spec allows for nested fenced code blocks by requiring the same amount (`{3,}`) of opening and closing `` ` ``'s or `~`'s: https://spec.commonmark.org/0.29/#fenced-code-blocks.

So this is what the rendered output looks for me:

Screen Shot 2019-04-24 at 13 09 09

And this is the exactly same code (from `` ````text `` to `` ```` ``), inlined in this comment:

````text
# Docs

This is a project to test out `rustdoc`.

[Here is a link!](https://www.rust-lang.org)

## Subheading

```rust
fn foo() -> i32 {
    1 + 1
}
```
````

**Comment by felixrabe** [comment]
Btw, to render `` ````text `` or `` ` `` in Markdown as I did above, use double backticks and a space around the code, e.g.:

    `` ````text ``

and

    `` ` ``

(Found by looking at https://spec.commonmark.org/0.29/changes.html#part-7.)

**Comment by Dylan-DPC** [comment]
ping from triage @steveklabnik any updates?

**Comment by steveklabnik** [comment]
@bors: r+ rollup

sorry for taking so long here!

**Pull request merged**
