### PR TITLE
impl Fn/FnMut/FnOnce for Arc/Rc

### PR DESCRIPTION
**Pull request by Centril**
This PR introduces the ability to have `Rc/Arc<F>: Fn(A) -> B where F: Fn(A) -> B` and `Rc/Arc<Fn(A) -> B`.

This was previously tried (and failed) in https://github.com/rust-lang/rust/pull/34118#issuecomment-228922628 due to breakage with crater. But now that the new edition is approaching we might want to try this in edition 2018. We should probably do a new crater run to see how much the breakage has changed since the previous attempt.

cc @aturon

### CODE REVIEW

**Comment by kennytm** [comment]
Could you clarify how Rust 2018 is going to make this work? Both Rust 2015 and 2018 editions are going to share the same standard library.

**Comment by Centril** [comment]
@kennytm That's true. Honestly not sure at all here; but @aturon seemed to agree that we should try something, so I defer to them ;) And if we can't, we'll have to skip it.

**Comment by shepmaster** [comment]
Ping from triage, @aturon — we eagerly await your review!

**Comment by aturon** [comment]
@rust-lang/infra Requesting crater run please!

**Comment by Mark-Simulacrum** [comment]
This probably cannot land as-is: the impls introduced appear to conflict with tokio-tls which is quite widely used: Crater results are at: http://cargobomb-reports.s3.amazonaws.com/pr-49224/index.html. 'Blacklisted' crates (spurious failures etc) can be found [here](https://github.com/rust-lang-nursery/crater/blob/master/config.toml). If you see any spurious failures not on the list, please make a PR against that file.

(interested observers: Crater is a tool for testing the impact of changes on the crates.io ecosystem. You can find out more at the [repo](https://github.com/rust-lang-nursery/crater/) if you're curious)

**Comment by pietroalbini** [comment]
Ping from triage @aturon! What should we do with this PR?

**Comment by alexcrichton** [comment]
Unfortunately that's a pretty high number of regressions, so I'm going to close this.

**Comment by alexcrichton** [comment]
Unsure, I just know we can't land this with so many known regressions.

**Comment by Centril** [comment]
@alexcrichton Agreed on that :)

**Pull request closed without merging**
