### PR TITLE
rustdoc: Reset the title when pressing the back button

### LINKED ISSUE #26673: rustdoc: Pressing back after search doesn't reset <title>
1. Navigate to https://doc.rust-lang.org/nightly/std/index.html
2. Type a query in the search bar (wait for results to appear)
3. Take note of the title of the search results
3. Press 'back' and notice how the title doesn't reset

### PR DESCRIPTION
**Pull request by nhowell**
Fixes #26673

### CODE REVIEW

**Comment by BigBoneDaddy** [comment]
Does this support multiple forwards and backs in a row?

**Comment by nhowell** [comment]
Hi, @BigBoneDaddy. I'm not certain, but the existing code uses replaceState when you change your search query so there's only ever one level of forward/back to go anyway. Or is there something else that I'm missing?

**Comment by BigBoneDaddy** [comment]
@nhowell Ok sorry just checking. I am not web technology guru I more systems programmer so I just want to confirm it work like I thought maybe it work. 100 thank to you for hard work on this! :100:

**Comment by steveklabnik** [comment]
Thanks @nhowell ! Sorry about the delay :(

**Comment by nhowell** [comment]
No worries. Thanks!

**Pull request merged**
