### PR TITLE
Fix documentation example in the book

### PR DESCRIPTION
**Pull request by ollie27**
The code sections shouldn't be inside a ```text block.

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is on purpose, actually. See the line right before: it's trying to show the literal syntax.

**Comment by ollie27** [comment]
But if you put
```
    ```text
    let x = 5;
    # let y = 6;
    # println!("{}", x + y);
    ```
```
It will result in the lines beginning with # being included which is what I thought this example was tying to avoid.

I guess if "our source code" is supposed to mean the source code of `documentation.md` then I think the ```` ```text ```` lines inside this block need changing to ```` ```rust ````.

**Comment by steveklabnik** [comment]
> It will result in the lines beginning with # being included which is what I thought this example was tying to avoid.

This example is trying to show you how to use the `#`s. So in this part of it, they need to be shown.

**Comment by steveklabnik** [comment]
That said you are right that

> I think the ```text lines inside this block need changing to ```rust.

They should be. Would you mind updating this PR to change that?

**Comment by ollie27** [comment]
Updated.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

Thanks for sticking with me :)

**Pull request merged**
