### PR TITLE
Remove perl as a dependency

### PR DESCRIPTION
**Pull request by richo**
There's only one build-critical path in which perl is used, and it was to do a text replacement trivially achievable with sed(1).

I ported the indenter script because it [appears to be used](https://github.com/rust-lang/rust/blob/master/src/librustc/util/common.rs#L60-70), but removed check links because it appears to be entirely out of date.

### CODE REVIEW

**Comment by richo** [comment]
Not sure what exploded here. I'll poke.

**Comment by frewsxcv** [comment]
Can https://github.com/rust-lang/rust/issues/12913 be closed now that this has merged?

**Comment by richo** [comment]
Yes! Thanks, that's a great catch.

**Pull request merged**
