### PR TITLE
Deny merge in CI take 2

### PR DESCRIPTION
**Pull request by Noratrieb**
Taking up #105058 which was reverted in #106320 because it caused build failures in bors builds.

https://github.com/rust-lang-ci/rust/actions/runs/3810081096/jobs/6481927643#logs

### CODE REVIEW

**Comment by ehuss** [comment]
I think this may not work if the contributor adds any commits *after* the merge commit, since the fetch depth is only 2. That might be unlikely, but something to be aware of.

**Comment by jyn514** [comment]
> I think this may not work if the contributor adds any commits _after_ the merge commit, since the fetch depth is only 2. That might be unlikely, but something to be aware of.

False negatives are ok, at worst it means a reviewer needs to tell the author to get rid of the merge, like today. False positives are worse since tidy gives a hard error.

That said we can increase the fetch depth if we need to, I expect ~20 commits will be enough in practice. But let's avoid doing that until we figure out why this broke when it merged last time.

**Comment by Mark-Simulacrum** [comment]
It's probably worth seeing if enabling GitHub's "require linear history" would give a visual warning here. I think it is maybe true that bors can be setup to bypass that, in which case we might get something relatively reasonable.

**Comment by jyn514** [comment]
@Mark-Simulacrum I think you and Pietro are the only ones with access to those settings - do you have time to look into it? I can see about trying this on a personal repo if not so I can link you the exact setting.

We should also make sure that *only* shows up for merge commits and not when the merge-base for the PR is based on a old commit of master.

**Comment by Mark-Simulacrum** [comment]
I can, yes. I'll need a chunk of time around a bors merge so we can fix bors if it goes wrong; it might be best to do it on some other repo (e.g., crater?) that also uses bors.

I can try to make that happen soon.

**Comment by Mark-Simulacrum** [comment]
It looks like getting bors to bypass that might be trickier than expected -- so let's assume that strategy won't work for now.

**Comment by Nilstrieb** [comment]
gonna close this, either someone else picks it up or i may continue at some point

**Pull request closed without merging**
