### PR TITLE
submodules: update clippy from f1753522 to 6ce78d12

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Should fix clippy toolstate

Changes:
````
wildcard_match_arm: Update lint count.
wildcard_match_arm: add nesting issue to known.
wildcard_match_arm: lint only enum matches.
wildcard_match_arm: update ui test stderr
wildcard_match_arm: format test.
wilcard_match_arm: run rustfmt.
wildcard_match_arm: add lint properly.
wildcard_match_arm: rename function.
wildcard_match_arm: add simple ui test.
wildcard_match_arm: expand lint scope.
Change match_wild lint name to WILDCARD_MATCH_ARM.
Add match_wild lint (#3649).
fetch_prs_between: add .sh file ending
cargo fmt
Update various docs
Use built-in entry_fn detection over self-built
cargo fmt
Reorganize conditionals: Run faster checks first
Maybe fix ICE?
Add initial version of const_fn lint
Fix `unit_arg` false positive
Rustfmt
Check hypothetically failing conversion
Remove tests for deprecated items
Update more changed iterator paths
Atomics constants are now handled by the deprecation lint
Update changed iterator paths
Update const slice processing
update test stderr
run cargo fmt
rustup https://github.com/rust-lang/rust/pull/57907/
Fix documentation for `slow_vector_initialization`
rustup https://github.com/rust-lang/rust/pull/57726
Remove unsafe_vector_initialization from added lints
Prevent incorrect cast_lossless suggestion in const_fn
Incorporate review suggestions
Fix dogfood tests on Appveyor
test(versioncheck): Use .no_deps()
test(versioncheck): Fix version equality check
chore(cargo/dependencies/cargo-metadata): Upgrade to 0.7.1
dependencies: update itertools from 0.7 to 0.8
Add script to fetch GitHub PRs between two commits
gitattributes: Treat .fixed files as rust files
Update changelog with all changes since 0.0.212
Fix `expect_fun_call` lint suggestions
````

r? @oli-obk

### CODE REVIEW

**Comment by Centril** [comment]
Adjusting queue order for rollups:
@bors p=2

**Comment by matthiaskrgr** [comment]
rebased

**Comment by matthiaskrgr** [comment]
Clippy needs to be fixed again...

**Comment by matthiaskrgr** [comment]
I pulled in an rls update since this needs update as well

**Comment by matthiaskrgr** [comment]
looks spurious

**Comment by matthiaskrgr** [comment]
I removed the rls update again..

I wonder if if the rls hang has something to do with debug assertions...
r? @oli-obk

**Comment by matthiaskrgr** [comment]
That's strange, I can't see any changes to Cargo.lock in the recent PRs...

**Comment by mati865** [comment]
PR merged 7 hours ago made small changes to the lockfile and bors is very picky about merge conflicts.
I bet it surfaced so late because bors was about to run tests. You will have to rebase it and somebody needs to reapprove it.

**Pull request merged**
