### PR TITLE
Clarify the workings of StringReader in the lexer

### PR DESCRIPTION
**Pull request by nnethercote**
In a lexer you want it to be extremely clear what the current character is, as well as those before and after it. The current code and comments in StringReader don't achieve this: `curr` refers to the current character, but so does `last_pos`; `pos` refers to the next character; and `col` refers to the current character but its comment says it refers to the next character.

This PR renames some of these fields and does some related clean-ups. This makes the lexer code easier to understand and marginally faster.

### CODE REVIEW

**Comment by sanxiyn** [comment]
This changes public API of libsyntax, so it needs special handling. cc #31645.

**Comment by nnethercote** [comment]
@sfackler: 7 day review ping!

**Comment by nnethercote** [comment]
So the patches above do these renamings:
```
pos      -> next_pos
last_pos -> curr_pos
col      -> curr_col
```
Another possibility is this:
```
pos      -> next_pos
last_pos -> pos
col unchanged
curr     -> ch
```
The idea being that we avoid `curr_` prefixes, instead making them implicit. The reason I suggest this is that it would match `Parser`, which has `token` and `span` which refer to the current token and span. (`Parser` also has `last_span` and `last_token_kind` which should be renamed as `prev_span` and `prev_token_kind` respectively.)

**Review by eddyb — APPROVED** [review]
@Manishearth r=me

**Comment by nnethercote** [comment]
Oh... I pulled out two of these commits in #36921, and I want to redo the renaming in the way I mentioned above, and I want to do some similar renamings in the parser.

So: thank you for the review, @eddyb, but I'd like to hold off from landing these commits in their current form. (Well, they need a rebase, but I'm going to change them in a bigger way.) I will file a new PR for that to make things clearer. Apologies for the lack of clarity.

**Comment by nnethercote** [comment]
I'm going to reuse this PR for my updated commits.

**Comment by nnethercote** [comment]
Nope, that didn't work because I did the new patches in a different local clone. So I opened #36969.

**Pull request closed without merging**
