### PR TITLE
Fix excessive initialization and reads beyond EOF in `io::copy(_, Vec<u8>)` specialization

### LINKED ISSUE #117545: Exponential Performance Regression in Rust 1.73 Read API from BorrowedCursor::ensure_init
Reported by a lz4_flex user https://github.com/PSeitz/lz4_flex/issues/147

### Code
I created a small repo to demonstrate on a minimal example.
https://github.com/PSeitz/copy_regression_1.73

BorrowedCursor::ensure_init from this PR https://github.com/rust-lang/rust/pull/97015 seems exhibit exponential cost. 

The program creates a Vec and reads it in chunks of 32kb. Size is specified as a command line argument (100MB-400MB).

`time cargo run --release 100000000` (If your default is 1.73)
```
Executed in    3.84 secs    fish           external
   usr time    3.80 secs  268.00 micros    3.80 secs
   sys time    0.03 secs  262.00 micros    0.03 secs
```
`time cargo run --release 200000000`
```
Executed in   16.90 secs    fish           external
   usr time   16.82 secs  626.00 micros   16.82 secs
   sys time    0.04 secs    0.00 micros    0.04 secs
```
`time cargo run --release 400000000`
```
Executed in   72.84 secs    fish           external
   usr time   72.65 secs  586.00 micros   72.65 secs
   sys time    0.06 secs  138.00 micros    0.06 secs
```

`time cargo +1.72 run --release  100000000`
```
Executed in   57.23 millis    fish           external
   usr time   16.83 millis  404.00 micros   16.43 millis
   sys time   37.02 millis    0.00 micros   37.02 millis

```

`time cargo +1.72 run --release  400000000`
```
Executed in  257.30 millis    fish           external
   usr time  150.46 millis  477.00 micros  149.98 millis
   sys time  106.64 millis  112.00 micros  106.53 millis
```

### PR DESCRIPTION
**Pull request by the8472**
fixes #117545 and https://github.com/bczhc/bzip3-rs/pull/8

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+

I wonder if the detection here should be publicly available on BorrowedBuf or similar - seems like it might be useful elsewhere too. But shouldn't block this.

**Comment by a1phyr** [comment]
Side question: is there a reason why this is not implemented as `reader.read_to_end(self)` ?

**Comment by the8472** [comment]
Good point, they're quite similar though they contain some different optimizations. It probably make sense to unify them.

**Comment by the8472** [comment]
beta-nominated [on behalf of this comment](https://github.com/rust-lang/rust/issues/117545#issuecomment-1800844427)

**Comment by cuviper** [comment]
This was backported during the 1.74.0 stable promotion in #117843, and it already landed in what is now 1.75-beta, so there's nothing more to do here.

@rustbot label -beta-nominated

**Pull request merged**
