### PR TITLE
[beta] rustdoc revert deref recur

### PR DESCRIPTION
**Pull request by pnkfelix**
beta-targetted version of PR #84867 

Its description is transcribed below.

----

As discussed here: https://github.com/rust-lang/rust/issues/82465#issuecomment-829290384, Revert PR #80653 to resolve issue #82465.

Issue #82465 was we had stopped including certain trait implementations, namely implementations on an imported type of an imported trait *instantiated on a local type*. That bug was injected by PR #80653.

Reverting #80653 means we don't list all the methods that you have accessible via recursively applying `Deref`.

[Discussion in last week's rustc triage meeting](https://zulip-archive.rust-lang.org/238009tcompilermeetings/19557weekly2021042954818.html#236680594) led us to conclude that the bug was worse than the enhancement, and there was not an obvious fix for the bug itself. So for the short term we  remove the enhancement, while in the long term we will work on figuring out a way to have our imported trait implementation cake and eat it too.

### CODE REVIEW

**Comment by pnkfelix** [comment]
(similar tidy issues to what I did in PR #84867; fixing now.)

**Comment by jyn514** [comment]
r=me with CI passing

**Comment by Mark-Simulacrum** [comment]
Thanks! Bundled into https://github.com/rust-lang/rust/pull/84864.

**Pull request closed without merging**
