### PR TITLE
Clarify undefined behaviour in binary heap, btree and hashset docs

### PR DESCRIPTION
**Pull request by Wilfred**
Previously, it wasn't clear whether "This could include" was referring to logic errors, or undefined behaviour. Tweak wording to clarify this sentence does not relate to UB.

### CODE REVIEW

**Comment by SkiFire13** [comment]
I don't think this makes it more clear, quite the opposite, at first glance I thought the "behaviour" you added was referring to the "undefined behaviour".

You should also change the docs for `HashMap`, `HashSet`, `BTreeMap` and `BTreeSet` since they all include that same sentence

**Comment by kpreid** [comment]
> I don't think this makes it more clear, quite the opposite, at first glance I thought the "behaviour" you added was referring to the "undefined behaviour".

How about wording like this? “The behavior resulting from such a logic error is not specified (it could include panics, incorrect results, aborts, memory leaks, or non-termination) but will not be undefined behavior.”

(I think it would also be good to link “undefined behavior” to some page explaining what undefined behavior is, since this might be the first time someone has encountered the concept, and it might not be obvious that “undefined behavior” is a specific formal term.)

**Comment by Mark-Simulacrum** [comment]
Agreed that this seems like a good clarification.

It may make sense to extract the shared language somewhere in the root of the library docs as a general statement we can link to in terms of what logic errors can do; that way we can avoid updating N places each time and potentially expand a little on the paragraph. std's top level doc comment seems like a reasonable place to add that section, I guess.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@Wilfred can you please address the comments from the reviewer? Thank you.

**Comment by Wilfred** [comment]
OK, I've updated the docs in all four places using the wording suggested by @kpreid :). The patch isn't identical in all those files as they've used different line lengths, so I followed the convention in each file.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Rebased and approved, thanks!

**Pull request merged**
