### PR TITLE
Implement placement-in protocol for `LinkedList`

### PR DESCRIPTION
**Pull request by apasel422**
CC #30172.

r? @pnkfelix 
CC @nagisa

### CODE REVIEW

**Comment by pnkfelix** [comment]
I am not a member of the libs team, but my intuition is that the name "emplace_back` is longer than necessary; we don't have to follow C++'s precedent here. 

Unfortunately deciding on a name for such methods does imply a bikeshedding discussion. . .

**Comment by pnkfelix** [comment]
Cc @rust-lang/libs

**Comment by apasel422** [comment]
@pnkfelix Agreed. Unfortunately, `front` and `back` are already taken.

**Comment by petrochenkov** [comment]
|||
|-------|-------|
|`place(index)`, `front()`, `back()` | when `front` and `back` are not taken|
|`place(index)`, `front_place()`, `back_place()` | when `front` and `back` are taken|

**Comment by alexcrichton** [comment]
From a library API perspective this seems fine to me for now, we'll likely want to do a sweeping audit whenever we consider this for stabilization (aligning names for example), but for now having this as unstable seems fine to me!

**Comment by apasel422** [comment]
@alexcrichton So should I update any of the names for now?

**Comment by alexcrichton** [comment]
Oh I guess we don't have any prior art here (sorry I thought we had these implemented for vectors).

In terms of naming, we'll probably want to have a convention like iterators where it's super straightforward and you don't have to think about it much. Along those lines maybe something like:

* All "placer" methods have some shared word in them. Perhaps `place` or `emplace` (I don't have much of an opinion either way)
* Each collection may have a suite of placer methods, and if so they've all got some other prefix/suffix indicating how the placement is happening. Again, on whether it's a prefix/suffix I don't have much of an opinion
* The returned struct has the exact same name as the method, but in camel case

So I guess within those guidelines, I'd recommend renaming the returned structs, and otherwise keeping the names as is or the `front_place`/`back_place` suggestions @petrochenkov mentioned.

**Comment by apasel422** [comment]
Updated.

**Pull request merged**
