### PR TITLE
`Exclusive` nits

### PR DESCRIPTION
**Pull request by ghost**
Tracking issue: #98407
- const fns now have `rustc_const_unstable`
- Added `Generator` forwarding impl
- Added `FnOnce` & `FnMut` forwarding impls
- Made the `From` impl unstably const

### CODE REVIEW

**Comment by anden3** [comment]
Hello @H4x5! I noticed that there are some merge conflicts for this PR, what's the status of it?

**Comment by anden3** [comment]
@H4x5 I believe one of the preconditions for getting a review is to not have merge conflicts, so it's probably much easier if you fix those first.

**Comment by Dylan-DPC** [comment]
@H4x5 

> I can resolve the conflicts if a reviewer is interested in merging this

it would be easier to resolve the conflicts, and then wait for the reviewer to review it when they have the time to.

**Comment by JohnCSimon** [comment]
@H4x5 
ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

-----------------

**Review by dtolnay — CHANGES_REQUESTED** [review]
Per https://github.com/rust-lang/rust/pull/104057#issuecomment-1518578519, I don't think the `impl<T> const From<T> for Exclusive<T>` is something we would accept for now.

The rest of the PR looks good to me.

**Comment by dtolnay** [comment]
I have extracted the `FnOnce`, `FnMut`, `Generator` part of this PR to https://github.com/rust-lang/rust/pull/116241.

**Pull request closed without merging**
