### PR TITLE
Implement Iterator::size_hint for Elaborator.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by Aaronepower** [comment]
Triage: @SimonSapin Do you have time to review this PR?

**Comment by SimonSapin** [comment]
Oops, sorry for the delay.

I’m not familiar with this part of compiler internals but based on reading surrounding code: the lower bound look accurate, but I think the upper bound should be `None`. `Iterator::next` can call `Elaborator::push` which can call `self.stack.extend(…)`.

**Comment by frewsxcv** [comment]
> based on reading surrounding code: the lower bound look accurate, but I think the upper bound should be `None`. `Iterator::next` can call `Elaborator::push` which can call `self.stack.extend(…)`

Addressed in the latest force push.

**Pull request merged**
