### PR TITLE
add #[inline] to all the public IpAddr functions

### PR DESCRIPTION
**Pull request by saethlin**

### CODE REVIEW

**Comment by m-ou-se** [comment]
@saethlin Did you mark this PR as a draft on purpose, or is it ready for review?

**Comment by saethlin** [comment]
@m-ou-se I'm looking to assess any compile time impact of this PR. I created it as a draft to link it in the zulip, but it looks like I'll be on my own to assess any compile time regression it causes.

If I can't measure a regression though (which seems likely), it's ready for review.

**Comment by saethlin** [comment]
This produces the desired codegen change, and I cannot measure a compile time regression.

**Pull request merged**
