### PR TITLE
Opt out TaKO8Ki from review rotation for now

### PR DESCRIPTION
**Pull request by jieyouxu**
Hi @TaKO8Ki, I'm opting you out from compiler/diagnostics review rotation for now because I *think* you're very busy recently. Please feel free to re-add yourself (or close this PR) whenever you have more time / feel like it.

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
It's ok. Thanks! I will come back again when I am available.

**Comment by jieyouxu** [comment]
Thanks for your contributions ❤️

**Comment by jieyouxu** [comment]
what

**Comment by jieyouxu** [comment]
Seriously
@bors retry

**Pull request merged**
