### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #111152 (update `pulldown-cmark` to `0.9.3`)
 - #111384 (Fix linking Mac Catalyst by including LC_BUILD_VERSION in object files)
 - #111757 (Consider lint check attributes on match arms)
 - #111831 (Always capture slice when pattern requires checking the length)
 - #111929 (Don't print newlines in APITs)
 - #111945 (Migrate GUI colors test to original CSS color format)
 - #111950 (Remove ExpnKind::Inlined.)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=111152,111384,111757,111831,111929,111945,111950)

### CODE REVIEW

**Comment by klensy** [comment]
#111384 pushed after adding to rollup.

**Comment by compiler-errors** [comment]
@bors r- retry
(I think that's the right incantation to stop the auto merge)

Kicking out of the queue because https://github.com/rust-lang/rust/pull/111384 needs re-approval. Thanks for catching this @klensy, cc @bmisiak

**Comment by compiler-errors** [comment]
I'll open a new rollup without this one, sorry @matthiaskrgr haha

**Pull request closed without merging**
