### PR TITLE
compiler: Never debug_assert in codegen

### PR DESCRIPTION
**Pull request by workingjubilee**
In the name of Turing and his Hoarey heralds, assert our truths before creating a monster!

The `rustc_codegen_llvm` and `rustc_codegen_ssa` crates are fairly critical for rustc's correctness. Small mistakes here can easily result in undefined behavior, since a "small mistake" can mean something like "link and execute the wrong code". We should probably run any and all asserts in these modules unconditionally on whether this is a "debug build", and damn the costs in performance.

...Especially because the costs in performance seem to be *nothing*. It is not clear how much correctness we gain here, but I'll take free correctness improvements.

r? @ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
r? compiler

**Comment by BoxyUwU** [comment]
bors-r-plus

@bors rollup=never
because I figure it'd be nice for this to bisect nicely on regressions (and honestly god knows if this will fail in some weird way in actual-merge CI for some weird target lol

**Comment by workingjubilee** [comment]
I'm sorry?

**Pull request merged**
