### PR TITLE
Experiment: testing cargo scrape-examples in Crater

### PR DESCRIPTION
**Pull request by willcrichton**
This PR does NOT need a review. It is testing out a change to Cargo via Crater.

r? @ghost

### CODE REVIEW

**Comment by willcrichton** [comment]
@craterbot run name=scrape-examples-test start=nightly end=try#339827f5fe28434bbdbb89cf0e3e531acf167554+cargoflags=-Zrustdoc-scrape-examples mode=rustdoc crates=top-1000

**Comment by Dylan-DPC** [comment]
@willcrichton do you still want to do this? if you can resolve the conflicts I can run the crater run on it

**Comment by willcrichton** [comment]
@Dylan-DPC thanks for checking -- I've just been running Crater locally with the try-build from this PR. I'm going to leave this open until rust-lang/cargo#10343 is merged in case of further testing needs.

**Comment by willcrichton** [comment]
@Dylan-DPC can I ask you to run a Crater job for me? Here's the experiment parameters:

name=scrape-examples start=nightly end=try#6ee483316d2e4581572121d60a955affb2032eb3+cargoflags=-Zrustdoc-scrape-examples mode=rustdoc

**Comment by Dylan-DPC** [comment]
@craterbot name=scrape-examples start=nightly end=try#6ee483316d2e4581572121d60a955affb2032eb3+cargoflags=-Zrustdoc-scrape-examples mode=rustdoc

**Comment by willcrichton** [comment]
@Dylan-DPC oh sorry I thought you had to provide a name (I haven't used craterbot before). Will it work if you don't provide a name?

**Comment by willcrichton** [comment]
@Dylan-DPC  Oh sorry I meant to include a "run" at the beginning there 😅 so run:

```
@craterbot run name=scrape-examples start=nightly end=try#6ee483316d2e4581572121d60a955affb2032eb3+cargoflags=-Zrustdoc-scrape-examples mode=rustdoc
```

**Comment by Dylan-DPC** [comment]
oh i was supposed to run `run`, forgot to type it before pasting what you'd sent :D

**Comment by Dylan-DPC** [comment]
@craterbot run name=scrape-examples start=nightly end=try#6ee483316d2e4581572121d60a955affb2032eb3+cargoflags=-Zrustdoc-scrape-examples mode=rustdoc

**Comment by anden3** [comment]
Hi @willcrichton! Since the experiment was successful, can this PR be closed? Or do you plan on using it more?

**Comment by willcrichton** [comment]
Yes I think we can go ahead and close this.

**Pull request closed without merging**
