### PR TITLE
[do not merge] Perform ThinLTO on Windows dist builder in try builds

### PR DESCRIPTION
**Pull request by Kobzol**
Checking if the new testing of optimized artifacts would have caught the ThinLTO rustc miscompilation on Windows (https://github.com/rust-lang/rust/issues/109067).

r? @ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
Well, almost all mir-opt tests have failed, although the errors look a bit weird. It looks like running tests on optimized dist builds would in fact prevent this specific miscompilation.

**Comment by Nilstrieb** [comment]
that's a very funny failure condition that would be very fun to debug if we didn't know that whitespace handling was broken :D

**Comment by Kobzol** [comment]
Yes, it looks super weird with the whitespace. Still, if we got this failure before, we could prevent getting a miscompiling rustc on Windows into stable :) So hopefully next time the tests will help us find similar problems much sooner.

**Pull request closed without merging**
