### PR TITLE
Name LLVM anonymous constants by a hash of their contents

### PR DESCRIPTION
**Pull request by Zoxc**
This makes the names stable between different versions of a crate unlike the `AllocId` naming, making LLVM IR comparisons with `llvm-diff` more practical.

### CODE REVIEW

**Comment by Zoxc** [comment]
This could use a perf run.

**Comment by compiler-errors** [comment]
My initial suspicion was "what if two constants have different allocations but hash to the same contents", but my understanding from this thread is that @oli-obk said this is fine: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/LLVM.20anonymous.20constants/near/337952486

r=me on the impl, but would like another confirmation so 

r? @oli-obk

**Pull request merged**
