### PR TITLE
Add CI test for documentation of hidden items in std

### LINKED ISSUE #87844: CI tests running rustdoc with `--document-private-items --document-hidden-items` on `std`?
I recently broke the command `RUSTDOCFLAGS='--document-private-items --document-hidden-items' x doc library/std`, see #87842, which demonstrates that CI doesn’t test rustdoc on the standard library with these flags. In effect, code with broken intra doc links in or other issues with `doc(hidden)` items (and probably also for private items?) aren’t detected and can be merged into `master`. Maybe we want to add a test for it? Possibly it’s even true that normal `x doc library/std` will always succeed if the one with `--document-private-items --document-hidden-items` does so we wouldn’t even need to test both with and without those flags? (Correct me if I’m wrong on that last point.)

@rustbot label T-infra, A-docs, A-testsuite, C-enhancement

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #87844

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
@ChrisDenton docker seems to be messing with the quotes.
```
; cat Dockerfile 
FROM alpine:latest
ENV SCRIPT RUSTDOCFLAGS="--document-private-items --document-hidden-items" env | grep RUSTDOC
RUN sh -c "$SCRIPT"
; docker build .
Sending build context to Docker daemon  79.49MB
Step 1/3 : FROM alpine:latest
 ---> 49176f190c7e
Step 2/3 : ENV SCRIPT RUSTDOCFLAGS="--document-private-items --document-hidden-items" env | grep RUSTDOC
 ---> Using cache
 ---> cb827fc459ad
Step 3/3 : RUN sh -c "$SCRIPT"
 ---> Running in 94860e857d3b
sh: --document-hidden-items: not found
The command '/bin/sh -c sh -c "$SCRIPT"' returned a non-zero code: 1
```

**Comment by jyn514** [comment]
Escaping the backslashes seems to work:
```
; docker build .
Sending build context to Docker daemon  79.49MB
Step 1/3 : FROM alpine:latest
 ---> 49176f190c7e
Step 2/3 : ENV SCRIPT RUSTDOCFLAGS=\"--document-private-items --document-hidden-items\" env
 ---> Running in bd1af3f1d278
Removing intermediate container bd1af3f1d278
 ---> efaf4a9fafd7
Step 3/3 : RUN sh -c "$SCRIPT"
 ---> Running in c07667c971ce
RUSTDOCFLAGS=--document-private-items --document-hidden-items
SCRIPT=RUSTDOCFLAGS="--document-private-items --document-hidden-items" env
```

**Comment by ChrisDenton** [comment]
Oh eck. Fixed.

**Comment by jyn514** [comment]
Thanks!

@bors r+

**Pull request merged**
