### PR TITLE
Require `#[proc_macro_derive]` functions to be `pub`

### PR DESCRIPTION
**Pull request by jseyfried**
r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
cc @alexcrichton and #35900

**Comment by nrc** [comment]
r = me, but I just want a chance for people to see this before I land it.

**Comment by alexcrichton** [comment]
Oh I thought this was already the case, I even vaguely remember adding a test for this...

In any case looks good to me as well!

**Comment by alexcrichton** [comment]
This just made it into beta, so de-nominating.

**Pull request merged**
