### PR TITLE
Move codegen regression tests to subfolder

### PR DESCRIPTION
**Pull request by bugadani**
As there are a number of codegen tests that check specific issues, I think it's worth to group them into a subfolder.

### CODE REVIEW

**Comment by bugadani** [comment]
Might not be, but I've noticed a bunch of these and also the fact that issue repros in ui tests are also collected in a folder.

**Comment by petrochenkov** [comment]
I also don't think this is an improvement, the grouping here is artificial.
It would be better to use more semantic categorization and make nested directories based on specific language or compiler features, but for the codegen directory it's not too important because it's not too large.
(Also the `issue-NNNN.rs` naming is kind of legacy, it's better to use more semantic names for test files as well.)

**Comment by petrochenkov** [comment]
>the fact that issue repros in ui tests are also collected in a folder.

Yes, and we could name that folder `unsorted-garbage` instead of `issues` with equal success.
This is not a good practice.

**Pull request closed without merging**
