### PR TITLE
Fix process module tests to run on Windows

### LINKED ISSUE #38565: libstd Process tests depend on msys programs on windows
If you don't have some sort of msys in your PATH, then the libstd process tests will fail because they attempt to spawn programs that don't exist on Windows by default.

```
failures:

---- process::tests::test_finish_once stdout ----
        thread 'process::tests::test_finish_once' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_finish_twice stdout ----
        thread 'process::tests::test_finish_twice' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_process_output_error stdout ----
        thread 'process::tests::test_process_output_error' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_process_output_output stdout ----
        thread 'process::tests::test_process_output_output' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_process_status stdout ----
        thread 'process::tests::test_process_status' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_wait_with_output_once stdout ----
        thread 'process::tests::test_wait_with_output_once' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845


failures:
    process::tests::exit_reported_right
    process::tests::smoke
    process::tests::stdout_works
    process::tests::test_finish_once
    process::tests::test_finish_twice
    process::tests::test_process_output_error
    process::tests::test_process_output_output
    process::tests::test_process_status
    process::tests::test_wait_with_output_once
```

### PR DESCRIPTION
**Pull request by abhijeetbhagat**
Fixes #38565
r? @retep998

### CODE REVIEW

**Comment by retep998** [comment]
You have a lot of missing spaces, in particular `){` -> `) {`.

**Comment by AraHaan** [comment]
don't rely on cmd.exe because in future versions of windows that will be removed for powershell.

**Comment by retep998** [comment]
`cmd.exe` has not been removed from Windows yet, not even in insider builds. Microsoft has merely hidden it from certain places to make powershell more of a default option. We can reevaluate the decision to use `cmd.exe` if Microsoft ever does take such a drastic step, but at the moment `cmd.exe` is a significantly better choice than the status quo of using gnu utilities that don't exist on Windows in the first place.

**Comment by petrochenkov** [comment]
r=me with fixed formatting (https://github.com/rust-lang/rust/pull/38797#issuecomment-270106306)
@bors delegate=retep998

**Comment by retep998** [comment]
@AraHaan To dissuade your fears, Microsoft has even published a blog post saying that they will not be removing cmd.exe in the near or distant future. https://blogs.msdn.microsoft.com/commandline/2017/01/04/rumors-of-cmds-death-have-been-greatly-exaggerated/

**Comment by alexcrichton** [comment]
@bors: retry

* sccache timeout

**Comment by alexcrichton** [comment]
@bors: retry

* osx network timeout

**Comment by alexcrichton** [comment]
@bors: retry

* OS X linker segfaulted

**Pull request merged**
