### PR TITLE
book: 'x' is already taken, so use something else

### PR DESCRIPTION
**Pull request by tshepang**
This caused me some confusion

### CODE REVIEW

**Comment by brson** [comment]
Can you expand on what's confusing about 'x' here? This is the first example of the chapter and 'x' wasn't mentioned previously.

**Comment by tshepang** [comment]
It's used in the first 2 code blocks in the page, and that's a differernt `x` to those in the other code blocks.

**Comment by steveklabnik** [comment]
`qux`, while one of the more interesting metasyntactic variables, is also likely to be confusing, as it's less often used. Maybe just a `bar`?

**Comment by tshepang** [comment]
@steveklabnik done

**Comment by Manishearth** [comment]
Merged in https://github.com/rust-lang/rust/commit/6cf3b0b74aadcc1fe87adbd2c74876a1f6c920b3

**Comment by tshepang** [comment]
Looks like this wasn't actually merged. I was made aware by http://internals.rust-lang.org/t/newcomer-to-rust-my-experience/1816/52?u=tshepang.

**Comment by tshepang** [comment]
@cmr re-submitted here: https://github.com/rust-lang/rust/pull/24309

**Comment by Manishearth** [comment]
Oh, oops. My bad, sorry.

**Comment by tshepang** [comment]
[is kool my man, is kool](https://www.youtube.com/watch?v=-3ml3GP_5fg)

**Pull request closed without merging**
