### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by oli-obk**
- Successful merges: #25666, #25681, #25687, #25695, #25697, #25702, #25703, #25709, #25710, #25714, #25715, #25716, #25722
- Failed merges:

### CODE REVIEW

**Comment by eddyb** [comment]
@bors r-
Commit 5263d62 caused the previous rollup, #25711, to [fail on windows](http://buildbot.rust-lang.org/builders/auto-win-gnu-64-nopt-t/builds/43).

**Comment by oli-obk** [comment]
:( I don't have windows around to investigate and fix this. I'll try to remove that one PR

**Comment by eddyb** [comment]
One way to do this is to r- the individual PR (I'll go do that now) and re-create the rollup (force push to replace this branch would work, I hope).

**Pull request closed without merging**
