### PR TITLE
parser: Cleanup `LazyTokenStream` and avoid some clones

### PR DESCRIPTION
**Pull request by petrochenkov**
by using a named struct instead of a closure.

r? @Aaron1011

### CODE REVIEW

**Comment by Aaron1011** [comment]
It looks like adding a `Lrc` didn't result in any performance impact.

@bors r+

**Comment by petrochenkov** [comment]
@Aaron1011 
So, https://github.com/rust-lang/rust/pull/78712 introduces one more case of converting a lazy token stream into a non-lazy one, and I started thinking about using an `enum` again.

The second reason for introducing an enum is that using `None` (of `Option<LazyTokenStream>`) in https://github.com/rust-lang/rust/pull/77255 as both an unknown and as an empty stream feels sketchy, although I can't give an example where it would be incorrect.
Is this case intended for private visibilities specifically?

The problem is that the requirement `sizeof(Option<LazyTokenStream>) <= 8 byte` is [significant for performance](https://github.com/rust-lang/rust/pull/78612) but very restrictive, if `LazyTokenStream` is made into enum, then you can't add even an empty variant without growing its size!
```
struct S1(Box<u8>);
struct S2(Option<Box<u8>>);
enum S3 { None, Some(Box<u8>) }
enum S4 { None, Empty, Some(Box<u8>) }
struct S5(Option<S3>);
struct S6(Option<S4>);
```
```
[src/main.rs:11] size_of::<S1>() = 8
[src/main.rs:12] size_of::<S2>() = 8
[src/main.rs:13] size_of::<S3>() = 8
[src/main.rs:14] size_of::<S4>() = 16
[src/main.rs:15] size_of::<S5>() = 16
[src/main.rs:16] size_of::<S6>() = 16
```
Perhaps if 16 byte is significantly better in terms of allocations and cloning, it will compensate... I need to check.

**Comment by Mark-Simulacrum** [comment]
Since Lazytokenstream is heap allocated, you might consider bit packing the discriminant (by increasing alignment slightly); there's some helpers available in rustc data structures to do so somewhat easily. Unfortunately it's unlikely to be an ergonomic thing as you definitely lose matching and such.

**Comment by petrochenkov** [comment]
Some statistics of token stream lengths in `fn collect_tokens` collected from bootstrapping rustc and stdlib:
```
  1  377069
  4   45481
  7   27001
 13   15311
 10   13782
 17   11456
  5   11309
  3   10065
  9    8041
  2    5961
  6    5295
 16    2672
  8    2079
 12    1692
 18    1679
 11    1349
  0    1300
 14    1243
 20    1003
 21     988
```
So, optimizing for 1-token streams is important, and optimizing for 0-token streams is not too important.

**Pull request merged**
