### PR TITLE
[beta] Backport "Fix rustdoc test ICE"

### PR DESCRIPTION
**Pull request by frewsxcv**
https://github.com/rust-lang/rust/pull/48382

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Shouldn't this be called forward-port?

**Comment by kennytm** [comment]
@bors p=8

Beta "forward-port"

**Comment by frewsxcv** [comment]
looks like it timed out?

**Comment by alexcrichton** [comment]
All dist jobs passed, merging manually

* [Travis](https://travis-ci.org/rust-lang/rust/builds/346779222)
* [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6484)

**Pull request merged**
