### PR TITLE
Fix sub-variant doc display

### LINKED ISSUE #54758: rustdoc: Bad rendering of enums with named fields
Consider the documentation at https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/layout/enum.Abi.html. After expanding the fields, it looks like

screenshot from 2018-10-02 19-55-03

To me this looks like an enum with 4 variants. The way things are indented, I did not even realize that there is a fifth variant, `Aggregate`. I don't mind so much that the tables showing the enum variant fields are not very pretty, but the way they are flushed to the left makes the entire thing really hard to read.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #54758.

screen shot 2018-10-19 at 01 34 11

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
cc @RalfJung 

I'm building a local copy to check it out myself, but i'm curious what this looks like if one of these sub-fields has docs of its own, or an unstable banner, like in the original issue.

**Comment by QuietMisdreavus** [comment]
Personal testing with this branch:

```rust
/// that's some enum, all right
#[unstable(feature="asdf", issue="0")]
pub enum SomeEnum {
    Asdf,
    /// we got some variant here, i guess
    SomeVariant {
        /// it's one field
        one: usize,
        /// it's two field
        two: usize,
    },
    Qwop,
    Girp,
}
```

image

The stability banners seem to overlap the field definitions?

Without the stability banners, it does look much better:

image

**Comment by GuillaumeGomez** [comment]
Good catch! I'll fix the stability banner \*soon\*.

**Comment by RalfJung** [comment]
It also looks odd to have to expand/collapse toggles here, one for the comment and one for the fields. Shouldn't that be just one?

Also, the horizontal line below "Fields of SomeVariant" extends too far to the left; makes it look like it encompasses also "Qwop" and "Girp".

**Comment by GuillaumeGomez** [comment]
Fixed.

@RalfJung I also moved the line more to the left.

**Comment by RalfJung** [comment]
To the right, you mean?

**Comment by GuillaumeGomez** [comment]
To the right indeed. :laughing:

**Comment by QuietMisdreavus** [comment]
Excellent, this looks much better!

image

image

**Comment by RalfJung** [comment]
It does. :)

I still don't understand why we have two expand/collapse trees below `SomeVariant` though? Makes it look somewhat cluttered, and it means one cannot use the `[-]` (which stand out visually quite nice) for visually navigating to the variants.

**Comment by QuietMisdreavus** [comment]
The first `[-]` collapses just the docs, the second collapses the sub-field listing.

However, you do bring up a good point - the section-marker that you can use to grab the anchor for the sub-fields is impossible to reach now. The marker appears all the way in the left gutter, and it goes away when you mouse over the space between the field name and the section marker.

image

**Comment by GuillaumeGomez** [comment]
Ah indeed. I'll fix it as well.

**Comment by GuillaumeGomez** [comment]
Fixed as well.

**Comment by QuietMisdreavus** [comment]
Much better, thanks!

image

@RalfJung Just to demonstrate the "two folds" thing, here's the same docs with a couple paragraphs of dummy text added. See how the extra text separates the two now:

image

There is something to be said about our habit of putting folding containers everywhere, but that discussion should probably happen elsewhere, maybe in its own issue or as a conversation on Discord or IRC first. For now, i think this PR is a good improvement for the problem it sets out to solve.

@bors r+

**Pull request merged**
