### PR TITLE
Implement implied shortcut links for intra-rustdoc-links

### PR DESCRIPTION
**Pull request by Manishearth**
cc https://github.com/rust-lang/rust/issues/43466

Needs https://github.com/google/pulldown-cmark/pull/126

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Shouldn't this wait until the referenced PR is merged upstream and set into a release?

**Comment by Manishearth** [comment]
Yes, that's why it says "needs X".

I'm putting this up for testing and review 😄

**Comment by Manishearth** [comment]
Raph did a release, ready to land.

r?

**Comment by QuietMisdreavus** [comment]
Dang, that came together fast. r=me pending travis

**Comment by jonhoo** [comment]
I wonder if this should be tracked for `relnotes`. It's *such* a win for well-interlinked documentation that as many people as possible should be aware of it!

**Comment by Manishearth** [comment]
It's not stable and will stabilize all in one go

**Comment by jonhoo** [comment]
Sorry, what I meant is that when this *does* stabilize, and #43466 is brought up, the feature landed in this PR specifically should be highlighted.

**Comment by crumblingstatue** [comment]
This is amazing, but is it known that this doesn't work for backticked paths?

```Implements [Iterator]. Yeah, it implements [`Iterator`]. Yup, [Iterator].``` renders as:



[Backticks are allowed in implied reference links in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md#implied-shortcut-reference-links).

**Comment by QuietMisdreavus** [comment]
That's *supposed* to work with this PR, given that the intra-links test verifies that shortcut links with backticks properly resolve. `>_>`

**Comment by Manishearth** [comment]
idk why the test passes, the current implementation doesn't seem to work here (I thought it would but on second thoughts it's missing some things); I need to fix that 😄

**Pull request merged**
