### PR TITLE
Improve string literal unescaping

### PR DESCRIPTION
**Pull request by nnethercote**
Some easy wins that affect a few popular crates.

r? @matklad

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at a time.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
This won't benefit the benchmarks in rustc-perf much, the benefits are in other crates. Here are the instruction count results I got locally on rustc-perf plus the following benchmarks identified as relevant by [this analysis](https://hackmd.io/mxdn4U58Su-UQXwzOHpHag): `pkcs8-0.9.0-pre`, `bitvec-1.0.1`, `der-0.6.0-pre.1`, and `snafu-0.7.0`.

Benchmark & Profile | Scenario | % Change | Significance Factor?
-- | -- | -- | --
pkcs8 check | incr-unchanged | -7.26% | 36.28x
bitvec check | incr-unchanged | -6.76% | 33.82x
der check | incr-unchanged | -5.87% | 29.34x
pkcs8 check | full | -5.14% | 25.69x
pkcs8 check | incr-full | -4.00% | 20.00x
der check | full | -2.77% | 13.86x
der check | incr-full | -2.24% | 11.21x
bitvec check | full | -2.17% | 10.85x
snafu check | full | -1.96% | 9.78x
bitvec check | incr-full | -1.93% | 9.64x
snafu check | incr-full | -1.52% | 7.60x
snafu check | incr-unchanged | -1.34% | 6.70x
coercions check | incr-unchanged | -1.01% | 5.05x
coercions check | incr-patched: println | -0.90% | 4.48x
coercions check | full | -0.49% | 2.46x
coercions check | incr-patched: add static arr item | -0.42% | 2.08x
coercions check | incr-full | -0.40% | 2.00x
stm32f4 check | incr-unchanged | -0.35% | 1.75x

**Comment by nnethercote** [comment]
As for the relative importance of the two commits, here are instruction counts according to Cachegrind for `pkcs8`, which was my primary benchmark.
```
Original  190.1M
Commit 1  186.4M
Commit 2  180.0M
```

**Review by petrochenkov — APPROVED** [review]

**Comment by petrochenkov** [comment]
I'm going to return this to rollup-able state, we see the result, it's localized to 2-3 crates and should be visible in a rollup, no need to merge this separately.
@bors rollup=maybe

**Comment by petrochenkov** [comment]
Network failures when accessing crates.io
@bors retry

**Comment by nnethercote** [comment]
Note: several of the affected crates, such as `pkcs8`, `der`, and `bitvec`, all use `include_str!` to include big chunks of documentation from `.md` files into their code. This seems to be the reason why the string literal processing is hot.

**Pull request merged**
