### PR TITLE
Add missing types' urls for slice type

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus

### CODE REVIEW

**Comment by gagan0723** [comment]
ping from triage @QuietMisdreavus any updates on this?

**Comment by GuillaumeGomez** [comment]
I need to fix the PR first. Seems like the links are badly created.

**Comment by QuietMisdreavus** [comment]
It looks like there's one too many `../` in the URLs when the methods are being rendered on the `slice` page (`std/primitive.slice.html`). I think this is one of those situations where relative-link URLs can't work because the methods are also rendered on the  `Vec` page (`(alloc|std)/vec/struct.Vec.html`). These may have to stay un-linked.

**Comment by hdhoang** [comment]
ping from triage @QuietMisdreavus, any updates on the reviewer's comment?

**Comment by GuillaumeGomez** [comment]
It doesn't seem like it can be solved currently so I'll close this PR.

**Pull request closed without merging**
