### PR TITLE
Prefer `is_empty` to `len()`

### PR DESCRIPTION
**Pull request by tamird**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm I think I may prefer to more officially establish a convention in this regard before migrating the codebase. Along those lines I'm curious if others have thoughts on this?

I'm personally pretty ambivalent, I tend to reach for `len` first just because it's what I'm using 90% of the time elsewhere.

**Comment by Diggsey** [comment]
"is_empty()" is always going to run in constant time, whereas "len()" may take linear time for some containers.

**Comment by Gankro** [comment]
vecmap and bitvset still take linear time to answer is_empty if the answer is "true". If it's false they *may* do better depending on value locations.

**Comment by tamird** [comment]
@Diggsey good call. @alexcrichton wdyt?

**Comment by alexcrichton** [comment]
I feel like the most commonly used collections for the compiler, `Vec` and `HashMap`, it doesn't matter perf-wise one way or another, but it is indeed a good point that collections *may* have a more optimized version of `is_empty` than they do of `len`.

Overall I'd still prefer a broader consensus for changes like this. Ideally this would be a rustc-specific lint as well, but that seems over the top for something so minor.

**Comment by gereeter** [comment]
I'm definitely inclined to prefer `is_empty`, both because of the efficiency argument and because if we use `len`, then `is_empty` serves no purpose.

**Comment by tamird** [comment]
@alexcrichton I think a lint is the way to go here, and probably not a rustc-specific one. I lack the necessary rustc-fu to make this happen though, could you mark this `E-mentor`?

This lint should probably suggest `is_empty()` if the following predicates hold:
- `fn len(&self) -> usize` is called on a receiver that implements an in-scope `fn is_empty(&self) -> bool` **and**:
  - `len()`'s return is compared to zero **or**
  - `len()`'s return is checked for being less than `1`)

WDYT?

**Comment by alexcrichton** [comment]
Ok I find the comments here pretty convincing, so I think this is fine to go in for now. We'll probably want to discuss a little more if we want a lint for something like this, but it seems beneficial regardless for rustc itself to be consistent.

Thanks for being patient and doing so many rebases @tamird!

@bors: r+ c55ae1d

**Comment by lfairy** [comment]
@tamird That would make a great addition to https://github.com/Manishearth/rust-clippy

**Comment by nikomatsakis** [comment]
+1 to `is_empty`

**Pull request merged**
