### PR TITLE
Use `llvm-config` instead of `download-ci-llvm` in PGO script

### PR DESCRIPTION
**Pull request by Kobzol**
This should avoid CI breakage when the LLVM stamp is updated, and also it will avoid an unnecessary LLVM download from CI.

r? @jyn514

### CODE REVIEW

**Comment by Kobzol** [comment]
I'll also start a try build, we should see in ~hour if it works, to avoid an unnecessarily failed merge.

@bors try

**Comment by Kobzol** [comment]
Ok, apparently I will not.

**Comment by Nilstrieb** [comment]
> 🙅 Please do not `try` after a pull request has been `r+`ed. If you need to `try`, unapprove (`r-`) it first.

For context, bors has a funny bug where it insta pushes a PR to master if you r+ during a try build.

**Comment by Kobzol** [comment]
@rustbot ready

I realized that by default the tests won't run in a try build, so we might as well just retry the merge.

**Pull request merged**
