### PR TITLE
L4Re Target: Add the needed Libraries and locate them

### PR DESCRIPTION
**Pull request by TobiasSchaffner**
Add the libraries and objects that have to be linked to a get working L4Re Binary using pre- and post-link-args. Additionaly some ld commands had to be passed.

* L4Re libraries and objects will be located by an environment variable.
* gcc libraries and objects will be located using a gcc call.

GCC is mandatory for this target, that might need documentation somewhere. As soon as something mandatory cannot be found, the compiler will panic. This is intended, because the functions involved don't allow the usage of a Result type. libgcc_eh is now passed using `-l` and crtbeginT.o and crtend.o are now located using `gcc -print-filename`.

### CODE REVIEW

**Comment by TobiasSchaffner** [comment]
As we want the build to fail if the L4RE_LIBDIR environment variable is not set, this behavior is intended.

`[00:59:28] ---- target::test_json_encode_decode::x86_64_unknown_l4re_uclibc stdout ----
[00:59:28] 	thread 'target::test_json_encode_decode::x86_64_unknown_l4re_uclibc' panicked at 'Unable to find L4Re library directory: L4RE_LIBDIR not set.', /checkout/src/libcore/option.rs:819:4
[00:59:28] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:59:28] 
[00:59:28] 
[00:59:28] failures:
[00:59:28]     target::test_json_encode_decode::x86_64_unknown_l4re_uclibc
[00:59:28] 
[00:59:28] test result: FAILED. 73 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[00:59:28] 
[00:59:28] error: test failed, to rerun pass '--lib'`

**Comment by alexcrichton** [comment]
This seems fine to me, thanks! The CI test can probably fixed in w/e the same way iOS doesn't cause failures today (which can also fail at runtime when calculating the target). I'll leave it up to you whether you'd like to hardcode all these values, I'm not sure if they change much for y'all!

**Comment by alexcrichton** [comment]
Hm sorry that's not quite what I had in mind, I believe the `target` function returns a `Result`, so if the env var isn't defined can it just return an error?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
