### PR TITLE
stabilize RangeBounds collections_range #30877

### LINKED ISSUE #30877: Tracking issue for RangeBounds
This issue tracks the `collections_range` feature which applies to `std::collections::range::RangeArgument`. It used to be lumped in with `drain` (#27711) but that was stabilized while `RangeArgument` may continue to be affected by experiments with inclusive ranges, so here we are.

### PR DESCRIPTION
**Pull request by coryshrmn**
The FCP for #30877 closed last month, with the decision to:
1. move from `collections::range::RangeArgument` to `ops::RangeBounds`, and
2. rename `start()` and `end()` to `start_bounds()` and `end_bounds()`.

Simon Sapin already moved it to `ops::RangeBounds` in #49163.

I renamed the functions, and removed the old `collections::range::RangeArgument` alias.

This is my first Rust PR, please let me know if I can improve anything. This passes all tests for me, except the `clippy` tool (which uses `RangeArgument::start()`).

I considered deprecating `start()` and `end()` instead of removing them, but the contribution guidelines indicate we can break `clippy` temporarily. I thought it was best to remove the functions, since we're worried about name collisions with `Range::start` and `end`.

Closes #30877.

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Fantastic, thank you!

**Comment by DDOtten** [comment]
It would be nice to have a `into_bounds` method that gives a way to get `(Bound<T>, Bount<T>)`. Otherwise there is no way to get the start and end as `T` instead of `&T`. I currently came across a situation where I wan't to have an owned vesion of `T` and where it would be slower to clone it. (And it would require an additional trait bound)

**Pull request merged**
