### PR TITLE
remove `&'static` bound from type_id intrinsic (RFC 1849)

### PR DESCRIPTION
**Pull request by cjgillot**
Reopen of #66272 

The broken test in the original PR was not supposed to pass.
By removing it, everything passes.

cc #41875 
r? @Dylan-DPC

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Has anything changed here since @eddyb's comments here: https://github.com/rust-lang/rust/pull/66272#issuecomment-553172133?

What is your use case for this?

**Comment by cjgillot** [comment]
I do not have a use case. I was directed to #41875 by @Dylan-DPC. 
AFAIK, @eddyb's comment is still valid.

**Comment by Mark-Simulacrum** [comment]
I am personally inclined to close this in that case, as I still believe (in agreement with @eddyb) that this is more of a footgun than being helpful. In practice, we've not encountered strong demand for this. I'm going to ping @rust-lang/lang, here, though, since it seems like it may be helpful to fcp close the tracking issue (or at least discuss a bit in a meeting).

**Comment by nikomatsakis** [comment]
I agree with @Mark-Simulacrum that I would prefer not to permit `type_id` to be applied to non-static types.

**Comment by nikomatsakis** [comment]
I would support fcp closing the relevant tracking issue.

**Comment by joshtriplett** [comment]
Based on discussion in the lang team meeting today, we're going to close this due to the lack of a clear use case. If someone wants to re-propose this, they should provide a detailed use case.

**Pull request closed without merging**
