### PR TITLE
Make late_bound_lifetime_arguments a hard error.

### LINKED ISSUE #42868: Tracking issue for `late_bound_lifetime_arguments` compatibility lint
cc https://github.com/rust-lang/rust/pull/42492

TODO: write the description

#### How to fix this warning/error

Just removing the lifetime arguments pointed to by the lint should be enough in most cases.

#### Current status
- [x] https://github.com/rust-lang/rust/pull/42492 introduces the `late_bound_lifetime_arguments` lint as warn-by-default
- [ ] PR ? makes the `late_bound_lifetime_arguments` lint deny-by-default
- [ ] PR ? makes the `late_bound_lifetime_arguments` lint a hard error

### PR DESCRIPTION
**Pull request by cjgillot**
Split from https://github.com/rust-lang/rust/pull/103448

That lint has been there for 5 years.

Fixes https://github.com/rust-lang/rust/issues/42868

### CODE REVIEW

**Comment by compiler-errors** [comment]
Should we crater this? It would be nice to see what crates could use fix PRs to reduce the fallout of this.

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by cjgillot** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-108782/retry-regressed-list.txt

**Comment by cjgillot** [comment]
Crater report:
- use of cssparser 0.17 and 0.25, those versions date back to 2017 and 2019. Latest release 0.27 does not error.
- use of roaring 0.4.2, from 2019. Latest release 0.10 does not error.
- use of scoped pool 1.0, from 2017. There is one PR to fix the warning since 2017, unmerged.
- zerocopy 0.7.0-alpha.3 which errs because it denies the lint, so ok.
- container-broadcast, no github repo, fixed by applying the suggestion.
- easy-csv, 7 year old, fixed by applying the suggestion.
- Sladuca.berkletree, repository archived.

**Comment by oli-obk** [comment]
Does roaring 0.5 also not error? The two crates that depend on 0.4 have no README and no updates since 5 years.

The only cssparser dependencies for versions at 0.25 or earlier are either explicitly abandoned or have no README and no updates since 5 years.

**Comment by oli-obk** [comment]
Nominating for lang team FCP. The summary in the tracking issue https://github.com/rust-lang/rust/issues/42868 is still up to date, so I'm not creating a new summary.

The only regressions are in abandoned crates or outdated (and unused) versions of crates that have been updated to not trigger the future incompat lint.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Discussed in a (minimally attended) lang-team triage meeting and we are in favor of moving forward with this.

**Comment by BoxyUwU** [comment]
The intention long term is to make all lifetimes late bound, I would have thought this would mean we should be _removing_ this lint not making it a hard error since otherwise you would be unable to ever turbofish lifetime args. not to mention we may end up with late bound type and const parameters, not being able to turbofish _any_ generic arguments seems not great.

**Comment by BoxyUwU** [comment]
It would probably be a good idea to nominate this for t-types discussion to figure out how this lint interacts with long term plans for late bound generic parameters

**Comment by tmandry** [comment]
@rfcbot concern types-team-input

Agreed that types team should weigh in here.

**Comment by tmandry** [comment]
@rust-lang/types, can you comment on this proposal with respect to the following?

> It would probably be a good idea to nominate this for t-types discussion to figure out how this lint interacts with long term plans for late bound generic parameters

**Comment by jackh726** [comment]
We haven't discussed this yet, but I do think we should weigh in here. Likely we'll go through nominated issues as a team at the beginning of next month.

**Comment by RalfJung** [comment]
I don't understand why we even want to disallow explicitly stating late-bound lifetime parameters. This is the first time I hear of https://github.com/rust-lang/rust/issues/42868, and that issue description is confusing to me but doesn't motivate the change being made.

I posted my confusion/question at https://github.com/rust-lang/rust/issues/42868#issuecomment-1517848699, though now I realize maybe I should have done that here? let me quote it for your convenience:

> I have to say I am quite confused by the issue description here, and I don't understand what the underlying issue is. The core of my confusion seems to be captured by this (repeated) statement
> 
> > the first argument doesn't make much sense because the function is not parameterized by 'a.
> 
> I strongly disagree! The function _is_ parameterized by `'a`. Sure, this parameter is a type system fiction (the actual runtime address of the function is the same for all choices of `'a`), but that doesn't make `'a` any less of a parameter. It can still be valuable to explicitly set that parameter to guide inference.
> 
> Taking a step back: The fact that some lifetime parameters are type system fictions while others are actually relevant for monomorphization is very confusing and surprising. (I have never fully understood why this is the case; I'll need to dig into this some time.) This will clearly incur some friction when creating function pointers since monomorphization-relevant ("early-bound") lifetime parameters need to be chosen the moment the function pointer is created. I can see that we might want to improve that situation. But reading just this issue I really don't understand the motivation for the current change, since there's a big gap between "unfortunately some lifetime parameters actually matter for monomorphization" and "other lifetime parameters (that don't matter for monomorphization) don't make sense and we should disallow people from explicitly stating them". Which problem is being solved here?

I guess it's time I use my lang team advisor role for the first time. ;)
@rfcbot concern unclear-motivation

**Comment by tmandry** [comment]
Since rfcbot hasn't fully implemented the advisors role yet, I'll proxy Ralf's concern.

@rfcbot concern unclear-motivation

**Comment by cjgillot** [comment]
There is no real motivation on my end besides simplifying the implementation of https://github.com/rust-lang/rust/pull/103448. Closing for now, until I get back to that PR.

**Pull request closed without merging**
