### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
- Successful merges: #42959, #43447, #43455, #43456, #43458, #43462, #43463, #43465, #43471, #43480
- Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
`x86_64-pc-windows-msvc` stage2-rls test failed, likely #43453, spurious.

<details>

```
     Running build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\deps\rls-63ddc6f60085b731.exe
running 14 tests
test build::cargo::test::test_dedup_flags ... ok
test server::test::server_message_get_method_name ... ok
test server::test::server_message_to_str ... ok
error[E0422]: cannot find struct, variant or union type `LibCfgTestStruct` in module `bin_lib_no_cfg_test`
 --> test_data\bin_lib_no_cfg_test\src\main.rs:5:37
  |
5 |     let test = bin_lib_no_cfg_test::LibCfgTestStruct { };
  |                                     ^^^^^^^^^^^^^^^^ not found in `bin_lib_no_cfg_test`
test test::test_bin_lib_project ... ok
test test::test_borrow_error ... ok
test test::test_completion ... ok
test test::test_find_all_refs ... ok
test test::test_find_all_refs_no_cfg_test ... ok
test test::test_multiple_binaries ... ok
test test::test_parse_error_on_malformed_input ... ok
test test::test_reformat ... ok
test test::test_reformat_with_range ... ok
test test::test_simple_workspace ... ok
test test::test_bin_lib_project_no_cfg_test ... FAILED
failures:
---- test::test_bin_lib_project_no_cfg_test stdout ----
	thread 'test::test_bin_lib_project_no_cfg_test' panicked at 'Hit timeout', src\tools\rls\src\test\harness.rs:142:12
failures:
    test::test_bin_lib_project_no_cfg_test
test result: FAILED. 13 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '--bin rls'
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "test" "-j" "2" "--target" "x86_64-pc-windows-msvc" "--release" "--locked" "--color" "always" "--manifest-path" "C:\\projects\\rust\\src/tools/rls/Cargo.toml"
expected success, got: exit code: 101
```

</details>

**Comment by Mark-Simulacrum** [comment]
@bors retry - RLS failure (again, despite attempted fix) - https://github.com/rust-lang/rust/issues/43453

```
[01:46:09] test build::cargo::test::test_dedup_flags ... ok
[01:46:09] test server::test::server_message_get_method_name ... ok
[01:46:09] test server::test::server_message_to_str ... ok
[01:46:10] error[E0422]: cannot find struct, variant or union type `LibCfgTestStruct` in module `bin_lib_no_cfg_test`
[01:46:10]  --> test_data\bin_lib_no_cfg_test\src\main.rs:5:37
[01:46:10]   |
[01:46:10] 5 |     let test = bin_lib_no_cfg_test::LibCfgTestStruct { };
[01:46:10]   |                                     ^^^^^^^^^^^^^^^^ not found in `bin_lib_no_cfg_test`
[01:46:10]
[01:46:11] test test::test_bin_lib_project ... ok
[01:46:11] test test::test_borrow_error ... ok
[01:46:12] test test::test_completion ... ok
[01:46:12] test test::test_find_all_refs ... ok
[01:46:13] test test::test_find_all_refs_no_cfg_test ... ok
[01:46:13] test test::test_multiple_binaries ... ok
[01:46:13] test test::test_parse_error_on_malformed_input ... ok
[01:46:14] test test::test_reformat ... ok
[01:46:14] test test::test_reformat_with_range ... ok
[01:46:15] test test::test_simple_workspace ... ok
[01:46:19] test test::test_bin_lib_project_no_cfg_test ... FAILED
[01:46:19]
[01:46:19] failures:
[01:46:19]
[01:46:19] ---- test::test_bin_lib_project_no_cfg_test stdout ----
[01:46:19]  thread 'test::test_bin_lib_project_no_cfg_test' panicked at 'Hit timeout', src\tools\rls\src\test\harness.rs:142:12
```

cc @nrc

**Pull request merged**
