### PR TITLE
Only use dense bitsets in dataflow analyses

### PR DESCRIPTION
**Pull request by cjgillot**
When a dataflow state has the size close to the number of locals, we should prefer a dense bitset, like we already store locals in a dense vector.
Other occurrences of `ChunkedBitSet` need to be justified by the size of the dataflow state.

### CODE REVIEW

**Comment by lqd** [comment]
cc @nnethercote who introduced the chunked bitsets in #93984

**Comment by nnethercote** [comment]
https://github.com/rust-lang/rust/pull/93984#issuecomment-1048397867 is the best comment about why I introduced these. In short, it was mostly about reducing peak memory usage, and so all metrics should be considered.

Having said that, interestingly the results here don't look like the inverse of #93984. `keccak` is no longer in the benchmark suite, and it was the most-affected benchmark, but ones like `unicode-normalization` and `match-stress` were also affected strongly.

In #93984 I measured a few crates outside of rustc-perf: http-0.2.6, rust-language-tags-0.3.2, tinyvec-1.5.1, vte-0.10.1. It would be worth measuring them too (or updated versions) along with keccak. If the perf results are good, it would be a nice win for simplicity if `ChunkedBitSet` can be removed.

**Comment by cjgillot** [comment]
Looking closer to the massif and dhat profiles, the analyses using a `MovePathIndex` are responsible for the memory consumption. This is to be expected, as there are many more move paths than locals.

New version, only changing the liveness analyses, not initializedness.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
r? @nnethercote 

For the cases that use `MovePathIndex`, a better solution would be to shrink the state space. For borrowck, I don't know if this is possible, but I suspect that dropping Copy or !Drop types for drop elaboration should be possible. In another PR.

**Comment by nnethercote** [comment]
It seems like the perf results for the original version was better, where you removed more `ChunkedBitSet`s? r=me either way.

> For the cases that use `MovePathIndex`, a better solution would be to shrink the state space. For borrowck, I don't know if this is possible, but I suspect that dropping Copy or !Drop types for drop elaboration should be possible. In another PR.

Sounds like a good idea, if it can be done.

**Comment by cjgillot** [comment]
@nnethercote https://github.com/rust-lang/rust/pull/116300 proposes to do that.

**Comment by cjgillot** [comment]
@nnethercote I have updated this PR's message. Do you want me to do further changes?

**Pull request merged**
