### PR TITLE
Move run-pass tests to ui

### PR DESCRIPTION
**Pull request by petrochenkov**
This is the second attempt at doing https://github.com/rust-lang/rust/pull/53994 (which was previously reverted in https://github.com/rust-lang/rust/pull/54530).

The issue with inability to run the test suite in a faster way (https://github.com/rust-lang/rust/issues/54047) that motivated the revert was recently addressed by https://github.com/rust-lang/rust/pull/61755.

r? @Centril

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @rust-lang/compiler

**Comment by Centril** [comment]
```
tidy error: /checkout/src/test/ui/lexer-crlf-line-endings-string-literal-doc-comment.rs: ignoring CR characters unnecessarily
```

Looks good otherwise. r=me

@bors p=1000

**Pull request merged**
