### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by jhpratt**
Successful merges:

 - #123714 (Add test for fn pointer duplication.)
 - #124091 (Update AST validation module docs)
 - #124741 (patchable-function-entry: Add unstable compiler flag and attribute)
 - #126470 (make cargo submodule optional)
 - #126963 (Add basic Serde serialization capabilities to Stable MIR)
 - #126970 (Simplify `str::clone_into`)
 - #127010 (Update browser-ui-test version to `0.18.0`)
 - #127015 (Switch back `non_local_definitions` lint to allow-by-default)
 - #127029 (Fix Markdown tables in platform-support.md)
 - #127032 (Enable const casting for `f16` and `f128`)
 - #127041 (Migrate `run-make/override-aliased-flags` to `rmake.rs`)
 - #127058 (Tighten `fn_decl_span` for async blocks)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=123714,124091,124741,126470,126963,126970,127010,127015,127029,127032,127041,127058)

### CODE REVIEW

**Comment by tgross35** [comment]
@jhpratt could https://github.com/rust-lang/rust/pull/127010 have been what failed the rollup in https://github.com/rust-lang/rust/pull/127056#issuecomment-2195778735? Doesn't seem like it should have but none of the other PRs from that rollup look like they touch that area. (unless it was the ssa changes somehow?)

**Comment by tgross35** [comment]
Nvm, guess it was spurious

**Comment by matthiaskrgr** [comment]
Yeah im wondering as well, I think the ui test update is the one looking most suspicious...
I'll rollup=never it

**Comment by jhpratt** [comment]
It's rustdoc, so it's plausible. The version bump is apparently to _reduce_ flakiness, but presumably there is still some.

**Comment by matthiaskrgr** [comment]
it its somehowe flaky we should probably still not roll it up so its easier to bisect to it later on in case it causes problems...
its already enough painful enough to deal with flaky things in CI that only somtimes break prs :sweat:

**Comment by jhpratt** [comment]
Doesn't bisection handle rollups nowadays?

**Pull request closed without merging**
