### PR TITLE
update miri

### LINKED ISSUE #69462: `miri` no longer builds after rust-lang/rust#69440
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#69440, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @Dylan-DPC, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Dylan-DPC, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Let's make that toolstate green again. :D

This bumps serde in the lockfile, so r? @oli-obk 

Fixes https://github.com/rust-lang/rust/issues/69462

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm, interesting:
```
2020-03-02T16:32:10.3818914Z error: internal compiler error: src/librustc_codegen_ssa/mir/block.rs:520: `miri_start_panic` should never end up in compiled code
2020-03-02T16:32:10.3819454Z 
2020-03-02T16:32:10.3821168Z thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:885:9
2020-03-02T16:32:10.3821537Z stack backtrace:
2020-03-02T16:32:10.5535378Z    0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
2020-03-02T16:32:10.5537236Z    1: core::fmt::write
2020-03-02T16:32:10.5537847Z    2: std::io::Write::write_fmt
2020-03-02T16:32:10.5538155Z    3: std::panicking::default_hook::{{closure}}
2020-03-02T16:32:10.5538893Z    4: std::panicking::default_hook
2020-03-02T16:32:10.5542130Z    5: rustc_driver::report_ice
2020-03-02T16:32:10.5546238Z    6: std::panicking::rust_panic_with_hook
2020-03-02T16:32:10.5550337Z    7: std::panicking::begin_panic
2020-03-02T16:32:10.5554388Z    8: rustc_errors::HandlerInner::bug
2020-03-02T16:32:10.5558305Z    9: rustc_errors::Handler::bug
2020-03-02T16:32:10.5562860Z   10: rustc::util::bug::opt_span_bug_fmt::{{closure}}
2020-03-02T16:32:10.5568446Z   11: rustc::ty::context::tls::with_opt::{{closure}}
2020-03-02T16:32:10.5572721Z   12: rustc::ty::context::tls::with_opt
2020-03-02T16:32:10.5613294Z   13: rustc::util::bug::opt_span_bug_fmt
2020-03-02T16:32:10.5613625Z   14: rustc::util::bug::bug_fmt
2020-03-02T16:32:10.5614074Z   15: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_call_terminator
2020-03-02T16:32:10.5614657Z   16: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
2020-03-02T16:32:10.5615072Z   17: rustc_codegen_ssa::mir::codegen_mir
2020-03-02T16:32:10.5615488Z   18: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
2020-03-02T16:32:10.5615939Z   19: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
2020-03-02T16:32:10.5616625Z   20: rustc::dep_graph::graph::DepGraph::with_task
2020-03-02T16:32:10.5617160Z   21: rustc_codegen_llvm::base::compile_codegen_unit
2020-03-02T16:32:10.5617525Z   22: rustc_codegen_ssa::base::codegen_crate
2020-03-02T16:32:10.5620002Z   23: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
2020-03-02T16:32:10.5624143Z   24: rustc_interface::passes::start_codegen
2020-03-02T16:32:10.5628697Z   25: rustc::ty::context::tls::enter_global
2020-03-02T16:32:10.5632880Z   26: rustc_interface::queries::Queries::ongoing_codegen
2020-03-02T16:32:10.5637110Z   27: rustc_interface::interface::run_compiler_in_existing_thread_pool
2020-03-02T16:32:10.5641459Z   28: rustc_ast::attr::with_globals
2020-03-02T16:32:10.5646064Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2020-03-02T16:32:10.5646360Z 
2020-03-02T16:32:10.5654225Z note: the compiler unexpectedly panicked. this is a bug.
2020-03-02T16:32:10.5654691Z 
2020-03-02T16:32:10.5661245Z note: we would appreciate a bug report: ***/blob/master/CONTRIBUTING.md#bug-reports
2020-03-02T16:32:10.5661564Z 
2020-03-02T16:32:10.5665967Z note: rustc 1.43.0-nightly (2a4746ca1 2020-03-02) running on x86_64-unknown-linux-gnu
2020-03-02T16:32:10.5666295Z 
2020-03-02T16:32:10.5673655Z note: compiler flags: -Z always-encode-mir -Z mir-emit-retag -Z mir-opt-level=0 -Z force-unstable-if-unmarked -C opt-level=3 -C debug-assertions=on -C debug-assertions=y --crate-type lib
2020-03-02T16:32:10.5674148Z 
2020-03-02T16:32:10.5686968Z note: some of the compiler flags provided by cargo are hidden
```
@Aaron1011 looks like code is still generated somewhere for a `--cfg miri` library, when running `cargo-miri miri setup` in bootstrap. Strange.

**Comment by Aaron1011** [comment]
@RalfJung: It looks like bootstrap is passing `cargo-miri` the path of `xargo` rather than `xargo-check`:

https://github.com/rust-lang/rust/blob/18c275b423f9f13c0e404ae3804967d2ab66337c/src/bootstrap/test.rs#L394

This causes us to end uo [using `xargo` instead of `xargo-check`](https://github.com/rust-lang/miri/blob/7cdcdecb01dde41f3e7dd3e350778ef66f533f7b/src/bin/cargo-miri.rs#L104), resulting in codegen being run for `panic_unwind`.

Since `cargo-miri` now only invokes `xargo-check` (never `xargo`), we should probably rename this environment variable to `XARGO_CHECK`, and set it to the path of `xargo-check` in bootstrap.

**Comment by Aaron1011** [comment]
@RalfJung: I've opened https://github.com/rust-lang/miri/pull/1201. Once it's merged, you should be able to update `src/bootstrap/test.rs` to set `XARGO_CHECK` to the proper path.

**Comment by RalfJung** [comment]
@Aaron1011 great catch! That's most likely it. Thanks :)

**Comment by RalfJung** [comment]
This is some kind of cargo feature issue:
```
2020-03-04T04:08:54.5742630Z duplicate artifacts found when compiling a tool, this typically means that something was recompiled because a transitive dependency has different features activated than in a previous build:
2020-03-04T04:08:54.5743350Z 
2020-03-04T04:08:54.5743800Z the following dependencies are duplicated although they have the same features enabled:
2020-03-04T04:08:54.5744250Z the following dependencies have different features:
2020-03-04T04:08:54.5745550Z   proc-macro2 0.4.30 (registry+https://github.com/rust-lang/crates.io-index)
2020-03-04T04:08:54.5746790Z     `rustfmt` additionally enabled features {"default"} at "/Users/runner/runners/2.165.0/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libproc_macro2-58288f9f59724080.rlib"
2020-03-04T04:08:54.5748230Z     `cargo` additionally enabled features {} at "/Users/runner/runners/2.165.0/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libproc_macro2-ad9101f6f50fce55.rlib"
2020-03-04T04:08:54.5749280Z   quote 0.6.12 (registry+https://github.com/rust-lang/crates.io-index)
2020-03-04T04:08:54.5750460Z     `rustfmt` additionally enabled features {"default"} at "/Users/runner/runners/2.165.0/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libquote-d6c8c62334473aa9.rlib"
2020-03-04T04:08:54.5751860Z     `cargo` additionally enabled features {} at "/Users/runner/runners/2.165.0/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libquote-571fc6c253801dac.rlib"
2020-03-04T04:08:54.5752910Z   syn 0.15.35 (registry+https://github.com/rust-lang/crates.io-index)
2020-03-04T04:08:54.5754070Z     `rustfmt` additionally enabled features {"visit"} at "/Users/runner/runners/2.165.0/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libsyn-7a2f4a52e285b5df.rlib"
2020-03-04T04:08:54.5756090Z     `cargo` additionally enabled features {} at "/Users/runner/runners/2.165.0/work/1/s/build/x86_64-apple-darwin/stage1-tools/x86_64-apple-darwin/release/deps/libsyn-61f655d09c570865.rlib"
```
These days, is there a better way to debug those than random guessing?

**Comment by RalfJung** [comment]
I think what's happening is that fewer things use the old syn now, and that changes the features it gets, and they are not consistently the same features everywhere... what a pain.

I will just downgrade serde_json in miri so that I don't have to touch the lockfile here, and hope that someone with a better clue for rustc dependencies resolves this eventually.^^

**Pull request merged**
