### PR TITLE
Implement `Sync` for `mpsc::Sender`

### PR DESCRIPTION
**Pull request by ibraheemdev**
`mpsc::Sender` is currently `!Sync` because the previous implementation contained an optimization where the channel started out as single-producer and was dynamically upgraded on the first clone, which relied on a unique reference to the sender. This optimization is one of the main reasons the old implementation was so complex and was removed in #93563. `mpsc::Sender` can now soundly implement `Sync`.

Note for any potential confusion, this chance does *not* add MPMC behavior. This only affects the already `Send + Clone` *sender*, not *receiver*.

It's technically possible to rely on the `!Sync` behavior in the same way as a `PhantomData<*mut T>`, but that seems very unlikely in practice. Either way, this change is insta-stable and needs an FCP.

@rustbot label +T-libs-api -T-libs

### CODE REVIEW

**Comment by BurntSushi** [comment]
This PR makes `mpsc::Sender` implement `Sync`.

@rfcbot fcp merge

**Comment by BurntSushi** [comment]
Are we certain that the original reason for a `!Sync` impl was because of an internal optimization? Can we go back and find where the original API was sketched out and see if there were any other reasons for the `!Sync` impl?

@rfcbot concern why-not-sync

**Comment by BurntSushi** [comment]
Right now there are some failing tests. We should check to make sure those themselves don't raise any other concerns.

@rfcbot concern failing-tests

**Comment by goffrie** [comment]
> Are we certain that the original reason for a `!Sync` impl was because of an internal optimization? Can we go back and find where the original API was sketched out and see if there were any other reasons for the `!Sync` impl?

I dug up #11111 - which made senders (and other channel types) `!Freeze` (because `Sync` hadn't been invented yet). The only comment was:

```
#[no_freeze] // technically this implementation is shareable, but it shouldn't
             // be required to be shareable in an arc
pub struct SharedChan<T> {
```

I doubt that the decision was considered in-depth - my guess is that it was done just to keep options open for future implementation changes. But maybe @alexcrichton remembers ;)

**Comment by goffrie** [comment]
Ah, I found #42397 as well which made `SyncSender` `Sync`; there's some interesting discussion in there.

**Comment by BurntSushi** [comment]
@goffrie Thanks for digging up #42397. That gives me a lot of confidence that these types weren't `Sync` primarily due to implementation details. So I can at least resolve that concern.

@rfcbot resolve why-not-sync

**Comment by dtolnay** [comment]
> the previous implementation contained an optimization where the channel started out as single-producer and was dynamically upgraded on the first clone, which relied on a unique reference to the sender. This optimization is one of the main reasons the old implementation was so complex and was removed in https://github.com/rust-lang/rust/pull/75194.

This isn't the right PR. Is it #93563?

**Comment by ibraheemdev** [comment]
@dtolnay yeah that's the one, not sure how #75194 ended up in there.

**Comment by ibraheemdev** [comment]
> Right now there are some failing tests. We should check to make sure those themselves don't raise any other concerns.

Fixed the failing tests, which were just UI tests asserting `Sender<()>: !Sync`.

**Comment by ibraheemdev** [comment]
I guess a big question is why implement `Sync` if it's already `Send` and `Clone`, and the only real reason is ergonomics. For example, it makes patterns with `thread::scope` possible without extra cloning clutter:

```rust
let (tx, rx) = std::sync::mpsc::channel();
 
 // std::thread::scope(|s| {
//     let tx1 = tx.clone();
//     s.spawn(|| {
//         tx1.send(1);
//     });
//
//     let tx2 = tx.clone();
//     s.spawn(|| {
//         tx2.send(2);
//     });
// })

std::thread::scope(|s| {
    s.spawn(|| {
        tx.send(1);
    });
    
    s.spawn(|| {
        tx.send(2);
    });
})
```

**Comment by BurntSushi** [comment]
@rfcbot resolve failing-tests

**Review by dtolnay — APPROVED** [review]

**Comment by ibraheemdev** [comment]
cc @thomcc because they expressed thoughts on this.

**Comment by thomcc** [comment]
My thoughts are just that it's a useful optimization sometimes to be able to do things like that (even the lower-complexity version where we just check an Arc's reference count somewhere).

If we don't want to do it in the future, then IMO there's no harm in accepting this. So I'm not opposed to it.

**Pull request merged**
