### PR TITLE
rustdoc: compute maximum Levenshtein distance based on the query

### LINKED ISSUE #82131: [rustdoc] Search results: Make fuzzy search less wild for small words
Fuzzy search is matching too many things [*], e.g.:

- `FRom` due to `FRee`
- `REm` due to `fREe`

It could be improved restricting matches for small words, e.g. for words < 4 in size, match only if 3 characters or more match.

[*]
image

### LINKED ISSUE #103357: search on https://doc.rust-lang.org/ not doing well
I could not figure out a better place to report the issue with https://doc.rust-lang.org/  (which might be an issue on its own, to have a link from the docs to the source code)

The problem is that the search on https://doc.rust-lang.org/ does not seem to function well:

e.g. https://doc.rust-lang.org/std/index.html?search=regex returns lots of hits, none of them related to regex.

OTOH https://doc.rust-lang.org/std/index.html?search=println works quite well.

https://doc.rust-lang.org/std/index.html?search=print starts out quite well, but then also includes things that end with `::pin` and `::hint` that seem to be unrelated.

### PR DESCRIPTION
**Pull request by notriddle**
Preview: https://notriddle.com/notriddle-rustdoc-demos/search-lev-distance-2023/std/index.html?search=regex

The heuristic is pretty close to the name resolver, maxLevDistance = `Math.floor(queryLen / 3)`.

Fixes #103357
Fixes #82131

Similar to https://github.com/rust-lang/rust/pull/103710, but following the suggestion in https://github.com/rust-lang/rust/pull/103710#issuecomment-1296360267 to use `floor` instead of `ceil`, and unblocked now that https://github.com/rust-lang/rust/pull/105796 made it so that setting the max lev distance to `0` doesn't cause substring matches to be removed.

### CODE REVIEW

**Review by GuillaumeGomez — COMMENTED** [review]
Overall, looks good to me. Can you add a test focusing on this change please? For now it's mostly removal and no adds.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks! Considering it's a change in the search engine, let's start a FCP to confirm it's ok with the team.

@rfcbot fcp merge

**Comment by camelid** [comment]
Do we know of any downsides to this change, or is it just a matter of making search follow the text of the query more strictly?

**Comment by camelid** [comment]
@notriddle Ah, thanks for the explanation! Scaling linearly with the input length seems like a good approach 👍

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
