### PR TITLE
Break apart global unstable features

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit shards the all-encompassing `core`, `std_misc`, `collections`, and `alloc` features into finer-grained components that are much more easily opted into and tracked. This reflects the effort to push forward current unstable APIs to either stabilization or removal. Keeping track of unstable features on a much more fine-grained basis will enable the library subteam to quickly analyze a feature and help prioritize internally about what APIs should be stabilized.

A few assorted APIs were deprecated along the way, but otherwise this change is just changing the feature name associated with each API. Soon we will have a dashboard for keeping track of all the unstable APIs in the standard library, and I'll also start making issues for each unstable API after performing a first-pass for stabilization.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @aturon 
cc @rust-lang/libs

**Comment by BurntSushi** [comment]
Woah! This will help a lot! :+1:

**Comment by aturon** [comment]
OK, initial pass done -- this is fantastic.

I marked a few places where I think we can probably just stabilize for 1.2 or deprecate. But it's fine to punt that to a separate pass if you prefer. Otherwise r=me.

**Comment by alexcrichton** [comment]
So my initial strategy was going to be to land this and then follow up with a blanket deprecation pass, following that up with a blanket stabilization pass. The idea would be to only deprecate things that should have been deprecated some time ago, and also only stabilize minor apis that should have been stable awhile ago.

I'm rethinking this, though, as if I'm using these unstable features I may have to update code twice where otherwise I could just lump all the changes into this one PR. Thoughts on whether these blanket passes for "easy" things should happen now or later? I do suspect it will delay this PR to add more stabilizations to it, but we still have a few weeks to the release (and I wouldn't want to cherry-pick stabilizations into the 1.1 branch).

**Comment by aturon** [comment]
Yeah, to avoid unnecessary churn on Nightly, it seems prudent to at least pick off the easy stuff we can get quick consensus on.

**Comment by sfackler** [comment]
Folding them into this seems fine - preferably the deprecation and stabilization passes would each happen in their own commit for ease of review.

**Comment by alexcrichton** [comment]
OK, I have pushed a proposed set of stabilizations and deprecations, each of which is separate as one feature per commit. I can squash everything later, but wanted to make sure it was clear what's going on where.

I'm also now going through the process of updating all the tests and warnings that come out of these changes (a commit to be added).

**Comment by sfackler** [comment]
Is the plan to delete the deprecated stuff in 1.3?

**Comment by Gankro** [comment]
I'm positive-to-neutral on all these changes.

**Comment by alexcrichton** [comment]
@sfackler yeah I'd want to clean out deprecated unstable items after the next release (e.g. when master is 1.3).

**Comment by alexcrichton** [comment]
I'll also mention that I'm avoiding rebasing for now to ensure commit comments are not lost, but I'll rebase once it's all good to go.

**Comment by alexcrichton** [comment]
Ok I've pushed a follow-up to address some comments and also stabilize `vec_map::Entry::or_insert`.

This PR now passes all test as well!

**Comment by alexcrichton** [comment]
One point of note to highlight is [sfackler's comment](https://github.com/alexcrichton/rust/commit/0fb809d331b5b4a8b8c2630a4cdd3c7d7d1c1fb3#commitcomment-11626216) about whether `BorrowState` for a `RefCell` should communicate how many readers are currently reading the cell. It may also be best to just leave out that commit for now.

**Comment by sfackler** [comment]
Is anyone asking for a stable `BorrowState`? If not, we may as well punt on it.

**Comment by aturon** [comment]
Yeah, I wouldn't mind holding off on the BorrowState stuff for now. Otherwise I'm happy with this.

**Comment by alexcrichton** [comment]
Sounds good to me! I've rebased and removed the stabilization of `borrow_state`

**Pull request merged**
