### PR TITLE
CI: Set job names.

### PR DESCRIPTION
**Pull request by ehuss**
This should make it easier to identify what each job is doing when looking at the Travis or Appveyor UI.

- Set `name` for each job in Travis.
- Move `CI_JOB_NAME` to the front in Appveyor so that it appears first in the UI.

### CODE REVIEW

**Comment by ehuss** [comment]
This changes the job name for a few jobs for consistency, such as `x86_64-apple` → `check-x86_64-apple`. If there are any external tools tracking jobs by name, this will likely cause some disruption. If such tools exist, I can change the names back to their original.

**Comment by Mark-Simulacrum** [comment]
@rustbot modify labels to I-nominated and T-infra.

We should discuss this at the next meeting and if there are no concerns raised r=me on the implementation.

Cc @alexcrichton, @pietroalbini, and @kennytm in particular

**Comment by kennytm** [comment]
I'm leaning towards _not_ changing the CI job names since I don't see the appeal of having a "consistent" `$VERB-$NOUN`-style name. AFAIK no automated services need to distinguish between different jobs based on the `$VERB`. Plus the existing names are already recorded throughout the spurious PR tracking sheet.

As for the PR itself, why some jobs are named `check-xxx` and some are named `test-xxx`? For instance the `check-x86_64-linux` (existing name `x86_64-gnu-llvm-6.0`) and `check-x86_64-apple` (existing name `x86_64-apple`) jobs still run the full test suite.

**Comment by Centril** [comment]
Having clearer names on the overview of builds, e.g. https://travis-ci.com/rust-lang/rust/builds/103795945, would be useful when doing rollups. For example, what each macOS builder does is really cryptic... @kennytm What's are the drawbacks to this change?

**Comment by kennytm** [comment]
@Centril I'm +1 with adding the `name:` field, but -0 with changing the name from `x86_64-apple` to `check-x86_64-apple`.

**Comment by Centril** [comment]
@kennytm Oh... I'm fine with whatever on that front.

**Comment by ehuss** [comment]
I'm sorry, I somehow had it in my mind that "check" and "test" were different.  I have reverted the name changes, so every job name should now be the same as before.

If you want a preview of what it looks like, here are some samples:
https://travis-ci.org/ehuss/test/builds/504330368
https://ci.appveyor.com/project/ehuss/test/builds/22962579

**Comment by pietroalbini** [comment]
:+1: This is way clearer when looking for a job, and it shouldn't affect anything else.

**Comment by alexcrichton** [comment]
@bors: r+

Looks like since the renamings are backed out this is otherwise equivalent, and definitely much nicer to read on the travis side of things

**Comment by pietroalbini** [comment]
Removing the nomination since the team already approved the PR.

**Pull request merged**
