### PR TITLE
bootstrap: Rename profile = user to profile = dist

### LINKED ISSUE #112074: bootstrap: Rename `profile = user` to `profile = dist`
`config.user.toml` currently says: https://github.com/rust-lang/rust/blob/20ca24e3c59dff52f76f1566c121c134e3a9b287/src/bootstrap/defaults/config.user.toml#L1
"users" is so ambiguous as to be meaningless. What I originally intended was something like "people building from source once and installing it locally", like Gentoo users or something. I think "dist" is a much better name for this profile: it makes it more clear why CI uses the profile and it hopefully will make it easier for distros to find and understand.

cc @cuviper - you said in https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Redesign.20bootstrap.20stages.20compiler-team.23619/near/351408631 this would be helpful, do you still think that? The only other name I can think of is something like `install` but I'm not sure that's a good description of what CI is doing with the profile.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #112074

### CODE REVIEW

**Comment by AnakinSkywalkeer** [comment]
@clubby789 can u take a look

**Comment by compiler-errors** [comment]
@AnakinSkywalkeer, in the future, when you want to link your PR to an issue that is fixed, please put it in the PR message body instead of the title. That'll make sure it's automatically closed when the PR lands. 

I've fixed this one for you.

**Comment by AnakinSkywalkeer** [comment]
> @AnakinSkywalkeer, in the future, when you want to link your PR to an issue that is fixed, please put it in the PR message body instead of the title. That'll make sure it's automatically closed when the PR lands. (Also, a description wouldn't hurt for PRs in the future.)
> 
> I've fixed this one for you.

ohhh so sorry about that my bad gonna keep in mind next time

**Comment by jyn514** [comment]
This doesn't keep backwards compatibility like I asked for in the issue :/ it also doesn't update configure.py, so anyone using configure will be using an invalid profile; and it doesn't update the file in src/bootstrap/defaults.

I think the only effect of this is that it's no longer possible to pick `user` through `x setup`, and that choosing `dist` will give a hard error that the file isn't found. Please test your changes in the future.

**Pull request merged**
