### PR TITLE
Upgrade a comment to a doc comment

### PR DESCRIPTION
**Pull request by oli-obk**
r? @alexcrichton 

cc @bjorn3

### CODE REVIEW

**Comment by oli-obk** [comment]
Maybe we should have a lint that forbids comments before undocumented public items and other documentable things.

**Comment by bjorn3** [comment]
Forgot to submit one more review comment.

**Review by bjorn3 — APPROVED** [review]

**Comment by bjorn3** [comment]
> Maybe we should have a lint that forbids comments before undocumented public items and other documentable things.

It should also detect enum variant followed by comment on the same line. I have seen quite a lot in older code.

**Comment by oli-obk** [comment]
Maybe this is something rustfmt could do?

**Comment by bjorn3** [comment]
Was working on some more comment to doc comment changes, but got tired as I already have ~500 changes and I have about 100 to go according to my code :cry:

https://github.com/bjorn3/rust/tree/tidy_comment_check

**Pull request merged**
