### PR TITLE
Improve unstable feature message display

### LINKED ISSUE #51387: [rustdoc] unclear experimental api notes
Which API is a nightly-only experimental API? The one followed by the note, or the one it follows? It's not very clear to me.

notes

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #51387.

r? @QuietMisdreavus 

screen shot 2018-06-14 at 23 04 18

### CODE REVIEW

**Comment by pietroalbini** [comment]
Ping from triage @QuietMisdreavus! This PR needs your review.

**Comment by GuillaumeGomez** [comment]
I need to modify it again after a discussion we had (putting the unstable message into the doc instead).

**Comment by pietroalbini** [comment]
Ping from triage @GuillaumeGomez! It's been a while since we heard from you, will you have time to work on this again?

**Comment by GuillaumeGomez** [comment]
I'll, just going through my TODO list by thanks for the reminder. :)

**Comment by TimNN** [comment]
Ping from triage, @GuillaumeGomez!

**Comment by TimNN** [comment]
Ping from triage, @GuillaumeGomez! We haven't heard from you in a while, so we are closing this PR. Feel free to re-open it in the future. Thanks for your contribution!

**Pull request closed without merging**
