### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #131654 (Various fixes for Xous)
 - #131743 (rustc_metadata: minor tidying)
 - #131823 (Bump libc to 0.2.161)
 - #131850 (Missing parenthesis)
 - #131857 (Allow dropping dyn principal)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=131654,131743,131823,131850,131857)

### CODE REVIEW

**Comment by jhpratt** [comment]
See https://github.com/rust-lang/rust/pull/131867 — my suspicion is the `rustc_metadata` change is why it failed but I'm not positive.

**Comment by jieyouxu** [comment]
> See #131867 — my suspicion is the `rustc_metadata` change is why it failed but I'm not positive.

@jhpratt that's one of the msvc spurious failures, i.e. #127883

**Comment by jhpratt** [comment]
Thanks for the info. I'll be sure to simply `retry` it in the future (in addition to tagging).

**Pull request merged**
