### PR TITLE
Move the alloc::allocator module to core::heap

### PR DESCRIPTION
**Pull request by SimonSapin**
This is the `Alloc` trait and its dependencies.

### CODE REVIEW

**Comment by glandium** [comment]
Why `core::heap` and not `core::allocator`? `core::heap` won't even ever contain `Heap`

**Comment by alexcrichton** [comment]
@glandium `alloc::allocator` wasn't intended to ever be a public/stable interface, and libcore is simply a subset of libstd so `core::heap` was a natural subset of `std::heap`

**Comment by SimonSapin** [comment]
@glandium I’m also going to propose renaming the `heap` modules of respective crates to `alloc`, but maybe we should batch breaking changes together so that Nightly users can migrate at once. (I’m traveling right now, I’ll write up more soon.)

**Pull request merged**
