### PR TITLE
dont call mir.post_mono_checks in codegen

### PR DESCRIPTION
**Pull request by RalfJung**
It seems like all tests are still passing when I remove this... let's see what CI says.

### CODE REVIEW

**Comment by RalfJung** [comment]
Yeah this seems to be unnecessary to call. @oli-obk does monomorphization already go over all the `required_consts` before monomorphizing the function itself or how does this work?

**Comment by oli-obk** [comment]
Yea, it doesn't do this explicitly, but due to the `MirUsedCollector` visiting the body with a mir visitor, we'll encounter `visit_constant` and evaluate the constant there.

@bors r+

**Comment by RalfJung** [comment]
I think I want to add some comments explaining this.
@bors r-

**Comment by oli-obk** [comment]
Yep, those match my knowledge

@bors r+

**Pull request merged**
