### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #127462 (std: uefi: Add basic Env variables)
 - #131537 (Fix range misleading field access)
 - #131838 (bootstrap: allow setting `--jobs` in config.toml)
 - #131890 (Update `use` keyword docs to describe precise capturing)
 - #131899 (Mark unexpected variant res suggestion as having placeholders)
 - #131908 (rustdoc: Switch from FxHash to sha256 for static file hashing.)
 - #131916 (small interpreter error cleanup)
 - #131919 (zero-sized accesses are fine on null pointers)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=127462,131537,131838,131890,131899,131908,131916,131919)

### CODE REVIEW

**Comment by lqd** [comment]
The regressions are in rustdoc, so probably https://github.com/rust-lang/rust/pull/131908.

**Comment by notriddle** [comment]
Yes, it's real. Sha256 is slower than fxhash.

Addressed by https://github.com/rust-lang/rust/pull/131951

**Comment by pnkfelix** [comment]
* primary regressions to helloworld (doc) and hyper (opt); primary improvement to libc (doc).
* all the secondary regressions are to doc benchmarks, which led lqd to hypothesize that this is due to PR 131908 which changed the hash used for filename generation to sha256 since it should be stable going forward.
* hyper history seems really noisy.
* marking as triaged

@rustbot label: +perf-regression-triaged

**Pull request merged**
