### PR TITLE
Stabilize `#[cfg(panic = "...")]`

### PR DESCRIPTION
**Pull request by cchiw**
[Stabilization PR](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr) for #77443

### CODE REVIEW

**Comment by joshtriplett** [comment]
Note: when announcing this in the release notes, we should document that people shouldn't write code assuming only two panic strategies (e.g. `#[cfg(panic = "abort")]` being equivalent to `#[cfg(not(panic = "unwind"))]` and vice versa).

**Comment by joshtriplett** [comment]
Shall we stabilize `#[cfg(panic = "...")]`?

@rfcbot merge

**Comment by scottmcm** [comment]
@rfcbot reviewed

(I don't know if this is a complex enough feature for compiler folks to want to be included, BTW.)

**Comment by joshtriplett** [comment]
Yeah, I missed that this was also tagged T-compiler.

Removing T-compiler for a T-lang FCP, but if anyone on T-compiler has concerns with this feature, please feel free to raise them.

@rfcbot cancel

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by joshtriplett** [comment]
The documentation previously in `src/doc/unstable-book/src/language-features/cfg-panic.md` (minus the bits about the unstable feature gate) should go somewhere, such as in the reference. We shouldn't just delete it without replacement.

Otherwise, LGTM.

**Comment by Manishearth** [comment]
@joshtriplett https://github.com/rust-lang/reference/pull/1157, but it can't be merged yet due to the feature not being stabilized :)

**Comment by joshtriplett** [comment]
@Manishearth Ah, excellent.

In that case, r=me when the FCP finishes.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by cchiw** [comment]
> The documentation previously in `src/doc/unstable-book/src/language-features/cfg-panic.md` (minus the bits about the unstable feature gate) should go somewhere, such as in the reference. We shouldn't just delete it without replacement.
> 
> Otherwise, LGTM.

Just FYI, additional documentation was accepted by [Rust for Example
](https://github.com/rust-lang/rust-by-example/pull/1500)

**Pull request merged**
