### PR TITLE
[beta] Prepare beta 1.53.0

### PR DESCRIPTION
**Pull request by emilyalbini**
Along with updating the channel and updating the bootstrap compiler, this also includes:

* 692454d58353a25e2b8289dd925bf33d43a44a42 - Fixes the diagnostics difference we had for some cycles already
* 9157430d6223e0c50cf50a13ec4e38fad2a8ec37 - Disables the known broken RLS builder on AArch64 Windows
* #84183 - Update RELEASES.md for 1.52.0 
* #84950 - Revert PR 83866
* #84886 - Update RLS and Rustfmt

Changes we backported to 1.52.0 that we also need to include in 1.53.0 to avoid regressing:

* #84867 - rustdoc: revert deref recur to resume inclusion of impl ExtTrait<Local> for ExtType
* #84759 - [beta] remove assert_matches
* #83171 - Revert PR 81473 to resolve (on beta) issues 81626 and 81658.

r? @ghost

### CODE REVIEW

**Comment by camelid** [comment]
Just checking, is it intentional that this is filed against master rather than beta? According to `src/version`, master is currently 1.54.0 (not 1.53.0).

**Comment by pietroalbini** [comment]
Ugh thanks for pointing that out @camelid, we definitely need CI to prevent that from happening :(

**Comment by pietroalbini** [comment]
CI is finally green :tada: 

r? @Mark-Simulacrum

**Comment by jyn514** [comment]
Please see the comments on https://github.com/rust-lang/rust/pull/84950, it is not the right fix.

**Comment by jyn514** [comment]
> Please see the comments on #84950, it is not the right fix.

For posterity, I'm going to make the proper fix as a PR to master - #84950 is being merged to simplify the differences between beta and master.

**Comment by pietroalbini** [comment]
@bors p=100

Let's get this merged soon so we can start Crater.

**Comment by jyn514** [comment]
Rustfmt just got updated in https://github.com/rust-lang/rust/pull/84886, maybe you need to cherry-pick it

**Comment by Mark-Simulacrum** [comment]
Hm, I thought this included a revert of https://github.com/rust-lang/rust/pull/83312 for beta which should also fix this failure I suspect, but either cherry-pick should work.

**Comment by pietroalbini** [comment]
Woops, forgot to include the rustfmt changes :/

Opted to cherry-pick the rustfmt bump (https://github.com/rust-lang/rust/pull/84886), as that is one less revert we have to account for when backporting future changes to this cycle's beta.

@bors r=Mark-Simulacrum p=100

**Pull request merged**
