### PR TITLE
correctly handle normalization in implied bounds query

### LINKED ISSUE #109628: bounds on trait impls are used in implied bounds
The following compiles although it shouldn't:
```rust
trait Trait {
    type Assoc;
}

impl<T: 'static> Trait for Box<T> {
    type Assoc = ();
}

struct MyTy<U>(U)
where
    U: Trait,
    U::Assoc: Sized, // any predicate naming U::Assoc
;

fn fn_test<T>(_: MyTy<Box<T>>) {}
```
`fn_test` should fail with an error requiring an explicit `T: 'static` bound.

This is a compiler bug for the following reasons:
- It certainly does not follow from the rules of [RFC 1214][rfc1214] and [RFC 2089][rfc2089]. The implied bounds from a trait reference (`Box<T>: Trait`) includes only the where-clauses of the trait itself, not the trait impl. 
- It breaks stability guarantees in the sense that relaxing region constraints on trait impls is now a breaking change. Removing the useless bound `U::Assoc: Sized` is also a breaking change.
- It requires remote reasoning when dealing with implied bounds.
- It is a surprising behavior: why does the trivial bound `U::Assoc: Sized` make any meaningful difference?

[rfc1214]: https://rust-lang.github.io/rfcs/1214-projections-lifetimes-and-wf.html
[rfc2089]: https://rust-lang.github.io/rfcs/2089-implied-bounds.html

### LINKED ISSUE #109799: incomplete normalization in implied bounds
The following fails to compile:
```rust
pub trait Iter {
    type Item;
}

impl<'x, I> Iter for I
where
    I: IntoIterator<Item = &'x str>,
{
    type Item = &'x str;
}

pub struct Map<I>(I)
where
    I: Iter,
    I::Item: 'static;

fn test(_: Map<Vec<&str>>) {}
//~^ ERROR needs to satisfy a `'static` lifetime requirement
```
while changing the `Iter` impl to use a paramter type `X` instead of the lifetime `'x` makes it compile:
```rust
// ...

impl<X, I> Iter for I
where
    I: IntoIterator<Item = X>,
{
    type Item = X;
}

// ...
```

This is because we are ignoring projection predicates that constrain region variables while using those that constrain type variables:
https://github.com/rust-lang/rust/blob/8a7ca936e61d04399198911ee2b07ac110bf17b0/compiler/rustc_traits/src/implied_outlives_bounds.rs#L86-L94

Should be fixed by #109482.

### PR DESCRIPTION
**Pull request by aliemjay**
One subtle bug with the `implied_outlives_bounds` is that it adds implied bounds from trait impls. Example:
```rust
trait Trait { type Ty; }
impl<T: 'static> Trait for T { type Ty = (); }
// implied_outlives_bounds(Vec<<T as Trait>::Ty>) = [T: 'static,]
// note Vec<_> is necessary 
```

~This is not a user-visible bug only because wfcheck currently computes implied bounds for fully normalized types only.~ (edit: this is not correct unfortunately. See #109628)  The only place where we use implied bounds for unnormalized types during HIR analysis is in `compare_predicate_entailment`.

This PR fixes this by using `wf::unnormalized_obligations` instead of `wf::obligations`.

Fixes #109628.
Fixes #109799.

Additional changes :
- rework to handle inference vars and normalization more explicitly and rigorously.
- add implied bounds from the input types after normalization.

r? @lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
that's really cool :+1: i remember that we still have that issue during borrowck

```rust
use std::any::Any;

trait Trait {
    type Assoc;
}

impl<T: 'static> Trait for T {
    type Assoc = &'static T; 
}

fn foo<T>(t: T, x: <T as Trait>::Assoc) -> Box<dyn Any> {
    Box::new(t)
}
```
I forgot why exactly we had to add both the normalized and the unnormalized signature types for implied bounds, maybe that was also an issue solved by opportunistically resolving region vars in the query response?

why is this still a draft?

**Comment by aliemjay** [comment]
> i remember that we still have that issue during borrowck

@lcnr I breaked this code in https://github.com/rust-lang/rust/pull/109482/commits/00a80b04fd4235d74626d6e7071e4c58803cbd2f only to asses the impact with crater. That said, this only breaks borrowck -- we still accept this in wfcheck:
```rust
trait Trait {
    type Assoc;
}

impl<T: 'static> Trait for Box<T> {
    type Assoc = &'static T; 
}

impl<T> Trait for (T, <Box<T> as Trait>::Assoc) {
    type Assoc = &'static T; // We can still assume T: 'static by wfcheck
}
```

**Comment by lcnr** [comment]
@craterbot check

**Comment by aliemjay** [comment]
There are 2 root regressions: 

- `actix-mqtt-client` (2 dependent crates)
- `bevy_ecs` (~450 dependent crates) (cc @BoxyUwU) 

Both are legitimate breakages. In the case of `bevy_ecs` we were having an implied bound `Q: 'static` from `ParamsSet<Query<Q>>`. This bound originates from the trait impl [here][impl] only -- it cannot be deduced from the struct definition. This can be fixed by moving the bound to the struct definition.

[impl]: https://docs.rs/bevy_ecs/0.10.0/bevy_ecs/system/struct.Query.html#impl-SystemParam-for-Query%3C'_,+'_,+Q,+F%3E

All other regressions (~1500) are due to [the experiment](https://github.com/rust-lang/rust/pull/109482#issuecomment-1480661780) I described above. They are irrelevant to this PR.

**Comment by aliemjay** [comment]
I reverted https://github.com/rust-lang/rust/commit/00a80b04fd4235d74626d6e7071e4c58803cbd2f. We can re-run crater on the regressed list only.

**Comment by lcnr** [comment]
@bors try

and then with `check crates=https://crater-reports.s3.amazonaws.com/pr-109482/index.html`

**Comment by compiler-errors** [comment]
@craterbot run mode=check-only crates=https://crater-reports.s3.amazonaws.com/pr-109482/retry-regressed-list.txt

**Comment by lcnr** [comment]
We currently consider bounds only on impls used during normalization while computing implied bounds. This means that removing bounds on impls is a theoretical breaking change.

This PR causes us to only consider implied bounds which are from WF requirements directly and stops considering bounds from normalization. This allows users to safely remove (region) bounds from their impls.

The following code currently compiles but will break with this change:
```rust
use core::any::Any;

trait Trait {
    type Assoc;
}

impl<X: 'static> Trait for Vec<X> {
    type Assoc = ();
}

struct Foo<T: Trait>(T)
where
    T::Assoc: Clone; // any predicate using `T::Assoc` works here

fn foo<X>(x: X, _: Foo<Vec<X>>) -> Box<dyn Any> {
    Box::new(x) // gets to assume `X: 'static` from the bound on the impl
}
```

This is relied on by 2 crates:
- https://github.com/Syndim/actix-mqtt-client
- https://github.com/bevyengine/bevy

This breakage is fixing a previously underspecified part of the language and is therefore acceptable. I think we should open PRs for both of these crates as soon as possible, fixing this issue. Maybe even asking the bevy devs to emit point releases for some previous versions, and then land this at the start of the next nightly cycle: April 14th.

going to start a types FCP after we have the PRs up to fix these 2 crates

**Comment by lcnr** [comment]
alright, bevy is very annoying to fix. We would have to add `'static` bounds to a lot of structs and that also leaks to crates using bevy, so users may also be required to add `'static`.

Considering that region bounds on *trait definitions* are already used as implied bounds somewhere?

```rust
use std::any::Any;

trait Trait: 'static {}

fn foo<T: Trait>(x: T) -> Box<dyn Any> {
    Box::new(x)
}
```
Maybe we should apply this consistently to trait predicates in implied bounds, looking at the nested predicates of trait bounds and considering the outlives predicates... not sure why that isn't currently happening/what exactly is happening here.

With this we should only have to add a `'static` bound to  `trait WorldQuery` to `bevy` and get it implied everywhere else.

**Comment by aliemjay** [comment]
closing in favor of the lint version #109763.

**Pull request closed without merging**
