### PR TITLE
Add additional parenthesis for binary ops in pretty printer

### PR DESCRIPTION
**Pull request by GSam**
In the case where there are no paren in the AST, the pretty printer doesn't correctly print binary operations where precedence is concerned. Parenthesis may be missing due to some kind of expansion or manipulation of the AST. 

Example:
Pretty printer prints Expr(*, Expr(+, 1, 1), 2) as 1 + 1 \* 2, as opposed to (1 + 1) \* 2

r? @nrc

### CODE REVIEW

**Comment by GSam** [comment]
Failing on pretty/issue-4264.rs, due to some additional parenthesis. I assume that 'as' is left associative?

**Comment by nrc** [comment]
Rather than adding this logic in three places, could you modify `print_expr_maybe_paren` - these seem to be the only uses of that function and the name makes it sound like it should do what you want.

**Comment by GSam** [comment]
It doesn't seem much cleaner, especially with that Option, although perhaps I can do it a different way.

**Comment by nrc** [comment]
Can you check the sub-expression rather than passing in the parent?

**Comment by GSam** [comment]
@nrc Dropped the last patch.

**Pull request merged**
