### PR TITLE
make matching on NaN a hard error, and remove the rest of illegal_floating_point_literal_pattern

### LINKED ISSUE #41620: Tracking issue for `illegal_floating_point_literal_pattern` compatibility lint
This is a tracking issue for the compatibility lint disallowing floating point literals in patterns.

The corresponding RFC is [RFC 1445](https://github.com/rust-lang/rfcs/pull/1445). Originally, #36890 was the only tracking issue for floats in patterns, but after it was found out that the implementation of that lint doesn't cover literals (issue  #41255), another lint and tracking issue were required.

The goal of this lint is to make code like this a hard error:

```rust
fn main() {
    let x = 13.4;

    match x {
        1.0 => println!("one"),
        22.4 => println!("two"),
        3.67 => println!("three"),
        13.4 => println!("thirteen point four"),
        _ => println!("anything"),
    }
}
```

- [x] PR #41293 introduces the lint as warn by default
- [ ] PR xxxx makes the lint deny by default
- [ ] PR xxxx makes the lint a hard error

### PR DESCRIPTION
**Pull request by RalfJung**
These arms would never be hit anyway, so the pattern makes little sense. We have had a future-compat lint against float matches in general for a *long* time, so I hope we can get away with immediately making this a hard error.

This is part of implementing https://github.com/rust-lang/rfcs/pull/3535.

Closes https://github.com/rust-lang/rust/issues/41620 by removing the lint.

https://github.com/rust-lang/reference/pull/1456 updates the reference to match.

### CODE REVIEW

**Comment by RalfJung** [comment]
All right let's see what crater finds
@craterbot check

**Comment by asquared31415** [comment]
It would be nice if there were justification in a `note` in the error message, maybe something like "`NaN` never matches any float, including identical `NaN`s"?

**Comment by RalfJung** [comment]
Yeah if crater comes back with the results I hope we can improve the diagnostics.

**Comment by RalfJung** [comment]
These all look spurious. :)

@rust-lang/lang this is basically a trimmed-down version of https://github.com/rust-lang/rust/pull/84045 that only makes matching specifically on NaNs a hard error. Those match arms are impossible to hit, so there's no way these arms are actually useful.

**Comment by nikomatsakis** [comment]
@RalfJung We discussed this in the lang-team meeting today. We had some questions:

* First, what is the motivation to eliminate NaN specifically? Is it simply that NaN is confusing for end-users (because it is not equal to itself, and hence the arm is dead code) or is it because NaN itself adds some difficulties to const generics or other things? 
* Second, do we have a sense for the overall "plan" around the semantics of pattern matching and floating point values? At some point we expected to remove that, but now it seems like we are allowing floats, presumably with today's semantics, is that correct? 

Our preliminary feeling at the meeting was that...

* If we are going to allow matching on floats, we would prefer to lint against matching on NaN, as it could be quite surprising, but not make it a hard error.
* If we are going to disallow *all* float matching, then, this is a different thing.

**Comment by RalfJung** [comment]
> First, what is the motivation to eliminate NaN specifically?

NaN is by far the least well-behaved class of float values when it comes to comparison, since they don't even satisfy reflexivity. No matter the mental model for `match`, it seems very hard to justify a value not even matching itself.

> Second, do we have a sense for the overall "plan" around the semantics of pattern matching and floating point values? At some point we expected to remove that, but now it seems like we are allowing floats, presumably with today's semantics, is that correct?

There was the plan to disallow floats entirely as part of the move to enforcing structural matching (this even got [RFC'd](https://rust-lang.github.io/rfcs/1445-restrict-constants-in-patterns.html)). Then t-lang rejected https://github.com/rust-lang/rust/pull/84045, which is a departure from that plan. If t-lang has a long-term plan here than you didn't tell us about it. :)

**Comment by saethlin** [comment]
> * If we are going to allow matching on floats, @scottmcm and myself, at least, would prefer to lint against matching on NaN, as it could be quite surprising, but not make it a hard error.

A future-incompat lint that covers _all_ float matches already exists: https://github.com/rust-lang/rust/pull/41293

**Comment by scottmcm** [comment]
> If t-lang has a long-term plan here than you didn't tell us about it. :)

Yeah, we agree we need a plan :)  We opened https://github.com/rust-lang/lang-team/issues/222 so that the planning meeting tomorrow can hopefully schedule something about it

**Comment by workingjubilee** [comment]
I believe we should _not_ use PartialEq as the basis of `match`, and especially not in this case. It is irritatingly recursive to begin with (generally, when writing PartialEq impls, I use match to **avoid** having to reason about the existence of **other** PartialEq impls) and encourages needless semantic drift between a match arm described by a constant and a match arm described by a pattern.

**Comment by tmandry** [comment]
Un-nominating for now in lieu of the upcoming lang team meeting, https://github.com/rust-lang/lang-team/issues/222.

@rustbot label -I-lang-nominated

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rfcs/pull/3535 motivates why specifically matching on NaN should get rejected.

**Comment by RalfJung** [comment]
I have updated this PR to match https://github.com/rust-lang/rfcs/pull/3535 for how floats in patterns should behave: NaN is forbidden, but everything else is allowed without a lint.

**Comment by RalfJung** [comment]
The RFC has been accepted, so I think this is ready to go.
@rust-lang/lang do we need FCP for this part of implementing an accepted RFC? This change does affect what happens on stable so this could be considered to be the usual stabilization FCP.

We did a crater run back in October and it found [no regressions](https://github.com/rust-lang/rust/pull/116284#issuecomment-1742449398).

**Comment by cjgillot** [comment]
On the implementation, r=me once the FCP/no-FCP is resolved.

**Comment by traviscross** [comment]
@rustbot labels +I-lang-nominated

This was blocked on the acceptance of rust-lang/rfcs#3535, which has now been accepted.  Nominating to check our consensus this is OK to now move forward.

@RalfJung: It may be prudent to post a stabilization report here so that, if people decide that's needed, this doesn't block an extra review cycle.

**Comment by RalfJung** [comment]
Not sure what to say, beyond the PR description: the change in this PR is that when a const of float type is used as a pattern (or more generally, when a const used as a pattern contains a float value):
- if it is a NaN, we emit a hard error (before: future-compat lint, active for many years but not shown in dependencies)
- otherwise, we consider this to be fine, there's no lint (before: future-compat lint)

We did a crater run which found no regressions. Matching against NaN should be extremely rare since it is never useful. Hence I think it is okay to move from "future compat lint (not shown in dependencies)" directly to "hard error" without a period of "future compat lint (shown in dependencies)".

**Comment by workingjubilee** [comment]
In a hypothetical programming language, there _are_ uses for matching on NaN, however, in order to achieve anything resembling a coherent semantics in light of the acceptance of RFC 3535, including the motivating reasons there, it would require the introduction of NaN literals (and code generator support for these!). This is because there isn't really a way to write a NaN that isn't generated by an expression, and you can't rely on a specific NaN coming back from any given NaN-generating expression, even the ones that involve bit-level conversions.

The ones that _do_ perform bit-level conversions at least offer an escape hatch in some cases where programmers genuinely do need to inspect and match on the contents of a float that could be NaN, and proceed even if it is NaN: they can do so as if it is a u32.

**Comment by RalfJung** [comment]
What I meant is, matching on NaN with the current semantics is never useful. These are just dead arms since we use "==" semantics.

Changing the semantics to butwise is a much bigger breaking change. For +0 vs -0 I think it would be quite the footgun.

**Comment by RalfJung** [comment]
Based on the [review above](https://github.com/rust-lang/rust/pull/116284#issuecomment-1912812323)
@bors r=cjgillot

**Pull request merged**
