### PR TITLE
Fix c_char on AIX

### LINKED ISSUE #122985: c_char on AIX should be u8
Currently, core::ffi::c_char on AIX is i8, but AFAIK, the default of this platform is unsigned (u8).

[XL C for AIX](https://www.ibm.com/docs/en/xl-c-aix/13.1.3?topic=descriptions-qchars):

> Defaults
> -qchars=unsigned

Clang:

```console
$ clang --version
Homebrew clang version 17.0.6

$ clang -E -dM -x c /dev/null -target powerpc64-ibm-aix | grep __CHAR_        
#define __CHAR_BIT__ 8
#define __CHAR_UNSIGNED__ 1
```

Rust:

```
$ tail -2 src/lib.rs 

const C: core::ffi::c_char = 0u8;

$ cargo check -Zbuild-std=core --target powerpc64-ibm-aix
error[E0308]: mismatched types
    --> src/lib.rs:3972:30
     |
3972 | const C: core::ffi::c_char = 0u8;
     |                              ^^^ expected `i8`, found `u8`
     |
help: change the type of the numeric literal from `u8` to `i8`
     |
3972 | const C: core::ffi::c_char = 0i8;
     |                               ~~
```

cc @ecnelises @bzEq ([target maintainers](https://github.com/rust-lang/rust/blob/548e14b43963882fb758deb89e8258d9b8c2fc2a/src/doc/rustc/src/platform-support/aix.md?plain=1#L7))

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (2f090c30d 2024-03-23)
binary: rustc
commit-hash: 2f090c30ddd6b3bbe5c81c087579a5166e7c7278
commit-date: 2024-03-23
host: aarch64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### PR DESCRIPTION
**Pull request by taiki-e**
Closes https://github.com/rust-lang/rust/issues/122985

### CODE REVIEW

**Comment by bjorn3** [comment]
cc @ecnelises and @bzEq as target maintainers

**Comment by Mark-Simulacrum** [comment]
r? @Mark-Simulacrum 

@rustbot author (while libc is merged)

Per https://github.com/rust-lang/libc/pull/3631#issuecomment-2018138224, it looks like target maintainers are happy with this change, and [our policy](https://std-dev-guide.rust-lang.org/policy/target-code.html) is that no further review for tier-3 targets is required.

**Comment by taiki-e** [comment]
@rustbot ready

https://github.com/rust-lang/rust/pull/124560 which includes libc side change has been merged.

**Comment by riking** [comment]
You still need to remove the Github draft status :slightly_smiling_face:

**Comment by ecnelises** [comment]
Thanks for taking care of this! I did not notice libc has been bumped.

**Pull request merged**
