### PR TITLE
Move to doc links inside the prelude

### PR DESCRIPTION
**Pull request by poliorcetics**
Helps with #75080.

@rustbot modify labels: T-doc, A-intra-doc-links, T-rustdoc

### CODE REVIEW

**Comment by jyn514** [comment]
@bors r+ rollup

Good catch with the `module@vec` :)

**Comment by poliorcetics** [comment]
It's not my achievement, `rustdoc` caught the ambiguity by itself, which is amazing !

**Comment by poliorcetics** [comment]
It fails on the `module@crate::vec` on CI but doesn't on my machine. @jyn514 any idea on how to fix this ?

**Comment by jyn514** [comment]
@poliorcetics try rebasing over master? I might have broken something in #75079 or #75318.

**Comment by poliorcetics** [comment]
Rebasing did nothing (my branch is an hour old at most at this point) and rebuilding from scratch still worked when doing `./x.py doc library/std --stage 1`.

**Comment by jyn514** [comment]
Not sure then, I'll have to debug it. I wish we had https://github.com/rust-lang/rust/issues/75305 :(

**Comment by poliorcetics** [comment]
Exact error:

```
error: `[crate::vec]` cannot be resolved, ignoring it.
  --> library/std/src/prelude/mod.rs:78:19
   |
78 | //! [`std::vec`]: module@crate::vec
   |                   ^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
   |
   = note: `-D intra-doc-link-resolution-failure` implied by `-D warnings`
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

error: aborting due to previous error
```

**Comment by LukasKalbertodt** [comment]
Looks like this PR is already in good hands :) 

r? @jyn514

**Comment by jyn514** [comment]
CI is documenting using stage 0, which doesn't have the latest fixes to intra-doc links. Not sure what this exact failure is from, but this will break anyway when we start linking to associated items (#74489).

@Mark-Simulacrum do you know why mingw-check uses `doc --stage 0 library/std`? Is it just for efficiency? I think we should either ad `-A broken_intra_doc_links` or skip the check altogether if `--stage 1` is too expensive to run.

**Comment by jyn514** [comment]
This would probably work if it went through a full bors build, but then the whole compiler will have broken mingw-check builds on every PR, so I don't want to do that unilaterally.

**Comment by jyn514** [comment]
This was added in 1f7c8967dcb695ebc645c9e920c14c9db1e3a440. @ecstatic-morse, what was the rationale for using --stage 0 instead of --stage 1?

**Comment by poliorcetics** [comment]
The PR that made the change was #71649 if that helps.

**Comment by Mark-Simulacrum** [comment]
--stage 0 is intentionally checked (other stages are checked already on other builders) because we want to ensure that docs are buildable and viewable locally; this means that docs contributors don't need to build anything locally.

In the future I'd like for that to not be necessary, instead that we provide an easy way for a "recent master build" or perhaps nightly to work, but as of now that's not really feasible.

**Comment by poliorcetics** [comment]
I moved the `std::vec` link back to a path, to make it compile and allow this to be merged.

@jyn514 do you think making a note in the tracking issue is possible (both for the affected files as they are found and a more generic one to warn people) ?

**Comment by jyn514** [comment]
> we want to ensure that docs are buildable and viewable locally

Hmm ... if the intra-doc link breaks it will still be _viewable_, there will just be some broken links. What do you think about having `cfg_attr(bootstrap, allow(broken_intra_doc_links))`? That way `x.py doc` still works but we still ensure we have working links on nightly.

Merging this PR since it has good changes :) but I think it's worth continuing the discussion.

@bors r+ rollup

**Comment by Mark-Simulacrum** [comment]
I would prefer to avoid that - we only have a few weeks to go - but if it is truly necessary, then it should go into bootstrap/builder.rs along with other warnings. I can review such a PR.

**Comment by jyn514** [comment]
Well it's not certain that #74489 will get merged before the beta cutoff ... but other issues seems rare enough that we can delay the discussion until then, I agree if it's only 1 or 2 weeks it's not worth special casing and we can just do it after the new release.

**Pull request merged**
