### PR TITLE
Work around bad `ptr::with_addr` codegen in `core::ptr`

### LINKED ISSUE #96152: CHERI-valid pointer stuffing produces worse codegen than an implementation which does huge wrapping offsets
I came across this here: https://github.com/tokio-rs/bytes/pull/542 so I'm raising it more broadly because this seems like a portability hazard. [godbolt demo](https://godbolt.org/z/Kn3Mea4fv)

In a world where we can forget about provenance, one could set the lowest bit in a pointer with this:
```rust
pub fn old_style(a: *mut u8) -> *mut u8 {
    (a as usize | 1) as *mut u8
}
```
But of course we want to have a provenance model, including because we want to support architectures where pointer provenance is checked at runtime. So one might want to implement this function like so to be compatible with CHERI:
```rust
pub fn cheri_compat(a: *mut u8) -> *mut u8 {
    let old = a as usize;
    let new = old | 1;
    let diff = new.wrapping_sub(old);
    a.wrapping_add(diff)
}
```
But that version is slower. Instead of just `mov + or`, it gets compiled to `mov + not + and + and`. Which is very silly. We can get the original codegen back by writing this in a style which is almost certainly invalid on CHERI:
```rust
pub fn fast(a: *mut u8) -> *mut u8 {
    let old = a as usize;
    let new = old | 1;
    a.wrapping_sub(old).wrapping_add(new)
}
```
It doesn't make sense to me that users should have to choose between compatibility with CHERI and avoiding ptr-int-ptr casts while keeping a careful eye out for codegen regressions.

### PR DESCRIPTION
**Pull request by thomcc**
Fixes #96152.

Probably not really the ideal way to fix this, but the ideal way is an LLVM patch (or to make it an intrinsic), and I'm not a compiler person.

### CODE REVIEW

**Comment by thomcc** [comment]
Oof, hm. Well, I wonder if it's even worth keeping the old code given that all current platforms actually support the current way of doing this.

**Comment by thomcc** [comment]
Hm, those are some downright spooky failures.

**Comment by thomcc** [comment]
Uh whelp, no idea why this fails so hard, but some of these failures are pretty spooky (segfaults), so I think that we should just wait for an intrinsic (or an LLVM change that removes the overhead here).

So, there are a few possibilities here:

1. I've written a bug in this implementation. I don't see it, and I got a few others who has been paying more attention to strict provenance to say they don't see it either. But it's possible it's still there.

2. LLVM is miscompiling it. One possible way this might happen is if it sees `self.cast::<u8>().wrapping_sub(self_addr)` results in null, and replaces that, and then mistakenly concludes it has provenance over nothing. I dunno, just a guess.

This... probably doesn't bode well for the `bytes` crate's workaround, which is effectively what this is (and then I tried the trivial variation where I swapped the orders of wrapping_add and wrapping_sub).

Anyway, I can't seem to make this work, but it was worth a shot.

**Comment by thomcc** [comment]
Wait I see a mistake. At least, in my most recent commit.

**Comment by thomcc** [comment]
Okay, the fact that this fails for `self.cast::<u8>().wrapping_sub(self as usize).wrapping_add(addr)` and not for `self.cast::<u8>().wrapping_add(addr).wrapping_sub(self as usize)` is *highly spooky*, but this seems... fine?

**Comment by thomcc** [comment]
Yeah, it's also possible that there's some bug I'm just not seeing in [35f28d8](https://github.com/rust-lang/rust/pull/96538/commits/35f28d8433022ecadff947c2cadd895767a615c7).

**Comment by nikic** [comment]
It does get miscompiled for constant pointers: https://llvm.godbolt.org/z/chr3v7r9z

I thought we had fixed this one already...

**Comment by nikic** [comment]
@thomcc The switched order mostly avoids this, but I'm afraid the issue can still be hit: https://llvm.godbolt.org/z/eG4PMcbhb In this case the two GEPs will be interchanged to move one of them loop invariant, at which point we'd back to the same issue.

**Comment by thomcc** [comment]
Hm, I see. That's unfortunate. Probably enough to not want this change.

**Comment by nikic** [comment]
I've put up https://reviews.llvm.org/D124677 to fix the miscompile.

**Pull request closed without merging**
