### PR TITLE
Optimize &Iterator::nth

### PR DESCRIPTION
**Pull request by Stebalien**
There are actually three changes here:
1. Remove unnecessary `by_ref` calls in the Iterator trait. I needed to remove the `by_ref` call from the `nth` method to make it object safe (`by_ref` isn't object safe) but I ended up removing all of them because they were pointless.
2. :warning: Make `nth` object safe. This changes `nth`'s signature but I'm nearly positive that this change can't break existing code (see the commit message).
3. Override `nth` on `by_ref` iterators to make it call though to `nth` on the underlying implementation (the type behind the reference). This way, if the underlying implementation provides an optimized `nth`, `by_ref` iterators can take advantage of it.

Part of #24214

### CODE REVIEW

**Comment by Stebalien** [comment]
r? aturon

**Comment by Stebalien** [comment]
Feel free to completely ignore this PR till after the 1.0 dust settles.

**Comment by alexcrichton** [comment]
Hm, I agree that I'm not 100% certain that the removal of `where Self: Sized` is OK to do, but I would personally suspect that it's compatible enough to be ok to land.

**Comment by alexcrichton** [comment]
@Stebalien could you back out the removal of `where Self: Sized` for `Iterator::nth`? After some discussion we're thinking that we may want to pursue this at a later date (and perhaps automatically not even require `where Self: Sized` for object safety), but for now it seems odd to make a one-off method on `Iterator` object-safe while leaving behind all the others.

**Comment by Stebalien** [comment]
@alexcrichton unfortunately, not without specialization. I would need `I: Sized` which rust happily informs me I'm not allowed to do:
```rust
error: the requirement `I : marker::Sized` appears on the impl method but not on the corresponding trait method [E0276]
fn nth(&mut self, n: usize) -> Option<I::Item> where I: Sized { (**self).nth(n) }
```

**Comment by alexcrichton** [comment]
Yeah the impl of `Iterator for &mut I` will no longer be able to delegate the `nth` implementation, unfortunately.

**Pull request closed without merging**
