### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #37835, #37840, #37841, #37848, #37876, #37880, #37881, #37882
- Failed merges:

### CODE REVIEW

**Comment by frewsxcv** [comment]
Travis has an error.

**Comment by GuillaumeGomez** [comment]
Travis is weird now. Only one test failed.

**Comment by frewsxcv** [comment]
On each pull request, Travis only builds one of the environments:

https://github.com/rust-lang/rust/blob/master/.travis.yml#L24

Marked by `ALLOW_PR=1`

**Comment by GuillaumeGomez** [comment]
Well, it seems that LLVM didn't build, so...

**Comment by frewsxcv** [comment]
I think `master` might be broken on Travis, so this PR might be alright.

**Pull request merged**
