### PR TITLE
move `const_eval` and `check_match` out of `librustc` into their own crate

### PR DESCRIPTION
**Pull request by oli-obk**
r? @arielb1

### CODE REVIEW

**Comment by arielb1** [comment]
You also have to fix rustdoc

**Comment by oli-obk** [comment]
fixed and ran `make doc`

**Comment by oli-obk** [comment]
travis found a leftover `e` in `middle::const_eval`: https://s3.amazonaws.com/archive.travis-ci.org/jobs/116132961/log.txt

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
rebased

**Comment by oli-obk** [comment]
rustbuild used `../graphviz` instead of `../libgraphviz`

**Comment by oli-obk** [comment]
I managed to get rustbuild to work... `make check` does not much more than `make`, but it works

**Comment by alexcrichton** [comment]
@bors: retry force

One of these days restarting buildbot won't be a multi-hour-long ordeal...

**Pull request merged**
