### PR TITLE
Fix tracking issue for error iterators

### PR DESCRIPTION
**Pull request by sfackler**
r? @withoutboats

### CODE REVIEW

**Comment by withoutboats** [comment]
@sfackler your commit might be dirty, whats this about modifying submodules?

**Comment by withoutboats** [comment]
oh looks like you fixed it

**Comment by haraldh** [comment]
@withoutboats so rename `iter_chain()` to `iter()` ?

**Comment by withoutboats** [comment]
@haraldh We'll discuss it in the tracking issue.

**Pull request merged**
