### PR TITLE
Fix perf regression from Miri Machine trait changes

### PR DESCRIPTION
**Pull request by RalfJung**
Maybe this fixes the perf regression that https://github.com/rust-lang/rust/pull/62003 seemingly introduced?

Cc @nnethercote

### CODE REVIEW

**Comment by RalfJung** [comment]
The build succeeded after the timeout went off... @rust-lang/infra should the timeout be increased?

Let's see if we can time this anyway.
@rust-timer build a36397fa11d1d3c42a1ac182d0159fa152cc005d

**Comment by mati865** [comment]
I think try builds will timeout until https://github.com/rust-lang/rust/pull/62247 is merged.

**Comment by RalfJung** [comment]
That doesn't seem to make a difference. I guess it's time to revert parts of that MR to figure out where it is coming from.

(Please don't merge!)

**Comment by RalfJung** [comment]
@rust-timer build 32136d389b1951d10e042b321b07730c2b175f43

**Comment by RalfJung** [comment]
Yeah, this confirms the perf regression is fixed by reverting the entire PR.

@nnethercote can you explain that? I am completely mystified. That just makes no sense at all. And without any hypothesis what is even causing this, it is very hard to do anything about it.^^

Next run: reverting those parts of the PR that we did just "for consistency", but don't technically *need*.

@bors try

**Comment by RalfJung** [comment]
Ah never kind, [I found it](https://github.com/rust-lang/rust/pull/62003/files#r299381499).

Is there a way to abort the try build?

**Comment by RalfJung** [comment]
If my analysis is correct, this should fix the regression.

@bors try

**Comment by RalfJung** [comment]
@rust-timer build ed4ad9cd1d76cd59e7f8a44227a597b87164ca88

**Comment by RalfJung** [comment]
Perf looks good, confirms my assumption that this fixes the regression. This is ready for review.

**Comment by nnethercote** [comment]
Thank you for hunting this down, RalfJung! For compiler perf, fixing regressions is less glamorous but just as important as writing new optimizations.

**Comment by RalfJung** [comment]
Rebased to fix conflict.

**Pull request merged**
