### PR TITLE
Fix error[E0518] not displayed for #[inline] on structs inside fns

### PR DESCRIPTION
**Pull request by nxnfufunezn**
Fixes : #31769 
r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
LGTM, but it needs a compile-fail test, something along the lines of:
```rust
fn main() {
    #[inline] struct Foo;
    #[repr(C)] fn foo() {}
}
```
Both of those compile right now and neither is valid.

**Comment by nxnfufunezn** [comment]
oops! I always forget about tests..

**Comment by nxnfufunezn** [comment]
@eddyb

**Comment by jonas-schievink** [comment]
Just noting that this is technically a [breaking-change] (with probably no impact)

**Pull request merged**
