### PR TITLE
Rollup of 17 pull requests

### PR DESCRIPTION
**Pull request by oli-obk**
- Successful merges: #25416, #25632, #25653, #25666, #25667, #25681, #25687, #25695, #25697, #25702, #25703, #25709, #25710, #25714, #25715, #25716, #25722
- Failed merges:

### CODE REVIEW

**Comment by oli-obk** [comment]
sorry about that :/ i thought it'd create that branch in my repos only

**Comment by oli-obk** [comment]
stage1 passes

**Comment by oli-obk** [comment]
make check passes

**Comment by steveklabnik** [comment]
wait a minute, why does this have 17 PRs when theres only seven in the queue that are open?

**Comment by oli-obk** [comment]
there are some that are already merged

**Comment by oli-obk** [comment]
oh + the rollup PRs

**Comment by steveklabnik** [comment]
are you on IRC? I'm confused.

**Pull request closed without merging**
