### PR TITLE
make unaligned_references lint deny-by-default and make it show up in future-breakage report

### PR DESCRIPTION
**Pull request by RalfJung**
This lint has been warn-by-default for a year now (since https://github.com/rust-lang/rust/pull/82525), so I think it is time to crank it up a bit. Code that triggers the lint causes UB (without `unsafe`) when executed, so we really don't want people to write code like this.

Also make it show up in future-breakage report.

### CODE REVIEW

**Comment by scottmcm** [comment]
This makes sense to me 👍 

Cap-lints mean it's still not breaking, and this is something that should be fixed before running tests, not left to languish.

**Comment by RalfJung** [comment]
I'd also like this lint to be shown as part of cargo's future-breakage report. (It was literally used as the example in the RFC!)

@Aaron1011 is there anything I have to do to make that happen? In your original PR https://github.com/rust-lang/rust/pull/75534 lints had to be marked with `future_breakage` but that annotation does not exist any more and I don't know if *all* `future_incompatible` lints are now reported or if there is something else that needs to be done.

**Comment by RalfJung** [comment]
(After digging a bit more) I think what I have to do is add
```rust
reason: FutureIncompatibilityReason::FutureReleaseErrorReportNow
```
to the lint declaration. But very few lints have that declaration so I'll hold off on that until I hear back about this.

**Comment by Aaron1011** [comment]
@RalfJung That's correct - that specific variant is required to add it to the report. We should probably check with @rust-lang/compiler before enabling it for this lint, though.

**Comment by pnkfelix** [comment]
> @RalfJung That's correct - that specific variant is required to add it to the report. We should probably check with @rust-lang/compiler before enabling it for this lint, though.

discussed at T-compiler triage meeting.

there's general approval for adding this lint to the future-incompat report now.

**Comment by RalfJung** [comment]
Done that, and blessed the tests. Is there anything else that needs to be done?

**Pull request merged**
