### PR TITLE
Normalize obligations before matching them against a candidate

### LINKED ISSUE #88460: E0277 (bound not satisfied) for bound on generic associated types when combined with HRTB
I tried this code:

```rust
#![feature(generic_associated_types)]

pub trait Marker {}

pub trait Trait {
    type Assoc<'a>;
}

fn test<T>(value: T)
where
    T: Trait,
    for<'a> T::Assoc<'a>: Marker,
{
}

impl Marker for () {}

struct Foo;

impl Trait for Foo {
    type Assoc<'a> = ();
}

fn main() {
    test(Foo);
}
```

I expected it to compile since `T::Assoc<'a>` to my understanding does implement `Marker` when `T` is `Foo`.

Instead we get this error:
```
error[E0277]: the trait bound `for<'a> <_ as Trait>::Assoc<'a>: Marker` is not satisfied
  --> test.rs:25:5
   |
25 |     test(Foo);
   |     ^^^^ the trait `for<'a> Marker` is not implemented for `<_ as Trait>::Assoc<'a>`
   |
note: required by a bound in `test`
  --> test.rs:12:27
   |
9  | fn test<T>(value: T)
   |    ---- required by a bound in this
...
12 |     for<'a> T::Assoc<'a>: Marker,
   |                           ^^^^^^ required by this bound in `test`
```

### Alternatives

An option is lift the `'a` bound to `test`, but that potentially causes other issues down the line like this ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7a63f2c0e506dfb2dddba689e88b0738)):

```rust
#![feature(generic_associated_types)]

pub trait Marker {
    fn reborrow_self(&self) -> &Self;
}

pub trait Trait {
    type Assoc<'a>;

    fn assoc(&self) -> Self::Assoc<'_>;
}

fn test<'a, T>(value: T)
where
    T: 'a + Trait,
    T::Assoc<'a>: Marker,
{
    let assoc = value.assoc();
    assoc.reborrow(); // the lifetime for this reborrow ends up being narrow.
}

impl Marker for () {
    fn reborrow(&self) -> &Self {
        self
    }
}

struct Foo;

impl Trait for Foo {
    type Assoc<'a> = ();

    fn assoc(&self) -> Self::Assoc<'_> {
        ()
    }
}

fn main() {
    test(Foo);
}
```

Error:

```text
error[E0597]: `value` does not live long enough
  --> test.rs:18:17
   |
13 | fn test<'a, T>(value: T)
   |         -- lifetime `'a` defined here
...
18 |     let assoc = value.assoc();
   |                 ^^^^^--------
   |                 |
   |                 borrowed value does not live long enough
   |                 argument requires that `value` is borrowed for `'a`
19 |     assoc.borrow();
20 | }
   | - `value` dropped here while still borrowed

For more information about this error, try `rustc --explain E0597`.
error: could not compile `audio` due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (5eacec9ec 2021-08-28)
binary: rustc
commit-hash: 5eacec9ec7e112a0de1011519a57c45586d58414
commit-date: 2021-08-28
host: x86_64-pc-windows-msvc
release: 1.56.0-nightly
LLVM version: 13.0.0
```

I somewhat expected this to be addressed by #56556 given there there appears to be some overlap with the list of available bugs, ,but that doesn't seem to be the case as of 2021-08-28 nightly (assuming it's in there).

I also apologize if this is a duplicate. I tried my best to grok the existing set of issues to see if this was applicable to one of them.

### LINKED ISSUE #89196: HRTB bounds not resolving correctly (take 2)
This is similar to the resolved issue https://github.com/rust-lang/rust/issues/85636 , but details a newer iteration of that problem that has not yet been fixed.

<details><summary>Code example</summary>

```rust
trait MiniYokeable<'a> {
    type Output;
}

struct MiniYoke<Y: for<'a> MiniYokeable<'a>> {
    pub yokeable: Y,
}

impl<Y> Clone for MiniYoke<Y>
where
    Y: for<'a> MiniYokeable<'a>,
    for<'a> <Y as MiniYokeable<'a>>::Output: Clone
{
    fn clone(&self) -> Self {
        todo!()
    }
}

trait MiniDataMarker {
    type Yokeable: for<'a> MiniYokeable<'a>;
}

trait MiniDataProvider<M>
where
    M: MiniDataMarker
{
    fn mini_load_payload(&self) -> MiniYoke<M::Yokeable>;
}

struct MiniStructProvider<M>
where
    M: MiniDataMarker,
{
    pub yoke: MiniYoke<M::Yokeable>,
}

impl<M> MiniDataProvider<M> for MiniStructProvider<M>
where
    M: MiniDataMarker,
    for<'a> <M::Yokeable as MiniYokeable<'a>>::Output: Clone,
{
    fn mini_load_payload(&self) -> MiniYoke<M::Yokeable> {
        self.yoke.clone()
    }
}

#[derive(Clone)]
struct SimpleStruct(pub u32);

impl<'a> MiniYokeable<'a> for SimpleStruct {
    type Output = SimpleStruct;
}

impl MiniDataMarker for SimpleStruct {
    type Yokeable = SimpleStruct;
}

fn main() {
    let provider = MiniStructProvider {
        yoke: MiniYoke {
            yokeable: SimpleStruct(42)
        }
    };

    let yoke: MiniYoke<SimpleStruct> = provider.mini_load_payload();
    assert_eq!(yoke.yokeable.0, 42);
}
```

</summary>

([playpen](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=025e2d4cefe09821650352a935b0baed))

This fails to compile on beta/nightly (stable does not have https://github.com/rust-lang/rust/pull/85499 so we cannot expect this to compile) with:

```
error[E0599]: the method `mini_load_payload` exists for struct `MiniStructProvider<_>`, but its trait bounds were not satisfied
  --> src/main.rs:65:49
   |
30 | / struct MiniStructProvider<M>
31 | | where
32 | |     M: MiniDataMarker,
33 | | {
34 | |     pub yoke: MiniYoke<M::Yokeable>,
35 | | }
   | | -
   | | |
   | |_method `mini_load_payload` not found for this
   |   doesn't satisfy `MiniStructProvider<_>: MiniDataProvider<_>`
...
65 |       let yoke: MiniYoke<SimpleStruct> = provider.mini_load_payload();
   |                                                   ^^^^^^^^^^^^^^^^^ method cannot be called on `MiniStructProvider<_>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `<_ as MiniYokeable<'a>>::Output: Clone`
           which is required by `MiniStructProvider<_>: MiniDataProvider<_>`
```

The trait is implemented here: `for<'a> <SimpleStruct as MiniYokeable>::Output` is just `SimpleStruct`, which implements Clone.

cc @jackh726 @sffc

### LINKED ISSUE #90950: HRTB bounds not resolving correctly (take 3, lifetimes on the RHS)
This is a new version of https://github.com/rust-lang/rust/issues/85636 and https://github.com/rust-lang/rust/issues/89196 . When reporting it I first hit an ICE which got fixed in https://github.com/rust-lang/rust/issues/90638.

The basic idea is that bounds of the form `for<'a> <Type as Trait<'a>>::AssocType: OtherTrait<'a>` don't work. https://github.com/rust-lang/rust/issues/85636, which has since been fixed, is about this same issue without a lifetime on the right side of the bound. This will likely also be a problem for GATs.

The commented out code is not necessary for it to work, but it gives an idea of why such a bound might be necessary.

<details>

```rust
trait Yokeable<'a>: 'static {
    type Output: 'a;
}


trait IsCovariant<'a> {}

struct Yoke<Y: for<'a> Yokeable<'a>> {
    data: Y,
}


// impl<Y: for<'a> Yokeable<'a>> Yoke<Y> {
//     fn project<Y2: for<'a> Yokeable<'a>>(&self, f: for<'a> fn(<Y as Yokeable<'a>>::Output, &'a ()) -> <Y2 as Yokeable<'a>>::Output) -> Yoke<Y2> {
//         unimplemented!()
//     }
// }

fn upcast<Y>(x: Yoke<Y>) -> Yoke<Box<dyn IsCovariant<'static> + 'static>> where
    Y: for<'a> Yokeable<'a>,
    for<'a> <Y as Yokeable<'a>>::Output: IsCovariant<'a>
    {
    // x.project(|data, _| {
    //     Box::new(data)
    // })
    unimplemented!()
}


impl<'a> Yokeable<'a> for Box<dyn IsCovariant<'static> + 'static> {
    type Output = Box<dyn IsCovariant<'a> + 'a>;
}

// this impl is mostly an example and unnecessary for the pure repro
use std::borrow::*;
impl<'a, T: ToOwned + ?Sized> Yokeable<'a> for Cow<'static, T> {
    type Output = Cow<'a, T>;
}
impl<'a, T: ToOwned + ?Sized> IsCovariant<'a> for Cow<'a, T> {}



fn upcast_yoke(y: Yoke<Cow<'static, str>>) -> Yoke<Box<dyn IsCovariant<'static> + 'static>> {
    upcast(y)
}

fn main() {}
```

<details>

([playpen](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=81f4af21c188ad79272d58458986fb3c))

The error shown is:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `for<'a> <_ as Yokeable<'a>>::Output: IsCovariant<'a>` is not satisfied
  --> src/main.rs:44:5
   |
44 |     upcast(y)
   |     ^^^^^^ the trait `for<'a> IsCovariant<'a>` is not implemented for `<_ as Yokeable<'a>>::Output`
   |
note: required by a bound in `upcast`
  --> src/main.rs:21:42
   |
19 | fn upcast<Y>(x: Yoke<Y>) -> Yoke<Box<dyn IsCovariant<'static> + 'static>> where
   |    ------ required by a bound in this
20 |     Y: for<'a> Yokeable<'a>,
21 |     for<'a> <Y as Yokeable<'a>>::Output: IsCovariant<'a>
   |                                          ^^^^^^^^^^^^^^^ required by this bound in `upcast`
```

which is incorrect, that bound _is_ satisfied here.

I'm currently working on rustc master (d914f17ca71a33a89b2dc3436fca51b1a091559e) so that I can have the fix for https://github.com/rust-lang/rust/issues/90638, though that fix is not necessary for the commented-out version of my code to work. This should be available on nightly soon.

cc @jackh726 @eddyb

### PR DESCRIPTION
**Pull request by oli-obk**
Noticed again during https://github.com/rust-lang/rust/pull/108860

When we are matching an impl against a predicate obligation, we normalize the impl predicate, but not the obligation predicate, causing errors like `trait bound for<'a> <Type as Trait>::Assoc<'a>: OtherTrait is not satisfied`, even though we have all the information available to figure out that the associated type is a type that implements `OtherTrait`. 

r? types

fixes #88460
fixes #90950
fixes #89196

### CODE REVIEW

**Review by lcnr — COMMENTED** [review]
we tend to assume that `obligation` is already normalized. fulfill has an explicit normalization step, maybe we should also explicitly normalize at the start of evaluate instead? That should supersede both this PR and #103695

**Comment by oli-obk** [comment]
I guess we can leave this for the new trait solver.

The issue is with the existing normalization during `process_obligation`. This PR does the normalization after replacing bound vars with inference vars, where it trivially succeeds (by replacing the projection with an inference var). So... I guess the right solution would be to look into https://github.com/rust-lang/rust/blob/7c306f6dcd600b1fcc74439c780e8ebef338d84c/compiler/rustc_trait_selection/src/traits/project.rs#L566-L576 after https://github.com/rust-lang/rust/pull/108860

**Comment by aliemjay** [comment]
Doesn't this have the same problems as @BoxyUwU's attempt at [deferred projection equality](https://hackmd.io/CxNdsDTKQUKFImAOkqGrtQ)? particularly the type enum regression.

**Comment by jackh726** [comment]
I'm really not sure what the state of this is. r? @lcnr

**Comment by oli-obk** [comment]
Closing this PR as it's a very lazy (as in, the work I did) approach to the problem that has unclear effects on other parts of trait solving. We'll wait for the new solver to land and then try again.

**Pull request closed without merging**
