### PR TITLE
Allow to click on setting text

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
You can test it [here](https://rustdoc.crud.net/imperio/gui-settings-text-click/doc/foo/index.html).

This PR allows to click on the text alongside the toggle to change it.

r? @jsha

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed the eslint error.

**Comment by jsha** [comment]
The correct way to do this is not with an onclick handler, it's by putting the text inside a `<label>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by GuillaumeGomez** [comment]
I was able to fix the bug and to simplify the code thanks to @jsha's comment. :)

The demo is available [here](https://rustdoc.crud.net/imperio/gui-settings-text-click/doc/foo/index.html).

**Pull request merged**
