### PR TITLE
Feature gate Self and associated types in struct expressions and patterns

### PR DESCRIPTION
**Pull request by petrochenkov**
cc https://github.com/rust-lang/rust/issues/37544
Fixes https://github.com/rust-lang/rust/pull/37035#issuecomment-258003420
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Thanks @petrochenkov, you're awesome.

**Comment by arielb1** [comment]
```
thread '<unnamed>' panicked at 'failed to generate documentation: Error { file: "/buildslave/rust-buildbot/slave/auto-linux-cross-opt/build/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-gnu/doc/src/rustc_unicode", error: Error { repr: Os { code: 28, message: "No space left on device" } } }', /buildslave/rust-buildbot/slave/auto-linux-cross-opt/build/src/libcore/result.rs:837
```

@bors retry

**Pull request merged**
