### PR TITLE
Simplify FFI calls for `-Ztime-llvm-passes` and `-Zprint-codegen-stats`

### PR DESCRIPTION
**Pull request by Zalathar**
The existing code for these unstable LLVM-infodump flags was jumping through hoops to pass an allocated C string across the FFI boundary, when it's much simpler to just write to a `&RustString` instead.

### CODE REVIEW

**Comment by Zalathar** [comment]
(Alternatively we could just delete these, but they do seem plausibly useful to somebody, and with the new implementation they’re not so bad.)

**Comment by Nadrieril** [comment]
Looks reasonable enough, but 

r? compiler

**Comment by fee1-dead** [comment]
r? compiler

**Comment by jieyouxu** [comment]
r? jieyouxu

**Review by jieyouxu — APPROVED** [review]
Makes sense, thanks!

**Pull request merged**
