### PR TITLE
Allow tests to specify a `//@ filecheck-flags:` header

### PR DESCRIPTION
**Pull request by Zalathar**
This allows individual codegen/assembly/mir-opt tests to pass extra flags to the LLVM `filecheck` tool as needed.

---

The original motivation was noticing that `tests/run-make/instrument-coverage` was very close to being an ordinary codegen test, except that it needs some extra logic to set up platform-specific variables to be passed into filecheck.

I then saw the comment in `verify_with_filecheck` indicating that a `filecheck-flags` header might be useful for other purposes as well.

### CODE REVIEW

**Comment by Zalathar** [comment]
Updated for #121370.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Awesome, always nice to see `run-make` tests getting migrated into regular compiler tests!

@bors r+ rollup

**Comment by Zalathar** [comment]
Looks like this got caught up in whatever CI failure has the tree closed at the moment.

**Comment by ehuss** [comment]
@bors retry

ghcr.io network error

**Pull request merged**
