### PR TITLE
First-class struct and tuple constants

### LINKED ISSUE #23260: Allow first-class struct and tuple constants
The following code should compile, but does not:

```
struct MyStruct { field: usize }
struct Nested { nested: MyStruct }
struct Mix2 { nested: ((usize,),) }
 
const STRUCT: MyStruct = MyStruct { field: 42 };
const TUP: (usize,) = (43,);
const NESTED_S: Nested = Nested { nested: MyStruct { field: 5 } };
const NESTED_T: ((usize,),) = ((4,),);
const MIX_1: ((Nested,),) = ((Nested { nested: MyStruct { field: 3 } },),);
const MIX_2: Mix2 = Mix2 { nested: ((2,),) };
const INSTANT_1: usize = (MyStruct { field: 1 }).field;
const INSTANT_2: usize = (0,).0;
 
fn main() {
    let a = [0; STRUCT.field];
    let b = [0; TUP.0];
    let c = [0; NESTED_S.nested.field];
    let d = [0; (NESTED_T.0).0];
    let e = [0; (MIX_1.0).0.nested.field];
    let f = [0; (MIX_2.nested.0).0];
    let g = [0; INSTANT_1];
    let h = [0; INSTANT_2];
}
```

### PR DESCRIPTION
**Pull request by aochagavia**
Fixes #23260 

r? @eddyb

### CODE REVIEW

**Comment by aochagavia** [comment]
Needs a rebase... I'm on it

**Comment by aochagavia** [comment]
Rebased!

**Comment by eddyb** [comment]
You should never clone AST nodes if you can avoid it.
Thankfully, the AST is borrowed by tcx.map so you can freely pass `&'tcx ast::Expr` around and whatnot.

**Comment by aochagavia** [comment]
When I first tried storing an `&ast::Expr`, I got stuck in lifetime hell because the new lifetime parameter of `const_val` required adding lifetimes to other enums as well. I think a better solution is to store the `NodeId` in the `Struct` and `Tuple` variants and to use `tcx.map.expect_expr(id)` to retrieve the `&Expr` back. Do you think this is a correct approach?

I am building rustc again to see if it works. It will take some time because for some reason LLVM is being compiled again.

**Comment by eddyb** [comment]
@aochagavia that's a good idea, for some reason I didn't expect adding a lifetime `const_val` to propagate outside that module (or only to types that already had `'tcx`), my bad.

**Comment by aochagavia** [comment]
@eddyb I have pushed the changes now

**Pull request merged**
