### PR TITLE
Fix RFC-1014 test

### PR DESCRIPTION
**Pull request by tmiasko**
Use two printlns when testing that writing to a closed stdout does not
panic. Otherwise the test is ineffective, since the current implementation
silently ignores the error during first println regardless.

### CODE REVIEW

**Comment by tmiasko** [comment]
Created in part to test @workingjubilee theory that there is an existing, but undetected issue on wasm32-unknown-emscripten target (although the fixed test does pass for me locally), cc @Lucretiel.

**Comment by Lucretiel** [comment]
> Otherwise the test is ineffective, since the current implementation silently ignores the error during first println regardless.

Do you mean that this first ignore is independent of the (`handle_ebadf`)[https://github.com/rust-lang/rust/blob/ac48e62db85e6db4bbe026490381ab205f4a614d/library/std/src/io/stdio.rs#L236-L241] used in (`Maybe::write`)[https://github.com/rust-lang/rust/blob/ac48e62db85e6db4bbe026490381ab205f4a614d/library/std/src/io/stdio.rs#L181-L186]? This would be news to me, do you know where this first error ignore is happening?

**Comment by tmiasko** [comment]
It is consequence of the fact that flushing is driven internally rather than
externally. 

For example, "hello world\n" is written to the internal buffer successfully.
It ends with a newline, and a flush attempt is made. It fails, but since input
is already buffered the writer returns Ok(12) indicating that all data had been
written, while marking that a writer needs to be flushed. On the next write
attempt, flush will happen first and an error is returned.

Maybe saying that return of the error is delayed would be more accurate.

**Comment by Lucretiel** [comment]
Oh! OH! OHHH! That explains it! That explains why my PR breaks this test, because one of the core design goals is cleaning up the error suppressing behavior of the current `LineWriter`!

**Comment by workingjubilee** [comment]
Excellent synthesis! I hope this proves revealing.

**Comment by Lucretiel** [comment]
Might be worth changing /src/test/ui/rfcs/rfc-1014-2.rs to match.

**Comment by tmiasko** [comment]
Updated rfc-1014-2.rs test case as well.

**Comment by tmiasko** [comment]
The error number mismatch on the CI was fixed by #75569, and this should be working correctly now.

**Pull request merged**
