### PR TITLE
parent_module_from_def_id does not need to be a query.

### PR DESCRIPTION
**Pull request by cjgillot**
r? @ghost

### CODE REVIEW

**Review by compiler-errors — COMMENTED** [review]
i know this is a draft, but r=me if perf comes back well

edit: huh, actually maybe need to look at the rustdoc failure first?

**Comment by cjgillot** [comment]
r? @compiler-errors 

The first commit was buggy, `parent_module_from_def_id(id)` would return `id`, which made rustdoc misbehave.
This version corrects the bug, and accurately returns the closest strict parent which is a module.

**Pull request merged**
