### PR TITLE
Add contains_key to SortedIndexMultiMap

### PR DESCRIPTION
**Pull request by Jesse-Bakker**

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Do you have a need for this? This is simple so it seems fine anyways, but we usually only add these methods as needed.

**Comment by Nilstrieb** [comment]
Do you have a need for this? This is simple so it seems fine anyways, but we usually only add these methods as needed.

**Comment by Nilstrieb** [comment]
r? Nilstrieb
Looks good, if you've had a need the we can definitely add it.

**Review by Noratrieb — APPROVED** [review]

**Pull request merged**
