### PR TITLE
Stop using a string literal as a format argument

### PR DESCRIPTION
**Pull request by TaKO8Ki**

### CODE REVIEW

**Comment by compiler-errors** [comment]
@TaKO8Ki, one line PRs like this are (in my opinion) not significant enough to review... Performance hasn't changed and readability only increased slightly.

Do you mind including changes like this in a more significant PR when you're editing code near by, instead of putting up such small changes independently? Thanks!

**Comment by TaKO8Ki** [comment]
@compiler-errors 
I completely agree with you. However, when reading the rustc code, I sometimes find strange programs like this one, so I created this patch for it because I don't feel comfortable leaving it as it is, just like a typo.

**Comment by compiler-errors** [comment]
I am just confused why not all of the usages were fixed in this file, or even (if i saw correctly) in this function? I recommend batching at least a few of these into a PR, so we don't have a lot of tiny commits in the logs..

**Comment by TaKO8Ki** [comment]
@compiler-errors 
This is because the main point of this pull request is not to use `format-args-capture`, but to stop using a string literal as a format argument like the following. The former is what I did incidentally.

```diff
- format!("{}{}", snippet, ".collect::<Vec<_>>()"),
+ format!("{}.collect::<Vec<_>>()", snippet),
```

Should I make additional changes like #96065?

**Comment by compiler-errors** [comment]
I am still not convinced that this change does anything meaningful, but also I will not block it. Thanks for making this contribution -- but also keep this in mind when putting up one-line changes like this that don't affect performance or readability :sweat_smile: 

If you want to change more spots to use format-args-capture, then at least please batch it together, maybe a few crates together at once.

@bors r+ rollup=always

**Comment by TaKO8Ki** [comment]
@compiler-errors 
I'm sorry. I understand.

**Pull request merged**
