### PR TITLE
Improve documentation for Iterator's methods

### PR DESCRIPTION
**Pull request by steveklabnik**
This cleans up descriptions, adds more examples, and increases
consistency between similar methods.

### CODE REVIEW

**Comment by apasel422** [comment]
Hmm, the diff is too big to leave inline comments.

**Comment by steveklabnik** [comment]
@apasel422 oh no :(

**Comment by killercup** [comment]
https://github.com/rust-lang/rust/pull/29311.patch is the raw diff, waiting to be opened in your favorite editor 😄

**Comment by alexcrichton** [comment]
Hm, @steveklabnik could you split up this commit perhaps for now to review? Without that there's basically no way to easily review this...

**Comment by steveklabnik** [comment]
@alexcrichton split it up into a bunch of smaller ones. github still shows it as one thing due to it all being in one file, it looks like :/

**Comment by nagisa** [comment]
A common problem with most of the descriptions is use of word “closure” to mean “anything that satisfies `Fn{,Mut,Once}`”. You can easily pass regular functions to most of the iterators too.

That being said, I have no idea how to word it better so it is as concise and more correct.

**Comment by steveklabnik** [comment]
@nagisa yeah, it takes a closure, but you can convert a function pointer to a closure.

**Comment by steveklabnik** [comment]
Okay, fixed up @nagisa 's issues, and re-broke them out.

**Comment by steveklabnik** [comment]
Oh, and this PR is part of https://github.com/rust-lang/rust/issues/29360

**Comment by alexcrichton** [comment]
Whew, awesome patch @steveklabnik! Just some minor nits here and there, but otherwise r=me with those addressed.

**Comment by steveklabnik** [comment]
@bors: r=alexcrichton

(I forgot to re-run the tests since i modified some of them, whoops! all pass now)

**Pull request merged**
