### PR TITLE
Add an item-info for non-public visibility, and remove redundant `pub`

### PR DESCRIPTION
**Pull request by jsha**
For most documentation, the `pub` in front of each method is redundant: you know the method is public because you are reading the documentation.

However, when running with `--document-private`, it's important to see which items are public and which are private. This adds an item-info tag for private items showing their visibility, and removes the `pub` from methods and fields.

This doesn't currently touch the summary code block at the top of the page, which will still have `pub` or `pub(crate)` or whatever is appropriate.

This refactors some code in Visibility to allow better reuse.

Part of #59829. Note: [one of the pieces of feedback](https://github.com/rust-lang/rust/issues/59853) there was that the item-infos (experimental, deprecated, platform-specific, etc) are too prominent. That may be the case, but for this change, I think the important thing is matching the other item-infos, and we can change the style of item-infos later if we want to.

r? @GuillaumeGomez
/cc @camelid 

Demo:

https://jacob.hoffman-andrews.com/rust/document-private/foo/outer_mod/inner_mod/inmost_mod/struct.Boo.html
https://jacob.hoffman-andrews.com/rust/document-private/foo/outmost_mod/outer_mod/inner_mod/inmost_mod/struct.Foo.html
https://jacob.hoffman-andrews.com/rust/document-private/foo/outmost_mod/outer_mod/inner_mod/inmost_mod/enum.Bar.html

image

### CODE REVIEW

**Comment by camelid** [comment]
> This doesn't make the visibility display dependent on the --document-private-items flag. It removes pub from struct methods in all cases. The changes to --document-private-items are a followup from your comment a few months ago: if we omit pub from certain places, we need a way to distinguish things that are private.

Sorry, I wasn't clear. I was referring to Mark's suggestion from above:

> Perhaps we can instead only emit visibility annotations if --document-private-items is passed, but not modify their style? These feel like orthogonal changes to me.

-----

> `@Mark-Simulacrum` said:
> 
> > I'd personally rather avoid having rustdoc invent a new way of describing privacy -- and the lack of a visibility label does not imply public in most Rust code, so it seems surprising to take that approach here.
> 
> This is not really a new way to describe privacy: It's how privacy is described at https://doc.rust-lang.org/reference/visibility-and-privacy.html:
> 
> > By default, everything in Rust is _private_
> 
> The difference is that privacy is expressed one way in the code, and one way in the reference documentation. I think it makes sense to align rustdoc with the reference documentation rather than the code. The code expression is geared towards one use case: privacy should be the default. The documentation expression should be geared towards another use case: public visibility is the default.

What do you mean by the way privacy is expressed in the Reference documentation? The Rust Reference should be describing how Rust source code works. Where does the Reference say that public visibility is the default? I want to make sure we're not miscommunicating :)

-----

> Would this idea improve things? If a struct is private, we would mark that struct private at the top of its page, but we would not separately annotate its fields and methods as private, since that is implied by the struct being private.

It's hard for me to know without experiencing it first-hand. I wonder if we could consider changing the UI behind a feature flag so we could get practical experience with it before landing it for all users?

> Also, I'd be really interested to hear more details about your workflow - what crates do you use `--document-private` on, and what tasks are you looking to accomplish when you do? Are they mostly crates that will eventually be published? Or are they crates where everything is perpetually private?

Mostly, I'm referring to the rustc and rustdoc API docs (/nightly/nightly-rustc), which I use frequently while working on Rust. I also sometimes use `--document-private-items` with a private side project (that's an executable, not a library), but not very frequently. I also sometimes document rust-lang/triagebot with private items when working on it.

For the most part, I use `--document-private-items` to be able to easily browse large and/or unfamiliar codebases and as a quick way to search for items I see in the code that I want to learn more about.

-----

Overall, part of the issue is that I and others, like Mark, are used to the docs the way they are. Thus, it's hard for me to tell whether changing the format would be an improvement or regression, and either way, I'd have to get used to the new UI. Like I mentioned above, maybe we could figure out a way to land this behind a feature flag (or, rather, an unstable CLI flag)? Otherwise, it feels like we have to commit to the new UI before even trying it out "in the wild".

**Comment by JohnCSimon** [comment]
ping from triage:
@jsha  
Returning to you to address build failures and after that, please switch back to `S-waiting-on-review`.
thanks.

@rustbot label: +S-waiting-on-author -S-waiting-on-review

**Comment by Dylan-DPC** [comment]
@jsha any updates on this?

**Comment by camelid** [comment]
I still prefer the current approach of trying to match source code syntax. And, if we were to switch to a less-close-to-syntax approach, I quite dislike using "item-infos" since they're very visually noisy.

**Comment by jsha** [comment]
Yeah, I agree item-info is not the way to go here. I hadn't really grokked how much people use rustdoc to navigate private aspects of a crate. Closing for now; I'll try again with a different approach later.

**Pull request closed without merging**
