### PR TITLE
Punctuation and clarity fixes.

### PR DESCRIPTION
**Pull request by jimmantooth**

### CODE REVIEW

**Comment by aidanhs** [comment]
Thanks for the PR! We'll check in now and again to make sure @steveklabnik or another reviewer gets to this soon.

**Comment by carols10cents** [comment]
review ping for you @steveklabnik !

**Comment by shepmaster** [comment]
No comment from @steveklabnik in over a week; picking new reviewer from @rust-lang/docs:

r? @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
@bors r+ rollup

Sorry this fell through the cracks! Thanks so much!

**Pull request merged**
