### PR TITLE
[perf] More span update benchmarking

### PR DESCRIPTION
**Pull request by petrochenkov**
https://github.com/rust-lang/rust/pull/126544#issuecomment-2173187242

### CODE REVIEW

**Comment by nnethercote** [comment]
Nice simplification.

@bors r+

**Comment by petrochenkov** [comment]
@nnethercote 
I never intended to merge this, it was just an experiment.
I've even explicitly set the label to waiting on author.

**Comment by nnethercote** [comment]
Waiting on author is not an obvious signal, it's very easy to overlook. Next time I suggest one or more of the following.
- Mark it as a draft.
- Put "[DO NOT MERGE]" or "[EXPERIMENT]" or something more obvious in the title.
- Write a better PR description.
- Use `r? @ghost` as the reviewer.

**Comment by petrochenkov** [comment]
Labels are important, most important from what you've listed, and they also subsume the draft mark entirely as a better tool.
Merging a PR without a description is also pretty questionable.
I guess I'll use more big letters as a precaution next time.

**Comment by petrochenkov** [comment]
`issue-58319` has a very significant regression (5-10x significance factor), so I expected it to have some unusual statistics, e.g. many `PartiallyInterned`s.
But that's not the case, all the updates in that test are still `InlineCtxt`s!
Apparently it's just the same kind of inlining noise as in other cases.

**Pull request merged**
