### PR TITLE
Remove bitrig support from rust

### LINKED ISSUE #60743: Remove Bitrig support
Bitrig is a now defunct OpenBSD fork. It has been mostly successful and some of it's changes have been merged back into OpenBSD. It's development has halted ~2 years ago, and it never got another release after 1.0 in 2014.

Rust had some limited support for Bitrig (as a Tier 3 platform). I think we should remove the support to clean up the libstd code a bit.

(inspired by https://github.com/rust-lang/rust-forge/pull/165, which just unlists it)

### PR DESCRIPTION
**Pull request by hellow554**
Resolves #60743

using `find` and `rg` I delete every occurence of "bitrig" in the sources, expect for the llvm submodule (is this correct?).

There's also this file https://github.com/rust-lang/rls/blob/5b8e99bb61958ca8abcb7c5eda70521726be1065/rls-analysis/test_data/rust-analysis/libstd-af9bacceee784405.json which contains a bitrig string in it. What to do with that?

### CODE REVIEW

**Comment by hellow554** [comment]
Ping @joshtriplett . Are you having time for this or should I choose another reviewer?

**Comment by joshtriplett** [comment]
On May 14, 2019 1:50:35 AM PDT, Marcel Hellwig <notifications@github.com> wrote:
>Ping @joshtriplett . Are you having time for this or should I choose
>another reviewer?

Looks generally reasonable to me. r=me if it passes CI. Currently traveling, though, so feel free to pick another reviewer.

**Comment by hellow554** [comment]
Happy traveling then :) 

@bors r=joshtriplett

**Pull request merged**
