### PR TITLE
Iterate on crate_inherent_impls for metadata.

### PR DESCRIPTION
**Pull request by cjgillot**
Split from #80347

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
Huh... this regresses rustdoc? Idk how rustdoc handles metadata, but that seems very odd. Should we ping the rustdoc team?

**Comment by cjgillot** [comment]
TBH, all the differences are <1%, so I barely looked at them.

**Comment by oli-obk** [comment]
Yea... I'm fine regressing rustdoc a bit, but it would still be nice to track it, since it seems like a symptom of a deeper thing (I don't think this PR should affect rustdoc, and the fact that it does speaks for rustdoc doing something odd)

@bors r+

**Pull request merged**
