### PR TITLE
[perf experiment] Enable overflow checks for not-std

### PR DESCRIPTION
**Pull request by Noratrieb**
r? @ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
While instruction counts look scary, cycles are almost unmoved, and bootstrap also wasn't regressed almost at all. It makes the compiler library ~3MiB larger though, that's interesting.

**Comment by Nilstrieb** [comment]
An overflow check is an instruction, but an extremely well predicted branch, so I think that difference makes sense. We haven't had many bugs caught with overflow checks (though to be fair, they've never been in dist, so we've only partially turned the lights on in matthias' fuzzing), but I don't think we should enable them with these results. If we could get the regressions down with a few well-placed `wrapping_*`, it might be worth it.

**Comment by Kobzol** [comment]
We could also just enable them on some selected CI runners (assuming that we don't do that already).

**Comment by Nilstrieb** [comment]
We already have debug assertions CI. @saethlin suggested a crater run here, which might reveal something interesting.
@craterbot build

**Comment by Nilstrieb** [comment]
@craterbot run mode=build-only

**Comment by saethlin** [comment]
The run found a bug: https://crater-reports.s3.amazonaws.com/pr-119440/try%23fe8f664b41f030f307cfeb6cb8c3a1419292aeed/reg/dialectic-macro-0.1.0/log.txt

**Comment by saethlin** [comment]
Ah, the problem is that `Parser` only uses a `u16` for the number of angle brackets we've seen.

**Comment by Nilstrieb** [comment]
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-119440/retry-regressed-list.txt

**Comment by alex** [comment]
FWIW, in an attempt to minimize the overhead, a number of years ago I tried an approach of only enabling overflow checks for `usize` ops: https://github.com/rust-lang/rust/pull/58475

At the time I hit a number of LLVM missed-optimizations, where overflow checks were not removed when they should have been. It appears that at some point, they got resolved, so that approach may be a practical middle ground.

**Comment by Nilstrieb** [comment]
I filed #119497 for the one bug found. Let's see whether a few cleverly placed (not very clever, just threw wrapping_* all over the place where perf complained) wrapping_* help mitigate the performance impact.
@bors try @rust-timer queue

**Comment by Nilstrieb** [comment]
hm, maybe i should propose merging this, lol. it's perf neutral in cycles

**Pull request closed without merging**
