### PR TITLE
even more unify Projection/Opaque handling in region outlives code

### PR DESCRIPTION
**Pull request by aliemjay**
edit: This continues ate the same pace as #106829. New changes are described in https://github.com/rust-lang/rust/pull/106910#issuecomment-1383251254.
 

~This touches `OutlivesBound`, `Component`, `GenericKind` enums.~

r? @oli-obk (because of overlap with #95474)

### CODE REVIEW

**Comment by compiler-errors** [comment]
lol, this basically duplicates #106829 I think?

**Comment by aliemjay** [comment]
Wow, what a strange coincidence!

@compiler-errors I think we can land yours first, and then I will update mine based on that. This is because this PR contains more involved changes, specifically the EscapingAlias change, which should fix an ICE in the following snippet (this remembers me to add a test):
```rust
#![feature(type_alias_impl_trait)]
type Ty<'a> = impl Sized + 'a;
fn define<'a>() -> Ty<'a> {}
fn test(_: &'static fn(Ty<'_>)) {}
```
Additionally this also introduces `AliasTy::{kind,to_ty}` which allows us to get rid of `AliasKind`.

**Comment by oli-obk** [comment]
@bors delegate+

r=me with perf clean

**Comment by oli-obk** [comment]
A moderate regression in diesel. We should cachegrind it to see if it's something obvious

**Comment by oli-obk** [comment]
Cachegrind says 

```
113,350,107  ???:<alloc::vec::Vec<rustc_middle::ty::sty::Binder<rustc_middle::ty::OutlivesPredicate<rustc_middle::ty::Ty, rustc_middle::ty::sty::Region>>> as alloc::vec::spec_from_iter::SpecFromIter<rustc_middle::ty::sty::Binder<rustc_middle::ty::OutlivesPredicate<rustc_middle::ty::Ty, rustc_middle::ty::sty::Region>>, core::iter::adapters::inspect::Inspect<core::iter::adapters::chain::Chain<core::iter::adapters::filter::Filter<core::iter::adapters::filter_map::FilterMap<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::Predicate>>, <rustc_infer::infer::outlives::verify::VerifyBoundCx>::collect_outlives_from_predicate_list<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::Predicate>>>::{closure
-64,527,904  ???:<rustc_infer::infer::outlives::verify::VerifyBoundCx>::param_bound
 14,731,334  ???:<rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::FallibleTypeFolder>::try_fold_ty
-13,297,583  ???:<rustc_borrowck::constraint_generation::ConstraintGeneration as rustc_middle::mir::visit::Visitor>::visit_basic_block_data
 10,924,743  ???:<rustc_infer::infer::at::At as rustc_trait_selection::traits::project::NormalizeExt>::normalize::<rustc_middle::ty::InstantiatedPredicates>
 10,799,485  ???:rustc_borrowck::constraint_generation::generate_constraints
-10,150,298  ???:<rustc_middle::ty::InstantiatedPredicates as rustc_middle::ty::fold::TypeFoldable>::fold_with::<rustc_infer::infer::resolve::OpportunisticVarResolver>
  9,251,025  ???:<rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::register_predicate_obligation
  8,900,919  ???:<rustc_middle::ty::subst::GenericArg as rustc_middle::ty::fold::TypeFoldable>::try_fold_with::<rustc_infer::infer::resolve::OpportunisticVarResolver>
  7,595,609  ???:<rustc_middle::ty::sty::AliasTy>::to_ty
 -7,301,243  ???:<rustc_infer::infer::outlives::verify::VerifyBoundCx>::projection_opaque_bounds
  6,529,401  ???:<rustc_infer::infer::outlives::verify::VerifyBoundCx>::alias_bound
```

I don't think there's really anything actionable here, and we should land regardless.

@bors r+

**Pull request merged**
