### PR TITLE
Use an SVG image for clipboard instead of unicode character

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Linked to https://github.com/rust-lang/docs.rs/pull/1394.

cc @jsha 
r? @Nemo157

### CODE REVIEW

**Comment by notriddle** [comment]
`fill=currentColor` isn’t going to work correctly with the IMG tag.

We should really switch to using an [SVG sprite sheet](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) for rustdoc icons, so all three icons can be loaded from one file, and so that we can inherit theme colors.

**Comment by GuillaumeGomez** [comment]
They currently keep their color, whatever the theme.

**Comment by Nemo157** [comment]
> They currently keep their color, whatever the theme.

That's a problem

image

**Comment by Nemo157** [comment]
It currently goes back to the old text clipboard icon after clicking (pretend this is a gif, I don't have a gif recorder on this pc :grinning:):

image
image
image

**Comment by GuillaumeGomez** [comment]
Oh right! Good catch!

**Comment by camelid** [comment]
This made the clipboard icon *much* larger and more distracting:

**before**

image


**after**

image

I felt concerned about it being too conspicuous before, but now it's even more so. Is there a way to make it smaller or lighter?

The docs.rs one is only shown for the crate root, not for every single item in the crate.

**Comment by GuillaumeGomez** [comment]
Hum... Maybe @jsha has an opinion here? I personally don't mind changing to any of what was suggested so I'm definitely not the good person to pick one.

**Comment by GuillaumeGomez** [comment]
Giving it a try then!

**Pull request merged**
