### PR TITLE
Don't panic on stable since miri is not available there

### LINKED ISSUE #105816: Stable build of 1.66.0 fails due to 'missing miri'
On Solaris 11 x86_64, from scratch `stable` builds of 1.66.0 from git fails with:
```
...
   Compiling opener v0.5.0
   Compiling toml v0.5.9
    Finished dev [unoptimized] target(s) in 1m 02s
Build completed successfully in 0:01:10
Building rustbuild
    Finished dev [unoptimized] target(s) in 2.25s
thread 'main' panicked at 'missing miri', install.rs:205:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:03
make: *** [Makefile:54: install] Error 1
```

A `nightly` build of the same tag completes successfully, as do `stable` and `nightly` builds of 1.65.0.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #105816

### CODE REVIEW

**Comment by paulmenzel** [comment]
As this is still happening in 1.66.1, is it possible to have it backported to 1.67.0?

**Comment by oli-obk** [comment]
I don't believe this warrants a backport, but we can bring it up in the compiler team triage on Thursday. If you open an issue for it and ping me there I can nominate it for a compiler team decision

**Pull request merged**
