### PR TITLE
Update RLS and Rustfmt

### LINKED ISSUE #84537: `rls` no longer builds after rust-lang/rust#84310
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#84310, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @RalfJung, do you think you would have time to do the follow-up work?
If so, that would be great!

### LINKED ISSUE #84538: `rustfmt` no longer builds after rust-lang/rust#84310
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#84310, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @RalfJung, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by Xanewok**
Closes #84537. Closes #84538.

I know there's https://github.com/rust-lang/rust/pull/82208 in progress but I'm not sure which we want to land first.

Also, I'm getting Rustfmt test failures due to inner attributes not permitted:
<details>

```
error: an inner attribute is not permitted in this context
 --> tests/target/issue-3592.rs:4:13
  |
4 |             #![cfg(unix)]
  |             ^^^^^^^^^^^^^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

error: an inner attribute is not permitted in this context
 --> tests/target/issue-3592.rs:8:13
  |
8 |             #![cfg(not(unix))]
  |             ^^^^^^^^^^^^^^^^^^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

error: an inner attribute is not permitted in this context
   --> tests/source/match.rs:413:9
    |
413 |         #![allow(simple_match)]
    |         ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

error: an inner attribute is not permitted in this context
   --> tests/target/match.rs:444:9
    |
444 |         #![allow(simple_match)]
    |         ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

test test::system_tests ... FAILED
test test::idempotence_tests ... FAILED
```

</details>

but let's see what CI says, first.

cc @calebcartwright

### CODE REVIEW

**Comment by joshtriplett** [comment]
@Xanewok Would you consider applying and including https://github.com/rust-lang/rls/pull/1732 in this, please?

**Comment by Xanewok** [comment]
> @Xanewok Would you consider applying and including [rust-lang/rls#1732](https://github.com/rust-lang/rls/pull/1732) in this, please?

Done :)

**Comment by joshtriplett** [comment]
@Xanewok Thanks!

**Comment by Xanewok** [comment]
I'm confused, `x86_64-gnu-tools` decides to skip itself due to lack of submodules changes (??). Force-pushed it again and it's the same result.

Should we approve it and see if this makes it past bors or should we wait for https://github.com/rust-lang/rust/pull/82208 to land?

**Comment by jyn514** [comment]
I have no preference on whether to land this or https://github.com/rust-lang/rust/pull/82208 first; it might be faster to land this though since it's just a routine bump and 82208 still needs review for the bootstrap changes.

**Comment by Xanewok** [comment]
Let's try it then:

@bors r+ p=1

**Comment by jyn514** [comment]
Looks like a rustfmt test failure, cc @calebcartwright

**Comment by Mark-Simulacrum** [comment]
Likely due to https://github.com/rust-lang/rust/pull/83312, cc https://github.com/rust-lang/rust/issues/84879

**Comment by Xanewok** [comment]
It doesn't seem like we'll add back the support for inner attributes in that context in time before we need to fix the toolstate, correct? Should we ignore these tests for now?

**Comment by calebcartwright** [comment]
Yeah I'll remove those snippets from our set of test files; no point keeping around something the parser won't accept and we can always add them back if something changes.

I'll patch it in rustfmt here in a little bit

**Comment by calebcartwright** [comment]
Have updated rustfmt and opened https://github.com/rust-lang/rls/pull/1734 in RLS to pull in the updates

**Comment by Xanewok** [comment]
Update the Rustfmt rev both here and in the RLS (it's nice to migrate to a new version in unison), so let's try again:

@bors r+

**Pull request merged**
