### PR TITLE
[rustdoc] Box `ItemKind::Impl` to shrink the size of Item

### PR DESCRIPTION
**Pull request by jyn514**
Helps with #79103. Builds on https://github.com/rust-lang/rust/pull/79957 and should not be merged before. Eventually I want to calculate this info on demand (https://github.com/rust-lang/rust/issues/76382) but that turned out to be quite difficult so I'm leaving it for later and slapping on this short-term fix.

This brings the size of Item and ItemKind from

```
[src/librustdoc/lib.rs:102] std::mem::size_of::<Item>() = 680
[src/librustdoc/lib.rs:102] std::mem::size_of::<ItemKind>() = 408
```

to
```
[src/librustdoc/lib.rs:102] std::mem::size_of::<Item>() = 608
[src/librustdoc/lib.rs:102] std::mem::size_of::<ItemKind>() = 336
```

Waiting to start a perf run until https://github.com/rust-lang/rust/pull/79957 lands.

### CODE REVIEW

**Comment by jyn514** [comment]
@GuillaumeGomez I plan to box a couple other variants too - would you prefer I do that here or in a separate PR? The only reason I'd separate it is to get more accurate perf numbers, but if we get a perf run on this I think we could compare later runs to the first one?

**Comment by GuillaumeGomez** [comment]
I'd prefer in other PRs yes. Like that we can compare more accurately and it makes reviewing easier for me. :)

**Comment by jyn514** [comment]
Another alternative I didn't think of earlier is to box the whole `ItemKind`. That would reduce the size a lot more without having to box each variant piecemeal.

**Comment by jyn514** [comment]
@GuillaumeGomez I made all the changes I planned to make so that I can compare them to the alternative approach in https://github.com/rust-lang/rust/pull/80014. If we end up making this change I can split them into separate PRs, but I don't think it make sense to make any of these changes if 80014 gets merged, so I want to compare the final impact.

@bors try @rust-timer queue

**Comment by jyn514** [comment]
Max of -2.1% on instructions, max of -1.3% on max-rss. I think I would prefer to go with https://github.com/rust-lang/rust/pull/80014 because it improves max-rss more.

**Pull request closed without merging**
