### PR TITLE
type_alias_enum_variants: fix #61801; allow a path pattern to infer

### LINKED ISSUE #61801: #![feature(type_alias_enum_variants)]: Unit variant pattern through a type alias to generic enum requires type annotations
The following, which I expect to work, fails to infer the type of `OptAlias::None`:

```rust
#![feature(type_alias_enum_variants)]

enum Option<T> {
    None,
    Some(T),
}

type OptAlias<T> = Option<T>;

fn work_on_alias(x: OptAlias<u8>) {
    match x {
        OptAlias::None => (), //~ ERROR type annotations needed
        _ => (),
    }
}
```

In HIR, `OptAlias::None` should correspond to:
```rust
PatKind::Path(
    QPath::TypeRelative(_, P(
        PathSegment { res: Some(
            Res::Def(DefKind::Ctor(CtorOf::Variant, CtorKind::Const))
        ), .. }
    ))
)
```

However, if we change the snippet to:

```rust
#![feature(type_alias_enum_variants)]

enum Option<T> {
    None,
    Some(T),
}

type OptAlias<T> = Option<T>;

fn work_on_alias(x: OptAlias<u8>) {
    match x {
        OptAlias::None {} => (), // Note the changed pattern.
        _ => (),
    }
}
```
it all works out fine.

I also tested changing `None` to a tuple variant and that works also.

cc @petrochenkov @eddyb @alexreg 

cc https://github.com/rust-lang/rust/pull/61682

### PR DESCRIPTION
**Pull request by Centril**
Fix #61801.

Given a type-relative path pattern referring to an enum variant through a type alias, allow inferring the generic argument applied in the expectation set by the scrutinee of a `match` expression.

Similar issues may exist for `let` statements but I don't know how to test for that since `PhantomData<T>` is necessary...)

The gist of the problem here was that `resolve_ty_and_res_ufcs` was called twice which is apparently no good... It is possible that this PR is papering over some deeper problem, but that is beyond my knowledge of the compiler.

r? @petrochenkov 
cc @eddyb @alexreg 
cc https://github.com/rust-lang/rust/pull/61682
cc https://github.com/rust-lang/rust/issues/49683

### CODE REVIEW

**Comment by Centril** [comment]
@bors try

This might possibly be a perf improvement?

**Comment by petrochenkov** [comment]
>The gist of the problem here was that resolve_ty_and_res_ufcs was called twice which is apparently no good...

This looks like a fallout from implementation default binding modes.
It was called once the last time I rewrote that code.

@bors r+ rollup

**Comment by Centril** [comment]
@bors p=101

Trying this one out to see if the bors problems go away.

**Pull request merged**
