### PR TITLE
Fix some AArch64 typos

### PR DESCRIPTION
**Pull request by parched**
cc @dlrobertson

### CODE REVIEW

**Comment by dlrobertson** [comment]
:+1: Thanks! FWIW the typo was introduced in https://github.com/rust-lang/rust/pull/56599

**Comment by Centril** [comment]
Failed in rollup, https://github.com/rust-lang/rust/pull/58014#issuecomment-459173341

@bors r-

**Review by dlrobertson — CHANGES_REQUESTED** [review]
Ah the issues aren't visible in the diff and really are due to a bad implementation in my original PR. I'll do my best to describe it, but it will be a bit difficult since it is outside the diff. Please feel free to ping me on discord or zulip if you have questions.

The implementation of `Debug` (line 63) should be run for `aarch64` + `target_os = "ios"` devices.

Line 74 needs a `not(target_os = "ios")`

The `cfg`s for intrinsic implementation of `va_copy` needs corrected. The one returning a `VaList` should be used for `aarch64-ios`.

**Comment by michaelwoerister** [comment]
Let's try again.

@bors r+

**Comment by dlrobertson** [comment]
@parched If you do not have the time to make the final fixes needed to get this to work, I can submit a PR to your branch

**Comment by parched** [comment]
Thanks, I see what you mean by your comment, I just haven't had the chance to do them yet. I don't think I will for at least a week, so by all means submit them yourself.

**Comment by dlrobertson** [comment]
> I just haven't had the chance to do them yet. I don't think I will for at least a week

:+1: totally understand. I think that's fine. I just didn't want this to not get merged for outside issues.

**Comment by Dylan-DPC** [comment]
ping from triage @dlrobertson @parched any updates on this?

**Comment by dlrobertson** [comment]
I think we also need to fix the use of `va_copy` otherwise we're using the wrong `va_copy`.

```
diff --git a/src/libcore/ffi.rs b/src/libcore/ffi.rs
index 3fe65ab344..823d040d7b 100644
--- a/src/libcore/ffi.rs
+++ b/src/libcore/ffi.rs
@@ -198,10 +198,10 @@ impl<'a> VaList<'a> {
                   windows))]
         let mut ap = va_copy(self);
         #[cfg(all(any(target_arch = "aarch64", target_arch = "powerpc", target_arch = "x86_64"),
-                  not(windows)))]
+                  not(windows), not(all(target_arch = "aarch64", target_os = "ios"))))]
         let mut ap_inner = va_copy(self);
         #[cfg(all(any(target_arch = "aarch64", target_arch = "powerpc", target_arch = "x86_64"),
-                  not(windows)))]
+                  not(windows), not(all(target_arch = "aarch64", target_os = "ios"))))]
         let mut ap = VaList(&mut ap_inner);
         let ret = f(VaList(ap.0));
         va_end(&mut ap);
@@ -217,10 +217,11 @@ extern "rust-intrinsic" {
     /// Copy the current location of arglist `src` to the arglist `dst`.
     #[cfg(any(all(not(target_arch = "aarch64"), not(target_arch = "powerpc"),
                   not(target_arch = "x86_64")),
+              all(target_arch = "aarch64", target_os = "ios"),
               windows))]
     fn va_copy<'a>(src: &VaList<'a>) -> VaList<'a>;
     #[cfg(all(any(target_arch = "aarch64", target_arch = "powerpc", target_arch = "x86_64"),
-              not(windows)))]
+              not(windows), not(all(target_arch = "aarch64", target_os = "ios"))))]
     fn va_copy(src: &VaList) -> VaListImpl;

     /// Loads an argument of type `T` from the `va_list` `ap` and increment the
```

**Comment by parched** [comment]
Ah yes, done.

**Comment by dlrobertson** [comment]
:+1: LGTM

**Comment by dlrobertson** [comment]
@michaelwoerister ping

**Comment by michaelwoerister** [comment]
Hm, it seems this is changing a bit more than just typos now. I think @joshtriplett knows about FFI.

r? @joshtriplett (feel free to re-assign to somebody else of course)

**Comment by joshtriplett** [comment]
Currently reviewing.  Initial note: Please don't back-merge master into a branch; please rebase (and re-test) instead.

**Comment by joshtriplett** [comment]
Please merge the "take 2" commit into its parent commit, and drop the merge commit. Otherwise, this looks reasonable to me, provided that folks familiar with the iOS/non-iOS calling conventions for aarch64 are comfortable with it.

**Comment by dlrobertson** [comment]
Per the [Apple Developer Docs]

> As a result of this change, the type `va_list` is an alias for `char *`

So this looks correct

[Apple Developer Docs]: https://developer.apple.com/library/archive/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html

**Comment by TimNN** [comment]
Ping from triage @parched: It looks like some changes have been requested to your PR.

**Comment by parched** [comment]
@joshtriplett Ok I've rebased to get rid of the merge, and squashed that take 2 commit. I haven't tested it on AArch64 iOS yet though.

**Comment by joshtriplett** [comment]
Looks good, thanks! r=me after CI passes.

**Comment by dlrobertson** [comment]
@joshtriplett I think you'd need to `delegate` in order to do that right?

**Pull request merged**
