### PR TITLE
[beta] temporarily disable rust-lang/rust#46833 due to rust-lang/rust#48251

### PR DESCRIPTION
**Pull request by nikomatsakis**
see also https://github.com/rust-lang/rust/pull/48378

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by nikomatsakis** [comment]
[See FCP on the stable PR](https://github.com/rust-lang/rust/pull/48378#issuecomment-367473893)

**Comment by Mark-Simulacrum** [comment]
@bors retry

We need to backport the appveyor fix to beta...

**Comment by kennytm** [comment]
@bors p=8

Beta backport

**Comment by Manishearth** [comment]
@bors p=10

(we care about this one more)

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout in `dist-powerpc-linux`.

**Comment by alexcrichton** [comment]
All dist jobs completed for https://github.com/rust-lang/rust/commit/62ad16c7d20ff18b76a7aca7dfde21dbbdf83b72

* [Travis](https://travis-ci.org/rust-lang/rust/builds/346334899)
* [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6476)

gonna merge that manually

**Pull request merged**
