### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #127279 (use old ctx if has same expand environment during decode span)
 - #127945 (Implement `debug_more_non_exhaustive`)
 - #128941 ( Improve diagnostic-related lints: `untranslatable_diagnostic` & `diagnostic_outside_of_impl`)
 - #129070 (Point at explicit `'static` obligations on a trait)
 - #129187 (bootstrap: fix clean's remove_dir_all implementation)
 - #129231 (improve submodule updates)
 - #129264 (Update `library/Cargo.toml` in weekly job)
 - #129284 (rustdoc: animate the `:target` highlight)
 - #129302 (compiletest: use `std::fs::remove_dir_all` now that it is available)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=127279,127945,128941,129070,129187,129231,129264,129284,129302)

### CODE REVIEW

**Comment by jieyouxu** [comment]
> The job **`x86_64-msvc-ext`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/10496414606/job/29077025650) [(plain)](https://github.com/rust-lang-ci/rust/commit/562df53ef01f2ab1f3a89231e039147986bde389/checks/29077025650/logs)

Pinging back #127883.

**Comment by pnkfelix** [comment]
visiting for weekly rustc-perf triage.

* primary regressions are solely to various incr-patched scenarios
* possibly PR #127279 is root cause then?
* enqueued rust-timer build request for ff4d0214b98f67a324dfa1baacd12e9acff8cde9 (associated with PR #127279)
* note that PR #127279 is addressing an issue in incr-comp; it might be expected that it would cause some incr-comp benchmarks to be impacted.

**Comment by pnkfelix** [comment]
The above seems to confirm that PR #127279 is the cause of the reported regression.

However, I do not think the performance hit is significant enough to warrant reverting that PR, compared to the impact that would have on the incremental compilation scenarios described in issue #112680. (We may nonetheless want to explore *replacing* that PR with a fix for the [potential deeper problem](https://github.com/rust-lang/rust/pull/127279#issuecomment-2210376603) alluded to by @cjgillot and @petrochenkov on PR #127279.)

**Pull request merged**
