### PR TITLE
Bootstrap: Don't get output if `lldb --version` errors

### LINKED ISSUE #126892: Bootstrap panics if lldb fails to start
Running `./x test tests/ui --stage 1` on Windows I get:

```
thread 'main' panicked at src\core\build_steps\test.rs:1820:40:
"lldb" "-P" failed Output { status: ExitStatus(ExitStatus(3221225781)), stdout: "", stderr: "" }
```

This seems especially unfortunate because (as far as I know) ui tests don't require lldb. It works fine if there's no lldb in `PATH` at least.

This is ultimately an LLVM issue caused by not installing/shipping its own dependencies (in this case Python310). However, bootstrap shouldn't crash here. It should be treated similarly to lldb not existing unless it is actually necessary,

### PR DESCRIPTION
**Pull request by ChrisDenton**
fixes #126892

`Command` can error in two ways: the OS can fail to run the binary at all or else the binary can return an error exit code. Unfortunately the distinction between the two is not clear cut. The OS may succeed in starting the binary but it may still error before `main` (e.g. if a necessary library fails to load) and this will be reported via the exit code.

Fortunately this case is simpler. We can assume that `lldb --version` will only ever error if there's a startup issue of some kind. so both kinds of errors are caused by the OS. Thus it's safe for us to treat them equally for the sake of this specific check.

### CODE REVIEW

**Comment by Kobzol** [comment]
I don't understand how this fixes the crash. It seems just to change the returned error? The original issue showed a crash on line `1820`, inside the `run` function, but that isn't used in this `lldb` invocation. It is probably crashing elsewhere (?) :) Probably line 1841.

**Comment by ChrisDenton** [comment]
Sorry, I didn't explain that very well. The code is a bit spaghetti but the `run` function is only invoked after the `lldb --version` is, It's guarded by the `if let Some(ref vers) = lldb_version {` block.

And `lldb --version` already fails but we don't actually check the exit status before reading the output of `lldb --version` so we're getting nonsense. Well probably `Ok("")` because it doesn't print anything.

**Comment by ChrisDenton** [comment]
I've pushed a new commit that hopefully makes the code a bit clearer.

**Comment by Kobzol** [comment]
Aah, I understand now, thanks! Yeah, this command invocation code is very messy. I will nuke it soon (probably in the next couple of days) anyway with my bootstrap command refactoring PRs. But it doesn't hurt to fix the issue for now, it will help me understand the intent of the original code better.

Thanks!

@bors rollup r+

**Comment by ChrisDenton** [comment]
> I will nuke it soon (probably in the next couple of days) anyway with my bootstrap command refactoring PRs.

That'll be great!

**Pull request merged**
