### PR TITLE
Add diagnostic items for macros

### PR DESCRIPTION
**Pull request by Alexendoo**
For use in Clippy, it adds diagnostic items to all the stable public macros

Clippy has lints that look for almost all of these (currently by name or path), but there are a few that aren't currently part of any lint, I could remove those if it's preferred to add them as needed rather than ahead of time

### CODE REVIEW

**Comment by inquisitivecrystal** [comment]
If I may ask, what's the reason for the `[cfg_attr(not(test), ...]` that's present on a lot of these?

**Comment by Alexendoo** [comment]
I'm not entirely sure, I saw (only some) others that had them on. I'll try without and see if everything passes

**Comment by Alexendoo** [comment]
Well, that explains it. Not sure why that happens but I'll put the cfgs back

**Pull request merged**
