### PR TITLE
Clean and enable `rustdoc::unescaped_backticks` for `core/alloc/std/test/proc_macro`

### PR DESCRIPTION
**Pull request by ojeda**
I am not sure if the lint is supposed to be "ready enough" (since it is `allow` by default), but it does catch a couple issues in `core` (`alloc`, `std`, `test` and `proc_macro` are already clean), so I propose making it `warn` in all the crates rendered in the website.

Cc: @GuillaumeGomez

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
It is. Thanks for the PR! r=me once CI pass

@bors delegate=ojeda

**Comment by ojeda** [comment]
It was a private item -- fixed. I also widened it to the 5 crates rendered in the website.

**Comment by ojeda** [comment]
> It is. Thanks for the PR! r=me once CI pass

That is great. Then I will propose to enable it for the kernel too. Thanks!

@bors r=@GuillaumeGomez

**Comment by ojeda** [comment]
@GuillaumeGomez Just in case, please note that I added it also to `std`, `test` and `proc_macro`. Perhaps I shouldn't have done the bors thing given I changed that...

**Comment by GuillaumeGomez** [comment]
It's fine don't worry. I had the email notifications. If I saw something problematic, I would have commented so no worries here. ;)

**Comment by ojeda** [comment]
Thanks! :)

**Comment by GuillaumeGomez** [comment]
Seems like you forgot one as you can see [here](https://github.com/rust-lang/rust/pull/128311#issuecomment-2254595184).

@bors r-

**Comment by ojeda** [comment]
It was a conflict with this other PR in that rollup: https://github.com/rust-lang/rust/pull/127765/files#diff-e8ccaf64ce21f955ccebef33b52158631493a6f0966815a2ebc142d7cd2b5e06R3456

**Comment by ojeda** [comment]
Rebased now that the PR with the conflict was merged.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
