### PR TITLE
Deny rustc::internal lints for rustdoc and clippy

### PR DESCRIPTION
**Pull request by jyn514**
- Fix rustc::internal lints for rustdoc
- Deny internal lints only for rustdoc and clippy (previously the lints were ignored for clippy because -Zunstable-options didn't get passed)

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by jyn514** [comment]
Hmm, this errors out in `clippy/tests/compile-test.rs` because it uses `HashMap` instead of `FxHashMap`. But that's not right, because compiletest is a bootstrap tool and doesn't depend on rustc_data_structures. I think I need to find a way to only do this for regular code and not tests? It sounds difficult to do that without special casing clippy though, I can imagine wanting these lints for rustc unit tests.

**Comment by flip1995** [comment]
I'm good with adding `#![allow(rustc::internal)]` to clippys `compile-test.rs` file.

**Comment by jyn514** [comment]
The failure seems spurious, not sure why it wouldn't have libstd for other targets installed.

**Comment by jyn514** [comment]
Hmm, it seems this affects rustfmt too.

<details>

```
warning: Prefer FxHashMap over HashMap, it has better performance
  --> src/tools/rustfmt/src/lib.rs:12:23
   |
12 | use std::collections::HashMap;
   |                       ^^^^^^^ help: use: `FxHashMap`
   |
   = note: `-W rustc::default-hash-types` implied by `-W rustc::internal`
   = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashSet over HashSet, it has better performance
 --> src/tools/rustfmt/src/config/options.rs:1:34
  |
1 | use std::collections::{hash_set, HashSet};
  |                                  ^^^^^^^ help: use: `FxHashSet`
  |
  = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

warning: Prefer FxHashSet over HashSet, it has better performance
   --> src/tools/rustfmt/src/config/options.rs:282:15
    |
282 |     path_set: HashSet<PathBuf>,
    |               ^^^^^^^ help: use: `FxHashSet`
    |
    = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

warning: Prefer FxHashSet over HashSet, it has better performance
   --> src/tools/rustfmt/src/config/options.rs:322:26
    |
322 |             type Value = HashSet<PathBuf>;
    |                          ^^^^^^^ help: use: `FxHashSet`
    |
    = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

warning: Prefer FxHashSet over HashSet, it has better performance
   --> src/tools/rustfmt/src/config/options.rs:332:36
    |
332 |                 let mut path_set = HashSet::new();
    |                                    ^^^^^^^ help: use: `FxHashSet`
    |
    = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
 --> src/tools/rustfmt/src/config/file_lines.rs:4:23
  |
4 | use std::collections::HashMap;
  |                       ^^^^^^^ help: use: `FxHashMap`
  |
  = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/config/file_lines.rs:157:29
    |
157 | pub struct FileLines(Option<HashMap<FileName, Vec<Range>>>);
    |                             ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/config/file_lines.rs:176:34
    |
176 | fn normalize_ranges(ranges: &mut HashMap<FileName, Vec<Range>>) {
    |                                  ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/config/file_lines.rs:208:36
    |
208 |     pub fn from_ranges(mut ranges: HashMap<FileName, Vec<Range>>) -> FileLines {
    |                                    ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/config/file_lines.rs:215:35
    |
215 |         Files(self.0.as_ref().map(HashMap::keys))
    |                                   ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/config/file_lines.rs:305:21
    |
305 |         let mut m = HashMap::new();
    |                     ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
 --> src/tools/rustfmt/src/formatting.rs:3:23
  |
3 | use std::collections::HashMap;
  |                       ^^^^^^^ help: use: `FxHashMap`
  |
  = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/formatting.rs:313:34
    |
313 | pub(crate) type FormatErrorMap = HashMap<FileName, Vec<FormattingError>>;
    |                                  ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
  --> src/tools/rustfmt/src/macros.rs:12:23
   |
12 | use std::collections::HashMap;
   |                       ^^^^^^^ help: use: `FxHashMap`
   |
   = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/macros.rs:576:15
    |
576 |     map: &mut HashMap<String, String>,
    |               ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/macros.rs:595:50
    |
595 | fn replace_names(input: &str) -> Option<(String, HashMap<String, String>)> {
    |                                                  ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/macros.rs:598:22
    |
598 |     let mut substs = HashMap::new();
    |                      ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/lib.rs:188:45
    |
188 |             internal: Rc::new(RefCell::new((HashMap::new(), ReportedErrors::default()))),
    |                                             ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: 18 warnings emitted

error: Prefer FxHashSet over HashSet, it has better performance
  --> src/tools/rustfmt/src/format-diff/main.rs:15:23
   |
15 | use std::collections::HashSet;
   |                       ^^^^^^^ help: use: `FxHashSet`
   |
note: the lint level is defined here
  --> src/tools/rustfmt/src/format-diff/main.rs:5:9
   |
5  | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(rustc::default_hash_types)]` implied by `#[deny(warnings)]`
   = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

error: Prefer FxHashSet over HashSet, it has better performance
  --> src/tools/rustfmt/src/format-diff/main.rs:88:24
   |
88 | fn run_rustfmt(files: &HashSet<String>, ranges: &[Range]) -> Result<(), FormatDiffError> {
   |                        ^^^^^^^ help: use: `FxHashSet`
   |
   = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

error: Prefer FxHashSet over HashSet, it has better performance
   --> src/tools/rustfmt/src/format-diff/main.rs:125:14
    |
125 | ) -> Result<(HashSet<String>, Vec<Range>), FormatDiffError>
    |              ^^^^^^^ help: use: `FxHashSet`
    |
    = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

error: Prefer FxHashSet over HashSet, it has better performance
   --> src/tools/rustfmt/src/format-diff/main.rs:138:21
    |
138 |     let mut files = HashSet::new();
    |                     ^^^^^^^ help: use: `FxHashSet`
    |
    = note: a `use rustc_data_structures::fx::FxHashSet` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
 --> src/tools/rustfmt/src/bin/main.rs:8:23
  |
8 | use std::collections::HashMap;
  |                       ^^^^^^^ help: use: `FxHashMap`
  |
  = note: `-W rustc::default-hash-types` implied by `-W rustc::internal`
  = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/bin/main.rs:505:20
    |
505 |     inline_config: HashMap<String, String>,
    |                    ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

warning: Prefer FxHashMap over HashMap, it has better performance
   --> src/tools/rustfmt/src/bin/main.rs:586:31
    |
586 |             .collect::<Result<HashMap<_, _>, _>>()?;
    |                               ^^^^^^^ help: use: `FxHashMap`
    |
    = note: a `use rustc_data_structures::fx::FxHashMap` may be necessary

error: aborting due to 4 previous errors

error: could not compile `rustfmt-nightly`
```

</details>

@calebcartwright how do you feel about fixing those lints for rustfmt? Or would you prefer I ignore them?

**Comment by calebcartwright** [comment]
> @calebcartwright how do you feel about fixing those lints for rustfmt? Or would you prefer I ignore them?

Admittedly haven't read the full thread/linked issues, but I feel like rustfmt should be ignored/excluded from this.

Although we periodically run clippy and selectively apply fixes, it's not really part of our inner dev loop and not a fixed gate, and I don't foresee that changing any time soon. If we were to include the internal lints against rustfmt here then we'll inevitably end up in a scenario where we don't find out about a lint failure til an attempted submod bump which would then require a restart of our upgrade dance.

Also, since rustfmt utilizes the rustc internals via the auto publish crates, I really don't want to increase our dependence on said internals unless absolutely necessary or unless the benefits significantly outweigh the drawbacks. Retroactively dealing with breaking rustc internal changes in rustfmt is already painful enough, and that pain gets exacerbated the more we couple ourselves to those internals.

**Comment by flip1995** [comment]
I think it would be best to make internal lints opt-in rather than opt-out, if that's somehow possible.

**Comment by jyn514** [comment]
> I think it would be best to make internal lints opt-in rather than opt-out, if that's somehow possible.

I changed this to only deny the lints for tools that are in-tree, which includes things like error_index_generator, but not rustfmt. @flip1995 does that sound good to you? I can special case clippy and rustdoc instead if you like, but I think this is a good metric.

**Comment by jyn514** [comment]
> 2021-01-03T05:13:45.3994486Z Checking bootstrap artifacts (x86_64-unknown-linux-gnu -> i686-pc-windows-gnu)

Oh, I think I figured out why this is failing: In https://github.com/rust-lang/rust/pull/80573/commits/216de7ac1532d1163531fdcc97224b28d44636ba, I don't require building libstd before building bootstrap, which breaks when cross-compiling. I feel like there should be some way to improve that without having to check the compiler, but regardless it doesn't belong in this PR.

**Comment by flip1995** [comment]
> I changed this to only deny the lints for tools that are in-tree, which includes things like error_index_generator, but not rustfmt. @flip1995 does that sound good to you?

Yes, that sounds reasonable.

**Comment by Mark-Simulacrum** [comment]
I do not think we should do this for all tools that depend on rustc. The internal lints are intentionally internal; applying them to tools (even ones in-tree) should be done only if it makes sense for that tool. For rustdoc, that's probably true, but for other tools I'm less certain. I would suggest we start with just rustdoc - I'm not aware of any other in-tree tools for which this would make sense. I think that would be a matter of moving this -W flag to the Rustdoc tool step (and also check.rs step).

**Comment by flip1995** [comment]
Well, Clippy was the first tool that implemented internal lints and now uses rustc internal lints **and** additional Clippy internal lints.

But maybe making all internal lints allow-by-default and then adding `-Wrustc-internal` in bootstrap on a tool by tool basis sounds good to me.

**Comment by Mark-Simulacrum** [comment]
Yes, that seems like the path I'd suggest for now.

**Comment by jyn514** [comment]
Ok, now this only enables rustc::internal lints for clippy and rustdoc specifically.

**Comment by Mark-Simulacrum** [comment]
It looks like CI is currently failing. Since unlike rustc, rustdoc and clippy are both currently just one crate (and we *don't* need to lint their dependencies) maybe just easier to directly add the two attributes to their lib.rs?

**Comment by jyn514** [comment]
> It looks like CI is currently failing. Since unlike rustc, rustdoc and clippy are both currently just one crate (and we _don't_ need to lint their dependencies) maybe just easier to directly add the two attributes to their lib.rs?

Hmm, that will work now, but will break after https://github.com/rust-lang/rust/pull/80524, which was the original motivation. I'll see if I can improve https://github.com/rust-lang/rust/pull/80524 not to need bootstrap changes, since I agree `#![deny(rustc::internal)]` is probably a better approach in general.

**Comment by Mark-Simulacrum** [comment]
Hm I admit I haven't followed that PR closely, if this helps it somehow I can take a look.

Note you want to use warn, not deny - we forbid warnings in bootstrap and that should include these lints, right?

**Comment by jyn514** [comment]
Alright, this is finally working. It
- denies internal lints only for rustdoc and clippy (previously the lints were ignored for clippy because `-Zunstable-options` didn't get passed)
- fixes the internal lints for rustdoc

**Review by flip1995 — APPROVED** [review]
LGTM

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by flip1995** [comment]
@GuillaumeGomez bors doesn't react to commands in review comments, only in normal comments.

**Comment by GuillaumeGomez** [comment]
It was a normal comment. I didn't post a review comment. But let's try again.

@bors: r+

**Pull request merged**
