### PR TITLE
Add implicit result return for rustdoc main function

### LINKED ISSUE #56260: Rustdoc: Allow implicit `fn main() -> Result<_, _>`
Rustdoc now allows us to use `?` in our tests. Unfortunately, this requires writing the `fn main() -> ..` manually, which really shouldn't be needed IMHO.

So we now have to write:

```rust
/// ```rust
///# fn main() -> Result<(), ()> {
/// let foo = Ok(1usize);
/// assert!(foo? > 0);
///# }
/// ```
```

where it should suffice to write:

```rust
/// ```rust
/// let foo = Ok(1usize);
/// assert!(foo? > 0);
/// ```
```

Doing so will make the tests shorter and hopefully lead to more `?` and less `unwrap` in tests.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #56260.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'll need to check if a function ends with an `Ok` or a `Result`...

**Comment by ollie27** [comment]
I'm not sure this can be done. It'll not only have to detect if the code returns `Result` but also what error type it uses because not many things use `()`.

**Comment by GuillaumeGomez** [comment]
I think it's worth a try but I was expecting a bit too much. :)

**Comment by QuietMisdreavus** [comment]
This conflicts with https://github.com/rust-lang/rust/pull/56470.

**Comment by GuillaumeGomez** [comment]
Indeed, I'll close it in favor of #56470.

**Pull request closed without merging**
