### PR TITLE
macros: Improve `tt` matchers

### LINKED ISSUE #5846: tt-macro doesn't work
I haven't finished investigating this, so I'm making an issue just so I don't forget it:

```rust
macro_rules! foo (
    ($x:tt) => {type t = ($x) int;})

foo!(~)
```

### LINKED ISSUE #22819: Traverse interpolated TTs so we can parse them as other things
See discussion on #9364.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #5846, fixes #22819.
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
Looks like this breaks some non-trivial macro-expanded `macro_rules!`, which I thought were already broken but actually happen to work in some cases due to the strange behavior of today's `tt` fragments.

This should be able to land without breakage once I fix non-trivial macro-expanded `macro_rules!`.

**Comment by jseyfried** [comment]
cc @eddyb

**Comment by eddyb** [comment]
LGTM, pending on #34925 landing.

**Comment by jseyfried** [comment]
This is ready to land now pending review (cc @nrc).
The travis failure is spurious.

**Comment by alexcrichton** [comment]
@bors: retry force clean

* restarted buildbot

**Comment by durka** [comment]
Has this innocuously named PR killed the reparse hack? https://is.gd/MBJDFW

**Comment by eddyb** [comment]
@durka That's what was fixed here, yeah.

**Comment by durka** [comment]
That makes me unjustifiably happy. Please tag this with `relnotes`, trumpet from rooftops, etc.

**Pull request merged**
