### PR TITLE
Restore working debuginfo tests by trimming comments from non-header directive lines

### PR DESCRIPTION
**Pull request by nerd2**
I noticed when adding a debuginfo test that nothing I did caused the test to fail. Tracing back this seems to have been caused by 3e6c83de1dc0a72df3663617d394a9e79641618d which broke parsing of the command/check lines, leaving all tests passing without any checking. This commit provides a basic (although still not very robust) restoration of tests and a should-fail test which checks the parser is running

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

Oh dear, thanks so much for catching this! Let's hope we haven't seen any regressions in the meantime...

cc @kennytm

**Comment by nerd2** [comment]
Looks like a few failures on both GDB and LLDB. Do you want them fixed in this commit or marked ignore?

**Comment by alexcrichton** [comment]
If you know how to fix them that'd be great, otherwise we can open an issue and ignore them.

**Comment by nerd2** [comment]
@alexcrichton updated this PR to disable them and created issue 47163 to track. Will update issue with ignored tests if this passes.

**Comment by alexcrichton** [comment]
@bors: r+

Ok, thanks!

**Comment by alexcrichton** [comment]
A few missing tests?

```
[01:01:23] failures:
[01:01:23]     [debuginfo-gdb] debuginfo/by-value-non-immediate-argument.rs
[01:01:23]     [debuginfo-gdb] debuginfo/function-arg-initialization.rs
[01:01:23]     [debuginfo-gdb] debuginfo/method-on-enum.rs
[01:01:23]     [debuginfo-gdb] debuginfo/struct-in-enum.rs
```

**Comment by nerd2** [comment]
A lot seems to be broken

**Comment by kennytm** [comment]
Why is this file added?

https://github.com/nerd2/rust/blob/57b4fb16a2475a1aee676ad4bc74bb10512ea367/test

**Pull request merged**
