### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by flip1995** [comment]
@bors r+

Starting to r+ sync PRs myself. Did it ever make sense waiting for someone else to do it? :thinking:

**Comment by Manishearth** [comment]
(sorry, should have notified people, I'm in the wilderness with very little internet)

I think it's fine to wait for review just as a matter of consistency but I'm open to changing it. We all see these PRs anyway due to the team cc.

**Comment by flip1995** [comment]
r? @matthiaskrgr 

This includes https://github.com/rust-lang/rust-clippy/pull/12818, which should fix CI.

**Comment by matthiaskrgr** [comment]
rustfmt test failed??
@bors retry

**Pull request merged**
