### PR TITLE
Attempt to fix Azure line endings

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This is just a verification step for now, but I want to run it in a try builder to gauge whether it works or not. Presumably it'll fail, and we can then attempt to track down why.

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I seem to be unable to come up with a bash script that'll correctly detect the presence of the CRLF line endings. It does look like we're not successful in setting the autocrlf config though -- e.g. https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/3018/logs/53 clearly shows that `git config --list` has two `core.autocrlf=true` entries, and no `core.autocrlf=false` entries.

I've yet to discover exactly where these are coming from though. The "Show environment variables" step for that same build has "core.autocrlf=false" in the `git config --list` (https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/3018/logs/25), so something in between those two is presumably replacing that.

I'll investigate further tomorrow.

**Comment by mati865** [comment]
Interesting, something must be overriding `core.autocrlf=true` to `core.autocrlf=false`.
I think printing git config (or at least value of `core.autocrlf`) could help.

**Comment by Mark-Simulacrum** [comment]
Show environment variables: `file:C:/Program Files/Git/mingw64/etc/gitconfig	core.autocrlf=false`
Ensure build on C:/: `file:C:/agents/2.154.1/externals/git/mingw64/etc/gitconfig	core.autocrlf=true`

**Pull request closed without merging**
