### PR TITLE
Sync portable-simd to 2023 July 07

### PR DESCRIPTION
**Pull request by workingjubilee**
r? @ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
no really? tell me more.

**Comment by workingjubilee** [comment]
Needed to unbreak a build.

@bors r+ p=1 rollup=never

**Comment by workingjubilee** [comment]
It's a party for the whole family!

**Review by oli-obk — APPROVED** [review]

**Comment by workingjubilee** [comment]
errr I choose to assert the numbers are Good, Actually? you could hypothetically persuade me otherwise.

**Comment by Kobzol** [comment]
I oficially declare these numbers to be Good™.

@rustbot label: +perf-regression-triaged

**Pull request merged**
