### PR TITLE
trpl: Use infinite iterator in chain example with take

### PR DESCRIPTION
**Pull request by puzza007**

### CODE REVIEW

**Comment by aochagavia** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
So, while it's true that you usually use unbounded iterators with `take()`, I'm not sure we actually explained them before this point. Can you look into that, please?

**Comment by puzza007** [comment]
Yeah they're explained in the previous section. https://github.com/rust-lang/rust/pull/25941/files#diff-f81dbe18693d6f4de2cd78b29a5ea670R284

**Comment by steveklabnik** [comment]
@puzza007 excellent, thank you!

**Pull request merged**
