### PR TITLE
Implement `Sync` for `process::Command on unix and vxworks

### LINKED ISSUE #72387: Implement `Sync` for `process::Command`
`std::process::Command` is currently `Send`, but not `Sync`. While `Sync` probably isn't super useful for `Command` itself, it does mean that any type that wraps a `process::Command` _also_ isn't `Sync` even if it might be useful on that type.

`Command` currently has a manual `impl Send` following https://github.com/rust-lang/rust/pull/47760 (issue https://github.com/rust-lang/rust/issues/47751), though from the discussion on [users.r-l.o](https://users.rust-lang.org/t/would-it-be-possible-for-std-process-command-to-be-send/15254/4), it sounds like a manual `impl Sync` would also be sound. @cuviper not sure if that still holds?

If it does, this seems like a worthwhile `impl` to add, simply for the auto-trait implications.

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Closes #72387.
r? @cuviper

### CODE REVIEW

**Comment by cuviper** [comment]
I think this is technically fine, but it should have a libs team member review for the public API change.

r? @dtolnay

**Review by dtolnay — COMMENTED** [review]
To clarify, it's already Sync on all other supported platforms?

**Comment by cuviper** [comment]
I think so -- every other `Command` is "boring", just `OsString`s and such. But the test change in `src/libstd/process.rs` will confirm that in CI.

**Comment by dtolnay** [comment]
@bors r+

FYI @rust-lang/libs - this adds Sync for std::process::Command on unix, which was missing for an insignificant reason. Sync was already implemented on windows and other platforms.

**Pull request merged**
