### PR TITLE
Fix `resolution_failure` ICE

### LINKED ISSUE #103997: Typo in docs causes ICE
Using `cargo doc` in a crate with the following code causes an ICE. 

### Code

```Rust
pub fn foo() { }

/// [`foo`](Self::foo)
pub use foo as bar;
```
Note that just ``/// [`foo`](Self)`` causes a different panic message.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-pc-windows-msvc
release: 1.65.0
LLVM version: 15.0.0
```
also happens in nightly
```
rustc 1.67.0-nightly (215e3cd21 2022-11-03)
binary: rustc
commit-hash: 215e3cd218b83b8a3152d84d92f17109253c25e1
commit-date: 2022-11-03
host: x86_64-pc-windows-msvc
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Error output

```
error: internal compiler error: compiler\rustc_middle\src\ty\mod.rs:2186:13: item_name: no name for DefPath { data: [DisambiguatedDefPathData { data: Use, disambiguator: 1 }], krate: crate0 }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120\compiler\rustc_errors\src\lib.rs:1462:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ffeca8c8fb2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1086ecfa86360858
   1:     0x7ffeca9040db - core::fmt::write::hbadbc3de7beb6abb
   2:     0x7ffeca8bb8aa - <std::io::IoSlice as core::fmt::Debug>::fmt::hb7e33fb242ec9ac1 
   3:     0x7ffeca8cc5b4 - std::panicking::default_hook::hb8b3ce065b661264
   4:     0x7ffeca8cc1ea - std::panicking::default_hook::hb8b3ce065b661264
   5:     0x7ffe8cc225ee - rustc_driver[c6471a3a75cc3305]::describe_lints
   6:     0x7ffeca8ccfb2 - std::panicking::rust_panic_with_hook::h33e40e3f5d3be1f3        
   7:     0x7ffe8ee63583 - <rustc_middle[12c473a188441910]::ty::DestructuredConst as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
   8:     0x7ffe8ee62169 - <rustc_middle[12c473a188441910]::ty::DestructuredConst as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
   9:     0x7ffe8ee8a8b9 - <rustc_middle[12c473a188441910]::ty::subst::UserSubsts as rustc_middle[12c473a188441910]::ty::context::Lift>::lift_to_tcx
  10:     0x7ffe8ee60a89 - <rustc_middle[12c473a188441910]::ty::DestructuredConst as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  11:     0x7ffe8ee5e051 - <rustc_middle[12c473a188441910]::ty::DestructuredConst as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  12:     0x7ffe8ee5d8d2 - <rustc_middle[12c473a188441910]::ty::DestructuredConst as core[8087a2e8d825f5e1]::fmt::Debug>::fmt
  13:     0x7ffe8eec5687 - <rustc_middle[12c473a188441910]::ty::sty::Binder<rustc_middle[12c473a188441910]::ty::TraitPredicate>>::print_modifiers_and_trait_path
  14:     0x7ffe8eec6d58 - rustc_middle[12c473a188441910]::util::bug::bug_fmt
  15:     0x7ffe8eec6cd5 - rustc_middle[12c473a188441910]::util::bug::bug_fmt
  16:     0x7ffe8cb0a5c9 - <rustc_middle[12c473a188441910]::ty::context::TyCtxt>::item_name
  17:     0x7ff66e0b1559 - <unknown>
  18:     0x7ffe8cabe8a8 - rustc_middle[12c473a188441910]::lint::struct_lint_level::struct_lint_level_impl
  19:     0x7ff66e24e6bd - <unknown>
  20:     0x7ff66df72979 - <unknown>
  21:     0x7ff66df6b3df - <unknown>
  22:     0x7ff66df7693c - <unknown>
  23:     0x7ff66df6d6cd - <unknown>
  24:     0x7ff66df64107 - <unknown>
  25:     0x7ff66e11308f - <unknown>
  26:     0x7ff66df376dd - <unknown>
  27:     0x7ff66e113674 - <unknown>
  28:     0x7ff66e0cd21b - <unknown>
  29:     0x7ff66deb2638 - <unknown>
  30:     0x7ff66e20ed32 - <unknown>
  31:     0x7ff66defdf7f - <unknown>
  32:     0x7ff66e127887 - <unknown>
  33:     0x7ff66df1ca73 - <unknown>
  34:     0x7ffeca8dd7cc - std::sys::windows::thread::Thread::new::h742bb0c6405f02e2      
  35:     0x7fff11077034 - BaseThreadInitThunk
  36:     0x7fff127c26a1 - RtlUserThreadStart

```

</p>
</details>

### PR DESCRIPTION
**Pull request by TaKO8Ki**
Fixes #103997

### CODE REVIEW

**Comment by petrochenkov** [comment]
I think this PRs only hides the underlying issue, the erroneous `Self` shouldn't resolve to `Res::Def(DefKind::Use, _)` in the first place.

**Comment by TaKO8Ki** [comment]
Or should rustdoc warn like the following? @rust-lang/rustdoc If so, I think we need to improve `LinkCollector::resolve_self_ty`.

```
warning: unresolved link to `Self::foo`
 --> src/main.rs:3:13
  |
3 | /// [`foo`](Self::foo)
  |             ^^^^^^^^^ no item named `Self` in scope
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: `debug_playground` (bin "debug_playground" doc) generated 1 warning
```

**Comment by GuillaumeGomez** [comment]
Would be better indeed.

**Pull request merged**
