### PR TITLE
Stabilize euclidean modulo methods

### LINKED ISSUE #49048: Tracking issue for RFC 2169: Euclidean Modulo
Tracking issue for rust-lang/rfcs#2169, euclidean modulo methods on numbers

**Steps**:

- [x] Implementation (https://github.com/rust-lang/rust/pull/49389)
- [ ] Stabilization PR

### PR DESCRIPTION
**Pull request by anirudhb**
This PR stabilizes the `mod_euc` method on numbers.

In the RFC, the feature for `mod_euc` is `euclidean_modulo`. However, it has been implemented as `euclidean_division`. Should I also stabilize the div methods, or change `mod_euc`'s feature name to `euclidean_modulo`?

Closes #49048

### CODE REVIEW

**Comment by kennytm** [comment]
r? @rust-lang/libs 

Note that the stabilization hasn't been FCP'ed yet.

**Comment by anirudhb** [comment]
Oh I see, I forgot to stabilize the methods in `libstd`

**Comment by anirudhb** [comment]
Ok, now can someone explain the tidy error?

**Comment by kennytm** [comment]
@anirudhb `{f32, f64}::div_euc`.

**Comment by anirudhb** [comment]
Yes, that was my question about whether I should change the feature name of Euclidean modulo to be `euclidean_modulo` (as defined by the RFC) or stabilize the `div_euc` methods.

**Comment by kennytm** [comment]
Well the team will make a choice. But if neither action is taken `tidy` will not accept the code.

**Comment by anirudhb** [comment]
OK, for now I'll change the feature name to `euclidean_modulo` as defined by the RFC. (I'm kinda biased towards that)

**Comment by anirudhb** [comment]
Does this need to be rebased to make tidy succeed? My fork is 1250 commits behind master.

**Comment by clarcharr** [comment]
I personally think that `euc` should be renamed to `euclid` in these cases, and `mod` should be renamed to `rem` for consistency.

**Comment by varkor** [comment]
> I personally think that `euc` should be renamed to `euclid` in these cases, and `mod` should be renamed to `rem` for consistency.

A case for extending the name could be made, but renaming to `rem` would be _inconsistent_ with Rust's current naming scheme (and mathematical convention). The remainder of a division operator is different to the modulo of a division.

**Comment by kennytm** [comment]
> and `mod` should be renamed to `rem` for consistency.

Or we could go full inconsistency renaming `div_euc` to `quot_euc` 😛

**Comment by clarcharr** [comment]
@varkor I beg to differ; `mod_euc` returns the remainder of Euclidean division. Euclidean division is defined specifically so that the modulus is the remainder. :p

In terms of renaming `div` to `quot`: it's quotrem and divmod, so having divrem and quotmod is super weird.

**Comment by anirudhb** [comment]
@clarcharr @kennytm @varkor This PR is not for that. If you would like, I could close this PR and reopen it once discussion about names have been resolved.

**Comment by kennytm** [comment]
@anirudhb Let's bring this to the tracking issue #49048 then. We could submit the stabilization PR after FCP is complete.

**Comment by anirudhb** [comment]
Okay, since there seems to be further discussion about naming.

**Pull request closed without merging**
