### PR TITLE
[WIP] rustc: Reimplement native library overriding and reordering

### LINKED ISSUE #73319: Linked native libraries are sometimes deduplicated and sometimes not deduplicated
The approximate rule is that deduplication happens when `-l` options on command line are involved (which override or not override `#[link]` attributes) and don't happen when only `#[link]` attributes are involved.
I don't want to get into the details here because I plan to fix this myself in some near future, but I'll perhaps extend it if the plan fails.

https://github.com/rust-lang/rust/issues/47989 raised this issue previously and https://github.com/rust-lang/rust/pull/57018 changed the rules in this area somewhat, and the PR author was lucky to get the desired linking order after the changes, but someone else could be less lucky and get broken order instead.

What could be a correct solution to this issue:
- Never deduplicate.
Safe choice, but may result in some redundant libraries passed to the linker.
Library renaming will still work (`#[link(name = "zoo")]` + `-lfoo -lzoo:myzoo` -> `-lmyzoo -lfoo -lmyzoo`) but will pass one potentially redundant linker option.
(There are alternatives, e.g. consider options with `:renames` "directives" rather than libraries and remove them after applying the renaming.)

- Always deduplicate, but provide an opt-out for cases when an option/attribute must not be deduplicated.
The non-deduplicatable cases should be pretty rare after all.
    ```
    #[link(name = "foo", modifiers = "-dedup")]
    ```
    or something.

We could potentially switch from the alternative 1 to alternative 2 on edition boundary if there's enough interest.

### PR DESCRIPTION
**Pull request by petrochenkov**
Addresses the question (1) from https://github.com/rust-lang/rust/pull/93901#issuecomment-1041325522
Fixes https://github.com/rust-lang/rust/issues/73319

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot run mode=build-only

**Comment by petrochenkov** [comment]
@craterbot run mode=build-only p=1 crates=https://crater-reports.s3.amazonaws.com/pr-94962/retry-regressed-list.txt

**Comment by mati865** [comment]
@petrochenkov crater won't include your latest changes because there was no try build.

**Comment by petrochenkov** [comment]
Ah, you are right.
@craterbot abort

**Comment by petrochenkov** [comment]
@craterbot run mode=build-only p=1 crates=https://crater-reports.s3.amazonaws.com/pr-94962/retry-regressed-list.txt

**Comment by petrochenkov** [comment]
@craterbot run mode=build-only p=1 crates=https://crater-reports.s3.amazonaws.com/pr-94962-1/retry-regressed-list.txt

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/96885.

**Comment by JohnCSimon** [comment]
@petrochenkov 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
