### PR TITLE
Stabilize Ratified RISC-V Target Features

### PR DESCRIPTION
**Pull request by coastalwhite**
Stabilization PR for the ratified RISC-V target features. This stabilizes some of the target features tracked by #44839. This is also a part of #114544 and eventually needed for the RISC-V part of rust-lang/rfcs#3268.

There is a similar PR for the the stdarch crate which can be found at rust-lang/stdarch#1476.

This was briefly discussed on Zulip
(https://rust-lang.zulipchat.com/#narrow/stream/250483-t-compiler.2Frisc-v/topic/Stabilization.20of.20RISC-V.20Target.20Features/near/394793704).

Specifically, this PR stabilizes the:
* Atomic Instructions (A) on v2.0
* Compressed Instructions (C) on v2.0
* ~Double-Precision Floating-Point (D) on v2.2~
* ~Embedded Base (E) (Given as `RV32E` / `RV64E`) on v2.0~
* ~Single-Precision Floating-Point (F) on v2.2~
* Integer Multiplication and Division (M) on v2.0
* ~Vector Operations (V) on v1.0~
* Bit Manipulations (B) on v1.0 listed as `zba`, `zbc`, `zbs`
* Scalar Cryptography (Zk) v1.0.1 listed as `zk`, `zkn`, `zknd`, `zkne`, `zknh`, `zkr`, `zks`, `zksed`, `zksh`, `zkt`, `zbkb`, `zbkc` `zkbx`
* ~Double-Precision Floating-Point in Integer Register (Zdinx) on v1.0~
* ~Half-Precision Floating-Point (Zfh) on v1.0~
* ~Minimal Half-Precision Floating-Point (Zfhmin) on v1.0~
* ~Single-Precision Floating-Point in Integer Register (Zfinx) on v1.0~
* ~Half-Precision Floating-Point in Integer Register (Zhinx) on v1.0~
* ~Minimal Half-Precision Floating-Point in Integer Register (Zhinxmin) on v1.0~

r? @Amanieu

### CODE REVIEW

**Comment by Amanieu** [comment]
This is an FCP for both adding the target features to the language via `#[target_feature]` and for adding them to the standard library via `is_riscv_feature_detected!`. These features (including the feature names) have been standardized by the RISC-V foundation.

@rfcbot fcp merge

**Comment by RalfJung** [comment]
On x86 we are having some trouble because it is possible to *disable* features that are enabled by default.

Are there any such RISC-V features? Can we ensure that all features that our targets have by default cannot be disabled by the user?

**Comment by Amanieu** [comment]
On RISC-V the ABI is [explicitly specified](https://github.com/rust-lang/rust/blob/0f3d72aa7a71b58f487b7e4ed663cf5b23b746fd/compiler/rustc_target/src/spec/riscv64gc_unknown_linux_gnu.rs#L13) in the target spec, independently of which target features are used. Obviously, you need to enable the FP instructions if you are using a hard-float ABI, but otherwise I don't think this would cause any issues.

**Comment by RalfJung** [comment]
What happens if you write a function with float argument/return types and you have the FP instruction feature disabled? How do arguments get passed? Or does codegen abort in that case?

**Comment by Amanieu** [comment]
I think LLVM just fails with an assert.

**Comment by RalfJung** [comment]
We should really ensure this is the case, with a test. Fixing "target features are affecting the ABI" later is such a pain.

**Comment by coastalwhite** [comment]
I am happy to write a test for this. This will do this on Monday.

**Comment by ehuss** [comment]
Can you please post a PR to update the documentation at https://github.com/rust-lang/reference/blob/HEAD/src/attributes/codegen.md#the-target_feature-attribute?

**Comment by coastalwhite** [comment]
> Can you please post a PR to update the documentation at https://github.com/rust-lang/reference/blob/HEAD/src/attributes/codegen.md#the-target_feature-attribute?
> 
> 

I will do that as well. I noticed that there is a patch necessary as well on [the page for in-line assembly](https://doc.rust-lang.org/reference/inline-assembly.html). Vector registers are supported as register in the inline assembly already.

**Comment by Amanieu** [comment]
> I will do that as well. I noticed that there is a patch necessary as well on [the page for in-line assembly](https://doc.rust-lang.org/reference/inline-assembly.html). Vector registers are supported as register in the inline assembly already.

There are currently no valid types that you can pass as input/output asm operands for vector registers. This will be solved once we have support for scalable vectors in stdarch.

**Comment by coastalwhite** [comment]
Passing `in("v3")` worked for before, but maybe Rust doesn't officially support that.

**Comment by Amanieu** [comment]
> Passing `in("v3")` worked for before, but maybe Rust doesn't officially support that.

I don't think it ever worked:
```
error: register class `vreg` can only be used as a clobber, not as an input or output
 --> <source>:4:10
  |
4 | asm!("", in("v3") x);
  |          ^^^^^^^^^^

error: type `i32` cannot be used with this register class
 --> <source>:4:19
  |
4 | asm!("", in("v3") x);
  |                   ^
  |
  = note: register class `vreg` supports these types: 

error: aborting due to 2 previous errors
```

**Comment by coastalwhite** [comment]
This <https://godbolt.org/z/rcGTfbMM7> works for me, but it is on an `out("v0")`.

**Comment by Amanieu** [comment]
Yes, you can only use it as a clobber with `_`. You can't actually move values in/out of the asm.

**Comment by coastalwhite** [comment]
Ah, I could have sworn that the `Only clobbers` in the reference was not there before, I must have overlooked it. Never mind then.

**Comment by coastalwhite** [comment]
> We should really ensure this is the case, with a test. Fixing "target features are affecting the ABI" later is such a pain.

It seems like this currently does *not* fail codegen. We get messages saying what we are doing is probably incorrect, but no exit on codegen. It actually just ignores the target ABI and falls back to the ABI without hard floats.

The message:

```
Hard-float 'd' ABI can't be used for a target that doesn't support the D instruction set extension (ignoring target-abi)
```

[Here](https://godbolt.org/z/hxsdoMhKn) is the reproduction on Compiler Explorer as well. It shows the same message and also does not fail.

**Comment by coastalwhite** [comment]
@RalfJung Is there something that Rust can do to fix this internally, or is this a LLVM issue?

**Comment by RalfJung** [comment]
For x86 the tentative plan was to reject `-x87` as a feature flag, thus ensuring we won't generate functions with the wrong ABI. An alternative we are considering in https://github.com/rust-lang/rust/issues/116558 is to reject certain types to be passed by-value when the corresponding ABI features are missing.

What's not quite clear is how to handle softfloat situations. Presumably if you are using softfloats you want to be able to pass them around by-value. IMO we should have this distinction on the target level: `i686-unknown-linux-gnu` is a hardfloat target and `-87` is banned, so floats are always passed in appropriate SSE/x87 registers; `x86_64-unknown-none` is a softfloat target and `x87` (and all other float/vector-related features) are banned so floats and SIMD types are always passed on the stack or in general-purpose registers.

**Comment by RalfJung** [comment]
Looking at the feature list, `f`, `d`, and `v` seem to have the highest risk of affecting ABI. I played around with this a bit and [this](https://godbolt.org/z/bMG4vjcdY) is as far as I got -- there's a clear difference visible for `d` affecting `f64` ABI, but I at least for that function it looks like `v` doesn't affect the ABI of `f32x4`? Obviously when I make it [actually do something](https://godbolt.org/z/xfKq94Mjb) it uses different instructions, but I cannot tell if the input/output is passed via the same registers.

**Comment by coastalwhite** [comment]
RISC-V does not have traditional fixed size SIMD instructions, it instead uses scalable vectors. Portable SIMD for RISC-V afaik uses the `p` extension which has not been ratified yet. I would not want the `p` extension to be part of this stabilization PR. The `v` target feature currently only allows for implicit codegen (or inline assembly). Explicit codegen with intrinsics is tracked in rust-lang/rfcs#3268.

**Comment by coastalwhite** [comment]
> Looking at the feature list, `f`, `d`, and `v` seem to have the highest risk of affecting ABI. I played around with this a bit and [this](https://godbolt.org/z/bMG4vjcdY) is as far as I got -- there's a clear difference visible for `d` affecting `f64` ABI, but I at least for that function it looks like `v` doesn't affect the ABI of `f32x4`? Obviously when I make it [actually do something](https://godbolt.org/z/xfKq94Mjb) it uses different instructions, but I cannot tell if the input/output is passed via the same registers.

I think there is actually also a concern about `Zfinx`, `Zhinx` and `Zdinx`. This changes the ABI to the normal registers for floats, but still uses hard-floats. It is also incompatible with `f` and `d`. And no warning there.

**Comment by RalfJung** [comment]
> RISC-V does not have traditional fixed size SIMD instructions, it instead uses scalable vectors. Portable SIMD for RISC-V afaik calls the p extension (when available) which has not been ratified yet. I would not want the p extension to be part of this stabilization PR. The v target feature currently only allows for implicit codegen (or inline assembly). Explicit codegen with intrinsics is tracked in https://github.com/rust-lang/rfcs/pull/3268.

Ah I see.  I looked for float vector operations in https://doc.rust-lang.org/nightly/core/arch/riscv64/index.html but could not find any either.

So looks like `v` is harmless from an ABI perspective then, but `f` and `d` are problematic, and the `Z` extensions as well if they affect ABI.

**Comment by RalfJung** [comment]
Yeah, as far as I can tell, not stabilizing `f` and `d` would resolve my concerns. It's the ability to *opt-out* of these default features that is causing issues.

**Comment by workingjubilee** [comment]
> RISC-V does not have traditional fixed size SIMD instructions, it instead uses scalable vectors. Portable SIMD for RISC-V afaik calls the `p` extension (when available) which has not been ratified yet. I would not want the `p` extension to be part of this stabilization PR. The `v` target feature currently only allows for implicit codegen (or inline assembly). Explicit codegen with intrinsics is tracked in [rust-lang/rfcs#3268](https://github.com/rust-lang/rfcs/pull/3268).

`core::simd` compiles to RVV instructions when available, actually.

**Comment by coastalwhite** [comment]
I removed the stabilization of the target features, which may lead to ABI incompatibilities. For these, it should be figured out later where they want to be kept with some workaround for the ABI or whether they should because part of the target triple.

The target features that are now *not* being stabilized by this PR:
- `d`: Double-Precision Floating-Point (Due to #116344)
- `f`: Single-Precision Floating-Point (Also due to #116344)
- `e`: Embedded (Changes available GP registers amount from 32 to 16)
- `v`: Vector Instructions (Needs to be figured out in rust-lang/rfcs#3268).

There is now also a PR for the rust reference with the stabilized target features in rust-lang/reference#1415.

Let me know if there are any other concerns.

**Comment by Amanieu** [comment]
I would also remove Zfinx, Zhinx and Zfinx for the same reason: they change the way floating point values are passed in the ABI.

**Comment by coastalwhite** [comment]
> I would also remove Zfinx, Zhinx and Zfinx for the same reason: they change the way floating point values are passed in the ABI.

This was shortly discussed in #116558. I don't think it is needed, as they don't change the ABI in comparison to softfloats. But I can remove them as well if that would block stabilizing the others.

**Comment by workingjubilee** [comment]
I think holding them back while we figure out what our story is going to be is reasonable, even if they *should* be safe.

**Comment by workingjubilee** [comment]
> e: Embedded (Changes available GP registers amount from 32 to 16)

I thought we don't actually use more than 16 registers for parameter passing?

**Comment by coastalwhite** [comment]
> I thought we don't actually use more than 16 registers for parameter passing?

RISC-V uses the `a0` to `a7` registers for argument passing.

From the RISC-V ISA Manual:

> The RISC-V calling convention passes arguments in registers when possible. Up to eight integer registers, a0–a7, and up to eight floating-point registers, fa0–fa7, are used for this purpose.

The embedded `E` extension does not include the upper 16 GP registers, which include `a6` and `a7`. Therefore, they are ABI incompatible.

**Comment by coastalwhite** [comment]
PR is now updated to *not* include the `Zfh`, `Zfhmin`, `Zfinx`, `Zdinx`, `Zhinx` and `Zhinxmin`.

I also updated the reference PR (rust-lang/reference#1415) and the stdarch PR (rust-lang/stdarch#1476).

I don't think there should be any additional concerns, but still, if there are, please let me know.

**Comment by tmandry** [comment]
Seems reasonable. Thanks for pushing this through!

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Review by vishalverma8200 — APPROVED** [review]

**Review by vishalverma8200 — CHANGES_REQUESTED** [review]
****

**Comment by kupiakos** [comment]
https://github.com/rust-lang/rust/pull/116485/#issue-1930078088 does not mention the `zbb` extension but the diff is the same as for `zba`, `zbc`, and `zbs`. Should it be edited?

**Comment by coastalwhite** [comment]
Indeed `zbb` is also stabilised, what do you think should it be edited?

**Pull request merged**
