### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #132419 (PassWrapper: adapt for llvm/llvm-project@b01e2a8b5620466c3b)
 - #132437 (coverage: Regression test for inlining into an uninstrumented crate)
 - #132458 (get rid of a whole bunch of unnecessary rustc_const_unstable attributes)
 - #132520 (NFC add known bug nr to test)
 - #132522 (make codegen help output more consistent)
 - #132523 (Added regression test for generics index out of bounds)
 - #132528 (Use `*_opt` typeck results fns to not ICE in fallback suggestion)

Failed merges:

 - #132511 (stabilize const_arguments_as_str)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=132419,132437,132458,132520,132522,132523,132528)

### CODE REVIEW

**Comment by workingjubilee** [comment]
wait, that's weird, this failed on timeout.

**Comment by Kobzol** [comment]
This is something else, it failed after 5 minutes, because a Docker registery was not responding (it was a network timeout).

**Comment by workingjubilee** [comment]
Oh okay, weird.

**Pull request closed without merging**
