### PR TITLE
Fix off-by-one error in column number in `explain_span`.

### LINKED ISSUE #41938: Lifetime scope note messages have off-by-one column numbers.
The [`explain_span`](https://github.com/rust-lang/rust/blob/e19ccb71c8427135a69d874623af68422aeeb9e9/src/librustc/infer/error_reporting/mod.rs#L116) function used for them doesn't convert `lo.col` to be 1-based.

Noticed because in #41914 some messages ended up looking like this:
```rust
note: the anonymous lifetime #2 defined on the function body at 15:0...
```

### PR DESCRIPTION
**Pull request by fhartwig**
Fixes #41938

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Ordinarily, I'd say let's add a test, but I'm not sure it's worth it in this particular case, since I think those error messages are fairly fragile and likely to be changed.

**Comment by fhartwig** [comment]
Okay, I've fixed the test and amended the commit.

**Comment by Mark-Simulacrum** [comment]
err... no

@bors r-

@bors r=nikomatsakis

**Pull request merged**
