### PR TITLE
tests: Fix the SIMD FFI tests with certain x86 configuration

### PR DESCRIPTION
**Pull request by liushuyu**
This pull request fixes the SIMD FFI tests with certain x86 configurations by gating the SSE2 intrinsic behind the `sse2` feature gate. A generic LLVM intrinsic that is easy to un-fuse on those platforms is added to compensate for those platforms.

### CODE REVIEW

**Comment by workingjubilee** [comment]
I see.

@bors r+ rollup

**Comment by liushuyu** [comment]
Sorry, I had some skill issues :tm: managing the `git stash`; now I have pushed the correct changes.

**Comment by workingjubilee** [comment]
granted, we don't run tests on them, but still

**Comment by liushuyu** [comment]
> granted, we don't run tests on most bare metal targets, but still

According to https://gitlab.com/x86-psABIs/x86-64-ABI, at least on Linux, "x86_64 (baseline)" means SSE + SSE2. I could not find information for Windows, but according to https://en.wikipedia.org/wiki/X86-64#AMD64 it seems like SSE registers are a standard at least for AMD64.

**Comment by liushuyu** [comment]
Oh, sorry, you meant freestanding implementations, my bad. I will change the test.

**Comment by liushuyu** [comment]
Done. The test is updated to gate both `x86` platforms behind the `sse2` feature gate.

**Comment by workingjubilee** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
