### PR TITLE
Revert "Assume slice len is bounded by allocation size"

### PR DESCRIPTION
**Pull request by nagisa**
https://github.com/rust-lang/rust/pull/77023#issuecomment-703987379
suggests that the original PR introduced a significant perf regression.

This reverts commit e44784b8750016a695361c990024750e037d8f9f / #77023.

cc @HeroicKatora

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me, but looks like other stuff started using the features so we'll need to retain them

**Comment by nagisa** [comment]
Huh, I force pushed but github is taking its time catching it...

**Comment by Mark-Simulacrum** [comment]
perf results on landing are about as expected; a small win. There are some regressions too but nothing too large and on recently-added benchmarks. I would not worry about them right now.

- Moderate improvement in [instruction counts](https://perf.rust-lang.org/compare.html?start=cae8bc1f2324e31c98cb32b8ed37032fc9cef405&end=87b71ed68b69361ab0d45653a972ad4cf7a65cba&stat=instructions:u) (up to -2.5% on `incr-patched: Job` builds of `regex-opt`)
- Moderate regression in [instruction counts](https://perf.rust-lang.org/compare.html?start=cae8bc1f2324e31c98cb32b8ed37032fc9cef405&end=87b71ed68b69361ab0d45653a972ad4cf7a65cba&stat=instructions:u) (up to 1.3% on `full` builds of `match-stress-enum-check`)

**Pull request merged**
