### PR TITLE
rustdoc: color the question mark operator

### PR DESCRIPTION
**Pull request by est31**
The idea of coloring `?` specially was proposed by @eddyb in: https://github.com/rust-lang/rust/issues/31436#issuecomment-247426582

### CODE REVIEW

**Comment by est31** [comment]
How it looks now:
highlight

Please suggest better options if you prefer stronger colors.

**Comment by est31** [comment]
**cc** @GuillaumeGomez for the case you haven't seen it yet.

**Comment by GuillaumeGomez** [comment]
I don't like '?'. :'(

:trollface: I thought question mark was considered explicit enough by himself.

serious_mode="on":
I'll do it.

**Comment by GuillaumeGomez** [comment]
Otherwise it's a nice idea. Just want others' opinion.

cc @steveklabnik

**Comment by eddyb** [comment]
Why not bold + max saturation?

**Comment by est31** [comment]
Put saturation from 77 to 95 now, and made it bold. Saturation of 100 (`#f58300`) looks less appealing, I think. The current state:

highlight2

**Comment by est31** [comment]
> I don't like '?'. :'(

Me neither in fact. But decision was to stabilize it, so we have to live with it :/.

This PR intends to highlight `?` so that it is more visible, addressing the "? can be overlooked too easily" concern.

**Comment by eddyb** [comment]
It's either the font or the color-abusing scheme that makes it hard to spot. At least bold is slightly better.
(I mean, *red* for `self` and `Ok`?! Anyway I'm not a web designer so I won't comment further)

**Comment by est31** [comment]
Yes, its far from perfect, but it improves the situation. I don't have much skills in this kind of work either. I have tried changing the background color, but couldn't come up with anything that didn't look totally ugly until I went with normal backgrounds and copied the line number's color for the font.

If nobody has ideas to make it better, changes to make `?` easier to spot will still be possible in the future as well.

**Comment by GuillaumeGomez** [comment]
@est31: try with `#ff9011`.

**Comment by steveklabnik** [comment]
I think it's a good idea to highlight, I don't have strong feelings about the details.

**Comment by GuillaumeGomez** [comment]
New screenshot please. :D

**Comment by est31** [comment]
highlight3

**Comment by GuillaumeGomez** [comment]
Ah nice, a bit better for me.

For now, since it seems that no one has strong feeling about this PR, I'll r+ it. If anyone has issue with it, it'll still be possible to rollback.

@est31: Thanks!

@bors: r+ rollup

**Comment by eddyb** [comment]
Okay this is frustrating so I'l speak again: IMO the way the scheme uses bright words for common colors is dumb. It makes it impossible to bring attention to anything when you have a colorfest.
Swapping the orange and the red would probably be a major improvement already.

**Comment by est31** [comment]
Hmm should that failure be a concern for me?

The error seems to be:

```
configure: error: in `/buildslave/rust-buildbot/slave/auto-linux-cross-opt/build/obj/powerpc64-unknown-linux-gnu/rt/jemalloc':
configure: error: C compiler cannot create executables
```

**Comment by eddyb** [comment]
Everything is failing thereb build bots not set up right.

**Pull request merged**
