### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/59218

cc @Xanewok

### CODE REVIEW

**Comment by Xanewok** [comment]
@mati865 As in https://github.com/rust-lang/rust-clippy/pull/3893#issuecomment-473997089, could we also include:
- RLS bump to https://github.com/rust-lang/rls/commit/90f7ab070321ebc5ad217dc0d6db163c029dffd9
- Rustfmt bump to https://github.com/rust-lang/rustfmt/commit/1427e4c20ba5cdc80a338347585c9de71a0dea4d

This should also update rustc-ap-* to v407

**Comment by mati865** [comment]
```
Updating only changed submodules
Updating submodule src/tools/rustfmt
Submodules updated in 0.12 seconds
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  patch for `rustfmt-nightly` in `https://github.com/rust-lang/crates.io-index` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
failed to run: /home/mateusz/Projects/rust/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /home/mateusz_arch/Projects/rust/rust/src/bootstrap/Cargo.toml
```
Looking into.

**Comment by Xanewok** [comment]
@mati865 remove https://github.com/rust-lang/rust/blob/225c5bf5dd4049c57ba88fdf73e2531aaff1f954/Cargo.lock#L3160-L3189 and this try again (this should prune old rustc-ap-* v373, RLS now only uses Rustfmt 1.1)

**Comment by mati865** [comment]
Finally old `scoped-tls` and `parking_lot` are dropped :trophy:.

@bors r=Xanewok

**Comment by Xanewok** [comment]
Nice, thanks!

@bors p=5

**Comment by Xanewok** [comment]
What I believe is the issue:
> [02:15:54] error: failed to download from `https://crates.io/api/v1/crates/filetime/0.1.10/download`
[02:15:54] 
[02:15:54] Caused by:
[02:15:54]   failed to get 200 response from `https://static.crates.io/crates/filetime/filetime-0.1.10.crate`, got 504

@bors retry

**Pull request merged**
