### PR TITLE
Add `cmp::{min_by, min_by_key, max_by, max_by_key}`

### PR DESCRIPTION
**Pull request by timvermeulen**
This adds the following functions to `core::cmp`:

- `min_by`
- `min_by_key`
- `max_by`
- `max_by_key`

`min_by` and `max_by` are somewhat trivial to implement, but not entirely because `min_by` returns the first value in case the two are equal (and `max_by` the second). `min` and `max` can be implemented in terms of `min_by` and `max_by`, but not as easily the other way around.

To give an example of why I think these functions could be useful: the `Iterator::{min_by, min_by_key, max_by, max_by_key}` methods all currently hard-code the behavior mentioned above which is an ever so small duplication of logic. If we delegate them to `cmp::{min_by, max_by}` methods instead, we get the correct behavior for free. (edit: this is now included in the PR)

I added `min_by_key` / `max_by_key` for consistency's sake but I wouldn't mind removing them. I don't have a particular use case in mind for them, and `min_by` / `max_by` seem to be more useful.

Tracking issue: #64460

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage
@timvermeulen 
@withoutboats @cuviper Can you please review this?

Thanks.

**Comment by cuviper** [comment]
> To give an example of why I think these functions could be useful: the `Iterator::{min_by, min_by_key, max_by, max_by_key}` methods all currently hard-code the behavior mentioned above which is an ever so small duplication of logic. If we delegate them to `cmp::{min_by, max_by}` methods instead, we get the correct behavior for free.

Did you try making this change?

**Comment by timvermeulen** [comment]
@cuviper I did indeed, here's the diff: https://github.com/timvermeulen/rust/commit/aed2e46d4d84a76438f02fb64b1705bb08360a37

It's not a huge win, but it gets rid of the stability logic. And I guess it's also nice to have them in terms of the more general `fold1` rather than `select_fold1`.

**Comment by cuviper** [comment]
I like it! Care to add that motivation to this PR?

Fill in a tracking issue too, and I think we can land this.

**Comment by timvermeulen** [comment]
@cuviper Thanks, I added it.

**Comment by cuviper** [comment]
I meant to actually include the iterator commit here, but it can be a followup if you prefer.

The tracking issue number needs to be set in the `#[unstable]` attributes.

**Comment by timvermeulen** [comment]
Ah, I was going to submit a follow-up, but I'm happy to include it here too.

**Comment by cuviper** [comment]
Looks great, thanks!

@bors r+

**Pull request merged**
