### PR TITLE
Associated constants for new duration constructors

### PR DESCRIPTION
**Pull request by edwardwc**
Add associated constants to the unstable Duration constructors. The tracking issue for these constructors is [#120301](https://github.com/rust-lang/rust/issues/120301).

This change aims to make interacting with time more clean and intuitive by providing predefined duration constants.

For example, to use a static for your sleep intervals:
```rs
static SLEEP_INTERVAL: Duration = Duration::HOUR;

...

sleep(SLEEP_INTERVAL)
```

Or with use of a `lazy_static`
```rs
lazy_static! {
    static ref SLEEP_INTERVAL: Duration = 5 * Duration::MINUTE;
}

...

sleep(*SLEEP_INTERVAL)
```

Or, to use it plainly
```rs
sleep(Duration::WEEK)
```

### CODE REVIEW

**Review by djc — APPROVED** [review]
Adding these makes sense to me -- not sure if they should be part of the same feature?

**Comment by edwardwc** [comment]
@djc up to you. My thinking is it could be reasonable to bundle these associated constants with their required constructor counterparts as one feature.

**Comment by djc** [comment]
I don't think it's up to me -- I'm not a libs reviewer.

**Comment by Dylan-DPC** [comment]
@edwardwc this needs an ACP to be written to proceed. Once you have submitted the ACP, you can mention it here (preferably in the pr description)

**Comment by alex-semenyuk** [comment]
@edwardwc
From wg-triage. Any updates on this?

**Pull request closed without merging**
