### PR TITLE
[core] Fix a soundness hole in `core::sync::Exclusive`

### PR DESCRIPTION
**Pull request by dead-claudia**
Just like `Mutex<T>` is only `Sync` if `T` is `Send`, `Exclusive<T>` should contain the same constraints.

As an example, `sd_journal*` instances created per https://www.freedesktop.org/software/systemd/man/sd_journal_open.html# cannot be either `Send` or `Sync`, and wrapper types likewise can't.

> All functions listed here are thread-agnostic and only a single specific thread may operate on a given object during its entire lifetime. It's safe to allocate multiple independent objects and use each from a specific thread in parallel. **However, it's not safe to allocate such an object in one thread, and operate or free it from any other, even if locking is used to ensure these threads don't operate on it at the very same time.**

The current API would technically allow a wrapper that (correctly) doesn't implement `Send` or `Sync` to be erroneously moved to another thread. This fixes that soundness hole.

Edit: Relevant issue: https://github.com/rust-lang/rust/issues/98407

### CODE REVIEW

**Comment by clubby789** [comment]
The purpose of `Exclusive` is to *always* implement `Sync`, so adding bounds goes against the documented behavior. This implementation upholds the contract for `Sync`:
> the safety requirements of Sync state that for Exclusive to be Sync, it must be sound to share across threads, that is, it must be sound for &Exclusive to cross thread boundaries. By design, a &Exclusive has no API whatsoever, making it useless, thus harmless, thus memory safe.

**Comment by ibraheemdev** [comment]
> The current API would technically allow a wrapper that (correctly) doesn't implement Send or Sync to be erroneously moved to another thread. This fixes that soundness hole.

It does not, because `Exclusive<T: !Send>` does not implement `Send`.

**Comment by dead-claudia** [comment]
Closed since I can't seem to find a `std` counterexample to @ibraheemdev's claim.

**Pull request closed without merging**
