### PR TITLE
Add codegen tests for identity matching results

### PR DESCRIPTION
**Pull request by Kobzol**
This is an attempt to write codegen tests to ensure that returning an identity of a `Result` does not have unnecessary overhead (https://github.com/rust-lang/rust/issues/37939).

This is my first codegen test, so take it easy on me.

Btw, I noticed that for `Result<u32, u32>` it generates less optimal code (https://rust.godbolt.org/z/YEcjTboYK). Seems like some aggregate ABI issue.

r? @scottmcm

### CODE REVIEW

**Comment by scottmcm** [comment]
Doh, we raced on this -- I opened #100693 two minutes after you did this one 😆

**Comment by Kobzol** [comment]
Aaah! :D Well, let's keep your PR, you know much more about this. At least I learned how to write a codegen test :)

**Comment by scottmcm** [comment]
Looks like you did a pretty good job!  Always good to have more people who can help out with pinning or `E-needs-test` things!

The two review notes I'd have to help you in future:
- Some of the builders run on system LLVM that's not our up-to-date in-tree LLVM, thus why you'll see things like `// no-system-llvm` in a bunch of them.  So these tests -- where it's an LLVM change that made them work -- need to have some sort of attribute or they'll pass CI but break in bors on those other LLVMs.
- I strongly suggest using `CHECK-LABEL` to help make sure your other `CHECK`s match where you think they're going to match, rather than potentially matching way later in the file and giving a confusing error.  See <https://llvm.org/docs/CommandGuide/FileCheck.html#the-check-label-directive>.

**Comment by scottmcm** [comment]
> Btw, I noticed that for `Result<u32, u32>` it generates less optimal code (https://rust.godbolt.org/z/YEcjTboYK). Seems like some aggregate ABI issue.

Oh, that's really interesting!  Since `Result` is `repr(Rust)`, I know of no reason why `Result<i32,i32>`/`Result<i32,u32>`/`Result<u32,i32>`/`Result<u32,u32>` shouldn't just all use the same ABI -- though I also don't know much about ABI.

Can you file an issue about it?  Definitely seems weird enough to be worth one, at least.

(Though it's nice that it's still a nop, just a two-register nop instead of a one-register nop.)

**Comment by Kobzol** [comment]
Thanks a lot for the hints! I filed https://github.com/rust-lang/rust/issues/100698.

**Pull request closed without merging**
