### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by flip1995** [comment]
@Jarcho The patch https://github.com/rust-lang/rust-clippy/pull/7565 caused an error with the `itertools dep in the UI tests. I temporarily removed the test case depending on it.

**Comment by Manishearth** [comment]
@bors r-

```
---- compile_test stdout ----
thread 'compile_test' panicked at '
----------------------------------------------------------------------
ERROR: Found multiple rlibs for crates: `itertools`
Try removing the stageN-tools directory or remove the following files:

/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-25dc0cde4ae95530.rlib \
/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-a462d7304c071790.rlib \
/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-079b879cf9789047.rlib
```

uh oh

**Comment by Jarcho** [comment]
You'll probably need to comment out line 42 in `compile-test.rs` as well for a quick fix.

**Comment by Jarcho** [comment]
I have a fix here rust-lang/rust-clippy#7630. Don't know if you want to try and pull that in or not.

**Comment by flip1995** [comment]
Hm, now we missed the beta branching before the release next week anyway. So yeah, let's get this fixed and then do the proper sync.

**Comment by flip1995** [comment]
Let's try if https://github.com/rust-lang/rust-clippy/pull/7631 solves this.

**Comment by flip1995** [comment]
It did. But we have to get it merged first. Let's wait for it. The official sync day is only tomorrow anyway.

**Comment by flip1995** [comment]
@Manishearth This is now ready. Regular sync day is tomorrow, but I would just go ahead and sync it now.

**Pull request merged**
