### PR TITLE
will_wake tests fail on Miri and that is expected

### PR DESCRIPTION
**Pull request by RalfJung**
Follow-up to https://github.com/rust-lang/rust/pull/121622
r? @cuviper @dtolnay

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thank you!

If I wanted to try to make this test pass in Miri, does something along the lines of https://github.com/rust-lang/rust/commit/c4c5b3decad536ab4476f63e15f0ed036db71d73 seem promising? This was the original draft of #121622. Maybe the right fix involves making both changes.

**Comment by RalfJung** [comment]
> If I wanted to try to make this test pass in Miri, does something along the lines of https://github.com/rust-lang/rust/commit/c4c5b3decad536ab4476f63e15f0ed036db71d73 seem promising? This was the original draft of https://github.com/rust-lang/rust/pull/121622. Maybe the right fix involves making both changes.

I don't think so. Rust never makes any guarantees about the address identity of promoteds, and so neither does Miri. The only globals with address identity guarantees are `static`. I think it's pretty fundamental that for constants that involve generics, duplication can happen, due to how we do codegen.

**Comment by dtolnay** [comment]
Good call. Then this calls for a language feature. `static VTABLE<W: Wake + Send + Sync + 'static>: RawWakerVTable = ...`

**Comment by RalfJung** [comment]
Generic statics are requested every now and then bot so far nobody proposed a credible implementation strategy. See [here](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Issues.20with.20generic.20statics) for a recent incarnation of this discussion.

**Pull request merged**
