### PR TITLE
Mechanical translation towards making GlobalCtxt implement Sync

### PR DESCRIPTION
**Pull request by Zoxc**
This PR is split out from https://github.com/rust-lang/rust/pull/45912.

### CODE REVIEW

**Comment by alexcrichton** [comment]
ping @michaelwoerister, did you want to take a look at this?

**Comment by michaelwoerister** [comment]
Nominating for discussion in the @rust-lang/compiler team meeting. This is a huge change that I can't approve by myself. Also, I think we should have a broader, more open discussion about multi-threading support in the compiler. I feel that such a thing would need an RFC.

**Comment by eddyb** [comment]
I've insistented on numerous occasions on IRC that `rustc` is currently optimized for straight-line and single-threaded performance and we'd have to redesign core parts of it for parallelism.

It is plausible that you get *some* speedup even with locks everywhere but it's not ideal IMO.

**Comment by nikomatsakis** [comment]
I do feel like parallelizing rustc seems like a good goal but I would like to see some more design discussion. 

That said, I don't know that I have an objection to *this PR* in particular, which seems like it's probably necessary groundwork? If I understand what's happening here, we're basically just redirecting names on the basis of a configuration option? (i.e., we're still going to be using `Rc` and `RefCell`).

That said, I think I might prefer to use names `Rc` and `RefCell`, but just import them from `rustc_data_structures::sync`. Then the diff would be quite small (we just modify the `use` lines, and that's it), but we achieve the same ends. We can always do The Big Edit at some later point. 

Thoughts?

**Comment by Zoxc** [comment]
> That said, I don't know that I have an objection to this PR in particular, which seems like it's probably necessary groundwork? If I understand what's happening here, we're basically just redirecting names on the basis of a configuration option? (i.e., we're still going to be using Rc and RefCell).

That is indeed what is happening.

> That said, I think I might prefer to use names Rc and RefCell, but just import them from rustc_data_structures::sync. Then the diff would be quite small (we just modify the use lines, and that's it), but we achieve the same ends. We can always do The Big Edit at some later point.

There are a couple of problems with that.
- There are still uses of `Rc`, `Cell` and `RefCell` which do not get redirected to multi-threaded variants so its easy to mix them up. This is particularly problematic if some new use of `Rc` or `RefCell` gets added which refer to the multi-threaded variant, but actually don't require the use of a multi-threaded variant. This means that locks can silently get added. On the other hand, if we use distinct names for the single-threaded and multi-threaded variants, this isn't likely to happen.
- `LockCell` does not get redirected to `Cell`, but is a thin wrapper around `Cell` so that it has the same API as the multi-threaded variant.

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/compiler meeting. Consensus was that @Zoxc would open a thread on internals and we would try to ensure we have some level of agreement on the overall plan before we go forward. Closing PR for now.

**Pull request closed without merging**
