### PR TITLE
[crater only] make forbidden_lint_groups a hard error

### PR DESCRIPTION
**Pull request by RalfJung**
This is to gather information for https://github.com/rust-lang/rust/issues/81670.

### CODE REVIEW

**Comment by RalfJung** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
@craterbot cancel

Crater is currently bugging out and running at 155% completed on another job. I'm gonna clear the queue and re-queue all the jobs in order.

**Comment by compiler-errors** [comment]
Re-queueing now :)

@craterbot check

**Comment by RalfJung** [comment]
I posted my findings at https://github.com/rust-lang/rust/issues/81670#issuecomment-2511832156, this PR is done then.

**Pull request closed without merging**
