### PR TITLE
pretty print BTreeSet

### PR DESCRIPTION
**Pull request by fukatani**
I want pretty printing for BTreeSet.
```rust
use std::collections::*;

fn main() {
  let mut s = BTreeSet::new();
  s.insert(5);
  s.insert(3);
  s.insert(7);
  s.remove(&3);
  println!("{:?}", s);
}
```

```
(gdb) b 9
(gdb) p s
$1 = BTreeSet<i32> with 2 elements = {[0] = 5, [1] = 7}
```
This is analogy of pretty printing for C++ std::set.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Do we have any sort of tests for this code? cc @michaelwoerister @tromey

**Comment by nikomatsakis** [comment]
Also .. I'm probably not the best reviewer here ... one of you two care to pick this up?

**Comment by fukatani** [comment]
I found I should write test here. https://github.com/rust-lang/rust/tree/4ecf12bf0eb8386626ccdb5f721a7183ccc4eba6/src/test/debuginfo

**Comment by michaelwoerister** [comment]
@nikomatsakis, I'll take it.

> I found I should write test here.

@fukatani, yes, that would be great. I don't know why this test is [ignored](https://github.com/rust-lang/rust/blob/4ecf12bf0eb8386626ccdb5f721a7183ccc4eba6/src/test/debuginfo/pretty-std.rs#L13) at the moment.

**Comment by michaelwoerister** [comment]
@fukatani, I re-enabled the `pretty-std.rs` test case in #53154, so once that is merged, you can add your test to that. Alternatively, you can create a separate test file.

**Comment by michaelwoerister** [comment]
Thanks a lot, @fukatani! Looks great. I'm wondering though if `display_hint()` for `BTreeSet` should be `array` instead of `map` since the keys are kind of redundant. 

Also, to make things more consistent with the other collection printers, could you make it `BTreeSet<i32>(len: 3)` instead of `BTreeSet<i32> with 3 elements`?

**Comment by fukatani** [comment]
Current PR behavior is the same as `ordered_set` in C++.
```cpp
#include <set>

int main() {
    std::set<int> map;
    map.insert(5);
    map.insert(6);
    return 0;
}
```

```
>>> b 7
>>> p map
$1 = std::set with 2 elements = {[0] = 6, [1] = 5}
```

I agree that it's a bit redundant.
But is it unnecessary to unify with C++ ``?

**Comment by michaelwoerister** [comment]
So far we have not made any effort to match C++'s pretty printers. I'd rather have the Rust pretty printers be consistent among each other.

**Comment by tromey** [comment]
FWIW the libstdc++ `std::set` printer doesn't emit a display hint at all.

**Comment by fukatani** [comment]
@michaelwoerister 
Sure, I changed pretty printing to `BTreeSet<i32>(len: 3) = {3, 5, 7}`

**Comment by michaelwoerister** [comment]
Thanks, @fukatani!

@bors r+

**Pull request merged**
