### PR TITLE
Revert let_chains stabilization

### PR DESCRIPTION
**Pull request by Noratrieb**
This is the revert against master, the beta revert was already done in #100538.

Bumps the stage0 compiler which already has it reverted.

### CODE REVIEW

**Comment by hkmatsumoto** [comment]
Removing `A-translation` label which looks unrelated.

**Comment by Nilstrieb** [comment]
I'm a little busy this week, I should get to it next week.

**Comment by Nilstrieb** [comment]
@Mark-Simulacrum done, I also migrated the one "new" diagnostic to session diagnostics.

Also, I think this should probably get p=1 since this is pretty bitrotty as it seems

**Pull request merged**
