### PR TITLE
Update RLS and Rustfmt

### PR DESCRIPTION
**Pull request by Xanewok**
Essentially https://github.com/rust-lang/rust/pull/46929 with only RLS update that fixes the build.

The rls wasn't included in the recent nightlies and a lot of people have been wondering what to do about it, so it'd be good to include the RLS back with the nightly builds as soon as we can.

r? @alexcrichton

### CODE REVIEW

**Comment by kennytm** [comment]
Should this update rustfmt as well?

**Comment by Xanewok** [comment]
I wanted to err on the safe side and update only RLS, mostly to fix the build issues.
@nrc Should I also update rustfmt and toolstate.toml?

**Comment by Xanewok** [comment]
@kennytm how does the new https://github.com/rust-lang-nursery/rust-toolstate work? Does it automatically detect touched tools in the tree and publishes appropriate toolstate if it compiles/tests pass?

**Comment by Xanewok** [comment]
Updated rustfmt submodule to [rustfmt@0.3.4](https://github.com/rust-lang-nursery/rustfmt/tree/0.3.4), which is the version that updated RLS uses.

**Comment by kennytm** [comment]
@Xanewok Yes it automatically detects if the tools can be built and tested. If the state changed, the CI will send a commit to update the webpage.

**Pull request merged**
