### PR TITLE
Add serial tests

### PR DESCRIPTION
**Pull request by shivjm**
This PR adds a `#[serial]` attribute that marks tests that should be executed one-by-one rather than concurrently (per #33519).

I’ve confirmed that the `libtest` tests pass. I wasn’t able to run the full suite as a lot of the `run_make` tests seem to fail on my Windows system, but everything passed up to that point. I also ran a tidy check and fixed a couple of small errors.

Rust (and PR!) newbie here, so please do let me know if I’m doing something poorly or incorrectly!

### CODE REVIEW

**Comment by shivjm** [comment]
Just realized I had forgotten to commit the tidy fixes.

**Comment by arielb1** [comment]
Thanks for the PR @shivjm! @brson (or someone else) will be reviewing your PR soon.

**Comment by shivjm** [comment]
I managed to discover a new way to mess up history by rewriting metadata, so this pull request is in a strange spot right now. Would it be a problem if I closed this PR and opened a new one from a different branch with the same result, only a little cleaner? (Apologies, again, for how new I am at this.)

**Comment by Mark-Simulacrum** [comment]
No problem at all! Let us know if there is anything we can help with, feel free to reach out over IRC too, if you want.

**Comment by shivjm** [comment]
Cheers!

**Pull request closed without merging**
