### PR TITLE
Add deprecated_safe feature gate and attribute, cc #94978

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by jhpratt — APPROVED** [review]
LGTM in terms of adding the attribute itself (there's obviously no functionality here yet).

**Comment by skippy10110** [comment]
Is the build failure related to my change? I'm looking here: https://github.com/rust-lang-ci/rust/runs/5570015260?check_suite_focus=true

I see the 5 build attempts in this log, each ending with:
````
The command '/bin/sh -c /scripts/cmake.sh' returned a non-zero code: 1
````

I'm not sure if this is the source of the cmake error, but I also see this in each build attempt:
````
/scripts/cmake.sh: line 14: /tmp/build.log: Permission denied
ERROR: An error was encountered with the build.
````

**Comment by skippy10110** [comment]
Not sure if this is spurious or if I've done something wrong here.

**Comment by Dylan-DPC** [comment]
nah some other prs are failing with the same problem

**Pull request merged**
