### PR TITLE
Add lint warning for inner function marked as `#[test]`

### LINKED ISSUE #36629: Inner function cannot be tested
I really would like to be able to this:

``` rust
fn outer(x: i32) -> i32 {
    fn inner(a: i32, b: i32) -> i32 {
        a + b
    }
    #[test]
    fn test_inner() {
        assert_eq!(inner(3, 5), 8);
    }
    inner(x, 5)
}

#[test]
fn test_outer() {
    assert_eq!(outer(3), 8);
}
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #36629.

### CODE REVIEW

**Comment by estebank** [comment]
@centril in that case I'll create an RFC. This felt small enough as it's warning about already existing behavior, but I can see why we wouldn't want to make exceptions.

**Comment by Centril** [comment]
@estebank yeah I agree that it seems like a small, good and uncontroversial change :) 

It might be a good idea to document what lints need RFCs and which don't.

**Comment by zackmdavis** [comment]
`untestable_method` is a _very confusing_ name.

**Comment by zackmdavis** [comment]
Whatever name is chosen (`untestable_test_functions`??), it should respect [RFC 344](https://rust-lang.github.io/rfcs/0344-conventions-galore.html#lints) (see #50879).

**Comment by pnkfelix** [comment]
This code seems fine. The only thing left is to resolve the name of the lint itself.

How about `unnameable_test_methods`? The lint diagnostic itself can be the thing that points out that such `#[test]` methods are in fact not run by the test harness, while the lint name itself will serve to imply *why* they are not supported.

**Comment by zackmdavis** [comment]
[This](https://github.com/rust-lang/rust/pull/51450/files#diff-9e8e264ffda1e628f06610b6cd3bc16fR16) isn't a "method"; it's a function (as I hear the words usually used).

**Comment by pnkfelix** [comment]
@zackmdavis I don't disagree. The high-order bit of my suggestion was meant to be the "unnameable" part, not the use of the word "methods."

**Comment by estebank** [comment]
Changed lint name.

**Comment by zackmdavis** [comment]
(RFC 344 seems to suggest the plural: unnameable-test-function**s**?)

**Comment by estebank** [comment]
Ping. Anything left for me to do?

**Comment by pietroalbini** [comment]
Ping from triage @pnkfelix! This PR needs your review.

**Comment by estebank** [comment]
Ping.

**Comment by TimNN** [comment]
Ping from triage, @pnkfelix / @rust-lang/compiler: This PR requires your review!

**Comment by cramertj** [comment]
@pnkfelix said `The only thing left is to resolve the name of the lint itself.`, and that happened, so

@bors r=@pnkfelix

**Pull request merged**
