### PR TITLE
set self.is_known_utf8 to false in extend_from_slice

### LINKED ISSUE #126977: Fix internal `Wtf8Buf::extend_from_slice` check
Reviewing PR #126885 had some oversight regarding valid utf8 checks. This was graciously brought to our (meaning myself and @workingjubilee) attention by @yhx-12243 in [this comment](<https://github.com/rust-lang/rust/commit/aa46a3368eb017eba41bfab956c7787d46c09935#r143539097>). Fix should really just be changing [line 483 of wtf8.rs](<https://github.com/rust-lang/rust/blob/a299aa5df79dd8e5a1405b97ddd7b367b61eecc6/library/std/src/sys_common/wtf8.rs#L483>) to setting `self.is_known_utf8` to `false`, unless we decide there may be some merit to iterating again through the `other` buffer.

### PR DESCRIPTION
**Pull request by tnuha**
try-job: x86_64-msvc

closes #126977 
Related to #126885, #126333, and [this conversation](<https://github.com/rust-lang/rust/commit/aa46a3368eb017eba41bfab956c7787d46c09935#r143539097>)

### CODE REVIEW

**Comment by Borgerr** [comment]
r? @workingjubilee
 
@yhx-12243 may be interested

**Comment by workingjubilee** [comment]
@Borgerr I have pushed a set of tests to your branch, please pull before pushing anything.

**Comment by workingjubilee** [comment]
and they had a flipped condition in the third one, of course.

**Comment by Borgerr** [comment]
Tests pass locally! Pushing for CI and going to bed, will review on the morrow. Thank you again for your patience and mentorship.

**Comment by workingjubilee** [comment]
@Borgerr All three should pass.

**Comment by workingjubilee** [comment]
cool.

**Comment by workingjubilee** [comment]
@Borgerr I think the third one will fail the current PR, however.

**Comment by workingjubilee** [comment]
Hmm, maybe not, `push_str` bypasses the check.

**Comment by workingjubilee** [comment]
oh nice.

**Comment by workingjubilee** [comment]
( squashed the last two commits. )

**Pull request merged**
