### PR TITLE
Add `core::array::from_fn`

### PR DESCRIPTION
**Pull request by CryZe**
This adds `core::array::from_fn` for initializing an array from a closure. The API is meant to closely resemble `core::iter::from_fn` with the difference that the array dictates the amount of elements produced as opposed to the function.

This should also cover a lot of cases where one might want to reach for collecting into an array, but without all the associated problems that this would have, such as providing too few or too many elements.

# Example Usage

```rust
let array = std::array::from_fn(|index| 2 * index);
assert_eq!(array, [0, 2, 4, 6]);
```

### CODE REVIEW

**Comment by the8472** [comment]
Would it make sense to pass the index? Iterators can be infinite so it doesn't make sense there, but that doesn't apply to arrays.

**Comment by voidc** [comment]
I think this is very similar to https://github.com/rust-lang/rust/pull/75644.

**Comment by slightlyoutofphase** [comment]
You possibly might want to note in the example you gave that it's specifically the `assert_eq!(array, [0, 2, 4, 6]);` that makes it actually compile. It might not be clear to some people that `rustc` is inferring the length of `array` entirely from the length of the other array it's being compared to, and that it *won't* compile without that line as there's then no way for it to know what length you're asking for.

**Comment by joshtriplett** [comment]
I'd suggest that we discuss on https://github.com/rust-lang/rust/pull/75644 which PR should get merged.

**Comment by JohnCSimon** [comment]
Ping from triage - @CryZe
can you please resolve the merge conflicts?

@Rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by CryZe** [comment]
I'll close this in favor of #75644 which also implements the `try_from_fn` version of this.

**Pull request closed without merging**
