### PR TITLE
NLL: change compare-mode=nll to use borrowck=migrate 

### LINKED ISSUE #55118: NLL: change compare-mode=nll to use borrowck=migrate
We have a couple different modes that NLL can run in.

borrowck=mir is sort of the "adopt NLL whole hog"; it just runs the MIR-based borrow checker, and reports its errors as, well, errors.

borrowck=migrate is the migration plan for the 2018 edition. It runs the MIR-based borrow checker, and if it signals an error, then it runs the old AST-based borrow checker as a backup. If the code is accepted by AST-based borrow checker, then all the MIR-based errors are downgraded to warnings. This is the mode that we'll be deploying for Rust 2018.

Anyway: We are currently testing borrowck=mir for our test suite via `compare-mode=nll`.

The plan is to *deploy* borrowck=migrate.

We have barely any automated testing of borrowck=migrate.

See the problem here?

----

My proposal: We should change `compare-mode=nll` to use `borrowck=migrate` instead of `borrowck=mir`. We should make this change ASAP.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #55118.

This PR is split into two parts:

The first commit is a minor change that fixes a flaw in the existing `borrowck=migrate` implementation whereby a lint that was promoted to an error in the AST borrow checker would result in the same lint from the NLL borrow checker being downgraded to a warning in migrate mode. This PR fixes this by ensuring lints are exempt from buffering in the NLL borrow checker.

The second commit updates `compiletest` to make the NLL compare mode use `-Z borrowck=migrate` rather than `-Z borrowck=mir`. The third commit shows all the test output changes that result from this.

r? @pnkfelix

### CODE REVIEW

**Comment by pnkfelix** [comment]
This PR looks fine as it stands. I didn't read over everything in commit 539404b, but I did some spot checking  of the changes in output.

However, there is some debate about whether this PR should land before or after we do the third and final round of .stderr review #54528 ... so I'm delaying slightly on r+'ing this until after we've resolved that Question.

**Comment by pnkfelix** [comment]
(i gave this priority=1 because I'm concerned about the .stderr files going stale quickly.)

**Comment by Mark-Simulacrum** [comment]
@bors retry

Should definitely not be related to this...

**Pull request merged**
