### PR TITLE
[breaking batch] don't glob export ast::UnOp variants

### PR DESCRIPTION
**Pull request by oli-obk**
r? @Manishearth 

I just noticed they can't be rolled up (often modifying the same line(s) in imports). So once I reach the critical amount for them to be merged I'll create a PR that merges all of them.

### CODE REVIEW

**Comment by Manishearth** [comment]
Feel free to just make a single PR which you keep adding commits to to avoid needing a rebase

**Comment by Manishearth** [comment]
r+

**Comment by bluss** [comment]
Fyi the marker is exactly `[breaking-change]` with the hyphen. As used by http://bitrust.octarineparrot.com/.

**Comment by oli-obk** [comment]
ok, this is ready, I'm done for this run. Before the rebase + squash it passed locally. Let's see what travis says. The only potentially controversial changes are in libsyntax/ast.rs, everything else is just fallout due to the renamings or removal of glob exports.

**Comment by oli-obk** [comment]
jup travis likes it :)

**Comment by Manishearth** [comment]
Reviewed most of it, have marked places where I'm unsure of something.

**Comment by oli-obk** [comment]
addressed comments

**Comment by oli-obk** [comment]
the PR already bitrotted (see travis). rebasing...

**Comment by Manishearth** [comment]
@bors r+ p=5


@erickt @sfackler @llogiq heads up, major breaking change to libsyntax

**Comment by petrochenkov** [comment]
The result looks pretty bad for `Expr_`, `Item_`, `Ty_` and other `Foo_`s renamed too `FooKind`.
AFAIR, the last time someone tried to do this renaming, the idea was rejected and now it has slipped through without much notice.

**Comment by oli-obk** [comment]
it was decided to use `*Kind`: https://github.com/rust-lang/rust/pull/29766#issuecomment-156059150

**Comment by llogiq** [comment]
@petrochenkov I don't think it's too ugly, but I guess that's a matter of taste.

**Comment by petrochenkov** [comment]
Well, ok. I guess.
Also, @Manishearth when does the "breakage window" close? I wanted to do some refactoring is AST and to group it together with these changes to reduce breakage.

**Comment by Manishearth** [comment]
@petrochenkov In the past we didn't have a concrete policy on breakages.

Try to make a PR before this makes the nightly, basically. The window is flexible, though.

**Comment by Manishearth** [comment]
Also, if someone wants to do the same reexport change to the HIR it would be nice. Don't worry about breakages there, since only clippy and some other lints depend upon the HIR and we can take care of that.

**Comment by Manishearth** [comment]
> now it has slipped through without much notice.

btw, regarding this, there wasn't much discussion on this PR, but people affected by breaking changes were pinged a couple of days ago on the older version of this PR (which was split up).

Usually I'd wait a few days so that further breaking changes can be collected; however this itself is a large collection of breakages and is large enough that it will bitrot almost every few hours.

Usually, if you feel the need to make a breaking change, make a PR, get reviewed (without the r+), and when we have enough of them around we can roll them up.

**Comment by llogiq** [comment]
@oli-obk perhaps you can say something about https://internals.rust-lang.org/t/nightly-broke-quote-tokens-1i32/3174/2 ?

**Comment by sgrif** [comment]
Is there some reasoning for this change? While I understand that we don't want libsyntax to be defacto stable, this seems like really unnecessary breakage that affects basically every crate doing anything with macros.

> but people affected by breaking changes were pinged a couple of days ago on the older version of this PR (which was split up).

Nobody on the Diesel team was pinged. :\

**Comment by Manishearth** [comment]
@sgrif Ah, sorry. I didn't know that Diesel uses syntax extensions a lot. The main breakage I was worried about was serde/aster (which is used by half the ecosystem).

I'll ping y'all next time this happens, and keep a tracking issue where we can coordinate future libsyntax breaking changes.

**Pull request merged**
