### PR TITLE
Use backticks instead of single quotes for library feature names in diagnostics

### PR DESCRIPTION
**Pull request by dianne**
This PR changes the text of library feature errors for using unstable or body-unstable items. Displaying library feature names in backticks is consistent with other diagnostics (e.g. those from `rustc_passes`) and with the `reason`s on unstable attributes in the library. Additionally, this simplifies diagnostics when supporting multiple unstable attributes on items (see #131824) since `DiagSymbolList` also displays symbols using backticks.

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
this is a somewhat churny change, but i also agree with it, so whatever 😅

**Comment by compiler-errors** [comment]
r? compiler-errors @bors r+ rollup

**Comment by matthiaskrgr** [comment]
@bors r- 
https://github.com/rust-lang/rust/pull/132554#issuecomment-2453385919

**Comment by dianne** [comment]
@rustbot ready

I think the 2nd commit should fix that merge failure, but let me know if there's a better way to get `--stage 1` ui-fulldeps to pass.

**Pull request merged**
