### PR TITLE
Break dependencies between `syntax_ext` and other crates

### PR DESCRIPTION
**Pull request by petrochenkov**
Move `source_util` macros into `syntax_ext`.
Move other early code generation facilities like standard library injection into `syntax_ext`.

The only crate that depends on `syntax_ext` now is `rustc_interface` which is one of the "final" crates that depend on everything.

Minor: Cleanup dependencies of `rustc_driver`, many of them are no longer used after introduction of `rustc_interface`.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
> without either moving the whole proc macro server into libsyntax

IMO that's where it should go, I probably should've put it there myself.
Can we rename `syntax_ext` to `rustc_builtin_macros` or something?

**Review by eddyb — APPROVED** [review]
cc @Zoxc but LGTM

**Comment by petrochenkov** [comment]
@bors r-
(I'll move the proc macro server.)

**Review by eddyb — APPROVED** [review]

**Comment by petrochenkov** [comment]
Updated.
`syntax_ext` is no longer tied to `rustc_metadata` (proc macro server is in libsyntax now) and more code is moved into `syntax_ext`.

**Review by eddyb — APPROVED** [review]
r=me

**Comment by Mark-Simulacrum** [comment]
@bors p=1

This moves things around, which makes rebasing somewhat painful, and touches Cargo.lock that it warrants a bit of a priority bump.

**Pull request merged**
