### PR TITLE
Support run-fail ui tests

### PR DESCRIPTION
**Pull request by tmandry**
Needed for the test in #64158 for panic=abort tests.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me though I'd personally want to see a test verifying the functionality, but if it's going to be used shortly in a separate PR then that's fine too

**Comment by JohnCSimon** [comment]
Ping from triage:
This has sat idle for over a week,
@tmandry can you add the test @Mark-Simulacrum is asking for?
Thank you!

**Comment by tmandry** [comment]
I'm trying to be lazy and merge this as part of #64158, which relies on the functionality in the test, since @Mark-Simulacrum said that was fine.

In part this is because I haven't seen any examples of explicit tests for compiletest functionality (I'm not sure how to "test for failure"), but if someone could point me to an example I'd be happy to add an additional test.

**Comment by Mark-Simulacrum** [comment]
Yes, I don't think there's a better way to test this other than just a functionality-dependent test. I think it's fine for this to be merged as part of that.

```rust
fn main() {
    panic!("We indeed fail");
}
```

**Comment by tmandry** [comment]
Rebased and merged as part of #64158.

**Pull request closed without merging**
