### PR TITLE
debuginfo: Revert to old/more verbose behavior for -Cdebuginfo=1

### PR DESCRIPTION
**Pull request by michaelwoerister**
https://github.com/rust-lang/rust/commit/cff075009 made LLVM emit less debuginfo when compiling with "line-tables-only". The change was essentially correct but the reduced amount of debuginfo broke
a number of tools.

This commit reverts the change so we get back the old behavior, until we figure out how to do this properly and give external tools to adapt to the new format.

See https://github.com/rust-lang/rust/issues/60020 for more info.

r? @cuviper 
cc @jrmuizel & @froydnj

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Definitely fixes issues seen over at https://github.com/rust-lang/rust/pull/60852#issuecomment-494453859, so seems like we should land this!

**Comment by alexcrichton** [comment]
@bors: p=1 

since this blocks #60852

**Review by cuviper — APPROVED** [review]

**Comment by michaelwoerister** [comment]
Nominating for backporting to beta.

**Comment by pnkfelix** [comment]
accepted for beta-backport

**Pull request merged**
