### PR TITLE
Clarify interfaction between File::set_len and file cursor

### PR DESCRIPTION
**Pull request by jethrogb**

### CODE REVIEW

**Comment by retep998** [comment]
Has this behavior been verified on both Linux *and* Windows?

**Comment by jethrogb** [comment]
I did look at the documentation of [SetFileInformationByHandle](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365539(v=vs.85).aspx) but it isn't clear about how setting `FileEndOfFileInfo` affects the file position.

**Comment by shepmaster** [comment]
Ping from triage, @bluss!

**Comment by retep998** [comment]
Confirmed with local testing on Windows that changing the length of the file does not update the cursor, even when it causes the cursor to be past the end.

**Comment by pietroalbini** [comment]
Ping from triage! This PR has yet to be reviewed, can someone from @rust-lang/libs do it?

**Comment by kennytm** [comment]
@bors retry #46903. 

52 minutes to compile stage1-rustc, which is ridiculous. 

<details><summary>Timing breakdown</summary>

```
make-prepare                	  76.97
stage0-tidy                 	  91.38
bootstrap                   	  20.30
stage0-rustc                	1783.10
llvm                        	 986.29
stage0-trans-llvm           	 212.96
stage1-std                  	 183.77
stage1-test                 	  46.29
stage1-rustc                	3124.49
stage1-trans-llvm           	 272.56
stage0-compiletest          	 207.94
test/ui                     	 234.20
test/parse-fail             	  11.71
test/run-fail               	  48.28
test/run-pass-valgrind      	   7.56
test/mir-opt                	  48.77
test/codegen                	   7.99
test/codegen-units          	   6.70
test/incremental            	  43.56
test/ui-fulldeps            	 100.09
test/run-pass-fulldeps      	 667.10
test/run-fail-fulldeps      	  10.65
test/compile-fail-fulldeps  	 198.52
test/incremental-fulldeps   	   5.77
stage2-rustdoc              	 392.27
test/rustdoc                	 236.26
test/run-make               	 140.30
stage1-test-term            	  11.54
test/libtest                	  16.37
stage1-test-test            	  21.34
test/libtest                	  25.23
stage1-test-alloc           	 126.45
test/libstd                 	 288.66
```

</details>

<details><summary>/proc/cpuinfo of this build (Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz)</summary>

```
[00:17:58] processor	: 0
[00:17:58] vendor_id	: GenuineIntel
[00:17:58] cpu family	: 6
[00:17:58] model		: 63
[00:17:58] model name	: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
[00:17:58] stepping	: 2
[00:17:58] cpu MHz		: 2397.000
[00:17:58] cache size	: 256 KB
[00:17:58] physical id	: 0
[00:17:58] siblings	: 2
[00:17:58] core id		: 0
[00:17:58] cpu cores	: 2
[00:17:58] apicid		: 0
[00:17:58] initial apicid	: 0
[00:17:58] fpu		: yes
[00:17:58] fpu_exception	: yes
[00:17:58] cpuid level	: 15
[00:17:58] wp		: yes
[00:17:58] flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pni ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase bmi1 avx2 smep bmi2 erms invpcid
[00:17:58] clflush size	: 64
[00:17:58] cache_alignment	: 64
[00:17:58] address sizes	: 44 bits physical, 48 bits virtual
[00:17:58] power management:
[00:17:58] 
[00:17:58] processor	: 1
[00:17:58] vendor_id	: GenuineIntel
[00:17:58] cpu family	: 6
[00:17:58] model		: 63
[00:17:58] model name	: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
[00:17:58] stepping	: 2
[00:17:58] cpu MHz		: 2397.000
[00:17:58] cache size	: 256 KB
[00:17:58] physical id	: 0
[00:17:58] siblings	: 2
[00:17:58] core id		: 1
[00:17:58] cpu cores	: 2
[00:17:58] apicid		: 1
[00:17:58] initial apicid	: 1
[00:17:58] fpu		: yes
[00:17:58] fpu_exception	: yes
[00:17:58] cpuid level	: 15
[00:17:58] wp		: yes
[00:17:58] flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pni ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase bmi1 avx2 smep bmi2 erms invpcid
[00:17:58] clflush size	: 64
[00:17:58] cache_alignment	: 64
[00:17:58] address sizes	: 44 bits physical, 48 bits virtual
[00:17:58] power management:
```

</details>
<details><summary>/proc/cpuinfo of the <a href="https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6650/job/ki5i8u47096g6f0a">previous build</a> (Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz)</summary>

```
[00:13:24] processor	: 0
[00:13:24] vendor_id	: GenuineIntel
[00:13:24] cpu family	: 6
[00:13:24] model		: 63
[00:13:24] model name	: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
[00:13:24] stepping	: 2
[00:13:24] cpu MHz		: 2497.000
[00:13:24] cache size	: 256 KB
[00:13:24] physical id	: 0
[00:13:24] siblings	: 2
[00:13:24] core id		: 0
[00:13:24] cpu cores	: 2
[00:13:24] apicid		: 0
[00:13:24] initial apicid	: 0
[00:13:24] fpu		: yes
[00:13:24] fpu_exception	: yes
[00:13:24] cpuid level	: 15
[00:13:24] wp		: yes
[00:13:24] flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pni ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase bmi1 avx2 smep bmi2 erms invpcid
[00:13:24] clflush size	: 64
[00:13:24] cache_alignment	: 64
[00:13:24] address sizes	: 44 bits physical, 48 bits virtual
[00:13:24] power management:
[00:13:24] 
[00:13:24] processor	: 1
[00:13:24] vendor_id	: GenuineIntel
[00:13:24] cpu family	: 6
[00:13:24] model		: 63
[00:13:24] model name	: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
[00:13:24] stepping	: 2
[00:13:24] cpu MHz		: 2497.000
[00:13:24] cache size	: 256 KB
[00:13:24] physical id	: 0
[00:13:24] siblings	: 2
[00:13:24] core id		: 1
[00:13:24] cpu cores	: 2
[00:13:24] apicid		: 1
[00:13:24] initial apicid	: 1
[00:13:24] fpu		: yes
[00:13:24] fpu_exception	: yes
[00:13:24] cpuid level	: 15
[00:13:24] wp		: yes
[00:13:24] flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pni ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase bmi1 avx2 smep bmi2 erms invpcid
[00:13:24] clflush size	: 64
[00:13:24] cache_alignment	: 64
[00:13:24] address sizes	: 44 bits physical, 48 bits virtual
[00:13:24] power management:
```

</details>
<details><summary>/proc/meminfo of this build (1.8 GiB total)</summary>

```
[00:17:58] MemTotal:        1901592 kB
[00:17:58] MemFree:          848456 kB
[00:17:58] HighTotal:             0 kB
[00:17:58] HighFree:              0 kB
[00:17:58] LowTotal:        1901592 kB
[00:17:58] LowFree:          848456 kB
[00:17:58] SwapTotal:        458752 kB
[00:17:58] SwapFree:         413320 kB
```

</details>
<details><summary>/proc/meminfo of previous build (1.7 GiB total)</summary>

```
[00:13:24] MemTotal:        1764376 kB
[00:13:24] MemFree:          627900 kB
[00:13:24] HighTotal:             0 kB
[00:13:24] HighFree:              0 kB
[00:13:24] LowTotal:        1764376 kB
[00:13:24] LowFree:          627900 kB
[00:13:24] SwapTotal:        458752 kB
[00:13:24] SwapFree:         396692 kB
```

</details>

**Pull request merged**
