### PR TITLE
Miri environ shim

### PR DESCRIPTION
**Pull request by pvdrz**
r? @RalfJung

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Triage: Assigning this back to @christianpoveda because this is still WIP

**Comment by JohnCSimon** [comment]
Triage: @christianpoveda - is this still a draft PR?

**Comment by christianpoveda** [comment]
yes this is still a draft, I'll try to finish it soon :)

**Comment by christianpoveda** [comment]
The new scheme proposed in https://github.com/rust-lang/rust/pull/69408 made this PR unneccesary

**Pull request closed without merging**
