### PR TITLE
Remove the `Box` from `Place::Static`.

### PR DESCRIPTION
**Pull request by nnethercote**
It is unnecessary.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Do we need a perf run for this? Otherwise this looks good to me.

**Comment by oli-obk** [comment]
I think the projection variant is already just as big (two pointer sizes), so this doesn't increase the enum's size

**Comment by nnethercote** [comment]
> I think the projection variant is already just as big (two pointer sizes), so this doesn't increase the enum's size

I disagree. Currently, `Local`'s payload is 32 bits, while `Static`'s is word-sized and `Projection`'s is word-sized. So this change increases `Static`'s to two words.

@Mark-Simulacrum: a perf run would be great, thanks!

**Comment by oli-obk** [comment]
Oh. I overlooked the fact that the projection is boxed. The enum might still get optimized by the layout optimizer. And if not we might be able to trick it into doing so by reordering the two fields of the `Static` struct

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 3cedcd581e804304956ff9ee31992b23390652ba

@nnethercote -- you should be able to also queue perf builds with this invocation and if you send a PR to add yourself to https://github.com/rust-lang/rust-central-station/blob/master/homu.toml.template#L149 you'll be able to run try builds yourself in the future

**Comment by nnethercote** [comment]
Perf results basically are in the noise. Possibly a very small improvement.

**Comment by Mark-Simulacrum** [comment]
Memory use has increased, though: https://perf.rust-lang.org/compare.html?start=704af2d7e1474ba60a0b70a5aa78e29905abb4e1&end=3cedcd581e804304956ff9ee31992b23390652ba&stat=max-rss

**Comment by nnethercote** [comment]
Ok, not worth it due to the memory regressions.

**Comment by eddyb** [comment]
Do we want to just use the `DefId` and get the type from the `tcx`, and probably same for projections?
I'm curious if we'd see a slowdown from that.

**Pull request closed without merging**
