### PR TITLE
Bump to 1.23 and update bootstrap

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates the bootstrap compiler, bumps the version to 1.23, updates
Cargo, updates books, and updates crates.io dependencies

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Some failures, but changes look good to me.

```
std/ops/index.html:67: broken link fragment `#operator-precedence` pointing to `reference/expressions/operator-expr.html`

[01:12:44] core/ops/index.html:67: broken link fragment `#operator-precedence` pointing to `reference/expressions/operator-expr.html`

[01:12:46] reference/print.html:292: broken link fragment `#non_ascii_idents` pointing to `reference/print.html`

[01:12:46] reference/print.html:304: broken link fragment `#non_ascii_idents` pointing to `reference/print.html`

[01:12:46] reference/print.html:1786: broken link fragment `#expresions.html#constant-expressions` pointing to `reference/print.html`

[01:12:46] reference/print.html:3884: broken link fragment `#visibility-and-privacy.html` pointing to `reference/print.html`

[01:12:46] reference/expressions/method-call-expr.html:163: broken link fragment `#visibility-and-privacy.html` pointing to `reference/expressions/method-call-expr.html`

[01:12:46] reference/identifiers.html:153: broken link fragment `#non_ascii_idents` pointing to `reference/identifiers.html`

[01:12:46] reference/identifiers.html:165: broken link fragment `#non_ascii_idents` pointing to `reference/identifiers.html`

[01:12:46] reference/expressions.html:193: broken link fragment `#path-expressions` pointing to `reference/expressions.html`

[01:12:46] reference/items/static-items.html:161: broken link fragment `#expresions.html#constant-expressions` pointing to `reference/items/static-items.html`

[01:12:48] thread 'main' panicked at 'found some broken links', /checkout/src/tools/linkchecker/main.rs:49:8
```

**Comment by kennytm** [comment]
@bors r-

Cannot build clippy due to `Cargo.lock` issue.

```
Building stage2 tool clippy-driver (x86_64-unknown-linux-gnu)
[00:36:22] error: the lock file needs to be updated but --locked was passed to prevent this
[00:36:22] 
[00:36:22] 
[00:36:22] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/clippy/Cargo.toml"
[00:36:22] expected success, got: exit code: 101
[00:36:22] 
[00:36:22] 
[00:36:22] You can disable the tool in `src/tools/toolstate.toml`
[00:36:22] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:36:22] Build completed unsuccessfully in 0:33:05
[00:36:22] make: *** [all] Error 1
[00:36:22] Makefile:22: recipe for target 'all' failed
```

**Comment by alexcrichton** [comment]
Good lord here we go again...

**Comment by alexcrichton** [comment]
ping @Manishearth @llogiq @mcarton @oli-obk

This PR is currently going to break clippy. I believe the fix should be pretty easy though. Cargo on nightly is rewriting Cargo.lock to remove the `[root]` section, but in our containers and CI we've mounted the repository as read-only which means that we're failing on CI as we rewrite the Cargo.lock. The fix should basically be to just run `cargo build` in the clippy repository and commit the change to the lock file.

**Comment by oli-obk** [comment]
I removed the workspace and the `Cargo.lock` on clippy master: https://github.com/rust-lang-nursery/rust-clippy/pull/2149

**Comment by alexcrichton** [comment]
Ok thanks! I'll delay the update though until after this PR lands to hopefully ensure this doesn't conflict with too much

**Comment by kennytm** [comment]
`x86_64-gnu-incremental`, the new bootstrap compiler ICE'd (#45161) when building `unicode-xid` 🤔 

```
[00:00:52] error: internal compiler error: /checkout/src/librustc/ich/impls_ty.rs:78: TypeIdHasher: unexpected region ReLateBound(DebruijnIndex { depth: 1 }, "BrEnv")
[00:00:52] 
[00:00:52] note: the compiler unexpectedly panicked. this is a bug.
[00:00:52] 
[00:00:52] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:00:52] 
[00:00:52] note: rustc 1.22.0-beta.1 (e694dd37b 2017-10-12) running on x86_64-unknown-linux-gnu
[00:00:52] 
[00:00:52] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
[00:00:52] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:00:52] 
[00:00:52] error: Could not compile `unicode-xid`.
```

**Comment by alexcrichton** [comment]
I've left a comment at https://github.com/rust-lang/rust/pull/45176#issuecomment-337924159 which I think we'll need to backport to fix this as-is. If we don't want to backport we can work around it, but let's see if a backport is ok first.

**Comment by kennytm** [comment]
beta.2 (2017-10-20) is available now.

**Comment by kennytm** [comment]
wut?

```
Dist docs (x86_64-pc-windows-msvc)
Building stage0 std artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
...
    Finished release [optimized] target(s) in 44.64 secs
thread 'main' panicked at 'no output generated for "std.dll" "lib"', src\bootstrap\compile.rs:897:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap dist
```

@bors retry — since it only takes 5 minutes to check if the error is legit, let's retry.

**Comment by kennytm** [comment]
@bors r- retry 

No this PR is not ready yet 😅

**Comment by kennytm** [comment]
Error reproduced locally. The problem is that the unhashed `std.dll.lib` not found inside `build\x86_64-pc-windows-msvc\stage0-std\release\deps` --- it is *moved* (not copied) one level up. I guess rust-lang/cargo#4570 is relevant, but I haven't checked why the problem did not happen in the previous version.

<details><summary>Tree after this PR</summary>

```cmd
E:\rust\rust>tree build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release /f
Folder PATH listing
Volume serial number is 0004-3A75
E:\RUST\RUST\BUILD\X86_64-PC-WINDOWS-MSVC\STAGE0-STD\X86_64-PC-WINDOWS-MSVC\RELEASE
│   .cargo-lock
│   liballoc.rlib
│   liballoc_system.rlib
│   libcollections.rlib
│   libcompiler_builtins.rlib
│   libcore.rlib
│   liblibc.rlib
│   libpanic_abort.rlib
│   libpanic_unwind.rlib
│   librand.rlib
│   libstd.rlib
│   libstd_unicode.rlib
│   libunwind.rlib
│   std.dll
│   std.dll.lib
│
<snip>
├───deps
│       liballoc-8490ab2df56c3c86.rlib
│       liballoc_system-2c84c9094647cd8f.rlib
│       libcollections-7ab0c32d58e65002.rlib
│       libcompiler_builtins-c37dfe420a20df58.rlib
│       libcore-7d1a88f4f376d9a2.rlib
│       liblibc-5c6f934303254eea.rlib
│       libpanic_abort-c7028058eff8fc81.rlib
│       libpanic_unwind-7efdc8d3a0dbc79f.rlib
│       librand-bcffd6de6bf76148.rlib
│       libstd-8438184fb5808c19.rlib
│       libstd_unicode-08c362a5bf679dc4.rlib
│       libunwind-a70ebc948488ee43.rlib
│       std-8438184fb5808c19.dll
│       std-8438184fb5808c19.dll.exp
│       std-8438184fb5808c19.dll.lib
│       std-8438184fb5808c19.pdb
│
├───examples
├───incremental
└───native

E:\rust\rust>
```

</details>

**Comment by alexcrichton** [comment]
Thanks so much for helping out here @kennytm! I've had a surprising lack of itme to push on this recently :(

**Comment by shepmaster** [comment]
> I've had a surprising lack of itme to push on this recently :(


A surprising lack of itme

**Comment by kennytm** [comment]
`dist-check` failed. Fuchsia provided some more new BSD-3 packages again, legit. 

Needs to update `src/tools/tidy/src/deps.rs`.

```
[00:11:23] invalid license BSD-3-Clause in /checkout/obj/build/tmp/distcheck/src/vendor/fuchsia-zircon/Cargo.toml
[00:11:23] invalid license BSD-3-Clause in /checkout/obj/build/tmp/distcheck/src/vendor/fuchsia-zircon-sys/Cargo.toml
```

**Comment by alexcrichton** [comment]
Sorry forced push by accident before I realized! I think I reverted it back and it should be good to go.

You're of course always more then welcome to help out, thanks so much!

**Comment by kennytm** [comment]
@bors r=Mark-Simulacrum

Looks like our interaction confused bors and the last r= was not registered 🤣. Anyway I've took the chance and removed the `magenta` exceptions as well (matching your changes).

**Pull request merged**
