### PR TITLE
Rename categorization and stop re-exporting its variants.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by arielb1** [comment]
We may want to do some re-categorization as part of the MIR work.

r? @pnkfelix

**Comment by pnkfelix** [comment]
@Ms2ger unfortunately I let this sit in my review queue so long that it has become invalidated.

As a refactoring it seems fine, but @arielb1 is right to wonder if the mem-categorization code may well change with the coming MIR changes...

anyway, it is lgtm as it is.  if @Ms2ger rebases, I can re-review.  Seems relatively harmless either way, up to you.

**Comment by Ms2ger** [comment]
@pnkfelix r?

**Comment by nikomatsakis** [comment]
My expectation is that mem-categorization will largely go away, but I think it's fine to refactor it.

**Pull request merged**
