### PR TITLE
Implement TryFrom<&str> for numerical types, bool and char

### PR DESCRIPTION
**Pull request by grego**
As `TryFrom` is a generic interface for fallible conversion, the standard library types should support it as well.

ACP: https://github.com/rust-lang/libs-team/issues/132 [Accepted]

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Thank you for the implementation!
But since this a change to the public API, you need to create an [API change proposal](https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29) to move this forward.

**Comment by grego** [comment]
Thank you, I created the proposal [here](https://github.com/rust-lang/libs-team/issues/132).

**Review by dtolnay — COMMENTED** [review]
The ACP was not accepted, so I'll go ahead and close this PR.

Thank you anyway for suggesting this API and entertaining our process!

**Pull request closed without merging**
