### PR TITLE
mark internal inplace_iteration traits as hidden

### LINKED ISSUE #85373: Public unstable feature="inplace_iteration" APIs without a tracking issue
The `SourceIter` and `InPlaceIterable` unstable traits are public, so they and their `impl`s show up in docs. For example https://doc.rust-lang.org/1.52.1/std/iter/trait.InPlaceIterable.html. However unlike other unstable public APIs, there is no link to a tracking issue.

These traits were added by @the8472 in https://github.com/rust-lang/rust/pull/70793. It’s not clear from the PR’s description if the traits are intended as private implementation details of the standard library that are only technically `pub` so that they can be used across multiple standard library crates, or if they are intended as a new public API with a possible path to eventual stabilization.

Source definitions of the traits and `impl`s should either have `#[doc(hidden)]` attributes added, or a tracking issue should be filed and the `#[unstable]` attributes modified to point there.

### PR DESCRIPTION
**Pull request by the8472**
resolves #85373

r? @SimonSapin

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks!

Could you confirm that impls are also hidden from docs when the trait has `#[doc(hidden)]`?

**Comment by the8472** [comment]
I have checked `core/iter/struct.Zip.html`, which previously showed those impls. It does not anymore.

**Comment by SimonSapin** [comment]
r+ as far as I’m concerned, but the link checker is complaining

**Comment by the8472** [comment]
Looks like `#[doc(hidden)]` only has an effect within the same crate, not across crates. I have add it to the impls in the `alloc` crate.

**Comment by SimonSapin** [comment]
This sounds like a rustdoc bug worth filing

**Pull request merged**
