### PR TITLE
Update rustc-hash to version 2 but again

### PR DESCRIPTION
**Pull request by Noratrieb**
it's like #129533 but not closed by bors and rebased

r? WaffleLapkin meow

### CODE REVIEW

**Comment by workingjubilee** [comment]
Bors thinks this is queued?
@bors r-

**Comment by workingjubilee** [comment]
rebasededed

**Comment by Noratrieb** [comment]
don't terminate my batch job D:
@bors retry

**Comment by workingjubilee** [comment]
as this PR has encountered many curses and has already had to be reopened:

@bors p=1

**Comment by pnkfelix** [comment]
* primary improvements to unicode-normalization and libc
* primary regressions to typenum and serde
* i don't think there's anything interesting to investigate here. marking as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
