### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
- Successful merges: #46888, #46894, #46910, #46928, #46930, #46933, #46937, #46939, #46940, #46943
- Failed merges: #46924, #46954

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r-

Travis is failing, investigating.

**Comment by kennytm** [comment]
@bors r+

Removed #46924

**Comment by alexcrichton** [comment]
@kennytm FWIW I've confirmed that failure is due to https://github.com/rust-lang/rust/pull/46910

**Pull request closed without merging**
