### PR TITLE
Add `is_callable` to `rustc_middle::ty::Ty`

### PR DESCRIPTION
**Pull request by robinmoussu**
I'm not sure that I didn't forgot other cases, please double check. Also, do I need to add a unit test somewhere (I'm a new rustc contributor)?

### CODE REVIEW

**Review by davidtwco — CHANGES_REQUESTED** [review]
Thanks for the pull request:

What's the motivation for this PR? It doesn't appear to resolve any issues, and the function that you're adding isn't used anywhere in this pull request (so it isn't reducing duplication in the compiler, for example). Helper functions like this would typically be added as they were required in pull requests that used them.

As for the implementation, the pull request fails CI because this function is implemented on `TyCtxt`, not `Ty`, so the member functions it invokes doesn't exist. You don't need to worry about unit tests for things like this in rustc.

**Comment by robinmoussu** [comment]
I should effectively have added a bit more context.

I'm working on a tool (not yet release, it doesn't work yet) that extract the dependency between function (both direct, when `foo()` calls `bar()` and indirect through function pointer, traits, …).

```rust
fn main() {
    let fct = bar; // create a reference to bar
    foo(fct); // direct call to foo
}

fn foo<Fct: Fn()>(fct: Fct) {
    fct(); // indirect call to bar, indirection set in `main`
}

fn bar() {}
```

My work is based on a fork of rustdoc, and uses the internal of rustc. At one point in the analysis, I need to test for every constant used in a function if those constant are callable objects, in order to be able to report correctly the places where the indirect calls are set-up. I asked on zulip if `ty.is_fn() || ty.is_fn_ptr() || ty.is_closure()` was enough, and I was [told](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Is.20there.20some.20kind.20of.20.60is_callable(ty.3A.20.26Ty).20-.3E.20bool.60.3F) to add it directly in `Ty`, hence this PR.

**Comment by robinmoussu** [comment]
I should effectively have added a bit more context.

I'm working on a tool (not yet release, it doesn't work yet) that extract the dependency between function (both direct, when `foo()` calls `bar()` and indirect through function pointer, traits, …).

```rust
fn main() {
    let fct = bar; // create a reference to bar
    foo(fct); // direct call to foo
}

fn foo<Fct: Fn()>(fct: Fct) {
    fct(); // indirect call to bar, indirection set in `main`
}

fn bar() {}
```

My work is based on a fork of rustdoc, and uses the internal of rustc. At one point in the analysis, I need to test for every constant used in a function if those constant are callable objects, in order to be able to report correctly the places where the indirect calls are set-up. I asked on zulip if `ty.is_fn() || ty.is_fn_ptr() || ty.is_closure()` was enough, and I was [told](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Is.20there.20some.20kind.20of.20.60is_callable(ty.3A.20.26Ty).20-.3E.20bool.60.3F) to add it directly in `Ty`, hence this PR.

**Comment by davidtwco** [comment]
> I asked on zulip if ty.is_fn() || ty.is_fn_ptr() || ty.is_closure() was enough, and I was told to add it directly in Ty, hence this PR.

That motivation makes sense, but I'm not sure that we normally add functions in the compiler which aren't used by the compiler (or the other tools that are submodules/subtrees in this repository). It might make more sense to just have a free function in your project for this?

**Comment by robinmoussu** [comment]
Sorry, I didn't saw that you commented on this PR (and my bandwidth suddenly reduced a lot :disappointed:)

> It might make more sense to just have a free function in your project for this?

I can totally do it, but if another project needs the same function, he will have to duplicature the code. Personally I don't mind either solution.

**Comment by davidtwco** [comment]
> I can totally do it, but if another project needs the same function, he will have to duplicature the code. Personally I don't mind either solution.

I'm going to close this for now since I don't think we should add a function that isn't used in rustc or by one of the other projects that we test in this repository.

**Pull request closed without merging**
