### PR TITLE
Make `$crate` a keyword

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/42898

r? @jseyfried or @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
LGTM overall. I still don't really think of `$crate` as a keyword though -- instead I consider `macro_rules!` to expand it into the hygienic crate root; I think how we represent this is an implementation detail.

If we're making it a keyword though, could we put it next to its counterpart `CrateRoot`. Putting it with the "real" keywords seems weird to me.

**Comment by petrochenkov** [comment]
>I still don't really think of $crate as a keyword though -- instead I consider macro_rules! to expand it into the hygienic crate root; I think how we represent this is an implementation detail.

That's true, it just needs to "quack like a keyword" (path segment keyword, to be precise), i.e. answer "yes" to questions "is it reserved?" and "can it be used in a path segment?". So, making it a keyword is the simplest solution.

>If we're making it a keyword though, could we put it next to its counterpart CrateRoot.

I suspect `$crate` can be lowered directly into `CrateRoot` with correct hygiene, but I can't check right now.
Or maybe both can be replaced with `keywords::Invalid` which is usually used for other things similar to crate root (elided lifetimes, unnamed parameters, etc), but that's the opposite to what I'd like to see, I'd rather replace the remaining uses of `keywords::Invalid` with more specialized "reserved identifier placeholders" instead.

(I'll return to this PR in a few days.)

**Comment by jseyfried** [comment]
> So, making it a keyword is the simplest solution.

Makes sense.

> more specialized "reserved identifier placeholders" instead [of `keywords::Invalid`]

Agreed, I was just saying we should declare the reserved identifier placeholders next to each other, not interspersed with the traditional keywords (or we could also separate/refactor out "reserved identifier placeholders" further).

**Comment by petrochenkov** [comment]
@jseyfried
>Agreed, I was just saying we should declare the reserved identifier placeholders next to each other, not interspersed with the traditional keywords (or we could also separate/refactor out "reserved identifier placeholders" further).

Updated.

**Comment by jseyfried** [comment]
Thanks! @bors r+

**Pull request merged**
