### PR TITLE
Removed usage of `drop` from `std::net::UdpSocket` docs

### LINKED ISSUE #30507: Probably misleading example for std::net::UdpSocket in docs
In the example for [std::net::UdpSocket](https://doc.rust-lang.org/nightly/std/net/struct.UdpSocket.html) `drop` is used:
```rust
drop(socket); // close the socket
```
This is redundant and might mislead users that they're supposed to explicitly `drop` the socket. I think this should be removed.

cc @steveklabnik ?

### PR DESCRIPTION
**Pull request by defyrlt**
Resolves #30507

r? @steveklabnik

### CODE REVIEW

**Comment by tomjakubowski** [comment]
Might be worth noting that the socket will be dropped and closed automatically when it goes out of scope.

**Comment by defyrlt** [comment]
Good point. I'll add it.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

Thanks so much!

**Comment by defyrlt** [comment]
Glad to help :)

**Pull request merged**
