### PR TITLE
rustfmt liblibc

### PR DESCRIPTION
**Pull request by mseri**
r? @nrc

Nothing special going on, the only real notable change is the explicit ABI on line 6183. 
I re-onlined some extern on top of the file by hand.

### CODE REVIEW

**Comment by nrc** [comment]
Some of the empty function bodies should remain on one line. I filed https://github.com/nrc/rustfmt/issues/463. I don't think it needs fixing up.

**Comment by nrc** [comment]
Could you remove the `#[rustfmt_skip]`s from the fixup please? I think we will fix rustfmt soon and then they won't be necessary.

**Comment by nrc** [comment]
https://github.com/nrc/rustfmt/issues/465

From line 2962, I guess you could fix that up or leave it till we fix rustfmt.

**Comment by nrc** [comment]
At line 5907 - https://github.com/nrc/rustfmt/issues/466 - this does need a fixup, I think.

**Comment by nrc** [comment]
There's a few instances of that, actually.

**Comment by nrc** [comment]
There's a lot of those, probably not worth trying to fixup manually, we should block on fixing https://github.com/nrc/rustfmt/issues/466

**Comment by mseri** [comment]
I thought that the functions alignments where meant to be like that after seeing few of them. I'll fix those and the misaligned SYNCHRONIZED and push the update soon.

**Comment by mseri** [comment]
Ok. Then I won't touch it anymore and will wait for the fix. I may try to help but I don't know rust and rustfmt internals enough (yet)

**Comment by nrc** [comment]
@mseri if you'd like to try and fix the rustfmt bug, it shouldn't be too hard (although not the easiest), I'm happy to mentor over on the rustfmt repo. You don't need to know anything about rust's internals.

**Comment by mseri** [comment]
Thanks, I will look into it as soon as I get some free time.

**Comment by mseri** [comment]
Is it possible to track down why rustfmt failed to reformat the long lines in commit d368102 ?

**Comment by nrc** [comment]
@mseri it's because they are in an `extern` block. I think that is fixed now.

**Comment by mseri** [comment]
It is fixed indeed, with rustfmt commit `d326a29`. However the following one introduced a serious bug (issue nrc/rustfmt#499)

**Comment by mseri** [comment]
It looks like now `rustfmt` is doing a pretty great job here.

**Comment by nrc** [comment]
@mseri could you squash your commits please? It will give better history, but also I can't easily review this on GitHub.

**Comment by mseri** [comment]
@nrc history cleaned

**Comment by nrc** [comment]
@mseri thanks for sticking with this one, looks good now.

@bors: r+

**Pull request merged**
