### PR TITLE
Fix search sidebar width when no crate select is present

### LINKED ISSUE #60480: Search bar should take all width when no select is alongside (when just one crate is documented)
A good screenshot:

Screenshot 2019-05-02 at 21 57 35

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #60480.

I also fixed the box-shadow that seemed to have been kind of removed?

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Can you add a screenshot with your changes?

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/rustdoc in case i drop this review

**Comment by GuillaumeGomez** [comment]
Sure!

Screenshot from 2019-05-03 10-17-09

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
meh

@bors: r+

**Pull request merged**
