### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #41826, #41919, #41946, #41967, #41969
- Failed merges: #41939

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Spurious? I think? No errors... Odd.

@bors retry force

```
[00:21:11]    Compiling syntax_pos v0.0.0 (file:///C:/projects/rust/src/libsyntax_pos)
[00:21:14]    Compiling rustc_errors v0.0.0 (file:///C:/projects/rust/src/librustc_errors)
[00:21:19]    Compiling rustc_data_structures v0.0.0 (file:///C:/projects/rust/src/librustc_data_structures)
[00:21:22]    Compiling rustc-serialize v0.3.23
[00:21:31]    Compiling syntax v0.0.0 (file:///C:/projects/rust/src/libsyntax)
[00:21:32]    Compiling rls-span v0.4.0
[00:21:33]    Compiling rls-data v0.3.1
[00:24:54]    Compiling proc_macro v0.0.0 (file:///C:/projects/rust/src/libproc_macro)
[00:24:54]    Compiling rustc_const_math v0.0.0 (file:///C:/projects/rust/src/librustc_const_math)
[00:24:56]    Compiling rustc_back v0.0.0 (file:///C:/projects/rust/src/librustc_back)
[00:24:56]    Compiling syntax_ext v0.0.0 (file:///C:/projects/rust/src/libsyntax_ext)
[00:25:17]    Compiling rustc v0.0.0 (file:///C:/projects/rust/src/librustc)
[00:29:19] error: Could not compile `rustc`.
[00:29:19]
[00:29:19] To learn more, run the command again with --verbose.
[00:29:19]
[00:29:19]
[00:29:19] command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "build" "-j" "2" "--target" "x86_64-pc-windows-msvc" "--release" "--locked" "--features" "" "--manifest-path" "C:\\projects\\rust\\src/rustc/Cargo.toml"
[00:29:19] expected success, got: exit code: 101
```

**Comment by Mark-Simulacrum** [comment]
@bors retry

I have no clue how this syntax really works...

**Comment by frewsxcv** [comment]
@Mark-Simulacrum probably https://github.com/rust-lang/rust/pull/41967 ?

**Comment by Mark-Simulacrum** [comment]
Maybe, but that looks like it is only MSVC related.

**Pull request closed without merging**
