### PR TITLE
Bump rustfmt and rls

### LINKED ISSUE #71076: `rls` no longer builds after rust-lang/rust#71059
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#71059, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @Dylan-DPC, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### LINKED ISSUE #71077: `rustfmt` no longer builds after rust-lang/rust#71059
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#71059, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @Dylan-DPC, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by topecongiro**
Close #71076. Close #71077.

r? @Xanewok

### CODE REVIEW

**Comment by ehuss** [comment]
It looks like maybe you ran `cargo update`?  When updating, you should only update the specific packages that are needed (like `cargo update -p rustfmt-nightly -p rls`).

**Comment by topecongiro** [comment]
@ehuss Thanks, I have removed unnecessary diffs from Cargo.lock.

**Review by Xanewok — APPROVED** [review]

**Pull request merged**
