### PR TITLE
Enable inserting sideeffect by default

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This makes the -Zinsert-sideeffect be enabled by default, and can be disabled
with -Zinsert-sideeffect=no.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/rust/issues/28728 https://github.com/rust-lang/blog.rust-lang.org/pull/494

**Comment by nikic** [comment]
I remember this having a devastating impact on compile-times, at least in the initial implementation. Is that no longer the case?

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

I knew I was forgetting something :)

I am not aware of such a hit on compile times, but you could be right! We were not aware of such a roadblock in the compiler team meeting which spawned this.

**Comment by Mark-Simulacrum** [comment]
It does look like this is still a pretty big performance regression. I will try to dig in a bit and see if there's something we can do to minimize the regression; I have not looked at the current implementation to see how hard that would be.

**Comment by nikic** [comment]
Here's the output for one of the failing codegen tests: https://gist.github.com/nikic/7e521def71d106c345a255e464b18d3f

I can ... kind of see where the compile-time increase comes from ;)

There's clearly an opportunity here for LLVM to coalesce redundant sideffect intrinsics, but rust probably shouldn't be generating so many in the first place either. In particular sideffect on function entry is only needed for potentially recursive functions. Or could possibly be just disabled entirely, as it seems like a much less important case than infinite loops.

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

I've removed the function entry side-effect intrinsics.

I agree that this likely gets us most of the benefits (though not resolving 100% of the cases). If this doesn't bring compile times down enough, my next idea is to land a change that only adds side effect calls if we're unconditionally looping (according to rustc). That would make `loop {}` compile correctly, but more complex cases perhaps not (if LLVM notices unconditional recursion where we don't). I imagine that 95% (maybe even 100%, to be honest) of cases where this occurs in practice is literally `loop {}` so if we make that work.

**Comment by nikomatsakis** [comment]
The cases where I've been bitting by this are functions that (accidentally) recurse infinitely without a base case. (Though the lint that detects such cases now seems to catch most such bugs for me.)

**Comment by Mark-Simulacrum** [comment]
> The cases where I've been bitting by this are functions that (accidentally) recurse infinitely without a base case. (Though the lint that detects such cases now seems to catch most such bugs for me.)

Interesting, that's unexpected to me. The new results are certainly much better -- 3-7% losses -- so that suggests that we could "solve" the function-local part of this relatively easily. Cross-function, a couple of mitigation strategies that I hope to try are:
 * Emit the side effect intrinsic only in functions which could plausibly loop
    * we see a virtual call somewhere inside them, or the recursion lint has noted possible recursion (we do not lint on such possible recursion, because that would be a "anti recursion" lint)
 * Emit only if function has call terminators (poor approximation of the previous)
 * I imagine there's other strategies we might explore, e.g. around reusing the monormophization collectors "graph"

**Comment by rkruppe** [comment]
I'm skeptical about trying hard to emit fewer of these intrinsics. Locally checking that there are no calls at all is unlikely to help much at all (especially without MIR inlining enabled), and taking whole call graphs into account seems quite expensive (and hard to make properly incremental, even if you can isolate codegen itself from spurious changes with a sufficiently targeted query) for what *should* be a very minor gain on most code.

We can of course experiment endlessly on the rustc side but I think we're quickly approaching the point where the case can be made that `llvm.sideeffect` is not a good enough solution and the other proposal from past discussions (making forward-progress opt-in via an attribute instead of the default that has to be worked around) is worth pursuing.

**Comment by Mark-Simulacrum** [comment]
It was my perspective that we considered the LLVM forward-progress not really feasible to do on our end (i.e., it is not even agreed among LLVM developers that they would accept such a feature).

I think I disagree that sideeffect is completely not viable -- I think we do have to accept that we will not catch 100% of cases with it, but I do think it may be worth making sure that the trivial `loop {}` construct does not miscompile on Rust, as doing so (AFAICT) should be relatively simple, as well as hopefully essentially free from a compilation time perspective -- the MIR for `loop {}` with an empty body should be easy to detect, I think.

It has been my interpretation that while there is a broader issue here about our language not having a guarantee that LLVM believes it has, in the case where you *want* this behavior (i.e. it is not a bug in the code), it is usually because you have a literal `loop {}` in your code. Maybe that impression is wrong, and then this idea doesn't make much sense in the entirety.

**Comment by rkruppe** [comment]
Emitting `llvm.sideeffect` only for `loop {}` might very well be a worthwhile and practical mitigation, but we need to fully close this soundness hole eventually. I know very well that proposing deeper changes to LLVM (and then implementing them, if they're accepted) is far from trivial, and it absolutely should not block improving the situation on it. But unless we can merge a complete bug fix without ruining our compile times, we'll still have an open bug that we apparently can't close without something happening on the LLVM side.

**Comment by Mark-Simulacrum** [comment]
Yes, I agree.

I do think that the situation is not *that* hopeless with sideeffect as it exists today (in particular, the current patch set with strictly function-local side effects performs not horribly). I do think that the global analysis necessary to minimally emit side effects on functions is not possible (given time and implementation constraints), but getting closer to the minimum rather than *every* function should be feasible.

(Notably, I *believe* it is already true that we walk the function call graph at least once, so this would only need to collect more information than that does, but not fundamentally do more work).

**Comment by nikomatsakis** [comment]
It's interesting how completely we overlooked the perf results when discussing this in the past :) I'm beginning to wonder if indeed we *should* have some kind of discussion or meeting!

**Comment by Mark-Simulacrum** [comment]
Yes, I think so. I'm going to go ahead and close this pull request -- I think we shouldn't make any change exactly like it does today, with the intention to:

 * Schedule a design discussion for T-compiler, as to what we can do here -- e.g., should we try to optimize where we emit side effects?
 * Land a more minimal patch that always emits side-effect calls on codegen for `loop {}` or equivalents (i.e., unconditional branches into predecessor blocks); this would not be gated on -Zinsert-sideeffect, but would also hopefully not really regress any code in the wild.

**Pull request closed without merging**
