### PR TITLE
update Miri

### LINKED ISSUE #74580: `miri` no longer builds after rust-lang/rust#69749
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#69749, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @davidtwco, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/74580
Cc @rust-lang/miri r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
Tools PR CI failed.
@bors retry r-

**Comment by RalfJung** [comment]
I have no idea what this test failure is about:
```
2020-07-29T20:34:20.6114553Z failures:
2020-07-29T20:34:20.6114835Z 
2020-07-29T20:34:20.6118059Z ---- build::close_output stdout ----
2020-07-29T20:34:20.6123835Z thread 'build::close_output' panicked at 'assertion failed: !status.success()', src/tools/cargo/tests/testsuite/build.rs:5016:9
2020-07-29T20:34:20.6124329Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2020-07-29T20:34:20.6124435Z 
2020-07-29T20:34:20.6124690Z 
2020-07-29T20:34:20.6125074Z failures:
2020-07-29T20:34:20.6126826Z     build::close_output
```
@Mark-Simulacrum any idea?

I cannot see Miri tests even being run in this PR, so let's hope this is spurious.
@bors retry

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/cargo/issues/8564 @ehuss 

Indeed spurious.

**Comment by RalfJung** [comment]
@bors r-
A miri-breaking change landed in the mean time

**Pull request merged**
