### PR TITLE
Return values larger than 2 registers using a return area pointer

### PR DESCRIPTION
**Pull request by bjorn3**
LLVM and Cranelift disagree about how to return values that don't fit in the registers designated for return values. LLVM will force the entire return value to be passed by return area pointer, while Cranelift will look at each IR level return value independently and decide to pass it in a register or not, which would result in the return value being passed partially in registers and partially through a return area pointer.

While Cranelift may need to be fixed as the LLVM behavior is generally more correct with respect to the surface language, forcing this behavior in rustc itself makes it easier for other backends to conform to the Rust ABI and for the C ABI rustc already handles this behavior anyway.

In addition LLVM's decision to pass the return value in registers or using a return area pointer depends on how exactly the return type is lowered to an LLVM IR type. For example `Option<u128>` can be lowered as `{ i128, i128 }` in which case the x86_64 backend would use a return area pointer, or it could be passed as `{ i32, i128 }` in which case the x86_64 backend would pass it in registers by taking advantage of an LLVM ABI extension that allows using 3 registers for the x86_64 sysv call conv rather than the officially specified 2 registers.

This adjustment is only necessary for the Rust ABI as for other ABI's the calling convention implementations in rustc_target already ensure any return value which doesn't fit in the available amount of return registers is passed in the right way for the current target.

Helps with https://github.com/rust-lang/rustc_codegen_cranelift/issues/1525
cc https://github.com/bytecodealliance/wasmtime/issues/9250

### CODE REVIEW

**Comment by jieyouxu** [comment]
I have no clue about this... r? compiler

**Review by Noratrieb — APPROVED** [review]
the logic seems sound, though I will leave it open for a bit in case someone else has input because I don't feel 100% confident on this (and you still have to do some FileChecking, good luck on that)

This shouldn't cause any problems as it checks the size, and if two types have different sizes they're obviously not ABI-compatible anyways.
This seems like it could be a performance pessimization in some cases, but it seems unlikely to actually affect anything. I think rustc uses u128 a bunch, and probably sometimes in `Option<T>`, so if you think that it could have effects you could do a perf run I guess.

**Comment by bjorn3** [comment]
A perf run can't hurt.

@bors try @rust-timer queue

**Comment by workingjubilee** [comment]
fwiw LLVM often looks at an i128, sees that the intermediate computation will not exceed 64 bits for `$REASONS`, and then folds it into a 64-bit computation, in an actual optimized code section. this has been true since a long time ago. not that we shouldn't check the perf, obviously.

**Comment by petrochenkov** [comment]
r? compiler
cc @nikic maybe

**Review by nikic — COMMENTED** [review]
This looks generally reasonable to me. It's always better to specify the correct ABI on the Rust side rather than make LLVM lower it. Apart from the benefit to Cranelift, this may also enable more optimization in LLVM, e.g. by allowing copies to be optimized away (because they are now explicit, not implicit).

My only question here is whether it would make sense to try and preserve the behavior you mention where we pass the result in up to three registers rather than two? Or does Cranelift not support that variant?

**Comment by bjorn3** [comment]
> My only question here is whether it would make sense to try and preserve the behavior you mention where we pass the result in up to three registers rather than two? Or does Cranelift not support that variant?

LLVM only supports this on some architectures afaik and conditionally doing this depending on the architecture is harder than never doing it at all. In any case Cranelift only supports it on x86_64. Also due to the interaction of PassMode::Pair with padding, it depends on the exact way rust types are lowered to llvm types if some types would be considered 3 or 4 registers big. The LLVM and Cranelift backends currently disagree about this for some types including the aformentioned `Option<u128>`. The LLVM backend lowers it as `{ i32, i128 }` without padding which fits in 3 registers, while the Cranelift backend takes the total type size including padding (32 bytes) which requires 4 registers.

**Comment by bjorn3** [comment]
Fixed tests on 32bit targets.

**Review by jieyouxu — APPROVED** [review]
AFAICT the test changes look reasonable. You can r= nikic and me after PR CI is green.

**Comment by bjorn3** [comment]
An assembly test needed to be updated as LLVM decided to reorder an argument load instruction.

@bors r=nikic,jieyouxu

**Pull request merged**
