### PR TITLE
Rustdoc - Specify max-image size

### LINKED ISSUE #24861: Rustdoc should specify maximum image size
I just saw http://huonw.github.io/cogset/cogset/, a rustdoc page with an image. On small screens, the image doesn't resize and is just cut off.

I know images are probably quite rare in documentation, but adding `img {max-width: 100%}` to the rustdoc main css file is a trivial thing.

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #24861

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Actually, I'm not really qualified to review this, given how very little I know of CSS :)

r? @steveklabnik

**Comment by steveklabnik** [comment]
Seems reasonable to me. @bors: r+ rollup

**Pull request merged**
