### PR TITLE
Add attributes for trait and methods as well

### LINKED ISSUE #48485: [Rustdoc] Show #[must_use] on functions
As it's important information about the function, Rustdoc should show that the result of the function must be used.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #48485.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Here are the screenshots:

screen shot 2018-06-01 at 15 49 30
screen shot 2018-06-01 at 15 49 33

**Comment by QuietMisdreavus** [comment]
Looks good to me, thanks!

@bors r+

**Comment by GuillaumeGomez** [comment]
I suppose there is no merge conflicts so let's just retry...

@bors: r=QuietMisdreavus

**Comment by GuillaumeGomez** [comment]
Rebased, no conflict. This is making me sad...

@bors: r=QuietMisdreavus

**Pull request merged**
