### PR TITLE
trans her gender

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
CC https://github.com/rust-lang/team/pull/1511

r? @Noratrieb

### CODE REVIEW

**Comment by Noratrieb** [comment]
alona this branch name will go horribly wrong

**Comment by Noratrieb** [comment]
GitHub PRs break for mysterious reasons for just emoji branch names so please add some random letter at the start :3

**Comment by aDotInTheVoid** [comment]
Closed in favor of #128293

**Comment by Noratrieb** [comment]
wow I can't believe you closed my transition like that

**Comment by aDotInTheVoid** [comment]
has cancel culture gone too far?

**Comment by Noratrieb** [comment]
the woke mind virus has reached rust-lang/rust :/

**Comment by aDotInTheVoid** [comment]
This isn't true, rust become woke with the addaption of [RFC 2592](https://rust-lang.github.io/rfcs/2592-futures.html#waking-up)

**Comment by Noratrieb** [comment]
Screenshot_20240728-015644

**Comment by Noratrieb** [comment]
wow

**Pull request closed without merging**
