### PR TITLE
FIX String struct Doc comments for better rendering inside of IDEs

### PR DESCRIPTION
**Pull request by troglodytto**
Previously, the rendering of the documentation for this particular part of code looked like this:

Notice the rendering of **code blocks** after the "FIXME" Comment

Screenshot from 2023-09-27 13-52-48

---

Now it looks like this:

Screenshot from 2023-09-27 13-53-22

### CODE REVIEW

**Comment by troglodytto** [comment]
@m-ou-se Any updates on this?

**Comment by mohe2015** [comment]
> @m-ou-se Any updates on this?

Two hours is definitely not enough time to wait before asking for updates. People sleep, have other things to do, have a backlog of issues/PRs they need to check, work on something else currently and don't want to be interrupted, etc.

**Review by dtolnay — CHANGES_REQUESTED** [review]
I believe this is intentional as currently written. The FIXME comment is targeted to the standard library maintainer, not to the standard library user reading String's rustdoc. Your PR changes it to get shown to the reader of the rustdoc, which is not the intended audience for this comment.

**Comment by troglodytto** [comment]
@dtolnay @m-ou-se Updated the PR

Now the rendered content looks like this

image

**Comment by troglodytto** [comment]
Any updates on this @dtolnay @m-ou-se

**Review by dtolnay — COMMENTED** [review]
I think this code is all right as currently written.

The first screenshot in https://github.com/rust-lang/rust/pull/116192#issue-1914983604 is a bug in whatever application that screenshot is from. Could you look into reporting that in the appropriate place?

Thanks anyway for the PR!

**Pull request closed without merging**
