### PR TITLE
Use clang 12.0.1 on dist-x86_64/i686-linux

### PR DESCRIPTION
**Pull request by nikic**
The LLD + ThinLTO __morestack bug has been fixed in 12.0.1, so
we can now update our clang version. This also means that we no
longer need to build Python 2.

### CODE REVIEW

**Comment by nikic** [comment]
@bors try

Turns out we also need a slightly newer binutils to handle R_X86_64_REX_GOTPCRELX relocations. I've also taken the liberty of replacing hardcoded `make -j10` with `make -j$(nproc)` to make this more amenable to machines with high core count, not sure if there was some reason this particular number was used.

**Comment by Mark-Simulacrum** [comment]
r=me when ready

**Pull request merged**
