### PR TITLE
Remove `#[macro_escape]`.

### PR DESCRIPTION
**Pull request by jseyfried**
Remove `#[macro_escape]`, which was deprecated at the end of 2014 (c.f 5bf385be6a5ce267ac7cd9d1725178488e33131c).
`#[macro_escape]` is allowed with a deprecation warning on stable, so this is a [breaking-change].
r? @eddyb

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @petrochenkov

**Comment by eddyb** [comment]
LGTM. @rust-lang/compiler, looks like this should've been removed before 1.0 - can we do that now?

**Comment by nrc** [comment]
+1

**Comment by alexcrichton** [comment]
ping r? @eddyb, perhaps this should be nominated for a compiler team discussion?

**Comment by nikomatsakis** [comment]
This is really a @rust-lang/compiler team problem.

Wearing my compiler hat, I propose that we do a quick crater run to see if anyone is affected and remove it. Basically the normal bug fix protocol. At worst, we can have a warning period, but this seems like one of those cases where it's probably not needed.

**Comment by nikomatsakis** [comment]
We can actually skip crater and just (rip)grep the sources of crates.io I guess, even easier.

**Comment by brson** [comment]
This looks like it removes all tests around `#[macro_escape]`. Can it instead add a test that captures what _does_ happen when you mention macro_escape? Is it an error?

**Comment by brson** [comment]
[Here's rg over the most recent versions of all crates on crates.io](https://gist.github.com/brson/9061f8a80974c5817b4f28c47486b7ca).

**Comment by jseyfried** [comment]
@brson Currently, `#[macro_escape]` would have no effect, but I think it should be a `custom_attribute` feature error like other unknown attributes (I'll update and add a test when we want to land).

@nikomatsakis 
> At worst, we can have a warning period

It has been a [deprecation warning](https://play.rust-lang.org/?gist=91ed70d66dd8577c4b3354d2ebbc04ad&version=stable&backtrace=0) since the beginning of 2015.

At least two of the grepped crates (`immutable` and `rust-GSL`) real regressions (many are already broken or have a dead GH repository link). There's very little downside to keeping `#[macro_escape]`, so I'm going to close this PR until there are no regressing crates.

**Pull request closed without merging**
