### PR TITLE
Update to LLVM 12.0.0 final

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by cuviper** [comment]
@nagisa mentioned wanting a few more backports, so we could wait and roll that together here. Let's try in the meantime...

r? @nikic
@bors try

**Comment by nikic** [comment]
@bors r+ rollup=never (just in case, as this pulls in a few more commits than usual)

The only other backport we need that I'm aware of is https://reviews.llvm.org/D99469, and that one hasn't landed upstream yet.

**Comment by nagisa** [comment]
https://reviews.llvm.org/rG1c268a8ff4e90a85d0e634350b1104080614cf2b was one of the backport candidates I had in mind. Looks like it didn't make v12.0.0 so will have to backport it to both nightly and beta.

**Comment by wesleywiser** [comment]
We discussed this in the compiler team triage meeting this morning and decided to approve the backport. I see a beta PR (#84271) has already been opened so I will leave the approval tag on that PR.

**Pull request merged**
