### PR TITLE
save-analysis: signatures for everything!

### PR DESCRIPTION
**Pull request by nrc**

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
Legitimate failure.

```
[00:00:11] error: failed to parse lock file at: /checkout/src/Cargo.lock
```

**Comment by carols10cents** [comment]
[Looks like a legit failure to me?](https://travis-ci.org/rust-lang/rust/jobs/241873814#L5003)

```
[00:58:45] error[E0512]: transmute called with differently sized types: rls_data::Analysis (2176 bits) to data::Analysis (1984 bits)
[00:58:45]    --> /checkout/src/tools/rls/src/build.rs:588:57
[00:58:45]     |
[00:58:45] 588 |                                                         ::std::mem::transmute(a.clone())
[00:58:45]     |                                                         ^^^^^^^^^^^^^^^^^^^^^ transmuting between 2176 bits and 1984 bits
```

**Comment by Nashenas88** [comment]
Crate version mismatch! I've found the [cargo-tree](https://github.com/sfackler/cargo-tree/blob/master/README.md) project very useful for narrowing this one down.

**Pull request merged**
