### PR TITLE
Remove `sip::Hasher::short_write`.

### PR DESCRIPTION
**Pull request by nnethercote**
`sip::Hasher::short_write` is currently unused. It is called by
`sip::Hasher::write_{u8,usize}`, but those methods are also unused,
because `DefaultHasher`, `SipHasher` and `SipHasher13` don't implement
any of the `write_xyz` methods, so all their write operations end up
calling `sip::Hasher::write`.

(I confirmed this by inserting a `panic!` in `sip::Hasher::short_write`
and running the tests -- they all passed.)

The alternative would be to add all the missing `write_xyz` methods.
This does give some significant speed-ups, but it hurts compile times a
little in some cases. See #69152 for details. This commit does the
conservative thing and doesn't change existing behaviour.

r? @rust-lang/libs

### CODE REVIEW

**Comment by nnethercote** [comment]
This should have zero perf impact because it just removes dead code. But I was surprised by the perf impact of #69152 so I will check.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
The performance effect is right on the edge of "noise" and "miniscule improvement", more or less as expected.

**Review by dtolnay — APPROVED** [review]
Regarding https://github.com/rust-lang/rust/pull/69152#issuecomment-591152663, I agree that this is the right tradeoff. Thanks!

**Pull request merged**
