### PR TITLE
Add trait related queries to SMIR's rustc_internal

### PR DESCRIPTION
**Pull request by spastorino**
r? @oli-obk

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by spastorino** [comment]
This is really low-risk ... as you've approved @compiler-errors and given that @oli-obk is on vacations, I guess I can r=compiler-errors?.

This is low risk, is going in the same direction as we go for instance in `all_local_items` and also ... I'd say that as soon as we have clear clients that interact with SMIR better we could do another pass with cleanups. I find the thing right now a bit untidy, but I don't clear until there's a high level of completeness. Let me know if it's ok if I `bors r=you`

**Comment by compiler-errors** [comment]
github status is yellow, give it a few hours then try to re-approve if bors is still asleep

**Comment by spastorino** [comment]
Thanks, going to rollup as we're doing with most SMIR PRs and this one is really simple :).

@bors rollup

**Pull request merged**
