### PR TITLE
Update jemalloc to 4.0.3

### PR DESCRIPTION
**Pull request by fbernier**
Updating to 4.0.0 had already been attempted [here](https://github.com/rust-lang/rust/pull/28304), but for some reasons the tests failed. I just tried with the latest jemalloc release and they seemed to work (if I am doing this right).

### CODE REVIEW

**Comment by fbernier** [comment]
So, I am not sure it's going to build finally. it looks like jemalloc needs to ./autogen before ./configure ([see here](https://github.com/jemalloc/jemalloc/blob/dev/INSTALL#L11-L14) and the current build script doesn't do that. I don't really know where to change this yet.

Also, maybe we should reenable jemalloc for openBSD and bitrig?

**Comment by fbernier** [comment]
and rust-lang/jemalloc would need to be updated. I guess I should not be doing this as it looks like this whole job should be made by someone from the core team. Sorry for the noise.

**Comment by alexcrichton** [comment]
@fbernier ah I'm totally fine trying out the update again! You'll want to open a PR against `rust-lang/jemalloc`, and yeah you'll basically use the relevant commit of upstream jemalloc and then add one with a checked in configure script on top. I'll merge after that and then a PR can be made here

**Comment by fbernier** [comment]
Great! Will do that soon. Thanks!

**Pull request closed without merging**
