### PR TITLE
[jemalloc] call mallocx only when neceesary

### PR DESCRIPTION
**Pull request by gnzlbg**
We currently always use `mallocx` but using `malloc` is faster when specifying the alignment is not necessary (we already do this optimization for `calloc`).

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Are there perhaps benchmarks showing this is faster? Additionally, should such an optimization be applied to deallocation as well?

**Comment by arthurprs** [comment]
Maybe we shouldn't do this. It's just pulling the branch up in the stack as mallocx already has a fast path for likely(flags == 0).

Also checked in a benchmark.

```
test roundtrip           ... bench:          13 ns/iter (+/- 3)
test roundtrip_w_nallocx ... bench:          16 ns/iter (+/- 7)
test roundtrip_w_sallocx ... bench:          19 ns/iter (+/- 3)
test roundtripx          ... bench:          13 ns/iter (+/- 2)
```

**Comment by gnzlbg** [comment]
@alexcrichton for deallocation the optimization is to pass the size to speed up finding the memory blocks which is what we are already doing.

@arthurprs is right, `mallocx` already has a n `unlikely(flags != 0)` branch so that the only difference between `mallocx` and `malloc` here is that mallocx sets as option `error_on_errorno` in malloc: https://github.com/jemalloc/jemalloc/blob/7e74093c96c019ce52aee9a03fc745647d79ca5f/src/jemalloc.c#L2535

@arthurprs where are these benchmarks and how do you run them?

It takes 1 hour to recompile any change to `liballoc_jemalloc` and `liballoc` on my machine (incremental compilation and `--keep stage 1` always fail to build), and when I try to run the benchmarks with `x.py bench liballoc vec` I haven't been able to run yet only benchmarks with `vec` in the name.

**Comment by arthurprs** [comment]
@gnzlbg I uploaded it to a gist https://gist.github.com/arthurprs/0c6e7d1f561ac8ec7ff942d399620dcc

**Pull request closed without merging**
