### PR TITLE
rustdoc: Early doc link resolution fixes and refactorings

### PR DESCRIPTION
**Pull request by petrochenkov**
A subset of https://github.com/rust-lang/rust/pull/94857 that shouldn't cause perf regressions, but should fix some issues like https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/ICE.20in.20collect_intra_doc_links.2Ers https://github.com/rust-lang/rust/pull/95290 and improve performance in cases like https://github.com/rust-lang/rust/issues/95694.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Not all performance is recovered.

The full condition on import inlining is `denied` in `fn clean_use_statement`.
It's pretty complex but the `is_visible_from_parent_mod` component can easily be used in `early.rs` for further pruning the set of imports we need to process.
Other conditions are rare and shouldn't affect performance on average.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks for this first improvement! Is the PR ready or not yet? If so r=me. Also, do you have ideas on how to fix the remaining perf regression?

**Comment by petrochenkov** [comment]
Yep, this recovers the performance.
@rutbot ready

**Comment by petrochenkov** [comment]
If backporting is required then the part inside `fn process_module_children_or_reexports` can be backported in isolation.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
It's awesome, thanks a lot!

@bors: r+

**Comment by petrochenkov** [comment]
>Error:  (line 5) TimeoutError: waiting for selector "#search-settings" failed: timeout 30000ms exceeded: for command `wait-for: "#search-settings"`

Looks spurious.
@bors retry

**Pull request merged**
