### PR TITLE
[WIP] Tweak query code for performance

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 43d2894e0f981b4365a12b95cdb3b44716d2fa0b

**Comment by Zoxc** [comment]
@rust-timer build 264b63a71f4c28f5cfd0cc552b51e0288ccb0cca

**Comment by michaelwoerister** [comment]
This looks very promising `:)` Ping me when it's not work-in-progress anymore.

cc @rust-lang/wg-compiler-performance

**Comment by nnethercote** [comment]
Indeed, looks good! @Zoxc, can you edit this PR's description with some brief details of what the 30 commits do? Thanks.

**Comment by Zoxc** [comment]
I'll probably split this out in smaller PRs when I clean things up

**Comment by michaelwoerister** [comment]
> I'll probably split this out in smaller PRs when I clean things up

Yes, that's a good idea!

**Comment by Aaronepower** [comment]
Triage; @Zoxc  Hello, have you been able to get back to this PR?

**Pull request closed without merging**
