### PR TITLE
add implementation of Ord for Cell<T> and RefCell<T> where T: Ord

### PR DESCRIPTION
**Pull request by vadixidav**
Raised this in issue #33305.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
I think these sort of proxy impls for `RefCell` were omitted intentionally, since they need to borrow the cell, which can cause a panic.

**Comment by vadixidav** [comment]
It is safe code. Borrow on `RefCell` already can cause a safe panic. Also, the only other way to get `Ord` on a `RefCell` is by making a newtype, which was problematic in some code I was writing where I would have to make newtypes and write tons of boilerplate for about 10 types. Also, it would cause a panic anyways if std was passed some sort of closure or used the Ref from the borrow() function when a RefMut was in existence. There is no way to implement Ord for RefCell in any other way. Also, Cell didn't have any Ord either, despite it not having the borrow issue.

**Comment by jonas-schievink** [comment]
Of course it's safe, but it might be surprising. I don't think there's any other operator impl in the standard library that can panic.

> I would have to make newtypes and write tons of boilerplate for about 10 types.

Why isn't `struct OrdRefCell<T>` enough? Or did you mean you're only using it for 10 different types?

> Also, it would cause a panic anyways if std was passed some sort of closure or used the `Ref` from the `borrow()` function

The difference is that the `.borrow()` would have been written explicitly by the user, while this puts it in the standard library (and not even into a regular method, but into otherwise harmless operators like `<`).

I don't think it's too much of a hassle to have to write `x.borrow() < y.borrow()`, but then again I don't know your code so YMMV.

Regarding `Cell`, maybe that's just an oversight. I don't know.

**Comment by vadixidav** [comment]
Eq is implemented on RefCell. That will cause the same issue. To be consistent we should add this as well.

**Comment by jonas-schievink** [comment]
Huh, indeed. In that case, I agree that these should be added for consistency. Same for `Cell`.

**Comment by sfackler** [comment]
For historical context: https://github.com/rust-lang/rust/pull/25744

**Comment by alexcrichton** [comment]
I'd be fine merging this. This is just extending what we already have with `PartialEq` and the conclusion of #25744 was that the ergonomic win here is worth it.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage the other day and the conclusion was to merge. Thanks again for the PR @vadixidav!

@bors: r+ 4dcb63707eae97032254c18204b0f64b002b9cca

**Pull request merged**
