### PR TITLE
Remove explicit syntax highlight from docs.

### PR DESCRIPTION
**Pull request by jbcrail**
As suggested by @steveklabnik in #23254, I removed the redundant Rust syntax highlighting from the documentation.

### CODE REVIEW

**Comment by brson** [comment]
Nice cleanup. Thanks.

@bors: r+ rollup

**Comment by jbcrail** [comment]
Thanks. I resolved the merge conflicts and rebased.

**Comment by jbcrail** [comment]
I fixed merge conflicts and rebased.

**Pull request merged**
