### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by cuviper**
- Fix insufficient logic when searching for the underlying allocation #124761
- Handle field projections like slice indexing in invalid_reference_casting #124908
- Handle Deref expressions in invalid_reference_casting #124978
- Fix ICE in non-operand `aggregate_raw_ptr` instrinsic codegen #125184
- Wrap Context.ext in AssertUnwindSafe #125392
- Revert problematic opaque type change #125489
- ast: Revert a breaking attribute visiting order change #125734
- Update to LLVM 18.1.7 #126061
- Revert "Disallow ambiguous attributes on expressions" on beta #126102 / #126101
- Silence double-symlink errors while building solaris toolchain #126011 

r? cuviper

### CODE REVIEW

**Comment by lqd** [comment]
As seen in https://github.com/rust-lang/rust/pull/126102 which failed as well, I think we need to backport the CI fix https://github.com/rust-lang/rust/pull/126011

**Comment by workingjubilee** [comment]
Correct.

**Comment by cuviper** [comment]
Ok, I can pull that as well as your other backport.

**Comment by workingjubilee** [comment]
Should only need 40291bce5f93afe25825709d7782e86445086e2f

**Pull request merged**
