### PR TITLE
Check array indices in constant propagation

### LINKED ISSUE #48920: Missing index out of bounds error
The following example no longer throws a warning about indices being out of bounds, on master: 
```rust
fn main() {
    let a: [i32; 1] = [0; 1];
    a[1];
}
```
I expect a [`index out of bounds: the len is 1 but the index is 1` error](https://play.rust-lang.org/?gist=34c432d5968965257cc05db9c330d63f&version=nightly). I suspect this is due to https://github.com/rust-lang/rust/pull/46882.

cc @oli-obk

### PR DESCRIPTION
**Pull request by fanzier**
Previously, uses of constant weren't correctly propagated.
This fixes #48920.

r? @oli-obk because you suggested it

### CODE REVIEW

**Review by oli-obk — COMMENTED** [review]
My initial hope was that just propagating the `Rvalue::Len` would automatically cause the index out of bounds terminator to report its error.

Did you try to go down that route?

**Comment by fanzier** [comment]
Not sure what you mean with `Rvalue::Len` because I don't think this is emitted for arrays (just for slices). In this [example](https://play.rust-lang.org/?gist=f079f31d3ad6b5cb1f4aff7657ca6497&version=nightly&mode=debug), there is only a comparison of two constants (the array size and the index) and an assertion that this comparison is as expected:

```
    bb5: {                              
        StorageDead(_4);                 // bb5[0]: scope 0 at src/main.rs:2:37: 2:38
        StorageLive(_6);                 // bb5[1]: scope 1 at src/main.rs:3:5: 3:9
        StorageLive(_7);                 // bb5[2]: scope 1 at src/main.rs:3:7: 3:8
        _7 = const 1usize;               // bb5[3]: scope 1 at src/main.rs:3:7: 3:8
                                         // ty::Const
                                         // + ty: usize
                                         // + val: Value(Scalar(Bits { defined: 64, bits: 1 }))
                                         // mir::Constant
                                         // + span: src/main.rs:3:7: 3:8
                                         // + ty: usize
                                         // + literal: const 1usize
        _8 = const 1usize;               // bb5[4]: scope 1 at src/main.rs:3:5: 3:9
                                         // ty::Const
                                         // + ty: usize
                                         // + val: Value(Scalar(Bits { defined: 64, bits: 1 }))
                                         // mir::Constant
                                         // + span: src/main.rs:3:5: 3:9
                                         // + ty: usize
                                         // + literal: const 1usize
        _9 = Lt(_7, _8);                 // bb5[5]: scope 1 at src/main.rs:3:5: 3:9
        assert(move _9, "index out of bounds: the len is move _8 but the index is _7") -> bb6; // bb5[6]: scope 1 at src/main.rs:3:5: 3:9
    }
```

**Comment by fanzier** [comment]
Yes, exactly, this code in `const_prop.rs` was the problem:
```
            // No need to overwrite an already evaluated constant
            Rvalue::Use(Operand::Constant(box Constant {
                literal: Literal::Value {
                    value: &ty::Const {
                        val: ConstVal::Value(_),
                        ..
                    },
                },
                ..
            })) => None,
```

Removing this makes array index checks work. I'll do slices in a separate PR. Will update the commit in a minute.

**Comment by oli-obk** [comment]
You should `#![allow(const_err)]` in the failing run-fail tests, because while we know at compile-time that they are going to fail, the tests are supposed to test that the panic actually occurs

**Comment by fanzier** [comment]
Thanks, Travis is passing now

**Comment by oli-obk** [comment]
@bors r+

Awesome! Thanks

**Comment by fanzier** [comment]
Rebased but didn't find any conflicts (?)

**Comment by leonardo-m** [comment]
Is code like this supposed to give an error in the last Nightly?

```
fn main() {
    let a: [i32; 1] = [0; 1];
    a[1];
}
```

**Comment by leonardo-m** [comment]
If I compile with "rustc test.rs" I see:

```
error: index out of bounds: the len is 1 but the index is 1
 --> test.rs:3:5
  |
3 |     a[1];
  |     ^^^^
  |
  = note: #[deny(const_err)] on by default
```

If I compile with "rustc --emit=metadata test.rs", I see no errors. Is this good?

**Comment by oli-obk** [comment]
Ugh.... that is weird. Open an issue?

**Comment by leonardo-m** [comment]
Opened as #51491

**Pull request merged**
