### PR TITLE
Compiler error messages: reduce assertiveness of message E0384

### LINKED ISSUE #84144: Immutable variable reassignment help message
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=513388a632de3de69d34c0ced0483ec6

```rust
fn main() {
    let x = 5;
    println!("The value of x is: {}", x);
    x = 6;
    println!("The value of x is: {}", x);
}
```

The current output is:

```
...
  |         help: make this binding mutable: `mut x`
...
```

Ideally the output should look like:

```
...
  |         help: consider making this binding mutable: `mut x`
...
```

Maybe it's over-analyzing the messaging, but in a lot of cases we make _suggestions_ from compiler help messages - i.e. `consider doing x`.  That suggests the programmer should take a moment to think of alternatives before continuing.

The current message regarding mutable variables seems quite direct, as if it might be the only solution.  Perhaps in some cases it will be, but encouraging use of immutable variables is probably - generally - a good thing.

One drawback with this suggestion would be that it is less concise.  That means slightly more overhead as people read and understand the message.

### PR DESCRIPTION
**Pull request by jayaddison**
This message is emitted as guidance by the compiler when a developer attempts to reassign a value to an immutable variable.  Following the message will always currently work, but it may not always be the best course of action; following the 'consider ...' messaging pattern provides a hint to the developer that it could be wise to explore other alternatives.

Resolves #84144

### CODE REVIEW

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Comment by petrochenkov** [comment]
The failure looks spurious and unrelated, @bors retry

**Comment by jayaddison** [comment]
Thanks @petrochenkov; I did notice that a very similar error to https://github.com/rust-lang/rust/pull/84172#issuecomment-819072591 was also reported at https://github.com/rust-lang/rust/pull/83610#issuecomment-810428674 (cc @bjorn3) - perhaps there's a bug to find in the build process somewhere?

**Pull request merged**
