### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #71923 (Check non-Send/Sync upvars captured by generator)
 - #72153 (exhaustively check `ty::Kind` during structural match checking)
 - #72272 (Fix going back in history to a search result page on firefox)
 - #72275 (Continue lowering for unsupported async generator instead of returning an error.)
 - #72361 (split_inclusive: add tracking issue number (72360))

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Ci failed spuriously

**Comment by ecstatic-morse** [comment]
@bors r-

This failure is not spurious. #72153 needs a rebase.

**Comment by Dylan-DPC** [comment]
Thanks

**Pull request closed without merging**
