### PR TITLE
Symbols: do not write string values of preinterned symbols into compiled artifacts

### PR DESCRIPTION
**Pull request by klensy**
r? @bjorn3

Followup for #98851

https://github.com/rust-lang/rust/pull/98851#issuecomment-1215606291

### CODE REVIEW

**Comment by pnkfelix** [comment]
This PR addresses a performance regression injected by #98851, so I'm going to up its priority to ensure it gets in well before the aforementioned regression can cause too many problems.

@bors p=3

**Comment by matthiaskrgr** [comment]
moving before the rollup @bors p=20

**Pull request merged**
