### PR TITLE
Stabilise inclusive_range_methods

### LINKED ISSUE #49022: Tracking issue for `start`, `end` and `new` methods of RangeInclusive
Tracking issue for the `start`, `end` and `new` methods of `RangeInclusive`. 

(Originally the tracking issue for rust-lang/rfcs#1980 the `start` and `end` fields, but we decided to make the representation private in https://github.com/rust-lang/rust/issues/49022#issuecomment-377533282)

**Steps**:

- [x] Implementation #49724
- [ ] Stabilization PR https://github.com/rust-lang/rust/pull/50758

**Unresolved questions**:

- [x] ~~Should we want to expose the fields as public (stabilize as is), or simply provide getter methods and don't show the implementation detail (redesign from scratch)?~~

This issue is separated from #28237 since there were vocal oppositions from the community (see #47813) due to performance loss if we commit to the two-field design. 

If you want `start` and `end`, please use these for now:

* `x.start()` ↦ `x.next().unwrap()`
* `x.end()` ↦ `x.next_back().unwrap()`

### PR DESCRIPTION
**Pull request by varkor**
r? @SimonSapin 

Closes #49022.

### CODE REVIEW

**Comment by varkor** [comment]
Note that this stabilises `RangeInclusive::into_inner` too, which is contained under the same feature name. It probably makes sense to stabilise this at the same time, but if not, I'll change the feature name.

**Comment by SimonSapin** [comment]
The libs team discussed this today. Given that `a..=b` syntax was stabilized in 1.26 with no way to access the fields and that this is very low-risk, the consensus was that we’re fine with stabilizing these methods (including `into_inner`) and backporting to 1.27 beta.

The only concern was the behavior of these accessors after an inclusive range has been iterated to exhaustion. Currently, `start` and `end` are reset to 1 and 0 respectively, but we might want to change that later.

@varkor, could you please:

* Add to the doc-comment of each of these three methods something like this: The value returned by this method after the range has been iterated to its end is undefined.
* Change the `since` attributes back to 1.27.0 (sorry!)

**Comment by dtolnay** [comment]
I wouldn't necessarily use the word "undefined" in the sense of "if your code does this then you are triggering undefined behavior." That is, it isn't scary to do but just probably not a foolproof way to do what you intended unless you have thought through the edge cases.

I would find the more transparent approach more appealing -- explain in the struct-level documentation of RangeInclusive what the current implementation does and why it is more complicated than what you might naively expect, and be very explicit about what aspects of it are / are not subject to change.

**Comment by SimonSapin** [comment]
It’s not *undefined behavior* but we don’t want to define (document, guarantee) what the *value* is, right?

**Comment by kennytm** [comment]
We call them "unspecified" or "implementation defined" in C 🙂.

**Comment by SimonSapin** [comment]
Alright, unspecified sounds good to me.

**Comment by dtolnay** [comment]
I agree with calling it unspecified.

**Comment by varkor** [comment]
👍 I've added comments describing it as such.

**Comment by SimonSapin** [comment]
@bors r+

Thanks!

**Comment by varkor** [comment]
I've rebased on top of the conflicting stabilisation in https://github.com/rust-lang/rust/pull/50807.

**Comment by kennytm** [comment]
It is an endless stream of merge conflicts 😕

**Pull request merged**
