### PR TITLE
Clarify the debug-related values should take boolean

### PR DESCRIPTION
**Pull request by JohnTitor**
#76588 tweaked their placeholders but these values should take boolean and the current placeholders are confusing, at least for me.

### CODE REVIEW

**Comment by jyn514** [comment]
Hmm, I don't know if I like this change. You've changed the default to the default of `debug`, but that is _not_ the default value here: the default is the value of `debug`. If you set `debug = true`, these will default to `true`, not to `false`.

**Comment by tmiasko** [comment]
This is being changed back and forth. See for example previous discussion in #73538.

**Comment by JohnTitor** [comment]
@jyn514 Okay, you think a placeholder should be a "default value" but I thought it should've been a "taken value" :)
Hmm, but it's not obvious to me that they take boolean since their docs aren't mentioned. Actually, I just uncommented `debug-assertions` then x.py complained that the value was wrong, it made me confused. So I'd like to improve in some way.

**Comment by jyn514** [comment]
I would like to avoid changing this back and forth. If we do change this, I would like a policy somewhere (maybe just at the top of config.toml?) so people know not to change this back.

That said, I'm not _strongly_ opposed to this change as long as it's documented that it's not the default. Currently config.toml says these are defaults, so this would break that: https://github.com/rust-lang/rust/blob/03eb74a3c833778a38a476c36ece8bbfd2cdfbc1/config.toml.example#L6-L7

**Comment by JohnTitor** [comment]
@jyn514 Fair enough! So what about this?
```toml
#debug-assertions = rust.debug value (boolean)
```
It doesn't lose the current meaning and tells the users that the value should take boolean.

**Comment by jyn514** [comment]
Sure, that sounds good to me. I would remove "value" in the comment though, or maybe change it to "value of rust.debug".

**Comment by JohnTitor** [comment]
@jyn514 Updated.

**Comment by jyn514** [comment]
@bors r+ rollup

Thanks for bringing this up :) I can definitely see how it was confusing before.

**Pull request merged**
