### PR TITLE
--remap-path-prefix: Fix duplicated path components in debuginfo

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR fixes an issue with `--remap-path-prefix` where path components could appear twice in the remapped version of the path (e.g. https://github.com/rust-lang/rust/issues/78479). The underlying problem was that `--remap-path-prefix` is often used to map an absolute path to something that looks like a relative path, e.g.:

```
--remap-path-prefix=/home/calvin/.cargo/registry/src/github.com-1ecc6299db9ec823=crates.io",
```

and relative paths in debuginfo are interpreted as being relative to the compilation directory. So if Cargo invokes the compiler with `/home/calvin/.cargo/registry/src/github.com-1ecc6299db9ec823/some_crate-0.1.0/src/lib.rs` as input and `/home/calvin/.cargo/registry/src/github.com-1ecc6299db9ec823/some_crate-0.1.0` as the compiler's working directory, then debuginfo will state that the working directory was `crates.io/some_crate-0.1.0` and the file is question was `crates.io/some_crate-0.1.0/src/lib.rs`, which combined gives the path:

```
crates.io/some_crate-0.1.0/crates.io/some_crate-0.1.0/src/lib.rs
```

With this PR the compiler will detect this situation and set up debuginfo in LLVM in a way that makes it strip the duplicated path components when emitting DWARF.

The PR also extracts the logic for making remapped paths absolute into a common helper function that is now used by debuginfo too (instead of just during crate metadata generation).

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Perf looks good.

**Comment by nagisa** [comment]
r? rust-lang/compiler

I won't be able to get to reviewing things for the upcoming next couple weeks.

**Comment by compiler-errors** [comment]
not exactly my wheelhouse, so reassigning

r? rust-lang/compiler

**Review by davidtwco — APPROVED** [review]

**Comment by michaelwoerister** [comment]
It looks like `-Z simulate-remapped-rust-src-base` does not have an effect if `remap-debuginfo = true` in `config.toml`, so the test that failed produces a different output on CI (`/rustc/<sha>/foo.rs` vs `/rustc/<value from simulate-remapped-rust-src-base>/foo.rs`). I reverted my changes to that test so that it accepts both versions again.

**Pull request merged**
