### PR TITLE
[perf] Delay the construction of early lint diag structs

### PR DESCRIPTION
**Pull request by fmease**
Attacks some of the perf regressions from https://github.com/rust-lang/rust/pull/124417#issuecomment-2123700666.

See individual commits for details. The first three commits are not strictly necessary.
However, the 2nd one (06bc4fc67145e3a7be9b5a2cf2b5968cef36e587, *Remove `LintDiagnostic::msg`*) makes the main change way nicer to implement.
It's also pretty sweet on its own if I may say so myself.

### CODE REVIEW

**Comment by fmease** [comment]
Ah, yikes, I completely forgot about tools!

**Comment by fmease** [comment]
r? nnethercote or davidtwco

**Comment by nnethercote** [comment]
Looks good, thanks.

@bors r+

**Pull request merged**
