### PR TITLE
Doc backport

### PR DESCRIPTION
**Pull request by steveklabnik**
This backports to beta all non-reference, non-TRPL documentation commits made since we forked. At least, up until the two PRs that are open today.
- https://github.com/rust-lang/rust/pull/24496
- https://github.com/rust-lang/rust/pull/24501
- https://github.com/rust-lang/rust/pull/24510
- https://github.com/rust-lang/rust/pull/24554
- https://github.com/rust-lang/rust/pull/24555
- https://github.com/rust-lang/rust/pull/24559
- https://github.com/rust-lang/rust/pull/24567
- https://github.com/rust-lang/rust/pull/24572
- https://github.com/rust-lang/rust/pull/24606
- https://github.com/rust-lang/rust/pull/24608
- https://github.com/rust-lang/rust/pull/24625
- https://github.com/rust-lang/rust/pull/24627
- https://github.com/rust-lang/rust/pull/24628
- https://github.com/rust-lang/rust/pull/24629
- https://github.com/rust-lang/rust/pull/24647
- https://github.com/rust-lang/rust/pull/24662
- https://github.com/rust-lang/rust/pull/24692
- https://github.com/rust-lang/rust/pull/24783 (relevant portions)

Only one had two commits, hence 18 PRs and 19 commits.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Ahh i guess try only works to master.

**Comment by steveklabnik** [comment]
I'm gonna run a test locally before merging.

**Comment by Gankro** [comment]
Presumably I don't actually need to review anything for this kind of PR?

**Comment by steveklabnik** [comment]
@Gankro yeah, I already assigned it to myself. :heart:

**Comment by steveklabnik** [comment]
Passed all tests locally. :confetti_ball:

**Pull request merged**
