### PR TITLE
[doc] Fix multi-threading example in dining-philosophers

### PR DESCRIPTION
**Pull request by rwz**
The current example does not illustrate threaded behavior imo.

### CODE REVIEW

**Comment by rwz** [comment]
Oh man, I didn't notice the philosophers names are different.

**Comment by alexcrichton** [comment]
The current example does actually show off multithreading, it's just not as interleaved as one  might expect because you have to lock your fork on the table and if you can't you haven't started eating. The actual scenario where everyone starts eating all at once before anyone has finished is impossible because there aren't enough forks to go around.

Thanks for the PR though!

**Comment by rwz** [comment]
At the point that I've edited we still don't have any locks/forks. This is the example where everyone start at the same time, wait 1 second and then finish, roughly at the same again. Forks are added in the next step. The change that I've made was actually what I was getting implementing the example.

**Comment by alexcrichton** [comment]
Oh oops sorry, missed that part!

**Pull request merged**
