### PR TITLE
Issue #60709 test

### PR DESCRIPTION
**Pull request by tmandry**
Adds a test for #60709, which was fixed as part of #59897.

r? @cramertj

### CODE REVIEW

**Comment by tmandry** [comment]
@cramertj Are you fine with this grouping? It's not totally consistent with `src/tests/ui/async-await`. I suppose that directory could be renamed to `futures` too.

**Comment by cramertj** [comment]
@tmandry No, I'd expect `futures` tests to be for the library functionality-- generators / async/await stuff should be in `src/test/ui/async-await` or `src/test/run-pass/async-await` IMO.

**Pull request merged**
