### PR TITLE
Give SliceIndex impls a test suite of girth befitting the implementation

### PR DESCRIPTION
**Pull request by ExpHP**
So one day I was writing something in my codebase that basically amounted to `impl SliceIndex for (Bound<usize>, Bound<usize>)`, and I said to myself:

*Boy, gee, golly!  I never realized bounds checking was so tricky!*

At some point when I had around 60 lines of tests for it, I decided to go see how the standard library does it to see if I missed any edge cases. ...That's when I discovered that libcore only had about 40 lines of tests for slicing altogether, and none of them even used `..=`.

---

This PR includes:

* **Literally the first appearance of the word `get_unchecked_mut` in any directory named `test` or `tests`.**
* Likewise the first appearance of `get_mut` used with _any type of range argument_ in these directories.
* Tests for the panics on overflow with `..=`.
    * I wanted to test on `[(); usize::MAX]` as well but that takes linear time in debug mode </3
* A horrible and ugly test-generating macro for the `should_panic` tests that increases the DRYness by a single order of magnitude (which IMO wasn't enough, but I didn't want to go any further and risk making the tests inaccessible to next guy).
* Same stuff for str!
    * Actually, the existing `str` tests were pretty good. I just helped filled in the holes.
* [A fix for the bug it caught](https://github.com/rust-lang/rust/issues/50002).  (only one ~~sadly~~)

### CODE REVIEW

**Comment by ExpHP** [comment]
On second thought I think I'm going to pull the bug fix into a separate PR to make it easier to backport to beta

**Comment by ExpHP** [comment]
Note: After #50039 merges, this will need to be rebased/force-pushed  (I couldn't cherry-pick the commit from this PR).

When I do so I will likely:
* revisit the syntax for the test-generating macro in this PR (because I really hate it)
* look for any other `RangeXyzInclusive` methods that can be delegated to `RangeXyz` (https://github.com/rust-lang/rust/pull/50039#issuecomment-383315030)

so any review might want to hold off until then.

**Comment by ExpHP** [comment]
Oops, sorry!   I did something locally, but then started having second thoughts due to how uneven the PR makes this part of the test suite appear, and chickened out.  I guess I should follow through and just get it back up here, to let others be the judge of that.

(also, my local branch currently has the cardinal sin of a later commit that broadly changes decisions made in an earlier commit, but it seemed too difficult to clean up due to intervening commits, so I'm afraid I might have to leave it like that. Blechh)

**Comment by ExpHP** [comment]
Oops, sorry!   I did something locally, but then started having second thoughts due to how uneven the PR makes this part of the test suite appear, and chickened out.  I guess I should follow through and just get it back up here, to let others be the judge of that.

(also, my local branch currently has the cardinal sin of a later commit that broadly changes decisions made in an earlier commit, but it seemed too difficult to clean up due to intervening commits, so I'm afraid I might have to leave it like that. Blechh)

**Comment by ExpHP** [comment]
rebased, force-pushed, and put into correct chronological order using black magic.

Notes:

* Be aware that the macro syntax introduced in 02b3da1 is revised in later commits.
    * (Crap, I just noticed now that I actually *could* have squashed these easily, thanks to having removed some of the intervening commits at the last minute. Sorry)
* The concern addressed by ce66f5d9185aa2b81159fa61597bbb6e4cf2847f is purely anticipatory

**Comment by shepmaster** [comment]
Ping from triage, @bluss! Will you have time to review this in the near future?

**Comment by alexcrichton** [comment]
Egad sorry for the delay @ExpHP! Tihs all looks great to me, thanks!

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry r-

prioritizing rollup which includes this in it

I think the `simple_big` test may also have been the cause of https://travis-ci.org/rust-lang/rust/jobs/377407894, so I've ignored the test for Emscripten specifically in the rollup and we can see how that goes

**Comment by ExpHP** [comment]
Makes sense.  The test was present before this PR, but my PR adds a `to_owned()` (hidden in the `assert_range_eq!` macro) that might be pushing it just over the limit.

**Pull request merged**
