### PR TITLE
Backport #46385

### PR DESCRIPTION
**Pull request by steveklabnik**
r? @alexcrichton

### CODE REVIEW

**Comment by kennytm** [comment]
🤔 CI is failing because external factors are still not fixed.

@steveklabnik Could you backport #46715 and #46694 together? Otherwise I'm afraid bors won't be happy (yes http://crosstool-ng.org/ is *still* offline).

**Comment by steveklabnik** [comment]
I can try to roll them into these PRs...

**Comment by steveklabnik** [comment]
Let's see how this goes.

**Comment by steveklabnik** [comment]
Looks like it passed!

@bors: r=alexcrichton

**Pull request merged**
