### PR TITLE
Fix fs tests on Windows systems with non-english locales.

### PR DESCRIPTION
**Pull request by retep998**
Fixes https://github.com/rust-lang/rust/issues/34628

r? @alexcrichton

### CODE REVIEW

**Comment by petrochenkov** [comment]
Does this fix https://github.com/rust-lang/rust/issues/34628?
(That issue becomes more important because rustbuild doesn't allow manually skipping tests currently.)

**Comment by retep998** [comment]
@petrochenkov It does now.

**Comment by daschl** [comment]
@retep998 how did that branch name came to be? 😂

**Comment by est31** [comment]
@daschl I've stumbled across this error on a german locale, and the 🐇 has fixed it :)

**Comment by petrochenkov** [comment]
Can confirm, with `chcp 65001` all `make check` tests now pass on a totally non-English (Windows itself, locale, username, env vars) system.

**Pull request merged**
