### PR TITLE
Remove leftover tab in libtest outputs

### LINKED ISSUE #50362: Unnecessary whitespaces in test stdout capture
To reproduce, run `cargo test` on the following library:
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        println!("hello");
        println!("world");
        panic!();
    }
}
```

Expected output:
```
...
---- tests::it_works stdout ----
hello
world
thread 'tests::it_works' panicked at 'explicit panic', src\lib.rs:7:9
...
```

Actual output:
```
...
---- tests::it_works stdout ----
        hello
world
thread 'tests::it_works' panicked at 'explicit panic', src\lib.rs:7:9
...
```

Version info:
```
> rustc --version --verbose
rustc 1.26.0-nightly (5508b2714 2018-03-18)
binary: rustc
commit-hash: 5508b27145cfb82896ae838e6aca0cd48750796f
commit-date: 2018-03-18
host: x86_64-pc-windows-msvc
release: 1.26.0-nightly
LLVM version: 6.0

> cargo --version --verbose
cargo 1.26.0-nightly (d6c3983fe 2018-03-16)
release: 1.26.0
commit-hash: d6c3983fe3bd8fa06b54712e53fb23645598188b
commit-date: 2018-03-16
```

### PR DESCRIPTION
**Pull request by phansch**
This removes some tabs that were present in the output of libtest.

Related #19299
Closes #50362

### CODE REVIEW

**Comment by kennytm** [comment]
(cc @nikomatsakis #19299)

**Comment by nikomatsakis** [comment]
Maybe, but I sort of doubt it. That'd be some pretty careful parsing of the output, and we don't really consider this output to be stable.

**Comment by TimNN** [comment]
@bluss or someone else from @rust-lang/dev-tools, could you please review this PR?

**Comment by pietroalbini** [comment]
Ping from triage! This PR needs a review, can @bluss or someone else from @rust-lang/libs review this?

**Comment by kennytm** [comment]
@bors r-

Blocked by #50696.

**Comment by phansch** [comment]
With https://github.com/rust-lang/rust/pull/50696 merged, I believe this should be ready now.

**Pull request merged**
