### PR TITLE
update miri

### LINKED ISSUE #70055: `miri` no longer builds after rust-lang/rust#67133
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#67133, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @oli-obk, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/70055
r? @ghost
Cc @oli-obk @Amanieu

### CODE REVIEW

**Comment by RalfJung** [comment]
Submodule-only toolstate fix
@bors r+ p=1

**Comment by RalfJung** [comment]
```
2020-03-19T09:16:28.8996940Z clang+llvm-9.0.0-x86_64-darwin-apple/bin/llvm-elfabi: Lzma library error:  No progress is possible
2020-03-19T09:16:28.9087930Z tar: Error exit delayed from previous errors.
```
@bors retry

**Comment by RalfJung** [comment]
Same error again.
```
2020-03-19T12:23:55.8361020Z curl: (56) SSLRead() return error -9806
2020-03-19T12:23:55.8666880Z clang+llvm-9.0.0-x86_64-darwin-apple/bin/opt: Lzma library error:  No progress is possible
2020-03-19T12:23:55.8745420Z tar: Error exit delayed from previous errors.
```

@bors retry

**Comment by pietroalbini** [comment]
Hijacking this PR to test infra changes, sorry for the noise!

**Comment by pietroalbini** [comment]
YAY! :tada: 

@bors r=RalfJung p=5 treeclosed-

**Pull request merged**
