### PR TITLE
Remove `match` and `memcpy` from `String::push`

### PR DESCRIPTION
**Pull request by paolobarbolini**
This all started as an experiment trying to remove the `memcpy` from the `self.vec.extend_from_slice` branch of `String::push`.

I haven't run any extensive benchmarks yet, for the moment results on the current benchmarks are ~~mixed~~ promising. ~~I don't like the fact that the `panic!` branch of `encode_utf8_raw` doesn't get optimized away anymore :disappointed:, probably because of an LLVM limitation. I have an idea for how to fix it.~~
Diff view: https://rust.godbolt.org/z/bKh6dfqo7

If this were to work the same optimization could be applied to `String::insert` in the future.

### CODE REVIEW

**Comment by paolobarbolini** [comment]
I'm thinking of temporarily replacing the `panic!` in `encode_utf8_raw` with `unreachable_unchecked` so that we can do another perf run and get a quick feedback on whether this would worth it.

**Comment by JohnTitor** [comment]
So regressions here are greater than improvements, I don't feel it's worth moving forward currently. Do you have any other follow-ups?

**Comment by paolobarbolini** [comment]
No other folloups. Closing

**Pull request closed without merging**
