### PR TITLE
stage info

### PR DESCRIPTION
**Pull request by richo**
This will add information about the stage that a rustc was built with to the verbose version info

I have symlinks into $(HOST)/stage{0,1,2} into the rust version switcher thing I use, and occasionally need to know which stage a given rustc is.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

I don't have too much of an opinion on this, but I think you might!

**Comment by brson** [comment]
I understand the use case, but I feel a little uneasy about it. It's a niche feature for rustc hackers. I want to think about it a bit more and see if others comment.

**Comment by jroesch** [comment]
@brson I am of two minds as a rustc hacker I think it is kind of useful, but I don't know really think we should leak this information to all users of the Rust compiler given its irrelevant to 99% of our users. I tend to just use the stage1 and mostly in its own build directory so maybe I don't have the best perspective.

**Comment by richo** [comment]
How about just leaving it out for stage2+ ?

That would seem to make it transparent to end users, but make it visible if you're poking a bootstrap compiler while hacking?

**Comment by brson** [comment]
@richo Ok, let's add it for stage0/1. Thanks for your patience.

**Comment by richo** [comment]
No worries! I'll update this when I get a sec :)

**Comment by richo** [comment]
Updated! r? @brson

**Comment by richo** [comment]
I'm not really sure what's going on, but the stage2 build (including the assets installed by `make install`) reports `stage: stage1`. Is there something wonky in the build system? I've gone back and checked that `rustc` was definitely getting `--cfg stage2`.

I think this patch is still good to land, but it seems something is askew here.

**Pull request merged**
