### PR TITLE
[LLVM] Avoid losing the !nonnull attribute in SROA

### LINKED ISSUE #37945: Extra null check in slice iterator's `.next().is_none()`
This is an interesting codegen bug (Note that this reproduces in a special case setting and in many regular contexts, this problem does not exist).

### Expected behavior:

This code should just be a pointer comparison (`ptr == end` leads to `None` being returned)

```rust
use std::slice::Iter;
pub fn is_empty_1(xs: Iter<f32>) -> bool {
    {xs}.next().is_none()
}
```

### Actual behavior:

It compiles to the equivalent of `ptr == end || ptr.is_null()`.

[Playground link](https://is.gd/3G8tKj). Use release mode.

version: rustc 1.15.0-nightly (0bd2ce62b 2016-11-19)

### Additional notes:

This version has the expected codegen, without the null check.

```rust
pub fn is_empty_2(xs: Iter<f32>) -> bool {
    xs.map(|&x| x).next().is_none()
}
```

### PR DESCRIPTION
**Pull request by arielb1**
Fixes #37945.

r? @alexcrichton

### CODE REVIEW

**Comment by arielb1** [comment]
(added missing `min-llvm-version`)

@bors r=alexcrichton

**Comment by aidanhs** [comment]
```
[00:50:00] ---- [codegen] codegen/issue-37945.rs stdout ----
[00:50:00] 	
[00:50:00] error: verification with 'FileCheck' failed
[00:50:00] status: exit code: 1
[00:50:00] command: /checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck -input-file=/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/issue-37945.ll /checkout/src/test/codegen/issue-37945.rs
[00:50:00] stdout:
[00:50:00] ------------------------------------------
[00:50:00] 
[00:50:00] ------------------------------------------
[00:50:00] stderr:
[00:50:00] ------------------------------------------
[00:50:00] /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/issue-37945.ll:19:12: error: CHECK-NOT: string occurred!
[00:50:00]  %phitmp = icmp eq float* %2, null
[00:50:00]            ^
[00:50:00] /checkout/src/test/codegen/issue-37945.rs:23:15: note: CHECK-NOT: pattern specified here
[00:50:00] // CHECK-NOT: icmp eq float* {{.*}}, null
```

**Comment by arielb1** [comment]
Umm... this works on x86. What's the problem on ARM?

**Comment by arielb1** [comment]
Looks like LLVM casts pointers to integers on 32-bit archs when loading, so I might need to implement the interconversion between range <-> nonnull there too.

**Comment by arielb1** [comment]
status:

I have a patch that makes this work on 32-bit archs, now I just need to make it publication-ready and get in touch with @chandlerc.

**Comment by arielb1** [comment]
However, maybe I should just land this change now, ignoring 32-bit archs?

**Comment by alexcrichton** [comment]
Ignoring seems fine to me

**Pull request merged**
