### PR TITLE
macros: improve expansion performance

### PR DESCRIPTION
**Pull request by jseyfried**
#34908 regressed expansion performance on recursive, `tt`-heavy workloads.
This PR fixes that regression, further improves performance on recursive, `tt`-heavy workloads, and makes a variety of other improvements to parsing and expansion performance.

Expansion performance improvements:

| Test case      | Run-time | Memory usage |
| -------------- | -------- | ------------ |
| libsyntax      | 8%       | 10%          |
| librustc       | 15%      | 6%           |
| librustc_trans | 30%      | 6%           |
| #37074         | 20%      | 15%          |
| #34630         | 40%      | 8%           |

r? @eddyb

### CODE REVIEW

**Comment by jseyfried** [comment]
The 5th commit is the AST version of #37445 (h/t @nnethercote).
cc @durka

**Comment by eddyb** [comment]
@Manishearth r=me

**Comment by Manishearth** [comment]
@bors r=eddyb

cc @dtolnay

**Comment by bluss** [comment]
Since not needing ast coercion is a feature, it should have tests so that it is not broken by this improvement. Are there any tests? I didn't find any in the tree.

**Comment by jseyfried** [comment]
By "not needing ast coercion", do you mean #22819? If so, that is tested [here](https://github.com/jseyfried/rust/blob/master/src/test/compile-fail/macro-tt-matchers.rs).

**Comment by bluss** [comment]
great! I overlooked compile-fail.

**Comment by nnethercote** [comment]
AFAICT this PR regressed the speed of html5ever compilation in rustc-benchmarks. perf.rust-lang.org is showing a 6% regression for html5ever this week while other benchmarks are basically unchanged. This PR is one of the PRs that show up in the regressing measurement, and I have profiling data that corroborates.

One cause of this is the `span_to_filename` call in `Parser::new_with_doc_flag`, which causes 800k extra allocations. Another cause is an extra 800k allocations in `macro_parser::parse`. I think this is because of the `Box::new(rdr)` at the top, but I'm not certain. (I found these by comparing DHAT output for before and after.)

I think these are not the only parts of the change that lead to regressions, but it's less obvious from my profiling what else might be a factor, other than vec and slice operations are showing up higher in the profile. (I got that from the Cachegrind output.)

**Comment by jseyfried** [comment]
@nnethercote Thanks, I'll fix the regression ASAP.

**Pull request merged**
