### PR TITLE
Add documentation for aarch64-apple-ios-sim target

### PR DESCRIPTION
**Pull request by badboy**
Documentation as requested for [MCP 428](https://github.com/rust-lang/compiler-team/issues/428) to promote this target to Tier 2.

Currently it calls out that it's Tier 3. That should be changed if this target is promoted, but this PR could also land before that.

Note: probably should get signoff from the compiler team based on that MCP.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by badboy** [comment]
Oh, I just realized that the "Building Rust programs" are _not_ valid as of right now, because target artifacts are not shipped. So right now users would need nightly + `-Z build-std` for that.
If wanted I can make that more clear there.

**Comment by GuillaumeGomez** [comment]
Please do so then. There is never too much clarity. :)

**Comment by badboy** [comment]
Oh, actually, it's easier than that: We can just check for '`' somewhere in the line

**Pull request merged**
