### PR TITLE
RustWrapper: adapt for llvm/llvm-project@a38152e2156

### PR DESCRIPTION
**Pull request by durin42**
I am only partially confident this is reasonable, and the argument is ignored on targets other than ARM64EC which appears to be some Windows 11 thing, and therefore I have no way to test.

@rustbot label: +llvm-main

### CODE REVIEW

**Comment by cuviper** [comment]
@wesleywiser perhaps you (or someone you know) could evaluate this Windows change?

**Comment by cjacek** [comment]
Non-hybrid targets should not use it to pass exports to `writeImportLibrary`, please use something like `std::nullopt` instead. I created https://github.com/llvm/llvm-project/pull/81600 to clarify that.

**Comment by durin42** [comment]
Done, thanks!

**Comment by durin42** [comment]
The argument is now optional, so this shouldn't be needed. I'll open a new PR if we end up needing a change here.

**Pull request closed without merging**
