### PR TITLE
[beta] Final backports to beta

### PR DESCRIPTION
**Pull request by alexcrichton**
Backport of:

* https://github.com/rust-lang/rust/pull/40863
* https://github.com/rust-lang/rust/pull/41085
* https://github.com/rust-lang/rust/pull/41354
* https://github.com/rust-lang/rust/pull/41378

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=5

(beta backports)

**Comment by arielb1** [comment]
```Rust
error[E0369]: binary operation `!=` cannot be applied to type `Mode`

   --> /checkout/src/bootstrap/lib.rs:477:12

    |

477 |         if mode != Mode::Tool {

    |            ^^^^

    |
```

**Comment by alexcrichton** [comment]
@bors: retry

* presumed ar.exe error - https://github.com/rust-lang/rust/issues/40546

**Pull request merged**
