### PR TITLE
Update .mailmap

### PR DESCRIPTION
**Pull request by jeremystucki**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
r? @jonas-schievink @bors r+ rollup

CI failure looks spurious.

**Comment by mati865** [comment]
Is this format right?
See https://github.com/rust-lang/rust/pull/63600#issuecomment-521716064

**Comment by jonas-schievink** [comment]
@bors r-

You're right. We should fix the existing mailmap entries to avoid this confusion in the future.

**Comment by jeremystucki** [comment]
Ah sorry about that, will fix ASAP

**Pull request merged**
