### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by emilyalbini**
Successful merges:

 - #60897 (error: remove StringError from Debug output)
 - #61304 (Speed up Azure CI installing Windows dependencies)
 - #61319 (Swap order of `unsafe async fn` to `async unsafe fn`)
 - #61342 (Set ellipsis_inclusive_range_patterns lint to warn)
 - #61344 (Add regression test for const generics ICE)
 - #61359 (Fix links in Deref documentation)
 - #61363 (Stabilize iter_nth_back feature)
 - #61369 (Fixed lifetime misspelling)
 - #61372 (Migrate some books to mdbook version 0.2)
 - #61374 (Explicitly suggest 'type_ascription' feature)
 - #61382 (Fixed a typo in core::convert::AsMut)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Centril** [comment]
@bors retry

Looks spurious to me..

**Comment by mati865** [comment]
It's [Spurious SIGILL (signal 4) when linking with `cc` on macOS during doctest](https://github.com/rust-lang/rust/issues/58209)

**Comment by Manishearth** [comment]
Looks like that's a spurious toolstate breakage? I can't really tell with the new Azure stuff.

**Comment by mati865** [comment]
It's not spurious, see https://api.travis-ci.com/v3/job/204667069/log.txt and search `/checkout/src/tools/clippy/Cargo.toml`

**Comment by Manishearth** [comment]
Ah, its an issue that was already fixed on clippy master. I see.

**Pull request merged**
