### PR TITLE
use question mark operator in a few places.

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Interesting, is there a performance difference to be expected?
I tried to whip up a minimal godbolt example and the assembly seemed identical: for `a?` and `if a.is_none() { return None; }`

https://rust.godbolt.org/z/sXmqcP

**Comment by Centril** [comment]
The `?` operator can be slower in some cases due to a lack of optimizations and inlining, so I'm just verifying that there are no regressions, although I don't necessarily expect that there will be any regressions.

**Comment by petrochenkov** [comment]
Perf looks very strange, a change like this shouldn't result in such speedups.

**Comment by petrochenkov** [comment]
I'm not sure this increases readability, `a?;` looks a bit strange if the result is not assigned to anything (`let b = a?;`).

**Comment by petrochenkov** [comment]
Eh, @bors r+ anyway, I guess.

**Pull request merged**
