### PR TITLE
std::fs: get_mode implementation for all unix

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by workingjubilee** [comment]
@devnexen I see that the internal `get_path` implementation varies significantly based on OS, but are you aware of another Unix OS that would use a different implementation than the current `get_mode` implementation? It seems everyone uses the same code.

If you are not, I would like to remove the `cfg` and the "default" implementation and simply use the same code for all OS, and see if it passes in CI. That would also mean we can remove the relevant FIXME.

**Comment by devnexen** [comment]
I have no idea about another exotic unix being different in that regard.

**Comment by workingjubilee** [comment]
@devnexen I think I would prefer to demand the "exotic Unix" show themselves.

**Comment by workingjubilee** [comment]
Thanks! Let's see what CI says!

@bors r+ rollup=iffy

**Comment by workingjubilee** [comment]
( aspirationally. )

**Comment by kadiwa4** [comment]
You silently reverted #128677, was that intentional?

**Comment by devnexen** [comment]
ah no sorry for that

**Comment by workingjubilee** [comment]
Huh, sorry, didn't notice that. :upside_down_face:

**Pull request merged**
