### PR TITLE
Rename Result::as_deref_ok to as_deref

### PR DESCRIPTION
**Pull request by tesuji**
Addresses https://github.com/rust-lang/rust/issues/50264#issuecomment-533952247

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by dtolnay** [comment]
@bors r-

I think there are a bunch of tests that need to change. https://github.com/rust-lang/rust/search?q=as_deref_mut_ok&unscoped_q=as_deref_mut_ok

**Comment by lzutao** [comment]
That's right. I totally forgot about that.

**Comment by lzutao** [comment]
The build is green.

**Comment by dtolnay** [comment]
LGTM but needs a quick rebase.

**Comment by lzutao** [comment]
Rebased.

**Pull request merged**
