### PR TITLE
Fix main.js for gtk-rs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
We need it for gtk-rs. :)

r? @rust-lang/rustdoc

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Can you add a comment explaining what it's doing?

**Comment by QuietMisdreavus** [comment]
What is gtk-rs doing that requires this fix?

**Comment by GuillaumeGomez** [comment]
It's checking that the values exist before using them.

**Comment by jonas-schievink** [comment]
Is that only needed by gtk-rs, or would all crates benefit? Why or why not?

**Comment by GuillaumeGomez** [comment]
I assume that if we had this issue with gtk-rs, other crates might encounter it as well.

**Comment by jonas-schievink** [comment]
*What* issue though? Is there an upstream issue you can link to? Why is gtk-rs hitting this and (apparently) no other crates?

**Comment by GuillaumeGomez** [comment]
I think it's because we're generating a lot of crates at once, which is rarely done outside (or just locally). 

Another difference is that we generate without crates' docs without minification and then run the minification. However, the process is the same as in rustdoc so chances that it comes from there are quite small.

**Comment by Dylan-DPC** [comment]
oops
r? @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
> I think it's because we're generating a lot of crates at once, which is rarely done outside (or just locally).

What do you mean by "a lot of crates at once"? That sounds to me like a regular `cargo doc` run of any crate with a deep dependency tree, or a workspace with many crates in it (like the compiler).

> Another difference is that we generate without crates' docs without minification and then run the minification. However, the process is the same as in rustdoc so chances that it comes from there are quite small.

In other words, you run your crates' docs with `--disable-minification` except for the last one? (Or do you run some client of the `minifier` crate over it after all the crates have been run?) That sounds like a minifier bug more than a rustdoc bug.

-----

To be clear, the actual change in this PR is small and not even that controversial. What i'm concerned about is that it looked like there was no investigation into what was going on, and that it was framed as a fix specifically for `gtk-rs`. It sets a weird precedent if one of us can shotgun our fixes through without so much as opening an issue (which you usually do for your small changes anyway, but not here) if the bug personally affects our own other projects, but anyone else with large/nonstandard project structures (e.g. rustc, Servo, Fuchsia) has to follow the usual process of opening an issue, contributing to an investigation, and waiting for a PR to open, review, and land.

**Comment by Dylan-DPC** [comment]
ping from triage @QuietMisdreavus what's the status of this?

**Comment by QuietMisdreavus** [comment]
I never heard back from @GuillaumeGomez about what gtk-rs was doing that made this change necessary. I'm convinced this is papering up a different bug in the `minifier` crate, or in rustdoc's handling of it, instead of something the javascript itself would otherwise have to care about.

**Comment by GuillaumeGomez** [comment]
I wasn't able to determine if the bug was coming from rustdoc or my gtk-rs minification process... I can't use a workspace system so I'm stuck with using this fix for the moment.

**Comment by Mark-Simulacrum** [comment]
I'm closing this PR as the relevant procedure should likely be followed here; see https://github.com/rust-lang/rust/pull/59958#issuecomment-483278457. Please reopen once that investigation is conducted and the PR description is updated.

**Pull request closed without merging**
