### PR TITLE
Add function core::iter::zip

### PR DESCRIPTION
**Pull request by cuviper**
This makes it a little easier to `zip` iterators:

```rust
for (x, y) in zip(xs, ys) {}
// vs.
for (x, y) in xs.into_iter().zip(ys) {}
```

You can `zip(&mut xs, &ys)` for the conventional `iter_mut()` and
`iter()`, respectively. This can also support arbitrary nesting, where
it's easier to see the item layout than with arbitrary `zip` chains:

```rust
for ((x, y), z) in zip(zip(xs, ys), zs) {}
for (x, (y, z)) in zip(xs, zip(ys, zs)) {}
// vs.
for ((x, y), z) in xs.into_iter().zip(ys).zip(xz) {}
for (x, (y, z)) in xs.into_iter().zip((ys.into_iter().zip(xz)) {}
```

It may also format more nicely, especially when the first iterator is a
longer chain of methods -- for example:

```rust
    iter::zip(
        trait_ref.substs.types().skip(1),
        impl_trait_ref.substs.types().skip(1),
    )
    // vs.
    trait_ref
        .substs
        .types()
        .skip(1)
        .zip(impl_trait_ref.substs.types().skip(1))
```

This replaces the tuple-pair `IntoIterator` in #78204.
There is prior art for the utility of this in [`itertools::zip`].

[`itertools::zip`]: https://docs.rs/itertools/0.10.0/itertools/fn.zip.html

### CODE REVIEW

**Comment by bluss** [comment]
The main feature is that a free function can have a more permissive trait bound than a method - the method has to have a more specific receiver. The symmetry in the treatment of the two operands contributes to the readability of the code.

- `a.zip(b)`
  - `a` is an iterator and `b` is an iterable
  - `a` is receiver and `b` is a parameter
- `zip(a, b)`
  - symmetry: `a` and `b` are iterable
  - symmetry: `a` and `b` are function parameters
  - (drawback) it's a binary function while zipping but it *"should be"* an n-ary operation with tuples or variadic generics


itertools has these "opinonated" free functions (that I introduced there), and the other one I'd speak for would be `enumerate(iterable)` with similar features to `zip`.

**Comment by cuviper** [comment]
> the other one I'd speak for would be `enumerate(iterable)`

A particular thing I like about that one is that `enumerate(iterable)` matches the order `(index, item)`, whereas `iter.enumerate()` reads backwards to me -- a method at the end which adds something to the front.

**Comment by WaffleLapkin** [comment]
Another way to make zipping `impl IntoIterator`s easier may be adding a `zip` method to `IntoIterator` itself.
```rust
// IntoIterator::zip
for (x, y) in xs.zip(ys) {}

// this or, iter::zip
for (x, y) in zip(xs, ys) {}

// current status
for (x, y) in xs.into_iter().zip(ys) {}
```
I'm not sure what drawback will this bring, just wanted to point out.

**Comment by cuviper** [comment]
@WaffleLapkin 
> Another way to make zipping `impl IntoIterator`s easier may be adding a `zip` method to `IntoIterator` itself.

The blanket `impl<I: Iterator> IntoIterator for I` would make `iter.zip()` ambiguous for current code. That is, every `Iterator` also implements `IntoIterator`, so it would not be clear which trait's `zip` you mean to call.

**Comment by WaffleLapkin** [comment]
@cuviper it would still work though, see this example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0eae1647eca2fa1b091f12c73a579e6

**Comment by jplatte** [comment]
> @cuviper it would still work though, see this example: [play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0eae1647eca2fa1b091f12c73a579e6](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0eae1647eca2fa1b091f12c73a579e6)

Only because of the generic context I think. Counter-example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=437828d53ebe1566ba397e775c41c3be

**Comment by bluss** [comment]
Adding methods on widely implemented traits like `IntoIterator` is incredibly fraught (consider the diversity of data structures that implement it, much more so than for `Iterator`) and I'd argue against adding a `zip` method there - it could also conflict very widely. Take for example the naming collision with Option::zip.

**Comment by cuviper** [comment]
> Take for example the naming collision with Option::zip.

That particular case would be resolved in favor of the inherent method, but I still agree with you in general.

**Comment by m-ou-se** [comment]
Thanks for working on this, @cuviper!

Can you [open a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX)? Thanks!

r=me with the tracking issue added.

cc @rust-lang/clippy: this makes minor changes to the clippy code in [the last commit](https://github.com/rust-lang/rust/pull/82917/commits/e82e8129e728e9202cfae89daa22987cf49c32af).

**Comment by cuviper** [comment]
Added tracking issue #83574.

@bors r=m-ou-se

**Comment by leonardo-m** [comment]
I've tried to use this zip and I find it nearly useless, or in most cases it makes the code worse. A zip macro that takes many arguments could be useful instead, because it avoids the usage of multiple zip methods and the creation of nested tuples. Take a look at itertools for ideas for the most commonly used stuff, don't reinvent the wheel from zero. I'd like functions like sorted(), etc instead.

**Pull request merged**
