### PR TITLE
BTreeMap: Support custom allocators (v1.5)

### PR DESCRIPTION
**Pull request by exrook**
Related:
https://github.com/rust-lang/wg-allocators/issues/7
https://github.com/TimDiekmann/alloc-wg

Blocked on:
~~#77187~~
~~#78459~~ 
~~#95036~~

previous: #77438

### CODE REVIEW

**Comment by RalfJung** [comment]
This introduced an ICE in Miri: https://github.com/rust-lang/rust/issues/98176. The actual bug is probably somewhere else and just uncovered here. But the strange thing is that the ICE does not need custom allocators to be triggered.

**Comment by RalfJung** [comment]
FWIW that might be related to the performance regressions -- this PR will create `Box<T, &System>` boxes, which are twice as big as regular `Box<T>` boxes.

**Comment by TennyZhuang** [comment]
> FWIW that might be related to the performance regressions -- this PR will create `Box<T, &System>` boxes, which are twice as big as regular `Box<T>` boxes.

I guess that this can be fixed by replacing `Box<T, &A>` to `Box<T, A>`, and I'd like to submit a PR to fix this!

**Comment by RalfJung** [comment]
I'm already working on that in https://github.com/rust-lang/rust/pull/98178 -- sorry.

**Pull request merged**
