### PR TITLE
[do not merge] Test mimalloc

### PR DESCRIPTION
**Pull request by Zoxc**
r? @ghost

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 090f4a44679dfd5f618706147f631c44ecebe3f5

**Comment by jonas-schievink** [comment]
No change :(

Maybe updating your fork to include https://github.com/gnzlbg/mimallocator/commit/4c47b66c1e62634561141399705c4a1e89641610 could improve performance? (not sure that would be noticeable though)

**Comment by Zoxc** [comment]
It seems like a minor win. Applying it to LLVM and inlining the fast paths could improve things further.

**Pull request closed without merging**
