### PR TITLE
Revert "Apply EarlyOtherwiseBranch to scalar value #129047"

### PR DESCRIPTION
**Pull request by jieyouxu**
This reverts PR #129047, commit a772336fb3fbd1fe4493077fcfe04e0221296a99, reversing changes made to 702987f75b74f789ba227ee04a3d7bb1680c2309.

cc @DianQK and @cjgillot as the PR author and reviewer of #129047 respectively.

It seems [Apply EarlyOtherwiseBranch to scalar value #129047](https://github.com/rust-lang/rust/pull/129047) may have lead to several nightly regressions:

- https://github.com/rust-lang/rust/issues/130769
- https://github.com/rust-lang/rust/issues/130774
- https://github.com/rust-lang/rust/issues/130771

Example test that would ICE with changes in #129047 (this test is included in this PR):

```rs
//@ compile-flags: -C opt-level=3
//@ check-pass

use std::task::Poll;

pub fn poll(val: Poll<Result<Option<Vec<u8>>, u8>>) {
    match val {
        Poll::Ready(Ok(Some(_trailers))) => {}
        Poll::Ready(Err(_err)) => {}
        Poll::Ready(Ok(None)) => {}
        Poll::Pending => {}
    }
}
```

Since this is a mir-opt ICE that seems to quite easy to trigger with real-world crates being affected, let's revert for now and reland the mir-opt after these are fixed.

### CODE REVIEW

**Comment by fmease** [comment]
Could you perhaps add a regression test (in a separate commit)?

**Comment by jieyouxu** [comment]
> Could you perhaps add a regression test (in a separate commit)?

(I did just before you asked lol)

**Comment by nagisa** [comment]
@bors r+ p=1

Fixing a critical regression, should land ASAP.

**Comment by lqd** [comment]
This is a revert, no investigation needed.

@rustbot label: +perf-regression-triaged

**Pull request merged**
