### PR TITLE
Add a missing fmt::Debug impl lint

### LINKED ISSUE #20855: Add a lint for public types that don't implement Debug
[RFC 504](https://github.com/rust-lang/rfcs/blob/master/text/0504-show-stabilization.md) states that Debug should be implemented for all types, so we should add a lint that warns for types missing an impl.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #20855

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think it's a bit too strong to set the default level to warn for this lint though. We've seen real compile time hits as well as code blow up sizes in the past from just adding `derive(Debug)` to everything. Especially seeing how many crates in the standard distribution are opting out of this lint I think it should be default allow if we're going to have it.

From a library author's perspective it's unfortunate to accidentally leave this out, but it's a backwards compatible change to add one at any time.

**Comment by sfackler** [comment]
I was under the impression that `Debug` was supposed to be implemented for all public types: https://github.com/rust-lang/rfcs/blob/master/text/0565-show-string-guidelines.md#debugging-fmtdebug. Should we be revising that?

I disabled the lint for all of the main rustc crates because I didn't feel like adding hundreds of Debug implementations in this PR.

**Comment by alexcrichton** [comment]
To me that guideline states that all public types should have a `Debug` implementation, but forcing it to be so seems somewhat unnecessary. There are many use cases (such as the hundreds of types in this repo) which don't want to have to have this lint turned one (another being `*-sys` crates for example).

**Comment by sfackler** [comment]
Updated to be allow by default. We may want to set the missing_copy_implementations to default allow as well.

**Comment by alexcrichton** [comment]
I would love to do so for that! It may want to have a separate PR though to prevent entangling the two.

**Comment by sfackler** [comment]
Yeah, for sure.

**Pull request merged**
