### PR TITLE
BTreeMap: detect bulk_steal's count-1 underflow in release builds too

### PR DESCRIPTION
**Pull request by ssomers**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
The title here implies that this is happening on release builds, but I presume you just mean "detect it *if* it happens"?

**Comment by ssomers** [comment]
The `count -1` expression is always evaluated and - as far as I noriced and know - always panics in debug builds when it underflows. Could use `count.checked_sub(1)` or something instead, but that seemed awkward. Could change its meaning to `extra` and start from 0, or change the type to `NonZeroUsize`, but that seemed awkward in the caller.

**Comment by Mark-Simulacrum** [comment]
My question is more so - is this PR caused by a suspicion that this actually happens? It seems fine to me, but I would like to know if this is brought on by something or just seemed like a good idea.

**Comment by ssomers** [comment]
It actually happened to me in experimental code, but it cannot happen in the current code. The callers in split.rs are pretty clear about that.

Which makes me realize now that it's also possible to skip the operation if count == 0, which allows taking `self` by value and getting close to the other steal functions (which are really the same written out for count == 1).

**Pull request merged**
