### PR TITLE
[BETA] Delay formatting trimmed path until lint/error is emitted

### PR DESCRIPTION
**Pull request by compiler-errors**
Backports ~#100310~ #99893
cc #100542
r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
Sorry, noise was due to wrong merge base (master -> beta)

**Comment by compiler-errors** [comment]
Where the heck is the CI

**Comment by pnkfelix** [comment]
[discussed](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-08-18/near/294099398) at T-compiler meeting.

@rustbot label: beta-accepted

**Comment by ehuss** [comment]
Just checking, the PR linked in the description (#100310) doesn't look correct. Is it supposed to be #99893?

**Comment by compiler-errors** [comment]
You're right, oops.

**Comment by ehuss** [comment]
Closing as rolled up in #101221.

@compiler-errors Just a note in terms of process. If a PR just needs a backport, the usual process is to just tag the original PR with `beta-nominated`. Once they are accepted, beta PRs get rolled up.  It's only necessary to create a new PR if the old one does not backport cleanly, and the changes are nontrivial.

**Pull request closed without merging**
