### PR TITLE
add extended information for E0562; impl Trait can only be a return type

### PR DESCRIPTION
**Pull request by zackmdavis**
r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by zackmdavis** [comment]
Appveyor [failure](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.3663/job/7g56sjc7i1q6vllh) is surely spurious (`curl: (18) transfer closed with 6222313 bytes remaining to read`/`Command exited with code 18`).

**Comment by alexcrichton** [comment]
@bors: retry

* git error? https://github.com/rust-lang/rust/issues/42117

**Pull request merged**
