### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #98574 (Lower let-else in MIR)
 - #99011 (`UnsafeCell` blocks niches inside its nested type from being available outside)
 - #99030 (diagnostics: error messages when struct literals fail to parse)
 - #99155 (Keep unstable target features for asm feature checking)
 - #99199 (Refactor: remove an unnecessary `span_to_snippet`)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=98574,99011,99030,99155,99199)

### CODE REVIEW

**Comment by Amanieu** [comment]
This is quite surprising, I wasn't expecting this code to be hot. It's only called at startup, and even then only twice instead of once. I will see if I can change it to only query the LLVM features once.

**Comment by Amanieu** [comment]
It is quite concerning that a whole 5% of the compilation time of "hello world" is just querying LLVM for the list of target features. Perhaps we should consider moving the feature selection logic to rustc in the future.

**Comment by rylev** [comment]
That is surprising. Should we try to capture this in an issue? This is definitely a perf relevant piece of info that would be good to move out of this PR.

**Comment by nnethercote** [comment]
I looked at this `SetImpliedBits` stuff recently. AFAICT, the LLVM API is designed so you can query lots of feature bits at once, via a bitset, and you just get a boolean result indicating if all the feature bits are enabled. But rustc wants to query feature bits one at a time, and x86-64 has lots of features, so `SetImpliedBits` ends up being called 50+ times. It doesn't sound expensive, but helloworld is so fast to compile that it ends up being a non-trivial fraction of execution time.

I couldn't see how rustc could do better given the LLVM API, but I could easily have overlooked something.

**Comment by nnethercote** [comment]
Here are the notes I wrote down at the time:

> Hard to improve. On x86-64 we query ~50 target feature flags, for things like SSE*, AVX*, etc. This is within target_features in compiler/rustc_codegen_llvm/src/llvm_util.rs. We check one flag at a time because the LLVM interface makes it hard to do otherwise, and LLVM is moderately slow to check each one. Even though it’s a significant fraction of execution time for small programs, the absolute time is low, so doesn’t seem worth any further effort.

**Pull request merged**
