### PR TITLE
[beta] Revert #113923

### LINKED ISSUE #118609: 🐛 Symbol multiply defined since nightly-2023-12-02 with custom builtins.
`cargo build --release` fails when building an rp2040 application with `lto=fat`.

### Code

To reproduce:
```sh
git clone https://github.com/ithinuel/sandbox-rp2040 -b rust-regression

cd sandbox-rp2040
cargo build --release
```

I expected to see the project build successfully.

Instead, it fails with:
```
warning: Linking globals named '__addsf3': symbol multiply defined!

error: failed to load bitcode of module "rp2040_hal-99af59d59c714fe0.rp2040_hal.6c650a4395998581-cgu.0.rcgu.o": 

warning: `rust-regression` (bin "rust-regression") generated 1 warning
error: could not compile `rust-regression` (bin "rust-regression") due to 1 previous error; 1 warning emitted
```

### `bisect-rustc`

searched nightlies: from nightly-2023-12-01 to nightly-2023-12-03
regressed nightly: nightly-2023-12-02
searched commit range: https://github.com/rust-lang/rust/compare/87e1447aadaa2899ff6ccabe1fa669eb50fb60a1...8c2b57721728233e074db69d93517614de338055
regressed commit: https://github.com/rust-lang/rust/commit/8c2b57721728233e074db69d93517614de338055

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.7</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2023-12-01 --end=2023-12-03 -vv --target thumbv6m-none-eabi -- build --release 
```
</details>

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### Background

The rp2040 mcu has in-ROM implementation of some builtins. The `rp2040-hal` implements the necessary _magic_ in order to use these rather than the regular compiler-builtins that would otherwise consume flash are induce unecessary execution latency.
See [here](https://github.com/rp-rs/rp-hal/blob/cfd6c128a1688186f419e3bd60ce469ddeb7fb47/rp2040-hal/src/rom_data.rs#L288-L338) for memcpy, memset (and a few other) and [here](https://github.com/rp-rs/rp-hal/tree/cfd6c128a1688186f419e3bd60ce469ddeb7fb47/rp2040-hal/src/float) for float related builtins.

Such magic can be disabled with `--features disable-intrinsics` which allows to build on nightly-2023-12-02 at the cost of flash storage & execution speed.

### initial report

- https://github.com/rp-rs/rp2040-project-template/issues/71

### PR DESCRIPTION
**Pull request by dianqk**
Per [#t-compiler/meetings > [weekly] 2024-01-11](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-01-11) discussion, revert #113923. Also revert associated #118568.

The PR #113923 causes the regression issue #118609. We need more time to find a proper solution.

Discussions start at [412365838](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-01-11/near/412365838) and continue to [412369643](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-01-11/near/412369643).

Fixes #118609.

Same as #119885 but backported to beta.

r? compiler

### CODE REVIEW

**Comment by weihanglo** [comment]
I've created another beta backport PR #120111. Feel free to roll them up :)

**Comment by cuviper** [comment]
Procedural note: we normally deal with backport flags on the master PR, especially because it doesn't show up in the release team's queries until merged. That's kind of a chicken-and-egg situation when you're already targeting beta. Then we may ask for help backporting if there's some conflict, but generally we can handle it. :)

https://forge.rust-lang.org/release/backporting.html

Anyway, no worries, I've verified that this is a clean match of #119885.

@bors r+ rollup=never

**Comment by DianQK** [comment]
> Procedural note: we normally deal with backport flags on the master PR, especially because it doesn't show up in the release team's queries until merged. That's kind of a chicken-and-egg situation when you're already targeting beta. Then we may ask for help backporting if there's some conflict, but generally we can handle it. :)
> 
> https://forge.rust-lang.org/release/backporting.html
> 
> Anyway, no worries, I've verified that this is a clean match of #119885.
> 
> @bors r+ rollup=never

Thanks, I got it. I just need to add the `beta-nominated` to the PR of the target master branch.
(Based on the discussion at the meeting I assumed this was already in `beta-accepted`, so I submitted the PR.)

**Pull request merged**
