### PR TITLE
Update jemalloc to 4.0.3

### PR DESCRIPTION
**Pull request by fbernier**
Follow-up from https://github.com/rust-lang/rust/pull/29196

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 4b51d9ce4c849b1727a0203c264685fd43cd02ad

Thanks!

**Comment by alexcrichton** [comment]
Hm that looks eerily similar to the bug from last time, but perhaps we can retry and see if it shows up twice!

@bors: retry

**Comment by fbernier** [comment]
Nondeterministic failures on Windows when using threads :disappointed: . This is not going to be easy to debug...

**Comment by alexcrichton** [comment]
Closing due to inactivity, but hopefully a future version of jemalloc will fix these issues!

**Pull request closed without merging**
