### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #119199 (Add arm64ec-pc-windows-msvc target)
 - #121416 (Improve error messages for generics with default parameters)
 - #121475 (Add tidy check for .stderr/.stdout files for non-existent test revisions)
 - #121736 (Remove `Mutex::unlock` Function)
 - #121784 (Make the success arms of `if lhs || rhs` meet up in a separate block)
 - #121818 (CFI: Remove unused `typeid_for_fnsig`)
 - #121819 (Handle stashing of delayed bugs)
 - #121828 (Remove unused fluent messages)
 - #121831 (Fix typo in comment)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=119199,121416,121475,121736,121784,121818,121819,121828,121831)

### CODE REVIEW

**Comment by dpaoliello** [comment]
@NobodyXu bumping the cc crate to 1.0.88 may have caused a failure with the arm-android build...

**Comment by NobodyXu** [comment]
Is that relatee to, and could be fixed by rust-lang/cc#983 ?

**Comment by dpaoliello** [comment]
> Is that relatee to, and could be fixed by rust-lang/cc#983 ?

Trying it out: https://github.com/rust-lang/rust/pull/121874

**Comment by dpaoliello** [comment]
@NobodyXu that doesn't fix it

**Comment by dpaoliello** [comment]
1.0.86 has the issue: https://github.com/rust-lang/rust/pull/121872#issuecomment-1974021744
1.0.83 does not: https://github.com/rust-lang/rust/actions/runs/8118668338/job/22193341342?pr=121874
Going to try 1.0.84 next...

**Comment by dpaoliello** [comment]
1.0.84 has the issue: https://github.com/rust-lang/rust/pull/121874#issuecomment-1974151279
Looking at the diff between 83 and 84, this commit seems relevant: https://github.com/rust-lang/cc-rs/commit/53564e00498156c9be00361c4b039952cbf7ff59
I'm going to try building with that commit

**Comment by dpaoliello** [comment]
Using 53564e00498156c9be00361c4b039952cbf7ff59 reproduced the issue: <https://github.com/rust-lang/rust/pull/121874#issuecomment-1974171096>
The previous commit did not have the issue: https://github.com/rust-lang/rust/actions/runs/8145164818/job/22260797425?pr=121874
And reverting 53564e00498156c9be00361c4b039952cbf7ff59 from 1.0.88 also did not have the issue: https://github.com/rust-lang/rust/actions/runs/8145164818/job/22260797425?pr=121874

**Pull request closed without merging**
