### PR TITLE
Reenable debuginfo tests

### PR DESCRIPTION
**Pull request by cbiffle**
These tests were disabled four years ago; it appears that it was
intended to be temporary.

In that time their assertions have rotted. I've gone through and fixed
the assertions where necessary and rehabilitated them. In several cases
I've had to leave lldb disabled, because the lldb output has changed in
ways that I don't understand. I figured gdb coverage was better than no
coverage.

It's worth noting that these tests being enabled would probably have
caught the regression observed in https://github.com/rust-lang/rust/issues/90357.

### CODE REVIEW

**Comment by cbiffle** [comment]
(More context available in #95685, fwiw.)

**Comment by cbiffle** [comment]
Welp. One of these tests appears to segfault gdb under certain circumstances. Guess I'll turn it back off.

```
Check compiletest suite=debuginfo mode=debuginfo (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 136 tests
i........i..i..i.......ii.i........F......i.............iii....ii.......i.......i................... 100/136
Some tests failed in compiletest suite=debuginfo mode=debuginfo host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
..i.................................
failures:

---- [debuginfo-gdb] debuginfo/drop-locations.rs stdout ----
NOTE: compiletest thinks it is using GDB with native rust support

error: compilation failed!
status: signal: 11 (core dumped)
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/debuginfo/drop-locations.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/debuginfo/drop-locations.gdb/a" "-Crpath" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-g" "-O" "-C" "no-prepopulate-passes" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/debuginfo/drop-locations.gdb/auxiliary"
stdout: none
stderr: none



failures:
    [debuginfo-gdb] debuginfo/drop-locations.rs

test result: FAILED. 119 passed; 1 failed; 16 ignored; 0 measured; 0 filtered out; finished in 4.09s
```

**Comment by lcnr** [comment]
hey :wave: is there anything to review right now? If so please comment `r? rust-lang/compiler` to reassign this PR as I don't know much about the state of debug info in Rust.

**Comment by cbiffle** [comment]
Sorry, this is based on another PR that I thought was headed for review. Without it, the tests don't pass. I'll update when that's in.

**Comment by wesleywiser** [comment]
Oh, excellent! I started working on re-enabling many of these as well in #94489 but I haven't had much time lately to work on that. I'm happy to review & approve your changes instead!

r? @wesleywiser

**Comment by cbiffle** [comment]
> Oh, excellent! I started working on re-enabling many of these as well in #94489 but I haven't had much time lately to work on that. I'm happy to review & approve your changes instead!
> 
> r? @wesleywiser

Thanks! The PR to _fix_ the debuginfo generation has been approved, once that's rolled up I'll rebase this and set it to ready (and CC you).

**Comment by camelid** [comment]
triage: Hi @cbiffle, it looks like the fix PR you mentioned has been merged. Is this just in need of a rebase and review?

**Comment by cbiffle** [comment]
> triage: Hi @cbiffle, it looks like the fix PR you mentioned has been merged. Is this just in need of a rebase and review?

Oh hi! Yes, I believe that is correct. Lemme set the ready bit.

**Comment by camelid** [comment]
Hi, I think this might need a rebase first! (Unless you feel that a review first would be helpful.)

Either way, please then post a comment with `@rustbot ready` to mark your PR as ready for a review. This changes the label, which is what reviewers usually look for.

**Comment by JohnCSimon** [comment]
Triage - doesn't seem to be in ready state? Not sure what's causing this
> @[cbiffle](https://github.com/cbiffle) cbiffle marked this pull request as ready for review [last month](https://github.com/rust-lang/rust/pull/95696#event-7114096205)

@rustbot ready - setting it to ready anyway

**Comment by JohnCSimon** [comment]
???
@rustbot ready

**Comment by wesleywiser** [comment]
@cbiffle do you want rebase out [98190b7](https://github.com/rust-lang/rust/pull/95696/commits/98190b716829fd4edbf1b364a1a662de9a9ca7bb) since that was already merged in #95685?

**Comment by JohnCSimon** [comment]
@cbiffle 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
