### PR TITLE
doc: fix swapped docs for intro_ptr and intro_raw of CString

### PR DESCRIPTION
**Pull request by tsurai**
Please correct me if I confused something but the documentation for `into_ptr` and `into_raw` of `CString` seem to be swapped as the docs for `into_ptr` mentions `into_raw` and vice versa.

Update: I actually meant `into_ptr` and `into_raw` NOT `from_*`

### CODE REVIEW

**Comment by bluss** [comment]
Since `from_ptr` is deprecated, both should really say `from_raw`.

**Comment by tsurai** [comment]
I thought that it's better for the deprecated ```from_ptr``` and ```to_ptr``` functions to stay the same for developers to know what they originally did and to avoid confusion.

But do you agree that the documentation as it is now is inconsistent? Especially considering the documentation of ```to_ptr``` and ```to_raw```.
I can change the documentation to always refer to the ```*_raw``` functions if you think it's better that way.

**Comment by bluss** [comment]
I think it's better. Either way, the unstable & deprecated methods will be removed relatively quickly.

**Comment by tsurai** [comment]
There certainly is no reason why the ```from_raw``` method should only mention ```from_ptr``` in its documentation. Especially when the deprecated methods get removed.

**Comment by bluss** [comment]
@bors r+ rollup

Great, let's go!

**Pull request merged**
