### PR TITLE
update Miri

### LINKED ISSUE #94687: `miri` no longer builds after rust-lang/rust#94597
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#94597, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @nnethercote, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/94687
r? @rust-lang/miri

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
can r+ if needed, unless you want a detalied review

**Comment by RalfJung** [comment]
Thanks! We usually self-r+ tool updates, at least for Miri. I thought by putting in `r? @rust-lang/miri` I could prevent it from annoying others unnecessarily but highfive didn't play along...

**Comment by Dylan-DPC** [comment]
no worries :)

**Pull request merged**
