### PR TITLE
Add method Result::into_ok

### LINKED ISSUE #61695: Tracking issue for `Result::into_ok`
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/issues/61695)*

This is (now) a tracking issue for 
https://doc.rust-lang.org/nightly/std/result/enum.Result.html#method.into_ok
https://doc.rust-lang.org/nightly/std/result/enum.Result.html#method.into_err
`#![feature(unwrap_infallible)]`

---

I would like to propose adding a `unwrap_infallible` associated function to `core::result::Result`. The purpose is to convert `Result<T, core::convert::Infallible>` to a `T`, as the error case is impossible.

The implementation would basically be:

```rust
impl<T> Result<T, Infallible> {
    #[inline]
    pub fn unwrap_infallible(self) -> T {
        match self {
            Ok(value) => value,
        }
    }
}
```

An example use-case I have is a wrapper type with generic value verification, like `Handle<T:Verify>`. Some verifications can fail, but some can not. When verification is infallible, a `Result<Handle<T>, Infallible>` will be returned.

Since some can fail, the `Handle` type implements `TryFrom` and not `From`. Because of the blanket implementation of `TryFrom` for all types implementing `From`, I can't additionally add a `From` conversion for the infallible cases. This blanket implementation makes sense, as it allows an API to take a `T: TryFrom` and handle all possible conversions, even infallible ones.

But for the API consumer it would be beneficial to be able to go from an infallible `Result<T, Infallible>` to a plain `T` without having to manually match or use `expect`. The latter is shorter and chainable, but has the disadvantage that it will still compile when the types are changed and the conversion is no longer infallible.

It might be that there is a different solution to infallible conversions via `TryFrom` in the future, for example via specialization. I believe that having an `unwrap_infallible` would still be beneficial in many other cases where generically fallible actions can be infallible in certain situations. One example is when working with a library that is based on fallible operations with a user supplied error type, but where the specific implementation from the user is infallible.

I'd be happy to work on a PR for this if it's acceptable to add, though I might require some guidance with regards to stability attributes, feature flags and so on. It's a bit hard to find information on that, and experimentation is costly as it takes me a while to complete a `./x.py test src/libcore` :)

### PR DESCRIPTION
**Pull request by mzabaluev**
Implementation of https://github.com/rust-lang/rfcs/pull/2799

Tracking issue #61695

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage:
@sfackler  Can you please review this PR?
CC: @mzabaluev 

Thanks!

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Comment by JohnCSimon** [comment]
Ping from triage - this PR is still waiting on review:
cc: @Kimundi @KodrAus @SimonSapin @sfackler @mzabaluev 
Thanks.

**Comment by SimonSapin** [comment]
I’ve changed the PR description to not close #61695 since that is to become the tracking issue.

**Comment by JohnCSimon** [comment]
Ping from triage - @sfackler this looks like it's still waiting on a merge

**Comment by sfackler** [comment]
It is still waiting on one of @Kimundi, @KodrAus, or @withoutboats to complete the FCP process.

**Comment by mzabaluev** [comment]
`never_type` has been stabilized since this branch was first submitted. I have rebased and removed the `feature(never_type)` crate attributes from tests.

**Comment by MikailBag** [comment]
Maybe it is too late, but maybe feature should be renamed too (e.g. to `result_into_ok`)?

**Comment by mzabaluev** [comment]
The rebased branch is mergeable and the code currently compiles. Does anything else need to be done to remove S-waiting-on-author?

**Pull request merged**
