### PR TITLE
Still more `ObligationForest` improvements.

### PR DESCRIPTION
**Pull request by nnethercote**
Following on from #64627, more readability improvements, but negligible effects on speed.

r? @nikomatsakis

### CODE REVIEW

**Comment by nnethercote** [comment]
This is the end of my spate of `ObligationForest` changes. I didn't manage to get rid of the `memcpy`s caused by the `swap` calls within `compress`, which was the original motivation for looking into `ObligationForest`. (Well... not without (a) regressing performance, (b) causing test failures, or (c) using `unsafe`.) `drain_filter()` is the right fit conceptually, but caused a slowdown in practice :(

**Comment by pnkfelix** [comment]
@nnethercote what sort of test failures were you observing from (b) above?

Are we talking about injecting unsoundness bugs into compiler? Or changes to diagnostic output? Or something else?

**Comment by nnethercote** [comment]
> Are we talking about injecting unsoundness bugs into compiler? Or changes to diagnostic output? Or something else?

They were all changes in error messages that arose from changing the order of pending obligations. Some of them looked pretty trivial (e.g. change the order of two errors) but some of them were more complex, to the point where I was struggling to tell if the new messages were as valid as the old ones. And there were quite a few in the latter basket. So I ended up preserving the order because the potential speed benefits of reordering were small.

**Comment by nnethercote** [comment]
The test failures on automation are trivial; some vectors of erroneous obligations have changed order, but (AIUI) the order is not significant. I will fix those on Monday.

**Comment by nnethercote** [comment]
I fixed the test failures and rebased. Ready for review, @nikomatsakis!

**Review by nikomatsakis — APPROVED** [review]

**Pull request merged**
