### PR TITLE
Make sure #47772 does not regress

### PR DESCRIPTION
**Pull request by RalfJung**
Mostly to make my life in https://github.com/rust-lang/rust/pull/52206 harder.^^

Or should I just add that test there?

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ rollup

Either way's fine!

**Comment by RalfJung** [comment]
@bors r-

This is failing CI on Windows:
```
C:\projects\rust\build\x86_64-pc-windows-gnu\test\codegen\slice-position-bounds-check\slice-position-bounds-check.ll:13:233: error: CHECK-NOT: string occurred!
define zeroext i1 @position_no_bounds_check([0 x i32]* noalias nonnull %y.0, i64 %y.1, i32* noalias nocapture readonly dereferenceable(4) %x, i32* noalias nocapture readonly dereferenceable(4) %z) unnamed_addr #0 personality i32 (%"panic_unwind::windows::EXCEPTION_RECORD"*, i8*, %"panic_unwind::windows::CONTEXT"*, %"panic_unwind::windows::DISPATCHER_CONTEXT"*)* @rust_eh_personality {
                                                                                                                                                                                                                                        ^
C:\projects\rust\src/test\codegen\slice-position-bounds-check.rs:28:16: note: CHECK-NOT: pattern specified here
 // CHECK-NOT: panic
               ^
```
Does this mean that the function *does* panic on Windows, or that Windows IR contains the string "panic" for other reasons?

Anyway I do not even have access to a Windows machine, so the best thing I could so is make the test `// ignore-windows` and hope that this works on codegen tests. Any other suggestions?

**Comment by RalfJung** [comment]
Okay I think this should help, thanks @eddyb

**Pull request merged**
