### PR TITLE
rustdoc: Rename internal API fns to `into_string`

### PR DESCRIPTION
**Pull request by tesuji**
to avoid surprising listed in API guidelines.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]
Thanks!

**Comment by ollie27** [comment]
@bors r-

failed on CI:

```
error[E0599]: no method named `to_string` found for struct `html::markdown::MarkdownHtml<'_>` in the current scope
    --> src/librustdoc/html/render.rs:2334:18
     |
2334 |                   .to_string()
     |                    ^^^^^^^^^ help: there is an associated function with a similar name: `into_string`
     | 
    ::: src/librustdoc/html/markdown.rs:73:1
     |
73   | / pub struct MarkdownHtml<'a>(
74   | |     pub &'a str,
75   | |     pub &'a mut IdMap,
76   | |     pub ErrorCodes,
77   | |     pub Edition,
78   | |     pub &'a Option<Playground>,
79   | | );
     | |  -
     | |  |
     | |  method `to_string` not found for this
     | |__doesn't satisfy `_: std::fmt::Display`
     |    doesn't satisfy `_: std::string::ToString`
     |
     = note: the method `to_string` exists but the following trait bounds were not satisfied:
             `html::markdown::MarkdownHtml<'_>: std::fmt::Display`
             which is required by `html::markdown::MarkdownHtml<'_>: std::string::ToString`

error: aborting due to previous error

```

**Comment by GuillaumeGomez** [comment]
@ollie27 Thanks for catching it up!

**Comment by lzutao** [comment]
Tests passed locally. Sorry for the inconveniences.

**Comment by GuillaumeGomez** [comment]
I'll wait for the CI this time. :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
