### PR TITLE
Remove libc from MSVC targets

### PR DESCRIPTION
**Pull request by saethlin**
@ChrisDenton started working on a project to remove libc from Windows MSVC targets. I'm completing that work here.

The primary change is to cfg out the dependency in `library/`. And then there's a lot of test patching. Happy to separate this more if people want.

### CODE REVIEW

**Comment by saethlin** [comment]
@ChrisDenton Is there anything else that needs to be done to remove libc from MSVC targets? I feel like this was almost too easy.

**Comment by ChrisDenton** [comment]
There's also #123976.

Also I found the std_detect crate is pulling in libc even if unused. See std uses the default features "std_detect_file_io", and "std_detect_dlsym_getauxval" https://github.com/rust-lang/rust/blob/0e15f5ee8fb3f9edcb8a35b1cbd9f8d352be54a0/library/sysroot/Cargo.toml#L14

Which in the std-detect crate enables the libc feature which in turn enables the libc dependency: https://github.com/rust-lang/stdarch/blob/7df81ba8c3e2d02c2ace0c5a6f4f32d800c09e56/crates/std_detect/Cargo.toml#L37

However, libc isn't used for those two features on Windows (it is currently used for a third, not default enabled. feature). But I'm not sure how to have a dependency enabled when it's both feature and target specific.

**Comment by ChrisDenton** [comment]
Rebasing on this PR and excluding libc from std_detect I'm still seeing the following UI test failures:

```
failures:
    [ui] tests\ui\attributes\unix_sigpipe\unix_sigpipe-inherit.rs
    [ui] tests\ui\attributes\unix_sigpipe\unix_sigpipe-not-used.rs#without_feature
    [ui] tests\ui\attributes\unix_sigpipe\unix_sigpipe-not-used.rs#with_feature
    [ui] tests\ui\attributes\unix_sigpipe\unix_sigpipe-sig_dfl.rs
    [ui] tests\ui\attributes\unix_sigpipe\unix_sigpipe-rustc_main.rs
    [ui] tests\ui\attributes\unix_sigpipe\unix_sigpipe-sig_ign.rs
    [ui] tests\ui\error-codes\E0259.rs
    [ui] tests\ui\feature-gates\rustc-private.rs
    [ui] tests\ui\foreign\foreign-fn-linkname.rs
    [ui] tests\ui\foreign\foreign2.rs
    [ui] tests\ui\imports\issue-37887.rs
    [ui] tests\ui\lint\unnecessary-extern-crate.rs
    [ui] tests\ui\meta\no_std-extern-libc.rs
    [ui] tests\ui\process\no-stdio.rs
    [ui] tests\ui\runtime\stdout-during-shutdown.rs
    [ui] tests\ui\wait-forked-but-failed-child.rs
```

**Comment by saethlin** [comment]
Ah-ha! That makes more sense.

**Comment by saethlin** [comment]
Now we should be down to
```
    [ui] tests\ui\foreign\foreign2.rs
    [ui] tests\ui\imports\issue-37887.rs
    [ui] tests\ui\runtime\stdout-during-shutdown.rs
    [ui] tests\ui\wait-forked-but-failed-child.rs
```
These tests are all pretty unix-y, but I'm going to educate myself a bit and see if there's a way to make a windows equivalent in some cases.

**Review by ChrisDenton — APPROVED** [review]
LGTM. Though removing `regions-mock-tcx` might require compiler approval? I've no idea what that test was trying to do. Or more to the point, why it was doing what it does.

**Comment by compiler-errors** [comment]
Why was regions-mock-tcx removed in the first place?

I'm generally fine with removing it (was added a Long time ago: https://github.com/rust-lang/rust/commit/f4f4a35b5b1fe54b05b2dac3428c55ef2d3923b1#diff-1f35cd44172fbe59c9c9fa0902a448a6d0d1c97304f840e2e272396d5a671413) but mostly want to know why

**Comment by saethlin** [comment]
> Why was regions-mock-tcx removed in the first place? Like what does that have to do with libc and MSVC targets?

I think I made it fail to build at some point... but I can't see why now. So maybe it's fine? Anyway, we should know pretty quickly.

**Comment by ChrisDenton** [comment]
Thanks! Let's see if the full CI is happy.

@bors r+

**Comment by saethlin** [comment]
Fix for the nomicon: https://github.com/rust-lang/nomicon/pull/450

**Pull request merged**
