### PR TITLE
Fix `improper_ctypes` fallout

### LINKED ISSUE #27263: Error compiling for armv7-apple-ios
This is 607f74df2ad6b6fb32ce5b862a9e48a8c4afdad2.

~~~
rustc: x86_64-apple-darwin/stage2/lib/rustlib/armv7-apple-ios/lib/libstd
warning: dropping unsupported crate type `dylib` for target `armv7-apple-ios`
../src/libstd/rand/os.rs:215:43: 215:52 error: found zero-size struct in foreign module, consider adding a member to this struct, #[deny(improper_ctypes)] on by default
../src/libstd/rand/os.rs:215         fn SecRandomCopyBytes(rnd: *const SecRandom,
                                                                       ^~~~~~~~~
error: aborting due to previous error
make: *** [x86_64-apple-darwin/stage2/lib/rustlib/armv7-apple-ios/lib/stamp.std] Error 101
[2] sirver@raph(git)-[master] > mvim ../src/libstd/rand/os.rs
~~~

### PR DESCRIPTION
**Pull request by tamird**
Fixes #27263.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 847fba0

Thanks!

**Comment by tamird** [comment]
Failed on git, needs a retry

**Pull request merged**
