### PR TITLE
Stabilize `std::hint::unreachable_unchecked`.

### LINKED ISSUE #43751: Tracking issue for `mem::unreachable`

### PR DESCRIPTION
**Pull request by kennytm**
Closes #43751.

### CODE REVIEW

**Comment by lukaslueg** [comment]
Maybe the docs should point out that undefined behaviour can occur if runtime *could* reach the point that was marked `unreachable_unchecked`, not just *if*. That is, the program might behave weirdly even if it does not reach the `unreachable` part, because the compiler made assumptions somewhere else.

It's a nuance in wording, yet people have been banging their heads with "catching" code reaching `unreachable` parts while debugging random segfaults: It's spooky action at a distance.

**Comment by rkruppe** [comment]
It's certainly worth reminding people of that since it's often not untuitive, but I want to be clear that this is not specific to `unreachable`: *all* Undefined Behavior is "time travelling" in the sense that a program that eventually executes UB has never had any meaning to begin with and thus implementations don't have to try and faithfully implement the part of the program trace before the UB operation. This is worth stressing, but if it's stressed in the documentation of one particular function, the docs should be careful to not imply that this is *specific* to said function.

**Comment by pietroalbini** [comment]
Ping from triage @sfackler! This PR needs your review!

**Pull request merged**
