### PR TITLE
[breaking batch] don't glob-export `syntax::abi` enums

### PR DESCRIPTION
**Pull request by oli-obk**
r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
While we're at it, should we also un-batch export `TyFoo` and `ExprBar` and friends from AST/HIR?

**Comment by Manishearth** [comment]
cc @erickt heads up

**Comment by oli-obk** [comment]
I'm creating a bunch of these PRs, then you can roll them up. Feels free to open an issue with checkboxes of things that should be done, in an order that your prefer.

**Comment by Manishearth** [comment]
Nah, this works

**Comment by Manishearth** [comment]
r+ on this one

**Comment by bluss** [comment]
Should it have the ususal `[breaking-change]` marker in the commit log or PR message? That's the usual marker.

**Comment by Manishearth** [comment]
the [breaking-batch] is for batching up breaking libsyntax changes

**Comment by bluss** [comment]
Is this a breaking change in the usual sense of `[breaking-changes]`? Then it should have that tag.

**Comment by Manishearth** [comment]
Well, breaking libsyntax. Not sure if that qualifies as breaking; since many compiler changes break internals and we don't mark that as breaking either.

**Comment by oli-obk** [comment]
I'll mark it. `Abi` can show up in compiler plugins

**Comment by oli-obk** [comment]
merged into #31487

**Pull request closed without merging**
