### PR TITLE
Stabilize `const_caller_location` and `const_location_fields`

### LINKED ISSUE #76156: Tracking Issue for const_caller_location
This is a tracking issue for the const part of RFC 2091: track_caller (rust-lang/rfcs#2091).
The feature gate for the issue is `#![feature(const_caller_location)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps
- [x] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

https://github.com/rust-lang/rust/pull/72445

### LINKED ISSUE #102911: Tracking Issue for `const_location_fields`
Feature gate: `#![feature(const_location_fields)]`

This is a tracking issue for `core::panic::Location` methods as `const` functions.

### Public API

```rust
// core::panic::location
impl Location {
    pub const fn file(&self) -> &str;
    pub const fn line(&self) -> u32;
    pub const fn column(&self) -> u32;
}
```

### Steps / History

- [x] Implementation: #101030 
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

### PR DESCRIPTION
**Pull request by lilasta**
Closes #102911. Closes #76156.

tests: [library/core/tests/panic/location.rs](https://github.com/rust-lang/rust/blob/3521a2f2f317cb978063842485c7d1bc86ec82b6/library/core/tests/panic/location.rs)

API:
```rust
// core::panic::location
impl Location {
    pub const fn caller() -> &'static Location<'static>;
    pub const fn file(&self) -> &str;
    pub const fn line(&self) -> u32;
    pub const fn column(&self) -> u32;
}
```

### CODE REVIEW

**Comment by jhpratt** [comment]
This still needs FCP.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting today. We are happy to const-stabilize these methods, but this should happen alongside the const-stabilization of `Location::caller`, not separately.

**Comment by Amanieu** [comment]
FCP started in #76156.

**Comment by Amanieu** [comment]
FCP has finished, this PR should be changed to also stabilize const_caller_location.

**Comment by slanterns** [comment]
Isn't it already included in the PR?

**Review by dtolnay — APPROVED** [review]
Thank you!

**Pull request merged**
