### PR TITLE
Avoid cloning a collection only to iterate over it

### PR DESCRIPTION
**Pull request by kadiwa4**
@rustbot label: +C-cleanup

### CODE REVIEW

**Comment by compiler-errors** [comment]
Gonna do a perf run on this, if it's perf-sensitive then let's leave it as rollup=never, otherwise we can make it rollup=maybe

@bors try @rust-timer queue

**Comment by compiler-errors** [comment]
(i'm doing this because the rollup=iffy list is super long and it's probably not getting any shorter)

**Comment by compiler-errors** [comment]
Secondary regressions are outweighed by primary and secondary improvements.

@bors r=cjgillot rollup=never

**Comment by nnethercote** [comment]
`html5ever-0.26.0` has been noisy recently, so I think those numbers can be ignored. The `doc` improvements for `webrender`, `syn` and `regex` look like they're real, because they were seen on both perf runs. The other changes are iffy, may just be noise.

**Pull request merged**
