### PR TITLE
rustdoc: align stability badge to baseline instead of bottom

### PR DESCRIPTION
**Pull request by notriddle**
| desc | img |
|------|-----|
| before | image |
| | |
| after | image |

Preview: http://notriddle.com/notriddle-rustdoc-demos/stab-baseline/test_dingus/index.html

Based on comment from https://github.com/rust-lang/rust/pull/105509#discussion_r1044816673

r? @joshtriplett

### CODE REVIEW

**Comment by fbstj** [comment]
duplicate of #105509 ?

**Comment by Antikyth** [comment]
This seems sensible to me.  A very minor change in the alignment of the stability badge, single line changing the `vertical-align` CSS attribute to `baseline`.

**Comment by workingjubilee** [comment]
Would you rebase this, please?

**Comment by workingjubilee** [comment]
Thanks!

@bors r+

**Comment by GuillaumeGomez** [comment]
Please don't approve other teams code.

@bors r-

**Comment by workingjubilee** [comment]
Hokay!

Normally I avoid doing so, the PR in question merely seemed _spectacularly_ inoffensive (the style doesn't actually have much effect due to other css changes, unfortunately) and it had been sitting for... 230 days ish?

r? rustdoc

**Comment by GuillaumeGomez** [comment]
There are two approaches to this problem and it's one of the two PRs for it. But at least you brought it back to our attention so we'll discuss it in the next meeting.

**Comment by GuillaumeGomez** [comment]
Thanks for the improvement!

@bors r+

**Pull request merged**
