### PR TITLE
impl Sum/Product for more types, to avoid overflow/panic

### PR DESCRIPTION
**Pull request by liigo**
Currently, `Iterator::sum()` maybe likely overflow, and panic:

```rust
    let values = [126u8, 127, 128];
    let sum: u8 = values.iter().sum(); // panicked at 'attempt to add with overflow'
    println!("sum = {}", sum);
```

That is, the sum of `u8` values, may be likely out of range of type `u8`.

----

One of the possible solutions is, giving users the chance of selecting the return-type of `Iterator::sum()` and/or `Sum::sum()`:
```rust
let sum: u64 = values.iter().sum(); // returns `u64`, no overflow/panic
```
or
```rust
let sum = values.iter().sum::<u64>(); // returns `u64`, no overflow/panic
```

That's what this PR does.

- Implements `Sum<u64>` for `u8` `u16` `u32` and their borrowed and wrapping types
- Implements `Sum<i64>` for `i8` `i16` `i32` and their borrowed and wrapping types
- Implements `Sum<f64>` for `f32` and `&f32`

The same occurs to `Product<_>`.

By doing this, we may avoid most (but not all) overflow/panic.

----

Drawbacks: add many more trait-impls to libcore/libstd.
Unresolved questions: add more impls about `usize` `isize`?

### CODE REVIEW

**Comment by liigo** [comment]
Per "Obvious API hole patch" in [libs changes](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md), I don't think we need an RFC here. Please let me know if I'm wrong.

**Comment by ollie27** [comment]
It's an interesting idea but we can already do `let sum: u64 = values.iter().map(|&x| u64::from(x)).sum();` so I'm not sure this is worth it.

**Comment by alexcrichton** [comment]
The addition of the `Wrapping` impls looks good to me, but the implicit conversions I think we'll want to hold off on for now (to be conservative). Could those be extracted to a separate PR if still necessary?

**Comment by liigo** [comment]
I've removed wrapping impls from this PR.  @alexcrichton

**Comment by alexcrichton** [comment]
Ah ok so to me at least these impls were the more controversial ones. We currently don't do a lot of conversion like this unless it's infallible, and I'm not sure if this is the place to start doing so. Is this super common though? Does something like this happen quite a lot?

cc @rust-lang/libs

**Comment by liigo** [comment]
Oops, I misread your words, @alexcrichton , sorry!
But the non-`Wrapping` impls are more useful than `Wrapping` ones, IMHO.

**Comment by aturon** [comment]
@alexcrichton 

> We currently don't do a lot of conversion like this unless it's infallible

I may be confused, but I believe this PR is allowing you to do things like sum a collection of `u8` values into a `u64` value to avoid overflow -- which should always be safe. And we have similar `From` conversions already. I'm 👍 on the PR. Note that this is an insta-stable change.

Can you elaborate on your concern?

**Comment by alexcrichton** [comment]
@aturon oh I think I misinterpreted what was happening, it looks like overflow is handled as it usually is, so in that sense seems fine to me.

@rfcbot fcp merge

**Comment by ollie27** [comment]
We don't do this kind of widening elsewhere, for example you can't do `let x: u64 = 255u8 + 255u8;`, so why is it appropriate here?

This only saves writing `.map(u64::from)`or `.map(|&x| u64::from(x))`, is this a common thing to do?

Why is this only implemented for this small set of types? Why not sum `u8`s to a `u32` or even `i32`?

**Comment by Kimundi** [comment]
I share @ollie27's concerns - the addition itself is fine on its own, but the widening seems inconsistent with the behavior of the existing operator impls, without enabling any new semantic.

**Comment by liigo** [comment]
@ollie27

> This only saves writing `.map(u64::from)` or `.map(|&x| u64::from(x))`

`.sum()` only saves writing `.fold(0, |a,b| a+b)`. This is not an enough reason to not provide `.sum()`. We should try to make things *easier*, and *better*.

> you can't do `let x: u64 = 255u8 + 255u8;`

I'd propose `impl Add<u8> for u64`, so you can do `let x = 255u8 as u64 + 255u8;`. That's another orthogonal topic, which involves **many** `Add/Mul/…` impls.

**Comment by liigo** [comment]
> Why is this only implemented for this small set of types? Why not sum u8s to a u32 or even i32?

Too many trait impls involves here. I hesitated.

**Comment by aturon** [comment]
Hm, on reflection, I agree with @ollie27 and @Kimundi's concern. While I'm very interested in adding implicit widening for ergonomics, it's best that this be done in a wholesale/considered way, rather than just in certain APIs.

I'd *love* to see an RFC proposing implicit widening in general (as well as navigating the [tradeoffs](https://internals.rust-lang.org/t/implicit-widening-polymorphic-indexing-and-similar-ideas/1141) and perhaps offering an opt-out).

**Comment by liigo** [comment]
ok, closing. waiting for an rfc.

**Pull request closed without merging**
