### PR TITLE
Revert "Stop git from merging generated files"

### PR DESCRIPTION
**Pull request by RalfJung**
This reverts https://github.com/rust-lang/rust/pull/133851. "-merge" makes git not even do merges if they are entirely conflict-free, which is not the behavior we want. We sometimes have conflict-free merges in generated files and it's much better if git can handle them automatically.

r? @oli-obk 
Cc @jieyouxu @Urgau

### CODE REVIEW

**Comment by jieyouxu** [comment]
Ah, that's unfortunate... Thanks for the revert.

**Comment by jyn514** [comment]
i think we could achieve the goal of oli’s original PR by using a custom merge driver: https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-String-1

(in this case it would probably be a simple script that uses `git merge -X theirs` or something like that)

**Comment by jieyouxu** [comment]
> Spurious MSVC thing again.

(@RalfJung btw, we're now tracking msvc and mingw failures in case they have different root causes, there's a separate `CI-spurious-fail-mingw` label now)

**Pull request merged**
