### PR TITLE
Implement Borrow<T> and BorrowMut<T> for Box<T: ?Sized>

### PR DESCRIPTION
**Pull request by bluss**
Implement Borrow<T> and BorrowMut<T> for Box<T: ?Sized>

### CODE REVIEW

**Comment by bluss** [comment]
r? @aturon 

This change seems logical, it allows the `Box<[T]>` analogue of `Vec<T>`.

Question is of course, if it is a breaking change in any way, or if it's simple to introduce?

**Comment by alexcrichton** [comment]
I would be ok with these trait implementations, but a [recent change](https://github.com/rust-lang/rust/pull/26008) to add a `AsRef` implementation to a core pointer type ended up [causing a regression](https://github.com/rust-lang/rust/issues/26096), so I'm somewhat hesitant about this.

I believe, however, that `borrow` and `borrow_mut` are rarer inherent methods, so I think this would be ok.

**Comment by brson** [comment]
I'll run this through crater.

**Comment by aspiwack** [comment]
I guess that if I have a `x:Box<A>` with `A:Borrow<B>`, then `x.borrow()` will be `&A` instead of `&B` just like in #26096 above.

At any rate, I precipitated this pull request by enquiring about `Box<A>` not implementing `Borrow<A>` on irc. In my intuition, `Box` and `Rc` are very similar, and I don't see any reason for them not to implement the same trait (apart from the obvious ones). Was that a design choice?

**Comment by bluss** [comment]
It's a breaking change but a minor change. I expected no trouble, but I understand the situation is the same. I think for our Map collections it can't break anything, it will only allow more types to use `.get()`.

@brson Bringing out crater is great, but I didn't think this was such high stakes :smile:

**Comment by alexcrichton** [comment]
triage: beta-accepted pending merging plus a crater run

**Comment by brson** [comment]
No regressions. https://gist.github.com/brson/1e14d7129c7d3c770b52

**Comment by bluss** [comment]
@brson 998 unknown crates though?

**Comment by brson** [comment]
@bluss Ugh, idk what happened. I'll run it again.

**Comment by brson** [comment]
OK, now it's run, still looks good https://gist.github.com/brson/1e14d7129c7d3c770b52

**Comment by bluss** [comment]
Yes, no impact whatsoever on crater, great!

**Comment by alexcrichton** [comment]
@bors: r+ 4fdb4cfa896232a2a2beb9d1eace922402b98082

Thanks @brson!

**Pull request merged**
