### PR TITLE
Ensure PATH does not contain invalid character `"`

### LINKED ISSUE #34959: rustbuild should warn on quotes in PATH
I have had two people already get an ambiguous `failed to execute command: The system cannot find the file specified.` error when running rustbuild, and both times it was determined to be as a result of quotes in their `PATH`. Rustbuild should detect this ahead of time and warn/error.

cc @alexcrichton

### PR DESCRIPTION
**Pull request by aravind-pg**
Fixes #34959. Note that I'm not sure if panicking is the right thing to do here.

r? @alexcrichton cc @retep998

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you add a comment with some of the rationale (and perhaps a link to) #34959 as well?

**Comment by aravind-pg** [comment]
Done.

**Comment by alexcrichton** [comment]
@bors: r+ 2bb735a1302c8132085c8d54dfbeab99abc84648

Thanks!

**Comment by retep998** [comment]
Also it might help if you wrap that check in `if cfg!(windows)` to ensure it only is checked on Windows.

**Comment by alexcrichton** [comment]
Ah the failure here looks to be legitimate. @aravind-pg you can test this out via `./configure --enable-rustbuild && make`

**Comment by aravind-pg** [comment]
Ah my bad, I really should've checked that. Two questions at this point:
- What if the PATH isn't valid unicode (seems like it can happen legitimately on Windows) and we're not able to obtain it as an `&str` (i.e. `OsStr::to_str` returns None)? Do we allow this, give up on the `contains("\"")` check and continue, or do we bail out and panic?
- Do we want to wrap this in an `if cfg!(windows)` as per @retep998's suggestion? Seems to me this is a useful check in general, but I may be wrong.

**Comment by retep998** [comment]
@aravind-pg It is Windows which has issues with quotes in `PATH`. Other platforms have their own rules for how `PATH` is structured and which characters are allowed and so on, so this really is Windows specific.

**Comment by aravind-pg** [comment]
Ah I see, thanks for clarifying. Any thoughts on my first question?

**Comment by retep998** [comment]
@aravind-pg Probably could use `OsStr::to_string_lossy` and then check that.

**Comment by aravind-pg** [comment]
Good idea! Just updated to use `if cfg!(windows)` and `to_string_lossy`.

**Comment by alexcrichton** [comment]
@bors: retry force clean

* restarted buildbot

**Comment by alexcrichton** [comment]
Having a lot of trouble with @bors right now unfortunately, I'm gonna close this for now to see if it fixes things but I hope to reopen shortly thereafter.

**Comment by alexcrichton** [comment]
Sorry it looks like @bors is super confused by this PR. @aravind-pg would you be ok resubmitting as a new PR?

**Comment by aravind-pg** [comment]
Sure thing, no problem.

**Pull request closed without merging**
