### PR TITLE
Make `str` indexing generic on `SliceIndex`.

### LINKED ISSUE #55603: Implement `Index` for `SliceIndex` types for `str`
While writing a generic implementation today, I was surprised that you can't do `s[i]` for `i: SliceIndex<S>`, if `s` is of slice type `&S`. Doing `s.get(i).unwrap()` is an easy enough workaround, but feels really bad. Replacing the various explicit impls with one for `SliceIndex` would feel much nicer.

### PR DESCRIPTION
**Pull request by alercah**
Fixes #55603

### CODE REVIEW

**Comment by kennytm** [comment]
Could you revert the formatting or split it into a separate commit? It is hard to review what is actually changed.

**Comment by alercah** [comment]
My bad; my editor's autoformat must have snuck back on when I wasn't paying attention.

**Comment by alercah** [comment]
Fixed, with some slight UX improvements too.

**Comment by alercah** [comment]
One more round of test failure fixes. @kennytm this should be ready for review.

**Comment by sfackler** [comment]
@bors r+

Thanks!

**Pull request merged**
