### PR TITLE
Remove `generic_associated_types_extended` feature gate

### PR DESCRIPTION
**Pull request by compiler-errors**
This PR retires nightly support for the `generic_associated_types_extended` feature. This feature hasn't received much attention in the last two years or so, and I believe the feature still remains both unsound and ICEy to use. I think that if we were to redesign and reimplement it, we'd want to first figure out how to implement it soundly, but in the mean time I'd prefer to clean this up.

r? @lcnr cc @jackh726 who added this feature gate I think

### CODE REVIEW

**Review by jackh726 — APPROVED** [review]
This is fine by me - this was really only meant for experimentation, but I never had much time to dig into this.

However, I do think that there should be an open issue to track the general pattern here that we want to solve (there may be only), and that at least some of the tests modified here should reference that with `known-bug`.

**Comment by jackh726** [comment]
Well, I guess that's one issue. But there is also the error in `tests/ui/generic-associated-types/extended/lending_iterator.rs` where we think the impl has stricter requirements than the trait. (There is also the more general implied bounds issue, but I don't think any of these tests are directly related to that.)

**Comment by compiler-errors** [comment]
Added a known-bug for the subtle impl/trait compatibility bug. I don't think a tracking issue for object-safe GATs is super necessary, though I guess if you disagree feel free to open one.

**Comment by dhardy** [comment]
> Sure, I can open an issue about having GATs in dyn-compatible traits.

https://github.com/rust-lang/rust/issues/81823 is related, though reads more like a (diagnostic) bug report than a feature tracker.

Personally I'd love to see support for dyn-compatible GATs with lifetime parameters.

**Pull request merged**
