### PR TITLE
Support `use *;` and `use ::*;`.

### LINKED ISSUE #31484: Cannot glob import the crate root.
The following does not compile.
```Rust
mod foo {
    use *;
    pub fn meow(){bar()}
}
pub fn bar(){}
fn main(){foo::meow()}
```
Also tried `use ::*;` `use {*};` and `use ::{*};`.

I'm not sure why we don't support this case. Maybe nobody felt anyone would ever use it? It sure would be nice to have in winapi.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #31484.
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @rust-lang/lang, @petrochenkov, @retep998

**Comment by nrc** [comment]
This seems reasonable to me (r=me), but is technically a language change, so I'd like the lang team to approve and/or discuss.

@rfcbot fcp merge

**Comment by withoutboats** [comment]
@rfcbot reviewed

Accepting this is definitely the behavior I would expect.

(I'd also really like to see `use path::{self, *};` accepted someday, but that's neither here nor there.)

**Comment by steveklabnik** [comment]
What's the motivation here? `use ::` is not actually useful; I agree that supporting some of this stuff makes it more orthogonal, but if it's not something that you're supposed to write anyway...

basically, there's nearly no actual motivation here or in  #31484.

**Comment by nrc** [comment]
> What's the motivation here? use :: is not actually useful;

This doesn't support `use ::` it supports `use ::*` which imports everything from the crate root module. That seems just as useful as glob importing from any other module.

**Comment by nrc** [comment]
@withoutboats @dikaiosune the rfcbot reviewed comment didn't tick off the box in the request for feedback, is it meant to?

**Comment by dikaiosune** [comment]
@nrc it's a race condition with some DB interaction that I fixed this morning, but haven't deployed yet. Can you manually check the box for now? (see https://github.com/dikaiosune/rust-dashboard/issues/91)

**Comment by steveklabnik** [comment]
> This doesn't support use :: it supports use ::* which imports everything from the crate root module.

Given that `use` always starts from the crate root, shouldn't that be the same as `use *`?

**Comment by withoutboats** [comment]
@steveklabnik you're right that the `::` in `use ::[path]` is redundant, but its already supported. This just adds glob imports of the module root.

**Comment by steveklabnik** [comment]
Okay, so it's more that the `use ::*` case falls out than it is specifically adding support for this case. That makes sense, then.

**Comment by nikomatsakis** [comment]
Similarly to https://github.com/rust-lang/rust/pull/37035, arguably this should have been feature-gated (and moved for stabilization in the next cycle).

**Pull request merged**
