### PR TITLE
doc: Make block of inline Deref methods foldable

### LINKED ISSUE #127470: rustdoc: Way to fold documentation of `Methods from Deref<Target = ...>`
Take [Vec for example][1], there are fold-able `impl` blocks, but the inline `impl Deref` block
cannot be folded. Sometimes I just wanna skim over the doc, and skip uninterested doc block
by folding them.

image

@rustbot label +A-rustdoc-ui T-rustdoc T-rustdoc-frontend C-enhancement 

[1]: https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.is_ascii

```
> rustc --version
Nightly version: 1.81.0-nightly
(2024-07-06 ed7e35f3494045fa1194)
```

### PR DESCRIPTION
**Pull request by tesuji**
After:
image
Before:
image

Fix  #127470.

Current status:
- [x] Bug when hovering over title "Methods from ...": The anchor sign $ overlaps with `[-]`: https://github.com/rust-lang/rust/pull/127474#issuecomment-2222930038
    => Fixed by https://github.com/rust-lang/rust/pull/127474#issuecomment-2228886292

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
The `[-]`/`[+]` sign is not aligned with the title right?

**Comment by tesuji** [comment]
> The `[-]`/`[+]` sign is not aligned with the title right?

Yeah, that was true since I am not really familiar with CSS. But I found the trick in [0fdb788](https://github.com/rust-lang/rust/pull/127474/commits/0fdb788bda7e0d1f88b3303020d897d170ec34cb)
After:
image

**Comment by GuillaumeGomez** [comment]
There is also this bug:

image

**Comment by GuillaumeGomez** [comment]
If it's fine with you, I can make changes so all UI bugs are fixed?

**Comment by tesuji** [comment]
I'm glad you offer the help. CSS is really not my expertise.

**Comment by GuillaumeGomez** [comment]
Changed the display, it now looks like this:

Screenshot from 2024-07-15 17-37-29
Screenshot from 2024-07-15 17-37-33

And on mobile, since there is no hover, it gets back to its original X position:

Screenshot from 2024-07-15 17-45-28

I'm not too fond of having to move the `[-]` sign to the left like this but it's the only way I could find to allow to have this feature without preventing the anchor to work...

Sadly, it seems like I can't publish doc with this feature since `rustdoc.crud.net` seems down.

Anyway, let's set another reviewer.

r? @notriddle

**Comment by GuillaumeGomez** [comment]
And fixed tidy...

**Pull request merged**
