### PR TITLE
Accept `TyCtxt` instead of `TyCtxtAt` in `Ty::is_*` functions

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Functions in answer:

- `Ty::is_freeze`
- `Ty::is_sized`
- `Ty::is_unpin`
- `Ty::is_copy_modulo_regions`

This allows to remove a lot of useless `.at(DUMMY_SP)`, making the code a bit nicer :3

r? @compiler-errors

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
I was told that the span from `TyCtxtAt` is actually used in query engine, somehow (I don't want to untangle the macros to check how exactly...), so maybe we shouldn't do that. On the other hand, more than half of all places where `.at` was used, just used `DUMMY_SP`, so maybe it's actually fine to use `TyCtxt`?..

**Comment by oli-obk** [comment]
> I was told that the span from `TyCtxtAt` is actually used in query engine, somehow (I don't want to untangle the macros to check how exactly...), so maybe we shouldn't do that. On the other hand, more than half of all places where `.at` was used, just used `DUMMY_SP`, so maybe it's actually fine to use `TyCtxt`?..

If it is used anywhere and we test that code path, you'll see it in ui tests. We have a bunch of cycle error tests, and cycles is where this shows up for users.

**Comment by compiler-errors** [comment]
I'm not sure if this is worthwhile, and  I think you'll see UI test changes when you bless the tests... :thinking:

**Comment by compiler-errors** [comment]
:thinking: how does this not affect any of the UI tests?

**Comment by WaffleLapkin** [comment]
Why would it? I don't think that these queries can lead to cycle errors, so the spans are never shown to the user, I think?

**Comment by compiler-errors** [comment]
Hm, maybe so. In that case, @bors r+

**Pull request merged**
