### PR TITLE
Refactor core::iter module

### PR DESCRIPTION
**Pull request by clarfonthey**
A while back, I refactored `core::ops` in #42523 because the module had become a giant mess and was difficult to modify. Now, I'm doing the same with the `core::iter` module.

Like the `core::ops` refactor, things have been split up into multiple commits to make rebasing easier, and so that you can follow changes. Although the diffs are hard to decipher, the only actual code changes I've made in the first few commits are to modify exports and imports. I save all of the actual code refactoring, e.g. modifying what methods are called, for the end.

### CODE REVIEW

**Comment by bluss** [comment]
Do you think we can find a better place for src/libcore/iter_private.rs too? Should be easy with pub(crate) features.

**Comment by clarcharr** [comment]
That's a good point! I'll move that into the stuff with Zip.

**Comment by clarcharr** [comment]
Rebased and moved `TrustedRandomAccess` into the module with `Zip`. This seems awkward, but considering how this trait is a hack to make `Zip` efficient, I felt like it was most appropriate there.

Let me know what you think!

**Comment by clarcharr** [comment]
Rebased now that #56802 is merged.

**Comment by clarcharr** [comment]
@bluss do you think you'll have time to review this soon? I'm going to be rebasing on #55045 once that's done but after that this will be ready to merge.

Would rather get this merged sooner to avoid conflicts with other PRs.

**Comment by clarcharr** [comment]
This is ready to merge! If @bluss isn't available to review, maybe someone else could?

**Pull request merged**
