### PR TITLE
Make html rendered by rustdoc allow searching non-English identifier / alias

### PR DESCRIPTION
**Pull request by Sunshine40**
Fix alias search result showing `undefined` description.

Inspired by https://github.com/rust-lang/mdBook/issues/2393 .

Not sure if it's worth it adding full-text search functionality to rustdoc rendered html.

### CODE REVIEW

**Comment by Sunshine40** [comment]
Demo:

image

Corresponding code:

```
/// 这是一个加法函数
#[doc(alias = "加法")]
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

/// 这等效于 add 函数，但是用中文命名
pub fn 中文名称的加法API(left: usize, right: usize) -> usize {
    left + right
}

#[macro_export]
macro_rules! 中文命名的加法宏 {
    () => {};
}

/// 英文命名的加法宏
#[doc(alias = "加法")]
#[macro_export]
macro_rules! add {
    () => {};
}
```

**Comment by GuillaumeGomez** [comment]
Seems like a very good start! Can you add tests in `rustdoc-js` to ensure we don't break it in the future please?

Also cc @notriddle

**Comment by Sunshine40** [comment]
> Can you add tests in `rustdoc-js` to ensure we don't break it in the future please?

Done.

**Comment by Sunshine40** [comment]
> I think you'll need to bump the EcmaScript version in the eslint configuration. It's currently set to 8, but [if I'm understanding the Introduction correctly](https://262.ecma-international.org/9.0/#sec-intro), it need bumped to 9.

I'd be happy to do that if stopping support for some legacy browser versions is acceptable (I must admit, I didn't think about browser compatibility at the beginning)

**Comment by Sunshine40** [comment]
> Does anybody know why we have both of these? There's two spots where we're checking es versions.

Because ES-Check and ESLint are separate tools, and there's no out-of-the-box solution to make them share configurations?

**Comment by Sunshine40** [comment]
Should I bump the EcmaScript version in these files as well?
```
/src/tools/rustdoc-js/.eslintrc.js
/src/tools/rustdoc-gui/.eslintrc.js
```

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks a lot! Just letting @notriddle review to ensure I didn't miss something.

**Pull request merged**
