### PR TITLE
don't use generator witness for implied bounds

### PR DESCRIPTION
**Pull request by aliemjay**
... ~and also don't draw implied bounds from the output type of generators and closures. FnDef is still an exception so that we keep supporting~ (edit: reverted):
```rust
fn absurd<T>() -> Option<&'static T> { None }
```

TODO open issues for the bugs fixed here. In the mean time there is `tests/ui/async-await/generator-wf-check.rs`

r? @ghost

### CODE REVIEW

**Comment by aliemjay** [comment]
@craterbot check

**Comment by Dylan-DPC** [comment]
@aliemjay any updates on this?

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
