### PR TITLE
rustc: Add support for `extern crate foo as bar`

### PR DESCRIPTION
**Pull request by alexcrichton**
The compiler will now issue a warning for crates that have syntax of the form
`extern crate "foo" as bar`, but it will still continue to accept this syntax.
Additionally, the string `foo-bar` will match the crate name `foo_bar` to assist
in the transition period as well.

This patch will land hopefully in tandem with a Cargo patch that will start
translating all crate names to have underscores instead of hyphens.

cc #23533

### CODE REVIEW

**Comment by lfairy** [comment]
Oh dear... I've already [implemented this](https://github.com/rust-lang/rust/compare/master...lfairy:dehyphenator) as well :scream:

I think I'll support your version as it's less intrusive, but I'll keep mine around for reference.

(For the record, I took a slightly different approach. My branch pretty much enforces that crate names are identifiers right away instead of patching around it.)

**Comment by alexcrichton** [comment]
Oh oops, sorry about that! I think that we'll definitely want to move towards your approach soon, but for now we want to try to smooth the transition. I don't expect the code to allow hyphens to stick around longer than a week!

**Comment by alexcrichton** [comment]
I've also got crates.io support implemented, just need to deal with some straggler crates that violate the new rule. I will work on a cargo implementation for the RFC soon as well (and this should not be r+'d until that's ready).

**Comment by alexcrichton** [comment]
I've updated with a new warning that's emitted whenever a crate name contains a hyphen. This should cover the case @lfairy did that I forgot where you pass `--crate-name` or it's otherwise inferred from the file name.

**Comment by alexcrichton** [comment]
Ok, crates.io is now rejecting uploads of crates that only differ in hyphens vs underscores

**Comment by alexcrichton** [comment]
I should also note that this adds a bunch of warnings to the build because we have some `extern crate "foo" as bar`, but they should all be removable after a new snapshot lands.

**Comment by lfairy** [comment]
@alexcrichton That sounds good. I'm swamped with course work right now, so I don't mind you taking it from here ;)

**Comment by alexcrichton** [comment]
Ok, I have [implemented cargo support](https://github.com/rust-lang/cargo/pull/1443) and this should be ready to go.

**Comment by alexcrichton** [comment]
This PR actually passed except for a known spurious failure, so I'm going to merge manually.

**Pull request merged**
