### PR TITLE
replace libterm with termcolor in libtest

### LINKED ISSUE #45728: rustc does not emit color output even with --color always with TERM=tmux-256color
`rustc` does not emit color output when running under a tmux session with `TERM` set correctly to `tmux-256color` (supported by the latest versions of ncurses) even with `cargo +nightly build --color=always` when `TERM` is set to `tmux-256color`. On the machine in question (macOS) the term file for `tmux-256color` is installed and `infocmp` returns the following:

```
#	Reconstructed via infocmp from file: /usr/local/Cellar/ncurses/6.0_4/share/terminfo/74/tmux-256color
tmux-256color|tmux with 256 colors,
	am, hs, km, mir, msgr, xenl,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
	acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=\r,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
	cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, dsl=\E]0;\007, ed=\E[J, el=\E[K,
	el1=\E[1K, enacs=\E(B\E)0, flash=\Eg, fsl=^G, home=\E[H,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=\n, is2=\E)0, kDC=\E[3;2~, kEND=\E[1;2F, kHOM=\E[1;2H,
	kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~, kPRV=\E[5;2~,
	kRIT=\E[1;2C, kbs=^H, kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB,
	kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~, kend=\E[4~, kf1=\EOP,
	kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P,
	kf14=\E[1;2Q, kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~,
	kf18=\E[17;2~, kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~,
	kf21=\E[20;2~, kf22=\E[21;2~, kf23=\E[23;2~,
	kf24=\E[24;2~, kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R,
	kf28=\E[1;5S, kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~,
	kf31=\E[18;5~, kf32=\E[19;5~, kf33=\E[20;5~,
	kf34=\E[21;5~, kf35=\E[23;5~, kf36=\E[24;5~,
	kf37=\E[1;6P, kf38=\E[1;6Q, kf39=\E[1;6R, kf4=\EOS,
	kf40=\E[1;6S, kf41=\E[15;6~, kf42=\E[17;6~,
	kf43=\E[18;6~, kf44=\E[19;6~, kf45=\E[20;6~,
	kf46=\E[21;6~, kf47=\E[23;6~, kf48=\E[24;6~,
	kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q, kf51=\E[1;3R,
	kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m,
	ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l, rmir=\E[4l,
	rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
	rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;,
	sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
	tbc=\E[3g, tsl=\E]0;,

```

Per https://github.com/rust-lang/cargo/issues/2877 cargo should be invoking rustc with the `--color always` flag, and indeed, `cargo rustc --color always -- --color always` returns 'Option color given more than once`.

Executing `env TERM=xterm-256color cargo build` also does not produce color output, but `env TERM=xterm-256color cargo build --color always` does.

### LINKED ISSUE #60349: Switch to `termcolor` (first)?
There're on going effort to move libtest out of tree, however i think the current approach(#59440) is a little too aggressive by changing everything in a huge PR. I think it the effort should be splitted and happen in several separate steps. 

The first big step in it is replacing `libterm` with `termcolor`, which means:
* Add separate features to `termcolor`, `wincolor`, and `winapi` to mark these crates unstable (so they can be shipped with rustc.
* Maybe move these crates repo to `rust-lang` organization.
* Modify libtest in-tree to use `termcolor`

An alternative is to keep the existing code for unstable rustc usage but make it a shim over `termcolor` for non-rustc usages.

Just wrote these down to see what peoples think. @alexcrichton @Manishearth @gnzlbg @BurntSushi

### PR DESCRIPTION
**Pull request by euclio**
This commit also completely removes libterm from the tree.

Fixes #60349.
Fixes #45728.

### CODE REVIEW

**Comment by ehuss** [comment]
I'm concerned about bumping the termcolor version.  There is a bug between termcolor and the fwdansi crate that causes colors to go horribly wrong in cargo on windows 7 and 8.  I think it would be good to get https://github.com/kennytm/fwdansi/issues/1 fixed before bumping termcolor.

Colors are currently broken, but they just don't display.  If termcolor is updated, then the colors don't reset and it looks awful.  See https://github.com/rust-lang/rust/issues/55769

**Comment by alexcrichton** [comment]
In addition to @ehuss's concern the build process for libtest is changing in https://github.com/rust-lang/rust/pull/63637 which will conflict with this PR unfortunately. There's a few issues with that which are:

* The manifest of `termcolor` and its dependencies will need the `rustc-dep-of-std` treatment (before they didn't, but after that PR they will)
* We've never gotten around to getting `winapi` building as part of libstd or for libtest, so `termcolor`'s transitive dependency will be difficult to manage. We've basically just never tried this, but it's likely to be thorny for at least one reason or another.

**Comment by crlf0710** [comment]
I coincidentally have a fork of termcolor that had got rid of the `winapi` dependency at https://github.com/crlf0710/termcolor , if anyone found it useful, feel free to cherry pick that commit away. I had named the feature "rustc-dep-of-test" but people might want to change it.

@alexcrichton @euclio

**Comment by euclio** [comment]
Nice, we can certainly try that. Though I'm curious what issues people foresee with trying to get winapi to build in-tree. It might be nice in the long term for libstd to start depending on it anyways.

**Comment by crlf0710** [comment]
@euclio need a rebase

**Comment by retep998** [comment]
I would be happy to help with getting `winapi` building as part of libstd/libtest if that would make things easier.

**Comment by euclio** [comment]
I started by trying to add a `rustc-dep-of-std` feature to winapi, but cargo complains because winapi already has a feature named `std`. Is there a way to work around this?

**Comment by crlf0710** [comment]
@alexcrichton Sorry, i just checked and it seems `rustc-std-workspace-std` on crates.io is totally blank (I think i made a mistake when uploading). Could you add the necessary `pub use std::*;` and publish a new dot version?
After that @euclio can use the optional dependency to replace the feature (just remove the `std = []` line, i think.

**Comment by alexcrichton** [comment]
Sure, I've published a version with that.

**Comment by Alexendoo** [comment]
Ping from triage: How is adapting to https://github.com/rust-lang/rust/pull/63637 going @euclio?

**Comment by euclio** [comment]
This is blocked on updating termcolor and its dependencies with `rustc-std-workspace` support.

**Comment by crlf0710** [comment]
Previously I experimented with the changes locally and found that now `bootstrap` relies on the in-tree libcore, and of course that will fail... My local installed `cargo-tree` doesn't support the newest Cargo.lock format (and i can't get it to work with cargo 0.40). 

I don't really know how to get it right... so tricky...

**Comment by crlf0710** [comment]
Thinking aloud: Why does libtest needs a term library anyway...  `cargo test` command can simply support colors with the `fwdansi` style handling, right? @alexcrichton

**Comment by bjorn3** [comment]
@crlf0710 It is possible to build and invoke a test binary directly without using `cargo test`.

**Comment by crlf0710** [comment]
@bjorn3 It is, but ... what for?

**Comment by bjorn3** [comment]
For example when you want to cross compile and then run the test executable on the target machine.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this PR as pending (likely significant) work in the ecosystem to update the dependencies to be ready for std-inclusion via rustc-dep-of-std propagation.

We can reopen once it's ready to move forward.

**Pull request closed without merging**
