### PR TITLE
try enabling typeof for fun error messages

### PR DESCRIPTION
**Pull request by yaahc**

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@yaahc if you can fix the CI we can take this pr forward

**Comment by yaahc** [comment]
> @yaahc if you can fix the CI we can take this pr forward

@Dylan-DPC it will probably be a bit before I get to this but :+1:

**Comment by oli-obk** [comment]
r? @oli-obk 

if you want, we can also close this PR and open an E-easy issue. Then someone can copy your PR and update all the tests (or write some more)

**Comment by yaahc** [comment]
> r? @oli-obk
> 
> if you want, we can also close this PR and open an E-easy issue. Then someone can copy your PR and update all the tests (or write some more)

I think I want to try to finish this one, since I know it's supposed to be easy.

**Comment by jyn514** [comment]
@yaahc are you still planning to work on this?

**Comment by yaahc** [comment]
yea, sorry about that, this fell off my radar completely but I have a lot more bandwidth for this now (once I get a working dev machine setup again, laptop battery started expanding a couple days ago). So yea, to answer your question, yes, still planning on working on this and soon.

**Comment by oli-obk** [comment]
The impl lgtm. Please add a test showcasing the new error messages

**Pull request merged**
