### PR TITLE
Make Hash{Set,Map}::with_hasher unstably const

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Makes  [`HashMap::with_hasher`](https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.with_hasher) and [`HashSet::with_hasher`](https://doc.rust-lang.org/stable/std/collections/hash_set/struct.HashSet.html#method.with_hasher) `const`.

This allows

```rust
static GlobalState: Mutex<HashMap<i32, i32, SomeHasher>> = Mutex::new(HashMap::with_hasher(SomeHasher::new()))
```

Tracking issue: #102575

### CODE REVIEW

**Comment by cuviper** [comment]
> ```rust
> = Mutex::new(HashMap::new(SomeHasher::new()))
> ```

This should be `HashMap::with_hasher`.
(and we can't do `::new` because that uses runtime randomization)

**Comment by aDotInTheVoid** [comment]
Typo Fixed. Thanks.

**Comment by thomcc** [comment]
CC @rust-lang/wg-const-eval

**Pull request merged**
