### PR TITLE
[beta] Backport #62615

### PR DESCRIPTION
**Pull request by wesleywiser**
This is the backport of #62615

### CODE REVIEW

**Comment by zackmdavis** [comment]
Is there some sort of special procedure for backport PRs, or is it just the usual "bors r+"? #62615 is labeled beta-accepted, so I'm going to assume there's nothing special.

@bors r+

**Comment by wesleywiser** [comment]
I don't believe there's anything special, no.

**Comment by wesleywiser** [comment]
@Centril I see the tree is currently closed but it would be great to get the into beta soon-ish so Mozilla can verify there's no other issues blocking them from using PGO in 1.37.

**Comment by Centril** [comment]
The tree is closed due to CI problems; See https://github.com/rust-lang/rust/pull/62856 for the fix.

Pietro will do a beta backport rollup once the problems are gone.

**Comment by wesleywiser** [comment]
Awesome, thanks so much!

**Pull request merged**
