### PR TITLE
distribute tool documentations and avoid file conflicts on `x install`

### LINKED ISSUE #115213: `python3 x.py install` attempts to install some files multiple times and leaves ".old" files
In a fresh install of 1.72.0 there are some `.old` files:

```
/opt/rustc-1.72.0/share/doc/rustc-1.72.0/README.md.old
/opt/rustc-1.72.0/share/doc/rustc-1.72.0/LICENSE-MIT.old
/opt/rustc-1.72.0/share/doc/rustc-1.72.0/LICENSE-APACHE.old
/opt/rustc-1.72.0/bin/cargo-fmt.old
/opt/rustc-1.72.0/bin/cargo-clippy.old
/opt/rustc-1.72.0/bin/rustfmt.old
/opt/rustc-1.72.0/bin/clippy-driver.old
/etc/bash_completion.d/cargo.old
```

The same thing happens with 1.71.1.

### PR DESCRIPTION
**Pull request by onur-ozkan**
I suggest reading commits one-by-one with the descriptions for more context about the changes.

Fixes #115213

### CODE REVIEW

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+ rollup

**Comment by matthiaskrgr** [comment]
@bors r- rollup=iffy
failed in  https://github.com/rust-lang/rust/pull/121235#issuecomment-1950247890 I think

**Comment by onur-ozkan** [comment]
> @bors r- rollup=iffy failed in [#121235 (comment)](https://github.com/rust-lang/rust/pull/121235#issuecomment-1950247890) I think

Yes, and https://github.com/rust-lang/rust/compare/e4a15d4f042ee9010cbe7f9d26becd52c30f4dec..6ff9c6f96b2ddd9fd83fe32b7089d77d61f40508 should fix that.

@bors r=albertlarsan68 rollup

**Comment by onur-ozkan** [comment]
Changed the 2nd commit.

cc @albertlarsan68

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+

**Pull request merged**
