### PR TITLE
Distinguish fn item types to allow reification from nothing to fn pointers.

### LINKED ISSUE #19925: Set transmute from fn item to type fn lint a hard error
**Original title:** Fn item types should be zero-sized

Per [RFC 401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md#function-type-polymorphism), every fn in Rust should have its own unique, zero-sized type. This fits with the overall design of closures, which also have their own unique types (but those types are not zero-sized, as they carry the environment). None of these types have any explicit syntax at present. This has been a longstanding plan, but until recently it was not fully implemented. This is changing with PR #31710, which means that some existing code will need to be adjusted to account for the new behavior. This issue attempts to summarize how things work and describe what needs to be changed.
### Zero-sized fn types

What all of this means is that, if you have a function declaration `foo`:

``` rust
// for the purposes of this discussion, all of these different kinds of `fn` declarations are equivalent:
fn foo(x: i32) { ... }
extern "C" fn foo(x: i32);
impl i32 { fn foo(x: self) { ... } }
```

the type of `foo` is **not** `fn(i32)`, as one might expect. Rather, it is a unique, zero-sized marker type that I will just write as `typeof(foo)`. However, `typeof(foo)` can be _coerced_ to a function pointer `fn(i32)`, so you rarely notice this:

``` rust
let x: fn(i32) = foo; // OK, coerces
```

The reason that this matter is that the type `fn(i32)` is not specify to any particular function: it's a function _pointer_. So calling `x()` results in a virtual call, whereas `foo()` is statically dispatched, because the type of `foo` tells us precisely what function is being called. 
### Impact on users

As noted above, coercions mean that most code will continue to work just fine before and after this issue is fully fixed. However, you can tell the difference in a few scenarios. Perhaps the most prominent is using **transmute** to convert a fn item into a fn pointer. This is often done as part of an FFI:

``` rust
extern "C" fn foo(userdata: Box<i32>) {
   ...
}

let f: extern "C" fn(*mut i32) = transmute(foo);
callback(f);
```

Here, transmute is being used to convert the types of the fn arguments. This pattern is now incorrect because, because the type of `foo` is a function **item** (`typeof(foo)`), which is zero-sized, and the target type (`fn()`) is a function pointer, which is not zero-sized. For now, this pattern still works due to some special-cased code in the compiler, but that code is expected to be removed. For future compatibility, this pattern should be rewritten. There are a few possible ways to do this:
- change the original fn declaration to match the expected signature, and do the cast in the fn body (perhaps the best);
- cast the fn item fo a fn pointer before calling transmute, as shown here:
  - `let f: extern "C" fn(*mut i32) = transmute(foo as extern "C" fn(_))`
  - `let f: extern "C" fn(*mut i32) = transmute(foo as usize) /* works too */`

The same applies to transmutes to `*mut fn()`, which were observed frequently in practice. Note though that use of this type is generally incorrect. The intention is typically to describe a function pointer, but just `fn()` alone suffices for that. `*mut fn()` is a pointer to a fn pointer. (Since these values are typically just passed to C code, however, this rarely makes a difference in practice.)
### Current status and implementation trail
- [x] PR #19891 laid the groundwork with fresh, unique types per fn item, but left the back-end work undone
- [x] PR #31710 completes the work.

### PR DESCRIPTION
**Pull request by eddyb**
### Type-checking and translation of zero-sized function item types (fixes #19925).

The first commit is a rebase of #26284, except for files that have moved since.

This is a [breaking-change], due to:
- each FFI function has a distinct type, like all other functions currently do
- all generic parameters on functions are recorded in their item types, e.g.:  
  `size_of::<u8>` & `size_of::<i8>`'s types differ despite their identical signature.
- function items are zero-sized, which will stop transmutes from working on them

The first two cases are handled in most cases with the new coerce-unify logic,
which will combine incompatible function item types into function pointers,
at the outer-most level of if-else chains, match arms and array literals.

The last case is specially handled during type-checking such that transmutes
from a function item type to a pointer or integer type will continue to work for
another release cycle, but are being linted against. To get rid of warnings and
ensure your code will continue to compile, cast to a pointer before transmuting.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Triggering a crater run.

**Comment by nikomatsakis** [comment]
Crater run results: https://gist.github.com/nikomatsakis/0902ea970301a841231e

One regression (`fann`).

**Comment by eddyb** [comment]
The regression should be handled by the unify-coerce logic, however I wish I could enable the full extent of it without triggering LLVM asserts :disappointed:.

**Comment by eddyb** [comment]
Turns out that using `fcx.resolve_type_vars_if_possible(...)` on both types in `coercion::try_unify` solves the problem.
That is worrying, because `demand::coerce` does this and it appears to be the reason normalizations happen at all.

The problem in question starts with `&[1, 2, 3][..]` being lowered to `Index::index(&[1, 2, 3] as &[i32], ..: $Idx): &$Output` with an obligation of `<&[i32] as Index<$Idx>>::Output == $Output`.
Immediately afterwards, `$Idx` is unified to `RangeFull`. This is unchanged by my PR.
This specific sequence of events means `$Output` is an inference variable and not a projection or `[i32]`.

My code was mistakenly assigning `Vec<i32>` to `$Output`.
That should error. Instead, the obligation gets dropped or otherwise ignored.

What usually happens is `demand::coerce` (called from anywhere in typeck) calls `resolve_type_vars_if_possible` which resolves `$Output` and nothing has time to assign `$Output` something incorrect.

I've come up with this testcase, which *should* trigger the same sequence of events, but does not:
```rust
fn main() {
    let mut x = unsafe {std::mem::zeroed()};
    let mut y = &[1, 2, 3][x];
    y = &vec![];
    x = ..;
}
```
It errors with "type mismatch resolving `<[_] as Index<RangeFull>>::Output == Vec<_>`" before and after this PR.

cc @rust-lang/compiler Even though my PR appears to work now, I dread leaving an obligation-dropping bug around

**Comment by eddyb** [comment]
Found the culprit: it's [this `resolve_type_vars_if_possible` call](https://github.com/rust-lang/rust/blob/6ffd7cd1664b70fed34861df3957ddee87ec9ad1/src/librustc_typeck/check/mod.rs#L2093), which ironically I added a long time ago (although I'm not sure how the fulfillment context worked at that point, if it even existed).

```rust
        let resolved_t = match unresolved_type_action {
            UnresolvedTypeAction::Error => {
                structurally_resolved_type(fcx, sp, t)
            }
            UnresolvedTypeAction::Ignore => {
                // We can continue even when the type cannot be resolved
                // (i.e. it is an inference variable) because `Ty::builtin_deref`
                // and `try_overloaded_deref` both simply return `None`
                // in such a case without producing spurious errors.
                fcx.resolve_type_vars_if_possible(t)
            }
        };
```

`UnresolvedTypeAction::Ignore` is only used by the coercion code, which is incidentally (AFAICT) the sole caller of `autoderef` from within a transaction (`commit_if_ok`).

`fcx.resolve_type_vars_if_possible`, unlike its `infcx` counterpart, also tries to select obligations.
Obligations selected inside a transaction have their type bindings lost if the transaction is rolled back.

Usually that's not an issue because a failed coercion is fatal, so at worst you get an ICE after a legitimate error.

But I had code which tried coercions and continued in a different manner, resulting in projection obligations successfully selected but then their effects completely rolled back and thus `&[1, 2, 3][..]: &Vec<i32>` managed to sneak in undetected.

The fix is very simple: replace that line with `fcx.infcx().resolve_type_vars_if_possible(&t)`.

However, I would like a permanent solution, that *doesn't allow access* to `fulfillment_cx` *unless* there is no transaction going on. Sticking `fulfillment_cx` in `infcx` might make this cleaner, but atm there's no easy/efficient way of determining whether you're already in a transaction.

**Comment by eddyb** [comment]
@nikomatsakis Tests appear to pass, can I get another crater run? If we see any regressions caused by the scheme I chose, we'll have to tone it down, perhaps limit it to two function item types (although I really like this scheme, especially now that I've plucked the bugs out and it seems to "just work").

**Comment by nikomatsakis** [comment]
OK, I've reviewed as far as ea2510c9eaf1fe3d1fc87b30b643a51e8662d13d (though I'm still reading through d619ebedbbaef7ec0a5c3aabf72edc9a7a165f3b, which seems to be the "meaty" commit) -- it all seems quite nice thus far.

**Comment by nikomatsakis** [comment]
@eddyb the crater run seems to have results now, maybe it just wasn't done before:

https://gist.github.com/nikomatsakis/54fbfe9a0d09b8f51cc6

* 4148 crates tested: 2469 working / 1389 broken / 235 regressed / 1 fixed / 54 unknown.
* There are 27 root regressions
* There are 235 regressions

**Comment by nikomatsakis** [comment]
@eddyb so we were talking about this in the @rust-lang/lang meeting -- if we want to abide by our usual policies, we may want to think about a compatibility mode for transmute where we permit transmutes from a (zero-sized) fn to a ptr but issue a "forward compatibility" lint warning about phasing this change out.

I wish there was something more ergonomic than `transmute(foo as *mut _)` in any case, which seems rather awkward.

**Comment by eddyb** [comment]
What would the check be for? `transmute` from function item type to raw pointer or `fn` pointer type?

**Comment by nikomatsakis** [comment]
On Tue, Mar 01, 2016 at 02:35:02PM -0800, Eduard-Mihai Burtescu wrote:
> What would the check be for? `transmute` from function item type to raw pointer or `fn` pointer type?

Probably... either? I guess people do both in practice?

**Comment by eddyb** [comment]
@nikomatsakis Right, I meant both at the same time.

**Comment by eddyb** [comment]
@nikomatsakis I believe I've addressed all comments, awaiting final crater run (on this or #32080 - betting on nothing being broken there).

**Comment by nikomatsakis** [comment]
@eddyb kicked off a crater run, I haven't looked at your latest changes yet

**Comment by nikomatsakis** [comment]
@eddyb https://gist.github.com/nikomatsakis/a39fa8ebe3eb96a6fa39

## Coverage

* 4277 crates tested: 2831 working / 1411 broken / 21 regressed / 3 fixed / 11 unknown.

## Regressions

* There are 7 root regressions
* There are 21 regressions

**Comment by eddyb** [comment]
Out of the 7 root regressions, 2 use the compiler (clippy), 2 timed out, one is `nix` with lints set to deny and we have 2 actual problems:
`glib-0.0.7`, transmuting to `Option<fn()>`:
```rust
src/source.rs:52:70: 52:79 error: transmute called with differently sized types:
extern "C" fn(&RefCell<Box<FnMut() -> source::Continue + 'static>>) -> i32 {source::trampoline} (0 bits) to
Option<unsafe extern "C" fn(*mut libc::c_void) -> i32> (64 bits) [E0512]                                          
src/source.rs:52         glib_ffi::g_idle_add_full(glib_ffi::G_PRIORITY_DEFAULT_IDLE, transmute(trampoline),
```
I could check for this relatively easily, if you want to.

`zmq-rs-0.1.5`, which has a type I check for, but it's inferred too late:
```
src/lib.rs:317:32: 317:41 error: transmute called with differently sized types:
unsafe extern "C" fn(*mut libc::c_void, *mut libc::c_void) {zmq_free_fn} (0 bits) to
*mut unsafe extern "C" fn(*mut libc::c_void, *mut libc::c_void) (64 bits) [E0512]                                                                                                                  
src/lib.rs:317         let free_fn = unsafe { transmute(zmq_free_fn) };
```
I wouldn't like doing the check any later than the function call, because then many types and inference variables could have been affected and it's probably impossible to track it down.

I've also looked at non-root regressions and there's nothing interesting there.

@nikomatsakis Do you want me to add handling and a testcase for `Option<fn()>` before merging? Although it would increase the complexity of the check, the FFI lints already allow it AFAIK, so it should be possible to detect it.

**Comment by eddyb** [comment]
And yes, that second one is a transmute from a function with the signature `unsafe extern "C" fn(*mut libc::c_void, *mut libc::c_void)` to a pointer to a function pointer **with that exact signature**.

This crate would not regress if the author had used `fn()` instead of `*mut fn()` for a function pointer type, *it would not even need `transmute`*.

cc @steveklabnik @Manishearth @Gankro
The fact that people are writing code like this scares me. Do you think there is a way to prevent this from happening, maybe with cleverer lints?

**Comment by Manishearth** [comment]
We have a transmute lint in clippy, no reason not to add more.

**Comment by Manishearth** [comment]
https://github.com/Manishearth/rust-clippy/issues/749

**Comment by nikomatsakis** [comment]
@eddyb 

>  glib-0.0.7, transmuting to Option<fn()>...I could check for this relatively easily, if you want to.

Seems like we should, yes.

> zmq-rs-0.1.5, which has a type I check for, but it's inferred too late:
> I wouldn't like doing the check any later than the function call, because then many types and inference variables could have been affected and it's probably impossible to track it down.

Fair enough.

Though I'm a bit surprised: I expected to be doing this "transmute backwards compat" code as a hack to trans, not type inference. That is, I expected to modify intrinsicck to allow these particular cases, and just generate different code for transmute calls in that scenario.

Note: I haven't review your changes here yet, I plan to do that today.

**Comment by eddyb** [comment]
I wanted to keep it out of trans, as, for example, I would have to duplicate the check for MIR too, and I just didn't feel comfortable having type-checked bad code (I just spent an entire day weeding out the bad MIR we generate).
I don't even add the reification myself, just switched the expected type where needed.

If you really want me to move it to trans, I can do that and it would handle the `Option` case without special-casing `Option`, I guess.

**Comment by arielb1** [comment]
@eddyb 

Do we still generate bad MIR?

**Comment by eddyb** [comment]
@arielb1 I fixed all the instances I can find, so that rustc builds with MIR (but running that segfaults).
Current status is: trying a fix for `let x = 0; (box || drop(x)) as Box<FnBox()>;` causing a double-free (noop `Box<Trait> -> Box<Trait>` unsizing does this too).

I've pushed my MIR changes to #32080 if you want to look through them.

**Comment by arielb1** [comment]
So mostly transmir fixes, not MIR fixes. Plus the few const-val brokenness fixes.

**Comment by nikomatsakis** [comment]
> I wanted to keep it out of trans, as, for example, I would have to duplicate the check for MIR too, and I just didn't feel comfortable having type-checked bad code (I just spent an entire day weeding out the bad MIR we generate).

Well, I guess it depends on your POV. I wouldn't consider this to be "type-checked bad code" but rather a more subtle definition of transmute. But given that there is only one regression, maybe it's fine either way.

**Comment by nikomatsakis** [comment]
@eddyb ok so I reviewed the final commit and it seems ok. I'm good with landing this now. I updated the description of #19925 so maybe we can redirect people there when it comes to the "forward compat" lint.

**Comment by nikomatsakis** [comment]
@eddyb can you update the lint to point at #19925? I think that's the only change left before `r+`?

**Comment by nikomatsakis** [comment]
@eddyb well, actually, I have one other question and concern. Right now, I think the type for a trait method call is derived from the "pick", which I think means that it may be tied to the *impl* -- if we can find it. But I think that, given the specialization RFC, it should sometimes be tied to the *trait*.

Here is an example that demonstrates what i'm talking about:

```rust
trait Foo { fn foo() { /* this is a default fn */ } }
impl<T>  Foo for T { /* `foo` is still default here */ }

fn main() {
    let x = <u8 as Foo>::foo;
    let y = <u16 as Foo>::foo;
    let mut pair = (x, y);
    same(&mut pair);
}

fn pair<X>(x: &mut (X,X)) { }
```

I expect that, under your impl, this will type-check -- but under specialization, I think it should not, because we are supposed to hold the type of "default" items "opaque" -- and hence the type of `<u8 as Foo>::foo` would be associated with *the trait*.

The simplest thing to do for now would probably be to *always* make the type of methods associated with the trait and not the impl, even though that is stronger than necessary. It may be advisable anyway. (I know @aturon was thinking of this.)

**Comment by nikomatsakis** [comment]
(That said, I'm comfortable addressing this as a follow-up, I think.)

**Comment by eddyb** [comment]
@nikomatsakis A while back I changed it so trait impl methods are not referenced before trans *anywhere*.
Also, I want to try and see if the transmute check can be simpler if done late, before merging.

**Comment by nikomatsakis** [comment]
@eddyb ok, that is sort of how I thought things worked, but when I read over the code I wasn't ... totally sure if that was how it would turn out. Can you add the test case that I mentioned and show that it gives an error? (I am doing a local build now to run some tests.)

**Comment by nikomatsakis** [comment]
@eddyb I'm also +1 on moving the transmute check later, or at least giving it a try. The existing code was a bit grungy.

**Comment by eddyb** [comment]
While the MIR doesn't bootstrap, I could still check the test:
```rust
niko.rs:8:10: 8:19 error: mismatched types:
 expected `&mut (_, _)`,
    found `&mut (fn() {Foo::foo}, fn() {Foo::foo})` [E0308]
niko.rs:8     same(&mut pair);
                   ^~~~~~~~~
```

I *really* wish we had a generalized way of printing `<Self as all::but::Last<A, B>>::last::<X, Y>` paths, fwiw.

**Comment by nikomatsakis** [comment]
@eddyb ah, I see what I was missing -- the `def_id` for the method comes from `pick.item.def_id()` which is actually the *trait item*. I was tracking the `DefId` in the `ExtensionCandidatePick` or whatever. Nonetheless, I'd really like an explicit test added (with a comment explaining its purpose). Seems like an easy thing for us to get wrong.

**Comment by nikomatsakis** [comment]
@eddyb I wonder if we should pretty print fn types with `typeof()` btw... even though it's not valid syntax, it seems a *bit* more obvious than the current `{}` notation.

**Comment by eddyb** [comment]
@nikomatsakis What about `<Self as Trait>::method(T) -> U`? Or does that look too obscure?

**Comment by nikomatsakis** [comment]
@eddyb well, that doesn't obviously handle free fns or inherent things, right? But I guess the question is whether to include the argument types etc in the signature, or leave them out. *Probably* worth including them? I guess they'd be important in particular with failed coercions to a `fn` type.

**Comment by nikomatsakis** [comment]
(Honestly, I'd rather leave them out -- but only if we can still give useful error messages.)

**Comment by eddyb** [comment]
@nikomatsakis Right, free would be just, e.g. `size_of::<Foo>() -> usize` - it kinda looks like the function definition, I guess? I agree that keeping them is a bit annoying, to say the least.

**Comment by nikomatsakis** [comment]
@eddyb seems like we should maybe start an internals thread. With respect to the parameters, it'd be worth attempting various scenarios where they become significant (e.g., when coercing but with wrong argument types) and seeing if we can tailor the error message for that case anyway. (Probably not in this PR, though.) In other words, the best thing we can do here is NOT print the type whenever possible. :)

**Comment by SSheldon** [comment]
FYI, special casing the transmute from functions did not prevent all regressions. I had some code that started segfaulting in 1.9.0, fixed by SSheldon/rust-objc-foundation@f918819. Basically, it boils down to looking like this:
``` rust
#[link(name = "objc", kind = "dylib")]
extern {
    fn objc_msgSend();
}

unsafe fn msg_send<T>(t: T) {
    let f: unsafe extern fn() = objc_msgSend;
    let f: unsafe extern fn(T) = ::std::mem::transmute(f);
    f(t)
}

fn hello() {
    println!("hello");
}

fn main() {
    unsafe {
        msg_send(hello);
    }
}
```

That's a case where what used to be a function pointer silently becomes a 0-sized type.

Anyways, fixed now, hopefully no one else is writing code like this! But figured I'd make it known in case anyone else runs into something similar.

**Comment by eddyb** [comment]
@SSheldon Interesting example. While there is transmute in there, it has to do with passing generic arguments to C functions. A similar situation arose with C variadics in FFI, see #32201.
You could also notice this problem if you were doing `(*(&rust_function as *const fn()))()`.

**Pull request merged**
