### PR TITLE
:arrow_up: `rust-analyzer`

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
CC @HKalbasi

>   error[E0725]: the feature `rustc_private` is not in the list of allowed features

**Comment by HKalbasi** [comment]
Hmm, is it renamed? It worked on my machine's nightly.

**Comment by lnicola** [comment]
Maybe `#![feature(rustc_private)]` is disallowed by the CI?

**Comment by HKalbasi** [comment]
Ah, I missed the `allowed` in the error message, and read it as `is not in the list of features`.

It seems we should add `rustc_private` [here](https://github.com/rust-lang/rust/blob/67ad3c23941d2296448d7b38b16eccd1b3e38925/src/bootstrap/tool.rs#L606C10-L606C30).

**Comment by lnicola** [comment]
> error[E0463]: can't find crate for `hkalbasi_rustc_ap_rustc_abi`

Huh

**Comment by HKalbasi** [comment]
Do you have any idea why should this happen? It is a normal dependency without any cfg and things like that.

**Comment by lnicola** [comment]
No answers in https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/.22Can't.20find.20crate.22.20on.20RA.20sync.20PR, not sure what to do about future syncs.

**Pull request closed without merging**
