### PR TITLE
Add {get,set}rlimit and getrusage to libc

### PR DESCRIPTION
**Pull request by nagisa**
Hopefully didn’t miss or mess up anything.

~~EDIT: ah, as usual, just didn’t bother running build before pushing a submit request button. Build pending.~~

### CODE REVIEW

**Comment by huonw** [comment]
I have no idea about how stable these are across platforms. Are the `rlimit`/`rusage` structs standardised?

**Comment by nagisa** [comment]
from `man 0p sys_resource.h`:

> The <sys/resource.h> header shall define the following type through typedef:
> 
>     rlim_t          Unsigned integer type used for limit values.
> 
> The <sys/resource.h> header shall define the following symbolic constants, which shall have values suitable for use in #if preprocessing directives:
> 
>     RLIM_INFINITY   A value of rlim_t indicating no limit.
>     RLIM_SAVED_MAX  A value of type rlim_t indicating an unrepresentable saved hard limit.
>     RLIM_SAVED_CUR  A value of type rlim_t indicating an unrepresentable saved soft limit.
> 
> On implementations where all resource limits are representable in an object of type rlim_t, RLIM_SAVED_MAX and RLIM_SAVED_CUR need not be distinct from RLIM_INFINITY.
> The <sys/resource.h> header shall define the following symbolic constants as possible values of the who parameter of getrusage():
> 
>     RUSAGE_SELF     Returns information about the current process.
>     RUSAGE_CHILDREN Returns information about children of the current process.
> 
> The <sys/resource.h> header shall define the rlimit structure, which shall include at least the following members:
>
>     rlim_t rlim_cur  The current (soft) limit.
>     rlim_t rlim_max  The hard limit.
>
> The <sys/resource.h> header shall define the rusage structure, which shall include at least the following members:
>
>     struct timeval ru_utime  User time used.
>     struct timeval ru_stime  System time used.
>
> The <sys/resource.h> header shall define the timeval structure as described in <sys/time.h>.
> The <sys/resource.h> header shall define the following symbolic constants as possible values for the resource argument of getrlimit() and setrlimit():
>
>     RLIMIT_CORE     Limit on size of core file.
>     RLIMIT_CPU      Limit on CPU time per process.
>     RLIMIT_DATA     Limit on data segment size.
>     RLIMIT_FSIZE    Limit on file size.
>     RLIMIT_NOFILE   Limit on number of open files.
>     RLIMIT_STACK    Limit on stack size.
>     RLIMIT_AS       Limit on address space size.
>
> The following shall be declared as functions and may also be defined as macros. Function prototypes shall be provided.
>
>     int  getpriority(int, id_t);
>     int  getrlimit(int, struct rlimit *);
>     int  getrusage(int, struct rusage *);
>     int  setpriority(int, id_t, int);
>     int  setrlimit(int, const struct rlimit *);

The values and structs are included here from corresponding OS’s header files (except for OS X/iOS `rusage` which is comes from [iOS docs](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrusage.2.html)) with all the extensions they provide.

**Comment by nagisa** [comment]
Ok, this `rusage` conforms to `SVr4, 4.3BSD`, rather than `POSIX 2001`. Abort all reviews until updated.

**Comment by alexcrichton** [comment]
This looks good to me (it will be used in an upcoming patch of yours, right?). Feel free to ping once you've gone through the final update.

We should always be able to fix these in the future as well, so tweaks here and there should be fine.

**Comment by nagisa** [comment]
> it will be used in an upcoming patch of yours, right?

At least a part of it, yes.  I decided that if I’m binding a function in liblibc, I could as well just bind the related functions as well. Also, since I’m not really sure what I’m doing here, I thought it would be better to submit this as a separate PR.

Moved rusage struct to bsd43.

**Comment by alexcrichton** [comment]
In general this crate is currently a bit of a dumping ground and I'm not sure how well the organization has been maintained over time. We generally are not adding many new additions to it but instead binding them locally at (e.g. `sys::c`), but if you've already gone through the trouble of adding the definitions for all platforms then I think it's fine to go ahead and merge

@bors: r+

**Pull request merged**
