### PR TITLE
Remove struct_span_err function from ExtCtxt

### LINKED ISSUE #76508: Clean up rustc_expand: remove struct_span_err method and use the macro instead
As said in https://github.com/rust-lang/rust/pull/76406

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #76508

cc @jyn514 @pickfire

### CODE REVIEW

**Comment by jyn514** [comment]
FYI this wasn't what I was referring to in https://github.com/rust-lang/rust/pull/76406 - [`Session::struct_span_err`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/struct.Session.html#method.struct_span_err), confusingly, is different from [`struct_span_err!`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/macro.struct_span_err.html) - the second takes an error code and the first doesn't.

No opinion on this PR, though.

**Comment by GuillaumeGomez** [comment]
Yep, the naming is funny. I don't want to update the macro though (because I'd prefer that we used error codes everywhere \o/).

**Comment by pickfire** [comment]
Weird, I thought the `struct_span_error!` macro can take in an optional error code so we can use that here but it doesn't seemed so.

**Comment by pickfire** [comment]
> Yep, the naming is funny. I don't want to update the macro though (because I'd prefer that we used error codes everywhere \o/).

Just wondering, if we write error codes everywhere doesn't mean later we will have a high chance to duplicate one of the error code?

**Comment by GuillaumeGomez** [comment]
There is a check for that. You can't use the same error code at multiple places.

**Comment by pickfire** [comment]
> There is a check for that. You can't use the same error code at multiple places.

Not same error code. Different error code but a same or a very similar message.

**Comment by estebank** [comment]
> There is a check for that. You can't use the same error code at multiple places.

We no longer to 👀

> Not same error code. Different error code but a same or a very similar message.

This already happens from time to time. Sometimes we leave it like that, sometimes we merge them.

**Comment by estebank** [comment]
I don't see the benefit this PR brings, but I don't see its harm either. What's the rationale? If I understand correctly it was a comment about using the `struct_span_error!` macro, not about removing `ExtCtxt::struct_span_err`, right?

**Comment by GuillaumeGomez** [comment]
Yes, not really useful... Closing it then.

**Comment by pickfire** [comment]
@estebank Since we are not using `struct_span_error_with_code` and we used `struct_span_error!` instead, but we still have `struct_span_error` delegating to the original `struct_span_error`, I thought it would be better to remove `struct_span_error` so it does not cause confusion as there is no `struct_span_error_with_code`.

**Comment by estebank** [comment]
@pickfire I would like to do that sort of clean up in a more mechanical/principled way, checking what patterns we currently use and optimize for them.

**Pull request closed without merging**
