### PR TITLE
Pretty print btreemap for GDB

### PR DESCRIPTION
**Pull request by fukatani**
Merge #53112 first, please.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
r? @michaelwoerister

NB #53112 is merged

**Comment by michaelwoerister** [comment]
Looks great, thanks @fukatani!

@bors r+

**Comment by ortem** [comment]
This implementation only works for very small maps with only one node, isn't it?

**Comment by tromey** [comment]
> This implementation only works for very small (size <= 12, as I understand) maps with only one node, isn't it?

I tried it and yes, it seems that you are correct.  I filed #55771 for this.

**Pull request merged**
