### PR TITLE
Rollup of 18 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #119123 (Add triagebot mentions entry for simd intrinsics)
 - #119991 (Reject infinitely-sized reads from io::Repeat)
 - #120172 (bootstrap: add more unit tests)
 - #120250 (rustdoc: Prevent JS injection from localStorage)
 - #120376 (Update codegen test for LLVM 18)
 - #120387 (interpret/memory: fix safety comment for large array memset optimization)
 - #120400 (Bound errors span label cleanup)
 - #120402 (Make the coroutine def id of an async closure the child of the closure def id)
 - #120403 (Add instructions of how to use pre-vendored 'rustc-src')
 - #120424 (raw pointer metadata API: data address -> data pointer)
 - #120425 (Remove unnecessary unit returns in query declarations)
 - #120439 (Move UI issue tests to subdirectories)
 - #120443 (Fixes footnote handling in rustdoc)
 - #120452 (std: Update documentation of seek_write on Windows)
 - #120460 (Be more careful about interpreting a label/lifetime as a mistyped char literal.)
 - #120464 (Add matthewjasper to some review groups)
 - #120467 (Update books)
 - #120488 (Diagnostic lifetimes cleanups)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=119123,119991,120172,120250,120376,120387,120400,120402,120403,120424,120425,120439,120443,120452,120460,120464,120467,120488)

### CODE REVIEW

**Comment by Nilstrieb** [comment]
going all in

**Comment by chenyukang** [comment]
@Nilstrieb @GuillaumeGomez 
do you know how to resolve this `homu` timeout issue? 😅

**Comment by GuillaumeGomez** [comment]
@Nilstrieb: No time to lose! :rocket: 

@chenyukang: Doing a retry like what was done. Not much else that can be done as far as I know...

**Pull request merged**
