### PR TITLE
A number of spell-checking corrections.

### PR DESCRIPTION
**Pull request by jest**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you!

**Comment by steveklabnik** [comment]
removing the doc-backport label because this is the book, i'm doing that last, right before the merge. @jest , make sure you name is in the AUTHORs PR!

**Comment by jest** [comment]
I'm sorry, but I totally don't know what I'm expected to do... For me everything is fine.

**Comment by steveklabnik** [comment]
Sorry! I wasn't as clear as I should be.

Because 1.0 is happening this week, some commits are getting backported to the release. yours is one of them. I'll handle all those details, but the AUTHORS.txt file doesn't include your name, since we ran the 'get everyone's names' script before this PR was merged.

So, head over to #25196 and mention that you should be in there, because of this PR.

**Comment by jest** [comment]
Thanks for clarification, done.

**Pull request merged**
