### PR TITLE
Stabilize duration_float

### LINKED ISSUE #54361: Tracking issue for duration_float
Rust PRs: #52813, #59102

This feature adds the following float related methods to `Duration`:
- `as_secs_f64(&self) -> f64`
- `as_secs_f32(&self) -> f32`
- `from_secs_f64(secs: f64) -> Duration`
- `from_secs_f32(secs: f32) -> Duration`
- `mul_f64(self, rhs: f64) -> Duration`
- `mul_f32(self, rhs: f32) -> Duration`
- `div_f64(self, rhs: f64) -> Duration`
- `div_f32(self, rhs: f64) -> Duration`

`div_duration` methods are tracked in #63139.

### PR DESCRIPTION
**Pull request by newpavlov**
Closes: #54361

### CODE REVIEW

**Comment by joelpalmer** [comment]
Ping from Triage. Hi, @dtolnay, pinging you to check on the status of a review for this PR. 
cc: @rust-lang/libs

**Comment by alexcrichton** [comment]
I'm personally in favor of stabilizing these functions, so I'm going to propose such.

@rfcbot fcp merge

The major new APIs here that I would proposed for stabilization are:

```rust
impl Duration {
    pub fn as_secs_f64(&self) -> f64;
    pub fn as_secs_f32(&self) -> f32;
    pub fn from_secs_f64(secs: f64) -> Duration; // panics on overflow
    pub fn from_secs_f32(secs: f32) -> Duration; // panics on overflow
}
```

then using those new APIs implementations are provided for:

```rust
impl Duration {
    pub fn mul_f64(self, rhs: f64) -> Duration; // panics on overflow
    pub fn mul_f32(self, rhs: f32) -> Duration; // panics on overflow
    pub fn div_f64(self, rhs: f64) -> Duration;
    pub fn div_f32(self, rhs: f32) -> Duration;
}
```

... and finally there are these two methods which also use `as_secs_*` but I would personally propose they not be stabilized at this time since they seem a bit odd and not really buying much over just doing what the implementation already does (`self.as_secs_f32() / rhs.as_secs_f32()`)

```rust
impl Duration {
    pub fn div_duration_f64(self, rhs: Duration) -> f64;
    pub fn div_duration_f32(self, rhs: Duration) -> f32;
}
```

**Comment by newpavlov** [comment]
What should I do with `div_duration` methods? I guess we can simply remove them.

**Comment by alexcrichton** [comment]
If others agree that we shouldn't stabilize the methods then yeah I think it's fine to just remove them.

**Comment by jhpratt** [comment]
@alexcrichton Certainly there's a use case for `div_duration_{f32,f64}`? Right now, I'm doing `self.duration.div_duration_f32(Duration::from_millis(1))` to get the number of milliseconds _including_ the fractional bit. I suppose I could do `self.duration.checked_mul(1000).as_secs_f32()`, but it seems clearer to me to extract the millisecond value directly. Of course, a `.as_millis_f32()` method would be ideal, but regardless.

**Comment by alexcrichton** [comment]
Note that I'm not saying that they're not useful nor that we should never stabilize. I don't think they fit into the pattern of the other stabilizations so I think it's worthwhile to consider them separately from these initial stabilizations. Sounds like we shouldn't remove them though, we'll just want to open a new tracking issue for those specific methods.

**Comment by newpavlov** [comment]
I've marked `div_duration` methods as unstable, they will be tracked in #63139.

**Comment by faern** [comment]
How come the `mul_fXX` and `div_fXX` methods are not just `Mul`/`Div` implementations?:
```rust
impl Div<f32> for Duration {...}
impl Div<f64> for Duration {...}
impl Mul<f32> for Duration {...}
impl Mul<f64> for Duration {...}
```

There might be an obvious answer that I missed. But I can't see anyone discussing/proposing this in the PRs leading up to this stabilization.

**Comment by newpavlov** [comment]
@faern 
See this [message](https://github.com/rust-lang/rust/pull/52813#issuecomment-415516936). I think adding those impls can be done in a separate PR, although I am not  sure if the libs team will support such addition.

**Comment by faern** [comment]
Thanks @newpavlov,

I interpret that message as the libs team wanting the `Div`/`Mul` impls after/when there is a way to convert a `Duration` to a float. Which this PR stabilizes. So I don't see why we would bloat `std` with duplicate ways to do the same thing if the libs team agree we could add the proper trait impls now when we have the to-float-functionality?

**Pull request merged**
