### PR TITLE
Don't use posix_spawn_file_actions_addchdir_np on macOS.

### PR DESCRIPTION
**Pull request by ehuss**
There is a bug on macOS where using `posix_spawn_file_actions_addchdir_np` with a relative executable path will cause `posix_spawnp` to return ENOENT, even though it successfully spawned the process in the given directory.

`posix_spawn_file_actions_addchdir_np` was introduced in macOS 10.15 first released in Oct 2019.  I have tested macOS 10.15.7 and 11.0.1.

Example offending program:

```rust
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::process::*;

fn main() {
    fs::create_dir_all("bar").unwrap();
    fs::create_dir_all("foo").unwrap();
    fs::write("foo/foo.sh", "#!/bin/sh\necho hello ${PWD}\n").unwrap();
    let perms = fs::Permissions::from_mode(0o755);
    fs::set_permissions("foo/foo.sh", perms).unwrap();
    let c = Command::new("../foo/foo.sh").current_dir("bar").spawn();
    eprintln!("{:?}", c);
}
```

This prints:

```
Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
hello /Users/eric/Temp/bar
```

I wanted to open this PR to get some feedback on possible solutions.  Alternatives:
* Do nothing.
* Document the bug.
* Try to detect if the executable is a relative path on macOS, and avoid using `posix_spawn_file_actions_addchdir_np` only in that case.

I looked at the [XNU source code](https://opensource.apple.com/source/xnu/xnu-6153.141.1/bsd/kern/kern_exec.c.auto.html), but I didn't see anything obvious that would explain the behavior.  The actual chdir succeeds, it is something else further down that fails, but I couldn't see where.

EDIT: I forgot to mention, relative exe paths with `current_dir` in general are discouraged (see #37868).  I don't know if #37868 is fixable, since normalizing it would change the semantics for some platforms. Another option is to convert the executable to an absolute path with something like joining the cwd with the new cwd and the executable, but I'm uncertain about that.

### CODE REVIEW

**Comment by tmiasko** [comment]
The bug is in `posix_spawnp` implementation. After successful `posix_spawn` it calls `stat` on the specified executable path: https://opensource.apple.com/source/Libc/Libc-1353.100.2/sys/posix_spawn.c.auto.html

**Comment by ehuss** [comment]
Interesting, thanks for taking a look!  Comments like "We hope that the race for a stat() is unimportant." are great.  I guess another option in theory we could use `posix_spawn` directly and replicate the PATH search ourselves, although that seems unpleasant.

Also, to be clear, I'm fine with the "do nothing" option.  It just seems like an easy footgun, and there doesn't seem to be a clear path forward for #37868, which if it used an absolute path I think would fix this.  

I'm not sure I understood the discussion about `canonicalize`, because I would think it would be as simple as "if exe contains '/', join it with the current directory".  I wouldn't think it would be necessary to use `realpath`, since the OS will handle all the other work.  I know `env::current_dir` could fail, but I assume in that case (and exe isn't absolute), the call to spawn would fail, too.  

A question is, are people willing to change the semantics of `Command::current_dir` (to make it consistent across platforms), or should we leave it in its confusing state, or should it be deprecated and replaced with something better?

**Comment by tmiasko** [comment]
The macOS bug is quite severe when combined with `Command::current_dir`. Using a workaround to avoid it feels well deserved in this case. The approached proposed in this PR, which fall backs to fork & exec and restores the previous behaviour looks fine to me. I would also add a regression test, e.g., in `src/test/ui/command`.

**Comment by ehuss** [comment]
OK, I have added a test.  I think it should pass on all platforms, but I am not absolutely certain about some of the more unusual platforms (I tested linux, macos, and windows).

**Review by dtolnay — APPROVED** [review]

**Comment by ehuss** [comment]
I pushed a small fix to make the test work on Android.  An alternative fix would be to change remote-test-server to set the current_dir when it spawns a test, but I figure just updating the test would make it more robust.

@bors r=dtolnay

**Pull request merged**
