### PR TITLE
Fix footnote link on "The stack and the heap" page

### PR DESCRIPTION
**Pull request by ericye16**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you! :smile:

**Comment by pnkfelix** [comment]
a merge commit has somehow gotten mixed in here?

**Comment by ericye16** [comment]
Oops, I messed up. Should I try to revert that or should I just make a new
PR?

**Comment by ericye16** [comment]
I fixed the merge commit via force push, next time I'll branch properly :)

**Comment by steveklabnik** [comment]
(unsure if bors needs the re-r+, but doing it anyway just in case)

**Pull request merged**
