### PR TITLE
Fix documentation of conversion from String to OsString

### PR DESCRIPTION
**Pull request by steffahn**
From [this question on URLO](https://users.rust-lang.org/t/does-converting-a-string-into-a-pathbuf-allocate-new-buffer/57678), I noticed that the documentation of `From<String> for OsString` incorrectly claims to be copying data.

@rustbot modify labels: T-doc, T-libs

### CODE REVIEW

**Comment by steffahn** [comment]
I’m also adding a few more minor cleanup things to this PR regarding `From` implementations

**Review by JohnTitor — APPROVED** [review]
Good catch!

> I’m also adding a few more minor cleanup things to this PR regarding `From` implementations

Do you have more cleanups other than 5264ef2 on this PR?

**Comment by steffahn** [comment]
Ah, in case you were just asking about what I was referring to, no I haven’t got anything beyond 5264ef2 yet. Anything extra can also go into a new PR if this one is improved.

**Comment by steffahn** [comment]
well, okay, that didn’t work, @pietroalbini

>Highfive failed to assign someone here. I'll add more logging so we'll discover what's causing this in the future.
>
>When something like this happens again, please ping the whole infra team. Thanks :)


https://github.com/rust-lang/rust/pull/75911#issuecomment-680988468

**Comment by steffahn** [comment]
>Only Rust team members can ping teams.

Guess I can do it manually
@aidanhs @Mark-Simulacrum @kennytm @pietroalbini @shepmaster

**Comment by Dylan-DPC** [comment]
please do not ping people :D yeah it's a known thing and sometimes it happens. The infra team is aware about it. 

r? @Dylan-DPC

**Comment by shepmaster** [comment]
`s/documenation/documentation/g`

**Comment by jyn514** [comment]
> `s/documenation/documentation/g`

One step ahead of you ;)

**Comment by JohnTitor** [comment]
> Ah, in case you were just asking about what I was referring to, no I haven’t got anything beyond [5264ef2](https://github.com/rust-lang/rust/commit/5264ef2a8063ab539f11e0081851a00b5c1ef62d) yet. Anything extra can also go into a new PR if this one gets approved in the meantime.

Yeah, that's what I meant. Okay, then @bors r+ rollup
Thanks!

**Comment by shepmaster** [comment]
> One step ahead of you ;)

It's also in the commit message, which is why I commented instead of changing it myself.

**Comment by steffahn** [comment]
removed typo in the commit message

**Review by JohnTitor — COMMENTED** [review]
I was late a bit but...

**Comment by JohnTitor** [comment]
Thanks again :)
@bors r+

**Pull request merged**
