### PR TITLE
Move the SC constants for macos to an accessible module (fixes #24374 for mac).

### LINKED ISSUE #24374: Add _SC_NPROCESSORS_ONLN constants for linux and macos
There is a bug in `num_cpu` where the call to `sysconf` is hard-coded to `84` so doesn't work when on Mac OS X; which consequently brakes a lot of libraries when used on Mac OS X.

We need to add constants to `numcpu` so this type of bug doesn't occur again.

https://github.com/seanmonstar/num_cpus/issues/2

### PR DESCRIPTION
**Pull request by Ms2ger**
These constants were added in 6f54ce9aa5d2baf0cd82c01e2c181ab17439b7d7 and
e8fbd1ce048fdfc2db1d446fedfe8775ce446046 to a consts module that is behind a
gate.

I have not confirmed that these constants do indeed work on either OSX or iOS.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 2a46976

Thanks!

**Comment by Ms2ger** [comment]
r?

**Pull request merged**
