### PR TITLE
implement sort for VecDeque

### LINKED ISSUE #27322: VecDeque has no `sort_by` method (should possibly have one to match Vec).
I just came across a use case for this while working on a visit order for the UI graph in conrod - its absence took me by surprise :smile_cat: 

Is there a particular reason this hasn't been implemented yet? Or has it just not _popped_ up yet (pun intended)?

### PR DESCRIPTION
**Pull request by lcnr**
closes https://github.com/rust-lang/rust/issues/27322.

I have currently only implemented `sort_by`. If this change is desired,
I will gladly add the other sort methods:

- `sort`
- `sort_by_key`, 
- `sort_by_cached_key`
- `sort_unstable`
- `sort_unstable_by`
- `sort_unstable_by_key`

### CODE REVIEW

**Comment by lcnr** [comment]
An alternative implementation may not have rearrange the slices.
Even if rearranging would not be guaranteed right now, it is still observable
and may therefore be depended on by some user code.

This could be prevented changing the deque to not be continuous after sorting:

```rust
pub fn sort_by<F>(&mut self, compare: F)
where
    F: FnMut(&T, &T) -> Ordering,
{
    self.make_continuous();

    self.as_mut_slices().0.sort_by(compare);

    if self.len() % 3 == 1 { 
        self.make_noncontinuous();
    }
}
```

**Comment by lcnr** [comment]
I temporarily added `ignore-tidy-filelength`, as `vec_deque.rs` now has over 3000 lines.

I think that it would be easiest to move `struct Iter` and `struct Drain` into a submodule,
should I do this?

**Comment by lcnr** [comment]
Using merge instead of one continuous sort. Not quite sure on how compare both
implementations before this PR is merged, as I can't easily implement the sorting done in this PR outside of liballoc.

```rust
fn merge<T, F>(front: &mut [T], back: &mut [T], compare: &mut F)
where
    F: FnMut(&T, &T) -> Ordering,
{
    if back.is_empty() {
        return;
    }

    if let Some(initial_element) = front
        .iter()
        .position(|e| compare(&back[0], e) == Ordering::Less)
    {
        mem::swap(&mut back[0], &mut front[initial_element]);

        let mut back_ptr = 1;
        for front_ptr in (initial_element + 1)..front.len() {
            if let Some(back_elem) = back.get(back_ptr) {
                if compare(&back_elem, &back[0]) == Ordering::Less {
                    mem::swap(&mut back[back_ptr], &mut front[front_ptr]);
                    back_ptr += 1;
                } else {
                    mem::swap(&mut back[0], &mut front[front_ptr]);
                }
            } else {
                break;
            }
        }

        let (buffer, rest) = back.split_at_mut(back_ptr);
        merge(buffer, rest, compare);
    }
}

pub fn sort_by<T, F>(q: &mut VecDeque<T>, mut compare: F)
where
    F: FnMut(&T, &T) -> Ordering,
{
    let (front, back) = q.as_mut_slices();
    front.sort_by(&mut compare);
    back.sort_by(&mut compare);

    merge(front, back, &mut compare);
}
```

**Comment by CryZe** [comment]
This makes me wonder if `make_continuous` should just be a public API instead that returns a &mut [T], where you can then use it with any API that expects a slice, and thus you can use that for not just sorting, but other APIs as well.

**Comment by lcnr** [comment]
superseded by #69425

**Comment by KodrAus** [comment]
I would personally still be in favour of sorting methods on `VecDeque` itself, since going through `get_contiguous` isn't really discoverable for somebody looking for a way to sort.

**Comment by lcnr** [comment]
By using `#[rustc_on_unimplemented]` and mentioning it in the overview I think this might be at least partially solved.

I don't think that adding 7 more methods to `VecDeque` (`sort, sort_by, sort_by_key, sort_by_cached_key, sort_unstable, sort_unstable_by, sort_unstable_by_key`)  is not worth this imo rather small metal complexity. Especially since sorting a `VecDeque` is used very infrequently.

**Pull request closed without merging**
