### PR TITLE
Remove CrateNum::ReservedForIncrCompCache

### PR DESCRIPTION
**Pull request by bjorn3**
It's only use is easily replaceable with `Option<CrateNum>`.

### CODE REVIEW

**Comment by bjorn3** [comment]
Wow! Up to 11.3% improvements for such a simple change! Bootstrap improved by 1.0%. No regressions at all. :heart:

**Comment by Aaron1011** [comment]
The perf impact is pretty stunning. I think we should try look into exactly why this is such a large improvement - I suspect that there could be similar missed opportunities within rustc.

**Comment by klensy** [comment]
No data for `rustc_parse_format` in perf run. Other question: why that big change?

**Comment by bjorn3** [comment]
I would expect that part of the perf change is from the `Hash` impl now only needing to hash an `u32` instead of a tag and maybe an `u32`. Another part could be that there are no more panics in the encodable impl. Some could be caused by the `from_*` and `as_*` methods previously not being `#[inline]`. Another part of the perf improvement could be the rest of the derives optimizing better.

> No data for rustc_parse_format in perf run.

Huh, strange.

**Comment by Mark-Simulacrum** [comment]
rustc_parse_format has a runtime of ~1 second, and we don't currently record measurements less than 1 second.

**Comment by bjorn3** [comment]
x86_64-apple has been running for over 4 hours. All other jobs passed. Likely spurious.

@bors retry

**Comment by Mark-Simulacrum** [comment]
Do we have some idea for why this was such a large win? It seems like it may be worth investigating as there's likely some more general improvements to be made - the enum previously defined does not seem like it *should* add overheads, ideally. Maybe we're hashing enums that are size-optimized by unpacking and hashing the discriminant first, even though that's not necessary in practice in at least some cases (e.g., this one, where the hash of the raw bytes would be sort of fine?).

**Comment by bjorn3** [comment]
This is my best guess: https://github.com/rust-lang/rust/pull/85829#issuecomment-851600916

> Maybe we're hashing enums that are size-optimized by unpacking and hashing the discriminant first

Yeah, I am pretty sure this is the case.

**Pull request merged**
