### PR TITLE
force tidy to be executed after other tests

### LINKED ISSUE #36613: make tidy runs before the rest of make check with -jn>1
This is extremely annoying since it means you have to have nicely formatted code to run the tests. We changed this years ago and it seems to have reverted to the old behaviour.

### PR DESCRIPTION
**Pull request by 0xmohit**
Fixes #36613

### CODE REVIEW

**Comment by sanxiyn** [comment]
Isn't the issue about running tidy *before* other tests, not *after* other tests?

**Comment by 0xmohit** [comment]
I may be wrong but the issue seemed to suggest otherwise.  (It ends up running *before* other tests when running multiple jobs in parallel with `-j`.)

cc @nrc

**Comment by alexcrichton** [comment]
As @pnkfelix [pointed out](https://github.com/rust-lang/rust/issues/36613#issuecomment-248889257) this has been changed before so we probably don't want to oscillate too much and [I personally think](https://github.com/rust-lang/rust/issues/36613#issuecomment-249443194) there's not really a right answer.

**Comment by nrc** [comment]
Currently, tidy runs before other tests when running -jn and after (which is desirable) when running -j1. I would like it to run after in both cases.

**Comment by 0xmohit** [comment]
Before this change, the prerequisites for `make check` were:

    check-sanitycheck cleantmptestlogs cleantestlibs all check-stage2 tidy

Given that the order in which the prerequisites would be built is not defined, it seemed reasonable to pull out `tidy` from the prerequisites for `check` and instead make it a part.  A seemingly silly example seems to work.  In the following, the target `last` would be executed after the prerequisites, namely one and two, regardless of `-j`.  On the other hand, it the prerequisites were listed as `one two last`, then those would be guaranteed to execute in the specified _order_ only if one job was being run, i.e. `-j=1`.

```
all: one two
        $(MAKE) last

one:
        @echo one1
        @echo one2
        @echo one3
        @echo one4
        @echo one5

two:
        @echo two1
        @echo two2
        @echo two3
        @echo two4
        @echo two5

last:
        @echo foo1
        @echo foo2
        @echo foo3
        @echo foo4
        @echo foo5
```

--

Another option might have been to make use of [order-only prerequisites](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html).

**Comment by pnkfelix** [comment]
>  Another option might have been to make use of [order-only prerequisites](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html).

When I first saw this PR I was going to suggest that it instead use Order-only Pre-requisites. But after skimming the documentation for them, I was not able to determine if they were actually applicable in this scenario. :(

If someone more knowledgeable of GNU make than I can figure out a way to use them here, I would probably prefer to take that route.

**Comment by 0xmohit** [comment]
> But after skimming the documentation for them, I was not able to determine if they were actually applicable in this scenario. :(

Digging further into the [documentation](https://www.gnu.org/software/make/manual/make.html), it appears that those aren't applicable here.  (Also see http://gnu-make.2324884.n4.nabble.com/order-only-prerequisites-don-t-behave-as-I-d-have-expected-after-reading-the-documentation-td3787.html)

**Comment by pnkfelix** [comment]
>  (Also see http://gnu-make.2324884.n4.nabble.com/order-only-prerequisites-don-t-behave-as-I-d-have-expected-after-reading-the-documentation-td3787.html)

This thread does have the following interesting idea: 

```
I think I would use a test on $(MAKECMDGOALS) to make T1 a
prerequisite of T2 if and only if T1 is a goal, say...

     ifneq ($(filter T1,${MAKECMDGOALS}),)
     T2: T1
     endif
```

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with comments addressed!

**Pull request closed without merging**
