### PR TITLE
Specialize `derive(Clone)` to use `Copy` when applicable

### PR DESCRIPTION
**Pull request by fee1-dead**
In this PR I added two internal items in `core::clone`: `try_copy` and `DerivedClone`.

`try_copy` will copy from `&T` to `T` if it can, and call a function when it cannot.

The derive impl for `Clone` is changed such that it generates a call to `try_copy(self, DerivedClone::clone)`, and the impl for `DerivedClone` contains the derive impl before this PR.

Internally:
I added a field to `TraitDef` named `bound_current_trait` that disables addition of generic bounds of the trait that is being implemented. This prevents bounding on `DerivedClone` when we are generating that impl.

### CODE REVIEW

**Comment by fee1-dead** [comment]
Could be perf sensitive, so:

@bors try @rust-timer queue

**Comment by jackh726** [comment]
Do you need me to review this prior to fixing perf?

**Comment by fee1-dead** [comment]
Yes, I think perf might be unavoidable.

**Comment by jackh726** [comment]
What's the point of this, if not perf?

**Comment by fee1-dead** [comment]
compiler perf will definitely be negatively affected since we now emit two items for the derive. The question would be, "are there people who implement `Copy` manually or `derive(Copy)` in a different attribute while deriving `clone`?"

If there is a significant amount of them, then I think this would definitely be beneficial. But now it doesn't seem to have much of a benefit. Maybe we could discuss the possibility of doing something like this with perfect derives.

**Comment by scottmcm** [comment]
Note that in the case of something like
```rust
#[derive(Clone)]
pub struct Foo(usize, HashSet<String>, usize);
```

The mir-opt in #94276 will replace the `clone` calls on the primitives with copies pretty early, to simplify the MIR.

So that along with LLVM being pretty good at inlining the clones enough to notice they're actually copies (even the MIR inliner can often do this, though it's not on *yet*), it's possible that most of the low-hanging fruit here has already been picked.

**Pull request closed without merging**
