### PR TITLE
BTreeMap: clean up the full_range function

### PR DESCRIPTION
**Pull request by ssomers**
Long ago, benchmarks seemed to say this function had a performance benefit, but with more accurate benchmarking and insight I think that was malarkey.
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

Let's check in on perf.rlo, but seems fine to drop to me.

**Comment by Mark-Simulacrum** [comment]
Hm, overall those numbers definitely show this change had some significant effects, but it's less clear the extent to which they are positive or negative.

**Comment by ssomers** [comment]
I don't know what the numbers mean and how stable they are. The only way I see how `full_range` could be better, is locality in the first iteration, because it reads the first and last edge of the same root node. I'd be interested to see how a hybrid version of `full_range` that expresses that would fare, but not hugely so.

**Comment by ssomers** [comment]
The alloc benchmarks (that shrugged their shoulders over the abolition of full_range) consistently grant the latest version a ~5% win on the iterator tests, inconsistently setting back a few unrelated tests.

**Comment by Mark-Simulacrum** [comment]
I don't think we can land this with regressions in the perf suite and at least to me no strong benefit (AFAICT, this is just a refactoring and isn't actually necessary for other work?).

I'm going to go ahead and close but happy to reopen or continue discussing if you would like; in particular, if you feel that there is a strong benefit.

**Pull request closed without merging**
