### PR TITLE
Remove ordering traits from `LocalExpnId`

### PR DESCRIPTION
**Pull request by pierwill**
See https://github.com/rust-lang/rust/issues/90317.

### CODE REVIEW

**Comment by cjgillot** [comment]
I think we want to keep the `Idx` impl for `LocalExpnId`. `IndexVec` is quite a good data structure for an interner. It may be easier to make the ordering traits opt-out in `newtype_index` macro, like we do with encodable/decodable traits.

**Comment by pierwill** [comment]
> It may be easier to make the ordering traits opt-out in `newtype_index` macro, like we do with encodable/decodable traits.

Ah, great! I was wondering if something like that was possible. I'll check out that code. 👍

**Comment by pierwill** [comment]
> It may be easier to make the ordering traits opt-out in newtype_index macro, like we do with encodable/decodable traits.

@cjgillot Could you offer a clue on how to do this, or an example from the encodable traits you mention? I'm a macro newbie!

**Pull request closed without merging**
