### PR TITLE
validate promoteds

### LINKED ISSUE #67465: Promoted values are not validated
The program below creates a promoted in a constant via

```rust
&unsafe { BoolTransmute { val: 3 }.bl }
```

but immediately casts this to a raw pointer. Now having weird values behind raw pointers is fine, but we have an intermediate reference to an invalid value. I don't understand how this compiles considering that the promoted is essentially
 
```rust
static PROMOTED: bool = transmute(3u8);
```

Apparently we don't validate promoteds. I think we are allowed to fix this and validate promoteds, even though it will be a breaking change, because the user had to create an intermediate reference that pointed to an invalid bool.

cc @RalfJung 

```rust
union BoolTransmute {
    val: u8,
    bl: bool,
}

const RAW_TRAIT_OBJ_CONTENT_INVALID: *const dyn Trait = &unsafe { BoolTransmute { val: 3 }.bl } as *const _;

trait Trait {}
impl Trait for bool {}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=42fa563741feac63e6fcdff07762eb7b))

### PR DESCRIPTION
**Pull request by RalfJung**
Turn on const-value validation for promoteds. This is made possible now that https://github.com/rust-lang/rust/issues/67534 is resolved.

I don't think this is a breaking change. We don't promote any unsafe operation any more (since https://github.com/rust-lang/rust/pull/77526 landed). We *do* promote `const fn` calls under some circumstances (in `const`/`static` initializers), but union field access and similar operations are not allowed in `const fn`. So now is a perfect time to add this check. :D

r? @oli-obk 
Fixes https://github.com/rust-lang/rust/issues/67465

### CODE REVIEW

**Comment by RalfJung** [comment]
Ah, but validation complains about...
```
error[E0080]: it is undefined behavior to use this value
  --> /home/r/src/rust/rustc/src/test/ui/consts/const-eval/promote-static.rs:7:1
   |
LL | / static NONE_REF_REF: &&Option<String> = {
LL | |     let x = &&NONE;
LL | |     x
LL | | };
   | |__^ type validation failed: encountered a reference pointing to a static variable at .<deref>
   |
   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
```
Since promoteds are constants and constants may not point to statics.

**Comment by RalfJung** [comment]
Meanwhile, let's see if this affects perf.
@bors try @rust-timer queue

**Comment by oli-obk** [comment]
> Since promoteds are constants and constants may not point to statics.

ah lol, I guess we need to differentiate between promoteds in statics and promoteds elsewhere?

**Comment by RalfJung** [comment]
I guess promoted in consts should not contain refs to statics, yeah...

**Comment by RalfJung** [comment]
Looks like there's a perf hit of up to 4.5% for some examples.

**Comment by RalfJung** [comment]
I fixed the breakage, tests should pass now (the ones I ran locally did).

What remains is deciding if we are okay with the perf hit.

**Comment by oli-obk** [comment]
So... I'm ok with this perf hit, though I'm wondering if we should somehow "turn it off" and just keep it as a sort of debug assertion that we aren't doing anything bad with promotion. I mean... this should *never* actually cause a validation failure afaict.

**Comment by RalfJung** [comment]
This would be true if we did not promote `const fn` calls in const/static bodies... at least on nightly, those can produce invalid results.

**Comment by oli-obk** [comment]
Riiight, those. So let's do this now and consider moving to debug assertions once we know the result of the crater run

@bors r+

**Pull request merged**
