### PR TITLE
Batch up libsyntax breaking changes

### PR DESCRIPTION
**Pull request by jseyfried**
Batch of the following syntax-[breaking-change] changes:
- #35591: Add a field `span: Span` to `ast::Generics`.
- #35618: Remove variant `Mod` of `ast::PathListItemKind` and refactor the remaining variant `ast::PathListKind::Ident` to a struct `ast::PathListKind_`.
- #35480: Change uses of `Constness` in the AST to `Spanned<Constness>`.
  - c.f. `MethodSig`, `ItemKind`
- #35728: Refactor `cx.pat_enum()` into `cx.pat_tuple_struct()` and `cx.pat_path()`.
- #35850: Generalize the elements of lists in attributes from `MetaItem` to a new type `NestedMetaItem` that can represent a `MetaItem` or a literal.
- #35917: Remove traits `AttrMetaMethods`, `AttributeMethods`, and `AttrNestedMetaItemMethods`.
  - Besides removing imports of these traits, this won't cause fallout.
- Add a variant `Union` to `ItemKind` to future proof for `union` (c.f. #36016).
- Remove inherent methods `attrs` and `fold_attrs` of `Annotatable`.
  - Use methods `attrs` and `map_attrs` of `HasAttrs` instead.

r? @Manishearth

### CODE REVIEW

**Comment by petrochenkov** [comment]
>:broken_heart: Test failed - auto-win-gnu-32-opt-rustbuild

`run-pass\union\union-xcrate.rs` fails.
Can you just remove it? Something is legitimately wrong there, but I don't want to block the batch, I'll investigate today or tomorrow.

**Comment by jseyfried** [comment]
@petrochenkov I removed #36016 and instead added a commit that future proofs the AST so that #36016 is no longer a syntax-[breaking-change].
@bors r=Manishearth p=10

**Comment by petrochenkov** [comment]
@jseyfried 
> I removed #36016 and instead added a commit that future proofs the AST so that #36016 is no longer a syntax-[breaking-change].

There are also `derive` changes - `supports_unions: bool` needs to be added to `deriving::generic::TraitDef` for future proofing, see https://github.com/rust-lang/rust/pull/36016/commits/d7ed590541148ca2330d02b07a97577facb1e1c3 and https://github.com/rust-lang/rust/pull/36016/commits/49eb1d2ab833986d67cd6789e042a8b285a43652.

**Comment by jseyfried** [comment]
@petrochenkov Good point, I added `supports_unions: bool` in the above commit.

**Pull request merged**
