### PR TITLE
Update books

### PR DESCRIPTION
**Pull request by ehuss**
Update nomicon, reference, book, edition-guide, embedded-book

rust-by-example cannot be updated because it is currently broken (https://github.com/rust-lang/rust-by-example/pull/1161)

## nomicon

8 commits in b7eb4a087207af2405c0669fa577f8545b894c66..f1ff93b66844493a7b03101c7df66ac958c62418
2018-11-30 08:52:24 -0500 to 2019-02-26 13:37:28 -0500
- Fix typo in other-reprs.md (rust-lang-nursery/nomicon#112)
- Remove duplicate 'the' in aliasing.md (rust-lang-nursery/nomicon#116)
- Fix typo in subtyping.md (rust-lang-nursery/nomicon#117)
- Trivial updates to the coercions chapter (rust-lang-nursery/nomicon#118)
- Fix double "the" in aliasing.md (rust-lang-nursery/nomicon#119)
- Fixes outdated bindgen link (rust-lang-nursery/nomicon#110)
- Fix link to type layout reference (rust-lang-nursery/nomicon#121)
- Fix capitalization of Rust in races.md (rust-lang-nursery/nomicon#107)

## reference

18 commits in 1c775a1dc5e29bc44b36604b510d6196d98077fa..41493ffce5d0e17d54eaf5ec9a995054e2b9aece
2019-01-13 21:12:05 +0100 to 2019-03-05 12:32:22 +0100
- Fix broken link. (rust-lang-nursery/reference#527)
- Update attribute documentation. (rust-lang-nursery/reference#528)
- Remove target_has_atomic. (rust-lang-nursery/reference#529)
- Remove "mode" from derive macro terminology. (rust-lang-nursery/reference#530)
- Clarifications (rust-lang-nursery/reference#493)
- Fix an incorrect note (rust-lang-nursery/reference#522)
- Document extern_crate_self (rust-lang-nursery/reference#517)
- Fix spelling (rust-lang-nursery/reference#520)
- Update conditional-compilation.md (rust-lang-nursery/reference#503)
- Document if_while_or_patterns (rust-lang-nursery/reference#516)
- Fix some broken links. (rust-lang-nursery/reference#519)
- Clarify what access struct updates do (rust-lang-nursery/reference#518)
- Document irrefutable_let_patterns (rust-lang-nursery/reference#515)
- Document Rc/Arc method receivers. (rust-lang-nursery/reference#494)
- unions have no active field (rust-lang-nursery/reference#478)
- attributes.md Outer -> Inner (rust-lang-nursery/reference#510)
- Let bindings are now available in const contexts (rust-lang-nursery/reference#512)
- Add missed literal at MacroFragSpec (rust-lang-nursery/reference#513)

## book

2 commits in fab9419503f0e34c1a06f9350a6705d0ce741dc6..9cffbeabec3bcec42d09432bfe7705125c848889
2019-02-25 07:53:23 -0500 to 2019-03-02 08:22:41 -0500
- More edits (rust-lang/book#1838)
- Remove the 2018 edition nostarch directory

## edition-guide

1 commits in 5f3cc2a5618700efcde3bc00799744f21fa9ad2e..aa0022c875907886cae8f3ef8e9ebf6e2a5e728d
2019-02-27 20:11:50 -0800 to 2019-02-27 22:10:39 -0800
- Fix one last link in readme. (rust-lang-nursery/edition-guide#153)

## embedded-book

12 commits in bd2778f304989ee52be8201504d6ec621dd60ca9..9e656ead82bfe869493dec82653a52e27fa6a05c
2019-02-10 12:37:14 +0000 to 2019-03-03 16:03:26 +0000
- Merge rust-embedded/book#174
- Merge rust-embedded/book#172
- Merge rust-embedded/book#169
- Merge rust-embedded/book#171
- Merge rust-embedded/book#168
- Merge rust-embedded/book#153
- Merge rust-embedded/book#142 rust-embedded/book#151
- Merge rust-embedded/book#133 rust-embedded/book#135
- Merge rust-embedded/book#150
- Merge rust-embedded/book#145
- Merge rust-embedded/book#129
- Merge rust-embedded/book#128

### CODE REVIEW

**Comment by Centril** [comment]
Looks spurious to me; @bors retry

**Comment by ehuss** [comment]
Moved to #58920.

**Pull request closed without merging**
