### PR TITLE
Revert "Add fatal overflow test"

### LINKED ISSUE #104957: src/test/ui/traits/predicate_can_apply-hang.rs is failing spuriously
First introduced in https://github.com/rust-lang/rust/pull/104269, cc @compiler-errors

```
---- [ui]  stdout ----

error: Error: expected failure status (Some(1)) but received status None.
status: signal: 6 (SIGABRT) (core dumped)
Some tests failed in compiletest suite=ui mode=ui host=i686-unknown-linux-gnu target=i686-unknown-linux-gnu
command: "/checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/traits/predicate_can_apply-hang.rs" "-Zthreads=1" "--target=i686-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/i686-unknown-linux-gnu/test/ui/traits/predicate_can_apply-hang" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/i686-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/i686-unknown-linux-gnu/test/ui/traits/predicate_can_apply-hang/auxiliary"
stdout: none
--- stderr -------------------------------
memory allocation of 713031696 bytes failed
------------------------------------------
```

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/104950#issuecomment-1328119407_

### PR DESCRIPTION
**Pull request by compiler-errors**
This reverts commit 9decfff6f87d3e5760fd61375c3d27fa45a83e52.

Fixes #104957

r? @jyn514

### CODE REVIEW

**Comment by compiler-errors** [comment]
I'll file a bug for the spurious hang investigation. I think it should be separate from #104957, though I guess we could reuse that issue.

**Comment by jyn514** [comment]
Note `    [ui] src/test/ui/typeck/hang-in-overflow.rs` was also failing, so if you remove one you should probably remove the other.

**Comment by compiler-errors** [comment]
In that case, imma just revert the whole PR.

**Pull request closed without merging**
