### PR TITLE
fix #40294 obligation cause.body_id is not always a NodeExpr

### LINKED ISSUE #40294: Compiler unnecessary panicked due to a mistake in where clause
The compiler unexpectedly panicked where a nice error should be produced.

I tried this code:
    
    pub fn zip<K, V, W, A, B>(a: A, b: B)
        where K: Ord,
              A: Iterator<Item=(K, V)>,
              A: Iterator<Item=(K, W)>,
    {
    
    }

I simply forgot to change the third entry in the where clause to `B`.

## Meta

`rustc --version --verbose`:
rustc 1.17.0-nightly (24a70eb59 2017-02-09)
binary: rustc
commit-hash: 24a70eb598a76edb0941f628a87946b40f2a1c83
commit-date: 2017-02-09
host: x86_64-pc-windows-gnu
release: 1.17.0-nightly
LLVM version: 3.9

Backtrace:
thread 'rustc' panicked at 'Box<Any>', C:\bot\slave\nightly-dist-rustc-win-gnu-64\build\src\librustc_errors\lib.rs:417
stack backtrace:
   0:         0x659e854a - strncmp
   1:         0x659f2fa7 - strncmp
   2:         0x659f2b21 - strncmp
   3:         0x659f352e - strncmp
   4:         0x66242f9a - strncmp
   5:         0x6625b044 - strncmp
   6:         0x6f387f5e - strncmp
   7:         0x6f387cb5 - strncmp
   8:         0x6f3874fc - strncmp
   9:         0x6f29c278 - strncmp
  10:         0x6f39578b - strncmp
  11:         0x6f38af55 - strncmp
  12:         0x6f389971 - strncmp
  13:         0x70cab10f - strncmp
  14:         0x70bea5d6 - strncmp
  15:         0x70c6d966 - strncmp
  16:         0x70c8097a - strncmp
  17:         0x70c97768 - strncmp
  18:         0x70cfd984 - strncmp
  19:         0x69c60b83 - strncmp
  20:         0x69bbc0ab - strncmp
  21:         0x69c4ace4 - strncmp
  22:         0x69c343a9 - strncmp
  23:         0x69c7f2b9 - strncmp
  24:         0x69b8af05 - strncmp
  25:         0x659f6938 - strncmp
  26:         0x69ba83b4 - strncmp
  27:         0x659f0d52 - strncmp
  28:     0x7ffff6398363 - strncmp

### PR DESCRIPTION
**Pull request by cengiz-io**
Hello!

This fixes #40294 and moves tests related to #38812 to a much more sensible directory.

Thanks to @nikomatsakis and @eddyb

### CODE REVIEW

**Comment by petrochenkov** [comment]
@cengizIO 
>and moves tests related to #38812 to a much more sensible directory

Those tests are about type checking, not name resolution.
Could you move then to some (possibly new) subdirectory dedicated to type checking instead?

@bors r-
(Sorry.)

**Comment by cengizIO** [comment]
@petrochenkov thanks for warning.

Maybe we can add directory mappings to `src/test/ui/README.md`

**Comment by Zoxc** [comment]
The test for #40294 is a edited copy of the #21974 test. It should go alongside it in `compile-fail`.

**Comment by nikomatsakis** [comment]
@Zoxc 

> The test for #40294 is a edited copy of the #21974 test. It should go alongside it in compile-fail.

So, I agree with @petrochenkov that `resolve` wasn't the right directory (good spot!), but I don't see any particular reason that #40294 has to live alongside the test for #21974, though. (And [I'd like to remove compile-fail](https://internals.rust-lang.org/t/consolidating-compile-fail-and-ui-testing-and-possibly-others-as-well/4896/2) anyhow.) It's a separate regression test, regardless of how it was derived.

**Pull request merged**
