### PR TITLE
rustdoc: Resolve doc links referring to `macro_rules` items

### PR DESCRIPTION
**Pull request by petrochenkov**
cc https://github.com/rust-lang/rust/issues/81633

UPD: the fallback to considering *all* `macro_rules` in the crate for unresolved names is not removed in this PR, it will be removed separately and will be run through crater.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Review by notriddle — APPROVED** [review]
Overall, I like this change. Using the "real" name resolver, instead of dumping all the `macro_rules` into a big global hash map, is definitely a bug fix. The rustdoc name resolver should act like the regular one as much as is reasonable.

But (1) this is a breaking change, and (2) even though I was assigned to it, I'm still not really the best expert on this kind of change.

**Comment by petrochenkov** [comment]
Only removal of the `fn resolve_macro_rules` fallback can cause a noticeable breakage here.
I can move to a separate PR so it doesn't block landing the remaining changes here (I plan to do some more work on top of them).

**Comment by petrochenkov** [comment]
>we know docs.rs doesn't make warnings very visible, so anyone publishing there might not even notice

Then crater won't catch them either?
Only crates with `deny(rustdoc::broken_intra_doc_links)` will regress in both cases.

**Comment by petrochenkov** [comment]
>Maybe a crater run with a tweaked version that, instead of making the fallback fill in a resolution, the "fallback" is tweaked to produce a hard error whenever it actually runs and resolves something?

Ok, that should be possible.

>I'd like to use a backcompat warning, but anyone using docs.rs won't actually see it.

`rustdoc::broken_intra_doc_links` is already a warning, so reporting another warning saying that we are going to report this warning is a bit strange.

**Comment by petrochenkov** [comment]
Updated the PR, removal of the `fn resolve_macro_rules` fallback is reverted now.
@rustbot ready

**Review by notriddle — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
So unless I missed something, we need a crater run here, right?

**Comment by petrochenkov** [comment]
No, crater run is no longer needed.
It will be needed in the next PR that will attempt to remove the `resolve_macro_rules` fallback.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Then let's go. Thanks!

@bors: r=notriddle,GuillaumeGomez

**Pull request merged**
