### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by mati865** [comment]
You should use r? @ghost in PR description if you do not expect review 😉

**Comment by matklad** [comment]
Good tip, fixed in https://github.com/rust-analyzer/rust-analyzer/pull/5340

**Comment by Manishearth** [comment]
@bors r- 

https://github.com/rust-lang/rust/pull/74303#issuecomment-657787870

**Comment by matklad** [comment]
Yup, legitimate failure, hopefully will be fixed next week. I am also going to add power check build to our CI — it’s the second time we fail with AtomicU64 error. I wish we had(transitive) portability lints

**Pull request closed without merging**
