### PR TITLE
A simplified Rube Goldberg line

### PR DESCRIPTION
**Pull request by m0w**
There is no need for all those list initializations and merging operations. This line is just a Rube Goldberg machine for updating the second list element, and here is a Pythonic proposal to cope with this issue.

### CODE REVIEW

**Comment by Piturnah** [comment]
Should it not be `'-h'`?

**Comment by m0w** [comment]
> Should it not be `'-h'`?

Yea yea, my bad. I've updated the commit that I proposed.

**Comment by Mark-Simulacrum** [comment]
It looks like it's still double quotes, but regardless, please squash commits into one, and then we can merge.

**Comment by m0w** [comment]
> It looks like it's still double quotes, but regardless, please squash commits into one, and then we can merge.

To be honest, there is no need for the use of single quotation marks over the single ones, because they are interpreted as the same in Python (ref. https://peps.python.org/pep-0008/#string-quotes). As it is just a matter of convention, and there is no consistency throughout the code in that manner, I really can't see any reason for this to be a single quotation mark besides a matter of taste.

**Comment by Mark-Simulacrum** [comment]
If you'd like to leave the quotes as is, that's fine by me, I agree it doesn't matter since we're not consistent in either direction anyway. However, I would still like to see the commits squashed.

**Comment by Piturnah** [comment]
> Should it not be `'-h'`?

> It looks like it's still double quotes, but regardless, please squash commits into one, and then we can merge.

I think I caused a bit of confusion here, just to clarify to Mark my comment was in reference to the `-` not being present in the initial commit and wasn't to do with quotes. It was fixed in the next commit along with the quote style being changed.

**Comment by JohnCSimon** [comment]
@m0w 
ping from triage - can you post your status on this PR? Thanks

**Comment by JohnCSimon** [comment]
@m0w

> It looks like it's still double quotes, but regardless, please squash commits into one, and then we can merge.

can you please squash the commits?

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by JohnCSimon** [comment]
@m0w 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
