### PR TITLE
Add test, closes #20454

### LINKED ISSUE #20454: "Unable to infer enough type information" when spawning thread and looping.
```rust
use std::thread;

fn main() {
    thread::Thread::spawn(move || {
        loop { // Remove the loop and everything works fine.
            println!("hello");
        }
        // This gives you:
        //
        // type_inf.rs:4:5: 4:26 error: unable to infer enough type information about `_`; type annotations required
        // type_inf.rs:4     thread::Thread::spawn(move || {
        //                   ^~~~~~~~~~~~~~~~~~~~~
        // error: aborting due to previous error


        // Uncomment the `()` below, and the error changes to a warning:
        //
        // type_inf.rs:8:9: 9:6 warning: unreachable expression, #[warn(unreachable_code)] on by default
        // type_inf.rs:8         ()
        // type_inf.rs:9     }).detach();

        // ()
    }).detach();
}
```

$ rustc --version
rustc 0.13.0-nightly (39d740266 2015-01-01 15:51:08 +0000)

### PR DESCRIPTION
**Pull request by jfager**
Closes #20454

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ f340ccb rollup

Thanks!

**Comment by Manishearth** [comment]
This test hangs.

Is [this](https://github.com/Manishearth/rust/commit/9e11cf43bdddd2dc2c4608ea7816d5411f9a5474) an acceptable way of fixing it?

**Comment by jfager** [comment]
Argh, `scoped` was supposed to be `spawn`, I think I was just playing around with it and accidentally pushed the wrong thing.  Sorry.

**Pull request merged**
