### PR TITLE
configure: Don't disable optimizations when enabling debug

### LINKED ISSUE #24405: `configure --enable-debug --enable-optimize` is not enabling optimizations
Running `configure --enable-debug --enable-optimize` is not enabling optimizations.

Concretely, running `../configure --enable-debug --enable-optimize` yields:
```
CFG_ENABLE_DEBUG     := 1
...
CFG_DISABLE_OPTIMIZE := 1
CFG_DISABLE_OPTIMIZE_CXX := 1
...
CFG_CONFIGURE_ARGS   := --enable-debug --enable-optimize
```

And, just out of curiosity, I tried switching the order of args; that made little difference:
```
CFG_ENABLE_DEBUG     := 1
...
CFG_DISABLE_OPTIMIZE := 1
CFG_DISABLE_OPTIMIZE_CXX := 1
...
CFG_CONFIGURE_ARGS   := --enable-optimize --enable-debug
```

### PR DESCRIPTION
**Pull request by richo**
Optimization is now on by default. Closes #24405

### CODE REVIEW

**Comment by pnkfelix** [comment]
@richo my goal was to preserve the spirit of the original change, under which `--enable-debug` on its own would indeed disable optimizations, and only change the behavior when one passes *both* `--enable-debug` and `--enable-optimize`.

(However. perhaps this is misguided, and we should simply just do what you suggest here.)

**Comment by richo** [comment]
Ah. I pondered that for a while, and wound up concluding that optimizations are now the default state. That seems reasonable to me though, will update the patch.

**Comment by pnkfelix** [comment]
@richo well, TBH now I am torn too.  I'm going to go ask for opinions in `#rust-internals`.

**Pull request merged**
