### PR TITLE
feat(ci): upload metrics to GitHub Artifacts ✨

### PR DESCRIPTION
**Pull request by meysam81**
fixes rust-lang/infra-team#74
replaces rust-lang/simpleinfra#348

### CODE REVIEW

**Review by jdno — CHANGES_REQUESTED** [review]
We also generate detailed metrics in `x.py`, which we should upload. Here's the relevant step in [upload-artifacts.sh](https://github.com/rust-lang/rust/blob/093b9d5b295d85e144d0ee7da65ea03987214c06/src/ci/scripts/upload-artifacts.sh#L29C4-L29C4):

```shell
cp "${build_dir}/metrics.json" "${upload_dir}/metrics-${CI_JOB_NAME}.json"
```

I didn't notice before that `build_dir` is a variable that has two different values, based on the operating system:

```shell
build_dir=build
if isLinux; then
    build_dir=obj/build
fi
```

So simply invoking `actions/upload-artifact` might not be enough. 😬

I am wondering if it would make sense to create a script to gather the build metrics that we can call in both `upload-artifacts.sh` and in a step before `actions/upload-artifact`. In other words, move these instructions into a script and call it in both places:

```shell
# CPU usage statistics.
cp build/cpu-usage.csv "${upload_dir}/cpu-${CI_JOB_NAME}.csv"

# Build metrics generated by x.py.
cp "${build_dir}/metrics.json" "${upload_dir}/metrics-${CI_JOB_NAME}.json"
```

What do you think?

**Comment by Dylan-DPC** [comment]
@jdno any updates on the review? thanks

**Comment by Dylan-DPC** [comment]
r? infra

**Pull request closed without merging**
