### PR TITLE
do not propagate closure requirements if we can prove them locally

### LINKED ISSUE #53570: [nll] overly strict `T: 'static` bound arising from closure
The recent crater run found an incorrect `T: 'static` bound compiling [cswinter.locustdb.c5942997e6bdbb94fe0920e67bd96b0637399b97](https://github.com/cswinter/LocustDB/tree/c5942997e6bdbb94fe0920e67bd96b0637399b97) ([log](https://crater-reports.s3.amazonaws.com/pr-53426/a5d98b025f62ace80fe9d2a15781f900fc42515e-alt/gh/cswinter.LocustDB/log.txt)). This looks perhaps like a variant of https://github.com/rust-lang/rust/issues/53119. 

[Minimized reproduction available here.](https://play.rust-lang.org/?gist=a051d535a66f46f52ceb271383d334d5&version=nightly&mode=debug&edition=2015).

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #53570 

cc @mikhail-m1 -- you're the one who last touched this code

r? @pnkfelix

### CODE REVIEW

**Comment by TimNN** [comment]
Ping from triage @pnkfelix / @rust-lang/compiler: This PR requires your review.

**Comment by estebank** [comment]
@bors r-

@nikomatsakis the nll errors [are not stable](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.8873/job/itj8n6kqtuhgs3qf#L10727) :-/

**Pull request merged**
