### PR TITLE
Fix not running some steps in CI

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
We'd previously assumed that these paths would be relative to the src
dir, and that for example our various CI scripts would, when calling
x.py, use `../x.py build ../src/tools/...` but this isn't the case --
they use `../x.py` without using the relevant source-relative path.

We eventually may want to make this (actually somewhat logical) change,
but this is not that time.

r? @kennytm

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=50

I'm going to go ahead and r=me this since it's a fairly critical patch that makes our CI properly test wasm, for example.

**Comment by pnkfelix** [comment]
my hope is that this PR will also fix issue #48268

**Comment by pnkfelix** [comment]
@Mark-Simulacrum your description seems to imply that if my old workflow for invoking tidy from a non-std directory, then the interim workaround would be to add an appropriate prefix to the path to `tidy`.

E.g. if I used to do `../x.py test src/tools/tidy`, then I should now start doing `../x.py test ../src/tools/tidy` (at least until some PR, perhaps this one, lands that fixes #48268)

But from my own local experimentation, the above assertion is not correct:

```
% pwd
/Users/fklock/Dev/Mozilla/rust.git/objdir-dbgopt
% ../x.py test ../src/tools/tidy
Updating submodules
    Finished dev [unoptimized] target(s) in 0.0 secs
Warning: no rules matched objdir-dbgopt/../src/tools/tidy.
Build completed successfully in 0:00:05
% ../x.py test src/tools/tidy
Updating submodules
    Finished dev [unoptimized] target(s) in 0.0 secs
Warning: no rules matched objdir-dbgopt/src/tools/tidy.
Build completed successfully in 0:00:04
```

**Comment by Mark-Simulacrum** [comment]
Ah, we needed to path-clean those. I was close, but I guess we don't consider those two paths equivalent.

**Pull request merged**
