### PR TITLE
Bump bootstrap compiler to 1.69 beta

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @pietroalbini

### CODE REVIEW

**Comment by klensy** [comment]
This too?
https://github.com/rust-lang/rust/blob/9b60e6c68ff0aabad9a0edd71898466886dbf6bb/library/core/src/intrinsics.rs#L1623-L1630

**Comment by Mark-Simulacrum** [comment]
stdarch can self-own bumping those, we don't typically touch submodules as part of these bumps.

The roundeven functions are likely recently added (in https://github.com/rust-lang/rust/pull/95317) even though the commit is pretty old, so my guess is they're probably fine to bump next cycle.

**Comment by Mark-Simulacrum** [comment]
@bors retry

I doubt this is spurious, but feels likely to be very annoying to track down so want to get another datapoint.

**Comment by ehuss** [comment]
`no more archived files` happens fairly often (#108862).

**Pull request merged**
