### PR TITLE
Force-inline `shallow_resolve` at its hottest call site.

### PR DESCRIPTION
**Pull request by nnethercote**
It's a ~1% win on `keccak` and `inflate`.

### CODE REVIEW

**Comment by nnethercote** [comment]
@rust-timer build 55fa515

**Comment by nnethercote** [comment]
@rust-timer build 55fa5150e491e8e5ce6936b862f4878fd3126ffc

**Comment by nnethercote** [comment]
From the comparison URL, these are the ones that I am confident are not noise:
```
keccak-check
        avg: -1.1%      min: -1.6%      max: 0.1%
inflate-check
        avg: -1.1%      min: -1.5%      max: -0.0%
keccak-debug
        avg: -0.8%      min: -1.4%      max: -0.1%
keccak-opt
        avg: -0.8%      min: -1.3%      max: -0.0%
inflate-debug
        avg: -0.9%      min: -1.2%      max: -0.5%
```

**Comment by nnethercote** [comment]
It's been a week and this is a tiny change. Let's try a different reviewer: r? @varkor

**Comment by varkor** [comment]
Some nice gains here! @bors r+ rollup

**Comment by nnethercote** [comment]
Thank you for the fast review.

**Pull request merged**
