### PR TITLE
When a codegen worker has a FatalError, propagate it instead of ICE'ing.

### LINKED ISSUE #66530: ICE when rustc asked to `-o /dev/null` on OSX
Ok, so rustc outputting to /dev/null is a bit pathelogical but it used to not ICE the compiler.

If you checkout 

https://github.com/jethrogb/rust-reduce/tree/master/tests/suite/futures_core

and from dir tests/suite/futures_core run:

rustc --crate-type lib -o /dev/null input.rs

Then rustc is vexed:

```
error: failed to write bytecode to /dev/null.input.3a1fbbbh-cgu.3.rcgu.bc.z: Permission denied (os error 13)

error: failed to write bytecode to /dev/null.input.3a1fbbbh-cgu.0.rcgu.bc.z: Permission denied (os error 13)

error: failed to write bytecode to /dev/null.input.3a1fbbbh-cgu.4.rcgu.bc.z: Permission denied (os error 13)

error: failed to write bytecode to /dev/null.input.3a1fbbbh-cgu.7.rcgu.bc.z: Permission denied (os error 13)

thread '<unnamed>' panicked at 'src/librustc_codegen_ssa/back/write.rs:1544: worker thread panicked', src/librustc/util/bug.rs:37:26
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc_codegen_ssa::back::write::start_executing_work::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic
```
(ICEs on stable and nightly)

The irony is that this is in the test suite of a rust code minimisation project.... 🤣 🤣 🤣 

Let me minimise the reproduction of the problem...

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix #66530

### CODE REVIEW

**Comment by pnkfelix** [comment]
(I'm a little worried about the test being fragile, in terms of its output. I tried making this a `compile-fail` test instead of a ui test, but when I did that, it seemed like ICE'ing is considered an acceptable outcome for a `compile-fail` test, as long as the error-pattern matches...


... (which sounds like a bug, if you ask me. We may want to look into changing that, to avoid having hidden ICE's in the compile-fail test suite.)

**Comment by matthewjasper** [comment]
> I guess I could/should look into trying to do some custom normalization of the test output to side-step the fragility regarding the details of the error output.

You could also use `// dont-check-compiler-stderr`

**Comment by pnkfelix** [comment]
> You could also use `// dont-check-compiler-stderr`

No, that is too broad (I explicitly double-checked just now).

Specifically, it will miss the ICE itself.

(Note that in this particular example, we are always *getting* the desired diagnostic from the worker thread. The only problem is that the coordinating thread is ICE'ing, because that code was written assuming that an error from the worker must correspond to a panic.)

But I think `// normalize-stderr-test`  will serve my purposes just fine.

**Comment by pnkfelix** [comment]
sigh, gotta ignore wasm for some reason ...

**Comment by pnkfelix** [comment]
what ...? But I thought I fetched ... hmm. Well, okay, that teaches me to force-push without reviewing more carefully.

**Comment by pnkfelix** [comment]
I go around *claiming* I'm going to be careful about force-pushing, but next thing I know, I've blown away the version of the file that actually properly "worked" on Mac OS X and Linux ...

Sigh.

**Pull request merged**
