### PR TITLE
[llvm-wrapper] adapt for LLVM API change

### PR DESCRIPTION
**Pull request by krasimirgg**
for https://github.com/llvm/llvm-project/commit/feda983ff89b7be27a9bfabbabce7d2b59869eba.

### CODE REVIEW

**Comment by krasimirgg** [comment]
@nikic : if this looks good could you also add the llvm-main label to this PR

**Comment by nikic** [comment]
@krasimirgg Done, but it like it should be settable via rustbot now: https://github.com/rust-lang/rust/commit/9eb977bec440cf8610b9e687146c510f8a2fbf7c

**Pull request merged**
