### PR TITLE
update Nomicon and Reference

### PR DESCRIPTION
**Pull request by RalfJung**
Cc @Centril

### CODE REVIEW

**Comment by RalfJung** [comment]
I included the whitespace fix.

@bors r=Centril

**Comment by RalfJung** [comment]
@bors r-
linkcheck failed

**Comment by ehuss** [comment]
I normally update the books today (1 week before release).  Do you know if the nomicon will be fixed within the next day?  Can you include all the other books? rust-by-example is also broken. I posted a pr to fix it, but I'm not sure how long it will take to get merged.

**Comment by RalfJung** [comment]
@bors r=Centril

The nomicon should be fixed now. I'm afraid I don't have the time to also look into the other books, but if you want I can close this PR and you can do your usual procedure.

**Pull request merged**
