### PR TITLE
Remove unneeded macro witchery

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by huonw** [comment]
Does this have the same performance as the old version? (It certainly looks like it *should*, but that doesnt't mean that it actually does.)

**Comment by tbu-** [comment]
@huonw I don't know, but it should. The functions are marked as `#[inline]`, and then it's just like the code was written where the functions are invoked.

**Comment by huonw** [comment]
Yes, as I said that's the theory, but the practice may not match that.

**Comment by huonw** [comment]
It'd be good to at least run a (can be out-of-tree) microbenchmark of say `for c in s.chars() { black_box(c) }` on one or two strings. (The `str` tests  in libcollections contain some strings with non-ASCII data if you need an example.)

**Comment by tbu-** [comment]
I'm consistently getting worse results for the new solution...

    running 2 tests
    test bench::bench_new ... bench:      5439 ns/iter (+/- 163) = 11 MB/s
    test bench::bench_old ... bench:      5307 ns/iter (+/- 30) = 12 MB/s

**Comment by bluss** [comment]
I don't think 12 MB/s is a reasonable number anyway, we need to examine that benchmark.

**Comment by tbu-** [comment]
With `#[inline(always)]` the results are a bit closer together:

    running 2 tests
    test bench::bench_new ... bench:      5392 ns/iter (+/- 46) = 12 MB/s
    test bench::bench_old ... bench:      5315 ns/iter (+/- 21) = 12 MB/s

The benchmark can be found here: https://gist.github.com/tbu-/c49e5a5ec4a4426b6d75

**Comment by alexcrichton** [comment]
@tbu- are you perhaps forgetting to optimize the benchmark you gave? I'm getting some pretty wildly different results here:

```
$ rustc bench.rs --test -O       
$ ./bench --bench 
running 2 tests
test bench::bench_new ... bench:        49 ns/iter (+/- 1) = 1326 MB/s
test bench::bench_old ... bench:        49 ns/iter (+/- 2) = 1326 MB/s

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured
```

**Comment by tbu-** [comment]
@alexcrichton Indeed. I somehow assumed that `--bench` would behave exactly as in `cargo`.

So this seems safe to merge.

**Comment by huonw** [comment]
@tbu- thanks for checking that! :)

**Pull request merged**
