### PR TITLE
Update Cargo to ffab51954ec32d55631c37a8730bb24915fc090b

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/rust-lang/cargo/pull/4123 added the `[patch]` section of the manifest

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
 Downloading rustc-serialize v0.3.24
error: unable to get packages from source
Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.)
```
Temporary network failure?

**Comment by kennytm** [comment]
```
[01:32:09] invalid license Apache-2.0 / MIT in /checkout/obj/build/tmp/distcheck/src/vendor/fnv/Cargo.toml
[01:32:09] some tidy checks failed
```

**Comment by SimonSapin** [comment]
I couldn’t reproduce the failure locally with `./x.py test src/tools/tidy`, so here is a “blind” edit. r?

**Comment by SimonSapin** [comment]
```
[00:06:08] ERROR: An error was encountered with the build.
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20170721.103231
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_isl_get[scripts/build/companion_libs/121-isl.sh@741]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@591]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 4:36.45)
[04:37] / make: *** [build] Error 1
[00:06:08] The command '/bin/sh -c ./build-s390x-toolchain.sh' returned a non-zero code: 1
```

Any idea?

**Comment by SimonSapin** [comment]
Same failure in https://github.com/rust-lang/rust/pull/43343#issuecomment-316961960, it seems nothing can land at the moment.

**Comment by aidanhs** [comment]
@bors retry

(a current retried build appears to have got past the issue, so the cached dockerfile should be used from now on which will hopefully resolve the issue)

**Comment by kennytm** [comment]
`x86_64-unknown-linux-musl` stage2-std test failed, feels like spurious. Not sure if the panic is relevant. 

```
[01:06:09] thread '<unnamed>' panicked at 'explicit panic', /checkout/src/liballoc/../liballoc/tests/slice.rs:1194:16
...
[01:06:10] (B[m[31m[1merror:(B[m An unknown error occurred
[01:06:10] (B[m
[01:06:10] To learn more, run the command again with --verbose.
[01:06:10] 
[01:06:10] 
[01:06:10] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-j" "4" "--target" "x86_64-unknown-linux-musl" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--features" "panic-unwind jemalloc backtrace" "-p" "std:0.0.0" "-p" "core:0.0.0" "-p" "unwind:0.0.0" "-p" "rustc_asan:0.0.0" "-p" "panic_abort:0.0.0" "-p" "rustc_tsan:0.0.0" "-p" "compiler_builtins:0.0.0" "-p" "rand:0.0.0" "-p" "rustc_lsan:0.0.0" "-p" "rustc_msan:0.0.0" "-p" "alloc_system:0.0.0" "-p" "std_unicode:0.0.0" "-p" "collections:0.0.0" "-p" "libc:0.0.0" "-p" "alloc:0.0.0" "--"
```

**Comment by alexcrichton** [comment]
@bors: retry

* likely a musl segfault - https://github.com/rust-lang/rust/issues/38618

**Pull request merged**
