### PR TITLE
Use allow(unused_imports) instead of cfg(doc) for imports used only for intra-doc links

### PR DESCRIPTION
**Pull request by jyn514**
This prevents links from breaking when items are re-exported in a
different crate and the original isn't being documented.

Spotted in https://github.com/rust-lang/rust/pull/75832#discussion_r475275837 (thanks ollie!)

r? @ollie27

### CODE REVIEW

**Comment by ollie27** [comment]
Yeah, there are currently broken links on https://doc.rust-lang.org/nightly/std/intrinsics/fn.atomic_xchg.html which this should fix.

@bors r+ rollup

**Comment by jyn514** [comment]
I'm a little confused how this slipped through CI ... the place where this breaks is when documenting a re-export in `std`, right? So it seems strange it wasn't caught by `x.py doc library/std` :/

**Comment by ollie27** [comment]
We're explicitly ignoring warnings from other crates:

https://github.com/rust-lang/rust/blob/5180f3da5fd72627a8d38558ad1297df38793acd/src/librustdoc/passes/collect_intra_doc_links.rs#L952-L954

**Comment by jyn514** [comment]
Yup, that would do it. We should probably close https://github.com/rust-lang/rust/issues/56922 as fixed, then. I'll make a PR with a test case.

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/75862#issuecomment-678864726
@bors r-

**Comment by jyn514** [comment]
@JohnTitor I pushed a commit which I hope will fix it, but I'm not sure how to test thumb targets locally ... `x.py doc library/std --target thumbv8m.main-none-eabihf` panics at `couldn't find required command: "arm-none-eabi-gcc"`. Do you have any suggestions?

**Comment by jyn514** [comment]
well, I'll ask bors to test in the meantime and if it fails, it fails.

@bors r=ollie27 rollup=iffy

**Comment by JohnTitor** [comment]
@jyn514 I don't familiar with that target so let's ask bors :)

**Pull request merged**
