### PR TITLE
turn `invalid_type_param_default` into a `FutureReleaseErrorReportInDeps`

### LINKED ISSUE #27336: Tracking Issue for RFC 213: Default Type Parameter Fallback
2024-07-15: This feature (`default_type_parameter_fallback`) is slated for removal, but that is currently blocked on too many [crater regressions](https://github.com/rust-lang/rust/pull/127655#issuecomment-2228285460).

-----

EDIT: this issue has been stalled on disagreements about how to handle a nasty problem found during implementation. [See the internals thread where this was detailed and discussed](https://internals.rust-lang.org/t/interaction-of-user-defined-and-integral-fallbacks-with-inference/2496).

-----

This is a tracking issue for [RFC 213](https://github.com/rust-lang/rfcs/blob/master/text/0213-defaulted-type-params.md). 

The initial implementation of this feature has [landed](https://github.com/rust-lang/rust/pull/26870).

cc @nikomatsakis

### PR DESCRIPTION
**Pull request by RalfJung**
@rust-lang/types I assume the plan is still to disallow this? It has been a future-compat lint for a long time, seems ripe to go for hard error.

However, turns out that outright removing it right now would lead to [tons of crater regressions](https://github.com/rust-lang/rust/pull/127655#issuecomment-2228285460), so for now this PR just makes this future-compat lint show up in cargo's reports, so people are warned when they use a dependency that is affected by this.

Fixes https://github.com/rust-lang/rust/issues/27336 by removing the feature gate (so there's no way to silence the lint even on nightly)
CC https://github.com/rust-lang/rust/issues/36887

### CODE REVIEW

**Comment by compiler-errors** [comment]
I'm in favor of this change, and I think we should make this into a hard error (or bump it to deny, if there's significant fallback). Furthermore, I feel like we should go ahead and mark `default_type_parameter_fallback` feature as *removed* gate since it's essentially abandoned and needs significant reworking on the types side.

**Comment by RalfJung** [comment]
@craterbot check

@compiler-errors is there code inside the type/trait system that becomes dead when `default_type_parameter_fallback` is removed? I won't be able to clean up things that deep in the compiler. Just removing the feature is easy, of course.

**Comment by lcnr** [comment]
> @compiler-errors is there code inside the type/trait system that becomes dead when `default_type_parameter_fallback` is removed? I won't be able to clean up things that deep in the compiler. Just removing the feature is easy, of course.

did a quick look through the code, it does not seem like it

**Comment by RalfJung** [comment]
Ah, it's our old friend `typemap`... our favorite unmaintained widely-used crate.

**Comment by compiler-errors** [comment]
@RalfJung: You should still be able to remove the feature gate and clean up the fallout. Do you still want to do that? Otherwise I can. And I still think we can bump this to deny/FCW/some other lint class.

**Comment by RalfJung** [comment]
I have made the PR just bump up the lint to something that shows up in future-compat reports.

> You should still be able to remove the feature gate and clean up the fallout. Do you still want to do that? Otherwise I can. And I still think we can bump this to deny/FCW/some other lint class.

Ah, because the feature just silences the lint? Sure, can do.

**Comment by RalfJung** [comment]
Okay, should be done. :)

r? @compiler-errors

**Review by compiler-errors — APPROVED** [review]
this bumps a lint version and removes an (unstable) feature gate, so this is probably worth an fcp, unless there is some particular reason you think this needs to land ASAP.

r=me when fcp is done.

**Comment by compiler-errors** [comment]
This PR removes the `default_type_parameter_fallback` feature gate, and bumps `invalid_type_param_default` to an FCW that **does** report in deps.

Given the feature being an (intended) type system feature, this seems to me a pretty clear types FCP.

@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by QuineDot** [comment]
I doubt anyone cares enough to sway this FCP, but [function type parameter defaults act the same as ADT type parameters defaults](https://quinedot.github.io/rust-learning/misc-default-param.html#default-type-parameters-elsewhere) as far as I know.  They're worse off mainly because you can't name function item types.

**Comment by compiler-errors** [comment]
Thanks for the info @QuineDot, but I don't really think users should really be using of default type params on functions anyways. If this is heavily requested, I think we can add this feature gate back with a proper lang team experiment to investigate supporting default params the *right* way (i.e. in a more ergonomic way). 

@bors r+

**Pull request merged**
