### PR TITLE
float types: move copysign, abs, signum to libcore

### PR DESCRIPTION
**Pull request by RalfJung**
These operations are explicitly specified to act "bitwise", i.e. they just act on the sign bit and do not even quiet signaling NaNs. We also list them as ["non-arithmetic operations"](https://doc.rust-lang.org/nightly/std/primitive.f32.html#nan-bit-patterns), and all the other non-arithmetic operations are in libcore. There's no reason to expect them to require any sort of runtime support, and from [these experiments](https://github.com/rust-lang/rust/issues/50145#issuecomment-997301250) it seems like LLVM indeed compiles them in a way that does not require any sort of runtime support.

Nominating for @rust-lang/libs-api since this change takes immediate effect on stable.

Part of https://github.com/rust-lang/rust/issues/50145.

### CODE REVIEW

**Comment by workingjubilee** [comment]
`abs` does not actually require an intrinsic at all and can be redefined in terms of its bit operation, LLVM can promote such to fabs: https://github.com/llvm/llvm-project/commit/5c0da5839de1

I was working on PRing this with some tests to validate that no calls to `__builtin_fabs` or such were generated.

**Comment by workingjubilee** [comment]
That said, we can always read the source.
The libcall lowering is here: https://github.com/llvm/llvm-project/blob/461274b81d8641eab64d494accddc81d7db8a09e/llvm/lib/CodeGen/IntrinsicLowering.cpp#L202

It does not generate libcalls for fabs, but it does for fcopysign.

**Comment by RalfJung** [comment]
> It does not generate libcalls for fabs, but it does for fcopysign.

Then either things changed since @Urgau made their experiments or there are some other factors involved...

FWIW we could also implement `copysign` fairly trivially ourselves:
```rust
let sign_bit = mem::size_of::<Self>)*8 - 1;
Self::from_bits(self.abs().to_bits() | (sign.to_bits() & (1 << sign_bit))
```

**Comment by workingjubilee** [comment]
> Then either things changed since @Urgau made their experiments or there are some other factors involved...

@RalfJung Architecture and size of the float, the latter of which has become particularly relevant for f128... I believe a lot of things that "shouldn't" generate libcalls nonetheless _do_ for f128.

**Comment by workingjubilee** [comment]
my implementation of copysign was
```rust
        let sign = sign.abs().to_bits() ^ sign.to_bits();
        Self::from_bits(self.to_bits() | sign)
```

**Comment by RalfJung** [comment]
Judging from the f16/f128 comments, we do already have things in libcore that generate calls -- I see comments about missing ``{eq,gt,unord}tf`` or `eqtf2`, so seemingly even `==` or `<` can generate libcalls.  So that shouldn't be a blocker. Also, these are unstable anyway.

Cc @tgross35

**Comment by workingjubilee** [comment]
We "just" need to make sure that compiler_builtins supports the relevant libcall.

**Comment by RalfJung** [comment]
> my implementation of copysign was

If `self` is negative, `self.to_bits() | sign` will always remain negative, won't it? So this implementation doesn't seem right to me.

**Comment by workingjubilee** [comment]
Oh, you're right, I meant `self.to_bits().abs() | sign`

**Comment by RalfJung** [comment]
> We "just" need to make sure that compiler_builtins supports the relevant libcall.

I don't see any `copysign` implementations there.
I was hoping this would be a quick PR... so I'll stop here, unless someone wants to make a compiler-builtins PR.

**Comment by workingjubilee** [comment]
@RalfJung If you cut this down to fabs then I'll go pick up the copysign works.

**Comment by tgross35** [comment]
`fabs` and `copysign` are in the `libm` repo, not `compiler-builtins`. Hm... `libm` isn't nearly as thoroughly tested as `compiler-builtins`. I'm working on improving this, but it is part of the reason we don't have the other `math.h` functions in `core` yet. These functions are probably low risk but is there a way to have this not be insta-stable?

`libm` also doesn't have `f128` support yet (also a WIP) but there isn't any reason not to just leave the fallbacks there for now.

**Comment by workingjubilee** [comment]
As-mentioned, I am absolutely okay with this landing as-is for fabs, because it won't (except if it legalizes the bitops to `@llvm.fabs` it might hypothetically do the resizing thing for f16, which is a hypothetical pessimization, but whatever, this isn't about _good_ code, just code that links correctly).

**Comment by workingjubilee** [comment]
Apologies for holding up the works.

I believe I was mislead by the dead rising again in a hollow mockery of the living, and will pursue turning them away upstream: https://github.com/llvm/llvm-project/pull/111269

**Comment by RalfJung** [comment]
> fabs and copysign are in the libm repo, not compiler-builtins

That's odd, why would `eq` and similar functions be in compiler-builtins but the much simpler fabs/copysign are in libm?

**Comment by RalfJung** [comment]
> I believe I was mislead by the dead rising again in a hollow mockery of the living, and will pursue turning them away upstream:

Ah, so these libcalls are likely not *actually* used?

> I was working on PRing such with some tests to validate that no calls to __builtin_fabs or such were generated.

Maybe we should have that first before moving these things to libcore. So if you have a good idea for how to write such a test, I'll happily wait for that. :)

**Comment by tgross35** [comment]
> That's odd, why would `eq` and similar functions be in compiler-builtins but the much simpler fabs/copysign are in libm?

It just mirrors how things are split in the C world - `compiler-builtins` provides the same symbols as LLVM's `compiler-rt` or `libgcc`, `libm` provides whatever is in `math.h`. We actually ship `libm` as a module of `compiler-builtins` and are probably somewhat close to making the symbols always weakly available (we actually had this a few months ago but reverted since our symbols were getting picked first, https://github.com/rust-lang/rust/issues/128386).

Looking at `compiler-rt` it doesn't define `copysign` anywhere but _does_ make use of `__builtin_copysign`. I assume this has to just be getting lowered to asm since I don't think clang can rely on libm being available. Maybe a good sign that it doesn't ever make this a libcall...

**Comment by workingjubilee** [comment]
> Ah, so these libcalls are likely not actually used?

Yes, my understanding is that the codepath that does "libcall legalization" of intrinsics happens "last" (speaking very, very loosely) during lowering to the machine level, and thus has several possible upstream chances to "get missed". For instance, maybe LLVM notices a call to copysign can use one of the FSGNJ* instructions on RISCV (a somewhat odd set of instructions that compose two floats with one of three bitops). I couldn't find something in SelectionDAG that *guarantees* we never hit the switch into `Intrinsic::copysign`, but I am fully willing to believe one exists somewhere in the remaining 1.99 million lines of code I didn't read, and if my PR is accepted and I am wrong then we'll find out because someone's LLVM choked on it.

**Comment by cuviper** [comment]
r? libs-api

**Comment by RalfJung** [comment]
@workingjubilee so what's the status here now -- after you dug more into this, are you now sure that we get copysign lowering without a libcall on all relevant platforms and supported LLVM versions, or not?

**Comment by workingjubilee** [comment]
> @workingjubilee so what's the status here now -- after you dug more into this, are you now sure that we get copysign lowering without a libcall on all relevant platforms and supported LLVM versions, or not?

Yes, I am certain now.

**Comment by RalfJung** [comment]
Okay. :)

@rust-lang/libs-api based on that, are you okay with moving these functions to libcore?

**Comment by workingjubilee** [comment]
To explain why I am certain:

The reason `@llvm.copysign.{float}` lowers to `call {float} @copysignl` _sometimes_ is because one can use `@llvm.copysign.ppcf128`, AKA the "double double". We do not have `long double` or `__ibm128` in the language, so we do not have to worry about this, as that is the only type affected. Even if it _did_ affect us, it could only affect `f128`... and no, there is no implicit conversion of `f128` to `ppcf128`... and PowerPC targets are trying to migrate `long double` from "double double" to real `binary128` support.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting. In the end we will want to support all of the math functions in core anyways, so this is a good step forward.

@rfcbot fcp merge

**Comment by RalfJung** [comment]
@dtolnay I resolved the conflicts, so this should be ready for review. :)

It's going to be out of FCP soon.

**Comment by cuviper** [comment]
Can we now fix this?

https://github.com/rust-lang/rust/blob/de27914e8e6c5f8a02698a8ed9b318df17f2f621/library/core/src/num/f64.rs#L527-L534

**Comment by RalfJung** [comment]
Good point -- yes we can. :) I had to add some `rustc_allow_const_fn_unstable` for this, so Cc @rust-lang/wg-const-eval. It's completely harmless since those intrinsics can be implemented via `to_bits` and `from_bits` fairly easily.

@cuviper  Would you like to take over reviewing this PR? :D

**Comment by tgross35** [comment]
I don't believe this needs libs-api review since FCP completed https://github.com/rust-lang/rust/pull/131304#issuecomment-2452934402. The new use of `const_float_methods` seems acceptable, especially considering that feature just went into FCP https://github.com/rust-lang/rust/issues/130843#issuecomment-2474061661.

@bors r+

**Comment by lopopolo** [comment]
Hey folks, I recently was making changes to a no std crate and wanted to use `f64::abs`. I was super confused when it didn't compile in my MSRV build since the docs for the f64 primitive show that `abs` is stable since Rust 1.0.0.

I would definitely have appreciated some caveats in the primitive docs for functions that have conditional availability in no std crates based on Rust version!

**Comment by RalfJung** [comment]
Sadly we don't have infrastructure for that. Feel free to open an issue so we can discuss possible ways of handling this. There might even already be done; the keyword here is "path stability" vs "item stability" -- rustdoc can only communicate the latter currently.

**Comment by lopopolo** [comment]
Even free form text in the prose of the doc comment would have solved this for me.

**Comment by lopopolo** [comment]
Filed https://github.com/rust-lang/rust/issues/139066 to discuss.

**Pull request merged**
