### PR TITLE
Stabilize option_insert.

### PR DESCRIPTION
**Pull request by m-ou-se**
FCP finished here: https://github.com/rust-lang/rust/issues/78271#issuecomment-817201319

### CODE REVIEW

**Comment by et342** [comment]
Should this be called `get_replace`?

Say, if we have a box and if we put a `thing` into it, then what we get is a box filled with the `thing`, and not the `thing` itself. But, we do get the thing here, so prefix `get_` seems appropriate. But, `get_insert` does not seems appropriate, because if box is filled − then we cannot insert, we can only replace and replacement is what is what's happening here, so `get_replace`.

**Comment by m-ou-se** [comment]
@et342 Comments on the stabilization PR tend to not get a lot of attention. If you want to discuss the feature, it's better to comment on the [tracking issue](https://github.com/rust-lang/rust/issues/78271).

**Comment by et342** [comment]
@m-ou-se Ah, ok. Thank you. Thought since it says comment period is over on the tracking issue, concern should be directed here.

**Comment by m-ou-se** [comment]
(see https://github.com/rust-lang/rust/issues/78271#issuecomment-820240251)

@bors r+ rollup

**Pull request merged**
