### PR TITLE
Ignore expected type in diverging blocks

### PR DESCRIPTION
**Pull request by canndrew**
As per comment: https://github.com/rust-lang/rust/issues/39297#issuecomment-276810343

### CODE REVIEW

**Comment by eddyb** [comment]
r? @nikomatsakis 

Also, please use a more descriptive title (e.g. "Allow diverging blocks to have a type different than that of their trailing expression." but that's maybe too long).

**Comment by nikomatsakis** [comment]
@canndrew instead of removing the affected tests, can you move at least one of them into a `run-pass` test, with a comment explaining why the code now type-checks?

**Comment by nikomatsakis** [comment]
cc @eddyb

**Comment by nikomatsakis** [comment]
Oh, I see he already commented =)

**Comment by nikomatsakis** [comment]
It occurs to me that we perhaps ought to crater this too. That is, I guess that this can lead to types becoming constrained that were not otherwise (as we saw in #39009).

**Comment by canndrew** [comment]
Is there a way to skip debuginfo tests when testing rustc? They always fail for me and it throws me off because sometimes I think the other tests have succeeded when I've gotten that far.

As for the failing run-pass tests. This now fails (unable to infer enough type information for `E`)

```rust
fn foo() -> Result<Foo, isize> {
    return Ok(Foo {
        x: Bar { x: 22 },
        a: return Err(32)
    });
}
```

Which is unfortunate. Shouldn't inference be able to infer that the `Ok` being returned has the type of the return of type?

Also, this now fails (unable to infer enough type information for `_`):

```rust
pub fn index_colors<Pix>(image: &ImageBuffer<Pix, Vec<u8>>)
                         -> ImageBuffer<Luma<u8>, Vec<u8>>
where Pix: Pixel<Subpixel=u8> + 'static,
{
    let mut indices: ImageBuffer<_,Vec<_>> = loop { };
    for (pixel, idx) in image.pixels().zip(indices.pixels_mut()) {
        // failured occurred here ^^ because we were requiring that we
        // could project Pixel or Subpixel from `T_indices` (type of
        // `indices`), but the type is insufficiently constrained
        // until we reach the return below.
    }
    indices
}
```

Which makes sense, but is also unfortunate.

**Comment by nikomatsakis** [comment]
@canndrew 

> Shouldn't inference be able to infer that the Ok being returned has the type of the return type?

Well, the whole change here is basically that **it doesn't have to**. (Since it is dead-code.) 

cc @eddyb -- it makes sense that this would be causing some back-compat issues, but it's a drag. Definitely have to do a crater run I guess.

**Comment by nikomatsakis** [comment]
Started a crater run.

**Comment by nikomatsakis** [comment]
[Crater run results](https://gist.github.com/nikomatsakis/101baa09d8a874d18e2f3fb5298668b9):

* [rustc-serialize-0.3.22](https://crates.io/crates/rustc-serialize) ([before](https://tools.taskcluster.net/task-inspector/#E1g2M1PUQb6bRzVzMkIAdg)) ([after](https://tools.taskcluster.net/task-inspector/#V9H8Dwk4SICvZmkrrTSivA))
* [glium-0.16.0](https://crates.io/crates/glium) ([before](https://tools.taskcluster.net/task-inspector/#mQN2o4b7SfG_QgcYt8FnUA)) ([after](https://tools.taskcluster.net/task-inspector/#YvBZihpyThCubdlB53h76A))
* [libimagstore-0.2.0](https://crates.io/crates/libimagstore) ([before](https://tools.taskcluster.net/task-inspector/#QSipIBPZQjaZiVF59kikCQ)) ([after](https://tools.taskcluster.net/task-inspector/#wl3S7V8USlK7KBIutjUyGg))
* [unicode-segmentation-1.1.0](https://crates.io/crates/unicode-segmentation) ([before](https://tools.taskcluster.net/task-inspector/#icRFEEbRTiSLjcylHvPHOA)) ([after](https://tools.taskcluster.net/task-inspector/#GhWSO5vlRze80d2rIKcEmQ))
* [log4rs-0.5.2](https://crates.io/crates/log4rs) ([before](https://tools.taskcluster.net/task-inspector/#khgUD0AEQkSclUKXVTvYYg)) ([after](https://tools.taskcluster.net/task-inspector/#NopBS74wR7a1_I2v508Nuw))
* [mime_guess-1.8.1](https://crates.io/crates/mime_guess) ([before](https://tools.taskcluster.net/task-inspector/#e4iaH_YjSQSdPUdMDRimNA)) ([after](https://tools.taskcluster.net/task-inspector/#2tz_pw7gRT-_ZXQMbLRAxw))
* [primal-bit-0.2.3](https://crates.io/crates/primal-bit) ([before](https://tools.taskcluster.net/task-inspector/#J0DZ1WGxQPetLwzqdL4n_Q)) ([after](https://tools.taskcluster.net/task-inspector/#qXmKG40dTBmrlNoPTbjEIQ))
* [gpg-error-0.2.1](https://crates.io/crates/gpg-error) ([before](https://tools.taskcluster.net/task-inspector/#xBntRr7STByYjVmwy3efVA)) ([after](https://tools.taskcluster.net/task-inspector/#3UmBT0wfSmqh5ReyACSmdw))
* [hoodlum-parser-0.5.0](https://crates.io/crates/hoodlum-parser) ([before](https://tools.taskcluster.net/task-inspector/#wCDeD0iCRsO10Peo9CHSDQ)) ([after](https://tools.taskcluster.net/task-inspector/#Z-hypMk4RPyuoQZRoVq_EA))
* [secrets-0.11.1](https://crates.io/crates/secrets) ([before](https://tools.taskcluster.net/task-inspector/#6nP4c8zgSy6jebvvTe68vw)) ([after](https://tools.taskcluster.net/task-inspector/#rmYTrcF1RUWzL4rDOwzKzw))
* [eval-0.3.2](https://crates.io/crates/eval) ([before](https://tools.taskcluster.net/task-inspector/#XOzGipA2RQm3ye7c52pWwA)) ([after](https://tools.taskcluster.net/task-inspector/#7r-W4nz3RNydQlJlbzuMjQ))
* [xz-embedded-sys-0.1.1](https://crates.io/crates/xz-embedded-sys) ([before](https://tools.taskcluster.net/task-inspector/#IFMJF624RNyea6M27TdQtg)) ([after](https://tools.taskcluster.net/task-inspector/#WHWD8WIHTD2HA1ISoBq_ow))
* [hetu-0.3.0](https://crates.io/crates/hetu) ([before](https://tools.taskcluster.net/task-inspector/#NON1kR2sQIKHhpqtPdDHEw)) ([after](https://tools.taskcluster.net/task-inspector/#-T__MucQRmK3SXgLnBgB4A))
* [cargo-release-0.7.0](https://crates.io/crates/cargo-release) ([before](https://tools.taskcluster.net/task-inspector/#Ec4zDwBCRDmq98V3h_w3NQ)) ([after](https://tools.taskcluster.net/task-inspector/#qXHXDZRAQc66CgYMaraqQg))
* [imag-0.2.0](https://crates.io/crates/imag) ([before](https://tools.taskcluster.net/task-inspector/#xOlo6uq6SkWW6jAToY4kSA)) ([after](https://tools.taskcluster.net/task-inspector/#8CTVeCFlQYmNA_-i92gzzQ))
* [imag-counter-0.2.0](https://crates.io/crates/imag-counter) ([before](https://tools.taskcluster.net/task-inspector/#t6g6O_HyQ8Gr0Nrubu1y9Q)) ([after](https://tools.taskcluster.net/task-inspector/#rc-L8Wj9SD-QeCt5TrnGlg))
* [ip6gen-0.0.2](https://crates.io/crates/ip6gen) ([before](https://tools.taskcluster.net/task-inspector/#pD5NvxySRG6gvk0ZOR5Hgg)) ([after](https://tools.taskcluster.net/task-inspector/#PV9eOxuKRjKjZjGRbedTrg))
* [disassemble-0.0.1](https://crates.io/crates/disassemble) ([before](https://tools.taskcluster.net/task-inspector/#_3RwQqmDSsmDauJLJtUUcw)) ([after](https://tools.taskcluster.net/task-inspector/#QvBRoCojRVyxm_2bu6yTEA))
* [dotfiler-0.1.0](https://crates.io/crates/dotfiler) ([before](https://tools.taskcluster.net/task-inspector/#HO2rdR8TRUKH7-vas7MvRg)) ([after](https://tools.taskcluster.net/task-inspector/#DJqxAkxlR0uyvWWpRFYVxg))
* [lion-0.0.0](https://crates.io/crates/lion) ([before](https://tools.taskcluster.net/task-inspector/#kueBKOfnTnGUi_lfyZ5RDg)) ([after](https://tools.taskcluster.net/task-inspector/#5abVjCbDQCW1-j4AuxeRjQ))
* [mdblog-0.1.8](https://crates.io/crates/mdblog) ([before](https://tools.taskcluster.net/task-inspector/#y22QQGF6RJKO2AkNHsbVRA)) ([after](https://tools.taskcluster.net/task-inspector/#kFluLv-GRaWny1pks3Q3Fg))
* [chromaprint-0.1.2](https://crates.io/crates/chromaprint) ([before](https://tools.taskcluster.net/task-inspector/#naqiz4jeQDWAhi_-3g_PyQ)) ([after](https://tools.taskcluster.net/task-inspector/#vjj2G5zjTEykZUJcGM5FEA))
* [energymon-sys-0.1.0](https://crates.io/crates/energymon-sys) ([before](https://tools.taskcluster.net/task-inspector/#umExzg3bTluHEo0Mz_OHiA)) ([after](https://tools.taskcluster.net/task-inspector/#5pkB2i8lT-GtFXUl-uVu3Q))
* [fiber-0.1.0](https://crates.io/crates/fiber) ([before](https://tools.taskcluster.net/task-inspector/#U3wM1Z-6QCGqkGHIXTWgiQ)) ([after](https://tools.taskcluster.net/task-inspector/#18sZZZfXSbGy4AChEBlerw))
* [rand-pop-0.1.1](https://crates.io/crates/rand-pop) ([before](https://tools.taskcluster.net/task-inspector/#G9ax0wuZTcCUoG1U7Ytt8Q)) ([after](https://tools.taskcluster.net/task-inspector/#Yr-jMyckS8-gFdGPzb8rOQ))
* [gamma-lut-0.1.6](https://crates.io/crates/gamma-lut) ([before](https://tools.taskcluster.net/task-inspector/#rnGsP-1xQFeqeqdyp6q_yQ)) ([after](https://tools.taskcluster.net/task-inspector/#mjnpznqXSBGzDua-OA586A))
* [glutin_cocoa-0.1.6](https://crates.io/crates/glutin_cocoa) ([before](https://tools.taskcluster.net/task-inspector/#mEyXVOe0ST-ZLTXTs2vQ1g)) ([after](https://tools.taskcluster.net/task-inspector/#34yogGN2RDycGCoFSbUS5w))
* [tachyon-0.0.0](https://crates.io/crates/tachyon) ([before](https://tools.taskcluster.net/task-inspector/#OXv0kWaJQOqCWr_j0R0Ivg)) ([after](https://tools.taskcluster.net/task-inspector/#qdOp77zsRVORoxXwVe62Zw))
* [todotxt-0.3.0](https://crates.io/crates/todotxt) ([before](https://tools.taskcluster.net/task-inspector/#qYp-l_-GS426_eTdVDVFOQ)) ([after](https://tools.taskcluster.net/task-inspector/#sD7PZbPrTK2EyKQwUQZbgQ))
* [trace-macro-1.1.1](https://crates.io/crates/trace-macro) ([before](https://tools.taskcluster.net/task-inspector/#XluhGmM_RHO3gSlELWtL4w)) ([after](https://tools.taskcluster.net/task-inspector/#TUF109ntT2e-_hYL4q3quA))
* [twig-0.1.0](https://crates.io/crates/twig) ([before](https://tools.taskcluster.net/task-inspector/#VHup1e1JS2Gkm1TpAAn-Sw)) ([after](https://tools.taskcluster.net/task-inspector/#afYltf9cRyq27vm2Vt8G-A))
* [verbose_bird-0.2.2](https://crates.io/crates/verbose_bird) ([before](https://tools.taskcluster.net/task-inspector/#IUnt_ZMmSL6wtE1i7cpYow)) ([after](https://tools.taskcluster.net/task-inspector/#4fFrAhvKSUC_QKpFPjwu4g))
* [halo-0.1.0](https://crates.io/crates/halo) ([before](https://tools.taskcluster.net/task-inspector/#H1MGbCtMTpysxMAqDXcT6A)) ([after](https://tools.taskcluster.net/task-inspector/#0cGjLUUbRPKoVyEQtgbShA))

**Comment by canndrew** [comment]
I've fixed the two failing tests.

**Comment by nikomatsakis** [comment]
@canndrew ok, well, seems like we might as well go through with this. I feel like the current behavior is pretty inconsistent.

> Of course if we did default to ! in these cases there wouldn't be any regressions. I'm not saying I prefer that solution just that it's a possibility.

I'm not sure I understand what you mean here by "default to `!`".

**Comment by canndrew** [comment]
> @canndrew ok, well, seems like we might as well go through with this. I feel like the current behavior is pretty inconsistent.

Sounds good to me.

> I'm not sure I understand what you mean here by "default to `!`".

I just meant set the type variable which can't be inferred to `!`.

**Comment by nikomatsakis** [comment]
@canndrew I see. Well, I'm not a big fan of that idea, for a couple of reasons. For one thing, it would re-create the problem we are trying to fix here. Consider e.g. something like this:

```rust
let mut v = vec![];
if condition {
    return;
    v.push(vec![]); // this type variable is created in dead code
}
```

Now the type of `v` becomes `Vec<Vec<_0>>` where `_0` is "from dead code", and hence defaults to `!`. But we don't want that type to default to `!`.

In general, the rule of "dead code halts information flow *up* the tree (i.e., from expression to where expression is used)" but not "side-to-side" seems pretty good to me. Among other things, since the code is dead, there is (indeed) no data or information flow up the tree, and we can't know if you intended to add conversion and so forth.

**Comment by nikomatsakis** [comment]
cc @Nercury -- twig-rs may be affected by this change. The testing of the PR got this error:

```
error[E0282]: unable to infer enough type information about `E`
   --> src/nodes/parser/expr.rs:379:5
    |
379 |     Ok(Expr::new_at(
    |     ^^ cannot infer type for `E`
    |
    = note: type annotations or generic parameter binding required
```

This PR affects information flow around dead-code. The problem seems to be that the type of [this variable `arg`](https://github.com/Nercury/twig-rs/blob/master/src/nodes/parser/expr.rs#L349) is "inferred" from an `unimplemented!` macro. The simplest fix is [probably to remove this code](https://github.com/Nercury/twig-rs/blob/master/src/nodes/parser/expr.rs#L379-L387) but some type hints would help.

**Comment by nikomatsakis** [comment]
I'm marking this for relnotes, since it does affect code. The relnotes could read:

"Fixed bugs around how type inference interacts with dead-code. The existing code generally ignores the type of dead-code **unless** a type-hint is provided; this can cause surprising inference interactions particularly around defaulting. The new code uniformly ignores the result type of dead-code."

**Comment by alexcrichton** [comment]
@bors: retry

* appveyor timeout

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Comment by Nercury** [comment]
@nikomatsakis twig was my early Rust project that is not finished and is paused now, so the breakage won't cause any issues

**Comment by golddranks** [comment]
There was some concerns about what is expected breakage and what is not in https://github.com/rust-lang/rust/issues/39984 but I suspect they are more likely to be answered here.

There is this code that returns an `Ok(())` in dead code: https://play.rust-lang.org/?gist=188e52dc2ba423a8f78c6e381f278cf1&version=nightly&backtrace=1 It's broken, because the inference can't infer the `Err(_)` variant anymore. The variant is directly inferrable from the signature of the function that contains the dead code.

So, is it expected breakage that the dead branch of code is 1) required to have fully known types but 2) not type-inferred, unlike live branches, so these dead branches must have additional type annotations, which they wouldn't need if they were live branches?

**Pull request merged**
