### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #119354 (Make `negative_bounds` internal & fix some of its issues)
 - #119414 (bootstrap: Move -Clto= setting from Rustc::run to rustc_cargo)
 - #119420 (Handle ForeignItem as TAIT scope.)
 - #119506 (Use `resolutions(()).effective_visiblities` to avoid cycle errors in `report_object_error`)
 - #119538 (Cleanup error handlers: round 5)
 - #119566 (Remove `-Zdump-mir-spanview`)
 - #119567 (Remove `-Zreport-delayed-bugs`.)
 - #119577 (Migrate memory overlap check from validator to lint)
 - #119586 ([rustdoc] Fix invalid handling for static method calls in jump to definition feature)
 - #119588 (Move `i586-unknown-netbsd` from tier 2 to tier 3 platform support table)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=119354,119414,119420,119506,119538,119566,119567,119577,119586,119588)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Absolutely no idea what caused this failure. Closing for now. Do you have an idea by any chance @fmease?

**Comment by fmease** [comment]
@GuillaumeGomez, I've got it. #117213 changed the order of some diagnostics which affects both #119420 and #119506. I've bors-unapproved them, they just need to rebless stderr.

**Comment by GuillaumeGomez** [comment]
Great, thanks!

**Pull request closed without merging**
