### PR TITLE
[WIP] Impl Debug, Hash, PartialEq, Eq, PartialOrd, Ord, Default for closures

### PR DESCRIPTION
**Pull request by luca-barbieri**
This pull request implements these traits for closures in addition to the Copy and Clone that the compiler already supports, as well as allowing crates to implement their custom traits for closures.

# Motivation

As for motivation, there is the "serde_closure" crate that does this by re-implementing closures with a macro (except it can't automatically detect upvars), and in general Debug is useful for debugging, while the other traits are useful to determine whether instances of a closure are equal, which can allow to avoid re-calling the closure and instead using a memoized result (when the API requires the closure to be a pure function): this is useful for instance for React-like WebAssembly frameworks where a component may take as props closures that generate subcomponents and that should not be called again if props is set to props equal to the old props (which requires an impl of Eq for closures).

# Implementation

This code uses a clever technique that allows to add this feature with minimal effort and maximal flexibility:
1. Each closure now implements a Closure trait
2. The Closure impl has an Inner associated type that consists of a tuple with the same layout of the closure (we use a tuple of the upvars followed by the new marker LayoutAs<T>)
3. We add blanket impls of Debug, Hash, PartialEq, Eq, PartialOrd, Ord, Default for T: Closure conditional on <T as Closure>::Inner implementing the traits (we special-case the Closure trait in coherence.rs to make this work).
4. This results in the already existing implementations for tuples being reused for closures

The advantage of this strategy is that it does not require any code to generate implementations of specific 
traits, and allows to implement custom traits on closures without changing the compiler.

# Drawbacks

The first drawback is that we inherit the tuple length limit on the impls. However, that needs to be fixed for tuples anyway, and the fix will fix closures as well.

Another apparent drawback that should however not be an issue is that we expose closures as tuples, allowing code to know about the upvar types. Since we use a special layout marker that includes the closure type and that can't be instantiated otherwise, this does not limit the ability to do profile-guided layout or in general to change closure layout in an arbitrary way. Also, closures are semantically a tuple of their upvars so exposing this should not be a problem.

We also expose an ordering of the upvars. However, there is a canonical ordering, which is the order of the source code position of the first mention of the upvar, that I hope the compiler is currently using and if so there seems to be no reason to change it.

# Alternatives

Adapting the #[derive] code is not easily possible because it's broken (generates incorrect type bounds) and because it's based on the AST, and in that phase we don't even know what the upvars are.

Generating MIR like for the Clone shim is possible, but it requires ad-hoc code and wouldn't allow to implement for instance the serde traits without adding even more ad-hoc code to the compiler; on the other hand, the approach in this pull request allows to reuse trait implementations for tuples.

# Shortcomings

The current implementation seems to work but has:
- No feature gating, immediately stable
- No RFC
- No tests

# Conclusion

Let me know if this is considered a viable approach, and whether you would like a feature gate, RFC, or tests.

### CODE REVIEW

**Comment by shepmaster** [comment]
Too wide-reaching for me!

r? @BurntSushi

**Comment by BurntSushi** [comment]
This is outside my wheelhouse too. r? @alexcrichton cc @rust-lang/libs 

I wouldn't be surprised if this needs an RFC, since this is adding a lot of impls to a core part of the language.

**Comment by alexcrichton** [comment]
This seems like a neat way to implement closures and add features for closures, thanks for the work here @luca-barbieri!

I think the best way to go about landing this would be to split this into two pieces. One would be updating the compiler and moving the existing clone/copy impls to this new infrastructure, and that would largely require sign-off from the compiler team. For the libs team afterwards we could separately consider adding these new impls. I think the libs team wants to be in the loop on the first part since it'll likely influence the design, but @luca-barbieri how do you feel about that?

**Comment by Centril** [comment]
New stable guarantees about closures, as provided in this PR, will require language team sign-off on an RFC. 

This is far too subtle and has interactions with other parts of the language (e.g. https://github.com/rust-lang/rfcs/pull/2229, tuple variadics, tying the fate to tuples, exposing the type of the upvars, using `#[fundamental]`, lang items, coherence hacks, possibly generic closures (tho on initial inspection it does not seem so), questions around how these interact with async closures, possibly future const closures, etc.) to be decided on through a PR.

cc @rust-lang/lang 

> However, that needs to be fixed for tuples anyway, and the fix will fix closures as well.

There is no current consensus that it needs to be fixed for tuples (e.g. with variadics).

**Comment by luca-barbieri** [comment]
Thank you for your feedback.

I'll look at writing an RFC, although it may take a while until I have time to do so.

**Comment by edmilsonefs** [comment]
Hey! This is a ping from triage, it seems to be a great plan @luca-barbieri. 
Take your time I'm just updating to a more proper label. ;-D

@rustbot modify labels to +S-waiting-on-author, -S-waiting-on-review

**Comment by jesskfullwood** [comment]
Just want to chime in on a use-case for this work.

I have been writing a WASM web framework in Rust along the principles of Elm. The app maintains a virtual dom (VDOM) which mirrors the DOM. There is also a View function which runs whenever some application state changes. It creates a new VDOM, which is diffed with the previous VDOM, and the diffs are applied to the DOM. This is a very common frontend-framework pattern.

Problem - We want to create a closure to act as a listener for e.g. an `onClick` event. That part works fine, but when VDOM-diffing we cannot compare the 'new' closure with the existing one, since they are not `PartialEq`. That means we cannot know if any of the event listeners have changed, so they have to be torn down and rebuilt on every refresh. Ugly and inefficient.

A niche use-case to be sure - for now, at least!

**Comment by eddyb** [comment]
I also have a combinator library for memoized graph-shaped computations (`cyclotron`), which can't be deduplicate work right now (it would need `Eq + Ord` or `Eq + Hash`).

**Comment by eddyb** [comment]
IMO this should be solved properly with VGs ("variadic generics") and some form of (statically typed) closure reflection (could be std/rustc-internal).

We can defer the VG requirement by limiting closures like tuples, e.g. max 12 elements for most traits.

For example, `|| x + y` could automatically (in the compiler) implement:
```rust
#[fundamental]
trait Closure {
    type Captures/*: Tuple*/;
    fn captures_ref(&self) -> &Self::Captures;
}
struct Capture<const NAME: &'static str, T>(T);
```
roughly like this:
```rust
impl Closure for /*typeof(|| x + y)*/ {
    type Captures = (Capture<"x", i32>, Capture<"y", i32>);
    fn captures_ref(&self) -> &Self::Captures {
        // Note that this requires the closure to be represented as its Captures:
        unsafe { &*(self as *const _ as *const _) }
    }
}
```
This is what a std impl based on this form of reflection would look like:
```rust
impl<A, B, const NAME_A: &'static str, const NAME_B: &'static str, C> fmt::Debug for C
where C: Closure<Captures = (Capture<NAME_A, A>, Capture<NAME_B, B>)>,
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let (a, b) = self.captures_ref();
        f.debug_struct("closure").field(NAME_A, a).field(NAME_B, b).finish()
    }
}
```

Of course, there is a lot to bikeshed here, but I think this could work now/soon.

**Comment by joelpalmer** [comment]
Ping from Triage: Hi @luca-barbieri - any update on this?

**Comment by luca-barbieri** [comment]
I'm probably not going to do any further work on this any time soon, so if anyone wants to write an RFC and do further work (e.g adopting @eddyb 's more featureful proposal) they are welcome to do so.

**Comment by Alexendoo** [comment]
Thanks for the work @luca-barbieri, I'll close this as inactive to keep things tidy, if there's any change in the future please feel free to reopen it

**Pull request closed without merging**
