### PR TITLE
[WIP] Swap 1.1.1.1 and 8.8.8.8.

### PR DESCRIPTION
**Pull request by kennytm**
r? @ghost 

Just to check if this could workaround Travis issue 9696.

### CODE REVIEW

**Comment by kennytm** [comment]
| CI | Time | 1.1.1.1 | 1.0.0.1 | 8.8.8.8 | 8.8.4.4 |
|---|---|---|---|---|---|
| PR-CI 1 | 06:59:30 | 52.219.28.41 | 52.219.28.41 | 52.219.24.13 | 52.219.24.13 |
| PR-CI 2 | 06:59:30 | 52.219.28.41 | 52.219.28.41 | 52.219.24.41 | 52.219.24.97 |
| First try 1 | 07:00:15 | 52.219.28.33 | 52.219.28.33 | 52.219.28.41 | 52.219.24.1 |
| First try 2 | 07:00:16 | 52.219.28.33 | 52.219.28.33 | 52.219.24.1 | 52.219.24.1 |
| Second try 1 | 07:18:38 | 54.231.236.45 | 54.231.236.45 | 52.219.20.21 | 52.219.24.129 |
| Second try 2 | 07:18:38 | 54.231.236.45 | 54.231.236.45 | 52.219.20.21 | 52.219.20.1 |

Observations:

* The answers from 1.1.1.1 and 1.0.0.1 seem to be consistent with the same IP, while that from 8.8.8.8 and 8.8.4.4 can produce totally different answers with a few seconds difference (the TTL of this domain is extremely short though).
* A 9696 happened between the two `try` builds. With 1.1.1.1 and 1.0.0.1 we see the IP jumped across an entire /10 net, while 8.8.8.8 still returns 52.219.\*.\*.

I'll try doing a continuous dig and curl for 30 minutes tomorrow, closing for now.

**Comment by pietroalbini** [comment]
Hmm, should we merge the `dig`s into master so we're sure we catch the results during the 9696?

**Comment by kennytm** [comment]
@pietroalbini In https://api.travis-ci.org/v3/job/398515215/log.txt, the network access before 07:05:04Z is completely fine, so adding a `dig` at the beginning may not be useful.

**Comment by pietroalbini** [comment]
@kennytm we can also add it in the `script` section [after the main script is called](https://github.com/rust-lang/rust/blob/acf50b79beb5909c16861cc7c91e8226b7f78272/.travis.yml#L259), that's executed as soon as the main script exits (so as soon as there is a resolve error)

**Comment by kennytm** [comment]
We could add a `dig` check in `after_failure` though the behavior outside and inside docker may be different. For instance the `curl -fs --head https://google.com` in the log above works fine.

**Pull request closed without merging**
