### PR TITLE
Stabilize unit tests with non-`()` return type

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
References #48854

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@nikomatsakis 
>>> error: no rules expected the token `Some`
[00:06:18]    --> libsyntax/feature_gate.rs:611:63
[00:06:18]     |
[00:06:18] 611 |     (accepted, termination_trait_test, "1.27.0", Some(48854), Some(Edition::Edition2018)),
[00:06:18]     |                                                               ^^^^
[00:06:18] 


should it be `None` instead? feels odd :stuck_out_tongue:

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Review by nikomatsakis — APPROVED** [review]

**Pull request merged**
