### PR TITLE
Add Target for aarch64-unknown-uefi

### PR DESCRIPTION
**Pull request by HTGAzureX1212**
This Pull Request adds a new `rustc` target configuration called `aarch64-unknown-uefi`.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Hi.
What is the relation of this PR with #85357?
They were submitted at the same time and contain some similar issues (https://github.com/rust-lang/rust/pull/85357#issuecomment-841794979).

**Comment by joshtriplett** [comment]
In addition to any other potential issues, this also needs to meet the target tier policy requirements for a new tier 3 target. You'll need to full-quote the tier 3 requirements from https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html and explain how you meet each of them.

**Comment by HTG-YT** [comment]
Good morning @petrochenkov and @joshtriplett; I will write up the reason why this `aarch64-unknown-uefi` target meets the requirements of a Tier-3 Target later today, thanks.

**Comment by petrochenkov** [comment]
To avoid doing the same work in two PRs I'm going to close this PR in favor of #85357 which was opened 2 minutes earlier.
@HTG-YT, feel free to collaborate with @Andy-Python-Programmer there.

**Comment by HTG-YT** [comment]
👌

**Pull request closed without merging**
