### PR TITLE
[NLL] Small move error reporting improvements

### PR DESCRIPTION
**Pull request by matthewjasper**
* Use a MirBorrowckContext when reporting errors to be more uniform with other error reporting
* Add a special message for the case of trying to move from capture variables in `Fn` and `FnMut` closures.

part of #51028

### CODE REVIEW

**Comment by kennytm** [comment]
```
---- [ui (nll)] ui\issue-30355.rs stdout ----
diff of stderr:
-	error[E0508]: cannot move out of type `[u8]`, a non-copy slice
-	  --> $DIR/issue-30355.rs:15:8
-	   |
-	LL |     &X(*Y)
-	   |        ^^ cannot move out of here
-	
7	error[E0161]: cannot move a value of type X: the size of X cannot be statically determined
8	  --> $DIR/issue-30355.rs:15:6
9	   |
15	   |
16	LL |     &X(*Y)
17	   |        ^^
+	
+	error[E0508]: cannot move out of type `[u8]`, a non-copy slice
+	  --> $DIR/issue-30355.rs:15:8
+	   |
+	LL |     &X(*Y)
+	   |        ^^ cannot move out of here
18	
19	error: aborting due to 3 previous errors
20	
```

**Comment by matthewjasper** [comment]
Tests updated

**Comment by euclio** [comment]
I realize this PR's already been approved, but if there's still time, it would be worth removing [this line](https://github.com/rust-lang/rust/blob/master/src/test/ui/issue-20801.rs#L11) (merged in #52197), since this PR fixes the ICE in that test.

**Comment by matthewjasper** [comment]
Done, needs another r+.

**Comment by kennytm** [comment]
@bors retry travis-ci/travis-ci#9696

```
[01:51:58] fatal: unable to access 'https://github.com/dzamlo/treeify/': Could not resolve host: github.com
```

**Pull request merged**
