### PR TITLE
More refactorings to rustc_interface

### PR DESCRIPTION
**Pull request by bjorn3**
Follow up to https://github.com/rust-lang/rust/pull/126834

### CODE REVIEW

**Comment by bjorn3** [comment]
This doesn't yet remove driver queries entirely as I'm not sure how to deal with the various finalization things in `Compiler::enter`. Shifting the responsibility to call them to custom drivers seems like it would be forgotten too easily.

**Comment by Nadrieril** [comment]
Looks good, just a test to update.

I'm curious: what do you mean by "remove driver queries"?

**Comment by bjorn3** [comment]
The methods on https://doc.rust-lang.org/nightly/nightly-rustc/rustc_interface/struct.Queries.html are what I call driver queries. Just like the queries in TyCtxt they are cached after their first call, but they are not serialized in the incr comp cache. They are purely interacted with by rustc_driver_impl and custom drivers. IMO they complicate things as it makes it easy for custom drivers to create the TyCtxt or HIR before the driver callback where you are supposed to access these, skipping various driver steps. In fact most custom drivers I have seen make this mistake at least once.

**Comment by Nadrieril** [comment]
I see, thanks! Pretty sure I've done that myself :>

**Comment by Nadrieril** [comment]
Thanks!

@bors r+

**Pull request merged**
