### PR TITLE
fix for late-bound regions

### PR DESCRIPTION
**Pull request by toidiu**
Fix for https://github.com/rust-lang/rust/issues/53419

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Sorry for the delay. Rust conf. This doesn't feel quite right to me, but let me investigate the code and say a bit more =)

**Comment by nikomatsakis** [comment]
OK, I see now where the assert is failing. I pushed a commit that fixes this in a different way -- basically, doing a better job of the previous hack. If you recall, @toidiu, we already modified the code to just *ignore* `Self` since it was unknown -- we were using `ty` as a "convenient self type", but it turns out that was a bad choice. Since it doesn't really matter *what* type we use, I modified the code to just use `usize`, which will obviously not trip that assert.

I also added a newtype for the bool to make it a bit more self documenting. Weird quirk I have. 

What do you think?

**Comment by estebank** [comment]
r=me if you decide to submit as is.

**Comment by toidiu** [comment]
@nikomatsakis This looks good to me and I think the new type helps improve the documentation.

**Comment by nikomatsakis** [comment]
@bors p=1 

Part of Edition

**Pull request merged**
