### PR TITLE
Make the NonZero* methods const fn

### LINKED ISSUE #53331: Make the `NonZero*` methods const fn
and undo the const -> fn changes in https://github.com/rust-lang/rust/pull/53315/files#diff-a4a060a3c734b42317d2b9136d68918eL186

This requires changing applicable methods on `NonZero*` from `fn` to `const fn`, adding the `#[rustc_const_unstable="const_nonzero*_methods"]` attribute to all of them and adding some tests ensuring that the methods are not const fn on stable rust.

### PR DESCRIPTION
**Pull request by JamesHinshelwood**
- Makes the `get` method a `const fn`, with a regression test added. Enabled with `feature(const_nonzero_methods)`.
- Makes some methods in the `indexed_vec!` data structure `const fn`.
- Revert some `const` -> `fn` changes in #53315

Fixes #53331

r? @oli-obk

### CODE REVIEW

**Comment by TimNN** [comment]
Ping from triage @JamesHinshelwood: It looks like some changes have been requested to your PR and it also needs to be rebased.

**Comment by JamesHinshelwood** [comment]
@TimNN Sorry, been very busy lately. I will get these changes made within a week.

**Comment by JamesHinshelwood** [comment]
@oli-obk Made the requested changes and rebased. Sorry for the (long) delay.

**Comment by oli-obk** [comment]
did you run `x.py test` all the way through? These tests happen pretty late. You can directly run them with `x.py test src/test/run-pass-fulldeps`

**Comment by Dylan-DPC** [comment]
pinging from triage @JamesHinshelwood Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again!

**Pull request closed without merging**
