### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth 

Sorry for taking so long. There were so many blockers and so little time. This situation should be mitigated with #104007 in the future.

### CODE REVIEW

**Comment by flip1995** [comment]
Not sure why this was labeled `A-bootstrap`. It only touches Clippy and updates the Clippy version in the `Cargo.lock` file

**Comment by matthiaskrgr** [comment]
Do we use if-let chains a lot? https://github.com/rust-lang/rust/issues/99938 :/

**Comment by flip1995** [comment]
Clippy is probably the main user of `let_chains`. Glad we can test it :sweat_smile:

**Comment by flip1995** [comment]
Argh, what's going on with this PR. Seems like GH ignores it and webhooks aren't working on it anymore or something. reopening it, maybe that'll help?

**Pull request merged**
