### PR TITLE
[CRATER] separate type equality from mutual subtyping

### PR DESCRIPTION
**Pull request by lcnr**
cc #97156

### CODE REVIEW

**Comment by lcnr** [comment]
@craterbot check 4e3d7541a523df82cea75064e44e60ae9a008bcb

**Comment by lcnr** [comment]
@craterbot check

**Comment by RalfJung** [comment]
> bidirectional subtyping

A note on terminology: "bidirectional typing" is a thing and it has nothing to do with what you do here, so to people like me your terminology is very confusing. :) I would recommend something like "mutual subtyping", or "symmetric closure of subtyping".

**Comment by Mark-Simulacrum** [comment]
Closing as crate results are available whenever needed, but this PR otherwise doesn't serve any purpose.

**Pull request closed without merging**
