### PR TITLE
Optimize size/speed of Unicode datasets

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
The overall implementation has the same general idea as the prior approach,
which was based on a compressed trie structure, but modified to use less space
(and, coincidentally, be an overall performance improvement).

Sizes | Old | New | New/current
-- | -- | -- | --
Alphabetic | 4616 | 2982 | 64.60%
Case_Ignorable | 3144 | 2112 | 67.18%
Cased | 2376 | 934 | 39.31%
Cc | 19 | 43 | 226.32%
Grapheme_Extend | 3072 | 1734 | 56.45%
Lowercase | 2328 | 985 | 42.31%
N | 2648 | 1239 | 46.79%
Uppercase | 1978 | 934 | 47.22%
White_Space | 241 | 140 | 58.09%
  |   |   |  
Total | 20422 | 11103 | 54.37%

This table shows the size of the old and new tables in bytes. The most important
of these tables is "Grapheme_Extend", as it is present in essentially all Rust
programs due to being called from `str`'s Debug impl (`char::escape_debug`). In
a representative case given by this [blog post] for the embedded world, the
shrinking in this PR shrinks the final binary by 1,604 bytes, from 14,440 to
12,836.

The performance of these new tables, based on the (rough) benchmark of linearly
scanning the entire valid set of chars, querying for each `is_*`, is roughly
~50% better, though in some cases is either on par or slightly (3-5%) worse. In
practice, I believe the size benefits of this PR are the main concern. The new
implementation has been tested to be equivalent to the current nightly in terms
of returned values on the set of valid chars.

A (relatively) high-level explanation of the specific compression scheme used
can be found [in the generator].

This is split into three commits -- the first adds the generator which produces
the Rust code for the tables, the second adds support code for the lookup, and
the third actually swaps the current implementation out for the new one.

[blog post]: https://jamesmunns.com/blog/fmt-unreasonably-expensive/
[in the generator]: https://github.com/rust-lang/rust/blob/0bf7c2ad77fdcb18a65ae05996dc8e226fbaeab4/src/tools/unicode-table-generator/src/raw_emitter.rs

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @jamesmunns per our discussions about this being helpful for embedded

**Comment by Mark-Simulacrum** [comment]
Turns out adding in the case conversions at the last minute in a way that I thought was 1-1 with the old code is not a good idea. The bug should be fixed now.

**Comment by joshtriplett** [comment]
Very nice!

@bors r+

**Comment by joshtriplett** [comment]
Not for this series, but looking at the implementation of escape_debug, how critical is it (and how much does backward compatibility depend on) that it treats extended graphemes specially, rather than escaping all Unicode or all non-printable Unicode? Omitting that table entirely from most Rust programs seems worthwhile.

**Comment by CAD97** [comment]
> rather than escaping all Unicode

That would be `str::escape_default`

> or all non-printable Unicode

That's today's `str::escape_debug` (roughly) :stuck_out_tongue: 

The problem being solved by the grapheme table is (in theory, anyway) that the printability of any specific Unicode codepoint depends on its position in a grapheme. Just as a simple example, ZERO WIDTH JOINER is an "unprintable" that has no meaning and is invisible when just in the middle of whitespace. But when between two emoji, it signifies that the user wants a singular emoji containing the attributes of both emoji. Similarly, the country code codepoints on their own are "unprintables", but in pairs they represent country flag emoji. (In practice: Unicode is _hard_ and you don't even know what's actually printable until you ask the font. `escape_default` is best effort to show all meaningful codepoints in the string while maintaining legibility for strings including non-ascii characters.)

**Comment by joshtriplett** [comment]
@CAD97 What I'm suggesting is that for *Debug* output, it's potentially acceptable to escape characters that might have been printable. And if doing so means we can drop a fairly large table from the majority of Rust binaries, that seems worth doing.

**Pull request merged**
