### PR TITLE
Added the `xop` target-feature and the `xop_target_feature` feature gate

### PR DESCRIPTION
**Pull request by sayantn**
This is an effort towards #127208. This adds the `xop` target feature gated by `xop_target_feature`.

### CODE REVIEW

**Comment by compiler-errors** [comment]
sorry, i'm probably not the right person to review this

r? compiler

**Comment by fee1-dead** [comment]
r? compiler

**Comment by sayantn** [comment]
will rebase after merge of #126639, as that would generate another merge conflict

**Pull request merged**
