### PR TITLE
Add powerpc64-unknown-freebsd

### PR DESCRIPTION
**Pull request by ghost**
FreeBSD review: https://reviews.freebsd.org/D18367

### CODE REVIEW

**Comment by jonas-schievink** [comment]
What's the difference between this and https://github.com/rust-lang/rust/pull/57758?

**Comment by MikaelUrankar** [comment]
> What's the difference between this and #57758?

I didn't know that someone was upstreaming my patches.

**Comment by nagisa** [comment]
Would you perhaps know whether changes to how LLVM is built from the linked PR necessary at all? If not, then we can just merge this now.

**Comment by lenoil98** [comment]
@MikaelUrankar I saw that we were working on this and borrowed some of your code into what I had been putting together.  Ref issue #57112

**Comment by nagisa** [comment]
As per [this comment](https://github.com/rust-lang/rust/pull/57758#discussion_r249561602), lets merge this PR.

Thanks, @lenoil98 @MikaelUrankar!

@bors r+

**Pull request merged**
