### PR TITLE
force-recompile library changes on download-rustc="if-unchanged"

### PR DESCRIPTION
**Pull request by onur-ozkan**
This makes the download-rustc="if-unchanged" option more functional and useful for library developers.

Implements the second item from [this tracking issue](https://github.com/rust-lang/rust/issues/131744).

### CODE REVIEW

**Comment by onur-ozkan** [comment]
There are already some PRs awaiting reviews from Mark.

r? bootstrap

**Comment by onur-ozkan** [comment]
I got some ideas to make this better. I will work on them later.

@rustbot author

**Comment by onur-ozkan** [comment]
> I got some ideas to make this better. I will work on them later.
> 
> @rustbot author

I was planning to change the staging logic for CI rustc, then I realized it's too much for this particular task. For now, this PR should meet the intended purpose (I believe).

@rustbot ready

**Comment by Kobzol** [comment]
Was a bit of a head-spin (`if if_unchanged` always triggers me :D), but it makes sense to me.

@bors r+

**Pull request merged**
