### PR TITLE
rustbuild: use Display for exit status instead of Debug, see #74832 for justification

### PR DESCRIPTION
**Pull request by infinity0**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me, but looks like ci is failing?

**Comment by infinity0** [comment]
@Mark-Simulacrum it's because Display isn't implemented for Result (it's implemented for both ExitStatus and io::Error).

It would be easy to implement it and I could do it as part of the PR (it would have to come in two parts since it doesn't exist in stage0), however was there a reason it wasn't already implemented? Seems like such an obvious thing to have.

**Comment by infinity0** [comment]
Display is not implemented for Option either so I figure this is some sort of libraries design decision, I'll update this PR to case-switch over the possibilities.

**Comment by Mark-Simulacrum** [comment]
Yes, lack of Display impls for Result and Option is intentional - there's no universal user facing representation of either.

@bors r+

**Comment by infinity0** [comment]
@Mark-Simulacrum I decided to just rewrite that section since it was repetitive and also had bugs (e.g. if you set both on-fail and RUSTC_PRINT_STEP_TIMINGS it wouldn't work correctly). It also allows us to get rid of the slightly messy `status_code` function.

**Pull request merged**
