### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by compiler-errors**
Successful merges:

 - #119838 (style-guide: When breaking binops handle multi-line first operand better)
 - #124844 (Use a proper probe for shadowing impl)
 - #125047 (Migrate `run-make/issue-14500` to new `rmake.rs` format)
 - #125080 (only find segs chain for missing methods when no available candidates)
 - #125088 (Uplift `AliasTy` and `AliasTerm`)
 - #125100 (Don't do post-method-probe error reporting steps if we're in a suggestion)
 - #125118 (Use new utility functions/methods in run-make tests)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=119838,124844,125047,125080,125088,125100,125118)

### CODE REVIEW

**Comment by Kobzol** [comment]
@rust-timer build b6ce40ac37b0ada020b88a5c443330c45c0b9a5e

**Comment by lqd** [comment]
That PR should only target the new solver 🤔

**Comment by compiler-errors** [comment]
Yeah, I started a perf build for a more likely PR (the `AliasTy` one): https://github.com/rust-lang/rust/pull/125088#issuecomment-2111060418

**Comment by Kobzol** [comment]
Ah, right, we probably can't schedule multiple runs on the same PR, that's annoying. Thanks.

**Comment by lqd** [comment]
A bit strange, I think I saw multiple runs being asked concurrently in the same PR in the past before...

**Comment by compiler-errors** [comment]
It's due to https://github.com/rust-lang/rust/pull/125088#issuecomment-2111255549, though nothing strikes me as immediately obviously less performant in that PR, except for perhaps the assertions I changed.

**Pull request merged**
