### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by sophiajt**
- Successful merges: #35754, #35759, #35793, #35880, #36099, #36160, #36171, #36178, #36180, #36190, #36198, #36205, #36210
- Failed merges:

### CODE REVIEW

**Comment by frewsxcv** [comment]
Tests failed.

```
failures:
---- ops::RangeToInclusive_2 stdout ----
	error: inclusive range syntax is experimental (see issue #28237)
 --> <anon>:5:17
  |
5 | assert_eq!(arr[ ...2], [0, 1, 2]);
  |                 ^^^^
  |
  = help: add #![feature(inclusive_range_syntax)] to the crate attributes to enable
error: aborting due to previous error(s)
thread 'ops::RangeToInclusive_2' panicked at 'Box<Any>', src/librustc/session/mod.rs:170
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    ops::RangeToInclusive_2
test result: FAILED. 1051 passed; 1 failed; 12 ignored; 0 measured
error: test failed
```

**Comment by TimNN** [comment]
Looks like #35759, that PR had the same failure.

**Pull request closed without merging**
