### PR TITLE
Suggest importing missing module when using module-qualified struct

### LINKED ISSUE #106068: Suggest importing missing module when using module-qualified struct
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=219638398b780287d5063239a94f8451

```rust
pub mod foo {
    pub mod bar {
        pub struct Baz;
    }
}

fn main() {
    let _: bar::Baz = unimplemented!();
}
```

The current output is:

```
error[E0433]: failed to resolve: use of undeclared crate or module `bar`
 --> src/main.rs:8:12
  |
8 |     let _: bar::Baz = unimplemented!();
  |            ^^^ use of undeclared crate or module `bar`

For more information about this error, try `rustc --explain E0433`.
```

Ideally the output should look like:

```
error[E0433]: failed to resolve: use of undeclared crate or module `bar`
 --> src/main.rs:8:12
  |
8 |     let _: bar::Baz = unimplemented!();
  |            ^^^ use of undeclared crate or module `bar`
  |
help: consider importing this module
  |
1  | use crate::foo::bar;
  |
For more information about this error, try `rustc --explain E0433`.
```

### PR DESCRIPTION
**Pull request by obeis**
Closes #106068

### CODE REVIEW

**Comment by obeis** [comment]
cc @jyn514 @petrochenkov
```
   Doc-tests core
error[E0773]: attempted to define built-in macro more than once
    --> /checkout/library/core/src/macros/mod.rs:1310:5
     |
1310 |     macro_rules! cfg {
     |     ^^^^^^^^^^^^^^^^
     |
note: previously defined here
    --> /checkout/library/core/src/macros/mod.rs:1310:5
     |
1310 | /     macro_rules! cfg {
1311 | |         ($($cfg:tt)*) => {
1312 | |             /* compiler built-in */
1313 | |         };
1314 | |     }
     | |_____^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0773`.
error: doctest failed, to rerun pass `-p core --doc`

Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustdoc --edition=2021 --crate-type lib --crate-name core --test /checkout/library/core/src/lib.rs --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/release/deps -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-b52adc3381d2c5df/out --test-args --quiet --extern core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/libcore-fa992565d2130c71.rlib --extern rand=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/librand-5f5a08803cfd7db0.rlib --extern rand_xorshift=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/librand_xorshift-1f0433028f46d505.rlib -C embed-bitcode=no -Zunstable-options --check-cfg 'names()' --check-cfg 'values()' -Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(stdarch_intel_sde)' '--check-cfg=values(no_fp_fmt_parse)' '--check-cfg=values(no_global_oom_handling)' '--check-cfg=values(no_rc)' '--check-cfg=values(no_sync)' '--check-cfg=values(freebsd12)' '--check-cfg=values(backtrace_in_libstd)' '--check-cfg=values(target_env,"libnx")' '--check-cfg=values(target_os,"watchos")' '--check-cfg=values(target_arch,"asmjs","spirv","nvptx","nvptx64","le32","xtensa")' '--check-cfg=values(dont_compile_me)' '--check-cfg=values(rustix_use_libc)' -Dwarnings '-Wrustdoc::invalid_codeblock_attributes' --crate-version '1.68.0-nightly
  (f49eaf41d
  2023-01-02)' '-Zcrate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/")' --error-format human` (exit status: 1)
Build completed unsuccessfully in 0:22:33
== clock drift check ==
  local time: Mon Jan  2 03:51:40 UTC 2023
  network time: Mon, 02 Jan 2023 03:51:40 GMT
== end clock drift check ==
Error: Process completed with exit code 1.
```

**Comment by jyn514** [comment]
@obeis I don't know why you pinged me; this is a regression introduced by your PR. You probably need to make the suggestions [speculative](https://rustc-dev-guide.rust-lang.org/name-resolution.html#speculative-crate-loading)

**Comment by JohnCSimon** [comment]
@obeis 

ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
