### PR TITLE
Test that we cannot use trait impl methods arguments as defining uses

### PR DESCRIPTION
**Pull request by oli-obk**
Addresses https://github.com/rust-lang/rust/issues/63063#issuecomment-1360053614

r? @dtolnay

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by Nilstrieb** [comment]
Tests moved from `src/tests` to the `tests` directory in the root, can you [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing) and move them?
@bors r-
@rustbot author

**Comment by dtolnay** [comment]
Rebased.
@bors r+

**Pull request merged**
