### PR TITLE
Cleanup uses of TypeIdHasher and replace them with StableHasher

### LINKED ISSUE #50424: Remove TypeIdHasher and replace it with StableHasher in debuginfo and symbol hashing
At the moment we have two implementations for hashing `Ty` values, the `StableHasher` (which is used for incr. comp. and `TypeId`) and the [TypeIdHasher](https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/librustc/ty/util.rs#L609) which was formerly used for `TypeId` and has some leftover uses in [symbol hash generation](https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/librustc_trans_utils/symbol_names.rs#L147) and [debuginfo](https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/librustc_trans/debuginfo/metadata.rs#L147). 

We should be able to switch the two remaining uses to `StableHasher` quite easily. This might also be a small performance win, since StableHasher is more optimized. 

cc @rust-lang/wg-compiler-performance

### PR DESCRIPTION
**Pull request by iancormac84**
Fixes #50424 

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks, @iancormac84! Looks great. Let's see if this affects performance.

@bors try

**Comment by kennytm** [comment]
@Mark-Simulacrum perf requested.

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, could you enqueue a perf run please?

**Comment by michaelwoerister** [comment]
Link: http://perf.rust-lang.org/compare.html?start=8ff4b42064b374bb62043f7729f84b6d979c7667&end=743a8724ab405b092f6311bbef137c098d405e63&stat=instructions%3Au

**Comment by iancormac84** [comment]
Hi @michaelwoerister. Anything I need to do? I noticed the merge conflict, and tried a git rebase, the resolves of which I didn't like, so I cherry-picked my commits on to another branch. I'm still a newbie at using Git, so I'm not 100% sure what's best.

**Comment by michaelwoerister** [comment]
I'm still waiting for the performance results to see if this introduces any regressions. Once those are in and look good, you need to do the following:
```bash
# get the latest version of master
git fetch upstream

# rebase your branch onto master
git rebase upstream/master

# resolve any conflicts that arise during rebase and require manual resolving
...

# Push your changes so they show up here on github.
git push -f
```

You can already do that now. Performance testing won't be affected by it.

**Comment by kennytm** [comment]
Perf result is ready @michaelwoerister. Almost no change in performance in general.

**Comment by michaelwoerister** [comment]
Sorry about the delay. I was out sick for a couple of days. Yes, this should be good to go once it passes travis again.

**Comment by iancormac84** [comment]
@michaelwoerister sorry to hear. Hope you've made a full recovery.

Updates made.

**Comment by michaelwoerister** [comment]
Thanks for keeping things rebased, @iancormac84!

@bors r+ rollup

**Pull request merged**
