### PR TITLE
Diagnostic renaming 2

### PR DESCRIPTION
**Pull request by nnethercote**
A sequel to #121489.

r? @davidtwco

### CODE REVIEW

**Comment by nnethercote** [comment]
I rebased.

**Comment by nnethercote** [comment]
I rebased again.

**Comment by nnethercote** [comment]
I rebased a third time.

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
@bors r+

Apologies that it took a few days to get to this.

**Comment by nnethercote** [comment]
@bors p=1

Because this is conflict-prone.

**Comment by nnethercote** [comment]
I rebased, and added a commit making `tests/ui-fulldeps/internal-lints/diagnostics.rs` stage 2 only, which it should be, which fixes the test error seen above.

@bors r=davidtwco

**Comment by nnethercote** [comment]
Presumably the max-rss "regressions" are just noise? This PR just renamed a bunch of stuff, shouldn't have effected performance at all.

**Pull request merged**
