### PR TITLE
Force linker to link in exported symbols

### PR DESCRIPTION
**Pull request by carbotaniuman**
The more surgical variant of #93791, which uses linker args `-u` on Unix and `/INCLUDE` on Windows to forcefully include exported symbols.

This allows statics like this to work (and get embedded in the final executable):
```
mod foo {
    #[used]
    static FOO: [u32; 10] = [1; 10];
}
```

@nbdd0121 I've copied your test wholesale, feel free to review. I'm not sure if this handles all the edge cases, and I'd love a test for crate-type=bin.

### CODE REVIEW

**Comment by nbdd0121** [comment]
`-u` have a very unfortunate effect that it will inhibit GC sections. For example, `#[no_mangle]` functions should be allowed to GCed if they are not reached from main in binaries. I have experimented with `-u` before trying while-archive  and abandoned it for this reason.

I have been experimenting a more advanced approach for ELF targets using a customly generated object file and it seems working well; though I didn't make much progress due to lack of time recently.

**Comment by petrochenkov** [comment]
There's kind of a race condition between our work, because this is almost exactly what I planned to implement today-tomorrow to address the question (2) from https://github.com/rust-lang/rust/pull/93901#issuecomment-1041325522.

Except that I primarily care about dylibs (as described in the linked comment), so the issue with garbage-collecting `#[no_mangle]` stuff is irrelevant, nothing exported should be garbage-collected in that case.

>using a customly generated object file

Generating a "root" object file with artificial references to all exported symbols may be the most general solution, because it looks like it should work for both dylib and executable cases (and would allow GCing `no_mangle`s while keeping `used`s).
It is unfortunate if just passing `-u`s is not equivalent to generating such references.

**Comment by carbotaniuman** [comment]
Hmm I see this issue: https://github.com/rust-lang/rust/issues/84161 at the same time. Given `-u` inhibits garbage collecting symbols (does it do so on both MSVD and GCC/LD).

Is there anything wrong with mapping `#[used(linker)]` to `-u`? That seems like it has the perfect semantics. I'm also wondering if we could pass `-u` only for statics, which seems like the best of both worlds.

**Comment by carbotaniuman** [comment]
I'm going to implement these semantics right now, but I'm sure they'll be wrong somewhere.

1. All exposed exported symbols will be forcefully linked in. If this is a cdylib or a dylib, then functions are included, if not, then just statics, unless the RFC 2841 option is specified.
2. All `#[used(linker)]` statics will be linked in. We could also have another used arg to say I want this to be linked in but possibly GCed.
3. Everything else will be up to the linker.

I'm not actually going to touch the RFC 2841 part or dylibs, but I think those semantics *should* cover everything.

**Comment by carbotaniuman** [comment]
Ok implemented the first part of the above. There's a lot of todos and fixmes thrown around here as there needs to be a refactor or two, but this uses implicit linker scripts (for GCC) and command files (for LINK) to forcibly link stuff. This *is* implemented for dylibs currently (and dylibs were the reason I had to switch to files and not args), but I've kept the whole-archive stuff in place so idk if it does anything.

**Comment by nbdd0121** [comment]
> All exposed exported symbols will be forcefully linked in. If this is a cdylib or a dylib, then functions are included, if not, then just statics, unless the RFC 2841 option is specified.

This is just heuristics, not a comprehensive fix, isn't it?

> Is there anything wrong with mapping `#[used(linker)]` to `-u`? That seems like it has the perfect semantics.

Mapping `#[used(linker)]` to `-u` is probably okay.

The best approach that I can think of so far is still a custom-generated object file. I think it could be a universal solution, without need of any heuristics or special handling of `#[used(linker)]`, and without introducing extra unwanted semantics. I'll try to find some time next weekend to see if I can at least get a prototype version working.

**Comment by carbotaniuman** [comment]
I feel like it's a comprehensive fix, but I'm not sure. I can't come up with a counterexample right now other than `#[used(linker)]`. I'm not sure how a custom object file could avoid special casing though, you'd still need to grab a list of symbols from somewhere?

**Comment by nbdd0121** [comment]
> I feel like it's a comprehensive fix, but I'm not sure. I can't come up with a counterexample right now other than `#[used(linker)]`.

For binaries, this would still cause some statics (`#[no_mangle]` or `#[used(compiler)]` but unreferenced) to be non-GC-able, and functions to be omitted (e.g. those `KEEP`-ed by linker scripts).

> I'm not sure how a custom object file could avoid special casing though, you'd still need to grab a list of symbols from somewhere?

It'll just need to use the same list of symbols that is used in version scripts.

**Comment by bjorn3** [comment]
> For binaries, this would still cause some statics (#[no_mangle] or #[used(compiler)] but unreferenced) to be non-GC-able, and functions to be omitted (e.g. those KEEP-ed by linker scripts).

For executables this is ignored: https://github.com/rust-lang/rust/pull/95363/files#diff-3f87e69f5e21712681d6fca5b6b70542c10eaf49bf48ff16445ddd17f1ae6dadR666

**Comment by carbotaniuman** [comment]
> For executables this is ignored: https://github.com/rust-lang/rust/pull/95363/files#diff-3f87e69f5e21712681d6fca5b6b70542c10eaf49bf48ff16445ddd17f1ae6dadR666

This wasn't exactly correct before, but it is now. We forcefully link all `#[used]` (even `#[used(compiler)]` but that's just because our semantics for that are weird rn) into an executable. We only forcefully link in exports if we're actually exporting things.

**Comment by bjorn3** [comment]
Would https://github.com/rust-lang/rust/pull/85673 fix your usecase?

**Comment by carbotaniuman** [comment]
Can I get a perf run now, or do I have to figure out this reproducible build error first?

**Comment by kaspar030** [comment]
GC'ing `#[no_mangle]` symbols is essential for embedded code (where every byte counts).

**Comment by petrochenkov** [comment]
>Can I get a perf run now, or do I have to figure out this reproducible build error first?

@bors try @rust-timer queue
(FWIW, I didn't have a chance to look at the updated changes yet.)

**Comment by carbotaniuman** [comment]
Hmm, no idea why that is failing. I made some changes so I can know if it's OOMing, but given it's an executable there shouldn't be any issues... Can I get another run?

**Comment by carbotaniuman** [comment]
Ok, I think it's a linker difference between whatever I'm using and whatever the runners are doing. Should hopefully be the last run.

**Comment by carbotaniuman** [comment]
@petrochenkov Mind giving the button another push?

**Comment by petrochenkov** [comment]
Performance is ok, but the `run-make-fulldeps/reproducible-build` test is still failing though.

**Comment by petrochenkov** [comment]
I'll get to reviewing this next weekend most likely, I need to read https://github.com/rust-lang/rust/issues/47384 and look at some code in rustc generating export lists, to understand what different cases exists.

I'm also still interested in landing some simple solution addressing only dylibs sooner to unblock stabilization of the `bundle` modifier.

**Comment by carbotaniuman** [comment]
Yeah I'm not sure what to do for `run-make-fulldeps/reproducible-build `.

The reason is I have to inject a synthetic file that didn't previously exist: `forcelink.ld` (ignore the `-1-62` below, those were me trying to fix CI).

So I grabbed the same tempdir that was used for `export_symbols` to place the file in, and that of courses uses a tempdir that  changes every run. The actual contents of the file are identical however as the function that creates it is deterministic, so I don't think the output is still reproducible. I don't know what this is testing, nor can I reasonably put `forcelink.fd` in a reproducible directory without breaking things.

```
-/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/reproducible-build/reproducible-build/rustc1YSzXc/forcelink-1-62.ld: 2650171599958706936
+/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/reproducible-build/reproducible-build/rustcjv1Ryr/forcelink-1-62.ld: 2650171599958706936
```

**Comment by petrochenkov** [comment]
Marking as blocked on https://github.com/rust-lang/rust/pull/95604 for now, with an intent to close when/if it lands.

**Pull request closed without merging**
