### PR TITLE
Update RLS to solve serious crash

### PR DESCRIPTION
**Pull request by Enet4**
As a follow-up to rust-lang-nursery/rls#312, this PR contains the fix to the latest experienced RLS crashes, which should hopefully reach the nightly release as soon as possible.

### CODE REVIEW

**Comment by petrochenkov** [comment]
@bors r+
Thanks!

**Comment by Mark-Simulacrum** [comment]
@bors retry

Prioritizing rollup that contains this

**Comment by nrc** [comment]
@bors r-

There has been another update to LSP types (to 0.10), so this submodule update is out of date now.

**Comment by Enet4** [comment]
@nrc I have pulled the latest changes again. Can we try again now? :)

**Comment by Mark-Simulacrum** [comment]
Could you squash commits?

**Comment by Enet4** [comment]
@Mark-Simulacrum Commits were squashed (I don't squash commits very often, but hopefully everything is in order).

**Comment by Mark-Simulacrum** [comment]
Thanks!

@bors r+

**Comment by chetgurevitch** [comment]
Build failed due to a seemingly random(?) server error with crates.io.

**Comment by Mark-Simulacrum** [comment]
Previous appveyor failure, #41545. Logged.

```
[01:28:26]   failed to get 200 response from `https://crates.io/api/v1/crates/utf8-ranges/0.1.3/download`, got 500
```

**Comment by nrc** [comment]
Thanks @Enet4 !

**Pull request merged**
