### PR TITLE
Do not emit coerce_suggestions for expr from destructuring assignment desugaring

### LINKED ISSUE #109991: Compiler suggests dereferencing LHS of tuple-assign
### Code

```Rust
fn main() {
    let a: usize;
    let b: usize;
    
    (a, b) = (123, &mut 123);
}
```

### Current output

```
error[E0308]: mismatched types
  --> src/main.rs:17:9
   |
15 |     let b: usize;
   |            ----- expected due to this type
16 |     
17 |     (a, b) = (123, &mut 123);
   |         ^ expected `usize`, found `&mut {integer}`
   |
help: consider dereferencing the borrow
   |
17 |     (a, *b) = (123, &mut 123);
   |         +
```

### Desired output

```
error[E0308]: mismatched types
  --> src/main.rs:17:9
   |
15 |     let b: usize;
   |            ----- expected due to this type
16 |     
17 |     (a, b) = (123, &mut 123);
   |         ^ expected `usize`, found `&mut {integer}`
   |
help: consider dereferencing the borrow
   |
17 |     (a, b) = (123, *&mut 123);
   |                    +
```

Although this cannot be always applied, e.g. consider:

```rust
fn main() {
    let a: usize;
    let b: usize;
    
    (a, b) = foo();
}

fn foo() -> (usize, &'static mut usize) {
    todo!()
}
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #109991

### CODE REVIEW

**Review by compiler-errors — COMMENTED** [review]
I don't think this works for other kinds of destructuring patterns, like arrays:

```rust
fn main() {
    let x: i32;
    [x] = [&1];
}
```

Also, does this work to fix the nonsense suggestion for this example?

```rust
fn main() {
    let x: &i32;
    [x] = [1];
}
```

I think the problem here is that for destructuring assignments, the spans are wrong and don't really correspond correctly... 

I don't know if fixing this one specific suggestion addresses the larger problem that other suggestions are still broken -- maybe we need a more thorough solution?

**Comment by compiler-errors** [comment]
Maybe the best compromise here is to detect if the expression is from a destructuring assignment desugaring and just not offer any of the suggestions in `emit_coerce_suggestions` or `emit_type_mismatch_suggestions`...

That isn't perfect, but it should also help not suggesting nonsense like:

```
fn main() {
    let x: String;
    (x,) = (1,);
}
```

```
error[[E0308]](https://doc.rust-lang.org/stable/error_codes/E0308.html): mismatched types
 --> src/main.rs:3:6
  |
2 |     let x: String;
  |            ------ expected due to this type
3 |     (x,) = (1,);
  |      ^- help: try using a conversion method: `.to_string()`
  |      |
  |      expected `String`, found integer
```

**Comment by chenyukang** [comment]
> I don't think this works for other kinds of destructuring patterns, like arrays:
> 
> ```rust
> fn main() {
>     let x: i32;
>     [x] = [&1];
> }
> ```
> 
> Also, does this work to fix the nonsense suggestion for this example?
> 
> ```rust
> fn main() {
>     let x: &i32;
>     [x] = [1];
> }
> ```
> 
> I think the problem here is that for destructuring assignments, the spans are wrong and don't really correspond correctly...
> 
> I don't know if fixing this one specific suggestion addresses the larger problem that other suggestions are still broken -- maybe we need a more thorough solution?

Yes, we need a better general solution if we want to suggest like this:

```rust
help: consider dereferencing the borrow
   |
17 |     (a, b) = (123, *&mut 123);
   |                    +
```
we don't have expr for `&mut 123` passed into `suggest_deref_or_ref`.

**Comment by compiler-errors** [comment]
I don't think it's, in general, possible to suggest what you said above. You can do destructuring assignments where the expressions do not align, like:

```
let x = (1, 2);
(a, b) = x;
```

so there's no way to in general pair `a` with `1` and `b` with `2` in the type mismatch. it's better to just suppress the suggestions altogether.

**Comment by chenyukang** [comment]
Updated code to suppress the suggestions altogether.

**Comment by compiler-errors** [comment]
r=me after blessing tests and squashing the commits

**Pull request merged**
