### PR TITLE
convert boolean ui tests into unit tests

### PR DESCRIPTION
**Pull request by njasm**
PR related with rust-lang/rust#76268
Moves/converts boolean ui test into library unit tests.

?r @matklad

### CODE REVIEW

**Comment by njasm** [comment]
?r @matklad

**Comment by matklad** [comment]
Hm, are those actually tests of standard library functionality? IIRC, operators on primitive types (`<`, `^`, etc) are actually built-in, and, as such, this suite of tests exercises the compiler rather than stdlib.

**Comment by njasm** [comment]
yes you are right, sorry. I jumped the gun and went on converting them to unit tests based only on the `//run-pass` plus the share volume of current ui tests.

Also, looking into `library/core/tests/cmp.rs` I believe those cover pretty much (and more) the same changes in this PR for `cmp::{Greater, Less, Equal}` 

So, being such a tiny change, should we close this and move on, or do you think there's something we could do here?
(take notice i'm confortable either way 👍)

**Comment by jyn514** [comment]
> Hm, are those actually tests of standard library functionality? IIRC, operators on primitive types (<, ^, etc) are actually built-in, and, as such, this suite of tests exercises the compiler rather than stdlib.

@matklad what do you think about adding a `compiler/rustc/tests` directory with unit tests for the compiler itself? Then we still get the benefits that the tests are fast to run/compile, but without intermingling compiler tests with the standard library.

**Comment by matklad** [comment]
This is a tradeoff. It should be significantly easier to debug standalone programs, as you won't have to wade through libtest machinery if the compiler does break. 

I'd say this (with a pretty low confidence level, as I am not that much of an expert in rustc's internals):

* library unit-test should go to #[test] inside the library
* if possible, we should grow the set of uni-tests inside the compiler for various intermediate represntations. If done carefully, this'll give us fast, cheap to maintain and deep test suite. If done haphazardly, it risks ossifying the existing architecture
* the final say should be behind a large battery of fully integrated tests, each of which should be a separate program. However, when we fix compile times and test execution speed becomes a concern, we should add a mode which batches integration tets together (rougthly concates 64 consequtive tests and swaps `fn main()` for `#[test] fn test()`)

**Comment by njasm** [comment]
ok, lets move on then. 👍

**Pull request closed without merging**
