### PR TITLE
[stable] Prepare 1.58.1 point release

### PR DESCRIPTION
**Pull request by emilyalbini**
Included in this point release:

* https://github.com/rust-lang/rust/issues/92938
  * https://github.com/rust-lang/rust-clippy/pull/8075 (only a part of it)
  * https://github.com/rust-lang/rust-clippy/pull/8295
* https://github.com/rust-lang/rust/pull/92912
* https://github.com/rust-lang/rust/pull/91254

cc @rust-lang/release

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors r+ p=1000 rollup=never

Trying to fix disk space on CI.

**Comment by pietroalbini** [comment]
@bors r+ p=1000 rollup=never

Fallout from the previous fix.

**Comment by camsteffen** [comment]
Sorry, don't know if this is way too late. I think we should include rust-lang/rust-clippy#7945? (fix for rust-lang/rust-clippy#7934, rust-lang/rust-clippy#8307) @flip1995

**Comment by flip1995** [comment]
If bors should fail again and @pietroalbini has the patience to include those, sure.

**Comment by pietroalbini** [comment]
@camsteffen hi! While we could add that bug fix to the point release, I got the release to a point where we know it doesn't have CI failures (it just timed out due to a couple slow builders), and I'm wary of adding more changes. We need it to build successfully today and adding extra code increases the risk of the build failing.

**Comment by flip1995** [comment]
@pietroalbini I agree. Let's get this merged as-is then. I'll make sure that those fixes at least get into beta (if they aren't already)

**Comment by pietroalbini** [comment]
(do not retry this PR)

**Comment by pietroalbini** [comment]
Superseded by https://github.com/rust-lang/rust/pull/93110

**Pull request merged**
