### PR TITLE
Update alloc, core, and std to rand 0.8

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Comment by klensy** [comment]
see #104658

**Comment by thomcc** [comment]
This will fail on wasm32-unknown-unknown. The right way to do this is https://github.com/rust-lang/rust/pull/104658.

**Comment by thomcc** [comment]
See previous attempts to update this:
- https://github.com/rust-lang/rust/pull/86963 (in particular https://github.com/rust-lang/rust/pull/86963#issuecomment-885438936 which explains why this is non-trivial)
- https://github.com/rust-lang/rust/pull/89131
- https://github.com/rust-lang/rust/pull/96626#issuecomment-1114562857 (I tried in that PR at the same time, but settled for just removing the usage of `thread_rng()` from the benchmarks, since that was the main goal).
- https://github.com/rust-lang/rust/pull/104185

**Pull request closed without merging**
