### PR TITLE
rustdoc: Unify `where` clause styling

### LINKED ISSUE #112901: rustdoc: where-clauses on tuple & unit structs and on assoc tys are weirdly styled
The styling of where-clauses on *tuple* & *unit* structs and on assoc tys weirdly differs from those on other items (structs, enums, unions, functions, impl blocks etc.) in that they don't have a smaller fonts size and are indented by 9 instead of 4 spaces (more precisely: for associated types it's *3* instead of 4 inside the `.item-decl` of the trait but 9 instead of 4 everywhere else).

### Tuple Structs

```rs
pub struct A<T>(T)
where
    T: Copy;
```

is rendered as

Screenshot 2023-06-21 at 18-54-30 A in tup - Rust

Compare that to

```rs
pub struct B<T>
where
    T: Copy,
{
    x: T,
}
```

Screenshot 2023-06-21 at 18-55-31 B in tup - Rust

### Unit Structs

```rs
#![feature(trivial_bounds)]

pub struct S
where
    String: Clone;
```

Screenshot 2023-06-21 at 19-07-44 S in tup - Rust

### Associated Types

```rs
pub struct S;

pub trait Tr {
    type F<T>
    where
        T: Clone;
}

impl Tr for S {
    type F<T> = T where T: Clone;
}
```

Inside the `.item-decl` of the trait (3 spaces, big):

Screenshot 2023-06-21 at 20-14-21 Tr in nx - Rust

In section *Required Associated Types* on the page of the trait (9 spaces):

Screenshot 2023-06-21 at 20-12-24 Tr in nx - Rust

On the implementer's page (9 spaces, big):

Screenshot 2023-06-21 at 20-15-58 S in nx - Rust

@rustbot label C-bug T-rustdoc A-rustdoc-ui

### PR DESCRIPTION
**Pull request by camelid**
Fixes #112901 (and other inconsistencies).

After this change, all `where` clauses are rendered the same (except for ending
in commas versus semicolons in some cases). They look like this (note that the
`where` clause will also be in a slightly-smaller font size than is used for the
rest of the docs):

```rust
pub trait Tr {
    type F<T>
    where
        T: Clone;
}
```

r? @GuillaumeGomez

### CODE REVIEW

**Comment by camelid** [comment]
Screenshot (will post more later):

image

**Comment by camelid** [comment]
### "Long" before (1.65.0)

image

### Before (nightly 2023-06-24)

image

### After (this PR)

image

**Comment by camelid** [comment]
### Before (nightly 2023-06-24)

image

### After (this PR)

image

**Comment by camelid** [comment]
### Before (nightly 2023-06-24)

image

### After (this PR)

image

**Comment by GuillaumeGomez** [comment]
I think your change breaks alignment starting from the second bound if you have more than one bound since you changed the font size. For example:

```rust
pub struct Foo<A, B>(A, B)
where
    A: Display,
    B: Clone;
```

We should add a GUI test for that.

For the broken indent (more than 4 whitespace characters diff between `where` and bounds), there was https://github.com/rust-lang/rust/pull/112927.

As for this indent:

```rust
pub trait Foo {
    fn bar<T>(t: T)
       where T: Clone;
}
```

I thought it was voluntary so I left it as is. But you can fix it by removing `let where_indent = 3;` (and its uses). Investigating.

**Comment by fmease** [comment]
The three space indentation was introduced in #102842 (see #85566 for rationale). I can see where it's coming from but I dislike that it ceased formatting where-clauses in adherence to the Rust style guide.

**Comment by camelid** [comment]
No, #112901 is that some items have a 9-space indent for their where-clause.

**Comment by fmease** [comment]
> but I do not want to endlessly re-litigate this

Aye, makes sense. I didn't notice that this decision was FCP'ed. All good then, I defo don't want to needlessly reopen the case.

I'm happy as long as where-clauses *outside* of `.item-decl` (which the FCP was about afaik) have a consistent style (small font, `where` not indented, bounds w/ an indent of 4).

**Comment by Dylan-DPC** [comment]
@camelid any updates on this? thanks

**Comment by camelid** [comment]
Sorry, I haven't had a chance to work on this since June. I think the main thing is for us (T-rustdoc) to agree on what we want our `where` clause styling to be across rustdoc. My proposal is as follows:

* On a trait's page, in its `item-decl` (the pseudocode block at the top of the page), the `where` clauses for its associated items have normal font-size and 3-space indent. The first bound is on the same line as the `where` keyword, and subsequent lines are indented so the bounds line up. This is to maintain consistency with what was agreed upon in #102842. `where` clauses on the trait itself (i.e., `trait Foo where ...`) will be styled the same way.

* Everywhere else that `where` clauses appear (in the rest of traits' pages, in other items' `item-decl`s, and in the rest of the pages for other items), they are in a slightly smaller font, with rustfmt style: The `where` keyword has no indent with respect to its attached item and is on its own line, and each subsequent line (with one bound each) has 4-space indent.

@GuillaumeGomez @notriddle (and anyone else who's interested) does this sound good to you?

**Comment by GuillaumeGomez** [comment]
Sounds good to me.

**Comment by Dylan-DPC** [comment]
@camelid any updates on this?

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
