### PR TITLE
Do not merge

### PR DESCRIPTION
**Pull request by ChrisDenton**
This has been failing a lot lately. Let's see if we can get more info.

r? ghost

try-job: x86_64-msvc-ext

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Oh no! Let's try again.

@bors try

**Comment by ChrisDenton** [comment]
Oops, wrong command

@bors try

**Comment by tgross35** [comment]
Something may be weird with bors here - the commit doesn't have `r=<try>` as usual, and https://bors.rust-lang.org/queue/rust says `pending` rather than `pending(try)`. Is it trying to merge this?

**Comment by ChrisDenton** [comment]
Oh!

**Comment by tgross35** [comment]
Well, guess we'll see what this means 😆 

image

**Comment by ChrisDenton** [comment]
Hmm, I might have to make a new PR...

**Comment by tgross35** [comment]
Weird 🤷

**Pull request closed without merging**
