### PR TITLE
Rollup of 15 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #76097 (Stabilize hint::spin_loop)
 - #76227 (Stabilize `Poll::is_ready` and `is_pending` as const)
 - #77640 (Refactor IntErrorKind to avoid "underflow" terminology)
 - #78026 (Define `fs::hard_link` to not follow symlinks.)
 - #78065 (make concurrency helper more pleasant to read)
 - #78114 (Recognize `private_intra_doc_links` as a lint)
 - #78228 (Promote aarch64-unknown-linux-gnu to Tier 1)
 - #78345 (Fix handling of item names for HIR)
 - #78437 (BTreeMap: stop mistaking node for an orderly place)
 - #78476 (fix some incorrect aliasing in the BTree)
 - #78570 (Remove FIXME comment in print_type_sizes ui test suite)
 - #78658 (Add a tool to run `x.py` from any subdirectory)
 - #78706 (Fix run-make tests running when LLVM is disabled)
 - #78790 (Vendor libtest's dependencies in the rust-src component)
 - #78828 (use single char patterns for split() (clippy::single_char_pattern))

Failed merges:

 - #78480 (BTreeMap: fix pointer provenance rules)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=76097,76227,77640,78026,78065,78114,78228,78345,78437,78476,78570,78658,78706,78790,78828)

### CODE REVIEW

**Comment by jyn514** [comment]
Failed to link LLVM:

```
 collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
ninja: build stopped: subcommand failed.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.44/src/lib.rs:885:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@bors retry

**Comment by m-ou-se** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/78874 is already in progress, and overlaps with this rollup.

**Comment by Dylan-DPC** [comment]
previous rollups should be triaged first before creating a new one :)

**Pull request closed without merging**
