### PR TITLE
Kill IdentTT

### PR DESCRIPTION
**Pull request by Manishearth**
... it wasn't being used anyway

### CODE REVIEW

**Comment by Manishearth** [comment]
r? @eddyb @alexcrichton 

An alternative is to add support to `macro_rules` to be able to create `IdentTTs`. `bitflags! foo {...}` looks better than `bitflags! { flags Foo {... }}`

**Comment by alexcrichton** [comment]
cc @sfackler, @huonw, @nrc, not super familiar with plugins myself

**Comment by sfackler** [comment]
Do you know of any syntax extensions that use IdentTT?

**Comment by Manishearth** [comment]
Nope. @eddyb tells me `IdentTT` was a hack to support `macro_rules!` but it has its own variant now.

**Comment by sfackler** [comment]
I was talking about third party extensions.

**Comment by Manishearth** [comment]
Yeah, I know. I don't know of any using that, and a grep on my cargo dir turns up nothing.

**Comment by nrc** [comment]
I'm not aware of any.

cc @erickt too.

**Comment by jonas-schievink** [comment]
rust-peg [uses](https://github.com/kevinmehall/rust-peg/blob/76cfa35901319e88b70a096cf2e13b1be91f4b9f/src/peg_syntax_ext.rs#L28) it

**Comment by Manishearth** [comment]
Doesn't look strictly necessary there, though `IdentTT` is slightly more ergonomic. Still, left a note in an issue there.

**Comment by sfackler** [comment]
So do we have a compelling reason to remove this? The LOC delta doesn't seem all that large.

**Comment by Manishearth** [comment]
Nah, just that it's not being used and there isn't much of a reason to use it.

**Comment by leodasvacas** [comment]
I'm totally ignorant but [stainless](https://github.com/reem/stainless) uses it. reem/stainless#11 discusses TT things.

**Comment by Manishearth** [comment]
@reem Any particular affinity to IdentTT?

**Comment by reem** [comment]
As noted above its used in stainless to give a nicer syntax to the plugin. Personally I would like more freedom for macros and plugins, so I would like it to stay as it makes for much better syntax in some cases.

**Comment by Gankro** [comment]
Sounds like we should close this?

**Comment by alexreg** [comment]
I don't generally like to reopen old cans of worms, but is there really a need for this syntax extension type any more? It seems like needless complexity at little gain. @Manishearth

**Comment by eddyb** [comment]
cc @jseyfried

**Comment by Manishearth** [comment]
Does the new proc macro system wish to have this feature?

I suspect it does actually, since hopefully `macro_rules` can be written as a proc macro itself. Maybe.

**Comment by alexreg** [comment]
@Manishearth AFAIK, `macro_rules` itself being written as a proc macro is something that has been discussed before several times, but I don't believe it's anywhere high on the priority list.

Anyway, it seems like a rather odd special-case that makes declarative macros more unlike functions. Is there really a need?

**Comment by Manishearth** [comment]
_shrug_

**Comment by nrc** [comment]
It won't be part of macros 2.0 (hopefully) at which point it should be deprecated and removed, but it has to go through the RFC process, I don't think we've agreed to remove it yet.

**Comment by alexreg** [comment]
@nrc, Okay, fair enough.

**Pull request closed without merging**
