### PR TITLE
Rollup of 16 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #91804 (Make some `Clone` impls `const`)
 - #92541 (Mention intent of `From` trait in its docs)
 - #93057 (Add Iterator::collect_into)
 - #94059 (Treat constant values as mir::ConstantKind::Val)
 - #94368 ([1/2] Implement macro meta-variable expressions)
 - #94472 (Use MaybeUninit in VecDeque to remove the undefined behavior of slice)
 - #94644 (Fix soundness issue in scoped threads.)
 - #94657 (Constify `Index{,Mut}` for `[T]`, `str`, and `[T; N]`)
 - #94719 (Statically compile libstdc++ everywhere if asked)
 - #94739 (Suggest `if let`/`let_else` for refutable pat in `let`)
 - #94740 (Unify impl blocks by wrapping them into a div)
 - #94753 (Improve rustdoc book)
 - #94754 (Warn users about `||` in let chain expressions)
 - #94763 (Add documentation about lifetimes to thread::scope.)
 - #94768 (Ignore `close_read_wakes_up` test on SGX platform)
 - #94772 (Add miri to the well known conditional compilation names and values)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=91804,92541,93057,94059,94368,94472,94644,94657,94719,94739,94740,94753,94754,94763,94768,94772)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@Dylan-DPC I would suggest to not make such big rollups, if this introduces a perf regression it might be pain to debug where it's comming from.

**Comment by matthiaskrgr** [comment]
CI already failed, closing
````
test [ui] run-pass/vec.rs ... ok
diff of stdout:

-[2, 2] Iter([2, 2], [])
+[2, 2] Iter([core::mem::maybe_uninit::MaybeUninit<alloc::boxed::Box<i32>>, core::mem::maybe_uninit::MaybeUninit<alloc::boxed::Box<i32>>], [])
 Iter([], [])
 

The actual stdout differed from the expected stdout.
Actual stdout saved to /tmp/compiletest20lDZR/vecdeque.stage-id.stdout
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args vecdeque.rs`

error: 1 errors occurred comparing output.
status: exit status: 0
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/miri" "tests/run-pass/vecdeque.rs" "-L" "/tmp/compiletest20lDZR" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/tmp/compiletest20lDZR/vecdeque.stage-id" "-A" "unused" "--edition" "2018" "-Astable-features" "--sysroot" "/home/user/.cache/miri/HOST" "-Zmiri-tag-raw-pointers" "-L" "/tmp/compiletest20lDZR/vecdeque.stage-id.aux"
stdout:
------------------------------------------
[2, 2] Iter([core::mem::maybe_uninit::MaybeUninit<alloc::boxed::Box<i32>>, core::mem::maybe_uninit::MaybeUninit<alloc::boxed::Box<i32>>], [])
Iter([], [])

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

test [ui] run-pass/vecdeque.rs ... FAILED
test [ui] run-pass/float.rs ... ok
````

**Comment by Dylan-DPC** [comment]
CI was failing because previous rustdoc issue that hasn't been merged yet

**Comment by matthiaskrgr** [comment]
Yes the rustdoc failure was also happening, after the miri test failure
https://github.com/rust-lang/rust/runs/5487191514?check_suite_focus=true#step:26:7625

**Pull request closed without merging**
