### PR TITLE
Speed up operations on scopes

### PR DESCRIPTION
**Pull request by arielb1**
This increases regionck performance greatly - type-checking on
librustc decreased from 9.1s to 8.1s. Because of Amdahl's law,
total performance is improved only by about 1.5% (LLVM wizards,
this is your opportunity to shine!).

before:
576.91user 4.26system 7:42.36elapsed 125%CPU (0avgtext+0avgdata 1142192maxresident)k
after:
566.50user 4.84system 7:36.84elapsed 125%CPU (0avgtext+0avgdata 1124304maxresident)k

I am somewhat worried really need to find out why we have this Red Queen's
Race going on here. Originally I suspected it may be a problem from RFC1214's
warnings, but it seems to be an effect from other changes.

However, the increase seems to be mostly in LLVM's time, so I guess
it's the LLVM wizards' problem.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Nice. I was thinking of starting a branch to follow up in these ideas, glad I didn't. Will review Monday probably (if not sooner)/

**Comment by arielb1** [comment]
I will give perf numbers for the last patch when my benchmark machine is working again.

**Comment by nikomatsakis** [comment]
(started a review, mostly jutts nits so far, going to have to finish up tomorrow.)

**Comment by nikomatsakis** [comment]
@bors r+ -- looks nice.

cc @pnkfelix just fyi, this touches some of the setup in region.rs, though I'd make you aware

**Pull request merged**
