### PR TITLE
rustc_errors: only box the `diagnostic` field in `DiagnosticBuilder`.

### PR DESCRIPTION
**Pull request by eddyb**
I happened to need to do the first change (replacing `allow_suggestions` with equivalent functionality on `Diagnostic` itself) as part of a larger change, and noticed that there's only two fields left in `DiagnosticBuilderInner`.

So with this PR, instead of a single pointer, `DiagnosticBuilder` is two pointers, which should work just as well for passing *it* by value (and may even work better wrt some operations, though probably not by much).

But anything that was already taking advantage of `DiagnosticBuilder` being a single pointer, and wrapping it further (e.g. `Result<T, DiagnosticBuilder>` w/ non-ZST `T`), ~~will probably see a slowdown~~, so I want to do a perf run before even trying to propose this.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I suspect it's real -- maybe not *that* pronounced, but 'expected' non-change is typically 2-3% at most for the smaller crates and ~1% for the larger ones.

**Comment by eddyb** [comment]
I didn't expect that, and had a trick I wanted to use to see if I can counter any regressions, but even the small changes being filtered out (from the main benchmarks, not bootstrap times) are all green, no red in there.

I've marked this PR as ready to review, and will be opening separate ones for any other perf experiments.

**Comment by jackh726** [comment]
Simple enough

@bors r+

**Comment by eddyb** [comment]
@bors retry
(spurious network failure?)

**Pull request merged**
