### PR TITLE
experimental: Share generic code for optimized builds.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This is not meant to be merged. I just want to see how sharing monomorphizations affects optimized builds.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, would you mind starting a perf-run for this?

**Comment by Mark-Simulacrum** [comment]
Perf queued for b60bd5703773a04cd853519fdc2465dc9d45603d.

**Comment by ishitatsuyuki** [comment]
Do we have whole crate graph LTO by default? From my understanding this should be paired with that, and should not be enabled on dylibs right?

**Comment by michaelwoerister** [comment]
> Do we have whole crate graph LTO by default?

No, that would probably take too long.

> From my understanding this should be paired with that, and should not be enabled on dylibs right?

It's probably best to wait for MIR-only RLIBs (which are blocked on query parallelization). Those should be even better at sharing code without the runtime performance implications.

**Pull request closed without merging**
