### PR TITLE
Turn macro expansion and name resolution into a query

### PR DESCRIPTION
**Pull request by Zoxc**
Builds on https://github.com/rust-lang/rust/pull/59205.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
ping from triage r? @michaelwoerister

**Comment by Mark-Simulacrum** [comment]
Visiting from triage, I'm closing the series of PRs here other than the first one since they will likely only make progress sequentially and it doesn't help to have all of them open. For reference, this is  blocked on #59205 which is then blocked on #59064.

Feel free to reopen as those PRs merge and/or make progress.

**Comment by gagan0723** [comment]
ping from `wg-triage`, @Zoxc @michaelwoerister any updates on this?

**Comment by Alexendoo** [comment]
Triage: Labelled as blocked, see https://github.com/rust-lang/rust/pull/59282#issuecomment-493679561

**Pull request closed without merging**
