### PR TITLE
Add `Future` and `IntoFuture` to the 2024 prelude

### PR DESCRIPTION
**Pull request by Noratrieb**
Implements rust-lang/rfcs#3509.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
thanks rustbot for giving me a compiler reviewer because i touched ui tests
r? libs

**Comment by fmease** [comment]
> thanks rustbot for giving me a compiler reviewer because i touched ui tests

Since rustbot looks at the size of diffs to find the largest one to find the most appropriate code owner, you should've removed the two empty lines from the Ui test to make it choose libs over compiler (9 LOC libs, 10 →8 LOC compiler). It's your fault! 😝😂

**Comment by fmease** [comment]
> thanks rustbot for giving me a compiler reviewer because i touched ui tests

Since rustbot looks at the size of diffs to find the largest one to figure the most appropriate code owner, you should've removed the two empty lines from the Ui test to make it choose libs over compiler (9 LOC libs, 10 →8 LOC compiler). It's your fault! 😝😂

**Comment by Mark-Simulacrum** [comment]
r=me

**Comment by Nilstrieb** [comment]
ok ok bors i am listening i will stop the eager r+
@bors r-

**Comment by Nilstrieb** [comment]
🙏 
@bors r=Mark-Simulacrum rollup

**Pull request merged**
