### PR TITLE
Arbitrary self types v2: probe for more methods.

### PR DESCRIPTION
**Pull request by adetaylor**
This PR is one of the first steps towards arbitrary self types v2, RFC [3519](https://github.com/rust-lang/rfcs/pull/3519) (#44874). Specifically, it is [step 2 of the plan outlined here](https://github.com/rust-lang/rust/issues/44874#issuecomment-2122179688). That says:

> 1. **Search for potentially conflicting method candidates** per the [deshadowing part of the RFC](https://github.com/rust-lang/rfcs/blob/master/text/3519-arbitrary-self-types-v2.md#compiler-changes-deshadowing). This is the riskiest part - per
    > the production of errors requires us to interrogate more candidates to look for potential conflicts, so this could have a compile-time performance penalty which we should measure
>    let's attempt to land this first and see if performance issues show up. If so, it's back to the drawing board.

So - this commit isn't useful in itself but we need to determine its performance and any unexpected compatibility problems. That's what this PR is for. We shouldn't necessarily merge it.

Here's what this commit does.

Rust prioritizes method candidates in this order:
1. By value;
2. By reference;
3. By mutable reference;
4. By const ptr.

Previously, if a suitable candidate was found in one of these earlier categories, Rust wouldn't even move onto probing the other categories.

As part of the arbitrary self types work, we're going to need to change that - even if we choose a method from one of the earlier categories, we will sometimes need to probe later categories to search for methods that we may be shadowing.

This commit adds those extra searches for shadowing, but it does not yet produce an error when such shadowing problems are found. That will come in a subsequent commit, by filling out the 'check_for_shadowing' method.

We're adding the extra searches in a preliminary commit because they are the risky bit. We want to find any functional or performance problems from these extra searches before we proceed with the actual work on arbitrary self types and specifically on extra deshadowing errors.

### CODE REVIEW

**Comment by adetaylor** [comment]
@wesleywiser Hello, you've been assigned as reviewer!

However, rather than working towards merging this, I'd love advice about how to get Crater running over this, and how best we can assess performance implications. Any suggestions? Otherwise I'll pester some of the usual suspects who have previously been involved in arbitrary self types.

**Comment by adetaylor** [comment]
(a bit of iteration here because I can't get the whole `rustc` test suite to work locally due to something like https://github.com/llvm/llvm-project/issues/92603)

**Comment by jackh726** [comment]
Is a crater run useful here  yet? We're not emitting an extra errors, right?

For sure, perf run here indicates the "minimum extra work" in the happy path though.

**Comment by adetaylor** [comment]
> Is a crater run useful here yet? We're not emitting an extra errors, right?

I've found that the extra calls to (for instance) `pick_autorefd_method` sometimes trigger other `rustc` bugs/overflows/extra error emission. In fact, an earlier version of this commit was causing some failures in `rustc`'s own test suite due to the extra probing which was occurring. I've resolved those specific problems by doing the most minimal possible amount of probing, but it wouldn't surprise me to find that there are unforeseen issues in real crates.

**Comment by lqd** [comment]
@rust-timer build f313d8bf6655283a87ff8f574fbecb272a119a8b

**Comment by adetaylor** [comment]
I'm glad we did a perf run :) It looks like it's significant.

So, the next steps here are:

1. *Redo the PR such that it does less extra stuff, if possible.* This _may_ be possible at the cost of making the method probing more complex. Specifically, options include:
    * *Reduce probing search space* We only want to probe for possibly-shadowed methods meeting certain criteria. Right now we go ahead and call `pick_method` and _then_ evaluate if any discovered methods match those criteria. We may be able to reduce the work done if we pass some of these criteria into `pick_method`, `consider_candidates` etc., reducing the work they have to do.
    * *Cease to fully resolve candidates*. We can take things further by ceasing to return fully-resolved candidates, but instead the minimum information required for `pick_all_method` to determine if there is shadowing. I don't know if there are possibilities here.

2. If spotting these shadowing picks remains expensive, then we'll have to revisit [that section of the RFC to determine if we can live without it, or amend it](https://github.com/rust-lang/rfcs/blob/master/text/3519-arbitrary-self-types-v2.md#compiler-changes-deshadowing). However I'm fairly optimistic we won't need to do that.

I'm unlikely to be able to work on this in the next 3 weeks or so, so I'm closing this PR for now. I may reopen it with an extra commit or two when I get back to this.

**Pull request closed without merging**
