### PR TITLE
Put all existential ty vars in the `ROOT` universe

### PR DESCRIPTION
**Pull request by scalexm**
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@rust-timer build 65100c536f962d5273e5dc088a6534052a93be3a

**Comment by nikomatsakis** [comment]
Giving p=1 because this fixes a massive perf regression.

**Comment by nikomatsakis** [comment]
@scalexm do you know whether the commit that caused problems is on beta?

**Comment by scalexm** [comment]
@nikomatsakis it isn't

**Pull request merged**
