### PR TITLE
Detect missing `;` that parses as function call

### LINKED ISSUE #106515: Unexpected "expected function" error with unit type
I tried this code:

```rust
fn main() {
    let x = 5

    ()
}
```

I expected to see this happen:
```text
error: expected `;`, found `}`
 --> src/main.rs:2:14
  |
2 |     let x = 5
  |              ^ help: add `;` here
3 | }
  | - unexpected token
```
One error occurs from the missing semicolon.

Instead, this happened:
```text
error: expected `;`, found `}`
 --> src/main.rs:4:7
  |
4 |     ()
  |       ^ help: add `;` here
5 | }
  | - unexpected token

error[E0618]: expected function, found `{integer}`
 --> src/main.rs:2:13
  |
2 |       let x = 5
  |  _____________^
3 | |
4 | |     ()
  | |______- call expression requires function
```
An additional unexpected error occurs when when I obviously do not want to invoke a closure. Also note that the semicolon error *is after the supposed closure invocation*, when I would expect it to be after the `let x = 5`.

### Meta
Occurs on latest stable and nightly.

### PR DESCRIPTION
**Pull request by estebank**
Fix #106515.

### CODE REVIEW

**Review by compiler-errors — COMMENTED** [review]
Is it too permissive to suggest this on *any* expr kind? Why is this still limited to just `Path | Call | Lit`?

**Comment by estebank** [comment]
> Is it too permissive to suggest this on any expr kind?

I was slightly concerned, but you're right: this could happen with any expression. I gated this behind the "array element missing comma" check as otherwise `[(foo,) (bar,), (baz,)]` would get both "missing comma" and "missing semicolon" suggestions.

**Comment by estebank** [comment]
seems spurious
@bors retry

**Pull request merged**
