### PR TITLE
Revert #107376 to fix potential `bincode` breakage and `rustc-perf` benchmark.

### LINKED ISSUE #109199: Bincode fails to compile with nightly-2023-03-16: "add_outlives_bounds: unexpected regions"
Trying to install the latest version of nushell, 0.77, fails with compiler error
 
```bash
cargo install nu --features=extra
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (ab654863c 2023-03-15)
binary: rustc
commit-hash: ab654863c3d50482f260cf862647f1fe0ff5e010
commit-date: 2023-03-15
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

### Error output

```
xxx@xxxxxxxx:~$ cargo install nu --features=extra
    Updating crates.io index
  Downloaded nu v0.77.0
  Downloaded 1 crate (256.2 KB) in 0.23s
  Installing nu v0.77.0
    Updating crates.io index
  Downloaded ahash v0.7.6
  Downloaded dirs-next v2.0.0
  Downloaded base64 v0.13.1
  Downloaded crypto-common v0.1.6
  Downloaded crc32fast v1.3.2
  Downloaded mio-extras v2.0.6
  Downloaded minimal-lexical v0.2.1
  Downloaded bincode v1.3.3
  Downloaded cpufeatures v0.2.5
  Downloaded bytesize v1.2.0
  Downloaded crossbeam-utils v0.8.15
  Downloaded arrayvec v0.5.2
  Downloaded dirs-sys-next v0.1.2
  Downloaded bitflags v1.3.2
  Downloaded miniz_oxide v0.6.2
  Downloaded fallible-streaming-iterator v0.1.9
  Downloaded crossbeam-channel v0.5.7
  Downloaded mime_guess v2.0.4
  Downloaded rand_chacha v0.3.1
  Downloaded cassowary v0.3.0
  Downloaded quote v1.0.26
  Downloaded codepage v0.1.1
  Downloaded notify v4.0.17
  Downloaded htmlescape v0.3.1
  Downloaded rayon-core v1.11.0
  Downloaded memchr v2.5.0
  Downloaded erased-serde v0.3.25
  Downloaded rand v0.8.5
  Downloaded ansitok v0.2.0
  Downloaded const_format v0.2.30
  Downloaded byte-unit v4.0.19
  Downloaded console v0.15.5
  Downloaded memoffset v0.8.0
  Downloaded lru v0.9.0
  Downloaded md-5 v0.10.5
  Downloaded regex v1.7.1
  Downloaded serde_derive v1.0.156
  Downloaded rmp v0.8.11
  Downloaded rusqlite v0.28.0
  Downloaded smallvec v1.10.0
  Downloaded strum v0.24.1
  Downloaded strip-ansi-escapes v0.1.1
  Downloaded terminal_size v0.1.17
  Downloaded tinyvec_macros v0.1.1
  Downloaded generic-array v0.14.6
  Downloaded autocfg v1.1.0
  Downloaded toml_datetime v0.6.1
  Downloaded thread_local v1.1.7
  Downloaded phf_generator v0.11.1
  Downloaded nu-cmd-lang v0.77.0
  Downloaded nu-cli v0.77.0
  Downloaded toml_edit v0.19.7
  Downloaded titlecase v2.2.1
  Downloaded unicode-normalization v0.1.22
  Downloaded unicode-segmentation v1.10.1
  Downloaded unicode-xid v0.2.4
  Downloaded unicase v2.6.0
  Downloaded ghost v0.1.8
  Downloaded vte_generate_state_changes v0.1.1
  Downloaded nu-plugin v0.77.0
  Downloaded users v0.10.0
  Downloaded xmlparser v0.13.5
  Downloaded uuid v1.3.0
  Downloaded iovec v0.1.4
  Downloaded roxmltree v0.18.0
  Downloaded rayon v1.7.0
  Downloaded fs_extra v1.3.0
  Downloaded is_ci v1.1.1
  Downloaded inotify v0.7.1
  Downloaded alphanumeric-sort v1.5.0
  Downloaded hashlink v0.8.1
  Downloaded fallible-iterator v0.2.0
  Downloaded iana-time-zone v0.1.53
  Downloaded fancy-regex v0.11.0
  Downloaded inotify-sys v0.1.5
  Downloaded ansi-str v0.5.0
  Downloaded crossterm v0.24.0
  Downloaded is_executable v1.0.1
  Downloaded unsafe-libyaml v0.2.7
  Downloaded utf8-width v0.1.6
  Downloaded thiserror-impl v1.0.39
  Downloaded signal-hook-registry v1.4.1
  Downloaded thiserror v1.0.39
  Downloaded slab v0.4.8
  Downloaded which v4.4.0
  Downloaded time v0.3.20
  Downloaded version_check v0.9.4
  Downloaded unicode-ident v1.0.8
  Downloaded serde v1.0.156
  Downloaded openssl v0.10.46
  Downloaded hashbrown v0.12.3
  Downloaded serde_json v1.0.94
  Downloaded regex-automata v0.1.10
  Downloaded ureq v2.6.2
  Downloaded is_debug v1.0.1
  Downloaded nu-pretty-hex v0.77.0
  Downloaded json_to_table v0.3.1
  Downloaded chrono-humanize v0.2.2
  Downloaded vcpkg v0.2.15
  Downloaded cfg-if v0.1.10
  Downloaded tabled_derive v0.5.0
  Downloaded nu-explore v0.77.0
  Downloaded syn v1.0.109
  Downloaded nom-supreme v0.8.0
  Downloaded rust_decimal v1.29.0
  Downloaded sysinfo v0.28.2
  Downloaded nu-utils v0.77.0
  Downloaded url v2.3.1
  Downloaded nu-ansi-term v0.47.0
  Downloaded vte v0.10.1
  Downloaded time-core v0.1.0
  Downloaded time v0.1.45
  Downloaded walkdir v2.3.2
  Downloaded time-macros v0.2.8
  Downloaded mio v0.8.6
  Downloaded io-lifetimes v1.0.6
  Downloaded rustversion v1.0.12
  Downloaded pathdiff v0.2.1
  Downloaded owo-colors v3.5.0
  Downloaded zip v0.6.4
  Downloaded winnow v0.3.6
  Downloaded tabled v0.10.0
  Downloaded wax v0.5.0
  Downloaded supports-unicode v2.0.0
  Downloaded rustix v0.36.9
  Downloaded openssl-sys v0.9.81
  Downloaded rust-embed v6.6.0
  Downloaded proc-macro2 v1.0.52
  Downloaded typenum v1.16.0
  Downloaded mio v0.6.23
  Downloaded miette v5.6.0
  Downloaded nu-table v0.77.0
  Downloaded lscolors v0.12.0
  Downloaded pure-rust-locales v0.5.6
  Downloaded lazy_static v1.4.0
  Downloaded indent_write v2.2.0
  Downloaded regex-syntax v0.6.28
  Downloaded quick-xml v0.25.0
  Downloaded parse-zoneinfo v0.3.0
  Downloaded parking_lot_core v0.9.7
  Downloaded nom v7.1.3
  Downloaded rand_core v0.6.4
  Downloaded miette-derive v5.6.0
  Downloaded nu-glob v0.77.0
  Downloaded libc v0.2.140
  Downloaded quick-xml v0.27.1
  Downloaded procfs v0.15.1
  Downloaded serde_urlencoded v0.7.1
  Downloaded ryu v1.0.13
  Downloaded open v3.4.0
  Downloaded net2 v0.2.38
  Downloaded native-tls v0.2.11
  Downloaded openssl-probe v0.1.5
  Downloaded openssl-macros v0.1.0
  Downloaded proc-macro-error v1.0.4
  Downloaded proc-macro-error-attr v1.0.4
  Downloaded powierza-coefficient v1.0.2
  Downloaded shell-words v1.1.0
  Downloaded nu-parser v0.77.0
  Downloaded nu-json v0.77.0
  Downloaded pwd v1.4.0
  Downloaded print-positions v0.6.1
  Downloaded nu-protocol v0.77.0
  Downloaded bstr v0.2.17
  Downloaded portable-atomic v0.3.19
  Downloaded csv v1.2.1
  Downloaded nu-command v0.77.0
  Downloaded nix v0.26.2
  Downloaded phf_shared v0.11.1
  Downloaded linux-raw-sys v0.1.4
  Downloaded mime v0.3.16
  Downloaded encoding_rs v0.8.32
  Downloaded num_threads v0.1.6
  Downloaded num_cpus v1.15.0
  Downloaded pori v0.0.0
  Downloaded papergrid v0.7.1
  Downloaded ppv-lite86 v0.2.17
  Downloaded phf_codegen v0.11.1
  Downloaded nu-path v0.77.0
  Downloaded idna v0.3.0
  Downloaded percent-encoding v2.2.0
  Downloaded dialoguer v0.10.3
  Downloaded chrono v0.4.24
  Downloaded static_assertions v1.1.0
  Downloaded phf v0.11.1
  Downloaded trash v3.0.1
  Downloaded serde_yaml v0.9.19
  Downloaded once_cell v1.17.1
  Downloaded dtparse v1.3.0
  Downloaded rust-embed-impl v6.5.0
  Downloaded nu-term-grid v0.77.0
  Downloaded brownstone v3.0.0
  Downloaded sha2 v0.10.6
  Downloaded filetime v0.2.20
  Downloaded bytecount v0.6.3
  Downloaded nu-color-config v0.77.0
  Downloaded nu-system v0.77.0
  Downloaded is-root v0.1.2
  Downloaded ahash v0.8.3
  Downloaded filesize v0.2.0
  Downloaded crossterm v0.25.0
  Downloaded crossbeam-epoch v0.9.14
  Downloaded inventory v0.3.4
  Downloaded hashbrown v0.13.2
  Downloaded unicode-bidi v0.3.11
  Downloaded itoa v1.0.6
  Downloaded foreign-types v0.3.2
  Downloaded utf8parse v0.2.1
  Downloaded scopeguard v1.1.0
  Downloaded foreign-types-shared v0.1.1
  Downloaded digest v0.10.6
  Downloaded form_urlencoded v1.1.0
  Downloaded same-file v1.0.6
  Downloaded libsqlite3-sys v0.25.2
  Downloaded paste v1.0.12
  Downloaded num-traits v0.2.15
  Downloaded indexmap v1.9.2
  Downloaded heck v0.4.1
  Downloaded fuzzy-matcher v0.3.7
  Downloaded umask v2.0.0
  Downloaded simplelog v0.12.1
  Downloaded signal-hook v0.3.15
  Downloaded hex v0.4.3
  Downloaded sys-locale v0.2.4
  Downloaded smawk v0.3.1
  Downloaded shadow-rs v0.21.0
  Downloaded rust-embed-utils v7.5.0
  Downloaded indicatif v0.17.3
  Downloaded calamine v0.19.1
  Downloaded ansi-str v0.7.2
  Downloaded users v0.11.0
  Downloaded fnv v1.0.7
  Downloaded lock_api v0.4.9
  Downloaded reedline v0.17.0
  Downloaded tui v0.19.0
  Downloaded itertools v0.10.5
  Downloaded unicode-width v0.1.10
  Downloaded toml v0.7.3
  Downloaded typetag-impl v0.2.6
  Downloaded typetag v0.2.6
  Downloaded num-integer v0.1.45
  Downloaded unicode-linebreak v0.1.4
  Downloaded serde_spanned v0.6.1
  Downloaded parking_lot v0.12.1
  Downloaded nu-engine v0.77.0
  Downloaded pkg-config v0.3.26
  Downloaded is-terminal v0.4.4
  Downloaded byteorder v1.4.3
  Downloaded arrayvec v0.7.2
  Downloaded textwrap v0.15.2
  Downloaded chrono-tz v0.8.1
  Downloaded bit-vec v0.6.3
  Downloaded joinery v2.1.0
  Downloaded log v0.4.17
  Downloaded tinyvec v1.6.0
  Downloaded terminal_size v0.2.5
  Downloaded supports-hyperlinks v2.0.0
  Downloaded bit-set v0.5.3
  Downloaded termcolor v1.1.3
  Downloaded supports-color v2.0.0
  Downloaded strum_macros v0.24.3
  Downloaded rmp-serde v1.1.1
  Downloaded lazycell v1.3.0
  Downloaded ctor v0.1.26
  Downloaded linked-hash-map v0.5.6
  Downloaded fd-lock v3.0.10
  Downloaded siphasher v0.3.10
  Downloaded signal-hook-mio v0.2.3
  Downloaded num-format v0.4.4
  Downloaded number_prefix v0.4.0
  Downloaded cc v1.0.79
  Downloaded getrandom v0.2.8
  Downloaded crossbeam-deque v0.8.3
  Downloaded csv-core v0.1.10
  Downloaded cfg-if v1.0.0
  Downloaded flate2 v1.0.25
  Downloaded const_format_proc_macros v0.2.29
  Downloaded Inflector v0.11.4
  Downloaded aho-corasick v0.7.20
  Downloaded either v1.8.1
  Downloaded block-buffer v0.10.4
  Downloaded adler v1.0.2
  Downloaded atty v0.2.14
  Downloaded base64 v0.21.0
  Downloaded ctrlc v3.2.5
  Downloaded chrono-tz-build v0.1.0
  Downloaded 286 crates (24.1 MB) in 1.91s (largest was `libsqlite3-sys` at 4.8 MB)
   Compiling libc v0.2.140
   Compiling proc-macro2 v1.0.52
   Compiling quote v1.0.26
   Compiling unicode-ident v1.0.8
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling autocfg v1.1.0
   Compiling syn v1.0.109
   Compiling memchr v2.5.0
   Compiling serde_derive v1.0.156
   Compiling serde v1.0.156
   Compiling bitflags v1.3.2
   Compiling log v0.4.17
   Compiling once_cell v1.17.1
   Compiling ahash v0.7.6
   Compiling num-traits v0.2.15
   Compiling scopeguard v1.1.0
   Compiling getrandom v0.2.8
   Compiling io-lifetimes v1.0.6
   Compiling itoa v1.0.6
   Compiling rustix v0.36.9
   Compiling aho-corasick v0.7.20
   Compiling vte_generate_state_changes v0.1.1
   Compiling linux-raw-sys v0.1.4
   Compiling regex-syntax v0.6.28
   Compiling arrayvec v0.5.2
   Compiling utf8parse v0.2.1
   Compiling unicode-width v0.1.10
   Compiling smallvec v1.10.0
   Compiling vte v0.10.1
   Compiling lock_api v0.4.9
   Compiling regex v1.7.1
   Compiling num-integer v0.1.45
   Compiling typenum v1.16.0
   Compiling signal-hook v0.3.15
   Compiling parking_lot_core v0.9.7
   Compiling signal-hook-registry v1.4.1
   Compiling mio v0.8.6
   Compiling time v0.1.45
   Compiling generic-array v0.14.6
   Compiling iana-time-zone v0.1.53
   Compiling arrayvec v0.7.2
   Compiling pure-rust-locales v0.5.6
   Compiling signal-hook-mio v0.2.3
   Compiling parking_lot v0.12.1
   Compiling hashbrown v0.12.3
   Compiling ryu v1.0.13
   Compiling crossbeam-utils v0.8.15
   Compiling thiserror v1.0.39
   Compiling thiserror-impl v1.0.39
   Compiling memoffset v0.8.0
   Compiling minimal-lexical v0.2.1
   Compiling nom v7.1.3
   Compiling chrono v0.4.24
   Compiling indexmap v1.9.2
   Compiling crossbeam-epoch v0.9.14
   Compiling serde_json v1.0.94
   Compiling heck v0.4.1
   Compiling either v1.8.1
   Compiling cc v1.0.79
   Compiling pkg-config v0.3.26
   Compiling crossterm v0.24.0
   Compiling unicode-linebreak v0.1.4
   Compiling is-terminal v0.4.4
   Compiling ahash v0.8.3
   Compiling rustversion v1.0.12
   Compiling strip-ansi-escapes v0.1.1
   Compiling erased-serde v0.3.25
   Compiling rayon-core v1.11.0
   Compiling crossbeam-deque v0.8.3
   Compiling lscolors v0.12.0
   Compiling crossbeam-channel v0.5.7
   Compiling num-format v0.4.4
   Compiling ctor v0.1.26
   Compiling ghost v0.1.8
   Compiling num_cpus v1.15.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling sys-locale v0.2.4
   Compiling byteorder v1.4.3
   Compiling is_ci v1.1.1
   Compiling smawk v0.3.1
   Compiling bit-vec v0.6.3
   Compiling textwrap v0.15.2
   Compiling inventory v0.3.4
   Compiling supports-color v2.0.0
   Compiling nu-utils v0.77.0
   Compiling bit-set v0.5.3
   Compiling strum_macros v0.24.3
   Compiling hashbrown v0.13.2
   Compiling supports-unicode v2.0.0
   Compiling supports-hyperlinks v2.0.0
   Compiling ansitok v0.2.0
   Compiling typetag-impl v0.2.6
   Compiling miette-derive v5.6.0
   Compiling dirs-sys-next v0.1.2
   Compiling terminal_size v0.1.17
   Compiling proc-macro-error v1.0.4
   Compiling owo-colors v3.5.0
   Compiling utf8-width v0.1.6
   Compiling strum v0.24.1
   Compiling lazy_static v1.4.0
   Compiling byte-unit v4.0.19
   Compiling dirs-next v2.0.0
   Compiling typetag v0.2.6
   Compiling lru v0.9.0
   Compiling rayon v1.7.0
   Compiling miette v5.6.0
   Compiling fancy-regex v0.11.0
   Compiling chrono-humanize v0.2.2
   Compiling pwd v1.4.0
   Compiling unicode-xid v0.2.4
   Compiling time-core v0.1.0
   Compiling paste v1.0.12
   Compiling const_format_proc_macros v0.2.29
   Compiling sysinfo v0.28.2
   Compiling nu-path v0.77.0
   Compiling nu-protocol v0.77.0
   Compiling ansi-str v0.5.0
   Compiling siphasher v0.3.10
   Compiling bytecount v0.6.3
   Compiling crc32fast v1.3.2
   Compiling nu-glob v0.77.0
   Compiling fnv v1.0.7
   Compiling papergrid v0.7.1
   Compiling phf_shared v0.11.1
   Compiling tabled_derive v0.5.0
   Compiling openssl-sys v0.9.81
   Compiling unicase v2.6.0
   Compiling adler v1.0.2
   Compiling nu-ansi-term v0.47.0
   Compiling rand_core v0.6.4
   Compiling miniz_oxide v0.6.2
   Compiling rand v0.8.5
   Compiling nu-engine v0.77.0
   Compiling tabled v0.10.0
   Compiling rmp v0.8.11
   Compiling itertools v0.10.5
   Compiling linked-hash-map v0.5.6
   Compiling tinyvec_macros v0.1.1
   Compiling percent-encoding v2.2.0
   Compiling vcpkg v0.2.15
   Compiling tinyvec v1.6.0
   Compiling nu-json v0.77.0
   Compiling flate2 v1.0.25
   Compiling libsqlite3-sys v0.25.2
   Compiling rmp-serde v1.1.1
   Compiling phf_generator v0.11.1
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling bincode v1.3.3
   Compiling slab v0.4.8
error: internal compiler error: /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/compiler/rustc_infer/src/infer/outlives/env.rs:145:26: add_outlives_bounds: unexpected regions

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/compiler/rustc_errors/src/lib.rs:1644:9
stack backtrace:
   0:     0x7f74b472a50a - std::backtrace_rs::backtrace::libunwind::trace::hca5b94e57c77ccf5
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f74b472a50a - std::backtrace_rs::backtrace::trace_unsynchronized::h5b5fce74d82f8778
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f74b472a50a - std::sys_common::backtrace::_print_fmt::ha47e7aaa1d2225ec
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f74b472a50a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1aaba92be89501b
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f74b478db3e - core::fmt::write::h750a8e721825859f
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f74b471d375 - std::io::Write::write_fmt::hbf6015e32697f7ba
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/io/mod.rs:1684:15
   6:     0x7f74b472a2d5 - std::sys_common::backtrace::_print::h301c6b6cac7c0a3a
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f74b472a2d5 - std::sys_common::backtrace::print::h7f921f37b0542aab
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f74b472d04f - std::panicking::default_hook::{{closure}}::ha1e8e5c596b5be71
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/panicking.rs:271:22
   9:     0x7f74b472cd8b - std::panicking::default_hook::hb0497d64ba7aeb9b
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/panicking.rs:290:9
  10:     0x7f74b7a28475 - rustc_driver_impl[190cb2184ae08abb]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f74b472d88d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5fe0c368b54c8ed7
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/alloc/src/boxed.rs:2002:9
  12:     0x7f74b472d88d - std::panicking::rust_panic_with_hook::hde905c542c1ea61a
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/panicking.rs:696:13
  13:     0x7f74b7f8d161 - std[75e4c6f671155ce4]::panicking::begin_panic::<rustc_errors[bdf389fe3f70d25b]::ExplicitBug>::{closure#0}
  14:     0x7f74b7f88876 - std[75e4c6f671155ce4]::sys_common::backtrace::__rust_end_short_backtrace::<std[75e4c6f671155ce4]::panicking::begin_panic<rustc_errors[bdf389fe3f70d25b]::ExplicitBug>::{closure#0}, !>
  15:     0x7f74b7f856e6 - std[75e4c6f671155ce4]::panicking::begin_panic::<rustc_errors[bdf389fe3f70d25b]::ExplicitBug>
  16:     0x7f74b7fda606 - std[75e4c6f671155ce4]::panic::panic_any::<rustc_errors[bdf389fe3f70d25b]::ExplicitBug>
  17:     0x7f74b7fd6e26 - <rustc_errors[bdf389fe3f70d25b]::HandlerInner>::bug::<&alloc[dd66e831cb8c4684]::string::String>
  18:     0x7f74b7fd6af0 - <rustc_errors[bdf389fe3f70d25b]::Handler>::bug::<&alloc[dd66e831cb8c4684]::string::String>
  19:     0x7f74b7fc2f9b - rustc_middle[d8dcb3e1f9b6a1d3]::util::bug::opt_span_bug_fmt::<rustc_span[e39f9d1da20fb520]::span_encoding::Span>::{closure#0}
  20:     0x7f74b7fc18ea - rustc_middle[d8dcb3e1f9b6a1d3]::ty::context::tls::with_opt::<rustc_middle[d8dcb3e1f9b6a1d3]::util::bug::opt_span_bug_fmt<rustc_span[e39f9d1da20fb520]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f74b7fc18b6 - rustc_middle[d8dcb3e1f9b6a1d3]::ty::context::tls::with_context_opt::<rustc_middle[d8dcb3e1f9b6a1d3]::ty::context::tls::with_opt<rustc_middle[d8dcb3e1f9b6a1d3]::util::bug::opt_span_bug_fmt<rustc_span[e39f9d1da20fb520]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f74b7fc2ee6 - rustc_middle[d8dcb3e1f9b6a1d3]::util::bug::opt_span_bug_fmt::<rustc_span[e39f9d1da20fb520]::span_encoding::Span>
  23:     0x7f74b60864b3 - rustc_middle[d8dcb3e1f9b6a1d3]::util::bug::bug_fmt
  24:     0x7f74b6243b45 - <rustc_infer[4cb97a789990ae8c]::infer::outlives::env::OutlivesEnvironment>::with_bounds::<core[86d79cd3dd753e85]::iter::adapters::flatten::Flatten<core[86d79cd3dd753e85]::iter::adapters::map::Map<indexmap[6bbb46ee84024ff5]::set::IntoIter<rustc_middle[d8dcb3e1f9b6a1d3]::ty::Ty>, <rustc_infer[4cb97a789990ae8c]::infer::InferCtxt as rustc_trait_selection[834a42ea12cf8990]::traits::outlives_bounds::InferCtxtExt>::implied_bounds_tys::{closure#0}>>>
  25:     0x7f74b6540580 - rustc_hir_analysis[60e36e2803dc18bc]::check::compare_impl_item::compare_method_predicate_entailment
  26:     0x7f74b653a6bb - rustc_hir_analysis[60e36e2803dc18bc]::check::compare_impl_item::compare_impl_method
  27:     0x7f74b6532f1c - rustc_hir_analysis[60e36e2803dc18bc]::check::check::check_impl_items_against_trait
  28:     0x7f74b652a2b8 - rustc_hir_analysis[60e36e2803dc18bc]::check::check::check_mod_item_types
  29:     0x7f74b705b2be - rustc_query_system[1a66d6a5882ef44d]::query::plumbing::try_execute_query::<rustc_query_impl[9c3c364151da071f]::queries::check_mod_item_types, rustc_query_impl[9c3c364151da071f]::plumbing::QueryCtxt>
  30:     0x7f74b705ae43 - <rustc_query_impl[9c3c364151da071f]::Queries as rustc_middle[d8dcb3e1f9b6a1d3]::ty::query::QueryEngine>::check_mod_item_types
  31:     0x7f74b70cc27c - <rustc_middle[d8dcb3e1f9b6a1d3]::hir::map::Map>::for_each_module::<rustc_hir_analysis[60e36e2803dc18bc]::check_crate::{closure#6}::{closure#0}>
  32:     0x7f74b5c316b8 - rustc_hir_analysis[60e36e2803dc18bc]::check_crate
  33:     0x7f74b5c28d25 - rustc_interface[c60781b202b529bb]::passes::analysis
  34:     0x7f74b7236b9c - rustc_query_system[1a66d6a5882ef44d]::query::plumbing::try_execute_query::<rustc_query_impl[9c3c364151da071f]::queries::analysis, rustc_query_impl[9c3c364151da071f]::plumbing::QueryCtxt>
  35:     0x7f74b7236890 - <rustc_query_impl[9c3c364151da071f]::Queries as rustc_middle[d8dcb3e1f9b6a1d3]::ty::query::QueryEngine>::analysis
  36:     0x7f74b7060899 - <rustc_middle[d8dcb3e1f9b6a1d3]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[190cb2184ae08abb]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>>
  37:     0x7f74b6becdc8 - rustc_span[e39f9d1da20fb520]::with_source_map::<core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>, rustc_interface[c60781b202b529bb]::interface::run_compiler<core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>, rustc_driver_impl[190cb2184ae08abb]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  38:     0x7f74b6be48e0 - <scoped_tls[3baa4ec3dd04ff72]::ScopedKey<rustc_span[e39f9d1da20fb520]::SessionGlobals>>::set::<rustc_interface[c60781b202b529bb]::interface::run_compiler<core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>, rustc_driver_impl[190cb2184ae08abb]::run_compiler::{closure#1}>::{closure#0}, core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>>
  39:     0x7f74b6be3fc2 - std[75e4c6f671155ce4]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c60781b202b529bb]::util::run_in_thread_pool_with_globals<rustc_interface[c60781b202b529bb]::interface::run_compiler<core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>, rustc_driver_impl[190cb2184ae08abb]::run_compiler::{closure#1}>::{closure#0}, core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>>
  40:     0x7f74b6be3d6a - <<std[75e4c6f671155ce4]::thread::Builder>::spawn_unchecked_<rustc_interface[c60781b202b529bb]::util::run_in_thread_pool_with_globals<rustc_interface[c60781b202b529bb]::interface::run_compiler<core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>, rustc_driver_impl[190cb2184ae08abb]::run_compiler::{closure#1}>::{closure#0}, core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[86d79cd3dd753e85]::result::Result<(), rustc_span[e39f9d1da20fb520]::ErrorGuaranteed>>::{closure#1} as core[86d79cd3dd753e85]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f74b4737783 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3341c80cf784afb0
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/alloc/src/boxed.rs:1988:9
  42:     0x7f74b4737783 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6a4397435c8c4587
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/alloc/src/boxed.rs:1988:9
  43:     0x7f74b4737783 - std::sys::unix::thread::Thread::new::thread_start::h4d87276efd9893f6
                               at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys/unix/thread.rs:108:17
   Compiling same-file v1.0.6
  44:     0x7f74b447bb43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  45:     0x7f74b450da00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  46:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-nightly (ab654863c 2023-03-15) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=s -C linker-plugin-lto -C strip=debuginfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_mod_item_types] checking item types in module `de`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `bincode` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.77.0`, intermediate artifacts can be found at `/tmp/cargo-installskD4aP`
```

### PR DESCRIPTION
**Pull request by lqd**
#107376 caused `rustc-perf`'s `webrender` benchmark to break, by regressing on the `bincode-1.3.3` crate.

~~This PR is a draft revert in case we can't land a fix soon enough, and we'd like to land the revert instead~~

(Though I myself think it'd be safer to do the revert, and run crater when relanding #107376.)

cc @aliemjay

### CODE REVIEW

**Comment by compiler-errors** [comment]
> Though I myself think it'd be safer to do the revert, and run crater when relanding https://github.com/rust-lang/rust/pull/107376.

I also think that this is probably the safest approach as well.

**Comment by compiler-errors** [comment]
Anyways, if you'd like to unblock perf sooner than later, r=me.

**Comment by lqd** [comment]
> if you'd like to unblock perf sooner than later

That wasn't the primary motivation -- `bincode` seems popular and the next nightly might cause a bunch of breakage otherwise -- but now that you mention it, it's another good reason to do so :)

We're likely going to miss the nightly cutoff, unfortunately.

We _could_ add the [MCVE](https://github.com/rust-lang/rust/pull/107376#issuecomment-1470570487) as a test here, but if we plan to run crater anyways, it can be added when we revert this revert.

Thanks @compiler-errors.

r? @compiler-errors @bors r=compiler-errors

**Review by aliemjay — APPROVED** [review]
Thank you for the revert and the MCVE!

I haven't thought enough about how this blocks perf. I should've prioritized the issue more.

**Comment by lqd** [comment]
Even if no triage needs to be done per-se: this is a revert, and the `tt-muncher` benchmark is currently noisy.

**Pull request merged**
