### PR TITLE
[Do not merge] Allow generic parameters to be specified in expressions without `::`

### PR DESCRIPTION
**Pull request by varkor**
Note: this PR is an experiment in making the `::` generics disambiguation in expressions optional. It is not intended to be merged. Any serious consideration of such a change would be subject to the full RFC process.

---

I was almost ready to move on, then I realised I had made a silly mistake in the last experiment. I wanted to just see whether this small optimisation made a difference or not.

(I closed the old branch on https://github.com/rust-lang/rust/pull/53074, so I had to open a new PR.)

r? @varkor (not sure if this works, to avoid pinging anyone unnecessarily)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
You can r? @ghost as well, same as we do for rollup PRs automatically.

**Comment by varkor** [comment]
> You can r? @ghost as well, same as we do for rollup PRs automatically.

Ah, neat, thanks!

**Comment by varkor** [comment]
@rust-timer build 670e75fae5ca5024e3e2ec5903f7c41a0fe58e62

**Comment by varkor** [comment]
https://github.com/rust-lang/rfcs/pull/2527 has now been opened following the discoveries here.

**Comment by varkor** [comment]
While this is feasible from a performance perspective, there are additional grammar ambiguities I had not considered. Sadly this experiment must remain that.

**Pull request closed without merging**
