### PR TITLE
 Reorder check_item_type diagnostics so they occur next to the corresponding `check_well_formed` diagnostics

### PR DESCRIPTION
**Pull request by oli-obk**
The first commit is just a cleanup.

The second commit moves most checks from `check_mod_item_types` into `check_well_formed`, invoking the checks in lockstep per-item instead of iterating over all items twice.

### CODE REVIEW

**Comment by oli-obk** [comment]
I don't expect a perf effect, but technically some incremental cache dep graph could be affected

@bors try @rust-timer queue

**Comment by oli-obk** [comment]
cc @rust-lang/rustdoc I had to revert some of #97842, as that only works if we avoid some sanity checks. We'll need to figure out a new way to get whatever was desired by that PR (though my changes did not affect any test output I think?)

**Comment by GuillaumeGomez** [comment]
cc @notriddle as you are the author of https://github.com/rust-lang/rust/pull/97842.

**Review by estebank — APPROVED** [review]
r=me

**Review by notriddle — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I'm not against it but you're the person who worked on it so just wanted you to be aware of it. :)

**Comment by oli-obk** [comment]
Almost all of the regression is expected. Rustdoc was not performing various sanity checks, but now is performing them. So this change is part of the longer term strategy of making Rustdoc stop documenting code that wouldn't even pass a check build.

I'll look into the other (<0.5% and few) regressions. They should be fixable by removing the check_mod_item_types query entirely. To do this I need to move the entry fn sanity checks to another query. Ideally to the `entry_fn` query or what it's called

**Comment by oli-obk** [comment]
The remaining regression is actually a tiny reduction in executions of `incr_comp_encode_dep_graph`.

but there seems to be some extra cost in the dep graph:

```rust
1,938,519  ???:<rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  645,665  ???:_rjem_je_arena_cache_bin_fill_small
  309,036  ???:do_rallocx
  286,648  ???:_rjem_je_malloc_default
  277,177  ???:_rjem_je_arena_ralloc
  198,054  ???:_rjem_je_arena_ralloc_no_move
  130,937  /build/glibc-sMfBJT/glibc-2.31/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms
  100,089  ???:_rjem_je_tcache_alloc_small_hard
   99,620  /build/glibc-sMfBJT/glibc-2.31/nptl/../nptl/pthread_mutex_trylock.c:pthread_mutex_trylock
```

**Comment by oli-obk** [comment]
I guess there's a small advantage to having multiple queries for wf checks, those queries that only depend on green queries do not get rerun. If you have a larger query, it gets rerun if any inputs differ, being more expensive in total if one of the smaller queries would not have gotten rerun.

I'll split out the rustdoc regression part into its own PR, then we have a cleaner diff here

**Comment by oli-obk** [comment]
The 1.4% regression must be noise, it is purely in codegen, and this PR does not affect codegen.

The other regressions are real, either in incremental cache loading or in wf-check. Surprising, so I'll dig into those.

**Comment by oli-obk** [comment]
The regression is because we actually need to do *some* work when `ensure`ing a query:

```
1,854,992  ???:<rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  597,830  ???:_rjem_je_arena_cache_bin_fill_small
 -473,102  /build/glibc-wuryBv/glibc-2.31/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms
  309,010  ???:do_rallocx
  277,039  ???:_rjem_je_arena_ralloc
  269,328  ???:_rjem_je_malloc_default
  224,251  ???:rustc_middle::ty::codec::encode_with_shorthand::<rustc_middle::query::on_disk_cache::CacheEncoder, rustc_middle::ty::Ty, <rustc_middle::query::on_disk_cache::CacheEncoder as rustc_type_ir::codec::TyEncoder>::type_shorthands>
  198,054  ???:_rjem_je_arena_ralloc_no_move
   94,215  ???:_rjem_je_tcache_alloc_small_hard
   91,732  /build/glibc-wuryBv/glibc-2.31/nptl/../nptl/pthread_mutex_trylock.c:pthread_mutex_trylock
   85,620  ???:_rjem_je_tcache_bin_flush_stashed
  -72,143  ???:rustc_query_impl::plumbing::encode_query_results::<rustc_query_impl::query_impl::typeck::QueryType>::{closure
```

**Pull request merged**
