### PR TITLE
Consolidating looping documentation 

### PR DESCRIPTION
**Pull request by KieranHunt**
I found that the book had little information for `loop`s and `loop` label so I've added some.

### CODE REVIEW

**Comment by KieranHunt** [comment]
I see that `loop`s are alluded to [here](https://doc.rust-lang.org/book/while-loops.html). I'm not sure if it would be better to merge what I've done with that page or move that information into this new page. 

Another idea is to put all of the looping (`loop`, `while`, and `for`) information onto a single page.

**Comment by steveklabnik** [comment]
> Another idea is to put all of the looping (loop, while, and for) information onto a single page.

I like this idea a lot. Would you mind updating this PR to do that?

**Comment by KieranHunt** [comment]
I've moved all of the looping information to a single page and removed the individual pages for `while` and `for` loops. I didn't really change the content much apart from making sure that it flows nicely and adding a brief introduction.

**Comment by steveklabnik** [comment]
Thanks so much!

**Comment by KieranHunt** [comment]
Thank you, it was my pleasure.

**Comment by Manishearth** [comment]
@bors r-

This causes tests to fail, http://buildbot.rust-lang.org/builders/auto-mac-32-opt/builds/5983/steps/test/logs/stdio

(try it with `make tmp/check-stage2-T-i686-apple-darwin-H-i686-apple-darwin-doc-trpl-loops.ok`)

**Comment by KieranHunt** [comment]
I'm a bit confused. I see from the link that a test failed. But after that it seemed that the merge went through? I'm not sure how to replicate those tests. Looking at [the log file](http://buildbot.rust-lang.org/builders/auto-mac-32-opt/builds/5983/steps/test/logs/stdio) I'm not even sure what test failed.

Can someone fill me in?

**Comment by Manishearth** [comment]
It didn't merge, the line above is the commit message for the rollup merge being linked to this pull request for mentioning its id (#27305). If it merged this PR would automatically get marked as such :smile:

Thsoe are the doctests -- all rust code (except the bits annotated with `ignore`) in documentation is compiled and run. Something went wrong there. `make tmp/check-stage2-T-i686-apple-darwin-H-i686-apple-darwin-doc-trpl-loops.ok` or even `make check-stage1-doc-trpl-loops` should work (not sure about the latter).

`rustdoc --test loops.md` might also work.

It's quite possible that this was a freak error on the buildbot side, in which case we can just retry your pull request.

**Comment by Manishearth** [comment]
(for me when I try `rustdoc --test loops.md` it hangs)

**Comment by KieranHunt** [comment]
The hanging is intended. There is an example of an infinite loop:
```rust
loop {
    println!("Loop forever!");
}
```
Shall I annotate it to be ignored?

**Comment by KieranHunt** [comment]
So [that failure](http://buildbot.rust-lang.org/builders/auto-linux-64-nopt-t/builds/5907/steps/test/logs/stdio) is reported as:

```
thread '<unnamed>' panicked at 'Some tests failed', ../src/libtest/lib.rs:253
make: *** [tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-doc-trpl-functions.ok] Error 101
```

That seems to relate to the functions.md chapter of the book. My PR doesn't relate to, or touch, that at all.

**Comment by killercup** [comment]
@KieranHunt, just FYI, you could use `no_run` instead of `ignore` to have rustdoc check for syntax errors :)

**Comment by Gankro** [comment]
Looks like a spurious error -- stdio disappeared. 

@bors retry

**Pull request merged**
