### PR TITLE
Stabilize raw-dylib, link_ordinal, import_name_type and -Cdlltool

### PR DESCRIPTION
**Pull request by dpaoliello**
This stabilizes the `raw-dylib` feature (#58713) for all architectures (i.e., `x86` as it is already stable for all other architectures).

Changes:
* Permit the use of the `raw-dylib` link kind for x86, the `link_ordinal` attribute and the `import_name_type` key for the `link` attribute.
* Mark the `raw_dylib` feature as stable.
* Stabilized the `-Zdlltool` argument as `-Cdlltool`.
* Note the path to `dlltool` if invoking it failed (we don't need to do this if `dlltool` returns an error since it prints its path in the error message).
* Adds tests for `-Cdlltool`.
* Adds tests for being unable to find the dlltool executable, and dlltool failing.
* Fixes a bug where we were checking the exit code of dlltool to see if it failed, but dlltool always returns 0 (indicating success), so instead we need to check if anything was written to `stderr`.

NOTE: As previously noted (https://github.com/rust-lang/rust/pull/104218#issuecomment-1315895618) using dlltool within rustc is temporary, but this is not the first time that Rust has added a temporary tool use and argument: https://github.com/rust-lang/rust/pull/104218#issuecomment-1318720482

Big thanks to @tbu- for the first version of this PR (#104218)

### CODE REVIEW

**Comment by tbu-** [comment]
Thanks for picking this up! :)

**Comment by est31** [comment]
> using `\n` in the messages.ftl file doesn't work

FTR if you think that the stdout contains useful information, you can directly do newlines in fluent files, they need to just be aligned correctly to the previous line. The Dlltool error doesn't seem to be the only place this mistake has happened in ftl files, and I suppose it's not that hard to think that `\n` works in them, so I've opened #109686.

**Comment by michaelwoerister** [comment]
Thanks a lot, @dpaoliello! The PR looks good to me.

The only thing I'm missing is a mention of the `import_name_type` (added in https://github.com/rust-lang/rust/pull/100732) in the stabilization report and in the [documentation update PR](https://github.com/rust-lang/reference/pull/1345). Once we have that, we can start the FCP 🙂

**Comment by michaelwoerister** [comment]
@petrochenkov, you mentioned potential interactions between `-Cdlltool` and `-Cself-contained` in https://github.com/rust-lang/rust/pull/109575. Are there any blocking issues around that? It sounds like the two features are not in conflict with each other, right?

**Comment by petrochenkov** [comment]
>you mentioned potential interactions between `-Cdlltool` and `-Cself-contained` in https://github.com/rust-lang/rust/pull/109575. Are there any blocking issues around that? It sounds like the two features are not in conflict with each other, right?

No, there shouldn't be any major issues.

**Comment by dpaoliello** [comment]
> The only thing I'm missing is a mention of the `import_name_type` (added in #100732) in the stabilization report and in the [documentation update PR](https://github.com/rust-lang/reference/pull/1345). Once we have that, we can start the FCP 🙂

@michaelwoerister Done!

**Comment by michaelwoerister** [comment]
Thanks, @dpaoliello! Let's start the FCP then. This includes the lang team for final sign off on the `import_name_type` field of the `#[link]` attribute. In https://github.com/rust-lang/rust/pull/100732#issuecomment-1225873457, @joshtriplett gave a general OK for the new key, but let's make it part of an FCP.

@dpaoliello's extensive stabilization report is in the tracking issue at https://github.com/rust-lang/rust/issues/58713#issuecomment-1485826095.

@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
@rfcbot fcp reviewed

**Comment by tmandry** [comment]
I think it's a bit unfortunate that in the compiler we use `dylib` to mean Rust and `cdylib` to mean native, but here `dylib` is used to mean native. That said this was already stabilized for most platforms, so we won't revisit that here (and perhaps it was already discussed).

@rfcbot reviewed

**Comment by dpaoliello** [comment]
Ping @Aaron1011 @estebank @joshtriplett @nagisa @pnkfelix @scottmcm - can I please get a review?

**Comment by kennykerr** [comment]
MrBeanWaitingGIF

**Comment by michaelwoerister** [comment]
@estebank, @joshtriplett, @nagisa, @pnkfelix: Gentle ping about [this FCP](https://github.com/rust-lang/rust/pull/109677#issuecomment-1491574659). Do you have any concerns stabilizing the rest of the raw-dylib feature?

**Comment by pnkfelix** [comment]
@rfcbot fcp reviewed

**Review by wesleywiser — APPROVED** [review]

**Pull request merged**
