### PR TITLE
Rustdoc coverage fields count

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow-up of #88688.

Instead of requiring enum tuple variant fields and tuple struct fields to be documented, we count them if they are documented, otherwise we don't include them in the count.

r? @Manishearth

### CODE REVIEW

**Review by Manishearth — COMMENTED** [review]
I don't understand why we need an additional hashmap: is there a reason we cannot look at the parent of the node and check what kind of field it is?

**Comment by GuillaumeGomez** [comment]
I feel very stupid not doing that. Updating.

**Comment by GuillaumeGomez** [comment]
Rewrote using the direct parent through hir map this time.

**Review by Manishearth — APPROVED** [review]
r=me

**Pull request merged**
