### PR TITLE
[experiment] ty: add `flags`, `outer_exclusive_binder` fields to `ty::List`.

### PR DESCRIPTION
**Pull request by eddyb**
These fields would be used just like the ones in `TyS`, for storing the computed flags of e.g. `Substs`.

I'm opening this PR to check that adding these fields doesn't cause perf regressions.

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
Looks fine, I think.

**Comment by nikomatsakis** [comment]
@eddyb is this something you would like me to review now?

**Comment by eddyb** [comment]
@nikomatsakis If you want to, we could even land this and populate these fields later *shrug*.

**Comment by nikomatsakis** [comment]
@eddyb Hmm, that seems like it would be confusing, to leave this change "half done". I'm fine if it's not ready to land yet.

**Comment by nikomatsakis** [comment]
I'm going to close this to help me manage my queue, feel free to re-open @eddyb if desired.

**Pull request closed without merging**
