### PR TITLE
Remove inherited `#[stable(..)]` annotations

### LINKED ISSUE #65515: Reduce the places where `stable` annotations are needed
Looking at the definition of `std::option::Option`, we have the following `stable` annotations:

```rust
#[derive(Copy, PartialEq, PartialOrd, Eq, Ord, Debug, Hash)]
#[stable(feature = "rust1", since = "1.0.0")]
pub enum Option<T> {
    /// No value
    #[stable(feature = "rust1", since = "1.0.0")]
    None,
    /// Some value `T`
    #[stable(feature = "rust1", since = "1.0.0")]
    Some(#[stable(feature = "rust1", since = "1.0.0")] T),
}
```

Is it strictly _necessary_ for the stability checker to look at the fields of enum variants (or of structs, for that matter)?

It seems to me that `MissingStabilityAnnotations` could be modified to allow stability markings to flow down from at least a variant to its fields, as _changing_ them is not a backwards compatible change and shouldn't ever happen. Even extending an existing enum would be backwards incompatible, so I would even flow from ADT attribute downwards. This would let the definition above to be:

```rust
#[derive(Copy, PartialEq, PartialOrd, Eq, Ord, Debug, Hash)]
#[stable(feature = "rust1", since = "1.0.0")]
pub enum Option<T> {
    /// No value
    None,
    /// Some value `T`
    Some(T),
}
```

This is normally not an issue, but with [the new output in #65421](https://github.com/rust-lang/rust/pull/65421#issuecomment-542869234) we will start showing this code to end users in errors, and it'd be nice if we could eliminate unnecessary boilerplate.

### PR DESCRIPTION
**Pull request by estebank**
Fix #65515. Blocked on #71481 landing on the beta compiler used to build master.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Triage: #71481 is now live on beta 🎉

**Comment by Dylan-DPC** [comment]
unblocking this

**Comment by Dylan-DPC** [comment]
@estebank any updates?

**Comment by estebank** [comment]
I tried applying this PR but it seems like there are some additional changes that I need to make for this to work.

**Comment by JohnCSimon** [comment]
@estebank any updates for this PR?

**Comment by Dylan-DPC** [comment]
closing this as it has bitrotted

**Pull request closed without merging**
