### PR TITLE
Update RLS

### PR DESCRIPTION
**Pull request by Xanewok**
Continuation of https://github.com/rust-lang/rust/pull/53610.
Workspaces are tricky - the `json_internal` problem was only reproducible in Rust CI (not sure why it was only relevant to Windows?) and it seems that this was fixed by updating serde_json workspace-wide.

Tested locally in Rust repo and it seems to be working.

Nightlies are currently shipping without RLS, so it'd be great to include this in the next nightlies if possible.

### CODE REVIEW

**Comment by kennytm** [comment]
Please exempt `ryu` from tidy for now.

**Comment by Xanewok** [comment]
@kennytm done.

**Comment by kennytm** [comment]
@bors delegate+

#53567, if merged, will conflict with this PR, and you'll need to rebase then.

**Pull request merged**
