### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by oli-obk**
r? @Manishearth 

cc @kennytm 

supersedes #47172 by not running dogfood in the rustc test suite and placing the clippy ui output files into /tmp

### CODE REVIEW

**Comment by kennytm** [comment]
```
[00:02:53] Makefile:76: recipe for target 'prepare' failed
[00:02:53] Command failed. Attempt 5/5:
[00:02:53]     Updating registry `https://github.com/rust-lang/crates.io-index`
[00:02:53] error: failed to select a version for `compiletest_rs` (required by `miri`):
[00:02:53] all possible versions conflict with previously selected versions of `compiletest_rs`
[00:02:53]   version 0.3.5 in use by compiletest_rs v0.3.5
[00:02:53]   possible versions to select: 0.3.3
[00:02:53] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
```

Please do a `cargo update`.

**Comment by oli-obk** [comment]
I did. It's conflicting with miri. But I can't update just the Cargo.toml of miri, I need to get it working again before it'll allow me to merge ;)

**Comment by Manishearth** [comment]
r=me when you fix the build

**Comment by shepmaster** [comment]
Ping from triage @oli-obk ! We haven't heard from you in a week; will you be able to "get it working again" in the near future? 😇

**Comment by oli-obk** [comment]
Yea this'll be stuck a while longer

**Pull request closed without merging**
