### PR TITLE
[experiment] remove diverge_from in box expr building

### PR DESCRIPTION
**Pull request by nbdd0121**
See if some instruction count regressions can be regained from #89030

r? @ghost

### CODE REVIEW

**Comment by nbdd0121** [comment]
@rylev could you do a perf run please?

**Comment by nbdd0121** [comment]
Trying another approach. This should have similar result, but the change is made in library not in compiler. Please have another perf run.

**Comment by nbdd0121** [comment]
As I expected the performance is largely similar to removing the diverging path. I have no idea why adding rustc_allocator_nounwind makes expand_crate slower though.

**Comment by JohnCSimon** [comment]
This needs to assign a reviewer.

**Comment by camelid** [comment]
r? rust-lang/libs

**Comment by the8472** [comment]
> This needs to assign a reviewer.

does it? it's still labeled as experiment

**Comment by nbdd0121** [comment]
I am unsure whether this should proceed. I can turn this into a PR that removes the unwinding path and gain a bit perf now, but it'll need to reverted anyway to support oom=panic.

**Comment by nbdd0121** [comment]
Also this is more T-compiler than T-libs.

@rustbot label: -T-libs +T-compiler

**Comment by camelid** [comment]
r? rust-lang/compiler

**Comment by pnkfelix** [comment]
> 

Discussed in T-compiler meeting.

Given that our  trajectory is to support oom=panic (PR #88098, Tracking Issue #43596), we do not think we will be landing this.

It was good to gather the performance data, though!

**Pull request closed without merging**
