### PR TITLE
Update miri submodule

### LINKED ISSUE #64244: `miri` no longer builds after rust-lang/rust#64230
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#64230, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #64244

### CODE REVIEW

**Comment by tmandry** [comment]
why was this r-?

**Comment by eddyb** [comment]
@tmandry IIUC, there's a bors bug where sometimes it starts a build just after the PR has been merged as part of a rollup.
That build gets cancelled or something but the PR stays in a weird state until someone does what @pietroalbini did, is my guess.

**Comment by pietroalbini** [comment]
Yep, basically what @eddyb said. The bug shows up usually after we restart bors.

**Comment by tmandry** [comment]
oh, I see, thanks. I somehow didn't see that this was merged =)

**Pull request merged**
