### PR TITLE
rustc_plugin: Remove `Registry::register_attribute`

### PR DESCRIPTION
**Pull request by petrochenkov**
Legacy plugins cannot register inert attributes anymore.

The preferred replacement is to use `register_tool` ([tracking issue](https://github.com/rust-lang/rust/issues/66079)).
```rust
#![register_tool(servo)]

#[servo::must_root]
struct S;
```

The more direct replacement is `register_attribute` ([tracking issue](https://github.com/rust-lang/rust/issues/66080))
```rust
#![register_attr(must_root)]

#[must_root]
struct S;
```
, but it requires registering each attribute individually rather than registering the tool once, and is more likely to be removed rather than stabilized.

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @SimonSapin @rust-lang/dev-tools

**Comment by SimonSapin** [comment]
@petrochenkov Would you be ok with waiting a bit before landing this? The alternative only landed very recently, and upgrading the Rust version used in Servo is currently blocked on fixing some new warnings: https://github.com/servo/servo/issues/24684

**Comment by SimonSapin** [comment]
I’ve verified that removing `Registry::register_attribute` calls produces errors that are fixed either by adding `#![register_attr(…)]` attributes, or by adding a `#![register_tool(…)]` attribute and a corresponding prefix path component to each use of the relevant attributes.

I’m afraid the latter renders the lint ineffective since it relies on `TyCtxt.html#method.has_attr` which takes a single `Symbol`. I didn’t find an equivalent for an attribute whose path has two components, but it shouldn’t be too hard to write.

**Review by matthewjasper — APPROVED** [review]
Changes look good. I'm marking as blocked while Servo makes changes.

**Comment by SimonSapin** [comment]
Alright, Servo should be unblocked now: https://github.com/servo/servo/pull/24750

**Pull request merged**
