### PR TITLE
submodules: update clippy, rls and miri

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Let's give this another try.
r? @Manishearth 
cc @Xanewok

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
````
[01:42:31] test client_use_statement_completion_doesnt_suggest_arguments ... ok
[01:42:31] test client_test_simple_workspace ... ok
[01:42:32] test client_workspace_symbol ... ok
[01:42:32] test client_workspace_symbol_duplicates ... ok
[01:42:56] thread panicked while panicking. aborting.
[01:42:56] [2019-04-09T11:54:19Z ERROR rls::server] Can't read message
[01:42:56] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:997:5
[01:42:56] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:42:56] error: process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/client-55bfb9e00fb32a17` (signal: 4, SIGILL: illegal instruction)
[01:42:56]
[01:42:56]
[01:42:56] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/rls/Cargo.toml" "--features" "rustc-workspace-hack/all-static" "--"
[01:42:56] expected success, got: exit code: 101
[01:42:56]
[01:42:56]
[01:42:56] [TIMING] Rls { stage: 2, host: "x86_64-unknown-linux-gnu" } -- 212.034
Building stage2 tool rustfmt (x86_64-unknown-linux-gnu)
[01:42:57]    Compiling rustfmt-nightly v1.2.0 (/checkout/src/tools/rustfmt)
[01:44:08] [RUSTC-TIMING] rustfmt_nightly test:false 70.169
[01:44:23] [RUSTC-TIMING] rustfmt_format_diff test:false 14.716
[01:44:32] [RUSTC-TIMING] cargo_fmt test:false 23.426
[01:44:33] [RUSTC-TIMING] git_rustfmt test:false 24.930
[01:44:36] [RUSTC-TIMING] rustfmt test:false 27.628
````

This didn't happen when I tested locally, hmm.

**Comment by RalfJung** [comment]
Yeah, that's a spurious RLS error I have seen before. Is there an issue for it?

**Comment by matthiaskrgr** [comment]
Timed out again ...

**Comment by Manishearth** [comment]
This is https://github.com/rust-lang/rust/issues/59815

@bors treeclosed=15

**Comment by matthiaskrgr** [comment]
Can someone re-r+ ? :sweat_smile:

**Comment by Manishearth** [comment]
I was waiting to come to work so that I can cancel builds where the bad mac builders get picked

**Comment by Manishearth** [comment]
Hmm, the `-alt` task got a separate builder, but we still have two mac tasks sharing the same problematic builder.

**Comment by Manishearth** [comment]
@bors retry

pietro has emailed Travis, hopefully they fix it? Or we get lucky and this PR doesn't get the cursed builders

**Comment by Manishearth** [comment]
@bors retry

the other mac failure

**Comment by Manishearth** [comment]
Wait, that's a different failure, but it's also an intermittent.

**Comment by Aaron1011** [comment]
The android failure appears to be another instance of https://github.com/rust-lang/rust/issues/55861

**Comment by TimDiekmann** [comment]
If someone is looking for all possible travis failures, they only need to read this and preceding threads.

**Comment by pietroalbini** [comment]
@bors retry

We're overcommitted again.

**Comment by pietroalbini** [comment]
@bors retry

*Please* Travis.

**Comment by matthiaskrgr** [comment]
Merging manually is not an option, right? :/

**Comment by pietroalbini** [comment]
Nope, release artifacts (also used for nightly) are uploaded after the build, and if we merge before all the builders finish we're going to miss macOS, which is unacceptable since it's a Tier 1 platform.

I'm going to stop retrying until Travis replies to me (pinged them again a few minutes ago) as we keep getting scheduled on the same builder. No point spamming y'all with all the retries.

**Comment by TimDiekmann** [comment]
We could still unsubscribe and set an alarm for 3 hours ;)

**Comment by TimDiekmann** [comment]
Currently, all four apple builds are more or less even in time. Both `dist-` builds are behind by 3 minutes. Looks promising :)

**Pull request merged**
