### PR TITLE
Remove unused methods from MultiSpan

### PR DESCRIPTION
**Pull request by sophiajt**
Removed a couple of unused methods from MultiSpan.  I thought about batching this with some other changes but wasn't sure when I'd get around to them, so PR for a tiny fix instead.

This can be rollup'd.

### CODE REVIEW

**Comment by mcarton** [comment]
This PR seems to have removed the only way to create a `MultiSpan` with more that one primary span (the only two ways to create one are now `MultiSpan::new()` and `impl From<Span> for MultiSpan`). Since `primary_spans` is a vector and used everywhere as if there can be more than one primary span (it's sorted, its min is taken, etc) I wonder whether this is intentional. If so, more cleanup should be done and `primary_spans` should be made an option.

This also breaks Clippy (https://github.com/Manishearth/rust-clippy/issues/1120, https://github.com/Manishearth/rust-clippy/issues/1119) without a simple way to fix it, so I'd like to know whether I can hope getting that method back or should remove the broken Clippy feature.

**Comment by jonathandturner** [comment]
@mcarton I joined the discussion on https://github.com/Manishearth/rust-clippy/pull/1119 to see if there are alternate fixes for clippy.  Since MultiSpan isn't being used in the compiler in this way, I wanted to continue to simplify it.  As you point out, there's more there to be done.

**Pull request merged**
