### PR TITLE
Merge `#[deprecated]` and `#[rustc_deprecated]`

### PR DESCRIPTION
**Pull request by jhpratt**
The first commit makes "reason" an alias for "note" in `#[rustc_deprecated]`, while still prohibiting it in `#[deprecated]`.

The second commit changes "suggestion" to not just be a feature of `#[rustc_deprecated]`. This is placed behind the new `deprecated_suggestion` feature. This needs a tracking issue; let me know if this PR will be approved and I can create one. 

The third commit is what permits `#[deprecated]` to be used when `#![feature(staged_api)]` is enabled. This isn't yet used in stdlib (only tests), as it would require duplicating all deprecation attributes until a bootstrap occurs. I intend to submit a follow-up PR that replaces all uses and removes the remaining `#[rustc_deprecated]` code after the next bootstrap.

@rustbot label +T-libs-api +C-feature-request +A-attributes +S-waiting-on-review

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
Seems reasonable to me.

**Comment by Mark-Simulacrum** [comment]
@oli-obk I presume the nomination here is for the unstable deprecated_suggestion feature? It'd be great to leave a comment in the future to avoid making folks guess in meetings :)

**Comment by m-ou-se** [comment]
:+1: from libs.

**Comment by jhpratt** [comment]
Awesome. Just doing a bit of digging then I'll create a tracking issue and update this PR with it.

**Comment by jhpratt** [comment]
PR should be good to go. Tracking issue was created and included in the relevant commit.

**Pull request merged**
