### PR TITLE
Expose mutex poisoning helpers

### PR DESCRIPTION
**Pull request by kmcallister**
I needed these to implement efficient poisoning in [seqloq](https://github.com/kmcallister/seqloq/tree/poison).

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think adding `PoisonError::new` is probably fine, but can this avoid exposing `map_lock_result` for now? That should be implement-able with `new` exposed, right?

cc @aturon, an interesting conventions dilemma of whether we should provide constructors for *all* errors or largely just some method to reconstruct "wrapper errors" after decomposing them.

**Comment by kmcallister** [comment]
> can this avoid exposing `map_lock_result` for now? That should be implement-able with `new` exposed, right?

Yeah, I could copy it out, but I don't want to ;)

**Comment by alexcrichton** [comment]
As an API we'll have to support to the end of time the threshold should be fairly high for inclusion. A bare `map_lock_result` doesn't really fit into any conventions that we have so far, so it should likely be left out until a later date if it is necessary to re-include.

**Comment by kmcallister** [comment]
> As an API we'll have to support to the end of time

It's marked as `#[unstable]`.  I thought we could add things like this as part of the "stability not stagnation".

**Comment by alexcrichton** [comment]
> It's marked as #[unstable]. I thought we could add things like this as part of the "stability not stagnation".

Although we have a distinction of `#[unstable]` APIs in the standard library it does not mean that it will become a "dumping ground" for everything submitted. The lifetime of a new API is:

1. An RFC is created for a new API and is discussed.
2. The RFC is accepted.
3. The RFC is implemented with `#[unstable]` APIs
4. Some time later, the APIs are removed or promoted to `#[stable]`

All currently `#[unstable]` APIs are either planned for removal or planned to be revisited at some point in the future to stabilize.

Along these lines, I do not think that this `map_lock_result` is an API that we would want to stabilize, so it should not be included at this time. The `PoisonError::new` API is a fine candidate for stabilization, however, as it follows a well accepted pattern of constructors and is a very minor (and probably expected) addition to the API.

**Comment by aturon** [comment]
(FWIW, I agree with @alexcrichton here.)

**Comment by kmcallister** [comment]
That sounds good, I'll update this PR soon.

**Comment by kmcallister** [comment]
Updated to keep `map_lock_result` private.

**Pull request merged**
