### PR TITLE
Optimize unchecked indexing into chunks and chunks_mut

### LINKED ISSUE #53340: Performance regression in tight loop since rust 1.25
I've finally gotten around to doing some proper benchmarking of rust versions for my crate:

http://chimper.org/rawloader-rustc-benchmarks/

As can be seen in the graph on that page there's a general performance improvement over time but there are some very negative outliers. Most (maybe all) of them seem to be very simple loops that decode packed formats. Since rust 1.25 those are seeing 30-40% degradations in performance. I've extracted a minimal test case that shows the issue:

```rust
fn decode_12le(buf: &[u8], width: usize, height: usize) -> Vec<u16> {
  let mut out: Vec<u16> = vec![0; width*height];

  for (row, line) in out.chunks_mut(width).enumerate() {
    let inb = &buf[(row*width*12/8)..];

    for (o, i) in line.chunks_mut(2).zip(inb.chunks(3)) {
      let g1: u16 = i[0] as u16;
      let g2: u16 = i[1] as u16;
      let g3: u16 = i[2] as u16;

      o[0] = ((g2 & 0x0f) << 8) | g1;
      o[1] = (g3 << 4) | (g2 >> 4);
    }
  }
  out
}

fn main() {
  let width = 5000;
  let height = 4000;

  let buffer: Vec<u8> = vec![0; width*height*12/8];
  
  for _ in 0..100 {
    decode_12le(&buffer, width, height);
  }
}
```

Here's a test run on my machine:

```sh
$ rustc +1.24.0 -C opt-level=3 bench_decode.rs 
$ time ./bench_decode 

real	0m4.817s
user	0m3.581s
sys	0m1.236s
$ rustc +1.25.0 -C opt-level=3 bench_decode.rs 
$ time ./bench_decode 

real	0m6.263s
user	0m5.067s
sys	0m1.196s
```

### PR DESCRIPTION
**Pull request by the8472**
Fixes #53340

```
# BEFORE

$ rustc +nightly -Copt-level=3 -Ccodegen-units=1 -Clto=fat chunks.rs
$ perf stat ./chunks

 Performance counter stats for './chunks':

          3,177.03 msec task-clock                #    1.000 CPUs utilized
                 4      context-switches          #    0.001 K/sec
                 0      cpu-migrations            #    0.000 K/sec
           984,006      page-faults               #    0.310 M/sec
    13,092,199,322      cycles                    #    4.121 GHz                      (83.29%)
       384,543,475      stalled-cycles-frontend   #    2.94% frontend cycles idle     (83.35%)
     7,414,280,722      stalled-cycles-backend    #   56.63% backend cycles idle      (83.38%)
    50,493,980,662      instructions              #    3.86  insn per cycle
                                                  #    0.15  stalled cycles per insn  (83.29%)
     6,625,375,297      branches                  # 2085.396 M/sec                    (83.38%)
         3,087,652      branch-misses             #    0.05% of all branches          (83.31%)

       3.178079469 seconds time elapsed

       2.327156000 seconds user
       0.762041000 seconds sys

# AFTER

$ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc -Copt-level=3 -Ccodegen-units=1 -Clto=fat chunks.rs
$ perf stat ./chunks

 Performance counter stats for './chunks':

          2,705.76 msec task-clock                #    1.000 CPUs utilized
                 4      context-switches          #    0.001 K/sec
                 0      cpu-migrations            #    0.000 K/sec
           984,005      page-faults               #    0.364 M/sec
    11,156,763,039      cycles                    #    4.123 GHz                      (83.26%)
       342,198,882      stalled-cycles-frontend   #    3.07% frontend cycles idle     (83.37%)
     6,486,263,637      stalled-cycles-backend    #   58.14% backend cycles idle      (83.37%)
    40,553,476,617      instructions              #    3.63  insn per cycle
                                                  #    0.16  stalled cycles per insn  (83.37%)
     6,668,429,113      branches                  # 2464.532 M/sec                    (83.37%)
         3,099,636      branch-misses             #    0.05% of all branches          (83.26%)

       2.706725288 seconds time elapsed

       1.782083000 seconds user
       0.848424000 seconds sys
```

### CODE REVIEW

**Comment by the8472** [comment]
Grepping through the compiler source doesn't show any uses of `chunks` or `chunks_mut`, even less so in combination with `Zip`, so I don't really expect a change in performance, but maybe some dependencies do.

@bors try @rust-timer queue

**Comment by klensy** [comment]
Comparing CI build nightly with manually build stage1 can show unrelated info.

**Comment by the8472** [comment]
I'd expect the compiler internals to be built differently, but shouldn't the *output* of the compiler remain comparable?

**Comment by pedrocr** [comment]
Awesome, thanks for working on this!

**Pull request merged**
