### PR TITLE
Make ExitStatus implement Default

### PR DESCRIPTION
**Pull request by ijackson**
And, necessarily, make it inhabited even on platforms without processes.

I noticed while preparing https://github.com/rust-lang/rfcs/pull/3362 that there was no way for anyone to construct an `ExitStatus`.

This would be insta-stable so needs an FCP.

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
Impl looks fine, but will need API review.

**Comment by thomcc** [comment]
This should probably have ACP, tbh

**Comment by ijackson** [comment]
> This should probably have ACP, tbh

Ah, sorry.  Now done in https://github.com/rust-lang/libs-team/issues/158

The rustbot comment says (emphasis added):
> If this PR contains changes to any **unstable** APIs please edit the PR description to add a link to the relevant API Change Proposal or create one if you haven't already.

Maybe that isn't quite right?  I'm not sure what it should say precisely (or where to edit it).

**Comment by m-ou-se** [comment]
@rfcbot merge

(See https://github.com/rust-lang/libs-team/issues/158 for motivation/details.)

**Comment by scottmcm** [comment]
I see that there's nothing in the PR that documents what the default *is*.

I think it should at least say somewhere what that default is.  Having it come from a `derive(Default)` on a `c_int` feels indirect to me as well, so perhaps it would make sense to define it manually in terms of `ExitCode::SUCCESS` instead, say -- that would also allow putting a doc-comment on the `impl`.

**Comment by scottmcm** [comment]
It also feels like it make make sense to make [`ExitCode`](https://doc.rust-lang.org/std/process/struct.ExitCode.html) *also* be `Default` at the same time, since it feels weird for the more-complicated type to be `Default` when the simple one isn't.

**Comment by ijackson** [comment]
@scottmcm I generally agree with your comments.

In https://github.com/rust-lang/libs-team/issues/158 @m-ou-se suggested `impl From<ExitCode> for ExitStatus`, which I also agree with.

In summary, I think we should
 * `impl Default for ExitCode` (simply `SUCCESS`)
 * `impl From<ExitCode> for ExitStatus` (with the obvious semantics, but might be worth some additional docs)
 * Document that `Default` for `ExitStatus` is "process reported successful termination", ie the result of `ExitCode::success().into()`, and, implement it that way.

I have put this on my personal todo list.  Items 1 and 2 are insta-stable.  Should I make an ACP, or can we do the FCP in the MR?  It seems to me that this is all relatively uncontroversial so maybe going straight to MR is best.

I don't think any of those are ABI breaks from where this MR gets us, so this MR can go through as-is, even though it has room for improvement.

**Comment by jyn514** [comment]
> Impl looks fine, but will need API review.

I think it makes sense to add the documentation @scottmcm suggested, but we can open a follow-up issue for that.

@bors r=thomcc rollup

**Comment by matthiaskrgr** [comment]
@bors r- 
https://github.com/rust-lang/rust/pull/110868#issuecomment-1524386529

**Comment by ijackson** [comment]
> @bors r- [#110868 (comment)](https://github.com/rust-lang/rust/pull/110868#issuecomment-1524386529)

Oh dear.  Sorry about that.  I will fix it.

**Comment by ijackson** [comment]
I've fixed the fuchsia impl, and manually checked the other impls.

Should I squash this?  Rebase onto current main?

**Comment by workingjubilee** [comment]
It's not going to be squashed on its own, so...

**Comment by ijackson** [comment]
I have squashed this.  I haven't rebased it onto a recent main.

**Comment by ijackson** [comment]
Oh.  I see I lost the review race there.  I will rewind and do the followup as its own MR.

**Comment by ijackson** [comment]
@workingjubilee I think my push and rewind have caused the bots to become confused.  @bors said "this is now in the queue" but clicking through to the queue it isn't showing as Approved.  Would you mind re-approving 1f1d49a ?  Sorry for the inconvenience.

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
