### PR TITLE
Move Various str tests in library

### PR DESCRIPTION
**Pull request by ayushmishra2005**
Moved various string ui  tests in library  as a part of #76268

r? @matklad

### CODE REVIEW

**Comment by jyn514** [comment]
This would belong better in `string.rs` I think, e.g. https://github.com/rust-lang/rust/blob/7d834c87d2ebb3d8dd4895bc5fabc4d44a1d2b52/library/alloc/tests/string.rs#L25

**Comment by jyn514** [comment]
Actually it looks like this is testing string literals themselves, not `.to_string()`? Then I'm not sure it should be moved ... I'll wait to hear what matklad say.s

**Comment by ayushmishra2005** [comment]
> Actually it looks like this is testing string literals themselves, not `.to_string()`? Then I'm not sure it should be moved ... I'll wait to hear what matklad says.

@jyn514 Shall I move in `string.rs` or wait for @matklad to provide any feedback?

**Comment by jyn514** [comment]
Wait for matklad's opinion I think, this was just a drive-by review :P

**Comment by ayushmishra2005** [comment]
> Wait for matklad's opinion I think, this was just a drive-by review :P

Hi @matklad Please provide your feedback for this PR.

**Comment by jyn514** [comment]
@bors r+ rollup

This looks fine, if there are issues they can be fixed later.

**Pull request merged**
