### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #114376 (Avoid exporting __rust_alloc_error_handler_should_panic more than once.)
 - #114413 (Warn when #[macro_export] is applied on decl macros)
 - #114497 (Revert #98333 "Re-enable atomic loads and stores for all RISC-V targets")
 - #114500 (Remove arm crypto target feature)
 - #114566 (Store the laziness of type aliases in their `DefKind`)
 - #114594 (Structurally normalize weak and inherent in new solver)
 - #114596 (Rename method in `opt-dist`)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=114376,114413,114497,114500,114566,114594,114596)

### CODE REVIEW

**Comment by lqd** [comment]
@rust-timer build 0e990905571547422756ed5b48ee8057572ea74c

**Comment by lqd** [comment]
If it’s not noise happening twice, it looks like https://github.com/rust-lang/rust/pull/114594 is involved @compiler-errors: it may have changed common code and not just the new solver?

**Comment by compiler-errors** [comment]
I don't think so -- the only change that affects the old solver is replacing some resolve_vars_with_obligations calls with try_structurally_resolve_type calls, but the latter just calls the former when the old solver is active.

**Comment by lqd** [comment]
@compiler-errors has opened https://github.com/rust-lang/rust/pull/114648 which will only apply https://github.com/rust-lang/rust/pull/114594 to the new solver 🙏 

Let's mark this PR triaged: @rustbot label: +perf-regression-triaged

**Pull request merged**
