### PR TITLE
Revert "Teach parser to understand fake anonymous enum syntax" and related commits

### LINKED ISSUE #107461: Closure with a typed function argument and top level struct constructor break in nightly
### Code

I tried this code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7f3bdb07bcc3a0a30d2ef80cf0adfd22

```rust
let closure = |f: fn(&f32) -> f32| MyStruct { x: f(&y) };
```

This code should compile.

Instead of compiling, the compiler generates the following error:

```rust
error: anonymous enums are not supported
 --> src/main.rs:8:38
  |
8 |     let closure = |f: fn(&f32) -> f32| MyStruct { x: f(&y) };
  |                                   ---^ --------
  |
  = help: create a named `enum` and use it here instead:
          enum Name {
              Variant1(f32),
              Variant2(MyStruct),
          }

error: expected one of `!`, `(`, `,`, `::`, `<`, or `|`, found `{`
 --> src/main.rs:8:49
  |
8 |     let closure = |f: fn(&f32) -> f32| MyStruct { x: f(&y) };
  |                                                 ^ expected one of `!`, `(`, `,`, `::`, `<`, or `|`

error: could not compile `playground` due to 2 previous errors
```

### Version it worked on

It most recently worked on: (1.67)

### Version with regression

Breaks in latest nightly 1.69.0-nightly (2023-01-29 e972bc8083d5228536df)

Related:
* #106960
* #100988
*  #100741

### PR DESCRIPTION
**Pull request by compiler-errors**
anonymous enum types are currently ambiguous in positions like:

* `|` operator: `a as fn() -> B | C`
* closure args: `|_: as fn() -> A | B`

I first tried to thread around `RecoverAnonEnum` into all these positions, but the resulting complexity in the compiler is IMO not worth it, or at least worth a bit more thinking time. In the mean time, let's revert this syntax for now, so we can go back to the drawing board.

Fixes #107461

cc: @estebank @cjgillot #106960

---
### Squashed revert commits:

Revert "review comment: Remove AST AnonTy"

This reverts commit 020cca8d36cb678e3ddc2ead41364be314d19e93.

Revert "Ensure macros are not affected"

This reverts commit 12d18e403139eeeeb339e8611b2bed4910864edb.

Revert "Emit fewer errors on patterns with possible type ascription"

This reverts commit c847a01a3b1f620c4fdb98c75805033e768975d1.

Revert "Teach parser to understand fake anonymous enum syntax"

This reverts commit 2d824206655bfb26cb5eed43490ee396542b153e.

### CODE REVIEW

**Comment by estebank** [comment]
@compiler-errors can you add tests for those ambiguous case, in case someone tries to do this again?

r=me

**Comment by compiler-errors** [comment]
I did in 859b14ce7d469bc1af3ee396fd8e91b7b2e20d6f :smile_cat:

@bors r=estebank

**Comment by estebank** [comment]
> I first tried to thread around RecoverAnonEnum into all these positions, but the resulting complexity in the compiler is IMO not worth it, or at least worth a bit more thinking time.

I think that instead we can rely on global Parser state to control when these kinds of anon enums can be detected. I have global state, but it is a natural communication mechanism for the parser :-/

**Comment by compiler-errors** [comment]
@estebank oh yes, let me re-teach the compiler those really quick. Sorry, I totally overlooked those because they weren't their own commit :sweat_smile:

**Comment by compiler-errors** [comment]
Added a few more test cases that shouldn't be broken when this PR is re-attempted.

@bors r=estebank

**Comment by compiler-errors** [comment]
This is bitrotty, but also P-critical :sweat: 

@bors p=1

**Pull request merged**
