### PR TITLE
[WIP] migrate more of src/test/run-pass to src/test/ui/run-pass

### PR DESCRIPTION
**Pull request by pnkfelix**
This may be enough to consider marking #53764 as closed

### CODE REVIEW

**Comment by petrochenkov** [comment]
@pnkfelix 
Could you address https://github.com/rust-lang/rust/issues/54047 before doing this migration?
Plus probably a way to disable the NLL half of UI tests as well.
It becomes increasingly harder to run tests locally.

**Comment by pnkfelix** [comment]
marking as WIP until T-compiler decides how we are going to resolve #54047

**Comment by pnkfelix** [comment]
Discussed at compiler team meeting.

Long term we will probably adopt some test layout that puts everything in a place that acts like `ui` suite.

But short term I am going to move stuff back to `run-pass` and turn it into another `ui` suite.

**Pull request closed without merging**
