### PR TITLE
Remove unused files from libcoretest

### PR DESCRIPTION
**Pull request by fhahn**
While working on #28711 I found out that 
-  src/libcoretest/clone.rs 
- src/libcoretest/fmt/float.rs  
- src/libcoretest/intrinsics.rs 

are not used. I am not sure if removing them is the right way to go. If it makes sense to keep (and fix and enable) them, I would be happy to update the PR.

### CODE REVIEW

**Comment by brson** [comment]
It looks to me like they should be added to coretest since these tests don't exist anywhere else. Can you add them back to the crate?

**Comment by fhahn** [comment]
Yeah that makes sense. I've updated the PR. I only changed `int` to `i32` and had to remove a [test](https://github.com/fhahn/rust/commit/6aa5237e279498a36d58da7e3589cc2570a2b3ce#diff-b06a5f6786606ca38b350a10e8e00001L28) which used `clone()` on functions (I am not sure, is something like this still supported?)

**Comment by alexcrichton** [comment]
@bors: r+ 6aa5237e279498a36d58da7e3589cc2570a2b3ce

Yay!

**Comment by fhahn** [comment]
It seems like to rounding behavior has changed: `format!("{:.1}" , 9.85f64)` prints 9.8 instead of the expected 9.9. Is this a regression? According to the [documentation](http://doc.rust-lang.org/nightly/std/primitive.f64.html#method.round) , `round()` should round half-way cases away from zero. `format!("{:.1}" , 9.851f64)` generates 9.9 as expected.

**Comment by alexcrichton** [comment]
I believe that's probably because 9.85 isn't representable as a float, for example:

```
$ cat foo.rs
fn main() {
    let a = 9.85;
    println!("{}", a);
}
$ rustc -g foo.rs
$ lldb ./foo
(lldb) target create "./foo"
bCurrent executable set to './foo' (x86_64).
(lldb) b foo.rs:3
Breakpoint 1: where = foo`foo::main + 107 at foo.rs:3, address = 0x000000010000156b
(lldb) r
Process 98510 launched: './foo' (x86_64)
Process 98510 stopped
* thread #1: tid = 0xdf51c, 0x000000010000156b foo`foo::main + 107 at foo.rs:3, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x000000010000156b foo`foo::main + 107 at foo.rs:3
   1   	fn main() {
   2   	    let a = 9.85;
-> 3   	    println!("{}", a);
   4   	}
(lldb) print a
(double) $0 = 9.8499999999999996
(lldb) 
```

**Comment by fhahn** [comment]
Ah I see. I have updated the test.

**Pull request merged**
