### PR TITLE
[beta] Revert "Promote missing_fragment_specifier to hard error #75516"

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This reverts "Promote missing_fragment_specifier to hard error #75516" on just beta. I would like us to explore a more principled fix, perhaps along the lines @petrochenkov suggested in #76605, on master when we have more time to test it but I don't want us shipping the breakage in the meantime. I don't personally feel comfortable immediately backporting anything more than a revert here.

cc @matklad 

This matches #77456 for 1.47 but targets 1.48 (current beta) instead.

r? @petrochenkov

### CODE REVIEW

**Comment by matklad** [comment]
:+1: from me on reverting

**Comment by petrochenkov** [comment]
Looks like some UI tests need an update?

**Pull request merged**
