### PR TITLE
s/eval_usize/eval_target_usize/ for clarity

### PR DESCRIPTION
**Pull request by oli-obk**
r? @nnethercote 

as discussed in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.60Const.60.20and.20.60usize.60.2F.60u64.60 it is unclear what `usize` means and why we use a `u64` for something talking about `usize`. This renaming should make it clear that we're talking about `usize`s on the target platform, irrespective of the compiler host platform.

### CODE REVIEW

**Comment by RalfJung** [comment]
In the interpreter we use `machine_usize` for this. Might be better to be consistent? Probably would be best to rename machine → target then, "machine" doesn't make a ton of sense outside the interpreter.

**Comment by oli-obk** [comment]
Yea, the `Machine` naming was never very well motivated. I can pull up a PR for that, but it should land separately from this one, as each one of those changes will be very bitrotty

**Comment by RalfJung** [comment]
Fair.
@bors r+ rollup

**Comment by saethlin** [comment]
It's always been unclear to me if the "machine" there was the `usize` of the Machine itself, or the target the Machine is simulating. Agree that `target` is better.

**Pull request merged**
