### PR TITLE
Add `--print host-tuple` to print host target tuple

### PR DESCRIPTION
**Pull request by Noratrieb**
People often parse `-vV` output to get to the host tuple, which is annoying to do. It's easier to just get it directly.

I called it "host-tuple" instead of "host" because it's clearer that it's just the target name. I'm open to different names, but I think this one is fine.

a quick GitHub search for `'^host` reveals many instances of people doing the parsing, for example:

https://github.com/japaric/xargo/blob/68e0ca57cd90837fe02f262f074182f9cfeb6227/README.md?plain=1#L369
https://github.com/taiki-e/setup-cross-toolchain-action/blob/0e38473b0c562d6db19a98d3ec20a80f7ac189ae/main.sh#L96
https://github.com/taiki-e/cargo-llvm-cov/blob/8a3553b86551eabf9c30c060b1f72a5bbccb98c6/README.md?plain=1#L625
https://github.com/SiliconLabs/cpc-nvm3/blob/43f3ec39709b30700ef7f39d91fa647974323bf1/do.sh#L35

needs a compiler FCP. I could also do an MCP but I think just an FCP here makes the most sense.

### CODE REVIEW

**Comment by workingjubilee** [comment]
I would prefer `host-tuple`, so we don't have to stress about ontologies if the tuple happens to have 2 or 5.

**Comment by bjorn3** [comment]
> a quick GitHub search for '^host reveals many instances of people doing the parsing, for example:

Cargo also does this.

**Comment by oli-obk** [comment]
@rfcbot merge

**Comment by lcnr** [comment]
@rfcbot concern triple vs tuple

https://github.com/rust-lang/rust/pull/125579#issuecomment-2132386452

**Comment by michaelwoerister** [comment]
As a data point, our existing documentation seem to call it "triple" pretty consistently:
https://doc.rust-lang.org/rustc/?search=triple
https://doc.rust-lang.org/cargo/index.html?search=triple
https://doc.rust-lang.org/reference/?search=triple

**Comment by apiraino** [comment]
So, should that be "tuple" or "triple"?

(trying to understand is the concern raised is still standing)

**Comment by lcnr** [comment]
I personally don't have a strong opinion here and would be open to rescind my concern

- tuple is more accurate as some targets don't use exactly 3 words
- triple is currently the used terminology, though it seems to only be internal

https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html?highlight=tuple#loongarch-unknown-linux- already uses tuple

@michaelwoerister @workingjubilee does one of you care strongly about either option? It is fairly arbitrary in the end (and it's documentation should probably mention the alternative).

One simple way to resolve this might just be a vote on zulip and we pick whatever ends up on top as long as nobody feels very strongly about this: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.60--print.20host.5B-tuple.7C-triple.5D.60

**Comment by michaelwoerister** [comment]
I voted "don't care" on Zulip.

**Comment by oli-obk** [comment]
r? compiler

**Comment by davidtwco** [comment]
I don't think there's necessarily a strong consensus from the Zulip poll on terminology here, the team seems to have a slight preference towards `host-tuple`, do you want to change it to that @Noratrieb?

**Comment by Noratrieb** [comment]
@davidtwco I do! I changed it to `host-tuple` and also updated a bunch (but by far not all) places in the compiler where "triple" is used today.

**Comment by lcnr** [comment]
@rfcbot resolve triple vs tuple

**Comment by Noratrieb** [comment]
I almost forgot to add documentation, I updated the `--print` docs in the rustc book with the new value.

**Review by davidtwco — APPROVED** [review]
r=me after rebase

**Comment by zackw** [comment]
I hope this isn't baking in further confusion about what "build", "host", and "target" mean when talking about compilation.  These terms have longstanding definitions outside of Rust:

The *build* system is the system where you are compiling something.
The *host* system is the system that the thing you're compiling right now will run on.
The *target* system is the system that the thing you're compiling right now _will generate code for._  It is only meaningful when the thing you are compiling right now is itself a compiler.

In a native compilation, build and host are the same, but if the thing you're compiling is a cross-compiler, target might be different.  In a cross-compilation, the cross-compiler's _host_ is the _build_ system for the thing being compiled, and the cross-compiler's _target_ is the _host_ system for the thing being compiled.

`--print host-tuple`, therefore, should print the system tuple for the machine _where rustc runs_, and `--print target-tuple` should print the system tuple for the machine _that rustc is currently configured to generate code for_.  It is not clear to me whether the PR does this.

**Comment by Noratrieb** [comment]
yes this is the host, as the name implies

**Comment by Noratrieb** [comment]
rebased
@bors r=davidtwco

**Comment by workingjubilee** [comment]
rebased at Nora's request

**Comment by Noratrieb** [comment]
mrow thanks
@bors r=davidtwco p=1

**Comment by Noratrieb** [comment]
fixed a trivial semantic conflict where a stray test file was around
@bors r=davidtwco

**Pull request merged**
