### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by mati865**
There are few nice fixes waiting already.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me, but looks like the lockfile needs an update?

**Comment by mati865** [comment]
I see, I'll update it soon when I get access to my machine.

**Comment by ishitatsuyuki** [comment]
It seems that you did an `cargo update`, which updates all dependencies available. That can cause some weird regressions and is more likely to cause a merge conflict.

Instead, please do `cd src && cargo clean`, which is the way that allows Cargo to update the lockfile **conservatively**. (`clean` is a little bit silly here, but it's a hack as there's no "just conservatively update" subcommand implemented)

**Comment by mati865** [comment]
Thank you for the reviews.
Addressed comments and Travis is green, waiting for r.

**Comment by mati865** [comment]
Rebased.
Guess (and expect) I cannot do it but let's try:

@bors r=alexcrichton

**Pull request merged**
