### PR TITLE
Add missing normalization when checking const generics

### LINKED ISSUE #114217: lazy_type_alias: type `is forbidden as the type of a const generic parameter`
I tried this code:
`tests/rustdoc/issue-101743-bold-tag.rs`
```rust
// Regression test for https://github.com/rust-lang/rust/issues/101743

#![crate_name="foo"]

pub type Word = usize;
pub struct Repr<const B: usize>([i32; B]);
pub struct IBig(usize);

pub const fn base_as_ibig<const B: Word>() -> IBig {
    IBig(B)
}

impl<const B: Word> Repr<B> {
    // If we change back to rendering the value of consts, check this doesn't add
    // a <b> tag, but escapes correctly

    // @has foo/struct.Repr.html '//section[@id="associatedconstant.BASE"]/h4' '= _'
    pub const BASE: IBig = base_as_ibig::<B>();
}

```

without  `-Zcrate-attr=feature(lazy_type_alias)´: no warnings

with `-Zcrate-attr=feature(lazy_type_alias)`:

```
error: `Word` is forbidden as the type of a const generic parameter
 --> tests/rustdoc/issue-101743-bold-tag.rs:9:36
  |
9 | pub const fn base_as_ibig<const B: Word>() -> IBig {
  |                                    ^^^^
  |
  = note: the only supported types are integers, `bool` and `char`
  = help: more complex types are supported with `#![feature(adt_const_params)]`

error: `Word` is forbidden as the type of a const generic parameter
  --> tests/rustdoc/issue-101743-bold-tag.rs:13:15
   |
13 | impl<const B: Word> Repr<B> {
   |               ^^^^
   |
   = note: the only supported types are integers, `bool` and `char`
   = help: more complex types are supported with `#![feature(adt_const_params)]`

error: aborting due to 2 previous errors
```

````
rustc 1.73.0-nightly (04abc370b 2023-07-28)
binary: rustc
commit-hash: 04abc370b9f3855b28172b65a7f7d5a433f41412
commit-date: 2023-07-28
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
````

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/114217.
Part of https://github.com/rust-lang/rust/issues/112792.

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
I'm not actually totally convinced this is something we want to support. We don't normalize other aliases --

```
trait Mirror { type Mirror; }
impl<T> Mirror for T { type Mirror = T; }

fn test<const N: <i32 as Mirror>::Mirror>() {}
//~^ `<i32 as Mirror>::Mirror` is forbidden as the type of a const generic parameter
```

**Comment by compiler-errors** [comment]
Even if we were to normalize things here, we should not be using `normalize_erasing_regions` at all this early in the compiler. We need to use a wf-checking context to normalize things properly.

**Comment by GuillaumeGomez** [comment]
> I'm not actually totally convinced this is something we want to support. We don't normalize other aliases --
> 
> ```
> trait Mirror { type Mirror; }
> impl<T> Mirror for T { type Mirror = T; }
> 
> fn test<const N: <i32 as Mirror>::Mirror>() {}
> //~^ `<i32 as Mirror>::Mirror` is forbidden as the type of a const generic parameter
> ```

Are projections the same as aliases?

Also, sorry, just realized that some context is missing (only present in the issue). Without the feature enabled, the code compiles just fine, meaning that aliases are supposed to work for const generics. But maybe I should only normalize if this is a weak ty alias? As you prefer.

As for using projections in const generics, it was something that was kinda agreed upon in https://github.com/rust-lang/rust/pull/104443 but it wasn't merged because it was introducing new bugs (hence why I'm suggesting to only normalize if this is a weak ty alias).

> Even if we were to normalize things here, we should not be using `normalize_erasing_regions` at all this early in the compiler. We need to use a wf-checking context to normalize things properly.

Sounds good to me!

So what do you want me to do here? Should I update the PR to use the correct normalization, should I only normalize if it's a weak ty alias or this is not something that the compiler wants at all and then we can close this PR?

**Comment by compiler-errors** [comment]
> Are projections the same as aliases?

Both "lazy type aliases" ("weak") and projections are forms of [alias](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_type_ir/sty/enum.TyKind.html#variant.Alias), so I expect them to act consistently.

> Without the feature enabled, the code compiles just fine, meaning that aliases are supposed to work for const generics. 

The point of the `lazy_type_alias` feature is to change the semantics of type aliases. Just because something builds [without the flag](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a6cd41bbe264d36105b1560dbe2110f0) doesn't mean it will build [with the flag](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1059a021663c671b4fd1f8a0437e860f).

> As for using projections in const generics, it was something that was kinda agreed upon in https://github.com/rust-lang/rust/pull/104443 but it wasn't merged because it was introducing new bugs (hence why I'm suggesting to only normalize if this is a weak ty alias).

I think we should then probably bring this question back up formally rather than just fix it ad-hoc like this. The more that these features diverge, the more we're gonna have to clean up and reconcile later, imo.

Also, doesn't this lead to the same exact bugs as #104443? Either that, or this PR is incomplete?

**Comment by GuillaumeGomez** [comment]
> Both "lazy type [alias](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_type_ir/sty/enum.TyKind.html#variant.Alias)es" ("weak") and projections are forms of alias, so I expect them to act consistently.

Thanks for the clarification!

> The point of the lazy_type_alias feature is to change the semantics of type aliases. Just because something builds [without the flag](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a6cd41bbe264d36105b1560dbe2110f0) doesn't mean it will build [with the flag](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1059a021663c671b4fd1f8a0437e860f).

Makes sense! Just a bit weird. :smile_cat: 

> I think we should then probably bring this question back up formally rather than just fix it ad-hoc like this. The more that these features diverge, the more we're gonna have to clean up and reconcile later, imo.
> 
> Also, doesn't this lead to the same exact bugs as #104443? Either that, or this PR is incomplete?

It's not doing the same change (maybe because the code changed a lot since then?) as it doesn't fail the test, so I suppose it's unrelated to supporting projections in const generics. Just an early check I guess.

Anyway, I'll update the code and if the compiler team doesn't want it, I'll close this PR and instead open a new one with the failing code so it's not forgotten.

**Comment by GuillaumeGomez** [comment]
When changing:

```diff
-            let param_env = tcx.param_env(param.def_id);
-            let ty = tcx.normalize_erasing_regions(param_env, ty);
+            enter_wf_checking_ctxt(tcx, hir_ty.span, param.def_id, |wfcx| {
+                let ty = wfcx.normalize(hir_ty.span, Some(WellFormedLoc::Ty(param.def_id)), ty);
```

`tests/ui/const-generics/projection-as-arg-const.rs` panics:

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: Const::from_anon_const: couldn't lit_to_const TypeError
  --> /home/imperio/rust/rust/tests/ui/const-generics/projection-as-arg-const.rs:19:11
   |
LL |     foo::<12>();
   |           ^^
   |
note: delayed at compiler/rustc_middle/src/ty/consts.rs:213:30
         0: <rustc_errors::HandlerInner>::emit_diagnostic
         1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         2: <rustc_middle::ty::consts::Const>::from_anon_const
         3: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_value_path::CreateCtorSubstsContext as rustc_hir_analysis::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind
         4: rustc_hir_analysis::astconv::generics::create_args_for_parent_generic_args::<<rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_value_path::CreateCtorSubstsContext>
         5: <rustc_hir_typeck::fn_ctxt::FnCtxt>::instantiate_value_path
         6: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_path
         7: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
         8: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_call
         9: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_kind
        10: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
        11: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_stmt
        12: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_block_with_expected
        13: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
        14: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_expr
        15: rustc_hir_typeck::check::check_fn
        16: rustc_hir_typeck::typeck
        17: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        18: <rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
        19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        20: rustc_query_impl::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
        21: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_hir_analysis::check_crate::{closure#7}>::{closure#0}>::{closure#0}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
        22: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_hir_analysis::check_crate::{closure#7}>::{closure#0}>
        23: rustc_hir_analysis::check_crate
        24: rustc_interface::passes::analysis
        25: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        26: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
        27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        28: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        29: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#6}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        30: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
        31: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
        32: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        33: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        34: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        35: std::sys::unix::thread::Thread::new::thread_start
        36: start_thread
                   at ./nptl/pthread_create.c:442:8
        37: clone3
                   at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  --> /home/imperio/rust/rust/tests/ui/const-generics/projection-as-arg-const.rs:19:11
   |
LL |     foo::<12>();
   |           ^^

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
```

So I suppose either this fix is incomplete or it's simply wrong to change it. I updated the code, but I guess it'll just be closed for now.

**Pull request closed without merging**
