### PR TITLE
Add inline attributes to syntax_pos

### PR DESCRIPTION
**Pull request by Zoxc**
The existing `impl PartialOrd<InternedString> for InternedString` causes an error in some of my branches for some reason...

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could the `#[inline(always)]` be switched to `#[inline]`? Other than that r=me

**Comment by kennytm** [comment]
OK let me change it back to `S-waiting-on-author` then 🙂

**Comment by Zoxc** [comment]
I've removed the changes to `InternedString` since the error was caused by a dependency on the `rayon` crate. I'll fix it in https://github.com/rust-lang/rust/pull/50235.

This just leaves the `#[inline]` attributes for the PR. I've looked over syntax_pos added some more of them.

**Pull request closed without merging**
