### PR TITLE
update Miri

### LINKED ISSUE #82173: `miri` no longer builds after rust-lang/rust#82153
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#82153, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @jonas-schievink, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
This pulls in the recent cargo-miri fixes by @hyd-dev.
Cc @rust-lang/miri r? @ghost
Fixes https://github.com/rust-lang/rust/issues/82173

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r-
Something broke Miri

**Comment by RalfJung** [comment]
Miri should be good again.
@bors r+ p=1

**Comment by RalfJung** [comment]
@rust-lang/infra something seems to be wrong with toolstate tracking? https://rust-lang-nursery.github.io/rust-toolstate/ did not update when this PR got merged, and now Miri fails to build and there was no notification or issue being created.

**Comment by hyd-dev** [comment]
> @rust-lang/infra something seems to be wrong with toolstate tracking? https://rust-lang-nursery.github.io/rust-toolstate/ did not update when this PR got merged, and now Miri fails to build and there was no notification or issue being created.

That seems a Python 2 → Python 3 issue: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Toolstate.20update.20was.20broken.20for.20Miri

**Comment by RalfJung** [comment]
Okay, I created an issue to track this: https://github.com/rust-lang/rust/issues/82254

**Pull request merged**
