### PR TITLE
Cross compiling rustc_llvm on Darwin requires zlib.

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**

### CODE REVIEW

**Comment by the8472** [comment]
> Merge branch 'rust-lang:master' into llvm_cross

We require PR branches to not contain merge commits. It should be rebased instead.

https://rustc-dev-guide.rust-lang.org/contributing.html#opening-a-pr

**Comment by MarcusCalhoun-Lopez** [comment]
Sorry, Git is still somewhat of a mystery to me.
Is this correct now?

**Comment by the8472** [comment]
Yes, the commit history is fine now.

**Comment by JohnCSimon** [comment]
Triage: Is this still waiting on review?

**Pull request merged**
