### PR TITLE
BTreeMap: comment why drain_filter's size_hint is somewhat pessimistic

### PR DESCRIPTION
**Pull request by ssomers**
The `size_hint` of the `DrainFilter` iterator doesn't adjust as you iterate. This hardly seems important to me, but there has been a comparable PR #64383 in the past. I guess a scenario is that you first iterate half the map manually and keep most of the key/value pairs in the map, and then tell the predicate to drain most of the key/value pairs and `.collect` the iterator over the remaining half of the map.

I am totally ambivalent whether this is better or not.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I am a bit confused -- we're updating the length live, so why do we need a new remaining field?

My guess is that there's something subtle going on here that would be good to document on the remaining field (as well as clarify here).

If we do need the additional field I think we shouldn't do this, it's not worth the extra field and more complicated logic.

**Comment by ssomers** [comment]
The length includes the part of the map that the predicate saw and decided not to drain. It overestimates how many elements are yet to be returned by the iterator.

I agree this is rather futile. If the predicate keeps very many elements, then the size hint is always overestimated. If the predicate drains very many elements, then you're better of with `into_iter` and collecting a new map. #64383 didn't require any new data to improve the estimate, but here we need some number in addition to the length - the number drained, the number kept, or the number remaining.

**Comment by Mark-Simulacrum** [comment]
I think it's probably fine for us to include that extra in the size hint -- it's a hint, and I'd prefer to avoid the complication introduced by the logic here (I am surprised tracking the information we need requires so many changes).

I am leaning towards saying that we shouldn't do this.

**Comment by ssomers** [comment]
> (I am surprised tracking the information we need requires so many changes).

Well it doesn't _require_ changes in navigate.rs, but it allows getting rid of some Err values and saving a total of 5 lines there. But without really reducing complexity.

I'll write a comment in the size_hint function instead.

**Pull request merged**
