### PR TITLE
rustbuild: Update the OpenSSL version to link

### PR DESCRIPTION
**Pull request by alexcrichton**
This updates the OpenSSL tarball download to reflect OpenSSL's newest release.

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @sfackler

**Comment by kennytm** [comment]
cc @SimonSapin just in case (https://internals.rust-lang.org/t/updates-on-rusts-ci-uploads/6062/6).

**Comment by SimonSapin** [comment]
Some old commits of Servo download https://s3.amazonaws.com/rust-lang-ci/rust-ci-mirror/openssl-1.0.2k.tar.gz when building for android. @kennytm, is that file being removed?

Either way, I switched Servo a couple weeks ago to download from a copy at `s3.amazonaws.com/servo-deps` instead.

**Comment by kennytm** [comment]
@SimonSapin IIRC the whole `rust-lang-ci` bucket is going away. The equivalent file on the `rust-lang-ci2` should stay longer (personally I don't see reason to delete it, it's just 5.1 MB), but no guarantee can be given.

**Pull request merged**
