### PR TITLE
Bages for easy access links to Rust community

### PR DESCRIPTION
**Pull request by 0xf333**
Easy access links to Rust community on Twitter, Discord, YouTube and Rust community page

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I don't have a super strong opinion, but I think that these don't really belong in the readme directly. We should be linking to these resources from https://www.rust-lang.org/community, I think, which has the right context and sets users on a path to discovering more of the places they can reach out with questions to.

I'm not opposed to linking the community page from the readme though.

**Comment by 0xf333** [comment]
> I don't have a super strong opinion, but I think that these don't really belong in the readme directly. We should be linking to these resources from https://www.rust-lang.org/community, I think, which has the right context and sets users on a path to discovering more of the places they can reach out with questions to.
> 
> I'm not opposed to linking the community page from the readme though.

Thanks for the guidance, I will make the change now to reflect you suggestion. 
You obviously have more experience than me, so I think I should just listen and do it :smile:

**Comment by 0xf333** [comment]
@Mark-Simulacrum 
Adjustment done, now it will only display the badge for the link you suggested.

**Comment by Mark-Simulacrum** [comment]
Please squash commits into one, and then happy to merge.

**Comment by Mark-Simulacrum** [comment]
https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing has some guidance on how to rebase to squash commits if you want it.

**Comment by 0xf333** [comment]
> Please squash commits into one, and then happy to merge.

I'm traveling right now, I didn't bring my laptop with me.
I will do it first thing first as soon as I'm back to the city.

Thanks for the reply.

**Comment by 0xf333** [comment]
@ Mark-Simulacrum 
I/m noticing that the fact that I changed username made things messy!
I will close this PR and open a new to keep this clean and concise moving forward.

**Pull request closed without merging**
