### PR TITLE
keep the AST node-id when lowering ExprKind::Range

### LINKED ISSUE #40749: Nightly compiler error regression for struct array field
The following code produces a compiler error (as expected) on stable, but the compiler crashes on nightly.

```rust
pub struct ChunkIterator {
    buf: [u8; 10],
}

impl ChunkIterator {
    pub fn new() {
        ChunkIterator {
            buf: [0; ..10],
        }
    }
}
```

On stable:

```
error[E0308]: mismatched types
 --> <anon>:8:22
  |
8 |             buf: [0; ..10],
  |                      ----
  |                      |
  |                      expected usize, found struct `std::ops::RangeTo`
  |                      in this macro invocation
  |
  = note: expected type `usize`
             found type `std::ops::RangeTo<{integer}>`
```

On nightly:

```
error: internal compiler error: /checkout/src/librustc/hir/map/mod.rs:379: local_def_id: no entry for `22`, which has a map of `Some(EntryExpr(NodeId(20), expr(22: ::std::ops::RangeTo{end: 10,})))`
```

### PR DESCRIPTION
**Pull request by arielb1**
When the Range expression is the root of a constant, its node-id is
used for the def-id of the body, so it has to be preserved in the AST ->
HIR lowering.

Fixes #40749.

r? @eddyb 
beta-nominating because regression

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Marking as beta-accepted. Small patch, regression.

cc @rust-lang/compiler

**Comment by arielb1** [comment]
- #40821
@bors retry

**Comment by arielb1** [comment]
-  #40821
    @bors retry

**Comment by alexcrichton** [comment]
@arielb1 unfortunately this doesn't apply cleanly to the beta branch, would you mind looking into the backport?

**Pull request merged**
