### PR TITLE
rustdoc: Remove `clean::TraitWithExtraInfo` and queryify `is_notable_trait`

### PR DESCRIPTION
**Pull request by camelid**
cc @notriddle @GuillaumeGomez

### CODE REVIEW

**Comment by camelid** [comment]
This reduces the regressions for stm32f4 by a factor of 10 and eliminates the regressions for the other crates.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
It's super cool, thanks! (and welcome back!)

@bors r+ rollup=iffy

**Comment by nnethercote** [comment]
The `keccak` improvements are probably noise. Otherwise this looks to be perf-neutral or perhaps a very slight improvement.

@rustbot label: +perf-regression-triaged

**Pull request merged**
