### PR TITLE
Fix link generation for local primitive types in rustdoc JSON output

### LINKED ISSUE #104064: [Rustdoc JSON] Primitive types in `core` are missing from the index
## The issue

The id for `i32` in the JSON documentation generated for `core` is `0:79316:78663`. 
It appears in the `path`:

```json
"0:79316:78663": {
  "crate_id":0,
  "path":["core","i32"],
  "kind":"primitive"
}
```

but it is not present in the `index`, although it's referenced in the `links` section for many other items.   
The same happens to the other primitives I checked - e.g. `i64` (`0:79317:78665`) or `char` (`0:79294:78252`).

## How to reproduce

Add the `rust-docs-json` component to your `nightly` toolchain, using 

```bash
rustup component add rust-docs-json --toolchain nightly
```

You can then inspect `core.json` in `.rustup/toolchains/nightly-<platform-triplet>/share/doc/rust/json/core.json`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/104064.

As mentioned in the issue, I'm not super happy about this fix which is more a hack rather than a sound-proof solution. However I couldn't find a better way to fix it.

r? @aDotInTheVoid

### CODE REVIEW

**Comment by aDotInTheVoid** [comment]
Given that primitives are handled with the `DisplayDefId` machinery, we're not using `ItemId::Primitive` here. What does is it used for?

This PR should also remove the code path for `ItemId::Primitive` to clairify that its not used.

https://github.com/rust-lang/rust/blob/c7572670a1302f5c7e245d069200e22da9df0316/src/librustdoc/json/conversions.rs#L232-L241



```diff
-      ItemId::Primitive(ty, krate) => Id(format!("p:{}:{}", krate.as_u32(), ty.as_sym())), 
+      ItemId::Primitive(_, _) => unreachable!(),
```

I've tested this localy, but github won't let me suggest changes for lines "to far" from the changed lines.

@rustbot author

**Comment by GuillaumeGomez** [comment]
`ItemId::Primitive` exists for the generation of the search index. But at this point, I think we could maybe remove it. To be investigated.

**Comment by GuillaumeGomez** [comment]
I removed the match pattern for the primitive type.

**Comment by aDotInTheVoid** [comment]
r=me when CI passes.

**Pull request merged**
