### PR TITLE
Simplify the arguments to macros generated by the `rustc_queries` proc macro

### PR DESCRIPTION
**Pull request by jyn514**
Very small cleanup. Based on https://github.com/rust-lang/rust/pull/100436 which modifies some of the same code.

r? @cjgillot

### CODE REVIEW

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/100436 hasn't yet been merged.

@bors r-

**Comment by klensy** [comment]
This not rebased over #100436, so first 4 comments doubled.

**Pull request merged**
