### PR TITLE
Add `/System/iOSSupport` to the library search path on Mac Catalyst

### PR DESCRIPTION
**Pull request by madsmtm**
On macOS, `/System/iOSSupport` contains iOS frameworks like UIKit, which is the whole idea of Mac Catalyst.

To link to these, we need to explicitly tell the linker about the support library stubs provided in the macOS SDK under the same path.

Concretely, when building a binary for Mac Catalyst, Xcode passes the following flags to the linker:
```
-iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/iOSSupport/System/Library/Frameworks
-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/iOSSupport/usr/lib
```

This is not something that can be disabled (it's enabled as soon as you enable `SUPPORTS_MACCATALYST`), so I think it's pretty safe to say that we don't need an option to turn these off.

I've chosen to slightly deviate from what Xcode does and use `-F` instead of `-iframework`, since we don't need to change the header search path, and this way the flags nicely match on all the linkers. From what I could tell by reading Clang sources, there shouldn't be a difference when just running the linker.

CC @BlackHoleFox, @shepmaster (I accidentally let rustbot choose the reviewer).

### CODE REVIEW

**Comment by BlackHoleFox** [comment]
I'm not opposed to this but it also seems less useful then the mirror for `cc-rs`. Users already need to define what framework you want the `extern C` block to link to. Is it to make that unneeded? Or is it just to match XCode better even if nothing in rustc or std actually needs this linkage?

**Comment by madsmtm** [comment]
> Users already need to define what framework you want the `extern "C"` block to link to. Is it to make that unneeded? Or is it just to match XCode better even if nothing in rustc or std actually needs this linkage?

No, `#[link(name = "UIKit", kind = "framework")] extern "C" {}` would still be needed. The issue is that that doesn't work unless this option is present, i.e. the test I added in the second commit fails to link on Mac Catalyst targets.

(Even worse is when you link frameworks that are present on both platforms, like `WebKit`, since that ends up linking the macOS version of `WebKit` and not the iOS version).

I guess the user (or a library like `objc2`) _could_ fix this by using `cargo:rustc-link-arg=...` in a build script, but that seems like a worse option than solving it in `rustc` itself.

**Review by BlackHoleFox — APPROVED** [review]

**Comment by madsmtm** [comment]
r? shepmaster

**Comment by madsmtm** [comment]
Unsure who has enough macOS/Xcode experience that I can assign this to.

r? compiler

**Comment by Nadrieril** [comment]
Same

r? compiler

**Review by thomcc — APPROVED** [review]
I can confirm this makes sense to do for the catalyst targets.

**Comment by wesleywiser** [comment]
Since @thomcc said this makes sense, I'm just going to 

@bors r+

**Comment by petrochenkov** [comment]
@madsmtm 
Clang supports Mac Catalyst targets, I assume, but I don't see the `iOSSupport` anywhere in its source code.
So it expects them to be passed from some higher build system layer (that's what "Xcode passes the following flags" I assume).
Why should `rustc` do differently and pass them by itself?

I'm currently auditing include directories passed to linkers and this is the only case in which rustc passes "system" directories, in other cases it will leaves this work either to user or to cc/linker.

Also, is it correct that these directories go after user-passed directories, but before other "system" directories implicitly passed by cc/linker? Seems generally reasonable.

**Comment by bjorn3** [comment]
In the case of rust, most people expect that they can just run `cargo build --target aarch64-apple-ios-macabi` on a mac. When plain cargo is used, the only other location where the search path information could be encoded is cargo. Where possible target specific information is intentionally kept out of cargo and put in rustc instead. Cargo doesn't even know the file extension for executables, staticlibs and dylibs. It queries rustc for this information instead.

**Pull request merged**
