### PR TITLE
Add a regression test for mutating a non-mut #[thread_local]

### LINKED ISSUE #54901: Write to #[thread_local] is not respected
```rust
#![feature(thread_local)]

#[thread_local]
static S: &str = "before";

fn set_s() {
    S = "after";
}

fn main() {
    println!("{}", S);
    set_s();
    println!("{}", S);
}
```

On rustc 1.31.0-nightly (b2d6ea98b 2018-10-07) and x86_64-unknown-linux-gnu, we see the following surprising behavior:

```console
$ cargo run  # as expected
before
after

$ cargo run --release
before
before
```

In release mode it seems the write has not happened in the place that it should.

Mentioning thread_local tracking issue: [rust-lang/rust#29594](https://github.com/rust-lang/rust/issues/29594).

### PR DESCRIPTION
**Pull request by mjbshaw**
This should close #54901 since the regression has since been fixed.

### CODE REVIEW

**Comment by nagisa** [comment]
Two things before this can land:

1. This should be an `ui` test instead;
2. I believe it is valid, and even preferred, to not have the license header anymore.

**Comment by mjbshaw** [comment]
Thanks, @nagisa. I have fixed and amended the commit.

**Comment by mjbshaw** [comment]
I'm a bit confused by the diff here. Locally, (using `rustc 1.33.0-nightly (60e825389 2018-12-28)`, which includes the parent of merge 7a79e03), rustc gives the output:

```
error[E0594]: cannot assign to immutable thread-local static item
  --> t.rs:11:5
   |
11 |     S = "after"; //~ ERROR cannot assign to immutable thread-local static item
   |     ^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0594`.
```

This is slightly different that what the test is emitting on Travis. I don't know why Travis is getting a different output.

**Comment by mjbshaw** [comment]
You're right, @kennytm, thanks! I didn't realize the test suite uses `--edition=2018` by default now. I've amended the commit.

**Comment by stokhos** [comment]
Ping from triage, @mjbshaw have you had time to work this PR?

**Comment by mjbshaw** [comment]
@stokhos Sorry about the delay. I've been trying to figure out Rust's test system (`./x.py test` used to work, but something changed recently and now it just spits out a bajillion tidy errors; then I switched to `./x.py test src/test/ui`, which seemed to work, but when I added `--test-args thread-local-mutation.rs` it rebuilt the whole compiler for some reason, and building takes forever on my old laptop) and how to get this test to work.

There's a slight difference in output that NLL introduces, and I haven't been able to find any documentation that says how to get these kinds of tests to work (it passed locally but Travis was failing). I just barely updated the PR with a wild guess and put the NLL output in a *.nll.stderr file, but I have no idea what I'm doing and whether or not this is correct.

**Comment by nikomatsakis** [comment]
@mjbshaw sorry to hear you were confused! We definitely need to improve the docs on the testing system. Seems like you got it setup right; in the future, the `--bless` switch may be useful. Alternatively, please feel free to hop on [Zulip](https://rust-lang.zulipchat.com/) with any questions or just ping the reviewer (me, I guess =)

**Pull request merged**
