### PR TITLE
Add AMX target-features and `x86_amx_intrinsics` feature flag

### PR DESCRIPTION
**Pull request by sayantn**
This is an effort towards #126622. This adds support for all 5 target-features for `AMX`, and introduces the feature flag `x86_amx_intrinsics`, which would gate these target-features and the yet-to-be-implemented amx intrinsics in stdarch.

### CODE REVIEW

**Comment by fmease** [comment]
Overloaded with reviews
r? compiler

**Comment by workingjubilee** [comment]
Please rebase.

**Comment by sayantn** [comment]
r? wg-llvm

**Comment by workingjubilee** [comment]
Hi, @sayantn I rebased your PR, hope that's okay!

@bors r=Amanieu

**Comment by workingjubilee** [comment]
And forgot to touch my ssh key!

**Comment by workingjubilee** [comment]
For realsies now
@bors r=Amanieu

**Comment by sayantn** [comment]
Thank you @workingjubilee

**Comment by sayantn** [comment]
@workingjubilee The feature gate is marked as `CURRENT_RUSTC_VERSION` in `compiler/rustc_feature/unstable.rs`. Do we need to change it before merge?

**Comment by cuviper** [comment]
No, that's an intentional placeholder that will be replaced during branch promotion.

**Pull request merged**
