### PR TITLE
Update clang to 12.0.0 on Windows and macOS

### PR DESCRIPTION
**Pull request by joshtriplett**
Needed for https://github.com/rust-lang/rust/pull/84764 . Tarballs
already uploaded to the CI mirror bucket.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We should try to make sure that the build still *works* without this on Windows/macOS, though, as expecting really recent toolchains isn't great. My understanding is that we should only need this on aarch64 Windows, perhaps, so in that sense it shouldn't be too necessary for most people?

**Comment by joshtriplett** [comment]
This is needed when building an aarch64 target on a Windows host. It's only a requirement on Windows; other platforms can continue to use older compilers. It seems more reasonable to expect an up-to-date toolchain on Windows, since it would normally be installed directly rather than obtained from a distribution. And if people specifically need to build with an older compiler, they could potentially disable aarch64 target support.

**Pull request merged**
