### PR TITLE
Remove unnecessary Arc usage in introduction

### PR DESCRIPTION
**Pull request by aochagavia**
cc @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hmm, the point is to introduce comboing Arc and Mutex together. The examples have gotten a bit out of sync from each other, I think, but I'm not sure this is the right way to address this. Thoughts?

**Comment by aochagavia** [comment]
I also think it is nice to introduce `Arc`. However, I think it is difficult to find a trivial example where it makes sense to use it (probably with detached threads).

**Comment by steveklabnik** [comment]
I'm planning on doing more overhauls to this section, but let's just merge this for now, and we'llsee how it ends up.

**Pull request merged**
