### PR TITLE
Add enum_intrinsics_non_enums lint

### LINKED ISSUE #83899: Uplift clippy::mem_discriminant_non_enum into rustc
The [clippy::mem_discriminant_non_enum](https://rust-lang.github.io/rust-clippy/master/index.html#mem_discriminant_non_enum) lint seems like it should be directly in rustc. The lint prevents doing something like:
```Rust
core::mem::discriminant::<i32>(&4)
```
which causes unspecified behavior.

### PR DESCRIPTION
**Pull request by Flying-Toast**
There is a clippy lint to prevent calling [`mem::discriminant`](https://doc.rust-lang.org/std/mem/fn.discriminant.html) with a non-enum type. I think the lint is worthy of being included in rustc, given that `discriminant::<T>()` where `T` is a non-enum has an unspecified return value, and there are no valid use cases where you'd actually want this.

I've also made the lint check [variant_count](https://doc.rust-lang.org/core/mem/fn.variant_count.html) (#73662).

closes #83899

### CODE REVIEW

**Comment by Flying-Toast** [comment]
CI failed because compiler/rustc_lint/src/builtin.rs is too long. Should I add `// ignore-tidy-filelength`, or try to split stuff out into another file?

**Comment by Flying-Toast** [comment]
While I'm at it, I made the lint also check [variant_count](https://doc.rust-lang.org/core/mem/fn.variant_count.html)

**Comment by flip1995** [comment]
@Flying-Toast  When this lint is uplifted, the Clippy lint should be deprecated properly. Since this is a lengthy procedure and explaining it takes longer than doing it myself, please ping me once the ``rustc`` changes are ready and I can add the patch to deprecate the Clippy lint.

**Comment by Flying-Toast** [comment]
> @Flying-Toast When this lint is uplifted, the Clippy lint should be deprecated properly. Since this is a lengthy procedure and explaining it takes longer than doing it myself, please ping me once the `rustc` changes are ready and I can add the patch to deprecate the Clippy lint.

@flip1995 Thanks. This PR is ready now

**Comment by flip1995** [comment]
Thanks! I'm waiting for a Rust review and confirmation that this lint should be uplifted. After that, I'll provide the necessary Clippy changes.

**Comment by Dylan-DPC** [comment]
@estebank any update?

**Comment by Flying-Toast** [comment]
@estebank when do you think you can review this?

**Review by davidtwco — APPROVED** [review]
LGTM, r=me after rebase, apologies this took so long to be reviewed.

**Comment by flip1995** [comment]
@Flying-Toast please apply [the patch in this gist](https://gist.github.com/flip1995/25896b75a86b8ad868e93be3f2f77389) for the PR to pass the Clippy test suite.

**Comment by davidtwco** [comment]
@Flying-Toast GitHub is still reporting your branch as having conflicts, have you been able to rebase?

**Comment by JohnCSimon** [comment]
Ping again from triage:
@Flying-Toast GitHub is still reporting your branch as having conflicts, have you been able to rebase?

**Comment by Flying-Toast** [comment]
@JohnCSimon @davidtwco I've rebased the PR, sorry for the delay - I've been busy with school. @flip1995: The patch doesn't apply very well anymore by now - could you make the patch again?

**Comment by camelid** [comment]
@Flying-Toast rust-lang/rust follows a ["No-Merge Policy"](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy). Could you please [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) over upstream changes instead of merging? Thanks!

**Comment by Flying-Toast** [comment]
@flip1995 thanks :) I've pushed from your branch.

**Review by davidtwco — APPROVED** [review]
LGTM!

**Pull request merged**
