### PR TITLE
Remove `rustc_deprecated` diagnostics

### PR DESCRIPTION
**Pull request by jhpratt**
Follow-up on #95960. The diagnostics will remain until the next bootstrap, at which point people will have had six weeks to adjust.

@rustbot label +A-diagnostics

r? @compiler-errors

### CODE REVIEW

**Comment by compiler-errors** [comment]
>  The diagnostics will remain until the next bootstrap, at which point people will have had six weeks to adjust.

You mean that the diagnostic will remain for those working internally in the compiler (and bootstrapping with beta), right? Cause if anyone's using this externally (which, presumably, they shouldn't), it's deprecated next nightly with this PR.

Just getting an idea of the implications of this PR. It LGTM otherwise.

**Comment by jhpratt** [comment]
Yes, I meant for people working on the compiler. Anyone external…well that's what you get for using an internal attribute.

**Comment by compiler-errors** [comment]
Cool, thank you for clarifying. Anyways, just for the record, stage2 builds would also break with this PR landed I think?

But yeah, it's an internal attribute.

@bors r+

**Comment by jhpratt** [comment]
I think? I'm not super familiar with the different stages.

**Comment by compiler-errors** [comment]
Stage 2 builds the compiler and stdlib with the stage 1 artifacts, so if we have any stray `rustc_deprecated` in the codebase, then they would break immediately with these changes landed. Regardless, bors will not merge this if stage 2 is broken, so this isn't risky to land IMO.

**Comment by jhpratt** [comment]
Any `#[rustc_deprecated]` would have already been an error before this change, just with a diagnostic. So there's definitely not any stray (I checked again regardless).

**Comment by compiler-errors** [comment]
Ah, I didn't see it was an error, I thought it was just a warning before. Thanks for double-checking anyways!

**Pull request merged**
