### PR TITLE
Set cfg(test) when rustdoc is running with --test option

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Following a [discussion on twitter](https://twitter.com/burntsushi5/status/1117091914199785473), I proposed this change. What do you think about it?

r? @QuietMisdreavus 

cc @BurntSushi

### CODE REVIEW

**Comment by BurntSushi** [comment]
I'm not sure what the rustdoc team procedures are here, but you might want to consider this as a normal public API addition. That is, if you accept this change and it makes it to stable Rust, then _removing_ this would be a breaking change AIUI. For example, one thing I think this would allow you to do is to write doc tests using code that is gated behind a `cfg(test)`.

**Comment by ehuss** [comment]
There is some discussion about this in #45599.

**Comment by QuietMisdreavus** [comment]
I'm against this change. Doctests are analogous to examples, not unit tests - they're standalone binaries that link against the parent code as a separate crate.

**Comment by QuietMisdreavus** [comment]
(Sorry about closing this, i misclicked the button when typing my initial comment. 😓)

This looks like it's not the same as https://github.com/rust-lang/rust/issues/45599 - this is about setting `cfg(test)` when *collecting* doctests, not when *compiling* them. This is probably fine, since there's been a slight pattern of having non-public doctests to test when something should not compile, or (in the case of the linked twitter thread) to check the doctests of the README without directly including it in the crate's docs. I originally learned about this when trying to block doctests on private items (https://github.com/rust-lang/rust/pull/54438). It looks like this is a way to properly support that.

**Comment by ehuss** [comment]
Ah, sorry for misinterpreting.

**Comment by GuillaumeGomez** [comment]
So is it ok to merge it?

**Review by QuietMisdreavus — APPROVED** [review]
This seems fine to me, though i'm a little worried that there will be some subtle ramifications that we haven't thought about. I'd like someone from @rust-lang/docs or @rust-lang/rustdoc to see whether i'm overthinking this, but in the meantime there doesn't seem to be much harm from landing it into nightly for now - we have plenty of time to revert it if things go awry.

**Comment by ollie27** [comment]
I'm a bit worried that doctests on items marked `#[cfg(not(test))]` will no longer be run but I don't know how common that would be in the wild.

Also can we add a `rustdoc-ui` test like the following to test this behavior:

```rust
// compile-pass
// compile-flags:--test
// normalize-stdout-test: "src/test/rustdoc-ui" -> "$$DIR"

/// this doctest will be ignored:
///
/// ```
/// assert!(false);
/// ```
#[cfg(not(test))]
pub struct Foo;

/// this doctest will be tested:
///
/// ```
/// assert!(true);
/// ```
#[cfg(test)]
pub struct Foo;
```

**Comment by GuillaumeGomez** [comment]
@ollie27: Hum good point, they won't be tested indeed. I don't see it as an issue since there are workarounds though. I'll add the test shortly.

@bors: r-

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by Centril** [comment]
@bors retry

yielding to r0llup

**Comment by ollie27** [comment]
I should have checked before merging this but there are doctests in this repository that are behind `#[cfg(not(test))]` which we haven't been testing since this was merged. For example the entire of `core`:

https://github.com/rust-lang/rust/blob/f492693982d1e252f5411ae3e4d560ab0dfea48a/src/libcore/lib.rs#L50-L51

I've submitted a revert: #61199

**Pull request merged**
