### PR TITLE
docs: Add missing backtick in object_safety.rs docs

### LINKED ISSUE #56019: Missing trailing backtick in compiler docs
https://github.com/rust-lang/rust/blob/f6e9485bfc245eb5f10b1f2b0a786538d12d1cb0/src/librustc/traits/object_safety.rs#L473

```rust
/// for `self: Pin<Box<Self>>, this means `Pin<Box<Self>>: DispatchFromDyn<Pin<Box<U>>>`
                             ^ here
```

This causes most of the `TyCtxt` docs to be underlined:

screenshot_2018-11-17 rustc ty tyctxt - rust

### PR DESCRIPTION
**Pull request by Xanewok**
Closes #56019.

r? @bjorn3

### CODE REVIEW

**Review by bjorn3 — APPROVED** [review]
I'm not a member of rust-lang, so you should probably r? someone else.

Note to rust-highfive maintainers: please make rust-highfive ignore r? with non rust-lang members.

**Comment by Xanewok** [comment]
Right, sorry about that.

Since it's docs, let's try...
r? @QuietMisdreavus

**Review by QuietMisdreavus — APPROVED** [review]
Looks good to me! r=me when travis is green.

**Pull request merged**
