### PR TITLE
Update Python and Clang on x86 dist images

### PR DESCRIPTION
**Pull request by nikic**
LLVM 12 no longer builds with Python 2, so install Python 3 in
preparation for the upgrade (#81451).

However, Clang 10 does not build with Python 3, so we need update
to Clang 11 as well, which supports both.

Unfortunately, doing so results in errors while linking the
libLLVM.so into other binaries:
> __morestack: invalid needed version 2

This is fixed by using LLD instead. Possibly this is due to a binutils
linker bug, but updating to the latest binutils version does not fix
it.

r? @Mark-Simulacrum 
cc @cuviper

### CODE REVIEW

**Comment by cuviper** [comment]
FWIW, there was also a case of the `__morestack` issue with clang and LLVM 11 here:
https://zulip-archive.rust-lang.org/131828tcompiler/25509morestackerrorwhenbuildinglibrustcdriver.html

**Comment by nikic** [comment]
I've switched the `LLVM_ENABLE_LLD` use when `llvm.thin-lto=true` is set to use `LLVM_USE_LINKER=lld` instead, as otherwise one can't use `llvm.thin-lto=true` and `llvm.use-linker=lld` at the same time.

Missed this previously as I did not delete `obj/` between rebuilds.

**Comment by RalfJung** [comment]
Looks like this PR broke the produced toolchains: https://github.com/rust-lang/rust/pull/81489

**Pull request merged**
