### PR TITLE
macros: clean up scopes of expanded `#[macro_use]` imports

### PR DESCRIPTION
**Pull request by jseyfried**
This PR changes the scope of macro-expanded `#[macro_use]` imports to match that of unexpanded `#[macro_use]` imports. For example, this would be allowed:

``` rust
example!();
macro_rules! m { () => { #[macro_use(example)] extern crate example_crate; } }
m!();
```

This PR also enforces the full shadowing restrictions from RFC 1560 on `#[macro_use]` imports (currently, we only enforce the weakened restrictions from #36767).

This is a [breaking-change], but I believe it is highly unlikely to cause breakage in practice.
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
*@eddyb

**Comment by eddyb** [comment]
Starting crater run now.

**Comment by nrc** [comment]
Thanks @eddyb!

**Comment by nrc** [comment]
ah crap

@bors: r-

**Comment by nrc** [comment]
r=me if the Crater run comes back clean

**Comment by eddyb** [comment]
The [crater report](https://gist.github.com/eddyb/4c83021638ddf0d7a21e505ea7a83194) only has crater download failures and such (cc @brson).

@bors r=nrc

**Pull request merged**
