### PR TITLE
adding openbsd snapshot

### PR DESCRIPTION
**Pull request by dhuseby**
@alexcrichton please upload this snapshot when landing:

https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2015-08-11-1af31d4-openbsd-x86_64-9cae790c4ca19b1b29a048605ce249fe1c20a498.tar.bz2

BTW, this is the snapshot that @semarie has published on his website for use in the OpenBSD port for rust.  Credit goes to him.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 2425b9ddcebf69ce37d325157241e8f9cef1716e

Thanks @dhuseby and @semarie!

**Comment by dhuseby** [comment]
@semarie I have started setting up an OpenBSD buildbot.  You can see it's status here:
http://buildbot.rust-lang.org/buildslaves/openbsd-64-opt
I was looking at your port and it appears that the configure scripts need some plumbing work done around egcc vs gcc so that it detects gcc 4.9 instead of the default gcc 4.2.  If you've got suggestions/patches, that would be awesome.  Otherwise, I can figure it out.

My ultimate plan is to have the buildbot building snapshots for both rust and cargo since I can successfully bootstrap cargo on pretty much any platform rust compiles on.

**Comment by semarie** [comment]
@dhuseby thanks for you work !

For building rust from git under openbsd, you could see the README at http://semarie.free.fr/rust/. (The openbsd ports have implicit PATH that change one thing or two for using gcc-4.9).

The current "limitation" is really the need to use gcc from ports (4.9). All the teaks are for that (even the jemalloc `force_tls="0"` that is detected differently with base gcc or ports gcc, if I recall well).

gcc-4.9 is need: at configure, at build, at target linking.

I don't known what would be the better method: it could be configured in the buildbot with specific environment variable I think.

I have also a local patch for generating openbsd snapshot, in order to include system-libraries needed for stage0. I will see to make a PR for it.

**Comment by semarie** [comment]
oh and I omit a file edition for linking with `libestdc++` instead of `libstdc++` (`src/etc/mklldeps.py`) . This one fill be more complex to deal with it, I think.

**Pull request merged**
