### PR TITLE
`rustc_expand` cleanups

### PR DESCRIPTION
**Pull request by nnethercote**
Some cleanups I made while looking through this code. Nothing that requires any real domain-specific knowledge about this crate.

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Looks good to me, thanks for the PR, @nnethercote!

@bors r+ rollup

**Comment by nnethercote** [comment]
I rebased.

@bors r=compiler-errors

**Comment by michaelwoerister** [comment]
> r=compiler-errors

Wrong Michael 😉

@bors r=michaelwoerister

**Comment by nnethercote** [comment]
> Wrong Michael 😉

Whoops, sorry!

**Pull request merged**
