### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #39983, #40434, #41352, #41362, #41370, #41442, #41463, #41500, #41518
- Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
macOS-check (x86_64) Stuck in `git clone` are errored out https://travis-ci.org/rust-lang/rust/jobs/225443793 ¯\\\_(ツ)\_/¯

**Comment by alexcrichton** [comment]
@bors: retry

* llvm clone timeout https://github.com/rust-lang/rust/issues/40474

**Comment by eddyb** [comment]
Even though it supposedly started 3 hours ago, Travis says "Running for 1 hr 48 min" for some builders, and "Running for 18 min" for others, this looks bad cc @rust-lang/tools

**Comment by kennytm** [comment]
@eddyb 

Although the build was created 4 hours ago (~05:00 UTC), no jobs started until 3 hours ago. According to the raw log in https://travis-ci.org/rust-lang/rust/jobs/225486381, the oldest job started at 06:44 UTC, and finished at 09:04 UTC. (Time now is 09:30 UTC). That is, the build waited almost 2 hours on Travis.

Travis has a [database connectivity issue](https://www.traviscistatus.com/) from 03:41 UTC to 04:45 UTC, so probably the response is slower when Travis is clearing the backlog esp. the macOS ones.

**Pull request closed without merging**
