### PR TITLE
Update the reference submodule and fix tidy

### PR DESCRIPTION
**Pull request by petrochenkov**
cc https://github.com/rust-lang-nursery/reference/pull/36

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
https://travis-ci.org/rust-lang/rust/jobs/219191882#L9976-L9977

**Comment by petrochenkov** [comment]
There are broken links in the reference and the link checker fails.
If the reference submodule in this repo cannot be updated in arbitrary moment, it means it's not tested properly.

**Comment by steveklabnik** [comment]
> If the reference submodule in this repo cannot be updated in arbitrary moment, it means it's not tested/gated properly on PR merge.

It's not possible to do so without pulling in the entirety of the rust distribution.

You'll have to send a PR to the reference first to update it.

**Comment by petrochenkov** [comment]
It's faster to override local git config.

**Pull request closed without merging**
