### PR TITLE
Move global analyses from lowering to resolution

### PR DESCRIPTION
**Pull request by cjgillot**
Split off https://github.com/rust-lang/rust/pull/87234

r? @petrochenkov

### CODE REVIEW

**Comment by pnkfelix** [comment]
This was identified as yielding a moderate improvement in [instruction counts](https://perf.rust-lang.org/compare.html?start=c5799b2a73bd03d1d7b4a432fa0a0cb93e7288db&end=577a76f0031f727735410b99a5cc5f0b61b92eef&stat=instructions:u) (up to -1.6% on `incr-unchanged` builds of `keccak`) during weekly performance triage. Thanks and good job! :tada:

**Comment by Mark-Simulacrum** [comment]
Small regressions are limited to stress tests -- marking as triaged, the benefits here outweigh the relatively small regressions.

**Pull request merged**
