### PR TITLE
Improve `-Zmeta-stats` some more

### PR DESCRIPTION
**Pull request by nnethercote**
A follow-up to #97384.

r? @bjorn3

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at a time. The first commit is stolen from #101014, and we should probably let that PR merge before this one.

**Review by bjorn3 — APPROVED** [review]

**Comment by bjorn3** [comment]
r=me once https://github.com/rust-lang/rust/pull/101014 lands.

**Comment by nnethercote** [comment]
I forgot to show the before:
```
1268465 metadata bytes, of which 0 bytes (0.0%) are zero
             preamble:       30 bytes ( 0.0%)
                  dep:      923 bytes ( 0.1%)
          lib feature:        0 bytes ( 0.0%)
stability_implications:        0 bytes ( 0.0%)
            lang item:        0 bytes ( 0.0%)
      diagnostic item:        0 bytes ( 0.0%)
           native lib:        0 bytes ( 0.0%)
      foreign modules:        0 bytes ( 0.0%)
       def-path table:    33048 bytes ( 2.6%)
               traits:        8 bytes ( 0.0%)
                impls:     2538 bytes ( 0.2%)
     incoherent_impls:        0 bytes ( 0.0%)
                  mir:    18105 bytes ( 1.4%)
                 item:   442248 bytes (34.9%)
interpret_alloc_index:        0 bytes ( 0.0%)
      proc-macro-data:        0 bytes ( 0.0%)
               tables:   557422 bytes (43.9%)
 debugger visualizers:        0 bytes ( 0.0%)
     exported symbols:        0 bytes ( 0.0%)
              hygiene:    27103 bytes ( 2.1%)
      def-path hashes:   172083 bytes (13.6%)
           source_map:    14621 bytes ( 1.2%)
                final:      336 bytes ( 0.0%)
```
and after
```
meta-stats METADATA STATS
meta-stats Section                      Size
meta-stats ----------------------------------------------------------------
meta-stats lib-features                    0 ( 0.0%)
meta-stats stability_implications          0 ( 0.0%)
meta-stats lang-items                      0 ( 0.0%)
meta-stats diagnostic-items                0 ( 0.0%)
meta-stats native-libs                     0 ( 0.0%)
meta-stats foreign-modules                 0 ( 0.0%)
meta-stats incoherent-impls                0 ( 0.0%)
meta-stats interpret-alloc-index           0 ( 0.0%)
meta-stats proc-macro-data                 0 ( 0.0%)
meta-stats debugger-visualizers            0 ( 0.0%)
meta-stats exported-symbols                0 ( 0.0%)
meta-stats traits                          8 ( 0.0%)
meta-stats preamble                       30 ( 0.0%)
meta-stats final                         335 ( 0.0%)
meta-stats dep                           923 ( 0.1%)
meta-stats impls                       2_538 ( 0.2%)
meta-stats source-map                 14_623 ( 1.2%)
meta-stats mir                        18_105 ( 1.4%)
meta-stats hygiene                    27_103 ( 2.1%)
meta-stats def-path-table             33_048 ( 2.6%)
meta-stats def-path-hash-map         172_083 (13.6%)
meta-stats items                     442_248 (34.9%)
meta-stats tables                    557_422 (43.9%)
meta-stats ----------------------------------------------------------------
meta-stats Total                   1_268_466 (of which 47.4% are zero bytes)
meta-stats
```

**Comment by nnethercote** [comment]
#101014 has been merged.

@bors r=bjorn3

**Pull request merged**
