### PR TITLE
Add some regression tests

### LINKED ISSUE #29988: FFI calls may create out-of-bounds loads
Given this Rust code:

``` rust
#[repr(C)]
struct S {
    f1: i32,
    f2: i32,
    f3: i32,
}

extern {
    fn foo(s: S);
}
```

A call to `foo()` generates IR like this on x86_64 Linux:

``` llvm
  %S = type { i32, i32, i32 }
; ...
  %arg = alloca %S
; ...
  %2 = bitcast %S* %s to i8*
  %3 = bitcast %S* %arg to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %3, i8* %2, i64 12, i32 4, i1 false)
  %4 = bitcast %S* %arg to { i64, i64 }*
  %5 = load { i64, i64 }, { i64, i64 }* %4
  call void @x({ i64, i64 } %5)
```

So we have a 12 byte alloca from which we then read 16 bytes.

### LINKED ISSUE #34979: Mismatched types error with mixed lifetimes in trait bounds
This was encountered from a [derive plugin that created where bounds for all member types](https://github.com/serde-rs/serde/issues/443#event-731862636). Occurs on stable, beta, and nightly.

``` rust
struct S<'a>(&'a ());

trait Tr { }
impl<T> Tr for Option<T> { }
impl<'a> Tr for S<'a> where Option<&'a str>: Tr, Option<&'static str>: Tr { }
```

```
error: mismatched types [--explain E0308]
 --> <anon>:5:1
  |>
5 |> impl<'a> Tr for S<'a> where Option<&'a str>: Tr, Option<&'static str>: Tr { }
  |> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
note: expected type `Tr`
note:    found type `Tr`
note: the lifetime 'a as defined on the impl at 5:0...
 --> <anon>:5:1
  |>
5 |> impl<'a> Tr for S<'a> where Option<&'a str>: Tr, Option<&'static str>: Tr { }
  |> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...does not necessarily outlive the static lifetime

error: aborting due to previous error
```

[playpen repro](https://is.gd/UgB9SI)

### PR DESCRIPTION
**Pull request by JohnTitor**
Closes #29988
Closes #34979
Pick up two snippets that have been fixed from #67945 (shouldn't be closed yet!)

### CODE REVIEW

**Comment by RalfJung** [comment]
I think this [failed on Windows](https://github.com/rust-lang-ci/rust/runs/653076898) in https://github.com/rust-lang/rust/pull/71978.

**Comment by JohnTitor** [comment]
Indeed! @bors r-

**Comment by JohnTitor** [comment]
d717e55f should avoid failures.
@bors r=Dylan-DPC

**Pull request merged**
