### PR TITLE
Stabilize std::path::Path::ancestors

### LINKED ISSUE #48581: Tracking issue for std::path::Path::ancestors
Tracking issue for #48420, `std::path::Path::ancestors` and `std::path::Ancestors`.

**Steps:**

- [X] Implementation
- [X] Stabilization PR (#50894)

**Unresolved questions:**

- [X] What is a good name? `ancestors`? `parents`?

### PR DESCRIPTION
**Pull request by teiesti**
Closes #48581

r? @BurntSushi

### CODE REVIEW

**Comment by alexcrichton** [comment]
@rfcbot fcp merge


Thanks for the PR @teiesti! This all looks good to me, let's see what the libs team thinks

**Comment by teiesti** [comment]
If someone wonders why I modified this PR: I've fixed a typo in the title!

**Comment by Mark-Simulacrum** [comment]
Did the decision around calling this ancestors vs. parents get settled? `parents` seems more appropriate to me since it's more readily searchable/recognizable with relation to the existing `parent` method.

**Comment by teiesti** [comment]
There has been a long lasting debate around the naming issue in the initial PR (#48420). The discussion was then postponed to the tracking issue/stabilization in order to get this feature working on nightly. There has indeed never been a deliberate decision but the discussion immediately ebbed away after the feature was merged.

When writing the stabilization PR, I consciously decided not to bring up this issue again in order to see if there's still need for further debate. @Mark-Simulacrum: Thank You for mentioning this, because this shows me that we should indeed talk about this again!

Here is a list of arguments already raised:

Pro `ancestors`:
1. [Cargo has a similar method called `ancestors`.](https://github.com/rust-lang/rust/pull/48420#issuecomment-368561578)
2. [It might be weird that an iterator called `Ancestor` yields the current path. It is more reasonable that the current path is a "null ancestor" than a "null parent".](https://github.com/rust-lang/rust/pull/48420#issuecomment-368969323)
3. [The name `parents` might be misleading.](https://github.com/rust-lang/rust/pull/48420#issuecomment-368990922)
4. Changing the name would break existing code in nightly.

Pro `parents`:
1. [When sorted, `parents` comes right after `parent`. It is therefore grouped with its more specific counterpart within the documentation.](https://github.com/rust-lang/rust/pull/48420#issue-170659575) (*This argument is ruled out by the fact that the standard library is not sorted by name but by the order in which functions appear in the source code. It is therefore possible to put `ancestors` right after `parents`.*)
2. [`parents` is more easily searchable/recognizable, given you are familiar with `parent`.](https://github.com/rust-lang/rust/pull/50894#issuecomment-394109061)

There have been arguments against both, `ancestors` and `parents`, but nobody came up with an idea that was clearly superior. Therefore, I suggest that we limit the decision to the choice between these two.

I, personally, have a slight tendency towards `ancestors` but in the end I don't really care about the name as long as it is one of the two. I do care about a fast stabilization because the functionality is highly useful for me.

In order to have both, fast stabilization and a good decision about the name, I propose to announce some kind of a final comment period about the name. This would give anyone the chance to raise new arguments. After that, @rust-lang/libs could decide.

**Comment by Mark-Simulacrum** [comment]
Just wanted to check that it was brought up before stabilization, but looks like there has been debate about the topic already -- I'm fine with ancestors per the arguments you linked to.

**Comment by dtolnay** [comment]
I have only read @teiesti's recap of the arguments and not the original tracking issue, but I prefer `ancestors` over `parents` for a reason that hasn't been listed so far. An iterator called `parents` implies to me that a path can have multiple parents. In reality a path has at most one parent. There is no transitive property where a parent of my parent would be considered my parent. In contrast, it seems easy to accept that an ancestor of my ancestor would be considered my ancestor, and thus `ancestors` would be an iterator over the chain of ancestors.

**Comment by teiesti** [comment]
I've rebased this branch. Can we try again?

**Comment by dtolnay** [comment]
Thank you @teiesti.

@bors r+

**Pull request merged**
