### PR TITLE
syntax: Remove warning for unnecessary path disambiguators

### PR DESCRIPTION
**Pull request by petrochenkov**
`rustfmt` is now stable and it removes unnecessary turbofishes, so removing the warning as discussed in https://github.com/rust-lang/rust/pull/43540 (where it was introduced).
One hardcoded warning less.

Closes https://github.com/rust-lang/rust/issues/58055

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

There used to be a hard-coded warning for unnecessary `::` in a path (e.g., `Vec::<u32>` as a type). As @petrochenkov notes, this is no longer needed, since rustfmt will silently normalize this. In general, I favor using rustfmt over warnings to try and push minor stylistic nits -- far less annoying. But in this particular case, it would also be good, because this warning appears so early we can't easily use the standard lint system, so it cannot be "allowed" or "denied" etc. Therefore, I am in favor of merging this PR and removing the warning.

**Comment by Centril** [comment]
I feel that this style is distinctly unidiomatic and would therefore fit well into `nonstandard_style`; however, if that is exceedingly difficult to do well in the compiler (e.g. it would slow things down or incur very ugly hacks) I could be swayed to not lint anymore. Feels like a good topic to discuss on Thursday.

**Comment by nikomatsakis** [comment]
@petrochenkov question -- can we set a flag in the resulting AST to indicate that an unnecessary `::` was present, in which case we could make a "true lint", right?

**Comment by nikomatsakis** [comment]
I'm still happy for rustfmt to silently normalize, but @cramertj feels like there is value in having a "teachable moment" here -- but it'd be nice if it were rustfix'able or something like that.

**Comment by petrochenkov** [comment]
>can we set a flag in the resulting AST to indicate that an unnecessary :: was present

Ugh, we can but that would at least increase the size of every path segment in AST.

The hardcoded warning can be converted into a lint without extending AST, but it will be attached to the crate root and only could be `allow`ed/`deny`ed at crate granularity.

**Comment by nikomatsakis** [comment]
> The hardcoded warning can be converted into a lint without extending AST, but it will be attached to the crate root and only could be allowed/denyed at crate granularity.

Sure, but that seems pretty surprising. I guess it could be considered a long-standing bug.

Presumably we could do something where we record the span, too, and try to reproduce the node-id from that.

**Comment by nikomatsakis** [comment]
To be clear, I don't know that it's worth the effort.

**Comment by nikomatsakis** [comment]
Particularly not if we adopt the "remove turbofish" RFC, in which case... nobody would likely think to add `::` in the first place.

**Comment by Dylan-DPC** [comment]
ping from triage @petrochenkov you have a conflict to resolve

**Comment by petrochenkov** [comment]
Rebased.

**Comment by Dylan-DPC** [comment]
ping from triage @petrochenkov more conflicts :D (maybe ask for a r+ before more conflicts arise)

**Comment by petrochenkov** [comment]
@Dylan-DPC 
The `S-waiting-on-review` label is already asking for r+.
(Also, conflicts don't usually prevent reviewing, that's why rfcbot doesn't reset the label to `S-waiting-on-author` when they happen, so the triage team probably shouldn't do it either.)

**Comment by Dylan-DPC** [comment]
@petrochenkov true though, but i have seen some reviewers wait for conflicts to be resolved before reviewing (especially if the conflict relates to the change being made).

Yeah i know the label is for that, but sometimes reviewers oversee that and won't check a PR until they are pinged or there is a discussion somewhere.

**Comment by Centril** [comment]
Reassigning to myself to lessen Niko's review load; r? @Centril 

@bors r+

**Pull request merged**
