### PR TITLE
Update crossbeam-channel to avoid UB

### PR DESCRIPTION
**Pull request by mati865**
More info: https://github.com/RustSec/advisory-db/pull/425

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]

**Comment by jyn514** [comment]
The 0.4.3 update happened in https://github.com/rust-lang/rust/commit/342d9567491ee044aac99870536cb5df75d6aec2, which is now on 1.47 stable.

**Comment by lcnr** [comment]
Why are you updating `Cargo.lock` instead of `Cargo.toml`?

**Comment by mati865** [comment]
@lcnr it's pulled by RLS.

Stable nomination seems like an overkill because `corssbeam_channel::bounded` seems to only be used by RLS. For beta it'd be nice to ship official binaries without UB.

**Comment by Mark-Simulacrum** [comment]
I am a bit worried that without a Cargo.toml update forcing this we'll end up accidentally going back to the old state; can you submit a PR to RLS updating it's toml as well?

@bors r+ though

**Comment by mati865** [comment]
Sure, I'll do that soon.

**Comment by Dylan-DPC** [comment]
prioritising it to avoid catching conflicts 

@bors p=1

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/30725weeklymeeting2020101554818.html#213432088) in T-compiler meeting.

@rustbot modify labels: beta-accepted

**Pull request merged**
