### PR TITLE
Make `MaybeUninit::assume_init()` a `const fn`

### PR DESCRIPTION
**Pull request by slightlyoutofphase**
It can be, because it simply calls an intrinsic and then another function which is already a `const fn` (`ManuallyDrop::into_inner` specifically.)

Example use case for this:

https://github.com/slightlyoutofphase/staticvec/blob/addf203c0ec11905c403d25faacfdd29f9191a28/src/lib.rs#L50

If `assume_init` were `const fn`, then the linked `new` function could be also.

### CODE REVIEW

**Comment by slightlyoutofphase** [comment]
Alright, I don't get it. Am I seeing some kind of weird attribute bug here? 

`#![feature(const_fn)]` is of course *already* set in `lib.rs` for `libcore`, as it pretty obviously has to be.

**Comment by slightlyoutofphase** [comment]
For reference, here is the entirety of `maybe_uninit.rs` extracted into a playground crate, with no changes but to comment out the stability attributes so that the compiler doesn't raise E0734, as well as add the necessary attributes directly at the top, and change a couple of instances of `crate::` to `core::`.

In this form, `assume_init` compiles without issues as a `const fn` (which is to say, it's something anyone using nightly could write themselves at any time.)

**Comment by slightlyoutofphase** [comment]
Alright, not gonna clog up the build queue anymore. 

Should I open a bug for this, though, or is there something else I'm missing here?

Does it maybe have something to do with the fact that `libcore` is of course `no_core`, whereas the working playground example I linked to was not?

**Comment by Centril** [comment]
The behavior you are seeing is here is by design and not a bug. The difference between the playground example and the actual libcore is that you've omitted `#![feature(staged_api)]`. As part of the static analysis the compiler performs, we ensure that crates with `#![feature(staged_api)]` are not allowed to use unstable const-features in stable `const fn`s (so called `min_const_fn`s) irrespective of whether `#![feature(const_fn)]` or that feature is enabled. More specifically, there are two features here that you need but cannot use in stable `const fn`s:

- The ability to call `panic_if_uninhabited` in stable `const fn`s.
- The ability to access union fields (which effectively amount to `mem::transmute`s).

For the time being, you can use `rustc_const_unstable` instead to make the function `const fn` on nightly-only.

**Comment by slightlyoutofphase** [comment]
> The behavior you are seeing is here is by design and not a bug. The difference between the playground example and the actual libcore is that you've omitted `#![feature(staged_api)]`. As part of the static analysis the compiler performs, we ensure that crates with `#![feature(staged_api)]` are not allowed to use unstable const-features in stable `const fn`s (so called `min_const_fn`s) irrespective of whether `#![feature(const_fn)]` or that feature is enabled. More specifically, there are two features here that you need but cannot use in stable `const fn`s:
> 
> * The ability to call `panic_if_uninhabited` in stable `const fn`s.
> * The ability to access union fields (which effectively amount to `mem::transmute`s).
> 
> For the time being, you can use `rustc_const_unstable` instead to make the function `const fn` on nightly-only.

Ah, yeah, it would have to be that way wouldn't it? Sorry for my clumsy attempts so far. Pretty sure `libcore` compiled fine on the in-progress builds though so I think I got it right this time.

I can add a test for it a bit later also, if that's something that would generally be wanted.

**Comment by Centril** [comment]
Yeah I do think you got it right. It would be good to squash the commits. Tests would also be neat; somewhere in `src/test/ui/consts/` would be ideal.

cc @oli-obk @RalfJung

**Comment by slightlyoutofphase** [comment]
Actually, I'm not sure this will work as-is. Trying to actually use it while writing a test I get "calling intrinsic `panic_if_uninhabited`" needs an rfc before being allowed inside constants".

It's unclear if that's meant literally though, because looking into it further, it seems like that message is just a catch-all for anything not present in librustc_mir/interpret/intrinsics.rs in the `emulate_intrinsic` function.

Miri seems to have a version of it that looks compatible (or at least that it could be made compatible) with the code in librustc_mir, though:
https://github.com/rust-lang/miri/blob/35e92d942093fad264ff010957d2eecb13a68315/src/shims/intrinsics.rs#L400

**Comment by RalfJung** [comment]
I am not a big fan of letting const code do the equivalent of `mem::uninitialized()` before it can do `mem::zeroed()`.

**Comment by RalfJung** [comment]
> Hmm, I'm not sure this will work as-is. Trying to actually use it while writing a test I get "calling intrinsic panic_if_uninhabited needs an rfc before being allowed inside constants".

See https://github.com/rust-lang/rust/pull/66275: intrinsics need to be specifically support in `const fn`, and this one is not yet. Moreover, there is a bug in const-checking (fixed by said PR) that leads to a bad error message.

**Comment by RalfJung** [comment]
To elaborate on my earlier post: at the current state, I don't view "because we can" as sufficient motivation for making tricky operations like `assume_init` CTFE-compatible.

The one use-case given *is already a hack*. `MaybeUninit::uninit().assume_init()` should basically never be used, currently it is used because we don't have stable const-array-initializers yet. Now this PR proposes to home in on that hack and adjust even more things around it. That does not seem like a great road to go down.

This is just an unstable experiment, so not a terribly big deal, but I'd rather we block stabilizing `assume_init` in CTFE on first having const-array-initializers stable. Then we don't drive people even more towards using `MaybeUninit::uninit().assume_init()`, which really is like the dreaded `mem::uninitialized` but *worse*.

**Comment by slightlyoutofphase** [comment]
> For `StaticVec`, couldn't that become const-compatible by making things a bit more hacky and using a type like this?
> 
> ```rust
> pub struct StaticVec<T, const N: usize> {
>   data: MaybeUninit<[MaybeUninit<T>; N]>,
>   length: usize,
> }
> ```

Possibly. I'm not sure how much that would complicate the rest of the crate though. Might not be worth it just to support `const new` right away.

Anyways, seems like there's generally more complexity to this overall issue than I thought. Should I just close the PR for now, then? It's not _that_ important to me anyways, I can definitely just wait for a better way of doing it that's what you think is a better way to go.

I might ask though if there's any aspect of the situation that _does_ need specific work in some area that no one is really working on at the moment? Would be happy to try to help that way if so.

**Comment by RalfJung** [comment]
For array repeat expressions, the tracking issue is https://github.com/rust-lang/rust/issues/49147. @ecstatic-morse would know the details, but I don't think it's implementation work blocking this right now.

For const `mem::zeroed`, the issue is https://github.com/rust-lang/rust/issues/62061. AFAIK the blocker is `&mut` in const, which last I heard @christianpoveda is working on.

**Comment by slightlyoutofphase** [comment]
Ok, well I'll close this for now then I guess, and keep an eye on the PRs / issues for anything I think I'd be capable of helping with.

**Pull request closed without merging**
