### PR TITLE
[WIP] NRVO pass for acyclic CFGs

### PR DESCRIPTION
**Pull request by jonas-schievink**

### CODE REVIEW

**Comment by slanterns** [comment]
Is this related to https://github.com/rust-lang/rust/pull/47954 ?

**Comment by jonas-schievink** [comment]
Yeah, it's a simpler version of that

**Comment by eddyb** [comment]
@slanterns Yeah, it's a simpler approximation - oops, @jonas-schievink already replied.

Failure seems to be formatting related, so I'm going ahead with:
@bors try @rust-timer queue

**Comment by eddyb** [comment]
Looks like neither of the racing `try` builds worked:

@bors try @rust-timer queue

**Comment by bjorn3** [comment]
`promoted_mir` is has become much slower in many cases.

**Comment by eddyb** [comment]
@bjorn3 To be clear, this run was for fun. I'm impressed it's only 30x though.

#47954 initially had regressions like 320x and I remember even 9000x but can't confirm that because the perf data from back then is gone now.
Also, those regressions were `inflate` and `clap-rs`, IIRC? Which both look fine now.

As for `promoted_mir`, I wonder if we're doing unnecessary work on constant MIR.
We might want to skip it, not because miri can't handle it (modulo #71005), but for perf reasons.

**Comment by jonas-schievink** [comment]
Wow, I'm impressed that building rustc with this optimization actually made it quite a bit faster in some cases! That makes me think making this optimization fast but approximate could already be a fairly big gain.

**Comment by jonas-schievink** [comment]
Let's see how the performance of an NRVO-optimized rustc changes.

@bors try @rust-timer queue

**Comment by jonas-schievink** [comment]
`option_env!` is compile-time only :facepalm: 

Well I messed that perf run up, but I guess this explains why @eddyb saw much worse performance – the pass simply handled more cases. Now that my pass handles arbitrary destination places instead of just locals, its performance became much worse, slowing down compilation up to 200x (but still better than the 1000x regressions that were apparently seen in the original attempt).

I guess the next steps for this pass are:
* Repeat the last experiment, this time correctly – to test performance of an NRVO-optimized rustc.
* Make the pass fast. I have several ideas I'll look into:
  * Precompute bitmaps mapping from `Local`s to the `BasicBlock`s using that local. This can be used to avoid traversing `BasicBlock`s other than the one containing the assignment we're looking at.
  * Precompute forwards and backwards reachability matrices of the CFG. This can be used to avoid traversing the CFG at all when checking if the live ranges overlap.
  * Both of these should only actually be computed if we have candidates.

**Comment by jonas-schievink** [comment]
Well that's marginally less disastrous, but I've expected the optimization to make more of a difference. Maybe the expensive part is walking the CFG.

Now let's actually only run it on rustc

@bors try @rust-timer queue

**Comment by jonas-schievink** [comment]
`tuple-stress` sees the biggest regression, since:

* It is 65535 lines for filling a static array with tuples
* It generates a function containing 131070 MIR locals
* It ends up only being a *single* MIR block
* ...containing 458745 statements

So, yeah, quite a lot of stress indeed. It is basically the worst-case scenario for this pass, at least how I've written it. For every candidate assignment, the pass will walk the containing basic block forwards and backwards to find conflicting uses of the involved locals. Looking at the MIR it seems that there's one candidate assignment for every tuple constructed, so 65535 in total. For each of these, it'll iterate over all 458745 statements.

My plans for speeding up this pass involve caching CFG walks, which does not matter at all in this case since the CFG is just one block in size. Not very encouraging.

I suppose the most promising way to do this would be to go with the original approach of calculating a conflict matrix between relevant locals. For now, I'll close this PR though. I've learned a lot while implementing this.

**Pull request closed without merging**
