### PR TITLE
Add a new `wide-arithmetic` feature for WebAssembly

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit adds a new rustc target feature named `wide-arithmetic` for WebAssembly targets. This corresponds to the [wide-arithmetic] proposal for WebAssembly which adds new instructions catered towards accelerating integer arithmetic larger than 64-bits. This proposal to WebAssembly is not standard yet so this new feature is flagged as an unstable target feature. Additionally Rust's LLVM version doesn't support this new feature yet since support will first be added in LLVM 20, so the feature filtering logic for LLVM is updated to handle this.

I'll also note that I'm not currently planning to add wasm-specific intrinsics to `std::arch::wasm32` at this time. The currently proposed instructions are all accessible through `i128` or `u128`-based operations which Rust already supports, so intrinsic shouldn't be necessary to get access to these new instructions.

[wide-arithmetic]: https://github.com/WebAssembly/wide-arithmetic

### CODE REVIEW

**Comment by alexcrichton** [comment]
ping @estebank, I'm happy to re-roll review here or otherwise seek out a reviewer if you're busy though

**Comment by jieyouxu** [comment]
I'll take a look.
r? jieyouxu

**Review by jieyouxu — APPROVED** [review]
Since this is an unstable flag, this LGTM, thanks!

**Pull request merged**
