### PR TITLE
Combine all builtin late lints

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by kennytm** [comment]
@Zoxc  If you're `try`ing for perf, we can't do it until #51680 is merged (see https://github.com/rust-lang/rust/pull/51356#issuecomment-399098087).

**Comment by kennytm** [comment]
@bors r- try- retry 

The try build is complete but we've restarted bors and got the states confused.

**Comment by kennytm** [comment]
@Mark-Simulacrum perf is requested `try#8059be493eda3c285d334e22c36b80071ee2a2a4` vs `master#f790780451a724dce9be0ba03ff217955036ff88`.

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by Zoxc** [comment]
Result: https://perf.rust-lang.org/compare.html?start=f790780451a724dce9be0ba03ff217955036ff88&end=8059be493eda3c285d334e22c36b80071ee2a2a4&stat=instructions%3Au

**Comment by estebank** [comment]
@Zoxc great! I feel comfortable merging this as is. Do you have any outstanding change before I approve?

**Comment by Zoxc** [comment]
@estebank No, this should be good to go.

**Pull request merged**
