### PR TITLE
Make rustc_parse_format compile again on stable

### PR DESCRIPTION
**Pull request by lnicola**
https://github.com/rust-lang/rust/pull/115948/files#r1385932710

r? @fmease

### CODE REVIEW

**Comment by fmease** [comment]
Duplicate of #117819

**Comment by lnicola** [comment]
Oh, sorry, somehow I didn't notice yours!

**Comment by fmease** [comment]
Since this unblocks an r-a sync I presume, I'm just gonna approve this PR. I'm gonna open a t-bootstrap/t-infra ticket for building compiler crates which ought to compile on stable without `RUSTC_BOOTSTRAP=0` in CI.

@bors r+ rollup

**Comment by lnicola** [comment]
It doesn't block the sync itself, just us using a newer version of this crate.

**Pull request closed without merging**
