### PR TITLE
Move the <dyn Error>::chain() method to a trait

### PR DESCRIPTION
**Pull request by haraldh**
Because `chain()` was only implemented for `dyn Error`, users had
to cast errors to a `&(dyn Error)` to use the `chain()` method.

```rust
    let mut iter = (&my_error as &(dyn Error)).chain();
    // or
    let mut iter = <dyn Error>::chain(&my_error);
    // or
    let mut iter = Error::chain(&my_error);
```

What I would liked to have is

```rust
pub trait Error: Debug + Display {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        None
    }

    fn chain(&self) -> Chain<'_> where Self: Sized + 'static {
        Chain {
            current: Some(self),
        }
    }
}

impl dyn Error + 'static {
    fn chain(&self) -> Chain<'_> {
        Chain {
            current: Some(self),
        }
    }
}
```

This doesn't work, because of:
https://github.com/rust-lang/rust/issues/69161

This patch introduces an ErrorChain trait, which accomplishes the
job and is implemented for `Error` and `dyn Error + 'static`.

### CODE REVIEW

**Comment by CryZe** [comment]
Don't you have to import the trait then? Wouldn't just a free standing `std::error::chain(...)` make more sense?

**Comment by haraldh** [comment]
> Don't you have to import the trait then? Wouldn't just a free standing `std::error::chain(...)` make more sense?

Hmm... works, but not so ergonomic.  E.g. for `mybox: Box<dyn Error>` you will have to write `chain(mybox.as_ref())` instead of simply `mybox.chain()`

**Comment by haraldh** [comment]
Hmm, cannot find the source of the CI error.

**Comment by JelteF** [comment]
I think it's very important to have chain as a method method call. Otherwise it will not be very useful to add more functionality to the Chain, because creating a Chain will require too much effort. So I fully support the idea of this PR. I would very much prefer #69161, since I think it's much nicer not to have to import a separate trait to get access to this method.

**Comment by JelteF** [comment]
@haraldh I figured out a way to get this to work:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=949ac10fa02c57adf23cb1c1f7352b10

It does trigger the warning added in https://github.com/rust-lang/rust/issues/51443, but I guess it might be fine in this case. If not it seems reasonable to use this in nightly until #69161 is fixed.

**Comment by haraldh** [comment]
> @haraldh I figured out a way to get this to work, without requiring the ErrorChain trait to be added to the scope:
> https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=949ac10fa02c57adf23cb1c1f7352b10
> 
> It does trigger the warning added in #51443, but I guess it might be fine in this case. If not it seems reasonable to use this in nightly until #69161 is fixed.

cool, but I don't want everybody using `Error` to have this warning displayed. Is there any way to turn it off in this case?

**Comment by JelteF** [comment]
I would expect this can be done by adding `#[allow(where_clauses_object_safety)]` somewhere. I cannot get it to work on the playground though without adding `#![allow(where_clauses_object_safety)] to the top of the file. Can you check if you can make it work in the actual rustc source? I expect it should work, since it looks like the warning is on the trait itself, not the usage of the trait.

**Comment by haraldh** [comment]
> I would expect this can be done by adding `#[allow(where_clauses_object_safety)]` somewhere. I cannot get it to work on the playground though without adding `#![allow(where_clauses_object_safety)] to the top of the file. Can you check if you can make it work in the actual rustc source? I expect it should work, since it looks like the warning is on the trait itself, not the usage of the trait.

If it doesn't work in the playground, I doubt it works without global disable.

**Review by dtolnay — COMMENTED** [review]
Thanks for the PR!

I am interested in having a chain method that works better, but I would prefer not to add a new standard library trait just for this. I would instead like to see work on https://github.com/rust-lang/rust/issues/69161 and then implement chain in the way you say you want in the PR description. A trait like this would only hamstring us once the method resolution issue is fixed.

**Pull request closed without merging**
