### PR TITLE
Stabilize termination_trait_lib

### PR DESCRIPTION
**Pull request by llogiq**
This is a prerequisite to #56470

### CODE REVIEW

**Comment by llogiq** [comment]
Error seems unrelated. Any ideas?

**Comment by cramertj** [comment]
@llogiq If you're interested in stabilizing, would you be able to write up a stabilization report on the tracking issue? The lang team isn't sure about whether or not this feature is ready for stabilization, and we'd like to see an update on where the feature is and why it's being proposed for stabilization.

**Comment by nikomatsakis** [comment]
Note: maybe there is another way to achieve the goals w/o stabilization? (Or with a narrow stabilization)

**Comment by Dylan-DPC** [comment]
ping from triage @llogiq any updates on this?

**Comment by llogiq** [comment]
On second thought, I agree that it's probably too early to stabilize. Besides I found a way to accept `Results` in doctests without this feature, so this doesn't block anything. Closing this for now.

**Pull request closed without merging**
