### PR TITLE
emscripten: Use the latest emsdk 3.1.68

### LINKED ISSUE #131467: Emscripten metadata file size is wrong
I tried this code:

```rust
std::fs::read("my-file")
```

for a file that is <1MB large.

I expected to see this happen: The read should allocate a vec that is as large as the file content. The heap size in Emscripten should not meaningfully change.

Instead, this happened: The Emscripten heap grows by 1.8GB

I looked into the implementation of fs::read. Since it uses the file metadata size to pre-allocate the output vector, I debug printed the file size, which is around 1.8GB.

Since my Rust code is running inside Pyodide 0.25, I also checked Python's os.stat of the file, which reports the correct file size. Reading the file in Python also succeeds without the enormous over-allocation. It seems that this is a Rust-specific bug in getting the correct file size information from Emscripten.

### Meta

My Rust toolchain is pinned to nightly-2024-07-21, the last nightly for 1.81.

### PR DESCRIPTION
**Pull request by workingjubilee**
This should fix our precompiled std being unsound in `std::fs` code.

Should resolve #131467 I hope.

### CODE REVIEW

**Comment by Kobzol** [comment]
I have to say that I'm often clueless when reviewing these kinds of PRs :) Do we have some documentation about what does it mean to update this? Do we even document somewhere which version of emscripten we use for given targets, or is it just an "internal implementation detail".

**Comment by juntyr** [comment]
Updating the Emscripten version to something newer is definitely a good idea. But it should go hand-in-hand with some documentation (I'll submit a PR later) on this coupling between Emscripten and Rust that won't matter in most cases until you get a weird bug, and how to work around it with `-Zbuild-std`.

I think I was experiencing this issue for a long while but simply never noticed. Pyodide can use ~2GB RAM before anything breaks, and up until a few days ago even the senseless overallocation during file reading never hit the boundary. So it was by pure chance and additional up-front memory pressure that allocating an extra 1.8GB was no longer fine and I noticed the ABI mismatch.

**Comment by hoodmane** [comment]
Thanks for helping to support the Emscripten target @workingjubilee! I really appreciate it.

**Comment by alexcrichton** [comment]
Alas I'm ignorant in the ways of Emscripten here so I also don't understand the full consequences of what an update here might have. In the absence of more information it seems reasonable to go ahead with the update and use it as a learning process for what to and what not to do in the future.

**Comment by workingjubilee** [comment]
atm I don't think anyone understands how *Rust* interacts with Emscripten, tbh.

@sbc100 if you could weigh in?

**Comment by sbc100** [comment]
I also don't know much about how emscripten and rust work together, but updating certainly seems like a good idea.  2.0.5 is ancient.

I assume there is some amount of CI testing that occurs here to make sure at least some things work?

**Comment by workingjubilee** [comment]
> I also don't know much about how emscripten and rust work together, but updating certainly seems like a good idea. 2.0.5 is ancient.
> 
> I assume there is some amount of CI testing that occurs here to make sure at least some things work?

...we make sure things build! :D

**Comment by workingjubilee** [comment]
Yeah, that was my feeling as well.

It would be nice to land more tests for emscripten but even for the tests that we do run, it already has a custom test harness in compiletest. More tests may thus require wrangling more Fun, and such tests will not necessarily be checked in CI. Indeed, a large portion of the UI test suite seems to fall prey to linking failures when I try to build it, for reasons that don't have any clear relationship with the EMSDK version, and probably have been true for quite some time.

As this is a soundness concern, it doesn't seem worth blocking on a task which will take an indefinite amount of time. Thus, let us give scream-based deployment testing a go.

@bors r=Kobzol

**Pull request merged**
