### PR TITLE
Split up libproc_macro_plugin

### PR DESCRIPTION
**Pull request by nrc**
Separate the plugin code from non-plugin code to break a potential cycle in crates.

This will allow us to merge the new libproc_macro_tokens into libproc_macro.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Do we want to perhaps go ahead and merge `proc_macro_tokens` into `proc_macro`? It should be fine to stabilize some surface area of that crate without stabilizing all of it.

**Comment by nrc** [comment]
@alexcrichton that is kind of tricky because everything in proc_macro_tokens uses the `TokenStream` which is not the `proc_macro` one. I think the next step has to be merging the `TokenStream`s (there has to be a Ghostbusters joke in there somewhere) and then merging the two crates would be trivial.

**Comment by alexcrichton** [comment]
@bors: r+

Ok!

**Comment by nrc** [comment]
r=@alexcrichton

**Pull request merged**
