### PR TITLE
Simplify Command::spawn (no semantic change)

### PR DESCRIPTION
**Pull request by joshtriplett**
This minimizes the size of an unsafe block, and allows outdenting some
complex code.

### CODE REVIEW

**Comment by joshtriplett** [comment]
Note that I based this PR on the branch from https://github.com/rust-lang/rust/pull/83121 , to avoid a conflict.

**Comment by kennytm** [comment]
CI not running? 🤔

**Comment by joshtriplett** [comment]
I'd like to hold off on this one until https://github.com/rust-lang/rust/pull/81825 gets in, since the two will likely conflict and that one has been waiting longer. I'll rebase this after that goes in.

**Comment by voidc** [comment]
I also don't mind rebasing #81825 if you want to merge this first.

**Comment by joshtriplett** [comment]
@voidc I appreciate that, but this is a minor cleanup and I'm much more interested in the pidfd work.

**Comment by joshtriplett** [comment]
Since #81825 seems to be blocked by an LLVM codegen issue, I'd like to go ahead and merge this.

**Comment by joshtriplett** [comment]
@kennytm

**Pull request merged**
