### PR TITLE
delete some old tests

### PR DESCRIPTION
**Pull request by steveklabnik**
These are for syntaxes that haven't existed for a long time.

### CODE REVIEW

**Comment by tshepang** [comment]
Aren't these tests still valid? Is it enough to just trust that the compiler rejects such syntax?

**Comment by nikomatsakis** [comment]
they are indeed still valid tests, but then a regression here seems rather unlikely

**Comment by brson** [comment]
Oh, I didn't look closely before commenting. Still, I feel ok about removing them. Nobody's going to accidentally reimplement old syntaxes.

**Comment by tshepang** [comment]
Looks like there are other tests for old syntax. What should be done with them? I imagine these were only really useful pre-1.0?

**Pull request merged**
