### PR TITLE
Fix rustc_lint_defs documentation typo

### PR DESCRIPTION
**Pull request by benmezger**
Found a typo while reading the documentation. This PR fixes it.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Thanks!

@bors r+

**Comment by ehuss** [comment]
Sorry, I make that typo way too often (I just did it again this morning).  I don't know why my fingers don't want to type that word correctly.

**Comment by benmezger** [comment]
> Sorry, I make that typo way too often (I just did it again this morning).  I don't know why my fingers don't want to type that word correctly.
> 
> 

Don't worry. I first fixed the typo by repeating the typo 😅

**Pull request merged**
