### PR TITLE
Puts capitals and dots in the comments of the rustonomicon.

### PR DESCRIPTION
**Pull request by gamazeps**
This is a bit silly but it bothered me much more than it should have
when reading the rustonomicon (great read by the way!).

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @steveklabnik, do we have a convention on this?

**Comment by gamazeps** [comment]
Actually it's mostly because it was inconsistent, sometimes there were capital and no dots, sometime dots and no capital, sometime both and sometime none.

**Comment by steveklabnik** [comment]
We don't have a strong one. I tend to use less complete sentences when writing comments, so I'm not sure here.

**Comment by gamazeps** [comment]
I doesn't really change the comments, it's just for consistency :)
If a coding style is decided at some point I have no issues changing them all to the agreed style.

**Comment by alexcrichton** [comment]
Perhaps some comments could be touched up, but perhaps not in a blanket-change-everything fashion? Some of these seem like they were intended to be fragments or such where others probably just mistakenly need a capital letter or some punctuation.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with comments addressed!

**Pull request closed without merging**
