### PR TITLE
compiletest: "fix" FileCheck with --allow-unused-prefixes

### PR DESCRIPTION
**Pull request by durin42**
The default of --allow-unused-prefixes used to be false, but in LLVM
change 87dbdd2e3b (https://reviews.llvm.org/D95849) the default became
true. I'm not quite sure how we could do better here (specifically not
providing the CHECK prefix when it's not needed), but this seems to work
for now.

This reduces codegen test failures against LLVM HEAD from 31 cases to 5.

### CODE REVIEW

**Comment by durin42** [comment]
It wasn't clear to me how I should gate this flag on LLVM >= 13, but the flag was new in https://reviews.llvm.org/D90281, which is dated October 2020 so it's a recent flag. I assume we need to do some detection on that, but how? Can someone guide me on that?

Thanks!

**Comment by nikic** [comment]
Can you maybe share an example of a test that currently fails without the flag?

**Comment by durin42** [comment]
https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/1517#08add164-76ca-4964-ad3d-eee03fd98059 has around 25. An example from there:

```
---- [codegen] codegen/abi-efiapi.rs#arm stdout ----
  |  
  | error in revision `arm`: verification with 'FileCheck' failed
  | status: exit status: 2
  | command: "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--input-file" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/codegen/abi-efiapi.arm/abi-efiapi.ll" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/src/test/codegen/abi-efiapi.rs" "--check-prefixes" "CHECK,arm"
  | stdout:
  | ------------------------------------------
  |  
  | ------------------------------------------
  | stderr:
  | ------------------------------------------
  | error: no check strings found with prefix 'CHECK:'
  |  
  | ------------------------------------------
 ```

I think the problem is the unconditional inclusion of CHECK in the `--check-prefixes` flag, but I'm not sure how to determine when it should be included.

**Comment by nikic** [comment]
Thanks for the example. So the problem is that for tests with revisions, we translate the revisions to FileCheck prefixes, while also retaining `CHECK` as a common prefix. And we do have tests that make use of both CHECK and revision prefixes at the same time.

So I think passing `--allow-unused-prefixes` is the right thing to do for our usage. You should be able to gate on LLVM by checking `config.llvm_version`, which will be something like `Some(130000)` for LLVM 13.

**Comment by durin42** [comment]
Updated - note that as of today rustc HEAD won't compile against LLVM HEAD, but you can test this change if you want against LLVM commit d2a291a5f81af7c99351ecf619c7115ac652b115 - I'll try and work on the build-fix later today so we can see the remaining codegen bugs against head easily.

**Comment by durin42** [comment]
Alternatively, you can wait for #85416 to be in and then this should be easy to test against LLVM/Rust HEADs.

**Pull request merged**
