### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by compiler-errors**
Successful merges:

 - #114287 (update overflow handling in the new trait solver)
 - #114475 (Migrate GUI colors test to original CSS color format)
 - #114482 (Fix ui-fulldeps missing the `internal_features` lint on stage 0)
 - #114490 (Fix a typo in the error reporting for sealed traits.)
 - #114491 (Rename issue #114423 test files to include context)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=114287,114475,114482,114490,114491)

### CODE REVIEW

**Comment by Kobzol** [comment]
@rust-timer build 72c7f0ec33b0b7dc5d13a562527c6ae4d578125b

(the only thing that comes to mind)

**Comment by lqd** [comment]
This PR should be self-contained within the new solver, but we'll see. 

tt-muncher check looks like a bump back to steady state. And the hyper doc regression looks possibly "expected" with the rustdoc PR in the rollup.

---

Unless you're trying to find the source of the wins: in that case I'd think it's just the ripples of the incr comp regression noise we've been seeing in the last few merges.

image

(kinda looks like the top of the batman symbol)

**Comment by Kobzol** [comment]
I was actually worried about [this](https://perf.rust-lang.org/compare.html?start=90f0b24ad3e7fc0dc0e419c9da30d74629cd5736&end=fca59ab5f0e7df7d816bed77a32abc0045ebe80b&stat=cycles:u).

**Comment by lqd** [comment]
Since there's no PR involved in CTFE here, I was thinking it was some noise, like this also happened a couple weeks ago in https://perf.rust-lang.org/compare.html?start=1c44af9b791c16557b5bf606707bb76df979134a&end=cec34a43b1b14f4e39363f3b283d7ac4f593ee81&stat=cycles:u

**Comment by Kobzol** [comment]
@lqd good catch, I didn't know that it blipped recently. Given that the perf. run didn't return anything, and the other PRs should be harmless, I think this can be triaged as resolved.

**Pull request merged**
