### PR TITLE
bootstrap: use `internment` instead of hand-rolled interning

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
Part of the #109859.

### CODE REVIEW

**Comment by GrigorenkoPV** [comment]
Unfortunately, this pulls in hashbrown, so probably not worth it

**Comment by Dylan-DPC** [comment]
@GrigorenkoPV what's the status on this? maybe you can resolve the conflicts and we can push this forward

**Comment by jieyouxu** [comment]
> tidy error: invalid license `Zlib` in `registry+https://github.com/rust-lang/crates.io-index#foldhash@0.1.3`

**Comment by GrigorenkoPV** [comment]
Well, it comes as a dependency from the hashbrown crate. And no, it does not seem to be dual licensed.

Anyways, I'm not sure, what do I have to do now? Since it's S-waiting-on-author

**Comment by jieyouxu** [comment]
Sorry, this is S-waiting-for-compiler-leads :3

**Comment by Kobzol** [comment]
While I like the code simplification, as usually, adding a dependency to bootstrap is a very hard sell. This increases the number of dependencies from 86 to 91, for relatively little gain. This code was written in ~2017, and from that time it required only very little maintenance (apart from some Clippy lint fixes and some small refactoring), and it seems to be working just fine. Yes, we found a case of unsoundness in it once, but now that the two unsafe lines of code in it were heavily reviewed, I trust that it should be OK.

CC also @onur-ozkan

**Comment by jieyouxu** [comment]
> While I like the code simplification, as usually, adding a dependency to bootstrap is a very hard sell. This increases the number of dependencies from 86 to 91, for relatively little gain.

For more context on why, bootstrap needs to keep minimal deps as it needs to build fast.

**Comment by onur-ozkan** [comment]
> While I like the code simplification, as usually, adding a dependency to bootstrap is a very hard sell. This increases the number of dependencies from 86 to 91, for relatively little gain. This code was written in ~2017, and from that time it required only very little maintenance (apart from some Clippy lint fixes and some small refactoring), and it seems to be working just fine. Yes, we found a case of unsoundness in it once, but now that the two unsafe lines of code in it were heavily reviewed, I trust that it should be OK.
> 
> 
> 
> CC also @onur-ozkan

Completely agree.

**Comment by Kobzol** [comment]
The original [issue](https://github.com/rust-lang/rust/issues/109859) has mentioned the `lasso` library, which seems to only depend on hashbrown. But we don't even depend on that :( So with lasso, it would actually be 94.

We should probably make a t-bootstrap decision on what to do about https://github.com/rust-lang/rust/issues/109859, to avoid sending mixed signals that we want to remove all `unsafe` at all costs, which is probably not true.

**Comment by GrigorenkoPV** [comment]
I also do not think moving `unsafe` over into dependencies would be a good idea in all cases. I just mostly wanted to get a confirmation

**Comment by GrigorenkoPV** [comment]
I also do not think moving `unsafe` over into dependencies would be a good idea in all cases. I just mostly wanted to get it over with #109859 by either fixing or getting an explicit "wontfix" for every point brought up there. Just to make sure that all the unaddressed places were consciously not touched and not just simply overlooked. So, now that #109859 is closed,

**Comment by Kobzol** [comment]
Sorry for the previous confusion. Thank you for working on this, and making the other changes that were already merged!

**Comment by jieyouxu** [comment]
Yeah, we should've updated that issue earlier. Sorry for the confusion and thanks for the PR!

**Pull request closed without merging**
