### PR TITLE
Revert recent changes to dead code analysis

### LINKED ISSUE #126169: dead_code lint wrongly warns about public repr(C) structs with private fields but no constructors
### Code

```Rust
#[repr(C)] // <--
pub struct Foo {
    pub i: i16,
    align: i16
}
```

### Current output

```Shell
warning: field `align` is never read
 --> src/lib.rs:3:5
  |
1 | pub struct Foo {
  |            --- field in this struct
2 |     pub i: i16,
3 |     align: i16
  |     ^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

### Desired output

```Shell
No warnings, or perhaps a different warning.
```

### Rationale and extra context

This warning is probably triggering because there's no constructor that allows a user to set the `align` field on struct `Foo`.  However, there is still a valid way for a user to construct it: `std::mem::zeroed()`.  The libc crate contains many structs that must be initialized that way.  libc could silence these warnings by `#[allow(dead_code)]`, but that's too broad a brush.  It would silence many much more serious warnings.  Could we please either revert to the previous behavior, or else create a new lint for this that can be separately silenced?

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.80.0-nightly (804421dff 2024-06-07)
binary: rustc
commit-hash: 804421dff5542c9c7da5c60257b5dbc849719505
commit-date: 2024-06-07
host: x86_64-unknown-freebsd
release: 1.80.0-nightly
LLVM version: 18.1.7
```

### Anything else?

This is a regression since `rustc 1.80.0-nightly (f67a1acc0 2024-06-01)`.  That version did not warn in such cases.

Downstream issue: https://github.com/rust-lang/libc/issues/3740

### LINKED ISSUE #128272: false positive `dead_code` "never constructed" warning on 1.80.0 for a `struct` where the constructor takes `&'static self`
### Code

```Rust
/* XXX: changing Foo::init to take self: &'static Foo instead of
 * &'static self silences the dead_code warning. */
pub struct Foo {
    x: i32,
}

impl Foo {
    #[must_use]
    //pub const fn init(self: &'static Foo, x: i32) -> Foo {
    pub const fn init(&'static self, x: i32) -> Foo {
        Foo { x }
    }

    pub fn foo(&self) -> i32 {
        self.x
    }
}

#[cfg(test)]
mod test {
    use crate::Foo;

    #[test]
    fn test() {
        static FOO: Foo = FOO.init(7);
        assert_eq!(FOO.foo(), FOO.x);
    }
}
```

### Current output

```Shell
warning: struct `Foo` is never constructed
 --> src/lib.rs:3:12
  |
3 | pub struct Foo {
  |            ^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `playground` (lib) generated 1 warning
```

### Desired output

No output.

### Rationale and extra context

This problem does not occur with 1.79.0. https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=ad761b02ac5d86f28629e7fa2d6a1936

This is a reduced example from real code where objects are constructed in such a way that they need static references to fields within the same object (and those objects themselves will be static). It's clearly possible to construct such an object, so the dead_code warning is not accurate.

### Other cases

Changing the parameter to be `self: &'static Foo` instead silences the warning.

### Rust Version

```Shell
$ rustc --version --verbose
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: aarch64-apple-darwin
release: 1.80.0
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by compiler-errors**
This is a revert to recent changes to dead code analysis, namely:
* efdf219 Rollup merge of #128104 - mu001999-contrib:fix/128053, r=petrochenkov
* a70dc297a899b76793a14c5705f6ec78fd7a57a7 Rollup merge of #127017 - mu001999-contrib:dead/enhance, r=pnkfelix
* 31fe9628cf830a08e7194a446f66c668aaea86e9 Rollup merge of #127107 - mu001999-contrib:dead/enhance-2, r=pnkfelix
* 2724aeaaeb127a8073e39461caacbe21a128ce7b Rollup merge of #126618 - mu001999-contrib:dead/enhance, r=pnkfelix
* 977c5fd419ade52467f7de79d5bfc25c0c893275 Rollup merge of #126315 - mu001999-contrib:fix/126289, r=petrochenkov
* 13314df21b0bb0cdd02c6760581d1b9f1052fa7e Rollup merge of #125572 - mu001999-contrib:dead/enhance, r=pnkfelix

There is an additional change stacked on top, which suppresses false-negatives that were masked by this work. I believe the functions that are touched in that code are legitimately unused functions and the types are not reachable since this `AnonPipe` type is not publically reachable -- please correct me if I'm wrong cc @NobodyXu who added these in #127153.

Some of these reverts (#126315 and #126618) are only included because it makes the revert apply cleanly, and I think these changes were only done to fix follow-ups from the other PRs?

I apologize for the size of the PR and the churn that it has on the codebase (and for reverting @mu001999's work here), but I'm putting this PR up because I am concerned that we're making ad-hoc changes to fix bugs that are fallout of these PRs, and I'd like to see these changes reimplemented in a way that's more separable from the existing dead code pass. I am happy to review any code to reapply these changes in a more separable way. 

cc @mu001999
r? @pnkfelix 

Fixes #128272
Fixes #126169

### CODE REVIEW

**Comment by workingjubilee** [comment]
I agree, it seems likely these changes have allowed some dead code to pass as live.

Though I am _also_ almost-certain that these linting changes have _correctly_ revealed more dead code in the standard library for some targets. So I would be happy to see them return in a more precise and perhaps configurable format, because I would like to delete whatever code in the standard library target support is truly dead.

**Comment by ChrisDenton** [comment]
Note that the `library/src/sys/` directory is undergoing a pretty major refactoring so that `unix` hopefully won't just be a soup of disparate targets. So things like `#[allow(dead_code)] // Not used on all platforms` will (hopefully) be a thing of the past. Though I don't expect that effort to complete any time soon.

**Comment by compiler-errors** [comment]
Felix told me to r=them on this PR, so:

@bors r=pnkfelix

Also I'm going to beta-nominate this, since at least a few of these commits can be reverted on beta as well. I'll probably have to prepare the beta revert by hand, but I'm happy to do so.

**Comment by tgross35** [comment]
Failed in the rollup, https://github.com/rust-lang/rust/pull/128423#issuecomment-2259593499. Looks like this bit shouldn't actually get added back? https://github.com/rust-lang/rust/commit/cfe4039098bc760a3074e8150f5afd5b8043e909#diff-d4747a985d7b47cdae081cfcd2060642cfd377791e4a354ac3e847391ddab7e8.

Not sure why this didn't show up in the PR CI, salsa hasn't changed since this PR was created.

@bors r-

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-08-01/near/455659353). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted

**Comment by compiler-errors** [comment]
Tests failed because `./x.py test ui-fulldeps --stage=1` uses the stage0 compiler, which still has these changes, so we still need to keep the `allow(dead_code)` that were removed by reverting these PRs. I fixed the tests.

@bors r=pnkfelix rollup=iffy

**Comment by jieyouxu** [comment]
@bors r-
Probably caused the failure in https://github.com/rust-lang/rust/pull/128577#issuecomment-2266631321

**Pull request merged**
