### PR TITLE
Querify object_safety_violations.

### PR DESCRIPTION
**Pull request by cjgillot**
Split from #69076

r? @Zoxc

### CODE REVIEW

**Comment by cjgillot** [comment]
Failure seems spurious.

**Comment by jonas-schievink** [comment]
The `is_object_safe` query can probably be removed then, and replaced with a method on `TyCtxt`

**Comment by cjgillot** [comment]
Perf seems good. Shall we try with `is_object_safe` removed?

**Comment by Zoxc** [comment]
Yes we can probably make `is_object_safe` a method calling `object_safety_violations` now.

**Comment by cjgillot** [comment]
Added a commit doing that.

**Pull request merged**
