### PR TITLE
[Doc] Add links to the `thread::LocalKey` doc.

### PR DESCRIPTION
**Pull request by gamazeps**
Part of #29378 .

I do not know exactly what should be done for the `cleanup` part, if you have any idea I'll gladly do it.

r? @rust-lang/docs

### CODE REVIEW

**Comment by frewsxcv** [comment]
```
[00:43:55] Linkcheck (x86_64-unknown-linux-gnu)
[00:43:56] std/macro.thread_local.html:60: broken link - std/struct.LocalKey.html
[00:43:56] std/macro.thread_local.html:75: broken link - std/struct.LocalKey.html
[00:43:56] std/index.html:938: broken link - std/struct.LocalKey.html
[00:44:02] thread 'main' panicked at 'found some broken links', /checkout/src/tools/linkchecker/main.rs:49
```

**Comment by gamazeps** [comment]
Indeed, my mistake....

**Comment by gamazeps** [comment]
Done :)

**Review by frewsxcv — APPROVED** [review]

**Comment by frewsxcv** [comment]
Thanks!

@bors r+ rollup

**Comment by steveklabnik** [comment]
>  if you have any idea I'll gladly do it.

I don't really remember what I was thinking of specifically, so let's not worry about it!

**Pull request merged**
