### PR TITLE
Remove derives `Encodable`/`Decodable` and unstabilize attribute `#[bench]`

### LINKED ISSUE #62048: Built-in derive macros `Encodable`, `Decodable`, `RustcEncodable` and `RustcDecodable` are stable
The macros produce paths like `serialize::foo` or `rustc_serialize::foo` and I suspect that the feature gating was supposed to happen when you write `extern crate serialize` to bring that `serialize` into scope.

However, you can easily write `use anything as serialize`, and `rustc_serialize` is a stable crate on crates.io, so this kind of feature gating doesn't work.

After https://github.com/rust-lang/rust/pull/62042 lands we should try to un-stabilize them and test it with crater.

### PR DESCRIPTION
**Pull request by petrochenkov**
`Encodable` and `Decodable` were deprecated before 1.0 and emitted an unsuppressable warning all this time.
`#[bench]` is a part of the custom test framework feature and cannot be used meaningfully on stable, only as `cfg(false)`.

Crater results can be found in https://github.com/rust-lang/rust/pull/62507#issuecomment-513850732 and below.

This PR also reroutes the tracking issue for `feature(test)` from #27812 (compiler internals) to #50297 (custom test frameworks).

Closes https://github.com/rust-lang/rust/issues/62048

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot run mode=check-only

**Comment by pietroalbini** [comment]
@craterbot retry

**Comment by kennytm** [comment]
The crater failure seems legit.

**Comment by petrochenkov** [comment]
Argh, there's only one crater instance right now, so it won't run for a few days anyway.

**Comment by kennytm** [comment]
The error message should be clearer anyway. "Some threads returned an error" is totally pointless.

**Comment by petrochenkov** [comment]
`RustcDecodable` - 418 projects
`RustcEncodable` - 211 projects
`bench` - 5 projects
`Decodable` - 0 projects
`Encodable` - 0 projects

Ok, it's clear that we
- can remove `Encodable`/`Decodable` and
- cannot remove `RustcDecodable`/`RustcEncodable` (but perhaps can deprecate if something like https://github.com/rust-lang/rust/issues/62398 is implemented).

I'll check how `#[bench]` is used.

**Comment by petrochenkov** [comment]
`#[bench]`:
- `./reg/punkt/1.0.5` - `#![cfg_attr(test, feature(test))]`, other unconditional features, nightly crate
- `./reg/route-recognizer/0.1.12` - `#![cfg_attr(test, feature(test))]`, no other unconditional features
- `./reg/triadic-census/0.2.0` - `#![cfg_attr(test, feature(test))]`, no other unconditional features
- `./reg/beehave/0.0.4` - no `feature`s (not sure how this works), part of examples rather than primary code, other unconditional features, nightly crate
- `./gh/ryan-scott-dev/beehave` - duplicate of the previous one

I.e. 2 real stable regressions.
Seems more or less ok to unstabilize, given the unclear plans for custom testing frameworks.

**Comment by petrochenkov** [comment]
I'll implement the deprecation/removal once https://github.com/rust-lang/rust/pull/62086 lands.

**Comment by Centril** [comment]
> cannot remove `RustcDecodable`/`RustcEncodable` (but perhaps can deprecate if something like #62398 is implemented).

It's clear to me that we cannot remove it now but it's also clear to me that this is a C-future-compatibility case and that these need to be removed eventually, especially given the fact that these are called `RustcDecodable` and `RustcEncodable` so anyone using these must have known that they were not meant to be stable.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks for all the descriptions and analysis here, makes reviewing a breeze on my end. This all looks and sounds great to me! The conclusion matches my gut in that removing the `Rustc*` modes won't be an easy task, but I also don't think it's impossible. If we really need to I think it's plausible with enough messaging and careful planning, but I suspect the technical debt of `Rustc*` derive modes hasn't quite gotten that heavy yet.

**Comment by Centril** [comment]
> The conclusion matches my gut in that removing the `Rustc*` modes won't be an easy task, but I also don't think it's impossible. If we really need to I think it's plausible with enough messaging and careful planning, but I suspect the technical debt of `Rustc*` derive modes hasn't quite gotten that heavy yet.

I think the following plan would work towards removing them eventually:
1. Write a custom derive macro that does the equivalent of what rustc does and publish it on cargo.
2. Create a C-future-compatibility lint which suggests using said crate.
3. File some PRs to some of the bigger crates with more users.

**Comment by Centril** [comment]
@bors r-

Failed in https://github.com/rust-lang/rust/pull/63112#issuecomment-516202569.

**Comment by petrochenkov** [comment]
Waiting on https://github.com/rust-lang/cargo/pull/7198.

**Comment by alexcrichton** [comment]
@bors: r+

I think the changes in https://github.com/rust-lang/rust/pull/62766 to src/bootstrap/test.rs means that this should be landable, because nightly tests in Cargo shouldn't be running on Rust's CI

**Comment by Nemo157** [comment]
Breaking `route-recognizer` with this change is quite annoying, it is depended on by quite a few projects, but doesn't seem to have any active maintenance team. There have been recent attempts to get access to support it better, but as far as I know it's still pretty much abandoned but in use at this point.

**Pull request merged**
