### PR TITLE
Using expressions instead sentences

### PR DESCRIPTION
**Pull request by tehAnswer**
Imho, this is more idiomatic.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hey @tehAnswer ! I find this version significantly harder to read, because of the `=` and the `==` on the same line, and then, without the `;`, I was trying to figure out if the value got returned somewhere...

Let's see what others have to say.

**Comment by tehAnswer** [comment]
D'oh! Sorry, I forgot the `;`.  Yeah, maybe it's harder to read, but it is the more correct! If Rust could speak, it will agree with me. Because Rust play no games.

Cheers!

**Comment by oli-obk** [comment]
The reason the `done` variable is inside an if-condition, is that it leads the way to the `break`. Therefor I would stay with the if. You could easily refactor the while loop to `while x % 5 != 0 {...}`, but the whole example is meant to introduce `break` and `continue`, not show how to write minimal code.

**Comment by nikomatsakis** [comment]
Personally, I agree with @steveklabnik  that the code before was more readable. With the new version, it's less obvious that e.g. the `done` flag goes from `false` to `true` but never vice-versa (I had to think about it for a second). I also would prefer redundant parens to make visually parsing more obvious: `x = (y == 2)`. But anyway if I were writing this code for *real*, I'd use `loop` and `break` and drop the `done` variable altogether -- but that wouldn't demonstrate a `while` loop, so it makes for a poor example. :)

In any case, I'm going to close this PR and advocate leaving the code as is, but thank you for the suggestion in any case.

**Pull request closed without merging**
