### PR TITLE
static mut: allow mutable reference to arbitrary types, not just slices and arrays

### PR DESCRIPTION
**Pull request by RalfJung**
For historical reasons, we allow this:
```rust
static mut ARRAY: &'static mut [isize] = &mut [1];
```
However, we do not allow this:
```rust
static mut INT: &'static mut isize = &mut 1;
```

I think that's terribly inconsistent. I don't care much for `static mut`, but we have to keep it around for backwards compatibility and so we have to keep supporting it properly in the compiler. In recent refactors of how we deal with mutability of data in `static` and `const`, I almost made a fatal mistake since I tested `static mut INT: &'static mut isize = &mut 1` and concluded that we don't allow such `'static` mutable references even inside `static mut`. After all, nobody would expect this to be allowed only for arrays and slices, right?!?? So for the sake of our own sanity, and of whoever else reverse engineers these rules in the future to understand what the Rust compiler accepts or does not accept, I propose that we accept this for all types, not just arrays and slices.

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
It's better to reroll. r? compiler

**Review by davidtwco — APPROVED** [review]
Implementation looks good to me, but this should have t-lang look over it.

**Comment by RalfJung** [comment]
Note that this is orthogonal to `feature(const_mut_refs)`. That feature would still not accept the example since it only allows mutable references to memory that will be deallocated before the `static mut` is done computing. Also, without `const_mut_refs`, there's no way to write to a mutable reference in const context, so even though we allow more `&mut` expressions in `static mut`, there's not a ton one can do with them except for just using them as the final value of the static. (And if there is a way to write to a mutable reference in `static mut`, then that's already an issue for the array case, so allowing it on more types doesn't really make things worse.)

**Comment by joshtriplett** [comment]
@rfcbot cancel

Oops. I meant for that to be a lang FCP. Will remove compiler, FCP, and re-add compiler.

**Comment by tmandry** [comment]
It makes sense to do this for consistency, but the inconsistency is so odd that I'd like to know more about how it came about.

Nonetheless,

@rfcbot reviewed

**Comment by RalfJung** [comment]
> the inconsistency is so odd that I'd like to know more about how it came 

My guess is that someone wanted to store a mutable array somewhere and filed a bug asking why that doesn't work, and then it was added as a very special case. Back in the day CTFE was extremely limited so this probably only allowed the syntactic form `static mut S = &mut [...];`. As CTFE became more powerful, the exception had to remain for backwards compatibility, but it became part of the larger const-check so e.g. suddenly `let x = &mut [...];` was allowed in `static mut` without anyone even thinking about that.

This [worked in Rust 1.0](https://rust.godbolt.org/z/fM6af1qq3) so the exact reasons will require some advanced code archeology, if they can still be recovered at all...

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this today and the consensus was to do this.  There is a proposed FCP that needs one more box checked at this point.  Let's remove the nomination for now.

**Comment by RalfJung** [comment]
I found the PR that added this:
https://github.com/rust-lang/rust/pull/12742
It fixes this issue:
https://github.com/rust-lang/rust/issues/11411
I wasn't able to find any further discussion. I guess we can just blame @nikomatsakis :joy:

**Comment by RalfJung** [comment]
@nikomatsakis @pnkfelix @scottmcm there are FCP boxes waiting for you here :)

**Comment by RalfJung** [comment]
@nikomatsakis @pnkfelix @scottmcm there are FCP boxes waiting for you here :)

**Comment by homersimpsons** [comment]
Note that this feature may be deprecated / removed in the future following https://github.com/rust-lang/rfcs/pull/3560

**Pull request merged**
