### PR TITLE
Fix #96847

### LINKED ISSUE #96847: internal error: entered unreachable code: in literal form when lowering mac args eq
I'm seeing an internal compiler error on the following input, found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc):

### Code

```rust
fn main() {
    for _ in [] {
        #![doc=""]
    }
}
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
warning: unused doc comment
 --> src/main.rs:3:9
  |
2 | /     for _ in [] {
3 | |         #![doc=""]
  | |         ^^^^^^^^^^
4 | |     }
  | |_____- rustdoc does not generate documentation for expressions
  |
  = note: `#[warn(unused_doc_comments)]` on by default
  = help: use `//` for a plain comment

thread 'rustc' panicked at 'internal error: entered unreachable code: in literal form when lowering mac args eq: Lit { token: Lit { kind: Str, symbol: "", suffix: None }, kind: Str("", Cooked), span: src/main.rs:3:16: 3:18 (#0) }', compiler/rustc_ast_lowering/src/lib.rs:903:17
```

This is not unique to `doc` attributes, it can be replaced by any other name, but I used `doc` in the example because I know it is imported by default. Affected versions: nightly 2022-05-07 is affected, but beta 1.61.0-beta.5 and stable 1.60.0 are not affected

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
warning: unused doc comment
 --> src/main.rs:3:9
  |
2 | /     for _ in [] {
3 | |         #![doc=""]
  | |         ^^^^^^^^^^
4 | |     }
  | |_____- rustdoc does not generate documentation for expressions
  |
  = note: `#[warn(unused_doc_comments)]` on by default
  = help: use `//` for a plain comment

thread 'rustc' panicked at 'internal error: entered unreachable code: in literal form when lowering mac args eq: Lit { token: Lit { kind: Str, symbol: "", suffix: None }, kind: Str("", Cooked), span: src/main.rs:3:16: 3:18 (#0) }', compiler/rustc_ast_lowering/src/lib.rs:903:17
stack backtrace:
   0:     0x7f7565767ead - std::backtrace_rs::backtrace::libunwind::trace::ha82e355503b775ae
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7565767ead - std::backtrace_rs::backtrace::trace_unsynchronized::h8e110267c4bde050
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7565767ead - std::sys_common::backtrace::_print_fmt::h5f563af01e258275
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f7565767ead - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hea5b1fa30c1333eb
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f75657c3b6c - core::fmt::write::h82dfb1eb62467416
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f75657595a1 - std::io::Write::write_fmt::h453cda435b3f142f
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/io/mod.rs:1655:15
   6:     0x7f756576abc5 - std::sys_common::backtrace::_print::hc8f28f28ca4dc2eb
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f756576abc5 - std::sys_common::backtrace::print::he50667b6c89ab0df
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f756576abc5 - std::panicking::default_hook::{{closure}}::hefe4dc9c157160a4
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:295:22
   9:     0x7f756576a839 - std::panicking::default_hook::h1376b5b10508fdef
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:314:9
  10:     0x7f7565f2bee1 - rustc_driver[5234e93807a03500]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f756576b396 - std::panicking::rust_panic_with_hook::h839908001643daf0
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:702:17
  12:     0x7f756576b197 - std::panicking::begin_panic_handler::{{closure}}::hf027c1af338d28cd
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:588:13
  13:     0x7f7565768364 - std::sys_common::backtrace::__rust_end_short_backtrace::h42726b9619ec7247
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f756576aec9 - rust_begin_unwind
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/panicking.rs:584:5
  15:     0x7f7565730193 - core::panicking::panic_fmt::hecbeff60ca345ea1
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/core/src/panicking.rs:142:14
  16:     0x7f7567621501 - <smallvec[783a7bc302c18e9d]::SmallVec<[rustc_ast[8c13dfba7c39903e]::ast::Attribute; 8usize]> as core[6c67f8de41fca20a]::iter::traits::collect::Extend<rustc_ast[8c13dfba7c39903e]::ast::Attribute>>::extend::<core[6c67f8de41fca20a]::iter::adapters::map::Map<core[6c67f8de41fca20a]::slice::iter::Iter<rustc_ast[8c13dfba7c39903e]::ast::Attribute>, <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_attrs::{closure#0}>>
  17:     0x7f75675f03ee - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::expr
  18:     0x7f75682f17c2 - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_expr_for
  19:     0x7f75675ebbfe - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_expr_mut::{closure#0}
  20:     0x7f75675e80f2 - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_stmts
  21:     0x7f75675f401d - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::lower_maybe_async_body
  22:     0x7f7567604da8 - <rustc_ast_lowering[840f68559e06d09a]::LoweringContext>::with_hir_id_owner::<<rustc_ast_lowering[840f68559e06d09a]::item::ItemLowerer>::with_lctx<<rustc_ast_lowering[840f68559e06d09a]::item::ItemLowerer>::lower_item::{closure#0}>::{closure#0}>
  23:     0x7f756762ad99 - <rustc_ast_lowering[840f68559e06d09a]::item::ItemLowerer>::lower_node
  24:     0x7f7567603adc - rustc_ast_lowering[840f68559e06d09a]::lower_crate
  25:     0x7f7567fdac17 - <rustc_interface[259f7f2d687dc9cd]::passes::boxed_resolver::BoxedResolver>::access::<rustc_interface[259f7f2d687dc9cd]::passes::create_global_ctxt::{closure#0}, &rustc_hir[a682107990697923]::hir::Crate>
  26:     0x7f7567fd0e43 - rustc_interface[259f7f2d687dc9cd]::passes::create_global_ctxt
  27:     0x7f7567ff415d - <rustc_interface[259f7f2d687dc9cd]::queries::Queries>::global_ctxt
  28:     0x7f7567f9d172 - <rustc_interface[259f7f2d687dc9cd]::interface::Compiler>::enter::<rustc_driver[5234e93807a03500]::run_compiler::{closure#1}::{closure#2}, core[6c67f8de41fca20a]::result::Result<core[6c67f8de41fca20a]::option::Option<rustc_interface[259f7f2d687dc9cd]::queries::Linker>, rustc_errors[473276f074908285]::ErrorGuaranteed>>
  29:     0x7f7567fc559f - rustc_span[e19c93a5cc4d231b]::with_source_map::<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_interface[259f7f2d687dc9cd]::interface::create_compiler_and_run<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#1}>
  30:     0x7f7567f9df44 - rustc_interface[259f7f2d687dc9cd]::interface::create_compiler_and_run::<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>
  31:     0x7f7567f9b6f2 - <scoped_tls[7f40d5f18d3a19f0]::ScopedKey<rustc_span[e19c93a5cc4d231b]::SessionGlobals>>::set::<rustc_interface[259f7f2d687dc9cd]::interface::run_compiler<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>
  32:     0x7f7567fb276f - std[da27fefd8cd19b64]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[259f7f2d687dc9cd]::util::run_in_thread_pool_with_globals<rustc_interface[259f7f2d687dc9cd]::interface::run_compiler<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>
  33:     0x7f7567fb28a9 - <<std[da27fefd8cd19b64]::thread::Builder>::spawn_unchecked_<rustc_interface[259f7f2d687dc9cd]::util::run_in_thread_pool_with_globals<rustc_interface[259f7f2d687dc9cd]::interface::run_compiler<core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>, rustc_driver[5234e93807a03500]::run_compiler::{closure#1}>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>::{closure#0}, core[6c67f8de41fca20a]::result::Result<(), rustc_errors[473276f074908285]::ErrorGuaranteed>>::{closure#1} as core[6c67f8de41fca20a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7f75657752e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd85bf70b078c05e8
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/alloc/src/boxed.rs:1872:9
  35:     0x7f75657752e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6a20ba204ab10b14
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/alloc/src/boxed.rs:1872:9
  36:     0x7f75657752e3 - std::sys::unix::thread::Thread::new::thread_start::h6522ecd8b15d879a
                               at /rustc/ea92b08383b718e79317b29470cb244c48557cd5/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7f75656a5609 - start_thread
  38:     0x7f75655be163 - clone
  39:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (ea92b0838 2022-05-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `playground` (bin "playground") generated 1 warning
error: could not compile `playground`; 1 warning emitted
```

</p>
</details>

### PR DESCRIPTION
**Pull request by nnethercote**
r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
The fix is simple, but I admit I don't understand why it's needed. This attribute gets lowered twice, with the second time now being a no-op. If I remove the loop the double lowering goes away.

**Comment by cjgillot** [comment]
I think that the double lowering happens in `rustc_ast_lowering/expr.rs`, line `1538`.  We should pass `e.attrs` directly to `expr_drop_temps_mut`.

**Comment by nnethercote** [comment]
Thanks, @cjgillot, you were right! Your punishment for this good deed:

r? @cjgillot 

:)

**Comment by nnethercote** [comment]
I changed the commit message on the second commit to reflect the change.

@bors r=cjgillot

**Comment by nnethercote** [comment]
Nominating for beta backport. It's an obscure bug unlikely to be hit by human-written code (the bug was found by a fuzzer) but the fix is simple enough that it might be worth getting it out 6 weeks earlier.

**Comment by pnkfelix** [comment]
[Discussed](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-08-18/near/294092661) at T-compiler meeting.

Declining to backport; the scope of this problem, from brief investigation, seems limited to inner attributes (`#![...]` not `#[...]`), and we think this can ride the trains.

**Comment by apiraino** [comment]
Beta backport declined as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-08-18/near/294092661)

@rustbot label -beta-nominated

**Pull request merged**
