### PR TITLE
[DO NOT MERGE] Use google cloud storage to cache docker images

### PR DESCRIPTION
**Pull request by emilyalbini**
Let's test how this goes.

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Yay, image upload worked, let's try downloading it now.

@bors retry

**Comment by TimNN** [comment]
Ping from triage, @pietroalbini: What is the status of this PR?

**Comment by pietroalbini** [comment]
We'll need to experiment with this a little further in the coming weeks.

**Comment by Centril** [comment]
Marking as "blocked" on experimentation.

**Comment by pietroalbini** [comment]
A little status update on this: we're probably going to merge this anyway, but we need to setup the bucket in a permanent location, and that's blocked on getting GCP setup.

**Comment by pietroalbini** [comment]
Let's close this in the meantime.

**Pull request closed without merging**
