### PR TITLE
Automatically make trivial types noop-traversable

### PR DESCRIPTION
**Pull request by eggyal**
This is a second reincarnation of #108214 (or at least, what that PR ultimately became), the previous reincarnation in #117620 having been closed accidentally.  It may be easier to review by commit, albeit there are quite a few of them.

## Terminology

I refer to:
* folds and visits as "traversals"
* the types that are folded or visited as "traversables"
* the folders and visitors as "traversers"
* traversables on which traversers can act as "interesting" (there are currently only five: binders, types, consts, regions and predicates) and all others as "trivial" (traversals of which are no-ops)
* the `TypeFoldable` and `TypeVisitable` traits (and only these traits) as the "traversable traits"

## Content

This PR:

* introduces a macro, `rustc_type_ir::noop_if_trivially_traversable` that uses [auto-deref specialisation](http://lukaskalbertodt.github.io/2019/12/05/generalized-autoref-based-specialization.html) to:
    * perform a no-op traversal on values of type `T` if the interner implements `rustc_type_ir::TriviallyTraverses<T>` (thereby obviating all need for most trivial types to implement the traversable traits—and indeed such implementations are removed) or
    * delegate to the relevant traversable trait implementation on `T` otherwise;
* introduces an auto-trait, `rustc_middle::ty::TriviallyTraversable`, that is then "unimplemented" on the interesting types (and thereby remains implemented only on, but on all, trivial types);
* implements `rustc_type_ir::TriviallyTraverses<T>` on the `TyCtxt<'tcx>` interner for all `T: rustc_middle::ty::TriviallyTraversable` (thus ensuring that, for that interner at least, trivial types do not require implementations of the traversable traits);
* updates the traversable traits' derive macros to:
    * skip fields that reference neither any generic type parameters nor, if present, the `'tcx` lifetime parameter
    * use the above specialisation macro when traversing fields
    * if the traversable is not parameterised by a `'tcx` lifetime, generate implementations that are generic over the interner;
* replaces those derive macros' distinct helper attributes (introduced in #108040) with a unified `#[skip_traversal]` helper attribute that requires a justifying reason to be provided (this does mean that the different types of traversal can no longer be independently skipped, but nowhere is that currently required or ever expected to be);
    * the derive macros by default refuse to be implemented on trivial types as specialisation usually negates any need—but this can be overridden with a `#[skip_traversal(impl_despite_trivial_because = "<reason>")]` attribute;
* uses those derive macros in place of remaining usages of the `TrivialTypeTraversal` macros and some explicit implementations; and
* a few other minor relevant refactorings.

## Commentary

One limitation of auto-deref specialisation is that it cannot work for unconstrained generic types.  Therefore, absent real specialisation, implementations of the traversable traits must constrain their generics:
* by default, the derive macros constrain every field type `T` that references one or more generic type parameters to implementors of the relevant traversable trait—however this can be modified on a field (or variant) basis with a `#[skip_traversal(because_trivial)]` attribute so that instead the interner is constrained to implement `TriviallyTraverses<T>` (and the field is not traversed)
    * the constraints are applied to the field types rather than the generic type parameters to achieve a "[perfect derive](https://smallcultfollowing.com/babysteps/blog/2022/04/12/implied-bounds-and-perfect-derive/)" that not only avoids having to propagate `#[skip_traversal]` annotations into wrapping types but also works with associated types and other esoteric situations—however this could result in trait solver cycles if interesting generic field types are one day involved in recursive type definitions;
    * for exceptionally rare cases where traversal of an item/variant/field should be a no-op despite it being (potentially, if generic) interesting, it can be annotated with the explicit and deliberately cumbersome `#[skip_traversal(despite_potential_miscompilation_because = "<reason>")]` (which produces a no-op without adding any constraint).
* (the few remaining) explicit implementations of the traversable traits over generic types are similarly constrained
    * indeed, for generic tuples *all element types* must implement the trait—however, since (most) trivial types no longer do, this unfortunately means that the implementations are not applicable to tuples with trivial elements and hence some such tuples have been replaced with more concrete newtypes that have appropriate constraints: c5e9447d5fde4971c12250f18ee853b645522869 is a particularly hefty example of this (where tuples containing `Span` are replaced with `Spanned<T>` instead).

r? @lcnr
cc @oli-obk

@rustbot label A-query-system T-compiler WG-trait-system-refactor

### CODE REVIEW

**Comment by lcnr** [comment]
if there are conflicts, feel free to only rebase once I've reviewed it

**Comment by eggyal** [comment]
Sure.  Will wait until you've reviewed before pushing anything else.  You may want to try that perf run now before any conflicts arise?

**Comment by lcnr** [comment]
@rust-timer build 793a8bf6d82bf779eead11e22a6dad04873c5342

**Comment by eggyal** [comment]
I'll try and look into the perf regression over the weekend.

One thing that I should perhaps highlight is that, in order to support safe derivation of the traversable traits upstream of `rustc_middle` (therefore over generic interners, absent the `TriviallyTraverses` impl from the auto-trait), the derive macro itself now makes an initial determination (on syntax alone) that a type is *guaranteed* to be trivial if it references neither generic type parameters nor a `'tcx` lifetime (on the basis that without some handle on the interner, it won't contain anything of interest).

Also, since auto-deref specialisation doesn't work for generic types (generics must be constrained to use either a trivial or a non-trivial traversal), the only time that specialisation is now needed is when traversing a field that does not reference any generic type parameters but that does reference a `'tcx` lifetime.  It may be worth exploring how many of these are actually trivial, as if there are very few then perhaps the complexity of the specialisation machinery isn't justified?  (The auto-trait would nevertheless remain to constrain impls so that `#[skip_traversal]` attributes cannot be unintentionally misused).

Accordingly, I think this PR could be split into a number of smaller ones; for example:
- syntactically detect & skip trivial types in the derive macro, use derive macro in trivial cases, remove superfluous impls
- (if still required, add specialisation and remove further superfluous impls)
- add auto-trait and `#[skip_traversal]` attribute, use derive macros in newly-supported cases
- make derivations generic over interner (where possible) and use upstream of `rustc_middle`
- other refactorings

This could make review easier and help to identify the source of the perf regression... let me know if you'd like me to take a crack at it.

**Comment by lcnr** [comment]
> the derive macro itself now makes an initial determination (on syntax alone) that a type is *guaranteed* to be trivial if it references neither generic type parameters nor a `'tcx` lifetime (on the basis that without some handle on the interner, it won't contain anything of interest).

People sometimes use non `'tcx` lifetimes for interned lifetimes, so I would change the rule to simply be "no type or non-static lifetime params".

I think splitting the work over multiple self-contained PRs is helpful if possible. So feel free to go ahead. Will hold off reviewing this PR in that case.

**Comment by eggyal** [comment]
Presence of a `'tcx` lifetime is already used to determine whether the derived impl is generic over the interner or only for `TyCtxt<'tcx>`.  Indeed, I'm pretty sure all cases where a lifetime other than `'tcx` is currently used are indeed trivial (as I don't think a previous iteration would have compiled if not)—but I'll check on that.

Will go ahead and split this monster up.

@rustbot author

**Comment by eggyal** [comment]
Okay, I have reworked this into 8 upcoming PR's—but since some build on others, I'm not sure how best to post them.  Shall I open one at a time, waiting for each to merge before opening the next?  Or shall I open them all at once, each based off its predecessor and therefore automatically rolling forward with master but risking confusion/excess review work if considered out of order?

**Comment by JohnCSimon** [comment]
Triage: 
@eggyal I guess this PR is still active.

**Comment by Dylan-DPC** [comment]
Closing this as it is being split into parts with https://github.com/rust-lang/rust/pull/117896 being the first part

**Pull request closed without merging**
