### PR TITLE
Remove eval_always for privacy.

### PR DESCRIPTION
**Pull request by cjgillot**
Split off #86056
r? @ghost

### CODE REVIEW

**Comment by Aaron1011** [comment]
@cjgillot: The performance still looks somewhat mixed. Could you try running perf builds where only one of `privacy_access_levels` and `check_private_in_public` is changed at a time?

**Comment by apiraino** [comment]
Does this need another spin of `@rust-timer` to test again performance diff?

**Comment by apiraino** [comment]
switching to waiting on PR author (as I think it reflects the current status), but please flip the switch if it's not the case

@rustbot author

**Pull request closed without merging**
