### PR TITLE
Re-export NonZero signed variant in std

### LINKED ISSUE #59834: NonZero signed variants not available in std
The `NonZero` signed variants are not re-exported in `std` here: https://github.com/rust-lang/rust/blob/master/src/libstd/num.rs#L15

We should duplicate that line and re-export them.

cc @rust-lang/release @rust-lang/libs -- this will likely slip into 1.34, but we will backport the fix into 1.35

### PR DESCRIPTION
**Pull request by tesuji**
Closes  #59834 .

### CODE REVIEW

**Comment by lzutao** [comment]
Try the triage bot
@rustbot modify labels: T-libs

**Comment by Mark-Simulacrum** [comment]
@bors r+

Cc @pietroalbini @rust-lang/release

**Comment by pietroalbini** [comment]
@bors r-

Legit.

**Comment by pietroalbini** [comment]
This will need to be backported to beta since it's landing on stable.

**Comment by pietroalbini** [comment]
This has been cherry-picked both on stable 1.34 and beta 1.35.

**Pull request merged**
