### PR TITLE
Added submodule fetch instructions.

### PR DESCRIPTION
**Pull request by krk**

### CODE REVIEW

**Comment by varkor** [comment]
This shouldn't be necessary, because `x.py` automatically fetches and updates the submodules each time it's run.

**Comment by krk** [comment]
It didn't work for me on Windows 10 x64, `x.py` complained that `src\tools\clippy` is empty. 

After fetching the submodules, x.py can display `--help`.

**Comment by pietroalbini** [comment]
Thanks for this PR! Seems strange that doesn't work on Windows... (also highfive failed to assign a reviewer, picking one randomly)

cc @retep998 
r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I can reproduce this on non-windows, it seems that perhaps Cargo has recently(?) started examining toml files on `cargo build` that aren't the ones passed via `manifest-path`... @alexcrichton / @matklad Any thoughts on whether that's the case?

**Comment by ehuss** [comment]
I've noticed that since #48569 that you can't run `x.py --help` on a fresh checkout because of this:

https://github.com/rust-lang/rust/blob/989b25718bbfdcc5615cdc5880e5573eb8b9688f/src/bootstrap/bootstrap.py#L771-L774

Cargo can't build `bootstrap` because it is part of the workspace, and the submodules are missing.

Maybe that check is no longer necessary since #49057 has landed?

**Comment by matklad** [comment]
>I can reproduce this on non-windows, 

@Mark-Simulacrum this works for me on Linux:


```
~/trash
λ g clone https://github.com/rust-lang/rust                                                                                          ~/trash
Cloning into 'rust'...
remote: Counting objects: 770444, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 770444 (delta 2), reused 2 (delta 0), pack-reused 770435
Receiving objects: 100% (770444/770444), 344.99 MiB | 9.29 MiB/s, done.
Resolving deltas: 100% (622321/622321), done.

~/trash 1m 4s
λ cd rust                                                                                                                            ~/trash

~/trash/rust master
λ ./x.py build
...
Updating submodule src/tools/cargo
Submodule 'src/tools/cargo' (https://github.com/rust-lang/cargo.git) registered for path 'src/tools/cargo'
Cloning into '/home/matklad/trash/rust/src/tools/cargo'...
Submodule path 'src/tools/cargo': checked out '311a5eda6f90d660bb23e97c8ee77090519b9eda'
...
```


What is exactly the error are you seeing? It's hard to figure out what is from from the issue description, and I it works for me on Linux :)

**Comment by Mark-Simulacrum** [comment]
@krk Could you let us know what you are seeing that goes wrong? We can't seem to reproduce (my previous comment turned out to not actually be the case).

**Comment by ollie27** [comment]
The issue occurs when running `x.py --help`with no submodules checked out:

```
> python x.py --help --verbose
info: Downloading and building bootstrap before processing --help
      command. See src/bootstrap/README.md for help with common
      commands.
running: C:\Source\rust_test\build\x86_64-pc-windows-msvc\stage0\bin\cargo.exe build --manifest-path C:\Source\rust_test\src/bootstrap/Cargo.toml
error: failed to read `C:\Source\rust_test\src\tools\clippy\Cargo.toml`

Caused by:
  The system cannot find the file specified. (os error 2)
Traceback (most recent call last):
  File "x.py", line 20, in <module>
    bootstrap.main()
  File "C:\Source\rust_test\src\bootstrap\bootstrap.py", line 800, in main
    bootstrap(help_triggered)
  File "C:\Source\rust_test\src\bootstrap\bootstrap.py", line 780, in bootstrap
    build.build_bootstrap()
  File "C:\Source\rust_test\src\bootstrap\bootstrap.py", line 606, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "C:\Source\rust_test\src\bootstrap\bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: C:\Source\rust_test\build\x86_64-pc-windows-msvc\stage0\bin\cargo.exe build --manifest-path C:\Source\rust_test\src/bootstrap/Cargo.toml
```

**Pull request closed without merging**
