### PR TITLE
PGO - Add a smoketest for combining PGO with cross-language LTO.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR

- Adds a test making sure that PGO can be combined with cross-language LTO.
- Does a little cleanup on how the `pgo-use` flag is handled internally.
- Makes the compiler error if the `pgo-use` file given to `rustc` doesn't actually exist. LLVM only gives a warning and then just doesn't do PGO. Clang, on the other hand, does give an error in this case.
- Makes the build system also build `compiler-rt` when building LLDB. This way the Clang compiler that we get from building LLDB can perform PGO, which is something that the new test case wants to do. CI compile times shouldn't be affected too much.

### CODE REVIEW

**Comment by Centril** [comment]
@bors p=1

Possible cause of failure https://github.com/rust-lang/rust/pull/61178#issuecomment-495920214 but unsure; prioritizing to find out quickly.

**Comment by michaelwoerister** [comment]
This doesn't look spurious. It seems that macOS has trouble building LLVM? I'll try to reproduce locally.

**Comment by michaelwoerister** [comment]
It looks like `compiler-rt` is built for all targets (e.g. also iOS) and that doesn't seem to quite work everywhere.

**Comment by michaelwoerister** [comment]
The last commit makes rustbuild only add `compiler-rt` to `LLVM_ENABLE_PROJECTS` when it's needed for testing.

@bors r=alexcrichton

**Comment by michaelwoerister** [comment]
Compilation error fixed.
@bors r=alexcrichton

**Pull request merged**
