### PR TITLE
Rollup of 16 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #97015 (std::io: migrate ReadBuf to BorrowBuf/BorrowCursor)
 - #98301 (Add GDB/LLDB pretty-printers for NonZero types)
 - #98801 (Add a `File::create_new` constructor)
 - #99696 (Uplift `clippy::for_loops_over_fallibles` lint into rustc)
 - #100337 (Stabilize `std::io::read_to_string`)
 - #100437 (Improve const mismatch `FulfillmentError`)
 - #100640 (Use `DisplayBuffer` for socket addresses.)
 - #100885 (Export Cancel from std::os::fortanix_sgx::usercalls::raw)
 - #100898 (Do not report too many expr field candidates)
 - #100955 (Some papercuts on error::Error)
 - #100959 (translations: rename warn_ to warning)
 - #101002 (Provide structured suggestion for `hashmap[idx] = val`)
 - #101055 (Use smaller span for suggestions)
 - #101091 (Extend attrs if local_def_id exists)
 - #101098 (rustc_middle: Remove `Visibility::Invisible`)
 - #101102 (unstable-book-gen: use std::fs::write)

Failed merges:

 - #100970 (Allow deriving multipart suggestions)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=97015,98301,98801,99696,100337,100437,100640,100885,100898,100955,100959,101002,101055,101091,101098,101102)

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Hm, we may need to r- all pending stabilization PRs until they're updated with the new syntax.

**Comment by matthiaskrgr** [comment]
est31 already left a comment on the stab pr, I r-'d it now.

**Pull request closed without merging**
