### PR TITLE
Format linker args in a way that works for gcc and ld

### PR DESCRIPTION
**Pull request by alecmocatta**
Pass multiple linker arguments rather than concatenate with commas (fixes #52634).

`-l library` -> `-llibrary` to work with apple's ld.

To build with apple's ld I'm currently also passing `-C link-args="-arch x86_64 -macosx_version_min 10.13.0"`. I'll try and understand the latter flag better before PRing that.

This PR currently works for me. Hopefully CI will pick up any grievous ramifications in other toolchains?

Thanks to @alexcrichton for the pointer to the relevant code!

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors r+

Thanks!

**Comment by RalfJung** [comment]
> This PR currently works for me. Hopefully CI will pick up any grievous ramifications in other toolchains?

Of course, since this doesn't change CI, if someone else hopes for the same thing again later it might break again for you. :/  I appreciate it is hard to test for these things though. But maybe some comments would be a good idea?

**Comment by alecmocatta** [comment]
@RalfJung Agreed. I'll follow up with a PR once I've tested on a few macOS versions, adding in the aforementioned missing flags for Apple's ld, as well as commenting my understanding of its idiosyncrasies.

**Pull request merged**
