### PR TITLE
Update stdsimd

### PR DESCRIPTION
**Pull request by gnzlbg**
This updates stdsimd to a Rust2015 / Rust2018 compatible version. Once this is merged it should be possible to migrate libcore and libstd to Rust2018. Once that happens, we can just require the 2018 edition in stdsimd.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

higher priority b/c this is likely to bounce a few times and it'd be good to weed that out

**Comment by gnzlbg** [comment]
> higher priority b/c this is likely to bounce a few times and it'd be good to weed that out

So I tried it locally, but not for arm / aarch64 / etc. and the recent ACLE changes might still need some ironing.

**Comment by gnzlbg** [comment]
So I can't reproduce this locally, I get a SIGSEV trying to build the docs.

@bors: r-

**Comment by mati865** [comment]
@gnzlbg you can try with Docker image that failed on Travis.
In the Rust checkout run:
```sh
# depending on system configuration it may require `sudo`
./src/ci/docker/run.sh x86_64-gnu-llvm-6.0 
```

**Comment by gnzlbg** [comment]
Do they run on macos?

**Comment by mati865** [comment]
I don't have Mac and I don't know how Docker works there (it allows running Linux via VM?).
If other Linux based Docker images work then this one should be good.

**Comment by gnzlbg** [comment]
@QuietMisdreavus i've pushed a fix that might cause the aarch64 to contain docs of arm intrinsics and vice-versa, i don't know the best way to fix that. 

Basically, the arm and aarch64 docs include the ACLE docs, where ACLE has some intrinsics that are only for arm, and some for aarch64, and some for both. When compiling all targets with `--cfg dox`, both modules include all of the acle module. AFAICT there is no way to state "this submodule should only include docs for items defined for target X". 

One could manually import everything from acle manually into the arm and aarch64 submodules, but ACLE is such a mess that this is, at this moment, not really feasible. Maybe when ACLE is fully implemented, we can do this once. 

cc @alexcrichton @centril this should be ready2go

**Comment by Centril** [comment]
Unblocks other work on edition migration; thus: @bors p=5

**Comment by gnzlbg** [comment]
@Centril something failed, I don't know what or why, but it appears spurious.

**Comment by QuietMisdreavus** [comment]
```
[02:03:02] 12 command(s) did not execute successfully:
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/c-tips/index.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/collections/index.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/concurrency/index.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/interoperability/c-with-rust.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/peripherals/singletons.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/start/exceptions.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/start/hardware.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/start/panicking.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/start/qemu.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/start/registers.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/embedded-book/src/start/semihosting.md" "--test-args" ""
[02:03:02] 
[02:03:02]   - "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/rls/Cargo.toml"
```

Looks like the embedded book and the RLS failed to pass tests? Not totally sure the connection, but the test output logs are farther up the log.

**Comment by gnzlbg** [comment]
The raw logs are a pain to read: 

> [00:07:37] [0m[0m[1m[32m ...

And there are 305 occurences of error in the raw log. I went through most of them (so many its hard to tell if I missed any or not), and haven't found anything related to `stdsimd` =/

Looking for `test result: FAIL` reveals only 12 issues, but they also seem unrelated to `stdsimd`. 

Does anybody have an idea about what's going on? Maybe this is just a spurious failure.

**Comment by mati865** [comment]
embedded book fails all over the place like here:
```
[01:22:48] ---- /checkout/src/doc/embedded-book/src/c-tips/index.md - Tips_for_embedded_C_developers::Iterators_vs_Array_Access (line 183) stdout ----
[01:22:48] error[E0425]: cannot find function `process` in this scope
[01:22:48]  --> /checkout/src/doc/embedded-book/src/c-tips/index.md:186:5
[01:22:48]   |
[01:22:48] 5 |     process(*element);
[01:22:48]   |     ^^^^^^^ not found in this scope
[01:22:48] 
[01:22:48] thread '/checkout/src/doc/embedded-book/src/c-tips/index.md - Tips_for_embedded_C_developers::Iterators_vs_Array_Access (line 183)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:351:13
[01:22:48] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:22:48] 
[01:22:48] ---- /checkout/src/doc/embedded-book/src/c-tips/index.md - Tips_for_embedded_C_developers::Preprocessor::Compile_Time_Sizes_and_Computation (line 78) stdout ----
[01:22:48] error: incorrect close delimiter: `]`
[01:22:48]  --> /checkout/src/doc/embedded-book/src/c-tips/index.md:82:38
[01:22:48]   |
[01:22:48] 6 |     #[cfg(not(feature="use_more_ram")]
[01:22:48]   |      -   -                           ^ incorrect close delimiter
[01:22:48]   |      |   |
[01:22:48]   |      |   un-closed delimiter
[01:22:48]   |      close delimiter possibly meant for this
[01:22:48] 
[01:22:48] thread '/checkout/src/doc/embedded-book/src/c-tips/index.md - Tips_for_embedded_C_developers::Preprocessor::Compile_Time_Sizes_and_Computation (line 78)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:351:13
[01:22:48] 
[01:22:48] ---- /checkout/src/doc/embedded-book/src/c-tips/index.md - Tips_for_embedded_C_developers::Volatile_Access (line 262) stdout ----
[01:22:48] error[E0658]: The attribute `interrupt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
[01:22:48]  --> /checkout/src/doc/embedded-book/src/c-tips/index.md:265:3
[01:22:48]   |
[01:22:48] 5 | #[interrupt]
[01:22:48]   |   ^^^^^^^^^
[01:22:48]   |
[01:22:48]   = help: add #![feature(custom_attribute)] to the crate attributes to enable
[01:22:48] 
[01:22:48] error[E0425]: cannot find function `run_task` in this scope
[01:22:48]   --> /checkout/src/doc/embedded-book/src/c-tips/index.md:280:9
[01:22:48]    |
[01:22:48] 20 |         run_task();
[01:22:48]    |         ^^^^^^^^ not found in this scope
[01:22:48] 
[01:22:48] thread '/checkout/src/doc/embedded-book/src/c-tips/index.md - Tips_for_embedded_C_developers::Volatile_Access (line 262)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:351:13
[01:22:48] 
```

I don't want to post RLS error here because it's huge and spurious.

Neither or them should be affected by this PR.

**Comment by gnzlbg** [comment]
@Centril @alexcrichton can we give this another try ?

**Pull request merged**
