### PR TITLE
Revert Replace ASCII control chars with Unicode Control Pictures

### PR DESCRIPTION
**Pull request by oli-obk**
reverts #127528 as that was a perf regression

r? @estebank

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors r+

I'd like to see this code re-landed in a way that's more efficient, since the improvement to diagnostics is quite nice. This is worth probably a spin-off discussion about how diagnostics formatting code affects the good path in the case of lints and warnings.

**Comment by estebank** [comment]
I'm honestly a bit shocked that it *had* a perf regression (as it only affected rendering...)

**Comment by compiler-errors** [comment]
See the discussion at https://github.com/rust-lang/rust/pull/128169#issuecomment-2250187140 for more info, if you haven't already

**Comment by estebank** [comment]
@compiler-errors thanks, catching up

**Comment by estebank** [comment]
I suspect that the culprit is https://github.com/rust-lang/rust/pull/128200/files#diff-a35029c589a6b5b002ecf598efb24d174232e719ecbc6f741a58eee8509cd6a5L2612-L2614

**Comment by compiler-errors** [comment]
@bors r-

Let's give this a tiny bit of time to let Esteban fix the perf w/o a full revert.

**Pull request closed without merging**
