### PR TITLE
submodules: update clippy from d8e6e4cf to 1ff81c1b

### LINKED ISSUE #70310: `clippy-driver` no longer builds after rust-lang/rust#70305
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#70305, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Changes:
````
rustup https://github.com/rust-lang/rust/pull/69968/
Fix documentation generation for configurable lints
Fix single binding in closure
Improvement: Don't show function body in needless_lifetimes
````
Fixes #70310
r? @Dylan-DPC

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@Dylan-DPC  can you also bump prio to 1? ^^

**Comment by Dylan-DPC** [comment]
I was intending to that later when I check the queue. 

@bors p=1

**Comment by matthiaskrgr** [comment]
Oh ok, my bad. :)

**Pull request merged**
