### PR TITLE
Warn for outlives lint when gats are enabled for non-gats

### PR DESCRIPTION
**Pull request by jackh726**
Based on #91849

The basic idea is that having a where clause allows more flexibility, as with GATs. We can't error, because of backwards compatibility.

I think this needs further discussion before merge, but opening this for that discussion.

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]
coding wise, r+ from me

**Comment by nikomatsakis** [comment]
@jackh726 I'm wondering if we should rebase, make this deny-by-default, and do a crater run

**Comment by nikomatsakis** [comment]
I think that would be the best way to move forward here. It'd be useful to have some data on what's affected and to see how many "false warnings" we get.

**Comment by jackh726** [comment]
I'll do that this weekend. Crater queue is a bit long right now, but I dont think this is time-sensitive at all.

**Comment by Dylan-DPC** [comment]
@jackh726 what's the update on this?

**Comment by jackh726** [comment]
I need to rework this a bit. It's on my list of things, but not a priority.

**Pull request closed without merging**
