### PR TITLE
fix error code in E0751.md

### PR DESCRIPTION
**Pull request by contrun**
reference: https://github.com/rust-lang/rust/issues/71304

### CODE REVIEW

**Comment by JohnTitor** [comment]
The issue is not just the annotation but also that code emits E0748 in actual.

**Comment by estebank** [comment]
☝️ Fixing #71304 requires not only changing the test, but rather making that code emit the right error.

**Comment by contrun** [comment]
Thanks. I thought it was just the annotation. I will change the code.

**Comment by pnkfelix** [comment]
discussed at this weeks [T-compiler meeting](festehttps://zulip-archive.rust-lang.org/131828tcompiler/05709weeklymeeting2020043054818.html#195844425).

at the time, we declined to accept for backport.

but further discussion with @estebank led me to rethink that outcome.

(We knew it was very low risk; we just didn't understand what the supposed gain was until estebank [pointed out](festehttps://zulip-archive.rust-lang.org/131828tcompiler/05709weeklymeeting2020043054818.html#195844425) that the publicly posted docs would carry the incorrect number, which is not hidden by any part of our nightly/stability firewall.)

So I am going to unilaterally beta-accept based on that outcome. This will also serve as an example of a new policy going forward, where very low-risk beta-nominated issues can be unilaterally beta-accepted by a T-compiler lead (and we will just announce such beta-acceptances at the meeting, which I am now doing by marking this as I-nominated.)

**Pull request merged**
