### PR TITLE
Add x86_64-unknown-linux-gnux32 target

### PR DESCRIPTION
**Pull request by malbarbo**
This adds X32 ABI support for Linux on X86_64. Let's package and dist it so we can star testing libc, libstd, etc.

Fixes https://github.com/rust-lang/rfcs/issues/1339

### CODE REVIEW

**Comment by malbarbo** [comment]
Add the target build to cross2 because it seems to have some free time.

**Comment by malbarbo** [comment]
Why this target is important?

> Compared to amd64, x32 offers significant memory savings, often on the order of 30%, and modest efficiency gains.
> 
> Compared to i386, there's no memory use difference, but speed increases are more pronounced, especially in code that's under register pressure, operates on 64-bit or floating-point variables. It also avoids i386's penalty for PIC code, where EBX is essentially reserved for the Global Offset Table (GOT).
>
> There are three principal use cases:
>
> - vserver hosting (memory bound)
> - netbooks/tablets (low memory, want performance)
> - scientific tasks (want every % of performance)  

From [Debian X32 port](https://wiki.debian.org/X32Port).

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
