### PR TITLE
Use Self over specific type in return position

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Comment by petrochenkov** [comment]
`Self` in non-generic/macro positions is harmful for code readability and searchability.

**Comment by joshtriplett** [comment]
@petrochenkov I personally tend to find it an improvement. Searching should turn up the `impl TypeName` block that the methods appear in. And for readability, I find it easier to evaluate a type at a glance when it contains `Self`:

`-> Self`: a constructor
`-> &mut Self`: a method that supports chaining, such as a builder method

**Comment by Centril** [comment]
I agree with @joshtriplett. In particular, it's even better in rustdoc to see `Self` to the reasons aforementioned.

**Pull request merged**
