### PR TITLE
Remove Spans from HIR

### PR DESCRIPTION
**Pull request by cjgillot**
This PR is an experiment in removing the Span information from the HIR tree.
I plan to submit a MCP if this PR is considered relevant.

The spans are stored in a side table, indexed by `HirId`, and constructed during lowering.
A dedicated query is created to retrieve those spans.

Subsequent commits gradually remove spans from HIR nodes.
Those are quite mechanical, and don't deserve close examination before the MCP is accepted.

The point of this PR is to limit HIR invalidation due to span info changing.
At this stage, there are still a lot of spans in the HIR. 
I do not think we will see benefits while there are some.

Anyway, I would like to get a few comment wrt. the soundness of the approach.

### CODE REVIEW

**Comment by varkor** [comment]
Not sure who's most appropriate to review. Maybe r? @petrochenkov?

**Comment by cjgillot** [comment]
cc #47389.

**Comment by petrochenkov** [comment]
Spans that are not in `Ident`s should mostly be used for diagnostics in case of errors so it shouldn't be a performance issue it they are moved to a side table (there may be exceptions, I'm not sure).

If this allows to not hash spans in most cases and hash them only in rare cases in which they are really needed, then this should be an improvement.
I don't really understand how incremental works in detail, so I can't give any design advice besides that.

r? @nikomatsakis because you mentioned this recently in https://github.com/rust-lang/rust/issues/51003#issuecomment-626727258

**Comment by nikomatsakis** [comment]
Interesting! So, to make sure I understand the approach:

* Create a map (during lowering) from HirId -> Span during HIR lowering
* Remove the spans from the HIR itself (or, presumably, most spans -- maybe some HIR nodes have multiple spans)
* Create a query `span_of(HirId)` (say) that returns the span for a given `HirId`

I think an MCP would be most appropriate, yes. I also suspect that @pnkfelix is the right reviewer, as he's been interested in getting more involved in this area, but I'll let him volunteer if he feels he has time.

**Comment by pnkfelix** [comment]
@cjgillot Do we have metrics for how much (if any) invalidation this eliminates?

(As you said a lot of spans still remain, I wouldn't be surprised if the net change is approximately zero. But I am still curious whether we can easily gather data here.)

**Comment by cjgillot** [comment]
I have no idea how to gather such data. A possibility would be a perf run, and look at the "println incremental" lines. Does perf handle comparing "clean incremental" and "println incremental"?

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

Well, a perf run certainly can't hurt -- and since CI seems to be passing might as well try it out.

**Comment by cjgillot** [comment]
Rebased.

**Comment by cjgillot** [comment]
@Mark-Simulacrum, can you call out perf once again? Thanks.

**Comment by Mark-Simulacrum** [comment]
@bors try

Perf should appear once the try build is done, it listens indefinitely until a successful try build completes :)

**Comment by cjgillot** [comment]
HIR lowering regresses by 80% on many benchmarks. Query execution count has not changed.

**Comment by nikomatsakis** [comment]
Oof, that's quite a hit. Interesting.

**Comment by cjgillot** [comment]
Can I get a perf run on this? Thanks.

**Comment by cjgillot** [comment]
The HIR lowering regression appears to be mitigated. The performance diff is now located on all the other queries. For a very few cases, the query count is lower, and compilation is faster. For the rest, the query count is unchanged, and compilation is slower: it takes more work to get the spans.

**Comment by Muirrum** [comment]
@cjgillot What's the status of this PR? There are outstanding merge conflicts.

**Comment by bjorn3** [comment]
Mostly regressions of up to 7.8%. Three improvements of up to 12% for patched incremental benches.

**Comment by jackh726** [comment]
@cjgillot Is this waiting for a review or do you plan to do more here?

**Comment by cjgillot** [comment]
@jackh726 I believe this PR is not the right solution for the issue of span invalidation.

**Pull request closed without merging**
