### PR TITLE
Document `diagnostic_namespace` feature

### PR DESCRIPTION
**Pull request by mejrs**
This adds it to the rust unstable book.

FWIW: I couldn't find a way to serve the book locally (please send help), so I can't check that this renders correctly.

cc @weiznich

### CODE REVIEW

**Comment by fmease** [comment]
Did you try `mdbook serve` while you are in the directory of the book?

**Comment by mejrs** [comment]
> Did you try `mdbook serve` while you were in the directory of the book?

That was the first thing i tried, but it gave 
```
2023-10-10 21:18:08 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "C:\\Users\\bruno\\Rust\\rust\\src\\doc\\unstable-book\\src" directory
2023-10-10 21:18:08 [ERROR] (mdbook::utils):    Caused By: The system cannot find the file specified. (os error 2)
```

**Comment by fmease** [comment]
Hmm, I guess `boostrap` generates the `SUMMARY.md`. I should probably leave this question for someone else to answer, how you could try to use `./x b <path/to/book>` or a variation thereof.

**Comment by ehuss** [comment]
To build the documentation, you need to run `./x.py doc src/doc/unstable-book --open`. We don't have support for automatically rebuilding the book.

There's a little bit of documentation on this at https://rustc-dev-guide.rust-lang.org/contributing.html#writing-documentation, but that isn't very discoverable. We should probably add something somewhere to point that out.

Thanks for adding this!

@bors r+ rollup

**Comment by ehuss** [comment]
Oops, forgot the example needs to compile.

@bors r-

I think the code block needs something like `rust,compile_fail,E0277`

You can test it with `./x.py test src/doc/unstable-book`

**Comment by ehuss** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
