### PR TITLE
Delete deprecated & unstable range-specific `step_by`

### LINKED ISSUE #41477: Incorrect lower bound from StepBy<A, RangeInclusive<A>>::size_hint
Repro: https://is.gd/nFIian (tried 2017-04-21)
```
#![feature(step_by)]
#![feature(inclusive_range_syntax)]

fn main() {
    let i = (0...10).step_by(3);
    assert!(i.size_hint().0 <= i.count());
}
```

Looks like the implementation is adding one to the Range (exclusive) lower bound, which is incorrect when the size of the base range isn't a multiple of the step.

Thoughts on whether it'd be a better fix to just not add one (correct, but a less-helpful hint) or to add one to end before calling `Step::steps_between` (better hint, more math and more overflow cases)?

### PR DESCRIPTION
**Pull request by scottmcm**
Using the new one is annoying while this one exists, since the inherent method hides the one on iterator.

Tracking issue: #27741
Replacement: #41439
Deprecation: #42310 for 1.19
Fixes #41477

### CODE REVIEW

**Comment by leonardo-m** [comment]
See also #43063

**Comment by SimonSapin** [comment]
This is blocking Servo from upgrading Rust until we find a work around :/ `Iterator:step_by` is not a full replacement since it cannot support negative steps, and `.rev()` produces a different type. We have code that conditionally returns an iterator with positive or negative step.

**Comment by SimonSapin** [comment]
This was pointed out in https://github.com/rust-lang/rust/issues/27741#issuecomment-305968988 when `Range::step_by` was deprecated.

**Comment by SimonSapin** [comment]
I ended up making this type. Would something like it belong in `std`?

```rust
struct MaybeReverse<I> {
    iter: I,
    reverse: bool,
}

impl<I: DoubleEndedIterator> Iterator for MaybeReverse<I> {
    type Item = I::Item;

    fn next(&mut self) -> Option<I::Item> {
        if self.reverse {
            self.iter.next_back()
        } else {
            self.iter.next()
        }
    }
}
```

**Pull request merged**
