### PR TITLE
Module doc examples

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I was going through the libcore and adding missing code examples when I realized the lint was mostly complaining about modules. In my opinion, forcing modules to have code examples doesn't make sense.

What do you think @rust-lang/rustdoc ?

### CODE REVIEW

**Comment by jyn514** [comment]
Can you give an example of the modules that were missing documentation? In general I think it's good to have; for instance https://docs.rs/cranelift-frontend/0.66.0/cranelift_frontend/#example is _extremely_ helpful in seeing how to use the API. Module-level examples are good for showing how to put different parts of the API together, not just what individual functions do (which sometimes isn't very helpful on its own, e.g. https://docs.rs/cranelift-frontend/0.66.0/cranelift_frontend/struct.FunctionBuilder.html#method.inst_results).

I did spot that https://doc.rust-lang.org/stable/std/default/index.html is missing an example, but that's because all the docs are on the trait itself, not the module. So maybe it makes sense to move that to the module instead?

**Comment by Manishearth** [comment]
Modules often have code examples in my experience. I think we should lint about them. It's okay to duplicate code examples between a module and its contents

**Comment by GuillaumeGomez** [comment]
But in the case of a crate providing utilities and tools, it seems a bit weird. For example, libstd and libcore provide only tools. What should we put as example at the crate top level doc comment for example?

**Comment by jyn514** [comment]
If it doesn't make sense, then it should use `allow(missing_doc_code_examples)`. But I don't think that means rustdoc shouldn't _ever_ lint for modules.

**Comment by GuillaumeGomez** [comment]
That would make a lot of `allow(missing_doc_code_examples)` in both libstd and libcore. ;)

**Comment by Manishearth** [comment]
@GuillaumeGomez What we might want is an attribute that allows you to skip linting for just a module but not its contents.

**Comment by GuillaumeGomez** [comment]
That'd still make a lot of module in both libcore and libstd. I really think that in some cases, modules don't need code examples.

**Comment by jyn514** [comment]
I don't think rustdoc is the right place to fix this. If libstd doesn't need module examples, then it shouldn't enable the lint - it's off by default anyway. There are a lot of modules that _do_ need linting and those shouldn't be ignored because it's not a good fit for libstd.

**Comment by GuillaumeGomez** [comment]
I just used libstd as an example. But I'm pretty sure that it's more common to have a module that shouldn't be commented than the opposite.

**Comment by Manishearth** [comment]
> But I'm pretty sure that it's more common to have a module that shouldn't be commented than the opposite.

I disagree: Most modules I've worked on have a reasonable code example that could be used in their documentation. At worst, it's just a copy of a code example from a substruct. 

I'm okay with adding a doc attribute that lets you skip this lint for a module, given that there is no way to apply `allow()` to a module and not have it apply to the children.

**Comment by GuillaumeGomez** [comment]
Modules can be used as **code** namespaces (which is, I think, the most common thing). Adding a code example on something like that doesn't make sense, since it's just providing a set of functions/types. Which one should you pick? It doesn't make sense.

**Comment by Manishearth** [comment]
When modules are used as _code_ namespaces they are private with reexported members. If the module is public, it's being used as a proper namespace.

**Comment by Manishearth** [comment]
Like, I'm struggling to come up with a project I have worked on where there is no applicable code example on the module, _aside_ from grab-bag utility modules, or modules containing a lot of subparts (e.g. `std`).

**Comment by GuillaumeGomez** [comment]
Yes, I realized it afterwards (forgot to write it here, just talked about that with @jyn514 on discord...).

**Comment by jyn514** [comment]
So the discussion is in one place: what we discussed is that we were talking at cross-purposes. @GuillaumeGomez was only referring to _private_ modules and both @Manishearth and I thought he was talking about _public_ modules. @GuillaumeGomez plans to make a few other PRs that make the handling of private vs public lints in rustdoc more consistent (of which I think https://github.com/rust-lang/rust/pull/76767 is the first).

**Comment by jyn514** [comment]
@GuillaumeGomez does this still make sense to add? I think the discussion about `missing_docs` being consistent with or without `--document-private-items` is also true here: I would expect a separate lint for warning about private items, instead of it changing behavior based on a CLI argument.

**Comment by GuillaumeGomez** [comment]
No, indeed! Closing.

**Pull request closed without merging**
