### PR TITLE
add ./x clippy ci

### PR DESCRIPTION
**Pull request by klensy**
This is rebase of https://github.com/rust-lang/rust/pull/126321

also https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/enable.20more.20clippy.20lints.20for.20compiler.20.28and.5Cor.20std.29 for context

### CODE REVIEW

**Comment by jieyouxu** [comment]
r? bootstrap (a bit busy with other compiletest stuff)

**Comment by onur-ozkan** [comment]
r? onur-ozkan

**Comment by klensy** [comment]
Weird: passes CI, but locally breaks on bootstrap warnings.

**Comment by onur-ozkan** [comment]
> Weird: passes CI, but locally breaks on bootstrap warnings.

It will probably fail on llvm-18 runner.

**Comment by klensy** [comment]
Eh? Why bootstrap tests fails in x86_64-gnu-llvm-18 55min, but not in mingw-check 35min.

**Comment by klensy** [comment]
> > Weird: passes CI, but locally breaks on bootstrap warnings.
> 
> It will probably fail on llvm-18 runner.

Actually, `python x.py clippy bootstrap -Dwarnings` fails on master too, but passes in CI.

**Comment by klensy** [comment]
Okay, thing is that `x.py clippy bootstrap` didn't run on windows CI, so it missed some `cfg(windows)` things that emitted warnings.

@rustbot ready

**Review by onur-ozkan — APPROVED** [review]
LGTM with the rebase

**Pull request merged**
