### PR TITLE
Add `try_fold` implementation to `Zip` iterator

### PR DESCRIPTION
**Pull request by Lucretiel**
Added implementation of `try_fold` to the `Zip` iterator, which is based on the `try_fold` of the first iterator in the zip.

### CODE REVIEW

**Comment by Lucretiel** [comment]
I can't tell what the source of the conflict is; I based these changes off the latest master and they merge on my own clone without complaint.

**Comment by clarfon** [comment]
This is definitely not on the latest master.

**Comment by Lucretiel** [comment]
Whoops, you're right- I rebased onto the master of my fork, not upstream

**Comment by Lucretiel** [comment]
Fixed

**Comment by Lucretiel** [comment]
Fixed

**Comment by Dylan-DPC** [comment]
ping from triage @sfackler can you review this? 
@Lucretiel any updates on the test errors?

**Comment by sfackler** [comment]
The implementation seems reasonable, but it doesn't build.

**Comment by Dylan-DPC** [comment]
ping from triage @Lucretiel can you fix the test errors?

**Comment by jonas-schievink** [comment]
Closing due to inactivity, but feel free to submit a new PR with the errors fixed @Lucretiel!

**Pull request closed without merging**
