### PR TITLE
Install robots.txt into rust-docs tarballs

### LINKED ISSUE #68677: doc.rust-lang.org/robots.txt doesn't match src/doc/robots.txt
The intention in https://github.com/rust-lang/rust/pull/59213 was to add robots.txt to what gets uploaded to doc.rust-lang.org, but it appears that either the manual step of copying this over for a release hasn't been happening, or that the automation was never done, or the automation isn't working.

The contents of [src/doc/robots.txt](https://github.com/rust-lang/rust/blob/212b2c7da87f3086af535b33a9ca6b5242f2d5a7/src/doc/robots.txt) doesn't match what I'm currently seeing on https://doc.rust-lang.org/robots.txt:

```
User-agent: *
Disallow: /0.3/
Disallow: /0.4/
Disallow: /0.5/
Disallow: /0.6/
Disallow: /0.7/
Disallow: /0.8/
Disallow: /0.9/
Disallow: /0.10/
Disallow: /0.11.0/
Disallow: /0.12.0/
Disallow: /1.0.0-alpha/
Disallow: /1.0.0-alpha.2/
Disallow: /1.0.0-beta/
Disallow: /1.0.0-beta.2/
Disallow: /1.0.0-beta.3/
Disallow: /1.0.0-beta.4/
Disallow: /1.0.0-beta.5/
```

(lines 20-27 in the repo are not present on the live site)

Thanks!

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Fixes #68677.

I believe this might just work out from the central-station perspective, but even if it doesn't, this is a prerequisite step anyway.

### CODE REVIEW

**Comment by BO41** [comment]
This should allow this comment to be removed, right?
https://github.com/rust-lang/rust/blob/212b2c7da87f3086af535b33a9ca6b5242f2d5a7/src/doc/robots.txt#L1

**Comment by Mark-Simulacrum** [comment]
Ah, yes, that can be removed. I'll update the PR soon.

**Comment by pietroalbini** [comment]
@bors r+ rollup

Thanks!

**Pull request merged**
