### PR TITLE
give full path of constraint in suggest_constraining_type_param

### LINKED ISSUE #83513: Error message doesn't give full path in suggestion.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d854c189b0a198c091da3ccf429e0ec9

It suggests adding `Sum` to the bounds, but `Sum` is *not* in scope, so typing directly what it says just leads to another error.

Interestingly, Mul was suggested as std::ops::Mul.

So it should likely suggest the correct prefix for the Sum trait.

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rust/issues/83513

### CODE REVIEW

**Comment by lcnr** [comment]
r? @estebank 

feeling unsure about whether using full paths is actually desirable, but don't have a strong opinion here

**Comment by estebank** [comment]
Oh! It's a shame that it also affects things in the prelude 🤔

The current behavior means you get two errors but if you apply both suggestions you get to working code. The new behavior means a single step to working code, at the cost of verbosity.

@lcnr what do you think about this: lets land this (to reduce fix cycles for users) and revisit this output once we have real "locally accessible paths" for these suggestions where we can reduce the verbosity again.

**Comment by lcnr** [comment]
> what do you think about this: lets land this (to reduce fix cycles for users) and revisit this output once we have real "locally accessible paths" for these suggestions where we can reduce the verbosity again.

:+1:

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/83690#issuecomment-810626027) 

@bors r-

**Comment by hi-rustin** [comment]
> failed in [rollup](https://github.com/rust-lang/rust/pull/83690#issuecomment-810626027)
> 
> @bors r-

Rebased.But it doesn't seem to have updated any files, so it looks like some changes were lost in the rollup PR?

**Comment by hi-rustin** [comment]
> failed in [rollup](https://github.com/rust-lang/rust/pull/83690#issuecomment-810626027)
> 
> @bors r-



> failed in [rollup](https://github.com/rust-lang/rust/pull/83690#issuecomment-810626027)
> 
> @bors r-

@Dylan-DPC  Blessed with nll  compare mode.

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/83673) 

@bors r-

**Comment by hi-rustin** [comment]
> failed in [rollup](https://github.com/rust-lang/rust/pull/83673)
> 
> @bors r-

@Dylan-DPC  I tested both modes again locally with no problems, so I don't know what's wrong, do you have any suggestions?

image

**Comment by hi-rustin** [comment]
It seems that without my commit, this https://github.com/rust-lang/rust/pull/83728 PR is also failing because of the same problem?

**Comment by hi-rustin** [comment]
> let's give it a try once,

Thanks, maybe we can rollup this time without the other PRs that modify the diagnostic information, otherwise it might fail again and we still don't know if the PR is the problem.

**Pull request merged**
