### PR TITLE
Implement checked Shl/Shr at MIR building.

### PR DESCRIPTION
**Pull request by cjgillot**
This does not require any special handling by codegen backends,
as the overflow behaviour is entirely determined by the rhs (shift amount).

This allows MIR ConstProp to remove the overflow check for constant shifts.

~There is an existing different behaviour between cg_llvm and cg_clif (cc @bjorn3).
I took cg_llvm's one as reference: overflow if `rhs < 0 || rhs > number_of_bits_in_lhs_ty`.~

EDIT: `cg_llvm` and `cg_clif` implement the overflow check differently. This PR uses `cg_llvm`'s implementation based on a `BitAnd` instead of `cg_clif`'s one based on an unsigned comparison.

### CODE REVIEW

**Comment by bjorn3** [comment]
> There is an existing different behaviour between cg_llvm and cg_clif (cc @bjorn3).
I took cg_llvm's one as reference: overflow if rhs < 0 || rhs > number_of_bits_in_lhs_ty.

What is the difference? `rhs < 0` is implied by `rhs > number_of_bits_in_lhs_ty` due to the usage of an unsigned comparison rather than a signed one.

**Comment by tmiasko** [comment]
Can you also update the docs for CheckedBinaryOp:

https://github.com/rust-lang/rust/blob/3200982b7689ff496e63584c5c8f9bf707b98ae3/compiler/rustc_middle/src/mir/syntax.rs#L1115-L1117

**Comment by RalfJung** [comment]
Does this mean `BinOp::is_checkable` should no longer consider Shl/Shr to be checkable? Sounds like it to me.

**Comment by cjgillot** [comment]
I don't think so.

`BinOp::is_checkable` is poorly named: it controls whether `-Coverflow-checks` emits an assertion. This is still true: we still decide to emit/omit the assert terminator. https://github.com/rust-lang/rust/pull/109058 makes the documentation more precise.

**Comment by nnethercote** [comment]
The `tt-muncher` improvements might be noise. The `ctfe-stress-5` regressions are small and not really important. Looking at non-relevant (sub-threshold) results it might be a very slight win overall. In short: nothing worth worrying about.

@rustbot label: +perf-regression-triaged

**Pull request merged**
