### PR TITLE
Update Source Code Pro and include italics

### LINKED ISSUE #65502: Rustdoc uses fake italics for code
For example https://doc.rust-lang.org/std/primitive.i32.html has the string “*See also the `std::i32` module*” which inludes code in italics. This is rendered using fake italics because the Source Code Pro italic font is not included.

Adding the italic font would fix this, but at the cost of having an extra font to download. Is the better formatting worth the (one-time?) download?

If there is an interest, I can prepare a PR to include the [latest version](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it) of Source Code Pro including the italic font. The sizes are as follows:

| Font | Current Size | Latest Size |
|:-|:-|:-|
| Regular | 55472 | 95872 |
| Semibold | 55360 | 95576 |
| Italic | | 84264 |
| *Total*| 110832 | 275712 |

### PR DESCRIPTION
**Pull request by tspiteri**
Fixes #65502.

#65665, a similar PR to this was merged but reverted because of https://github.com/rust-lang/rust/pull/65665#issuecomment-556860510.

The issue in that comment is the upstream issue https://github.com/adobe-fonts/source-code-pro/issues/217 which should now be fixed in the upstream since [2.032R-ro/1.052R-it/1.012R-VAR release](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro/1.052R-it/1.012R-VAR), so I think this can now be merged.

A couple of notes from the original PR:
* Since this PR changes the font set, I think docs.rs would have to be updated if this PR is merged.
* The fonts have a double extension (.ttf.woff); this is to keep the names consistent with the upstream font release which does that to distinguish these from the .otf.woff files (Source Code Pro otf renders poorly on older Windows system apps).

### CODE REVIEW

**Comment by jyn514** [comment]
> Since this PR changes the font set, I think docs.rs would have to be updated if this PR is merged.

You mean, update ESSENTIAL_FILES_VERSIONED?
https://github.com/rust-lang/docs.rs/blob/05d236821ca7d569daa8a33dc2819e9e39467ed1/src/docbuilder/rustwide_builder.rs#L27

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks! Now we just need to sync with docs.rs and I think we're good to go.

**Comment by jyn514** [comment]
Could someone please explain what they mean by 'sync with docs.rs'?

**Comment by GuillaumeGomez** [comment]
Someone can explain: you'll need to update the font file on docs.rs but I don't know the process. If there is nothing particular to be done, then we can simply merge this PR. :)

**Comment by jyn514** [comment]
Ok. Docs.rs can only be updated after this is merged, because it requires those files to exist and gives an error otherwise. So this needs to make it to a nightly before docs.rs can be updated I think.

@rust-lang/docs-rs please correct me if I'm wrong.

**Comment by pietroalbini** [comment]
Yeah we'll need to update the essential files list.

To avoid generating broken docs I think the best approach is to pin the docs.rs nightly to a known good one before merging this PR, merge the PR, update the docs.rs code to copy the file and then remove the pin.

**Comment by crlf0710** [comment]
Triage: What's the current status?

**Comment by tspiteri** [comment]
Rebased and updated fonts to the upstream [2.038R-ro/1.058R-it/1.018R-VAR](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.038R-ro%2F1.058R-it%2F1.018R-VAR) release.

**Comment by GuillaumeGomez** [comment]
@jyn514 Should we wait for https://github.com/rust-lang/docs.rs/issues/1302 or can we r+ it?

**Comment by jyn514** [comment]
I would prefer to wait for https://github.com/rust-lang/docs.rs/issues/1302 if possible. If it takes more than another week or so I'm ok with approving this and fixing the breakage when it occurs.

**Pull request merged**
