### PR TITLE
Revert "debuginfo: Bring back some GDB pretty printing autotests that…

### PR DESCRIPTION
**Pull request by alexcrichton**
… are not actually broken."

This reverts commit 354cf4b56b8e2af67cc68965eb816deec0e79e4b.

Unfortunately these [tests are failing](http://buildbot.rust-lang.org/builders/nightly-dist-rustc-linux/builds/224/steps/distcheck/logs/stdio) on the snapshot/nightly bots with the [same message](https://gist.github.com/alexcrichton/611705ded07b0d73ded9) found in #27514

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
So, there seems to be some kind of problem that only occurs on some systems. I don't quite understand why I can't reproduce it but I'll look into it some more.

**Comment by alexcrichton** [comment]
Yeah :(. If you want me to give you temp access to the snap bots just lemme know and you can try out the gdb in that environment to see what the differences are.

**Comment by brson** [comment]
This made it into 1.3 beta. Backporting.

**Pull request merged**
