### PR TITLE
Prevent the `start_bx` basic block in codegen from having two `Builder`s at the same time

### PR DESCRIPTION
**Pull request by 823984418**
Here, at the same time, there are two `start_llbb` builder, this should be unexpected.

### CODE REVIEW

**Comment by cjgillot** [comment]
Could you elaborate what is the bug you are fixing, how does your patch fix it, and maybe add a test?

**Comment by bjorn3** [comment]
I like to work towards using a single builder for the entire function. This PR is a step in this direction, however there are other places where multiple builders exist at the same time. In addition I don't think this PR on it's own is actually useful. A PR that makes it such that only a single builder is used will changes this anyway except rather than dropping the builder here is would switch the current basic block of the builder later in this function.

**Comment by 823984418** [comment]
If someone wants to through `rustc_codegen_ssa` write a codegen backend of pure Rust, this may cause trouble to the internal variability of the `BasicBlock`.

But now there are no bugs. This is just a problem I met on the way to study and try.

**Comment by bjorn3** [comment]
I'm currently quite busy with among other things uni work. I'm going to re-assign it to you, but if you want to assign it to someone else that is fine too.

r? @cjgillot

**Comment by cjgillot** [comment]
> If someone wants to through `rustc_codegen_ssa` write a codegen backend of pure Rust, this may cause trouble to the internal variability (For example: `RefCell::borrow_mut()`) of the `BasicBlock`.
> 
> But now there are no bugs. This is just a problem I met on the way to study and try.

Then, could you add a comment explaining why there is this statement.
r=me with the comment

**Pull request merged**
