### PR TITLE
dump-ice-to-disk/check.sh: convert needless bashism in a /bin/sh script.

### PR DESCRIPTION
**Pull request by he32**
This script is marked with `#! /bin/sh`, but uses Bash-only constructs ("bashisms").
In this case there is a corresponding portable POSIX shell construct, and this
change converts to use that, instead of insisting that `/bin/sh` must be Bash.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
can we change it to a bash shebang instead? the bash looks less bad than the posix shell

**Comment by Mark-Simulacrum** [comment]
Kicking to get another CI run, last one seems to be a spurious failure.

I'm not sure bash shebang is really a delta here, I'm inclined to land as-is. Long-term, https://github.com/rust-lang/rust/issues/40713 is the real solution to readability.

**Comment by he32** [comment]
> can we change it to a bash shebang instead? the bash looks less bad than the posix shell. I don't think it matters which shebang you choose exactly because I don't expect the test suite to actually use the shebang, but it's nice to have one for tools like shellcheck. I'd recommend `/usr/bin/env bash`

Well.  It's evident that you have different priorities than I do, and if this was my code, I would not do that.  I would instead put priority on "standard compliance" and "portability", instead of prioritizing "it looks prettier".  But this isn't my code or my call to make.

**Comment by Nilstrieb** [comment]
better idea: just rewrite the test in rust instead: #121876

**Comment by Dylan-DPC** [comment]
Closing this pr as it's inactive and better off being rewritten as a rust test instead of this approach

**Pull request closed without merging**
