### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by Manishearth**
r? @kennytm @alexcrichton @oli-obk

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like CI may be failing b/c the lock file needs to be updated? Other than that r=me

**Comment by Manishearth** [comment]
@bors r=alexcrichton p=3

(p+ for it to reach beta)

**Comment by kennytm** [comment]
@Manishearth 1.24 beta has already been branched off, this PR won’t reach it unless we backport.

**Comment by Manishearth** [comment]
Ah. Is is important for this PR to reach it? Or is it ok because we don't ship clippy with rustup yet?

**Comment by kennytm** [comment]
According to https://github.com/rust-lang/rust/pull/47119#issuecomment-354832859 it is OK not to backport it because we don't ship clippy yet.

**Comment by Manishearth** [comment]
@bors r=alexcrichton

needed a compiletest bump

**Comment by kennytm** [comment]
Legit, test failed due to read-only filesystem. Looks like still the same error we've seen before at https://github.com/rust-lang/rust/pull/46554#issuecomment-349995076

```
[01:06:06] ---- compile_test stdout ----
[01:06:06] 	thread 'compile_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', /checkout/src/libcore/result.rs:916:5
[01:06:06] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:06:06] 
[01:06:06] 
[01:06:06] failures:
[01:06:06]     compile_test
```

**Comment by shepmaster** [comment]
Ping from triage, @Manishearth! Will you have time to address the reported issues in the near future?

**Comment by Manishearth** [comment]
Not really, and I don't know what's going on. Perhaps @oli-obk does?

**Comment by carols10cents** [comment]
Looks like this is replaced by #47557, so I'm closing!

**Pull request closed without merging**
