### PR TITLE
[WIP] Allow global_allocators in submodules

### LINKED ISSUE #44113: global_allocator can not not be defined inside module
When trying define a global allocator inside a module, you get a weird error message: `[E0432]: unresolved import super`. The global_allocator is expanded to code containing `use super::<varname>` but I don't know why rustc fails to resolve that in this case. Happens with both inline and file modules. 

Looks like the module that is created by expanding global_allocator thinks its parent is the root crate despite being in the `breaks` module.

Example:
```rust
#![feature(global_allocator, allocator_api)]                                                                                                                                                                       
                                                                                                                                                                                                                   
struct TAlloc;                                                                                                                                                                                                     
                                                                                                                                                                                                                   
unsafe impl<'a> std::heap::Alloc for &'a TAlloc{                                                                                                                                                                   
    unsafe fn alloc(&mut self, _layout: std::heap::Layout) -> std::result::Result<*mut u8, std::heap::AllocErr> {                                                                                                  
        return Err(std::heap::AllocErr::Unsupported{details: "Stub allocator"});                                                                                                                                   
    }                                                                                                                                                                                                              
    unsafe fn dealloc(&mut self, _ptr: *mut u8, _layout: std::heap::Layout) {                                                                                                                                      
    }                                                                                                                                                                                                              
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
mod breaks{                                                                                                                                                                                                        
    #[global_allocator]                                                                                                                                                                                            
    static ALLOCATOR: ::TAlloc = ::TAlloc;                                                                                                                                                                         
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
pub fn main() {                                                                                                                                                                                                    
}
```
causes:
```
error[E0432]: unresolved import `super`
  --> alloc.rs:15:5
   |
15 |     static ALLOCATOR: ::TAlloc = ::TAlloc;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ALLOCATOR` in the root
```

### PR DESCRIPTION
**Pull request by mark-i-m**
First commit is rustfmt.

Is this even the right approach? Right now it's just breaking everything...

Fix #44113

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I could review this if forced, but I'm not super familiar with what's going on here. @alexcrichton -- are you the right person?

**Comment by alexcrichton** [comment]
Sure yeah I don't mind reviewing this. @mark-i-m mind explaning a bit what the change here is doing?

**Comment by mark-i-m** [comment]
@alexcrichton Thanks!

The problem: `global_allocators` currently can only be declared in the crate root, but it would be nice to be able to declare them in submodules to. The current implementation is a magic proc_macro that gets expanded into an inline submodule with an allocator implementation (see the location of the edits of this PR; that's code that actually does this magic expansion). The implementation forces the item decorated with `global_allocator` to be in the crate root by hard-coding `super::NAME_OF_STATIC` as the path of the allocator.

Proposed solution: Rather than hard-coding `super::NAME_OF_STATIC` as the path of the static, we use the actual path of the static. Unfortunately, it doesn't appear that there is a way to get this path at name resolution when macro expansion happens, so instead, I am trying to keep track of the path as I fold. The current implementation in this PR has bugs, but more importantly, I don't know if that is the right way to approach the problem in the first place. Any help would be appreciated.

**Comment by alexcrichton** [comment]
Ok thanks! I was actually the original author of all this code so I'm mostly curious in the delta from the previous instantiation :)

I think, though that `super::NAME` should work here, right? We should be unconditionally generating a submodule that references the parent static. I suspect that the underlying issue here is hygiene, so perhaps the hygiene of `super` or the identifier could be sorted out to get this working?

**Comment by mark-i-m** [comment]
> I suspect that the underlying issue here is hygiene, so perhaps the hygiene of super or the identifier could be sorted out to get this working?

TBH, I don't  really know that much about how hygiene works in macro expansion (the rustc-guide chapter has yet to be written). Do you have any hints of how to get started?

**Comment by alexcrichton** [comment]
I'm not so sure myself (hence why this has never been fixed), but AFAIK it's all tied to identifiers/spans. It may not be necessary at all to even use `super::NAME` and instead we could just use `NAME`. Syntactically the Rust code would look invalid but it may hygienically resolve

**Comment by mark-i-m** [comment]
I get the following error:

```
failures:

---- [ui] ui/allocator-submodule.rs stdout ----
	normalized stderr:
error[E0432]: unresolved import `MY_HEAP`
  --> $DIR/allocator-submodule.rs:22:5
   |
LL |     static MY_HEAP: Heap = Heap::default();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `MY_HEAP` in the root

error: aborting due to previous error
```

**Comment by alexcrichton** [comment]
Ah if that doesn't work then it may mean that a special span needs to be used for `super` that contextualizes it correctly. Unfortunately though I'm still not so sure myself, I'm also pretty unfamiliar with hygiene.

**Comment by mark-i-m** [comment]
Unfortunately, I don't know enough about name resolution or hygiene to know how to do that. Do you have any suggested resources for learning more? Unfortunately, the rustc-guide section is a bit incomplete.

**Comment by alexcrichton** [comment]
Hm ok, an alternative is to change how things are expanded. Currently a `#[global_allocator]` item expands to itself and a submodule, but the contents of the submodule could be inlined next to `#[global_allocator]` which may help the resolution issue

**Comment by mark-i-m** [comment]
Thanks @alexcrichton! I will give that a try.

Quick question: What does the following line (112) do exactly?

```rust
        let module = f.cx.monotonic_expander().fold_item(module).pop().unwrap();
```

**Comment by alexcrichton** [comment]
A good question! I'm... not actually sure. I may have copy/pasted that from somewhere else originally, and it may be safe to remove.

**Comment by mark-i-m** [comment]
It seems that we have the same hygiene problems with `core`. I think we need to bite the bullet and figure out how hygiene works in name resolution :stuck_out_tongue: ... What we really need is
1. A way to construct a hygienic non-conflicting new ident on the fly.
2. A way to construct absolute paths to existing idents such that things like "crate root", `super`, and `self` are handled properly.

I feel like (2) already exists but we are doing it wrong?

**Comment by mark-i-m** [comment]
Ok, I think I'm onto something: when we create the new `Mark` for the macro expansion, I think we need to set the `call_site` so that we get hygiene for the location of the global item: https://github.com/rust-lang/rust/pull/49320/commits/60fbde77b10e6b45c42c3985b7ff001d41a32858#diff-a65fc158001a4a43e2add393cbf864a9R89

I also set the `crate_name` correctly when creating the `ExpansionConfig`, but I'm not sure what this is used for.

I am now getting "no `super::MY_HEAP` in root" or "no `MY_HEAP` in root" errors. I'm hoping that this is coming from the `call_allocator`-generated call to the allocator, since it uses the static item by name. Does this sound reasonable?

**Comment by alexcrichton** [comment]
Sorry I'm getting pretty mixed up in the diff right now, call the rustfmt changes get backed out for a future run later?

**Comment by alexcrichton** [comment]
This in general sounds plausible though! Want to add a test to make sure if it passes CI it's good to go?

**Comment by mark-i-m** [comment]
Sorry, I will pull out rustfmt and comments to another PR... It doesn't work yet, but if I'm right, then it might make like easier. I have a UI test I've been using locally. I will add it too... I'm on mobile at the moment, but when I get to my computer, I will do this...

**Comment by mark-i-m** [comment]
Also, I believe that last commit is the only one with any actual changes (for the moment)... Will update a bit later...

**Comment by mark-i-m** [comment]
@alexcrichton I have factored out the formatting and commenting into PR #49969. There are now two commits in this PR. The first makes the change to use the call-site for hygiene. The second adds a test for allocators in submodules (it should _fail_).

**Comment by alexcrichton** [comment]
@mark-i-m something which may also work is the use of `gensym` which generates un-nameable identifiers which can be used to reference themselves but normal Rust code can't reference them. Using that we may be able to splat everything into the original module I think?

**Comment by mark-i-m** [comment]
@alexcrichton Thanks! I will try that out later... A bit swamped at the moment :)

**Comment by mark-i-m** [comment]
@alexcrichton Is there a way to see the code with macros expanded?

**Comment by alexcrichton** [comment]
@mark-i-m I've used `cargo expand` historically and I think it'd work for this? I'm not 100% sure but otherwise I just stare and hope I can find it...

**Comment by mark-i-m** [comment]
It does work (it's a really useful tool :))

**Comment by mark-i-m** [comment]
@alexcrichton I think I have made some progress on this. I think I can get it to work, but I need to synthesize a `extern crate core as __other_core` (I can use `gensym` to generate a name `__other_core`) so that the import doesn't conflict with `core` if it is already imported. However, `ExtCtxt::item_extern_crate` doesn't seem to have a way to generate an extern with `as`. Any hints?

**Comment by alexcrichton** [comment]
@mark-i-m oh I think you can avoid the `as`, if you use `gensym` to generate `extern crate core` it won't conflict with normal `core` I believe

**Comment by mark-i-m** [comment]
Hmm... that leads to the following error
```
error[E0463]: can't find crate for `core`
  --> /nobackup/rust/src/test/run-pass/allocator/submodule.rs:34:5
   |
34 |     static MY_HEAP: MyAlloc = MyAlloc;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

**Comment by mark-i-m** [comment]
The following also doesn't seem to work:

```rust
        let extcore = {
            let coreraw = Symbol::from_ident(Ident::from_str("core"));
            let extcore = f.cx.item_extern_crate(item.span, f.core, Some(coreraw));
            f.cx.monotonic_expander().fold_item(extcore).pop().unwrap()
        };
```

```rust
    fn item_extern_crate(&self, span: Span, name: Ident, orig: Option<ast::Name>) -> P<ast::Item> {
        self.item(span, name, Vec::new(), ast::ItemKind::ExternCrate(orig))
    }
```

**Comment by alexcrichton** [comment]
@mark-i-m the paths referencing `core` will probably need to also be `self::core::...`, does that help?

**Comment by mark-i-m** [comment]
I think the problem isn't with the usage site but with the `extern crate core`. If we gensym the `core` in the extern, it doesn't "unify" with `core` as in `libcore`, right?

**Comment by alexcrichton** [comment]
It should I believe so, yes, but the best way to figure that out is to test it out!

**Comment by mark-i-m** [comment]
I did :smile: (see the latest commit). Is that what you were thinking of or did I misunderstand?

**Comment by alexcrichton** [comment]
Ah alas :( Yeah that's what I thought my have worked.

I'm running out of ideas here...

**Comment by mark-i-m** [comment]
So I know we are really close because adding `extern crate core` manually to the submodule causes everything to be hunky-dory... The following works:

```rust
mod submod {
    extern crate core; // Adding this manually, rather than programmatically works :P
    use super::MyAlloc;

    #[global_allocator]
    static MY_HEAP: MyAlloc = MyAlloc;
}
```

However, interestingly, doing that results in the test crashing with SIGILL (signal 4)... Strange.

**Comment by pietroalbini** [comment]
Ping from triage! What's the status of this PR?

**Comment by mark-i-m** [comment]
@pietroalbini We are facing weird hygiene problems that neither I nor @alexcrichton know how to fix. I'm not really sure how to proceed.

**Comment by mark-i-m** [comment]
@alexcrichton Sorry for the delay, I was in a bit of a time crunch. Let me check.

(also, I rebased so the branch doesn't fall too far behind, but there are no changes, and it still doesn't work)

**Comment by mark-i-m** [comment]
@alexcrichton Ok, so here's what I have.

If I don't generate an `extern crate core` but _manually_ do that in the code to be compiled, it seems to compile and run as expected. Likewise, the expanded code also compiles when I manually add in the extern.

If I generate an `extern crate core` programmatically instead, I merely get an error:

```console
$ cargo +stage1 expand
   Compiling my_test v0.1.0 (file:///tmp/my_test)
warning: ignoring --out-dir flag due to -o flag
warning: ignoring -C extra-filename flag due to -o flag
error[E0463]: can't find crate for `core`
  --> src/main.rs:21:5
   |
21 |     static MY_HEAP: MyAlloc = MyAlloc;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
error: Could not compile `my_test`.
To learn more, run the command again with --verbose.
cat: /tmp/cargo-expand.UUz20ChlwC2T/expanded: No such file or directory
```

**Comment by TimNN** [comment]
@alexcrichton: Do you have any ideas about the error above?

**Comment by alexcrichton** [comment]
Ah unfortunately I don't recognize the error nor know the best way to fix it :(

**Comment by mark-i-m** [comment]
Hmm... ok so what would be the best path to take? I'm not really sure that I have the knowledge to proceed productively on this issue, so it might be best to leave this for someone else? 

IMHO, we should disallow allocators in submodules for now, making it a hard error. That would unblock stabilization, right? Then, we should leave notes in #44113 for the next intrepid explorer?

**Comment by alexcrichton** [comment]
Yes until this is fixed I think it's fine to just disallow this with a hard error

**Comment by mark-i-m** [comment]
Ok, I will try to implement that this week. Would that be done by just keep track in the Folder if we ever try to fold a submodule?

I will also leaves some comments on the issue about some of the things we tried.

**Comment by alexcrichton** [comment]
I believe so yeah that should work out well enough

**Comment by shepmaster** [comment]
Ping from triage, @mark-i-m ! Will you have time to revisit this soon?

**Comment by mark-i-m** [comment]
@shepmaster Sorry, I'm without a computer for the next few days. If you want to close this to keep the issue tracker clean, feel free. I will try to do it soon.

**Comment by pietroalbini** [comment]
Ugh, you have to open a new PR since you force-pushed the branch...

**Comment by mark-i-m** [comment]
Really? Why? I do that every time I rebase

**Comment by TimNN** [comment]
> Really? Why? I do that every time I rebase

GitHub oddities. Once a PR is closed (which happened above) it cannot be re-opened once there has been a force push to the underlying branch.

**Comment by mark-i-m** [comment]
Oh, good to know...

**Pull request closed without merging**
