### PR TITLE
add -Zunpretty=hir-tree

### PR DESCRIPTION
**Pull request by nikomatsakis**
This uses the debug impls to dump the raw HIR. Particularly useful when
learning how the compiler works.

cc @qmx

### CODE REVIEW

**Comment by qmx** [comment]
👍 useful

**Comment by nikomatsakis** [comment]
You can also do `-Zdump-tree=22` to lower the contents of node-id 22, or `-Zdump-tree=foo` to lower a particular path `foo`. I've found the latter... imperfect... in my testing, but it's just using the existing infrastructure.

**Comment by arielb1** [comment]
Could you add a `run-make` test on some sort of "Hello World" program (an Hello World without `println!`, I suppose), just that we make sure this doesn't randomly break, or do you think that would be too much of a maintenance burden?

**Comment by nikomatsakis** [comment]
@arielb1 good question. It does seem useful to have a test -- but I am not super keen about periodically updating it with new HIR. I guess we could just check that it emits something non-empty or perhaps something with a few strings (e.g., names of the functions)?

**Comment by arielb1** [comment]
Sure, just running it, seeing that it doesn't crash, and seeing that e.g. a string literal from the code appears in the HIR should work.

**Comment by shepmaster** [comment]
Greetings from triage, @nikomatsakis! It's been a week since we last heard from you here — will you be able to add the requested tests sometime soon?

**Comment by nikomatsakis** [comment]
@shepmaster I will, I'm just slow. =)

**Comment by nikomatsakis** [comment]
Added a test.

**Pull request merged**
