### PR TITLE
FRC target support

### PR DESCRIPTION
**Pull request by emmaworley**
This PR adds support for [target platform](http://forums.ni.com/t5/FIRST-Robotics-Competition/roboRIO-Details-and-Specifications/ta-p/3494658) used in the FIRST Robotics Competition.

### CODE REVIEW

**Comment by jmesmon** [comment]
Given that the control system has a habit of changing every few years, might make sense to expand the `vendor` to either include the year of introduction or the name of the platform.

**Comment by connorworley** [comment]
Agreed, I've added the platform name and year of release.

**Comment by aidanhs** [comment]
Thanks for the PR @connorworley! We'll check in regularly to make sure @alexcrichton or another reviewer gets to this soon.

**Comment by parched** [comment]
I don't think rust is in the habit of adding vendored targets like this. Would adding a neutral armv7-unknown-linux-gnueabi target be sufficient for your needs?

**Comment by alexcrichton** [comment]
Thanks for the PR @connorworley! As mentioned by @parched though we tend to add more generalized platforms to the compiler before branching into the specialized ones. We don't currently really have a policy one way or the other about this, it's mostly just gut feelings so far.

Out of curiosity is there a more general target that could be added? Or are custom target specs not sufficient for your use case maybe?

**Comment by connorworley** [comment]
I could get away with using custom target specs, but the ultimate goal is for the high school students I work with to be able to easily deploy rust code for the roboRIO. In that regard, I think getting this target upstreamed would make it the easiest for them.

**Comment by arielb1** [comment]
@alexcrichton are we going to be including this target? Should this be discussed in one of the teams?

**Comment by jmesmon** [comment]
Looks like this is just a specific cpu & features. Given that, it seems like naming it for the cpu selection & fpu options might be more appropriate (there isn't anything really FRC specific about the target, others with similar cpus could use it).

Is the need here just for better optimization compared to using one of the other `arm-*-linux-gnueabi` targets? More generally: what customizations here are actually required/desired and why are they required/desired?

**Comment by connorworley** [comment]
So after some more testing I have a better idea of what's going on, and I think I can get away with just using `arm-unknown-linux-gnueabi`. If it turns out that any customization are actually necessary, I'll send in a new PR for a generic target supporting those customizations.

**Pull request closed without merging**
