### PR TITLE
Remove use of const traits (and `feature(effects)`) from stdlib

### PR DESCRIPTION
**Pull request by fee1-dead**
The current uses are already unsound because they are using non-const impls in const contexts. We can reintroduce them by reverting the commit in this PR, after #120639 lands.

Also, make `effects` an incomplete feature.

cc @rust-lang/project-const-traits 
r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me when ci is green

# Note for anyone whose code has regressed because we removed const traits from libstd

Please pin your nightly version to `2024-06-16` since it's likely going to be a bit of time before we restore const to some of these traits like `PartialEq` and `Add`. Sorry!

**Comment by oli-obk** [comment]
Could also mark the features as incomplete now as then they won't be usable in libcore accidentally

**Comment by compiler-errors** [comment]
Yeah, good idea. Will require adding a bunch of `//~^ WARN the feature effects is incomplete` to the test suite, but I'd rather mark it incomplete until we're confident about it!

**Comment by fee1-dead** [comment]
I made `effects` incomplete and blessed the ui tests.

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me after making tests pass

**Comment by oli-obk** [comment]
Looks like the book uses effects in examples

**Pull request merged**
