### PR TITLE
Remove unreasonable help message for auto trait

### LINKED ISSUE #105788: Invalid suggest for methods in auto trait
Given the following [code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3d78bc0ac4aa5d4ce69d876c285f6112)

```rust
#![feature(auto_traits)]

auto trait Foo {
    fn g(&self);
}

trait Bar  {
    fn f(&self) {
        self.g();
    }
}

fn main() {}

```

The current output is:

```
error[E0380]: auto traits cannot have associated items
 --> src/main.rs:4:8
  |
3 | auto trait Foo {
  |            --- auto trait cannot have associated items
4 |     fn g(&self);
  |     ---^-------- help: remove these associated items

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:1
  |
1 | #![feature(auto_traits)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: the method `g` exists for reference `&Self`, but its trait bounds were not satisfied
 --> src/main.rs:9:14
  |
9 |         self.g();
  |              ^
  |
note: trait bound `&Self: Foo` was not satisfied
  = note: the following trait bounds were not satisfied:
          `Self: Foo`
          which is required by `&Self: Foo`
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `g`, perhaps you need to add a supertrait for it:
  |
7 | trait Bar: Foo  {
  |          +++++

Some errors have detailed explanations: E0380, E0554, E0599.
For more information about an error, try `rustc --explain E0380`.
error: could not compile `playground` due to 3 previous errors
```

The second error is not reasonable, since we don't allow associated items in auto trait.
Ideally the output should look like:

```
error[E0599]: no method named `g` found for reference `&Self` in the current scope
 --> ./p/e.rs:9:14
  |
9 |         self.g();
  |
```

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #105788

### CODE REVIEW

**Comment by chenyukang** [comment]
There is another solution, we just emit E0380, and use `items` with an empty vec in:
https://github.com/rust-lang/rust/blob/49c2279ef658d8732597c4da93897d84838f3df5/compiler/rustc_parse/src/parser/item.rs#L876

Then, in later parts we don't need care about auto trait, since we have made sure there will be no assoc items in it.

I'm not sure whether this is a desirable solution, but it seems more completed than our current case by case fix.

@TaKO8Ki how do you think?

**Comment by chenyukang** [comment]
I tried this solution, it's also a fix for #105732:

https://github.com/rust-lang/rust/commit/e2e9a31f24eae9e4e2492da6a7af42fa1bfcdd13

Not sure which fix is better.
@compiler-errors

**Review by TaKO8Ki — COMMENTED** [review]
@bors r+ rollup

**Comment by compiler-errors** [comment]
This failure is unrelated to the PR.

@bors r=TaKO8Ki

**Pull request merged**
