### PR TITLE
Update the coherence rules to "covered first"

### LINKED ISSUE #20749: Parameterized traits can't be implemented for arbitrary types even if their parameters are "local"
This program fails to compile:
```rust
use std::ops::Add;

struct BigFloat;

impl Add<BigFloat> for f64 {
    type Output = BigFloat;

    fn add(self, rhs: BigFloat) -> BigFloat {
        BigFloat
    }
}

fn main() {}
```
The error:
```
test7.rs:5:1: 11:2 error: the type `f64` does not reference any types defined in this crate; only traits defined in the current crate can be implemented for arbitrary types [E0117]
test7.rs:5 impl Add<BigFloat> for f64 {
test7.rs:6     type Output = BigFloat;
test7.rs:7 
test7.rs:8     fn add(self, rhs: BigFloat) -> BigFloat {
test7.rs:9         BigFloat
test7.rs:10     }
            ...
error: aborting due to previous error
```

I would expect that this should work because `Add`'s parameter is "local" type. [Associated types and multidispatch RFC](https://github.com/aturon/rfcs/blob/associated-items/active/0000-associated-items.md#clearer-trait-matching) agrees with me.

[reddit discussion](http://www.reddit.com/r/rust/comments/2rql1m/implementing_foreign_traits_parameterized_with/)

### LINKED ISSUE #20974: The new coherence rules disable very useful patterns
Specifically that input parameters cannot be used as proof of coherence, i.e. `impl ExternTrait<LocalType> for ExternType`, is no longer allowed. 

I've hit this in Iron pretty hard, with this simplified example:

Crate 1: (rust-modifier)

```rust
trait Modifier<M> { .. }
```

Crate 2: (hyper)

```rust
pub enum Status { .. }
```

Crate 3: (iron)

```rust
struct Response { .. }

// None of these impls are legal anymore, which is a massive ergonomic
// regression, since it will require a series of wrapper types instead.

impl Modifier<Response> for Status { .. }
impl<'a> Modifier<Response> for &'a str { .. }
impl Modifier<Response> for String { .. }
impl Modifier<Response> for Vec<u8> { .. }
impl Modifier<Response> for Box<Reader + Send> { .. }
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Update the coherence rules to "covered first" -- the first type parameter to contain either a local type or a type parameter must contain only covered type parameters.

cc #19470.
Fixes #20974.
Fixes #20749.

r? @aturon

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Still running make check locally.

**Comment by nikomatsakis** [comment]
OK, tweaked a few tests, should pass make check now (though the last few bits are still running).

**Comment by aturon** [comment]
Looks good. One question: presumably the error messages need to be updated to clarify the new rule? Unless they were vague enough before that they accurately describe the new rule as well?

**Comment by nikomatsakis** [comment]
@aturon I felt they were vague enough to still be accurate, but I'm open to suggestions.

**Comment by nikomatsakis** [comment]
Here are the messages in question:

https://github.com/nikomatsakis/rust/blob/ecaa68768cdc1fa82a750998634e9cc3202975f9/src/librustc_typeck/coherence/orphan.rs#L76-L104

**Comment by nikomatsakis** [comment]
Well, you were correct that one of them at least was outdated. (In fact, I had fixed that message, but as part of a commit removing `old-orphan-check` that I was forced to back out.) Good catch!

**Comment by nikomatsakis** [comment]
@aturon I interpreted that as r+ and decided to take advantage of a quiet moment in the bors queue. If we want to tweak error messages further we can always do so.

**Comment by rrichardson** [comment]
I think I am seeing a symptom of this with this code:  http://is.gd/WbOmdE
Please let me know if this is not the case (also I'm sure there are other issues with this code)
```rust
use std::ops::Shl;

pub trait Subscriber {
    type Input;
}

pub trait Publisher<'a> {
    type Output;
}

pub trait Processor<'a> : Subscriber + Publisher<'a> { }

impl<'a, P> Processor<'a> for P
where P : Subscriber + Publisher<'a> { }


impl<'a, PR, PB> Shl<Box<PR>> for Box<PB>
where PR : Processor<'a, Input=<PB as Publisher<'a>>::Output>,
      PB : Publisher<'a, Output=<PR as Processor<'a>>::Input>
{
    type Output = Box<Publisher<'a, Output=<PR as Processor<'a>>::Output> + 'a>;

    fn shl(self, rhs: Box<PR>) -> Box<<Self as Shl<Box<PR>>>::Output> {
        rhs as Box<PB>
    }
}


fn main() {}
```

**Pull request merged**
