### PR TITLE
{compiler-builtins,libc} shim cleanup

### PR DESCRIPTION
**Pull request by tamird**
~~Depends on https://github.com/rust-lang/libc/pull/764; opening early for feedback.~~ r? @alexcrichton

### CODE REVIEW

**Comment by tamird** [comment]
Hm, seems like I should amend the new comments to reference https://github.com/rust-lang/rfcs/pull/1133. WDYT?

**Comment by alexcrichton** [comment]
Using cargo features sounds fine to me!

**Comment by tamird** [comment]
Sounds find to me too! But it doesn't quite work out, which this PR is really about documenting at this point

**Comment by tamird** [comment]
Alright, this is ready for a real look!

**Comment by tamird** [comment]
Rebased.

**Comment by shepmaster** [comment]
```
[00:03:44] tidy error: /checkout/src/test/compile-fail/rmeta_lib.rs:13: line longer than 100 chars
```

**Comment by tamird** [comment]
@shepmaster did you mean to post that elsewhere? that file didn't change in this PR and I don't see that failure anywhere.

**Comment by shepmaster** [comment]
> did you mean to post that elsewhere? that file didn't change in this PR and I don't see that failure anywhere.

It was in the CI run; but it appears someone has restarted it. Perhaps it's an unrelated thing that someone has already fixed...

**Comment by kennytm** [comment]
`dist cross` in rollup #44652 failed. Needs `#![feature(cfg_target_vendor)]`.

<details>

```
[00:49:47] error: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)
[00:49:47]    --> /checkout/src/rustc/libc_shim/../../liblibc/src/unix/mod.rs:247:47
[00:49:47]     |
[00:49:47] 247 |     } else if #[cfg(all(target_os = "netbsd", target_vendor = "rumprun"))] {
[00:49:47]     |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[00:49:47]     |
[00:49:47]     = help: add #![feature(cfg_target_vendor)] to the crate attributes to enable
[00:49:47] 
[00:49:47] error: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)
[00:49:47]    --> /checkout/src/rustc/libc_shim/../../liblibc/src/unix/mod.rs:247:47
[00:49:47]     |
[00:49:47] 247 |     } else if #[cfg(all(target_os = "netbsd", target_vendor = "rumprun"))] {
[00:49:47]     |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[00:49:47]     |
[00:49:47]     = help: add #![feature(cfg_target_vendor)] to the crate attributes to enable
[00:49:47] 
[00:49:47] error: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)
[00:49:47]    --> /checkout/src/rustc/libc_shim/../../liblibc/src/unix/mod.rs:247:47
[00:49:47]     |
[00:49:47] 247 |     } else if #[cfg(all(target_os = "netbsd", target_vendor = "rumprun"))] {
[00:49:47]     |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[00:49:47]     |
[00:49:47]     = help: add #![feature(cfg_target_vendor)] to the crate attributes to enable
[00:49:47] 
[00:49:47] error: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)
[00:49:47]    --> /checkout/src/rustc/libc_shim/../../liblibc/src/unix/mod.rs:247:47
[00:49:47]     |
[00:49:47] 247 |     } else if #[cfg(all(target_os = "netbsd", target_vendor = "rumprun"))] {
[00:49:47]     |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[00:49:47]     |
[00:49:47]     = help: add #![feature(cfg_target_vendor)] to the crate attributes to enable
[00:49:47] 
[00:49:47] error: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)
[00:49:47]    --> /checkout/src/rustc/libc_shim/../../liblibc/src/unix/mod.rs:247:47
[00:49:47]     |
[00:49:47] 247 |     } else if #[cfg(all(target_os = "netbsd", target_vendor = "rumprun"))] {
[00:49:47]     |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[00:49:47]     |
[00:49:47]     = help: add #![feature(cfg_target_vendor)] to the crate attributes to enable
[00:49:47] 
[00:49:47] error: `cfg(target_vendor)` is experimental and subject to change (see issue #29718)
[00:49:47]    --> /checkout/src/rustc/libc_shim/../../liblibc/src/unix/mod.rs:247:47
[00:49:47]     |
[00:49:47] 247 |     } else if #[cfg(all(target_os = "netbsd", target_vendor = "rumprun"))] {
[00:49:47]     |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[00:49:47]     |
[00:49:47]     = help: add #![feature(cfg_target_vendor)] to the crate attributes to enable
[00:49:47] 
[00:49:47] error: aborting due to 6 previous errors
[00:49:47] 
[00:49:47] error: Could not compile `libc`.
```

</details>

**Comment by tamird** [comment]
Fixed!

**Comment by tamird** [comment]
```
error: Could not remove file: C:\projects\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\libcompiler_builtins-7054340c38d0eb75.rlib.
Caused by:
  Access is denied. (os error 5)
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "test" "--target" "x86_64-pc-windows-msvc" "-j" "2" "--release" "--locked" "--color" "always" "--features" "panic-unwind backtrace profiler" "--manifest-path" "C:\\projects\\rust\\src/libstd/Cargo.toml" "-p" "std:0.0.0" "-p" "core:0.0.0" "-p" "collections:0.0.0" "-p" "panic_abort:0.0.0" "-p" "unwind:0.0.0" "-p" "std_unicode:0.0.0" "-p" "alloc_system:0.0.0" "-p" "libc:0.0.0" "-p" "alloc:0.0.0" "-p" "rand:0.0.0" "-p" "compiler_builtins:0.0.0" "--"
expected success, got: exit code: 101

```
Not sure what to make of that...

**Comment by tamird** [comment]
Same error:
```
error: Could not remove file: C:\projects\rust\build\x86_64-pc-windows-gnu\stage1-std\x86_64-pc-windows-gnu\release\deps\libcompiler_builtins-127d72c3245de4b7.rlib.
Caused by:
  Access is denied. (os error 5)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by alexcrichton** [comment]
I don't think that's spurious. I don't know what it is, but I don't think it's spurious.

**Comment by kennytm** [comment]
Should be reproducible by `./x.py test --stage1 src/libstd` on Windows if not spurious.

**Comment by alexcrichton** [comment]
@bors: r-

reappeared in the travis queue

**Comment by alexcrichton** [comment]
@tamird do you plan on investigating a fix for this?

**Comment by tamird** [comment]
I'd love to, but I'm not sure how to proceed. Any advice?

**Comment by alexcrichton** [comment]
It's probably best to split up this PR to start off with and figure out precisely which chunk relates to the regression, I don't know personally what's going on here. Failing that the next best thing to do would be to reproduce locally

**Comment by tamird** [comment]
@alexcrichton can we give this another try?

**Comment by kennytm** [comment]
Still the same error.

<details>

```
[00:57:45] Testing libstd stage1 (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
[00:57:51]    Compiling rand v0.0.0 (file:///C:/projects/rust/src/librand)
[00:57:51]    Compiling compiler_builtins v0.0.0 (file:///C:/projects/rust/src/rustc/compiler_builtins_shim)
[00:57:51]    Compiling core v0.0.0 (file:///C:/projects/rust/src/libcore)
[00:57:51]    Compiling alloc v0.0.0 (file:///C:/projects/rust/src/liballoc)
[00:57:54]    Compiling std_unicode v0.0.0 (file:///C:/projects/rust/src/libstd_unicode)
[00:57:55] error: Could not remove file: C:\projects\rust\build\x86_64-pc-windows-gnu\stage1-std\x86_64-pc-windows-gnu\release\deps\libcompiler_builtins-127d72c3245de4b7.rlib.
[00:57:55] 
[00:57:55] Caused by:
[00:57:55]   Access is denied. (os error 5)
[00:57:55] warning: build failed, waiting for other jobs to finish...
[00:58:42] error: build failed
```

</details>

**Comment by tamird** [comment]
Uno mas?

**Comment by alexcrichton** [comment]
Hm I believe what's happening here is that the `compiler-builtins` crate is getting recompiled when it shouldn't. I don't know why that may be the case, though. I'm not sure that increasing appveyor verbosity will help much though. What you can do though is temporarily edit `appveyor.yml` on this branch to only have one build and debug through that if you don't have a Windows machine locally.

**Comment by alexcrichton** [comment]
@tamird do you have a windows machine to test this on locally with? Or any luck using appveyor to test this PR?

**Comment by tamird** [comment]
Haven't come back to this yet; will see about doing that today

**Comment by tamird** [comment]
@alexcrichton I edited `appveyor.yml` as you suggested, but how do I trigger single appveyor builds?

**Comment by alexcrichton** [comment]
@tamird you'll also need to enable appveyor for the `auto` branch

**Comment by alexcrichton** [comment]
Looking at the logs there, the fact that the build script is running is actually a bug I believe, maybe try setting `RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info` to see why the build script is being rerun?

**Comment by tamird** [comment]
Thanks for the hint!
```
INFO:cargo::ops::cargo_rustc::fingerprint: stale: C:\projects\rust\src\rustc\compiler_builtins_shim\build.rs -- missing
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for compiler_builtins v0.0.0 (file:///C:/projects/rust/src/rustc/compiler_builtins_shim): mtime based components have changed: previously Some(FileTime { seconds: 13151797507, nanos: 852703300 }) now None, paths are "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage1-std\\x86_64-pc-windows-gnu\\release\\build\\compiler_builtins-6a0431bf00803b6f\\output" and "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage1-std\\x86_64-pc-windows-gnu\\release\\build\\compiler_builtins-6a0431bf00803b6f\\output"
INFO:cargo::ops::cargo_rustc::fingerprint:   cause: mtime based components have changed: previously Some(FileTime { seconds: 13151797507, nanos: 852703300 }) now None, paths are "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage1-std\\x86_64-pc-windows-gnu\\release\\build\\compiler_builtins-6a0431bf00803b6f\\output" and "C:\\projects\\rust\\build\\x86_64-pc-windows-gnu\\stage1-std\\x86_64-pc-windows-gnu\\release\\build\\compiler_builtins-6a0431bf00803b6f\\output"
```
Not sure what to make of this, though. mtime is now None? Does that mean the file was removed?

**Comment by alexcrichton** [comment]
The bug I think is [this line](https://github.com/rust-lang-nursery/compiler-builtins/blob/fe8d893a6b713edda0707b5b535270ebe0678b5f/build.rs#L6) because with the presence of `src/rustc/compiler-builtins-shim/build.rs` it's say "rerun if that file changed" but that file's being deleted in this PR, so it's saying "rerun if this file that doesn't exist changed" which means it's always being rerun!

It's probably fine to just make `build.rs` an empty file with a comment as to why.

**Comment by tamird** [comment]
We could just remove that from upstream, right? The docs at http://doc.crates.io/build-script.html state:
> Note that if the build script itself (or one of its dependencies) changes, then it's rebuilt and rerun unconditionally, so cargo:rerun-if-changed=build.rs is almost always redundant (unless you want to ignore changes in all other files except for build.rs).

**Comment by alexcrichton** [comment]
I commented on the associated PR, but to comment here as well, we want this directive when developing the compiler-builtins crate because only modifications to the build script should rerun the build script.

**Comment by tamird** [comment]
Yup, thanks for your help. Done!

**Comment by alexcrichton** [comment]
@bors: r+

Ok hopefully we're good to go now! Sort of a crazy coincidence this ever worked.

**Comment by tamird** [comment]
Urgh. Fixed the license.

**Pull request merged**
