### PR TITLE
Update rand deps

### PR DESCRIPTION
**Pull request by klensy**
rand 0.7 -> 0.8
rand_xorshift 0.2 -> 0.3

This gives -6 crates for rustc compiler build

### CODE REVIEW

**Comment by klensy** [comment]
Should i add rand_core_0_6 here too?
https://github.com/rust-lang/rust/blob/d2b04f075c0ce010758c4c8674152ff89d1d73f3/src/tools/rustc-workspace-hack/Cargo.toml#L73

**Comment by Mark-Simulacrum** [comment]
Can you at least cite the changelogs for the updated crates? For example, the note about different results on big endian platforms may mean that we need to check our usage of those functions in the compiler, but it sounds like that investigation has not been done?

Generally speaking updates to dependencies of the compiler or standard library that aren't just used in tests need some scrutiny for potential breakage caused by their new implementations and it's quite helpful if you provide a summary of what checking has been done (e.g., for each compatibility note in the crates' changelog, or similar listing). Alternatively, if it seems like the bump has no compatibility implications, then explicitly indicating that in the PR/commit description and why would also be helpful.

**Comment by klensy** [comment]
Changes for rand 0.8 https://github.com/rust-random/rand/blob/master/CHANGELOG.md#080---2020-12-18 (this is for 0.8.0, description for up to 0.8.3 higher)

Changes for rand_xorshift 0.3 https://github.com/rust-random/rngs/blob/master/rand_xorshift/CHANGELOG.md#030---2020-12-18

Existing tests that was broken by dependency update was fixed.

There is only one place where rand used not for test (as far as i can see):
https://github.com/rust-lang/rust/blob/81053b912fab51978f4806cddfc37eb9a9a5afc6/compiler/rustc_incremental/src/persist/fs.rs#L458-L473

and i don't see how this can broke anything, as we simply generate random number for folder name.

**Comment by klensy** [comment]
Should i add something?

**Comment by klensy** [comment]
Ha-ha, actually breaks.
https://github.com/rust-random/getrandom/blob/master/CHANGELOG.md#020---2020-09-10
> Unsupported targets no longer compile 

https://docs.rs/getrandom/0.2.3/getrandom/#webassembly-support
> Instead, if the "js" Cargo feature is enabled, this crate will assume that you are building for an environment containing JavaScript, and will call the appropriate methods.

**Comment by Mark-Simulacrum** [comment]
I don't have the bandwidth to investigate this failure and suggest a course of action for the wasm32 target; if you have a specific proposal, happy to review that though.

**Comment by klensy** [comment]
I didn't changed anything yet, so it will fail for wasm again.

**Comment by JohnCSimon** [comment]
Ping for triage: 

@klensy can you please post your status on this PR?

**Comment by JohnCSimon** [comment]
Ping from triage:
@klensy 
Please adjust the label with `@rustbot ready` if this PR is ready for another review.

**Comment by JohnCSimon** [comment]
@klensy
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
