### PR TITLE
CFI: Repair vtables without altering types

### PR DESCRIPTION
**Pull request by maurer**
This is an alternative to #121962 intended to showcase two possible design alternatives discussed in the doc there:

1. Instead of altering the *type* of `Instance`s so that they fit the principally-typed expectations of KCFI, we feed the `Instance` information into the CFI typeinfo generator and *it* performs the adjustments.
2. Since call shims were brought up as a concern due to being potential gadgets, this shows how we could instead just generate a different copy of the function in question. It does currently still generate a call shim for the case where the trait was implemented in a different crate than the one producing the vtable, but if that's a blocker more modifications could be added to remove that.

Note that this *does not* remove the new Instance variant generation. I am not convinced it is possible to support KCFI without generating variant instances or something equivalent, as argued in the [design doc](https://hackmd.io/6U7gB9SkQBWV9l4iIsp3Jg?view#Multiple-Variants-are-Required).

r? @workingjubilee

### CODE REVIEW

**Comment by maurer** [comment]
As a note, unlike the main PR, I have not:
1. Built and run a CFI'd compiler with this approach
2. Built and run a KCFI'd kernel

I have only ensured the tests are working. If this approach is selected I will validate it further.

**Comment by rcvalle** [comment]
For anyone that commented on this PR and also anyone new to this PR, see my comments in https://github.com/rust-lang/rust/pull/116404#issuecomment-2008602437.

**Comment by workingjubilee** [comment]
Well, this obviously would need a rebase, but also it's not clear that we're going to take exactly this route since #123012 so!

@rustbot author

**Comment by maurer** [comment]
I'm closing this PR as I'm landing smaller pieces of this one by one with some variations. The branch will still be there for reference until we finish fixing the overall vtable issues in case we need to crib solutions from it.

**Pull request closed without merging**
