### PR TITLE
[Experiment] Allow undisambiguated generic arguments in patterns

### PR DESCRIPTION
**Pull request by varkor**
I want to try a crater run to see whether this has any unexpected consequences.

r? @ghost

### CODE REVIEW

**Comment by varkor** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
We currently has two path flavors - requiring disambiguation for generic arguments (`a::<b>`, `Fn::(C)`) and not requiring disambiguation (`a<b>`, `Fn(C)`). (We exclude paths not allowing generic arguments at all.)

This PR adds a third flavor - requiring disambiguation for `(`, but not `<` (`a<b>`, `Fn::(C)`), intended specifically for patterns because patterns have "calls" (`TupleStruct(..)`) but not comparison of shift operators.
This should work (modulo bugs in the PR), and I wouldn't spend several days of crater on this, but I'm not sure the motivation is strong enough - generic arguments in patterns are exceptionally rare.

**Comment by varkor** [comment]
I also expect it to work, but since the crater queue was empty until yesterday, I thought it was worth confirming there weren't any overlooked edge cases. I'm happy to cancel the crater run if another PR needs to run crater. I also haven't spent much time looking into when generics in patterns come up in practice; they do seem relatively rare. This was in part an experiment to check how much it was necessary to change to make `::` optional in these contexts.

**Comment by jyn514** [comment]
@varkor are you still planning to work on this?

**Comment by varkor** [comment]
@jyn514: I am, but it's clear now that I'm not going to get to this in the immediate future, so I'll close it for the time being.

**Pull request closed without merging**
