### PR TITLE
Remove/replace some outdated crates from the dependency tree

### PR DESCRIPTION
**Pull request by JohnTitor**
- Remove `cloudabi` by updating `parking_lot` to 0.11.1.
- Replace `packed_simd` with `packed_simd2` by updating `bytecount` to 0.6.2.

### CODE REVIEW

**Comment by joshtriplett** [comment]
Seems reasonable. Note that this also pulls in the `libm` crate. That seems fine though.

**Comment by Mark-Simulacrum** [comment]
Hm, something seems wrong with the tidy logic - libm is new (AFAICT) but not listed in the tidy dep filter. @JohnTitor would you be up for investigating that? I'd expect that it would need to get added, but maybe I'm missing something...

**Comment by JohnTitor** [comment]
> 
> 
> Hm, something seems wrong with the tidy logic - libm is new (AFAICT) but not listed in the tidy dep filter. @JohnTitor would you be up for investigating that? I'd expect that it would need to get added, but maybe I'm missing something...

Seems we don't check the deps on submodules/subtrees, the tree looks like:  `rustfmt-nightly -> bytecount -> packed_simd2 -> libm`. For another example, `derive-new`, which is a direct dep on clippy, isn't also catched. Is this desired?

**Comment by Mark-Simulacrum** [comment]
I definitely think we need to be checking those dependencies. However, I don't think we need to block this PR on that; let's file an issue (or even better, a PR if you'd be willing) to expand the checks to include submodule roots. It'll likely be desirable to indicate whether the dependency is in the compiler or in a tool, though.

@bors r+

**Pull request merged**
