### PR TITLE
`impl Add<Output = String> for &str`

### PR DESCRIPTION
**Pull request by jyn514**
Inspired by https://fasterthanli.me/articles/some-mistakes-rust-doesnt-catch.

cc @fasterthanlime

### CODE REVIEW

**Comment by jyn514** [comment]
Amos says in his blog this may have been intentional: image

but there are already other trait calls that allocate, like `.into()`, and `String + &str` may still need to reallocate even though it uses push_str. I think it's more likely that no one felt like messing around with coherence checks before now.

> This is done to avoid allocating a new String and copying the entire contents on every operation, which would lead to O(n^2) running time when building an n-byte string by repeated concatenation.

Fortunately, `"a" + "b" + "c" ...` has the types `&str + &str + &str`, which after operator precedence leaves you with `String + &str`. So there's no possible O(n^2) runtime introduced by this new impl.

**Comment by joshtriplett** [comment]
Worth considering. This would be convenient, at the expense of potentially unexpected memory allocation.

We should discuss this in a libs-api meeting.

**Comment by jyn514** [comment]
(going to hold off on fixing the tests until I hear whether the libs team wants this - I have to dig into exactly how the diagnostic code works.)

**Comment by m-ou-se** [comment]
I'm opposed to this change, for a few different reasons:

1. It hides allocation. Requiring the left hand side to be a `String` that gets consumed makes it clear that there's an allocation involved, and concatenating strings isn't 'free' like adding two integers is.

2. It's an implementation on the builtin `&str` type, but defined in `alloc`. This means that in `#![no_std]` programs, whether this impl is available or not depends on whether another crate in the tree pulls in `std`/`alloc`. This can get confusing.

3. There are different implementations of allocated strings that are arguably better than `std::string::String`, such as a variant with small string optimization. I'd prefer to not make std's `String` more special than it already is. If another crate provides a better `String2`, that type should be just as ergonomic as `std`'s `String` type. If we use tricks like `impl Add for &str` for our `String` type, then such a `String2` type can never provide the same interface.

**Comment by fasterthanlime** [comment]
> 3\. There are different implementations of allocated strings that are arguably better than `std::string::String`, such as a variant with small string optimization. I'd prefer to not make std's `String` more special than it already is. If another crate provides a better `String2`, that type should be just as ergonomic as `std`'s `String` type. If we use tricks like `impl Add for &str` for our `String` type, then such a `String2` type can never provide the same interface.

Ooh, that's an excellent argument I hadn't considered before. I'm tempted to suggest linking to this thread (or including the rationale inline) somewhere in the stdlib documentation to avoid future PRs like that popping up in the future.

**Comment by m-ou-se** [comment]
> Ooh, that's an excellent argument I hadn't considered before. I'm tempted to suggest linking to this thread (or including the rationale inline) somewhere in the stdlib documentation to avoid future PRs like that popping up in the future.

It's part of a more general theme I want to focus on a bit more this year: Making the standard library 'less special'. One example is that `String` or `Rc` or `Arc` shouldn't be the one and only implementation of their kind, it should just be one convenient implementation that's easily available, but not much more special than a similar type provided by another crate. Reducing the amount of unstable `#![feature]`s the standard library is another thing that we should work on. Next week we'll be talking to the lang team about language features we might want to push towards stabilizing to make some more progress here.

**Comment by joshtriplett** [comment]
I was uncertain about whether (1) was enough to not add this, but I hadn't even thought about (3), and I agree completely.

**Pull request closed without merging**
