### PR TITLE
Portable SIMD subtree update

### PR DESCRIPTION
**Pull request by calebzulawski**
Syncs nightly to the latest changes from rust-lang/portable-simd

r? @rust-lang/libs

### CODE REVIEW

**Comment by workingjubilee** [comment]
This looks correct.

@bors r+ rollup=never

**Comment by calebzulawski** [comment]
That is easy to update manually, but why didn't `x.py test --bless` handle it?

**Comment by workingjubilee** [comment]
uhm, it... should?

**Comment by calebzulawski** [comment]
ah, I realized it's failing on 32-bit targets, I'm on macOS which doesn't have a 32-bit target to bless the tests...

**Comment by calebzulawski** [comment]
I manually updated the 32-bit tests, hopefully they should work now

**Comment by calebzulawski** [comment]
Rebased. @workingjubilee want to try again?

**Comment by workingjubilee** [comment]
Whoops.
@bors r+

**Comment by calebzulawski** [comment]
That's silly, I thought `core::arch::x86_64` always existed when building docs.  Anyway, I removed the link. @workingjubilee hope this works 🙃

**Comment by workingjubilee** [comment]
@calebzulawski Docs are primarily for the user, their ability to be hosted on docs.rs or other docs sites is secondary: that's a choice a user gets to make. Which means docs are built, primarily, for informing you about what's available for the specific build configuration you did. Every crate has to configure docs.rs metadata to get something hostable if there's no defaults.

**Comment by calebzulawski** [comment]
whew

**Comment by lqd** [comment]
Strange regression, but mostly on doc builds. Could be std/core metadata changes.

**Comment by calebzulawski** [comment]
Yeah, idk.  I wouldn't expect these changes to affect performance.  Maybe there are more trait implementations? I can't think of anything significant

**Comment by workingjubilee** [comment]
yeah, if we add a function then there's more docs to generate, them's the breaks.

**Comment by rylev** [comment]
> yeah, if we add a function then there's more docs to generate, them's the breaks.

Seems reasonable to me

@rustbot label: +perf-regression-triaged

**Pull request merged**
