### PR TITLE
evaluate the array length of fixed size array types in rustdoc

### PR DESCRIPTION
**Pull request by oli-obk**
mitgates #34579

to fix it we'd need an expression simplifier.

r? @steveklabnik 

cc @Osspial

### CODE REVIEW

**Comment by steveklabnik** [comment]
This failed Travis, because it looks like some tests were testing that this behavior exists!

**Comment by oli-obk** [comment]
travis likes it now

**Comment by oli-obk** [comment]
fixed `rustc/Cargo.lock`

**Pull request merged**
