### PR TITLE
[WIP] Build the compiler with a single CGU

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by the8472** [comment]
This time instructions might not be painting the whole picture? 🤔

Except for `ctfe-stress-4` and `rustc` max-rss, wall-time, cycles are mostly trending down as opposed their usual mixed results.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this. I think the perf results don't speak to this being a clear win, and certainly it would be a big hit to our CI times.

**Pull request closed without merging**
