### PR TITLE
DRAFT: Add an aarch64-msvc build running on ARM64 Windows

### PR DESCRIPTION
**Pull request by dpaoliello**
r? @Kobzol

### CODE REVIEW

**Comment by dpaoliello** [comment]
Looks like this is blocked by <https://github.com/msys2/setup-msys2/issues/358>

**Comment by ChrisDenton** [comment]
The msys2 setup step was discussed recently and it was concluded that it could possibly be skipped if you can manually get the mingw `make` earlier in PATH than the default make. Though you'd also need to make sure not to override other tools.

run-make tests specifically need the one that uses mingw style paths.

**Comment by dpaoliello** [comment]
> Looks like this is blocked by [msys2/setup-msys2#358](https://github.com/msys2/setup-msys2/issues/358)

I've worked around this by downgrading the `setup-msys2` task to v2.21.0

The bigger issue that I'm hitting now: this is a clean install of Windows, so no VS, Git, GitHub Runner Agent, etc.

**Comment by Kobzol** [comment]
> The bigger issue that I'm hitting now: this is a clean install of Windows, so no VS, Git, GitHub Runner Agent, etc.

Does that somehow differ on ARM vs the old x86 Windows runners?

**Comment by dpaoliello** [comment]
> > The bigger issue that I'm hitting now: this is a clean install of Windows, so no VS, Git, GitHub Runner Agent, etc.
> 
> Does that somehow differ on ARM vs the old x86 Windows runners?

Yes: the x86 runners use a [pre-built image provided by GitHub](https://github.com/actions/runner-images), but GitHub/Microsoft are yet to provide such an image for ARM64 Windows. GitHub's blog post says "with plans to add developer tools to the Windows image" but doesn't provide any timeline for when that'll be available.

I'm going to continue to experiment with installing dependencies during the build, but it may take me a while to get everything working.

**Comment by dpaoliello** [comment]
I'm going to pause this work until there's a Windows ARM64 image with tools preinstalled.

**Pull request closed without merging**
