### PR TITLE
Split `core::alloc` module

### PR DESCRIPTION
**Pull request by TimDiekmann**
No changes to the code itself, only moves `Layout`-related and `GlobalAlloc`-related stuff into private submodules.

r? @Amanieu

### CODE REVIEW

**Comment by Amanieu** [comment]
This is likely to result in a merge conflict once #69799 lands.

**Comment by TimDiekmann** [comment]
Yes, this will result in a merge conflict (tested locally). However, this will be easy to fix and I'm ready to rebase :)

**Comment by TimDiekmann** [comment]
It's also very likely, that #69743 will result in merge conflicts.

**Comment by TimDiekmann** [comment]
Closing in favor of #69889

**Pull request closed without merging**
