### PR TITLE
Doc rewording

### PR DESCRIPTION
**Pull request by king6cong**

### CODE REVIEW

**Comment by Centril** [comment]
Why this rewording? "reaches" fits with the notion of programs reaching a certain state.

**Comment by king6cong** [comment]
> Why this rewording? "reaches" fits with the notion of programs reaching a certain state.

I'm not sure, but I think these are better than `reaches an unrecoverable problem`
* encounters an unrecoverable problem
* reaches an unrecoverable state

**Comment by Centril** [comment]
r? @Centril 

> reaches an unrecoverable state

This variant sounds good to me; @king6cong mind changing to that?

**Comment by Centril** [comment]
@bors rollup

r=me with the change above...

**Comment by king6cong** [comment]
@Centril Updated

**Pull request merged**
