### PR TITLE
fix jobserver GLOBAL_CLIENT_CHECKED uninitialized before use

### PR DESCRIPTION
**Pull request by oksbsb**
override #118589, resolve merge conflict

@petrochenkov @SparrowLii

Thanks!

### CODE REVIEW

**Comment by petrochenkov** [comment]
It's not necessary to create new PRs on conflicts, rebasing and force pushing is enough.
I'll r+ when CI is green.
r? @petrochenkov

**Comment by compiler-errors** [comment]
Possibly the reason for failure in https://github.com/rust-lang/rust/pull/118716#issuecomment-1845963554 ? If not, sorry, my pattern matching is poor in this part of the compiler.

@bors r-

**Comment by oksbsb** [comment]
> Possibly the reason for failure in [#118716 (comment)](https://github.com/rust-lang/rust/pull/118716#issuecomment-1845963554) ? If not, sorry, my pattern matching is poor in this part of the compiler.
> 
> @bors r-

resloved, caused by #118635, it change stderr output.

**Pull request merged**
