### PR TITLE
Use LLVM patch to correct alignments for `i128` and `u128`

### PR DESCRIPTION
**Pull request by tgross35**
This applies https://reviews.llvm.org/D86310 and https://reviews.llvm.org/D158169, which fix the alignment and ABI issues for 128-bit integers. I ran an ABI check on this and we are no compatible with GCC and the current `main` clang.

Zulip discussion: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.2354341.20-.20alignment.20of.20i128.20for.20FFI

This will be a draft since I don't think we are going to backport

r? compiler
@rustbot label +T-compiler

Todo still: pull in the rest of the changes from https://github.com/rust-lang/rust/pull/113880

### CODE REVIEW

**Comment by krasimirgg** [comment]
It seems we may need to also update i686 specs: when locally building this with LLVM @ HEAD and the static_assert_size-s commented out following https://github.com/rust-lang/rust/pull/113880, I'm getting some i686 test failures, e.g., `tests/codegen/abi-efiapi.rs#i686`:
```
compiler/rustc_codegen_llvm/src/context.rs:190:13: data-layout for target `i686-unknown-linux-musl`, `e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128`, differs from LLVM target's `i686-unknown-linux-musl` default layout, `e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-i128:128-f64:32:64-f80:32-n8:16:32-S128`
```

**Comment by nikic** [comment]
@krasimirgg Yes, the i686 data layouts changed as well.

**Comment by tgross35** [comment]
I think this may be superseded by  #116672?

**Comment by tgross35** [comment]
https://github.com/rust-lang/rust/pull/116672 will handle this now, closing

**Pull request closed without merging**
