### PR TITLE
Update the book to fix some edition-related bugs

### PR DESCRIPTION
**Pull request by carols10cents**
I'd love to have this included in a point release if one happens, but the changes aren't worth doing a point release on their own IMO. I'd definitely like to see this backported to beta.

The most urgent changes included here are:

- Chapter 19.6, on macros (including the macro changes that just stabilized), [is cut off](https://github.com/rust-lang/book/issues/1668) because of an ill-placed newline in a comment that [pulldown-cmark interprets incorrectly](https://github.com/raphlinus/pulldown-cmark/issues/124).
- [The `Cargo.toml` shown in the Guessing Game example in Chapter 2 (and one in Chapter 14) doesn't have `edition="2018"`](https://github.com/rust-lang/book/pull/1671), which can be confusing depending on whether the readers have it in theirs or not, think they should remove it if they have it, and the rest of the chapter assumes it's there and the code doesn't compile if you don't have it.
- The redirects implemented as part of only shipping the 2018 edition of the book sometimes lead to [having to click through 2 redirect pages](https://github.com/rust-lang/book/pull/1667) when it could be just one.

There are other small corrections included that were made since the last time the book was updated, but those aren't urgent.

cc @steveklabnik

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Comment by carols10cents** [comment]
Thanks @GuillaumeGomez! 

Should I open another PR for backporting to beta, @Mark-Simulacrum ? And are the labels sufficient to get this picked up if a stable point release happens?

**Comment by Mark-Simulacrum** [comment]
@carols10cents The release team will roll this up into both stable and beta backports (beta for sure, stable if indeed we release a point release). However, this PR does need to be marked `beta-accepted` and `stable-accpeted` as well if that is to happen -- right now it's just nominated; it'll need to be accepted for the backport to happen.

**Comment by pietroalbini** [comment]
cc @rust-lang/docs, should this PR be backported to beta and stable (1.31.1)?

**Comment by QuietMisdreavus** [comment]
Based on the issues mentioned in the PR description, i think this should be backported. I know i've seen people get confused by them already.

**Pull request merged**
