### PR TITLE
libstd/sync/mpsc: relicense under rust license

### LINKED ISSUE #36556: Licensing issue
The files `src/libstd/sync/mpsc/spsc_queue.rs` and `src/libstd/sync/mpsc/spsc_queue.rs` was originally added a long time ago in #10080, and the first line is `Copyright (c) 2010-2011 Dmitry Vyukov. All rights reserved.` (explained in #9710). These files are only licensed under the BSD 2-Clause license.
- The file doesn't contain the usual `Copyright The Rust Developers`, although the team is a co-author.
- Does the second clause means, that rustc should print the whole BSD license just for these? (Or I'm misinterpreting it?)

Is it an issue at all? (I'm not that familiar with distributing and licensing software.) If it is, can we do something about it?

### PR DESCRIPTION
**Pull request by dvyukov**
These files are licensed under a different license
than the rest of the codebase. This causes potential
issues and inconveniences.
Relicense these files under the standard license.
I hold original copyright on that code.

Fixes #36556

### CODE REVIEW

**Comment by alexcrichton** [comment]
Whoa awesome thanks so much @dvyukov! I'm personally not much of a licensing expert myself so I think I'll defer to others like @brson, but I'll be sure that we get a resolution on this soon regardless.

**Comment by steveklabnik** [comment]
Looks great to me; thanks so much for doing this and making things a bit easier ❤️

**Comment by brson** [comment]
I think we can do this without much fuss. The vast majority of the code was written by @alexcrichton based off @dvyukov, and these are all the people have touched these files:

Aaron Turon
Alex Crichton
Andre Bogus
Ariel Ben-Yehuda
Barosl Lee
Brian Anderson
Felix S. Klock II
Huon Wilson
Jeffrey Seyfried
Johannes Oertel
Jorge Aparicio
Manish Goregaokar
Michael Layzell
Nick Cameron
Niko Matsakis
Stepan Koltsov
Steven Fackler
Tamir Duberstein
Tobias Bucher
Vadim Petrochenkov

Almost all these people we know are cool with the Rust license, and their contributions are likely trivial.

So I think we should just do it.

**Comment by brson** [comment]
@bors r-

Oh actually this code was not written by @alexcrichton but by @toffaletti. That gives me pause.

**Comment by brson** [comment]
@toffaletti I wonder if you are around to take a look at this. It is re licensing the queue you wrote for Rust way back in 2013 from BSD to the Rust MIT/Apache-2.0 license.

**Comment by toffaletti** [comment]
@brson I agree to relicensing. Thanks @dvyukov

**Comment by alexcrichton** [comment]
Awesome, thanks @toffaletti!

@bors: r=brson

**Pull request merged**
