### PR TITLE
Add Extend impls for tuples of arity 1 through 12

### PR DESCRIPTION
**Pull request by shahn**

### CODE REVIEW

**Comment by shahn** [comment]
This was discussed in https://github.com/rust-lang/rust/pull/85835#issuecomment-2433273323 and I want to get that effort started. It's been forever since I contributed to rustc, so please excuse if I did something wrong. If this is deemed OK, I would be happy to follow this up with the same treatmeant for `FromIterator` and maybe `unzip, too - but those probably deserve their own PR?

**Review by dtolnay — APPROVED** [review]

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

Among other things, this feature makes `unzip` work for larger (and smaller) tuples.

```diff
  fn main() {
      let iter = std::iter::repeat_n(('a', 'b', 'c'), 3);
-     let (va, (vb, vc)): (Vec<_>, (Vec<_>, Vec<_>)) = iter.map(|(a, b, c)| (a, (b, c))).unzip();
+     let (va, vb, vc): (Vec<_>, Vec<_>, Vec<_>) = iter.unzip();
      println!("{:?}\n{:?}\n{:?}", va, vb, vc);
  }
  ```

**Comment by dtolnay** [comment]
@rfcbot fcp cancel

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

Among other things, this feature makes `unzip` work for larger (and smaller) tuples.

```diff
  fn main() {
      let iter = std::iter::repeat_n(('a', 'b', 'c'), 3);
-     let (va, (vb, vc)): (Vec<_>, (Vec<_>, Vec<_>)) = iter.map(|(a, b, c)| (a, (b, c))).unzip();
+     let (va, vb, vc): (Vec<_>, Vec<_>, Vec<_>) = iter.unzip();
      println!("{:?}\n{:?}\n{:?}", va, vb, vc);
  }
  ```

**Comment by cuviper** [comment]
> Among other things, this feature makes `unzip` work for larger (and smaller) tuples.

How so? This doesn't change `Iterator::unzip` AFAICS, which explicitly operates on pairs -- but either of those pairs could be a *nested* tuple of arity 1..=12 after this change.

**Comment by dtolnay** [comment]
You are right. I've updated the motivating use case to use `collect_into` instead of `unzip`. Or please let me know if someone knows a better one.

**Comment by shahn** [comment]
This came from https://github.com/rust-lang/rust/pull/85835#issuecomment-2433273323

**Comment by shahn** [comment]
I noticed I made a silly mistake, I added tuple impls for not just 12-tuples but 13-tuples accidentally. I am also adding some tests for these impls, but I wonder, is there a good example to verify 13-tuples do *not* have the Extend impl?

I also want to add the FromIterator<(EA, ...)> for (A, ...) impls. Should these go into a new PR?

**Comment by shahn** [comment]
it would be awesome to get your opinion here, @joshtriplett @m-ou-se @BurntSushi - thanks!

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
