### PR TITLE
Removed `in_band_lifetimes` from `rustc_trait_selection`

### PR DESCRIPTION
**Pull request by lameferret**
Issue: [#91867](https://github.com/rust-lang/rust/issues/91867)

Wasn't able to run `./x.py build --stage 0 compiler/rustc_trait_selection/` got 
`thread 'main' panicked at 'error: no rules matched compiler/rustc_trait_selection/', src/bootstrap/builder.rs:236:17` only ran `./x.py check`
Is this the supposed behaviour ?

### CODE REVIEW

**Comment by oli-obk** [comment]
> Is this the supposed behaviour ?

Well... kind of. Even if that one crate compiles, you still need to check if the rest of the compiler still works, as other parts of the compiler depend on that one crate.

@bors r+ rollup

**Comment by jackh726** [comment]
Duplicate of #91904, sorry!

**Comment by camelid** [comment]
> Wasn't able to run `./x.py build --stage 0 compiler/rustc_trait_selection/`

Why are you passing `--stage 0`? Don't pass a `--stage` flag in this case.

**Comment by anuvratsingh** [comment]
> > Wasn't able to run `./x.py build --stage 0 compiler/rustc_trait_selection/`
> 
> Why are you passing `--stage 0`? Don't pass a `--stage` flag in this case.

> To build a compiler, run ./x.py build. This will build up to the stage1 compiler, including rustdoc, producing a usable compiler toolchain from the source code you have checked out.
> For hacking, often building the stage 1 compiler is enough, but for final testing and release, the stage 2 compiler is used.
> From [rust-dev-guide](https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html)

Reading this, I thought stage 0 would give the fastest compile time and errors I'm interested in, later on I can check stage1 and 2 before pushing.

**Comment by camelid** [comment]
> And I tried without `stage` flag, got same error

Yeah, that part's probably because of https://github.com/rust-lang/rust/pull/91927#issuecomment-993834536. Still, `--stage 0` is incorrect here.

**Pull request closed without merging**
