### PR TITLE
Add copy bound to atomic & numeric intrinsics

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by eddyb** [comment]
Blocked on #70088.

But until then, let's see if all of these bounds slow down compilation:
@bors try @rust-timer queue

**Comment by eddyb** [comment]
Wait, this is silly, only `core`'s compilation would be slowed down, nothing uses the intrinsics directly.
And the results are likely all noise.

Sorry for the unnecessary delay, I didn't think the implications through properly.
@bors r+

**Comment by bjorn3** [comment]
All regressions are for incremental mode.

**Pull request merged**
