### PR TITLE
Correctly handle impl trait in external items in rustdoc

### LINKED ISSUE #49373: Rustdoc doesn't render all `impl Trait` details
Given a function definition

```rust
pub fn timeout<'a>(&'a mut self, duration: Duration) -> impl Future<Item=(), Error=!> + 'a
```

then this is currently (`rustc 1.26.0-nightly (482a913fb 2018-03-25)`) rendered as

impl-trait-doc

There are two very important bits of information missing from this:

 * The associated types of the `Future` trait
 * The lifetime bound on the returned type

### PR DESCRIPTION
**Pull request by Manishearth**
fixes #49373

r? @QuietMisdreavus

### CODE REVIEW

**Comment by Manishearth** [comment]
(test coming soon)

**Comment by Manishearth** [comment]
cc @alexcrichton we may want this for the beta

**Comment by alexcrichton** [comment]
Ah sorry but it's too late at this point to make it into 1.25 unless this is **really** urgent

**Comment by Manishearth** [comment]
Oh, I'm talking about the 1.26 beta -- the beta that's being created soon. We can backport this later as well, I figure that if we can merge this in now (provided it gets reviewed before) that would be easier.

**Comment by GuillaumeGomez** [comment]
Tests are failing btw.

**Comment by Manishearth** [comment]
Yeah, it's tidy, forgot to fix it

**Comment by Manishearth** [comment]
Fixed

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Pull request merged**
