### PR TITLE
Apply size optimizations to panic machinery and some cold functions

### PR DESCRIPTION
**Pull request by the8472**
* std dependencies gimli and addr2line are now built with opt-level=s 
* various panic-related methods and `#[cold]` methods are now marked `#[optimize(size)]` 

Panics should be cold enough that it doesn't make sense to optimize them for speed. The only tradeoff here is if someone does a lot of backtrace captures (without panics) and printing then the opt-level change might impact their perf.

Seems to be the first use of the optimize attribute. Tracking issue #54882

### CODE REVIEW

**Comment by the8472** [comment]
Odd, I expected opt builds to get smaller (by not bloating stuff in panic code paths).
But debug builds getting faster and smaller is unexpected.

**Comment by the8472** [comment]
r? libs

**Comment by cuviper** [comment]
I think it could be nice to add `#[optimize(size)] mod backtrace_rs;` too, but that didn't seem to have any effect when I tried it locally just now. In the tracking issue, it sounds like it's still missing propagation for that kind of use.

**Pull request merged**
