### PR TITLE
don't warn about a missing change-id in CI

### LINKED ISSUE #130352: change-id warning shows up as clutter in CI logs
CI logs (specifically the mingw-check PR CI job) have a lot of this:
```
WARNING: The `change-id` is missing in the `config.toml`. This means that you will not be able to track the major changes made to the bootstrap configurations.
NOTE: to silence this warning, add `change-id = 129473` at the top of `config.toml`
NOTE: this message was printed twice to make it more likely to be seen
```
This should probably be silenced on CI to avoid cluttering the logs?
Cc @onur-ozkan

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes #130352

### CODE REVIEW

**Comment by onur-ozkan** [comment]
Why this doesn't work already? https://github.com/rust-lang/rust/blob/e7386b361dda8c2222bee7a1ae79faba7e9a0351/src/ci/run.sh#L50-L53

Directly ignoring the change tracker at the bootstrap level could have negative effects for downstream  CIs.

**Comment by workingjubilee** [comment]
as a downstream CI: I am also ignoring this in my CI because I do not give a fucking shit about all the notifications because they are never fucking relevant to me.

**Comment by workingjubilee** [comment]
if something happens that is important, the CI will probably break. until then, the 9 million tiny changes that only matter to interactive users are not very relevant. it doesn't matter if my eyes glaze over when I see the message or if I actively silence it: the same effect of "I ain't readin' all that" takes place.

**Comment by onur-ozkan** [comment]
> Directly ignoring the change tracker at the bootstrap level could have negative effects for downstream CIs.

Update on this: I initially thought this PR was ignoring the change messages, but it’s actually just skipping the help message for the missing field. That makes sense. I have just created an [alternative PR](https://github.com/rust-lang/rust/pull/130368) that skips the help message for everyone by default unless running in verbose mode.

**Comment by workingjubilee** [comment]
thank you! personally happy to see whatever variation on this people like better land.

**Review by albertlarsan68 — APPROVED** [review]
LGTM, sorry for the delay!

**Comment by onur-ozkan** [comment]
> LGTM, sorry for the delay!

Did you check https://github.com/rust-lang/rust/pull/130368? If so, I will close that one.

**Comment by albertlarsan68** [comment]
I think that those are quite orthogonal

**Pull request merged**
