### PR TITLE
Stabilize -Z strip as -C strip

### PR DESCRIPTION
**Pull request by joshtriplett**
Leave -Z strip available temporarily as an alias, to avoid breaking
cargo until cargo transitions to using -C strip.

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by calavera** [comment]
It looks like this proposal has passed the one week final comments period. It's so good to see it over the final line, thanks for all your work @joshtriplett.

**Comment by joshtriplett** [comment]
@calavera FCP is 10 days, so a few more days to go. Thank you, though.

**Comment by calavera** [comment]
oh, that's interesting, thanks for letting me know. It looks like Google is indexing the wrong thing:

image

**Comment by joshtriplett** [comment]
Rebased.

**Comment by Wyvern** [comment]
Just updated to latest 1.58.0 stable, `strip=true` in `[profile.release]` of .cargo/config.toml still can't work as expected. 

How to activate stable strip feature in release build config?

**Comment by Urgau** [comment]
@Wyvern The release notes clearly state:
> Stabilize -Z strip as -C strip.  [..] **Note that this release only includes support in rustc, not directly in cargo.**

The [cargo stabilization](https://github.com/rust-lang/cargo/pull/10088) was done way after the `rustc` one, you will need to wait one or two release for the `strip = true` to be stable in cargo.

**Comment by edmorley** [comment]
I'm encountering `error: symbols referenced by indirect symbol table entries that can't be stripped in <file>.dylib` errors on macOS, for which I've filed #93988. It seems like it might be occurring after the change in #88137?

**Comment by rimutaka** [comment]
@joshtriplett , sorry, this is probably a wrong PR for my code comment: https://github.com/rust-lang/cargo/commit/75e544d54578c8463ece495fa05b1e812b09e444#r67674858

**Pull request merged**
