### PR TITLE
Implemented shutdown for UdpSocket (fixes #23194).

### LINKED ISSUE #23194: UdpSocket is missing the shutdown method
Should be easy enough to implement! Good first bug for anyone and I'd be willing to mentor.

### PR DESCRIPTION
**Pull request by aatxe**
See title. This should probably have unit tests. So, I'll add those soon (a bit busy right now, but wanted to get this out) and then squash.

### CODE REVIEW

**Comment by jakub-** [comment]
@aatxe Could we concoct a test in the vein of https://github.com/rust-lang/rust/blob/14ce607d9b96ab3c8d5564bcddd553d6f8e175c7/src/libstd/net/tcp.rs#L618?

**Comment by alexcrichton** [comment]
In addition to tests, could you also refactor the implementations of `TcpStream::shutdown` and `UdpSocket::shutdown` to share code?

**Comment by aatxe** [comment]
It seems as though I cannot write any test for this that doesn't just yield `Socket is not connected (os error 57)`. I'm not entirely sure this is possible. @alexcrichton asked me to ping him here on IRC.

**Comment by alexcrichton** [comment]
Hm I just wrote a small test locally that passes, it looks like `shutdown` should definitely be able to unblock the read side at least?

```rust
use std::net::UdpSocket;
use std::thread;
use std::os::unix::prelude::*;
fn main() {
    let b = UdpSocket::bind("0.0.0.0:3944").unwrap();

    let _t = thread::scoped(|| {
        let mut b = &b;
        println!("a");
        assert!(b.recv_from(&mut []).is_err());
        println!("here");
    });

    let fd = b.as_raw_fd();
    extern {
        fn shutdown(socket: i32, how: i32) -> i32;
        fn sleep(seconds: u32) -> u32;
    }

    unsafe {
        sleep(1);
        println!("shutting down");
        println!("{}", shutdown(fd as i32, 2));
        println!("shut down");
    }
}
```

**Comment by aatxe** [comment]
I have what appears to me to be an almost identical test that's still failing with the same issue. I must be missing something here. Hopefully, you can pick it out. I tried adding sleep just as you did, but it didn't help.

```rust
    #[test]
    fn udp_shutdown_smoke() {
        each_ip(&mut |addr, _| {
            let sock = t!(UdpSocket::bind(&addr));

            let _t = thread::scoped(|| {
                let mut sock = &sock;
                assert!(sock.recv_from(&mut []).is_err());
            });

            t!(sock.shutdown(Shutdown::Read));
        })
    }
```

**Comment by alexcrichton** [comment]
Hm, you may need to fiddle with the synchronization there to guarantee that the `shutdown` happens *after* the socket is already blocked in `recv`. I would expect, however, that a socket which has been shut down prevents all future reads as well, so I'm a little curious as to why you're getting an error. Could you paste the logs of the test?

**Comment by aatxe** [comment]
I had tried adding the sleep, too. It didn't make a difference.
Here's a log of the tests: http://lpaste.net/124415

**Comment by alexcrichton** [comment]
Hm interestingly enough it appears I wasn't even reading the output of my program! It also appears to return an error (of the same kind). Oddly enough it looks like it *also* unblocks any pending read (but not future reads).

In light of this we may not want to expose this at this time. One can indeed `connect` a UDP socket to another address, but we don't currently expose support for that. I think it may be best to actually hold off on this for now until a need for it arises, how does that sound?

**Comment by aatxe** [comment]
Seems fair to me.

**Comment by alexcrichton** [comment]
Ok, thanks anyway for looking into this @aaxte!

**Pull request closed without merging**
