### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by ehuss**
12 commits in 90691f2bfe9a50291a98983b1ed2feab51d5ca55..1e8703890f285befb5e32627ad4e0a0454dde1fb
2021-03-16 21:36:55 +0000 to 2021-03-26 16:59:39 +0000
- tests: Tolerate "exit status" in error messages (rust-lang/cargo#9307)
- Default macOS targets to `unpacked` debuginfo (rust-lang/cargo#9298)
- Fix publication of packages with metadata and resolver (rust-lang/cargo#9300)
- Fix config includes not working. (rust-lang/cargo#9299)
- Emit note when `--future-incompat-report` had nothing to report (rust-lang/cargo#9263)
- RFC 3052: Stop including authors field in manifests made by cargo new (rust-lang/cargo#9282)
- Refactor feature handling, and improve error messages. (rust-lang/cargo#9290)
- Split out cargo-util package for cargo-test-support. (rust-lang/cargo#9292)
- Fix redundant_semicolons warning in resolver-tests. (rust-lang/cargo#9293)
- Use serde's error message option to avoid implementing `Deserialize`. (rust-lang/cargo#9237)
- Allow `cargo update` to operate with the --offline flag (rust-lang/cargo#9279)
- Fix typo in faq.md (rust-lang/cargo#9285)

### CODE REVIEW

**Comment by klensy** [comment]
This actually bump versions for some other crates, is it intended?

**Comment by ehuss** [comment]
@klensy Yes, Cargo bumped the requirements for those dependencies.

**Comment by ehuss** [comment]
Blocked on PR https://github.com/rust-lang/rls/pull/1725

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/83422#issuecomment-805278784)

**Comment by Dylan-DPC** [comment]
ah this was marked as blocked but the rollup wasn't stopped

**Comment by ehuss** [comment]
@Dylan-DPC Oh, I'm sorry. I thought bors kicked it out of the queue when the checks failed. I was not paying attention.

@bors r-

**Comment by ehuss** [comment]
@bors r+ p=1
Unblocks #83462

**Pull request merged**
