### PR TITLE
Fix typo in generics.rs

### PR DESCRIPTION
**Pull request by eltociear**
paramater -> parameter

### CODE REVIEW

**Comment by JohnTitor** [comment]
You should update the test outputs that are affected by this change, with `./x.py test src/test/ui/const-generics/diagnostics.rs --bless`.

**Comment by crlf0710** [comment]
@eltociear Ping from triage, would you mind fixing the test suite according to the instructions above? Thanks.

**Comment by JohnCSimon** [comment]
@eltociear Ping again from triage, would you mind fixing the test suite according to the instructions above? Thank you.

**Comment by eltociear** [comment]
@JohnCSimon Thank you noticing.
I tried it but return errors.

like this.

```
error: linker `x86_64-w64-mingw32-gcc` not found
  |
  = note: 指定されたファイルが見つかりません。 (os error 2)　→（Target file not found.）

error: linker `x86_64-w64-mingw32-gcc` not found
  |
  = note: 指定されたファイルが見つかりません。 (os error 2)

error: aborting due to previous error

error: aborting due to previous error

error: could not compile `memchr`

```

**Comment by JohnTitor** [comment]
Seems you're using the Windows MinGW target, could you follow this instruction?: https://github.com/rust-lang/rust#mingw

**Comment by crlf0710** [comment]
@eltociear Ping from triage, any updates on this?

**Comment by eltociear** [comment]
@crlf0710 no...

**Comment by Dylan-DPC** [comment]
given how tiny this pr is, going to close it. Whenever you have the time, it would be much faster to just make the change again. Thanks

**Pull request closed without merging**
