### PR TITLE
docs: show how to stringify the output of Command

### PR DESCRIPTION
**Pull request by beyarkay**
This documentation-only change clarifies how the user can get the string representation of the output of a command.

The `stdout` and `stderr` members of `std::process::Output` from `std::process::Command` return a Vec<u8>, which is not always what the user wants.

For simple cases like printing `stderr` iff the `std::process::ExitStatus` is non-zero, it's useful to get the string representation of this `Vec<u8>`. This can be done via `String::from_utf8_lossy`, but it's not clear that this is possible from the documentation without first searching the internet for an answer.

Link to playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8189f65dc4b354a643311af2cea5b230

### CODE REVIEW

**Comment by joshtriplett** [comment]
Rather than calling lossy string conversions, how about adding an example to the documentation showing how to print the error output to stderr without converting it? That just requires a call to write_all.

**Comment by beyarkay** [comment]
Happy to remove the lossy conversion, although I initially favoured using the `assert_eq` since it'll be run as a unit test (I believe?). I've re-written the example below to remove the lossy conversion but keep the assert.

I haven't used `stdout` much before. Just to make sure I understand you correctly, would the example look something like this ([link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=308d638c5ba860da3c30080296bf8a7e)):

```rs
#![allow(unused)]
use std::io::{self, Stdout, Write};
use std::process::Command;

fn main() -> io::Result<()> {
    let output = if cfg!(target_os = "windows") {
        Command::new("cmd")
            .args(["/C", "echo hello"])
            .output()
            .expect("failed to execute process")
    } else {
        Command::new("sh")
            .arg("-c")
            .arg("echo hello")
            .output()
            .expect("failed to execute process")
    };

    // Note that `output.stdout` is a slice of bytes
    assert_eq!(&output.stdout, b"hello\n");

    // It can be written to stdout as a string either via stdout.write_all:
    let mut stdout = io::stdout().lock();
    stdout.write_all(&output.stdout)?;

    // Or via a lossy conversion:
    assert_eq!(String::from_utf8_lossy(&output.stdout), "hello\n");

    Ok(())
}
```

Possibly excluding the `assert_eq`, comments, or `println!`s, depending on what you think? 

Thanks for the help!

**Comment by thomcc** [comment]
> Rather than calling lossy string conversions, how about adding an example to the documentation showing how to print the error output to stderr without converting it? That just requires a call to write_all.

IIRC that fails on windows if it's not UTF-8, FWIW. Although I guess you probably wouldn't get UTF-8 input there (although you could from a program with a different codepage, presumably).

Anyway, I've done or seen the lossy converstion dance here a jillion times and can't think of a case where I've seen the direct logging to stderr, so I think this is fine as is. 

@bors r+ rollup

**Comment by Dylan-DPC** [comment]
fails in [rollup](https://github.com/rust-lang/rust/pull/99214) 

@bors r-

**Comment by matthiaskrgr** [comment]
also failed earlier here: https://github.com/rust-lang/rust/pull/99439#issuecomment-1188545797

**Comment by beyarkay** [comment]
So based on [rust-log-analyzer](https://github.com/rust-lang/rust/pull/99439#issuecomment-1188545797):
```
stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"hello\r\n"`,
 right: `"hello\n"`', src\process.rs:19:1
```
It seems like the failure was at [std/process:19](https://github.com/rust-lang/rust/blob/master/library/std/src/process.rs#L19) which wasn't modified in my commit, although I do include a similar same assertion.

Happy to modify my changes, but I'm not sure if they were the culprit?

**Comment by beyarkay** [comment]
Sorry, still getting used to the rust PR system. Is there anything I need to do to make this commit merge-able?

Thanks!

**Comment by thomcc** [comment]
It failed in CI when merging, you need to make sure it passes the tests that failed.

**Comment by JohnCSimon** [comment]
@beyarkay
Triage: what is the status of this PR?

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by beyarkay** [comment]
Okay I've hopefully fixed the issue causing the assertions to sometimes fail. My knowledge of OS-specific line endings isn't great, but it looks like on [some builds](https://github.com/rust-lang-ci/rust/actions/runs/2694666586) the assertion would fail because I used `\n` but it was expecting `\r\n`.

Side note, I got confused by [this line](https://github.com/rust-lang-ci/rust/runs/7401247415?check_suite_focus=true#step:25:19454) (reproduced below):
```

failures:

---- src\process.rs - process::Command (line 461) stdout ----
Test executable failed (exit code: 101).

stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"hello\r\n"`,
 right: `"hello\n"`', src\process.rs:19:1                           <--- This line
stack backtrace:
```

Because it reads to me like the error was on line 19 (which made me think it wasn't something I'd caused) but on closer reading it's referring to line 461 which was the issue I'd caused.

I also see that [line 19](https://github.com/rust-lang/rust/pull/99214/files#diff-36874f872091dd105fbb727506ee7e2d9136ed3265acd5a165c8d925d57db7d1R19) is the last line of the first example code block in `process.rs`. Any chance a friendly rustacian could explain why the output refers to line 19?

**Comment by thomcc** [comment]
This looks fine, but you have a merge commit in the history, which we don't allow (See https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy). Can you clean up the git history?

**Comment by JohnCSimon** [comment]
triage: 
@beyarkay ☝️

**Comment by JohnCSimon** [comment]
@beyarkay  
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
