### PR TITLE
Add Iterator::max_size_hint

### PR DESCRIPTION
**Pull request by clarfonthey**
This is an alternative to #48544 (since closed) which adds a `max_size_hint` method to `Iterator`. It should be merged after #56932, and the actual change is in commit 21348899c7c3068028d6c490edd3482f5e6392bb.

The idea of a "minimum size" is confusing for iterators and iterables, because it's unclear where this should exactly be described. However, the maximum size is unambiguous and will improve the upper bound hints for `flatten` and `flat_map`.

I figured that I'd create a PR here so that people can discuss the change, even though it probably won't be added immediately.

### CODE REVIEW

**Comment by Centril** [comment]
How does this square with boat's comment about object safety?

**Comment by scottmcm** [comment]
I'm pretty sure the upper bounds are (sadly) completely unused: https://internals.rust-lang.org/t/is-size-hint-1-ever-used/8187?u=scottmcm

So I'm not sure how much good this will do in practice, much as I like it in theory.

**Comment by clarcharr** [comment]
> How does this square with boat's comment about object safety?
> (i.e. will you be able to make Travis go green?)

You're right-- I've changed from a constant to a method instead. This limits its use in constants until some version of `const Trait` comes around, but it should do fine for all uses in `size_hint`.

**Comment by Dylan-DPC** [comment]
ping from triage @clarcharr @alexcrichton any updates on this?

**Comment by alexcrichton** [comment]
I wonder if this would perhaps be best moved to an internals thread or an issue? The description of this PR indicates it's largely here for discussion, but it doesn't seem to have a lot of discussion.

**Comment by clarcharr** [comment]
Honestly? That's reasonable. I'm just going to close this for now because I don't really have the energy to start a discussion for the time being, although I'll revisit this at some point if no one else does.

**Pull request closed without merging**
