### PR TITLE
Lint path statements to suggest using drop when the type needs drop

### LINKED ISSUE #48852: "path statement with no effect" issued even when `drop` makes effect
```rust
struct Droppy;

impl Drop for Droppy {
    fn drop(&mut self) {
        println!("2");
    }
}

fn main() {
    let q = Droppy;
    (||{
        println!("1");
        q;
    })();
    println!("3");
}
```

([playground link](https://play.rust-lang.org/?gist=e92c0b3191c67de1999566da63799dbe&version=stable))

```
warning: path statement with no effect
  --> src/main.rs:13:9
   |
13 |         q;
   |         ^^
   |
   = note: #[warn(path_statements)] on by default
```

Removing the "no effect" line definitely has effect.

The warning may instead suggest to explicitly use `std::mem::drop` if that is what is needed.

### PR DESCRIPTION
**Pull request by Veykril**
Fixes #48852. With this change the current lint description doesn't really fit entirely anymore I think.

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors r+

Thanks! that was quite a long-standing issue

**Comment by molenzwiebel** [comment]
Just for completeness, should this also include a test for types that have drop glue but don't impl Drop themselves? An example being a single-element tuple that contains a Drop type.

**Comment by oli-obk** [comment]
@bors r-

That's a good idea

**Comment by Veykril** [comment]
Added the extra test case

**Pull request merged**
