### PR TITLE
Create `core::fmt::ArgumentV1` with generics instead of fn pointer

### PR DESCRIPTION
**Pull request by nbdd0121**
Split from (and prerequisite of) #90488, as this seems to have perf implication.

@rustbot label: +T-libs

### CODE REVIEW

**Comment by nbdd0121** [comment]
The perf run shows that this change generally improves typechecking perf of `format_args!` but there are seems to be some pathological cases regarding LLVM.

Manually inlining `ArgumentV1::new` into `new_<trait>` doesn't change the perf run result. Maybe adding `#[inline(always)]` could help.

Please queue another perf run, thanks!

**Comment by nbdd0121** [comment]
The later perf run shows that typeck is sped up in general, with some regression in debug profile codegen (which is expected, since `#[inline(always)]` will require LLVM to do more work). Is this regression acceptable or maybe shall I try `#[inline]` instead of `#[inline(always)]` to see the difference?

**Comment by joshtriplett** [comment]
I personally think this seems reasonable, but it's worth a perf run to see how regular inline fares.

**Comment by nbdd0121** [comment]
`#[inline]` seems to be slightly better than `#[inline(always)]` in debug builds.

**Comment by joshtriplett** [comment]
I agree. I personally think this looks like a reasonable optimization.

@rustbot label: +perf-regression-triaged

**Comment by camsteffen** [comment]
FYI this will most likely break Clippy unfortunately.

**Comment by jackh726** [comment]
This looks like a libs thing.

r? rust-lang/libs

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed

**Comment by nbdd0121** [comment]
The errors for the failing test are exactly the same, but order of two errors are swapped.

**Comment by nbdd0121** [comment]
It seems that the order change is caused by a FxHashMap used in clippy which makes the order unstable given pertubations to HirId: https://github.com/rust-lang/rust-clippy/blob/3d4d0cf8be8d833c26c95fb61f34a6eab93e916c/clippy_lints/src/index_refutable_slice.rs#L97.

Can someone more knowledgeable in Clippy take a look?

**Comment by Mark-Simulacrum** [comment]
It probably makes sense to swap the FxHashMap with [`FxIndexMap`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/fx/type.FxIndexMap.html).

**Comment by nbdd0121** [comment]
Rebased.

@rustbot ready

**Pull request merged**
