### PR TITLE
Call File::sync_all when finalizing encoding

### PR DESCRIPTION
**Pull request by saethlin**
https://github.com/rust-lang/rust/issues/123352#issuecomment-2048264423

r? @ghost

### CODE REVIEW

**Comment by the8472** [comment]
I'm curious about the motivation. `sync_all` is about guaranteeing that the kernel side dirty pages and metadata have made it to persistent storage. It's _not_ about ensuring that userspace changes make it to the kernel/become visible to other processes.

**Comment by goffrie** [comment]
> I'm curious about the motivation.

In the linked issue, a user repeatedly rebooted a VM, presumably causing the filesystem to lose non-`fsync`ed (i.e. `sync_all`) data and thereby causing rustc to crash. Another user reported the same problem after a power failure.

In general the safe-save pattern (i.e. write a new file, then move it over an existing file) is _not_ safe in the presence of unexpected shutdown without an `fsync` after the new file's contents are written. So adding the `sync_all` call is legitimate in that sense. This LWN article (from 2009) is relevant: https://lwn.net/Articles/351422/

However, `fsync` is a very expensive call and this can be seen in the wall-time perf results (somewhere between 5 and 20 milliseconds). Other hardware and OSes most likely perform even worse. (Not to mention that calling fsync increases write amplification for flash storage which reduces the longevity of the device.)
(I think this PR also performs more fsyncs than are strictly needed as `FileEncoder` is also used in other use cases that may not need the written files to be durably persisted.)

IMO, trying to keep build products consistent in the face of unclean shutdowns is a losing game. Lots of other files get generated during a build, by many different tools (linkers? build scripts?), and those generally don't call `fsync` either. So a system crash could still end up with corrupt build products. They may fail with other cryptic errors rather than a rustc ICE, but the end result for the user is still the same - the build will fail unless they run `cargo clean`.

**Comment by the8472** [comment]
> In general the safe-save pattern (i.e. write a new file, then move it over an existing file) is not safe in the presence of unexpected shutdown without an fsync after the new file's contents are written.

In fact my aim with #82047 was to ensure that we're as non-durable as we can be. This is very useful for repeated rebuilds or short-lived things like UI tests and doctests where the intermediate files are thrown away or replaced soon after they have been created. By avoiding all syncing they only stay in the page-cache and no IO-waits are incurred.

> IMO, trying to keep build products consistent in the face of unclean shutdowns is a losing game

Agreed. Plus there are other sources of corruption, especially on non-checksumming filesystems.
A better approach is to detect the issue and clean the build dir.

**Comment by saethlin** [comment]
> A better approach is to detect the issue and clean the build dir.

I agree that a better approach is to detect the problem. The trouble is actually detecting the problem in a way that doesn't incorrectly detect a compiler issue. Until quite recently, _reproducible_ compiler bugs produced a lot of corrupt output files, and nobody else debugged that. I don't think that accidentally papering over a family of compiler bugs in an attempt to be resilient to misbehaving filesystems or operating systems is a good outcome.

So I'm going to close this and see what I can come up with. Ideally we'd have some sort of telemetry, but maybe a future diagnostic can ask people to comment on an issue.

**Pull request closed without merging**
