### PR TITLE
Fix performance regression with #[instrument]

### PR DESCRIPTION
**Pull request by oli-obk**
linked tracing PR: https://github.com/tokio-rs/tracing/pull/1600

regression introduced by #89048

### CODE REVIEW

**Comment by oli-obk** [comment]
r? rust-lang/compiler

**Comment by joshtriplett** [comment]
Reviewing the results, this looks like a substantial improvement.

**Comment by Mark-Simulacrum** [comment]
I do note that tracing-subscriber now takes ~1.8x as long to compile -- some of that might be noise, but maybe worth mentioning upstream.

The minor performance regressions on a number of benchmarks do seem to be outweighed by the far larger and more consistent wins, though, so this seems good to merge to me in the meantime - we can always bump again if there's further improvements (e.g., to tracing-subscriber compile times).

@bors r+

**Pull request merged**
