### PR TITLE
Remove branch target prologues from `#[naked] fn`

### PR DESCRIPTION
**Pull request by workingjubilee**
This patch hacks around rust-lang/rust#98768 for now via injecting appropriate attributes into the LLVMIR we emit for naked functions. I intend to pursue this upstream so that these attributes can be removed in general, but it's slow going wading through C++ for me.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Hmm, probably should also get input from
cc @npmccallum

**Comment by cjgillot** [comment]
I am not the right reviewer for this.  Do you know who would be better suited @workingjubilee?

**Comment by workingjubilee** [comment]
...honestly I have no idea, this feels like a deeply cursed segment of the compiler and not a lot of hands pass through here. Apparently a lot of recent touches to this were from tmiasko and flip1995, not sure if either are considered compiler reviewers.

**Comment by npmccallum** [comment]
This approach seems sane to me. Perhaps @joshtriplett or @Amanieu might want to look at it?

**Comment by Amanieu** [comment]
LGTM! @bors r+

> What about lowering naked functions into global asm blocks? That way no codegen backend can accidentally add a prologue or epilogue and no codegen backend has to implement naked functions themself, but can piggyback on rustc's lowering for it.

I actually have a WIP branch that does just that, but it's still incomplete and I've been working on other stuff lately. I think this is the best way forward for naked functions in the long term.

**Comment by workingjubilee** [comment]
Sure! I agree that using that approach for handling naked functions is likely quite profitable, though I still think that LLVM should be handling this more correctly in general. At the very least, we shouldn't have to emit per-architecture hints just to disable the same codegen feature on different architectures.

**Pull request merged**
