### PR TITLE
Specialization for Extend<&T> for vec

### LINKED ISSUE #38021: Serialization performance regression
Between **`rustc 1.14.0-nightly (5665bdf3e 2016-11-02)`** and **`rustc 1.14.0-nightly (cae6ab1c4 2016-11-05)`** all of my [serialization benchmarks](https://github.com/serde-rs/json-benchmark) showed a ~50% regression. It affected all the libraries (Serde, json-rust, rustc-serialize). Deserialization was not affected. So far I have narrowed it down to the following code:

```rust
#![feature(test)]

extern crate test;

#[bench]
fn bench(b: &mut test::Bencher) {
    const N: usize = 65536;
    let mut buf = Vec::with_capacity(N);
    b.iter(|| {
        buf.clear();
        for _ in 0..N {
            w(&mut buf, b'[').unwrap();
        }
    });
}

#[inline(never)]
fn w(buf: &mut Vec<u8>, b: u8) -> Result<(), ::std::io::Error> {
    buf.extend_from_slice(&[b]);
    Ok(())
}
```

On my linux laptop this regressed from 160μs to 220μs, on my mac laptop 215μs to 300μs.

cc @bluss who seems to know about `extend_from_slice`.

### PR DESCRIPTION
**Pull request by bluss**
Specialize to use copy_from_slice when extending a Vec with &[T] where
T: Copy.

This specialization results in `.clone()` not being called in `extend_from_slice` and `extend` when the element is `Copy`.

Fixes #38021

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Seems ok to me, thanks!

I'd still ideally prefer to explore the route of adding codegen tests eventually (to ensure we don't regress) but that can happen in a follow-up

**Comment by bluss** [comment]
Ok, there is no codegen test, but codegen for extend_with_slice was examined before it went in, so in that way it's unlikely that it would have been caught that way. It already optimized fine in many situations.

**Comment by bluss** [comment]
@dtolnay This PR fixes the regression in the sense that the regression I found here https://github.com/rust-lang/rust/issues/38021#issuecomment-263090715 was verified to be fixed to be back at its old performance at 1.5-1.6 ms/iter. I haven't done further tests.

**Pull request merged**
