### PR TITLE
deriv(Hash) for single-variant enum should not hash discriminant

### LINKED ISSUE #39137: Derived Hash for repr(u8) enum submits 8 bytes to Hasher instead of 1
Automatically derived `Hash` for an `enum` marked as `repr(u8)` will hash 8 bytes when it is only necessary to hash just one. When hashing large value containing many such enums this will lead to 8x slower hashing than necessary.

Example:

```rust
use std::hash::{Hash, Hasher};

struct H;

impl Hasher for H {
    fn finish(&self) -> u64 {
        unreachable!()
    }

    fn write(&mut self, bytes: &[u8]) {
        println!("{:?}", bytes);
    }
}

#[repr(u8)]
#[derive(Hash)]
enum E {
    A,
    B,
}

fn main() { 
    E::A.hash(&mut H);
}
```

prints `[0, 0, 0, 0, 0, 0, 0, 0]` while I expected it to print `[0]` just like `0u8.hash(&mut H)`.

This behavior is the same on recent stable, beta and nightly (1.14, 1.15, 1.16).

---
EDIT: Added second variant to the enum. Previous example with single variant doesn't print anything anymore because of #42709.

### PR DESCRIPTION
**Pull request by stepancheg**
Fixes #39137

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@jseyfried This is waiting for a review from you, and possibly should get sign off from @rust-lang/libs as well - I don't think if this change is something we want to commit to. Seems fine to me, though.

**Comment by jseyfried** [comment]
Reviewed, r=me if @rust-lang/libs is OK with the new behavior (I don't have a strong opinion either way).

**Comment by alexcrichton** [comment]
@bors: r=jseyfried

Yeah libs-wise this is fine

**Comment by kryptan** [comment]
I don't think this PR fixes #39137.

#39137 is about enums marked with `repr(u8)` (or other similar reprs). This PR affects enums with single variant regardless of their repr.

**Comment by Mark-Simulacrum** [comment]
Reopened.

**Comment by stepancheg** [comment]
@kryptan yes, sorry.

**Pull request merged**
