### PR TITLE
Miri sync

### PR DESCRIPTION
**Pull request by RalfJung**
This is a Miri sync created with my experimental fork of josh. We should probably not merge this yet, but we can use this to check if the sync looks the way it should.

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
Also this does not merge the entire recent Miri history, but only the parts before https://github.com/rust-lang/miri/pull/2554 -- that PR will have to be edited out of the history via a force-push, and the rest then re-constructed by hand.

**Comment by RalfJung** [comment]
Now that we fixed the Miri history, I updated this to sync all the way to Miri master. I also included https://github.com/rust-lang/rust/pull/102573/commits/b85b4808d9ef68c5df1774e2afc17fe201e84d16 with changes on the rustc side: remove the xargo installation, and run PR CI when Miri changes.

Merging this does not fully commit us to using josh forever, in the end these could be just normal commits to the Miri subtree inside rustc. So we could consider merging this before knowing for sure that josh will support our workflow. (But then we'd probably want to include https://github.com/rust-lang/miri/pull/2566.)

**Comment by oli-obk** [comment]
> (But then we'd probably want to include [rust-lang/miri#2566](https://github.com/rust-lang/miri/pull/2566).)

Either way seems fine to me. I'm checking this PR out locally to look at it in a graph, but seems fine to me to merge now and do another sync once more things land on the miri side?

**Review by oli-obk — APPROVED** [review]

**Comment by RalfJung** [comment]
Okay, syncing onto an already existing sync branch is not a thing -- josh will complain
```
remote: hint: Updates were rejected because a pushed branch tip is behind its remote
remote: hint: counterpart. Check out this branch and integrate the remote changes
remote: hint: (e.g. 'git pull ...') before pushing again.
remote: hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
I don't quite understand why this is a problem, given that even when it succeeds the pushed tip does not contain a sync from the rustc repo, but :shrug:

**Comment by RalfJung** [comment]
There is something I don't quite understand though... josh decided to base this branch off of 8e3b9bca65d7d79a3b0e9c33fed8d8c93dd66041, which is quite a bit behind the current master. I did update my master branch to the latest one first so it could have picked a newer one. There seems to be nothing wrong with using that particular commit, but I'd like to understand why it didn't use the latest one...

**Comment by RalfJung** [comment]
On the plus side, if I merge this with master, and then re-extract Miri, I do get something that is compatible with https://github.com/rust-lang/miri/pull/2583. I get a commit with 2 parents: current miri master (the one I used as basis for this PR), and 338c50e which is the commit josh produced for the previous sync. So, it looks perfect.

**Comment by RalfJung** [comment]
```
/checkout/src/test/rustdoc-gui/basic-code.goml basic-code... FAILED
```
looks unrelated

**Comment by oli-obk** [comment]
The new diff lgtm. r=me unless you were still waiting on sth

**Comment by RalfJung** [comment]
The base commit is a bit strange, but it doesn't affect the extracted history... so it's not relevant for roundtrips. (Future versions of josh making different choices here would not be a problem for us.) If we don't mind the rustc history graph becoming even more non-tree-like (the commit this is based on is *not* a bors-created merge commit, it's a commit from inside a PR), then I think we can land this.

**Comment by RalfJung** [comment]
After reproducing the exact same commit with the alternative implementation of the required josh features from https://github.com/josh-project/josh/pull/965, I am confident that this all holds together.

@bors r=oli-obk

**Comment by RalfJung** [comment]
@bors ping
hello, bors?

**Pull request merged**
