### PR TITLE
Revert "Promote missing_fragment_specifier to hard error" #75516

### PR DESCRIPTION
**Pull request by wesleywiser**
Revert of #75516 per #76605.

r? @Mark-Simulacrum 

Note: I only reverted the two commits in #75516 which made the lint a hard error. I did not revert the other two commits in the PR as they seemed fine to leave IMO (commits 84fcd0dc991e2f5b9035d118d8c016f35ab37d0a and eb4d6b520b3e75c7e93f1ea13f1a45eda0687b4e).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r-

(But please reapprove once things are working, or ping me on Zulip and I can drive this to conclusion).

**Comment by wesleywiser** [comment]
I'm having issue running this locally so we should wait until CI is green before r+'ing again.

**Comment by wesleywiser** [comment]
Seems that did it! 

@bors r=Mark-Simulacrum

**Comment by wesleywiser** [comment]
@Mark-Simulacrum any idea why this failed? I can't seem to access the log for the failed builder.

**Comment by Mark-Simulacrum** [comment]
@bors retry


I think the self hosted runners sometimes just die midbuild.

**Pull request merged**
