### PR TITLE
Promote Mac Catalyst targets to Tier 2, and ship with rustup

### PR DESCRIPTION
**Pull request by madsmtm**
Promote the Mac Catalyst targets `x86_64-apple-ios-macabi` and `aarch64-apple-ios-macabi` to Tier 2, as per [the MCP](https://github.com/rust-lang/compiler-team/issues/761) (see that for motivation and details).

These targets are now also distributed with rustup, although without the sanitizer runtime, as that currently has trouble building, see https://github.com/rust-lang/rust/issues/129069.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
r? compiler

**Comment by madsmtm** [comment]
[The MCP](https://github.com/rust-lang/compiler-team/issues/761) has [been accepted](https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Promote.20Mac.20Catalyst.20targets.20to.20Tier.202.20compiler-team.23761/near/448873001), so:

@rustbot ready

**Review by petrochenkov — APPROVED** [review]

**Comment by petrochenkov** [comment]
r? infra

**Comment by GuillaumeGomez** [comment]
I think this PR failed in https://github.com/rust-lang/rust/pull/128030.

@bors r-

**Comment by madsmtm** [comment]
Still have to do some more digging, but it seems like the issue is that we don't pass the `iOSSupport` libraries to CMake, as is [otherwise](https://github.com/rust-lang/rust/blob/1a2b57b426667c60a82214526be949b9e599c914/compiler/rustc_codegen_ssa/src/back/link.rs#L2158-L2159) [done](https://github.com/rust-lang/cc-rs/blob/eb3390615747fde57f7098797b2acb1aec80f539/src/lib.rs#L2790-L2819).

I'll try to fix this in the `cmake` crate, but after that, we'll still have to update `bootstrap` to use the newer `cmake`.

Linking https://github.com/leetal/ios-cmake to myself for later (might contain some of the relevant CMake configuration for this).

**Comment by madsmtm** [comment]
I've disabled the sanitizer runtimes on Mac Catalyst for now and opened https://github.com/rust-lang/rust/issues/129069 for that, to get this moving forwards.
@rustbot ready

I don't _think_ it'll fail to merge again, I've tested it by replacing the `pr` step in `jobs.yml` with the `dist-apple-various` step I've changed, and got a successful build [here](https://github.com/rust-lang/rust/actions/runs/10378750002/job/28735606781) (didn't actually complete, I think since it didn't upload, but the build itself completed).

**Comment by lqd** [comment]
obviously noise

@rustbot label: +perf-regression-triaged

**Review by Booss13 — COMMENTED** [review]
- [ ] - []()

**Pull request merged**
