### PR TITLE
Expand a bit on thread::park spurious wakeups

### LINKED ISSUE #26475: Improve documentation on thread::park returning spuriously
I'm aware that currently there is [no way](https://github.com/rust-lang/rust/blob/a38e7585fc29289581e6cefcdf9e201c3d58ed14/src/libstd/thread/mod.rs#L515) a thread can return from park spuriously, but this is an implementation detail - when/if the new implementation happens it will break anything trying to use `park` because there was previously no way to use it correctly.

(it may be that I've just missed how to do this, in which case I'd consider it a documentation bug and can make a PR)

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #26475 

I'm not sure this is enough, really, but I'm not totally clear on what specific information would be valuable here. In the original issue, the Java page was pretty decent, but now I can't think of a different way to word it, and copying their prose is of course not acceptable.

thoughts @alexcrichton @aturon @aidanhs ?

### CODE REVIEW

**Comment by alexcrichton** [comment]
I feel like this doesn't quite reflect the discussion in #26475, but after re-reading the [module documentation](http://doc.rust-lang.org/std/thread/#blocking-support:-park-and-unpark) I'm not actually sure what clarification is needed. @aidanhs could you weigh in with what you'd like to see?

**Comment by aidanhs** [comment]
The thing missing for me was an explanation of what this library feature brings to the table - the rest of the page talks about things impossible to achieve without library support, whereas this is effectively an optimisation of a busy-wait loop (I can't think of any other uses off-hand).

Some tweaked docs:

> Every thread is equipped with some basic low-level blocking support, via the park and unpark functions. These can be used as a more CPU-efficient implementation of a spinlock.

> The API is typically used by acquiring a handle to the current thread, placing that handle in a shared data structure so that other threads can find it, and then parking (in a loop with a check for the token actually being acquired).

**Comment by steveklabnik** [comment]
I incorporated your suggestions, @aidanhs . Improving the module documentation makes sense too, but I'll take care of that when i run through all of `std::thread` together, I'm just finishing up `std::io`.

**Pull request merged**
