### PR TITLE
Mark payload fields of ScalarPair enums as Scalar::Union when they're not always initialized

### LINKED ISSUE #96158: enum padding incorrectly has Scalar::Initialized layout
https://github.com/rust-lang/rust/pull/94527 extended our `Scalar` layout with the notion of whether a scalar has to be initialized or not. Miri enforces this, and also uses it to know whether it can use a more efficient representation for scalars that *have* to be initialized.

However, in some situations we currently compute a `Scalar::Initialized` layout when it should be `Scalar::Union` (aka "may be uninitialized" -- maybe we should rename it to `Scalar::MaybeUninit`). Specifically, `Option<u32>` [has](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=92914061696d357eb96f359bfa1c9978):
```
           abi: ScalarPair(
               Initialized {
                   value: Int(
                       I32,
                       false,
                   ),
                   valid_range: 0..=1,
               },
               Initialized {
                   value: Int(
                       I32,
                       false,
                   ),
                   valid_range: 0..=4294967295,
               },
           ),
```
Note that this claims that the second field must be always initialized. This is not true though, since for a `None` that second field is padding and hence does not have to be initialized.

This causes https://github.com/rust-lang/miri/issues/2068.
@oli-obk any idea how hard this is to fix?

(To be clear, this bug only causes problems in Miri, not during regular codegen -- at least for now, since we don't [yet] tell LLVM about this "must be initialized" thing.)

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #96158

r? @RalfJung

### CODE REVIEW

**Comment by erikdesjardins** [comment]
I guess this is only layout code
r? @oli-obk

**Comment by oli-obk** [comment]
@bors r+ rollup=never this is strictly a bugfix, but it may have minor perf effects

Thanks for fixing this so fast. I should've reviews those fishy parts better when implemented union scalars

**Comment by oli-obk** [comment]
Looks like the alignments are higher on arm. Maybe ignore the test there?

**Pull request merged**
