### PR TITLE
Add librustc and libsyntax to rust-src distribution.

### LINKED ISSUE #58268: Add some crates sources to "rust-src" distribution.
In `IntelliJ-Rust` and `rls-vscode`, `rust-src` component is used to acquire standard crates sources.
But, in currently, `librustc`, `librustc_plugin`, and `libsyntax` are emitted in the list below.
https://github.com/rust-lang/rust/blob/ad433894abd4231fb2102416a520ae995ee09aed/src/bootstrap/dist.rs#L889
So, syntax highlighting and code completion are not working when using those crates in `IntelliJ-Rust` or `rls-vscode`.

There was similar issue #55279 about `libproc_macro` and it was fixed in #55280.
How about adding those crates (`librustc`, `librustc_plugin`, and `libsyntax`) to the list above, too?

Related issue: https://github.com/intellij-rust/intellij-rust/issues/2623

### PR DESCRIPTION
**Pull request by taeguk**
Fixes #58268.

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @rust-lang/compiler 

@eddyb has concerns about including the plugin crate

**Comment by Centril** [comment]
It doesn't seem like a good idea to facilitate using `librustc_plugin` more in user-space.

**Comment by eddyb** [comment]
Yeah, my question is why `librustc_plugin` specifically? Everything else makes sense.

**Comment by Centril** [comment]
Ping from triage, @taeguk, what are your thoughts re. the question above?

**Comment by taeguk** [comment]
@Centril @eddyb When developing a compiler plugin, `librustc_plugin` is used. So, adding `librustc_plugin` to rust-src distribution is needed for auto completion in IDE. This is just my humble thought.

**Comment by oli-obk** [comment]
We don't want anyone to actually keep developing plugins. We want to get rid of them entirely. Including them in this list sends the wrong message imo.

**Comment by taeguk** [comment]
@oli-obk if so, `librustc_plugin` will not be added to rust-src in my opinion, too.

**Comment by superriva** [comment]
@oli-obk , is a compiler plugin deprecated api?

**Comment by oli-obk** [comment]
>  is a compiler plugin deprecated api?

Not yet, but I want to make it so, since we do have replacement APIs that are stable or in the process of being stabilized.

**Comment by Mark-Simulacrum** [comment]
r=me with rustc_plugin removed.

**Comment by taeguk** [comment]
I removed librustc_plugin.

**Comment by ljedrz** [comment]
```
Build completed successfully in 3:05:50
Command exited with code 259
```
@bors retry

**Comment by ljedrz** [comment]
The same error on a previously green machine.

@bors retry

**Pull request merged**
