### PR TITLE
incr.comp.: Speed up span hashing by caching expansion context hashes.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR fixes the performance regressions from https://github.com/rust-lang/rust/pull/46338.

r? @nikomatsakis

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, could you do a perf run please?

**Comment by Mark-Simulacrum** [comment]
Perf run started. Sorry for the delay.

**Comment by michaelwoerister** [comment]
Hey @Mark-Simulacrum, did that perf run ever finish?

**Comment by Mark-Simulacrum** [comment]
Yes. I generally forget to check back in; they auto-queue and finish within 4 hours at most, and the URLs are fairly easy to generate. Eventually this will be automated...

http://perf.rust-lang.org/compare.html?start=ee25791df5f025378e9ddebef661e25cb75d9172&
end=b867f1811e7bb767d248b0ae46b8fabc16e83bed&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
Thanks @Mark-Simulacrum! I see now how I can compose these URLs myself.

**Comment by michaelwoerister** [comment]
This is now ready for review, @nikomatsakis.

**Comment by michaelwoerister** [comment]
Rebased.
r? @eddyb (@nikomatsakis is a bit swamped right now)

**Review by eddyb — APPROVED** [review]

**Pull request merged**
