### PR TITLE
Add missing tests for 'E-needstest' labeled issues

### LINKED ISSUE #19712: missing-copy-implementations warning only triggers on externally-reachable types.
example, `foo.rs`:

``` rust
#![crate_type = "lib"]
mod inner {
    pub struct Foo {
        pub field: i32
    }
}

pub fn foo() -> inner::Foo {
    inner::Foo { field: 42 }
}
```

`bar.rs`:

``` rust
extern crate foo;

fn main() {
    let f = foo::foo();
    drop(f);
    println!("{}", f.field);
}
```

`foo` compiles cleanly, `bar` doesn't compile because oh no! I've forgotten to make `foo::inner::Foo` `Copy`able.

### LINKED ISSUE #24947: ICE using a trait-associated const in an array size
This only seems to be triggered if the size has to be evaluated by `typeck`; for instance you can use `size_of` on such an array without triggering the issue.

Test case:

``` rust
// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

#![feature(associated_consts)]

struct Foo;

impl Foo {
    const SIZE: usize = 8;
}

trait Bar {
    const BAR_SIZE: usize;
}

impl Bar for Foo {
    const BAR_SIZE: usize = 12;
}

#[allow(unused_variables)]
fn main() {
    let w: [u8; 12] = [0u8; <Foo as Bar>::BAR_SIZE];
    let x: [u8; 12] = [0u8; <Foo>::BAR_SIZE];
    let y: [u8; 8] = [0u8; <Foo>::SIZE];
    let z: [u8; 8] = [0u8; Foo::SIZE];
}
```

In fact, it's fine to use the inherent impl above (in the definitions of `y` and `z`), but the trait-associated constant causes a problem that resembles #24946 and #24938. I'm not sure if it would have the same solution, though, since this issue is encountered at an earlier stage.

### LINKED ISSUE #28600: ICE: pub extern fn with parameter type &str inside struct impl
```
struct Test;

impl Test {
    pub extern fn test(val: &str) {

    }
}
```

When you attempt to compile you get:

```
thread 'rustc' panicked at 'assertion failed: index < LLVMCountParams(llfn)', ../src/librustc_llvm/lib.rs:2281

stack backtrace:
   1:     0x7f594732b6e9 - sys::backtrace::tracing::imp::write::hc20cecbe7cbc162bPnt
   2:     0x7f5947328c36 - panicking::on_panic::h838652421a384701enx
   3:     0x7f59472f3f9e - sys_common::unwind::begin_unwind_inner::h1941327c7a60c738ffs
   4:     0x7f5942add8bf - sys_common::unwind::begin_unwind::h10325064115155345230
   5:     0x7f5942ade6c8 - get_param::h41f15541bf012b4aDUc
   6:     0x7f594682b985 - trans::base::trans_closure::h9db23c69943cc6edvQi
   7:     0x7f594682ea4f - trans::base::trans_fn::he234bd1782c765fai0i
   8:     0x7f59468330ab - trans::base::trans_item::hdd4c4224f51d93be9qj
   9:     0x7f594683f989 - trans::base::trans_crate::hbcfdc768138ad4feRck
  10:     0x7f59478574dc - driver::phase_4_translate_to_llvm::h281d81b2d864b5a0lPa
  11:     0x7f5947851ba3 - driver::phase_3_run_analysis_passes::closure.21540
  12:     0x7f594782f27c - middle::ty::context::ctxt<'tcx>::create_and_enter::h14146594457946518047
  13:     0x7f594782aa31 - driver::phase_3_run_analysis_passes::h3931958423828830349
  14:     0x7f594780aded - driver::compile_input::h4f0a6e7bed616ea50ba
  15:     0x7f5947970d0b - run_compiler::ha3f4465c73f94406qqc
  16:     0x7f594796e576 - boxed::F.FnBox<A>::call_box::h9054381916092353385
  17:     0x7f594796de84 - sys_common::unwind::try::try_fn::h18243607356614407688
  18:     0x7f5947328538 - __rust_try
  19:     0x7f594731ccd2 - sys_common::unwind::try::inner_try::h074d3cf1bfeda6e7Dbs
  20:     0x7f594796e01e - boxed::F.FnBox<A>::call_box::h2812587830519910695
  21:     0x7f5947330a03 - sys::thread::Thread::new::thread_start::h745044ae17db5a99dGw
  22:     0x7f59412c64a3 - start_thread
  23:     0x7f5946fb813c - clone
  24:                0x0 - <unknown>
```

Also tested with the following:

```
use std::path::Path;

struct Test;

impl Test {
    pub extern fn test(val: &Path) {

    }
}
```

You get:

```
thread 'rustc' panicked at 'assertion failed: index < LLVMCountParams(llfn)', ../src/librustc_llvm/lib.rs:2281

stack backtrace:
   1:     0x7fab8a7b06e9 - sys::backtrace::tracing::imp::write::hc20cecbe7cbc162bPnt
   2:     0x7fab8a7adc36 - panicking::on_panic::h838652421a384701enx
   3:     0x7fab8a778f9e - sys_common::unwind::begin_unwind_inner::h1941327c7a60c738ffs
   4:     0x7fab85f628bf - sys_common::unwind::begin_unwind::h10325064115155345230
   5:     0x7fab85f636c8 - get_param::h41f15541bf012b4aDUc
   6:     0x7fab89cb0985 - trans::base::trans_closure::h9db23c69943cc6edvQi
   7:     0x7fab89cb3a4f - trans::base::trans_fn::he234bd1782c765fai0i
   8:     0x7fab89cb80ab - trans::base::trans_item::hdd4c4224f51d93be9qj
   9:     0x7fab89cc4989 - trans::base::trans_crate::hbcfdc768138ad4feRck
  10:     0x7fab8acdc4dc - driver::phase_4_translate_to_llvm::h281d81b2d864b5a0lPa
  11:     0x7fab8acd6ba3 - driver::phase_3_run_analysis_passes::closure.21540
  12:     0x7fab8acb427c - middle::ty::context::ctxt<'tcx>::create_and_enter::h14146594457946518047
  13:     0x7fab8acafa31 - driver::phase_3_run_analysis_passes::h3931958423828830349
  14:     0x7fab8ac8fded - driver::compile_input::h4f0a6e7bed616ea50ba
  15:     0x7fab8adf5d0b - run_compiler::ha3f4465c73f94406qqc
  16:     0x7fab8adf3576 - boxed::F.FnBox<A>::call_box::h9054381916092353385
  17:     0x7fab8adf2e84 - sys_common::unwind::try::try_fn::h18243607356614407688
  18:     0x7fab8a7ad538 - __rust_try
  19:     0x7fab8a7a1cd2 - sys_common::unwind::try::inner_try::h074d3cf1bfeda6e7Dbs
  20:     0x7fab8adf301e - boxed::F.FnBox<A>::call_box::h2812587830519910695
  21:     0x7fab8a7b5a03 - sys::thread::Thread::new::thread_start::h745044ae17db5a99dGw
  22:     0x7fab8474b4a3 - start_thread
  23:     0x7fab8a43d13c - clone
  24:                0x0 - <unknown>
```

However, the following works:

```
struct Test;

impl Test {
    pub extern fn test(val: &u8) {

    }
}
```

Rust version:

```
rustc 1.4.0-beta.1 (d2e13e822 2015-09-15)
```

Also tested on 1.3.0 stable. Haven't tested on nightly.

### LINKED ISSUE #34751: ICE: 'rustc' panicked at 'assertion failed: !substs.has_regions_escaping_depth(0)'
Code:

```
use std::marker::PhantomData;

fn f<'a>(PhantomData::<&'a u8>: PhantomData<&'a u8>) {}

fn main() {}
```

ICEs on stable/beta/nightly.

Backtrace:

```
#0  0x000000006e55e727 in rust_panic ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\std-f53fb285.dll
#1  0x000000006e544e2c in std::panicking::rust_panic_with_hook::hff406a2d53fd3a8a ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\std-f53fb285.dll
#2  0x0000000067a81464 in std::panicking::begin_panic::h7a5a31993347e9ec ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#3  0x0000000067b02537 in rustc_typeck::check::FnCtxt::instantiate_value_path::hd4af43121728875c ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#4  0x0000000067ab2dba in rustc_typeck::check::_match::_$LT$impl$u20$check..FnCtxt$LT$$u27$a$C$$u20$$u27$gcx$C$$u20$$u27$tcx$GT$$GT$::check_pat::h5874e11e18e036cd ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#5  0x0000000067aabf61 in rustc_typeck::check::check_fn::hedf1b94becbdc550 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#6  0x0000000067aa1d89 in rustc_typeck::check::check_bare_fn::haac232c6a78527e7 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#7  0x0000000067a9d25f in rustc_typeck::check::check_item_body::hca9847fe73b73821 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#8  0x0000000067a94672 in rustc_typeck::check::check_item_bodies::h0129b02cf3aee3c1 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#9  0x0000000067a892e2 in rustc_typeck::check_crate::hf9d573c002b16fbd ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_typeck-f53fb285.dll
#10 0x000000006ac97e25 in rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::hab5b4af6b2e2861f ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_driver-f53fb285.dll
#11 0x000000006ac95d56 in rustc::ty::context::TyCtxt::create_and_enter::hc30a91872bbf912b ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_driver-f53fb285.dll
#12 0x000000006ac5a782 in rustc_driver::driver::compile_input::h2d1b58b831f06a86 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_driver-f53fb285.dll
#13 0x000000006ac4697d in rustc_driver::run_compiler::h833483649bdaa9c3 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_driver-f53fb285.dll
#14 0x000000006ac438ba in std::panicking::try::call::hf1c34f6ae15d2786 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_driver-f53fb285.dll
#15 0x000000006e58f6f9 in __rust_maybe_catch_panic ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\std-f53fb285.dll
#16 0x000000006ac443b4 in _$LT$F$u20$as$u20$std..boxed..FnBox$LT$A$GT$$GT$::call_box::h7d06daf297860d37 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\rustc_driver-f53fb285.dll
#17 0x000000006e57d32a in std::sys::thread::Thread::new::thread_start::h150ac04d84605902 ()
   from C:\msys64\home\rust\x86_64-pc-windows-gnu\stage1\bin\std-f53fb285.dll
#18 0x00000000770659bd in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
#19 0x000000007729a2e1 in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
#20 0x0000000000000000 in ?? ()
```

### LINKED ISSUE #35988: ICE: failed to get layout for `E`: the type `E` has an unknown layout
This is a regression: reproduces on beta and nightly, doesn't reproduce on stable.

``` rust
enum E {
    V([Box<E>])
}

fn main() {}
```

```
error: internal compiler error: ../src/librustc_lint/types.rs:698: failed to get layout for `E`: the type `E` has an unknown layout

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:634
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by topecongiro**
This PR adds missing tests for issue #35988, #19712, ~~#18627~~, #24947, #28600 and #34751.

Fixes #35988 
Fixes #19712 
Fixes #24947 
Fixes #28600 
Fixes #34751

### CODE REVIEW

**Comment by petrochenkov** [comment]
@topecongiro 
Could you remove the test for https://github.com/rust-lang/rust/issues/18627? It's not actually fixed.

**Comment by topecongiro** [comment]
Removed the test for #18627 & rebased.

**Comment by brson** [comment]
Awesome PR @topecongiro 👍

**Pull request merged**
