### PR TITLE
Add a warning to CStr::as_ptr

### PR DESCRIPTION
**Pull request by Gankra**
@bluss was saying that this is a really common problem for people to run into on IRC. Hopefully this helps?

### CODE REVIEW

**Comment by retep998** [comment]
I agree that this is a common problem and some sort of documentation needs to be provided warning people about it.

**Comment by Gankro** [comment]
bluss noted on IRC that providing more positive/affirmitive/specific advice might be better here. As in, "Make sure the returned pointer is only used while the original CString is live". Inclined to agree, but interested in discussing the best way to handle this sort of thing. 

See https://github.com/rust-lang/rust/issues/27769 for some related discussion.

**Comment by alexcrichton** [comment]
Yeah I would also expect the docs to nudge you in the right direction by talking about having the original `CString` outlive the pointer itself

**Comment by steveklabnik** [comment]
Yeah, there should be something here. We can nitpick it a bunch, or we can just merge this, and as I go through the API docs, I can clean it up later, either is fine for now imho.

**Pull request closed without merging**
