### PR TITLE
test: Verify all sysroot crates are unstable

### PR DESCRIPTION
**Pull request by alexcrichton**
As we continue to add more crates to the compiler and use them to implement
various features we want to be sure we're not accidentally expanding the API
surface area of the compiler! To that end this commit adds a new `run-make` test
which will attempt to `extern crate foo` all crates in the sysroot, verifying
that they're all unstable.

This commit discovered that the `std_shim` and `test_shim` crates were
accidentally stable and fixes the situation by deleting those shims. The shims
are no longer necessary due to changes in Cargo that have happened since they
were originally incepted.

### CODE REVIEW

**Comment by alexcrichton** [comment]
My current plan for bringing external crates to the compiler is that we'll pass `--cfg rustbuild` to all compilations initiated by rustbuild itself, and then crates will need a preamble like https://github.com/alexcrichton/log/commit/75c6a0e1582a5e1aaa3e6a1387081c44937d9e41 if we pull them in. I'm  open to other opinions/options though!

**Comment by brson** [comment]
relnotes because the backcompat thing, though probably nobody ever noticed.

@bors r+

**Comment by brson** [comment]
cc @japaric dropping the shims may affect xargo

**Comment by alexcrichton** [comment]
Hm so actually I'm not sure that the strategy of `--cfg rustbuild` will work. I'll back out that piece but otherwise this PR is still good, so let's still merge.

**Comment by japaric** [comment]
Thanks for the ping, @brson. Today's Xargo doesn't depend on the shim crates and it's up to the end user to adapt to changes in the std facade (there's a Xargo.toml where you declare what crates from the std facade you want to build)

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Comment by alexcrichton** [comment]
@bors: retry

* spurious osx timeout?

**Pull request merged**
