### PR TITLE
impl From<Cow> for Box, Rc, and Arc

### PR DESCRIPTION
**Pull request by cuviper**
These forward `Borrowed`/`Owned` values to existing `From` impls.

- `Box<T>` is a fundamental type, so it would be a breaking change to add a blanket impl. Therefore, `From<Cow>` is only implemented for `[T]`, `str`, `CStr`, `OsStr`, and `Path`.
- For `Rc<T>` and `Arc<T>`, `From<Cow>` is implemented for everything that implements `From` the borrowed and owned types separately.

### CODE REVIEW

**Review by pickfire — APPROVED** [review]
Looks good to me.

**Comment by pickfire** [comment]
I will probably create another pull request for `Path`.

**Comment by cuviper** [comment]
@pickfire What do you mean? I did implement for `Box<Path>` here.

**Comment by pickfire** [comment]
`impl AsRef<Path> for Cow<'_, str>` is that possible?

**Comment by cuviper** [comment]
> `impl AsRef<Path> for Cow<'_, str>` is that possible?

Oh, sure, that seems fine. It's tangential to this PR though.

Let's try another reviewer here...

r? @dtolnay

**Review by dtolnay — APPROVED** [review]
I think I am on board with all of these. Thanks @cuviper.

**Comment by dtolnay** [comment]
@rfcbot fcp merge

```rust
impl From<Cow<str>> for Box<str> {...}
impl From<Cow<CStr>> for Box<CStr> {...}
impl From<Cow<OsStr>> for Box<OsStr> {...}
impl From<Cow<Path>> for Box<Path> {...}

impl<T> From<Cow<[T]>> for Box<[T]>
where
    T: Copy,
{...}

impl<'a, B> From<Cow<'a, B>> for Rc<B>
where
    B: ToOwned + ?Sized,
    Rc<B>: From<&'a B> + From<B::Owned>,
{...}

impl<'a, B> From<Cow<'a, B>> for Arc<B>
where
    B: ToOwned + ?Sized,
    Arc<B>: From<&'a B> + From<B::Owned>,
{...}
```

All of the impls follow the same pattern:

```rust
fn from(cow: Cow<...>) -> Self {
    match cow {
        Cow::Borrowed(v) => Self::from(v),
        Cow::Owned(v) => Self::from(v),
    }
}
```

**Comment by jplatte** [comment]
This should get a relnotes tag and milestone of 1.45, no?

**Comment by cuviper** [comment]
@jplatte as a stable library addition, yes, I suppose so.

**Pull request merged**
