### PR TITLE
travis: Split the linux-tested-targets builder

### LINKED ISSUE #40359: Spurious "no space left on device" exceptions
Causing our builds to fail.

I have no idea why ;_;

### PR DESCRIPTION
**Pull request by alexcrichton**
Travis only gives us 30GB disk space and we don't currently have an option to
increase that. Each musl target generates "hello world" binaries of about 3.5MB
in size, and we're testing two targets in the same image. We have around 3k
run-pass tests and 2 musl targets which works out to around 20GB. That's
dangerously close to the limit and is causing PRs to bounce.

This PR splits up the builder in two, one for x86_64 musl and the other for
i686. Hopefully that'll keep us under the disk limit.

Closes #40359

### CODE REVIEW

**Comment by arielb1** [comment]
Can't we change compiletest to remove binaries after it creates them?

**Comment by alexcrichton** [comment]
Heh in theory yes! We can do w/e we like.

I don't think that's a feature we want to add though because I've at least often found it useful to inspect binaries after-the-fact. We've got extra capacity and in general this was just easier to implement.

**Pull request merged**
