### PR TITLE
"Incredibly easy" => "easy"

### PR DESCRIPTION
**Pull request by kud1ing**
Given all those scaffolding tools for other programming languages, i don't see why we should tell programmers this is "incredible".

### CODE REVIEW

**Comment by steveklabnik** [comment]
Compared to the systems language space we're in, yes, it is incredible ;)

Thank you for the suggestion, but I think we should certainly play up our strengths in one of our primary marketing materials.

**Comment by kud1ing** [comment]
People are your used to scaffolding tools for at least 10 years. Yeoman supports multiple backends.

Stating that Cargo creating a Rust project is "Incredible" in the sense of "you won't believe it" or "you've never seen anything like it" will do Rust no good.

**Comment by Gankro** [comment]
Arguing over the dictionary definition of incredible seems like needless pedantry.

And for the record I *am* frequently incredibly surprised at how easy it is to set up a Rust project, coming from the nonsense that is Make and Maven.

**Comment by kud1ing** [comment]
@Gankro: Actually this is not about objectivity but subjectivity.

I care deeply about Rust. My code contributions in Rust 0.1 are pretty neglectable. My resources just don't allow much more than to evangelize, test and point to things that could be improved.
As a Rust enthusiast who has used code scaffolding tools for different languages for a couple of years already, reading that Cargo makes starting Rust development "incredibly easy" i get very uneasy. This gives me the subjective feeling of cheap marketing plastered over a common thing.
But also English is not my first language.

I understand you don't think anyone else will be offended, so i am fine. It's subjective.

**Pull request closed without merging**
