### PR TITLE
avoid clone path prefix when lowering to hir

### PR DESCRIPTION
**Pull request by SparrowLii**
Found this while trying to parallelize `lower_to_hir`.

When lowering to hir, `Nested` paths in `ast` will be split and the prefix segments will be cloned. This could be omited, since the only consequence is that the prefix segments in `Path`s in hir will have the same `HirId`s, and it seems harmless.

This simplifies the process of lowering to hir and avoids re-modification of `ResolverAstLowering`. 

r? @Aaron1011 
cc #99292

### CODE REVIEW

**Comment by Aaron1011** [comment]
This looks good to me, but I'd like someone else to confirm that it's fine to have different segments with the same HirIds.

**Comment by SparrowLii** [comment]
Thanks! @petrochenkov Could you help to have a look?

**Comment by SparrowLii** [comment]
@Aaron1011 Can you help r=cjgillot? I'm not reviewer :)

**Comment by cjgillot** [comment]
Thanks!
@bors r+

**Pull request merged**
