### PR TITLE
Remove unused data structures

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Cleanup; as far as I can tell the compiler no longer uses these.

### CODE REVIEW

**Comment by shepmaster** [comment]
image

😻

**Comment by shepmaster** [comment]
Ping from triage, @michaelwoerister !

**Comment by BatmanAoD** [comment]
Ping from triage, @michaelwoerister (also pinged on IRC). @rust-lang/compiler this PR is now 10 days old; if mw does not respond, can a new reviewer be selected?

**Comment by michaelwoerister** [comment]
Thanks for taking over the review, @nikomatsakis. Back from PTO now.

**Pull request merged**
