### PR TITLE
Stabilize arbitrary_enum_discriminant, take 2

### PR DESCRIPTION
**Pull request by fee1-dead**
Documentation has been updated in https://github.com/rust-lang/reference/pull/1055. cc #86860 for previous stabilization report.

Not yet marks https://github.com/rust-lang/rust/issues/60553 as done: need documentation in the rust reference.

### CODE REVIEW

**Comment by fee1-dead** [comment]
r? rust-lang/lang

**Comment by est31** [comment]
:wave: Hello, I'm writing this comment in this **stabilization PR** to notify you, the authors of this PR, that https://github.com/rust-lang/rust/pull/100591 has been merged, which implemented a change in how features are stabilized.

Your PR has been filed before the change, so will likely require modifications in order to comply with the new rules. I recommend you to:

1. rebase the PR onto latest master, so that uses of the placeholder are possible.
2. replace the version numbers in the PR with the placeholder `CURRENT_RUSTC_VERSION`. For language changes, this means the version numbers in `accepted.rs` (example: 4caedbae869855a19ca49455e2cd338ae3b8c1ef). For library changes, this means the `since` fields (example e576a9b554f24a26c36c04b41c901636d190605b).

That's it! The `CURRENT_RUSTC_VERSION` placeholder will, as part of the release process, be replaced with the version number that the PR merged for. It can be used anywhere in `rust-lang/rust`, not just accepted.rs and the since fields.

If you have any questions, feel free to drop by the [zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/libs.20stabilization.20placeholder), or ping me directly in this PR's thread. Thanks! :wave:

**Comment by fee1-dead** [comment]
r? lang

**Comment by ARitz-Cracker** [comment]
Hey, is there anything specific other than a rebase required for getting this merged? I've got a couple things that would greatly benefit from this!

**Comment by joshtriplett** [comment]
This already went through an FCP. I think it just needs a rebase. LGTM, r=me when rebased.

**Comment by ARitz-Cracker** [comment]
Looks like the rebase happened, lookin' forward to this! 🥳

**Comment by pietroalbini** [comment]
@bors r-

Queue got messed up after a synchronize.

**Comment by fee1-dead** [comment]
Last CI error was spurious per https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/rustdoc-gui.20test.20failure/near/305520742.

@bors r=joshtriplett

**Pull request merged**
