### PR TITLE
Introduce HashStable trait and base ICH implementations on it.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR introduces the `HashStable` trait which marks that a type can be hashed in a way that is stable across multiple compilation sessions. The PR also moves HIR incr. comp. hashing over to implementations of this trait instead of doing this via a HIR visitor. It also provides many `HashStable` implementations that are not used yet (e.g. for MIR types) but soon will be used when we directly hash crate metadata for incr. comp.

I've only done superficial performance measurements but it looks like the new implementation is a bit faster than the current one (due, I suppose, to some bugs I fixed and some unnecessary inefficiencies I removed). Here is the time in seconds for the `compute_incremental_hashes_map` pass for various crates:

|                 |  OLD  |  NEW  |
|:---------------:|:-----:|:-----:|
| libcore         | 0.507 | 0.409 |
| libsyntax       | 0.320 | 0.260 |
| librustc        | 0.730 | 0.611 |
| librustc_driver | 0.024 | 0.015 | 

Some notes regarding the implementation:
* Most `HashStable` implementations are provided via the `impl_hash_stable_for!` macro (as suggested by @nikomatsakis). This works out quite well. A custom_derive would have been better but Macros 1.1 are not available in the compiler. 
* The trait implementation take care to exhaustively destructure everything they hash so that fields added in the future don't fall through the cracks. This is a bit verbose but I think it's well worth the trouble since we've had quite a few issues with missing fields or visitor callbacks in this area in the past. Most of it is behind the macro anyway.

cc @rust-lang/compiler 
r? @nikomatsakis

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Those travis errors seem to indicate that something went wrong when rebasing ontop of the `catch` changes. Looking into it...

**Comment by michaelwoerister** [comment]
So, I can reliably reproduce these errors but I can't see how the changes in this PR would have an effect like that `:/`

**Comment by michaelwoerister** [comment]
OK, the problem was that those tests where exercising code paths that would try to hash the DefPath of NodeIds that don't have a corresponding DefId.

**Comment by michaelwoerister** [comment]
This latest error is legitimate (the SVH is more sensitive than it needs to be) and I figured out that impl specialization offers a way of solving this in a nice and general way, that also allows for reverting the splitting-out of dep_graph_assert attrs. Please hold off on reviewing until I've done that.

**Comment by michaelwoerister** [comment]
Alright, this passes `make check` for me now and the implementation is simpler too. Hurray specialization!

**Comment by alexcrichton** [comment]
@bors: retry

* centos network issues https://github.com/rust-lang/rust/issues/40474

**Comment by frewsxcv** [comment]
Ran into an issue with this PR in the rollup

https://travis-ci.org/rust-lang/rust/jobs/219131927

@bors r-

**Comment by nikomatsakis** [comment]
@michaelwoerister 

Looks like a minor merge thing-y:

```
[00:06:09] error[E0026]: struct `hir::Block` does not have a field named `break_to_expr_id`
[00:06:09]    --> /checkout/src/librustc/ich/impls_hir.rs:347:13
[00:06:09]     |
[00:06:09] 347 |             break_to_expr_id,
[00:06:09]     |             ^^^^^^^^^^^^^^^^ struct `hir::Block` does not have field `break_to_expr_id`
[00:06:09] 
[00:06:09] error[E0027]: pattern does not mention field `targeted_by_break`
[00:06:09]    --> /checkout/src/librustc/ich/impls_hir.rs:341:13
[00:06:09]     |
[00:06:09] 341 |           let hir::Block {
[00:06:09]     |  _____________^ starting here...
[00:06:09] 342 | |             ref stmts,
[00:06:09] 343 | |             ref expr,
[00:06:09] 344 | |             id,
[00:06:09] 345 | |             rules,
[00:06:09] 346 | |             span,
[00:06:09] 347 | |             break_to_expr_id,
[00:06:09] 348 | |         } = *self;
[00:06:09]     | |_________^ ...ending here: missing field `targeted_by_break`
[00:06:09] 
[00:06:15] error: aborting due to 2 previous errors
```

**Comment by nikomatsakis** [comment]
In particular I renamed `break_to_expr_id` to `targeted_by_break`

**Pull request merged**
