### PR TITLE
std: Update compiler-rt for more ABI fixes

### LINKED ISSUE #37630: [beta] librand unreachable pattern on armv7-unknown-linux-gnueabihf
I just tried builds of 1.13.0-beta.3 on [Fedora 24](http://koji.fedoraproject.org/koji/taskinfo?taskID=16332440) and [Rawhide](http://koji.fedoraproject.org/koji/taskinfo?taskID=16332435) (with LLVM 3.8 and 3.9 respectively), and both builds failed *only* on armv7hl, in the exact same place:

```
CFG_LLVM_LINKAGE_FILE=/builddir/build/BUILD/rustc-beta/armv7-unknown-linux-gnueabihf/rt/llvmdeps.rs LD_LIBRARY_PATH=/builddir/build/BUILD/rustc-beta/armv7-unknown-linux-gnueabihf/stage2/lib:/usr/lib:$LD_LIBRARY_PATH   armv7-unknown-linux-gnueabihf/stage2/bin/rustc --cfg stage2 -Clink-args=-Wl,-z,relro,-z,now -O --cfg rtopt -g  --target=armv7-unknown-linux-gnueabihf  -C prefer-dynamic -L "armv7-unknown-linux-gnueabihf/rt" -L native="/usr/lib"     --out-dir armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib -C extra-filename=-f02899e6 -C metadata=f02899e6 src/librand/lib.rs
error[E0001]: unreachable pattern
  --> src/librand/distributions/gamma.rs:93:13
   |
93 |             0.0...1.0 => Small(GammaSmallShape::new_raw(shape, scale)),
   |             ^^^^^^^^^ this is an unreachable pattern
```

That full function is:

```rust
impl Gamma {
    /// Construct an object representing the `Gamma(shape, scale)`
    /// distribution.
    ///
    /// Panics if `shape <= 0` or `scale <= 0`.
    pub fn new(shape: f64, scale: f64) -> Gamma {
        assert!(shape > 0.0, "Gamma::new called with shape <= 0");
        assert!(scale > 0.0, "Gamma::new called with scale <= 0");

        let repr = match shape {
            1.0 => One(Exp::new(1.0 / scale)),
            0.0...1.0 => Small(GammaSmallShape::new_raw(shape, scale)),
            _ => Large(GammaLargeShape::new_raw(shape, scale)),
        };
        Gamma { repr: repr }
    }
}
```

This particular code hasn't changed in over a year, and my i686, x86_64, and aarch64 builds were fine with it.  Only armv7hl has the error, and note even then it wasn't until `--cfg stage2`.

I had no problem with armv7hl on prior releases, so this appears to be a beta regression.  I do have one patch applied from #36933 to disable NEON, but I also had that on 1.12.1 and it went fine.  I'm baffled what else could be specific to armv7hl to cause this...

### PR DESCRIPTION
**Pull request by alexcrichton**
This update of compiler-rt includes rust-lang/compiler-rt#26 which provides a
targeted fix to the powisf2 intrinsics to keep #37559 fixed but also address
the new issue of #37630. I've also [written up my thoughts][1] on why it appears
that this is the correct fix for now (hoepfully at least).

Closes #37630

[1]: https://github.com/rust-lang/compiler-rt/pull/26#issuecomment-259751998

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nominating for beta as this is a [stable-to-stable regression](https://github.com/rust-lang/rust/issues/37630)

**Comment by rillian** [comment]
@alexcrichton Has this landed on beta yet? I don't see it in the commit log.

**Comment by alexcrichton** [comment]
@rillian AFAIK no

**Comment by rillian** [comment]
@alexcrichton Ok, thanks for checking. Does the beta-accepted tag mean bors will land it, or should I submit a PR? We want this so we can update the gecko builders.

**Comment by alexcrichton** [comment]
Ah this doesn't happen automatically, we do so periodically from time to time. I've done so here: https://github.com/rust-lang/rust/issues/37815

**Comment by rillian** [comment]
Thanks Alex!

**Pull request merged**
