### PR TITLE
Refactor the parser to consume token trees

### PR DESCRIPTION
**Pull request by jseyfried**
This is groundwork for efficiently parsing attribute proc macro invocations, bang macro invocations, and `TokenStream`-based attributes and fragment matchers.

This improves parsing performance by 8-15% and expansion performance by 0-5% on a sampling of the compiler's crates.

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
This looks great. I'm a little concerned about the commit removing the lookahead buffer - is that because we never use lookahead now?

**Comment by nrc** [comment]
Oh, right, you can look ahead in the Tok stream without it, I guess?

**Comment by jseyfried** [comment]
Yeah, we look ahead in `parser.tts` directly.

**Pull request merged**
