### PR TITLE
Add regression tests for issue 80309

### LINKED ISSUE #80309: Miscompilation when using wrapping_sub/wrapping_add on pointer.
[Relevant comment on IRLO](https://internals.rust-lang.org/t/pointers-are-complicated-ii-or-we-need-better-language-specs/13562/25?u=steffahn). The following code leads to `illegal instruction` in release mode. (It works fine, printing `42` in debug mode.)

```rust
pub unsafe fn foo(x: *const i8) -> i8 {
    *x.wrapping_sub(x as _).wrapping_add(x as _)
}

fn main() {
    let x = 42;
    println!("{}", unsafe {foo(&x)});
}
```
Apparently, leaving the object `x` with a `wrapping_sup`, then going back into the object with `wrapping_add` and dereferencing the resulting pointer is supposed to be safe (although there is still an open issue (#80306) about properly documenting that this is safe).

As discussed in the linked IRLO thread, what’s probably happening here is that LLVM realizes that the first `x.wrapping_sub(x as _)` evaluates to the null pointer, and then considers the code equivalent to something like `*std::ptr::null().wrapping_add(x as _)` which is then detected as UB (dereferencing some integer offset of the null pointer), hence the illegal instruction.

([Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=3fcc0c74aa07be2f1b3420dd63b28f77))

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished release [optimized] target(s) in 1.03s
     Running `target/release/playground`
timeout: the monitored command dumped core
/playground/tools/entrypoint.sh: line 11:     7 Illegal instruction     timeout --signal=KILL ${timeout} "$@"

```

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Closes #80309 😝 

I'm not sure where to put the tests, is `ui/issues` the right place for this kind of tests?

### CODE REVIEW

**Comment by oli-obk** [comment]
Tidy is unhappy, maybe put it in a new folder like `src/test/ui/ptr_ops`

r? @oli-obk

**Comment by oli-obk** [comment]
Uh oh. Looks like this is still happening... maybe CI has a different llvm? brb reading some diffs

**Comment by oli-obk** [comment]
I guess CI being `x86_64-gnu-llvm-12` should've been a hint. 

@rust-lang/wg-llvm should we wait until CI is bumped or can we ignore the tests on an old llvm somehow?

**Comment by nagisa** [comment]
`// min-llvm-version`

**Pull request merged**
