### PR TITLE
Update build instructions

### PR DESCRIPTION
**Pull request by akoserwal**
It get stuck at the cloning step. 
`./x.py build `   
Updating only changed submodules
Updating submodule src/llvm
Submodule 'src/llvm' (https://github.com/rust-lang/llvm.git) registered for path 'src/llvm'
Cloning into '/home/username/rust/src/llvm'...

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

This seems like a decent change for users, and doesn't make much difference I believe since bootstrap will take care of checking out anything we missed.

**Comment by glandium** [comment]
Why change the documentation instead of changing the bootstrap script? Presumably, the only problem is that `git submodule update`, which bootstrap runs, doesn't report anything unless it's given `--progress`, which the documentation change suggests users do manually, but it seems like bootstrap should just do it.
FWIW, `--progress` is only a valid option of `git submodule` in git >= 2.11.

**Comment by kennytm** [comment]
@bors retry #40474 😒 

```
curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com
```

**Comment by Mark-Simulacrum** [comment]
> Why change the documentation instead of changing the bootstrap script?

My primary reasoning for accepting this is because I want to avoid having to revert it when people complain that bootstrap is now giving too much output. But, realistically, I don't care too much, so if we want to move this into bootstrap either in this PR or later down the road that's fine by me.

**Comment by akoserwal** [comment]
I can work to add this to bootstrap script? and I can check for condition `git >= 2.11.` ?

**Comment by Mark-Simulacrum** [comment]
I think this is fine for now, if you can rebase and force push I can re r+ and then we can land this

**Comment by akoserwal** [comment]
@Mark-Simulacrum : done

**Pull request merged**
