### PR TITLE
Ignore comments in tidy-filelength

### PR DESCRIPTION
**Pull request by ibraheemdev**
Ref https://github.com/rust-lang/rust/issues/60302#issuecomment-652402127

### CODE REVIEW

**Comment by petrochenkov** [comment]
I disagree with this change, keeping comment lines short enough have the same value as keeping anything other text or code short.
We already have some logic in tidy applying exceptions to "special" comments like `//~ ERROR text` or comments containing URLs.

**Comment by ibraheemdev** [comment]
> I think in these cases, it's not so important to split up the files, because the length doesn't pose an issue for comprehension. Anyone editing the file is going to be interested in one or two particular functions, which are well-isolated within the file, and wouldn't benefit from being in their own file. In some sense, files like these are "false positives", though I don't think we could automatically exclude them. The lint is really more for files with large functions, and interdependency that we want to make easier to navigate.

It's not about being short, it's about readability. Comments don't add complexity to the file.

**Comment by Mark-Simulacrum** [comment]
Hm, @petrochenkov - I don't think this PR changes behavior for *line* length checking. Line lengths are already ignored for most of the codebase: we avoid nagging people in files under rustfmt control. Whether that was the right call, I'm not sure, but this PR seems unrelated to that topic.

This PR seems to solely intend to avoid nagging on *long* files if the length is primarily due to comment lines. I think that's an interesting proposal, but as I personally don't really typically find file length an impediment or good proxy, I'm not sure I'm the right reviewer.

Regardless, for issues like this I think it's likely best to circulate them more widely; I would suggest a T-compiler MCP.

Cc @rust-lang/libs-contributors as well, since many of our longer files are such due to extensive documentation in std, core, etc.

**Comment by petrochenkov** [comment]
Ah, ok, sorry for misinterpreting the changes.
I'm ok with making files longer.

**Comment by Mark-Simulacrum** [comment]
Discussed during T-compiler meeting; no objections to just moving ahead were raised. Seems trivial to re-add if opposition is raised.

An additional point of discussion was the check might be dropped entirely, but that can also be proposed in the future with little trouble. It's possible being happier to ignore the lint is preferable, though, in cases where it is causing pain for no good reason.

@bors r+

**Comment by NoobProgrammer31** [comment]
can i start working on mod.rs first in first file ( i am new to it )

**Pull request merged**
