### PR TITLE
Honour the -Z treat-err-as-bug again

### PR DESCRIPTION
**Pull request by nagisa**
r? @nikomatsakis or @jonathandturner

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hmm. I had a slightly different fix for this bug which I think I prefer here: https://github.com/rust-lang/rust/pull/33137/commits/fee2dba48938f3d9c6f9ddc60e84acd8251bd06a

My fix was local to the `DiagnosticBuilder`, in particular, rather than making `EmitterWriter` care about that case.

**Comment by nikomatsakis** [comment]
(I do hope to land that PR soon.)

**Comment by nagisa** [comment]
What I prefer about my approach that it allows the system emit the associated helps and whatnot which I think your patch does not allow.

**Comment by nikomatsakis** [comment]
@nagisa 

> What I prefer about my approach that it allows the system emit the associated helps and whatnot which I think your patch does not allow.

I think my patch does allow that, but I agree that is preferable. I'll double check.

**Comment by nikomatsakis** [comment]
OK, my alternative patch just landed, and I think it does preserve the behavior that you see all notes and things. Closing this, therefore.

**Pull request closed without merging**
