### PR TITLE
Update LLVM submodule

### LINKED ISSUE #131164: non-pub function no longer compiled in debug profile, causing link errors on thumbv7em-none-eabihf with defmt
### Code

I tried this code:

```bash
$ git clone https://github.com/ferrous-systems/rust-exercises.git
$ cd rust-exercises
$ git checkout v1.17.0
$ cd nrf52_code/radio_app
$ rustup target add thumbv7em-none-eabihf --toolchain=nightly
$ cargo install flip-link (or change `.cargo/config.toml` to not use flip-link - either is fine)
$ cargo +nightly build
```

I expected to see this happen:

The binaries build like, they do on stable.

Instead, this happened:

```text
  = note: rust-lld: error: /Users/jonathan/Documents/clients/training/open-rust-embedded-2024-10-02/rust-exercises-v1.17.0/nrf52-code/radio-app/target/thumbv7em-none-eabihf/debug/build/defmt-36a2ab5d209daca3/out/defmt.x:7: symbol not found: __defmt_default_panic
          rust-lld: error: /Users/jonathan/Documents/clients/training/open-rust-embedded-2024-10-02/rust-exercises-v1.17.0/nrf52-code/radio-app/target/thumbv7em-none-eabihf/debug/build/defmt-36a2ab5d209daca3/out/defmt.x:7: symbol not found: __defmt_default_panic
          rust-lld: error: /Users/jonathan/Documents/clients/training/open-rust-embedded-2024-10-02/rust-exercises-v1.17.0/nrf52-code/radio-app/target/thumbv7em-none-eabihf/debug/build/defmt-36a2ab5d209daca3/out/defmt.x:7: symbol not found: __defmt_default_panic
          rust-lld: error: /Users/jonathan/Documents/clients/training/open-rust-embedded-2024-10-02/rust-exercises-v1.17.0/nrf52-code/radio-app/target/thumbv7em-none-eabihf/debug/build/defmt-36a2ab5d209daca3/out/defmt.x:7: symbol not found: __defmt_default_panic
```

That symbol is defined here: https://github.com/knurling-rs/defmt/blob/b7a89f56059fc66ac3c7cc3445d092829599e699/defmt/src/lib.rs#L365

### Bisect

@Dirbaio said:

searched nightlies: from nightly-2024-07-30 to nightly-2024-10-02
regressed nightly: nightly-2024-08-01
searched commit range: https://github.com/rust-lang/rust/compare/f8060d282d42770fadd73905e3eefb85660d3278...28a58f2fa7f0c46b8fab8237c02471a915924fe5
regressed commit: https://github.com/rust-lang/rust/commit/0b5eb7ba7bd796fb39c8bb6acd9ef6c140f28b65

That's the LLVM 19 upgrade.

### PR DESCRIPTION
**Pull request by dianqk**
Fixes (maybe after beta backport) #131164.

r? nikic

### CODE REVIEW

**Comment by DianQK** [comment]
Backporting will also bring #131293, mostly clang changes. I can create a separate branch for backporting if necessary.

**Comment by DianQK** [comment]
It broke something, I'll check it out tomorrow. 😣

**Comment by onur-ozkan** [comment]
Maybe reason is because `download-rustc="if-unchanged"` is being utilized in non-dist runners. If that's the case (you can set `NO_DOWNLOAD_CI_RUSTC=1` in the failed runner for testing), we should add a logic to skip `download-rustc` on LLVM bumps.

**Comment by DianQK** [comment]
> Maybe reason is because `download-rustc="if-unchanged"` is being utilized in non-dist runners. If that's the case (you can set `NO_DOWNLOAD_CI_RUSTC=1` in the failed runner for testing), we should add a logic to skip `download-rustc` on LLVM bumps.

I'm trying to remove `FORCE_CI_RUSTC` first.

**Comment by onur-ozkan** [comment]
Can you cherry pick commits from https://github.com/rust-lang/rust/pull/131453 and https://github.com/rust-lang/rust/pull/131305 (with reverting the last change)? I want to see if they can fix `x86_64-gnu-llvm-18` and `x86_64-gnu-tools` issues.

**Comment by jieyouxu** [comment]
> `thread 'core::config::tests::download_ci_llvm' panicked at src/core/config/tests.rs:34:5`

Might need to rebase again?

**Comment by DianQK** [comment]
> > `thread 'core::config::tests::download_ci_llvm' panicked at src/core/config/tests.rs:34:5`
> 
> Might need to rebase again?

This is a known error: #131303.

**Comment by onur-ozkan** [comment]
> > > `thread 'core::config::tests::download_ci_llvm' panicked at src/core/config/tests.rs:34:5`
> > 
> > 
> > Might need to rebase again?
> 
> This is a known error: #131303.

https://github.com/rust-lang/rust/pull/131305 will fix that.

**Comment by DianQK** [comment]
In terms of https://github.com/rust-lang/rust/issues/131164#issuecomment-2400724853, https://github.com/rust-lang/rust/issues/131164#issuecomment-2402667673 as well as https://github.com/rust-lang/rust/issues/131164#issuecomment-2404970102, I think it's a broad impact.

**Comment by lqd** [comment]
@DianQK I just noticed that this is an lld regression, right? That is, it only affects nightly by default, and I didn't need to beta-nominate it.

**Comment by DianQK** [comment]
> @DianQK I just noticed that this fixes an lld regression, right? That is, it only affects nightly by default, and I didn't _need_ to beta-nominate it? Though it's surely better that the issue doesn't reach beta/stable for the targets using `rust-lld` by default.

IIUC, something like thumbv7em-none-eabihf would use rust-lld on beta/stable.

**Comment by jieyouxu** [comment]
Not sure why this is failing, that seems strange...

**Comment by onur-ozkan** [comment]
> The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/11285680219/job/31388885471) [(plain)](https://github.com/rust-lang-ci/rust/commit/5431d516592bbece7ed93326c0d6856d92c98ed9/checks/31388885471/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)

I think the problem behind this is because [CI doesn't have upstream master accessible](https://github.com/rust-lang/rust/pull/131358), so we always  current `HEAD` . But still, bootstrap have some mechanism to handle that situation. Maybe we just hit some rare case here and rebase would help?

**Comment by DianQK** [comment]
Rebased.

**Comment by jieyouxu** [comment]
This time it's the config test `core::config::tests::download_ci_llvm ... F`

**Comment by onur-ozkan** [comment]
See https://github.com/rust-lang/rust/pull/131448#issuecomment-2404959666.

@bors r+

**Comment by onur-ozkan** [comment]
There is this logic in mingw-check runner:

https://github.com/rust-lang/rust/blob/0321e73d1cb3f739caa806927344eca6f96257b5/src/ci/docker/host-x86_64/mingw-check/Dockerfile#L57-L60

but I am not sure if it's related since it's reverting the commit.

**Comment by onur-ozkan** [comment]
> There is this logic in mingw-check runner:
> 
> https://github.com/rust-lang/rust/blob/0321e73d1cb3f739caa806927344eca6f96257b5/src/ci/docker/host-x86_64/mingw-check/Dockerfile#L57-L60
> 
> but I am not sure if it's related since it's reverting the commit.

As far as I see this is related as the failure happens before the revert. I will find a solution in couple of hours.

**Comment by DianQK** [comment]
> I will find a solution in couple of hours.

Never mind, I don’t think this is urgent. :3

**Comment by onur-ozkan** [comment]
Once https://github.com/rust-lang/rust/pull/131305 and https://github.com/rust-lang/rust/pull/131531 is merged, hopefully CI will become more stable for LLVM update PRs.

**Comment by lqd** [comment]
> Never mind, I don’t think this is urgent. :3

Beta is branching off today and the stable artifacts will be prepared Monday 😓

**Comment by lqd** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-10-10/near/476140136). A backport PR will be authored by the release team at the end of the current development cycle, if CI ever allows this PR to land.

@rustbot label +beta-accepted

**Comment by tgross35** [comment]
Just to make sure this (hopefully) gets in before the branch, so we don't need to track backports to two different betas

@bors p=1

**Comment by onur-ozkan** [comment]
> The job **`x86_64-gnu-llvm-19`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/11305493455/job/31445068279) [(plain)](https://github.com/rust-lang-ci/rust/commit/4b31ccbaa7bbae53babbe30e6fe89b87650a60cb/checks/31445068279/logs)
> 
> Click to see the possible cause of the failure (guessed by this bot)
> ```
> failures:
> 
> ---- core::config::tests::download_ci_llvm stdout ----
> Detected LLVM as non-available: running in CI and modified LLVM in this change
> thread 'core::config::tests::download_ci_llvm' panicked at src/core/config/tests.rs:24:5:
> assertion failed: parse("").llvm_from_ci
>    0: rust_begin_unwind
>              at /rustc/8c27a2ba6b21f3406a51118643080f0591949827/library/std/src/panicking.rs:662:5
>    1: core::panicking::panic_fmt
>              at /rustc/8c27a2ba6b21f3406a51118643080f0591949827/library/core/src/panicking.rs:74:14
> ```

lol this is getting really annoying

**Comment by onur-ozkan** [comment]
Feel free to apply this patch:

```diff
diff --git a/src/bootstrap/src/core/config/tests.rs b/src/bootstrap/src/core/config/tests.rs
index 4b689aa3ecc..15600f70d6e 100644
--- a/src/bootstrap/src/core/config/tests.rs
+++ b/src/bootstrap/src/core/config/tests.rs
@@ -21,7 +21,6 @@ pub(crate) fn parse(config: &str) -> Config {

 #[test]
 fn download_ci_llvm() {
-    assert!(parse("").llvm_from_ci);
     assert!(parse("llvm.download-ci-llvm = true").llvm_from_ci);
     assert!(!parse("llvm.download-ci-llvm = false").llvm_from_ci);

```

as a first commit (make sure the LLVM submodule update is the last commit) and r=me.

**Comment by onur-ozkan** [comment]
> Feel free to apply this patch:
> 
> ```diff
> diff --git a/src/bootstrap/src/core/config/tests.rs b/src/bootstrap/src/core/config/tests.rs
> index 4b689aa3ecc..15600f70d6e 100644
> --- a/src/bootstrap/src/core/config/tests.rs
> +++ b/src/bootstrap/src/core/config/tests.rs
> @@ -21,7 +21,6 @@ pub(crate) fn parse(config: &str) -> Config {
> 
>  #[test]
>  fn download_ci_llvm() {
> -    assert!(parse("").llvm_from_ci);
>      assert!(parse("llvm.download-ci-llvm = true").llvm_from_ci);
>      assert!(!parse("llvm.download-ci-llvm = false").llvm_from_ci);
> ```
> 
> as a first commit (make sure the LLVM submodule update is the last commit) and r=me.

or even ignore that test with #[ignore] completely. I guess that will be much better until we have a stabilized change tracking logic (something like https://github.com/rust-lang/rust/pull/131358).

**Comment by lqd** [comment]
The good news is that the backport has already landed on the beta branch

**Comment by cuviper** [comment]
Yes, but if #131560 lands before this, marking the version cutoff, then there will be a new beta needing backport .

**Pull request merged**
