### PR TITLE
Implement AsMut for Vec

### LINKED ISSUE #28549: There should be an `impl<T> AsMut<[T]> for Vec<T>`.
In [GJ](https://github.com/dwrensha/gj) I have this trait like this:

```
pub trait AsyncRead: 'static {
    fn try_read<T>(self, buf: T, min_bytes: usize) -> Promise<(Self, T, usize), Error<(Self, T)>> where T: DerefMut<Target=[u8]>, Self: Sized;
}
```

I'd like to switch the bound on `T` to be `T: AsMut<[u8]>`, but then I can no longer use a bare `Vec<u8>` for `T`, because there is currently no `impl<T> AsMut<[T]> for Vec<T>`.

It seems to me that such an impl ought to exist, especially because `impl<T> AsRef<[T]> for Vec<T>` already exists.

### PR DESCRIPTION
**Pull request by bluss**
Implement AsMut for Vec

Fixes #28549

### CODE REVIEW

**Comment by bluss** [comment]
I don't foresee any problems with this trait impl. Vec already implements AsRef, so it should impl AsMut.

Not handling Box since Box is missing both AsRef and AsMut. I thought we had a problem implementing them already, but I can't find any trace of it?

**Comment by alexcrichton** [comment]
We currently don't implement this for `Box<T>` because the meaning of `as_ref` on `Box<Option<T>>` would change (returning `&Option<T>` instead of `Option<&T>`). Which is to say it conflicts with `Option::as_ref` unfortunately.

Some discussion of this is happening on https://github.com/rust-lang/rust/pull/27197 as well.

**Comment by bluss** [comment]
Updated with `AsMut<Vec<T>>`.

**Comment by bluss** [comment]
Thanks!

**Comment by bluss** [comment]
What about implementing `AsRef<[T]> for Box<[T]>` (and `AsMut`)? It's less general than implementing it for all `Box<T>`, but this should be without conflict.

**Comment by alexcrichton** [comment]
Certainly a possibility to consider!

**Pull request merged**
