### PR TITLE
Add --run flag to compiletest

### PR DESCRIPTION
**Pull request by tmandry**
This controls whether run-* tests actually get run.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I guess you're intending to use this via --test-args --run or so? Does that work for you?

If so, r=me, otherwise happy to re-review after the option is pulled through and exposed in rustbuild as a flag as well.

**Comment by tmandry** [comment]
Yep, that's what I was going to do at least for now. I wasn't sure how many others would need it.

@bors r=Mark-Simulacrum

**Comment by tmandry** [comment]
@bors r-

actually I'm seeing some problems with this

**Comment by tmandry** [comment]
Okay, I fixed some things and threaded `--run` through rustbuild. `--run=never` should now work for all test types, and attempts to build rather than ignore the tests that are usually run.

I've confirmed that I can run `./x.py test --run=never` and it succeeded up until I hit #78778, which is pretty late in the build.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Thanks!

**Pull request merged**
