### PR TITLE
[beta] backport various PRs

### PR DESCRIPTION
**Pull request by oli-obk**
original PRs:

* https://github.com/rust-lang/rust/pull/49949 (not yet merged at the time of writing)
* https://github.com/rust-lang/rust/pull/49947 (long running const eval error -> warning)
* https://github.com/rust-lang/rust/pull/49833 (static recursion)
* #49876 (no clippy in stable rls)
* #49904 (Work around LLVM debuginfo problem in librustc_driver. )

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by oli-obk** [comment]
r? @kennytm 

all merged into one now

**Comment by oli-obk** [comment]
cc @rust-lang/compiler a beta backport of the various fixes for miri+incremental ICEs

**Comment by kennytm** [comment]
@bors r-

Err wait, let's ensure that #49949 is successfully merged first.

Also, #49949, #49947 and #49833 are missing the <kbd>beta-accepted</kbd> labels for rubber-stamping the backport.

**Comment by oli-obk** [comment]
we don't have rubber stamps yet...

**Comment by nagisa** [comment]
everything has been stamped.

**Comment by pietroalbini** [comment]
Timed out on Travis ` IMAGE=x86_64-gnu-incremental`.

@bors retry

**Comment by kennytm** [comment]
@bors r+

Rolled up #50046 here.

**Pull request merged**
