### PR TITLE
update Miri

### LINKED ISSUE #84553: `miri` no longer builds after rust-lang/rust#84216
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#84216, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @RalfJung, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/84553
Cc @rust-lang/miri r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r-
Miri is currently broken: https://github.com/rust-lang/rust/issues/84553

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/84545#issuecomment-826328063)

**Pull request merged**
