### PR TITLE
std: Remove rust_builtin C support library

### PR DESCRIPTION
**Pull request by alexcrichton**
All these definitions can now be written in Rust, so do so!

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

I have a feeling this will break android, but I'm curious what CI will say. Also cc @dhuseby and @semarie, I tried to make sure that this doesn't break the BSD builds but it may as we don't have CI there.

**Comment by brson** [comment]
@alexcrichton Can you link me to the libc changes this pulls in? I'm curious what was involved.

**Comment by alexcrichton** [comment]
So far (although this is likely to grow to be a longer list) it required 2 changes:

* https://github.com/rust-lang-nursery/libc/pull/89
* https://github.com/rust-lang-nursery/libc/pull/90

(the latter of which I now realize still needs to land...)

**Comment by steveklabnik** [comment]
:heart_eyes:

**Comment by semarie** [comment]
@alexcrichton thanks to Cc me. currently, it breaks at least openbsd.

I have manually applied the patch (so I could also had done mistakes).
And while building libstd:
```
CFG_LLVM_LINKAGE_FILE=/home/builder/build/openbsd-master/build/x86_64-unknown-openbsd/rt/llvmdeps.rs LD_LIBRARY_PATH=/home/builder/build/openbsd-master/build/x86_64-unknown-openbsd/stage0/lib:$LD_LIBRARY_PATH   x86_64-unknown-openbsd/stage0/bin/rustc --cfg stage0 -Z print-link-args  -O --cfg rtopt -C prefer-dynamic -C no-stack-check --target=x86_64-unknown-openbsd  -W warnings -L "x86_64-unknown-openbsd/rt" -L native="/opt/llvm-cde1ed3196ba9b39bcf028e06e08a8722113a5cb/lib"     -L "/usr/local/lib/gcc/x86_64-unknown-openbsd5.8/4.9.3/../../../" --out-dir x86_64-unknown-openbsd/stage0/lib/rustlib/x86_64-unknown-openbsd/lib -C extra-filename=-71b07a99 ../src/libstd/lib.rs
../src/libstd/sys/unix/fs.rs:220:13: 220:34 error: failed to resolve. Use of undeclared type or module `slice` [E0433]
../src/libstd/sys/unix/fs.rs:220             slice::from_raw_parts(self.entry.d_name.as_ptr() as *const u8,
                                             ^~~~~~~~~~~~~~~~~~~~~
../src/libstd/sys/unix/fs.rs:220:13: 220:34 help: run `rustc --explain E0433` to see a detailed explanation
../src/libstd/sys/unix/fs.rs:220:13: 220:34 error: unresolved name `slice::from_raw_parts` [E0425]
../src/libstd/sys/unix/fs.rs:220             slice::from_raw_parts(self.entry.d_name.as_ptr() as *const u8,
                                             ^~~~~~~~~~~~~~~~~~~~~
../src/libstd/sys/unix/fs.rs:220:13: 220:34 help: run `rustc --explain E0425` to see a detailed explanation
../src/libstd/sys/unix/os.rs:207:24: 207:44 error: unresolved name `libc::KERN_PROC_ARGS` [E0425]
../src/libstd/sys/unix/os.rs:207                        libc::KERN_PROC_ARGS,
                                                        ^~~~~~~~~~~~~~~~~~~~
../src/libstd/sys/unix/os.rs:207:24: 207:44 help: run `rustc --explain E0425` to see a detailed explanation
../src/libstd/sys/unix/os.rs:209:24: 209:44 error: unresolved name `libc::KERN_PROC_ARGV` [E0425]
../src/libstd/sys/unix/os.rs:209                        libc::KERN_PROC_ARGV];
                                                        ^~~~~~~~~~~~~~~~~~~~
```

I can't check deeper today, but I will take a look tomorrow.

**Comment by alexcrichton** [comment]
Thanks @semarie! I've added the imports for `slice` and I'm adding the constants to libc in https://github.com/rust-lang-nursery/libc/pull/91.

**Comment by brson** [comment]
@alexcrichton I think I would like the source to explicitly separate the cases where the cast is needed there - it seems like it *must* be a bug right?

**Comment by cuviper** [comment]
It's a bad thing if these functions ever truncate values for `DirEntry`, `MetadataExt`, etc.  On Android this comes up for quite a few fields, `d_ino`, `d_off`, `st_ino`, `st_size`, `st_blocks`, and more, where `stat` and `dirent` have 64-bit types despite their 32-bit `ino_t`, `off_t`, etc.  On Linux it will also come up when I switch to LFS `stat64` etc.

I think we should either fake the `os::raw` types to sufficient 64-bit sizes, which means they won't match the `libc` types of the same name, or we should change return values to reflect the actual types at hand, which means this will vary by platform.  e.g. on Android `DirEntry::ino() -> u64` to match `d_ino`, instead of `-> raw::ino_t`.

**Comment by alexcrichton** [comment]
I've pushed a commit to remove the cast, and I just started updating the `ino_t` type in `std::os::raw` to reflect what's actually returned (e.g. the larger type).

That's a little controversial to me, however, as the types in `std::os::raw` are basically becoming lies. I'm gonna tag this with T-libs to discuss that a little more, especially with respect to the other values inside of `std::os::raw` and 64-bit stat support on Linux.

**Comment by alexcrichton** [comment]
And to make my concerns a little more concrete, here's what I'm thinking:

* The return value of `ino` is a good example where *some* platforms store the field in the struct as the literal `d_ino` type, but other platforms (like android) store a different type (e.g. u64) and the actual `d_ino` type is different (e.g. u32). This means that if we can't make `d_ino` the "FFI compatible type" as well as the right-width type for the purpose at hand.
* Some platforms like Linux can have the meaning of types like `off_t` change based on `#define` directives in play. For example with LFS (large file support) it will become 64-bits on 32-bit platforms, but otherwise it's 32-bits on 32-bit platforms. This also affects the `stat` type as well. Like with the previous bullet, it's impossible to provide "FFI compatible types" here as well as retaining the same name in all situations.

Overall I would propose a plan that looks like:

1. Remove all symbolic names for types on all platforms. Concretely mark them all `#[rustc_deprecated]` and `#[doc(hidden)]` eventually in the future.
2. Change basically everything to return `u64` or `i64` depending on signedness.
3. Add a whole mess of extension traits to access all the lowered fields of `stat` on all platforms.

This will separate us from the C names as well as how they may change depending on how C code is compiled, and it means that we are no longer providing types that are "FFI compatible" as it doesn't always work out.

For now we can probably leave the basic integer definitions (e.g. `c_void`, `c_int`, and such) as not deprecated, but I'd also be tempted to just deprecate all of them as well...

**Comment by cuviper** [comment]
:+1: for hiding these and going all 64-bit.

Keeping fundamental C types (`c_void`, `c_int`, `c_char`, et al) sounds sane, then leave all the derived types to libc as much as possible

**Comment by alexcrichton** [comment]
re-r? @brson 

I'd like to move forward on this rather than wait for dealing with questions about other types in play here. Along those lines this patch now preserves the same behavior we have today.

**Comment by brson** [comment]
r=me

**Comment by dhuseby** [comment]
When #30643 lands, i'll take a close look at the BSD builds and fix anything up that is needed.

**Comment by larsbergstrom** [comment]
FYI, this did end up breaking Android. It broke rust-errno (https://github.com/lfairy/rust-errno), and getting a fix landed for that is currently blocking Servo's rustup.

Maybe we should just backport the symbol removed here (`__errno_location`) into Servo until we can reach @lfairy?

**Comment by alexcrichton** [comment]
@larsbergstrom you can probably fix it temporarily by adding this to any crate:

```rust
#[cfg(target_os = "android")]
#[no_mangle]
pub unsafe extern fn __errno_location() -> *mut i32 {
    extern { fn __errno() -> *mut i32; }
    __errno()
}
```

**Comment by larsbergstrom** [comment]
@alexcrichton Yeah, thanks! I was thinking of doing just that. Otherwise, we might have to fork errno, add a submodule for it, add a `paths` override to `.cargo/config`, etc. Ick!

**Comment by dhuseby** [comment]
@alexcrichton @semarie when https://github.com/rust-lang/rust/pull/31230 and https://github.com/rust-lang-nursery/libc/pull/157 land, the BSD builds should be green.

**Pull request merged**
