### PR TITLE
[DO NOT MERGE] Perf run for zoxc's rustc-hash

### PR DESCRIPTION
**Pull request by lqd**
This is another perf run to try and see the results of zoxc's version of the 64b fxhash, from their [rustc-hash PR](https://github.com/rust-lang/rustc-hash/pull/18).

This was previously tried in https://github.com/rust-lang/rust/pull/93651 on the older benchmarks, and we now want to see the results on the recently updated `rustc-perf` benchmarks.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
As before: instruction counts are barely changed, but cycles and wall times look like a clear improvement.

**Comment by nnethercote** [comment]
I did a local run on my Intel Linux box and results were underwhelming. Instruction counts barely changed. Cycles for primary benchmarks, `check full` runs:

Benchmark | Profile | Scenario | % Change | Significance Factor?
-- | -- | -- | -- | --
libc-0.2.124 | check | full | -1.68% | 8.38x
cargo-0.60.0 | check | full | 1.33% | 6.63x
unicode-normalization-0.1.19 | check | full | -1.32% | 6.61x
stm32f4-0.14.0 | check | full | -1.23% | 6.13x
clap-3.1.6 | check | full | 0.91% | 4.54x
html5ever-0.26.0 | check | full | 0.56% | 2.82x
syn-1.0.89 | check | full | 0.50% | 2.49x
diesel-1.4.8 | check | full | -0.48% | 2.40x
regex-1.5.5 | check | full | -0.43% | 2.15x
cranelift-codegen-0.82.1 | check | full | -0.43% | 2.13x
hyper-0.14.18 | check | full | 0.34% | 1.71x
bitmaps-2 | check | full | -0.33% | 1.63x
serde_derive-1.0.136 | check | full | 0.32% | 1.59x
ripgrep-13.0.0 | check | full | -0.31% | 1.57x

and secondary (many of these are non-rustc-perf benchmarks that I have downloaded):

Benchmark | Profile | Scenario | % Change | Significance Factor?
-- | -- | -- | -- | --
unused-warnings | check | full | -8.00% | 40.00x
wf-projection-stress-65510 | check | full | 4.83% | 24.15x
deep-vector | check | full | -4.59% | 22.96x
ucd | check | full | -3.82% | 19.08x
coercions | check | full | -3.57% | 17.87x
issue-58319 | check | full | 3.33% | 16.63x
await-call-tree | check | full | -3.26% | 16.28x
tuple-stress | check | full | -2.96% | 14.80x
match-stress | check | full | -2.73% | 13.64x
yansi-0.5.0 | check | full | 2.64% | 13.21x
many-assoc-items | check | full | -2.27% | 11.34x
inotify-0.10.0 | check | full | 2.22% | 11.08x
memchr-2.4.1 | check | full | 2.17% | 10.87x
ctor-0.1.21 | check | full | 1.94% | 9.71x
tokio-1.17.0 | check | full | -1.79% | 8.93x
externs | check | full | 1.78% | 8.91x
issue-46449 | check | full | -1.46% | 7.32x
log-0.4.16 | check | full | 1.38% | 6.91x
deeply-nested-multi | check | full | 1.37% | 6.87x
enum-as-inner-0.4.0 | check | full | -1.31% | 6.57x
regression-31157 | check | full | -1.28% | 6.39x
enumflags2_derive-0.7.4 | check | full | -1.27% | 6.34x
issue-88862 | check | full | -1.22% | 6.12x
num-derive-0.3.3 | check | full | -1.14% | 5.70x
wayland-scanner-0.29.4 | check | full | -1.07% | 5.33x
unicode-xid-0.2.3 | check | full | -0.96% | 4.79x
diesel_derives-1.4.1 | check | full | -0.78% | 3.90x
rustfix-0.6.0 | check | full | 0.76% | 3.80x
token-stream-stress | check | full | 0.75% | 3.76x
derive | check | full | -0.72% | 3.62x
proc-macro2-1.0.38 | check | full | -0.66% | 3.30x
ostn15_phf | check | full | -0.66% | 3.28x
stdweb-derive-0.5.3 | check | full | 0.59% | 2.94x
web-sys-0.3.56 | check | full | 0.58% | 2.88x
tonic-build-0.7.0 | check | full | 0.55% | 2.76x
unify-linearly | check | full | -0.53% | 2.63x
clap_derive-3.1.7 | check | full | -0.49% | 2.45x
wasm-bindgen-backend-0.2.79 | check | full | 0.46% | 2.30x
futures-lite-1.12.0 | check | full | -0.44% | 2.22x
futures-macro-0.3.19 | check | full | 0.43% | 2.15x
pest_generator-2.1.3 | check | full | 0.40% | 2.02x
wg-grammar | check | full | 0.40% | 2.00x
projection-caching | check | full | 0.38% | 1.90x
time-macros-0.2.3 | check | full | -0.33% | 1.66x
vsdb_derive-0.21.1 | check | full | 0.33% | 1.66x
scroll_derive-0.11.0 | check | full | -0.33% | 1.64x
async-std-1.10.0 | check | full | 0.33% | 1.63x
wast-39.0.0 | check | full | -0.32% | 1.60x
nix-0.23.1 | check | full | 0.30% | 1.52x

Walltimes are generally too noisy on local runs to say much.

**Comment by lqd** [comment]
As discussed, this looked like a clearer win on AMD. It's unclear on Intel, so it may not be worth it to bother anymore with this PR exactly as-is. It was on our performance roadmap, we tried it, and it's not a definite win. Closing the PR.

**Pull request closed without merging**
