### PR TITLE
Implement suggestions for `elided_named_lifetimes`

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
A follow-up to #129207, as per https://github.com/rust-lang/rust/pull/129207#issuecomment-2308992849.

r? cjgillot

I will probably squash this a bit, but later.

@rustbot label +A-lint

### CODE REVIEW

**Comment by GrigorenkoPV** [comment]
Apparently this is in conflict with clippy's `needless_lifetimes`. For
```rust
fn foo<'a>(x: &'a str) -> &str
```
this suggests adding lifetime to the output, but clippy suggests removing it from the input. Applying both at the same time produces
```rust
fn foo(x: &str) -> &'a str
```
which is not correct.

I would say that `needless_lifetimes` here is probably a more sensible suggestion than `elided_named_lifetimes`.

Though, if one applies `elided_named_lifetimes` first, then `needless_lifetimes` is still able to tell that the lifetime can still be removed, and the result is not broken.

Idk how to fix this one.

**Comment by GrigorenkoPV** [comment]
It seems like without suggestions, `elided_named_lifetimes` can be quite confusing: https://github.com/rust-lang/rust/pull/129207#issuecomment-2333175482, so I feel like it is a priority to get this PR out in a timely manner, but there is a blocker at the moment: https://github.com/rust-lang/rust/pull/129840#issuecomment-2323349119

I see three possible ways of dealing with the issue.

1. **Hack around the conflict now**
   
   This is what I've done: 9e2d264fa251f98780084382a071e10a123770d6. This commit simply disables the suggestions for non-`'static` cases[^applicability].
   
   **Pros**: no stalling, adds some suggestions, there is no conflict, the hack is easy to revert once we resolve the issue.
   **Cons**: many suggestions are missing.
   
2. **Ignore the conflict**

    Just merge as is (removing the failing test), and deal with it later. The fallout of the conflict would probably be rather small[^cn].
    
    **Pros**: no stalling, all suggestions are added.
    **Cons**: potential conflicts with a clippy `complexity` lint.

3. **Resolve this now**

    Do not merge this PR until the issue is resolved.
    
    **Pros**: all suggestions are added, there is no conflict
    **Cons**: high risk of missing the `1.83` release window, which `elided_named_lifetimes` has landed into.

[^applicability]: I've tried setting `applicability` to `Unspecified` instead of `MachineApplicable` for potentially conflicting cases, but it didn't seem to help.
[^cn]: citation needed

**Comment by cjgillot** [comment]
@bors r+ rollup

The easiest way to remove the conflict could be to uplift the needless_lifetimes lint to rustc. It may fit well with the current architecture of the code, but I haven't tried writing any code.

**Comment by GrigorenkoPV** [comment]
Okay, I've managed to swap the priorities between `elided_named_lifetimes` and `cippy::needless_lifetimes`. Now the latter does not emit when the former would.[^conflict]

[^conflict]: And unlike with the 9e2d264fa251f98780084382a071e10a123770d6 hack, the suggestion is suppressed only when there *would* be a conflict, not when there *potentially could* be a conflict.

<details>
<summary>Patch</summary>

```patch
diff --git a/compiler/rustc_lint/src/lints.rs b/compiler/rustc_lint/src/lints.rs
index ae7e9659856..693f1b22587 100644
--- a/compiler/rustc_lint/src/lints.rs
+++ b/compiler/rustc_lint/src/lints.rs
@@ -2639,13 +2639,6 @@ fn decorate_lint(self, diag: &mut rustc_errors::Diag<'_, G>) {
         if let Some(declaration) = declaration {
             diag.span_label(declaration, fluent::lint_label_named);
         }
-        // FIXME(GrigorenkoPV): this `if` and `return` should be removed,
-        //  but currently this lint's suggestions can conflict with those of `clippy::needless_lifetimes`:
-        //  https://github.com/rust-lang/rust/pull/129840#issuecomment-2323349119
-        // HACK: `'static` suggestions will never sonflict, emit only those for now.
-        if name != rustc_span::symbol::kw::StaticLifetime {
-            return;
-        }
         match kind {
             MissingLifetimeKind::Underscore => diag.span_suggestion_verbose(
                 span,
diff --git a/src/tools/clippy/clippy_lints/src/lifetimes.rs b/src/tools/clippy/clippy_lints/src/lifetimes.rs
index ba34af9c100..793ef442c13 100644
--- a/src/tools/clippy/clippy_lints/src/lifetimes.rs
+++ b/src/tools/clippy/clippy_lints/src/lifetimes.rs
@@ -420,6 +420,9 @@ fn could_use_elision<'tcx>(
         .filter_map(|(def_id, occurrences)| {
             if occurrences == 1
                 && (input_lts.len() == 1 || !output_lts.iter().any(|lt| named_lifetime(lt) == Some(def_id)))
+                && !output_lts
+                    .iter()
+                    .any(|lt| suggested_by_elided_named_lifetimes(lt, def_id))
             {
                 Some(def_id)
             } else {
@@ -437,6 +440,10 @@ fn could_use_elision<'tcx>(
     Some((elidable_lts, usages))
 }
 
+fn suggested_by_elided_named_lifetimes(lt: &Lifetime, res: LocalDefId) -> bool {
+    lt.res == LifetimeName::Param(res) && matches!(lt.ident.name, kw::Empty | kw::UnderscoreLifetime)
+}
+
 fn allowed_lts_from(named_generics: &[GenericParam<'_>]) -> FxHashSet<LocalDefId> {
     named_generics
         .iter()
```

</details>

but the problem now is that

> if one applies `elided_named_lifetimes` _first_, then `needless_lifetimes` is still able to tell that the lifetime can be removed (now from both input and output)

This does result in only correct code along the way, but it makes a new suggestion pop up after the previous is applied. The testsuite does not like that:
```
error: test got exit status: 1, but expected 0
   --> tests/ui/needless_lifetimes.fixed:266:30
    |
266 | fn named_input_elided_output<'a>(_arg: &'a str) -> &'a str {
    |                              ^^ after rustfix is applied, all errors should be gone, but weren't
    |
```

So, to reiterate my previous point:

> I would say that `needless_lifetimes` here is probably a more sensible suggestion than `elided_named_lifetimes`.

We should probably emit `needless_lifetimes` first, cache the set of lifetime params that were suggested to be elided, and then just avoid those in `elided_named_lifetimes`.

The problem is that we emit `elided_named_lifetimes` immediately during lifetime resolution, while `needless_lifetimes` walks the tree after the fact.

I don't think we can move `needless_lifetimes` inside the resolution (it fundamentally works with already resolved lifetimes and walks the tree quite a lot). But maybe we can move `elided_named_lifetimes` outside of resolution and into the same pass as `needless_lifetimes`.[^latelintpass]

[^latelintpass]:  It seems like we can easily detect the lifetimes that `needless_lifetimes` is interested in using `matches!(lt.res, LifetimeName::Param(_) | LifetimeName::Static) && matches!(lt.ident.name, kw::Empty | kw::UnderscoreLifetime)`. Though, we do lose access to `MissingLifetimeKind`, which was quite handy for suggestions. But maybe we can propagate it or infer it from the context. Speaking of inferring from the context, moving `elided_named_lifetimes` to a `LateLintPass` will probably eliminate the need for the `LifetimeRes::Static.suppress_elision_warning` & `MissingLifetime.id_for_lint` hacks.

> The easiest way to remove the conflict could be to uplift the needless_lifetimes lint to rustc.

It seems like uplifting is unavoidable here, because we need some information to flow from `needless_lifetimes` to `elided_named_lifetimes`. But `needless_lifetimes` currently has some issues:

- It might be too aggressive for people's liking: https://github.com/rust-lang/rust-clippy/issues/9694
- Broken suggestions
  - https://github.com/rust-lang/rust-clippy/issues/12789
  - Sometimes not all occurrences are removed
    - https://github.com/rust-lang/rust-clippy/issues/10495
    - https://github.com/rust-lang/rust-clippy/issues/11291
- It can produce overlapping suggestions
  - https://github.com/rust-lang/rust-clippy/issues/11197
  - https://github.com/rust-lang/rust-clippy/issues/12495
- False positives
  - https://github.com/rust-lang/rust-clippy/issues/12908
- Some false negatives, but that is not an issue for uplifting.

There was an attempt to fix those but it seemingly got abandoned right at the start: https://github.com/rust-lang/rust-clippy/pull/13141 https://github.com/rust-lang/rust-clippy/pull/12456

Soo, should we maybe just break `needless_lifetimes` even further and go with [the option 2](https://github.com/rust-lang/rust/pull/129840#issuecomment-2334250112)?

**Pull request merged**
