### PR TITLE
Shrink RELEASES.md

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This is a mostly[^1] identically rendered result, while cutting 9.4% (59.5 kilobytes, roughly 6 releases worth) from the file. My hope is that this puts us back into territory where GitHub is rendering the file without issues, giving us some more time to figure out next steps for shrinking/adjusting future releases.

Tested with manual inspection of HTML diffs generated by pulldown-cmark. See the inlining script embedded into the "Inline [...]" commit for how I did the replacement.

cc @ehuss

r? @cuviper 

[^1]: In practice, we had a bunch of references that collided previously or where duplicated with different links (e.g., one to nightly and one to stable). The commits here clean those cases up while we're touching this so that there's less manual inspection needed.

### CODE REVIEW

**Comment by jeffparsons** [comment]
Surely someone in the Rust org knows someone on the GitHub team. I'm not suggesting that they would/should do all the work to migrate to a better renderer just because it would help Rust... but maybe they could at least offer a more generous timeout to a reputable org like rust-lang...

I've had multiple SaaS providers add these kinds of exceptions for teams I'm on in the past, so I wouldn't assume they'll say no until they've actually said no.

**Comment by est31** [comment]
Not sure if still done but there is [evidence on zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/call.20with.20github) that there are regular calls with github staff happening by Rust representatives.

**Comment by cuviper** [comment]
> Large diffs are not rendered by default. 

/me hits "Load diff"

> Oops, something went wrong.

Oh, the irony...

**Comment by cuviper** [comment]
More seriously, I don't really see a good way to review this. I can fetch the patch locally, but it's a lot of rote replacement to be reviewing by hand. I trust your own verification via pulldown-cmark, but since the new file is still failing to render, we can't really see it "live". And if we haven't actually bought any time there, I'm not sure there's any point in the churn.

(Some of your changes are probably good fixes on their own merit though.)

**Comment by Mark-Simulacrum** [comment]
Yeah. I think you can best review commit by commit and checking with pulldown-cmark yourself (similar to what I did myself), but I agree it may not be worth it since this doesn't seem to fix the problem.

**Pull request closed without merging**
