### PR TITLE
Add as_c_str

### PR DESCRIPTION
**Pull request by clarfonthey**
Again, tying up some consistencies with `CString`.

### CODE REVIEW

**Comment by clarcharr** [comment]
cc @alexcrichton and #40380

**Comment by alexcrichton** [comment]
Seems reasonable to me, thanks!

Looks like `as_os_str` may already exist though?

**Comment by clarcharr** [comment]
Oh, huh, you're right. Will fix.

**Comment by clarcharr** [comment]
Passes now! Ready to merge.

**Comment by TimNN** [comment]
@bors retry

* #38618

**Pull request merged**
