### PR TITLE
Fix invalid removal of newlines from doc comments

### LINKED ISSUE #91201: Newlines don't cause a paragraph break when mixing `#[doc]` and `///`
See the test added in #91199. This code:

```rust
#[doc = "Hello world!\n\n"]
/// Goodbye!
#[doc = "  Hello again!\n"]
pub struct S1;
```

renders as:

> Hello world! Goodbye! Hello again!

rather than the expected:

> Hello world!
>
> Goodbye! Hello again!

Meanwhile, changing some `#[doc]`s to `///`s and vice versa causes it to render as expected.

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/91201.

Before:

Screenshot from 2021-12-28 17-02-11

After:

Screenshot from 2021-12-28 17-02-25

r? @camelid

### CODE REVIEW

**Comment by camelid** [comment]
I realize this could be a breaking change, so I [opened a discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/stop.20trimming.20newlines.20from.20doc.20strings).

**Comment by pnkfelix** [comment]
Discussed at T-compiler meeting. Looks like T-rustdoc and T-compiler are all fine with it.

@rustbot label: -S-waiting-on-team +S-waiting-on-review

**Review by camelid — APPROVED** [review]
Can you add this as another `@snapshot` test case to `mixing-doc-comments-and-attrs`? After that (assuming the output is as two separate paragraphs), r=me

```rust
/** Par 1
*/ ///
/// Par 2
```

**Comment by camelid** [comment]
Interesting historical note: As part of reviewing this, I did a git blame to see when this line trimming code was added. It turns out it's existed since the very beginning of sugared doc comment syntax, back in 2012: https://github.com/rust-lang/rust/commit/0b653ab9539140bb04941de9a36c03cf10bfc28b#diff-4f03b42b44fcc76340e613b56e73a2202d12544a8b464a311a49ad0517d6e474R43-R48. I still don't know why it was considered necessary 🤷

**Comment by camelid** [comment]
Another historical note: The `//~ ERROR` syntax used in the test suite was originally `//! ERROR`. It had to be [changed](https://github.com/rust-lang/rust/issues/2498#issuecomment-6643154) because of the new doc-comment syntax.

**Comment by GuillaumeGomez** [comment]
@camelid: Updated! I'll let you check if the added test looks like what you expected. ;)

**Comment by camelid** [comment]
Oops, looks like I forgot to approve this.

@bors r+

**Comment by camelid** [comment]
Marking this as `relnotes` for compatibility reasons. Probably not necessary, but maybe it's worth pointing out. Feel free to unmark this if you disagree.

**Comment by GuillaumeGomez** [comment]
I think it's fine to mention it even though I don't expect anyone to be impacted by this.

**Pull request merged**
