### PR TITLE
Extend mir dump to dump each region

### PR DESCRIPTION
**Pull request by chrisvittal**
Building on #44878, implement the feature discussed in #44872. 

Through discussions on the WG-nll-gitter, @nikomatsakis and I decided to implement this by extending `dump_mir` and all functions that it calls to take a callback of signature `FnMut(PassWhere, &mut Write) -> io::Result<()>` where `PassWhere` is an enum that represents possible locations that we may want to print out extra data in the process of dumping the MIR.

I'm not particularly wedded to the name `PassWhere`, but I felt that simply calling the enum `Where` wasn't the right thing to name it.

This work depends strongly on #44878, and should be rebased on the final version of that tree, whatever that may be.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
r @nikomatsakis

**Review by nikomatsakis — APPROVED** [review]
This looks great @chrisvittal!

**Comment by kennytm** [comment]
@bors retry 

* Android SDK HTTPS issue (fixed in #45193)

**Pull request merged**
