### PR TITLE
Cache CI Docker images in ghcr registry

### PR DESCRIPTION
**Pull request by Kobzol**
This PR changes the way `rust-lang` caches Docker images used in CI workflows. Before, the intermediate Docker layers were manually exported from `docker history` and backed up in S3. However, this approach doesn't work any more with the Docker version used by GitHub Actions since August 2023. We had to revert to disabling Docker BuildKit to make the old caching work, but this workaround will stop working eventually, after GitHub updates Docker again and the old build backend will be removed.

This PR changes the caching to use [Docker caching](https://docs.docker.com/build/cache/) instead. There are several backends for the cache, for our use-case S3 and Docker registry makes sense. This PR uses the Docker registry backend and uses the ghcr.io registry.

The caching creates a Docker image labeled `rust-ci`, which is currently stored to the `ghcr.io/rust-lang-ci` package registry. This image appears [here](https://ghcr.io/rust-lang-ci/rust-ci). The image is stored in `rust-lang-ci` and not `rust-lang`, because `try` and `auto` builds run in the context of that repository, so the used `GITHUB_TOKEN` has permissions for it (unlike for `rust-lang`).

For pull request CI runs, the provided `GITHUB_TOKEN` reduces its permissions automatically to `packages: read`, which means that we won't be able to write the Docker image. If we're not able to write, we won't have anything to read. So I disabled the caching entirely for PR runs (it makes it slightly faster to build the Docker image if we don't have to deal with exporting and using a separate build driver). Note that before this PR, we also weren't able to read or write the cache on PR runs.

Rustup part of this change is [here](https://github.com/rust-lang/rustup/pull/3648).

Related issue: https://github.com/rust-lang/infra-team/issues/81

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try

This broadly looks fine to me -- is there a reason I don't see try builds etc. on this PR? I think we should test out that it works on try + local builds (src/ci/docker/run.sh from your laptop or w/e), and perhaps get rustup CI working, and then we can merge.

**Comment by Kobzol** [comment]
>  is there a reason I don't see try builds etc. on this PR

I tested a try build on a different PR, but we should of course also try it here.

What I'm struggling with currently is how to use the cache as a `docker pull`-able image from rustup. It doesn't seem to be possible to pull the cached images from the repository.

**Comment by Mark-Simulacrum** [comment]
@rustbot author

Let me know if I can/should try to help here, otherwise will put this in waiting on author for now.

**Comment by Kobzol** [comment]
The Rustup part of this change is at: https://github.com/rust-lang/rustup/pull/3648. Local build seems to work.

**Comment by Kobzol** [comment]
Try build seems to be cached, local build seems to work, the Rustup part is implemented [here](https://github.com/rust-lang/rustup/pull/3648). I also added more comments to the script.

@rustbot ready

**Comment by Kobzol** [comment]
@bors r=Mark-simulacrum

(This run will fail, but I added additional logging to help me debug the used Docker version on our self-hosted runners).

**Pull request merged**
