### PR TITLE
Stabilize `Option::filter`.

### LINKED ISSUE #45860: Tracking issue for Option::filter (feature `option_filter`)
This is a tracking issue for `Option::filter`.

- Proposed in https://github.com/rust-lang/rfcs/issues/1485
- RFC written in https://github.com/rust-lang/rfcs/pull/2124
- Initial implementation in #44996 (not merged)
- Resubmitted in #45863

Unresolved questions: 

- [ ] decide on name (`filter` vs `and_if` vs …)

### PR DESCRIPTION
**Pull request by tmccombs**
Fixes #45860

### CODE REVIEW

**Comment by frewsxcv** [comment]
there a couple other instances of the feature flag that can be removed:

https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=option_filter&type=

**Comment by pietroalbini** [comment]
Ping from triage @withoutboats! This PR needs your review.

**Pull request merged**
