### PR TITLE
Convert Operand::Move to Operand::Copy

### PR DESCRIPTION
**Pull request by saethlin**
Looks like this fires ~72,000 times on the standard library. Neat.

Note: The unleashed version fires ~165,000 times.

cc @JakobDegen

### CODE REVIEW

**Comment by JakobDegen** [comment]
Is there any reason to do this besides the specific example we'd talked about yesterday?

I'm not so sure this is the right way to address the issue that destprop has. Specifically, destprop needs to be taught to be smarter about dealing with "removable writes" anyway for the purpose of storage statements (see my comment [here](https://github.com/rust-lang/rust/pull/96451#discussion_r933910276)) and once it can do that, fixing this will be pretty straight forward

**Comment by saethlin** [comment]
This is simple/easy to slap together quickly, and is unlikely to be a perf issue in itself. So it is a way to assess what the opportunity is. Of course you know much better than I if this is actually something that should be merged, but I think a PR and perf run is a step to assessing that.

**Comment by JakobDegen** [comment]
Oh, yeah, don't misunderstand, this is definitely something we should try. That being said, I don't actually see how this could show an improvement in PRLO. In any case, my comment was about whether this made sense to merge, so do carry on with whatever experiments you're interested in

**Comment by compiler-errors** [comment]
sorry for the noise but bors thinks this is a merge and not a try for some reason:

image

and the rollup isn't testing because of that :rofl: 

@bors r- maybe this will do it

**Comment by saethlin** [comment]
This was a cool experiment to feed discussion about DestinationPropagation, but that's all it is ultimately.

**Pull request closed without merging**
