### PR TITLE
trans: Try to detect the Universal CRT on MSVC

### PR DESCRIPTION
**Pull request by alexcrichton**
Visual Studio 2015, recently released, includes the Universal CRT, a different
flavor than was provided before. The binaries and header files for this library
are included in new locations not previously known about by gcc-rs, and this
commit adds support for the necessary probing to find these.

Unfortunately there are no prior examples of this probing to be found in
frameworks like CMake or clang, so this is done is a bit of a sketchy method
today. It assumes that the installation is in a relatively standard format and
then blindly looks for the location of the UCRT. I'd love to switch this over to
using registry keys for probing, but I was currently unable to find such keys.

This should enable the compiler to work outside VS 2015 dev tools prompts.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

cc @retep998, @vadimcn 

I'm.. not actually sure this is the best way to do this, but it's nice to not have to spin up dev tool shells for a number of reasons!

**Comment by alexcrichton** [comment]
Another example of where this helps is that all our `appveyor.yml` files for external crates have [this line](https://github.com/rust-lang/time/blob/master/appveyor.yml#L12) which can be removed after this lands.

**Comment by vadimcn** [comment]
MSBuild's logic for finding uCRT can be found in this file: `C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\uCRT.props` (if you have VS2015 installed).
Looks like they start with directory specified in this registry entry: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots@KitsRoot10`, then append `lib\$(TargetUniversalCRTVersion)\ucrt\$(Arch)`

**Comment by alexcrichton** [comment]
@vadimcn oh nice! Do you know if there's a better way to detect whether an VS installation is using the uCRT? Right now the logic would be something along the lines of "If the VS installation folder '14.0' in it then look at the registry entry (you specified above), find the max 'KitsRootXXX' key, probe for the version of the ucrt (max numerical value in the Lib/ folder), and then add the appropriate LIB path".

I'm somewhat uncomfortable about:

* Looking for the uCRT only if we see "14.0" in a folder name
* Looking for the uCRT in KitsRootXX (for the maximum XX). Or is this always going to be `KitsRoot10`?
* Probing for the version of the uCRT by just iterating over some folders.

I definitely think though that finding the installation root through the registry is probably better than "find the 8.1 one and then pop a directory and add a 10 onto it" :)

**Comment by alexcrichton** [comment]
Also, it looks like `TargetUniversalCRTVersion` comes from `TargetPlatformVersion`, but I can't seem to find where that originates from, would you happen to know where that is?

**Pull request merged**
