### PR TITLE
x.py: Give a more helpful error message if curl isn't installed

### PR DESCRIPTION
**Pull request by jyn514**
Before:

```
Updating only changed submodules
Submodules updated in 0.01 seconds
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  ...
  File "/home/joshua/src/rust/src/bootstrap/bootstrap.py", line 137, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

After:

```
Updating only changed submodules
Submodules updated in 0.01 seconds

spurious failure, trying again

spurious failure, trying again

spurious failure, trying again

spurious failure, trying again
failed to run: curl -s -y 30 -Y 10 --connect-timeout 30 --retry 3 -Sf -o /tmp/tmpSWF21P.sha256 https://static.rust-lang.org/dist/2020-04-22/rust-std-beta-x86_64-unknown-linux-gnu.tar.gz.sha256: [Errno 2] No such file or directory
Build completed unsuccessfully in 0:00:00
```

### CODE REVIEW

**Comment by jyn514** [comment]
I'm not sure that the `RuntimeError` is the right way to go about things since other parts of the program seem to assume that means a spurious failure ... I'm not sure how else to give a reasonable message though. Maybe it would be better to just print the error and exit unconditionally?

**Comment by Mark-Simulacrum** [comment]
Hm, we can probably do the same thing we do for git? IIRC we run git --version and if that fails assume git isn't installed or won't do what we need.

**Comment by jyn514** [comment]
Ooh that looks like a good way to do it! I see that sort of thing is repeated a lot (also for `uname`, `isainfo`) - do you mind if I factor it out into a function at the same time?

**Comment by Mark-Simulacrum** [comment]
Not at all, please do!

**Comment by jyn514** [comment]
The new output is

```
Updating only changed submodules
Submodules updated in 0.01 seconds
error: `curl` is not found, please make sure it's installed and in the path.
```

**Comment by jyn514** [comment]
I realized that this will now give a misleading error if you have the command in path but the command failed (e.g. maybe `-s` isn't a valid argument to uname). I'm going to print out the entire that command that failed instead so it's easier to debug.

**Comment by jyn514** [comment]
New output:
```
Updating only changed submodules
Submodules updated in 0.01 seconds
error: `curl --version` is not found, please make sure it's installed and in the path.
```

**Comment by Mark-Simulacrum** [comment]
Hm, can we perhaps say:

``
Unable to run `curl --version`: OSError: not found
Please make sure it's installed and in PATH.
```

**Comment by jyn514** [comment]
How does this look?
```
error: unable to run `curl --version`: [Errno 2] No such file or directory
Please make sure it's installed and in the path.
```

**Comment by Mark-Simulacrum** [comment]
Please squash the commits into one; r=me after that.

**Pull request merged**
