### PR TITLE
Remove `underscore_lifetimes` and `match_default_bindings` from active feature list

### PR DESCRIPTION
**Pull request by kennytm**
These are already stabilized in 1.26.

### CODE REVIEW

**Comment by kennytm** [comment]
Nominating for beta. These entries are also repeated in beta.

```
$ rg 'underscore_lifetimes|match_default_bindings' -- src/libsyntax/feature_gate.rs
386:    (active, underscore_lifetimes, "1.22.0", Some(44524), None),
389:    (active, match_default_bindings, "1.22.0", Some(42640), None),
567:    (accepted, match_default_bindings, "1.26.0", Some(42640), None),
569:    (accepted, underscore_lifetimes, "1.26.0", Some(44524), None),
```

**Comment by pietroalbini** [comment]
Ping from triage @aturon! This PR needs your review.

**Comment by pietroalbini** [comment]
Ping from triage! Can @aturon or someone else from @rust-lang/compiler review this?

**Pull request merged**
