### PR TITLE
Remove no_stack_check (#34915)

### PR DESCRIPTION
**Pull request by abhijeetbhagat**
Part of the fixes for #34915

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@abhijeetbhagat I think I saw a note that you had many distinct PRs; do you think you can pull them together into one branch? Let me know if you need more help making that happen, git can be a bit rough when getting started. :(

**Comment by abhijeetbhagat** [comment]
@nikomatsakis sure. let me get them into one branch.

**Comment by nikomatsakis** [comment]
@abhijeetbhagat I'm going to close this PR -- please do re-open if you have something more consolidated (or point me at it).

**Pull request closed without merging**
