### PR TITLE
Update LLVM to 1deeee3

### LINKED ISSUE #123772: [MIPS] `AtomicI8` and `AtomicI16` doctests for `fn fetch_min()` and  `fn fetch_max()` began failing in `nightly-2024-04-08`
Hello,

`nightly-2024-04-08` regressed on the following tests on MIPS:

```
failures:
    library/core/src/sync/atomic.rs - sync::atomic::AtomicI16::fetch_max (line 3072)
    library/core/src/sync/atomic.rs - sync::atomic::AtomicI16::fetch_min (line 3072)
    library/core/src/sync/atomic.rs - sync::atomic::AtomicI16::fetch_min (line 3084)
    library/core/src/sync/atomic.rs - sync::atomic::AtomicI8::fetch_max (line 3036)
    library/core/src/sync/atomic.rs - sync::atomic::AtomicI8::fetch_min (line 3036)
    library/core/src/sync/atomic.rs - sync::atomic::AtomicI8::fetch_min (line 3048)

test result: FAILED. 4537 passed; 6 failed; 37 ignored; 0 measured; 6 filtered out; finished in 315.73s
```

I have bisected this to https://github.com/rust-lang/rust/pull/123555 in the Rust repo and to https://github.com/llvm/llvm-project/commit/fbb27d16fa12aa595cbd20a1fb5f1c5b80748fa4 in the LLVM repo.

# How to reproduce

1. (On Debian 12) install a MIPS toolchain:

```sh
sudo apt install \
    gcc-mipsel-linux-gnu \
    libc6-mipsel-cross \
    qemu-user
```

2. Create a file `main.rs` with the following contents (which is a simplified snippet of the failing doctests mentioned above):

```rs
fn main() {
    let x = std::sync::atomic::AtomicI8::new(23);
    assert_eq!(x.fetch_max(42, std::sync::atomic::Ordering::SeqCst), 23);
}
```

3. Build it like this:

```sh
./x build --target mipsel-unknown-linux-gnu
build/x86_64-unknown-linux-gnu/stage1/bin/rustc \
    --target mipsel-unknown-linux-gnu \
    -Clinker=mipsel-linux-gnu-gcc \
    main.rs
```

4. Run like this:

```
qemu-mipsel -L /usr/mipsel-linux-gnu main
```

## Expected

The program completes successfully.

## Actual

The program fails like this:

```
thread 'main' panicked at src/main.rs:3:5:
assertion `left == right` failed
  left: 0
 right: 23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Bisection

With `src/llvm-project` pointing to https://github.com/llvm/llvm-project/commit/fbb27d16fa12aa595cbd20a1fb5f1c5b80748fa4 the test also fails, but when pointing  `src/llvm-project` to the parent commit (https://github.com/llvm/llvm-project/commit/e74c1678231ab2a7c6defe8bb90366e664780d6f) the test passes.

So we can conclude that this regression was introduced by https://github.com/llvm/llvm-project/commit/fbb27d16fa12aa595cbd20a1fb5f1c5b80748fa4, which originates from https://github.com/llvm/llvm-project/pull/77072. 

Edit: See https://github.com/llvm/llvm-project/pull/77072 for more discussion around this.

@rustbot label +O-MIPS +A-atomic +T-compiler +C-bug

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #123772.

Diff: https://github.com/rust-lang/llvm-project/compare/af8f9eb61a2ad4ee1f2d3f46d157b93a47c6a4bf...5399a24c66cb6164cf32280e7d300488c90d5765
Diff (From 18.1.2): https://github.com/rust-lang/llvm-project/compare/0af6c732ec6ca189cd7725e4a7d4290793046e83...5399a24c66cb6164cf32280e7d300488c90d5765

r? @cuviper

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
bors rollup=neeeev3r

**Comment by DianQK** [comment]
Oh no, version 18.1.4 has already been released just now. The new changes don't seem important: https://github.com/llvm/llvm-project/compare/1deeee3f5da4f323e0e5b33688450dc066e9651b...e6c3289804a67ea0bb6a86fadbe454dd93b8d855.

**Comment by DianQK** [comment]
Replace #124044 with this PR.

@rustbot label beta-nominated T-compiler

**Pull request merged**
