### PR TITLE
Simplify `static_assert_size`s.

### PR DESCRIPTION
**Pull request by nnethercote**
We want to run them on all 64-bit platforms.

r? @ghost

### CODE REVIEW

**Comment by Nilstrieb** [comment]
i don't think the try build will be useful as it only runs x86-64 linux, but now I can't approve it :D
r=me after the try build is over

**Comment by nnethercote** [comment]
So should we just mark as a non-rollup, let it attempt the merge, and see if anything fails then?

**Comment by Nilstrieb** [comment]
yeah, that's how we figure out what happens
@bors r+ rollup=iffy

**Comment by saethlin** [comment]
The problem here is the size difference of `PathBuf` on Windows, because internally it has an extra `bool`.

**Comment by nnethercote** [comment]
> The problem here is the size difference of PathBuf on Windows, because internally it has an extra bool.

I have updated that assertion accordingly. Let's try again...

@bors r=Nilstrieb

**Pull request merged**
