### PR TITLE
Add `-Z unpretty` flags for the AST

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Implements rust-lang/compiler-team#408.
Builds on #82269, but if that PR is rejected or stalls out, I can implement this without #82269.
cc rust-lang/rustc-dev-guide#1062

### CODE REVIEW

**Comment by estebank** [comment]
r=me based purely on the last commit, after the FCP is completed.

**Comment by camelid** [comment]
Marking as blocked on #82269.

**Review by spastorino — APPROVED** [review]

**Comment by LeSeulArtichaut** [comment]
rust-lang/compiler-team#408 was accepted and #82269 was merged, so this is now unblocked.

**Comment by LeSeulArtichaut** [comment]
Rebased.

**Pull request merged**
