### PR TITLE
Ignore host C++ runtime in a cross build scenario

### PR DESCRIPTION
**Pull request by inferiorhumanorgans**
I'm not quite sure how this will play out for other cross builds, but in the case of macOS to DragonFly one of the big problems I was running into was the insistence on linking against a non-existent `libc++`.  It turned out that the flags were coming in from the `llvm-config` built for the host, which at first blush seems like the wrong behavior.

### CODE REVIEW

**Comment by wesleywiser** [comment]
Visited during the compiler team triage meeting. @cuviper or @nikic are either of you familiar with build LLVM for cross-platform targets?

**Comment by cuviper** [comment]
To be clear, `rustc_llvm` doesn't build LLVM itself, only our own wrappers `extern "C"` access to some C++ APIs.

This change seems like it may be ok, but fickle. I sure wish we could get the right answer out of `llvm-config`...

> It turned out that the flags were coming in from the `llvm-config` built for the host, which at first blush seems like the wrong behavior.

We do have to run a host binary to run it at all, but it looks like we are *trying* to use the target version of that?
https://github.com/rust-lang/rust/blob/249595b7523fc07a99c1adee90b1947739ca0e5b/src/bootstrap/compile.rs#L1012-L1013

**Comment by inferiorhumanorgans** [comment]
For context I was cross building host tools (`build = macOS, host = target = {dragonfly, solaris-sparc, solaris-x86}`).  I think host flags are being picked up in a few places (e.g. `zlib`) and going from LLVM → GNU C++ runtime just highlights that.  If you've the spare cycles this should be easy enough to verify on a non-mac as well by going from e.g. Linux → DragonFly or Solaris.

Unfortunately I've blown away the build dirs (so this will be a slow context switch), but from looking at the logs I believe this was the root of the problem:
 
```
Building LLVM for x86_64-unknown-dragonfly
…
running: cd "/Users/alex/cross/rust-1.71.1/build/x86_64-unknown-dragonfly/llvm/build" &&
CMAKE_PREFIX_PATH="" DESTDIR="" "cmake" "/Users/alex/cross/rust-1.71.1/src/llvm-project/llvm" 
"-G" "Ninja" "-DLLVM_ENABLE_ASSERTIONS=OFF" "-DLLVM_UNREACHABLE_OPTIMIZE=OFF"
"-DLLVM_ENABLE_PLUGINS=OFF" "-DLLVM_TARGETS_TO_BUILD=AArch64;ARM;BPF;Hexagon;LoongArch;
MSP430;Mips;NVPTX;PowerPC;RISCV;Sparc;SystemZ;WebAssembly;X86" 
"-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR;M68k" "-DLLVM_INCLUDE_EXAMPLES=OFF" 
"-DLLVM_INCLUDE_DOCS=OFF" "-DLLVM_INCLUDE_BENCHMARKS=OFF" "-DLLVM_INCLUDE_TESTS=OFF" 
"-DLLVM_ENABLE_TERMINFO=OFF" "-DLLVM_ENABLE_LIBEDIT=OFF" "-DLLVM_ENABLE_BINDINGS=OFF" 
"-DLLVM_ENABLE_Z3_SOLVER=OFF" "-DLLVM_PARALLEL_COMPILE_JOBS=8" "-DLLVM_TARGET_ARCH=x86_64" 
"-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-dragonfly" "-DLLVM_ENABLE_WARNINGS=OFF" 
"-DLLVM_INSTALL_UTILS=ON" "-DLLVM_ENABLE_ZSTD=OFF" "-DLLVM_ENABLE_ZLIB=ON" 
"-DLLVM_ENABLE_LIBXML2=OFF" "-DLLVM_TABLEGEN=/Users/alex/cross/rust-1.71.1/build/x86_64-
apple-darwin/llvm/build/bin/llvm-tblgen" "-DLLVM_NM=/Users/alex/cross/rust-1.71.1/build
/x86_64-apple-darwin/llvm/build/bin/llvm-nm" "-DLLVM_CONFIG_PATH=/Users/alex/cross/rust-
1.71.1/build/x86_64-apple-darwin/llvm/build/bin/llvm-config" "-DLLVM_VERSION_SUFFIX=-
rust-1.71.1-nightly" "-DCMAKE_INSTALL_MESSAGE=LAZY" "-DCMAKE_CROSSCOMPILING=True" 
"-DCMAKE_SYSTEM_NAME=DragonFly" "-DCMAKE_C_COMPILER=/Users/alex/cross/bin/x86_64-unknown-
dragonfly-gcc" "-DCMAKE_CXX_COMPILER=/Users/alex/cross/bin/x86_64-unknown-dragonfly-g++" 
"-DCMAKE_ASM_COMPILER=/Users/alex/cross/bin/x86_64-unknown-dragonfly-gcc" "-DCMAKE_C_FLAGS=-
ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-
sections -fPIC -m64" "-DCMAKE_AR=/Users/alex/cross/gnu-dragonfly-6.4/bin/x86_64-unknown-
dragonfly-gcc-ar" "-DCMAKE_RANLIB=/Users/alex/cross/gnu-dragonfly-6.4/bin/x86_64-unknown-
dragonfly-gcc-ranlib" "-DCMAKE_SHARED_LINKER_FLAGS=" "-DCMAKE_MODULE_LINKER_FLAGS=" 
"-DCMAKE_EXE_LINKER_FLAGS=" "-DCMAKE_INSTALL_PREFIX=/Users/alex/cross/rust-1.71.1/build
/x86_64-unknown-dragonfly/llvm" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC 
-m64" "-DCMAKE_BUILD_TYPE=Release"
```

Specifically:

`-DLLVM_CONFIG_PATH=/Users/alex/cross/rust-
1.71.1/build/x86_64-apple-darwin/llvm/build/bin/llvm-config`

**Comment by apiraino** [comment]
Hi, visiting and checking progress. I'm a bit unclear about the status of this PR but I _think_ it is waiting on the author. However @inferiorhumanorgans feel free to request a review if you feel it's not the case, thanks.

@rustbot author

**Comment by Dylan-DPC** [comment]
@inferiorhumanorgans any updates on this?

**Comment by JohnCSimon** [comment]
@inferiorhumanorgans 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
