### PR TITLE
Remove quote_*! macros

### LINKED ISSUE #26994: quasi-quoting a block expression doesn't work
`quote_expr!(self.cx, { $result_name = Some($expr); break $loop_label; })` failed with `error: expected one of `.`, `;`, `}`, or an operator, found `'__hoare_2`` (`__hoare_2` is the expected value of `$loop_label`). This failed in expansion so I couldn't get an expanded AST to find out what was going on.

The work around:

```
                let stmts = vec![quote_stmt!(self.cx, $result_name = Some($expr);).unwrap(),
                                 quote_stmt!(self.cx, break $loop_label;).unwrap()];
                self.cx.expr_block(self.cx.block(stmts[0].span, stmts, None))
```

worked fine

### LINKED ISSUE #46849: Remove old quasi quoting APIs
We still have the `quote_foo!` macros. They aren't used anywhere within rustc, and they are used by cargo and clippy for testing syntax extension related things.

We can update cargo and clippy to use other APIs (and eventually move them to TokenStream).

https://github.com/rust-lang/cargo/pull/4838 is the cargo PR; will make a clippy one shortly.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This deletes a considerable amount of test cases, some of which we may want to keep. I'm not entirely certain what the primary intent of many of them was; if we should keep them I can attempt to edit each case to continue compiling without the quote_*! macros involved.

Fixes #46849.
Fixes #12265.
Fixes #12266.
Fixes #26994.

r? @Manishearth

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
Looks good.

**Comment by eddyb** [comment]
LGTM. cc @alexcrichton Do we want to move any of these tests to `proc_macro`?

**Comment by sfackler** [comment]
It's not quite true that clippy was the only consumer of these - rust-phf uses them as well, for example: https://github.com/sfackler/rust-phf/blob/master/phf_macros/src/util.rs. It does still seem reasonable to move the ecosystem towards the newer APIs though.

I think this is probably a libs thing vs a lang thing, so I'll start an FCP there, but if lang folks want to jump in that works as well!

@rfcbot fcp merge

**Comment by eddyb** [comment]
@sfackler It seems `phf_macro` uses `plugin_registrar` - that will likely get removed sooner or later, so moving to the `proc_macro` approach in both interface and implementation is advisable.

**Comment by Mark-Simulacrum** [comment]
I'll rebase when/if this is approved.

**Comment by Mark-Simulacrum** [comment]
@eddyb Do we want to wait for @alexcrichton's approval here?

**Comment by petrochenkov** [comment]
>Do we want to move any of these tests to `proc_macro`?

I wanted to suggest to migrate the tests to `quote!` initially, but they seem to be so specific to legacy plugins that it doesn't worth the effort.

**Comment by SergioBenitez** [comment]
Rocket is a heavy consumer of the `quote_` macros. Removing these uses in Rocket is non-trivial. Can merging this be postponed while I investigate removing their use in Rocket?

**Comment by Mark-Simulacrum** [comment]
This is waiting for @alexcrichton to return and I plan to do a PSA of sorts before we merge -- I don't see it as urgent, so I have no real problems with waiting.

**Comment by Manishearth** [comment]
Can you use the quote crate instead?

Yeah, we can wait on this. The way forward here is to use the quote crate with proc_macro, since the old proc macro API is unsupported.

**Comment by SergioBenitez** [comment]
@Manishearth Not directly, no, since Rocket's codegen is still a syntax extension. We'll be attempting to migrate to proc-macros soon, however. I think we can stop using the `quote_` macros before that, however.

**Comment by alexcrichton** [comment]
I'm personally ok removing all this support, it's definietly supplanted by proc_macro. Seems ok to wait for Rocket to migrate as well!

**Comment by jebrosen** [comment]
@llogiq - in reading [your recent blog post](https://llogiq.github.io/2018/06/28/self-bug.html) I noticed that mutagen also uses the quote_*! macros.

Would it be worth a crater run to find other crates that will be affected by this change? A PSA is a good idea, but it would need to be very visible.

**Comment by Mark-Simulacrum** [comment]
I haven't gotten around to doing a PSA yet -- loosely though I believe there's around ~50 crates out there (that crater knows about) with `#![feature(quote)]` in their source, so while this is going to be a painful thing to land I think it's limited enough in scope that with a PSA and probably issues filed on each of those repositories/crates we'll be good to go here (if only in the long-term).

**Comment by Manishearth** [comment]
Bear in mind, this is in the old unstable proc macro API, which regularly experiences breakages _anyway_ . We should worry about large consumers like rocket, but aside from that I don't think it's a big deal.

**Comment by llogiq** [comment]
@jebrosen thanks for the heads up. I think I'll have to look into converting mutagen to use the quote crate.

**Comment by pietroalbini** [comment]
Should we do a crater run for this then? We have spare capacity for one.

**Comment by Mark-Simulacrum** [comment]
Might as well, yes -- I don't know that it'll be *too* interesting but seems like a good idea.

**Comment by petrochenkov** [comment]
>We have spare capacity for one.

I'll need one crater run for testing [local `$crate::exported_macro`](https://github.com/rust-lang/rust/pull/50911#issuecomment-401151270) today/tomorrow.
I'd prefer to spend the crater slot on that, because instances of `quote_*!` is can be found with simple text search (or you can start crater on this and then abort if it becomes necessary).

**Comment by pietroalbini** [comment]
> I'd prefer to spend the crater slot on that, because instances of quote_*! is can be found with simple text search (or you can start crater on this and then abort if it becomes necessary).

That's not really a problem, Crater is way faster with the new code we merged in the last few days, and a check-only run should now take only one day.

By the way, let's test something new with this PR, shall we?

@craterbot run start=master#c6807bb1b282e0c5398aa4e659dbc165b6f3c81b end=try#dd230fd2f576521932ccc43dffb4b637c450458f mode=check-only

**Comment by Mark-Simulacrum** [comment]
Root regressions are below.

Crater found these root regressions (a grep for `feature.*\bquote\b` in crater's crates direcotry finds many more crates, but it looks like at least some just don't build in crater); this is a good initial set for authors to fix and publish new versions of.
 - [pear_codegen-0.0.18](https://crates.io/crates/pear_codegen/0.0.18): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/pear_codegen-0.0.18/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/pear_codegen-0.0.18/log.txt), cc @SergioBenitez 
 - [phf_macros-0.7.22](https://crates.io/crates/phf_macros/0.7.22): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/phf_macros-0.7.22/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/phf_macros-0.7.22/log.txt), cc @sfackler 
 - [unicode_names2_macros-0.2.0](https://crates.io/crates/unicode_names2_macros/0.2.0): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/unicode_names2_macros-0.2.0/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/unicode_names2_macros-0.2.0/log.txt) (3 dependent crates); cc @ProgVal
 - [tarpc-plugins-0.3.0](https://crates.io/crates/tarpc-plugins/0.3.0): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/tarpc-plugins-0.3.0/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/tarpc-plugins-0.3.0/log.txt) (2 dependent crates); cc @tikue
 - [flamer-0.2.3](https://crates.io/crates/flamer/0.2.3): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/flamer-0.2.3/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/flamer-0.2.3/log.txt) (2 dependent crates); cc @llogiq
 - [speculate-0.0.26](https://crates.io/crates/speculate/0.0.26): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/speculate-0.0.26/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/speculate-0.0.26/log.txt) (1 dependent crates); cc @utkarshkukreti
 - [peg-syntax-ext-0.5.5](https://crates.io/crates/peg-syntax-ext/0.5.5): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/peg-syntax-ext-0.5.5/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/peg-syntax-ext-0.5.5/log.txt) (1 dependent crates); cc @kevinmehall
 - [overflower-0.4.3](https://crates.io/crates/overflower/0.4.3): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/overflower-0.4.3/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/overflower-0.4.3/log.txt) (1 dependent crates); cc @llogiq
 - [jmespath-macros-0.1.1](https://crates.io/crates/jmespath-macros/0.1.1): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/jmespath-macros-0.1.1/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/jmespath-macros-0.1.1/log.txt) (1 dependent crates); cc @mtdowling
 - [embed-0.1.1](https://crates.io/crates/embed/0.1.1): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/embed-0.1.1/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/embed-0.1.1/log.txt) (1 dependent crates); cc @mantasmatelis
 - [clucstr-0.1.3](https://crates.io/crates/clucstr/0.1.3): [a log](https://crater-reports.s3.amazonaws.com/pr-51285/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b-alt/reg/cluuname-0.1.5/log.txt) vs. [b log](https://crater-reports.s3.amazonaws.com/pr-51285/dd230fd2f576521932ccc43dffb4b637c450458f-alt/reg/cluuname-0.1.5/log.txt) (1 dependent crates); cc @denisandroid

**Comment by ProgVal** [comment]
Fixed in my crate (unicode_names2_macros), which actually didn't use that feature anymore.

**Comment by tikue** [comment]
@eddyb 

> @sfackler It seems phf_macro uses plugin_registrar - that will likely get removed sooner or later, so moving to the proc_macro approach in both interface and implementation is advisable.

FWIW I've tried multiple times to move tarpc to proc_macro, but it hasn't worked because proc macros can't be reexported from other crates unless they're `#[derive]` macros.

**Comment by eddyb** [comment]
@tikue That sounds like a bug to me. cc @alexcrichton @dtolnay

**Comment by alexcrichton** [comment]
@tikue oh dear, sounds bad! Can you elaborate a bit what you're trying to do? With `use_extern_macros` enabled you should be able to reexport everything as necessary

**Comment by tikue** [comment]
I filed #44817 when I initially tried to switch over.

**Comment by llogiq** [comment]
I just removed the `quote_block!` call from flamer 0.2.4. Next up: Overflower.

**Comment by TimNN** [comment]
Ping from triage @Manishearth / @Mark-Simulacrum: It looks like the FCP has completed, although there seem to be some concerns. Is this PR blocked on something? What is the status of this PR?

**Comment by Manishearth** [comment]
I think we can land this


@djrenren wanted to use these APIs for the custom test framework work though (it's more convenient over AstBuilder. However, I'm not sure if it's worth maintaining these to support a single feature, especially given how buggy these are.

**Comment by Mark-Simulacrum** [comment]
I believe we're primarily waiting on Rocket and maybe some other crates to migrate? I'd not want to land this if we believe a significant portion of the ecosystem is using it -- seems like not much win for lots of pain.

**Comment by djrenren** [comment]
Yeah, I rewrote it without them. We're good.

**Comment by TimNN** [comment]
Ping from triage, @Mark-Simulacrum. It looks like your PR is generally ready to land but needs to be rebased.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this for now -- I don't think Rocket and other crates have migrated yet and I'm not ready to try and push this through by opening PRs for them at this point. I think we'll wait a few more months and hopefully by then there will have been more progress.

**Comment by SergioBenitez** [comment]
An update on Rocket's status: the next release, `v0.4`, will no longer use any `quote_` macros! The final changes are being polished now. I expect to ship the next release within a week's time.

**Comment by TimNN** [comment]
Ping from triage @Mark-Simulacrum. What is the status of this PR?

**Comment by Mark-Simulacrum** [comment]
We're waiting on the rocket release and will then re-run crater.

**Comment by steveklabnik** [comment]
This would also fix https://github.com/rust-lang/rust/issues/26994

I believe rocket hasn't had a release yet.

**Comment by Centril** [comment]
Ping from triage... @Mark-Simulacrum @SergioBenitez any updates wrt. rocket / this PR?

**Comment by petrochenkov** [comment]
The new planned Rocket 0.4 release date is [December 5th](https://rocket.rs/v0.4/news/2018-11-30-version-0.4-rc-2/).
Not sure how reliable the date is given the history of previous planned Rocket 0.4 release dates, but seems like there's still chance this will be unblocked until the end of the year.

**Comment by Mark-Simulacrum** [comment]
I'll take a look soon at rebasing this, and will probably schedule another crater run at that point as well.

**Comment by Mark-Simulacrum** [comment]
@craterbot run start=master#0a7798079608b4ff014471ae64b6c8201aa59cdf end=try#51fed1065d4f23779902876ba8c37ed02399dde7 mode=check-only

**Comment by nagisa** [comment]
Rocket v0.4 has been released so merge away.

**Comment by Centril** [comment]
# Regression tree

## Possibly spurious
- loggr-0.3.0 

## Actual:

- pear_codegen:
  - basic-auth-raw-0.1.0
  - diesel_errors-0.1.3
  - hadron-0.1.0
  - limiting-factor-0.5.1
  - line-messaging-api-rocket-0.1.1
  - rocket-lenient-json-0.3.1
  - rocket-file-cache-1.0.0-beta
  - rocket-etagged-file-response-0.5.0
  - rocket_igniter-0.0.2
  - rocket-simpleauth-0.4.0
- phf_macros-0.7.23:
  - css-0.0.22
  - css-autoprefix-0.0.5
  - css-purify-0.0.15
  - fix-rs-0.2.1
  - html5ever_ext-0.21.20
  - human_name-0.7.0
  - json-api-rocket-0.4.1
  - oil_shared-0.1.0
  - punkt-1.0.4
  - orf-0.1.0
  - openrtb-0.1.0
  - vstepchik/mold-web
  - Lythenas/rust-orgmode
  - tld-1.17.0
  - static_map_macros-0.2.0-beta
- cluuname-0.1.8
- google/rerast

**Comment by eddyb** [comment]
I think `pear_codegen` is part of Rocket, so those projects should update.

As for `phf_macros`, I guess that still needs to be ported over to proc macros.

@sfackler do you want this PR to wait on `phf_macros`?

**Comment by sfackler** [comment]
I'll work on getting phf updated this week. We should be able to jump over to stable with item macros.

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-phf/commit/03187fd85e85712b51c8113f73e28e6b98f7f8f9

**Comment by sfackler** [comment]
Master has a bunch of breaking changes on it - I'll be cutting a release off of the 0.7.x branch tomorrow.

**Comment by Mark-Simulacrum** [comment]
@bors treeclose=1000 

I believe CI is currently failing due to android

**Comment by pietroalbini** [comment]
@bors retry

Android is broken.

**Comment by Centril** [comment]
@bors p=11

Rollup fairness.

**Pull request merged**
