### PR TITLE
Add tests for issues with the E-needstest label

### LINKED ISSUE #19181: rustdoc panics if target crate has compilation errors
# Updated issue
### STR

``` rust
// err.rs
fn main() { 0 }
```
### Output

```
$ rustc err.rs 2>/dev/null || echo compilation error as expected
compilation error as expected
$ rustdoc err.rs
err.rs:2:5: 2:6 error: mismatched types: expected `()`, found `_` (expected (), found integral variable)
err.rs:2     0
             ^
error: aborting due to previous error
task '<unnamed>' panicked at 'Box<Any>', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libsyntax/diagnostic.rs:142
task '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: rustc failed', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libcore/result.rs:743
```

---
# Original issue: rustdoc panics with `#![deny(missing_docs]` and associated items
### STR

``` rust
#![deny(missing_docs)]
#![feature(associated_types)]

//! Crate

/// Trait
pub trait AsSlice {
    /// Item
    type Item;

    // Forgot to document the method
    fn as_slice(&self) -> &[<Self as AsSlice>::Item];
}
```
### Output

``` rust
ai.rs:12:5: 12:53 error: missing documentation for a type method
ai.rs:12     fn as_slice(&self) -> &[<Self as AsSlice>::Item];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ai.rs:1:9: 1:21 note: lint level defined here
ai.rs:1 #![deny(missing_docs)]
                ^~~~~~~~~~~~
error: aborting due to previous error
task '<unnamed>' panicked at 'Box<Any>', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libsyntax/diagnostic.rs:142
task '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: rustc failed', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libcore/result.rs:743
```
### Version
#19174 on top of c9f6d69

cc @tomjakubowski

### LINKED ISSUE #29516: ICE: Conflicting trait impls with custom default-implemented trait bound
This stems from my attempt to extend the `NotSame` trait for type inequality as described in #29499 to tuples of arbitrary size. The implementation for (A, B) conflicts with the implementation for A because the (A) tuple lacks a trailing comma.

``` rust
#![feature(optin_builtin_traits)]

trait NotSame {}
impl NotSame for .. {}
impl<A> !NotSame for (A, A) {}

trait OneOfEach {}

impl <A> OneOfEach for (A) { }

impl <A, B> OneOfEach for (A, B) where (B): OneOfEach, (A, B): NotSame { }

// ...

fn main() {}
```

```
robert@laptop:~/projects/one_of_each$ RUST_BACKTRACE=1 rustc one_of_each.rs
one_of_each.rs:11:1: 11:75 error: internal compiler error: coherence failed to report ambiguity: cannot locate the impl of the trait `OneOfEach` for the type `(A, B)`
one_of_each.rs:11 impl <A, B> OneOfEach for (A, B) where (B): OneOfEach, (A, B): NotSame { }
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/diagnostic.rs:176
stack backtrace:
   1:     0x7f8e6d26fd20 - sys::backtrace::tracing::imp::write::h5839347184a363c1Tnt
   2:     0x7f8e6d2765e5 - panicking::log_panic::_<closure>::closure.39955
   3:     0x7f8e6d276055 - panicking::log_panic::hcde6d42710304abbWnx
   4:     0x7f8e6d239683 - sys_common::unwind::begin_unwind_inner::h4039843fef6bffefYgs
   5:     0x7f8e670c63c7 - sys_common::unwind::begin_unwind::begin_unwind::h17811388397816602357
   6:     0x7f8e670c6386 - diagnostic::_<impl>::span_bug::h517cd016f9a1ed4fqGA
   7:     0x7f8e6b04f4a0 - middle::traits::error_reporting::report_fulfillment_errors::h7b40fdbf7b69efa1DqR
   8:     0x7f8e6bdf69b5 - check::_<impl>::select_all_obligations_or_error::h68d2b62f895fda24Nar
   9:     0x7f8e6be4d9a4 - check::wf::_<impl>::check_item_well_formed::h294fa0c9be11cb26O4j
  10:     0x7f8e6be8bfbe - check::check_wf_old::h2896130387effa64m9o
  11:     0x7f8e6bf3b8ab - check_crate::hbd4bd8f4f3340ed1BrD
  12:     0x7f8e6d7438b9 - driver::phase_3_run_analysis_passes::_<closure>::closure.21990
  13:     0x7f8e6d729213 - middle::ty::context::_<impl>::create_and_enter::create_and_enter::h7648551165536465273
  14:     0x7f8e6d72420e - driver::phase_3_run_analysis_passes::h13807885485637783892
  15:     0x7f8e6d704c92 - driver::compile_input::he5c7814d86abe8678ba
  16:     0x7f8e6d85badb - run_compiler::h3e946a4e9bc089bfvqc
  17:     0x7f8e6d858b56 - sys_common::unwind::try::try_fn::try_fn::h18225326314371046170
  18:     0x7f8e6d26da48 - __rust_try
  19:     0x7f8e6d261abb - sys_common::unwind::try::inner_try::h81e998e565f2181dwds
  20:     0x7f8e6d858ea4 - boxed::_<impl>::call_box::call_box::h16507595822000360715
  21:     0x7f8e6d2750b3 - sys::thread::_<impl>::new::thread_start::h0be42f811434f5398Fw
  22:     0x7f8e6691c181 - start_thread
  23:     0x7f8e6ceef47c - __clone
  24:                0x0 - <unknown>

```

On rustc 1.6.0-nightly (1a2eaffb6 2015-10-31)

### LINKED ISSUE #29798: index is not an integer constant expression when using const fn argument
``` rust
#![feature(const_fn)]
const fn test(x: usize) -> i32 {
    [42;5][x]
}
fn main () {
    let _ = test(5);
}
```

<del>I guess we cannot const evaluate the index anymore but must translate it with llvm's constant evaluator, because it might only be available as a value we got from a static. But then I'm not sure how to do the range check.</del>

Nope, that's not a problem. Is there any reason not to thin out trans/consts down to the point where it's just a thin wrapper around const_eval + translation of `ConstVal` to `ValueRef`?

I mean after #25570 (const indexing), since after that I think the const_eval is feature-equivalent with the const translator.

### LINKED ISSUE #33504: ICE: Shadowing a unit-like enum in a closure crashes compiler
Shadowing a unit-like enum in a closure crashes compiler.

I tried this code:

```
struct Test;

fn main() {
    || {
        let Test = 1;
    };
}
```

I expected to see this happen: Failure message E0413

Instead, this happened: Compiler crash

```
driver.rs:5:13: 5:17 error: declaration of `Test` shadows an enum variant or unit-like struct in scope [E0413]
driver.rs:5         let Test = 1;
                        ^~~~
driver.rs:5:13: 5:17 help: run `rustc --explain E0413` to see a detailed explanation
error: internal compiler error: ../src/librustc/middle/mem_categorization.rs:614: Def::Err in memory categorization
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
## Meta

`rustc --version --verbose`:

```
rustc 1.10.0-nightly (62e2b2fb7 2016-05-06)
binary: rustc
commit-hash: 62e2b2fb7acf5f8331781cd7128c754ed1b66c4f
commit-date: 2016-05-06
host: x86_64-unknown-linux-gnu
release: 1.10.0-nightly
```

Backtrace:

```
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:576
stack backtrace:
   1:     0x7f95e967bd10 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x7f95e968958b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x7f95e968912c - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x7f95e964e8cf - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x7f95e4ca6717 - std::sys_common::unwind::begin_unwind::h24c4c0fa2cfe995a
   6:     0x7f95e4ca607e - syntax::errors::Handler::bug::h4846e60601033e50
   7:     0x7f95e5d2fab2 - rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::hf0fb5697f8f25f40
   8:     0x7f95e5d2f942 - rustc::session::opt_span_bug_fmt::hc581ba88c4e2ec53
   9:     0x7f95e5d47826 - rustc::session::bug_fmt::had96c08cb43bd8a1
  10:     0x7f95e5ebecb0 - rustc::middle::mem_categorization::MemCategorizationContext::cat_def::h1e6d1d71a3ac3d06
  11:     0x7f95e5ebcce9 - rustc::middle::mem_categorization::MemCategorizationContext::cat_pattern_::h688ac5141fed7601
  12:     0x7f95e5eba413 - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_pat::h95254f9d39fba4a1
  13:     0x7f95e5eb5cf3 - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_irrefutable_pat::h7304094e79d13564
  14:     0x7f95e5eb8d46 - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_stmt::h8bc9b54fe3fcb6f0
  15:     0x7f95e5eb7f0e - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr::h9cca31560139037e
  16:     0x7f95e5eb5e84 - rustc::middle::expr_use_visitor::ExprUseVisitor::consume_expr::ha16e99aa14e61262
  17:     0x7f95e5eb5b65 - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_fn::h5a4a2ab4ebcdb73a
  18:     0x7f95e6cb635d - _<check..upvar..AdjustBorrowKind<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_fn::hba13755c61d6d401
  19:     0x7f95e6cb5e48 - rustc::hir::intravisit::walk_expr::h4743b97a2ee4072c
  20:     0x7f95e6c14a5a - rustc_typeck::check::check_bare_fn::h7e4c2ad58d1814dd
  21:     0x7f95e6c12196 - rustc_typeck::check::check_item_body::h7ffec660fc242796
  22:     0x7f95e6c0a011 - rustc_typeck::check::check_item_bodies::ha729008a2e67410e
  23:     0x7f95e6c02012 - rustc_typeck::check_crate::hb08ba31a6a5f65b5
  24:     0x7f95e9bd0860 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::hfdd8d88ff571b474
  25:     0x7f95e9bce8be - rustc::ty::context::TyCtxt::create_and_enter::ha551c2427049829f
  26:     0x7f95e9b9a285 - rustc_driver::driver::compile_input::h0629572e6f316b31
  27:     0x7f95e9b8a4fd - rustc_driver::run_compiler::h8902aebf8b1849a8
  28:     0x7f95e9b877bd - std::sys_common::unwind::try::try_fn::h4c74456035d0fcc7
  29:     0x7f95e96794eb - __rust_try
  30:     0x7f95e967947d - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  31:     0x7f95e9b881ea - _<F as std..boxed..FnBox<A>>::call_box::h27f542a39f1d61ef
  32:     0x7f95e96876f4 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  33:     0x7f95e1424473 - start_thread
  34:     0x7f95e92e5acc - clone
  35:                0x0 - <unknown>

```

### LINKED ISSUE #34780: ICE: Encountered early bound region when generalizing: ReEarlyBound(TypeSpace, 0, 'a)
Code:

``` rust
#![feature(associated_consts)]

use std::marker::PhantomData;

trait Tr<'a> {
    const C: PhantomData<&'a u8> = PhantomData::<&'a u8>;
}

fn main() {}
```

ICEs on nightly (1.12), can't be reproduced on stable/beta due to `#![feature(associated_consts)]`

Backtrace:

```
#0  0x000000006e55e767 in rust_panic () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#1  0x000000006e544e3c in std::panicking::rust_panic_with_hook::h9a3925e37821d434 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#2  0x0000000002a05b8c in std::panicking::begin_panic::hdf32e6f0d48da313 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#3  0x0000000002a059c8 in rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::hfbd05ef01f930389 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#4  0x0000000002a05798 in rustc::session::opt_span_bug_fmt::he49e515088fa8437 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#5  0x0000000002a05555 in rustc::session::span_bug_fmt::h40548a94744de842 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#6  0x0000000002b1d29e in _$LT$rustc..infer..combine..Generalizer$LT$$u27$cx$C$$u20$$u27$gcx$C$$u20$$u27$tcx$GT$$u20$as$u20$rustc..ty..fold..TypeFolder$LT$$u27$gcx$C$$u20$$u27$tcx$GT$$GT$::fold_ty::hf2fab54cf2614ed1 ()
   from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#7  0x0000000002b15a36 in rustc::infer::combine::CombineFields::instantiate::hffd1f98ca5ab6d3b () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#8  0x0000000002af0be1 in _$LT$rustc..infer..equate..Equate$LT$$u27$a$C$$u20$$u27$gcx$C$$u20$$u27$tcx$GT$$u20$as$u20$rustc..ty..relate..TypeRelation$LT$$u27$a$C$$u20$$u27$gcx$C$$u20$$u27$tcx$GT$$GT$::tys::he042e4faca40a521 ()
   from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#9  0x0000000002af4645 in rustc::ty::relate::relate_type_params::_$u7b$$u7b$closure$u7d$$u7d$::h27ac1d6284ceaedc () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#10 0x0000000002af435a in _$LT$collections..vec..Vec$LT$T$GT$$u20$as$u20$core..iter..traits..FromIterator$LT$T$GT$$GT$::from_iter::hd947b801a25609d2 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#11 0x0000000002af36bf in rustc::ty::relate::relate_substs::ha20cc22e09ccff78 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#12 0x0000000002af1e2b in rustc::ty::relate::relate_item_substs::hf669fec513c5c374 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#13 0x0000000002b1ebfe in rustc::ty::relate::super_relate_tys::h698b991f588f8d3b () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#14 0x0000000002af0d89 in _$LT$rustc..infer..equate..Equate$LT$$u27$a$C$$u20$$u27$gcx$C$$u20$$u27$tcx$GT$$u20$as$u20$rustc..ty..relate..TypeRelation$LT$$u27$a$C$$u20$$u27$gcx$C$$u20$$u27$tcx$GT$$GT$::tys::he042e4faca40a521 ()
   from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#15 0x0000000002af4645 in rustc::ty::relate::relate_type_params::_$u7b$$u7b$closure$u7d$$u7d$::h27ac1d6284ceaedc () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#16 0x0000000002af435a in _$LT$collections..vec..Vec$LT$T$GT$$u20$as$u20$core..iter..traits..FromIterator$LT$T$GT$$GT$::from_iter::hd947b801a25609d2 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#17 0x0000000002af36bf in rustc::ty::relate::relate_substs::ha20cc22e09ccff78 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#18 0x0000000002af1e2b in rustc::ty::relate::relate_item_substs::hf669fec513c5c374 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#19 0x0000000002af1c72 in _$LT$rustc..ty..sty..TraitRef$LT$$u27$tcx$GT$$u20$as$u20$rustc..ty..relate..Relate$LT$$u27$tcx$GT$$GT$::relate::h986b72a0959563fb () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#20 0x0000000002af1484 in rustc::infer::InferCtxt::eq_trait_refs::h1a047bc0d7cb9287 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#21 0x0000000002cad67b in rustc::traits::select::SelectionContext::match_impl::hc59fa4b835fb8273 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#22 0x0000000002cacec9 in rustc::traits::select::SelectionContext::assemble_candidates_from_impls::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h477fb8af4d02a8d4 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#23 0x0000000002cace18 in rustc::traits::select::SelectionContext::probe::h9e68b3f3a4f27c3c () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#24 0x0000000002cacbf8 in rustc::ty::trait_def::TraitDef::for_each_relevant_impl::h48255f01a2713db2 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#25 0x0000000002ca7b6e in rustc::traits::select::SelectionContext::assemble_candidates::h5d6c8f4149f33306 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#26 0x0000000002c9b2b4 in rustc::traits::select::SelectionContext::candidate_from_obligation::h57e2e1988c8b0c1d () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#27 0x0000000002ca5efd in rustc::traits::select::SelectionContext::evaluate_stack::h41d9a289217f5274 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#28 0x0000000002ca53e8 in rustc::traits::select::SelectionContext::evaluate_predicate_recursively::hd3a46054b61ed569 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#29 0x0000000002c4e821 in rustc::traits::select::SelectionContext::evaluate_obligation_conservatively::h6ab08bc990db370f () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#30 0x0000000002b1113f in rustc::traits::type_known_to_meet_builtin_bound::haf67b98536009464 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#31 0x0000000002d0c751 in rustc::ty::util::_$LT$impl$u20$rustc..ty..TyS$LT$$u27$tcx$GT$$GT$::impls_bound::h07a139f8ccd4fd61 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#32 0x0000000002b10e4f in rustc::ty::util::_$LT$impl$u20$rustc..ty..TyS$LT$$u27$tcx$GT$$GT$::moves_by_default::h25b140bd780bb824 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#33 0x0000000002b10d96 in rustc::infer::InferCtxt::type_moves_by_default::hfe88106eb6250ac6 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#34 0x0000000002b9f9e5 in rustc::middle::expr_use_visitor::ExprUseVisitor::consume_expr::h4b2d785ca70f00ad () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#35 0x00000000673c8d6b in rustc_passes::consts::CheckCrateVisitor::global_expr::h47f4b325bf42d285 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_passes-f53fb285.dll
#36 0x00000000673d2976 in _$LT$rustc_passes..consts..CheckCrateVisitor$LT$$u27$a$C$$u20$$u27$tcx$GT$$u20$as$u20$rustc..hir..intravisit..Visitor$LT$$u27$v$GT$$GT$::visit_item::h0528b8b3ad96685d ()
   from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_passes-f53fb285.dll
#37 0x00000000673d4bff in rustc_passes::consts::check_crate::h17411c6a9c58041d () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_passes-f53fb285.dll
#38 0x000000006ac97fdd in rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::he1de538a7584312e () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#39 0x000000006ac95d7e in rustc::ty::context::TyCtxt::create_and_enter::he5466411552b055e () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#40 0x000000006ac5a76c in rustc_driver::driver::compile_input::h2d1b58b831f06a86 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#41 0x000000006ac4695d in rustc_driver::run_compiler::h833483649bdaa9c3 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#42 0x000000006ac438ca in std::panicking::try::call::hd16aacc09eeeaf9e () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#43 0x000000006e58f849 in __rust_maybe_catch_panic () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#44 0x000000006ac443c4 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hbf614b3f826456b6 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#45 0x000000006e57d4da in std::sys::thread::Thread::new::thread_start::h150ac04d84605902 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#46 0x00007ffce27813d2 in KERNEL32!BaseThreadInitThunk () from /c/Windows/system32/KERNEL32.DLL
#47 0x00007ffce39554e4 in ntdll!RtlUserThreadStart () from /c/Windows/SYSTEM32/ntdll.dll
#48 0x0000000000000000 in ?? ()
```

### LINKED ISSUE #39211: `cannot use an outer type parameter in this context`
I get the error:

    error[E0402]: cannot use an outer type parameter in this context
      --> <anon>:11:17
       |
    11 |     let a = [3; M::Row::DIM];
       |                 ^^^^^^^^^^^

    error: internal compiler error: unexpected panic

    note: the compiler unexpectedly panicked. this is a bug.

https://gist.github.com/73a223aa33c081bf47d84c2bf52fcc19

### LINKED ISSUE #39467: ICE: associated constants and macros
https://play.rust-lang.org/?gist=19881877a8b06d7014c9af2ab2a5a39f&version=nightly&backtrace=1

```
macro_rules! expr { () => { () } }

enum A {}

impl A {
    const A: () = expr!();
}
```

```
rustc 1.16.0-nightly (df8debf6d 2017-01-25)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'adding a def'n for node-id NodeId(2) and data Initializer but a previous def'n exists: DefKey { parent: Some(DefIndex(0)), disambiguated_data: DisambiguatedDefPathData { data: Misc, disambiguator: 0 } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/definitions.rs:335
stack backtrace:
   1:     0x7f347fd6096c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f347fd6ee6e - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f347fd6ea13 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7f347fd6f30b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f347fd6f1a4 - std::panicking::begin_panic::hc4c5d184a1e3fb7c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f347fd6f0c9 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7f347cd9e73d - rustc::hir::map::definitions::Definitions::create_def_with_parent::hade3673fccb27c33
   8:     0x7f347cd9b58e - <rustc::hir::map::def_collector::DefCollector<'a> as syntax::visit::Visitor<'a>>::visit_impl_item::h7b3200d9cd164dd0
   9:     0x7f347cd28fa1 - syntax::visit::walk_item::h69fd055462a67732
  10:     0x7f347cd9b001 - <rustc::hir::map::def_collector::DefCollector<'a> as syntax::visit::Visitor<'a>>::visit_item::{{closure}}::h9091e118e4816ffb
  11:     0x7f347cd9a99a - <rustc::hir::map::def_collector::DefCollector<'a> as syntax::visit::Visitor<'a>>::visit_item::h245a68a66023f85b
  12:     0x7f347cd28d7f - syntax::visit::walk_item::h69fd055462a67732
  13:     0x7f347cd9aa0a - <rustc::hir::map::def_collector::DefCollector<'a> as syntax::visit::Visitor<'a>>::visit_item::h245a68a66023f85b
  14:     0x7f347d24e12e - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::hf2f69d86db69f9ff
  15:     0x7f34789ee992 - syntax::ext::expand::MacroExpander::collect_invocations::hb7286b5215f6cabe
  16:     0x7f34789ec5d7 - syntax::ext::expand::MacroExpander::expand::he64090ad698e4ac4
  17:     0x7f34789ec095 - syntax::ext::expand::MacroExpander::expand_crate::h9effb4e2a488a85d
  18:     0x7f34801001ec - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::h3ddcf02b571a1c51
  19:     0x7f34800f7905 - rustc_driver::driver::phase_2_configure_and_expand::hd0c4535cf8df7dea
  20:     0x7f34800eddee - rustc_driver::driver::compile_input::h44853ffed84a12cb
  21:     0x7f3480137554 - rustc_driver::run_compiler::hdc4bb0fcf7d0917a
  22:     0x7f3480043c2b - std::panicking::try::do_call::h84a15e0d2b943318
  23:     0x7f347fd7814a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  24:     0x7f348006be62 - <F as alloc::boxed::FnBox<A>>::call_box::h61c78220cad685ea
  25:     0x7f347fd6dcc4 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  26:     0x7f3477b256b9 - start_thread
  27:     0x7f347fa2382c - clone
  28:                0x0 - <unknown>
```

### LINKED ISSUE #39720: ICE with simd_cast
When casting from i8x3 -> i16x3 there's an ICE on `rustc 1.17.0-nightly (24a70eb59 2017-02-09)`

```
PromoteIntegerResult #0: t35: v4i16 = sign_extend_vector_inreg t34

Do not know how to promote this operator!
UNREACHABLE executed at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp:51!
```

Test case: https://gist.github.com/rawrasaur/27a3e624e5a6e071bc4e9059795fd97b

It seems to trigger when the width is 3, the source is _not_ a float, and in size is smaller than the out size. Clang handles this case fine in its __builtin_convertvector.

### PR DESCRIPTION
**Pull request by topecongiro**
Fixes #19181.
Fixes #29516.
Fixes #29798.
Fixes #33504.
Fixes #34780.
Fixes #39211.
Fixes #39467.
Fixes #39720.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Could you add `Fixes #xxx` for each issue you've fixed by adding a test for it to the description? That way GitHub will automatically close them.

**Comment by topecongiro** [comment]
@Mark-Simulacrum Thanks, updated the description.

**Comment by RalfJung** [comment]
This adds a test checking that
```
trait VecN {
    const DIM: usize;
}
trait Mat {
    type Row: VecN;
}

fn m<M: Mat>() {
    let a = [3; M::Row::DIM]; //~ ERROR associated type `Row` not found for `M`
}
fn main() {
}
```
It seems that this used to ICE, and the test makes sure that doesn't happen. Okay. However, the error message doesn't make any sense, so I am somewhat surprised that it should be "enforced" by a test.

**Comment by Mark-Simulacrum** [comment]
Once https://github.com/rust-lang/rust/issues/34344 is fixed, I'd imagine we'd remove that test. I think it's better to have it and avoid regressing on the ICE. Tests in general to me don't imply cemented behavior, just current behavior -- if you're fixing something and it fixes a test, consider removing the test; it's just somewhat unusual that we have tests like this.

**Pull request merged**
