### PR TITLE
add solaris sparcv9 support

### LINKED ISSUE #39901: add solaris sparcv9 support
Hi, at this point, rust nightly pretty much builds out of the box (assuming you have an already built beta rustc compiler) on Solaris for x86_64.

However, it doesn't (yet) build for sparcv9.  I will provide a pull request shortly that adds the final, missing piece to support sparcv9 / Solaris.

### PR DESCRIPTION
**Pull request by binarycrusader**
Fixes #39901

### CODE REVIEW

**Comment by binarycrusader** [comment]
Please note that this pull request depends upon another pull request https://github.com/rust-lang/rust/pull/39871 to actually function as expected.

**Comment by binarycrusader** [comment]
Note that there is little point in ever using -fomit-frame-pointer on sparc since the sparc ABI requires a minimum of 176 bytes of stack frame, which means space is always reserved for %fp regardless of whether it's used.  Also, most debuggers and other tools on any platform for sparc generally expect %fp to be valid.

**Comment by alexcrichton** [comment]
Looks good to me, thanks! Out of curiosity, would `sparc64-sun-solaris` be "wrong", or is `sparcv9` just conventional?

**Comment by binarycrusader** [comment]
SPARC v9 (as in version 9) is the official name of the 64-bit architecture and is what is always used on Solaris and in SPARC architecture documentation.  The ELF ABI documentation also refers to it as sparcv9. The C compilers also set __sparcv9 to be defined.  For reasons unknown to me, the BSDs have always used sparc64 instead.

So, at least on Solaris, it would be unexpected and surprising to refer to it as sparc64.

**Comment by binarycrusader** [comment]
GCC built on Solaris and LLVM built on Solaris also refer to it as sparcv9 for this reason.

**Comment by alexcrichton** [comment]
Ok, sounds good to me, thanks!

@bors: r+

I wonder though if we should rename the `target_arch = "sparc64"` cfg? If the official name is sparcv9 it may be best to use that name

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by binarycrusader** [comment]
As an FYI, the frame pointer bug on sparc turned out to be an old oversight in gcc; a [bug was filed](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79749) and the issue fixed for future gcc versions.  I'd still heavily discourage use of -fomit-frame-pointer on sparc for some of the reasons I previously mentioned.

**Pull request merged**
