### PR TITLE
rustc_codegen_llvm: use opaque LLVM structs for `extern type`.

### PR DESCRIPTION
**Pull request by eddyb**
Mostly an experiment, @RalfJung suggested it could be used to inform LLVM that for e.g.:
```rust
extern {
    type Foo;
    static BAR: Foo;
}
```
`BAR` does not have a known size, and therefore nothing can be assumed about the validity of accesses at arbitrary offsets.

### CODE REVIEW

**Comment by eddyb** [comment]
@Mark-Simulacrum Ohh, the coredump backtraces are nice!
I wish we could enable debuginfo-lines.
Anyway, are LLVM assertions disabled? It seems like something they'd catch.
(I'll try a build of this locally later)

**Comment by Mark-Simulacrum** [comment]
You could manually enable an ALT builder for llvm asserts, neither one that's run so far has them enabled.

**Comment by eddyb** [comment]
The LLVM assertion failure is:
> `rustc`: [`src/llvm-project/llvm/include/llvm/IR/Instructions.h:847`](https://github.com/rust-lang/llvm-project/blob/683d3522690b7a9d0163e7e7e6586f2b1364ed02/llvm/include/llvm/IR/Instructions.h#L847): `llvm::Type *llvm::checkGEPType(llvm::Type *)`: Assertion `Ty && "Invalid GetElementPtrInst indices for type!"` failed.

**Comment by Dylan-DPC** [comment]
ping from triage @eddyb closing this issue due to inactivity. Thanks.

**Comment by RalfJung** [comment]
I opened an issue so we don't forget about this: https://github.com/rust-lang/rust/issues/59095

**Pull request closed without merging**
