### PR TITLE
Convert a hard-warning about named static lifetimes into lint "unused_lifetimes"

### LINKED ISSUE #96956: "warning: unnecessary lifetime parameter" unsilenceable lint
Given the following code: 

```rust
pub fn thing<'a>(_s: &'a str) where 'a: 'static { }
```

The current output is:

```
warning: unnecessary lifetime parameter `'a`
 --> src/lib.rs:2:37
  |
2 | pub fn thing<'a>(_s: &'a str) where 'a: 'static { }
  |                                     ^^
  |
  = help: you can use the `'static` lifetime directly, in place of `'a`

warning: `playground` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 1.27s
```

Ideally the output should also say something like this:

```
  = note: `#[warn(needless_lifetimes)]` on by default
```

And of course then `#[allow(needless_lifetimes)]` ought to work.

### Versions affected

```
rustcargo@zealot:/volatile/rustcargo/Rustup/Game/server$ rustc -vV
rustc 1.62.0-nightly (ecd44958e 2022-05-10)
binary: rustc
commit-hash: ecd44958e0a21110d09862ee080d95a4ca6c52f8
commit-date: 2022-05-10
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
rustcargo@zealot:/volatile/rustcargo/Rustup/Game/server$ 
```

The example code is accepted without any complaint by stable and beta,  However, in both stable and beta, clippy has the same weird name-less complaint.  And saying `#![allow(clippy::needless_lifetimes)]` doesn't suppress the message.

I searched for "lifetime" in the clippy lints db.  Of those that came up, `needless_lifetimes` and `redundant_static_lifetimes` seemed like they might be it, but neither of those suppresses the lint on stable's clippy.

### PR DESCRIPTION
**Pull request by LittleFall**
Fixes https://github.com/rust-lang/rust/issues/96956.

Some changes are ported from https://github.com/rust-lang/rust/pull/98079, thanks to jeremydavis519.

r? @estebank @petrochenkov 

Any feedback is appreciated!

## Actions
- [x] resolve conflicts
- [x] fix build
- [x] address review comments in last pr
- [x] update tests

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors r-

Can you squash these into one commit? The presence of 17a7ccc92f25a342ccf305b3231d7b8f36e97eb3 is a bit disorienting to the commit history. Thanks!

**Comment by LittleFall** [comment]
> @bors r-
> 
> Can you squash these into one commit? The presence of [17a7ccc](https://github.com/rust-lang/rust/commit/17a7ccc92f25a342ccf305b3231d7b8f36e97eb3) is a bit disorienting to the commit history. Thanks!
> 
> For context, we don't allow merge commits in the history: https://github.com/rust-lang/rustc-dev-guide/blob/master/src/git.md#keeping-things-up-to-date

Got and done. I have cherry-picked actual commits and squashed them into single.

**Comment by compiler-errors** [comment]
Thank you, sorry for the inconvenience.

@bors r=estebank

**Pull request merged**
