### PR TITLE
Add .wrapping_offset() methods

### PR DESCRIPTION
**Pull request by bluss**
.wrapping_offset() exposes the arith_offset intrinsic in the core
module (as methods on raw pointers, next to offset). This is the
first step in making it possible to stabilize the interface later.

`arith_offset` is a useful tool for developing iterators for two
reasons:
1. `arith_offset` is used by the slice's iterator, the most important
   iterator in libcore, and it is natural that Rust users need the same
   power available to implement similar iterators.
2. It is a good way to implement raw pointer iterations with step
   greater than one.

The name seems to fit the style of methods like "wrapping_add".

### CODE REVIEW

**Comment by alexcrichton** [comment]
Sounds great to me!

@rfcbot fcp merge

**Comment by alexcrichton** [comment]
Ok! @bluss want to open a tracking issue for this and I'll r+?

**Comment by bluss** [comment]
Great! Tracking issue is #37570

**Pull request merged**
