### PR TITLE
More macro expansion optimizations

### PR DESCRIPTION
**Pull request by nnethercote**
A few nice wins for macro-heavy crates.

r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
Some `check full` results on a few crates. Those marked with `*` are in the rustc-perf suite.

Benchmark & Profile | Scenario | % Change | Significance Factor?
-- | -- | -- | --
quote-stress check | full | -7.44% | 37.19x
async-std-1.10.0 check | full | -7.06% | 35.30x
time-macros-0.2.3 check | full | -3.92% | 19.62x
yansi-0.5.0 check | full | -2.38% | 11.89x
inotify-0.10.0 check | full | 0.94% | 4.70x
*token-stream-stress check | full | 0.53% | 2.63x
scroll_derive-0.11.0 check | full | -0.51% | 2.56x
ctor-0.1.21 check | full | -0.51% | 2.56x
num-derive-0.3.3 check | full | -0.47% | 2.35x
pest_generator-2.1.3 check | full | -0.46% | 2.28x
futures-macro-0.3.19 check | full | -0.44% | 2.22x
mockall_derive-0.11.0 check | full | -0.44% | 2.20x
*diesel check | full | -0.44% | 2.18x

**Comment by nnethercote** [comment]
There likely won't be much change within the rustc-perf benchmarks, but let's check just in case.

@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
`Nonterminal::NtTT` is an implementation detail of `rustc_expand::mbe`, it can never be encountered by parsing functions in `rustc_parse` etc, so it doesn't need to be defined in `rustc_ast` in theory.
It's quite possible that after https://github.com/rust-lang/rust/pull/95259/commits/460f39f1aa89ef2781e09a71ba53d4e582710e6d it can be removed entirely.

**Comment by slanterns** [comment]
bors did not respond.

**Comment by nnethercote** [comment]
> `Nonterminal::NtTT` is an implementation detail of `rustc_expand::mbe`, it can never be encountered by parsing functions in `rustc_parse` etc, so it doesn't need to be defined in `rustc_ast` in theory. It's quite possible that after [460f39f](https://github.com/rust-lang/rust/commit/460f39f1aa89ef2781e09a71ba53d4e582710e6d) it can be removed entirely.

Interesting! I will take a look, I have plans to do more here anyway.

**Comment by nnethercote** [comment]
I pushed an update to remove an "njn:" comment that I accidentally left behind.

@bors r=petrochenkov

**Comment by nnethercote** [comment]
The perf wins clearly outweigh the losses here.

@rustbot label: +perf-regression-triaged

**Pull request merged**
