### PR TITLE
Change camel case warning to upper camel case

### PR DESCRIPTION
**Pull request by tcullum-gpsw**
Changed 5 files to update from structs having camel case to structs having "upper camel case" as discussed https://github.com/rust-lang/rust/issues/57319 and https://github.com/rust-lang/rfcs/pull/2389

### CODE REVIEW

**Comment by varkor** [comment]
This looks good so far, but you'll need to make sure the lines aren't longer than 100 characters (e.g. https://github.com/rust-lang/rust/pull/57346/files#diff-a027af56133818b67275f8d2d9c06a40R92). You can run `./x.py tidy` to check that the line lengths are okay.

Also, could you squash all the changes into a single commit?

r? @varkor

**Comment by estebank** [comment]
It would also be convenient for you to squash your commits down to one, given that this is a single conceptual change. Also, avoid merging from master into your branch, use rebase.

**Comment by TimNN** [comment]
Ping from triage @tcullum-gpsw: Thanks for your contributions! Do you think you'll be able to get back to this PR?

**Comment by Dylan-DPC** [comment]
ping from triage @tcullum-gpsw Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again! Thanks for taking the time to contribute :)

**Pull request closed without merging**
