### PR TITLE
[WIP] Implement a "place unification" MIR optimization (aka source/destination propagation aka NRVO).

### PR DESCRIPTION
**Pull request by eddyb**
*nothing to see here* (PR open for testing purposes)

note to self: **DO NOT MERGE** without inspecting all `FIXME` / `HACK` comments

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
```
[01:17:24] [1m[31merror: internal compiler error(B[m[1m: librustc_trans/mir/block.rs:838: can't directly store to unaligned value(B[m
[01:17:24]   (B[m[1m[34m--> (B[m/cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/error.rs:31:5(B[m
[01:17:24]    (B[m[1m[34m|(B[m
[01:17:24] [1m[34m31(B[m (B[m[1m[34m| (B[m[1m[31m/(B[m (B[m    fn from(failure: F) -> Error {(B[m
[01:17:24] [1m[34m32(B[m (B[m[1m[34m| (B[m[1m[31m|(B[m (B[m        let inner: Inner<F> = {(B[m
[01:17:24] [1m[34m33(B[m (B[m[1m[34m| (B[m[1m[31m|(B[m (B[m            let backtrace = if failure.backtrace().is_none() {(B[m
[01:17:24] [1m[34m34(B[m (B[m[1m[34m| (B[m[1m[31m|(B[m (B[m                Backtrace::new()(B[m
[01:17:24] [1m[34m...(B[m  (B[m[1m[31m|(B[m
[01:17:24] [1m[34m38(B[m (B[m[1m[34m| (B[m[1m[31m|(B[m (B[m        Error { inner: Box::new(inner) }(B[m
[01:17:24] [1m[34m39(B[m (B[m[1m[34m| (B[m[1m[31m|(B[m (B[m    }(B[m
[01:17:24]    (B[m[1m[34m| (B[m[1m[31m|_____^(B[m
[01:17:24] 
[01:17:24] thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:482:9
[01:17:24] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:17:24] 
[01:17:24] note: the compiler unexpectedly panicked. this is a bug.
[01:17:24] 
[01:17:24] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[01:17:24] 
[01:17:24] note: rustc 1.25.0-nightly (7a4d4c6c9 2018-02-01) running on x86_64-unknown-linux-gnu
[01:17:24] 
[01:17:24] [m[m[31m[1merror:[m Could not compile `cargo`.
[01:17:24] 
```

**Comment by eddyb** [comment]
Looks like banning `#[repr(packed)]` structs is trickier than I thought.

**Comment by shepmaster** [comment]
> nothing to see here

👁 We See All 👁 

Like the fact that it's been open for a week, has some CI failures, and some merge conflicts. Any hopes of fixing those issues in the near future?

**Comment by eddyb** [comment]
@shepmaster I can close while I'm not using this (I just need to remember to reopen before pushing).

**Comment by kennytm** [comment]
@bors retry 

Timed out because docker wants to rebuild GCC. Stale cache?

**Comment by eddyb** [comment]
Oh, compiling `clap` appears to never finish but on Travis it looks like Cargo (which compiles just fine).

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by eddyb** [comment]
[Perf comparison](https://perf.rust-lang.org/compare.html?start=d2592cc1fd6fd56b975206a2d1c3e4f4978be3a6&end=bb221b4d8405e9167e3ef627940e8c22049d04cc&stat=instructions%3Au) relative to #48300 (the base of this PR) looks great, except `inflate` and `html5ever`.

I know why `inflate` is affected so much, since I wrote the nasty macro-generated code.
For everyone who updated past https://github.com/PistonDevelopers/inflate/pull/35, there shouldn't be a regression.

`html5ever` is a bit more worrying but also nowhere near as bad. `clap-2.29`, while not on perf, still has a 10x regression I also want to look into.

**Comment by eddyb** [comment]
@bors try

I've pushed a "broken" commit, but I'm failing to find a testcase for it, maybe this will help.
(would a crater run be too much to ask for?)

**Comment by eddyb** [comment]
[Travis did find something](https://travis-ci.org/rust-lang/rust/builds/344888149#L2548) which is a good sign.

**Comment by Mark-Simulacrum** [comment]
Perf runs queued for 1eebfaae190fd40f45c560947525d34db858eae3 and ab6dfcc0775d8a7788d61e23cb49a04eaf32843c.

**Comment by eddyb** [comment]
There is a bit of a cost [for doing it correctly](https://perf.rust-lang.org/compare.html?start=1eebfaae190fd40f45c560947525d34db858eae3&end=ab6dfcc0775d8a7788d61e23cb49a04eaf32843c&stat=instructions%3Au), but that's not really relevant.
Against the #48300 baseline, [it's somewhat similar](https://perf.rust-lang.org/compare.html?start=d2592cc1fd6fd56b975206a2d1c3e4f4978be3a6&end=ab6dfcc0775d8a7788d61e23cb49a04eaf32843c&stat=instructions%3Au) (in fact, [it's worse](https://perf.rust-lang.org/compare.html?start=bb221b4d8405e9167e3ef627940e8c22049d04cc&end=ab6dfcc0775d8a7788d61e23cb49a04eaf32843c&stat=instructions%3Au) than https://github.com/rust-lang/rust/pull/47954#issuecomment-367663279).
Not sure what to make of that last part, since locally this last run is twice as fast for `clap`.

**Comment by Mark-Simulacrum** [comment]
Perf started.

**Comment by eddyb** [comment]
Latest [perf results](https://perf.rust-lang.org/compare.html?start=0e3c9bba8ec6b8c5f8c66868ba6c47d3d38b20b2&end=d0b78e7227949eb539860a246b184d0da38da59a&stat=instructions%3Au) look much better, worse regression is `inflate` still but now only a bit under `30x`.

**Comment by pietroalbini** [comment]
Ping from triage! Do you still need this @eddyb?

**Comment by MSxDOS** [comment]
@eddyb Have you made any progress with this?

**Comment by eddyb** [comment]
@MSxDOS I *may* have found a way to make this cheap enough to always run it.
I'll probably get back to it in the coming months.

**Comment by mark-i-m** [comment]
Any updates?

**Comment by Dylan-DPC** [comment]
Closing this due to inactivity

**Pull request closed without merging**
