### PR TITLE
Update compiletest's `read2` function

### PR DESCRIPTION
**Pull request by alexcrichton**
This was originally copied over from Cargo and Cargo has since [been
updated][update] so let's pull in the fixes here too!

[update]: https://github.com/rust-lang/cargo/pull/5030

### CODE REVIEW

**Comment by kennytm** [comment]
There is a read2 in libstd too, should that be updated?

**Comment by alexcrichton** [comment]
Nah that's actually written a bit differently in such a way that it doesn't need this update

**Pull request merged**
