### PR TITLE
update books for next release

### PR DESCRIPTION
**Pull request by steveklabnik**

### CODE REVIEW

**Comment by petrochenkov** [comment]
@steveklabnik 
https://github.com/rust-lang/rust/pull/48516 got into the next release, but https://github.com/rust-lang-nursery/reference/pull/259 is still not merged.

**Comment by kennytm** [comment]
Lots of broken links.

<details>

```
[01:20:47] reference/special-types-and-traits.html:143: broken link fragment `#associated-functions-and-methods` pointing to `reference/items/traits.html`
[01:20:47] reference/lifetime-elision.html:137: broken link fragment `#function-pointers` pointing to `reference/types.html`
[01:20:47] reference/lifetime-elision.html:240: broken link fragment `#constant-items` pointing to `reference/items.html`
[01:20:47] reference/lifetime-elision.html:240: broken link fragment `#static-items` pointing to `reference/items.html`
[01:20:47] reference/types.html:631: broken link fragment `#elision-and-defaults-in-trait-objects` pointing to `reference/lifetime-elision.html`
[01:20:47] reference/items/constant-items.html:147: broken link - reference/items/lifetime-elision.html
[01:20:47] reference/expressions/operator-expr.html:138: broken link fragment `#the--operator` pointing to `reference/expressions/operator-expr.html`
[01:20:47] reference/expressions/match-expr.html:257: broken link - reference/range-expr.html
[01:20:47] reference/macros-by-example.html:154: broken link - reference/keyword.html
[01:20:47] reference/print.html:1059: broken link - reference/keyword.html
[01:20:47] reference/print.html:1921: broken link - reference/items/lifetime-elision.html
[01:20:47] reference/print.html:3641: broken link fragment `#the--operator` pointing to `reference/print.html`
[01:20:47] reference/print.html:5043: broken link - reference/range-expr.html
[01:20:47] reference/print.html:5586: broken link fragment `#elision-and-defaults-in-trait-objects` pointing to `reference/lifetime-elision.html`
[01:20:47] reference/print.html:6202: broken link fragment `#function-pointers` pointing to `reference/types.html`
[01:20:47] reference/print.html:6305: broken link fragment `#constant-items` pointing to `reference/items.html`
[01:20:47] reference/print.html:6305: broken link fragment `#static-items` pointing to `reference/items.html`
[01:20:47] reference/print.html:6351: broken link fragment `#associated-functions-and-methods` pointing to `reference/items/traits.html`
[01:20:49] thread 'main' panicked at 'found some broken links', tools/linkchecker/main.rs:49:9
[01:20:49] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

</details>

**Comment by steveklabnik** [comment]
@petrochenkov we’re relaxing stabilization requirements for the next few releases, see my internals post. It’ll land soon. That said, if it’s good to go, I can merge and pull it in here.

I’ll investigate those broken links soon.

**Comment by steveklabnik** [comment]
Locally, this claims to have built. Let's see what travis says.

**Pull request merged**
