### PR TITLE
parse_and_disallow_postfix_after_cast: account for `ExprKind::Err`.

### LINKED ISSUE #70552: internal error: entered unreachable code: parse_dot_or_call_expr_with_ shouldn't produce this
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
type T = [(String, [String; u:b ()(:)])];
```

```
$ rustc main.rs
error: expected expression, found `:`
 --> main.rs:1:36
  |
1 | type T = [(String, [String; u:b ()(:)])];
  |                                    ^ expected expression

thread 'rustc' panicked at 'internal error: entered unreachable code: parse_dot_or_call_expr_with_ shouldn't produce this', src/librustc_parse/parser/expr.rs:641:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (699f83f52 2020-03-29) running on x86_64-unknown-linux-gnu

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by Centril**
Fixes https://github.com/rust-lang/rust/issues/70552.

r? @estebank 
cc @daboross

### CODE REVIEW

**Comment by Centril** [comment]
Wrong PR @Dylan-DPC... :) @bors r=estebank

**Comment by pnkfelix** [comment]
discussed at today's [T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/84812weeklymeeting2020040254818.html#192670862). Accepted for beta backport.

**Pull request merged**
