### PR TITLE
mk: Distribute fewer TARGET_CRATES

### PR DESCRIPTION
**Pull request by alexcrichton**
Right now everything in TARGET_CRATES is built by default for all non-fulldeps
tests and is distributed by default for all target standard library packages.
Currenly this includes a number of unstable crates which are rarely used such as
`graphviz` and `rbml`>

This commit trims down the set of `TARGET_CRATES`, moves a number of tests to
`*-fulldeps` as a result, and trims down the dependencies of libtest so we can
distribute fewer crates in the `rust-std` packages.

### CODE REVIEW

**Comment by sanxiyn** [comment]
In Travis, `run-pass/issue-11881.rs` failed because it uses `rbml`.

**Comment by alexcrichton** [comment]
Hm not sure how tests missed those, but should be all fixed now.

**Comment by alexcrichton** [comment]
All tests passed but bors didn't get around to merging, so merging manually.

**Pull request merged**
