### PR TITLE
Color primitives and aliases in rustdoc

### LINKED ISSUE #15307: Std docs links are not all highlighted
[Std doc](http://doc.rust-lang.org/master/std/f32/) links should have colors to highlight that they are links:

std2

Some [users](http://www.reddit.com/r/rust/comments/29kia3/no_ord_for_f32/cils5pz) find it difficult to know which items are links.

[EDIT] Removed sidebar circles. Never thought they needed changing.

### PR DESCRIPTION
**Pull request by mdinger**
This is an alternative to https://github.com/rust-lang/rust/pull/29240 which fixes #15307 by adding colors to primitives and aliases instead of underlining.

Try to keep the discussion in https://github.com/rust-lang/rust/pull/29240 for now though so it can be kept track of.

A sample rendering is [here](http://mdinger.github.io/rust_std_colored/std/index.html)

### CODE REVIEW

**Comment by steveklabnik** [comment]
I think that I like this change better, but I'm going to hold off until after the branch today to do it. Sneaking something like this in right before the release doesn't seem like the right thing to do.

**Comment by mdinger** [comment]
@steveklabnik Any opinion on making all the types a single color instead of varying them? Also, should I add the colored underline on hover? Both are easy to do.

**Comment by defuz** [comment]
Just examples of how underline on hover looks like:

img1

And:

img2

**Comment by steveklabnik** [comment]
@bors: r+ rollup


The branch has happened, so let's merge this and see what people think. I expect it landing on nightly will let people give even more/better feedback.

**Comment by steveklabnik** [comment]
(ie, i think this is a decent solution, but can imagine changing / reverting before 1.6 beta happens)

**Comment by mdinger** [comment]
Ok cool. I'll file an issue to revisit this later then.

**Comment by mdinger** [comment]
Oy, I never pushed the change which added green color to the macros. Here I fixed it.

r? @steveklabnik

**Pull request merged**
