### PR TITLE
rustdoc: Don't inline impls from doc(hidden) modules

### LINKED ISSUE #29584: 404 link in std docs
The link to "FullOps" on this page is broken: https://doc.rust-lang.org/std/primitive.u32.html

### PR DESCRIPTION
**Pull request by mitaa**
fixes #29584

r? @alexcrichton

### CODE REVIEW

**Comment by mitaa** [comment]
I'm not entirely sure if this is the right fix. On the one hand this is already done [when inlining specific impls](https://github.com/rust-lang/rust/blob/2084c2c33a47407c5ec514898d72701cf0233ba9/src/librustdoc/clean/inline.rs#L288), but OTOH there is the pass `strip-hidden` which this maybe should be somehow coupled to.

**Comment by alexcrichton** [comment]
Hm, it's tough to say what the interaction should be here is. Items can be exported from a `#[doc(hidden)]` module but then again you may also want to hide everything in a `#[doc(hidden)]` module.

Right now I think it's a rare enough pattern that we should take this for now, however. Can you be sure to add a test for this though?

**Comment by mitaa** [comment]
Forgot to commit the test..  :neutral_face:

(updated)

**Pull request merged**
