### PR TITLE
Ignore functions before main and thread entry points in backtraces

### PR DESCRIPTION
**Pull request by Zoxc**
Same PR as https://github.com/rust-lang/rust/pull/47824

### CODE REVIEW

**Comment by pietroalbini** [comment]
Ping from triage @alexcrichton! This PR needs your review.

**Comment by alexcrichton** [comment]
Sorry for taking awhile to get to this, but can this include a test of some form to ensure it works across platforms and doesn't regress?

**Comment by pietroalbini** [comment]
Ping from triage @Zoxc! The reviewer asked for some changes.

**Comment by TimNN** [comment]
Closing due to inactivity, feel free to re-open or submit a new PR in the future.

Thanks for your changes!

**Pull request closed without merging**
