### PR TITLE
skip target sanity check when it's a `local-rebuild`

### LINKED ISSUE #130242: Target sanity-check in bootstrap incorrect when doing a local-rebuild
When doing a local-rebuild, the bootstrap compiler is supposed to be functionally identical to the compiler we are building and thus supports all newly introduced targets. As such all targets in the `STAGE0_MISSING_TARGETS` list would actually be supported. With current nightly doing a local-rebuild results in the following error due to this issue:

```
Following targets supported from the stage0 compiler, please remove them from `STAGE0_MISSING_TARGETS` list.
  armv7-rtems-eabihf
Build completed unsuccessfully in 0:00:28
```

We should probably set `BOOTSTRAP_SKIP_TARGET_SANITY=1` unconditionally for all local-rebuilds, or alternatively pretend `STAGE0_MISSING_TARGETS` is empty.

### PR DESCRIPTION
**Pull request by onur-ozkan**
Running the stage0 target sanity check on the newly built compiler can result in errors and incorrect assumptions.

Resolves #130242

### CODE REVIEW

**Comment by lqd** [comment]
Do we also need to revert https://github.com/rust-lang/rustc-perf/pull/1973/files ?(because the target tests had the same issues on perf.rlo as opt-dist and "broke" the bootstrapping benchmark)

**Comment by onur-ozkan** [comment]
> Do we also need to revert https://github.com/rust-lang/rustc-perf/pull/1973/files and do the same as this PR? (because the target tests had the same issues on perf.rlo as opt-dist and "broke" the bootstrapping benchmark)

That doesn't really seem like a local rebuild.

**Comment by Kobzol** [comment]
Could you please comment out `DIST_TRY_BUILD` in `src/ci/github-actions/jobs.yml` and do a try build for `dist-x86_64-linux`?

**Comment by onur-ozkan** [comment]
> Could you please comment out `DIST_TRY_BUILD` in `src/ci/github-actions/jobs.yml` and do a try build for `dist-x86_64-linux`?

Sure.

@bors try

**Comment by Kobzol** [comment]
You can r=me after reverting the temporary change.

**Pull request merged**
