### PR TITLE
Change `to_owned` to `to_string` in docs

### PR DESCRIPTION
**Pull request by ghost**
We should teach conversion from `str` to `String` using `to_string` rather than the legacy `to_owned`.

### CODE REVIEW

**Comment by stjepang** [comment]
By the way, there are around 150 uses of type `"something".to_owned()` in the actual source (not documentation). Would it make sense to update them now, too?

**Comment by steveklabnik** [comment]
@bors: r+ rollup

Thanks!

Last I checked, @rust-lang/compiler wasn't sold on doing that automatically, maybe their opinion has changed.

**Comment by nrc** [comment]
:-( I prefer `to_owned` rather than `to_string` - I think it describes most clearly the transform that is happening (converting a borrowed string to an owned string) and is most likely to let you know when you are doing something unexpected (since `to_string` will convert a whole bunch of stuff to a string, you could think you are converting an `&str` but are actually converting something else, thus hiding an underlying issue).

**Comment by stjepang** [comment]
@nrc I see your point, but after we got specialization `to_string` became more-or-less the idiomatic way, and consistency in documentation is important.

I would personally like it best if `&'static str` would be automatically coerced to `String`. Both `"smth".to_owned()"` and `"smth".to_string()"` look pretty bad to me. Eh, it's hard to make everyone happy :)

**Pull request merged**
