### PR TITLE
feed resolver_for_lowering instead of storing it in a field

### PR DESCRIPTION
**Pull request by oli-obk**
r? @cjgillot 

opening this as

* a discussion for `no_hash` + `feedable` queries. I think we'll want those, but I don't quite understand why they are rejected beyond a double check of the stable hashes for situations where the query is fed but also read from incremental caches.
* and a discussion on removing all untracked fields from TyCtxt and setting it up so that they are fed queries instead

### CODE REVIEW

**Review by cjgillot — APPROVED** [review]
The main reason I disallowed `no_hash` was because I hadn't found a use case.
This one is great! I have 2 suggestions, and r=me.

**Comment by oli-obk** [comment]
While the performance looks like it is not noise, looking at it with cachegrind yields only inliner noise:

```
110,101,744  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::is_terminal_path
 67,503,324  ???:<rustc_infer::infer::combine::CombineFields>::instantiate
-54,068,248  ???:<rustc_infer::infer::sub::Sub as rustc_middle::ty::relate::TypeRelation>::tys
-14,745,244  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::on_all_children_bits::<rustc_mir_dataflow::drop_flag_effects::drop_flag_effects_for_location<<rustc_mir_dataflow::impls::MaybeUninitializedPlaces as rustc_mir_dataflow::framework::GenKillAnalysis>::statement_effect<rustc_index::bit_set::ChunkedBitSet<rustc_mir_dataflow::move_paths::MovePathIndex>>::{closure
-13,892,472  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::on_all_children_bits::<rustc_mir_dataflow::drop_flag_effects::drop_flag_effects_for_location<<rustc_mir_dataflow::impls::MaybeInitializedPlaces as rustc_mir_dataflow::framework::GenKillAnalysis>::statement_effect<rustc_index::bit_set::ChunkedBitSet<rustc_mir_dataflow::move_paths::MovePathIndex>>::{closure
 -6,814,818  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::on_all_children_bits::<&mut rustc_mir_dataflow::drop_flag_effects::drop_flag_effects_for_location<<rustc_mir_dataflow::impls::MaybeUninitializedPlaces as rustc_mir_dataflow::framework::GenKillAnalysis>::statement_effect<rustc_index::bit_set::ChunkedBitSet<rustc_mir_dataflow::move_paths::MovePathIndex>>::{closure
 -6,418,962  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::on_all_children_bits::<&mut rustc_mir_dataflow::drop_flag_effects::drop_flag_effects_for_location<<rustc_mir_dataflow::impls::MaybeInitializedPlaces as rustc_mir_dataflow::framework::GenKillAnalysis>::statement_effect<rustc_index::bit_set::ChunkedBitSet<rustc_mir_dataflow::move_paths::MovePathIndex>>::{closure
 -4,980,660  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::on_all_children_bits::<rustc_mir_dataflow::drop_flag_effects::drop_flag_effects_for_location<<rustc_mir_transform::elaborate_drops::ElaborateDropsCtxt>::drop_flags_for_locs::{closure
 -2,752,512  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::on_all_children_bits::<&mut rustc_mir_dataflow::drop_flag_effects::drop_flag_effects_for_location<<rustc_mir_transform::elaborate_drops::ElaborateDropsCtxt>::drop_flags_for_locs::{closure
 -1,965,767  ???:<rustc_trait_selection::traits::select::SelectionContext>::select
   -983,094  ???:<ena::unify::UnificationTable<ena::unify::backing_vec::InPlace<rustc_type_ir::TyVid, &mut alloc::vec::Vec<ena::unify::VarValue<rustc_type_ir::TyVid>>, &mut rustc_infer::infer::undo_log::InferCtxtUndoLogs>>>::uninlined_get_root_key
   -917,494  ???:<rustc_middle::mir::syntax::Rvalue>::ty::<rustc_middle::mir::Body>
   -917,490  ???:<rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::statement
   -851,932  ???:<rustc_middle::mir::BasicBlockData>::expand_statements::<<rustc_mir_transform::deaggregator::Deaggregator as rustc_middle::mir::MirPass>::run_pass::{closure
   -786,405  ???:<rustc_mir_dataflow::framework::engine::Engine<rustc_borrowck::dataflow::Borrows>>::iterate_to_fixpoint
    524,329  ???:<rustc_borrowck::type_check::TypeChecker>::typeck_mir
    524,304  ???:<rustc_borrowck::borrow_set::BorrowSet>::build
    524,280  ???:<core::iter::adapters::map::Map<core::ops::range::Range<usize>, <rustc_const_eval::interpret::validity::ValidityVisitor<rustc_const_eval::const_eval::machine::CompileTimeInterpreter> as rustc_const_eval::interpret::visitor::ValueVisitor<rustc_const_eval::const_eval::machine::CompileTimeInterpreter>>::walk_value::{closure
    262,152  ???:rustc_mir_transform::check_unsafety::unsafety_check_result
   -131,074  ???:<rustc_mir_build::build::Builder>::as_operand
```

**Comment by pnkfelix** [comment]
Visiting for weekly performance triage



* the original timer run said [this had no problem](https://github.com/rust-lang/rust/pull/105220#issuecomment-1336312355)
* (though to be fair, I don't know what changes occurred to the commit series between that timer run and what landed)
* oli-obj investigated and found [cachegrind shows this to be artifacts from inlining decisions](https://github.com/rust-lang/rust/pull/105220#issuecomment-1338942653)
* The impact on cycle-counts (rather than instruction counts) was well within noise tolerance levels.
* Therefore, marked as triaged.

@rustbut label: +perf-regression-triaged

**Pull request merged**
