### PR TITLE
add const generics array coercion test

### PR DESCRIPTION
**Pull request by lcnr**

### CODE REVIEW

**Comment by lcnr** [comment]
Why did CI get cancelled here?

**Comment by lcnr** [comment]
spurious

@bors r+ rollup

**Comment by lcnr** [comment]
okay, that failure is more interesting. cc @rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
```
2020-07-27T19:22:12.6296060Z ##[error]fatal: reference is not a tree: d86d134a1b5cc4714a6904a09cb8975ff4d48715
2020-07-27T19:22:12.6304840Z ##[warning]Git checkout failed on shallow repository, this might because of git fetch with depth '2' doesn't include the checkout commit 'd86d134a1b5cc4714a6904a09cb8975ff4d48715'.
2020-07-27T19:22:12.6317910Z ##[error]Git checkout failed with exit code: 128
```

Probably a race with something or other, @bors retry

**Comment by kennytm** [comment]
```
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/fnv/1.0.6/download`, got 502
```

@bors retry

**Pull request merged**
