### PR TITLE
Implement rustc part of RFC 3127 trim-paths

### PR DESCRIPTION
**Pull request by Urgau**
This PR implements (or at least tries to) [RFC 3127 trim-paths](https://github.com/rust-lang/rust/issues/111540), the rustc part. That is `-Zremap-path-scope` with all of it's components/scopes.

@rustbot label: +F-trim-paths

### CODE REVIEW

**Comment by weihanglo** [comment]
@Urgau have you started cargo part of this? I can help do that if you haven't.

**Comment by Urgau** [comment]
> @Urgau have you started cargo part of this? I can help do that if you haven't.

No, I haven't and to be honest I'm not sure when or if I would have done it any time soon.

**Comment by weihanglo** [comment]
PR on cargo side <https://github.com/rust-lang/cargo/pull/12625>

**Comment by Urgau** [comment]
@compiler-errors This PR is waiting on you (to review). I will continue to rebase for the time being. Let me know if you don't have time or prefer another reviewer.

**Comment by compiler-errors** [comment]
Sorry, I'll try to review this in a few days. If in a couple of days you still haven't heard anything, feel free to eithe bother me or re-roll the reviewer.

**Comment by Urgau** [comment]
```
  --- stderr -------------------------------
  
  thread 'main' has overflowed its stack
  ------------------------------------------ 
  
  failures:
      [rustdoc] tests\rustdoc\intra-doc\primitive-disambiguators.rs
```
Spurious?

**Comment by compiler-errors** [comment]
@bord retry

**Comment by Urgau** [comment]
> The job **`x86_64-apple-1`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/6438928065/job/17486023717) [(plain)](https://github.com/rust-lang-ci/rust/commit/0e6505fdfa9cf58a46111e089039fd12da067af5/checks/17486023717/logs)

My bad, I put the apple/darwin condition before the variable (`$(UNAME)` is this case) was initialized. I was misled by the other variables defined before importing "tools.mk". Fixed.

**Comment by Urgau** [comment]
https://github.com/rust-lang/rust/commit/acc3b61c5e998b8ae170ed7f7b0b37aeecaf01a9 removed the `bitflags` dependency from `rustc_session` which this PR is using. Re-added it.

**Pull request merged**
