### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by RalfJung**
Successful merges:

 - #72026 (Update annotate-snippets-rs to 0.8.0)
 - #72583 (impl AsRef<[T]> for vec::IntoIter<T>)
 - #72615 (Fix documentation example for gcov profiling)
 - #72761 (Added the documentation for the 'use' keyword)
 - #72799 (Add `-Z span-debug` to allow for easier debugging of proc macros)
 - #72811 (Liballoc impl)
 - #72963 (Cstring `from_raw` and `into_raw` safety precisions)
 - #73001 (Free `default()` forwarding to `Default::default()`)
 - #73075 (Add comments to `Resolve::get_module`)
 - #73092 (Clean up E0646)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @rust-lang/infra second timeout I am seeing in 24h...

**Comment by marmeladema** [comment]
FYI, it was making progress, albeit rather slowly: https://dev.azure.com/rust-lang/rust/_build/results?buildId=31399&view=logs&j=fd0bd97c-dca3-5d16-5976-7c3893e4446f&t=3fc0f2c0-6393-5fc1-7bce-c70c707d4d26

**Comment by Dylan-DPC** [comment]
looks like one of the normal failures we receive once in a while

**Comment by marmeladema** [comment]
All builds have finished except https://dev.azure.com/rust-lang/rust/_build/results?buildId=31422&view=logs&j=77fe58e7-c26b-56af-861c-0e6795721952&t=28b6fc66-4f34-5b10-ad6a-df15d8bbc116  which seems blocked on completion.

**Comment by RalfJung** [comment]
Strange, it said "Build completed successfully in 2:13:42" already more than 1h ago, and then stopped.

**Comment by Dylan-DPC** [comment]
looks like another timeout..

**Comment by RalfJung** [comment]
There we go.
@bors retry

**Pull request merged**
