### PR TITLE
Add Pass manager for MIR

### PR DESCRIPTION
**Pull request by nagisa**
A new PR, since rebasing the original one (https://github.com/rust-lang/rust/pull/31448) properly was a pain. Since then there has been several changes most notable of which:
1. Removed the pretty-printing with `#[rustc_mir(graphviz/pretty)]`, mostly because we now have `--unpretty=mir`, IMHO that’s the direction we should expand this functionality into;
2. Reverted the infercx change done for typeck, because typeck can make an infercx for itself by being a `MirMapPass`

r? @nikomatsakis

### CODE REVIEW

**Comment by arielb1** [comment]
Is there a way to generate MIR graphs after this PR?

**Comment by nagisa** [comment]
The graphviz ones? I don’t think so, but an option for `unpretty` could certainly be added.

**Comment by nikomatsakis** [comment]
This basically LGTM. I think the dep-graph node handling here is not right, but it might be worth cleaning that up in a later PR.

Sort of sad to lose access to the graphviz code altogether, though I agree that `--unpretty` is the better way to access it. (Also, it ought to imho be `-Z unpretty`, as that is not on any sort of path to stability, but that's obviously a separate issue.)

**Comment by nagisa** [comment]
Rebased, comments addressed.

**Comment by nikomatsakis** [comment]
Actually, one question: are we ok with having no more way to get graphviz output (until someone lands a PR)? I am, but I'd love to hear from one or two others on @rust-lang/compiler on this point.

**Comment by arielb1** [comment]
I like to use graphviz to debug MIR. It is much more readable than the standard debug output.

**Comment by arielb1** [comment]
I think that having a `--unpretty mir-graphviz` would be a good way to fix that.

**Comment by nagisa** [comment]
I’ll try implementing that this weekend or something if I don’t get carried away with university things. I’m fine with blocking this on that – it is not like this is important to land this sooner than later.

**Comment by nagisa** [comment]
`--unpretty mir-cfg` added. Bikeshed on name welcome.

**Pull request merged**
