### PR TITLE
Bump Miri for panic unwinding support

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by RalfJung** [comment]
Ah, we had the same thought. ;) You were slightly faster, so let's use this one.

@bors r+

**Comment by Aaron1011** [comment]
@RalfJung: I've updated this PR to include https://github.com/rust-lang/miri/pull/1065. Could you approve the latest commit?

**Comment by RalfJung** [comment]
Rust master doesn't work with Miri any more: https://travis-ci.com/rust-lang/miri/jobs/259357217

@bors r-

**Comment by RalfJung** [comment]
@Aaron1011 Miri is fixed, could you update the PR?

**Comment by Aaron1011** [comment]
@RalfJung: Updated

**Comment by RalfJung** [comment]
(Cycling PR to restart CI.)

**Pull request merged**
