### PR TITLE
avoid computing liveness for locals that escape into statics

### LINKED ISSUE #52713: [nll] avoid liveness for values that escape into the output when in a static
As an optimization for large statics like the ones in html5ever and so forth: we tend to spend a ton of time in liveness and elsewhere in these cases, but it seems a bit silly since we know that any references or lifetimes which flow into the result must be `'static`. 

The idea would be something like this:

- Before computing liveness, we do a pass over the MIR.
- We create a union-find set of `Local` values.
- Whenever we see a statement like `_0 = _1` or `_0 = Aggregate { _1 }` or `_0 = &_1`, we union together `_0` and `_1` -- basically, the idea is we union `_0` and `_1` whenever the type of `_0` must contain any of the lifetimes in `_1`.
- Then at the end we check which things are union'd with `_0` -- for those variables, we do not have to compute liveness, and can instead just force all of their regions to outlive `'static`. 

I .. think that's sound =)

Example:

```rust
#![feature(nll)]

pub struct Map<K: 'static, V: 'static> {
    pub key: u64,
    pub disps: Slice<(u32, u32)>,
    pub entries: Slice<(K, V)>,
}

pub enum Slice<T: 'static> {
    Static(&'static [T]),
}

pub static NAMED_ENTITIES: Map<&'static str, (u32, u32)> = Map {
    key: 1897749892740154578,
    disps: Slice::Static(&[
        (1, 4),
        (1, 4),
        (1, 4),
        (1, 4),
        (1, 4),
        (1, 4),
        (1, 4),
    ]),
    entries: Slice::Static(&[
        ("GreaterSlan", (0, 0)),
        ("GreaterSlan", (0, 0)),
        ("GreaterSlan", (0, 0)),
        ("GreaterSlan", (0, 0)),
        ("GreaterSlan", (0, 0)),
        ("GreaterSlan", (0, 0)),
        ("GreaterSlan", (0, 0)),
    ]),
};

fn main() {
}
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #52713 

I poked at this on the plane and I think it's working -- but I want to do a bit more investigation and double check. The idea is to identify those local variables where the entire value will "escape" into the return -- for them, we don't need to compute liveness, since we know that the outlives relations from the return type will force those regions to be equal to free regions. This should help with html5ever in particular.

- [x] test performance
- [x] verify correctness
- [x] add comments

r? @pnkfelix 
cc @lqd

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@rust-timer build da90b26bfa124c61397a741382494a3e2d109739

**Comment by nikomatsakis** [comment]
without support for `X = &*Y` reborrows, this won't work so well :)

**Comment by nikomatsakis** [comment]
@rust-timer build 24a313ef05eff74c552335159aa02fbbfcf7e8b3

**Comment by nikomatsakis** [comment]
The comparison URL doesn't work yet but you can view the NLL dashboard results for 24a313e here:

https://perf.rust-lang.org/nll-dashboard.html?commit=24a313ef05eff74c552335159aa02fbbfcf7e8b3&stat=instructions%3Au

html5ever | 11,036,800,000.00 | 241,127,686,144.00 | 2,184.76
-- | -- | -- | --
tuple-stress | 24,313,452,544.00 | 69,815,214,080.00 | 287.15
keccak | 47,153,451,008.00 | 85,099,872,256.00 | 180.47
clap-rs | 21,144,303,616.00 | 30,054,019,072.00 | 142.14
sentry-cli | 12,483,297,280.00 | 15,415,211,008.00 | 123.49
inflate | 13,858,590,720.00 | 16,881,270,784.00 | 121.81

versus


html5ever | 11,049,374,720.00 | 359,718,027,264.00 | 3,255.55
-- | -- | -- | --
tuple-stress | 24,456,257,536.00 | 69,911,584,768.00 | 285.86
keccak | 47,174,316,032.00 | 85,679,489,024.00 | 181.62
clap-rs | 21,200,508,928.00 | 31,260,983,296.00 | 147.45
inflate | 13,863,846,912.00 | 17,317,126,144.00 | 124.91

**Comment by nikomatsakis** [comment]
Seems to be a good win on html5ever, as predicted =)

**Comment by nikomatsakis** [comment]
@pnkfelix ready for review now I think

**Comment by kennytm** [comment]
@bors r-

```
[00:13:14] [0m[1m[38;5;9merror[0m[0m[1m: field is never used: `tcx`[0m
[00:13:14] [0m  [0m[0m[1m[38;5;12m--> [0m[0mlibrustc_mir/borrow_check/nll/escaping_locals.rs:79:5[0m
[00:13:14] [0m   [0m[0m[1m[38;5;12m|[0m
[00:13:14] [0m[1m[38;5;12m79[0m[0m [0m[0m[1m[38;5;12m| [0m[0m    tcx: TyCtxt<'cx, 'gcx, 'tcx>,[0m
[00:13:14] [0m   [0m[0m[1m[38;5;12m| [0m[0m    [0m[0m[1m[38;5;9m^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
[00:13:14] [0m   [0m[0m[1m[38;5;12m|[0m
[00:13:14] [0m   [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: `-D dead-code` implied by `-D warnings`[0m
[00:13:14] 
[00:13:14] [0m[1m[38;5;9merror[0m[0m[1m: field is never used: `mir`[0m
[00:13:14] [0m  [0m[0m[1m[38;5;12m--> [0m[0mlibrustc_mir/borrow_check/nll/escaping_locals.rs:80:5[0m
[00:13:14] [0m   [0m[0m[1m[38;5;12m|[0m
[00:13:14] [0m[1m[38;5;12m80[0m[0m [0m[0m[1m[38;5;12m| [0m[0m    mir: &'cx Mir<'tcx>,[0m
[00:13:14] [0m   [0m[0m[1m[38;5;12m| [0m[0m    [0m[0m[1m[38;5;9m^^^^^^^^^^^^^^^^^^^[0m
[00:13:14] 
[00:13:14] [0m[1m[38;5;9merror[0m[0m[1m: aborting due to 2 previous errors[0m
[00:13:14] 
[00:13:14] [0m[0m[1m[31merror:[0m Could not compile `rustc_mir`.
[00:13:14] 
```

**Pull request merged**
