### PR TITLE
Migrate `run-make/symlinked-rlib` to `rmake.rs`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/rust-lang/rust/issues/121876.

r? @jieyouxu

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks, r=me after fixing the tidy failure.

**Comment by jieyouxu** [comment]
Sorry I completely missed this (I think I missed updating the tracking issue), but I think this collides with https://github.com/rust-lang/rust/pull/125674 because both PRs are modifying the same test. I'm was updating the tracking issue and noticed just now. I'll take a closer look later to see which port we should go for...

**Comment by GuillaumeGomez** [comment]
Closing then!

**Pull request closed without merging**
