### PR TITLE
Update cargo

### LINKED ISSUE #8241: If rev is added to git url cargo gives no warnings and has unexpected behavior
**Problem**
I have 2 git repos in my `Cargo.toml`:
```toml
[dependencies]
juniper-actix = { git = "https://github.com/graphql-rust/juniper#91a33539", package = "juniper_actix" }
juniper = { git = "https://github.com/graphql-rust/juniper#91a33539" }
```
When cargo downloads / compiles these packages it shows the `#91a33539` 2 times:
```
> cargo build
    Updating git repository `https://github.com/graphql-rust/juniper#91a33539`
   Compiling juniper_codegen v0.14.2 (https://github.com/graphql-rust/juniper#91a33539#91a33539)
   Compiling juniper v0.14.2 (https://github.com/graphql-rust/juniper#91a33539#91a33539)
   Compiling juniper_actix v0.1.0 (https://github.com/graphql-rust/juniper#91a33539#91a33539)
```

**Steps**
1. Run `cargo init`
2. Add the deps shown above to the dependencies
3. Run `cargo build`

**Possible Solution(s)**
Show an error with a note to add `rev = ".."` to the dep or support adding a rev to the URL

**Notes**

Output of `rustup show`:
```
> rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/mark/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/mark')
rustc 1.45.0-nightly (7ced01a73 2020-04-30)
```

### PR DESCRIPTION
**Pull request by ehuss**
9 commits in 9fcb8c1d20c17f51054f7aa4e08ff28d381fe096..40ebd52206e25c7a576ee42c137cc06a745a167a
2020-05-25 16:25:36 +0000 to 2020-06-01 22:35:00 +0000
- Warn if using hash in git URL, Fixes rust-lang/cargo#8241 (rust-lang/cargo#8297)
- reset lockfile information between resolutions (rust-lang/cargo#8274)
- Disable strip_works test on macos. (rust-lang/cargo#8301)
- Fix typo in impl Display for Strip (rust-lang/cargo#8299)
- Add support for rustdoc root URL mappings. (rust-lang/cargo#8287)
- Fix tests with enoent error message on non-english systems. (rust-lang/cargo#8295)
- Fix fingerprinting for lld on Windows with dylib. (rust-lang/cargo#8290)
- Fix a typo (rust-lang/cargo#8289)
- Fix several issues with close_output test. (rust-lang/cargo#8286)

### CODE REVIEW

**Comment by ehuss** [comment]
@Mark-Simulacrum do you have any objection if I enable building lld on the Windows job that tests Cargo? Cargo now has a test for some lld behavior on Windows.  

AFAIK, lld builds pretty fast (about 40s on my machine) and with sccache should be even faster. I also believe it is not actually *used* for anything (unless `use-lld` is enabled, which I believe it isn't).

r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Should be fine. @bors r+

**Pull request merged**
