### PR TITLE
Add checkup in tail function and return Option type

### LINKED ISSUE #24141: Calling `.tail()` on a empty slice panics
Calling `.tail()` on a slice does no check at all (see https://github.com/rust-lang/rust/blob/master/src/libcore/slice.rs#L210 ), and will panic if called on a empty slice.

Nothing suggests it in the documentation, I personally expected that calling `.tail()` on an empty slice would return an empty slice, as `.first()` returns an Option.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #24141.

### CODE REVIEW

**Comment by kballard** [comment]
This makes `tail()` inconsistent with `tail_mut()`, `init()` ,and `init_mut()`.

**Comment by kballard** [comment]
I'm working on a separate PR that implements my proposal, of replacing `tail()` / `init()` with `pop_first()` / `pop_last()`.

**Comment by kballard** [comment]
My PR has been submitted as #24184.

**Comment by nikomatsakis** [comment]
Hmm. @kballard's PR is a bit more ambitious, so they're not directly comparable; but at minimum I agree that having `tail` be inconsistent with the other fns doesn't seem quite right!

**Comment by nikomatsakis** [comment]
So I'm going to leave this PR open as an alternative to #24184. I figure we might decide to take this PR, #24184, or neither. But let's move the conversation to #24141 so it can be consolidated.

**Comment by nikomatsakis** [comment]
I think I'm going to close this due to https://github.com/rust-lang/rfcs/pull/1058 -- let's see how that pans out, but that approach in some form seems to be popular.

**Comment by nikomatsakis** [comment]
Thanks @GuillaumeGomez for the PR in any case!

**Pull request closed without merging**
