### PR TITLE
 [WIP] Try packing hot type flags in the Ty (pointer)

### PR DESCRIPTION
**Pull request by WaffleLapkin**
r? @ghost

### CODE REVIEW

**Comment by jackh726** [comment]
The added complexity here is enough, that I personally don't think it's worth landing unless it's a *substantial* perf win (I'm thinking >10%).

**Comment by WaffleLapkin** [comment]
@jackh726 while it's unlikely this will actually be merged (as you can see this is a significant perf **regression**), I think you went a bit overboard with asking for >10%, 10% is **a lot** a lot.

I don't see significant complexity being added here, the code added to handle tags is mostly trivial. Sure it adds more layers to `Ty`'s internals, but they are it — internals. `ty` module is a bit of a mess, but this can be addressed separately (which I'm planning to do anyway).

**Comment by jackh726** [comment]
Sure, 10% is a lot, but that does indicate well my aversion to this. Maybe a more detailed comment would be something like "more than 10% on a few benches or several percent green on most benches".

Yes, these are internals, but increasing the complexity of these makes abstracting over these (in the type library) more difficult and complex. When these have a clear and obvious benefit that comes mostly from being able to do less work (rather than simply being able to do things *faster*), then they're clearly worth the complexity in these abstractions. 

While the actual *code* for this is not that complicated, it  increases the overall internals complexity by a lot (by splitting flags into two potential locations) - not just in code, but also mental complexity.

**Comment by WaffleLapkin** [comment]
I has not been able to make this beneficial and don't really want to try figuring why this is not working. If anyone ever wants to try this again, here is how I measured which flags are hot: https://github.com/rust-lang/rust/compare/master...WaffleLapkin:rust:record_flag_accesses (commits 79b55b098784a15e1fef4a550071666fff5e3adc and 16ba41474cce57b7a65eea2b30b92c46e031c014).

**Pull request closed without merging**
