### PR TITLE
Document that `create_dir_all` calls `mkdir`/`CreateDirW` multiple times

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by the8472** [comment]
How do those details help the reader?

**Comment by tbu-** [comment]
It's not a single syscall that makes this function work, but additional logic on top of it. That's interesting for the user of this function.

**Comment by the8472** [comment]
We don't document all the functions that happen to do more than 1 syscall. So, again, *why* is that interesting to the user? How does it help them to use it?

**Comment by tbu-** [comment]
It's interesting in that it's non-atomic. In the error case, there might be partial directory structures lying around.

> We don't document all the functions that happen to do more than 1 syscall.

Can you give an example of a function that documents which syscall it corresponds to, but uses it multiple times without documenting it?

**Comment by the8472** [comment]
> It's interesting in that it's non-atomic. In the error case, there might be partial directory structures lying around.

Then the docs should say that, rather then trying to say that through the implementation details.

> Can you give an example of a function that documents which syscall it corresponds to, but uses it multiple times without documenting it?

Eh, most docs aren't even that precise. `fs::copy` says which syscalls it uses but not how often.

**Comment by tbu-** [comment]
> > It's interesting in that it's non-atomic. In the error case, there might be partial directory structures lying around.
> 
> Then the docs should say that, rather then trying to say that through the implementation details.

Before I'll try to do that: Are you opposed to *also* mentioning that it's using multiple calls to `mkdir` instead of just one, in the implementation details? I'll remove the longer explanation of how the multiple calls are issued.

**Comment by the8472** [comment]
Using a plural is fine. Explaining the traversal order seems unnecessary to me.

**Pull request merged**
