### PR TITLE
Breaking update of stdsimd

### PR DESCRIPTION
**Pull request by gnzlbg**
This commit updates stdsimd and contains two breaking changes:

* https://github.com/rust-lang-nursery/stdsimd/pull/733
* https://github.com/rust-lang-nursery/stdsimd/pull/586

We already did a crater run of 586 but we should do another one here.

r? @alexcrichton

### CODE REVIEW

**Comment by gnzlbg** [comment]
Switching this to WIP: needs a crater run once CI is green.

**Comment by Centril** [comment]
Note to self: crater check-only when try completes.

**Comment by Centril** [comment]
@craterbot run mode=check-only

**Comment by Centril** [comment]
@gnzlbg Looking good! 

@alexcrichton Let's move ahead?

**Pull request merged**
