### PR TITLE
miri engine: turn some debug_assert into assert

### PR DESCRIPTION
**Pull request by RalfJung**
@eddyb said to avoid debug assertions in rustc. These checks here look like they are probably not too expensive. Cc @oli-obk

### CODE REVIEW

**Review by eddyb — APPROVED** [review]
r=me if perf is fine

**Comment by RalfJung** [comment]
There's +1.5% on many "clean incremental" and "patched incremental" tests (i.e., tests that run very shortly). I suppose @nnethercote wouldn't like to lose those, so I'll have to make a guess about which assertion might be the culprit here.

**Comment by RalfJung** [comment]
Now it looks like noise.

@bors r=eddyb

**Pull request merged**
