### PR TITLE
Add more `// unit-test`s to MIR opt tests

### PR DESCRIPTION
**Pull request by JakobDegen**
I only changed things which are hopefully completely uninteresting. I plan to submit more PRs that cover more files, but those cases will need some more complicated (and hence possibly controversial) changes, so I'll try and submit those in reasonably sized batches.

r? rust-lang/wg-mir-opt

### CODE REVIEW

**Comment by JakobDegen** [comment]
r? rust-lang/mir-opt

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @JakobDegen!

@bors r+

**Comment by wesleywiser** [comment]
Oh, wait. There's a merge conflict. 

@bors r-

**Comment by JakobDegen** [comment]
@rustbot ready

Nothing interesting changed, no bors perms though @wesleywiser

**Comment by tmiasko** [comment]
Failed in #100330. Probably requires `profiler = true` in `config.toml` to update output of `src/test/mir-opt/instrument_coverage.rs` test.

@bors r- delegate+

**Comment by JakobDegen** [comment]
Thanks, was able to reproduce and fix the failure locally, hopefully bors agrees. Wonder what it would take to make GHA run these...

@bors r=wesleyweiser

**Pull request merged**
