### PR TITLE
Add `is_even` and `is_odd` methods on `int_impl` and `uint_impl`.

### PR DESCRIPTION
**Pull request by vidhanio**
These methods would be nice helper methods similar to `is_positive` and `is_negative`.

### CODE REVIEW

**Comment by vidhanio** [comment]
r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs

**Comment by vidhanio** [comment]
> These methods seem highly specific. Are there common use cases for them?
> 
> (Maybe a more generic `.is_multiple_of(2)` would be more useful.)

`is_multiple_of` could be better, but i felt that since `is_positive`/`is_negative` exist already, `is_even`/`is_odd` aren't too out of the scope for helper methods to make code look more declarative.

**Comment by vidhanio** [comment]
How would I go about fixing the "missing stability attribute" errors? I don't know how I would set those in a pull request for a new feature.

**Comment by m-ou-se** [comment]
> How would I go about fixing the "missing stability attribute" errors? I don't know how I would set those in a pull request for a new feature.

You can set them to `"none"`. Once someone from the team is on board with your change, you can open a tracking issue and put its number there.

I don't think we should add this though. I can imagine something like `is_multiple_of` might be generally useful enough for the standard library`, but `is_even` and `is_odd` seem too specific to me. If you want to add those, I first want to see some more motivation including real world use cases.

**Comment by vidhanio** [comment]
> I don't think we should add this though. I can imagine something like `is_multiple_of` might be generally useful enough for the standard library, but `is_even`and`is_odd` seem too specific to me. If you want to add those, I first want to see some more motivation including real world use cases.

I think that `is_multiple_of` could be a nice middle ground. Personally, I wish `is_(even|odd)` existed for the same reasons as `is_(positive|negative)`, being to remove the visually cluttered and imperative `x % 2 == 0`.

**Comment by vidhanio** [comment]
Oops, didn't think renaming the branch would close the pull request. 😅

**Comment by vidhanio** [comment]
> Even the python standard library, known for its wide selection of batteries, doesn't have a dedicated method for this. Neither does java.
> 
> I don't think this feature is worth it, especially considering that the remainder operator exists and is more general.

I see what you mean, but I just feel that the existence of `is_(positive|negative)` kind of nullifies this, as it is also just as easy (arguably even easier) to do `n > 0` or `n < 0`.

**Comment by vidhanio** [comment]
> That said, I'd personally approve an `is_multiple_of`, for the more general case, largely because it'd be nice for chaining. (It should probably be marked as `inline`, and I'm sure the compiler will be able to optimize `is_multiple_of(2)`.)

I could definetly get started on that instead. Just to clarify for myself `inline`, means I be doing `inline(always)`, correct?

**Comment by vidhanio** [comment]
> `is_multiple_of(n)` isn't all that great either because it's still a subset of the remainder op AND you can't use it for `filter(is_multiple_of)` because it takes an argument and we don't have currying so in that way it's even less useful than `is_positive`.

I realized that while writing the code, but I'll still finish up the new PR.

**Comment by joshtriplett** [comment]
Closing this, in favor of a possible future PR.

**Pull request closed without merging**
