### PR TITLE
Implement Extend and FromIterator for OsString

### PR DESCRIPTION
**Pull request by lopopolo**
Add the following trait impls:

- `impl Extend<OsString> for OsString`
- `impl<'a> Extend<&'a OsStr> for OsString`
- `impl FromIterator<OsString> for OsString`
- `impl<'a> FromIterator<&'a OsStr> for OsString`

Because `OsString` is a platform string with no particular semantics, concatenating them together seems acceptable.

I came across a use case for these trait impls in https://github.com/artichoke/artichoke/pull/1089:

Artichoke is a Ruby interpreter. Its CLI accepts multiple `-e` switches for executing inline Ruby code, like:

```console
$ cargo -q run --bin artichoke -- -e '2.times {' -e 'puts "foo: #{__LINE__}"' -e '}'
foo: 2
foo: 2
```

I use `clap` for command line argument parsing, which collects these `-e` commands into a `Vec<OsString>`. To pass these commands to the interpreter for `Eval`, I need to join them together. Combining these impls with `Iterator::intersperse` https://github.com/rust-lang/rust/issues/79524 would enable me to build a single bit of Ruby code.

Currently, I'm doing something like:

```rust
let mut commands = commands.into_iter();
let mut buf = if let Some(command) = commands.next() {
    command
} else {
    return Ok(Ok(()));
};
for command in commands {
    buf.push("\n");
    buf.push(command);
}
```

If there's interest, I'd also like to add impls for `Cow<'a, OsStr>`, which would avoid allocating the `"\n"` `OsString` in the concatenate + intersperse use case.

### CODE REVIEW

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by lopopolo** [comment]
@m-ou-se can I go ahead and add the impls for `Cow<'a, OsStr>` as well?

**Comment by m-ou-se** [comment]
@lopopolo Yes, that seems reasonable, since we also have those for str/String.

cc @dtolnay @Amanieu since you already checked your checkboxes.

**Comment by lopopolo** [comment]
I added `FromIterator` and `Extend` impls for `Iterator<Item = Cow<'a, OsStr>>`.

These impls can potentially expanded to add impls for `Box<OsStr>`, `Rc<OsStr>`, and `Arc<OsStr>`, but I don't have a need for these so I'm not planning on adding these.

**Comment by pthariensflame** [comment]
This is insta-stable and so needs `relnotes`, yes?

**Pull request merged**
