### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #71568 (Document unsafety in slice/sort.rs)
 - #72709 (`#[deny(unsafe_op_in_unsafe_fn)]` in liballoc)
 - #73214 (Add asm!() support for hexagon)
 - #73248 (save_analysis: improve handling of enum struct variant)
 - #73257 (ty: projections in `transparent_newtype_field`)
 - #73261 (Suggest `?Sized` when applicable for ADTs)
 - #73300 (Implement crate-level-only lints checking.)
 - #73334 (Note numeric literals that can never fit in an expected type)
 - #73357 (Use `LocalDefId` for import IDs in trait map)
 - #73364 (asm: Allow multiple template string arguments; interpret them as newline-separated)
 - #73382 (Only display other method receiver candidates if they actually apply)
 - #73465 (Add specialization of `ToString for char`)
 - #73489 (Refactor hir::Place)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors retry

network issue

**Comment by Manishearth** [comment]
```
[/checkout/obj/build/ct/xsv/target/debug/xit/cat_cols/test-499]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "cat" "columns" "in1.csv" "in2.csv" "--no-headers"
thread 'test_cat::prop_cat_cols' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (CsvData { data: [[[]]] }, CsvData { data: [[[239, 187, 191]]] })
Error: "assertion failed: `(left == right)`\n  left: `[]`,\n right: `[[\"\", \"\\u{feff}\"]]`"', /checkout/src/libstd/macros.rs:13:23


failures:
    test_cat::prop_cat_cols

test result: FAILED. 421 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/cargotest" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/cargo" "/checkout/obj/build/ct"
expected success, got: exit code: 101
```

**Comment by Manishearth** [comment]
I don't undestand how that could break

**Comment by Manishearth** [comment]
I'm also not really happy with running stochastic tests like quickcheck for ecosystem crates :/

**Comment by Manishearth** [comment]
@bors retry

that's the byte order mark, that's a bug in the xsv tests

**Comment by Manishearth** [comment]
https://github.com/BurntSushi/xsv/issues/227

**Comment by Mark-Simulacrum** [comment]
We should either disable quickcheck ecosystem tests or perhaps make the seed constant, I think -- I imagine there's some env variable we can set?

**Comment by Manishearth** [comment]
Oh, that can work too

**Comment by Manishearth** [comment]
Unrelated: I wonder if we can set up caching so that retrying the same PR won't rerun builds that succeeded?

**Comment by Mark-Simulacrum** [comment]
In theory yeah but I imagine it's pretty hard. I have wanted to try sccache for stage 0 at least though which would probably give many of the benefits of your proposal.

**Comment by Manishearth** [comment]
@bors retry force 

network

**Comment by nnethercote** [comment]
This merge was a small perf [win](https://perf.rust-lang.org/compare.html?start=2d8bd9b74dc0cf06d881bac645698ccbcf9d9c5e&end=34c5cd9a64d8537236626c4ccbed39a924cd38e2&stat=instructions:u).

**Pull request merged**
