### PR TITLE
Replace libgcc with libcompiler-rt.

### PR DESCRIPTION
**Pull request by vadimcn**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Some thoughts:

* Does compiler-rt need to be explicitly passed? I think it's already at the end of the link args, right?
* Are we sure that compiler-rt implements everything in libgcc, as well as under the same names and everything? I'm mostly worried about this passing on the bots and then compiles fail for any toolchain other than the one the bots have.

**Comment by vadimcn** [comment]
> Does compiler-rt need to be explicitly passed? I think it's already at the end of the link args, right?

Yes, but then we throw in some more libs - `mingw32` and `mingwex` - that depend on the stack probes at the very least.

> Are we sure that compiler-rt implements everything in libgcc, as well as under the same names and everything? 

No, I am not sure.  The Rust toolchain compiles and passes all tests though.   
I suppose a crater run might produce more clarity.   Do you know how to kick it off?

(I am assuming we do want to disentangle Rust from gcc runtime?)

**Comment by alexcrichton** [comment]
Guh we seem to always throw these 'extra arguments' in some random order to the linker...

Unfortunately crater probably won't help much here as it doesn't build anything on Windows, but yeah I'm fine at least disentangling Rust from the gcc runtime!

What does the gcc runtime actually do? E.g. what do mingw32/mingwex actually buy us?

**Comment by vadimcn** [comment]
mingw32/mingwex are not gcc runtime, they are more of a C runtime.  They seem to contain some startup code for libc, as well as implementations of some unix-y libc functions that msvcrt does not provide.  In short, as long as we link in mingw's libc, it won't be easy to drop them.

**Comment by alexcrichton** [comment]
Some discussion on IRC [here](https://botbot.me/mozilla/rust-internals/2015-11-09/?msg=53793315&page=7), the conclusion of which I believe was that due to us including `mingwex` and `mingw32` that we'll want to stick with libgcc for now as they're gcc-generated and may end up requiring more fiddly bits in the future. Does that sound right @vadimcn?

**Comment by vadimcn** [comment]
I'd be more worried about C libs we depend upon like jemalloc or miniz.
But ok, I agree that replacing lingcc is not urgent, so let's table this for now.

**Pull request closed without merging**
