### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by workingjubilee**
Successful merges:

 - #124101 (Add PidFd::{kill, wait, try_wait})
 - #126125 (Improve conflict marker recovery)
 - #126481 (Add `powerpc-unknown-openbsd` maintaince status)
 - #126613 (Print the tested value in int_log tests)
 - #126617 (Expand `avx512_target_feature` to include VEX variants)
 - #126707 (Pass target to inaccessible-temp-dir rmake test)
 - #126712 (Migrate `relocation-model`, `error-writing-dependencies` and `crate-name-priority` `run-make` tests to rmake)
 - #126757 (Properly gate `safe` keyword in pre-expansion)
 - #126758 (Do not allow safe/unsafe on static and fn items)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=124101,126125,126481,126613,126617,126707,126712,126757,126758)

### CODE REVIEW

**Comment by tgross35** [comment]
Looks like there might be a race between https://github.com/rust-lang/rust/pull/126758 and https://github.com/rust-lang/rust/pull/126757

**Comment by workingjubilee** [comment]
Pushing errs's through first since it's scheduled for backport.

**Comment by workingjubilee** [comment]
feel a bit silly I didn't check whether this passed CI but :face_with_spiral_eyes:

**Pull request closed without merging**
