### PR TITLE
Update compiler-builtins

### PR DESCRIPTION
**Pull request by tamird**
~~I can't tell if this was ever used, but it's not used today.~~

See commits.

### CODE REVIEW

**Comment by tamird** [comment]
Pushed another commit - can I get another approval?

**Comment by nikomatsakis** [comment]
@tamird do you see the travis failures? I can't tell if they are legit or not, but they definitely seem related to the builtins code.

Also, I'm confused about the change to double quotes -- is that an unrelated change?

**Comment by tamird** [comment]
@nikomatsakis yeah, I think the failures have to do with compiler-builtins being updated to pick up https://github.com/rust-lang-nursery/compiler-builtins/pull/188, which picked up a bunch of other stuff. I'll dig in a little deeper today or tomorrow.

The second commit is unrelated, just a drive-by as the single quotes were confusing my IDE's TOML parser (and single quotes aren't used anywhere else).

**Comment by tamird** [comment]
I was wrong! rustbuild is still used. I'll update this PR to just bump compiler-builtins after https://github.com/rust-lang-nursery/compiler-builtins/pull/189 lands.

**Comment by tamird** [comment]
Ready for another look!

**Comment by alexcrichton** [comment]
@bors: retry 

* s3 outage

**Pull request merged**
