### PR TITLE
Introduce max_by/min_by on iterators

### PR DESCRIPTION
**Pull request by phimuemue**
See https://github.com/rust-lang/rfcs/issues/1722 for reference.

It seems that there is `min`, `max` (simple computation of min/max), `min_by_key`, `max_by_key` (min/max by comparing mapped values) but no `min_by` and `max_by` (min/max according to comparison function). However, e.g. on vectors or slices there is `sort`, `sort_by_key` and `sort_by`.

### CODE REVIEW

**Comment by sfackler** [comment]
cc @rust-lang/libs 

Since these are pretty clearly following the conventions used else where like sort, I'd like to just land these immediately stable. Thoughts?

**Comment by alexcrichton** [comment]
Implementation looks good to me. I'd still prefer to land as unstable, but we could move it to FCP this cycle

**Comment by phimuemue** [comment]
Hi, thanks for the feedback. Seems that I did not pay enough attention to the output last time, so I added two `#![feature]` declarations and ran `make check`, which outputted `11137 passed; 0 failed; 117 ignored; 0 measured`.

Regarding stable/unstable: Do I have to take action? Is the annotation I used correct?

**Comment by alexcrichton** [comment]
For now unstable is fine, although we'll want to open an issue on this repository rather than the rust-lang/rfcs repository and point the `issue` number to that, but we can do that just before landing as well.

**Comment by brson** [comment]
@phimuemue please update the issue number in the stability attributes to use https://github.com/rust-lang/rust/issues/36105 instead of the RFC issue.

**Comment by phimuemue** [comment]
@brson Do you think that my last commit (changing 1722 to 36015 in the comments) actually caused the build to suddenly fail?

**Comment by brson** [comment]
@phimuemue Nope. There's an unrelated issue with the travis configuration presently.

@bors r+

**Pull request merged**
