### PR TITLE
Avoid clone in `Comments::next`

### PR DESCRIPTION
**Pull request by nnethercote**
`Comments::next`, in `rustc_ast_pretty`, has this comment:
```
// FIXME: This shouldn't probably clone lmao
```
The obvious thing to try is to return `Option<&Comment>` instead of `Option<Comment>`. But that leads to multiple borrows all over the place, because `Comments` must be borrowed from `PrintState` and then processed by `&mut self` methods within `PrintState`.

This PR instead rearranges things so that comments are consumed as they are used, preserving the `Option<Comment>` return type without requiring any cloning.

r? @compiler-errors

### CODE REVIEW

**Comment by nnethercote** [comment]
cc @fee1-dead

**Review by compiler-errors — APPROVED** [review]
🆒

**Comment by workingjubilee** [comment]
...failed to download tidy-html?
Let's try again.
@bors retry

**Comment by nnethercote** [comment]
Clearly another CI issue.

@bors retry

**Pull request merged**
