### PR TITLE
Work around pointer aliasing issue in Vec::extend_from_slice, extend_with_element

### LINKED ISSUE #17844: Vec::clone and String::clone are very slow
Platform: Windows, rust nightly.

The optimizations made to fix https://github.com/rust-lang/rust/issues/13472 appear to have been undone by https://github.com/rust-lang/rust/pull/15471 and https://github.com/rust-lang/rust/commit/3316b1eb7c3eb520896af489dd45c4d17190d0a8

In 32-bit mode, `rustc -O --test test.rs && ./test --bench` gives:
```
running 7 tests
test clone_str                  ... bench:   1540862 ns/iter (+/- 25433)
test clone_vec_from_fn          ... bench:    745343 ns/iter (+/- 7535)
test clone_vec_from_incremental ... bench:   1088468 ns/iter (+/- 5358)
test fast_clone_vec             ... bench:    310484 ns/iter (+/- 3212)
test memory_copy                ... bench:    102162 ns/iter (+/- 1220)
test naive_clone_vec            ... bench:    745599 ns/iter (+/- 8111)
```
With ~~`-C target-cpu=x86-64`~~ SSE enabled (`-C target-feature=+sse2`), things look better but `String::clone` still stands out:
```
running 7 tests
test clone_str                  ... bench:   1661609 ns/iter (+/- 60586)
test clone_vec_from_fn          ... bench:    359253 ns/iter (+/- 202820)
test clone_vec_from_incremental ... bench:    357418 ns/iter (+/- 3406)
test fast_clone_vec             ... bench:    309973 ns/iter (+/- 9762)
test memory_copy                ... bench:    102129 ns/iter (+/- 1317)
test naive_clone_vec            ... bench:    753919 ns/iter (+/- 8473)
```

Performance seems very dependent on minor details: `clone_vec_from_incremental` is much slower than `clone_vec_from_fn` in ~~32 bit~~ non-SSE mode.

Benchmark program:
```rust
extern crate test;
extern crate core;

use test::{Bencher, black_box};
use core::ptr;

static SIZE: uint = 1024*1024;

#[bench]
fn clone_str(bh: &mut Bencher) {
    let mut x = String::with_capacity(SIZE);
    for _ in range(0, SIZE) {
        x.push('x');
    }
    bh.iter(|| black_box(x.clone()));
}

#[bench]
fn clone_vec_from_incremental(bh: &mut Bencher) {
    let mut x: Vec<u8> = Vec::with_capacity(SIZE);
    for _ in range(0, SIZE) {
        x.push(0x78);
    }
    bh.iter(|| black_box(x.clone()));
}

#[bench]
fn clone_vec_from_fn(bh: &mut Bencher) {
    let x: Vec<u8> = Vec::from_fn(SIZE, |_| 0x78);
    bh.iter(|| black_box(x.clone()));
}

#[bench]
fn naive_clone_vec(bh: &mut Bencher) {
    let x: Vec<u8> = Vec::from_fn(SIZE, |_| 0x78);
    bh.iter(|| {
        black_box(Vec::from_fn(SIZE, |i| x[i]));
    });
}

#[bench]
fn fast_clone_vec(bh: &mut Bencher) {
    let x: Vec<u8> = Vec::from_fn(SIZE, |_| 0x78);
    bh.iter(|| {
        let mut copy = Vec::<u8>::with_capacity(SIZE);
        unsafe {
            ptr::copy_memory(copy.as_mut_ptr(), x.as_ptr(), x.len());
            copy.set_len(SIZE);
        }
        black_box(copy)
    });
}

#[bench]
fn memory_copy(bh: &mut Bencher) {
    let x: Vec<u8> = Vec::from_fn(SIZE, |_| 0x78);
    let mut y: Vec<u8> = Vec::from_fn(SIZE, |_| 0);
    bh.iter(|| {
        unsafe {
            ptr::copy_memory(y.as_mut_ptr(), x.as_ptr(), x.len());
        }
    })
}
```

### LINKED ISSUE #32155: Nightly performance issue with vec::extend_with_element
When compiling [this program](https://github.com/keeperofdakeys/Process-Query) with nightly and beta, the runtime increases by 1/3, and perf reports that "vec::Vec$LT$T$GT$::extend_with_element::..." is taking 20% of the runtime. This doesn't occur with the stable compiler.

Are there any tools, or perf options, that I can use to further debug this?

### LINKED ISSUE #33518: Performance issue in `write_all` (`Vec::extend_from_slice`)
Hi folks. Chatted a bit on IRC, seemed to think this wasn't obviously a dup, so reporting here.

I'm using `write_all` to push some bytes into a buffer. If I do this in-line, all goes well performance-wise (memcpy speeds; about 50GB/s on my machine). If I put it in a method, even with a `#[inline(always)]` attribute, it drops down to about 1GB/s (and assembly looks like a loop doing something).

The problem goes away if I don't push the leading 24 bytes on using `write_all`. Meaning, if I don't push them on, great! If I call `push(0u8);` 24 times, also great! Something about the existence of the preceding `write_all` seems to tank the perf of the second `write_all` (the big one). If I push 32 bytes (i.e. use a `&[0u8; 32]`) the problem goes away as well (quadword alignment?). 

But there never seems to be a problem with the manually inlined code; it always goes nice and fast.

```rust
extern crate time;

use std::io::Write;

fn main() {
	
    let dataz = vec![0u8; 1 << 20];
    let mut bytes = Vec::new();

    let rounds = 1_000;
    let start = time::precise_time_ns();

    for _ in 0..rounds {
        bytes.clear();

        // these two: "average time: 81135"
        // bytes.write_all(&[0u8; 24]).unwrap();
        // bytes.write_all(&dataz[..]).unwrap();

        // this one: "average time: 530736"
        test(&dataz, &mut bytes)
    }

    println!("average time: {:?}", (time::precise_time_ns() - start) / rounds);

}

#[inline(always)]
fn test(typed: &Vec<u8>, bytes: &mut Vec<u8>) {
    // comment first line out to go fast!
    // weirdly, to me: if you replace the first line with 24x `bytes.push(0u8)` you get good performance.
    bytes.write_all(&[0u8; 24]).unwrap();
    bytes.write_all(&typed[..]).unwrap();
}
```

**Edit**: stable, beta, and nightly.

### PR DESCRIPTION
**Pull request by bluss**
Due to missing noalias annotations for &mut T in general (issue #31681),
in larger programs extend_from_slice and extend_with_element may both
compile very poorly. What is observed is that the .set_len() calls are
not lifted out of the loop, even for `Vec<u8>`.

Use a local length variable for the Vec length instead, and use a scope
guard to write this value back to self.len when the scope ends or on
panic. Then the alias analysis is easy.

This affects extend_from_slice, extend_with_element, the vec![x; n]
macro, Write impls for Vec<u8>, BufWriter, etc (but may / may not
have triggered since inlining can be enough for the compiler to get it right).

Fixes #32155
Fixes #33518 
Closes #17844

### CODE REVIEW

**Comment by bluss** [comment]
Verified that it fixes the two issues. (More or less by finding programs that exhibit the regression behavior, and then that the new version fixes it).

**Comment by bluss** [comment]
Adding fixes  #17844 since Vec::clone uses extend_from_slice

**Comment by alexcrichton** [comment]
@bors: r+ 765700ba7a3743b9af5cb12092ea1293dbe07068

Nice catch!

**Comment by bluss** [comment]
Thanks. I'm thrilled to see this fixed.

**Pull request merged**
