### PR TITLE
Ignore proc-macros when assembling rustc libdir

### LINKED ISSUE #80294: rustc is distributed with unnecessary? procedural macros ~60 MB
```console
$ cd ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
$ ls -s -S --si 
total 282M
121M librustc_driver-54c3daf069bcd3f6.so
 94M libLLVM-11-rust-1.50.0-nightly.so
 15M libserde_derive-026483cb77a7c305.so
 15M librustc_macros-5f0ec4a119c6ac86.so
 15M libchalk_derive-0685d79833dc9b2b.so
 14M libtracing_attributes-e4be92c35ab2a33b.so
8,3M libstd-25c6acf8063a3802.so
2,6M libtest-57470d2aa8f7aa83.so
4,1k rustlib/

$ rm libserde_derive-*.so librustc_macros-*.so libchalk_derive-*.so libtracing_attributes-*.so
$ ls -s -S --si
total 224M
...
```

### PR DESCRIPTION
**Pull request by tmiasko**
Fixes #80294.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I just re-read the explanation of dual proc macros - https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/-Z.20dual-proc-macros.

cc @petrochenkov 

I think this should be fine, presuming my model that $sysroot/lib/ exists only for runtime linkage of rustc (and tool) binaries is accurate. The proc macro libraries dropped by this PR are currently still needed in the $sysroot/lib/rustlib/$host/lib _and_ $sysroot/lib/rustlib/$target/lib when cross-compiling plugins/drivers from $host to $target, but $sysroot/lib should not be in the compiler's search path at that time I believe (but am somewhat unsure). AFAICT, this PR should not change the contents of the rustlib directory.

**Comment by petrochenkov** [comment]
I more or less remember why `-Zdual-proc-macros` are necessary, but have very little idea of how they maps on files and directories in Rust distribution, and which of those files are affected by this patch.

If both proc-macros-for-target and proc-macros-for-host were previously shipped together with other-artifacts-for-target, and now only proc-macros-for-target are shipped, then it should be ok.

**Comment by petrochenkov** [comment]
In any case, this can be reverted later if something breaks.

**Pull request merged**
