### PR TITLE
Bump boostrap compiler to new beta

### PR DESCRIPTION
**Pull request by BoxyUwU**
Currently failing due to something about the const stability checks and `panic!`. I'm not sure why though since I wasn't able to see any PRs merged in the past few days that would result in a `cfg(bootstrap)` that shouldn't be removed. cc @RalfJung #131349

### CODE REVIEW

**Comment by RalfJung** [comment]
There are some `cfg_attr(bootstrap, ...)` that you did not remove, like here:

https://github.com/rust-lang/rust/blob/6852fd42fbcc431c6f227ccae4fee4481944d240/library/core/src/fmt/mod.rs#L337

Probably it's related to them being broken across multiple lines.

**Comment by BoxyUwU** [comment]
Ah.... yep that would do it. There was some `cfg(not(bootstrap),`  split across multiple lines that i *did* notice but didn't see those. Thanks

**Review by jieyouxu — APPROVED** [review]
Thanks

**Comment by jieyouxu** [comment]
AFAICT this looks good.
@bors r+ rollup=never p=1 (bootstrap compiler bump)

**Comment by BoxyUwU** [comment]
@bors retry

spurrious issue i hope?

**Comment by BoxyUwU** [comment]
not spurious :^)

**Comment by RalfJung** [comment]
Seems like it's a cargo test that failed?
Cc @rust-lang/cargo

**Comment by weihanglo** [comment]
The nightly `CARGO_RUSTC_CURRENT_DIR` environment variable has been removed. Cargo needs to adjust [this hack](https://github.com/rust-lang/cargo/blob/81e0670dddefc0b78b272e58decc0eea9def3720/.cargo/config.toml#L7-L10) maybe. Let me check.

**Comment by epage** [comment]
We removed that 3 weeks ago (https://github.com/rust-lang/cargo/pull/14799), why is it just now causing problems?

**Comment by weihanglo** [comment]
@BoxyUwU this patch should fix the test failures.

However since it changes bootstrap, I would recommend looping some bootstrap team folks to have a look.

```patch
diff --git a/src/bootstrap/src/core/build_steps/test.rs b/src/bootstrap/src/core/build_steps/test.rs
index dd967bca867..1c24ccc3216 100644
--- a/src/bootstrap/src/core/build_steps/test.rs
+++ b/src/bootstrap/src/core/build_steps/test.rs
@@ -263,12 +263,16 @@ pub struct Cargo {
     host: TargetSelection,
 }
 
+impl Cargo {
+    const CRATE_PATH: &str = "src/tools/cargo";
+}
+
 impl Step for Cargo {
     type Output = ();
     const ONLY_HOSTS: bool = true;
 
     fn should_run(run: ShouldRun<'_>) -> ShouldRun<'_> {
-        run.path("src/tools/cargo")
+        run.path(Self::CRATE_PATH)
     }
 
     fn make_run(run: RunConfig<'_>) {
@@ -286,7 +290,7 @@ fn run(self, builder: &Builder<'_>) {
             Mode::ToolRustc,
             self.host,
             Kind::Test,
-            "src/tools/cargo",
+            Self::CRATE_PATH,
             SourceType::Submodule,
             &[],
         );
@@ -301,6 +305,9 @@ fn run(self, builder: &Builder<'_>) {
         // those features won't be able to land.
         cargo.env("CARGO_TEST_DISABLE_NIGHTLY", "1");
         cargo.env("PATH", path_for_cargo(builder, compiler));
+        // Cargo's test tsuite requires configurations from its own `.cargo/config.toml`.
+        // Change to the directory so Cargo can read from it.
+        cargo.current_dir(builder.src.join(Self::CRATE_PATH));
 
         #[cfg(feature = "build-metrics")]
         builder.metrics.begin_test_suite(
```

**Comment by Mark-Simulacrum** [comment]
Cargo patch looks fine to me.

**Pull request merged**
