### PR TITLE
Windows implementation of feature `path_try_exists`

### PR DESCRIPTION
**Pull request by ChrisDenton**
Draft of a Windows implementation of `try_exists` (#83186).

The first commit reorganizes the code so I would be interested to get some feedback on if this is a good idea or not. It moves the `Path::try_exists` function to `fs::exists`. leaving the former as a wrapper for the latter. This makes it easier to provide platform specific implementations and matches the `fs::metadata` function.

The other commit implements a Windows specific variant of `exists`. I'm still figuring out my approach so this is very much a first draft. Eventually this will need some more eyes from knowledgable Windows people.

### CODE REVIEW

**Comment by yaahc** [comment]
Hey @ChrisDenton, thank you for the PR and I'm sorry for the slow reply. I've taken a look, and admittedly I'm no Windows expert, but everything here looks good to me. I really appreciate the comments btw, they made reviewing this PR much easier. For a real Windows expert you could try asking on Zulip (in [#t-libs](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs) or [#t-compiler/windows](https://rust-lang.zulipchat.com/#narrow/stream/242869-t-compiler.2Fwindows)) first. If that doesn't work, we can ping a few Windows experts on GitHub here.

**Comment by ChrisDenton** [comment]
@yaahc No worries, I'm not in a rush! I've asked in the Windows group if someone wouldn't mind taking a look. I think there are a few changes I'd like to make but I'd prefer to wait for a second opinion first.

**Comment by ChrisDenton** [comment]
A Microsoft engineer expressed the concern that using `GetFileAttributesW` as an optimization relied on OS implementation details that may change. So I've simplified the second commit to merely try opening the file. The first commit remains the same.

I think this is now ready for review.

**Comment by yaahc** [comment]
Looks good, thank you.

@bors r+

**Comment by RalfJung** [comment]
Failed in rollup:
https://github.com/rust-lang/rust/pull/85483#issuecomment-844497789
@bors r- rollup=iffy

**Comment by ChrisDenton** [comment]
Oh, sorry. I made a silly mistake there. I didn't catch it locally because I wasn't testing a target with an unsupported `std::fs`. I'll push a fix soon.

**Comment by ijackson** [comment]
@ChrisDenton Hi.  I'm doing some work on `io::ErrorKind` in #79965 which involved adding many more Windows error codes.  My bulk import (from mingw) discovered that your definition of `ERROR_SHARING_VIOLATION` specified `u32` rather than `DWORD`.

I think this was just a slip on your part, so I adjust that in my branch.  If that was deliberate then please come over to #79965 and comment on https://github.com/rust-lang/rust/pull/79965/commits/e2bd0d0e6218051c07edef4a74c484f214262647

Thanks :-).

**Comment by ChrisDenton** [comment]
@ijackson That was indeed a slip on my part and I'm glad you caught it!

**Comment by ijackson** [comment]
> @ijackson That was indeed a slip on my part and I'm glad you caught it!

No problem.  They're the same type underneath anyway.  Thanks.

**Pull request merged**
