### PR TITLE
Reinstate the `hir-stats.rs` tests on stage 1.

### PR DESCRIPTION
**Pull request by nnethercote**
r? @the8472

### CODE REVIEW

**Comment by jyn514** [comment]
It seems unfortunate to have tests that aren't run in CI ... is there a reason we shouldn't keep `// ignore-stage1` here permanently?

**Comment by nnethercote** [comment]
I think `ignore-stage1` should be avoided as much as possible. It's annoying to run `x test tests/ui` and everything passes and you think you're good and then you realize much later that an `ignore-stage1` test was skipped and fails with stage 2.

**Pull request merged**
