### PR TITLE
std: Implement io traits for io::Cursor of Vec references

### PR DESCRIPTION
**Pull request by ruuda**
For example, `io::Cursor<&Vec<u8>>` did not implement `io::Read`, whereas `io::Cursor<Vec<u8>>` did. There might be a good reason for this that I missed, but it is not impossible as this PR demonstrates.

Constructing a cursor from a reference is useful when you already have the vector. You can temporarily wrap it in a cursor to read from it or write to it, and continue using the vector when the cursor goes out of scope. There is no need to call `into_inner`.

I don’t know what the procedure is for stability attributes, so I did not add them yet.

r? @aturon

### CODE REVIEW

**Comment by bluss** [comment]
You could use `Cursor<&[u8]>` and similar, right?

**Comment by ruud-v-a** [comment]
For reading, yes, but for writing, no, because `&mut [u8]` cannot grow, and `&mut Vec<u8>` can.

**Comment by bluss** [comment]
Ah but &mut Vec<u8> doesn't need a cursor (its length is the cursor).

**Comment by ruud-v-a** [comment]
It does if you want it to be `Seek + Write`.

**Comment by alexcrichton** [comment]
Due to the way stability of trait implementations works, we'd be forced to mark all these with `#[stable(feature = "...", since = "1.1.0")]` (in terms of stability attributes), and I agree with @bluss that `&Vec<u8>` is probably too similar to `&[u8]` to add for now.

**Comment by Gankro** [comment]
@alexcrichton Should this be closed?

**Comment by alexcrichton** [comment]
@Gankro ah yes this has gone a little stale, so I think I'll close this for now. We can always continue to explore these options in the future though!

**Pull request closed without merging**
