### PR TITLE
Additional doc links and explanation of `Wake`.

### PR DESCRIPTION
**Pull request by kpreid**
This is intended to clarify:

* That `Wake` exists and can be used instead of `RawWaker`.
* How to construct a `Waker` when you are looking at `Wake` (which was previously only documented in the example).

### CODE REVIEW

**Comment by scottmcm** [comment]
I'm waker-ignorant, so re-rolling in hopes of getting someone more qualified:
r? libs

**Comment by kpreid** [comment]
The broken link checker seems to be giving a false positive — the link works in generated docs.

**Comment by kpreid** [comment]
Re-requesting review because of lack of response for 6 weeks.

r? libs

**Comment by thomcc** [comment]
I'm going to be away for a few months, so I'm rerolling my PRs so that folks don't have to wait for me. Sorry/thanks.

r? libs

**Comment by cuviper** [comment]
The addition looks fine to me, but the link checker is going to need to be fixed or otherwise convinced. Have you followed up on that at all?

**Comment by kpreid** [comment]
> The addition looks fine to me, but the link checker is going to need to be fixed or otherwise convinced. Have you followed up on that at all?

To be honest, I was hoping someone would come along with “Oh, you just have to format it like so…”

To unblock this improvement to the docs, I've removed the link (except for a comment about why it doesn't exist).

**Pull request merged**
