### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #128596 (stabilize const_fn_floating_point_arithmetic)
 - #129199 (make writes_through_immutable_pointer a hard error)
 - #129246 (Retroactively feature gate `ConstArgKind::Path`)
 - #129290 (Pin `cc` to 1.0.105)
 - #129323 (Implement `ptr::fn_addr_eq`)
 - #129500 (remove invalid `TyCompat` relation for effects)
 - #129501 (panicking: improve hint for Miri's RUST_BACKTRACE behavior)
 - #129505 (interpret: ImmTy: tighten sanity checks in offset logic)
 - #129509 (Add a hack to workaround MSVC CI issues)
 - #129510 (Fix `elided_named_lifetimes` in code)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=128596,129199,129246,129290,129323,129500,129501,129505,129509,129510)

### CODE REVIEW

**Comment by jieyouxu** [comment]
😭

**Comment by ChrisDenton** [comment]
Hm, must have been a fluke that it worked in my tests. At least it ruled out another option I guess.

**Pull request closed without merging**
