### PR TITLE
Update cmake, cc and compiler_builtins for VS 2019 support

### PR DESCRIPTION
**Pull request by Zoxc**
r? @alexcrichton

### CODE REVIEW

**Comment by Centril** [comment]
@bors p=10

Raising above rollup todo.

**Comment by Manishearth** [comment]
@bors retry

yielding priority to clippy PR

**Comment by Manishearth** [comment]
@bors retry

Yield priority to clippy PR which blocks the beta

**Comment by Zoxc** [comment]
@alexcrichton Is this a `cc-rs` regression?

**Comment by Manishearth** [comment]
@bors retry

Tree closed due to Travis osx being slow

**Comment by Zoxc** [comment]
We also build test helpers even when not needed. No idea how that worked before.

**Comment by Zoxc** [comment]
Ping @alexcrichton

**Pull request merged**
