### PR TITLE
Explicitly link kernel32.lib from alloc

### PR DESCRIPTION
**Pull request by ChrisDenton**

### CODE REVIEW

**Comment by klensy** [comment]
There is some reason for it, yes? :-)

**Comment by bjorn3** [comment]
https://github.com/rust-lang/backtrace-rs/pull/482 is a similar PR to backtrace-rs. The following reasons are listed there:

> Currently backtrace depends on something else to link `kernel32.lib`, which is usually a safe assumption. However, it may become more of a problem once [raw-dylib](https://doc.rust-lang.org/beta/unstable-book/language-features/raw-dylib.html) is stable and used by the standard library and other crates.
>
> Using `#[link]` also allows calling into the function directly instead of going through a jump stub.

**Comment by ChrisDenton** [comment]
Yes, sorry for being terse. That last reason is also why `sys/windows/c.rs` was changed to have `#[link]` attributes on the `extern` blocks. For people familiar with MSVC C/C++ this makes the imported functions have the equivalent of `dllimport` .

**Comment by thomcc** [comment]
Looks fine. Initially I thought this meant `liballoc` which I'd have been opposed to.

@bors r+ rollup

**Pull request merged**
