### PR TITLE
Correct typo for 'underyling'

### PR DESCRIPTION
**Pull request by duaneedwards**

### CODE REVIEW

**Comment by Gankro** [comment]
Nailed It :+1: 

@bors r+ 9c686 rollup

I can't spell, so I'm gonna be *super* embarrassed if this PR is actually wrong.

**Comment by Gankro** [comment]
Basically what I'm saying is I'm putting my reputation on the line for you, kid.

Don't let me down.

:cold_sweat:

**Comment by duaneedwards** [comment]
Hahaha, that made me second guess the change a little, but I'm pretty confident in the change after double checking now :-)

**Comment by kmcallister** [comment]
@Gankro you have my ~~underyling~~ ~~underlying~~ undying gratitude.

**Pull request merged**
