### PR TITLE
Fix equivalent string in escape_default docs

### PR DESCRIPTION
**Pull request by mernen**
This newline should be escaped.

### CODE REVIEW

**Comment by ehuss** [comment]
Oh, @Centril you need to delegate=ehuss when you assign me.

**Comment by Centril** [comment]
@bors delegate=ehuss

@pietroalbini Can you give @ehuss r+ rights?

**Comment by pietroalbini** [comment]
> @pietroalbini Can you give @ehuss r+ rights?

I'm not the one who should decide who gets r+ perms... Ask the compiler team.

**Comment by Centril** [comment]
@rust-lang/compiler ^-- asking you =P

**Pull request merged**
