### PR TITLE
Stabilize `isqrt` feature

### LINKED ISSUE #116226: Tracking Issue for `{u8,i8,...}::isqrt`
Feature gate: `#![feature(isqrt)]`

This is a tracking issue for the functions `{u8,u16,u32,u64,i128,usize}::isqrt` and `{i8,i16,i32,i64,i128,isize}::{isqrt,checked_isqrt}`, which compute the [integer square root](https://en.wikipedia.org/wiki/Integer_square_root), addressing issue #89273.

### Public API

For every suffix `N` among `8`, `16`, `32`, `64`, `128` and `size`, the feature `isqrt` introduces the methods

```rust
const fn uN::isqrt() -> uN;
const fn iN::isqrt() -> iN;
const fn iN::checked_isqrt() -> Option<iN>;
```

<details>
<summary>Expand to see the full API</summary>

```rust
const fn u8::isqrt() -> u8;
const fn i8::isqrt() -> i8;
const fn i8::checked_isqrt() -> Option<i8>;


const fn u16::isqrt() -> u16;
const fn i16::isqrt() -> i16;
const fn i16::checked_isqrt() -> Option<i16>;


const fn u32::isqrt() -> u32;
const fn i32::isqrt() -> i32;
const fn i32::checked_isqrt() -> Option<i32>;


const fn u64::isqrt() -> u64;
const fn i64::isqrt() -> i64;
const fn i64::checked_isqrt() -> Option<i64>;


const fn u128::isqrt() -> u128;
const fn i128::isqrt() -> i128;
const fn i128::checked_isqrt() -> Option<i128>;


const fn usize::isqrt() -> usize;
const fn isize::isqrt() -> isize;
const fn isize::checked_isqrt() -> Option<isize>;
```
</details>

### Steps / History

- Forum discussion history:
  -  https://users.rust-lang.org/t/u32-integer-square-root/86909/2?u=scottmcm
  - https://users.rust-lang.org/t/integer-square-root-algorithm/13529/5?u=scottmcm
- [x] Implementation: #116176
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by ChaiTRex**
Stabilizes the `isqrt` feature. FCP is incomplete.

Closes #116226

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval

**Comment by RalfJung** [comment]
Looks good from a const-eval perspective. :)

**Review by scottmcm — APPROVED** [review]
Looks good once an FCP happens
r? @scottmcm

**Comment by tgross35** [comment]
FCP complete https://github.com/rust-lang/rust/issues/116226#issuecomment-2440914095

@bors r=scottmcm,tgross35 rollup

**Pull request merged**
