### PR TITLE
Debug #48116.

### PR DESCRIPTION
**Pull request by kennytm**
1. When the invalid condition is hit, write out the relevant variables too
2. In compile-fail/parse-fail tests, check for ICE first, so the invalid error patterns won't mask our ICE output.

r? @alexcrichton 
cc #48116, cc @eddyb

### CODE REVIEW

**Comment by estebank** [comment]
@kennytm Needs rebase.

**Comment by kennytm** [comment]
Okay okay

**Comment by kennytm** [comment]
Perfect, hit #48116 😂 

<details>

```
[01:51:01] failures:
[01:51:01] 
[01:51:01] ---- [compile-fail] compile-fail/rfc-2126-extern-in-paths/single-segment.rs stdout ----
[01:51:01] 	
[01:51:01] error: compiler encountered internal error
[01:51:01] status: exit code: 101
[01:51:01] command: "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/bin/rustc" "/Users/travis/build/rust-lang/rust/src/test/compile-fail/rfc-2126-extern-in-paths/single-segment.rs" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail" "--target=x86_64-apple-darwin" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail/rfc-2126-extern-in-paths/single-segment.stage2-x86_64-apple-darwin" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail/rfc-2126-extern-in-paths/single-segment.stage2-x86_64-apple-darwin.aux" "-A" "unused"
[01:51:01] stdout:
[01:51:01] ------------------------------------------
[01:51:01] 
[01:51:01] ------------------------------------------
[01:51:01] stderr:
[01:51:01] ------------------------------------------
[01:51:01] {"message":"unresolved import `extern::*`","code":{"code":"E0432","explanation":"\nAn import was unresolved.\n\nErroneous code example:\n\n```compile_fail,E0432\nuse something::Foo; // error: unresolved import `something::Foo`.\n```\n\nPaths in `use` statements are relative to the crate root. To import items\nrelative to the current and parent modules, use the `self::` and `super::`\nprefixes, respectively. Also verify that you didn't misspell the import\nname and that the import exists in the module from where you tried to\nimport it. Example:\n\n```\nuse self::something::Foo; // ok!\n\nmod something {\n    pub struct Foo;\n}\n# fn main() {}\n```\n\nOr, if you tried to use a module from an external crate, you may have missed\nthe `extern crate` declaration (which is usually placed in the crate root):\n\n```\nextern crate core; // Required to use the `core` crate\n\nuse core::any;\n# fn main() {}\n```\n"},"level":"error","spans":[{"file_name":"/Users/travis/build/rust-lang/rust/src/test/compile-fail/rfc-2126-extern-in-paths/single-segment.rs","byte_start":620,"byte_end":629,"line_start":17,"line_end":17,"column_start":5,"column_end":14,"is_primary":true,"text":[{"text":"use extern::*; //~ ERROR unresolved import `extern::*`","highlight_start":5,"highlight_end":14}],"label":"cannot glob-import all possible crates","suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error[E0432]: unresolved import `extern::*`\n  --> /Users/travis/build/rust-lang/rust/src/test/compile-fail/rfc-2126-extern-in-paths/single-segment.rs:17:5\n   |\n17 | use extern::*; //~ ERROR unresolved import `extern::*`\n   |     ^^^^^^^^^ cannot glob-import all possible crates\n\n"}
[01:51:01] thread 'rustc' panicked at 'librustc_resolve/resolve_imports.rs:1040: invalid name `::extern` at Span { lo: BytePos(525), hi: BytePos(531), ctxt: #0 }; global = false, names = [], subclass = SingleImport { target: extern#0, source: extern#0, result: PerNS { value_ns: Cell { value: Err(Determined) }, type_ns: Cell { value: Err(Determined) }, macro_ns: None }, type_ns_only: false }', librustc/session/mod.rs:1180:26
[01:51:01] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:51:01] 
[01:51:01] error: internal compiler error: unexpected panic
[01:51:01] 
[01:51:01] note: the compiler unexpectedly panicked. this is a bug.
[01:51:01] 
[01:51:01] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[01:51:01] 
[01:51:01] note: rustc 1.25.0-dev running on x86_64-apple-darwin
[01:51:01] 
[01:51:01] 
[01:51:01] ------------------------------------------
[01:51:01] 
[01:51:01] thread '[compile-fail] compile-fail/rfc-2126-extern-in-paths/single-segment.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2883:9
[01:51:01] 
[01:51:01] ---- [compile-fail] compile-fail/use-keyword.rs stdout ----
[01:51:01] 	
[01:51:01] error: compiler encountered internal error
[01:51:01] status: exit code: 101
[01:51:01] command: "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/bin/rustc" "/Users/travis/build/rust-lang/rust/src/test/compile-fail/use-keyword.rs" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail" "--target=x86_64-apple-darwin" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail/use-keyword.stage2-x86_64-apple-darwin" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail/use-keyword.stage2-x86_64-apple-darwin.aux" "-A" "unused"
[01:51:01] stdout:
[01:51:01] ------------------------------------------
[01:51:01] 
[01:51:01] ------------------------------------------
[01:51:01] stderr:
[01:51:01] ------------------------------------------
[01:51:01] {"message":"`self` imports are only allowed within a { } list","code":{"code":"E0429","explanation":"\nThe `self` keyword cannot appear alone as the last segment in a `use`\ndeclaration.\n\nErroneous code example:\n\n```compile_fail,E0429\nuse std::fmt::self; // error: `self` imports are only allowed within a { } list\n```\n\nTo use a namespace itself in addition to some of its members, `self` may appear\nas part of a brace-enclosed list of imports:\n\n```\nuse std::fmt::{self, Debug};\n```\n\nIf you only want to import the namespace, do so directly:\n\n```\nuse std::fmt;\n```\n"},"level":"error","spans":[{"file_name":"/Users/travis/build/rust-lang/rust/src/test/compile-fail/use-keyword.rs","byte_start":634,"byte_end":643,"line_start":16,"line_end":16,"column_start":13,"column_end":22,"is_primary":true,"text":[{"text":"        use self as A;","highlight_start":13,"highlight_end":22}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error[E0429]: `self` imports are only allowed within a { } list\n  --> /Users/travis/build/rust-lang/rust/src/test/compile-fail/use-keyword.rs:16:13\n   |\n16 |         use self as A;\n   |             ^^^^^^^^^\n\n"}
[01:51:01] thread 'rustc' panicked at 'librustc_resolve/resolve_imports.rs:1040: invalid name `::super` at Span { lo: BytePos(726), hi: BytePos(736), ctxt: #0 }; global = false, names = [], subclass = SingleImport { target: B#0, source: super#0, result: PerNS { value_ns: Cell { value: Err(Determined) }, type_ns: Cell { value: Err(Determined) }, macro_ns: None }, type_ns_only: false }', librustc/session/mod.rs:1180:26
[01:51:01] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:51:01] 
[01:51:01] error: internal compiler error: unexpected panic
[01:51:01] 
[01:51:01] note: the compiler unexpectedly panicked. this is a bug.
[01:51:01] 
[01:51:01] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[01:51:01] 
[01:51:01] note: rustc 1.25.0-dev running on x86_64-apple-darwin
[01:51:01] 
[01:51:01] 
[01:51:01] ------------------------------------------
[01:51:01] 
[01:51:01] thread '[compile-fail] compile-fail/use-keyword.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2883:9
[01:51:01] 
[01:51:01] ---- [compile-fail] compile-fail/use-mod-2.rs stdout ----
[01:51:01] 	
[01:51:01] error: compiler encountered internal error
[01:51:01] status: exit code: 101
[01:51:01] command: "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/bin/rustc" "/Users/travis/build/rust-lang/rust/src/test/compile-fail/use-mod-2.rs" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail" "--target=x86_64-apple-darwin" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail/use-mod-2.stage2-x86_64-apple-darwin" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/compile-fail/use-mod-2.stage2-x86_64-apple-darwin.aux" "-A" "unused"
[01:51:01] stdout:
[01:51:01] ------------------------------------------
[01:51:01] 
[01:51:01] ------------------------------------------
[01:51:01] stderr:
[01:51:01] ------------------------------------------
[01:51:01] thread 'rustc' panicked at 'librustc_resolve/resolve_imports.rs:1040: invalid name `::self` at Span { lo: BytePos(492), hi: BytePos(496), ctxt: #0 }; global = false, names = [], subclass = SingleImport { target: self#0, source: self#0, result: PerNS { value_ns: Cell { value: Err(Undetermined) }, type_ns: Cell { value: Err(Determined) }, macro_ns: None }, type_ns_only: true }', librustc/session/mod.rs:1180:26
[01:51:01] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:51:01] 
[01:51:01] error: internal compiler error: unexpected panic
[01:51:01] 
[01:51:01] note: the compiler unexpectedly panicked. this is a bug.
[01:51:01] 
[01:51:01] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[01:51:01] 
[01:51:01] note: rustc 1.25.0-dev running on x86_64-apple-darwin
[01:51:01] 
[01:51:01] 
[01:51:01] ------------------------------------------
[01:51:01] 
[01:51:01] thread '[compile-fail] compile-fail/use-mod-2.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2883:9
[01:51:01] 
[01:51:01] 
[01:51:01] failures:
[01:51:01]     [compile-fail] compile-fail/rfc-2126-extern-in-paths/single-segment.rs
[01:51:01]     [compile-fail] compile-fail/use-keyword.rs
[01:51:01]     [compile-fail] compile-fail/use-mod-2.rs
```

</details>

**Comment by eddyb** [comment]
Okay, looks like outer `if names.is_empty()` is broken and enters the `else` for some reason.

**Comment by alexcrichton** [comment]
What I'm curious about is what in the world is nondeterministic to cause this?

**Comment by kennytm** [comment]
Since we've got the reason of failure, I'm transform this PR for debugging.

**Comment by kennytm** [comment]
cancelbot is too aggressive, there should be some way to let cancelbot ignore manual restarts... 😐

**Pull request closed without merging**
