### PR TITLE
Fix typo README.md

### PR DESCRIPTION
**Pull request by LFS6502**
Fix typo README.md 2: Electric Boogaloo
Expands on #131144

### CODE REVIEW

**Comment by fmease** [comment]
Please follow: https://rustc-dev-guide.rust-lang.org/git.html#git-is-trying-to-rebase-commits-i-didnt-write

**Comment by HypheX** [comment]
Yeah, apologies, I'm working on it.

**Comment by HypheX** [comment]
There we go, fixed.

**Comment by fmease** [comment]
I don't know if `tests/ui/README.md` still pulls its weight contrary to the corresponding chapter(s) in the rustc dev guide but well, doesn't matter right now.

Thanks @bors r+ rollup

**Comment by fmease** [comment]
I can reopen and reapprove if you're fine with that -- only if you consent though of course.

**Comment by fmease** [comment]
No worries!

**Pull request merged**
