### PR TITLE
Fix documentation in Cell

### PR DESCRIPTION
**Pull request by joshlf**

### CODE REVIEW

**Comment by JohnCSimon** [comment]
ping from triage:
@joshlf
Returning to you to address build failures and after that, please switch back to `S-waiting-on-review`.
thanks.

@rustbot label: +S-waiting-on-author -S-waiting-on-review

**Comment by joshlf** [comment]
Looks like the issue was a transient network error. I don't believe I have permission to trigger another run?

@rustbot label: -S-waiting-on-author +S-waiting-on-review

**Comment by JohnCSimon** [comment]
> Looks like the issue was a transient network error. I don't believe I have permission to trigger another run?
> 

@joshtriplett  can you help with this?

**Comment by joshtriplett** [comment]
I don't seem to have the button to restart CI on this PR.

I'd suggest doing a commit --amend and then a force-push, which will force CI to re-run.

**Review by JohnTitor — APPROVED** [review]

**Pull request merged**
