### PR TITLE
Make rustdoc not include self-by-value methods from Deref target

### LINKED ISSUE #39550: rustdoc should only include &self methods from Deref target
Currently, if Foo impls Deref<Target=Bar>, then the generated documentation for Foo will include every method defined on Bar, regardless of receiver type. &mut self methods should only be included if DerefMut is impled, and self methods shouldn't be included at all.

It may also be worth excluding methods on the Deref target from the generated documentation if a method of the same name is defined on the original type, since that's the one that will be called under normal circumstances.

### PR DESCRIPTION
**Pull request by fhartwig**
Fixes #39550

### CODE REVIEW

**Comment by kennytm** [comment]
Two rustdoc test cases need to be updated, removing the `count_ones` methods. Or maybe rustdoc should keep the self-by-value methods if the target is `Copy`.

```
[00:56:43] ---- [rustdoc] rustdoc/issue-19190-3.rs stdout ----
[00:56:43] 	
[00:56:43] error: htmldocck failed!
[00:56:43] status: exit code: 1
[00:56:43] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-19190-3.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/issue-19190-3.rs"
[00:56:43] stdout:
[00:56:43] ------------------------------------------
[00:56:43] 
[00:56:43] ------------------------------------------
[00:56:43] stderr:
[00:56:43] ------------------------------------------
[00:56:43] 20: @has check failed
[00:56:43] 	`XPATH PATTERN` did not match
[00:56:43] 	// @has - '//*[@id="method.count_ones"]' 'fn count_ones(self) -> u32'
[00:56:43] 
[00:56:43] Encountered 1 errors
[00:56:43] 
[00:56:43] ------------------------------------------
[00:56:43] 
[00:56:43] failures:
[00:56:43]     [rustdoc] rustdoc/issue-19190-2.rs
[00:56:43]     [rustdoc] rustdoc/issue-19190-3.rs
```

**Comment by QuietMisdreavus** [comment]
What i would suggest to fix the tests, rather than trying to wrangle with Copy, is to instead change the Derefs in those tests to point to String instead, and use `fn as_str(&self) -> &str` and `fn new() -> String` instead. That way the test is still checking for the proper thing. Note that for `issue-19190-3.rs` the Deref impls are actually in `src/test/rustdoc/auxiliary/issue-19190-3.rs` - that test is checking for cross-crate imports.

**Comment by shepmaster** [comment]
We haven't heard from you in a week or so, @fhartwig  — will you have time to address the most recent feedback?

**Comment by fhartwig** [comment]
@shepmaster Sorry for the silence, I've been pretty busy. I should be able to finish this in the next 2-3 days.

**Comment by fhartwig** [comment]
I've rebased the changes and adapted the failing tests as @QuietMisdreavus suggested (thanks!).

Sorry for the delay.

**Comment by QuietMisdreavus** [comment]
@bors r+

Thanks!

**Pull request merged**
