### PR TITLE
Avoid cloning refcounted types during folding 

### PR DESCRIPTION
**Pull request by eggyal**
Addresses FIXME comment created in #78313

r? @lcnr

### CODE REVIEW

**Comment by eggyal** [comment]
Actually I just realised `make_mut` is more concise/appropriate here than `get_mut`.  Shall I force-push or wait for the perf run first?

**Comment by lcnr** [comment]
afaik `Rc` and `Arc` are really rarely used. I think that ideally we would avoid the copy of the inner data (which is actually the costly part, but that requires some more complex (and probably `unsafe`) changes, so I am fine with this as is

@bors delegate

**Comment by eggyal** [comment]
Perhaps the `TypeFoldable::fold_with` methods should mutate in-place rather than take ownership and return a new instance?

**Comment by eggyal** [comment]
> I think that ideally we would avoid the copy of the inner data (which is actually the costly) part, but that requires some more complex (and probably unsafe) changes, so I am fine with this as is

I've pushed a version that avoids those clones if possible.  Can you request that rust-timer do a perf-run?  Then obvs will need a thorough review.  Or else am happy to roll back to the previous version.

**Review by lcnr — COMMENTED** [review]
alright, the impl looks good to me.

Please add some comments to explain what's going on here though.

I think that in the lines
```rust
let mut unique = Rc::from_raw(Rc::into_raw(self).cast());
```
it makes sense to explicitly mention the type of `unique` somewhere, either in `Rc::<...>::from_raw`, in `cast::<...>` or as the type of `unique` itself. Same for `Arc`.

r=me with some helpful comments

**Comment by lcnr** [comment]
good comments :heart:

**Pull request merged**
