### PR TITLE
Improve URLs handling

### LINKED ISSUE #81330: [rustdoc] Remove query component from URL by pressing ESC
mdbook v4.6+ has a feature that pressing ESC removes query components from URLs (for example `?highlight=...`).
The feature was implemented in rust-lang/mdBook#1427.

 It would be nice if rustdoc offers the same kind of that feature.

This is, for example, an URL that contains query components in rustdoc: https://doc.rust-lang.org/nightly/std/time/struct.Duration.html?search=asdfasdf.

### What's the benefit of this feature?

When users share URLs to an API, they don't have to remove the query manually.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #81330.

Explanations: before this PR, when emptying the search input, we still had `?search=` in the URL, which wasn't very nice. Now, if the search is empty, we drop the `?search=` part.

Also, I realized while working on this PR that when we clicked on a menu link when we were on the search results, the search parameters would look like: `?search=#the-anchor`, which was super weird. Now, it looks like this: `?search=the-search#the-anchor`.

Also, I didn't use the `Url` very nice API because it's not available in any IE version (sadness...).

cc @lzutao 
r? @Nemo157

### CODE REVIEW

**Comment by Nemo157** [comment]
> Also, I realized while working on this PR that when we clicked on a menu link when we were on the search results, the search parameters would look like: `?search=#the-anchor`, which was super weird. Now, it looks like this: `#the-anchor?search=the-search`.

Query must come before the fragment, otherwise it is just part of the fragment content: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7db14933706efebda3821140565faefd>.

**Comment by lzutao** [comment]
Wikipage about URI syntax: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

**Comment by lzutao** [comment]
>  I didn't use the `Url` very nice API because it's not available in any IE version (sadness...).

Disclaimer: Not a web developer by any means. 
What would happen if we use unsupported APIs like URL in IE ?

**Comment by GuillaumeGomez** [comment]
> What would happen if we use unsupported APIs like URL in IE ?

A big JS error and some broken state for the website.

**Comment by GuillaumeGomez** [comment]
> What would happen if we use unsupported APIs like URL in IE ?

A big JS error and some broken state for the website.

**Comment by GuillaumeGomez** [comment]
Fixed the URL order and made the changes more "global".

**Pull request merged**
