### PR TITLE
Diagnostic width span is not added when '0$' is used as width in format strings

### PR DESCRIPTION
**Pull request by miam-miam**
When the following code is run rustc does not add diagnostic spans for the width argument. Such spans are necessary for a clippy lint that I am currently writing.

```rust
println!("Hello {1:0$}!", 5, "x");
//                 ^^
// Should have a span here
```

### CODE REVIEW

**Comment by oli-obk** [comment]
Is it possible to trigger any rustc error/lint that will show this change?

**Comment by miam-miam100** [comment]
I added a test which wouldn't have previously passed if that's what you mean?

**Comment by oli-obk** [comment]
Yea I saw that ^^ I was wondering about a user-visible change. It's not really important, just wondering

**Comment by miam-miam100** [comment]
Yes there is! 
```rust
fn main() {
    let test = 5;
    println!("Hello {test:1$}!");
}
```
Gives
```
error: invalid reference to positional argument 1 (no arguments were given)
 --> src/main.rs:3:21
  |
3 |     println!("Hello {test:1$}!");
  |                     ^^^^^^--^
  |                           |
  |                           this width flag expects an `usize` argument at position 1, but no arguments were given
  |
  = note: positional arguments are zero-based
  = note: for information about formatting flags, visit https://doc.rust-lang.org/std/fmt/index.html
  ```
  but 
  ```rust
  fn main() {
    let test = 5;
    println!("Hello {test:0$}!");
}
```
Only gives this
```
error: invalid reference to positional argument 0 (no arguments were given)
 --> src/main.rs:3:21
  |
3 |     println!("Hello {test:0$}!");
  |                     ^^^^^^^^^
  |
  = note: positional arguments are zero-based

error: could not compile `playground` due to previous error
```

**Comment by oli-obk** [comment]
cool! Please add such a test to the `src/test/ui` test suite. There are existing tests around wrong format strings, so you can just add your snippet to one of those existing tests and rebless that test with `./x.py test src/test/ui --bless --test-arg name_of_the_test`

**Pull request merged**
