### PR TITLE
Implement additional `split_inclusive` variants for slices

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
Implements additional variants of the `split` iterator methods for strings and slices.

### Methods implemented:

- **`slice::{r}split{n}{left}_inclusive{_mut}()`, `str::{r}split{n}{left}_inclusive()`, and `str::split_once{_left}_inclusive`:** The `inclusive` variants include the separator at the end of the returned elements, while the `left_inclusive` variants include it at the beginning.
- **`str::{r}split_initiator`, and `str::{r}split_ends`:** Variants of `split_terminator` that skip empty subslices at the beginning of the string, and at both ends of the string respectively.

In addition, this PR implements `Clone` when appropriate for the `splitn` iterators, and changes the return value of `size_hint` in a few cases.

### Unresolved questions

This adds a lot of new methods because of all the possible permutations. The implementations are unified via macros, but it's a lot of choices to sort through in the documentation. Maybe some variants should be omitted, or a more generic interface should be provided?

One possibility to limit the combinatorial explosion, which I'm currently implementing, is to not have the additional "`n`" variant methods be defined directly on `str`/`slice`, but on their base iterator.

-----
Interacts with #77998 (I haven't yet implemented `as_str` for all the new iterators)

### CODE REVIEW

**Comment by Jules-Bertholet** [comment]
@scottmcm This is complete and ready for review!

**Comment by scottmcm** [comment]
(Sorry for not responding over winter break)

Hmm, have you had any libs team feedback on all these?  This is a great many new iterator types, for example, as you mentioned.

If not, maybe [start a zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs) to collect some thoughts?

**Comment by Jules-Bertholet** [comment]
@scottmcm The final form of this PR is a lot more extensive than I initially intended; I set out to add [a single "obviously" missing iterator](https://internals.rust-lang.org/t/potential-rsplit-inclusive/15721/2), but then realized there were many other "obvious" additions to be made. I'll make a thread on Zulip

**Comment by scottmcm** [comment]
Zulip thread is https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Plugging.20holes.20in.20the.20string.2Fslice.20split.20apis (or https://zulip-archive.rust-lang.org/stream/219381-t-libs/topic/Plugging.20holes.20in.20the.20string.2Fslice.20split.20apis.html without needing a login).

Because of the number of additions this represents, I'm going to spin this to a libs member and mark it waiting on team.

r? rust-lang/libs

**Comment by m-ou-se** [comment]
We briefly discussed this in the libs-api meeting just now. Our conclusion is basically the same as what @BurntSushi already said on the Zulip thread: We care more about actual use cases than about filling out the whole matrix of possibilities. We're hesistant to add this many similar types and functions.

An idea that was brought up is to not add more iterator types, but to add new methods to the existing ones, to cover most/all of the functionality this PR adds. For example, `std::slice::Split` could have a method or two like `.next_with_separator()` or `.next_separator()` or `.next_including_separator()` or something in that direction. We didn't discuss this option in detail, but we'd like to see some exploration of alternatives that do not involve adding so many similar functions and types. An alternative with fewer functions and types might also be easier to document, and easier to learn and use for users.

**Comment by JohnCSimon** [comment]
ping from triage:
@Jules-Bertholet - can you please post the status of this PR?


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by Jules-Bertholet** [comment]
This PR isn't ready as is, I need to integrate some reviewer comments.

**Comment by Dylan-DPC** [comment]
@Jules-Bertholet any updates on this

**Comment by Jules-Bertholet** [comment]
@Dylan-DPC Not at present. I'm planning to make an API change proposal before continuing to work on the implementation, that should be ready soon

**Comment by pitaj** [comment]
I've implemented an alternate API using combinators. It's available in the [`str_splitter`](https://crates.io/crates/str_splitter) crate if anyone wants to check it out.

**Comment by Dylan-DPC** [comment]
Closing this as it is a draft and is inactive for some time. Feel free to reöpen this or create a new pr if you want to continue with this. Thanks

**Pull request closed without merging**
