### PR TITLE
Fix ICE test in compiletest fail-tests

### PR DESCRIPTION
**Pull request by mcarton**
While working on Clippy which uses _compiletest_, I noticed that as long as all expected error are found, _compile-fail_ tests will be marked _ok_ even if there is an ICE. One function seems to have not been updated with JSON errors because ICEs are now reported like this:

``` json
{"message":"../src/librustc/ty/context.rs:161: Attempted to intern `_` which contains inference types/regions in the global type context","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":null}
```

I don't think I can add a test for that.

I guess:
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@mcarton good catch =)

**Comment by GuillaumeGomez** [comment]
It made an ICE it seems: https://buildbot.rust-lang.org/builders/auto-linux-64-opt/builds/10480/steps/test/logs/stdio

**Comment by mcarton** [comment]
```rustc
% rustc src/test/compile-fail/issue-31109.rs
error: internal compiler error: ../src/librustc_const_eval/eval.rs:1273: could not evaluate float literal (see issue #31407)
  --> src/test/compile-fail/issue-31109.rs:14:18
   |
14 |     let _: f64 = 1234567890123456789012345678901234567890e-340; //~ ERROR could not evaluate float
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.
```

Looks weird to check for the presence of an ICE.
Should that be converted to a regular error?

**Comment by nikomatsakis** [comment]
It sounds to me like the desired error is being reported and then,
separately, an ICE. In other words the PR is catching a latent bug.

**Comment by mcarton** [comment]
I've changed the error so that it does not ICE anymore.

**Comment by GuillaumeGomez** [comment]
But it still fails travis. :p

**Comment by mcarton** [comment]
This once, I've tested it :sweat_smile:

**Comment by GuillaumeGomez** [comment]
And travis seems happy. All good for me then. Thanks!

@bors: r+ rollup

**Comment by rkruppe** [comment]
I only now saw this PR. When I introduced that test in #31410 I was told to make it a `span_bug` rather than an ordinary error. So it's *not* a latent bug, it was an "intentional ICE". Maybe whoever has the last word on that decides that ICE-ing on known issues isn't good, but I do want to bring it up just to be sure.

**Pull request merged**
