### PR TITLE
rustc: use methods instead of functions in middle::ty.

### PR DESCRIPTION
**Pull request by eddyb**
Next step towards split local/global type contexts, after #26351.
cc @rust-lang/compiler @jroesch

### CODE REVIEW

**Comment by barosl** [comment]
O.o This is a HUGE refactoring! :clap: :+1: :cake: for @eddyb.

I also wonder how many PRs will be marked to unmergeable because of this... :laughing:

**Comment by eddyb** [comment]
@barosl it's a... prerequisite for a prerequisite (`TyCx<'a, 'tcx>`) for split local/global type contexts.
I'm a bit worried that it doesn't help as much as I had hoped or that it will be controversial.
It's also going to rot if it doesn't get reviewed this week, but most changes were mechanical, so unless there are significant changes to `middle::ty`, it should be possible to rebase it.

**Comment by eddyb** [comment]
I might remove the last two commits - if we can get something like `'_` working (to replace `&ty::ctxt<'tcx>` with `TyCx<'_, 'tcx>`), even if it's feature-gated, the existing `TyCx` commits would be obsoleted (and merging them would make it harder to switch to `'_` later).
Also see https://internals.rust-lang.org/t/flattening-the-contexts-for-fun-and-profit/2293.

**Comment by eddyb** [comment]
@nikomatsakis I've removed the `TyCx` commits from this PR - they are now at https://github.com/eddyb/rust/commits/tycx-more-tcx-tcx.
If #26598 is merged, introducing `TyCx` will be way less painful (though it does mean a couple of days were wasted) - also see rust-lang/rfcs#1177.

**Comment by nikomatsakis** [comment]
@eddyb this is nice!

**Pull request merged**
