### PR TITLE
rustdoc: don't collapse `docblock-short`

### PR DESCRIPTION
**Pull request by liigo**
docblock-short

### CODE REVIEW

**Comment by frewsxcv** [comment]
```

failures:

thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:295
---- [rustdoc] rustdoc/issue-32374.rs stdout ----
	
error: htmldocck failed!
status: exit code: 1
command: "python" "/build/src/etc/htmldocck.py" "/build/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-32374.stage2-x86_64-unknown-linux-gnu" "/build/src/test/rustdoc/issue-32374.rs"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
16: @has check failed
	`XPATH PATTERN` did not match
	// @has issue_32374/index.html '//*[@class="docblock short"]' '[Deprecated] [Unstable]'

Encountered 1 errors

------------------------------------------

thread '[rustdoc] rustdoc/issue-32374.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:2359
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [rustdoc] rustdoc/issue-32374.rs

test result: FAILED. 120 passed; 1 failed; 1 ignored; 0 measured

```

**Comment by steveklabnik** [comment]
I like this, but yeah, seems like it fails the tests.

**Comment by bluss** [comment]
Some of the styling of docblock will no longer apply to the docblock-short lines since they change class. Does it matter? I think this one is needed, and maybe more?

```css
.docblock {
    margin-left: 24px;
}
```

**Comment by liigo** [comment]
@steveklabnik I've fixed test failure, and rebased. r?

**Comment by steveklabnik** [comment]
@liigo did you check on what @bluss was saying? I'm not sure if it matters or not.

**Comment by liigo** [comment]
@steveklabnik  @bluss 
I think, `.docblock { margin-left: 24px; }` is used for making room for the `[−]` button at the top-left corner of a docblock.

docblock-magin

----

If remove it, something will get mess:

docblock-magin-0

**Comment by bluss** [comment]
@liigo Aha, I tested locally and that seems right. Looks like `.docblock code { }` is missing though, so that rule needs to be updated.

**Comment by liigo** [comment]
I'll recheck. Thank you @bluss !

**Comment by liigo** [comment]
Done. Could you have another review? Thank you! @bluss

**Comment by steveklabnik** [comment]
@bors: r+

thank you!

**Comment by bluss** [comment]
This change looks great in real life :+1:

**Pull request merged**
