### PR TITLE
Update stdarch

### PR DESCRIPTION
**Pull request by jrmuizel**
This adds a bunch of NEON intrinsics, AVX512 intrinsics, eliminates MMX
support and relands the mm_extract_epi fix. I believe
the mm_extract_epi fix is the only change that impacts stable.

### CODE REVIEW

**Comment by jrmuizel** [comment]
mingw-check failure will hopefully be fixed by https://github.com/rust-lang/stdarch/pull/910

**Comment by jyn514** [comment]
Duplicate of #73166 ?

**Comment by jrmuizel** [comment]
Well this updates to an even newer version, but it's probably worth waiting for #73166 to land before taking this one.

**Comment by Amanieu** [comment]
I'm going to close this in favor of #73166.

**Pull request closed without merging**
