### PR TITLE
Added remove_item to vec.rs (#38143)

### PR DESCRIPTION
**Pull request by eddyb**
Turns out that if you push to someone's PR branch and cause the PR to close, you lose delegation 😞.

@madseagames I'm really sorry about that 😭

### CODE REVIEW

**Comment by madseagames** [comment]
So... Now what? Is my commit gonna be in the compiler now? In the beta or nightly?

**Comment by eddyb** [comment]
@madseagames It first has to go through the [merge queue](https://buildbot.rust-lang.org/homu/queue/rust), where the PR is tested in a few dozen configurations, and if successful, it will be in the first nightly after that.

**Comment by madseagames** [comment]
@eddyb that's awesome! Thanks for the help Eddy!

**Pull request merged**
