### PR TITLE
Make [-] invisible in most cases

### LINKED ISSUE #85372: rustdoc: make [-] invisible in most cases
The toggles (`[-]` / `[+]`) on rustdoc pages are needed for a couple of reasons:

 - Some sections are closed by default and need a `[+]` to open them.
 - Some sections are open by default, but can be default-closed by a setting. Those need a `[+]` to open them.
 - The user might close all sections with the "collapse all docs" button. Those need a `[+]` to open them.
 
Note that these all involve the `[+]`, not the `[-]`. But we show lots of `[-]` all over the page, which is visually distracting. In theory these allow users to collapse a single section at a time, but I don't think that's very useful.
 
I propose that we make `[-]` invisible. With one exception: If someone has opened a section with `[+]`, it would be confusing and frustrating to not be able to close that section again. So, when someone clicks a `[+]`, we would added a "perma-visible" class to that `<summary>` tag, which would cause the `[-]` to be visible.

cc @GuillaumeGomez

### PR DESCRIPTION
**Pull request by jsha**
Many items on doc pages are collapsible, so they have `[-]` / `[+]` items. These icons take up critical space in the gutter, reducing the ability to scan for an item you're looking for. The `[+]` icon is very important, so you can open the item you're looking for once you find it. But for a group of toggles that are already open, having `[-]` is not very useful, since collapsing a single item doesn't give you a much clearer view of the page.

This PR changes the UI so that `[-]` doesn't show up on sections that are toggled open. Those sections can be toggled closed with the keyboard shortcuts or the button in the top right. Also, some sections (like methods) can be toggled closed by a setting.

For sections that start in a closed position, when you click the `[+]` to open them, they will get a `[-]` to close them again. Otherwise it would be frustrating to open a section and not be able to immediately change your mind and close it.

This change made the `⬑` in stability output point into empty space, so I changed the display of stability information to not use `⬑` (see comment on 770f7dd2d01054f64d8433034a8e8ee8ff53c26a).

Fixes #85372

Demo: https://jacob.hoffman-andrews.com/rust/invisible-toggles/std/string/struct.String.html#implementations
https://jacob.hoffman-andrews.com/rust/invisible-toggles/std/io/trait.Read.html#provided-methods

r? @GuillaumeGomez

### CODE REVIEW

**Comment by jsha** [comment]
We have a failure in the rustdoc-gui tests that is presumably triggered by the real behavior change here. I've tried to debug it locally but I'm not sure how to get an interactive browser session to poke around after a test fails. Any recommendations @GuillaumeGomez ?

**Comment by Nemo157** [comment]
Two places I would still leave the toggle is the per-impl-block headers and the description. The former are not toggled by the "collapse all docs" button so there is no way to collapse them now, the latter I at least very commonly collapse to get it out of the way and start skimming the method docs.

This also exacerbates an existing nightly issue that the text in trait-implementations is not indented far enough, previously that was sort of ok since the `[-]` acted as a bullet point

image

but now it's very hard to find the method headers inside the trait-implementation.

image

**Comment by GuillaumeGomez** [comment]
Sorry but I really don't like it either... The disappearance of the toggle makes it look like you can't collapse it anymore. And just like @Nemo157 said, it actually makes the reading harder. This was a good visual element to "separate" elements.

**Comment by Cldfire** [comment]
One other anecdote: for me the [-] button next to methods is an important visual landmark that helps my eyes "feel" where the beginning and end of each method's docs are. With that button removed, this visual landmark is gone, meaning there's no differentiation in indentation or any other sort of prominent landmark via which to identify the beginning / end of a method in an impl block.

**Comment by jsha** [comment]
That's good feedback that people see the `[-]` as a visual separator between methods. That's actually part of my goal, to _improve_ the visual separation between methods, and generally improve scanability. To me, the `[-]` do indeed serve as separators but I don't think they are the best tool for the job. They also wind up acting as visual noise and distracting from the most important thing: the method name.

I figured what I'm trying to get at here would be clearer if I put together a few of the changes I'm thinking of into one PR rather than doing this piecemeal. Take a look at https://github.com/rust-lang/rust/pull/86283.

> The disappearance of the toggle makes it look like you can't collapse it anymore.

Is the idea that people are likely to want to collapse toggles one-by-one? Or do you want the series of `[-]` down the side of the page to serve as a sort of advertisement for the "collapse all docs" feature?

**Comment by GuillaumeGomez** [comment]
I can only use myself as example: I tend to collapse everything by default and then expand items to check if this is the one I'm looking for, and if not, to collapse it again.

**Comment by jsha** [comment]
Closing. Some of the same concepts are incorporated into #86283; when I pick that up again I'm interested to explore this more.

**Pull request closed without merging**
