### PR TITLE
Make `DefId` `repr(C)`, optimize big-endian field order

### PR DESCRIPTION
**Pull request by llogiq**
r? @michaelwoerister

### CODE REVIEW

**Comment by llogiq** [comment]
That's *weird*. Even if I did something wrong, it shouldn't change the outcome by that much.

**Comment by michaelwoerister** [comment]
Yeah, that is weird. We'd expect the outcome to not change at all...

**Comment by jackh726** [comment]
I wonder if something is going wrong with perf: https://github.com/rust-lang/rust/pull/91672#issuecomment-996533166

**Comment by llogiq** [comment]
Yeah, that looks really fishy. Perhaps someone with access to perf can have a look?

**Comment by llogiq** [comment]
Ah it's likely because of https://github.com/rust-lang/rustc-perf/pull/1123

**Comment by llogiq** [comment]
So there *is* something wrong. I'll have a look.

**Comment by llogiq** [comment]
Can we get another perf run? I wonder if removing the `repr(C)` fixes the regression. Otherwise it must be because of the ``#[cfg(..)]`s. I also wonder if at this point it would make sense to change `DefId` to a single `u64` and make `index` and `krate` methods instead, but that change would be far larger. The upside would be that we could freely change the internal representation should we ever desire it.

**Comment by michaelwoerister** [comment]
perf.rlo seems to have problems with increased noise at the moment: https://github.com/rust-lang/rustc-perf/issues/1126

Let's wait for that to be fixed and then revisit this.

**Comment by llogiq** [comment]
@michaelwoerister should I reinstate the `#[repr(C)]` then before we do the perf run?

**Comment by Mark-Simulacrum** [comment]
That particular bug on perf at least should be fixed.

@bors try @rust-timer queue

(Just to get one going in the meantime...)

**Comment by llogiq** [comment]
Ok, that's what we were expecting. Now I'll add the `#[repr(C)]` back.

**Comment by llogiq** [comment]
Cool. This means we haven't lost any perf on any tier-1 systems and may have gained a little on big-endian 64-bit machines, not that there would be a lot of them around.

**Comment by michaelwoerister** [comment]
Looks good now!
@bors r+

**Pull request merged**
