### PR TITLE
Add EntryExistInstrumenterPass for -Z instrument-mcount to the pipeline manually for LLVM >= 13.

### LINKED ISSUE #92109: Instrumentation (-Zinstrument-mcount) broken due to missing LLVM-pass since LLVM13 update
### Issue

I tried to compile a generic hello-world binary with the `-Zinstrument-mcount` compiler option.

I expected every function-entry to have a call to `mcount()`.
Instead, there are no such calls inserted.

### Triage

I have triaged the bug, and it first occurred in `nightly-2021-08-22`, the first version with LLVM13.

The LLVM-IR still contains the `"instrument-function-entry-inlined"="mcount"` attributes, but the corrosponding llvm-pass is not run anymore.

```rust
rustc +nightly-2021-08-21 -O -Zinstrument-mcount main.rs --emit asm -Z print-llvm-passes -Z no-parallel-llvm 2>&1 | grep mcount
    Instrument function entry/exit with calls to e.g. mcount() (pre inlining)
      Instrument function entry/exit with calls to e.g. mcount() (post inlining)
rustc +nightly-2021-08-22 -O -Zinstrument-mcount main.rs --emit asm -Z print-llvm-passes -Z no-parallel-llvm 2>&1 | grep mcount
[empty]
```

Verbose Versions:
```
❯ rustc +nightly-2021-08-21 --version --verbose
rustc 1.56.0-nightly (a0035916e 2021-08-20)
binary: rustc
commit-hash: a0035916e01d8e644ccd44554c57f0874cef8c8c
commit-date: 2021-08-20
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
❯ rustc +nightly-2021-08-22 --version --verbose
rustc 1.56.0-nightly (d3e2578c3 2021-08-21)
binary: rustc
commit-hash: d3e2578c31688619ddc0a10ddf8543bf4ebcba5b
commit-date: 2021-08-21
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 13.0.0
```

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #92109

### CODE REVIEW

**Comment by nikic** [comment]
As we only set `instrument-function-entry-inlined`, I assume the pre-inline pass is not strictly necessary and just added for the sake of completeness?

**Comment by tmiasko** [comment]
I don't have opinion whether we should land this for now, but I think the issue is ultimately on the LLVM side: https://github.com/llvm/llvm-project/issues/52853

**Comment by luqmana** [comment]
> As we only set `instrument-function-entry-inlined`, I assume the pre-inline pass is not strictly necessary and just added for the sake of completeness?

Yea. Mostly trying to keep the same behaviour that was previously handled in LLVM. More-or-less doing the same sorta thing in clang (as per https://reviews.llvm.org/D97608)

**Comment by luqmana** [comment]
> I don't have opinion whether we should land this for now, but I think the issue is ultimately on the LLVM side: [llvm/llvm-project#52853](https://github.com/llvm/llvm-project/issues/52853)

I think that's the slightly different issue of clang producing misleading results. Rust simply stopped inserting the mcount calls at all, which is what this PR was trying to address. Although, reading that it seems like we might as have the same issue.

**Comment by tmiasko** [comment]
> > I don't have opinion whether we should land this for now, but I think the issue is ultimately on the LLVM side: [llvm/llvm-project#52853](https://github.com/llvm/llvm-project/issues/52853)
> 
> I think that's the slightly different issue of clang producing misleading results. Rust simply stopped inserting the mcount calls at all, which is what this PR was trying to address. Although, reading that it seems like we might as have the same issue.

To my understanding fixing that issue would obviate the need for changes on the Rust side, and obsolete any changes made here, so it might be a preferable direction. Especially that Rust implementation would otherwise have exactly the same problem.

Sorry for just linking the issue without offering an explanation.

**Comment by luqmana** [comment]
> > > I don't have opinion whether we should land this for now, but I think the issue is ultimately on the LLVM side: [llvm/llvm-project#52853](https://github.com/llvm/llvm-project/issues/52853)
> > 
> > 
> > I think that's the slightly different issue of clang producing misleading results. Rust simply stopped inserting the mcount calls at all, which is what this PR was trying to address. Although, reading that it seems like we might as have the same issue.
> 
> To my understanding fixing that issue would obviate the need for changes on the Rust side, and obsolete any changes made here, so it might be a preferable direction. Especially that Rust implementation would otherwise have exactly the same problem.
> 
> Sorry for just linking the issue without offering an explanation.

Oh no worries. I did think on first read they meant making those changes on the Clang side but if it involves just doing the work from the backend again, that works too. I guess the question then is is it worth getting something working in the meantime since it has been broken for a couple months now.

**Comment by pnkfelix** [comment]
I think we can and should push ahead with the strategy of adding a `-Z` flag for the short term to cover this functionality.

But I also think it makes a lot of sense to include a pointer to https://github.com/llvm/llvm-project/issues/52853, *either* in a comment in the code itself, or in the help text for `-Z instrument-mcount`, so that people at least have some hint that the results they get may suffer from misleading end results.

r+ from me after you make a change along those lines, @luqmana .

**Comment by apiraino** [comment]
Switching to waiting on author to incorporate changes. Feel free to request a review when ready, thanks!

@rustbot -S-waiting-on-review +S-waiting-on-author

**Comment by cuviper** [comment]
FYI, #100460 made LLVM 13 the minimum, which should simplify some things here.

**Comment by JohnCSimon** [comment]
ping from triage:
@luqmana 

Can you please post your status on this PR? There are reviewer comments. 

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by mati865** [comment]
ping @luqmana

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
