### PR TITLE
Support Android ndk versions `r23-beta3` and up

### PR DESCRIPTION
**Pull request by ghost**
Since android ndk version `r23-beta3`, `libgcc` has been replaced with `libunwind`. This moves the linking of `libgcc`/`libunwind` into the `unwind` crate where we check if the system compiler can find `libunwind` and fall back to `libgcc` if needed.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@petrochenkov -- do you have a read on this PR perhaps?

It seems like this could break downstream users if they're relying on libgcc linked in (due to std asking for it), even though they sort of shouldn't be doing so. Ultimately seems ok, though, especially if upstream is going to drop it...

**Comment by petrochenkov** [comment]
If this passes CI (which uses an old NDK?) then I'm happy with this.

We are linking compiler-builtins anyway so Rust code is covered, and if `libgcc` is required by `libc` then we'll know it from CI, I guess. That's certainly a possibility because a random old NDK that I have at hand (`android-ndk-r17c-aarch64-21`) does this
```
-lgcc -lc -ldl -lgcc
```

**Comment by ATiltedTree** [comment]
There seem to be two main issues:

#### 1. `_sync_*` missing

These are normally defined by `compiler-builtins` but it seems they are only exposed on `target_os = "linux"` and not android:
https://github.com/rust-lang/compiler-builtins/blob/master/src/lib.rs#L52-L53

This should be changed to include android as it also uses them.

#### 2. Missing unwinder

Apparently `libgcc` included an unwinder which we are now missing. ndk r23 beta 3 now includes `libunwind` as a replacement. So we could check if the c compiler can

**Comment by ATiltedTree** [comment]
There seem to be two main issues:

#### 1. `__sync_*` missing

These are normally defined by `compiler-builtins` but they are only exposed on `target_os = "linux"` and not android:
https://github.com/rust-lang/compiler-builtins/blob/master/src/lib.rs#L52-L53

This should be changed to include android as it also uses them.

#### 2. Missing unwinder

`libgcc` included an unwinder which we are now missing. ndk r23 beta 3 [now includes libunwind](https://github.com/android/ndk/wiki/Changelog-r23#changes) as a replacement. So we could check in the `unwind` build script if the C compiler can link with `libunwind` and fall back to `libgcc` otherwise.

Any other ideas are appreciated.

**Comment by ATiltedTree** [comment]
The mentioned issues should now be resolved as `compiler-builtins` now exposes the missing functions. And we now try to find the newer `libunwind` using the `C` compiler and fall back to `libgcc` if it cannot be found.

**Comment by petrochenkov** [comment]
@ATiltedTree 
To clarify, you are going to use this for custom builds of the standard library, right?
The NDK on CI is still old, and will always result in linking to libgcc in released Rust toolchains.

@bors r+

**Comment by ATiltedTree** [comment]
> To clarify, you are going to use this for custom builds of the standard library, right?

Yes, I am going to use this for custom std builds.

> The NDK on CI is still old, and will always result in linking to libgcc in released Rust toolchains.

And that is fine as long as I can do custom builds with newer toolchains.

**Comment by ATiltedTree** [comment]
Updated `compiler_builtins` again to fix the panic for targets with less than three target components.

**Comment by ssrlive** [comment]
I have test the patch with rustc 1.55.0 and rustc 1.57.0-nightly with NDK 23.0.7599858  , I find it not work.
the compiler always tell me
```
ld: error: unable to find library -lgcc
```
please re-test your fixing.

**Comment by marcbrevoort-cyberhive** [comment]
I find it somewhat confusing that the automatic fallback means that a lack of `libunwind` results in an error message `ld: error: unable to find library -lgcc` - this is misleading and hard to troubleshoot.

**Comment by vok1980** [comment]
> Until the Rust project decide to bump the requirement to `r23` minimum or start providing a target for `r23 >=`. It think the only solution is to have a custom build of the standard library.

@Urgau Is there any prognosis when requirement will be bumped or target for r23 provided?

**Comment by Urgau** [comment]
@marcbrevoort-cyberhive The fallback is at build time, and the current android target are build with an SDK lower than r23 so the linking error is indeed misleading but not wrong, your are still trying to link to libgcc.

@vok1980 I'm not part of any Rust Team no I can speak for the project. In the past the minimum SDK requirement was bump when necessary and acceptable, eg. using a function only available in newer sdk, ... I'm not aware of any PR that would increase the minimum required SDK and even if there was one updating to r23 it would probably to not be accepted (due to the potential large breakage of projects).
As for a target with r23 and upper, I'm again not aware of any attempt to create such target. Sorry to not being more helpful.

I think it would be useful if someone could create an issue stating that the current situation is not great because it requires a custom build of std. It also seems that `cargo-apk` (a community project) has found a workaround for this issue with older sdk starting [0.8.2](https://github.com/rust-windowing/android-ndk-rs/releases/tag/cargo-apk-0.8.2).

**Comment by cherryleafroad** [comment]
I'm still getting this error on 1.59.0. Building on r22b works perfectly fine. Am I doing something wrong here, or is there a way I can use the newer ndk?

**Comment by kopianan** [comment]
> 

i got some issue here. Rust code linker will got issue on -lgcc. so it because the newer version of ndk does'nt have this library ?

**Comment by saurik** [comment]
So, I don't understand what is going on here... it seems like Rust doesn't support building projects for Android unless you are using an obsolete and actively-"unsupported" version of the Android NDK? And there was some kind of patch that was committed to maybe fix this, but it only affects a configuration that can itself only be unlocked using an experimental and essentially-unsupported version of Rust? And this has been the case for an entire year? :( And so, rather than fixing this issue, I'm seeing tons of other projects here saying that they've simply committed crazy workarounds to their build systems to add stub copies of libgcc.a that are actually linker scripts that remap symbols to libunwind.a--amazingly including parts of Rust itself, which is just crazy to me: the libc patch that someone submitted (which I'm guessing will die on the vine anyway) seriously has a FIXME in a script to do that same horrible workaround--which ostensibly means that any attempt that Rust is having here to pretend to be avoiding breaking projects is just creating even more churn and even more breakage in downstream projects (an issue we've also seen with cross-compilation in Cargo being so broken that the third-party recommended fix is to set __CARGO_TEST_CHNANLE_OVERRIDE_DO_NOT_USE_THIS in all new projects in order to get access to -Z target-applies-to-host)?

**Comment by Urgau** [comment]
@saurik The Standard Library is perfectly able to be build for and be used with newer ndk version. The "problem" (depending on your position) is that the pre-build std, core, ...  distributed with `rustup` for the target are targeting (voluntarily) an old ndk. If you want to use this pre-build standard libraries with the distributed target on newer target you need to have the "crazy" workaround, but the simpler and better solution would be to simply have artifacts for the desired ndk which is possible with cargo [`-Zbuild-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) (albeit still nightly-only).

**Comment by phatblat** [comment]
Confirmed that @ssrlive's dummy `libgcc.a` workaround https://github.com/rust-lang/rust/pull/85806#issuecomment-1096266946 works with both NDK versions `23.1.7779620` and `25.1.8937393` with rust version `1.66.1` android targets.

Here's a one-liner script to drop these `libgcc.a` files next to every `libunwind.a`.

```bash
find "${ndk_dir}" -name "libunwind.a" \
    -execdir bash -c 'echo "INPUT(-lunwind)" > libgcc.a' \;
```

`ndk_dir` can be a specific NDK version dir (e.g. `~/Library/Android/sdk/ndk/25.1.8937393`) or just `~` to get them all.

**Comment by cjdelisle** [comment]
In case you are using busybox find (e.g. alpine linux), this should work:

```bash
find "${ndk_dir}" -name 'libunwind.a' | \
  sed 's@libunwind.a$@libgcc.a@' | \
  while read x; do
    echo "INPUT(-lunwind)" > $x
  done
```

**Comment by nova2moon** [comment]
Maybe someone can clarify further for total new-comer :)  did spend few hours and cannot get it to work..

running: cross build  --target aarch64-linux-android --release  and hitting this issue:

error: linking with `aarch64-linux-android-gcc` failed: exit status: 1
  = note: /android-ndk/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lunwind

(full failure here: https://pastebin.com/iUxLMLGx)

so, seems like same issue.  

Linux Mint 22.1 (kia) 
$ rustc -V
rustc 1.87.0 (17067e9ac 2025-05-09)
 cross -V
cross 0.2.5
[cross] note: Falling back to `cargo` on the host.
cargo 1.87.0 (99624be96 2025-05-06)

Using latest NDK:

$ env|grep NDK
NDK_HOME=/opt/android-sdk-lite/ndk/29.0.13113456/

Reading all notes, figured need the workaround suggested, so, ran the find/sed one liner, it created 11 libgcc.a right next to the libunwind.al   two sample files:

/opt/android-sdk-lite/ndk/29.0.13113456/toolchains/llvm/prebuilt/linux-x86_64# find . -name '*libgcc.a' -ls |grep aarch64
 10673353      4 -rw-r--r--   1 root     root           16 May 16 18:44 ./lib/clang/20/lib/linux/aarch64/libgcc.a
 10673357      4 -rw-r--r--   1 root     root           16 May 16 18:44 ./lib/aarch64-unknown-linux-musl/libgcc.a



$ rustup target add aarch64-linux-android 
info: component 'rust-std' for target 'aarch64-linux-android' is up to date

maybe (re)install it?

$ rustup install aarch64-linux-android 
warning: (partial) target triple specified instead of toolchain name
error: no candidate toolchains found
error: toolchain 'aarch64-linux-android' is not installed

but rustup shows it is there:

$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/moon/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-linux-android
arm-linux-androideabi
armv7-linux-androideabi
i686-linux-android
x86_64-linux-android
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------
stable-x86_64-unknown-linux-gnu (default)
rustc 1.87.0 (17067e9ac 2025-05-09)


trying to maybe set as default?

$ rustup default aarch64-linux-android 
warning: (partial) target triple specified instead of toolchain name
you may use the following toolchain: stable-aarch64-linux-android
error: toolchain 'aarch64-linux-android' is not installed

Also tried the suggested workaround one comment above:
mkdir android (create libgcc.a) then placing the build.rc inside src direcotory,

however, still it fails with unable to find -lunwind.a


As a "workaround" built it for 32 bit, which worked right away:

cross build -v --target arm-linux-androideabi --release

got the binary, however still curious how to get 64 bit version...

**Pull request merged**
