### PR TITLE
[perf] Measure Destination Propagation performance

### PR DESCRIPTION
**Pull request by jonas-schievink**
Based on https://github.com/rust-lang/rust/pull/72632

### CODE REVIEW

**Comment by bjorn3** [comment]
Very mixed results.

**Comment by jonas-schievink** [comment]
Looks basically as expected, I'd say. The biggest slowdown is ~10%, in ucd-check. `optimized_mir` now takes ~600 ms longer, which is a rather big-looking regression by 16577.8%. Suspicious log output:

```
[DEBUG rustc_mir::transform::dest_prop] DefId(0:1732 ~ ucd[f25a]::tables[0]::scripts[0]::{{impl}}[14]::fmt[0]): 696 locals (278 relevant), 417 blocks
```

I've pushed a commit that skips functions that have too many blocks (in addition to skipping ones with too many locals).

@bors try @rust-timer queue

**Comment by jonas-schievink** [comment]
(this still regresses `optimized_mir` from ~30ms to ~300ms for ucd, but costs like that should be somewhat expected when optimizations are turned on)

**Comment by jonas-schievink** [comment]
Huh, that did nothing to the ucd benchmarks, odd.

**Comment by Dylan-DPC** [comment]
@jonas-schievink any updates?

**Comment by jonas-schievink** [comment]
This was just for perf runs of #72632, closing in favor of that.

**Pull request closed without merging**
