### PR TITLE
Implement MaybeUninit::fill{,_with,_from}

### PR DESCRIPTION
**Pull request by ajwock**
ACP: rust-lang/libs-team#156

### CODE REVIEW

**Comment by ajwock** [comment]
With @jmillikin 's blessing, I am submitting a new PR for:

Tracking issue: [#117428 ](https://github.com/rust-lang/rust/issues/117428)

ACP: [rust-lang/libs-team#156](https://github.com/rust-lang/libs-team/issues/156)

Credit to him for letting me use bits of his PR, especially testing.

**Comment by ajwock** [comment]
r? @Amanieu

I understand you've reviewed the previous implementation of this ACP.

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/122031#issuecomment-1979419665

**Pull request merged**
