### PR TITLE
Remove `-Zdump-mir-spanview`

### PR DESCRIPTION
**Pull request by Zalathar**
The `-Zdump-mir-spanview` flag was added back in #76074, as a development/debugging aid for the initial work on what would eventually become `-Cinstrument-coverage`. It causes the compiler to emit an HTML file containing a function's source code, with various spans highlighted based on the contents of MIR.

When the suggestion was made to [triage and remove unnecessary `-Z` flags (Zulip)](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.60-Z.60.20option.20triage), I noted that this flag could potentially be worth removing, but I wanted to keep it around to see whether I found it useful for my own coverage work.

But when I actually tried to use it, I ran into various issues (e.g. it crashes on `tests/coverage/closure.rs`). If I can't trust it to work properly without a full overhaul, then instead of diving down a rabbit hole of trying to fix arcane span-handling bugs, it seems better to just remove this obscure old code entirely. 

---

@rustbot label +A-code-coverage

### CODE REVIEW

**Comment by Zalathar** [comment]
While I was in the area I also noticed some opportunities to simplify `pretty.rs` by inlining `create_dump_file_with_basename` and `dump_file_basename`, but I decided to keep this PR clean and pursue those changes later in a separate PR.

**Review by Swatinem — APPROVED** [review]
good to see all this code gone. unfortunate that it was not useful with helping/guiding your recent work to improve all that span handling.

**Review by Noratrieb — APPROVED** [review]
Tried this out once and while it was pretty cute, if it's not useful it should be removed.

**Pull request merged**
