### PR TITLE
Run tidy license checker on more workspaces

### PR DESCRIPTION
**Pull request by bjorn3**
The license checker didn't run on several workspaces before this PR. The same applied to the "external package sources" check. There were also two missing lockfiles which I have added now.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
All of these changes seem reasonable to me, this isn't adding any new dependencies, just improving our tidy check - do you want to merge now or wait until the various `Cargo.lock` pull requests are landed? r=me if you want

**Comment by bjorn3** [comment]
I did like to merge it now to catch potential issues sooner.

**Comment by bjorn3** [comment]
Looks like running tidy's licence checker for cg_gcc won't work until it's dependencies are vendored. Disabled it for now.

**Comment by ehuss** [comment]
@bors r-

synchronizing the queue

**Comment by davidtwco** [comment]
Apologies for not checking on this recently, are there any changes you want to make here before r=me @bjorn3?

**Comment by bjorn3** [comment]
I'm happy with the current state. There are a couple of temporary exceptions, but those can be removed once the respective issues get fixed.

**Comment by bjorn3** [comment]
`src/etc/test-float-parse` and the miri tests don't get their dependencies vendored. (cc @oli-obk) Excluded them for now.

@rustbot ready

**Review by davidtwco — APPROVED** [review]

**Comment by lqd** [comment]
The perf collector is acting up, and this is a change to tidy only.

I'll mark this as triaged for now, but we could remove the `perf-regression` label instead when weekly triage happens.

@rustbot label: +perf-regression-triaged

**Pull request merged**
