### PR TITLE
Split core::iter module implementation into parts

### PR DESCRIPTION
**Pull request by bluss**
Split core::iter module implementation into parts

split iter.rs into a directory of (implementation private) modules.
- mod (adaptor structs whose private fields need to be available both for them and Iterator
  - iterator (Iterator trait)
  - traits (FromIterator, etc; all traits but Iterator itself)
  - range (range related)
  - sources (Repeat, Once, Empty)

### CODE REVIEW

**Comment by bluss** [comment]
I was looking for a good diff tool to display / review this with.

No functional change (of course). Only edits are license headers and `use/mod` lines.

This git command makes it show a diff between iter.rs and each output file at least:

```
git diff --diff-algorithm=minimal  -M01 -C01 HEAD~2 -p --stat
```

**Comment by alexcrichton** [comment]
Nice! 

Currently `mod.rs` [starts with](https://github.com/bluss/rust/blob/085fddac50a808d2013a86b5ae11297cd31adcb3/src/libcore/iter/mod.rs#L336) a couple of implementations of `ExactSizeIterator`, but could they move to their relevant adaptor like the other impelmentations of `ExactSizeIterator`?

Other than that this basically all looks good to me! r=me with that minor change

**Comment by bluss** [comment]
No diff is too big for you! I've moved the ESI impls now, that's a good thing to do anyway.

@bors r=alexcrichton

**Pull request merged**
