### PR TITLE
Move tests from src/test/run-fail/ to src/test/ui/

### PR DESCRIPTION
**Pull request by nvlbg**
Moving few tests according to issue #65440

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@nvlbg it looks like you need to run `./x.py test --bless` locally

**Review by nikomatsakis — APPROVED** [review]

**Comment by nvlbg** [comment]
I couldn't figure out in which folders to put the following tests so I put them in the top level ui foler:

- bug-811.rs
- rhs-type.rs
- tls-exit-status.rs
- unwind-interleaved.rs
- unwind-rec2.rs
- unwind-rec.rs
- unwind-unique.rs -> unwind-unique-panic.rs
- meta-revision-bad.rs
- meta-revision-ok.rs

Also the following two tests fail and I don't know how to fix them:
- meta-revision-bad.rs
- meta-revision-ok.rs

@estebank commented in the issue that there were tests that were non-deterministic on different platforms but apart from the two failing tests I didn't find such tests.

**Comment by nikomatsakis** [comment]
@nvlbg 

> Also the following two tests fail and I don't know how to fix them:

Is this still true? can you say a bit more about how they fail?  Based on the log I see above, it seems like only one test fails (but two revisions):

```
2019-10-22T22:01:44.1370673Z failures:
2019-10-22T22:01:44.1371565Z [ui] ui/meta-revision-bad.rs#bar
2019-10-22T22:01:44.1376476Z [ui] ui/meta-revision-bad.rs#foo 
```

This is *presumably* related to the `should_fail` attribute. i.e., that test uses an intentionally incorrect `error-pattern` and checks that we notice that. It seems like maybe the failure is alerting us to the that `error-pattern` attribute is being ignored by UI tests? Based on a quick examination of the code, I am guessing that is correct.

Here is the code for run-fail tests:

https://github.com/rust-lang/rust/blob/caa1f8d7b3b021c86a70ff62d23a07d97acff4c4/src/tools/compiletest/src/runtest.rs#L418-L419

For UI tests though we only do this:

https://github.com/rust-lang/rust/blob/caa1f8d7b3b021c86a70ff62d23a07d97acff4c4/src/tools/compiletest/src/runtest.rs#L3136-L3138

**Comment by nikomatsakis** [comment]
@nvlbg how do you feel about attempting a fix of compiletest here? :)

**Comment by nvlbg** [comment]
@nikomatsakis I'll give it a shot

**Comment by tmiasko** [comment]
This should be considered to be blocked on #65759, which starts to tests error
patterns and annotations for run-fail tests placed in ui (since they are
currently silently ignored).

**Comment by nikomatsakis** [comment]
Given that #65759 has landed, should this be rebased?

**Comment by hdhoang** [comment]
ping from triage @nvlbg, can you take a look at the failing checks? thanks!

**Comment by JohnCSimon** [comment]
pinging again from triage 
@nvlbg, can you please take a look at the failing checks? 
thank you

**Comment by Dylan-DPC** [comment]
@nvlbg can you rebase instead of merging? Thanks

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/rust/issues/66929: for now we shouldn't move run-fail tests to ui as that breaks `--pass check`.

**Comment by nikomatsakis** [comment]
Hmm, given that this is blocked, and quite old, I'm going to close the PR for the time being to help clear up my PR queue. @nvlbg feel free to re-open another time. =)

**Pull request closed without merging**
