### PR TITLE
Initialize LLVM's AMDGPU target machine, if available.

### PR DESCRIPTION
**Pull request by DiamondLovesYou**
Note this isn't useful, yet. More changes will be necessary to be able to
actually codegen for this machine. As such, it is not enabled by default.

This patch is on its own for the benefit of the reviewers.

### CODE REVIEW

**Comment by nicokoch** [comment]
Will this enable Rust on the GPU in the long term? Is there any kind of RFC/tracking issue one can follow?

**Comment by LifeIsStrange** [comment]
Rust on the gpu would be fantastic, but this doesn't seems to be an extension to SYCL which support many languages, if it's standard rust, how will it work ?
Because from my understanding, a gpu has more contraints than cpus, e.g you must be able to specify if what you allocate is on the gpu, cpu or shared (unified memory), also some things like recursives are more restricted. 
Wouldn't it be better to add rust support to SYCL ?

This doesn't seems to be difficult as it's more about removing feature support than adding them :) 
For openCL "Function pointers, bit fields and variable-length arrays are omitted, recursion is forbidden.[17]"
https://en.m.wikipedia.org/wiki/OpenCL

And you should use the language agnostic SPIR-V back-end. 
"In order to open the OpenCL programming model to other languages or to protect the kernel source from inspection, the Standard Portable Intermediate Representation (SPIR)[14] can be used as a target-independent way to ship kernels between a front-end compiler and the OpenCL back-end."

It's also more than openCL/SYCL, for example it's used by openGL and Vulkan (and others khronos apis) maybe even for WebGL-next), and HSA. 

Rust could arguably be the best language for GPUs, and others accelerators.
I think this could be a massive improvment !

**Comment by LifeIsStrange** [comment]
@pmarcell
Firstly thank you, you said many interesting things. 
So when I was saying we need to add rust support for sycl was effectively meaningless as it's not language agnostic. 
Instead we need to add rust as an api for openCL.
Quoting Wikipedia, "The OpenCL standard defines host APIs for C and C++; third-party APIs exist for other programming languages and platforms such as Python,[13] Java and .NET.[10]:15"
It would probably be very beneficial to study the github issues/rfcs of those languages.

Then we have two ways for adding rust support for GPUs, either we transpile rust to the c++ Subset that is sycl or to the OpenCL C or even to .NET.
This method (the reverse of the program corrode) would be quite Limited as rust support things that c++ can't support. 

The other paradigm would be to port the same gpu restrictions and Syntax (eg the kernel entry point) and the few features (single source, runtime compilation, gpu host memory support and optionally unified memory) than sycl.
That way we would not use the openCL Neither the sycl implementations and so we could use SPIR-V and this would be supported on platforms without openCL 2.1 as rust would not use the openCL runtime at all. 
And this would support new rust features without changes (while the first approach need to update the transpiler at every releases).

**Comment by pmarcelll** [comment]
I think most of the higher level languages generate OpenCL code, which is JIT compiled by the runtime, so no IR is involved. JIT compiling the source code is the default mode of OpenCL 1.2, the Wikipedia article describes some of the problems with this approach. This also works in Rust today via an ordianry API binding (and the kernels are still OpenCL C), and in theory it is possible to create something like SYCL 1.2 for Rust, but it probably would be a more difficult project than SYCL itself.

The second paradigm you described is not possible. The generated SPIR-V is fed to the OpenCL runtime, which is part of the GPU driver itself, it first compiles the SPIR-V to GPU machine code, and then the driver feeds this machine code to the GPU for execution.

If these PRs are accepted, rustc will be able to generate a binary that contains both the CPU and the GPU (in this case AMD) machine code. Rustc can already target Nvidia GPUs, so it's theoretically possible to hack something together to target both GPU vendors, but it still wouldn't be universally usable, like OpenCL (and even OpenCL is not universally usable, the only version that is supported everywhere is 1.2, Nvidia doesn't support 2.0 because they prefer CUDA, and their 1.2 implementation is slower than CUDA, AMD only supports OpenCL 2.0 with their ROCm runtime, and Intel only supports OpenCL 2.1, so the one year old OpenCL 2.2 specification is implemented by exactly zero GPU manufacturers).

**Comment by OvermindDL1** [comment]
> AMD only supports OpenCL 2.0 with their ROCm runtime, and Intel only supports OpenCL 2.1, so the one year old OpenCL 2.2 specification is implemented by exactly zero GPU manufacturers

I thought that was because they were both waiting for the OpenCL 2.2 backend to land in LLVM mainline, which it is doing right now I think (or just finished)?

**Comment by pmarcelll** [comment]
Landing it in upstream LLVM is important, but they could have implemented it in closed source drivers earlier.

BTW, sorry for spamming this PR with these conversations.

**Comment by OvermindDL1** [comment]
> Landing it in upstream LLVM is important, but they could have implemented it in closed source drivers earlier.

AMD doesn't have closed source drivers anymore, the last update was over a year ago for it (AMDGPUPRO) and their open-source AMDGPU driver has overtaken it in all functionality now.  :-)

_/me quite likes that Intel and AMD are well made enough to use fully open source drivers now, unlike nVidia_

But yeah, OpenCL 2.2 I think will come out shortly after LLVM is released stable with it.

**Comment by OvermindDL1** [comment]
Ah, I bet that is for some backwards compatibility bits.  the AMDGPUPRO driver is used by some propriatery older setups (AMDGPU only supports 'newer' GPU's, like 5 years old or newer).

> I also like that they open up most of the stack, but GPGPU is still a mess, which means it will be a lot harder for Rust to become a part of it.

Sounds like PR time?  ;-)

**Comment by DiamondLovesYou** [comment]
TBH, this whole ecosystem is a mess. Thankfully, targeting the GPU directly avoids most of this, though it has it's downsides.

**Comment by stokhos** [comment]
ping from triage @michaelwoerister will you have time to review this in near future?

**Pull request merged**
