### PR TITLE
perf: Revert accidental inclusion of a part of #69218

### PR DESCRIPTION
**Pull request by Marwes**
This was accidentally included in #69464 after a rebase and given
how much `inflate` and `keccak` stresses the obligation forest seems
like a likely culprit to the regression in those benchmarks.

(It is necessary in #69218 as obligation forest needs to accurately
track the root variables or unifications will get lost)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
> #69494 

That seems like the wrong PR

**Comment by nikomatsakis** [comment]
@bors r+

the perf run results, however, aren't visible yet

**Comment by nikomatsakis** [comment]
@bors r-

Hmm

**Comment by nikomatsakis** [comment]
@Marwes doesn't seem to have much impact on keccak... any thoughts?

**Comment by Marwes** [comment]
Trying to figure that out but I really can't find another place which would disproportionately affect keccak and inflate :S

**Comment by nikomatsakis** [comment]
@Marwes yeah -- you know about the self-profile options? Have you tried seeing if they show any particular impact?

**Comment by nnethercote** [comment]
@Marwes: Are you developing on Linux? I usually use Cachegrind to perform diffs between different revisions, it can be very helpful. Instructions are [here](https://github.com/rust-lang/rustc-perf/blob/master/collector/README.md), search for "Cachegrind".

**Comment by Marwes** [comment]
Adding some `#[inline]` fixed most of it with `inflate` only having regressed by 1.5% in my measurements.

@nnethercote I tried cachegrind but for whatever reason I can't get it to work. Tried with callgrind also and tried to view the output in kcachegrind (which I have used before) but I just get addresses displayed. I guess something makes valgrind/cachegrind/ etc not understand the debug information

**Comment by nnethercote** [comment]
@Marwes: your comment made me realize that the docs are missing a crucial part about setting a `config.toml` correctly. I just added a [new section](https://github.com/rust-lang/rustc-perf/blob/master/collector/README.md#preparation) explaining it. Could you try again with that? Cachegrind is great for detecting inlining issues, because an inlined function has no instruction counts on its first and last lines, while a non-inline function does.

**Comment by Marwes** [comment]
Used `debuginfo-level = 2` in my case which didn't work :/

**Comment by nnethercote** [comment]
Didn't work how? Can you show me some example output?

**Comment by Marwes** [comment]
Running `valgrind --tool=cachegrind --cache-sim=no --branch-sim=no ~/Code/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc  --crate-type=lib src/lib.rs`

And then running `cg_diff` on the output file just gives me a list of c/c++ functions, putting the same file into kcachegrind shows what I can only assume a are memory addresses display in lieu of debug info.

(Diffs a file with itself so everything is zero, still there are not rust functions in the diff)
```
fl=/build/glibc-OTsEL5/glibc-2.27/malloc/arena.c
fn=_int_free
0 0
fl=???
fn=std::ios_base::ios_base()
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/posix/../sysdeps/unix/sysv/linux/_exit.c
fn=_Exit
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/stdlib/msort.c
fn=qsort_r
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/elf/dl-lookup.c
fn=_dl_setup_hash
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/string/strdup.c
fn=strdup
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/nptl/../include/list.h
fn=__free_tcb
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/elf/../misc/sbrk.c
fn=sbrk
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/multiarch/../strlen.S
fn=strlen
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/multiarch/strcspn.c
fn=strcspn
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/math/../sysdeps/x86_64/fpu/multiarch/s_rint.c
fn=rint
0 0
fl=???
fn=std::_Rb_tree_decrement(std::_Rb_tree_node_base*)
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/csu/../sysdeps/unix/sysv/linux/x86_64/init-first.c
fn=_init
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/pthread-pids.h
fn=__pthread_initialize_minimal
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/elf/dl-load.c
fn=_dl_map_object
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/io/../sysdeps/unix/sysv/linux/poll.c
fn=poll
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/wcsmbs/../sysdeps/x86_64/multiarch/ifunc-avx2.h
fn=wcslen
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/posix/../sysdeps/unix/syscall-template.S
fn=getpid
0 0
fl=???
fn=std::ostream::flush()
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/x86_64/cancellation.S
fn=__libc_disable_asynccancel
0 0
fl=/build/glibc-OTsEL5/glibc-2.27/malloc/malloc.c
fn=_int_realloc
0 0
summary: 0
```

Screenshot from 2020-05-25 09-51-40

**Comment by Mark-Simulacrum** [comment]
Note that I'm not sure we'll rebuild the compiler for you, so you may need to x.py clean and rebuild.

Also, debuginfo level of 1 should be sufficient I suspect and significantly lighter on disk usage - I've personally seen IIRC tens of gigabytes of space savings.

**Comment by nnethercote** [comment]
I also recommend running Cachegrind via `collector`, rather than directly. I find it simpler that way.

**Comment by Marwes** [comment]
Cleaning and rebuilding does not help, nor does just using level 1 or running via collector.

Could use a perf run to validate that inlining helps.

**Comment by Aaron1011** [comment]
Great work @Marwes!

**Comment by Marwes** [comment]
It doesn't recover all the performance but it is at least most of it (1.5% regression remaining locally). However with #69218 it probably doesn't matter anyway, since that improves keccak and inflate by so much that it won't really be noticed.

**Comment by nnethercote** [comment]
The perf improvements from the landing are [here](https://perf.rust-lang.org/compare.html?start=2873165725c15e96dae521a412065c144d9c7a25&end=664fcd3f046e2a6824602da0fad81e3e2bb0d409&stat=instructions:u). Nice work!

**Pull request merged**
