### PR TITLE
Update Cargo submodule

### PR DESCRIPTION
**Pull request by alexcrichton**
Also update Cargo's dependencies while we're at it

### CODE REVIEW

**Comment by alexcrichton** [comment]
ping r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
@bors r+

Too many Cargo.lock changes...

**Comment by RalfJung** [comment]
Since this too so long anyway, could you include https://github.com/rust-lang/cargo/pull/5919? :D

**Pull request merged**
