### PR TITLE
Delay literal unescaping

### PR DESCRIPTION
**Pull request by nnethercote**
r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
For completeness, here is a program exhibiting all the relevant literal errors. The comments describe the current behaviour.
```rust
fn main() {
    // ---- SYNTACTIC (LEXING) ERRORS ----

    '';             // ZeroChars

    'ab';           // MoreThanOneChar

    "\x\\";         // InvalidCharInHexEscape + LoneSlash (a weird one)

    "\a";           // InvalidEscape

    "a^Mb";         // BareCarriageReturn
    r"a^Mb";        // BareCarriageReturnInRawString

    '   ';          // (TAB) EscapeOnlyChar

    "\x1";          // TooShortHexEscape

    "\xz";          // InvalidCharInHexEscape

    "\xff";         // OutOfRangeHexEscape

    "\u1234";       // NoBraceInUnicodeEscape

    "\u{xyz}";      // InvalidCharInUnicodeEscape

    "\u{}";         // EmptyUnicodeEscape

    "\u{1234";      // UnclosedUnicodeEscape

    "\u{_123}";     // LeadingUnderscoreUnicodeEscape

    "\u{1234567}";  // OverlongUnicodeEscape

    "\u{dfff}";     // LoneSurrogateUnicodeEscape

    "\u{123456}";   // OutOfRangeUnicodeEscape

    b"\u{1234}";    // UnicodeEscapeInByte

    b"🦀";          // NonAsciiCharInByte

    // ---- SEMANTIC (DELAYED) ERRORS ----

    "abc"xyz;       // InvalidSuffix

    1xyz;           // InvalidIntSuffix
    1u20;           // InvalidIntSuffix

    1.0xyz;         // InvalidFloatSuffix
    1.0f20;         // InvalidFloatSuffix

    0b10f32;        // NonDecimalFloat
    0o10f32;        // NonDecimalFloat

    0x100000000000000000000000000000000; // IntTooLarge

    c"a \0 b";      // NulInCStr 
}
```

This PR would make all of them delayed, i.e. compiling this program with `-Zparse-only` would produce no errors.

I'm going to argue for one of two outcomes here.
- Accept this PR. It makes for a consistent story: all literal checking is delayed. But it does preclude (or at least make more difficult) the addition of some hypothetical future escape syntax.
- Reject this PR, but change `NulInCStr` to a lexer error. It's a weird exception at the moment, being the only string literal error that is delayed. I'd be happy to implement that change in a separate PR. (In fact, it's already implemented as the "[Detect NulInCStr error earlier](https://github.com/rust-lang/rust/pull/118699/commits/8769da621024ac45597973706a7b11a7bffeb4b0)" commit in this PR).  I think there is still time for this because C string literals haven't reached the release channel yet.

I don't want to end up in a situation where some string literal errors are lexer-level and some are delayed (e.g. `\u{999999}`). I think that's ugly from both a language design POV and an implementation POV. The numeric literals are already like that, which is unfortunate, but let's not make it worse.

**Comment by nnethercote** [comment]
> I _do_ agree with this PR that having it be just either `\\u\{\x{1,6}\}` or `\\u\{\x+\}` from a _lexical_ sense would be a nice simplification, moving the USV requirements out to a semantic check instead.

It would simplify the lexical specification, at the cost of requiring a separate semantic check later. Overall that's less simple, IMO.

Likewise, from the implementation POV, it's nice if all the char/byte/string literal checking is in one place, be it the lexer, or HIR lowering. Having some checks in the lexer and others in HIR lowering is worse.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the T-lang triage meeting on 2023-12-20.  There were parts of this that the members liked (e.g. allowing an arbitrary string of `9`s), and there were parts of this the members did not (e.g. allowing `''`).

Our impression was that @nnethercote would prefer to go fully in one direction or the other here.  In our discussion, we were somewhat open to and curious about the direction of going the *other* way and rejecting syntactically more of those things that are semantically invalid.  @nnethercote, what are your thoughts on the desirability and feasibility of this?

Alternatively, if we were to go in the direction of relaxing the syntactic rules, we were interested in perhaps breaking these out.  @nnethercote, is this something you'd consider doing, and if so, what categories might you propose?

Please renominate this for us with your answers.

**Comment by nnethercote** [comment]
> Our impression was that @nnethercote would prefer to go fully in one direction or the other here. In our discussion, we were somewhat open to and curious about the direction of going the _other_ way and rejecting syntactically more of those things that are semantically invalid. @nnethercote, what are your thoughts on the desirability and feasibility of this?

I'm going to switch terminology from syntactic/semantic to lex-time/post-expansion, because I think the definition of what's syntactic vs. semantic is open to interpretation.

In general, you can't move post-expansion checks to lex-time, because that could break code that currently compiles. The one exception is NulInCStr, because that hasn't yet stabilized. I am advocating for moving that earlier in #119172 and [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/rfc.203349.3A.20mixed.20utf8.20literals), at least in the short term, for consistency with all the other byte/char/string literal checks. That needs to be done before stabilization occurs.

Moving from lex-time to post-expansion can be done at any time, because it's a backwards compatible change.

> Alternatively, if we were to go in the direction of relaxing the syntactic rules, we were interested in perhaps breaking these out. @nnethercote, is this something you'd consider doing, and if so, what categories might you propose?

Do you mean break them into categories? I don't particularly want to do that, because it would encourage a conclusion where some checks are done at lex-time and some post-expansion. (The attraction of this PR is that it moves all the checks to post-expansion, for maximum consistency.) But if you put a gun to my head I'd look at [this comment above](https://github.com/rust-lang/rust/pull/118699#issuecomment-1852867466) and come up with:
- Wrong length: ZeroChars, MoreThanOneChar
- Disallowed char: BareCarriageReturn, BareCarriageReturnInRawString, NonAsciiCharInByte, EscapeOnlyChar
- Invalid escape: all the others

**Comment by traviscross** [comment]
> In general, you can't move post-expansion checks to lex-time, because that could break code that currently compiles. 

We do have an edition coming up.  If we *could* do it, what things would we want to change to achieve consistency?

**Comment by petrochenkov** [comment]
There's a category of artificial errors, like "this can compile just right, but we don't want to accept it to avoid confusing human readers".
I think errors like `BareCarriageReturn(InRawString)` or some of `EscapeOnlyChar` are in this category.

If we want them reported at all, then we want them to be reported in lexer because human eyes look at code regardless of whether it's in `main`, `sink!` or `#[cfg(FALSE)]`.

**Comment by petrochenkov** [comment]
I don't think moving *all* errors either to post-expansion, or to lexer is a goal.
Having both points gives us enough flexibility to both report human-oriented (https://github.com/rust-lang/rust/pull/118699#issuecomment-1889462541) or future-proofing errors early, and to report "clearly semantic" errors at a later point.

The `NulInCStr` is in the "clearly semantic" category because it doesn't depend on how exactly the NUL is written lexically - `\0`, or `\x00`, or `\u{0}` - it's the lowered "semantic string content" that matters here.

**Comment by petrochenkov** [comment]
There's also a question of when a "not a literal" turns into a "literal with escaping problems", which is relevant to cases like `''`.
This is purely a question of error recovery strategy in the lexer, so perhaps the error reporting should also stay in the lexer for cases like this.

**Comment by petrochenkov** [comment]
Basically, I'm currently on the position that what we have now is fine, but we should probably remove some artificial errors.

**Comment by nnethercote** [comment]
> is https://github.com/rust-lang/rfcs/pull/3349 implemented yet?).

I have a partial implementation of RFC3349. There is no PR yet. It's blocked on two things:
- The decision on whether to delay literal unescaping checks or not (i.e. this PR).
- Some issues with the RFC itself, as described [here](https://github.com/rust-lang/rust/issues/116907#issuecomment-1853160194).

I know I wrote this PR, but I think I will close it. Why?
- It's getting in the way of RFC3349.
- This eager vs delayed checking discussion is prone to hair-splitting, e.g. about the exact meaning of "syntactic" vs "semantic", and what is or isn't "human-oriented". The kind of thing that can drag on and block useful progress.
- I'm motivated by (a) what is useful to users, and (b) what simplifies the implementation. For (a), eager checking is working pretty well right now and I haven't seen any compelling reasons to delay checking so far. For (b), and doing all the checks early simplifies the implementation.
- If we later find a compelling reason to delay checking, we can do so.

**Pull request closed without merging**
