### PR TITLE
#59361 Moved rustc edition opt to short list

### PR DESCRIPTION
**Pull request by peterjoel**
Addresses #59361, in case that issue is accepted.

### CODE REVIEW

**Comment by estebank** [comment]
I'll wait for @rust-lang/compiler discussion, which will probably not happen until next Thursday.

**Comment by nagisa** [comment]
I doubt this needs that much process or consensus from the whole team. Objectively looking at this, it is an obvious improvement.

@bors r+ Thanks!

**Comment by nagisa** [comment]
@peterjoel please adjust the message in your first comment to say `"Fixes #59361"` so that the issue is automatically closed once this merges.

**Comment by nagisa** [comment]
@bors r+.

Changing the comment, not commit message would have sufficed but this is also fine.

**Pull request merged**
