### PR TITLE
impl `From<&[T; N]>` for `Cow<[T]>`

### PR DESCRIPTION
**Pull request by tguichaoua**
Implement `From<&[T; N]>` for `Cow<[T]>` to simplify its usage in the following example.

```rust
fn foo(data: impl Into<Cow<'static, [&'static str]>>) { /* ... */ }

fn main() {
    foo(vec!["hello", "world"]);
    foo(&["hello", "world"]); // Error: the trait `From<&[&str; 2]>` is not implemented for `Cow<'static, [&'static str]>`
    foo(&["hello", "world"] as &[_]); // Explicit convertion into a slice is required
}
```

### CODE REVIEW

**Comment by workingjubilee** [comment]
Many additional impls involving common types that we've landed recently have resulted in ecosystem inference regressions, and many have had to be reverted. I recommend against accepting this patch, only to have to churn it on a later nightly, or at least deferring it for a while, if only because we need to not have so many potentially-regressing changes in-flight, so that we have hands free to catch the ones that _do_ regress.

For example:
- https://github.com/rust-lang/rust/issues/113238#issuecomment-1627338024
- https://github.com/rust-lang/rust/pull/113318

**Comment by compiler-errors** [comment]
We could at least run a crater run on this to assess inference breakage, but I'd say we only do that if T-libs-api is interested in accepting this implementation.

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

Since Rust 1.8, there already exists `From<&'a [T]> for Cow<'a, [T]>`.

This PR adds `From<&'a [T; N]> for Cow<'a, [T]>`.

Both impls create `Cow::Borrowed`.

The use case is people want to use function arguments of type `impl Into<Cow<[T]>>`, which works with Vec\<T\> and &amp;\[T\] but not currently &amp;\[T; N\].

**Review by dtolnay — APPROVED** [review]

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
