### PR TITLE
Ayu theme: Use different background color for Run button

### PR DESCRIPTION
**Pull request by tesuji**
Make it clearer that there is a button Run there.

Demo in https://github.com/rust-lang/rust/pull/74501#issuecomment-660597377 .

### CODE REVIEW

**Comment by lzutao** [comment]
I copy the rule from #74371.

**Comment by Cldfire** [comment]
Good idea! I agree that the run button should have a backing to make it easily recognizable.

I don't like the outline, though. It feels very out-of-place. I would prefer it if we went with something like this:

```css
a.test-arrow {
	font-size: 100%;
	color: #788797;
	border-radius: 4px;
	background-color: rgba(57,175,215,0.09);
}

a.test-arrow:hover {
	background-color: rgba(57,175,215,0.368);
	color: #c5c5c5;
}
```

Which looks like:

image

This is also more in line with what the existing themes do, and it works better on mobile aspect ratios:

image

The outline approach makes this even harder to read.

**Review by Cldfire — APPROVED** [review]
LGTM, thank you!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
