### PR TITLE
rustbuild: Fix dependencies of build-manifest

### LINKED ISSUE #44140: ./x.py dist hash-and-sign builds LLVM
This is what rust-central-station does when making a release, it shouldn't need to build anything other than libstd!

### PR DESCRIPTION
**Pull request by alexcrichton**
No need to depend on librustc! All we need is libstd

Closes #44140

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Good point. I think the original reason this was librustc is because it depends on proc macros, but since we currently build in stage0 that's fine I believe. Worst case is it doesn't work (and I assume we test that somewhere and at least manually).

@bors r+

**Comment by alexcrichton** [comment]
We're gonna backport this to make deployments easier on beta/stable

**Pull request merged**
