### PR TITLE
Prevent rustc overwriting input files

### LINKED ISSUE #13019: rustc overwrites input file when it has no extension
```
% echo 'fn main() {}' > test
% rustc test
% ./test # input has been replaced with the output binary
```

Tested on OS X, af9368452d8578af219713b34f7e3be4bd085186.  Not that it makes sense to write Rust files with no extension, but if you do, rustc should not overwrite the input file by default.

### PR DESCRIPTION
**Pull request by varkor**
If rustc is invoked on a file that would be overwritten by the
compilation, the compilation now fails, to avoid accidental loss. This
resolves #13019. Kudos to @estebank, whose patch I finished off.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Would it be possible to perhaps avoid duplicating the invocation of `build_output_filenames` and reuse it being created elsewhere? Other than that though looks great!

**Comment by varkor** [comment]
Which invocation of `build_output_filenames` would be most appropriate to reuse? The one in `driver.rs` seems to be the only one that is guaranteed to be called — but then the input filename would probably need to be passed to `compile_input` as well. Is it preferable to add an extra parameter here to avoid the extra invocation?

**Comment by eddyb** [comment]
@varkor Yes, feel free to change `rustc_driver` APIs.

**Comment by varkor** [comment]
Done, thanks!

**Comment by alexcrichton** [comment]
Thanks! Looks like there's a test that's failing though?

**Comment by varkor** [comment]
Ah, let an invocation slip through the net. Fixed.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
