### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth 

Delayed Clippy sync. I didn't get to it over the weekend..

### CODE REVIEW

**Comment by camsteffen** [comment]
```
error[E0061]: this function takes 3 arguments but 1 argument was supplied
   --> src/tools/rls/rls-rustc/src/clippy.rs:62:9
    |
62  |         clippy_lints::register_pre_expansion_lints(&mut lint_store);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ --------------- supplied 1 argument
    |         |
    |         expected 3 arguments
```
Did this function change?

**Comment by flip1995** [comment]
Yes 413d255916a314ab8377a308e6b8f98a55301a55 changed that function. So we will have to do a RLS sync first.

**Comment by flip1995** [comment]
Ohoh, we can't update RLS, because we can't bump the Clippy version, because the Clippy packages have edition 2021, so `cargo` complains that it can't find them:

```bash
cargo update -p clippy_lints
    Updating git repository `https://github.com/rust-lang/rust-clippy`
    Updating crates.io index
    Updating git repository `https://github.com/rust-lang/rust-clippy`
error: no matching package named `clippy_lints` found
location searched: https://github.com/rust-lang/rust-clippy?rev=0c8799da5aabf72aee26053075d2bd73ef9f7789
required by package `rls v1.41.0 (/home/pkrones/rust-lang/rls)`
```

Let's investigate...

**Comment by flip1995** [comment]
Since we missed the time frame to get this into this release, I will close this in favor of the sync I'll do on Thursday.

**Pull request closed without merging**
