### PR TITLE
Stabilize f16c_target_feature

### LINKED ISSUE #1234: Why is `F16C` still unstable?
I noticed that most `x86_64` intrinsics were stable, yet `F16C` isn't. I'd like to know what is keeping it from hitting stable, and what can be done to make it stable. According to another [tracking issue comment](https://github.com/rust-lang/rust/issues/48556#issuecomment-743190548) there doesn't seem to be anything blocking it.

### PR DESCRIPTION
**Pull request by VoidStarKat**
Resolves https://github.com/rust-lang/stdarch/issues/1234

Library PR for stabilizing corresponding intrinsics: https://github.com/rust-lang/stdarch/pull/1366

See also #44839 tracking issue for target_feature

### CODE REVIEW

**Comment by petrochenkov** [comment]
>Why is `F16C` still unstable?

I had the same question when seeing this PR, this x86 feature is sufficiently old.
If @Amanieu [says](https://github.com/rust-lang/stdarch/issues/1234#issuecomment-961581661) nothing is blocking it, then let's stabilize.

Not sure whether an FCP is needed when stabilizing a minor target feature, probably not, so I'll only ping @rust-lang/compiler.

**Comment by pnkfelix** [comment]
@wesleywiser pointed out to me that there is some precedent for getting lang team sign off or at least rough approval on the stabilization of target features, see e.g. https://github.com/rust-lang/rust/pull/93745

I'm personally inclined to trust T-libs-api's judgement w.r.t. the specific stabilization of f16c, but I also want to keep T-lang design team or T-compiler aware of such changes in general, and give them the chance say that stabilizing even minor target features needs some kind of team sign off beyond just T-libs-api...

So, I am nominating this for both T-compiler and T-lang, just so that they each note the process that was followed here (namely, trusting the judgement of @Amanieu with their T-libs-api hat on), and get a chance to say that a different process should be followed either here or in other cases in the future.

(Having said all that, I don't see a need to revert this PR itself, not without input from at least one of the teams for which I nominated this for discussion.)

@rustbot label: I-lang-nominated I-compiler-nominated

**Comment by Amanieu** [comment]
My understanding is that the stabilization of the intrinsics in stdarch are under T-libs-api (https://github.com/rust-lang/stdarch/pull/1366, still in FCP). However the actual target feature for `#[target_feature]` and `#[cfg(target_feature)]` is under T-lang.

**Comment by apiraino** [comment]
I assume team discussion nominations can be removed by now

@rustbot  label -I-compiler-nominated -I-lang-nominated

**Pull request merged**
