### PR TITLE
add BinaryHeap::try_reserve and BinaryHeap::try_reserve_exact

### PR DESCRIPTION
**Pull request by TennyZhuang**
`try_reserve` of many collections were stablized in https://github.com/rust-lang/rust/pull/87993 in 1.57.0. Add `try_reserve` for the rest collections such as `BinaryHeap` should be not controversial.

### CODE REVIEW

**Comment by Xuanwo** [comment]
I think this PR should be part of https://github.com/rust-lang/rust/issues/48043

**Comment by TennyZhuang** [comment]
> I think this PR should be part of #48043

But the feature was stabilized in 1.57.0, we need another feature gate.

**Comment by yaahc** [comment]
lgtm, just needs a tracking issue. I agree that you should setup a new one since the related feature has already merged.

**Comment by TennyZhuang** [comment]
> lgtm, just needs a tracking issue. I agree that you should setup a new one since the related feature has already merged.

Is it necessary for me to create an RFC other than for tracking issues?

**Comment by yaahc** [comment]
> > lgtm, just needs a tracking issue. I agree that you should setup a new one since the related feature has already merged.
> 
> Is it necessary for me to create an RFC other than for tracking issues?

No, not in this case.

**Comment by TennyZhuang** [comment]
@yaahc Thanks for your review!

I've added a tracking issue #91789 and a feature gate `try_reserve_2`.

**Comment by yaahc** [comment]
Looks great, thank you very much!

@bors r+

**Pull request merged**
