### PR TITLE
[beta] Give a better error message for unknown derive messages

### PR DESCRIPTION
**Pull request by keeperofdakeys**
This PR improves the error message for unknown derive macros.

Currently unknown derives give the following error, which is very misleading:
```
`#[derive]` for custom traits is not stable enough for use. It is deprecated and will be removed in v1.15 (see issue #29644)
```

I'm currently working on a PR that will change this (https://github.com/rust-lang/rust/pull/39442) to the following:
```
cannot find derive macro `Foo` in this scope
```

This PR backports the (as yet unmerged) error message to beta/1.16 (it's a pity that this is probably too late for 1.15).

r? @jseyfried

### CODE REVIEW

**Comment by alexcrichton** [comment]
As a note to reviewers on this PR, we're not able to use @bors to approve branches going to beta, and it's in fact highly recommended to do so!

(just to avoid hitting the merge button)

**Comment by nikomatsakis** [comment]
@alexcrichton 

You wrote (emphasis mine):

> As a note to reviewers on this PR, we're **not** able to use @bors to approve branches going to beta, and it's in fact highly recommended to do so!

Did you mean: "we're NOW able"?

**Comment by alexcrichton** [comment]
Ooops, yes! To clarify

### @bors should be used to approve this PR


To be fair the "t" and "w" keys are ... not at all close to each other.

**Comment by nikomatsakis** [comment]
I'm a bit confused, what is this a backport of? And which beta does it have to land in?

**Comment by keeperofdakeys** [comment]
On 1.15, the code `#[derive(Foo)] struct A;` with an unrecognised derive macro `Foo` gets the error message `'#[derive]'  for custom traits is not stable enough for use. It is deprecated and will be removed in v1.15 (see issue #29644)`. As part of PR https://github.com/rust-lang/rust/pull/39442 the error message was updated. I intended this PR to update the error message to match that PR for the 1.16 beta/stable release.

**Comment by jseyfried** [comment]
@keeperofdakeys Did you test that this passes all tests locally? I'm not sure how much integration testing bors does on beta...

**Comment by alexcrichton** [comment]
@bors: p=1 

(PR against beta branch)

**Comment by alexcrichton** [comment]
This'll need to hold off on using @bors to merge until https://github.com/rust-lang/rust/pull/39546 lands unfortunately :(

**Comment by brson** [comment]
It might be prudent to wait still for patches to land on master before letting bors try to land them on beta, in case there are problems with the patch.

**Pull request merged**
