### PR TITLE
reference: slices do not contain elements, for they are just views

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by tshepang** [comment]
I'm not 100% sure

**Comment by Diggsey** [comment]
Personally I'd say that slices do *contain* elements, they just don't *own* those elements. Regardless of the exact interpretation though, this segment shouldn't just be removed: the important point is that it's impossible to access an uninitialised memory location using in-bounds access to either a slice or an array (modulo bugs in unsafe code).

**Comment by steveklabnik** [comment]
Yes, they do contain them, but they don't own them.

**Comment by tshepang** [comment]
@Diggsey should your statement sounds good. Should we use it like this:

> All in-bounds elements of arrays and slices are always initialized. That is,  it's impossible to access an uninitialised memory location using in-bounds access to either a slice or an array.

Or should we use it as-is, or just leave things as they are now?

**Pull request closed without merging**
