### PR TITLE
Stabilize `waker_getters`

### LINKED ISSUE #87021: Feature: Provide getters of data and vtable pointer for `RawWaker`?
[Docs of `std::task::RawWaker`](https://doc.rust-lang.org/stable/std/task/struct.RawWaker.html):
> It consists of a data pointer and a virtual function pointer table (vtable) that customizes the behavior of the RawWaker.

We said it consists of two pointer, but doesn't enforce its layout by `repr`, nor provide methods to get data and vtable pointer from a constructed `RawWaker`. So it impossible to destruct a `RawWaker` even with `transmute`, since the layout is unknown, which makdes it difficult to pass `RawWaker` or `Waker` across FFI boundary.

Note that `Waker` has `repr(transparent)` on it so it's able to `transmute` into a `RawWaker`. But it barely does anything since we can do nothing with a `RawWaker`. I'm confusing about why there is a `repr(transparent)` struct to an blackbox struct without any methods.

If it's intended to NOT stabilizing the layout of `std::task::RawWaker`. I think we should at least provide methods like `fn data(&self) -> *mut ()` and `fn vtable(&self) -> &'static RawWakerVTable` to do the inverse of `RawWaker::new`, which can be used to destruct it to cross FFI boundary.

### LINKED ISSUE #96992: Tracking Issue for `waker_getters`
Feature gate: `#![feature(waker_getters)]`

This is a tracking issue for getters of data and vtable pointers for `RawWaker`, and the method to get `RawWaker` from `Waker`.

### Public API

```rust
// core::task
impl RawWaker {
    pub fn data(&self) -> *const ();
    pub fn vtable(&self) -> &'static RawWakerVTable;
}
impl Waker {
    pub fn as_raw(&self) -> &RawWaker;
}
```

### Steps / History

- [x] Implementation: #91828
- [x] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- Do we also need `fn into_raw(self) -> RawWaker` for `Waker`? https://github.com/rust-lang/rust/issues/87021#issuecomment-1091899591

### PR DESCRIPTION
**Pull request by oxalica**
Close #96992
Close #87021

API summary:
```rust
// core::task
impl RawWaker {
    pub fn data(&self) -> *const ();
    pub fn vtable(&self) -> &'static RawWakerVTable;
}
impl Waker {
    pub fn as_raw(&self) -> &RawWaker;
}
```

### CODE REVIEW

**Comment by TiddoLangerak** [comment]
Has there been any progress on this recently? When could we expect this to land in stable?

**Comment by oxalica** [comment]
> Has there been any progress on this recently? When could we expect this to land in stable?

I'm not familiar with the formal stabilization steps. Seems we need an FCP.
r? rust-lang/libs-api

**Comment by Amanieu** [comment]
I raised a concern about the API in the tracking issue: https://github.com/rust-lang/rust/issues/96992#issuecomment-1342739726

**Comment by Dylan-DPC** [comment]
@oxalica any updates on this?

**Comment by Dylan-DPC** [comment]
Closing this as some concerns (listed on the tracking issue) still need to be resolved before we stabilise this so it's going to be a while.

**Pull request closed without merging**
