### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #119582 (bootstrap: handle vendored sources when remapping crate paths)
 - #119730 (docs: fix typos)
 - #119828 (Improved collapse_debuginfo attribute, added command-line flag)
 - #119869 (replace `track_errors` usages with bubbling up `ErrorGuaranteed`)
 - #120037 (Remove `next_root_ty_var`)
 - #120094 (tests/ui/asm/inline-syntax: adapt for LLVM 18)
 - #120096 (Set RUSTC_BOOTSTRAP=1 consistently)
 - #120101 (change `.unwrap()` to `?` on write where `fmt::Result` is returned)
 - #120102 (Fix typo in munmap_partial.rs)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=119582,119730,119828,119869,120037,120094,120096,120101,120102)

### CODE REVIEW

**Comment by Kobzol** [comment]
No, that was not it.

@rust-timer build d62113ddf8b52917059346f0d11c3b2e6880437b

**Comment by compiler-errors** [comment]
No, but looking back at the PR that added the helper function that I removed, it seems to have just undone the perf win here:

https://github.com/rust-lang/rust/pull/112702#issuecomment-1594965566

So I think we can just ignore this perf regression.

**Comment by Kobzol** [comment]
Ok.

@rustbot label: +perf-regression-triaged

**Pull request merged**
