### PR TITLE
[Experiment] Test rustc perf if compiled for x86-64-v3

### PR DESCRIPTION
**Pull request by hkratz**
This can of course not be committed but it might be interesting too see how much perf would be gained (or lost) from AVX2 auto-vectorization and other [x86-64-v3 micro-architecture](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels) optimizations.

r? @ghost

### CODE REVIEW

**Comment by the8472** [comment]
looks like a network error

@bors retry

**Comment by hkratz** [comment]
> looks like a network error

It's a cert verification failure due to another updated cert whose ca is no recognized by the ancient Debian image.

**Comment by the8472** [comment]
Oh.

@bors cancel

**Pull request closed without merging**
