### PR TITLE
Add support for custom mir

### PR DESCRIPTION
**Pull request by JakobDegen**
This implements rust-lang/compiler-team#564 . Details about the design, motivation, etc. can be found in there.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
> I don't know if this needs an MCP. I can put one up if necessary.

Please do, even if we just use it as an announcement

**Comment by JakobDegen** [comment]
I'll put one up later today. I'll squash all three commits in the branch then though, will be a little bit harder to review but will more accurately represent the MVP.

**Comment by JakobDegen** [comment]
Squashed commits and MCP is up

**Comment by JakobDegen** [comment]
First commit is gone since that PR merged. Marking as ready since I have no more changes planned to this PR, still might want to wait for the FCP to finish though

**Comment by matthiaskrgr** [comment]
@bors r-
looks like this failed in a rollup: https://github.com/rust-lang/rust/pull/104167
https://github.com/rust-lang/rust/actions/runs/3422647986/jobs/5700299869#step:25:1577

**Comment by JakobDegen** [comment]
Semantic conflict with my own change, will rebase and fix later today

**Pull request merged**
