### PR TITLE
Add missing stability annotations on reexports

### PR DESCRIPTION
**Pull request by petrochenkov**
Extracted from https://github.com/rust-lang/rust/pull/29083
I'll redo https://github.com/rust-lang/rust/pull/29083 in some time and it will be much smaller and easier to review without this part

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm I [have the same concerns as before](https://github.com/rust-lang/rust/pull/29083#discussion_r42522088) where if we start annotating reexports we may want to hammer down the semantics first. For example what does it mean to have a stable reexport of an unstable item? An unstable reexport of a stable item? I'd personally expect:

* Stable reexport of stable -- ok, everything is stable
* Unstable reexport of unstable -- ok, everything is unstable
* Stable reexport of unstable -- compiler error
* Unstable reexport of stable -- ok, unstable to reference via this name but stable to reference via the other name.

**Comment by petrochenkov** [comment]
Yes, I'd like to hear what people actually dealing with library stabilization want and expect.
I suppose the same scheme will be used later in third party crates when stability/deprecation is available for them.
Below I consider, that all variants are implementable without complete rewrite of resolve :smile: (I'm not sure in it yet), i.e. every imported name knows through which `use` it was imported.

One pole is maximum flexibility - an original entity can be accessed with different names imported through multiple imports, or without imports at all if it can be accessed directly. Each of these paths should have its own stability/deprecation attribute and they are completely independent.
A name can be deprecated and the new non-deprecated name created with `use`.
An item in e.g. libcore can be unstable and be moved around libcore freely, but have a stable reexport in libstd which location is fixed.

Another extreme is "one true stability" - every accessible entity have a stability attribute on it and aliases are completely ignored. In this case it would be better to make annotating them an error and remove existing annotations to avoid confusion.

Both approaches have drawbacks, however. "One true stability" is too rigid - you can't rename things and deprecate old names. With "maximum flexibility" even if an item is unstable we can't change its signature if it's stably reexported, it can be mitigated by "Stable reexport of unstable -- compiler error" as you mentioned, and keeping only deprecation attributes completely independent. Some new form of stability inheritance can be introduced, so reexports will possibly have, but not *require* stability, their stability will be inherited from the exported items if necessary and still considered by the checking pass. Or stability of `use` can be inherited from its containing module (but it seems useless).

In general, I have no strong opinion and can, e.g. "revert" this PR and delete the confusing existing annotations instead until they are actually considered, or I can leave everything optional, as now. That's why I'd like to hear more opinions.

**Comment by alexcrichton** [comment]
Hm yes, all valid points! cc @rust-lang/libs, thoughts?

**Comment by Gankro** [comment]
I definitely agree with @alexcrichton's intuiton here.

One true stability doesn't seem good for anyone, but I'd also prefer stability to be inherited by default in re-exports. So we don't need to annotate all re-exports. Only the ones that we want to.

I'm a bit on the fence about stable of unstable. My gut reaction is that it *could* be useful, and I can't imagine it would be a big problem?

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the conclusion was that [the semantics I outlined above](https://github.com/rust-lang/rust/pull/29626#issuecomment-154452859) were the ones we'd like to settle on. To move this forward, perhaps this could be included with the PR that actually verifies these attributes? It's pretty easy to skip past annotations like this in a review so it's not critical it be split out.

**Comment by petrochenkov** [comment]
>To move this forward, perhaps this could be included with the PR that actually verifies these attributes? It's pretty easy to skip past annotations like this in a review so it's not critical it be split out.

Sorry, I have linguistic difficulties with these two sentences.
First, should attributes be verified in this PR, or new annotation added in some future PR? (I think, the latter). Second, what is not critical to be split out from what?

Also, what's about inheritance by default? (`use A as B;` inherits stability of `A` by default).
Currently, I tend to "revert" this PR and remove existing annotations on reexports, because they are all would be unnecessary with inheritance (in addition to being completely unchecked now).

**Comment by alexcrichton** [comment]
Ah sorry I'm not always the most eloquent person either! To answer your questions:

> First, should attributes be verified in this PR, or new annotation added in some future PR?

I was thinking this could be lumped in https://github.com/rust-lang/rust/pull/29083 with other stability changes.

> Second, what is not critical to be split out from what?

Ah I was just saying that it was not critical to split off this sort of boilerplate changes from #29083 to make it easier to review. 

> Also, what's about inheritance by default?

I personally like the motto that unstable inherits and everything stable must be annotated as such, it gives convenient behavior where expected and requires work where expected as well!

**Comment by petrochenkov** [comment]
Applied to https://github.com/rust-lang/rust/pull/29083, closing.

**Pull request closed without merging**
