### PR TITLE
resolve/hygiene: `macro_rules` are not "legacy"

### PR DESCRIPTION
**Pull request by petrochenkov**
The "modern" vs "legacy" naming was introduced by jseyfried during initial implementation of macros 2.0.
At this point it's clear that `macro_rules` are not going anywhere and won't be deprecated in the near future.
So this PR changes the naming "legacy" (when it implies "macro_rules") to "macro_rules".
This should also help people reading this code because it's wasn't obvious that "legacy" actually meant "macro_rules" in these contexts.

The most contentious renaming here is probably
```
fn modern -> fn normalize_to_macros_2_0
fn modern_and_legacy -> fn normalize_to_macro_rules
```
Other alternatives that I could think of are `normalize_to_opaque`/`normalize_to_semitransparent`, or `strip_non_opaque`/`strip_transparent`, but they seemed less intuitive.
The documentation to these functions can be found in `symbol.rs`.

r? @matthewjasper

### CODE REVIEW

**Comment by Centril** [comment]
> The most contentious renaming here is probably

This seems like a good idea, much clearer!

**Review by eddyb — APPROVED** [review]
r=me on the renaming diff if nobody disagrees on the choices themselves

**Pull request merged**
