### PR TITLE
[Experiment] Rewrite exhaustiveness in one pass

### PR DESCRIPTION
**Pull request by Nadrieril**
I've had this in mind for a looong time now. Arm reachability checking does a quadratic amount of work: for each arm it checks if it is reachable given the arms above it. This feels wasteful since we often end up re-exploring the same cases when we check for exhaustiveness.

This PR is an attempt to check reachability at the same time as exhaustiveness. This opens the door to a bunch of code simplifications I'm very excited.

Last time I tried I utterly destroyed performance. Until I get the right permissions to run `perf` in my dev environment, I'll run perf from here if that's ok.

r? @ghost

### CODE REVIEW

**Comment by Nadrieril** [comment]
I didn't know doc errors would stop bors 🙈

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
Those are excellent numbers :3

**Comment by Nadrieril** [comment]
Alright I reworked all the integer-range-related stuff, should be tons faster

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
This makes no sense I'm measuring a 14% *improvement* on match-stress locally :'(

**Comment by Kobzol** [comment]
Cycle wins are pretty nice: https://perf.rust-lang.org/compare.html?start=f3d597b31c0f101a02c230798afa31a36bdacbc6&end=7a6baddc69eb6fadc114345e5ca1eb81f2a07807&stat=cycles:u So I wouldn't mind the instruction regressions.

**Comment by nnethercote** [comment]
Walltime results are also nice, up to 8% wins on match-stress. Instruction counts are a decent metric in general, but the larger the change, the less reliable they become, and this seems like a fairly large change.

**Comment by Nadrieril** [comment]
Ohh nice I never checked the other metrics, ty both

**Comment by Nadrieril** [comment]
I lost momentum because of the perf issue, should come back to this this week or the next

**Comment by Kobzol** [comment]
@Nadrieril I'm curious, why did you close this? The perf. results on the match stress enum were really nice.

**Comment by Nadrieril** [comment]
I'm still excited about it and hope to finish it! But I lost momentum and life happened and I don't expect to be able to come back to it for weeks if not months :/. I'm closing it in the meantime for triage purposes

**Comment by Kobzol** [comment]
I see. Take care!

**Pull request closed without merging**
