### PR TITLE
interpret: fix CheckedBinOp behavior when overflow checking is disabled

### PR DESCRIPTION
**Pull request by RalfJung**
Adjusts the interpreter to https://github.com/rust-lang/rust/pull/98738.

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
Uh, ConstProp is not happy with this...

**Comment by tmiasko** [comment]
I don't think CTFE should change the behaviour based on the options from the session. This would risk introducing cross-crate non-determinism in the execution.

Conceptually I was considering CTFE to simply have overflow checking enabled, and so already in agreement with wording from #98738, but I can make this explicit.

**Comment by RalfJung** [comment]
> I don't think CTFE should change the behaviour based on the options from the session. This would risk introducing cross-crate non-determinism in the execution.

You specified MIR behavior to depend on the session options. CTFE should accurately implement MIR behavior.

If this is fine for codegen, then why not for CTFE?

**Comment by RalfJung** [comment]
FWIW I would much prefer if CheckedBinOp would just always check for overflow. Also note that the code here is not just for CTFE, it is also for Miri.

I don't understand these CI failures though, ConstProp does not even call this function, it directly calls `overflowing_binary_op`...

**Comment by RalfJung** [comment]
> This would risk introducing cross-crate non-determinism in the execution.

I guess it does mean that the same query executed in different crates can have different results. Which indeed sounds bad.
But the same seems to be true for the codegen queries, so... not sure what to make of this.

Also is it really so easy to break the query system? I have no idea if our other accesses to `tcx.sess` are any better...

**Comment by RalfJung** [comment]
> I don't understand these CI failures though, ConstProp does not even call this function, it directly calls overflowing_binary_op...

Oh, these are not actually lints. Those are const-evaluations that used to fail because we always overflow-check arithmetic in `const`/`static` (we always generate CheckedBinaryOp), but now that we honor the same flag as codegen, we don't check this any more.

I suppose I could add a machine flag to control this, so Miri can behave like codegen and CTFE can behave like before.

**Comment by oli-obk** [comment]
r=me with CI happy

**Comment by tmiasko** [comment]
> > This would risk introducing cross-crate non-determinism in the execution.
> 
> I guess it does mean that the same query executed in different crates can have different results. Which indeed sounds bad. But the same seems to be true for the codegen queries, so... not sure what to make of this.
> 
> Also is it really so easy to break the query system? I have no idea if our other accesses to `tcx.sess` are any better...

I wasn't referring to the determinism in context of a query system and I don' see any immediate issue there since overflow checking is controlled by tracked options.

I was referring to the determinism as a fundamental property that CTFE should have. It would be rather bad if non-deterministic computation is lifted into the type system and different crates have a different view of what the types are.

In the specific case of overflow checking, maybe there is some argument to be made that given how MIR is built the only other behaviour would be an evaluation error ...

The proposed changes looks go to me. Thanks for updating this.

**Pull request merged**
