### PR TITLE
Add all unstable features to Unstable Book.

### PR DESCRIPTION
**Pull request by frewsxcv**
Add all unstable features to the Unstable Book, also remove a few that
either no longer exist or were promoted to stable.

These changes were extracted out of
https://github.com/rust-lang/rust/pull/40694

### CODE REVIEW

**Comment by steveklabnik** [comment]
https://travis-ci.org/rust-lang/rust/jobs/214510619#L1351 ....... wat

**Comment by frewsxcv** [comment]
This should be passing now. The issue was that I was missing a file linked from the SUMMARY.md so mdbook was trying to create it, which caused the readonly error. This should be fixed now.

r? @steveklabnik

**Comment by steveklabnik** [comment]
> The issue was that I was missing a file linked from the SUMMARY.md so mdbook was trying to create it, which caused the readonly error.

Oh nooo!

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks 😄

**Pull request merged**
