### PR TITLE
update miri

### PR DESCRIPTION
**Pull request by RalfJung**
I will keep updating this PR as miri master gets updated to follow rustc changes, so that hopefully we can get miri green again in the toolstate. :)

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
p=1? I was thinking this can easily wait until at least your alloc PR and my escape-to-raw PR have landed, both of which will break miri again anyway.

**Comment by oli-obk** [comment]
well, toolstate updates happen with priority. Otherwise I'd suggest to close this PR and open it later.

If we r+, but expect it not to get merged, then we shouldn't r+.
If we do not r+, but wait for other PRs, then we could mark it as blocked, but I don't know why we'd have a submodule update PR open before the other PRs are merged.

**Comment by RalfJung** [comment]
Okay I'll close then and reopen (or open a new one) when both of the aforementioned PRs have landed.

**Pull request closed without merging**
