### PR TITLE
demonstrate `RHS != Self` use cases for `Add` and `Sub`

### PR DESCRIPTION
**Pull request by matthew-piziak**

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks a ton, this is great!

**Comment by jonathandturner** [comment]
@bors r-

Looks like this might be causing a possible issue on Windows.  @steveklabnik any idea what might cause:

```
Linkcheck stage2 (i686-pc-windows-gnu)
core\ops\trait.Add.html:121: broken link - time\struct.SystemTime.html
core\ops\trait.Sub.html:95: broken link - time\struct.SystemTime.html
std\ops\trait.Add.html:121: broken link - time\struct.SystemTime.html
std\ops\trait.Sub.html:95: broken link - time\struct.SystemTime.html


command did not execute successfully: "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-tools\\i686-pc-windows-gnu\\release\\linkchecker.exe" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\doc"
expected success, got: exit code: 101


Makefile:49: recipe for target 'check' failed
>> rustjob: found 0 remaining processes
```

**Comment by steveklabnik** [comment]
Does it need one `..` and not two, maybe?

**Comment by jonathandturner** [comment]
@steveklabnik - no idea.  Who's a good contact for rustdoc?

**Comment by jonathandturner** [comment]
I wonder if @brson or @alexcrichton might know...

**Comment by alexcrichton** [comment]
I think the links here may have just one too many `../`?

**Comment by matthew-piziak** [comment]
@alexcrichton Is that the case? If I take https://doc.rust-lang.org/nightly/std/ops/trait.Add.html and add `/../../time/struct.SystemTime.html`. to the end of it, then it seems to navigate correctly. There's the question of the leading slash, of course. Now, a bigger issue for me is that I'm unable to test docs changes locally (`rustdoc` fails on multiple machines). If anybody wants to help me debug it on `#rust-docs`, that would be hugely helpful.

**Comment by alexcrichton** [comment]
Sometimes the traits are rendered in multiple locations due to inlining in rustdoc, so maybe that's what's happening here?

**Comment by matthew-piziak** [comment]
I'm having difficulty testing this. When I run `cargo docs` in `src/libstd` on nightly I get: 
`error: couldn't read "/Users/matt/rustfork/rust/src/rustc/libc_shim/../../liblibc/src/lib.rs": No such file or directory (os error 2)`

**Comment by ollie27** [comment]
> If I take https://doc.rust-lang.org/nightly/std/ops/trait.Add.html and add /../../time/struct.SystemTime.html. to the end of it, then it seems to navigate correctly.

That's not what the browser does. It basically tries to load `https://doc.rust-lang.org/nightly/std/ops/../../time/struct.SystemTime.html` which of course fails. So yeah, there is one too many `../`s.

As far as I know the most reliable way to build the docs for testing is to use `make docs` see [here](https://github.com/rust-lang/rust#building-documentation).

**Comment by matthew-piziak** [comment]
Thanks @ollie27! Fixed.

**Comment by matthew-piziak** [comment]
Looks like the build is still being weird here. I don't think it's my fault this time...

**Comment by steveklabnik** [comment]
Yes, this is not you.  Let's give it a shot again on bors.

@bors: r+ rollup

**Comment by TimNN** [comment]
This still fails linkcheck for me:

```
core/ops/trait.Sub.html:121: broken link - core/time/struct.SystemTime.html
core/ops/trait.Add.html:121: broken link - core/time/struct.SystemTime.html
```

**Comment by matthew-piziak** [comment]
Anybody have advice on how to run linkcheck locally?

**Comment by matthew-piziak** [comment]
@matthew-piziak
```
cd src/tools/linkchecker
cargo run ../../lib_you_want_to_check
```

**Comment by matthew-piziak** [comment]
@TimNN I cannot reproduce.

Here is my repro attempt: 
- `make docs`
- open `file:///home/matt/rustfork/rust/doc/std/ops/trait.Sub.html` in Chromium
- click on `std::time::SystemTime` link

This navigates to `file:///home/matt/rustfork/rust/doc/std/time/struct.SystemTime.html` as expected.

**Comment by TimNN** [comment]
The problem is that `Add` / `Sub` are document in both `core` and `std`, however `time` is only in `std`.

Try the links from `file:///home/matt/rustfork/rust/doc/core/ops/trait.Sub.html` and you should get a 404.

**Comment by matthew-piziak** [comment]
Thanks @TimNN!

**Comment by steveklabnik** [comment]
Travis looks spurious, let's try with bors.

@bors: r+ rollup

**Pull request merged**
