### PR TITLE
Revert "Parse `Ty?` as `Option<Ty>` and provide structured suggestion"

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Reverts https://github.com/rust-lang/rust/pull/92746

References #94510 

r? @davidtwco 

cc @estebank

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
beta-nom as this fixes a regression which has slipped into beta.

**Comment by estebank** [comment]
Can we hold off on merging until tomorrow? I'm seeing if I can patch the logic to be correct in the first place.

**Comment by davidtwco** [comment]
r=me if necessary but I've approved #94593

**Comment by Dylan-DPC** [comment]
closing this as this is not needed

**Pull request closed without merging**
