### PR TITLE
Make docs required again

### PR DESCRIPTION
**Pull request by brson**
Completely untested. Fixes https://github.com/rust-lang-nursery/rustup.rs/issues/903

r? @alexcrichton cc @steveklabnik

### CODE REVIEW

**Comment by brson** [comment]
Nominating because it's a simple regression fix.

**Comment by alexcrichton** [comment]
@bors: p=1

(beta nominated)

**Comment by alexcrichton** [comment]
@bors: retry

* spurious sccache failure https://github.com/rust-lang/rust/issues/40240

**Pull request merged**
