### PR TITLE
[draft] Store the path in io::Error without extra allocations.

### PR DESCRIPTION
**Pull request by m-ou-se**
This stores the path of the file/directory in io::Error, without doing any allocations and without increasing the size of io::Error.

We need to allocate for doing a syscall on a path anyway, so this just keeps that allocation around in the io::Error if the syscall fails.

This implements it only on unix. But it can work similarly on other platforms as well.

It does not store the path for the rename and (sym)link operations, as they involve two paths, and you can't really tell which of the two paths caused the error.

This only shows the path in the Debug implementation of io::Error. It's not clear what else we should do with it. Putting it in Display will make many programs show the path twice, and have less control over the output format. Adding a .path() accessor to io::Error is also not great, because it'll have to be a Option, and won't be accessible through the Error triat.

### CODE REVIEW

**Comment by m-ou-se** [comment]
cc @yaahc

**Comment by m-ou-se** [comment]
@CryZe Since you reacted with a :-1:, I'd be curious to hear your thoughts on this.

**Comment by CryZe** [comment]
> @CryZe Since you reacted with a 👎, I'd be curious to hear your thoughts on this.

Haha, yeah alright. I have nothing against the implementation, but rather against the concept as a whole. While yes it is indeed a nice ergonomics improvement, I disagree that the path should be there in the first place. Let's say I parse an integer and that fails with a ParseIntError. Then in the end, what will propagate up is some sort of "Failed to parse integer, invalid digit" (I didn't bother checking the actual message). However what actually failed, is possibly parsing a width or a height in some image format, or whatever we were trying to parse. It is the exact same kind of problem where the integer doesn't carry enough semantic information for the error to then contain that semantic information. What actually should be happening here instead is that some layer higher up knows what the integer was meant to be for and should annotate that via an appropriate context. The same thing applies to the File where a higher level may decide to either:
- Show the full path.
- Show a relative path as part of the application's folder or some sort of virtualized path in case of WASI.
- Show a more meaningful name instead ("Failed parsing the configuration.")

I agree that it's more ergonomic if you don't need to bother, but what we instead need are better ways of annotating context and not magic that only applies to File that can't be configured.

**Comment by yaahc** [comment]
@CryZe I will note that we have only added the path info to the `Debug` format, not to Display, precisely because people already add the path at a higher level where they have that context on the semantics of it's usage. Does this change your reaction?

**Comment by CryZe** [comment]
Yeah I guess that may be fine then.

**Comment by sunfishcode** [comment]
It's possible that in the future, std could be optimized to avoid `alloc`ing the path buffer in common cases, using a technique like [this](https://github.com/bytecodealliance/rsix/blob/main/src/path/arg.rs#L1238) which can be about 2.5% faster in microbenchmarks that include the system call. If Rust does that, would it still be ok `alloc`ing in the error path to continue to support storing the path in the `Error`?

**Comment by thomcc** [comment]
Since it was brought up to me, https://github.com/rust-lang/rust/pull/87869 and this aren't really incompatible beyond it needing to allocate in the 64 bit case (on 32 bit targets it would be almost identical).

(IMO that's probably fine, since this is in the error case, and that having a smaller io::Error optimizes the success path more than allocating in the error case would pessimize anything)

**Comment by ben0x539** [comment]
When making the OsPathBuf allocation, can't you just leave some room for the error kind field in there, even if it's not needed in the success case? (With 64 bit, maybe half of the string length usize unless we assume path names can be too long for u32 length field?)

**Comment by ben0x539** [comment]
> It does not store the path for the rename and (sym)link operations, as they involve two paths, and you can't really tell which of the two paths caused the error.

Can store both of them, like, allocated contiguously?

**Comment by saethlin** [comment]
@sunfishcode The link in your comment above is now broken, at a guess because it wasn't a permalink that included the git commit. Did you mean this: https://github.com/bytecodealliance/rustix/blob/e1ec8abf106e976bc05ce45d308602728e84ccf3/src/path/arg.rs#L933-L953

**Comment by sunfishcode** [comment]
@saethlin Yes; that's the right link. But also, there is now a PR implenting this in Rust, which may land soon: https://github.com/rust-lang/rust/pull/93668

**Pull request closed without merging**
