### PR TITLE
issue has since been fixed

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
The issue is closed, but I don't think this is actually fixed. We don't (AFAIK) test the non-cgu=1 configuration on CI.

**Comment by tshepang** [comment]
should a new issue be opened, so that this points to something open

**Comment by Mark-Simulacrum** [comment]
I think we should just drop the issue link, this is always going to be a little buggy unless we test it in CI. I don't expect CI testing here to be worth the cost.

r=me with that done.

**Pull request merged**
