### PR TITLE
BufReader: In Seek impl, remove extra discard_buffer call

### PR DESCRIPTION
**Pull request by czipperz**
As far as I can tell, this code does nothing.  I'm not sure why it even is there.

### CODE REVIEW

**Comment by czipperz** [comment]
Since this will be peer reviewed, I might as well ask: should this refactored to not use a `result` variable?  It would simplify the code but would require storing the `pos` and `cap` fields locally (`discard_buffer` resets them).

**Comment by czipperz** [comment]
It seems this was introduced in the [original implementation](https://github.com/rust-lang/rust/commit/0a380a9318cb450fc54153c1327a35cf02fab8e6#diff-a074b6c6ae44d9ac353aa145411afb53R157).  It's been dead code for a while.

**Comment by taiki-e** [comment]
I tried to do the same when I added async BufReader in futures-rs, but that was not correct (https://github.com/rust-lang-nursery/futures-rs/pull/1573#discussion_r281162309).

There is no `Pending` in `std::io`, but there is [a case to retry when `ErrorKind::Interrupted` is returned](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/io/allow_std.rs#L23-L35), so I think the same problem will occur when called in the order Ok - Err(ErrorKind::Interrupted).

**Comment by czipperz** [comment]
Mmh so it's because of the `?` on the next line. Shoot

**Comment by czipperz** [comment]
I'm going to add try to add a test so this behavior is ensured.

**Comment by taiki-e** [comment]
> it's because of the `?` on the next line.

Yeah, after early return with the next line's `?` operator, enter the same branch again and call `inner.seek(SeekFrom::Current(-remainder))?`. Since we are calling `inner.seek(SeekFrom::Current(-remainder))` twice at this point, the next line's `inner.seek(SeekFrom::Current(n))?` will seek the wrong position.

(If `pos` and `cap` are reset with `discard_buffer`, then `remainder` will be 0 at the next time, so it will not enter this branch.)

**Comment by czipperz** [comment]
Cool. I undid my commit and added a test that fails without that line.

**Review by nikomatsakis — APPROVED** [review]

**Pull request merged**
