### PR TITLE
Improve code clarity

### PR DESCRIPTION
**Pull request by AnthonyMikh**
No commit except 55b54285c811b6ab12bb0ba001126fd5b7d3bd09 address performance, just making the existing code more clear.

r? @estebank

### CODE REVIEW

**Comment by AnthonyMikh** [comment]
TIL that `override` is a Rust keyword

**Comment by estebank** [comment]
@bors r-

I'll approve once CI is green.

**Comment by AnthonyMikh** [comment]
Should compiling `rustc_plugin` take so long? CI seems to stuck on it

**Comment by Centril** [comment]
CI is green now. @bors r=estebank

**Pull request merged**
