### PR TITLE
Replace the ICEing on const fn loops with an error

### LINKED ISSUE #56035: const fn ICE on playground.
Minimal repro code:
```
const fn foo(a: u32) -> u32 {
    loop {}
}
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #56035

### CODE REVIEW

**Comment by oli-obk** [comment]
nominating for beta backport because of triviality of PR and diagnostics of newly stabilized const functions should not ICE on their release to the public.

**Comment by alexcrichton** [comment]
@bors: retry

Apparently bors missed that

**Pull request merged**
