### PR TITLE
Add missing urls in slice doc module

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @steveklabnik

### CODE REVIEW

**Comment by frewsxcv** [comment]
r=me if Travis is ✅

**Comment by steveklabnik** [comment]
Travis is not :white_check_mark: 

@bors: delegate=frewsxcv

**Comment by frewsxcv** [comment]
```
Linkcheck stage2 (x86_64-unknown-linux-gnu)
collections/slice/index.html:94: broken link - collections/clone/trait.Clone.html
collections/slice/index.html:95: broken link - collections/cmp/trait.Eq.html
collections/slice/index.html:95: broken link - collections/cmp/trait.Ord.html
collections/slice/index.html:95: broken link - collections/cmp/trait.Eq.html
collections/slice/index.html:95: broken link - collections/cmp/trait.Ord.html
collections/slice/index.html:96: broken link - collections/hash/trait.Hash.html
collections/slice/index.html:96: broken link - collections/hash/trait.Hash.html
collections/slice/index.html:132: broken link - collections/primitive.slice.html
collections/slice/index.html:132: broken link - collections/primitive.slice.html
collections/slice/index.html:134: broken link - collections/primitive.slice.html
collections/slice/index.html:134: broken link - collections/primitive.slice.html
collections/slice/index.html:135: broken link - collections/primitive.slice.html
collections/slice/index.html:135: broken link - collections/primitive.slice.html
thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:56
```

**Comment by GuillaumeGomez** [comment]
Updated (waiting for url check...).

**Pull request merged**
