### PR TITLE
Replace -O and -g with -C before handling options

### LINKED ISSUE #32352: rustc should accept rustc -O -C opt-level=x
`rustc -O -O` is ok just like `rustc -C opt-level=1 -C opt-level=2`. `-O` is documented to be the same as `-C opt-level=2`, so there should be no conflict, just have the last argument take precedent.

`-g` vs `-C debuginfo=2` behave the same way.

```
$ rustc -O -C opt-level=2
error: -O and -C opt-level both provided

$ rustc -C opt-level=1 -C opt-level=2 -g -g foo.rs
# ok.
```

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #32352.

### CODE REVIEW

**Comment by sanxiyn** [comment]
Travis failed because of conflict with #32369. (No textual conflict, but it changed Vec to slice.)

**Comment by alexcrichton** [comment]
I'm not sure that this is the best way to implement a change like this, it's modifying *pre-parsed* options which could perhaps mess with parsing other options. For example what if an argument to another argument is the string `-g` or `-O`?

This is also a semantic change which may or may not be intended, I kinda forget the original motivation here...

cc @rust-lang/tools

**Comment by nrc** [comment]
I would like to see some discussion of #32352 before landing a PR. Perhaps an internals thread? Given that it is the interface to the compiler, maybe even an RFC.

**Comment by nrc** [comment]
Sorry, I think I misunderstood that issue, it's not actually proposing anything new, just better handling overlap. In which case it seems more like just a bug.

**Comment by sanxiyn** [comment]
Rebased.

**Comment by alexcrichton** [comment]
This continues to not [handle the case I mentioned](https://github.com/rust-lang/rust/pull/32399#issuecomment-199400232) which I would personally consider a blocker for this.

**Comment by sanxiyn** [comment]
> For example what if an argument to another argument is the string -g or -O?

Is this possible? I failed to come up with such `arguments: Vec<String>`.

**Comment by alexcrichton** [comment]
This may involve tweaking getopts perhaps to learn about the position of arguments. Either that or we could just change the semantics so the opt level is the max, not the rightmost one (which makes more sense to me at least)

**Comment by sanxiyn** [comment]
"max not rightmost" would be different from GCC.

```
$ gcc -S test.c -o - -g2 -g0 | grep '\.debug_info' # no output
$ gcc -S test.c -o - -g0 -g2 | grep '\.debug_info'
.section .debug_info
```

**Comment by alexcrichton** [comment]
Right, it's just easier to implement that a modification to getopts to track where each option came from positionally which I believe is the other alternative here.

**Comment by petevine** [comment]
What about this message? (which is printed in plain text, no hint it's an error)

`rustc: for the -force-target-max-vector-interleave option: may only occur zero or one times!`

after providing `-C llvm-args=-force-target-max-vector-interleave=` twice on the command line.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with comments addressed!

**Pull request closed without merging**
