### PR TITLE
use parallel front end(-Zthreads=2) in ui tests

### PR DESCRIPTION
**Pull request by SparrowLii**
use parallel front end(-Zthreads=2) in ui tests
Test the functionality of the parallel frontend to support stabilization

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Due to the nature of parallel compiler bugs not being reliably reproducible most of the time, I don't think we will ever be able to turn this on in ci permanently, as a default at least.

What will happen is that we run into weird one-in-50 edge cases where tests fail or ICEs happen on seemingly unrelated PRs or random targets, while the pr that introduced the bug passed in ci by pure luck.

**Comment by SparrowLii** [comment]
Makes sense. The biggest value of this PR may be to find bugs that may be caused by parallel front-ends through UI testing.

**Comment by Kobzol** [comment]
We could add a special CI job that enables more threads, as a sort of a fuzzer, and allow it to fail (or just run it on a different rustc fork, for example).

**Comment by the8472** [comment]
You should check the walltime impact of running UI tests locally. They don't run under a jobserver, so it'll likely end up oversubscribing the CPU cores.

OTOH UI tests are tiny, so I wonder how much of a chance it even gets at running multiple threads.

**Comment by SparrowLii** [comment]
The main value of this PR draft is to find potential bugs, which has been completed and this PR is closed.

**Pull request closed without merging**
