### PR TITLE
Update GCC used in Linux dist builds to 9.1.0

### PR DESCRIPTION
**Pull request by Kobzol**
It would be helpful to make more tests pass in dist builds.

r? @ghost

### CODE REVIEW

**Comment by cuviper** [comment]
Looks like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90397

That should be fixed in later versions of GCC 9 -- why not go all the way to 9.5?

**Comment by Kobzol** [comment]
I'm not sure if it's a tidy problem, I would expect that we just can't compile such recent GCC with the old GCC 4.8. That's why I wanted to do the smallest update first.

I'll try 9.5 next.

**Comment by Kobzol** [comment]
Good, now it works. Rerunning try to see if the build gets any faster.

@bors try

@rust-timer build 212c0bcc50aa77f57225870959a11e745cc9f04e

**Comment by Kobzol** [comment]
Ok, good point, I'll use the latest minor versions then.

**Comment by Kobzol** [comment]
We know that we can use GCC up to 9.5, but there doesn't seem to be any benefit to that currently, so I'll close this. We can revisit this later, e.g. when we upgrade LLVM next time.

**Pull request closed without merging**
