### PR TITLE
remove erroneous error message when checking impl trait params

### LINKED ISSUE #48703: error message when passing parameters to fn using `impl Trait` is ungreat
This program:

```
#![feature(universal_impl_trait)]

use std::fmt::Debug;

fn foo<T>(x: impl Debug) { }

fn main() {
    foo::<String>('a');
}
```

gives the error:

```
error[E0089]: too few type parameters provided: expected 2 type parameters, found 1 type parameter
 --> src/main.rs:8:5
  |
8 |     foo::<String>('a');
  |     ^^^^^^^^^^^^^ expected 2 type parameters

error[E0632]: cannot provide explicit type parameters when `impl Trait` is used in argument position.
 --> src/main.rs:8:5
  |
8 |     foo::<String>('a');
  |     ^^^^^^^^^^^^^
```

I would expect just:

```
error[E0632]: cannot provide explicit type parameters when `impl Trait` is used in argument position.
 --> src/main.rs:8:5
  |
8 |     foo::<String>('a');
  |     ^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by tinaun**
fixes #48703

### CODE REVIEW

**Comment by tinaun** [comment]
i don't really like my solution here, but idk if doing the test in both functions would be any better

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Seems good to me, the only nit is in the name of the parameter, which could be clearer I think.

**Comment by nikomatsakis** [comment]
@tinaun -- do you think you'll have a chance to address the nit above? ❤️

**Comment by shepmaster** [comment]
@nikomatsakis looks like there has been new code pushed!

**Comment by nikomatsakis** [comment]
True, although it did not address my nit. That's ok, I don't care that much, but @tinaun you will need to fix this travis error:

https://travis-ci.org/rust-lang/rust/builds/353614751#L1817

r=me once green

**Comment by pietroalbini** [comment]
@tinaun ping from triage! The travis build is failing, could you fix that so the PR can be merged?

**Review by nikomatsakis — APPROVED** [review]

**Comment by alexcrichton** [comment]
@bors: retry

prioritizing rollup with this included in it

**Pull request merged**
