### PR TITLE
fix pretty print for `loop`

### PR DESCRIPTION
**Pull request by klensy**

### CODE REVIEW

**Comment by klensy** [comment]
There similar https://github.com/rust-lang/rust/blob/2336406b38db20d1bad30d32914e73af1dd62742/src/test/ui/issues/issue-22777.rs#L10..L12 but additional space here added manually.

**Comment by klensy** [comment]
Need to fix the same in hir pretty.

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed into one

**Pull request merged**
