### PR TITLE
Remove src/libsyntax/parse/attr.rs

### PR DESCRIPTION
**Pull request by KyleMayes**
This file is no longer needed as attribute parsing is no longer part of a trait.

### CODE REVIEW

**Comment by pnkfelix** [comment]
@KyleMayes I'm sorry, I don't understand: what do you mean "is no longer part of a trait" in your description?

Overall I'm not quite clear on what this change is accomplishing, but that may be because I don't understand the aforementioned sentence.

**Comment by mitaa** [comment]
@pnkfelix I think "no longer part of a trait" refers to this [commit](https://github.com/rust-lang/rust/commit/c141f47c2449a2f70e6d199104eb318b083def2a)

**Comment by pnkfelix** [comment]
Well  .... I still don't really understand what moving the contents of the `attr` modulre into the `parser` is accomplishing.

For example, Is there some example of state that is unnecessarily `pub` due to the factoring prior to this PR?

**Comment by KyleMayes** [comment]
I guess I'll close it, I just thought it didn't make any sense to have the implementation of Parser spread across multiple files.

**Pull request closed without merging**
