### PR TITLE
Update rustfmt to v1.4.26

### PR DESCRIPTION
**Pull request by calebcartwright**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Note that this will go into 1.50 (1.48 releases in a week, 1.49 in 7).

@bors r+

**Comment by calebcartwright** [comment]
> Note that this will go into 1.50 (1.48 releases in a week, 1.49 in 7).

Thanks!

Sorry for the semi-OT question, but is there a way I can check the beta status for https://github.com/rust-lang/rust/pull/78775#issuecomment-723341266? Without this, the version of rustfmt in beta currently is still panicking on nested tuple access and would hate to miss getting that fix into stable

**Comment by Mark-Simulacrum** [comment]
I just unilaterally beta accepted that patch - my guess is it was missed in compiler team meetings? - I will do another round of beta backports tonight or tomorrow which will likely include that PR. Feel free to ping me on discord/zulip if something is pending like that, easy to overlook.

**Comment by calebcartwright** [comment]
> I will do another round of beta backports tonight or tomorrow which will likely include that PR. Feel free to ping me on discord/zulip if something is pending like that, easy to overlook.

Awesome, thanks so much!

**Pull request merged**
