### PR TITLE
[perf] Use std based dedup in projection

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Unstable sort was added recently, and the code that is being modified is 3 years old. As quicksort doesn't allocate it will likely perform as well as, or better than linear search.

I didn't benchmark. Have a perf run.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Hmm, so basically sorting fails because most types do not implement Ord. Is it a good idea to add derivation of them in this PR?

**Comment by kennytm** [comment]
@ishitatsuyuki Let's add it, we need a perf check anyway. If it's unacceptable we could use `sort_unstable_by_key`.

**Comment by nikomatsakis** [comment]
Seems fine. I'd like to see some perf results, for sure -- even a local run on some non-trivial test case might be of interest.

**Comment by ishitatsuyuki** [comment]
Unwipped. Please perform a try a/o perf.

**Comment by ishitatsuyuki** [comment]
@Mark-Simulacrum please perform a perf run.

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by ishitatsuyuki** [comment]
http://perf.rust-lang.org/compare.html?start=47a8eb7c4e24b61a8a9ab4eaff60ef65291aaa56&end=77de396b7685c2d4870314ad7ca865ad7b6feb5c&stat=instructions%3Au

... and well, surprisingly no noticable time change except one (see below). To sum up, the code is now cleaner and resistant to quadratic blowup, but some Ord implementations are added.

The case where quicksort probably shines:

```
| clean incremental-opt | 251066587932.00 | 206164489487.00 | -17.9% |
```

No idea why only incremental is improved though. I'm pretty sure I compared against the parent of the merge commit.

**Pull request merged**
