### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #103842 (Adding Fuchsia compiler testing script, docs)
 - #104354 (Remove leading newlines from `NonZero*` doc examples)
 - #104372 (Update compiler-builtins)
 - #104380 (rustdoc: remove unused CSS `code { opacity: 1 }`)
 - #104381 (Remove dead NoneError diagnostic handling)
 - #104383 (Remove unused symbols and diagnostic items)
 - #104391 (Deriving cleanups)
 - #104403 (Specify language of code comment to generate document)
 - #104404 (Fix missing minification for static files)
 - #104413 ([llvm-wrapper] adapt for LLVM API change)
 - #104415 (rustdoc: fix corner case in search keyboard commands)
 - #104422 (Fix suggest associated call syntax)
 - #104426 (Add test for #102154)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=103842,104354,104372,104380,104381,104383,104391,104403,104404,104413,104415,104422,104426)

### CODE REVIEW

**Comment by nnethercote** [comment]
All the regressions are in `doc` builds. I'm guessing #104404 is the most likely cause.
cc @GuillaumeGomez 

@rust-timer build d5d26c0b90e16abe95721abdd3af630a23efd02b

**Comment by nnethercote** [comment]
Yep, #104404 is definitely the cause of the regression.

**Comment by rylev** [comment]
[Justification](https://github.com/rust-lang/rust/pull/104404#issuecomment-1317574300) for this regression was posted #104404. Effectively this regression is taking us back to the baseline. 

@rustbot label: +perf-regression-triaged

**Pull request merged**
