### PR TITLE
Small changes w/ `query::Erase<_>`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
r? @cjgillot 
cc @Zoxc

### CODE REVIEW

**Comment by Zoxc** [comment]
Why this change given that `transmute_unchecked` is unstable?

**Comment by cjgillot** [comment]
For the first commit: all the types here are `Copy`. Adding the types are generic arguments to `transmute_copy` should be enough, as `transmute_unchecked` does not assert size equality.
For the second commit: ok.

**Comment by cjgillot** [comment]
r=me with a comment explaining the transmute_unchecked/transmute_copy rationale.

**Pull request merged**
