### PR TITLE
Make the Box one-liner more descriptive

### PR DESCRIPTION
**Pull request by dns2utf8**
I would like to avoid a definition that relies on itself.

r? @GuillaumeGomez

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me but I'll let the final approval to someone from the libs-api team have the final word.

r? @rust-lang/libs-api

**Review by dtolnay — CHANGES_REQUESTED** [review]
I am hesitant about calling this "heap allocation for an owned value". It's 100% equally suitable to heap allocating a borrowed value. What you put in the Box can really be arbitrary.

**Comment by dns2utf8** [comment]
Would it be valid to create a Box that points to an object living on the stack?
I am at EuroRust currently, would love to chat :)

**Comment by dtolnay** [comment]
Box\<T\> itself always points to the heap, so no. But that is different from whether the value it points to is an owned value or borrowed. For example the following puts a borrowed value on the heap. It borrows from data on the stack.

```rust
let x = Struct { ... };
let b = Box::new(&x);
```

**Comment by dtolnay** [comment]
I pushed an alternative wording that avoids referring to T's type as being an owned type, just the fact that Box\<T\> owns a value of that type.

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
