### PR TITLE
Stabilize SystemTime::UNIX_EPOCH

### LINKED ISSUE #49502: Tracking issue for SystemTime::UNIX_EPOCH
Added in #49501

### PR DESCRIPTION
**Pull request by tmccombs**
Fixes #49502

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Since FCP on the related tracking issue finished I believe we're clear to r+ this; cc @rust-lang/libs for any objections.

@bors r-

**Comment by Mark-Simulacrum** [comment]
...That was meant to be:

@bors r+

**Comment by newpavlov** [comment]
Shouldn't it be in release notes?

**Comment by SimonSapin** [comment]
Added in https://github.com/rust-lang/rust/pull/52677

**Pull request merged**
