### PR TITLE
test - simulate default discriminant start at 1

### PR DESCRIPTION
**Pull request by bonega**
*WIP/TEST*
Trying to gauge the general performance impact of enums not starting with zero.
This is only for `repr(rust)`

Please sate my curiosity with a perf-run

Edit: sorry - didn't mean to set of all the sirens...

### CODE REVIEW

**Comment by the8472** [comment]
Wouldn't it be simpler to adjust the compiler logic that determines the implicit discriminants when no explicit ones are given? That'll also catch those in external crates.

**Comment by bonega** [comment]
There is a couple of enums in the compiler that expects to have discriminant zero, without it being explicit.
So had to manually go sort them out, that was fun.

My first try to change the default discriminant didn't work either. Can't remember if it was because of before mentioned reason or not

**Comment by bonega** [comment]
Thanks for the perf-run.

I tried to change `initial_discriminant` function to `val: 1` and disable overflow check in `wrap_incr`. 
I hoped that would mean that only overflow-tests would break.

Get a *lot* of coredumps instead.
Any tips for this?

**Comment by oli-obk** [comment]
> disable overflow check in `wrap_incr`.

What does this mean?

I would have assumed we'd need to remove the -1 in https://github.com/rust-lang/rust/blob/cdeba02ff71416e014f7130f75166890688be986/compiler/rustc_middle/src/ty/util.rs#L71 and https://github.com/rust-lang/rust/blob/cdeba02ff71416e014f7130f75166890688be986/compiler/rustc_middle/src/ty/util.rs#L80 so that we essentially do +1 on overflow. There may be more sites to touch, but I would hope this would be the only place to touch

**Comment by bonega** [comment]
Thanks!

But I don't want to forbid zero as discriminant.
Sorry for the confusing title, my bad - Changing it.
I want to start non explicit discriminant selection at `1`.
If it wraps around to `0` then that is fine.

I think your change would make it so that we can only fit 255 variants in an `repr(u8)`?

Anyhow the change still seem to result in same problem: Lot of coredumps

**Comment by oli-obk** [comment]
right, I misunderstood the intention. Just wrapping around normally is good then. Can you push your changes somewhere so we can be sure to be talking about the same things?

**Comment by bonega** [comment]
Pushed my best guess.

Intention: For `repr(rust)` enums with no explicit discriminants, use `1` instead of `0` for initial discriminant.

I get a lot of coredumps for this.
Unsure how to best debug/structure it.
Thankful for any tips

**Comment by oli-obk** [comment]
my recommendation for debugging it is putting it behind a feature gate and then creating a very simple test.

compile the test once with the feature and once without, but with explicit discriminants that should be equal and compare various tracing dumps between the two runs to see how things differ.

**Comment by tmiasko** [comment]
What is motivation behind an additional optimize argument to `AdtDef::discriminants`? In commit above, the MIR building uses false, while uninhabited enum branches through `discriminant_for_variant` will potentially use true, so at least one arm of every match one enum using the optimization will be completely removed out at MIR level `:)`.

I would also look at codegen / interpreter of niche encoding, if I recall correctly it assumes that discriminants start at 0.

**Comment by bonega** [comment]
Thanks to both of you.

I have pushed a new version that only has one test failing for `/x.py test ui`.
`rust/src/test/ui/mir/issue-76803-branches-not-same.rs`.
Will think about it some more

**Comment by tmiasko** [comment]
```console
$ cat a.rs 
#[derive(Debug, Eq, PartialEq)]
pub enum Type {
    A = 1,
    B = 2,
}
pub fn encode(v: Type) -> Type {
    match v {
        Type::A => Type::B,
        _ => v,
    }
}
fn main() {
  assert_eq!(Type::B, encode(Type::A));
}
$ rustc -Zmir-opt-level=0 a.rs && ./a
$ rustc a.rs && ./a
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `B`,
 right: `A`', a.rs:13:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

...

**Comment by bonega** [comment]
Good catch.
I was thinking it was my code...

**Comment by JohnCSimon** [comment]
triage: 
@bonega Can you please address the build failures  and adjust the label with `@rustbot ready` when you're ready for review.

**Comment by bonega** [comment]
Been stuck on this for a while, will try and look at it again

**Comment by JohnCSimon** [comment]
Ping from triage: 
@bonega 
I'm closing this due to inactivity, Please reopen when you are ready to continue with this. Thank you.

@rustbot label: +S-inactive

**Pull request closed without merging**
