### PR TITLE
rustc: Allow cdylibs to link against dylibs

### PR DESCRIPTION
**Pull request by maurer**
Previously, rustc mandated that cdylibs could only link against rlibs as dependencies (not dylibs).
This commit disables that restriction and tests that it works in a simple case.

I don't have a windows rustc dev environment, so I guessed at the MSVC test code, I'm hoping the CI can run that for me.

Additionally, we might want to consider emitting (through cargo or rustc) some metadata to help C users of a cdylib figure out where all the dylibs they need are. I don't think that should be needed to land this change, as it will still be usable by homogeneous build systems without it.

My new test was templated off the `tests/run-make-fulldeps/cdylib` test. It seemed more appropriate to have it as a separate test, since both foo.rs and bar.rs would need to be replicated to make that test cover both cases, but I can do that if it would be preferred.

If I'm doing anything out of order/process, please let me know; this is only my second change to rustc and the prior one was trivial.

r? alexcrichton

### CODE REVIEW

**Comment by maurer** [comment]
r? @alexcrichton 
(Sorry, got syntax wrong the first time.)

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by maurer** [comment]
@alexcrichton 
I switched to using a dylib glob rather than doing it manually, which will hopefully fix the mac build. I don't think I have the power to retrigger bors myself though (or to trigger only the mac build to check if it worked first, as I don't have easy access to an OSX machine).

**Pull request merged**
