### PR TITLE
Don't restrict docs in compiler-docs mode

### PR DESCRIPTION
**Pull request by Manishearth**
Search is broken without this. We want all crates to be included in compiler-docs mode. This was changed in https://github.com/rust-lang/rust/pull/38858, this PR brings that functionality back in compiler-docs mode.

### CODE REVIEW

**Comment by ollie27** [comment]
Isn't the search index for the compiler docs not completely broken anyway: #34800? I agree that the compiler docs should include docs for all crates that `std` depends on though.

**Comment by Manishearth** [comment]
Yeah, it's broken anyway, this just makes it more broken 😄

**Comment by alexcrichton** [comment]
Could you add a comment here as well? Out of the blue such a conditional seems like it would be quite odd.

**Comment by alexcrichton** [comment]
(other than that r=me)

**Pull request merged**
