### PR TITLE
travis: Compile a more compatible libc.a for musl

### LINKED ISSUE #39979: Linking liblibc using musl target fails ("unrecognized relocation") with the new nightlies
Here's a dockerized test case: https://github.com/golddranks/libc_regression_test/ (run with `docker build .`)

Here's the error:
```
  = note: /usr/bin/ld: /root/.rustup/toolchains/nightly-2017-02-19-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-95af4192ed69a1c8.rlib(exit.lo): unrecognized relocation (0x2a) in section `.text.libc_exit_fini'
          /usr/bin/ld: final link failed: Bad value
          collect2: error: ld returned 1 exit status
```

The linking error seems to happen only with the musl target. I originally posted this as https://github.com/rust-lang/libc/issues/529, but because the breaking is dependent on the nightly, it seems that this is an `rustc` issue rather than an issue of the `libc` crate.

After testing with various nightlies, it seems that the nightly `nightly-2017-02-16 installed - rustc 1.17.0-nightly (62eb6056d 2017-02-15)` is the first one that breaks. The nightly before that, `nightly-2017-02-13 installed - rustc 1.17.0-nightly (956e2bcba 2017-02-12)` is the last one that works.

So that seems to imply that the commit that introduced this regression is in the range `956e2bcba..62eb6056d`. Any thoughts about which one it might be?

### PR DESCRIPTION
**Pull request by alexcrichton**
The mitigations for #34978 involve passing `-Wa,-mrelax-relocations=no` to all C
code we compile, and we just forgot to pass it when compiling musl itself.

Closes #39979

### CODE REVIEW

**Comment by BurntSushi** [comment]
@alexcrichton Did this make it into the `2017-02-23` nightly? I think I'm still seeing failures: https://travis-ci.org/BurntSushi/ripgrep/jobs/204969471 --- Should I open a new bug?

**Comment by alexcrichton** [comment]
@BurntSushi this PR hasn't landed yet?

**Pull request merged**
