### PR TITLE
fs::copy() linux: handle sparse files and set file mode early

### PR DESCRIPTION
**Pull request by haraldh**
A convenience method like fs::copy() should try to prevent pitfalls a
normal user doesn't think about.

In case of an empty umask, setting the file mode early prevents
temporarily world readable or even writeable files,
because the default mode is 0o666.

In case the target is a named pipe or special device node, setting the
file mode can lead to unwanted side effects, like setting permissons on
`/dev/stdout` or for root setting permissions on `/dev/null`.

Not handling sparse files could fill up the users disk very quickly.

Fixes:
https://github.com/rust-lang/rust/issues/26933
https://github.com/rust-lang/rust/issues/37885
https://github.com/rust-lang/rust/issues/58635

### CODE REVIEW

**Comment by mattico** [comment]
Rust doesn't support kernels older than 2.6 (https://forge.rust-lang.org/platform-support.html). I don't object to the check being there but something else is likely to break before anyone gets to this code.

**Comment by alexcrichton** [comment]
Thanks for the PR! We actually had a [different request for this as well](https://github.com/rust-lang/rust/pull/55909) recently, but I think the verdict is still the same as before. We're not currently in a position to maintain complicated maintenance of file copying to this degree. This sort of algorithm would be perfect for crates.io, however!

Would you be ok to slim down this PR to just the bug fixes aside from the sparse file handling?

**Comment by vi** [comment]
If handling sparse files is out of scope by design then it should probably be mentioned in documentation, maybe with a link to said crate of crates.io.

**Comment by haraldh** [comment]
Fix for the non-sparse version:
https://github.com/rust-lang/rust/pull/58803

**Comment by gnzlbg** [comment]
> We're not currently in a position to maintain complicated maintenance of file copying to this degree.

Would it help if this PR would add a test to prevent this from breaking again?

**Comment by alexcrichton** [comment]
@vi yes adding documentation to that effect seems reasonable. @gnzlbg afaik nothing broke here, this is new functionality being added. @haraldh thanks for opening a new PR! Should this one be closed in that case?

**Comment by haraldh** [comment]
@alexcrichton yeah, close this, if sparse files won't be handled.

**Comment by alexcrichton** [comment]
Ok!

**Pull request closed without merging**
