### PR TITLE
Be stricter about combining `repr(packed)` with `derive`.

### PR DESCRIPTION
**Pull request by nnethercote**
Currently there are two errors you can get when using `derive` on a
`repr(packed)` struct:
    
- "`#[derive]` can't be used on a `#[repr(packed)]` struct with type
  or const parameters (error E0133)"
- "`#[derive]` can't be used on a `#[repr(packed)]` struct that does not
  derive Copy (error E0133)"
    
These were introduced under #82523, because they can lead to unaligned
references, which is UB. They are in the process of being upgraded to
hard errors.
    
This is all fine, but the second error overstates things. It *is*
currently possible to use `derive` on a `repr(packed)` struct that doesn't derive
`Copy` in two cases.
- If all the fields within the struct meet the required alignment: 1 for
  `repr(packed)`, or N for `repr(packed(N))`.
- Or, If `Default` is the only trait derived.
    
These exceptions don't seem particularly important or useful, and the
language would be simpler if they are removed. So this commit does that,
making these cases a hard error. The new checks are done at derive code
creation time which means that `unsafe_derive_on_repr_packed` is no
longer needed at MIR build time.

Test changes:
- deriving-with-repr-packed.rs has numerous changes to the code to
  broaden coverage. Some of the errors are reported twice now,
  which is hard to avoid but harmless (and users won't see duplicates
  thanks to the normal error de-duplication). Also, if a packed struct
  is both non-`Copy` and has type params, both those errors are now
  reported.
- deriving-all-codegen.rs has the `PackedNonCopy` case removed, because
  it's no longer allowed.
- packed.rs needs `Copy` added to some packed struct that currently only
  derive `Default`.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
All commits prior to the last commit can be ignored, because they come from #99046.

It's unclear if this change will be acceptable, so I will do a crater run.

@bors try

cc @RalfJung

**Comment by nnethercote** [comment]
BTW, this kind of falls under #82523.

**Comment by nnethercote** [comment]
@craterbot check

**Comment by nnethercote** [comment]
Hmm, 99 regressing crates in the crater run, which seems too high to do this as-is. `Default` and `Debug` are the most commonly derives in the failing cases, but we see most of the builtin traits showing up in at least one place.

So, possible course of action:
- Turn this into a lint, and go through the whole deprecation process.
- Clarify the error message, e.g. change "`#[derive]` can't be used on a `#[repr(packed)]` struct that does not derive Copy" into "`#[derive(Debug)]` can't be used on a `#[repr(packed)]` struct with this alignment that does not derive Copy".
- Do nothing.

**Comment by RalfJung** [comment]
If we accept the same code when hand-written, I don't quite see the advantage of rejecting it for automatic derive.

**Comment by nnethercote** [comment]
Yeah, I agree. The advantage of the blanket ban is simplicity. But that would ban some legitimate things that are currently accepted. In particular, `derive(Default)` shows up a lot in the crater regressions.

So I think I will improve the error message a little but leave everything else alone.

**Comment by RalfJung** [comment]
Maybe something like this can be salvaged if we find a way to support some of the cases that started to error here... see https://github.com/rust-lang/rust/issues/82523#issuecomment-1312729769.

**Pull request closed without merging**
