### PR TITLE
Turn turbo 🐟 🍨 into an error

### PR DESCRIPTION
**Pull request by oli-obk**
Master branch part of #60989

r? @varkor

### CODE REVIEW

**Comment by varkor** [comment]
r=me when Travis passes.

**Comment by oli-obk** [comment]
Nominating for stable backport. The backport already exists in https://github.com/rust-lang/rust/pull/61208 (since this PR does not apply cleanly to stable)

**Comment by pnkfelix** [comment]
discussed in T-compiler meeting. accepted for backport to beta and stable channels.

**Comment by Centril** [comment]
Discussed on T-release meeting; declining point release for now based on sum-total of stable-accepted.

**Pull request merged**
