### PR TITLE
Rename iter::Iterator::intersperse() to ::separate()

### PR DESCRIPTION
**Pull request by lukaslueg**
Following up in the suggestion voiced [here](https://github.com/rust-lang/rust/issues/79524#issuecomment-2002474737), this

* renames `Iterator::intersperse()` to `Iterator::separate()`
* adds a doc-alias `"intersperse"` on `separate()` 
* renames `Iterator::intersperse_with()` to `Iterator::separate_with()`
* renames the associated structs and modules, and updates all references

in order to move on wrt #79524. I have no opinion wrt https://github.com/rust-lang/rust/issues/79524#issuecomment-2002474737 being the correct solution to solve #79524

### CODE REVIEW

**Comment by joboet** [comment]
r? libs-api

**Comment by camelid** [comment]
Just wanted to note that there was some disagreement in the associated issue about whether we should merge `separate` and `separate_with` into one method `separate` that takes a closure. I'm personally in favor of two separate methods since this is the usual design in Rust and since a constant separator is much more common. But others disagree so that should be decided before merging this PR.

**Comment by jadebenn** [comment]
Not to bikeshed too much, but I think `seperate` is an awfully non-descriptive name for what this method does. My intuition at seeing that name would be that it somehow breaks up an existing collection, not that it adds a new element between each instance.

Something along the lines of `interject`, `interleave`, `interlace`, or perhaps even just`separator` would seem more descriptive to me if the name needs to be changed to avoid a conflict with itertools.

**Comment by Amanieu** [comment]
To give an update, we're currently trying to work around the naming conflict with a language-level feature: https://github.com/rust-lang/rust/issues/89151#issuecomment-2063584575

**Comment by lukaslueg** [comment]
Superseded by #89151

**Pull request closed without merging**
