### PR TITLE
compiler: `{TyAnd,}Layout` comes home

### PR DESCRIPTION
**Pull request by workingjubilee**
The `Layout` and `TyAndLayout` types are heavily abstract and have no particular target-specific qualities, though we do use them to answer questions particular to targets. We can keep it that way if we simply move them out of `rustc_target` and into `rustc_abi`. They bring a small entourage of connected types with them, but that's fine.

This will allow us to strengthen a few abstraction barriers over time and thus make the notoriously gnarly layout code easier to refactor. For now, we don't need to worry about that and deliberately use reexports to minimize this particular diff.

### CODE REVIEW

**Review by jieyouxu — COMMENTED** [review]
The organization after this PR looks definitely more sane to me :+1: I don't work with ABI/codegen/target enough so won't r+ as I imagine other compiler reviewers will have a better gauge on this.

**Comment by saethlin** [comment]
r? saethlin

**Comment by saethlin** [comment]
@bors r+

If this is part of a larger effort, @workingjubilee can you link to that from this PR or mention this PR on the larger PR? Just so it's easier to follow the plot in GitHub, the code here is good to go.

**Comment by workingjubilee** [comment]
Oh, sure!

https://github.com/rust-lang/rust/pull/131424 was the PR before this, the followups will link back to this one or maybe I'll make an issue. Basically we started migrating important components of layout code into `rustc_abi`... 2 years ago.. and never actually finished it, and all of the things I've even tried to work on for five minutes lately are made harder by the intense cross-crate couplings (that are cut very oddly, to boot).

**Pull request merged**
