### PR TITLE
Add future incompatibility lint for #[link] without arguments

### LINKED ISSUE #53901: Incorrect link attibute allowed
```rust
#[link="reiojregioergioregiojrge"]
extern "C" {}

fn main() {}
```

([Playground](https://play.rust-lang.org/?gist=760c602adc45ca7fe66314eb2b8f6564&version=stable&mode=debug&edition=2015))

Output:

```
   Compiling playground v0.0.1 (file:///playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.18s
     Running `target/debug/playground`

```

### PR DESCRIPTION
**Pull request by varkor**
- Add a lint `invalid_link_arguments` for `#[link = "foo"]` (rather than `#[link(name = "foo")]`).
- Add a lint for duplicate arguments.
- Improve feature gate diagnostics for `#[link]`.
Fixes #53901.

### CODE REVIEW

**Comment by kennytm** [comment]
Servo's broken.

**Comment by SimonSapin** [comment]
This PR breaks code that runs on the Stable channel. What makes this breaking change acceptable?

**Comment by varkor** [comment]
@SimonSapin: I was just going to make a comment noting this. I'm going to change this to a lint instead, so it won't break dependencies. It does seem reasonable to make this deny-by-default, though?

**Comment by SimonSapin** [comment]
A lint that is affected by `--cap-lints` is less bad, but deny by default still breaks code on Stable that didn’t opt into `#[deny(warnings)]`.

https://github.com/rust-lang/rust/issues/53901 doesn’t say much, what’s wrong with `#[link = "dl"]`?

**Comment by SimonSapin** [comment]
I agree that silently doing nothing is not good, but ecosystem impact is also something to consider. I think this needs at least a crater run, and perhaps some team discussion. Or is there an established policy or a precedent on how to deal with code that compiles on Stable but is likely incorrect, without being unsound?

**Comment by varkor** [comment]
(I've [nominated the issue](https://github.com/rust-lang/rust/issues/53901) for discussion.)

**Comment by retep998** [comment]
I am strongly in favor of having this lint.

If I recall correctly, the correct procedure should be a warn by default lint first, later upgraded to a deny by default lint once the major offenders have been fixed, and finally converted into a hard error in the distant future once crater comes up clean (or at the very least the remaining breakages are considered acceptable).

**Comment by petrochenkov** [comment]
This is mostly subsumed by https://github.com/rust-lang/rust/pull/57321.
I suggest to wait until that PR lands and then report remaining mistakes (like duplicate `kind`s) like errors, crater found no regressions for them.

**Pull request closed without merging**
