### PR TITLE
submodules: Update miri from d2df5098 to 67fd5a44

### PR DESCRIPTION
**Pull request by tesuji**
r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Parts of the Miri test suite currently only pass without validation -- Miri master is in "degraded state", so to speak. I'd prefer to defer updating Miri until https://github.com/rust-lang/miri/pull/830 lands.

**Comment by lzutao** [comment]
Closed to wait for it then.

**Comment by RalfJung** [comment]
@lzutao  Miri has been fixed, you can try again. :)

**Comment by RalfJung** [comment]
Ah, someone bet you to it at https://github.com/rust-lang/rust/pull/62594.

**Pull request closed without merging**
