### PR TITLE
Bump miri

### LINKED ISSUE #77791: `miri` no longer builds after rust-lang/rust#77731
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#77731, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @cuviper, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes https://github.com/rust-lang/rust/issues/77791

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
r=me when PR CI passes

@bors delegate+

**Comment by Aaron1011** [comment]
I bumped Miri again so that it includes https://github.com/rust-lang/miri/pull/1580

@bors r=RalfJung

**Pull request merged**
