### PR TITLE
Fix precidence of as in the manual.

### LINKED ISSUE #15008: Operator precedence for "as" seems incorrect in the manual
The manual in section *7.2.11.8 Operator precedence* states that "* / %" bind stronger than "as", however rustc seems to disagree:

```rust
let _a = 1. * 1 as f32;
let _b = 1. * (1 as f32);
let _c = (1. * 1) as f32;
```

Only the last expression triggers an error, the _a seems to evaluate like _b.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #15008.

### CODE REVIEW

**Comment by P1start** [comment]
This was actually correct beforehand (the referenced issue is no longer valid, as it was fixed in db013f9). `as` should be at the top because it binds tighter than `+`: `1. + 1 as f32` is equivalent to `1. + (1 as f32)`.

**Comment by steveklabnik** [comment]
Then the bug still exists somewhere, as I get the same results as the original post today.

**Comment by P1start** [comment]
The original post of that issue states that `as` binds tighter than `/ * %`. That is true, so the reference manual should place `as` above those operators (as the list is sorted strongest- to weakest-binding), as it does today.

**Comment by steveklabnik** [comment]
Oh, I can't read. :(

**Pull request closed without merging**
