### PR TITLE
Small optimizations

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I'm actually wondering if it'll change anything. Are there performance tests available for everyone?

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
To be honest I would be very surprised if llvm did not already do this on its own.

**Comment by matthiaskrgr** [comment]
https://godbolt.org/g/hqVnT7

**Comment by nagisa** [comment]
This change is only valid to make when it is guaranteed that no overflow will occur in case of multiplication, otherwise a change in behaviour occurs. This change can be summarised as removal of overflow checks in debug mode. Division by powers-of-two may be replaced (by LLVM, target depending) with shifts even at `opt-level = 0` (and for opt-level > 0 it will also replace divisors such as `3` with the more efficient forms as well).

That being said, there’s some value in keeping code as is, for readability purposes, so I’d be inclined to close.

**Comment by petrochenkov** [comment]
I agree with closing.
Without debug assertions this is basic strength reduction and it should be performed by the compiler and not by human since it hurts readability.

**Pull request closed without merging**
