### PR TITLE
Changed error message for enum variants

### LINKED ISSUE #35241: Forgetting to call a variant constructor causes a confusing error message
## STR

``` Rust
struct Foo(u32);

fn test() -> Foo { Foo }

fn main() {
}
```
## Confusing result

```
error[E0308]: mismatched types
 --> <anon>:3:20
  |
3 | fn test() -> Foo { Foo }
  |                    ^^^ expected struct `Foo`, found fn item
  |
  = note: expected type `Foo`
  = note:    found type `fn(u32) -> Foo {Foo::{{constructor}}}`
```

### PR DESCRIPTION
**Pull request by hilasha2**
Fixes #35241 

r? @jonathandturner

### CODE REVIEW

**Comment by arielb1** [comment]
```
/build/src/librustc/infer/error_reporting.rs:523: trailing whitespace
/build/src/librustc/infer/error_reporting.rs:537: trailing whitespace
/build/src/librustc/infer/error_reporting.rs:550: trailing whitespace
/build/src/test/compile-fail/issue-35241.rs:37: trailing whitespace
```

That's annoying.

@bors r-

**Comment by jonathandturner** [comment]
@bors r-

This looks like a legit failure:

```
error[E0531]: unresolved variant or struct `FnConverging`
   --> /buildslave/rust-buildbot/slave/auto-linux-64-cross-freebsd/build/src/librustc/infer/error_reporting.rs:543:22
    |
543 |                     (ty::FnConverging(ret_ty), _) => {
    |                      ^^^^^^^^^^^^^^^^

error[E0531]: unresolved variant, struct or constant `FnDiverging`
   --> /buildslave/rust-buildbot/slave/auto-linux-64-cross-freebsd/build/src/librustc/infer/error_reporting.rs:546:22
    |
546 |                     (ty::FnDiverging, _) => true
    |                      ^^^^^^^^^^^^^^^
```

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with the test failure fixed!

**Pull request closed without merging**
