### PR TITLE
Rename HAIR to THIR (Typed HIR).

### PR DESCRIPTION
**Pull request by Lezzz**
r? @nikomatsakis

Originally suggested by @eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Probably a better name, I admit.

We probably will want to update the rustc-dev-guide too (cc @rust-lang/wg-rustc-dev-guide). I'm not sure whether this ought to merit an MCP (cc @rust-lang/compiler, thoughts?).

**Comment by mark-i-m** [comment]
I still regret the HAIR loss...

**Comment by nagisa** [comment]
> I'm not sure whether this ought to merit an MCP

IMHO we can do without one here. HAIR is a comparatively obscure internal representation not many interact with or will have an opinion about.

**Comment by wesleywiser** [comment]
Judging by the reactions to @nagisa's comment, it seems like most of the compiler team is in favor of this change. I think this can be r+'d after a rebase.

**Pull request merged**
