### PR TITLE
Add targets thumbv7neon-linux-androideabi and thumbv7neon-unknown-linux-gnueabihf

### PR DESCRIPTION
**Pull request by hsivonen**
These two targets enable both thumb-mode and NEON for ARMv7 CPUs.

This another attempt at #49902, which cannot be reopened. Between that PR and this one, some subrepos with C code whose build systems were failing went away.

### CODE REVIEW

**Comment by hsivonen** [comment]
Filed a [follow-up](https://github.com/rust-lang/rustup.rs/issues/1586) about `rust-std` availability for these targets via rustup.

**Comment by hsivonen** [comment]
And thanks for getting this landed!

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust-forge/blob/master/platform-support.md needs to be updated as well.

**Pull request merged**
