### PR TITLE
Implement `MaybeUninit::fill{,_cloned,_mut,_with,_from}`

### PR DESCRIPTION
**Pull request by jmillikin**
ACP: https://github.com/rust-lang/libs-team/issues/156

Tracking issue: https://github.com/rust-lang/rust/issues/117428

### CODE REVIEW

**Comment by jmillikin** [comment]
The original ACP proposed adding `fill<T: Clone>(&mut self, value: T) -> &mut [T]` -- I made the following adjustments to this API:

* Changed the value parameter to `&T` to have better control over `Drop` handling -- in particular there was no good way to avoid dropping `value` if called with an empty slice.
* Changed to return a non-mutable slice to avoid the accidental leaking discussed in https://github.com/rust-lang/rust/issues/80376
* To accommodate the common case of filling with zero or a known bit pattern, I renamed the `Clone` fill method to `fill_cloned()` and added `fill()` / `fill_mut()` for `T: Copy` -- the mut slice return isn't dangerous since there's no dropping.

The ACP's proposed `fill_with<F: FnMut() -> T>(f: F)` and `fill_from<I: Iterator<Item = T>>(iter: I)` were implemented as originally described.

I verified that `MaybeUninit<u8>::fill()` compiles to `memset()`.

**Comment by Amanieu** [comment]
>     * Changed to return a non-mutable slice to avoid the accidental leaking discussed in [MaybeUninit::write_slice_cloned() makes it very easy to accidentally leak #80376](https://github.com/rust-lang/rust/issues/80376)

I disagree. I think this should always return `&mut`. I think introducing more API surface will only increase user confusion, and by working with `MaybeUninit` you already have to be aware of potentially leaking data. All the `fill` methods should return mutable slices.

>     * To accommodate the common case of filling with zero or a known bit pattern, I renamed the `Clone` fill method to `fill_cloned()` and added `fill()` / `fill_mut()` for `T: Copy` -- the mut slice return isn't dangerous since there's no dropping.

I'm less concerned about this: there is already `fill_with` for people who want precise control over how many clone calls are made. The discussion about `T` vs `&T` has already happened in https://github.com/rust-lang/rust/issues/70758, and I would prefer just keeping the `T` version for consistency with `slice::fill`.

**Comment by Amanieu** [comment]
ping @jmillikin, could you address the review feedback?

**Comment by jmillikin** [comment]
Closed in favor of https://github.com/rust-lang/rust/pull/121280

**Pull request closed without merging**
