### PR TITLE
Restore lldb build

### PR DESCRIPTION
**Pull request by tromey**
commit 6c10142251 ("Update LLVM submodule") disabled the lldb build.
This patch updates the lldb and clang submodules to once again build
against the LLVM that is included in the Rust tree, and reverts the
.travis.yml changes from that patch.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

Thanks for doing this! Sorry long weekend here so was a bit delayed getting around to it!

**Comment by tromey** [comment]
The lldb code definitely looks incorrect -- that file has moved -- but I cannot reproduce it in a local build.

**Comment by tromey** [comment]
Maybe locally it is picking up an installed lldb header.

**Comment by tromey** [comment]
I've fixed the lldb issue and as it is trivial I'm going to see if I can re-r+ this.

@bors r=alexcrichton

**Comment by tromey** [comment]
@alexcrichton it will need another r+ from you

**Pull request merged**
