### PR TITLE
Mark other variants as uninitialized after switch on discriminant

### PR DESCRIPTION
**Pull request by ecstatic-morse**
During drop elaboration, which builds the drop ladder that handles destruction during stack unwinding, we attempt to remove MIR `Drop` terminators that will never be reached in practice. This reduces the number of basic blocks that are passed to LLVM, which should improve performance. In #66753, a user pointed out that unreachable `Drop` terminators are common in functions like `Option::unwrap`, which move out of an `enum`. While discussing possible remedies for that issue, @eddyb suggested moving const-checking after drop elaboration. This would allow the former, which looks for `Drop` terminators and replicates a small amount of drop elaboration to determine whether a dropped local has been moved out, leverage the work done by the latter.

However, it turns out that drop elaboration is not as precise as it could be when it comes to eliminating useless drop terminators. For example, let's look at the code for `unwrap_or`.

```rust
fn unwrap_or<T>(opt: Option<T>, default: T) -> T {
    match opt {
        Some(inner) => inner,
        None => default,
    }
}
```

`opt` never needs to be dropped, since it is either moved out of (if it is `Some`) or has no drop glue (if it is `None`), and `default` only needs to be dropped if `opt` is `Some`. This is not reflected in the MIR we currently pass to codegen.

pasted_image

@eddyb also suggested the solution to this problem. When we switch on an enum discriminant, we should be marking all fields in other variants as definitely uninitialized. I implemented this on top of alongside a small optimization (split out into #68943) that suppresses drop terminators for enum variants with no fields (e.g. `Option::None`). This is the resulting MIR for `unwrap_or`.

after

In concert with #68943, this change speeds up many [optimized and debug builds](https://perf.rust-lang.org/compare.html?start=d55f3e9f1da631c636b54a7c22c1caccbe4bf0db&end=0077a7aa11ebc2462851676f9f464d5221b17d6a). We need to carefully investigate whether I have introduced any miscompilations before merging this. Code that never drops anything would be very fast indeed until memory is exhausted.

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Just to see how slow this makes dataflow:

@bors try
@rust-timer queue

**Comment by ecstatic-morse** [comment]
@bors try
@rust-timer queue

**Comment by bjorn3** [comment]
This reduces the amount of time spent in LLVM. For incremental builds is also reduces the amount of time spent in `incr_comp_load_dep_graph` by up to 20%. For clean incremental there are a few regressions of ~2%, but those regressions are less than 10ms, so they are likely. The self profiling data even says for some of the regressions that they were actually improvements.

**Comment by ecstatic-morse** [comment]
@bjorn3 I added a summary of the changes to the OP, along with an explanation of the perf results for `check` builds, which this PR makes strictly slower. A 10% improvement for `syn-opt` seems almost too good to be true. In fact, it seems *so* good that I was hesitant to call attention to these results lest this PR be found to be unsound. If that improvement is legitimate, I would be overjoyed.

**Comment by eddyb** [comment]
Since I suggested this approach, I'd rather someone else review:
r? @pnkfelix or @matthewjasper cc @arielb1

**Comment by JohnCSimon** [comment]
Triage: @ecstatic-morse is this still a WIP?

**Comment by kiljacken** [comment]
The author [mentioned on zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Review.20request.20for.20.2368241) that it's primarly blocked on #68241

**Comment by mark-i-m** [comment]
#68241 has merged

**Comment by ecstatic-morse** [comment]
This is still kind of hacky because it needs to look for `SwitchInt`s on the result of an `Rvalue::Discriminant` and map the integer values back to their corresponding variant. A `SwitchDiscriminant` terminator would make this easier. Additionally, since `apply_discriminant_switch_effect` only takes a single variant, it doesn't run on the "otherwise" edge, and we don't assume anything about variants that aren't handled on that edge.

**Comment by oli-obk** [comment]
We used to have a plain Switch terminator which worked on enums, but eliminated it in favour of reading the discriminant and then running SwitchInt on that

**Review by oli-obk — APPROVED** [review]

**Comment by ecstatic-morse** [comment]
@bors rollup=never

for perf

**Pull request merged**
