### PR TITLE
Update rustc-guide submodule

### PR DESCRIPTION
**Pull request by mark-i-m**
Just keeping up with the head...

r? @steveklabnik

### CODE REVIEW

**Comment by ehuss** [comment]
@mark-i-m What is the story for this submodule?  It is currently not published anywhere, which is a bit unusual.  

I'm looking at updating the documentation every few weeks, and I can include this in the updates if you'd like.  However, since I didn't see it being used, I wasn't sure what it was for.

**Comment by mark-i-m** [comment]
@ehuss The plan is for toolstate to be used to check it, but I’ve pretty slow about implementing that. I just opened https://github.com/rust-lang/rust/issues/59597... which should be a good first PR for someone.

Updating the docs every few weeks would be super helpful, especially when toolstate is in place.

**Comment by steveklabnik** [comment]
>  It is currently not published anywhere, which is a bit unusual.

Yes, I thought that it was. My intention was to create a PR to start publishing it. I haven't gotten to it yet though.

**Comment by mark-i-m** [comment]
Currently it is published via our own CI here: https://rust-lang.github.io/rustc-guide/

**Pull request merged**
