### PR TITLE
`as_deref()` and `as_deref_mut()` impls

### PR DESCRIPTION
**Pull request by U007D**
addresses #50264 
renamed `deref()` -> `as_deref()`
added `deref_mut()` impls + tests
fixed breaking changes

### CODE REVIEW

**Comment by joshtriplett** [comment]
LGTM, though I'm not a libs reviewer.

**Comment by Kimundi** [comment]
@bors: r+

Seems like a sensible change, based on the discussion so far.

**Comment by Centril** [comment]
@bors r-

Failed in https://github.com/rust-lang/rust/pull/59692#issuecomment-479882228 due to miri toolstate.
cc @RalfJung

**Comment by RalfJung** [comment]
Looks like the old `deref` is used by Miri? Then I guess it has to be deprecated instead of removed, so that Miri can be moved to the new thing.

Or land this separately from a Miri update so that breaking Miir is not fatal.

**Comment by U007D** [comment]
Hi, @RalfJung,

I'm not fluent with the Rust release process, but can a featue which has never been stable be deprecated?  Or are you recommending the method name be reverted from `as_deref()` back to `deref()`?

**Comment by RalfJung** [comment]
> can a feature which has never been stable be deprecated?

Yes. Just add a `#[rustc_deprecated]` attribute next to the `#[unstable]`.

**Comment by Centril** [comment]
@U007D We can break miri again so you don't need to use `rustc_deprecated` here, just rebase your PR and we should be good to go.

**Comment by RalfJung** [comment]
Sure, that also works. No idea how widely used this function is.

(What happened last time was not about tools not breaking due to beta; it was that this one got rolled up with an "update miri" PR. Changing a tool and breaking it in the same PR leads to CI failure.)

**Comment by Dylan-DPC** [comment]
ping from triage @U007D any updates?

**Comment by jonas-schievink** [comment]
Triage ping @U007D, this needs a few merge conflicts to be resolved

**Comment by Dylan-DPC** [comment]
ping from triage @U007D 
Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again!

**Pull request closed without merging**
