### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
9 commits in a4c63fe5388beaa09e5f91196c86addab0a03580..7065f0ef4aa267a7455e1c478b5ccacb7baea59c
2024-03-06 22:15:17 +0000 to 2024-03-12 13:25:15 +0000
- chore: remove repetitive word (rust-lang/cargo#13575)
- refactor(lockfile): Make diffing/printing more reusable (rust-lang/cargo#13564)
- test: Add tests for using worktrees and sparse checkouts (rust-lang/cargo#13567)
- util/network/http: Use `cargo/1.2.3` user-agent header (rust-lang/cargo#13548)
- fix: Consistently compare MSRVs (rust-lang/cargo#13537)
- refactor(shell): Use alternate to close links (rust-lang/cargo#13562)
- fix(doc): Collapse down Generated statuses without --verbose (rust-lang/cargo#13557)
- doc: Add doc for -Zpublic-dependency (rust-lang/cargo#13556)
- docs: add link to the exported_private_dependencies lint (rust-lang/cargo#13547)

r? ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
Hmm… didn't get it. There is no change obviously affecting performance in Cargo. `tt-muncher` looks even less relevant.

**Comment by Kobzol** [comment]
I wouldn't worry about it. Updating cargo almost always introduces small perf. changes, unless something really large stands out, we usually don't deal with it.

**Comment by Kobzol** [comment]
The muncher change looks like noise, based on the historical chart.

@rustbot label: +perf-regression-triaged

**Pull request merged**
