### PR TITLE
Stabilize `IpAddr::is_ipv4` and `is_ipv6` as const

### PR DESCRIPTION
**Pull request by CDirkx**
Insta-stabilize the methods `is_ipv4` and `is_ipv6` of `std::net::IpAddr` as const, in the same way as [PR#76198](https://github.com/rust-lang/rust/pull/76198).

Possible because of the recent stabilization of const control flow.

Part of #76225 and #76205.

### CODE REVIEW

**Comment by KodrAus** [comment]
@rfcbot fcp merge

This is another set of constifying for boolean-style match methods. This time for `IpAddr`:

```rust
impl IpAddr {
    pub const fn is_ipv4;
    pub const fn is_ipv6;
}
```

**Review by dtolnay — APPROVED** [review]

**Comment by CDirkx** [comment]
I bumped the version to 1.50.0

**Comment by dtolnay** [comment]
Good catch, thanks.
@bors r+

**Pull request merged**
