### PR TITLE
[beta] Backport https://github.com/rust-lang/rust/pull/50748 to beta

### PR DESCRIPTION
**Pull request by steveklabnik**
This should wait until the backport is approved https://github.com/rust-lang/rust/pull/50748#issuecomment-388881450

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

No need for a high p=, this is a low priority backport and can land at any time

**Comment by pietroalbini** [comment]
Maybe I can merge this in #50741 to avoid having two backport PRs in the queue?

**Comment by alexcrichton** [comment]
Sure yeah! Feel free to close this one if you do that

**Comment by pietroalbini** [comment]
Merged into https://github.com/rust-lang/rust/pull/50741.

**Pull request closed without merging**
