### PR TITLE
Stabilize #[coverage] attribute

### LINKED ISSUE #84605: Tracking issue for function attribute `#[coverage]`
This issue will track the approval and stabilization of the attribute `coverage`, needed to give developers a way to "hide" a function from the coverage instrumentation enabled by `rustc -Z instrument-coverage`.

The `Eq` trait in the `std` library implements a marker function that is not meant to be executed, but results in an uncovered region in all rust programs that derive `Eq`. This attribute will allow the compiler to skip that function, and remove the uncovered regions.

## Unresolved questions

* is it ok that the attribute applied to the crate root, a function, or a module applies to *all* items within the marked item? So far we do not have such attributes other than the lint level attributes.

### PR DESCRIPTION
**Pull request by clarfonthey**
Closes #84605, which passed FCP.

Stabilisation report here: https://github.com/rust-lang/rust/issues/84605#issuecomment-2166514660

Also added to reference here: rust-lang/reference#1628

---

try-job: aarch64-apple
try-job: x86_64-gnu
try-job: x86_64-msvc

### CODE REVIEW

**Comment by nnethercote** [comment]
I will forward this to a more appropriate reviewer:

r? @Zalathar

**Comment by clarfonthey** [comment]
FWIW, I'm currently working on fixing the test errors-- my computer kept crashing which made it difficult to run all the tests. Unfortunately a *lot* of coverage tests are now off-by-one due to the removal of the line enabling the feature, and they're all going to have to be re-blessed.

**Comment by clarfonthey** [comment]
Appear to be getting very weird crashes with the debuginfo tests. From the backtrace:

<details><summary>Backtrace</summary>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x000075b3eae5d463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x000075b3eae04120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x000075b3eadeb4c3 in __GI_abort () at abort.c:79
#4  0x000075b3eb0e451b in fatal_error_exit (status=-1) at Python/pylifecycle.c:2737
#5  fatal_error (fd=<optimized out>, header=header@entry=1, prefix=prefix@entry=0x75b3eb372990 <__func__.10.lto_priv.1> "PyImport_AppendInittab", msg=msg@entry=0x75b3eb2bf7c0 "PyImport_AppendInittab() may not be called after Py_Initialize()", status=status@entry=-1) at Python/pylifecycle.c:2848
#6  0x000075b3eb0e4899 in _Py_FatalErrorFunc (func=0x75b3eb372990 <__func__.10.lto_priv.1> "PyImport_AppendInittab", msg=0x75b3eb2bf7c0 "PyImport_AppendInittab() may not be called after Py_Initialize()") at Python/pylifecycle.c:2934
#7  0x000075b3eb034330 in PyImport_AppendInittab (name=<optimized out>, initfunc=<optimized out>) at Python/import.c:1499
#8  0x000075b3e9c61aa2 in InitializePythonRAII () at /usr/src/debug/lldb/lldb-18.1.8.src/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp:110
#9  lldb_private::ScriptInterpreterPythonImpl::Initialize () at /usr/src/debug/lldb/lldb-18.1.8.src/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp:2938
#10 0x000075b3eae608fb in __pthread_once_slow (once_control=0x75b3ea3c32a4 <lldb_private::ScriptInterpreterPython::Initialize()::g_once_flag>, init_routine=0x75b3ddc9e2e0 <std::__once_proxy()>) at pthread_once.c:116
#11 0x000075b3eae60979 in ___pthread_once (once_control=<optimized out>, init_routine=<optimized out>) at pthread_once.c:143
#12 0x000075b3e96f5180 in __gthread_once () at /usr/include/c++/14.1.1/x86_64-pc-linux-gnu/bits/gthr-default.h:713
#13 call_once<lldb_private::ScriptInterpreterPython::Initialize()::<lambda()> > () at /usr/include/c++/14.1.1/mutex:916
#14 call_once<lldb_private::ScriptInterpreterPython::Initialize()::<lambda()> > () at /usr/include/llvm/Support/Threading.h:89
#15 lldb_private::ScriptInterpreterPython::Initialize () at /usr/src/debug/lldb/lldb-18.1.8.src/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp:348
#16 lldb_private::lldb_initialize_ScriptInterpreterPython () at /usr/src/debug/lldb/lldb-18.1.8.src/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp:64
#17 lldb_private::SystemInitializerFull::Initialize () at /usr/src/debug/lldb/lldb-18.1.8.src/build/source/Plugins/Plugins.def:104
#18 0x000075b3e95c543e in lldb_private::SystemLifetimeManager::Initialize () at /usr/src/debug/lldb/lldb-18.1.8.src/source/Initialization/SystemLifetimeManager.cpp:36
#19 lldb::SBDebugger::InitializeWithErrorHandling () at /usr/src/debug/lldb/lldb-18.1.8.src/source/API/SBDebugger.cpp:219
#20 0x000075b3e9727ddb in lldb::SBDebugger::Initialize () at /usr/src/debug/lldb/lldb-18.1.8.src/source/API/SBDebugger.cpp:175
#21 _wrap_SBDebugger_Initialize () at /usr/src/debug/lldb/lldb-18.1.8.src/build/bindings/python/LLDBWrapPython.cpp:23282
#22 0x000075b3eb13bd1b in cfunction_vectorcall_NOARGS (func=0x75b3ea6f6750, args=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at ./Include/cpython/methodobject.h:50
#23 0x000075b3eb15caed in _PyObject_VectorcallTstate (tstate=0x75b3eb5e3198 <_PyRuntime+459704>, callable=0x75b3ea6f6750, args=0x75b3eb5f1468, nargsf=9223372036854775808, kwnames=0x0) at ./Include/internal/pycore_call.h:92
#24 PyObject_Vectorcall (callable=0x75b3ea6f6750, args=0x75b3eb5f1468, nargsf=9223372036854775808, kwnames=0x0) at Objects/call.c:325
#25 0x000075b3eb141829 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:2715
#26 0x000075b3eb2064b5 in PyEval_EvalCode (co=0x5cdfa44d2040, globals=<optimized out>, locals=0x75b3ea855980) at Python/ceval.c:578
#27 0x000075b3eb222a76 in builtin_exec_impl (module=<optimized out>, source=0x5cdfa44d2040, globals=0x75b3ea855980, locals=0x75b3ea855980, closure=<optimized out>) at Python/bltinmodule.c:1096
#28 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/clinic/bltinmodule.c.h:586
#29 0x000075b3eb15cc3e in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<optimized out>, args=0x75b3ea86e358, nargsf=<optimized out>, kwnames=0x0) at Objects/methodobject.c:438
#30 0x000075b3eb146c11 in PyCFunction_Call (callable=0x75b3ea938770, args=0x75b3ea86e340, kwargs=0x75b3ea86fec0) at Objects/call.c:387
#31 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:3263
#32 0x000075b3eb16798b in _PyObject_VectorcallTstate (tstate=0x75b3eb5e3198 <_PyRuntime+459704>, callable=0x75b3ea93c040, args=0x7ffce28e7510, nargsf=2, kwnames=0x0) at ./Include/internal/pycore_call.h:92
#33 object_vacall (tstate=tstate@entry=0x75b3eb5e3198 <_PyRuntime+459704>, base=<optimized out>, callable=0x75b3ea93c040, vargs=0x7ffce28e75a0) at Objects/call.c:850
#34 0x000075b3eb1999eb in PyObject_CallMethodObjArgs (obj=<optimized out>, name=<optimized out>) at Objects/call.c:911
#35 0x000075b3eb198f19 in import_find_and_load (tstate=0x75b3eb5e3198 <_PyRuntime+459704>, abs_name=0x75b3ea7ac360) at Python/import.c:2779
#36 PyImport_ImportModuleLevelObject (name=0x75b3ea7ac360, globals=<optimized out>, locals=<optimized out>, fromlist=0x75b3eb56a460 <_Py_NoneStruct>, level=0) at Python/import.c:2862
#37 0x000075b3eb1494d1 in import_name (tstate=<optimized out>, frame=<optimized out>, name=0x75b3ea7ac360, fromlist=0x75b3eb56a460 <_Py_NoneStruct>, level=0x75b3eb573aa8 <_PyRuntime+3272>) at Python/ceval.c:2482
#38 _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/bytecodes.c:2144
#39 0x000075b3eb2064b5 in PyEval_EvalCode (co=0x5cdfa44ec7e0, globals=<optimized out>, locals=0x75b3ea77ef00) at Python/ceval.c:578
#40 0x000075b3eb22a84a in run_eval_code_obj (tstate=tstate@entry=0x75b3eb5e3198 <_PyRuntime+459704>, co=co@entry=0x5cdfa44ec7e0, globals=globals@entry=0x75b3ea77ef00, locals=locals@entry=0x75b3ea77ef00) at Python/pythonrun.c:1722
#41 0x000075b3eb22572f in run_mod (mod=mod@entry=0x5cdfa450e6a0, filename=filename@entry=0x75b3ea7c1590, globals=globals@entry=0x75b3ea77ef00, locals=locals@entry=0x75b3ea77ef00, flags=flags@entry=0x7ffce28e7b90, arena=arena@entry=0x75b3ea8b5fd0) at Python/pythonrun.c:1743
#42 0x000075b3eb23fd14 in pyrun_file (fp=fp@entry=0x5cdfa43ec550, filename=filename@entry=0x75b3ea7c1590, start=start@entry=257, globals=globals@entry=0x75b3ea77ef00, locals=locals@entry=0x75b3ea77ef00, closeit=closeit@entry=1, flags=0x7ffce28e7b90) at Python/pythonrun.c:1643
#43 0x000075b3eb23f5a1 in _PyRun_SimpleFileObject (fp=0x5cdfa43ec550, filename=0x75b3ea7c1590, closeit=1, flags=0x7ffce28e7b90) at Python/pythonrun.c:433
#44 0x000075b3eb23ecff in _PyRun_AnyFileObject (fp=0x5cdfa43ec550, filename=0x75b3ea7c1590, closeit=1, flags=0x7ffce28e7b90) at Python/pythonrun.c:78
#45 0x000075b3eb2374c4 in pymain_run_file_obj (program_name=0x75b3ea77f030, filename=0x75b3ea7c1590, skip_source_first_line=0) at Modules/main.c:360
#46 pymain_run_file (config=0x75b3eb585d78 <_PyRuntime+77720>) at Modules/main.c:379
#47 pymain_run_python (exitcode=0x7ffce28e7b64) at Modules/main.c:633
#48 Py_RunMain () at Modules/main.c:713
#49 0x000075b3eb1f1c2c in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:767
#50 0x000075b3eadece08 in __libc_start_call_main (main=main@entry=0x5cdf84c7e120 <main>, argc=argc@entry=4, argv=argv@entry=0x7ffce28e7df8) at ../sysdeps/nptl/libc_start_call_main.h:58
#51 0x000075b3eadececc in __libc_start_main_impl (main=0x5cdf84c7e120 <main>, argc=4, argv=0x7ffce28e7df8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffce28e7de8) at ../csu/libc-start.c:360
#52 0x00005cdf84c7e045 in _start ()
```

</details>

I'm just going to run `./x clean` and hope that fixes it. But it looks like there might be some weird inconsistency between Rust wanting to run the version of LLVM in the repo, and the one on my machine…

**Comment by traviscross** [comment]
cc @rust-lang/lang

**Comment by jieyouxu** [comment]
> Yeah, okay. It might also be a difference in Python 3.12 that broke something too, but either way, the debuginfo tests show up as failing on my machine and the coverage tests show up as passing also, so, something weird is afoot.

I'm not exactly sure what debuginfo tests want, but bootstrap and other parts of compiletest AFAIK assumes Python 3.10 *exactly*, not 3.9 or 3.12.

**Comment by clarfonthey** [comment]
> > Yeah, okay. It might also be a difference in Python 3.12 that broke something too, but either way, the debuginfo tests show up as failing on my machine and the coverage tests show up as passing also, so, something weird is afoot.
> 
> I'm not exactly sure what debuginfo tests want, but bootstrap and other parts of compiletest AFAIK assumes Python 3.10 _exactly_, not 3.9 or 3.12.

That feels worth documenting somewhere, considering how on my end that just shows up as LLVM hard-crashing and not as a wrong Python version. Like, maybe even worth having a virtualenv setup for the repo just to guarantee the right Python version is being used.

**Comment by jieyouxu** [comment]
I'm not sure if that's the root cause of your crashes, but if it is, then yes

**Comment by jieyouxu** [comment]
Actually sorry minor correction: it's not bootstrap that expects Python 3.10, but something in compiletest (maybe debuginfo tests?) expect Python 3.10 dll to be available.

**Comment by jieyouxu** [comment]
> That feels worth documenting somewhere, considering how on my end that just shows up as LLVM hard-crashing and not as a wrong Python version. Like, maybe even worth having a virtualenv setup for the repo just to guarantee the right Python version is being used.

This is cc https://github.com/rust-lang/rust/issues/125706 https://github.com/rust-lang/rust/issues/128392 and https://github.com/rust-lang/rust/issues/128392

**Comment by clarfonthey** [comment]
You linked #128392 twice, which I assume is a mistake.

**Comment by jieyouxu** [comment]
> You linked #128392 twice, which I assume is a mistake.

I meant to link https://github.com/rust-lang/rust/issues/126092, but I had both issues ending in `92` open at once and I got confused.

**Comment by clarfonthey** [comment]
Yeah, I'm giving up on getting the debuginfo tests working. But I'll poke around to see if I can get the other tests to replicate their issues.

**Comment by clarfonthey** [comment]
It seems that even running the test suite via docker, I can't replicate the latest errors. Running `../x test --stage 2` inside the container either passes with no issues, or gives me an error about being unable to find `ld`…

Looks like I've stumbled my way into the realm of cursed compiler testing issues that I don't know how to fix.

**Comment by jieyouxu** [comment]
> It seems that even running the test suite via docker, I can't replicate the latest errors. Running `../x test --stage 2` inside the container either passes with no issues, or gives me an error about being unable to find `ld`…

I can't reproduce the failures either on an aarch64-unknown-linux-gnu dev desktop (with `./x test coverage`).

**Comment by jieyouxu** [comment]
@clarfonthey I tried to run `./x test coverage --stage 1` on your PR locally, 4 coverage tests failed because I think they now have trailing new line...?

```
failures:
    [coverage-run] tests/coverage/branch/if-let.rs
    [coverage-run] tests/coverage/attr/nested.rs
    [coverage-run] tests/coverage/await_ready.rs
    [coverage-run] tests/coverage/coverage_attr_closure.rs
```

**Comment by jieyouxu** [comment]
I can't reproduce the crashes,

```
Testing stage1 compiletest suite=coverage mode=coverage-map (x86_64-unknown-linux-gnu)

running 90 tests
i...........i.................iiiii..................................................... 88/90
..

test result: ok. 83 passed; 0 failed; 7 ignored; 0 measured; 0 filtered out; finished in 726.19ms

Testing stage1 compiletest suite=coverage mode=coverage-run (x86_64-unknown-linux-gnu)

running 90 tests
.............i..................iiiii................................................... 88/90
..

test result: ok. 84 passed; 0 failed; 6 ignored; 0 measured; 0 filtered out; finished in 1.46s
```

**Comment by jieyouxu** [comment]
... because `tests/coverage/mcdc` requires additional things.

**Comment by clarfonthey** [comment]
Yeah, I was under the impression that using the Docker image would be the best bet to replicate the crashes, but no…

**Comment by jieyouxu** [comment]
@clarfonthey I rebased then reblessed the coverage tests, let's see if PR CI still complains...

**Comment by jieyouxu** [comment]
In the meantime, I'll try to see if I rollback the llvm to use one that's llvm 18, build that locally, and use that to rebless the MCDC tests...

**Comment by jieyouxu** [comment]
I have a hard time trying to force an older rust-lang/llvm-project to be built with bootstrap, maybe @Zalathar knows how to rebless these MCDC tests...

**Comment by jieyouxu** [comment]
Tbh, I'm not even opposed to disabling mcdc tests temporarily `//@ ignore-test (FIXME: mcdc tests are not supported on llvm 19)` and re-enable them with https://github.com/rust-lang/rust/pull/126733.

**Comment by clarfonthey** [comment]
Since it appears that both this PR and that one are waiting on a review from @Zalathar, I wouldn't mind just blocking this one until that one merges. Gonna mark as blocked for now and edit the description in the meantime.

@rustbot blocked

**Comment by matthiaskrgr** [comment]
There are some easy-to-run-into panics related to attribute parsing, should this be fixed first? https://github.com/rust-lang/rust/issues/127880

**Comment by clarfonthey** [comment]
This is the first time I've seen this issue, but yes, that seems worth a fix.

**Comment by Zalathar** [comment]
I've filed #131187 to fix the ICE.

**Comment by clarfonthey** [comment]
Still the obnoxious Python issue, but going to try and see if blessing the tests locally actually works this time. Gonna let that run while I go do other things.

**Comment by clarfonthey** [comment]
Looks like everything is passing now. Gonna mark as ready for review.

@rustbot review

**Comment by psandana** [comment]
@clarfonthey besides merge conflicts, what else is needed to merge this PR and move forward towards stable?

**Comment by clarfonthey** [comment]
It just requires review; I've not fixed the merge conflicts because nobody has taken a look yet, but I can do that soon.

**Review by wesleywiser — APPROVED** [review]
Thanks for the PR and the stabilization report @clarfonthey! 

I'm satisfied with the implementation and covering tests.

r=me when rebased

**Comment by clarfonthey** [comment]
Rebased, let's see if I caught everything…

**Comment by clarfonthey** [comment]
(I would wait for the PR runs to finish first, since last time I had a bunch of issues that weren't caught by my local testing, and I want to verify those pass before we clog up the merge queue.)

**Comment by clarfonthey** [comment]
Seems to pass!

**Comment by Zalathar** [comment]
(Unrelated to the above failure)

Suggestion: Instead of deleting `#![feature(coverage_attribute)]` from tests, consider commenting it out instead. The `.coverage` snapshots would still need to be re-blessed, but the `.cov-map` snapshots wouldn't change at all, which might make this PR less bitrotty. Then the commented-out lines could be deleted in a later PR, separate from the stabilization PR.

(Feel free to only do this if you think it would actually help.)

**Comment by clarfonthey** [comment]
I think I figured out the issue— one test required the profiler runtime which wasn't tested on the PR tests, but is tested in the merge tests. It should work now.

**Comment by Zalathar** [comment]
Giving this a try job on the main targets that run coverage tests:

@bors try

**Comment by clarfonthey** [comment]
I guess I'll begrudgingly set up a test docker image and do it that way. Heading out soon but I can at least start the build now and let it run while I'm shopping, since it'll be quite a while.

**Comment by clarfonthey** [comment]
Apparently, blessing the `build.profiler = true` tests just added an extra newline to the end of them. This appears to be the catastrophic failure that stopped CI from passing, since that was all I could find from running the tests, including after rebasing. I didn't run the aarch64 tests via qemu but I'm assuming that the architecture-specific stuff isn't failing… hopefully.

Maybe third time's the charm?

**Comment by clarfonthey** [comment]
@bors merge

(idk if delegate lets me do this, let's find out)

**Pull request merged**
