### PR TITLE
fix typo in primitive-types section on slices

### PR DESCRIPTION
**Pull request by jpreiss**

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks a ton!

**Comment by jpreiss** [comment]
sorry, I did not intend to make c0c43b1 part of this pull request, but it is just another small typo fix.

**Comment by steveklabnik** [comment]
@jpreiss no worries, it just meant that it un-approved it. The second fix looks good as well, so let's just put them together :smile: 

@bors: r+ rollup

**Comment by steveklabnik** [comment]
@jpreiss no worries, it just meant that it un-approved it. The second fix looks good as well, so let's just put them together :smile: 

@bors: r+ rollup

**Pull request merged**
