### PR TITLE
Implement `str::from_raw_parts()` and `str::from_raw_parts_mut()`

### PR DESCRIPTION
**Pull request by Kixiron**
Implements `str::from_raw_parts()` and `str::from_raw_parts_mut()` which are effectively shorthand for

```rust
let bytes = slice::from_raw_parts(ptr, len);
str::from_utf8_unchecked(bytes)
```

@rustbot label: +T-libs +T-core

ACP: https://github.com/rust-lang/libs-team/issues/167.

### CODE REVIEW

**Comment by thomcc** [comment]
Can you file an ACP?

**Comment by tgross35** [comment]
Could you something like, "if there is any doubt that the incoming data may not be UTF-8, prefer `str::from_utf8(slice::from_raw_parts(ptr, len))` instead", to point people in the right diretion?

Also, I think it would be better to provide a short summary of the safety guarantess and then point to `slice::from_raw_parts{mut}` for the details rather than duplicating the documentation.

**Comment by Sky9x** [comment]
any update on this? would be very nice to have

**Comment by Sky9x** [comment]
I've opened a tracking issue: #119206

**Pull request closed without merging**
