### PR TITLE
Centralize panic macro documentation

### LINKED ISSUE #61327: `core::panic` documentation is useless
For some reason, the [documentation for `core::panic`](https://doc.rust-lang.org/core/macro.panic.html) does not contain any of the useful pieces of information of `std::panic`'s documentation and instead references a non-existent module `std::macros`.

### PR DESCRIPTION
**Pull request by czipperz**
Closes #61327

### CODE REVIEW

**Comment by czipperz** [comment]
Haha the docs lied

**Comment by czipperz** [comment]
I'm not sure that making a macros directory is the right approach here.  Should we have a shared documentation folder?

**Comment by Dylan-DPC** [comment]
ping from triage 
r? @steveklabnik 
can you review this?

**Comment by czipperz** [comment]
Before I rebase this, I would like to come to a definitive conclusion on my previous concern

**Comment by edmilsonefs** [comment]
Hey! This is a ping from triage, we would like to know if there is someone from @rust-lang/docs which can help here.

Your effort would be well appreciated!

**Comment by Dylan-DPC** [comment]
@rust-lang/docs

**Comment by edmilsonefs** [comment]
**Note**: I just got a feedback from @steveklabnik on Discord and he told me he will check it in a few hours.

**Comment by steveklabnik** [comment]
I am not sure what the answer is:

> I'm not sure that making a macros directory is the right approach here. Should we have a shared documentation folder?

@rust-lang/rustdoc is better equipped to give advice than I am.

**Comment by GuillaumeGomez** [comment]
Looks good to me! r=me once conflicts fixed.

**Comment by czipperz** [comment]
Rebased

**Comment by GuillaumeGomez** [comment]
Arf sorry, didn't see your message... Please rebase once more and ping me.

**Comment by czipperz** [comment]
@GuillaumeGomez rebased

**Comment by GuillaumeGomez** [comment]
Tests failed.

**Comment by czipperz** [comment]
mingw seems to be spuriously failing?  linux x86_64 is erroring with:

```
tidy check
* 577 error codes
* highest error code: E0732
* 267 features
tidy error: `/checkout/src/libcore/macros/mod.rs` contains `#[test]`; libcore tests must be placed inside `src/libcore/tests/`
some tidy checks failed
```

I don't get why master is green if this is the case because I haven't edited the macros.rs file but rather just moved it to mod.rs.  I can pull out the tests I guess

**Comment by czipperz** [comment]
I'm trying to build locally and am getting a lot of weird build breakages.

**Comment by czipperz** [comment]
Specifically when `src/libcore/macros/mod.rs` includes `macros/panic.md` it fails saying it can't find `src/libcore/macros/macros/panic.md`.  Then when I change it to include `panic.md` it fails saying it can't find `src/libcore/panic.md`.  Then I change it back to `macros/panic.md` and it starts working again.  Very strange.  Doing `./x.py test -i --stage 1 src/test/ui` fyi.

**Comment by czipperz** [comment]
```
error: couldn't read src/libcore/macros/macros/panic.md: No such file or directory (os error 2)
 --> src/libcore/macros/mod.rs:1:17
  |
1 | #[doc(include = "macros/panic.md")]
  |                 ^^^^^^^^^^^^^^^^^ couldn't read file
```

**Comment by jplatte** [comment]
A related PR was merged 5 days ago: https://github.com/rust-lang/rust/pull/60938

That might be the cause of the CI issues. This PR *might* have to wait for the release of Rust 1.37 due to bootstrapping concerns (I'm not an expert on this though).

**Comment by GuillaumeGomez** [comment]
Let's wait for the new release then. Extra safety doesn't hurt.

**Comment by hdhoang** [comment]
from triage: I have changed this PR to S-blocked, waiting for rust 1.37 release. The author will resolve conflict afterwards.

**Comment by Mark-Simulacrum** [comment]
Moving back to waiting-on-author. This should be no longer blocked on release process (we're in 1.40 cycle now).

**Comment by joelpalmer** [comment]
Ping from Triage:  @czipperz Any updates?

**Comment by czipperz** [comment]
Ping me again next week and I'll rebase it

**Comment by Alexendoo** [comment]
Ping from triage: @czipperz Next week is upon us

**Comment by joelpalmer** [comment]
Ping from triage: @czipperz any updates?

**Comment by Dylan-DPC** [comment]
Closing this due to inactivity. @czipperz thanks for contributing :)

**Pull request closed without merging**
