### PR TITLE
Teach `compiletest` to ignore platform triples

### PR DESCRIPTION
**Pull request by estebank**
The UI tests are written assuming `--remap-path-prefix` is *not used* (`remap-debuginfo` in `config.toml`). The consequence is that the error messages may include paths and snippets into the standard library. When `remap-debuginfo` is enabled, these messages change in format and structure because `rustc` will not show paths and snippets into the standard library.

This normally isn't a problem for the "main" platforms (linux/macos/windows), because the CI infrastructure is set up so that the tests run without `remap-debuginfo`, but the `dist` artifacts are built separately with `remap-debuginfo` enabled. However, some of the lower-tier platforms perform both tests and distribution in a single step with `remap-debuginfo` enabled. This also affects developers and distributors who use `remap-debuginfo`.

To sidestep this problem, we add a way to ignore tests in specific platform triples, and update the overly broad `ignore-x86` rule in affected tests.

Address #46948, #54546, #53081.

### CODE REVIEW

**Comment by estebank** [comment]
As (I think) we don't have a way to run the entire test suite for all platforms outside of r+ing, we might need a couple of back and forth tweaking the triple ignore list to get this right.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+ 

This seems strictly better than the current situation, though ignoring tests always gives me a bad feeling.

I wonder @estebank if there would be some way to pass a `-Z` flag to suppress the "remap-path-prefix" sort of behavior? I guess not easily.

**Comment by estebank** [comment]
I believe that turning the remap would actually make things worse, I'm afraid.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/67451#issuecomment-567980328, @bors r- rollup=never p=1

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/67580 adds another of these `ignore-x86`.

**Pull request merged**
