### PR TITLE
Implement get_pair for HashMap

### LINKED ISSUE #43143: Add a function to get the key from a HashMap
Basically just
```
pub fn get_both<Q: ?Sized>(&self, k: &Q) -> Option<(&K,&V)>
        where K: Borrow<Q>,
              Q: Hash + Eq
    {
        self.search(k).into_occupied_bucket().map(|bucket| bucket.into_refs())
}
```
sometimes you need a reference to a key with the lifetime of the collection.

### PR DESCRIPTION
**Pull request by Diggsey**
Fixes #43143

### CODE REVIEW

**Comment by stjepang** [comment]
Any reason for not adding the same method to `BTreeMap`?

**Comment by Diggsey** [comment]
No, it just wasn't mentioned in the issue - I will add it there too.

**Comment by nvzqz** [comment]
Is it possible to have `get_pair_mut` that returns `Option<(&K, &mut V)>`?

**Comment by Diggsey** [comment]
@nvzqz The entry api covers that case

**Comment by nvzqz** [comment]
The entry api requires passing an owned key (`K`) whereas this allows passing any `Q where K: Borrow<Q>`.

**Comment by alexcrichton** [comment]
ping @rust-lang/libs, thoughts on this API/naming?

**Comment by sfackler** [comment]
#47259 added `HashMap::remove_entry` - the namings for the remove and access should hopefully match. `get_entry` may be confusing though in comparison to `entry`?

**Comment by RReverser** [comment]
I'll back `get_pair_mut` suggestion, but even without it this addition looks pretty good.

**Comment by RReverser** [comment]
Although `get_pair_mut` could instead be `occupied_entry(&K) -> OccupiedEntry` instead to provide all the convenient mutation APIs for free, so probably unrelated to this PR.

**Comment by Diggsey** [comment]
I've added the BTreeMap method too. I'm not going to add the mutable versions as part of this PR as I think there are still some questions about what the API should look like.

**Comment by aturon** [comment]
Sorry for the delay on this from the libs team!

I think that `get_entry` is too confusing, as @sfackler mentioned, but `get_pair` is not very self-explanatory.

How about `get_key_value`?

**Comment by pietroalbini** [comment]
@Diggsey someone from the libs team replied with a suggestion for another name, can you implement that?

**Comment by pietroalbini** [comment]
@Diggsey thanks for taking the time to send this PR! Unfortunately, there was no activity for more than two weeks, so I'm closing it. If you have time to work on it again, feel free to open another PR with the new changes, we'll be happy to review and merge it!

**Pull request closed without merging**
