### PR TITLE
rustdoc: do not allocate String when writing path full name

### PR DESCRIPTION
**Pull request by notriddle**
No idea if this makes any perf difference, but it just seems like premature pessimisation to use String when str will do.

### CODE REVIEW

**Review by camelid — APPROVED** [review]
Even if it's not faster, it's simpler!

**Comment by camelid** [comment]
This is only used in the JSON backend, which I believe isn't tested in perf, and it's changing pretty drastically over time, so @bors rollup

**Comment by aDotInTheVoid** [comment]
Yeah, we don't yet have perf test for rustdoc-json, but we should (#94141)

**Pull request merged**
