### PR TITLE
Add functions for reversing the bit pattern in an integer

### PR DESCRIPTION
**Pull request by Amanieu**
This adds the `bitreverse` intrinsic and adds a `reverse_bits` function to all integer types.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Could you elaborate on the motivation for this a bit as well? Looking at the assembly of LLVM for x86_64 it doesn't seem to be doing much special beyond what one could write in Rust anyway?

**Comment by Amanieu** [comment]
On ARM, there are dedicated instructions for reversing bits. The intrinsic would lower to a single `RBIT` instruction.

**Comment by Amanieu** [comment]
It seems this intrinsic is only supported on LLVM 3.8+. Since Rust currently supports LLVM 3.6+, should I add a software fallback implementation for older LLVM versions?

**Comment by alexcrichton** [comment]
Is there motivation beyond just exporting this because we probably should? Adding a fallback is probably pretty complicated and perhaps not worth it at this time, so it may be best to just wait until we bump the required LLVM version if it's just a nice-to-have.

**Comment by Amanieu** [comment]
I just thought it would be nice to expose these intrinsics to Rust, I don't have a particularly urgent reason to use them myself.

**Comment by alexcrichton** [comment]
Ah ok, in that case I'm going to close this for now as we're still trying to remain compatible with LLVM 3.6. If you'd like to draft up a PR to support this even on 3.6 (with a fallback), feel free to send a PR though!

**Pull request closed without merging**
