### PR TITLE
Clean up diagnostics for arithmetic operation errors

### PR DESCRIPTION
**Pull request by varkor**
Plus a small tweak to a range pattern error message.

### CODE REVIEW

**Comment by jyn514** [comment]
Failed in rollup (https://github.com/rust-lang/rust/pull/76951):
```
 ---- [ui] ui/lint/lint-exceeding-bitshifts.rs#opt stdout ----
diff of stderr:

140	  --> $DIR/lint-exceeding-bitshifts.rs:77:15
141	   |
142	LL |       let n = 1_isize << BITS;
-	   |               ^^^^^^^^^^^^^^^ attempt to shift left by `64_usize`, which would overflow
+	   |               ^^^^^^^^^^^^^^^ attempt to shift left by `32_usize`, which would overflow
144	
145	warning: this arithmetic operation will overflow
146	  --> $DIR/lint-exceeding-bitshifts.rs:78:15

147	   |
148	LL |       let n = 1_usize << BITS;
-	   |               ^^^^^^^^^^^^^^^ attempt to shift left by `64_usize`, which would overflow
+	   |               ^^^^^^^^^^^^^^^ attempt to shift left by `32_usize`, which would overflow
150	
151	warning: 24 warnings emitted
```
Looks like you might need to normalize the size of `BITS` in the diagnostic?

**Comment by jyn514** [comment]
Looks spurious:

```
Run src/ci/scripts/install-clang.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  424M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1  424M    1 6779k    0     0  4627k      0  0:01:33  0:00:01  0:01:32 4624k
  3  424M    3 12.8M    0     0  6190k      0  0:01:10  0:00:02  0:01:08 6190k
curl: (56) SSLRead() return error -9806
clang+llvm-10.0.0-x86_64-apple-darwin/lib/libLLVMCore.a: Lzma library error:  No progress is possible
```

@bors retry

**Comment by jyn514** [comment]
You need to bless the `fulldeps` tests:
```

failures:
    [run-make] run-make-fulldeps/instrument-coverage-mir-cov-html-base
    [run-make] run-make-fulldeps/instrument-coverage-mir-cov-html-link-dead-code
```

**Comment by varkor** [comment]
I addressed the `fulldeps`, but unfortunately I couldn't run the entire test suite on my computer (it's been acting up lately), so I'm not certain there isn't another issue. Hopefully that's the last of them.

@bors r=ecstatic-morse

**Pull request merged**
