### PR TITLE
Add `Atomic*::from_ptr`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This PR adds functions in the following form to all atomic types:
```rust
impl AtomicT {
    pub const unsafe fn from_ptr<'a>(ptr: *mut T) -> &'a AtomicT;
}
```
r? @m-ou-se (we've talked about it before)

I'm not sure about docs & safety requirements, I'd appreciate some feedback on them.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Is there some reason why we don't have the interface like `&mut T -> &AtomicT`?

**Comment by WaffleLapkin** [comment]
@compiler-errors hate to break it to you, we have it: https://doc.rust-lang.org/std/sync/atomic/struct.AtomicU8.html#method.from_mut

**Comment by compiler-errors** [comment]
:forgor:

**Comment by m-ou-se** [comment]
Can you [open a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX)? Thanks!

**Comment by WaffleLapkin** [comment]
I've opened a tracking issue

**Pull request merged**
