### PR TITLE
Refactor coercions/adjustments

### PR DESCRIPTION
**Pull request by nrc**
@eddyb's preparatory work for DST coercions

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@nrc so I reviewed the code. I think it's good, but I have a couple of nits. For one, I think there is a simpler explanation for how AutoderefRef works. This seems to both be logical and fit what trans does, and also makes `Box` not really a special case. Anyway, I wrote this up here:

https://github.com/nikomatsakis/rust/commit/3f310aeaa954e77a50b9b8773c6a0e1708462162

that patch also includes a simplification to the `ExprUseVisitor` based on this idea that makes it less hacky. Thoughts?

r+ modulo these nits

**Comment by nrc** [comment]
Comments inline on your patch. I'm not sure I agree with you explanation 100%, but maybe I misunderstood something last night. It might be that there are just two views on this - the type system's and trans's and they're fundamentally a bit different.

The ExprUseVisitor change looks nice, I can't comment on whether I think it will work :-p

**Comment by nikomatsakis** [comment]
@nrc I responded inline. Seems like we see the code a bit differently...but I still stand by my interpretation ;) maybe we can discuss it online (either IRC or vidyo), or maybe @eddyb can weight in as to how he sees it.

**Comment by nrc** [comment]
Rebased and added Niko's changes (with a little reformatting).

**Pull request merged**
