### PR TITLE
Stabilize total_cmp

### PR DESCRIPTION
**Pull request by golddranks**
Stabilises `total_cmp` for <s>Rust 1.61.0</s>. **Didn't make it in time, will be in Rust 1.62.0.** Tracking issue: https://github.com/rust-lang/rust/issues/72599

### CODE REVIEW

**Comment by golddranks** [comment]
The latest `strict_provenance` changes made the feature list to conflict, so rebased it.

**Comment by scottmcm** [comment]
With the FCP complete (https://github.com/rust-lang/rust/issues/72599#issuecomment-1030701000), this looks good to me!  1.61 is still the right version per https://github.com/rust-lang/rust/blob/master/src/version, so let's see if it merges in time.

r? @scottmcm 
@bors r+

**Comment by scottmcm** [comment]
No lucky, the bump is happening now #95636

@bors r-

`r=me` with the stabilization version updated.

**Comment by golddranks** [comment]
Rebased, updated to 1.62.0 and squashed.

**Pull request merged**
