### PR TITLE
update Miri

### LINKED ISSUE #71241: `miri` no longer builds after rust-lang/rust#70629
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#70629, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @anyska, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/71241
r? @ghost Cc @rust-lang/miri

### CODE REVIEW

**Comment by RalfJung** [comment]
Actually https://github.com/rust-lang/rust/pull/71280 will break Miri again so probably it is better to wait until that lands.

**Comment by RalfJung** [comment]
Well, not sure when that PR is going to get reviewed, so I guess let's fix Miri in the mean time. The bors queue is pretty empty anyway.
@bors r+ p=1

**Comment by RalfJung** [comment]
Ah, but https://github.com/rust-lang/rust/pull/71170 could also have some interesting interactions. Let's wait for that.
@bors r-

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/71170 landed, and all looks good.
@bors r+

**Comment by RalfJung** [comment]
@bors r-
that PR is moving ahead now

**Comment by spastorino** [comment]
@RalfJung according to https://rust-lang-nursery.github.io/rust-toolstate/ miri is failing and the release is coming tomorrow. Unsure if this PR will fix miri, I guess it will, but I'm not sure why did you `r-` and if there's something I'd need to do for this to move forward.

**Comment by Mark-Simulacrum** [comment]
miri is not gated for releases, so that's not a problem (we've already prepared artifacts as of Monday, and cut beta yesterday).

This is not a blocker for the release.

**Comment by RalfJung** [comment]
Yeah, Miri is nightly-only. So releases really don't matter, we shouldn't even try to build it on beta/stable.

**Pull request merged**
