### PR TITLE
 [DO NOT MERGE] Test if sccache is the cause build flaky 

### PR DESCRIPTION
**Pull request by tesuji**
cc  #62558

r? @ghost

### CODE REVIEW

**Comment by lzutao** [comment]
2 errors are the same. I pretty sure it's not a spurious failure.
cc @Centril who may know more about this.

**Comment by jonas-schievink** [comment]
Maybe https://github.com/rust-lang/rust/issues/63663? For some reason the compiler seems to be built with debug assertions on.

**Comment by mati865** [comment]
Doesn't sccache only affect LLVM and maybe other C/C++ code?

**Comment by lzutao** [comment]
> Doesn't sccache only affect LLVM and maybe other C/C++ code?

I'm not sure.

Closed on waiting for #63663 get fixed.

**Pull request closed without merging**
