### PR TITLE
rustc_serialize: specialize opaque encoding and decoding of some u8 sequences

### PR DESCRIPTION
**Pull request by tgnottingham**
This specializes encoding and decoding of some contiguous u8 sequences to use a more efficient implementation. The default implementations process each u8 individually, but that isn't necessary for the opaque encoder and decoder. The opaque encoding for u8s is a no-op, so we can just copy entire sequences as-is, rather than process them byte by byte.

This also changes some encode and decode implementations for contiguous sequences to forward to the slice and vector implementations, so that they can take advantage of the new specialization when applicable.

### CODE REVIEW

**Comment by bjorn3** [comment]
ctfe-stress-4 shows major improvements. ctfe-stress-4-check even shows an 86% improvement for incr-unchanged. Other than that there are slight (<1%) improvements and no regressions.

**Comment by tgnottingham** [comment]
Rebased and fixed conflict.

By the way, this is kind of a "soft" blocker on #80463 (only for performance reasons).

**Pull request merged**
