### PR TITLE
Fix a couple of FIXMEs in ext::tt::transcribe

### PR DESCRIPTION
**Pull request by mark-i-m**
_Blocked on #60618_

A crater run would be nice to make sure my understanding is correct. A quick google search seems to indicate these are extremely rare errors if they are possible (which I don't believe they are).

r? @petrochenkov 

cc #2887 (there is only one FIXME left and it is hygiene-related)

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot run mode=check-only

**Comment by pietroalbini** [comment]
@craterbot retry

Wut docker died.

**Comment by mark-i-m** [comment]
> Completed jobs:  98346 / 98348

:cry:

**Comment by pietroalbini** [comment]
What is happening with this agent :/

@craterbot retry

**Comment by pietroalbini** [comment]
Whelp that run completly broke (no successful tests...).

@craterbot run mode=check-only assign=agent:aws-2

**Comment by petrochenkov** [comment]
Unless this PR is useful as a testing ground for crater, I'd suggest to just land it and revert with tests if it turns out that the code hitting these ICEs is possible, there's plenty of time to do that (there are also regular beta crater runs).

**Comment by mark-i-m** [comment]
@petrochenkov Sure, it looks like there were no regressions, which is expected. I can rebase the PR and it will be ready to be merged. @pietroalbini do you want me to wait?

**Comment by pietroalbini** [comment]
I haven't had time to investigate this yet, but I don't need this PR to be open to be able to do that (the try builds are already uploaded).

**Comment by mark-i-m** [comment]
@pietroalbini Ok, thanks :) @petrochenkov I rebased.

**Comment by petrochenkov** [comment]
>it looks like there were no regressions

That's because crater is broken.

@bors r+ rollup

**Comment by pietroalbini** [comment]
@mark-i-m @petrochenkov I found the crater bug and I should have a patch deployed in max a few hours. Do you want to r-?

**Comment by mark-i-m** [comment]
@petrochenkov Ah I see. I'm fine with waiting for the crater run if you want... This PR is not super-high priority. These FIXMEs have been around for ~7 years IIUC...

**Comment by pietroalbini** [comment]
@bors r=petrochenkov rollup

This will likely require more time to fully investigate since Cargo changed how its internal locking works, conflicting with Crater wanting to make as much stuff as possible read-only.

**Pull request merged**
