### PR TITLE
Clean code a bit

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by jonathandturner** [comment]
I don't do much in the std lib.  Assigning back to aturon, who might know a good reviewer.

r? @aturon

**Comment by GuillaumeGomez** [comment]
cc @brson @alexcrichton or whoever who can review this PR please. :)

**Comment by GuillaumeGomez** [comment]
@brson: You failed the r+ I think. :p

@bors: r=brson

**Pull request merged**
