### PR TITLE
[DO NOT MERGE] Deny borrows of unaligned fields

### PR DESCRIPTION
**Pull request by matthewjasper**
Just for a crater run (for rust-lang/rfcs#2582)

cc @RalfJung @Centril 
r? @ghost

### CODE REVIEW

**Comment by matthewjasper** [comment]
@rust-lang/infra please can I have a check-only crater run of this PR and (then) #58672 ?

**Comment by pietroalbini** [comment]
@craterbot run start=master#bcfb5e8ac30c46ba512526d66f803756c124c7bb end=try#1f8cc9922f2bbb590be9d43e552423d08a3a96db mode=check-only

**Comment by matthewjasper** [comment]
I've left [a report](https://github.com/rust-lang/rfcs/pull/2582#issuecomment-467629986) in the RFC

**Pull request closed without merging**
