### PR TITLE
Remove EraseRegionsVisitor since mir implements TypeFoldable

### PR DESCRIPTION
**Pull request by spastorino**
r? @nikomatsakis /cc @arielb1

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 57090e42d531b3b48c64ed07f2f900acb55a926b

**Comment by Dylan-DPC** [comment]
ping from triage @spastorino you have conflict to resolve

**Comment by spastorino** [comment]
I guess @Zoxc is right and in that case we should probably close this :). Would leave this up to @Zoxc

**Pull request closed without merging**
