### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by lnicola** [comment]
@bors r+

(why do I need to use `@` in this repo, but not in others?)

**Comment by jonas-schievink** [comment]
> (why do I need to use `@` in this repo, but not in others?)

This repo uses a different bot (https://github.com/rust-lang/homu) than https://bors.tech/, which uses https://github.com/bors-ng/bors-ng

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/homu/issues/140

**Comment by lnicola** [comment]
Yeah, I figured -- it has a different profile image.

**Comment by lnicola** [comment]
Can anyone see what went wrong here?

image

**Comment by ehuss** [comment]
@bors retry

x86_64-apple died after 2 hours with no logs.

**Pull request merged**
