### PR TITLE
Ship the rustdoc book

### LINKED ISSUE #42322: Ship "the rustdoc book"
Located here: https://github.com/rust-lang/rust/tree/master/src/doc/rustdoc/src

This book documents Rustdoc and all its options. To do:

- [x] Write the [doc tests chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/documentation-tests.md)
- [x] Write the [in-source directives chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/in-source-directives.md)
- [ ] Write the [passes chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/passes.md)
- [x] Write the [plugins chapter](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/plugins.md)
- [x] Create an "environment variables" chapter
- [ ] write rustbuild integration to generate the book 
- [ ] link the book from the doc index page

It's no use, Mr. James – it's ~~turtles~~ docs all the way down.

Originally filed as  https://github.com/rust-lang/book/issues/725:

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #42322, as it's the last step.

Blocked on https://github.com/rust-lang/rust/pull/43790, though they will not conflict.

r? @rust-lang/docs

### CODE REVIEW

**Comment by steveklabnik** [comment]
Oh, this is also blocked by a decision that @rust-lang/tools needs to make today about the passes chapter.

**Comment by steveklabnik** [comment]
We decided that we want to remove plugins, not document them, so this is unblocked.

**Comment by QuietMisdreavus** [comment]
Travis failed on linkchecker:

    [01:05:38] rustdoc/command-line-arguments.html:162: broken link - rustdoc/plugins.html
    [01:05:38] rustdoc/command-line-arguments.html:177: broken link - rustdoc/plugins.html
    [01:05:38] rustdoc/print.html:256: broken link - rustdoc/plugins.html
    [01:05:38] rustdoc/print.html:271: broken link - rustdoc/plugins.html
    [01:05:38] thread 'main' panicked at 'found some broken links', /checkout/src/tools/linkchecker/main.rs:49:8

**Review by frewsxcv — APPROVED** [review]
r=me once the other pr lands

**Comment by steveklabnik** [comment]
Ah right; since I removed plugins, those links broke.

I'll remove the flags too.

**Comment by steveklabnik** [comment]
@bors: r=frewsxcv rollup

the other one is in the rollup too now, so let's land them together 😄

**Pull request merged**
