### PR TITLE
download .tar.xz if python3 is used

### LINKED ISSUE #65757: use xz files for stage0 download if on system with xz
I noticed that if `./x.py` is run from a git checkout, the build script downloads the rust-std and rustc, and cargo stage0 archives from static.rust-lang.org in the tar.gz format. Those are a lot bigger in size than the also delivered tar.xz files, usually adds some 30% in download time and consumed bandwith. Do you think you could possibly change the script to use `tar.xz` in the future? 

here's a snipet from my log: 

```
downloading https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz.sha256
running: curl -# -y 30 -Y 10 --connect-timeout 30 --retry 3 -Sf -o /var/tmp/portage/dev-lang/rust-999/temp/tmprecglk92.sha256 https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz.sha256
################################################################################### 100,0%
downloading https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz
running: curl -# -y 30 -Y 10 --connect-timeout 30 --retry 3 -Sf -o /var/tmp/portage/dev-lang/rust-999/temp/tmp_2fjvg1r https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz
################################################################################### 100,0%
verifying /var/tmp/portage/dev-lang/rust-999/temp/tmp_2fjvg1r
```

### PR DESCRIPTION
**Pull request by guanqun**
fixes https://github.com/rust-lang/rust/issues/65757

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Is there something that we should test for in Python to see if xz decompression is supported? Is it possible to configure that off in python 3? Are we sure that all Python 3 versions support this?

**Comment by guanqun** [comment]
Good catch, I added an extra check for the version, according to the python documentation here: https://docs.python.org/3/library/tarfile.html

```
Changed in version 3.3: Added support for lzma compression.
```

If we trust this info, checking the version is enough, we don't have to try to import lzma.

**Comment by lzutao** [comment]
Maybe:
```python
tarball_suffix = '.tar.xz'
try:
    import lzma
except ImportError:
    tarball_suffix = '.tar.gz'
```

**Comment by guanqun** [comment]
updated to import check, please help review again. 

btw how can we update the azure pipelines to do a full verification?

**Comment by guanqun** [comment]
According to the `tarfile`'s implementation from python, it internally uses `lzma`, see the source code here: https://github.com/python/cpython/blob/master/Lib/tarfile.py#L387-L397

but in python2, even we have `lzma`, I doubt it can work with `tarfile` out of box.

So that's why I originally think it's better to do the version check, it's simple and can also work. Even if it might be a more conservative estimate.

**Comment by alexcrichton** [comment]
That's what I'm sort of getting at with maybe not doing this at all because it doesn't save all that much and it's pretty complicated. The `import lzma` trick won't work because if the `lzma` package is defined it doesn't imply the `tarfile` package uses it. The version check won't work because it doesn't imply that `lzma` support is compiled in. The least common denominator is gz-compressed tarballs.

Perhaps a configuration option could be used to opt-in to this? Or something like that?

**Comment by alex** [comment]
I think if you change `return True` after `import lzma` to `return sys.version_info[0] >= 3` then this is correct under all practical circumstances.

**Comment by guanqun** [comment]
@alex we can do that, but I'd argue the logic is a bit unclear at first glance, just checking the python version is >= 3.3 is much clear and will work for sure, since `lzma` is part of the standard library of Python after that version.

**Comment by alexcrichton** [comment]
Presumably though lzma support can be disabled when python is compiled right? Sorry but this is where it all just seems like this is perhaps a bit too much effort with respect to the change proposed here?

**Comment by alex** [comment]
It's technically possible, yes.

I'm practice compiling with lzma disabled is _incredibly_ rare.

**Comment by JohnCSimon** [comment]
Ping from triage - this PR has sat idle for the last few days...
@alex  @alexcrichton @guanqun 
Can you post what else needs to happen with this PR?

Thanks!

**Comment by guanqun** [comment]
I come up with a slightly better idea. We can try to create a `.tar.xz` file, if it can succeed, then on the other hand, the decompression should be fine. With this approach, we can bypass the version check or the import check.

Code is pushed, but I need to test that with Python3, will report back.

**Comment by guanqun** [comment]
Tried python2 and python3, they both can figure out the right file types. These are pre-built version, not custom built, I believe it would cover most of the use cases.

**Comment by alexcrichton** [comment]
@bors: r-

er actually, let's keep this out of the hot path. This shouldn't be calculated every time `./x.py build` is run.

**Comment by guanqun** [comment]
thank you for the review. I've moved the check to the downloading function. locally it's fine for python 3. let's see if the CI job works. it's using python 2.

**Pull request merged**
