### PR TITLE
Remove warning of duplicated error code

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @Manishearth

### CODE REVIEW

**Comment by bstrie** [comment]
@GuillaumeGomez can you be more specific about what this does, for posterity? Is there an open issue for the correction here?

**Comment by GuillaumeGomez** [comment]
It just remove the warning that the E0015 error code appears more than one in the code:

```
diagnostic code E0015 already used
```

**Comment by ebfull** [comment]
I think the function should be closer in scope to the actual place it's used, since it's very specific for this situation and shouldn't be used elsewhere. Once const functions stabilize we can refactor it out.

On that note, it might be interesting to add a `:reuse` flag of some kind to the `span_err!` macro for this situation in the future, though it might not buy us much.

**Comment by Manishearth** [comment]
The more idiomatic thing to do here is to use a single `span_err` call, and use an `if` to decide what string to pass it (`let foo = if ...{format!(...)} else {format!(...)}; span_err(code, str)`)

**Comment by GuillaumeGomez** [comment]
You're hard on business haha ! I moved the function to a more little scope as proposed.

**Comment by arielb1** [comment]
@GuillaumeGomez 

Squash and use better names for the parameters (e.g. pass `tcx` instead of `sess`)

**Comment by GuillaumeGomez** [comment]
@arielb1: Done !

**Comment by arielb1** [comment]
@bors r-

Sorry, `tcx: &Session` just doesn't cut it.

**Comment by GuillaumeGomez** [comment]
Updated !

**Pull request merged**
