### PR TITLE
Update Clippy

### LINKED ISSUE #66409: `clippy-driver` no longer builds after rust-lang/rust#66233
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#66233, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @cjgillot, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @oli-obk, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #66409

r? @Manishearth

### CODE REVIEW

**Comment by JohnTitor** [comment]
@Manishearth bors-servo isn't here, bors' here instead :)

**Comment by Manishearth** [comment]
Yeah, I realized. But both actually work in this case, the -servo just gets
ignored

**Pull request merged**
