### PR TITLE
rustc(codegen): uncache `def_symbol_name` prefix from `symbol_name`.

### PR DESCRIPTION
**Pull request by eddyb**
The `def_symbol_name` query was an optimization to avoid recomputing the common part of a symbol name, as only the hash needs to be added to it for each symbol.

However, #57967 will add a new mangling scheme, which doesn't readily support this kind of reuse - while it's plausible, it requires a lot more effort, since you'd have to "symbolically evaluate" mangling, and keep it in a form where the backreference positions can be computed correctly in the final step.

So I want to see how much time we're actually saving with this `def_symbol_name` optimization, nowadays.

cc @michaelwoerister

### CODE REVIEW

**Comment by eddyb** [comment]
@rust-timer build 7172250e104720198a66744d2121b7151cef4723

**Comment by oli-obk** [comment]
Perf is randomly better or worse, but all below 1%. Max-rss seems to mostly have improvements, but that might just be noise, I don't know what the usual variances are.

impl lgtm

**Comment by michaelwoerister** [comment]
Looks good to me, thanks for the PR, @eddyb!

@bors r+

**Pull request merged**
