### PR TITLE
force `i1` booleans to `i8` when comparing

### PR DESCRIPTION
**Pull request by nikomatsakis**
Work around LLVM bug.

cc #36856

r? @eddyb

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: p=1

(fixing a regression)

**Comment by brson** [comment]
Nominated for backport. Regression fix (though it's been on stable a long time).

**Comment by nikomatsakis** [comment]
Backport seems fine to me. This is a really simple patch.

**Comment by nikomatsakis** [comment]
Accepting for beta because small patch, regression.

cc @rust-lang/compiler

**Comment by stouset** [comment]
Out of curiosity, is there a plan to revert this workaround once the upstream bug is fixed?

**Comment by nikomatsakis** [comment]
@stouset good question. I have no such plan. It probably makes sense to do, but I don't know an easy way to make sure we don't forget. =) I guess filing a P-medium issue might help or something.

**Pull request merged**
