### PR TITLE
std: Remove `iter::ByRef` and generalize impls

### PR DESCRIPTION
**Pull request by alexcrichton**
This removes the `ByRef` iterator adaptor to stay in line with the changes to
`std::io`. The `by_ref` method instead just returns `&mut Self`.

This also removes the implementation of `Iterator for &mut Iterator` and instead
generalizes it to `Iterator for &mut I` where `I: Iterator + ?Sized`. The
`Box<I>` implementations were also updated.

### CODE REVIEW

**Comment by reem** [comment]
Should be marked a breaking change, since ByRef was stable.

**Comment by aturon** [comment]
@reem, good point. r=me with a commit message update.

**Comment by alexcrichton** [comment]
Gah thanks for the reminder @reem!

@bors r=aturon d30f225

**Pull request merged**
