### PR TITLE
Shrink `ObligationCauseCode`

### PR DESCRIPTION
**Pull request by nnethercote**
These commits reduce the size of `ObligationCauseCode` from 56 bytes to 32 bytes on 64-bit. This reduces instruction counts on various benchmarks by up to 1%, due to less `memcpy`ing.

### CODE REVIEW

**Comment by nnethercote** [comment]
@rust-timer build afbe8d987c61ec4a326e6d612f8d18733e0dea33

**Comment by nnethercote** [comment]
BTW, I tried taking things a step further, by boxing the `BuiltinDerivedObligation` and `ImplDerivedObligation` variants of `ObligationCauseCode`. This shrank `ObligationCauseCode` from 32 bytes to 24 bytes, but ended up slowing things down because the `memcpy` improvements were outweighed by the cost of the additional allocations.

Also, these results are good, but I might wait a bit before landing. AFAICT, this change causes LLVM to use direct code for `PredicateObligation` copies instead of `memcpy`. (The commits reduce the size of that type from 136 bytes to 112 bytes... maybe >128 bytes is the threshold for LLVM using `memcpy`?) And in doing so, it hides all the remaining `PredicateObligation` copies from my new profiling tool, which only looks at `memcpy` calls!

**Comment by mati865** [comment]
Indeed 128 is the threshold for using libc instead of `memcpy`: https://github.com/llvm/llvm-project/blob/127240acf1001b72c0c52863ffe3dc39b7c5fd6d/llvm/lib/Target/X86/X86Subtarget.h#L437

**Review by m-komilov — COMMENTED** [review]
good job

**Pull request merged**
