### PR TITLE
Add a method to the mpsc::Receiver for producing a non-blocking iterator

### PR DESCRIPTION
**Pull request by mitchmindtree**
Currently, the `mpsc::Receiver` offers methods for receiving values in both blocking (`recv`) and non-blocking (`try_recv`) flavours. However only blocking iteration over values is supported. This PR adds a non-blocking iterator to complement the `try_recv` method, just as the blocking iterator complements the `recv` method.
## Use-case

I predominantly use rust in my work on real-time systems and in particular real-time audio generation/processing. I use `mpsc::channel`s to communicate between threads in a purely non-blocking manner. I.e. I might send messages from the GUI thread to the audio thread to update the state of the dsp-graph, or from the audio thread to the GUI thread to display the RMS of each node. These are just a couple examples (I'm probably using 30+ channels across my various projects). I almost exclusively use the `mpsc::Receiver::try_recv` method to avoid blocking any of the real-time threads and causing unwanted glitching/stuttering. Now that I mention it, I can't think of a single time that I personally have used the `recv` method (though I can of course see why it would be useful, and perhaps the common case for many people).

As a result of this experience, I can't help but feel there is a large hole in the `Receiver` API.

| blocking | non-blocking |
| --- | --- |
| `recv` | `try_recv` |
| `iter` | 🙀 |

For the most part, I've been working around this using `while let Ok(v) = r.try_recv() { ... }`, however as nice as this is, it is clearly no match for the Iterator API.

As an example, in the majority of my channel use cases I only want to check for _n_ number of messages before breaking from the loop so that I don't miss the audio IO callback or hog the GUI thread for too long when an unexpectedly large number of messages are sent. Currently, I have to write something like this:

``` rust
let mut take = 100;
while let Ok(msg) = rx.try_recv() {
    // Do stuff with msg
    if take == 0 {
        break;
    }
    take -= 1;
}
```

or wrap the `try_recv` call in a `Range<usize>`/`FilterMap` iterator combo.

On the other hand, this PR would allow for the following:

``` rust
for msg in rx.try_iter().take(100) {
    // Do stuff with msg
}
```

I imagine this might also be useful to game devs, embedded or anyone doing message passing across real-time threads.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I was pretty skeptical at first glance but I think your description has won me over. My only heistation is the fact that we're hiding whether iteration was terminated due to "would block" or "disconnected", but perhaps that's not so bad in the long run? If a channel is disconnected then any attempt to receive on it again will again receive a disconnection

cc @rust-lang/libs

**Comment by mitchmindtree** [comment]
@alexcrichton thanks for taking look!

> My only heistation is the fact that we're hiding whether iteration was terminated due to "would block" or "disconnected, but perhaps that's not so bad in the long run?"

I attempted to make sure that this behaviour is clear in the new iterator's docs, but perhaps I could also add a note that recommends using `try_recv`, a `loop` and a `match` expr (with an example?) in the case that the user wishes to loop while distinguishing between reasons for termination?

**Comment by alexcrichton** [comment]
@mitchmindtree ah yeah the docs are definitely quite clear in this regard, I was just hoping we could surface it at the API level as well (but I'm not sure that's possible here)

**Comment by brson** [comment]
Thanks for the good writeup. Looks fine to me.

**Comment by aturon** [comment]
I'm happy to land this API on an unstable basis.

**Comment by alexcrichton** [comment]
Discussed during libs triage the decision was to merge, thanks again for the PR @mitchmindtree!

@bors: r+

**Comment by mitchmindtree** [comment]
Ahh, it seems I'm missing the `issue` field for the `unstable` decorators. Would you like me to create a tracking issue for this? Or would you prefer it if I just use the issue number of this PR?

**Comment by alexcrichton** [comment]
Ah yeah that'd do it, if you want to open an issue I'll be sure to tag it appropriately and you can update this PR to reference it.

**Comment by alexcrichton** [comment]
@bors: r+ aed2e5c1e5d1774fba671ba60ee6347a1d524f2e

Thanks!

**Comment by alexcrichton** [comment]
Looks like a failure perhaps in the tests?

**Comment by mitchmindtree** [comment]
Ahh sorry about that @alexcrichton, I just made the fix and successfully ran the tests locally - should be good to go now!

**Comment by alexcrichton** [comment]
@bors: r+ 

No worries!

**Comment by alexcrichton** [comment]
@bors: retry

sorry for the number of retries...

**Pull request merged**
