### PR TITLE
impl SliceIndex<str> for (Bound<usize>, Bound<usize>)

### PR DESCRIPTION
**Pull request by mattfbacon**
This impl is conspicuously missing.

### CODE REVIEW

**Comment by mattfbacon** [comment]
I noticed that there are similar functions for converting `Bound` pairs to `Range`s in core::slice::index. What would be a good approach to share them with the string module?

**Comment by Mark-Simulacrum** [comment]
Marking as waiting on team as this will need T-libs-api FCP.

**Comment by Amanieu** [comment]
Since we already have these on slices, it makes sense to have them on `str` as well.

@rfcbot fcp merge

**Comment by mattfbacon** [comment]
> > I noticed that there are similar functions for converting `Bound` pairs to `Range`s in core::slice::index. What would be a good approach to share them with the string module? Maybe move all of the SliceIndex impls to their own module?
> 
> Yes, please re-use the `to_range` function from `core::slice::index`. You can make it `pub(crate)` for this purpose.

Done. I also had to make `core::slice::index` `pub(crate)`.

**Comment by mattfbacon** [comment]
Hmm, maybe #71146 should also be extended to `str`.

**Comment by Amanieu** [comment]
Yes, I agree that extending #71146 for `*const str` makes sense. This should be done in a separate PR.

**Comment by mattfbacon** [comment]
Do you mean that I should create a PR for that method, then wait for it to merge, then return to this one?

**Comment by workingjubilee** [comment]
> Do you mean that I should create a PR for that method, then wait for it to merge, then return to this one?

Or we can merge this one with whatever internal implementation works now, and you can do another PR fixing it up with the nightly API you want that extends `slice_ptr_len`. Either way! The order isn't important, but this one won't land until you rebase it.

**Comment by workingjubilee** [comment]
Excellent, thank you!

@bors r+

**Pull request merged**
