### PR TITLE
Update RLS

### PR DESCRIPTION
**Pull request by nrc**
Should fix RLS toolstate

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+

I've rebased it myself.

**Comment by RalfJung** [comment]
> `in `abort_upload': multipart upload failed: execution expired (Aws::S3::MultipartUploadError)`

Looks spurious to me.

@bors retry

**Comment by kennytm** [comment]
@bors retry treeclosed=10

We've contacted Travis support about these network failures started 19 hours ago. Closing the tree until we've got reply.

**Comment by nrc** [comment]
Looks like network issues again. :-( I guess I should just wait for the rollup.

**Pull request merged**
