### PR TITLE
Add community translations.

### PR DESCRIPTION
**Pull request by steveklabnik**
/cc @kgv, @rust-kr, @KaiserY, @mkpankov

### CODE REVIEW

**Comment by mkpankov** [comment]
Wow, supercool! Thanks. 

By the way, would be possible to announce #rust-ru channel somewhere?

**Comment by steveklabnik** [comment]
@mkpankov yeah, having it here would be good. It's on mozilla's IRC?

**Comment by ithamsteri** [comment]
@steveklabnik Yes. This channel on Mozilla's IRC.

**Comment by mkpankov** [comment]
@steveklabnik  Ok, just to confirm: the channel is at Mozilla's server [here](http://client00.chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-ru)

**Comment by steveklabnik** [comment]
I realized there are actually several language-specific channels, so we should add them in a new section, but I'll do that in a different PR

r? @brson

**Comment by sinistersnare** [comment]
I think there should be an added disclaimer that these are not maintained by Rust developers, and that they may be out of date.

**Comment by steveklabnik** [comment]
@sinistersnare Does "Community" not communicate that effectively enough?

**Comment by goyox86** [comment]
Hi guys @kgv, @rust-kr, @KaiserY, @mkpankov I want to start translating to Spanish do you have any advice on the process to setup the env for translating?

**Comment by sinistersnare** [comment]
@steveklabnik, no, I do not think that it is enough.

**Comment by KaiserY** [comment]
@goyox86 https://github.com/rust-lang/rust/tree/master/src/doc/trpl is all you need, just make them Spanish:)

**Comment by brson** [comment]
r=me but seems like some comments may not be completely addressed yet

**Comment by steveklabnik** [comment]
My thoughts is that by putting a huge disclaimer, we risk minimizing the hard work everyone is doing to translate the book. I think just saying "community" is enough to communicate the situation without being overly negative.

**Comment by steveklabnik** [comment]
I am also going to add the non-english channels to the IRC list, but I need to figure out how to query for all rust related channels on moznet, and that's fine as a separate PR

**Comment by goyox86** [comment]
Hey guys Spanish translation started here :) 

http://goyox86.gitbooks.io/el-libro-de-rust/content/ :smile:

**Comment by steveklabnik** [comment]
@goyox86 thanks, snuck it in :)

**Comment by goyox86** [comment]
@steveklabnik Correction: this is the github repo of the book: https://github.com/goyox86/elpr :smile:

**Comment by mkpankov** [comment]
Oh, I feel stupid for not bringing these issues up earlier.

Still, is this file reflected on the web somewhere? I feel it might be hard to actually discover these links.

Also, isn't it better to insert them directly to TRPL introduction for example, as AFAIK all of these translations are translations of just TRPL, not the entirety of the documentation.

**Comment by steveklabnik** [comment]
@mkpankov it will be on http://doc.rust-lang.org/ tomorrow

**Pull request merged**
