### PR TITLE
Remove QueryResult

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Looks good!
@bors r+

**Comment by Mark-Simulacrum** [comment]
@Zoxc Is there a chance some commentary can be added or a link to a discussion posted? This appears to change behavior unless I'm misunderstanding when a query panics; is that intentional and fine?

**Comment by Zoxc** [comment]
@bors r-

I think not having this could result error messages being duplicating due to queries possibly executing twice with parallel queries. I think we'll have to wait until we no longer return using panics to do this.

**Comment by Zoxc** [comment]
For example: We have two queries running in parallel, `A` and `B`. `A` emits an error message then exits early using a panic. We'll have to wait for `B` to complete before continuing unwinding, but `B` could itself call `A` which would cause the error message to be emitted again before `B` also will be unwound.

**Pull request closed without merging**
