### PR TITLE
[xsave] whitelist xsave target feature

### PR DESCRIPTION
**Pull request by gnzlbg**
Required for https://github.com/rust-lang-nursery/stdsimd/issues/171

### CODE REVIEW

**Comment by gnzlbg** [comment]
What happened here?

**Comment by kennytm** [comment]
@gnzlbg Nothing happened here 😄

**Comment by gnzlbg** [comment]
@kennytm ?

The travis status is:

```shell
Worker information
hostname: 3145c91c-8ae7-4a85-9f77-dc541c238e75@3701.wjb-2
version: v3.3.1 https://github.com/travis-ci/worker/tree/1153e5010ef9863bf96264b75fba506109633460
instance: 64270063-efdf-411d-85c9-baa53c7d9455 travis-ci-osx10.11-xcode7.3-1480691248 (via amqp)
startup: 2m1.415893162s
Download from https://build.travis-ci.org/filter/redirect_io.rb failed. Trying https://build.travis-ci.com/filter/redirect_io.rb ...
ruby: No such file or directory -- /Users/travis/filter.rb (LoadError)
```

**Comment by kennytm** [comment]
@gnzlbg Travis madness. Ignore it, we'll issue a retry when the CI gets back to normal shape.

**Pull request merged**
