### PR TITLE
Remove emoji from docs

### PR DESCRIPTION
**Pull request by mitaa**
None of my devices/browsers renders this correctly.

r? @steveklabnik

### CODE REVIEW

**Comment by nagisa** [comment]
I do not think lack of fonts on anybody’s device is a justification good enough for removing/not-using features.

On the other hand, emoji do not really belong in formal technical documentation.

**Comment by retep998** [comment]
Considering this emoji is part of unicode 8 which was released only recently, that means a significant amount of devices don't support it. Even Firefox on Windows 10 doesn't support it. Having glyphs in the documentation which most devices are incapable of rendering is a poor idea.

**Comment by steveklabnik** [comment]
I guess since this is a newer one, as @retep998 says, we can take it out. For now.

@bors: r+ rollup

**Comment by nagisa** [comment]
Seems like @bors missed the r+, ping @steveklabnik

**Pull request merged**
