### PR TITLE
Make accesses to fields of packed structs unsafe

### PR DESCRIPTION
**Pull request by arielb1**
To handle packed structs with destructors (which you'll think are a rare
case, but the `#[repr(packed)] struct Packed<T>(T);` pattern is
ever-popular, which requires handling packed structs with destructors to
avoid monomorphization-time errors), drops of subfields of packed
structs should drop a local move of the field instead of the original
one.

That's it, I think I'll use a strategy suggested by @Zoxc, where this mir
```
drop(packed_struct.field)
```

is replaced by
```
tmp0 = packed_struct.field;
drop tmp0
```

cc #27060 - this should deal with that issue after codegen of drop glue
is updated.

The new errors need to be changed to future-compatibility warnings, but
I'll rather do a crater run first with them as errors to assess the
impact.

cc @eddyb

Things which still need to be done for this:
 - [ ] - handle `repr(packed)` structs in `derive` the same way I did in `Span`, and use derive there again
 - [ ] - implement the "fix packed drops" pass and call it in both the MIR shim and validated MIR pipelines
 - [ ] - do a crater run
 - [ ] - convert the errors to compatibility warnings

### CODE REVIEW

**Comment by eddyb** [comment]
LGTM. cc @rust-lang/compiler

**Comment by kennytm** [comment]
CI failure is due to `tendril`. 

The relevant `#[repr(packed)]` has been removed in servo/tendril@f9c672f4e559d00ff5449c5658cbf611479ec840. The latest version of `tendril` is 0.4.0, but we are currently using 0.3.1. #44785 does **not** include this update. We need to get [`kuchiki`](https://github.com/kuchiki-rs/kuchiki) to update its dependencies.

Dependency tree:

* `tendril` 0.3.1 (current: 0.4.0)
    * `markup5ever` 0.3.2 (current: 0.5.0)
        * `html5ever` 0.18.0 (current: 0.20.0)
            * **`kuchiki` 0.5.1 (already latest)**
                * `html-diff` 0.0.4 (already latest)
                    * `rustdoc` 0.0.0

<details>

```
[00:34:19] error[E0133]: borrow of packed field requires unsafe function or block
[00:34:19]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.3.1/src/tendril.rs:486:26
[00:34:19]     |
[00:34:19] 486 |         let kind = match self.ptr.get().get() {
[00:34:19]     |                          ^^^^^^^^ borrow of packed field
[00:34:19] 
[00:34:19] error[E0133]: borrow of packed field requires unsafe function or block
[00:34:19]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.3.1/src/tendril.rs:562:15
[00:34:19]     |
[00:34:19] 562 |         match self.ptr.get().get() {
[00:34:19]     |               ^^^^^^^^ borrow of packed field
[00:34:19] 
[00:34:19] error[E0133]: borrow of packed field requires unsafe function or block
[00:34:19]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.3.1/src/tendril.rs:572:17
[00:34:19]     |
[00:34:19] 572 |         let n = self.ptr.get().get();
[00:34:19]     |                 ^^^^^^^^ borrow of packed field
[00:34:19] 
[00:34:19] error[E0133]: borrow of packed field requires unsafe function or block
[00:34:19]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.3.1/src/tendril.rs:580:17
[00:34:19]     |
[00:34:19] 580 |         let n = self.ptr.get().get();
[00:34:19]     |                 ^^^^^^^^ borrow of packed field
[00:34:19] 
[00:34:19] error[E0133]: borrow of packed field requires unsafe function or block
[00:34:19]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.3.1/src/tendril.rs:582:39
[00:34:19]     |
[00:34:19] 582 |         (n > MAX_INLINE_TAG) && (n == other.ptr.get().get())
[00:34:19]     |                                       ^^^^^^^^^ borrow of packed field
[00:34:19] 
[00:34:19] error[E0133]: borrow of packed field requires unsafe function or block
[00:34:19]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.3.1/src/tendril.rs:588:12
[00:34:19]     |
[00:34:19] 588 |         if self.ptr.get().get() <= MAX_INLINE_TAG {
[00:34:19]     |            ^^^^^^^^ borrow of packed field
[00:34:19] 
[00:34:19] error[E0133]: borrow of packed field requires unsafe function or block
[00:34:19]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/tendril-0.3.1/src/tendril.rs:589:13
[00:34:19]     |
[00:34:19] 589 |             self.ptr.set(unsafe { NonZeroUsize::new(EMPTY_TAG) });
[00:34:19]     |             ^^^^^^^^ borrow of packed field
[00:34:19] 
[00:34:19] error: aborting due to 7 previous errors
```

</details>

**Comment by pnkfelix** [comment]
@arielb1 do you know if the now merged update to kuchiki mean we should re-do a travis run on this?

**Comment by arielb1** [comment]
Code is green. Can we have a crater run to see whether we break the world before I go make this a future-compat warning?

**Comment by Mark-Simulacrum** [comment]
Cargobomb run started.

**Comment by carols10cents** [comment]
@Mark-Simulacrum has the cargobomb run completed on this?

**Comment by Mark-Simulacrum** [comment]
Cargobomb complete: http://cargobomb-reports.s3.amazonaws.com/pr-44884/index.html

**Comment by arielb1** [comment]
This appears to be quite a problem, we have 31 root regressions.

Summary:
basic_dsp_vector 0.5.2 - derive
cgmath 0.15.0 - derive
simd 0.2.0 - derive
tendril 0.2.4 - borrow, fixed
btrfs 1.2.2 - borrow, not on github
gjio 0.1.3 - borrow, deprecated
carp 0.1.0 - derive, no dependent crates, dead?
rust-extra 0.0.17 - borrow, badly unsound
elfloader 0.0.4 - borrow, needs {}
vek 0.1.0 - derive, needs copy
libpijul 0.8.2 - derive, need copy?
lm4f120 0.2.0 - borrow, needs to not be packed?
multiboot 0.3.0 - derive, needs more Copy?
multiboot2 0.3.2 - derive, no repo, needs more Copy?
orbclient 0.3.12 - borrow, needs {}
p0f_api 0.1.1 - borrow, needs {}
pe 0.1.1 - borrow, needs {} I think
pelite 0.4.0 - borrow, needs {}
persistent_hashmap 0.3.0 - derive, not sure how to fix
btrfs2 1.2.2 - borrow, not on github
rpcap 0.3.0 - borrow, needs to switch to Packed fields?
rux 0.1.0 - borrow, needs {}
sgx-isa 0.1.2 - borrow, needs to use by-value
simd-alt 0.2.0 - derive, like simd
tantivy 0.4.3 - borrow, needs extra packed annotations on datastructs
td_revent - borrow, needs {}
vec-2-10-10-10 - borrow, unsound public API
x86_64 0.1.2 - EntryOptions also needs to be packed because the compiler is stupid
zfs 0.1.0 - borrow, needs {}
lout (https://github.com/rrichardson/lout) - borrow, needs {}

**Comment by arielb1** [comment]
There are a few common types of regressions:

One easily-fixed case is `println!("{}", packed.field);`, which needs to be changed to `println!("{}", {packed.field});` to avoid creating a direct reference to a packed field.

The other annoying one is `derive` on a non-Copy packed struct. The worst one is this from https://github.com/JoNil/persistent_hashmap/blob/master/src/lib.rs:
```Rust
#[derive(Clone, Copy, Default)]
#[repr(C, packed)]
struct HashmapEntry<V> {
    // 1 bit occupied and 63 bit hash
    state: u64,
    value: V,
}
```

The Debug & Clone impls are currently UB, and I don't see a good way of fixing them.

**Comment by arielb1** [comment]
I think the `derive` wrapper needs to be changed to add an attribute that *warns* if there's a non-Copy field, to avoid breaking half the world.

**Comment by alexcrichton** [comment]
ping @arielb1 I've tagged this as waiting on review, but please feel free to change it if that's not right!

**Comment by shepmaster** [comment]
Howdy @arielb1 — it's been over 14 days since we last heard from you here, so I'm going to go ahead and close this PR to keep things tidy. Please feel free to reopen when you have some cycles to address the conflicts!

**Comment by shepmaster** [comment]
Howdy @arielb1 — it's been over 21 days since we last heard from you here, so I'm going to go ahead and close this PR to keep things tidy. Please feel free to reopen when you have some cycles to address the conflicts!

**Comment by arielb1** [comment]
status: I need to remember how we decided to handle borrowck conflicts.

**Comment by arielb1** [comment]
This has been modified to only issue warnings

r? @eddyb

**Comment by eddyb** [comment]
LGTM, r=me after #45225 gets merged.

**Comment by eddyb** [comment]
LGTM, r? @nikomatsakis

**Comment by arielb1** [comment]
fixed mir-opt test failure

**Review by nikomatsakis — APPROVED** [review]
Looks great.

**Comment by kennytm** [comment]
Failed on NetBSD 😂 

```
[00:45:43]    Compiling alloc_system v0.0.0 (file:///checkout/src/liballoc_system)
[00:45:49] error: borrow of packed field requires unsafe function or block (error E0133)
[00:45:49]    --> /checkout/src/libstd/net/ip.rs:722:9
[00:45:49]     |
[00:45:49] 722 |         self.inner.s_addr.hash(s)
[00:45:49]     |         ^^^^^^^^^^^^^^^^^
[00:45:49]     |
[00:45:49] note: lint level defined here
[00:45:49]    --> /checkout/src/libstd/lib.rs:232:9
[00:45:49]     |
[00:45:49] 232 | #![deny(warnings)]
[00:45:49]     |         ^^^^^^^^
[00:45:49]     = note: #[deny(safe_packed_borrows)] implied by #[deny(warnings)]
[00:45:49]     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
[00:45:49]     = note: for more information, see issue #46043 <https://github.com/rust-lang/rust/issues/46043>
[00:45:49] 
[00:45:51] error: aborting due to previous error
[00:45:51] 
[00:45:51] error: Could not compile `std`.
```

`self` is an `Ipv4Addr` defined as

```rust
#[derive(Copy)]
#[stable(feature = "rust1", since = "1.0.0")]
pub struct Ipv4Addr {
    inner: c::in_addr,
}
```

`in_addr` is defined as

```rust
    #[cfg_attr(target_os = "netbsd", repr(packed))]
    pub struct in_addr {
        pub s_addr: in_addr_t,
    }
```

where `type in_addr_t = u32;`.

**Comment by kennytm** [comment]
`x86_64-gnu-aux`, rustfmt `checkstyle_test` is broken? It seems the error is due to a missing new line at EOF? What is going on??? @nrc 

```
[01:25:31] failures:
[01:25:31] 
[01:25:31] ---- checkstyle_test stdout ----
[01:25:31] 	
[01:25:31] Mismatch at tests/writemode/source/fn-single-line.rs:1:
[01:25:31]  <?xml version="1.0" encoding="utf-8"?>⏎
[01:25:31]  <checkstyle version="4.3"><file name="tests/writemode/source/fn-single-line.rs"><error line="2" severity="warning" message="Should be `fn foo_expr() { 1 }`" /><error line="2" severity="warning" message="Should be `fn foo_stmt() { foo(); }`" /><error line="2" severity="warning" message="Should be `fn foo_decl_local() { let z = 5; }`" /><error line="2" severity="warning" message="Should be `fn foo_decl_item(x: &amp;mut i32) { x = 3; }`" /><error line="2" severity="warning" message="Should be `fn empty() {}`" /><error line="2" severity="warning" message="Should be `fn foo_return() -&gt; String { &quot;yay&quot; }`" /><error line="2" severity="warning" message="Should be `fn foo_where() -&gt; T`" /><error line="2" severity="warning" message="Should be `where`" /><error line="2" severity="warning" message="Should be `    T: Sync,`" /><error line="2" severity="warning" message="Should be `{`" /><error line="52" severity="warning" message="Should be `fn lots_of_space() { 1 }`" /><error line="59" severity="warning" message="Should be `    fn dummy(&amp;self) {}`" /><error line="59" severity="warning" message="Should be `trait CoolerTypes {`" /><error line="59" severity="warning" message="Should be `    fn dummy(&amp;self) {}`" /><error line="59" severity="warning" message="Should be `fn Foo&lt;T&gt;()`" /><error line="59" severity="warning" message="Should be `where`" /><error line="59" severity="warning" message="Should be `    T: Bar,`" /><error line="59" severity="warning" message="Should be `{`" /></file></checkstyle>⏎
[01:25:31] -⏎
[01:25:31] thread 'checkstyle_test' panicked at 'Text does not match expected output', /checkout/src/tools/rustfmt/tests/system.rs:97:8
[01:25:31] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:25:31] 
[01:25:31] 
[01:25:31] failures:
[01:25:31]     checkstyle_test
[01:25:31] 
[01:25:31] test result: FAILED. 9 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:25:31] 
[01:25:31] error: test failed, to rerun pass '--test system'
```

@bors retry — error doesn't look relevant.

**Comment by kennytm** [comment]
Same error ¯\\\_(ツ)_/¯

**Comment by arielb1** [comment]
@kennytm 

This might have been caused by me updating Cargo.lock. cc @nrc

**Comment by arielb1** [comment]
umm so you actually need rustfmt=Compiling for it to work. I hope.

@bors r=nikomatsakis

**Comment by kennytm** [comment]
@bors r- 

CI failed, we now need to mark errors with `//~ ERROR` in UI tests as well.

```
[00:46:50] ---- [ui] ui/deriving-with-repr-packed.rs stdout ----
[00:46:50] 	
[00:46:50] error: /checkout/src/test/ui/deriving-with-repr-packed.rs:16: unexpected error: '16:19: 16:21: #[derive] can't be used on a #[repr(packed)] struct with type parameters (error E0133) [safe_packed_borrows]'
[00:46:50] 
[00:46:50] error: /checkout/src/test/ui/deriving-with-repr-packed.rs:16: unexpected warning: '16:19: 16:21: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!'
[00:46:50] 
[00:46:50] error: /checkout/src/test/ui/deriving-with-repr-packed.rs:16: unexpected error: '16:19: 16:21: #[derive] can't be used on a #[repr(packed)] struct with type parameters (error E0133) [safe_packed_borrows]'
[00:46:50] 
[00:46:50] error: /checkout/src/test/ui/deriving-with-repr-packed.rs:16: unexpected warning: '16:19: 16:21: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!'
[00:46:50] 
[00:46:50] error: /checkout/src/test/ui/deriving-with-repr-packed.rs:20: unexpected error: '20:16: 20:20: #[derive] can't be used on a non-Copy #[repr(packed)] struct (error E0133) [safe_packed_borrows]'
[00:46:50] 
[00:46:50] error: /checkout/src/test/ui/deriving-with-repr-packed.rs:20: unexpected warning: '20:16: 20:20: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!'
[00:46:50] 
[00:46:50] error: 6 unexpected errors found, 0 expected errors not found
```

**Comment by arielb1** [comment]
travis failed

@bors r- retry

**Comment by arielb1** [comment]
Looks like errors are duplicated in the compile-fail test between the `eq` and `ne` methods. I think I'll move the error reporting to `syntax_ext` and have it put an `#[allow(safe_packed_borrows)]` attribute.

**Comment by nrc** [comment]
Rustfmt is fixed by https://github.com/rust-lang/rust/pull/46144, I was waiting for this to land, but it looks like it is taking longer than expected. Since 46144 is ready to go and fixes the RLS which is currently broken, I want to land it sooner rather than later. Assuming it lands first (which it should) could you remove the 'mark rustfmt as broken' commit here since it shouldn't be needed.

**Pull request merged**
