### PR TITLE
Update normalize.css to 8.0.1

### PR DESCRIPTION
**Pull request by jsha**
From From https://github.com/necolas/normalize.css/releases/tag/8.0.1.

The old version was 3.0.0, from 2014. The new version is from 2018.

I noticed when looking at frontend performance for rustdoc that this file was out of date. The URL in the 3.0.0 license header now resolves to an incorrect destination. And generally it seems good to be up-to-date.

Before-and-after images, plus diff, under details. TL;DR: Nothing changes except a slight adjustment to line height.

<details>

with-normalize-8 0 1

with-normalize-3 0 0

diff

</details>

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm curious about one thing: why is the sidebar not taking the full height of the page?

**Comment by bugadani** [comment]
> I'm curious about one thing: why is the sidebar not taking the full height of the page?

I'd guess it's an artifact of the particular scrolling screenshot method used?

**Comment by jsha** [comment]
> > I'm curious about one thing: why is the sidebar not taking the full height of the page?
> I'd guess it's an artifact of the particular scrolling screenshot method used?

Yes, I think it is. This was from Firefox's DevTool's screenshot tool.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Tested and I couldn't see any issues so let's give it a try! But before: cc @rust-lang/docs-rs. It'll update a static file. r=me if it's fine for you.

**Comment by jyn514** [comment]
@bors r=GuillaumeGomez 

This will probably break docs.rs temporarily, but I don't think this should be blocked on docs.rs fixing the static file mess. I can make a PR fixing the breakage after this gets merged.

**Pull request merged**
