### PR TITLE
[WIP] polymorphisation: re-enable

### PR DESCRIPTION
**Pull request by davidtwco**
**Do not merge this PR!** 
Before re-enabling polymorphisation, we're going to perform a crater run to make sure that there are no more regressions.

r? @lcnr

### CODE REVIEW

**Comment by davidtwco** [comment]
@craterbot check

**Comment by davidtwco** [comment]
@craterbot abort

**Comment by davidtwco** [comment]
@craterbot run mode=build-and-test

**Comment by lcnr** [comment]
Should we rebase this and requeue the crater run, considering the recent changes?

**Comment by davidtwco** [comment]
> Should we rebase this and requeue the crater run, considering the recent changes?

I'm tempted to, we'd only go back one spot in the queue.

**Comment by lcnr** [comment]
yeah, we can then also reuse this PR for perf :sparkles:

**Comment by lcnr** [comment]
looks like we can get cycle errors with associated consts

**Comment by davidtwco** [comment]
Looks like I've got something to fix on Monday. 😢

**Comment by lcnr** [comment]
can quickly fix this myself :sweat_smile:

**Comment by davidtwco** [comment]
#75333 and #75337 will fix the regression above. #75260 and #75255 were fixing (or spun out of fixing) issues with polymorphization and the symbol mangling scheme (e.g. #75326) and so I forgot to run tests with only polymorphization enabled - which let these regressions slip past.

**Comment by lcnr** [comment]
We will have to start a new crater run considering the recent changes: @craterbot abort

**Comment by lcnr** [comment]
@craterbot abort

**Comment by davidtwco** [comment]
Incremental has gotten really bad but everything else is mostly unaffected. I assume that no longer storing a "no unused params" result is worse when polymorphization is enabled. 

I'd expect no real gains - we know that there aren't many polymorphization opportunities (especially with the script benchmark removed) in the benchmark suite.

**Comment by Mark-Simulacrum** [comment]
> I'd expect no real gains - we know that there aren't many polymorphization opportunities (especially with the script benchmark removed) in the benchmark suite.

To be clear, this is with *current* polymorphization, right? We know of at least one case that I identified last night that could be a win (drop_in_place). 

Regardless -- I am personally hesitant to see it enabled by default with no wins and only losses on the nightly/beta/stable compilers. Maybe we can just enable it in rustc's test suite? (At least on some builders, so we're still testing both?) Or do we expect nightly coverage to be really beneficial?

**Comment by davidtwco** [comment]
> Regardless -- I am personally hesitant to see it enabled by default with no wins and only losses on the nightly/beta/stable compilers. Maybe we can just enable it in rustc's test suite? (At least on some builders, so we're still testing both?) Or do we expect nightly coverage to be really beneficial?

I'm not that interested in actually enabling polymorphization in this PR - it primarily exists to do a crater run. 

I intend to wait until we support more cases and have a better understanding of how incr-comp is interacting with polymorphization.

**Comment by Dylan-DPC** [comment]
@davidtwco any updates on this? do we need to still keep it open?

**Comment by davidtwco** [comment]
> @davidtwco any updates on this? do we need to still keep it open?

No updates, we're still working on fixing some of the bugs with polymorphization then we'll look at resurrecting this.

**Comment by JohnCSimon** [comment]
@davidtwco 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 

@rustbot label: +S-inactive

**Pull request closed without merging**
