### PR TITLE
trans::mir::constant - fix assignment error recovery

### LINKED ISSUE #43197: 1.18.0 and nightly ICE:  /checkout/src/librustc_trans/mir/constant.rs:377: _1 not initialized
```bash
$ rustc --version
rustc 1.20.0-nightly (bf0a9e0b4 2017-07-10)
$ 
$ rustc tmp.rs
error[E0080]: constant evaluation error
 --> tmp.rs:3:18
  |
3 |    const B:i32 = A[0];	 
  |                  ^^^^ index out of bounds: the len is 0 but the index is 0

error: internal compiler error: /checkout/src/librustc_trans/mir/constant.rs:378: _1 not initialized
 --> tmp.rs:4:12
  |
4 |    let _ = &B;
  |            ^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (bf0a9e0b4 2017-07-10) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:437:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ 
$ rustc-1.18.0 tmp.rs
error[E0080]: constant evaluation error
 --> tmp.rs:3:18
  |
3 |    const B:i32 = A[0];	 
  |                  ^^^^ index out of bounds: the len is 0 but the index is 0

error: internal compiler error: /checkout/src/librustc_trans/mir/constant.rs:377: _1 not initialized
 --> tmp.rs:4:12
  |
4 |    let _ = &B;
  |            ^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:375
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ 
$ cat tmp.rs
fn main () {
   const A:&[i32] = &[];	
   const B:i32 = A[0];	 
   let _ = &B;
} 
$ 
```

### PR DESCRIPTION
**Pull request by arielb1**
trans::mir::constant - fix assignment error recovery
    
We used to not store anything when the RHS of an assignment returned an error, which caused ICEs downstream.
    
Fixes #43197.

### CODE REVIEW

**Comment by xftroxgpx** [comment]
Come on bors, merge this baby :) I can't wait!
or is the [current github](https://status.github.com/messages) status preventing that?
```
19:13 CEST We are continuing to investigate an elevated error rate in web requests to GitHub.com.
18:32 CEST Major service outage.
18:27 CEST Minor service outage.
```
or does it need another r+ for the second commit? 1057a72

**Comment by kennytm** [comment]
@xftroxgpx You could see bors's progress in https://buildbot2.rust-lang.org/homu/queue/rust. Currently it is at the 3rd place in the queue, so you will need to wait for at least 6 hours before this PR got tested.

**Pull request merged**
