### PR TITLE
std: Switch from libbacktrace to gimli (take 2)

### LINKED ISSUE #71060: Backtraces don't work during ICE
Backtraces work fine when using `panic!()` inside crate but they don't when `rustc` ICEs.

### Meta
<details><summary>Backtrace from building Rust with `debuginfo-level = 1`</summary>
<p>

```
error: internal compiler error: src\librustc_mir\monomorphize\collector.rs:606: collection encountered polymorphic constant
  --> C:\Users\mateusz\.cargo\registry\src\github.com-1ecc6299db9ec823\compiler_builtins-0.1.25\src\int\mod.rs:50:5
   |
50 |     const ONE: Self;
   |     ^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
stack backtrace:
   0:         0x67afae48 - _iob_func
   1:         0x67af99b0 - _iob_func
   2:         0x67b3968c - _iob_func
   3:         0x67aed175 - _iob_func
   4:         0x67b08fb4 - _iob_func
   5:         0x67b08c40 - _iob_func
   6:           0xe6f3eb - _iob_func
   7:         0x67b096e0 - _iob_func
   8:          0x1f8df75 - _iob_func
   9:          0x1eaea19 - _iob_func
  10:          0x1eaef52 - _iob_func
  11:          0x2292275 - _iob_func
  12:          0x229386f - _iob_func
  13:          0x2293817 - _iob_func
  14:          0x208c6f3 - _iob_func
  15:          0x208c2a9 - _iob_func
  16:          0x208a98f - _iob_func
  17:          0x208adff - _iob_func
  18:          0x1f722a4 - _iob_func
  19:          0x20894f2 - _iob_func
  20:          0x21298b6 - _iob_func
  21:          0x12411ae - _iob_func
  22:          0x12ba632 - _iob_func
  23:          0x12681f0 - _iob_func
  24:          0x138d820 - _iob_func
  25:          0x1316579 - _iob_func
  26:          0x11084b7 - _iob_func
  27:          0x1196334 - _iob_func
  28:          0x10cbc29 - _iob_func
  29:          0x11d6da7 - _iob_func
  30:           0xf7c788 - _iob_func
  31:           0xe7655c - _iob_func
  32:           0xe73391 - _iob_func
  33:           0xe80fc1 - _iob_func
  34:         0x67b090d7 - _iob_func
  35:           0xf801ae - _iob_func
  36:         0x67af2356 - _iob_func
  37:         0x67aea359 - _iob_func
  38:     0x7ffbf5f27bd4 - _iob_func
  39:     0x7ffbf650ced1 - _iob_func

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-dev running on x86_64-pc-windows-gnu

note: compiler flags: -Z macro-backtrace -Z save-analysis -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C debuginfo=1 -C linker=clang1 -C prefer-dynamic -C panic=abort -C debug-assertions=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

</p>
</details>

<details><summary>Backtrace from nightly</summary>
<p>

```
error: internal compiler error: src\librustc_mir_build\build\matches\test.rs:417: non_scalar_compare called on non-reference type: impl std::marker::Copy

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:880:9
stack backtrace:
   0:         0x6e4e7f9b - mingw_set_invalid_parameter_handler
   1:         0x6e51432b - mingw_set_invalid_parameter_handler
   2:         0x6e4d8d15 - mingw_set_invalid_parameter_handler
   3:         0x6e4ec7e1 - mingw_set_invalid_parameter_handler
   4:         0x6e4ec456 - mingw_set_invalid_parameter_handler
   5:         0x63cdedb5 - mingw_set_invalid_parameter_handler
   6:         0x6e4ece85 - mingw_set_invalid_parameter_handler
   7:         0x664647b5 - mingw_set_invalid_parameter_handler
   8:         0x664a18e2 - mingw_set_invalid_parameter_handler
   9:         0x664a0662 - mingw_set_invalid_parameter_handler
  10:         0x65e54e20 - mingw_set_invalid_parameter_handler
  11:         0x65e48d30 - mingw_set_invalid_parameter_handler
  12:         0x65e48cd3 - mingw_set_invalid_parameter_handler
  13:         0x65e54d1f - mingw_set_invalid_parameter_handler
  14:         0x65e54c7d - mingw_set_invalid_parameter_handler
  15:         0x64bc06dc - mingw_set_invalid_parameter_handler
  16:         0x64bc6d2e - mingw_set_invalid_parameter_handler
  17:         0x64bc3a91 - mingw_set_invalid_parameter_handler
  18:         0x64bc1055 - mingw_set_invalid_parameter_handler
  19:         0x64bb945f - mingw_set_invalid_parameter_handler
  20:         0x64bb9a5b - mingw_set_invalid_parameter_handler
  21:         0x64bab77f - mingw_set_invalid_parameter_handler
  22:         0x64bb926f - mingw_set_invalid_parameter_handler
  23:         0x64bb9a5b - mingw_set_invalid_parameter_handler
  24:         0x64bb9a5b - mingw_set_invalid_parameter_handler
  25:         0x64ba6f63 - mingw_set_invalid_parameter_handler
  26:         0x64b727a2 - mingw_set_invalid_parameter_handler
  27:         0x64ba5b80 - mingw_set_invalid_parameter_handler
  28:         0x64ce9818 - mingw_set_invalid_parameter_handler
  29:         0x64e29faf - mingw_set_invalid_parameter_handler
  30:         0x64d4bbbf - mingw_set_invalid_parameter_handler
  31:         0x651937d6 - mingw_set_invalid_parameter_handler
  32:         0x64ceb781 - mingw_set_invalid_parameter_handler
  33:         0x64e2d3e1 - mingw_set_invalid_parameter_handler
  34:         0x64d33c16 - mingw_set_invalid_parameter_handler
  35:         0x6508c4df - mingw_set_invalid_parameter_handler
  36:         0x64ce98e8 - mingw_set_invalid_parameter_handler
  37:         0x64e38cbf - mingw_set_invalid_parameter_handler
  38:         0x64d321ef - mingw_set_invalid_parameter_handler
  39:         0x6508cab0 - mingw_set_invalid_parameter_handler
  40:         0x64cea128 - mingw_set_invalid_parameter_handler
  41:         0x64e2eb0d - mingw_set_invalid_parameter_handler
  42:         0x64d27c13 - mingw_set_invalid_parameter_handler
  43:         0x650c81d4 - mingw_set_invalid_parameter_handler
  44:         0x64057538 - mingw_set_invalid_parameter_handler
  45:         0x64096cff - mingw_set_invalid_parameter_handler
  46:         0x6407236d - mingw_set_invalid_parameter_handler
  47:         0x64058af4 - mingw_set_invalid_parameter_handler
  48:         0x63fc1e60 - mingw_set_invalid_parameter_handler
  49:         0x64055395 - mingw_set_invalid_parameter_handler
  50:         0x63cf76ab - mingw_set_invalid_parameter_handler
  51:         0x63e2fd24 - mingw_set_invalid_parameter_handler
  52:         0x63cf9b41 - mingw_set_invalid_parameter_handler
  53:         0x63e669d6 - mingw_set_invalid_parameter_handler
  54:         0x63e3b4e0 - mingw_set_invalid_parameter_handler
  55:         0x63ce5a8c - mingw_set_invalid_parameter_handler
  56:         0x63e70701 - mingw_set_invalid_parameter_handler
  57:         0x63cea8b1 - mingw_set_invalid_parameter_handler
  58:         0x63e3d75a - mingw_set_invalid_parameter_handler
  59:         0x6e4c8b06 - mingw_set_invalid_parameter_handler
  60:         0x6e4fb7fc - mingw_set_invalid_parameter_handler
  61:     0x7ffbf5f27bd4 - mingw_set_invalid_parameter_handler
  62:     0x7ffbf650ced1 - mingw_set_invalid_parameter_handler

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (94d346360 2020-04-09) running on x86_64-pc-windows-gnu

query stack during panic:
#0 [mir_built] building MIR for
#1 [unsafety_check_result] unsafety-checking `main`
#2 [mir_const] processing `main`
#3 [mir_validated] processing `main`
#4 [mir_borrowck] borrow-checking `main`
#5 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

</p>
</details>

### PR DESCRIPTION
**Pull request by alexcrichton**
This is the second attempt to land https://github.com/rust-lang/rust/pull/73441 after being reverted in https://github.com/rust-lang/rust/pull/74613. Will be gathering precise perf numbers here in this take.

Closes #71060

### CODE REVIEW

**Comment by mati865** [comment]
`run_linker` is still significant, the other big slowdowns are as expected: `metadata_register_crate` and `metadata_decode_entry`.
I should be able to look into it next week.

**Comment by Mark-Simulacrum** [comment]
cc  https://github.com/rust-lang/rust/pull/74716 which is another revert of basically a major expansion of code in libstd.

I expect that this basically means that the current implementation of the metadata loading and such in the compiler just deals really poorly with expanding dependencies (at least std). This seems to match up with what @alexcrichton has said.

Hopefully, these two cases can both be resolved with similar modifications to the metadata loading in the compiler.

**Comment by alexcrichton** [comment]
@Mark-Simulacrum @nnethercote do y'all know what the next steps are here? This has basically been silent since the perf results came back?

**Comment by Mark-Simulacrum** [comment]
Yeah, I've been bogged down with the perf server being overloaded due to the increased speed of rust-lang/rust CI (due to GHA). I'm hoping to have some cycles this week to take a look at the performance here, probably by pushing some commits to this branch and/or doing some local benchmarking.

I also noticed that @petrochenkov noted https://github.com/rust-lang/rust/pull/74807 as likely an improvement for this PR.

I can take on rebasing this and such as needed; my guess is that we'll probably take this week to examine if there's anything we can do here and then prepare a report for next week's compiler team meeting where the benefits/costs of this PR will be evaluated. I believe that we're likely to decide that the soundness and cross-compiling nature of std is more important than the performance losses here -- which are all mostly on smaller crates, and measure in large percentages but are absolutely small -- and as such approve this PR.

**Comment by alexcrichton** [comment]
I'm happy to take on the rebasing, I just want to make sure this isn't lost in the shuffle. That was the purpose of not reverting it in the first place, it's easily forgotten. Is there anything that needs to be done to place this on an agenda?

**Comment by mati865** [comment]
I think LTOing backtrace crate would reduce linker regression at the expense of Rust's build time but haven't really got time to test that yet.

**Comment by mark-i-m** [comment]
Just a heads up that `backtrace` should be added to `library/` now instead of `src/`.

**Comment by nnethercote** [comment]
@alexcrichton: I'm happy to do some profiling, but I can't manage to apply the patch so that it builds locally, even after @Mark-Simulacrum helped me. Is the contents of `.gitmodules` correct? It mentions `src/backtrace`. Can you give me a single command to download and apply the patch? Thanks.

**Comment by alexcrichton** [comment]
AFAIK this can't be downloaded as a patch because it adds a submodule, you'll need to checkout the git commit or do a cherry-pick. I'll fix the .gitmodules issue but I don't think that will help with apply this PR as a patch.

**Comment by nnethercote** [comment]
Here is a Cachegrind diff for `helloworld`, which should be representative.
```
--------------------------------------------------------------------------------
Ir                   file:function
--------------------------------------------------------------------------------
 1,356,720 ( 6.95%)  /home/njn/moz/rustN/library/core/src/str/mod.rs:core::str::from_utf8
   759,853 ( 3.89%)  /home/njn/moz/rustN/src/librustc_serialize/leb128.rs:rustc_serialize::serialize::Decoder::read_option
   749,805 ( 3.84%)  /home/njn/moz/rustN/src/librustc_hir/definitions.rs:<rustc_hir::definitions::DefKey as rustc_serialize::serialize::Decodable>::decode
   576,010 ( 2.95%)  /home/njn/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-hash-1.1.0/src/lib.rs:_ZN59_$LT$rustc_hash..FxHasher$u20$as$u20$core..hash..Hasher$GT$5write17hb6bb59a12824277fE.llvm.NNN 
   509,976 ( 2.61%)  /home/njn/moz/rustN/src/librustc_serialize/leb128.rs:<rustc_hir::definitions::DefKey as rustc_serialize::serialize::Decodable>::decode
   475,531 ( 2.44%)  /home/njn/moz/rustN/src/librustc_serialize/opaque.rs:<rustc_span::SourceFile as rustc_serialize::serialize::Decodable>::decode
   456,418 ( 2.34%)  /home/njn/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/raw/mod.rs:hashbrown::raw::RawTable<T>::insert
   416,754 ( 2.13%)  /home/njn/moz/rustN/src/librustc_metadata/rmeta/decoder.rs:<rustc_metadata::rmeta::decoder::DecodeContext as rustc_serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
   399,952 ( 2.05%)  ???:llvm::StringMapImpl::LookupBucketFor(llvm::StringRef)
   375,778 ( 1.92%)  /home/njn/moz/rustN/src/librustc_serialize/opaque.rs:_ZN88_$LT$rustc_serialize..opaque..Decoder$u20$as$u20$rustc_serialize..serialize..Decoder$GT$8read_str17h01d5500dbce54e65E.llvm.NNN
   366,560 ( 1.88%)  /home/njn/moz/rustN/src/librustc_serialize/serialize.rs:rustc_serialize::serialize::Decoder::read_option
   329,920 ( 1.69%)  /build/glibc-YYA7BZ/glibc-2.31/malloc/malloc.c:_int_malloc
   321,586 ( 1.65%)  /home/njn/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/raw/mod.rs:scoped_tls::ScopedKey<T>::with
   321,192 ( 1.64%)  /home/njn/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:scoped_tls::ScopedKey<T>::with
   304,226 ( 1.56%)  /home/njn/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/map.rs:hashbrown::map::HashMap<K,V,S>::insert
   298,526 ( 1.53%)  /home/njn/moz/rustN/library/alloc/src/vec.rs:<rustc_span::SourceFile as rustc_serialize::serialize::Decodable>::decode
   295,320 ( 1.51%)  /build/glibc-YYA7BZ/glibc-2.31/elf/../sysdeps/x86_64/tls_get_addr.S:__tls_get_addr
   267,966 ( 1.37%)  /build/glibc-YYA7BZ/glibc-2.31/malloc/malloc.c:_int_free
   213,647 ( 1.09%)  /build/glibc-YYA7BZ/glibc-2.31/string/../sysdeps/x86_64/multiarch/memcmp-avx2-movbe.S:__memcmp_avx2_movbe
   205,266 ( 1.05%)  /home/njn/moz/rustN/src/librustc_serialize/leb128.rs:<rustc_metadata::rmeta::decoder::DecodeContext as rustc_serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
   192,838 ( 0.99%)  /build/glibc-YYA7BZ/glibc-2.31/malloc/malloc.c:malloc
   183,278 ( 0.94%)  /home/njn/moz/rustN/library/core/src/slice/mod.rs:<rustc_metadata::rmeta::decoder::DecodeContext as rustc_serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
   179,183 ( 0.92%)  /home/njn/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/raw/mod.rs:hashbrown::map::HashMap<K,V,S>::insert
   174,984 ( 0.90%)  /home/njn/moz/rustN/src/librustc_serialize/serialize.rs:rustc_serialize::serialize::Decoder::read_seq
   173,436 ( 0.89%)  /home/njn/moz/rustN/src/librustc_serialize/leb128.rs:_ZN88_$LT$rustc_serialize..opaque..Decoder$u20$as$u20$rustc_serialize..serialize..Decoder$GT$8read_str17h01d5500dbce54e65E.llvm.NNN
   173,341 ( 0.89%)  /home/njn/moz/rustN/library/alloc/src/vec.rs:rustc_serialize::serialize::Decoder::read_seq
   158,871 ( 0.81%)  /home/njn/moz/rustN/src/librustc_query_system/query/plumbing.rs:rustc_query_system::query::plumbing::get_query_impl
   154,258 ( 0.79%)  ???:llvm::PassRegistry::registerPass(llvm::PassInfo const&, bool)
   149,634 ( 0.77%)  /home/njn/moz/rustN/library/core/src/num/mod.rs:core::str::from_utf8
   146,524 ( 0.75%)  /home/njn/moz/rustN/src/librustc_serialize/opaque.rs:<rustc_hir::definitions::DefKey as rustc_serialize::serialize::Decodable>::decode
   144,218 ( 0.74%)  /build/glibc-YYA7BZ/glibc-2.31/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms
   143,430 ( 0.73%)  /home/njn/moz/rustN/src/librustc_span/symbol.rs:<rustc_hir::definitions::DefKey as rustc_serialize::serialize::Decodable>::decode
```
Looks like it's all due to more metadata encoding.

**Comment by alexcrichton** [comment]
Is there something I need to do to ensure that this comes up on the appropriate agenda? If so, what is that?

**Comment by Mark-Simulacrum** [comment]
I don't think so -- I plan to spend some more time this week looking at that cachegrind diff and performance here in general (and have already posted at least one PR, #74887 which should have a ~1% improvement on the benchmarks that regressed here). I think once that's done we'll want to re-run try here for some "final numbers" and nominate this PR for the compiler team.

My expectation is that it will then be discussed on August 6th and likely landed soon thereafter.

**Comment by alexcrichton** [comment]
Is it possible to bump this sooner on the agenda? It was intended to land this just after the beta branch to give this maximal testing on nightly to weed out unexpected regressions. Landing after August 6th delays that by 3 weeks and halves the amount of nightly testing this is going to get.

I'll reiterate I'm more than happy to revert this if the decision is that it shouldn't land. Given though that this is highly likely to land I continue to not understand the very strong reluctance to put this in tree.

**Comment by Mark-Simulacrum** [comment]
That's a good point re:nightly testing, I hadn't considered that previously. I've now nominated this for discussion this Thursday (tomorrow) and then I expect the conclusion to be that it'll land roughly this week/weekend.

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue 

Let's get a final perf build before the compiler team meeting tomorrow.

**Comment by Mark-Simulacrum** [comment]
We [discussed](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-07-30.20.2354818/near/205489732) this in today's compiler team meeting, and the decision was that indeed the functionality tradeoff here is worth the (possibly temporary) performance losses. It was also noted that indeed, the performance losses in wall-clock time are marginal and only affect the smaller benchmarks.

@alexcrichton, would you be up for confirming that this PR appropriately fixes any rust-src component breakage and such? I imagine a rustup-toolchain-install-master install and confirming -Zbuild-std works is basically sufficient there. I can also publish a dev-static nightly if that'd be helpful.

**Comment by alexcrichton** [comment]
Is there a way to test that ahead of time? I'm happy to do any testing for that, I just figured it wasn't really testable until this merged

**Comment by Mark-Simulacrum** [comment]
Hm okay so rust-src is broken right now *anyway* as a result of the src -> library move... but that should have been fixed by https://github.com/rust-lang/rust/pull/74923. I guess the try build here kicked off a few hours before that merged, though.

@bors try

I (tried to) test the current try build by doing this:

```
cargo new --lib foo && cd foo
$ rustup-toolchain-install-master -c rust-src -- 59c859c74c32bb26ba7c0932ec50c6
c566eeac76
detecting the channel of the `59c859c74c32bb26ba7c0932ec50c6c566eeac76` toolchain...
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/59c859c74c32bb26ba7c0932ec50c6c566eeac76/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
50.63 MB / 50.63 MB [=====================================================] 100.00 % 13.00 MB/s
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/59c859c74c32bb26ba7c0932ec50c6c566eeac76/rust-src-nightly.tar.xz>...
1.76 MB / 1.76 MB [========================================================] 100.00 % 4.44 MB/s
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/59c859c74c32bb26ba7c0932ec50c6c566eeac76/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz>...
20.73 MB / 20.73 MB [=====================================================] 100.00 % 12.14 MB/s
toolchain `59c859c74c32bb26ba7c0932ec50c6c566eeac76` is successfully installed!
$ cargo +59c859c74c32bb26ba7c0932ec50c6c566eeac76 -Zbuild-std build --target x86_64-unknown-linux-gnu
error: failed to read `/home/mark/.rustup/toolchains/59c859c74c32bb26ba7c0932ec50c6c566eeac76/lib/rustlib/src/rust/src/libstd/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

(Obviously, we expect that to succeed).

**Comment by alexcrichton** [comment]
Needed to add `-c cargo` there too to get Cargo installed, but after that I can confirm that this does indeed work with `-Zbuild-std`

**Comment by Mark-Simulacrum** [comment]
As expected, this was a performance [regression](https://perf.rust-lang.org/compare.html?start=cfc572cae2d1fc381cce476b5c787fd7221af98c&end=c058a8b8dc5dea0ed9b33e14da9e317e2749fcd7&stat=instructions%3Au) of up to 20% on smaller crates, essentially entirely due to increased amount of metadata decoding. https://github.com/rust-lang/rust/pull/75008 may be the first step in eliminating these losses.

**Pull request merged**
