### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by JohnTitor**
Successful merges:

 - #86659 (fix(rustdoc): generics search)
 - #86768 (Add myself to mailmap)
 - #86775 (Test for const trait impls behind feature gates)
 - #86777 (Include terminators in instance size estimate)
 - #86779 (Allow anyone to add or remove any label starting with perf-)
 - #86783 (Move Mutex::unlock to T: ?Sized)
 - #86785 (proc_macro/bridge: Remove dead code Slice type)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=86659,86768,86775,86777,86779,86783,86785)

### CODE REVIEW

**Comment by wesleywiser** [comment]
#86777 should not be rolled up since it could affect perf. Can we redo this rollup without that PR?

**Comment by JohnTitor** [comment]
Sure!
@bors r-

**Comment by wesleywiser** [comment]
Thanks @JohnTitor! 🙂

**Pull request closed without merging**
