### PR TITLE
Avoid recompiling std when tests change in std::net

### PR DESCRIPTION
**Pull request by tesuji**
I moved ui tests to their own files.
It's best when review commit by commit.

I could squash them all if requested.
r? @KodrAus

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks @lzutao!

It looks like we don’t have a really consistent approach to organizing tests here in `std`, is there anything special about these ones to move them into separate files or is the plan to work through other modules and do the same thing?

**Comment by lzutao** [comment]
I am modifying things in #75110 . It is kind of painful when I only change tests but std is recompiled.

**Comment by lzutao** [comment]
@KodrAus Should I open an MCP on compiler team repo to enforce tests module in separate file?

**Comment by KodrAus** [comment]
> Should I open an MCP on compiler team repo to enforce tests module in separate file?

I wasn't actually aware that moving `#[cfg(test)]` modules into a separate file could save recompiling the main crate when only that test file changes. If that's the case then it seems like that would be worth doing! We could try re-organize more of `std`'s tests to resemble the way they're done in `core`?

**Comment by lzutao** [comment]
Reopened the proposal in #75979.

**Pull request closed without merging**
