### PR TITLE
Update stdarch submodule

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I'm syncing the rustc_codegen_gcc backend currently and it seems that the new rustc version we use is not happy with the current stdarch submodule version: https://github.com/rust-lang/rustc_codegen_gcc/actions/runs/7930753019/job/21653642490?pr=439

r? @Amanieu

### CODE REVIEW

**Comment by Amanieu** [comment]
I just merged some PRs, can you update the submodule to the latest master?

**Comment by GuillaumeGomez** [comment]
Sure, done!

**Comment by Amanieu** [comment]
There's been a few more updates on stdarch, can you update again?

**Comment by GuillaumeGomez** [comment]
Done!

**Comment by RalfJung** [comment]
@bors p=1
(submodule / tool update, unblocking other work)

**Pull request merged**
