### PR TITLE
Add MemoryExtra to find_foreign_static

### PR DESCRIPTION
**Pull request by pvdrz**
r? @RalfJung @oli-obk 

Related miri PR: https://github.com/rust-lang/miri/pull/928

### CODE REVIEW

**Comment by RalfJung** [comment]
Sounds reasonable!

@bors rollup=0

(I don't want this to land before the next nightly because it'll break Miri, and we desparately need a new working Miri shipped by rustup.)

**Comment by RalfJung** [comment]
All right, now it can't land before midnight anyway.

@bors rollup-

**Comment by oli-obk** [comment]
@bors r-

No, do it here

**Comment by RalfJung** [comment]
> I discovered that I also need to change Machine::find_foreign_static return type to Alloc<M::Tag, M::AllocExtra> should I do it on a separate PR?

Why that?

**Comment by RalfJung** [comment]
Hm... not sure that that makes sense. `find_foreign_static` is only called the first time a foreign static is accesses, then it gets put into the alloc_map.

But indeed so far we didn't have foreign statics that can change, so it is possible that something will have to change here. I am not sure what the best design looks like.

**Comment by RalfJung** [comment]
No, that would just make your life even harder.

**Comment by RalfJung** [comment]
But also you are getting initially tagged with `M::STATIC_KIND.map(MemoryKind::Machine)` as kind anyway.

**Comment by RalfJung** [comment]
Initial plan: also pass the `AllocId` to `find_foreign_static`.

On the Miri side, have state in `EnvVars` that stores an `environ: Option<AllocId>` (or maybe `Option<Pointer<Tag>>`, obtained via `tag_static_base_pointer`). Whenever an env var changes, if that variable is set, you need to build a new env list and store the address in the allocation identified there. In `find_foreign_static`, (a) assert it is still `None`, (b) set it to point to the `AllocId` you got, and (c) return as initial value the initial env list.

I think that should work. It is also quite clumsy though. I'll need to sleep over it.

**Comment by RalfJung** [comment]
@oli-obk is it possible, given the link name of a foreign static, to compute its `DefId`?

What happens with something like
```
extern {
    static foo: *const libc::c_void;
}
mod bar {
    extern {
        static foo: *const libc::c_void;
    }
}
```
Will that be two separate `DefId` for the same static?

**Comment by oli-obk** [comment]
Oh :/ yea that seems like we'd screw it up. I guess we can use the string name as a unique identifier.

**Comment by RalfJung** [comment]
The problem is that every `DefId` gives rise to an `AllocId`. For normal statics that already makes things subtle as there are two `AllocId` (the `DefId` one and the "evaluated" one); for extern statics that's basically nonsense.

OTOH, I think it is fine for now to ICE if the program uses two `extern static` with the same name.

**Comment by JohnCSimon** [comment]
Ping from triage - 
@christianpoveda @RalfJung @oli-obk 
This conversation seems to have stalled out for a week. Is this ready for review? Thanks

**Comment by christianpoveda** [comment]
I think we can close this PR and come back to it when I have a clearer idea on how to fix it

**Pull request closed without merging**
