### PR TITLE
Rollup of 1 pull requests

### PR DESCRIPTION
**Pull request by TimNN**
- Successful merges: #40998
- Failed merges: #41045

### CODE REVIEW

**Comment by aidanhs** [comment]
```
[00:00:00] Attempting with retry: docker build --rm -t rust-ci /home/travis/build/rust-lang/rust/src/ci/docker/dist-x86-linux
[00:00:00] unable to prepare context: unable to evaluate symlinks in context path: lstat /home/travis/build/rust-lang/rust/src/ci/docker/dist-x86-linux: no such file or directory
```
Sounds a bit bad

**Comment by TimNN** [comment]
@bors retry

* `ar.exe`...

**Comment by TimNN** [comment]
@bors retry

* #40240

**Pull request merged**
