### PR TITLE
Don't show associated const value anymore

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #44348.

Before:

screen shot 2018-08-16 at 00 48 30

After:

screen shot 2018-08-16 at 00 48 23

cc @nox

r? @QuietMisdreavus

### CODE REVIEW

**Comment by nox** [comment]
Did you check what it looks like if the constant is documented? If I just hide the code block for the definition with current rustdoc, the spacing around the docs seems closer to the next item than the one it documents.

**Comment by GuillaumeGomez** [comment]
I didn't but I can add a pass for it if you want.

**Comment by nox** [comment]
I just mentioned it because I noticed it was messing up the spacing with my small [CSS extension](
https://twitter.com/nokusu/status/1029512110060064769).

**Comment by GuillaumeGomez** [comment]
Didn't see anything special despite the fact that the toggle wasn't added to associated const docs. I fixed it in my last commit. Now it looks like this:

screen shot 2018-08-18 at 18 10 37

screen shot 2018-08-18 at 18 10 57

**Comment by QuietMisdreavus** [comment]
Tagging some people who i know use associated consts in their documentation: @sgrif @SergioBenitez 

Overall i'm fine with this, since like @nox said, it can leak internal information. I'd hoped there could be a more elegant/complicated way to deal with it, but i guess this solves an immediate problem.

**Comment by nox** [comment]
I've just realised that constant definitions should be hidden too, not just for associated constants.

https://docs.rs/khronos_api/2.2.0/khronos_api/constant.EGL_XML.html

**Comment by SimonSapin** [comment]
Right, for `const` items and `static` items it may make sense to not show the value, but that’s not related to whether the item is associated (in an `impl`) or module-level.

Though I feel that it might depend. Sometimes the value of a constant is useful and relevant info, not absurdly long, and not "leaking" internal implementation details. https://github.com/rust-lang/rust/issues/44348#issuecomment-413135869 mentions opaque wrappers, so maybe the presence of private fields (or the *absence* of public fields, for structs) could be a heuristic that affects the default. And may it’s worth having an attribute like `#[doc(value = "hidden")]` and `#[doc(value = "shown")]`.

**Comment by nox** [comment]
One can always click on the `[src]` link to see the definition.

**Comment by GuillaumeGomez** [comment]
> One can always click on the `[src]` link to see the definition.

That was the whole point of adding `[src]` while removing the definition.

**Comment by QuietMisdreavus** [comment]
It's worth linking this PR to https://github.com/rust-lang/rust/issues/49259 as well.

**Comment by SergioBenitez** [comment]
I generally like this change. This might imply, however, that the actual value of a constant is not part of the public interface, which would mean that changing the value of a `const` is a semver-compatible change, all other things remaining the same. I _believe_ that should be true, but it's something worth considering.

**Comment by GuillaumeGomez** [comment]
@SergioBenitez: From my point of view, you're supposed to use a const, not its value. So changing its value shouldn't impact someone's code. But that should be considered, indeed.

**Comment by GuillaumeGomez** [comment]
Yes, I'll do it soon.

**Comment by sgrif** [comment]
I am extremely :+1: on not showing the value, I felt it was noisy when that was added

**Comment by Centril** [comment]
It seems to me that in the presence of const generics; the value of an associated const is absolutely part of the interface and can cause compilation errors. I'm quite skeptical about not showing associated consts long term therefore.

**Comment by nox** [comment]
What you say is already true without const generics and you can click on the source link to see the definition of the constant.

**Comment by QuietMisdreavus** [comment]
@Centril I disagree; to me, the actual *value* is less important than what it *represents*, and that doesn't change in the light of const generics. I'm skeptical that changing the value of a const without changing its type will affect whether something *compiles*. To the code that's using a given const, the value is opaque - you're interacting with the value via this named handle that is substituted in behind the scenes whenever you compile. Do you have a situation in mind which could be affected like that?

What does change, however, is how we decide to represent instances of const generics which use a given value instead of being generic over it. However, that can wait until [the current const generics PR](https://github.com/rust-lang/rust/pull/53645) gets to the point where they wish to expose it from rustdoc.

**Comment by Centril** [comment]
@QuietMisdreavus 

> I'm skeptical that changing the value of a const without changing its type will affect whether something compiles.

As @nox says, this is the case even [today](https://play.rust-lang.org/?gist=87b74ee9bed73ba3e7a30835e6366325&version=stable&mode=debug&edition=2015):

```rust
trait Foo {
    const BAR: usize;
}

struct Baz;

impl Foo for Baz {
    const BAR: usize = 3; // Change this to 4 and we have a compilation error.
}

fn main() {
    let arr: [u8; <Baz as Foo>::BAR] = [1, 2, 3];
}
```

**Comment by Centril** [comment]
@nox 

> That doesn’t happen if you use the constant exhaustively as one should.

Fair enough.

**Comment by bluetech** [comment]
If the value is informative for the user, it can always be repeated in the docstring. See e.g. [`http::StatusCode`](https://docs.rs/http/0.1.10/http/status/struct.StatusCode.html).

**Comment by TimNN** [comment]
Ping from triage @QuietMisdreavus / @GuillaumeGomez: What is the status of this PR?

**Comment by GuillaumeGomez** [comment]
It **seems** to be ok. Not sure if the debate is over or not...

**Comment by QuietMisdreavus** [comment]
Something to note for the people wanting a more-robust means of printing associated constants: Since @GuillaumeGomez didn't make this close the linked issue, i can only assume he has some plan up his sleeve? It can be extended later, but the current form of associated consts is unwieldy and awkward. If the concerns of @Centril, @SimonSapin, and/or whoever else was in this thread have been resolved, r=me.

Side note: Is the `prefix` parameter of `document_full`/`document_short`/etc used any more? I seem to remember thinking that was its only use...

**Comment by Centril** [comment]
@GuillaumeGomez my concerns are resolved. :)

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus It's still in use apparently. And @Centril seems to be happy with changes. I'll let you r+ though. :p

**Comment by TimNN** [comment]
Ping from triage @QuietMisdreavus: It looks like this PR requires a final review from you.

**Comment by QuietMisdreavus** [comment]
Welp, with no further comment, let's get this merged.

@bors r+

**Pull request merged**
