### PR TITLE
Add nowrap_{add|sub|mul|neg} intrinsics

### PR DESCRIPTION
**Pull request by scottmcm**
[LLVM cannot deduce nsw/nuw for things like `Range::next` today](https://play.rust-lang.org/?gist=e232272d4a843214df76db23fbc3a980&version=nightly&mode=release&edition=2015), so add these so that my next PR can use them to improve what `Range` tells LLVM.

(This adds the ones that [`rustc_codegen_llvm::builder::Builder`](https://github.com/rust-lang/rust/issues/51737) and `rustc_llvm::ffi` currently support, which is why it has `nowrap_neg` but not [`nowrap_shl`](http://llvm.org/docs/LangRef.html#shl-instruction).)

tag guess: T-compiler

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors r+

I see no reason not to do this, and if it ends up not helping we can always remove them

**Comment by nagisa** [comment]
@bors r-

There’s no necessity to land intrinsics before a PR with an actual use case can be made (such as e.g. `Range` optimisations).

Please implement actual changes against `Range` and provide benchmarks before landing these intrinsics.

**Comment by nagisa** [comment]
Also, 

> we can always remove them

is a very slippery slope, simply because it is way easier to forget and not remove something that ended up not being used (or not useful for some immediate use case). It is way easier to land everything together or not land stuff at all :)

**Comment by gnzlbg** [comment]
Here is an use case for these intrinsics: https://github.com/rust-lang/rfcs/issues/2508

Basically, there is no easy way to generate LLVM-IR with `nsw nuw` flags via rustc today. This makes it very hard to even evaluate whether such operations should be exposed by higher-level APIs, or whether these flags have an impact at all on the generated code.

So I'd argue that these intrinsics are at least useful for hacking on rustc/LLVM, debugging performance issues, etc.

**Pull request closed without merging**
