### PR TITLE
Bring back ParamEnv deduplication

### LINKED ISSUE #48551: Unexpected panic with cgmath
The command: cargo build
The version: rustc 1.26.0-nightly (322d7f7b9 2018-02-25)
The error:

```
   Compiling cgmath v0.16.0
   Compiling rusqlite v0.13.0
   Compiling target_build_utils v0.3.1
thread 'rustc' panicked at 'assertion failed: `(left != right)`
  left: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([S, S]), item_def_id: DefId(2/0:885 ~ core[ffe9]::ops[0]::arith[0]::Add[0]::Output[0]) }, S)))`,
 right: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([S, S]), item_def_id: DefId(2/0:885 ~ core[ffe9]::ops[0]::arith[0]::Add[0]::Output[0]) }, S)))`', librustc/traits/project.rs:146:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: core::ops::function::Fn::call
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:401
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   7: rustc::traits::project::ProjectionTyCandidateSet::push_candidate
   8: rustc::traits::project::opt_normalize_projection_type
   9: rustc::traits::project::poly_project_and_unify_type::{{closure}}
  10: rustc::traits::project::poly_project_and_unify_type
  11: <rustc::traits::fulfill::FulfillProcessor<'a, 'b, 'gcx, 'tcx> as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
  12: rustc::traits::fulfill::FulfillmentContext::select
  13: rustc::traits::fulfill::FulfillmentContext::select_all_or_error
  14: rustc_typeck::check::compare_method::compare_predicate_entailment
  15: rustc_typeck::check::check_impl_items_against_trait
  16: rustc_typeck::check::check_item_type
  17: rustc_typeck::check_crate::{{closure}}
  18: rustc_typeck::check_crate
  19: rustc::ty::context::TyCtxt::create_and_enter
  20: rustc_driver::driver::compile_input
  21: rustc_driver::run_compiler

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (322d7f7b9 2018-02-25) running on x86_64-unknown-linux-gnu

error: Could not compile `cgmath`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Fix #48551

### CODE REVIEW

**Comment by leodasvacas** [comment]
Could we have a test for this?

**Comment by ishitatsuyuki** [comment]
We probably should, but we don't have a deducted test case yet.

**Comment by nikomatsakis** [comment]
This seems to be causing a lot of pain, so I'm going to r+ with p=1, but I agree with @leodasvacas that we ought to have a test here.

@bors r+ p=1

**Comment by ishitatsuyuki** [comment]
Initial simplified case: https://play.rust-lang.org/?gist=878f5427988c9c59b9ff11057547e624&version=stable

**Pull request merged**
