### PR TITLE
remove overzealous Box<ZeroSizeType> optimization

### PR DESCRIPTION
**Pull request by qmx**

### CODE REVIEW

**Comment by arielb1** [comment]
@bors r+

Let's see whether this is important IRL.

**Comment by bstrie** [comment]
What bug is this fixing? "Overzealous" how?

**Comment by eddyb** [comment]
@bstrie This was leftover cruft from before @arielb1 moved drop glue to MIR shims. All it does is skip very little code, for a very special case. It was annoying because of two reasons:
* it was used from `monomorphize::resolve` which @qmx was trying to move to librustc and generalize (to use in MIR inlining), and if you have a type parameter you can't check its size
* it's a `Box` special case, the fewer of those, the better

**Pull request merged**
