### PR TITLE
[do not merge] test #129714 revert on bootstrap times

### PR DESCRIPTION
**Pull request by lqd**
It seems we're currently experiencing some instability with the benchmarking results. #129714 had weird results, somehow failing to measure bootstrap and other benchmarks. Since then bootstrap measurements [have also increased](https://perf.rust-lang.org/bootstrap.html). Let's see if a revert does anything to bootstrap times at the very least, to see if the PR is maybe involved.

r? ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
@rust-timer build 60a3a34388fb9b4261f940a462652d7c42a33f35

**Comment by lqd** [comment]
The more the merrier. Now with a #127537 revert, since it seems to be more of the culprit for bootstrap times.

@bors try

**Comment by lqd** [comment]
- bootstrap was measured successfully
- bootstrap times unchanged, and expected, now that we know https://github.com/rust-lang/rust/pull/127537 should be the root cause instead
- all benchmarks were run
- cycles and max-rss are still going crazy. We'll see if that changes with the https://github.com/rust-lang/rust/pull/127537 revert, or most likely we'll need to land either/both and see what happens.

**Comment by lqd** [comment]
@rust-timer build b0dec66dd4ba3f647b067a903fe73f1283153720

**Comment by lqd** [comment]
ready in case #129854 doesn't work out 
r? kobzol

**Comment by lqd** [comment]
Issue looks to be in the collector DB, no need to merge this.

**Pull request closed without merging**
