### PR TITLE
Merge `TraitItem` & `ImplItem into `AssocItem`

### PR DESCRIPTION
**Pull request by Centril**
In this PR we:

- Merge `{Trait,Impl}Item{Kind?}` into `AssocItem{Kind?}` as discussed in https://github.com/rust-lang/rust/issues/65041#issuecomment-538105286.

   - This is done by using the cover grammar of both forms.

   - In particular, it requires that we syntactically allow (under `#[cfg(FALSE)]`):

      - `default`ness on `trait` items,

      - `impl` items without a body / definition (`const`, `type`, and `fn`),

      - and associated `type`s in `impl`s with bounds, e.g., `type Foo: Ord;`.

   - The syntactic restrictions are replaced by semantic ones in `ast_validation`.

- Move syntactic restrictions around C-variadic parameters from the parser into `ast_validation`:

    - `fn`s in all contexts now syntactically allow `...`,

    - `...` can occur anywhere in the list syntactically (`fn foo(..., x: usize) {}`),

    - and `...` can be the sole parameter (`fn foo(...) {}`.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
r=me on the implementation.

Not sure whether this needs an FCP from the lang team or the consensus in https://github.com/rust-lang/rust/issues/65041#issuecomment-538105286 is enough.

**Comment by Centril** [comment]
👋 @rust-lang/lang :)

**Comment by Centril** [comment]
I'm gonna interpret the radio silence here + general feeling about semantic vs. syntactic errors expressed in the past as "I have nothing new to add atop the existing consensus in https://github.com/rust-lang/rust/issues/65041#issuecomment-538105286". :)

@bors r=petrochenkov

**Comment by eddyb** [comment]
Could this PR allow the following (assuming `delegate` is some proc macro)?

```rust
struct Wrapper<T>(T);

#[delegate(self.0: T)]
impl<T> fmt::Debug for Wrapper<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result;
}
```
Which could expand into:
```rust
struct Wrapper<T>(T);

impl<T> fmt::Debug for Wrapper<T>
    where T: fmt::Debug
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self.0, f)
    }
}
```

I guess you could do it before this PR too and just require an empty body or thereabouts, but being able to have an explicit `;` seems slightly nicer.

**Comment by nikomatsakis** [comment]
@Centril 

> I'm gonna interpret the radio silence here + general feeling about semantic vs. syntactic errors expressed in the past as "I have nothing new to add atop the existing consensus in #65041 (comment)". :)

in my case, I just hadn't gotten to the notification -- but I am indeed fine with the "language implications" here.

I didn't look *too* closely at the PR itself, though from a quick look it seemed good.

**Comment by Centril** [comment]
> Could this PR allow the following (assuming `delegate` is some proc macro)?

@eddyb Indeed, that would be allowed. :) Go forth and implement!

**Comment by Centril** [comment]
> The job `i686-mingw-2` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=15606&view=logs&jobId=aac1e68a-9baa-54d2-b80b-75ce793a8506) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/15606/logs/1699), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/15606/logs/1699)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

Might be spurious? I have no idea why this is happening at the moment so let's try again and see if it was.

@bors r=petrochenkov rollup=never

**Comment by Centril** [comment]
We'll have to wait a week for toolstate now.

**Pull request merged**
