### PR TITLE
delete [allow(unused_unsafe)] from issue #74838

### PR DESCRIPTION
**Pull request by mj10021**
While looking into issue #111288 I noticed the following `#[allow(...)]` with a `FIXME` asking for it to be removed.  Deleting the `#[allow(...)]` does not seem to break anything, it seems like the lint has been updated for unsafe blocks in macros?

### CODE REVIEW

**Comment by jyn514** [comment]
it would be nice to track down when this changed so we know whether or not to close https://github.com/rust-lang/rust/issues/111288. do you have time to do that?

**Comment by mj10021** [comment]
> it would be nice to track down when this changed so we know whether or not to close #111288. do you have time to do that?

Do you mean to track down when the lint from #111288 regressed or when the `[allow(...)]` stopped being necessary?  This doesn't fix #111288 and I actually think #111288 is a bigger issue regarding warnings from macros in general

**Comment by jyn514** [comment]
When the allow stopped necessary. I'm trying to find out if #111288 is still an issue or not. Another (maybe easier?) way would be to write a small program that shouldn't lint about unsafe but does and that would confirm it's still an issue.

**Comment by mj10021** [comment]
Ok gotcha I will look into it

**Comment by mj10021** [comment]
@jyn514 it looks like commit [e1d7dec558d](https://github.com/rust-lang/rust/commit/e1d7dec558d) is the one that made the `allow` unnecessary, does that make any sense?

**Comment by jyn514** [comment]
@mj10021 it makes sense, but it doesn't actually help narrow this down much - that commit includes all the changes between 1.64 beta and 1.65 beta, so the change in the lint could have happened any time in those 6 weeks.

**Comment by jyn514** [comment]
Sorry, I've been confused this whole time. I meant to say which change made *74838* not warn any more, not 111288.

**Comment by mj10021** [comment]
I got the following from cargo-bisect-rustc:

```
********************************************************************************
Regression in nightly-2022-08-20
********************************************************************************

fetching https://static.rust-lang.org/dist/2022-08-19/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2022-08-19: 40 B / 40 B [======================] 100.00 % 776.59 KB/s converted 2022-08-19 to 0b79f758c9aa6646606662a6d623a0752286cd17
fetching https://static.rust-lang.org/dist/2022-08-20/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2022-08-20: 40 B / 40 B [======================] 100.00 % 503.39 KB/s converted 2022-08-20 to e1b28cd2f16bd5b832183d7968cae3bb9213e78d
looking for regression commit between 2022-08-19 and 2022-08-20
cloning rust repository
fetching (via local git) commits from 0b79f758c9aa6646606662a6d623a0752286cd17 to e1b28cd2f16bd5b832183d7968cae3bb9213e78d
opening existing repository at "rust.git"
Found origin remote under name `origin`
refreshing repository at "rust.git"
looking up first commit
looking up second commit
checking that commits are by bors and thus have ci artifacts...
finding bors merge commits
found 5 bors merge commits in the specified range
  commit[0] 2022-08-18: Auto merge of #98807 - cbeuw:derived-obligation, r=compiler-errors
  commit[1] 2022-08-18: Auto merge of #98851 - klensy:encode_symbols, r=cjgillot
  commit[2] 2022-08-19: Auto merge of #99541 - timvermeulen:flatten_cleanup, r=the8472
  commit[3] 2022-08-19: Auto merge of #100209 - cjgillot:source-file-index, r=estebank
  commit[4] 2022-08-19: Auto merge of #100740 - Dylan-DPC:rollup-0td6yq4, r=Dylan-DPC
ERROR: no CI builds available between 0b79f758c9aa6646606662a6d623a0752286cd17 and e1b28cd2f16bd5b832183d7968cae3bb9213e78d within last 167 days
```

It's not obvious to me why any of the commits affect the `unused_unsafe` in macros...

**Comment by mj10021** [comment]
Nevermind!  I think it's this: [#100081](https://github.com/rust-lang/rust/pull/100081)

**Comment by mj10021** [comment]
hey @jyn514 just following up here, is there anything else that I should do for this pr?

**Comment by jyn514** [comment]
r? libs

**Comment by cuviper** [comment]
There are a few more allows around thread locals -- can they all be removed?

https://github.com/rust-lang/rust/blob/114fb86ca08cfa6a99087e0f0bc264d03590dc37/library/std/src/sys/common/thread_local/os_local.rs#L27
https://github.com/rust-lang/rust/blob/114fb86ca08cfa6a99087e0f0bc264d03590dc37/library/std/src/sys/common/thread_local/os_local.rs#L62-L65
https://github.com/rust-lang/rust/blob/114fb86ca08cfa6a99087e0f0bc264d03590dc37/library/std/src/sys/common/thread_local/static_local.rs#L46-L49
https://github.com/rust-lang/rust/blob/114fb86ca08cfa6a99087e0f0bc264d03590dc37/library/std/src/sys_common/thread_info.rs#L2

**Comment by mj10021** [comment]
ah good point, I took out all of the `allow(unused_unsafe)`s in /library/std and it seems to be building fine

**Comment by cuviper** [comment]
Thanks!

@bors r+

**Comment by mj10021** [comment]
I am assuming the `#[allow...` that needed to be added back was in `library/std/src/sys/unix/weak.rs`... do you know how I can rerun the `arm-android` test?

**Comment by cuviper** [comment]
You can add temporarily add it to the `pr` job [here](https://github.com/rust-lang/rust/blob/d908a5b08e9ccbd2b41f8b399aa6cd919d5cb451/src/ci/github-actions/ci.yml#L309), and re-run the command mentioned at the top of that file.

**Comment by mj10021** [comment]
> You can add temporarily add it to the `pr` job [here](https://github.com/rust-lang/rust/blob/d908a5b08e9ccbd2b41f8b399aa6cd919d5cb451/src/ci/github-actions/ci.yml#L309), and re-run the command mentioned at the top of that file.

since it passes the CI should i just remove the last commit and push again?

**Comment by cuviper** [comment]
Yeah, and can you also squash the 3rd commit, so we don't have commits removing and adding the same line?

In case you don't know how, `git rebase -i` should be straightforward -- just mark the 3rd commit as a fixup and delete the 4th commit altogether.

**Comment by mj10021** [comment]
> Yeah, and can you also squash the 3rd commit, so we don't have commits removing and adding the same line?
> 
> In case you don't know how, `git rebase -i` should be straightforward -- just mark the 3rd commit as a fixup and delete the 4th commit altogether.

yeah np on it rn

**Comment by cuviper** [comment]
OK, let's try it!

@bors r+

**Comment by nnethercote** [comment]
One tiny regression; this is fine.

@rustbot label: +perf-regression-triaged

**Pull request merged**
