### PR TITLE
Make `LLVMRustGetOrInsertGlobal` always return a `GlobalVariable`

### LINKED ISSUE #87813: LLVM ERROR: Invalid LLVMRustLinkage value!
### Code

https://github.com/haraldh/rust_llvm_error

```
❯ cd /tmp
❯ git clone https://github.com/haraldh/rust_llvm_error.git
❯ cd rust_llvm_error/
❯ cargo clean; cargo build
   Compiling scopeguard v1.1.0
   Compiling primordial v0.1.0
   Compiling lock_api v0.4.4
   Compiling spinning v0.1.0
   Compiling llvm_error v0.1.0 (/tmp/rust_llvm_error)
    Finished dev [unoptimized + debuginfo] target(s) in 1.20s

❯ cd ..
❯ mkdir -p /tmp/sfdgfdgdfgfdg/dfghfdgfd/fdfdgfdg/
❯ mv rust_llvm_error /tmp/sfdgfdgdfgfdg/dfghfdgfd/fdfdgfdg/
❯ cd /tmp/sfdgfdgdfgfdg/dfghfdgfd/fdfdgfdg/rust_llvm_error/
❯ cargo clean; cargo build
   Compiling scopeguard v1.1.0
   Compiling primordial v0.1.0
   Compiling lock_api v0.4.4
   Compiling spinning v0.1.0
   Compiling llvm_error v0.1.0 (/tmp/sfdgfdgdfgfdg/dfghfdgfd/fdfdgfdg/rust_llvm_error)
LLVM ERROR: Invalid LLVMRustLinkage value!
error: could not compile `llvm_error`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1
```

### Error output

```
LLVM ERROR: Invalid LLVMRustLinkage value!
error: could not compile `llvm_error`
```

### LINKED ISSUE #87933: `Invalid LLVMRustVisibility value!` error on `cargo build` after upgrading from 1.53.0 to 1.54.0
After upgrading our toolchains from `1.53.0` to `1.54.0`, our bootloader rust crates stopped building. 

Instead, the build command produced the error message `LLVM ERROR: Invalid LLVMRustVisibility value!`.

### Code

As these are a closed-source projects I cannot share any code publicly, but it can be shared privately if necessary.

I expected to see this happen: the build to succeed

Instead, this happened: the build failed

### Version it worked on

It most recently worked on: Rust 1.53

### Version with regression

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1
```

### Backtrace
The compiler did not crash or produce a backtrace.

</p>
</details>

### LINKED ISSUE #91050: llvm::Module::getOrInsertGlobal returns a Constant*, not always GlobalValue*
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1990657

In Fedora, one particular crate has been seeing non-deterministic errors or crashes in the compiler, and I was able to reproduce it with a `rustup`-installed compiler as well. Valgrind gave the following error report, even on runs that otherwise appeared to succeed.

<details><summary>Valgrind error</summary>
<p>

```
==325== Invalid read of size 1
==325==    at 0x93E6CF4: getVisibility (GlobalValue.h:229)
==325==    by 0x93E6CF4: LLVMGetVisibility (Core.cpp:1992)
==325==    by 0x4F6D05C: LLVMRustGetVisibility (RustWrapper.cpp:1602)
==325==    by 0x51AE144: rustc_codegen_llvm::mono_item::<impl rustc_codegen_llvm::context::CodegenCx>::should_assume_dso_local (mono_item.rs:106)
==325==    by 0x51A41DF: rustc_codegen_llvm::consts::<impl rustc_codegen_llvm::context::CodegenCx>::get_static (consts.rs:289)
==325==    by 0x51A1E05: rustc_codegen_llvm::common::<impl rustc_codegen_ssa::traits::consts::ConstMethods for rustc_codegen_llvm::context::CodegenCx>::scalar_to_backend (common.rs:267)
==325==    by 0x521D477: rustc_codegen_ssa::mir::operand::OperandRef<V>::from_const (operand.rs:85)
==325==    by 0x523D07A: eval_mir_constant_to_operand<rustc_codegen_llvm::builder::Builder> (constant.rs:20)
==325==    by 0x523D07A: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand (operand.rs:450)
==325==    by 0x5238B33: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue_operand (rvalue.rs:546)
==325==    by 0x522DB68: codegen_statement<rustc_codegen_llvm::builder::Builder> (statement.rs:24)
==325==    by 0x522DB68: codegen_block<rustc_codegen_llvm::builder::Builder> (block.rs:901)
==325==    by 0x522DB68: rustc_codegen_ssa::mir::codegen_mir (mod.rs:258)
==325==    by 0x51B6E09: rustc_codegen_ssa::base::codegen_instance (base.rs:342)
==325==    by 0x51E249C: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define (mono_item.rs:70)
==325==    by 0x51F713E: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen (base.rs:141)
==325==  Address 0x1734a400 is 8 bytes after a block of size 56 alloc'd
==325==    at 0x4840FF5: operator new(unsigned long) (vg_replace_malloc.c:417)
==325==    by 0x94DDFE4: allocateFixedOperandUser (User.cpp:127)
==325==    by 0x94DDFE4: llvm::User::operator new(unsigned long, unsigned int) (User.cpp:146)
==325==    by 0x93CE0C6: operator new (ConstantsContext.h:55)
==325==    by 0x93CE0C6: llvm::ConstantExprKeyType::create(llvm::Type*) const (ConstantsContext.h:612)
==325==    by 0x93DA482: create (ConstantsContext.h:715)
==325==    by 0x93DA482: llvm::ConstantUniqueMap<llvm::ConstantExpr>::getOrCreate(llvm::Type*, llvm::ConstantExprKeyType) (ConstantsContext.h:734)
==325==    by 0x93E02F2: getFoldedCast (Constants.cpp:1937)
==325==    by 0x93E02F2: getBitCast (Constants.cpp:2194)
==325==    by 0x93E02F2: llvm::ConstantExpr::getBitCast(llvm::Constant*, llvm::Type*, bool) (Constants.cpp:2185)
==325==    by 0x94AA7E0: llvm::Module::getOrInsertGlobal(llvm::StringRef, llvm::Type*) (Module.cpp:226)
==325==    by 0x51C67D5: declare_global (declare.rs:60)
==325==    by 0x51C67D5: rustc_codegen_llvm::consts::check_and_apply_linkage (consts.rs:157)
==325==    by 0x51A34BC: rustc_codegen_llvm::consts::<impl rustc_codegen_llvm::context::CodegenCx>::get_static (consts.rs:234)
==325==    by 0x51A1E05: rustc_codegen_llvm::common::<impl rustc_codegen_ssa::traits::consts::ConstMethods for rustc_codegen_llvm::context::CodegenCx>::scalar_to_backend (common.rs:267)
==325==    by 0x521D477: rustc_codegen_ssa::mir::operand::OperandRef<V>::from_const (operand.rs:85)
==325==    by 0x523D07A: eval_mir_constant_to_operand<rustc_codegen_llvm::builder::Builder> (constant.rs:20)
==325==    by 0x523D07A: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand (operand.rs:450)
==325==    by 0x5238B33: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue_operand (rvalue.rs:546)
```

</p>
</details>

Note that `llvm::Module::getOrInsertGlobal` returns a `Constant*`, but `LLVMGetVisibility` casts its argument to a `GlobalValue*`, which is a subclass. Most of the time you do get a `GlobalVariable*` (a further subclass), except when `getOrInsertGlobal` is given different types it instead returns a constant bitcast expression, as you can see in the error backtrace with `getBitCast`.

I ran a new rustc with LLVM assertions, and it does fail there trying to cast `GlobalValue*`:

```
rustc: /checkout/src/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = llvm::GlobalValue, Y = llvm::Value]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

So, casting the wrong pointer type is Undefined Behavior, and the non-reproducible aspect of this bug is just "luck" of whatever happens to be in memory there.

I'm not yet sure why `rustc` would have a type mismatch in what it's feeding `getOrInsertGlobal`, but my first suspicion is this `real_name` indirection in `check_and_apply_linkage`.

https://github.com/rust-lang/rust/blob/cc946fcd326f7d85d4af096efdc73538622568e9/compiler/rustc_codegen_llvm/src/consts.rs#L180-L200

### PR DESCRIPTION
**Pull request by cuviper**
`Module::getOrInsertGlobal` returns a `Constant*`, which is a super
class of `GlobalVariable`, but if the given type doesn't match an
existing declaration, it returns a bitcast of that global instead.
This causes UB when we pass that to `LLVMGetVisibility` which
unconditionally casts the opaque argument to a `GlobalValue*`.

Instead, we can do our own get-or-insert without worrying whether
existing types match exactly. It's not relevant when we're just trying
to get/set the linkage and visibility, and if types are needed we can
bitcast or error nicely from `rustc_codegen_llvm` instead.

Fixes #91050, fixes #87933, fixes #87813.

### CODE REVIEW

**Comment by cuviper** [comment]
cc @datdenkikniet @haraldh -- if you could confirm that this fixes your bugs, that would be great. I'll start a build:

@bors try

**Comment by cuviper** [comment]
cc @hellow554 was also testing those bugs.

**Comment by nagisa** [comment]
I went ahead and approved this because it looks correct to me regardless, and because I won't really have an opportunity to take a closer look at this later.

**Comment by nagisa** [comment]
Ah, actually, I do have a concern about what would happen with the code of the following shape (i.e. actual uses of the differently typed globals exist):

```rust
pub mod before {
    extern "C" {
        pub static GLOBAL1: [u8; 1];
    }

    pub unsafe fn do_something_with_array() -> u8 {
        GLOBAL1[0]
    }
}

pub mod inner {
    extern "C" {
        pub static GLOBAL1: u8;
    }

    pub unsafe fn call() -> u8 {
        GLOBAL1 + 42
    }
}
```

can we add a test like that too?

---

As I was busy coming up with the test case I built a compiler with this change, and indeed this case is problematic, building it with the following flags produces:

```
$ rustc test.rs --crate-type=rlib --emit=llvm-ir -Cno-prepopulate-passes
LLVM ERROR: Invalid LLVMRustVisibility value!
```



---

@bors r- for now

**Comment by cuviper** [comment]
> As I was busy coming up with the test case I built a compiler with this change, and indeed this case is problematic, building it with the following flags produces:
> 
> ```
> $ rustc test.rs --crate-type=rlib --emit=llvm-ir -Cno-prepopulate-passes
> LLVM ERROR: Invalid LLVMRustVisibility value!
> ```

Are you sure your `rustc` command used my change? I can reproduce that error with nightly, but my local build works.

**Comment by cuviper** [comment]
@nagisa I added your test variant.

**Comment by nagisa** [comment]
> Are you sure your rustc command used my change?

/me facepalms. `rustc` was the rustup rustc and not `./build/x86_64-unknown-linux-gnu/stage1/bin/rustc`.

@bors r+ Thanks!

**Comment by cuviper** [comment]
Moved the tests to appease tidy.

@bors r=nagisa

**Comment by datdenkikniet** [comment]
A little late to the party perhaps, but this PR does indeed seem to fix the issues we faced in #87933

It's slightly difficult to tell because the error was spurious, but I've cleaned/built about 10 times now and it hasn't produced an error once, which it do relatively consistently do before these changes.

**Comment by glandium** [comment]
Is it too late to get this in 1.57?

**Comment by cuviper** [comment]
It is very late for 1.57, but possibly not _too_ late -- @Mark-Simulacrum what do you think?

**Comment by nagisa** [comment]
Given that it is fixing a relatively longstanding regression I would personally prefer this to ride the :train2:.

**Comment by Mark-Simulacrum** [comment]
If it's nominated/accepted by beta backport quite soon (next ~72 hours), we can get it in, but not otherwise. I have no strong opinion or sense of the exact possibility for problems caused by this patch, though.

**Comment by cuviper** [comment]
I'm OK with @nagisa's opinion to let it wait through the normal release process, but I might still backport in Fedora for its bug.

**Pull request merged**
