### PR TITLE
Allow filtering what proof trees are dumped to stdout via a rustc attr

### PR DESCRIPTION
**Pull request by BoxyUwU**
Adds a `#![rustc_filter_proof_tree_dump("...")]` attribute that can be placed on the crate root to filter the output of `-Zdump-solver-proof-tree=always`. It works by only generating proof trees if the debug output of the root goal's predicate is the same as the string. It doesn't feel ideal although I wasn't sure how else to make something like this work- actually trying to parse goal syntax seemed far harder.

Ideally this would also work for `=on_error` but i haven't made that work yet. I was hoping this could be used to generate proof trees in ui tests but the output still seems kinda huge and its not deduplicated at all (the stdout file i commited literaly has the exact same proof tree Twice...) I'm not sure its actually worth adding `-Zdump-solver-proof-tree` to ui tests yet.

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/113763
probably just needs rebase + rebless

**Comment by Dylan-DPC** [comment]
@BoxyUwU any updates on this?

**Pull request closed without merging**
