### PR TITLE
Pass static crt to llvm cmake configuration

### PR DESCRIPTION
**Pull request by liranringel**
Solves https://github.com/rust-lang/rust/issues/40246

### CODE REVIEW

**Comment by liranringel** [comment]
?r @alexcrichton

**Comment by Mark-Simulacrum** [comment]
Are the dependency updates necessary, or unrelated?

r? @alexcrichton

**Comment by liranringel** [comment]
@Mark-Simulacrum they are necessary. See https://github.com/alexcrichton/gcc-rs/pull/159 and https://github.com/alexcrichton/cmake-rs/pull/31

**Comment by Mark-Simulacrum** [comment]
Sounds good. Just making sure.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
