### PR TITLE
Update stdarch submodule

### LINKED ISSUE #56483: LLVM assertion in simdnoise crate
The simdnoise crate [is failing to build](https://crater-reports.s3.amazonaws.com/beta-1.31-5/master%238940af3cea4a9a9deabcaf843b2f8cad9a83fc61/reg/simdnoise-2.3.6/log.txt) with an LLVM assertion:

```
rustc: /checkout/src/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp:118: static uint8_t (anonymous namespace)::X86MCCodeEmitter::ModRMByte(unsigned int, unsigned int, unsigned int): Assertion `Mod < 4 && RegOpcode < 8 && RM < 8 && "ModRM Fields out of range!"' failed.
```

This is not a regression, it's confirmed to also fail on 1.28.0 (alt builds are not available past that).

### PR DESCRIPTION
**Pull request by tmiasko**
Changes included:

* Use a bootstrap guard for modules with new target features
* Avoid calling intrinsics with invalid const arguments
* Avx512bw
* Avx512cd
* Add AVX512BITALG
* Add GFNI Intrinsics
* Add AVX512VPOPCNTDQ Intrinsics
* Add VPCLMULQDQ Intrinsics
* Avx512bw
* Reimplement `_xgetbv` with LLVM intrinsics
* Avx512bw
* Add reamained vmax and vmin via auto-generated code
* Add VAES intrinsics

Fixes #56483.

### CODE REVIEW

**Comment by tmiasko** [comment]
Spurious failure:

> LINK : fatal error LNK1201: error writing to program database 'D:\a\rust\rust\build\i686-pc-windows-msvc\test\run-make-fulldeps\override-aliased-flags\override-aliased-flags\main.pdb'; check for insufficient disk space, invalid path, or insufficient privilege

**Comment by rylev** [comment]
@tmiasko @Amanieu This change caused [lots of regressions in [the perf benchmark](https://perf.rust-lang.org/compare.html?start=fa416394275d2468d104b8f72ac31b1ddf7ee52e&end=8b3ee82eb68cb35030bb745c23f8aa76d9de5bee&stat=instructions:u). We should look into this to see if we can win some of the performance losses back.

**Pull request merged**
