### PR TITLE
Remove various double spaces in the libraries.

### PR DESCRIPTION
**Pull request by anden3**
I was just pretty bothered by this when reading the source for a function, and was suggested to check if this happened elsewhere.

### CODE REVIEW

**Comment by anden3** [comment]
cc @Dylan-DPC

**Comment by matthiaskrgr** [comment]
Should probably be squashed into a single commit, removing two spaces per commit seems kind of underkill

**Comment by anden3** [comment]
> Should probably be squashed into a single commit, removing two spaces per commit seems kind of underkill
Agreed, will squash before merging.

**Comment by Dylan-DPC** [comment]
thanks
@bors r+

**Comment by anden3** [comment]
I found some more, pushing another commit soon.

**Pull request merged**
