### PR TITLE
Turn `-Z incremental-verify-ich` on by default

### PR DESCRIPTION
**Pull request by Aaron1011**
Issue #82920 showed that the kind of bugs caught by this flag have
soundness implications.

### CODE REVIEW

**Comment by bjorn3** [comment]
Huge regressions up to 330% for incr-unchanged and 58% for incr-patched.

**Comment by lcnr** [comment]
i think these perf regressions are still somewhat acceptable depending on how much we expect to catch with this :thinking:

that's not a decision i want to make myself though, because this is not an area i have much expertise.

**Comment by matthiaskrgr** [comment]
Is it possible to verify incremental compilation with a crater run?

**Comment by Aaron1011** [comment]
@matthiaskrgr: If you mean proactively trying to find ICEs caused by this change - this is issue https://github.com/rust-lang/crater/issues/556, since we need to built a crate multiple times (the second time with an incremental cache).

If you mean doing that *instead* of enabling this option, then no. There are an enormous number of combinations of (incremental cache, changed code), and we have no hope of testing any appreciable fraction of them using Crater.

**Comment by Aaron1011** [comment]
cc @rust-lang/wg-incr-comp

**Comment by tgnottingham** [comment]
The `incremental_verify_ich` function is marked `#[cold]` and `#[inline(never)]`, and has debug traces. We could remove these to try to improve performance.

**Comment by Aaron1011** [comment]
The `debug!` statements are compiled out in builds without debug asserions. I'll try to removing the `#[cold]` and `#[inline(never)]` attributes, and change the `unlikely!` to `likely!`

**Comment by michaelwoerister** [comment]
I wonder if it would be an option to just check one fingerprint in a thousand (in a deterministic way so things are reproducible). We would not have the performance regression and would have at least a chance of catching cases like these.

I'm not sure I actually want to propose this `:)`

**Comment by Mark-Simulacrum** [comment]
I will note that while the instruction counts are considerably increased, wall times are only around 50% worse in the worst case (on a stress test of ctfe stress -- not really a representative one, either, generally speaking) -- and in the common case, only 10-15% worse. It may be that's an acceptable cost to pay for correctness, and if there's some mitigation we can apply, to bring it down to 5% or so in the common cases then it seems like we should at least land it for now to get some sense of "how broken" things are. It only affects incremental (and rebuilds at that, right?), so it's not going to affect most CI pipelines or default setting release builds, which are currently the slowest builds. A 5% hit is painful, but I'd much rather get an ICE than hidden miscompilations.

**Comment by Aaron1011** [comment]
As a result of this PR, we'll start getting some ICEs due to https://github.com/rust-lang/rust/issues/80691

**Comment by Aaron1011** [comment]
The performance impact is much smaller if we only re-hash the result when the query gets re-computed (not when we just load an existing result from disk). I've confirmed that this causes the reproducer in https://github.com/rust-lang/rust/issues/82920 to ICE instead of producing a miscompilation.

@Mark-Simulacrum: I think we should land this PR in its current form (since the performance impact appears strictly lower than the previous perf run), since we know that it would have prevented at least one case of incr-comp-induced miscompilation. We can then consider whether or not we gain anything from re-hashing results loaded from disk.

**Comment by Mark-Simulacrum** [comment]
I think it would be good to add a note in the comments explaining the kind of bug that leads to a verification failure (likely similar to the comments on https://github.com/rust-lang/rust/issues/82920 which narrowed down the cause of one bug).

r=me with that done, and I agree that we can follow up with more extensive fixes or better performance in the future.

**Pull request merged**
