### PR TITLE
Only copy LLVM into rust-dev with internal LLVM

### LINKED ISSUE #76572: rust-dev doesn't support building with external llvm
When building rustc-nightly (e2be5f568d1f60365b825530f5b5cb722460591b here), the build error inside RustDev Target with:

```
> RustDev { target: TargetSelection { triple: "x86_64-unknown-openbsd", file: None } }
Dist RustDev (x86_64-unknown-openbsd)
thread 'main' panicked at 'Error: File "/data/semarie/build-rust/build_dir/build/x86_64-unknown-openbsd/llvm/bin/llvm-config" not found!', src/bootstrap/lib.rs:1273:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
        finished in 0.205
```

The build is done with the following `config.toml`:

```
[build]
rustc = "/data/semarie/build-rust/install_dir/beta/bin/rustc"
cargo = "/data/semarie/build-rust/install_dir/beta/bin/cargo"
rustfmt = "/data/semarie/build-rust/install_dir/beta/bin/rustfmt"
python = "/usr/local/bin/python3"
gdb = "/usr/local/bin/egdb"
#docs = false
vendor = true
extended = true
verbose = 1

[install]
prefix = "/data/semarie/build-rust/install_dir/nightly"

[dist]
src-tarball = false

[rust]
channel = "nightly"
codegen-tests = false
verbose-tests = true

[target.x86_64-unknown-openbsd]
llvm-config = "/usr/local/bin/llvm-config"

[llvm]
static-libstdcpp = false
ninja = true
```

Please note that `llvm` is system wide installed.

I am a bit unsure about the exact purpose of RustDev. but it seems to me that it should be not build if llvm is external ?

Cc: @Mark-Simulacrum

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This avoids needing to figure out where to locate each of the components with an
external LLVM. This component isn't manifested for rustup consumption and
generally shouldn't matter for anyone except Rust's CI, so it is fine for it to not be
complete elsewhere.

Fixes #76572.

r? @alexcrichton

### CODE REVIEW

**Comment by semarie** [comment]
does it make sens to even build it for external llvm ? the tarball will be almost empty. But maybe it will be extended later ?

LlvmTools uses the following:
```rust
        /* run only if llvm-config isn't used */
        if let Some(config) = builder.config.target_config.get(&target) {
            if let Some(ref _s) = config.llvm_config {
                builder.info(&format!("Skipping LlvmTools ({}): external LLVM", target));
                return None;
            }
        }
```

**Comment by Mark-Simulacrum** [comment]
Yeah, I am thinking that we'll expand it eventually but for now I think it does indeed make sense to just skip it entirely.

**Comment by alexcrichton** [comment]
Hm I don't think I've kept up enough with this over the past, I'm not sure what `RustDev` is :(. Can you provide a small description of what it's used for?

**Comment by Mark-Simulacrum** [comment]
It's the component intended for aiding rustc development, specifically providing pre-compiled LLVMs to developers (along with llvm-config and header files, basically enough for librustc_llvm to compile and link to this LLVM). It was just added a few days ago in https://github.com/rust-lang/rust/pull/76332

**Comment by alexcrichton** [comment]
@bors: r+

Ok cool, makes sense to me!

**Pull request merged**
