### PR TITLE
Rust 2018: Disable catch_expr, not targeted for 2018 edition

### LINKED ISSUE #52604: `do catch` is accidentally stable in 2018 edition
This works with no `#![feature]`:
```rust
fn main() {
    let x: Option<_> = do catch { 4 };
}
```
https://play.rust-lang.org/?gist=ed21b1848a1114ed7f7fefc13bdb8880&version=nightly&mode=debug&edition=2018

I expect this to be fixed with https://github.com/rust-lang/rust/pull/52602, but wanted to file explicitly for tracking.

### PR DESCRIPTION
**Pull request by joshtriplett**
Fixes #52604

### CODE REVIEW

**Comment by joshtriplett** [comment]
Note that https://github.com/rust-lang/rust/pull/52602/ fixes this as well, as part of a full implementation of `try`; this separates out just the fix for the features in the edition.

**Comment by scottmcm** [comment]
@bors r+

(I don't think I have permissions to do this, but I also didn't think highfive would assign me, so let's see.)

**Review by scottmcm — APPROVED** [review]
This looks right to me, but I don't have reviewer privileges.

**Pull request merged**
