### PR TITLE
Remove rustc_const_stable attribute on const NOOP

### PR DESCRIPTION
**Pull request by eholk**
This was accidentally reintroduced while editing #133089.

r? dtolnay

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by tgross35** [comment]
That's interesting, maybe const stability on consts should be rejected? @RalfJung

**Comment by RalfJung** [comment]
Perma-unstable attributes like this often don't have the logic to reject them in all the places where they do nothing. It's a lot of work to add that logic everywhere. I hope @jdonszelmann's [work](https://github.com/rust-lang/compiler-team/issues/796) will make this easier.

**Pull request merged**
