### PR TITLE
Remove more Lrcs from queries

### PR DESCRIPTION
**Pull request by Zoxc**
Based on https://github.com/rust-lang/rust/pull/59545.

r? @eddyb

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 3c4e28e6354da9ee1a4d40f8bd3eee4d55bc8f61

**Review by eddyb — APPROVED** [review]
r=me

**Comment by lzutao** [comment]
For anyone interest, this PR is included in #59545 .

**Pull request closed without merging**
