### PR TITLE
Add doc for impl From in char_convert

### PR DESCRIPTION
**Pull request by phungleson**
As part of issue #51430 (cc @skade).

The impl is very simple, let me know if we need to go into any details.

### CODE REVIEW

**Comment by pietroalbini** [comment]
Ping from triage @skade! This PR needs your review.

**Comment by TimNN** [comment]
Ping from triage, @skade / @rust-lang/docs: This PR requires your review.

**Comment by GuillaumeGomez** [comment]
Please add examples (yes, even for this docs adds!).

**Comment by phungleson** [comment]
Hey, I am currently traveling, will look at this again in around 3 weeks.

**Review by frewsxcv — APPROVED** [review]
Thanks!

**Pull request merged**
