### PR TITLE
Implement `Copy` for `IoSlice`

### LINKED ISSUE #69395: `IoSlice` does not implement `Clone`
`IoSlice` (from `std::io`) does not implement the `Clone` trait. Is there a reason for this? Cloning can be safely simulated with `IoSlice::new(*slice)`, but the lack of the `Clone` trait prevents from using functions such as `Vec::<IoSlice>::extend_from_slice`.

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Resolves #69395

r? @sfackler

### CODE REVIEW

**Comment by sfackler** [comment]
@rfcbot fcp merge

Should be uncontroversial, but this is adding insta-stable impls of `Copy` and `Clone` to `IoSlice`.

**Comment by Dylan-DPC** [comment]
@KodrAus @SimonSapin @withoutboats waiting for your vote on the fcp above

**Comment by jplatte** [comment]
Should this have a milestone attached / get an entry in `RELEASES.md`? (those two are always done in conjunction, right?)

**Comment by sfackler** [comment]
I am not sure about milestone tracking, but it seems reasonable to add an entry in the release notes!

**Comment by Dylan-DPC** [comment]
cc @Centril on release notes / milestone tracking

**Comment by Centril** [comment]
If you add `relnotes` (you should) then you should always add the relevant nightly milestone as well.

**Pull request merged**
