### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #94817 (Release notes for 1.60.0)
 - #95431 (Stabilize total_cmp)
 - #95438 (Add SyncUnsafeCell.)
 - #95467 (Windows: Synchronize asynchronous pipe reads and writes)
 - #95588 (explicitly distinguish pointer::addr and pointer::expose_addr)
 - #95603 (Fix late-bound ICE in `dyn` return type suggestion)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=94817,95431,95438,95467,95588,95603)

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Sorry, that was not a spurious error. In #95467 I made a dumb mistake in calling convention. I pushed a commit to fix it.

**Comment by Dylan-DPC** [comment]
thanks

**Pull request closed without merging**
