### PR TITLE
interpret: fix vtable check debug assertion

### LINKED ISSUE #99605: Miri tests fail with debug assertions enabled
I thought I had tested the debug assertions that I added in https://github.com/rust-lang/rust/pull/99420, but it seems I hadn't tested them on enough code, because they do actually fail, for example:
```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Instance { def: VTableShim(DefId(2:3509 ~ core[3dde]::ops::function::FnOnce::call_once)), substs: [[closure@std::thread::Builder::spawn_unchecked_<[closure@tests/pass/weak_memory/weak.rs:38:20: 38:27], ()>::{closure#1}], ()] }`,
 right: `Instance { def: Item(WithOptConstParam { did: DefId(1:985 ~ std[636e]::thread::{impl#0}::spawn_unchecked_::{closure#1}), const_param_did: None }), substs: [ReErased, ReErased, [closure@tests/pass/weak_memory/weak.rs:38:20: 38:27], (), i32, extern "rust-call" fn(()), (std::thread::Thread, std::option::Option<std::sync::Arc<std::sync::Mutex<std::vec::Vec<u8>>>>, [closure@tests/pass/weak_memory/weak.rs:38:20: 38:27], std::sync::Arc<std::thread::Packet<()>>)] }`', /home/r/src/rust/rustc/compiler/rustc_const_eval/src/interpret/terminator.rs:600:21
```
That's this assertion:
https://github.com/rust-lang/rust/blob/41419e70366962c9a878bfe673ef4df38db6f7f1/compiler/rustc_const_eval/src/interpret/terminator.rs#L600
failing on this code:
```
note: the place in the program where the ICE was triggered
  --> /home/r/src/rust/rustc/library/alloc/src/boxed.rs:1935:9
   |
LL |         <F as FnOnce<Args>>::call_once(*self, args)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@eddyb looks like the check you proposed does not always hold?

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/99605
Thanks to @eddyb for suggesting the fix!

### CODE REVIEW

**Review by eddyb — APPROVED** [review]
LGTM/r=me - only one thing I wanted to ask before then though, is this testable on this side, or only in the miri repo?

For the record, I believe a minimal test would look something like this:
```rust
(Box::new(|| {}) as Box<dyn FnOnce()>)()
```
(just checked and there is indeed a `::{shim:vtable#0}` generated for such code)

**Comment by RalfJung** [comment]
>  is this testable on this side, or only in the miri repo?

Yeah it can be tested in a rustc checkout (with debug assertions enabled) via `./x.py test src/tools/miri --stage 1`. (Stage 0 will also work again soon.)

**Comment by eddyb** [comment]
> > is this testable on this side, or only in the miri repo?
> 
> Yeah it can be tested in a rustc checkout (with debug assertions enabled)

Sorry, I meant whether it's possible to *add a test* in `rust-lang/rust` at all, for this situation.
But I suppose that would only be the case if CTFE could cause a virtual call?

**Comment by RalfJung** [comment]
Ah I see. Yeah I don't think CTFE can reach this... well, it could with `-Zunleash-the-miri-inside-of-you` I guess?

@bors r-

**Comment by RalfJung** [comment]
No that won't work, it still dynamically checks that we only call `const fn`.

@bors r=eddyb

**Pull request merged**
