### PR TITLE
Bubble up an overflow error so that rustdoc can ignore it

### LINKED ISSUE #54524: Building diesel documentation fails
After https://github.com/rust-lang/rust/issues/52545 is fixed now, I've tried to build diesels documentation and failed with the following error:
```
 Documenting diesel v1.3.3 (/home/weiznich/Dokumente/rust/diesel/diesel)
error[E0275]: overflow evaluating the requirement `<&_ as insertable::Insertable<_>>::Values`
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&_, &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(_, _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(_, _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((_, _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((_, _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((_, _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((_, _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_
, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _,
_, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _,
 _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _,
 _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _
, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _
, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _,
_, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _,
_, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _,
 _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _,
 _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _
, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _
, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _),
_, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _),
_, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _),
 _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _),
 _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)
, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)
, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&((((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _
), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&(((((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _
), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `(&(((((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _,
_), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), &_, &_, &_, &_)`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&((((((((((((((((((((_, _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _,
_), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _), _, _, _, _)`
…
```

Note that a normal build of diesel succeeds and also all doc tests are passing.

rustc version: rustc 1.30.0-nightly (4591a245c 2018-09-22)
rustdoc version: rustdoc 1.30.0-nightly (4591a245c 2018-09-22)
diesel version: [git master at commit 42d5b831](https://github.com/diesel-rs/diesel/commit/42d5b831ac6b407c74a3659653f5b9d171730851)

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #54524

Idk how to write a test for this, other than trying to minimize the entire diesel crate. If desirable I will do that.

Note that there are many other such overflow errors hiding out there. Should we try to proactively eliminate them or do we just whack-a-mole them?

cc @GuillaumeGomez 

r? @nikomatsakis

### CODE REVIEW

**Comment by pnkfelix** [comment]
(I personally vote for whack-a-mole, but what do I know...)

**Comment by nikomatsakis** [comment]
We should whack-a-mole -- the chalk efforts will make overflow "not a thing"

**Comment by kennytm** [comment]
@bors retry 

30 min timeout

**Comment by oli-obk** [comment]
some test segfaulted (signal 11). No idea how this PR could cause it

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout

**Comment by kennytm** [comment]
@rust-timer build 1c953cdf998080d5457b3453ad1f0ee5636539b4

I find it strange this keeps timing out. 

@bors retry

**Pull request merged**
