### PR TITLE
[Experiment] reduce allocations in exhaustiveness checking

### PR DESCRIPTION
**Pull request by Nadrieril**
I'm playing with how to structure the matrix to see if I can squeeze good perfs out of it. So far this stores the matrix by columns first instead of by rows, which makes it possible to mutate a same matrix instead of rebuilding one every iteration.

I'm making this so that I can get proper perf runs; there's only so much I can measure locally.

r? @ghost

### CODE REVIEW

**Comment by Nadrieril** [comment]
And I have perf rights now :3

@bors try @rust-timer queue

**Comment by Nadrieril** [comment]
Good, this doesn't noticeably affect benches that aren't match-specific. I've got some more ideas to try, I'll leave this open while I get them to work

**Comment by jyn514** [comment]
@Nadrieril do you plan to keep working on this? It looks like the perf impact is not great :/

**Comment by Nadrieril** [comment]
Yeah no I gave up indeed, it wasn't worth it. Forgot to close this.

**Pull request closed without merging**
