### PR TITLE
[WIP] add check if lints belong to an external macro

### LINKED ISSUE #48855: Add macro checks to lints
From https://github.com/rust-lang/rust/issues/48385

Many of our lints trigger even when the code is within a macro defined by an external crate. They should include macro checks.

Clippy has [a function](https://github.com/rust-lang-nursery/rust-clippy/blob/a7407f9acc2e216dee23fd5e4fc2ab9b01e4d77b/clippy_lints/src/utils/mod.rs#L67-L95) for this already.

We should include this in librustc::lint somewhere, and use it for various lints. It should _not_ be used for future compat lints.

One possible thing to do here is to work it into the lint framework itself, so that non-future-compat lints which are triggered on macro spans will not actually be emitted.

We should still have the helper function since some lints may involve multiple important spans so they need the ability to check them all.

Ideally there would be a way to turn this off, though -- in case you want to find issues in your macros. It's a tricky problem.

Willing to mentor the basic issue of importing the macro checks and applying them in most lints (or working it into the framework).

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Closes #48855 

r? @Manishearth

### CODE REVIEW

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363462251). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612901/612901), completed with 4871 local objects.
---
[00:00:46] configure: rust.quiet-tests     := True
---
[00:04:41] tidy error: /checkout/src/test/ui/in-band-lifetimes/ellided-lifetimes-macro-checks.rs: missing trailing newline
[00:04:42] some tidy checks failed
[00:04:42]
[00:04:42]
[00:04:42] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:42] expected success, got: exit code: 1
[00:04:42]
[00:04:42]
[00:04:42] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:42] Build completed unsuccessfully in 0:02:00
[00:04:42] Makefile:79: recipe for target 'tidy' failed
[00:04:42] make: *** [tidy] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:01a65ed8:start=1523099207403251722,finish=1523099207409899545,duration=6647823
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:26093c46
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:26093c46:start=1523099207416118481,finish=1523099207421918945,duration=5800464
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:00677a71
$ dmesg | grep -i kill
[   11.691344] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363475679). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612958/612958), completed with 4866 local objects.
---
[00:00:43] configure: rust.quiet-tests     := True
---
[00:07:13] error[E0432]: unresolved import `codemap`
[00:07:13]   --> librustc/lint/mod.rs:57:5
[00:07:13]    |
[00:07:13] 57 | use codemap::{ExpnFormat, ExpnInfo, Span };
[00:07:13]    |     ^^^^^^^ Did you mean `syntax::codemap`?
[00:07:13]
[00:07:14] error[E0433]: failed to resolve. Use of undeclared type or module `lint`
[00:07:14]    --> librustc/lint/context.rs:469:13
[00:07:14]     |
[00:07:14] 469 |         if !lint::in_external_macro(lint, span) {
[00:07:14]     |             ^^^^ Use of undeclared type or module `lint`
[00:07:14]
[00:07:17] error: unused import: `Span`
[00:07:17]   --> librustc/lint/mod.rs:57:37
[00:07:17]    |
[00:07:17] 57 | use codemap::{ExpnFormat, ExpnInfo, Span };
---
[00:07:17]    = note: #[deny(unused_imports)] implied by #[deny(warnings)]
[00:07:17]
gnu/release/deps/libbitflags-e01ce88b04783514.rlib --extern serialize=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libserialize-f27fded04dd31022.so --extern serialize=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libserialize-f27fded04dd31022.rlib --extern log=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/liblog-7eebd272275b441b.rlib --extern fmt_macros=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libfmt_macros-5106459147843225.so --extern byteorder=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libbyteorder-f04ca02424a68c4e.rlib --extern rustc_data_structures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_data_structures-1e725c22de2888b8.so --extern backtrace=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libbacktrace-a7efadae36f54a3c.rlib --extern rustc_apfloat=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_apfloat-b23276248c684a7d.rlib --extern flate2=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libflate2-0249ed74490015f9.rlib --extern syntax_pos=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libsyntax_pos-069d1433ad059ff1.so --extern lazy_static=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/liblazy_static-3c1d922a28d91411.rlib --extern jobserver=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libjobserver-3c385cb05f9c08fa.rlib --extern tempdir=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libtempdir-728fcbc86125f341.rlib --extern proc_macro=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libproc_macro-414d7e12269f768c.so --extern rustc_const_math=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_const_math-2cbdd37d611532dc.so -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/backtrace-sys-751752dec0960570/out/.libs -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/miniz-sys-07c608814ba8d6ba/out` (exit code: 101)
[00:07:52] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" " jemalloc" "--manifest-path" "/checkout/src/rustc/Cargo.toml" "--message-format" "json"
[00:07:52] expected success, got: exit code: 101
[00:07:52] thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1085:9
[00:07:52] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:07:52] travis_fold:end:stage0-rustc
[00:07:52] travis_time:end:stage0-rustc:start=1523104033367956872,finish=1523104230584479106,duration=197216522234
[00:07:52] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:07:52] Build completed unsuccessfully in 0:03:30
[00:07:52] Makefile:28: recipe for target 'all' failed
[00:07:52] make: *** [all] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or di
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by Manishearth** [comment]
Alright, this is a good first step -- now, the LintStore contains a hashmap of future incompatibility lints; we should always lint for these, regardless of the macro. So check the lint id against that.

**Comment by pietroalbini** [comment]
Ping from triage @Dylan-DPC! The reviewer requested some changes, could you implement them in the near future?

**Comment by Dylan-DPC** [comment]
Yes sure. Will add them in a few days :+1:

**Comment by Dylan-DPC** [comment]
@Manishearth I don't have access to the `LintStore` in the place where i'm [checking](https://github.com/rust-lang/rust/pull/49755/files#diff-771d6215d1fb5e7f5503514f9895f7bdR469) the lint. Any clues?

**Comment by pietroalbini** [comment]
Ping from triage @Manishearth! The author needs a bit of help.

**Comment by Manishearth** [comment]
Sure you do -- `.lints()`

**Comment by shepmaster** [comment]
Ping from triage, @Dylan-DPC ! You have test failures to address.

**Comment by pietroalbini** [comment]
Ping from triage @Dylan-DPC! You have _other_ failures to address.

**Comment by pietroalbini** [comment]
Thank you for this PR @Dylan-DPC! Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please **reopen** this PR, we'll be happy to review it again!

**Comment by Dylan-DPC** [comment]
Oops sorry, got busy and demotivated to complete this. Sure no problems :smile:

**Pull request closed without merging**
