### PR TITLE
Adjust argument type for mutable with_metadata_of (#75091)

### PR DESCRIPTION
**Pull request by 197g**
The method takes two pointer arguments: one `self` supplying the pointer value, and a second pointer supplying the metadata.

The new parameter type more clearly reflects the actual requirements. The provenance of the metadata parameter is disregarded completely. Using a mutable pointer in the call site can be coerced to a const pointer while the reverse is not true.

In some cases, the current parameter type can thus lead to a very slightly confusing additional cast. [Example](https://github.com/HeroicKatora/static-alloc/commit/cad93775eb9adc62f744651e3abf19513e69e7d0).

```rust
// Manually taking an unsized object from a `ManuallyDrop` into another allocation.
let val: &core::mem::ManuallyDrop<T> = …;

let ptr = val as *const _ as *mut T;
let ptr = uninit.as_ptr().with_metadata_of(ptr);
```

This could then instead be simplified to:

```rust
// Manually taking an unsized object from a `ManuallyDrop` into another allocation.
let val: &core::mem::ManuallyDrop<T> = …;

let ptr = uninit.as_ptr().with_metadata_of(&**val);
```

Tracking issue: https://github.com/rust-lang/rust/issues/75091

@dtolnay you're reviewed #95249, would you mind chiming in?

### CODE REVIEW

**Comment by HeroicKatora** [comment]
r? dtolnay

**Review by dtolnay — APPROVED** [review]
:) I like it. Thank you for sharing the real-world example, that is compelling.

**Comment by HeroicKatora** [comment]
@dtolnay Would you also adjust [the tracking issue](https://github.com/rust-lang/rust/issues/75091#issue-671868145) to reflect the current API when the merge has gone through? I'm afraid it's somewhat out-of-date and doesn't reflect the full history.

**Comment by dtolnay** [comment]
Done.

**Pull request merged**
