### PR TITLE
Account for doc comments coming from proc macros without spans

### LINKED ISSUE #63821: rustdoc crashes on nightly nightly-2019-08-22
`cargo doc` crashes on nightly (`nightly-2019-08-22`) and also on stable (`1.37.0`) with "nightly" features turned on via `RUSTC_BOOSTRAP=1`. It does not trigger on stable without `RUSTC_BOOTSTRAP=1` flag.

Here is the output I'm getting:
```
thread 'rustc' panicked at 'could not find markdown in source', src/libcore/option.rs:1166:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (e44fdf979 2019-08-21) running on x86_64-apple-darwin

error: Could not document `rustdoc-crash`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-name rustdoc_crash src/lib.rs -o /Users/idubrov/Projects/rustdoc-crash/target/doc --color always -L dependency=/Users/idubrov/Projects/rustdoc-crash/target/debug/deps --extern derive=/Users/idubrov/Projects/rustdoc-crash/target/debug/deps/libderive-aeb93296cea2c806.dylib` (exit code: 1)
```

I created a small repro case + README.md here: https://github.com/idubrov/rustdoc-crash (it only happens when there is a certain combination of procedural macros, so I cannot make it a single file).

### PR DESCRIPTION
**Pull request by estebank**
Fix https://github.com/rust-lang/rust/issues/63821.

### CODE REVIEW

**Comment by Centril** [comment]
A regression test would be nice =)

**Comment by Centril** [comment]
@estebank Ah; fwiw, you can put `[WIP]` in the title :)

**Comment by Centril** [comment]
I have never reviewed anything of importance in rustdoc.
r? @ollie27

**Comment by nikomatsakis** [comment]
Report from compiler triage meeting: Accepted for beta backport (once it lands)

**Comment by estebank** [comment]
Ping @rust-lang/rustdoc?

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Pull request merged**
