### PR TITLE
rustc_transmute: Directly use types from rustc_abi

### PR DESCRIPTION
**Pull request by workingjubilee**
Using the reexport from rustc_target is not necessary here, so use rustc_abi directly.

### CODE REVIEW

**Comment by workingjubilee** [comment]
well!

r? compiler

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me when green

**Comment by RalfJung** [comment]
Should we get rid of these reexports? RA isn't great at dealing with them so it often ends up adding the `rustc_abi` imports... and then we get build failures since that crate isn't listed as a dependency.

**Comment by workingjubilee** [comment]
> Should we get rid of these reexports? RA isn't great at dealing with them so it often ends up adding the `rustc_abi` imports... and then we get build failures since that crate isn't listed as a dependency.

...well, we _want_ the `rustc_abi` imports. It's the `rustc_target` reexports that we don't want.

**Comment by workingjubilee** [comment]
But yes incrementing towards the final state where rustc_target reexports nothing, at least publicly, from rustc_abi, is the primary aim of most of my recent flurry of PRs.

**Pull request merged**
