### PR TITLE
[rustdoc] stabilize cfg(doctest)

### LINKED ISSUE #62210: Tracking issue for `cfg(doctest)`
This feature allows you to restrict items to only be compiled when rustdoc is collecting doctests. This allows you to isolate certain doctests that will be tested, but not shown in documentation - for example, if you need to use `compile_fail`, or if you're testing the samples in your README file. I'm still putting the PR that adds this feature in - i will update this issue description when it is posted.

We had previously set `cfg(test)` when collecting doctests, starting in https://github.com/rust-lang/rust/pull/59940, but this caused issues with libcore that caused all its doctests to be ignored, so that was reverted in https://github.com/rust-lang/rust/pull/61199. This feature is the replacement for that, currently unstable while we ensure the semantics.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #62210.

Since we removed rustdoc from providing `cfg(test)` on test runs, it's been replaced by `cfg(doctest)`. It'd be nice to have it in not too far in the future. :)

cc @rust-lang/rustdoc 

r? @ollie27

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Ping @rust-lang/rustdoc 

r? @Mark-Simulacrum 

Btw, like said multiple times, a few (very big) crates depend on this feature because it's replacing `cfg(test)` for rustdoc. Having it hit stable as soon as possible is something I'd really like.

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/rust/issues/62210#issuecomment-520135434: AFAIK no decision was made yet by the relevant team(s) (whichever ones that would be) which approach is the right one. The revert happened because just adding `--cfg test` in rustdoc test collection broke something that worked since pre-1.0 (libcore doc tests) -- in that case the process is to first back out the breaking change, and then discuss whether this is acceptable breakage or not.

**Comment by Mark-Simulacrum** [comment]
I think the implementation here looks good. However, I agree that the discussion @RalfJung notes should happen prior to landing stabilization.

**Comment by GuillaumeGomez** [comment]
The original `cfg(test)` has already been reverted which is why I opened this PR (so no breakage considering nothing has been stabilized). I'm still waiting for team approval though.

**Pull request closed without merging**
