### PR TITLE
update anyhow

### LINKED ISSUE #100062: `./x.py test src/test/ui` fails to build compiletest
```
$ ./x.py test src/test/ui --test-args align --bless
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.05s
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.20s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.34s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.17s
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 tool compiletest (x86_64-unknown-linux-gnu)
   Compiling proc-macro2 v1.0.37
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.91
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.126
   Compiling serde_derive v1.0.140
   Compiling memchr v2.5.0
   Compiling lazy_static v1.4.0
   Compiling autocfg v1.1.0
   Compiling regex-syntax v0.6.26
   Compiling parking_lot_core v0.8.5
   Compiling ryu v1.0.5
   Compiling serde v1.0.140
   Compiling serde_json v1.0.82
   Compiling anyhow v1.0.51
   Compiling smallvec v1.8.1
   Compiling log v0.4.14
   Compiling scopeguard v1.1.0
   Compiling once_cell v1.12.0
   Compiling itoa v1.0.2
   Compiling pin-project-lite v0.2.8
   Compiling diff v0.1.13
   Compiling unicode-width v0.1.8
   Compiling ansi_term v0.12.1
   Compiling same-file v1.0.6
   Compiling glob v0.3.0
   Compiling instant v0.1.12
   Compiling tracing-core v0.1.21
   Compiling sharded-slab v0.1.1
   Compiling lock_api v0.4.7
   Compiling thread_local v1.1.4
   Compiling getopts v0.2.21
   Compiling walkdir v2.3.2
   Compiling unified-diff v0.2.1
   Compiling regex-automata v0.1.10
error[E0407]: method `backtrace` is not a member of trait `StdError`
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/context.rs:127:5
    |
127 | /     fn backtrace(&self) -> Option<&Backtrace> {
128 | |         self.error.backtrace()
129 | |     }
    | |_____^ not a member of trait `StdError`

error[E0407]: method `backtrace` is not a member of trait `StdError`
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/context.rs:141:5
    |
141 | /     fn backtrace(&self) -> Option<&Backtrace> {
142 | |         Some(self.error.backtrace())
143 | |     }
    | |_____^ not a member of trait `StdError`

error[E0407]: method `backtrace` is not a member of trait `StdError`
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/error.rs:904:5
    |
904 | /     fn backtrace(&self) -> Option<&Backtrace> {
905 | |         Some(unsafe { ErrorImpl::backtrace(self.erase()) })
906 | |     }
    | |_____^ not a member of trait `StdError`

error[E0407]: method `backtrace` is not a member of trait `StdError`
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/wrapper.rs:71:5
   |
71 | /     fn backtrace(&self) -> Option<&crate::backtrace::Backtrace> {
72 | |         self.0.backtrace()
73 | |     }
   | |_____^ not a member of trait `StdError`

   Compiling aho-corasick v0.7.18
error[E0599]: no method named `backtrace` found for type parameter `E` in the current scope
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/backtrace.rs:41:20
   |
39 | / macro_rules! backtrace_if_absent {
40 | |     ($err:expr) => {
41 | |         match $err.backtrace() {
   | |                    ^^^^^^^^^ method not found in `E`
42 | |             Some(_) => None,
...  |
45 | |     };
46 | | }
   | |_- in this expansion of `backtrace_if_absent!`
   |
  ::: /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/context.rs:27:29
   |
27 |               let backtrace = backtrace_if_absent!(self);
   |                               -------------------------- in this macro invocation

error[E0599]: no method named `backtrace` found for type parameter `E` in the current scope
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/context.rs:128:20
    |
128 |         self.error.backtrace()
    |                    ^^^^^^^^^ method not found in `E`

error[E0599]: no method named `backtrace` found for type parameter `E` in the current scope
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/backtrace.rs:41:20
   |
39 | / macro_rules! backtrace_if_absent {
40 | |     ($err:expr) => {
41 | |         match $err.backtrace() {
   | |                    ^^^^^^^^^ method not found in `E`
42 | |             Some(_) => None,
...  |
45 | |     };
46 | | }
   | |_- in this expansion of `backtrace_if_absent!`
   |
  ::: /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/error.rs:33:25
   |
33 |           let backtrace = backtrace_if_absent!(error);
   |                           --------------------------- in this macro invocation

error[E0599]: no method named `backtrace` found for type parameter `E` in the current scope
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/backtrace.rs:41:20
    |
39  | / macro_rules! backtrace_if_absent {
40  | |     ($err:expr) => {
41  | |         match $err.backtrace() {
    | |                    ^^^^^^^^^ method not found in `E`
42  | |             Some(_) => None,
...   |
45  | |     };
46  | | }
    | |_- in this expansion of `backtrace_if_absent!`
    |
   ::: /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/error.rs:530:25
    |
530 |           let backtrace = backtrace_if_absent!(error);
    |                           --------------------------- in this macro invocation

error[E0599]: no method named `backtrace` found for reference `&(dyn std::error::Error + Send + Sync + 'static)` in the current scope
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/error.rs:886:42
    |
886 |                 return Self::error(this).backtrace();
    |                                          ^^^^^^^^^ method not found in `&(dyn std::error::Error + Send + Sync + 'static)`

   Compiling quote v1.0.18
error[E0599]: no method named `backtrace` found for struct `Box<(dyn std::error::Error + Send + Sync + 'static)>` in the current scope
   --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/backtrace.rs:41:20
    |
39  | / macro_rules! backtrace_if_absent {
40  | |     ($err:expr) => {
41  | |         match $err.backtrace() {
    | |                    ^^^^^^^^^ method not found in `Box<(dyn std::error::Error + Send + Sync + 'static)>`
42  | |             Some(_) => None,
...   |
45  | |     };
46  | | }
    | |_- in this expansion of `backtrace_if_absent!`
    |
   ::: /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/kind.rs:113:25
    |
113 |           let backtrace = backtrace_if_absent!(error);
    |                           --------------------------- in this macro invocation

   Compiling atty v0.2.14
error[E0599]: no method named `backtrace` found for struct `Box<(dyn std::error::Error + Send + Sync + 'static)>` in the current scope
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/wrapper.rs:72:16
   |
72 |         self.0.backtrace()
   |                ^^^^^^^^^ method not found in `Box<(dyn std::error::Error + Send + Sync + 'static)>`

Some errors have detailed explanations: E0407, E0599.
For more information about an error, try `rustc --explain E0407`.
error: could not compile `anyhow` due to 11 previous errors
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:00:11
```

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/100062 by incorporating https://github.com/dtolnay/anyhow/pull/249

### CODE REVIEW

**Comment by bjorn3** [comment]
Yeah, cg_clif's Cargo.lock should probably be updated too.

**Comment by RalfJung** [comment]
When I do `cargo update -p anyhow` in `compiler/rustc_codegen_cranelift/` it only updates to 1.0.59, to 1.0.60... no idea what's going on, I guess I better don't touch that lockfile.

**Comment by bjorn3** [comment]
> When I do cargo update -p anyhow in compiler/rustc_codegen_cranelift/ it only updates to 1.0.59, to 1.0.60... no idea what's going on, I guess I better don't touch that lockfile.

1.0.60 has been yanked. That is why cargo didn't update it.

**Comment by RalfJung** [comment]
Ah, interesting. It is working fine here though and fixed our issue... very strange.

**Pull request merged**
