### PR TITLE
Require rlibs for dependent crates when linking static executables

### PR DESCRIPTION
**Pull request by smaeul**
This handles the case for `CrateTypeExecutable` and `+crt_static`. I reworked the match block to avoid duplicating the `attempt_static` and error checking code again (this case would have been a copy of the `CrateTypeCdylib`/`CrateTypeStaticlib` case).

On `linux-musl` targets where `std` was built with `crt_static = false` in `config.toml`, this change brings the test suite from entirely failing to mostly passing.

This change should not affect behavior for other crate types, or for targets which do not respect `+crt_static`.

### CODE REVIEW

**Comment by aidanhs** [comment]
This this caused a failure in #44550 (best guess)
@bors r- rollup-
```
[00:53:43] ---- [compile-fail] compile-fail/rmeta_lib.rs stdout ----
[00:53:43] 	
[00:53:43] error: error pattern ' crate `rmeta_meta` required to be available in rlib, but it was not available' not found!
```

**Comment by smaeul** [comment]
It looks like the compile failure is happening in the intended way, but the error message is different because it's being caught earlier. Should I just change the expected error message in the test?

**Comment by alexcrichton** [comment]
If possible yeah let's just get the errors to emit through a common path to ensure that they're the same

**Comment by carols10cents** [comment]
> [00:03:44] tidy error: /checkout/src/test/compile-fail/rmeta_lib.rs:13: line longer than 100 chars

tidy error for you @smaeul!

**Comment by smaeul** [comment]
How do I fix that without making the error message shorter?

**Comment by kennytm** [comment]
@smaeul You could remove the spaces around `error-pattern`. The line is now exactly 100 chars.

```
//error-pattern:crate `rmeta_meta` required to be available in rlib format, but it was not available
```

**Comment by arielb1** [comment]
Test failure:

```
[00:49:18] error: error pattern ' dependency `cdylib_dep` not found in rlib format' not found!
[00:49:18] status: exit code: 101
[00:49:18] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/cdylib-deps-must-be-static.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/cdylib-deps-must-be-static.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/cdylib-deps-must-be-static.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux" "-A" "unused"
[00:49:18] stdout:
[00:49:18] ------------------------------------------
[00:49:18] 
[00:49:18] ------------------------------------------
[00:49:18] stderr:
[00:49:18] ------------------------------------------
[00:49:18] warning: unused extern crate
[00:49:18]   --> /checkout/src/test/compile-fail/cdylib-deps-must-be-static.rs:18:1
[00:49:18]    |
[00:49:18] 18 | extern crate cdylib_dep;
[00:49:18]    | ^^^^^^^^^^^^^^^^^^^^^^^^
[00:49:18]    |
[00:49:18]    = note: #[warn(unused_extern_crates)] on by default
[00:49:18] 
[00:49:18] error: crate `cdylib_dep` required to be available in rlib format, but it was not available in this form
[00:49:18] 
[00:49:18] error: aborting due to previous error
[00:49:18] 
[00:49:18] 
[00:49:18] ------------------------------------------
[00:49:18] 
[00:49:18] thread '[compile-fail] compile-fail/cdylib-deps-must-be-static.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2433:8
[00:49:18] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:49:18] 
[00:49:18] 
[00:49:18] failures:
[00:49:18]     [compile-fail] compile-fail/cdylib-deps-must-be-static.rs
[00:49:18] 
[00:49:18] test result: [31mFAILED(B[m. 2736 passed; 1 failed; 13 ignored; 0 measured; 0 filtered out
[00:49:18] 
[00:49:18] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:323:21
[00:49:18] 
```

**Comment by carols10cents** [comment]
This looks like it's ready for rereview @alexcrichton !

**Pull request merged**
