### PR TITLE
Allow for parentheses after macro intra-doc-links

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by ollie27** [comment]
Shouldn't a test be added for this?

**Comment by GuillaumeGomez** [comment]
Outch, good catch @ollie27 !

Please add a test @Manishearth.

@bors: r-

**Comment by Manishearth** [comment]
@ollie27 we mostly don't have tests for this kind of thing, i was considering adding them separately, but i can do that

**Comment by Manishearth** [comment]
I was wrong, we do test this, it was just part of another test.

**Review by jyn514 — APPROVED** [review]

**Comment by Manishearth** [comment]
@bors p=5

trying something

**Pull request merged**
