### PR TITLE
update clippy submodule to a72e786c 

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/pull/53824 broke the clippy build so this won't pass CI in its current state.

I filed a PR to fix clippy and will update this PR once that is merged into clippy.

**Comment by kennytm** [comment]
Ok.

@bors r-

**Comment by matthiaskrgr** [comment]
rebased to include fix-pr

**Comment by kennytm** [comment]
Needs to update Cargo.lock...

**Comment by matthiaskrgr** [comment]
Ah yes, sorry, I forgot to `git add` that..

**Pull request merged**
