### PR TITLE
Add overflow checking for `str::get` with inclusive ranges

### PR DESCRIPTION
**Pull request by scottmcm**
Fixes https://github.com/rust-lang/rust/issues/42401

Two commits here:

1. The first makes `str::index` just call `SliceIndex<str>::index`.  It's intended to have no behavior change, except where the two methods were inconsistent.
2. The second actually adds the overflow checking to `get(_mut)` (and tests for it)

### CODE REVIEW

**Comment by arielb1** [comment]
Thanks for the PR @scottmcm! @aturon (or someone else) should be reviewing your PR soon.

**Comment by carols10cents** [comment]
Aturon's on vacation this week, sorry this fell through the cracks last week! Let's try...

r? @nikomatsakis

**Pull request merged**
