### PR TITLE
Rollup of 23 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
- Successful merges: #48374, #48596, #48759, #48939, #49029, #49069, #49093, #49109, #49117, #49140, #49158, #49188, #49189, #49209, #49211, #49216, #49225, #49231, #49234, #49242, #49244, #49105, #49038
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
Maybe https://github.com/rust-lang/rust/pull/48786 at caus?

<details>

```
[01:23:25] 

[01:23:25] failures:

[01:23:25] 

[01:23:25] ---- [debuginfo-lldb] debuginfo/macro-stepping.rs stdout ----

[01:23:25] 	NOTE: compiletest thinks it is using LLDB version 902

[01:23:25] 

[01:23:25] error: line not found in debugger output: [...]#loc5[...]

[01:23:25] status: exit code: 0

[01:23:25] command: "/usr/bin/python" "/Users/travis/build/rust-lang/rust/src/etc/lldb_batchmode.py" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo/macro-stepping.stage2-i686-apple-darwin" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo/macro-stepping.debugger.script"

[01:23:25] stdout:

[01:23:25] ------------------------------------------

[01:23:25] LLDB batch-mode script

[01:23:25] ----------------------

[01:23:25] Debugger commands script is '/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo/macro-stepping.debugger.script'.

[01:23:25] Target executable is '/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo/macro-stepping.stage2-i686-apple-darwin'.

[01:23:25] Current working directory is '/Users/travis/build/rust-lang/rust'

[01:23:25] Creating a target for '/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo/macro-stepping.stage2-i686-apple-darwin'

[01:23:25] settings set auto-confirm true

[01:23:25] 

[01:23:25] version

[01:23:25] lldb-902.0.73.1 Swift-4.1 

[01:23:25] command script import /Users/travis/build/rust-lang/rust/./src/etc/lldb_rust_formatters.py

[01:23:25] type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust

[01:23:25] type category enable Rust

[01:23:25] 

[01:23:25] breakpoint set --file 'macro-stepping.rs' --line 111

[01:23:25] Breakpoint 1: where = macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:111, address = 0x00003030 

[01:23:25] breakpoint set --file 'macro-stepping.rs' --line 126

[01:23:25] Breakpoint 2: where = macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba + 402 at macro-stepping.rs:126, address = 0x000031c2 

[01:23:25] set set stop-line-count-before 0

[01:23:25] 

[01:23:25] set set stop-line-count-after 1

[01:23:25] 

[01:23:25] run

[01:23:25] Hit breakpoint 1.1: where = macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:111, address = 0x00003030, resolved, hit count = 1 

[01:23:25] Process 44098 stopped * thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1 frame #0: 0x00003030 macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:111 -> 111 zzz(); // #break 112 Target 0: (macro-stepping.stage2-i686-apple-darwin) stopped. Process 44098 launched: '/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo/macro-stepping.stage2-i686-apple-darwin' (i386) 

[01:23:25] next

[01:23:25] frame select

[01:23:25] frame #0: 0x00003060 macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:113 -> 113 foo!(); // #loc1 114 

[01:23:25] next

[01:23:25] frame select

[01:23:25] frame #0: 0x00003078 macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:115 -> 115 foo2!(); // #loc2 116 

[01:23:25] next

[01:23:25] frame select

[01:23:25] frame #0: 0x000030b0 macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:117 -> 117 let x = vec![42]; // #loc3 118 

[01:23:25] next

[01:23:25] frame select

[01:23:25] frame #0: 0x000030f1 macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:117 -> 117 let x = vec![42]; // #loc3 118 

[01:23:25] next

[01:23:25] frame select

[01:23:25] frame #0: 0x000030f4 macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba at macro-stepping.rs:119 -> 119 new_scope!(); // #loc4 120 

[01:23:25] continue

[01:23:25] Hit breakpoint 2.1: where = macro-stepping.stage2-i686-apple-darwin`macro_stepping::main::hb15c3f8d880d6dba + 402 at macro-stepping.rs:126, address = 0x000031c2, resolved, hit count = 1 

[01:23:25] step

[01:23:25] frame select

[01:23:25] frame #0: 0x00003200 macro-stepping.stage2-i686-apple-darwin`macro_stepping::included::h0d608a1ca9b366e4 at macro-stepping.inc:12 -> 12 foo!(); // #inc-loc1 13 

[01:23:25] next

[01:23:25] frame select

[01:23:25] frame #0: 0x0000321b macro-stepping.stage2-i686-apple-darwin`macro_stepping::included::h0d608a1ca9b366e4 at macro-stepping.inc:14 -> 14 foo2!(); // #inc-loc2 15 

[01:23:25] next

[01:23:25] frame select

[01:23:25] frame #0: 0x00003253 macro-stepping.stage2-i686-apple-darwin`macro_stepping::included::h0d608a1ca9b366e4 at macro-stepping.inc:16 -> 16 zzz(); // #inc-loc3 17 } 

[01:23:25] quit

[01:23:25] None

[01:23:25] 

[01:23:25] ------------------------------------------

[01:23:25] stderr:

[01:23:25] ------------------------------------------

[01:23:25] warning: (i386) /Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo/macro-stepping.stage2-i686-apple-darwin.lldb.aux/libmacro_stepping.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.

[01:23:25] 

[01:23:25] ------------------------------------------

[01:23:25] 

[01:23:25] thread '[debuginfo-lldb] debuginfo/macro-stepping.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2900:9

[01:23:25] note: Run with `RUST_BACKTRACE=1` for a backtrace.

[01:23:25] 

[01:23:25] 

[01:23:25] failures:

[01:23:25]     [debuginfo-lldb] debuginfo/macro-stepping.rs

[01:23:25] 

[01:23:25] test result: [31mFAILED(B[m. 89 passed; 1 failed; 19 ignored; 0 measured; 0 filtered out

[01:23:25] 

[01:23:25] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:478:22

[01:23:25] 

[01:23:25] 

[01:23:25] command did not execute successfully: "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage0-tools-bin/compiletest" "--compile-lib-path" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage2/lib" "--run-lib-path" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage2/lib/rustlib/i686-apple-darwin/lib" "--rustc-path" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/stage2/bin/rustc" "--src-base" "/Users/travis/build/rust-lang/rust/src/test/debuginfo" "--build-base" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/test/debuginfo" "--stage-id" "stage2-i686-apple-darwin" "--mode" "debuginfo-lldb" "--target" "i686-apple-darwin" "--host" "i686-apple-darwin" "--llvm-filecheck" "/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/llvm/build/bin/FileCheck" "--nodejs" "/Users/travis/.nvm/versions/node/v6.12.3/bin/node" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/Users/travis/build/rust-lang/rust/build/i686-apple-darwin/native/rust-test-helpers" "--docck-python" "/usr/local/opt/python/bin/python2.7" "--lldb-python" "/usr/bin/python" "--lldb-version" "lldb-902.0.73.1" "--lldb-python-dir" "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python" "--llvm-version" "6.0.0\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"

[01:23:25] expected success, got: exit code: 101

[01:23:25] 

[01:23:25] 

[01:23:25] failed to run: /Users/travis/build/rust-lang/rust/build/bootstrap/debug/bootstrap test

[01:23:25] Build completed unsuccessfully in 0:23:32

[01:23:25] make: *** [check] Error 1

[01:23:25] make: INTERNAL: Exiting with 1 jobserver tokens available; should be 3!
```

</details>

**Comment by kennytm** [comment]
Hmm perhaps. 

@bors r+

Removed #48786 (as shown above) and #49203 (already testing)

**Comment by kennytm** [comment]
@bors r+

Added #49105 (new rollup), #49038 (the Travis failure is spurious)

**Comment by alexcrichton** [comment]
Despite [one builder timing out](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6764/job/3ytojqa5tj4ip47e) all other builds passed:

* [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6764)
* [Travis](https://travis-ci.org/rust-lang/rust/builds/356982018)

I think this is an instance of https://github.com/rust-lang/rust/issues/48844, so merging manually

**Comment by kennytm** [comment]
Step timing of that build, for future reference:

<details>

```
[00:07:30] [TIMING] StartupObjects { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 0.569
[00:10:40] [TIMING] Std { target: "i686-pc-windows-gnu", compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" } } -- 190.281
[00:12:01] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", tool: "tidy", path: "src/tools/tidy", mode: Libstd, is_ext_tool: false, extra_features: [] } -- 80.332
[00:12:01] [TIMING] Tidy { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 0.140
[00:14:04] [TIMING] Tidy -- 123.503
[00:15:05] [TIMING] Bootstrap -- 60.268
[00:15:24] [TIMING] Test { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 19.631
[00:36:58] [TIMING] Rustc { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 1293.790
[00:52:50] [TIMING] Llvm { target: "i686-pc-windows-gnu", emscripten: false } -- 951.358
[00:55:53] [TIMING] CodegenBackend { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", backend: "llvm" } -- 183.629
[00:55:54] [TIMING] Assemble { target_compiler: Compiler { stage: 1, host: "i686-pc-windows-gnu" } } -- 0.333
[00:55:54] [TIMING] StartupObjects { compiler: Compiler { stage: 1, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 0.141
[00:58:20] [TIMING] Std { target: "i686-pc-windows-gnu", compiler: Compiler { stage: 1, host: "i686-pc-windows-gnu" } } -- 145.682
[00:58:44] [TIMING] Test { compiler: Compiler { stage: 1, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 24.514
[01:31:10] [TIMING] Rustc { compiler: Compiler { stage: 1, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 1946.125
[01:34:39] [TIMING] CodegenBackend { compiler: Compiler { stage: 1, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", backend: "llvm" } -- 209.135
[01:34:40] [TIMING] TestHelpers { target: "i686-pc-windows-gnu" } -- 0.368
[01:37:24] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", tool: "compiletest", path: "src/tools/compiletest", mode: Libtest, is_ext_tool: false, extra_features: [] } -- 164.324
[01:42:04] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "ui", suite: "ui" } -- 279.832
[01:42:40] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "parse-fail", suite: "parse-fail" } -- 35.715
[01:43:22] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "run-fail", suite: "run-fail" } -- 42.572
[01:43:29] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "run-pass-valgrind", suite: "run-pass-valgrind" } -- 7.081
[01:44:20] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "mir-opt", suite: "mir-opt" } -- 50.585
[01:44:31] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "codegen", suite: "codegen" } -- 11.027
[01:44:39] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "codegen-units", suite: "codegen-units" } -- 8.449
[01:45:32] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "incremental", suite: "incremental" } -- 52.041
[01:46:04] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "debuginfo-gdb", suite: "debuginfo" } -- 32.197
[01:46:04] [TIMING] RustcLink { compiler: Compiler { stage: 1, host: "i686-pc-windows-gnu" }, target_compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 0.103
[01:46:49] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "ui", suite: "ui-fulldeps" } -- 45.058
[01:55:22] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "run-pass", suite: "run-pass-fulldeps" } -- 512.538
[01:55:29] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "run-fail", suite: "run-fail-fulldeps" } -- 7.014
[01:58:12] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "compile-fail", suite: "compile-fail-fulldeps" } -- 163.293
[01:58:17] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "incremental", suite: "incremental-fulldeps" } -- 4.843
[02:03:22] [TIMING] Rustdoc { host: "i686-pc-windows-gnu" } -- 305.601
[02:08:18] [TIMING] Compiletest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: "rustdoc", suite: "rustdoc" } -- 295.567
[02:08:27] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libtest, test_kind: Test, krate: "term" } -- 8.871
[02:08:46] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libtest, test_kind: Test, krate: "test" } -- 18.740
[02:14:02] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libstd, test_kind: Test, krate: "alloc" } -- 316.828
[02:14:03] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libstd, test_kind: Test, krate: "alloc_system" } -- 1.041
[02:22:42] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libstd, test_kind: Test, krate: "core" } -- 518.282
[02:22:44] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libstd, test_kind: Test, krate: "panic_abort" } -- 2.167
[02:30:27] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libstd, test_kind: Test, krate: "std" } -- 463.380
[02:30:47] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libstd, test_kind: Test, krate: "std_unicode" } -- 19.988
[02:30:48] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Libstd, test_kind: Test, krate: "unwind" } -- 1.181
[02:30:54] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "arena" } -- 5.299
[02:30:57] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "fmt_macros" } -- 3.517
[02:31:02] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "graphviz" } -- 4.618
[02:31:06] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "proc_macro" } -- 3.791
[02:34:00] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc" } -- 174.336
[02:34:01] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_allocator" } -- 0.868
[02:34:47] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_apfloat" } -- 45.902
[02:35:10] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_back" } -- 23.366
[02:35:11] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_borrowck" } -- 0.826
[02:35:13] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_const_math" } -- 2.403
[02:35:44] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_data_structures" } -- 30.449
[02:37:42] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_driver" } -- 118.383
[02:37:46] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_errors" } -- 3.769
[02:37:55] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_incremental" } -- 9.392
[02:37:56] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_lint" } -- 1.048
[02:38:05] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_metadata" } -- 8.950
[02:38:55] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_mir" } -- 49.624
[02:39:01] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_passes" } -- 5.793
[02:39:06] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_platform_intrinsics" } -- 5.399
[02:39:11] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_plugin" } -- 5.060
[02:39:16] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_privacy" } -- 5.086
[02:39:17] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_resolve" } -- 0.861
[02:39:24] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_save_analysis" } -- 6.727
[02:39:28] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_traits" } -- 3.641
[02:39:29] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_trans_utils" } -- 0.847
[02:39:29] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc_typeck" } -- 0.873
[02:40:14] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "serialize" } -- 44.750
[02:42:13] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "syntax" } -- 118.561
[02:42:22] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "syntax_ext" } -- 9.367
[02:42:28] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "syntax_pos" } -- 6.028
[02:42:45] [TIMING] Crate { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", mode: Librustc, test_kind: Test, krate: "rustc-main" } -- 16.629
[02:44:08] [TIMING] CrateRustdoc { host: "i686-pc-windows-gnu", test_kind: Test } -- 82.987
[02:44:26] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", tool: "unstable-book-gen", path: "src/tools/unstable-book-gen", mode: Libstd, is_ext_tool: false, extra_features: [] } -- 18.210
[02:44:28] [TIMING] UnstableBookGen { target: "i686-pc-windows-gnu" } -- 1.690
[02:47:50] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", tool: "rustbook", path: "src/tools/rustbook", mode: Librustc, is_ext_tool: false, extra_features: [] } -- 202.304
[02:47:53] [TIMING] RustbookSrc { target: "i686-pc-windows-gnu", name: "unstable-book", src: "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\md-doc" } -- 3.012
[02:47:54] [TIMING] RustbookSrc { target: "i686-pc-windows-gnu", name: "book/first-edition", src: "C:\\projects\\rust\\src/doc" } -- 0.641
[02:47:55] [TIMING] RustbookSrc { target: "i686-pc-windows-gnu", name: "book/second-edition", src: "C:\\projects\\rust\\src/doc" } -- 1.250
[02:47:57] [TIMING] Standalone { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu" } -- 1.908
[02:48:01] [TIMING] TheBook { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", name: "book" } -- 4.283
[02:50:28] [TIMING] Std { stage: 2, target: "i686-pc-windows-gnu" } -- 146.590
[02:52:04] [TIMING] Rustc { stage: 2, target: "i686-pc-windows-gnu" } -- 96.619
[02:52:35] [TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", tool: "error_index_generator", path: "src/tools/error_index_generator", mode: Librustc, is_ext_tool: false, extra_features: [] } -- 30.277
[02:52:35] [TIMING] ErrorIndex { target: "i686-pc-windows-gnu" } -- 0.364
[02:52:36] [TIMING] RustbookSrc { target: "i686-pc-windows-gnu", name: "nomicon", src: "C:\\projects\\rust\\src/doc" } -- 0.861
[02:52:37] [TIMING] RustbookSrc { target: "i686-pc-windows-gnu", name: "reference", src: "C:\\projects\\rust\\src/doc" } -- 0.821
[02:52:37] [TIMING] RustbookSrc { target: "i686-pc-windows-gnu", name: "rustdoc", src: "C:\\projects\\rust\\src/doc" } -- 0.279
[02:52:42] [TIMING] RustbookSrc { target: "i686-pc-windows-gnu", name: "rust-by-example", src: "C:\\projects\\rust\\src/doc" } -- 4.418
[02:52:42] [TIMING] CargoBook { target: "i686-pc-windows-gnu", name: "cargo" } -- 0.658
[02:53:03] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", tool: "linkchecker", path: "src/tools/linkchecker", mode: Libstd, is_ext_tool: false, extra_features: [] } -- 20.454
[02:55:11] [TIMING] Linkcheck { host: "i686-pc-windows-gnu" } -- 129.028
[02:56:23] [TIMING] ErrorIndex { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" } } -- 71.835
[02:56:26] [TIMING] DocTest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, path: "src/doc/rustdoc", name: "rustdoc", is_ext_doc: false } -- 2.660
[02:56:50] [TIMING] DocTest { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" }, path: "src/doc/unstable-book", name: "unstable-book", is_ext_doc: false } -- 24.223
[02:56:52] [TIMING] RustdocJS { host: "i686-pc-windows-gnu", target: "i686-pc-windows-gnu" } -- 1.489
[02:56:54] [TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "i686-pc-windows-gnu" }, target: "i686-pc-windows-gnu", tool: "rustdoc-themes", path: "src/tools/rustdoc-themes", mode: Libstd, is_ext_tool: false, extra_features: [] } -- 2.535
[02:56:54] [TIMING] RustdocTheme { compiler: Compiler { stage: 2, host: "i686-pc-windows-gnu" } } -- 0.126
```

</details>

**Pull request merged**
