### PR TITLE
Beginning of more beautiful rustc --explain

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
As mentionned in #24523, here is the beginning of the more beautiful printing. Only tested under linux. It doesn't -yet- manage terminals which doesn't handle color printing. Any opinion is welcome.

### CODE REVIEW

**Comment by killercup** [comment]
This sounds quite cool. Can you maybe add a screenshot?

I guess by only using blue and red for highlights, you don't need to concern yourself with detecting the terminals background color (since red and blue both work on dark and light backgrounds). Do you have any plans for a more complex color scheme?

**Comment by GuillaumeGomez** [comment]
I actually asked yesterday on the IRC if there is any color code but no one answered. For the parsing, I wanted to use the one made in rustdoc (I asked for help for that but no answer yet neither ^^). Here is the current display :

screenshot from 2015-05-02 13 00 04

**Comment by bluss** [comment]
Errors and warnings are already colored. Rustc uses som kind of term library for this. You should look into it.

**Comment by killercup** [comment]
@GuillaumeGomez, @bluss is right, there is a [`libterm`](https://github.com/rust-lang/rust/tree/354d16bd72ed002d6d8abe9896f89a445a60c21f/src/libterm) that seems to do some terminal output stuff.

**Comment by GuillaumeGomez** [comment]
Oh nice ! I'll take a look then !

**Comment by huonw** [comment]
It would be good to have this code not directly inside `lib.rs`, e.g. a `explain.rs` submodule would be better.

**Comment by GuillaumeGomez** [comment]
@huonw: Don't worry, it was just a start to have an idea of what it'll look like after. For now, the code is just ugly.

**Comment by GuillaumeGomez** [comment]
I created an `explain.rs` submodule and I also use the `libterm`. But I'm not very happy of the color code. Another one could be nice. Any idea of how I could improve it ?

**Comment by jakub-** [comment]
I'm concerned about the maintainability of this code. Could we use something like https://github.com/rkitover/vimpager or http://www.gnu.org/software/src-highlite/ for this purpose, instead? We have the vim definitions already so this would be a matter of shelling out, of course conditional on vim being present.

The build changes may be non-trivial but would be more future-proof, I think. Thoughts?

**Comment by GuillaumeGomez** [comment]
I'm a fan of emacs actually. :-p Once again, this code is just a preview, I don't intend to continue this one. I'd prefer use something from inside the compiler (I'm thinking about the `librustdoc`).

**Comment by michaelsproul** [comment]
One way I thought of doing this would be to write a custom renderer for Hoedown (the markdown parser used by `rustdoc`). This would give us heading highlighting almost for free, and then we could generalise the code in [src/librustdoc/html/higlight.rs](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/highlight.rs) to highlight code blocks.

**Comment by GuillaumeGomez** [comment]
@michaelsproul: hum... Why not. Originally, I was going to use the `rustdoc`, not modify it. However it seems even better this way, I'll give it a try.

**Comment by michaelsproul** [comment]
@GuillaumeGomez: It's a whole lot of FFI and stuff, but if you're up for it...

**Comment by GuillaumeGomez** [comment]
I am. I'll start to see how `rustdoc` works before going any further and then I'll modify it.

**Comment by nikomatsakis** [comment]
So I am confused as to what should happen with this current PR -- should we close it, as you are now trying an alternative approach?

**Comment by GuillaumeGomez** [comment]
I'm still working on rustdoc, but before I have to fix the JSON error. I don't have much time recently (and I'm sorry about that). So can you keep it open while I start the other one please ?

**Comment by alexcrichton** [comment]
Closing due to inactivity, but I'm looking forward to see where this goes!

**Pull request closed without merging**
