### PR TITLE
Document the discrepancy in the mask type for _mm_shuffle_ps

### LINKED ISSUE #62490: `core::arch::x86_64::_mm_shuffle_ps` input doesn't match official docs
[x86_64::_mm_shuffle_ps](https://doc.rust-lang.org/core/arch/x86_64/fn._mm_shuffle_ps.html) (and by extension [x86::_mm_shuffle_ps](https://doc.rust-lang.org/core/arch/x86/fn._mm_shuffle_ps.html)) have `i32` as the mask type, but the [intel intrinsics guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_shuffle_ps&expand=5190) lists `unsigned int` as the mask type.

This issue has been assigned to @georgio via [this comment](https://github.com/rust-lang/rust/issues/62490#issuecomment-667341126).

### PR DESCRIPTION
**Pull request by georgio**
This Pull Request updates the `stdarch` submodule in order to resolve #62490

### CODE REVIEW

**Comment by kennytm** [comment]
Please checkout the submodule at 78891cdf292c23278ca8723bd543100249159604 instead of the current d6822f9c433bd70f786b157f17beaf64ee28d83a. 

r=me afterwards.

**Comment by georgio** [comment]
@kennytm done :-)

**Comment by kennytm** [comment]
🤔 could you do a clean rebase? a lot of irrelevant diff is brought in.

```sh
git fetch origin master
git checkout master
git reset --hard origin/master
cd library/stdarch
git checkout d6822f9c433bd70f786b157f17beaf64ee28d83a
cd -
git add library/stdarch
git commit
git push georgio master --force-with-lease
```

**Comment by georgio** [comment]
Sorry about that, these commits happened by mistake (my first time contributing).
Thanks for the instructions to fix it! I hope works now.

**Comment by jethrogb** [comment]
@kennytm Please don't approve changes that make submodules point to commits that are not part of the target repository's submodule branch.

**Pull request merged**
