### PR TITLE
Remove size_of == 1 case from `fill` specialization.

### LINKED ISSUE #87891: Undefined behaviour in `slice::fill` specialization.
This was reported by @the8472 on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/potential.20UB.20in.20slice.3A.3Afill/near/248871405

> I'm wondering if the optimization here is correct: https://github.com/rust-lang/rust/blob/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/core/src/slice/specialize.rs#L22-L28
> 
> Specifically if T is `MaybeUninit<u8>`. It momentarily transmutes that to an u8 before passing it to `write_bytes`.

Demo:

```rust
use std::mem::MaybeUninit;

fn main() {
    let mut a = [MaybeUninit::<u8>::uninit(); 10];
    a.fill(MaybeUninit::uninit());
}
```
```
error: Undefined Behavior: using uninitialized data, but this operation requires initialized memory
    --> /home/mara/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2191:14
     |
2191 |     unsafe { write_bytes(dst, val, count) }
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ using uninitialized data, but this operation requires initialized memory
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
```

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes https://github.com/rust-lang/rust/issues/87891

See [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/potential.20UB.20in.20slice.3A.3Afill/near/248875743).

### CODE REVIEW

**Review by the8472 — APPROVED** [review]
Should be fine as an immediate fix to remove the UB, but I think it's still better to explicitly tell the compiler that it's dealing with a memset when we can rather than relying on optimizers. [Currently it helps at least one other backend](https://rust.godbolt.org/z/hrMYvWz9n). And even llvm will have to do less work if we just tell it.

**Comment by RalfJung** [comment]
@m-ou-se Miri actually runs libcore tests (https://github.com/rust-lang/miri-test-libstd), so it'd be great if you could add your test case from https://github.com/rust-lang/rust/issues/87891 to the test suite -- doesn't have to be in this PR though.

**Pull request merged**
