### PR TITLE
optmize grow process of `InitMask`

### PR DESCRIPTION
**Pull request by SparrowLii**
This PR optmize the grow process of `InitMask` struct. I divided it into 3 commits for  reivewing, we can finally sqaush them if this PR been approved.
Commit 1 moves grow process from `grow` method to `set_range`, because `set_range` sets all values from `start` to `end`, this makes the setting in `grow` method redundant.
Commit 2 fixes the FIXME of selecting the value to extending blocks according to `new_state`, which can avoid redundant setting again.
Commit 3 replaces `BLOCK_SIZE` with `BLOCK_SIZE_POW`, so that we can use shiftings instead of multiply and divide operations, which can save a little time.[Edit: This commit has been reverted]

### CODE REVIEW

**Comment by RalfJung** [comment]
> Commit 3 replaces BLOCK_SIZE with BLOCK_SIZE_POW, so that we can use shiftings instead of multiply and divide operations, which can save a little time.

Did you benchmark this? I keep hearing compilers know how to compile multiply/divide by constants much better than humans do.

**Comment by oli-obk** [comment]
There's a small perf hit. Without running cachegrind it's hard to tell, i'll check tomorrow. I agree with Ralf tho, the last commit should be reverted and benchmarked on its own.

**Comment by SparrowLii** [comment]
Thanks! I have reverted the last commit, and avoids calling `set_range_inbounds` when `new()` be called. I think we can do another perf run

**Comment by SparrowLii** [comment]
It looks like this PR doesn't serve the purpose of saving time. This is probably because blocks are rarely extended when actually using InitMask. 
In that case, I think this PR can be closed, and the FIXME can also be removed.

**Comment by RalfJung** [comment]
I'm surprised how hard it is to squeeze more time out of this. Thanks for giving it a go!

**Comment by oli-obk** [comment]
Do we actually use `set_range` for ranges outside the already existing mask? Maybe that arm is dead code and due to the manual inlining of `grow` is now pessimizing LLVM opts on that piece of code?

Similarly wondering how much we actually create init masks that are marked as initialized from the start

**Comment by SparrowLii** [comment]
> Do we actually use set_range for ranges outside the already existing mask? Maybe that arm is dead code and due to the manual inlining of grow is now pessimizing LLVM opts on that piece of code?

Probably. I split `grow_and_set` from `set_range`. This should not pessimize the opt effect of llvm

**Comment by oli-obk** [comment]
> In that case, I think this PR can be closed, and the FIXME can also be removed.

Looks like that's the way to go. I don't see much that we can do here.

**Pull request closed without merging**
