### PR TITLE
Ignore own item bounds in parent alias types in `for_each_item_bound`

### LINKED ISSUE #120912: `polymorphic_recursion.rs` takes longer to compile
### Code

I tried this code:

```rust
// skip-filecheck
// Make sure that the MIR inliner does not loop indefinitely on polymorphic recursion.
// compile-flags: --crate-type lib

// Randomize `def_path_hash` by defining them under a module with different names
macro_rules! emit {
    ($($m:ident)*) => {$(
        pub mod $m {
            pub trait Tr { type Next: Tr; }

            pub fn hoge<const N: usize, T: Tr>() {
                inner::<N, T>();
            }

            #[inline(always)]
            fn inner<const N: usize, T: Tr>()
            {
                inner::<N, T::Next>();
                inner::<N, T::Next>();
            }
        }
    )*};
}

// Increase the chance of triggering the bug
emit!(m00 m01 m02 m03 m04 m05 m06 m07 m08 m09 m10 m11 m12 m13 m14 m15 m16 m17 m18 m19);
```

https://github.com/rust-lang/rust/blob/1.76.0/tests/mir-opt/inline/polymorphic_recursion.rs

I expected to see this happen: *It compiles quickly.*

Instead, this happened: *It takes 10s to complete.*

### Version with regression

Bisected to https://github.com/rust-lang/rust/pull/120584.

cc @compiler-errors

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #120912

I want to get a vibe check on this approach, which is very obviously a hack, but I believe something that is forwards-compatible with a more thorough solution and "good enough for now".

The problem here is that for a really deep rigid associated type, we are now repeatedly considering unrelated item bounds from the parent alias types, meaning we're doing a *lot* of extra work in the MIR inliner for deeply substituted rigid projections.

This feels intimately related to #107614. In that PR, we split *supertrait* bounds (bound which share the same `Self` type as the predicate which is being elaborated) and *implied* bounds (anything that is implied by elaborating the predicate).

The problem here is related to the fact that we don't maintain the split between these two for `item_bounds`. If we did, then when recursing into a parent alias type, we'd want to consider only the bounds that are given by [`PredicateFilter::All`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_analysis/astconv/enum.PredicateFilter.html#variant.SelfOnly) **except** those given by [`PredicateFilter::SelfOnly`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_analysis/astconv/enum.PredicateFilter.html#variant.SelfOnly).

### CODE REVIEW

**Comment by compiler-errors** [comment]
whoops

r? lcnr

**Comment by compiler-errors** [comment]
For the record, I understand that this approach also doesn't fix the new trait solver, which still suffers this problem. Didn't want to make a change there until we decide what the best approach for this problem actually is.

**Comment by lcnr** [comment]
I think we can go with the same approach in the new solver. Given that when assembling item bounds for `Alias1<Alias2>`, we know that `ALias1` and `Alias2` are rigid at this point, so any alias bound which applies to `Alias2` does not apply to `Alias1`.  

@bors r+ rollup=never

**Comment by lcnr** [comment]
(this should partially revert the regression in https://github.com/rust-lang/rust/pull/120862)

**Pull request merged**
