### PR TITLE
Clarify the difference between get_mut and into_mut for OccupiedEntry

### PR DESCRIPTION
**Pull request by Phlosioneer**
The examples for both `hash_map::OccupiedEntry::get_mut` and
`hash_map::OccupiedEntry::into_mut` were almost identical. This led
to some confusion over the difference, namely why you would ever
use `get_mut` when `into_mut` gives a longer lifetime. Reddit thread:
https://www.reddit.com/r/rust/comments/8a5swr/why_does_hashmaps

This commit adds two lines and a comment to the example, to show
that the entry object can be re-used after calling `get_mut`.

I'm open to alternate ways to modify these examples.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Is it worth perhaps explicitly calling out the difference between `into_mut` and `get_mut` in the docs? It seems like the comments in the reddit thread could be re-molded into a couple short sentences in the docs.

Thanks for taking the time to improve this. :-)

**Comment by Phlosioneer** [comment]
Sure. I just don't know what to say exactly - there's a difference between giving a rough guesstimation of the difference on reddit and encoding information into the docs.

**Comment by Phlosioneer** [comment]
(See also my separate but related issue #49745)

**Comment by pietroalbini** [comment]
Ping from triage! Can @BurntSushi (or someone else from @rust-lang/docs) review this PR?

**Comment by GuillaumeGomez** [comment]
Hum not much to say. Just wondering what @frewsxcv will find out. :D

**Comment by pietroalbini** [comment]
Ping from triage! What's the status of this PR?

**Comment by Phlosioneer** [comment]
I'm going through stuff and haven't had the time to finish this yet. It's not forgotten, though.

**Comment by pietroalbini** [comment]
Ping from triage @Phlosioneer! Will you have time to work on this again in the future?

**Comment by frewsxcv** [comment]
I'm not confident with the wording of these, but:

For `into_mut`, maybe add:

```
If you need multiple references to the `OccupiedEntry`, see `get_mut`.
```

And for `get_mut`, maybe:

```
If you need a reference to the `OccupiedEntry` which may outlive the destruction of the `Entry` value, see `into_mut`.
```

Also if it's easy for you, please also make these changes to the `btree_map` docs:

- https://doc.rust-lang.org/std/collections/btree_map/struct.OccupiedEntry.html#method.get_mut
- https://doc.rust-lang.org/std/collections/btree_map/struct.OccupiedEntry.html#method.into_mut

**Comment by pietroalbini** [comment]
Assigning to someone else from libs. r? @dtolnay

**Review by dtolnay — COMMENTED** [review]
I agree with the review in https://github.com/rust-lang/rust/pull/49743#issuecomment-390548750.

**Comment by pietroalbini** [comment]
Ping from triage @Phlosioneer! It's been a while since we heard from you, will you have time to work on this again?

**Comment by frewsxcv** [comment]
In an attempt to keep this moving, I just opened a new pull request which cherry picks these two picks and adds in my suggested changes: https://github.com/rust-lang/rust/pull/51312/ . Hope that's alright @Phlosioneer!

**Comment by Phlosioneer** [comment]
That's okay. I've been unable to devote time to rustc lately.

**Pull request closed without merging**
