### PR TITLE
std::rand: fix dragonflybsd after #121942.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by josephlr** [comment]
I think the correct approach here would be to add a binding to the `libc` crate, and use the binding from there.

**Comment by devnexen** [comment]
> I think the correct approach here would be to add a binding to the `libc` crate, and use the binding from there.

It can take a little while before a new libc release is out then to update here.

**Comment by josephlr** [comment]
PR to add bindings to libc: https://github.com/rust-lang/libc/pull/3619

**Comment by jhpratt** [comment]
I'm going to hold off on approving this pending an outcome of https://github.com/rust-lang/libc/pull/3618. It seems like that is the better approach and wouldn't necessitate any changes in the standard library.

**Comment by josephlr** [comment]
> I'm going to hold off on approving this pending an outcome of [rust-lang/libc#3618](https://github.com/rust-lang/libc/pull/3618). It seems like that is the better approach and wouldn't necessitate any changes in the standard library.

If that's the case, we should revert #121942, as the dragonflyBSD target currently does not build.

**Comment by Nilstrieb** [comment]
It's okay to have breakage, but we'd of course rather have working targets. I think it's fine to wait a bit until the libc change is merged unless it's particularly urgent to have it working again.

**Comment by newpavlov** [comment]
@josephlr 
The `libc` PR does not show any signs of activity for several weeks. So unless you know that it could be merged in the near future, I think it's worth to merge this PR and revert it only after the `libc` changes will land.

**Comment by jhpratt** [comment]
Agreed. I had assumed that the `libc` change would land relatively quickly, but that isn't the case for whatever reason. If/when the `libc` PR lands, whoever makes a PR to revert this should feel free to explicitly request me as reviewer (using `r? @jhpratt`).

@bors r+ rollup

**Comment by jhpratt** [comment]
For some reason, bors still has this in the queue even though it's been merged.

@bors r-

**Pull request merged**
