### PR TITLE
add avx512fp16 to x86 target features

### PR DESCRIPTION
**Pull request by usamoi**
std_detect avx512fp16: https://github.com/rust-lang/stdarch/pull/1508

### CODE REVIEW

**Comment by cjgillot** [comment]
r? compiler

**Comment by usamoi** [comment]
Will somebody review this PR?

**Comment by GuillaumeGomez** [comment]
Let's reroll reviewers.

r? compiler

**Comment by oli-obk** [comment]
This just adds the feature unstably, and thus doesn't need an FCP

@bors r+ rollup

**Pull request merged**
