### PR TITLE
Make more `Result` methods `const`

### PR DESCRIPTION
**Pull request by netsutetsu**
Tracking issue: #82814

Constified methods: Result::{map, map_or, map_or_else, map_err, as_deref, as_deref_mut, unwrap_or_default, and_then, or_else, unwrap_or_else, unwrap_unchecked, unwrap_err_unchecked, copied, cloned}

### CODE REVIEW

**Comment by thomcc** [comment]
I think even in our new process an ACP is needed for this? You can file one here https://github.com/rust-lang/libs-team/

**Comment by Dylan-DPC** [comment]
@netsutetsu any updates on the ACP?

**Comment by thomcc** [comment]
I'm going to be away for a few months, so I'm rerolling my PRs so that folks don't have to wait for me. Sorry/thanks.

r? libs

**Pull request closed without merging**
