### PR TITLE
Demonstrate best practice for feeding stdin of a child processes

### PR DESCRIPTION
**Pull request by kornelski**
Documentation change. 

It's possible to create a deadlock with stdin/stdout I/O on a single thread:

* the child process may fill its stdout buffer, and have to wait for the parent process to read it,
* but the parent process may be waiting until its stdin write finishes before reading the stdout.

Therefore, the parent process should use separate threads for writing and reading.

These examples are not deadlocking in practice, because they use short strings, but I think it's better to demonstrate code that works even for long writes. The problem is non-obvious and tricky to debug (it seems that even libstd has a similar issue: #45572).

This also demonstrates how to use stdio with threads: it's not obvious that `.take()` can be used to avoid fighting with the borrow checker.

I've checked that the modified examples run fine.

### CODE REVIEW

**Comment by joshtriplett** [comment]
@kornelski I think explaining this issue and providing an example is a good idea. So is demonstrating `take`.

Would you consider adding a note explaining when this is needed, along the lines of: "This is an issue when running any program that doesn't have a stated guarantee that it reads its entire stdin before writing more than a pipe buffer's worth of output, if you want to feed it more than a pipe buffer's worth of input. The size of a pipe buffer varies on different targets."

Also, one other issue (which may or may not be possible to simply address here): it'd be nice if somewhere we had a good example of error handling for threads using `?`. We still have many examples that use `.expect()`, dating back to when we couldn't easily use `?` in doctests. But one issue with `expect` and threaded code is that it's easy to translate `expect` to a `?` outside of a thread, but in a thread it isn't obvious how to handle errors. This isn't necessarily the example to fix that, though, if doing so isn't trivial.

**Comment by lukaslueg** [comment]
This PR addresses a very common problem where people deadlock their program and can't figure out why. Without derailing this specific PR: Should we have a `Process::communicate()` [like Python has](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait) for this exact reason?

**Comment by kornelski** [comment]
I've added more explanations.

I agree that changing `unwrap()` would be good. I can make another PR for this.

**Comment by joshtriplett** [comment]
@kornelski wrote:
> I've added more explanations.

Looks great. Merging.

> I agree that changing `unwrap()` would be good. I can make another PR for this.

Thank you!

**Pull request merged**
