### PR TITLE
Update rustc-hash to version 2

### PR DESCRIPTION
**Pull request by Noratrieb**
This brings in the new algorithm.

see https://github.com/rust-lang/rustc-hash/pull/37 and https://github.com/rust-lang/rust/pull/125133

### CODE REVIEW

**Comment by Noratrieb** [comment]
@bors try @rust-timer queue
let's see again

**Comment by workingjubilee** [comment]
> The job x86_64-gnu-llvm-17 failed! Check out the build log:

huh.

**Comment by Noratrieb** [comment]
stuff relies on hashmap iteration order lol. it's sorta stable with fxhash as it has a fixed seed

**Comment by workingjubilee** [comment]
deep sigh

**Comment by workingjubilee** [comment]
On the bright side, we simultaneously reveal everything that depends on hashmap iteration order and get a faster compiler.

**Review by WaffleLapkin — APPROVED** [review]
r=me when CI is fixed

**Comment by Noratrieb** [comment]
uhh wtf?? @GuillaumeGomez do you have an idea why changing fxhash would cause rustdoc-gui tests to fail to find fonts?

**Comment by GuillaumeGomez** [comment]
Wth. Someone cursed this CI run, I have no other explanation... I think it's safe to ignore this failure (or just make another CI run).

**Comment by Noratrieb** [comment]
you know, i wanted to ignore this failure but then i re-ran it and it failed again. well, let's rebase and try again.

**Comment by workingjubilee** [comment]
One option if this doesn't CI run doesn't succeed is disabling the rustdoc-gui suite.

Does anyone have any better ideas?

**Comment by klensy** [comment]
> One option if this CI run doesn't succeed is disabling the rustdoc-gui suite.
> 
> Does anyone have any better ideas?

https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/css/rustdoc.css have hardcoded filenames with hashes.

**Comment by GuillaumeGomez** [comment]
> One option if this CI run doesn't succeed is disabling the rustdoc-gui suite.
> 
> Does anyone have any better ideas?

Please don't.

I'll take a look in a few days when I'm back. I think something unrelated like maybe disk space is in cause.

**Comment by aDotInTheVoid** [comment]
>  I think something unrelated like maybe disk space is in cause.

No, the error is actually accurate (and it's concerning that (almost) everyone see's a rustdoc-gui failure and assumes it's something spooky). Fix/explanation is here: #131908

**Comment by Noratrieb** [comment]
ferris forgor

**Comment by aDotInTheVoid** [comment]
Eeeeek, sorry!

**Comment by Noratrieb** [comment]
it's ok, you were gaming hard on your pr :heart:

**Pull request closed without merging**
