### PR TITLE
Update compiler error E0076 to use new error format

### LINKED ISSUE #35221: E0076 needs to be updated to new format
From: src/test/compile-fail/E0076.rs

Error E0076 needs a span_label, updating it from:

```
error[E0076]: SIMD vector should be homogeneous
  --> src/test/compile-fail/E0076.rs:14:1
   |
14 | struct Bad(u16, u32, u32); //~ ERROR E0076
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

To:

```
error[E0076]: SIMD vector should be homogeneous
  --> src/test/compile-fail/E0076.rs:14:1
   |
14 | struct Bad(u16, u32, u32); //~ ERROR E0076
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ SIMD elements must have the same type
```

Bonus: The span should focus on the arguments

```
error[E0076]: SIMD vector should be homogeneous
  --> src/test/compile-fail/E0076.rs:14:1
   |
14 | struct Bad(u16, u32, u32); //~ ERROR E0076
   |            ^^^^^^^^^^^^^ SIMD elements must have the same type
```

### PR DESCRIPTION
**Pull request by abhiQmar**
Fixes #35221 part of #35233

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR!

This looks like a good start.  The next step is to update the unit test so that it tests the new label.  You can read how to do this by looking at the Extra Credit part of the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html).

**Comment by abhiQmar** [comment]
done
Can you please point me in a direction with the bonus on this one ?

**Comment by abhiQmar** [comment]
@jonathandturner 
Do I need to do add anything?

**Comment by jonathandturner** [comment]
Looks good.  One last thing.  Can you squash your 2 commits down to 1 commit?  After that, I think it's ready.

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Comment by abhi-sm** [comment]
@jonathandturner 
All the tests were passing on my machine. Has the master moved, should I take a pull and fix them ?

**Comment by abhiQmar** [comment]
@jonathandturner 
All the tests were passing on my machine. Has the master moved, should I take a pull and fix them ?

**Pull request merged**
