### PR TITLE
Extract exhaustiveness into its own crate

### PR DESCRIPTION
**Pull request by Nadrieril**
It now makes sense to extract exhaustiveness into its own crate! This was much-requested by rust-analyzer (they currently maintain by hand a copy of the algorithm), and I hope this can serve other projects e.g. clippy.

This is the churny PR: it exclusively moves code around. It's not yet useable outside of rustc but I wanted the churny parts to be out of the way.

r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
cool

**Comment by Nadrieril** [comment]
Thanks!

**Comment by compiler-errors** [comment]
Looking forward to see the PR that adds `feature = "nightly"` so that rust-analyzer can actually use this code ;)

**Comment by Nadrieril** [comment]
I'm working on it as we speak :)

**Pull request merged**
