### PR TITLE
Don't use an allocation for ItemId in StmtKind

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r-

We should not be landing this without support for why we're doing it - at least a perf run.

Cc @nnethercote

@bors try

**Comment by nnethercote** [comment]
This looks fine to me. I expect it will either have no noticeable effect or be a small improvement. Either way it's still worth landing for the code simplification.

@bors try

**Comment by nnethercote** [comment]
@rust-timer build d18f9b6ebce5710fd5379932994af11a2622836a

**Comment by nnethercote** [comment]
Perf results look like noisy, no discernible perf effect.

@bors r=oli-obk rollup

**Pull request merged**
