### PR TITLE
Remove reverted change from relnotes

### PR DESCRIPTION
**Pull request by XAMPPRocky**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by pthariensflame** [comment]
@XAMPPRocky @Aaron1011 Wait, was this actually removed after all?  I thought #79427 resolved this without taking away the newly-stable `impl`s.

**Comment by XAMPPRocky** [comment]
@pthariensflame According to this comment, it's not present. https://github.com/rust-lang/rust/pull/79815#discussion_r550830286

**Comment by pthariensflame** [comment]
@XAMPPRocky I see!  Thanks for clearing that up.  ❤️

**Pull request merged**
