### PR TITLE
Enable `-W semicolon_in_expressions_from_macros` in bootstrap

### PR DESCRIPTION
**Pull request by Aaron1011**
Now that stdarch has been updated, we can do this without breaking the
build.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me in theory but looks like there's at least one use left

**Comment by Aaron1011** [comment]
This is now blocked on bumping the `stdarch` submodule.

**Comment by jyn514** [comment]
@Aaron1011 this should be possible since #83776

**Comment by Aaron1011** [comment]
It looks like https://github.com/rust-lang/stdarch/pull/1080 wasn't included in the submodule bump.

**Comment by Aaron1011** [comment]
@Mark-Simulacrum This is now ready to merge

**Pull request merged**
