### PR TITLE
Const prop aggregates even if partially or fully modified

### PR DESCRIPTION
**Pull request by oli-obk**
r? @wesleywiser 

cc @rust-lang/wg-mir-opt I'm moderately scared of this change, but I'm confident in having reviewed all the cases.

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]
Agreed: it does seem a bit scary but the code appears correct. Let's see what perf says.

**Comment by wesleywiser** [comment]
Let's try that again:

@rust-timer queue 274c308239850d9f5a2a2a9067bcc5c41ab35a6d

**Comment by wesleywiser** [comment]
Oh, looks like it's still in the queue...

**Comment by oli-obk** [comment]
@rust-timer build 274c308239850d9f5a2a2a9067bcc5c41ab35a6d

**Comment by oli-obk** [comment]
@rust-timer build 274c308

**Comment by mati865** [comment]
Perf shows minimal improvement.

**Comment by wesleywiser** [comment]
I think we mostly wanted to make sure this didn't cause any regressions.

@bors r+

**Pull request merged**
