### PR TITLE
Implement two features: Creating OS pipes and redirecting stdio of child processes to File handles

### PR DESCRIPTION
**Pull request by ipetkov**
This pull request implements two separate but related features:
- Safely creating an OS pipe which will create two `std::fs::File` handles (thus inheriting all their benefits). There was a similar struct in the past, however, it exposed raw file descriptors and was rather unsafe. It is feature gated behind `fs_pipe`.
- Allow for redirection of stdio of `std::process::Command`s to open file handles, this allows saving command output or piping output from two different `Command`s without having to manually buffer the data. This is currently feature gated behind `process_redirect`.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh wow, thanks for taking the initiative here! Also thanks for the quite comprehensive tests!

I think that the Windows implementation here may need some more work, however. We're trying to move away from the use of file descriptors as much as possible and currently `Stdio::piped` is the last holdout before we're able to remove them entirely. The current representation of a `File` on Windows as simple a `libc::HANDLE` is actually quite intentional, and it's fairly crucial that we keep it that way.

Would you be interested in investigating removing the usage of file descriptors on Windows here? I'd be willing to help out of course!

**Comment by alexcrichton** [comment]
This will also need an RFC to land first as there's quite a few vectors of design here which may want to be discussed in a broader forum than on this PR itself.

**Comment by ipetkov** [comment]
@alexcrichton I think it shouldn't be too difficult to refactor the Windows implementation to not rely on any file descriptors, so I'll definitely take a shot at it!

In the mean time I'll draft up an RFC for the proposed API additions (any any existing APIs that may be beneficial to tweak).

**Comment by alexcrichton** [comment]
Thanks @ipetkov!

**Comment by ipetkov** [comment]
RFC for this feature: https://github.com/rust-lang/rfcs/pull/1055

**Comment by alexcrichton** [comment]
I'm gonna close this for now in favor of the RFC opened by @ipetkov.

**Pull request closed without merging**
