### PR TITLE
Tweak multispan rendering to reduce output length

### PR DESCRIPTION
**Pull request by estebank**
Consider comments and bare delimiters the same as an "empty line" for purposes of hiding rendered code output of long multispans. This results in more aggressive shortening of rendered output without losing too much context, specially in `*.stderr` tests that have "hidden" comments. We do that check not only on the first 4 lines of the multispan, but now also on the previous to last line as well.

### CODE REVIEW

**Review by oli-obk — APPROVED** [review]

**Comment by estebank** [comment]
I don't have access to a windows machine to fix that miri test, and the log that's being printed by CI doesn't really make sense, so I'll have to try a few different things to see what `stderr` output it *actually* expects 🙄

**Comment by oli-obk** [comment]
Ah, you can usually just bless with `--target`, as miri emulates all targets from any host. Idk how to do that from within this repo, @rust-lang/miri have you cross-tested from the rustc repo before?

**Comment by estebank** [comment]
The issue is with this https://github.com/rust-lang/rust/blob/7d9a4a7d3a4ae6298f3aed697dffaaf379308983/src/tools/miri/tests/fail-dep/concurrency/windows_join_self.rs and https://github.com/rust-lang/rust/blob/7d9a4a7d3a4ae6298f3aed697dffaaf379308983/src/tools/miri/tests/fail-dep/concurrency/windows_join_main.rs, which I think have the dependency on `windows_sys`, which I'm not sure the miri test suite will help with, right?

**Comment by RalfJung** [comment]
> Ah, you can usually just bless with `--target`, as miri emulates all targets from any host. Idk how to do that from within this repo, @rust-lang/miri have you cross-tested from the rustc repo before?

Yeah we do that all the time, it even runs on CI. `./x test miri --target <foo> --bless` should just work.

**Comment by estebank** [comment]
Ended up getting it right by "blind editing" (by making an expression that kind of looked the same physically as far as spans go to see what the new rendering looked like and going off that).

@bors r=oli-obk

**Pull request merged**
