### PR TITLE
fix `llvm_out` to use the correct LLVM root

### PR DESCRIPTION
**Pull request by onur-ozkan**
When `download-ci-llvm` is enabled, `llvm_out` ends up with the
error below due to an incorrect path on cross-compilations. This change fixes that.

```sh
failed to execute command: "/rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/llvm-config" "--version"
ERROR: No such file or directory (os error 2)
```

### CODE REVIEW

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+

**Comment by onur-ozkan** [comment]
I just added a unit test for testing the behaviour of `llvm_out`. 

@bors r-

**Comment by albertlarsan68** [comment]
Thanks for the PR!
r=me when CI is green

**Comment by Nadrieril** [comment]
I got this [linker-related rollout failure](https://github.com/rust-lang/rust/pull/120743#issuecomment-1932520372), could this be the culprit?

**Comment by onur-ozkan** [comment]
I am not so sure.

@bors rollup=iffy

**Comment by Nadrieril** [comment]
FWIW the rest of the rollup worked

**Comment by Nadrieril** [comment]
This doesn't look like a spurious failure at least. Maybe @rust-lang/bootstrap would know more? For the bootstrap team: this PR makes more use of the CI LLVM, which seems to have triggered a problem with `ld` flags on `x86_64-apple-darwin` (error [here](https://github.com/rust-lang/rust/pull/120743#issuecomment-1932520372)).

@bors r-

From googling, [suggested workaround](https://slack-chats.kotlinlang.org/t/13905976/ld-unknown-options-ios-simulator-version-min-sdk-version-any) is to use the `-ld64` flag to use the old linker. Or use the newer `-platform_version` flag instead.

**Comment by onur-ozkan** [comment]
I don't understand how this is relevant. Currently, `llvm_out` is returning the compiled LLVM path. This PR modifies it to return the ci-llvm path if `download-ci-llvm` is enabled. However, `download-ci-llvm` is disabled in the CI pipeline anyway. Therefore, this PR shouldn't have any effect there.

**Comment by onur-ozkan** [comment]
> do you think it was a fluke?

I think it was

**Comment by Nadrieril** [comment]
Alright then, I can't claim to understand much in this topic

@bors r=albertlarsan68 rollup=iffy

**Pull request merged**
