### PR TITLE
Add simd_bswap, simd_bitreverse, simd_ctlz, and simd_cttz intrinsics

### PR DESCRIPTION
**Pull request by calebzulawski**
cc @workingjubilee

### CODE REVIEW

**Comment by workingjubilee** [comment]
> Intrinsic has incorrect argument type!
<4 x i32> (<4 x i32>, i8)* @llvm.ctlz.v4i32
Intrinsic has incorrect argument type!
<4 x i32> (<4 x i32>, i8)* @llvm.ctlz.v4i32
Intrinsic has incorrect argument type!
<4 x i32> (<4 x i32>, i8)* @llvm.cttz.v4i32
Intrinsic has incorrect argument type!
<4 x i32> (<4 x i32>, i8)* @llvm.cttz.v4i32
LLVM ERROR: Broken module found, compilation aborted!


well
that won't do.

**Comment by calebzulawski** [comment]
Is that LLVM 14 specific? I'm pretty sure the bump to 15 is imminent.

**Comment by calebzulawski** [comment]
Ah, actually, the problem is that it's encoding the last argument as `i8` instead of `i1`.  Why does it work elsewhere?

**Comment by workingjubilee** [comment]
> Is that LLVM 14 specific? I'm pretty sure the bump to 15 is imminent.

I don't thiiink so?

**Comment by Urgau** [comment]
> > Is that LLVM 14 specific? I'm pretty sure the bump to 15 is imminent.
> 
> I don't thiiink so?

https://github.com/rust-lang/rust/pull/114148 8 hours ago ;-)

**Comment by workingjubilee** [comment]
@Urgau I mean that I don't think the issue is LLVM 14 specific, I could be wrong.

**Comment by Urgau** [comment]
> @Urgau I mean that I don't think the issue is LLVM 14 specific, I could be wrong.

Oh, yeah sorry. As for the issue here, I would just note that [`type_bool()`](https://github.com/rust-lang/rust/blob/e40e22be550fdcf5f11ba95cc84f3f337b0695f4/compiler/rustc_codegen_llvm/src/type_.rs#L82-L84) is indeed `i8` not `i1`; to have `i1` you should call [`type_i1()`](https://github.com/rust-lang/rust/blob/e40e22be550fdcf5f11ba95cc84f3f337b0695f4/compiler/rustc_codegen_llvm/src/type_.rs#L137-L139).

**Comment by bjorn3** [comment]
cg_clif and cg_gcc will need these intrinsics too.

**Comment by calebzulawski** [comment]
> > Is that LLVM 14 specific? I'm pretty sure the bump to 15 is imminent.
> 
> I don't thiiink so?

It compiles on newer LLVM so at some point it became flexible enough to accept i8.



> cg_clif and cg_gcc will need these intrinsics too.

@bjorn3 do you expect that to be part of this PR, or just making a note of it?

**Comment by bjorn3** [comment]
Mostly making a note. I can implement it on the cg_clif side myself. I don't know what @antoyo prefers for cg_gcc.

**Comment by antoyo** [comment]
I'm also taking note for cg_gcc and I'll implement it myself.

**Comment by calebzulawski** [comment]
> > @Urgau I mean that I don't think the issue is LLVM 14 specific, I could be wrong.
> 
> Oh, yeah sorry. As for the issue here, I would just note that [`type_bool()`](https://github.com/rust-lang/rust/blob/e40e22be550fdcf5f11ba95cc84f3f337b0695f4/compiler/rustc_codegen_llvm/src/type_.rs#L82-L84) is indeed `i8` not `i1`; to have `i1` you should call [`type_i1()`](https://github.com/rust-lang/rust/blob/e40e22be550fdcf5f11ba95cc84f3f337b0695f4/compiler/rustc_codegen_llvm/src/type_.rs#L137-L139).

It looks like this worked!

**Review by compiler-errors — APPROVED** [review]

**Comment by RalfJung** [comment]
Any chance someone could make a PR to also implement these in Miri? :) Let me know if you need any pointers for getting started. The [existing SIMD intrinsics](https://github.com/rust-lang/miri/blob/master/src/shims/intrinsics/simd.rs) are probably a good template.

**Pull request merged**
