### PR TITLE
[MIR] Change "scopes" from "visibility scopes" to "source scopes".

### PR DESCRIPTION
**Pull request by eddyb**
These scopes are already used for source-oriented diagnostics, lint levels and unsafety checks.
This PR generalizes the naming around scopes, making the type `SourceScope`, and flips (across several commits) the relationship/priority between `LocalDecl`'s "visibility" and "syntactic" scopes.

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
beautiful little windy path :)

**Comment by eddyb** [comment]
@bors retry
* network issues

**Pull request merged**
