### PR TITLE
Stabilize remaining integer methods as `const fn`

### LINKED ISSUE #53718: Tracking Issue for more const int functions
(none exhaustive) list of `libcore::num`, which should be a `const fn`:

- `feature = const_int_rotate`
  - [x] `rotate_left` #53697 -- stabilized
  - [x] `rotate_right` #53697 -- stabilized
- `feature = const_checked_int_methods`
  - [x] `checked_add` [1] #68809
  - [x] `checked_sub` [1] #68809
  - [x] `checked_mul` [1] #68809
  - [x] `checked_div` [1] #68809
  - [x] `checked_rem` [1] #68809
  - [x] `checked_neg` [1] #68809
  - [x] `checked_shl` [1] #68809
  - [x] `checked_shr` [1] #68809
  - [x] `checked_abs` [1] #68809
- `feature = const_saturating_int_methods`
  - [x] `saturating_add` #58246
  - [x] `saturating_sub` #58246
  - [x] `saturating_mul` [1] #68809
- `feature = const_int_wrapping`
  - [x] `wrapping_add` #53697 -- stabilized
  - [x] `wrapping_sub` #53697 -- stabilized
  - [x] `wrapping_mul` #53697 -- stabilized
  - [x] `wrapping_div` [1] #68809
  - [x] `wrapping_rem` [1] #68809
  - [x] `wrapping_neg` #58044 -- stabilized
  - [x] `wrapping_shl` #53697 -- stabilized
  - [x] `wrapping_shr` #53697 -- stabilized
  - [x] `wrapping_abs` #63786 -- stabilized in 1.39
- `feature = const_int_overflowing`
  - [x] `overflowing_add` #53697
  - [x] `overflowing_sub` #53697
  - [x] `overflowing_mul` #53697
  - [x] `overflowing_div` [1] #68809
  - [x] `overflowing_rem` [1] #68809
  - [x] `overflowing_neg` #58044 -- stabilized
  - [x] `overflowing_shl` #53697
  - [x] `overflowing_shr` #53697
  - [x] `overflowing_abs`  #63786 -- stabilized in 1.39
- `feature = const_euclidean_int_methods`
  - [x] `checked_div_euc` [1] #68809
  - [x] `checked_mod_euc` [1] #68809
  - [x] `wrapping_div_euc` [1] #68809
  - [x] `wrapping_mod_euc` [1] #68809
  - [x] `overflowing_div_euc` [1] #68809
  - [x] `overflowing_mod_euc` [1] #68809
- `feature = const_int_pow`
  - [x] `pow`[1, 2] #68978
  - [x] `is_power_of_two` #65092
  - [x] `next_power_of_two` [1] #68978
  - [x] `checked_pow` [1] #68978
  - [x] `checked_next_power_of_two` [1] #68978
  - [x] `saturating_pow` [1, 2] #68978
  - [x] `wrapping_pow` [1, 2] #68978
  - [x] `wrapping_next_power_of_two` [1] #68978
  - [x] `overflowing_pow` [1, 2] #68978
- `feature = const_int_sign`
  - [x] `abs` #63786 -- stabilized in 1.39
  - [x] `signum` #61635
  - [x] `is_positive` #53697 -- stabilized
  - [x] `is_negative` #53697 -- stabilized
- `feature = const_int_conversion`
  - [x] `to_be_bytes` #53697
  - [x] `to_le_bytes` #53697
  - [x] `to_ne_bytes` #53697
  - [x] `from_be_bytes` #53697
  - [x] `from_le_bytes` #53697
  - [x] `from_ne_bytes` #53697
  - [x] `reverse_bits` #53697
- `feature = const_nonzero_int_methods`
  - [x] `NonZero*::new` [1] #68976

1. Requires conditionals. Tracking Issue: #49146 (implemented on nightly)
2. Requires loops. Tracking Issue: #52000 (implemented on nightly)

This issue has been assigned to @9999years via [this comment](https://github.com/rust-lang/rust/issues/53718#issuecomment-559985439).

### PR DESCRIPTION
**Pull request by jhpratt**
This pull request stabilizes the following methods as `const fn`:

- `i*::checked_div`
- `i*::checked_div_euclid`
- `i*::checked_rem`
- `i*::checked_rem_euclid`
- `i*::div_euclid`
- `i*::overflowing_div`
- `i*::overflowing_div_euclid`
- `i*::overflowing_rem`
- `i*::overflowing_rem_euclid`
- `i*::rem_euclid`
- `i*::wrapping_div`
- `i*::wrapping_div_euclid`
- `i*::wrapping_rem`
- `i*::wrapping_rem_euclid`
- `u*::checked_div`
- `u*::checked_div_euclid`
- `u*::checked_rem`
- `u*::checked_rem_euclid`
- `u*::div_euclid`
- `u*::overflowing_div`
- `u*::overflowing_div_euclid`
- `u*::overflowing_rem`
- `u*::overflowing_rem_euclid`
- `u*::rem_euclid`
- `u*::wrapping_div`
- `u*::wrapping_div_euclid`
- `u*::wrapping_rem`
- `u*::wrapping_rem_euclid`

These can all be implemented on the current stable (1.49). There are two unstable details: const likely/unlikely and unchecked division/remainder. Both of these are for optimizations, and are in no way required to make the methods function; there is no exposure of these details publicly. Per comments below, it seems best practice is to stabilize the intrinsics. As such, `intrinsics::unchecked_div` and `intrinsics::unchecked_rem` have been stabilized as `const` as part of this pull request as well. The methods themselves remain unstable.

I believe part of the reason these were not stabilized previously was the behavior around division by 0 and modulo 0. After testing on nightly, the diagnostic for something like `const _: i8 = 5i8 % 0i8;` is similar to that of `const _: i8 = 5i8.rem_euclid(0i8);` (assuming the appropriate feature flag is enabled). As such, I believe these methods are ready to be stabilized as `const fn`.

This pull request represents the final methods mentioned in #53718. As such, this PR closes #53718.

@rustbot modify labels to +A-const-fn, +T-libs

### CODE REVIEW

**Comment by jhpratt** [comment]
If anyone can let me know what I need to do to avoid errors, that would be great! I see that the `#[allow_internal_unstable]` isn't allowed on non-macros, but without it, I get an error.

**Comment by oli-obk** [comment]
The attribute you are looking for is `rustc_allow_const_fn_unstable`, not `allow_internal_unstable`. We used to use `allow_internal_unstable` for this, but have moved to a custom attribute.

**Comment by jhpratt** [comment]
Thanks @oli-obk; I'll give that a shot.

Going to hopefully include some more integer methods as well, as it doesn't look like the list on that issue was exhaustive. Just on the off chance someone wants to review this before it's completed.

**Comment by oli-obk** [comment]
cc @rust-lang/wg-const-eval stabilization of lots of inherent methods on integers

**Comment by jhpratt** [comment]
Ok, just pushed up what represents the stabilization of all unstably-const inherent integer methods as `const fn`. The list at the top of this PR is correct.

Let me know what needs to be changed, if anything! I'd absolutely love to see these methods stabilized as `const`; it would reduce the amount of code written and increase clarity to anyone reading.

**Comment by RalfJung** [comment]
I assume those all have pretty trivial code, so -- no objections from my side (but this is not a review, I hope someone goes through all of these individually and makes sure they are truly trivially CTFE-safe ;).

What seems fishy though is the use of `rustc_allow_const_fn_unstable`. Haven't we usually avoided this by marking the intrinsic as const-stable?

**Comment by jhpratt** [comment]
Yeah, they're all quite trivial to implement, so I suspect they won't change in the slightest in the future.

I can stabilize the intrinsics as `const` if desired; I've no idea what is typically done.

**Comment by CDirkx** [comment]
I've looked into stabilizing these methods before, the `rustc_allow_const_fn_unstable` is indeed not necessary when the intrinsics `unchecked_div` and `unchecked_rem` are stabilized. At the time I believed stabilization of these intrinsics was blocked on `const_err`, but now looking at it I don't think so?

`NonZero*::leading_zeros` and `trailing_zeros` are the only remaining const-unstable methods of the non-zero integers, I think they could also be included in this PR.

**Comment by jhpratt** [comment]
@CDirkx The `NonZero*` methods are unstable, though, whereas all methods so far mentioned are already stable (just not `const`).

**Comment by RalfJung** [comment]
> At the time I believed stabilization of these intrinsics was blocked on const_err, but now looking at it I don't think so?

Well, the intrinsics can cause UB. But even if the intrinsics are const-stable, they are still not stable, so they cannot be *directly* called from stable code -- and the wrappers being stabilized in this PR are all safe.

**Comment by jhpratt** [comment]
Now that you mention that...I recall there being an issue somewhat recently where someone wanted to block something being const stable if it wasn't stable in general. Would the stabilization of these intrinsics as const fall under that? Or is that someone else's problem (in all seriousness)?

**Comment by RalfJung** [comment]
Intrinsics are special, almost all of them are unstable and only exposed through other, stable functions.

**Comment by jhpratt** [comment]
I'm aware. Just wasn't sure if declaring an intrinsic const-stable might have unintended side effects down the road (internally).

**Comment by RalfJung** [comment]
Well, it's hard to anticipate unanticipated side-effects. ;) It *shouldn't* have any... right, @oli-obk ?

**Comment by oli-obk** [comment]
Yea the `unchecked_div` intrinsic can be made const-stable, we already support the equivalent MIR operation and we may want to lower the intrinsic to that primitive operation at some point.

**Comment by jhpratt** [comment]
Went ahead and stabilized the two intrinsics as const.

I can't ping teams as I'm not a member of the rust-lang GitHub org, but this needs lang team approval per comments in the code.

@rustbot modify labels to +T-lang

**Comment by RalfJung** [comment]
These newly-stabilized intrinsics are unsafe, and their UB detection during CTFE is reasonably well-tested in `src/test/ui/consts/const-int-unchecked.rs`. Anyway that is not even being exposed by this PR, only safe wrappers are.

I think this is ready for FCP by the relevant teams (libs, lang).

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by bjorn3** [comment]
Looking at the page source, the bot replied at 2021-01-15T15:56:05Z. You commented at 2021-01-15T15:56:26Z. So it supposedly replied 21 seconds before you commented. I presume this is a server whose clock drifted a bit.

**Comment by BurntSushi** [comment]
Maybe I'm just out of step with how we treat the `core::intrinsics` module, but why are we stabilizing routines there? I thought we generally did not want to stabilize compiler intrinsics directly?

**Comment by CDirkx** [comment]
The intrinsics are being stabilized _as const_, not stabilized themselves.

**Comment by BurntSushi** [comment]
@CDirkx OK, thanks. What does that mean?

**Comment by RalfJung** [comment]
It means that stable `const fn` can call them. But they cannot be called directly.

`const` exposes the implementation details of a function to a much larger degree than regular functions do, and for this reason the `const` stability checker is *recursive*: a stable `const fn` may only perform other stable operations. This ensures that we do not accidentally stabilize aspects of the CTFE machine that are not yet meant to be stable.

**Comment by scottmcm** [comment]
Makes sense to me!  If one can already do division in const fn, I can't imagine that checked_div and friends could cause any issue.

**Comment by jhpratt** [comment]
Ping for review.

@KodrAus @cramertj @joshtriplett @nikomatsakis @pnkfelix @withoutboats

**Comment by jhpratt** [comment]
Should I wait until we've officially missed the beta cut to bump the version to 1.52? FCP is ten days, so figure it would have to start within the next five or so to have time to merge afterwards as well.

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Review by dtolnay — APPROVED** [review]

**Comment by jhpratt** [comment]
Just seeing the milestone was set to 1.52. Did this miss the cutoff for beta (set to be released this coming Thursday)? If so, the attributes need to be updated in the code.

**Comment by RalfJung** [comment]
Beta cutoff happens today (always on the Monday before the release, see [here](https://forge.rust-lang.org/release/process.html)). So... this was a race condition.^^

But looking at the `beta` branch, I think the cutoff did not happen yet, so the Milestone set by the bot is likely wrong. Not sure though. Cc @pietroalbini @Mark-Simulacrum

**Comment by jhpratt** [comment]
Wouldn't this fall under "promote master to beta", which happens on Tuesday? Unless that document is wrong for whatever reason.

**Comment by tspiteri** [comment]
It appears to me the critical moment is the merging of the [version bump PR](https://github.com/rust-lang/rust/pull/81792) which was opened on Friday (T-6) and merged on Saturday, so that this PR did miss 1.51. :(

I think there is a typo in the release process document section about promoting master to beta: "the PR opened last Monday" is probably referring to the version bump PR and should be "the PR opened last Friday".

**Comment by pietroalbini** [comment]
We changed the release process a couple releases ago, now the cutoff happens on the Friday PR.

**Comment by jhpratt** [comment]
Probably worth updating the process document to avoid confusion.

Should I submit a PR to change these few lines or does someone else want to do it? I don't really care either way; it's obviously a trivial change.

Also cc @dtolnay so you don't approve anything else like this 🙂

**Comment by m-ou-se** [comment]
> Should I submit a PR to change these few lines

@jhpratt If you want to do that, that'd be useful. Thanks :)

**Comment by pthariensflame** [comment]
`relnotes` needed, I think.

**Pull request merged**
