### PR TITLE
doc: make into_iter example more concise

### PR DESCRIPTION
**Pull request by tshepang**
Also, remove dupe example

### CODE REVIEW

**Comment by steveklabnik** [comment]
The example is duplicated on purpose, so that each thing has its own docs with examples.

I don't have any particular feelings about making it more concise, but the build is failing.

**Comment by tshepang** [comment]
looks like a spurious failure

**Comment by tshepang** [comment]
I will leave it duplicated then

**Comment by alexcrichton** [comment]
r? @steveklabnik 

Mind reviewing this Steve?

**Pull request merged**
