### PR TITLE
Add backquotes to have better looking rust code

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by P1start** [comment]
I don’t think these messages are Markdown (they’re just printed to the terminal), so why would backticks help here? Perhaps it would be better to simply indent the code, e.g.:

```
Foo bar baz:

    let foo = 1;
    let bar = foo;

Fizzbar foobang qux, frob quxbaz.
```

**Comment by GuillaumeGomez** [comment]
Then did I have to add some ([here](https://github.com/rust-lang/rust/pull/24482#discussion_r28468216)) ? Kinda weird.

**Comment by P1start** [comment]
I disagree with @Manishearth there. I don’t think any non-Markdown code should be using ```` ``` ```` to represent code blocks. Indentation is OK, and actually looks clearer in my opinion than using ```` ``` ````. That said, I’d still like to hear @Manishearth’s reasoning about backticks being easier to read.

**Comment by Manishearth** [comment]
@P1start My point is that there should be something distinguishing code, especially block code, from regular text. It helps the flow of reading.

Perhaps @steveklabnik has some opinions on this ?

**Comment by GuillaumeGomez** [comment]
Maybe we could use "```" as separator to print console color codes ? I'd be interested in implementing such a thing.

**Comment by Manishearth** [comment]
Hm, so the code printed should be slightly greyer or something?

We'd need to pick out the existing foreground color and darken/lighten it a bit.

Alternatively, we can indent it. That's what man pages do.

**Comment by GuillaumeGomez** [comment]
Yes, that's what I was thinking about.

**Comment by huonw** [comment]
It makes a lot of sense to me for these errors to also have a prettier web/rendered interface, which would work best if we formatted the messages as real markdown.

Of course block code can be denoted by indentation and that probably works best here.

**Comment by GuillaumeGomez** [comment]
@huonw: I think it would be better to use a separator (like the current or another, doesn't matter) and then make a pretty printing in console (since that's where it will be displayed).

**Comment by huonw** [comment]
It makes a lot of sense to me for these errors to also have a prettier web/rendered interface, which would work best if we formatted the messages as real markdown.

Of course block code can be denoted by indentation and that probably works best here.

**Comment by Manishearth** [comment]
So a concrete solution:

When printing to any terminal: Indent all code blocks in the diagnostics

When printing to a color-supported terminal (i.e. not to file), additionally mark inline code blocks as bold.

**Comment by GuillaumeGomez** [comment]
I agree with @Manishearth's proposition. However, how do you intent to let know what part of the solution will have a "special" print ? For the moment, "```" and I'm fine with it but someone else maybe would want another one ?

**Comment by Manishearth** [comment]
As in?

**Comment by huonw** [comment]
My point was that they won't always be displayed in the terminal. Also, if we want to do fancy formatting in the terminal, there's no particular reason we can't do that by parsing and "rendering" real markdown (I.e. with a proper parser etc) rather than an even more adhoc markup language.

We could even do syntax highlighting of code like rustdoc.

**Comment by Manishearth** [comment]
I guess we should do indentation for now, and leave the rest to a separate issue?

**Comment by GuillaumeGomez** [comment]
Well, I can change my current PR depending on what you need.

**Comment by michaelsproul** [comment]
I like Huon's idea of using Markdown and then outputting it appropriately for the different backends. I think we should leave everything the same for now and update to Markdown syntax once the infrastructure is in place. I've started working on something similar already, so I'll add this as a goal.

**Comment by GuillaumeGomez** [comment]
So ?

**Comment by Manishearth** [comment]
So...change the diagnostics printer to indent code blocks :)

**Comment by GuillaumeGomez** [comment]
Done ! :-)

**Comment by Manishearth** [comment]
I meant that we should modify the code responsible for displaying these strings to indent code fences, that's a more resilient solution.

@huonw what do you think?

**Comment by GuillaumeGomez** [comment]
Oh right ! Well, I can do that if no one's working on it. Should I revert my last commit ?

**Comment by huonw** [comment]
That sounds good to me, although landing the back-ticks first/separately is fine by me.

Maybe @steveklabnik has opinions.

**Comment by GuillaumeGomez** [comment]
I added back the backquotes. I'll rebase when I'll be back home.

**Comment by GuillaumeGomez** [comment]
I removed useless commits.

**Comment by steveklabnik** [comment]
I feel like the triple ticks don't hurt.

**Comment by GuillaumeGomez** [comment]
Good ! r+ ?

**Pull request merged**
