### PR TITLE
Stabilize fn-like proc macros in expression, pattern and statement positions

### PR DESCRIPTION
**Pull request by petrochenkov**
I.e. all the positions in which stable `macro_rules` macros are supported.

Depends on https://github.com/rust-lang/rust/pull/68716 ("Stabilize `Span::mixed_site`").

cc https://github.com/rust-lang/rust/issues/54727
cc https://github.com/rust-lang/rust/issues/54727#issuecomment-580647446

Stabilization report: https://github.com/rust-lang/rust/pull/68717#issuecomment-623197503.

### CODE REVIEW

**Review by pksunkara — APPROVED** [review]

**Comment by petrochenkov** [comment]
This is still waiting on me writing the stabilization report, but it's also blocked on https://github.com/rust-lang/rust/pull/68716.

**Review by pksunkara — APPROVED** [review]

**Comment by mark-i-m** [comment]
I think this is still waiting for a stabilization report and FCP, right?

**Comment by petrochenkov** [comment]
Yep, writing it at the moment.

**Comment by petrochenkov** [comment]
## Stabilization report

This PR stabilizes function-like procedural macros in expression, pattern and statement positions.
```rust
let expr = mac!(); // expression
match expr {
    mac!() => {} // pattern
}
mac!(); // statement
```

Stabilization currently targets Rust 1.45 (July 16th 2020), hopefully one month will be enough for FCP.

Tests for these macros can be found by looking at the diff in this PR (files in which `#![feature(proc_macro_hygiene)]` is removed).

### Some history

The feature was implemented together with all other proc macros somewhere in 2017-2018.

It could be stabilized earlier, somewhere soon after 2018 edition, but it would have to use only call-site hygiene in that case (aka ~no hygiene).
Macros in expression and statement positions can 1) consume local variables from their environment code and 2) produce local variables consumable from their environment code.
Having non-hygienic local variables is undesirable, and is a regression from `macro_rules` in user experience, so proc macros in these position were mostly waiting for some other kind of hygiene to be stabilized.

People could still work around the feature gate with stable item macros (https://crates.io/crates/proc-macro-hack) and some indirection, but the workarounds were inconvenient.

Now the other kind of hygiene is stabilized. [`Span::mixed_site`](https://github.com/rust-lang/rust/pull/68716) exposes `macro_rules` hygiene to proc macro authors, so they can produce token streams identical to those produced by `macro_rules` in hygienic properties.

Proc macro authors are strongly encouraged to use `Span::mixed_site` instead of `Span::call_site` in all macros that can be used in expression, pattern and statement positions.
It's also encouraged to use `Span::mixed_site` instead of `Span::call_site` everywhere else because it's a strictly better default, unless you specifically want a non-hygienic *local variable*, but that's a rare case.

### Detailed description

The newly stabilized macros should be identical to `macro_rules` called in the same positions.
In both cases the macro takes token stream as an input, and produces a token stream as an output, which is then parsed as an AST fragment with the fragment kind depending on the position.
The difference is that proc macros produce the token stream programmatically rather than through `macro_rules` DSL, which gives more control over hygiene in particular.

The new macros are expected to use `Span::mixed_site` (possibly with location adjusted with `Span::located_at`) for identifiers to maintain hygienic properties equivalent to `macro_rules`.
If `Span::call_site` is used, then local variables used or produced by the new macros may interfere with other code at call site.

**Comment by petrochenkov** [comment]
@rust-lang/lang 
Could someone start an FCP?

**Comment by jhpratt** [comment]
I'd just like to thank you and everyone else for your hard work!

**Comment by Lokathor** [comment]
This also allows expressions at the module level right?

That is:
```rust
const FOO: &str = proc_macro_call!(args to compute some string literal);
```

**Comment by petrochenkov** [comment]
@Lokathor 
Yes, proc macros are supported in any locations where expressions can be used.

**Comment by joshtriplett** [comment]
@rfcbot merge
Based on @petrochenkov's [stabilization report](https://github.com/rust-lang/rust/pull/68717#issuecomment-623197503)

**Comment by nikomatsakis** [comment]
I'm in favor of moving forward with this, as I think that having expression level procedural macros is a great enabler.

**Comment by ErichDonGubler** [comment]
I wasn't able to find this in the conversation, so maybe I missed it, but will there be a lint to assist with encouraging (old in particular) code to move to usage of `Span::mixed_site`? I would consider that orthogonal to stabilization I guess, but I know it'd be helpful for old proc macros I've written.

**Comment by petrochenkov** [comment]
@ErichDonGubler 
There's some discussion about migrating to `Span::mixed_site` on the PR stabilizing it - https://github.com/rust-lang/rust/pull/68716.

I'm not sure how we can lint this besides simply reporting all uses of `Span::mixed_site` and `quote!`, but that's probably not desirable.
In most cases the migration can be done by mass-replacing `call_site` -> `mixed_site` and `quote!` -> `quote_spanned!(Span::mixed_site())`.
Comments starting from https://github.com/rust-lang/rust/pull/68716#issuecomment-583761512 list some cases in which extra work may be required.

**Comment by Aaron1011** [comment]
@bors retry

A job was stuck for 3 hours on 'Installing msys2 packages' (https://dev.azure.com/rust-lang/rust/_build/results?buildId=29511&view=logs&j=339a807e-05eb-50a3-f69a-0d7a3a5b2cef), so the build is going to time out.

**Comment by mati865** [comment]
@Aaron1011 can you close the tree? It's msys2 issue.
I'm working on a workaround in https://github.com/rust-lang/rust/pull/72332

**Pull request merged**
