### PR TITLE
Stabilization change for mod.rs

### PR DESCRIPTION
**Pull request by blitzerr**
This change is in response to https://github.com/rust-lang/rust/issues/53125.
The patch makes the feature accepted and removes the tests that tested the
non-accepted status of the feature.

### CODE REVIEW

**Comment by eddyb** [comment]
cc @Mark-Simulacrum

**Comment by nikomatsakis** [comment]
I think this was merged by @kennytm as part of #54146?

**Comment by blitzerr** [comment]
@nikomatsakis I see this pull in the list of the 15 pulls that were merged. Is anything else required from me on this?

**Pull request closed without merging**
