### PR TITLE
trpl: fix some broken internal links

### PR DESCRIPTION
**Pull request by durka**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ dc6eb7839c8b35c997e95b2b94fbf22f9eda9c4c rollup

Thanks!

**Comment by durka** [comment]
The same link is broken in the next chapter (Enums) too. Should I add that to this PR, or is it too late?

**Comment by alexcrichton** [comment]
Yeah adding it to this PR is fine, feel free to just ping me once it's in!

**Comment by durka** [comment]
@alexcrichton pushed.

**Comment by durka** [comment]
@alexcrichton actually maybe tell bors to hold off on this and I'll turn it into a more general "fix a bunch of broken TRPL links" PR.

**Comment by alexcrichton** [comment]
@bors: r-

Ok!

**Comment by steveklabnik** [comment]
@durka now that you have this extra commit, i'm assuming this is good to go

**Comment by durka** [comment]
Should be! I ran out of time going through the book, but I'll see if I
catch any more when I get back to Rust learning.

**Pull request merged**
