### PR TITLE
Make novel structural match violations not a `bug`

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Fixes (on master) #73431.

Ideally, `CustomEq` would emit a strict subset of the structural match errors that are found by `search_for_structural_match_violation`, since it allows more cases due to value-based reasoning. However, const qualification is more conservative than `search_for_structural_match_violation` around associated constants, since qualification does not try to substitute type parameters.

In the long term, we should probably make const qualification work for generic associated constants, but I don't like extending its capabilities even further.

r? @pnkfelix

### CODE REVIEW

**Comment by pnkfelix** [comment]
Should the warning text reference some issue for further info?

**Comment by ecstatic-morse** [comment]
Done. See #73448.

**Comment by pnkfelix** [comment]
As discussed in private with @ecstatic-morse , i cannot immediately tell if this represents a hole in the structural-match check that we will need to plug (and thus maybe we should have something stronger than a `warn!` here, which will only fire if one uses `RUSTC_LOG=warn` or similar).
 
But it probably isn't worth the effort of putting in the plumbing to issue a proper lint warning here; instead effort should be focused on fixing #73448 itself.

and in any case, this PR as it stands fixes the ICE, which trumps all else at the moment.

@bors r+

**Comment by pnkfelix** [comment]
unilaterally accepting for beta-backport.

**Comment by Dylan-DPC** [comment]
giving this priority since it is a backport 
@bors p=1

**Comment by RalfJung** [comment]
Yielding to rollup
@bors retry

**Pull request merged**
