### PR TITLE
Switch inline(always) in core/src/fmt/rt.rs to plain inline

### PR DESCRIPTION
**Pull request by saethlin**
I have a vague memory of these being instantiated a lot. Let's ask perf.

Looks like this is an improvement!

### CODE REVIEW

**Comment by saethlin** [comment]
Neat.

**Comment by saethlin** [comment]
r? libs

**Comment by tgross35** [comment]
It looks like these were added as part of https://github.com/rust-lang/rust/pull/110766 (@m-ou-se), any chance this improves compile times but trades it for runtime formatting performance?

**Comment by Kobzol** [comment]
More improvements than regressions.

@rustbot label: +perf-regression-triaged

**Pull request merged**
