### PR TITLE
WIP inherited deprecation fixes #26040

### LINKED ISSUE #26040: Deprecated attribute should be inherited
We've cycled through a few different inheritance strategies for stability attributes, but with the move to release channels we've lost inheritance for the deprecated attribute. This appears not to be an intentional choice, and there are strong ergonomic reasons to use inheritance here.

We should alter the lint's computation so that deprecation is inherited. Should be pretty easy to do.

### PR DESCRIPTION
**Pull request by Gankra**
Uncertain if this is the desired effect/strategy/testing.

r? @aturon

### CODE REVIEW

**Comment by Gankro** [comment]
cc @brson if you have an opinion

**Comment by brson** [comment]
Patch looks ok to me. I'm curious what impacts this had on the deprecatedness of std. Did anything new get deprecated?

**Comment by brson** [comment]
Oh, there's a weird case in this patch: since it applies the parent deprecation tag, it could potentially apply the deprecation tag from one feature to a different feature, which is pretty bogus. It could possibly also apply a deprecated tag to something without an explicit stability level at all, which is illegal.

It's not likely to happen in sane code, but it could. You might add more conditions that the parent has the same stability level and feature.

**Comment by Gankro** [comment]
Yeah I wasn't sure how "no stability" was supposed to interact here. I'm not sure what you mean about one feature getting the deprecation of another. It seems like if I deprecate a whole module, anything in there should inherit that, regardless of what features its under? 

Would you be able to provide some test cases/examples of what you're imagining?

**Comment by brson** [comment]
The concern about accidentally deprecating multiple features isn't as important as I was thinking, since features can be partially deprecated, and deprecations can happen during any version.

Here's one example where inheritance crosses features and could cause incorrect deprecation.

```
pub reexport a::f;

#[unstable(feature = "foo", ...)]
pub mod a {
    #[stable(feature = "bar", ...)]
    pub fn f() { }
}
```

With deprecation inheritance, if `a` is deprecated, the function `f` in the other feature 'bar' is also deprecated.

There's a current rule that says that anything marked deprecated, must also be explicitly marked unstable or stable. This is to prevent unstable+deprecated things accidentally making their way into stable releases by becoming stable+deprecated. With stable not inheriting though the only error I can think of making would be accidentally tagging something that has inherited deprecation with stable.

Imagine:

```
pub reexport a::f;

#[unstable(feature = "foo", ...)]
pub mod a {
    #[unstable(feature = "bar", ...)]
    pub fn f() { }
}
```

Then mod `a` is deprecated, deprecated `f` as well:

```
pub reexport a::f;

#[unstable(feature = "foo", ...)]
#[deprecated(...)]
pub mod a {
    #[unstable(feature = "bar", ...)]
    pub fn f() { }
}
```

Now part of feature 'bar' is unstable. Then five years later somebody says, 'bar' is finally stable. So they convert all the unstable bars to stable bars, without thinking about it too hard:

```
pub reexport a::f;

#[unstable(feature = "foo", ...)]
#[deprecated(...)]
pub mod a {
    #[stable(feature = "bar", ...)]
    pub fn f() { }
}
```

Now they've created a stable function that is immediately deprecated.

That's the only problematic counter-example i can think of offhand.

**Comment by Gankro** [comment]
Since deprecations and stable are marked with a `since` it seems possible
to largely guard against this by checking deprecated_since >= stable_since.
Then this can only slip in if a deprecation and stabilization land in the
same release. Maybe not sufficient, though.

**Comment by brson** [comment]
@Gankro, yes, assuming the person who switches the function from `unstable` to `stable` also updates the `since` field, your proposed assertion would catch the error. It sounds like a reasonable precaution to take, but really this doesn't *need* to be airtight as long as reviewers pay attention to stabilization.

**Comment by brson** [comment]
Oh, `unstable` doesn't have a 'since' field, so there's no need to 'remember' to update it when switching from 'unstable' to 'stable'.

**Comment by Gankro** [comment]
updated to validate stability against deprecation version.

**Pull request merged**
