### PR TITLE
Update rustc-perf

### PR DESCRIPTION
**Pull request by weihanglo**
Just check if the latest commit works.

https://github.com/rust-lang/rustc-perf/compare/4f313add609f43e928e98132358e8426ed3969ae...cc81f9654dac3fe08de286907dba747538417afd

See discussion on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/tempfile.20in.20rustc-perf.20make.20it.20hard.20to.20configure.20vendor/near/440442827

r? ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
> Compile-time: No results

Something went wrong, right?

**Comment by Kobzol** [comment]
No, everything seems fine :) Just no relevant differences were found.

**Comment by weihanglo** [comment]
Okay thanks! I guess we're ready to bump this before the diff becomes too big?

**Comment by Kobzol** [comment]
I don't think that we really need to update rustc-perf, there haven't been any relevant changes as far as I remember, but it also shouldn't hurt. So if you want to update it, feel free to r=me.

**Comment by weihanglo** [comment]
> there haven't been any relevant changes as far as I remember

That's true. I am doing this because we might have some more changes ([license update](https://github.com/rust-lang/team/pull/1462) from our git dependencies, and a potential new [`--cargo-config` flag](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/tempfile.20in.20rustc-perf.20make.20it.20hard.20to.20configure.20vendor)) in the future, so better checking if it can be merged and merge it now.

Thanks for the review! I am going to merge :)

@bors r=Kobzol

**Pull request merged**
