### PR TITLE
.to_string() -> String::from

### PR DESCRIPTION
**Pull request by steveklabnik**
I wanted to do this for just the docs, as people over-use the very slow `.to_string()`. Then I was like "I wonder how this looks in the compiler", and turns out there's about 450 files. So I updated some of them. I am willing to update them all, but wanted to check if that's okay before I bother.

Even if the compiler changes get rejected, I'd still like to change the docs.

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'm not particularly a huge fan of transitions like this, saying something like `.to_string()` is slow I've often found is akin to saying that memory is slower than registers. Of course it's true, and it really matters sometimes, but 99% of the time that's not the case.

I still believe it's more idiomatic to use `.to_string()` (it's obvious what it's doing and far more general)

**Comment by tshepang** [comment]
@alexcrichton I thought `to_str` was considered less idiomatic. I was probably confusing it with (the now-deprecated) `from_str`.

**Comment by bstrie** [comment]
to_string will be idiomatic once specialization lands. In addition, I don't believe we've ever advocated String::from, instead I've always seen to_owned.

**Comment by steveklabnik** [comment]
I've been using and seeing `String::from` for literals a lot, and it's really grown on me. I do think `to_string()` is better than `.to_owned()`, which is imho for generic code only.

Anyway, got my answer! Thanks.

**Comment by tshepang** [comment]
Same here... `String::from` grew on me @steveklabnik.

**Pull request closed without merging**
