### PR TITLE
Stabilize mem::take (mem_take)

### PR DESCRIPTION
**Pull request by jonhoo**
Tracking issue: https://github.com/rust-lang/rust/issues/61129

r? @matklad

### CODE REVIEW

**Comment by SimonSapin** [comment]
@rfcbot fcp merge

**Comment by SimonSapin** [comment]
Looks good, thanks!

@bors r+

**Comment by lzutao** [comment]
Ping?

**Comment by SimonSapin** [comment]
Ah, I didn’t realize this had been rebased…

@bors r+

**Pull request merged**
