### PR TITLE
Propagate expected type hints through struct literals.

### LINKED ISSUE #40355: Crate with large static map in external crate fails to compile
Possibly related: https://github.com/rust-lang/rust/issues/36799
When attempting to compile https://github.com/urschrei/lonlat_bng  using `cargo test` or `cargo build --release` on OS X using beta (5276ba72e) or nightly (b1e31766d), the compilation step doesn't complete (or at least, it hadn't after around 11 hours). It also times out on Linux [Nightly](https://travis-ci.org/urschrei/lonlat_bng/jobs/199261902) and [Beta](https://travis-ci.org/urschrei/lonlat_bng/jobs/199261898), using Travis.  

On current OS X Stable (021bd294c), it compiles as expected within ~95s locally, [and on Linux Stable, using Travis](https://travis-ci.org/urschrei/lonlat_bng/jobs/199261885), although `rustdoc` for the external crate fails with an OOM error on Linux.

This is probably due to the size of the static map in the external crate (https://github.com/urschrei/ostn15_phf), which is around 40.9mb.

### PR DESCRIPTION
**Pull request by eddyb**
Partial fix for #31260 to maximize backwards-compatibility, i.e. the hint is provided but not coerced to.

The added test works because `{...; x}` with a hint of `T` coerces `x` to `T`, and the reasoning why that is slightly different has to do with DSTs: `&Struct { tail: [x] }: &Struct<[T]>` has a hint of `[T]` for `[x]`, but the inferred type should be `[T; 1]` to succeed later, so `[x]` shouldn't be *forced* to be `[T]`.

*However*, implementing that complete behavior in a backwards-compatible way may be non-trivial, and has not yet been fully investigated, while this PR fixes #40355 and can be backported.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
r=me pending crater.

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/compiler meeting. It's a tough call regarding the backport. On the one hand, we definitely want to fix the bug, and it affects anybody using the `phf` crate to some degree. On the other hand, changes to inference are notoriously sensitive, and so we risk unintended side-effects.

Let's see what crater has to say (a clean run would help allay fears) before reaching a final decision.

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/94bcce4c4d11ef00d486864ad7826da8) only contains false positives!

**Comment by nikomatsakis** [comment]
OK, we're marking as beta-accepted. Live on the edge!

**Comment by nikomatsakis** [comment]
Looks like this was never formally r+'d?

**Comment by eddyb** [comment]
@nikomatsakis @brson If this made it into the stable release but wasn't merged on nightly, it might be missing from beta. I'll re-nominate it to make sure we don't forget to check (and backport if needed).

**Pull request merged**
