### PR TITLE
fixes #27124 for freebsd

### LINKED ISSUE #27124: Rust building is broken for BSD system
Starting with the latest update of LLVM, several BSD system don't be able to build rust anymore.

At least:
- freebsd: http://buildbot.rust-lang.org/builders/auto-freebsd10_64-1/builds/2/steps/compile/logs/stdio
- bitrig: http://buildbot.rust-lang.org/builders/auto-bitrig-64-opt/builds/1186/steps/compile/logs/stdio
- openbsd

The error message is the same of these three platform (here bitrig message):
```
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib" "x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib/std-7e44814b.0.o" "-o" "x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib/libstd-7e44814b.so" "x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib/std-7e44814b.metadata.o" "-Wl,-O1" "-nodefaultlibs" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/libcollections-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/librand-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/liballoc-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/librustc_unicode-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/liblibc-7e44814b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.M1grNw2xGkYD/libcore-7e44814b.rlib" "-Wl,--no-whole-archive" "-L" "x86_64-unknown-bitrig/rt" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/x86_64-unknown-bitrig/llvm/Release/lib" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/x86_64-unknown-bitrig/stage1/lib/rustlib/x86_64-unknown-bitrig/lib" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/.rust/lib/x86_64-unknown-bitrig" "-L" "/home/builder/rust-buildbot/slave/auto-bitrig-64-opt/build/obj/lib/x86_64-unknown-bitrig" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "rust_builtin" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-l" "backtrace" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-l" "rustrt_native" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "pthread" "-l" "c++abi" "-l" "c" "-l" "m" "-shared" "-l" "compiler-rt"
note: /tmp/rustc.M1grNw2xGkYD/libcollections-7e44814b.rlib: member /tmp/rustc.M1grNw2xGkYD/libcollections-7e44814b.rlib(__.SYMDEF) in archive is not an object
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

cc: @dhuseby @wg @vhbit @mneumann

### PR DESCRIPTION
**Pull request by dhuseby**
freebsd linking fix.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Like on the other PR could this actually just delete the `archive_format` option altogether? Other than that r=me, and feel free to roll this into the other PR as well.

**Comment by alexcrichton** [comment]
It looks like "gnu" works for OpenBSD on #27144, so perhaps this could also use "gnu"?

**Comment by dhuseby** [comment]
Let me try "gnu" on FreeBSD and report back.

**Comment by dhuseby** [comment]
@alexcrichton using "gnu" works on both x86_64 and i686 freebsd.

**Comment by dhuseby** [comment]
@alexcrichton "gnu" works for FreeBSD as well.

**Pull request merged**
