### PR TITLE
rustdoc: separate test collection from the main "clean"-ing pipeline.

### PR DESCRIPTION
**Pull request by eddyb**
While reusing the documentation "clean"-ing infrastructure for collecting code examples to test may have seemed appealing at some point, doing the same through a HIR visitor is barely any harder.
At the same time, supporting both "regular documentation" and "test collection" modes in `rustdoc::clean` has its cost, requiring any use of a `TyCtxt` to be speculative, and provide some sort of fallback.

This simplification is the first step towards bringing rustdoc closer to the compiler, and perhaps even unifying the "local crate" (based on the HIR AST) and "inlinined across crates" (based on crate metadata and typesystem information) implementations of rustdoc.

Sadly, not all possible changes to rustdoc will be uncontroversial, so I'm starting small with this patch.

### CODE REVIEW

**Comment by eddyb** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Huge 👍 !

**Comment by alexcrichton** [comment]
Sounds like a good change to me, there's *tons* of technical debt in rustdoc to be shed at this point

**Comment by GuillaumeGomez** [comment]
```
failures:

---- cyclic_dev_dep_doc_test stdout ----
	running `C:\bot\slave\auto-win-msvc-64-cargotest\build\obj\build\ct\cargo\target\debug\cargo test`
thread 'cyclic_dev_dep_doc_test' panicked at '
Expected: execs
    but: differences:
  6 - |running 1 test|
    + |running 0 tests|

  7 - |test _0 ... ok|
    + ||

  8 - ||
    + |test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured|

  9 - |test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured|
    + ||

 10 - ||
    +


other output:
`   Compiling foo v0.0.1 (file:///C:/bot/slave/auto-win-msvc-64-cargotest/build/obj/build/ct/cargo/target/cit/t14/foo)
   Compiling bar v0.0.1 (file:///C:/bot/slave/auto-win-msvc-64-cargotest/build/obj/build/ct/cargo/target/cit/t14/foo/bar)
    Finished debug [unoptimized + debuginfo] target(s) in 1.3 secs
     Running target\debug\deps\foo-6688213a3cfc5207.exe
   Doc-tests foo
`', C:/msys64/slave/auto-win-msvc-64-cargotest/cargo-home\registry\src\github.com-1ecc6299db9ec823\hamcrest-0.1.1\src\core.rs:31
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    cyclic_dev_dep_doc_test

test result: FAILED. 54 passed; 1 failed; 0 ignored; 0 measured



command did not execute successfully: "C:\\bot\\slave\\auto-win-msvc-64-cargotest\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\release\\cargotest.exe" "C:\\bot\\slave\\auto-win-msvc-64-cargotest\\build\\obj\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "C:\\bot\\slave\\auto-win-msvc-64-cargotest\\build\\obj\\build\\ct"
expected success, got: exit code: 101
```

**Comment by eddyb** [comment]
@alexcrichton Should the PR Travis builds include cargotest?

**Comment by alexcrichton** [comment]
@eddyb yeah once we start gating on travis I'd like to look into PR test coverage

**Comment by eddyb** [comment]
Travis passed but the OSX builds are broken. @bors r=nrc

**Pull request merged**
