### PR TITLE
Implement basic support for PGO in rustbuild for rustc

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This implements support for applying PGO to the rustc compilation step (not
standard library or any tooling, including rustdoc). Expanding PGO to more tools
is not terribly difficult but will involve more work and greater CI time
commitment.

For the same reason of avoiding greater time commitment, this currently avoids
implementing for platforms outside of x86_64-unknown-linux-gnu, though in
practice it should be quite simple to extend over time to more platforms. The
initial implementation is intentionally minimal here to avoid too much work
investment before we start seeing wins for a subset of Rust users.

The choice of workloads to profile here is somewhat arbitrary, but the general
rationale was to aim for a small set that largely avoided time regressions on
perf.rust-lang.org's full suite of crates. The set chosen is libcore, cargo (and
its dependencies), and a few ad-hoc stress tests from perf.rlo. The stress tests
are arguably the most controversial, but they benefit those cases (avoiding
regressions) and do not really remove wins from other benchmarks.

The primary next step after this PR lands is to implement support for PGO in
LLVM. It is unclear whether we can afford a full LLVM rebuild in CI, though, so
the approach taken there may need to be more staggered. rustc-only PGO seems
well affordable on linux at least, giving us up to 20% wall time wins on some
crates for 15 minutes of extra CI time (1 hour up from 45 minutes).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
So I guess we know that this empty file actively hurts - but at least PGO is having an effect :)

@michaelwoerister - can you share what workload you used? I pushed an update to use libcore, we'll see if that works better

@bors try @rust-timer queue

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

Dropped libcore collection from the PGO set. I think we're going to need to work in some incremental somehow though.

**Comment by michaelwoerister** [comment]
FYI: I started working on something similar for the LLVM part in https://github.com/michaelwoerister/rust/tree/bootstrap-pgo.

**Comment by michaelwoerister** [comment]
> @michaelwoerister - can you share what workload you used? I pushed an update to use libcore, we'll see if that works better

I used the entire perf.rlo test suite for collecting data. That is almost certainly overkill. A couple of small, medium, and large crates, in debug, release, and check modes, both incremental and non-incremental should suffice. I'd guess that it's still going to take ~50-100 compilation sessions to go through all combinations.

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

Interesting. Yeah, it looks like we're seeing decent results with just cargo (and its dependencies) plus a scattering of individual crates (libcore up until now, adding a couple more right now: externs and ctfe stress tests from perf.rlo). Cargo I'm running in various incremental and non-incremental modes as you suggest. It is worth noting that the addition of PGO to the build here is adding only roughly 10-15 minutes on one of our fastest builders, so we could definitely pull off PGO for rustc on linux at least without the off-by-one collection approach if we wanted to. 

(in fact this PR with minor changes I'd almost be comfortable landing as-is; I do want to upload the PGO file before we merge, but otherwise I am not sure that I would block on anything else. Since this does PGO in one builder we avoid any of the perf.rlo comparison problems too in some sense).

**Comment by bjorn3** [comment]
```
Connecting to raw.githubusercontent.com|151.101.248.133|:443... connected.
ERROR: certificate common name `www.github.com' doesn't match requested host name `raw.githubusercontent.com'.
```

**Comment by bjorn3** [comment]
Apart from a ~30% regression in ctfe-stress-4-doc there are only a few <2% regressions and overall a huge improvement of up 23% for task-clock. Instruction count does show some regressins, but that is expected as PGO optimized for cycle count rather than instruction count.

**Pull request closed without merging**
