### PR TITLE
Flatten rustc and rustc_trans module hierarchy slightly.

### PR DESCRIPTION
**Pull request by eddyb**
The following moves were made, in the name of sanity/simplicity:
- `rustc::middle::{cfg, infer, traits, ty}` to `rustc::{cfg, infer, traits, ty}`
- `rustc::middle::subst` to `rustc::ty::subst`
- `rustc_trans::trans::*` to `rustc_trans::*`
- `rustc_trans::save` to `rustc_save_analysis` (cc @nrc)

I've rebased a larger WIP branch on top of this and the only conflicts were in imports, but YMMV.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
:+1: from me.

**Comment by nrc** [comment]
:+1: from me too.

**Comment by nikomatsakis** [comment]
@eddyb I guess I didn't say r=me explicitly, but r=me

**Pull request merged**
