### PR TITLE
rustc_span: add span_data_to_lines_and_cols to caching source map view

### PR DESCRIPTION
**Pull request by tgnottingham**

### CODE REVIEW

**Comment by tgnottingham** [comment]
This is a performance mitigation for #76256. The improvement is about the smallest I'd feel justified in creating PR for, and I'm not totally sure the improvement justifies the added complexity. But I'm doing my due diligence.

**Comment by camelid** [comment]
Note: this seems to have very small perf improvements.

**Comment by tgnottingham** [comment]
Yeah, I don't have strong feelings on whether or not to push forward with this. I'll note that cycles, cpu-clock, and task-clock stats saw moderate improvements even though instruction counts saw very small improvements. But it's possible that was just luck with the variance.

**Comment by jyn514** [comment]
The second perf run was a lot more promising :) up to -.7% on instruction counts.

**Comment by estebank** [comment]
CC @rust-lang/compiler
It's added complexity and marginal improvements, but it improves some worst-case scenarios.

**Pull request merged**
