### PR TITLE
Rename middle::ty::ctxt to TyCtxt

### PR DESCRIPTION
**Pull request by jseyfried**
r? @eddyb

### CODE REVIEW

**Comment by KalitaAlexey** [comment]
Why do we need namespaces if we are not using them?

**Comment by jseyfried** [comment]
We need namespaces because we often do them. That doesn't mean we should always avoid descriptive names just because namespaces allow it.

In this case, I decided to use `TyCtxt` instead of just `Ctxt` to be consistent with the other contexts in the codebase (`ExtCtxt`, `TestCtxt`, `CrateCtxt`, `InferCtxt`, `FnCtxt`, `MatchCheckCtxt`, `BorrowckCtxt`, `CheckLoanCtxt`,  `GatherLoanCtxt`, `StaticInitializerCtxt`, etc).

**Comment by KalitaAlexey** [comment]
@jseyfried you can write `use middle::ty::ctxt as TyCtxt` in outer modules.

**Comment by jseyfried** [comment]
True, but I would prefer to be consistent with the other contexts. Also, that would make it harder to grep for uses of `TyCtxt`.

**Comment by eddyb** [comment]
cc @nikomatsakis There is that dual type context (w/ multiple lifetimes) refactor I wanted to do ages ago, which also renamed the context, but I used `TyCx` IIRC (because it was shorter). Thoughts?

**Comment by KalitaAlexey** [comment]
@jseyfried It wouldn't make harder to grep. Or I don't understood you.

**Comment by jseyfried** [comment]
@KalitaAlexey You would have to grep for both `ctxt` and `TyCtxt` to find the definition and all uses.

**Comment by KalitaAlexey** [comment]
Ok. You said `all uses of TyCtxt`. I separate definition from use.

**Comment by nikomatsakis** [comment]
On Mon, Feb 29, 2016 at 11:48:26PM -0800, Eduard-Mihai Burtescu wrote:
> cc @nikomatsakis There is that dual type context (w/ multiple lifetimes) refactor I wanted to do ages ago, which also renamed the context, but I used `TyCx` IIRC (because it was shorter). Thoughts?

It seems like the precedent is to call the type `Ctxt` and the
variables `cx`.  e.g., `InferCtxt`/`infcx`, `BorrowckCtxt`/`bccx`,
etc. Not sure this is the best convention, but it's the one that
exists.

**Comment by eddyb** [comment]
Well then, it's not like it could make refactorings any harder (actually, it should be easier to grep for `TyCtxt` than anything else), so LGTM.

**Comment by jseyfried** [comment]
@eddyb I rebased and built locally (travis is having problems).

**Comment by jseyfried** [comment]
@eddyb rebased, the travis build is successful now

**Pull request merged**
