### PR TITLE
Update libc to 0.2.21

### PR DESCRIPTION
**Pull request by malbarbo**
Update to include android aarch64 and x86 improvements.

### CODE REVIEW

**Comment by frewsxcv** [comment]
This appears to fail on Android:

https://travis-ci.org/rust-lang/rust/jobs/209003929

@bors r-

**Comment by malbarbo** [comment]
@frewsxcv libc 0.2.21 fixed the type of c_char from u8 to i8. I update the c_char on src/libstd/os/raw.rs to i8. This should fix the PR.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by frewsxcv** [comment]
@bors r-

Looks like there's still an issue here: https://github.com/rust-lang/rust/pull/40592#issuecomment-287262668

**Comment by malbarbo** [comment]
I fixed the error.

Run  `src/ci/docker/run.sh dist-android` and it almost worked... the dist tar balls was generated, but I got I error about rustbook:

```
Rustbook (arm-linux-androideabi) - nomicon
An error occured:
Read-only file system (os error 30)


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/rustbook" "build" "/checkout/src/doc/nomicon" "-d" "/checkout/obj/build/arm-linux-androideabi/doc/nomicon"
expected success, got: exit code: 101
```

Maybe a local error?

I also rebased...

**Comment by frewsxcv** [comment]
Here's another one: https://github.com/rust-lang/rust/pull/40629#issuecomment-287522275

@bors r-

**Comment by malbarbo** [comment]
@alexcrichton Now both `src/ci/docker/run.sh arm-android` and `src/ci/docker/run.sh dist-android` run successful in my machine. Let's see how it goes on travis.

**Comment by alexcrichton** [comment]
@bors: r+

Ok!

**Pull request merged**
