### PR TITLE
[EXPERIMENT]: Use Windows `sys` bindings and add raw-dylib feature

### PR DESCRIPTION
**Pull request by ChrisDenton**
With recent changes in win32metadata and windows-rs we should no longer need a special `-std` bindings. Additionally, this adds a `windows-raw-dylib` feature that allows users of `build-std` to experiment with using `raw-dylib`. The feature isn't yet complete because there are a few other crates that contribute imports (alloc and backtrace). This PR will currently fail CI's tidy test due to using a git dependency.

cc @kennykerr, just to notify you I'm experimenting with this

try-job: x86_64-msvc
try-job: i686-msvc
try-job: i686-mingw
try-job: x86_64-mingw

r? ghost

### CODE REVIEW

**Comment by kennykerr** [comment]
That's the only reason the "std" option still exists. 😊

**Comment by ChrisDenton** [comment]
@petrochenkov it's not super important but would you happen to know why imports aren't de-deduplicating in this case?

**Comment by Urgau** [comment]
> it's not super important but would you happen to know why imports aren't de-deduplicating in this case?

it's probably because the de-duplication logic[^1] takes into account the "kind" part of the import and it's different between the two but it still leads to the same linker arguments being emitted, which is considered duplicated by the test since it can't find anything different about the two linker args

the simplest fix would probably be moving the de-duplication logic one step further (ie just after the `filter_map`) so the "kind" part is no longer taken into account

[^1]: https://github.com/rust-lang/rust/blob/164e1297e1bce47a241e4d93a9f044452b288715/compiler/rustc_codegen_ssa/src/back/link.rs#L1493-L1497

**Comment by ChrisDenton** [comment]
Success! 🎉

I'll close this experiment for now and open a new PR when there's a crates.io release.

**Pull request closed without merging**
