### PR TITLE
add `no_compile` doctest attribute

### LINKED ISSUE #63193: Flag for stop interpreting code blocks as doctests
Code blocks inside documentation are interpreted as doctests by default. Sometimes the code is not for testing at all (for example, writing pseudo-code for an algorithm), and we can add `ignore` at the beginning of the code block.

However, even if `ignore` is added, `cargo test` still interprets the code block as doctest, and prints "... ignored" on each occurrence of `ignore`-tagged code blocks. In fact, those code blocks should not be interpreted as doctest, and `cargo test` should *silently* ignore those code blocks.

For example, the following code is a snippet of my current project.
```rust
/// Minimize the input size while preserving the coverage.
///
/// The algorithm trims by trying to remove chunks, starting from large chunks
/// to small chunks.
///
/// # Algorithm
/// ```ignore
/// for round in rounds {
///     for chunk_index in buffer {
///         let new_buffer = remove_chunk(chunk_index, round_size);
///         if run(new_buffer).coverage == known_coverage {
///             buffer = new_buffer;
///         }
///     }
/// }
/// ```
pub struct Trim {
...
}
```

`cargo test` generates the following output:
```
[...]
   Doc-tests dfuzz

running 4 tests
test src/algorithm/pass/mod.rs - algorithm::pass::Trim (line 17) ... ignored
test src/tracer/function.rs - tracer::function (line 18) ... ignored
test src/tracer/function.rs - tracer::function (line 23) ... ignored
test src/tracer/function.rs - tracer::function (line 5) ... ignored
```

Is it possible to add a flag in the code block to suppress such "ignored" messages?

### PR DESCRIPTION
**Pull request by CAD97**
This makes it possible to write a doctest

````rust
```no_compile
my_fancy_macro!(12);
```
````

which is detected as and highlighted as rust code, but is *not* compiled. `ignore` *kind of* serves this purpose, but is still compiled and run when `--include-ignored` or `--ignored` is used.

Maybe should be feature gated / limited to working on the nightly channel (but I personally think this is simple and obviously correct enough that it could potentially just ride the release train).

Fixes #63193, Fixes (kinda) #87586

<details><summary>Big Picture View</summary>

https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Cleaning.20up.20docblock.20attributes

We currently have

| doctest attribute | test attribute | compile | run |
| -- | -- | -- | -- |
| | ignore | yes | with `--ignored` |
| no_run | | yes | no |
| ignore | | with `--ignored` | with `--ignored` |
| compile_fail | | fail | |
| | cfg(any()) | no | |

I want to clean up this to be

| doctest attribute | test attribute | compile | run |
| -- | -- | -- | -- |
| ignore | ignore | yes | with `--ignored` |
| no_run | | yes | no |
| compile_fail | | fail | |
| no_compile | cfg(any()) | no | |

This does the simple part of adding `no_compile`. After `no_compile` is available, it becomes possible to tell current uses of `ignore` for does-not-compile rust code to use `no_compile` instead, and move towards `ignore` always compiling the code in the next edition.

### CODE REVIEW

**Comment by jyn514** [comment]
The test for this would live in src/test/rustdoc-ui.

**Comment by CAD97** [comment]
UI test has been added.

**Comment by CAD97** [comment]
Okay tidy, I'm trying to unblock stopping using `ignore` (so maybe the lint will have to cover `no_compile` as well)

**Comment by CAD97** [comment]
Some interesting stats on ```` ```ignore (reason)````:

- 13× only-for-syntax-highlighting or syntax-highlighting-only (obvious `no_compile` candidate)
- 10× pseudo-rust (obvious `no_compile` candidate)
- 3× illustrative (obvious `no_compile` candidate)
- 5× incomplete (obvious `no_compile` candidate)
- 6× hypothetical (obvious `no_compile` candidate)
- 2× exposition (obvious `no_compile` candidate... or just actually compile)
- 1× pacify the merciless tidy (should be `no_compile`)
- 2× not-usage-example (maybe should be `ignore`, maybe should just be tested)
- 1× ignore future compatibility warning
- 9× needs multiple files/crates
- 8× no longer emitted error code
- 2× feature got removed
- 5× platform dependent
- 1× requries external plugin
- 2× depends on release channel
- 1× can't specify compiler flags
- 1× needs dependency
- 12× cannot test private items
- 6× diagnostic (should be `text` imho)
- 10× extern declaration (should maybe be `no_run`?)
- 14× ```` ```ignore```` examples/tests

(I definitely missed a some, I got to clippy in the github\.dev search and bailed)

**Comment by GuillaumeGomez** [comment]
I'm not sure to understand the use case here. It means you'd want to have a rust code example that can never be checked. It's a strange use case. Why do you need this?

Also, just like for `ignore`, it should display the `i` alongside the code block in the generated documentation.

**Comment by CAD97** [comment]
> I'm not sure to understand the use case here. [...]

So, fundamentally, I believe the current usage of ```` ```ignore```` is wrong.

> [#[ignore]](https://doc.rust-lang.org/reference/attributes/testing.html#the-ignore-attribute) — Indicates that the test function will be compiled, but not run ***by default*** [emphasis mine]. See the [--ignored](https://doc.rust-lang.org/rustc/tests/index.html#--ignored) and [--include-ignored](https://doc.rust-lang.org/rustc/tests/index.html#--include-ignored) options to run these tests. [[rustc book §6 Tests, Test attributes](https://doc.rust-lang.org/rustc/tests/index.html#test-attributes)]

`#[ignore]`, and thus by extension ```` ```ignore````, should be used for tests which should always be compiled but only ran when opted into with `--ignored` or `--include-ignored`; flaky, long-running, or test otherwise undesirable to always be running, but which should be able to be run.

This is demonstrably *not* how ```` ```ignore```` is used in practice. In practice, ```` ```ignore```` is used because there is no other way to get Rust syntax highlighting in rustdoc without trying to compile the example.

<details><summary>Examples in this repo</summary>

Some of these should maybe be made to compile, but most want `no_compile` semantics, where they aren't tested at all.

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_ast/src/ast.rs#L1479-L1487

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_ast/src/ast.rs#L2705-L2714

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_builtin_macros/src/deriving/generic/mod.rs#L509-L518

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_builtin_macros/src/deriving/generic/mod.rs#L522-L534

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_hir/src/hir.rs#L1978-L1984

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_hir/src/hir.rs#L3287-L3292

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_macros/src/diagnostics/mod.rs#L15-L35

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_macros/src/diagnostics/mod.rs#L46-L54

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_macros/src/diagnostics/mod.rs#L70-L95

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_macros/src/diagnostics/mod.rs#L107-L111

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_macros/src/diagnostics/utils.rs#L134-L143

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_macros/src/diagnostics/utils.rs#L148-L150

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_middle/src/query/mod.rs#L107-L117

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_middle/src/query/mod.rs#L195-L200

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_middle/src/ty/context.rs#L345-L351

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/compiler/rustc_middle/src/ty/mod.rs#L1078-L1083

... you get the point, just do a code search for ```` ```ignore````.

</details>

The use of ```` ```ignore```` for this purpose breaks `--[include-]ignored`, as now the flag includes testing of documentation blocks which aren't intended to be compiled/tested. Ultimately, I would like ```` ```ignore```` in edition 2024+ to behave more like `#[ignore]` — always checked to compile, tested with the `--[include-]ignored` flag. Doing so requires providing a mechanism to get the behavior people are using ```` ```ignore```` for today, though — applying Rust syntax highlighting in the rendered documentation, but never tying to compile/test the code block. That's what `no_compile` is.

The behavior I would like to see is that in edition 2024 ```` ```ignore```` is checked to compile, and if an ```` ```ignore```` documentation block fails to compile, a "use `compile_fail` if the snippet is an example of code which fails to compile, or `no_compile` if the snippet should not be tested" hint is provided.

[Flag for stop interpreting code blocks as doctests #63193](https://github.com/rust-lang/rust/issues/63193), [No way to run `no_run` doctests #82715](https://github.com/rust-lang/rust/issues/82715), and [Ignored doctests are run with `cargo test -- --ignored`. #87586](https://github.com/rust-lang/rust/issues/87586) contain more discussion of motivation.

> Also, just like for `ignore`, it should display the i alongside the code block in the generated documentation.

Agreed, I'm going to look into fixing that this week.

**Comment by GuillaumeGomez** [comment]
Ok, now I understand the problem. It seems super weird that `ignore` tests are compiled. Let's take this example:

```rust
/// ```ignore
/// kawakunga
/// ```
pub use ::std as x;
```

If I run `rustdoc`, nothing is compiled as far as I can see and if I run `rustdoc --test`, I get:

```console
running 1 test
test foo.rs - x (line 1) ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

So maybe the documentation itself is wrong? Needs to be checked more in detail.

**Comment by ChrisDenton** [comment]
The docs aren't super clear but for rustdoc I believe you need something like this to run ignored tests:

`rustdoc library.rs --test --test-args=--ignored`

**Comment by GuillaumeGomez** [comment]
Some clarification would be appreciated... So in any case, with this in mind, I don't see why `no_compile` would be needed.

**Comment by CAD97** [comment]
@ChrisDenton is correct. With `cargo`, the command is `cargo test -- --ignored`.

The current status of things is explained by the following table:

| doctest attribute | test attribute | compile | run |
| -- | -- | -- | -- |
| | ignore | yes | with `--ignored` |
| no_run | | yes | no |
| ignore | | with `--ignored` | with `--ignored` |
| compile_fail | | fail | |
| | cfg(any()) | no | |

The point of `#[ignore]` is that the tests are ignored by default, but *can* be run with an opt in with `--ignored`. With current ```` ```ignore````, the tests are treated as `#[test] #[ignore] fn rustdoctest() { compile(test).run() }`, meaning that the documentation block is compiled and run when `--ignored` is provided.

`no_compile`'s purpose is to fill in that bottom left cell:

| doctest attribute | test attribute | compile | run |
| -- | -- | -- | -- |
| | ignore | yes | with `--ignored` |
| no_run | | yes | no |
| ignore | | with `--ignored` | with `--ignored` |
| compile_fail | | fail | |
| no_compile | cfg(any()) | no | |

giving an option for documentation blocks which should be highlighted as Rust code in the documentation but should not be considered tests — they should not be tested with `rustdoc --test --test-args=--ignored`, and they should not show up in the listing of tests *at all* when running `rustdoc --test`.

In edition 2024, I would *like* to change the table to

| doctest attribute | test attribute | compile | run |
| -- | -- | -- | -- |
| ignore | ignore | yes | with `--ignored` |
| no_run | | yes | no |
| compile_fail | | fail | |
| no_compile | cfg(any()) | no | |

to improve the experience of passing `--ignored` to the test suite. This is a long-term goal and a much harder sell than `no_compile` (basically requiring touching every ```` ```ignore```` when upgrading the edition), but I believe this to be a much cleaner state of things than where ```` ```ignore```` tests are only checked to compile when explicitly asking to *run* ignored tests.

A different table that's fully backwards compatible would be

| doctest attribute | test attribute | compile | run |
| -- | -- | -- | -- |
| bikeshed | ignore | yes | with `--ignored` |
| no_run | | yes | no |
| compile_fail | | fail | |
| ignore | cfg(any()) | no | |

instead making ```` ```ignore```` never compile/run the tests nor show up in the test listing, and adding a new attribute to get the behavior of `#[ignore]` in normal tests. I personally think that making ```` ```ignore```` and `#[ignore]` behave differently is a footgun that can and should be avoided if possible, but accept that this is also a viable state to land in.

**Comment by CAD97** [comment]
See also [some discussion in zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Cleaning.20up.20docblock.20attributes)

**Comment by GuillaumeGomez** [comment]
Ok, now I see the problem. I'm not used at using `cargo` with `rustdoc` enough... It's strange that they pass this option by default. I mean: the whole point of `ignore` is that you have rust highlighting without running the compiler on it **unless** you pass the option.

Anyway, what do you think about this @rust-lang/rustdoc ?

**Comment by CAD97** [comment]
> It's strange that they pass this option by default.

To be clear, the default is to ignore the tests:

`cargo test` calls `cargo rustdoc --test`  
`cargo test -- --ignored` calls `cargo rustdoc --test --test-args=--ignored`

**Comment by GuillaumeGomez** [comment]
Then again I don't see the need for `no_compile`. If you want to test that some `ignore` blocks are compiling, why not checking it all the test with `no_run`? If you don't want that some code examples to be compiled, why running `--ignored`?

**Comment by ChrisDenton** [comment]
Because you do want to run ignored tests in general. They may all be too slow or too janky to run **by default** but you do want some way to run them as a group. They're opt-in when you know what you're doing.

But there are also some code in doc comments which you **never ever ever** want to run. Because it's not really rust code (but you want the same syntax highlighting) or it's just for illustrative purposes or whatever.

The first group you definitely do want to run at some point. The second group you don't want to be compiled ever at all. These are both currently using the same `ignore` attribute, which can be run.

**Comment by CAD97** [comment]
The point is that running `--ignored` is useful, e.g. #82715:

> It follows from ["examples such as 'Here's how to retrieve a web page,' which you would want to ensure compiles, but might be run in a test environment that has no network access"] that in some cases you do want to run doctests marked as `no_run`, such as if the test environment does have network access. This is possible with regular tests marked `#[ignore]` by passing `-- --ignored` to cargo test, but the same does not work with [`no_run`] documentation tests.

Similarly, there's desire to suppress the `ignored` message for non-test Rust documentation blocks, e.g. #63193:

> Code blocks inside documentation are interpreted as doctests by default. Sometimes the code is not for testing at all (for example, writing pseudo-code for an algorithm), and we can add `ignore` at the beginning of the code block.
> 
> However, even if `ignore` is added, `cargo test` [equiv. `rustdoc --test`] still interprets the code block as doctest, and prints "... ignored" on each occurrence of `ignore`-tagged code blocks. In fact, those code blocks should not be interpreted as doctest, and `cargo test` [equiv. `rustdoc --test`] should silently ignore those code blocks.

It's my position that such uses should use `no_compile`.

> It's pretty frustrating to have to choose between syntax highlighting and "this code is never to be compiled or tested regardless of flags" -- would be really nice to have a simple way to handle this seemingly common case [https://github.com/rust-lang/rust/issues/63193#issuecomment-1007624653]

I'll also quote @thomcc's motivation from #87586:

> If you use `rust,ignore` to ignore doctests which don't compile (often because you want to include example code that's entirely expository in your documentation — something that doesn't compile at all, and should merely syntax highlight as Rust), they still are attempted to compile and run when you pass `--ignored` to the test runner.
> 
> This is unfortunate, as this is what you use to run `#[ignore]`d tests, which are good (intended?) for tests that are too slow to complete in normal execution, often ones which are exhaustive. Having doctests that fail to compile be mixed in here means this use of `#[ignore]` is ***effectively broken*** [emphasis mine].

@jonhoo @jyn514 it'd be helpful if you could explain your position here as well that you alluded to in #82715. cc also @thomcc from #87586

**Comment by jyn514** [comment]
I don't want to be involved in this, sorry.

**Comment by Manishearth** [comment]
So I'm in favor of this in general, but before we go forward with this can we have a doc or something talking about the different options that currently exist (there's `compile_fail`, `ignore`, `text`, `no_run`, and now `no_compile`) and what they each mean and how they relate to each other.

The reason I say this is that this space is kinda complicated already, and I would rather not have people confused about which option to pick. If we can pick a name that's clear and document it well, I'd be in favor of this.

I am a _little_ skeptical about `--ignore` being used at all in doctests. I do see the use case presented, and I kinda wonder if it's better served by a `cfg` or something.  I'm not sure, I find the concept of an ignorable-ignore to be kinda iffy. But we already have that, so I can't complain too much.

A pretty major use case for non-compiling code is writing snippets, rustdoc _does_ let you "fill in" the snippets with `#` but this can quickly make a small doc section giant, and is a pain to keep in sync. Sometimes crates are complicated and need a lot of scaffolding for something to actually compile.

Fundamentally the distinction being drawn here seems to be "this will not compile, this will never compile, never try" (`no_compile`) vs "this could compile based on the environment, don't try by default" (`ignore`)  vs "this will not compile, and the fact that it doesn't compile is relevant" (`compile_fail`)

**Comment by CAD97** [comment]
Here's a draft of a replacement for the [Attributes section](https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes) of the documentation tests part of the rustdoc book, both one for clarity on the current situation and one for my "ideal future":

<details><summary>Today</summary>

Code blocks can be annotated with attributes that help `rustdoc` do the right thing when testing your code.

`compile_fail` tells `rustdoc` that the example should fail to compile. If compilation succeeds, then the test will fail. However, please note that code which fails to compile with the current Rust release may be made to work in a future release, as new features are added.

```rust
/// ```compile_fail
/// let x = 5;
/// x += 2; // shouldn't compile!
/// ```
```

`no_run` tells `rustdoc` that the example should compile, but to not run the code. This is useful for examples which cannot be made to run under the test fixture, would fail to terminate, or which would be Undefined Behavior if run.

```rust
/// ```no_run
/// loop {
///     println!("Hello, world");
/// }
/// ```
```

`should_panic` tells `rustdoc` that the example should compile, but panic during execution. If the code fails to panic, the test will fail.

```rust
/// ```should_panic
/// assert!(false);
/// ```
```

`ignore` tells the test runner to ignore the doctest by default, unless specifically opting in to running ignored tests with the `--ignored` or `--include-ignored` flags (used as `cargo test -- --ignored` or `rustdoc --test-args=--ignored`). This is useful for examples such as "here's how to retrieve a web page" which use external resources such as the network, as the test environment may lack such resources.

If the test is ignored by the test runner, `rustdoc` does not attempt to compile the example. As such, a predominant current use of `ignore` is for code which should be highlighted as Rust code, but which shouldn't be interpreted as a documentation test. This is rarely what you actually want, as the code *is* tested when the correct flags are used, and it's better to mark examples as `text` if they are not Rust code or `no_compile` if they deliberately fail to compile.

```rust
/// ```ignore
/// fn foo() {
/// ```
```

`edition2015`, `edition2018`, and `edition2021` tell `rustdoc` that the code sample should be compiled using the specified edition of Rust. When running `rustdoc` through `cargo`, the package's edition is used by default.

```rust
/// Only compiles in the 2015 edition.
///
/// ```edition2015
/// try!(Result::<(), std::io::Error>::Ok(()));
/// Ok::<(), std::io::Error>(())
/// ```
```

</details>

<details><summary>Future</summary>

(replacing the previous, starting at `ignore`)

`ignore` tells `rustdoc` that this example should be interpreted as a test, but ignored by default, as if you had marked the test with `#[ignore]`. This is useful for examples like "here's how to retrieve a web page" which use external resources such as the network, but the test environment may lack. Even when not run, the test is still checked to compile.

```rust
/// This test requires user interaction.
///
/// ```ignore
/// assert!(show_yes_no_dialog("Should this test succeed?"));
/// ```
```

`no_compile` tells `rustdoc` that this example is not a test and should not be compiled. If the example isn't Rust code, it should be marked as `text` instead. However, `no_compile` is useful when the example should still be highlighted as Rust code, such as expository pseudo-Rust which can be syntax highlighted but shouldn't be treated as a test.

```rust
/// The syntax of a function declaration is
///
/// ```no_compile
/// $vis $(unsafe)? $(extern $($literal)?)? fn $ident( $( $pat : $ty ),* $(,)? ) $(-> $ty)? {
///     $($stmt)*
///     $($expr)?
/// }
/// ```
```

(return to the previous, starting at `edition2015`)

</details>

**Comment by CAD97** [comment]
(triaging my open PRs)

It's been a month, and this is <kbd>S-waiting-on-review</kbd>. Let me summarize the state of this:

The meaning of ```` ```ignore```` for doctests is somewhat overloaded. We currently mark these as [ignored](https://doc.rust-lang.org/nightly/test/struct.TestDesc.html#structfield.ignore) in the test runner, so that it shows the test but lists it as ignored. However, this also means that using the test runner argument of `--include-ignored` will attempt to compile the example, even if it's not intended to be valid Rust code.

This is made worse by the fact that there is no other way to get Rust highlighting for an example block than use ```` ```ignore```` or ```` ```compile_fail````. In practice, this means that if a project does not set `doctest = false` in their manifest, `cargo test --include-ignored` will fail due to non-test documentation examples. The only workarounds short of disabling doctests are to:

- Note which non doctest tests are ignored and request them with `--ignored name_of_test`,
- Use a test runner such as `cargo nextest` which does not support doctests,
- Test each target individually (`cargo test --lib --bin --tests --examples --benches`) and set `--include-ignored` for everything but `--doc`, or
- Fall back to source edits, which is basically required if you want to actually test an ignored doctest.

This PR proposes adding ```` ```no_compile````, which marks a code block as Rust code for the purpose of syntax highlighting and the "this code is not tested" marker (though I think that's missing atm), but does not submit it to the test runner.

Additionally, I've proposed making ```` ```ignore```` always check that the code block compiles to align it to the `#[ignored] #[test]` semantics in a future edition, but this is a significantly larger change and *not* part of this PR, and is merely provided as an indication of the larger picture of making test annotations more consistent. See [this comment](https://github.com/rust-lang/rust/pull/96573#issuecomment-1115248925) for some comparison graphs.

So, the **actionable question to the reviewer**:

Does the above justify adding ```` ```no_compile```` *semantics*?

If so, three follow up questions:

- Is this implementation reasonable?
- Should this be feature gated initially?
  - If so, I would appreciate a pointer at how to get a feature flag into librustdoc.
- This should have an integration test that makes sure the blocks get highlighting and the "not tested" note. Where/how do I set that up?

**Comment by GuillaumeGomez** [comment]
Like I said I'm definitely not convinced but let's see what the others think about it.

cc @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
Just in case: it's not about compiling but not running (because there is `no_run` for that) but really about having code blocks with Rust syntax highlighting that are not `ignore`d.

**Comment by CAD97** [comment]
Whoops, I think I've accidentally crossed some wires @notriddle 

This PR is solely about adding ```` ```no_compile```` as a usable semantic.

Changing the behavior of ```` ```ignore```` is *not* part of this PR, just a future possibility.

**Comment by xxchan** [comment]
I find this PR when I am checking the usage of doctests in my codebase. Specifically I'm curious about why some are ignored, and many of them turn out to be never ever wanted to be run (illustration only, pesudo code). They are simply *not* tests, instead of *ignored* tests. I expect they are not included in the test result report. 😄

**Review by notriddle — APPROVED** [review]

**Comment by jyn514** [comment]
@notriddle can you please post a stabilization report so it's clear exactly what's being approved? is it just the new `no_compile` attribute? or changing the behavior of `ignore` in a future edition? or all that plus a `rustfix` diagnostic to upgrade from `ignore` to `no_compile`? Note that last bit will require work on rustfix to be useful: https://github.com/rust-lang/rustfix/issues/192

**Comment by Manishearth** [comment]
@rfcbot concern feature-gate We should have a feature gate for this attribute

**Comment by Nemo157** [comment]
I don't think a feature gate is necessary, `` ```no_compile `` is valid syntax today that says "highlight this code block with the `no_compile`" language, which implicitly does not treat it as a doctest. The only change this will cause is to start highlighting the code block as `rust` instead.

**Comment by Manishearth** [comment]
Hmm, that's reasonable; 

@rfcbot resolve feature-gate

**Comment by Manishearth** [comment]
@rfcbot resolved feature-gate

Yeah that's reasonable.

**Comment by camelid** [comment]
@rfcbot reviewed

This addition seems good to me. I hadn't realized that `ignore` was so strange in rustdoc, so it seems good to have an option with clearer semantics.

@Manishearth it looks like rfcbot didn't recognize `resolved` as a command.

**Comment by Manishearth** [comment]
@rfcbot resolved feature-gate

**Comment by camelid** [comment]
Weird... the `feature-gate` concern is still there, though the other one's resolution worked.

**Comment by camelid** [comment]
I think this might be an rfcbot glitch. Asked on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/rfcbot.20concern.20not.20resolving).

**Comment by xxchan** [comment]
only the original author can mark their concern as resolved? cc @Manishearth

**Comment by Manishearth** [comment]
@rfcbot resolved feature-gate We should have a feature gate for this attribute

**Comment by riking** [comment]
I have a comment about the "shiny future" presented -- I don't like `ignore` as the preferred spelling for this behavior.
However, the only direct equivalent in other test frameworks I can think of is that Bazel calls it `tags = ["manual"]` (test only runs when named on the command line).

For the instant issue, no complaints!

**Comment by CAD97** [comment]
<details><summary>less important details</summary>

FWIW: the reason for `ignore` behaving this way is that it's already the documented and expected behavior of `#[ignore]` to allow running the tests with `--include-ignored` (run ignored and not ignored tests) and `--ignored` (run only ignored tests). Where this becomes very surprising is that the rustdoc test runner only compiles doctests once the libtest test runner has decided to run it; effectively `#[test] #[ignore] fn doctest() { compile(include_str!())?.run()? }`.

I don't have any idea the best way to handle this -- it might be just to disable `-[-include]-ignored` when rustdoc is the test runner. Fundamentally, there's a conflict of interest here aiui -- rustdoc wants to list the ```` ```ignore```` as a present-but-ignored example-test, the developer has written something that's likely not going to compile, and the libtest runner wants you to be able to opt-in to running `#[test] #[ignore]` tests.

The important thing imho is that `cargo test -- --ignored` should work to run `#[test] #[ignored]` tests. On 1.64.0 and 1.65.0-beta.2, though, for basically any project using doctests this will fail due to ```` ```ignore```` "doctests" which don't compile (#87586).
</details>

HOWEVER, something apparently has changed between 1.65.0-beta.2 and 1.66.0-nightly-2022-10-03: nightly `cargo test -- --ignored` now no longer runs doctests:

```
> cargo +beta -V 
cargo 1.65.0-beta.2 (082503982 2022-09-13)

> cargo +beta test -- --ignored > $null
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests src\lib.rs (D:\.rust\target\debug\deps\dynty-5fe814ab794244b1.exe)
     Running unittests src\lib.rs (D:\.rust\target\debug\deps\dynty_macros-1aaf157df7fac3ba.exe)
     Running unittests src\lib.rs (D:\.rust\target\debug\deps\dynty_macros_impl-6f94d6f3dc68c979.exe)
   Doc-tests dynty
   Doc-tests dynty-macros
   Doc-tests dynty-macros-impl

> cargo +nightly -V
cargo 1.66.0-nightly (0b84a35c2 2022-10-03)

> cargo +nightly test -- --ignored > $null
   Compiling dynty v0.1.0 (D:\git\cad97\dynty\lib)
    Finished test [unoptimized + debuginfo] target(s) in 0.33s
     Running unittests src\lib.rs (D:\.rust\target\debug\deps\dynty-e50eb211e71fe749.exe)
     Running unittests src\lib.rs (D:\.rust\target\debug\deps\dynty_macros-ce1215d5d07a1208.exe)
     Running unittests src\lib.rs (D:\.rust\target\debug\deps\dynty_macros_impl-d6d1d0e03e3d048f.exe)
```

Investigating a bit, it looks like this is probably a bugfix, as `cargo test filter` has always suppressed doctests, but `cargo test -- filter` hasn't. If this change is kept, then that fixes #87586 and makes this change imho no longer necessary.

#63193 is asking for ```` ```no_compile```` (or to make the change to ```` ```ignore````); to completely skip the code block rather than including it in the `cargo test` output as `#[ignore]`d. I honestly do not have any opinion here; my motive is just to make `cargo test -- --ignored` not include deliberately noncompiling documentation "tests".

(That said, what makes ```` ```ignore```` special that it should be listed in `cargo test` output but e.g. ```` ```text```` isn't listed? In practice, people use ```` ```ignore```` to mark a block as *not a test*, so #63193 has a point in saying that rustdoc shouldn't be reporting them as tests.)

@rfcbot concern does-the-cargo-behavior-change-make-this-unnecessary

**Comment by GuillaumeGomez** [comment]
Any information about https://github.com/rust-lang/rust/pull/96573#issuecomment-1271083183 @CAD97 ?

**Comment by pitaj** [comment]
@CAD97 @GuillaumeGomez ping from triage. Have you come to a conclusion on whether this is necessary?

**Comment by RaulTrombin** [comment]
Can I maintain the formatting using rust-analyser while using `no_compile`? 

Is it possible to include conditional triggers in `no_compile`? For example: `/// #[cfg(target_arch = "armv7")]`

I encountered some issues on CI where the documentation examples were running with `cargo test` and causing annoying errors. I discovered that I can skip the example using `/// #[cfg(target_arch = "armv7")] { example }`, but it looks good in the documentation...

This tool is very helpful, and I would like to know if it's possible to make it conditional while still performing format checks.

**Comment by GuillaumeGomez** [comment]
You can hide lines in code examples by starting them with `# `.

**Comment by CAD97** [comment]
> Any information about #96573 (comment)

(Sorry for the delay; life happened)

I've come to the eventual conclusion that ```` ```ignore```` should be sufficient. It's unfortunate that different "kinds" of ignored tests exist, but they do. It's odd that `cargo test --all-targets` excludes `cargo test --doc`, but it does. At this point I think ```` ```no_compile```` would only really serve to muddy things further.

The normal test harness has the advantage that tests have names, so it's possible (even if not necessarily *nice*) to run a subset of ignored tests that actually work in the current environment. Doctests don't really have that affordance.

If the test runner ever gets more interesting (e.g. `ignore_if`), then this might be worth revisiting. Until then, though, I no longer think this change to be particularly beneficial. The test runner needs to recognize a difference between "ignored by default but may be meaningful in some environments" and "ignored and will never pass" before this addition actually means anything.

As such, closing this. If someone else thinks this is a valuable addition, feel free to take the code and make your argument for it.

**Pull request closed without merging**
