### PR TITLE
WIP: Get rid of the `Immediate` optimization for locals in the miri engine

### PR DESCRIPTION
**Pull request by oli-obk**
r? @RalfJung 

let's see what perf says. @eddyb said even if it's an improvement now, it might be slow for evaluations when we have const generics (which are mostly immediate?)

### CODE REVIEW

**Comment by oli-obk** [comment]
@rust-timer build 466e347e301678b7dfa854a02da08ff077cf1a4f

**Comment by oli-obk** [comment]
Cc @RalfJung benchmarks are clear on this: don't do it. the optimization is needed for perf

**Comment by RalfJung** [comment]
Well, that would have been too easy, wouldn't it?^^

**Pull request closed without merging**
