### PR TITLE
Match the loop examples

### PR DESCRIPTION
**Pull request by dns2utf8**
The idea is to show the usefulness of the expression side by side.

### CODE REVIEW

**Comment by Centril** [comment]
Can you please elaborate on this change and why it should be done?

**Comment by dns2utf8** [comment]
Certainly, when I read the last example it was confusing me that the algorithm demonstrated was not the same.
So I matched them and picked the one with a little more complexity.

**Comment by dns2utf8** [comment]
A more explicit variant would be this:
```rust
let mut i = 1;
let mut something = 0;
loop {
    println!("i is {}", i);
    if i > 100 {
        something = i;
        break;
    }
    i *= 2;
}
assert_eq!(something, 128);
```

**Comment by edmilsonefs** [comment]
Hey! This is a ping from triage, we would like to know if you @aidanhs could give us a few minutes to share your thoughts on it.

**Comment by dns2utf8** [comment]
I rebased the branch on the current master. 
Do you think the example should be more explicit?
Or are there other opinions?

Cheers,
Stefan

**Comment by Alexendoo** [comment]
Ping from triage: Requesting a review from @rust-lang/docs

**Comment by ProgrammaticNajel** [comment]
Ping from triage. @GuillaumeGomez any updates on this? Thanks.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
