### PR TITLE
CFI: Refactor: Split into modules

### PR DESCRIPTION
**Pull request by maurer**
We have almost all the implementation in a single ~1200 line file, and have had a lot of churn that leaves debris around.
I believe this to be no-functional-change, just code organization and cleanup.

This change:

* Splits it out into three modules, `instance`, which has our instance generalization code, `ty`, which has the `transform_ty` logic, and `itanium_cxx_abi`, which has the type encoding.
* Merges the three option types into one - they were type aliases, not newtypes, so you could already freely cast between them, and we were doing error handling for if one of them didn't accept the bit patterns of another.
* Removes inclusion of module names in function/type names, avoiding redundancy when using the API through `use rustc_symbol_mangling::typeid;`
* Minor clippy fixes
* Adds some summary documentation about the behavior of `instance::transform` and `ty::transform`

### CODE REVIEW

**Comment by rcvalle** [comment]
I'll take a look at it, but it might have to wait a little bit because we're in the middle of moving all sanitizers related code into a rustc_sanitizers crate and stabilizing the core sanitizers, and we'll have to see how it fits in the planned design (@davidtwco and I).

**Review by davidtwco — COMMENTED** [review]
At first glance, these changes all seem reasonable to me, but will conflict with #123620 so you might want to wait until that lands?

**Comment by rcvalle** [comment]
Thanks a lot for your time and work on this, @maurer! Much appreciated. I took a look, and after #123620 is merged, I think we what we want from here is:

1. Consolidating `EncodeTyOptions`, `TransformTyOptions` as `TypeIdOptions`.
2. Fixing Clippy findings.
3. Maybe the abstraction for `TransformTy`?

The abstraction for `TransformTy` would cause `TransformTy` to be allocated and deallocated (with a non-trivial drop) for every parameter of every function or method so I'm unsure if we want that. Using `TransformTy` directly doesn't seem too bad when weighted against that. What do you think?

Would you mind rebasing these on top of #123620 whenever you have time?

**Comment by Dylan-DPC** [comment]
@maurer any updates on this? thanks

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
