### PR TITLE
Move RangeArgument and Bound to libcore.

### PR DESCRIPTION
**Pull request by clarfonthey**
This moves them to `core::ops` with the rest of the `Range` types and re-exports them in `collections`.

Right now, there's no reason why these shouldn't be accessible in libcore. Caution is due, however, because this would add `Bound` to libcore as stable immediately.

Also as a side note, it may be desirable in the future to split up `libcore/ops.rs` as it is getting rather big.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Thanks for the PR! We’ll periodically check in on it to make sure that @reviewer or someone else from the team reviews it soon.

It also looks like there are some [compilation failures](https://travis-ci.org/rust-lang/rust/jobs/224588891#L766), so perhaps you could take a look at those?

**Comment by clarcharr** [comment]
I think that everything should be fixed now!

**Comment by Mark-Simulacrum** [comment]
Looks like that's not quite true: some feature attributes need to be added to a few crates: https://travis-ci.org/rust-lang/rust/jobs/225394483#L780.

This is somewhat concerning, as that implies that moving this feature changed from stable to unstable? Or otherwise made things "now unstable," which feels like a regression? Might want to pay careful attention to the stability attributes... not certain.

**Comment by aturon** [comment]
cc @rust-lang/libs, I believe this change is in line with our general philosophy around `libcore`.

**Comment by alexcrichton** [comment]
This seems reasonable to me, but note that it's adding a new insta-stable type, `std::ops::Bound`. Previously this was only available at `std::collections::Bound` and I don't think we have many other instances in the standard library of the same type available in two locations.

What's the rationale for the movement to justify the duplication?

**Comment by clarcharr** [comment]
I hadn't considered this, and you're right. I could make a `core::collections` module to hold this type, although it does make the most sense in `core::ops`.

**Comment by alexcrichton** [comment]
@aturon it's been awhile since you last looked at this, mind giving it another look with an eye towards reviewing?

**Comment by Mark-Simulacrum** [comment]
@clarcharr Looks like there are quite a few compilation failures due to feature gating, could you take a look?

**Comment by Mark-Simulacrum** [comment]
@clarcharr Thanks for the contribution! The change looks good to me but it needs some changes still, see the Travis failure. Do you think you'll have a chance to make them soon?

**Comment by carols10cents** [comment]
Hi @clarcharr, thank you for your PR! Since there hasn't been any activity on this recently, we're going to close this to keep our open PR list current, but please feel free to reopen this when you have time to work on this again ❤️

**Comment by clarcharr** [comment]
I've redone this in #42268 and #42269.

**Pull request closed without merging**
