### PR TITLE
rustdoc: inline all the impls

### LINKED ISSUE #32881: Trait object inherent methods do not show in docs anymore
The docs for [std::any::Any](http://doc.rust-lang.org/nightly/std/any/trait.Any.html) don't show the methods on the trait object type `Any` anymore. (They show in stable).

For example: Method `downcast_ref()` does not show up.

### LINKED ISSUE #33025: rustdoc: External implementors for inlined traits are not shown
When re-exporting a external trait, the implementors section of that (inlined) trait does not show external implementors of it (unless they too have been inlined).
Re-exported external types on the other hand do show external trait implementations.

```rust
// foo.rs
extern crate bar;

pub use bar::Bar;
```

```rust
// bar.rs
pub trait Bar {}
pub struct Baz;

// this impl does not show up in `foo::Bar`s implementors section
impl Bar for Baz {}
```

### LINKED ISSUE #33113: missing impls in std::str::Pattern docs
Some of the impls of Pattern disappeared from the std docs starting in beta. Compare:

- http://doc.rust-lang.org/std/str/pattern/trait.Pattern.html (stable docs, impls shown)
- http://doc.rust-lang.org/nightly/std/str/pattern/trait.Pattern.html (nightly docs, impls missing)

They are also missing from the stable (and nightly) docs of core.

### PR DESCRIPTION
**Pull request by mitaa**
This used to be done to avoid inlining impls referencing private items, but is now unnecessary since we actually check that impls do not reference non-doc-reachable items.

fixes #32881 
fixes #33025
fixes #33113

r? @alexcrichton

### CODE REVIEW

**Comment by petrochenkov** [comment]
>we actually check that impls do not reference non-doc-reachable items

I'm curious, is this done with a separate check somewhere in rustdoc?
Because exactly this information is gathered in rustc_privacy and returned by `access_levels.is_doc_reachable(impl_id)`

**Comment by mitaa** [comment]
That was introduced in #33002. AFAIU the `access_levels` gathered in rustc_privacy are only for the local crate - so rustdoc tries to also [probe][0] the [crate metadata][1] in a similar way (i.e. also takes `doc(hidden)` into account) to `librustc_privacy::EmbargoVisitor` and adds that to `access_levels`.

[0]: https://github.com/rust-lang/rust/blob/478a33dabc4e6f2f501f476c79b56178d9df4f37/src/librustdoc/clean/mod.rs#L148-L149
[1]: https://github.com/rust-lang/rust/blob/master/src/librustdoc/visit_lib.rs

**Comment by alexcrichton** [comment]
@bors: r+ 8c302a00223abb46a2f42e5331fc27d1b1d35e1a

Nice!

**Comment by mitaa** [comment]
(updated)

**Comment by alexcrichton** [comment]
Looks like there's still an error on Travis?

```
failures:

---- [rustdoc] rustdoc/inline_local/issue-32343.rs stdout ----
	
error: htmldocck failed!
status: exit code: 1
command: "/usr/bin/python2.7" "/home/travis/build/rust-lang/rust/src/etc/htmldocck.py" "x86_64-unknown-linux-gnu/test/rustdoc/inline_local/issue-32343.stage2-x86_64-unknown-linux-gnu" "/home/travis/build/rust-lang/rust/src/test/rustdoc/inline_local/issue-32343.rs"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
21: @has check failed
	`XPATH PATTERN` did not match
	// @has - '//code/a' 'Bar'

Encountered 1 errors

------------------------------------------

thread '[rustdoc] rustdoc/inline_local/issue-32343.rs' panicked at 'explicit panic', /home/travis/build/rust-lang/rust/src/tools/compiletest/src/runtest.rs:1597
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [rustdoc] rustdoc/inline_local/issue-32343.rs
```

**Comment by mitaa** [comment]
Sorry, I guess checking local item links is a bit of an issue, and unnecessary. Because of that I've changed to only checking extern items.

**Comment by jethrogb** [comment]
This PR should be backported into beta, to fix this regression:
https://doc.rust-lang.org/stable/std/any/trait.Any.html
https://doc.rust-lang.org/beta/std/any/trait.Any.html

**Pull request merged**
