### PR TITLE
Rollup of 14 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
- Successful merges: #48403, #48432, #48546, #48573, #48590, #48657, #48727, #48732, #48753, #48754, #48761, #48474, #48507, #47463
- Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+

Added #48474, #48507, #47463.

**Comment by kennytm** [comment]
Same error. Some PR is significantly slowing down the jobs.

**Comment by kennytm** [comment]
@bors r+ 

Removed #48647, #48669 (the latter is removed due to rebase conflict with Cargo.lock).

**Comment by alexcrichton** [comment]
All dist jobs succeeded, merging manually

* [Travis](https://travis-ci.org/rust-lang/rust/builds/349854736)
* [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6569)

**Comment by kennytm** [comment]
@bors retry 

3 hour timeout in `check-aux`.

**Pull request merged**
