### PR TITLE
check_const: use the same ParamEnv as codegen for statics

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes at least part of https://github.com/rust-lang/rust/issues/52849 (my CTFE-stress benchmark). Note that I do not know what I am doing here, this is just based on hints from @oli-obk.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors r+

papers over a recent compile time regression. We're figuring out a nice fix. Until then, this should do it.

**Comment by RalfJung** [comment]
@bors r-
we'll do a perf run first

**Comment by kennytm** [comment]
@rust-timer build daf753aef352e31e3c849c10ea2249502c24092a

**Comment by RalfJung** [comment]
perf seems to say it definitely helps. As expected, `check` is still much slower -- previously, `check` wouldn't even compute the statics; now it does. But also for `opt` and `debug`, there's still a very noticeable gap between pre-sanity_check and post-this-patch. However, that's in a benchmark marked `?`.

**Comment by oli-obk** [comment]
Nominating for beta as it partially addresses the perf regression in https://github.com/rust-lang/rust/issues/52849#issuecomment-415967297

**Comment by nikomatsakis** [comment]
cc @rust-lang/compiler -- marking as **beta-accepted** since it is a small PR, approved by @oli-obk and @RalfJung, and affects a serious perf regression

**Comment by nikomatsakis** [comment]
Backported in https://github.com/rust-lang/rust/pull/53825

**Pull request merged**
