### PR TITLE
Cross reference io::copy and fs::copy in docs.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/52524.

### CODE REVIEW

**Comment by pietroalbini** [comment]
Ping from triage @steveklabnik! This PR needs your review.

**Comment by TimNN** [comment]
Ping from triage @steveklabnik / @rust-lang/docs: This PR requires your review.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
