### PR TITLE
Revert let_chains stabilization

### PR DESCRIPTION
**Pull request by Noratrieb**
This reverts commit 326646074940222d602f3683d0559088690830f4.

It was discovered in #100513 that they are not implemented correctly, which does not make them ready for stabilization.

The merge in the let parsing had a few conflicts, cc @compiler-errors and @c410-f3r to make sure I did it correctly (alternatively I could also revert @compiler-errors' let diagnostic improvement PR as well if a simpler revert is desired).

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by compiler-errors** [comment]
Discussed with nils on zulip, this looks fine.

@bors r+ rollup=never p=1

**Comment by Nilstrieb** [comment]
Looking at CI, this doesn't look fine to me :)
Or is this normal that is failing for beta?

**Comment by compiler-errors** [comment]
Yeah, that's broken I think :thinking:

**Comment by Nilstrieb** [comment]
The `feature(let_chains)` attribute in rustc_errors got an incorrect `cfg_attr(bootstrap)`. I added it unconditionally and didn't see any other wrong features, so it should hopefully pass CI now.

**Comment by compiler-errors** [comment]
@bors delegate=nilstrieb

r=me when CI is green then

**Comment by Nilstrieb** [comment]
i think i messed up my rebase, at least git printed a warning while trying to rebase on another branch :/

**Comment by Nilstrieb** [comment]
I did the entire revert again (copying out the conflict merge results from the PR here), could you take a quick look anyways to make sure I didn't break it? @compiler-errors

**Comment by compiler-errors** [comment]
The force-push diff looks right: https://github.com/rust-lang/rust/compare/b1f53f864deb49b078cabe6f6ae372bea7c99ad4..4b77950bac03717796b98df65b45bd9fee44a3d5

**Comment by Nilstrieb** [comment]
Oh no, it does not, the `cfg_attr` got in again 😢

**Comment by compiler-errors** [comment]
:rofl:

**Comment by c410-f3r** [comment]
https://youtu.be/roRQ2mNwMMQ

**Review by c410-f3r — APPROVED** [review]
https://github.com/rust-lang/reference/pull/1179 also needs to be reverted

**Comment by Nilstrieb** [comment]
😕 no idea what I should do here

**Comment by compiler-errors** [comment]
I think we gotta revert https://github.com/rust-lang/reference/pull/1179 first

**Comment by Nilstrieb** [comment]
Would anyone else like to do that?

**Comment by compiler-errors** [comment]
https://github.com/rust-lang/reference/pull/1251

**Comment by Nilstrieb** [comment]
LGTM (Looks green to me) but I'd like to get a second opinion nevertheless

**Comment by est31** [comment]
I'm not sure it's worth it, but just an idea. You could change `#![cfg_attr(bootstrap, feature(let_chains))]` to `#![cfg_attr(let_chains_unstable, feature(let_chains))]` together with some bootstrap magic that sets the cfg. Because right now, after this PR merges, one has to touch all places twice: once during stabilization, and once during update of the bootstrap (to remove the feature attr altogether). With my proposal, the first step is reduced to just changing the bootstrap magic to emit the cfg depending on if bootstrap is active or not. It's a feature that's heavily used in the compiler at this point.

**Review by wesleywiser — APPROVED** [review]
Revert looks good to me but I think we should wait for the compiler team triage meeting on Thursday before merging.

**Comment by pnkfelix** [comment]
[discussed](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-08-18/near/294097799) at T-compiler meeting.

@rustbot label: beta-accepted

**Pull request merged**
