### PR TITLE
Panic if NodeIds are used for incremental compilation

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
This makes the query system treat node ids as pure integers (which is what they are) instead of HIR ids.

cc @rust-lang/compiler Does anyone know of any scenarios this would break?

**Comment by Zoxc** [comment]
In order to do this, we'd have to track `node_to_hir_id` as that would reveal the `HirId` now. There's just 1 call of it left in the compiler proper though (some more in save-analysis).

**Comment by eddyb** [comment]
Do we deal with `NodeId`s anymore though? Can we remove these impls?

**Comment by Zoxc** [comment]
They exist in macro defs and attributes (in token trees). I'm not sure if they are actually used for anything though.

**Comment by eddyb** [comment]
cc @petrochenkov (sounds like the problem is interpolated `Nonterminal`s?)

**Comment by petrochenkov** [comment]
@eddyb, do you remember these PRs - https://github.com/rust-lang/rust/pull/56492 ("syntax: use MetaPath (a simpler version of Path) for Attribute and MetaItem"), https://github.com/rust-lang/rust/pull/56480 (Use hir::Path instead of ast::Path in HIR Attribute's)?
The goal was to avoid AST types being embedded into HIR types due to attributes.

**Comment by petrochenkov** [comment]
Nonterminal tokens don't exist in HIR, they are converted into primitive tokens during AST -> HIR lowering, so `NodeId`s shouldn't exist in HIR either. HIR hashing can insert some kind of runtime panic for them.

**Comment by eddyb** [comment]
> @eddyb, do you remember these PRs - #56492 ("syntax: use MetaPath (a simpler version of Path) for Attribute and MetaItem"), #56480 (Use hir::Path instead of ast::Path in HIR Attribute's)?

Oh right, it's... been a while. I plan to eventually go over unfinished work like that as soon as it's possible, but things keep coming up and most of my plans end up in the trash.
All I can do for the time being is apologize, I suppose.

> HIR hashing can insert some kind of runtime panic for them.

I wanted to suggest panicking but I wasn't sure if we're expecting leftover `NodeId`s, thanks!

**Comment by Zoxc** [comment]
I made this panic instead.

r? @petrochenkov

**Comment by petrochenkov** [comment]
@bors r+
(If it passes through CI.)

**Pull request merged**
