### PR TITLE
ast: Standardize visiting order for attributes and node IDs

### PR DESCRIPTION
**Pull request by petrochenkov**
This should only affect `macro_rules` scopes and order of diagnostics.

Also add a deprecation lint for `macro_rules` called outside of their scope, like in https://github.com/rust-lang/rust/issues/124535.

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by petrochenkov** [comment]
The number of root regressions is not large (10 crates), I think we can fix this.

- 491 cannot find macro `self_test` in this scope - in `document-features` (crate root)
- 196 cannot find macro `cargo_toml` in this scope - in `influxdb` (crate root)
- 136 cannot find macro `blob_url_prefix` in this scope - in `chumsky` (crate root)
-  84 cannot find macro `font_bmp` in this scope - in `bitmap-font` (module)
-  32 cannot find macro `docs_self` in this scope - in `pacaptr` (module)
-   9 cannot find macro `file_url` in this scope - in `html5tokenizer` (crate root)
-   4 cannot find macro `doc_WallpaperBuilder_example` in this scope - in `more-wallpapers` (crate root)
-   4 cannot find macro `alias_file` in this scope - in `attr_alias` (crate root)
-   3 cannot find macro `stringified_module_code` in this scope - `safer-ffi` (module)
-   2 cannot find macro `doctest_example` in this scope - `test_gen` (crate root)

**Comment by petrochenkov** [comment]
Updated with the deprecation lint.
@rustbot ready

**Comment by petrochenkov** [comment]
Lint descriptions :rage4:

**Review by davidtwco — APPROVED** [review]
This seems good to me, I agree that the regressions in crater seem like something we can fix. Do we want to make this lint warn-by-default so we aren't breaking anything and can merge this, and then can toggle it once we've fixed those? I can't recall if that is our usual approach for introducing new future-incompat lints.

**Comment by petrochenkov** [comment]
I'll better turn this to warn-by-default (don't currently have time to send fixes to the crates).

**Comment by petrochenkov** [comment]
Rebased and changed the lint to warn-by-default.

**Review by davidtwco — APPROVED** [review]
r=me once you've rebased

**Comment by nnethercote** [comment]
What was the motivation for this change?

**Comment by petrochenkov** [comment]
Fixing scoping for `macro_rules` and reporting diagnostics in source code order.

**Comment by pnkfelix** [comment]
visiting for weekly rustc-perf triage

* solely regressions to secondary benchmark: tt-muncher.
* marking as triaged

@rustbot label: +perf-regression-triaged

**Pull request merged**
