### PR TITLE
Move some tests to more reasonable directories

### PR DESCRIPTION
**Pull request by c410-f3r**
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
issue-36708.rs - certainly not impl-trait, typeck maybe
issue-40231-1.rs, issue-40231-2.rs - unsized maybe
@rustbot author

**Comment by c410-f3r** [comment]
> issue-36708.rs - certainly not impl-trait, typeck maybe issue-40231-1.rs, issue-40231-2.rs - unsized maybe @rustbot author

Done

**Pull request merged**
