### PR TITLE
mark vec::IntoIter pointers as `!nonnull`

### PR DESCRIPTION
**Pull request by the8472**
This applies the same NonNull optimizations to `vec::IntoIter` as  #113344 did for `slice::Iter`

[Godbolt](https://rust.godbolt.org/z/n1cTea718) showing the test IR on current nightly, note the absence of `!nonnull` on the loads.

r? @scottmcm

### CODE REVIEW

**Comment by scottmcm** [comment]
r=me, assuming perf comes back tolerable

**Comment by workingjubilee** [comment]
> r=me, assuming perf comes back tolerable

> Overall result: ❌ regressions

Gonna assume that's a no.
@rustbot author

**Comment by workingjubilee** [comment]
nom-json win of minus 16% speedup

...maybe that's a justification tho'.

**Comment by the8472** [comment]
We don't have charts for the runtime benchmarks yet so it's hard to eyeball how significant that is.

Plus most of the regressions are in incremental with the dep-graph growing a bit. I don't know what that means, but maybe there's some fat that can be shaved off.

**Comment by Kobzol** [comment]
> We don't have charts for the runtime benchmarks yet so it's hard to eyeball how significant that is.

I'll try to add charts and possibly also some cachegrind diff so that we can examine what causes these runtime benchmark changes.

**Comment by scottmcm** [comment]
It's frustrating that changes like this even cause *check* regressions 😢  This isn't doing anything that `check` should have to care about, since none of the signatures are different and it's not using RPIT.

I wonder if we could make a `slice::PtrIter` that just gives out `NonNull`s, and implement `slice::Iter`, `slice::IterMut`, and `vec::IntoIter` all around it somehow, as a way to not need to repeat the 
```rust
        unsafe { &mut *ptr::addr_of_mut!($place).cast::<NonNull<$t>>() }
```
dance so many times...

**Comment by the8472** [comment]
I suspect that the extra code affects inlining (e.g. due to the extra indirection through `NonNull::eq`) but I'm not sure how to check that.

**Comment by JohnCSimon** [comment]
@the8472 
ping from triage - can you post your status on this PR? This PR has not received an update in a few months. Thank you!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by the8472** [comment]
shaved off a few function calls by replacing them with `as` casts. let's see if it makes any difference.

@bors try @rust-timer queue

**Comment by the8472** [comment]
Looks quite neutral now, though far from the slice improvements.
I'm fine with either merging or closing.

@rustbot ready

**Comment by the8472** [comment]
> subtrahend
> subtracted

platform-specific IR naming? Fun...

**Pull request merged**
