### PR TITLE
Fix for issue #28012: pow overflow inconsistency

### LINKED ISSUE #28012: i32::pow only handles overflow up to an exponent of 1023
Playpen: http://is.gd/zhwksu

```rust
fn main() {
    let x: i32 = 2;

    println!("{}", x.pow(1024));
    println!("{}", x.pow(1023));
}
```

Prints:
```
0
thread '<main>' panicked at 'arithmetic operation overflowed', ../src/libcore/num/mod.rs:550
```

Interestingly, this only seems to happen with an even base. The overflow is detected correctly when `x` is set to 3 or other odd numbers.

### PR DESCRIPTION
**Pull request by PeterReid**
Overflows in integer pow() computations would be missed if they
preceded a 0 bit of the exponent being processed. This made
calls such as 2i32.pow(1024) not trigger an overflow.

Fixes #28012

### CODE REVIEW

**Comment by ranma42** [comment]
Should we add a test for this?

**Comment by alexcrichton** [comment]
Thanks! As @ranma42 mentioned, can you be sure to add a new test for this as well?

**Comment by PeterReid** [comment]
Here's that test. It just checks that the 2**1024 computation from the original issue panics, structured the same way as several other run-fail/overflowing_*.rs tests.

**Comment by alexcrichton** [comment]
@bors: r+ a593a211fe71e82b3f87dd16fb25831fb8a00442

Thanks!

**Pull request merged**
