### PR TITLE
Remove i suffix in docs

### PR DESCRIPTION
**Pull request by steveklabnik**
This takes advantage of integer fallback to stop recomending `i` so much.

### CODE REVIEW

**Comment by Gankro** [comment]
Awesome! Did you check for `u`s aswell? I imagine none of those are really meaningful either.

**Comment by steveklabnik** [comment]
@Gankro I did not check for `u`, as I know that I was perpetuating `i`, and wanted to atone for my sins :wink:

**Comment by alexcrichton** [comment]
Needs a rebase

**Comment by alexcrichton** [comment]
This actually didn't land in #20610, sorry for the confusion! I had to revert it in https://github.com/rust-lang/rust/commit/ee9921aaedb26de3cac4c1c174888528f68bbd3f.

@steveklabnik could you reopen this? Again, sorry for the trouble!

**Comment by steveklabnik** [comment]
It's all good. yeah, let me open a new PR.

**Comment by steveklabnik** [comment]
This patch is too much trouble to fix, so i'll open a new one eventually.

**Pull request merged**
