### PR TITLE
rustc_target: support Unix-flavor linkers for UEFI

### PR DESCRIPTION
**Pull request by alyssais**

### CODE REVIEW

**Comment by alyssais** [comment]
In the test that's failing:

> // Check that flavors mentioned in link args are compatible with the default flavor.

Can we not add linker arguments for non-default linkers?

**Comment by petrochenkov** [comment]
This needs some context.

UEFI uses PE/COFF binary format, right?
I'm only aware of one Unix-style linker that can produce it, it's the linker from mingw toolchain - are you trying to cover this case or something else?

@rustbot author

**Comment by alyssais** [comment]
> I'm only aware of one Unix-style linker that can produce it, it's the linker from mingw toolchain - are you trying to cover this case or something else?

No, I'd like to use ld.lld, which can also produce COFF.

The reason for specifically using the ld interface of lld is as follows: in [Nixpkgs](https://github.com/NixOS/nixpkgs), cc is a wrapper script around the actual C compiler, which in this case is clang.  The wrapper script is there so that we can set up the compiler with our library search paths and so on.  Compiler wrappers like this are very common among package collections — I'm somewhat familiar with pkgsrc and Homebrew, both of which also use compiler wrappers.  Our compiler wrapper was written for Unix compilers and linkers, so it understands Unix-flavor flags, but not the Windows-style ones rustc uses by default for UEFI targets.  But since rustc supports choosing the linker flavor, the best way for us to add support to our toolchain for building UEFI binaries with Rust is to tell it to use the Unix-flavor arguments.  This works fine with these small changes to teach rustc how to handle the UEFI specifics for Unix-flavor linkers.

**Comment by petrochenkov** [comment]
Ok, I see.
It's hard to accommodate for differences between toolchains like msvc and clang+lld in one target.

I suggest adding new UEFI targets `*-unknown-uefi-gnu` for this.
I.e. a `uefi_msvc_base`/`uefi_gnu_base` pair and specific targets inheriting from it, in the same way like we currently have `windows_msvc_base` and `windows_gnu_base`.

As a bonus they will be able to use mingw toolchain for linking for UEFI too (if it works at all).

**Comment by dvdhrm** [comment]
Using `*-gnu` as suffix might confuse people into thinking it follows the `gnu-efi` model.

Given that RISCV-on-PE is still not supported by LLVM, there might be people working to resurrect the `gnu-efi` model and compile ELF binaries which are then loaded by a PE-stub on UEFI. These would then likely use some `*-gnu` suffix. Hence, I would avoid the `*-gnu` suffix here.

I don't have a better idea, though. Sorry. Preferably, we would be able to detect the argument-style of lld at runtime and keep a single target.

**Comment by Dylan-DPC** [comment]
@alyssais any updates on this? thanks

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
