### PR TITLE
Remove `TokenStreamBuilder`

### PR DESCRIPTION
**Pull request by nnethercote**
`TokenStreamBuilder` is used to combine multiple token streams. It can be removed, leaving the code a little simpler and a little faster.

r? @Aaron1011

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at a time.

cc @pnkfelix Because of the parts relating to #57735.
cc @mystor Because it touches some proc macro stuff.
cc @petrochenkov Because it involves tokens.

**Comment by Aaron1011** [comment]
r=me, assuming that there are no objections from any of the other mentioned reviewers.

**Comment by nnethercote** [comment]
It has been a week since the PR was filed, and I don't think it's controversial, so I will r+. It'll take a while to get merged, if anyone objects they can still r- in the meantime.

@bors r=Aaron1011

**Pull request merged**
