### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by tmandry**
Successful merges:

 - #64337 (libstd: Fix typos in doc)
 - #64986 (Function pointers as const generic arguments)
 - #65048 (Added doc about behavior of extend on HashMap)
 - #65191 (Add some regression tests)
 - #65200 (Add ?Sized bound to a supertrait listing in E0038 error documentation)
 - #65205 (Add long error explanation for E0568)
 - #65263 (Deduplicate is_{freeze,copy,sized}_raw)
 - #65266 (Mark Path::join as must_use)
 - #65276 (Don't cc rust-lang/compiler for toolstate changes)
 - #65277 (Query generator kind for error reporting)
 - #65283 (stability: Do not use `buffer_lint` after lowering to HIR)
 - #65297 (Rollup of 16 pull requests)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Centril** [comment]
Seems the 16 PR rollup was included as well? @bors r- retry

**Comment by tmandry** [comment]
😞 not sure how that happened..

**Comment by Centril** [comment]
@tmandry probably a bug in homu introduced by yours truly. :)

**Pull request closed without merging**
