### PR TITLE
Fix typo in mod_file_nonascii_forbidden.stderr

### PR DESCRIPTION
**Pull request by eltociear**
identifer -> identifier

### CODE REVIEW

**Comment by henryboisdequin** [comment]
@eltociear Since you are modifying a `.stderr` file you first need to update the original diagnostic message. After that, run `./x.py test src/test/ui/` to update all the `.stderr` files.

**Comment by JohnCSimon** [comment]
@eltociear Ping from triage - can you address the merge comments? thanks

**Comment by crlf0710** [comment]
Already covered in #83936, closing.

**Pull request closed without merging**
