### PR TITLE
syntax: Remove traits `AttrMetaMethods`, `AttributeMethods`, and `AttrNestedMetaItemMethods`

### PR DESCRIPTION
**Pull request by jseyfried**
**syntax-[breaking-change] cc #31645**
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @cgswords @eddyb 
@Manishearth This is based on top of #35850 for easier inclusion in the breaking batch.

**Comment by nrc** [comment]
r+

**Comment by jseyfried** [comment]
Rebased.

**Comment by jseyfried** [comment]
Rebased.

**Comment by nrc** [comment]
@Manishearth r=@nrc

**Pull request merged**
