### PR TITLE
Improve diagnostics for Precise Capture

### LINKED ISSUE #22: Improve diagnostics for Precise Capture
Currently, we store and report back only one expression for why a particular path is captured and how the path is captured. We prioritize how the path is captured (i.e on the CaptureKind  -- ByValue/ByRef). This works today since the root variable is captured in entirety, however won't result in good diagnostics once the feature is complete. 

Consider the following example
```rust
let p = Point { x: 10, y: 10 };

let c = || {
    p.x      += 10;
//  ^ E1 ^
    println!("{:?}",  p);
//                  ^ E2 ^
};
```

Here the result of the capture analysis is `p` is borrowed by a `MutBorrow`. This is because `E1` force the `MutBorrow` and `E2` forces the path `p`. 

By storing only one piece of information currently `E1` (since we prioritize the capture kind) in diagnostics can't express all the information a user might need to fix their code.

We need to update `CaptureInformation` (`rustc_middle/src/ty/mod.rs`) to contain two expression ids (`capture_kind_expr_id`, `path_expr_id`). We then use this to emit two notes.

```rust
let mut p = Point { x: 10, y: 10 };

let c = || {
    p.x      += 10;
//  ^ mutable borrow of `p` happens here
    println!("{:?}",  p);
//                    ^ `p` is captured since it's used here.
};
```

In case both the `capture_kind_expr_id` and `path_expr_id` are the same we only emit one-note similar to how we do it today. 

```rust
let mut p = Point { x: 10, y: 10 };

let c = || {
    p  = Point { ... } ;
//  ^ mutable borrow of `p` happens here
};
```

### PR DESCRIPTION
**Pull request by ChrisPardy**
This is just the capture analysis part and borrow checker logging will updated as part of rust-lang/project-rfc-2229#8

Closes rust-lang/project-rfc-2229#22

### CODE REVIEW

**Comment by ChrisPardy** [comment]
r? nikomatsakis

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
This looks good. I was thinking about what kinds of tests make sense. I'm going to post a separate comment.

**Comment by nikomatsakis** [comment]
It seems like we want to cover the following cases:

| Use 1 | Use 2 | Expected result | Covered |
| --- | --- | --- | --- |
| move `p.x` | read `p` | cite both | :heavy_check_mark: |
| write `p.b.q.y` | read `p` | cite both | :heavy_check_mark: |
| write `t.0.0.0` | read `t` | cite both | :heavy_check_mark: |
| move `a.b.c` | read `a.b` | cite both | :x: |
| move `a.b` | read `a.b.c` | just cite `a.b` | :x: |

Maybe add those two tests?

At that point feel free to r=nikomatsakis

@bors delegate+

**Pull request merged**
