### PR TITLE
ci: Move most builders to Azure Pipelines

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit disables all builders on Travis and almost all builders on
AppVeyor now that they're all running on Azure Pipelines. There is one
remaining builder on AppVeyor which hasn't been migrated yet due to a
test failure on Azure, which we'll be debugging soon. One remaining
builder is left on Travis which is the tools builder whenever a
submodule is changed, but we'll probably turn that off soon since it's
just for PRs.

The other major change in this PR is that the auto builders on Azure are
now configured with "real" prod credentials which should cause them to
publish all artifacts into the official CI buckets.

### CODE REVIEW

**Comment by RalfJung** [comment]
> One remaining
builder is left on Travis which is the tools builder whenever a
submodule is changed, but we'll probably turn that off soon since it's
just for PRs.

Is there a plan for an Azure-based replacement for this in-PR-tools-builder? It's been very useful, good to know that the checks pass in CI which can be hard or slow to do locally.

Not a big deal though if that doesn't work any more or will need some more time to be fleshed out. :)

**Comment by pietroalbini** [comment]
@RalfJung yep, it's tracked here: https://github.com/rust-lang/rust/issues/61837

**Comment by alexcrichton** [comment]
@bors: r=pietroalbini

Leaving x86_64-gnu-tools entirely on travis as well due to the same RLS failure on Azure. Seems like a spurious test failure we'll have to deal with one way or another o Azure.

**Pull request merged**
