### PR TITLE
Refactor two functions in rustc_resolver

### PR DESCRIPTION
**Pull request by MaciejWas**
Hi, this is my first contribution to the rust compiler :). When studying the code I found two functions which could use refactor:
 - I made resolve_crate_root fn use `Iter` chains instead of keeping a mutable state and peeking
 - I flattened legacy_const_generic_args so that the control flow is easier to see

### CODE REVIEW

**Comment by petrochenkov** [comment]
Second commit LGTM, the first one doesn't look like much of an improvement to me (all that logic is a hack and heuristic anyway).
@rustbot author

**Comment by MaciejWas** [comment]
Hi, thanks for your review. About first commit: I thought it was more readable after this change, but I get your perspective. I reverted it and continue with the second one.
@rustbot label -S-waiting-on-author +S-waiting-on-review

**Comment by petrochenkov** [comment]
Thanks!
r=me after squashing the commits and updating the PR description.
@rustbot author

**Pull request closed without merging**
