### PR TITLE
Fix hashing for windows paths containing a CurDir component

### PR DESCRIPTION
**Pull request by the8472**
* the logic only checked for / but not for \
* verbatim paths shouldn't skip items at all since they don't get normalized
* the extra branches get optimized out on unix since is_sep_byte is a trivial comparison and is_verbatim is always-false
* tests lacked windows coverage for these cases

That lead to equal paths not having equal hashes and to unnecessary collisions.

### CODE REVIEW

**Comment by the8472** [comment]
Lacking a windows machine (and too lazy to setup a VM) I haven't actually run the tests on windows.

**Comment by Mark-Simulacrum** [comment]
> That lead to equal paths not having equal hashes and to unnecessary collisions.

Equal paths not having equal hashes means that things like HashMap etc may be just broken today, right? Is this a recently introduced bug we should be backporting a fix for (IIRC, I may have approved a PR in this area somewhat recently).

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=iffy

In the meantime, this seems good to me.

**Comment by the8472** [comment]
>Equal paths not having equal hashes means that things like HashMap etc may be just broken today, right?

Yes.

>  Is this a recently introduced bug we should be backporting a fix for (IIRC, I may have approved a PR in this area somewhat recently).

#90596 (1.58).

**Comment by Mark-Simulacrum** [comment]
I'm going to beta nominate then for backport to 1.59, since it seems plausible that folks could hit it in the wild.

It might be worth considering running a fuzzer or similar against the old and new impls, maybe that could help uncover any other hidden bugs...?

**Comment by the8472** [comment]
I'll take a stab at that, would be my first time using one and this looks like a good first test case.

**Comment by the8472** [comment]
> I'm going to beta nominate then for backport to 1.59, since it seems plausible that folks could hit it in the wild.

Just to be explicit, identical paths will hash fine. It's only some not-identical-but-equal paths, on windows, that would hash incorrectly. Which means one would have to put something under one such path into a hashmap and then construct a different path as lookup key. And one can't use `PathBuf::push` to construct such a path because push is also normalizing. Not impossible, but probably mitigates the impact.

**Comment by the8472** [comment]
The failing test

https://github.com/rust-lang/rust/blob/6499c5e7fc173a3f55b7a3bd1e6a50e9edef782d/src/test/ui/issues/issue-23036.rs#L1-L10

Running it locally with the `wasm32-unknown-unknown` target gets a little further and fails with

```
/home/the8472/workspace/rust/src/etc/wasm32-shim.js:17
let m = new WebAssembly.Module(buffer);
        ^

CompileError: WebAssembly.Module(): Compiling function #3:"_ZN11issue_230364main17hf6fa4aae1344ccadE" failed: Invalid opcode 0xff @+874
    at Object.<anonymous> (/home/the8472/workspace/rust/src/etc/wasm32-shim.js:17:9)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

An LLVM bug?

**Comment by Mark-Simulacrum** [comment]
Maybe. Could be a NodeJS/V8 parsing bug too. Not really sure what the best way to investigate is -- probably cross-compiling to wasm32 locally or otherwise getting that bytecode to try and run it against a newer NodeJS or perhaps load it up in a disassembler of some kind?

It may be worth simplifying the test too, we probably just need to hash a path...

**Comment by the8472** [comment]
My system nodejs is 17.3, that's fairly recent.

> It may be worth simplifying the test too, we probably just need to hash a path...

Replacing the test with the following makes it pass.

```rust
    let mut hasher = RandomState::new().build_hasher();
    Path::new("a").hash(&mut hasher);
    dbg!(hasher.finish());
```

**Comment by the8472** [comment]
Rebuilt LLVM with asserts enabled, now I get the same error as CI

> rustc: /home/the8472/workspace/rust/src/llvm-project/llvm/lib/MC/WasmObjectWriter.cpp:149: void {anonymous}::writePatchableLEB(llvm::raw_pwrite_stream&, uint64_t, uint64_t) [with int W = 5; uint64_t = long unsigned int]: Assertion `SizeLen == W' failed.

**Comment by Mark-Simulacrum** [comment]
Hm. Well, maybe let's file a rust-lang/rust bug with that and ping the LLVM group -- I would like to see this PR land ideally, but it sounds like that might be tough to have happen in a shortish time frame.

I don't really have much expertise myself at digging in LLVM.

**Comment by the8472** [comment]
If we want a fix for beta then another option is to revert #90596, file a LLVM bug and then try to reland the version from this PR when it is fixed.

**Comment by Mark-Simulacrum** [comment]
Yeah, that's probably the right approach. Let's go ahead and revert #90596 on master to avoid needing to remember beta backports as well, and then we can backport that. Once the LLVM bug is fixed we can re-land the work (in combination with this PR).

**Comment by the8472** [comment]
A complete revert of #90596 also triggers this assert. I suspect this bug has been around for a while and is highly responsive to perturbations.

My observations so far

* master: [X] windows bug [ ] wasm bug
* this PR: [ ] windows bug [X] wasm bug
* revert 90596 whole: [ ] windows bug [X] wasm bug
* revert a083dd653af0f7f46ba6058ab51e1f9d6a2aca7d: [ ] windows bug [X] wasm bug
* revert 7f6e080120fe3c2fd067a5b8d5df04b45ef78b09 a6e0aa20d90ee9173a6b901c641a8d48abbd82db: [X] windows bug [ ] wasm bug

We can conclude that the universe does not allow wasm and windows to exist simultaneously.

Would it be ok to disable the test on wasm? It seems somewhat questionable since miscompilations of Path would be fairly serious. On the other hand the bug seems fragile in the first place.

E.g. changing the test from

```rust
     map.insert(Path::new("a"), 0); 
     map.get(Path::new("a")); 
```

to


```rust
    map.insert(Path::new("a"), 0);
    map[Path::new("a")];
```

or

```rust
     map.insert(Path::new("aa/./b"), 0); 
     map.get(Path::new("aa/b")); 
```

makes it pass.

**Comment by the8472** [comment]
Disabled the test. Since the issue appears to be preexisting and just trigger unreliable it shouldn't affect the beta nomination but you might want to reevaluate that anyway.

**Comment by Mark-Simulacrum** [comment]
I think the beta backport likely still makes sense, I suspect this assert is not really related to this PR (or even the previous one), just triggering some latent state inside LLVM.

@bors r+

**Pull request merged**
