### PR TITLE
Don't cache results of coinductive cycle

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Aaron1011** [comment]
cc @rust-lang/wg-traits @cjgillot - this PR is now ready for review.

I tested this on the benchmark from https://github.com/rust-lang/rust/issues/91598, and verified that it didn't result in an exponential blowup. However, it would probably be a good idea to test this PR on some various 'complex' uses of auto traits, to reduce the chance that this leads to a huge regression missed by our perf suite.

**Comment by jackh726** [comment]
r=me on the "don't cache" side of things. Not sure if @cjgillot has thoughts.

**Comment by cjgillot** [comment]
On the incr. comp. side, I agree that this is the best solution for now.  Devising a clean scheme to handle cycles is very hard, and probably way more brittle.
We still cache one node in the cycle, a kind of cycle root.  This node can be re-discovered by the other participants in the cycle by following the "slow" path.  In that case, the cached node would be correct.
As a consequence, the new scheme is more robust than the earlier one, so let's go ahead.

@bors r=jackh726,cjgillot

**Comment by lqd** [comment]
We could add a test from #96319.

**Pull request merged**
