### PR TITLE
Add `Captures` marker trait

### PR DESCRIPTION
**Pull request by alexreg**
Implements #56046.

### CODE REVIEW

**Comment by alexreg** [comment]
@rust-lang/libs I've done very little library work before, mainly working with the compiler. How do I add a feature gate for the library? Are feature-gate tests done in the same way as for compiler features?

**Comment by SimonSapin** [comment]
I believe `#[unstable]` as already used here is enough, regarding feature-gating.

However, please add to both the doc-comment and the description of the tracking issue: what this API does, why it exists, an example of how it is used.

You link to https://github.com/rust-lang/rust/issues/34511#issuecomment-373423999 to justify the existence of this feature, but that is a comment in the middle of the tracking issue for `impl Trait` type, which has very many comments, so it’s hard to understand what the context is.

Is this new API expected to be associated with language changes in how `impl Trait` type interact with borrow checking? While the tracking issue is still open, some of the functionality of `impl Trait` type is already available on Stable. Are these language-level changes still possible now or would they be breaking changes?

**Comment by alexreg** [comment]
@SimonSapin I don't believe there are any plans to change the language semantics for RPIT lifetimes, but I could be wrong. This solution is ambivalent to such potential changes, as I see it.

Regarding the tracking issue and doc comment: happy to add this once I can get a minimal working example. The doc comment already explains what it does, though the "why" and example do indeed need to be added. Will have a think about all this. I just wanted to get this issue formally out there in the open for now.

@nikomatsakis @aturon Thoughts and opinions on any of the above would be welcome, given your comments about this on the aforementioned tracking issue.

**Comment by alexreg** [comment]
@TimNN We've decide to take a separate approach to this. @eddyb left @nikomatsakis some suggestions on this on Discord, which he will be reviewing shortly, I think. :-)

**Comment by Dylan-DPC** [comment]
ping from triage @alexreg @eddyb any updates on this?

**Comment by alexreg** [comment]
@Dylan-DPC @eddyb had some ideas for @nikomatsakis about this (and making it a language feature). I think it's waiting for the two of them to talk before something can be done, I'm afraid.

**Pull request closed without merging**
