### PR TITLE
Update to chalk 0.31

### PR DESCRIPTION
**Pull request by jackh726**
Gonna assign @nikomatsakis to the review here, but since he is pretty busy recently, if anyone else wants to review this, that would be much appreciated.

r? @nikomatsakis

### CODE REVIEW

**Comment by matthewjasper** [comment]
r? matthewjasper
@bors r+

**Comment by jackh726** [comment]
Oh I have to bless in compare mode nll

**Comment by jackh726** [comment]
Okay this is ready again. @jonas-schievink @matthewjasper

**Comment by jackh726** [comment]
This has been rebased @matthewjasper

**Pull request merged**
