### PR TITLE
Update Source Code Pro and include italics

### LINKED ISSUE #65502: Rustdoc uses fake italics for code
For example https://doc.rust-lang.org/std/primitive.i32.html has the string “*See also the `std::i32` module*” which inludes code in italics. This is rendered using fake italics because the Source Code Pro italic font is not included.

Adding the italic font would fix this, but at the cost of having an extra font to download. Is the better formatting worth the (one-time?) download?

If there is an interest, I can prepare a PR to include the [latest version](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it) of Source Code Pro including the italic font. The sizes are as follows:

| Font | Current Size | Latest Size |
|:-|:-|:-|
| Regular | 55472 | 95872 |
| Semibold | 55360 | 95576 |
| Italic | | 84264 |
| *Total*| 110832 | 275712 |

### PR DESCRIPTION
**Pull request by tspiteri**
Fixes #65502.

A few notes:
  * As stated in #65502, this does increase the download size.
  * Since this PR changes the font set, I think docs.rs would have to be updated if this PR is merged.
  * The fonts have a double extension (.ttf.woff); this is to keep the names consistent with the upstream font release which does that to distinguish these from the .otf.woff files ([Source Code Pro otf renders poorly on older Windows system apps](https://github.com/adobe-fonts/source-code-pro/issues/25#issuecomment-9019600)).

### CODE REVIEW

**Comment by hellow554** [comment]
> As stated in #65502, this does increase the download size.
Can you say how much it will increase?

**Comment by tspiteri** [comment]
Reproducing the table in the issue below. Updating the upright fonts to the [latest version](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it) costs an extra 79 KiB, and including the italics costs 82 KiB, total increase is 161 KiB. I believe this shouldn't be such an issue, especially with caching.

Font | Current Size | Latest Size
-- | -- | --
Regular | 55472 | 95872
Semibold | 55360 | 95576
Italic |   | 84264
Total | 110832 | 275712

**Comment by tspiteri** [comment]
@JohnCSimon I think you got the wrong label.

**Comment by JohnCSimon** [comment]
Ping from triage
@QuietMisdreavus can you please review this pr? 
cc: @tspiteri 
Thanks

**Comment by GuillaumeGomez** [comment]
So we're doubling the size of the font to add italic if I understood correctly?

**Comment by tspiteri** [comment]
Basically adding about 75% current size to add italic, and this PR also adds another 75% to update the upright and bold to the latest version, so it's a 150% increase in total (from 110 kb to 275 kb).

**Comment by GuillaumeGomez** [comment]
I'm not sure if it's worth it... Any additional opinion @rust-lang/rustdoc ?

**Comment by joelpalmer** [comment]
Ping from Triage:  Any updates @rust-lang/rustdoc @GuillaumeGomez @tspiteri?

**Comment by ollie27** [comment]
I think we should merge this. If we're going to ship custom fonts they should at least be up to date and complete.

**Comment by GuillaumeGomez** [comment]
Fine by me then. Thanks @tspiteri !

@bors: r+ rollup

**Comment by tspiteri** [comment]
@GuillaumeGomez Great! When this is merged I think docs.rs has to be updated, though I couldn't figure out how that works in https://github.com/rust-lang/docs.rs/issues/270.

**Comment by GuillaumeGomez** [comment]
Don't worry, let them handle their part. ;)

cc @pietroalbini

**Comment by ehuss** [comment]
This broke font rendering on firefox on macos with the dark theme.  See https://github.com/rust-lang/rust/issues/60365#issuecomment-490306731 for details.  Can we maybe have a different solution?

image

**Comment by tspiteri** [comment]
Aargh!

@GuillaumeGomez Should I open a PR to revert this PR?

**Comment by GuillaumeGomez** [comment]
Yes please.

**Comment by GuillaumeGomez** [comment]
Considering it's broken, I already open the PR to revert it [here](https://github.com/rust-lang/rust/pull/66602).

**Comment by tspiteri** [comment]
As a workaround to the issue, I tried to open the woff files with fontforge and regenerate without doing any modification: my reasoning is that since fontforge does not support svg glyphs, it will remove them, and in fact the woff files do shrink a bit. However since I wasn't able to reproduce the issue I'm not able to test the workaround.

I made a test page to test the workaround: [https://tspiteri.gitlab.io/scp-test/test.html](https://tspiteri.gitlab.io/scp-test/test.html). The page has three pieces of code:
  1. Old: with the old font which should be fine, with dark background and light colour.
  2. New: with the new font which should demonstrate the issue where it exists.  I couldn't reproduce the issue myself.
  3. Fontforged: with the new font passed through fontforge.

If sample New looks bad (black on dark background) and sample Fontforged looks good (light colour on dark background) it means the workaround works. However I'm not even sure that sample New manifests the issue as I'm unable to reproduce the issue. Can someone who can reproduce the issue please have a look?

**Pull request merged**
