### PR TITLE
Link to corresponding sections for enum variants in rustdoc

### LINKED ISSUE #74849: Rustdoc should link fields/variants to their corresponding section
Currently, the generated Rustdoc page for a struct/enum just writes out struct fields/enum variants as plain text. It would nice if Rustdoc generated clickable links to the corresponding section for the field/variant - this would make it easy to read the docs for a particular field.

### PR DESCRIPTION
**Pull request by RDambrosio016**
resolves #74849 (for structs rustdoc shows fields omitted, so i am not sure if that should be removed and replaced for this)

This makes the text for each variant in an enum declaration a link to their corresponding section. As for the color that must be decided, i am by no means a design expert, i chose the color used for statics since it looked nice and not overbearing. But if you have an idea for a better color feel free to comment!

@Aaron1011 For structs do you mean rustdoc should render fields as well with clickable links for the fields?

Example of the output on dark theme
 Example

### CODE REVIEW

**Comment by Cldfire** [comment]
As far as the colors go, I played around with the blues a bit and came up with:

* Light theme: `#2f71b3`

image

* Dark theme: `#8eb4db`

image

* Ayu theme: `#98c1ee`

image

They all have good contrast for their respective backgrounds and fit in well with the surrounding colors.

Something else I noticed was that in the light and dark themes, we went from:

image

to, after this PR:

image

(`layout:` is colored now.) We should color the enum variants down there instead since that's the color that corresponds to the new links (or maybe we could leave them uncolored?).

**Comment by GuillaumeGomez** [comment]
I'm not a big fan of adding link in code blocks nor adding extra colors to the fields description (I don't mind adding colors in the type code block though).

**Comment by Aaron1011** [comment]
> resolves #74849 (for structs rustdoc shows fields omitted, so i am not sure if that should be removed and replaced for this)

@RDambrosio016: I think that's only for private fields/structs. For example, [rustc_infer::traits::Obligation](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/traits/struct.Obligation.html) shows all of the fields. I think it would be useful to generate links for structs as well.

@GuillaumeGomez: I think links in code blocks are very useful, especially for larger enums. For example, having links on [rustc_hir::ExprKind](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/enum.ExprKind.html) would make it much easier to read the description for any particular variant.

**Comment by GuillaumeGomez** [comment]
You already have all the links in the sidebar.

**Comment by Aaron1011** [comment]
@GuillaumeGomez: Personally, I find it easier to read through the code block enum declaration, rather than looking at the sidebar. Types used in codeblocks already have links - is there any harm in adding more?

**Comment by GuillaumeGomez** [comment]
Which types in codeblocks already have links?

Also, I said I don't like it but if people are in favor, then we'll merge it, don't worry. ;)

**Comment by Aaron1011** [comment]
@GuillaumeGomez: Any type used in a codeblock (other than a plain generic parameter `T`) has a link: see the pages I listed in https://github.com/rust-lang/rust/pull/75178#issuecomment-669069920 for examples

**Comment by GuillaumeGomez** [comment]
This is a good argument.

**Comment by GuillaumeGomez** [comment]
Ok, I've been thinking about it for a while, and here's my conclusion: this is a good idea. However, we should also do it for all types with fields (as long as we provide a section for the fields). What do you think?

Otherwise, great work here!

**Comment by RDambrosio016** [comment]
It has been decided this feature should be expanded to be more expansive, and it should be incrementally implemented, therefore i will be closing this PR and opening a tracking issue. Then incrementally opening PRs to add this.

**Pull request closed without merging**
