### PR TITLE
chore: Bump compiler_builtins

### PR DESCRIPTION
**Pull request by Patryk27**
- https://github.com/rust-lang/compiler-builtins/pull/598
- https://github.com/rust-lang/compiler-builtins/pull/601

### CODE REVIEW

**Comment by Patryk27** [comment]
Ah, I see what's happening - it looks like newest compiler-builtins provides intrinsics for f16 and f128, which are not supported by rustc yet:

https://github.com/rust-lang/rust/blob/dde8cfa597dff58e5f65f1184a83c2cc22318b6e/compiler/rustc_symbol_mangling/src/v0.rs#L322

compiler-builtins provides a dedicated feature-switch to disable those intrinsics:

https://github.com/rust-lang/compiler-builtins/blob/9dd4dbfcc68a2f57a1772e8c8e90f0dfa19e7cf0/Cargo.toml#L52

... so, I guess, the question is: should rustc simply force-activate it? (if so, how? -- I'm not sure on this part)

cc @Mark-Simulacrum

**Comment by tgross35** [comment]
Note that https://github.com/rust-lang/rust/pull/125016 does the same thing

**Comment by Patryk27** [comment]
Alright, I'm closing this one, since it's a duplicate of https://github.com/rust-lang/rust/pull/125016 🙂

**Pull request closed without merging**
