### PR TITLE
fix more clippy warnings

### PR DESCRIPTION
**Pull request by matthiaskrgr**
clippy::{redundant_pattern_matching, clone_on_copy, iter_cloned_collect, option_as_ref_deref, match_ref_pats}

r? @Dylan-DPC

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
looks like ci failed spuriously

@bors r+ rollup=never p=1

**Comment by matthiaskrgr** [comment]
@Dylan-DPC  err, this is not a toolstate fix ^^

**Comment by Dylan-DPC** [comment]
oof lol 

@bors p=0 rollup=maybe

**Comment by Dylan-DPC** [comment]
@bors r-

check CI (probably tidy)

**Comment by matthiaskrgr** [comment]
Fixed the formatting.

**Pull request merged**
