### PR TITLE
Use question_mark feature in libsyntax.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by japaric** [comment]
I think we explicitly don't use `?` in the `syntax` crate because it makes hard to update the `syntex` crate.

**Comment by ahmedcharles** [comment]
Really? How does it make it hard? I guess I can't submit the same change there since it's purpose is to work on stable. :)

**Comment by japaric** [comment]
> Really? How does it make it hard? I guess I can't submit the same change there since it's purpose is to work on stable.

The fact that doesn't work on stable means that syntex maintainers have to revert the `?`s back to `try`s when porting the syntax crate to the stable channel. See #34311

It's better to ask @erickt directly.

> It will be stable in a few weeks, anyways, right?

It just entered FCP. AIUI, it's at least one cycle to decide whether it will enter the next beta, then another cycle for it to go from beta to stable. So two releases at least; that's around 3 months.

**Comment by ahmedcharles** [comment]
Yeah, I understood why as I typed the comment. Anyways, it's already done and I'll keep it rebased on master. :)

**Comment by nrc** [comment]
Yeah, for the sake of @erickt's sanity, we shouldn't land this until `?` is stabilised. Closing this PR for now, but please do re-open once `?` is stable.

**Comment by ahmedcharles** [comment]
Will do.

**Pull request closed without merging**
