### PR TITLE
update Miri

### LINKED ISSUE #99224: `miri` no longer builds after rust-lang/rust#97995
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#97995, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @RalfJung, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/99224
r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
Oh, is `./x.py` not enough any more to update the lockfile?

**Comment by RalfJung** [comment]
@oli-obk this adds some new crates to the compiler lockfile, is there any process we have to follow for that?

**Comment by oli-obk** [comment]
> @oli-obk this adds some new crates to the compiler lockfile, is there any process we have to follow for that?

We either already have these in our list of allowed crates, or tidy will complain.

**Comment by RalfJung** [comment]
Looks like it does complain:
```
tidy error: invalid license `MIT OR Zlib OR Apache-2.0` in `miniz_oxide 0.5.3 (registry+[https://github.com/rust-lang/crates.io-index)`](https://github.com/rust-lang/crates.io-index)%60)
```

**Comment by RalfJung** [comment]
@Mark-Simulacrum does this change to the tidy license check seem fine?

**Comment by RalfJung** [comment]
I got [some people to look at the license checker changes](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Adjusting.20tidy.20for.20new.20crate.20dependencies.3F) and it looks like this is fine. Going ahead with this PR then. :)

@bors r+

**Pull request merged**
