### PR TITLE
Update LLVM to rust-llvm-2015-02-19

### LINKED ISSUE #21721: llvm::StructType::getElementType: Assertion `N < NumContainedTys && "Element number out of range!"' failed.
```rust
pub fn maybe_ptr() -> *const u8 {
    static NONE: Option<((), &'static u8)> = None;
    unsafe {
        *(&NONE as *const _ as *const *const u8)
    }
}
```
Running this in [the playpen](http://is.gd/NaIyoH) gives:
```
rustc: /build/rust-git/src/rust/src/llvm/include/llvm/IR/DerivedTypes.h:285: llvm::Type* llvm::StructType::getElementType(unsigned int) const: Assertion `N < NumContainedTys && "Element number out of range!"' failed.
Aborted (core dumped)
```
This is actually happening inside LLVM optimizations, in the `early-cse` pass (`-C opt-level=1` still triggers it). Originally found in a `memcpy` optimized into a `load`.
Reduced LLVM IR:
```llvm
target datalayout = "e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@NONE = internal constant { { {}, i8* } } zeroinitializer

define i8* @maybe_ptr() {
entry-block:
  %0 = load i8** bitcast ({ { {}, i8* } }* @NONE to i8**)
  ret i8* %0
}
```
cc @dotdash

### LINKED ISSUE #22159: LLVM doesn't know about jemalloc
LLVM can remove "dead" calls to malloc() (where the return value is ignored, or immediately free()-d (possibly after being compared with NULL)).  However, this is basically hardcoded to the "malloc" symbol (and "free", etc.); it is not aware of jemalloc (specifically je_mallocx and je_sdallocx), which Rust uses.

LLVM is very good at removing temporary allocations, as it turns out:

````rust
extern crate libc;
extern crate test;

fn main() {

unsafe {
    // totally dead (and a memory leak)
    // produces no calls to libc malloc
    let _ = libc::malloc(4);
        
    // freed immediately, no allocations
    libc::free(libc::malloc(4));
    
    // allocated, used to store something temporarily, then freed
    // still no allocations!
    let x = libc::malloc(std::mem::size_of::<i32>() as libc::size_t);
    assert!(!x.is_null());
    *(x as *mut i32) = 42i32;
    let y = *(x as *mut i32);
    libc::free(x);
    test::black_box(y);
}

}
````

will not call malloc or free (at -O2).

On the other hand, even the most trivial allocation using liballoc...

````rust
fn main() {
    let _ = Box::new(42i32);
}
````

will invoke je_mallocx and je_sdallocx, even at -O3.

/cc @dotdash

### PR DESCRIPTION
**Pull request by dotdash**
Fixes #22159
Fixes #21721

### CODE REVIEW

**Comment by Manishearth** [comment]
There seems to be a merge conflict, and  this might be the cause of a failure on android

http://buildbot.rust-lang.org/builders/auto-linux-64-x-android-t/builds/3681/steps/test/logs/stdio

`error: undefined reference to 'pthread_atfork'`

**Comment by Manishearth** [comment]
Not your fault. You are back in the rollup :smile:

**Comment by Manishearth** [comment]
(let's let this one merge)

**Comment by Manishearth** [comment]
This pull request has *incredibly* bad luck :sob:

**Comment by Manishearth** [comment]
Oh, great, all-seeing buildbot in the sky, whatever we have done to offend you, please forgive us this time and let this pull request may land. Thank you :heart:

**Comment by Manishearth** [comment]
Okay, that's new (for this PR)

```

command timed out: 1200 seconds without output, attempting to kill
process killed by signal 13
program finished with exit code -1
elapsedTime=2752.439075
```

whilst testing sync/threads. Possible deadlock? I think I've seen this before, but could someone verify on a mac if this failure is reproducible?

**Comment by alexcrichton** [comment]
@bors: retry

That's just stdtest deadlocking and happens somewhat regularly unfortunately on all platforms.

**Comment by Manishearth** [comment]
@alexcrichton Yeah, but with this PR I'm starting to suspect that something might be somehow broken (given the number of failures it's endured)

**Pull request merged**
