### PR TITLE
Unify region variables when projecting associated types

### PR DESCRIPTION
**Pull request by matthewjasper**
This is required to avoid cycles when evaluating auto trait predicates.
Notably, this is required to be able add Chalk types to `CtxtInterners` for `cfg(parallel_compiler)`.

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
r=me with or without nit

**Review by nikomatsakis — APPROVED** [review]

**Comment by spastorino** [comment]
[heavily discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/79848weeklymeeting2020082054818.html#207525792) in T-compiler meeting.

This is a subtle change to subtle code. We've also agreed on backporting it and fire a crater run as soon as possible, which probably won't be on time but would give as an advantage to act quickly if there are bad consequences.

@rustbot modify labels: beta-accepted

**Pull request merged**
