### PR TITLE
Stabilize SliceIndex trait.

### LINKED ISSUE #35729: Tracking issue for the `SliceIndex` trait
Tracking issue for https://github.com/rust-lang/rfcs/pull/1679

The implementations are stable, but the `SliceIndex` trait is not.

### PR DESCRIPTION
**Pull request by tmccombs**
CC #35729

According to recommendations in
https://github.com/rust-lang/rust/issues/35729#issuecomment-377784884

### CODE REVIEW

**Comment by tmccombs** [comment]
hmm, should I not make the methods hidden in docs, since that would break links to those methods in the documentation (at least I think that is the purpose of those tests).

@SimonSapin

**Comment by tmccombs** [comment]
I'm not sure why this is broken. Possibly related to this: https://github.com/rust-lang/rust/issues/13698 which is supposedly fixed.

**Comment by SimonSapin** [comment]
@tmccombs Please revert the `#[doc(hidden)]` additions so that we can land the rest of these changes, and file an issue to do them later.

**Comment by tmccombs** [comment]
will do.

**Comment by kennytm** [comment]
@tmccombs Hi could you do a "rebase" instead of "merge"?

**Pull request merged**
