### PR TITLE
[do not merge] Measure upper limit for performance of 32 bit `Span`

### PR DESCRIPTION
**Pull request by petrochenkov**
What would happen if span interner accesses were cheap and didn't require any synchronization?

r? @ghost

### CODE REVIEW

**Comment by petrochenkov** [comment]
TODO: Exclude rustdoc from bors try for this PR.

**Comment by nnethercote** [comment]
This will be interesting. https://github.com/rust-lang/rust/pull/59693#issuecomment-479829802 suggests that roughly half the speedup of 64-bit spans comes from fewer TLS accesses, and the other half comes from fewer hash table accesses.

**Comment by petrochenkov** [comment]
Oh, come on, why `x.py dist` tests rustbook, I disabled it.

**Comment by petrochenkov** [comment]
cc @Mark-Simulacrum 
Any hints on how to "disable running any rustdoc" in rustbuild on `bors try`?
So far `bors try` was behaving entirely differently from what I see on local attemts to run `dist` with or without `docker/run.sh`.

**Comment by petrochenkov** [comment]
@rust-timer build d80681574370cb24650e053d4f30bf0e28f8b923

**Comment by nnethercote** [comment]
The comparison URL is empty, showing an error message about "could not find commit..." :(

**Comment by Mark-Simulacrum** [comment]
Yeah, that's a known bug. The parent commit is still building.

**Comment by MSleepyPanda** [comment]
Parent commit is finished

**Comment by nnethercote** [comment]
This gets roughly 75% of the Span64 improvements (#59693).

**Comment by petrochenkov** [comment]
@nnethercote 
On the largest crates that's true, but I wouldn't say that in general.
Here's the diff between this PR (the first column) and that PR (the second column).
https://perf.rust-lang.org/compare.html?start=d80681574370cb24650e053d4f30bf0e28f8b923&end=cfa77658d2ba937d22801e3a5222fcfc7f63ca47

**Comment by petrochenkov** [comment]
I'd say that if we had perfectly inline-able TLS accesses or explicitly passed interner, then 64 bit spans would rather be a regression for most of crates beside `script-servo`.

**Pull request closed without merging**
