### PR TITLE
Customizable extended tools

### PR DESCRIPTION
**Pull request by o01eg**
This PR adds `build.tools` option to manage installation of extended rust tools.

By default it doesn't change installation. All tools are built and `rls` and `rustfmt` allowed to fail installation.

If some set of tools chosen only those tools are built and installed without any fails allowed.

It solves some slotting issues with extended build enabled: https://bugs.gentoo.org/show_bug.cgi?id=645498

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @alexcrichton 

Seems fine to me too, though looks somewhat odd... I'd like @alexcrichton to have a look though since this is dist-related.

**Comment by alexcrichton** [comment]
Thanks @o01eg! Mind adding a helper method to do the extended + is a member check? Other than that looks good to go!

**Comment by o01eg** [comment]
@alexcrichton Added commit with refactoring. I'm waiting installat step to see if something broken. Also I'm not sure about `#[allow(dead_code)]` but I have no other idea.

**Comment by alexcrichton** [comment]
@bors: r+

Looks fine by me!

**Pull request merged**
