### PR TITLE
Link to rustc guide

### PR DESCRIPTION
**Pull request by mark-i-m**
As proposed in https://github.com/rust-lang-nursery/rustc-guide/issues/239

### CODE REVIEW

**Comment by mark-i-m** [comment]
cc @gnzlbg

**Comment by gnzlbg** [comment]
@mark-i-m Thanks! 

I will just call this "Rust Compiler Guide", we want to advertise this for people that might be interested in contributing, but not be familiar with rust, and they might not make the conclusion that `rustc` is the rust compiler.

Also, the Rust Compiler Guide explains, for example, how to build Rust from source, run the tests, install it in a location that can be picked by rustup, etc. This is not the focus of the guide, but this is very useful information for people that want to build Rust from source for whatever reason, e.g., because rustup does not support their platform, because they are packaging Rust for a linux distribution, etc. 

It might well be that this group of people deserves their own guide, but since in the mean time the Rust Compiler Guide is all we got, I think it might be worth it to emphasize that it also explains these things.

**Comment by mark-i-m** [comment]
I'm honestly a bit torn about the naming. There is also a "rustc book" linked in the same page. It is a user guide of how to use the compiler.

**Comment by gnzlbg** [comment]
Yeah, that's definitely confusing. Maybe "Rust Compiler User Guide" vs "Rust Compiler Developer Guide" ?

**Comment by steveklabnik** [comment]
This isn't ready to go yet; the plan is to uplift that repo as a submodule in this one, and *then* do this.

We also discussed the naming at the time. https://github.com/rust-lang/rust/pull/49707

**Comment by gnzlbg** [comment]
@steveklabnik is there an open issue tracking that ? Adding the rustc book as a submodule is pretty straightforward.

**Comment by mark-i-m** [comment]
Oh, yeah, I forgot about that.

Do we need to wait for it to become a submodule first?

**Comment by steveklabnik** [comment]
> @steveklabnik is there an open issue tracking that ? Adding the rustc book as a submodule is pretty straightforward, is there anything blocking this?

There is no issue; the only think blocking it is @nikomatsakis saying that it's ready to go.

> Do we need to wait for it to become a submodule first?

Yes.

**Comment by gnzlbg** [comment]
@nikomatsakis what do you think ? Is the `rustc` guide "good enough" to be linked in the docs website ? It's a bit hard to discover right now, and it contains information that's useful for non-rustc developers like how to build the Rust toolchain from source and test it etc.

**Comment by mark-i-m** [comment]
We now have a submodule :)

**Comment by Dylan-DPC** [comment]
ping from triage @nikomatsakis @steveklabnik any updates on this?

**Comment by steveklabnik** [comment]
r=me if @nikomatsakis agrees

thank you! sorry for the delay.

**Comment by dwijnand** [comment]
(ah, the if let of r=me's :P)

**Comment by mark-i-m** [comment]
Ping @nikomatsakis ?

**Pull request merged**
