### PR TITLE
Add codegen tests for issues fixed by LLVM 16

### LINKED ISSUE #75978: Unnecessary instructions generated
I'm trying to figure out why certain iterator-based algorithms get const-optimized, while others don't and I stumbled upon this case.

[example](https://rust.godbolt.org/z/191WM4)

Compiling `fn1` results in the expected machine code, but `fn2` has extra stack reserve/free instructions that are not necessary, since the function's contents are optimized away completely. The stack size equals the size of the array.

### LINKED ISSUE #99960: Rust 1.56.0+ no longer recognizes boundary checks as avoiding division overflow panic
The following code (contrived for demonstration purposes) correctly checks for and avoids a division overflow condition (`i64::MIN` input coerced to `i64::MIN.abs()` output) but a regression in rustc 1.56.0 (still in latest nightly and latest 1.62.0 release) causes the optimizer to no longer skip the checked division and panic branch:

```rust
pub fn checked_div_i64(dividend: i64, divisor: i64) -> Option<i64> {
    if dividend > i64::min_value() && divisor != 0 {
        Some(dividend / divisor)
    } else {
        None
    }
}
```

[Godbolt link comparing 1.55.0 to 1.62.0](https://godbolt.org/z/x95rGbW4j)

@rustbot label +regression-from-stable-to-stable +A-codegen +A-llvm +I-heavy +I-slow +T-compiler

Edit:

It might be worth adding some regression tests for this because it's happened and then was fixed a few times before (e.g. introduced in 1.47.0 and fixed in 1.48.0).

### LINKED ISSUE #101048: codegen regression for bool
### Code

I tried this code:

<https://rust.godbolt.org/z/3EW6zoffE>

```rust
pub fn all_zero(data: &[u64]) -> bool {
    data.iter().copied().fold(true, |acc, x| acc & (x == 0))
}
```

I expected to see this happen: 
```asm
.LBB0_3:
        cmp     qword ptr [rdi + rcx], 0
        sete    dl
        and     al, dl
        add     rcx, 8
        cmp     rsi, rcx
        jne     .LBB0_3
```

Instead, this happened: 
```asm
.LBB0_3:
        test    al, al
        setne   dl
        cmp     qword ptr [rdi + rcx], 0
        sete    al
        and     al, dl
        add     rcx, 8
        cmp     rsi, rcx
        jne     .LBB0_3
```

There are two unnecessary instructions:

```asm
        test    al, al
        setne   dl
```

### Version it worked on

It most recently worked on: Rust 1.63, Rust beta

### Version with regression

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (748038961 2022-08-25)
binary: rustc
commit-hash: 7480389611f9d04bd34adf41a2b3029be4eb815e
commit-date: 2022-08-25
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### LINKED ISSUE #101082: Regression: Inlined loops not fully evaluating with `const`-eable dependencies
I tried this code:

```rust
pub fn arr() -> usize {
  let values = [23, 16, 54, 3, 60, 9];
  let mut acc = 0;
  for item in values { 
    acc += item;
  }
  acc
}
```

I expected to see this happen: The loop should be inlined because `values` is const-known. For example, here is the generated assembly on Rust 1.63.0 ([Godbolt](https://godbolt.org/z/75Y1c63cE)) and Rust Beta ([Godbolt](https://godbolt.org/z/KhcozT55j)):

```asm
example::arr:
        mov     eax, 165
        ret
```

Instead, this happened: On nightly, the loop is inlined. However, the entire function is not computed despite the stable and beta Rust inlining it.  Here is the generated assembly on Nightly ([Godbolt](https://godbolt.org/z/7bTWPh15s)):

```asm
.LCPI0_0:
        .quad   23
        .quad   16
.LCPI0_1:
        .quad   54
        .quad   3
.LCPI0_2:
        .quad   60
        .quad   9
example::arr:
        sub     rsp, 72
        movaps  xmm0, xmmword ptr [rip + .LCPI0_0]
        movaps  xmmword ptr [rsp], xmm0
        movaps  xmm0, xmmword ptr [rip + .LCPI0_1]
        movaps  xmmword ptr [rsp + 16], xmm0
        movaps  xmm0, xmmword ptr [rip + .LCPI0_2]
        movaps  xmmword ptr [rsp + 32], xmm0
        mov     qword ptr [rsp + 56], 6
        xor     ecx, ecx
        xor     edx, edx
        jmp     .LBB0_1
.LBB0_3:
        lea     rdi, [rcx + 1]
        mov     qword ptr [rsp + 48], rdi
        mov     rdx, qword ptr [rsp + 8*rcx]
        mov     esi, 1
        mov     rcx, rdi
        add     rdx, rax
        test    rsi, rsi
        je      .LBB0_5
.LBB0_1:
        mov     rax, rdx
        cmp     rcx, 5
        jbe     .LBB0_3
        xor     esi, esi
        add     rdx, rax
        test    rsi, rsi
        jne     .LBB0_1
.LBB0_5:
        add     rsp, 72
        ret
```

### Meta

n/a - disclosed at usages

Keywords: const inline loop, const loop, const loop not evaluated

Relevant discord thread: https://discord.com/channels/273534239310479360/592856094527848449/1013050670942793808

### LINKED ISSUE #101814: Poor optimization of iter().skip()
Using iter().skip() functions leads to poor optimization compared to the manually done loop with range.
https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=b7ed8bf9e4fc3341a92f301fa5185cc5

```rust
pub fn test_1(a: [i32; 10]) -> i32 {
    let mut sum = 0;
    for v in a.iter().skip(8) {
        sum += v;
    }
    
    sum
}

pub fn test_2(a: [i32; 10]) -> i32 {
    let mut sum = 0;
    for index in 8..10 {
        sum += a[index];
    }
    
    sum
}
```

This produces the following asm output:
```asm
playground::test_1:
	movq	%rdi, %r8
	addq	$40, %r8
	xorl	%esi, %esi
	movl	$8, %edx
	xorl	%eax, %eax
	testb	$1, %sil
	jne	.LBB0_2

.LBB0_5:
	leaq	-1(%rdx), %rsi
	movq	%r8, %rcx
	subq	%rdi, %rcx
	shrq	$2, %rcx
	cmpq	%rsi, %rcx
	jbe	.LBB0_4
	leaq	(%rdi,%rdx,4), %rdi

.LBB0_2:
	cmpq	%r8, %rdi
	je	.LBB0_4
	testq	%rdi, %rdi
	je	.LBB0_4
	addl	(%rdi), %eax
	addq	$4, %rdi
	movb	$1, %sil
	xorl	%edx, %edx
	testb	$1, %sil
	je	.LBB0_5
	jmp	.LBB0_2

.LBB0_4:
	retq

playground::test_2:
	movl	36(%rdi), %eax
	addl	32(%rdi), %eax
	retq
```

Considering the zero-cost abstraction rule and the fact that the compiler knows the size of the array, it should optimize test_1 to at least the same form as test_2 where it correctly detected that we only need two values summed. Instead, there's quite a chunk of asm with lots of branches.

The issue is present both in the stable version (1.63.0) and nightly/beta channels.

### LINKED ISSUE #103132: Overflow checks don't get optimized out surprisingly
I tried this code:

```rust
pub fn accumulate(arr: &[u8], weight: f32) {
    let weight = (weight * 256. * 256. * 256.) as u32;
    let weight = weight.min(256 * 256 * 256);

    // If you uncomment this, all examples will get optimized out fine on all versions.
    // let weight = weight.min(256 * 256 * 256 - 1);

    for x in arr {
        // This avoids overflow checks on 1.64.0 (but not on beta/nightly).
        // let result = f(*x, weight);

        // This inlined version has overflow checks.
        assert!(weight <= 256 * 256 * 256);
        let result = *x as u32 * weight;

        // This also has overflow checks for some reason.
        // let result = f2(*x as u32, weight);
    }
}

#[inline(always)]
fn f(x: u8, weight: u32) -> u32 {
    assert!(weight <= 256 * 256 * 256);
    x as u32 * weight
}

#[inline(always)]
fn f2(x: u32, weight: u32) -> u32 {
    assert!(weight <= 256 * 256 * 256);
    x * weight
}
```

https://godbolt.org/z/9c8qc88qo

I expected to see this happen: all three versions of the loop body have no overflow checks and are optimized out.

Instead, this happened: `let result = f(*x, weight);` has no overflow checks whereas the two other versions do have overflow checks on 1.64.0 and below, and on beta/nightly all versions have overflow checks. Also, uncommenting line #6, which makes `weight` bound one smaller, makes all three versions have no overflow checks on both 1.64.0 and nightly, which is extra weird because the bounds are satisfied with either value.

### LINKED ISSUE #103327: Missed optimization with short circuit AND
Consider this code:
```rs
pub fn other(a: i32, b: i32) -> bool {
    let c1 = (a >= 0) & (a <= 10);
    let c2 = (b >= 0) & (b <= 20);

    if c1 & c2 {
        a + 100 != b
    } else {
        true
    }
}

```
This compiles to just:
```asm
example::other:
        mov     al, 1
        ret
```
([Godbolt](https://godbolt.org/z/MGqTvb4ex))
However, changing any of the `&` to `&&` breaks this optimization and a bunch of cmps are generated as well as the addition, which seems unnecessary in this case, because `&`/`&&` shouldn't make any difference as short circuit can't be observed.
```asm
example::other:
        mov     al, 1
        cmp     edi, 10
        ja      .LBB0_3
        cmp     esi, 20
        ja      .LBB0_3
        add     edi, 100
        cmp     edi, esi
        setne   al
.LBB0_3:
        ret
```
([Godbolt](https://godbolt.org/z/e57zEEor3))
This works fine with [Clang](https://godbolt.org/z/Ev9bqrccn)

Doesn't seem like an LLVM issue (to me?). ~~The LLVM IR that Rust emits~~ [The resulting LLVM IR](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=29dc248880357f83fc2fae4501fb1da0):
```llvm
define zeroext i1 @test(i32 %a, i32 %b) unnamed_addr #0 {
start:
  %0 = icmp ult i32 %a, 11
  %1 = icmp ult i32 %b, 21
  %_13.0 = select i1 %0, i1 %1, i1 false
  br i1 %_13.0, label %bb4, label %bb6

bb4:                                              ; preds = %start
  %_16 = add nuw nsw i32 %a, 100
  %2 = icmp ne i32 %_16, %b
  br label %bb6

bb6:                                              ; preds = %start, %bb4
  %.0 = phi i1 [ %2, %bb4 ], [ true, %start ]
  ret i1 %.0
}
```
correctly gets optimized to this with `opt -O3 in -S -o out`
```llvm
define zeroext i1 @test(i32 %a, i32 %b) unnamed_addr #0 {
start:
  ret i1 true
}
```
([Godbolt](https://godbolt.org/z/n5jrfa4v8))

### PR DESCRIPTION
**Pull request by nikic**
Fixes #75978.
Fixes #99960.
Fixes #101048.
Fixes #101082.
Fixes #101814.
Fixes #103132.
Fixes #103327.

### CODE REVIEW

**Comment by nikic** [comment]
Probably more for...

r? @cuviper

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/110167#issuecomment-1502625050
@bors r- rollup=iffy

**Comment by nikic** [comment]
Looks like the usual issue with stdlib compiled with debug assertions.

@bors r=cuviper

**Comment by nikic** [comment]
Next try with a fix for 32-bit...

@bors r=cuviper

**Pull request merged**
