### PR TITLE
PlayStation Vita support

### PR DESCRIPTION
**Pull request by amgdev9**
Just the compiler definitions for no-std projects and std support using newlib

Earlier PR: https://github.com/rust-lang/rust/pull/105606

### CODE REVIEW

**Comment by amg98** [comment]
Just the compiler definitions for no-std projects. When merged I'll PR again with the std library adaptation.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
LGTM but I'd defer the final judge to t-compiler, r? @wesleywiser

**Comment by Onerazan** [comment]
Is there any progress to this? I want to try out compiling rust applications for the ps vita.

**Comment by amg98** [comment]
@Onerazan Sure! Just follow the docs in this PR and you should be able to compile an ELF file using Rust. You need the [VitaSDK](https://vitasdk.org/) installed first.

Also note that you need to provide the C bindings to use the vita syscalls, this PR only allows compiling rust to this target and using the standard library. For the syscalls part, you can use https://github.com/vita-rust/psp2-sys

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
The Tier 3 target policy was acknowledged in the original PR [here](https://github.com/rust-lang/rust/pull/90584#issuecomment-962180142). 

Thanks @amg98 for your patience getting this landed! 🙂 

@bors r+

**Pull request merged**
