### PR TITLE
Rename `NestedMetaItem` to `MetaItemInner`

### LINKED ISSUE #131087: `NestedMetaItem` would be better named as `MetaItemInner`
> An aside: `NestedMetaItem` would be better named as `MetaItemInner`, to match the grammar.

_Originally posted by @nnethercote in https://github.com/rust-lang/rust/pull/131034#discussion_r1781999888_

### PR DESCRIPTION
**Pull request by codemountains**
Fixes #131087 

r? @nnethercote

### CODE REVIEW

**Comment by nnethercote** [comment]
This is a good start! But for completeness there are some related names that should be changed as well. I grepped for `nested_meta` and found the following:
- `nested_meta` variable names -> `meta_item_inner` or `meta_inner` or `inner`
- `parse_nested_meta` method -> `parse_meta_item_inner`
  - often used with a `nested` closure argument -> `inner`
- `visit_nested_meta_item` -> `visit_meta_item_inner`

Please change these. You can do them in a separate commit. A few of them are in rustfmt, but that's fine, you can change them in this PR. Thanks!

**Comment by codemountains** [comment]
@nnethercote 

Thank you for your thorough review! I appreciate your attention to detail. I've made most of the suggested changes, but there are a couple of exceptions I'd like to highlight:

> - `parse_nested_meta` method -> `parse_meta_item_inner`
>   - often used with a `nested` closure argument -> `inner`

- I haven't modified the parse_nested_meta method as it's part of the [syn](https://crates.io/crates/syn) crate and not within our codebase to change.
  - The nested closure argument has been left as is because its type is ParseNestedMeta<'a>. 

All other suggested changes have been implemented as requested. 
Thank you again for your comprehensive review. Please let me know if you'd like me to make any further modifications or if you have any questions about the changes I've made.

**Comment by nnethercote** [comment]
Looks good. The added `nested_meta` commits are all so small, they can be combined into a single commit. (Sorry if my previous suggestion wasn't clear about that.) Once that's done I think it's good to go.

@bors delegate=codemountains

**Comment by codemountains** [comment]
@nnethercote 

Thank you for your review! I've addressed the changes as requested. I've combined all the small `nested_meta` commits into a single commit for better clarity and organization. I appreciate your guidance on this. 

Please let me know if there's anything else you'd like me to adjust or if you have any questions.

**Comment by nnethercote** [comment]
Thank you!

@bors r+

**Pull request merged**
