### PR TITLE
travis: Gate on some minimal support for incremental compilation.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This commit adds a travis job that

1. builds a stage2 compiler in incremental mode (but with empty incremental compilation cache), and
2. builds and runs the run-pass test suite also in incremental mode.

Building incrementally with an empty cache makes sure that the compiler doesn't crash in dependency tracking during bootstrapping. Executing the incrementally built test suite gives some measure of confidence that we generate valid code. 

Note, however, that the above does not give strong guarantees about the validity of incremental compilation, it just provides a basis for being able to rely on from-scratch incr. comp. builds as reference values in further tests (which then do actual incremental compilation).

r? @alexcrichton

### CODE REVIEW

**Comment by michaelwoerister** [comment]
cc @nikomatsakis

**Comment by alexcrichton** [comment]
@michaelwoerister have you confirmed that `RUSTFLAGS` does indeed work here? I could imagine that it's picked up by Cargo to build crates, but I'm not sure if we have logic to move those flags into compiletest test suites. Just want to make sure we're actually doing that all incrementally!

Additionally, perhaps we could just run the whole test suite here? Presumably stdtest/coretest/collectionstest may weed out other bugs that may otherwise crop up?

**Comment by michaelwoerister** [comment]
I did test that the compiler is invoked with `-Zincremental` during bootstrap, but you're right, the test suites are a different matter. I'll look into that.

> Additionally, perhaps we could just run the whole test suite here? Presumably stdtest/coretest/collectionstest may weed out other bugs that may otherwise crop up?

Good idea! Though I suspect that at least some of the tests would not want `-Zincremental` passed to them. Is there a way to filter out some tests/test suites? Or does `x.py` take multiple arguments?

**Comment by alexcrichton** [comment]
You can't say "don't run these suites" but you can indeed say "run all of these suites" with something like:

```
./x.py test src/test/run-pass src/test/compile-fail src/libstd ...
```

(etc)

**Comment by michaelwoerister** [comment]
Yeah, that should do the trick.

**Comment by alexcrichton** [comment]
ping @michaelwoerister, any update on this?

**Comment by michaelwoerister** [comment]
Somewhat: I can confirm that `RUSTFLAGS` are *not* passed down to tests with rustbuild. So in the current form, this would only test that bootstrapping works with incremental compilation and that a compiler generated this way would generate valid code. It would not confirm that it could also incrementally compile all tests and they'd still be valid.

The question is whether that's enough testing for now or whether I should extend `compiletest` with an "incremental mode" ...

**Comment by alexcrichton** [comment]
@michaelwoerister I'd be fine either way. We could always add this and then perhaps expand later if need be?

**Comment by michaelwoerister** [comment]
@alexcrichton I've updated this to just bootstrapping in incremental mode and then running `make check`.

**Comment by alexcrichton** [comment]
So that error is just a spurious network error, but @michaelwoerister I think that [this error](https://travis-ci.org/rust-lang/rust/jobs/193654786) may be caused by this PR? (found from the rollup)

**Comment by michaelwoerister** [comment]
I'll try to reproduce that locally.

**Comment by michaelwoerister** [comment]
OK, I was able to reproduce this locally. Haven't looked further into to yet...

**Comment by michaelwoerister** [comment]
So the problem here is that the run-make tests inherit the RUSTFLAGS env-var, which messes with the codegen-unit related tests there. I tried to fix this by setting CARGO_INCREMENTAL instead of RUSTFLAGS, but the Cargo version used from bootstrapping doesn't seem to pick that up yet.

**Comment by alexcrichton** [comment]
@michaelwoerister perhaps the compiletest support for run-make could delete the env var from spawned processes?

**Comment by michaelwoerister** [comment]
> perhaps the compiletest support for run-make could delete the env var from spawned processes?

I'll look into that. It would only be consistent with the rest of `compiletest`.

**Comment by michaelwoerister** [comment]
Yeah, that seems to be sufficient to fix the run-make tests. I just pushed a commit to that effect. 
r? @alexcrichton

**Comment by alexcrichton** [comment]
Oh I think we've got `.env_remove` to completely remove an env var, and could you also add a comment to the effect of why it's there?

**Comment by michaelwoerister** [comment]
Updated.

**Comment by alexcrichton** [comment]
@bors: retry

* sccache wedged https://github.com/rust-lang/rust/issues/39003

**Comment by alexcrichton** [comment]
@bors: retry

* segfault on musl #38618

**Pull request merged**
