### PR TITLE
Add additional float constants

### PR DESCRIPTION
**Pull request by ghost**
Initial implementation of this ACP: https://github.com/rust-lang/libs-team/issues/119. [Accepted]
Tracking issue: #103883

The values for the constants are copied from the [`libstdc++` source code](https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/libstdc%2B%2B-v3/include/std/numbers#L57-L120).

### CODE REVIEW

**Comment by leonardo-m** [comment]
SQRT_3 is useful.
Sometimes in rust code I've had to define:

    const LN_3: f64 = 1.0986122886681098;

**Comment by H4x5** [comment]
I've left the addition of ln(3) (and potential others) as an open question on the tracking issue: #103883

This PR just includes the ones missing from C++, as discussed in the ACP: https://github.com/rust-lang/libs-team/issues/119#issuecomment-1278270668

**Comment by thomcc** [comment]
This has ACP+ and these are unstable, so

@bors r+

**Pull request merged**
