### PR TITLE
[beta] Attempt to fix the component manifest problem for rls-preview

### PR DESCRIPTION
**Pull request by nrc**
cc #44270

r? @alexcrichton 

Hypothesis - this change will lead to the installer putting `rls-preview` instead of `rls` in the `components` file in the rls tarball, which will lead to rustup being happy with the component name in the rls package, and prevent the `CorruptComponent` error.

There is no good way to test this though, as far as I can see?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Sounds plausible to me!

I've retargeted this PR to the beta branch from the master branch and I've pushed a commit to bump the beta version as well, we can land it on nightly once we've verified that it works on beta.

@bors: r+

**Comment by alexcrichton** [comment]
@bors: p=1

I also realize that I don't think we've ever changed the base branch of a PR before, this may cause homu to explode.

**Comment by alexcrichton** [comment]
Hm ok I didn't really expect that to work...

@nrc want to close this an reopen a new PR targeted at beta?

**Comment by nrc** [comment]
I'll make a beta PR. Do we want to merge something to master too? Or will we forward-port the beta patch?

**Comment by alexcrichton** [comment]
Nah yeah let's do a PR for the master branch here. I think I've probably done enough damage here though by accident you may wish to make a new PR though? Feel free to r=me on a master PR (although give a higher p=10 to a beta PR)

**Comment by nrc** [comment]
New master PR: https://github.com/rust-lang/rust/pull/44356

**Comment by nrc** [comment]
beta PR: https://github.com/rust-lang/rust/pull/44357

**Pull request closed without merging**
