### PR TITLE
resolve: Recover from indeterminate macro resolutions more agressively

### PR DESCRIPTION
**Pull request by petrochenkov**
If we are in "forced resolution" mode and in-module resolution is indeterminate, don't give up and continue searching in outer scopes.

Fixes https://github.com/rust-lang/rust/issues/53481

### CODE REVIEW

**Comment by petrochenkov** [comment]
Nah, this is not a good solution, easy way to get compiling code with potentially inconsistent resolutions.
Need to try something more conservative first.
@bors r-

**Comment by petrochenkov** [comment]
The root issue here is that derive helper attributes like `#[serde]` in https://github.com/rust-lang/rust/issues/53481 or `#[my_attr]` in the test *require* going through forced resolution, this is something that needs to be avoided.

Ideally, forced resolution should never result in successful compilation, except for the `feature(custom_attribute)` case, but that feature is probably going to be retired eventually.

I'll return to this until beta/stable, but for now it's blocked by some other work from https://github.com/rust-lang/rust/pull/50911#issuecomment-411605393.

**Comment by norru** [comment]
Has consensus been reached on this resolution yet? I have been unable to upgrade Nightly past 2018-08-15 (build failures on dependencies).

**Comment by petrochenkov** [comment]
@norru 
This PR as written will result in accepting code that needs to be rejected and thus poses a backward-compatibility risk.
The proper fix is less trivial, but I hope to implement it in the next few weeks.

In the meantime, I'd recommend to implement a workaround in `log4rs` (if that is the dependency you are talking about) and publish a minor version, or simply to stay on the old nightly.

**Comment by norru** [comment]
Hi @petrochenkov, thanks for the extensive explanation. I am not willing/keen on using a patched version of https://github.com/sfackler/log4rs so I'll stick to the old Nightly. How long do you think is going to take, for the sake of my own planning? @sfackler FYI

**Comment by nikomatsakis** [comment]
@petrochenkov Is this PR still blocked?

**Comment by petrochenkov** [comment]
This PR can be closed actually,
The only thing that can be reused from here is the test.
I hope to return to this issue this weekend or next week.
It would be nice to land refactorings from https://github.com/rust-lang/rust/pull/53778 before that, but not necessary.

**Comment by Boscop** [comment]
@petrochenkov 
> or simply to stay on the old nightly.

I'm running into this issue with both `nightly-2018-08-25` and `nightly-2018-09-13`.
Which old nightly would work with log4rs?
I need to use at least `nightly-2018-08-25` because of rocket..

**Comment by petrochenkov** [comment]
@Boscop 
The issue was fixed in https://github.com/rust-lang/rust/pull/54086 (merged into rust-lang:master  10 hours ago), so the fix should appear in today's or tomorrow's nightly.

**Comment by jack-fraser** [comment]
@petrochenkov thank you for being so responsive. 

Everyone working with rocket and log4rs owes you one 🍺

**Pull request closed without merging**
