### PR TITLE
Add test for correct span for type

### LINKED ISSUE #27522: Bad span for self type
The high end of the span of `&SomeType` in

``` rust
trait Foo {
    fn handler(self: &SomeType);
}
```

is incorrectly set to `BytePos(0)`.

### PR DESCRIPTION
**Pull request by estebank**
Adds test for and closes #27522.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Hmm, `Failed to clone 'src/llvm' a second time, aborting`

@bors retry

**Comment by estebank** [comment]
Had to change test as the error is pointing at the type now instead of the argument. Rebased and fixed. Can I get a new r+ for the rebase, @petrochenkov?

**Comment by estebank** [comment]
@petrochenkov can I get a retry? The travis error is unrelated to this PR:
```
 Downloading num_cpus v0.2.13
warning: spurious network error (2 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
error: unable to get packages from source
```

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Pull request merged**
