### PR TITLE
Remove all unstable placement features

### LINKED ISSUE #22181: `box` and `in` expressions (tracking issue for RFC 809)
Tracking issue for https://github.com/rust-lang/rfcs/pull/809. This should be filled out with TODO items. Note that in this case there are some [unsettled design questions](https://github.com/rust-lang/rfcs/pull/809#issuecomment-73910414) to be resolved as well.

To do:
- [x] land placement-`in` desugaring implementation
- [ ] land overloaded-`box` desugaring implementation
- [ ] port `libstd` APIs to support `in`
- [ ] port `libstd` APIs to support `box`
- [ ] resolve/finalize syntax for placement-`in`
- [ ] investigate improvement of inference, coercion, and cast interactions (subissues #22221, #22403, #22405)
- [ ] improve error messages when code is rejected (#22231)

Unresolved questions:
- [ ] best precedence for `box` (was https://github.com/rust-lang/rust/issues/21192)

### PR DESCRIPTION
**Pull request by aidanhs**
Closes #22181, #27779. Effectively makes the assortment of placement RFCs (rust-lang/rfcs#470, rust-lang/rfcs#809, rust-lang/rfcs#1228) 'unaccepted'. It leaves `box_syntax` and keeps the `<-` token as recognised by libsyntax.

------------------------

I don't know the correct process for unaccepting an unstable feature that was accepted as an RFC so...here's a PR.

Let me preface this by saying I'm not particularly happy about doing this (I know it'll be unpopular), but I think it's the most honest expression of how things stand today. I've been motivated by a [post on reddit](https://www.reddit.com/r/rust/comments/7wrqk2/when_will_box_and_placementin_syntax_be_stable/) which asks when these features will be stable - the features have received little RFC-style design work since the end of 2015 (~2 years ago) and leaving them in limbo confuses people who want to know where they're up to. Without additional design work that needs to happen (see the collection of unresolved questions later in this post) they can't really get stabilised, and I think that design work would be most suited to an RFC rather than (currently mostly unused) experimental features in Rust nightly.

I have my own motivations - it's very simple to 'defeat' placement in debug mode today and I don't want a placement in Rust that a) has no guarantees to work and b) has no plan for in-place serde deserialisation.

There's a quote in [1]: "Ordinarily these uncertainties might lead to the RFC being postponed. [The RFC seems like a promising direction hence we will accept since it] will thus give us immediate experience with the design and help in determining the best final solution.". I propose that there have been enough additional uncertainties raised since then that the original direction is less promising and we should be think about the problem anew.

(a historical note: the first mention of placement (under that name - uninit pointers were earlier) in an RFC AFAIK is [0] in late 2014 (pre-1.0). RFCs since then have built on this base - [1] is a comment in Feb 2015 accepting a more conservative design of the Place* traits - this is back when serde still required aster and seemed to break every other nightly! A lot has changed since then, perhaps placement should too)

------------------------

Edit: **you should read the [summary comment](https://github.com/rust-lang/rust/issues/27779#issuecomment-378416911) instead of the notes below.**

Concrete unresolved questions include:

 - making placement work in debug mode [7]
 - making placement work for serde/with fallible creation [5], [irlo2], [8]
 - trait design:
   - opting into not consuming the placer in `Placer::make_place` - [2]
   - trait proliferation - [4] (+ others in that thread)
   - fallible allocation - [3], [4] (+ others in that thread)
 - support for DSTs/unsized structs (if at all) - [1], [6]

More speculative unresolved questions include:

 - better trait design with in the context of future language features [irlo1] (Q11), [irlo3]
 - interaction between custom allocators and placement [irlo3]

[0] https://github.com/rust-lang/rfcs/pull/470
[1] https://github.com/rust-lang/rfcs/pull/809#issuecomment-73910414
[2] https://github.com/rust-lang/rfcs/issues/1286
[3] https://github.com/rust-lang/rfcs/issues/1315
[4] https://github.com/rust-lang/rust/issues/27779#issuecomment-146711893
[5] https://github.com/rust-lang/rust/issues/27779#issuecomment-285562402
[6] https://github.com/rust-lang/rust/issues/27779#issuecomment-354464938
[7] https://github.com/rust-lang/rust/issues/27779#issuecomment-358025344
[8] https://github.com/rust-lang/rfcs/pull/1228#issuecomment-190825370
[irlo1] https://internals.rust-lang.org/t/placement-nwbi-faq-new-box-in-left-arrow/2789
[irlo2] https://internals.rust-lang.org/t/placement-nwbi-faq-new-box-in-left-arrow/2789/19
[irlo3] https://internals.rust-lang.org/t/lang-team-minutes-feature-status-report-placement-in-and-box/4646

### CODE REVIEW

**Comment by aidanhs** [comment]
Probably for the lang team? r? @nikomatsakis

**Comment by estebank** [comment]
@rust-lang/lang

**Comment by estebank** [comment]
(Doing this would also close #36611.)

**Comment by nikomatsakis** [comment]
@aidanhs I've been wondering about the procedure to "unaccept" a feature myself on a few occasions. I guess this is as good as any. I think I'm inclined to agree that it makes sense to "back off" from supporting this right now until we have time to focus again.

**Comment by coder543** [comment]
I agree that this will be unpopular, but your reasoning is sound. Really, Rust _needs_ to figure out the placement-new stuff. Ideally, this would be treated with the same urgency as SIMD, and it would be finished in 2018. It's a serious and confusing language gap.

**Comment by aturon** [comment]
Thanks @aidanhs, I think this is overdue.

**Comment by Manishearth** [comment]
I think we should just modify them and say "XYZ issues cropped up during the experimental period, this RFC has been unaccepted" at the top somewhere.

**Comment by nikomatsakis** [comment]
Hmm so @Manishearth raises a good point. I think I am r+ on this change, but I would like to see a write-up summarizing some of the outstanding concerns that proved hard to resolve. I would be happy for this to be a comment on the tracking issue (which could then be closed), and/or added to the RFC. @aidanhs do you think you'd be up for gathering such a thing? It doesn't have to be a big thing, just some points so we don't start by scratching our heads and rediscovering constraints.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

I propose to **merge** this PR -- well, some variant of this PR. In particular, I propose that we accept @aidanhs's proposal and remove this feature for now (along with some kind of notes for the future on where the problems and open questions were).

**Comment by aturon** [comment]
@aidanhs I'd rather not go through a full round of RFC to litigate this particular process concern; I think the lang team should just reach a decision about how it wants to approach this issue in situ.

**Comment by nikomatsakis** [comment]
Let's discuss at @rust-lang/lang meeting today.

**Comment by nikomatsakis** [comment]
We discussed in the lang meeting today. Conclusion was that the procedure for "unapproving" ought to be that we:

- Pull together a summary comment, ideally with pointers to other conversations.
    - Probably -- even better -- this should really be done *before* kicking off FCP, but whatevs.
    - If possible, point to a place where ongoing discussion is happening. Probably there is no such place, though, so you might say, "If you are interested in rejuvenating the design, start a thread on internals".
- Post that comment on the tracking issue.
- Update various RFCs with a brief sentence like this:

```
This RFC was **unapproved**. For details, see [this comment][c].

[c]: ...
```

Those changes can be pushed directly to the RFC repo or merged without discussion. The decision is being made here, after all.

**Comment by glaebhoerl** [comment]
(Might be worth posting a link on the original RFC thread(s) and maybe advertising on internals too just in case.)

**Comment by nikomatsakis** [comment]
Actually, I quite like the idea of the internals thread -- we should also link it from the summary comment. That way, people might add extra stuff we forget in that thread.

**Comment by shepmaster** [comment]
Ping from triage, @aidanhs ! Looks like you have some merge conflicts. I also can't *quite* tell exactly what state this PR is in as it looks like you are blazing a new path...

**Comment by cramertj** [comment]
@shepmaster I think we're just waiting two more days for the FCP to complete.

**Comment by nikomatsakis** [comment]
r=me after rebase

**Comment by shepmaster** [comment]
Ping from triage, @aidanhs ! It looks like it's waiting on you for a rebase.

**Comment by aidanhs** [comment]
I'll find some time to do this next week, I'm mainly delayed on wanting to do the summary comment justice so it's informative for future readers!

**Comment by aidanhs** [comment]
I've appended my proposed summary comment below. Once this PR is r+ed (@nikomatsakis), I'll create the internals thread, create the comment on the tracking issue and create the RFCs PRs.

cc @alexcrichton

------------------

Placement new is imminently about to be/has been removed as an unstable feature and the RFCs unaccepted. The approved/merged PR is at https://github.com/rust-lang/rust/pull/48333. Note that this does *not* affect box syntax.

Find the internals thread where you can discuss this more at LINK-TODO. Please add any thoughts there.

So why remove placement?
========

The implementation does not fulfil the design goals
--------------

As described in rust-lang/rfcs#470 (referred to by the accepted rust-lang/rfcs#809), the implementation of placement new should

> Add user-defined placement `in` expression (more succinctly, "an `in` expression"), an operator analogous to "placement new" in C++. This provides a way for a user to specify (1.) how the backing storage for some datum should be allocated, (2.) that the allocation should be ordered before the evaluation of the datum, and (3.) that the datum should preferably be stored directly into the backing storage (rather than allocating temporary storage on the stack and then copying the datum from the stack into the backing storage).

The summarised goals (from the same RFC text) are to be able to:
1. Place an object at a specific address (references the original C++ goals)
2. Allocate objects in arenas (references the original C++ goals)
3. Be competitive with the implementation in C++

Now consider the description of C++ behaviour in https://isocpp.org/wiki/faq/dtors#placement-new and note that during construction, the `this` pointer will point to the allocated location, so that all fields are assigned directly to the allocated location. It follows that we must provide similar guarantees to achive goal 3 (be competitive with C++), so the "preferably" in the implementation description is not strong enough - it is actually necessary.

Unfortunately, [it is easy to show](https://play.rust-lang.org/?gist=0b250385a4a657f50cc8f6723eef5d2c&version=nightly) that rust does *not* construct objects directly into the allocation in debug mode. This is a very simple case that uses a struct literal rather than the very common Rust pattern of 'return value construction' (most `new` functions).

It appears that the current implementation cannot competitive with C++ placement as-is. A new RFC might either propose different guarantees, or describe how the implementation should work given the very different method of construction in Rust (compared to C++). Straw man: "A call to a `fn() -> T` can be satisfied by a `fn(&uninit T)` function of the same name (allowing you to assign fields directly in the function body via the uninit reference)".

The functionality of placement is unpredictable
--------------

As described by the C++ goals for placement (mentioned above), placement is typically used because you need to have explicit control over the location an object is put at. We saw above that Rust fails in very simple cases, but *even if it didn't* there is a more general issue - there is no feedback to the user whether placement is actually working. [For example](https://github.com/rust-lang/rust/issues/27779#issuecomment-358025344), there is no way for a user to tell that `linkedlist.back_place() <- [0u8; 10*1024*1024]` and `linkedlist.back_place() <- [[0u8; 10*1024*1024]]` are not both placed.

Effectively, placement as implemented today is a 'slightly-better-effort to place values than normal assignment'. For an API that aims to offer additional control, this unpredictability is a significant problem. A new RFC might provide either provide clear guidance and documentation on what placement is guaranteed, or require that compilation will fail if a requested placement cannot succeed. Straw man 1: "Placement only works for arrays of bytes. Function calls (e.g. serde or anything with fallible creation) and DSTs will not work". Straw man 2: "If a same-name `fn(&uninit T)` does not exist for the `fn() -> T` call being placed, compilation will fail".

Specific unresolved questions
--------------

There are a number of specific unresolved questions around the RFC(s), but there has been effectively no design work for about 2 years. These include (some already covered above):

 - making placement work for serde/with fallible creation [5], [irlo2], [7]
 - trait design:
   - opting into not consuming the placer in `Placer::make_place` - [2]
   - trait proliferation - [4] (+ others in that thread)
   - fallible allocation - [3], [4] (+ others in that thread)
 - support for DSTs/unsized structs (if at all) - [1], [6]

More speculative unresolved questions include:

 - better trait design with in the context of future language features [irlo1] (Q11), [irlo3]
 - interaction between custom allocators and placement [irlo3]

[0] https://github.com/rust-lang/rfcs/pull/470
[1] https://github.com/rust-lang/rfcs/pull/809#issuecomment-73910414
[2] https://github.com/rust-lang/rfcs/issues/1286
[3] https://github.com/rust-lang/rfcs/issues/1315
[4] https://github.com/rust-lang/rust/issues/27779#issuecomment-146711893
[5] https://github.com/rust-lang/rust/issues/27779#issuecomment-285562402
[6] https://github.com/rust-lang/rust/issues/27779#issuecomment-354464938
[7] https://github.com/rust-lang/rfcs/pull/1228#issuecomment-190825370
[irlo1] https://internals.rust-lang.org/t/placement-nwbi-faq-new-box-in-left-arrow/2789
[irlo2] https://internals.rust-lang.org/t/placement-nwbi-faq-new-box-in-left-arrow/2789/19
[irlo3] https://internals.rust-lang.org/t/lang-team-minutes-feature-status-report-placement-in-and-box/4646

I've opted to list these rather than going into detail, as they're generally covered comprehensively by the corresponding links. A future RFC might examine these points to identify areas to explictly address, including (in no particular order):
 - does the new RFC support DSTs? serde and fallible creation?
 - does the new RFC have a lot of traits? Is it justified?
 - can the new RFC handle cases where allocation fails? Does this align with wider language plans (if any) for fallible allocation?
 - are there upcoming/potential language features that could affect the design of the new RFC? e.g. custom allocators, NoMove, HKTs? What would the implications be?

**Comment by SimonSapin** [comment]
Oops, it looks like a PR of mine made this one unmergeable *twice* :( I’ve just force-pushed a rebase to your branch.

**Comment by SimonSapin** [comment]
@bors: p=1

This PR has already bitrotted a couple times, and I’m working on more changes that should go on top of this to avoid further conflicts.

**Pull request merged**
