### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #70566 (Don't bail out before linting in generic contexts.)
 - #70657 (Allow `try`-blocks in places where an open delim is expected)
 - #71002 (fix target & runtool args order)
 - #71100 (Miri: expand frame hooks)
 - #71128 (Remove unused single_step flag)
 - #71135 (Update books)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
I am pretty sure this will fail, PR CI failure looks legit and points at https://github.com/rust-lang/rust/pull/70566.

**Comment by Dylan-DPC** [comment]
Thanks. checking

**Comment by Dylan-DPC** [comment]
@bors r-

re-rolling

**Pull request closed without merging**
