### PR TITLE
Improve runtest output

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Actually, when a test fails, runtest prints ALL the errors he got and ALL the expected errors. When you only had 1 or 2 errors, it's quite easy to see what you forgot/didn't do correctly. However, when you have like 10 or more errors, it's just terrible.

This PR changes the output, now only not found expected errors and unexpected errors are displayed. Everything else is unneeded and so, isn't displayed.

**Comment by GuillaumeGomez** [comment]
original (yes, it took me a while to copy/paste):

```bash
actual errors (from JSON output): [
    Error {
        line_num: 18,
        kind: Some(
            Error
        ),
        msg: "18:42: 18:48: unknown meta item \'reason\' [E0541]"
    }
   // and every other errors
]

expected errors (from test file): [
    Error {
        line_num: 18,
        kind: Some(
            Error
        ),
        msg: "unknown meta item \'reason\'"
     }
     // and every other expected errors
]
```

new output:

```bash
unexpected errors (from JSON output): [
    Error {
        line_num: 77,
        kind: Some(
            Error
        ),
        msg: "77:3: 77:38: multiple stability levels [E0544]"
    }
]

not found errors (from test file): [
    Error {
        line_num: 78,
        kind: Some(
            Error
        ),
        msg: "multiple stability levels"
    }
]
```

Do you understand better? :)

**Comment by jonathandturner** [comment]
LGTM

**Pull request merged**
