### PR TITLE
Avoid translation of unreachable arms in lazy binops

### PR DESCRIPTION
**Pull request by dotdash**

### CODE REVIEW

**Comment by brson** [comment]
Can you add a one-line comment explaining what this early return is doing?

**Comment by brson** [comment]
I presume the idea here is to generate less IR since LLVM will figure this out on its own. Do you have a sense of how often this occurs in real code and what kind of savings it creates?

**Comment by dotdash** [comment]
I only noticed this when looking at the unoptimized IR for libsyntax, looking for `br i1 (false|true)`. A few dozen of those were from `with_cond` calls (fixed in an earlier PR), and a few hundred from from lazy binops. I don't know how representative that is or if it saves much in terms of compile time, but the places I looked at were rather hard to read due to the extra branches and basic blocks. The fact that some of them were inside matches didn't exactly help ;-)

**Comment by dotdash** [comment]
Looking through the IR for libsyntax again, most of these seem to originate from derived PartialEq implementations. Maybe "fixing" those is preferable?

**Comment by dotdash** [comment]
Compile times for libsyntax are unchanged. I'd be fine with dropping this and maybe fixing the deriving code at some point. In the meantime, I can easily locally apply this patch when I feel the need.

**Comment by dotdash** [comment]
Not worth the added complexity

**Pull request closed without merging**
