### PR TITLE
Move some tests to more reasonable directories

### PR DESCRIPTION
**Pull request by c410-f3r**
r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
issue-43784-supertrait.rs - no associated types involved there
issue-77993-1.rs - no async-await is involved there
issue-3563-2.rs - can be removed now
issue-3563-3.rs - "Demonstrates traits, impls, operator overloading, non-copyable struct, unit testing", not block-result
issue-5500-1.rs - never_type, i guess
issue-48962.rs - drop
issue-17718-* - the issue is so vague that it doesn't make sense to group tests according to it, imo, all the tests in non-`issues` subdirectories are already in good places
issue-17718-const-privacy.rs - privacy
issue-17718-patterns.rs - pattern
issue-17718-static-move.rs - borrowck
issue-17718-static-sync.rs -> statics
issue-17718-static-unsafe-interior.rs -> statics
issue-64620.rs - no generators involved there
issue-36053.rs - no mismatched types observed there, it's a run-pass test
issue-2718-a.rs - structs-enums or recursion
issue-23338-ensure-param-drop-order.rs - drop
issue-23338-params-outlive-temps-of-body.rs - borrowck
issue-24805-dropck-itemless.rs - dropck
issue-7575.rs - can be removed now

@rustbot author

**Comment by JohnCSimon** [comment]
@c410-f3r 
ping from triage - can you post your status on this PR and address the review comments? Thanks

**Comment by c410-f3r** [comment]
> @c410-f3r ping from triage - can you post your status on this PR and address the review comments? Thanks

I will in a few days. Just needed a little Rustc break

**Comment by c410-f3r** [comment]
@petrochenkov The intention here is to unify all scattered tests that are part of the same issue but it seems that some tests shouldn't be included in the same directory.

Closing in favour of #102055.

**Pull request closed without merging**
