### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by jieyouxu** [comment]
@matthiaskrgr I think #131808 is going to conflict with this one. Is it possible for clippy subtree bump to wait for #131808 then do a resync?

**Comment by flip1995** [comment]
I'll need a few days to get back to this. Probably until the weekend.

**Comment by flip1995** [comment]
Today is a new sync day. Closing in favor of the new sync, I'll open in a few minutes.

**Pull request closed without merging**
