### PR TITLE
Fix broken link to the rustc guide

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**

### CODE REVIEW

**Comment by mark-i-m** [comment]
Thanks! I would actually point to `https://rust-lang.github.io/rustc-guide/borrow_check.html` instead. "Region checking" is just jargon for "borrow checking", which is the subject of the whole chapter.

Also, I don't have r+ privileges. r? @JohnTitor or @spastorino

**Comment by Dylan-DPC** [comment]
Ouch sorry xD

**Comment by LeSeulArtichaut** [comment]
Edited the link

**Review by mark-i-m — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
