### PR TITLE
Make the symbol interner use thin string pointers

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by petrochenkov** [comment]
Ugh.
Is this really necessary? Are there performance numbers?

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by michaelwoerister** [comment]
Link: http://perf.rust-lang.org/compare.html?start=2b1d69d6b520046108dae04c625f15ea35127388&end=ac6940c9bdd6197a59b32bbd2a4cc8b169171cdd&stat=instructions%3Au

I'm not sure it's worth the complication.

**Pull request closed without merging**
