### PR TITLE
Add `Parser::reached_eof` utility method

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
I though this could be useful.

r? @matklad

### CODE REVIEW

**Comment by matklad** [comment]
LGTM, but let's

r? @petrochenkov 

to make sure

**Comment by petrochenkov** [comment]
I don't think this is useful unless there's are specific plan to change `reached_eof` to something other than `self.token == token::Eof` or change it often.

**Comment by matklad** [comment]
There are definitely no specific plans at the moment. Non-specific plan of parse-library-ification would *likely* (but not necessary) require us to better abstract the parser interface, and it's unlikely that we'll want to keep `.token` public. 

Ultimately, I don't have strong feelings one way or another here. It feels like a small step in the right direction, but, as nothing prevents using `.token == Eof`, it also increases inconsystensy of the codebase at the meantime.

**Comment by petrochenkov** [comment]
I'll go forward and close, now is not the time to do this.

**Pull request closed without merging**
