### PR TITLE
std: Cache HashMap keys in TLS

### LINKED ISSUE #27243: Make HashMap use a per-process or per-thread seed instead of a per-instance seed
Currently every call to HashMap::new makes a new RandomState that makes two new calls to the thread_rng to create its seed. This is, to my knowledge cryptographic overkill, as there is no clear distinction between a single HashMap with a seed and many HashMaps with the same seed, as long as that seed is not hardcoded (and therefore able to be attacked offline).

There is no argument to be had on minimizing the risk of a single compromise, as the SipHash security model is designed to make it impossible to compromise a single map. If our users disagree with this, we may consider exposing a constructor for RandomState that explicitly reseeds it.

This can be implemented via Once or through a Thread Local Static. Whichever is more efficient.

CC @alexcrichton

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a rebase and extension of #31356 where we not only cache the keys in
thread local storage but we also bump each key every time a new `HashMap` is
created. This should give us a nice speed bost in creating hash maps along with
retaining the property that all maps have a nondeterministic iteration order.

Closes #27243

### CODE REVIEW

**Comment by sfackler** [comment]
ping?

**Comment by briansmith** [comment]
Why is it safe to key different HashMaps with keys that are known to each differ by only 1?

**Comment by eternaleye** [comment]
briansmith: Because if it was not safe that would constitute a related-key attack, and none is known for SipHash?

**Comment by briansmith** [comment]
> briansmith: Because if it was not safe that would constitute a related-key attack, and none is known for SipHash?

1. The hash function isn't necessarily SipHash. It's pluggable per-hashmap and also the default may be changed.

2. I don't find "we don't currently know of a related-key attack on SipHash" very encouraging. There are lots of ways to derive N secret keys from an initial secret key that are fast and don't depend on the related-key-security of the hashing function.

**Comment by eternaleye** [comment]
@briansmith: Fair enough on both points - Not being assured of SipHash means that it may well be an issue, and I agree that the _margin_ of security even so is unnecessarily thin.

**Comment by sfackler** [comment]
This logic is only used by the SipHash hasher.

**Comment by aturon** [comment]
r=me on the code and perf front. But I don't feel qualified to judge the security/DDoS protection side of this.

**Comment by briansmith** [comment]
> But I don't feel qualified to judge the security/DDoS protection side of this.

Others have quoted this, but again, this is what the SipHash paper says:
> On startup a program reads a secret SipHash key from the operating system’s cryptographic random-number generator; the program then uses SipHash for all of its hash tables.

Thus, the easiest thing to do is what the SipHash authors recommend: Use `std::sync::Once` to generate one key using the `OsRng`, and then use that same key for every hash table.

Think about the threat model: We assume that the attacker can add or remove arbitrary (key, value) entries from any hash table used in the program. From this, it follows that we assume the attacker can change any hash table *A* into any other hash table *B* by removing all the items from *A* and then copying all the entries from *B* into *A*. Thus, it seems to not help if *A* or *B* have different keys, at least under this threat model. If you have a different threat model, it would be a good idea to document it.

More generally, crypto people never generate a secret key by adding a constant value to another secret key. See https://en.wikipedia.org/wiki/Related-key_attack for an introduction to why. tl;dr: Knowing the difference of two secrets can help an attacker find the value of one (usually both) secrets, even if they wouldn't be able to find the values any other way. Because no crypto people would do this, it is unlikely that somebody will seriously study the problems that may or may not occur when somebody does what is proposed in this PR because we generally assume it is a-priori wrong to do.

HTH.

**Comment by aturon** [comment]
@briansmith Thanks for the comment! That does indeed help highlight some of the tradeoffs here.

AIUI, the motivation for using these distinct (but related) keys is just to avoid clients of the default hashmap from accidentally assuming that all instances share a common key -- a behavior we could conceivably want to change in the future. But it could easily be that this cure is worse than the disease, and we'd be better off just very clearly documenting that you cannot rely on the apparent determinism. We just risk de facto lock-in to that behavior, but that seems (to me) better than taking a step that could easily end up revealing hashmap keys.

@rust-lang/libs Thoughts here?

**Comment by alexcrichton** [comment]
Yeah I'm not *too* worried about switching to a per-process key with the risk of relying on a per-process deterministic iteration order. It's just a "nice to have" to make everything nondeterministic really I think.

**Comment by huonw** [comment]
It seems to me that we could have this per-thread without the adjustment, but maybe having inter-thread differences isn't worth the slightly higher complexity vs. just being uniform through a process.

**Comment by aturon** [comment]
Per-thread sounds like a good compromise across the board. @alexcrichton, want to update accordingly?

**Comment by alexcrichton** [comment]
Sounds like a plan to me, I've updated the PR, the comment, and I also tweaked to use `OsRng` directly. The `thread_rng` isn't necesssary when we cache per-thread b/c we're gonna hit `OsRng` for the first time on each thread anyway.

**Comment by aturon** [comment]
Thanks!

@bors: r+

**Pull request merged**
