### PR TITLE
AtomicPtr without losing pointer provenance

### PR DESCRIPTION
**Pull request by RalfJung**
This came up while debugging why Miri kept reporting memory leaks on Windows. The leaked memory came from libstd static `sys:common::mutex::Mutex`. When such a mutex gets initialized, allocation happens (on Windows XP, which is also the code path that Miri uses), and then the pointer to that allocation is *cast to an integer* and stored in static memory. When doing leak checking, Miri cannot tell that there is a pointer here, it just sees an integer, and thus the memory that the integer "points to" is considered leaked.

The easiest fix would be to *transmute* the pointer to an integer instead of casting it. That avoids dropping the provenance which Miri uses to later do leak checking.

However, since this could happen with anyone handling pointers atomically, I wanted to use `AtomicPtr` instead -- which, as it turns out, internally also performed ptr-to-int casts, so I replaced those by transmutes.

Ideally we'd call `atomic_store` and friends at pointer type, but that leads to a codegen error:
```
error[E0511]: invalid monomorphization of `atomic_load` intrinsic: expected basic integer type, found `*mut ()`
    --> /home/r/src/rust/rustc.2/src/libcore/sync/atomic.rs:2277:19
     |
2277 |         SeqCst => intrinsics::atomic_load(dst),
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
If that codegen check can be relaxed to also accept pointers, we could avoid transmutes and casts entirely, but that goes beyond my LLVM knowledge.

(In principle whether or not provenance is dropped should also make a difference for optimizations in LLVM, but currently LLVM is buggy in that area and [does not make this distinction](https://bugs.llvm.org/show_bug.cgi?id=34548).)

### CODE REVIEW

**Comment by kennytm** [comment]
I think we should make `lock` a union of `c::SRWLOCK` and `AtomicPtr<ReentrantMutex>` to get rid of all those casting.

This in general LGTM, but I find that `ptr as usize` having subtly different behavior than `transmute(ptr): usize` is too easy to misuse, in particular `transmute()` does not mention that it preserves provenance.

**Comment by RalfJung** [comment]
> I find that ptr as usize having subtly different behavior than transmute(ptr): usize is too easy to misuse, in particular transmute() does not mention that it preserves provenance.

Well, transmute says it "reinterprets" the value and that it is "transmute is semantically equivalent to a bitwise move of one type into another".

The problem is that most people think a ptr-to-int cast also just reinterprets the value, but unfortunately, that is wrong. If anything we should adjust the docs for casts, whatever would be the right place for that. However, it also also hard to say anything precise here while LLVM is still full of bugs in this area.

**Comment by Aaron1011** [comment]
@RalfJung: If I understand correctly, this change is only about preventing false-positives in Miri's leak checker, right? That is, casting to an integer is fine correctness-wise?

If this is the case, then I'm concerned that Miri could run into this same issue on other projects. As @kennytm  pointed out, the `transmute` cast distinction seems extremely subtle, and does not seem to be clearly documented at the moment. I think it will be difficult to convince other projects to add `unsafe` code if the only purpose to avoid certain Miri false-positives, when using a cast is both safe and correct.

I have no objection to this PR itself, but I think it would be a good idea to make an issue on Miri about this.It make sense to for Miri to store some extra information during int-ptr casts to allow the leak checker to avoid false positives (though I'm not sure how difficult this would be).

**Comment by RalfJung** [comment]
> If I understand correctly, this change is only about preventing false-positives in Miri's leak checker, right? That is, casting to an integer is fine correctness-wise?

Well. The full answer [is complicated](https://people.mpi-sws.org/~jung/twinsem/twinsem.pdf). Casting and transmuting to an integer are *not* the same operation, and pretending that they are has lead to hard to fix and still outstanding bugs in multiple compilers:
* https://bugs.llvm.org/show_bug.cgi?id=34548
* https://bugs.llvm.org/show_bug.cgi?id=35229
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82282

So, while *right now* this is mainly about Miri, it *is* the case that it seems mighty odd that a type named `AtomicPtr` would internally lose the provenance of the pointers it is working with.

In fact, as the paper I linked above shows, using integers here (that carry pointer values, still with provenance) is not entirely free of problems either (there are some arithmetic optimizations on integers that go wrong if integers are allowed to actually be pointers). Really what we would want is to be able to atomically load and store pointers in memory without changing their type ever -- but LLVM's [`atomicrmw`](https://llvm.org/docs/LangRef.html#atomicrmw-instruction) only works with integer types, probably because LLVM devs thought of ptr-int-casts as NOPs, so they saw no need for truly ptr-typed atomic instructions.

> I have no objection to this PR itself, but I think it would be a good idea to open an issue on Miri. It might make sense for Miri to store some extra information during int-ptr casts to allow the leak checker to avoid false positives (though I'm not sure how difficult this would be).

That might work for some special cases like this one, at the expense of making the core Miri engine notably more complicated (as now there would be things that do not have provenance in the Abstract Machine, but *do* have provenance in Miri). For a case that is already harder than the one here, imagine that the program stored the pointer cast to an integer and with the last bit of the pointer (guaranteed to be zero due to alignment) used for storing some boolean flag. For more extreme cases, imagine the XOR of two pointers is stored together with one pointer (so the other can be restored by another XOR). Or maybe the program is using some clever packing scheme to fit more pointers into the same memory.

This is a never-ending game of whack-a-mole, which I am not sure is worth pursuing. I like having a clear specification for Miri's leak checker: it will consider pointers, but not integers, when checking which allocations are live. In that sense I lean towards calling this a "wontfix" issue on the Miri side, but could be convinced otherwise.

> If this is the case, then I'm concerned that Miri could run into this same issue on other projects.

Fair. I have several responses to that. First of all, even though Miri is already used on a dozen or more libraries for UB testing, as far as we know none had this particular problem so far. Secondly, if it becomes a problem for a library, it is legitimate to disable the leak check locally if they prefer that over adjusting their code to preserve provenance. And finally, the code this is patching here is somewhat special as it affects *every* program running on a Windows target.

**Comment by jonhoo** [comment]
I am very much in favor of mentioning this in the documentation _somewhere_, though I don't quite know where. Maybe in the nomicon too? We could, perhaps, even make it a clippy lint? As someone who does write a decent amount of unsafe code, I would be perfectly happy changing usize casts to transmutes if it helps tools that check for correctness, I just need to know that that's necessary in the first place!

**Comment by RalfJung** [comment]
I am honestly somewhat worried about promoting the "transmute to `usize`" approach too much, because at least some variants of solving the "type punning" problem [described in §8 of this paper](https://people.mpi-sws.org/~jung/twinsem/twinsem.pdf) actually involve making ptr-to-usize transmutes UB...

**Comment by RalfJung** [comment]
I am giving up on this approach for now. A better solution to enable leak checks on Windows might be to implement the modern RwLock APIs, that side-steps the issue.

Atomic pointer operations remain a problem independent of that, but maybe it's better to make Miri track provenance some more than to introduce `transmute`s in the code here.

**Pull request closed without merging**
