### PR TITLE
Misc fixes for configure

### PR DESCRIPTION
**Pull request by matwey**
Currently,
`./configure` at armv6 machines ends up with

```
configure: error: unknown CPU type: armv6l
```

`./configure` at armv7 machines **silently** produces build for armv6 (compatible, but suboptimal)

```
configure: CFG_BUILD            := arm-unknown-linux-gnueabihf
```

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Right now rustup has a similar block but also has this:

```

**Comment by alexcrichton** [comment]
Er, hit comment too soon, but rustup also has this:

```sh
# Detect armv7 but without the CPU features Rust needs in that build,
# and fall back to arm.
# See https://github.com/rust-lang-nursery/rustup.rs/issues/587.
if [ $_ostype = "unknown-linux-gnueabihf" -a $_cputype = armv7 ]; then
    if ensure grep '^Features' /proc/cpuinfo | grep -q -v neon; then
        # At least one processor does not have NEON.
        local _cputype=arm
    fi
fi
```

I wonder if that also needs to be included here? Could you also elaborate on the purpose of the PR in the description as well?

cc @brson

**Comment by matwey** [comment]
@alexcrichton I am not sure that your code snippet is necessary.

**Comment by alexcrichton** [comment]
Ah I erroneously thought that the armv7 Linux target enabled NEON, which we needed to specifically check for lack of support and go back to arm. Due to a recent PR, though, we no longer assume NEON on armv7, so this is fine.

@bors: r+

**Pull request merged**
