### PR TITLE
ci: introduce haiku x86_64 builder

### PR DESCRIPTION
**Pull request by jessicah**

### CODE REVIEW

**Comment by aidanhs** [comment]
Thanks for the PR! Would it be possible for you to move this new directory into the `disabled` folder to indicate that these aren't actually used by travis? We don't have capacity to add more builders at the moment.

**Comment by alexcrichton** [comment]
@jessicah any thoughts on @aidanhs's last comment?

**Comment by jessicah** [comment]
Sorry, just haven't gotten around to updating, been busy with other Haiku work. Should have time this weekend.

Are there ever going to be plans to enable some of the disabled CI? It seems this story hasn't changed in a long time.

**Comment by alexcrichton** [comment]
At this time we don't have a great story for turning on whole new builders, it ends up being quite a large investment on our end over time so there's more we need to work through to enable that.

**Comment by alexcrichton** [comment]
Looks like tidy may be failing?

**Comment by aidanhs** [comment]
It appears our tidy checker is a bit overzealous, and detects any file marked as executable and without a .sh or .py extension to be a binary checked into git :(

I don't mind how you solve this (adding a .sh, chmod +x in the dockerfile) but travis won't let this pass as-is unfortunately.

**Comment by jessicah** [comment]
It gets renamed in `COPY` in `Dockerfile` anyway, so adding .sh is fine.

**Pull request merged**
