### PR TITLE
Add hashmap! + hashset! macros

### PR DESCRIPTION
**Pull request by 0x1F339**
These macros let you make HashMaps and HashSets filled w/ items in 1 pass much like vec!. They can also be used as a slightly shorter alternative to HashMap::new()/HashSet::new() for empty HashMaps/HashSets

HashMap!'s syntax's meant to be similar to using the insert method:
```Rust
let mut book_reviews = HashMap::new();
book_reviews.insert("Adventures of Huckleberry Finn", "My favorite book.");
book_reviews.insert("Grimms' Fairy Tales", "Masterpiece.");
let mut book_reviews = hashmap![("Adventures of Huckleberry Finn", "My favorite book."), ("Grimms' Fairy Tales", "Masterpiece.")];
```
No feature gates coz apparently feature gates don't work for macros
Issues: these macros're available even when HashMap/HashSet ain't in scope, tho I ain't sure how much of a problem that is in practice since I imagine people'll type `use std::collections::HashMap` 1st

```Rust
fn main() {
    let map = hashmap![("test", 1)];
}
```
```
error[E0433]: failed to resolve. Use of undeclared type or module `HashMap`
 --> src/main.rs:2:15
  |
2 |     let map = hashmap![("test", 1)];
  |               ^^^^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `HashMap`
  |
```
Maybe add HashMap and HashSet to the prelude but I don't think that's likely

### CODE REVIEW

**Comment by cool-cool-sweat** [comment]
Maybe this should be in an RFC?

**Comment by udoprog** [comment]
Hey @cool-cool-sweat, this looks really neat!

This feature is already present in an active RFC. You might want to look through it to see if it meets your needs, and possibly make your voice heard there: https://github.com/rust-lang/rfcs/issues/542

**Comment by cool-cool-sweat** [comment]
I'm gonna close this in favour of the pull request I've made against maplit

**Comment by cup** [comment]
https://github.com/rust-lang/rfcs/issues/1420
https://github.com/rust-lang/rfcs/issues/1602
https://github.com/rust-lang/rfcs/issues/542
https://github.com/rust-lang/rfcs/pull/207
https://github.com/rust-lang/rust/issues/14726

https://github.com/rust-lang/rust/pull/48937

**Pull request closed without merging**
