### PR TITLE
visit enum init when the enum variable doesn't have any parameters

### LINKED ISSUE #101208: Provide suggestion for error when `if let` used with enum variant whose values are not initialized
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ac515a35cf754b067d63ab16f3917383)

```rust
enum E {
    One(i32, i32)
}

fn main() {
    let var = E::One;
    if let E::One(var1, var2) = var {
        println!("{var1} {var2}");
    }
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:7:12
  |
7 |     if let E::One(var1, var2) = var {
  |            ^^^^^^^^^^^^^^^^^^   --- this expression has type `fn(i32, i32) -> E {E::One}`
  |            |
  |            expected fn item, found enum `E`
  |
  = note: expected fn item `fn(i32, i32) -> E {E::One}`
                found enum `E`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Ideally the output should suggest to the user that they need to initialize the enum variant's value in order to use the `if let`.

### PR DESCRIPTION
**Pull request by lyming2007**
this will fix #101208

### CODE REVIEW

**Comment by compiler-errors** [comment]
Is this a duplicate of #102062? Which one of these is the preferred fix?

**Comment by compiler-errors** [comment]
As I noted on #102062, I feel like this logic overlaps very heavily with `FnCtxt::suggest_fn_call` -- is it possible to use that instead?

**Comment by lyming2007** [comment]
> As I noted on #102062, I feel like this logic overlaps very heavily with `FnCtxt::suggest_fn_call` -- is it possible to use that instead?

There is no respond for #102062 since a long time ago. 
And I found we don't need to modify the file compiler/rustc_span/src/span_encoding.rs which caused the conflict.
So this one(#102984) is actually a more less expensive fix.
That's why I've created a new one.

**Comment by compiler-errors** [comment]
@lyming2007 in the future, you can just update the PR with a new approach. If it has been a long time since it was reviewed, then please ping the reviewer.

I will close the older one since they achieve the same purpose.

**Comment by lyming2007** [comment]
> @lyming2007 in the future, you can just update the older PR with a new approach. If it has been a long time since it was reviewed, then please ping the reviewer.
> 
> I will close the older one since they achieve the same purpose.

Thank you for the suggestion. I will do that in the future

**Comment by compiler-errors** [comment]
@lyming2007 you did the rebase incorrectly. I think you need to do:

```
git pull --rebase $ORIGIN master
```

where `$ORIGIN` is whatever `git remote` that is set up to track `rust-lang/rust`.

**Comment by lyming2007** [comment]
> 



> @lyming2007 you did the rebase incorrectly. I think you need to do:
> 
> ```
> git pull --rebase $ORIGIN master
> ```
> 
> where `$ORIGIN` is whatever `git remote` that is set up to track `rust-lang/rust`.
When I tried to merge the code, it keeps asking me to fix the conflict of Cargo.lock which I nerve touched before.
Seems it's much easier to create a new PR than doing the merge.
Can I create a new one and abandon the current one? 
I will do as you suggested later

**Comment by lyming2007** [comment]
this PR was broken by me obviously

**Pull request closed without merging**
