### PR TITLE
Remove build date from the output of --version

### LINKED ISSUE #25812: Remove build date from --version
I added this some months ago because I thought it would help stem confusion about the reported commit date when it happens to be a few days behind the release artifacts. I no longer think this is a great idea for two reasons:

1) This date is not guaranteed to be the same across platforms. There have been occasions when the builds were spread across multiple days. Because these strings are not guaranteed to be the same one can't compare the output of two `rustc --version` invocations to check for equivalence, which is something I have wanted to do (I think one of my tools has to frob this string to eliminate the build date). Fixing this would require more complexity in the buildbot config than I'm comfortable with atm.

2) The commit date for nightlies should never actually be more than 1-2 days behind the distribution date since the head commit is always a merge commit. The original motivation for adding the build date may not have been very strong.

### PR DESCRIPTION
**Pull request by jooert**
Closes #25812.

### CODE REVIEW

**Comment by brson** [comment]
Nominating for beta because this breaks parsing of `rustc --version` so better to do it quickly.

**Comment by alexcrichton** [comment]
cc @rust-lang/tools 

I agree this should be backported

**Comment by alexcrichton** [comment]
Accepting for the backport

**Pull request merged**
