### PR TITLE
Inline `evaluate_obligation` instead of going through the query system

### PR DESCRIPTION
**Pull request by jyn514**
There are several reasons I changed this:

- `evaluate_obligation` is only used in one place in
  `rustc_trait_selection`, and in fact warns you against using it
  anywhere else.
- ~~The implementation in `rustc_traits` was considerably more complicated
  than necessary, because it didn't have the context available in
  `rustc_trait_selection`.~~ I think I just didn't understand how it worked.
- It allows moving OverflowError into rustc_trait_selection, making
  https://github.com/rust-lang/rust/issues/81091 simpler (in particular,
  it allows holding an `Obligation` in OverflowError, which is only
  defined in `rustc_infer` and not available in rustc_middle).

The only reason to keep the previous behavior is if the cache from the
query system made it significantly faster.

### CODE REVIEW

**Comment by jyn514** [comment]
Hmm, I'm not sure why *removing* caching causes this test to fail:
```
failures:

---- [ui] ui/traits/cycle-cache-err-60010.rs stdout ----

error: ui test compiled successfully!
```
https://github.com/rust-lang/rust/blob/4253153db205251f72ea4493687a31e04a2a8ca0/src/test/ui/traits/cycle-cache-err-60010.rs#L67-L70

**Comment by Aaron1011** [comment]
I suspect that the test failure us due to the removed query canonicalization.

**Comment by jyn514** [comment]
> I suspect that the test failure us due to the removed query canonicalization.

Yup, I changed it to have the old code and the test passes now. I'm still confused why the cycle test is now failing, though.

**Comment by jyn514** [comment]
I don't know how to fix the test suite and it sounds like this won't be very useful.

**Pull request closed without merging**
