### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Successful merges:

 - #67112 (Refactor expression parsing thoroughly)
 - #67192 (Various const eval and pattern matching ICE fixes)
 - #67287 (typeck: note other end-point when checking range pats)
 - #67459 (prune ill-conceived BTreeMap iter_mut assertion and test its mutability)
 - #67576 (reuse `capacity` variable in slice::repeat)
 - #67602 (Use issue = "none" instead of "0" in intrinsics)
 - #67614 (Set callbacks globally)
 - #67617 (Remove `compiler_builtins_lib` documentation)
 - #67629 (Remove redundant link texts)
 - #67632 (Convert collapsed to shortcut reference links)
 - #67633 (Update .mailmap)
 - #67635 (Document safety of Path casting)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by xfix** [comment]
```
warning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `regex-syntax v0.6.6` within 30s)
```

retry?

**Comment by Centril** [comment]
No, do not retry.

**Comment by Mark-Simulacrum** [comment]
That's in the PR builder which ultimately doesn't matter AFAICT.

**Comment by xfix** [comment]
#67287 causes a conflict.

**Pull request closed without merging**
