### PR TITLE
Update Cargo and its dependencies

### PR DESCRIPTION
**Pull request by alexcrichton**
Just a routine update!

### CODE REVIEW

**Comment by kennytm** [comment]
A test in cargo failed, looks legit.

```
[01:09:13] ---- bad_git_dependency stdout ----
[01:09:13] 	running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build -v`
[01:09:13] thread 'bad_git_dependency' panicked at '
[01:09:13] Expected: execs
[01:09:13]     but: differences:
[01:09:13]  10 - |  [[..]] 'file:///' is not a valid local file URI|
[01:09:13]     + |  'file:///' is not a valid local file URI; class=Config (7)|
[01:09:13] 
[01:09:13] 
[01:09:13] other output:
[01:09:13] ``', /cargo/registry/src/github.com-1ecc6299db9ec823/hamcrest-0.1.1/src/core.rs:31:12
[01:09:13] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:09:13] 
[01:09:13] 
[01:09:13] failures:
[01:09:13]     bad_git_dependency
[01:09:13] 
[01:09:13] test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by kennytm** [comment]
This has broken several RLS tests (cc @nrc)? Not sure if legit. 

```
[01:12:17] ---- test::test_find_all_refs stdout ----
...
[01:12:17] thread 'test::test_find_all_refs' panicked at 'Could not find `{"start":{"line":9,"character":7},"end":{"line":9,"character":10}}` in `{"jsonrpc":"2.0","id":42,"result":[]}`', /checkout/src/libcore/option.rs:891:4
[01:12:17] 
[01:12:17] ---- test::test_find_all_refs_no_cfg_test stdout ----
...
[01:12:17] thread 'test::test_find_all_refs_no_cfg_test' panicked at 'Could not find `{"start":{"line":9,"character":7},"end":{"line":9,"character":10}}` in `{"jsonrpc":"2.0","id":42,"result":[]}`', /checkout/src/libcore/option.rs:891:4
...
[01:12:17] failures:
[01:12:17]     test::test_borrow_error
[01:12:17]     test::test_features
[01:12:17]     test::test_find_all_refs
[01:12:17]     test::test_find_all_refs_no_cfg_test
[01:12:17]     test::test_find_impls
[01:12:17]     test::test_goto_def
[01:12:17]     test::test_highlight
[01:12:17]     test::test_hover
[01:12:17]     test::test_infer_bin
[01:12:17]     test::test_infer_custom_bin
[01:12:17]     test::test_infer_lib
[01:12:17]     test::test_multiple_binaries
[01:12:17]     test::test_no_default_features
[01:12:17]     test::test_parse_error_on_malformed_input
[01:12:17]     test::test_rename
[01:12:17]     test::test_workspace_symbol
[01:12:17] 
[01:12:17] test result: FAILED. 11 passed; 16 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by alexcrichton** [comment]
@bors: r+

*prays it's spurious*

**Comment by nrc** [comment]
This doesn't look spurious to me. I updated Cargo locally and get the same failures in the RLS. The pattern of failure is what happens when no compilation happens. Probably something changed in the Cargo API which is screwing up the RLS, but nothing in Cargo's commit log looks suspicious.

**Comment by alexcrichton** [comment]
@nrc can you help me debug this? I spent a few hours yesterday tracing through rls tests and the rls iteslf (I found the output quite difficult to debug) and I even reverted Cargo back to the original revision and still got the same error.

The few commits landing in Cargo have what I would presume as minor changes. There's some minor tweaks but I can't make heads or tails of anything in the rls logs and/or internals as to what's actually changing or where the error is coming from.

**Comment by nrc** [comment]
Yep, looking into it now.

**Comment by nrc** [comment]
@alexcrichton 

The problem seems to be the way that Cargo is passing the file to compile to rustc. For the RLS tests the working directory is `rls`, the test file being compiled is `rls/tests/common/src/main.rs`. The manifest directory is `rls/tests/common`. Old Cargo is passing `tests/common/src/main.rs` to rustc (i.e., relative to the working directory) new Cargo is passing `src/main.rs` (i.e., relative to the manifest direct

I think Git bisect gives the problem-causing PR as https://github.com/rust-lang/cargo/pull/4788, but I might have misunderstood the output since one of the commits doesn't compile by itself (and I don't use `git bisect` very often).

I couldn't work out from the PR diff how things have changed, sorry. If it helps, we pass the working directory to Cargo here: https://github.com/rust-lang-nursery/rls/blob/master/src/build/cargo.rs#L605

**Comment by alexcrichton** [comment]
@nrc thanks for tracking that down!

Do you know how we might fix that? That PR does indeed change the paths passed to rustc to be workspace-relative instead of cwd relative (for more determinism and such). Additionally, how were you able to diagnose that? I wasn't able to ever reach such a conclusion poring over the various logs rls was generating :(

**Comment by nrc** [comment]
How I diagnosed - the key bit was there is a `trace!` log in rustc.rs which dumps all the arguments to rustc and env vars - that's a good place to look when there are problems between Cargo and rustc - I did take a while working out that there wasn't a problem in calling Cargo though.

How to solve it? I'm not sure how this is meant to work in the non-RLS case - how can you pass a workspace-relative path to rustc and have rustc run the right thing? Do you also change the CWD? Or do you pass extra info to rustc somehow? I think I can change the RLS to do exactly what Cargo would do otherwise, but I'm not clear on what that ought to be.

**Comment by alexcrichton** [comment]
@nrc ok cool that makes sense. Yeah Cargo changes the cwd of the rustc for relative paths (setting cwd to always be a workspace root). Cargo's logic [is here](https://github.com/rust-lang/cargo/blob/fac7e2559a5ceebcf3e710e2076f9ca3df9ab465/src/cargo/ops/cargo_rustc/mod.rs#L713-L735), but if you could point me to a place in the rls I wouldn't mind trying my hand at fixing the rls!

I tried checking the rls out locally and `cargo +nightly test` raised a SIGILL though so I didn't get too far debugging that earlier :(

**Comment by nrc** [comment]
I think we should not set the working directory in the RLS - we've had so many problems doing this in the past (because everything is done in one process, it is global mutable state). It should be easy enough to adjust the path though. I think we would do that in cargo.rs where we get the data back from Cargo and then save information for running rustc later.

**Comment by nrc** [comment]
I fixed the SIGILL issue - needed an update to a few deps

**Comment by alexcrichton** [comment]
I've [sent a PR](https://github.com/rust-lang-nursery/rls/pull/635) to update the RLS, thanks for your help @nrc!

**Comment by kennytm** [comment]
@bors retry

Hoping to be spurious.

```
[01:15:44] test failed_submodule_checkout has been running for over 60 seconds

No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by kennytm** [comment]
Same error, not going to retry. Something changed in libgit2 caused the test to be stuck?

The test case: https://github.com/rust-lang/cargo/blob/fac7e2559a5ceebcf3e710e2076f9ca3df9ab465/tests/git.rs#L2183

**Comment by alexcrichton** [comment]
Ok I've debugged this to something unrelated (the debugging stuff I added to the test didn't help). It's an issue with using the bundled libcurl, still investigating...

**Pull request merged**
