### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/rust/actions/runs/4712066890#summary-12779316921

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/rust/actions/runs/4712067124#summary-12779317247

### CODE REVIEW

**Comment by fee1-dead** [comment]
This PR is pretty big.. Would it be easy to split these changes into smaller PRs?

**Comment by Nilstrieb** [comment]
You should also squash the commits afterward the splitting up (the best way to split it up is probably after specific areas (compiler, library, rustdoc etc). With the tests you should be careful and maybe avoid them for now to not accidentally make the test wrong. Changes to rustc_codegen_gcc, rustc_codegen_cranelift, clippy, cargo and rustfmt should be filed on their respective repositories instead of here.

**Comment by compiler-errors** [comment]
There are several problems with this PR:

1. First of all, it's somewhat disruptive to the github history and to reviewability that this is broken into one commit per word. Even if we were to review this, it's much easier to break this into smaller PRs centered around fixing certain areas of the codebase (e.g. per crate in `compiler/`, fixing typos in `rustdoc`, libstd docs, etc.).
2. Secondly, this touches crates that are "in limbo" and other sources that really shouldn't be modified in tree unless for a good reason. For example, `rustc-apfloat` shouldn't be modified. Nor is it a good idea to touch tools that have their own repos, like `src/tools/rustfmt`.
3. Third, it's not very valuable IMO to be "fixing" UI tests. Those are test data, it doesn't matter if they have small typos in them. From a quick glance, a lot of the fixes are to those...

Per #58619 and precedent for large "typo fixes" PRs, I'm going to close this. Thanks for your contribution to rustc.

**Comment by fee1-dead** [comment]
> it's not very valuable IMO to be "fixing" UI tests.

I assume that typo fixing was automated using a tool, so I'd have no problem with typos being fixed for ui tests. I totally agree that it should be split into different subfolders only (`compiler/*`, `library/*`)

On another note, we can have bors squash the commits before merging so having each commit for each word is not a really big problem.

**Comment by jsoref** [comment]
* I split off the components that were listed as subtrees (https://github.com/rust-lang/miri/pull/2843, https://github.com/rust-lang/rust-analyzer/pull/14577, https://github.com/rust-lang/rustfmt/pull/5753#partial-pull-merging, https://github.com/rust-lang/rust-clippy/pull/10649)
  * I tried to peel off rustfmt and friends, apparently when I did my last round of rebasing/fixups some slipped in.

* I'm happy to split things in whichever means people like -- I just need input
* I'm happy to squash, but only once people are ok w/ the changes -- if I had squashed eagerly, it'd have been unusable (I rely on unsquashed changes to enable me to drop / fix up items, or while rebasing to deal w/ conflicts)
* sorry for not commenting sooner, I'm still working on annotating the PR. I can either flush that or discard it.
* I'm quite happy to let bors do the squashing

* I assume that typo fixing was automated using a tool -- sort of: an automated tool identifies possible issues. A human (that's me) manually applies changes and I try to make sure that I apply them to everything (while also trying not to apply them to things I've decided to exclude)

**Review by jsoref — COMMENTED** [review]
I won't finish the annotations, but here's what I had when I stopped...

**Comment by workingjubilee** [comment]
Sorry, we cannot actually rely on bors to do squashing.

**Comment by jsoref** [comment]
I'm quite happy to do the squashing, can someone suggest a limited subset of directories they'd like me to start w/?

I'm fully capable of doing splits and squashes, but I do need direction. 

If there's a specific set of directories I should absolutely ignore, I can take that now and drop changes to them.

**Comment by Nilstrieb** [comment]
rustc_apfloat needs to be ignored. I'd recommend splitting as I described above. You can `r? Nilstrieb` on the compiler PR.

**Comment by fee1-dead** [comment]
> Sorry, we cannot actually rely on bors to do squashing.

Yeah.. sorry for forgetting about that.

**Pull request closed without merging**
