### PR TITLE
remove allow(incomplete_features) from std

### PR DESCRIPTION
**Pull request by lcnr**
cc https://github.com/rust-lang/rust/pull/80349#issuecomment-753357123

> Now I am somewhat concerned that the standard library uses some of these features...

I think it is theoretically ok to use incomplete features in the standard library or the compiler if we know that there is an already working subset and we explicitly document what we have to be careful about. Though at that point it is probably better to try and split the incomplete feature into two separate ones, similar to `min_specialization`.

Will be interesting once `feature(const_evaluatable_checked)` works well enough to imo be used in the compiler but not yet well enough to be removed from `INCOMPLETE_FEATURES`.

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
Ah, this is great, thanks. :)
@bors r+

Do you know if the one in `library/stdarch/crates/core_arch/src/lib.rs` can also be removed?

**Comment by lcnr** [comment]
i think we can also remove in stdarch :laughing: didn't want to touch a subrepo though

**Comment by lcnr** [comment]
looks spurious to me

@bors r=RalfJung rollup

**Pull request merged**
