### PR TITLE
Update raw_vec.rs

### PR DESCRIPTION
**Pull request by ankushT369**
Optimize capacity doubling by replacing multiplication with bitwise shift

### CODE REVIEW

**Comment by workingjubilee** [comment]
@ankushT369 This optimization is performed at compile time, you realize.

**Comment by ankushT369** [comment]
Isn't it faster than just using multiplication operator?

**Comment by workingjubilee** [comment]
@ankushT369 "This optimization is performed at compile time" means "This optimization is performed at compile time". i.e. optimizing compilers are real.

Here: https://rust.godbolt.org/z/oW35T8jzc

You will notice that the Rust compiler, even on the lowest optimization level, has transformed these two functions into the same machine code.

**Comment by workingjubilee** [comment]
As this change will have no practical effect, I am closing this PR.

**Pull request closed without merging**
