### PR TITLE
derive: use intrinsics::unreachable over unreachable!()

### LINKED ISSUE #31574: Cannot derrive Clone for empty enums when using no_std
derriving clone on an empty enum does not work without std, because it calls `core::rt::begin_unwind`:

    #![no_std]
    
    #[derive(Copy, Clone)]
    enum MyEnum { }

leads to:

    <anon>:4:16: 4:21 error: failed to resolve. Could not find `rt` in `core` [E0433]
    <anon>:4 #[derive(Copy, Clone)]
                            ^~~~~
    <anon>:4:16: 4:21 note: in this expansion of #[derive_Clone] (defined in <anon>)
    <anon>:4:16: 4:21 help: see the detailed explanation for E0433
    <anon>:4:16: 4:21 error: unresolved name `core::rt::begin_unwind` [E0425]
    <anon>:4 #[derive(Copy, Clone)]
                            ^~~~~
    <anon>:4:16: 4:21 note: in this expansion of #[derive_Clone] (defined in <anon>)
    <anon>:4:16: 4:21 help: see the detailed explanation for E0425
    error: main function not found
    error: aborting due to 3 previous errors

Playground: https://play.rust-lang.org/?gist=7f786db03eca51a39900&version=nightly

### PR DESCRIPTION
**Pull request by durka**
derive: use intrinsics::unreachable over unreachable!()

Fixes #31574.

Spawned from #32139.

r? @alexcrichton

### CODE REVIEW

**Comment by durka** [comment]
The commit from #32139 that factors out the construction of `intrinsics::unreachable()` depends on both this PR and #32252 so it will have to wait.

**Comment by alexcrichton** [comment]
This passed in bors but I'm messing with the configuration so it didn't realize it, so merging manually.

**Comment by ubsan** [comment]
yay!

**Pull request merged**
