### PR TITLE
Manually order `DefId` on 64-bit big-endian

### PR DESCRIPTION
**Pull request by cuviper**
`DefId` uses different field orders on 64-bit big-endian vs. others, in
order to optimize its `Hash` implementation. However, that also made it
derive different lexical ordering for `PartialOrd` and `Ord`. That
caused spurious differences wherever `DefId`s are sorted, like the
candidate sources list in `report_method_error`.

Now we manually implement `PartialOrd` and `Ord` on 64-bit big-endian to
match the same lexical ordering as other targets, fixing at least one
test, `src/test/ui/methods/method-ambig-two-traits-cross-crate.rs`.

### CODE REVIEW

**Comment by cjgillot** [comment]
Relying on the `DefId` ordering is a source of incr-comp bug.  It would be more interesting to remove this dependency and make the test rely on some other order, like the one of source code, or of spans.

**Comment by cuviper** [comment]
Are there any plans to remove `DefID` ordering altogether? Because this PR is just making the status quo more consistent.

**Comment by cuviper** [comment]
OK, well that looks like a huge effort, but it can easily drop the changes I'm making here when that goes through.

> It would be more interesting to remove this dependency and make the test rely on some other order, like the one of source code, or of spans.

As for this, I think the test doesn't *really* care about order at all, just that it needs to be reproducible enough for UI to match. I can look at other more-stable options.

**Pull request merged**
