### PR TITLE
Minor improvements to -Zprofile

### PR DESCRIPTION
**Pull request by Amanieu**
- `-Zprofile` is broken with codegen units because GCOV assumes that each source file corresponds to one object file. This PR makes `-Zprofile` automatically set codegen units to 1 and gives an error if `-Ccodegen-units=X` is specified on the command line (with `X != 1`).
- The `profiler_builtins` crate is not suitable for `no_std` applications since it contains C code that depends on libc. In such cases a custom implementation of the LLVM gcov API (`llvm_gcov_init`, `llvm_gcda_*`) is needed. This PR adds `-Zno-profiler-runtime` flag which inhibits automatic injection of the `profiler_builtins` crate.

cc @whitequark who implemented the original `-Zprofile` support

### CODE REVIEW

**Review by whitequark — APPROVED** [review]
LGTM, and good catch!

**Review by davidtwco — APPROVED** [review]
r=me when CI passes

**Comment by Amanieu** [comment]
Just published [`minicov`](https://crates.io/crates/minicov) which uses this to support code coverage for `no_std`.

**Comment by whitequark** [comment]
@Amanieu Excellent work!

**Pull request merged**
