### PR TITLE
(do not merge) perf.rlo run for v0 symbol mangling

### PR DESCRIPTION
**Pull request by michaelwoerister**
Let's see if we can get perf.rlo results in time for the compiler team steering meeting today.

r? @ghost

### CODE REVIEW

**Comment by lqd** [comment]
In case fresh results are not ready by then, a run was done in november https://github.com/rust-lang/rust/pull/104698#issuecomment-1323020703

**Comment by michaelwoerister** [comment]
Thanks, @lqd - that will be a good fallback!

**Comment by michaelwoerister** [comment]
Results seem to be roughly in line with the [run from last year](https://github.com/rust-lang/rust/pull/104698#issuecomment-1323020703).

**Pull request closed without merging**
