### PR TITLE
Update rustfmt

### LINKED ISSUE #87363: cargo fmt fails with error "Invalid value for `--edition`"
I tried this code:

```rust
cargo fmt
```

I expected to see this happen: *Nothing, but format code*

Instead, this happened: *Invalid value for `--edition`*

I tried this with the following repository: https://github.com/datafuselabs/datafuse

see the CI result: https://github.com/datafuselabs/datafuse/pull/1159/checks?check_run_id=3132249396#step:6:9

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (b41936b92 2021-07-20)
binary: rustc
commit-hash: b41936b92cd8463020207cb2f62a4247942ef2e4
commit-date: 2021-07-20
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by PsiACE**
Closes #87363 

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by calebcartwright** [comment]
We should really do a push of the subtree to the rustfmt repo first before trying to do a pull here

**Comment by PsiACE** [comment]
> We should really do a push of the subtree to the rustfmt repo first before trying to do a pull here

Thanks for your suggestions, what should I do? I am a rookie and I not familiar with related operations.

**Comment by calebcartwright** [comment]
> > We should really do a push of the subtree to the rustfmt repo first before trying to do a pull here
> 
> Thanks for your suggestions, what should I do? I am a rookie and I not familiar with related operations.

No worries. For reference, the process for subtree updates is documented [here](https://rustc-dev-guide.rust-lang.org/contributing.html#synchronizing-a-subtree) in the rustc dev guide.

However, the rustfmt subtree is really out of sorts at the moment and that's reflected in the commit set on this PR (e.g. d67f1a48efbcdc689c69b6218ec55b541ebf8c7a shouldn't be here given 079d1c403feb03ce48191bccbb17143faea17bb8). I think I know what caused this divergence and it's something that'll require updates in the rustfmt repo first prior to a subtree push and pull flow.

As such I'd suggest this PR be closed

**Comment by Mark-Simulacrum** [comment]
Closing -- we can file a new PR as needed, of course (likely best to r? @calebcartwright on rustfmt subtree bumps in the future, btw).

**Pull request closed without merging**
