### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #66881 (Optimize Ord trait implementation for bool)
 - #67015 (Fix constant propagation for scalar pairs)
 - #67074 (Add options to --extern flag.)
 - #67164 (Ensure that panicking in constants eventually errors)
 - #67174 (Remove `checked_add` in `Layout::repeat`)
 - #67205 (Make `publish_toolstate.sh` executable)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by eddyb** [comment]
Before I forget about it, I think something in this rollup caused [a noticeable regression](https://perf.rust-lang.org/compare.html?start=7dbfb0a8ca4ab74ee3111e57a024f9e6257ce37c&end=033662dfbca088937b9cdfd3d9584015b5e375b2&stat=instructions:u).
My initial guess was #67015, but it might not be that, according to https://github.com/rust-lang/rust/pull/67015#issuecomment-565058210.

cc @rust-lang/wg-compiler-performance

**Comment by nikomatsakis** [comment]
Should we file an issue to track that ?

**Comment by nnethercote** [comment]
@oli-obk: Could #67164 have caused the regression?

@krishna-veerareddy: Could #66881 have cause the regression?

@ehuss: Could #67074 have caused the regression?

#67174 and #67205 seem very unlikely to be the cause.

I just tried to work out which commit caused the problem but failed; every revision I tried (even blatantly pre-merge ones) had the same post-regression numbers on `ctfe-stress-4`. Not sure what I'm doing wrong.

**Comment by krishna-veerareddy** [comment]
@nnethercote Hey sorry for the late response. It's unlikely that 66881 could have caused a regression since it has to do with boolean comparision which isn't used quite often and if anything the fix should have reduced the instruction count but I could be wrong. Is this still an unresolved issue?

**Comment by oli-obk** [comment]
It could have been caused by #67164 since we now produce some code for dead code that would otherwise never have been emitted to MIR. We can likely fix this via https://github.com/rust-lang/rust/issues/67191 because then we can revert the commit.

**Pull request merged**
