### PR TITLE
Subtree update of `rust-analyzer`

### PR DESCRIPTION
**Pull request by lnicola**
r? ghost

### CODE REVIEW

**Comment by fmease** [comment]
> rust-analyzer is developed in its own repository. If possible, consider making this change to [rust-lang/rust-analyzer] instead.

We could add `exclude_titles = ["subtree sync "]` to this trigger.

**Comment by lnicola** [comment]
The error location seems wrong, but it doesn't seem to recognize my new key.

**Comment by klensy** [comment]
For r-a:
```
tidy error: invalid license `Apache-2.0 WITH LLVM-exception` in `rustc_apfloat 0.2.0+llvm-462a31f5a5ab (registry+https://github.com/rust-lang/crates.io-index)`
```

**Comment by lnicola** [comment]
Asked about triagebot in https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/triagebot.20exclusions. I'll just revert that commit for now.

**Comment by lnicola** [comment]
@bors p=1

But I guess I'll wait for approval for the license change.

**Comment by klensy** [comment]
r- ? For some reason still `waiting-on-bors`

**Comment by lnicola** [comment]
@bors r-

I pushed a couple of commits, I don't think bors still merge it, but let's clear the label.

**Comment by mu001999** [comment]
@lnicola hi, can you r+? I hope #118257 can land in 1.77 (will branch from master on 2 February), and it depends on this PR.

**Comment by lnicola** [comment]
I'd like to, but there's a trivial change to the license list and I'm not sure I'm supposed to self-approve that.

**Comment by lnicola** [comment]
Sigh, "better to ask forgiveness" or something. That crate is already used this repository.

@bors r+ p=2

**Comment by ehuss** [comment]
@bors treeclosed=100

Large builders are offline.

**Comment by ehuss** [comment]
@bors retry

runners offline

**Comment by RalfJung** [comment]
> there's a trivial change to the license list and I'm not sure I'm supposed to self-approve that.

There's nobody assigned to the PR (since you requested a "ghost" review) so nobody else will look at it either.

In this case, given that this is already a rustc dependency, this seems fine.

> These syncs are pretty painful when the repositories drift apart.

FWIW, in my experience doing these syncs for Miri, it helps a lot to do automate as much as possible and do them more often. We have a script that creates the PR fully automatically (for Miri -> rustc syncs); I run that almost every weekend and it is usually entirely pain-free.

**Comment by lnicola** [comment]
> There's nobody assigned to the PR (since you requested a "ghost" review) so nobody else will look at it either.

Oh, I thought the CCed people would look at it.

> FWIW, in my experience doing these syncs for Miri, it helps a lot to automate as much as possible and do them more often.

We do it every week(-ish) as well, but recently ran into a lot of bootstrap and lint related issues, like the "unknown `cfg`" lint, and stuff related to linking to `rustc_driver`; some of them wouldn't even show up on the PR CI, just on bors.

The other thing is that `git subtree` seems to report more conflicts than expected, even ones I've fixed before. There was one that showed up on every sync for I don't know, 6 months or maybe a year. It was auto-fixable, fortunately, and I think it went away recently when Veykril removed the code.

We were also stopping merges on the rust-analyzer side until the sync back (rust -> rust-analyzer), because if the rust-analyzer repository changed, we'd get more conflicts. What helped here was doing the sync back only up to the release commit, not up to master. So instead of:

1. merge rust-analyzer release into rustc master
2. fetch rustc master
3. subtree rustc master into a rust-analyzer branch
4. merge rust-analyzer master into the new branch
5. merge the new branch into rust-analyzer

This works much better:

1. merge rust-analyzer release into rustc master
2. fetch rustc master
3. subtree rustc master into a rust-analyzer branch
4. merge rust-analyzer release into the new branch
5. merge rust-analyzer master into the new branch
6. merge the new branch into rust-analyzer

> For the other direction we have a CI cronjob that creates a PR automatically whenever Miri no longer builds against rustc master.

We always sync both ways, not only when it stops building, because of https://github.com/rust-lang/rust-analyzer/pull/13676.

I think you're using `josh` now, maybe that one is more resilient, I haven't tried it yet.

**Comment by RalfJung** [comment]
Ouch. :( Okay that sounds quite painful. Not sure why it's so much worse for RA than for Miri. Do you have a lot of conflicts? We do syncs in the two directions largely independent of each other and that works fine.

The git master version of josh is pretty reliable, yeah. (The latest released version still has an issue that can sometimes be blocking.)

**Comment by lnicola** [comment]
> Do you have a lot of conflicts?

We used to freeze `master` during the syncs, but that wasn't strictly enforced and some of them took 2-3 days because of other PRs in the queue (that is, ignoring the CI/bors failures). So not a lot of conflicts in practice, but before my two-step merge trick, every "real" conflict would show up again on every further change to the same file up to `master`.

**Comment by lnicola** [comment]
@mu001999 was this in time for you?

**Comment by mu001999** [comment]
> @mu001999 was this in time for you?
> 
> Guess not, sorry 😔.

Never mind ;) seems the CI stuck again unexpectedly

**Pull request merged**
