### PR TITLE
std: Always check for EDEADLK in rwlocks on unix

### LINKED ISSUE #25012: Rwlock handles recursive locking attempts poorly on linux (double unlock)
On linux pthread_rwlock_rdlock/wrlock return EDEADLK if you attempt to take the other type of lock when you own one. libstd ignores this when debug-assertions are not on, and then will try to unlock twice anyway. This leads to arbitrarily bad behavior (on playpen it happens to hit x86-HLE code and SIGILL):

```
use std::sync::RwLock;
fn main() {
    let x = RwLock::new("");
    let _w = x.write().unwrap();
    let _r = x.read().unwrap();
}
```

### PR DESCRIPTION
**Pull request by alexcrichton**
Apparently implementations are allowed to return EDEADLK instead of blocking
forever, in which case this can lead to unsafety in the `RwLock` primitive
exposed by the standard library. A debug-build of the standard library would
have caught this error (due to the debug assert), but we don't ship debug
builds right now.

This commit adds explicit checks for the EDEADLK error code and triggers a panic
to ensure the call does not succeed.

Closes #25012

### CODE REVIEW

**Comment by aturon** [comment]
Fun!

@bors: r+

**Comment by huonw** [comment]
Do we have any test builders that bootstrap/test with debug assertions on in std/rustc?

**Comment by sfackler** [comment]
Is there any reason to not simply change the `debug_assert_eq` to `assert_eq` at this point?

**Comment by alexcrichton** [comment]
@huonw 

> Do we have any test builders that bootstrap/test with debug assertions on in std/rustc?

Currently, no

---

@sfackler 

> Is there any reason to not simply change the debug_assert_eq to assert_eq at this point?

Only in the sense that you get a nicer error message

**Pull request merged**
