### PR TITLE
Implement PartialOrd and Ord for SocketAddr*

### LINKED ISSUE #53710: Why doesn't std::net::SocketAddr implement std::cmp::Ord and std::cmp::PartialOrd?
It seems to me a bug, because `std::net::IpAddr` implements `std::cmp::Ord` and `std::cmp::PartialOrd`.

### PR DESCRIPTION
**Pull request by hch12907**
The implementation is mostly the same as the one found in `IpAddr` (other than adding comparison for ports, of course).
Continues #53788 and #53863
Fixes #53710

### CODE REVIEW

**Comment by retep998** [comment]
Aren't trait impls insta-stable?

**Comment by hch12907** [comment]
To be honest, I wasn't really sure.. which is why I played it safe by making them unstable. Should I just change all the instances of `#[unstable(...)]` into `#[stable(...)]`?

**Comment by hch12907** [comment]
Uh, I'll rebase it properly in a moment.

**Comment by Amanieu** [comment]
I'm not really sure if ordering addresses makes sense, but since we already have the precedent in `IpAddr` I think this is fine.

@rfcbot fcp merge

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by dtolnay** [comment]
This FCP covers:

```rust
// heterogeneous PartialEq
impl PartialEq<SocketAddr> for SocketAddrV4 {...}
impl PartialEq<SocketAddr> for SocketAddrV6 {...}
impl PartialEq<SocketAddrV4> for SocketAddr {...}
impl PartialEq<SocketAddrV6> for SocketAddr {...}

// Ord
impl Ord for SocketAddr {...}
impl Ord for SocketAddrV4 {...}
impl Ord for SocketAddrV6 {...}

// homogeneous PartialOrd
impl PartialOrd<SocketAddr> for SocketAddr {...}
impl PartialOrd<SocketAddrV4> for SocketAddrV4 {...}
impl PartialOrd<SocketAddrV6> for SocketAddrV6 {...}

// heterogeneous PartialOrd
impl PartialOrd<SocketAddr> for SocketAddrV4 {...}
impl PartialOrd<SocketAddr> for SocketAddrV6 {...}
impl PartialOrd<SocketAddrV4> for SocketAddr {...}
impl PartialOrd<SocketAddrV6> for SocketAddr {...}
```

The first 3 groups looks fine to me.

Is there any use case for the last group? What kind of code would reasonably want to use those?

**Comment by dtolnay** [comment]
Just gonna register my skepticism in https://github.com/rust-lang/rust/pull/72239#issuecomment-631765007. 

@rfcbot concern heterogeneous PartialOrd

I think those impls could cause more harm than good, where a refactor turns something that used to be a homogeneous `<` into an unintentional heterogeneous `<` that is always true or always false because it's comparing V6s to a constant V4 for example.

**Comment by hch12907** [comment]
I implemented it because `IpAddr` has had similar implementations too. (#38464)

Though I agree that its use cases are very niche and generally not useful, it may be surprising for users to find that their code fails to compile, when they find-and-replace `IpAddr*` with `SocketAddr*`.

**Comment by hch12907** [comment]
Removed heterogeneous ordering as per @dtolnay's suggestion and updated the tests a little bit. The PR should be ready for further (and hopefully final!) review now.

**Comment by dtolnay** [comment]
@rfcbot resolve heterogeneous PartialOrd
@rfcbot reviewed

**Pull request merged**
