### PR TITLE
Remove LocalDefId <-> HirId global maps

### PR DESCRIPTION
**Pull request by cjgillot**
~Based on https://github.com/rust-lang/rust/pull/89124.~

The LocalDefId <-> HirId maps were globally accessed through `tcx.definitions`. They are now encoded using the HIR queries.
- For HirId -> LocalDefId, a side map is added inside `hir_owner_nodes(hir_id.owner)`, indexed by `hir_id.local_id`.
- For LocalDefId -> HirId, the mapping is obvious if the `local_def_id` is an HIR owner, ie. if `hir_owner` is `Some`. Therefore, we  use the `None` case to store the non-owning `HirId`.

There is a special case with `use` trees, which can have a LocalDefId, which should be an HIR owner, but with no associated HIR data structure. In that case, we store the information like non-owning definitions.

### CODE REVIEW

**Comment by oli-obk** [comment]
Should we rerun perf or is this just a rebase?

**Comment by cjgillot** [comment]
This is just a rebase. I haven't figured how to reduce the regression yet.

**Comment by cjgillot** [comment]
Replaced by #93373.

**Pull request closed without merging**
