### PR TITLE
rustc_target: Change os and vendor values to "none" and "unknown" for some targets

### LINKED ISSUE #77730: rustc_target: The differences between `target_os = "none"` and `target_os = "unknown"`, and `target_vendor = "unknown"` and `target_vendor = ""` are unclear
The majority of targets use `target_os = "none"` / `target_vendor = "unknown"` respectively, but some targets deviate and use `target_os = "unknown"` / `target_vendor = ""`.

Possible solutions:
- There's no difference between "", "none" and "unknown", normalize to the more common variants.
- There are deep reasons for the status quo, keep and document it.
- 50 / 50 of the above.

### PR DESCRIPTION
**Pull request by petrochenkov**
Closes https://github.com/rust-lang/rust/issues/77730
r? @ehuss

### CODE REVIEW

**Comment by ehuss** [comment]
I'm going to approve this even though I am not a rustc reviewer. @petrochenkov is on the team, and I assume is comfortable assigning it to me.  It seems reasonable to me, and seems unlikely to make a difference in practice.  I did a search on crates.io for anything that is looking for an empty string in `target_vendor` and didn't see anything.  There is some risk that this may break something that is relying on that behavior, though.

avr-unknown-gnu-atmega328 is a bit of an oddball, since it doesn't follow normal naming conventions (see also https://github.com/rust-lang/rust/pull/74941#issuecomment-712219034).  I think that changing it to `os=none` makes sense, but I am not familiar with that target.  It should probably be changed to follow the normal naming conventions (though I imagine that's a larger discussion).

@bors r+

**Comment by XAMPPRocky** [comment]
For the release notes which target names have been changed? It's hard to tell just from the diff how many or which of the targets have new names.

**Comment by petrochenkov** [comment]
@XAMPPRocky 
Target names didn't change, only their `target_os` and `target_vendor` values did.

**Comment by XAMPPRocky** [comment]
@petrochenkov Isn't that in the name? If not I'm not sure I understand where this change would affect users.

**Comment by petrochenkov** [comment]
The change would affect code using `#[cfg(target_vendor = "")]` or `#[cfg(target_vendor = "unknown")]` with these targets, which is very unlikely to ever happen in practice.

**Pull request merged**
