### PR TITLE
Move path parsing earlier

### PR DESCRIPTION
**Pull request by nnethercote**
It's a hot enough path that moving it slightly earlier gives a tiny but easy speedup.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
@rust-timer d6f850c0e4cd20dc640d3ae2a0ecbc5407063042

**Comment by petrochenkov** [comment]
@nnethercote 
r=me if you like the perf results

**Comment by nnethercote** [comment]
The improvements are tiny but clear.

@bors r=petrochenkov

**Pull request merged**
