### PR TITLE
Implement match ergonomics 2024

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
Implement changes to match ergonomics for the 2024 edition, as described in #105647, #64586, https://hackmd.io/YLKslGwpQOeAyGBayO9mdw.

- [x] `mut ref`/`mut ref mut`
  - [ ] Bikeshed
  - [ ] Update all pattern diagnostics to ensure they know about this
- [x] Changes to `&` and `&mut` patterns
  - [ ] The HackMD says the reference types should be "compatible", not sure what that means so in the current impl they must match exactly
- [x] Don't reset binding mode on `mut` with edition >= 2024
  - [x] Edition migration lint
    - [x] Rustfix
- [ ] Feature gating
- [ ] Documentation
- [ ] FCP (RFC?)

Continuation of #120095. @Nadrieril 

@rustbot label T-lang A-edition-2024 A-patterns

### CODE REVIEW

**Comment by Nadrieril** [comment]
Wow, thank you for taking over this! Let me know when you'd like me to have a look.

**Comment by Jules-Bertholet** [comment]
@Nadrieril this should be ready for an initial review

@rustbot label -S-waiting-on-author

**Comment by WaffleLapkin** [comment]
This groups together multiple mostly unrelated changes. Could you split them into separate PRs? This will make review, discussion, FCPs, etc easier.

**Comment by Jules-Bertholet** [comment]
@WaffleLapkin The changes are related, as the edition migration lint for the change to `mut ident` relies on all the other features in order to produce valid code.

**Comment by WaffleLapkin** [comment]
> So if I split this up, the edition change PR will be blocked on the other two.

That seems fine?...

Like, if everything is in the same PR, everything in it is blocked on everything else.

Also, the edition migration is what's blocked (I think we can merge the implementation before the migration? seems fine as long as we don't forget to merge the migration later).

**Comment by Jules-Bertholet** [comment]
Closing in favor of separate PRs.
Tracking issue: https://github.com/rust-lang/rust/issues/123076

**Pull request closed without merging**
