### PR TITLE
Fix angle bracket formatting when dumping MIR debug vars

### LINKED ISSUE #66985: -Zunpretty=mir-cfg generates invalid dot syntax
Program:

```rust
fn f(arg: (u8)) {}
fn main() { f((0)) }
```

Build with `-Zunpretty=mir-cfg`:

```
$ /home/omer/rust/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc -Zunpretty=mir-cfg test.rs > test.dot
```

Generated .dot file is not valid:

```
$ dot -Tpng test.dot > test.png
Error: test.dot: syntax error in line 15 near '>'
```

File contents:

```dot
digraph __crate__ {
subgraph cluster_Mir_0_4 {
    graph [fontname="monospace"];
    node [fontname="monospace"];
    edge [fontname="monospace"];
    label=<fn main() -&gt; ()<br align="left"/>>;
    bb0__0_4 [shape="none", label=<<table border="0" cellborder="1" cellspacing="0"><tr><td bgcolor="gray" align="center" colspan="1">0</td></tr><tr><td align="left">_0 = const f(const 0u8)</td></tr></table>>];
    bb1__0_4 [shape="none", label=<<table border="0" cellborder="1" cellspacing="0"><tr><td bgcolor="gray" align="center" colspan="1">1</td></tr><tr><td align="left">return</td></tr></table>>];
    bb0__0_4 -> bb1__0_4 [label="return"];
}
subgraph cluster_Mir_0_3 {
    graph [fontname="monospace"];
    node [fontname="monospace"];
    edge [fontname="monospace"];
    label=<fn f(_1: u8) -&gt; ()<br align="left"/>debug arg => _1;<br align="left"/>>;
    bb0__0_3 [shape="none", label=<<table border="0" cellborder="1" cellspacing="0"><tr><td bgcolor="gray" align="center" colspan="1">0</td></tr><tr><td align="left">return</td></tr></table>>];
}
}
```

### PR DESCRIPTION
**Pull request by osa1**
Fixes #66985

### CODE REVIEW

**Comment by osa1** [comment]
Does this need a test? Where do I add it? Do we have any other tests that invoke `dot` to copy?

**Comment by matthewjasper** [comment]
The graphviz output of the compiler is untested. You could add a test in `src/test/run-make`. I'm not sure how I feel about requiring graphviz in the tests though.

**Comment by osa1** [comment]
> The graphviz output of the compiler is untested

OK, in that case this is good to go.

**Pull request merged**
