### PR TITLE
Add `ControlFlow::is_{break,continue}` methods

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
r? @scottmcm cc #75744

### CODE REVIEW

**Review by scottmcm — APPROVED** [review]
Makes sense to me; fits with `is_ok` and `is_none` and friends.

r=me when CI passes.

**Comment by LeSeulArtichaut** [comment]
@scottmcm CI is green now

**Comment by scottmcm** [comment]
@bors r+ rollup

(This will probably end up merge-conflicting with one of the other PRs, but maybe we'll get lucky.)

**Comment by Mark-Simulacrum** [comment]
This was backported into 1.48 (approved by me) in #79075 as a dependency of #78775.

**Pull request merged**
