### PR TITLE
Bump bootstrap to 1.72 beta

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
(This re-formats a bunch of let-else's so touches a bunch of code)

**Review by onur-ozkan — APPROVED** [review]
Changes looks good to me. I am not sure if I should queue the PR right away(I don't know how we handle release PRs). I leave that to you with r=me

**Comment by klensy** [comment]
Should format commit be added to git-blame-ignore-revs or it small?

**Comment by Nilstrieb** [comment]
It's true that it's never nice to get conflicts on PRs, but for such extremely conflict-prone PRs like this we just have to eat it and merge ASAP or it will drown in conflicts and never be merged.

**Comment by compiler-errors** [comment]
@matthiaskrgr: If this PR has to yield to all of the rollups, then this PR is never going to get merged, as folks use let-else quite frequently and the lack of formatting means that they're often not formatting them correctly. The onus shouldn't be on Mark to have to rebase past every other contributor's usages of let-else that land in the mean time. 

The sooner we can get beta bumped, the sooner we can get formatting support *before a PR* is put up.

Anyways, this PR is testing already, so I'm not sure what's being achieved by lowering the priority now, other than making this PR more annoying to merge

**Comment by fee1-dead** [comment]
Bumping bootstrap is a lot of work as well. Arbitrarily marking this as less priority just for a rollup doesn't make sense to me. It makes more sense to mark this as the highest priority to ensure consistent and correct formatting than wait for some random PRs just because this might conflict with those.

I'll also add that pushing to those PRs to fix formatting is trivial to do where resolving conflicts for this PR is non-trivial.

**Comment by matthiaskrgr** [comment]
> this PR is never going to get merged

you would both be right if we would get 20-30 prs approved in a day and the queue would fill up quick enough, but at the current rate I expect the queue to be down to maybe 5 prs again in around 30 hours max.  At that point we could rebase one (this) pr once and have it merged right away, instead of creating avoidable merge conflicts for multiple prs that have been  approved for longer and of course in the queue for way longer, but I'm also not the one who will have to deal with the merge conflicts so :shrug: 

>Anyways, this PR is testing already,

Right I didn't see this when I started commenting, my bad :D


>I'm not sure what's being achieved by lowering the priority now,

Right I didn't see that bors was fixed in the meantime.
I am trying to keep the total time wasted on a resolving merge conflicts at a minimum. :slightly_smiling_face: 

From looking at the pr, you only need to:
re-cherry-pick the first 3 commits onto master (10 seconds?) 
re-run `x.py format` (maybe 30 seconds?)
echo "# format let-else" >> .git-blame-ignore-revs
git log -1 --format=%H >> .git-blame-ignore-revs

So maybe a minute in total (ok x.py check to verify everything build might take another 2-5 minutes depending on the machine)


vs having to manually walk through your pr and resolve all the merge conflicts which might 2-5 minutes as well but there will probably be multiple prs that have to be rebased (only talking about the ones that have been approved already) and I expect the total time to manually rebase these to exceed the time needed to run git cherry-pick + x.py fmt

**Comment by fee1-dead** [comment]
If you are talking about contributor time, then disabling all formatting would count as an improvement. Still want code to look good? Just have a bot that periodically reformats the entire codebase.

**Comment by jyn514** [comment]
looks like we timed out installing clang (???)

@bors retry

**Comment by jyn514** [comment]
fwiw i want to mention that these bootstrap bumps usually hit *lots* of issues that need to be fixed, so spreading them out a day apart with time needed to fix conflicts in between makes it very likely it would take *weeks* to land

**Pull request merged**
