### PR TITLE
Add a method to query the capacity of a BufWriter and BufReader

### PR DESCRIPTION
**Pull request by 197g**
Besides the obvious of retrieving the parameter used to construct the writer, this method allows consumers to control the number of `flush` calls during write operations. For `BufReader` it gives an upper bound on the returned buffer in `fill_buf` which might influence the allocation behaviour of a consumer.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Seems plausible to me, thanks!

This'll want to get tagged as an `#[unstable]` API, and it may be good to go ahead and mirror it onto `BufReader` as well?

**Comment by HeroicKatora** [comment]
> [...] it may be good to go ahead and mirror it onto BufReader as well?

I don't see why not, it also relates to the length of the buffer returned from a call to `fill_buf`.

**Comment by HeroicKatora** [comment]
That should now have a feature gate and appropriate tests.

**Comment by JohnTitor** [comment]
The unstable attribute's issue number should be tracking issue's, not PR's. Opened #68833, I'll submit a follow-up PR once this is merged.

**Pull request merged**
