### PR TITLE
Remove libc from more tests

### PR DESCRIPTION
**Pull request by saethlin**
The goal here is to trim down the number of tests that depend on libc from the sysroot to make https://github.com/rust-lang/rust/pull/123938 more plausible.

This PR is a few simple cases that I missed in https://github.com/rust-lang/rust/pull/123943.

### CODE REVIEW

**Comment by jieyouxu** [comment]
Thanks for the cleanups 💚
r? jieyouxu
@bors r+ rollup

**Comment by matthiaskrgr** [comment]
@bors r- 
https://github.com/rust-lang/rust/pull/124109#issuecomment-2062998684

**Comment by saethlin** [comment]
@bors rollup=iffy
@bor r=jieyouxu

**Comment by jieyouxu** [comment]
> @bors rollup=iffy
> @bor r=jieyouxu

wrong bors :3

**Comment by saethlin** [comment]
Oops, sorry
@bors r=jieyouxu

**Pull request merged**
