### PR TITLE
Add "-webkit-overflow-scrolling: touch;" to book CSS

### PR DESCRIPTION
**Pull request by nelsonjchen**
Without these properties, these sections of the page in the Rust book do not have momentum scrolling in iOS which makes reading the book on iOS a fairly arduous experience. 

These commits adds the `-webkit-overflow-scrolling: touch;` property to both the TOC and the page content itself.

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm not at all in favour of using proprietary features.

**Comment by huonw** [comment]
@Ms2ger do you know of a non-prioprietary way to achieve this?

**Comment by Gankro** [comment]
As far as I can tell, this is simply the standard way to obtain this platform-specific behaviour. I've seen some hints that other platforms have tried to "infer" when this can be done, but it's apparently delicate.

**Comment by alexcrichton** [comment]
@bors: r+ e0dc9bd

I think we can always expand this in the future to more platforms, thanks for the PR!

**Comment by nelsonjchen** [comment]
Momentum scrolling actually works just fine on my Android phone so there's nothing be done there as far as I can tell. This is strictly an iOS only thing. Momentum scrolling even works in Safari on OS X. Just, once again, not iOS.

**Pull request merged**
