### PR TITLE
Add a tidy rule forbidding modules named `build`

### PR DESCRIPTION
**Pull request by Zalathar**
The module directory `compiler/rustc_mir_build/src/build/` causes a number of contributor papercuts:

- GitHub's go-to-file feature doesn't work for any files in this directory.
- We need a negated rule in .gitignore to override the blanket ignore rule for `build/`.
- Some git-adjacent tools automatically parse .gitignore but don't understand negative rules, so they inappropriately ignore the directory.
- Some tidy checks are accidentally not applied within this directory, probably for similar reasons.

Any one of these might be fixable or ignorable, but all of them together suggest that allowing modules named `build` is just not worth the hassle, especially when it isn't even necessary.

---

This PR therefore adds a tidy check forbidding `mod build;` and similar, and renames the existing modules that would be forbidden by that check. There are no functional changes in the affected modules.

(The check also has the side-effect of forbidding `build.rs` files that aren't build scripts, which seems net-positive.)

### CODE REVIEW

**Comment by Zalathar** [comment]
Replaced manual LazyLock with `static_regex!` [(diff)](https://github.com/rust-lang/rust/compare/b9d572830644196fa00c62323c212d310807617e..508e78f6d39aa6db328e903cf3be9a1dfaa639fc).

**Comment by jieyouxu** [comment]
r? jieyouxu

**Comment by Zalathar** [comment]
Ignoring non-root build directories was done deliberately in #106440.

**Comment by jieyouxu** [comment]
Hm, I'm inclined to revert it back to `/build/`, because `/build` will match against *any* subdirectories name `build/`, including e.g. `compiler/rustc_mir_build/src/build/foo.rs` which I find very footgunny. @pnkfelix wanted to be able to run `./x.py` from subdirectories (which would create `build/` underneath subdirectories, but creating `build/` in subdirectories seem very strange).

**Comment by jieyouxu** [comment]
Hi @Zalathar, thanks for the PR. I'm going to close this in favor of #133592, as I think not having the special `.gitignore` hacks is overall a better experience and it avoids having to add more special cases to tidy.

I would be in favor, however, of renaming `rustc_mir_build/src/build/` to something... more descriptive if those more familiar with MIR has better names...

**Comment by Zalathar** [comment]
Renaming `rustc_mir_build::build` extracted to #134365.

**Pull request closed without merging**
