### PR TITLE
Add error code for unstable feature errors

### LINKED ISSUE #47397: Shouldn't the "use of unstable library feature" error have an error number?
I thought every error was supposed to have a number that one could look up in the [error index](https://doc.rust-lang.org/error-index.html), run `rustc --explain` with, etc... but if I run this code with stable rust 1.23.0:

```
fn testl() {
    ::std::u128::MAX;
}
```

I get: 

```
error: use of unstable library feature 'i128' (see issue #35118)
 --> src/lib.rs:2:5
  |
2 |     ::std::u128::MAX;
  |     ^^^^^^^^^^^^^^^^
```

Rather than `error[E0644]` or something.

Feel free to close if this was a deliberate decision.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #47397.

### CODE REVIEW

**Comment by estebank** [comment]
r=me after rebasing against master.

**Comment by GuillaumeGomez** [comment]
Rebased. Considering the fact that I updated a lot of UI tests, I'll put a small priority (but sill bigger than 0) to avoid too much rebases.

@bors: r=estebank p=1

**Comment by estebank** [comment]
@bors r-

There seem to be [some issues with a test](https://travis-ci.org/rust-lang/rust/jobs/328882545#L6203).

**Comment by GuillaumeGomez** [comment]
Apparently there was an extra empty line in one stderr file. Strange... Should work now (but I'll wait for CI first).

**Pull request merged**
