### PR TITLE
Always inline `len` of `std::vec::Vec`.

### PR DESCRIPTION
**Pull request by Jerrody**

### CODE REVIEW

**Comment by asquared31415** [comment]
I don't expect this to do *anything* to codegen or performance, this function is almost certainly going to be inlined in every case anyway, even with no `#[inline]` marker.

**Comment by Jerrody** [comment]
> I don't expect this to do _anything_ to codegen or performance, this function is almost certainly going to be inlined in every case anyway, even with no `#[inline]` marker.

For me, it's better to be 100% sure that everything was made for this.

**Comment by faptc** [comment]
Do you have any snippets that could prove that `Vec::len` not inlined?

**Comment by Jerrody** [comment]
> Do you have any snippets that could prove that `Vec::len` not inlined?

Saying about low-level, exists following rule "it depends". If answer directly, so, nope I haven't those snippets.

**Comment by cuviper** [comment]
See https://std-dev-guide.rust-lang.org/policy/inline.html#what-about-inlinealways

We can let the perf run complete, but I'll be surprised if we see any gain from this.

**Comment by Jerrody** [comment]
> See https://std-dev-guide.rust-lang.org/policy/inline.html#what-about-inlinealways
> 
> We can let the perf run complete, but I'll be surprised if we see any gain from this.

Well, why not wait for perf test.

**Comment by workingjubilee** [comment]
This doesn't seem to be anything.

**Comment by Jerrody** [comment]
> This doesn't seem to be anything.

I'm not benchmarks master or compiler developer, but I see good improvement in instructions count or is it a perf noise?

**Comment by the8472** [comment]
>  but I see a good improvement in the instructions count or is it a perf noise?

Only in 3 incremental/debug builds (out of hundreds). And no runtime benchmark, check or doc improvements.
So even if this isn't noise it's not a big win.

Is this motivated by something? Did you spot non-inlined calls to the function in optimized code?

**Comment by Jerrody** [comment]
> >  but I see a good improvement in the instructions count or is it a perf noise?
> 
> Only in 3 incremental/debug builds (out of hundreds). And no runtime benchmark, check or doc improvements.
> So even if this isn't noise it's not a big win.
> 
> Is this motivated by something? Did you spot non-inlined calls to the function in optimized code?

Literally, this is my personal preference to always inline things that is tiny, so, I decided to make this PR.

**Comment by Noratrieb** [comment]
in that case i don't think it makes sense to change this. we don't want to micro-manage every inline attribute unless we have tangible evidence that it helps (ideally a real-world benchmark, or at least an assembly diff).
if this function wasn't inlined, then either the compiler knows something we don't and knows that it's better to not inline (which seems unlikely), or the compiler has a bug. in either case, `inline(always)` doesn't really solve the problem.
thanks for trying to make Rust faster though :)

**Comment by workingjubilee** [comment]
> I'm not a benchmarks master or compiler developer, but I see a good improvement in the instructions count or is it a perf noise?

The improvement is tiny, and there's also a regression.

> Literally, this is my personal preference to always inline things that is tiny, so, I decided to make this PR.

Because LLVM performs bottom-up inlining, it is very easy to make a mistake and inline something that you think is tiny but is actually quite large because you don't reason like the compiler does about inlining. There's a reason we generally recommend to *not* use `inline(always)`.

**Comment by workingjubilee** [comment]
Obviously this is a trivial field access, but that's precisely what the inliner is good at reasoning about and doing on its own. It doesn't need help there. We could probably even remove the `inline` annotation entirely.

**Comment by Jerrody** [comment]
@Noratrieb @workingjubilee 

Alright, thanks for the explanations. I close this PR, appreciated for the providing some additional context about underlaying working of compiler.

**Pull request closed without merging**
