### PR TITLE
Small mir-opt refactor

### PR DESCRIPTION
**Pull request by scottmcm**
Hopefully-non-controversial changes from some not-ready-yet work that I'd figured I'd submit on their own.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
r? mir-opt

**Comment by michaelwoerister** [comment]
r? rust-lang/mir-opt

**Comment by scottmcm** [comment]
Well, this passed, so might as well just put it in a
@bors rollup

but it probably also needs a
@bors retry

**Pull request merged**
