### PR TITLE
 miri: detect too large dynamically sized objects 

### PR DESCRIPTION
**Pull request by RalfJung**
Needed to make https://github.com/rust-lang/miri/pull/929 pass.

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
Is it possible to write a rustc test for this?

**Comment by RalfJung** [comment]
I tried, but then I ran into https://github.com/rust-lang/rust/issues/63952.

**Comment by RalfJung** [comment]
Ah, I found a way to do it. Does this fit into one of the existing files?

**Comment by oli-obk** [comment]
ub-wide-ptr.rs looks like a good match to me.

r=me either as is or with the test merged into `ub-wide-ptr.rs`

**Comment by RalfJung** [comment]
> ub-wide-ptr.rs looks like a good match to me.

That won't work; that's a `allow(const_err)` test but this test here is a const_err (the error happens before we even start validation).

@bors r=oli-obk

**Pull request merged**
