### PR TITLE
Add inline attributes and add unit to CommonTypes

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build https://github.com/rust-lang/rust/commit/f980b36eec11551030d2199b3f455a5a2116dc0a

**Comment by Zoxc** [comment]
@rust-timer build f980b36eec11551030d2199b3f455a5a2116dc0a

**Comment by Zoxc** [comment]
Seems like a slight win.

r? @michaelwoerister

**Comment by michaelwoerister** [comment]
@bors r+

Thanks @Zoxc! It's kinda sad that we still need these annotations although we have ThinLTO. Although I guess this is mostly because of using dylibs.

**Pull request merged**
