### PR TITLE
debuginfo: Add a name for tuple fields in debuginfo so that they can be accessed in debuggers.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR makes `rustc` emit field names for tuple fields in DWARF. Formerly there was no way of directly accessing the fields of a tuple in GDB and LLDB since there is no C/C++ equivalent to this. Now, the debugger sees the name `__{field-index}` for tuple fields. So you can type for example `some_tuple_val.__2` to get the third tuple component.
When pretty printers are used (e.g. via `rust-gdb` or `rust-lldb`) these artificial field names will not clutter tuple rendering (which was the main motivation for not doing this in the past).

Solves #21948.

### CODE REVIEW

**Comment by jdm** [comment]
:100:

**Comment by michaelwoerister** [comment]
It's always the same with you, @michaelwoerister...
Fixed the line-length issue.

**Comment by alexcrichton** [comment]
@bors: r+ 03f92694966259ee156bb8f3a7ef9d4dc587ecb9

Nice!

**Comment by jakub-** [comment]
Cool! Just to confirm, this couldn't be just `{field-index}` (as that's what the Rust equivalent is) because of restrictions on the field names, right?

**Comment by michaelwoerister** [comment]
@jakub- That's correct. I've tried using just the index but GDB's parser can't handle that.

**Pull request merged**
