### PR TITLE
Stabilize pointer::align_offset

### LINKED ISSUE #44488: Tracking issue for RFC 2043: Add `align_offset` intrinsic (formerly: and `[T]::align_to` function)
This is a tracking issue for the RFC "Add `align_offset` intrinsic and `[T]::align_to` function " (rust-lang/rfcs#2043). `align_to` is stable, so this tracks just `align_offset` now.

**Steps:**

- [x] Implement the RFC (align_offset: #43903; align_to: https://github.com/rust-lang/rust/pull/50319)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide]): `align_to`: https://github.com/rust-lang/rust/pull/53754

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [ ] "produce a lint in case `sizeof<T>() % sizeof<U>() != 0` and in case the expansion is not part of a monomorphisation, since in that case `align_to` is statically known to never be effective

### PR DESCRIPTION
**Pull request by CryZe**
Closes #44488

### CODE REVIEW

**Comment by RalfJung** [comment]
Just like with `align_to`, the docs should say that the method is allowed to fail (return `max`) even if aligning was possible -- this is a best-effort operation.

(In practice, it will always return `max` when running in CTFE/Miri.)

**Comment by RalfJung** [comment]
@CryZe  Can you do that docs change in a follow-up PR?

**Comment by CryZe** [comment]
They already state that: https://github.com/rust-lang/rust/pull/60303/files#diff-9839f9730ca3a90d5c0ebb0a7edd67cfR1524

**Comment by RalfJung** [comment]
That doesn't say that this may happen "spuriously".

`align_to` says

> The method does a best effort to make the middle slice the greatest length possible for a given type and input slice, but only your algorithm's performance should depend on that, not its correctness.

to make sure that this gets across.

**Comment by czipperz** [comment]
Out of curiosity, why wasn't this included in 1.35.0?  Wasn't that released nearly a full month after this?

**Comment by RalfJung** [comment]
Rust's release trains take 6 weeks. So any PR will generally enter the release that happens between 6 and 12 weeks after it landed.

**Pull request merged**
