### PR TITLE
Avoid tagging as I-nominated on toolstate breakage

### PR DESCRIPTION
**Pull request by spastorino**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We've confirmed with compiler team that we want this, right? If so, r=me -- seems correct but could break - we'll have to see.

**Comment by spastorino** [comment]
[We agreed during last week compiler team meeting](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202020-03-19.20.2354818/near/191117435). [@nikomatsakis have said that as long as we have a mechanism to raise alarm if problems are persisting he would be ok](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202020-03-19.20.2354818/near/191117692).

With that in mind I've added a step to check toolstate during prioritization on t-compiler, then talked to @Centril who has said that T-release can take care of this.

Please everyone confirm that this is what we want.

**Comment by Mark-Simulacrum** [comment]
> then talked to @Centril who has said that T-release can take care of this

I think this should be a compiler team check -- release team would end up just pinging compiler team creating needless run arounds.

However, we can work out that exact process later, I think, and if we run into trouble in some sense.

@bors r+

**Comment by spastorino** [comment]
> > then talked to @Centril who has said that T-release can take care of this
> 
> I think this should be a compiler team check -- release team would end up just pinging compiler team creating needless run arounds.
> 
> However, we can work out that exact process later, I think, and if we run into trouble in some sense.
> 
> @bors r+

Going to add that back to prioritization wg procedure.

**Comment by spastorino** [comment]
doh!

@bors r=Mark-Simulacrum

**Comment by Centril** [comment]
> I think this should be a compiler team check -- release team would end up just pinging compiler team creating needless run arounds.

@Mark-Simulacrum I don't think that's would be necessary. At this point I think that between the release team members / associated people, we have sufficient experience wrt. infra (Pietro + Mark), compiler internals (Mark + Centril + Jonas + Cuviper + Tmandry), and tools (huuyumi) to contact the tools people directly and work things out in crisis situations (which is very rare).

**Comment by Mark-Simulacrum** [comment]
Just because we have overlap in the set of folks does not mean that release team should be responsible for identifying whether tool breakage is a problem. It is (obviously) true that we have experience on the release team, but I don't want to see us taking on this responsibility at this time, and I believe it is better suited to the compiler team triage process (which has a pre-triage element for a small group of people). If the release team is to take this responsibility on, it basically means that someone (me? who?) on the release team now needs to start checking in with toolstate regularly. Maybe that's a good thing to discuss doing -- or even setting up alerts -- but I don't want to do that right now as part of this decision to remove the I-nominated tag.

**Comment by Centril** [comment]
> Maybe that's a good thing to discuss doing -- or even setting up alerts -- but I don't want to do that right now as part of this decision to remove the I-nominated tag.

Fair; I'm happy to have this discussion with you / others at some other point though. :)

**Pull request merged**
