### PR TITLE
Switch to normalized triples for Fuchsia

### PR DESCRIPTION
**Pull request by petrhosek**
This is a revert of e950d22fbf6895b812a120d31a2bdf2515ee16f0 which is no
longer needed since Clang now does normalization and handles all triple
spellings.

### CODE REVIEW

**Comment by camelid** [comment]
@petrhosek There seem to be merge conflicts. I think you'll need to rebase over upstream/master.

**Review by tmandry — APPROVED** [review]
This brings Fuchsia triple naming in line with nearly every other OS, so looks good to me.

**Comment by pietroalbini** [comment]
r? rust-lang/compiler

CI changes look good, but the compiler team should actually approve the change.

**Comment by tmandry** [comment]
Re-rolling

r? rust-lang/compiler

**Comment by matthiaskrgr** [comment]
Looks like this failed in a rollup: https://github.com/rust-lang/rust/pull/91056#issuecomment-974524776
@bors r- rollup=iffy

**Comment by JohnCSimon** [comment]
Ping from triage: 
@petrhosek Can you please post your status on  this PR? Is it ready for review? Thank you.

**Comment by JohnCSimon** [comment]
triage:
I'm moving this to waiting on Review... don't want to close a PR as inactive if it already has an approval - even though it hasn't moved for two months.
 
@rustbot label: -S-waiting-on-author +S-waiting-on-review

**Comment by pnkfelix** [comment]
@petrhosek @tmandry this seemed like it failed in rollup. Can you look into it?

**Comment by JohnCSimon** [comment]
@petrhosek  
Ping from triage: I'm closing this due to inactivity. This hasn't been touched in months. 
Please reopen when you are ready to continue with this. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
