### PR TITLE
Prepare beta 1.40.0

### PR DESCRIPTION
**Pull request by emilyalbini**
cc @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@alexcrichton -- any thoughts on a good approach to resolving this failure? I suspect personally that we might be conflicting with the bootstrap bitflags, but not sure - I'm not sure why we're only seeing this in this PR (i.e., how master was working)

**Comment by alexcrichton** [comment]
I've got no idea why this is only on beta and not on master. This fixes it though:

```diff
diff --git a/src/bootstrap/builder.rs b/src/bootstrap/builder.rs
index 2748903f2d4..de4e6b56459 100644
--- a/src/bootstrap/builder.rs
+++ b/src/bootstrap/builder.rs
@@ -886,6 +886,7 @@ impl<'a> Builder<'a> {
         // things still build right, please do!
         match mode {
             Mode::Std => metadata.push_str("std"),
+            Mode::ToolRustc => metadata.push_str("tool-rustc"),
             _ => {},
         }
         cargo.env("__CARGO_DEFAULT_LIB_METADATA", &metadata);
```

I've got no idea why it fixes it though.

**Comment by Mark-Simulacrum** [comment]
@bors r+

Pushed up the fix suggested by @alexcrichton along with a comment that proposes one theory for why it's a fix -- though presumably an incomplete one, as it wouldn't explain different behavior between beta and master (hopefully).

**Comment by Keruspe** [comment]
FWIW, wrt the rustdoc build fix: 1.38.0 can build 1.39.0 just fine, but 1.39.0 cannot build itself without backporting the patch.

**Pull request merged**
