### PR TITLE
Update pointers.md

### PR DESCRIPTION
**Pull request by wettowelreactor**

### CODE REVIEW

**Comment by richo** [comment]
This change looks unnecessary, why is it needed?

**Comment by wettowelreactor** [comment]
It may be my mistake but lines 458 through 475 in the doc imply that &*box_var is the proper way of casting a Box pointer to a reference pointer. The same syntax is used on line 554.

**Comment by richo** [comment]
There are now [deref coercions][coercions] which make `Box<T>` deref to a `T` automatically when required (http://is.gd/N9eDzD), which is why I was surprised by this patch.

The other docs might want to be updated, or it's possible that this is correct given that the coercions are not yet introduced. Thanks for the extra context.

[coercions]: https://github.com/rust-lang/rfcs/pull/241

**Comment by alexcrichton** [comment]
Yes and in addition to what @richo mentioned we tend to shy away from `&*` wherever possible (e.g. it shouldn't be necessary in normal code). I think that some of the surrounding examples may want to be borrowed as well, but @steveklabnik may also have a better idea of how to introduce deref coercions (or if they should be used at all).

r? @steveklabnik

**Comment by steveklabnik** [comment]
I am happy with merging this as-is, and I will come back and do stuff about deref coercions. This chapter needs a lot of work anyway, and with associated types merged, i'll get on it soon.

**Pull request merged**
