### PR TITLE
Bump bootstrap compiler to new beta

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
https://forge.rust-lang.org/release/process.html#master-bootstrap-update-t-2-day-tuesday

### CODE REVIEW

**Comment by compiler-errors** [comment]
Do you mind including this one too?

https://github.com/rust-lang/rust/blob/master/rustfmt.toml#L25-L26

Otherwise, no worries, and I'll do it myself after the beta bump.

**Comment by lqd** [comment]
🤔 

> Documenting std v0.0.0 (/checkout/library/std)
> 2024-07-23T11:35:59.8005392Z thread 'rustc' panicked at library/core/src/slice/sort/shared/smallsort.rs:848:5:
> 2024-07-23T11:35:59.8008951Z Ord violation

https://github.com/rust-lang/rust/blob/d111ccdb6186b368ead16c01f43c645a6e5f4a67/library/core/src/slice/sort/shared/smallsort.rs#L837-L843

**Comment by workingjubilee** [comment]
@Voultapher what do you think is up with https://github.com/rust-lang/rust/blob/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/src/librustdoc/html/render/print_item.rs#L316-L556 that is causing it to hit this panic path in smallsort?

**Comment by tgross35** [comment]
Is it possible that the rustdoc side is now doing something less determinant with floats where there wasn't before? https://github.com/rust-lang/rust/pull/126761 touched the rustdoc side (cc @GuillaumeGomez) slightly after https://github.com/rust-lang/rust/pull/124032 merged.

But based on that description I can't even see how the branch should _ever_ hit, given `T: Ord`...

**Comment by tgross35** [comment]
Cc also @orlp who collaborated on the sort algorithm (per the top note at https://github.com/rust-lang/rust/pull/124032).

**Comment by orlp** [comment]
First, this code looks a bit suspect to me:

```rust
if item_ty_to_section(ty1) != item_ty_to_section(ty2)
    || (ty1 != ty2 && (ty1 == ItemType::ExternCrate || ty2 == ItemType::ExternCrate))
{
    return (reorder(ty1), idx1).cmp(&(reorder(ty2), idx2));
}
```

You can't just arbitrarily decide to *sometimes* order by type + index, and sometimes ignore it, and still expect to form a strict weak ordering.

What's even weirder is that if I look at `item_ty_to_section`, I believe that the above code is equivalent to the much simpler:

```rust
if ty1 != t2 {
    return reorder(ty1).cmp(&reorder(ty2));
}
```

which would be correct for a strict partial order. What was the intention of this branch?

---

Then we have the following, which is an actual `Ord` violation:

```rust
let s1 = i1.stability(tcx).as_ref().map(|s| s.level);
let s2 = i2.stability(tcx).as_ref().map(|s| s.level);
if let (Some(a), Some(b)) = (s1, s2) {
    match (a.is_stable(), b.is_stable()) {
        (true, true) | (false, false) => {}
        (false, true) => return Ordering::Greater,
        (true, false) => return Ordering::Less,
    }
}
```

Generally speaking, "order by property X if both objects have property X" does not form a strict weak ordering. Consider the following three objects:

```rust
type   stability   name
0      Some(2)     a
0      None        b
0      Some(1)     c
```

Here we simplify a bit and directly sort by type, then stability if both are `Some`, and then by `name`. Seems reasonable right? Nope.

Here you'll find that the objects with names `a`, `b`, `c` will sort like `a < b < c < a`.

---

This then brings us to [`compare_names`](https://github.com/rust-lang/rust/blob/84c257ebe5319ba68ce9a4ce5bca2d89e7127a14/src/librustdoc/html/render/print_item.rs#L2032). This has an issue with a similar pattern:

```rust
// Then process the numeric part, if both sides have one (and they fit in a u64).
if let (Ok(ln), Ok(rn)) = (lb.parse::<u64>(), rb.parse::<u64>()) {
    match ln.cmp(&rn) {
        Ordering::Equal => (),
        x => return x,
    }
}
```

This violates strict weak ordering. Consider `foo100000000000000000000`, `foo10`, and `foo2`. The comparison function claims that `foo10 < foo100000000000000000000 < foo2 < foo10`.

**Comment by Voultapher** [comment]
@workingjubilee to my knowledge this panic an only happen when the comparison function does not implement a strict weak ordering. This is usually indicative of a logic bug. The old implementation quietly accepted such cases and produced some unspecified but arguably not sorted order.

**Comment by Voultapher** [comment]
> But based on that description I can't even see how the branch should ever hit, given T: Ord

I think this interpretation is something we should consider, maybe a better panic description can help avoid confusion in the future. `T: Ord` only says that it's implemented, not that it is implemented correctly.

**Comment by tgross35** [comment]
Thanks Orson & Lukas for the detailed response. I suppose @rust-lang/rustdoc may want to take a look at a possible change here. The relevant bit was added in 2022 so I doubt anybody has any specific memory of why it exists as it currently does (https://github.com/rust-lang/rust/pull/93830).

A PR to make the panic message more useful would be great, maybe even suggesting to double check `T`'s implementation of `Ord`. Possibly worth a note in the docs as well.

**Comment by GuillaumeGomez** [comment]
This is very surprising. Checking what's going on.

**Comment by workingjubilee** [comment]
Thank you @orlp for the entomology!

Yes, I am familiar with the "`T: Ord` is not actually a mathematical, compile-time-checked proof that the trait is implemented correctly" issue, and actually rather like that we now panic on violating strict weak orderings. But I couldn't quite remember what "strict weak order" was at the time I first asked. Math brain isn't up before noon, you see.

Checking again, if I understand correctly a strict weak ordering is still satisfied by most of libstd's PartialOrd impls, yes? Like floats?

**Comment by Voultapher** [comment]
Small word of caution, the docs say "If T: Ord does not implement a total order, the implementation may panic.". We do catch strict weak ordering violations in many cases, but it's not guaranteed. One thing I like about our implementation in contrast to for example the recently added libc++ `std::sort` strict weak ordering checks, is the libc++ ones work by consuming a fixed number of comparison at the very start (20/50) IIRC, but only for debug builds. In contrast our implementation sits at the heart of the small-sort and notices issues that were caused by some higher level components, this way it holistically works for the hole input catching violation with a high chance, plus it serves dual purpose as a safety safeguard that lets us avoid additional state tracking complexity, bailing before committing the faulty merge result. There are cases where this logic isn't used at all e.g. len <= 20, non `Freeze` types.

**Comment by GuillaumeGomez** [comment]
So is there anything for me to do on rustdoc side or...?

**Comment by Voultapher** [comment]
@GuillaumeGomez yes the rustdoc code needs to be changed so that the comparison functions respect the rules laid out in the [Ord docs](https://doc.rust-lang.org/std/cmp/trait.Ord.html) and with specific examples outlined in @orlp's [comment](https://github.com/rust-lang/rust/pull/128083#issuecomment-2247085914).

**Comment by GuillaumeGomez** [comment]
> Is it possible that the rustdoc side is now doing something less determinant with floats where there wasn't before? #126761 touched the rustdoc side (cc @GuillaumeGomez) slightly after #124032 merged.
> 
> But based on that description I can't even see how the branch should _ever_ hit, given `T: Ord`...

Just to comment on this, the code currently failing wasn't updated in 8 months. The two last commits changing it were:

 * https://github.com/rust-lang/rust/commit/b77aa74a2d6b0b5cac167a942a7c53931dc715c9
 * https://github.com/rust-lang/rust/commit/062d247cd795847be51df9e3f818f0eb52ac0d18

I'm still very surprised that it wasn't uncovered before that... Anyway, still looking into it.

**Comment by orlp** [comment]
@GuillaumeGomez The sort implementation was updated, and the new implementation can panic to alert you that your `Ord` / comparison function implementation is buggy, the old implementation never did that.

**Comment by GuillaumeGomez** [comment]
What I meant is that I'm surprised it didn't trigger when the new sort implementation was merged. Your post really nicely explained everything in detail (thanks a lot for that!) so I'm fixing one thing after the other to ensure that both rustdoc output and Ord violations are ok.

**Comment by GuillaumeGomez** [comment]
When I test with `--stage 1` it works so it'll need for the fix to be merged before this PR. Sending the fix into a PR.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/rust/pull/128139 to have this fix in nightly so this will be able to unlock this PR since it's using `stage 0` to run tests.

**Comment by workingjubilee** [comment]
> What I meant is that I'm surprised it didn't trigger when the new sort implementation was merged. Your post really nicely explained everything in detail (thanks a lot for that!) so I'm fixing one thing after the other to ensure that both rustdoc output and Ord violations are ok.

I suspect we're using the bootstrap compiler for too many things, which is why it took so long.

**Comment by GuillaumeGomez** [comment]
https://github.com/rust-lang/rust/pull/128146 was merged so once new nightly is generated, this PR can be re-approved.

**Comment by tgross35** [comment]
> #128146 was merged so once new nightly is generated, this PR can be re-approved.

Isn't this bug from the beta compiler with the new sort impl building what is currently in tree, meaning this PR only needs a rebase?

**Comment by tgross35** [comment]
And then I take it https://github.com/rust-lang/rust/pull/128083/commits/1258c642680e677ac18f732dd39165de86796cd6 (4th commit on this PR with rustdoc changes) should just be dropped?

**Comment by GuillaumeGomez** [comment]
Rebased.

**Comment by tgross35** [comment]
I think we need the fix in beta and not just a nightly - nominated https://github.com/rust-lang/rust/pull/128146 to get that process rolling.

**Comment by Mark-Simulacrum** [comment]
This is now ready for review.

**Review by GuillaumeGomez — APPROVED** [review]

**Review by albertlarsan68 — APPROVED** [review]

**Comment by tgross35** [comment]
`dist-x86_64-linux` passed when I did a try build with these same changes at https://github.com/rust-lang/rust/pull/128216, so it seems the culprit will be something that merged in the past three days.

**Comment by tgross35** [comment]
New theory new test https://github.com/rust-lang/rust/pull/128331.

I think a lot of people are waiting on this so let's put it above the rollups whenever it is ready again.

@bors p=10

**Pull request merged**
