### PR TITLE
Update to Clang 7 on CI.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Handles Linux and macOS. Windows seems to already have been updated.

r? @Mark-Simulacrum 
cc @rust-lang/infra

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Or at least, let's give it a @bors try

**Comment by alexcrichton** [comment]
r=me with green CI!

**Comment by alexcrichton** [comment]
Looks like a time out due to non primed caches, I don't think retry works on try builds so you'll need to push a new commit (not different content, just a different hash) and the run the try again

**Comment by kennytm** [comment]
No retry does work.

@bors retry

**Comment by pietroalbini** [comment]
@bors retry

The machine was killed...

**Comment by michaelwoerister** [comment]
\o/

**Pull request merged**
