### PR TITLE
rustc: Update LLVM, remove dead wasm code

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates the LLVM branch to the rebased version of the
upstream release/8.x branch. This includes a wasm patch which means that
the `rewrite_imports` pass in rustc is no longer needed (yay!) and we
can instead rely on `wasm-import-module`, an attribute we're already
emitting, to take care of all the work.

### CODE REVIEW

**Comment by cuviper** [comment]
I suspect you're going to run into the new toolchain requirements on the dist builders, per:
http://lists.llvm.org/pipermail/llvm-dev/2019-February/130117.html

I'm working on that right now for dist-*-linux builders, at least. In the meantime you can set `LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN` if it is indeed a problem.

**Comment by alexcrichton** [comment]
ping @matthewjasper, do you think you'll have a chance to take a look at this?

No worries if not, can just r? someone else!

**Comment by matthewjasper** [comment]
This isn't an area of the code I know much about. Could you r? someone else please.

**Comment by Mark-Simulacrum** [comment]
We technically support LLVM 6+ (i.e., that's what the distro LLVM builder in CI uses) -- do we want to continue having the "dead" wasm code?

**Comment by alexcrichton** [comment]
r? @michaelwoerister 

@Mark-Simulacrum we don't support the wasm target on anything other than our in-tree LLVM

**Comment by michaelwoerister** [comment]
@bors r+ 

Thanks, @alexcrichton!

**Comment by Centril** [comment]
Since it has submodule updates, ill use this an inbtw rollup filler, @bors p=1

**Comment by Centril** [comment]
Apparently bors interpreted this wrongly...

@bors p=1 rollup-

**Comment by nikic** [comment]
```
CMake Error at cmake/modules/CheckCompilerVersion.cmake:53 (message):
  Host Clang must have at least -fms-compatibility-version=19.00.24213.1,
  your version is 7.0.0.
```

**Comment by alexcrichton** [comment]
I've no idea what that is, so I've hopefully [corrected the diagnostic](https://github.com/rust-lang/llvm-project/commit/08df1a1ab00260e45c55aea6de46e3fdbf6b77b1) so we can debug a bit more.

@bors: r+

**Comment by alexcrichton** [comment]
That looks like a pretty benign error, and I'm not sure how to get around it, so I've [deleted the version check](https://github.com/rust-lang/llvm-project/pull/9)

@bors: r=michaelwoerister

**Comment by alexcrichton** [comment]
@cuviper your prophecy has been fulfilled!

Do you have thoughts on the best way to approach this? On one hand we really do need to fix this (by either updating toolchains or dropping platforms) but on the other hand this has some other nice fixes for the LLVM release branch. I don't mind going either way, but it could possibly take quite some time to actually update all these toolchains.

One alternative could be to perhaps whitelist specific docker images as "older toolchain allowed" and we at least know what to fix at that point?

**Comment by alexcrichton** [comment]
Hm ok I'm gonna go with that last point and attempt to whitelist images as "this needs an update" but otherwise don't set the option for all images.

@bors: r=michaelwoerister

**Comment by cuviper** [comment]
> One alternative could be to perhaps whitelist specific docker images as "older toolchain allowed" and we at least know what to fix at that point?

Sounds good to me. We should file issues for any that get whitelisted, but this won't be a hard error until LLVM 9 or later.

> The job `dist-x86_64-netbsd` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/180841290) ([raw log](https://api.travis-ci.com/v3/job/180841290/log.txt)).

Might be able to get newer GCC from pkgsrc: https://wiki.netbsd.org/pkgsrc/gcc/

> :broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/rust-lang/rust/builds/22648298)
```
CMake Error at cmake/modules/CheckCompilerVersion.cmake:53 (message):
  Host Clang must have at least -fms-compatibility-version=19.00.24213.1,
  your version is 19.0.
```

FWIW, this is the hard minimum, but the overridable soft error wants 19.1 (VS2017). The soft error wasn't checked for clang-cl, and you deleted the hard error, but it'll eventually need fixing.

https://github.com/rust-lang/llvm-project/blob/38ad31bde8ff681d862dc0f96930a5dd9b7a472e/llvm/cmake/modules/CheckCompilerVersion.cmake#L13-L14

**Comment by alexcrichton** [comment]
Hm ok, it shouldn't be too hard for us to update VS I think if we need, but sounds like a good thing to do intentionally after this lands.

Once this lands I'll open up a follow-up issues for each of the toolchains, currently including MSVC and NetBSD

**Comment by alexcrichton** [comment]
Docker rebuilt for that container, taking 2.5h, causing a timeout

@bors: retry

**Comment by cuviper** [comment]
Why is `dist-x86_64-linux` rebuilding its docker image? You didn't touch that!

In #58416 this seemed to be a problem too. There it really did need docker updates, of course, but it seemed to take a few tries before they all finally stuck.

**Comment by alexcrichton** [comment]
@cuviper it's probably hashing issues like before, although I won't pretend to know what hashing issues it is...

In any case I'm surprised this landed! I guess we don't actually have all that many toolchains to update

**Comment by alexcrichton** [comment]
I've opened up https://github.com/rust-lang/rust/pull/58852 to handle the NetBSD toolchain, will look into Windows next.

**Comment by alexcrichton** [comment]
And https://github.com/rust-lang/rust/pull/58854 is the attempt for Windows

**Pull request merged**
