### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #95234 (bootstrap.py: nixos check in /etc/os-release with quotes)
 - #95449 (Fix `x doc --stage 0 compiler`)
 - #95512 (diagnostics: translation infrastructure)
 - #95607 (Note invariance reason for FnDef types)
 - #95645 (Fix intra doc link ICE when trying to get traits in scope for primitive)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=95234,95449,95512,95607,95645)

### CODE REVIEW

**Comment by nnethercote** [comment]
Terrible perf results for `doc` builds here, and bootstrap time jumped from 675 to 691 seconds. @davidtwco #95512 seems the most likely cause.

**Comment by rylev** [comment]
Going to try to run a perf run on the revert of #95512. We'll see if that turns anything up.

**Comment by davidtwco** [comment]
Unfortunately, I don't think this is too surprising. #95512 adds new dependencies (and dependencies of those dependencies) which will all be adding to our bootstrap time. I don't think there's any easy way to avoid these dependencies though, maybe there's some feature flags I didn't notice for disabling some.

**Comment by rylev** [comment]
Unfortunately, reverting the PR is going to be difficult (it touches a lot of code and quickly becomes unmergeable). I think it's pretty clear that is the cause of the perf regression. For future note, we should really be avoiding rolling up PRs like this.  Still, the regressions are pretty bad. We probably want to prioritize looking into ways to gain back some of the performance lost.

**Comment by davidtwco** [comment]
> Unfortunately, reverting the PR is going to be difficult (it touches a lot of code and quickly becomes unmergeable). I think it's pretty clear that is the cause of the perf regression. For future note, we should really be avoiding rolling up PRs like this. Still, the regressions are pretty bad. We probably want to prioritize looking into ways to gain back some of the performance lost.

I've got some ideas for how to claw back some of the lost performance - I load the translations unconditionally right now but I could probably delay that until we know we're going to be emitting an error, that's probably where the performance loss comes from.

**Pull request merged**
