### PR TITLE
openbsd: add system-libs dependencies to snapshots

### PR DESCRIPTION
**Pull request by semarie**
when building a snapshot for openbsd (with `make snap-stageN`), include
system libraries dependencies, in order to make the snapshot more
portable across openbsd version.

Please note that for consistency with `src/etc/mklldeps.py`, the `libstdc++` used here is the system default one, whereas under openbsd, rust could be build with (it comes from gcc-4.2). This issue will be addressed later, after some dicussion with @dhuseby for see how to deal with (see #28241).

### CODE REVIEW

**Comment by sinistersnare** [comment]
Does this just crash the moment it cant find one dependency? What if we kept a list of missing deps, and then crashed after it finished collecting information?

**Comment by semarie** [comment]
if it don't find a dependency, it shouldn't have been able to compile (or there is some mismatch in paths). I don't think it would be a valuable gain to postpone the error.

Also, the logic is the same as for winnt.

**Comment by sinistersnare** [comment]
Its not that the error should be postponed, its that... for example, if both "libm.so" and "libstdc++.so" were missing, it would crash the moment it cant find libm.so, so i would fix it, then it would crash again complaining about libstdc++.so...

Wouldnt it be better if it just reported both at the same time?

**Comment by semarie** [comment]
I understand your point of vue, but if any of the mentioned file is missing, the build won't success, and snapshot won't be called. The error is more a `panic' than an information for the user.

**Comment by alexcrichton** [comment]
Is this really needed for the libpthread.so, libm.so, and libc.so libraries? Those typically have a very stable ABI so we shouldn't need to vendor them. Snapshots of libstdc++.so are totally plausible, but we actually tend to just link it in statically instead of distributing the dynamic library. The linux builders use `--enable-llvm-static-stdcpp` to achieve this, so perhaps this could do the same?

**Comment by semarie** [comment]
The policy for OpenBSD libraries version is strict: version bump occurs regulary for base library as libpthread, libm or libc and for ports libraries (third-party software). So don't have at runtime the libraries used when building the binary could render the binary useless.

For `--enable-llvm-static-stdcpp`, I will check.

**Comment by alexcrichton** [comment]
I'm pretty dubious that even on OpenBSD the libraries like libc are changing enough that we need to vendor them. Do any other projects on OpenBSD do this sort of vendoring? Is this common elsewhere? Any form of ABI breakage would have to be reflected in our own source as well due to us inlining all header files basically, so I feel that vendoring those libs isn't going to buy us much.

**Comment by semarie** [comment]
You could see http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libc/shlib_version which is the history of the file that control major/minor library version of libc.

- reason to crank major: change on ABI (changing public struct size, function arguments, removing...)
- reason to crank only minor: growing the ABI (adding function, struct, ...)

Speaking of -current version (what a lot of persons use for daily): on 01/01/2015, libc was libc.so.78.0. Today it is libc.81.0. There are a total of 4 changes (3 major + 1 minor). Every major changes would let the snapshot unusable for bootstrapping purpose.

For release, the ABI is stable (OpenBSD is released every 6 months).

**Comment by alexcrichton** [comment]
Let's start out just statically linking the C++ standard library and then we can start bundling these dependencies if it becomes a problem.

**Comment by semarie** [comment]
ok. thanks.

**Pull request closed without merging**
