### PR TITLE
Implement `Clone` only for `Copy` types.

### PR DESCRIPTION
**Pull request by scalexm**
Fixes ICEs encountered in e.g. #28229, no less, no more. I removed the old code as it will still be available in the commit history (or in my own branch).

cc @arielb1 @eddyb 

r? @nikomatsakis

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
Also, did it reach beta? It'd have to be reverted there too if it did.

**Comment by nikomatsakis** [comment]
Well, the PR looks good to me. I'd be ok with landing this (and perhaps reverting it) pending resolution of https://github.com/rust-lang/rfcs/pull/2132 and https://github.com/rust-lang/rfcs/pull/2133. That said, the trait selection code looks overall less clean to me, so that's a downside (although not having to handle `Clone` in MIR shims is of course nice-ish).

**Comment by nikomatsakis** [comment]
I think we can close this due to the RFCs being in FCP.

**Comment by alexcrichton** [comment]
Removing beta nomination as this is closed

**Pull request closed without merging**
