### PR TITLE
Add linker arguments from i686-pc-windows-msvc to LLD too

### PR DESCRIPTION
**Pull request by Zoxc**
cc @ollie27

r? @alexcrichton

### CODE REVIEW

**Comment by joelpalmer** [comment]
Triaged

**Comment by Dylan-DPC** [comment]
@Zoxc any updates?

**Comment by nikomatsakis** [comment]
Closing this pull request as Zoxc is stepping back from compiler development; see rust-lang/team#316.

**Comment by petrochenkov** [comment]
I'll pick this up.

**Comment by petrochenkov** [comment]
Done in https://github.com/rust-lang/rust/pull/71030.

**Pull request closed without merging**
