### PR TITLE
[BETA] Universe leak check

### PR DESCRIPTION
**Pull request by nikomatsakis**
Backport of https://github.com/rust-lang/rust/pull/58592 and #58056 to beta.

### CODE REVIEW

**Comment by pietroalbini** [comment]
Can you rollup all the other [beta-accepted](https://github.com/rust-lang/rust/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+label%3Abeta-nominated+label%3Abeta-accepted) PRs with this one? r=me when you do that

**Comment by Mark-Simulacrum** [comment]
We'll probably roll this up with one or two other backports, so not yet approving this PR.

**Comment by nikomatsakis** [comment]
Not sure if try is a good idea or not, but I know we had talked about crater runs, so might as well get started just in case?

**Comment by Mark-Simulacrum** [comment]
I don't think we want/need a crater run here - the one on master should be sufficient.

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum ok, then this is ready to go, and I leave it to you to decide how/when to merge

**Comment by Centril** [comment]
Let's merge in https://github.com/rust-lang/rust/pull/58649 and https://github.com/rust-lang/rust/pull/58227 first and then backport everything in one PR.

**Pull request closed without merging**
