### PR TITLE
apfloat: improve doc comments

### PR DESCRIPTION
**Pull request by RalfJung**
r? @eddyb @nagisa

### CODE REVIEW

**Comment by eddyb** [comment]
I'd rather not change `rustc_apfloat` directly, but rather upstream it to LLVM and then port it back to `rustc_apfloat`. I need to go through the few changes that were made to `rustc_apfloat` and not reviewed by me, to make sure.

**Comment by RalfJung** [comment]
Submitting patches to LLVM is super painful though. :/
So what do we do with this PR?

**Comment by RalfJung** [comment]
@eddyb so what do we do with this PR now? Just close it? Seems like a waste of a good docs improvement, but then it's not like his took long to write.

**Comment by JohnCSimon** [comment]
hello from triage, 
@RalfJung it seems that you'll just have to close this PR, sorry. 
Thank you.

**Comment by RalfJung** [comment]
I'd like for @eddyb to lay down a plan for how we can improve apfloat when that is needed. AFAIK patches have landed here before without being sync'ed upstream, and AFAIK there is no precedent for making code "read-only" like that in rustc.

Cc @rust-lang/compiler

**Comment by eddyb** [comment]
I'm really not sure how to proceed, there are annoying constraints at odds.
Maybe if we moved this to a separate repo (https://github.com/rust-lang/rust/issues/55993) we could have:
* one branch for the port (where LLVM->Rust backports would go into)
* one branch for the crates.io version, *based* on the other branch, with some other patches on top

**Comment by RalfJung** [comment]
Given that [we have](https://github.com/rust-lang/rust/commit/c3e182cf43aea2c010a1915eb37293a458df2228#diff-c7435c803c369d13aabeb6b8861868dd) landed [doc fixes](https://github.com/rust-lang/rust/commit/190d139f3aa0613a8b639bae742561ff89c8fbc7#diff-c7435c803c369d13aabeb6b8861868dd) for apfloat [before](https://github.com/rust-lang/rust/commit/ee89c088b057affb5bdb96195e107a218b64b1c5#diff-c7435c803c369d13aabeb6b8861868dd), I don't understand why we are stopping now.

**Comment by JohnCSimon** [comment]
Ping from triage

@RalfJung @eddyb This has sat idle for a week ... I'm not sure what to do with this one.

Thanks

**Comment by pnkfelix** [comment]
@RalfJung that may be in part because this PR does not have a team label.

**Comment by nikomatsakis** [comment]
My two cents:

The changes seem good, but @eddyb seemed to feel that it would help @skade in working out licensing issues if we make the most minimal changes we can to these files. I think that's a perfectly good reason to hold off on this PR.

**Comment by skade** [comment]
I think it's okay to land this, if @ralfjung agrees on future relicensing of his effort.

**Comment by RalfJung** [comment]
Sure, I am happy to relicense this particular PR under any license.

**Review by eddyb — APPROVED** [review]

**Pull request merged**
