### PR TITLE
Cleanup librustc mir err codes

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Three things are done in this PR:

 * Sort error codes
 * Uncomment an error code long error explanation (they should **never** be commented)
 * Unify explanations

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can you give rational for sorting the error codes? To be frank, it just seems like an excellent way to cause merge conflicts and is otherwise useless - unless I'm missing something. If we had only a couple error codes it might make more sense but I usually can't fit a single error code explanation on screen at a time, much less see two at once to know that they're sorted.

**Comment by GuillaumeGomez** [comment]
Doesn't have much interest in itself. It's just more "clean". However, if you go through missing error codes like I'm currently doing, it helps a lot because generally the error codes close to the one you're writing have pretty close examples that you can use. All depending on the point of view. :)

**Comment by Mark-Simulacrum** [comment]
r=me with the box syntax removed

**Comment by GuillaumeGomez** [comment]
I couldn't find out how to get the error without the box syntax (which is very strange).

**Comment by Mark-Simulacrum** [comment]
I guess you can technically get it via `vec![10]` because that uses box internally, and I'd probably prefer that (it also generates other error codes though). We just don't have any allocating const fn functions to fall back on which is required to get this error, since we don't support it :)

**Comment by GuillaumeGomez** [comment]
Nicely found! Thanks a lot for the tip!

@bors: r=Mark-Simulacrum

**Comment by Centril** [comment]
This seems to reproduce diffs under `--compare-mode=nll` -- please check that it doesn't or `--bless` otherwise. @bors r-

**Comment by GuillaumeGomez** [comment]
Re-ran the tests so let's r+ it again.

@bors: r=Mark-Simulacrum

**Pull request merged**
