### PR TITLE
Add is_documentation for IPv6

### PR DESCRIPTION
**Pull request by achanda**
This function returns true if the given IPv6 is reserved for
documentation. Also, reject this block in the is_global check

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you elaborate on the rationale for this addition as well? We aren't currently very principled about the query methods we have so I'm largely just curious.

**Comment by achanda** [comment]
RFC 3849 defines this range to be used for documentation only [1]. No end hosts should be assigned addresses in this range. Thus this address can not be a globally routable address. This is how python behaves for this range
```
$ python3
Python 3.5.1 (default, Mar 13 2016, 13:29:57) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipaddress
>>> ip = ipaddress.ip_address('2001:db8::')
>>> ip.is_global
False
>>> ip.is_private
True
```
Please let me know if I should clarify something else.

[1] https://tools.ietf.org/html/rfc3849

**Comment by alexcrichton** [comment]
Seems reasonable to me! Tagging with T-libs just to make sure this comes up during triage.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to merge, thanks @achanda!

@bors: r+ aa22b4e7c86729a51cc19d080fa34bbb77bc9cf9

**Pull request merged**
