### PR TITLE
[libstd_unicode] Upgrade to Unicode 10.0.0

### PR DESCRIPTION
**Pull request by behnam**
Update `libstd_unicode`'s data tables to Unicode 10.0.0, as released on 2017 June 20: http://www.unicode.org/versions/Unicode10.0.0/

### CODE REVIEW

**Comment by jonas-schievink** [comment]
```
// NOTE: The following code was generated by "./unicode.py", do not edit directly
```

**Comment by behnam** [comment]
@jonas-schievink, I ran the script to generate the file. I didn't mention that part because it's obvious.

In https://github.com/rust-lang/rust/pull/42998, I applied the change manually, because running the script also makes this changes. So, we can apply https://github.com/rust-lang/rust/pull/42998 after this one, hopefully, to avoid breaking any instructions, theoretically.

**Comment by behnam** [comment]
CC'ing from file's blame/history: @petrochenkov, @cuviper, @alexcrichton, @SimonSapin

**Comment by jonas-schievink** [comment]
Oh, nevermind then, I thought you'd have to do some changes to the script itself.

**Comment by behnam** [comment]
Yeah, the script always fetches the `latest` version and there's no CLI option to change that. I think we should fix that, so we don't have to upgrade if we don't want to. (We don't keep the text data files in the repo.)

So, is there any reason to keep it as it is, or can I send a PR?

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @behnam!

**Comment by H2CO3** [comment]
Could you please check https://github.com/rust-lang/regex/issues/391 as well. The `regex` crate would benefit from more recent Unicode compatibility as well.

**Comment by cuviper** [comment]
See rust-lang/regex#400 for Unicode 10.0.

**Comment by H2CO3** [comment]
@cuviper Awesome!

**Pull request merged**
