### PR TITLE
 Add aarch64-unknown-netbsd target

### PR DESCRIPTION
**Pull request by jakllsch**
Depends on #53116.

### CODE REVIEW

**Comment by estebank** [comment]
r=me once #53116 has been merged

**Comment by kennytm** [comment]
#53116 has been merged.

**Comment by estebank** [comment]
@bors r+ rollup

@kennytm 👍

**Comment by jakllsch** [comment]
I can rebase this if necessary.

**Comment by jakllsch** [comment]
I haven't been able to test this yet. If I could get a newer libc crate to build against first that'd be awesome.

**Pull request merged**
