### PR TITLE
Bump stage0 compiler

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @pietroalbini (or anyone else)

### CODE REVIEW

**Comment by pietroalbini** [comment]
r=me once CI is green

**Comment by Mark-Simulacrum** [comment]
@bors r=pietroalbini rollup

cc @calebcartwright on the last commit's rustfmt changes, in case they're unexpected

**Comment by calebcartwright** [comment]
Thanks for the ping! Yes they are expected, assuming this repo uses the non-default `version = Two` to pull in formatting improvements

**Comment by Mark-Simulacrum** [comment]
Yes, we do. Sounds good.

**Pull request merged**
