### PR TITLE
Show type for docs slice Chunks

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

r=me once CI pass

**Comment by scottmcm** [comment]
I feel like this should have libs or doc come to a bigger decision about examples on all the adapter types.  Most of them just point to the method on `Iterator` and say "See its documentation for more", which has always seemed fine to me -- following the hyperlink isn't a problem, and is better than copying the documentation since the type is never used in isolation.  (And almost never typed out explicitly, in my experience, especially now that `-> impl Iterator<Item = T>` works.)

If this PR is desirable, it seems like that would imply that there should also be ones for `Cloned`, `Copied`, `Cycle`, `Empty`, `Enumerate`, and more.

**Comment by pickfire** [comment]
@GuillaumeGomez I did mentioned these last time, I thought we started adding examples for structs?

@scottmcm Yes, the link to the original function is still there, I initially don't agree with this when I saw @GuillaumeGomez sending how to create the struct, but then I found @jyn514 sending suggestion on giving explicit type to the struct.

Then I find it useful, since now we know the explicit struct type without digging much given the examples, like `Chunks<char>` here, it may not be as straightforward for a beginner to read the generics signature but this helps me understand a lot.

**Comment by jyn514** [comment]
I think this is better than before - maybe not by a lot, but it makes it more clear what the types are. Iterators are pretty 'magic' when you're new to the language and I think this makes them less mysterious.

> If this PR is desirable, it seems like that would imply that there should also be ones for Cloned, Copied, Cycle, Empty, Enumerate, and more.

Sure, that sounds good to me ;)

**Comment by GuillaumeGomez** [comment]
> @GuillaumeGomez I did mentioned these last time, I thought we started adding examples for structs?

That wasn't my complain. They should have examples. My point was just that maybe there was too much information. Is it really necessary to add type information?

**Comment by pickfire** [comment]
> That wasn't my complain. They should have examples. My point was just that maybe there was too much information. Is it really necessary to add type information?

I find it good such that they can easily understand the additional type system rather than going to read generics and understand it, concrete types certainly is easier to comprehend.

**Comment by crlf0710** [comment]
Triange: It seems this is waiting on team decision? Let me mark it as such.

**Comment by pickfire** [comment]
@GuillaumeGomez Similar patch https://github.com/rust-lang/rust/pull/78776

**Comment by apiraino** [comment]
@crlf0710 any team in particular you are asking for a review? what's the context here?

cc @pickfire

**Comment by pickfire** [comment]
Doc team but I think they are busy.

**Comment by jyn514** [comment]
There is no doc team. The best reviewer for this is probably someone from T-libs.

**Comment by m-ou-se** [comment]
Agreed with [what @scottmcm said](https://github.com/rust-lang/rust/pull/77938#issuecomment-708521923). None of the other iterator adapters have examples in the *type* documentation. The example on this type doesn't really add anything over the link to slice::chunks. The slice::chunks documentation already clearly shows the signature including `Chunks` in the return type, and has a more complete example. I'd like to avoid duplicating documentation and examples over the adapter functions and types. So let's just remove this example and just point people directly to slice::chunks for examples and documentation.

**Comment by pickfire** [comment]
Should I just close this?

**Comment by JohnCSimon** [comment]
Triage:
@pickfire what would you like to do with this PR?

**Pull request closed without merging**
