### PR TITLE
adds dragonflybsd to snapshots.txt

### PR DESCRIPTION
**Pull request by dhuseby**
@alexcrichton please upload the following snapshots when landing this patch:

https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2016-02-17-4d3eebf-dragonfly-x86_64-765bb5820ad406e966ec0ac51c8070b656459b02.tar.bz2

https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2016-02-17-4d3eebf-freebsd-x86_64-395adf223f3f25514c9dffecb524f493c42a0e5d.tar.bz2

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like the freebsd snapshot already exists in that block?

**Comment by dhuseby** [comment]
@alexcrichton doh! let me fix this.

**Comment by dhuseby** [comment]
@alexcrichton fixed and squashed.  this now only adds the dragonfly snapshot.

**Pull request merged**
