### PR TITLE
Extend CSS check to CSS variables

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This PR is a bit big because the first commit is a rewrite of the CSS parser to something a bit simpler which still allows to get easily access to CSS properties name.

The other two are about adding tests and adding the CSS variables check.

This check was missing because we are relying more and more on CSS variables rather than CSS selectors in themes.

r? @notriddle

### CODE REVIEW

**Review by notriddle — CHANGES_REQUESTED** [review]
More generally, I have concerns about producing non-rustdoc-specific warnings from the tool as it's written.

* Good linters have support for localized silencing, like the `#[allow()]` directives in Rust itself. There's none of that here.

* It's also fairly likely, since this parser hasn't really been tested against a production-grade battery of CSS test suite corner cases, that there's bugs in here.

  For example, you can totally include semicolons and curley braces in `url({;}.png)` without quotes. It looks like this parser tokenizes it incorrectly.

As long as it's just scanning for variables and selectors, it's probably *okay*, but if it's going to start producing more broadly-applicable warnings, it becomes more important to minimize false positives.

**Comment by GuillaumeGomez** [comment]
I added them without thinking. Removing them.

**Comment by GuillaumeGomez** [comment]
> It's also fairly likely, since this parser hasn't really been tested against a production-grade battery of CSS test suite corner cases, that there's bugs in here.
>
> For example, you can totally include semicolons and curley braces in url({;}.png) without quotes. It looks like this parser tokenizes it incorrectly.

Yes, bugs are very likely but the goal isn't to support the CSS syntax faithfully so we should be mostly fine on this part. As for why I didn't use an existing CSS parser: either they're way too big (in term of deps) or they provide way too advanced features, making it complicated to just query the information we want. But if you know one that isn't too big and covers just what we need, it'd be perfect!

**Comment by GuillaumeGomez** [comment]
I added an extra handling for parens which fixes the issue you mentioned.

**Review by notriddle — APPROVED** [review]

**Pull request merged**
