### PR TITLE
Reduce monomorphisation bloat in RawVec::allocate_in

### PR DESCRIPTION
**Pull request by GnomedDev**
This outlines logic that is not reliant on `T`, leading to a small drop in llvm-lines that is amplified across large projects with many many Vecs. Tests are performed with fat LTO in release mode. This ironically seems to cause the binary size to go up, one theory is that more inlining is performed around the call, which may improve runtime performance.

| [TTS Bot](https://github.com/Discord-TTS/Bot) | RawVec::allocate_in llvm lines | Binary Size |
|---------|-----------------------------|-------------|
| Before  | 21642                       | 20,540,688  |
| After   | 17256                       | 20,565,064  |

| [T2FanRD](https://github.com/GnomedDev/t2fanrd) | RawVec::allocate_in llvm lines | Binary Size |
|---------|-----------------------------|-------------|
| Before  | 842                         | 630,744     |
| After   | 646                         | 630,768     |

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
So, the perf results are noise (or regressions). The binary size goes up for the test cases you cite (a regression). To me that looks like the motivation for doing this is pretty weak -- llvm-lines aren't necessarily a direct correlation with cost, and even if this reduces the amount of bloat in some initial stage, it makes our code more complicated and seems to either be neutral or regress on other important measurements (e.g. code size and potentially compiler performance).

Do you have data supporting that we should land this change?

**Comment by GnomedDev** [comment]
It seems like my initial assessment that the results were noise was misleading, as the binary size metrics seem to have a lot of positive improvements, but other than that I don't have any hard data. Without a specific test case for Vec's allocation performance, I cannot say if it improves due to inlining. 

@rustbot review

**Comment by Mark-Simulacrum** [comment]
I'm worried by the cycle count regressions consistently for a couple benchmarks (and what looks like beyond the noise range to me). Ignoring our relevance filter, the average cycle count benchmark shows a +0.2% regression as well. It would make sense to me that LLVM has a harder time optimizing with outlined code like this -- the allocation itself becomes less visible -- so I don't think this is the right thing to do unless we have good evidence that's not the case, especially given how critical Vec's performance is.

I don't think the binary size improvements are worth it at this time.

@rustbot author (happy to discuss further but otherwise I'd suggest just closing this. This kind of change is very hard to justify without more performance data that we don't really track today).

**Comment by GnomedDev** [comment]
Okay, thanks for your time reviewing, I'll close now as it doesn't improve the metrics I was looking for (binary size) and doesn't help with runtime performance in a measurable way either.

**Pull request closed without merging**
