### PR TITLE
Wrap EarlyContext::visit_local/visit_expr in with_lint_attrs calls

### PR DESCRIPTION
**Pull request by jonas-schievink**
`LateContext` already does this, looks like this was just forgotten in #29850.

Found while investigating #30326 (but doesn't fix it)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
cc @Kimundi

**Comment by Kimundi** [comment]
Ah, yeah I didn't notice there being another lint visitor. Could you add some tests that show the new code working?

**Comment by jonas-schievink** [comment]
Huh. For some reason, the first 2 `allow`s in this test aren't applied correctly:

```rust
fn main() {
    #[allow(unused_parens)]
    let _ = (9);
    
    let _ = #[allow(unused_parens)] (9);

    // This now works:
    #[allow(unused_parens)]
    {
        let _ = (9);
    }
}
```

Any idea what's going on here? (or is this a separate issue?)

Anyways, I've pushed a test for the last case, in case this *is* a different issue.

**Pull request merged**
