### PR TITLE
Small optimizations in macro derive

### PR DESCRIPTION
**Pull request by JulianKnodt**
Some small memory optimizations in macro derives, removing some allocations.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
Implementation LGTM, queued a perf run, r=me if there's an improvement.

**Comment by JulianKnodt** [comment]
I believe this can only be chocked up to noise; if it's alright I'd like to continue working on this

**Comment by JulianKnodt** [comment]
This should be good, hopefully it has a minor effect?

**Comment by JulianKnodt** [comment]
Hm, I can't make heads or tails of whether this is just noise at this point(which probably means it is noise), but let me know what you think.

**Comment by davidtwco** [comment]
> 
> 
> Hm, I can't make heads or tails of whether this is just noise at this point(which probably means it is noise), but let me know what you think.

I agree, it's hard to say if there's any improvement here. If you have other things that you want to try then feel free to, but we might just need to close this unfortunately.

**Comment by JulianKnodt** [comment]
I'll keep working on it, but will try to avoid perf runs for a bit

**Comment by JulianKnodt** [comment]
I believe this should _certainly_ have some perf impact now, altho it's deviated a bit from the original course of the PR

**Comment by davidtwco** [comment]
Sorry for the delay in getting back to this, @JulianKnodt: I'll trigger another try and perf run, but could you rebase first (I think the try run will fail otherwise)?

**Comment by JulianKnodt** [comment]
No worries, it's the holidays and all, thank you for helping out even w/ me implementing somewhat random optimizations

**Comment by JulianKnodt** [comment]
Let me know what you think of these results, some are p good but it's mixed.
If they're not significant I'll just toss out all the changes

**Comment by davidtwco** [comment]
> 
> 
> Let me know what you think of these results, some are p good but it's mixed.
> If they're not significant I'll just toss out all the changes

The `max-rss` results, while initially promising, are probably just noise (when compared to the last noise run). Unfortunately, I don't think these results are significant. Thanks for taking the time to try make an improvement here though!

**Pull request closed without merging**
