### PR TITLE
Only fetch HIR for naked functions that have the attribute.

### PR DESCRIPTION
**Pull request by cjgillot**

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
Changes look good to me, but this was presumably an attempt to improve perf?

**Comment by davidtwco** [comment]
@cjgillot what's the current status here? is this waiting on anything from me?

**Comment by cjgillot** [comment]
@davidtwco this was initially an attempt to improve perf.  In the end, this is only a simplification without any perf regression, so I think it's still worth being merged.

**Comment by tmiasko** [comment]
Thanks.

@bors r=davidtwco,tmiasko

**Pull request merged**
