### PR TITLE
Update E0191 to the new error format

### PR DESCRIPTION
**Pull request by munyari**
Part of #35233

"r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR!

Please also update the test case that goes along with E0191, so we can make sure the new label gets tested.

**Comment by munyari** [comment]
Will do!

**Comment by munyari** [comment]
And didn't mention that this is #35278

**Comment by munyari** [comment]
@jonathandturner how exactly do I test for the span? Should I add something to `src/test/compile-fail/E0191.rs`?

**Comment by jonathandturner** [comment]
@munyari - yes.  You can see examples by reading the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html) and looking at PRs that have been accepted.

**Comment by munyari** [comment]
Hi @jonathandturner, I've updated the test file but am still getting errors. Specifically, the test `associated-type-projection-ambig-between-bound-and-where-clause` fails, even when I add ``//~| NOTE missing associated type `Color` value`` to the test comments.

**Comment by jonathandturner** [comment]
@munyari - when the test fails, can you copy/paste the error it gives you?

**Comment by munyari** [comment]
Sure.
```
$ python src/bootstrap/bootstrap.py --step check-cfail associated-type-projection-from-multiple-supertraits --stage 1
```

```
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage1 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage1 tool compiletest (x86_64-unknown-linux-gnu)
Check compiletest compile-fail (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 1 test
test [compile-fail] compile-fail/associated-type-projection-from-multiple-supertraits.rs ... FAILED

failures:

---- [compile-fail] compile-fail/associated-type-projection-from-multiple-supertraits.rs stdout ----
	
error: /home/nash/code/rust/src/test/compile-fail/associated-type-projection-from-multiple-supertraits.rs:35: unexpected "note": 'missing associated type `Color` value'

error: 1 unexpected errors found, 0 expected errors not found
status: exit code: 101
command: /home/nash/code/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc /home/nash/code/rust/src/test/compile-fail/associated-type-projection-from-multiple-supertraits.rs -L /home/nash/code/rust/build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json -Z unstable-options -L /home/nash/code/rust/build/x86_64-unknown-linux-gnu/test/compile-fail/associated-type-projection-from-multiple-supertraits.stage1-x86_64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o /home/nash/code/rust/build/x86_64-unknown-linux-gnu/test/compile-fail/associated-type-projection-from-multiple-supertraits.stage1-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/home/nash/code/rust/build/x86_64-unknown-linux-gnu/rust-test-helpers
unexpected errors (from JSON output): [
    Error {
        line_num: 35,
        kind: Some(
            Note
        ),
        msg: "missing associated type `Color` value"
    }
]

thread '[compile-fail] compile-fail/associated-type-projection-from-multiple-supertraits.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:1082
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [compile-fail] compile-fail/associated-type-projection-from-multiple-supertraits.rs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured



command did not execute successfully: "/home/nash/code/rust/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/compiletest" "--compile-lib-path" "/home/nash/code/rust/build/x86_64-unknown-linux-gnu/stage1/lib" "--run-lib-path" "/home/nash/code/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/home/nash/code/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--rustdoc-path" "/home/nash/code/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc" "--src-base" "/home/nash/code/rust/src/test/compile-fail" "--build-base" "/home/nash/code/rust/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage1-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/home/nash/code/rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--host-rustcflags" "-Crpath -O" "--target-rustcflags" "-Crpath -O -Lnative=/home/nash/code/rust/build/x86_64-unknown-linux-gnu/rust-test-helpers" "--docck-python" "python" "--lldb-python" "python" "associated-type-projection-from-multiple-supertraits" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp" "--android-cross-path" ""
expected success, got: exit code: 101
```

**Comment by jonathandturner** [comment]
It looks like there's one more test case that needs to be updated.  Look at:

```
error: /home/nash/code/rust/src/test/compile-fail/associated-type-projection-from-multiple-supertraits.rs:35: unexpected "note": 'missing associated type `Color` value'
```

You can add it the same way you did in file `src/test/compile-fail/E0191.rs`


File `src/test/compile-fail/associated-type-projection-from-multiple-supertraits.rs` on line 35 looks like it needs a NOTE also that says 'missing associated type `Color` value'

**Comment by munyari** [comment]
Sweet! I'd somehow ended up editing the wrong file.

**Comment by munyari** [comment]
Should I squash the commits?

**Comment by jonathandturner** [comment]
@munyari - yes, please squash the commits.

**Comment by munyari** [comment]
@jonathandturner I think this is ready

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Pull request merged**
