### PR TITLE
extract const part of grow_amortized into a constant

### PR DESCRIPTION
**Pull request by lcnr**
we don't yet fold this during mir opts so llvm get's a lot more IR than it needs to, let's see if
this has a positive effect.

### CODE REVIEW

**Comment by jyn514** [comment]
Maybe it's also worth making `        if mem::size_of::<T>() == 0 {` a constant?

**Comment by lcnr** [comment]
Let's first see if this has an effect :thinking: Would be annoying if doing these things manually had a big impact

**Comment by lcnr** [comment]
doesn't look like it improved perf, that makes me somewhat happy :sweat_smile:

**Pull request closed without merging**
