### PR TITLE
Use `rustc_on_unimplemented`'s trait name argument in `try`

### LINKED ISSUE #42694: Error diagnostics for `?` regressed over `try!`
This is a thing that occured to me while giving a training on Rust: the diagnostics of `?` over `try!` are worse, despite it being special syntax.

Compare:

```rust
fn main() {
    
}

try() {
    try!(std::fs::File::open("foo"));
}
```

```


rustc 1.19.0-nightly (258ae6dd9 2017-06-15)
error[E0308]: mismatched types
 --> <anon>:6:5
  |
6 |     try!(std::fs::File::open("foo"));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `std::result::Result`
  |
  = note: expected type `()`
             found type `std::result::Result<_, _>`
  = note: this error originates in a macro outside of the current crate

error: aborting due to previous error(s)
```

over:

```rust
fn main() {
    
}

fn question() {
    std::fs::File::open("foo")?;
}
```

```
rustc 1.19.0-nightly (258ae6dd9 2017-06-15)
error[E0277]: the trait bound `(): std::ops::Try` is not satisfied
 --> <anon>:6:5
  |
6 |     std::fs::File::open("foo")?;
  |     ---------------------------
  |     |
  |     the trait `std::ops::Try` is not implemented for `()`
  |     in this macro invocation
  |
  = note: required by `std::ops::Try::from_error`
```

While the second makes perfect sense to advanced Rust developers, it is confusing to newcomers and leaks a lot of internal details. People have to know about traits, about the `ops` module, and similar. Also, it reports a macro invocation, where - from a user perspective - there is none. To my knowledge, this is the only place where we do this.

Considering that `?` raises a macro to syntax, I would also think it gives opportunity for better diagnostics. It is a crucial part of the language with non-trivial semantics and making a pass on giving better errors here would help newcomers _a lot_.

### PR DESCRIPTION
**Pull request by estebank**
Follow up to #43000 and #43001. Fix #42694.

### CODE REVIEW

**Comment by kennytm** [comment]
Travis failed with:

```
[00:02:28] error[E0230]: there is no type parameter Try on trait Try
[00:02:28]   --> /checkout/src/libcore/ops/try.rs:18:1
[00:02:28]    |
[00:02:28] 18 | / #[rustc_on_unimplemented = "the `?` operator can only be used in a function that returns `Result` \
[00:02:28] 19 | |                             (or another type that implements `{Try}`)"]
[00:02:28]    | |_______________________________________________________________________^
```

This probably needs a `cfg_attr(not(stage0), ...)`.

**Comment by estebank** [comment]
@kennytm @brson, I'm thinking that we should just wait until #43000 is part of the release. It's a minor thing, I feel.

**Comment by arielb1** [comment]
Yeah that will happen the next time we'll have a snapshot, which should be in a ~week or so

**Comment by alexcrichton** [comment]
@estebank I think we've got a new stage0 so this should be ready for a rebase!

**Comment by estebank** [comment]
@alexcrichton This PR is ready for merging.

**Pull request merged**
