### PR TITLE
[beta] backport cargo

### PR DESCRIPTION
**Pull request by weihanglo**
backport cargo `2e4932801996a8799be8648a8858701e1ee8697a` for 1.59.0-beta

- [Beta] backport "Be resilient to most IO error and filesystem loop while walking dirs" 
  https://github.com/rust-lang/cargo/pull/10286

### CODE REVIEW

**Comment by weihanglo** [comment]
I followed this guide: https://forge.rust-lang.org/release/backporting.html#beta-backporting-in-rust-langcargo, but cannot figure out how the channel switch on CI works. 😞

**Comment by ehuss** [comment]
This will need to wait until #92734 merges.  After beta is branched (which was very recent), the release team has to push a PR through to update it before anything else can be merged to the beta branch.  Sometimes that process is a little bumpy, as in this case.  All tools must be functional on the beta branch, but RLS is currently broken.

**Comment by ehuss** [comment]
Looks like #92734 landed, so this should be able to go.

@bors r+ rollup=never

**Comment by weihanglo** [comment]
Should good to go, @ehuss. Take your time. No rush 🙂

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/93010.

**Pull request closed without merging**
