### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #42307, #42385, #42531, #42551
- Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
libstd test failed on i686-pc-windows-msvc. Spurious?

```
thread '<unnamed>' panicked at 'assertion failed: a - Duration::new(0, 100) <= b', src\libstd\time\mod.rs:473
test time::tests::instant_math ... FAILED

failures:
    time::tests::instant_math
test result: FAILED. 787 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out
```

[src/libstd/time/mod.rs:473](https://github.com/rust-lang/rust/blob/9454dd5d2d8786d6eef07e2a7b737ad092e303df/src/libstd/time/mod.rs#L473):

```rust
    #[test]
    fn instant_math() {
        let a = Instant::now();
        let b = Instant::now();
        let dur = b.duration_since(a);
        assert_almost_eq!(b - dur, a);   // <-- line 473
        assert_almost_eq!(a + dur, b);

        let second = Duration::new(1, 0);
        assert_almost_eq!(a - second + second, a);
    }
```

**Comment by frewsxcv** [comment]
Seems that way

@bors retry

**Comment by kennytm** [comment]
i686-pc-windows-gnu this time, spurious, #41006.

```
Testing librustc stage2 (i686-pc-windows-gnu -> i686-pc-windows-gnu)
…
error: failed to remove: C:\projects\rust\build\i686-pc-windows-gnu\stage1-rustc\i686-pc-windows-gnu\release\rustc_trans.dll
Build failed, waiting for other jobs to finish...
error: build failed
```

**Pull request closed without merging**
