### PR TITLE
library: Move unstable API of new_uninit to new features

### PR DESCRIPTION
**Pull request by workingjubilee**
- `new_zeroed` variants move to `new_zeroed_alloc`
- the `write` fn moves to `box_uninit_write`

The remainder will be stabilized in upcoming patches, as it was decided to only stabilize `uninit*` and `assume_init`.

- https://github.com/rust-lang/rust/issues/63291
- https://github.com/rust-lang/rust/issues/129396
- https://github.com/rust-lang/rust/issues/129397

### CODE REVIEW

**Comment by workingjubilee** [comment]
Further extracted from https://github.com/rust-lang/rust/pull/129401 as that PR is now waiting on a Tuesday.

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/129419#issuecomment-2305566108

**Comment by workingjubilee** [comment]
I suppose there isn't a way for Rust-for-Linux to be updated from our repository, huh.

**Comment by workingjubilee** [comment]
@rustbot rfl

Hey, I opened https://github.com/Rust-for-Linux/linux/pull/1106 but if that PR isn't good enough can one of you take over fixing RfL so we can later land the stabilization of the features you want? Thanks.

**Comment by workingjubilee** [comment]
@rustbot ping rfl

Hey, I opened https://github.com/Rust-for-Linux/linux/pull/1106 but if that PR isn't good enough can one of you take over fixing RfL so we can later land the stabilization of the features you want? Thanks.

**Comment by workingjubilee** [comment]
Hey, I opened https://github.com/Rust-for-Linux/linux/pull/1106 but if that PR isn't good enough can one of you take over fixing RfL so we can later land the stabilization of the features you want? Thanks.

@rustbot ping rust-for-linux

**Comment by workingjubilee** [comment]
...Rustbot is being disobedient so

cc @alex @bjorn3 @Darksonn @dingxiangfei2009 @fbq @maurer @metaspace @nbdd0121 @ojeda @tgross35 @vincenzopalazzo @wedsonaf @y86-dev

**Comment by alex** [comment]
I see there's a thread on the RfL side, but I do think this points out the need for a clearer process when rust changes "break" rfl's use of unstable apis. We shouldn't assume rust contributors will be familiar with the kernel contribution process

**Comment by tgross35** [comment]
> I see there's a thread on the RfL side, but I do think this points out the need for a clearer process when rust changes "break" rfl's use of unstable apis. We shouldn't assume rust contributors will be familiar with the kernel contribution process

Agreed to this, I think this is the first case we have encountered it.

> and it seems that RfL _does_ still use PRs, but mostly as a way to borrow the GitHub UI for a slightly less onerous review flow than mailing lists, and then those are routed to the mailing list?

That is accurate; we usually suggest that changes in early stages can go through a GH PR to collect some loose feedback before being sent to the list, but everything needs to go through the list for review and eventually getting picked up. We can of course help wherever needed - helping anyone figure out how to send patches, or forwarding patches for anyone who has a fix but doesn't know mailing list flow, or just doing the fix as needed.

**Comment by Darksonn** [comment]
We have a [Rust for Linux page in the rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/tests/rust-for-linux.html). We should make sure that this link is shared when the job breaks.

**Comment by ojeda** [comment]
> Hey, I opened [Rust-for-Linux/linux#1106](https://github.com/Rust-for-Linux/linux/pull/1106) but if that PR isn't good enough can one of you take over fixing RfL so we can later land the stabilization of the features you want? Thanks.

Thanks!

> I see there's a thread on the RfL side, but I do think this points out the need for a clearer process when rust changes "break" rfl's use of unstable apis. We shouldn't assume rust contributors will be familiar with the kernel contribution process

As far as I understood it from the discussions, the idea was to ping us, i.e. it is not expected that Rust contributors need to get familiar with the kernel or its development process. But, of course, if they want to contribute, that is great!

[1] https://rust-lang.zulipchat.com/#narrow/stream/425075-rust-for-linux/topic/building.20on.20Rust.20CI/near/447162810
[2] https://rustc-dev-guide.rust-lang.org/tests/rust-for-linux.html#what-to-do-in-case-of-failure

**Comment by workingjubilee** [comment]
In general, I do not consult the rustc-dev-guide every time a build breaks. It generally does not change so often that such is useful, and for better or worse, it is rare that a test job is specifically documented inside it.

**Comment by ojeda** [comment]
There is a message at `triagebot.toml`, but I am not sure if that is/was supposed to trigger automatically, and given how it is worded, it sounds like it is a message to the ping group, rather than a message for the PR author.

@Kobzol

**Comment by workingjubilee** [comment]
The ping group didn't even work, so.

**Comment by Kobzol** [comment]
I don't think that we currently have any logic that pings RfL (or any other notification group) in case where some specific CI job fails, that would have to be implemented in triagebot.

Trying if the `rfl` alias works for the ping (if it does, sorry for the notification)

@rustbot ping rfl

**Comment by tgross35** [comment]
I don't know if it is the case here but apparently something in the GitHub UI has been inserting hidden characters around `@` names in messages (or so it seems), which confuses rustbot https://github.com/rust-lang/triagebot/issues/1832

**Comment by ojeda** [comment]
> I don't think that we currently have any logic that pings RfL (or any other notification group) in case where some specific CI job fails, that would have to be implemented in triagebot.

I see, thanks! If something like that ends up being possible, then, to follow the docs/policy and minimize confusion, what would be ideal would be for the bot to write a message targeted to the PR author, saying something like "It seems that this PR broke the ABC job. If this is expected/intentional, please use the following command to ping the XYZ group so that they can take a look: ...".

**Comment by ojeda** [comment]
@workingjubilee For this PR, you can add a commit like this:

```patch
From fbce5b0a1f054fa0f1538fa639883644fb28a965 Mon Sep 17 00:00:00 2001
From: Miguel Ojeda <ojeda@kernel.org>
Date: Fri, 23 Aug 2024 09:28:30 +0200
Subject: [PATCH] CI: rfl: move to temporary commit

Link: https://github.com/rust-lang/rust/pull/129416
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>
---
 src/ci/docker/scripts/rfl-build.sh | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/ci/docker/scripts/rfl-build.sh b/src/ci/docker/scripts/rfl-build.sh
index d690aac27fae..389abb2fdd38 100755
--- a/src/ci/docker/scripts/rfl-build.sh
+++ b/src/ci/docker/scripts/rfl-build.sh
@@ -2,7 +2,7 @@
 
 set -euo pipefail
 
-LINUX_VERSION=v6.11-rc1
+LINUX_VERSION=4c7864e81d8bbd51036dacf92fb0a400e13aaeee
 
 # Build rustc, rustdoc and cargo
 ../x.py build --stage 1 library rustdoc
@@ -28,7 +28,7 @@ rm -rf linux || true
 # Download Linux at a specific commit
 mkdir -p linux
 git -C linux init
-git -C linux remote add origin https://github.com/torvalds/linux.git
+git -C linux remote add origin https://github.com/Rust-for-Linux/linux.git
 git -C linux fetch --depth 1 origin ${LINUX_VERSION}
 git -C linux checkout FETCH_HEAD
 
-- 
2.46.0
```

**Comment by workingjubilee** [comment]
"Open a stabilization PR" is something that people who have never ever contributed to FOSS before, and often only barely know about git, are encouraged to do. I obviously know about formatting and applying patches. But if this is supposed to be something that _you_ fix, without putting additional burden on contributors, then it should probably mean they aren't required to use additional git commands they may have never heard of and have no idea how to. That includes `git am` or `git apply`.

This peculiarly months-dead stabilization issue was brought to my attention because such a programmer (confident with writing Rust, but shy and averse to public interaction with FOSS projects) wanted to use its API in their own project. I briefly tried to encourage them to open the stabilization PR, even knowing it would probably be their first attempt, ever. When they declined, I started in on it, because usually these are essentially effortless, and saw it was irritatingly bureaucratically complicated for Rust issue reasons. And now...

This has required an absurd amount of effort for a stabilization PR. Even the prelude to the actual stabilization is complicated! And if T-libs-api decides to rename the relevant fn to `uninit` and `uninit_slice` (and they probably should, honestly) that will again break the RfL job and require a more invasive patch. All this just to stabilize _something that you want stabilized_.

I will apply this, but I'm glad that I didn't succeed in encouraging someone to be a little bolder, because by now I would have died of embarrassment at putting them through all this trouble! And that's a fucking dismal place to be.

**Comment by nbdd0121** [comment]
I think a part of issue here is the introduce of new feature names here when things get partially stabilized. Would it make sense to rename the feature-to-be-stabilized to a new feature name and then stabilize it, or better, mark it as stable without changing the feature name?

**Comment by workingjubilee** [comment]
> or better, mark it as stable without changing the feature name?

That will not work if half the API is stable and half the API is to be unstable.

**Comment by maurer** [comment]
What if we created a tag on r4l similar to the llvm-main tag on Rust?

We use this tag for keeping Rust up to date with the latest LLVM without necessarily being able to merge changes instantly. When the LLVM+Rust CI breaks, we send up a PR with the fix, tag it with that, and our CI looks for that tag on open PRs, and merges those against current HEAD before proceeding.

If we had e.g. `rustc-main` on the r4l branch, then someone like Jubilee could just open a PR, tag it, and we'd know that we had until the underlying change got to the next stable to get that patch or an equivalent one sent to the list and merged.

Once it's merged into `rust-next` via list, we'd close the PR, and that would stop the Rust CI from auto-applying it.

**Comment by workingjubilee** [comment]
I'm surprised something like the toolstate paradigm (the build is allowed to break but it generates the appropriate notices afterwards, but is not allowed to break in the week before cutting a release) was not used. While we mostly have moved away from it, that's because most of them were things we wanted to always build and ship, really, and could pull in as subtrees.

**Comment by nbdd0121** [comment]
I recall this was discussed and the idea was that you want to know whether RfL's broken before the PR is merged.

**Comment by workingjubilee** [comment]
It feels like the PRs most likely to actually regress RfL are the ones like this one, where the RfL job is not appeased, but rather is silenced. But that's purely a vibe, I have no statistical basis to back that up.

**Comment by workingjubilee** [comment]
Despite my grumbling about having to learn additional git commands, that's more a principle-of-the-thing nattering about the friction here. I would be quite happy if I could simply land commits like this after diffing RfL and generating the patch with `git format-patch`, and then transferring it to the appropriate folder. The RfL CI job could then just apply all the patches in a given folder. That seems both
- instructable
- easy to add to the CI job
- easy to then forward to the mailing list
- easy to add detection of an additional diff to that folder to rustbot (as that already is coded in rustbot), so that it notifies you folks and keeps you abreast of any changes

**Comment by workingjubilee** [comment]
...an in-std use of `new_zeroed`... but only on FreeBSD, oddly enough.
@bors r-

**Pull request merged**
