### PR TITLE
Add targets for HermitCore (https://hermitcore.org) to the Rust compiler and port libstd to it.

### PR DESCRIPTION
**Pull request by ColinFinck**
As a start, the port uses the simplest possible configuration (no jemalloc, abort on panic) and makes use of existing Unix-specific code wherever possible.
It adds targets for x86_64 (current main HermitCore platform) and aarch64 (HermitCore platform under development).

Together with the patches to "liblibc" (https://github.com/rust-lang/libc/pull/1048) and llvm (https://github.com/rust-lang/llvm/pull/122), this enables HermitCore applications to be written in Rust.

### CODE REVIEW

**Comment by ColinFinck** [comment]
This patch is part of a patch series to add HermitCore support to Rust:

1. https://github.com/rust-lang/llvm/pull/122 / https://reviews.llvm.org/D48964
2. https://github.com/rust-lang/libc/pull/1048
3. https://github.com/rust-lang/rust/pull/52861

CC @stlankes

**Comment by alexcrichton** [comment]
Thanks! Looks like there's a tidy error on CI but otherwise this looks good to merge!

**Comment by ColinFinck** [comment]
@alexcrichton Thanks for the prompt reply! I've fixed the coding style.

**Pull request merged**
