### PR TITLE
Rollup of 4 iffy pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #89234 (Disallow non-c-like but "fieldless" ADTs from being casted to integer if they use arbitrary enum discriminant)
 - #91045 (Issue 90702 fix: Stop treating some crate loading failures as fatal errors)
 - #91394 (Bump stage0 compiler)
 - #91411 (Enable svh tests on msvc)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=89234,91045,91394,91411)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Mmh, I would assume we benchmark the stage2 compiler anyway so bootstrap bump should not have a big effect, so probably one of the first two..?

**Comment by rylev** [comment]
@matthiaskrgr for the future, it's usually good to *not* group iffy pull requests into the same PR. It's better to group an iffy PR with other clearly non-performance sensitive PRs so that if a perf regression happens, you can go with the hypothesis that the iffy PR caused the regression. It'll likely be too difficult to figure out the cause of the regression given how small the regression actually is (0.8% is the largest regression in a non-noisy test case). 

@rustbot label: +perf-regression-triaged

**Comment by matthiaskrgr** [comment]
@rylev  isn't that was rollup=never is for?
IMO `iffy` signals that this "might" pass in ci but it is not certain, so if you want a rollup that has high likelyhood of merging, don't include iffy prs.
If a PR is sensitive to perf, it should be marked rollup=never for exactly this reason and make it easier to figure out later on.

**Pull request merged**
