### PR TITLE
Add `html_root_url` to `rustc_hir` crate

### PR DESCRIPTION
**Pull request by pierwill**

### CODE REVIEW

**Comment by pierwill** [comment]
Should we add this attribute to all crates in `compiler/`?

**Comment by oli-obk** [comment]
cc @rust-lang/rustdoc 

What does this attribute change?

**Comment by jyn514** [comment]
This shouldn't be necessary. The only time it's useful is when rustc_hirid is documented as a dependency *and* rustdoc is passed --no-deps, which isn't the case for the docs published on /nightly-rustc.

**Comment by jyn514** [comment]
See also https://github.com/rust-lang/api-guidelines/issues/229.

**Comment by camelid** [comment]
@pierwill what's the reason you want to add this attribute?

**Comment by pierwill** [comment]
In my local setup, it seems this attribute makes it possible to use LSP
commands that open the selected item in external documentation (docs.rs).

**Comment by camelid** [comment]
> In my local setup, it seems this attribute makes it possible to use LSP commands that open the selected item in external documentation (docs.rs).

Hmm, that's weird. Why would adding a doc.rust-lang.org root URL help with docs.rs? That seems like a tooling bug IMO.

**Comment by pierwill** [comment]
> > In my local setup, it seems this attribute makes it possible to use LSP commands that open the selected item in external documentation (docs.rs).
> 
> Hmm, that's weird. Why would adding a doc.rust-lang.org root URL help with docs.rs? That seems like a tooling bug IMO.

Ah sorry. It *does* help with doc.rust-lang.org.

**Comment by camelid** [comment]
Hmm, IMO it still feels like overkill to add this attribute to every crate.

**Comment by Mark-Simulacrum** [comment]
Can you share more about your local setup? In general, it seems like fixing this with attributes in each(?) of the rustc_ crates in-tree is likely not the right approach. Maybe this can be fixed upstream?

It might also be worth asking what is different about these crates vs. other crates you're editing -- maybe they're just unilaterally prefixing with docs.rs without such an attribute? The docs.rs/std redirect to doc.rust-lang.org may be something we could match, there, though I'm a little uncertain about the concept in general (IIRC, there's no actual restrictions on std or rustc_ crates being published to crates.io).

**Comment by camelid** [comment]
> (IIRC, there's no actual restrictions on std or rustc_ crates being published to crates.io).

I think I recall seeing a discussion recently where someone said that `std` is not allowed on crates.io. There's a blocklist somewhere in the crates.io sources.

**Comment by Nemo157** [comment]
There was some previous discussion about having docs.rs do forwarding for the internal rustc crates in https://github.com/rust-lang/docs.rs/issues/79. I wonder whether the LSP implementations parse/use the [`[doc.extern-map]`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#rustdoc-map) section, though I don't know whether it's possible to specify a "local path" registry key in there to give an external location for the local crate's docs.

**Comment by jyn514** [comment]
Relevant code in RA: https://github.com/rust-analyzer/rust-analyzer/blob/4f04d8477a1aac357e137df47f4e1ff277325c89/crates/ide/src/doc_links.rs#L298

I think this is an ok change, but it shouldn't live in the crate proper, which causes lots of churn any time it needs to be updated - can you put it in `impl Step for Rustc` in `src/bootstrap/doc.rs` instead?

**Comment by jyn514** [comment]
Also, if you can mention this bug on the RFC and comment why the RFC helps, that would be *extremely* helpful :)

> // BUG: For Option::Some
// Returns https://doc.rust-lang.org/nightly/core/prelude/v1/enum.Option.html#variant.Some
// Instead of https://doc.rust-lang.org/nightly/core/option/enum.Option.html
//
// This should cease to be a problem if RFC2988 (Stable Rustdoc URLs) is implemented
// https://github.com/rust-lang/rfcs/pull/2988

**Comment by Mark-Simulacrum** [comment]
It basically seems like https://github.com/rust-analyzer/rust-analyzer/blob/4f04d8477a1aac357e137df47f4e1ff277325c89/crates/ide/src/doc_links.rs#L420 could (should?) be expanded to all rustc_ crates, or perhaps some kind of rust-analyzer configuration option added.

I'm OK with adding some kind of once-off mention of the nightly-rustc docs prefix, per-crate changes feel a little excessive to me. At the very least, if we go down that path, we should add a tidy lint requiring them...

In general it feels problematic to expect that this configuration is something that can be guessed by rust-analyzer -- e.g., if I'm developing serde or something locally, I might want rust-analyzer to open cargo doc local docs, not the public ones. So I'd guess that a more holistic answer is needed here eventually even if there's temporarily OK workarounds.

**Comment by matklad** [comment]
Yeah, I feel it's best to just add a configuration option to rust-analyzer to swap our default of `doc.rs` for something else. 

I don't think it makes sense to expand the list at https://github.com/rust-analyzer/rust-analyzer/blob/4f04d8477a1aac357e137df47f4e1ff277325c89/crates/ide/src/doc_links.rs#L420 manually. What that list contains is the *runtime* crates a rust user can get into by clicking goto definition (/library). Things like `rustc_hir` are different, they are completely invisible to the user (/compiler). 

What might have also make sense is some workspace-global Cargo configuration for `html_root_url`, but, even if that's a good idea, it's better and simpler to start with ra-specific config for the same thing.

**Pull request closed without merging**
