### PR TITLE
tidy: exempt URLs from the line length restriction

### PR DESCRIPTION
**Pull request by zackw**
The length of a URL is usually not under our control, and Markdown
provides no way to split a URL in the middle.  Therefore, comment
lines consisting _solely_ of a URL (possibly with a Markdown link
label in front) should be exempt from the line-length restriction.

Inline hyperlink destinations ( `[foo](http://...)` notation ) are
_not_ exempt, because it is my arrogant opinion that long lines of
that type make the source text illegible.

The patch adds dependencies on the `regex` and `lazy_static` crates
to the tidy utility.  This _appears_ to Just Work, but if you would
rather not have that dependency I am willing to provide a hand-written
parser instead.

### CODE REVIEW

**Comment by steveklabnik** [comment]
This LGTM, but yeah, we're _just_ getting to the place where we can use dependencies in places like this, see https://github.com/rust-lang/rust/pull/39728 and https://github.com/rust-lang/rust/pull/39633

/cc @rust-lang/compiler

**Comment by alexcrichton** [comment]
We don't *really* need lazy-static/regex for this, can we just ignore long lines with "http://" and "https://" ?

**Comment by steveklabnik** [comment]
Might need `../` too, maybe. Or we can cross that bridge if and when we come to it.

**Comment by zackw** [comment]
> We don't really need lazy-static/regex for this, can we just ignore long lines with "http://" and "https://" ?

Well, that's essentially what I meant by a "hand-written parser", but I do think we should be a _little_ more picky than just `line.contains("http://") || line.contains("https://")`.  I got tripped up earlier by how permissive the parser for `// ignore-tidy-foo` is; currently style.rs is exempt from all of its own checks because `contents.contains("ignore-tidy-whatever")` matches *itself*!

... So anyway I wrote something, but it may not be the way someone 100% fluent in the language would  write it, please tell me what you think.

**Comment by alexcrichton** [comment]
@bors: r+

Yeah this wasn't really written to be bulletproof, just catch some common mistakes.

**Pull request merged**
