### PR TITLE
Prepare the 1.22.0 beta

### PR DESCRIPTION
**Pull request by alexcrichton**
This updates the Cargo submodule a bit but is otherwise pretty routine.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=100

This is the new beta!

**Comment by kennytm** [comment]
@bors retry #43402 

```
[01:18:21] failures:
[01:18:21] 
[01:18:21] ---- [run-make] run-make\issue-26092 stdout ----
[01:18:21] 	
[01:18:21] error: make failed
[01:18:21] status: exit code: 2
[01:18:21] command: "make"
[01:18:21] stdout:
[01:18:21] ------------------------------------------
[01:18:21] PATH="/c/projects/rust/build/x86_64-pc-windows-gnu/test/run-make/issue-26092.stage2-x86_64-pc-windows-gnu:C:\projects\rust\build\x86_64-pc-windows-gnu\stage2\bin:/c/projects/rust/build/x86_64-pc-windows-gnu/stage0-tools/x86_64-pc-windows-gnu/release/deps:/c/projects/rust/build/x86_64-pc-windows-gnu/stage0-sysroot/lib/rustlib/x86_64-pc-windows-gnu/lib:/c/Program Files (x86)/Inno Setup 5:/c/Python27:/c/projects/rust/mingw64/bin:/usr/bin:/c/Perl/site/bin:/c/Perl/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files/7-Zip:/c/Program Files/Microsoft/Web Platform Installer:/c/Tools/GitVersion:/c/Tools/PsTools:/c/Program Files/Git LFS:/c/Program Files (x86)/Subversion/bin:/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn:/c/Program Files/Microsoft SQL Server/120/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/ManagementStudio:/c/Tools/WebDriver:/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.4:/c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/PrivateAssemblies:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI/wbin:/c/Ruby193/bin:/c/Tools/NUnit/bin:/c/Tools/xUnit:/c/Tools/MSpec:/c/Tools/Coverity/bin:/c/Program Files (x86)/CMake/bin:/c/go/bin:/c/Program Files/Java/jdk1.8.0/bin:/c/Python27:/c/Program Files/nodejs:/c/Program Files (x86)/iojs:/c/Program Files/iojs:/c/Users/appveyor/AppData/Roaming/npm:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/MSBuild/14.0/Bin:/c/Tools/NuGet:/c/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files/Microsoft DNX/Dnvm:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/130/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/c/Program Files (x86)/Apache/Maven/bin:/c/Python27/Scripts:/c/Tools/NUnit3:/c/Program Files/Mercurial:/c/Program Files/LLVM/bin:/c/Program Files/dotnet:/c/Program Files/erl8.3/bin:/c/Tools/curl/bin:/c/Program Files/Amazon/AWSCLI:/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/140:/c/Program Files (x86)/Yarn/bin:/c/Program Files/Git/cmd:/c/Program Files/Git/usr/bin:/c/ProgramData/chocolatey/bin:/c/Tools/vcpkg:/c/Program Files (x86)/nodejs:/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code:/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager:/c/Users/appveyor/AppData/Local/Yarn/bin:/c/Users/appveyor/AppData/Roaming/npm:/c/Program Files/AppVeyor/BuildAgent:/c/projects/rust:/c/projects/rust/handle" 'C:\projects\rust\build\x86_64-pc-windows-gnu\stage2\bin\rustc.exe' --out-dir /c/projects/rust/build/x86_64-pc-windows-gnu/test/run-make/issue-26092.stage2-x86_64-pc-windows-gnu -L /c/projects/rust/build/x86_64-pc-windows-gnu/test/run-make/issue-26092.stage2-x86_64-pc-windows-gnu  -o "" blank.rs 2>&1 | \
[01:18:21] 		grep -i 'No such file or directory'
[01:18:21] 
[01:18:21] ------------------------------------------
[01:18:21] stderr:
[01:18:21] ------------------------------------------
[01:18:21] make: *** [Makefile:4: all] Error 1
[01:18:21] 
[01:18:21] ------------------------------------------
[01:18:21] 
[01:18:21] thread '[run-make] run-make\issue-26092' panicked at 'explicit panic', src\tools\compiletest\src\runtest.rs:2433:8
[01:18:21] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:18:21] 
[01:18:21] 
[01:18:21] failures:
[01:18:21]     [run-make] run-make\issue-26092
[01:18:21] 
[01:18:21] test result: FAILED. 160 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by aidanhs** [comment]
RLS failures?
```
[01:39:18] [m[m[32m[1m   Compiling[m git2-curl v0.7.0
[01:39:20] [m[m[32m[1m   Compiling[m cargo v0.23.0 (file:///checkout/src/tools/cargo)
[01:43:39] [m[m[32m[1m   Compiling[m rls v0.122.0 (file:///checkout/src/tools/rls)
[01:45:56] [m[m[32m[1m    Finished[m release [optimized] target(s) in 471.8 secs
[01:45:56] [m[m[32m[1m     Running[m build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/rls-6bb3c6a77c1f06b8
[01:45:56] 
[01:45:56] running 24 tests
[01:45:56] test actions::test::test_find_word_at_pos ... ok
[01:45:56] test build::cargo::test::test_dedup_flags ... ok
[01:45:56] test server::test_parse_as_notification ... ok
[01:45:57] test test::test_bin_lib_project ... ok
[01:45:57] test test::test_completion ... ok
[01:45:57] test test::test_find_all_refs ... FAILED
[01:45:57] test test::test_find_all_refs_no_cfg_test ... FAILED
[01:45:58] test test::test_goto_def ... FAILED
[01:45:59] test test::test_find_impls ... FAILED
[01:45:59] test test::test_highlight ... FAILED
[01:45:59] test test::test_hover ... FAILED
[01:46:56] test test::test_bin_lib_project_no_cfg_test has been running for over 60 seconds
[01:46:56] test test::test_borrow_error has been running for over 60 seconds
[01:46:58] test test::test_handle_utf8_directory has been running for over 60 seconds
[01:46:59] test test::test_infer_bin has been running for over 60 seconds
[01:51:16] test test::test_bin_lib_project_no_cfg_test ... FAILED
[01:51:16] test test::test_borrow_error ... FAILED
[01:51:18] test test::test_handle_utf8_directory ... FAILED
[01:51:19] test test::test_infer_bin ... FAILED
[01:51:19] test test::test_omit_init_build ... ok
[01:51:19] test test::test_parse_error_on_malformed_input ... ok
[01:51:20] test test::test_reformat ... ok
[01:51:20] test test::test_reformat_with_range ... ok
[01:51:20] test test::test_rename ... FAILED
[01:51:20] test test::test_workspace_symbol ... FAILED
[01:52:16] test test::test_infer_custom_bin has been running for over 60 seconds
[01:52:16] test test::test_infer_lib has been running for over 60 seconds
[01:52:18] test test::test_multiple_binaries has been running for over 60 seconds
[01:56:37] test test::test_infer_lib ... FAILED
[01:56:37] test test::test_infer_custom_bin ... FAILED
[01:56:38] test test::test_multiple_binaries ... FAILED
[01:56:38] 
[01:56:38] failures:
[01:56:38] 
[01:56:38] ---- test::test_find_all_refs stdout ----
[01:56:38] 	expect_messages:
[01:56:38]   results: [
[01:56:38]     "{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":{\"capabilities\":{\"textDocumentSync\":2,\"hoverProvider\":true,\"completionProvider\":{\"resolveProvider\":true,\"triggerCharacters\":[\".\",\":\"]},\"definitionProvider\":true,\"referencesProvider\":true,\"documentHighlightProvider\":true,\"documentSymbolProvider\":true,\"workspaceSymbolProvider\":true,\"codeActionProvider\":true,\"documentFormattingProvider\":true,\"documentRangeFormattingProvider\":false,\"renameProvider\":true,\"executeCommandProvider\":{\"commands\":[\"rls.applySuggestion\"]}}}}",
[01:56:38]     "{\"jsonrpc\":\"2.0\",\"method\":\"rustDocument/beginBuild\",\"params\":null}",
[01:56:38]     "{\"jsonrpc\":\"2.0\",\"method\":\"rustDocument/diagnosticsBegin\",\"params\":null}",
[01:56:38]     "{\"jsonrpc\":\"2.0\",\"method\":\"rustDocument/diagnosticsEnd\",\"params\":null}"
[01:56:38] ],
[01:56:38]   expected: [
[01:56:38]     ExpectedMessage {
[01:56:38]         id: Some(
[01:56:38]             0
[01:56:38]         ),
```

**Comment by alexcrichton** [comment]
@bors: retry

I'm going to pray that's spurious... I can't reproduce locally unfortunately

**Comment by kennytm** [comment]
RLS error again. Legit.

**Comment by alexcrichton** [comment]
@xanewok would you be able to help out here perhaps? I'm not so good at debugging the RLS :(

**Comment by alexcrichton** [comment]
@bors: r+

managed to track it down

**Comment by kennytm** [comment]
I think you need to include #45193.

**Comment by Xanewok** [comment]
@alexcrichton hey, sorry, read the notification just now. What was the cause? Still need help debugging?

**Comment by bgermann** [comment]
The Android SDK update tool was not able to verify the TLS connection to Google's update server. so @kennytm is probably right.

**Comment by alexcrichton** [comment]
@Xanewok ah it turned out that the RLS was rewriting Cargo.lock as it was using a newer version of Cargo, but the Cargo.lock was mounted on a readonly filesystem so that failed. That error then cascaded quite a bit into a bunch of failing test cases.

**Pull request merged**
