### PR TITLE
Add notifications when rust build ends

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @alexcrichton

### CODE REVIEW

**Comment by aidanhs** [comment]
Personally I'd probably prefer this hidden behind a `--notify` flag or something. If not, it definitely needs a way to disable it.

**Comment by GuillaumeGomez** [comment]
@aidanhs: Hum... I'm not sure to understand the issue. Why would you want to disable it?

**Comment by aidanhs** [comment]
It's just a bit obnoxious to get pop-ups every time I run the build system, especially if I'm doing builds with a very fast iteration cycle - I'd run the command and instantly be told about build success, every single time.

I also sometimes the rust build system automatically/non-interactively, and often as part of a larger pipeline of builds - in each of these cases, being told that the rust build is done is not actually of any use to me and is just noise.

Out of curiosity, do any other build systems do this? I've never seen anything like it before in the autotools/scons/cmake etc build systems I've used before, though I have wanted something like it.

**Comment by killercup** [comment]
Interesting. I would not expect a build system to show notifications, as a lot of time it'll run on a headless server. Might be cool to have behind a flag, though.

(Btw, on macOS, the same behavior is just an `brew install terminal-notifier` away: `
bla && terminal-notifier -title Rust -message 👌 ||  terminal-notifier -title Rust -message 💥`.)

**Comment by GuillaumeGomez** [comment]
@aidanhs: I took it from servo.

**Comment by GuillaumeGomez** [comment]
I added the possibility to disable notifications as asked.

**Comment by steveklabnik** [comment]
Yes, I would imagine the only way this can land is a flag that lets you do this, rather than a flag to opt out. This is very unusual.

Honestly, I'm not sure we need this in-tree. You can write a script to do this that wraps an `x.py` invocation and it will still work.

**Comment by est31** [comment]
I know this from servo, and there it has been useful for me.

**Comment by GuillaumeGomez** [comment]
@est31: Same for me. I'll deactivate it by default.

**Comment by alexcrichton** [comment]
This might be best as a `config.toml` option rather than a flag, I suspect that if you want this you always want this.

**Comment by frewsxcv** [comment]
I saw this pull request yesterday and it inspired me to write [alert-after](https://github.com/frewsxcv/alert-after). It allows one to do `aa ./x.py build` and get a notification after `./x.py build` is done. Seems like using a tool like `alert-after` would be a more generic solution instead of having notification logic built-in to each project. Also, it's written in pure Rust! (minus the Objective-C stuffs for macOS things)

**Comment by GuillaumeGomez** [comment]
@alexcrichton: Is there a global `config.toml` file for rust? The only one I found seems to only be an example.

**Comment by est31** [comment]
@GuillaumeGomez the config.toml file is never tracked in git, as its part of the local build config. The example serves as draft you are encouraged to base your config.toml on.

**Comment by alexcrichton** [comment]
@GuillaumeGomez how do you feel about @frewsxcv's [command above](https://github.com/rust-lang/rust/pull/40938#issuecomment-290926341)? That seems like the best solution here to me.

**Comment by petrochenkov** [comment]
I downvoted this not because of the default behaviour, but because of bloating the build system for little reason.
Can this be moved somewhere into a separate file at least, so people trying to read the script and understand the bootstrap are not distracted by 103 lines of bells and whistles (15% of all `bootstrap.py`), that contain no actual build logic.

**Comment by GuillaumeGomez** [comment]
@alexcrichton: For now, @frewsxcv's crate isn't complete yet. Also, adding another external dependency doesn't seem like a good idea to me. It's already heavy enough. I'll instead move the notification code into a separate file as @petrochenkov suggested.

**Comment by GuillaumeGomez** [comment]
I moved notifications into their own files.

**Comment by GuillaumeGomez** [comment]
So now you can also specify if you want the notifications or not in the `config.toml` file. For now, @frewsxcv's crate isn't complete yet (doesn't handle `windows` platform) so I'll need to add it first if I want us to use it in here. I'll try to do it when I have enough time.

@alexcrichton: Does it seem ok to you?

**Comment by alexcrichton** [comment]
With the advent of @frewsxcv's tool I'm personally in favor of leveraging that instead of landing support in our own build system, I'm not personally too thrilled about maintaining this over time.

**Comment by GuillaumeGomez** [comment]
So I have a disagreement in here with @alexcrichton: he'd prefer to keep this as an external tool where I think that we should provide it to make rust developers' life easier.

So now I ask to others as well, what do you think about this PR?

@rust-lang/compiler 
@rust-lang/core 
@rust-lang/docs 
@rust-lang/tools

**Comment by carols10cents** [comment]
iTerm2 on osx has built-in support for setting that you'd like to be notified of any arbitrary command finishing, so I wouldn't have any use for this and it doesn't really seem like something Rust's build system should be responsible for to me.

**Comment by aturon** [comment]
I agree with the sentiments of others on the thread: this isn't something that should be baked into the build system, but rather can be dealt with externally.

**Comment by nrc** [comment]
I just listen for my fans to stop making noise.

In seriousness I agree with others that a bit of `unix philosophy` should be applied here and this is better done in another tool.

**Comment by GuillaumeGomez** [comment]
Majority has spoken! I close this PR then. Thanks for everyone's opinion!

**Pull request closed without merging**
