### PR TITLE
Remove the "leak check" in favor of "universes"

### PR DESCRIPTION
**Pull request by sgrif**
See #48049 and https://gist.github.com/nikomatsakis/87822133b2d85ccac801e08bcb9702de for context. This branch is not yet expected to pass compile-fail or UI tests, nor does it work with NLL. However, it *should* be ready for a crater run. This PR requires #47861.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@bors try

As @sgrif said, we'd like to do a crater run first, and then fix the build failures etc.

**Comment by sgrif** [comment]
I'll fix the merge conflict in the morning

**Comment by shepmaster** [comment]
Ping from triage, @sgrif! We haven't heard from you in a week; perhaps you have moved to a very polar location and "morning" takes a few weeks to occur 😇?

**Comment by nikomatsakis** [comment]
I think @sgrif was waiting to https://github.com/rust-lang/rust/pull/47861 to land... which it has now.

**Comment by nikomatsakis** [comment]
@sgrif 

As noted on gitter, we need to remove the `universe` from `ParamEnv`, now that we it is added into `InferCtxt`.

**Comment by sgrif** [comment]
Yup, was waiting on that (and just had a busy week at work which kept me from having time to work on this). Still on the radar, planning on just deleting all the compile-fail and ui tests that are failing in order to get a crater run going.

**Comment by sgrif** [comment]
@rust-lang/release needs crater

**Comment by pietroalbini** [comment]
Added to the queue (there are 3 other PRs waiting before this one).

**Comment by sgrif** [comment]
@nikomatsakis Can you ask bors for me please :)

**Comment by nikomatsakis** [comment]
@sgrif I would but I see travis is sad

**Comment by aidanhs** [comment]
Just as a passing note - this has no try run so can't be crater run. I've marked it back as waiting on author (merge conflicts will need resolving, tests don't *need* to pass but it's usually a good idea).

**Comment by sgrif** [comment]
This is essentially blocked on #48696. I'm working on a fix

**Comment by shepmaster** [comment]
This has been blocked for a long time and seemingly on a chain of dependencies. There's quite a lot of merge conflicts. Does this PR have any value in its current state?

**Comment by nikomatsakis** [comment]
@shepmaster in its current state no but I think we are more or less at the point where @sgrif can rebase

**Comment by sgrif** [comment]
Yeah, I'm hoping to spend some time on it this week now that #50397 has been pulled out as a subset.

**Comment by sgrif** [comment]
I'm on vacation for a while, so I'm going to close this until I can get it rebased

**Pull request closed without merging**
