### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by tgross35**
Successful merges:

 - #124033 (Sync ar_archive_writer to LLVM 18.1.3)
 - #126699 (Delegation: support coercion for target expression)
 - #126762 (Deny keyword lifetimes pre-expansion)
 - #126967 (Promote the `wasm32-wasip2` target to Tier 2)
 - #127390 (Migrate `raw-dylib-inline-cross-dylib` and `raw-dylib-custom-dlltool` `run-make` tests to rmake)
 - #127501 (Invert infer `error_reporting` mod struture)
 - #127816 (Update method name to reflect changes to its internals)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=124033,126699,126762,126967,127390,127501,127816)

### CODE REVIEW

**Comment by tgross35** [comment]
x86_64-apple-1 has been running for 45 minutes longer than its usual, unfortunately seems stuck running some data structure tests:

```
       Running unittests src/lib.rs (build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/release/deps/rustc_data_structures-44d26cb07006d43d)
  
  running 104 tests
  test base_n::tests::limits ... ok
  test binary_search_util::tests::binary_search_slice_test ... ok
  test fingerprint::tests::combine_commutative_is_order_independent ... ok
```

@bors cancel

**Comment by tgross35** [comment]
Timing! Well, good thing bors ignored me 😆

**Comment by Kobzol** [comment]
This PR made the bootstrap benchmark 70s slower.

**Comment by tgross35** [comment]
I guess it has to be https://github.com/rust-lang/rust/pull/126967/commits/2a3e22bf04b41c6116cb1e29ab7d8daeed8e63db#diff-dc86e288bcf7b3ca3f8c127d3568fbafc785704883bc7fc336bd185910aed5da. Could that install be lazy?

**Pull request merged**
