### PR TITLE
Add missing stability attributes on struct fields.

### PR DESCRIPTION
**Pull request by huonw**
Unstable is the conservative choice.

cc #22950.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm, shouldn't this stability level be inherited from the crate itself? That may be a bug though, I'm fine with this for now

@bors: r+ b0e7c58

**Comment by huonw** [comment]
@alexcrichton I thought that stabilities are supposed to inherit only from the parent, which in this case is the `struct`?

**Comment by alexcrichton** [comment]
The `#[stable]` level does not inherit, but all over levels are inherited. So in this case I would expect to inherit the `#[unstable]` directive from the top of libcore.

**Comment by huonw** [comment]
Oh, I didn't realise that the inheritance just ignored `stable` entirely, I thought it just became an error to have unmarked children inside `stable` things. I guess that explains why the structs in std needed annotations in #22803.

**Pull request merged**
