### PR TITLE
Document `adt_const_params` feature in Unstable Book

### PR DESCRIPTION
**Pull request by Shadlock0133**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
r? rust-lang/compiler

**Comment by BoxyUwU** [comment]
there's already an entry for this with underscores instead of hyphens, but its pretty empty :sweat_smile:

**Comment by Dylan-DPC** [comment]
r? compiler-errors

**Comment by matthiaskrgr** [comment]
@bors r- failed in 
https://github.com/rust-lang/rust/pull/120977#issuecomment-1939153423
https://github.com/rust-lang/rust/actions/runs/7874596749/job/21484572859#step:26:6143

**Comment by BoxyUwU** [comment]
we already ahve an entry for adt_const_params iirc

**Comment by compiler-errors** [comment]
@BoxyUwU: I cannot find it.

**Comment by BoxyUwU** [comment]
https://doc.rust-lang.org/unstable-book/language-features/adt-const-params.html (?) unless im misunderstanding waht this PR does

**Pull request merged**
