### PR TITLE
update nomicon

### PR DESCRIPTION
**Pull request by RalfJung**
Will this trigger a website update automatically or is that a separate step?

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Yes, this'll update the nightly docs with the next nightly release.

**Comment by RalfJung** [comment]
Note that I had to update `travis.yml` to pin an older version of mdbook in the nomicon to make CI pass, will this be picked up here or will it still use the latest mdbook?

See https://github.com/rust-lang-nursery/mdBook/issues/724

**Comment by steveklabnik** [comment]
The rust build process is pinned to the same version you sent in to the
nomicon; I checked before merging :)

**Comment by RalfJung** [comment]
Ah, and as @kennytm pointed out bootstrap just walks all `*.md` files and [tests those with rustdoc directly](https://github.com/rust-lang/rust/blob/master/src/bootstrap/test.rs#L1382).

**Pull request merged**
