### PR TITLE
Sort diagnostics by custom span

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @estebank 

Split out from https://github.com/rust-lang/rust/pull/58281

### CODE REVIEW

**Comment by estebank** [comment]
Shouldn't you also account for `sort_span` when creating sub diagnostics too?

Could we add a single usage and a test that is affected by this?

Other than that, r=me.

**Comment by joelpalmer** [comment]
Ping from Triage: Hi @mark-i-m, any updates?

**Comment by mark-i-m** [comment]
I'm unlikely to get to this better the weekend. Feel free to close if you want. I can reopen later.

**Comment by JohnCSimon** [comment]
Hello from triage
@mark-i-m Closing this as inactive - go ahead and reopen when you have time. Thanks!

**Pull request closed without merging**
