### PR TITLE
Unchecked div/rem no longer generic

### PR DESCRIPTION
**Pull request by strega-nil**
Now they are `[ui](8|16|32|64)_unchecked_(div|rem)`

This is more in line with the other mathematical intrinsics, and means you can't, for example, call `unchecked_sdiv((),())` anymore.

### CODE REVIEW

**Comment by GBGamer** [comment]
I'd also like to change `overflowing_(add|sub|mul)` to be non-generic if possible.

**Comment by nagisa** [comment]
Rather than this, I’d prefer intrinsics checked their specialisation instead. Similarly to the SSE intrinsics code. See [this](https://play.rust-lang.org/?gist=dcab1fd75a18182026fb&version=nightly) which results in [E511](https://doc.rust-lang.org/error-index.html#E0511)

**Comment by alexcrichton** [comment]
I would also kinda tend to err on the side of ease of implementation of intrinsics, but @GBGamer I'm curious was there a use case other than bad monomorphizations which motivated this?

**Comment by GBGamer** [comment]
@alexcrichton because it's really ugly. `unchecked_udiv<T>(T, T) -> T` says "Hey, I'm valid for all T, so pass anything to me." when really, it's exclusively for the integer types. It's not meant for anything else.

**Comment by huonw** [comment]
Intrinsics are regarded as things that should essentially never be called directly: just once for each type, to build up safe abstractions. I.e. inaccuracies in their type signatures aren't thought to be the end of the world.

**Comment by GBGamer** [comment]
@huonw: that may be true, that doesn't mean it doesn't bother me :P.

However, I think that switching to the `simd_add<T>` version would be good. Then we don't have to worry about an LLVM error popping up in rust code, and there's no bloat. Actually, this might be good for all of the other intrinsics that are currently `T_function`, like `u8_mul_with_overflow` and friends.

**Comment by GBGamer** [comment]
@huonw The issue I have is this:

```rust
#![feature(core_intrinsics)]
fn main() {
    unsafe { std::intrinsics::unchecked_sdiv((),()); }
}
```

ends up spitting out

```
/Constants.cpp:1898: static llvm::Constant* llvm::ConstantExpr::get(unsigned int, llvm::Constant*, llvm::Constant*, unsigned int, llvm::Type*): Assertion `C1->getType()->isIntOrIntVectorTy() && "Tried to create an arithmetic operation on a non-arithmetic type!"' failed.
Aborted (core dumped)
```

**Comment by huonw** [comment]
Sure, I'm all for "last minute" (i.e. like `simd_add`) checks to avoid LLVM asserts like that.

**Comment by GBGamer** [comment]
I've an idea. One sec, let me try something.

**Pull request closed without merging**
