### PR TITLE
Update clippy and rls

### PR DESCRIPTION
**Pull request by tesuji**
r? @oli-obk cc @Manishearth

### CODE REVIEW

**Comment by lzutao** [comment]
```
2019-09-19T18:22:41.3307957Z The state of "clippy-driver" has changed from "build-fail" to "test-pass"
2019-09-19T18:22:41.3308802Z The state of "rls" has changed from "test-pass" to "build-fail"
2019-09-19T18:22:41.3416512Z The state of "rls" has regressed from "test-pass" to "build-fail"
```
cc @Xanewok

**Comment by mati865** [comment]
^^
```
2019-09-19T18:06:26.4266026Z error[E0433]: failed to resolve: could not find `rustc_driver` in `self`
2019-09-19T18:06:26.4266525Z --> src/tools/rls/rls-rustc/src/clippy.rs:52:15
2019-09-19T18:06:26.4266824Z |
2019-09-19T18:06:26.4268557Z 52 | use self::rustc_driver::plugin::registry::Registry;
2019-09-19T18:06:26.4269338Z | ^^^^^^^^^^^^ could not find `rustc_driver` in `self`
```
I think it was not found during RLS update because this code is guarded by `#[cfg(feature = "clippy")]` and `clippy` feature was disabled because Clippy didn't build.

**Comment by msizanoen1** [comment]
rust-lang/rls#1556 has been merged. You may want to update RLS too.

**Comment by lzutao** [comment]
Done. Thanks @msizanoen1. Ping @oli-obk

**Comment by oli-obk** [comment]
Please investigate why we now have two pulldown versions and deduplicate them by using the newer one everywhere

**Comment by lzutao** [comment]
Clippy have just updated pulldown-cmark. We need mdbook updated too.

**Comment by lzutao** [comment]
Include https://github.com/rust-lang/rust-clippy/pull/4565 . Ping @oli-obk

**Pull request merged**
