### PR TITLE
cherry-pick of PR #24553 to [beta]

### PR DESCRIPTION
**Pull request by pnkfelix**
This PR is a cherry-pick of PR #24553, which has gone through the beta-nomination and beta-acceptance process. (It just missed being part of the mass cherry-pick in #24708 because I had not yet reviewed it at that time.)

It should not be marked with the usual bors commands (i.e. no "r+" messages to at-bors); it instead will be merged manually after I had double checked that it builds locally.

### CODE REVIEW

**Comment by pnkfelix** [comment]
(I have no idea why this is marked as "safe to merge" by github while #24941 and #24942 were marked as "unable to be merged"; I still suspect it has something to do with my ill-advised attempt do a "try" with at-bors.)

**Comment by pnkfelix** [comment]
this does indeed build locally.  once it is merged, someone (e.g. me) will need to do the final step of removing the "beta-nominated" tag from PR #24553.  (Just writing down the formal process as a reminder, since it is still so new.)

**Comment by alexcrichton** [comment]
Yay!

**Comment by alexcrichton** [comment]
I also went ahead and removed the beta-nominated tag from #24553

**Pull request merged**
