### PR TITLE
 Store const_eval_raw results to disk

### PR DESCRIPTION
**Pull request by Zoxc**
Based on https://github.com/rust-lang/rust/pull/59722.

r? @oli-obk

### CODE REVIEW

**Comment by Zoxc** [comment]
@oli-obk Do you know why we only store const eval results which does not result in an error?

**Comment by oli-obk** [comment]
> Do you know why we only store const eval results which does not result in an error?

I don't remember. I think I just kept the status quo alive and assumed there's a reason.

**Comment by oli-obk** [comment]
We do need this for statics, because `const_eval` will validate statics, and statics can be mutually recursive. So we call `const_eval_raw` to not run validation during const eval.

This will increase the amount of cached data, potentially by very large amounts. Every constant that has a trivial representation via `ConstValue::Scalar` will now require a full allocation to be cached to disk.

But I think I can design a perf test that shows that this PR is a perf improvement, but I'm not sure if its worth it to include it. Essentially it should be

```rust
// lib.rs of crate `foo`
static FOO: u32 = 42; // do some very complex static computation here
```

```rust
// main.rs of crate `foo`
static BAR: u32 = *&foo::FOO + 1;
```

Because reading from a static via an indirection will trigger https://github.com/rust-lang/rust/blob/7e08576e4276a97b523c25bfd196d419c39c7b87/src/librustc_mir/interpret/memory.rs#L394

The only other uses are const evaluation of `const fn` with promoteds: https://github.com/rust-lang/rust/blob/7e08576e4276a97b523c25bfd196d419c39c7b87/src/librustc_mir/interpret/place.rs#L564

Ok, I just found one use that is odd: https://github.com/rust-lang/rust/blob/d3e2cec29225a46298ec4ebf082f34ebd7cfeecf/src/librustc_mir/interpret/operand.rs#L525 introduced in https://github.com/rust-lang/rust/commit/ba82f54b04f429d29b0d7c5aebbae2addd5669fd @RalfJung 	since we only need an operand here, could we do the recursive thing again and use `const_eval` and call `const_to_op` instead of using `const_eval_raw`.

Then we could cache `const_eval_raw` only for promoteds and statics, although we could consider having promoteds go thorough the `const_eval` path, too.

**Comment by RalfJung** [comment]
I did that because (a) converting a `ConstValue` back to an `Operand` is very messy, because `ConstValue` is really optimized for whatever the rest of the compiler needs, and I had hoped that we will eventually just kill the function in `const_eval.rs` that performs this conversion and the world will be a better place, and (b) I prefer to consistently use the same query for the constants/statics we encounter during evaluation.

**Comment by RalfJung** [comment]
Ah, turns out that messy `ConstValue`-to-op code is in that same function `eval_const_to_op`. ;) So I guess we cannot avoid that mess. :/

The argument about consistency remains though, and also I'd expect a performance cost from doing validation there when it is not needed?

Why is this call not a problem? That one cannot be replaced. Right now all "recursive" const eval goes through `InterpCtx::const_eval_raw` and that's nice.
https://github.com/rust-lang/rust/blob/d3e2cec29225a46298ec4ebf082f34ebd7cfeecf/src/librustc_mir/interpret/place.rs#L564

**Comment by oli-obk** [comment]
> I'd expect a performance cost from doing validation there when it is not needed?

That cost will be paid anyway once `const_eval` is called (which it is for all constants)

> So I guess we cannot avoid that mess. :/

We could avoid it if we removed `ConstValue::Scalar` and `ConstValue::Slice`, but that has a performance regression (I tried it once)

The reason I want to remove it is so that we don't store the `Allocation` of a trivial constant in metadata when we start caching `const_eval_raw`

**Comment by RalfJung** [comment]
> That cost will be paid anyway once const_eval is called (which it is for all constants)

Well, except for generic consts (once they exist). But I get what you are saying.

> The reason I want to remove it is so that we don't store the Allocation of a trivial constant in metadata when we start caching const_eval_raw

Remove what? I don't understand how that is connected to replacing one of three places where the interpreter calls `const_eval_raw`, with `const_eval`.

**Comment by oli-obk** [comment]
> why doing something else sometimes should be of any help.

If we only cache `const_eval_raw` calls for statics and promoteds, but we keep calling it for constants, then downstream crates will recompute those constants instead of fetching them from the cache. So if we use `const_eval` for constants, we only need to cache `const_eval`, which we already do.

**Comment by RalfJung** [comment]
> If we only cache const_eval_raw calls for statics and promoteds, but we keep calling it for constants, then downstream crates will recompute those constants instead of fetching them from the cache. So if we use const_eval for constants, we only need to cache const_eval, which we already do.

So you want to reliably use const_eval_raw for statics/promoteds, but const_eval for constants? I see. I don't like this lack of uniformity, but at least it's not entirely arbitrary -- and I guess there's always some price to pay for performance.

Do you think we can set things up in a way such that if we ever get it wrong, we get an ICE? That would put me more at ease with this scheme.

**Comment by Zoxc** [comment]
@rust-timer build a60befa583852dee37603e3bd00fd04ff2870b54

**Pull request closed without merging**
