### PR TITLE
Check for opaque types behind projections

### LINKED ISSUE #99840: TAIT: it's possible to impl a trait for a tait by using projections
```rust
#![feature(type_alias_impl_trait)]
type Alias = impl Sized;

fn constrain() -> Alias {
    1i32
}

trait HideIt {
    type Assoc;
}

impl HideIt for () {
    type Assoc = Alias;
}

pub trait Yay {}

impl Yay for <() as HideIt>::Assoc {}
// impl Yay for i32 {} // this errors
// impl Yay for u32 {} // this also errors
```
As coherence checking keeps opaque types opaque this should not be unsound. Considering that a direct impl for opaque types is forbidden, this is an inconsistency we should resolve though.

cc @oli-obk

### PR DESCRIPTION
**Pull request by oli-obk**
Fixes #99840

I still dislike how fragile this is, but integrating into the regular orphan check doesn't really make sense either, it's not about orphan checking at all.

r? @lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
that approach doesn't work i think, consider
```rust
#![feature(type_alias_impl_trait)]
trait Foo {
    type Assoc;
}

impl Foo for i32 {
    type Assoc = u32;
}
type ImplTrait = impl Sized;
fn constrain() -> ImplTrait {
    1u64
}
impl Foo for i64 {
    type Assoc = ImplTrait;
}

trait Bar<T> {}

impl<T: Foo> Bar<<T as Foo>::Assoc> for T {}
```
i don't think we can avoid opaque types during coherence. I think we should allow them but treat them as opaque so that they block impls for any other type which i added to https://github.com/rust-lang/rust/issues/99840#issuecomment-1198192759 as an edit :grin:

**Comment by lcnr** [comment]
for #76202 we have to not return a `SimplifiedType` for opaque types in impls so that they're added to `blanket_impls`.

not sure about #86411 but it seems fixable and #84660 is caused by opaque types not being considered "opaque enough" i think

**Comment by lqd** [comment]
if this approach is not going to work or land soon, should we revert #99383 in the meantime ?

**Comment by oli-obk** [comment]
> if this approach is not going to work or land soon, should we revert #99383 in the meantime ?

No, this is all behind feature gates, so we're not going to affect stable code.

**Pull request closed without merging**
