### PR TITLE
Faster submodule updating

### PR DESCRIPTION
**Pull request by Zoxc**
For the common case when there are no submodules which need updating, this takes 0.48 seconds instead of 47 seconds.

r? @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
What is the tradeoff here? That we won't clean out submodules if they have untracked files?

**Comment by Zoxc** [comment]
Yeah, they won't get cleaned by default, only when the submodule commit is outdated and the submodule updates.

**Comment by Mark-Simulacrum** [comment]
That seems fine to me. I'm generally okay with this change then.

**Comment by alexcrichton** [comment]
@bors: r+ rollup

Nice!

**Comment by SimonSapin** [comment]
I’m late to the party, but another reason to support this change: I was once surprised (and annoyed) to see the build system silently erase uncommitted local changes that I had just made to a submodule. Fortunately I still had those files open in my text editor, but silent data loss is really not good.

**Comment by Zoxc** [comment]
@SimonSapin That can still happen though if you pull master and the submodule was updated.

**Pull request merged**
