### PR TITLE
Use `Symbol` more in lint APIs

### PR DESCRIPTION
**Pull request by oli-obk**
r? @nnethercote 

This will cause clippy breakage, but super trivial to fix since we can then remove the hacky `match_def_path` function that I added and go back to calling rustc's `match_def_path` method.

### CODE REVIEW

**Comment by nnethercote** [comment]
@bors r+

But we need to coordinate... I'm working on more `Symbol` changes, e.g. #60815. I'm doing some ad hoc profiling to work out which ones are likely to affect performance. If we have multiple people doing these conversions there's a good chance there will be overlap.

**Comment by oli-obk** [comment]
Yes, I tried not to touch anything else out of that reason. I did this just to remove hacks from clippy

**Comment by Centril** [comment]
Toolstate breakage in https://github.com/rust-lang/rust/pull/60859#issuecomment-492812627, @bors r-

**Pull request merged**
