### PR TITLE
Make all proc-macro back-compat lints deny-by-default

### PR DESCRIPTION
**Pull request by Aaron1011**
The affected crates have had plenty of time to update.
By keeping these as lints rather than making them hard errors,
we ensure that downstream crates will still be able to compile,
even if they transitive depend on broken versions of the affected
crates.

This should hopefully discourage anyone from writing any
new code which relies on the backwards-compatibility behavior.

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

**Comment by Aaron1011** [comment]
@craterbot run mode=check crates=https://crater-reports.s3.amazonaws.com/pr-88041/retry-regressed-list.txt

**Comment by Aaron1011** [comment]
@craterbot run mode=check crates=https://crater-reports.s3.amazonaws.com/pr-88041/retry-regressed-list.txt

**Comment by Aaron1011** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-88041/retry-regressed-list.txt

**Comment by wesleywiser** [comment]
Nominating for the lang team to decide if we can make these lints deny-by-default.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

The impact of moving these lints to Deny seems to be minimal -- relatively few crates are affected, and of course (due to cap-lints) they will keep working for the time being.

**Comment by pnkfelix** [comment]
Out of curiosity, what percentage of the failing crates are using the `procedural-masquerade` crate?

**Review by wesleywiser — APPROVED** [review]

**Comment by jyn514** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/89994#issuecomment-945216978

**Pull request merged**
