### PR TITLE
Group all ABI tests.

### LINKED ISSUE #62401: Group all ABI tests.
There are a bunch of run-pass tests that should be in `run-pass/abi` (or some other directory if anyone has a better suggestion), and many of them are mentioned here: https://github.com/rust-lang/rust/blob/baab1914ec9a9742776a8147780947b48fddf54d/src/test/run-pass/abi-sysv64-arg-passing.rs#L7-L23
You can also look for tests that mention `rust_test_helpers` - most of the functions from that C library are used to test ABIs.

cc @nagisa @rkruppe

This issue has been assigned to @kper via [this comment](https://github.com/rust-lang/rust/issues/62401#issuecomment-509506173).

### PR DESCRIPTION
**Pull request by kper**
r? @eddyb

Closes #62401

### CODE REVIEW

**Comment by eddyb** [comment]
@kper You can write "r? @eddyb" in the PR description to make me the reviewer btw (instead of getting one randomly assigned).

**Comment by eddyb** [comment]
Heh GitHub is showing this as `-0 +0` because files were moved without being changed.

**Comment by eddyb** [comment]
@kper I think I wouldn't move all of those tests, specifically not the ones in their own sub-directories (like `rfcs/`), other than `issues/`.

Other than that, this seems good.

**Comment by kper** [comment]
@eddyb Most of the files I moved are in subdirectories. So should I move them all back or just `rfcs`? :)

**Comment by eddyb** [comment]
Hmm, I'm less sure now. Let's see what other @rust-lang/compiler people think.

**Comment by nikomatsakis** [comment]
Always a challenge!

I think I would keep things that are grouped under RFCs specifically -- are there any? -- but I think tests in generic sounding directories like `struct` or `union` would be better off moving into `abi` (as well as `run-pass`).

Going forward, I want some kind of tagging system where we can include keywords, so that we have a "primary organization" which is oriented around RFCs (or, more generally, *stabilization units*), I think, but a "secondary organization" for more general categories. 

Although, writing this out, it makes me wonder if the primary organization should rather be the "language area" or something, with tags being used to record things related to a particular stabilization unit. Well, either way. =) The bottom line is that no one hierarchy is best...

**Comment by JohnCSimon** [comment]
@rust-lang/compiler @nikomatsakis @kper 
Hello from triage - This PR has sat idle for over half a month and is waiting on a review.

**Comment by ProgrammaticNajel** [comment]
Ping from triage. @eddyb any updates on this? cc @rust-lang/compiler

**Comment by Centril** [comment]
@kper We recently moved things out from the `test/run-pass/` folder into `test/ui/` -- could you please rebase and force-push so that we can be sure the diff is still OK?

**Comment by nikomatsakis** [comment]
r? @Centril 

since he seems more up to date than I am =)

**Comment by kper** [comment]
@Centril ok, rebased. But the `abi` tests are both duplicated in `run-pass` and `ui` now.

**Comment by Centril** [comment]
@kper Alright, thank you. You'll need to do the same reorganization in the `src/test/ui/` directory instead. Hopefully it will take less time now that you know what files to move where. Also, no files should be added to `src/test/run-pass` since that directory is untested.

**Comment by kper** [comment]
@Centril ok, I reorganized it again. This time, I did not touch `rfcs` and `issues`.

**Comment by Centril** [comment]
I'm also conflicted like Niko re. `statics/` and similar but ultimately this seems like the better organization for all files moved here. I do agree we need a better categorization and tagging system!

@bors r+

**Comment by kper** [comment]
@Centril because `proc-macro` was split up into normal and `abi` test, each requires this `auxiliary/test_macros.rs` file. I just copied the file to copied the file to `abi/proc-macro/auxiliary/test_macros.rs`. Is this ok?

**Comment by Centril** [comment]
I think so yeah.

**Comment by petrochenkov** [comment]
The macro tests are not about ABI at all, I'm going to move them back into their old place.

**Pull request merged**
