### PR TITLE
Add #[unstable] to HashState and DefaultState

### LINKED ISSUE #21883: "there is no way to use this feature" for std::collections::hash_state::DefaultState
Upgrading Servo is blocked on this. Is there a work around?

```
/home/simon/projects/servo/components/util/cache.rs:29:45: 29:57 error: use of unmarked library feature
/home/simon/projects/servo/components/util/cache.rs:29           entries: HashMap::with_hash_state(DefaultState),
                                                                                                   ^~~~~~~~~~~~
/home/simon/projects/servo/components/util/cache.rs:29:45: 29:57 note: this is either a bug in the library you are using or a bug in the compiler - there is no way to use this feature
/home/simon/projects/servo/components/util/cache.rs:29           entries: HashMap::with_hash_state(DefaultState),
                                                                                                   ^~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by Manishearth**
Fixed #21883 

r? @Gankro

### CODE REVIEW

**Comment by Manishearth** [comment]
Oops, already fixed in #21745

**Comment by Gankro** [comment]
So... wait... this can be closed...?

**Comment by sinistersnare** [comment]
Yes, that merged PR contains the same content as this.

**Comment by Manishearth** [comment]
Forgot to close it, sorry

**Pull request closed without merging**
