### PR TITLE
Make `EvalCtxt` generic over `InferCtxtLike`

### PR DESCRIPTION
**Pull request by compiler-errors**
...but don't change any of the impls, yet! These can get uplifted as we add more methods to `InferCtxtLike`/`Interner` :3

This is built on top of #125230.

r? lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
:3

r=me after https://github.com/rust-lang/rust/pull/125230 landed, the last 2 commits lgtm

**Comment by lcnr** [comment]
please update the PR name though, you go `lifetime -> ty`

**Comment by compiler-errors** [comment]
Might just wait to see if we can merge the `SearchGraph` changes sooner, but will probably merge by end of week if not, so I can start actually making the impls generic too.

**Comment by lcnr** [comment]
> Might just wait to see if we can merge the `SearchGraph` changes sooner, but will probably merge by end of week if not, so I can start actually making the impls generic too.

I would merge it without waiting for #125167. Rebasing over this PR is pretty straightforward

**Comment by compiler-errors** [comment]
OK let me rebase then

**Pull request merged**
