### PR TITLE
Rollup of 3 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #112487 (Update documentation for `tools` defaults)
 - #112513 (Dont compute `opt_suggest_box_span` span for TAIT)
 - #112528 (bootstrap: Don't override `debuginfo-level = 1` to mean `line-tables-only`)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=112487,112513,112528)

### CODE REVIEW

**Comment by Kobzol** [comment]
@rust-timer build https://github.com/rust-lang-ci/rust/commit/9959cdf35accd1b07fb2ac74635e10de483ec3a4

**Comment by lqd** [comment]
It's likely to be the #112528 partial revert indeed, as the initial PR had unexpected wins by seeping through libstd IIRC https://github.com/rust-lang/rust/pull/110221#issuecomment-1576648641

**Comment by pnkfelix** [comment]
* One of the rolled up PRs, PR #112528, is itself a partial revert of PR #110221, which yields the large compile-time losses noted here (solely for helloworld, it is worth noting).
* the point is, the gains were 1. accidental 2. isolated to a toy and 3. due to an unintended change (which was now reverted).
* marking as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
