### PR TITLE
Use a bitset instead of a hash map in HIR ID validator

### PR DESCRIPTION
**Pull request by Kobzol**
The hashset insertion was slightly hot in incr patched runs, but it seems unnecessary to use a hashset here, as it just checks that a dense set of N integers was seen.

This PR does two things:
1) Enables the validation only if `debug_assertions` is enabled (so it's disabled in fully optimized builds now).
2) Uses a bitset instead of a hashmap for the validation, which speeds it up considerably when it is enabled.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Might also be worth trying an IntervalSet if we expect mostly contiguous insertion (I don't know if we do).

**Comment by Kobzol** [comment]
I checked the IDs and its usually contiguous in chunks, based on the visit order. So something like `14, 15, 16, 17, 8, 9, 10, 11` etc. I'll try once we see what happens with the BitSet.

**Comment by cjgillot** [comment]
Should we just gate all this code on `debug_assertions`?  All it does is ICE in case of lowering bugs.

**Comment by Kobzol** [comment]
Yeah I was also thinking that. It's just a sanity check (AFAIK), but consumes ~1% instructions for some incr-patched builds.

**Comment by Mark-Simulacrum** [comment]
@Kobzol for posterity, could you adjust the PR description to reflect that this also disables validation entirely unless debug_assertions is on (so essentially only for local rustc development)?

**Pull request merged**
