### PR TITLE
Update doc for `PhantomData` to match code example

### PR DESCRIPTION
**Pull request by lukas-code**
After https://github.com/rust-lang/rust/pull/106621, there is no longer a `T: 'a` annotation in the doc example, so update the text to match the code.

### CODE REVIEW

**Comment by SmiteWindows** [comment]
@lukas-code  src/test ->tests

**Comment by anden3** [comment]
Hello @lukas-code! I noticed this PR has some merge conflicts, what's the status of it?

**Comment by lukas-code** [comment]
This has bitrotted pretty hard and will probably be a pain to rebase. The main motivation for this PR is this documentation fix: 82de260230f93af5806440ab305e18e07bfdb0c8, which is pretty small. The rest is just updating `std` to be consistent with this and a probably redundant UI test (421a151f3fe478d092146cee7c94d1eb2cd04386) to confirm that the doc change is actually correct.

I can rebase to only keep 82de260230f93af5806440ab305e18e07bfdb0c8 (and optionally 421a151f3fe478d092146cee7c94d1eb2cd04386), which will reduce bitrot and make this easy to review.

**Comment by anden3** [comment]
Sounds like a good idea!

**Comment by lukas-code** [comment]
OK, turns out the relevant changes already landed in 4e7c14fe9f03dd0189f954bd9cb97c3c513e7eed, so this went from "impossible to review" to "tiny wording change" real quick.

@rustbot ready

r? docs

**Comment by ehuss** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
