### PR TITLE
fix -Zast-json to output correct JSON form

### LINKED ISSUE #71086: Invalid JSON for ast-json
The JSON for `-Zast-json` is broken because the [`id` field](https://github.com/rust-lang/rust/blob/9fed36055070168e5238d6bf6e58a36f519fe427/src/librustc_ast/ast.rs#L2239) for attributes serializes to nothing.

An empty library produces the following:

> {"module":{"inner":{"lo":0,"hi":0},"items":[{"attrs":[{"kind":{"variant":"Normal","fields":[{"path":{"span":{"lo":0,"hi":0},"segments":[{"ident":{"name":"prelude_import","span":{"lo":0,"hi":0}},"id":3,"args":null}]},"args":"Empty"}]},"id":,"style":"Outer","span":{"lo":0,"hi":0}}],"id":4,"span":{"lo":0,"hi":0},"vis":{"node":"Inherited","span":{"lo":0,"hi":0}},"ident":{"name":"","span":{"lo":0,"hi":0}},"kind":{"variant":"Use","fields":[{"prefix":{"span":{"lo":0,"hi":0},"segments":[{"ident":{"name":"{{root}}","span":{"lo":0,"hi":0}},"id":5,"args":null},{"ident":{"name":"std","span":{"lo":0,"hi":0}},"id":6,"args":null},{"ident":{"name":"prelude","span":{"lo":0,"hi":0}},"id":7,"args":null},{"ident":{"name":"v1","span":{"lo":0,"hi":0}},"id":8,"args":null}]},"kind":"Glob","span":{"lo":0,"hi":0}}]},"tokens":null},{"attrs":[{"kind":{"variant":"Normal","fields":[{"path":{"span":{"lo":0,"hi":0},"segments":[{"ident":{"name":"macro_use","span":{"lo":0,"hi":0}},"id":9,"args":null}]},"args":"Empty"}]},"id":,"style":"Outer","span":{"lo":0,"hi":0}}],"id":10,"span":{"lo":0,"hi":0},"vis":{"node":"Inherited","span":{"lo":0,"hi":0}},"ident":{"name":"std","span":{"lo":0,"hi":0}},"kind":{"variant":"ExternCrate","fields":[null]},"tokens":null}],"inline":true},"attrs":[],"span":{"lo":0,"hi":0},"proc_macros":[]}

The important bit `"id":,` which is clearly not valid JSON.

It looks like the [`AttrId`](https://github.com/rust-lang/rust/blob/9fed36055070168e5238d6bf6e58a36f519fe427/src/librustc_ast/ast.rs#L2214-L2218) serialization was removed in #70215.

I'm not sure what a solution is here. I'm guessing AST serialization is used elsewhere, where this field isn't needed.  I'm not too familiar with `rustc_serialize`, so I'm not sure if it has something equivalent to `#[serde(skip)]`.

`rustc 1.44.0-nightly (b543afca9 2020-04-05)`

cc @petrochenkov  

This issue has been assigned to @JOE1994 via [this comment](https://github.com/rust-lang/rust/issues/71086#issuecomment-615485095).

### PR DESCRIPTION
**Pull request by JOE1994**
fixes #71086 (Reverts some of the changes made in #70215)

JSON output (from an empty library) after fix has something for **"id"** field
```shell
lonelyjoe@lonelyjoe-desktop:~/workspace/empty_lib/src$ rustc lib.rs -Zast-json
```
```json
{
   "module":{
      "inner":{
         "lo":0,
         "hi":94
      },
      "items":[
         {
            "attrs":[
               {
                  "kind":{
                     "variant":"Normal",
                     "fields":[
                        {
                           "path":{
                              "span":{
                                 "lo":0,
                                 "hi":0
                              },
                              "segments":[
                                 {
                                    "ident":{
                                       "name":"prelude_import",
                                       "span":{
                                          "lo":0,
                                          "hi":0
                                       }
                                    },
                                    "id":3,
                                    "args":null
                                 }
                              ]
                           },
                           "args":"Empty"
                        }
                     ]
                  },
                  "id":null,
                  "style":"Outer",
                  "span":{
                     "lo":0,
                     "hi":0
                  }
               }
            ],
            "id":4,
            "span":{
               "lo":0,
               "hi":0
            },
            "vis":{
               "node":"Inherited",
               "span":{
                  "lo":0,
                  "hi":0
               }
            },
            "ident":{
               "name":"",
               "span":{
                  "lo":0,
                  "hi":0
               }
            },
            "kind":{
               "variant":"Use",
               "fields":[
                  {
                     "prefix":{
                        "span":{
                           "lo":0,
                           "hi":0
                        },
                        "segments":[
                           {
                              "ident":{
                                 "name":"{{root}}",
                                 "span":{
                                    "lo":0,
                                    "hi":0
                                 }
                              },
                              "id":5,
                              "args":null
                           },
                           {
                              "ident":{
                                 "name":"std",
                                 "span":{
                                    "lo":0,
                                    "hi":0
                                 }
                              },
                              "id":6,
                              "args":null
                           },
                           {
                              "ident":{
                                 "name":"prelude",
                                 "span":{
                                    "lo":0,
                                    "hi":0
                                 }
                              },
                              "id":7,
                              "args":null
                           },
                           {
                              "ident":{
                                 "name":"v1",
                                 "span":{
                                    "lo":0,
                                    "hi":0
                                 }
                              },
                              "id":8,
                              "args":null
                           }
                        ]
                     },
                     "kind":"Glob",
                     "span":{
                        "lo":0,
                        "hi":0
                     }
                  }
               ]
            },
            "tokens":null
         },
         {
            "attrs":[
               {
                  "kind":{
                     "variant":"Normal",
                     "fields":[
                        {
                           "path":{
                              "span":{
                                 "lo":0,
                                 "hi":0
                              },
                              "segments":[
                                 {
                                    "ident":{
                                       "name":"macro_use",
                                       "span":{
                                          "lo":0,
                                          "hi":0
                                       }
                                    },
                                    "id":9,
                                    "args":null
                                 }
                              ]
                           },
                           "args":"Empty"
                        }
                     ]
                  },
                  "id":null,
                  "style":"Outer",
                  "span":{
                     "lo":0,
                     "hi":0
                  }
               }
            ],
            "id":10,
            "span":{
               "lo":0,
               "hi":0
            },
            "vis":{
               "node":"Inherited",
               "span":{
                  "lo":0,
                  "hi":0
               }
            },
            "ident":{
               "name":"std",
               "span":{
                  "lo":0,
                  "hi":0
               }
            },
            "kind":{
               "variant":"ExternCrate",
               "fields":[
                  null
               ]
            },
            "tokens":null
         }
      ],
      "inline":true
   },
   "attrs":[

   ],
   "span":{
      "lo":0,
      "hi":94
   },
   "proc_macros":[

   ]
}
```

### CODE REVIEW

**Comment by petrochenkov** [comment]
@JOE1994 
Could you revert the change to `Decodable` as well to keep encoding and decoding symmetric?
(Decoding is probably not used for json specifically, but anyway.)

**Comment by petrochenkov** [comment]
There's a test `src\test\ui\ast-json\ast-json-output.rs` using `-Z ast-json`.
Could you add an attribute to it so the output contains `"id":null`?

**Comment by JOE1994** [comment]
> There's a test `src\test\ui\ast-json\ast-json-output.rs` using `-Z ast-json`.
> Could you add an attribute to it so the output contains `"id":null`?

Thank you for your feedback! :+1: It seems that `src/test/ui/ast-json/ast-json-output.rs` only tests the stdout output of using `-Z ast-json-noexpand` and not `-Z ast-json`. The tests were successful regardless of the changes made in this PR.

Below is what I thought I might have to do here (not yet committed):
1. Rename the following files
  * `src/test/ui/ast-json/ast-json-output.rs` -> `src/test/ui/ast-json/ast-json-noexpand.rs`
  * `src/test/ui/ast-json/ast-json-output.stdout` -> `src/test/ui/ast-json/ast-json-noexpand.stdout`
2. Create new test files (to test output of `-Z ast-json`)
  * `src/test/ui/ast-json/ast-json-output.rs`
  *  `src/test/ui/ast-json/ast-json-output.stdout`

May I ask how I can add an attribute to allow the test to contain "id:null"?
It seems that the current test simply compares the stdout with the provided existing file (`src/test/ui/ast-json/ast-json.stdout`).

**Comment by JOE1994** [comment]
I referred to the [`rustc-guide secion on rustc tests`](https://rustc-dev-guide.rust-lang.org/tests/adding.html#guide-to-the-ui-tests) but couldn't find info on adding attributes to tests :crying_cat_face:

**Comment by petrochenkov** [comment]
@JOE1994 
I think any attribute will work, e.g. `#[inline]` on the main function.

Having separate tests for `-Z ast-json` and `-Z ast-json-noexpand` would be nice.

**Comment by petrochenkov** [comment]
Thanks!
@bors r+

**Pull request merged**
