### PR TITLE
Remove failing GUI test to stop blocking CI until it is fixed

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Until https://github.com/rust-lang/rust/pull/126436 is solved, let's unblock rust CI.

r? @lqd

### CODE REVIEW

**Comment by lqd** [comment]
@bors r+ 

cc @matthiaskrgr we can bump the prio to whatever’s needed to override the tree close prio, when the tools builder is green 🤞

**Comment by cuviper** [comment]
This also hit beta in #126453, so I'm going to unilaterally backport the removal.

**Pull request merged**
