### PR TITLE
Revert Break into the debugger on panic (129019)

### PR DESCRIPTION
**Pull request by ChrisDenton**
This was talked about a bit at a recent libs meeting. While I think experimenting with this is worthwhile, I am nervous about this new behaviour reaching stable. We've already reverted on one tier 1 platform (Linux, https://github.com/rust-lang/rust/pull/130810) which means we have differing semantics on different tier 1 platforms. Also the fact it triggers even when `catch_unwind` is used to catch the panic means it can be very noisy in some projects.

At the very least I think it could use some more discussion before being instantly stable. I think this could maybe be re-landed with an environment variable to control/override the behaviour. But that part would likely need a libs-api decision.

cc @workingjubilee @kromych

### CODE REVIEW

**Review by Noratrieb — APPROVED** [review]

**Comment by Noratrieb** [comment]
borsrplus in the style of the ToysRUs logo

:leftwards_arrow_with_hook:

**Comment by cuviper** [comment]
#129019 is headed for 1.83, so let's consider a backport:

@rustbot label beta-nominated

**Comment by cuviper** [comment]
Oh, nevermind, I must be in a time bubble -- beta is 1.82 right now.

**Comment by kromych** [comment]
> This was talked about a bit at a recent libs meeting. While I think experimenting with this is worthwhile, I am nervous about this new behaviour reaching stable. 

Appreciate taking great care of this! To make experimentation easier, I've published https://crates.io/crates/dbg_breakpoint that has all that there has been in the PR being reverted, and also some more.

**Comment by khuey** [comment]
fwiw (as an rr maintainer) I don't think breaking rr is necessarily a showstopper. rr is powerful enough that we could hide ourselves from the tracee (by faking the reads from `/proc/<pid>/status` and removing the TracerPid line) if this feature were really valuable. I do think that breaking strace is a showstopper ...

The one big question I have about this feature is why the interactive debugger needs the standard library to cooperate at all? Why can't it just set a breakpoint on `__rust_start_panic`? For example, `catch throw` is implemented in gdb for C++ by setting a breakpoint on `__cxa_throw`. Why won't the equivalent work here?

**Comment by kromych** [comment]
> The one big question I have about this feature is why the interactive debugger needs the standard library to cooperate at all? Why can't it just set a breakpoint on `__rust_start_panic`? For example, `catch throw` is implemented in gdb for C++ by setting a breakpoint on `__cxa_throw`. Why won't the equivalent work here?

I believe it can. One needs to know the name of the panic function, and if it ever changes, that causes pain to the folks who do that. On one side there is a workflow of just starting the debugger and running the program and waiting for the panic, on the other side, knowing the name of the function and entering the command. The former seems as fewer steps or less setting up.

**Comment by Noratrieb** [comment]
Fewer steps, but less flexible and more fragile, as we're seeing. For example, if the standard library does it it's harder and weirder to turn off at runtime and as we're seeing, just not a decision the standard library is on a position to make. "debuggers" like strace really don't want this, and it's up to the debugger to decide if they want breakpoints or not.

**Comment by Noratrieb** [comment]
more specifically, I think the way to progress here is to document/stabilize the existence of a symbol suffix/substring[^1] (__rust_start_panic or whatever) (I say *suffix/substring* specifically because the unmangled global symbols are problematic and we shouldn't guarantee the existence of one) and then make debuggers break on that by default. Whether debuggers want to implement that is up to them of course.
This way breakpointing happens in the right place (the debugger, not the standard library) and therefore sidesteps a lot of problems here.
strace would obviously not do anything, rr would do it in a way that works, etc.
It's more effort because it involves changing the debuggers but it's the right solution I think.

[^1]: There is some symbol with the intention of this already but I forgot the name and I don't think it's documented stable

**Comment by khuey** [comment]
To be clear, I'm not saying "tell end users to break on __rust_start_panic", I'm saying teach gdb/lldb/Visual Studio/whatever that their "break on exception" knobs should translate to "break on __rust_start_panic" for Rust code. I believe all three of those debuggers have the capability to break on C++ exceptions.

Teaching the debuggers what to do instead of just SIGTRAPing also has the not-insignificant benefit that not every user of a debugger will be bombarded with panics regardless of their interest in them.

**Comment by kromych** [comment]
Until __rust_start_panic is guaranteed to preserve its name and meaning, that'd be another can of worms to change the debuggers.

As there is no solution presently that satisfies everyone, a separate crate is where this belongs rather than in std. The only obstacle would be the trap instruction intrinsic available in nightly only, yet that is easily solvable with some elbow grease. These considerations led to the crate above.

**Comment by RalfJung** [comment]
> Until __rust_start_panic is guaranteed to preserve its name and meaning, that'd be another can of worms to change the debuggers.

That seems like a pretty actionable next step then -- figure out if __rust_start_panic can be made a guaranteed symbol name, have that blessed by t-libs-api, and add suitable comments in the sources.

**Comment by bjorn3** [comment]
I think we could guarantee that the symbol has that substring, but I don't think we can guarantee that that exact symbol will be used without multiple standard library versions in a single binary conflicting with each other. For example https://github.com/rust-lang/rust/pull/127173 will mangle the name, but keep it as substring. Also we should probably provide guarantees about `rust_panic`, not `__rust_start_panic`. `rust_panic` is documented as being intended to put breakpoints on: https://github.com/rust-lang/rust/blob/f2becdff0496003217e7fc6fbfcaf2640e162775/library/std/src/panicking.rs#L856-L861

**Comment by GrigorenkoPV** [comment]
> > Until __rust_start_panic is guaranteed to preserve its name and meaning, that'd be another can of worms to change the debuggers.
> 
> That seems like a pretty actionable next step then -- figure out if __rust_start_panic can be made a guaranteed symbol name, have that blessed by t-libs-api, and add suitable comments in the sources.



A bit of a silly idea, but what if we just provide something like

```rust
#[inline(never)]
#[unsafe(no_mangle)]
fn __rust_panic_breakpoint() {}
```

? An empty function that is called from the actual `rust_panic` implementations and serves as a place "on which to slap yer breakpoints". This way we are free to change `rust_panic` however we see fit, as long as it calls `__rust_panic_breakpoint` at some point. And it is quite easy to preserve `__rust_panic_breakpoint` the way it is, since it literally does nothing.


Or, maybe, if we want some extensibility, we could pass a pointer to it,
```rust
#[inline(never)]
#[unsafe(no_mangle)]
extern "C" fn __rust_panic_breakpoint(_payload: *const core::ffi::c_void) {}
```
which, for now, will always be `null`, but in future can point to some payload with valuable info (presumably this payload should start with a version number for its format).

I think this way there will be no conflicts between the `std` version.

**Comment by bjorn3** [comment]
> I think this way there will be no conflicts between the std version.

Linkers tend to not like multiple definitions of a symbol even if they are identical.

**Comment by cuviper** [comment]
Isn't that what COMDAT is for?

**Comment by RalfJung** [comment]
> Linkers tend to not like multiple definitions of a symbol even if they are identical.

How does C++ deal with that?

**Comment by bjorn3** [comment]
COMDAT or weak symbols I think. Rustc doesn't currently support COMDAT though.

**Comment by workingjubilee** [comment]
Violating the [One Definition Rule](https://en.wikipedia.org/wiki/One_Definition_Rule) leaves a program ill-formed, "no diagnostic required".

Or: Declare it UB.

**Comment by workingjubilee** [comment]
C++ _implementations_ try to use those, yes.

**Comment by workingjubilee** [comment]
Yeah this is _quite specifically_ "we want the symbol in the object file so the debugger can find it" territory.

**Comment by ChrisDenton** [comment]
There are some really great ideas here but it might be better to move this to a new issue if someone would be willing to summarise. Or an [API Change Proposal](https://github.com/rust-lang/libs-team/issues/new?template=api-change-proposal.md) if someone wants to make a concrete.

It'd be shame if this were left buried in a closed PR.

**Pull request merged**
