### PR TITLE
Fix rendering issues on mobile

### LINKED ISSUE #47723: rustdoc: theme switcher button in awkward locations on mobile
When viewing docs on mobile, the "switch theme" button is placed into the top bar. However, this overlaps the crate version indicator on the crate root:

image

When the sidebar menu is opened, the button is instead placed into that sidebar menu, but can also overlap text there:

image

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #47723 

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
This keeps the button from moving into the sidebar menu when it's expanded, but it doesn't help the crate version from sitting underneath it:

image

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by QuietMisdreavus** [comment]
Now we've gone back to the button being awkward when the menu's open:

image

image

(these screenshots taken with firefox's responsive design mode)

**Comment by GuillaumeGomez** [comment]
I fixed a few others things as well. (Got too much motivation)

**Comment by QuietMisdreavus** [comment]
We're down to a couple small things that aren't deal-breakers. Let's merge this.

@bors r+ rollup

**Comment by QuietMisdreavus** [comment]
The things i've found. I'll post an issue once this is merged.

The padding on the top bar seems to be rendered in a different color? It's really subtle in the dark theme, but in the light theme it sticks out. Strangely, when viewing this in Chrome, the color resets to the "proper" one when i start mousing over elements in the inspector (which causes them to be highlighted in the page), so this may be a Chrome thing.

image

I like how the theme button is next to the search box now, but i guess i expected it to disappear under the menu when it's open? Right now it's just hovering awkwardly over the search box.

image

**Pull request merged**
