### PR TITLE
Update to LLVM 17.0.5

### LINKED ISSUE #116177: 64 bit shift is broken in nightly build for MIPS
I tried this code:

```rust
const SHIFTVALUE : i64 = 10000000000i64;

fn main() {

    fn shiftleft(a : i64, b : i64) -> i64 {
        a << b
    }

    assert_eq!(shiftleft(black_box(SHIFTVALUE), black_box(2)), SHIFTVALUE << 2);
}

```
Nightly fails running on MIPS emulator 

assertion `left == right` failed
  left: 35705032704
 right: 40000000000

Stable succeeds

Looks like the top and bottom dwords are mixed up

target is mips-unknown-linux-musl
emulator is qemu-mips-static

### PR DESCRIPTION
**Pull request by nikic**
Fixes https://github.com/rust-lang/rust/issues/116177.
Fixes the compile-time issue reported at https://internals.rust-lang.org/t/significant-increase-in-fat-lto-time-post-update-to-rustc-1-75-0-nightly/19765.

r? @cuviper

### CODE REVIEW

**Comment by nikic** [comment]
Mips is tier 3, but it probably still makes sense to backport this, as the target is currently completely broken.

(The nomination is for the next beta, not the upcoming stable.)

**Comment by nikic** [comment]
> It seems you included your own Nov 3 commit of "[GlobalOpt] Cache whether CC is changeable", before it landed on main on Nov 7 and was backported to 17.x on Nov 14 (today). Not a big deal, since the commits were identical and so the merge was clean -- just noting the difference in commit history.

Ooops, I forgot to reset my branch before merging.

**Comment by klensy** [comment]
Maybe bump here too? https://github.com/rust-lang/rust/blob/d97bb195bf7b84815622b235cb51171c1b8f7e51/src/ci/docker/host-x86_64/dist-x86_64-linux/build-clang.sh#L7

**Comment by cuviper** [comment]
@klensy that update can be done separately, and I think doesn't need beta backport.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-11-16/near/402491019)

@rustbot label +beta-accepted

**Pull request merged**
