### PR TITLE
WIP: Less globals

### PR DESCRIPTION
**Pull request by Zoxc**
This is based on https://github.com/rust-lang/rust/pull/45912.

r? @arielb1

### CODE REVIEW

**Comment by Zoxc** [comment]
@Mark-Simulacrum Can I get a perf run?

**Comment by Mark-Simulacrum** [comment]
Not currently. Perf is down while we transition to the new collector/frontend, but that should be a relatively temporary event. Once it's back up and running, sure -- it'll be a day or so, and then please ping me again if I haven't posted anything.

**Comment by kennytm** [comment]
Ping @Mark-Simulacrum ↑

**Comment by Mark-Simulacrum** [comment]
Please rebase onto master to pick up https://github.com/rust-lang/rust/pull/46354. Once that's in, I think this should work.

**Comment by Mark-Simulacrum** [comment]
Build queued. Should be available on perf.rlo at http://perf.rust-lang.org/compare.html?start=0a2e9ade83ff253bb489c63a95b1f499c5e0916f&end=04c8514ef729c50d18533b9b435fb0659afd07da&stat=instructions%3Au in at most 4 hours, likely less.

**Comment by Zoxc** [comment]
@Mark-Simulacrum Let's run perf again, now with thread-safe types :)

**Comment by Mark-Simulacrum** [comment]
Perf queued.

**Comment by Zoxc** [comment]
Here are the result:
http://perf.rust-lang.org/compare.html?start=bb42071f63830a984c4983f6fbdf982916857f72&end=c4c91a005d72225d7d849276369e39b5b66a4c91&stat=wall-time
The 30% overhead which I got last time seems to have disappeared.

**Comment by aidanhs** [comment]
@Zoxc just checking in for triage and wondering where this is up to? I can see there are merge conflicts, but once those are resolved is this ready for review?

**Comment by Zoxc** [comment]
This is basically just one step further on my parallel rustc branch than https://github.com/rust-lang/rust/pull/45912. So it needs to wait on that before merging.

**Comment by Zoxc** [comment]
This is being split into smaller PRs.

**Pull request closed without merging**
