### PR TITLE
un-regress behavior of `unused_results` lint for booleans

### LINKED ISSUE #44119: `unused_results` is stricter on Nightly and Beta than on Stable
This compiles fine on stable, but fails on nightly and beta:

https://play.rust-lang.org/?gist=9504fbb631c253be8e43bcb872524e0e&version=nightly

```rust
#![deny(unused_results)]

fn main() {
   let mut p = std::path::PathBuf::from("asdf");
   p.set_extension("foo");
}
```

Nightly results:

```text
  Compiling playground v0.0.1 (file:///playground)
error: unused result
 --> src/main.rs:5:4
  |
5 |    p.set_extension("foo");
  |    ^^^^^^^^^^^^^^^^^^^^^^^
  |
note: lint level defined here
 --> src/main.rs:1:9
  |
1 | #![deny(unused_results)]
  |         ^^^^^^^^^^^^^^

error: aborting due to previous error
```

Regardless of whether the change in behavior is an intentional backward compatibility break, it should be documented in the release notes.

See also #43806.

### PR DESCRIPTION
**Pull request by zackmdavis**
Resolves #44119.

### CODE REVIEW

**Comment by arielb1** [comment]
1.21 is now beta, so this needs to be applied there.

**Comment by zackmdavis** [comment]
@bors r- (if I can do that; it would make sense for the author to have r- privs)

The discussion on #44119 is leaning towards not doing this (three team members and one other contributor against, no one in favor yet). (The rollup #44164 is already in progress; if it passes, this will have been too late and I can make a revert PR afterwards. I'm imagining that the close/r-minus-attempt here won't itself disrupt the rollup.)

**Comment by alexcrichton** [comment]
Removing the beta-nominated tag as this was closed

**Comment by alexcrichton** [comment]
er sorry didn't mean to reopen

**Pull request closed without merging**
