### PR TITLE
Promote riscv64gc-unknown-linux-musl to tier 2

### PR DESCRIPTION
**Pull request by Amanieu**

### CODE REVIEW

**Comment by Amanieu** [comment]
I'm looking for a second target maintainer, this is required for tier 2 support.

cc @kraj @nmeum since you were involved in #82202

**Comment by kraj** [comment]
> I'm looking for a second target maintainer, this is required for tier 2 support.
> 
> cc @kraj @nmeum since you were involved in #82202

@Amanieu I will be happy to help. Please add me.

**Review by kraj — APPROVED** [review]
lgtm

**Comment by Amanieu** [comment]
I've opened an MCP: https://github.com/rust-lang/compiler-team/issues/728

**Comment by Mark-Simulacrum** [comment]
This should probably update the platform support docs to indicate the tier 2 target.

**Comment by kraj** [comment]
> ☔ The latest upstream changes (presumably #122170) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

@Amanieu this needs a manual rebase and push I guess

**Comment by kraj** [comment]
it seems to be a transient download error from looks of it, can we rerun the CI, or maybe push a rebased branch ?

**Comment by tgross35** [comment]
In the queue after the resync

@bors r-

**Comment by jieyouxu** [comment]
Failed in https://github.com/rust-lang/rust/pull/128566#issuecomment-2266191685.
@bors r-

**Comment by jieyouxu** [comment]
```
error: linking with `/musl-riscv64gc/bin/musl-gcc` failed: exit status: 1
[...]
  = note: /usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld: cannot find libgcc_s.so.1: No such file or directory
```

**Comment by tgross35** [comment]
@bors retry

Looks like some kind of networking error

**Comment by karalabe** [comment]
Something seems to be off, because this platform doens't seem to work, even though it's promoted to Tier 2 with Host Tools?

```
curl -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y

curl: (22) The requested URL returned error: 404
rustup: installer for platform 'riscv64gc-unknown-linux-musl' not found, this may be unsupported
```

**Pull request merged**
