### PR TITLE
Add lint for copyright headers to 'tidy' tool

### PR DESCRIPTION
**Pull request by alexreg**
r? @Mark-Simulacrum

CC @centril

### CODE REVIEW

**Comment by alexreg** [comment]
Looks to be working. I’ll fix those files shortly.

**Comment by Mark-Simulacrum** [comment]
Looks like Travis failed but this looks good to me in general - it might be worth including a check for "Rust" in the copyright line?

**Comment by alexreg** [comment]
> Looks like Travis failed but this looks good to me in general - it might be worth including a check for "Rust" in the copyright line?

Yep, I actually went further than this and made a regex for the copyright line, but let me know if that's overkill...

**Comment by alexreg** [comment]
Yeah, I thought originally I would need a more complicated regex to distinguish between Rust Developers and other sorts of copyright notices, but probably not. Let's see if this works...

**Comment by alexreg** [comment]
@Mark-Simulacrum Looking good now. (Tidy checks would have failed this far into the tests.) r+ if you're happy with things?

**Comment by Mark-Simulacrum** [comment]
r=me with notes fixed.

Thanks for taking this on!

Let's also @bors p=1 to hopefully help avoid some rebase pain.

**Comment by alexreg** [comment]
@Mark-Simulacrum LGTM?

**Comment by alexreg** [comment]
@Mark-Simulacrum Did your above r=me have any meaning to Bors or just a reminder?

Also, @nikomatsakis, was I added to the reviewers list yet? I tried to do `@bors r=@Mark-Simulacrum p=1`...

**Comment by alexreg** [comment]
(Ugh, @bors should really ignore commands within backticks.)

**Comment by Mark-Simulacrum** [comment]
Okay one last nit that I noticed, r=me now

I think we haven't re-deployed bors yet so the configuration hasn't been reloaded. For now, @bors delegate+

**Comment by alexreg** [comment]
@Mark-Simulacrum Ah, that makes sense. Thanks for delegating.

@bors r+ p=1

**Comment by alexreg** [comment]
Oops, I meant @bors r=@Mark-Simulacrum p=1

**Comment by alexreg** [comment]
@Mark-Simulacrum Fair enough. Do you have merge rights on the Book? It turns out there are some copyright notices in the code there blocking it. https://github.com/rust-lang/book/pull/1765 fixes it, so maybe you could approve that if possible (once CI passes)...

**Comment by Mark-Simulacrum** [comment]
Merged book PR.

**Comment by alexreg** [comment]
@Mark-Simulacrum @Centril I don't get the above errors when running locally... what's goin on?

**Comment by alexreg** [comment]
@Mark-Simulacrum @rust-lang/docs Could one of you kindly fix the links in the book, per above, so we can get this merged? Thanks.

**Comment by carols10cents** [comment]
@alexreg The broken links in the book should be fixed now: https://github.com/rust-lang/book/commit/0e9061cbaf95adfb9f3ed36c6cef4c046f282e86

**Comment by alexreg** [comment]
@carols10cents Thanks a lot. I'll go ahead and update the submodule in this PR then. Appreciate you working with us despite that surprising merge to your repo over the weekend!

**Comment by alexreg** [comment]
@Mark-Simulacrum @Centril Okay, this should be ready to merge now... when CI passes, at least.

**Pull request merged**
