### PR TITLE
[TEST] Make crate_variances a regular query

### PR DESCRIPTION
**Pull request by Zoxc**
Let's see if this has a performance overhead.

r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 9d1d30a04b41f2333bde432c260ab8d7b205877b

**Comment by ljedrz** [comment]
Looks like there's no overhead :+1:.

**Comment by Zoxc** [comment]
@rust-timer build 98ace47fc1edb766eeca18443ff81e4435320fb1

**Comment by Centril** [comment]
Ping from triage... @Zoxc, @michaelwoerister  seems this had perf regressions, what's the next step?

**Comment by Dylan-DPC** [comment]
ping from triage @Zoxc any updates?

**Pull request closed without merging**
