### PR TITLE
Update RLS and Cargo

### PR DESCRIPTION
**Pull request by nrc**
r? @alexcrichton

### CODE REVIEW

**Comment by kennytm** [comment]
Could not build stage0-rustc. Same problem as https://github.com/rust-lang/rust/pull/43975#issuecomment-324119828.

```
error: `#[deprecated]` cannot be used in staged api, use `#[rustc_deprecated]` instead
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.53\src\lib.rs:57:1
   |
57 | pub type Config = Build;
   | ^^^^^^^^^^^^^^^^^^^^^^^^
error: `#[deprecated]` cannot be used in staged api, use `#[rustc_deprecated]` instead
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.53\src\lib.rs:237:1
    |
237 | / pub fn compile_library(output: &str, files: &[&str]) {
238 | |     let mut c = Build::new();
239 | |     for f in files.iter() {
240 | |         c.file(*f);
241 | |     }
242 | |     c.compile(output);
243 | | }
    | |_^
error: aborting due to 2 previous errors
error: Could not compile `gcc`.
```

**Comment by RalfJung** [comment]
Indeed, same problem in the same crate. Short version of the current status of the issue: The compilation fails because `gcc` is compiled with `-Zforce-unstable-if-unmarked`, which due to a bug leads to `#[deprecated]` not being allowed. That bug is fixed by <https://github.com/rust-lang/rust/pull/44008> but the has not landed in the bootstrap compiler yet.

However, the fact that this flag even gets passed is a bug; there is code in bootstrap that clearly shows this flag is not supposed to be passed when building build scripts or plugins. This actually works on Linux, making the build succeed on my machine and on [Travis](https://travis-ci.org/rust-lang/rust/builds/267027730?utm_source=github_status&utm_medium=notification). However, for some reason, on Windows the flag erroneously (?) gets passed. To debug further, I need someone to run `./x.py build --stage 0 src/libstd -vv` on Windows; that should at least confirm whether the analysis is correct and hopefully shed some light on why Windows is different.

**Comment by alexcrichton** [comment]
@RalfJung the `gcc` crate is used at runtime by the compiler on Windows only, so it's not a bug.

**Comment by kennytm** [comment]
Without bumping stage0, I think we could either

1. Publish `gcc 0.3.54`, which provides a private Cargo feature `"rustc_private_allow_deprecated"` to `cfg_attr` away the `#[deprecated]`, then merge #43975, then rebase this PR; or

2. Lock the gcc dependency at `=0.3.51` in this PR (the version before `Config` is renamed to `Build`), and postpone #43975 to next stage0

```diff
diff --git a/src/bootstrap/Cargo.toml b/src/bootstrap/Cargo.toml
index daa2a3d0a0..a8db254fc9 100644
--- a/src/bootstrap/Cargo.toml
+++ b/src/bootstrap/Cargo.toml
@@ -34,7 +34,7 @@ cmake = "0.1.23"
 filetime = "0.1"
 num_cpus = "1.0"
 getopts = "0.2"
-gcc = "0.3.50"
+gcc = "=0.3.51"
 libc = "0.2"
 serde = "1.0.8"
 serde_derive = "1.0.8"
```

**Comment by RalfJung** [comment]
For the second, not only `bootstrap/Cargo.toml` but also `libstd/Cargo.toml` would need patching.

**Comment by kennytm** [comment]
@RalfJung I think as long as one dependency is locked, the others will all use 0.3.51 automatically. (`0.3.50` is equivalent to `>= 0.3.50, < 0.4.0`)

**Comment by RalfJung** [comment]
Isn't the build of boot strap and of the rest of the compiler done fairly separately?
Certainly for my problem (xargo building libstd), changing things in bootstrap will have no effect.

**Comment by kennytm** [comment]
@RalfJung I thought they all share the same `Cargo.lock`? Anyway, we could change all `gcc = "0.3.50"` to `gcc = "=0.3.51"` just to be safe.

**Comment by RalfJung** [comment]
They probably do in the Rust build process. But that lock file is not part of rust-src, and so xargo has to do fresh dependency resolution.
Maybe we should ship the lock file?

**Comment by nrc** [comment]
I just didn't bump GCC, seems to work on Linux, let's see if it passes bors.

@bors: r=@alexcrichton

**Comment by RalfJung** [comment]
Unfortunately this doesn't help for the xargo use case :/

**Comment by ishitatsuyuki** [comment]
If it fails, please update again to include rust-lang/cargo#4429.

**Comment by ishitatsuyuki** [comment]
I suspect there's a licensing issue going on... try downgrading `rand`.

https://softwareengineering.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license

**Comment by kennytm** [comment]
x86_64-gnu-aux failed, `stage2-cargo` test failed. Legit, needs to account for updated git client. (Cargo needs to be updated)

<details>

```
[01:13:30]      Running build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/build_auth-a9dcf589dab07a7e
[01:13:30] 
[01:13:30] running 3 tests
[01:13:30] test https_something_happens ... ok
[01:13:30] test ssh_something_happens ... ok
[01:13:30] thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
[01:13:30]   left: `{"Accept: */*", "GET /foo/bar/info/refs?service=git-upload-pack HTTP/1.1", "User-Agent: git/2.0 (libgit2 0.26.0)"}`,
[01:13:30]  right: `{"Accept: */*", "User-Agent: git/2.0 (libgit2 0.25.0)", "GET /foo/bar/info/refs?service=git-upload-pack HTTP/1.1"}`', /checkout/src/tools/cargo/tests/build-auth.rs:46:8
[01:13:30] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:13:30] test http_auth_offered ... FAILED
[01:13:30] 
[01:13:30] failures:
[01:13:30] 
[01:13:30] ---- http_auth_offered stdout ----
[01:13:30] 	running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build -v`
[01:13:30] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build`
[01:13:30] thread 'http_auth_offered' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
[01:13:30] 
[01:13:30] 
[01:13:30] failures:
[01:13:30]     http_auth_offered
[01:13:30] 
[01:13:30] test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:13:30] 
[01:13:30] error: test failed, to rerun pass '--test build-auth'
[01:13:30] 
[01:13:30] 
[01:13:30] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-j" "4" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/cargo/Cargo.toml"
[01:13:30] expected success, got: exit code: 101
[01:13:30] 
[01:13:30] 
[01:13:30] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/cargotest src/tools/cargo src/tools/rls src/test/pretty src/test/run-pass/pretty src/test/run-fail/pretty src/test/run-pass-valgrind/pretty src/test/run-pass-fulldeps/pretty src/test/run-fail-fulldeps/pretty
[01:13:30] Build completed unsuccessfully in 0:25:57
[01:13:30] Makefile:56: recipe for target 'check-aux' failed
[01:13:30] make: *** [check-aux] Error 1
```

</details>

**Comment by kennytm** [comment]
@ishitatsuyuki 

The `rand 0.3.16` license problem is introduced in rust-lang-nursery/rand#160 to support Fuchsia, where the new dependency [`magenta`](https://crates.io/crates/magenta) is licensed in BSD-3-Clause, same as Fuchsia itself. The dependency is enabled only when the target is Fuchsia.

This crates.io `rand` dependency is not used by libstd / libtest (they use the in-tree `rand 0.0.0` dependency), so in principle the `magenta` and `magenta-sys` crates can be added to the list of `EXCEPTIONS` originally introduced in #39633 for `mdbook`. 

https://github.com/rust-lang/rust/blob/426711d11c6315a0bd5eed01327de824d807b65c/src/tools/tidy/src/deps.rs#L27-L36

`rand` is used by `jobserver` used by both `rustc` and `cargo`. `cargo` is already exempt as it also uses `openssl`, but I don't know about adding this exception to `rustc`. Also the comment of `EXCEPTIONS` clearly states it is a bug.

<details><summary>Dependency graph of the rust repository, as reported by `cargo graph`.</summary>

1-or8

</details>

**Comment by shepmaster** [comment]
> Legit, needs to account for updated git client.

Based on this, assigning back to author

**Pull request merged**
