### PR TITLE
Fix invalid HTML DIV tag used in HEAD

### LINKED ISSUE #113067: Rustdoc generates invalid HTML header
The generated page HTML contains [a `<div>` tag in the header](https://github.com/rust-lang/rust/blob/27e10c5292eee22abef69aed7144f80bdea00603/src/librustdoc/html/templates/page.html#L27-L42), which is not valid as per the [HTML spec](https://html.spec.whatwg.org/multipage/semantics.html#the-head-element) (which only allows ["Metadata content"](https://html.spec.whatwg.org/multipage/dom.html#metadata-content)). This has been the case since #106915, which moved this div from the body to the header.

I believe browsers will open the body if an invalid tag is encountered in the header (which you can see in inspect elements, where every item in between `</div>` `</head>` are inside of `<body>`), or something like that.

This causes at least one bug: the `#![doc(html_favicon_url = "...")]` attribute, which expands into a `<link rel="icon" href="...">`, is not displayed on Chrome and Chromium-based browsers.
You can see this in the [`time`](https://docs.rs/time/latest/time/) crate on docs.rs:

- Chrome
  chrome
- Firefox 
firefox

Generated HTML:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    
    <!-- ... -->
    
    <div id="rustdoc-vars"
    
    <!-- ... -->

    <link rel="icon" href="https://avatars0.githubusercontent.com/u/55999857">

    <!-- ... -->
</head>
```

vs [inspect element](https://github.com/rust-lang/rust/assets/57450786/28b8a4fd-d43e-47bc-8458-62bab1f4509c):

```html
<html lang="en" data-theme="light">

<head>
    <meta charset="utf-8">
    
    <!-- ... -->
</head>
<div style="display: none; position: fixed; width: 100%; height: 100%; z-index: 1;"></div>

<body class="rustdoc-page">
    <div id="rustdoc-vars"

    <!-- ... -->

    <link rel="icon" href="https://avatars0.githubusercontent.com/u/55999857">

    <!-- ... -->
</body>
```

Manually moving the `link` tag to the header correctly displays the favicon:

1.
image
2. image

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/113067.

The issue also nicely explains the whole problem.

r? @notriddle

### CODE REVIEW

**Comment by fmease** [comment]
Having `<meta>` without `name` is non-standard though, did I read that right?

> Exactly one of the name, http-equiv, charset, and itemprop attributes must be specified.

https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element

**Comment by fmease** [comment]
Well yeah but this meta element doesn't have any name attribute, so this section doesn't apply. It means though that you could add a `name="some_custom_name"` that'd work.

Do we strive for standard compliance actually? I don't know. In this specific case it doesn't matter obviously.

**Comment by GuillaumeGomez** [comment]
I use the `html-checker` tool to ensure it's "okay enough". But if we want to be fully compliant, I don't mind replacing `id` with `name`.

**Comment by GuillaumeGomez** [comment]
Let's use `name` then. :)

**Pull request merged**
