### PR TITLE
[DO NOT MERGE] `-Zthir-unsafeck` perf

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Opening this to be able to perf-test the THIR unsafety checker and subsequent attempts to improve its performance.
r? @ghost

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
Looks like bors forgot about this PR? @bors try

**Comment by bjorn3** [comment]
style-servo-check run incr-patched:

Query/Function | Time (s) | Time (%) | Time delta | Executions | Executions delta | Incremental loading (s) | Incremental loading delta
-- | -- | -- | -- | -- | -- | -- | --
Totals | 13.896 | 108.75%* | 5.5% (0.729) | 5582590 | 0.9% (49092.000) | 0.280 | -6.4% (-0.019)
mir_borrowck | 1.211 | 8.72% | 84.3% (0.554) | 8394 | **126.4% (4686.000)** | 0.001 |  607.6% (0.001)
type_op_prove_predicate | 0.207 | 1.49% | 89.9% (0.098) | 34473 | 73.9% (14647.000) | 0.000 | 0.0% (0.000)

**Comment by LeSeulArtichaut** [comment]
I need to investigate the regression on MIR borrowck for incremental builds, but 34b15995f5388f7945b89109a7a45a2edc08297b should fix the regressions for full and incr-full builds.

@bors try @rust-timer queue

**Comment by LeSeulArtichaut** [comment]
Starting a crater experiment to try to find bugs in the THIR unsafeck, and to gather data for related issues #80059 and #87520.

@craterbot check

**Comment by Dylan-DPC** [comment]
Closing this as inactive

**Pull request closed without merging**
