### PR TITLE
demo of moving std::io::Error to core

### PR DESCRIPTION
**Pull request by programmerjake**
I mostly wanted to show my idea for how to move `std::io::Error` to `core`. I use `AtomicPtr` to fill in the parts that are needed from `alloc`/`std`, but that should probably be replaced with something like `#[panic_handler]` or `#[global_allocator]` except where it resolves to a null pointer instead of erroring if not provided.

I am not very likely to finish this off due to lack of time, so, anyone who wants to, feel free to base your code on mine.

### CODE REVIEW

**Comment by programmerjake** [comment]
afaict there's only one place `core::io::Error::new` is defined, I don't understand why rustc is erroring:
```
  error[E0034]: multiple applicable items in scope
    --> library/alloc/src/io/error/tests.rs:20:26
     |
  20 |     let mut err = Error::new(ErrorKind::Other, TestError);
     |                          ^^^ multiple `new` found
     |
  note: candidate #1 is defined in an impl for the type `core::io::Error`
    --> library/alloc/src/io/error.rs:80:5
     |
  80 | /     pub fn new<E>(kind: ErrorKind, error: E) -> Error
  81 | |     where
  82 | |         E: Into<Box<dyn error::Error + Send + Sync>>,
     | |_____________________________________________________^
     = note: candidate #2 is defined in an impl for the type `core::io::Error`
```

**Comment by cuviper** [comment]
> afaict there's only one place `core::io::Error::new` is defined,

I think it's because the incoherent impl is added in two `alloc` compilations, `cfg(test)` and `cfg(not(test))`.

**Comment by lygstate** [comment]
looks good to me

**Comment by cuviper** [comment]
I'm clearing this from my queue while it's in draft, but you can use `ready` when you are.

@rustbot author

**Comment by Dylan-DPC** [comment]
@programmerjake any updates on this? thanks

**Comment by programmerjake** [comment]
> @programmerjake any updates on this? thanks

as stated on the top comment:
> I am not very likely to finish this off due to lack of time, so, anyone who wants to, feel free to base your code on mine.

my lack of time hasn't changed.

**Comment by Dylan-DPC** [comment]
Thanks for the update. I'm going close this since it will remain inactive and bitrot (already has). When you have the time you can reöpen or preferably create a new pr and link to this one.

**Pull request closed without merging**
