### PR TITLE
Shrink table in the reference

### LINKED ISSUE #20051: Overwide table in pdf documentation
screen shot 2014-12-19 at 6 13 07 pm

Section 3.5.2.1 extends past the width of the page in the pdf. It also doesn't look great in the html:
screen shot 2014-12-19 at 6 15 20 pm

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #20051

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could all the hyperlinking remain? Seems a shame to lose nice clickable things.

**Comment by steveklabnik** [comment]
@alexcrichton seems good :) fixed

**Comment by mdinger** [comment]
You dropped the links for escapes

**Comment by alexcrichton** [comment]
r=me with those links re-added

**Pull request merged**
