### PR TITLE
Add treat-err-as-bug flag in rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @nikomatsakis 
r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Thanks for turning this around so quickly! r=me if travis is green.

**Comment by GuillaumeGomez** [comment]
Well, I think we found out why there is no tests for this flag! :laughing:

**Comment by GuillaumeGomez** [comment]
I removed the test (but kept it in the history).

**Comment by QuietMisdreavus** [comment]
Welp, i guess we can just get this in now.

@bors r+

**Pull request merged**
