### PR TITLE
Some tracing and comment cleanups

### PR DESCRIPTION
**Pull request by oli-obk**
Pulled out of https://github.com/rust-lang/rust/pull/101900 to see if that is the perf impact

### CODE REVIEW

**Comment by oli-obk** [comment]
OK... that wasn't it apparently. Still an improvement in debuggability

**Comment by jackh726** [comment]
Uh...

**Comment by lqd** [comment]
These results should mostly be unrelated.

The biggest numbers here, cranelift-codegen and keccak, are noise. Some of the other smaller regressions are likely noise as well, eg coercions, and wg-grammar is often noisy with them but with a slightly different pattern and has also improved since then.

**Pull request merged**
