### PR TITLE
Include extraction in the retrying for submodule download

### PR DESCRIPTION
**Pull request by emilyalbini**
The code to download larger submodules previously used retries around the `curl` invocation to handle network failures, but we saw in recent build failures that failures can also happen during extraction, for example if a response got terminated early.

This commit moves the retry outwards, wrapping the whole download+extraction function in the retrying code. This means, if the extraction fails the tarball will be re-downloaded.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
@bors r+ p=51
To fix the CI failure

**Comment by fee1-dead** [comment]
Stuck in queue?

@bors r-

**Comment by JohnTitor** [comment]
IIRC bors commands on closed PRs don't work, I guess we have to synchronize the queue or reopen this to r- (it needs Pietro to restore the branch).

**Comment by fee1-dead** [comment]
I've initiated the synchronization

**Comment by ehuss** [comment]
@fee1-dead, when clicking the synchronize button, you need to go through the queue after it is finished and clean up things. Synchronize is fairly buggy. For example, if a PR was approved, but failed in CI, Synchronize will cause it to be re-approved.  I think there are other issues like `try` builds getting converted to `r+` in some cases.  I went through and removed some erroneously approved PRs, but I did not check if any PRs got unapproved inadvertently since I didn't have the list of approved PRs before the synchronize.

**Pull request closed without merging**
