### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #104549 (add -Zexport-executable-symbols to unstable book)
 - #108292 (Label opaque type for 'captures lifetime' error message)
 - #108540 (Add `Atomic*::from_ptr`)
 - #108634 (Add link to component dashboard)
 - #108647 (Remove dead pgo.sh file)
 - #108678 (Use `Option::as_slice` where applicable)
 - #108681 (Improve comments in `needs_process_obligation`.)
 - #108688 (Match unmatched backticks in library/)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=104549,108292,108540,108634,108647,108678,108681,108688)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors retry https://github.com/rust-lang/rust/issues/108227

(╯°□°）╯︵ ┻━┻

**Comment by compiler-errors** [comment]
@bors retry could not create temporary file whilst writing archive: no more archived files

spurious it seems

**Comment by compiler-errors** [comment]
oops lol

**Comment by nnethercote** [comment]
The improvements here are in `keccak` and `cranelift-codegen`, which have been stable for a few days but noisy before that. The PR before this one saw them [regress slightly](https://perf.rust-lang.org/compare.html?start=7a809ce8997a1697b166b4bb2594993e87d69f31&end=44cfafe2fafe816395d3acc434663a45d5178c41&stat=instructions:u), but the improvements here slightly exceed those regressions. #108681 did touch the relevant code extremely lightly, hard to know if that's relevant or not.

**Pull request merged**
