### PR TITLE
Precise capturing in traits

### PR DESCRIPTION
**Pull request by compiler-errors**
This PR begins to implement `feature(precise_capturing_in_traits)`, which enables using the `impl Trait + use<..>` syntax for RPITITs. It implements this by giving the desugared GATs variance, and representing the uncaptured lifetimes as bivariant, like how opaque captures work.

Right now, I've left out implementing a necessary extension to the `refining_impl_trait` lint, and also I've made it so that all RPITITs always capture the parameters that come from the trait, because I'm not totally yet convinced that it's sound to not capture these args. It's certainly required to capture the type and const parameters from the trait (e.g. Self), or else users could bivariantly relate two RPITIT args that come from different impls, but region parameters don't affect trait selection in the same way, so it *may* be possible to relax this in the future. Let's stay conservative for now, though.

I'm not totally sure what tests could be added on top of the ones I already added, since we really don't need to exercise the `precise_capturing` feature but simply what makes it special for RPITITs.

r? types

Tracking issue:
* #130044

### CODE REVIEW

**Review by spastorino — APPROVED** [review]

**Comment by compiler-errors** [comment]
@spastorino, is this waiting on anything else? I didn't see an `r=me after rebasing` or anything :)

**Comment by workingjubilee** [comment]
Needs rebase.

@bors r-

**Comment by workingjubilee** [comment]
I have done so. It dropped one of the same set of warnings that PR #131263 stripped.

@bors r=spastorino

**Pull request merged**
