### PR TITLE
Document PowerShell build dependency on the readme

### PR DESCRIPTION
**Pull request by aochagavia**

### CODE REVIEW

**Comment by aochagavia** [comment]
On Windows, `bootstrap.py` uses `PowerShell` to download the stage 0 compiler.

**Comment by GuillaumeGomez** [comment]
Good catch!

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by alexcrichton** [comment]
@bors: r+

Thanks! I actually chose to use `PowerShell` because I thought it was always in `PATH`, but is that not the case? Are there some configurations where that's missing?

**Comment by retep998** [comment]
Recent Windows versions definitely have Powershell installed and in the PATH by default. What's the newest version of Windows which doesn't have Powershell by default?

**Comment by aochagavia** [comment]
I am using Windows 10 and somehow I didn't have Powershell in the PATH. When `bootstrap.py` failed to download an older rustc I just assumed that not having Powershell in the PATH was normal.

However, after the previous comments from @alexcrichton and @retep998 I am starting to think that I just screwed up my PATH. I have strong reasons to suspect this is the case, as I discovered `Windows/System32` was missing as well.

As it turns out, this PR can be safely ignored.

**Pull request closed without merging**
