### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by TheDerek**
Fixed grammatical error.

### CODE REVIEW

**Comment by mitaa** [comment]
Ah, you need to rebase :-)

**Comment by steveklabnik** [comment]
It's not so much an error as it is a style thing, but yes, @mitaa is right; can you rebase this, please?

**Comment by GuillaumeGomez** [comment]
I don't really agree with this change. I prefer to keep this comma, it's more comfortable to read with this from my point of view.

**Comment by brson** [comment]
I also prefer the existing punctuation, so I'm going to close this. Thank you for the patch.

**Comment by TheDerek** [comment]
Thanks for the consideration. Sometime in the future I will find a
grammatical error worthy of your consideration.

**Comment by GuillaumeGomez** [comment]
@TheDerek: Anytime. :)

**Pull request closed without merging**
