### PR TITLE
Fix wrongly refactored Lift impl

### PR DESCRIPTION
**Pull request by oli-obk**
see https://github.com/rust-lang/rust/pull/101858#issuecomment-1252713639

r? @bjorn3

### CODE REVIEW

**Comment by bjorn3** [comment]
I've confirmed this fixes my problem.

@bors r+

**Comment by wesleywiser** [comment]
#101858 made the beta cut. Should we nominate this for backport?

**Comment by oli-obk** [comment]
yea, I can't figure out how to reproduce on master from user code, but still better safe than sorry.

**Comment by wesleywiser** [comment]
I don't see an urgent reason to beta-accept this ASAP so I'll switch the label to `beta-nominated` for discussion at next week's triage meeting.

**Comment by oli-obk** [comment]
Eh, wrong label selected... I meant to nominate

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-09-29/near/301450296)

@rustbot label +beta-accepted

**Pull request merged**
