### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #118623 (Improve std::fs::read_to_string example)
 - #119365 (Add asm goto support to `asm!`)
 - #120608 (Docs for std::ptr::slice_from_raw_parts)
 - #121832 (Add new Tier-3 target: `loongarch64-unknown-linux-musl`)
 - #121938 (Fix quadratic behavior of repeated vectored writes)
 - #122099 (Add  `#[inline]` to `BTreeMap::new` constructor)
 - #122103 (Make TAITs and ATPITs capture late-bound lifetimes in scope)
 - #122143 (PassWrapper: update for llvm/llvm-project@a3319371970b)

Failed merges:

 - #122076 (Tweak the way we protect in-place function arguments in interpreters)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=118623,119365,120608,121832,121938,122099,122103,122143)

### CODE REVIEW

**Comment by Kobzol** [comment]
The bootstrap regression looks real.

@bors build 495b677058446e9065c089c48d19c859f7eaf71f

**Comment by pnkfelix** [comment]
Visiting for weekly perf triage

* sole primary regression is to image opt-full
* improvements obviously outweigh the regressions
* ... but oh, there is also a bootstrap regression that may be of concern: "Bootstrap: 648.483s -> 652.903s (0.68%)"
* [kobzol has hypothesized](https://github.com/rust-lang/rust/pull/122182#issuecomment-1985734301) that PR #122099 may be the cause of the bootstrap regression.
* not marking as triaged for now.

**Comment by matthiaskrgr** [comment]
to be honest I am not completely unamused by the fact that "our build took 5 seconds longer" is considered a serious  regression  :D

@rust-timer build bdb95761f0ffe2cfc8865affe5f4c73054e7c47c

**Comment by Kobzol** [comment]
It's not necessarily about the regression itself (I'd personally OK it), just that it would be nice to know what has caused it (if it is real), so that we can have a better idea about what effects do various code changes have on the compilation time of `rustc`.

**Comment by nnethercote** [comment]
Plus rustc is the only benchmark we have that is not just a single crate, so it's interesting in that way.

**Comment by matthiaskrgr** [comment]
:thinking: 
image

**Comment by Kobzol** [comment]
That's just LLVM artifact size tracking working again. The unrolled build was created too soon, so it still contained the an old `master` merge as a reference, which didn't have the artifact recorded.

**Comment by pnkfelix** [comment]
> It's not necessarily about the regression itself (I'd personally OK it), just that it would be nice to know what has caused it (if it is real), so that we can have a better idea about what effects do various code changes have on the compilation time of `rustc`.

marking as triaged

@rustbot label: +perf-regression-triaged

**Pull request merged**
