### PR TITLE
rustdoc: Merge `method` and `tymethod` URL fragments and sections

### PR DESCRIPTION
**Pull request by camelid**
This change was discussed on Zulip [here][1].

Here is an excerpt of my proposal, explaining my rationale:

>   They add needless complexity to the intra-doc links code (e.g.,
    [whether an associated item is an impl vs a prototype has to be
    hardcoded in some circumstances][2]) and elsewhere in rustdoc. I don't
    think there's any need to distinguish between these two kinds. For
    example, associated constant prototypes in traits vs definitions in
    traits, trait impls, and inherent impls both use `associatedconstant`.

[1]: https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/.5Bproposal.5D.20merge.20tymethod.20and.20method
[2]: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/trait.20assoc.20item.20-.3E.20impl.20assoc.20item

r? @GuillaumeGomez
cc @jsha

### CODE REVIEW

**Comment by camelid** [comment]
Oops, looks like VS code decided to reformat the JS...

**Comment by camelid** [comment]
I think the main downside of this change is the breakage of non–intra-doc links. There are a lot of results when I [search for `#tymethod.`](https://grep.app/search?q=%23tymethod.). Nearly all of these seem like they should be using intra-doc links instead.

Should we have an FCP given the breakage?

**Comment by jsha** [comment]
Why not add JS to fixup tymethod fragments on page load?

**Comment by camelid** [comment]
I guess we could... I just don't want to end up with tons of redirects as we change rustdoc's output over time.

Is there existing code for this or should I add it?

**Comment by GuillaumeGomez** [comment]
I'd rather not have JS code for that... Such things tend to last much longer than expected. Considering how big the impact is and because it's also a breaking change, FCP is required here.

**Comment by camelid** [comment]
Hmm, I'm sympathetic to the concern about the redirect lasting too long, but on the other hand, it shouldn't be much code to maintain and the change would otherwise be annoying for users.

**Comment by jsha** [comment]
The code would be something like (in main.js):

```js
document.addEventListener("DOMContentLoaded", function() {
  let fragment = getPageId();  // getPageId is defined in main.js
  if (fragment.startsWith("tymethod.")) {
    document.location.hash = "#" + fragment.slice(2);
  }
}
```

**Comment by camelid** [comment]
I moved the CSS cleanup commit into its own PR: #93444

**Comment by JohnCSimon** [comment]
Ping from triage: 
@camelid is this PR still active?

**Comment by camelid** [comment]
I've been meaning to get back to it. Hopefully within the next few weeks I'll be able to finish it. Otherwise, I'll probably close it.

**Pull request closed without merging**
