### PR TITLE
lint missing docs for extern items

### LINKED ISSUE #76991: warn(missing_docs) doesn't trigger on extern declarations
[playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1ba1bff872a1e65a60d097d5fe652186)

It seems like this lint should fire if you have an `extern` declaration without docs on it.

### PR DESCRIPTION
**Pull request by lcnr**
fixes #76991

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
LGTM

**Comment by dboyce-gh** [comment]
Where is check_foreign_item() called?

**Comment by lzutao** [comment]
> Where is check_foreign_item() called?

It is always called, just that's the default implementation on `LateLintPass` is empty, now it is overridden.

**Pull request merged**
