### PR TITLE
update crate dependencies

### PR DESCRIPTION
**Pull request by steveklabnik**
I wanted to update mdbook's version. This ended up updating a bunch of other stuff too.

I am not sure if updating this much stuff is considered a Good Idea or not; happy to figure out how to make it smaller if someone can help me figure out how to use x.py to do it.

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]
Will leave for @alexcrichton to sign off on but looks good in general to me.

**Comment by est31** [comment]
> if someone can help me figure out how to use x.py to do it.

I personally don't have any problems with updating all dependencies (this should be done from time to time either way IMO), but if you want to update only one crate, cd'ing into the src directory and then doing `cargo update -p mdbook` should do it

**Comment by ishitatsuyuki** [comment]
I feel that Cargo.lock updates should have priority; otherwise it would easily conflict with other changes which have more risk to fail.

**Comment by Mark-Simulacrum** [comment]
Not sure what you mean. We try to avoid updates in non-dedicated pull requests to Cargo.lock, so conflicts should be rare.

**Comment by ishitatsuyuki** [comment]
I mean, this will virtually block another approved PR from being merged as it would conflict as soon as this is merged. To minimize the cycle time, this PR should be prioritized.

**Comment by Mark-Simulacrum** [comment]
I wouldn't expect there to be conflicts unless the other PR also updated Cargo.lock; unless I'm missing something, that's rare -- and not all that harmful.

Also, if we wait till the queue is mostly empty, this PR will have less of an effect then (so again, prioritizing it seems odd).

**Comment by est31** [comment]
> I mean, this will virtually block another approved PR from being merged as it would conflict as soon as this is merged. 

A PR which this blocks would have to update Cargo.lock, which happens very rarely.

**Comment by aidanhs** [comment]
Hi @steveklabnik looks like this has some merge conflicts.

**Comment by steveklabnik** [comment]
Updated; looks like it's good to go now.

**Comment by ishitatsuyuki** [comment]
Maybe it's time to develop a custom conflict resolver (that clear and generates lockfile on every merge conflict).

**Comment by arielb1** [comment]
Hey @steveklabnik - looks like this just needs a rebase. Friendly ping to make sure it isn't getting lost.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/42936#issuecomment-313261194

@bors: r=alexcrichton p=1

giving this a priority because i'm sick of rebasing it and want to make sure it lands before next week

**Pull request merged**
