### PR TITLE
Refactor core::ops, move RangeArgument to libcore::ops

### PR DESCRIPTION
**Pull request by clarfonthey**
This is a redone version of most of #41460 that moves `RangeArgument` to `core::ops`. This also refactors `core::ops` into submodules so that it's a bit easier to tell where things are.

This relies on #42268.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks like travis failed:

```
[00:01:37] error: expected identifier, found keyword `fn`
[00:01:37]    --> /checkout/src/libcore/ops/mod.rs:151:5
[00:01:37]     |
[00:01:37] 151 | mod fn;
[00:01:37]     |     ^^
[00:01:37] 
[00:01:37] error: aborting due to previous error
[00:01:37] 
[00:01:37] error: Could not compile `core`.
```

**Comment by Mark-Simulacrum** [comment]
@clarcharr Looks like this is still waiting on some fixes from you... I guess still waiting on https://github.com/rust-lang/rust/pull/42268 though.

**Comment by aidanhs** [comment]
r? @alexcrichton 
Since you've been actively involved with the history here (#41460, #42268) I figure you may want to take a look at this one.

@clarcharr is it possible/does it make sense for you to separate out the two PRs? I realise it's probably a bit of a pain to unpick, but it looks like the other one may be stalled for now?

**Comment by clarcharr** [comment]
@aidanhs I will do that! it makes sense either way

**Comment by clarcharr** [comment]
Also I have to redo this anyway because of the `Carrier` -> `Try` move.

**Pull request closed without merging**
