### PR TITLE
Fix some simple associated const issues.

### LINKED ISSUE #24922: ICE on ambiguous associated const reference
I plan to fix this one very soon because it is easy, but I thought that it deserved a bug report in any case. Note the comment by @nikomatsakis [here](https://github.com/rust-lang/rust/pull/23606#issuecomment-88416969) with a test case.

### PR DESCRIPTION
**Pull request by quantheory**
This fixes #24922 and #25017, and reduces the number of error messages that talk about "methods" when associated constants rather than methods are involved.

I will admit that I haven't thought very carefully about the error messages. My goal has been to make more of the messages technically correct in all situations, and to avoid ICEs. But in some cases we could probably talk specifically about "methods" rather than "items".

### CODE REVIEW

**Comment by nikomatsakis** [comment]
This all seems good to me modulo that one error message (which also happens to be pretty frequent). I think we should ensure it's phrased in as comprehensible a way as possible. I'm now thinking:

> No method `{}` found for type `{}` in the current scope

or, when not doing a method lookup,

> No item `{}` found for type `{}` in the current scope

**Comment by quantheory** [comment]
@nikomatsakis Better?

**Comment by nikomatsakis** [comment]
@quantheory much. Sorry for being slow, was on partial vacation last week.

@bors r+

**Comment by oli-obk** [comment]
I just rebased this locally and ran `make check-stage1` and the failure is gone (as is the use `std::rc::Rc`). Maybe bors merged badly?

**Comment by alexcrichton** [comment]
Perhaps a rebase for this PR is in order? Failures like that generally don't turn out to be false negatives unfortunately.

**Comment by oli-obk** [comment]
i tried it locally, even with the rebase that line has to go.

**Comment by quantheory** [comment]
I haven't had the chance to do a full `make check`, but I tried just rebasing and fixing the one line, if you want to give it another go.

**Comment by quantheory** [comment]
The version here passed `make check` as well.

**Comment by quantheory** [comment]
Rebased, passes `make check`.

**Pull request merged**
