### PR TITLE
coverage: Remove debug code from the instrumentor

### PR DESCRIPTION
**Pull request by Zalathar**
The coverage instrumentor has an entire module full of complex code that is only used for debugging.

And as I continue to work on coverage, I keep finding that this debug code is constantly causing more trouble than it's worth. It's deeply entangled with current implementation details, such that making any non-trivial change to the instrumentor usually requires major changes to the debug code. And so far I have personally not found any of this debug code to be *useful*.

In light of that situation, I'd like to try just ripping all of it out. If I spend any more time dealing with coverage debug code, I want it to be because I'm writing new and useful tools, not dutifully maintaining a boat-anchor that quite plausibly isn't being used by anyone at all.

---
r? @ghost
@rustbot label +A-code-coverage

---

[Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Removing.20debug.20code.20from.20the.20coverage.20instrumentor)

### CODE REVIEW

**Comment by Zalathar** [comment]
The main things being removed here are:

- A parser for environment variable `RUSTC_COVERAGE_DEBUG_OPTIONS` that configures the rest of the debug code
- `DebugCounters`, which stores a mapping from `Operand` values to `BcbCounter` values, and an optional label that indicates a BCB node or BCB edge
- `GraphvizData`, which stores extra data needed by graphviz dumps
- `UsedExpressions`, which tries to check that the instrumentor hasn't injected any unnecessary expression nodes
- `dump_coverage_spanview`, which dumps spans extracted from MIR along with additional details about where those spans came from
- `dump_coverage_graphviz`, which dumps a graphviz diagram illustrating the BCB graph along with associated node/edge counter data

**Comment by Zalathar** [comment]
All of that sounds useful in the abstract, but it's all so heavily tied to the current instrumentor implementation that it is easily broken by any non-trivial change to the instrumentor, often in ways that are difficult or impossible to fix without major changes to the debug code itself.

**Comment by Zalathar** [comment]
This does *not* remove the `-Zdump-coverage-graphviz` and `-Zdump-coverage-spanview` flags, which should continue to work, but will no longer produce dumps containing extra coverage-specific information.

**Review by Swatinem — APPROVED** [review]

**Pull request merged**
