### PR TITLE
Inline len and is_empty in collections

### PR DESCRIPTION
**Pull request by ljedrz**
Is there any reason not to? All of these are trivial and heavily utilized.

### CODE REVIEW

**Comment by nikic** [comment]
I believe historically this has not been necessary, because generic methods were effectively automatically inline. However, this seems to no longer be entirely true nowadays, e.g. they made a large difference in #54668. It would be great if someone could clarify what exactly the impact of `#[inline]` on generic methods is nowadays.

**Comment by Centril** [comment]
cc @anp

**Comment by nagisa** [comment]
It used to be the case that generic functions/methods would be `#[inline]`-able by construction, yes. With that in mind, the guideline was to only add `#[inline]` if it is actually necessary.

However, nowadays, it is common to see cases where the instantiation in the dependency is called instead (and thus is not inlineable, unless LTO is enabled).

**Comment by nagisa** [comment]
@ljedrz with that in mind, are you seeing improvements in codegen with this patch?

**Comment by ljedrz** [comment]
@nagisa I'd be happy to check if you could suggest how I could do it or point me to some past PR that relied on it so I can follow its instructions.

**Comment by nagisa** [comment]
I simply had a test case that used said functions and looked at `--emit=llvm-ir/asm` output to see if the function(s) were inlined or not.

**Comment by ljedrz** [comment]
Ah, ok; I can do that but it will take some time until I can do some test builds; if the queue is clear, a perf run might be faster (and we would probably want one afterwards).

**Comment by ljedrz** [comment]
Ok, so I did some comparisons on a small test case and it appears that there is no difference in codegen; I'm pretty sure my test code does not get optimized away:
```
use std::env;
use std::collections::HashSet;

fn main() {
    let args = env::args().collect::<HashSet<_>>();

    println!("{:?}", args.is_empty());
}
```
I compiled with `rustc main.rs --emit=asm`, with and without `-O`.

*Nevertheless*, the inlined `stage2` build is ~1MB smaller than the non-inlined one 🤔.

**Comment by nagisa** [comment]
@bors try

Lets run that perf run

**Comment by nagisa** [comment]
@rust-timer build bfa68b9524fcf31938a159a9bb13c21184336ccd

**Comment by ljedrz** [comment]
The results look pretty neutral; maaaybe fractional improvements for some cases, but it might just be noise.

**Comment by ljedrz** [comment]
@memoryruins: these are within usual noise range; those benchmarks have high variance.

**Pull request closed without merging**
