### PR TITLE
Use same file permissions for ar_archive_writer as the LLVM archive writer

### LINKED ISSUE #107495: Regression 1.67.0: Static archives have different unix permissions than before
Given this code:

```rust
#[no_mangle]
pub extern "C" fn foo() {}
```

I get this output from rustc:

```
$ rustc +1.66.1 foo.rs --crate-type staticlib && ls -alh libfoo.a
-rw-r--r-- 1 acrichto acrichto 22M Jan 30 16:28 libfoo.a
$ rustc +1.67.0 foo.rs --crate-type staticlib && ls -alh libfoo.a
-rw------- 1 acrichto acrichto 22M Jan 30 16:28 libfoo.a
```

The most recent archive no longer has the "read" permission bit set for group/world owners. This ended up breaking [Wasmtime's build](https://github.com/bytecodealliance/wasmtime/actions/runs/4048924720/jobs/6964738137) because our files are built in a container with a different user and aren't then readable outside of the container. There's no particular reason we do this and we can work around this, but I also suspected that the change in permissions here probably wasn't intentional.

I think this is due to https://github.com/rust-lang/rust/pull/97485 (cc @bjorn3), specifically [this line](https://github.com/rust-lang/rust/blob/001a77fac33f6560ff361ff38f661ff5f1c6bf85/compiler/rustc_codegen_ssa/src/back/archive.rs#L279). I haven't dug too deeply but my guess is that temp files specifically turn off other permission bits

### PR DESCRIPTION
**Pull request by bjorn3**
This is required to switch to ar_archive_writer in the future without regressions. In addition to this PR support for reading thin archives needs to be added (https://github.com/rust-lang/rust/issues/107407) to fix all known regressions.

Fixes https://github.com/rust-lang/rust/issues/107495

### CODE REVIEW

**Comment by nnethercote** [comment]
This is unfamilar code for me, but seems reasonable.

@bors r+

**Comment by GuillaumeGomez** [comment]
I think it failed in https://github.com/rust-lang/rust/pull/122788.

**Comment by bjorn3** [comment]
It did.

@bors r-

**Comment by bjorn3** [comment]
I've added a `umask` call to ensure that the default permissions are consistent independent of the target system.

@rustbot ready

**Comment by nnethercote** [comment]
As before, r=me once CI is happy.

**Pull request merged**
