### PR TITLE
submodules: update rls

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
There was no nightly released because of bad toolstate (rls failed to build)
https://rust-lang-nursery.github.io/rust-toolstate/
rls failed to build because its clippy-lints dependency failed to build.
I updated the clippy-lints dep of rls to a state that is compatible with current rustc so hopefully this commit fixes the toolstate.
Or maybe I am misunderstanding things...

**Comment by nrc** [comment]
Is this updating to a branch? Because if not I think it won't work - building master RLS locally with the latest Rust commit fails in Clippy

**Comment by matthiaskrgr** [comment]
Yeah ... clippy just rebroke ... :(
https://github.com/rust-lang/rust/pull/53581#issuecomment-415160592

I'll see if I can get this fixed.

**Comment by alexcrichton** [comment]
@bors: r-

ah ok, removing from the queue in the meantime!

Also...

r? @nrc

**Comment by matthiaskrgr** [comment]
I updated again, should get rls to the same state as https://github.com/rust-lang/rust/pull/53638

**Comment by kennytm** [comment]
(The Travis error above is a 4924 and is spurious)

**Comment by kennytm** [comment]
```
[RUSTC-TIMING] cargo test:false 127.561
error[E0432]: unresolved import `syntax::codemap`
  --> tools\rls\src\build\rustc.rs:22:13
   |
22 | use syntax::codemap::{FileLoader, RealFileLoader};
   |             ^^^^^^^ Could not find `codemap` in `syntax`
error: cannot find macro `json_internal!` in this scope
   --> tools\rls\src\actions\mod.rs:506:9
    |
506 | /         json!({
507 | |             "watchers": watchers
508 | |         })
    | |__________^
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by matthiaskrgr** [comment]
Fixed via https://github.com/rust-lang-nursery/rls/pull/1010 and rebased.

**Comment by kennytm** [comment]
@matthiaskrgr how about `json_internal!`?

**Comment by matthiaskrgr** [comment]
@kennytm  I can't reproduce this one locally anymore,

I tried:
````
cargo +master build
cargo +master build --all-targets
cargo +master build --all-features
cargo +master build --all-features --all-targets
````
but all passed.
If you have any ideas please let me know!

**Comment by kennytm** [comment]
Let's see what bors think then.

@bors r=nrc

**Comment by matthiaskrgr** [comment]
Ok, then there is nothing I can do about it since I don't have a windows machine.
I'll leave this to someone else then...

**Comment by Xanewok** [comment]
I can take a look at the Windows error later today.

**Comment by Xanewok** [comment]
Verified the fix in https://github.com/rust-lang-nursery/rls/pull/1013 locally, so when that lands we should update RLS to pull that instead.

**Pull request closed without merging**
