### PR TITLE
Implement VecDeque::retain_mut

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/rust-lang/rust/issues/90829.

In https://github.com/rust-lang/rust/pull/90772, someone suggested that `retain_mut` should also be implemented on `VecDeque`. I think that it follows the same logic (coherency). So first: is it ok? Second: should I create a new feature for it or can we put it into the same one?

r? @joshtriplett

### CODE REVIEW

**Comment by the8472** [comment]
If we add a new variant of retain it would be nice to add a range parameter, it helps in cases where one only wants to work on a sub-section of an vec, e.g. when a callee appended N items then it can be more efficient to only post-filter those items but not the whole vec.

**Comment by GuillaumeGomez** [comment]
It seems like a completely different feature. You can't have more parameter in `retain_mut` than in `retain`. Maybe a `retain_range` or something along the line?

**Comment by the8472** [comment]
Sure, the name could be different, but imo not having the range on `retain` was simply an oversight since one always could have done `retain(.., |foo| {/* condition */})`, so any new method should have it.

In this case `&mut` is a more powerful version because a `&mut self` is taken of the vec anyway, so if we're making a more powerful version we might as well add the range.

**Comment by GuillaumeGomez** [comment]
Please open an issue so you can talk about it with libs team and not flood this PR too much.

**Pull request merged**
