### PR TITLE
Use crate name for reexported `extern crate` paths

### LINKED ISSUE #43189: Compiler suggested <unnamed> in a use
```
error[E0599]: no method named `size` found for type `glutin_window::GlutinWindow` in the current sco
pe
  --> src/grenderer/game.rs:28:39
   |
28 |             let tilespace_y = (window.size().height / 4) * 3;
   |                                       ^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use piston::<unnamed>::Window;`

```
Attempting to use that suggustion causes a compiler error itself, and the correct use statement is `use piston::window::Window;`

I dont know how to reproduce this behavior, but it can likely be found by looking in the piston_window crate's source code.

### PR DESCRIPTION
**Pull request by estebank**
Fix #43189.

### CODE REVIEW

**Comment by estebank** [comment]
Tested locally with the ticket's repro, and it seems to be doing the right thing. Need to figure out what the appropriate way to test this is.

**Comment by pietroalbini** [comment]
Ping from triage @michaelwoerister! This PR needs your review.

**Comment by michaelwoerister** [comment]
Yes, a test would be great!

**Comment by estebank** [comment]
Added test.

**Comment by michaelwoerister** [comment]
Thanks @estebank!

@bors r+

**Comment by alexcrichton** [comment]
FWIW it looks like this had a [fairly negative impact](https://perf.rust-lang.org/compare.html?start=ec99b220fe0b0741edd6c9d6e05e4d0d2733a467&end=2408095f3456ba8974032e5dd0a2806cc7329cfb&stat=instructions:u) on perf for a few benchmarks

**Comment by estebank** [comment]
@alexcrichton wow. Should we immediately revert this change? I'm surprised the performance regression is exclusively in `nll-opt`.

**Comment by michaelwoerister** [comment]
I'm surprised this has any perf impact at all. `original_crate_name` is a trivial query, more or less just a hash table lookup. @rust-lang/wg-compiler-nll any ideas why this could affect NLL performance?

**Comment by michaelwoerister** [comment]
http://perf.rust-lang.org/ shows a single NLL spike for this PR, then performance is immediately better again. Something might just have gone wrong with that performance measurement. I don't think this is something to worry about.

**Comment by alexcrichton** [comment]
Oh sorry I just wanted to bring this up as an FYI, no need to immediately revert! I just figured it'd be good to track if there's an easy or "obviously available" solution.

@michaelwoerister it does indeed spike but I was suspicious of this comment because the [commit afterwards](https://github.com/rust-lang/rust/commit/20af72b943527d584df4b99e157262f9b297b3e4) was an explicit optimization for NLL. In that sense I thought this could be a regression followed immediately by an improvement and may still be worth looking into

**Comment by alexcrichton** [comment]
One interesting test though would be to submit a try build of reverting this PR and if it shows a performance improvement across the benchmarks that may mean there's something to look into! If it shows no change, however (as expected), then it could safely be filed under "spurious bug"

**Pull request merged**
