### PR TITLE
Sum for Duration

### PR DESCRIPTION
**Pull request by clarfonthey**
Implemented the `Sum` trait for `Duration`. Seems reasonable.

### CODE REVIEW

**Comment by brson** [comment]
Thanks @clarcharr !

Seems like there's no precedent for implementing `Sum` on types other than primitives.

Might one also want to calculate the product of `Duration`s?

If we open the floodgates what other types are going to end up with `impl Sum` `impl Product`?

**Comment by sfackler** [comment]
We don't have a type to represent squared time, so I don't think a `Product` impl would make much sense :P

**Comment by clarcharr** [comment]
@sfackler I actually thought this question myself and took a look at what types implemented `Add` in std, and currently only `Duration` made any sense for this. I also would consider `Duration` to be essentially two primitive types wrapped in a thin shell, so, it's not going *too* far out of precedent.

Something like `String`, for example, which implements `Add`, might not be a good candidate for `Sum` because I don't ever think of the "sum" of strings to be them all joined together. But I do feel that durations have a well-defined meaning for sum.

**Comment by brson** [comment]
Thanks for the analysis @clarcharr !

**Comment by clarcharr** [comment]
@brson Does this need an RFC before it can be merged? If so, I can submit one.

**Comment by sfackler** [comment]
Nope, I don't think that'd be necessary.

@rfcbot fcp merge

**Comment by sfackler** [comment]
@brson speak now or forever hold your peace.

@bors r+

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault https://github.com/rust-lang/rust/issues/38878

**Comment by alexcrichton** [comment]
@bors: retry

* macs are having a bad day with the network

**Pull request merged**
