### PR TITLE
2018 edition - confusing error message when declaring unnamed parameters 

### LINKED ISSUE #53990: 2018 edition - confusing error message when declaring unnamed parameters
This code works correctly on nightly and stable
```rust
trait Trait {
    fn func(u8);
}
```
but not on 2018 edition, where it returns the error
```
error: expected one of `:` or `@`, found `)`
 --> src/main.rs:2:15
  |
2 |     fn func(u8);
  |               ^ expected one of `:` or `@` here
```

Changing it to `func(_: u8)` solves it.
 
Is this an intended change?
I couldn't find anything about it in the edition guide.

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #53990.

This PR adds a note providing context for the change to argument
names being required in the 2018 edition for trait methods and a
suggestion for the fix.

### CODE REVIEW

**Comment by Nemo157** [comment]
It seems like the compatibility warning and the hard error could use the same/similar error messages ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=0304a78e6d1ef3ce04537e8e520e843e))

```
error: anonymous parameters are deprecated and will be removed in the next edition.
 --> src/lib.rs:4:13
  |
4 |     fn func(u8);
  |             ^^ help: Try naming the parameter or explicitly ignoring it: `_: u8`
  |
[...]
  = note: #[deny(anonymous_parameters)] implied by #[deny(rust_2018_compatibility)]
```

**Comment by davidtwco** [comment]
> 
> 
> It seems like the compatibility warning and the hard error could use the same/similar error messages ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=0304a78e6d1ef3ce04537e8e520e843e))

Ah, good point @Nemo157. I've updated the messages.

**Review by nikomatsakis — APPROVED** [review]

**Comment by alexcrichton** [comment]
@bors: retry

* CI automation hiccup

**Pull request merged**
