### PR TITLE
std: add a Writer impl for &mut [u8]

### PR DESCRIPTION
**Pull request by erickt**
@alexcrichton mentioned in the [io reform rfc](https://github.com/rust-lang/rfcs/pull/517#issuecomment-66796223) that there might be interest in reviving the Writer for `&mut [u8]`, so I revived the PR for consideration. As written, it needs to do some unsafe magic in order to advance the mutable slice. It would be nice if this was someday factored out into a method on the slice itself.

### CODE REVIEW

**Comment by Gankro** [comment]
@erickt status?

**Comment by nwin** [comment]
The unsafe part can actually be reduced to (the transmute is just there for the lifetime)

    *self = unsafe { mem::transmute(self.slice_from_mut(write_len)) };

I still wonder why it is needed for the `Writer` but not for the `Reader`.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen once more of the I/O reform RFCs have landed!

**Pull request closed without merging**
