### PR TITLE
CI: use free runners for 4-core Linux jobs

### PR DESCRIPTION
**Pull request by Kobzol**
It looks like the [free runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) already have the same spec as the `4c` custom "large" runner (4 cores, 16 GiB of memory, Ubuntu 20.04).

try-job: arm-android
try-job: armhf-gnu
try-job: dist-aarch64-linux
try-job: dist-android
try-job: dist-arm-linux
try-job: dist-armhf-linux
try-job: dist-armv7-linux
try-job: dist-i586-gnu-i586-i686-musl
try-job: dist-i686-linux
try-job: dist-loongarch64-linux
try-job: dist-loongarch64-musl
try-job: dist-ohos
try-job: dist-powerpc-linux
try-job: dist-powerpc64-linux
try-job: dist-powerpc64le-linux
try-job: dist-riscv64-linux
try-job: dist-s390x-linux
try-job: dist-various-1
try-job: dist-various-2
try-job: dist-x86_64-freebsd
try-job: dist-x86_64-illumos
try-job: dist-x86_64-netbsd
try-job: mingw-check
try-job: test-various
try-job: x86_64-gnu
try-job: x86_64-gnu-stable
try-job: x86_64-gnu-aux
try-job: x86_64-gnu-debug
try-job: x86_64-gnu-nopt

### CODE REVIEW

**Comment by Kobzol** [comment]
Ran out of disk space. Fun.

**Comment by Kobzol** [comment]
I added an action to reduce disk usage. I'd suggest trying to merge this again and see if all other CI jobs that use the free runner now can fit within the available space.

@rustbot ready

**Comment by Kobzol** [comment]
Ah, forgot to only do the cleaning on Ubuntu.

@bors r=Mark-Simulacrum

**Comment by Kobzol** [comment]
Ok, time to selectively disable the free runners on selected workers. But there are a lot of them. @Mark-Simulacrum Can we do a merge attempt where I set `fail-fast: false` to the matrix, just to see all the jobs that fail? Then I could move all of them to the large runner at once.

**Comment by Mark-Simulacrum** [comment]
Sure. We could probably also add a bunch of try-job: to the PR description for all of those?

**Comment by Kobzol** [comment]
I was afraid you's say that :) Ok, I went through all of them and enumerated them in the PR description. Let's *try* it.

@bors try

**Comment by Kobzol** [comment]
Here are the results of how much free disk space was available after the given CI job ended:
```
arm-android: 18 GiB
armhf-gnu: 24 GiB
dist-aarch64-linux: OUT OF DISK SPACE
dist-android: 17 GiB
dist-armhf-linux: 4.1 GiB
dist-armv7-linux: 5.5 GiB
dist-i586-gnu-i586-i686-musl: 13 GiB
dist-i686-linux: 1.8 GiB
dist-loongarch64-linux: OUT OF DISK SPACE
dist-loongarch64-musl: OUT OF DISK SPACE
dist-ohos: 16 GiB
dist-powerpc-linux: 1.5 GiB
dist-powerpc64-linux: OUT OF DISK SPACE
dist-powerpc64le-linux: OUT OF DISK SPACE
dist-riscv64-linux: 2.3 GiB
dist-390x-linux: 1.3 GiB
dist-various-1: 2.2 GiB
dist-various-2: 4.1 GiB
dist-x86_64-freebsd: 6.8 GiB
dist-x86_64-illumos: 3.9 GiB
dist-x86_64-netbsd: 4.9 GiB
mingw-check: 27 GiB
test-various: 16 GiB
x86_64-gnu: 11 GiB
x86_64-gnu-stable: 11 GiB
x86_64-gnu-aux: 15 GiB
x86_64-gnu-debug: 29 GiB
x86_64-gnu-nopt: 14 GiB
```

We should obviously use the large runner for those runners that ran out of space. For the rest, I'd maybe also use it for `powerpc-linux` and `s390x-linux`, since these are kind of close to the limit?

**Comment by Mark-Simulacrum** [comment]
Seems reasonable to me.

**Comment by Kobzol** [comment]
Doing another try run with the updated config, just to be sure.

@bors try

**Comment by Kobzol** [comment]
Looks like it worked :tada: Removed the last testing commit.

**Comment by MarcoIeni** [comment]
@craterbot run mode=check-only crates=https://gist.githubusercontent.com/MarcoIeni/3800cdca02ddb30ac98404cafa849c1b/raw/crates start=master#91c4d09aed5d8bb3878bc81b7c85bcc6d6f31c16 end=try#acfdb8dd1fd4913ea004f43f73e7346e125491ed

**Comment by MarcoIeni** [comment]
^ this is a test

**Comment by Mark-Simulacrum** [comment]
@craterbot abort

Something about that run is broken, I suspect it's the starting commit (91c4d09aed5d8bb3878bc81b7c85bcc6d6f31c16) which isn't a bors commit.

**Comment by MarcoIeni** [comment]
@craterbot run mode=check-only crates=https://gist.githubusercontent.com/MarcoIeni/3800cdca02ddb30ac98404cafa849c1b/raw/crates start=master#2aa26d8a722cf8810b27538c24b93d29324d4ac7 end=try#acfdb8dd1fd4913ea004f43f73e7346e125491ed

**Pull request merged**
