### PR TITLE
Stabilize Wasm target features that are in phase 4 and 5

### PR DESCRIPTION
**Pull request by daxpedda**
This stabilizes the Wasm target features that are known to be working and in [phase 4 and 5](https://github.com/WebAssembly/proposals/tree/04fa8c810e1dc99ab399e41052a6e427ee988180).

Feature stabilized:
- [Non-trapping float-to-int conversions](https://github.com/WebAssembly/nontrapping-float-to-int-conversions)
- [Import/Export of Mutable Globals](https://github.com/WebAssembly/mutable-global)
- [Sign-extension operators](https://github.com/WebAssembly/sign-extension-ops)
- [Bulk memory operations](https://github.com/WebAssembly/bulk-memory-operations)
- [Extended Constant Expressions](https://github.com/WebAssembly/extended-const)

Features not stabilized:
- [Multi-value](https://github.com/WebAssembly/multi-value): requires rebuilding `std` #73755.
- [Reference Types](https://github.com/WebAssembly/reference-types): no point stabilizing without #103516.
- [Threads](https://github.com/webassembly/threads): requires rebuilding `std` #77839.
- [Relaxed SIMD](https://github.com/WebAssembly/relaxed-simd): separate PR #117468.
- [Multi Memory](https://github.com/WebAssembly/multi-memory): not implemented.

See https://github.com/rust-lang/rust/pull/117457#issuecomment-1787648070 for more context.

Documentation: https://github.com/rust-lang/reference/pull/1420
Tracking issue: https://github.com/rust-lang/rust/issues/44839

### CODE REVIEW

**Comment by daxpedda** [comment]
Cc @alexcrichton.

**Comment by alexcrichton** [comment]
AFAIK a stabilization policy is not documented anywhere for WebAssembly target features, but in my opinion this is a good PR to land.

As a bit of background on this in case anyone's curious: WebAssembly target features in LLVM relate to [WebAssembly proposals](https://github.com/WebAssembly/proposals/) and are frequently named after those proposals. WebAssembly proposals go through a phased design process similar to JS and once a feature reaches "phase 4" it's effectively done and ready for everyone to use. That's when browsers start shipping the feature ungated for example. There is no "standard" for what to call these proposals beyond "toolchain conventions" which, at this time, is "whatever LLVM called it". In that sense the choice of feature name here matches what one would use on the command line for C/C++ when compiling WebAssembly.

This particular proposal, along with others, as pointed out, is "stage 5" which means it's long since done and overdue for stabilization on our end.

**Comment by cjgillot** [comment]
@alexcrichton do you mind taking the review?

**Review by alexcrichton — APPROVED** [review]
Certainly! I fear I may not have bors permissions any more though, but I can offer a github approval nonetheless

**Comment by daxpedda** [comment]
I decided to add the remaining features into the same PR as they don't require any further work in the Rust compiler.

**Comment by nikomatsakis** [comment]
@alexcrichton can you clarify the impact of stabilizing these items? What impact does it have on what *Rust code* people are allowed to write? Do these affect the quality of codegen only? Does that imply that a broader set of Rust code will compile on the wasm target?

I'm generally in favor of doing this, but it would be good to understand what exactly it *means*.

**Comment by nikomatsakis** [comment]
In particular I am also trying to figure out if this is T-compiler, T-lang, or *both* in terms of who needs to commit to stabilization.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

I am going to assume that this is both a lang and compiler RFC, and hence I move to merge, based on what @alexcrichton had to say. Here is my understanding of what we are stabilizing:

* The ability to specify a certain set of webassembly features. These features have no direct impact on the compiler but are passed through to the backend (LLVM, at present) and enable it to make use of wasm features. They may affected quality of codegen and/or perhaps the ability for some kinds of code to be compiled, this is not entirely clear to me and I would appreciate clarification.
* The names of these features comes from webassembly spec processes and they are all in "stage 4", which means effectively *done* and also available in browsers without feature gates etc. So no reason to think the names or meaning will change going forward.

The primary concern I can imagine, if the above is correct, is that the compiler doesn't handle the flags correctly or that this may allow some Rust code to reach WASM that "ought not to" (not sure how that latter part would happen though unless there was a bug somewhere else in rustc that enabled it, so i.e. the first problem).

**Comment by tmandry** [comment]
I assume this would include the ability to specify those features in both compiler flags and `#[target_feature]`, though I can't remember if we stabilized the latter for WASM or not. 

Also @nikomatsakis it sounds like the exact names being used actually come from LLVM. I don't see any reason to differ on those though. 

In any case this all sounds fine to me, so 

@rfcbot reviewed

**Comment by alexcrichton** [comment]
Sure yeah I can try to document and clarify a few things here. I'll reiterate
some bits I mentioned
[above](https://github.com/rust-lang/rust/pull/117457#issuecomment-1787648070)
as well.

For background here the WebAssembly Community Group (CG) is the main technical
governing body for WebAssembly at this time. There is a process in place for
adding new features to WebAssembly and it is documented in [this
repository](https://github.com/WebAssembly/proposals/). As proposals go through
their stages it requires adding support to toolchains and languages which often
means implementing this in LLVM. For Rust that means that there's a question of
when to stabilize and how to support new features of WebAssembly.

Proposals which have reached at least stage 4 are generally considered done. At
that point browsers start shipping features ungated for example. Historically
this at least been my personal loose threshold of when to stabilize features for
Rust. Any feature in phase 3 or lower would, in my opinion, not be a candidate
for stabilization in Rust.

All of the features stabilized here are phase 4 and beyond (many at phase 5).
This means that the threshold for stability in WebAssembly itself is achieved
and the question now turns to Rust to how to expose these features. Features in
WebAssembly are often new instructions but sometimes manifest as new syntactic
forms in a WebAssembly binary. Features also do not work like native platforms
because for a WebAssembly binary to be considered valid to execute it must be
valid in its entirety. In contrast a native binary can contain code that the
current processor doesn't support so long as it doesn't execute it. In that
sense native runtime feature detection is not possible in WebAssembly unlike how
it is for native platforms.

Ok so how does any of this affect Rust. Rust supports compilation to WebAssembly
through LLVM, and in general needs to express the ability to customize the
output binary to handle the presence or non-presence of these features. For
example for performance-related features users may wish to have builds both with
and without the feature. This is achieved right now via a few means:

1. Via `-Ctarget-feature=+foo`. AFAIK this isn't gated and is passed through
   straight to LLVM, so this works today and does not require stabilization.
   This works well for WebAssembly since if a feature is enabled for one
   function it may as well be enabled for the whole binary since if one function
   gets it all others will be able to have access to it as well.

2. Via `#[target_feature(enable = "foo")]`. This is not stable today and is what
   would be stabilized here. This is where the story is a little murky for
   WebAssembly since unlike native platforms not much is gained from enabling a
   feature per-function rather than at the whole module level. That being said
   this is required for correctness in the case of simd128 for example (e.g.
   LLVM can't codegen intrinsics unless that feature is enabled) and can still
   be useful in some niche situations.

3. Testing via `#[cfg(target_feature = "foo")]` currently doesn't work today
   since only when these attributes are stable are the cfg directives defined.
   This can be useful in general but isn't too useful for many of the features
   stabilized here.

So given all that, this PR largely boils down to enabling `#[cfg(target_feature
= "foo")]` and `#[target_feature(enable = "foo")]` on stable. These aren't the
most useful things in the world but can be useful in some niche situations. What
follows is a more detailed description of what all these features are.

## `"bulk-memory"`

The [bulk memory
proposal](https://github.com/WebAssembly/spec/blob/main/proposals/bulk-memory-operations/Overview.md)
for WebAssembly can more-or-less be thought of as adding a `memcpy` instruction
to WebAssembly (or `memmove`, I forget which allows overlap). There's other bits
and bobs though for "data segments" and constructs in WebAssembly which are not
relevant to Rust-the-language directly. Why users might want this proposal:

* The `memory.copy` WebAssembly is much faster than `memcpy`-written-in-wasm for
  large data copies.
* Multithreaded WebAssembly uses features added in this proposal.

## `"extended-const"`

The [extended const proposal](https://github.com/WebAssembly/extended-const)
enables new forms of constant expressions in WebAssembly. This has no effect on
Rust itself and has nothing to do with Rust `const`. This is not useful nor
exposed to Rust code at all through LLVM and is only used, as far as I know, for
dynamic linking. The dynamic linking story in Rust for WebAssembly is not
well-defined and has not been fleshed out. Nevertheless though it's stable in
WebAssembly and implemented in LLVM and will be integral for any future
experimentation with dynamic linking for example. This may also be useful for
other more niche situations of users trying to craft particular shapes of wasm
modules.

## `"mutable-globals"`

The [mutable global proposal](https://github.com/WebAssembly/mutable-global/) is
largely centered around JS integration of WebAssembly. Honestly I'm not really
sure why this is exposed through LLVM. This has no effect on generated code as
far as I know and is basically only required if you want to experiment with
threads. Any threads-using target for WebAssembly is required to enable this
proposal (e.g. it's a hard requirement check in the LLD linker).

## `"nontrapping-fptoint"`

The [non-trapping float-to-int conversions
proposal](https://github.com/WebAssembly/spec/blob/main/proposals/nontrapping-float-to-int-conversion/Overview.md)
affects how `f32 as i32` is translated in Rust for example. A comparison can be
[seen on godbolt.org](https://godbolt.org/z/zj3r5q3Pd) of how the generated code
differs. For any application bottlenecked on performance of this operation this
would be critical in getting the best performance.

## `"sign-ext"`

The [sign extension operations
proposal](https://github.com/WebAssembly/spec/blob/main/proposals/sign-extension-ops/Overview.md)
added a few instructions related to sign extending 8/16-bit values to 32/64-bit
values to the base instruction set. A comparison here can also be seen [on
godbolt.org](https://godbolt.org/z/T1f6Ws1rY). Note that this feature is enabled
by default in the WebAssembly targets today so it's actually somewhat difficult
to disable.

**Comment by ehuss** [comment]
> I assume this would include the ability to specify those features in both compiler flags and #[target_feature]

`-C target-feature` generally doesn't restrict which options you can use. This is only stabilizing the `#[target_feature]` attribute values. Previous to this PR, only `simd128` was stable in the attribute.

**Comment by petrochenkov** [comment]
I'm going to rubber stamp this if wasm experts are on board with this stabilization.
@rfcbot reviewed

**Comment by CryZe** [comment]
Is this blocked by anything?

**Comment by daxpedda** [comment]
> Is this blocked by anything?

Nothing technical is blocking it.

I'm not very familiar with the process, but it seems to require a review according to the assigned labels?
According to https://github.com/rust-lang/rust/pull/117457#issuecomment-1789204219 it also seems like at least four more approvals are necessary.

**Comment by workingjubilee** [comment]
@alexcrichton 

> ## `"extended-const"`
> 
> ...This is not useful nor exposed to Rust code at all through LLVM and is only used, as far as I know, for dynamic linking.
>
> ## `"mutable-globals"`
> 
> The [mutable global proposal](https://github.com/WebAssembly/mutable-global/) is largely centered around JS integration of WebAssembly. Honestly I'm not really sure why this is exposed through LLVM. This has no effect on generated code as far as I know and is basically only required if you want to experiment with threads.

Just to clarify, but while you say these aren't really exposed to Rust code, they *do* alter codegen and could result in lowering existing Rust programs to wasm modules that would be rejected on-load by an "MVP" wasm interpreter, correct?

**Comment by daxpedda** [comment]
> Just to clarify, but while you say these aren't really exposed to Rust code, they _do_ alter codegen and could result in lowering existing Rust programs to wasm modules that would be rejected on-load by an "MVP" wasm interpreter, correct?

This is correct.
Notably `mutable-globals` is already enabled by default since Rust v1.70 because of LLVM v16, even though its unstable in Rust.

**Comment by alexcrichton** [comment]
I'd agree with @daxpedda, and to add a bit I'll mention that I don't at least personally know much about how to actually get LLVM to trigger different codegen. I think that to some degree LLVM is trying to follow the wasm proposals themselves and have flags for even the more minor ones. I don't see an issue doing the same with rustc, personally. 

Put another way, I don't know how to generate a module that requires either `mutable-globals` or `extended-const`. I know that LLVM considers `mutable-globals` a requirements of the `atomics` feature so it's sort of there for at least that, but I don't know if it actually affects codegen other than serving as a gate of "I'm going to codegen this a single way and you must opt-in to the feature". 

For `extended-const` I believe it's related to dynamic libraries on wasm and optimizing them but I do not personally have enough experience to be able to show the incantation to generate a module with `extended-const` expressions.

Neither of these features are related to code in `func`s, they're instead about the structure of the surrounding module. A native-platform lookalike might be opting into a new kind of relocation or more efficient debuginfo format, for example.

**Review by wesleywiser — APPROVED** [review]

**Comment by daxpedda** [comment]
@wesleywiser apologies for the delay.

**Pull request merged**
