### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by dns2utf8**
- Successful merges: #37859, #37919, #38020, #38028, #38029, #38073, #38077, #38090
- Failed merges:

### CODE REVIEW

**Comment by dns2utf8** [comment]
Rollup looks good. Is this ok? 

cc: @nikomatsakis @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
@dns2utf8: It looks good but we prefer when someone with r+ rights do it (in case of failure and stuff).

@bors: r+ p=1

**Comment by alexcrichton** [comment]
@bors: retry force clean

* restarted buildbot

**Comment by dns2utf8** [comment]
Oh, the button just worked so I guessed 😉 

I guess only members have the right to r+?

**Comment by dns2utf8** [comment]
Ah, too bad it failed. So what do we next? 

Can I edit this PR and try to fix it or should I close it?

**Comment by GuillaumeGomez** [comment]
Yes, only collaborators can r+ and yes, please close it.

**Comment by dns2utf8** [comment]
Sorry for the interruption.

**Pull request closed without merging**
