### PR TITLE
Properly categorize RFC UI tests

### PR DESCRIPTION
**Pull request by inquisitivecrystal**
For some reason, there are a bunch of folders under `src/test/ui` named `rfc-####-*`, despite the fact that there is already a `src/test/ui/rfcs` subdirectory for them. This is a bad thing, as `src/test/ui` already has an unmanageably large number of files and directories. This PR moves the RFC test subdirectories into the `src/test/ui/rfcs` space. 

I should mention that there were a few cases with both a `src/test/ui/rfc-####-*` directory and a `src/test/ui/rfcs/rfc-####-*` directory. I resolved any collisions that resulted by renaming the files involved.

I suspect the current division came about accidentally when some other test suites were merged into UI.
r? @JohnTitor

Since you were kind enough to review my last test PR, I thought it might make sense to ask you to review this one. Do you mind being asked for reviews on PRs that sort tests? I'm planning to do some more in the future.

### CODE REVIEW

**Comment by petrochenkov** [comment]
`rfcs` is a pointless subdirectory that shouldn't exist, IMO, it's better to move the small `rfcs-*` subdirectories to more meaningful subdirectories corresponding to compiler areas and people maintaining them - https://github.com/rust-lang/rust/pull/84065#issuecomment-817286962.

cc https://github.com/rust-lang/rust/issues/73494 (the big project for classifying tests)

**Comment by inquisitivecrystal** [comment]
> `rfcs` is a pointless subdirectory that shouldn't exist, IMO, it's better to move the small `rfcs-*` subdirectories to more meaningful subdirectories corresponding to compiler areas and people maintaining them - [#84065 (comment)](https://github.com/rust-lang/rust/pull/84065#issuecomment-817286962).
> 
> cc #73494 (the big project for classifying tests)

I am working on classifying some tests in a more meaningful way. It feels like the most urgent concern is making it so people can at least navigate to find a test in the tree without being overwhelmed though. I'd this is an improvement over the current state of affairs, even if it may not be ideal as an end state.

Also, if I may ask, who's the best person to r? on test classification PRs?

**Comment by JohnTitor** [comment]
Yeah, usually @petrochenkov handles such a PR so they should be a good reviewer here, but I'm also happy to review if it's minor (e.g. it's small or just adds a test).
And I agree with their opinion, in that case, we should move two or so (sub)directories at once so that reviewing would be easy.
(By the way, it makes me think about having README on `src/test/ui` to give some direction because the contributors may be confused if `RFC` dir doesn't exist anymore, for example.)

**Comment by inquisitivecrystal** [comment]
Alright, it sounds like I should close this.

Before I do though, I should make sure I understand what I'd need to do to fix it. What test subdirectories are meaningful? Is there any trick, beyond the classifier tool, for figuring out which subdirectory a test should be in?

**Comment by JohnTitor** [comment]
> What test subdirectories are meaningful? Is there any trick, beyond the classifier tool, for figuring out which subdirectory a test should be in?

It's not documented, that's why I said we needed README (or something else). AFAIK here's a brief list of meaningless subdirs (we might have more, I haven't taken a closer look): https://github.com/rust-lang/rust/issues/73494#issuecomment-761772344

**Comment by inquisitivecrystal** [comment]
Thanks!

**Pull request closed without merging**
