### PR TITLE
ExitCode docs improvements

### PR DESCRIPTION
**Pull request by coolreader18**
Not sure how changes made during a fcp should be PR'd, obviously this isn't needed for the stabilization so I just based it off the stabilization branch.

r? yaahc

### CODE REVIEW

**Comment by yaahc** [comment]
Can you change the base branch from master to my branch in the stabilization PR, `yaahc:termination-stabilization-celebration-station`?

**Comment by coolreader18** [comment]
Eeek, I don't think so, I'd have to make a new PR in your fork I think.

**Comment by coolreader18** [comment]
I could squash and you could cherry-pick?

**Comment by yaahc** [comment]
I've merged the touch up commit, thank you again!

**Pull request closed without merging**
