### PR TITLE
update blksize_t in raw to reflect libc change under openbsd

### PR DESCRIPTION
**Pull request by semarie**
make `os::raw::tests::unix` test to pass again

r? @alexcrichton

### CODE REVIEW

**Comment by aturon** [comment]
I just wanted to check in on this: we had *mega* problems making a similar change on Android, which was similarly considered having non-first tier support. Are we confident this won't instigate the same sort of breakage and dependency hell we saw there?

**Comment by semarie** [comment]
@aturon I am not sure to exactly understand the question. Some days ago, I updated OpenBSD libc based on libc-test (test suite of libc), and checking the C code. It results several code update to adjust Rust-libc with C-libc (see https://github.com/rust-lang-nursery/libc/pull/110 for all changes).

`blksize_t` change (for OpenBSD) is part of these changes:
  - switch to signed int32 in Rust-libc: https://github.com/semarie/libc/commit/b1a108c245a46ed69b8d3ad743aa5fd712431eca
  - definition of `__blksize_t` (which is same as `blksize_t`) under C-libc:  http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/sys/_types.h?rev=1.9&content-type=text/x-cvsweb-markup

**Comment by alexcrichton** [comment]
@aturon yes I suspect this to have far less breakage for two reasons:

* The `blksize_t` type is much more rarely used than `c_char`
* OpenBSD is also more rarely used right now than even Android

I suspect it won't take long to mitigate any breakage that comes up, even if it does so.

**Pull request merged**
