### PR TITLE
Add ThreadSanitizer test case

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by Centril** [comment]
I don't feel qualified to review this.

r? @hanna-kruppe @alexcrichton perhaps

**Comment by hanna-kruppe** [comment]
I am not familiar with the TSAN APIs used here or the test harness features this test relies on, but the reasoning in the comment seems good to me and the test code itself also looks good at a glance.

Is this test exercised by any of our builders? If so, is it among the checks that run on every PR or only run by bors?

**Comment by tmiasko** [comment]
They run on Linux x86_64-gnu and macOS x86_64-apple (not in any of PR runners, AFAIR).  Which reminds me that this should be fine to run on macOS and I adjusted the test accordingly.

**Comment by hanna-kruppe** [comment]
Alright, then I'll approve this now, otherwise I would have waited for the PR builders going green.

@bors r+

**Comment by Dylan-DPC** [comment]
>  otherwise I would have waited for the PR builders going green.

Not a problem, as it will take some time before this gets rolled up, and the try-CI will finish before that

**Pull request merged**
