### PR TITLE
Rename main theme into light theme

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Please also modify the text in `src/doc/rustdoc/src/unstable-features.md` so that the sections talking about `--themes` and `--theme-checker` mention the "light" theme instead of the "main" theme.

**Comment by GuillaumeGomez** [comment]
Done.

**Comment by QuietMisdreavus** [comment]
The docs you did change weren't even the ones i was thinking of, lol. It's these sections here: <https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html#--themes-provide-additional-themes>

**Comment by GuillaumeGomez** [comment]
Done as well.

**Pull request merged**
