### PR TITLE
Define c_char using cfg_if rather than repeating 40-line cfg

### PR DESCRIPTION
**Pull request by dtolnay**
Libstd has a 40-line cfg that defines the targets on which `c_char` is unsigned, and then repeats the same cfg with `not(…)` for the targets on which `c_char` is signed.

This PR replaces it with a `cfg_if!` in which an `else` takes care of the signed case.

I confirmed that `x.py doc library/std` inlines the type alias because c_char_definition is not a publicly accessible path:

Screenshot from 2021-12-07 13-42-07

### CODE REVIEW

**Comment by fee1-dead** [comment]
Looks like this caused a clippy test to fail in a rollup: https://github.com/rust-lang/rust/pull/91650#issuecomment-988520192. The stderr now tells users to remove cast to `c_char` which would actually break compilation for some platforms.

**Comment by dtolnay** [comment]
I filed https://github.com/rust-lang/rust-clippy/issues/8093 about the false positive and added a workaround in this PR. Tested by:

```rust
//#[cfg(all())]  // unnecessary_cast goes away if uncommented
type T = u8;

fn main() {
    let _ = 0 as T;
}
```

**Pull request merged**
