### PR TITLE
travis: Expand the `cross` linux image

### PR DESCRIPTION
**Pull request by alexcrichton**
This expands the `cross` travis matrix entry with a few more targets that our
nightlies are building:

* x86_64-rumprun-netbsd
* arm-unknown-linux-musleabi
* arm-unknown-linux-musleabihf
* armv7-unknown-linux-musleabihf
* mips-unknown-linux-musl
* mipsel-unknown-linux-musl

This commit doesn't compile custom toolchains like our current cross-image does,
but instead compiles musl manually and then compiles libunwind manually (like
x86_64) for use for the ARM targets and just uses openwrt toolchains for the
mips targets.

cc #38531

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @japaric, mind checking my logic on this?

**Comment by japaric** [comment]
LGTM. Just concerned about using Ubuntu's `arm-linux-gnueabihf-gcc` toolchain, which targets ARMv7 devices, to build the `arm-unknown-linux-musleabihf` toolchain / libunwind because that target = ARMv6+ devices. Setting CFLAGS takes care of generating ARMv6 compatible instructions from C code but if e.g. libunwind.a gets statically linked with some object from the `arm-linux-gnueabihf-gcc` toolchain, which was compiled for ARMv7, then that could introduce incompatible instructions.

**Comment by alexcrichton** [comment]
@japaric yeah my hope is that through the use of the musl wrapper scripts we avoid any usage of glibc objects as the wrapper scripts should point everything to the musl objects. I suppose we'll see though!

**Comment by alexcrichton** [comment]
@bors: r-

Building this docker image now produces too much output, so it needs to be hidden by default. I [fixed this](https://github.com/rust-lang/rust/pull/39199/commits/3fbe864375c9f2e9ba07b2891c3118b9afc134ec) in the rollup and hope to land that but we'll see how that goes.

**Pull request merged**
