### PR TITLE
[beta] Clippy backport ICE/infinite loop fix

### PR DESCRIPTION
**Pull request by flip1995**
Those commits are picked from the latest Clippy sync: #96735 

This fixed the issue https://github.com/rust-lang/rust-clippy/issues/8689

### CODE REVIEW

**Comment by flip1995** [comment]
ping @Mark-Simulacrum We'd like to get this in before beta branching tomorrow.

**Comment by Mark-Simulacrum** [comment]
The backport needs to be approved by either the clippy team or the compiler team.

Note that Friday is *next* beta branching, and that doesn't affect backport schedules, so while it's important to get this accepted or not quickly we're not on a rush to do so until beta branch on Friday.

**Comment by flip1995** [comment]
@rust-lang/clippy This backport moves the `only_used_in_recursion` lint to nursery and prevents it from running, if not explicitly enabled. I want to backport this infinite loop / ICE fix, because the lint is not really tested well enough and I have the suspicion that we'll see more of those infinite loops with this lint like it currently exists in beta. This infinite loop happens on long method chains and since builder patterns are popular in Rust, we can expect that this will happen often.

This still misses an approval of a Clippy team member and because I don't want to self-approve this, could someone else from the team take another look, please?

**Comment by Mark-Simulacrum** [comment]
Unilaterally approving for backport as we're somewhat pressed for time.

**Comment by Mark-Simulacrum** [comment]
Bundled into https://github.com/rust-lang/rust/pull/97014.

**Pull request closed without merging**
