### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by matklad**
r? @ghost

### CODE REVIEW

**Comment by jethrogb** [comment]
Commit `e65d48d1fb3d4d91d9dc1148a7a836ff5c9a3c87` doesn't exist in https://github.com/rust-analyzer/rust-analyzer

**Comment by matklad** [comment]
Hm?

https://github.com/rust-analyzer/rust-analyzer/commit/e65d48d1fb3d4d91d9dc1148a7a836ff5c9a3c87

Here it is, should be in the master branch as well.

**Comment by jethrogb** [comment]
Sorry, please ignore, I had my submodule setup messed up

**Pull request merged**
