### PR TITLE
Closes #28586

### LINKED ISSUE #28586: ICE: impl Foo for [u8; usize::BYTES]
I tried this code:

    pub trait Foo {}
    impl Foo for [u8; usize::BYTES] {}

I expected to see this happen: great success

Instead, this happened: error: internal compiler error: unexpected panic

## Meta

`rustc --version --verbose`:

    rustc 1.4.0-nightly (6873b9fee 2015-09-13)
    binary: rustc
    commit-hash: 6873b9fee4af732fe81d54fdcedbd31201e3edf0
    commit-date: 2015-09-13
    host: x86_64-apple-darwin
    release: 1.4.0-nightly

Backtrace:

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'path not fully resolved: PathResolution { base_def: DefPrimTy(TyUint(usize)), last_private: LastMod(AllPublic), depth: 1 }', ../src/librustc/middle/def.rs:82

    stack backtrace:
       1:        0x1121128d0 - sys::backtrace::tracing::imp::write::heea627b667abca63Y3s
       2:        0x11210fcfb - panicking::on_panic::hdbb29ca470ba8d91wSw
       3:        0x1120da292 - sys_common::unwind::begin_unwind_inner::h96272d8b0ab240cfv6r
       4:        0x1120dad6d - sys_common::unwind::begin_unwind_fmt::h9afcfd3cbded904aB5r
       5:        0x10ed9d260 - middle::const_eval::eval_const_expr_partial::h09b300ea76947f73LTk
       6:        0x10e87b052 - astconv::ast_ty_to_ty::hea6c277082e3ec36Hjx
       7:        0x10e8d365b - collect::convert_item::had78e6f690b64d6668y
       8:        0x10e8cf086 - collect::collect_item_types::h0cdd1ad21711c8b7Cky
       9:        0x10e91b84d - check_crate::hec1ce520a39b9d455BE
      10:        0x10e08f9ea - driver::phase_3_run_analysis_passes::closure.21862
      11:        0x10e07162a - middle::ty::ctxt<'tcx>::create_and_enter::h16774090565533553846
      12:        0x10e06ce35 - driver::phase_3_run_analysis_passes::h7058980529217618503
      13:        0x10e04d825 - driver::compile_input::hb180f9b5439d25130ba
      14:        0x10e1b22a0 - run_compiler::hed85d66f90e035a8qqc
      15:        0x10e1afb99 - boxed::F.FnBox<A>::call_box::h2035540886510390739
      16:        0x10e1af592 - sys_common::unwind::try::try_fn::h1377311635092239657
      17:        0x11210f638 - __rust_try
      18:        0x112103c60 - sys_common::unwind::try::inner_try::hcc9e69ddf677c559T2r
      19:        0x10e1af742 - boxed::F.FnBox<A>::call_box::h6878960542759305751
      20:        0x1121185dd - sys::thread::Thread::new::thread_start::h149e6b462b5fd2cfpqw
      21:     0x7fff99141059 - _pthread_body
      22:     0x7fff99140fd6 - _pthread_start

### PR DESCRIPTION
**Pull request by bltavares**
Cloases #28586

### CODE REVIEW

**Comment by brson** [comment]
Thanks @bltavares. Since this is a compile-fail test it needs to [indicate what the expected error is](https://github.com/rust-lang/rust-wiki-backup/blob/master/Note-testsuite.md#specifying-the-expected-errors-and-warnings). Can you modify the test to include an `^ERROR` line? You can test it with `make check-stage2-cfail TESTTNAME=issue-28586`.

**Comment by bltavares** [comment]
@brson sure thing. I just updated the branch and I'm running the tests locally.

**Comment by apasel422** [comment]
@brson Is the error code sufficient here, or do we want at least some of the message itself?

**Comment by sanxiyn** [comment]
Error code is sufficient.

**Pull request merged**
