### PR TITLE
Don't generate a branch hint for assertions in unoptimized builds

### PR DESCRIPTION
**Pull request by saethlin**
I've been staring a lot at our unoptimized LLVM IR to reduce the perf impact of https://github.com/rust-lang/rust/pull/104862 and I noticed this. Seems like an easy (if very small) win.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Wait, can you share more about the purpose of this PR? Doesn't seem like this has any effect.

@rustbot author

**Comment by saethlin** [comment]
This doesn't have any measurable effect _currently_. https://github.com/rust-lang/rust/pull/104862 contains this though, because it was an opportunity I noticed to generate less LLVM IR. I've significantly improved the compile time overhead of that PR (from about 40% to 4% primarily by just reducing the amount of IR that the checks generate, not by generating less checks). I am expecting to eventually have a `-Cextra-ub-checks` setting something like `thorough` or `aggressive` or `extreme` which will insert a niche check for every move of every reference. Which means in LLVM IR,

```
  %1 = icmp ne ptr %x, null
  %2 = call i1 @llvm.expect.i1(i1 %1, i1 true)
  br i1 %2, label %bb1, label %bb2
```
So for code like that, I expect that omitting a third of the instructions _will_ have an impact. We just don't generate much code like that yet.

And I personally prefer to not land separable optimizations in a PR that is likely to have overhead. The niche checks have overhead, and this PR reduces the overhead of Assert terminators. I'd rather not end up with a perf-neutral PR and people wondering "Where's the compile time overhead of adding all this code? Is it hidden by the improvement of this optimization you did?".

**Comment by compiler-errors** [comment]
> And I personally prefer to not land separable optimizations in a PR that is likely to have overhead. The niche checks have overhead, and this PR reduces the overhead of Assert terminators. I'd rather not end up with a perf-neutral PR and people wondering "Where's the compile time overhead of adding all this code? Is it hidden by the improvement of this optimization you did?".

I'm not certain if I understand this argument. On the flip side, I could say something like I don't understand why we're landing perf-neutral "optimizations" because they affect PRs we plan to land later on. I actually think it makes sense to co-locate regressions with the optimizations that most dramatically affect them.

**Comment by saethlin** [comment]
I think you understand the argument and just disagree with it :p

I'll just keep this change in the originating PR.

**Pull request closed without merging**
