### PR TITLE
std: Remove #[allow] directives in sys modules

### PR DESCRIPTION
**Pull request by alexcrichton**
These were suppressing lots of interesting warnings! Turns out there was also
quite a bit of dead code.

### CODE REVIEW

**Comment by aturon** [comment]
Nice!

@bors: r+ 2dbf199

**Comment by Manishearth** [comment]
```
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/libstd/sys/unix/backtrace.rs:87:5: 87:26 error: unused import, #[deny(unused_imports)] on by default
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/libstd/sys/unix/backtrace.rs:87 use os::unix::prelude::*;
                                                                                                       ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
make: *** [i686-apple-darwin/stage1/lib/rustlib/i686-apple-darwin/lib/stamp.std] Error 101
```

**Comment by Manishearth** [comment]
Might have caused this?

```
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:87:5: 87:26 error: unused import, #[deny(unused_imports)] on by default
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:87 use os::unix::prelude::*;
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:89:17: 89:24 error: unused import, #[deny(unused_imports)] on by default
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/backtrace.rs:89 use ffi::{CStr, AsOsStr};
                                                                                                                      ^~~~~~~
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:61:13: 65:14 error: unnecessary `unsafe` block, #[deny(unused_unsafe)] on by default
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:61             unsafe {
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:62                 let info = info();
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:63                 let diff = self.t as i64 - other.t as i64;
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:64                 Duration::nanoseconds(diff * info.numer as i64 / info.denom as i64)
/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-nopt-t/build/src/libstd/sys/unix/time.rs:65             }
error: aborting due to 3 previous errors
```

http://buildbot.rust-lang.org/builders/auto-mac-64-nopt-t/builds/4049/steps/compile/logs/stdio

**Comment by Manishearth** [comment]
```
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:337:9: 338:79 error: foreign function is never used: `pthread_getattr_np`, #[deny(dead_code)] on by default
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:337     pub fn pthread_getattr_np(native: libc::pthread_t,
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:338                               attr: *mut libc::pthread_attr_t) -> libc::c_int;
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:339:9: 340:83 error: foreign function is never used: `pthread_attr_getguardsize`, #[deny(dead_code)] on by default
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:339     pub fn pthread_attr_getguardsize(attr: *const libc::pthread_attr_t,
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:340                                      guardsize: *mut libc::size_t) -> libc::c_int;
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:341:9: 343:79 error: foreign function is never used: `pthread_attr_getstack`, #[deny(dead_code)] on by default
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:341     pub fn pthread_attr_getstack(attr: *const libc::pthread_attr_t,
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:342                                  stackaddr: *mut *mut libc::c_void,
/home/rustbuild/src/rust-buildbot/slave/auto-linux-64-x-android-t/build/src/libstd/sys/unix/thread.rs:343                                  stacksize: *mut libc::size_t) -> libc::c_int;
error: aborting due to 3 previous errors
```

**Pull request merged**
