### PR TITLE
Stabilize const_transmute_copy

### LINKED ISSUE #83165: Tracking Issue for const_transmute_copy
Feature gate: `#![feature(const_transmute_copy)]`

This is a tracking issue for making the function `mem::transmute_copy` `const fn`.

### Public API

```rust
mod mem {
    pub const unsafe fn transmute_copy<T, U>(src: &T) -> U;
}
```

### Steps / History

- [x] Implementation: #83091
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

### PR DESCRIPTION
**Pull request by Finomnis**
Closes #83165

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval @rust-lang/libs-api

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by cuviper** [comment]
r? libs-api

**Review by dtolnay — APPROVED** [review]

**Comment by RalfJung** [comment]
That's got to be noise.

**Pull request merged**
