### PR TITLE
Add error file for E0152

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
It completes #31818.

However it is not complete yet:
- test will need to be updated
- the file name displayed is a bit too unclear.

I'm not sure yet what's the "correct" file name to display. If anyone has an idea on this, it'd be very appreciated.

r? @brson

### CODE REVIEW

**Comment by brson** [comment]
Hm, the [span of the duplicate is not being printed](http://is.gd/MvrmwV).

After reviewing @Zoxc's comments on the issue I think what needs to happen is that span needs to be fixed so the error message prints the source location of the duplicate item as normal, then a second `note` should indicate further info about the previous definition.

The `self.session.local_crate_source_file` in use here isn't going to be helpful once the span is printing correctly. What we really want is the span of the *original* definition of the lang item, here represented by `original_def_id`.

**Comment by GuillaumeGomez** [comment]
@brson: I provided more information. Does it seem enough for you? If not, what could I add?

**Comment by GuillaumeGomez** [comment]
@brson: This is ready.

**Comment by brson** [comment]
Thanks @GuillaumeGomez.

Sadly, I think there's more to do here.

I didn't realize before that local definitions are checked *first* and then external definitions. That really changes my perspective on what this code does.

First [here](https://github.com/rust-lang/rust/pull/31957/files#diff-855fca46fb86dbacaee6e1226c2bd4a7R188), `self.ast_map.span_if_local(original_def_id).unwrap_or(span);`. I'm not sure that `span_if_local` will ever return `None`. It looks to be like it will always return `Some` since this check only fails if the duplicate is in the same crate. So the `unwrap_or` call should *I think* be something like `expect("we should have found a local duplicate earlier")`. Is my observation correct?

Second, rustc uses uncapitalized diagnostics by convention, so "Duplicate lang item found" should be "duplicate lang item found", "First defined here" should be "first defined here", "First defined in crate", should be "first defined in crate".

Next, in [this note](https://github.com/rust-lang/rust/pull/31957/files#diff-855fca46fb86dbacaee6e1226c2bd4a7R198) where the original def was in an external create, please do not call `span_note`, but just `note`, since the object of the note is not located at the span.

**Comment by GuillaumeGomez** [comment]
@brson: Updated.

**Comment by brson** [comment]
@bors r+

This looks really great now. Thanks for persevering.

**Pull request merged**
