### PR TITLE
submodules: update clippy from 71be6f62 to c0dbd34b

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Changes:
````
travis: disable rls integration test.
rustup https://github.com/rust-lang/rust/pull/61669/
Add OUTER_EXPN_INFO lint
````

Should fix clippy toolstate

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
wow, looks like I was too fast for highfive
r? @Manishearth

**Comment by Xanewok** [comment]
Looks spurious?

@bors retry

**Pull request merged**
