### PR TITLE
Implement `Write` for `Cursor<&mut Vec<u8>>`

### LINKED ISSUE #30132: Implement Read/Write on Cursor over &mut Vec
It is currently impossible to use a std::io::Cursor over a Vec in a smart pointer (Mutex, RefCell, ...) in a sane way. Please implement Read/Write/... over Cursor<&'a mut Vec<u8>>.

Discussed on [users.rust-lang.org](https://users.rust-lang.org/t/missing-implementation-of-cursor-for-a-derefmut-of-vec/3826).

### PR DESCRIPTION
**Pull request by Diggsey**
Fixes #30132

r? @dtolnay (I'm just going through `feature-accepted` issues I swear 😛)

### CODE REVIEW

**Comment by kennytm** [comment]
Thanks for the PR! We’ll periodically check in on it to make sure that @dtolnay or someone else from the team reviews it soon.

**Review by dtolnay — APPROVED** [review]
Thanks! The implementation looks good to me. Let's run it by the rest of the libs team though.

**Comment by dtolnay** [comment]
@rust-lang/libs this adds the following impl. This is important for being able to write to a Vec owned by a Mutex or similar.

```rust
impl<'a> Write for Cursor<&'a mut Vec<u8>>
```

@rfcbot fcp merge

**Comment by est31** [comment]
Thank you @Diggsey !

**Comment by clouds56** [comment]
Should we mention the behavior of resize in the document? (otherwise one might not sure if `Cursor<&mut Vec<u8>>` would do the same as `Cursor<&mut [u8]>`)

> Cursors are used with in-memory buffers, anything implementing AsRef<[u8]>, to allow them to implement Read and/or Write, allowing these buffers to be used anywhere you might use a reader or writer that does actual I/O. **the buffer of `Cursor<&mut [u8]>` would not be increased when the space runs out while `Cursor<Vec<u8>>` and `Cursor<&mut Vec<u8>>` would just like an actual file.**

I'd like to provide File-like in-memory buffer to some API accept `W: Write`, it takes me time to find out I could use `Cursor<&mut Vec<u8>>` before I see this PR.

**Pull request merged**
