### PR TITLE
Add new E0762 error code

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by doctorn** [comment]
I'm trying to add `E0761` in #73122, do you want to change or should I?

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/73122.

**Comment by petrochenkov** [comment]
Ah, these are different errors.
This PR can use a different code then.

**Comment by GuillaumeGomez** [comment]
Updated!

**Pull request merged**
