### PR TITLE
add missing 'static lifetime in docs

### PR DESCRIPTION
**Pull request by mulimoen**

### CODE REVIEW

**Comment by rkruppe** [comment]
Thanks for the PR! Just to avoid misunderstandings, could you say a bit about why you want to add the lifetime annotation? It isn't necessary to make this correct Rust (in `const`s and `static`s, omitted lifetimes default to `'static`) but if the argument is that it's less confusing or something, that's fine by me!

**Comment by mulimoen** [comment]
The docs explains what can be constants, including `&'static`. There are two examples showing this, one with the `static` lifetime, and then one showing how the compiler can elide this.

**Comment by mulimoen** [comment]
https://doc.rust-lang.org/std/keyword.const.html is confusing as it refers to an explicit lifetime that is not visible in the docs (`'static`).

**Comment by rkruppe** [comment]
Oh, I see, that makes a lot of sense. Thanks!

@bors r+ rollup

**Pull request merged**
