### PR TITLE
Add llvm debuginfo configure option

### LINKED ISSUE #37738: add build option for LLVM debug info
See relevant discussion in #31033. We probably want control of LLVM debuginfo independent of `--disable-optimize-llvm`. That's currently the only way to get debug symbols in LLVM (that I know of).

I suggested in the above issue that we call the option `--enable-llvm-debuginfo`.

CC @nnethercote @nagisa

### PR DESCRIPTION
**Pull request by mrhota**
CC @nnethercote @Mark-Simulacrum 

We add a new configure option, `--enable-llvm-debuginfo`, to do exactly what you'd think.

Re: #31033 

Fixes #37738

### CODE REVIEW

**Comment by nagisa** [comment]
There’s at least two things missing:

1. Corresponding changes to rustbuild (src/bootstrap) and build scripts (src/librustc_llvm/build.rs);
2. Possibly debug info generation for llvm wrapers (in src/rustllvm)

**Comment by TimNN** [comment]
Note that rustbuild already includes support for `RelWithDebInfo` (since a few days ago, actually).

So the only thing to be done for rustbuild (I think) is to add a line like

```rust
("LLVM_DEBUGINFO", self.llvm_release_debuginfo),
```

here: https://github.com/rust-lang/rust/blob/master/src/bootstrap/config.rs#L342

**Comment by mrhota** [comment]
@TimNN hmm, should I change the name of the `--enable-llvm-debuginfo` option? I didn't know anything about rustbuild until _just now_!

**Comment by TimNN** [comment]
@mrhota: I'm honestly not sure. When choosing the name for rustbuild, I went with `llvm_release_debuginfo` because it seemed more accurate: We already had `llvm-optimize`, which, if not enabled, always included debuginfo, so the new setting is really only applicable when`llvm-optimize` is enabled.

So one could argue to use `--enable-llvm-release-debuginfo` for consistency & accuracy or for `--enable-llvm-debuginfo` since it's shorter / easier to remember. (Note that for rustbuild, we have a `config.toml` file and the option is present in the `[llvm]` section so it's only called `release-debuginfo`).

I think I would just stay with `--enable-llvm-debuginfo`.

**Comment by mrhota** [comment]
@nagisa After glancing through the code, I don't think `rustllvm` needs any changes. I wouldn't know how or where to make those changes, though, so maybe someone with more expertise should weigh in.

**Comment by mrhota** [comment]
@TimNN hehe too late! :smile: I decided to go with your name: I agree it's more accurate. Moreover, it seems like maybe we're moving toward deprecating the configure system, so option names there might be less important. /me shrugs.

**Comment by mrhota** [comment]
cc @alexcrichton I think this is complete, but I might have missed something (esp. in rustbuild). Thoughts?

**Comment by alexcrichton** [comment]
@bors: r+

Looks great to me, thanks @mrhota!

**Comment by nnethercote** [comment]
Note to anyone following along: the final name chosen for the configure option was --enable-llvm-release-debuginfo.

**Comment by nnethercote** [comment]
I just tried this option. I'm using configure/make to build, not rustbuild. It's not working, as far as I can tell. I did "make clean", configured with `--enable-optimize --enable-debuginfo --enable--llvm-release-debuginfo`, rebuilt the compiler. But my profiles of the compiler still lack filenames and line numbers for LLVM functions.

Is there some way I can check the resulting rustc binary for the debuginfo? I'm on Linux.

**Comment by TimNN** [comment]
@nnethercote: I haven't used the make based system in a long time, however I *think* that `make clean` may not clean llvm, so you may want to try and manually remove the llvm build dir.

**Comment by mrhota** [comment]
@TimNN @nnethercote there is a `make clean-llvm` command, too. But I don't know if it does what you'd think it does. I just deleted the build dir.

**Comment by nnethercote** [comment]
Deleting the build dir fixes the problem -- I'm now getting files and line numbers for LLVM in my profiling output. Thanks!

**Pull request merged**
