### PR TITLE
Document non-obvious behavior of fmt::UpperHex & co for negative integers

### PR DESCRIPTION
**Pull request by SimonSapin**
Before stabilization I’d have suggested changing the behavior,  but that time is past.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Maybe these doc-comments should be on respective `impl`s instead?

**Comment by kennytm** [comment]
Reassigning to docs team — r? @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Sounds good. Thanks!

@bors: r+ rollup

**Comment by cmcqueen** [comment]
> Before stabilization I’d have suggested changing the behavior, but that time is past.

Is there any chance this can be changed in a Rust edition? Eg the upcoming 2021 edition.

**Comment by kennytm** [comment]
No, the runtime behavior is edition-agnostic in the since they share the same libcore. That means we either change it for all of 2015/2018/2021 starting from Rust 1.XX or never change it.

**Pull request merged**
