### PR TITLE
Stabilize some `ascii_ctype` methods

### LINKED ISSUE #39658: <ctype.h> functions for AsciiExt
As discussed at https://internals.rust-lang.org/t/improvements-to-asciiext/4689 I have added `is_ascii_*` equivalents of most (not quite all) of C's `ctype.h`'s `isxxx` functions to the AsciiExt trait.

The new functions are

 * `is_ascii_alphabetic`
 * `is_ascii_uppercase`
 * `is_ascii_lowercase`
 * `is_ascii_alphanumeric`
 * `is_ascii_digit`
 * `is_ascii_hexdigit`
 * `is_ascii_punctuation`
 * `is_ascii_graphic`
 * `is_ascii_whitespace` (matches the [Infra Standard definition of ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace), *not* POSIX)
 * `is_ascii_control`

They are implemented for `char`, `u8`, `str`, and `[u8]`, and, for backward compatibility with external trait implementations, have default implementations that call `unimplemented!()`.

PR to follow, but I needed to file this bug in order to get an issue number to put in the stability annotations.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
As discussed in #39658, this PR stabilizes those methods for `u8` and `char`. All inherent `ascii_ctype` for `[u8]` and `str` are removed as we prefer the more explicit version `s.chars().all(|c| c.is_ascii_())`.

This PR doesn't modify the `AsciiExt` trait. There, the `ascii_ctype` methods are still unstable. It is planned to remove those in the future (I think). I had to modify some code in `ascii.rs` to properly implement `AsciiExt` for all types. 

Fixes #39658.

### CODE REVIEW

**Comment by kennytm** [comment]
@LukasKalbertodt The *current* nightly version is 1.23.0, unless you mean to backport these to the current beta.

**Comment by LukasKalbertodt** [comment]
@kennytm Oops, nope, I confused things here. So I change my latest commit to `since = "1.24.0"`, yes?

**Comment by kennytm** [comment]
Make them 1.23.0 for now. We can backport it to the *next* beta if it didn't make it.

**Comment by LukasKalbertodt** [comment]
Ok done. Thanks!

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Awesome, thanks @LukasKalbertodt!

**Comment by alexcrichton** [comment]
@bors: r+

Thanks again @LukasKalbertodt!

**Comment by kennytm** [comment]
@rust-lang/libs Just to confirm — are we going to backport this to 1.23?

**Comment by Mark-Simulacrum** [comment]
Unmarking as beta-nominated. We basically never want to backport stabilizations with current policy.

**Comment by kennytm** [comment]
The versions needs to be changed to 1.24 in this case.

**Comment by LukasKalbertodt** [comment]
@kennytm @Mark-Simulacrum changed it to 1.24

**Comment by LukasKalbertodt** [comment]
This error doesn't look like it has anything to do with my changes... :confused: Right? What shall I do now?

**Pull request merged**
