### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #98582 (Allow destructuring opaque types in their defining scopes)
 - #99213 (migrate some of `rustc_passes::check_attr`'s diagnostics and derive improvements)
 - #99258 (Provide structured suggestion for dropped temp value)
 - #99259 (interpret/visitor: support visiting with a PlaceTy)
 - #99287 ([rustdoc-json] JSON no longer inlines)
 - #99290 (Revert "Highlight conflicting param-env candidates")
 - #99316 (docs: add missing word)
 - #99317 (Borrow Vec<T, A> as [T])
 - #99323 (Fix flakyness of GUI tests)
 - #99342 (Avoid some `Symbol` to `String` conversions)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=98582,99213,99258,99259,99287,99290,99316,99317,99323,99342)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I did some speculative testing https://github.com/rust-lang/rust/pull/99368 https://github.com/rust-lang/rust/pull/99370 https://github.com/rust-lang/rust/pull/99369
and it seems that the regression is caused by https://github.com/rust-lang/rust/pull/98582 , results of the revert: in   https://github.com/rust-lang/rust/pull/99368 :
https://perf.rust-lang.org/compare.html?start=1cd72b734318720adb99dc72147bb8169ef76ffe&end=f3aa1baa95ecd1fed574085c44f597a1de226da5&stat=instructions:u

**Comment by matthiaskrgr** [comment]
cc @oli-obk

**Comment by rylev** [comment]
Thank you very much for the investigation! Going to labeled this as triaged since we have identified the cause.

@rustbot label: +perf-regression-triaged

**Pull request merged**
