### PR TITLE
fix clippy::assigning_clones, instead of x = y.clone() use x.clone_from(y)

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
curious about the perf here
@bors try @rust-timer queue

**Comment by matthiaskrgr** [comment]
open source protip: actually committing all the changes immensely helps with not breaking the build!
 @bors try @rust-timer queue

**Comment by matthiaskrgr** [comment]
I ate the dogfood and reverted the cases where clippy would say we could use `clone_from` on `self` inside a `clone_from` impl :D 

 @bors try @rust-timer queue

**Comment by workingjubilee** [comment]
@matthiaskrgr Did you report the clippy-suggests-clone-from-inside-clone-from issue upstream?

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust-clippy/issues/12600

**Comment by workingjubilee** [comment]
Cool, thanks!

**Pull request closed without merging**
