### PR TITLE
Feature-gate #![no_std] and fix most syntax extensions

### LINKED ISSUE #21833: Feature-gate #[no_std]
It breaks various things at the syntax layer, e.g.  #21827, #16803, #14342.  I plan to fix those before the beta but I'm not sure what other issues there are.

### PR DESCRIPTION
**Pull request by kmcallister**
Fixes #21833.

[breaking-change]

r? @alexcrichton 

The tests in #21912 will also need `#[feature(no_std)]`. If you're okay with both PRs, I can merge and test them.

### CODE REVIEW

**Comment by kmcallister** [comment]
This causes problems in pretty printing, which I'm fixing.

**Comment by kmcallister** [comment]
Still not quite right...

**Comment by kmcallister** [comment]
Okay, this includes #21912 and is passing local tests.

**Comment by alexcrichton** [comment]
Nice! I think the entire `fmt` module can move to libcollections in fact, and other than that r=me

**Comment by kmcallister** [comment]
Rebased, and fixed that new test case.

**Pull request merged**
