### PR TITLE
Remove meaningless comments in src/test

### PR DESCRIPTION
**Pull request by sd234678**
Moved from #63411

### CODE REVIEW

**Review by Centril — APPROVED** [review]
r=me rollup when green

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/63617#issuecomment-521843756, @bors r-
You'll also need `--bless --compare-mode=nll`.

**Comment by sd234678** [comment]
@Centril do I need to do anything else to get bors to pick this back up?

**Comment by Centril** [comment]
@sd234678 I need to reapprove the PR when you make a change. However, when you force-push I don't get a notification so you have to leave a comment instead if you want me to see it.

@bors r+

**Pull request merged**
