### PR TITLE
configure: Disable rpass-valgrind when there's no valgrind

### PR DESCRIPTION
**Pull request by richo**
This stung me more than once in dev.

Bonus DRY'ing up of configure that I did on my way past.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm I'm a little hesitant to do this as it will silently stop running all valgrind tests on the bots if we reimage and forget to install valgrind.

**Comment by brson** [comment]
I have another patch that makes configure error if valgrind isn't available: https://github.com/rust-lang/rust/pull/24477. Personally, I do not like requiring valgrind to configure and build and might be in favor of this.

**Comment by richo** [comment]
I'd be in favour of tweaking this patch to make `configure` error if you pass `--enable-valgrind` and it can't be found. @alexcrichton is it plausible to just ensure that the builders pass that flag when they're configuring?

**Comment by alexcrichton** [comment]
@richo that seems reasonable, but it also seems like #24477 does that?

**Comment by richo** [comment]
It looks like #24477 will fail by default if valgrind isn't present, which I don't believe to be the behaviour we want to expose to end users. I'll probably update this patch tonight but I don't have a particular horse in this race, eg I'd be perfectly content with an updated version of @brson's that won't break by default without valgrind.

**Comment by richo** [comment]
I updated the branch. It'll now fail if you do something like:

    ./configure --enable-valgrind

and don't have a valgrind, otherwise it will just disable the valgrind rpass tests

**Comment by pnkfelix** [comment]
@alexcrichton Is the idea that we first land this, and then after it is landed, we update the bots ASAP to pass `--enable-valgrind` ?

Or do we already pass `--enable-valgrind` on the bots?

**Comment by alexcrichton** [comment]
Looks like we're currently passing `--disable-valgrind`, so yes we'd have to change the bots.

**Comment by brson** [comment]
OK, so as I understand it this patch turns on valgrind-rpass by default *if* valgrind exists, but otherwise silently disables it. If --enable-valgrind is passed explicitly and valgrind does not exist then this emits a new error.

@richo I'm sorry for the delay and hate to ask you to do more, but can you add a warning message to [mk/main.mk](https://github.com/rust-lang/rust/blob/master/mk/main.mk#L197) saying that valgrind-rpass was disabled, similar to the existing case where it prints a status message when it is enabled. Since this case is missing some test coverage it's important to point that out I think.

**Comment by brson** [comment]
r=me after that nit is addressed

**Comment by richo** [comment]
Sorry for delay, added the log message.

r? @brson

**Comment by brson** [comment]
@acrichto @pnkfelix What do you anticipate changing on the bots when this patch lands? I don't see it (maybe I don't actually understand this patch...). I think all that will happen is [this](https://github.com/rust-lang/rust/pull/24859/files#diff-e2d5a00791bce9a01f99bc6fd613a39dR745) will run on machines w/o valgrind and disable the valgrind-rpass tests.

On closer inspection I don't understand how the valgrind-rpass code works.

**Comment by richo** [comment]
Err, wait yeah I think I might have goofed at some point in a rebase. Sorry this pr is weeks old and I don't really remember how it works either. Want to r- and I'll have a closer peek today? Apologies!

**Comment by richo** [comment]
EDIT: No, it does the correct thing (CFG_VALGRIND is populated by probing for a valgrind binary on PATH)

**Comment by alexcrichton** [comment]
@brson I think we'd want to pass `--enable-valgrind` on the machines where we expect `rpass-valgrind` to run (so it's a configure error if we forget to install valgrind). I'd have to check though to make sure that `--enable-valgrind` only enables it for tests.

**Pull request merged**
