### PR TITLE
Add long diagnostics for E0015 and E0020.

### PR DESCRIPTION
**Pull request by nham**
Part of #24407.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Looks good to me :+1:

**Comment by alexcrichton** [comment]
Thanks @nham! r=me with @lfairy's comment

**Comment by nham** [comment]
Thanks, I've fixed the wording in E0015.

**Comment by nham** [comment]
I rebased on top of master.

**Comment by alexcrichton** [comment]
Closing in favor of the merged version at #24542

**Pull request closed without merging**
