### PR TITLE
Stabilize a few secondary macro features

### LINKED ISSUE #44690: Tracking issue: RFC 2103 - attributes for tools
Support scoped attributes for white-listed tools, e.g., `#[rustfmt::skip]`

[RFC](https://github.com/rust-lang/rfcs/blob/master/text/2103-tool-attributes.md)
[discussion thread](https://github.com/rust-lang/rfcs/pull/2103)

- [x] implement for attributes ([mentoring instructions here](https://github.com/rust-lang/rust/issues/44690#issuecomment-331979427))
- [ ] implement for lints (https://github.com/rust-lang/rust/pull/52018; see https://github.com/rust-lang/rust/issues/44690#issuecomment-405749334)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

Current status: stabilised for attributes, some work still to do on lints.

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

### PR DESCRIPTION
**Pull request by petrochenkov**
- `tool_attributes` - closes https://github.com/rust-lang/rust/issues/44690
- `proc_macro_path_invoc` - this feature was created due to issues with tool attributes (https://github.com/rust-lang/rust/issues/51277), those issues are now fixed (https://github.com/rust-lang/rust/pull/52841)
- partially `proc_macro_gen` - this feature was created due to issue https://github.com/rust-lang/rust/issues/50504, the issue is now fixed (https://github.com/rust-lang/rust/pull/51952), so proc macros can generate modules. They still can't generate `macro_rules` items though due to unclear hygiene interactions.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This looks good to me, thanks!

I'll defer to..

r? @nrc 

though because I want to make sure the `tool_attributes` feature is ready to be stabilized.

**Comment by Havvy** [comment]
Other than that procedural macros can generate modules now (yay!), what else here that's being stabilized and needs to be documented in the reference?

**Pull request merged**
