### PR TITLE
Check whether the next_node is else-less if in get_return_block

### LINKED ISSUE #124819: Incorrect span label when non-() else-less `if` is tail expression in `-> ()` function
### Code

```Rust
fn main() {
    if true {
        ""
    }
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
1 | fn main() {
  |          - expected `()` because of default return type
2 |     if true {
3 |         ""
  |         ^^ expected `()`, found `&str`
```

### Desired output

```Shell
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
2 | /     if true {
3 | |         ""
  | |         ^^ expected `()`, found `&str`
4 | |     }
  | |_____- expected this to be `()`
```

### Rationale and extra context

When the `if` is *not* the tail expression, we provide the right output. We might just have to change the order of operation when looking for additional context to print.

### Other cases

`if true { "" } else { "" }` as tail expression has the same problem.

### Rust Version

All checked, current version 1.78.

### PR DESCRIPTION
**Pull request by cardigan1008**
Fix #124819

### CODE REVIEW

**Comment by pnkfelix** [comment]
can you add a unit test illustrating the change?

(If you need help with what steps to use to add a test, feel free to ask; I'd probably start by reading this https://rustc-dev-guide.rust-lang.org/tests/ui.html )

**Comment by cardigan1008** [comment]
Hi @pnkfelix I have updated the unit test following the instruction. If there's any mistake, feel free to ask me to change. Thanks!

**Pull request merged**
