### PR TITLE
return inner error of std:io::Error as source/cause

### LINKED ISSUE #124513: unexpected behaviour for Custom `std::io::Error` source implementation
At the time of writing this bug ticket, `std::io::Error`'s source implementation is as follows:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
impl error::Error for Error {
    fn source(&self) -> Option<&(dyn error::Error + 'static)> {
        match self.repr.data() {
            ErrorData::Os(..) => None,
            ErrorData::Simple(..) => None,
            ErrorData::SimpleMessage(..) => None,
            ErrorData::Custom(c) => c.error.source(),
        }
    }
}
```

If you call:

```rust
std::io::Error::new(ErrorKind::Other, MyError).source()
```

with `MyError` being defined as:

```rust
struct MyError
```

Then that source will be `None`.

Seems to me like a bug? How so is there no source?

If you want something deeper, or even as far as the "root cause" then it is up to the user to go deeper, no? Because now let's consider:

```rust
struct WrapError(Box<dyn Error + 'static>);
// assuming `WrapError::source` returns `Some(self.0.as_ref())`
```

And now call:

```rust
std::io::Error::new(ErrorKind::Other, WrapError(MyError.into())).source()
```

Now my source is `MyError`.

Which means that `WrapError` is invisible to the user. If you argument is now, great right, because the actual root cause was returned. Well yes, you are correct, but that is only a side-effect and is neither expected and neither will it hold up as soon as you add one more layer...

To be fair I never create `std::io::Error` myself, I only discovered it as I was using it for a test case out of laziness. It's because I have a custom error module to easily go through the chain of errors, for which I use the source. This has always worked out for me with the assumption that source returns the wrapped error if there is any. And the chain stops when that returns None.

AFAIK that is also what `anyhow` relies upon, a crate I do not use myself but which is commonly used in the Rust community, so that's why I do reference it here for extra context.

But my chain logic and anyhow's logic alike fails if somewhere in the "chain" there is an `std::io::Error`. Then again not sure when you would ever look for something lower then the `std::io::Error`, but I can imagine that some low level http-like crate might use that for some reason? Not sure. Either way, it's behaviour that surprised me.

Whether that's wrong or I am just having wrong assumptions that I am not certain of.

Instead I would expect that source to be implemented as:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
impl error::Error for Error {
    fn source(&self) -> Option<&(dyn error::Error + 'static)> {
        match self.repr.data() {
            ErrorData::Os(..) => None,
            ErrorData::Simple(..) => None,
            ErrorData::SimpleMessage(..) => None,
            // instead of: `c.error.source()`
            ErrorData::Custom(c) => Some(c.error.as_ref()),
        }
    }
}
```

Which would then correctly give me the next error in the chain (the inner error of `std::io::Error`.

### Meta

`rustc --version --verbose`:
```
rustc 1.77.1 (7cf61ebde 2024-03-27)
binary: rustc
commit-hash: 7cf61ebde7b22796c69757901dd346d0fe70bd97
commit-date: 2024-03-27
host: aarch64-apple-darwin
release: 1.77.1
LLVM version: 17.0.6
```

### PR DESCRIPTION
**Pull request by GlenDC**
Proposed solution to close #124513

Not sure if this should be seen as a breaking change or not.

See for more context #124513.

### CODE REVIEW

**Comment by workingjubilee** [comment]
cc @thomcc apparently you were the last to touch this.

**Comment by a1phyr** [comment]
As you noted in #124513, this would break a lot code, so I don't think that this can be merged.

Additionally, this makes an `io::Error` and its source have the same `Display` impl, which is... not great. The current state of affairs enable having an error with a custom message and while still choosing the source.

In your case, you probably need a wrapper (as you have shown works) or use `into_inner`/`downcast`.

The fact that you were confused by this may be sign that it be better documented, though.

**Comment by GlenDC** [comment]
@a1phyr downcast is not a universal thing though. So based on your answer I seem to understand that `source` does not at all work like I think it supposed to do...

But that also means that approaches such as the one taken by https://docs.rs/anyhow/latest/anyhow/struct.Error.html#method.chain (not something I use, but it's close enough), are flawed? As these rely upon source. And once you start to skip errors (persistent or at random) things get confusing very quickly.

Downcast sounds great, but it's not part of the `Error` contract, so no way to rely on that either.
So if not source is to be used, what is?!

**Comment by bjorn3** [comment]
For custom errors, `io::Error` effectively acts as transparent wrapper around the inner error. This means that the `Display` impl and `Error` impl delegates to the inner error (except the `provide` method seems to have been missed). The outer `io::Error` disappears entirely. Only for the errors returned by the standard library itself or `io::Error::last_os_error()`/`io::Error::from_raw_os_error()` does it show up as itself. In those cases there is no inner error to delegate to. Because of being a transparent wrapper around the inner error in case of the custom error case, the only data lost is the `ErrorKind`.

**Comment by GlenDC** [comment]
Fair enough. I trust you all in this. Much respect.

Most important for me here is that I understand the intended behaviour behind ::source() as a concept.

I understand that no one is making random io errors and I get that there are no guarantees that people use the trait contract correctly.

Most important for me is just to know what source exactly is supposed to do. Are you always supposed to call inner.source? Should you never do it. Is it undefined and is there no real meaning to source? That's the thing I'm still confused about.

**Comment by workingjubilee** [comment]
It is more than "do people use the trait contract correctly", the issue is that `Error::source` is a provided method, so the default implementation is None, so many will simply implement it and not think about overriding it:

https://doc.rust-lang.org/1.77.2/src/core/error.rs.html#83-86

**Comment by workingjubilee** [comment]
When an implementation overrides `Error::source`, it should present the lower-level source of that error. The reason that the `io::Error` version "skips over" the `io::Error` and moves directly to the custom error is that when you present a custom error as an `io::Error`, that means it **is the Error**. It is adhering to the contract of [`io::Error::new`](https://doc.rust-lang.org/std/io/struct.Error.html#method.new). There is not intended to be any difference.

**Pull request closed without merging**
