### PR TITLE
Make clipboard button copy crate version too instead of just crate_name

### LINKED ISSUE #106990: Clipboard button should copy version for crate, not just the name
Take https://docs.rs/tokio/1.24.1/tokio/index.html as an example: clicking the clipboard will copy `tokio` to the clipboard, but ideally it would copy `tokio = "1.24.1"`, like https://docs.rs/crate/tokio/latest does. Rustdoc already has this information because it shows the crate version in the sidebar.

### PR DESCRIPTION
**Pull request by atsuzaki**
Fixes #106990

Now clipboard button will copy `crate_name = "0.1.0"`.

r? @jyn514

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for the PR! We will review it once we agree that we want this change.

**Comment by atsuzaki** [comment]
@GuillaumeGomez oh I thought this issue was ready to work on. Sorry for jumping on this so soon before you guys got a chance to talk about whether you want the change or not!

**Comment by GuillaumeGomez** [comment]
No problem. I think no expected to get a contributor this soon. ^^'

**Comment by KittyBorgX** [comment]
@rustbot author 
@atsuzaki Hey! It looks like there are some merge conflicts in your PR. Can you sort them out?
Once you're done type in `@rustbot review` here so that the label can be changed to `S-waiting-on-review` and your PR should be good for a review!

**Comment by jyn514** [comment]
I'm going to close this for now, sorry :( I still think this is a good change but there's no point making work for you if it's not going to be accepted.

**Pull request closed without merging**
