### PR TITLE
[stable]: Prepare the 1.25.0 stable release

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors retry

Uhh... Segfault on osx?

**Comment by kennytm** [comment]
This feels like #48866.

**Comment by kennytm** [comment]
@bors retry

```
/Users/travis/.rvm/gems/ruby-2.2.5/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/xml/doc_builder.rb:64:in `encode': dlopen(enc/trans/escape.so, 9): image not found - enc/trans/escape.so (LoadError)
```

**Comment by kennytm** [comment]
@bors retry #48866. 

If this failed due to segfault again, I suggest we backport #48891 immediately.

**Pull request merged**
