### PR TITLE
Add per-stage RUSTFLAGS: RUSTFLAGS_STAGE_{0,1,2} and RUSTFLAGS_STAGE_NOT_0

### LINKED ISSUE #47658: extend x.py so it is easy to pass custom -Z flags when building after stage 0
We'd like to start trying to bootstrap with `-Znll` enabled. From what I can tell, there is no easy way to do this at present: using `RUSTFLAGS=-Znll` will cause the flag to be passed to **all** stages, but the support for NLL in stage0 is not up to the task.

We could extend x.py to support `RUSTFLAGS_STAGE{0,1,2}` (which would get "copied into" the RUSTFLAGS environment when building stage 0, 1, or 2.

Or we could make some kind of flag.

It might also be nice to just support `RUSTFLAGS_NOT_STAGE0` since usually that's what you want.

Or maybe there's an existing solution here?

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Fixes #47658.

r? @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @nikomatsakis @eddyb

**Comment by alexcrichton** [comment]
r=me, but looks like tidy is failing?

**Pull request merged**
