### PR TITLE
bump Miri

### LINKED ISSUE #70894: `miri` no longer builds after rust-lang/rust#70884
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#70884, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @Dylan-DPC, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
r? @ghost Cc @rust-lang/miri

Fixes https://github.com/rust-lang/rust/issues/70894

### CODE REVIEW

**Comment by RalfJung** [comment]
Toolstate fix
@bors r+ p=1

**Comment by pietroalbini** [comment]
@bors p=1001

Let's try again.

**Comment by RalfJung** [comment]
@bors retry
(to get it in the queue again)

**Comment by RalfJung** [comment]
With all this yielding going on, it looks like we no longer actually prioritize toolstate fixes after all? When can we expect this to land?

**Comment by Centril** [comment]
(I yielded this because my rollup spuriously failed; that's always something I do with any rollup. I do not think we should have 3 toolstate fixes in a row overtake rollups.)

**Comment by RalfJung** [comment]
It's more like rollups overtaking toolstate fixes, given the priorities of the underlying PRs.

**Comment by RalfJung** [comment]
Thanks. :)

**Pull request merged**
