### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #120358 (Bump Fuchsia, build tests, and use 8 core bots)
 - #120402 (Make the coroutine def id of an async closure the child of the closure def id)
 - #120420 (Stop using derivative in rustc_pattern_analysis)
 - #120425 (Remove unnecessary unit returns in query declarations)
 - #120428 (hir: Two preparatory changes for #120206)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=120358,120402,120420,120425,120428)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
well, tempted to just rollup=iffy all 5 and call it a day :|

**Comment by fmease** [comment]
> The job `x86_64-apple-1` failed!

> ```
> ---- core::config::config::tests::detect_src_and_out stdout ----
> downloading https://static.rust-lang.org/dist/2023-12-22/rust-std-beta-x86_64-apple-darwin.tar.xz
> extracting /tmp/cache/2023-12-22/rust-std-beta-x86_64-apple-darwin.tar.xz to /tmp/x86_64-apple-darwin/stage0
> downloading https://static.rust-lang.org/dist/2023-12-22/rustc-beta-x86_64-apple-darwin.tar.xz
> extracting /tmp/cache/2023-12-22/rustc-beta-x86_64-apple-darwin.tar.xz to /tmp/x86_64-apple-darwin/stage0
> downloading https://static.rust-lang.org/dist/2023-12-22/cargo-beta-x86_64-apple-darwin.tar.xz
> thread 'core::config::config::tests::detect_src_and_out' panicked at /Users/runner/work/rust/rust/src/tools/build_helper/src/util.rs:18:9:
> status code: 1
> 
> 
> failures:
>     core::config::config::tests::detect_src_and_out
> ```

@onur-ozkan Any idea what might've happened here?

**Comment by onur-ozkan** [comment]
> > The job `x86_64-apple-1` failed!
> 
> > ```
> > ---- core::config::config::tests::detect_src_and_out stdout ----
> > downloading https://static.rust-lang.org/dist/2023-12-22/rust-std-beta-x86_64-apple-darwin.tar.xz
> > extracting /tmp/cache/2023-12-22/rust-std-beta-x86_64-apple-darwin.tar.xz to /tmp/x86_64-apple-darwin/stage0
> > downloading https://static.rust-lang.org/dist/2023-12-22/rustc-beta-x86_64-apple-darwin.tar.xz
> > extracting /tmp/cache/2023-12-22/rustc-beta-x86_64-apple-darwin.tar.xz to /tmp/x86_64-apple-darwin/stage0
> > downloading https://static.rust-lang.org/dist/2023-12-22/cargo-beta-x86_64-apple-darwin.tar.xz
> > thread 'core::config::config::tests::detect_src_and_out' panicked at /Users/runner/work/rust/rust/src/tools/build_helper/src/util.rs:18:9:
> > status code: 1
> > 
> > 
> > failures:
> >     core::config::config::tests::detect_src_and_out
> > ```
> 
> @onur-ozkan Any idea what might've happened here?

I don't see any helpful information in the log. I would give it another shot since the previous attempts didn't have this issue.

**Pull request closed without merging**
