### PR TITLE
Structured errors

### PR DESCRIPTION
**Pull request by nrc**
As discussed [here](https://internals.rust-lang.org/t/more-structured-errors/3005)

r? @nikomatsakis or anyone else on the @rust-lang/compiler team

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Travis fails because there's a double `where` is the parser: https://github.com/nrc/rust/blob/5b7665010cb0a36e377c08d535db442d0a3ce203/src/libsyntax/parse/parser.rs#L752-L753

**Comment by nrc** [comment]
Whoops, forgot the new commit

**Comment by aturon** [comment]
cc @rust-lang/compiler

**Comment by nrc** [comment]
Addressed the doc comment thing.

The problem with the Option thing was that using the StructErr was painful - lots of weird maps and as_mut stuff. Using the dummy thing is much cleaner to use, although a little bit less clear what is going on.

**Pull request merged**
