### PR TITLE
incr.comp.: Take names of children into account when computing the ICH of a module's HIR.

### LINKED ISSUE #40876: ICH: IDs of items within a hir::Mod are not hashed
This is not a problem at the moment but one could imagine it to become one because the data is available in the HIR map and in theory, decisions could be made based on it.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Fixes #40876. Red-green tracking does not make this a problem anymore. We should verify this via a perf-run though. 

r? @nikomatsakis

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
er, @bors try

**Comment by nikomatsakis** [comment]
r=me modulo perf

**Comment by Mark-Simulacrum** [comment]
Perf started

**Comment by michaelwoerister** [comment]
Link: http://perf.rust-lang.org/compare.html?start=e75e78256f07aadd120fb867880c0c7913748cbe&end=71ab10dfd3fd0fdf0361480b66adee7a15d2dda3&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
Interesting. That fix in `MonoItemExt::predefine_fn()` was just meant to make the `krate-inherent` test case pass again but it really seems to have helped `tokio-webpush-simple` (-65.2% for `println-opt`). Not bad.

I'll apply another small optimization to the hashing of the DefPathHashes and then r=niko.

**Pull request merged**
