### PR TITLE
Implement `last` for `EscapeUnicode`

### PR DESCRIPTION
**Pull request by ranma42**
The implementation is quite trivial as the last character is always `'{'`.
As a side-effect it also improves the implementation of `last` for `EscapeUnicode`.

Part of #24214, split from #31049.

Maybe this (and the other changes that I will split from #31049) should wait for a test like `ed_iterator_specializations` to be added. Would it be sufficient to do the same for each possible escape length?

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could you add a few tests for this as well?

**Comment by nagisa** [comment]
> Thanks! Could you add a few tests for this as well?

@ranma42 ping, in case you missed the original request by Alex (this happens to me way too often).

**Comment by ranma42** [comment]
Thanks for the heads-up!
I added a test for characters of any legitimate length and for the NUL character.
The test checks the behaviour of `nth`, `last` and `count` in a way that is similar to `ed_iterator_specializations`, but it also exercises them on partially-used iterators.

**Comment by ranma42** [comment]
@alexcrichton ping-back ;)
I tried to make the test pretty extensive as in my queue I also have patches for the specialisation of `nth` and `count`.

**Comment by alexcrichton** [comment]
@bors: r+ 8169fa2fe84b6e3944f7362d3e73ba763a2da1d9

Oops, sorry about that!

**Pull request merged**
