### PR TITLE
Remove type-traversal trait aliases

### PR DESCRIPTION
**Pull request by eggyal**
#107924 moved the type traversal (folding and visiting) traits into the type library, but created trait aliases in `rustc_middle` to minimise both the API churn for trait consumers and the arising boilerplate.  As mentioned in that PR, an alternative approach of defining subtraits with blanket implementations of the respective supertraits was also considered at that time but was ruled out as not adding much value.

Unfortunately, it has since emerged that rust-analyzer has difficulty with these trait aliases at present, resulting in a degraded contributor experience (see the recent [r-a has become useless](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/r-a.20has.20become.20useless) topic on the #t-compiler/help Zulip stream).

This PR removes the trait aliases, and accordingly the underlying type library traits are now used directly; they are parameterised by `TyCtxt<'tcx>` rather than just the `'tcx` lifetime, and imports have been updated to reflect the fact that the trait aliases' explicitly named traits are no longer automatically brought into scope.  These changes also roll-back the (no-longer required) workarounds to #107747 that were made in b409329c624b9e3bbd7d8e07697e2e9f861a45b6.

Since this PR is just a find+replace together with the changes necessary for compilation & tidy to pass, it's currently just one mega-commit.  Let me know if you'd like it broken up.

r? @oli-obk

### CODE REVIEW

**Comment by eggyal** [comment]
Oops, forgot about that annoying test.

**Comment by oli-obk** [comment]
> Oops, forgot about that annoying test.

oof. We could add an stderr normalization to the test that removes the line information from the output

**Comment by eggyal** [comment]
Good thinking!  Done.

**Comment by eggyal** [comment]
Rebased.

@rustbot ready

**Pull request merged**
