### PR TITLE
Default images

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Add default rust logo (the image at the top of the sidebar) and default favicon. No more missing image or inexistent icon on the documentation tabs!

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
```
[01:41:06] settings.html:1: broken link - favicon.ico
[01:41:12] thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:39:9
```

Does the settings page not get the right favicon information?

**Comment by GuillaumeGomez** [comment]
Updated.

**Review by QuietMisdreavus — APPROVED** [review]

**Comment by jethrogb** [comment]
`git status` always shows me these files as modifed now:
```
	modified:   librustdoc/html/static/favicon.ico
	modified:   librustdoc/html/static/rust-logo.png
```

**Comment by jethrogb** [comment]
This is #57858

**Comment by pietroalbini** [comment]
As a temporary fix you can add the content of #57858 to `.git/info/attributes`.

**Pull request merged**
