### PR TITLE
rustdoc: Remove methods from #[doc(masked)] crates from the search index

### LINKED ISSUE #44740: rustdoc: Masked functions still appear in the search result.
Repro:

1. Go to nightly docs
2. Search for "aborting" (or just go to https://doc.rust-lang.org/nightly/std/?search=aborting)
3. Note that the functions `aborting_div` and `aborting_rem` appeared.
4. Clicking into the result will not jump to any functions.

Expected: `aborting_div` and `aborting_rem` should not appear in the search result.

The `aborting_div` and [`aborting_rem`](https://doc.rust-lang.org/1.20.0/std/primitive.u32.html#method.aborting_rem) methods are part of the `Int` trait in `compiler_builtins` which is not supposed to be exposed. The documentation about this trait is successfully hidden thanks to #44026, but the search entry still exists.

cc @QuietMisdreavus

### PR DESCRIPTION
**Pull request by ollie27**
For example: https://doc.rust-lang.org/nightly/std/?search=from_parts

Fixes #44740

r? @QuietMisdreavus

### CODE REVIEW

**Comment by kennytm** [comment]
Could you verify if this fixes #44740?

**Comment by ollie27** [comment]
Indeed it does.

**Comment by QuietMisdreavus** [comment]
@bors r+ rollup

Thanks!

**Comment by kennytm** [comment]
@bors r-

Not your fault, but unfortunately a test case is invalid, causing failure after the bug is fixed. Please apply the following diff:

```diff
diff --git a/src/test/rustdoc-js/from_u.js b/src/test/rustdoc-js/from_u.js
index 0296788f7a..34b98a758d 100644
--- a/src/test/rustdoc-js/from_u.js
+++ b/src/test/rustdoc-js/from_u.js
@@ -15,7 +15,5 @@ const EXPECTED = {
         { 'path': 'std::char', 'name': 'from_u32' },
         { 'path': 'std::str', 'name': 'from_utf8' },
         { 'path': 'std::string::String', 'name': 'from_utf8' },
-        { 'path': 'std::i32', 'name': 'from_unsigned' },
-        { 'path': 'std::i128', 'name': 'from_unsigned' },
     ],
 };
```

**Comment by ollie27** [comment]
Is it possible for travis to run those tests automatically? They seem like they will be pretty fragile.

**Comment by kennytm** [comment]
@ollie27 Those tests should be run automatically, but it seems the CI docker image is missing nodejs. 

```
[01:37:12] No nodejs found, skipping "src/test/rustdoc-js" tests
[01:37:12] Build completed successfully in 0:56:39
[01:37:12] travis_fold:end:make-check
```

cc @GuillaumeGomez

**Pull request merged**
