### PR TITLE
Statics used in reachable function's inline asm are reachable

### LINKED ISSUE #104925: Failed linking to a library that uses inline assembly with `asm_sym` feature
### What does not work

I tried this code:

```rust
// lib.rs
static EIGHTEEN: usize = 18;

#[inline(always)]
pub fn add_to_18(x: usize) -> usize {
    let mut y = x;

    unsafe {
        core::arch::asm!(
            "add {y}, [rip + {eighteen}]",
            y = inout(reg) y,
            eighteen = sym EIGHTEEN,
        );
    }

    y
}
```

```rust
// main.rs
fn main() {
    println!("5 + 18 = {}", my_lib::add_to_18(5));
}
```

I expected to see this happen: output `5 + 18 = 23`

Instead, this happened:

```
   Compiling my_lib v0.1.0 (/home/user/my_lib)
error: linking with `clang` failed: exit status: 1
  <...omitted...>
  = note: mold: error: undefined symbol: my_lib::EIGHTEEN::he8c23468c01db196
          >>> referenced by 1551ilekjbvb99xo

```

### What works

1. `#[no_mangle]`:

```rust
// lib.rs
#[no_mangle]
static EIGHTEEN: usize = 18;

#[inline(always)]
pub fn add_to_18(x: usize) -> usize {
    let mut y = x;

    unsafe {
        core::arch::asm!(
            "add {y}, [rip + {eighteen}]",
            y = inout(reg) y,
            eighteen = sym EIGHTEEN,
        );
    }

    y
}
```

2. `#[inline(never)]`:

```rust
// lib.rs
static EIGHTEEN: usize = 18;

#[inline(never)]
pub fn add_to_18(x: usize) -> usize {
    let mut y = x;

    unsafe {
        core::arch::asm!(
            "add {y}, [rip + {eighteen}]",
            y = inout(reg) y,
            eighteen = sym EIGHTEEN,
        );
    }

    y
}
```

3. `pub static`:

```rust
// lib.rs
pub static EIGHTEEN: usize = 18;

#[inline(always)]
pub fn add_to_18(x: usize) -> usize {
    let mut y = x;

    unsafe {
        core::arch::asm!(
            "add {y}, [rip + {eighteen}]",
            y = inout(reg) y,
            eighteen = sym EIGHTEEN,
        );
    }

    y
}
```

### Meta

`rustc --version --verbose`:

```
rustc 1.67.0-nightly (a28f3c88e 2022-11-20)
binary: rustc
commit-hash: a28f3c88e50a77bc2a91889241248c4543854e61
commit-date: 2022-11-20
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

`mold --version`:

```
mold 1.6.0 (323ad30e25c2c81efdb07ab76601a119335a40c8; compatible with GNU ld)
```

Also tried with `ld` linker, got the same error.

### PR DESCRIPTION
**Pull request by tmiasko**
Fixes #104925.

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]

**Comment by luqmana** [comment]
asm_sym has been stabilized as of 1.66 which is current beta. Given this is a rather small patch worth backporting?

**Comment by wesleywiser** [comment]
Yeah, thanks @luqmana! I didn't realize that had been stabilized in beta. 

Nominating for beta-backport to ride the release train with https://github.com/rust-lang/rust/pull/103168.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-12-01/near/313302639)

@rustbot label +beta-accepted

**Pull request merged**
