### PR TITLE
Updates Solaris target information, adds Solaris maintainer

### PR DESCRIPTION
**Pull request by psumbera**

### CODE REVIEW

**Comment by psumbera** [comment]
Following yesterdays discussion. @cuviper @tgross35 @workingjubilee/

**Comment by GuillaumeGomez** [comment]
r? Noratrieb

**Comment by cuviper** [comment]
> `NOTE: if you are adding or renaming a markdown file in a mdBook, don't forget to register the page in SUMMARY.md`

**Review by workingjubilee — APPROVED** [review]
Hell yeah.

**Review by jieyouxu — APPROVED** [review]
Thanks, this looks great and thank you for signing up to be its target maintainer. I'll tag this with compat relnotes as we're technically changing the baseline -- but previously there was no explicit baseline at all!

**Comment by jieyouxu** [comment]
> @workingjubilee @jieyouxu I don't think there's anything blocking this PR? Can this be merged?

(We didn't know if a Tier 2 solaris baseline change needed an FCP, I'm inclined to say "no" in this case because this was previously underspecified and relnotes is likely sufficient)

**Comment by tgross35** [comment]
I posted an MCP just to make sure there aren't any objections https://github.com/rust-lang/compiler-team/issues/812. I think we're more interested in the internal FYI and the concern period rather than technical details, so anyone feel free to second :)

**Comment by Noratrieb** [comment]
r? tgross35 assigning you to approve once the MCP is through

**Review by tgross35 — APPROVED** [review]

**Comment by tgross35** [comment]
MCP completes tomorrow, I don't really see us getting any last minute objections.

@bors r+ rollup

**Comment by jieyouxu** [comment]
@tgross35 let's just wait for MCP to finish, there's no need to rush this change through.

**Comment by tgross35** [comment]
Now it's complete :)

@bors r+ rollup

**Pull request merged**
