### PR TITLE
Bump bootstrap compiler to 2018-04-24

### PR DESCRIPTION
**Pull request by michaelwoerister**
r? @alexcrichton

### CODE REVIEW

**Comment by abonander** [comment]
This will break bootstrap builds on MSVC 2017 (#49869)

**Comment by gnzlbg** [comment]
@alexcrichton does this fix the LLVM errors of ? https://github.com/rust-lang-nursery/stdsimd/pull/432

**Comment by alexcrichton** [comment]
@gnzlbg  probably not, this is just for rustc itself (stdsimd using nightlies already uses a compiler with this fix)

**Pull request merged**
