### PR TITLE
add AsRef<[u8]> for both str and String

### PR DESCRIPTION
**Pull request by seanmonstar**
r? @aturon

### CODE REVIEW

**Comment by alexcrichton** [comment]
Does this compile when rebased on https://github.com/rust-lang/rust/pull/25120? It makes the meaning of `vec_of_strings.concat()` ambiguous as it could return `Vec<Vec<u8>>` or a `String`

**Comment by seanmonstar** [comment]
Ah carps, you're right, that does make it ambiguous. Possibilities:

1. **Scrap this idea**. However, it feels right to be able to make APIs generate over `AsRef<[u8]>`, and including strings would be an ergo win.
2. **Require `vec_of_strings.concat()` be explicit.**
3. **Change the implementations of SliceConcatExt to 4 implementations, 1 for each `[T]`, `Vec<T>`, `str`, and `String`, instead of relying on `AsRef<U>`.**

**Comment by alexcrichton** [comment]
After some discussion with @aturon he has convinced me that we definitely want the ability to add these `AsRef` implementations, and we can touch up `SliceConcatExt` for now by using `Borrow` as the bound on those generic `impl` blocks instead of `AsRef` (as `str` will never implement `Borrow<[u8]>` due to hashing differences).

That will be a breaking change but is likely to have very little fallout, so we'll probably include it for beta. Could you update this PR with that change?

**Comment by seanmonstar** [comment]
@alexcrichton updated, passes `make check-stage1`.

**Comment by alexcrichton** [comment]
@bors: r+ 8e491ef0193f48fc000ff62c75544f8dcaa6548d p=50

Thanks @seanmonstar!

**Comment by bluss** [comment]
Dabo on irc says something broke with .connect()

```
< Dabo> This used to work, but doesn't anymore with the latest nightly: 
              some_set.iter().collect::<Vec<_>>().connect(", ")
< Dabo> `type `collections::vec::Vec<&collections::string::String>` does not implement any 
              method in scope named `connect``
< Dabo> I have rustc 1.1.0-nightly (dc630d01e 2015-05-09) (built 2015-05-10)
```

**Comment by daboross** [comment]
Full code example that breaks: http://is.gd/vdlpTma

This isn't a major use-case I wouldn't think, but just noting an example of that here.

**Comment by seanmonstar** [comment]
I forgot to include [breaking-change] in the last commit to :(

**Comment by alexcrichton** [comment]
Adding beta-accepted as this has been merged into beta

**Pull request merged**
