### PR TITLE
[DO NOT MERGE]: Try out 128bit SipHash for incr. comp. hashes.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This is just for performance testing on perf.rust-lang.org. It's not meant to be merged in this state.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Btw, this contains a copy of @arthurprs excellent metrohash implementation (had to copy it because `finish128` is not public). In my local tests this was the best performing hash function I found on crates.io.

**Comment by arthurprs** [comment]
Thanks for the ping, I'm always interesting in these changes. The faster the merrier :smile: 

Can perf.rust-lang.org test unmerged PRs? That's really nice.

**Comment by Mark-Simulacrum** [comment]
http://perf.rust-lang.org/compare.html?commit_a=fd8099f0ecc2fd3980469ec45cf834ae9a941ca3&commit_b=0ea9f24fb9ec914e29f759b5e1ede9fcd496a1d5&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
Thanks a lot, @Mark-Simulacrum!

This is the fairer comparison:
http://perf.rust-lang.org/compare.html?commit_a=d7e73e4b1abe120520d1894b89c0e25469f41e69&commit_b=0ea9f24fb9ec914e29f759b5e1ede9fcd496a1d5&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
Closing, see follow-up here: https://github.com/rust-lang/rust/issues/41215#issuecomment-334408968

**Pull request closed without merging**
