### PR TITLE
book: Removed platform compatibility table, link to the forge

### PR DESCRIPTION
**Pull request by brson**
The content is duplicated, and it doesn't need to be in this location.
It's mostly trivia that doesn't apply to most of the audience.

The forge is up to date.

r? @steveklabnik cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
I kinda like having it on doc.rust-lang.org and having it staged, but if you'd prefer it elsewhere I don't particularly mind

**Comment by steveklabnik** [comment]
Same as alex. I slightly worry that links are now going to be broken, but there's no real getting around that...

**Comment by brson** [comment]
I'll try putting it in a different location in tree then, and preserving the anchor here.

**Comment by steveklabnik** [comment]
Honestly, I don't think it's a big deal; we're gonna have to figure out a broader strategy for links and the book when it comes to book v2, so..... let's :shipit: 

@bors: r+ rollup

**Pull request merged**
