### PR TITLE
Turn trailing tokens in `assert!()` into hard errors

### LINKED ISSUE #69531: Revisit trailing tokens in assert!
About 10 months ago it was necessary to permit typos to become temporary non-errors due to #60024 slipping into a stable release. Since #60039, the compiler has issued a "this will become an error" warning for a subset of accidentally-allowed uses ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=51d2b03c4f8a7147d1f7d11907dae607)):

```
fn main() {
    assert!(true "whatever");      // Intended: error. Currently: warning.
    assert!(true;);                // Intended: error. Currently: warning.
    assert!(true some extra junk); // Intended: error. Currently: error.
}
```

Version: 1.43.0 2020-02-26 nightly

Since the fix has been in for far longer than the bug, it would be great to close the loop on this by removing the special cases or converting them to errors.

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
I didn't have time to build the compiler and thus edited the tests manually, I hope it will still pass.

Closes #69531
r? @Centril do you want to queue the Crater experiment?

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
@Centril Could you `@craterbot check`?

**Comment by Centril** [comment]
@craterbot check

**Comment by LeSeulArtichaut** [comment]
Hi @Centril, I see you added S-waiting-on-author, what do you want me to do?

**Comment by Centril** [comment]
If you could triage the crate runs (categorize the regressions, roots, the number of them, if any are spurious...) that would be great. :)

**Comment by LeSeulArtichaut** [comment]
Crater reported 7 regressions:
- 1 is spurious
- 2 are due to trailing semicolons
- 4 are due to missing commas before string literals

**Comment by Centril** [comment]
Given that the regressions are few in amount (all <= 4), none of the regressed crate have known reverse dependencies on crates.io, and that this has been a hard coded warning for some time, I think we can land this outright (although if you want to file PRs against the repos that would be nice, but optional, I think).

r? @petrochenkov for a second opinion

r=me on the code changes themselves though.

**Pull request merged**
