### PR TITLE
Automatically jump to the first result when entering directly in the search form

### PR DESCRIPTION
**Pull request by 0xPoe**
See: https://github.com/rust-lang/rust/issues/84214#issuecomment-821019360

### CODE REVIEW

**Comment by hi-rustin** [comment]
A simple demo:


https://user-images.githubusercontent.com/29879298/115134185-913d5900-a040-11eb-87a6-261a2835b2a2.mov

**Comment by GuillaumeGomez** [comment]
I don't find this behaviour very intuitive...

What do you think @rust-lang/rustdoc ?

**Comment by jyn514** [comment]
I like it; I think it makes it easier to navigate the docs. Normally enter would start a new search, but because rustdoc searches while you're typing, I don't think that's super useful.

**Comment by hi-rustin** [comment]
I think this is acceptable, we already use use the enter to jump pages (instead of searching), then I think it is acceptable to jump to the first result by default.

**Comment by GuillaumeGomez** [comment]
> I think this is acceptable, we already use use the enter to jump pages (instead of searching)

Where do we do that?

**Comment by hi-rustin** [comment]
> > I think this is acceptable, we already use use the enter to jump pages (instead of searching)
> 
> Where do we do that?

When we move up and down with the keyboard, we can jump with a return.

**Comment by GuillaumeGomez** [comment]
Yes, but it's after the user hovers an element (either with the mouse or with up/down arrows). The action is then obvious.

Oh also, since you know well about UX, what do you think @jsha ?

**Comment by Manishearth** [comment]
I'm fine with this if off by default; it does seem like an improvement over the original feature.

Note that it'll probably directly match `usize` and modules and stuff (`std::vec` gets matched before `std::vec::Vec`)

Very reluctant to make the search page do stuff like this by default; because a state change like that is usually kinda jarring

**Comment by GuillaumeGomez** [comment]
If it's done with a setting like @Manishearth suggested (disabled by default), I'm fine with it.

**Comment by jsha** [comment]
Thanks for the tag, @GuillaumeGomez. I posted some thoughts on the issue thread at https://github.com/rust-lang/rust/issues/84214#issuecomment-822032156

**Comment by hi-rustin** [comment]
@GuillaumeGomez @jyn514 @jsha What do you think about changing the feature to default highlighting the first result?

**Comment by GuillaumeGomez** [comment]
There is https://github.com/rust-lang/rust/pull/84462 coming up, so in this context, I don't know how this PR could work...

**Comment by hi-rustin** [comment]
> There is #84462 coming up, so in this context, I don't know how this PR could work...

Got it. So let's wait for that PR to merge and then we'll see how to solve this problem.

**Pull request closed without merging**
