### PR TITLE
std::env play with new syntax

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by joshtriplett** [comment]
So, this seems rather reasonable to me in isolation, but I *think* this would break anyone using these functions with an explicit `<>` specifying the types. If it does, I don't think we can do this. If it doesn't, then by all means let's do it.

**Comment by tshepang** [comment]
Does that mean the new syntax doesn't have the exact same meaning as the old syntax? What does "reak anyone using these functions with an explicit" mean?

**Comment by jonas-schievink** [comment]
Yeah, you cannot explicitly specify type parameters for a function using `impl Trait` in argument position.

**Comment by joshtriplett** [comment]
On October 1, 2019 10:24:48 PM GMT+02:00, Jonas Schievink <notifications@github.com> wrote:
>Yeah, you cannot explicitly specify type parameters for a function
>using `impl Trait` in argument position.

Then I think we can't accept this change, unfortunately.

New code can and should use this syntax, but we can't migrate existing public functions to it.

**Pull request closed without merging**
