### PR TITLE
Clarify mono item usage

### PR DESCRIPTION
**Pull request by nnethercote**
Some commits that make the terminology around mono items clearer, and simplify related data structures.

r? @wesleywiser

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at a time.

**Comment by nnethercote** [comment]
Perf is neutral, and I have rebased.

**Comment by nnethercote** [comment]
I rebased again.

**Review by wesleywiser — APPROVED** [review]
These are great cleanups! Not using `Range` certainly simplifies the code.

**Pull request merged**
