### PR TITLE
Remove transmute in From<&str> impls for Arc/Rc

### PR DESCRIPTION
**Pull request by nvzqz**
Performs conversion via raw pointer casts.

### CODE REVIEW

**Comment by bluss** [comment]
I'd prefer transmute here over going through `Arc::from_raw`, as long as the pointer arithmetic in into/from doesn't optimize out and cancel out as it should. Last time I checked, it didn't.

**Comment by nvzqz** [comment]
I forgot about that aspect of into/from here. That's a good point. 🤔

**Comment by bluss** [comment]
When [double checking in playground](https://play.rust-lang.org/?gist=d18c9d0379f402efee46de1337eb9f2e&version=nightly), it optimizes out, so then it's fine for me.

A reviewer can r=me but I wanted to figure out if travis will be green if we rerun it (after time out in scache?)

**Comment by nvzqz** [comment]
Thanks for checking the optimization out 😄

**Comment by kennytm** [comment]
@bors r=bluss,kennytm

Can't get pass the spurious error without rebasing. The change looks reasonable, just let bors to do the merge step.

**Pull request merged**
