### PR TITLE
require simd_insert, simd_extract indices to be constants

### PR DESCRIPTION
**Pull request by RalfJung**
As discussed in https://github.com/rust-lang/rust/issues/77477 (see in particular [here](https://github.com/rust-lang/rust/issues/77477#issuecomment-703149102)). This PR doesn't touch codegen yet -- the first step is to ensure that the indices are always constants; the second step is to then make use of this fact in backends.

Blocked on https://github.com/rust-lang/stdarch/pull/1530 propagating to the rustc repo.

### CODE REVIEW

**Comment by oli-obk** [comment]
I should investigate whether I can do the same trick as https://github.com/rust-lang/rust/pull/115933 for insert and extract

**Comment by RalfJung** [comment]
Which trick?
Const-generic versions of simd_extract / simd_insert are definitely possible. But with the current status of const generics, stdarch couldn't use them, just like it can't use simd_shuffle_generic -- see https://github.com/rust-lang/rust/issues/85229.

**Comment by oli-obk** [comment]
Ah, they wanna do math on their own const generics. Yea, that won't work

**Comment by RalfJung** [comment]
I think all they want to do is `as` casts.^^ (Though I didn't do an exhaustive check to see if that covers everything. And for simd_shuffle, constructing a slice.)

**Review by oli-obk — APPROVED** [review]
r=me when stdsimd has been synced

**Comment by RalfJung** [comment]
That should be soon hopefully: https://github.com/rust-lang/rust/pull/121185

**Comment by RalfJung** [comment]
We had a codegen that that consisted only of calls to simd_insert / simd_extract with variable arguments to the index. @workingjubilee @Amanieu @calebzulawski what are we supposed to do with that, given that we said we want these functions to be like simd_shuffle and only support constant indices?

**Comment by RalfJung** [comment]
Looks like the test was added in https://github.com/rust-lang/rust/pull/78863, Cc @KodrAus @gnzlbg

**Comment by calebzulawski** [comment]
I think changing those arguments to const generics is appropriate.  Typeck or similar should probably have rejected the non-const argument (which is what shuffles do, I think?) It seems packed_simd is really the only consumer of those intrinsics, if std::arch doesn't use them.

**Comment by RalfJung** [comment]
stdarch uses them as well, but with https://github.com/rust-lang/stdarch/pull/1530 it makes all arguments constants. It also had one non-constant use in a test only, somewhat similar to this codegen test.

But if we don't want to support non-constant simd_insert/extract, it makes little sense to have a codegen test for it.

**Comment by Amanieu** [comment]
I also think it's fine to make these require constants.

**Comment by RalfJung** [comment]
Is there something that I should do with that codegen test, or should I delete it?

**Comment by Amanieu** [comment]
It's fine to just remove it. We're changing the definition of `simd_insert`/`simd_extract` to only accept constants, which is fine since this is an unstable internal API. That test is no longer relevant.

**Comment by RalfJung** [comment]
Okay, thanks. :)
@bors r=oli-obk,Amanieu

**Pull request merged**
