### PR TITLE
Add decorator syntax extensions on trait and impl items

### PR DESCRIPTION
**Pull request by nrc**

### CODE REVIEW

**Comment by nrc** [comment]
@sfackler review ping

**Comment by sfackler** [comment]
I would not be opposed to just removing `Modifier` and `Decorator` to cut down on the duplicated code for the old/new cases, but r+ other than that.

**Comment by nrc** [comment]
@sfackler thanks for the review. My plan is to remove them after a month or so deprecation period - don't want to blind-side users too much.

**Comment by gsingh93** [comment]
Would it be a good idea to just rename `MultiItemModifer` to `ItemModifier` instead of removing `ItemModifier`? I'm not really a fan of the name `MultiItemModifier`.

**Comment by nrc** [comment]
Probably. That would require another deprecation stage, but that's OK.

**Pull request merged**
