### PR TITLE
Clean up (sub)diagnostic derives

### PR DESCRIPTION
**Pull request by Xiretza**
The biggest chunk of this is unifying the parsing of subdiagnostic attributes (`#[error]`, `#[suggestion(...)]`, `#[label(...)]`, etc) between `Subdiagnostic` and `Diagnostic` type attributes as well as `Diagnostic` field attributes.

It also improves a number of proc macro diagnostics.

Waiting for #101558.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
LGTM, is there a reason that this is still marked as a draft or can I r=me it?

**Comment by Xiretza** [comment]
> Waiting for #101558.

@JhonnyBillM has been waiting and rebasing for longer, I'll let them go first.

**Comment by Xiretza** [comment]
Sorry for force-pushing after r+, but I did actually still have a bugfix locally that I was waiting to push together with a rebase.

**Pull request merged**
