### PR TITLE
Allow "infinity" and ignore case when parsing floats.

### LINKED ISSUE #48881: Making f64::from_str case insensitive
Consider making `f64::from_str(src: &str) -> Result<f64, ParseFloatError>` case insensitive due to the following reasons:
1.  people may see infinity as a constant and write `"INF"` or `"Inf"`
2.  `f64::INFINITY` is all upper case
3.  `f64::NAN` is all upper case
4.  `is_nan` is all lower case
5.  `e` in `"12e3"` is case insensitive, so it seems to be inconsequent
6. `"NaN"` is camel case, but `"inf"` is lower case, which seems to be a little bit inconsistent
7.  `to_ascii_lowercase` is slow and will not be of help as `"NaN"` is mixed case
8.  `to_ascii_uppercase` is slow and will not be of help as `"NaN"` is mixed case
9.  a hypotetical function `to_standard_form(src: &str, dest: &mut str) -> Result<(), ParseFloatError>` is not possible as `str` cannot be mutable

So far, only `"inf"` and `"NaN"` are allowed.

Cons:
* slows parsers down by a minimal amount
* increases code size by a minimal amount

### PR DESCRIPTION
**Pull request by clarfonthey**
This fixes #48881.

### CODE REVIEW

**Comment by clarcharr** [comment]
This also technically depends on #48735.

**Comment by pietroalbini** [comment]
Thanks for this PR! Unfortunately, highfive failed to assign a reviewer to this PR. Picking someone randomly from the libs team. @dtolnay?

**Review by dtolnay — COMMENTED** [review]
The code looks good but what do you see as the use cases of this? What are some examples where an application would not have been able to use f64::from_str before but would want to after this change?

**Comment by petrochenkov** [comment]
ping @rkruppe

**Comment by clarcharr** [comment]
@dtolnay there are a few examples in the original issue; I think that once inf, INF, NaN, NAN, and nan are allowed, it just makes more sense to simplify the code and allow any case. The usage of "infinity" was just an extra I thought of though, and can be removed if it seems unnecessary.

**Review by dtolnay — COMMENTED** [review]
I just feel that "can unambiguously be interpreted as an f64" is not the set of inputs that f64::from_str would ideally accept. We define what the function accepts, and if someone wants to call the function they are expected to pass input the way we defined it. For that purpose I see the current set of `"inf"` and `"NaN"` as being sufficient. If someone is writing a YAML library for example and YAML's infinity is spelled `".inf"`, there should be no expectation that f64::from_str is the tool they need to use.

**Comment by clarcharr** [comment]
That is understandable! If you think that this wouldn't be worth having I can close this PR.

**Comment by dtolnay** [comment]
I appreciate the PR but let's keep this the way it is. Thanks!

**Comment by JohnBSmith** [comment]
It seems understandable to me too, I have found more than one reason that speaks against it. First of all, this would have been a subtle breaking change, as the return value's specification including its error cases belongs to the interface. Then, making a small and clear interface more complex is controversial and should not be taken lightly. And if the exact syntax definition differs, a validating parser needs to handle the cases that don't match  `[sign] ('.' | digit)` by itself anyway.

**Pull request closed without merging**
