### PR TITLE
Add Rev delegate methods for the impl of Iterator.

### PR DESCRIPTION
**Pull request by czipperz**

### CODE REVIEW

**Comment by czipperz** [comment]
This does three things:
1. Implement the following methods trivially: `count`, `last`, and `position`.
2. Mark all delegates as inline
3. Replace `Self::Item` with `<I as Iterator>::Item`.

**Comment by czipperz** [comment]
@clarcharr That's a great point.  I'll make a PR that makes tests for these.

**Comment by czipperz** [comment]
I'm keeping the PR open for right now so I remember to work on this.

**Comment by Dylan-DPC** [comment]
ping from triage @czipperz any updates on this?

**Comment by czipperz** [comment]
@Dylan-DPC I'm working on other things right now.  Do you think I should add tests ensuring this functionality or it is fine as is?

**Pull request closed without merging**
