### PR TITLE
Add i686-unknown-openbsd target.

### PR DESCRIPTION
**Pull request by semarie**
It is a preliminary work. I still have some tests failing, but I have a working rustc binary which is able to rebuild itself.

an update of libc should be required too, but I dunno how to do it with vendor/ layout.

r? @alexcrichton

### CODE REVIEW

**Comment by japaric** [comment]
LGTM.

> an update of libc should be required too, but I dunno how to do it with vendor/ layout.

At the very least, you'll need to update the `src/liblibc` submodule in this PR. I don't know the specifics about `cargo vendor`ing though.

**Comment by semarie** [comment]
@alexcrichton Could you unapprove this PR for now please ?

I have pending PR in libc (https://github.com/rust-lang/libc/pull/462) that would require a new liblibc for i686-unknown-openbsd correctness.

I will update this PR once libc PR be accepted.

**Comment by japaric** [comment]
@bors r-

Let's wait for that libc PR

**Comment by semarie** [comment]
I updated liblibc submodule.
I also added OpenBSD in `librustc_trans/cabi_x86.rs` as target requiring particular management for returning a struct (small structs are returned as integers).

**Comment by semarie** [comment]
this kind of "restructuration" was outside the scope of the PR, but I tend to agree with this approch, and it could be generalized to a list of options registered by target for required behaviour.

**Pull request merged**
