### PR TITLE
Statically link run-pass/command-before-exec so it passes not just whenever we happen to bootstrap perfectly.

### PR DESCRIPTION
**Pull request by eddyb**

### CODE REVIEW

**Comment by eddyb** [comment]
cc @rust-lang/tools This would probably not be a problem with `rustbuild`.

**Comment by alexcrichton** [comment]
A fix I also [suggested to](https://github.com/rust-lang/rust/issues/31398#issuecomment-194980053) @pnkfelix would be to just tag this with `// no-prefer-dynamic` to link it statically.

**Comment by Manishearth** [comment]
```

failures:

---- [run-pass] run-pass/command-before-exec.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: i686-apple-darwin/test/run-pass/command-before-exec.stage2-i686-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: output.status.success()', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/run-pass/command-before-exec.rs:64
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------

thread '[run-pass] run-pass/command-before-exec.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/compiletest/runtest.rs:1651
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-pass] run-pass/command-before-exec.rs

```

**Comment by eddyb** [comment]
@Manishearth What, the test is broken even at stage2?!

**Comment by eddyb** [comment]
*sigh* reproduced locally. Time to use `// no-prefer-dynamic`.

**Comment by eddyb** [comment]
Have to use the @bors force, apparently.

**Pull request merged**
