### PR TITLE
Fix invalid trait generation

### LINKED ISSUE #33919: [rustdoc] invalid trait doc generation
When rustdoc generates doc from trait implementation, it could replace generic ones with the one we have. Example with http://doc.rust-lang.org/nightly/std/cell/struct.RefCell.html :

```text
fn eq(&self, other: &RefCell<T>) -> bool;

This method tests for self and other values to be equal, and is used by ==. Read more

fn ne(&self, other: &Rhs) -> bool;

This method tests for !=.
```

`eq()`'s other argument is &RefCell<T>, but that's not the case for `ne()`. It should be fixed.

cc @nox

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #33919.

r? @steveklabnik 

And a screenshot to come along:

screenshot from 2016-05-29 01 37 40

### CODE REVIEW

**Comment by eefriedman** [comment]
```
fn eq(&self, other: RefCell<T>) -> bool
fn ne(&self, other: RefCell) -> bool
```

That doesn't look quite right.

**Comment by GuillaumeGomez** [comment]
Oh indeed. Going back to add missing information then.

**Comment by GuillaumeGomez** [comment]
New screenshot (lifetimes and type parameters now appear as well):

screenshot from 2016-05-29 23-43-46

**Comment by GuillaumeGomez** [comment]
A more complete screenshot to see lifetimes as well:

untitled

**Comment by steveklabnik** [comment]
I think conceptually, I like this change, but I am gonna review the code more a bit later. If anyone else is happy with the code, feel free to r+ it.

**Comment by steveklabnik** [comment]
This seems okay to me, but I am still getting to know rustdoc. @rust-lang/tools do any of you have thoughts on this patch?

**Comment by alexcrichton** [comment]
The issue this is fixing, https://github.com/rust-lang/rust/issues/33919, is mostly just a dupe of https://github.com/rust-lang/rust/issues/14072 which is a general problem that rustdoc doesn't substitute type parameters, so it just shows up this way. In general I think this may be a pretty ad-hoc solution which doesn't actually get us much farther.

It looks like this only handles `Self`, right? And it also only handles `&Self` and and `Self` as well? That is, I don't think cases like `Box<Self>` seem to be handled.

I think this would be best done as a preparation pass during rustdoc, either during the "clean" phase or as a dedicated pass in rustdoc itself. The rendered is already pretty complicated with lots of functions taking lots of arguments, so offloading as much as we can elsewhere seems beneficial.

**Comment by GuillaumeGomez** [comment]
@alexcrichton: That's what I tried at first but got quickly stuck with my lack of knowledge on the "low" code. I'll try to redo it in the "preparation pass".

**Comment by steveklabnik** [comment]
@GuillaumeGomez are you still working on this?

**Comment by steveklabnik** [comment]
Closing due to a lack of activity, let me know if you want to keep up with this!

**Comment by GuillaumeGomez** [comment]
Ah damn, didn't see the first comment. I'll, but don't know when.

**Pull request closed without merging**
