### PR TITLE
`super_relate_consts`: stop being generic

### PR DESCRIPTION
**Pull request by lcnr**
I previously attempted this in #78288 where it slightly improved perf and bootstrap times.

With #99730 changing `BoundVarReplacer` to use a type parameter instead of a trait object, this may now be even more effective. Relating `ConstKind::Value` was a large part of this function in the past, which may reduce the impact of this change tough.

r? @jackh726

### CODE REVIEW

**Comment by pnkfelix** [comment]
Hmm, comparing [the bootstrap times from 99730](https://perf.rust-lang.org/compare.html?start=3924dac7bb29bc8eb348059c901e8f912399c857&end=211637d0802a1c17d41b414e091e9a8691b26068&stat=instructions:u) to the [bootstrap times on 100016](https://perf.rust-lang.org/compare.html?start=25bb1c13bd472b75ceebee3b8dcf4dcbc431a8be&end=34427f20790cbf9f8387dd5a31e2de71d5466fd6&stat=instructions:u), it seems like 99730 regressed bootstrap times by ~2%, but this PR failed to recover that loss (it only improves bootstrap times by 0.11%).

I'll try to dig a little bit more into the specific data reported, just wanted to point out that this change made by PR #100016 may not be the way to address the root cause of the bootstrap time regression .

**Comment by jackh726** [comment]
For the bootstrap regression in #99730, I think we likely need to consider going back to dynamic dispatch, instead of static. It's a trade off between compiler compile times and overall compile times.

This I think is dependent on that decision.

**Comment by lcnr** [comment]
alright, looks like this is pretty much irrelevant now :grin:

**Pull request closed without merging**
