### PR TITLE
rustbuild: Clean more on `make clean`

### LINKED ISSUE #33986: rustbuild: `make clean` doesn't clean enough
Errors like http://buildbot.rust-lang.org/builders/auto-linux-64-cross-netbsd/builds/462 are happening on the bots, e.g.:

```
   Compiling bootstrap v0.0.0 (file:///buildslave/rust-buildbot/slave/auto-linux-64-cross-netbsd/build/src/bootstrap)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `bootstrap`.

To learn more, run the command again with --verbose.
```

This is https://github.com/rust-lang/rust/issues/33778 under the covers, but rustbuild's `make clean` command should blow away the build system directory ahead of time to be more resilient to bugs like this.

### PR DESCRIPTION
**Pull request by alexcrichton**
Be sure to not use the old build cache for the bootstrap build system nor the
old caches of the compiler/cargo extractions (in case something went wrong).

Closes #33986

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/33844

cc @retep998, failing command line:

```
note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-Wl,--large-address-aware" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\crt2.o" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "C:\\Users\\RUSTBU~1\\AppData\\Local\\Temp\\rustdoctest.BwMmbZ1jJDyY\\rust_out.0.o" "-o" "C:\\Users\\RUSTBU~1\\AppData\\Local\\Temp\\rustdoctest.BwMmbZ1jJDyY\\rust_out.exe" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps" "-L" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release" "-L" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\build\\alloc_jemalloc-251d3635b190c547\\out/lib" "-L" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\build\\std-b6c7401b64554a8e\\out/.libs" "-L" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\libstd-9155338590fead51.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcollections-42c2372e64b992cb.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\libpanic_unwind-3d50b641895f0f51.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\librustc_unicode-f78262cffb9aaffc.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\libunwind-e0c4676abffd20e8.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\librand-a5ad246e2bda752b.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\liblibc-7f852771f3f101ed.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\liballoc-c48ed75dbdecc32f.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liballoc_system-654c6d3f5f8e32c4.rlib" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2-std\\i686-pc-windows-gnu\\release\\deps\\libcore-59d138fb210ee147.rlib" "-l" "advapi32" "-l" "ws2_32" "-l" "userenv" "-l" "shell32" "-l" "gcc_eh" "-l" "gcc_eh" "-l" "compiler-rt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\bot\\slave\\auto-win-gnu-32-opt-rustbuild\\build\\obj\\build\\i686-pc-windows-gnu\\stage2\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsend.o"
```

That's unfortunately only 3600 characters long, not anywhere near the 32KB

**Comment by retep998** [comment]
I'm at a loss for what the problem is then, unless it is an argument to `CreateProcess` other than the command itself, or maybe something being called inside `Command::spawn`.

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/17360

**Pull request merged**
