### PR TITLE
update `build.extended` comments in `config.example.toml`

### LINKED ISSUE #115502: config.toml generated by ./configure does not include tools= definition anymore
I compile Rust by downloading it from https://forge.rust-lang.org/infra/other-installation-methods.html#source-code, unpacking, then calling

> ./configure  --enable-optimize-llvm --enable-extended --llvm-root=/usr/local --enable-llvm-link-shared --enable-sanitizers --enable-local-rust

This generates a config.toml file.  For Rust 1.72.0 the latter includes:
```
[build]
# Enable a build of the extended Rust tool set which is not only the compiler 
# but also tools such as Cargo. This will also produce "combined installers"
# which are used to install Rust and Cargo together. This is disabled by 
# default. The `tools` option (immediately below) specifies which tools should
# be built if `extended = true`. 
extended = true
```
The text above references  “`tools` option (immediately below)”, but the file does not contain tools= definition.  This is a regression towards Rust 1.65.0.  With Rust 1.65.0 config.toml contained also
```
[build]
# Installs chosen set of extended tools if `extended = true`. By default builds
# all extended tools except `rust-demangler`, unless the target is also being
# built with `profiler = true`. If chosen tool failed to build the installation
# fails. If `extended = false`, this option is ignored.
tools = ["cargo", "rls", "clippy", "rustfmt", "analysis", "src"] # + "rust-demangler" if `profiler` 
```

### PR DESCRIPTION
**Pull request by onur-ozkan**
Fixes #115502

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I would prefer to avoid populating a fixed list, because that means future changes to the list lead to breakage even if the user just wanted the default. Can we change the comment to mention that tools may not exist or point to config.example.toml instead?

**Comment by onur-ozkan** [comment]
> I would prefer to avoid populating a fixed list

How about reading this from config.example.toml instead having a fixed hard-coded list? So changes in example config will be reflected to here as well.

**Comment by Mark-Simulacrum** [comment]
I'm not sure I follow. My point is that I don't want to persist the _current_ (default/non-default) list of tools into config.toml at the time of ./configure. So I don't think reading config.toml helps?

**Comment by onur-ozkan** [comment]
> Can we change the comment to mention that tools may not exist or point to config.example.toml instead?

Didn't you mean this list

https://github.com/rust-lang/rust/blob/150e1637c586bae21669393e6d6d77cc797df3f6/src/bootstrap/configure.py#L286-L296

would be unsynchronized with the value in config.example.toml?

Did I missed your point?

**Comment by Mark-Simulacrum** [comment]
I think so. That list getting desynchronized is certainly *a* concern, but the larger concern I have is with the _result_ of the configure script, i.e., the config.toml file. I don't want to persist an explicit configuration that we may change over time if the user hasn't explicitly requested that configuration.

**Comment by onur-ozkan** [comment]
Oh, I see.

Hmm, now I am thinking if handling this(e.g., if extended is true and tools is not defined, use tools from example configuration as default value) in `bootstrap/config.rs` would be a good idea. So we don't end up persisting this list to `config.toml` for people, and we can catch the issues with this list on CI pipelines.

**Comment by Mark-Simulacrum** [comment]
My impression is that we do that. The issue this is trying to close is just about a misleading comment, right? It's not actually about changing any functionality.

**Comment by onur-ozkan** [comment]
> My impression is that we do that.

Yes, I just checked it. Sorry for any confusion/noises; I thought we were missing the functionality as well.

**Comment by onur-ozkan** [comment]
> r-
> r=Mark-Simulacrum

`(check config.example.toml to see its default value)` part was pushed after half a second of r+

**Pull request merged**
