### PR TITLE
Fix evaluating trivial drop glue in constants

### PR DESCRIPTION
**Pull request by oli-obk**
```rust
struct A;
impl Drop for A {
    fn drop(&mut self) {}
}

const FOO: Option<A> = None;

const BAR: () = (FOO, ()).1;
```

was erroring with

```
error: any use of this value will cause an error
 --> src/lib.rs:9:1
  |
9 | const BAR: () = (FOO, ()).1;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^-^
  |                           |
  |                           calling non-const function `std::ptr::real_drop_in_place::<(std::option::Option<A>, ())> - shim(Some((std::option::Option<A>, ())))`
  |
  = note: #[deny(const_err)] on by default

error: aborting due to previous error
```

before this PR. According to godbolt this last compiled successfully in 1.27

### CODE REVIEW

**Comment by pnkfelix** [comment]
Can you add a `ui` test for the error case showing that `const FOO: Option<A> = Some(A);` will be rejected?

I skimmed over the existing tests and I didn't immediately see anything covering that (where we have the glue for `Option` around the type implementing `Drop`).
 * I don't count 
https://github.com/rust-lang/rust/blob/6bba352cad2117f56353d400f71e96eafa2e6bd7/src/test/ui/consts/const-eval/const_let.rs#L17 because that seems like a slightly different path...

**Comment by pnkfelix** [comment]
r=me with aforementioned test added.

**Comment by oli-obk** [comment]
We do have https://github.com/rust-lang/rust/blob/79d8a0fcefa5134db2a94739b1d18daa01fc6e9f/src/test/ui/static/static-drop-scope.rs#L17-L21 and https://github.com/rust-lang/rust/blob/79d8a0fcefa5134db2a94739b1d18daa01fc6e9f/src/test/ui/span/E0493.rs#L17 but neither of these actually use an `Option` so I added some tests to `static-drop-scope.rs`

@bors r=pnkfelix

**Comment by Centril** [comment]
Failed in rollup, https://github.com/rust-lang/rust/pull/57874#issuecomment-457144588.
@bors r-

(please please `--bless` your tests with `--compare-mode=nll`  :) )

**Pull request merged**
