### PR TITLE
Update minifier

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
What changed in this version that warrants an upgrade on its own?

**Comment by GuillaumeGomez** [comment]
Just a code improvement. But as for now, I'd like to keep this open while I'm working on it.

**Comment by TimNN** [comment]
Ping from triage, @QuietMisdreavus: This PR requires your review.

**Comment by QuietMisdreavus** [comment]
> But as for now, I'd like to keep this open while I'm working on it.

@GuillaumeGomez Do you want this PR merged as-is? I don't see a big reason to update a dependency unless it fixes a bug, adds a feature that we need, or includes a major performance improvement. I don't know what the policy is more generally, but that's my personal opinion.

**Comment by GuillaumeGomez** [comment]
No no, I'd prefer not. I tested on my own and to not forget about it, I opened a PR. Some great changes will occur soon, I'll ping once it'll be "ready".

**Comment by TimNN** [comment]
> Some great changes will occur soon, I'll ping once it'll be "ready".

Ping from triage! This PR has been blocked / inactive for a while now, so I'm closing it in line with our current [triage guidelines](https://forge.rust-lang.org/triage-procedure.html). Feel free to re-open once you are ready & thanks for your contributions to the Rust project!

**Pull request closed without merging**
