### PR TITLE
Stabilize tool_attributes

### PR DESCRIPTION
**Pull request by mominul**
Stabilize tool_attributes feature! :tada: 

cc #44690 
 r? @nrc

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This is currently blocked on https://github.com/rust-lang/rust/pull/50911 landing first, so I'm gonna mark this as S-blocked

**Comment by nrc** [comment]
Looks like there are still some tests which need removing or changing. Do we have docs for this feature?

**Comment by mominul** [comment]
I have fixed the compile-fail testing issue and I can run the whole compile-fail test suite locally. I will resolve these conflicts when the blocking PR is merged.

**Comment by TimNN** [comment]
Ping from triage @mominul: The blocking PR has been merged, however this PR requires a rebase.

**Comment by mominul** [comment]
I think this feature already has been stabilized by #53459, am I wrong?

**Comment by TimNN** [comment]
> I think this feature already has been stabilized by #53459, am I wrong?

No, it looks like you are quite correct!

**Pull request closed without merging**
