### PR TITLE
Make `VecDeque::new` const

### PR DESCRIPTION
**Pull request by Sp00ph**
(See #105072)

### CODE REVIEW

**Comment by Sp00ph** [comment]
Had a little issue with git, should be good now.

@rustbot label -A-bootstrap -A-testsuite

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

This PR changes the stable `VecDeque::new` constructor to be callable in `const`, and immediately stabilizes that. I don't feel there is a need to land this `const` as unstable first. The closely related `Vec::new` has been callable in const on stable for a long time.

https://doc.rust-lang.org/nightly/std/collections/struct.VecDeque.html#method.new

**Comment by Sp00ph** [comment]
Is there anything blocking this or are we just waiting on one more reviewer to tick their box?

**Comment by dtolnay** [comment]
I'm gonna take the liberty of checking @yaahc's box because she has stepped down from T-libs-api. This PR would be in FCP already if the checkbox list were accurate.

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
