### PR TITLE
Bump `cc` and run `cargo update` for bootstrap

### PR DESCRIPTION
**Pull request by tgross35**
Bump `cc` to 1.1.22, which includes a caching fix. Also run `cargo update` which does a minor increment on a few dependencies.

### CODE REVIEW

**Comment by tgross35** [comment]
The differences in `cc` are minor enough that I doubt anything needs to change in bootstrap (responding to the comment). We specifically want https://github.com/rust-lang/cc-rs/pull/1215, which seems like it has a chance in improving the MSVC issue. More context on that starting around https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Spurious.20CI.20errors.20on.20x86_64-msvc-ext/near/472962033.

**Comment by Kobzol** [comment]
Looks like the dependency count stayed the same. The comment in the `Cargo.toml` file about `cc` updates sounded a bit worrying though :)

**Comment by tgross35** [comment]
Hm, not sure why it looks like these are getting the network errors. I made this just to see what the changes looked like after the automation PR.

> Looks like the dependency count stayed the same. The comment in the `Cargo.toml` file about `cc` updates sounded a bit worrying though :)

Yes, I thought so too :) but we specifically want https://github.com/rust-lang/cc-rs/pull/1215 since it might help the MSVC error, and the only other changes are https://github.com/rust-lang/cc-rs/pull/1209 and https://github.com/rust-lang/cc-rs/pull/1212 which I don't think would affect anything here, so that doesn't seem too concerning

**Comment by tgross35** [comment]
cc also @ChrisDenton since you've been doing some of the `cc` updates

**Comment by tgross35** [comment]
Cc @onur-ozkan since you authored the comment at https://github.com/rust-lang/rust/blob/a1fd2351803fd7db9c70093e19c63e11eded953c/src/bootstrap/Cargo.toml#L37-L39, is there anything that would need to change with this `cc` update?

**Comment by onur-ozkan** [comment]
> Cc @onur-ozkan since you authored the comment at
> 
> https://github.com/rust-lang/rust/blob/a1fd2351803fd7db9c70093e19c63e11eded953c/src/bootstrap/Cargo.toml#L37-L39
> 
> , is there anything that would need to change with this `cc` update?

It's never clear tbh. We need to try and see if we need to make a change on bootstrap :)

**Comment by Kobzol** [comment]
So let's just merge and see what breaks? Do you want to wait for some confirmation from soneone @tgross35?

**Comment by tgross35** [comment]
Oh no I just wanted to make sure I wasn't missing something, this is ready whenever you are :)

**Comment by Kobzol** [comment]
Ok, let's try.

@bors r+ rollup=never

**Pull request merged**
