### PR TITLE
Use Vec extend and collect instead of repeatedly calling push

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Nice! Since it'll very likely impact performance, I'll prevent putting it into a rollup.

@bors: r+ rollup=iffy

**Comment by GuillaumeGomez** [comment]
Wow, that's much better than what I expected!

**Comment by notriddle** [comment]
That’s the magic of the TrustedLen trait 😉

**Comment by camelid** [comment]
Wow, that is really impressive!

**Comment by camelid** [comment]
> Since it'll very likely impact performance, I'll prevent putting it into a rollup.

Just a note: it's better to use rollup=never if a PR will very likely affect perf. Otherwise, you can't tell what the perf changes were, and it may mask perf regressions in other rolled-up PRs.

**Comment by GuillaumeGomez** [comment]
`iffy` means "better not put it into a rollup unless it's strongly needed for whatever reason".

**Comment by camelid** [comment]
> `iffy` means "better not put it into a rollup unless it's strongly needed for whatever reason". So seems like a good match.

If for some reason, someone *really* needed to put it into a rollup, they could just mark the PR as rollup-able. In my experience, `iffy` usually means "prone to failures during bors testing" or "may have slight perf changes, but unlikely to be anything significant".

**Pull request merged**
