### PR TITLE
resolve: Collapse `macro_rules` scope chains on the fly

### PR DESCRIPTION
**Pull request by petrochenkov**
Otherwise they grow too long and you have to endlessly walk through them when resolving macros or imports.
Addresses https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Slow.20Builtin.20Derives/near/215750815

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
Looking over the implementation, I believe it is similar to the "path compression" optimization for union-find (collapsing redirects in a chain, i.e. replacing `A -> B -> C -> D` with `A -> D` where `B` and `C` are semantically noops, mere "aliases").

Here the chain is that of lexical (can only be seen "below" the definition, like `let`) `macro_rules!` names (as opposed to `macro`, which works like other Rust definitions), and the "noops" entries in the chain come from "there is a macro invocation which *could* expand to `macro_rules!` definitions" entries that got expanded (and don't themselves define `macro_rules!` macros).

Unlike union-find, however, this optimization is done eagerly (on every expansion), as opposed to lazily (when traversing these chains). I'm trusting @petrochenkov that this is more efficient, even though it might be clearer as an optimization to lazily cache-in-place during traversal, the way union-find "path compression" tends to work. Either way, I trust I can:

@bors r+

**Comment by petrochenkov** [comment]
@eddyb 
I'll try using lazy compression in a follow up.
I'm not sure what would be more efficient, on one hand I suspect that all these scopes are going to be traversed in the end, on another hand the eager update like it's done now can result in multiple updates where lazy one could result in one.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/issues/78665 - spurious, but known to fail often.
Let's @bors retry anyway.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/issues/78665 - spurious, but known to fail often.
Let's @bors retry anyway.

**Comment by rylev** [comment]
We may want to merge this benchmark first (https://github.com/rust-lang/rustc-perf/pull/791) so that we can easily see the impact of this change on compiler performance. Locally these changes allow the benchmark to compile in half the time.

**Comment by rylev** [comment]
https://github.com/rust-lang/rustc-perf/pull/791 has been merged so when this is merged we will be able to view the full perf improvement.

**Comment by jyn514** [comment]
Network error (https://github.com/rust-lang/cargo/issues/8517).

@bors retry

**Comment by jyn514** [comment]
Same error :/ @ehuss mentioned in https://github.com/rust-lang/cargo/issues/8517#issuecomment-665429054 that this happens more during GitHub outages and YouTube went down for a bit around an hour ago, so maybe that's the issue? Going to avoid retrying for now.

**Comment by ehuss** [comment]
It's not related to outages, it's just a case of bad luck.  The pack files in the git repositories are in flux as they are constantly updated (each time a crate is published) and periodically recompressed.  If it happens to recompress the pack file in such a way that it hits an edge condition, then it will fail.  The only options are to run again and hope that the load balancer picks a different server that packed it differently, or to wait for the affected server to rebuild its pack files (which seems to happen every hour or two?  I'm not sure) and hope it doesn't hit the edge case again.

**Comment by kennytm** [comment]
@bors retry 

A PR has been successfully merged, assuming the error has been fixed.

**Comment by petrochenkov** [comment]
>warning: spurious network error (1 tries remaining): error inflating zlib stream; class=Zlib (5)

@bors retry

**Pull request merged**
