### PR TITLE
elaborate obligations in coherence

### PR DESCRIPTION
**Pull request by lcnr**
The following test currently does not pass coherence:
```rust
trait Super {}
trait Sub<T>: Super {}

trait Overlap<T> {}
impl<T, U: Sub<T>> Overlap<T> for U {}
impl<T> Overlap<T> for () {}

fn main() {}
```

We check whether `(): Sub<?t>` holds. This stalls with ambiguity as downstream crates may add an impl for `(): Sub<Local>`. However, its super trait bound `(): Super` cannot be implemented downstream, so this one is known not to hold.

By elaborating the bounds in the implicit negative overlap check, this now compiles. This is necessary to prevent breakage from enabling `-Znext-solver=coherence` (#121848), see tests/ui/coherence/super-traits/super-trait-knowable-2.rs for more details.

r? @compiler-errors

### CODE REVIEW

**Comment by lcnr** [comment]
@rfcbot fcp merge

**Review by compiler-errors — APPROVED** [review]
r=me with TODO and FCP

**Comment by compiler-errors** [comment]
@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

Notably it's already a breaking change to remove a supertrait.

**Comment by BoxyUwU** [comment]
do we want to skip the 10 day waiting period so that this is included in the same beta bumps as new solver in coherence stabilization?

**Comment by lcnr** [comment]
the last beta bump was on the 26th of April, so this PR and the stabilization PR will definitely be on the same beta version unless we somehow delay this PR by 5 weeks

**Comment by matthiaskrgr** [comment]
@bors r-
guess this fails here: https://github.com/rust-lang-ci/rust/actions/runs/9067379305/job/24912371152#step:26:3926

**Comment by lcnr** [comment]
closing in favor of https://github.com/rust-lang/rust/pull/127574

**Pull request closed without merging**
