### PR TITLE
Optimize `core::char::CaseMappingIter`

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
Godbolt says this saves a few instructions…

@rustbot label T-libs A-layout C-optimization

### CODE REVIEW

**Review by Noratrieb — COMMENTED** [review]
The changes seem fine, but this `CaseMappingIter` seems pretty complex for doing a simple operation. What's the performance of just using an `array::IntoIter` and stopping when that one sees a `\0`?
I did a bit of digging on the origin of this type and it seems to have been around forever (addaa5b1ff0d611b6568ce5fb0c6469a8e1a6ee4).

**Comment by Jules-Bertholet** [comment]
@Nilstrieb That is a much better approach, adopted.

**Review by Noratrieb — APPROVED** [review]

**Comment by Nilstrieb** [comment]
Thanks!
@bors r+

**Comment by Jules-Bertholet** [comment]
Is this just a spurious failure?

**Pull request merged**
