### PR TITLE
Update traits.md

### PR DESCRIPTION
**Pull request by Xmasreturns**
Changes to readability and some clarifications for beginners

### CODE REVIEW

**Comment by tshepang** [comment]
The only nit I have is that those lines are overlong, at least as compared to the already existing ones, otherwise this is a decent improvement... :+1:

**Comment by tshepang** [comment]
One more thing, please squash these 2 commits. Either that, or give them more meaningful commit messages.

**Comment by Xmasreturns** [comment]
@tshepang I used the edit button directly on the github file pages for these two commits, and I'm not familiar with git in shell, so I'm not sure how to squash the two together. That being said, I didn't look too hard for that function and added the second commit because it seemed like the right thing to do based on the autoresponse from rust-highfive.

**Comment by Xmasreturns** [comment]
Also, when you say the lines are overlong, do you mean number of characters per line of code or do you mean number of words per sentence?

**Comment by tshepang** [comment]
I meant characters per line.

**Comment by steveklabnik** [comment]
We do generally try to wrap to 80 characters, and squash things down into less commits. However, I try to be a bit less lax with newer contributors, and I know we talked on IRC about git being a bit hard, so I don't think, in this case, it's a huge deal. I'm about to do a lot of editing to the book over the next week or two anyway.

@bors: r+ rollup

**Pull request merged**
