### PR TITLE
Fix LLVM target triple for `x86_64-win7-windows-msvc`

### PR DESCRIPTION
**Pull request by kleisauke**
The vendor field needs to be `pc` rather than `win7`.

### CODE REVIEW

**Comment by kleisauke** [comment]
Context: https://github.com/rust-lang/cc-rs/pull/1176#discussion_r1712622811.

**Comment by Nadrieril** [comment]
r? compiler

**Comment by ChrisDenton** [comment]
This is correct. LLVM does not (ab)use the vendor field like we do. I thought we'd fixed this before but I must be misremembering.

@bors r+ rollup

**Comment by roblabla** [comment]
Ah yes, this is my bad, some copy paste fail ^^'.

:+1:

**Review by roblabla — APPROVED** [review]

**Comment by mati865** [comment]
> This is correct. LLVM does not (ab)use the vendor field like we do. I thought we'd fixed this before but I must be misremembering.

I had noticed this problem in the cc-rs repo where you were pinged for the discussion, but nothing has been done about it until now.

**Pull request merged**
