### PR TITLE
fix comment on Allocator trait

### LINKED ISSUE #107040: Safety comment on Allocator trait likely incorrect
one of the safety requirements for the `Allocator` trait is:
https://github.com/rust-lang/rust/blob/a28f3c88e50a77bc2a91889241248c4543854e61/library/core/src/alloc/mod.rs#L97-L99

afaict that's incorrect since, because of the validity requirements, it requires Allocators to never free any memory blocks until the Allocator and all clones are dropped.

It should instead be something like:
```rust
 /// * Memory blocks returned from an allocator that are [*currently allocated*] must point to
 ///   valid memory and retain their validity while they are [*currently allocated*] and at
 ///   least one of the instance and all of its clones has not been dropped.
```

### PR DESCRIPTION
**Pull request by reez12g**
fixes https://github.com/rust-lang/rust/issues/107040

### CODE REVIEW

**Comment by scottmcm** [comment]
Since this is still marked draft, I'll assume
@rustbot author

(Please comment with `@rustbot ready` when you've undrafted it and think it's ready for review.)

**Comment by scottmcm** [comment]
r? rust-lang/wg-allocators

**Comment by scottmcm** [comment]
r? rust-lang/wg-allocators

**Comment by scottmcm** [comment]
r? Amanieu
(as a legal reviewer from wg-allocators)

**Comment by Amanieu** [comment]
I think it would be clearer to just say that block must remain valid until they are deallocated or all clones of the allocator are dropped.

**Comment by reez12g** [comment]
Sorry for the delay in responding. Conflicts have been resolved.

**Comment by klensy** [comment]
Should be squashed https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy https://github.com/rust-lang/rust/pull/107916/commits/5a3a65e1cc1dbc86efce75d6ad8d33cac22348a4

**Pull request merged**
