### PR TITLE
Migrate 9 more very similar FFI `run-make` tests to rmake

### PR DESCRIPTION
**Pull request by Oneirical**
Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

For the tracking issue:

- return-non-c-like-enum-from-c
- pass-non-c-like-enum-to-c
- c-static-dylib
- c-static-rlib
- extern-fn-generic
- extern-fn-with-union
- lto-no-link-whole-rlib
- linkage-attr-on-static
- issue-28595

### CODE REVIEW

**Comment by jieyouxu** [comment]
Question: should this be blocked on another PR that also introduces the build_native_lib helper?

**Comment by Oneirical** [comment]
Yes, it should be.
@rustbot blocked #126208 

```
2024-07-12T21:01:28.3065014Z thread 'main' panicked at src/tools/compiletest/src/header.rs:47:41:
2024-07-12T21:01:28.3065873Z open test file to parse earlyprops: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
2024-07-12T21:01:28.3066711Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Also, this CI failure is VERY weird. It doesn't seem related to what this PR changes.

**Comment by Oneirical** [comment]
Just noticed it was failing because one of the files didn't get bundled with my commits. Please add `issue-28595` in the tracking issue.

**Review by jieyouxu — APPROVED** [review]
Thanks!

**Comment by Oneirical** [comment]
@rustbot ready
Rebased, please re-approve.

**Comment by jieyouxu** [comment]
LGTM, please r=me after CI is green.
@bors delegate+

**Comment by Oneirical** [comment]
That's odd, this was fixed previously, it looks like the rebase rolled back something.
@bors r-

**Comment by Oneirical** [comment]
@bors r=@jieyouxu
Fifth time's the charm?

**Pull request merged**
