### PR TITLE
Improve `unsafe` diagnostic

### LINKED ISSUE #90880: unsafe: Bad diagnostic message
Given the following code: 

```rust
pub extern "C" unsafe fn test() {}
```

The current output is:

```
error: expected `{`, found keyword `unsafe`
  --> tests/syscalls.rs:14:16
   |
14 | pub extern "C" unsafe fn test() {}
   |                ^^^^^^ expected `{`
```

Ideally the output should look like:

```
error: wrongfully placed unsafe keyword
  --> tests/syscalls.rs:14:16
   |
14 | pub extern "C" unsafe fn test() {}
   |                ^^^^ "Move after access specifier"
```

### PR DESCRIPTION
**Pull request by terrarier2111**
This fixes: https://github.com/rust-lang/rust/issues/90880
I didn't use the exact proposed messages though.

### CODE REVIEW

**Comment by terrarier2111** [comment]
@estebank could you take a look at this?

**Comment by InfRandomness** [comment]
It would be amazing if this got a review.

**Comment by jackh726** [comment]
Sorry for the delay here!

@bos r+

**Comment by InfRandomness** [comment]
Is there something holding this from being merged ? I'll fix it.

**Comment by jackh726** [comment]
Bors? @bors r+

**Pull request merged**
