### PR TITLE
Allow quantification of lifetimes outside the self type in where clauses

### LINKED ISSUE #20022: Permit higher-ranked qualifiers to enclose the self type
There is a need to permit `for` qualifiers that appear in more places. In particular, I'd like to be able to write something like this:

    where for<'a, 'b> &'a T : Foo<&'b T>

but today the parser only accepts `for` after the `:`. the rest of the code already considers `'a` and `'b` to be in scope for the self-type of the trait, so it's just the parser that has to be changed. I imagine that the `for`, in that case, would distribute over all the attached where clauses, so:

    where for<'a> T : Foo<&'a T> + Bar<&'a T>

would be equivalent to:

    where T : for<'a> Foo<&'a T> + for<'a> Bar<&'a T>

Nested `for` qualifiers would be illegal, I think:

    where for<'a> T : for<'b> Foo<&'a &'b T> // ERROR

### PR DESCRIPTION
**Pull request by nrc**
Closes #20022

r? @nikomatsakis

### CODE REVIEW

**Comment by jroesch** [comment]
The patch looks good, I think it is wise to prefer the hack for the time being.

**Comment by nikomatsakis** [comment]
This looks good but don't we want some tests of some kind?

**Comment by nikomatsakis** [comment]
(PS sorry it took me so long to review, I didn't notice this for a while)

**Comment by nick29581** [comment]
ah, crap, I forgot to `git add` the test...

**Comment by nick29581** [comment]
rebased and added tests

**Comment by nikomatsakis** [comment]
Seems reasonable. I'd sort of like a test that shows that the correct requirements are being put onto the caller (e.g. a compile-fail test where the requirement is `for<'a> &'a T : Foo` but the caller only knows that `&'x T : Foo` holds for some particular `'x`)

**Comment by nick29581** [comment]
@nikomatsakis test added

**Pull request merged**
