### PR TITLE
Add an early-exit to `overlapping_impls`

### PR DESCRIPTION
**Pull request by jonas-schievink**
This is hit in approx. 37% of all calls when building the stm32f0(x2) crate, saving a small amount of time.

This can probably be done more effectively than using `simplify_type`, since that only seems to descend by one layer.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
@rust-timer queue 96ce905

**Comment by jonas-schievink** [comment]
@rust-timer build 96ce905

**Comment by jonas-schievink** [comment]
Hmm, this made things slightly worse for a few benchmarks, and shows no improvements

**Comment by jonas-schievink** [comment]
I checked against nrf52810-pac again, and there it reduces the time spent in coherence by ~45-50% (from ~5 seconds to 2.6), so it definitely helps in some cases.

**Comment by matprec** [comment]
Would adding crates impacted by this to the rustc perf suite make sense? That the improvement you see locally do not appear in the suite suggests the these code paths are not properly exercised.

**Comment by jonas-schievink** [comment]
Indeed, and I am planning to do that, however we plan to make a number of changes to the code generator for these crates, which could change the parts of rustc they stress. I also plan to change it so the generated code builds faster all around (in addition to improving rustc performance in general).

**Comment by estebank** [comment]
I am slightly worried about the mild regressions, but `syn` actually improved.

@rust-lang/compiler Let's keep an eye out for this in case there are more regressions in the wild, but I believe that this should have a net positive impact.

@bors r+ rollup=never

**Comment by jonas-schievink** [comment]
syn-opt is extremely noisy, it probably didn't actually improve. I'll have to re-check the results anyways since other optimizations have landed since.

**Comment by petrochenkov** [comment]
>ping in https://github.com/rust-lang/rust/pull/69010#issuecomment-587226566

[triagebot] I've seen eddyb mentioning that `syn` is noisy a couple of times.

**Comment by eddyb** [comment]
> I've seen eddyb mentioning that syn is noisy a couple of times.

Yeah, the issue is #69060, and we keep seeing this pretty often.

**Comment by joelpalmer** [comment]
Triaged

**Comment by Dylan-DPC** [comment]
@jonas-schievink waiting on a rebase

**Comment by jonas-schievink** [comment]
The benchmark still looks like a slight regression. I'll have to measure this again, but I've landed some other improvements in this area, so this might not even be necessary anymore. For now, closing this until I have more time to work on compile-time improvements again.

**Pull request closed without merging**
