### PR TITLE
Leak pthread_{mutex,rwlock}_t if it's dropped while locked.

### LINKED ISSUE #85434: Destroying locked Mutex in libstd triggers miri in safe code
I tried this code through miri:

```rust
use std::sync::Mutex;

fn main(){
    let m = Mutex::new(5i32);
    
    core::mem::forget(m.lock());
}
```

I expected to see this happen: No observable behaviour, including from miri (aside from "Unsupported Operation" errors).

Instead, this happened: 
`miri` reports undefined behaviour in "Destroying locked mutex" when calling `pthread_mutex_destroy` (Note: this report is correct, calling `pthread_mutex_destroy` on a locked mutex is prescribed to be undefined behaviour by POSIX)

### Meta

This was tested on all latest versions of rustc, all using miri 0.1.54, on play.rust-lang.org:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=28904dec86ec2f64bb03163bedf37299

<details><summary>Miri Backtrace</summary>
<p>

```
error: Undefined Behavior: destroyed a locked mutex
  --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/mutex.rs:78:17
   |
78 |         let r = libc::pthread_mutex_destroy(self.inner.get());
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ destroyed a locked mutex
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
           
   = note: inside `std::sys::unix::mutex::Mutex::destroy` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/mutex.rs:78:17
   = note: inside `<std::sys_common::mutex::MovableMutex as std::ops::Drop>::drop` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/mutex.rs:98:18
   = note: inside `std::ptr::drop_in_place::<std::sys_common::mutex::MovableMutex> - shim(Some(std::sys_common::mutex::MovableMutex))` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:192:1
   = note: inside `std::ptr::drop_in_place::<std::sync::Mutex<i32>> - shim(Some(std::sync::Mutex<i32>))` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:192:1
note: inside `main` at src/main.rs:8:1
...
[9 frames before `main` omitted manually]
```

</p>
</details>

This is caused by issue presented in #31936. However, I believe that it deserves new attention given that it causes miri to fail in safe code (and is not a miri false positive, as miri is correctly reporting undefined behaviour in calling `pthread_mutex_destroy`).

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes https://github.com/rust-lang/rust/issues/85434.

### CODE REVIEW

**Comment by Amanieu** [comment]
Does this issue also apply to `pthread_rwlock_t`? If so then we should apply the same workaround there.

**Comment by m-ou-se** [comment]
>  Attempting to destroy an uninitialized read-write lock results in undefined behavior.

Yes. Updating the PR. :)

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/98263#issuecomment-1159821176
```
error[E0425]: cannot find function `forget` in this scope
--> library/std/src/sys/unix/locks/pthread_rwlock.rs:27:13
|
27|             forget(rwlock);
| ^^^^^^not found in this scope
|
help: consider importing one of these items
|
1| use core::intrinsics::forget;
|
1| use core::mem::forget;
|
1| use crate::intrinsics::forget;
|
1| use crate::mem::forget;
|
```

Missing import on macOS.
@bors r-

**Pull request merged**
