### PR TITLE
Make `private_in_public` compatibility lint warn-by-default again

### PR DESCRIPTION
**Pull request by petrochenkov**
More details: https://internals.rust-lang.org/t/regression-report-stable-2016-08-16-vs-beta-2016-08-26/3930/10

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Do we need to backport this to beta?

**Comment by nikomatsakis** [comment]
(I'm going to assume we do, cc @brson)

**Comment by petrochenkov** [comment]
Btw, I sent PRs to all affected crates, most of them are merged/published.

**Pull request merged**
