### PR TITLE
nix-shell documentation

### PR DESCRIPTION
**Pull request by pelasgus**

### CODE REVIEW

**Comment by Nilstrieb** [comment]
We already have a nix shell in the dev guide to copy and adjust as liked
https://rustc-dev-guide.rust-lang.org/building/suggested.html#using-nix-shell

I'm not sure whether it's worth it to keep one in the repo (of we do, then it should definitely go into `src/etc` but I think it's better to just link to the dev guide instead.

**Comment by Mark-Simulacrum** [comment]
I don't think we should keep two copies of this, and rustc-dev-guide seems like the better place to me. I'm happy to merge a PR pointing to the dev guide for Nix specifically if we don't have that yet.

**Comment by Dylan-DPC** [comment]
@pelasgus any updates?

**Comment by Dylan-DPC** [comment]
Closing this as it's better to have this in one place and has been inactive for a while

**Comment by futile** [comment]
Just spent quite some time (read: hours) creating my own nix-shell (well, a `flake.nix`) for rustc development, before I found the one in [the docs](https://rustc-dev-guide.rust-lang.org/building/suggested.html#using-nix-shell) :upside_down_face:. There are some non-obvious parts, and it's hard to know that you got it right, even if it works for what you're testing.

I tried searching for `*.nix` files in the repo before, but didn't see any, and also didn't find the relevant docs page while googling. It seems the magic google incantation needs to contain `rustc dev nix-shell`, just `rustc dev nix` or `rustc nix-shell` is not enough. And even then it's not the first result, but it can be found.

Also, nowadays Nix flakes are used a lot, where the file is then called `flake.nix`, and googling for `rustc dev flake` or `rustc devShell` (`devShell` is the name used in `flake.nix`) doesn't turn up any (helpful) links either, especially not the one in the rustc dev guide.

So I think discoverability would really benefit from adding an (example) nix-shell to the source tree, e.g., in `src/etc/nix/{flake.nix,shell.nix}`. These two (new and old Nix shell formats) can be made compatible, i.e., without having to repeat the configuration.

Some other way of increasing discoverability would also be ok, but I think just adding it as a file, even just `shell.nix`, ignoring `flake.nix` for now, would be a massive help.

Posted here since the discussion seemed related/relevant, let me know if I should open a new issue/PR instead! Cheers & thanks! :)

**Comment by pelasgus** [comment]
@Dylan-DPC please forgive my tardiness. Please do re-open, I will provide new declarative shells for both nix(shell & flake) and guix, contribute them to the docs and then restructure the readme so they link here.

**Pull request closed without merging**
