### PR TITLE
Bump backtrace to 0.3.72

### PR DESCRIPTION
**Pull request by workingjubilee**
This removes a bunch of dead code, contains critical aarch64-windows fixes, some less-critical windows-in-general improvements, adds visionOS support (and probably improves support for a bunch of Apple platforms...), and harmonizes backtrace's dependencies with rustc/std's.

See https://github.com/rust-lang/backtrace-rs/compare/0.3.71...0.3.72

r? @ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
Almost forgot I had set this up before it actually got tagged. Using the actual tag now (it's just a matter of including the bump commit versus not, though).

@bors r+

**Comment by glandium** [comment]
This had the unfortunate side effect of adding another version of addr2line and gimli.

**Comment by glandium** [comment]
This actually doesn't make sense. This change added a dependency on addr2line 0.22.0 in a commit that says "Sync libstd deps with backtrace", when backtrace uses 0.21.

**Comment by glandium** [comment]
Opened #126292 126292

**Comment by workingjubilee** [comment]
@glandium Hi, can you source your statement?

**Comment by workingjubilee** [comment]
We can thin the herd of duplicate gimlis if we land https://github.com/rust-lang/thorin/pull/30 which will allow the next backtrace to line up if it rolls forward to use addr2line 0.23

**Pull request merged**
