### PR TITLE
Upgrade indexmap and thorin-dwp to use hashbrown 0.12

### PR DESCRIPTION
**Pull request by cuviper**
This removes the last dependencies on hashbrown 0.11.

This also upgrades to hashbrown 0.12.3 to fix a double-free (#99372).

### CODE REVIEW

**Comment by lqd** [comment]
just the usual sanity check:

@bors try @rust-timer queue

**Comment by lqd** [comment]
looks like usual ctfe-stress-5 noise.

r=me rollup=never if you agree

**Comment by Mark-Simulacrum** [comment]
@bors r+

Yeah, seems like it. Nice improvement in bootstrap times as well!

**Comment by lqd** [comment]
Indeed, the `object` speedup is great!

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

@Amanieu Do we have a reference for when the double-drop was introduced into hashbrown? I would've expected to see that in the changelog entry (https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md#v0123---2022-07-17), at least, but it doesn't seem to be there. Has it always been there?

**Comment by Amanieu** [comment]
I think it's always been there.

**Comment by Mark-Simulacrum** [comment]
beta-nominating this PR; this addresses a soundness problem in hashbrown (double-free in clone_from) which seems good to roll out to stable on a faster schedule.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-07-28/near/291187112)

@rustbot label +beta-accepted

**Pull request merged**
