### PR TITLE
fix for new attributes failing issue #22964

### PR DESCRIPTION
**Pull request by awlnx**

### CODE REVIEW

**Comment by nrc** [comment]
I'm not clear on why these cfgs shouldn't be removed on snapshot? Isn't bootstrapping then done? Perhaps I don't understand the motivation here.

**Comment by nrc** [comment]
cc @manishearth

**Comment by awlnx** [comment]
from my limited understanding during stage0 a new rust attribute isn't recognized. So we don't fail for #[foo] until stage1. bootstrap might of been the wrong word to use.e

**Comment by awlnx** [comment]
cc @huonw

**Comment by nrc** [comment]
What is the motivation for using these blanket cfgs, rather than a cfg(not(stage0)) when you use a new attribute (like we do with everything else that is a struggle due to bootstrapping)?

**Comment by awlnx** [comment]
@huonw would probably be the best person to ask about this. He pointed out over irc that @manishearth  proposed fix #[cfg(not(stage0))] would have some sort of staging issue.

**Comment by Manishearth** [comment]
@nrc This is because we want people to be able to add new custom attributes easily. The current process is:

 - Add them to `libsyntax/feature_gate.rs`
 - Wait for a snapshot
 - Continue

**Comment by Manishearth** [comment]
This looks good to me, but [it seems to be failing tidy](https://travis-ci.org/rust-lang/rust/builds/53145187). What does `make tidy` tell you?

**Comment by nrc** [comment]
@Manishearth That is the same procedure for making any compiler changes, not really sure why we should give special treatment to new attributes

**Comment by Manishearth** [comment]
Because custom_attribute isn't supposed to apply to the compiler anyway. It's for back compat only, so it's annoying to have this break what is otherwise a straightforward workflow.

**Comment by Manishearth** [comment]
Basically, this removes an extra annoyance from bootstrapping and makes us require less snapshots.

**Comment by nrc** [comment]
I don't think it means fewer snapshots, it means you get to avoid faffing around with cfgs, which is still a good thing (because it is so annoying). I do worry that this is a bit of a footgun every time someone does a snapshot (it means they're less automatic to do). I also like having a uniform process rather than exceptions, even if those exceptions make things easier.

Still it is simple to rewind, and look likes a win overall, so @bors: r+ 1e68dfd

**Comment by nrc** [comment]
Oh, I guess squashing the commits would be better too

**Comment by nrc** [comment]
Sorry, I please get rid of the merge commit - rebase and squash the commits please, r+ with that

**Comment by awlnx** [comment]
@nrc all finished up

**Pull request merged**
