### PR TITLE
Warn for bindings named same as variants when matching against a borrow

### LINKED ISSUE #67776: "pattern binding is named the same as one of the variants of the type `<type>`" warning is not generated when matching against a borrow
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6b951a2fc1cc70455730b35d42fcf483

This issue has been assigned to @LeSeulArtichaut via [this comment](https://github.com/rust-lang/rust/issues/67776#issuecomment-570070940).

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Fixes #67776

### CODE REVIEW

**Comment by Centril** [comment]
Please also add a regression test for the diff you've introduced.

r? @Centril

**Comment by LeSeulArtichaut** [comment]
> Please also add a regression test for the diff you've introduced.

I was going to ask if this was necessairy, thanks for answering

**Comment by LeSeulArtichaut** [comment]
@Centril added the test. Please tell me if it is correctly named and placed in the test directories.

@rustbot modify labels to -S-waiting-on-author +S-waiting-on-review

**Comment by csmoe** [comment]
append `--bless` to the `x.py ...` command, ui err file will be updated automatically.

**Comment by LeSeulArtichaut** [comment]
@Centril Updated according to review

@rustbot modify labels to -S-waiting-on-author +S-waiting-on-review

**Review by Centril — APPROVED** [review]

**Comment by Centril** [comment]
Thanks! @bors r+ rollup

**Pull request merged**
