### PR TITLE
Inline overlap based CGU merging

### PR DESCRIPTION
**Pull request by nnethercote**
Introduce a new CGU merging algorithm that aims to minimize the number of duplicated inlined items.

r? @wesleywiser

### CODE REVIEW

**Comment by nnethercote** [comment]
Some good results:
- Instructions counts are improved, though that doesn't really matter much for this case.
- Cycle counts are slightly worse, but that also doesn't matter much.
- Walltimes are roughly neutral, with wins and losses kinda balancing (esp. if you select "Show non-relevant results" to see all the small changes).
- max-rss has a few big wins for large real-world crates, yay.
- Binary size has some medium wins for large real-world crates, yay.
- Bootstrap is 8.9s better, yay!

**Comment by nnethercote** [comment]
@wesleywiser: this is ready for review!

Meanwhile, let's do another perf run, just to see if anything changes.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
The second perf run gives results similar to the first.

**Review by wesleywiser — APPROVED** [review]

**Comment by lqd** [comment]
Let's not bors retry immediately so that wesleywiser's nit can be fixed in this PR -- but the CI issue was spurious "failed to get successful HTTP response from `zerovec` (18.165.83.98), got 421"

**Comment by nnethercote** [comment]
I fixed the typo.

@bors r=pnkfelix

**Comment by tmandry** [comment]
I imagine that repeatedly merging `cgus[N-1]` with its closest neighbor in `cgus[N:]` could make the results very sensitive to the particular choice of N (codegen units). That would be very relevant for binary size, which is already subject to the many whims of the LLVM inliner. (I think most people who really care about binary size are setting N=1 today, often in development builds even, but this seems like a promising direction that could relax the need for that in the future.)

Out of curiosity @nnethercote, did you see anything while working on this that would suggest the results are, or are not, very stable with respect to small changes in the number of codegen units?

**Comment by nnethercote** [comment]
I have no data one way or the other. I never tried changing the default N away from 16.

**Pull request merged**
