### PR TITLE
std::net: Ipv4Addr and Ipv6Addr improvements

### PR DESCRIPTION
**Pull request by little-dude**
I picked up my previous un-finished PR: https://github.com/rust-lang/rust/pull/51832
Two tests are failing right now, but I'm working on it.

Ref: https://github.com/rust-lang/rust/issues/27709

### CODE REVIEW

**Comment by little-dude** [comment]
Oops. Looks like I messed up my rebasing and that there are formatting errors.

**Comment by little-dude** [comment]
How can I get stacktraces with all the line numbers, when running the tests?
I run:

```
RUST_BACKTRACE=full python x.py test src/libstd --stage 1
```

But the stacktrace is just:

```
  left: `true`,                                                                                         
 right: `false`', libstd/net/ip.rs:1946:13                                                              
stack backtrace:                                           
   0:     0x55d5563891cf - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h94bf54f902935668 
   1:     0x55d55635d9f7 - std::sys_common::backtrace::print::h29623c1aa060fc2f                         
   2:     0x55d5563f3e2f - std::panicking::default_hook::{{closure}}::h131049a1fc0672a2                 
   3:     0x55d5563f45ad - std::panicking::rust_panic_with_hook::h61610c5f8013cd16                      
   4:     0x55d5563f3fd0 - std::panicking::continue_panic_fmt::h721927dbbb0e40f5                        
   5:     0x55d5563f3f1e - std::panicking::begin_panic_fmt::h81505cc781e6dfe2                           
   6:     0x55d5563fb005 - std::net::ip::tests::ip_properties::check6::hf70d0d1be4e61588                
   7:     0x55d5563fa5af - std::net::ip::tests::ip_properties::h6be1fabe5a9bc980                        
   8:     0x7f281962949e - <F as alloc::boxed::FnBox<A>>::call_box::h94f7e1459d039765                   
   9:     0x7f2819583819 - __rust_maybe_catch_panic                                                     
  10:     0x7f281961797d - std::sys_common::backtrace::__rust_begin_short_backtrace::h4b5c31c858f402b8  
  11:     0x7f281960db84 - std::panicking::try::do_call::h2f9e4885c52d06ae
  12:     0x7f2819583819 - __rust_maybe_catch_panic                                                     
  13:     0x7f281960912c - <F as alloc::boxed::FnBox<A>>::call_box::h6396d3a5d65778c6                   
  14:     0x7f281954c0ad - std::sys_common::thread::start_thread::h8809e36f95be609f                     
  15:     0x7f2819578d85 - std::sys::unix::thread::Thread::new::thread_start::hda87df3389a6b90f
  16:     0x7f2819660a9c - start_thread
  17:     0x7f281940cb22 - clone
  18:                0x0 - <unknown>
```

Also, what's the fastest way to run these tests? It seems that many things get re-compiled with the above command, not just libstd.

**Comment by little-dude** [comment]
Every iteration (update a test and run the tests) takes 20 minutes, how do people usually manage that? There must be a way to have a faster edit -> test cycle no?

**Comment by little-dude** [comment]
Building the doc or running the tests more than 30 minutes locally, it's really hard to test changes, even as simple as these. Am I doing something wrong? What's people workflow when they make changes to libstd?

**Comment by clarcharr** [comment]
Question: if these were changed to slice matches, would the compiler generate more optimal code? It seems like the complexity in these methods would probably generate much more code than one would want but I'm curious if that's actually the case.

**Comment by little-dude** [comment]
@clarcharr I have no idea. We don't have benchmarks for these but this is something I could add.

To whoever will review this PR, I still [have a few questions](https://github.com/rust-lang/rust/pull/56050#issuecomment-439742420) regarding the tests: how to run them quickly, and  how to get full stacktraces. That would be really helpful to fix the existing tests and write new ones.

**Comment by TimNN** [comment]
> How can I get stacktraces with all the line numbers?

I don't know what the correct `config.toml` settings are for this. As a workaround, maybe you could turn `check()` into a macro, which includes the line number? Or add the failing IP address to the assertion message in check()?

> What's the fastest way to run the tests?

I don't know.

> How could the tests be refactored?

Maybe have multiple `check()` functions, which each only take a limited number of arguments?

**Comment by Dylan-DPC** [comment]
ping from triage @little-dude Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again!

**Pull request closed without merging**
