### PR TITLE
Re-enable M1 runners on GitHub Actions

### PR DESCRIPTION
**Pull request by shepmaster**
r? @ghost

### CODE REVIEW

**Comment by jdno** [comment]
I'm curious to see if the 7GB RAM might be an issue and what the performance of the runners will be. 😅

@bors r+ rollup=never

**Comment by shepmaster** [comment]
> what the performance of the runners will be

The [try build](https://github.com/rust-lang-ci/rust/actions/runs/7716459589/job/21033311535) took 2h 59m 24s; will be interesting to see how that compares to the future builds.

**Comment by shepmaster** [comment]
👀 https://twitter.com/charliermarsh/status/1754542590517551258

**Comment by shepmaster** [comment]
@matthiaskrgr seems unlikely as `dist-apple-various` failed which is not one that was changed by this PR.

**Pull request merged**
