### PR TITLE
Remove most box syntax from librustdoc

### PR DESCRIPTION
**Pull request by est31**
This is the second attempt after the librustdoc specific changes have been reverted from #87781 in #89134, due to a minor, but exant regression caused by the changes. ~~There have been some changes to librustdoc in the past and maybe thanks to them there is no regression any more. If there is still a regression, one can investigate further and maybe find ways to fix the regressions. Thus, i request a perf run.~~ Edit: turns out there is still a regression, but it's caused only by a subset of the changes. So I've changed this PR to only contains the changes that don't cause any performance regressions, keeping the regression causing changes for a later PR.

### CODE REVIEW

**Comment by jyn514** [comment]
I'm no longer on the rustdoc team, please don't assign me on PRs.

r? rust-lang/rustdoc

**Comment by est31** [comment]
> I'm no longer on the rustdoc team, please don't assign me on PRs.

@jyn514 didn't know that, sorry!

**Comment by est31** [comment]
Okay so the regression is still around. I've split up the change into multiple commits. I've sorted them by how much performance-relevant I think they are, so mostly by size if the type is obvious. This is of course not perfect, e.g. cold code should be less performance relevant than hot code, and what also matters is which optimizations LLVM is doing. But I'm doing a first approximation for now.

I was surprised by how large `ItemKind` was: 240 bytes! It might be an idea to work on reducing the size by additional boxing. Maybe there are already issues/PRs for it? Need to check. For now I have excluded structs larger than 100 bytes from the PR, so `ItemKind` is not included.

Can this get another perf run? Then I'll add back the larger structs and will ask for another perf run (because it's an effect close to the noise level).

**Comment by jyn514** [comment]
> I was surprised by how large `ItemKind` was: 240 bytes! It might be an idea to work on reducing the size by additional boxing. Maybe there are already issues/PRs for it? Need to check. For now I have excluded structs larger than 100 bytes from the PR, so `ItemKind` is not included.

https://github.com/rust-lang/rust/pull/79975

**Comment by est31** [comment]
This is very good, the regression is gone. It means that the regression is either in the commit that migrates `Box<BareFunctionDecl>` creation, or the commit that migrates `Box<ItemKind>` creation. I would guess it's in the latter only.

**Comment by est31** [comment]
I've added the commit with the `Box<BareFunctionDecl>` changes. Can this get another perf run? If that one is good, maybe this PR can be merged, as it contains trivial changes, and I can work on a way to solve the issue for `ItemKind` in another PR, e.g. by boxing some content.

**Comment by est31** [comment]
Yes, so it's the `ItemKind` changes only. Ready for review.

**Pull request merged**
