### PR TITLE
Update Clippy

### LINKED ISSUE #66989: `clippy-driver` no longer builds after rust-lang/rust#66982
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#66982, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by flip1995**
Fixes #66989

r? @Manishearth @Centril

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Looks like the latest rollup broke clippy again so I guess this can be cancelled... :(

**Comment by RalfJung** [comment]
"r-" just takes it off the queue but doesn't cancel a running job. "retry" does.

@bors retry

**Comment by flip1995** [comment]
Updated Clippy. Ready for another r+

**Pull request merged**
