### PR TITLE
Upgrade to 9.4 xcode

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
cc @kennytm @alexcrichton 

Going to try 9.4-moar and then revert to regular 9.4 if this doesn't work.

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r- try- retry

Travis isn't even starting 😕

**Comment by Mark-Simulacrum** [comment]
Yeah, I can't get builds to trigger at all for rust-lang/rust on Travis; rust-lang/cargo and rust-lang-nursery/rustc-perf are fine. I'm not sure what could be causing this...

**Pull request closed without merging**
