### PR TITLE
Use the updated Rust logo in rustdoc

### LINKED ISSUE #92831: rustdoc: use SVG form of Rust logo by default
Right now rustdoc's default logo is a PNG, which can look fuzzy on large or high DPI screens. Instead, we should use an SVG logo. For instance, there is one available at https://www.rust-lang.org/policies/media-guide. Note that it has somewhat wider margins than the PNG we currently use, so would require some tweaking to have the right size.

### PR DESCRIPTION
**Pull request by Urgau**
This pull-request use the updated Rust logo from https://github.com/rust-lang/rust-artwork/pull/9 and also change the logo format from PNG to SVG.

| Before | After |
| --- | --- |
| Screenshot 2022-01-13 at 14-33-40 std - Rust | Screenshot 2022-01-13 at 14-33-15 std - Rust |

I also took the liberty to update the two PNG favicons with the SVG reducing their size by ~35% each.

Fixes https://github.com/rust-lang/rust/issues/92831

r? @jsha

### CODE REVIEW

**Comment by jsha** [comment]
@GuillaumeGomez interesting, I didn't know SVG was that slow! Do you have a citation for that? We are already using SVG for all of our icons. I doubt changing the logo as well would cause a noticeable performance problem. Are there specific platforms on which SVG is very slow?

**Comment by GuillaumeGomez** [comment]
No, it's "browser knowledge": SVG aren't GPU accelerated for display. It doesn't change much at the end of the day though I guess...

**Comment by jsha** [comment]
This page seems to suggest it's an issue for large, complex SVGs with many points: https://css-tricks.com/high-performance-svgs/. You can see in the diff here that the Rust logo is a nice, simple, tiny SVG.

**Comment by GuillaumeGomez** [comment]
On that part we agree, what I meant was simply that `svg` was much slower than `png`. But in our case it's not really an issue I suppose.

Thanks again @Urgau!

@bors: r+ rollup

**Comment by notriddle** [comment]
Our webfonts probably have more overhead than this icon, both because they're in the critical path, and because this icon is less complicated than some of the glyphs they're rendering.

**Comment by pierwill** [comment]
> You can see in the diff here that the Rust logo is a nice, simple, tiny SVG.

I've been doing computers too long because I actually just thought "wow, that SVG has some [beautiful source code](https://github.com/rust-lang/rust/pull/92854/files#diff-4e1bb4dd5fa2a5b011ad63b4fca94f6f365794bcd106dbbf7a8b16e0cdc0bbe1)."

**Pull request merged**
