### PR TITLE
Update E0220 message to new format

### LINKED ISSUE #35385: E0220 needs to be updated to new format
From: src/test/compile-fail/E0220.rs

Error E0220 needs a span_label, updating it from:

```
error[E0220]: associated type `F` not found for `Trait`
  --> src/test/compile-fail/E0220.rs:15:18
   |
15 | type Foo = Trait<F=i32>; //~ ERROR E0220
   |                  ^^^^^
```

To:

```
error[E0220]: associated type `F` not found for `Trait`
  --> src/test/compile-fail/E0220.rs:15:18
   |
15 | type Foo = Trait<F=i32>; //~ ERROR E0220
   |                  ^^^^^ associated `F` not found in `Trait`
```

### PR DESCRIPTION
**Pull request by chamoysvoice**
Part of #35233 .
Fixes #35385.

r? @jonathandturner

Should it keep E0191?

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good.  Before we take the PR, please squash the 2 commits down to 1 commit.

**Comment by jonathandturner** [comment]
Great!

@bors r+ rollup

**Comment by TimNN** [comment]
From a local build of the rollup #35462 which included this PR, I believe that this PR causes the `compile-fail` tests `E0220.rs` and `unboxed-closure-sugar-wrong-trait.rs` to fail due to missing notes, see https://github.com/rust-lang/rust/pull/35462#issuecomment-238091144 for the full test output.

Also, @jonathandturner from looking at the diff, the `span_label` does not seem to include any additional information (same span, only slightly reworded message), does it even make sense to have a `span_label` in that case?

**Comment by jonathandturner** [comment]
@bors r- 

Looks like there might be some additional unit tests that need to be updated with this PR.  @TimNN mentions them above.

@TimNN - labels are good for readability, even if they just reiterate the error title.  In our tests, people tend to see the label first.

**Comment by TimNN** [comment]
@jonathandturner Thanks for the info, I just noticed and wanted to ask about it :)

However shouldn't the `span_label` better be `` associated **type** `{}` [...]``? The current message like ``associated `F` not`` doesn't read very well to me.

**Comment by jonathandturner** [comment]
@TimNN - it reads better, but it's also longer.  Perhaps a phrasing like "associated type `{}` not found" without the "in `{}`", since it's already on the label, might work better.

**Comment by TimNN** [comment]
@jonathandturner I (personally) like that suggestion very much!

**Comment by chamoysvoice** [comment]
@jonathandturner so this PR needs to be built after E0191 right? or is it another problem?

Can I help?

Also I'm taking you suggestion of removing "in {}" into the E0220 phrase

**Comment by jonathandturner** [comment]
@chamoysvoice - sorry, I missed this question.  And yes, please take the suggestion to shorten the label

**Comment by chamoysvoice** [comment]
OOOPS! missing parenthesis, for some reason my local branch has that parenthesis, somehow I didn't merge it, no worries I'll fix it.

**Comment by jonathandturner** [comment]
Thanks!

@bors r+ rollup

**Comment by jonathandturner** [comment]
@chamoysvoice - You'll need to fix some of the test failures before this PR can be accepted.

```
error: /build/src/test/compile-fail/E0220.rs:15: unexpected "error": '15:12: 15:24: the value of the associated type `Bar` (from the trait `Trait`) must be specified [E0191]'
error: /build/src/test/compile-fail/E0220.rs:15: unexpected "note": 'missing associated type `Bar` value'
error: /build/src/test/compile-fail/E0220.rs:16: expected error not found: E0191

error: 2 unexpected errors found, 1 expected errors not found

error: /build/src/test/compile-fail/unboxed-closure-sugar-wrong-trait.rs:15: unexpected "note": 'associated type `Output` not found'

error: 1 unexpected errors found, 0 expected errors not found

failures:
    [compile-fail] compile-fail/E0220.rs
    [compile-fail] compile-fail/unboxed-closure-sugar-wrong-trait.rs

test result: FAILED. 2443 passed; 2 failed; 12 ignored; 0 measured

/build/mk/tests.mk:769: recipe for target 'tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-cfail.ok' failed

make: *** [tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-cfail.ok] Error 101
```

You can run the compile-fail test suite to make sure you've fixed everything with:

```
python src/bootstrap/bootstrap.py --step check-cfail --stage 1
```

**Comment by chamoysvoice** [comment]
@jonathandturner This build is failing because E0191 is throwing an error right? E0191 should't be updated first? 

I can't find my mistake

**Comment by jonathandturner** [comment]
@chamoysvoice - have you tried updating with a `git pull`, building the compiler and trying one of those two errors by hand?

It's possible that another PR changed things since then, so you might have to update these tests to work with your fixes.

**Comment by chamoysvoice** [comment]
@jonathandturner E0191 #35396 is still failing the build, but is already merged to master, should I pull from master then?

**Comment by eddyb** [comment]
@jonathandturner NB: One needs to use `git pull --rebase` on a PR branch to avoid merge commits.

**Comment by jonathandturner** [comment]
@eddyb - updated

**Comment by chamoysvoice** [comment]
@jonathandturner  So, this need to be rebuilt and thats all right?

**Comment by jonathandturner** [comment]
@chamoysvoice - yes, your rebase should be on top of master.  That should let you pull in the new fixes that are causing the issue travis-ci is seeing.

**Pull request closed without merging**
