### PR TITLE
Edit docs on consistency of `PartialOrd` and `PartialEq`

### PR DESCRIPTION
**Pull request by pierwill**
Use ordered list to make the information about implementations more readable.

### CODE REVIEW

**Comment by pierwill** [comment]
Just a style suggestion. Feel free to close if it doesn't feel like an improvement. :)

**Comment by yaahc** [comment]
I think its a welcome improvement and significantly reduces how noisy it looks. Thank you!

@bors r+ rollup

**Comment by Dylan-DPC** [comment]
Personally i like the idea but i feel it could be more confusing as people need to look up the numbers after reading the comment so i'm not sure there's much gain in this.

**Comment by yaahc** [comment]
> Personally i like the idea but i feel it could be more confusing as people need to look up the numbers after reading the comment so i'm not sure there's much gain in this.

noted. cc @rust-lang/libs-api to see if anyone else has strong feelings for or against this change.

**Pull request merged**
