### PR TITLE
Register new snapshots (270a677)

### PR DESCRIPTION
**Pull request by Manishearth**
Needed so that #21824 can land

### CODE REVIEW

**Comment by Manishearth** [comment]
I was unable to get a bitrig snapshot, it seems like the bitrig build is broken.


```
checking whether GCC or Clang is our host compiler... clang
checking build system type... Invalid configuration `x86_64-unknown-bitrig': system `bitrig' not recognized
configure: error: /bin/sh /home/builder/rust-buildbot/slave/snap3-bitrig-64/build/src/llvm/autoconf/config.sub x86_64-unknown-bitrig failed
```

What should I do in this case? Wait for it to be fixed, or land this directly?

cc @dhuseby

**Comment by Manishearth** [comment]
(Also, I haven't yet tested this locally -- the build is ongoing -- PRd  so that I can get Dave's input)

**Comment by Manishearth** [comment]
This passes `make check-stage2` (and stage1)

**Comment by semarie** [comment]
@dhuseby I think you hit a parsing problem in ksh (`/bin/sh`). see http://marc.info/?l=openbsd-bugs&m=142571265625168&w=2

the configure isn't well interperted by the shell.

it is #22474 that spot the problem.

**Comment by dhuseby** [comment]
I determined that the configure was barfing part way, but didn't have the time to figure out the fix.  thanks for the info, it's late sunday here in PST so i'll take a crack at it tomorrow.  i have a build slave set up, i just need to get the configure to work and the snapshots should start rolling in.

**Comment by dhuseby** [comment]
@Manishearth 

"configure: error: /bin/sh /home/builder/rust-buildbot/slave/snap3-bitrig-64/build/src/llvm/autoconf/config.sub x86_64-unknown-bitrig failed"

that looks like you don't have all of the patches.

**Comment by dhuseby** [comment]
I can manually build a snapshot for the new set and upload it while working on fixing the configure issue.

**Comment by semarie** [comment]
@dhuseby the problem is an invalid parse of `configure` by `/bin/sh` (as previously said). A quick correction is to change the comment about pandoc to remove the quote, or move the comment out of `$(...)`.

**Comment by dhuseby** [comment]
k, thanks

**Comment by dhuseby** [comment]
@alexcrichton I just manually built the latest bitrig snapshot while we sort out the buildbot issues: https://github.com/dhuseby/rust-cross-bitrig/blob/master/snapshots/rust-stage0-2015-03-07-270a677-bitrig-x86_64-4b2f11a96b1b5b3782d74bda707aca33bc179880.tar.bz2

will you upload that so i can patch up the src/snapshots.txt file?

**Comment by alexcrichton** [comment]
I've uploaded the snapshot, thanks for making one!

**Pull request merged**
