### PR TITLE
Update rustc-guide

### PR DESCRIPTION
**Pull request by JohnTitor**
r? @ghost

CC: @rust-lang/wg-learning

### CODE REVIEW

**Comment by JohnTitor** [comment]
This is submodule-only.
@bors r+ rollup=never

**Comment by JohnTitor** [comment]
Needs more link fix, out of the queue for now.
@bors r-

**Comment by JohnTitor** [comment]
Okay, it should be fine...
@bors r+

**Comment by tmandry** [comment]
@bors retry rolled up

IMO this shouldn't be rollup=never, since it seems low-risk once it's passing smoke tests.

**Comment by mark-i-m** [comment]
@tmandry We did this in the past, but spurious failures tended to cause rollup failures, so we adopted a policy of not rolling up rustc-guide update.

This is part of the reason why WG-learning makes its own PRs to update the guide, rather than ehuss doing it with their regular round of book/doc updates.

**Comment by tmandry** [comment]
Okay, good to know. Can you elaborate on what kind of spurious failures tend to happen?

**Comment by JohnTitor** [comment]
@tmandry rustc-guide checks links on CI but some links cause spurious failures like not found, temporarily unavailable, etc. See also previous PR: https://github.com/rust-lang/rust/pull/66161

**Comment by mark-i-m** [comment]
Yes, or some link breaks over night while the PR is in the queue, as happened at the top of this PR.

**Comment by tmandry** [comment]
Got it, thanks.

I know this isn't really the place for this discussion, but it seems reasonable to me to leave the link checks for smoke tests and not put those in CI.

**Comment by mark-i-m** [comment]
Not sure what others think, but I'm open to suggestions. The main thing is that it is helpful for rustc-guide to be tracked by toolstate.

**Pull request merged**
