### PR TITLE
Emit `@llvm.lifetime.end` for moved arguments passed indirectly

### PR DESCRIPTION
**Pull request by erikdesjardins**
This results in code like:
```rust
fn array_dead_store(mut x: [u8; 1234]) {
    x[0] = 42;
}
```

Getting compiled to:
```ll
define void @array_dead_store([1234 x i8]* %x) {
  %0 = getelementptr inbounds [1234 x i8], [1234 x i8]* %x, i64 0, i64 0
  store i8 42, i8* %0 ; this store can be dropped
  tail call void @llvm.lifetime.end.p0i8(i64 1234, i8* nonnull %0)
  ret void
}
```
...which allows LLVM to drop the dead store.

Without the lifetime marker, `%x` is just a pointer argument, so LLVM
does not know that it cannot be used after the function returns.

Fixes (partially) #96497

r? @nikic

### CODE REVIEW

**Comment by erikdesjardins** [comment]
Hmm, not reproducible locally, wonder if it's a miscompile

@rustbot author

**Review by nikic — COMMENTED** [review]
Ideally this would be solved with an additional attribute on the LLVM side, because inserting lifetime.end only covers the normal return paths, but not the unwind paths. But adding lifetime.end does seem like a reasonable intermediate solution.

Those test failures are quite concerning...

**Comment by nikic** [comment]
To double check, for `Copy` args passed indirectly rustc will emit a memcpy *before* the call, right?

@bors try @rust-timer queue

**Comment by nikic** [comment]
> After inlining the llvm.lifetime.end intrinsic will have much stronger unintended semantics. When applied to a stack object it will incorrectly shorten the object's lifetime. And in the case where stack object didn't use any lifetime intrinsics, adding llvm.lifetime.end will make object dead everywhere.

From a cursory look, I believe we do emit lifetime.start for these stack objects. We'll have two lifetime.end intrinsics afterwards, which is weird, but not illegal. (Though maybe the lifetime.start emission isn't reliable -- you are definitely right that we should not emit lifetime.end if there is no lifetime.start before the call.)

**Comment by tmiasko** [comment]
> From a cursory look, I believe we do emit lifetime.start for these stack objects. We'll have two lifetime.end intrinsics afterwards, which is weird, but not illegal. (Though maybe the lifetime.start emission isn't reliable -- you are definitely right that we should not emit lifetime.end if there is no lifetime.start before the call.)

There is a number of situations under which we don't use lifetime intrisics. To give one example: calls using const operands `const A: [u32; 1024] = [0; 1024]; f(A);`. Adding intrinsics here introduces undefined behaviour from the perspective of LLVM IR after inlining.

This also brings more fundamental question of MIR semantics. In call terminators we pass `Operand::Move` arguments without making an intermediate copy, so this change affects the lifetime of such objects. The exact semantics is an open question, but I would currently assume that the value after the call is undefined in MIR, but the place still has storage and can be used again. The proposed code generation is inconsistent with that interpretation.

**Comment by erikdesjardins** [comment]
> To double check, for Copy args passed indirectly rustc will emit a memcpy before the call, right?

Yes: https://godbolt.org/z/Yz8en8684

> we should not emit lifetime.end if there is no lifetime.start before the call

It wasn't clear to me from the langref if `lifetime.end` with no `lifetime.start` kills the alloca everywhere. Alive2 doesn't seem to think so (https://alive2.llvm.org/ce/z/EmHI9c), but it might not implement the same semantics as LLVM itself.

If it is the case that this is only safe if (at least) there is a `lifetime.start` before the call, then I this is probably too sketchy to pursue (it would be hard to guarantee that nobody adds any codegen without missing lifetime markers), and we should add an attribute upstream instead.

Potentially, we could also (ab)use `lifetime.start` instead of using `lifetime.end`, since it has the same effect of poisoning the existing content of the object. Not sure if I would actually want to do that though...

> There is a number of situations under which we don't use lifetime intrisics. To give one example: calls using const operands `const A: [u32; 1024] = [0; 1024]; f(A);`.

Huh. Independently of this change, seems like we should be using lifetime intrinsics there?

I guess the reason we don't currently is that there's nowhere to put `StorageDead`/`StorageLive` for that in MIR, and we don't add it during codegen.

(Yep, it wastes stack space like you'd expect: https://godbolt.org/z/Kn7b7nTnd)

> This also brings more fundamental question of MIR semantics. In call terminators we pass Operand::Move arguments without making an intermediate copy, so this change affects the lifetime of such objects. The exact semantics is an open question, but I would currently assume that the value after the call is undefined in MIR, but the place still has storage and can be used again. The proposed code generation is inconsistent with that interpretation.

Yeah, this seems like a problem. Again (ab)using `lifetime.start` would avoid that, but...

**Comment by tmiasko** [comment]
> It wasn't clear to me from the langref if `lifetime.end` with no `lifetime.start` kills the alloca everywhere. Alive2 doesn't seem to think so (https://alive2.llvm.org/ce/z/EmHI9c), but it might not implement the same semantics as LLVM itself.

Ah, the reference was updated last year to clarify that "If the returned pointer is used by llvm.lifetime.start the returned object is initially dead". In that case it would be fine.

The stack coloring itself considers a slot "interesting" if it has any sort of lifetime marker (either start or end), but slots with empty live ranges are not merged, so this might be consistent with the reference.
 
> Potentially, we could also (ab)use `lifetime.start` instead of using `lifetime.end`, since it has the same effect of poisoning the existing content of the object. Not sure if I would actually want to do that though...

It would seem that also adding lifetime.start would solve one problem but create another in the case there are no markers.

**Pull request closed without merging**
