### PR TITLE
Standard library support for riscv64gc-unknown-linux-gnu

### PR DESCRIPTION
**Pull request by msizanoen1**
Add std support for RISC-V 64-bit GNU/Linux and update libc for RISC-V support.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ rollup

👍

**Comment by msizanoen1** [comment]
After this would be builds on CI: https://github.com/rust-lang/rust/compare/master...msizanoen1:riscv-ci
It is put on a separate builder so we can easily add it as a rustc host later.

**Comment by andreas-schwab** [comment]
I'm currently bootstrapping rust-1.39 with the backported riscv64 support on openSUSE Tumbleweed.

https://build.opensuse.org/package/show/home:Andreas_Schwab:riscv:llvm/rust

**Comment by Centril** [comment]
@bors rollup=never p=1

This may have caused several rollups to fail.
In the future, please do not rollup libc changes.

**Comment by andreas-schwab** [comment]
I haven't been able to build a native rust package so far.  The rust compiler is prone to crashes.

**Comment by msizanoen1** [comment]
Other PGO-related test still succeed, and the failing test does not reproduce under my machine, so may I temporarily disable the test for now?

**Comment by msizanoen1** [comment]
I tested this using the CI docker files and the pgo-branch-weights test still pass. Maybe somebody from infra could clear the docker caches?

**Comment by alexcrichton** [comment]
Are you running tests on macOS? That's the failing platform, and with a `libc` update in this PR it may be the case that a constant or something changed in `libc` which broke only macOS

**Comment by msizanoen1** [comment]
I am talking about this test failure: https://github.com/rust-lang/rust/pull/67132#issuecomment-562906524
It does not reproduce even when using docker.
The macOS failure is unrelated.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by msizanoen1** [comment]
As it does not reproduce when running in Docker locally so I think clearing the docker cache should fix it.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by msizanoen1** [comment]
Wait - I think I found the reason for the PGO failure: https://llvm.org/docs/LangRef.html#attribute-groups
It is not put inline but in another attribute group.
-------- Original Message --------

**Comment by msizanoen1** [comment]
Wait - it seems like the !prof is a metadata, not an attribute: https://llvm.org/docs/LangRef.html#metadata
So it looks like we still have to flush docker cache.
-------- Original Message --------

**Comment by msizanoen1** [comment]
The test only fails on Linux:
```
macOS i686-apple/25_Run build.txt:2019-12-08T02:11:09.2374160Z test [run-make] run-make-fulldeps/pgo-branch-weights ... [33mignored(B[m
macOS x86_64-apple/25_Run build.txt:2019-12-08T02:09:13.2506760Z test [run-make] run-make-fulldeps/pgo-branch-weights ... [32mok(B[m
Linux x86_64-gnu-llvm-7/25_Run build.txt:2019-12-08T02:15:32.9167453Z test [run-make] run-make-fulldeps/pgo-branch-weights ... [33mignored(B[m
Linux x86_64-gnu-distcheck/25_Run build.txt:2019-12-08T02:24:42.5236244Z test [run-make] run-make-fulldeps/pgo-branch-weights ... [33mignored(B[m
Linux x86_64-gnu/25_Run build.txt:2019-12-08T02:28:08.3023772Z test [run-make] run-make-fulldeps/pgo-branch-weights ... [31mFAILED(B[m
```
So it should be OK to temporarily ignore it on Linux.

**Comment by msizanoen1** [comment]
I cannot reproduce it even using docker caches from rust-lang-ci-sccache2. It's probably other caches.

**Comment by msizanoen1** [comment]
Maybe temporarily ignore it until the cause is found?

**Comment by msizanoen1** [comment]
This is the result of running the x86_64-gnu container on this PR: https://dev.azure.com/rust-lang/rust/_build/results?buildId=16159&view=results (I copy pasted the x86_64-gnu Dockerfile into x86_64-gnu-llvm-7 and removed the commit after it finishes running).
The test succeed with 0 cache misses.
It's probably not cache problem.

**Comment by msizanoen1** [comment]
Centril's comment says that this PR causes multiple rollups to fail and it is the same test failure (pgo-branch-weights). However it seems that there should not be any reason for the test to fail.

**Comment by msizanoen1** [comment]
Updating libc is already done in #67594 so this is only porting and updating LLVM to include https://github.com/rust-lang/llvm-project/pull/29 and possibly also https://github.com/alexcrichton/cc-rs/pull/461#issuecomment-569382658

**Comment by msizanoen1** [comment]
@alexcrichton Can you retry merging?

**Comment by mati865** [comment]
Previous CI error was spurious: https://github.com/rust-lang/rust/issues/67746

**Comment by msizanoen1** [comment]
@alexcrichton Can you try merging it?

**Pull request merged**
