### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #70817 (Add core::task::ready! macro)
 - #73762 (Document the trait keyword)
 - #74021 (impl Index<RangeFrom> for CStr)
 - #74071 (rustc_metadata: Make crate loading fully speculative)
 - #74445 (add test for #62878)
 - #74459 (Make unreachable_unchecked a const fn)
 - #74478 (Revert "Use an UTF-8 locale for the linker.")

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
This was a big [perf win](https://perf.rust-lang.org/compare.html?start=1fa54ad9680cc82e7301f8ed4e9b7402dfd6ce0e&end=0701419e96d94e5493c7ebfcecb66511ab0aa778&stat=instructions:u). Presumably it was #74478 that was responsible. 

*However*, the improvements here are smaller than those seen on perf CI runs in that PR. (E.g. the best improvement dropped from -42% to -33%.) So it's possible that one of the other PRs in this this rollup caused a significant regression. But it's difficult to say for certain, and I don't know which other PR may be the cause. Argh.

**Comment by Mark-Simulacrum** [comment]
The [perf results](https://perf.rust-lang.org/compare.html?start=1fa54ad9680cc82e7301f8ed4e9b7402dfd6ce0e&end=a2bdac26d4f4c69c6c065d86225b764ba750819b) for #74478 landing in this PR (i.e., basically an up to date run) indicates that it essentially accounts for all of the benefits of this PR.

Presumably some of the offsets from the original try run were offset by some other changes -- though it is unclear exactly how that could be the case. OTOH, this landed atop https://github.com/rust-lang/rust/commit/1fa54ad9680cc82e7301f8ed4e9b7402dfd6ce0e which was a known linker regression (based on perf runs elsewhere). So that may explain some of the offsets in terms of performance we managed to win back.

I consider this PR to be fully understood from a perf perspective.

**Pull request merged**
