### PR TITLE
Update rustc-guide

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @ehuss 

cc @rust-lang/wg-learning

### CODE REVIEW

**Comment by JohnTitor** [comment]
Would you include rust-lang/rustc-guide#549?
@bors r-

**Comment by mark-i-m** [comment]
@JohnTitor Done :)

**Comment by JohnTitor** [comment]
Thanks!
@bors r+

**Comment by mark-i-m** [comment]
Failure looks spurious to me. All except one builder passed, and the one that failed has nothing to do with the guide...

**Comment by JohnTitor** [comment]
It's a known/filed issue #67746
@bors retry

**Pull request merged**
