### PR TITLE
Bump to 1.78 bootstrap compiler

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
https://forge.rust-lang.org/release/process.html#master-bootstrap-update-t-2-day-tuesday

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Filed https://github.com/rust-lang/rust/issues/122758 and pushed what seems to be a workaround for that bug, we'll see if CI agrees.

**Comment by Mark-Simulacrum** [comment]
Alright, looks like CI is happy, so this is probably ready for review.

**Comment by albertlarsan68** [comment]
Am I supposed to review, or is it waiting on someone else?

**Comment by Mark-Simulacrum** [comment]
Sure, if you want to. This PR (well, this kind of PR every cycle) usually touches things all over the place but is pretty mechanical, so anyone can review it from my perspective.

**Comment by albertlarsan68** [comment]
A bunch of "on bootstrap bump, remove unsafe block" have been missed, it seem.

**Comment by Mark-Simulacrum** [comment]
Fixed. Those really should have some mention of cfg(bootstrap) so that they're mechanically findable :/

**Comment by albertlarsan68** [comment]
They have, and the bootstrap cfg has been correctly changed

**Comment by albertlarsan68** [comment]
Sorry, first time reviewing bump PR!

@bors r+ rollup=never
I guess?

**Comment by onur-ozkan** [comment]
Did we somehow miss something in this bump? Currently stage0 rustc is broken (see #122913) due to not being able to find the LLVM dylib.

**Comment by Mark-Simulacrum** [comment]
My guess is that is a pre-existing bug that would be exposed by any bump, not something missed in this particular case.

**Comment by Nilstrieb** [comment]
Yeah, this now ships the new libLLVM with the linker script. Something probably forgot to copy the stuff.

**Pull request merged**
