### PR TITLE
Improve codegen of String::retain method

### PR DESCRIPTION
**Pull request by Urgau**
This pull-request improve the codegen of the `String::retain` method.

Using `unwrap_unchecked` helps the optimizer to not generate a panicking path that will never be taken for valid UTF-8 like string.

Using `encode_utf8` saves us from an expensive call to `memcpy`, as the optimizer is unable to realize that `ch_len <= 4` and so can generate much better assembly code.

https://rust.godbolt.org/z/z73ohenfc

### CODE REVIEW

**Comment by the8472** [comment]
Wouldn't it be better to optimize for runs of retained/dropped chars so larger chunks could be memcopied? At least I assume real-world workloads rarely discard every second character.

**Comment by Urgau** [comment]
> Wouldn't it be better to optimize for runs of retained/dropped chars so larger chunks could be memcopied? At least I assume real-world workloads rarely discard every second character.

Maybe, but the cost of doing a `memcpy` is pretty high if `N` (number of bytes) is low and because the average length of words is: ~4.5 letters in engligh, ~4.84 letters in french and ~4.96 letters in spanish, I'm not sure that it would be good to do it unconditionally, at least not without a fast path for `N` < 32 (or 16 depending on the assembly generated).

http://www.cs.trincoll.edu/~crypto/resources/LetFreq.html

**Comment by thomcc** [comment]
I'll take over review for this since it's been a while since the last update.

r? @thomcc

Have you taken any benchmarks?

**Comment by Urgau** [comment]
> I'll take over review for this since it's been a while since the last update.

Thanks. *If you feel up to it you can also take https://github.com/rust-lang/rust/pull/94647 which hasn't had any activity at all. 😁*

> Have you taken any benchmarks?

Yes, I run them on `armv7-unknown-linux-gnueabihf` where `despace` is just `.retain(|ch| ch != ' ')` (and the number is the number of character in the input string):

```text
running 8 tests
test despace_25        ... bench:          17 ns/iter (+/- 0)
test despace_250       ... bench:          17 ns/iter (+/- 0)
test despace_5         ... bench:          17 ns/iter (+/- 0)
test despace_emoji     ... bench:          18 ns/iter (+/- 0)
test despace_std_25    ... bench:         374 ns/iter (+/- 2)
test despace_std_250   ... bench:       2,829 ns/iter (+/- 24)
test despace_std_5     ... bench:          87 ns/iter (+/- 0)
test despace_std_emoji ... bench:         168 ns/iter (+/- 1)
```

**Comment by the8472** [comment]
Previously it scaled with character counts and now it's flat, is that expected or do the benchmarks get optimized away entirely?

**Review by thomcc — APPROVED** [review]
It's a bit surprising to me that this would make much of a perf difference, but it would also surprise me that it would *hurt*, there are benchmark numbers, and the logic that this avoids a memcpy call for something that is always <= 4 bytes all makes sense.

This also has the benefit of improving the safety documentation of these blocks, and actually reducing the amount of unsafe needed as well (sort of), so it seems like a positive change all around.

**Comment by thomcc** [comment]
> Thanks. If you feel up to it you can also take https://github.com/rust-lang/rust/pull/94647 which hasn't had any activity at all. 😁

Sure.

> Previously it scaled with character counts and now it's flat, is that expected or do the benchmarks get optimized away entirely?

This is a fair point. Hm. I actually think this is a reasonable change regardless, but it's worth seeing more accurate benchmark numbers.

@bors r-

**Comment by Urgau** [comment]
> > Thanks. If you feel up to it you can also take #94647 which hasn't had any activity at all. grin
> 
> ~Sure.~ Nevermind, it's an API change, I didn't notice this.

Sorry.

> > Previously it scaled with character counts and now it's flat, is that expected or do the benchmarks get optimized away entirely?
> 
> This is a fair point. Hm. I actually think this is a reasonable change regardless, but it's worth seeing more accurate benchmark numbers.

Here is the same benchmark except that now the `String` always reallocated a part of the benchmark (my previous logic must have been wrong somewhat):

``text
running 8 tests
test despace_25        ... bench:         732 ns/iter (+/- 5)
test despace_250       ... bench:       4,020 ns/iter (+/- 25)
test despace_5         ... bench:         306 ns/iter (+/- 5)
test despace_emoji     ... bench:         507 ns/iter (+/- 3)
test despace_std_25    ... bench:       1,546 ns/iter (+/- 35)
test despace_std_250   ... bench:      10,296 ns/iter (+/- 598)
test despace_std_5     ... bench:         432 ns/iter (+/- 4)
test despace_std_emoji ... bench:         783 ns/iter (+/- 9)
```

**Comment by thomcc** [comment]
> Sorry.

You're fine. The issue should have more traction now anyway.

> Here is the same benchmark except that now the String always reallocated a part of the benchmark (my previous logic must have been wrong somewhat): ... \<snip\>

This looks reasonable to me, and since I was already inclined to accept the PR,

@bors r+

**Pull request merged**
