### PR TITLE
Remove region variable leaks from higher_ranked_sub().

### LINKED ISSUE #28279: Variance issue with higher kinded lifetimes
```rust
fn test() -> *mut for<'a> Fn(&'a usize) { // change to *const and it'll work
    if let Some(_) = Some(1) { // not sure why I have to do this
        loop{}
    } else {
        loop{}
    }
}

fn main() {}
```

```
<anon>:2:5: 6:6 error: cannot infer an appropriate lifetime for lifetime parameter 'a in generic type due to conflicting requirements
<anon>:2     if let Some(_) = Some(1) { // not sure why I have to do this
<anon>:3         loop{}
<anon>:4     } else {
<anon>:5         loop{}
<anon>:6     }
note: in expansion of if let expansion
<anon>:2:5: 6:6 note: expansion site
note: first, the lifetime cannot outlive lifetime ReSkolemized(0, BrNamed(0:7, 'a(61)))...
<anon>:2:5: 6:6 note: ...so that types are compatible (expected `for<'a> core::ops::Fn(&'a usize) + 'static`, found `core::ops::Fn(&usize) + 'static`)
<anon>:2     if let Some(_) = Some(1) { // not sure why I have to do this
<anon>:3         loop{}
<anon>:4     } else {
<anon>:5         loop{}
<anon>:6     }
note: in expansion of if let expansion
<anon>:2:5: 6:6 note: expansion site
<anon>:2:5: 6:6 note: but, the lifetime must be valid for the if let at 2:4...
<anon>:2     if let Some(_) = Some(1) { // not sure why I have to do this
<anon>:3         loop{}
<anon>:4     } else {
<anon>:5         loop{}
<anon>:6     }
note: in expansion of if let expansion
<anon>:2:5: 6:6 note: expansion site
<anon>:2:5: 6:6 note: ...so type `*mut core::ops::Fn(&usize)` of expression is valid during the expression
<anon>:2     if let Some(_) = Some(1) { // not sure why I have to do this
<anon>:3         loop{}
<anon>:4     } else {
<anon>:5         loop{}
<anon>:6     }
note: in expansion of if let expansion
<anon>:2:5: 6:6 note: expansion site
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: !ty.needs_infer()', ../src/librustc_typeck/lib.rs:155

```

### PR DESCRIPTION
**Pull request by ebfull**
Fixes #28279.

Currently

`common_supertype(*mut for<'a> Fn(&'a usize), *mut for<'a> Fn(&'a usize) + 'static)`

equals `*mut Fn(&usize)` which seems to be caused by `higher_ranked_sub()` allowing region variables to escape the comparison. This prevents inference from working properly with stuff like `Rc<Fn(&T)>`.

r? @nikomatsakis

### CODE REVIEW

**Comment by ebfull** [comment]
This could be better with tests to make sure that the tainted region checks are sound, but I can't come up with any.

**Comment by nikomatsakis** [comment]
Actually, the return value from `sub` (and `equate`) ought to be ignored, as described...well, somewhere or other. I think the bug is in the `relate_with_variance` for `lub` etc. That said, it is probably wrong to return `result` here. It would be better to return `a` (which is also consistent with what the other `sub` cases do). That would probably fix `lub`, fwiw, but it still seems like it's wrong to return the result from `equate`. I guess it'd be better to say that `sub` always returns a subtype (i.e., `a`), if it does not yield an error. I don't think that introduces any particular difficulties to do. Similarly, `equate` can be defined to return `a` something that is equal.

**Comment by ebfull** [comment]
Nice, that makes much more sense. I've rebased with a much more conservative fix that covers most of the bases. If you think I should go through and return `a` from all of the pertinent routines (such as higher_ranked_sub etc.) I can do that too.

**Comment by nikomatsakis** [comment]
@ebfull it seems like the policy is a bit unclear; I think at least a comment on Sub and Equate indicating that they are supposed to:

- make `a` a subtype of (resp. equal to) `b`
- return `a`

would make the policy clear.

**Comment by brson** [comment]
I've started a crater run.

**Comment by nikomatsakis** [comment]
@ebfull ah, I see you pushed a commit, sorry, I didn't notice (GH doesn't notify me). This looks good to me. @brson, is there any particular reason you started a crater run for this branch? (I wouldn't expect regressions from it in particular...?)

**Comment by ebfull** [comment]
@nikomatsakis I asked @brson if it would be a good idea, in case it fixes soundness holes we weren't aware of. I apologize if this was an unnecessary use of crater resources.

**Comment by nikomatsakis** [comment]
@ebfull oh not to worry, I just wondered if there was some known interaction

**Comment by brson** [comment]
Oh, shoot, sorry I let this crater run slip. It's still in progress.

**Comment by brson** [comment]
I've been running into problems with crater. Still trying to get this through.

**Comment by brson** [comment]
@ebfull [Crater found no problems](https://gist.github.com/brson/4a8152396c0b8020d4ef)

**Pull request merged**
