### PR TITLE
[crater experiment] do the opposite of what zip side-effect documentation currently guarantees

### PR DESCRIPTION
**Pull request by the8472**
Improved crater experiment to elucidate the possibility of completely removing the guarantee that was added in #52279, suggested by @steffahn in https://github.com/rust-lang/rust/pull/83791#issuecomment-892791462

That it was already used in linkedlist doesn't bode well. 😢

r? @ghost

### CODE REVIEW

**Comment by the8472** [comment]
Preparing for a crater run.

@bors try

**Comment by the8472** [comment]
@craterbot run mode=build-and-test

**Comment by the8472** [comment]
@craterbot retry

**Comment by Mark-Simulacrum** [comment]
@craterbot retry-report

**Comment by Mark-Simulacrum** [comment]
Results will still be here if/when desired, but closing the PR itself to get it out of our queue.

**Pull request closed without merging**
