### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by aarikpokras**
Fixed some grammar in README.md

### CODE REVIEW

**Comment by saethlin** [comment]
Nice find! I agree the grammar you've identified needs some improvement, but I'm not keen on just changing to "integratable".

**Comment by saethlin** [comment]
Sorry about that. Finger slipped.

I can't find "integratable" in major dictionaries, and it's certainly not in my phone's auto complete. Can you try "integrable" or "integrated"? The latter is technically a different tense I suppose but I think it serves the same purpose. English is strange.

**Comment by aarikpokras** [comment]
Sorry about that. My computer somehow recognized that as a word. I'll try to find another one. Sorry!

**Comment by aarikpokras** [comment]
Hi,
I used "integrated". Thank you!

**Comment by saethlin** [comment]
> Sorry about that. My computer somehow recognized that as a word. I'll try to find another one. Sorry!

No need to apologize :) Natural languages evolve in real time so it's quite possible this is just uncommon right now.

We try to keep PRs to just 1 commit for small changes like this, because bors doesn't have its own squashing. I'll fixup the history for you, but normally this operation is known as a squash if you want to read about how to do it yourself.

**Pull request merged**
