### PR TITLE
Update LLVM to include 4 backported commits by @majnemer.

### PR DESCRIPTION
**Pull request by eddyb**
Partial fix for rust-lang/rust#35662, should help at least loops on small arrays.

Nominated for backporting into the new beta (not the one that's being released as stable this week).

r? @alexcrichton

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Regarding beta-nomination: decided to wait until we have a better handle on how much of a fix this is and whether a better, more complete fix is coming.

**Comment by nikomatsakis** [comment]
Update: waiting on the fate of #36124, since this backport doesn't seem worth it without that (and maybe not at all)

**Comment by eddyb** [comment]
@nikomatsakis Moved the nomination to #36124.

**Pull request merged**
