### PR TITLE
Update to LLVM 12.0.1

### PR DESCRIPTION
**Pull request by nikic**
LLVM 12.0.1 has been released, rebase our fork on top of it.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me unless this is waiting for something

**Comment by nikic** [comment]
Nope, this should be a straightforward update.

@bors r=Mark-Simulacrum

**Comment by nikic** [comment]
@retry "post checkout the source code" failed on test-various. Assuming that's still spurious...

**Pull request merged**
