### PR TITLE
Error message for E0307 is weird #26485

### PR DESCRIPTION
**Pull request by jawline**
Print the error message and then what is expected by the repeat count so the output makes more sense when there is an error in the const expression

### CODE REVIEW

**Comment by pnkfelix** [comment]
Our standard convention for our error messages is to say "expected XXX, found YYY", but your PR is in this case emitting "found YYY, expected XXX"

I am not 100% clear on what your objection is to the error message as it was originally formed.

 * Is it that you find the "expected XXX, found YYY" format itself unclear?
 * Or is there something specific about this error case that is making this particular message hard to understand? 
   * If so, maybe we can tailor it in some way. E.g. would "expected positive integer, found variable (for repeat count)" be clearer?

Also, did you run `make check` with your patch in place?  I would expect a number of our test cases would need to be updated.

**Comment by jawline** [comment]
Hi,

Sorry I wasn't sure about the convention.

The issue I have with the print out is that the compiler is printing the details of an error in the found which can lead to strange error messages like

a.rs:8:17: 8:38 error: expected constant integer for repeat count, but unsupported constant expr [E0307]

or any of the possible errors in const_eval.rs ConstEvalError::description

The error text just seems a little bit incorrect grammar wise this way around - but if it goes against the convention perhaps it should just be left this way around.

**Comment by jawline** [comment]
Haven't run make check - defiantly should. Woops

**Comment by pnkfelix** [comment]
@jawline maybe simplest to try to get the output to look like "error: expected constant integer for repeat count, but *found* unsupported constant expr" instead?

alternatively, we could try to just emit "unsupported const expr" alone (without saying anything about "expected constant integer") for just that case, and leave the other cases alone?

**Comment by jawline** [comment]
Sure - I was trying to avoid logic just for this case, but I think adding the 'found' when the error kind is MiscCatchAll might be best.

**Comment by jawline** [comment]
Modified so the error now reads

src/lib.rs:20:15: 20:23 help: run `rustc --explain E0306` to see a detailed explanation
src/lib.rs:21:14: 21:35 error: expected constant integer for repeat count, but found unsupported constant expr [E0307]
src/lib.rs:21 	let q = [5; mem::size_of::<i32>()];

only for unsupport constant expr 

make check reports
summary of 45 test runs: 9078 passed; 0 failed; 89 ignored; 0 measured

**Comment by jawline** [comment]
Not entirely sure why Travis is failing in LLVM - haven't touched it. Builds on my machine

**Comment by Gankro** [comment]
You accidentally commited submodule changes.

**Comment by huonw** [comment]
This seems to include some submodule changes, which aren't appropriate.

**Comment by apasel422** [comment]
One of these commits should probably have "closes #26485" in it (they could all be squashed, too).

**Comment by Gankro** [comment]
@pnkfelix presumably this should be squashed?

**Comment by pnkfelix** [comment]
@Gankro yeah you're right; I was trying to avoid spending even more time on this than I already had (with back-and-forth regarding squashing and re-r-plusing) but obviously now I've lost more time than I saved.

**Comment by pnkfelix** [comment]
@jawline please squash.

(r=me after said squashing...)

**Comment by jawline** [comment]
Hi guys,Sorry I missed the comment about squashing before.

 I'm having trouble squashing because of the merge conflict solved after. rebase -p -i doesn't seem to work properly because of it, any idea what I need to do to squash it without screwing up the history in this case?

**Comment by apasel422** [comment]
@jawline With your original commits, you should rebase onto master, _then_ squash them.

**Comment by jawline** [comment]
@pnkfelix Hi, Sorry for the delay. Squashed most of the commits and added closes

**Comment by apasel422** [comment]
@jawline It should be possible to get this down to one commit with no merges.

**Comment by pnkfelix** [comment]
@jawline yes, please rebase to a single commit as requested by @apasel422 (if you need assistance, feel free to ping me on irc and I can try to help)

**Comment by jawline** [comment]
@pnkfelix Sorry I was a bit of an idiot and missed those. done

**Pull request merged**
