### PR TITLE
Fix extended bootstrap issues with OpenSSL on NetBSD build hosts

### PR DESCRIPTION
**Pull request by jakllsch**

### CODE REVIEW

**Comment by kennytm** [comment]
@bors retry #40474 or #44221 

`check x86_64-apple-darwin` failed to download the stage0 compiler. (2nd retry.)

```
Attempting with retry: make prepare
[00:03:57] downloading https://static.rust-lang.org/dist/2017-08-29/rust-std-beta-x86_64-apple-darwin.tar.gz


No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by kennytm** [comment]
@bors retry p=-1 #44221

`check i686-apple-darwin` failed. Reducing priority at 3rd retry to give other PRs a try.

<details>

```
[00:02:08] Attempting with retry: sh -c git submodule deinit -f src/libcompiler_builtins &&         git submodule update --init --recursive --reference /Users/travis/rustsrc/src/src/libcompiler_builtins src/libcompiler_builtins
[00:02:08] Cleared directory 'src/libcompiler_builtins'
[00:02:08] Submodule 'src/libcompiler_builtins' (https://github.com/rust-lang-nursery/compiler-builtins) registered for path 'src/libcompiler_builtins'
[00:02:08] Cloning into '/Users/travis/build/rust-lang/rust/src/libcompiler_builtins'...
[00:02:09] Submodule path 'src/libcompiler_builtins': checked out '6b9281d2b2f0ebb94838814b1e8ace2de4b7035b'
[00:02:09] Submodule 'compiler-rt/compiler-rt-cdylib/compiler-rt' (https://github.com/rust-lang/compiler-rt) registered for path 'src/libcompiler_builtins/compiler-rt'
[00:02:09] Cloning into '/Users/travis/build/rust-lang/rust/src/libcompiler_builtins/compiler-rt'...
[00:02:10] warning: no common commits
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

</details>

**Comment by alexcrichton** [comment]
er

@bors: rollup

**Comment by arielb1** [comment]
This had just went out of queue. Pending a new review?

**Comment by aidanhs** [comment]
@bors r-

Caused a failure in the rollup I think:
```
[00:58:45] failed to execute command: "shasum" "-a" "256" "/checkout/obj/build/x86_64-unknown-linux-gnu/openssl/openssl-1.0.2k.tar.tmp"

[00:58:45] error: No such file or directory (os error 2)
```

**Comment by aidanhs** [comment]
Looks like `shasum` is from the perl package on ubuntu, whereas `sha256sum` is from coreutils.

**Comment by Mark-Simulacrum** [comment]
r=me when commits are squashed

**Comment by Mark-Simulacrum** [comment]
Merged in https://github.com/rust-lang/rust/pull/44936.

**Pull request closed without merging**
