### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by Manishearth**
We need the fix for https://github.com/rust-lang/cargo/issues/7427 in ASAP, it's breaking CI builds

r? @centril @alexcrichton

### CODE REVIEW

**Comment by Centril** [comment]
Seems to be the same as https://github.com/rust-lang/rust/pull/64774 ?

**Comment by alexcrichton** [comment]
Yes, this is the same as https://github.com/rust-lang/rust/pull/64774

**Comment by Manishearth** [comment]
lol i meant to do this earlier and didn't notice it had already happened in the meantime

**Pull request closed without merging**
