### PR TITLE
Fixes to librustdoc javascript (mostly search)

### PR DESCRIPTION
**Pull request by nagisa**

### CODE REVIEW

**Comment by nagisa** [comment]
This is very likely to conflict with some future version of #28725.

**Comment by nagisa** [comment]
Ready for merge.

**Comment by alexcrichton** [comment]
@bors: r+ f38bc2c45763f773c9373634dbbe58cc36bf8704

Thanks!

**Comment by steveklabnik** [comment]
lol whoops i added the plus out of habit

**Pull request merged**
