### PR TITLE
Rename environment variable for overriding rustc version

### PR DESCRIPTION
**Pull request by pierwill**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This will need an update to rustc-perf prior to landing which sets both the old and new env variable to avoid another period of noise.

**Comment by pierwill** [comment]
This is ready, @matthewjasper—unless there's more to do on the rustc-perf side, first.

**Comment by Mark-Simulacrum** [comment]
I want to take a closer look before moving ahead with this, but should be able to get to that shortly. It doesn't seem particularly urgent either, I suppose.

**Comment by Mark-Simulacrum** [comment]
So, I think this is okay, but I would like to see this patch expanded -- right now, there's a bunch of different places CFG_VERSION is read in the compiler, and instead I think we can add a single place that reads it -- probably in rustc_session (maybe rustc_data_structures; play it by ear as the root of the relevant crate tree).

That place would do the dispatch on the environment variable querying the version, and be used across all of the places we might read from it -- ideally, that makes the environment variable much more useful, since it's a blanket override to the rustc hash, rather than a partial solution.

I think that should be a relatively lightweight set of changes; can you make them in this PR?

**Comment by bjorn3** [comment]
rustc_span doesn't depend on rustc_session.

> That place would do the dispatch on the environment variable querying the version, and be used across all of the places we might read from it -- ideally, that makes the environment variable much more useful, since it's a blanket override to the rustc hash, rather than a partial solution.

I think rustc_metadata shouldn't allow overriding the rustc version. Unlike the use in rustc_span it doesn't affect performance in any way. It just changes a couple of bytes at the start of the .rmeta files.

**Comment by Mark-Simulacrum** [comment]
Ah, yeah, span is going to be a problem...

I guess it's true that not all of those places are in need of this override (or really benefit). Let's temporarily leave it then and we can reconsider if we need to change it again.

@bors r+

**Pull request merged**
