### PR TITLE
Remove `serialized_bitcode` from `LtoModuleCodegen`.

### PR DESCRIPTION
**Pull request by nnethercote**
It's unused.

r? @bjorn3

### CODE REVIEW

**Review by antoyo — APPROVED** [review]
LGTM

**Comment by bjorn3** [comment]
Are you sure this is safe to remove? It may be necessary to keep it around to avoid dangling references and thus UB. Can't check right now.

**Comment by lqd** [comment]
until bjorn can take a look at the non-gcc parts, or the question is answered, @bors r-

**Comment by GuillaumeGomez** [comment]
Went too fast. Thanks for the r-!

**Comment by nnethercote** [comment]
The field was added in https://github.com/rust-lang/rust/commit/ded38dbfc258f8e253ab61d1bca08b21efa2bf3d. There appears to be no discussion there about whether anything subtle is happening.

**Comment by nnethercote** [comment]
There is the unsafe `LtoModuleTranslation::optimize` function nearby, not sure if that's relevant.

**Comment by nnethercote** [comment]
@tmiasko: can you suggest a rewriting of the comment?

**Comment by nnethercote** [comment]
I updated with the sentence removed from the comment.

**Pull request merged**
