### PR TITLE
Small fix span

### LINKED ISSUE #9033: Improve span of `or_fun_call` lint
### Description

The lint message currently spans through the entire method chain expression:

```console
error: use of `unwrap_or` followed by a call to `new`
  --> $DIR/or_fun_call.rs:182:9
   |
LL | /         frames
LL | |             .iter()
LL | |             .map(|f: &String| f.to_lowercase())
LL | |             .reduce(|mut acc, f| {
...  |
LL | |             })
LL | |             .unwrap_or(String::new());
   | |_____________________________________^
```

It would be enough to just point to the `unwrap_or`.

_Originally posted by @flip1995 in https://github.com/rust-lang/rust/pull/98261#discussion_r903425629_

### Version

_No response_

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by alex-semenyuk**
Close [#9033](https://github.com/rust-lang/rust-clippy/issues/9033)

### CODE REVIEW

**Comment by xFrednet** [comment]
Hey @alex-semenyuk, thank you for the PR. Did you intend to create it in the `rust-clippy` repo? It's usually better if PRs only affecting Clippy are created there.

Also related to your changes, it seems like you've only commited a `.stderr` file without any changes to the lint implementation. Is this correct?

**Comment by alex-semenyuk** [comment]
Thanks, @[xFrednet](https://github.com/xFrednet)

> Also related to your changes, it seems like you've only commited a .stderr file without any changes to the lint implementation. Is this correct?

Yes, here mentioned that improvement https://github.com/rust-lang/rust-clippy/issues/9033


> Did you intend to create it in the rust-clippy repo? It's usually better if PRs only affecting Clippy are created there.

As far as understand the changes requested here https://github.com/rust-lang/rust-clippy/issues/9033 should in this repo or am I wrong?

**Comment by xFrednet** [comment]
Hey @alex-semenyuk, the `.stderr` files store the output of the tested `.rs` files. These tests then execute Clippy on the `.rs` files and compare the produced output with the one in the `.stderr` file. These tests are called UI tests. (See [rustc dev guide](https://rustc-dev-guide.rust-lang.org/tests/ui.html?ui-tests) if you're interested.) This means, that changes to the `.stderr` files, will not change how Clippy behaves. Instead, it's better to first change Clippy's behavior and then adjust the `.stderr` files.

The mentioned issue came up in this repo as it's related to a compiler change, but the implementation can be done in the *rust-clippy* repo. The changes are synced every two weeks between these two repos. So, if you have the time, it would be cool if you could create this PR in *rust-clippy* :upside_down_face:

**Comment by flip1995** [comment]
This PR only changes the `.stderr` files (which are generated files). This has to be fixed in the rust-lang/rust-clippy repo. But we still have to wait for the sync on Thursday.

I will close this PR for now, because it has to be reopened in Clippy anyway.

@alex-semenyuk If you have further questions on how to approach this, feel free to ask on the issue or on Zulip :)

**Pull request closed without merging**
