### PR TITLE
Utilize `PhantomData` to enforce `!Sync` and `!Send` field.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by nagisa** [comment]
cc @alexcrichton, a nice optimisation. Some backward compat hazard if anybody does transmute out of these, but I don’t think that would ever be problematic.

**Comment by alexcrichton** [comment]
@bors: r+ 404e31b4e7f07031843bdfdba4d09e0b18eb1085

Looks good to me, thanks!

**Comment by frewsxcv** [comment]
Compile errors fixed in the latest force push.

```diff
diff --git a/src/libstd/sys/unix/os.rs b/src/libstd/sys/unix/os.rs
index bc4c22a..6b8dfa5 100644
--- a/src/libstd/sys/unix/os.rs
+++ b/src/libstd/sys/unix/os.rs
@@ -400,7 +400,7 @@ pub fn args() -> Args {
         }
     }

-    Args { iter: res.into_iter(), _dont_send_or_sync_me: ptr::null_mut() }
+    Args { iter: res.into_iter(), _dont_send_or_sync_me: PhantomData }
 }

 #[cfg(any(target_os = "linux",
@@ -419,7 +419,7 @@ pub fn args() -> Args {
     let v: Vec<OsString> = bytes.into_iter().map(|v| {
         OsStringExt::from_vec(v)
     }).collect();
-    Args { iter: v.into_iter(), _dont_send_or_sync_me: ptr::null_mut() }
+    Args { iter: v.into_iter(), _dont_send_or_sync_me: PhantomData }
 }

 pub struct Env {
```

**Comment by apasel422** [comment]
Out of curiosity, is there a reason that the following doesn't work?

```rust
struct Args {
    iter: vec::IntoIter<OsString>,
}

struct Env {
    iter: vec::IntoIter<(OsString, OsString)>,
}

impl !Send for Args {}
impl !Sync for Args {}

impl !Send for Env {}
impl !Sync for Env {}
```

It ends up giving a better error message when you try to use these types in a `Send` or `Sync` context because it doesn't mention the types' internal fields.

**Comment by alexcrichton** [comment]
@apasel422 yeah I think that'd work but `impl !Foo` is unstable right now and I just personally tend to lean towards stable before unstable things.

**Pull request merged**
