### PR TITLE
add auto-impl for primitive type

### LINKED ISSUE #50431: rustdoc/stdlib docs: Auto trait implementations are missing reference types.
The auto traits `Sync` and `RefUnwindSafe` do not indicate anywhere in generated documentation that they are generated for reference types. The [`RefUnwindSafe`](https://doc.rust-lang.org/nightly/std/panic/trait.RefUnwindSafe.html) page appears to not have any auto implementations listed; [`Sync`'s page](https://doc.rust-lang.org/nightly/std/marker/trait.Sync.html) lists auto implementors but does not include references. The [reference](https://doc.rust-lang.org/nightly/std/primitive.reference.html) page covers it in the prose, but neither of the traits appears in the implementation list.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #50431.

I have no clue how to test this though with the rustdoc test suite...

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
If it's because you don't know how to force a primitive page to appear, you can do that by creating an empty module in a crate root and tagging it with `#[doc(primitive = "i32")]` (or some other primitive name). That will cause rustdoc to replace that mod with the corresponding primitive page. Then you can add your desired tests.

**Comment by GuillaumeGomez** [comment]
Seems more complicated than just doing this. I'll need to investigate further...

**Comment by QuietMisdreavus** [comment]
Some investigation today:

*Only* having a module tagged with `#[doc(primitive = "i16")]` will produce a page with nothing but whatever docs you tagged onto the module. Forcing rustdoc to include `all_trait_implementations` by re-exporting something from another crate (say, by `pub use std::fs::File` or the like) will pull in the necessary impls from core/std, which makes it load the auto-trait impls as well.

Strangely, this works for `i16` but not `bool`. One thing i noticed between them is that `bool` has no inherent methods, only trait implementations. I wonder if that has something to do with it...

**Comment by QuietMisdreavus** [comment]
More discussion has uncovered that the "impl inlining" code uses [this table](https://github.com/rust-lang/rust/blob/935a2f12b2a3ce44cbcbd0f7de1b388949cccca2/src/librustdoc/clean/inline.rs#L274-L300) to reference the list of primitives, which does not include an entry for `bool`. It does, however, include *two* entries for `str`, which means that there are two sets of auto-trait entries on that page. There's probably another set of lang-items we can use to pull the primitives we need out.

**Comment by QuietMisdreavus** [comment]
The last rebase only includes a test, it does not address the "no `bool` with two `str`" problem mentioned up-thread. I'm willing to land this with just tidy fixed (and if travis passes with the new test), but if that's the case i want to keep https://github.com/rust-lang/rust/issues/50431 open to track that.

**Comment by GuillaumeGomez** [comment]
I'll fix tidy this evening.

**Pull request merged**
