### PR TITLE
[beta] Rollup backports

### PR DESCRIPTION
**Pull request by emilyalbini**
Cherry-picked:

* #58207: Make `intern_lazy_const` actually intern its argument.
* #58161: Lower constant patterns with ascribed types. 
* #57908: resolve: Fix span arithmetics in the import conflict error
* #57835: typeck: remove leaky nested probe during trait object method resolution 
* #57885: Avoid committing to autoderef in object method probing 
* #57646: Fixes text becoming invisible when element targetted

Rolled up:

* #58522: [BETA] Update cargo 

r? @ghost

### CODE REVIEW

**Comment by ehuss** [comment]
@pietroalbini would it be possible to include #58522?

**Comment by pietroalbini** [comment]
@bors r-

> @pietroalbini would it be possible to include #58522?

Sure!

**Comment by pietroalbini** [comment]
@bors r-

Soft-blocked on https://github.com/rust-lang/rust/pull/58549 to keep CI manageable.

**Pull request merged**
