### PR TITLE
[Wip]Tentative add alloc::io module.

### PR DESCRIPTION
**Pull request by lygstate**
At the current stage, just copy std::io into alloca::io and 
* Remove the os related things such as std::io::stdio.
* Also convert all Error to string
* Add core:ctypes
* Use core::ctypes::iovec instead.

 

Get std::io to be  an core::io component so that can be used by runtime implemenation.

Especially for posix libc implemenation in rust with
* syscall(Linux)
* win32 api (windows)
* syscall(osx)
* syscall(redox)
* ? (fedora)
and so on.

This is for https://github.com/redox-os/relibc

Also for 
https://github.com/rulibc/rulibc
The fork of relibc that act as an msvcrt/mingw/cygwin/msys2 alternative on win32

glibc/musl alternative on linux world.

redox support will alomost unchanged with the upstream  Thttps://github.com/redox-os/relibc

And makes platform dependent IoSliceMut can be customized by the user
And give the default impl for windows/posix.

https://github.com/rust-lang/rust/issues/36193
related

Depends on
https://github.com/rust-lang/project-error-handling/issues/3
https://github.com/rust-lang/rust/pull/77384

### CODE REVIEW

**Comment by jyn514** [comment]
This looks like a copy/paste of `std::io` to `alloc::io`. Unfortunately, this won't work because `alloc` is meant to work on platforms without an operating system and `io` depends on the operating system.

I recommend going through an RFC process or https://internals.rust-lang.org/ if you're interested in this change, but it will need a lot of design and a rationale for why it's useful. This PR as-is is unlikely to be merged.

**Comment by lygstate** [comment]
> This looks like a copy/paste of `std::io` to `alloc::io`. Unfortunately, this won't work because `alloc` is meant to work on platforms without an operating system and `io` depends on the operating system.
> 
> I recommend going through an RFC process or https://internals.rust-lang.org/ if you're interested in this change, but it will need a lot of design and a rationale for why it's useful. This PR as-is is unlikely to be merged.

Thanks, this tentative, I have already removed the operating system part from alloc::io, I placed it under io because std::io depends on alloc, so I didn't place it under core::io.
The only part of alloc::io that are special are the iovec struct and I place it in the core::ctypes, it's seems other than windows platform, all other platform are the same, never mind what iovec it is, it's just a structure need to passed into operating system, so we just need to compatiable with the corresponding operating system

**Comment by Dylan-DPC** [comment]
@lygstate can you resolve the conflicts?

**Comment by lygstate** [comment]
@Dylan-DPC Currently it's depends on https://github.com/rust-lang/rust/pull/77384
after that merged, then this can be working on

**Pull request closed without merging**
