### PR TITLE
occurences of 'may not' to be more descriptive for issue #83584

### LINKED ISSUE #83584: Convert 'may not' to either 'must not' or 'might not' in the standard library documentation
"may not" has two possible meanings:
1. A command: "You may not stay up past your bedtime."
2. A fact that's only sometimes true: "Some cities may not have bike lanes."

In some cases, the meaning is ambiguous: "Some cars may not have snow
tires." (do the cars *happen* to not have snow tires, or is it
physically impossible for them to have snow tires?)

It would be better to change places where the standard library uses the "description of
fact" meaning to say "might not" instead, and change the "command" meaning to "must not".

You can find places where "may not" is used like so:

```
fd '.*' library/ | rg -v 'LICENCE|backtrace|stdarch' | xargs rg --glob '!library/backtrace/crates/backtrace-sys/**' 'may not'
```
_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/83582_

### PR DESCRIPTION
**Pull request by jessefromearth**
I did a `grep -rl "may not" library/` and went through each instance of `may not` and made my best guess to what each meant and changed them to be more descriptive. For example, "Humans may not fly." would become "Humans can not fly." or "Humans may not breathe 100% carbon dioxide" to "Humans should not breathe 100% carbon dioxide". 

Again, I made my best guess. Please let me know if there are any that are not accurate. I chose not to modify any `may or may not`'s because those are pretty self-explanatory. 

Fixes #83584

### CODE REVIEW

**Comment by egilburg** [comment]
Perhaps follow [IEFT RFC 2119](https://tools.ietf.org/html/rfc2119) for guidance on using these terms? For example, use "should" for best practice advice, and use "must" for things like compiler guarantees or places where failure to do so will cause undefined behavior.

**Comment by jessehorne** [comment]
> Perhaps follow [IEFT RFC 2119](https://tools.ietf.org/html/rfc2119) for guidance on using these terms? For example, use "should" for best practice advice, and use "must" for things like compiler guarantees or places where failure to do so will cause undefined behavior.

I agree with RFC 2119 for the most part but I wish it had defined "WILL"/"WILL NOT". Given our use-case,  I don't feel like following it exactly would make much sense. For example, if a function is designed to return `1`, do you say in the documentation that "this function MUST return '1'", or "this function SHOULD return '1'"? For declaring intent of the implementation, I think "WILL" makes more sense. "MUST" sounds more like you're giving another party information. "WILL" sounds like you're saying "This was designed for that!". 

That being said, I didn't use "WILL" at all in this. I mostly just changed from "may not" to either "should not" or "might not" depending on the scenario. While I agree that a standard is helpful when using these terms in documentation, oftentimes it seemed that the use of "may not" in these cases were pretty clear IF you read the previous documentation to gain context. I see the value of this if nothing else to just make it that much clear and potentially save time.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@jessehorne - can you please address the merge conflict?

@Rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by crlf0710** [comment]
@jessehorne I'm gonna close this due to inactivity. Feel free to reopen or create a new pr when you've got time to work on this again. Thanks!

**Pull request closed without merging**
