### PR TITLE
Remove hack for actix-web and actori-web

### PR DESCRIPTION
**Pull request by Aaron1011**
Hopefully, most affected crates have run `cargo update` by now. If not,
I'll explore phasing this out gradually.

r? @ghost

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by ThePuzzlemaker** [comment]
Huh. I’m curious. When exactly was this introduced and why?

**Comment by Aaron1011** [comment]
@ThePuzzlemaker This was introduced in https://github.com/rust-lang/rust/commit/9a6ea386472acb7e1e1dd24370ef9d60d07463f5, as part of https://github.com/rust-lang/rust/pull/77135. That PR made us preserve the original `TokenStream` in more cases, making progress towards fixing the longstanding compiler bug https://github.com/rust-lang/rust/issues/76267.

Unfortunately, this change broke `actix-web` and `actori-web`, since they used an older version of `syn` that was not prepared to handle the `None`-delimited groups present in the new `TokenStream` input. As a result, I added this hack to allow those crates to continue to compile, while still allowing us to preserve `Span`s in the input `TokenStream`.

However, having the compiler special-case certain filenames is a really awful hack. I'd like to get rid of this as soon as possible - unfortunately, there may be a large number of `Cargo.lock` files onGitHub that need to be updated.

**Comment by pietroalbini** [comment]
@craterbot run start=master#5e91c4ecc09312d8b63d250a432b0f3ef83f1df7 end=try#5e91c4ecc09312d8b63d250a432b0f3ef83f1df7 mode=check-only

**Comment by Aaron1011** [comment]
@pietroalbini It looks like you specified the same start and end commit?

**Comment by Aaron1011** [comment]
@craterbot abort

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by pietroalbini** [comment]
@craterbot retry

**Comment by pietroalbini** [comment]
Sorry about that. A new crater deployment broke a thing. Should be fixed now.

@craterbot retry p=3

**Comment by pietroalbini** [comment]
@craterbot retry

**Comment by pietroalbini** [comment]
@craterbot p=3

**Comment by crlf0710** [comment]
Ping from triage @Aaron1011 : it seems some crates like `actix-web` 2.0.0 and `actix-web` 3.0.0 still regresses after this change. What's next steps here?

**Comment by Aaron1011** [comment]
The `actori-web` hack was removed entirely, and we are now linting whenver we apply the `actix-web` hack.

**Pull request closed without merging**
