### PR TITLE
Bump unsupported `ubuntu` CI images to 24.04 LTS

### LINKED ISSUE #133531: `arm-android/Dockerfile` is based on the now outdated Ubuntu 23.04
Hi there!

Since a while ago, Rustup's CI workflow has been failing due to the Android job's aborting (https://github.com/rust-lang/rustup/pull/4070#issuecomment-2500886187, https://github.com/rust-lang/rustup/pull/4098#issuecomment-2503418305) with the following error message:

```console
#5 0.935 E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates Release' no longer has a Release file.
```

... and I believe that it's caused by an outdated base image for which the `apt` repository is no longer online:

https://github.com/rust-lang/rust/blob/39cb3386ddc6c71657418be28dbb3987eea4aa4b/src/ci/docker/host-x86_64/arm-android/Dockerfile#L1

Are there any concerns regarding a potential bump to an LTS such as 24.04? I can do this myself if you think that's okay :)

### PR DESCRIPTION
**Pull request by rami3l**
Closes #133531.

try-job: arm-android
try-job: dist-android
try-job: dist-ohos

### CODE REVIEW

**Comment by pan93412** [comment]
```
  3.783 E: Unable to locate package libncurses5
```

Seems like it should be replaced to `libncurses` (which installs v6)? Reference: https://github.com/rvm/rvm/issues/5475

**Comment by rami3l** [comment]
> @bors try

@Urgau Thanks for the quick response! I've double checked these dockerfiles and have made some dependency updates. After that all three of them can build without issues on my machine (I'm not sure about the runtime behavior though). Shall we try again?

**Comment by rami3l** [comment]
r? Urgau

**Comment by Urgau** [comment]
LGTM, but I'm not a infra reviewer.

r? @Mark-Simulacrum

**Comment by Kobzol** [comment]
This seems uncontroversial, and since `23.04` is deprecated and soon EOL, we'll need to upgrade the base image anyway.

@bors r+

**Pull request merged**
