### PR TITLE
Do not ping PR reviewers in toolstate breakage

### PR DESCRIPTION
**Pull request by JohnTitor**
As per https://github.com/rust-lang/rust/issues/69419#issuecomment-590470520

We should also remove author part?

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I think pinging the PR author is at least reasonable, though I agree that many PR authors in practice won't followup (and leave it to tool people). I think that mostly speaks to a not-great experience to the "I want to fix tools" story today, though.

I'd like T-compiler sign-off on this as the primary affected party, though I think FCP is overkill -- let's just see if anyone objects at/before the meeting. cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
I think it's ok either way

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. All were in favor of this change. Some were in favor of going further (e.g. removing PR author as well) but we opted to leave that discussion for a later  point. I.e. lets not block this PR on that question.

**Pull request merged**
