### PR TITLE
[beta] Backports

### PR DESCRIPTION
**Pull request by MaloJaffre**
Cherry-picked (cleanly) into beta: 
- #46916
- #47161
- #47208
- #47269

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can you also bump the [beta version number](https://github.com/rust-lang/rust/blob/master/src/bootstrap/channel.rs#L32)? That way we can release a new beta with these backports. Thanks!

**Comment by MaloJaffre** [comment]
@Mark-Simulacrum Done!

**Comment by alexcrichton** [comment]
Thanks for the backport here @MaloJaffre!

**Pull request merged**
