### PR TITLE
Update Cargo

### PR DESCRIPTION
**Pull request by steveklabnik**
This pulls in https://github.com/rust-lang/cargo/pull/6054, and
is a beta backport of https://github.com/rust-lang/rust/pull/54334

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Actually, I think this might run into the same problem as the other pull request in that it doesn't update cargo.lock? Travis seems to be going though so maybe beta didn't need it.

**Comment by ehuss** [comment]
This removes about 4 days of updates that were in 1.30.  Not sure how important that is.  The rust beta branch was pointing at [a5d82949485802abb45f888d5b8b7f23927f031d](https://github.com/rust-lang/cargo/commit/a5d82949485802abb45f888d5b8b7f23927f031d) of cargo's master (from Sep 13).  The cargo-1.30.0 was branched off from [b917e35248fe57d11765c5a835de33e335babb7e](https://github.com/rust-lang/cargo/commit/b917e35248fe57d11765c5a835de33e335babb7e) from Sep 9th.  I don't know why the 1.30.0 branch was so far back.  Here's the diff: https://github.com/rust-lang/cargo/compare/b917e35248fe57d11765c5a835de33e335babb7e...a5d82949485802abb45f888d5b8b7f23927f031d

**Comment by steveklabnik** [comment]
> I think this might run into the same problem as the other pull request in that it doesn't update cargo.lock? 

I ran `cargo update cargo -p` and it didn't change anything.

> This removes about 4 days of updates that were in 1.30. Not sure how important that is.

I'm not sure either; this was the path Alex told me to take. I think it's because it has to be before the version bump PR landed. None of that diff looks mega-important to me, so I *think* it's fine.

**Comment by steveklabnik** [comment]
> [01:37:28] fatal: unable to access 'https://github.com/rust-lang/rust.git/': Could not resolve host: github.com

Seems spurious. 

@bors: retry

**Comment by ehuss** [comment]
> I think it's because it has to be before the version bump PR landed. None of that diff looks mega-important to me, so I _think_ it's fine.

The version bump was done on the 18th (after the beta branch).  This has happened in the past, and @alexcrichton just fixed the branch.  Personally I'd be a little disappointed if the new progress bar took another 6 weeks to be stabilized, but it's not critical.

**Comment by alexcrichton** [comment]
Er sorry, it appears I botched the original base of the `rust-1.30.0` branch! I'll fix that.

**Pull request merged**
