### PR TITLE
Assoc item cleanup

### PR DESCRIPTION
**Pull request by matthewjasper**
This removes some fields from ObligationCauseCode

Split out of #90639

### CODE REVIEW

**Comment by cjgillot** [comment]
Sorry for the ping oli-obk, I mis-clicked.

**Comment by cjgillot** [comment]
r=me with the PR message updated.

**Comment by matthewjasper** [comment]
I was hoping to readd some changes back into this PR, but I guess this can be merged as is for now.
@bors r=cjgillot

**Pull request merged**
