### PR TITLE
Update Clippy and cargo

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth  @oli-obk

### CODE REVIEW

**Comment by flip1995** [comment]
```
2019-08-15T12:07:28.8799163Z -error: error reading Clippy's configuration file `$DIR/clippy.toml`: expected an equals, found an identifier at line 1 column 4
2019-08-15T12:07:28.8799403Z +error: error reading Clippy's configuration file `$DIR/clippy.toml`: expected an equals, found an identifier at line 1
2019-08-15T12:07:28.8799604Z  error: aborting due to previous error
```

Huh, we had to fix this in Clippy the other way around? rust-lang/rust-clippy#4378 :thinking:

**Comment by flip1995** [comment]
Pointed the Clippy submodule to https://github.com/rust-lang/rust-clippy/commit/ebd3eeaede75e0a3aa55ceaa868d0dbbe23b4ec1, which will be on the master branch, once rust-lang/rust-clippy#4391 is merged. (Except the update of the `toml` crate to `0.5.3` breaks other things  in rustc)

**Comment by flip1995** [comment]
Updated to rust-lang/rust-clippy#4395

**Comment by matthiaskrgr** [comment]
This will probably not merge because https://github.com/rust-lang/rust/pull/63627 broke clippy again

**Comment by flip1995** [comment]
@bors r-

Is this possible now?

**Comment by flip1995** [comment]
Nice.

**Comment by flip1995** [comment]
Rebased it on the auto merge of rust-lang/rust-clippy#4398. So this can be r+ed again once this is merged.

**Comment by oli-obk** [comment]
Oh, nevermind

@bors r+

**Comment by flip1995** [comment]
Updated `Cargo.lock` again. Now this should be good to go.

@bors r+

**Comment by flip1995** [comment]
(Only the serde version change from the last `Cargo.lock` update. 1.0.98 -> 1.0.99)

**Comment by Centril** [comment]
PR builder says this will fail; @bors r-

**Comment by flip1995** [comment]
PR build of Clippy passes now :+1: 

@bors r+

**Comment by flip1995** [comment]
Updated to rust-lang/rust-clippy#4410

@bors r+

**Comment by flip1995** [comment]
```
---- bad_config::invalid_global_config stdout ----
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build -v`
thread 'bad_config::invalid_global_config' panicked at '
Expected: execs
    but: differences:
  9 - |  expected an equals, found eof at line 1|
    + |  expected an equals, found eof at line 1 column 2|

```

As expected (https://github.com/rust-lang/rust/pull/63587#issuecomment-521654518), the update of `toml` breaks the cargo tests.

I would also update `toml` in cargo, instead of downgrading `toml` in Clippy again.

**Comment by flip1995** [comment]
Also update cargo to include https://github.com/rust-lang/cargo/commit/b41c209af308dc307ae5b8c5521b01180a9abfa5

**Comment by matthiaskrgr** [comment]
@flip1995  can you re-r+? ^^

**Comment by flip1995** [comment]
Wanted to wait if the PR build passes, to not spam the queue. (And then forgot about it, oops) :smile:

**Comment by flip1995** [comment]
@bors r+

You can do it bors! :)

**Comment by phansch** [comment]
This will also need another update to https://github.com/rust-lang/rust-clippy/commit/1055cf5b9f0737a42bb9a58d9f6064c5bdf4926a

**Pull request merged**
