### PR TITLE
rustc_builtin_macros: make asm mod public for rustfmt

### PR DESCRIPTION
**Pull request by calebcartwright**
Follow up to #92016, as I'd completely missed that the mod we needed was internal

### CODE REVIEW

**Comment by jyn514** [comment]
Hmm, I think it would be better to re-export the function in the root rather than making the whole module public.

**Comment by calebcartwright** [comment]
> Hmm, I think it would be better to re-export the function in the root rather than making the whole module public.

Well, we need the struct too. There's only 4 currently public items in that mod, so I suppose I can either re-export the 2 we need and keep the mod private, or modify the visibility on the other 2 to keep them in-crate, if there's concerns about `expand_asm` or `expand_global_asm` being used elsewhere in an undesirable manner (or similarly for any hypothetical future `pub` items added to `asm`)

**Comment by calebcartwright** [comment]
I've opted for the latter, but don't mind changing it if you (or anyone) feels strongly that it'd be better to do the former. Let me know

**Comment by calebcartwright** [comment]
Not really sure what to make of the CI failure, seems potentially spurious so going to retry

image


@bors retry

**Pull request merged**
