### PR TITLE
Turn implied_outlives_bounds into a query

### PR DESCRIPTION
**Pull request by tmandry**
Right now all this does is remove the error reporting in `implied_outlives_bounds`, which seems to work. Farming out full tests to Travis.

For #51649. That issue is deferred so not sure what's next.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@tmandry oh, nice! This PR was a bit unexpected, but happy to have it! =) I did do some tests locally which suggest that the error reporting code is basically dead code (I added a `bug!` call and it never fired), so that's good news for making this into a query. Let me take a look.

**Comment by tmandry** [comment]
Hmm, I had triggered it on one test, see https://github.com/rust-lang/rust/issues/51649#issuecomment-401580525. 

This PR doesn’t actually make it a query, yet, btw :)

**Comment by nikomatsakis** [comment]
Ugh. Rebased, but travis is reporting a new failure. On the bright side, this turns out to fix some other problems we were encountering (#52078)

**Comment by nikomatsakis** [comment]
Rebased.

**Pull request merged**
