### PR TITLE
Move rustc_smir to driver

### PR DESCRIPTION
**Pull request by ouz-a**
With this change this will allow us to call `rustc_smir` function from `rustc_driver` and few other places. So things like being able to implement `--emit=smir` will be possible.

r? @oli-obk

### CODE REVIEW

**Comment by compiler-errors** [comment]
I don't understand why this motivation:

> With this change this will allow us to call rustc_smir function from rustc_driver and few other places.

Results in this change. You should be able to just make `rustc_driver` depend on `rustc_smir` via its `Cargo.toml` instead of actually moving the source into that crate.

**Comment by celinval** [comment]
I would also prefer keeping these two crate separate.

**Comment by ouz-a** [comment]
> I don't understand why this motivation:
> 
> > With this change this will allow us to call rustc_smir function from rustc_driver and few other places.
> 
> Results in this change. You should be able to just make `rustc_driver` depend on `rustc_smir` via its `Cargo.toml` instead of actually moving the source into that crate.

`rustc_smir` is fundamentally dependent on `rustc_driver`, I can't add cyclic dependency, also should've put prior discussion of this in my message: https://rust-lang.zulipchat.com/#narrow/stream/320896-project-stable-mir/topic/should.20we.20have.20--emit.3Dsmir

**Comment by oli-obk** [comment]
I was thinking that we could either

* move only the `StableMir` type to rustc_driver (as that is its own driver),
* or if we want to keep all logic in rustc_smir, add a macro that imports and invokes rustc_driver, so that smir drivers can just do that but rustc_smir doesn't actually depend on rustc_driver.

**Comment by ouz-a** [comment]
Since this is done better via in https://github.com/rust-lang/rust/pull/116837 I'm closing this.

**Pull request closed without merging**
