### PR TITLE
Enforce the static symbol order.

### PR DESCRIPTION
**Pull request by nnethercote**
By making the proc macro abort if any symbols are out of order.

The commit also changes the proc macro collect multiple errors (of order
or duplicated symbols) and prints them at the end, which is useful if
you have multiple errors.

r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
This will need rebasing after #74175 lands, but the code is reviewable in its current state.

**Comment by Manishearth** [comment]
@bors r-

#74242 (comment)

**Comment by Manishearth** [comment]
If https://github.com/rust-lang/rust/pull/72920 lands first this will need to be updated

**Comment by nnethercote** [comment]
I rebased.

@bors r=petrochenkov

**Comment by nnethercote** [comment]
I rebased again.

@bors r=petrochenkov

**Comment by nnethercote** [comment]
I rebased yet again. This commit is super conflict-prone.

@bors r=petrochenkov

**Comment by nnethercote** [comment]
How do p=1 and rollup=always interact?

**Comment by Manishearth** [comment]
@nnethercote sort order is by priority first, then rollupability. It's fine to p=1 rollup=always, it means that the PR is high priority but you also have a strong expectation that it will not break anything and encourage rollup authors to pick it up. Typically that never happens because if a PR is high priority it _probably_ makes nontrivial changes that warrant it being high priority, however priority can also be for "this PR is going to bitrot easily", in which case p=1 rollup=always makes sense

**Comment by nnethercote** [comment]
Ok, sounds like rollup=always really means rollup=highly-recommended :)

**Pull request merged**
