### PR TITLE
Forbid glob-importing from a type alias

### LINKED ISSUE #30560: rustdoc: panic caused by a "reexport" of a type alias
Code that compiles fine with rustc is causing an internal compiler error: unexpected panic with rustdoc.

I tried this code (`bug.rs`):
```rust
type Foo = isize;
pub use self::Foo::*;
```
The second line is essentially a typo, which can happen if `Foo` used to be an Enum for instance.

Again, the following works fine (although I'm not sure why, can you even add anything to the `Foo` namespace?):
```
rustc bug.rs --crate-type lib
```
However, if I run:
```
rustdoc bug.rs
```
I get the error:
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'glob not mapped to a module or enum', ../src/librustdoc/visit_ast.rs:246
```
This actually happened on a version of a package already pushed to crates.io (hdf5-sys 0.3.0), so anything that depends on the erroneous version and runs `cargo doc` will see this error.

## Meta
Run on `rustdoc 1.7.0-nightly (4ce1dafd1 2015-12-23)`.

Backtrace:
```
   1:        0x10767a558 - sys::backtrace::tracing::imp::write::h437867c953ecf350mZt
   2:        0x10768060f - panicking::log_panic::_<closure>::closure.41684
   3:        0x1076800b4 - panicking::log_panic::h11dc8b3c6952cc98VRx
   4:        0x107648006 - sys_common::unwind::begin_unwind_inner::haa584e089eabb124o2s
   5:        0x102f80b34 - sys_common::unwind::begin_unwind::begin_unwind::h18100502266587524809
   6:        0x103164cd3 - visit_ast::RustdocVisitor<'a, 'tcx>::resolve_id::h34d767a94ffda832qSt
   7:        0x1031629d6 - visit_ast::RustdocVisitor<'a, 'tcx>::visit_item::hec3b049092d8fa8cEVt
   8:        0x10315ba12 - visit_ast::RustdocVisitor<'a, 'tcx>::visit_mod_contents::h7551e6f2d22647cc1Ot
   9:        0x1030ef4ef - visit_ast::RustdocVisitor<'a, 'tcx>::visit::ha59cf730f9a0c027FHt
  10:        0x1030e8f12 - rustc_driver::driver::phase_3_run_analysis_passes::_<closure>::closure.42399
  11:        0x1030c5d27 - middle::ty::context::ctxt<'tcx>::create_and_enter::create_and_enter::h13379830180998392343
  12:        0x1030c2231 - driver::phase_3_run_analysis_passes::phase_3_run_analysis_passes::h13354236957594875836
  13:        0x102fbebb0 - core::run_core::h09e73f61b678853aZdk
  14:        0x102fba240 - sys_common::unwind::try::try_fn::try_fn::h13762566296504504003
  15:        0x107678088 - __rust_try
  16:        0x10766fd8e - sys_common::unwind::try::inner_try::hf68fe5ebaab44cceWYs
  17:        0x102fbbf01 - boxed::F.FnBox<A>::call_box::call_box::h3532894196117764030
  18:        0x10767f6ad - sys::thread::Thread::new::thread_start::h1257bf86ea35bf0aZbx
  19:     0x7fff8f30e267 - _pthread_body
  20:     0x7fff8f30e1e4 - _pthread_start
```

### PR DESCRIPTION
**Pull request by jseyfried**
This PR forbids glob-importing from a type alias or trait (fixes #30560):

``` rust
type Alias = ();
use Alias::*; // This is currently allowed but shouldn't be
```

This is a [breaking-change]. Since the disallowed glob imports don't actually import anything, any breakage can be fixed by removing the offending glob import.

r? @alexcrichton

### CODE REVIEW

**Comment by jseyfried** [comment]
I could also make this a warning for a warning cycle.

**Comment by jseyfried** [comment]
I could also make this a warning for a warning cycle.
cc @petrochenkov

**Comment by petrochenkov** [comment]
```
trait Tr {}
use Tr::*;
```
also compiles.
(I've checked other items, they all seem to behave appropriately.)

**Comment by jseyfried** [comment]
Good point, I'll forbid that too.

**Comment by alexcrichton** [comment]
Thanks @jseyfried! I'll run crater to see what kind of fallout we're looking at.

**Comment by alexcrichton** [comment]
Looks like there are [six root regressions](https://gist.github.com/alexcrichton/4b121522e4eeb4e87a34), but it looks like most of those are actually just rooted in [my own mistake](https://github.com/alexcrichton/git2-rs/blob/master/libgit2-sys/lib.rs#L539). I'm personally always a fan of aggressive bug fixing, so I would be ok with pushing forward without a warning cycle, but others might feel differently!

So in terms of code, r=me, but in terms of scheduling/warning, I'll defer to @rust-lang/lang 

cc @nikomatsakis

**Comment by alexcrichton** [comment]
er, r? @nikomatsakis

**Comment by alexcrichton** [comment]
To put the numbers into context, 12/13 regressions were fixed by the new versions of libgit2-sys I just published, so it seems like a relatively low-impact change to me. It's definitely "weird" code that would exercise this.

**Comment by jseyfried** [comment]
The remaining regression is in `angle-0.1.1` and is caused by glob importing from a trait.

**Comment by nikomatsakis** [comment]
I think most everyone would agree this is a straight-up bug fix and it's ok to Just Fix It.

**Pull request merged**
