### PR TITLE
`crate` shorthand visibility modifier

### LINKED ISSUE #45388: permit `crate` as a shorthand visibility identifier
As part of https://github.com/rust-lang/rust/issues/44660, we plan to support `crate` as a visibility modifier equivalent to `pub(crate)`. Given that `pub(crate)` exists, this should be relatively straight-forward. 

Visibilities are stored in [the AST type `Visibility`](https://github.com/rust-lang/rust/blob/e3fb84e951e3c602d2dbbfebbd4ee275ac414893/src/libsyntax/ast.rs#L1793). We will want to extend the `Crate` variant to include one additional field, indicating whether the sugar `crate` or the expanded form `pub(crate)` was used. We can add an enum like 

```rust
enum CrateSugar {
    /// User wrote `pub(crate)`
    PubCrate,

    /// User wrote `crate`
    JustCrate,
}
```

and add this field to [the `Crate` variant](https://github.com/rust-lang/rust/blob/e3fb84e951e3c602d2dbbfebbd4ee275ac414893/src/libsyntax/ast.rs#L1793), so that it looks like `Crate(Span, CrateSugar)`. Actually, at the same time we can remove the `Span` field, which appears to be unused, so it would just become `Crate(CrateSugar)`. Doing this simultaneously is sorta bad but will save you some editing, since all existing uses look like `Crate(_)`, and 99% of them want to ignore the `CrateSugar` field anyway. =)

The one user that does NOT want to ignore `CrateSugar` is the pretty printer.  We just want to change [this line](https://github.com/rust-lang/rust/blob/e3fb84e951e3c602d2dbbfebbd4ee275ac414893/src/libsyntax/print/pprust.rs#L1443) to something like:

```rust
 ast::Visibility::Crate(CrateSugar::PubCrate) => self.word_nbsp("pub(crate)"),
 ast::Visibility::Crate(CrateSugar::JustCrate) => self.word_nbsp("crate"),
```

Naturally, we also will want to alter the parser itself, in particular [the `parse_visibility` function](https://github.com/rust-lang/rust/blob/e3fb84e951e3c602d2dbbfebbd4ee275ac414893/src/libsyntax/parse/parser.rs#L5325). Currently, if it doesn't see the word `pub`, [it just returns](https://github.com/rust-lang/rust/blob/e3fb84e951e3c602d2dbbfebbd4ee275ac414893/src/libsyntax/parse/parser.rs#L5328). We need to extend this to look for `crate` and -- if it finds it -- to return the new visibility (with sugar `JustCrate`). We also need to modify [the existing `pub(crate)` code](https://github.com/rust-lang/rust/blob/e3fb84e951e3c602d2dbbfebbd4ee275ac414893/src/libsyntax/parse/parser.rs#L5341) to return `PubCrate` for the sugar.

(Note: Please limit discussion on this issue strictly to implementation concerns relative to this particular change. Policy discussion as to whether or not to make this change -- or whether to make other changes to the module system -- belong in https://github.com/rust-lang/rust/issues/44660.)

### PR DESCRIPTION
**Pull request by zackmdavis**
cc #45388.

r? @nikomatsakis

### CODE REVIEW

**Comment by petrochenkov** [comment]
Everything looks good to me.
@bors r+

P.S. I've edited the PR message so it doesn't close the tracking issue automatically.

**Comment by kennytm** [comment]
Cannot build rustfmt (and thus RLS), legit. The tools need to be broken.

```
[01:04:05] Dist RLS stage2 (x86_64-pc-windows-msvc)
[01:04:05] Building stage2 tool rls (x86_64-pc-windows-msvc)
...
[01:04:57] error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
[01:04:57]   --> src\tools\rustfmt\src\utils.rs:40:9
[01:04:57]    |
[01:04:57] 40 |         Visibility::Crate(_) => Cow::from("pub(crate) "),
[01:04:57]    |         ^^^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1
[01:04:57] 
[01:05:00] error: aborting due to previous error
[01:05:00] 
[01:05:02] error: Could not compile `rustfmt-nightly`.
[01:05:02] warning: build failed, waiting for other jobs to finish...
[01:05:04] error: build failed
```

**Comment by zackmdavis** [comment]
force-push 214b0f22 removes the "Resolves" language concerning #45388 (I had been given to understand that the tracking issue would be #44660, but I [agree that that's a bit unwieldy](https://github.com/rust-lang/rust/issues/44660#issuecomment-330076368)) and sets the toolstate for rustfmt and RLS to "Broken" (sorry @nrc)

**Pull request merged**
