### PR TITLE
Shrink `Nonterminal`

### PR DESCRIPTION
**Pull request by nnethercote**
These commits shrink `Nonterminal` from 240 bytes to 40 bytes. When building `serde_derive` they reduce the number of `memcpy` calls from 9.6M to 7.4M, and it's a tiny win on a few other benchmarks.

r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
Notable local `check-clean` results:
```
serde-serde_derive-check
        avg: -0.8%      min: -0.8%      max: -0.8%
coercions-check
        avg: -0.4%?     min: -0.4%?     max: -0.4%?
deep-vector-check
        avg: -0.3%      min: -0.3%      max: -0.3%
tuple-stress-check
        avg: 0.2%       min: 0.2%       max: 0.2%
helloworld-check
        avg: -0.1%      min: -0.1%      max: -0.1%
issue-46449-check
        avg: -0.1%      min: -0.1%      max: -0.1%
unify-linearly-check
        avg: -0.1%      min: -0.1%      max: -0.1%
syn-check
        avg: -0.1%      min: -0.1%      max: -0.1%
unicode_normalization-check
        avg: 0.1%       min: 0.1%       max: 0.1%
await-call-tree-check
        avg: -0.1%      min: -0.1%      max: -0.1%
tokio-webpush-simple-check
        avg: -0.1%      min: -0.1%      max: -0.1%
```
Note that `serde_derive` is not part of `rustc-perf`, but I have included it in my local copy to get the above results.

**Comment by Centril** [comment]
Would appreciate if we could block merging this PR on first merging https://github.com/rust-lang/rust/pull/67131 since this one will generate a lot of conflicts with that PR.

**Comment by nnethercote** [comment]
Here are the `serde_derive` results, for comparison:
```
serde-serde_derive-check
- avg: -1.1%  min: -1.8%  max: -0.7% 
- clean                 11,770,595,200.00  11,668,371,819.00  -0.9% 
- baseline incremental  14,431,966,930.00  14,328,177,470.00  -0.7% 
- clean incremental      5,746,154,634.00   5,642,802,601.00  -1.8% 
```

**Comment by petrochenkov** [comment]
r=me after rebase

**Comment by joelpalmer** [comment]
Ping from Triage: Any updates @nnethercote?

**Comment by nnethercote** [comment]
Back now from PTO, I have rebased.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
rust-timer didn't give us a "finished" message, but the results are in and look as expected -- a small win.

r? @petrochenkov

**Pull request merged**
