### PR TITLE
Ignore these tests ,since the called commands doesn't exist in VxWorks

### PR DESCRIPTION
**Pull request by BaoshanPang**

### CODE REVIEW

**Comment by BaoshanPang** [comment]
cc @n-salim @Umesh Kalappa

**Comment by JohnTitor** [comment]
Seems failed in https://github.com/rust-lang/rust/pull/66169#issuecomment-550556736
@bors r-

**Comment by BaoshanPang** [comment]
@alexcrichton 
Sorry, I didn't notice the ingoring for android on test case test_process_output_error has been removed.

**Pull request merged**
