### PR TITLE
Disable thread support in libtest if `RUST_TEST_THREADS=1`

### PR DESCRIPTION
**Pull request by ianks**
After #103681, each test now runs in it's own thread if the platform supports it. This was true even if `RUST_TEST_THREADS=1`. Unfortunately, this causes some subtle breakage for certain libraries that may rely on thread-local storage being shared across tests (as is the case for `libruby` and Julia, and probably more).

The feature [never intended to cause any breakage](https://github.com/rust-lang/rust/issues/104053#issuecomment-1304992972), so restoring the previous behavior should be OK. I considered adding a new option, such as `RUST_TEST_THREADS=0`, which would allow both the new and previous behavior to exist side-by-side. But the idea of 0 threads felt... wrong. So I think this is the best way forward.

This is my first rust PR, so please let me know if I missed anything!  ❤️

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @thomcc

It feels like we might want this to be a separate knob, not related to threads=1...

**Comment by the8472** [comment]
> It feels like we might want this to be a separate knob, not related to threads=1...

Agreed. Sometimes testing with N > 1 threads could also benefit from reusing threads instead of running a thread-per-test, e.g. when loads of thread-local caches or similar things need to be initialized.
I don't think we ever had thread pooling in libtest, but choosing a generic option name would allow it to cover both cases (all tests in 1 thread and all tests on pooled threads).

**Comment by thomcc** [comment]
This kinda feels like a libs-api decision, regarding how this "should" work.

**Comment by thomcc** [comment]
Actually, I've realized that promising this and doing it in this manner would lock us into never fixing some bugs in libtest (like having no slow test notification on machines with 1 core). Let me dig up some old code and make a counter-proposal.

**Comment by uazu** [comment]
As a vote in favour of the intent of this change (although I'm not following the details): 

I have a case where I need to test code that effectively locks future invocations of that same code to the same thread. This is to make internal use of global variables by the code sound. This is for an optional feature-based optimisation in the crate, but the optimisation is worthwhile for the cases where it is used, saving both memory and CPU. It tested fine until 1.67, but since then I can't test it because it immediately panics when it notices that it's running on another thread.

Making RUST_TEST_THREADS=1 use just a single thread again would fix my problem. Right now I have to use a hacky workaround, using --list to get a list of tests and running them one by one.

**Comment by knopp** [comment]
Rust default test harness is very much unusable for anything on macOS that requires execution on main thread. Unfortunately main thread is special (so that on some places there are actually checks for `pthread_main_np`, i.e. in libdispatch. It would be immensely helpful if there was way to run tests with the default harness directly on main thread.

**Comment by RalfJung** [comment]
> The feature never intended to cause any breakage, so restoring the previous behavior should be OK.

FWIW running it all in one thread was also never intended to be a feature -- previous behavior (Rust 1.0 - ~1.30) was to always spawn threads; https://github.com/rust-lang/rust/pull/56243 did the "run in a single thread" thing as a hack to make `cargo miri test` work.

So, neither #56243 nor https://github.com/rust-lang/rust/pull/103681 was intended to be more than an internal refactor, and neither should be read as indicating intent. Forcing a single thread has disadvantages (e.g. https://github.com/rust-lang/rust/issues/59122).

**Comment by the8472** [comment]
If the library has a requirement to run on a specific thread then it should do what many UI libraries do and provide something like `fn dispatch_to_ui_thread<R, F>(f: F) -> R where F: FnOnce() -> R + Send, R: Send` that submits it via a channel it to the initialized thread and waits for the result to be returned.

Then tests that interact with that library can serialize themselves by dispatching to that thread. Other tests that don't touch that part can still run in parallel.

None of that requires any changes to libtest. This is a problem of libraries that have additional requirements but do not provide the necessary facilities to meet those requirements in their API.

**Comment by bjorn3** [comment]
> None of that requires any changes to libtest.

It does require a change to free up the main thread for use by the ui framework. In many cases the ui thread can only be the main thread, but it is currently being used by libtest so nobody else can run anything on it.

**Comment by thomcc** [comment]
Yeah, apple provides those functions but a function you sent to that queue would never get run (and if you blocked on it, you'd deadlock), because libtest doesn't start the main loop.

Overall

**Comment by knopp** [comment]
> This is a problem of libraries that have additional requirements but do not provide the necessary facilities to meet those requirements in their API.

The API is all there - I can easily dispatch things to main thead on macOS (i.e. `dispatch_async` or `CFRunLoopAddSource`) but that will not help because the main thread is stuck in libtest instead of running the run loop.

**Comment by the8472** [comment]
> It does require a change to free up the main thread for use by the ui framework. 

Last time (it has been a few years) I had to deal with these kinds of issues the framework had a way to initialize the UI event loop on something that was not the program's first/main thread.

> The API is all there - I can easily dispatch things to main thead on macOS (i.e. dispatch_async or CFRunLoopAddSource) but that will not help because the main thread is stuck in libtest instead of running the run loop.

Ok, I haven't dealt with macos. Does it not have that?

**Comment by knopp** [comment]
> Ok, I haven't dealt with macos. Does it not have that?

Unfortunately no. There are hard-coded assumptions about main thread in various places.

https://github.com/opensource-apple/CF/blob/3cc41a76b1491f50813e28a4ec09954ffa359e6f/CFRunLoop.c#L1482-L1487
```c
CFRunLoopRef CFRunLoopGetMain(void) {
    CHECK_FOR_FORK();
    static CFRunLoopRef __main = NULL; // no retain needed
    if (!__main) __main = _CFRunLoopGet0(pthread_main_thread_np()); // no CAS needed
    return __main;
}
```
There are similar checks all over AppKit, libdispatch, etc. too. The only way for things to work properly is to run the main thread loop (`CFRunLoopRun()` on main thread (first created thread - for which `pthread_main_thread_np()` returns 1).

**Comment by thomcc** [comment]
I'm going to be away for a few months, so I'm rerolling my PRs so that folks don't have to wait for me. Sorry/thanks.

r? libs

**Comment by m-ou-se** [comment]
cc @rust-lang/testing-devex

**Comment by epage** [comment]
I agree with the disposition to close based on what I saw in the thread.

Another workaround for this is to use a custom test harness (`libtest-mimic` can help).  Of course, I'd love to improve the experience of using a custom test harness.  If someone would like to help out in that effort, come on over to https://github.com/rust-lang/libtest-next

**Pull request closed without merging**
