### PR TITLE
use vendored rustfmt-nightly (src/tools/rustfmt)

### PR DESCRIPTION
**Pull request by semarie**
Fixes: #52029

### CODE REVIEW

**Comment by semarie** [comment]
The PR is against beta directly: nightly head has been corrected by 68620b14a29d0db5f3b857ed1bd7348092a15b14.

I edited `Cargo.toml` to change `[patch.crates-io]` to `[patch."https://github.com/rust-lang-nursery/rustfmt"]`
And run: `cargo update -p rustfmt-nightly`

**Comment by semarie** [comment]
cc @alexcrichton @Mark-Simulacrum @bugabinga

**Comment by semarie** [comment]
I updated `Cargo.toml` comment to match the change on nightly.

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by bugabinga** [comment]
@semarie 
> And run: cargo update -p rustfmt-nightly

what version of cargo was used at this point?
when I tried this myself locally, I got an error saying that the _-p_ flag is not supported on the version I was using (which was stable 1.27.0).

**Comment by semarie** [comment]
it was stable too (1.27.0).

**Comment by bugabinga** [comment]
> it was stable too (1.27.0).

Alright, I must've made some error elsewhere then.
Thanks for taking care of this.

**Pull request merged**
