### PR TITLE
Fix ICE that @steveklabnik encountered in rust-book.

### LINKED ISSUE #20644: ICE compiling rustbook
@steveklabnik's changes to rust-book encountered an ICE. I reduced it to this:

```
// A reduced version of the rustbook ice. The problem this encountered
// had to do with trans ignoring binders.

#![feature(slicing_syntax)]
#![feature(associated_types)]
#![feature(macro_rules)]

use std::iter;
use std::os;
use std::io::File;

#[allow(unused)]
pub fn parse_summary<R: Reader>(_: R, _: &Path) {
     let path_from_root = Path::new("");
     Path::new(iter::repeat("../")
               .take(path_from_root.components().count() - 1)
               .collect::<String>());
 }

fn main() {
    let cwd = os::getcwd().unwrap();
    let src = cwd.clone();
    let summary = File::open(&src.join("SUMMARY.md"));
    let _ = parse_summary(summary, &src);
}
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fix ICE that @steveklabnik encountered in rust-book. The problems turned out to be that were being very loose with bound regions in trans (we were basically just ignoring and flattening binders). Since binders are significant to subtyping and hence to trait selection, this can cause a lot of problems. So this patch makes us treat them more strictly -- for example, we propagate binders, and avoid skipping past the `Binder` by writing `foo.0`.

Fixes #20644.

r? @pcwalton

### CODE REVIEW

**Comment by steveklabnik** [comment]
:heart: :heart_eyes: :confetti_ball:

**Comment by steveklabnik** [comment]
This is blocking my work, so getting it shipped would make me a very happy camper.

**Comment by nikomatsakis** [comment]
(Passes make check locally.)

**Pull request merged**
