### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #98914 (Minimal implementation of implicit deref patterns for Strings)
 - #101162 (Migrate rustc_resolve to use SessionDiagnostic, part # 1)
 - <s>#102207 (Constify remaining `Layout` methods)</s>
 - #102977 (remove HRTB from `[T]::is_sorted_by{,_key}`)
 - #104047 (Diagnostics `icu4x` based list formatting.)
 - #104456 (update Miri)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=98914,101162,102207,102977,104047,104456)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+ p=5

Piggybacking some PRs on top of the p=1 https://github.com/rust-lang/rust/pull/104456

After this I plan to close the tree so the nevers can drain

**Comment by klensy** [comment]
Something broken here: rollup reverts some dependency versions, but i can't find which PR do this.

**Comment by Manishearth** [comment]
Yes, because the lockfile needed to be updated

**Comment by Manishearth** [comment]
@bors r+

fixed the lockfile, idk where the intermediate one came from

**Comment by klensy** [comment]
And now rollup description totally lies about it content. Maybe it's easier to rebuild it from scratch, instead of manually fixing stuff? IMHO

**Comment by Manishearth** [comment]
@klensy I'd already crossed out the relevant entry in the description?

I usually rebuild from scratch, but in this case I've closed the tree and I didn't want to reopen just so that this last rollup can be remade.

And the lockfile update was a necessary manual change; I'd have had to do it even if I remade the rollup. It's just that the first time I made that commit I had run `cargo check` instead of `x.py build` which generated an incorrect lockfile. So my manual commit at https://github.com/rust-lang/rust/commit/8e72bb6c1e08ef7a5053c193951485c034580971 wasn't the cause of the failure: it was just an incomplete fix.

**Comment by Manishearth** [comment]
Ah, good to know!

**Comment by Manishearth** [comment]
```
---- [mir-opt] src/test/mir-opt/deref-patterns/string.rs stdout ----
25	        _7 = const false;                // scope 0 at $DIR/string.rs:+3:9: +3:10
26	        _6 = move _1;                    // scope 0 at $DIR/string.rs:+3:9: +3:10
27	        _0 = const 4321_i32;             // scope 1 at $DIR/string.rs:+3:14: +3:18
-	        drop(_6) -> [return: bb6, unwind: bb12]; // scope 0 at $DIR/string.rs:+3:17: +3:18
+	        drop(_6) -> bb6;                 // scope 0 at $DIR/string.rs:+3:17: +3:18
29	    }
30	
31	    bb2: {

37	    }
38	
39	    bb3: {
-	        _4 = <str as PartialEq>::eq(_3, const "a") -> [return: bb4, unwind: bb12]; // scope 0 at $DIR/string.rs:+2:14: +2:17
+	        _4 = <str as PartialEq>::eq(_3, const "a") -> bb4; // scope 0 at $DIR/string.rs:+2:14: +2:17
41	                                         // mir::Constant
42	                                         // + span: $DIR/string.rs:9:14: 9:17
43	                                         // + literal: Const { ty: for<'a, 'b> fn(&'a str, &'b str) -> bool {<str as PartialEq>::eq}, val: Value(<ZST>) }

52	
53	    bb5: {
54	        _0 = const 1234_i32;             // scope 0 at $DIR/string.rs:+2:22: +2:26
-	        goto -> bb10;                    // scope 0 at $DIR/string.rs:+2:22: +2:26
+	        goto -> bb9;                     // scope 0 at $DIR/string.rs:+2:22: +2:26
56	    }
57	
58	    bb6: {

59	        StorageDead(_6);                 // scope 0 at $DIR/string.rs:+3:17: +3:18
-	        goto -> bb10;                    // scope 0 at $DIR/string.rs:+3:17: +3:18
+	        goto -> bb9;                     // scope 0 at $DIR/string.rs:+3:17: +3:18
61	    }
62	
63	    bb7: {

64	        return;                          // scope 0 at $DIR/string.rs:+5:2: +5:2
65	    }
66	
-	    bb8 (cleanup): {
-	        resume;                          // scope 0 at $DIR/string.rs:+0:1: +5:2
+	    bb8: {
+	        drop(_1) -> bb7;                 // scope 0 at $DIR/string.rs:+5:1: +5:2
69	    }
70	
71	    bb9: {

-	        drop(_1) -> [return: bb7, unwind: bb8]; // scope 0 at $DIR/string.rs:+5:1: +5:2
-	    }
-	
-	    bb10: {
-	        switchInt(_7) -> [false: bb7, otherwise: bb9]; // scope 0 at $DIR/string.rs:+5:1: +5:2
-	    }
-	
-	    bb11 (cleanup): {
-	        drop(_1) -> bb8;                 // scope 0 at $DIR/string.rs:+5:1: +5:2
-	    }
-	
-	    bb12 (cleanup): {
-	        switchInt(_7) -> [false: bb8, otherwise: bb11]; // scope 0 at $DIR/string.rs:+5:1: +5:2
+	        switchInt(_7) -> [false: bb7, otherwise: bb8]; // scope 0 at $DIR/string.rs:+5:1: +5:2
85	    }
86	}
87	
```

**Pull request closed without merging**
