### PR TITLE
Revert "Stabilize $$ in Rust 1.63.0"

### PR DESCRIPTION
**Pull request by CAD97**
This mechanically reverts commit 9edaa76adce4de737db54194eb13d6c298827b37, the one commit from #95860.

https://github.com/rust-lang/rust/issues/99035; the behavior of `$$crate` is potentially unexpected and not ready to be stabilized. https://github.com/rust-lang/rust/pull/99193 attempts to forbid `$$crate` without also destabilizing `$$` more generally.

@rustbot modify labels +T-compiler +T-lang +P-medium +beta-nominated +relnotes

(applying the labels I think are accurate from the issue and alternative partial revert)

cc @Mark-Simulacrum

### CODE REVIEW

**Comment by CAD97** [comment]
Trying again...

@rustbot modify labels +T-lang

**Comment by ehuss** [comment]
@CAD97 Can you also post a revert of https://github.com/rust-lang/reference/pull/1192 to the reference repo?

As for beta process, someone on the team first needs to mark this with the https://github.com/rust-lang/rust/labels/beta-accepted label. Then someone (usually on the release team, but anyone can post it) rolls up multiple beta-accepted PRs roughly once a week or two. https://forge.rust-lang.org/release/backporting.html contains more details.

**Comment by CAD97** [comment]
reference revert happened: https://github.com/rust-lang/reference/pull/1242

**Pull request merged**
