### PR TITLE
Move built-in syntax extensions to a separate crate

### PR DESCRIPTION
**Pull request by sanxiyn**
This reduces iteration time (`make rustc-stage1`) for moved syntax extensions from 11 minutes to 3 minutes on my machine.

Because of the signature change, this is a [breaking-change] for people directly calling `expand_crate`. I think it is rare: from GitHub search, only case I found is [glassful](https://github.com/kmcallister/glassful).

### CODE REVIEW

**Comment by sanxiyn** [comment]
Fixed all tests.

**Comment by nikomatsakis** [comment]
This looks good to me, though it needs a rebase.

**Comment by sanxiyn** [comment]
Rebased and marked the crate unstable.

**Pull request merged**
