### PR TITLE
Replace code of conduct with link

### PR DESCRIPTION
**Pull request by ghost**
This will replace the code of conduct and link to a single version at https://www.rust-lang.org/conduct.html
Fixes https://github.com/rust-lang/rust/pull/61531#issuecomment-501473787

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by BO41** [comment]
which other repositorys can need this change?
- embedded-book
- rust-by-example
- rustc-guide
- clippy
- rustfmt

**Comment by Mark-Simulacrum** [comment]
I'm going to @bors r+ rollup

I think other repositories can do this if they want, I'm not personally intending to approve those PRs if you file them as it's out of my purview :)

**Comment by therealprof** [comment]
You've removed the contact link to the responsible team, is that intended (i.e. is the Rust Moderation team responsible for handling CoC violations globally for all Rust initiatives)?

**Comment by Mark-Simulacrum** [comment]
No - I thought the text was the same between the website and this file. We should update the website if that's not the case.

**Comment by Mark-Simulacrum** [comment]
Not sure I follow you. If I'm understanding, that's one reason why I did not note here that making this change elsewhere may not be as clear-cut and I would not be able to approve it elsewhere.

**Comment by therealprof** [comment]
@Mark-Simulacrum 

I had the impression that you suggested that other repositories are invited to make the same change when you said:

> I think other repositories can do this if they want,

which stimulated my curiosity about whether the moderation team is willing to take the lead on handling CoC topics and complaints globally.

**Comment by Mark-Simulacrum** [comment]
Oh. I did not (and do not intend) to suggest any change to moderation team policies. I believe, but do not consider this official word, that we do not intend the moderation team to get involved in any non-official places (rust-lang org, and projects under it, are official places, I believe).

**Comment by therealprof** [comment]
Thanks for the clarification.

**Pull request merged**
