### PR TITLE
Use intra-doc links in `str` and `BTreeSet`

### LINKED ISSUE #32129: Broken links in `String` documentation from `Deref` impl
There are a bunch of links in the [`String` documentation](http://doc.rust-lang.org/nightly/std/string/struct.String.html) page which are broken. The reason for this is that most links are drawn from the documentation of the `str` type at `/std/primitive.str.html` but the `String` page is located at `/std/string/struct.String.html`. This mismatch in depth of paths causes a number of broken links, for example on the [`String::split`](http://doc.rust-lang.org/nightly/std/string/struct.String.html#method.split) method.

Not sure of the best way to fix this, but needs a tracking issue.

### LINKED ISSUE #32130: Broken links in BTreeSet struct documentation
There are broken links when looking at the `BTreeSet` structure. This happens because the structure can be viewed from two locations, both at varying depths of links so the relative links may or may not work:
- [`std::collections::BTreeSet`](http://doc.rust-lang.org/nightly/std/collections/struct.BTreeSet.html) - working
- [`std::collections::btree_set::BTreeSet`](http://doc.rust-lang.org/nightly/std/collections/btree_set/struct.BTreeSet.html) - not working

### PR DESCRIPTION
**Pull request by Manishearth**
Partial fix for #32129 and #32130

A _slight_ degradation in quality is that the `#method.foo` links would previously link to the same page on `String`'s documentation, and now they will navigate to `str`. Not a big deal IMO, and we can also try to improve that.

### CODE REVIEW

**Comment by Manishearth** [comment]
This was previously reviewed in https://github.com/rust-lang/rust/pull/74453

@bors r=jyn514

**Comment by jyn514** [comment]
@manishearth why did you open a new PR? AFAIK the concerns in https://github.com/rust-lang/rust/pull/74453#issuecomment-660400513 were never addressed.

@bors r-

cc @ehuss

**Comment by Manishearth** [comment]
@jyn514 I accidentally deleted some branches and then force pushed

It did not seem like those were blocking concerns. They cannot, at any rate, be fixed in this PR.

**Comment by jyn514** [comment]
> To be clear, it is better to fix the broken links on the String page, but I consider it a backstep in other regards that should (eventually) be fixed.

Hmm ... Would it makes sense to use intra-doc links only for things that aren't primitives? Or is it not possible to use relative links because this module is re-exported in both std and core?

**Comment by Manishearth** [comment]
> Hmm ... Would it makes sense to use intra-doc links only for things that aren't primitives?

This wouldn't fix the original problem though. Note that it's not just primitives, it's methods of primitives, etc.

**Comment by jyn514** [comment]
Ok I misunderstood what happened - currently these links work in libcore but are broken in libstd. This PR makes it so they work in both crates, but link externally from libcore (they'll go to rust-lang.org/nightly). The second bit is unfortunate but IMO better than the status quo.

We should open an issue about the primitives, this has popped up a few different times now.

@bors r+

**Comment by Manishearth** [comment]
@jyn514 I was starting to draft an issue about the primitives, but I remembered that there may not be a solution here because primitives do not exist in docs before std. The code that makes this an external link is _deliberately_ written to handle this case.

**Comment by jyn514** [comment]
@manisheart why are primitives in libstd and not libcore? That seems weird.

**Comment by Manishearth** [comment]
(https://github.com/rust-lang/rust/issues/73423 btw, cc @ehuss)

**Comment by ollie27** [comment]
> Fixes #32129, fixes #32130

Those issues can't be closed until the exceptions in linkchecker are removed:

https://github.com/rust-lang/rust/blob/d3df8512d2c2afc6d2e7d8b5b951dd7f2ad77b02/src/tools/linkchecker/main.rs#L122-L127 and https://github.com/rust-lang/rust/blob/d3df8512d2c2afc6d2e7d8b5b951dd7f2ad77b02/src/tools/linkchecker/main.rs#L132-L141

**Comment by Manishearth** [comment]
@ollie27 hmm. Unfortunately not all of those exceptions can be removed, because some of the links are forward references, which is out of scope for intra doc links

**Comment by Manishearth** [comment]
@ollie27 would you be okay if we can land this, fixing _most_ of the cases, and unregistering the concern on intra doc stabilization?

**Comment by Manishearth** [comment]
@bors r=jyn514

removed the "fixes foo" keyword from the PR body

**Pull request merged**
