### PR TITLE
Include adjustments to allow unsizing coercions for raw slice pointers in receiver position

### LINKED ISSUE #74679: Missing unsizing coercions for raw slice pointers
With https://github.com/rust-lang/rust/pull/73986 having landed, one would expect something like this to work:
```rust
#![feature(raw_ref_op)]
#![feature(slice_ptr_get)]

struct S {
    keys: [i32; 2],
}

unsafe fn get_last(s: *const S) -> i32 {
    let keys = &raw const (*s).keys;
    *keys.get_unchecked(1)
}

fn main() {
    let s = S { keys: [24, 42] };
    let p = &raw const s;
    assert_eq!(unsafe { get_last(p) }, 42);
}
```
However, this fails saying
```
error[E0599]: no method named `get_unchecked` found for raw pointer `*const [i32; 2]` in the current scope
  --> src/main.rs:11:11
   |
11 |     *keys.get_unchecked(1)
   |           ^^^^^^^^^^^^^ method not found in `*const [i32; 2]`
   |
   = note: try using `<*const T>::as_ref()` to get a reference to the type behind the pointer: https://doc.rust-lang.org/std/primitive.pointer.html#method.as_ref
   = note: using `<*const T>::as_ref()` on a pointer which is unaligned or points to invalid or uninitialized memory is undefined behavior
```
One has to add a `*const [_]` type annotation to force an unsizing coercion for this to work.

### PR DESCRIPTION
**Pull request by b-naber**
Tries to fix https://github.com/rust-lang/rust/issues/74679

This change would allow calling methods defined for raw slice pointers directly on raw array pointers. The current implementation might have some problems, the idea is to insert adjustments for raw pointers in receiver position if the receiver type is a raw array pointer and a method candidate has a raw slice pointer as its self_ty. This could possibly be problematic, since we implicitly deref a raw pointer. However, currently the only methods that allow this type of unsizing coercion are unsafe, but we might need to only allow these types of coercions for unsafe methods in general. 

cc @RalfJung

### CODE REVIEW

**Comment by oli-obk** [comment]
I am surprised we need this much work inside the compiler. I thought unsizing had impls in libcore. I can try to review this, but I have little knowledge about the coercion part of typeck. It just feels suprising to me to have special cases added on top of the existing infrastructure.

cc @rust-lang/lang This adds a new unsizing coercion for raw pointers

**Comment by b-naber** [comment]
The title was probably poorly chosen. What we do here is not actually the unsizing itself, but rather we just adjust the self_ty in a way that allows method candidate search to find the right method. The correct method candidate is generated for a self_ty of type [_], because the compiler previously didn't allow deref adjustments for raw pointers, we had to include this (in `autoderef_self_ty`). But then we also have auto autoref this deref'd self_ty again, but the compiler previously only did this for references not raw pointers. We limit these raw pointer to adjustments to the case when we're dealing with raw array pointers and the generated candidate is a slice.

**Comment by oli-obk** [comment]
Ah, that does make more sense, thanks!

The artificial limitation to array->slice unsizings could go away entirely if we wanted to, right? There's no inherent limitation since any unsizing operation doesn't actually look at the pointer to the concrete type.

I can review the implementation, but this needs sign-off from the lang team

**Comment by b-naber** [comment]
> The artificial limitation to array->slice unsizings could go away entirely if we wanted to, right? There's no inherent limitation since any unsizing operation doesn't actually look at the pointer to the concrete type.

Ok cool, I didn't know that the unsizing operation doesn't look at the pointer. This would alleviate the safety concerns with the implementation and we could implement this in general and not just for array->slice unsizings.

**Comment by b-naber** [comment]
@oli-obk I'm not sure I understand what kind of unsize operations you expect this to work for. Currently in method resolution when the compiler generates autoderef steps it uses an `unsafe` flag only if the `final_ty` is an `Array` (this is done [here in `method_autoderef_steps`](https://github.com/rust-lang/rust/blob/8599bff5a3556059817503030e248507706e96b4/compiler/rustc_typeck/src/check/method/probe.rs#L481-L494)). But the compiler e.g. doesn't use adjustments that take into account `CoerceUnsized` implementations. Can you explain in what other situations you would expect this to work besides array -> slice unsizings?

**Comment by oli-obk** [comment]
I think I am confusing this situation with a very similar one. The example I was thinking of is

```rust
#![feature(raw_ref_op)]

trait Foo {
}

impl Foo for i32 {
}

trait Bar: Sized {
    fn bar(self) {}
}

impl Bar for *const dyn Foo {
    fn bar(self) {}
}

fn main() {
    let x = 42_i32;
    let y = &raw const x;
    y.bar();
    let z: *const dyn Foo = y;
    z.bar();
}
```

but I do see that it is not *exactly* the same as the situation for slices here, since that is for inherent impls on raw pointers to slices instead of trait impls.

**Comment by RalfJung** [comment]
> any unsizing operation doesn't actually look at the pointer to the concrete type

That's true *right now* but might stop being true with user-defined DST.

**Comment by crlf0710** [comment]
Triage: Added `needs-fcp` label since this needs sign-off from the lang team.

**Comment by crlf0710** [comment]
Triage: Added `needs-fcp` label since this needs sign-off from the lang team.

**Comment by Mark-Simulacrum** [comment]
Waiting on Niko before lang team discussion.

**Comment by nikomatsakis** [comment]
Hi @b-naber, @RalfJung et al.--

Sorry for being slow on this PR. I have some questions! If I understand correctly, this PR is modifying method dispatch to add a kind of special case. I guess the first question is, why doesn't the unsizing impl apply? I guess because it would have to deref a raw pointer?

**Comment by crlf0710** [comment]
@b-naber Ping from triage, could you answer the question above here, or create a topic on zulip to discuss this further? thanks!

**Comment by crlf0710** [comment]
@b-naber Ping from triage, any updates on this?

**Comment by crlf0710** [comment]
@b-naber  Ping from triage, any updates on this?

**Comment by crlf0710** [comment]
@b-naber Triage: I'm gonna close this due to inactivity. Feel free to reopen or create a new pr when you've got time to work on this again. Thanks!

**Pull request closed without merging**
