### PR TITLE
fix infinite recursion on complex traits

### LINKED ISSUE #39959: error[E0275]: overflow evaluating the requirement `_: std::marker::Sized`
Reduced test case:

```rust
#![recursion_limit = "5"]

fn main() {}

trait Serialize {}

struct Ser<'a, T: 'a>(&'a T);

impl<'a, T> Ser<'a, T> where Ser<'a, T>: Serialize {
    pub fn new(value: &'a T) -> Self {
        Ser(value)
    }
}

impl<'a, T> Serialize for Ser<'a, Option<T>> where Ser<'a, T>: Serialize {}

fn serialize<'a, T>(value: &'a T) where Ser<'a, T>: Serialize {
    Ser::new(value);
}
```

Output in rustc 1.17.0-nightly (536a900c4 2017-02-17):

```rust
error[E0275]: overflow evaluating the requirement `_: std::marker::Sized`
  --> a.rs:20:5
   |
20 |     Ser::new(value);
   |     ^^^^^^^^
   |
   = note: consider adding a `#![recursion_limit="10"]` attribute to your crate
   = note: required because of the requirements on the impl of `Serialize` for `Ser<'_, std::option::Option<_>>`
   = note: required because of the requirements on the impl of `Serialize` for `Ser<'_, std::option::Option<std::option::Option<_>>>`
   = note: required because of the requirements on the impl of `Serialize` for `Ser<'_, std::option::Option<std::option::Option<std::option::Option<_>>>>`
   = note: required because of the requirements on the impl of `Serialize` for `Ser<'_, std::option::Option<std::option::Option<std::option::Option<std::option::Option<_>>>>>`
   = note: required because of the requirements on the impl of `Serialize` for `Ser<std::option::Option<std::option::Option<std::option::Option<std::option::Option<std::option::Option<_>>>>>>`

error: aborting due to previous error
```

Without `#![recursion_limit = "5"]`, the error message is similar but much larger. If this isn’t a bug, at least the diagnostic should be improved.

### PR DESCRIPTION
**Pull request by joonazan**
Fixes #39959.

As I explained in the issue, evaluate_stack in rustc_trait_selection::traits::select attempts to prevent infinite recursion when inferring types that satisfy traits but fails to do so. I got the details wrong, though.

The code previously only checked for cases like $0: Eq, $1: Eq, etc. Now it also works in cases where the type variables are buried in some
data structure, like Union<$0, $1>: Eq.

This should fix all the errors reported in the issue. It fixes my instance of the problem, at least.

There is another class of problem it does not fix: infinite recursion that never repeats the same pattern. Avoiding that one would require exploring the options in a BFS manner or using bounded DFS. I haven't heard of this happening in practice but it could be that people who would have run into it were too discouraged by this bug.

I should probably add some test for this. Where would I do that?

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? types

**Comment by joonazan** [comment]
The first commit flagged things that weren't infinite recursion as such but after the second commit cases of infinite recursion are missed. I'll try to figure out how to make it just right tomorrow.

**Comment by estebank** [comment]
Can you add a test for this?

**Comment by joonazan** [comment]
@estebank I would like to add a test but I don't know where to add it. Where are tests generally located?

My first commit flagged too many things as infinite recursion while the second one is too strict (which is what causes the typenum regression).

It would be an improvement to detect infinite recursion if the old logic or the logic of the second commit detects it but it would affect performance. I'm looking for a more satisfying solution but I guess I should commit that solution to see if it avoids regressions.

**Comment by estebank** [comment]
You'll want to add a file somewhere in `src/test/ui`, likely in an appropriate subdirectory (you might have to create one), and then run `python x.py test src/test/ui --bless` to create/update the `.stderr` files.

**Comment by spastorino** [comment]
r? types

**Comment by compiler-errors** [comment]
This needs more investigation for the failing tests. Marking this as waiting-on-author, please comment `@rustbot ready` when it's ready for review. Feel free to reach out on the `T-types` or `T-compiler/help` zulip streams if you need help!

@rustbot author

**Comment by jackh726** [comment]
@joonazan any updates here? Do you need any help moving investigating the failing tests?

**Comment by joonazan** [comment]
@jackh726 I tried to make a correct but slow version of the code but it was so slow that it wasn't able to run the tests. It looks like it would require a big rewrite to make a version that is as good as possible but not ridiculously slow.

So yeah, the next step would be to go through each of the ICE caused by the new version to figure out if it is incorrect or if some other code that just happened to work with the old code needs to be fixed as well.

I lost motivation when I reached that point. I want to finish this but I don't have much free time currently, so I don't know when.

**Comment by Dylan-DPC** [comment]
@joonazan any updates on this?

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
