### PR TITLE
Make hitting the recursion limit in projection non-fatal

### PR DESCRIPTION
**Pull request by matthewjasper**
This change was originally made in #80246 to avoid future (effectively) infinite loop bugs in projections,
but wundergraph relies on rustc recovering here.

cc #80953 

r? @nikomatsakis

### CODE REVIEW

**Comment by jyn514** [comment]
I wonder if this would help with https://github.com/rust-lang/rust/issues/79459.

**Comment by jyn514** [comment]
See also https://github.com/rust-lang/rust/pull/79517.

**Comment by jyn514** [comment]
It does not fix https://github.com/rust-lang/rust/issues/79506, because that gives an error in `check_recursion_limit` instead, which wasn't modified here: https://github.com/rust-lang/rust/blob/5db5d8f87e2d224df6feea200af371d13394f2be/compiler/rustc_trait_selection/src/traits/select/mod.rs#L953-L960

@matthewjasper should that match be changed too?

**Comment by matthewjasper** [comment]
This change already isn't really correct, it's just the safest fix for a backport.

For rustdoc it would make sense to move reporting recursion limit errors outside of the trait system, but that's not what this change does (this change incorrectly allows the trait system to recover from recursion limit errors).

**Comment by jyn514** [comment]
> For rustdoc it would make sense to move reporting recursion limit errors outside of the trait system, but that's not what this change does 

Got it, thanks. Do you have suggestions for moving recursion limit errors out of the trait system? I'd be interested in working on it.

**Comment by matthewjasper** [comment]
It's basically find all of the places that create a `OverflowError` or `SelectionError::Overflow` and make sure that they are always early returned until outside of `rustc_trait_selection::traits::{select, project}`, at which point they should be emitted. Overflow errors should never be converted to any other kind of error (such as `EvaluatedToRecur` or `EvaluatedToError`)

**Comment by Mark-Simulacrum** [comment]
beta-nom label should not have been removed, see https://forge.rust-lang.org/release/beta-backporting.html -- can we add this to wg-prioritization docs perhaps? I think we're not highlighting those docs enough or they are confusing perhaps?

**Comment by apiraino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/45386weeklymeeting2021012854818.html#224340802) in T-compiler meeting, declined to backport to stable

@rustbot modify labels: -stable-nominated

**Comment by Aaron1011** [comment]
> this change incorrectly allows the trait system to recover from recursion limit errors

@matthewjasper Is there an open issue for applying the correct fix?

**Pull request merged**
