### PR TITLE
Implement CoerceUnsized for rc::Weak

### LINKED ISSUE #26704: CoerceUnsized isn't implemented for rc::Weak
```rust
#![feature(rc_weak)] 

use std::rc::{ Rc, Weak };
use std::cell::RefCell;

trait Barker {
  fn bark(&self);
}

struct Dog {
  x: i32,
  y: i32,
}

impl Barker for Dog {
  fn bark(&self) {
    println!("bark")
  }
}

fn speak_weak(barker: Weak<RefCell<Barker>>) {
  let b = barker.upgrade().unwrap();
  let c = b.borrow();
  c.bark();
}

fn speak_rc(barker: Rc<RefCell<Barker>>) {
  let b = barker.clone();
  let c = b.borrow();
  c.bark();
}

fn main() {
  let dog = Rc::new(RefCell::new(Dog { x: 0, y: 0 }));
  
  // works
  speak_rc(dog.clone() as Rc<RefCell<Barker>>);
  
  // doesn't work
  speak_weak(dog.downgrade() as Weak<RefCell<Barker>>);
}
```

```
<anon>:41:14: 41:54 error: non-scalar cast: `alloc::rc::Weak<core::cell::RefCell<Dog>>` as `alloc::rc::Weak<core::cell::RefCell<Barker>>`
<anon>:41   speak_weak(dog.downgrade() as Weak<RefCell<Barker>>);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```

```
rustc --version --verbose[system][~][::] $ rustc --version --verbose
rustc 1.3.0-nightly (faa04a8b9 2015-06-30)
binary: rustc
commit-hash: faa04a8b9c326bb71b1d21e962dd96912ce234c6
commit-date: 2015-06-30
host: x86_64-apple-darwin
release: 1.3.0-nightly
```

### PR DESCRIPTION
**Pull request by remram44**
This is a simple addition, shouldn't change behavior.

Fixes #26704

I don't know if the coercion for `Rc` is tested, if it is this probably needs the same test with `Weak`.

### CODE REVIEW

**Comment by eddyb** [comment]
Could probably do the same thing for `arc::Weak`. Tests are in `src/test/run-pass/dst-coerce-rc.rs`.

**Comment by remram44** [comment]
I feel like dst-coerce-rc.rs is more about testing the CoerceUnsized feature than checking it is implemented for the right types, but here you go.

**Comment by eddyb** [comment]
Thanks! @bors r+

**Comment by BigBoneDaddy** [comment]
@remram44 Good jobs!

**Pull request merged**
