### PR TITLE
Make miri value visitor useful for mutation

### PR DESCRIPTION
**Pull request by RalfJung**
~~This is based on top of https://github.com/rust-lang/rust/pull/55716, [click here](https://github.com/RalfJung/rust/compare/escape-to-raw...RalfJung:mut-visitor) for just the new commits.~~

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
r=me with other PR merged

**Comment by RalfJung** [comment]
@oli-obk I added [another commit here](https://github.com/rust-lang/rust/pull/55916/commits/a7b312f8255db978f0446cf62383402fee02bae3), a hopefully final change to the "base" model before adding barriers.

**Pull request merged**
