### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
cc @y21  ^

**Comment by y21** [comment]
ah... yea that `mixed_attributes_style` file should be using `Lrc` and not the aliased type `Arc`, I missed that in code review, oops.

Can I just commit a quick fix here to unblock this or will that break things? Subtree PRs are always scary

**Comment by matthiaskrgr** [comment]
if you can push onto the pr, I think it should work? :sweat_smile:

**Comment by y21** [comment]
Sad that our CI didn't catch this. I guess we're only testing the distributed parallel librustc where `type Lrc = Arc`.
I wonder if there's any good lint we have that we could make use of to deny using `Arc` directly where an `Lrc` is expected (there's `disallowed_types` but I don't know if banning `Arc` entirely is too strong).

**Comment by flip1995** [comment]
> I wonder if there's any good lint we have that we could make use of to deny using `Arc` directly where an `Lrc` is expected to prevent this from happening (there's `disallowed_types` but I don't know if banning `Arc` entirely in clippy is too strong).

Those are the only `use` statements for `Rc` and `Arc` in Clippy:
```
$ rg "use.*Rc" clippy*
clippy_utils/src/macros.rs
15:use std::rc::Rc;

clippy_lints/src/utils/format_args_collector.rs
12:use std::rc::Rc;

$ rg "use.*Arc" clippy*
clippy_lints/src/attrs/mixed_attributes_style.rs
8:use std::sync::Arc;
```

The `Arc` one was removed in this PR. For the `Rc` instances, I tried to replacing them with `Lrc` and it just worked. So I would welcome an internal lint that forbids `Arc` and `Rc` and suggests `Lrc`. Similar to our lint about `HashMap` vs `FxHashMap`.

**Comment by flip1995** [comment]
```
error: usage of an `Arc` that is not `Send` and `Sync`
  --> src/utils/format_args_collector.rs:31:54
   |
31 |                 .insert(expr.span.with_parent(None), Lrc::new((**args).clone()));
   |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `Arc<FormatArgs>` is not `Send` and `Sync` as:
   = note: - the trait `Send` is not implemented for `FormatArgs`
   = note: - the trait `Sync` is not implemented for `FormatArgs`
   = help: consider using an `Rc` instead. `Arc` does not provide benefits for non `Send` and `Sync` types
   = note: if you intend to use `Arc` with `Send` and `Sync` traits
   = note: wrap the inner type with a `Mutex` or implement `Send` and `Sync` for `FormatArgs`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
   = note: `-D clippy::arc-with-non-send-sync` implied by `-D clippy::all`
   = help: to override `-D clippy::all` add `#[allow(clippy::arc_with_non_send_sync)]`
```

Well except for this dogfood failure. But we could just allow that lint in this case.

**Pull request merged**
