### PR TITLE
Update runtime guarantee for `select_nth_unstable`

### PR DESCRIPTION
**Pull request by Sp00ph**
#106933 changed the runtime guarantee for `select_nth_unstable` from O(n) to O(n log n), since the old guarantee wasn't actually met by the implementation at the time. Now with #107522, `select_nth_unstable` should be truly linear in runtime, so we can revert its runtime guarantee to O(n). Since #106933 was considered a bug fix, this will probably need an FCP because it counts as a new API guarantee.

r? @Amanieu

### CODE REVIEW

**Comment by Sp00ph** [comment]
Woops

@rustbot label +T-libs-api -T-libs

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by n3vu0r** [comment]
Haven't you missed `select_nth_unstable_by_key`?

**Comment by Sp00ph** [comment]
Indeed, don't know how I missed that. Gonna have to file a follow up PR for #111973 too as I also missed it there.

**Pull request merged**
