### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #92360 (Some cleanups around check_argument_types)
 - #92389 (Regression test for borrowck ICE #92015)
 - #92443 (Rustdoc: resolve associated traits for non-generic primitive types)
 - #92490 (Move crate drop-down to search results page)
 - #92535 (Allow unwinding from OOM hooks)
 - #92568 (Add note about non_exhaustive to variant_count)
 - #92589 (Break the loop)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=92360,92389,92443,92490,92535,92568,92589)

### CODE REVIEW

**Comment by mati865** [comment]
FYI https://github.com/rust-lang/rust/pull/92589 has been `r-`

**Comment by matthiaskrgr** [comment]
It was just r+ed again.. ^^

**Pull request closed without merging**
