### PR TITLE
Add a message for if an overflow occurs in `core::intrinsics::is_nonoverlapping`.

### PR DESCRIPTION
**Pull request by nullptrderef29**

### CODE REVIEW

**Comment by scottmcm** [comment]
Since this does something different, can you elaborate on why this is better?  Is there a test that should be added?

**Comment by JohnBobbo96** [comment]
I just kind of wanted to get rid of the `unwrap`, but i can close this if it is better to panic here (maybe add a panic message indicating overflow?), or i could also add some sort of test.

**Comment by JohnBobbo96** [comment]
maybe something like this?
```rust
    let size = mem::size_of::<T>()
        .checked_mul(count)
        .expect("is_nonoverlapping: size_of::<T>() * count overflows a usize");
```

**Comment by the8472** [comment]
`is_nonoverlapping` is only used in debug asserts, so making the error explicit (overflow is an error here) is fine.

**Comment by JohnBobbo96** [comment]
I have changed it to be an explicit error message on overflow.

**Pull request merged**
