### PR TITLE
Fix #[track_caller] and function pointers

### LINKED ISSUE #68178: Calling unwind via function pointer leads to odd panic message
I was playing around with function pointers to `track_caller` methods (which [doesn't seem entirely implemented yet](https://github.com/rust-lang/rust/pull/65182#issuecomment-573649550)) and arrived at the following testcase:
```rust
fn call_it<T>(f: fn(T), x: T) {
    f(x);
}

fn main() {
    call_it(Result::unwrap, Err(0));
}
```
On stable, this behaves as expected:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 0', src/libcore/result.rs:1165:5
```
On the latest nightly though, the message is different:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libstd/panicking.rs:369:15
```
The line number points at this:
https://github.com/rust-lang/rust/blob/af958046e5855a4254831102b502f57dafa40f69/src/libstd/panicking.rs#L369

Two things seem odd here for me:
* I am actually surprised that this does not ICE, given that the `ReifyShim` stuff does not seem entirely implemented (at least [this test](https://github.com/rust-lang/rust/pull/65182/commits/b8414c13abf9dc994f9c0dccee848a8b0fb1b061#diff-576c0bfe42a59f60c74b63e865d59d1d) still ICEs).
* But the actual main bug here is that the comment about "always returns Some" seems wrong, so this panics at the wrong place. Clearly, the message shouldn't talk about `Option::unwrap()` when the actual panic is caused by a `Result::unwrap`.

Cc @anp

### PR DESCRIPTION
**Pull request by anp**
Starting with failing tests, fix the miscompilation and ICE caused by `ReifyShim` bug.

Fixes #68178.

### CODE REVIEW

**Comment by anp** [comment]
@eddyb thanks for the help with `ReifyShim`! Both of the bugs surfaced by @RalfJung have repro cases that pass for me now. Will see what CI says, can you do a quick review?

**Review by eddyb — APPROVED** [review]
r=me after someone else reviews my commit (e.g. @oli-obk or @RalfJung)

**Comment by RalfJung** [comment]
Great, these will be interesting test-cases for Miri :D (and I might need help to implement the shim in Miri)

I can't help with review though I'm afraid, I don't think I ever saw any of the involved code.

**Pull request merged**
