### PR TITLE
ci: allows files to be shared by docker images

### PR DESCRIPTION
**Pull request by malbarbo**
Change `src/ci/docker/run.sh` to allow files to be shared when building docker containers. For while, only android related shell scripts are shared. Others containers can be updated at any time.

sccache is installed last, as it is frequently updated this avoids the need to rebuilt the whole container.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! A few thoughts here:

* Could you update the `README.md` in the directory with a short explanation of the new filesystem layout? Basically that all containers have access to all these scripts and such.
* Could you go ahead and remove the "old way" of building a container? I'd prefer to not maintain a whole bunch of methods of building the containers, although having a "disabled" and "not disabled" path seems ok (at maximum). This'll involve updating the `COPY` paths of existing containers, but I think that's ok, we can deduplicate those scripts later.
* After this lands, mind opening up an issue to continue to deduplicate these scripts? I'm thinking things like `hide_output` as well as installing sccache would be great candidates.
* For now could this avoid deduplicating the apt-get install phases? I've found that to be ever-so-subtly different across all the containers so I'm hesitant to start trying to extract subsets again.

**Comment by malbarbo** [comment]
Done. Let's travis tests with I missed some Dockerfile update.

**Comment by alexcrichton** [comment]
@bors: r+

Looks great, thanks so much for this @malbarbo!

**Comment by malbarbo** [comment]
Fixed dist-powerpc-linux

**Comment by alexcrichton** [comment]
@bors: retry

* [appveyor network issues](https://appveyor.statuspage.io/incidents/2g5jnq5cy1g1) #40474

**Pull request merged**
