### PR TITLE
Change compare_exchange to return a Result<T, T>

### PR DESCRIPTION
**Pull request by Amanieu**
As per the discussion in #31767

I also changed the feature name from `extended_compare_and_swap` to `compare_exchange`.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks @Amanieu! From a technical perspective the change looks good to me, just a question of APIs now! I'm tagging this with `T-libs` to ensure it comes up during triage.

So I originally thought that this may make the classical "compare exchange loop" a little less ergnomic as getting the value out would require `unwrap_or_else` or something like that, but when I write them down...

current:

```rust
loop {
    let new = f(current);
    let old = foo.compare_exchange(current, new, ord1, ord2);
    if old == current {
        break
    }
    current = old;
}
```

new:

```rust
loop {
    let new = f(current);
    match foo.compare_exchange(current, new, ord1, ord2) {
        Ok(..) => break,
        Err(old) => current = old,
    }
}
```

I gotta say using `match` here seems quite appealing to me!

To get a handle on the ergonomics though it may be worthwhile to port a project like crossbeam to using this API instead of the old one (just as a smoke test)

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the conclusion was that this seems like a good change to have! It was brought up though that we may not want to change the feature names as that's kinda unnecessary breakage, would you be ok changing back?

**Comment by Amanieu** [comment]
Done

**Comment by Amanieu** [comment]
Fixed

**Comment by eddyb** [comment]
@alexcrichton This will have to wait until #32080 is merged, btw.

**Comment by Amanieu** [comment]
I think this should be fixed now

**Comment by Amanieu** [comment]
Fixed.

Note that it seems atomic intrinsics currently don't work on non-integer types, this should be properly fixed at some point...

**Pull request merged**
