### PR TITLE
build std for sparc64-unknown-linux-gnu

### PR DESCRIPTION
**Pull request by japaric**
r? @alexcrichton

panicking / unwinding is broken (#39646) but with std available at least people
will be able to debug that issue on real hardware

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can you also update src/tools/build-manifest to include this target? Otherwise looks great!

**Comment by japaric** [comment]
@alexcrichton Like so?

**Comment by alexcrichton** [comment]
I believe so!

@bors: r+

**Comment by sunnystormy** [comment]
Don't mean to necro this, but if I were to use the Nightly version of Rust, would I have access to this feature? Also, How soon will this make it over to Stable?

Thanks!

**Comment by alexcrichton** [comment]
@sunnystormy you can access this *right now* via:

```
rustup target add sparc64-unknown-linux-gnu --toolchain nightly
```

**Comment by sunnystormy** [comment]
@alexcrichton Thank you, sir! Works like a charm. :smile_cat:

**Pull request merged**
