### PR TITLE
cache evaluation results

### PR DESCRIPTION
**Pull request by arielb1**
This fixes an exponential worst-case and also provides an additional 1% perf improvement.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
:fireworks:

**Comment by nikomatsakis** [comment]
@arielb1 sorry, been at a conference, will get to this soon

**Comment by nikomatsakis** [comment]
@arielb1 

> OutputTypeParameterMismatch improves error reporting somewhat.

Yes, I know. This is the main reason I didn't rip it out a while back.

**Comment by arielb1** [comment]
@nikomatsakis 

I will deal with the fat errors on a later PR (this one is getting somewhat too big).

**Comment by arielb1** [comment]
<updated>

**Comment by nikomatsakis** [comment]
OK, I'm feeling pretty good about this patch. r+ from me with that comment. Nice work!

**Pull request merged**
