### PR TITLE
Implement cursors for BTreeMap

### PR DESCRIPTION
**Pull request by Amanieu**
See the ACP for an overview of the API: https://github.com/rust-lang/libs-team/issues/141

The implementation is split into 2 commits:
- The first changes the internal insertion functions to return a handle to the newly inserted element. The lifetimes involved are a bit hairy since we need a mutable handle to both the `BTreeMap` itself (which holds the root) and the nodes allocated in memory. I have tested that this passes the standard library testsuite under miri.
- The second commit implements the cursor API itself. This is more straightforward to follow but still involves some unsafe code to deal with simultaneous mutable borrows of the tree root and the node that is currently being iterated.

### CODE REVIEW

**Review by m-ou-se — APPROVED** [review]
r=me after adding [a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX).

**Comment by Amanieu** [comment]
Added tracking issue #107540

r=m-ou-se

**Comment by jeffparsons** [comment]
Does this need an explicit bors r+?

(Not sure how Bors interacts with GitHub reviews, if at all.)

**Pull request merged**
