### PR TITLE
Add TryFrom, TryInto, FromIterator to the v1 prelude

### PR DESCRIPTION
**Pull request by djc**
This is a test PR which I'd like to get a crater run for, as input to the [2021 prelude RFC](https://github.com/rust-lang/rfcs/pull/3090). Please don't merge!

### CODE REVIEW

**Comment by djc** [comment]
PR for minifier here: https://github.com/GuillaumeGomez/minifier-rs/pull/65.

**Comment by m-ou-se** [comment]
What's the status of this?

**Comment by djc** [comment]
Status: this appears to be breaking some usage inside doctests, which appears to deny warnings by default (at least that is what is happening in the alloc crate). I've just pushed another change to fix that, so I'll see what else happens.

**Comment by djc** [comment]
How can I get CI to run on this again?

**Comment by m-ou-se** [comment]
Note that for a crater run we only need a `try` build, which doesn't run any tests. So even if the CI on the PR fails, we can still continue as long as rustc builds.

**Comment by m-ou-se** [comment]
@craterbot check

**Comment by m-ou-se** [comment]
@rust-lang/infra Crater is stuck on generating the report. ^

**Comment by Mark-Simulacrum** [comment]
@craterbot retry-report

**Comment by m-ou-se** [comment]
Yay, we finally have a report.

As expected, lots of stuff breaks, which is why this needs to happen over an edition change.

Next step: Use this crater report to make a migration plan. We now have plenty of examples in which ways things break, and we can use this to come up with a migration lint that covers all/most of these cases. (This is a regular [lint](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/context/trait.LintContext.html#method.struct_span_lint) that can be run on Rust 2018 code and comes with a [`MachineApplicable`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint_defs/enum.Applicability.html#variant.MachineApplicable) [suggestion](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/diagnostic/struct.Diagnostic.html#method.span_suggestion) to convert the code to something that compiles in both Rust 2018 and Rust 2021.) We don't need an implementation of this lint right now, but we do need a plan of what exactly this lint will detect and what it will suggest.

**Comment by JohnCSimon** [comment]
this seems to still be in progress 
@Rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by bstrie** [comment]
I believe this PR can be closed, since it was just for crater and it has been decided that these changes require an edition.

**Pull request closed without merging**
