### PR TITLE
Make json test output formatter represent "test_count" as num

### LINKED ISSUE #53866: Json test output formatter should represents "test_count" as a json string instead of a number
The output of a test suite starting when using the json formatter represents "test_count" as a json string, like so:
```json
{ "type": "suite", "event": "started", "test_count": "1" }
```
I would expect it to be a number like this:
```json
{ "type": "suite", "event": "started", "test_count": 1 }
```

### PR DESCRIPTION
**Pull request by cwndrws**
fixes #53866

### CODE REVIEW

**Comment by sfackler** [comment]
What downstream code consumes this format? Is this a backwards compatibility concern?

**Comment by cwndrws** [comment]
@sfackler I'm working on a tool that consumes this. It's not backwards compatibility concern. It just seems wrong.

**Comment by zackmdavis** [comment]
@sfackler 

> Is this a backwards compatibility concern?

This JSON output format for tests (note, this is different from `--error-format json` for diagnostics; I was confused at first) seems to have been [introduced in December](https://github.com/rust-lang/rust/pull/46450) after the dev-tools team [decided that no RFC was needed to land it](https://github.com/rust-lang/rfcs/pull/2234#issuecomment-351263608). That sounds like we haven't made any stability promises yet.

**Comment by nrc** [comment]
cc @djrenren thoughts on this?

**Comment by nrc** [comment]
I don't think anyone is using the JSON test output. cc @vlad20012 - does IntelliJ use it?

**Comment by djrenren** [comment]
Hmm looked through the intellij rust repo and didn't see any references to it. Could be totally fine.

**Comment by vlad20012** [comment]
> does IntelliJ use it?

Not really. We have a PR, but it is not merged yet. So, it's not a problem for us.

**Pull request merged**
