### PR TITLE
resolve: Fix an ICE in import validation

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes ICE reported in the comment https://github.com/rust-lang/rust/issues/56596#issuecomment-449866807

### CODE REVIEW

**Comment by petrochenkov** [comment]
Beta-nominating as a regression fix, the assert was introduced in stable Rust 1.31 (in https://github.com/rust-lang/rust/pull/55884).

**Comment by pietroalbini** [comment]
This doesn't apply to beta @petrochenkov:

```
error[E0609]: no field `blacklisted_binding` on type `&mut Resolver<'a, 'crateloader>`resolve                                                                                                                                                                           
   --> src/librustc_resolve/resolve_imports.rs:242:57
    |
242 |                 if let Some(blacklisted_binding) = self.blacklisted_binding {
    |                                                         ^^^^^^^^^^^^^^^^^^^
```

**Comment by petrochenkov** [comment]
Turns out https://github.com/rust-lang/rust/pull/56392/commits/c658d7340149274bb30a56fb3e7de799c266f4bc is a prerequisite.

It's also a prerequisite for https://github.com/rust-lang/rust/pull/56759, so there's a good chance that it'll need to be backported anyway.

**Comment by petrochenkov** [comment]
Included into https://github.com/rust-lang/rust/pull/57483

**Pull request merged**
