### PR TITLE
rustdoc: update Source Serif 4 from 4.004 to 4.005

### PR DESCRIPTION
**Pull request by tspiteri**
[Version 4.005](https://github.com/adobe-fonts/source-serif/releases/tag/4.005R) was released on 2023-01-20.

### CODE REVIEW

**Comment by tspiteri** [comment]
The updated LICENSE.md has a trailing space in a line, but I did not want to touch the license file (apart from renaming it to SourceSerif4-LICENSE.md).

**Comment by GuillaumeGomez** [comment]
You also need to update the file hash in `rustdoc.css`.

**Comment by tspiteri** [comment]
> The updated LICENSE.md has a trailing space in a line, but I did not want to touch the license file (apart from renaming it to SourceSerif4-LICENSE.md).

I had to remove the trailing space as it would make tidy fail. Removing a trailing space from the license file is harmless anyway.

**Comment by tspiteri** [comment]
> You also need to update the file hash in `rustdoc.css`.

This is because of #98413 I guess. I think I found this a bit harder than it should be, as I have no idea how the hash is generated; in the end I had to `./x.py test` and search for the files with the added hash.

**Comment by GuillaumeGomez** [comment]
Don't hesitate to add a comment in the CSS file to explain how to generate it.

**Comment by tspiteri** [comment]
The best I could do is something like the following. Is this fine, or is there a better way?

```
/* When static files are updated, their suffixes need to be updated.

   1. In the top directory run:
      ./x.py doc --stage 1 library/core

   2. Find the directory containing files with filenames having updated suffixes:
      find build -path "*/stage1-std/*/static.files"

   3. Copy the filenames with updated suffixes from the directory.
*/
```

**Comment by GuillaumeGomez** [comment]
Actually we already have an explanation for it in `src/librustdoc/html/static/scrape-examples-help.md`. Maybe mention it instead?

**Comment by tspiteri** [comment]
I didn't find anything about the hash suffixes in `scrape-examples-help.md`.

**Comment by GuillaumeGomez** [comment]
Then let's update it. :D

**Comment by GuillaumeGomez** [comment]
I'll send the update myself. Thanks for working on this already!

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
I just realized that the file I mentioned have nothing to do with that. Sorry about the confusion.

**Pull request merged**
