### PR TITLE
Custom Debug impl for io::Error

### PR DESCRIPTION
**Pull request by retep998**
Fixes https://github.com/rust-lang/rust/issues/26408

Example output when using `Result::unwrap`:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified.\r\n" } }', src/libcore\result.rs:731
```

This could technically be considered a breaking change for any code that depends on the format of the `Debug` output for `io::Error` but I sincerely hope nobody wrote code like that.

### CODE REVIEW

**Comment by sfackler** [comment]
:+1:

**Comment by reem** [comment]
+1 from me as well, definitely addresses the concerns from #26408

**Comment by sfackler** [comment]
It may be a bit nicer to look at if we output `Os { code: 6, message: "foobar" }` instead of `Os(6, "foobar")` imo.

**Comment by reem** [comment]
Agreed. I like the setup in the latest commit.

**Comment by arielb1** [comment]
Test please.

**Comment by retep998** [comment]
@arielb1 Test added

**Comment by retep998** [comment]
*shakes fist at spurious failures*

**Comment by pnkfelix** [comment]
/me cant believe that we still havent solved the problem of including the *requested path* in the error information here

**Comment by retep998** [comment]
@pnkfelix That would involve storing the requested path in the `io::Error` and since that won't fit into the `i32` we'd have to `Box` it in the `Custom` variant. And we'd have to add code to every function that could potentially return a no such file error to check for that error code and instead return the fat custom error with the requested path.

**Comment by WandyLau** [comment]
why I still got this error when I run the code from Mac 10.13.6 with rustc version 1.29.0.

**Pull request merged**
