### PR TITLE
Add terminal support checking. Fixes #41587

### LINKED ISSUE #41587: rustc_errors doesn't check terminal attributes correctly
Looking at https://github.com/rust-lang-nursery/rustfmt/issues/1180, I found it originated in syntex_errors, which is basically a stabilized version of https://github.com/rust-lang/rust/blob/master/src/librustc_errors/emitter.rs#L1362. 

Looking over this code, the emitter doesn't check if the terminal actually supports the attribute before trying to set it. For example, in ```apply_style```, ```start_attr``` is called with ```term::Attr::Bold```. But on Windows, the terminal doesn't support bold (https://github.com/Stebalien/term/blob/master/src/win.rs#L181). So whenever an error is encountered, it panics because Bold is not supported. This also affects a Arch Linux + eshell, which doesn't support any attributes at all, including resetting them. As a result, ```t.attr(attr)?``` returns ```term::NotSupported``` which gets returned until it eventually panics at https://github.com/rust-lang/rust/blob/master/src/librustc_errors/emitter.rs#L1067.

I have a fix for syntex, https://github.com/serde-rs/syntex/pull/121/commits/7ca0bb2e2dbae42d3983991787857730854336ef, that would also work here.

### PR DESCRIPTION
**Pull request by keringar**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Thanks for the PR!

Looks like you have some errors in the code. I'm personally not familiar with this area, so I don't know if that method exists, but it seems at least possible that it doesn't -- grepping for it in Rust's source returned nothing for me. Where did you expect the `supports_reset` method to come from?

```
[00:02:35] error: no method named `supports_reset` found for type `&mut std::boxed::Box<term::Terminal<Output=std::io::Stderr> + std::marker::Send + 'static>` in the current scope
[00:02:35]     --> /checkout/src/librustc_errors/emitter.rs:1379:22
[00:02:35]      |
[00:02:35] 1379 |                 if t.supports_reset() {
[00:02:35]      |                      ^^^^^^^^^^^^^^
[00:02:35] 
[00:02:35] error: no method named `supports_reset` found for type `&mut std::boxed::Box<term::Terminal<Output=emitter::BufferedWriter> + std::marker::Send + 'static>` in the current scope
[00:02:35]     --> /checkout/src/librustc_errors/emitter.rs:1384:22
[00:02:35]      |
[00:02:35] 1384 |                 if t.supports_reset() {
[00:02:35]      |                      ^^^^^^^^^^^^^^
[00:02:35] 
[00:02:35] error: aborting due to 2 previous errors
```

**Comment by keringar** [comment]
The supports_reset is supposed to be a method provided by the term::Terminal trait. https://stebalien.github.io/doc/term/term/trait.Terminal.html#tymethod.supports_reset

**Comment by Mark-Simulacrum** [comment]
Yeah, the compiler's term crate is in-tree (`src/libterm`). I'm not sure what current policy is on moving away from these in-tree crates to out of tree equivalents is (cc @alexcrichton).

We'll try to get you a decision on what to do here soon.

**Comment by keringar** [comment]
Thank you

**Comment by rkruppe** [comment]
I asked @alexcrichton a while ago about libterm and he said it would be good to move to the crates.io version, he just hasn't found the time to do it yet. (Ideally we'd fix #27812 first)

**Comment by alexcrichton** [comment]
Yes I'd love to see libterm from crates.io integrated into the compiler!

**Comment by keringar** [comment]
I can start moving rustc away from depending on an in-tree term. I'm assuming that it won't be affected by #27812 (cc @eddyb)

**Pull request closed without merging**
