### PR TITLE
Revert "Update normalize.css to 8.0.1"

### LINKED ISSUE #82542: rustdoc: Search results have larger margins than before
### nightly (2021-02-25)

image

### beta (1.51.0-beta.3)

image

### LINKED ISSUE #82548: Rustdoc: button text does not respect color themes
I visited nightly-generated docs, e.g. https://doc.rust-lang.org/nightly/std/?search=a

With the dark and ayu themes, some texts appear black although they shouldn't. This includes:
 - tab buttons in searches ("in names", "in parameters", "in return types")
 - theme selection buttons, including those in the settings page

IIRC this wasn't the case yesterday, so this must have regressed in today's nightly (2021-02-26)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Reverts rust-lang/rust#82313

Fixes #82548
Fixes #82542

@jsha: I'm reverting until we can come up with a new version which is fully working.

r? @jyn514

### CODE REVIEW

**Comment by apiraino** [comment]
r+

**Comment by GuillaumeGomez** [comment]
Considering it's a revert for a small change, I guess it's fine to go ahead. Thanks for the quick reaction @apiraino !

@bors: r=apiraino rollup

**Review by jyn514 — APPROVED** [review]

**Comment by jsha** [comment]
Sounds good to me, and sorry for the breakage.

**Pull request merged**
