### PR TITLE
Update minifier-rs version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
The `main.js` file size goes from 52868 to 50134. A few fixes have been included as well (no more eluded parts of js files).

r? @QuietMisdreavus

### CODE REVIEW

**Comment by chocol4te** [comment]
@GuillaumeGomez @QuietMisdreavus Ping from triage regarding the merge conflicts and review! :)

**Comment by GuillaumeGomez** [comment]
Updated.

r? @ollie27

**Comment by GuillaumeGomez** [comment]
Considering this is a small bugfix and that it's been open for weeks, I'll just r+ it (I really hate doing it for my own PRs)...

@bors: r+

**Pull request merged**
