### PR TITLE
doc: add some array usage examples

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by bluss** [comment]
Looks good. Isn't this a nice place to explain how certain traits are implemented just for array sizes 0-32? Maybe mention information that's not visible in the API documentation:

- `[T; N]` is an array type for any compile time constant `N`.
- Array creation `[x; N]` and `[x, y, z]`.
- Array is Copy as long as the element type is Copy.
- Arrays always derefence to slices, so they have slice methods too.

**Comment by tshepang** [comment]
@bluss I don't mind if you add that extra info to either this PR or a follow-up... I don't have the knowledge of those things you mention.

**Comment by bluss** [comment]
Sounds like they need to be documented then!

**Comment by bluss** [comment]
@bors: r+ rollup

thanks! This is the starting point

**Comment by tshepang** [comment]
Take the following @bluss:

> Array creation [x; N] and [x, y, z].

Did you mean that I should mention that one doesn't need to explicitly mention the type (i.e. `[i32; 3]`)?

**Comment by bluss** [comment]
No but that `[x; N]` creates a fixed size array (if the type of `x` is Copy) where every element has value `x`.

**Comment by bluss** [comment]
#26923 is the follow-up

**Pull request merged**
