### PR TITLE
Use new dataflow framework for generators

### PR DESCRIPTION
**Pull request by ecstatic-morse**
#65672 introduced a new dataflow framework that can handle arbitrarily complex transfer functions as well as ones expressed as a series of gen/kill operations. This PR ports the analyses used to implement generators to the new framework so that we can remove the old one. See #68241 for a prior example of this. The new framework has some superficial API changes, but this shouldn't alter the generator passes in any way.

r? @tmandry

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Ping @tmandry

**Review by tmandry — APPROVED** [review]
Sorry for the delay on my end! It's been a wild couple of weeks.

Looks good, r=me after comment.

EDIT: The new framework looks really nice. :)

**Comment by ecstatic-morse** [comment]
Ugh, that was a bit loose.

@bors r=tmandry

**Pull request merged**
