### PR TITLE
[beta] Unstable const fn promotion

### PR DESCRIPTION
**Pull request by oli-obk**
r? @pietroalbini

### CODE REVIEW

**Comment by pietroalbini** [comment]
r=me, I don't have review permissions on bors though.

**Comment by kennytm** [comment]
@bors retry #50604

```
[00:32:34] [RUSTC-TIMING] syntax_ext test:false 22.340
[00:35:11] [RUSTC-TIMING] rustc test:false 178.794
[00:35:11] error: Could not compile `rustc`.
[00:35:11] 
[00:35:11] Caused by:
[00:35:11]   process didn't exit successfully: `C:\projects\rust\build\bootstrap/debug/rustc --crate-name rustc librustc\lib.rs --color always --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=3 -C metadata=d3200e9bbf160765 -C extra-filename=-d3200e9bbf160765 --out-dir C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps --target i686-pc-windows-msvc -L dependency=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps -L dependency=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\release\deps --extern log=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\liblog-2762c5caac82e417.rlib --extern rustc_target=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\rustc_target-05ddd24e760f7ace.dll --extern flate2=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\libflate2-94f78f7f57f2889d.rlib --extern tempdir=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\libtempdir-d420b445b9e14a91.rlib --extern rustc_data_structures=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\rustc_data_structures-ada7e2259a28d058.dll --extern backtrace=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\libbacktrace-8e3f073373aa2bb2.rlib --extern syntax=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\syntax-a13425ea467ee748.dll --extern proc_macro=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\proc_macro-fc17a52941a7f029.dll --extern arena=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\arena-b483733d2ccbf5e3.dll --extern bitflags=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\libbitflags-61e76ec1dd633d3a.rlib --extern rustc_errors=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\rustc_errors-bbc2087b6b278c3c.dll --extern serialize=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\serialize-7aaabfe06ab6d124.dll --extern serialize=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\libserialize-7aaabfe06ab6d124.rlib --extern byteorder=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\libbyteorder-71611757d6cec2d5.rlib --extern lazy_static=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\liblazy_static-765850a4e6bed16a.rlib --extern graphviz=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\graphviz-0d8356d8e0b0ba02.dll --extern syntax_pos=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\syntax_pos-9ad18d15aa741028.dll --extern jobserver=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\libjobserver-9e74702d9fded34b.rlib --extern rustc_apfloat=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\librustc_apfloat-055be6a6ca7a7943.rlib --extern fmt_macros=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\deps\fmt_macros-440f172084320323.dll -L native=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib\ -L native=C:\projects\rust\build\i686-pc-windows-msvc\stage1-rustc\i686-pc-windows-msvc\release\build\miniz-sys-d6e994b7a05d8bcc\out` (exit code: 3221225477)
[00:35:11] command did not execute successfully: "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage0/bin\\cargo.exe" "build" "--target" "i686-pc-windows-msvc" "-j" "4" "--release" "--locked" "--color" "always" "--features" "" "--manifest-path" "C:\\projects\\rust\\src/rustc/Cargo.toml" "--message-format" "json"
[00:35:11] expected success, got: exit code: 101
[00:35:11] thread 'main' panicked at 'cargo must succeed', bootstrap\compile.rs:1091:9
[00:35:11] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:35:11] failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap dist
[00:35:11] Build completed unsuccessfully in 0:29:31
[00:35:11] Command exited with code 1
```

**Pull request merged**
