### PR TITLE
Eagerly drop higher-ranked type outlives obligations if satisfied by param env

### LINKED ISSUE #97607: regression: parameter type may not live long enough
See https://crater-reports.s3.amazonaws.com/beta-1.62-1/beta-2022-05-20/gh/FSMaxB.rust-genealogy/log.txt:

```
[INFO] [stdout] error[E0311]: the parameter type `Extracted` may not live long enough
[INFO] [stdout]   --> genealogy-java-apis/src/comparator.rs:24:13
[INFO] [stdout]    |
[INFO] [stdout] 24 |             compare: Box::new(move |left, right| match (self.compare)(left, right) {
[INFO] [stdout]    |                      ^^^^^^^^ ...so that the type `Extracted` will meet its required lifetime bounds...
[INFO] [stdout]    |
[INFO] [stdout] note: ...that is required by this bound
[INFO] [stdout]   --> genealogy-java-apis/src/comparator.rs:21:28
[INFO] [stdout]    |
[INFO] [stdout] 21 |         for<'a> Extracted: Ord + 'a,
[INFO] [stdout]    |                                  ^^
[INFO] [stdout] help: consider adding an explicit lifetime bound...
[INFO] [stdout]    |
[INFO] [stdout] 21 |         for<'a> Extracted: Ord + 'a + 'a,
[INFO] [stdout]    |                                     ++++
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error: aborting due to previous error
```

This is a 1.62 regression, it seems, based on Crater. At the very least, it's a diagnostics issue that we're suggesting adding an already existing lifetime bound.

### PR DESCRIPTION
**Pull request by compiler-errors**
Attempts to satisfy `TypeOutlives` predicates using the param env, instead of unconditionally registering them in the infcx for later borrowck'ing. The first commit e176496 is the simpler attempt to fix this problem --and it fixes #97607 -- but only does so for `TypeOutlives(_, RePlaceholder)`, so #86483 continues to fail. 

The second commit 47a32b9 makes this logic slightly more complicated, but allows us to use `for<'a> T: 'a` to satisfy `for<'a> T: 'region` in general (including `'region = 'static`), as long as it doesn't cause us to further constrain any region variables in `T`.

I'm still unsure if this is the right approach -- this is a generalization of the logic I think @oli-obk suggested [here](https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/higher.20kinded.20lifetime.20bounds/near/284632712). Maybe it's overkill, and we can just search for exact matches in the param-env instead. I'd appreciate feedback.

I don't know who to r?, so I guess I'll just
r? @nikomatsakis 
cc @rust-lang/types 

Fixes #97607
Also converts tests from #88586, #86483 into passing.

### CODE REVIEW

**Comment by compiler-errors** [comment]
as expected... i wonder if we can employ some of the same heuristics used in impl matching.

**Comment by compiler-errors** [comment]
Oh, yes, I totally forgot that @oli-obk mentioned we wanted to backport a fix, lol, or at least ensure a fix gets into the next beta. I can write up that solution easily.

**Comment by oli-obk** [comment]
We should still probably do that change to get it merged on nightly before the beta cutoff, out of the reasons I mentioned for the wrongly-assumed-beta-backport

**Pull request closed without merging**
