### PR TITLE
bootstrap: Unify test argument handling

### LINKED ISSUE #104198: Unify test code in bootstrap
Right now, we copy paste a bunch of code in various places and it ends up with not all test suites supporting the same arguments. See for example https://github.com/rust-lang/rust/issues/66458. We should refactor all these Steps to use the same logic for the flags to pass to cargo.

https://github.com/rust-lang/rust/blob/131ef9580815329aa3647fa84d7c74769fefbccf/src/bootstrap/test.rs#L2448-L2464 is an example of code that's repeated nearly verbatim 5+ times in test.rs. It would be nice to have a `fn test_args(cargo: &mut Cargo) {}` that we call instead of trying to keep these in sync.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/72536#issuecomment-1308932797_

### PR DESCRIPTION
**Pull request by jyn514**
Fixes #104198. Does *not* help with https://github.com/rust-lang/rust/issues/80124 because I couldn't figure out a reasonable way to omit `--lib` only for `panic_abort` and not other `std` dependencies.

- Remove unnecessary `test_kind` field and `TestKind` struct. These are just subsets of the existing `builder.kind` / `Kind` struct.
- Add a new `run_cargo_test` function which handles passing arguments to cargo based on `builder.config`
- Switch all Steps in `mod test` to `run_cargo_test` where possible
- Combine several steps into one `CrateBootstrap` step. These tests all do the same thing, just with different crate names.
- Fix `x test --no-doc`. This is much simpler after the refactors mentioned earlier, but I'm happy to split it into a separate PR if desired. Before, this would panic a lot because steps forgot to pass `--lib`.

### CODE REVIEW

**Comment by jyn514** [comment]
r? bootstrap

**Comment by jyn514** [comment]
I tried to fix https://github.com/rust-lang/rust/issues/80124 but ran into https://github.com/rust-lang/rust/pull/100599#issuecomment-1517196256 so this is probably enough experimenting for tonight and I'm going to put it off for another day :sweat_smile:

**Review by onur-ozkan — APPROVED** [review]
great effort!

LGTM

**Comment by jyn514** [comment]
```
test concurrent::killing_cargo_releases_the_lock has been running for a long time
test death::ctrl_c_kills_everyone has been running for a long time
```
@matthiaskrgr I think these might just be spurious? I'm not sure how they could be related.

**Comment by matthiaskrgr** [comment]
Hm, I've seen hangs on two rollups both on the same runner, and both included this pr which seemed a bit suspicious to me 😅🤷

**Comment by jyn514** [comment]
ah, I was able to replicate this locally:
```
---- cargo_remove::optional_dep_feature::case stdout ----
thread 'cargo_remove::optional_dep_feature::case' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: "Failed to copy C:\\Users\\jyn\\src\\rust\\src\\tools\\cargo\\tests\\testsuite\\cargo_remove\\optional_dep_feature\\in to C:\\Users\\jyn\\src\\rust\\build\\x86_64-pc-windows-msvc\\stage1-tools\\x86_64-pc-windows-msvc\\tmp\\cit\\t695\\case\\: The system cannot find the path specified. (os error 3)", backtrace: None }', C:\Users\jyn\src\rust\src\tools\cargo\crates\cargo-test-support\src\lib.rs:324:77
```
not sure what the timeout was about, but hopefully fixing this test will fix the hang as well.

**Comment by jyn514** [comment]
Ok I take it back, the failure I saw locally was unrelated :/ https://github.com/rust-lang/cargo/issues/12042

I am not sure how to investigate this further. I guess I can revert the change for cargo only?

**Comment by ozkanonur** [comment]
I will also debug it tonight/early tomorrow. Let's see if I can find the reason

**Comment by ozkanonur** [comment]
I have repreduced the same errors(mostly about network errors and command not found errors) on windows machine with the default `tools` configuration created with `x setup`.

Commits that are causing the errors: 
- [Remove unnecessary test_kind field and TestKind struct](https://github.com/rust-lang/rust/pull/110576/commits/a1780a7e6f19ddf9aae04dca3c135644e4065a0e) - causing many tests failing for cargo, also hangs ~2-3 tests.
- [Convert the rest of the test Steps to run_cargo_test](https://github.com/rust-lang/rust/pull/110576/commits/84e7253a4ff1fbf12282b34fb4c5d9cc9f3bb3cb) - causing more tests to fail


--

I only had limited time, couldn't work on the fix. But would work on the fix at the weekend if you don't want to work on the fixes(probably multiple fixes needed for both commits) @jyn514

**Comment by jyn514** [comment]
that's so strange I couldn't reproduce locally. I'll try again this weekend. Thanks for looking into it :)

**Comment by jyn514** [comment]
I still can't reproduce this :(

@ozkanonur what version of windows are you on? are you using gnu or MSVC? what was the output from the failing tests?

**Comment by ozkanonur** [comment]
> what version of windows are you on? are you using gnu or MSVC?

Windows 11 / MSVC

I just run `x setup` and picked `tools` profile and then `x cargo test`.

To achieve logs, I had to ignore `ctrl_c_kills_everyone`, `killing_cargo_releases_the_lock`, `close_output`, `close_output_during_drain` tests because they were hanging the process.

- [Log output](https://gist.githubusercontent.com/ozkanonur/69d2ffcb886efae2f157568db3b058fa/raw/9f0f6cc48c0d390f23f41134ccb553c6981813f3/a1780a7e6f19ddf9aae04dca3c135644e4065a0e.txt) when HEAD is [Remove unnecessary test_kind field and TestKind struct](https://github.com/rust-lang/rust/pull/110576/commits/a1780a7e6f19ddf9aae04dca3c135644e4065a0e)
- [Log output](https://gist.githubusercontent.com/ozkanonur/748d4f4ee2c722bfbcf5d1afe5bf5fae/raw/e88c029129d87738ba132e16d4049e174a041a2a/84e7253a4ff1fbf12282b34fb4c5d9cc9f3bb3cb.txt) when HEAD is [Convert the rest of the test Steps to run_cargo_test](https://github.com/rust-lang/rust/pull/110576/commits/84e7253a4ff1fbf12282b34fb4c5d9cc9f3bb3cb)

**Comment by jyn514** [comment]
Oh! I have a global rustc install and CI doesn't. If you run `rustc --version` in your home directory, does that output anything? Or are you only using the rustc managed by bootstrap?

**Comment by ozkanonur** [comment]
> Oh! I have a global rustc install and CI doesn't. If you run `rustc --version` in your home directory, does that output anything?

It's fresh Windows 11 just has couple dependencies to build rustc. Just like CI, I also don't have rustc installed globally.

> Are you only using the rustc managed by bootstrap?

Yes

**Pull request merged**
