### PR TITLE
suggest one-argument enum variant to fix type mismatch when applicable

### LINKED ISSUE #42764: Also suggest `Some` when an `Option<T>` is expected, but `T` is given
```rust
let i: Option<i32> = 42i32;
```

produces

```
error[E0308]: mismatched types
 --> <anon>:2:26
  |
2 |     let i: Option<i32> = 42i32;
  |                          ^^^^^ expected enum `std::option::Option`, found i32
  |
  = note: expected type `std::option::Option<i32>`
             found type `i32`
  = help: here are some functions which might fulfill your needs:
          - .checked_abs()
          - .checked_neg()
```

I think the first item in this list should be `Some`

### PR DESCRIPTION
**Pull request by zackmdavis**
Following @est31's [suggestion](https://github.com/rust-lang/rust/issues/42764#issuecomment-309680886).

some_suggestion

Resolves #42764.

### CODE REVIEW

**Comment by zackmdavis** [comment]
I don't know what AppVeyor's problem is.

**Comment by jmesmon** [comment]
From the example, it looks like this _replaces_ the function suggestions with the enum constructor. Would it be possible just to add the enum constructor as an additional item in the list of suggestions?

**Comment by zackmdavis** [comment]
> it looks like this replaces the function suggestions with the enum constructor. Would it be possible to add the enum constructor as an additional item in the list of suggestions?

The behavior is intentional; discussion on the original issue [looked unfavorably](https://github.com/rust-lang/rust/issues/42764#issuecomment-311388958) on the existing suggestions in this situation (at least in the case of `Option`). 

Intuitively, I'd guess that situations that trigger this but where the probe-for-return-type method suggestions would be preferrable are kind of rare? (If you have an `x: T` where an `Option<T>` is expected, it's more likely that you meant to write `Some(x)` than that you meant a method on `x` that happens to return a `Some(T)`?—most useful methods on `T` will return something else.)

**Comment by zackmdavis** [comment]
(rebased on master and forced-pushed in the hopes of removing the [spurious "AppVeyor was unable to build"](http://help.appveyor.com/discussions/problems/4830-stuck-on-appveyor-was-unable-to-build-non-mergeable) failure indicator)

**Comment by jmesmon** [comment]
> The behavior is intentional; discussion on the original issue looked unfavorably on the existing suggestions in this situation (at least in the case of Option).

There is an issue opened around what the right way to filter and/or order the suggestions. #42929 . It seems preferable to allow generating the additional suggestion of the enum constructor while we're still in the process of deciding how to order/filter suggestions.

**Comment by zackmdavis** [comment]
@jmesmon OK (deleted `return` statement in 80c603f).

no_return_early_sole_argument_variant

Also 80c603f, made the suggestion use the path to the enum rather than the bare name (which might not be in scope).

**Comment by kennytm** [comment]
Unable to download `cmake` crate because the SSL revocation server is offline. Spurious.

```
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.)
```

**Comment by est31** [comment]
@kennytm this issue affects all PRs right now. Not sure what the cause of the issue is, but probably either some revocation server is actually down, or there is a networking issue with appveyor that is specific to the revocation servers (generally there seems to be network).

I guess we just wait a bit and hope the issue gets fixed by itself, but smashing the retry button won't be very useful....

cc @oli-obk

**Comment by est31** [comment]
lets try whether it persists...

@bors retry

**Pull request merged**
