### PR TITLE
Add @aldeka's safe and unsafe Ferris to nomicon

### PR DESCRIPTION
**Pull request by steveklabnik**
A while back, @gankro asked @aldeka if a Ferris could be used in
the nomicon. But he did not ever get around to actually implementing it.

I have done so in this PR. :smile:

### CODE REVIEW

**Comment by alexcrichton** [comment]
Haha that's great! Can you update the rustbuild build rules for the nomicon as well?

**Comment by steveklabnik** [comment]
@alexcrichton I _think_ this is the right way to do this. What do you think?

**Comment by alexcrichton** [comment]
Could you actually make a new `doc::nomincon` function which encapsulates both actions? I think you'll also want to place the output in `doc_root.join("nomicon/...")` rather than just `doc`

**Comment by alexcrichton** [comment]
(may also be worth running `python src/bootstrap/bootstrap.py --stage 0 --step doc-nomicon` to look at the output)

**Pull request closed without merging**
