### PR TITLE
Rollup of PRs in the queue; Friday

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by Manishearth** [comment]
wut

**Comment by iKevinY** [comment]
@Manishearth Since #22474 is part of this rollup now, should it be `r-`'d?

**Comment by Manishearth** [comment]
No, in case the rollup fails and there's nobody around to shepherd it through :)

r- is only when someone second-guesses a PR or if we know that the PR is going to fail the build.

**Comment by iKevinY** [comment]
Ah, that makes sense!

**Comment by Manishearth** [comment]
Same double panic, slightly different test. Any idea where it came from? @retep998 @alexcrichton

**Comment by alexcrichton** [comment]
I'll try to investigate some more, but I suspect https://github.com/rust-lang/rust/pull/22980 may be the most likely candidate

**Comment by alexcrichton** [comment]
I have confirmed that #23081 is the problem.

**Pull request merged**
