### PR TITLE
Move deny(warnings) into rustbuild

### LINKED ISSUE #49517: Provide config.toml flag (or so) to compile without deny(warnings)
It would sometimes be nice to run the compiler on a testcase even though there are currently warnings in the compiler. One way might be to have a config.toml flag that controls this.

Cc @eddyb

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This permits easier iteration without having to worry about warnings
being denied.

Fixes #49517

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @alexcrichton 

cc @eddyb @RalfJung

**Comment by RalfJung** [comment]
Just to be sure, the `./configure`-based build that runs on CI still has `deny(warnings)`, right? I can#t see any changes to the configure script.

**Comment by alexcrichton** [comment]
Sounds like a great idea to me! I wouldn't personally feel the need to have the command line flag as well, but now that it's done there's certainly no harm.

I wonder if it'd be best now though to disable warnings by default and update `src/ci/run.sh` so all CI builders deny warnings?

**Comment by alexcrichton** [comment]
er, disable deny(warnings) by default*

**Comment by RalfJung** [comment]
@cramertj expressed at the all-hands that he preferred `deny(warnings)` on in the compiler. Also, it seems it took 3 years for someone to take enough offense with the default to actually raise the point in the issue tracker, so maybe it's not such a bad default? Either way, that seems like a separate discussion form just providing the option.

I am perfectly fine changing my `cargo.toml`, so this patch already makes me happy :)

**Comment by Mark-Simulacrum** [comment]
@alexcrichton I think feedback above indicates we may not want to make this a default, and either way that seems like something we should do down the line. I fixed the nit that @steveklabnik noticed (thanks!) so I believe this is good to go.

**Comment by alexcrichton** [comment]
@bors: r+

Seems reasonable to me!

**Comment by RalfJung** [comment]
Seems like we now run `deny(warnings)` on more code than before? The windows build says
```
   Compiling rustc-main v0.0.0 (file:///C:/projects/rust/src/rustc)
error: unused attribute
  --> rustc\rustc.rs:16:47
   |
16 | #[cfg_attr(all(windows, target_env = "msvc"), link_args = "/STACK:16777216")]
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D unused-attributes` implied by `-D warnings`
error: aborting due to previous error
```

**Comment by Mark-Simulacrum** [comment]
@ishitatsuyuki Any thoughts on that error? It looks like this code was added by you in https://github.com/rust-lang/rust/pull/48575; I'm wondering if we should ignore that warning or if it's just that we don't properly consider link_args...

**Comment by alexcrichton** [comment]
I believe I tested that out locally a few days ago and rustc is basically incorrectly reporting that it's an unused attribute, you'll probably want to attach an `#[allow]` annotation there for now

**Comment by RalfJung** [comment]
And another one:
```
   Compiling rustdoc-tool v0.0.0 (file:///C:/projects/rust/src/tools/rustdoc)
error: unused attribute
  --> tools\rustdoc\main.rs:14:47
   |
14 | #[cfg_attr(all(windows, target_env = "msvc"), link_args = "/STACK:16777216")]
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D unused-attributes` implied by `-D warnings`
error: aborting due to previous error
``

**Pull request merged**
