### PR TITLE
WIP: check that required_consts really contains all required consts

### PR DESCRIPTION
**Pull request by RalfJung**
To this end, assert that evaluating const operands never fails (as they all should have been checked as part of `required_consts`).

I am going to try to find the right spot for codegen to add a similar check.

However, this also currently does not work -- const-eval triggers the new assertion. I am not sure how that is possible. (My previous theory made no sense.)

Cc @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
> However, this also currently does not work -- const-eval triggers the new assertion. I am not sure how that is possible. (My previous theory made no sense.)

Maybe it's const-prop again?

**Comment by RalfJung** [comment]
@oli-obk is it possible that for `const` items (not function bodies), `required_consts` is not filled properly?

No it's not ConstProp. The PR already contains a special constprop hack as usual (this is getting tedious^^), but the remaining failures have a stack trace like
```
   0: std::panicking::begin_panic
             at ./library/std/src/panicking.rs:497
   1: rustc_errors::HandlerInner::bug
             at ./src/librustc_errors/lib.rs:915
   2: rustc_errors::Handler::bug
             at ./src/librustc_errors/lib.rs:665
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
             at ./src/librustc_middle/util/bug.rs:33
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1792
   5: rustc_middle::ty::context::tls::with_context_opt
             at ./src/librustc_middle/ty/context.rs:1744
   6: rustc_middle::ty::context::tls::with_opt
             at ./src/librustc_middle/ty/context.rs:1792
   7: rustc_middle::util::bug::opt_span_bug_fmt
             at ./src/librustc_middle/util/bug.rs:29
   8: rustc_middle::util::bug::bug_fmt
             at ./src/librustc_middle/util/bug.rs:14
   9: rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_operand::{{closure}}
             at ./src/librustc_mir/interpret/operand.rs:526
  10: core::result::Result<T,E>::map_err
             at ./library/core/src/result.rs:612
  11: rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_operand
             at ./src/librustc_mir/interpret/operand.rs:521
  12: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
             at ./src/librustc_mir/interpret/step.rs:153
  13: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::statement
             at ./src/librustc_mir/interpret/step.rs:89
  14: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::step
             at ./src/librustc_mir/interpret/step.rs:65
  15: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
             at ./src/librustc_mir/interpret/step.rs:34
  16: rustc_mir::const_eval::eval_queries::eval_body_using_ecx
             at ./src/librustc_mir/const_eval/eval_queries.rs:57
  17: rustc_mir::const_eval::eval_queries::const_eval_raw_provider::{{closure}}
             at ./src/librustc_mir/const_eval/eval_queries.rs:313
  18: core::result::Result<T,E>::and_then
             at ./library/core/src/result.rs:729
  19: rustc_mir::const_eval::eval_queries::const_eval_raw_provider
             at ./src/librustc_mir/const_eval/eval_queries.rs:313
```
Query stack:
```
query stack during panic:
#0 [const_eval_raw] const-evaluating `main`
#1 [const_eval_validated] const-evaluating + checking `main`
#2 [const_eval_validated] const-evaluating + checking `main`
#3 [normalize_generic_arg_after_erasing_regions] normalizing `main::promoted[2]`
#4 [optimized_mir] optimizing MIR for `main`
#5 [collect_and_partition_mono_items] collect_and_partition_mono_items
```

**Comment by oli-obk** [comment]
Ah. I just remembered. We do probe const eval really early and this may cause `TooGeneric` errors. See https://github.com/rust-lang/rust/blob/4745cbe83e0b3299bfe7f7f305b975c3c09f92db/src/librustc_mir/const_eval/eval_queries.rs#L234

**Comment by RalfJung** [comment]
But it's not a TooGeneric:
```
error: internal compiler error: src/librustc_mir/interpret/operand.rs:526:25: const eval should have failed already when evaluating required_consts, so this error is unexpected: InterpErrorInfo { kind: referenced constant has errors, backtrace: None }
```
If anything, the referenced constant failed with `TooGeneruic`? But it doesn't look like that, the lints it printed so far are
```
warning: any use of this value will cause an error
  --> /home/r/src/rust/rustc/library/core/src/hint.rs:52:14
   |
LL |     unsafe { intrinsics::unreachable() }
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^
   |              |
   |              entering unreachable code
   |              inside `std::hint::unreachable_unchecked` at /home/r/src/rust/rustc/library/core/src/hint.rs:52:14
   |              inside `foo` at /home/r/src/rust/rustc/src/test/ui/consts/const_unsafe_unreachable_ub.rs:9:18
   |              inside `BAR` at /home/r/src/rust/rustc/src/test/ui/consts/const_unsafe_unreachable_ub.rs:14:28
   | 
  ::: /home/r/src/rust/rustc/src/test/ui/consts/const_unsafe_unreachable_ub.rs:14:1
   |
LL | const BAR: bool = unsafe { foo(false) };
   | ----------------------------------------
   |
note: the lint level is defined here
  --> /home/r/src/rust/rustc/src/test/ui/consts/const_unsafe_unreachable_ub.rs:13:8
   |
LL | #[warn(const_err)]
   |        ^^^^^^^^^
```

Also why does the query stack say it is "const-evaluating `main`"??

**Comment by RalfJung** [comment]
Oh, doing this during codegen will be hard because it doesn't actually stop compiling a function when encountering a bad constant!

https://github.com/rust-lang/rust/blob/4745cbe83e0b3299bfe7f7f305b975c3c09f92db/src/librustc_codegen_ssa/mir/mod.rs#L199

That seems rather strange to me? There's no meaningful codegen in this case, we should just leave the function body empty or so... but we don't even `delay_span_bug!` or so.

**Comment by oli-obk** [comment]
```
#1 [const_eval_validated] const-evaluating + checking `main`
#2 [const_eval_validated] const-evaluating + checking `main`
```

does hint at this happening. I think we should start collecting some numbers on whether this scheme really is useful or not, but that's a different story.

Anyway, back to this PR, idk how this is happening, we should be inserting all constants that we couldn't evaluate, so while there could be more constants added to MIR later (I don't know of this), seems unlikely, we already handle inlining correctly, I think the likely case is that there are constants that fail to eval early that don't end up in the list. This may be true for constants in types, maybe we're not looking at repeat lengths?

**Comment by oli-obk** [comment]
Jup, we're not checking repeat lengths: https://github.com/rust-lang/rust/blob/4745cbe83e0b3299bfe7f7f305b975c3c09f92db/src/librustc_mir/transform/required_consts.rs#L16

**Comment by RalfJung** [comment]
Also `main` is not a constant so that query stack just makes no sense. `main` cannot be const-eval'd.

**Comment by oli-obk** [comment]
> Also `main` is not a constant so that query stack just makes no sense. `main` cannot be const-eval'd.

it's `main::promoted[2]`, there's just bad printing of the const eval queries

**Comment by oli-obk** [comment]
you can fix the query stack printing by adjusting https://github.com/rust-lang/rust/blob/3cfc7fe78eccc754b16981704a098d7bd520e2fd/src/librustc_middle/query/mod.rs#L682 to just print the `GlobalId` I think.

**Comment by RalfJung** [comment]
I got a span for the const that fails to evaluate:
```rust
  --> /home/r/src/rust/rustc/src/test/ui/consts/const_unsafe_unreachable_ub.rs:17:14
   |
LL |   assert_eq!(BAR, true);
   |              ^^^
```
Doesn't look like an array length to me?

**Comment by oli-obk** [comment]
omg, promoteds are created *after* `required_consts`. We need to change promotion to also fill in `required_consts`

**Comment by oli-obk** [comment]
cc @wesleywiser ooops

**Comment by RalfJung** [comment]
Ah, found a real bug then. :)

Can one of you take over fixing that bug? That sounds like it is beyond my comfort zone.

**Comment by oli-obk** [comment]
jup. I checked out your PR locally, feel free to close this PR, I'll open a new one that includes your commit

**Comment by RalfJung** [comment]
I'll add another commit that does a similar check for codegen -- or do you prefer to land that separately?

**Comment by RalfJung** [comment]
Pushed the codegen change. It leads to errors like
```
error: internal compiler error: /home/r/src/rust/rustc/src/librustc_middle/macros.rs:13:35: erroneous constant not captured by required_consts
  --> /home/r/src/rust/rustc/src/test/ui/consts/promoted_div_by_zero.rs:8:13
   |
LL |     let x = &(1 / (1 - 1));
   |             ^^^^^^^^^^^^^^
```

**Comment by RalfJung** [comment]
All right, closing as @oli-obk is taking over.

**Pull request closed without merging**
