### PR TITLE
Optimize Write::write_fmt for Vec<u8>/Sink

### PR DESCRIPTION
**Pull request by sinkuu**
A small optimization for formatted writing to `Vec<u8>`. This doesn't fix the issue, but benchmarks for https://github.com/rust-lang/rust/issues/10761#issuecomment-152373019 :

```
 name                default ns/iter  override ns/iter  diff ns/iter   diff % 
 bench_write_macro1  22,253           17,460                  -4,793  -21.54% 
 bench_write_macro2  33,725           29,363                  -4,362  -12.93% 
 bench_write_ref     2,303            2,228                      -75   -3.26% 
 bench_write_value   2,263            2,252                      -11   -0.49%
```

### CODE REVIEW

**Comment by bluss** [comment]
Do you know roughly why this is an improvement?

**Comment by alexcrichton** [comment]
Hm yeah I'm also a little baffled on how this could result in a speedup. The `#[inline]` tags on `Sink` make sense to me, but AFAIK the specializations of `write_fmt` should be what's generated in the standard case anyway...

**Comment by sinkuu** [comment]
My intention is removing unnecessary (for `Vec<u8>` and `Sink`) error handling in default `write_fmt` impl.

**Comment by sinkuu** [comment]
Looking at IR diff, the significant difference looks like `write_fmt` beging inlined. But, just putting `#[inline]` on default `write_fmt` did't improve performance IIRC (I'll try it again).

https://gist.github.com/sinkuu/9f6c5e34e05c088e84c7330e2b146585

**Comment by bluss** [comment]
It's a very small program (the benchmark runner), so whole program optimization effects could cause this.

**Comment by sfackler** [comment]
Why do we particularly care about the performance of Sink?

**Comment by sinkuu** [comment]
I tried to remove unnecessary error handling in `write_fmt`, and thought that this can be applied to `Vec<u8>` and `Sink`.

Since the optimizer seems to be able to do that (and the cause of performance gain was inlining), this PR may not make much sense.

**Pull request closed without merging**
