### PR TITLE
Two HIR tweaks

### PR DESCRIPTION
**Pull request by nnethercote**
Two HIR tweaks that make things slightly simpler and faster.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks, @nnethercote!

@bors r+ rollup

**Comment by nnethercote** [comment]
Should these wait until 1.32 releases/branches, to avoid causing problems for tools like clippy?

**Comment by michaelwoerister** [comment]
Yeah, better safe than sorry.

@bors r-

**Comment by nnethercote** [comment]
1.32 has been released.

@bors r=michaelwoerister

**Pull request merged**
