### PR TITLE
Migrate (some) of run-pass/ to ui

### PR DESCRIPTION
**Pull request by pnkfelix**
This is a step towards addressing #53764. Much still remains.

I went through a large portion of the `*.rs` files that were directly stored into `src/test/run-pass/` and moved them into various subdirectories of a newly created `src/test/ui/run-pass/`.

(yes, it would have perhaps been nice to meld it more directly with directories already in `src/test/ui/`; but the sad truth is that opens up the reality of filename collisions, and one of my short term goals for resolving #53764 is to keep the *filenames* invariant, even as their parents directories and contents are mildly revised...)

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@bors r+

cc @rust-lang/compiler — seems like a notable change.

**Comment by nikomatsakis** [comment]
@petrochenkov 

> As a user of hygiene/, imports/, macros/, etc, I can say that they are all useful and different, and this PR makes things worse for me specifically + these directory rearrangements are not entirely on-topic for this PR.

I'm confused, perhaps. I thought that this PR preserved the existing run-pass directory structure, but made it a subpart of `src/test/ui`?

**Comment by nikomatsakis** [comment]
Ah, I see, I missed the various "collapse" commits.

**Comment by pnkfelix** [comment]
Hmm I thought my collapsing cases here still didn't *destroy* anything distinctions that were previously there.

That is, the directories being collapsed were ones that I **created** in earlier commits in the PR, and the source material ... always came solely from `src/test/run-pass/*.rs`, and none of its subdirectories .... (right? Or did I misremember and/or screw up somewhere?)

Having said that, I'm happy to drop some/all/any of the collapsing commits.

**Comment by kennytm** [comment]
Several these new UI tests generate integer overflow warnings on 32-bit platform e.g.

```
---- [ui] ui\run-pass\structs-enums\enum-discrim-width-stuff.rs stdout ----
normalized stderr:
warning: literal out of range for isize
  --> $DIR/enum-discrim-width-stuff.rs:40:20
   |
LL |     check!(f, u32, 0xe8d8c8b8);
   |                    ^^^^^^^^^^
   |
   = note: #[warn(overflowing_literals)] on by default
   = note: the literal `0xe8d8c8b8` (decimal `3906521272`) does not fit into an `isize` and will become `-388446024isize`
```

List of failures:

```
failures:
    [ui] ui\run-pass\array-slice-vec\box-of-array-of-drop-1.rs
    [ui] ui\run-pass\array-slice-vec\box-of-array-of-drop-2.rs
    [ui] ui\run-pass\array-slice-vec\nested-vec-3.rs
    [ui] ui\run-pass\consts\const-fn-val.rs
    [ui] ui\run-pass\deriving\deriving-hash.rs
    [ui] ui\run-pass\simd\simd-target-feature-mixup.rs
    [ui] ui\run-pass\structs-enums\enum-discrim-autosizing.rs
    [ui] ui\run-pass\structs-enums\enum-discrim-width-stuff.rs
```

**Comment by kennytm** [comment]
This needs a `@bors retry` but can't due to merge conflict.

**Pull request merged**
