### PR TITLE
Re-enable linkcheck after moving std

### PR DESCRIPTION
**Pull request by mark-i-m**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@mark-i-m Are you planning on fixing the tests here? I'm working on local builds of this currently to try and push patches

**Comment by Mark-Simulacrum** [comment]
Pushed a commit which passes linkcheck for me locally.

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=1

This re-enables testing so we should land it as quickly as possible.

**Comment by mark-i-m** [comment]
Rebased. Should be ready for r+

**Comment by Mark-Simulacrum** [comment]
@bors retry hopefully spurious?!

```
Assertion failed: (timeout != -1), function uv__io_poll, file ../deps/uv/src/unix/kqueue.c, line 231.
```

**Pull request merged**
