### PR TITLE
comment attribution fix

### PR DESCRIPTION
**Pull request by ghost**
comment means to refer to the macro in its direct scope

### CODE REVIEW

**Comment by jyn514** [comment]
Is this useful enough to comment? It's clear what the comment meant.

**Comment by o752d** [comment]
afiak `assert_eq` and `debug_assert_eq` are two different macros existing in the same scope as the comment

**Comment by o752d** [comment]
if you're asking me whether that was worth clicking through to produce this PR then.. yes

**Comment by jyn514** [comment]
Fair enough.

@bors r+ rollup

**Comment by o752d** [comment]
Thanks! :smile:

**Pull request merged**
