### PR TITLE
Automatically add OS labels to std PRs

### PR DESCRIPTION
**Pull request by ChrisDenton**
I'd love to have `library/std/src/sys` PRs that touch Windows stuff to have the `O-windows` label for easier discovery (and rediscovery). While I'm here I added a couple of other auto OS labels. Perhaps `O-unix` is a little too broad but it's hard to be more specific and I think it's still useful insomuch as POSIX is a thing.

r? libs

### CODE REVIEW

**Comment by cuviper** [comment]
> Perhaps `O-unix` is a little too broad but it's hard to be more specific and I think it's still useful insomuch as POSIX is a thing.

I think `unix` is ok, but there are also more specific paths under `std/src/os/` -- should we label all possible?

**Comment by ChrisDenton** [comment]
Sounds good. Unless I'm missing something, I can't find labels for hermit, itron or solid.

**Comment by ChrisDenton** [comment]
Ok, so I went ahead and created some new `O-` labels. They can always be changed/removed if they're unhelpful.

**Comment by cuviper** [comment]
It seems you added the rest of `src/sys`, but not `src/os`? I'm hoping for `O-linux` at least. :)

**Comment by ChrisDenton** [comment]
I admit is was concentrating on `sys/` and only added `os/` as an afterthought. I've now added a bunch `os/` only labels.

**Comment by cuviper** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
