### PR TITLE
Fix rustbuild per-target musl root

### PR DESCRIPTION
**Pull request by nastevens**
In #36292, support was added to target musl libc for ARM targets using rustbuild. Specifically, that change allowed the addition of per-target `musl-root` options in the rustbuild `config.toml` so that multiple targets depending on musl could be built. However, that implementation contained a couple of omissions: the `musl-root` option was added to the config, but was never added to the TOML parsing, and therefore was not actually being loaded from `config.toml`. This PR rectifies that.

Using these changes and a heavily modified version of the buildbot Docker container, I have been able to build rust targeting `armv7-unknown-linux-musleabihf` and have successfully run the binaries on a Raspberry Pi 3. I'm also planning to test `arm-unknown-linux-musleabi` and `arm-unknown-linux-musleabihf` systems, but have no reason to believe that this change would not simply work on those targets.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Nice! Do you have those docker images on hand to share? We may be trying to get these targets up and running soon :)

**Comment by nastevens** [comment]
I just put up the Dockerfile at https://github.com/nastevens/docker-rust-arm-musl - it'd be awesome if it were useful. I'm running a build right now with all three ARM targets and will push that to docker hub when it's done (i.e. tomorrow - it took forever with just one target...)

**Comment by nastevens** [comment]
Docker image is pushed: https://hub.docker.com/r/nastevens/arm-musl-rust/. Be forewarned - it is huge, around 4GB. I need to go back and refactor for size.

With that image all three arm targets work.

**Comment by alexcrichton** [comment]
Thanks @nastevens!

**Pull request merged**
