### PR TITLE
Uplift generator movability to `rustc_type_ir`

### PR DESCRIPTION
**Pull request by compiler-errors**
Part of rust-lang/types-team#124

r? types

### CODE REVIEW

**Comment by oli-obk** [comment]
Can we somehow keep sharing the hir and ir Movability type? Or is there no existing crate dependency from rustc_hir to rustc_ir?

**Comment by RalfJung** [comment]
Why are there two of these PRs...? This an https://github.com/rust-lang/rust/pull/116919.

**Comment by compiler-errors** [comment]
@RalfJung because they're different types and are pretty different review sizes.

**Comment by compiler-errors** [comment]
@oli-obk: No, there are no crate deps between them that would make sense to put this type in.

**Comment by RalfJung** [comment]
Oh, movability != mutability. :facepalm:

**Comment by oli-obk** [comment]
> @oli-obk: No, there are no crate deps between them that would make sense to put this type in.

If this becomes more common, maybe we should create such a crate. We merged some of these types to avoid any conversions or import confusions

**Comment by lcnr** [comment]
It feels like creating a new `rustc_ir_core` or whatever for `Mutability` would significantly help with #116919 :thinking: so I would prefer this over having duplicate types.

THough alternatively, can `rustc_hir` just depend on `rustc_type_ir`? This feels like the easiest solution here? :thinking:

**Pull request closed without merging**
