### PR TITLE
Fix sidebar display on small devices

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #87059.

Instead of hiding the sidebar on small devices, we instead move it out of the viewport so that it remains "visible" to our text only users.

Could you confirm it works for you @ahicks92 and @DataTriny please? You can give it a try at [this URL](https://guillaume-gomez.fr/rustdoc-test/test_docs/index.html).

r? @notriddle

### CODE REVIEW

**Comment by notriddle** [comment]
We also want to make sure this works well for sighted people using the keyboard to navigate.

The obvious way to do that is to have JavaScript detect when focus goes inside the sidebar, and make the sidebar visible when it does.

**Comment by GuillaumeGomez** [comment]
I don't expect sighted people to have a screen small enough to get the sidebar moved out of the viewport.

**Comment by notriddle** [comment]
B37A8FEA-ED70-4CFC-AA65-C720E645934A

**Comment by GuillaumeGomez** [comment]
😮 Ok nevermind. Please open an issue so I can do it next. 🤣

**Comment by notriddle** [comment]
@GuillaumeGomez https://github.com/rust-lang/rust/issues/87172

**Comment by notriddle** [comment]
Other than that concern, this seems fine to me.

**Comment by ahicks92** [comment]
NVDA is claiming it's at -19% from the left of the screen, so going with yes.

**Review by notriddle — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
@ahicks92 Awesome, thanks!

Once this PR is merged, I'll write the PR about the focus.

@bors: r=notriddle

**Pull request merged**
