### PR TITLE
Second pass stabilization: slice and vec

### PR DESCRIPTION
**Pull request by aturon**
# Second pass stabilization: vec

This PR takes a second pass through the `vec` module to
stabilize its API. The changes are as follows:

**Stable**:
- `dedup`
- `from_raw_parts`
- `insert`
- `into_iter`
- `is_empty`
- `remove`
- `reserve_exact`
- `reserve`
- `retain`
- `swap_remove`
- `truncate`

**Deprecated**:
- `from_fn`, `from_elem`, `grow_fn` and `grow`, all deprecated in
  favor of iterators. See rust-lang/rfcs#509
- `partition`, `partitioned`, deprecated in favor of a new, more
  general iterator consumer called `partition`.
- `unzip`, deprecated in favor of a new, more general iterator
  consumer called `unzip`.

A few remaining methods are left at experimental status.
# Second pass stabilization: slice

This PR takes a second pass through the `slice` module to
stabilize its API. The changes are as follows:

**Stable**:
- `as_mut_slice`
- `as_ptr`, `as_mut_ptr`
- `binary_search_by` (was: `binary_search`)
- `binary_search` (was: `binary_search_elem`)
- `chunks`, `chunks_mut`
- `contains`
- `ends_with`
- `first`, `first_mut` (was: `head`)
- `get_unchecked`, `get_unchecked_mut` (was: `unsafe_get`)
- `get`
- `is_empty`
- `iter`, `iter_mut`
- `len`
- `permutations`
- `reverse`
- `sort_by`
- `sort`
- `split_at`, `split_at_mut`
- `split_mut`, `splitn_mut`, `rsplitn_mut`
- `split`, `splitn`, `rsplitn`
- `starts_with`
- `swap`
- `to_vec`
- `windows`

**Deprecated**:
- `head`, `head_mut` (renamed as above)
- `unsafe_get`, `unsafe_mut` (renamed as above)
- `binary_search_elem` (renamed as above)
- `partitioned`, deprecated in favor of a new, more
  general iterator consumer called `partition`.
- `BinarySearchResult`, deprecated in favor of `Result<uint, uint>`
# Unify concat and concat_vec

We've long had traits `StrVector` and `VectorVector` providing
`concat`/`connect` and `concat_vec`/`connect_vec` respectively. The
reason for the distinction is that coherence rules did not used to be
robust enough to allow impls on e.g. `Vec<String>` versus `Vec<&[T]>`.

This PR consolidates the traits into a single `SliceConcatExt` trait
provided by `slice` and the prelude (where it replaces `StrVector`,
which is removed.)

[breaking-change]

r? @alexcrichton

### CODE REVIEW

**Comment by bluss** [comment]
Why did you change .remove() and .swap_remove to not return Option? It seems to contradict the RFC.

**Comment by bluss** [comment]
Also, why do we mark methods stable even if they were just changed?

**Comment by tomaka** [comment]
The RFC in question: https://github.com/rust-lang/rfcs/blob/master/text/0235-collections-conventions.md#deletion

**Comment by Gankro** [comment]
Yes, this change flew under my radar, I would be interested in the detailed rationale, as this is technically a functionality regression (even though it improves ergonomics in the expected case).

**Comment by aturon** [comment]
@bluss Thanks for bringing this to my attention! The RFC mistakenly had `remove` on `Vec` returning an `Option`, even though our intended convention for `Vec` operations was:

> If it takes an index, panic on out-of-bounds, with the sole exception of `get`/`get_mut`

This was part of rolling out error conventions for `Vec`, after a lot of experimentation with different options (e.g. returning `Option` everywhere). Initially `Vec` was very inconsistent.

The reason for marking it stable here was that I *believed* this was bringing into line with the old conventions RFC. However, as I said above, that RFC had a mistake.

I'm going to file an amendment to clarify the intended conventions and their rationale. If discussion there determines it should be otherwise, there's still time to change before 1.0-beta.

**Comment by SimonSapin** [comment]
> If it takes an index, panic on out-of-bounds, with the sole exception of `get` / `get_mut`

@aturon, Where was this discussed? What is the rationale? It seems opposite with the earlier trend of avoiding panic when possible, e.g. https://github.com/rust-lang/rust/pull/11129. And taking an index seems a fairly arbitrary criteria for different error handling.

If you *want* to panic on failure it’s very easy to add `.unwrap()` on an `Option<T>`, but doing something else on failure with a method that panics is much more difficult since panic cannot be caught/handled.

**Comment by aturon** [comment]
@SimonSapin Some of the early discussion was [here](https://github.com/rust-lang/meeting-minutes/blob/master/Meeting-API-review-2014-09-24.md#vecstring), although the repo seems to be missing the follow-up discussion after doing the experiment. This was also part of the (many, many) discussions about error conventions, though I don't recall how much was on IRC vs other forums.

In any case, two things:

### Why I believe this is the right guideline

I stand by the guideilne. It has a very simple rationale: almost all of the time, if you have managed to produce an index, either it's "special" (in practice, 0), or it was computed in a way that guarantees it's in bounds. 

For special indexes (0 and len() - 1) we tend to provide convenience methods (like `pop`) which then return `Option` to allow you to fold in the check. We don't currently have a convenience for `remove(0)` -- it was removed earlier on, before these conventions -- but we should.

FWIW, I tried many variations on the error conventions for `Vec` during the first stabilization pass. In particular, I tried a variant that returned `Result` everywhere. Rolling it out in `std` and the compiler, I found that there were very, very few times where I could end up taking advantage of that result if the code was already computing an index -- as above, unless it was a "special" index I already knew it was in bounds. So it ended up cluttering a *lot* of code with extra `unwrap`s for very little benefit.

While we have moved away from panicicking in general, we are not doing so blindly. The [accepted conventions](https://github.com/rust-lang/rfcs/pull/236) leave it to the API designer to choose what to treat as contracts (resulting in panics) and when to return results. It depends a lot on how a given API is used in practice and what knowledge clients typically have. The above guideline for `Vec`, besides being IMO the right tradeoff ergonomically, also makes `Vec`'s error handling story relatively simple, consistent and easy to predict.

To my mind, the pushback against changing `remove` really amounts to a request to add back `unshift`.

### But I could be wrong!

As I mentioned above, I will be posting an amendment to the RFC to make sure these considerations are recorded highly visibly and to give people a chance to weigh in. If there is strong disagreement, there is still time to change the API before 1.0-final.

**Comment by SimonSapin** [comment]
> almost all of the time, if you have managed to produce an index, either it's "special" (in practice, 0), or it was computed in a way that guarantees it's in bounds.

That makes sense. Thanks for the explanation.

> We don't currently have a convenience for remove(0) -- it was removed earlier on, before these conventions -- but we should.

Yes please. `remove(0)` in my code is what broke and lead me here.

**Pull request closed without merging**
