### PR TITLE
Enable MemorySSA in MemCpyOpt

### PR DESCRIPTION
**Pull request by nikic**
LLVM 12 ships with an implementation of MemCpyOpt which is based on MSSA instead of MDA. This implementation can eliminate memcpys across blocks, and as such fixes many (but not all) failures to eliminate redundant memcpys for Rust code. Unfortunately this was only enabled by default shortly after LLVM 12 was cut. This backports the enablement to our LLVM fork.

Perf results: https://perf.rust-lang.org/compare.html?start=8fd946c63a6c3aae9788bd459d278cb2efa77099&end=0628b91ce17035fb5b6a1a99a4f2ab9ab69be7a8

There are improvements on check and debug builds, which indicate that rustc itself has become faster. For opt builds this is, on average, a very minor improvement as well, although there is one significant outlier with deep-vector-opt. This benchmark creates ~140000 zero stores, which are now coalesced into a memset slightly later, resulting in longer compile-time for intermediate passes.

### CODE REVIEW

**Comment by nikic** [comment]
LLVM 12 ships with an implementation of MemCpyOpt which is based on MSSA instead of MDA. This implementation can eliminate memcpys across blocks, and as such fixes many (but not all) failures to eliminate redundant memcpys for Rust code. Unfortunately this was only enabled by default shortly after LLVM 12 was cut. I think it may be worthwhile to backport the enablement for our purposes. There's two ways to do this, with corresponding perf results:

Enable using `-enable-memcpyopt-memoryssa`: https://perf.rust-lang.org/compare.html?start=8fd946c63a6c3aae9788bd459d278cb2efa77099&end=dd2f66f571385888e89e2f017de490bbc855c499

Enable by backporting upstream change: https://perf.rust-lang.org/compare.html?start=8fd946c63a6c3aae9788bd459d278cb2efa77099&end=0628b91ce17035fb5b6a1a99a4f2ab9ab69be7a8

The difference is that the first enables MSSA but keeps the current position of the pass in the pipeline. This has compile-time cost, because it requires an extra MSSA calculation in most cases. The second one (which is how it was done upstream) also slightly adjusts the position where MemCpyOpt is run, so an existing MSSA calculation can be reused.

In terms of results, we can see improvements on check/debug builds in both cases, which indicates that rustc itself is faster. For opt builds the second version is faster, which is most clearly visible for the boostrap timings, although there is one outlier with deep-vector-opt.

r? @nagisa

**Comment by nagisa** [comment]
The message should be probably copied over to the first message so that it ends up in the merge commit description.

The results all look pretty good. I hoped this wasn't true, but sadly the deep-vector-opt has regressed significantly in wall-time (by ~12%, roughly matching the regression in instruction counts) too, so it'd be good to look into how representative the test case is of a typical Rust code. I suspect its going to have a huge number of memcpys or humongous basic blocks or very many of them.

I'm also curious how large is the improvement on the runtime of the code. We see from the compiler time improvements that there is some, but the compiler isn't always a very representative workload. Significant improvements in e.g. even the `deep-vector-opt` runtime could justify the compile time regressions. Alas I don't think this is a piece of information we can get out of perf :(

**Comment by nikic** [comment]
I've looked into what happens in the deep-vector-opt case: The input file is https://github.com/rust-lang/rustc-perf/blob/master/collector/benchmarks/deep-vector/src/main.rs which basically compiles down to 140000 GEPs + stores of zero. The reason for the compile-time regression in this case is that that we now have an additional InstCombine run prior to MemCpyOpt, which tries to (futilely) fold all those instructions. Previously the stores got combined into a memset a bit earlier, reducing the amount of work InstCombine does. The end result is the same in both cases (the function is optimized away entirely). I'm personally not particularly bothered by this, as this is a degenerate input, and the regression is a non-pathological one (linear).

As to runtime impact, I believe that unnecessary memcpys are a pretty common problem in Rust, but I don't have a way to quantify it beyond the check build results. @jrmuizel might have some insight here, I believe he reported a lot of memcpy optimization problems affecting servo.

**Comment by jrmuizel** [comment]
https://github.com/jrmuizel/memcpy-find should be a useful tool for evaluating this. I'll try to do some before and after on some projects with this branch if I can find the time.

**Comment by jrmuizel** [comment]
I confirmed, as expected, that this does fix #56172, which was a reduced test case from a relatively hot path in WebRender.

**Comment by nagisa** [comment]
> compiles down to 140000 GEPs + stores of zero

Yeah, that's exactly what I had hoped for. I think we're pretty comfortable taking a comptime perf hit here given the runtime perf improvements we're hoping to get here, even if they can't be quantified too well.

I still think it might make sense to track this kind of thing, but I'm not super concerned about it either.

I'm happy to r+ this once the PR is adjusted to the point where it can be landed.

**Comment by jrmuizel** [comment]
Building [wrench](https://github.com/servo/webrender/tree/master/wrench) with this branch brings the number of memcpy's down from 4206 to 3611 and the sum of sizes from 167776 to 133643

**Comment by jrmuizel** [comment]
https://github.com/jrmuizel/pdb-downloader memcpy counts go from 124 to 88

**Comment by nikic** [comment]
@jrmuizel Thanks for checking! Those are nice results -- although they should that we still have a ways to go...

I'll wait for #82783 to land before updating this, as the submodule will conflict anyway.

**Comment by nikic** [comment]
Now that the other PR has landed, I've pushed the commits to the main llvm-project repo. I've also updated the PR description.

**Comment by bstrie** [comment]
Is this a candidate for a codegen test?

**Comment by nagisa** [comment]
One _could_ probably write one, but as with all things optimisation, its a best-effort-basis kind of thing and, I imagine, it'd be pretty difficult to find a test case that's reliable over time and yet tests this particular improvement in a meaningful way.

I'm inclined to trust the LLVM test suite for this one.

**Comment by bjorn3** [comment]
```
2021-03-10T08:42:12.6022087Z Prepare workflow directory
2021-03-10T08:42:12.6826640Z Prepare all required actions
2021-03-10T08:42:12.7662338Z ##[group]Run exit 1
2021-03-10T08:42:12.7662842Z [36;1mexit 1[0m
2021-03-10T08:42:12.8239443Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2021-03-10T08:42:12.8240152Z ##[endgroup]
2021-03-10T08:42:12.8897530Z ##[error]Process completed with exit code 1.
```

**Comment by nikic** [comment]
Bugpoint: https://gist.github.com/nikic/cf38d27f12b98165cecbf2f17c01118a

**Comment by nikic** [comment]
Picked up the fix for the PowerPC hang. This also includes the fix for #80810 now, as it landed in the submodule in the meantime.

@bors r=nagisa

**Comment by glandium** [comment]
While the issues that have been closed are indeed fixed to some extent, I'm not particularly convinced they're intrinsically fixed. It feels like you could still be unlucky with the optimizer. And that's not mentioning that the problems still exist with unoptimized builds. Or with cranelift, I suppose.

**Comment by bstrie** [comment]
@glandium What more could be done? Indeed, you might still get unlucky with the optimizer, but the closed issues in question can also be generally characterized by "I got unlucky with the optimizer".

**Comment by nikic** [comment]
@bstrie There's two dimensions to this problem: The optimization problem, which is mostly resolved by this change, and the language semantics problem, which is not. Rust has neither placement new nor guaranteed NRVO, both of which may be desirable to provide hard guarantees that certain copies do not occur (e.g. that if you box a value, no stack allocation will be created even in completely unoptimized builds). I believe the closed issues all refer to optimization problems and we have separate issues to track the language semantics.

**Pull request merged**
