### PR TITLE
Add OsStringExt::from_wide_ptr for windows

### PR DESCRIPTION
**Pull request by bozaro**
This method is like CStr::from_ptr for wchar_t\* null-terminated strings

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! 

I'd feel a little uneasy about adding this as I think it's conflating the concept of a "C wide string" and an "OS string". For the standard library an OS string does not guarantee nor require a trailing nul, but a C string does (as do wide C strings). In some sense I think we may want a `WideString` or `CWideString` type which is the exact same interface as `CString` except with `s/u8/u16/`. That way this'd just be `CWideStr::from_ptr(...)` and you'd pass that to `from_wide`, like you do with `CString` and `OsString::from_bytes` today.

That's a pretty weighty addition, though, so we may not want to tackle it just yet. Thoughts from others on @rust-lang/libs?

**Comment by retep998** [comment]
Most of the time, when getting strings from windows API, you usually provide the buffer yourself. It is somewhat rare for Windows API to return a pointer to a buffer that you don't own. If anything, a `from_wide_null` which took a slice and only read up to the first null terminator would be more useful. Having a `from_wide_ptr` but not a `from_wide_null` may cause people to use `from_wide_ptr` even when they own the buffer and so should use something like `from_wide_null`.

**Comment by bozaro** [comment]
@alexcrichton
C++ `std::wstring` type defined as `std::basic_string<wchar_t>`, but `sizeof(wchar_t)` is platform depended (4 bytes on Linux, 2 bytes on Windows). In this case `CWideString` can't have platform independed signature.

**Comment by aturon** [comment]
@alexcrichton I agree that, in terms of fitting with existing std practice, we'd want to isolate a separate `CString`-like type here.

**Comment by retep998** [comment]
Would this `CWideString` type actually wrap `[u16]`, so that you could pass them directly to winapi functions without having to convert to and from WTF-8?

This sounds like a perfect opportunity for someone ___cough___ to flesh out the design in an external crate and then have an RFC to merge it into std.

**Comment by bozaro** [comment]
Ok. I'm starting to write RFC for CWideString. It will take some time.

**Comment by alexcrichton** [comment]
Ok, I'm gonna close this in favor of a future pending RFC, but thanks regardless for the PR @bozaro!

**Comment by bozaro** [comment]
Sorry for a long delay, but I created RFC: https://github.com/rust-lang/rfcs/issues/1773

**Comment by alexcrichton** [comment]
Thanks @bozaro!

**Pull request closed without merging**
