### PR TITLE
Remove a HACK by instead inferring opaque types during expected/formal type checking

### PR DESCRIPTION
**Pull request by oli-obk**
I was wondering why I couldn't come up with a test that hits the code path of the argument check checking the types we inferred from the return type... Turns out we reject those attempts early during fudging.

I have absolutely no information for you as to what kind of type inference changes this may incur, but I think we should just land this out of two reasons:

* had I found the other place to use opaque type inference on before I added the hack, we'd be using that today and this PR would never have happened
* if it is possible to hit this path, it requires some god awful recursive RPIT logic that I doubt anyone would have written without actively trying to write obscure code

r? @ghost

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors try

let's still crater it

**Comment by oli-obk** [comment]
@craterbot check

**Comment by oli-obk** [comment]
All of the regressions are spurious (either repro on master or are just disk out of space)

**Comment by compiler-errors** [comment]
Yeah, I'm happy with landing this now.

@bors r+

**Pull request merged**
