### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
Successful merges:

 - #52286 (Deny bare trait objects in src/librustc_errors)
 - #52306 (Reduce the number of clone()s needed in obligation_forest)
 - #52338 (update miri)
 - #52385 (Pass edition flags to compiler from rustdoc as expected)
 - #52392 (AsRef doc wording tweaks)
 - #52430 (update nomicon)
 - #52434 (Enable incremental independent of stage)
 - #52435 (Calculate the exact capacity for 2 HashMaps)
 - #52446 (Block beta if clippy breaks.)

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
Oh dang... yeah, combining the PR that fixes miri and another PR that breaks miri by renaming half the things into one leads to trouble.^^

**Comment by kennytm** [comment]
@bors r+

Removed #52338 (miri conflicts with latest master again)
Added #52429, #52286, #52306, #52435.

**Comment by RalfJung** [comment]
Somehow this doesn't really seem to be in the queue? Let's see if this works.

@bors retry

**Comment by RalfJung** [comment]
Compiler-bultins related... so probably #52431 is the culprit?

**Comment by kennytm** [comment]
No the error comes from libcore

```
[00:23:31] LLVM ERROR: Do not know how to split the result of this operator!
[00:23:31] 
[00:23:31] [RUSTC-TIMING] core test:false 46.302
[00:23:31] [0m[0m[1m[31merror:[0m Could not compile `core`.
```

I think the stdsimd one is more relevant. I'll remove both from the rollup anyway.

**Comment by kennytm** [comment]
@bors r+

Removed #52429, #52431 (suspected to cause libcore build failure on PowerPC)
Added #52338, #52434, #52446, #52385

**Pull request merged**
