### PR TITLE
Add -Z binding-stats

### PR DESCRIPTION
**Pull request by sanxiyn**
For some reasons, people like to discuss the number of immutable and mutable bindings in Rust codes: [example 1](https://www.reddit.com/r/rust/comments/3sf823/observations_bindings_immutable_by_default/), [example 2](https://www.reddit.com/r/rust/comments/3srvz0/ideas_about_features_which_may_be_useful_for_rust/). People's first impression is that mutable bindings are common; then invariably, experienced Rust users report that they are not. Numbers like 5%, 10%, 20% are thrown around. Since the compiler knows the answer, let's make it available.

Running this on core, std, syntax reports that 20%, 22%, 17% of local bindings are mutable, confirming the folklore.

### CODE REVIEW

**Comment by nrc** [comment]
I think this would be better as an external tool - it would be just as easy to implement there and I don't feel like there is a good reason to have this in the compiler. I think we have been keen to avoid adding options ad infinitum too (although I feel a bit hypocritical having just added `-Zinput-stats` - in that case the motivation is to add that data to compile-time benchmarking, so we really need it in the compiler. I also think that LOC, etc. is a more fundamental statistic than the number of bindings).

Interesting results though!

cc @rust-lang/compiler, @rust-lang/tools

**Comment by eddyb** [comment]
I think we could handle statistics with a lint, albeit it might be tricky to store the data.

**Comment by alexcrichton** [comment]
Yeah while this is a neat tool I'm not a huge fan of aggressively expanding the `-Z` options.

**Comment by sanxiyn** [comment]
What would be the best way to implement this as an external tool?

**Comment by nrc** [comment]
@sanxiyn I wrote a tutorial here: https://github.com/nrc/stupid-stats

**Comment by sanxiyn** [comment]
Ok, thanks.

**Pull request closed without merging**
