### PR TITLE
Fix sidebar background

### LINKED ISSUE #99691: rustdoc: mobile sidebar has gap at top and bottom
Steps to reproduce:

1. In mobile Chrome, visit https://doc.rust-lang.org/nightly/std/index.html.
2. Click the hamburger menu in upper left.

Expected results:

Sidebar opens and presents a solid background with no gaps.

Actual result:

Sidebar opens and there is a gap at top and bottom showing the main page.

image

This is a regression from beta to nightly. Possibly related to @GuillaumeGomez's recent refactoring of how colors are applied for themes.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #99691.

cc @jsha
r? @notriddle

### CODE REVIEW

**Comment by jsha** [comment]
Can you link to the PR where this was introduced?

**Comment by GuillaumeGomez** [comment]
The PR for this change in particular is https://github.com/rust-lang/rust/pull/93048. However it's not this one. I looked for a bit why it was suddenly broken but my guess is that the removal from the themes and moving it directly into `rustdoc.css` is what triggered this bug.

**Comment by jsha** [comment]
@GuillaumeGomez, can you nominate this for backport?

**Comment by GuillaumeGomez** [comment]
Thanks for checking. :)

**Pull request merged**
