### PR TITLE
Handle extern functions and statics in save-analysis

### PR DESCRIPTION
**Pull request by nrc**
r? @eddyb

### CODE REVIEW

**Comment by arielb1** [comment]
```
thread 'rustc' panicked at 'Name not in signature?', /checkout/src/libcore/option.rs:785

note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...

error: Could not compile `rustc_llvm`.
```

**Comment by arielb1** [comment]
Still broken, same error:
```
thread 'rustc' panicked at 'Name not in signature?', /checkout/src/libcore/option.rs:785

note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...

error: Could not compile `rustc_llvm`.

```

@bors r-

**Comment by nrc** [comment]
@arielb1 how do I repro this? We're passing everything on Travis and running `x.py test` locally is fine too.

**Comment by arielb1** [comment]
@nrc 

Try doing  `../x.py dist`.

**Comment by nrc** [comment]
Nope, `dist` works fine. This looks like a specific save-analysis error, but the only place (iirc) we run save-analysis in the the test suite is in two tests in run-make - both of which run fine. My only thought is that this is due to a combination of this PR and another one in the rollup? But I don't see anything that would affect save-analysis in the rollup. I've rebased and am running tests again locally to see if I can repro...

**Comment by nrc** [comment]
@bors: r=eddyb

Yet again, I still can't repro any failure with test or dist (which suggests that the problem is not with another PR, but perhaps platform specific?). I don't see any way to debug this further without bors having a run over it. I suppose this will fail and waste some time, but otherwise I'm stuck.

Please don't rollup this PR (or r- it).

**Comment by alexcrichton** [comment]
@bors: retry

* ar.exe error - https://github.com/rust-lang/rust/issues/40546

**Comment by frewsxcv** [comment]
@bors retry

prioritizing rollup

**Comment by frewsxcv** [comment]
@bors retry

prioritizing rollup

**Comment by alexcrichton** [comment]
@bors: retry

* failed to compile openssl https://github.com/rust-lang/rust/issues/40417

**Comment by frewsxcv** [comment]
@bors retry

prioritizing rollup which includes these changes

**Pull request merged**
