### PR TITLE
Update miri

### PR DESCRIPTION
**Pull request by matthewjasper**
r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
r=me when Travis is green

**Comment by Centril** [comment]
Thank you both for this!

cc https://github.com/rust-lang/rust/pull/58739

@bors p=9

**Comment by matthewjasper** [comment]
@bors r=RalfJung

Cancel this if a MIRI gets a PR for #59119 before this lands.

**Comment by RalfJung** [comment]
@bors r-

Could you update to include https://github.com/rust-lang/miri/pull/677 ?

**Pull request merged**
