### PR TITLE
Remove useless allocations in macro_rules follow logic.

### LINKED ISSUE #61543: macro_rules follow logic allocates uselessly in the happy path
E.g. in https://github.com/rust-lang/rust/blob/ab7cf71d4c6dd1696cb0eb52ad172bce296578cc/src/libsyntax/ext/tt/macro_rules.rs#L1045 a vec is created, only to be thrown away if the macro actually works out. I think we can just turn most places into an early return in the happy path and then only allocate in the error path.

Do not work on this issue before https://github.com/rust-lang/rust/pull/61541 is merged.

Also, https://github.com/rust-lang/rust/blob/ab7cf71d4c6dd1696cb0eb52ad172bce296578cc/src/libsyntax/ext/tt/macro_rules.rs#L1015 hasn't had its docs updated to reflect the source changes.

### PR DESCRIPTION
**Pull request by ghost**
Closes  #61543

### CODE REVIEW

**Review by Centril — APPROVED** [review]

**Review by mark-i-m — APPROVED** [review]

**Comment by Centril** [comment]
@rust-timer build 3f61c6a7b2a8230929768c1dc3b86e2fdd495222

**Comment by Centril** [comment]
Seems like noise mostly if possibly a perf improvement. 👍 

r? @Centril @bors r+ rollup

**Pull request merged**
