### PR TITLE
change OpenOptions to Self in std::os::windows::fs

### LINKED ISSUE #49961: Trait method `std::os::windows::fs::OpenOptionsExt::security_qos_flags()` returns a `&mut OpenOptions` instead of `&mut Self`
https://doc.rust-lang.org/src/std/sys/windows/ext/fs.rs.html#279-281

There's no reason for that method to return a concrete type instead of `Self`. I am currently writing an `OpenOptions` wrapper and that method is preventing me from implementing `OpenOptionsExt` for the wrapper. However, the trait is already stable (even if most likely unimplemented outside `libstd`) so I'm not sure what's the proper way of changing this?

### PR DESCRIPTION
**Pull request by csmoe**
Fixes #49961

### CODE REVIEW

**Comment by retep998** [comment]
Probably needs a crater run but I am very much in favor of this change.

**Comment by kennytm** [comment]
Is there a "grep only" mode which checks if `security_qos_flags` is referenced anywhere, and only check those crates 😂

**Comment by Mark-Simulacrum** [comment]
Oh. Right. No, we don't. 

However, I believe successfully (though hard to confirm), I've checked crates.io and GH apps that we test and none of them contain any mention of `security_qos_flags`. So I think we can proceed with this given @rust-lang/libs approval.

**Comment by est31** [comment]
`all-crate-grep` ([link](https://github.com/est31/cargo-local-serve/blob/master/all-crate-grep/main.rs)) gives me:
```
[15980/87305] Match found in combine v 1.3.0 file combine-1.3.0/test2.exe
[15981/87305] Match found in combine v 2.0.0-beta file combine-2.0.0-beta/test2.exe
[23832/87305] Match found in esplugin-ffi v 1.0.0 file esplugin-ffi-1.0.0/build/Debug/ffi_cpp_tests.exe
[23832/87305] Match found in esplugin-ffi v 1.0.0 file esplugin-ffi-1.0.0/build/Debug/ffi_cpp_tests.ilk
[23832/87305] Match found in esplugin-ffi v 1.0.0 file esplugin-ffi-1.0.0/build/Debug/ffi_cpp_tests.pdb
[21898/87305] Match found in dynlib v 0.1.0 file dynlib-0.1.0/src/test_dll.dll
[21898/87305] Match found in dynlib v 0.1.0 file dynlib-0.1.0/src/test_dll.dll.exp
[21898/87305] Match found in dynlib v 0.1.0 file dynlib-0.1.0/src/test_dll.dll.lib
[21898/87305] Match found in dynlib v 0.1.0 file dynlib-0.1.0/src/test_dll.pdb
[23833/87305] Match found in esplugin-ffi v 1.0.1 file esplugin-ffi-1.0.1/build/Debug/ffi_cpp_tests.exe
[23833/87305] Match found in esplugin-ffi v 1.0.1 file esplugin-ffi-1.0.1/build/Debug/ffi_cpp_tests.ilk
[23833/87305] Match found in esplugin-ffi v 1.0.1 file esplugin-ffi-1.0.1/build/Debug/ffi_cpp_tests.pdb
[58116/87305] Match found in process-memory v 0.2.2 file process-memory-0.2.2/process_dll.dll
[52445/87305] Match found in optimization v 0.0.1 file optimization-0.0.1/target-install/release/build/cargo-clippy-c892acf8ec768dd7/build-script-build.exe
[58117/87305] Match found in process-memory v 0.2.3 file process-memory-0.2.3/process_dll.dll
```

Not a single match in a rs file :)

**Comment by alexcrichton** [comment]
Thanks for the PR @csmoe! 

I [left a comment](https://github.com/rust-lang/rust/issues/49961#issuecomment-381622188) on the original issue, but it's very much not intended that these extension traits are implemented externally for other types. In that sense I would be very hesitant to land this and would actually prefer going the opposite direction, preventing it from being able to happen in the first place! (although that is itself also a breaking change)

**Comment by csmoe** [comment]
@alexcrichton Ok, I preferred  not to change that at the beginning. Then I thought this modification wouldn’t affect too much codes, so I made a PR. 
It’ll be better to close this from your discussion.

**Pull request closed without merging**
