### PR TITLE
Pass opaque types for the `type_alias_bounds` lint

### LINKED ISSUE #108617: Spurious "bounds [...] not enforced in type aliases" when using TAIT
### Code

```Rust
#![feature(type_alias_impl_trait)]

use std::fmt::Debug;

type Foo<T: Debug> = (impl Debug, usize);

fn foo<U: Debug>() -> Foo<U> {
    (Vec::<U>::new(), 1234)
}
```

### Current output

```
warning: bounds on generic parameters are not enforced in type aliases
 --> src/main.rs:5:13
  |
5 | type Foo<T: Debug> = (impl Debug, usize);
  |             ^^^^^
  |
  = note: `#[warn(type_alias_bounds)]` on by default
help: the bound will not be checked when the type alias is used, and should be removed
  |
5 - type Foo<T: Debug> = (impl Debug, usize);
5 + type Foo<T> = (impl Debug, usize);
  |
```

### Desired output

No warning at all, I think, since the bound _is_ actually checked; applying the suggestion yields code that does not compile.

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mu001999**
Fixes #108617

### CODE REVIEW

**Comment by lcnr** [comment]
r? @oli-obk 

do we convert the whole type alias to an opaque for `type Foo<T: Debug> = (impl Debug, usize);` :thinking:

**Comment by oli-obk** [comment]
I think we should still lint if the non-opaque types contain generic params of the type alias.

Also: please add a bunch of tests for various cases (other types using generic params, other types not using them, ...)

**Comment by MU001999** [comment]
Sorry, some tests failed, I will check the code.

**Comment by MU001999** [comment]
@oli-obk I have tried to only lint bounds whose ty is a generic parameter used in the non-opaque types if there is an opaque type. You can see the new commits. But it still lead to some false positives. For the following code, the bound `T: 'a` cannot be removed and will trigger the warning:
```rust
#![feature(type_alias_impl_trait)]
#![allow(dead_code)]

use std::fmt::Debug;

type Foo<'a, T: 'a> where &'a T: Debug = (impl Debug + 'a, T);
fn foo<'a, U: Debug + 'a>(v: U) -> Foo<'a, U> where &'a U: Debug {
    (Vec::<&'a U>::new(), v)
}
```

So, I think the best way is to not lint the type when meeting opaque types. What do you think?

**Comment by lcnr** [comment]
just want to throw this out there, but could we change **only** type aliases with opaque types to actually get treated as alias types and completely disable the lint for those?

I think our longterm goal is to check wf for trait aliases anyways, so this feels like a step in the right direction :thinking:

**Comment by oli-obk** [comment]
> could we change **only** type aliases with opaque types to actually get treated as alias types

you mean, adding `TyKind::Alias` but only using it for type aliases that have an opaque type in them?

> longterm goal is to check wf for trait aliases anyways

I think you mean *type* aliases, but yes 😆

**Comment by MU001999** [comment]
Sounds good, maybe this PR should be closed :)

**Comment by oli-obk** [comment]
Thanks for opening the PR! We found a good design due to it, I'll assign the issue to myself

**Pull request closed without merging**
