### PR TITLE
Fix unreachable_pub suggestion for enum with fields

### LINKED ISSUE #103317: Invalid unreachable_pub suggestion for enum with fields
Given the following code:

```rust
#[warn(unreachable_pub)]
mod inner {
    #[allow(unused)]
    pub enum T {
        A(u32),
    }
}
```

The current output is:

```
warning: unreachable `pub` item
 --> src/main.rs:4:5
  |
4 |     pub enum T {
  |     ---^^^^^^^
  |     |
  |     help: consider restricting its visibility: `pub(crate)`
  |
note: the lint level is defined here
 --> src/main.rs:1:8
  |
1 | #[warn(unreachable_pub)]
  |        ^^^^^^^^^^^^^^^
  = help: or consider exporting it for use by other crates

warning: unreachable `pub` field
 --> src/main.rs:5:11
  |
5 |         A(u32),
  |           -^^
  |           |
  |           help: consider restricting its visibility: `pub(crate)`

```

Which basically brokes cargo-fix, i.e `cargo fix --broken-code` produces invalid code:

```rust
#[warn(unreachable_pub)]
mod inner {
    #[allow(unused)]
    pub(crate) enum T {
        A(pub(crate)u32),
    }
}
```

That seems to affect any enum with variant fields.

### PR DESCRIPTION
**Pull request by l4l**
Resolves #103317

### CODE REVIEW

**Comment by wesleywiser** [comment]
r? compiler

**Comment by nagisa** [comment]
Doing a quick first pass, will take a closer look later this week.

Would it make sense to also add a `run-rustfix` test for this, given that the issue mentions `cargo fix` doing wrong replacements?

I would even consider adding a test without `#[allow(unused)]`, as AFAICT it doesn’t actually impact the scenario this is testing for (took me a moment to understand this.)

**Comment by l4l** [comment]
Ooh, there are tests for rustfix, that's really nice, will add one.

> I would even consider adding a test without #[allow(unused)]

You mean adding an additional one for run-rustfix, right? There are a lot of warnings for cargo-check (check-pass).

**Comment by l4l** [comment]
Added .fixed file for the same test and put `allow(unused)` closer to the `enum` which seems to be clearer.

**Comment by nagisa** [comment]
> You mean adding an additional one for run-rustfix, right? There are a lot of warnings for cargo-check (check-pass).

Yeah, but upon further review I don’t believe that’s necessary at all.

@bors r+ Thanks!

(Side note: it is quite unfortunate that the lint callback infrastructure requires us to figure if a field belongs to an enum variant after the fact, rather than allowing to just change this entire visitor to skip walking enums in the first place. Welp.)

**Pull request merged**
