### PR TITLE
Compute `lint_levels` by definition

### LINKED ISSUE #95094: Experiment computing lint_levels by definition
The `lint_levels` query traverses the whole crate to assign a set of lint and allowances to each `HirId`.

However, most incremental modifications to a crate don't involve many items. Computing `lint_levels` independently for each definition will help reduce the effect of recomputing it. The objective is to avoid lowering of some definitions once https://github.com/rust-lang/rust/pull/88186 is merged.

Steps: not defined yet. Please make contact on Zulip to discuss and define them.

### PR DESCRIPTION
**Pull request by fee1-dead**
Closes #95094.

cc @cjgillot

### CODE REVIEW

**Comment by fee1-dead** [comment]
cc @xFrednet this touches impl for lint expectations

**Comment by nagisa** [comment]
r? rust-lang/compiler

Not able to take on large reviews for the time being.

**Review by davidtwco — APPROVED** [review]
Not exceptionally familiar with the lint level computation but this seems reasonable (when not considering the big perf regression), will re-assign to cjgillot though.

**Comment by fee1-dead** [comment]
Yeah, I'm going to need some help regarding the perf hits here. @cjgillot could you take a look?

**Review by cjgillot — COMMENTED** [review]
You caught a bad case of incremental compilation invalidation.

When the incr. comp. engine tries to mark a query as green, it first checks whether all its dependencies are green.  `lint_levels_on` depends on `resolutions`, which is always red.
As it can trivially mark `lint_levels_on` as green, the incr. comp. engine tries to recompute the query. The query takes a `HirId` but the incr. comp. engine does not know how to make a `HirId` from its `Fingerprint`. So it cannot recompute the query, and marks `lint_levels_on` as red.
As a consequence, all queries that call it (= pretty much everything) get recomputed.

There are 2 possibilities here:
1. compute `lint_levels_on` by definition: for a whole item/trait-item/impl-item/foreign-item at once, and make `lint_levels_on` take a `LocalDefId`;
2. teach the query system to force a query that takes a `HirId`.

(1) may need to a larger refactor of the levels computation.  It will avoid the query call overhead (there are *many more* `HirId`s that `LocalDefId`s), but that overhead only appears as a ~1% regression, so that's probably fine.

(2) is a bit more experimental.  For this, you need to:
- add a variant to `rustc_query_system::dep_graph::FingerprintStyle`;
- return it in the `<HirId as DepNodeParams>::fingerprint_style` in `rustc_middle::dep_graph::dep_node`;
- modify `to_fingerprint` and `recover` in that method have a bidirectional conversion `Fingerprint <-> HirId` (look at what `LocalDefId` does for instance).

**Comment by fee1-dead** [comment]
rebase; no work yet

**Comment by fee1-dead** [comment]
Closing in favor of #101620. Thank you for working on this @cjgillot!

**Pull request closed without merging**
