### PR TITLE
Crater 2024 edition test

### PR DESCRIPTION
**Pull request by ehuss**

### CODE REVIEW

**Comment by ehuss** [comment]
@craterbot check crates=top-1000 p=1

**Comment by matthiaskrgr** [comment]
Out of curiosity, what does this do?
Compile top 1000 edition=2021 crates with edition=2024 and sees how it goes?

**Comment by ehuss** [comment]
It compiles them with 2021, collects diagnostics to migrate to 2024 and applies them, then compiles again with 2024 to ensures that works.

**Comment by matthiaskrgr** [comment]
Does this cover anything beyond the 2024 lint group?
`    rust-2024-compatibility  static-mut-refs, unsafe-op-in-unsafe-fn`

**Comment by ehuss** [comment]
This is just testing `unsafe-op-in-unsafe-fn`.

**Comment by ehuss** [comment]
@craterbot check crates=top-5000 p=1

**Comment by ehuss** [comment]
@craterbot check crates=top-5000 p=1

**Comment by ehuss** [comment]
@craterbot check p=1

**Comment by ehuss** [comment]
@craterbot check cap-lints=allow

**Pull request closed without merging**
