### PR TITLE
Defer Apple SDKROOT detection to link time.

### LINKED ISSUE #36156: Targets filtered out too early
Targets like `aarch64-apple-ios` don't appear under `--print target-list` with today's nightly (and latest beta):

```
$ rustc --print target-list | grep ios || echo (empty)
(empty)
```

but they appear there if I use the latest stable:

```
$ rustup run stable rustc --print target-list | grep ios
aarch64-apple-ios
armv7-apple-ios
armv7s-apple-ios
i386-apple-ios
x86_64-apple-ios
```

It's not like they just don't appear under the list of built-in targets. Using `--target aarch64-apple-ios` also says that the target doesn't exist

```
$ rustc --target aarch64-apple-ios --print cfg
error: Error loading target specification: Could not find specification for target "aarch64-apple-ios"
```

The weird thing is that you _can_ `rustup target add aarch64-apple-ios` but then you can't use the target:

```
$ rustup target add aarch64-apple-ios
info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
$ rustc --target aarch64-apple-ios --print cfg
error: Error loading target specification: Could not find specification for target "aarch64-apple-ios"
```
### Meta

```
$ rustc -V
rustc 1.13.0-nightly (77d2cd28f 2016-08-29)
$ rustup run beta rustc -V
rustc 1.12.0-beta.2 (389dad798 2016-08-24)
$ rustup run stable rustc -V
rustc 1.11.0 (9b21dcd6a 2016-08-15)
```

cc @alexcrichton

### LINKED ISSUE #76584: aarch64-apple-ios cannot be cross-compiled from Linux and causes cargo doc failures
All up there seems to two issues:

- Docs cannot be generated for iOS from non-macOS hosts because of a dependency on a binary for generating linker flags that only exists on macOS
- Errors are not being propagated from this part of the build process to rustbuild, leaving for a headscratcher

I added an `aarch64-apple-ios` requirement to the docs.rs metadata in one of my crates, which caused a build failure on docs.rs. https://github.com/rust-lang/docs.rs/issues/1040

Upon trying to reproduce this issue and find a fix, I _hit_ the issue while trying to build rustc with the target `aarch64-apple-ios` from an x86_64 Linux host.

```
$ ./x.py build --target aarch64-apple-ios
Updating only changed submodules
Submodules updated in 0.02 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s


error occurred: No such file or directory (os error 2)


failed to run: /.../rust/build/bootstrap/debug/bootstrap build --target aarch64-apple-ios
Build completed unsuccessfully in 0:00:00
```

Not ideal output. 😛 

The reason this happens is quite straightforward: ios and tvos targets use the [apple_sdk_base](https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/apple_sdk_base.rs) module to resolve the `pre_link_args` field, and it is fallable.

The logic in the `get_sdk_root` function seems a little faulty, as it does a simple check for existence of a directory from the environment variable `SDKROOT`, then if that fails, it tries to run the `xcrun` binary which only exists on macOS hosts. That xcrun failure is a hard failure.

As stated in https://github.com/rust-lang/docs.rs/issues/1040, a workaround for at least generating documentation is to provide `SDKROOT` with a path to an empty directory to `iPhoneOS.platform`.

No such issue occurs on `*-apple-darwin` because an entirely different codepath is taken.

I am not sure of the right course of action to fix this:

1. Change ios and tvos targets to not require `pre_link_flag`s to be set, like macOS, and let build failures occur after printing a warning so the user can at least fix the issue
1. Add a hack for `doc` so that at least docs.rs can generate documentation for ios
1. Don't change this behaviour at all, but fix the error message so that cross-compiling devs won't just stare blindly at their screen asking "why me"

My preference is for the first option, and I'm quite happy to contribute a fix for it, though I would need assistance in successfully cross-compiling rustc for macOS from Linux. 😄 

---

It is probable that this is the same issue: https://github.com/rust-lang/rust/issues/42084.

### PR DESCRIPTION
**Pull request by ehuss**
This defers the detection of the SDKROOT for Apple iOS/tvOS targets to link time, instead of when the `Target` is defined. This allows commands that don't need to link to work (like `rustdoc` or `rustc --print=target-list`). This also makes `--print=target-list` a bit faster.

This also removes the note in the platform support documentation about these targets being missing. When I wrote it, I misunderstood how the SDKROOT stuff worked.

Notes:
* This means that JSON spec targets can't explicitly override these flags. I think that is probably fine, as I believe the value is generally required, and can be set with the SDKROOT environment variable.
* This changes `x86_64-apple-tvos` to use `appletvsimulator`. I think the original code was wrong (it was using `iphonesimulator`). Also, `x86_64-apple-tvos` seems broken in general, and I cannot build it locally. The `data_layout` does not appear to be correct (it is a copy of the arm64 layout instead of the x86_64 layout). I have not tried building Apple's LLVM to see if that helps, but I suspect it is just wrong (I'm uncertain since I don't know how the tvOS simulator works with its bitcode-only requirements).
* I'm tempted to remove the use of `Result` for built-in target definitions, since I don't think they should be fallible. This was added in https://github.com/rust-lang/rust/pull/34980, but that only relates to JSON definitions. I think the built-in targets shouldn't fail. I can do this now, or not.

Fixes #36156
Fixes #76584

### CODE REVIEW

**Comment by lcnr** [comment]
Not something I can review

r? @Mark-Simulacrum for review or reassignment

**Comment by petrochenkov** [comment]
LGTM, except that I'd move `add_apple_sdk` from inside `add_pre_link_args` to the outside.

>I'm tempted to remove the use of `Result` for built-in target definitions, since I don't think they should be fallible.

This change affects all target specs, better do it in a separate PR.

**Comment by Mark-Simulacrum** [comment]
I feel like we should at least split the tvOS change into a separate commit (if not PR). I don't think we have anyone (maybe even anyone we can ping) that can answer questions on what the proper thing is for those platforms, but I'm not inclined to block seemingly correct changes on tracking someone down either.

**Comment by shepmaster** [comment]
FWIW, I pulled this PR into #77239 where I was doing a try build for aarch64-apple-darwin and the build succeeded.

**Comment by ehuss** [comment]
> LGTM, except that I'd move `add_apple_sdk` from inside `add_pre_link_args` to the outside.

Yea, I couldn't decide where to put it.  It doesn't really fit in `add_pre_link_args` so I moved it out.

> I feel like we should at least split the tvOS change into a separate commit

I can't really do that. The SDK is chosen by the target_os in the Target. I could just swap `appletvsimulator` with `iphonesimulator`, but I'm like 95% certain that's wrong.  It used `appletvsimulator` before 6b17330ef4f9a97bd539b55edb4e7ccdb6c00133, and that was just a refactoring that appears to have used the wrong value.   

@simlay, can you answer the questions here?  It looks like [this line](https://github.com/rust-lang/rust/blob/623fb90b5a1f324e0ec44085116bf858cef19a00/compiler/rustc_target/src/spec/x86_64_apple_tvos.rs#L5) should have used `AppleOS::tvOS`, is that correct?  Also, I am unable to build the x86_64-apple-tvos target because the `data_layout` does not appear correct (it is using the aarch64 layout, not x86-64).  Should that be changed?  Are there any other instructions on how to build that target (does it need Apple's LLVM?)?

**Comment by simlay** [comment]
>  It used appletvsimulator before 6b17330, and that was just a refactoring that appears to have used the wrong value.

Bleh. It looks like I screwed up in that PR. My bad. I was trying to refactor it so we could add watchOS without much work.

> @simlay, can you answer the questions here? It looks like this line should have used AppleOS::tvOS, is that correct?

Yes.

> Also, I am unable to build the x86_64-apple-tvos target because the data_layout does not appear correct (it is using the aarch64 layout, not x86-64). Should that be changed?

Yes.

> Are there any other instructions on how to build that target (does it need Apple's LLVM?)?

This I unfortunately do not know.

This PR is good. It makes the logic clearer. Once someone figures out the the `data_layout` and such parameters for the watchOS targets, it'll be a pretty small PR.

**Comment by Mark-Simulacrum** [comment]
It looks like @ehuss implemented what @petrochenkov asked for -- I am going to r? @petrochenkov since this is not an area I'm familiar with.

**Comment by petrochenkov** [comment]
@ehuss 
>I'm tempted to remove the use of `Result` for built-in target definitions, since I don't think they should be fallible.

Do you still plan to make this change?
If not then I'll do it today, it'd be a very nice cleanup to `rustc_target`.

**Comment by ehuss** [comment]
I was not planning to do that in the foreseeable future.  Please go ahead!

**Comment by petrochenkov** [comment]
@ehuss 
Done - https://github.com/rust-lang/rust/pull/77580.

**Pull request merged**
