### PR TITLE
Remove the full-bootstrap builder from CI

### LINKED ISSUE #75198: full-bootstrap builder doesn't test anything
It's clocking in at 20 minutes and seems to be doing nothing -- I suspect that this might be a result of @jyn514's changes to x.py defaults but have not confirmed.

We should fix this.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #75198

### CODE REVIEW

**Comment by pietroalbini** [comment]
Thanks!

@bors r+

**Comment by ehuss** [comment]
Just to be clear, is the `full-bootstrap` option in `config.toml` broken?  If so, should it be fixed? Or should it be removed? Or should it be documented as being broken?

**Comment by pietroalbini** [comment]
Hmm, @Mark-Simulacrum?

**Comment by Mark-Simulacrum** [comment]
I am uncertain, but I personally would be in favor of removing support for it. I don't personally think it useful (which is why I'm fine with dropping tests for it).

**Comment by JohnTitor** [comment]
> 
> 
> I am uncertain, but I personally would be in favor of removing support for it. I don't personally think it useful (which is why I'm fine with dropping tests for it).

I'm happy to remove it too. But it should be in another PR as it may need some discussion and/or some other eyes, right?

**Comment by Mark-Simulacrum** [comment]
Yep, this PR is good to go. I will need to think some more on the general fate of full-bootstrap.

**Pull request merged**
