### PR TITLE
Remove mir::LocalDecl::internal.

### PR DESCRIPTION
**Pull request by cjgillot**
It does not serve any purpose, as we don't have typeck-based generator witnesses any more.

### CODE REVIEW

**Comment by oli-obk** [comment]
r=me with perf clean

r? @oli-obk

**Comment by cjgillot** [comment]
We now emit slightly more storage statements in MIR: the storage statements for `internal` locals were not emitted when inlining MIR. This is now more correct, and could benefit LLVM.

**Comment by nnethercote** [comment]
The biggest perf changes were in binary size, with lots of small reductions, which is nice.

@rustbot label: +perf-regression-triaged

**Pull request merged**
