### PR TITLE
resolve: Do not error on access to proc macros imported with `#[macro_use]`

### PR DESCRIPTION
**Pull request by petrochenkov**
This error is artificial, but previously, when `#[macro_use] extern crate x;` was stable, but non-derive proc macros were not, it worked like kind of a feature gate. Now both features are stable, so the error is no longer necessary.

This PR simplifies how `#[macro_use] extern crate x;` works - it takes all items from macro namespace of `x`'s root and puts them into macro prelude from which they all can now be accessed.

### CODE REVIEW

**Comment by alexcrichton** [comment]
While this seems plausible to me, I'd defer to @rust-lang/lang in this regard as it's moreso a language change they'd likely wish to discuss.

Folks on @rust-lang/lang, how do you feel about `#[macro_use]`, a hopefully legacy attribute soon, working for new shiny new procedural macro attributes we've stabilized?

**Comment by joshtriplett** [comment]
Given that we're moving towards using `use` for macros, and `use` works for procedural macros, do we *want* to make `#[macro_use]` work for this?

**Comment by petrochenkov** [comment]
Given that `#[macro_use] extern crate ...` is being retired, I'd say that it largely doesn't matter from usability point of view whether this case is allowed or not.
My primary motivation for doing this is simplification of the rules and removal of technical debt from the compiler.

**Comment by joshtriplett** [comment]
@petrochenkov Fair enough. Sounds reasonable to me.

**Comment by Centril** [comment]
I also think it sounds reasonable :)
...we should discuss this further on the meeting,
...but to expedite things, let's:

@rfcbot fcp merge

**Comment by scottmcm** [comment]
If this is just allowing the compiler to delete code, not changing idioms,

@rfcbot reviewed

**Comment by petrochenkov** [comment]
Yay, FCP complete.
@bors r=alexcrichton

**Pull request merged**
