### PR TITLE
rename mir::Constant -> mir::ConstOperand, mir::ConstKind -> mir::Const

### PR DESCRIPTION
**Pull request by RalfJung**
Also, be more consistent with the `to/eval_bits` methods... we had some that take a type and some that take a size, and then sometimes the one that takes a type is called `bits_for_ty`.

Turns out that `ty::Const`/`mir::ConstKind` carry their type with them, so we don't need to even pass the type to those `eval_bits` functions at all.

However this is not properly consistent yet: in `ty` we have most of the methods on `ty::Const`, but in `mir` we have them on `mir::ConstKind`. And indeed those two types are the ones that correspond to each other. So `mir::ConstantKind` should actually be renamed to `mir::Const`. But what to do with `mir::Constant`? It carries around a span, that's really more like a constant operand that appears as a MIR operand... it's more suited for `syntax.rs` than `consts.rs`, but the bigger question is, which name should it get if we want to align the `mir` and `ty` types? `ConstOperand`? `ConstOp`? `Literal`? It's not a literal but it has a field called `literal` so it would at least be consistently wrong-ish...

@oli-obk any ideas?

### CODE REVIEW

**Comment by oli-obk** [comment]
r? @oli-obk 

`ConstOperand` seems best to me.

the `literal` field name is just an artifact from when MIR was created. we could rename it to `constant`

**Comment by bjorn3** [comment]
(why did triagebot not ping me for the cg_clif changes?)

**Comment by RalfJung** [comment]
It didn't ping anyone for the interpreter changes either. rustbot just entirely missed this PR in terms of pinging people.

**Comment by RalfJung** [comment]
> ConstOperand seems best to me.

Done that.

> the literal field name is just an artifact from when MIR was created. we could rename it to constant

I went with `const_` to match the type name.

**Comment by RalfJung** [comment]
FWIW smir still uses the old names, I was not sure what the process was for changing those. We should align them with the new internal names eventually, I hope.

**Comment by oli-obk** [comment]
Yea, we'll clean up on the SMIR side ourselves

**Pull request merged**
