### PR TITLE
Use parking lot's rwlock even without parallel-rustc

### PR DESCRIPTION
**Pull request by oli-obk**
Considering that this doesn't affect perf, I think we should use the simplest solution.

### CODE REVIEW

**Comment by SparrowLii** [comment]
Thanks for pushing this!

**Comment by oli-obk** [comment]
lol, good rustbot

**Comment by lqd** [comment]
I thought it was yet another bors ~~bug~~ vendetta against oli, but no it kinda makes sense, delegation gives r+ to the PR author which is also oli :)

**Comment by oli-obk** [comment]
🤦 

Should've been

@bors delegate=SparrowLii

**Pull request merged**
