### PR TITLE
Update cc to 1.0.77

### LINKED ISSUE #98746: Broken debug info with 1.62.0
Building Firefox with rustc 1.62.0 on Linux and running it under valgrind makes valgrind emit the following error:
```
==31382== Valgrind: debuginfo reader: ensure_valid failed:
==31382== Valgrind:   during call to ML_(img_get)
==31382== Valgrind:   request for range [3275670898, +4) exceeds
==31382== Valgrind:   valid image size of 1880027600 for image:
==31382== Valgrind:   "/builds/worker/workspace/obj-build/toolkit/library/build/libxul.so"
==31382==
==31382== Valgrind: debuginfo reader: Possibly corrupted debuginfo file.
==31382== Valgrind: I can't recover.  Giving up.  Sorry.
```
As of filing, I don't have more information to share yet, but I thought I'd already file it before starting to investigate it next week.

### PR DESCRIPTION
**Pull request by glandium**
Fixes (without a test) #98746.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=iffy

It would be good to add a test for this, I guess, so edited the description to avoid closing the issue for now (and labeled with E-needstest).

**Comment by glandium** [comment]
I suspect the failure could be a side effect of https://github.com/rust-lang/cc-rs/commit/0e51f6d8a05548bd9991bfd8184b45b77b261a17 . I'd suggest going with 1.0.77 for now, which only contains the wanted fix and the addition of the `Build::asm_flag` method, which wouldn't have side effects.

**Comment by ChrisDenton** [comment]
@glandium is there an issue for the 1.0.78 breakage? I'd guess this is essentially caused by mixing llvm and msvc tools somewhere along the line?

**Comment by glandium** [comment]
I didn't open an issue because it's not clear what's fault it is, and it's also not a problem unless you actively change the rustc tree. I figured the next person who upgrades cc will end up figuring it out.

**Pull request merged**
