### PR TITLE
Clean up some comments near `use` declarations

### PR DESCRIPTION
**Pull request by nnethercote**
#125443 will reformat all `use` declarations in the repository. There are a few edge cases involving comments on `use` declarations that require care. This PR cleans up some clumsy comment cases, taking us a step closer to #125443 being able to merge.

r? @lqd

### CODE REVIEW

**Comment by nnethercote** [comment]
Please review one commit at a time.

**Review by jieyouxu — APPROVED** [review]
Changes LGTM. I specifically checked the library changes and they don't seem to be exposing new docs (AFAICT the module-level docs are not publicly visible). Feel free to r=me unless you want a review from T-libs for the library changes.

**Comment by programmerjake** [comment]
the portable-simd stuff looks fine to me.

**Comment by nnethercote** [comment]
> Changes LGTM. I specifically checked the library changes and they don't seem to be exposing new docs (AFAICT the module-level docs are not publicly visible). Feel free to r=me unless you want a review from T-libs for the library changes.

Good enough for me. The changes are broad but trivial.

@bors r=jieyouxu

**Pull request merged**
