### PR TITLE
Add Seek instance for io::Take

### PR DESCRIPTION
**Pull request by wangbj**
Library tracking issue #97227.

### CODE REVIEW

**Comment by wangbj** [comment]
Note I added

```
#[unstable(feature = "seek_io_take", issue = "37214")]
```

Befreo `impl<T: Seek> for Take<T>` but rustc complaines:

```
     = note: `#[deny(ineffective_unstable_trait_impl)]` on by default
     = note: see issue #55436 <https://github.com/rust-lang/rust/issues/55436> for more information
```

**Comment by the8472** [comment]
`SeekFrom` [allows seeking beyond the end of an object](https://doc.rust-lang.org/stable/std/io/enum.SeekFrom.html#variant.End). This could be observable by doing `(&file).take(n).seek(m)` and then dropping the `Take` but continuing to operate on the file.

Since some branches clamp the seek value via `min` I think test-cases and documentation should cover what happens when the underlying source starts with a seek position beyond its end and when one tries to seek past its end. Some of those cases might be surprising or inconsistent with what `SeekFrom` says.

**Comment by wangbj** [comment]
@the8472 You are right if `.take(N)` return fewer than `N` bytes indeed cause issues (when calling `seek`). What would you suggest for the path forward? Do you think we could save `stream_position()` in `struct Take`?

**Comment by compiler-errors** [comment]
This is an `impl` of a public trait on a public type, and therefore insta-stable. Not sure if needs a tracking issue, but it is a T-libs-api issue instead of a T-libs one, per [this comment](https://github.com/rust-lang/rust/pull/97230#issuecomment-1133254784).

r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs

**Comment by compiler-errors** [comment]
@wangbj heads up that merge commits are not allowed in PRs. I recommend `git pull --rebase` instead in the future, and you should probably try to rework your git history so that merge commit is no longer included. See: https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy

**Comment by wangbj** [comment]
Close in flavor of #97807 97807

**Pull request closed without merging**
