### PR TITLE
assert_eq failure message easier to read

### PR DESCRIPTION
**Pull request by gilescope**
By having the left and right strings aligned with one another it helps spot the difference between the two far quicker than if they are on the same line. 

E.g.
Before:

```
thread 'tests::test_safe_filename' panicked at 'assertion failed: `(left == right)` left:  `"-aandb--S123.html"` right: `"-aandb-S123.html"`',
```

After:

```
thread 'tests::test_safe_filename' panicked at 'assertion failed: `(left == right)`
left:  `"-aandb--S123.html"`
right: `"-aandb-S123.html"`',
```

When the strings are both on the same line it take a lot longer to spot the difference. It is a small change but the small time savings add up with repetition. This would help Rust be an excellent language to write tests in out of the box.

Closes https://github.com/rust-lang/rust/issues/41615

### CODE REVIEW

**Comment by kennytm** [comment]
The [test case for `assert_eq`](https://github.com/rust-lang/rust/blob/master/src/test/run-fail/assert-eq-macro-panic.rs) needs to be updated as well.

```ini
[00:52:03] failures:
[00:52:03] 
[00:52:03] ---- [run-fail] run-fail/assert-eq-macro-panic.rs stdout ----
[00:52:03] 	
[00:52:03] error: error pattern 'assertion failed: `(left == right)` (left: `14`, right: `15`)' not found!
[00:52:03] status: exit code: 101
[00:52:03] command: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-fail/assert-eq-macro-panic.stage2-x86_64-unknown-linux-gnu 
[00:52:03] stdout:
[00:52:03] ------------------------------------------
[00:52:03] 
[00:52:03] ------------------------------------------
[00:52:03] stderr:
[00:52:03] ------------------------------------------
[00:52:03] thread 'main' panicked at 'assertion failed: `(left == right)`
[00:52:03] left:  `14`
[00:52:03] right: `15`', /checkout/src/test/run-fail/assert-eq-macro-panic.rs:14
[00:52:03] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:52:03] 
[00:52:03] ------------------------------------------
[00:52:03] 
[00:52:03] thread '[run-fail] run-fail/assert-eq-macro-panic.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2480
[00:52:03] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:52:03] 
[00:52:03] 
[00:52:03] failures:
[00:52:03]     [run-fail] run-fail/assert-eq-macro-panic.rs
[00:52:03] 
[00:52:03] test result: FAILED. 125 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

But the `error-pattern` header doesn't support multi-line expectation AFAIK...

**Comment by frewsxcv** [comment]
Might also be good to change the `assert_ne!` macro to match this formatting directly below the `assert_eq!` definition

**Comment by gilescope** [comment]
multiple error-pattern seems to work nicely 👍 .
I noticed assert_eq printed left == right as well as assert_ne. I've changed assert_ne to print left != right and added a test to prove it works as expected.

Ready for review.

**Comment by gilescope** [comment]
@alexcrichton is it looking ok now?

**Comment by alexcrichton** [comment]
Oops thanks for the ping @gilescope, turns out you're [not the first](https://github.com/rust-lang/rust/issues/41615) to have this idea! Looks like this closes that issue so I'll update the PR description as well. Otherwise looks great to me, thanks!

@bors: r+

**Comment by Mark-Simulacrum** [comment]
Legitimate failure.

```
[01:04:38] ---- cargo_bench_failing_test stdout ----

[01:04:38] 	running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build`

[01:04:38] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t11/foo/target/debug/foo`

[01:04:38] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo bench`

[01:04:38] thread 'cargo_bench_failing_test' panicked at '

[01:04:38] Expected: execs

[01:04:38]     but: expected to find:

[01:04:38] [COMPILING] foo v0.5.0 (file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t11/foo)

[01:04:38] [FINISHED] release [optimized] target(s) in [..]

[01:04:38] [RUNNING] target[/]release[/]deps[/]foo-[..][EXE]

[01:04:38] thread '[..]' panicked at 'assertion failed: `(left == right)` (left: `"hello"`, right: `"nope"`)', src[/]foo.rs:14

[01:04:38] [..]

[01:04:38] 

[01:04:38] 

[01:04:38] did not find in output:

[01:04:38]    Compiling foo v0.5.0 (file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t11/foo)

[01:04:38]     Finished release [optimized] target(s) in 0.63 secs

[01:04:38]      Running target/release/deps/foo-dfc15783c07e4d52

[01:04:38] thread 'main' panicked at 'assertion failed: `(left == right)`

[01:04:38]   left: `"hello"`

[01:04:38]  right: `"nope"`', src/foo.rs:14

[01:04:38] note: Run with `RUST_BACKTRACE=1` for a backtrace.

[01:04:38] error: bench failed

[01:04:38] ', /cargo/registry/src/github.com-1ecc6299db9ec823/hamcrest-0.1.1/src/core.rs:31

[01:04:38] note: Run with `RUST_BACKTRACE=1` for a backtrace.

[01:04:38] 

[01:04:38] 

[01:04:38] failures:

[01:04:38]     cargo_bench_failing_test
```

**Comment by kennytm** [comment]
Cargo strikes again 😆

**Comment by gilescope** [comment]
The fix for the cargo/tests/bench.rs is on gilescope/cargo revision 65ea42e8a847171e4f93fef6df5154aba7f832e3 (master branch). I'm unclear as to whether I should be creating a separate pull request for Cargo? Apologies - my git-foo seems to be lacking on submodules. Apologies for being a newbie in this respect.

**Comment by kennytm** [comment]
@gilescope Yes you need to submit a PR to cargo, wait for cargo to merge it, and then update the submodule here. You may see how this is handled in #41910 and rust-lang/cargo#4055.

**Comment by gilescope** [comment]
@alexcrichton good morning, hopefully second time luck with cargo!

**Comment by kennytm** [comment]
x86-gnu-aux failed. Legit. [At least one `cargo` test is still not updated](https://github.com/rust-lang/cargo/blob/402d8454f86e514fa00e4f13f051f08620d6a9a7/tests/test.rs#L218-L221).

**Comment by Mark-Simulacrum** [comment]
```
[01:06:58] ---- test_hello stdout ----

[01:06:58] <tab>thread 'test_hello' panicked at 'assertion failed: `(left == right)`

[01:06:58]   left: `"hello"`

[01:06:58]  right: `"nope"`', src/foo.rs:12

[01:06:58] note: Run with `RUST_BACKTRACE=1` for a backtrace.

[01:06:58] 

[01:06:58] 

[01:06:58] failures:

[01:06:58]     test_hello

[01:06:58] 

[01:06:58] test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

[01:06:58] 

[01:06:58] ', /cargo/registry/src/github.com-1ecc6299db9ec823/hamcrest-0.1.1/src/core.rs:31

[01:06:58] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by kennytm** [comment]
@Mark-Simulacrum The actual error information is above this piece.

<details><summary>The full failure:</summary>

```
[01:06:58] failures:
[01:06:58] 
[01:06:58] ---- cargo_test_failing_test_in_bin stdout ----
[01:06:58] 	running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build`
[01:06:58] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t9/foo/target/debug/foo`
[01:06:58] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo test`
[01:06:58] thread 'cargo_test_failing_test_in_bin' panicked at '
[01:06:58] Expected: execs
[01:06:58]     but: expected to find:
[01:06:58] [..]left: `"hello"`,[..]
[01:06:58] 
[01:06:58] did not find in output:
[01:06:58] 
[01:06:58] running 1 test
[01:06:58] test test_hello ... FAILED
[01:06:58] 
[01:06:58] failures:
[01:06:58] 
[01:06:58] ---- test_hello stdout ----
[01:06:58] <tab>thread 'test_hello' panicked at 'assertion failed: `(left == right)`
[01:06:58]   left: `"hello"`
[01:06:58]  right: `"nope"`', src/foo.rs:12
[01:06:58] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:06:58] 
[01:06:58] 
[01:06:58] failures:
[01:06:58]     test_hello
[01:06:58] 
[01:06:58] test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:06:58] 
[01:06:58] ', /cargo/registry/src/github.com-1ecc6299db9ec823/hamcrest-0.1.1/src/core.rs:31
[01:06:58] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:06:58] 
[01:06:58] 
[01:06:58] failures:
[01:06:58]     cargo_test_failing_test_in_bin
[01:06:58] 
[01:06:58] test result: FAILED. 75 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

</details>

The crucial line are these:

```
[01:06:58]     but: expected to find:
[01:06:58] [..]left: `"hello"`,[..]
...
[01:06:58]   left: `"hello"`
[01:06:58]  right: `"nope"`', src/foo.rs:12
```

[compare with the current cargo test](https://github.com/gilescope/cargo/blob/ef9b838e22fd2368b5bc046bf8b0b523bc058f4b/tests/test.rs#L220-L221):

```rust
.with_stdout_contains("[..]left: `\"hello\"`,[..]")
.with_stdout_contains("[..]right: `\"nope\"`[..]")
```

The comma should be removed.

(IIUC one could run the Cargo tests locally with `./x.py test src/tools/cargo`).

**Comment by gilescope** [comment]
I can follow the failures, just life getting in the way is the reason for the slow turn arounds! On reflection I think the commer should stay. When travis fails due to network issues is there a button to force a rebuild or do you just use a no-op commit?

**Comment by alexcrichton** [comment]
@gilescope ah sorry there's no way to restart a travis build other than with a new commit, but I think this is ready to go, right? Want to remove the noop commits and I'll r+?

**Comment by gilescope** [comment]
My git-fu has certainly improved a bit! Ok, I think I've managed to scrub those two no-op commits. Please feel free to r+

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by Mark-Simulacrum** [comment]
@bors retry

 network failure, I hope: [00:03:14] curl: (6) Could not resolve host: codeload.github.com

**Comment by Mark-Simulacrum** [comment]
@bors r=alexcrichton retry

Didn't mean to close...

**Comment by kennytm** [comment]
macOS timed out, spurious.

**Comment by gilescope** [comment]
Hmm, Travis timed out at 3h but it was happily chugging away running the tests. Maybe it hit a slow / heavily loaded server? I guess at some point we need to split the build from running the tests so that we can parallelise the tests further. Then again speeding up the rust compiler would help these build times and might have some side benefits. Not sure I'm quite ready to take that on as my second PR.

**Comment by kennytm** [comment]
@gilescope no need to worry about that, the rust team member will just retry in these cases

**Comment by Mark-Simulacrum** [comment]
@bors retry

OS X timed out

**Comment by lpil** [comment]
Late to the game here, just wanted to say thanks for this. Thanks!

**Pull request merged**
