### PR TITLE
rustc_expand: Switch FxHashMap to FxIndexMap where iteration is used

### PR DESCRIPTION
**Pull request by NiklasJonsson**
Relates #84447

### CODE REVIEW

**Comment by NiklasJonsson** [comment]
I tried to run rustc_perf locally to see if there was any performance impact like in [this MR](https://github.com/rust-lang/rust/pull/99126) but I couldn't get xperf to run (I'm on windows), so it would probably good to do a perf run to see if this has any impact.

**Comment by petrochenkov** [comment]
This map is used purely for diagnostics, so it's hot performance sensitive.

**Pull request merged**
