### PR TITLE
Move contributing.md to rustc-dev-guide and point at getting started

### PR DESCRIPTION
**Pull request by mark-i-m**
See description on https://github.com/rust-lang/rustc-dev-guide/pull/753

### CODE REVIEW

**Comment by mark-i-m** [comment]
The getting started guide is up: https://rustc-dev-guide.rust-lang.org/getting-started.html

@rustbot modify labels: -S-blocked

@nikomatsakis Would it make sense to do an FCP/MCP or something here?

**Comment by nikomatsakis** [comment]
I don't really think it's necessary, but I also don't think it could hurt. I would happily second it.

**Comment by nikomatsakis** [comment]
I'm going to go ahead and r+ -- if the MCP got 8 days into FCP, I think it's fine, and this is reversible.

@bors r+

**Comment by nikomatsakis** [comment]
@bors r-

Well, wait, I guess that rust-lang/rustc-dev-guide#753 should merge first...?

r=me in any case.

**Comment by mark-i-m** [comment]
@nikomatsakis I just merged #753

**Pull request merged**
