### PR TITLE
Fix memory leak in test "mem::uninit_write_slice_cloned_no_drop"

### LINKED ISSUE #80116: Test "mem::uninit_write_slice_cloned_no_drop" leaks memory
The test `mem::uninit_write_slice_cloned_no_drop` added in https://github.com/rust-lang/rust/pull/79607 leaks memory, which makes a Miri run of the test suite fail:

```
running 1 test
test mem::uninit_write_slice_cloned_no_drop ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1176 filtered out

The following memory was leaked: alloc1884656 (Rust heap, size: 16, align: 8) {
    01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 │ ................
}
```

Running Miri on the test suite is helpful to find bugs, so we should avoid deliberate leaks to still be able to detect accidental ones. Can the test be changed to use some other means of ensuring that `drop` is not called, e.g. with a `Bomb` type?
```rust
struct Bomb;

impl Drop for Bomb {
  fn drop(&mut self) { panic!(); }
}
```

Cc @DrMeepster

### PR DESCRIPTION
**Pull request by beepster4096**
This fixes #80116. I replaced the `Rc` based method I was using with a type that panics when dropped.

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks! I almost missed this PR; feel free to post a message in the issue when a PR fixes the issue so people are aware and can do the reviewing. :)

r? @RalfJung
@bors r+ rollup

**Comment by RalfJung** [comment]
@bors r-

Failed on a wasm target:
```
error: unused import: `std::rc::Rc`
 --> library/core/tests/mem.rs:3:5
  |
3 | use std::rc::Rc;
  |     ^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
```

**Comment by DrMeepster** [comment]
Fixed that errror

**Pull request merged**
