### PR TITLE
rustbuild: Fix LLVM build with LLD on windows-gnu targets

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/pull/94832#issuecomment-1073957722
(I currently have to add this to all my PRs because otherwise nothing builds on my machine.)

### CODE REVIEW

**Review by mati865 — APPROVED** [review]

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
We may need a more comprehensive change to deal with https://github.com/rust-lang/rust/issues/94983, but I think this is the right thing to do in the short term at least.

**Comment by mati865** [comment]
Yeah statically linking libc++ is tricky because it can use different low level libraires like libc++abi, libsupc++ or libcxxrt and sometimes depending on how it was building requires them to be passed.

**Comment by petrochenkov** [comment]
The change landed as a part of https://github.com/rust-lang/rust/pull/95255.

**Pull request closed without merging**
