### PR TITLE
rename `TyKind` to `RegionKind` in comment in rustc_middle

### PR DESCRIPTION
**Pull request by lcnr**

### CODE REVIEW

**Comment by lcnr** [comment]
do github PRs now start out as drafts by default? :thinking: Or does it reuse the selection from a previous PR

**Comment by jackh726** [comment]
Can you make a better title and maybe commit message?

r=me after

**Comment by JohnTitor** [comment]
> do github PRs now start out as drafts by default? 🤔 Or does it reuse the selection from a previous PR

It's the latter, GitHub reuses the previous selection.

**Pull request merged**
