### PR TITLE
Stabilize feature sort_unstable

### LINKED ISSUE #40585: Tracking issue for unstable sort in libcore
Tracking issue for https://github.com/rust-lang/rfcs/pull/1884

### PR DESCRIPTION
**Pull request by ghost**
Closes #40585

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks like Travis failed.

```
[00:03:24] tidy error: /checkout/src/liballoc/slice.rs:1273: different stability level than before
[00:03:24] tidy error: /checkout/src/liballoc/slice.rs:1273: different `since` than before
[00:03:24] tidy error: /checkout/src/liballoc/slice.rs:1273: different `tracking_issue` than before
```

**Comment by alexcrichton** [comment]
Thanks @stjepang! r=me other than the tidy error

**Comment by stjepang** [comment]
The tidy errors have been fixed.

**Comment by Mark-Simulacrum** [comment]
Travis appears to still be failing.

**Comment by stjepang** [comment]
All right, should be good to go now. :)

**Pull request merged**
