### PR TITLE
Implement LowerHex on Scalar to clean up their display in rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow-up of https://github.com/rust-lang/rust/pull/94091.

r? @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
LGTM, thanks!
@bors r+ rollup

Btw, rustc has a bunch of pretty-printing machinery for consts as part of MIR printing, e.g. [here](https://github.com/rust-lang/rust/blob/d54195db22421c51fd14560aba3bbf9b79a52677/compiler/rustc_middle/src/ty/print/pretty.rs#L1210). Is there any specific reason rustdoc cannot use that code?

**Comment by GuillaumeGomez** [comment]
> Btw, rustc has a bunch of pretty-printing machinery for consts as part of MIR printing, e.g. [here](https://github.com/rust-lang/rust/blob/d54195db22421c51fd14560aba3bbf9b79a52677/compiler/rustc_middle/src/ty/print/pretty.rs#L1210). Is there any specific reason rustdoc cannot use that code?

Simply because we didn't know of it. I'll send a PR to use it instead. Do you me to remove the `Display` implementation once done?

**Comment by RalfJung** [comment]
> Do you me to remove the Display implementation once done?

Yeah, we can remove "dangling" instances.

This PR still makes sense though IMO, to be more explicit about how `Scalar`s are printed. (In a follow-up change I intend to do the same with `ScalarMaybeUninit`, or you can do that in this PR if you want.)

Also we will have to see if the MIR printing satisfies the requirements of rustdoc. For example, I think it currently does not add `_` every 3 digits. However that would probably be a change for the better, so by unifying the two printers we can improve both of them. :)

**Comment by GuillaumeGomez** [comment]
Sounds good to me! I'll send a PR once this one is merged then.

**Comment by GuillaumeGomez** [comment]
I just checked for the follow-up and moving `format_integer_with_underscore_sep` into the formatting of `ConstInt`. It appears that for `MIN`/`MAX` values, it doesn't print the value but instead `type::MIN`/`type::MAX`. Also, the `format_integer_with_underscore_sep` function handles a few more things which would be "too much" for it to be put in `rustc_middle` and making us duplicate it in rustdoc.

So unless I missed something, I'll let things as is for the time being.

**Pull request merged**
