### PR TITLE
Fix simd_bswap for i8/u8

### PR DESCRIPTION
**Pull request by calebzulawski**
#114156 missed this test case ☹️ 
cc @workingjubilee

### CODE REVIEW

**Review by compiler-errors — COMMENTED** [review]
Do we expect people to be calling this intrinsic on `i8xN`? This seems like a misuse of the intrinsic, or at least for LLVM, since `llvm.bswap.*` says the element needs an even number of bytes.

**Comment by workingjubilee** [comment]
indeed, what are we actually trying to achieve here?

**Comment by calebzulawski** [comment]
This mirrors the scalar bswap intrinsic: https://github.com/rust-lang/rust/blob/a8be6e070f02fca6e5ab851e10e29d45c3a0217c/compiler/rustc_codegen_llvm/src/intrinsic.rs#L251-L260

It would be a bit of a pain to special-case i8/u8 vectors in std::simd.

**Comment by workingjubilee** [comment]
or more precisely, what is the current behavior we're trying to avoid?

**Comment by calebzulawski** [comment]
> or more precisely, what is the current behavior we're trying to avoid?

I thought LLVM would handle a no-op, but instead the compiler crashes:

```
warning: build failed, waiting for other jobs to finish...
bswap must be an even number of bytes
  %4 = call <32 x i8> @llvm.bswap.v32i8(<32 x i8> %3), !dbg !858
in function _ZN113_$LT$core_simd..core_simd..vector..Simd$LT$i8$C$_$GT$$u20$as$u20$core_simd..core_simd..elements..int..SimdInt$GT$10swap_bytes17h00fedc46e657fc9cE
LLVM ERROR: Broken function found, compilation aborted!
error: could not compile `core_simd` (test "i8_ops")

**Review by compiler-errors — COMMENTED** [review]
I guess r=me if @workingjubilee thinks that this is worthwhile -- the fact that we're special-casing i8 in both the simd and non-simd bswap intrinsics is a tiny bit odd, but I could believe it makes sense with like... macro-generated code or something. Still kinda sus, though.

**Comment by workingjubilee** [comment]
lmao llvm

**Comment by calebzulawski** [comment]
Both scalar integers and std::simd integer vectors are macro-generated 🙃 No users should be seeing these intrinsics.

**Comment by compiler-errors** [comment]
To be fair to LLVM, it says very clearly that the intrinsic is only defined when `BitWidth % 16 == 0`.

**Comment by workingjubilee** [comment]
> I guess r=me if @workingjubilee thinks that this is worthwhile
yeaaaaah.

> but I could believe it makes sense with like... macro-generated code or something

that describes all of std's integer impls, baby!

@bors r=compiler-errors

**Comment by workingjubilee** [comment]
@bors r- rollup=iffy
cc https://github.com/rust-lang/rust/pull/114270

I have no idea but I'm almost certain it's this PR.

**Comment by calebzulawski** [comment]
The failed test is tests/ui/lint/must_not_suspend/handled.rs, I don't see any way this PR could affect that. Maybe spurious?

**Comment by workingjubilee** [comment]
...hm yeah you're right, I misread the logs at-a-glance.

Probably is spurious then.

@bors r=compiler-errors

**Comment by nnethercote** [comment]
One possible, marginal regression, nothing to worry about.

@rustbot label: +perf-regression-triaged

**Pull request merged**
