### PR TITLE
Multiline string attr display

### LINKED ISSUE #81482: rustdoc: attribute string literals render with backslashes
I tried this code:

```rust
#[must_use = "this is a \
              message"]
pub fn f() {}
```

I expected to see this happen:  Rustdoc will render the string as `#[must_use = "this is a message"]`

Instead, this happened: It is rendered with a backslash:

image

### Meta

`rustdoc 1.51.0-nightly (f4eb5d9f7 2021-01-25)`

I believe this started in 1.44 via #69686.

(This is a pretty minor issue, I'm not sure it is worth putting energy into, but it does look a little strange.)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #81482.

As you see [here](https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.replace) (or on the screenshot below):

Screenshot from 2021-01-27 14-23-49

The backslash is kept in the string literal in the end. This fix removes it, however I wonder if there isn't a function to do that already in the compiler (couldn't find anything so...). Maybe you might have some information about it @oli-obk ?

cc @CraftSpider 
r? @camelid

### CODE REVIEW

**Comment by oli-obk** [comment]
We definitely have code for this somewhere already. I would actually have expected the parser to handle this for us so we don't ever see this.

**Comment by camelid** [comment]
I think the issue is that we get the attributes using:

```rust
        .filter_map(|attr| {
            if ALLOWED_ATTRIBUTES.contains(&attr.name_or_empty()) {
                Some(pprust::attribute_to_string(&attr))
            } else {
                None
            }
        })
```

which seems *very* hacky.

**Comment by camelid** [comment]
I think we want to use something like `Attribute::value_str` instead of the pretty-printer. Can you try that?

@rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by GuillaumeGomez** [comment]
The problem here is that we print not only the value but the whole attr. So here, we print `#[must_use = "blablabla"]`, no just "blablabla".

**Comment by oli-obk** [comment]
maybe we can fix the pretty printer to use `value_str`?

**Comment by GuillaumeGomez** [comment]
Sounds like a good idea! I'll go with this then.

**Comment by GuillaumeGomez** [comment]
It seems that the pretty printer cannot really use `value_str` as we go through multiple steps and in the end just finish with a `ast::Literal`. We can still make it remove the backslash though (diff of what I did):

<details>
```
diff --git a/compiler/rustc_ast/src/util/literal.rs b/compiler/rustc_ast/src/util/literal.rs
index 2124f1efb99..cf0f6ef3b2b 100644
--- a/compiler/rustc_ast/src/util/literal.rs
+++ b/compiler/rustc_ast/src/util/literal.rs
@@ -23,7 +23,7 @@ pub enum LitError {
 
 impl LitKind {
     /// Converts literal token into a semantic literal.
-    fn from_lit_token(lit: token::Lit) -> Result<LitKind, LitError> {
+    pub fn from_lit_token(lit: token::Lit) -> Result<LitKind, LitError> {
         let token::Lit { kind, symbol, suffix } = lit;
         if suffix.is_some() && !kind.may_have_suffix() {
             return Err(LitError::InvalidSuffix);
diff --git a/compiler/rustc_ast_pretty/src/pprust/state.rs b/compiler/rustc_ast_pretty/src/pprust/state.rs
index 2c8caf68f00..b79398035c6 100644
--- a/compiler/rustc_ast_pretty/src/pprust/state.rs
+++ b/compiler/rustc_ast_pretty/src/pprust/state.rs
@@ -191,13 +191,49 @@ pub fn literal_to_string(lit: token::Lit) -> String {
     let mut out = match kind {
         token::Byte => format!("b'{}'", symbol),
         token::Char => format!("'{}'", symbol),
-        token::Str => format!("\"{}\"", symbol),
+        token::Str => {
+            if let Ok(ast::LitKind::Str(symbol, _)) = ast::LitKind::from_lit_token(lit) {
+                format!("\"{}\"", symbol)
+            } else {
+                format!("\"{}\"", symbol)
+            }
+        }
         token::StrRaw(n) => {
-            format!("r{delim}\"{string}\"{delim}", delim = "#".repeat(n as usize), string = symbol)
+            if let Ok(ast::LitKind::Str(symbol, _)) = ast::LitKind::from_lit_token(lit) {
+                format!(
+                    "r{delim}\"{string}\"{delim}",
+                    delim = "#".repeat(n as usize),
+                    string = symbol
+                )
+            } else {
+                format!(
+                    "r{delim}\"{string}\"{delim}",
+                    delim = "#".repeat(n as usize),
+                    string = symbol
+                )
+            }
+        }
+        token::ByteStr => {
+            if let Ok(l) = ast::LitKind::from_lit_token(lit) {
+                format!("b\"{}\"", l.to_lit_token().symbol)
+            } else {
+                format!("b\"{}\"", symbol)
+            }
         }
-        token::ByteStr => format!("b\"{}\"", symbol),
         token::ByteStrRaw(n) => {
-            format!("br{delim}\"{string}\"{delim}", delim = "#".repeat(n as usize), string = symbol)
+            if let Ok(l) = ast::LitKind::from_lit_token(lit) {
+                format!(
+                    "br{delim}\"{string}\"{delim}",
+                    delim = "#".repeat(n as usize),
+                    string = l.to_lit_token().symbol
+                )
+            } else {
+                format!(
+                    "br{delim}\"{string}\"{delim}",
+                    delim = "#".repeat(n as usize),
+                    string = symbol
+                )
+            }
         }
         token::Integer | token::Float | token::Bool | token::Err => symbol.to_string(),
     };
```
</details>

So in the meantime, I opened a discussion about it in zulip [here](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Display.20of.20hir.3A.3Aattributes).

**Comment by jsha** [comment]
This is not needed so badly anymore since we removed `must_use` from ALLOWED_ATTRIBUTES. Do you still want to get this done?

**Comment by camelid** [comment]
I'm going to close this for now since this PR isn't actionable.

**Pull request closed without merging**
