### PR TITLE
Add `Option::owned`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This PR adds the following public library APIs:
```rust
// alloc::option
impl<T: ?Sized> Option<&T> {
    pub fn owned(self) -> Option<T::Owned>
    where
        T: ToOwned;
}

impl<T: ?Sized> Option<&mut T> {
    pub fn owned(self) -> Option<T::Owned>
    where
        T: ToOwned;
}

// alloc::result
impl<T: ?Sized, E> Result<&T, E> {
    pub fn owned(self) -> Result<T::Owned, E>
    where
        T: ToOwned;
}

impl<T: ?Sized, E> Result<&mut T, E> {
    pub fn owned(self) -> Result<T::Owned, E>
    where
        T: ToOwned;
}
```

`Option::owned` is similar to `Option::cloned` and `Option::copied`, but uses the `ToOwned` trait.

---

I thought that would be easier, but since `ToOwned` is defined in the alloc crate this becomes incoherent :')

### CODE REVIEW

**Comment by RReverser** [comment]
It should probably add same methods to `Result` as well, since it usually mirrors such `Option` utils (e.g. it also has `copied` & `cloned`).

**Comment by WaffleLapkin** [comment]
@RReverser Good catch! I'll add `owned` method to `Result` too.

**Comment by joshtriplett** [comment]
I like the concept of this, but as a nit on the name, I think this should be `to_owned`.

**Comment by RReverser** [comment]
> I like the concept of this, but as a nit on the name, I think this should be `to_owned`.

That wouldn't be possible - `.to_owned()` can already be called on arbitrary `T: Clone` refs, including on `&Option`, and does something different:

```rust
let a: &Option<i32> = &Some(1);
let b: Option<i32> = a.to_owned();
```

**Comment by camsteffen** [comment]
What about `borrowed`?

```rust
let x = Some(String::new());
let y: Option<&str> = x.borrowed();
```

**Comment by WaffleLapkin** [comment]
@camsteffen your snippet can use `.as_deref` instead, are there any reasons/use cases to use `Borrow` instead of `Deref`?

**Comment by camsteffen** [comment]
Yeah I just realized that. Probably not many such use cases.

**Comment by zesterer** [comment]
Could an implementation for `Option<Cow<T>>` be added too?

**Comment by WaffleLapkin** [comment]
@zesterer we already need magic to define `T: ToOwned` methods, since `ToOwned` is defined in `alloc` :)

Still, I don't think implementation for `Option<Cow<T>>` is possible -- `Cow<T>` can implement `ToOwned` which will overlap with the methods being added.

**Comment by WaffleLapkin** [comment]
CI is green

**Comment by WaffleLapkin** [comment]
CI is green (also filled in tracking issue)

**Comment by m-ou-se** [comment]
I _really_ don't think we should be using `#[rustc_has_incoherent_inherent_impls]`.

There's a good reason we don't normally support incoherent impls. It makes maintenance hard, and can easily result in very surprising behavior. For example, no_std code could suddenly compile differently when some other crate in the dependency tree pulls in `std`. (We already have this issue with f32::sin(), which is something we should solve by moving that method to `core`.)

**Comment by klensy** [comment]
Current title and description says about `Option`, while this PR actually affects `Result` too.

**Comment by WaffleLapkin** [comment]
I don't think that this is a good idea anymore, @m-ou-se's comment summarizes the problems quite well. On top of that, 1) it can be implemented as a crate (via a trait) 2) these methods are not _that_ commonly needed (my assumption, isn't backed by any data).

Thus, I'm closing this.

**Pull request closed without merging**
