### PR TITLE
Implement Deref{Mut} for arrays

### LINKED ISSUE #62992: slice methods could be added to the array docs
(I'm surprised I couldn't find an issue for this!)

The documentation page for the [primitive array type](https://doc.rust-lang.org/std/primitive.array.html) ideally should include the methods defined on slices. (see e.g. [this report of confusion](https://users.rust-lang.org/t/array-lengths-cant-depend-on-generic-parameters-with-const-generics-bug-or-expected-behavior/30579/36) on the forum)

This could be tricky; it looks like this capability is basically hardcoded into the compiler, so `rustdoc` would need to special-case it.  (it can't rely on `Deref` like it can for `Vec`)

---

As an aside, the page contains some misleading language:

> Arrays coerce to slices (`[T]`), so a slice method may be called on an array.

This suggests that coercions enable method access, but there's plenty of coercions in Rust that do not, including other `Unsize` coercions like `&T -> &dyn Trait`.

### PR DESCRIPTION
**Pull request by Veykril**
Now that we have const generics, there shouldn't really be a reason for arrays not to implement `Deref`/`DerefMut` anymore (to my knowledge). So this PR is an attempt in making that work.

With this, arrays now participate in deref coercions.

Unfortunately we still need to special case arrays in method probing, as unsizing can be always done in a const context while deref cannot on stable and currently the compiler will prefer dereferencing over unsizing. Of note is that once `Deref` is stably const, the unsizing step can (probably, not tested) be fully removed, meaning `Unsize` adjustments no longer need to happen for arrays)

Fixes https://github.com/rust-lang/rust/issues/62992

### CODE REVIEW

**Comment by Nilstrieb** [comment]
@compiler-errors on the compiler part, otherwise
r? libs-api

**Comment by Veykril** [comment]
Looks like a clippy diagnostic fails now (will look into why in a bit).

Also seems like rustdoc just handles this without any changes in terms of issue https://github.com/rust-lang/rust/issues/62992
image

**Comment by Veykril** [comment]
Not sure if this might be a T-lang thing as well, since arrays now participate in deref coercions (and arrays being a language type opposed to library)

**Comment by compiler-errors** [comment]
I actually tried to implement this back in #92652. I don't think it makes sense to implement Deref in this case anymore, since array -> slice is an unsize coercion.

Regardless, needs an ACP from T-lobs-api I think? https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by Veykril** [comment]
Guess I wasn't looking thoroughly enough for a previous PR :) I can see the reasoning behind why not to add this then.

Turns out this is even the third PR trying to do this, I wonder if it makes sense to add a comment somewhere that states as to why we don't want this impl?

**Pull request closed without merging**
