### PR TITLE
Remove unnecessary SpecFromIter impls

### PR DESCRIPTION
**Pull request by steffahn**
Unless I’m missing something, these `SpecFromIter<&'a T, …> for Vec<T>` implementations were completely unused.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Unfortunate that these aren't statically detected but I guess that's true of all (trait) impls...

@bors try @rust-timer queue

**Comment by the8472** [comment]
How did you determine that they're unused? They're specialization implementations, so they should be used for particular instances of an iterator. It looks like the last one is supposed to turn a `[T].iter().collect()` into `[T].to_vec()`.

**Comment by the8472** [comment]
The trait documentation would be outdated with this change

https://github.com/rust-lang/rust/blob/c902fdca459a9ee31a6ea81236cb250bc037255b/library/alloc/src/vec/spec_from_iter.rs#L16-L25

**Comment by steffahn** [comment]
> How did you determine that they're unused?

There are impls of the form `SpecFromIter<T, …> for Vec<T>` and of the form `SpecFromIter<&'a T, …> for Vec<T>`. None of the first type can ever overlap with any impl of the second type. I removed *all* the impls of the second form and `std` still compiles.

**Comment by steffahn** [comment]
> The trait documentation would be outdated with this change

Good catch. I’ve added a commit.

**Comment by the8472** [comment]
Ah, I see. Looking through the history it looks this was originally used for the `Extend<&'a T>` implementation which shared some code with the `FromIterator` implementations which I then split into separate specializations but didn't clean up.

👍

**Pull request merged**
