### PR TITLE
Correct ICE caused by macros generating invalid spans.

### LINKED ISSUE #68605: Compiler gives internal error during macro expansion.
Steps to replicate:
1. Create two files `a.rs` and `b.rs` in the same directory with the following content:
```rust
// a.rs
pub struct ProjectileCreated;
pub struct NotificationChannel<E>(std::marker::PhantomData<E>);

macro_rules! define_trigger_system {
    ($(( $field:ident, $ty:ident, $channel:ident )),* $(,)?) => {
        #[macro_export]
        macro_rules! all_trigger_fields {
            ($submacro:ident) => { $submacro!($( ( $field, $ty, $channel ) ),*) }
        }
    }
}

define_trigger_system!(
    ( projectile_created,   ProjectileCreated,   NotificationChannel ),
);
```
```rust
// b.rs
extern crate a;
use a::*;

macro_rules! make_event_subscription {
    ($(( $field:ident, $ty:ident, $channel:ident)),*) => {
        pub struct EventSubscription (
            $($channel<a::$ty>::ReaderId),*
        );
    }
}

all_trigger_fields!(make_event_subscription);
```
2. Compile both files
```
$ rustc a.rs --crate-type=lib
$ rustc b.rs --extern a=liba.rlib --crate-type=lib
```

3. Observe the following error
```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("b.rs"), BytePos(0)), end: (Macros("::a::all_trigger_fields"), BytePos(6695205)) })', src/librustc_errors/emitter.rs:2106:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (c2d141df5 2020-01-24) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

error: aborting due to previous error
```

I note that the `(Macros("::a::all_trigger_fields"), BytePos(6695205))` looks quite suspicious, since there are fewer than 6695205 bytes in the source text.

This issue has been assigned to @MichaelBurge via [this comment](https://github.com/rust-lang/rust/issues/68605#issuecomment-579357902).

### PR DESCRIPTION
**Pull request by MichaelBurge**
Closes #68605

### CODE REVIEW

**Comment by Centril** [comment]
Shouldn't this come with a regression test?

**Comment by pnkfelix** [comment]
(we discussed backporting this in today's T-compiler meeting. We are not certain what `warn!` will do here, in terms of what an end-user will see, so we held off on approving this change until after we've double-checked the default UX there...)

**Comment by nikomatsakis** [comment]
Discussed in today's T-compiler meeting. Inserting a `warn!` still seems unusual to me personally, but we decided to go ahead and approve for beta/stable backport, since it does correct an ICE, and the patch seems harmless enough.

**Pull request merged**
