### PR TITLE
[library/std/src/process.rs] `PartialEq` for `ExitCode`

### PR DESCRIPTION
**Pull request by SamuelMarks**
Converting a third-party CLI to a library so started passing around [`std::process::ExitCode`](https://doc.rust-lang.org/std/process/struct.ExitCode.html) in an `Either`. Then I realised the tests can't be modified to compare equality of `ExitCode`s.

This PR fixes this oversight.

### CODE REVIEW

**Comment by workingjubilee** [comment]
r? libs-api

**Comment by workingjubilee** [comment]
Hello, @SamuelMarks. This is not an oversight, it was quite intentional. See [this comment from ExitCode's stabilization](https://github.com/rust-lang/rust/pull/93840#issuecomment-1045160700) and [this one in a similar PR](https://github.com/rust-lang/rust/pull/125182#issuecomment-2115755918).

**Comment by workingjubilee** [comment]
see also this note from the docs:
```
/// # Differences from `ExitStatus`
///
/// `ExitCode` is intended for terminating the currently running process, via
/// the `Termination` trait, in contrast to [`ExitStatus`], which represents the
/// termination of a child process. These APIs are separate due to platform
/// compatibility differences and their expected usage; it is not generally
/// possible to exactly reproduce an `ExitStatus` from a child for the current
/// process after the fact.
```

**Comment by SamuelMarks** [comment]
In that case, what standard type should I use to percolate exit codes all the way up to `fn main`?

(and yes, I already `impl std::ops::FromResidual<Result<std::convert::Infallible, MyError>>
    for SuccessOrMyError<std::process::ExitCode>` and `impl<T> std::process::Termination for SuccessOrMyError<T> {` and that calls `impl std::process::Termination for MyError {`)

Would a [`code`](https://doc.rust-lang.org/std/process/struct.ExitStatus.html#method.code) [hyperlink is to `ExitStatus`] implementation have a PR accepted?

**Comment by workingjubilee** [comment]
> In that case, what standard type should I use to percolate exit codes all the way up to fn main?

Could you describe this motivation a little more clearly? It sounds like you have synthesized a few different ExitCodes, either via the SUCCESS or FAILURE constants, or via the `From<u8>`, and when you finish running this process, you have a few different ExitCodes generated elsewher, and you want to pick which one to return using some kind of comparator?

**Comment by workingjubilee** [comment]
or... wait, you just want to run tests?

**Comment by SamuelMarks** [comment]
@workingjubilee More than just run tests, this large Rust project I forked is oriented towards CLI-only usage. I'm going through it and replacing all `panic`s and other termination points with `Result` or `Either` types, percolating up `ExitCode`s all the way up until `fn main`.

_But_, in tests I need to compare that the right `ExitCode` is found, and perhaps in non `SUCCESS` cases from `main`—or a function in the backtrace—it will be used to retry something a certain number of times, and if `SUCCESS` is not reached, then return whatever the last `ExitCode` was and terminate the process.

**Comment by workingjubilee** [comment]
Oh okay, so a hypothetical most-minimal addition would be that you want `ExitCode::is_success` to exist?

I'm not the final word on whether this API change should be accepted, I'm just trying to note things that are going to be asked about at some point or another and trying to discern the motivation. A change that answers a specific motivation is often more persuasive than one that has an unclear motivation.

And for `is_success`, ["Should we add `is_success` to ExitCode?"](https://github.com/rust-lang/rust/issues/48711#issue-302050436) is even listed as an unresolved question in the original tracking issue. While it seems PartialEq was explicitly rejected, [`is_success` was seemingly shelved for later consideration](https://github.com/rust-lang/rust/issues/48711#issuecomment-1548148133). And you are not the only one who wants such a function, for basically the same reasons it seems: https://github.com/rust-lang/rust/issues/113081

libs-api could choose to reconsider the earlier decision about PartialEq, or might prefer to just add a function returning a bool. An ExitCode _is_ deliberately vague, but "success or not?" seems like a reasonable question to answer.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting.

For forwards compatibility with potentially weird future targets, we'd like to initially just support `PartialEq`.

Also, could you please update this PR to update the documentation as well? Right now, the documentation says "and intentionally does not provide accessors like `PartialEq`, `Eq`, or `Hash`.". This clause should be deleted, and replaced by something like "For forwards compatibility with potentially unusual targets, this type currently does not provide `Eq`, `Hash`, or access to the raw value. This type does provide `PartialEq` for comparison, but note that there may potentially be multiple failure codes, some of which will *not* compare equal to `ExitCode::FAILURE`."

@rfcbot merge

**Comment by joshtriplett** [comment]
@rfcbot cancel

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by BurntSushi** [comment]
@rfcbot concern pr-impls-eq

It looks like we're only approving `PartialEq` for now, but this PR adds impls for _both_ `PartialEq` and `Eq`.

**Comment by SamuelMarks** [comment]
@BurntSushi Fixed

**Comment by BurntSushi** [comment]
@rfcbot resolve pr-impls-eq

**Review by dtolnay — APPROVED** [review]
Thank you!

**Pull request merged**
