### PR TITLE
Some token stream cleanups

### PR DESCRIPTION
**Pull request by nnethercote**
Best reviewed one commit at a time.

r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
Not expecting much change here:

@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
r=me when the perf run is complete.

**Comment by nnethercote** [comment]
@matthiaskrgr: with the neutral perf CI run done, I think this one would be fine to be in a rollup. It's fairly small, and not doing anything very complicated.

**Pull request merged**
