### PR TITLE
add specs for riscv32/riscv64 musl targets

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by ojeda** [comment]
Please add them to `src/doc/rustc/src/platform-support.md` too.

**Comment by jhwgh1968** [comment]
@estebank since this adds new target platforms, shouldn't this be tagged for release notes?

**Comment by nmeum** [comment]
I am trying to get rustc to work on riscv64 musl for our Alpine Linux riscv64 port. Unfortunately, the cross-compiled stage2 rustc segfaults on more complex inputs for me. How did you test rustc on riscv64 musl?

See: #96876

**Pull request merged**
