### PR TITLE
Explicitly don't normalize param-env in new solver

### PR DESCRIPTION
**Pull request by compiler-errors**
Make it clear that we don't normalize param-envs in the new solver, since `normalize` is a noop. This also skips the `ConstNormalizer` hack in `normalize_param_env_or_error`, since we have deferred projection equality.

r? @lcnr @BoxyUwU

### CODE REVIEW

**Review by lcnr — COMMENTED** [review]
It feels a bit dangerous that we always have to explicitly elaborate when creating a new `ParamEnv`. I would like to have a slightly less "boring" name for `fn new` but can't think of anything too useful. Maybe `ParamEnv::from_raw_components` or something like that :thinking: 

r=me no matter what you prefer here

**Comment by compiler-errors** [comment]
I think `from_elaborated_clauses` might be a good name

**Comment by BoxyUwU** [comment]
for rust-lang/trait-system-refactor-initiative#90 we might wind up with another step that we do in param env construction which under this PR would be another thing every callsite of `ParamEnv::new` would have to explicitly remember to do. 

Seeing as how `normalize_param_env_or_error` does more than just normalizing maybe we ought to rename it to something like `prepare_manually_constructed_env` and have `ParamEnv::new_unprepared_from_clauses` or something. Then we can continue calling `prepare_manually_constructed_env` everywhere and do elaboration + filtering in it under new solver and normalization + elaboration under old solver

**Comment by lcnr** [comment]
I agree with boxy and think that we may want to add additional assumptions about the input when creating a `ParamEnv` in the future. At this point we should change the name again, I do quite like `fn from_raw_components`. I think the current name is good until then however, so r=me after fixing CI.

**Pull request closed without merging**
