### PR TITLE
Bootstrap from 1.28.0 beta

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Comment by cuviper** [comment]
> Bootstrap from 1.27.0

Isn't this actually using 1.28.0-beta.1?

**Comment by Mark-Simulacrum** [comment]
Ah, yes, it is.

**Comment by kennytm** [comment]
Why not increase the `CFG_RELEASE_NUM`?

**Comment by Mark-Simulacrum** [comment]
@kennytm Fixed

**Comment by kennytm** [comment]
Assuming it's not waiting for other things...

@bors r+

**Comment by kennytm** [comment]
@bors p=1 

Unblocks #51122 and #51677.

**Comment by mati865** [comment]
`error-chain` was recently [updated to 0.12](https://github.com/rust-lang-nursery/error-chain/commit/38f23249992baadf9c8edbdb07cc45c03d624dbc) which should fix the issue.
I'll open PR for rustup.

**Comment by Mark-Simulacrum** [comment]
I can reproduce this behavior locally, but have so far not found an explanation. `meta.len()` in [this code](https://github.com/Mark-Simulacrum/rust/blob/1bccafdb3c8b6e97c862dee449023b9b59f2397a/src/bootstrap/compile.rs#L1106) has a value of around 17592186045975 for all the files in that loop which seems to indicate a 16,384 GB file if I've done my math right. This file doesn't exist (of course) and I've been unable to determine where that length comes from.

**Comment by cuviper** [comment]
> a value of around 17592186045975 

This is 0x100000000617, which makes me suspect the correct value is 0x617 and something corrupted the upper half of the `u64`

**Comment by cuviper** [comment]
New in #51050:

https://github.com/rust-lang/rust/blob/8acec1f9d0b40dde142e6c26d7358b9ab232d2b4/src/libstd/sys/unix/fs.rs#L297-L308

This really needs to use `fstatat64` on 32-bit platforms!
(The pointer casts should have raised warning flags...)

**Comment by mati865** [comment]
Another PR failed with the same error: https://github.com/rust-lang/rust/pull/51570#issuecomment-400049989

**Comment by cuviper** [comment]
I'll send a PR to master, and we'll need a beta backport.

**Comment by oli-obk** [comment]
According to https://github.com/rust-lang/rust/pull/51790#issuecomment-400158354 we should have a beta release now with all the relevant patches inside.

**Comment by Mark-Simulacrum** [comment]
I'm going to retry as I personally don't have a way to debug this well and I did successfully build on linux, at least.

(And it does *feel* spurious).

@bors retry

**Comment by Mark-Simulacrum** [comment]
@eddyb, maybe @michaelwoerister is there any reason for the linking codegen_llvm to have changed since last bootstrap update in a way that could cause this link error?

It looks almost as if we're somehow hashing incorrectly or something like that. I also can't seem to reproduce on linux so debugging is hard (I don't have access to windows, though working on it).

```
[00:21:21]           rustc_codegen_llvm-3b62c8230fd41ad5.rustc_codegen_llvm8-792e8c686475d56adabb538d0f24f004.rs.rcgu.o : error LNK2019: unresolved external symbol _ZN12rustc_target3abi14FieldPlacement12memory_index17h9c0548eeef715a8aE referenced in function _ZN177_$LT$rustc_target..abi..TyLayout$LT$$u27$tcx$C$$u20$$RF$$u27$tcx$u20$rustc..ty..TyS$LT$$u27$tcx$GT$$GT$$u20$as$u20$rustc_codegen_llvm..type_of..LayoutLlvmExt$LT$$u27$tcx$GT$$GT$16llvm_field_index17h733d07d68364f8cdE
[00:21:21]
[00:21:21]           rustc_codegen_llvm-3b62c8230fd41ad5.rustc_codegen_llvm9-792e8c686475d56adabb538d0f24f004.rs.rcgu.o : error LNK2019: unresolved external symbol _ZN12rustc_target3abi7FloatTy9bit_width17hab4071c5006f13deE referenced in function _ZN18rustc_codegen_llvm9intrinsic22generic_simd_intrinsic17h1c3539a040f8d7abE
[00:21:21]
[00:21:21]           rustc_codegen_llvm-3b62c8230fd41ad5.rustc_codegen_llvm9-792e8c686475d56adabb538d0f24f004.rs.rcgu.o : error LNK2019: unresolved external symbol _ZN6syntax3ast6UintTy9bit_width17hf93b35ff53e0bb10E referenced in function _ZN18rustc_codegen_llvm9intrinsic22generic_simd_intrinsic17h1c3539a040f8d7abE
[00:21:21]
[00:21:21]           rustc_codegen_llvm-3b62c8230fd41ad5.rustc_codegen_llvm9-792e8c686475d56adabb538d0f24f004.rs.rcgu.o : error LNK2019: unresolved external symbol _ZN6syntax3ast5IntTy9bit_width17h8e1307e81b4114dcE referenced in function _ZN18rustc_codegen_llvm9intrinsic22generic_simd_intrinsic17h1c3539a040f8d7abE
[00:21:21]
[00:21:21]           rustc_codegen_llvm-3b62c8230fd41ad5.rustc_codegen_llvm9-792e8c686475d56adabb538d0f24f004.rs.rcgu.o : error LNK2019: unresolved external symbol _ZN65_$LT$rustc_target..abi..FloatTy$u20$as$u20$core..fmt..Display$GT$3fmt17ha9af2c5fe1cf1d7aE referenced in function _ZN18rustc_codegen_llvm9intrinsic22generic_simd_intrinsic27simd_simple_float_intrinsic17h757918de8b13cdc1E
[00:21:21]
[00:21:21]           libtempfile-c4a24b4d8e7621e4.rlib(tempfile-c4a24b4d8e7621e4.tempfile3-ea3b4947827a0896e405ebdaa806a9f3.rs.rcgu.o) : error LNK2019: unresolved external symbol _ZN4rand10thread_rng17h8400b230c1a3d21dE referenced in function _ZN8tempfile4util7tmpname17h4ce6a2cd15eadc51E
[00:21:21]
[00:21:21]           libtempfile-c4a24b4d8e7621e4.rlib(tempfile-c4a24b4d8e7621e4.tempfile3-ea3b4947827a0896e405ebdaa806a9f3.rs.rcgu.o) : error LNK2019: unresolved external symbol _ZN89_$LT$rand..ThreadRngReseeder$u20$as$u20$rand..reseeding..Reseeder$LT$rand..StdRng$GT$$GT$6reseed17hc32e88ed7df67dc9E referenced in function _ZN8tempfile4util7tmpname17h4ce6a2cd15eadc51E
[00:21:21]
[00:21:21]           libtempfile-c4a24b4d8e7621e4.rlib(tempfile-c4a24b4d8e7621e4.tempfile3-ea3b4947827a0896e405ebdaa806a9f3.rs.rcgu.o) : error LNK2019: unresolved external symbol _ZN4rand4prng7isaac6410Isaac64Rng7isaac6417hf31c3c7f79ba9eacE referenced in function _ZN8tempfile4util7tmpname17h4ce6a2cd15eadc51E
[00:21:21]
[00:21:21]           C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-rustc\x86_64-pc-windows-msvc\release\deps\rustc_codegen_llvm-3b62c8230fd41ad5.dll : fatal error LNK1120: 118 unresolved externals
```

**Comment by eddyb** [comment]
Interestingly enough, I believe all of those things are recent, `FloatTy` having been moved to `rustc_target` by @oli-obk, and `tempfile` replaced `tempdir`.

**Comment by alexcrichton** [comment]
I'm able to reproduce this locally, but only on MSVC. Apparently MinGW works just fine (accidentally did that first).

It looks like these crates just flat out aren't being linked:

* `log`
* `num_cpus`
* `rand`
* `rustc_errors`
* `rustc_target`
* `serialize`
* `syntax`
* `syntax_pos`

Trying to figure out what's going on...

**Comment by alexcrichton** [comment]
Looks like `*.dll.lib` files created by `link.exe` aren't getting copied into the sysroot. This means that due to [this condition](https://github.com/rust-lang/rust/blob/9f79d2f86af73da483f4fe8e2422c15c79221d32/src/librustc_codegen_llvm/back/linker.rs#L517-L524) we don't link anything

**Comment by alexcrichton** [comment]
Ok there's some sort of bug in Cargo I think? Cargo historically informed rustbuild about `*.dll` and `*.dll.lib`, but now it's only informing rustbuild about `*.dll`. I can't reproduce locally with a small example though, still digging

**Comment by alexcrichton** [comment]
Er actually looks like Cargo is indeed printing out `*.dll.lib` files, and rustbuild is losing them? Still digging...

**Comment by alexcrichton** [comment]
Ok I believe I've found the bug now.

What's happening is that a "benign change" in Cargo has exposed a bug in rustbuild which is causing issues. I can't find the exact change in Cargo right now but the general gist of it is that whenever we compile a path dependency we historically hard-linked aritfacts to `target/debug/foo.dll` whereas nowadays we only do that if it's the "final artifact" or the final library that's desired. All other intermediate libraries are left only in `target/debug/deps/foo-xxxxxx.dll`.

Cargo continues to inform us about all this but rustbuild has a bug [here](https://github.com/rust-lang/rust/blob/5d95db34a472dc09a90737c83ab533b840dcd224/src/bootstrap/compile.rs#L1046-L1087) where the `return` statements should be `continue`. Previously this worked because *everything* got an entry in the `toplevel` array which naturally continued to the next iteration. Now though the first filename printed (`.../deps/*.dll`) hits [this case](https://github.com/rust-lang/rust/blob/5d95db34a472dc09a90737c83ab533b840dcd224/src/bootstrap/compile.rs#L1065-L1068) which causes the next file (`.../deps/*.dll.lib`) to not get added due to the `return`

Switching the statements in that block from `return` to `continue` fixes the issue locally for me

**Comment by Mark-Simulacrum** [comment]
Rebased and pushed up a separate commit with that fix. r? @alexcrichton

**Comment by Mark-Simulacrum** [comment]
I've tried to track this issue down but so far been fairly unsuccessful in determining the root cause. We're generating what appears to be two different version of libcore but I can't tell where the one in the sysroot is coming from -- no other file matches its hash in the build directory.

This leads me to believe that either Cargo is overwriting files when generating the coretests -- this feels fairly likely considering that we see `[RUSTC-TIMING] core test:false 38.168` in the build log right before the error, though core should not have been recompiled according to previous build logs.

I'm not sure why core is being recompiled -- what we should see is just coretests being compiled. It is unclear to me why Cargo compiles core, though it loosely looks like it could be somewhat of a bug. The below fingerprint error is the only one I see related to libcore in this invocation of Cargo, yet we see that cargo is building `Target(lib)/Profile(release)` (` INFO 2018-06-28T23:40:36Z: cargo::core::compiler::job_queue: start: core v0.0.0 (file:///checkout/src/libcore) => Target(lib)/Profile(release) => Target`) -- *without* checking the fingerprint for that.

@alexcrichton -- is there a chance this is a Cargo bug? Or am I misreading/misinterpreting this output? Full log for the coretest compile: https://gist.github.com/Mark-Simulacrum/8121483a4484fe2477d9af4adb47d9cc 

```
 INFO 2018-06-28T23:40:36Z: cargo::core::compiler::fingerprint: fingerprint error for core v0.0.0 (file:///checkout/src/libcore): failed to read `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/wasm32-unknown-unknown/release/.fingerprint/core-bd1cd8ef55dd7af8/test-integration-test-coretests-bd1cd8ef55dd7af8`                                                                                                      
```

```
[0KTesting core stage2 (x86_64-unknown-linux-gnu -> wasm32-unknown-unknown)
[01:13:25] [0m[0m[1m[32m   Compiling[0m rand v0.4.2
[01:13:27] [RUSTC-TIMING] rand test:false 2.324
[01:13:27] [0m[0m[1m[32m   Compiling[0m core v0.0.0 (file:///checkout/src/libcore)
[01:14:48] [RUSTC-TIMING] coretests test:true 81.272
[01:14:48] [0m[0m[1m[32m    Finished[0m release [optimized] target(s) in 1m 23.89s
[01:14:48] [0m[0m[1m[32m     Running[0m build/x86_64-unknown-linux-gnu/stage2-std/wasm32-unknown-unknown/release/deps/coretests-2918b84facad306a.wasm
[01:14:50] 	finished in 85.668
[01:14:50] travis_fold:end:test_stage2-core
```

currently:
```
rust/obj/build/x86_64-unknown-linux-gnu$ find . -name 'libcore*' | xargs sha1sum
222dfeeeec7438583c58f8f70eafebe21842314a  ./stage1-std/wasm32-unknown-unknown/release/libcore.rlib
222dfeeeec7438583c58f8f70eafebe21842314a  ./stage1-std/wasm32-unknown-unknown/release/deps/libcore-c3cb23bcc2322123.rlib
ca628c2a42e82d09e178ecd6132d77a2eef119be  ./stage1/lib/rustlib/wasm32-unknown-unknown/lib/libcore-c3cb23bcc2322123.rlib
a368e67761f1835d8b82e846b23c49218390981a  ./stage0-std/x86_64-unknown-linux-gnu/release/deps/libcore-8834350d01f8283c.rlib
82cf8fd73d016b0c68cffbc7f5a86f4bb83ea6c8  ./stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-27386c6ead892bb8.rlib
a368e67761f1835d8b82e846b23c49218390981a  ./stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-8834350d01f8283c.rlib
```

**Comment by alexcrichton** [comment]
Ok that bug should be fixed by https://github.com/rust-lang/cargo/pull/5669 (confirmed locally) and once that Cargo PR lands we'll need to backport it and then make a new beta to update to here

**Pull request merged**
