### PR TITLE
Use the guaranteed precision of a couple of float functions in docs

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by Nilstrieb** [comment]
This looks reasonable to me, but I'll let someone with more (too much?) floating point knowledge takes a look as well.
🧙🏻‍♀️ @workingjubilee 🧙🏻‍♀️

**Comment by workingjubilee** [comment]
THOU HAST SUMMONED ME?
oh hi.

**Comment by workingjubilee** [comment]
oh yeah these tests were being waaay too cowardly about value approximation. `.abs()` is very much guaranteed to be the positive of the negative.

@bors r+

**Pull request merged**
