### PR TITLE
Add Iterator trait TrustedLen to enable better FromIterator / Extend

### LINKED ISSUE #37232: Vec::extend generates suboptimal code with `.map`
## Meta

``` Rust
$ rustc -V
rustc 1.14.0-nightly (a3bc191b5 2016-10-10)
```
## STR

``` Rust
#![crate_type="rlib"]
#![feature(test)]

extern crate test;

pub fn example_slow(l: &[(u32, u32)]) -> Vec<u32> {
    let mut result = Vec::with_capacity(l.len());
    result.extend(l.iter().map(|x| x.0));
    result
}

pub fn example_fast(l: &[(u32, u32)]) -> Vec<u32> {
    let mut result = Vec::with_capacity(l.len());
    for i in 0..l.len() {
        unsafe {
            *result.get_unchecked_mut(i) = l[i].0;
            result.set_len(i);
        }
    }
    result
}

#[bench]
fn bench_slow(b: &mut test::Bencher) {
    let data = [(0, 0); 16384];
    b.iter(|| {
        test::black_box(example_slow(test::black_box(&data)));
    });
}

#[bench]
fn bench_fast(b: &mut test::Bencher) {
    let data = [(0, 0); 16384];
    b.iter(|| {
        test::black_box(example_fast(test::black_box(&data)));
    });
}

```
## Expected result

Both cases take the same amount of time
## Actual result

```
$ ./slo-and-fast --bench

running 2 tests
test bench_fast ... bench:       7,490 ns/iter (+/- 271)
test bench_slow ... bench:      11,247 ns/iter (+/- 1,735)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured
```

### PR DESCRIPTION
**Pull request by bluss**
This trait attempts to improve FromIterator / Extend code by enabling it to trust the iterator to produce an exact number of elements, which means that reallocation needs to happen only once and is moved out of the loop.

`TrustedLen` differs from `ExactSizeIterator` in that it attempts to include _more_ iterators by allowing for the case that the iterator's len does not fit in `usize`. Consumers must check for this case (for example they could panic, since they can't allocate a collection of that size).

For example, chain can be TrustedLen and all numerical ranges can be TrustedLen. All they need to do is to report an exact size if it fits in `usize`, and `None` as the upper bound otherwise.

The trait describes its contract like this:

```
An iterator that reports an accurate length using size_hint.

The iterator reports a size hint where it is either exact
(lower bound is equal to upper bound), or the upper bound is `None`.
The upper bound must only be `None` if the actual iterator length is
larger than `usize::MAX`.

The iterator must produce exactly the number of elements it reported.

# Safety

This trait must only be implemented when the contract is upheld.
Consumers of this trait must inspect `.size_hint()`’s upper bound.
```

Fixes #37232

### CODE REVIEW

**Comment by bluss** [comment]
Benchmark and result at https://gist.github.com/bluss/baa98105d141cff3949dda1c1f2d8cce

Using SetLenOnDrop was required to avoid the aliasing troubles in the case of `bench_rev_2`.

The .chain() cases unfortunately are not optimized well (remains as one loop that goes through the chain's state logic, instead of splitting it into two loops for the front and back part).

**Comment by bluss** [comment]
cc @eddyb @arielb1

**Comment by Mark-Simulacrum** [comment]
I believe at least this adapter for Result also should have TrustedLen implemented on it: https://github.com/rust-lang/rust/blob/master/src/libcore/result.rs#L997. I know it currently doesn't have a size_hint, but @eddyb had me add it in #37270, since we believe it should have it.

**Comment by bluss** [comment]
@Mark-Simulacrum Thanks. Yes, there's a ton of iterators that will need the marker

**Comment by alexcrichton** [comment]
Nice! Does this mean that we can remove some of the specialization around extending vectors from slices as well?

**Comment by bluss** [comment]
@alexcrichton I think it does. We can probably remove .extend_from_slice()'s implementation entirely.

**Comment by bluss** [comment]
Nevermind, extend_from_slice is Clone and extend(&[T]) requires Copy.

**Comment by bluss** [comment]
Ah, that's how to do it. Now extend_from_slice's own implementation is gone, and the specialization that redirected to it. (Sorry #37094 !)

**Comment by bluss** [comment]
A reason that there is no `trusted_len` method in the trait itself, is that I was thinking about the best way to avoid bugs, for example that iterators would implement such a hypothetical method correctly, but not size hint. So implementors only need to implement `size_hint`.

I guess we can add a debug assertion to where this is used.

**Comment by bluss** [comment]
`Vec::append` is moving all the elements by calling memcpy. We give llvm more to chew on if that's replaced by the two loops in .extend().

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

I personally feel that we should get rid of the other specialization of `Vec::extend(Vec<T>) -> Vec::append`, but that's a pretty minor concern. Curious what others think!

> Vec::append is moving all the elements by calling memcpy. We give llvm more to chew on if that's replaced by the two loops in .extend().

Right it gives LLVM more to chew on, but we've practically *never* optimized the standard library for minimizing the amount of code we send to LLVM, so I don't think now's really the time to start. Removing the extra specialization keeps it a little more understandable as there's only one specialization to consider, not multiple.

**Comment by bluss** [comment]
@alexcrichton Oh, I can be on board with that. As long as Vec::append's own implementation stays as it is.

**Comment by alexcrichton** [comment]
Oh yeah I wouldn't imagine any change to the implementation of `Vec::append`

**Comment by bluss** [comment]
The special case for `<Vec<T>>::extend(Vec<T>)` has been removed. The regular .extend() call was verified to be equivalent using a microbenchmark (but only with optimizations applied).

**Comment by bluss** [comment]
Benchmark file for this PR https://gist.github.com/bluss/3828cadbd92f5a94d020a474b9879f6c

One highlight is the `.map()` case speeding up, like requested in the bug report:

```
bench_map_fast                  6,061                        6,245                                  184    3.04%
bench_map_regular               14,108                       6,429                               -7,679  -54.43%
```

`map_fast` is this code:

```rust

pub fn map_fast(l: &[(u32, u32)]) -> Vec<u32> {
    let mut result = Vec::with_capacity(l.len());
    for i in 0..l.len() {
        unsafe {
            *result.get_unchecked_mut(i) = l[i].0;
            result.set_len(i);
        }
    }
    result
}
```

and the other one is just `v.extend(data.iter().map(|t| t.1));`

**Comment by bluss** [comment]
Something that's not in this PR is to replace the for loop in `Vec::extend` with `.fold()`. That has some dramatic effects on `.chain()` when using extend/collect: https://gist.github.com/bluss/fad6a046491896ae4a4bf4655869b869

Remember that most of these benchmarks are best cases, where the iterator element is a small value and where loop optimizations like unrolling or converting to memcpy have a big impact.

**Comment by brson** [comment]
Waiting for @Kimundi to chime in.

**Comment by bluss** [comment]
Opened a tracking issue and linked it in.

**Comment by alexcrichton** [comment]
Looks like travis error is legit?

**Comment by bluss** [comment]
Yes, sorry, syntax error in the stability attr. Fixed by amending that commit.

**Comment by jonhoo** [comment]
Was there a particular reason behind not taking advantage of `TrustedLen` for `HashMap::from_iter`?

**Comment by bluss** [comment]
No reason, if it makes sense, just explore it

**Pull request merged**
