### PR TITLE
atomic::Ordering: Get rid of misleading parts of intro

### LINKED ISSUE #55196: Dangerously misleading introduction to std::sync::atomic::Ordering
When looking at https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html, this is in the intro:

> At its most restrictive, "sequentially consistent" atomics allow neither reads nor writes to be moved either before or after the atomic operation;

This is not true (even the explanations for variants disprove this, but if someone reads only the intro, they could get to the conclusion that using SeqCst is good enough everywhere, which it actually isn't).

Eg, from the docs below:

> SeqCst: Like AcqRel with the additional guarantee that all threads see all sequentially consistent operations in the same order.

> AcqRel: For loads it uses Acquire ordering. For stores it uses the Release ordering.

So, `atomic.load(Ordering::SeqCst)` has `Acquire` semantics (+ participating in the global timeline of all SeqCst operations), which means reads and writes are allowed to be reordered after the operation. And even failed CAS operation is effectively just a read, so operations are allowed to be reordered after the operation.

I have the vague memory someone was updating it recently to actually point out these gotchas, but I can't find that now.

I can try rewording it, but I'm not really that good at writing good concise documentation.

### PR DESCRIPTION
**Pull request by vorner**
Remove the parts of atomic::Ordering's intro that wrongly claimed that
SeqCst prevents all reorderings around it.

Closes #55196

This is a (minimal) alternative to #55233.

I also wonder if it would be worth adding at least some warnings that atomics are often a footgun/hard to use correctly, similarly like `mem::transmute` or other functions have.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This seems correct - approving.

However, I personally don't find the intro about `Relaxed` and `SeqCst` particularly useful. It's full of jargon and lacking details:

* What does "synchronized" mean?
* What does "total order" mean?
* What is a store-load pair? How do operations pair up?
* What memory do store-load `SeqCst` operations synchronize?

For people who don't know about memory orderings that might sound like gibberish. :) And for people who do, it's not very informative anyway.

Just saying something equivalent to "use `SeqCst` if in doubt and read the LLVM docs to learn more" would be enough, I think.

**Comment by vorner** [comment]
> However, I personally don't find the intro about Relaxed and SeqCst particularly useful. It's full of jargon and lacking details

Well, I tried to write something more useful in #55233 and the consensus was that such things should probably go to nomicon (and I plan on updating that eventually). So, I don't know how much I'm able to say without giving a full, digestible explanation and still be correct.

I'm open to discussing what level of explanation is appropriate here and in the nomicon. But I'd like to get rid of the wrong parts first.

> Just saying something equivalent to "use SeqCst if in doubt and read the LLVM docs to learn more" would be enough, I think.

That's the other quite often given advice about atomics I quite don't like, because it is misleading. If in doubt, read the LLVM docs ‒ sure, but using SeqCst without understanding how the synchronization works is likely to lead to wrong code (eg. SeqCst on compare_and_swap that didn't swap won't publish my changes and it's a non-obvious trap).

That's what I was asking about the warning ‒ should we say something like „Don't mess with these until you read the docs and use `Mutex` instead“?

**Comment by stjepang** [comment]
> Well, I tried to write something more useful in #55233 and the consensus was that such things should probably go to nomicon (and I plan on updating that eventually).

That'd be fantastic! <3

> That's the other quite often given advice about atomics I quite don't like, because it is misleading.

You're right and the pitfall of sequentially consistent CAS operations is a very good point. However, I'll be a little sad if our docs say "if you don't understand memory orderings, use mutexes".

In [Java](https://docs.oracle.com/javase/tutorial/essential/concurrency/atomic.html), `volatile` variables are just sequentially consistent atomics and I think they can be productively used by anyone without a deep understanding of memory orderings. The same applies to e.g. [Go](https://golang.org/pkg/sync/atomic/) and [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics). Note that the docs of those languages don't even mention orderings. In C++, `std::atomic` is designed so that `SeqCst` is the default ordering for all operations and you can use it without even thinking about memory barriers. I wish atomics in Rust don't get reserved for advanced users only.

Also, I'd point out that mutexes and RW locks come with their own similar pitfalls. For example, they're not guaranteed to be sequentially consistent. Or, read operations in RW locks can [elide](https://software.intel.com/en-us/node/506266) actual locking if there's no contention. And yet, mutexes and RW locks can be used fearlessly by anyone without even understanding those words.

Anyways, just my two cents. :) This PR is good to go as far as I'm concerned. 👍

**Pull request merged**
