### PR TITLE
rustc: fix ICE when trait alias has bare Self

### PR DESCRIPTION
**Pull request by seanmonstar**
Fixes https://github.com/rust-lang/rust/issues/59029

### CODE REVIEW

**Comment by seanmonstar** [comment]
cc @alexreg

**Comment by alexreg** [comment]
@seanmonstar Thanks! I'm glad the simple fix seems to have worked. Would you mind creating a new test under `src/test/run-pass/issues/issue-XYZ.rs` and writing a bit of code there that actually uses a trait alias with a `Self` bound in some meaningful way (simple is fine, but at least have an assert)? You can just revert the existing test file then.

**Comment by alexreg** [comment]
Okay, so this fix isn't actually enough, it seems... Could you try the following locally and let me know if they succeed?

```rust
trait SelfWhere<One, Two> = Assoc<Two> where Assoc<Two>::Out: Assoc<One>;
```

and

```rust
trait SelfWhere<One, Two> = Assoc<Two> where <Self as Assoc<Two>>::Out: Assoc<One>;
```

**Comment by seanmonstar** [comment]
The second one does work, it's part of the initial bug report. I haven't tried the first yet.

If `Self` should be qualified, I can just change this to a compile-fail test checking for the right error.

**Comment by seanmonstar** [comment]
The first one (`Assoc<Two> where Assoc<Two>::Out: Assoc<One>`) complains about "abiguous associated type".

**Comment by alexreg** [comment]
As a loose analogy to [this example](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=c240bb503b2f8f359101b8b20e831ac3) (insofar as it involves trait bounds on an associated type), I'm of the opinion that it's fine for `Self` alone not to work (so long as it doesn't ICE, of course).

So, now that we've solved the ICE, the question is: do we want better diagnostics when, e.g., `trait SelfWhere<One, Two> = Assoc<Two> where <Self as Assoc<Two>>::Out: Assoc<One>;` is used. @estebank, what do you think about the error message in the above CI test failure. Should we be doing better?

@seanmonstar Let's have a `ui` test for the failing case (just `Self`), and a run-pass test for the case that should pass (`<Self as ...>`). Two new test files. You can put them both in the `ui/issues/` dir though, maybe, and just annotate the passing one with `// run-pass` as its first line.

**Comment by estebank** [comment]
@alexreg it's probably fine. The ideal output would be to provide a suggestion to use `<Self as Svc<Target>>::Res`, but to do that you'd have to peek into `Svc` to see if the assoc type not found exists in it. I'm ok with merging this PR as is.

**Comment by alexreg** [comment]
@estebank Great. I'm okay with merging this as-is too, in that case.

**Pull request merged**
