### PR TITLE
add Miri to rustc rustdoc page

### PR DESCRIPTION
**Pull request by RalfJung**
Based on https://github.com/rust-lang/rust/pull/97773 by @InfRandomness 
r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
@RalfJung can you double check that `x doc src/tools/miri` works for you locally? I saw you added the `try_run` to make it optional, which is great, but I think we should at least have no warnings initially if we can help it.

**Comment by RalfJung** [comment]
```
 Documenting miri v0.1.0 (/home/r/src/rust/rustc.2/src/tools/miri)
    Finished release [optimized + debuginfo] target(s) in 41.43s
Build completed successfully in 0:12:23
```
Seems to work fine.

@InfRandomness you are marked as their author.

**Comment by InfRandomness** [comment]
Ah I know what happened, I put a lowercased username in, I think that's because of that,
can it be corrected or is it too late ?

**Comment by RalfJung** [comment]
If you produce commits with fixed emails in your fork, I can cherry-pick them.

**Comment by InfRandomness** [comment]
> If you produce commits with fixed emails in your fork, I can cherry-pick them. (But this PR might get rolled up any time and then it will be too late.)

My fork is completely destroyed, can I fork your fork, rebase and then have you cherry-pick it ?

**Comment by jyn514** [comment]
This is not going to be any easier than the initial submodule stuff that gave you trouble.

**Comment by RalfJung** [comment]
> My fork is completely destroyed, 

Your Github fork is fine. Your local copy of it might be busted, but you can just delete that and re-clone.

**Comment by RalfJung** [comment]
If you want to try that, fine with me.
@bors r-

**Comment by InfRandomness** [comment]
@RalfJung Okay I have successfully changed the author on my fork ! :smile:

**Comment by InfRandomness** [comment]
> Nice. :) So do you want to create a PR from your branch [https://github.com/InfRandomness/rust/tree/miri-rustdoc](https://github.com/InfRandomness/rust/tree/miri-rustdoc?rgh-link-date=2022-07-01T13%3A31%3A44Z) ?

Yep, done !

**Pull request closed without merging**
