### PR TITLE
[WIP] [DO NOT MERGE] combine #66020 and #66821.

### PR DESCRIPTION
**Pull request by eddyb**
That is, the two fixes for #65510, and only for perf testing purposes.
The fact that they both work to a comparable extent, while touching different parts of the trait system, made me curious if there would be any gains from having both.

r? @nikomatsakis

### CODE REVIEW

**Comment by eddyb** [comment]
That's significantly better than just either #66020 or #66821 alone, wow.
So they are indeed orthogonal, or at least partially so.

The `futures` and `serde` wins are so significant they cannot, in good conscience, be ignored, as this is mostly likely performance we've effectively been leaving on the table *for a couple years*.
*Even if* these PRs may not be perfectly sound, I don't think a perfect solution, whatever that may consist of, would lose much of the wins demonstrated here.

cc @rust-lang/compiler @rust-lang/wg-traits I'm nominating this for discussion, so that we can find a way to land *at least* some of these changes.

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/76822weeklymeeting2019120554818.html#182671909) in last week's T-compiler meeting

Main conclusion:

* we should invest effort in landing the caching changes, but hold off on the WF changes

**Comment by eddyb** [comment]
The caching changes already landed, and I closed #66020 already, closing this too.

**Pull request closed without merging**
