### PR TITLE
Try fixing bigendian metadata serialisation

### PR DESCRIPTION
**Pull request by nagisa**
I compiled this on PPC to check and it seems to work, but not sure whether I didn't mess up
anything in a major way.

Maybe a good shot at #41443

The easiest way to *really* test this is to land the patch (a high priority would be good, since I quite literally am just twiddling my thumbs on this now), wait for nightly, and, if the nightly works, backport this to beta.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
:tada:

**Comment by nagisa** [comment]
Confirming the relevant issue as fixed.

**Comment by cuviper** [comment]
Are you backporting this to beta?  I guess we need someone to agree on `beta-accepted`.

**Comment by nagisa** [comment]
We’ll discuss accepting this on Thursday’s compiler team meeting.

**Comment by nikomatsakis** [comment]
I'd be in favor of backporting; small patch. I've not looked deeply at the other side to confirm it's correct, but since nothing has fallen over, and it was tested, I'm assuming it is. =)

cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
I went ahead and marked as accepted since today is a "focus" mtg. If anyone objects, feel free to leave a comment!

**Comment by michaelwoerister** [comment]
+1 for backporting

**Pull request merged**
