### PR TITLE
Permit only optimizing/emitting debuginfo for specific stages.

### PR DESCRIPTION
**Pull request by DiamondLovesYou**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can you explain the use case?

**Comment by DiamondLovesYou** [comment]
I use it to debug (like with gdb) a stage2 rustc without waiting for a debug build of stage1 rustc to compile stage2 rustc.

**Comment by DiamondLovesYou** [comment]
@Mark-Simulacrum No, I'm using `optimize = false`.

**Comment by Mark-Simulacrum** [comment]
Generally speaking it's not really supported/expected to compile Rust without optimizations -- it should be far faster to enable debuginfo unconditionally and enable optimizations. Is this not the case for you?

I believe the documentation inside config.toml.example states something along these lines...

**Comment by ExpHP** [comment]
Just to complete the link loop (wherein a couple of numbers are shared):

https://users.rust-lang.org/t/could-a-stage-1-release-compiler-build-a-stage-2-debug-compiler/17438

**Comment by pietroalbini** [comment]
Ping from triage @Mark-Simulacrum @DiamondLovesYou! What should we do with this PR?

**Comment by Mark-Simulacrum** [comment]
I'm not really opposed to landing this (code looks fine, though I haven't reviewed in detail). I'm still not convinced that this is necessary -- I see the use case, in theory, but I think for now I'm inclined to state that users should disable optimization and then enable it selectively via `RUSTFLAGS_STAGE_N="-Copt-level=2"` which I believe should work.

**Comment by DiamondLovesYou** [comment]
@Mark-Simulacrum I leave it up to you. I'd like it in, as it makes things simple for me, but I can resort to setting `RUSTFLAGS_STAGE_N` as you said if rejected.

**Comment by Mark-Simulacrum** [comment]
Okay, I'm going to close this then -- I think I'd accept a patch that did this via a single flag, but I'm not sure how exactly that would work. My understanding is that there's two states we want: optimize all compilations, optimize all but the last rustc compilation. It seems likely that we could encode that into the `optimize` and/or `debug` parameters in the configuration. If you'd like to implement that, I think the changes should be smaller and it'll be more useful overall: generally speaking I'd prefer to expose less low-level knobs for things like this.

**Comment by DiamondLovesYou** [comment]
Well, if I did create such a patch, I'd likely do as a patch on this patch, leaving most of the changes except the stuff exposed to the configs. But then, at that rate, as I generally assume people are not babies, would rather just give people access to the knobs to fiddle at their leisure. Besides, if one is doing work/debugging the compiler itself, they probably want access to these knobs. What if the developer is investigating something in the stage1 compiler? We can't know these things a priori.

I'll just use `RUSTFLAGS_STAGE_N`.

**Pull request closed without merging**
