### PR TITLE
optimize redundant borrows and escaping paths in NLL 

### PR DESCRIPTION
**Pull request by nikomatsakis**
This builds on https://github.com/rust-lang/rust/pull/53168 and adds a commit that addresses https://github.com/rust-lang/rust/issues/53176 -- or at least I think it does. I marked this as WIP because I want to see the test results (and measure the performance). I also want to double check we're not adding in any unsoundness here.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@rust-timer build a7a1e7a9bda496d4f9f0fbd27d7cd126b18e8047

**Comment by kennytm** [comment]
Perf is ready.

**Comment by BurntPizza** [comment]
*\*Clicks link\**
*\*Falls out of chair\**

**Comment by nikomatsakis** [comment]
So yeah, seems like a win. =)

**Comment by wesleywiser** [comment]
`max-rss` is also looking great! 🎉 


html5ever-check | avg: -4.9% | min: -23.5% | max: 0.5%
-- | -- | -- | --

**Comment by nikomatsakis** [comment]
@bors r=pnkfelix p=1

I'm going to take the liberty of r+'ing that change, which is tiny, since pnkfelix is on PTO.

**Comment by nikomatsakis** [comment]
I also bumped priority because NLL is crucial EP2 component and this has a big effect on perf, at least in some cases.

**Pull request merged**
