### PR TITLE
liblibc: correct Linux ioctl request type

### PR DESCRIPTION
**Pull request by emberian**

### CODE REVIEW

**Comment by alexcrichton** [comment]
On OSX the manpage says:

> `int ioctl(int fildes, unsigned long request, ...);`

On linux (ubuntu) it says:

> `int ioctl(int d, int request, ...);`

How'd this arise?

**Comment by cmr** [comment]
That man page (probably ioctl(3p))is wrong, if you look at the actual `sys/ioctl.h`  or `stropts.h` header. `man 2 ioctl` is correct as well.

**Comment by cmr** [comment]
(It even has the standard "Linux implementation of this interface may differ" disclaimer up top!)

**Comment by alexcrichton** [comment]
Fascinating! I'm losing trust in manpages quickly now!

@bors: r+ cea9330bd11379ef56ee0c4f80b44f228660b9e9

**Comment by cmr** [comment]
@alexcrichton The man pages in section 2 and 3 can usually be trusted, but not section 3p (they're just the POSIX manuals imported directly). But I almost always skip them and go straight to the headers.

**Pull request merged**
