### PR TITLE
Speed up bootstrap a little.

### PR DESCRIPTION
**Pull request by ehuss**
The bootstrap script was calling `cargo metadata` 3 times (or 6 with `-v`). This is a very expensive operation, and this attempts to avoid the extra calls. On my system, a simple command like `./x.py test -h -v` goes from about 3 seconds to 0.4.

An overview of the changes:

- Call `cargo metadata` only once with `--no-deps`. Optional dependencies are filtered in `in_tree_crates` (handling `profiler_builtins` and `rustc_codegen_llvm` which are driven by the config).
- Remove a duplicate call to `metadata::build` when using `-v`. I'm not sure why it was there, it looks like a mistake or vestigial from previous behavior.
- Remove check for `_shim`, I believe all the `_shim` crates are now gone.
- Remove check for `rustc_` and `*san` for `test::Crate::should_run`, these are no longer dependencies in the `test` tree.
- Use relative paths in `./x.py test -h -v` output.
- Some code cleanup (remove unnecessary `find_compiler_crates`, etc.).
- Show suite paths (`src/test/ui/...`) in `./x.py test -h -v` output.
- Some doc comments.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I don't know that this performance matters that much - in practice, compiling is going to take a minute or two I think, at least. But I think it's a good cleanup regardless. I think it's fine to hard code profiler builtins and LLVM in bootstrap for the extra perf win as well.

**Comment by petrochenkov** [comment]
I does matter - running `x.py test` on a single test is a pretty common operation that performs no-op build (which runs all these operations, as far as I understand), and that no-op build takes some noticeable time, and it would be good to make it faster.

**Comment by Mark-Simulacrum** [comment]
Yes, though I think those no-op builds will end up doing something similar to cargo metadata? So it's not as significant a win. Still, seconds shaved off of every build is good.

**Comment by ehuss** [comment]
OK, I have pushed an update that uses `--no-deps`.  I also did a few small drive-by fixes, which I can split off if necessary.  They are:

- Use relative paths in `./x.py test -h -v` output.
- Some code cleanup (remove unnecessary `find_compiler_crates`, etc.).
- Show suite paths (`src/test/ui/...`) in `./x.py test -h -v` output.
- Some doc comments.

**Comment by Mark-Simulacrum** [comment]
r=me with the description updated to include the latest changes (profiler builtins and llvm in particular).

**Pull request merged**
