### PR TITLE
Very minor spelling fix in the book

### PR DESCRIPTION
**Pull request by ErikUggeldahl**
Changed datastructure to data structure.

r? @steveklabnik

### CODE REVIEW

**Comment by ErikUggeldahl** [comment]
A brief search shows that this is the only page that uses this spelling, so we should be good after this.

**Comment by ErikUggeldahl** [comment]
Also, I should take the opportunity to thank you @steveklabnik for all of your hard work on documentation. I'm looking forward to the next iteration of the book, and I wish you and Carol all the success in writing it!

**Comment by apasel422** [comment]
@bors: r+ rollup

Thanks!

**Comment by steveklabnik** [comment]
Thanks :smile:

**Pull request merged**
