### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #104898 (Put all cached values into a central struct instead of just the stable hash)
 - #105004 (Fix `emit_unused_delims_expr` ICE)
 - #105174 (Suggest removing struct field from destructive binding only in shorthand scenario)
 - #105250 (Replace usage of `ResumeTy` in async lowering with `Context`)
 - #105286 (Add -Z maximal-hir-to-mir-coverage flag)
 - #105320 (rustdoc: simplify CSS selectors on top-doc and non-exhaustive toggles)
 - #105349 (Point at args in associated const fn pointers)
 - #105362 (Cleanup macro-expanded code in `rustc_type_ir`)
 - #105370 (Remove outdated syntax from trait alias pretty printing)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=104898,105004,105174,105250,105286,105320,105349,105362,105370)

### CODE REVIEW

**Comment by Swatinem** [comment]
NOTE to whoever might triage this regression:

The changes to `deeply-nested-multi`, `issue-88862` and `await-call-tree` seem to be the effect of https://github.com/rust-lang/rust/pull/105250 and revert some earlier [wins from #104321](https://github.com/rust-lang/rust/pull/104321#issuecomment-1326854799).

This is a bit surprising to me though, I would have expected this to rather further improve things if anything, as it removes a fn call in favor of a more complex but also more correct type.

**Comment by rylev** [comment]
@rust-timer build 19a19284681762447cbed6f2543fd83583612d19

**Comment by rylev** [comment]
It does seem that https://github.com/rust-lang/rust/pull/105250 is the culprit. It's still small enough that I don't think we necessarily need to do anything about it. 

cc @Swatinem @oli-obk

**Comment by Swatinem** [comment]
I’m working on https://github.com/rust-lang/rust/pull/105668 currently, which fixes a regression from https://github.com/rust-lang/rust/pull/105250. That might as well win these perf regressions back as it avoids carrying around that more complex type altogether.

**Pull request merged**
