### PR TITLE
libcore documentation for builtin macros

### PR DESCRIPTION
**Pull request by newpavlov**
Fixes: #36272

Additionally I've edited docstring for `include!` a bit. (related PR #36404)

Unfortunately it seems there is no sane way to reexport empty macros definitions for their docstrings. To avoid copying the whole documentation for builtin macros I've only copied description and added links to `std` macro pages.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Is it not possible to move the macros currently in `std` from `std` to `core` and add them to [this attribute](https://github.com/rust-lang/rust/blob/0c429872a32c3005cf2b347025163361218634a4/src/libstd/lib.rs#L302-L307)?

**Comment by newpavlov** [comment]
I mentioned it in the OP. Naively moving `mod builtin` to `libcore` and adding reexports will result in `reexported macro not found` error. I've tried to play around with `#[cfg_attr(dox, macro_reexport(...))]` but without any results.

I am unable to fully analyze why this error happens, but my guess is what when we trying to compile docs and use `extern crate core` we compile `libcore` without `dox` option. Probably it can be fixed by modification of makefile or by using some another way, but it will require more in-depth knowledge which I do not currently posses.

**Comment by newpavlov** [comment]
If you want to try to fix `reexported macro not found` error you can look at this [branch](https://github.com/newpavlov/rust/tree/builtin_macros_doc).

**Comment by frewsxcv** [comment]
Thanks!

@bors r+ rollup

**Comment by eddyb** [comment]
Sadly this broke cross-crate `[src]` links, which was already a crumbling pile of hacks.
What's happening is that this introduces *exactly* one new item (the `mod`) which is not present when `libcore` is build regularly, and *that* determines what `DefId`s compiling `libstd` sees.
The difference of `1` in the `DefId` (or rather, `DefIndex`) between documented `libcore` and imported-by-`libstd` `libcore` shows up in the cross-crate `[src]` links which assumes the two `libcore`s are identical.

Simplest fix would be to just remove the `mod` and apply the `#[cfg(dox)]` to each macro instead.
cc @rust-lang/tools

**Comment by newpavlov** [comment]
@eddyb 
So I need to remove `mod builtin` from libcore and instead use `#[cfg(dox)]` on each builtin macros, is it right? Should I create another pull request for it?

**Comment by eddyb** [comment]
@newpav Sorry it didn't get linked. There's already a fix up, #37727.

**Pull request merged**
