### PR TITLE
document trait impls when the type appears in the trait's generics

### LINKED ISSUE #25264: Advertise impls of out-of-create traits for third party types with some type parameters set to in-crate types in rustdoc
As an example, in iron, the impls of `Modifier<Response>` for std types like `String`, `File`, and `Path` are not advertised anywhere in the generated documentation.

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Fixes #25264

image

### CODE REVIEW

**Comment by steveklabnik** [comment]
Iiinteresting. I like it, would like to see what others say.

**Comment by QuietMisdreavus** [comment]
I guess we should properly tag @rust-lang/docs to pull in the others, in that case.

**Comment by GuillaumeGomez** [comment]
Wo, that's awesome! Huge 👍 for me!

**Comment by steveklabnik** [comment]
@bors: r+

everyone is happy with this!

**Pull request merged**
