### PR TITLE
add more tests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
r? @jieyouxu

### CODE REVIEW

**Comment by jieyouxu** [comment]
Thanks! r=me after CI is green

**Comment by matthiaskrgr** [comment]
something failed on win
@bors r-
https://github.com/rust-lang/rust/pull/124442#issuecomment-2081126680

**Comment by matthiaskrgr** [comment]
"file not found" is different on windows and linux, need to norm test output
@bors r=jieyouxu rollup=iffy

**Pull request merged**
