### PR TITLE
Update rustfmt and rls

### PR DESCRIPTION
**Pull request by topecongiro**
This PR bumps the version of rustfmt to 1.3.0.

### CODE REVIEW

**Comment by topecongiro** [comment]
No idea where the error comes from or how to fix it... 🙄

**Comment by alexcrichton** [comment]
I think the rebase is probably good enough for now to fix the original error, but it looks like new errors are showing up?

**Comment by topecongiro** [comment]
Ok, rls has been in test-failing state since 673cf7de44b5a98092b5bc7cf2906e866383a65d (https://rust-lang-nursery.github.io/rust-toolstate/). AFAICT from the log, if a PR is updating one of the submodule that is in test-failing state, then the PR needs to fix that to test-passing.

cc @Xanewok

**Comment by topecongiro** [comment]
Is there any way to work around this for now? I just want to update `rls` so that both rls and rustfmt uses the same version of `rustc-ap-*` crates.

**Comment by topecongiro** [comment]
Looks like the test state of rls is fixed since 605ea9d05c48957a291eec11eb7339788c3140ed so trying again.

**Comment by Xanewok** [comment]
@topecongiro please also update RLS to https://github.com/rust-lang/rls/commit/4b13b102c876c01adf45d23273014646e863e33d - this ignores a Racer test that started causing spurious failures.
Looking at the PRs affected it seems like it's the only test that's the cause; hopefully that's true for now. Will investigate this later but let's make landing RLS submodule bumps easier for now.

**Comment by topecongiro** [comment]
Thank you @Xanewok!

@bors r+

**Comment by Centril** [comment]
Added to rollup in https://github.com/rust-lang/rust/pull/61962.

**Comment by Xanewok** [comment]
Now let's hope that the highfive spam about changed RLS toolstate will finally be over :smile:

**Pull request merged**
