### PR TITLE
Migrate diagnostics in `hir_typeck/src/cast.rs`

### PR DESCRIPTION
**Pull request by clubby789**

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
r=me

**Comment by clubby789** [comment]
I did want to note there's a few places with `fcx.ty_to_string` previously being wrapped in `DelayDm` or `DecorateLint` which are now being done more eagerly. I'm not sure if this causes any issues, or if there's a pre-existing solution for these - will just using a `Ty<'tcx>` as an arg result in the same output when formatted?

**Comment by compiler-errors** [comment]
> will just using a `Ty<'tcx>` as an arg result in the same output when formatted?

Yes, make sure that the types passed in have been resolved (`resolve_vars_if_possible`) if they have not yet.

**Comment by compiler-errors** [comment]
@clubby789 can you double check that all the places you're now using `Ty<'_>` in diagnostics, those tys have been previously `resolve_vars_if_possible`'d, and if not, pls add those. The worst regression here would be a `_` over a concrete ty, but it's kinda annoying and not hard to protect against.

Then r=me 

@rustbot author

**Pull request merged**
