### PR TITLE
Revamp codegen tests to check IR quality instead of quantity

### PR DESCRIPTION
**Pull request by dotdash**
The current codegen tests only compare IR line counts between similar
rust and C programs, the latter getting compiled with clang. That looked
like a good idea back then, but actually things like lifetime intrinsics
mean that less IR isn't always better, so the metric isn't really
helpful.

Instead, we can start doing tests that check specific aspects of the
generated IR, like attributes or metadata. To do that, we can use LLVM's
FileCheck tool which has a number of useful features for such tests.

To start off, I created some tests for a few things that were recently
added and/or broken.

### CODE REVIEW

**Comment by huonw** [comment]
Very cool.

**Comment by luqmana** [comment]
Looks good to me! I'll refrain from r+'ing though since it seems like @nikomatsakis or someone should get the chance to see it first.

**Comment by alexcrichton** [comment]
Amazing! I'm really looking forward to turning back on these kinds of tests. A few questions:

* I forget if we're actually running these by default, but these look like they'll be solid enough to enable by default, so just to confirm, these are run on `make check`, right?
* What's up with the `-C no-prepopulate-passes` argument to each test? Should that be an argument specified by compiletest or are there tests that may not wish to pass that?
* Do you know how brittle these tests would be across LLVM versions? In theory we have support for a number of LLVM version ranges, but we may want to disable the tests entirely on earlier LLVM versions if it causes problems. Also, do you know if it'd be difficult to update these tests with an LLVM upgrade?

**Comment by luqmana** [comment]
It would probably be a good idea to let different tests decide whether or not they want to pass `-C no-prepopulate-passes`. I can see a test that wants to make sure something about an `always_inline` function and thus doesn't want it to disappear from the IR.

As for brittleness, that really depends on how specific the tests get. For the initial couple in this pull we're only checking things like argument attributes (`noalias`, `nocapture` etc) and I don't expect those to change all that much. In any case, in the event they did change, we'd have to upgrade `librustc` anyways to emit the right flags, changing some tests wouldn't be all that bad.

**Comment by alexcrichton** [comment]
@luqmana hm yeah makes sense about `no-prepopulate-passes`. How come these tests require it though? (just curious)

> As for brittleness, that really depends on how specific the tests get.

True, I suspect it wouldn't be too hard to upgrade. I'm mostly just worried about multiple LLVM versions but we can always deal with that later as well!

**Comment by dotdash** [comment]
> @luqmana hm yeah makes sense about no-prepopulate-passes. How come these tests require it though? (just curious)

That's to make sure we actually check what we emit and not what LLVM can deduce. Also, the way the tests are written, the deduced flags would actually make them fail.

The tests should run by default, but I'll test that tomorrow to make sure. I also forgot to remove some remaining code from the old codegen test setup that checks for clang. Will fix that tomorrow, too.

**Comment by alexcrichton** [comment]
> That's to make sure we actually check what we emit and not what LLVM can deduce.

Ah of course!

> The tests should run by default, but I'll test that tomorrow to make sure. I also forgot to remove some remaining code from the old codegen test setup that checks for clang. Will fix that tomorrow, too.

Perfect! r=me with those minor changes and/or validations.

**Pull request merged**
