### PR TITLE
Terminate `--print link-args` output with newline

### LINKED ISSUE #127507: `--print link-args` does not print a newline
Running with `--print link-args` doesn't include a trailing `\n` so the next shell prompt gets smooshed on:

```sh
root@886c7cdb990c:/home# rustc a.rs --print link-args
LC_ALL="C" PATH="/root/.rustup/ /* SNIP */ "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"root@886c7cdb990c:/home#
```

I can't imagine this is intentional since all other `--print` options seem to include the newline.

```
rustc 1.81.0-nightly (35b658fb1 2024-07-08)
binary: rustc
commit-hash: 35b658fb1071d752d092751d9f17a9fa7b154ec4
commit-date: 2024-07-08
host: aarch64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### PR DESCRIPTION
**Pull request by eggyal**
Fixes #127507

### CODE REVIEW

**Comment by Urgau** [comment]
Would be good to update [`tests/run-make/link-arg/rmake.rs`](https://github.com/rust-lang/rust/blob/master/tests/run-make/link-arg/rmake.rs) to verify that there is indeed a new-line.

**Comment by compiler-errors** [comment]
yeah, r=me after adding a test

@rustbot author

**Comment by eggyal** [comment]
Test added.  @rustbot ready

**Comment by eggyal** [comment]
Pretty sure I don't have permission to do this, but given https://github.com/rust-lang/rust/pull/127512#issuecomment-2218679658... @bors r=compiler-errors rollup

**Pull request merged**
