### PR TITLE
std: Add capacity guarantees notes for OsString

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR intends to stabilize feature `try_reserve_2`, part of https://github.com/rust-lang/rust/issues/91789

This PR will is split from https://github.com/rust-lang/rust/pull/95392

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
I think copying the same cursory 1-sentence comment into 7 different places is not the best way to accomplish this documentation. I would prefer to see a single section that explains this topic more clearly in detail, probably with example code to illustrate some correct and incorrect uses of the APIs where this guarantee is relevant. Especially showing the incorrect case is important to illustrate the limitations of this guarantee (the "not specified" case).

This section would probably be most appropriate on the `OsString` type but alternatively on the `capacity()` method could work too, depending on how you write it. Everywhere else where that content is important to understand can just link to it.

**Comment by joshtriplett** [comment]
Updated version in https://github.com/rust-lang/rust/pull/97202 .

**Pull request closed without merging**
