### PR TITLE
Use edition of `macro_rules` when compiling the macro

### PR DESCRIPTION
**Pull request by ehuss**
This changes the edition assigned to a macro_rules macro when it is compiled to use the edition of where the macro came from instead of the local crate's edition.

This fixes a problem when a macro_rules macro is created by a proc-macro. Previously that macro would be tagged with the local edition, which would cause problems with using the correct edition behavior inside the macro. For example, the check for unsafe attributes would cause errors in 2024 when using proc-macros from older editions.

This is partially related to https://github.com/rust-lang/rust/issues/132906. Unfortunately this is only a half fix for that issue. It fixes the error that happens in 2024, but does not fix the lint firing in 2021. I'm still trying to think of some way to fix that, but I'm running low on ideas.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Do you expect this to have any effect on preexisting code? In that case, should we crater this change?

**Comment by petrochenkov** [comment]
It would be better to run crater on this.

**Comment by compiler-errors** [comment]
@rust-timer build 9a6ce9bcee4fff9f2010ea88aaa7654cc4d95132

**Comment by compiler-errors** [comment]
Actually why did I start rust-timer on this? Anyways, ignore that.

**Comment by compiler-errors** [comment]
From a cursory glance, looks like they're all just spurious crater failures. It does not seem like any of these crates are affected by this change.

**Review by traviscross — APPROVED** [review]

**Review by compiler-errors — APPROVED** [review]

**Comment by apiraino** [comment]
This caused a regression in #135669. T-lang decided to keep this behaviour, at least for now ([comment](https://github.com/rust-lang/rust/issues/135669#issuecomment-2637869022)). For this reason I'm adding this to be mentioned in the next releases notes (hoping it's the correct procedure):

@rustbot label +relnotes

**Pull request merged**
