### PR TITLE
add config option to add only debug! (and not trace!) calls

### PR DESCRIPTION
**Pull request by guswynn**
in #76588, @jyn514 mentioned that one way we could *possibly* turn on logging by default is to separate debug! and trace! calls

even if we don't go with it as default, its still nice to separate them so we can have granularity if we want it, AND so we can actually test the perf lost by making it default

r? @jyn514 @Mark-Simulacrum

### CODE REVIEW

**Comment by jyn514** [comment]
I'm not sure who the expected audience for this is. Very few parts of the compiler distinguish between `trace!` and `debug!`, so this doesn't have much of a performance impact, and personally I would still keep `trace` level logging on even if you added this option.

The idea I was thinking of was to _move_ some logging from debug! to trace!. However, that will require building a consensus with the relevant parts of the compiler team that this is a useful thing to do. If you're interested in that route, take a look at [the zulip for t-compiler](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler), especially ['improving bootstrap times for contributor fun and profit'](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/improving.20bootstrap.20times.20for.20contributor.20fun.20and.20profit).

As-is, though, I don't see much point to this.

**Comment by guswynn** [comment]
Ill read more into this!

**Comment by jyn514** [comment]
See also https://github.com/tokio-rs/tracing/issues/975, which has some more discussion.

**Pull request closed without merging**
