### PR TITLE
Add support for custom allocator for `(C)String`

### PR DESCRIPTION
**Pull request by TimDiekmann**
This follows the [roadmap](https://github.com/rust-lang/wg-allocators/issues/7) of the allocator WG to add custom allocators to collections.

currently blocked on:

  - #79499

r? @Amanieu

cc @rust-lang/wg-allocators 
@rustbot modify labels: +A-allocators +T-libs

### CODE REVIEW

**Comment by Amanieu** [comment]
CI seems to be failing.

**Comment by shlevy** [comment]
@TimDiekmann Is there a workaround until this is merged to have owned `str` with a custom allocator?

**Comment by TimDiekmann** [comment]
> @TimDiekmann Is there a workaround until this is merged to have owned `str` with a custom allocator?

No, sorry. You can implement/use a custom `String` class with the same API as a drop-in replacement and provide a `From` implementation for `std::String`, but this is rather an unsatisfactory solution.

**Comment by lachlansneff** [comment]
Any chance this could happen soonish?

**Comment by zachs18** [comment]
@TimDiekmann I made an initial partial re-implementation of this PR (#101551) on the current master branch using the [workaround](https://github.com/rust-lang/rust/issues/79499#issuecomment-1238578527)(?) I mentioned in the blocking issue.
I can close that PR if you'd rather rebase this PR onto current master or something else.

**Comment by TimDiekmann** [comment]
I currently don't have the time to rebase this branch, I'm sorry 🙁
 I'll close this PR in favor of https://github.com/rust-lang/rust/pull/101551

**Pull request closed without merging**
