### PR TITLE
Expand the set of mutual PartialEq and PartialOrd impls for OsStr[ing] and Path[Buf]

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by aturon** [comment]
Thanks for the PR!

@brson, would you mind doing a crater run on this PR? Just want to gauge whether this has any significant inference fallout.

**Comment by alexcrichton** [comment]
Crater reports [zero regressions](https://gist.github.com/alexcrichton/421872a772927e05b424) (a number of unknown ones though)

**Comment by aturon** [comment]
I'm sad this is necessary, but let's do it. Thanks again @gkoz!

@bors: r+

**Pull request merged**
