### PR TITLE
Point to let when modifying field of immutable variable

### LINKED ISSUE #27593: Error message for mutating field of immutable struct could be clearer
``` rust
struct Foo {
    pub v: Vec<String>
}

fn main() {
    let f = Foo { v: Vec::new() };
    f.v.push("cat".to_string());
}
```

The above code gives this compile error:

``` rust
<anon>:8:5: 8:8 error: cannot borrow immutable field `f.v` as mutable
<anon>:8     f.v.push("cat".to_string());
             ^~~
```

From my perspective, this implies that the field somehow needs to be marked as mutable, when in fact the user error is that the struct is immutable.

I believe the error message could be improved by saying something like `cannot borrow field `v` of immutable struct `f` as mutable`.
#18150 is "related".

### PR DESCRIPTION
**Pull request by estebank**
Point at the immutable local variable when trying to modify one of its
fields.

Given a file:

```rust
struct Foo {
    pub v: Vec<String>
}

fn main() {
    let f = Foo { v: Vec::new() };
    f.v.push("cat".to_string());
}
```

present the following output:

```
error: cannot borrow immutable field `f.v` as mutable
 --> file.rs:7:13
  |
6 |    let f = Foo { v: Vec::new() };
  |        - this should be `mut`
7 |    f.v.push("cat".to_string());
  |    ^^^

error: aborting due to previous error
```

Fix #27593.

### CODE REVIEW

**Comment by Emilgardis** [comment]
I think this should read

```
error: cannot borrow immutable field `f.v` as mutable
 --> file.rs:7:13
  |
6 |    let f = Foo { v: Vec::new() };
  |       ^ - consider adding `mut` here
7 |    f.v.push("cat".to_string());
  |    ^^^
```
or 

```
consider changing this to `mut f`
```

**Comment by nagisa** [comment]
@Emilgardis I disagree, because with complex patterns there’s multiple ways to make some binding mutable.

IME it should read simply, without suggesting any specific syntax.

```
6 |    let f = Foo { v: Vec::new() };
  |        - consider making this binding mutable
```

**Comment by nagisa** [comment]
Please also add a test for argument binding.

**Comment by jonathandturner** [comment]
@nagisa 

```
6 |    let f = Foo { v: Vec::new() };
  |        - consider making this binding mutable
```

This is a useful suggestion to more experienced Rust programmers, but one of the nice things about making a suggestion is that the errors can help teach you the language.  By teaching them about the `mut` keyword, they have something they can do to fix the error.  Your suggestion has the unfortunate side effect of saying "go read the manual"

**Comment by jonathandturner** [comment]
```
consider changing this to `mut f`
```

👍

**Comment by estebank** [comment]
> Please also add a test for argument binding.

[We](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-38147-1.stderr) [already](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-38147-2.stderr) [do](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-38147-3.stderr) [that](https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-38147-4.stderr) since #39139, and it isn't affected by this change because here it's [checking wether it is an argument to only add this message if it isn't](https://github.com/rust-lang/rust/pull/40445/files#diff-8c516b1674199747f85038166dd95527R714).

> This is a useful suggestion to more experienced Rust programmers, but one of the nice things about making a suggestion is that the errors can help teach you the language. By teaching them about the mut keyword, they have something they can do to fix the error. Your suggestion has the unfortunate side effect of saying "go read the manual"

I have to agree with these points. I'll change it, as proposed, to

```rust
error: cannot borrow immutable field `f.v` as mutable
 --> file.rs:7:13
  |
6 |    let f = Foo { v: Vec::new() };
  |        - consider changing this to `mut f`
7 |    f.v.push("cat".to_string());
  |    ^^^
```

**Comment by Emilgardis** [comment]
I agree with these changes.

Why did travis fail on only one suite?

**Comment by jonathandturner** [comment]
```
error: cannot borrow immutable field `f.v` as mutable
 --> file.rs:7:13
  |
6 |    let f = Foo { v: Vec::new() };
  |        - consider changing this to `mut f`
7 |    f.v.push("cat".to_string());
  |    ^^^
```

The ^^^ needs a label.

**Comment by estebank** [comment]
@jonathandturner does the following wording make sense?

```rust

error: cannot borrow immutable field `z.x` as mutable
  --> $DIR/issue-39544.rs:21:18
   |
20 |     let z = Z { x: X::Y };
   |         - consider changing this to `mut z`
21 |     let _ = &mut z.x;
   |                  ^^^ cannot borrow mutably field of immutable binding
```

**Comment by jonathandturner** [comment]
Seems close.  How about...

```
error: cannot borrow immutable field `z.x` as mutable
  --> $DIR/issue-39544.rs:21:18
   |
20 |     let z = Z { x: X::Y };
   |         - consider changing this to `mut z`
21 |     let _ = &mut z.x;
   |                  ^^^ cannot mutably borrow immutable field
```

**Comment by estebank** [comment]
@jonathandturner LGTM.

Done.

**Comment by estebank** [comment]
@jonathandturner ping.

**Pull request merged**
