### PR TITLE
std::net: Solaris supports `SOCK_CLOEXEC` as well since 11.4.

### PR DESCRIPTION
**Pull request by devnexen**
try-job: dist-various-2

### CODE REVIEW

**Comment by cuviper** [comment]
Hmm, I don't know if we have any proper target owner for Solaris to make decisions about the minimum version that Rust should support, but it appears Oracle is supporting Solaris 11.3 until January 2027.

https://en.wikipedia.org/wiki/Oracle_Solaris#Version_history

**Comment by cuviper** [comment]
I brought this up on Zulip: https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Solaris.20baseline

@psumbera you were mentioned as a potential target maintainer -- do you have any opinion on this change?

**Comment by psumbera** [comment]
> I brought this up on Zulip: https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Solaris.20baseline
> 
> @psumbera you were mentioned as a potential target maintainer -- do you have any opinion on this change?

Solaris 11.4 should be only relevant Solaris version for Rust. Don't bother with 11.3 version.

I should add myself to https://github.com/rust-lang/rust/tree/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/src/doc/rustc/src/platform-support for Solaris. But I haven't created pull request for that yet.

**Comment by cuviper** [comment]
Let me try to reawaken bors...

**Comment by cuviper** [comment]
We're clear now that the baseline change merged in #133293.

@bors r+ rollup

**Pull request merged**
