### PR TITLE
Provide NonZero_c_* integers

### PR DESCRIPTION
**Pull request by ijackson**
I'm pretty sure I am going want this for #73125 and it seems like an
omission that would be in any case good to remedy.

<strike>Because the raw C types are in `std`, not `core`, to achieve this we
must export the relevant macros from `core` so that `std` can use
them.  That's done with a new `num_internals` perma-unstable feature.

The macros need to take more parameters for the module to get the
types from and feature attributes to use.

I have eyeballed the docs output for core, to check that my changes to
these macros have made no difference to the core docs output.</strike>

### CODE REVIEW

**Comment by thomcc** [comment]
Given that `c_int` isn't a typesafe wrapper around e.g. `i32`, it seems reasonable to just have `std::num::NonZero_c_int` be a type alias for e.g. `NonZeroI32`.

That is, couldn't this just be a bunch of type aliases for the existing NonZero types added to `std::os::raw`?

(Regardless of your personal feelings about the choice for `c_int` to behave this way, it seems better to be consistent, no?)

---

Also, I personally think `NonZeroCInt` would be better a prettier color for the bikeshed than `NonZero_c_int`.

**Comment by ijackson** [comment]
Thom Chiovoloni writes ("Re: [rust-lang/rust] Provide NonZero_c_* integers (#82228)"):
> Given that c_int isn't a typesafe wrapper around e.g. i32, it seems
> reasonable to just have std::num::NonZero_c_int be a type alias for
> e.g. NonZeroI32.

> That is, couldn't this just be a bunch of type aliases for the
> existing NonZero types added to std::os::raw?

Hrm, you make a good point.  I will think about this.

> (Regardless of your personal feelings about the choice for c_int to
> behave this way, it seems better to be consistent, no?)
...
> Also, I personally think NonZeroCInt would be better a prettier color for the
> bikeshed than NonZero_c_int.

Haha :-).  NonZero_c_int has the virtue that grepping for `c_int`
might find it...  I thought it was mor eimportant to be consistent
with std::os::raw than with std::num.  But I can change this if the
general feeling is against me.

Ian.

-- 
Ian Jackson <ijackson@chiark.greenend.org.uk>   These opinions are my own.  

Pronouns: they/he.  If I emailed you from @fyvzl.net or @evade.org.uk,
that is a private address which bypasses my fierce spamfilter.

**Comment by ijackson** [comment]
> That is, couldn't this just be a bunch of type aliases for the existing NonZero types added to `std::os::raw`?

Thanks for the suggestion.  I did this and it came out quite a lot nicer to implement too.

**Comment by KodrAus** [comment]
`NonZeroCInt` is definitely more palatable than `NonZero_c_int`, but I can appreciate the desire to use the latter.

This looks good to me! Thanks for the review @thomcc :bow:

@bors r+

**Pull request merged**
