### PR TITLE
Transition build-manifest to 2018 edition

### PR DESCRIPTION
**Pull request by h-michael**
#58099

### CODE REVIEW

**Comment by h-michael** [comment]
@alexcrichton Thanks for your review.
All of your review is surely for me :)

**Comment by alexcrichton** [comment]
Thanks! Could you be sure to update the dependency in `Cargo.toml` to enable the `derive` feature of the `serde` crate as well?

**Comment by h-michael** [comment]
Updated. Is this what you mean? :)

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
