### PR TITLE
Highlight code in `rustc --explain` (WIP)

### PR DESCRIPTION
**Pull request by estebank**
[Internals thread](https://internals.rust-lang.org/t/syntax-highlighting-in-all-compiler-output/4652).

New output:

colorized code

### CODE REVIEW

**Comment by estebank** [comment]
**Not ready for merging yet**: It doesn't check wether the output can actually support color codes. Piping to other tools will cause control characters to be displayed:

<pre>
$ rustc --explain E0038 > file.txt && more file.txt
(...)
```
ESC[33mtraitESC(BESC[m ESC(BESC[mFooESC(BESC[m ESC(BESC[mESC[33mwhereESC(BESC[m ESC(BESC[mESC[36mSelfESC(BESC[m:ESC(BESC[m ESC(BESC[mSizedESC(BESC[m ESC(BESC[m{ESC(BESC[m

ESC(BESC[m}ESC(BESC[m
ESC(BESC[m```
(...)
</pre>

**Comment by pnkfelix** [comment]
@estebank any status update here? Should I close this PR?

**Comment by estebank** [comment]
@pnkfelix I've been offline for two weeks and haven't had a chance to clean this up for submission (it's lacking detection of pipe vs stdout output). Regardless, could you advice on the changes that were made already, in order to know wether they're in the right track?

**Comment by pnkfelix** [comment]
@estebank I'm not clear on whether we can just add new dependencies to `rustc`; the last time I tried to just throw in some external crates to the `Cargo.toml`, @alexcrichton [told me](https://github.com/rust-lang/rust/pull/39717#issuecomment-278969086) that our vendoring requirements make it difficult to add new crates.

**Comment by estebank** [comment]
@pnkfelix this PR didn't introduce any external crates, it moved existing code into its own crate.

I'll try to get back to this PR this Saturday to clean it up for merging.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

(seems like a nifty addition!)

**Pull request closed without merging**
