### PR TITLE
[WIP] On-demandify region mapping

### PR DESCRIPTION
**Pull request by cramertj**
Attempt at #41057

This approach wound up introducing lots of churn, and I'm opening this primarily as an opportunity to discuss the change and see if there's a more principled way to break up region maps.

In particular, I'd like to see if there's a way to keep `CodeExtent`s unique so that functions with access to only `CodeExtent`s can lookup the associated function. Without this, I'm not sure of the right way to write things like `fmt::Debug for CodeExtent` (in `src/librustc/middle/region.rs`), or the cfg-generating (`src/librustc/cfg/construct.rs`) or error-reporting (`src/librustc/infer/error_reporting/mod.rs`), since they all try to access region maps using only a `CodeExtent`, and doing anything else would require a massive refactor (such as adding a `NodeId` to `note_and_explain_region`).

Thoughts?

r? @nikomatsakis

### CODE REVIEW

**Comment by cramertj** [comment]
One possibility that occurred to me was to change `CodeExtent` from `CodeExtent(u32)` to `CodeExtent(u32, DefId)` where `DefId` is the ID of the top-level function with which it's associated. Thoughts?

**Comment by nikomatsakis** [comment]
@cramertj those are copied around quite frequently, and that would make the data structures *much* larger. I'll try to take tomorrow and form a more educated opinion. Thanks for the PR!

**Comment by leonardo-m** [comment]
Can't you use something like this to reduce the amount of manual refactoring? http://coccinelle.lip6.fr/

**Comment by nikomatsakis** [comment]
@leonardo-m plausibly, if it worked on rust, but I think that what @cramertj and I have been talking about is really more what we want the target code to look like, rather than the churn it takes to get there. That said, I've been doing a lot of refactoring on this PR on a side branch, and I think I'm going to close it for now (I've discussed with @cramertj off line), until I reach some point I am happy with.

**Pull request closed without merging**
