### PR TITLE
Added "copy" to Debug fmt for copy operands

### PR DESCRIPTION
**Pull request by RayMuir**
In MIR's debug mode (--emit mir) the printing for Operands is slightly inconsistent. 

The RValues - values on the right side of an Assign - are usually printed with their Operand when they are Places.

Example:
_2 = move _3

But for arguments, the operand is omitted.

_2 = _1

I propose a change be made, to display the place with the operand.

_2 = copy _1

Move and copy have different semantics, meaning this difference is important and helpful to the user. It also adds consistency to the pretty printing.

-- EDIT --

 Consider this example Rust program and its MIR output with the **updated pretty printer.**

This was generated with the arguments --emit mir --crate-type lib -Zmir-opt-level=0 (Otherwise, it's optimised away since it's a junk program).

```rust
fn main(foo: i32) {
    let v = 10;

    if v == 20 {
        foo;
    }
    else {
        v;
    }
}
```

```MIR
// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main(_1: i32) -> () {
    debug foo => _1;
    let mut _0: ();
    let _2: i32;
    let mut _3: bool;
    let mut _4: i32;
    let _5: i32;
    let _6: i32;
    scope 1 {
        debug v => _2;
    }

    bb0: {
        StorageLive(_2);
        _2 = const 10_i32;
        StorageLive(_3);
        StorageLive(_4);
        _4 = copy _2;
        _3 = Eq(move _4, const 20_i32);
        switchInt(move _3) -> [0: bb2, otherwise: bb1];
    }

    bb1: {
        StorageDead(_4);
        StorageLive(_5);
        _5 = copy _1;
        StorageDead(_5);
        _0 = const ();
        goto -> bb3;
    }

    bb2: {
        StorageDead(_4);
        StorageLive(_6);
        _6 = copy _2;
        StorageDead(_6);
        _0 = const ();
        goto -> bb3;
    }

    bb3: {
        StorageDead(_3);
        StorageDead(_2);
        return;
    }
}
```

In this example program, we can see that when we move a place, it is preceded by "move". e.g. ``` _3 = Eq(move _4, const 20_i32);```. However, when we copy a place such as ```_5 = _1;```, it is not preceded by the operand in the original printout. I propose to change the print to include the copy ```_5 = copy _1``` as in this example.

Regarding the arguments part. When I originally submitted this PR, I was under the impression this only affected the print for arguments to a function, but actually, it affects anything that uses a copy. This is preferable anyway with regard to consistency. The PR is about making ```copy``` explicit.

### CODE REVIEW

**Comment by pnkfelix** [comment]
I'm not sure this adds any actual value; the people who are reading the MIR output probably are already well aware of the semantics here?

But maybe making the pretty-printing line up has value. I certainly have valued assembly languages that chose the same number of letters in their opcodes (or at least a small upper bound to their lengh) for this exact reason.

Who are the people who would care most about whether or not to make this change? The people in @rust-lang/wg-mir-opt ?

**Comment by pnkfelix** [comment]
I'm going to reassign this to @oli-obk for now because I think they are in a better position to make a call about the value of  a change like this.

r? @oli-obk

**Comment by compiler-errors** [comment]
@pnkfelix:

> I'm not sure this adds any actual value; the people who are reading the MIR output probably are already well aware of the semantics here?

I think this adds value.

MIR is read by both MIR experts and non-expert users, and unless a non-experts reads the rustc pretty-printing code, or they reason by elimination, or someone teaches them that non-marked operands are always `copy`, I don't see how one transitions from "not knowing this" to "knowing this".

If anything, *not* marking the `move` operands and *always* marking `copy` operands seems more obvious, but why do we care about brevity here?

**Comment by oli-obk** [comment]
I'm moderately in favor of this. I think even tho it's obvious to me I'dve benefited from it when the difference was especially important.

let's leave this open for a week to let other @rust-lang/wg-mir-opt folk chime in. If there are no explanations of why we should keep the status quo or do something else entirely in that week, let's bless everything and land it.

**Comment by DianQK** [comment]
LGTM. But do we also need to update `custom_mir`?

**Comment by apiraino** [comment]
@RayMuir cc for this [comment](https://github.com/rust-lang/rust/pull/122551#issuecomment-2003407361). Apart from that are we good for merging this? 

thanks

@rustbot author

**Comment by RayMuir** [comment]
> LGTM. But do we also need to update `custom_mir`?

That may need looking into as I don't know off the top of my head.

**Comment by apiraino** [comment]
cc @DianQK @RalfJung thanks :-)

@rustbot review

**Comment by RalfJung** [comment]
I am confused by the PR description.

> But for arguments, the operand is omitted.

What "arguments"? Do you mean function arguments? But then the rest of the text seems to apply to all uses of `Operand`, not just (function) arguments. So not sure what is actually being proposed here.

**Comment by RalfJung** [comment]
It would be good if you could run `./x.py test mir-opt --bless` and add that to the PR, so that one can have an idea for what effect this PR will have.

**Comment by DianQK** [comment]
> > LGTM. But do we also need to update `custom_mir`?
> 
> That may need looking into as I don't know off the top of my head.
> 
> Is there anything more I'm required to do before this is accepted (this is my first pull request).

For me, just bless all the test cases. We don't often use `custom_mir`. It's not very important.

**Comment by RayMuir** [comment]
> I am confused by the PR description.
> 
> > But for arguments, the operand is omitted.
> 
> What "arguments"? Do you mean function arguments? But then the rest of the text seems to apply to all uses of `Operand`, not just (function) arguments. And the example does not involve an argument as far as I can see. What do "arguments" have to do with copy vs move anyway?
> 
> So not sure what is actually being proposed here. It seems to just be about making `copy` explicit rather than implicit, but the description seems to talk about something completely different.

Apologies, hopefully this makes the PR a little clearer. Consider this example Rust program and its MIR output with the **updated pretty printer.**

This was generated with the arguments --emit mir --crate-type lib -Zmir-opt-level=0 (Otherwise it's optimised away since it's a junk program).

```rust
fn main(foo: i32) {
    let v = 10;

    if v == 20 {
        foo;
    }
    else {
        v;
    }
}
```

```MIR
// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main(_1: i32) -> () {
    debug foo => _1;
    let mut _0: ();
    let _2: i32;
    let mut _3: bool;
    let mut _4: i32;
    let _5: i32;
    let _6: i32;
    scope 1 {
        debug v => _2;
    }

    bb0: {
        StorageLive(_2);
        _2 = const 10_i32;
        StorageLive(_3);
        StorageLive(_4);
        _4 = copy _2;
        _3 = Eq(move _4, const 20_i32);
        switchInt(move _3) -> [0: bb2, otherwise: bb1];
    }

    bb1: {
        StorageDead(_4);
        StorageLive(_5);
        _5 = copy _1;
        StorageDead(_5);
        _0 = const ();
        goto -> bb3;
    }

    bb2: {
        StorageDead(_4);
        StorageLive(_6);
        _6 = copy _2;
        StorageDead(_6);
        _0 = const ();
        goto -> bb3;
    }

    bb3: {
        StorageDead(_3);
        StorageDead(_2);
        return;
    }
}
```


In this example program, we can see that when we move a place, it is preceded by "move". e.g. ``` _3 = Eq(move _4, const 20_i32);```. However, when we copy a place such as ```_5 = _1;```, it is not preceded by the operand in the original printout. I propose to change the print to include the copy ```_5 = copy _1``` as in this example.

Regarding the arguments part. When I originally submitted this PR, I was under the impression this only affected the print for arguments to a function, but actually, it affects anything that uses a copy. This is preferable anyway with regard to consistency. The PR is about making ```copy``` explicit. 

Hope this clears the PR up.

**Comment by RayMuir** [comment]
> It would be good if you could run `./x.py test mir-opt --bless` and add that to the PR, so that one can have an idea for what effect this PR will have.

I ran the test and have attached it as the output was quite long.
[out.txt](https://github.com/user-attachments/files/16602184/out.txt)

**Comment by RalfJung** [comment]
The interesting part of a `--bless` run is not the output, it's what it does to the files. :) Please `git commit tests -m "bless tests"` after the command finishes, and push that to this branch -- then the PR will contain a diff of how your PR changes MIR printing.

**Comment by RalfJung** [comment]
> Regarding the arguments part. When I originally submitted this PR, I was under the impression this only affected the print for arguments to a function, but actually, it affects anything that uses a copy. This is preferable anyway with regard to consistency. The PR is about making copy explicit.

That helps, thanks. :) Please update the PR description so that it reflects your current understanding and the current status of the PR.

**Comment by oli-obk** [comment]
r? mir-opt

**Comment by saethlin** [comment]
This seems fine to me and it sounds like based on the thread like others agree.

I'll see what I can do to get this merged as soon as it's in a mergeable state. @RayMuir you've chosen a uniquely challenging first PR. What I'd suggest is you destroy the bless commit, rebase the commit that actually modifies the compiler onto the latest commit on rust-lang/rust's master branch, then re-bless from there.

If you are not already familiar with rebase workflows, I'm sorry. Here's what I would do to accomplish what I suggested above:
Run `git rebase -i HEAD~1`. This is an interactive rebase over the pointer 2 commits behind. This should pull up an editor with 2 commits mentioned at the top. Change the `pick` next to your `bless tests` commit to a `drop`. Write out that file then `git rebase` should take over and delete the bless commit. To rebase the new state of your branch over upstream's master, run `git pull --rebase git@github.com:rust-lang/rust`. This is by far the least error-prone way to rebase up your PR. That should go through cleanly. Then re-bless, which should also go through cleanly, and force-push that.

**Comment by saethlin** [comment]
A different commit would be good enough for me, I would think a separate PR would be impossible to land because tests will break.

**Comment by saethlin** [comment]
I approve of the contents of the commits, though I'd expect some conversation with the first-time contributor before taking over their PR.

**Comment by RayMuir** [comment]
> I approve of the contents of the commits, though I'd expect some conversation with the first-time contributor before taking over their PR.

Thanks for the detailed explanation of the process above, it was very helpful. It's certainly a bit more advanced than I'm used to, but I have some colleagues who are a bit more experienced with Git and its processes, which is lucky. I think from the PR's history that someone has done what was asked? If so, then great. Otherwise, let me know and I'll do the bit that was originally asked. Thanks for the patience!

**Comment by saethlin** [comment]
> If so, then great.

So shall it be!

@bors r+ rollup=never p=1

**Pull request merged**
