### PR TITLE
Extend dead code lint to detect more unused enum variants, rebased

### LINKED ISSUE #25960: CastError::RefToMutPtr is never constructed
`CastError::RefToMutPtr` in `src/librustc_typeck/check/cast.rs` is never constructed.

cc @arielb1

### PR DESCRIPTION
**Pull request by sanxiyn**
Rebase of #21468.

Fix #25960.

### CODE REVIEW

**Comment by huonw** [comment]
Could you add a test like:

```rust
enum Foo { A, B }

fn bar() -> Foo {
    match Foo::A {
        Foo::A | Foo::B => Foo::B
    }
}
```

That is, ensuring that alternation doesn't get cause variants to count as unused.

**Comment by sanxiyn** [comment]
Added a test.

**Comment by sanxiyn** [comment]
Ping?

**Comment by sanxiyn** [comment]
Another ping.

**Comment by huonw** [comment]
@bors r+

sorry for the delay

**Comment by sanxiyn** [comment]
Failed in pretty. Fixed.

**Pull request merged**
