### PR TITLE
Store a Symbol in InternedString

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Zoxc** [comment]
@Mark-Simulacrum I'd like a perf run on this

**Comment by Mark-Simulacrum** [comment]
Perf run queued.

**Comment by alexcrichton** [comment]
ping @Mark-Simulacrum, do we have perf results now perchance?

**Comment by pnkfelix** [comment]
(Also, Note that @jseyfried has not yet weighed in on whether they want these changes.)

**Comment by Mark-Simulacrum** [comment]
http://perf.rust-lang.org/compare.html?start=6c06bfaebad19abc73506e730e97b03291ecf187&end=8c522672d3f1dab4c6af8a0bd3cf8c731c5f9c8e&stat=instructions%3Au

**Comment by carols10cents** [comment]
review ping @jseyfried ! pinging you on IRC too!

**Comment by kennytm** [comment]
Review ping for you @jseyfried! Also cc @rust-lang/compiler.

**Comment by nikomatsakis** [comment]
Can somebody summarize (a) what is being done here so I don't have to read the diffs and (b) why I should care?

**Comment by eddyb** [comment]
@nikomatsakis This is reverting an API change @jseyfried (I believe) did.
Right now we can deref `InternedString` to `str` (sound because `InternedString` is not `Send`/`Sync`).
@Zoxc moves us backwards to an `with_str` style API with this PR (which makes `InternedString` largely redundant with `Symbol` - IMO `InternedString` should be `SymbolContents` anyway).

**Comment by petrochenkov** [comment]
What's the point of `InternedString` as a separate type if it's equivalent to `Symbol` now?

So far I didn't look carefully at @Zoxc's multithreading-related PRs and mostly seen them as something quite unfortunate, but maybe necessary after all.
Could someone write a design summary about how `Symbol`s are supposed to be organized in multithreaded rustc?
Is there going to be a global interner? Or many thread-local interners with string duplication? Or both?

**Comment by Zoxc** [comment]
> What's the point of InternedString as a separate type if it's equivalent to Symbol now?

It has `Ord` and `Hash` implementations based on strings instead of an unstable integer like `Symbol`.



> Is there going to be a global interner? Or many thread-local interners with string duplication? Or both?

My branch has a interner per compilation session which is behind a lock. There is no parallelism during parsing there though, so all symbols are identical to what happens on `master`.

**Comment by michaelwoerister** [comment]
This seems to be slowing things down quite a bit (as per the perf run above). Is this a soundness fix? Is there an alternative implementation that allows us to keep using direct string references?

**Comment by eddyb** [comment]
I believe we can just require that the interner outlives the threads that use it.

**Comment by eddyb** [comment]
@Zoxc I mean you already have the threads, you just have to own the interner outside of them.

**Comment by nikomatsakis** [comment]
>  We should instead pre-intern these constant strings using a macro. This avoids the string allocation and the string comparisons.

It seems pretty important to resolve this, no?

**Pull request closed without merging**
