### PR TITLE
[beta] Stabilize unions with `Copy` fields and no destructor

### PR DESCRIPTION
**Pull request by brson**
- https://github.com/rust-lang/rust/pull/42068

r? @aturon 

cc @petrochenkov

### CODE REVIEW

**Comment by brson** [comment]
Testing locally while we try to land via bors.

**Comment by petrochenkov** [comment]
@brson @aturon 
You may want to backport https://github.com/rust-lang/rust/pull/42083 as well, they were supposed to land together.

**Comment by petrochenkov** [comment]
I've submitted https://github.com/rust-lang/rust/pull/42328 including https://github.com/rust-lang/rust/pull/42083 and fixing discrepancies between beta and nightly causing the Travis failure.

**Comment by brson** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/42328

**Pull request closed without merging**
