### PR TITLE
Remove standard io chapter from the book

### LINKED ISSUE #23760: Book: Standard Input is out-of-date
http://doc.rust-lang.org/book/standard-input.html

When running  the old I/O Standard library, I get an error that the compiler won't admit.

Example:
```rust
use std::old_io; // error: use of unstable library feature 'old_io'
                 // warning: use of deprecated item, #[warn(deprecated)] on by default
fn main() {
    println!("Type something!");

    let input = old_io::stdin().read_line().ok().expect("Failed to read line"); // error: use of unstable library feature 'old_io'
                                                                                // error: use of unstable library feature 'old_io'
                                                                                // warning: use of deprecated item, #[warn(deprecated)] on by default
                                                                                // warning: use of deprecated item, #[warn(deprecated)] on by default
    println!("{}", input);

}
```

### PR DESCRIPTION
**Pull request by steveklabnik**
This was originally used to set up the guessing game, but that no longer
exists. This version uses `old_io`, and updating it involves talking
about `&mut` and such, which we haven't covered yet. So, for now, let's
just remove it.

Fixes #23760

### CODE REVIEW

**Comment by alexcrichton** [comment]
Shouldn't this also modify SUMMARY.md?

**Comment by alexcrichton** [comment]
Other than that though r=me

**Comment by KingOfThePirates** [comment]
Maybe having a "!This chapter will be revised to be less confusing" message at the top is better than no chapter at all?

As someone who is learning programming for the first time, I vote to reopen #23800. I would rather not know what that special mut code means or does, if it means I can use *some* code to use databases *now* in my games. Not being able to save accounts, characters, inventories, and game progress in the little, text-based games you make at this stage of programming is very frustrating. Yahoo answers solutions are 100x more confusing.

I think it is much better to learn a language as you make a program over and over again with new computer science topics and language idioms you learn.

Not being able to save data takes away all but tic-tac-toe.. not cool.

**Comment by steveklabnik** [comment]
> But when do we learn how to read and write files?

Because this is being removed in the moment doesn't mean that it's gone forever. It just doesn't fit currently. Also, I'm working on docs for IO in general, so this will be in the API docs as well.

**Comment by KingOfThePirates** [comment]
Do you think you could provide us noobies, even if just here, for a copy and paste that reads a plain text file and stores each line as a different variable?

Example plain text file: | Example variables:
---------------------------- | -------------------------
`Gold Roger` | `character_name`
`12` | `character_level`
`Warrior` | `character_job`
`177 0` | `character_health character_mana`

This may help write the docs for IO, too.

**Comment by KingOfThePirates** [comment]
Do you think you could provide us noobies, even if just here, for a copy and paste that reads a plain text file and stores each line as a different variable?

Example plain text file: | Example variables:
---------------------------- | -------------------------
`Gold Roger` | `character_name`
`12` | `character_level`
`Warrior` | `character_job`
`177 0` | `character_health character_mana`

This may help write the docs for IO, too.

**Pull request merged**
