### PR TITLE
Use the raw API in queries to avoid hashing the query key 3 times

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I like the idea! I wonder if we can create a reusable extension of `HashMap` to encapsulate this. Something that makes sure that we always have the same hasher, like (I did not actually test this): 
```
struct KeyWithCachedHash<K, H: Hasher> {
    hash: u64,
    key: K
}

trait HashMapCacheExt<K, V, H> {
    fn inner_mut(&mut self) -> &mut HashMap<K, V, H>;

    fn insert_cached(&mut self, key: KeyWithCachedHash<T, H>, value: V) -> Option<V> {
        self.inner()..raw_entry_mut().from_key_hashed_nocheck(key.hash, key.key).insert(value)
    }
}
```

**Comment by Zoxc** [comment]
@rust-timer build 7f4cdd3e6e208b6fb22ea43ad8bccc98301c9953

**Comment by Zoxc** [comment]
That doesn't look faster. I wonder if the raw API is slower or something :/

**Comment by michaelwoerister** [comment]
Yeah, the perf comparison looks like noise. `ctfe-stress` and `packed-simd` are rather flaky, I think.

My guess is that query key hashing is not very expensive to begin with. It uses `FxHasher` and keys are hashed shallowly (e.g. we just hash a pointer for `Ty`). For `StableHash` it would look different but we don't use stable hashes for with hash maps.

**Pull request closed without merging**
