### PR TITLE
Prepare Rust 1.80.1 point release

### PR DESCRIPTION
**Pull request by emilyalbini**
The point release is scheduled to include:

* https://github.com/rust-lang/rust/pull/128271
* https://github.com/rust-lang/rust/pull/128618

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors retry

Spurious failure.

**Comment by ysndr** [comment]
https://github.com/rust-lang/rust/releases/latest is still pointing to 1.80.0. Do you plan to make a Github Release for 1.80.1 as well?

**Pull request merged**
