### PR TITLE
Revert #132772 to fix unknown git commit hash

### PR DESCRIPTION
**Pull request by jieyouxu**
Reverts #132772 to address #132845, we seem to have unintentionally omitted commit hash.

r? @onur-ozkan

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r+ p=10
(I'm not on the team, but this is just a revert, and we want to land it ASAP so it does not become part of the next nightly)

**Comment by jieyouxu** [comment]
Since queue is very light, I'm going to yield the other PR that just started.

@bors rollup=never

**Comment by jieyouxu** [comment]
> I'm not on the team, but this is just a revert, and we want to land it ASAP so it does not become part of the next nightly

(I was going to self-approve as per revert policy but was double-checking queue, this works too 😆)

**Comment by jieyouxu** [comment]
Huh

**Comment by jieyouxu** [comment]
I'll babysit this revert to make sure it goes through. Closing the tree temporarily to not have to keep yielding other PRs.

@bors p=50
@bors treeclosed=1000

**Comment by jieyouxu** [comment]
PR to re-enable `version-verbose-commit-hash` after this revert PR lands: https://github.com/rust-lang/rust/pull/132846

**Comment by RalfJung** [comment]
The 2nd commit here can be reverted once https://github.com/rust-lang/rust/pull/132852 landed.

**Pull request merged**
