### PR TITLE
Reintroduce deprecated `collections` crate

### PR DESCRIPTION
**Pull request by murarth**

### CODE REVIEW

**Comment by murarth** [comment]
r? @alexcrichton 

cc #42648

**Comment by murarth** [comment]
I added `collections` as a dependency to `libstd` without declaring `extern crate collections;` anywhere. It seemed to be the only way to get `x.py` to build `libcollections`.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by murarth** [comment]
Broken links strike again.

**Comment by murarth** [comment]
Ah, it was because I forgot to re-export collections macros from `alloc`. Good thing that was caught somewhere.

**Pull request merged**
