### PR TITLE
Require `#[must_use]` on `Diagnostic` structs to prevent future bugs

### PR DESCRIPTION
**Pull request by Enselic**
This will prevent bugs like https://github.com/rust-lang/rust/issues/118972 at compile time.

Also see https://github.com/rust-lang/rust/pull/118973 where this was originally discussed.

This PR handles
* `Diagnostic` structs 

We should also begin to require `#[must_use]` on

* `Diagnostic` enums
* `Subdiagnostic` structs
* `Subdiagnostic` enums

but let's wait with that until we know we want this at all.

r? @michaelwoerister (who maybe want to delegate this to someone else)

cc @rust-lang/wg-diagnostics 

Note: Review this PR commit-by-commit since one of the commits is repetitive but big...

## Alternatives

We could maybe turn the `Diagnostic` derive macro into an attribute macro so that it can add `#[must_use]` automatically behind the scenes. But I am personally not against the clarity of an explicit `#[must_use]` attribute.

### CODE REVIEW

**Comment by estebank** [comment]
@michaelwoerister lets go for it.

**Comment by nnethercote** [comment]
Requiring a mandatory line of boilerplate on 1,300+ structs seems suboptimal to me :(

**Comment by compiler-errors** [comment]
I agree with @nnethercote. I don't think that this is maintainable, tbh, and it seems like it will immediately begin regressing as people add more derive structs without the attr.

**Comment by michaelwoerister** [comment]
One alternative would be to turn the derive macro into an attribute macro and make that add `#[must_use]`.

**Comment by michaelwoerister** [comment]
> I don't think that this is maintainable

I don't quite agree on the maintainability aspect, by the way. As far as I can tell, one would only come into contact with this when adding a new diagnostic struct and the error message gives a simple instruction on what to do. I think the approach is acceptable.

But yes, requiring the user to add boilerplate code is indeed not exactly optimal 🙂

**Comment by Enselic** [comment]
> One alternative would be to turn the derive macro into an attribute macro and make that add `#[must_use]`.

Let's explore that idea a bit more. It is not clear to me exactly how we would achieve this. Let's take this struct as an example:

```rs
#[derive(Diagnostic, Clone, Copy)]
#[diag(ast_lowering_underscore_expr_lhs_assign)]
pub struct UnderscoreExprLhsAssign {
    #[primary_span]
    #[label]
    pub span: Span,
}
```

what would this struct definition look like with the attribute macro approach?

**Comment by estebank** [comment]
@Enselic I believe that derive macros can't add annotations to the annotated item, only expand to new items, while proc macro attributes can fully rewrite the item they are applied to, including adding new attributes.

**Comment by Enselic** [comment]
I might explore the proc macro attribute approach later.

Since this PR is not actionable before someone has explored the proc macro attribute approach, I will close this PR for now.

I would like to thank everyone who provided feedback so far 👍

**Comment by michaelwoerister** [comment]
The attribute macro approach should be rather similar. The main difference is that [attribute macros](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros) will expect that the item given in the input token stream will be re-emitted (possibly modified) along with any additional items (e.g. "derived" impls). 

Then the example above would look like:
```
#[diag(ast_lowering_underscore_expr_lhs_assign)]
#[derive(Clone, Copy)] // `Diagnostic` is removed, this is handled by `#[diag]` now
pub struct UnderscoreExprLhsAssign {
    #[primary_span]
    #[label]
    pub span: Span,
}
```

The macro (now `#[diag]`) would still get the same token stream as input and would still have more or less the same token stream as output, just with input token stream (+ `#[must_use]`) prepended.

**Comment by michaelwoerister** [comment]
In the example above, I moved the `#[diag]` attribute above the `#[derive]`. This way, derive should already see the modified version of the struct (although it should not make a difference in this case).

**Pull request closed without merging**
