### PR TITLE
Generalize Coverage Expression simplification

### PR DESCRIPTION
**Pull request by Swatinem**
This extends the current simplification code to not only replace operands by `Zero`, but also to remove trivial `Counter + Zero` expressions and replace those with just `Counter`.

Currently this simplification is very simplistic, and does not handle more complex nested expressions such as `(A + B) - B` which could in theory be simplified as well.

This is based on top of https://github.com/rust-lang/rust/pull/114399 CC @Zalathar

### CODE REVIEW

**Comment by Zalathar** [comment]
@rustbot blocked

(This is written on top of #114399, so it can't land until that PR lands.)

**Comment by Zalathar** [comment]
I think we shouldn't add more simplifications right now, for a few reasons:

- Simpler mappings are nice to have, but they aren't essential; coverage works fine even if the mappings are unnecessarily complex. So if simplification interferes with other priorities, then those should take precedence.
- My goal behind #114399 is to work towards being able to make big changes to how coverage info is stored in MIR. To make that happen, all of the related code needs to be as simple as possible, so that it's feasible for me to make the necessary changes in one go. Adding more simplification code right now would get in the way of that.
- A lot of the unnecessary complexity in mappings comes from the instrumentor deliberately adding `(x + 0)` expressions instead of using the same counter/expression twice. That's currently necessary (due to other design decisions in the original coverage implementation), and I'd like to fix that at the source rather than papering over it in codegen.
- Aside from the above, many of the opportunities for simplification come from the fact that MIR optimizations can remove `CoverageKind::Expression` nodes. When I eventually move most of the coverage data out of MIR statements and into a per-function structure, the simplification steps will need to work differently, so putting effort into them now will end up being a bit of a waste.

I did add some simplification code in 114399, but that was only so that I could remove expression renumbering without making the mappings *worse* (because the renumbering code also performed a couple of simplifications of its own).

**Comment by Swatinem** [comment]
Other work on the coverage mappings have made this unnecessary

**Pull request closed without merging**
