### PR TITLE
Issue 20529: Tuple docs update

### PR DESCRIPTION
**Pull request by andrewyli**
Docs in `tuple.rs` edited.

Edit: for some reason commits from something else found their way into here.

### CODE REVIEW

**Comment by cmr** [comment]
@EchoAce can you remove the other commits?

**Comment by EchoAce** [comment]
I think it's all good now.

**Comment by aturon** [comment]
I agree with @cmr, this looks good modulo providing full examples.

**Comment by EchoAce** [comment]
Examples added!

**Pull request merged**
