### PR TITLE
Move error::Error from libstd to liballoc

### LINKED ISSUE #62502: Consider moving std::error::Error to `alloc`
Now that `alloc` is stable, this is a somewhat visible omission from `no_std` contexts.

In practice, it being in `std` means that library crates that would otherwise be `no_std` (+ `alloc`) compatible which expose some sort of error type have to either:
1. Skip implementing `std::error::Error` for their error type, giving up error ergonomics for users regardless of whether or not they care about no_std
2. Hide the implementation of `std::error::Error` behind a feature, which is awkward.
    - And if you already have `alloc` behind a feature, now you end up with separate `alloc` and `std` features (which is the option I took [in one of my crates](https://github.com/thomcc/rust-base16/tree/a5321823aa9361279d12ee460aa99ca1a4e62ddf#no_std-usage), and is mostly why I'm filing this) but is tedious, and makes your library have a larger configuration surface than feels necessary.
3. Ignore no_std completely (what most crates do and will probably continue to do).

Bummers, all of them.

If Error is moved to `alloc`, while not *ideal* <sup>[1]</sup>, it would make things easier for the relatively common case of library crates that could otherwise be `no_std` + `alloc`, but don't want to give up error handling ergonomics.

---

<b>[1]</b>: I think having `Error` in `core` makes more sense, but IIUC it can't: https://github.com/rust-lang/rust/pull/33149 (my read of this, which is probably wrong in some way, is that it's more or less because `Error::downcast` needs to be able to return a `Box<T>`)

As far as I know nothing prevents it from being in `alloc` (since Box is present in `alloc`), but I could easily be missing something important.

anyway thx for coming to my ted talk

### PR DESCRIPTION
**Pull request by taiki-e**
This moves `Error` trait from `libstd` to `liballoc`. ~~When importing `Error` trait from `liballoc`, it is necessary to enable an unstable feature (As I referred to #51846, I’m making this unstable, but is it actually unnecessary?).~~

Unlike #51846, this is just moving the trait, so I don't think RFC is needed, but I'm not sure how this will affect #53487 (backtrace). cc @alexcrichton 

Closes #62502

r? @SimonSapin

### CODE REVIEW

**Comment by SimonSapin** [comment]
@rust-lang/libs, any thoughts on this?

**Comment by BurntSushi** [comment]
It's there any reason not too do this? It otherwise seems like a big win. (And ideally, Error would be in core too, although it sounds like the downcast API makes that tricky I guess?)

**Comment by SimonSapin** [comment]
There’s a code comment about impl coherence not allowing the trait to be in libcore:

https://github.com/rust-lang/rust/blob/19a38de68a8de14fe49e96b315db026bd57b9696/src/libstd/error.rs#L5-L14

Having it in liballoc sounds ok to me. Maybe even doing FCP to stabilize the new location in this PR, if other team members are ok with that.

**Comment by taiki-e** [comment]
(I think it would be preferable if it could be stabilized in this PR, so I reverted the commit on unstable attributes.)

**Comment by withoutboats** [comment]
RFC 2504, which hasn't been fully implemented, intends to expose a `Backtrace` type in std, and a `fn backtrace(&self) -> Option<&Backtrace>` method on the `Error` trait. Moving `Error` to alloc would require exposing backtrace from alloc; I don't know if that's possible and desirable or not, but it needs to be considered.

**Comment by SimonSapin** [comment]
Thank you @taiki-e for the PR. I will close it now as it unfortunately appears to be incompatible with [RFC 2504](https://rust-lang.github.io/rfcs/2504-fix-error.html) which is already accepted (even if not implemented yet).

I’m not sure whether backtrace functionality qualifies for libcore/liballoc (that is, can it always be available everywhere Rust can run, without a dependency on the environment or operating system). But even if it does, the RFC currently specifies a behavior that relies on an environment variable and `std::env` is not available without libstd.

Maybe we could decide to have a `Backtrace` *type* always be present but only sometimes providing useful functionality (possibly when libstd is linked?). However I feel such a proposal should go through the RFC process to amend RFC 2504.

**Comment by withoutboats** [comment]
> Maybe we could decide to have a Backtrace type always be present but only sometimes providing useful functionality (possibly when libstd is linked?). However I feel such a proposal should go through the RFC process to amend RFC 2504.

Hard to remember 2 years later, but I believe this is what I did to make `failure` no_std - the backtrace type in failure is always present, but is a ZST if not compiled with the backtrace feature (which depends on std).

However, I think the best solution is to move to a feature-based architecture so that traits in core can have methods added in std, because core/alloc/std are all the same crate under different feature flags. But that's a big project.

**Comment by cbeck88** [comment]
it's really sad that error is messed up in this way and cannot be in `core`

There's a proposal in C++ right now from last year, the famous "Herbceptions" paper: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0709r0.pdf

The author laments that there is no one good way to signal errors in C++ that is acceptable in all cases. The language is built around exceptions, but in many / most embedded applications exceptions aren't suitable. So they point out that this has caused fragmentation in the language. Lots of libraries expose both throwing and non-throwing APIs, even the standard library, in order to make things usable by everyone. This is considered a tragic flaw and they propose massive changes to fix it.

In Rust, I would argue, a similar thing is happening with `std::error::Error`. Because it cannot be in `core`, even in `liballoc` after closing of this issue, we are going to see that libraries can't use it without creating portability headaches. And so the rust ecosystem will split into "embedded friendly" projects that use `std::error` and unfriendly ones that don't. And any use of `std::error` that is "essential" to the effective use of the library, will have to be duplicated. As a library author, why would I use `std::error` in any essential way then, if I know it will cause a portability problem? And if it's not essential why bother? Why not just use `failure` crate instead?

I've watched with sadness as making `std::error::Error` more portable is repeatedly identified as a good idea and then every possible way of doing it is closed.

This (eventually closed) PR described making `std::error::Error` a `#[fundamental]` trait so that it could be in `core` and still get trait impls later.
https://github.com/rust-lang/rust/pull/33149

This old issue described someone trying to use Jethro's `core_io` crate and struggling with the lack of `core_error`: https://github.com/jethrogb/rust-core_io/issues/3

This plan from 2017 to refactor and create `core::io` seems to have mostly stalled, without getting to `core::error`: https://github.com/rust-lang/rfcs/issues/2262

This code comment is frequently referred to: https://github.com/rust-lang/rust/blob/19a38de68a8de14fe49e96b315db026bd57b9696/src/libstd/error.rs#L5-L14
But it is very difficult to understand -- if `Error` is moved to `core`, along with `&str`, that seems to make it easier for other things to know that `&str: !Error`, not harder,
since they are lower down in the hierarchy. Right?

This recent RFC suggests that `failure` also should rely on `error` and then not be portable either :(
https://github.com/rust-lang/rfcs/blob/master/text/2504-fix-error.md#how-this-impacts-failure

And now at a moment when we could have moved `Error` to alloc, we decided that it was more interesting and important to integrate backtrace functionality that reads an environment variable into `Error`.

One thought that occurs to me: `libbacktrace` is already, before this recent RFC, used essentially to perform stack unwinding in the implementation of `catch_unwind`, in the `panic=unwind` configuration. To accomplish this, lang items and extern symbols are used, deep in libstd. Why can't we use the same sorts of mechanisms to dispatch calls to `Backtrace` objects -- when they would collect a backtrace, they call an extern symbol, and in `libstd` this is provided and does the environment variable / non-portable stuff, but in `no_std` projects this can symbol can be provided differently.

It makes me really sad that there's no clear way to make progress on this. The fact that `Error` trait is `std`-only is the *only* real reason that crates like `serde` must have `std` and `alloc` flags right now, afaict, and the source of a *lot* of the pain in `no_std` development, if you try to use a serialization lib with `serde`, which is the de-facto standard.

The fact is that using `std` and `alloc` flags to indicate "modes" is not a panacea -- it's often a hack, and results in features are not actually additive and this causes cargo to break the bulid.
For example, if I try to use crates like both `rmp` and `rmp-serde` in the same project, you must configure `rmp` and `rmp-serde` in exactly the same way, having `std` and not `alloc`, or `alloc` and not `std`, or it breaks.
This is because `serde` represents its errors using a trait, and in `std` mode the `std::error::Error` trait bound is added (seemingly reasonably). But if you think about it, this is not an "additive" use of features.
Making the trait bound *stricter* when a feature is turned on is not additive, it means that code that would have built against your library will stop building once your feature comes on. If it cannot bring `std::error::Error` into scope
then there may be no way for it to do that.
So there is no way for `rmp-serde` to build in `alloc` mode if `serde` is built with `std` mode. These are really distinct modes, and not additive features. Meanwhile cargo assumes that build-plan wide feature unification is always sound.
This is an enormous source of pain for embedded development, especially when you build `no_std` code but your `build.rs` scripts rely on `serde/std` for instance. And a large measure of this pain would simply go away if `std::error::Error` were portable,
as this would give `serde` an out when it builds in `alloc` mode.

Giving up on making `std::error::Error` portable means giving up on a *lot* of the possible progress in making rust ecosystem more portable and embedded-friendly, which has supposedly been a major development goal for the last year and a half.

What would you think about a more serious measure like standardizing parts of `failure` crate and putting `Failure` trait in `core`, and deprecating `std::error::Error` entirely?
It sounds drastic and would cause short term pain. But OTOH, there is no high-level reason that `Error` cannot be in core, so this is all accidental complexity.

Moreover it seems that almost all of this accidental complexity is caused by the desire to support implicit conversions (!)

It is commonly believed that implicit conversions are usually evil anyways -- in this case it is so evil that it even causes unnecessary dependencies of core traits on other parts of stdlib.

Why do we really need `impl<'a> From<Cow<'a, str>> for Box<dyn Error> ` ? Why can't we deprecate these and replace with `Into`, if it's an orphan rule problem?
For that matter, why couldn't we move these trait implementations to `alloc` -- in many cases doesn't that satisfy orphan rules even if `Error` is in `core`?

I can't tell you how frustrating it is to spend hours trying to track down feature-unification issues with serde etc. in large `no_std` project, knowing that simply patching `serde` to remove all reference to `std::Error` would fix the issue. (I know because I tried this -- it allows massive simplification of configuration surface area for almost all of the crates in our project, and everything builds and the tests pass, but we're afraid of the burden of maintaining a patch like this against `serde`.)
All these fundamental libraries try to use `std::error::Error` because they think it is the "recommended way" to represent error types. But the `catch_unwind` stuff seems mostly discouraged anyway, and `std::error::Error` is only essential as part of the interface to that AFAIU. I guess they worry that if they don't implement `Error` then no one can throw the errors from their lib?

I find it so ironic that we are essentially re-iterating in Rust the fundamental bifurcation in C++ ecosystem -- the embedded libraries can't use exceptions, and everyone else does. In our case, `Error` is the interface of "catch_unwind" but conceptually not an "exception" -- a good start! But due to accidental complexity, this trait can't be used without `stdlib`, and so is, again, usually unsuitable in embedded. Snatching defeat from the jaws of victory! And the only solution left on the table seems to be that everyone will have `ifdef` everywhere to condition their usage of `std::error`, and every lib will have an `std` feature to support this. And again, as in C++, anyone doing embedded development in rust is likely to spend a good fraction of their time trying to patch open source libs and hack out references to the standard library, due to design and portability problems.

I wish I understood in better detail the issues described relating to negative trait bounds and `Box` etc. If making `Error` more portable really can't be resolved
after years of many people trying, that in itself suggests the current implementation (and specifically the integrations with other parts of stdlib) may not be maintainable. Deprecating some parts may be the simplest way to make progress IMHO, if making `Error` portable is really a goal.

@withoutboats Failure crate is really nice, thank you for that. And sorry for what, despite my efforts to organize my thoughts, is surely a rant. Thanks to all rust devs for your hard work.

**Comment by SimonSapin** [comment]
> And now at a moment when we could have moved Error to the recently stable liballoc, we decided that it was more interesting and important to integrate backtrace functionality that reads an environment variable into Error. 

To clarify: I did not make a judgment of what is preferable, nor did I say that Error in liballoc could never happen. Only that since we already accepted an RFC for `Error::backtrace`, process-wise  reverting or amending this decision requires an equivalent level of community discussion and team decision.

> It makes me really sad that there's no clear way to make progress on this.

I did propose a way above. I feel that if you’re writing 1600+ words for everyone else to read, the least you can do is read the comments you’re responding to.

> Why do we really need `impl<'a> From<Cow<'a, str>> for Box<dyn Error>` 

That would have been relevant discussion when this impl was being proposed. Now that’s it’s [stable](https://rust-lang.github.io/rfcs/1105-api-evolution.html) we can’t simply remove it.

> Error is the interface of "catch_unwind"

It’s not. This signature has no bound on the `Error` trait:

```rust
type Result<T> = std::result::Result<T, Box<dyn Any + Send + 'static>>;
pub fn catch_unwind<F: FnOnce() -> R + UnwindSafe, R>(f: F) -> Result<R> {…}
```

**Comment by withoutboats** [comment]
@cbeck88 I really encourage you to read in detail RFC 2504 as well the discussion on the pull request - rust-lang/rfcs#2504. Your comment evidences a confusion about some of the issues at play, and I have to be honest that your comment is rather impolitely bombastic for not understanding the situation clearly.

There are two viable paths toward making Error available to no_std crates:

* Make the backtrace type available to no_std as a ZST (like failure does).
* Change the core/alloc/std compilation system so that we can stop dealing with coherence/local method issues like this. We have many issues of this nature and it would be great to overcome them all in one swoop.

**Pull request closed without merging**
