### PR TITLE
extend `Ty` and `TyCtxt` lints to self types

### PR DESCRIPTION
**Pull request by lcnr**
blocked on #76891 

r? @ecstatic-morse cc @Aaron1011

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
We actually have a test for this internal lint: `grep` for `&TyCtxt`. r=me when that is updated.

**Comment by lcnr** [comment]
We need to add in inherent impl for `TyCtxt` for this update to matter, as we don't lint for trait impls.

So the only solution I see here is to add a new struct with `#[rustc_diagnostic_item = "TyCtxt"]` which seemed weird to me.
If you think this is worth it I will go ahead and add it.

**Comment by ecstatic-morse** [comment]
Ah yes, that's right. Do we even allow for colliding diagnostic impls I wonder? I would like to test this, could you try once with `#[rustc_diagnostic_item]`? If it breaks we can just merge as-is.

**Comment by lcnr** [comment]
added a test, the changes don't make too much sense for `Ty` as we would need to use custom self types :shrug: added a comment for this.

**Pull request merged**
