### PR TITLE
Link to PhantomData in NonNull documentation

### PR DESCRIPTION
**Pull request by czipperz**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @QuietMisdreavus 

Should we be using intra-doc links here?

**Comment by czipperz** [comment]
I thought it was fine because it was already linking to `UnsafeCell`

**Comment by Mark-Simulacrum** [comment]
Sure, this will work but I'm not sure if we're trying to incrementally migrate to intra doc links.

Thinking on this some more though no reason this can't land in the meantime: @bors r+ rollup

**Comment by QuietMisdreavus** [comment]
If the intra-doc links work there, then we can start incrementally migrating them. There have been several situations in libcore where an intra-doc link didn't work when re-exported into libstd, though, so there are some places where it doesn't work. It should be fine to try here, though - if i remember right, `core::ptr` is re-exported wholesale, so it should be doable.

**Pull request merged**
