### PR TITLE
Deprecate `_ms` functions that predate the `Duration` API

### PR DESCRIPTION
**Pull request by bstrie**

### CODE REVIEW

**Comment by bstrie** [comment]
Given that aturon and acrichto seemed surprised to discover that these APIs had not been deprecated, would we want to backport these to beta? If so, then hold off approving this until I have the chance to change the "since" tags.

**Comment by sfackler** [comment]
Doesn't really seem worth backporting. Since we missed these in 1.4, it doesn't seem to matter a ton if we deprecate in 1.5 or 1.6.

**Comment by bstrie** [comment]
@sfackler Doesn't matter a ton, but it does add an additional six week period where people may use these functions accidentally.

**Comment by Gankro** [comment]
We backport *very* little. Basically only serious bug fixes. I don't care if people use this functionality, it's not exactly a footgun or anything, just a crufty interface.

**Comment by steveklabnik** [comment]
Yup, big :-1: to back porting.

**Comment by alexcrichton** [comment]
I agree with others that it's ok to not backport this, we unfortunately missed the 1.5 train but another's always on the way! Regardless, though, thanks @bstrie!

@bors: r+ a2efa2aa291c938200da59b89b14214c8d2c70ba

**Pull request merged**
