### PR TITLE
make copy_within #[inline]

### PR DESCRIPTION
**Pull request by oconnor663**
@briansmith suggested this in
https://github.com/rust-lang/rust/issues/54236#issuecomment-447617175.

### CODE REVIEW

**Comment by sfackler** [comment]
We generally do not add `#[inline]` to methods that are already inlined.

**Comment by oconnor663** [comment]
@briansmith what do you think here? I don't know enough about the compiler to have a real opinion.

**Comment by briansmith** [comment]
I don't know under what circumstances the compiler automatically inlines functions. It seems reasonable to me to think that, although the compiler might inline something without a hint today, it might choose to not do so tomorrow. OTOH if the compiler is guaranteed to always inline the function (why?) then I agree it is redundant.

**Comment by sfackler** [comment]
> it might choose to not do so tomorrow.

This *is* the compiler. We know exactly how it behaves, and if it stops behaving that way, we'll deal with this at that time. There are literally thousands of functions that we expect to be inlined without an explicit `#[inline`].

**Comment by oconnor663** [comment]
I'll close this PR on that basis. I'm curious to know more, though: Is inlining something that's determined only by looking at the inlined function itself? Like if the compiler inlines `foo` in one case, should I expect it to inline `foo` in all cases?

**Comment by hudson-ayers** [comment]
FWIW, I have run into several places where `copy_within` is not inlined when using `opt-level=s`. I suspect this may be related to the addition of `#[track_caller]` to the method.

**Pull request closed without merging**
