### PR TITLE
Constify Result

### PR DESCRIPTION
**Pull request by lukaslueg**
r? @oli-obk

This is just the `Result`-part of #67494 which I'll resubmit once #66254 has landed.

### CODE REVIEW

**Comment by oli-obk** [comment]
So... while this is very const eval related, it's also T-libs. I'm not sure how to take these PRs. @rust-lang/libs are you ok with me r+ing PRs that make functions `const` if and only if the constness is unstable?

Some of these even use features that prevent the `const fn` from being made stable without also adding an `allow_internal_unstable` attribute, which @Centril and I would be very happy to be pinged on if `allow_internal_unstable` is added anywhere. But without stabilizing the constness, making a function `const fn` has no stability concerns at all.

**Comment by dtolnay** [comment]
@oli-obk, yes I think you should feel free to r+ PRs that add unstable constness to the standard library.

**Comment by oli-obk** [comment]
ok cool, thx

@bors r+

**Comment by oli-obk** [comment]
huh? Why did you force push?

**Comment by oli-obk** [comment]
also ccing #67520 here so the issue knows about this PR

**Comment by lukaslueg** [comment]
Sorry, post coming late. Tidy fixes

Oliver Scherer <notifications@github.com> schrieb am So., 29. Dez. 2019,
15:35:

**Comment by Dylan-DPC** [comment]
Failed in [rollup](https://github.com/rust-lang/rust/pull/67750#issuecomment-569905075). 

@bors r-

**Comment by lukaslueg** [comment]
rebased

**Pull request merged**
