### PR TITLE
Make `IntoIterator` lifetime bounds of `&BTreeMap` match with `&HashMap` 

### LINKED ISSUE #74034: Inconsistency between &HashMap and &BTreeMap implementation of IntoIterator
The implementation of `IntoIterator` for `&'a BTreeMap<K, V>` and `&'a HashMap<K, V, S>` differ in the lifetime bounds of `K` and `V`

```rust
impl<'a, K: 'a, V: 'a> IntoIterator for &'a BTreeMap<K, V> { \* ... *\ }
impl<'a, K, V, S> IntoIterator for &'a HashMap<K, V, S> { \* ... *\ }
```

I believe those additional bounds should be unnecessary since they're implied by the fact that exists a reference of lifetime `'a` to the whole map. However, quite interestingly, they appear to change how the compiler resolves trait bounds in some cases. For example in the following code:

```rust
trait Map
where
    for<'a> &'a Self: IntoIterator<Item = (&'a Self::Key, &'a Self::Value)>,
{
    type Key;
    type Value;
}

// Ok, compiles
impl<K, V> Map for HashMap<K, V> {
    type Key = K;
    type Value = V;
}

// Not ok, doesn't compiles, with rather cryptic error
impl<K, V> Map for BTreeMap<K, V> {
    type Key = K;
    type Value = V;
}
```

I would expect it to compile, or at least throw the same error for both the `BTreeMap` and `HashMap` implementation. 
However it throws errors only for the `BTreeMap` implementation. 

Also note that error E0311 isn't even present in the Rust Compiler Error Index.

```
error[E0311]: the parameter type `K` may not live long enough
  --> src/lib.rs:18:12
   |
18 | impl<K, V> Map for BTreeMap<K, V> {
   |            ^^^
   |
   = help: consider adding an explicit lifetime bound for `K`
   = note: the parameter type `K` must be valid for any other region...
note: ...so that the type `K` will meet its required lifetime bounds
  --> src/lib.rs:18:12
   |
18 | impl<K, V> Map for BTreeMap<K, V> {
   |            ^^^

error[E0311]: the parameter type `V` may not live long enough
  --> src/lib.rs:18:12
   |
18 | impl<K, V> Map for BTreeMap<K, V> {
   |            ^^^
   |
   = help: consider adding an explicit lifetime bound for `V`
   = note: the parameter type `V` must be valid for any other region...
note: ...so that the type `V` will meet its required lifetime bounds
  --> src/lib.rs:18:12
   |
18 | impl<K, V> Map for BTreeMap<K, V> {
   |            ^^^

error: aborting due to 2 previous errors
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c214377f7f3d85b8f193aef4015e89fe)

### PR DESCRIPTION
**Pull request by canova**
This is a pretty small change on the lifetime bounds of `IntoIterator` implementations of both `&BTreeMap` and `&mut BTreeMap`. This is loosening the lifetime bounds, so more code should be accepted with this PR. This is lifetime bounds will still be implicit since we have `type Item = (&'a K, &'a V);` in the implementation. This change will make the HashMap and BTreeMap share the same signature, so we can share the same function/trait with both HashMap and BTreeMap in the code.

Fixes #74034.
r? @dtolnay hey, I was touching this file on my previous PR and wanted to fix this on the way. Would you mind taking a look at this, or redirecting it if you are busy?

### CODE REVIEW

**Review by pickfire — APPROVED** [review]
Looks good to me.

**Comment by nbdd0121** [comment]
I don't quite understand the reason why `K: 'a, V: 'a` would make a difference here, isn't this implied because that's needed for `&'a BTreeMap<K, V>` to be well-formed?

**Comment by canova** [comment]
Yeah, `'a` lifetime should be implied for `K` and `V`, since also we have `(&'a K, &'a V)` as the Item type. But apparently it does make a difference when we put that lifetime bound to the `IntoIterator` impl signature. You can see that the test I added doesn't compile without this patch [in this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e4ddff8e878f782c5aeb70a4eef84643).

**Comment by nbdd0121** [comment]
What I am suggesting is that this may be an issue with the compiler and we might want to fix that instead.

**Comment by canova** [comment]
Well, yes, we can investigate more if we think this is a bug, but I don't think so really. I'm looking all the use cases of `IntoIterator` implementations in the rust codebase and there is no other implementation that actually adds lifetime bounds to type params: https://dxr.mozilla.org/rust/search?q=%22%3E+IntoIterator+for+%26%27%22&redirect=false
This doesn't look like the correct way of using this trait. Also, I don't see a reason not to land this change, because it's better to make the signatures of `HashMap` and `BTreeMap` match each other.

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by nbdd0121** [comment]
> Well, yes, we can investigate more if we think this is a bug, but I don't think so really.

This is certainly a bug. If you look at the minimal example in the original issue:
```rust
fn foo<'a, K, V, I: 'a + IntoIterator<Item = (&'a K, &'a V)>>(i: I) {}

fn bar() {
    let map = HashMap::<u32, u32>::new();
    foo(&map);
    
    let map = BTreeMap::<u32, u32>::new();
    foo(&map);
}
```

This code is rejected in Rust 2015 for both HashMap and BTreeMap, suggesting that `K: 'a` and `V: 'a` must be added. In Rust 2018 this is now implied, so it should accept BTreeMap, regardless that bound is specified implicitly or explicitly. I have no objection to this PR, but I suggest we keep the original issue open or open a new issue after this PR is merged to track this discrepancy.

**Comment by canova** [comment]
> This code is rejected in Rust 2015 for both HashMap and BTreeMap, suggesting that `K: 'a` and `V: 'a` must be added. In Rust 2018 this is now implied, so it should accept BTreeMap, regardless that bound is specified implicitly or explicitly. I have no objection to this PR, but I suggest we keep the original issue open or open a new issue after this PR is merged to track this discrepancy.

Hm, this minimal example also fails for `HashMap` in version 2018 and 2015. So I assume this is not exactly the bug issue tried explain. But you're right, there is something wrong with the example and should be fixed. I can't reopen the previous issue, so I opened #75252 to track this instead. Thanks for the explanation!

**Pull request merged**
