### PR TITLE
trans: Fix missing closure env drop-glue in trans-item collector.

### LINKED ISSUE #38810: trans: Collector misses closure drop-glue generated via fn-once-shims
FnOnce shims can introduce a drop of `ClosureType`, but the translation item collector only ever gets to see the `&ClosureType` which does not require drop-glue. This leads to errors because the desired drop-glue doesn't get instantiated.

@arielb1 Do I remember correctly that you were looking into FnOnce shims at the MIR level? That might help here.

### PR DESCRIPTION
**Pull request by michaelwoerister**
FnOnce adapters automatically generated by the compiler introduce a call to drop the closure environment. The collector didn't pick up on that because this drop call does not show up in MIR. That could lead to an assertion being triggered if the drop-glue for the environment wasn't instantiated via something else.

Fixes #38810

cc @arielb1 

r? @eddyb or @nikomatsakis

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by michaelwoerister** [comment]
@eddyb I just pushed a commit with an additional fix. Could you please review that too?

**Comment by KalitaAlexey** [comment]
@michaelwoerister, @eddyb
I see no tests were added.
Why is that?

**Comment by michaelwoerister** [comment]
The main reason is that the failure cannot show up with the current CGU partitioning scheme, only with different scheme I have in a local branch. But I'll try to come up with a test case once that scheme gets merged.

**Pull request merged**
