### PR TITLE
Avoid committing to autoderef in object method probing

### PR DESCRIPTION
**Pull request by arielb1**
This fixes the "leak" introduced in #57835 (see test for details, also apparently #54252 had no tests for the "leaks" that were fixed in it, so go ahead and add one).

Maybe beta-nominating because regression, but I'm against landing things on beta we don't have to.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@arielb1 I've been wondering about trying to move all of method selection to a canonical query. Have you thought about that at all?

**Comment by arielb1** [comment]
I'll rather talk a bit about it on Zulip.

**Comment by arielb1** [comment]
So I think the simpler approach to things I have found is actually sound, and I added a test for a few of the edge-cases that should pass (it passes today, and should continue passing).

I'll rewrite this PR when I have the time for that.

**Comment by arielb1** [comment]
PR rewritten to use new and much-simpler approach

**Comment by pnkfelix** [comment]
@arielb1 in your earlier version of this PR, you said you didn't want to beta-nominate the first version you posted.

From skimming this (simpler) version, it seems like a reasonable thing to consider backporting this to beta. Do you still dislike the idea of backporting this? Or do you agree it would be worthwhile to backport this?

**Comment by arielb1** [comment]
@pnkfelix 

I'm not quite sure. This looks simple enough, but it's subtle enough I'm not sure I want it to land on beta.

**Comment by pnkfelix** [comment]
@arielb1 okay well then the followup question becomes: What is your opinion on landing PR #57835 *without* PR #57885, in order to resolve #57673 before it hits stable?

**Comment by arielb1** [comment]
I'm actually ok with both options - the bug this PR fixes is quite subtle.

**Comment by pnkfelix** [comment]
beta-nominating to ensure we discuss at weekly meeting (either today or at some point after this patch lands.)

**Comment by arielb1** [comment]
So @nikomatsakis told me I should r+ this myself.

@bors r=nikomatsakis

**Pull request merged**
