### PR TITLE
Stabilize `option_get_or_insert_default`

### LINKED ISSUE #82901: Tracking Issue for `Option::get_or_insert_default`
Feature gate: `#![feature(option_get_or_insert_default)]`

This is a tracking issue for adding `Option::get_or_insert_default`.

Basically, it is a shorthand for `option.get_or_insert_with(Default::default)`. It differs with `unwrap_or_default` since it does not consume the `Option`. This is useful, for example, when you have an `Option` as a struct field or inside a data structure like `Vec<Option<T>>`.

### Public API

```rust
impl<T> Option<T> {
    pub fn get_or_insert_default(&mut self) -> &mut T where T: Default;
}
```

### Steps / History

- Original issue: #55042
- [x] Implementation: #82849
- [x] Renamed from `get_or_default` to `get_or_insert_default`: #82977
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

### PR DESCRIPTION
**Pull request by slanterns**
Closes: https://github.com/rust-lang/rust/issues/82901.

@rustbot label: +T-libs-api

r? libs-api

### CODE REVIEW

**Comment by apiraino** [comment]
t-compiler probably  can be removed

@rustbot label -t-compiler

**Comment by coolreader18** [comment]
Is there anything blocking this from merging?

**Comment by GrigorenkoPV** [comment]
> Is there anything blocking this from merging?

This PR had been opened before the FCP was completed, but now it has been https://github.com/rust-lang/rust/issues/82901#issuecomment-2293704213 so probably nothing other than someone with the merge rights ~pressing the button~ `r+`ing this.

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
