### PR TITLE
Implement Display for Duration.

### PR DESCRIPTION
**Pull request by SimonSapin**
… or was there a reason not to do it?

r? @alexcrichton

### CODE REVIEW

**Comment by SimonSapin** [comment]
Oh, I just found #25481. This may need to be more involved than I thought (rounding vs truncating, the meaning of width/padding, …) but I’m less convinced about using a different unit based on the range of value.

CC @kballard

**Comment by kballard** [comment]
@SimonSapin If you don't use a different unit, then Display will be useless for most uses, because it will only be appropriate for durations of a scale that makes sense with the unit you chose.

**Comment by alexcrichton** [comment]
I do think this type should implement `Display`, but as #25481 has shown I think it's a pretty tricky situation about *what* it should actually be displaying. We may want to figure out what format should be displayed before pushing forward with an implementation.

For example, if I have a 3 nanosecond duration it seems like the "most readable" representation would be along the lines of `3ns` rather than `0.000000003` as I believe this would print.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday, and the conclusion was that we probably don't actually want a `Display` implementation on `Duration`. Following [the guidelines for `Display`](https://github.com/rust-lang/rfcs/blob/8e2d3a3341da533f846f61f10335b72c9a9f4740/text/0565-show-string-guidelines.md#user-facing-fmtdisplay) an interesting point about durations is that there seems to be no "one true way" to display them that is both not lossy and useful. As a result, it's likely that we may want to provide adapters which themselves implement `Display` to get different methods of formatting a duration, but we probably don't want a `Display` implementation itself on the type.

As a result I'm going to close this for now, but we also decided we'd be fine with an unstable method returning a display-able adapter, so feel free to open a PR with that!

**Comment by alexcrichton** [comment]
Ah and another point brought up by @brson is that once you start dealing with time + printing the question of locales can come into play, so we either need to have a story around that or ensure that we're stepping around the problem.

**Pull request closed without merging**
