### PR TITLE
submodule detection for proper fix on #96188

### PR DESCRIPTION
**Pull request by onur-ozkan**
This commit resolves an internal FIXME note within the bootstrap by implementing submodule detection. This is accomplished through an iterative process over the `.gitmodules` file.

r? @albertlarsan68

### CODE REVIEW

**Comment by ozkanonur** [comment]
> I feel like the approach to get submodules is good, but I don't think the code does the wanted thing. I haven't tested my theory, but I feel like you should cache the submodules list. This avoids a problem (I think) where the first path goes until the end of the file, and the second path does nothing, because the cursor is already at the end, and is not rewound. The other option would be to rewind the file, but it would be less efficient.

File is 34 lines long :D And I don't think it will ever reach more than ~70. Doing proper caching will require keeping those values in the parent configuration within HashMap for O(1) access. Wouldn't that be overkill for this particular purpose? I would prefer forgetting the values once we finish the process here rather than keeping it in memory permamently.

**Comment by albertlarsan68** [comment]
A HashMap is definitely overkill, I was thinking about keeping the Vec that you construct.

**Comment by ozkanonur** [comment]
> A HashMap is definitely overkill, I was thinking about keeping the Vec that you build.

We can do that by adding it to Config, or require extra arg for `paths` function as `Vec` for submodules(which will require every caller calculating submodules first).

**Comment by ozkanonur** [comment]
Now it should be much better @albertlarsan68

**Comment by albertlarsan68** [comment]
There is already `once_cell` in bootstrap, can you use it and add a `FIXME` to use std when stabilized?
Otherwise good.

**Comment by ozkanonur** [comment]
> add a `FIXME` to use std when stabilized?

This isn't needed, it's already mentioned on the `use` statement in `builder` module.

**Review by albertlarsan68 — APPROVED** [review]
r=me with the `unwrap`changed to `expect`

**Pull request merged**
