### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
@fasterthanlime umm, bit of help here, do you know why this PR (as produced by `git subtree pull`) contains older commits? The last one was https://github.com/rust-lang/rust/pull/107992, followed by a merge to upstream in https://github.com/rust-lang/rust-analyzer/pull/14143.

**Comment by fasterthanlime** [comment]
> @fasterthanlime umm, bit of help here please, do you know why this PR (as produced by `git subtree pull`) contains older commits? The last one was #107992, followed by a merge to upstream in [rust-lang/rust-analyzer#14143](https://github.com/rust-lang/rust-analyzer/pull/14143).

Off the top of my head (and from my phone) I'm not sure. That one is the only older commit (Jan 11), right? https://github.com/rust-lang/rust/pull/108260/commits/3e0e51c108ad38aec4225769711df9c99df6347c

Everything else is from a month later at least, afaict.

**Comment by fasterthanlime** [comment]
@lnicola so I can't really explain what happened there unfortunately. However, I'm curious: if you do another rust->ra sync after this PR (you can pretend to do that without actually merging the PR through bors/GitHub's UI), does the next ra->rust sync also still contain this commit?

**Comment by lnicola** [comment]
This is how I tested:

```bash
# in the RA repo
$ git branch -D sync-from-rust

# in the Rust repo
$ git checkout rust-analyzer-2023-02-20
$ git subtree push -P src/tools/rust-analyzer rust-analyzer-local sync-from-rust
$ git checkout -b ra-new-sync
$ git subtree pull -P src/tools/rust-analyzer rust-analyzer-local sync-from-rust
$ git log --format=oneline
04c4eda971e945fa533880eb14fc6db314d8ed3e (HEAD -> ra-new-sync) Merge commit '7e711da2f07778d62f6411de5da520f1e260d761' into ra-new-sync
03288ebba35defc807952e6e55a0ab8f5f77aa83 (origin/rust-analyzer-2023-02-20, rust-analyzer-2023-02-20) :arrow_up: rust-analyzer
7e711da2f07778d62f6411de5da520f1e260d761 (rust-analyzer-local/sync-from-rust) :arrow_up: rust-analyzer
824f915cbc32c0942122389274a1b6fbe2ffc51e (upstream/master, upstream/HEAD, master) Auto merge of #108235 - tmiasko:read-buf, r=the8472
[snip]
```

**Comment by fasterthanlime** [comment]
> This is how I tested:

Okay well, it doesn't seem to show up again.

Here's what I don't understand about the current situation:

  * There's a commit with the same hash in both [RA](https://github.com/rust-lang/rust-analyzer/commit/3e0e51c108ad38aec4225769711df9c99df6347c) and [this PR](https://github.com/rust-lang/rust/commit/3e0e51c108ad38aec4225769711df9c99df6347c): having "the same commit" show up is by design, but they should affect different paths, and thus have different hashes
  * Said commit in that PR does not touch `src/tools/rust-analyzer/crates`, it touches `crates` directly, you can tell by looking at [this PR's commit](https://github.com/rust-lang/rust/commit/3e0e51c108ad38aec4225769711df9c99df6347c)

These paths don't show up in the [Files changed tab of the PR](https://github.com/rust-lang/rust/pull/108260/files), so I'm really not sure what's going on.

**Comment by lnicola** [comment]
Given that my test above went fine, should we merge it like this?

**Comment by fasterthanlime** [comment]
> Given that my test above went fine, should we merge it like this?

The test working makes me slightly more confident in this, ideally I'd love to have an extra pair of eyes on this, I've pinged a couple folks and will keep you posted

**Comment by fasterthanlime** [comment]
> The test working makes me slightly more confident in this, ideally I'd love to have an extra pair of eyes on this, I've pinged a couple folks and will keep you posted

I haven't heard back yet and don't want to block this, you got my 👍

**Comment by workingjubilee** [comment]
Based on my subtree experiences, I think it's fine. Sometimes a commit gets confusingly replayed on the other side of the subtree so git can't quite be sure if it's new or not. If it's only one in a hundred commits or so, it's annoying but not unexpected.

**Pull request merged**
