### PR TITLE
Add Cargo.lock merge driver

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Mostly self-documented. This is made for convenience when PR is long in queue or waiting for review.

This will not (reliably) work in Homu yet as the displayed mergeable status messages are based on GitHub API. It may work if you configured on the bot side and trick it to force a merge.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Under what scenarios does this Python script get run?

**Comment by aidanhs** [comment]
I'm not really comfortable having something so potentially destructive in-tree. On an attempt to merge a cargo.lock it will blow away all changed or untracked files in any submodules (bar llvm/jemalloc), even if the submodules have nothing to do with what's currently being merged.

I also find it a little unlikely this will get use in bors, since cargo would now be a dependency and it's nice to be able to easily get a grasp on the merge operation bors performs (I'm not entirely sure when merge drivers get run at or what copy of the working tree they'd end up seeing). I don't even think bors clones submodules, if it does (as this script could cause) that adds another 10min to builds.

All that said, I don't know how often Cargo.lock merge conflicts happen. Is this something you primarily see people installing on their local machines, or is this you eventually want to end up within bors itself @ishitatsuyuki?

**Comment by Mark-Simulacrum** [comment]
I could see the script being helpful, but I agree with @aidanhs that I don't think automatically running a script on merge is a good idea -- it seems too powerful, and too surprising. In general, I don't think Cargo.lock merge conflicts are too common, and generally aren't that bad to deal with (as evidenced, in part, by the relative simplicity of the PR).

**Comment by ishitatsuyuki** [comment]
This is opt-in, and I would expect people having a clean tree when merging. I don't even touch the submodules directly (I only go with a commit).

I have experienced many times that I forgot to update the lockfile or generating with outdated submodules. Automation is great here.

I'm not sure if the clone time is long, as the llvm submodule is not touched here. Installing in bors would be great, but as I described it's too tricky and could be dangerous in some circumstances (open to attack from external code).

**Comment by Mark-Simulacrum** [comment]
@rust-lang/infra: I won't have time to give this the attention it deserves in the near future, so r? @aidanhs for now. Surface-level inclined to merge just the script itself.

**Comment by alexcrichton** [comment]
It seems like this isn't really a "merge driver" so much as "a way to call `cargo generate-lockfile` with updated submodules". In general merging lock files isn't done by just blowing away the existing lockfile and generating a new one (which is what `generate-lockfile` does right now) but rather performing a conservative update. Typically that'll involve a hard reset to the lock file that the master branch has and then just running `cargo build` again.

**Comment by aidanhs** [comment]
I'd like to bring this PR up at the next infra meeting to talk about
1. which team 'owns' `etc`?
2. should we have a contrib directory like git?

For context: the git project has a contrib directory and a readme describing the general philosophy at https://github.com/git/git/tree/master/contrib. Should we have something similar for scripts like this PR?

**Comment by ishitatsuyuki** [comment]
In reply to @alexcrichton's comments:

I think there's currently no way to perform a conservative update without side effects.

If it's implemented, it's quite possible to do the same thing by using the parameters git passes to the merge driver. I don't think it will be immediate, so it should be modified in future PRs.

**Comment by aidanhs** [comment]
I hadn't fully understood the impact of this PR when I first looked at it, and I'm even more hesitant now - I really don't think we should be encouraging anything other than a conservative update, but unfortunately this PR tacitly encourages full updates. If `cargo generate-lockfile` had a `--guided` (or `--conservative` or whatever) option that used an existing `Cargo.lock` file as a guide I could possibly see merging this but there are too many questions in my mind in the meantime.

There is another question that this PR raises, around the `etc` directory and ownership. We talked about this in the infra team meeting, and it seems that the contents of `etc` are miscellanea owned by an assortment of teams - this PR would therefore be an odd one out in that it doesn't have de-facto acceptance by a team. So I think we'd like to see a proposal for the layout (`contrib` directory or otherwise), some motivating examples and process (e.g. positive feedback on internals and approval from an rfcbot for a related team).

I apologise for the explosion in complexity here! Your PR has raised a number of interesting questions we don't have an answer to and we'd like to have a better idea of the big picture before moving forward.

I'm sure you want to use this yourself and part of your motivation for this PR is to get the `.gitattributes` updated. It looks like you should be able to use `.git/info/attributes` (https://git-scm.com/docs/gitattributes) without interfering tracked content in the Rust repo - hopefully this will at least let you scratch your itch in the meantime!

**Comment by carols10cents** [comment]
@aidanhs it sounds like you're advocating for this to be closed, right? Since your suggestion was to make updates more conservative but that option doesn't exist right now? Could you close this PR or clarify what @ishitatsuyuki could do to get this in a mergeable condition please?

**Comment by ishitatsuyuki** [comment]
I think this is ok to be postponed. Closing.

**Pull request closed without merging**
