### PR TITLE
Require LLVM 3.6

### LINKED ISSUE #20010: Rust requires llvm.assume intrinsic and hence LLVM 3.6
The rust ./configure LLVM version check is only for 3.[2-6], yet https://github.com/rust-lang/rust/pull/18080 adds a requirement on llvm.assume intrinsic.  This intrinsic only appears in LLVM 3.6.

I think the version check needs to be updated accordingly - or only use the new optimisation intrinsic conditionally on building against newer LLVM.

### PR DESCRIPTION
**Pull request by tamird**
Closes #20010.

### CODE REVIEW

**Comment by dotdash** [comment]
#25739 has fixes to make things compatible with 3.5.2

**Comment by alexcrichton** [comment]
Yeah I think that we may want to pursue #25739 for now (which doesn't *require* `llvm.assume` for example), but thanks for the PR!

**Comment by tamird** [comment]
Sure, thanks @alexcrichton.

**Pull request closed without merging**
