### PR TITLE
Remove images' url to make it work even without internet connection

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Needed for local std docs mainly.

cc @SimonSapin 

r? @QuietMisdreavus

### CODE REVIEW

**Comment by joshtriplett** [comment]
Looks great to me. This would mean the Debian packages don't need to sed away these URIs in the output anymore.

cc @infinity0

**Comment by GuillaumeGomez** [comment]
Rebased.

**Comment by SimonSapin** [comment]
By the way @GuillaumeGomez, does this remove the logo entirely or is there a copy of it shipped together with the generated docs?

**Comment by GuillaumeGomez** [comment]
If the `image_url` parameter isn't provided, a copy of the image will be provided alongside (so if multiple crates are generated, just one image is provided but still one).

**Pull request merged**
