### PR TITLE
Ignore more files from rustdoc-GUI test suite

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Why are we trying to ignore these files literally anywhere in tree? I thought we had arrived at a set of instructions that made these unlikely to get generated in tree (preferring global installation and such)?

**Comment by GuillaumeGomez** [comment]
I don't know how these files are generated. I just realized that after a few runs, they appeared when I ran "git status"...

**Comment by Mark-Simulacrum** [comment]
Can you say more about where they appeared, at least?

**Comment by GuillaumeGomez** [comment]
To be confirmed. I'll monitor it locally and try to find out what's going on.

**Comment by jyn514** [comment]
Closing this until @GuillaumeGomez has time to investigate; I haven't seen these files show up locally.

**Pull request closed without merging**
