### PR TITLE
Added a job to dry-run the publish_toolstate.py once

### LINKED ISSUE #56848: The toolstate script is not tested inside CI
At the moment we don't test that `publish_toolstate.py` works on CI. This means if a PR (like https://github.com/rust-lang/rust/pull/56758) makes a change that breaks the script we don't notice until [it breaks master](https://travis-ci.org/rust-lang/rust/builds/468399601).

We should at least check if the script's syntax is correct on CI, and ideally do a dry run.

cc @rust-lang/infra

### PR DESCRIPTION
**Pull request by kennytm**
Closes #56848.

Requires #56847 to be merged first.

### CODE REVIEW

**Comment by pietroalbini** [comment]
r=me once the revert is merged. Thanks!

**Comment by Mark-Simulacrum** [comment]
Could we move this code to the mingw-check builder? I think having more than one "short" builder probably doesn't make too much sense; people in infra meeting seemed to agree.

I'm explicitly not r- this PR though since I think we need the test more than we need this change, so we can land the change in a future PR.

**Comment by kennytm** [comment]
@Mark-Simulacrum Moved the code into the `before_script:` of `IMAGE=mingw-check`.

**Pull request merged**
