### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #102642 (Add tests for static async functions in traits)
 - #103283 (Add suggestions for unsafe impl error codes)
 - #103523 (Fix unwanted merge of inline doc comments for impl blocks)
 - #103550 (diagnostics: do not suggest static candidates as traits to import)
 - #103641 (Don't carry MIR location in `ConstraintCategory::CallArgument`)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=102642,103283,103523,103550,103641)

### CODE REVIEW

**Comment by lqd** [comment]
@rust-timer build 1f09266710d7a27fef22f4f26e9e3399a4bbdcce

**Comment by lqd** [comment]
I *think* https://github.com/rust-lang/rust/pull/103641 affected `deeply-nested-multi`, while `keccak`, `cranelift-codegen`, `wg-grammar` may currently be noisy, starting with this PR.

The diagnostics changes #103550 may be involved in perturbing codegen for typeck, impacting these benchmarks. There's nothing else in this PR anyway, so let's see if something shows up on the few remaining benchmarks.

@rust-timer build b590acdbf672ea83df12dfa034b1e19d127a0f34

**Comment by rylev** [comment]
@rust-timer build b590acdbf672ea83df12dfa034b1e19d127a0f34

**Pull request merged**
