### PR TITLE
E0435, E0437 & E0438 New Error Format

### PR DESCRIPTION
**Pull request by shyamsundarb-arch**
Part of #35801 , #35802 and #35803
r? @GuillaumeGomez 

Hi! Please review the changes.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR (and for squashing)

Have you compiled and tested this PR?  Our tester found that this code does not yet compile:

```
src/librustc_resolve/lib.rs:254:13: 260:95 error: mismatched types [E0308]

src/librustc_resolve/lib.rs:254             struct_span_err!(resolver.session,

                                            ^

src/librustc_resolve/lib.rs:254:13: 260:95 help: run `rustc --explain E0308` to see a detailed explanation

src/librustc_resolve/lib.rs:254:13: 260:95 note: expected type `errors::DiagnosticBuilder<'a>`

src/librustc_resolve/lib.rs:254:13: 260:95 note:    found type `()`

src/librustc_resolve/lib.rs:263:13: 269:95 error: mismatched types [E0308]

src/librustc_resolve/lib.rs:263             struct_span_err!(resolver.session,

                                            ^

src/librustc_resolve/lib.rs:263:13: 269:95 help: run `rustc --explain E0308` to see a detailed explanation

src/librustc_resolve/lib.rs:263:13: 269:95 note: expected type `errors::DiagnosticBuilder<'a>`

src/librustc_resolve/lib.rs:263:13: 269:95 note:    found type `()`

src/librustc_resolve/lib.rs:443:13: 447:99 error: mismatched types [E0308]

src/librustc_resolve/lib.rs:443             struct_span_err!(resolver.session,

                                            ^

src/librustc_resolve/lib.rs:443:13: 447:99 help: run `rustc --explain E0308` to see a detailed explanation

src/librustc_resolve/lib.rs:443:13: 447:99 note: expected type `errors::DiagnosticBuilder<'a>`

src/librustc_resolve/lib.rs:443:13: 447:99 note:    found type `()`

error: aborting due to 3 previous errors
```

You may want to have another look.  Just ping me or @GuillaumeGomez when you're ready.

**Comment by shyaamsundhar** [comment]
@jonathandturner Hi. Thanks for your patience with me. I have fixed the cause of errors. Hopefully it should get through.

**Comment by GuillaumeGomez** [comment]
It doesn't coompile.

**Comment by shyaamsundhar** [comment]
Hopefully I compiled in local with the previous errors rectified. It should compile.

**Comment by shyaamsundhar** [comment]
@GuillaumeGomez Kindly review changes.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
