### PR TITLE
Update rustfmt and rls

### PR DESCRIPTION
**Pull request by h-michael**
Update submodule, rustfmt and rls.

rustfmt: https://github.com/rust-lang/rustfmt/compare/be13559...ce682bd

rls: https://github.com/rust-lang/rls/compare/f331ff7...c4e4da9

cc: @Centril this commit includes making rustfmt 2018 idioms.
#58099

### CODE REVIEW

**Comment by h-michael** [comment]
Uh.. We may update racer's rustc-ap-syntax version.

**Comment by h-michael** [comment]
I've create PR https://github.com/racer-rust/racer/pull/1016.

**Comment by Xanewok** [comment]
@bors r+ p=1

Bumping priority due to Cargo.lock and submodule updates.

**Pull request closed without merging**
