### PR TITLE
Update submodules (Clippy, RLS)

### PR DESCRIPTION
**Pull request by Xanewok**
Basically https://github.com/rust-lang/rust/pull/59916 with one fix applied to make it build

### CODE REVIEW

**Comment by Xanewok** [comment]
Approved the last one and only pushed a small build fix (rand_core -> 0.3.1), so...

r? @Xanewok 
@bors r+ p=10

**Comment by Xanewok** [comment]
Based on https://github.com/rust-lang/rust/issues/59901#issuecomment-482526685 and since https://github.com/rust-lang/rust/pull/59733 is already being tested in the queue, I've omitted Miri for now

@bors r+

**Comment by mati865** [comment]
You don't have to update `rand` when `miri` is gone.

**Comment by Xanewok** [comment]
I'd like to avoid headache for someone that'd decide to update Miri together with rand (because of the rand_core:0.3.0 incompatibility) and hopefully that should the Miri update should follow very soon

**Comment by Xanewok** [comment]
The linker error definitely looks unrelated unless I'm missing something obvious. Let's go for the minimal patch as you're saying

**Pull request merged**
