### PR TITLE
compiletest: detect non-ICE compiler panics

### LINKED ISSUE #49888: compiletest: check_no_compiler_crash doesn't catch non-ICE panics
As noted in https://github.com/rust-lang/rust/pull/49826#issuecomment-380591115, currently rustc is panicking on `compile-fail/issue-36638` (which I will file as a separate bug), but compiletest does not detect this because it's also not caught as an ICE (to be fixed by #49826).  In `check_no_compiler_crash`, it only looks for the literal string "error: internal compiler error".

### PR DESCRIPTION
**Pull request by cuviper**
Fixes #49888, but will be blocked by revealing #49889.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me, but if this can't land I'll hold off on approving

**Comment by kennytm** [comment]
Blocked by #49889.

**Comment by cuviper** [comment]
Oh joy, found another compiler panic!

**Comment by cuviper** [comment]
cc @nikomatsakis -- seems you last tweaked `nll_beyond` in #49836.

**Comment by cuviper** [comment]
Filed #50128.

**Comment by cuviper** [comment]
I disabled `nll_beyond` per https://github.com/rust-lang/rust/issues/50128#issuecomment-384064384.

**Comment by cuviper** [comment]
Yay, the initial CI passed!

**Pull request merged**
