### PR TITLE
Use intra-doc-links in `core::{char, macros, fmt}`

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Helps with #75080.
r? @jyn514

### CODE REVIEW

**Review by jyn514 — COMMENTED** [review]
This will conflict with https://github.com/rust-lang/rust/pull/75815, but no helping that since `prim@` doesn't exist yet. Looks fine otherwise.

**Review by jyn514 — COMMENTED** [review]
r=me after nit

**Comment by LeSeulArtichaut** [comment]
Alright, this time there is NO reason why CI won't pass :D

**Comment by jyn514** [comment]
```
alloc/fmt/trait.Write.html:12: broken link - alloc/fmt/crate::write!
alloc/fmt/trait.Write.html:53: broken link - alloc/fmt/crate::write!
alloc/fmt/trait.Write.html:55: broken link - alloc/fmt/crate::write!
alloc/fmt/fn.write.html:16: broken link - alloc/fmt/crate::write!
alloc/fmt/struct.Formatter.html:365: broken link - alloc/fmt/crate::format_args
```
This is https://github.com/rust-lang/rust/pull/75176.

**Comment by jyn514** [comment]
Note to anyone making rollups: this will cause conflicts with #75815, so they shouldn't be placed in the same rollup.

**Pull request merged**
