### PR TITLE
[beta] 1.46 beta

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors treeclosed=5

will continue to manually shepherd today

**Comment by Manishearth** [comment]
```
2020-07-14T14:05:10.4562495Z [RUSTC-TIMING] cargo_metadata test:false 8.008
2020-07-14T14:05:11.0796179Z [0m[1m[38;5;9merror[E0635][0m[0m[1m: unknown feature `const_transmute`[0m
2020-07-14T14:05:11.0796697Z [0m  [0m[0m[1m[38;5;12m--> [0m[0m/cargo/registry/src/github.com-1285ae84e5963aae/rustc-ap-rustc_ast-664.0.0/lib.rs:13:12[0m
2020-07-14T14:05:11.0797080Z [0m   [0m[0m[1m[38;5;12m|[0m
2020-07-14T14:05:11.0797433Z [0m[1m[38;5;12m13[0m[0m [0m[0m[1m[38;5;12m| [0m[0m#![feature(const_transmute)][0m
2020-07-14T14:05:11.0798073Z [0m   [0m[0m[1m[38;5;12m| [0m[0m           [0m[0m[1m[38;5;9m^^^^^^^^^^^^^^^[0m
2020-07-14T14:05:11.0932281Z 
```

**Comment by Manishearth** [comment]
I think we're going to have to wait for the rust ap stuff

**Comment by Manishearth** [comment]
Once the ap stuff goes through would you mind updating this PR to include the clippy update? (currently in CI)

**Comment by Mark-Simulacrum** [comment]
Oh right, I forgot we never fixed toolstate this cycle. Indeed this will need to wait for that and we'll just re-promote at that point (basically rebasing atop master) I imagine.

**Comment by Manishearth** [comment]
@bors r-

This had failed, no?

**Comment by Manishearth** [comment]
homu seems to have gotten confused

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/72920 landed in the same rollup as the fix for the toolstate failures on rustfmt/RLS so we didn't note that the fix didn't actually fix things (since that PR introduced a regression, technically, in beta-week). I don't know that tooling could've detected it though -- I guess we should just not rollup toolstate-fixing PRs in beta week?

Anyway, I pushed up a dummy commit that just re-adds that const_transmute intrinsic and seems to fix the build for RLS and rustfmt locally -- hopefully that's also the case on CI.

@bors r+ rollup=never p=20

**Comment by Manishearth** [comment]
```
     Running `build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo-miri miri setup`
ERROR: the sysroot can't be built for the Beta channel. Switch to nightly.
fatal error: Failed to run xargo


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "run" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/miri/cargo-miri/Cargo.toml" "--features" "rustc-workspace-hack/all-static" "--" "miri" "setup"
expected success, got: exit code: 1


[TIMING] Miri { stage: 2, host: "x86_64-unknown-linux-gnu" } -- 33.283

2 command(s) did not execute successfully:

  - "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/rustfmt/Cargo.toml" "--features" "rustc-workspace-hack/all-static"

  - "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "run" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/miri/cargo-miri/Cargo.toml" "--features" "rustc-workspace-hack/all-static" "--" "miri" "setup"

failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --no-fail-fast src/doc/book src/doc/nomicon src/doc/reference src/doc/rust-by-example src/doc/embedded-book src/doc/edition-guide src/tools/rls src/tools/rustfmt src/tools/miri
Build completed unsuccessfully in 0:33:37
```

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=20

Tools builder is passing on the PR at least.

**Comment by mati865** [comment]
Miri should not be built on beta and stable.

**Comment by Mark-Simulacrum** [comment]
Miri failures are ignored -- we do currently try to build it, though. I'd be happy to take a patch that doesn't do so.

**Comment by mati865** [comment]
That's what https://github.com/rust-lang/rust/pull/73232 was supposed to fix 🤔

**Comment by Mark-Simulacrum** [comment]
> That's what #73232 was supposed to fix thinking

You're not wrong, but indeed the tools builder explicitly lists miri (https://github.com/rust-lang/rust/blob/c724b67e1b474262917a5154d74e7072267593fe/src/ci/docker/host-x86_64/x86_64-gnu-tools/checktools.sh#L19) so the defaults don't actually matter still -- only for `x.py build` for example will they affect things.

My guess is we can add some logic around (https://github.com/rust-lang/rust/blob/c724b67e1b474262917a5154d74e7072267593fe/src/bootstrap/test.rs#L358 that'll just refuse to test miri on stable/beta.

**Comment by mati865** [comment]
I'll cc @RalfJung in case they want to continue work on https://github.com/rust-lang/rust/pull/74323#issuecomment-658833707

**Comment by Mark-Simulacrum** [comment]
That would work too, I'm just less familiar with bash so would need to probably put in more effort (and we'd have a duplicate list of stable/unstable tools).

**Comment by RalfJung** [comment]
How did this land now if Miri is failing?

**Comment by mati865** [comment]
Miri fail is non fatal. It doesn't stop the build.

**Comment by RalfJung** [comment]
Oh so the problem that came up here is that the build happened at all, not that the failure was a problem?

**Comment by mati865** [comment]
I haven't checked the logs but something else must have failed.

**Comment by RalfJung** [comment]
Okay I thought there was an actual problem here not just "we are running more tests than we should". Oh well.

Here's my partial attempt at fixing this: https://github.com/rust-lang/rust/pull/74389. But I give up here, rustbuild is too hard to work on I am afraid and my Miri TODO list is already overflowing with other stuff. ;) Hopefully this is a start that someone else can build on, if anyone cares.

**Pull request merged**
