### PR TITLE
Switch Fuchsia to readdir (instead of readdir_r)

### LINKED ISSUE #40021: Many posix platforms should use readdir instead of readdir_r
Linux now deprecates readdir_r (see https://lwn.net/Articles/696474/ for the reasons for this deprecation), and Fuchsia doesn't implement it at all. There's already a configure switch in `src/libstd/sys/unix/fs.rs`, but it only selects readdir for Illumos.

The config should be switched to readdir at least for Fuchsia, and arguably for a number of other Posix-compatible systems as well. Sifting through exactly which should be which is beyond my scope, so I entrust this to the rust-libs community.

### PR DESCRIPTION
**Pull request by raphlinus**
The readdir_r function is deprecated on newer Posix systems because of
various problems, and not implemented at all for Fuchsia. There are
already implementations using both, and this patch switches Fuchsia
over to the readdir-based one.

Fixes #40021 for Fuchsia, but that issue also contains discussion of
what should happen for other Posix systems.

### CODE REVIEW

**Comment by raphlinus** [comment]
Note: this PR is dependent on https://github.com/rust-lang/libc/pull/533 being merged. It will almost certainly cause build breakages until then.

Also, as per discussion, I'd be happy for this change to be applied to other targets, in which case this PR is not sufficient. Hopefully, it's still useful, if for no other reason than to show what needs to change.

Tested with recent Fuchsia, and also seems to build correctly on MacOS (the latter is not obvious because of the `readdir$INODE64` name mangling - if the underlying libc patch was wrong, I'd expect problems).

**Comment by alexcrichton** [comment]
Looks good to me! I guess though we should hold off until https://github.com/rust-lang/libc/pull/533 is merged?

**Comment by alexcrichton** [comment]
er, 

@bors: r-

Looks like a merge conflict?

**Comment by raphlinus** [comment]
I think I just need to git pull from master, will upload another version as soon as I locally confirm it works.

**Pull request merged**
