### PR TITLE
Add an option to the parser so cfg'ed out modules can still be parsed

### PR DESCRIPTION
**Pull request by nrc**
r? @jseyfried 

cc @dtolnay, @erickt it would be great if we could get this picked up into Syntex asap - it fixes a pretty nasty bug in Rustfmt.

### CODE REVIEW

**Comment by nrc** [comment]
cc https://github.com/rust-lang/rust/pull/36482

**Comment by dtolnay** [comment]
Since you said asap, I am just going to grab ac2c1da and turn it into a syntex release.

**Comment by dtolnay** [comment]
I released Syntex 0.56.0 based on ac2c1da48631bc183e07a89d73c88bae25af1fb9.

**Comment by nrc** [comment]
@dtolnay  Awesome, thank you!

**Comment by nrc** [comment]
@bors r=@jseyfried 

@dtolnay could you pick up the updated PR into Syntex please? Because I am a doofus who can't do basic logic :-(

**Comment by dtolnay** [comment]
https://crates.io/crates/syntex_syntax/0.56.1

**Comment by nrc** [comment]
thanks!

**Comment by nrc** [comment]
@bors r=@jseyfried

urgh, another bug fix (at least I managed to test this one properly, so hopefully it'll be the last)

@dtolnay sorry, to keep bothering you with this, but another fix when you have a minute, thanks!

**Comment by dtolnay** [comment]
This is your last chance! After this we're waiting for a successful nightly build. I released v0.56.2.

**Comment by alexcrichton** [comment]
@bors: retry

* apparent travis bug?

**Pull request merged**
