### PR TITLE
Allow `blur` to work even when `rustdoc` is not the main `<body>`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/rust-lang/docs.rs/issues/1076

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
You also need to update the styles, right now they hard-code `<body>`.

**Comment by GuillaumeGomez** [comment]
Forgot to commit it, sorry... Force-pushed it.

**Comment by jyn514** [comment]
Hmm, I'm a little nervous changing from a class to an ID will break docs.rs' fragile parsing code. I don't have something to point to, but we hard-code a lot of styles and I'd prefer to not to change the rustdoc HTML more than we have to 😅

**Comment by GuillaumeGomez** [comment]
It makes it stronger because otherwise I'll have to loop over elements with the `rustdoc` class. I can give a hand on the docs.rs side to ensure it won't break anything. :wink:

**Comment by jyn514** [comment]
> I can give a hand on the docs.rs side to ensure it won't break anything. 😉

Well the issue is it will have to be compatible with the HTML before and after the change, which sounds difficult if you're changing from a class to an ID.

I'm also no longer sure this should be fixed on rustdoc's end ... I think this is actually a regression, take a look at https://github.com/rust-lang/docs.rs/blob/master/templates/style/base.scss#L42-L55

**Comment by GuillaumeGomez** [comment]
You can have both `.rustdoc` and `#rustdoc`. I personally think it's better to use an ID but if you think it's too much of a burden, I can keep the class and iterate over the elements. As you prefer.

**Pull request closed without merging**
