### PR TITLE
evade unused_variables lint in for-loop desugaring

### LINKED ISSUE #30371: Unused variable `result` without variable result (for loop)
Code:

```
fn main() {
    for _ in match return () {
        () => Some(0),
    } {}
}
```

Warning:

```
$ rustc a.rs
a.rs:2:5: 4:9 warning: unused variable: `result`, #[warn(unused_variables)] on by default
a.rs:2     for _ in match return () {
a.rs:3         () => Some(0),
a.rs:4     } {}
```

[Playpen](https://play.rust-lang.org/?gist=3f4373be0860d4685bf5&version=nightly)

It probably has something to do with for loop desugaring.

### PR DESCRIPTION
**Pull request by durka**
Fixes #30371.

### CODE REVIEW

**Comment by mitaa** [comment]
Pretty failure:

```diff
@@ -13,8 +13,7 @@
 fn main() {
     for _ in
         match return () {
-
-            // should not have a warning here
+             // should not have a warning here
             () => Some(0),
         } {
     }
```

**Comment by durka** [comment]
Ugh. But that's not where the warning is. Should I remove that comment or move it to the line before the match?

I'm also going to fix the comment in lowering.rs which I made stale.

**Comment by durka** [comment]
How can I run the pretty test locally? I guess it's not party of `make tidy`.

**Comment by durka** [comment]
Also, I found a smaller test case:

```rust
fn main() {
    for _ in { panic!(); Some(()) } {}
}
```

Should I replace the test with that, or include both?

**Comment by durka** [comment]
\o/

**Comment by sanxiyn** [comment]
FYI: you can use `make check-pretty` to run pretty tests.

**Pull request merged**
