### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #123726 (Clarify `Command::new` behavior for programs with arguments)
 - #126088 ([1/2] clean-up / general improvements)
 - #126238 (Fix Miri sysroot for `x run`)
 - #126315 (Add pub struct with allow(dead_code) into worklist)
 - #126360 (Uplift `structural_traits.rs` into the new trait solver)
 - #126371 (Tweak output of import suggestions)
 - #126388 (const-eval: make lint scope computation consistent)
 - #126390 (Fix wording in {checked_}next_power_of_two)
 - #126392 (Small style improvement in `gvn.rs`)
 - #126402 (Fix wrong `assert_unsafe_precondition` message for `core::ptr::copy`)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=123726,126088,126238,126315,126360,126371,126388,126390,126392,126402)

### CODE REVIEW

**Comment by estebank** [comment]
This seems to have been caused by #126371. (And I have no idea why.)

**Comment by matthiaskrgr** [comment]
@estebank  it happens everywhere, also https://github.com/rust-lang/rust/pull/126426 for example.
fix is prepared in https://github.com/rust-lang/rust/pull/126436

**Comment by GuillaumeGomez** [comment]
To be clear: no idea either. This test was not updated in a long time, so it's surprising that it's breaking out of the blue.

**Pull request merged**
