### PR TITLE
Fix from_utf8* links

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #55666.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by frewsxcv** [comment]
```
[01:39:02] std/primitive.str.html:89: broken link - /checkout/obj/build/x86_64-unknown-linux-gnu/std/str/fn.from_utf8.html
[01:39:02] std/primitive.str.html:98: broken link - /checkout/obj/build/x86_64-unknown-linux-gnu/std/str/fn.from_utf8_mut.html
```

**Comment by GuillaumeGomez** [comment]
This code is re-used everywhere... Talk about weird docss.

**Comment by QuietMisdreavus** [comment]
These links are ones that are impossible to make work with relative links like that. They appear in both `std/primitive.str.html` and on `std/string/struct.String.html` because of how String Derefs to `str`. Does an intra-doc link work?

**Comment by GuillaumeGomez** [comment]
Apparently not. I was completely unable to make intra links work with this one. We'll need more advanced intra-links support before making this one work.

**Comment by frewsxcv** [comment]
> We'll need more advanced intra-links support before making this one work.

is there a tracking issue for this?

**Comment by Mark-Simulacrum** [comment]
Sounds like maybe this is currently ~impossible to do because of lack of support in the compiler? As such I'm going to close this but feel free to reopen if a better solutions arises.

**Comment by Mark-Simulacrum** [comment]
Sounds like maybe this is currently ~impossible to do because of lack of support in the compiler? As such I'm going to close this but feel free to reopen if a better solutions arises.

**Pull request closed without merging**
