### PR TITLE
Add missing urls on Vec docs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @steveklabnik

### CODE REVIEW

**Comment by frewsxcv** [comment]
```
Linkcheck stage2 (x86_64-unknown-linux-gnu)
collections/index.html:134: broken link - /build/build/x86_64-unknown-linux-gnu/std/struct.Vec.html
collections/vec/index.html:52: broken link - std/struct.Vec.html
collections/vec/index.html:58: broken link - std/struct.Vec.html
collections/vec/index.html:58: broken link - std/struct.Vec.html
collections/vec/index.html:80: broken link - std/struct.Vec.html
collections/vec/struct.Vec.html:485: broken link fragment  `#method.into_vec` pointing to `collections/vec/struct.Vec.html`
std/index.html:696: broken link - /build/build/x86_64-unknown-linux-gnu/std/struct.Vec.html
std/vec/index.html:52: broken link - std/struct.Vec.html
std/vec/index.html:58: broken link - std/struct.Vec.html
std/vec/index.html:58: broken link - std/struct.Vec.html
std/vec/index.html:80: broken link - std/struct.Vec.html
thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:56
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by GuillaumeGomez** [comment]
Updated (waiting for url check...).

**Comment by frewsxcv** [comment]
```
Linkcheck stage2 (x86_64-unknown-linux-gnu)
collections/index.html:134: broken link - /build/build/x86_64-unknown-linux-gnu/std/vec/struct.Vec.html
std/index.html:696: broken link - /build/build/x86_64-unknown-linux-gnu/std/vec/struct.Vec.html
thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:56
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by GuillaumeGomez** [comment]
Ok, should be ok now. The issue was that the short description urls are totally broken.

**Comment by frewsxcv** [comment]
Looks good! :sparkles:

@bors r+ rollup

**Pull request merged**
