### PR TITLE
Issue #27628 - Also support the LLVM 3.6 IR format in two tests

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by dotdash** [comment]
I think you need to escape the `*` in the regular expressions. I didn't think of that when I gave the example in #27628.

**Comment by sylvestre** [comment]
@dotdash I add the escape but it seems still unhappy. Does it ring a bell?

**Comment by dotdash** [comment]
The CHECK line in loads.rs has an extra % before the first i32, and the one in stores.rs works for me if I escape the asterisk. Here are the CHECK lines that work for me:

// CHECK: load {{(i32\*, )?}}i32** %x{{.*}}, !nonnull
// CHECK: [[VAR:%[0-9]+]] = load {{(\[4 x i8\]\*, )?}}[4 x i8]** %x

**Comment by dotdash** [comment]
Sorry for all the trouble!

**Comment by sylvestre** [comment]
no worries, I will fix that tomorrow

**Comment by dotdash** [comment]
Btw, if you want to run the test against a pre-built rustc (e.g. a nightly that was built against LLVM 3.7) instead of bootstrapping it all yourself, this should do:

    rustc --allow unused --crate-type=lib -Cno-prepopulate-passes --emit llvm-ir -o tmp.ll src/test/codegen/loads.rs && FileCheck-3.7 src/test/codegen/loads.rs < tmp.ll

If you don't get any output from that command, everything's fine.

Using FileCheck-3.6 should work just fine as well.

**Comment by sylvestre** [comment]
Looks like I pushed the wrong patch, sorry :/

**Comment by dotdash** [comment]
@bors r+ 0fdc4a8

Codegen tests already passed on Travis! Thanks a lot!

**Pull request merged**
