### PR TITLE
`replace_bound_vars` fast path: check predicates, don't check consts

### PR DESCRIPTION
**Pull request by lcnr**
split out from #98900

`ty::Const` doesn't have precomputed type flags, so
computing `has_vars_bound_at_or_above` for constants
requires us to visit the const and its contained types
and constants. A noop fold should be pretty much equally as
fast so removing it prevents us from walking the constant twice
in case it contains bound vars.

r? @jackh726

### CODE REVIEW

**Comment by lcnr** [comment]
@rust-timer build 986b0925e1a63333e182d460bda90013cc286a0c

**Comment by jackh726** [comment]
r=me with clean perf

**Pull request merged**
