### PR TITLE
Don't allow `const` to begin a nonterminal

### LINKED ISSUE #79908: regression 1.49: macro_rules unexpected tokens
Unclear on the extent to which these are the same problem:

* https://crater-reports.s3.amazonaws.com/beta-1.49-1/beta-2020-11-26/gh/ErickHdez96.tiger/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.49-1/beta-2020-11-26/reg/fourier-0.1.0/log.txt

cc @petrochenkov @Aaron1011

### PR DESCRIPTION
**Pull request by camelid**
Fixes #79908.

Thanks to Vadim Petrochenkov who [told me what the fix was][z]!

[z]: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/finding.20which.20macro.20rule.20to.20use/near/220240422

r? @petrochenkov

### CODE REVIEW

**Comment by camelid** [comment]
Beta-nominating because this fixes a P-critical regression from stable to beta.

**Comment by camelid** [comment]
Should this be p=1 because it fixes a P-critical regression?

**Comment by camelid** [comment]
Likewise, I don't think should be `rollup` because we want to be able to easily bisect in case this causes any issues.

**Comment by petrochenkov** [comment]
Ok, looks like the questions above already resolved themselves without my involvement.

**Comment by camelid** [comment]
Oh well :)

**Pull request merged**
