### PR TITLE
Add a default implementation for CodegenBackend::link

### PR DESCRIPTION
**Pull request by bjorn3**
As a side effect this should add raw-dylib support to cg_gcc as the default ArchiveBuilderBuilder that is used implements create_dll_import_lib. I haven't tested if the raw-dylib support actually works however.

### CODE REVIEW

**Comment by antoyo** [comment]
Does this still allow overwriting the linking step in the different codegens?

I sometimes stumble upon cases where I need to adjust the linking for rustc_codegen_gcc.

**Comment by bjorn3** [comment]
Yes, this only adds a default impl. The LLVM backend still overrides the link method as it uses a different archive writer that supports reading symbols for LLVM bitcode.

**Comment by jieyouxu** [comment]
r? jieyouxu

**Review by jieyouxu — APPROVED** [review]
Thanks. This adds a default impl that can be overridden, so this LGTM.

**Pull request merged**
