### PR TITLE
coherence: fix is_knowable logic

### LINKED ISSUE #43355: Overlap checking with downstream impl is insufficient w.r.t. fundamental types; causes ICE
Overlap checker [considers](https://github.com/rust-lang/rust/blob/1.18.0/src/librustc/traits/select.rs#L677-L681) possible downstream `impl`, but it is insufficient if it may contain fundamental types. May cause ICE.

```rust
#![crate_type = "lib"]
#![crate_name = "foo"]

pub trait Trait1<X> {
    type Output;
}
pub trait Trait2<X> {}

impl<X, T> Trait1<X> for T where T: Trait2<X> {
    type Output = ();
}
impl<X> Trait1<Box<X>> for A {
    type Output = i32;
}

pub struct A;

fn f<X, T: Trait1<Box<X>>>() {
    println!("k: {}", ::std::mem::size_of::<<T as Trait1<Box<X>>>::Output>());
}

pub fn g<X, T: Trait2<Box<X>>>() {
    f::<X, T>();
}
```

```rust
extern crate foo;

use foo::{Trait2, A, g};

struct B;

impl Trait2<Box<B>> for A {}

fn main() {
    g::<B, A>();
}
```

In stable (1.18.0), ICE is triggered when compiling downstream main.

```
$ rustc --version
rustc 1.18.0 (03fc9d622 2017-06-06)
$ cargo build
   Compiling foo v0.1.0 (file:///C:/Users/qnighy/workdir/orphan-test/foo)
   Compiling orphan-test v0.1.0 (file:///C:/Users/qnighy/workdir/orphan-test)
error: internal compiler error: src\librustc\infer\mod.rs:715: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { trait_ref: <foo::A as foo::Trait1<std::boxed::Box<B>>>, item_name: Output(445) }, _)),depth=1),Ambiguity)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:375
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `orphan-test`.

To learn more, run the command again with --verbose.
```

In nightly, ICE is triggered when compiling even upstream `foo`. Perhaps this is a different bug.

```
$ rustc +nightly --version
rustc 1.20.0-nightly (582af6e1a 2017-07-19)
$ cargo +nightly build
   Compiling foo v0.1.0 (file:///C:/Users/qnighy/workdir/orphan-test/foo)
error: internal compiler error: src\librustc\infer\mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<T as std::marker::Sized>)),depth=1),Unimplemented), FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<T as Trait2<std::boxed::Box<X>>>)),depth=1),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (582af6e1a 2017-07-19) running on x86_64-pc-windows-msvc

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:437:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `foo`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by arielb1**
A trait-ref that passes the orphan-check rules can still be implemented in a crate downstream from our crate (for example, `LocalType for LocalTrait<_>` might be matched by a `LocalType for LocalTrait<TypeFromDownstreamCrate>`), and this should be known by the `is_knowable`  logic.

Trait selection had a hackfix for this, but it's an hacky fix that does not handle all cases. This patch removes it.

fixes #43355.

r? @nikomatsakis 

Needs a crater run

### CODE REVIEW

**Comment by aidanhs** [comment]
Crater run started.

**Comment by aidanhs** [comment]
Hi @arielb1 (crater requester), @nikomatsakis (reviewer)! Crater results are at: http://cargobomb-reports.s3.amazonaws.com/pr-46192/index.html. 'Blacklisted' crates (spurious failures etc) can be found [here](https://github.com/rust-lang-nursery/crater/blob/master/blacklist.md). If you see any spurious failures not on the list, please make a PR against that file.

(interested observers: Crater is a tool for testing the impact of changes on the crates.io ecosystem. You can find out more at the [repo](https://github.com/rust-lang-nursery/crater/) if you're curious)

**Comment by arielb1** [comment]
Regressions:

## crossbeam-epoch-0.1.0 & bow-1.0.3 (yay I broke Servo, but this is no longer a dependency)

```
impl<T> Into<Box<T>> for Owned<T>
 = note: conflicting implementation in crate `core`:
 - impl<T, U> core::convert::Into<U> for T
   where U: core::convert::From<T>;
```

This is a problem because any joker can write this (on nightly, but some variants are probably possible using `#[fundamental]` traits on stable - e.g. if `Bow` implemented `FnOnce`):
```Rust
#![feature(optin_builtin_traits)]

pub struct Foo;
pub auto trait Xyz {}
impl !Xyz for Foo {}
impl !Xyz for Box<Foo> {}

impl<T: Xyz> From<T> for Box<Foo> {
    fn from(_: T) -> Self { Box::new(Foo) }
}

fn main() {
    let _foo = <Box<Foo>>::from(());
}
```

Which would cause a coherence conflict on linking for the trait-ref `<Owned<Foo> as Into<Box<Foo>>>`. This is a link-safety issue, so the impl must not be allowed.

I think the only fix is to not use `Into` but instead use an `into_box` function.

## glib v0.1.3

```
impl<'a, T: ?Sized + SetValue> SetValue for &'a T {
impl<T: IsA<Object>> SetValue for T {
```

This causes a conflict because downstream crates can implement `IsA<Object>` for both `T` and `&T`, unless we check this impl in every downstream crate.

The crate author had actually encountered some other coherence problems with this approach, and removed this in a new version of their crate: https://github.com/gtk-rs/glib/commit/b36de4e9c38fb7be534fb7f17ec9eae3b2d3cd26#diff-dd26c2766e65aca43e4228e64ebd0cf8

I don't see any crates depending on `glib 0.1.3` itself.

## ocl v0.15.0 
## rusqlite v0.10.3
## rusqlcipher v0.14.6

This is basically the same issue as `glib` - attempt to implement a trait for both `T: Trait` and `&T where T: Trait`.

```Rust
impl<'a, E> From<E> for EventArray where E: Into<Event>
impl<'a, E> From<&'a E> for EventArray where E: Into<Event> + Clone
```
```
impl<'a, T: ?Sized> From<&'a T> for ToSqlOutput<'a> where &'a T: Into<ValueRef<'a>>
impl<'a, T: Into<Value>> From<T> for ToSqlOutput<'a>
```

This is still an issue in the newest crate version, probably need to talk with the crate authors 
- [ ] @jgallagher (rusqlite & rusqlcipher) - https://github.com/jgallagher/rusqlite/issues/313
- [ ] @cogciprocate (ocl) - ?

## lru-disk-cache v0.1.0 (aka sccache)

```
impl<K, V> CountableMeter<K, V> for Count {
impl<K, V, T: Meter<K, V, Measure=usize>> CountableMeter<K, V> for T {
```

This is a conflict because coherence can't see that `<Count as Meter<K, V>>::Measure = ()` can't coexist with `<Count as Meter<K, V>>::Measure = usize`.

This can be fixed by the crate author by breaking the associated type to a type parameter:
```Rust
use std::borrow::Borrow;
/// A trait for measuring the size of a cache entry.
///
/// If you implement this trait, you should use `usize` as the `Measure` type, otherwise you will
/// also have to implement [`CountableMeter`][countablemeter].
///
/// [countablemeter]: trait.Meter.html
pub trait Meter<K, V> {
    /// The type used to store measurements.
    type Measure: Default + Copy;
    /// Calculate the size of `key` and `value`.
    fn measure<Q: ?Sized>(&self, key: &Q, value: &V) -> Self::Measure
        where K: Borrow<Q>;
}

/// Size limit based on a simple count of cache items.
pub struct Count;

impl<K, V> Meter<K, V> for Count {
   /// Don't store anything, the measurement can be derived from the map.
    type Measure = ();

    /// Don't actually count anything either.
    fn measure<Q: ?Sized>(&self, _: &Q, _: &V) -> ()
        where K: Borrow<Q>
    {}
}

/// A trait to allow the default `Count` measurement to not store an
/// extraneous counter.
pub trait CountableMeter<K, V>: Meter<K, V> {
    /// Add `amount` to `current` and return the sum.
    fn add(&self, current: Self::Measure, amount: Self::Measure) -> Self::Measure;
    /// Subtract `amount` from `current` and return the difference.
    fn sub(&self, current: Self::Measure, amount: Self::Measure) -> Self::Measure;
    /// Return `current` as a `usize` if possible, otherwise return `None`.
    ///
    /// If this method returns `None` the cache will use the number of cache entries as
    /// its size.
    fn size(&self, current: Self::Measure) -> Option<usize>;
}

/// `Count` is all no-ops, the number of entries in the map is the size.
impl<K, V, T: Meter<K, V>> CountableMeter<K, V> for T
    where T: CountableMeterWithMeasure<K, V, <T as Meter<K, V>>::Measure>
{

    fn add(&self, current: Self::Measure, amount: Self::Measure) -> Self::Measure {
        CountableMeterWithMeasure::add(self, current, amount)
    }
    
    fn sub(&self, current: Self::Measure, amount: Self::Measure) -> Self::Measure {
        CountableMeterWithMeasure::sub(self, current, amount)
    }

    fn size(&self, current: Self::Measure) -> Option<usize> {
        CountableMeterWithMeasure::size(self, current)
    }
}


pub trait CountableMeterWithMeasure<K, V, M> {
    /// Add `amount` to `current` and return the sum.
    fn add(&self, current: M, amount: M) -> M;
    /// Subtract `amount` from `current` and return the difference.
    fn sub(&self, current: M, amount: M) -> M;
    /// Return `current` as a `usize` if possible, otherwise return `None`.
    ///
    /// If this method returns `None` the cache will use the number of cache entries as
    /// its size.
    fn size(&self, current: M) -> Option<usize>;
}


/// For any other `Meter` with `Measure=usize`, just do the simple math.
impl<K, V, T> CountableMeterWithMeasure<K, V, usize> for T {
    fn add(&self, current: usize, amount: usize) -> usize {
        current + amount
    }
    fn sub(&self, current: usize, amount: usize) -> usize {
        current - amount
    }
    fn size(&self, current: usize) -> Option<usize> { Some(current) }
}

impl<K, V> CountableMeterWithMeasure<K, V, ()> for Count {
    fn add(&self, current: (), amount: ()) {}
    fn sub(&self, current: (), amount: ()) {}
    fn size(&self, current: ()) -> Option<usize> { None }
}
fn main() {}
```

**Review by nikomatsakis — APPROVED** [review]
Left a few documentation nits.

**Comment by arielb1** [comment]
Yea this only issues warnings. I'll land this.

**Comment by luser** [comment]
I pushed a fix to lru-disk-cache in sccache, thanks for providing working code!
https://github.com/mozilla/sccache/commit/d14852991d39edccf4bc91f04577fcdf393de430

**Comment by kennytm** [comment]
@bors retry #44159

```
ERROR:  Could not find a valid gem 'aws-sdk-resources' (= 2.10.97) in any repository
```

**Pull request merged**
