### PR TITLE
Make causal tracking lazy

### LINKED ISSUE #51710: [nll] make causal tracking lazy
Analyzing profiles on my latest branch, it appears that approximately 4% of total compilation time is spent managing the "causal hash map":

https://github.com/rust-lang/rust/blob/01dbfdaf4f45b68b49332b8785262a3a780d0a19/src/librustc_mir/borrow_check/nll/region_infer/values.rs#L187-L191

Currently, that map is only non-None for the "liveness" set, which stores, for each region variable R, each point P where R is **directly** live (meaning typically that there is some local variable X that has R in its type and which may be used at some point Q reachable from P). The "cause" tracks basically this point Q. It's accessed later when constructing error messages, here:

https://github.com/rust-lang/rust/blob/01dbfdaf4f45b68b49332b8785262a3a780d0a19/src/librustc_mir/borrow_check/nll/region_infer/mod.rs#L1067-L1068

We should remove the causal hashmap altogether. Instead, when constructing an error, we can do a BFS over the MIR graph from `elem` (a `Location`), looking for points that may use the region `region_sub` that we are interested in.

### PR DESCRIPTION
**Pull request by spastorino**
Closes #51710

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @Mark-Simulacrum — once this try build is done, would be great to get perf results

**Comment by nikomatsakis** [comment]
cc @Mark-Simulacrum ok, bors try is done, perf run please :D

**Comment by nikomatsakis** [comment]
r=me but I'd like to see a perf run first

**Comment by Mark-Simulacrum** [comment]
I think I forgot to leave a comment -- https://perf.rust-lang.org/compare.html?start=57dd722606028cafde656a66edc3206b82cd3bab&end=f3375ed0f41c0e04b61e51e54df12456d7a57bbf&stat=instructions%3Au is done.

Since perf is positive across the board, @bors r=nikomatsakis

**Comment by pnkfelix** [comment]
Didn't this PR partially regress the diagnostic quality of the test for #47646 ? I'm referring in particular to this: 

https://github.com/rust-lang/rust/commit/0957ede5027c0bffe208904998675a17bfd4cd59#diff-46590a131be6d28cb3935ef7907f3ec4L6

**Pull request merged**
