### PR TITLE
Extended error message for mut borrow conflicts in loops

### PR DESCRIPTION
**Pull request by ivanbakel**
RFC issue: https://github.com/rust-lang/rfcs/issues/2080

The error message for multiple mutable borrows on the same value over loop iterations now makes it clear that the conflict comes from the borrow outlasting the loop. The wording of the error is based on the special case of the moved-value error for a value moved in a loop. Following the example of that error, the code remains the same for the special case.

This is mainly because I felt the current message is confusing in the loop case : https://github.com/rust-lang/rust/issues/43437. It's not clear that the two conflicting borrows are in different iterations of the loop, and instead it just looks like the compiler has an issue with a single line.

### CODE REVIEW

**Comment by estebank** [comment]
@ivanbakel This is great! Could you add a `ui` test that shows the two possible outputs affected by this PR?

**Comment by estebank** [comment]
r=me

**Comment by ivanbakel** [comment]
Sure. What are the two cases? All the current message tests still pass. Or should I write tests for the different kind of loops?

**Comment by estebank** [comment]
There should be at least two test cases, one that expects "first mutable borrow occurs here"/"second mutable borrow occurs here" to be displayed, and another that expects "mutable borrow starts here in previous iteration of loop". If in the test you can add you also add one case for each possible loop type (`loop`/`while`/`for`), that'd be icing in the cake.

**Comment by ivanbakel** [comment]
Alright, the tests are added. Do I have to do something else as well as just writing the files? They run on my machine using `./x.py test'.

**Comment by estebank** [comment]
Now we just wait for travis to finish so we can make sure there're no regressions in other platforms.

**Pull request merged**
