### PR TITLE
rustc: Remove platform intrinsics crate

### PR DESCRIPTION
**Pull request by alexcrichton**
This was originally attempted in #57048 but it was realized that we
could fully remove the crate via the `"unadjusted"` ABI on intrinsics.
This means that all intrinsics in stdsimd are implemented directly
against LLVM rather than using the abstraction layer provided here. That
ends up meaning that this crate is no longer used at all.

This crate developed long ago to implement the SIMD intrinsics, but we
didn't end up using it in the long run. In that case let's remove it!

### CODE REVIEW

**Comment by nagisa** [comment]
cc @rust-lang/compiler just so it does not go through without anybody noticing.

@bors r+

**Comment by Centril** [comment]
@bors p=9

Raising prio since this PR is too big to be included into any rollup.

**Comment by alexcrichton** [comment]
@bors: retry

* yielding priority to stabl erelease

**Comment by eddyb** [comment]
It's really sad to me that we've made this step backwards from a somewhat-declarative notion of platform intrinsics to hardcoding LLVM's particular interface to them.

`stdsimd` *should have never* been developed out-of-tree, the only reason it *had to be* reflects major issues with the general development process of the Rust project, particularly its (low) speed, in both local builds and merging changes. Some are alleviated by incremental compilation, but it's overall still quite suboptimal.

RLS, to some extent, also suffers from similar effects, but it doesn't directly feed back into the language itself, like `stdsimd` does, so its main impact is on the compiler architecture (or lack thereof).

cc @rust-lang/compiler @rust-lang/core 
What is the best venue to discuss such large-scale process issues and develop policies regarding approaches to solving problems that span the library/compiler/backend stack?
We should at least put this on the All Hands agenda.

**Pull request merged**
