### PR TITLE
Remove the unused-`#[doc(hidden)]` logic from the `unused_attributes` lint

### LINKED ISSUE #96890: False positive unused_attributes lint on doc(hidden) attribute on associated type
The warning added by #96008 claims that `doc(hidden)` on an impl item is ignored by rustdoc, but it isn't necessarily.

The warning says:

> whether the impl item is \`doc(hidden)\` or not entirely depends on the corresponding trait item

which is not true in the following repro:

```rust
pub trait Trait {
    type A;
    type B;
}

pub struct Struct;

impl Trait for Struct {
    type A = [(); "interesting type".len()];
    #[doc(hidden)]
    type B = [(); "nasty uninteresting type".len()];
}
```

```console
$ cargo check
warning: `#[doc(hidden)]` is ignored on trait impl items
  --> src/lib.rs:10:5
   |
10 |     #[doc(hidden)]
   |     ^^^^^^^^^^^^^^ help: remove this attribute
   |
   = note: `#[warn(unused_attributes)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: whether the impl item is `doc(hidden)` or not entirely depends on the corresponding trait item
```

This warning is a false positive. Rustdoc **does** pay attention to this attribute. For the code above, the rendered documentation of `Struct` and `Trait` looks like:

<table><tr><td></td><td></td></tr></table>

After removing the supposedly unused `doc(hidden)` attribute and rendering again, the "nasty uninteresting type" that we wanted not shown is going to get rendered on both pages:

<table><tr><td></td><td></td></tr></table>

(@fmease @lcnr)

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (88860d547 2022-05-09)
binary: rustc
commit-hash: 88860d5474a32f507dde8fba8df35fd2064f11b9
commit-date: 2022-05-09
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

### PR DESCRIPTION
**Pull request by fmease**
Fixes #96890.

It was found out that `#[doc(hidden)]` on trait impl items does indeed have an effect on the generated documentation (see the linked issue). In my opinion and the one of [others](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Validy.20checks.20for.20.60.23.5Bdoc.28hidden.29.5D.60/near/281846219), rustdoc's output is actually a bit flawed in that regard but that should be tracked in a new issue I suppose (I will open an issue for that in the near future).

The check was introduced in #96008 which is marked to be part of version `1.62` (current `beta`). As far as I understand, this means that **this PR needs to be backported** to `beta` to fix #96890 on time. Correct me if I am wrong.

CC @dtolnay (in case you would like to agree or disagree with my decision to fully remove this check)

@rustbot label A-lint T-compiler T-rustdoc

r? @rust-lang/compiler

### CODE REVIEW

**Comment by compiler-errors** [comment]
cc @GuillaumeGomez @lcnr who approved the original PR that added this lint.
cc @rust-lang/lang, specifically @scottmcm who [unofficially signed off on this](https://github.com/rust-lang/rust/pull/96008#issuecomment-1117690215).

nominating for backport consideration

**Comment by GuillaumeGomez** [comment]
Isn't it possible to fix the issues rather than entirely removing the check? It provides useful information after all...

**Comment by compiler-errors** [comment]
imo, @fmease can reintroduce this logic in a couple weeks in nightly 1.64, so that it can have plenty of time to surface issues.

**Comment by GuillaumeGomez** [comment]
Fair enough. Let's approve this revert for the time being even though it makes me sad. Let's hope the upgraded version will soon follow. :)

@bors r+

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-06-23/near/287195257)

@rustbot label +beta-accepted

**Pull request merged**
