### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #97709 (Normalize consts' tys when relating with `adt_const_params`)
 - #97875 (Remove the `infer_static_outlives_requirements` feature)
 - #97960 (interpret: unify offset_from check with offset check)
 - #97999 (Make `type_changing_struct_update` no longer an incomplete feature)
 - #98043 (Remove unnecessary `to_string` and `String::new`)
 - #98044 ([issues:97981] del unrelated comment)
 - #98049 (Document an edge case of `str::split_once`)
 - #98057 (Update miri)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=97709,97875,97960,97999,98043,98044,98049,98057)

### CODE REVIEW

**Comment by klensy** [comment]
Something wrong with GH runners? Jobs cancelled few times in rollups without exact errors (`GitHub Actions has encountered an internal error when running your job.`)

**Comment by matthiaskrgr** [comment]
mh wtf

**Comment by matthiaskrgr** [comment]
maybe more luck with https://github.com/rust-lang/rust/pull/98066

**Pull request closed without merging**
