### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by JohnTitor**
Successful merges:

 - #105806 (Support eager subdiagnostics again)
 - #106397 (Check `impl`'s `where` clauses in `consider_impl_candidate` in experimental solver)
 - #106503 (Do not filter substs in `remap_generic_params_to_declaration_params`.)
 - #106532 (Allow codegen to unsize `dyn*` to `dyn`)
 - #106570 (add tests for div_duration_* functions)
 - #106635 (std sync tests: better type name, clarifying comment)
 - #106653 (Fix help docs for -Zallow-features)
 - #106657 (Remove myself from rust-lang/rust reviewers)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=105806,106397,106503,106532,106570,106635,106653,106657)

### CODE REVIEW

**Comment by JohnTitor** [comment]
Seems this spurious failure happens continuously, on other PRs as well: https://github.com/rust-lang/rust/pull/101138#issuecomment-1377111489, https://github.com/rust-lang/rust/pull/106660#issuecomment-1377016303
@bors treeclosed=50

**Comment by JohnTitor** [comment]
#106680 should fix the issue, let's reopen the tree,
@bors treeclosed-

**Comment by JohnTitor** [comment]
@bors treeclosed=50
Seems we encountered another failure: https://github.com/rust-lang/rust/pull/106680#issuecomment-1377379761

**Comment by jyn514** [comment]
@JohnTitor please use a higher priority for treeclosed in the future - I accidentally set https://github.com/rust-lang/rust/pull/106458 to be merged before Pietro's PR fixing CI because I didn't know there were CI issues.

**Comment by JohnTitor** [comment]
@bors retry r-
Yielding #106708

**Pull request closed without merging**
