### PR TITLE
README.md: Remove prompts from code blocks

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/rust-lang/rust/issues/76863

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]

**Review by pickfire — COMMENTED** [review]
I don't have much opinion on this but I believe it is there for a reason and I prefer the way it is currently to be clearer (`$` for unix sh and `>` for msvc).

**Comment by qlcom** [comment]
> (`$` for unix sh and `>` for msvc).

`$` doesn't mean unix `sh`. I can put anything in want in prompt.

**Comment by pickfire** [comment]
> $ doesn't mean unix sh. I can put anything in want in prompt.

That's correct, fish could be `>` but `$` usually mean a normal shell and `#` for a root shell. I just mean the normal unix shell you will see is `$`.

**Comment by pickfire** [comment]
@qlcom Ah, you don't need to close it if you think it is good. If you think the change is better, you can ask the docs team to review, I am not from any team and just discussing this from my viewpoint.

**Comment by Mark-Simulacrum** [comment]
I personally find these really annoying when trying to copy/paste because you have to carefully not select them, so I think this is a win.

@bors r+ rollup

**Comment by pickfire** [comment]
@Mark-Simulacrum Note that one line here are not being able to copy paste without human intervention like
```sh
    pacman -Sy pacman-mirrors
    ...
```
If users happened to copy paste
```sh

   # Update package mirrors (may be needed if you have a fresh install of MSYS2)
   pacman -Sy pacman-mirrors

   # Install build tools needed for Rust. If you're building a 32-bit compiler,
   # then replace "x86_64" below with "i686". If you've already got git, python,
   # or CMake installed and in PATH you can remove them from this list. Note
   # that it is important that you do **not** use the 'python2', 'cmake' and 'ninja'
   # packages from the 'msys2' subsystem. The build has historically been known
   # to fail with these packages.
   pacman -S git \
               make \
               diffutils \
               tar \
               mingw-w64-x86_64-python \
               mingw-w64-x86_64-cmake \
               mingw-w64-x86_64-gcc \
               mingw-w64-x86_64-ninja
```
If they copy pasted the whole thing it would not work.

**Comment by Mark-Simulacrum** [comment]
Right, but selecting the single-line statements is still much easier (for me) without the prefix, which IMO doesn't add much value.

**Comment by qlcom** [comment]
> @Mark-Simulacrum Note that one line here is not being able to copy paste without human intervention like
> 
> ```shell
>     pacman -Sy pacman-mirrors
>     ...
> ```
> 
> If users happened to copy paste
> 
> ```shell
>    # Update package mirrors (may be needed if you have a fresh install of MSYS2)
>    pacman -Sy pacman-mirrors
> 
>    # Install build tools needed for Rust. If you're building a 32-bit compiler,
>    # then replace "x86_64" below with "i686". If you've already got git, python,
>    # or CMake installed and in PATH you can remove them from this list. Note
>    # that it is important that you do **not** use the 'python2', 'cmake' and 'ninja'
>    # packages from the 'msys2' subsystem. The build has historically been known
>    # to fail with these packages.
>    pacman -S git \
>                make \
>                diffutils \
>                tar \
>                mingw-w64-x86_64-python \
>                mingw-w64-x86_64-cmake \
>                mingw-w64-x86_64-gcc \
>                mingw-w64-x86_64-ninja
> ```
> 
> If they copy pasted the whole thing it would not work.

on which shell?

**Comment by Mark-Simulacrum** [comment]
@qlcom Did you intentionally close this? I continue to feel that it should be merged.

**Comment by qlcom** [comment]
why does it need to run CI server to merge a pull request which changes a markdown file?

**Comment by Mark-Simulacrum** [comment]
Everything that lands into Rust master needs to pass CI, currently we do not try to optimize for "definitely green" changes because that's error-prone and might cause failures if humans are in that loop. This'll get merged soon, though, it just needs to work its way through the queue: https://bors.rust-lang.org/homu/queue/rust

**Comment by hbina** [comment]
AFAIK there's a similar discussion in rustc-dev-guide here https://github.com/rust-lang/rustc-dev-guide/pull/460

**Pull request merged**
