### PR TITLE
`s/compiler-flags/compile-flags` in compiletest

### PR DESCRIPTION
**Pull request by compiler-errors**
Also make compiletest panic so this doesn't happen in the future! I literally always forget which it's called, so I wanted to make my life easier in the future.

Also open to the possibility of parsing both.

### CODE REVIEW

**Comment by compiler-errors** [comment]
@Mark-Simulacrum, sure, denying `// name: value` you mean? If so, can do

**Comment by Mark-Simulacrum** [comment]
Yeah, essentially -- my hope is that there's not too many false positives (maybe we can ignore some specific names to avoid common false positives if needed).

**Comment by compiler-errors** [comment]
I can try this.

@rustbot author

**Comment by JohnCSimon** [comment]
@compiler-errors 
Ping from triage: Can you please post the status of this PR? 
Thank you.

**Comment by compiler-errors** [comment]
Ah, yeah, have kinda ignored this. I will work on it this week!

**Comment by compiler-errors** [comment]
Hm, probably won't get around to fixing this in the general case. @Mark-Simulacrum, can we merge this as-is? Otherwise I'll just close this.

@rustbot ready

**Comment by Mark-Simulacrum** [comment]
I'm fine with merging as-is.

@bors r+

**Pull request merged**
