### PR TITLE
Update error E0035 and E0036 #35206 #35207

### PR DESCRIPTION
**Pull request by neilzxu**
Part of #35233 
Addresses #35207 #35206 

I got

```
test result: ok. 2443 passed; 0 failed; 13 ignored; 0 measured
```

from running:

```
 python src/bootstrap/bootstrap.py --step check-cfail --stage 1
```

so I didn't update any tests.

r? @jonathandturner”

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR!

There's a quirk in the test system where it doesn't check the labels if there aren't any in the test.  I talk about the quirk some in the Extra Credit section of the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html).  Please update the tests so that it's testing the new labels.  With that, we'll be ready.

**Comment by neilzxu** [comment]
@jonathandturner Alright, updated tests!

**Comment by jonathandturner** [comment]
Looks like it's almost there!  Nice.  A couple last comments:

1) can we [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the 3 commits down to 1?
2) I should have mentioned this in my issue, but we might want to slightly change the label wording.  For example, if we pass 1 and it expects 2, it will say:

```
Passed 1 type arguments, expected 2
```

Can we make that:

```
Passed 1 type argument(s), expected 2
```

Or, alternatively, you could check the number of parameters yourself.  Either way works with me.

With these fixed I think we'll be good.

**Comment by jonathandturner** [comment]
Looks like you'll need to update to satisfy `tidy`.

```
/build/src/librustc_typeck/check/method/confirm.rs:321: line longer than 100 chars

thread 'main' panicked at 'some tidy checks failed', /build/src/tools/tidy/src/main.rs:53
```

You can run `tidy` with:

```
http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html
```

**Comment by GuillaumeGomez** [comment]
Fixed by another PR.

**Pull request closed without merging**
