### PR TITLE
Polonius: fix some cases of `killed` fact generation, and most of the `ui` test suite

### PR DESCRIPTION
**Pull request by lqd**
Since basic Polonius functionality was re-enabled by @matthewjasper in #54468, some tests were still failing in the polonius compare-mode.

This PR fixes all but one test in the `ui` suite by:
- fixing some bugs in the fact generation code, related to the `killed` relation: Polonius would incorrectly reject some NLL-accepted code, because of these missing `killed` facts.
- ignoring some tests in the polonius compare-mode: a lot of those manually test the NLL or migrate mode, and the failures were mostly artifacts of the test revisions, e.g. that `-Z polonius` requires full NLLs. Some others were also both failing with NLL and succeeding with Polonius, which we can't encode in tests at the moment.
- blessing the output of some tests: whenever Polonius and NLL have basically the same errors, except for diagnostics differences, the Polonius output is blessed. Whenever we've advanced into a less experimental phase, we'll want to revisit these cases (much like we did on the NLL test suite last year) to specifically work on diagnostics.

Fact generation changes:
- we now kill loans on the destination place of `Call` terminators
- we now kill loans on the locals destroyed by `StorageDead` 
- we now also handle assignments to projections: killing the loans on a either a deref-ed local, or the ones whose `borrowed_place` conflicts with the current place.

One failing test remains: an overflow during fact generation, on a case of polymorphic recursion (and which I'll continue investigating later).

This adds some tests for the fact generation changes, with some simple Polonius cases similar to the existing smoke tests, but also for some cases encountered in the wild (in the `rand` crate for example).

A more detailed write-up is available [here](https://hackmd.io/CjYB0fs4Q9CweyeTdKWyEg?view) with an explanation for each test failure, the steps taken to resolve it (as a commit in the current PR), NLL and Polonius outputs (and diff), etc.

Since they've worked on this before, and we've discussed some of these failures together:

r? @matthewjasper

### CODE REVIEW

**Comment by matthewjasper** [comment]
@bors r+ 
At some point we'll probably want to have CI running these tests cc @rust-lang/infra

**Comment by lqd** [comment]
Looks like a network issue
```
2019-07-20T12:18:08.1142326Z error: failed to download from `https://crates.io/api/v1/crates/bitflags/1.0.3/download`
2019-07-20T12:18:08.1142895Z 
2019-07-20T12:18:08.1143134Z Caused by:
2019-07-20T12:18:08.1143339Z   [35] SSL connect error (OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crates.io:443 )
2019-07-20T12:18:08.1164594Z thread 'main' panicked at 'tests failed for https://github.com/servo/webrender', src/tools/cargotest/main.rs:88:9
```

@bors retry

**Comment by lqd** [comment]
Thanks to @oli-obk for the information about the Place 2.0 changes for the rebase.

@bors r=matthewjasper rollup

**Pull request merged**
