### PR TITLE
Batch up libsyntax breaking changes

### PR DESCRIPTION
**Pull request by jseyfried**
Batch of the following syntax-[breaking-change] changes:
- #34213: Add a variant `Macro` to `TraitItemKind`
- #34368: Merge the variant `QPath` of `PatKind` into the variant `PatKind::Path`
- #34385: Move `syntax::ast::TokenTree` into a new module `syntax::tokenstream`
- #33943:
  - Remove the type parameter from `visit::Visitor`
  - Remove `attr::WithAttrs` -- use `attr::HasAttrs` instead.
  - Change `fold_tt`/`fold_tts` to take token trees by value and avoid wrapping token trees in `Rc`.
  - Remove the field `ctxt` of `ast::Mac_`
  - Remove inherent method `attrs()` of types -- use the method `attrs` of `HasAttrs` instead.
- #34316:
  - Remove `ast::Decl`/`ast::DeclKind` and add variants `Local` and `Item` to `StmtKind`.
  - Move the node id for statements from the `StmtKind` variants to a field of `Stmt` (making `Stmt` a struct instead of an alias for `Spanned<StmtKind>`)
  - Rename `ast::ExprKind::Again` to `Continue`.
- #34339: Generalize and abstract `ThinAttributes` to `ThinVec<Attribute>`
  - Use `.into()` in convert between `Vec<Attribute>` and `ThinVec<Attribute>`
  - Use autoderef instead of `.as_attr_slice()`
- #34436: Remove the optional expression from `ast::Block` and instead use a `StmtKind::Expr` at the end of the statement list.
- #34403: Move errors into a separate crate (unlikely to cause breakage)

### CODE REVIEW

**Comment by jseyfried** [comment]
Pending #34403 (cc @jonathandturner)

**Comment by Manishearth** [comment]
I prefer having reviewer info stick around in the merge commit somehow. I have a process for this 😄

**Comment by Manishearth** [comment]
you may also find this git alias useful for future stuff: `fetchpr = !sh -c 'git fetch $1 pull/$2/head:pr-$2' -`

**Comment by jseyfried** [comment]
Ok, didn't mean to disrupt your process. There were a *lot* of merge conflicts, mostly from my PRs, so I figured I'd take care of them. If you'd like to integrate that work from the branch into your process, feel free :)

**Comment by Manishearth** [comment]
Nah, it's fine. I'm okay with others doing it, just leave the reviewer info and PR text in there somehow. Especially if you've already fixed merge conflicts.

Could you use `git rebase master --preserve-merges` and just edit the commit text of the merge commits? I have code that does this already, basically a `mergerollup` command in bash:

```bash
mergerollup() {
 echo "Merging $@"
 git branch -D current
 git fetch origin pull/$2/head:current
 NL="

"
 A=$(wget -O - https://api.github.com/repos/rust-lang/rust/pulls/$2 -q| grep "\"body\":"| sed  's/^  "body": "//'|sed 's/",$//'| sed 's/\\n/\n/g' | sed 's/\\r//g')

 git merge --no-ff current -m "Rollup merge of #$2 - $1, r=$3 $NL $A";
 git mergetool
}
```

which can be run using the code in https://github.com/rust-lang/rust/issues/31645#issuecomment-226436661

**Comment by jseyfried** [comment]
Will do.

**Comment by arielb1** [comment]
```
--- /Users/rustbuild/src/rust-buildbot/slave/try-mac/build/obj/x86_64-apple-darwin/test/run-make/pretty-expanded-hygiene.stage2-x86_64-apple-darwin/input.out.replaced	2016-06-25 11:38:14.000000000 -0400
+++ /Users/rustbuild/src/rust-buildbot/slave/try-mac/build/obj/x86_64-apple-darwin/test/run-make/pretty-expanded-hygiene.stage2-x86_64-apple-darwin/input.pp.rs	2016-06-25 11:38:14.000000000 -0400
@@ -13,6 +13,6 @@
 #![no_core]
 
 
-fn bar /* Sat Jun 25 11:38:14 EDT 2016 */() { let x /* Sat Jun 25 11:38:14 EDT 2016 */ = 1 y /* Sat Jun 25 11:38:14 EDT 2016 */ + x /* Sat Jun 25 11:38:14 EDT 2016 */ }
+fn bar /* Sat Jun 25 11:38:14 EDT 2016 */() { let x /* Sat Jun 25 11:38:14 EDT 2016 */ = 1; y /* Sat Jun 25 11:38:14 EDT 2016 */ + x /* Sat Jun 25 11:38:14 EDT 2016 */ }
 
 fn y /* Sat Jun 25 11:38:14 EDT 2016 */() { }

------------------------------------------
stderr:
```

**Comment by jseyfried** [comment]
@Manishearth 
Bors try is taking forever but otherwise this is ready to land (it's passing travis and my local build).
I added a summary of the changes in this batch to the initial comment.

**Comment by Manishearth** [comment]
@dtolnay @erickt @sgrif @sfackler @mystor @llogiq this will be landing in a day or two, fyi

**Comment by jonathandturner** [comment]
Not quite sure how try works but looking at the status, it's all green for the "try" runs at the bottom: http://buildbot.rust-lang.org/grid

**Comment by Manishearth** [comment]
looks like homu borked something. Alright, r=me in a day

**Comment by jseyfried** [comment]
Ok, here goes... @bors r=manishearth

**Comment by jonathandturner** [comment]
@jseyfried - does it rerun the test of it timed out?

**Comment by jseyfried** [comment]
@bors r=Manishearth
(Capital M)

**Comment by jseyfried** [comment]
@jonathandturner looks like it doesn't.

**Comment by jonathandturner** [comment]
@jseyfried - thanks :)

**Comment by dtolnay** [comment]
That top comment is really helpful, thanks @jseyfried.

**Pull request merged**
