### PR TITLE
Inline derived `hash`

### PR DESCRIPTION
**Pull request by nnethercote**
Because most of the other derived functions are inlined: `clone`, `default`, `eq`, `partial_cmp`, `cmp`. The exception is `fmt`, but it tends to not be on hot paths as much.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
Looks to be a slight perf win, and the added consistency is good.

r? @lqd

**Comment by lqd** [comment]
This makes sense to me, and could likely be a codegen improvement in runtime benchmarks (some of which it seems we're seeing in rustc's check builds).

I'm not sure why inlining impacts ctfe-stress-5 here per se, and cg attributes it to `<rustc_middle::ty::context::TyCtxt>::try_subst_and_normalize_erasing_regions::<rustc_middle::mir::ConstantKind>`. I don't know if you wanted to investigate this more even if it's a secondary benchmark, or if the wins outweighing the losses is enough. 

Some of the other regressions (e.g. on diesel) look like the usual obligations/folding processing code inlining shuffle.

Otherwise, r=me.

**Comment by nnethercote** [comment]
Lots of small perf changes, but the improvement slightly outweigh the regressions.

@rustbot label: +perf-regression-triaged

**Pull request merged**
