### PR TITLE
rustbuild: Stop building docs for std dependancies

### PR DESCRIPTION
**Pull request by ollie27**
Fixes: #38319

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by alexcrichton** [comment]
@bors: p=1

(beta nominated)

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/31657

**Comment by Manishearth** [comment]
Shouldn't this only apply in the --enable-compiler-docs case?

**Pull request merged**
