### PR TITLE
Remove use of 'just' in trpl/installing-rust.md

### PR DESCRIPTION
**Pull request by varjmes**
The beginning of the work that needs to be done as part of #28835.

:sunny:

### CODE REVIEW

**Comment by steveklabnik** [comment]
Looks great! Thanks so much.

**Comment by Charlotteis** [comment]
Wow that was easy! Thanks @steveklabnik. Will do further "just" removal slowly over time, when I find the time to actually go through the tutorial again like I want to!

**Comment by steveklabnik** [comment]
Great :+1:

**Pull request merged**
