### PR TITLE
Fix reference to 'librlibc' in libcore docs

### LINKED ISSUE #23059: libcore docs mention non-existing "librlibc"
The libcore/lib.rs file says

```
//! * `memcpy`, `memcmp`, `memset` - These are core memory routines which are
//!   often generated by LLVM. Additionally, this library can make explicit
//!   calls to these functions. Their signatures are the same as found in C.
//!   These functions are often provided by the system libc, but can also be
//!   provided by `librlibc` which is distributed with the standard rust
//!   distribution.
```

However, `find -iname "*rlibc*"` yields no result, both in the rust source folder and in the distributed tarball. So the part about this library being distributed with the standard distribution does not seem to apply anymore.

### PR DESCRIPTION
**Pull request by wesleywiser**
Fixes #23059

### CODE REVIEW

**Comment by brson** [comment]
@bors: rollup r+

Thanks!

**Comment by brson** [comment]
@barosl: not sure why bors is striking out his comments above.

**Comment by eddyb** [comment]
@barosl or what's up with the time travels - is @homu modifying its own comments? (the hash on the first struck out comment above is the one of the commit following it)

**Pull request merged**
