### PR TITLE
Explain why `&T` is cloned when `T` is not `Clone`

### LINKED ISSUE #95535: No hint about implementing clone on type mismatch when cloning reference
Given the following code:  https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ebe1fe6ca75fd88cba9aa3a77cb625bf

```rust
struct NotClone;

fn main() {
    clone_thing(&NotClone);
}

fn clone_thing(nc: &NotClone) -> NotClone {
    nc.clone()
}
```

The current output is:

```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:8:5
  |
7 | fn clone_thing(nc: &NotClone) -> NotClone {
  |                                  -------- expected `NotClone` because of return type
8 |     nc.clone()
  |     ^^^^^^^^^^ expected struct `NotClone`, found `&NotClone`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:8:5
  |
7 | fn clone_thing(nc: &NotClone) -> NotClone {
  |                                  -------- expected `NotClone` because of return type
8 |     nc.clone()
  |     ^^^^^^^^^^ expected struct `NotClone`, found `&NotClone`
  | note: `NotClone` does not implement clone, consider implementing it.

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #95535

### CODE REVIEW

**Comment by notriddle** [comment]
This seems like it’s redundant with the https://github.com/rust-lang/rust/blob/master/compiler/rustc_lint/src/noop_method_call.rs lint, which is disabled right now, but would accomplish the same thing.

Is it desirable to merge this, and then remove it later when the lint gets stabilized?

**Comment by compiler-errors** [comment]
@notriddle, given this code

```rust
#![warn(noop_method_call)]

struct PlainType<T>(T);

pub fn foo(non_clone_type_ref: &PlainType<u32>) -> PlainType<u32> {
    non_clone_type_ref.clone()
}
```

The suggestion I added fires, but the noop method call lint does not... I don't know very much about how late lints work, do you know if it only fires if typeck succeeds? If so, then it doesn't seem like we can deduplicate the logic here.

**Comment by notriddle** [comment]
It looks like it doesn’t run when there’s a type error, but this is a known issue, if I’m understanding https://github.com/rust-lang/rust/issues/91536 correctly.

**Comment by compiler-errors** [comment]
Interesting! Thanks for pointing that out. I may take a look at that issue..

**Comment by estebank** [comment]
@compiler-errors it's a long standing issue for lints that would help not triggering in the face of errors. It is also better (if more work) to consolidate useful information in the earliest possible error and avoid the later ones (or, as we do in some cases, keep information around from the first error, not emit it, and extend the later one).

**Comment by estebank** [comment]
r=me after rebase <3

**Pull request merged**
