### PR TITLE
Beta 20170928

### PR DESCRIPTION
**Pull request by nikomatsakis**
Backports of:

- Allow unused extern crate again #44825 
- macros: fix bug in collecting trait and impl items with derives. #44757 
-  `--cap-lints allow` switches off `can_emit_warnings` #44627 
-  Update the libc submodule #44116 
- limit and clear cache obligations opportunistically #44269 
- clear out projection subobligations after they are processed https://github.com/rust-lang/rust/pull/43999 
-  fix logic error in #44269's `prune_cache_value_obligations` #45065 
- REVERTS https://github.com/rust-lang/rust/pull/43543: Cleanup some remains of `hr_lifetime_in_assoc_type` compatibility lint:

### CODE REVIEW

**Comment by alexcrichton** [comment]
This may or may not fail due to weird build errors with the libc submodule. If it doesn't, then yay! If it does then this may need to backport https://github.com/rust-lang/rust/pull/44765. (I'm not sure if this was fast-forwarded enough to require that). Let's wait and see!

As one final point can you update the versoin in `src/bootstrap/channel.rs`? That way we'll publish a new beta as soon as this merges.

Other than that, r=me

@bors: p=1

**Comment by nikomatsakis** [comment]
@alexcrichton is that last commit what you had in mind?

**Comment by nikomatsakis** [comment]
if not, edit it yourself :)

**Comment by alexcrichton** [comment]
@bors: r+

Indeed!

**Comment by kennytm** [comment]
Legit.

```
[00:40:45] ---- [run-pass] run-pass/issue-43132.rs stdout ----
[00:40:45] 	
[00:40:45] error: compilation failed!
[00:40:45] status: exit code: 101
[00:40:45] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass/issue-43132.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/issue-43132.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/issue-43132.stage2-x86_64-unknown-linux-gnu.run-pass.libaux"
[00:40:45] stdout:
[00:40:45] ------------------------------------------
[00:40:45] 
[00:40:45] ------------------------------------------
[00:40:45] stderr:
[00:40:45] ------------------------------------------
[00:40:45] error: internal compiler error: /checkout/src/librustc_trans/context.rs:694: failed to get layout for `*mut MaybeDone<(Forward<(std::boxed::Box<Future<Error=u32>>,)>, [closure@/checkout/src/test/run-pass/issue-43132.rs:20:15: 20:21])>`: the type `MaybeDone<(Forward<(std::boxed::Box<Future<Error=u32>>,)>, [closure@/checkout/src/test/run-pass/issue-43132.rs:20:15: 20:21])>` has an unknown layout
[00:40:45] 
[00:40:45] note: the compiler unexpectedly panicked. this is a bug.
[00:40:45] 
[00:40:45] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:40:45] 
[00:40:45] note: rustc 1.21.0-dev (d158897d9 2017-09-28) running on x86_64-unknown-linux-gnu
[00:40:45] 
[00:40:45] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:490:8
[00:40:45] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:40:45] 
[00:40:45] 
[00:40:45] ------------------------------------------
[00:40:45] 
[00:40:45] thread '[run-pass] run-pass/issue-43132.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2435:8
[00:40:45] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:40:45] 
[00:40:45] 
[00:40:45] failures:
[00:40:45]     [run-pass] run-pass/issue-43132.rs
[00:40:45] 
[00:40:45] test result: FAILED. 2729 passed; 1 failed; 8 ignored; 0 measured; 0 filtered out
```

**Comment by arielb1** [comment]
Looks like #43132 somehow came back - this was supposed to be fixed by the trait-system PRs, so I guess a backport made them come back.

## Incident

This is not good. The release is pretty soon, and I'm on vacation Sunday to Tuesday. Next time we have problems with backports like this, we should ping more people and earlier cc @rust-lang/infra (and the new triage group). I'll try to get a fix to our backport troubles over the weekend, but that's not something that should have happened.

**Comment by nikomatsakis** [comment]
This now reverts https://github.com/rust-lang/rust/pull/43543, which fixes (on beta) #38714.

**Comment by arielb1** [comment]
libc trouble on sparc:
```
[0KBuilding stage2 std artifacts (x86_64-unknown-linux-gnu -> sparc64-unknown-linux-gnu)
[00:47:10] [m[m[32m[1m   Compiling[m core v0.0.0 (file:///checkout/src/libcore)
[00:47:10] [m[m[32m[1m   Compiling[m unwind v0.0.0 (file:///checkout/src/libunwind)
[00:47:10] [m[m[32m[1m   Compiling[m libc v0.0.0 (file:///checkout/src/rustc/libc_shim)
[00:47:10] [m[m[32m[1m   Compiling[m compiler_builtins v0.0.0 (file:///checkout/src/rustc/compiler_builtins_shim)
[00:47:10] [m[m[32m[1m   Compiling[m alloc_jemalloc v0.0.0 (file:///checkout/src/liballoc_jemalloc)
[00:47:28] [m[m[32m[1m   Compiling[m std v0.0.0 (file:///checkout/src/libstd)
[00:47:32] [m[m[32m[1m   Compiling[m rand v0.0.0 (file:///checkout/src/librand)
[00:47:32] [m[m[32m[1m   Compiling[m std_unicode v0.0.0 (file:///checkout/src/libstd_unicode)
[00:47:33] [m[m[32m[1m   Compiling[m alloc v0.0.0 (file:///checkout/src/liballoc)
[00:47:34] [1m[31merror[E0573](B[m[1m: expected type, found function `statfs64`(B[m
[00:47:34]    (B[m[1m[34m--> (B[m/checkout/src/rustc/libc_shim/../../liblibc/src/unix/notbsd/mod.rs:880:54(B[m
[00:47:34]     (B[m[1m[34m|(B[m
[00:47:34] [1m[34m880(B[m (B[m[1m[34m| (B[m    pub fn statfs64(path: *const ::c_char, buf: *mut statfs64) -> ::c_int;(B[m
[00:47:34]     (B[m[1m[34m| (B[m                                                     (B[m[1m[31m^^^^^^^^(B[m (B[m[1m[31mdid you mean `stat64`?(B[m
[00:47:34] 
[00:47:34] [1m[31merror[E0573](B[m[1m: expected type, found function `statfs64`(B[m
[00:47:34]    (B[m[1m[34m--> (B[m/checkout/src/rustc/libc_shim/../../liblibc/src/unix/notbsd/mod.rs:882:45(B[m
[00:47:34]     (B[m[1m[34m|(B[m
[00:47:34] [1m[34m882(B[m (B[m[1m[34m| (B[m    pub fn fstatfs64(fd: ::c_int, buf: *mut statfs64) -> ::c_int;(B[m
[00:47:34]     (B[m[1m[34m| (B[m                                            (B[m[1m[31m^^^^^^^^(B[m (B[m[1m[31mdid you mean `stat64`?(B[m
[00:47:34] 
[00:47:34] [1m[31merror[E0573](B[m[1m: expected type, found function `statvfs64`(B[m
[00:47:34]    (B[m[1m[34m--> (B[m/checkout/src/rustc/libc_shim/../../liblibc/src/unix/notbsd/mod.rs:883:55(B[m
[00:47:34]     (B[m[1m[34m|(B[m
[00:47:34] [1m[34m883(B[m (B[m[1m[34m| (B[m    pub fn statvfs64(path: *const ::c_char, buf: *mut statvfs64) -> ::c_int;(B[m
[00:47:34]     (B[m[1m[34m| (B[m                                                      (B[m[1m[31m^^^^^^^^^(B[m (B[m[1m[31mdid you mean `statvfs`?(B[m
[00:47:34] 
[00:47:34] [1m[31merror[E0573](B[m[1m: expected type, found function `statvfs64`(B[m
[00:47:34]    (B[m[1m[34m--> (B[m/checkout/src/rustc/libc_shim/../../liblibc/src/unix/notbsd/mod.rs:884:46(B[m
[00:47:34]     (B[m[1m[34m|(B[m
[00:47:34] [1m[34m884(B[m (B[m[1m[34m| (B[m    pub fn fstatvfs64(fd: ::c_int, buf: *mut statvfs64) -> ::c_int;(B[m
[00:47:34]     (B[m[1m[34m| (B[m                                             (B[m[1m[31m^^^^^^^^^(B[m (B[m[1m[31mdid you mean `statvfs`?(B[m
[00:47:34] 
[00:47:35] [1m[31merror(B[m[1m: aborting due to 4 previous errors(B[m
[00:47:35] 
[00:47:35] [m[m[31m[1merror:[m Could not compile `libc`.
```

**Comment by alexcrichton** [comment]
Working on it

**Comment by kennytm** [comment]
@bors retry

* spurious musl error.

**Comment by kennytm** [comment]
Failed to cross-compile `stage2-std` (x86_64-unknown-linux-gnu → x86_64-unknown-fuchsia), cannot link to `libfdio`. 

```
[02:30:45] warning: redundant linker flag specified for library `magenta`
[02:30:45] 
[02:31:04] error: linking with `x86_64-unknown-fuchsia-clang` failed: exit code: 1
[02:31:04]   |
[02:31:04]   = note: "x86_64-unknown-fuchsia-clang" "-m64" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-fuchsia/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/deps/std-9da33aa2df7af1bb.0.o" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/deps/libstd-9da33aa2df7af1bb.so" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/deps/std-9da33aa2df7af1bb.crate.metadata.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/deps/std-9da33aa2df7af1bb.crate.allocator.o" "-Wl,-O1" "-nodefaultlibs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-fuchsia/release/build/compiler_builtins-8eeea2bdf612d544/out" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-fuchsia/lib" "-l" "magenta" "-l" "backtrace" "-l" "mxio" "-l" "launchpad" "-Wl,-Bstatic" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/libpanic_unwind-4716ba3e04edbf85.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/libunwind-aab18988303f572c.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/librand-940cafb5d34d049d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/liballoc_system-71c60414f8c7a15d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/liblibc-30b2f9f033a91c34.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/liballoc-c05e268c627ead18.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/libstd_unicode-0bc266a7a125aa29.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.pBTzTvOIJv3l/libcore-a2272f548d3624ea.rlib" "-Wl,--no-whole-archive" "/tmp/rustc.pBTzTvOIJv3l/libcompiler_builtins-d80fc08b6a143705.rlib" "-Wl,-Bdynamic" "-l" "unwind" "-l" "c" "-l" "fdio" "-shared" "-Wl,-rpath,$ORIGIN/../lib"
[02:31:04]   = note: /usr/local/bin/ld.lld: error: unable to find library -lfdio
[02:31:04]           clang-5.0: error: ld.lld command failed with exit code 1 (use -v to see invocation)
[02:31:04]           
[02:31:04] 
[02:31:04] error: aborting due to previous error
[02:31:04] 
[02:31:04] error: Could not compile `std`.
```

Do we need #44612?

**Comment by alexcrichton** [comment]
@bors: r+

Removed the fuchsia builder, I believe it's broken anyway on beta

**Pull request merged**
