### PR TITLE
Update RLS to disable spurious client_find_definitions test

### PR DESCRIPTION
**Pull request by Xanewok**
Since switching CI to Azure Pipelines it seems that this test seems
to fail more consistently, so let's disable that for now. It helps
that we have less than a week before release - we disallow PRs that
break the tools to land in this period, so this makes landing critical
PRs smoother  now.

r? @alexcrichton

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors p=0 

cherry-picked into https://github.com/rust-lang/rust/pull/62247

**Comment by pietroalbini** [comment]
Already merged into #62247.

**Pull request closed without merging**
