### PR TITLE
Update RLS

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR updates RLS to include the following PRs:

* https://github.com/rust-lang/rls/pull/1766
* https://github.com/rust-lang/rls/pull/1767
* https://github.com/rust-lang/rls/pull/1771
* https://github.com/rust-lang/rls/pull/1772

It also updates racer to fix RLS compilation with the parallel compiler enabled.

### CODE REVIEW

**Comment by pietroalbini** [comment]
There are *new* RLS failures :(

**Comment by pietroalbini** [comment]
Opened https://github.com/racer-rust/racer/pull/1180 with the latest racer fix.

**Comment by Xanewok** [comment]
racer-rust/racer#1180 has been merged now.

**Comment by pietroalbini** [comment]
@Xanewok could you release a new `racer` version?

**Comment by Xanewok** [comment]
That’s done now, sorry for the lag.

**Pull request merged**
