### PR TITLE
implied_bounds: deal with inference vars

### LINKED ISSUE #101951: E0477 triggered with current nightly
I discovered that some code I had previously been using no longer compiles with the current nightly.  It gives E0477 which, as other issues have pointed out, is incorrectly described as "no longer emitted by the compiler".

### Code

[Link to Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4978275d01d9462b7fd8d5487350ccbb)

I expected to see this happen: *The code compiles successfully*

Instead, this happened: *I get this compiler error:*

```
error[E0477]: the type `PrettyCondo<'_>` does not fulfill the required lifetime
  --> src/lib.rs:41:5
   |
41 |     fn add_building(&mut self, _building: &mut PrettyCondo<'_>) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: type must outlive the anonymous lifetime as defined here
  --> src/lib.rs:41:21
   |
41 |     fn add_building(&mut self, _building: &mut PrettyCondo<'_>) {
   |                     ^

For more information about this error, try `rustc --explain E0477`.
error: could not compile `e0477-test` due to previous error
```

### Result of cargo-bisect-rustc

searched nightlies: from nightly-2022-08-08 to nightly-2022-09-17
regressed nightly: nightly-2022-08-10
searched commit range: https://github.com/rust-lang/rust/compare/f03ce30962cf1b2a5158667eabae8bf6e8d1cb03...34a6cae28e7013ff0e640026a8e46f315426829d
regressed commit: https://github.com/rust-lang/rust/commit/63e4312e6bd50ec9859c363402209809fb8155d5

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 
```
</details>

### PR DESCRIPTION
**Pull request by lcnr**
fixes #101951

while computing implied bounds for `<<T as ConstructionFirm>::Builder as BuilderFn<'_>>::Output` normalization replaces a projection with an inference var (adding a `Projection` obligation). Until we prove that obligation, this inference var remains unknown, which caused us to miss an implied bound necessary to prove that the unnormalized projection from the trait method signature is wf.

r? types

### CODE REVIEW

**Comment by jackh726** [comment]
I'm wondering if #101680 also fixes it...

**Comment by lcnr** [comment]
would assume no, because you still eagerly look at `TypeOutlives` obligations there :thinking:  But considering that the failing region relation was from the implied bounds query your pr may still fix https://github.com/rust-lang/rust/issues/101951? :thinking:

There may be other examples where ignoring infer vars from normalization causes us to fail to prove some outlives obligation which isn't added by the implied bounds query itself :sweat_smile: because of that I wouldn't be too comfortable with only merging your pr, even if that were to fix this specific test

**Comment by jackh726** [comment]
Just checked, it does fix it.

Now I'm wondering if I could find a minimal repro of a case that fails without my PR (and more-so *with* yours). I only really found the bug my PR aims to solve by making other changes (that didn't quite work anyways). I don't think yours solves that bug.

However, I have to think a little bit about why my PR *does* solve this test, since it *seems* to be because of not resolving the var before computing components. If I had to guess, the reason my PR fixes the issue, is because we properly register everything as *implied*, not *constraints*, even though it's an unresolved inference var. But then later we normalize and register everything properly.

I think the fully correct behavior is the intersection between these two PRs: we should be resolving variables before computing components for them *and* we shouldn't be registering implied bounds as constraints.

Two things I'd like to know about this (even though I'm not sure it's needed for this PR):
1) If you were to make the change I was *trying* to make in #101680 - namely pushing constraints immediately after registering implied bounds - does the `hyper` benchmark from rustc-perf still fail to build (how I found the bug).
2) With this PR, if we try to take implied bounds from normalized types (as in #99832), do we still run into that one test failure?

r? @jackh726

**Comment by jackh726** [comment]
The answers to the above are 1) No, it builds fine with this PR 2) No, the test passes.

**Comment by wesleywiser** [comment]
Since this fixes a regression in 1.65, I'm nominating for beta backport.

**Pull request merged**
