### PR TITLE
Restore creating the channel-rust-$channel-date.txt files

### PR DESCRIPTION
**Pull request by shepmaster**
I have **not** run this (because I don't know how to 😇), but it *does* compile.

r? @alexcrichton

### CODE REVIEW

**Comment by shepmaster** [comment]
@alexcrichton I've rebased to address #39917; note that there's now an extra commit to deal with what appears to be variables that weren't fully renamed.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by shepmaster** [comment]
Merge conflict (that I didn't see locally) fixed.

**Comment by alexcrichton** [comment]
@bors: retry

(need another PR to land)

**Comment by arielb1** [comment]
Cargo problem:
```
ar: creating archive ../../libcrypto.aar: 

../libcrypto.a: Inappropriate file type or format

make[2]: *** [../libcrypto.a] Error 1
```

**Comment by shepmaster** [comment]
@arielb1 that seems unrelated to my change. Do you know if there's something I need to address?

**Comment by alexcrichton** [comment]
@bors: retry

* probably spurious -- https://github.com/rust-lang/rust/issues/40417

**Pull request merged**
