### PR TITLE
Decouple `test` and `proc_macro`

### PR DESCRIPTION
**Pull request by Zoxc**
This decouples the `test` and `proc_macro` crates by having `bootstrap` build both at the same time instead of having `proc_macro` be a dependency of `test`. This allows them to build in parallel saving around 9 seconds locally.

The `std` is also built directly by `bootstrap` avoiding the extra features on the `test` crate.

This is an alternative to https://github.com/rust-lang/rust/pull/108865.

### CODE REVIEW

**Comment by Zoxc** [comment]
@jyn514 You'll want to look at the error on the first commit. The second is my attempted fix.

**Comment by jyn514** [comment]
```
error: the argument '--package [<SPEC>]' cannot be used multiple times
```
@Zoxc you can use `RUSTDOCFLAGS=... cargo doc` instead of `cargo rustdoc ...`.

**Comment by Zoxc** [comment]
I'll have to remove the ability to document individual crates then, as different crates may have different sets of features.

**Comment by jyn514** [comment]
I think it would be possible to change which `--features` we pass to cargo depending on the specific crate being documented. But I agree at that point it's getting quite complicated. I don't have strong opinions on whether to land this or https://github.com/rust-lang/rust/pull/108865.

**Comment by Zoxc** [comment]
I'm going to favor https://github.com/rust-lang/rust/pull/108865 then as I'd prefer not to reimplement cargo features in bootstrap. Ideally cargo would have to ability to specify features for a whole workspace here.

**Pull request closed without merging**
