### PR TITLE
[beta] back out #42480 and its dependents

### PR DESCRIPTION
**Pull request by arielb1**
#42480 makes the ICE in #43132 worse, and the "safe" fix to that causes the #43787 exponential worst-case.

Let's back everything out for beta to avoid regressions, and get the permafix in nightly.

### CODE REVIEW

**Comment by arielb1** [comment]
cc @nikomatsakis

**Comment by arielb1** [comment]
This appears to fix all relevant issues.

**Comment by kennytm** [comment]
@nikomatsakis @arielb1  The [Homu queue](https://buildbot2.rust-lang.org/homu/queue/rust) doesn't register the r+, and it says "Mergeable = no". This may need a `git commit --amend` to refresh bors's status.

**Pull request merged**
