### PR TITLE
Update Clippy to 43a1777

### PR DESCRIPTION
**Pull request by flip1995**
Updates Clippy to https://github.com/rust-lang/rust-clippy/commit/43a1777b89cf6791f9e20878b4e5e3ae907867a5

We should establish a process on how often and when to update Clippy. (After X feature PRs? Once per week? Only on bug fixes and in the release week? ...?)

r? @oli-obk

### CODE REVIEW

**Comment by flip1995** [comment]
These wasm test failures seem unrelated?

**Comment by matthiaskrgr** [comment]
Spurious failure again https://github.com/rust-lang-ci/rust/runs/670397946#step:16:66

**Comment by Dylan-DPC** [comment]
yeah investigating

**Pull request merged**
