### PR TITLE
Move std::os::raw::c_void into libcore and re-export in libstd

### PR DESCRIPTION
**Pull request by IsaacWoods**
Implements the first part of [RFC 2521](https://github.com/rust-lang/rfcs/pull/2521).

cc #53856

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks! As Travis-CI suggests, this needs `#![warn(non_camel_case_types)]` in `src/libcore/ffi.rs`.

@rust-lang/libs, how do you feel about `core::ffi` and `core::ffi::c_void` being insta-stable? I think it’s fine since the type is already stable under `std::os::raw::c_void`, but let’s formally get team sign off:

@rfcbot merge

**Comment by SimonSapin** [comment]
Rather than changing the links, maybe it’d be better to add `#[doc(inline)]` on the `pub use` item that replaced the previous `enum`?

**Comment by IsaacWoods** [comment]
@SimonSapin Tried this and tested locally (`./x.py test src/tools/linkchecker`) and that gives:
```
std/ffi/index.html:190: broken link - primitive.pointer.html
std/ffi/enum.c_void.html:4: broken link - primitive.pointer.html
std/ffi/enum.c_void.html:8: broken link - primitive.never.html
core/ffi/index.html:8: broken link - primitive.pointer.html
core/ffi/enum.c_void.html:4: broken link - primitive.pointer.html
core/ffi/enum.c_void.html:8: broken link - primitive.never.html
```

I don't think we could use the same link from all three places (`core::ffi`, `std::ffi` and `std::os::raw`) whatever it was. Is there a way to link absolutely to those pages?

**Comment by SimonSapin** [comment]
Sorry, in my previous comment I was only thinking of links *to* `c_void` and I didn’t realize that the broken links were in fact the ones in `c_void`’s own documentation.

Indeed, `std::os::raw` being at a different depth than `std::ffi` and `core::ffi` makes relative links tricky. However absolute links are not acceptable as we don’t know where docs will be based. For example on my machine running `rustup doc --std` opens `file:///home/simon/tmp/rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/std/index.html`.

So we probably need to **not** use `#[doc(inline)]` here. But it looks like https://github.com/rust-lang/rust/pull/53910#issuecomment-418364881 failed without as it still has broken links in `std::os::raw`, which I did not expect. What does the docs for `std::os::raw` look like? Is the doc-comment of `c_void` inlined "through" the `pub use` re-export?

**Comment by SimonSapin** [comment]
@rust-lang/docs, any thoughts on how we should handle this?

**Comment by IsaacWoods** [comment]
Update: adding `#[doc(no_inline)]` to both of the `pub use`s fixes the broken links in `std::os::raw` but not `std::ffi`, but I have no idea why. The generated docs look the same for both, showing `pub use core::ffi::c_void;` under a 'Re-exports' section, so it's not trying to inline the comment afaict.


The exact error from linkchecker is:
```
std/ffi/enum.c_void.html:4: broken link - primitive.pointer.html
std/ffi/enum.c_void.html:8: broken link - primitive.never.html
```

**Comment by TimNN** [comment]
Ping @rust-lang/docs & @rust-lang/rustdoc: It looks like there's some issues with `pub use`s broken links, could you take a look?

**Comment by QuietMisdreavus** [comment]
Links in the std docs are incredibly fragile. Since this is something that exists in both core and std, you need to make sure that they're at the same directory level in both places.

In fact, looking at the current Travis error, you may be closer then you think...

```
[01:17:18] std/os/raw/enum.c_void.html:4: broken link - std/std/primitive.pointer.html
[01:17:18] std/os/raw/enum.c_void.html:8: broken link - std/std/primitive.never.html
[01:17:18] std/os/raw/index.html:13: broken link - std/std/primitive.pointer.html
[01:17:29] thread 'main' panicked at 'found some broken links', tools/linkchecker/main.rs:49:9
[01:17:29] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It seems like it's only complaining about the re-export in `std::os::raw`, so i would suggest putting `#[doc(no_inline)]` just on that one.

-----

What's happening here is that the link you gave it is relative to its file path. This enum appears in three places in this PR:

* `core::ffi`
* `std::ffi`
* `std::os::raw`

Note that the module path for that last one is longer than the other two. This means that it has one more folder parent to pass through with `..` to get back to the doc root. Sadly, this means that it's impossible to use the same link in all three places and still have it be valid.

(Strictly speaking, this is what "intra-doc links" were made to fix, but i'm not sure the primitive link will totally work out? For one, you'd need to add the reference into [this array](https://github.com/rust-lang/rust/blob/994cdd918589535d705177545bf503cd0c3c5148/src/librustdoc/passes/collect_intra_doc_links.rs#L569-L587), but also, the primitive docs aren't even available in libcore! We'd have to fix rustdoc to make sure the link is handled correctly.)

**Comment by SimonSapin** [comment]
@QuietMisdreavus if we make `std::os::raw::c_void` (which is now a `pub use` reexport) *not be documented* inline (only be a link to `core::ffi::c_void`, which is documented):

* Would this fix the directory nesting level problem?
* Would this be acceptable, in terms of how we want the docs to look like?
* Would `#[doc(no_inline)]` be enough to achieve this?

**Comment by QuietMisdreavus** [comment]
@SimonSapin:

* Yes, because now the links are not being used in the `std::os::raw` location, and the other two have the same level of nesting.
* In terms of "how we want them to look like", i think it would work out, though i'm welcome to a second opinion from @rust-lang/docs. The idea here is that we're moving the "canonical" location for it into libcore (which is where it would start linking). Any *code* written can use this location just fine (in fact it must, since this used to be its "canonical" location), but it's now available in more places, and the docs can reflect that.
* Yes. `#[doc(no_inline)]`, when applied to a `pub use` re-export, tells rustdoc "don't copy in the docs for this item; render the `pub use` statement into the module instead".

  (For posterity: The method rustdoc uses to determine whether to "inline" a re-export is something like this: If the "original declaration" of the item is both crate-local and public, then link to that location. Otherwise, copy the docs inline. Applying `#[doc(inline)]` or `#[doc(no_inline)]` to the declaration overrides this behavior.)

**Comment by SimonSapin** [comment]
@IsaacWoods Yes, please squash into one commit and I’ll r+. Thanks!

**Comment by SimonSapin** [comment]
Oops I didn’t realize the squash was done.

Looks good, thanks!

@bors r+

**Pull request merged**
