### PR TITLE
Extract `sys::args::Args` implementation to `sys_common`

### PR DESCRIPTION
**Pull request by CDirkx**
After  #84413 and #84179 I have been looking into if code for `sys::args::Args` could be de-duplicated, as it was essentially the same on every platform: a wrapper type implementing `!Send + !Sync + Debug + Iterator + ExactIterator + DoubleEndedIterator` (although note that on `windows` and `sgx` the types are currently not `!Send + !Sync`).

This PR makes `sys::args::Args` a type alias (for `vec::IntoIter`<s>/`Empty`/`Clone<Iter<'static>>` depending on the platform</s>)  and extracts the wrapper type to `sys_common`. 

Alternatively, the wrapper type could be removed entirely and the type aliases used directly (i.e. only the first commit of this PR), since they are wrapped by `std::env::ArgsOs` anyway. These type aliases are not `!Send + !Sync`, but I don't know how much of a problem that would be since `ArgsOs` implements `!Send + !Sync` explicitly and currently `sys::windows::args::Args` and `sys::sgx::args::Args` are already `Send` and `Sync`.

### CODE REVIEW

**Comment by CDirkx** [comment]
One thing this is still blocked on is making sure the `Debug` output of `std::env::Args` and `std::env::ArgsOs` are not affected, which I overlooked.

**Comment by CDirkx** [comment]
> warning: spurious network error (1 tries remaining): failed to get 200 response from `https://crates.io/api/v1/crates/once_cell/1.7.2/download`, got 503
error: failed to download from `https://crates.io/api/v1/crates/difference/2.0.0/download`

**Comment by JohnCSimon** [comment]
Ping from triage:
@CDirkx  can you please resolve the merge conflicts?

**Comment by joshtriplett** [comment]
Seems reasonable to me; r=me with conflicts addressed.

**Comment by Dylan-DPC** [comment]
Closing this is inactive

**Pull request closed without merging**
