### PR TITLE
doc: "extern crate" is not an import

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hmmm, what do you mean? It does in fact bring things into scope, which is usually referred to as "importing".

**Comment by tshepang** [comment]
I was thinking "use" is what is referred to as an import @steveklabnik

**Comment by steveklabnik** [comment]
Right. But `extern crate` does bring the parent module into scope at the point of the declaration, like `use` does.

**Comment by alexcrichton** [comment]
I agree with @steveklabnik that `extern crate` basically does import something because it's linking to a piece of code and bringing in a large set of functionality. It is indeed also a declaration, but for `extern crate` I think there's not really much of a distinction.

Thanks for the pr though!

**Pull request closed without merging**
