### PR TITLE
doc (unstable-book): fix a typo

### PR DESCRIPTION
**Pull request by zamazan4ik**
Just fix a small typo.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Can you squash this into one commit?

**Comment by zamazan4ik** [comment]
Done.

**Comment by compiler-errors** [comment]
Actually, did you look at the rest of the pages in this section? They all seem to be putting backticks around the flag name. I assume the typo is a missing right backtick, not an unintentional left one.

**Comment by zamazan4ik** [comment]
Oh, you are right. I've looked at the rendered pages and didn't notice backticks. Fixed.

**Pull request merged**
