### PR TITLE
Reduce wait-for instructions for rustdoc GUI tests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @notriddle

### CODE REVIEW

**Comment by notriddle** [comment]
I’d really rather not mess with these numbers unless someone’s complaining about them becoming the long pole in the test suite. Making them shorter will increase the number of [intermittent failures](https://github.com/rust-lang/rust/pull/94779), when these tests run on a computer with a noisy neighbor.

Could these tests be tweaked to poll for some criteria to be fulfilled, instead of just waiting for a fixed amount of time?

For example, could the wait-for instruct be modified to take both a time *and* a selector?

**Comment by GuillaumeGomez** [comment]
It already can. It's just that in some cases, waiting for a selector isn't working because the CSS changes associated to it haven't been computed by the browser yet. I only changed the biggest ones because the 1 second wait for example is just way too much.

**Comment by GuillaumeGomez** [comment]
That could. Not sure if it's a good idea though...

**Comment by notriddle** [comment]
I've done browser UI tests (not with your framework, just Selenium-PHP), and wound up with a test suite that took hours to run while consuming less than 1% CPU. Redesigning it to use a function that pretty much does what "assert-css with a timeout param" would do improved it a lot, cutting runtime by more than half, while also pretty much eliminating intermittent test failures.

But, on the other hand, that project was strange in a lot of ways, so I'm not sure how reflective of rustdoc it'll be.

**Comment by notriddle** [comment]
Sure, that would be great. Thanks!

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/GuillaumeGomez/browser-UI-test/issues/286. I'll try to do it in the next days.

**Comment by GuillaumeGomez** [comment]
@notriddle Thanks to your great suggestion, almost all "random amount of time" waits have been removed! \o/

**Review by notriddle — APPROVED** [review]

**Pull request merged**
