### PR TITLE
Fix cross compiling dist/build invocations

### LINKED ISSUE #76733: Can't cross-build rustc for aarch64-apple-darwin anymore
With the following config.toml:
```
[build]
build = "x86_64-apple-darwin"
host = ["aarch64-apple-darwin"]
target = ["aarch64-apple-darwin"]
```
when building on a Apple Silicon DTK, you'd get an aarch64-apple-darwin rustc and libstd. That's not the case since #76415, where you only end up with an x86_64-apple-darwin compiler and libstd. There isn't even a build/aarch64-apple-darwin directory at all.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
I am uncertain why the first commit is not affecting CI. I suspect it's because we pass --disable-docs on most of our cross-compilation builders. The second commit doesn't affect CI because CI runs x.py dist, not x.py build. 

Both commits are standalone; together they should resolve #76733. The first commit doesn't really fix that issue but rather just fixes cross-compiled x.py dist, resolving a bug introduced in #76549.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It looks like the first commit here is presumably either an incomplete fix or something like that, https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/x.2Epy.20calls.20itself.20recursively.3F/near/210307295.

**Comment by Mark-Simulacrum** [comment]
Looks like that was a false alarm -- seems like this is actually fixed (or at least that build is not evidence otherwise).

**Comment by glandium** [comment]
I can confirm it works, but it also builds a stage1 "host" compiler with `x.py build` (without `--stage 2`). That sounds like what you wanted to avoid in the first place?

**Comment by Mark-Simulacrum** [comment]
I think that's probably avoidable but will be a more invasive change so I'll leave it to future work (unless @alexcrichton feels we should do it here). We'll probably need to model compile::Std and other steps similar to how rustdoc is done, where they don't ask for a top_stage compiler which they don't actually need.

**Comment by alexcrichton** [comment]
Seems reasonable to me, and yeah further optimizations can probably come later.

Would it be possible to add a test for this? These sorts of bugs are notoriously hard to protect against otherwise

**Comment by Mark-Simulacrum** [comment]
Okay @alexcrichton just pushed a test, annotated with a fixme comment since it's over-building things currently

**Pull request merged**
