### PR TITLE
Revert accidental stabilization

### LINKED ISSUE #94804: `1.59` accidentally stabilized dropping `Box<T>`s in `const fn`s
```rs
const fn f<T>(_: Box<T>) {}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6349e1b7d3023327e25c2fdebf4924cb))

Note that this works even if `T` implements `Drop` in a non-`const` way. This seems ***hightly*** problematic, especially provided we eventually want to support constructing `Box` at compile time.

Relevant PR: [#91884](https://github.com/rust-lang/rust/pull/91884/files#diff-ee1616b052da71e1a0b80b66544fc07b98debc288e71eeb3e827c7fc3e7e9ecfR1173-R1174)

Of course that impl *claims* to be unstable, but as we all know trait implementations are *never* unstable, unless the trait is unstable. (For ordinary traits, implementations of `const Trait` are thus unstable merely due to the fact that no user can use any such implementations in stable code yet.)

@rustbot label regression-from-stable-to-stable

~~I don’t know what team to tag.~~

The fix should be straightforward: Remove the `const Drop for Box<T, A>` implementation (i.e. revert it to be non-`const`), and add a test.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #94804

### CODE REVIEW

**Comment by jhpratt** [comment]
Why did `#[rustc_const_unstable]` not work here?

**Comment by oli-obk** [comment]
Butterfingers on mobile, didn't want to close

**Comment by oli-obk** [comment]
I think it was a weird combination of `Drop` being special and not actually being called, so the checks failed because they were not actually hit.

**Comment by Dylan-DPC** [comment]
i don't think it needs a re-r+ but just in case

@bors r+

**Comment by apiraino** [comment]
switched team label because (if I am not mistaken) the changes seems more relevant to t-libs, so I thought they should decide on the backport. But in case it can be discussed also tomorrow during T-compiler team

**Comment by apiraino** [comment]
Beta and stable backports accepted as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bweekly.5D.202022-03-17.20.2354818.html#275658643)

@rustbot label +beta-accepted +stable-accepted

**Pull request merged**
