### PR TITLE
ci: Attempt to skip a full rustc compile on dist*

### PR DESCRIPTION
**Pull request by alexcrichton**
Currently when we're preparing cross-compiled compilers it can take
quite some time because we have to build the compiler itself three
different times. The first is the normal bootstrap, the second is a
second build for the build platform, and the third is the actual target
architecture compiler. The second compiler was historically built
exclusively for procedural macros, and long ago we didn't actually need
it.

This commit tries out avoiding that second compiled compiler, meaning we
only compile rustc for the build platform only once. Some local testing
shows that this is promising, but bors is of course the ultimate test!

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors r+ p=1

This should also give us a big performance boost on the current Travis and AppVeyor setup.

**Comment by pietroalbini** [comment]
@bors retry

Yield priority to https://github.com/rust-lang/rust/pull/61213

**Comment by alexcrichton** [comment]
@bors: r-

Hm looking at the logs there's something else to remove, need to keep digging.

**Comment by alexcrichton** [comment]
Ok the last two commits I believe actually fix the issue, 

re-r? @pietroalbini

**Comment by pietroalbini** [comment]
This looks good! Let's try again.

@bors r+ p=1 rollup=never
(priority since it will reduce the build time a lot)

**Comment by mati865** [comment]
Timeout:
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by pietroalbini** [comment]
Ugh, it almost finished :/

@bors retry

**Pull request merged**
