### PR TITLE
Implement `IntoIterator` for `&{Path, PathBuf}`

### LINKED ISSUE #26220: Some things don't implement IntoIterator
There are some missing `IntoIterator`s:

* By-reference and mut-reference for `Option`
* By-reference and mut-reference for `Result`
* By-reference for `Path`
* Several misc. internal things (`TraitObligationStackList`, `SearchPaths`, `ArchiveRO`, `RawTable`, `Book`)

Given the by-value `IntoIterator` `impl`s for `Option` and `Result`, I don't see why by-reference iteration would be special. `Path` should probably be `IntoIterator`. I'm indifferent with regards to internal stuff.

### PR DESCRIPTION
**Pull request by apasel422**
Closes #26220.

r? @alexcrichton

### CODE REVIEW

**Comment by bluss** [comment]
if PathBuf should have a consuming iterator it's best to add it now (to not break .into_iter() later). I guess it's probably not going to have it?

**Comment by apasel422** [comment]
I'll look into adding it shortly.

**Comment by apasel422** [comment]
@bluss Now that I'm looking into how this is implemented, I'm not sure what a consuming iterator for `PathBuf` would be.

**Comment by bluss** [comment]
Right, it doesn't seem to make sense. Sorry, just a knee-jerk check due to recent discussions where .into_iter() means .iter() for certain types.

**Comment by alexcrichton** [comment]
@bors: r+ 6ad6cc30ef70bbb1f771a551183d317170ddfd7b

Thanks!

**Pull request merged**
