### PR TITLE
Do not attempt to recompile codegen backend(s) with --keep-stage

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Previously we'd attempt to recompile them and that would fail since
we've essentially not built the entire compiler yet, or we're faking
that fact. This commit should make us ignore the codegen backend build
as well.

Unlike the other compile steps, there is no CodegenBackendLink step that
we run here, because that is done later as a part of assembling the
final compiler and as an explicit function call.

r? @alexcrichton

I think this may fix or at least assist with #52174.

cc @RalfJung @tinco -- if you can test this patch locally that'd be
amazing; I don't want to recompile for the next couple hours to test it
locally. I don't think it can make the situation worse, and in fact, if
I've interpreted the cause of the failure correctly then this will fix
your problem.

### CODE REVIEW

**Comment by tinco** [comment]
Hi Mark! This does not solve things for me, though it does change the error message. This is the full message:

```
  rust git:(pull_52360) ./x.py test --keep-stage 0 --stage 1 src/test/pretty ; say "I am done. I am really done. ... Really"
Updating only changed submodules
Submodules updated in 0.09 seconds
    Finished dev [unoptimized] target(s) in 0.30s
Warning: Using a potentially old librustc. This may not behave well.
Warning: Using a potentially old codegen backend. This may not behave well.
Warning: Using a potentially old librustc. This may not behave well.
Warning: Using a potentially old libtest. This may not behave well.
Warning: Using a potentially old librustc. This may not behave well.
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Warning: Using a potentially old codegen backend. This may not behave well.
Assembling stage1 compiler (x86_64-apple-darwin)
Warning: Using a potentially old librustc. This may not behave well.
Copying stage1 rustc from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Warning: Using a potentially old libtest. This may not behave well.
Copying stage1 test from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 tool compiletest (x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.36s
Check compiletest suite=pretty mode=pretty (x86_64-apple-darwin -> x86_64-apple-darwin)

running 50 tests
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiF
failures:

---- [pretty] pretty/issue_12590_c.rs stdout ----

error: pretty-printing failed in round 0 revision None
status: signal: 6
command: "/Users/tinco/Source/rust/build/x86_64-apple-darwin/stage1/bin/rustc" "-" "-Z" "unpretty=expanded" "--target" "x86_64-apple-darwin" "-L" "/Users/tinco/Source/rust/build/x86_64-apple-darwin/test/pretty/issue_12590_c/auxiliary.pretty" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/Users/tinco/Source/rust/build/x86_64-apple-darwin/native/rust-test-helpers"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
dyld: Library not loaded: @rpath/libtest-6187db25f3681564.dylib
  Referenced from: /Users/tinco/Source/rust/build/x86_64-apple-darwin/stage1/bin/rustc
  Reason: image not found

------------------------------------------

thread '[pretty] pretty/issue_12590_c.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3162:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [pretty] pretty/issue_12590_c.rs

test result: FAILED. 0 passed; 1 failed; 49 ignored; 0 measured; 0 filtered out

thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:498:22


command did not execute successfully: "/Users/tinco/Source/rust/build/x86_64-apple-darwin/stage0-tools-bin/compiletest" "--compile-lib-path" "/Users/tinco/Source/rust/build/x86_64-apple-darwin/stage1/lib" "--run-lib-path" "/Users/tinco/Source/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib" "--rustc-path" "/Users/tinco/Source/rust/build/x86_64-apple-darwin/stage1/bin/rustc" "--src-base" "/Users/tinco/Source/rust/src/test/pretty" "--build-base" "/Users/tinco/Source/rust/build/x86_64-apple-darwin/test/pretty" "--stage-id" "stage1-x86_64-apple-darwin" "--mode" "pretty" "--target" "x86_64-apple-darwin" "--host" "x86_64-apple-darwin" "--llvm-filecheck" "/Users/tinco/Source/rust/build/x86_64-apple-darwin/llvm/build/bin/FileCheck" "--nodejs" "/usr/local/bin/node" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/Users/tinco/Source/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "--docck-python" "/usr/bin/python" "--lldb-python" "/usr/bin/python" "--gdb" "/usr/local/bin/gdb" "--lldb-version" "lldb-902.0.79.7" "--lldb-python-dir" "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python" "--quiet" "--llvm-version" "7.0.0svn\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" ""
expected success, got: exit code: 101


failed to run: /Users/tinco/Source/rust/build/bootstrap/debug/bootstrap test --keep-stage 0 --stage 1 src/test/pretty
Build completed unsuccessfully in 0:00:03
```
The important part being:

```
dyld: Library not loaded: @rpath/libtest-6187db25f3681564.dylib
  Referenced from: /Users/tinco/Source/rust/build/x86_64-apple-darwin/stage1/bin/rustc
  Reason: image not found
```

Before running this I did a full test compile once by executing the same command but without `--keep-stage 0`, to make sure all my artifacts were there.

**Comment by tinco** [comment]
Keeping stage 1 and running in stage 2 gives a slightly different error:

```
➜  rust git:(pull_52360) ./x.py test --keep-stage 1 --stage 2 src/test/pretty ; say "I am done. I am really done. ... Really"
Updating only changed submodules
Submodules updated in 0.09 seconds
    Finished dev [unoptimized] target(s) in 0.27s
Warning: Using a potentially old librustc. This may not behave well.
Warning: Using a potentially old codegen backend. This may not behave well.
Warning: Using a potentially old librustc. This may not behave well.
Warning: Using a potentially old libtest. This may not behave well.
Building stage0 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.28s
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 test artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.26s
Copying stage0 test from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.34s
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 codegen artifacts (x86_64-apple-darwin -> x86_64-apple-darwin, llvm)
    Finished release [optimized] target(s) in 0.34s
Assembling stage1 compiler (x86_64-apple-darwin)
Warning: Using a potentially old librustc. This may not behave well.
Copying stage1 rustc from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Warning: Using a potentially old codegen backend. This may not behave well.
Assembling stage2 compiler (x86_64-apple-darwin)
Warning: Using a potentially old librustc. This may not behave well.
Copying stage2 rustc from stage2 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
thread 'main' panicked at 'File::open(stamp) failed with No such file or directory (os error 2)', bootstrap/lib.rs:1109:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /Users/tinco/Source/rust/build/bootstrap/debug/bootstrap test --keep-stage 1 --stage 2 src/test/pretty
Build completed unsuccessfully in 0:00:03
```

**Comment by RalfJung** [comment]
It didn't fully work for me either. I first did `./x.py build src/rustc` to get a compiler in stage 2 built (I had to `rm build/x86_64-unknown-linux-gnu/stage{1,2}* -rf` but that may be because of junk in there from previous attempts).

Then I changed something in `rustc_mir` a bit, and did `./x.py build src/rustc --keep-stage 1`. This failed with the following log:
```
Updating only changed submodules
Submodules updated in 0.03 seconds
   Compiling bootstrap v0.0.0 (file:///home/r/src/rust/rustc/src/bootstrap)
    Finished dev [unoptimized] target(s) in 5.67s
Warning: Using a potentially old librustc. This may not behave well.
Warning: Using a potentially old codegen backend. This may not behave well.
Warning: Using a potentially old librustc. This may not behave well.
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.24s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.22s
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc_mir v0.0.0 (file:///home/r/src/rust/rustc/src/librustc_mir)
   Compiling rustc_passes v0.0.0 (file:///home/r/src/rust/rustc/src/librustc_passes)
   Compiling rustc_borrowck v0.0.0 (file:///home/r/src/rust/rustc/src/librustc_borrowck)
   Compiling rustc_codegen_utils v0.0.0 (file:///home/r/src/rust/rustc/src/librustc_codegen_utils)
   Compiling rustc_lint v0.0.0 (file:///home/r/src/rust/rustc/src/librustc_lint)
   Compiling rustc_driver v0.0.0 (file:///home/r/src/rust/rustc/src/librustc_driver)
   Compiling rustc-main v0.0.0 (file:///home/r/src/rust/rustc/src/rustc)
    Finished release [optimized] target(s) in 14.51s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 codegen artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu, llvm)
   Compiling rustc_codegen_llvm v0.0.0 (file:///home/r/src/rust/rustc/src/librustc_codegen_llvm)
    Finished release [optimized] target(s) in 7.64s
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Warning: Using a potentially old librustc. This may not behave well.
Copying stage1 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Warning: Using a potentially old codegen backend. This may not behave well.
Assembling stage2 compiler (x86_64-unknown-linux-gnu)
Warning: Using a potentially old librustc. This may not behave well.
Copying stage2 rustc from stage2 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
thread 'main' panicked at 'File::open(stamp) failed with No such file or directory (os error 2)', bootstrap/lib.rs:1109:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /home/r/src/rust/rustc/build/bootstrap/debug/bootstrap build src/rustc --keep-stage 1
Build completed unsuccessfully in 0:00:29
```

**Comment by RalfJung** [comment]
FWIW, reverting 9eda4aabff138add785c6e672d9c67cc612f7503 (from https://github.com/rust-lang/rust/pull/52006) fixes the problem.

**Pull request merged**
