### PR TITLE
Tighten emitted JSON diagnostics

### PR DESCRIPTION
**Pull request by Xanewok**
* Introduces SubDiagnostic to better reflect that diagnostics cannot be
nested
* Suggestions with provided suggested replacements are separated from other
children diagnostics

This just removes unused fields and the JSON format is unstable, so I don't think this will need much changes from the possible consumers. RLS will need to update compiler message parsing to account for subdiagnostics not having additional children diagnostics. (Passing structured diagnostics would be even better, but we can do that later at some point!)

r? @nrc

### CODE REVIEW

**Comment by oli-obk** [comment]
The json format is stable. we can't just change it. We can add new fields, but we can't change the general layout

**Comment by nrc** [comment]
Yeah, I'm afraid JSON being stable means we can't do this as it stands, sorry.

**Comment by Xanewok** [comment]
Wait, is it? I understood this is more of a works-for-now solution; Should [this](https://github.com/rust-lang/rust/blob/master/src/libsyntax/json.rs#L17) be changed then?

**Comment by nrc** [comment]
> Wait, is it? I understood this is more of a works-for-now solution; Should this be changed then?

Yeah, that is out of date. I'm not sure exactly when or how we stabilised, but it is usable on stable, which means it is stable.

**Pull request closed without merging**
