### PR TITLE
[beta] Rollup backports

### PR DESCRIPTION
**Pull request by emilyalbini**
Cherry-picked:

* #58021: Fix fallout from #57667 
* #59599: Updated RELEASES.md for 1.34.0
* #59587: Remove #[doc(hidden)] from Error::type_id 
* #58994: Hide deprecation warnings inside derive expansions 
* #58015: Expand docs for `TryFrom` and `TryInto`. 
* #59770: ci: pin android emulator to 28.0.23
* #59704: ci: Update FreeBSD tarball downloads 
* #59257: Update CI configuration for building Redox libraries
* #59724: Function arguments should never get promoted
* #59499: Fix broken download link in the armhf-gnu image 
* #58330: Add rustdoc JS non-std tests 
* #58848: Prevent cache issues on version updates 

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Added #58015.

@bors r+ p=20

**Comment by kennytm** [comment]
@bors r-

Still the same error, should be legit.

**Comment by kennytm** [comment]
@bors r=pietroalbini

Try to invalidate the Android docker cache, since there is this warning in the jobs:

```
[00:11:05] emulator: warning: opening audio output failed
[00:11:05] 
[00:11:05] Your emulator is out of date, please update by launching Android Studio:
[00:11:05]  - Start Android Studio
[00:11:05]  - Select menu "Tools > Android > SDK Manager"
[00:11:05]  - Click "SDK Tools" tab
[00:11:05]  - Check "Android Emulator" checkbox
[00:11:05]  - Click "OK"
```

**Comment by kennytm** [comment]
@bors r=pietroalbini

Now try to force an `sdkmanager --update` and also pass `-no-audio` into emulator. If this also doesn't work I have no idea 🤷

**Comment by pietroalbini** [comment]
Backed out all the CI changes, let's hope Android is happy with that.

@bors r+

**Comment by pietroalbini** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
You might require another PR of mine for that (it does trigger something in my memory but can't remember what exactly...). Or just remove the commits of mine that are provoking this?

**Comment by Centril** [comment]
> Or just remove the commits of mine that are provoking this?

👍

**Comment by pietroalbini** [comment]
Removed #58848, added #59770, #59704, #59257, #59724

@bors r+ p=500

**Comment by pietroalbini** [comment]
@bors r+ p=500

*Please*

**Comment by pietroalbini** [comment]
Added https://github.com/rust-lang/rust/pull/59499

**Comment by pietroalbini** [comment]
Timeout caused by image rebuilds.

@bors retry

**Comment by pietroalbini** [comment]
Added again https://github.com/rust-lang/rust/pull/58848, along with its prerequisite https://github.com/rust-lang/rust/pull/58330.

@bors r+ retry

**Pull request merged**
