### PR TITLE
Only tag data if debug assertions are enabled.

### PR DESCRIPTION
**Pull request by cjgillot**
r? @ghost

### CODE REVIEW

**Comment by cjgillot** [comment]
I'm not really sure that losing the capability is worth it, but at the same time I don't remember ever seeing an ICE triggered by this.

r? rust-lang/compiler

**Comment by nagisa** [comment]
Do I understand correctly that rustc will handle the different encodings correctly and evict the cache properly when running two rustc builds from the same commit, one with debug assertions enabled and another with them disabled?

**Comment by apiraino** [comment]
Switching to waiting on author to incorporate changes (see [previous comment](https://github.com/rust-lang/rust/pull/95850#issuecomment-1140246123)). Feel free to request a review when ready, thanks!

@rustbot author

**Comment by JohnCSimon** [comment]
@cjgillot 
ping from triage - can you post your status on this PR? This has sat unmoved for a while now. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Pull request closed without merging**
