### PR TITLE
built-in derive: remove BYTE_SLICE_IN_PACKED_STRUCT_WITH_DERIVE hack and lint

### LINKED ISSUE #107457: Tracking Issue for `BYTE_SLICE_IN_PACKED_STRUCT_WITH_DERIVE` lint
This is a tracking issue for the `BYTE_SLICE_IN_PACKED_STRUCT_WITH_DERIVE` lint, which is being added in https://github.com/rust-lang/rust/pull/104429. The lint detects cases where `derive` is used with a `packed` struct that contains a `[u8]` field.

### Example

This lint will trigger for code like this:

```rust
#[repr(packed)]
#[derive(Eq, PartialEq)]
pub struct FlexZeroSlice {
    width: u8,
    data: [u8], // triggered
}
```

At some point in the future this case will be disallowed.

See #104429 for more details, especially the [t-lang nomination](https://github.com/rust-lang/rust/pull/104429#issuecomment-1320909245).

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/107457 by turning the lint into a hard error. The lint has been shown in future breakage reports since Rust 1.69 (released in April 2023).

Let's see (via crater) if enough time has passed since https://github.com/rust-lang/rust/pull/104429, and https://github.com/unicode-org/icu4x/pull/2834 has propagated far enough to let us make this a hard error.

Cc @nnethercote @Manishearth

### CODE REVIEW

**Comment by RalfJung** [comment]
PR is ready for review.

**Comment by RalfJung** [comment]
r? compiler

**Comment by nnethercote** [comment]
The crater results include multiple "no space left on device" and ld bus errors, which are familiar failures. There are also a few where the newer run fails despite only warnings being emitted, e.g. [this one](https://crater-reports.s3.amazonaws.com/pr-127907/try%236223d840318ac1f9c8b6bf3aef24c3ff67683479/gh/septa97.intel-8080-emu-space-invaders/log.txt). And [this one](https://crater-reports.s3.amazonaws.com/pr-127907/try%236223d840318ac1f9c8b6bf3aef24c3ff67683479/gh/soumyadeep589.Linked-List/log.txt) where the newer run has two warnings while the old run has only one warning.

So, a handful of screwy results but they seem entirely unrelated to this PR. And the code changes look fine.

@bors r+

**Pull request merged**
