### PR TITLE
Use DefIndex encoding that works better with on-disk variable length integer representations.

### PR DESCRIPTION
**Pull request by michaelwoerister**
Use the least instead of the most significant bit for representing the address space.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
r=me with the build fixed

There's a neat extension of this: you could interleave various categories of `DefId`s if you wanted to, and have `IndexVec`s that use a subset of the categories, converting indices on the fly.

**Comment by alexcrichton** [comment]
@michaelwoerister looks like travis may still have a panic?

**Comment by michaelwoerister** [comment]
Yes, that's something different though. I'll investigate.

**Comment by michaelwoerister** [comment]
Build fixed.

@bors r=eddyb

**Comment by michaelwoerister** [comment]
@bors retry

(looks like a timeout on appveyor)

**Pull request merged**
