### PR TITLE
Obligation forest tweaks

### PR DESCRIPTION
**Pull request by nnethercote**
A few minor improvements to the code.

r? @nikomatsakis

### CODE REVIEW

**Comment by nnethercote** [comment]
I'm not expecting much performance change, maybe a small improvement to `keccak` and one or two others.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Ugh, this was a tiny perf win for me locally. PGO's effects again, I suspect. I will try a few more CI perf runs, try to work out the problem.

**Comment by nnethercote** [comment]
Hooray, those new perf results are much better. @nikomatsakis, review away please! :)

**Review by nikomatsakis — APPROVED** [review]

**Comment by nnethercote** [comment]
Sigh, performance regression here. `keccak` stresses the process obligation code, and it's very easy for minor, seemingly inconsequential changes to change it a couple of percent, because e.g. register allocation in the hot paths change a tiny bit. E.g. here are the results for the past month:

Screen Shot 2022-06-21 at 7 52 23 am

Let's look at the `check full` results, particularly the instruction counts.

This PR was looking like a win when measured 15 days ago (2022-06-06):

keccak | check | full | -1.96% | 10.03x | 20,749,612,998 | 20,343,711,976
-- | -- | -- | -- | -- | -- | --

Since then, three intervening PRs landed that improved `keccak`.

After #97447 (2022-06-08):

keccak | check | full | -2.06% | 10.83x | 20,718,223,737 | 20,291,756,873
-- | -- | -- | -- | -- | -- | --

After #97778 (2022-06-11):

keccak | check | full | -0.79% | 6.05x | 20,284,132,956 | 20,123,775,316
-- | -- | -- | -- | -- | -- | --

After #96591 (2022-06-14):

keccak | check | full | -1.61% | 13.79x | 20,111,191,751 | 19,787,718,379
-- | -- | -- | -- | -- | -- | --

So that was nice.

And now, after this PR merged yesterday (2022-06-20):

keccak | check | full | 2.38% | 24.28x | 19,797,304,578 | 20,268,024,059
-- | -- | -- | -- | -- | -- | --

(All of the above is also true for `cranelift-codegen-0.82.1`, to a lesser extent.)

I'm inclined to accept this and move on, because:
- this PR made the code nicer, and 
- `keccak`'s instruction count is still lower than it was three weeks ago (3 steps forward, 1 step back, and I was responsible for two of those steps), and
- the results here are so easy to perturb, and
- this PR didn't affect cycle counts.
 
I may try one more time to recover the loss, but this code has already been optimized to the nth degree, so I probably won't spend long on it.

@rustbot label: +perf-regression-triaged

**Pull request merged**
