### PR TITLE
Fixes error count display is different when there's only one error left

### PR DESCRIPTION
**Pull request by Noratrieb**
Supersedes #114759

### What did I do?

I did the small change in `rustc_errors` by hand. Then I did the other changes in `/compiler` by hand, those were just find replace on `*.rs` in the workspace. The changes in run-make are find replace for `run-make` in the workspace.

All other changes are blessed using `x test TEST --bless`. I blessed the tests that were blessed in #114759.

### how to review this nightmare

ping bors with an `r+`. You should check that my logic is sound and maybe quickly scroll through the diff, but fully verifying it seems fairly hard to impossible. I did my best to do this correctly.

Thank you @adrianEffe for bringing this up and your initial implementation.

cc @flip1995, you said you want to do a subtree sync asap
cc @RalfJung maybe you want to do a quick subtree sync afterwards as well for Miri

r? @WaffleLapkin

### CODE REVIEW

**Review by WaffleLapkin — APPROVED** [review]

**Comment by WaffleLapkin** [comment]
@bors r+ rollup p=10

let's pray to ferris everything goes smoothly 🙏

**Comment by WaffleLapkin** [comment]
@bors rollup=never

🤣

**Comment by Nilstrieb** [comment]
I blessed it some more 🙏 
@bors r=WaffleLapkin

**Comment by Nilstrieb** [comment]
#118178 doesn't have conflicts! this could be it...
@bors r=WaffleLapkin p=13

**Comment by RalfJung** [comment]
There's always the option of closing the tree to land this without any race conditions.

**Comment by Nilstrieb** [comment]
@flip1995 @RalfJung it's merged!

**Pull request merged**
