### PR TITLE
Add variant/struct field search tab

### LINKED ISSUE #58229: [rustdoc search] Add search into struct fields/enum variants
Add a fourth tab.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #58229.

screenshot 2019-02-10 at 00 05 27

I'm just wondering if it's really useful though. Any other opinions would be very appreciated!

r? @QuietMisdreavus

### CODE REVIEW

**Comment by oli-obk** [comment]
At some point (when we get many of these), we should probably not make it a tab, but a dropdown menu

**Comment by GuillaumeGomez** [comment]
I'm open to any suggestions. :)

**Comment by QuietMisdreavus** [comment]
Is this searching for types being used in structs/variants, or for the names of the field/variant? If it's the latter, this tab is not useful - it's duplicating a subset of the first tab. I'm not familiar with how the search code looks at the index, and your screenshot makes it look like it's searching through names.

**Comment by Dylan-DPC** [comment]
ping from triage @GuillaumeGomez @QuietMisdreavus what's the update on this?

**Comment by QuietMisdreavus** [comment]
I can't easily tell from reading the code whether this is searching for variants/fields by name or by type. If it's just a way to limit a name-based search to variants/fields (as the image in the PR description indicates), i don't think it's useful enough to include - they should already be included in the "In Names" tab.

-----

It seems like the problem statement is something like this. Say you have the following crate:

```rust
pub struct SomeStruct;

pub struct OtherStruct {
  pub my_field: SomeStruct,
}
```

You should be able to search "SomeStruct" and get `OtherStruct::my_field` in the "In Variants/Fields" tab. That's a very useful feature that i would love to include.

**Comment by GuillaumeGomez** [comment]
I'll change this PR to go this way then. It'll match more what I had in mind to being with.

**Comment by Centril** [comment]
Ping from triage, @GuillaumeGomez, what's the status of this PR?

**Comment by GuillaumeGomez** [comment]
Still requires to be done.

**Comment by GuillaumeGomez** [comment]
I'll reopen once I'm done.

**Pull request closed without merging**
