### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #107043 (Support `true` and `false` as boolean flag params)
 - #107831 (Query refactoring)
 - #107841 (Handled snap curl issue inside Rust)
 - #107852 (rustdoc: remove unused fn parameter `tab`)
 - #107861 (Sync release notes for 1.67.1)
 - #107863 (Allow multiple candidates with same response in new solver)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=107043,107831,107841,107852,107861,107863)

### CODE REVIEW

**Comment by rylev** [comment]
@rust-timer build 5677b86c43cf70b41403958c90e2ade33123b6b3

**Comment by rylev** [comment]
It seems like #107831 is the cause of the regression cc @nnethercote @oli-obk

**Comment by oli-obk** [comment]
Looking at the graph, I think there is no regression here. This looks like a reversal of the "improvement" in https://perf.rust-lang.org/compare.html?start=9433ba63942a736f068baacf19e5cffaff6dccc9&end=ef934d9b632b8ac00276558824664c104b92b5f0&stat=instructions:u

**Comment by nnethercote** [comment]
The `wg-grammar` change is very likely noise. The `bitmaps` change I am less certain about. Although I wouldn't have expected this change to affect perf, I will do some local measurements to see if I can work anything out.

**Comment by nnethercote** [comment]
I did some local measurements with Cachegrind, starting with the current trunk and then de-applying the four commits from #107831 one at a time:
```
Original    2,579,711,048 (100.0%)  PROGRAM TOTALS
MinusQ4     2,579,711,451 (100.0%)  PROGRAM TOTALS
MinusQ3     2,579,646,820 (100.0%)  PROGRAM TOTALS
MinusQ2     2,579,439,041 (100.0%)  PROGRAM TOTALS
MinusQ1     2,579,437,639 (100.0%)  PROGRAM TOTALS
```
That's a 0.02% reduction in instruction counts by de-applying the four commits, i.e. negligible. Which strongly suggests that #107831 didn't have any meaningful perf effects.

**Pull request merged**
