### PR TITLE
Merge oli-obk mail addresses

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @Mark-Simulacrum

This appears to not be the right format. I think you want this list:

```
Oliver Scherer <oliver.schneider@kit.edu> <git-spam-no-reply9815368754983@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <git-spam9815368754983@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <github333195615777966@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <github6541940@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <rust19446194516@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <git-no-reply-9879165716479413131@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <git1984941651981@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <github35764891676564198441@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <github6541940@oli-obk.de>
Oliver Scherer <oliver.schneider@kit.edu> <oli-obk@users.noreply.github.com>
Oliver Scherer <oliver.schneider@kit.edu> <public.oliver.schneider@kit.edu>
Oliver Scherer <oliver.schneider@kit.edu> <obk8176014uqher834@olio-obk.de>
Oliver Scherer <oliver.schneider@kit.edu>
```

```
$ git shortlog -sne | grep Oliver
  1936  Oliver Scherer <oliver.schneider@kit.edu>
   168  Oliver Middleton <olliemail27@gmail.com>
     1  Oliver Forral <intrepion@gmail.com>
     1  Oliver Middleton <ollie27@users.noreply.github.com>
     1  Paul Oliver <puzza007@gmail.com>
```

**Comment by oli-obk** [comment]
oh... I saw some others like this format, thanks for fixing it up for me

**Comment by Alexendoo** [comment]
Ping from triage, any updates? @Mark-Simulacrum

**Pull request merged**
