### PR TITLE
coverage: Correctly report and check LLVM's coverage mapping version

### PR DESCRIPTION
**Pull request by Zalathar**
I was puzzled by the fact that the LLVM 18 update (#120055) didn't need to modify this version check, despite the fact that LLVM 18 uses a newer version of the coverage mapping format.

This turned out to be because we were inappropriately hard-coding a specific version (`Version6`) in the C++ wrapper, instead of using `CovMapVersion::CurrentVersion` to reflect the version actually used by LLVM on our behalf.

This PR fixes that, and also changes the Rust-side version check to accept the new coverage mapping version used by LLVM 18, since the necessary compatibility work has already been done.

---

### Quick history of `LLVMRustCoverageMappingVersion`:

- Originally it returned LLVM's `coverage::CovMapVersion::CurrentVersion`, as intended. The Rust-side code would verify it, and also embed it as the actual coverage version number in the output binary.
- At some point it was changed to a hard-coded value, to work around a (now-irrelevant) compatibility issue. This was incorrect (but mostly benign), because the override should have been performed on the Rust side instead, after verifying LLVM's value.
- Later contributors dutifully updated the hard-coded value, because they didn't have enough context to identify the problem.
- With this PR, it once again returns LLVM's current coverage version number, and the Rust-side code checks it against an expected range. We don't override the result, but we do indicate where that override should occur if it ever becomes necessary.

### CODE REVIEW

**Comment by Swatinem** [comment]
Is there some docs on what the changes in the new version are?
I remember updating to Version5 I believe had one backwards incompatible change to how the compile directory was treated.

We should still hardcode the version we are outputting.

**Comment by Zalathar** [comment]
One of the tricky things here is that we control the version number that gets embedded in the `__llvm_covmap` section, but we don't control the format version that LLVM uses when encoding filenames or covfun data on our behalf.

So now that the LLVM 18 update has landed, we're still writing a hardcoded V6 into the output binary, but the `__llvm_covfun` sections contain data that LLVM has encoded in the *V7* format.

(Currently we get away with this, because the layout of the V7 format happens to be compatible with V6, as long as we don't use the new MC/DC mapping types.)

**Comment by Zalathar** [comment]
If we want to keep hardcoding V6, we can still do that. (I think we shouldn't, but it's a reasonable position.)

But we shouldn't achieve that by having the C++ wrapper lie to the Rust code about what version LLVM thinks it's using. If we want to force V6, we should have the C++ code accurately report “LLVM is using V7”, and then have the Rust code explicitly decide that the two formats are sufficiently compatible that we can substitute V6 instead.

**Comment by Zalathar** [comment]
> Is there some docs on what the changes in the new version are?

Past changes are listed at <https://llvm.org/docs/CoverageMappingFormat.html#llvm-ir-representation>, but not in very much detail. It looks like whoever added the MC/DC stuff to LLVM for V7 didn't update the per-version changes at all.

So the main reference for what has changed is `CoverageMappingReader.cpp` (and its associated headers), since that is LLVM's backwards-compatible coverage mapping parser. Looking at that file, it seems that the only changes in V7 were the introduction of two new entries in `enum RegionKind` for MC/DC coverage support. We never try to emit those new region kinds, so currently when we ask LLVM to encode one of our covfun entries, it produces bytes that happen to be compatible with both V6 and V7.

**Review by Swatinem — APPROVED** [review]
lgtm.

Looks like I misunderstood things, but it is perfectly obvious now. As we are just calling through to LLVM to generate some of the coverage output, we are at the mercy of the format that the currently linked LLVM outputs.

So it makes no sense at all to hardcode a specific format, as the underlying LLVM can and will make changes.

It is a bit unfortunate that the output format is split between a part that comes from LLVM, plus some other things on top that we output directly from the Rust side, and these things better be in sync.

**Comment by Zalathar** [comment]
Originally I had missed the fact that we do control the version number written into the output; I only noticed that while investigating things to answer your original feedback.

But I got lucky, because it turned out that my original changes were still correct, just for a slightly different reason than what I previously had in mind.

**Comment by Zalathar** [comment]
I have changed the new code slightly, to make it much clearer that the version number isn't just used for a version check; it  is also the version number that we end up embedding in the covmap section [(diff)](https://github.com/rust-lang/rust/compare/40d117f1fd725de24776ce722f45424a1c62810e..5ac6323cc1ff6aaff5f1907879cc91b64a4d672f).

That should hopefully reduce some of the confusion that got us into this situation in the first place.

**Comment by workingjubilee** [comment]
r? compiler

**Pull request merged**
