### PR TITLE
rustdoc: update pulldown + fix spurious rendering difference around footnotes

### LINKED ISSUE #45420: Footnotes don't display properly under CommonMark
[This footnote](https://github.com/rust-lang/rust/blob/87a8e8e07387f99ffe931b1f2bbc4c0585b16ccc/src/libcore/lib.rs#L13) generates different HTML under `--enable-commonmark` and not. Not only does this trigger what's effectively a spurious warning, but it doesn't render correctly either.

cc @QuietMisdreavus @GuillaumeGomez , marking this as p-high

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
fixes #45420

### CODE REVIEW

**Comment by steveklabnik** [comment]
This does not fix the issue:

```
WARNING: documentation for this crate may be rendered differently using the new Pulldown renderer.
    See https://github.com/rust-lang/rust/issues/44229 for details.
WARNING: rendering difference in `# The Rust Core Library`
   --> src\libcore\lib.rs:11:0
    /html[0]/body[1]/p[1] Attributes differ in `sup`: expected: `{"id": "supref1"}`, found: `{"id": "fnref1"}`
WARNING: rendering difference in `# The Rust Core Library`
   --> src\libcore\lib.rs:11:0
    /html[0]/body[1]/div[7]/ol[1] Attributes differ in `li`: expected: `{"id": "ref1"}`, found: `{"id": "fn1"}`
```

**Comment by steveklabnik** [comment]
(We should still land this, as I believe it *does* fix rendering issues, or so I hear; I haven't validated that myself yet. But it doesn't fix the warning)

**Comment by QuietMisdreavus** [comment]
I've just pushed an update that adds a check to bypass reporting a warning if the difference was with `id` attributes that follow the pattern pulldown and hoedown use for footnotes. Some structural differences were still fixed with the version bump, but the last rendering difference surrounding footnotes should be gone with that check.

**Comment by steveklabnik** [comment]
With my PR + this PR, we have no warnings 🎊 

@bors: r+

**Comment by ollie27** [comment]
The ids are generated by rustdoc so they could have been changed to match hoedown: https://github.com/rust-lang/rust/blob/cc03782b93f210a23ed792800b08c1ebad0a8820/src/librustdoc/html/markdown.rs#L374

**Comment by QuietMisdreavus** [comment]
@ollie27 D'oh! Since this is already in the middle of a rollup, i'll grab that in a separate PR. Nice catch!

**Comment by kennytm** [comment]
@QuietMisdreavus No it failed to make into the rollup 😄

**Comment by QuietMisdreavus** [comment]
@kennytm Oh, didn't notice that, oops. `>_>;;`

Take two! I just force-pushed a different update that uses @ollie27's suggestion rather than writing in a warning suppression. I ran it locally and it fixed the rendering differences in libcore the same as the other way, only this time it's because it's actually the same.

**Comment by kennytm** [comment]
@GuillaumeGomez @ollie27 Is this PR good to go?

**Comment by GuillaumeGomez** [comment]
Seems good for me.

**Comment by QuietMisdreavus** [comment]
r? @steveklabnik 

Since the footnote mitigation changed after the initial approval, this is worth another look before i blindly re-r+ it.

**Pull request merged**
