### PR TITLE
Bump stage0 to 1.80.0

### PR DESCRIPTION
**Pull request by emilyalbini**
r? @Mark-Simulacrum

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by lqd** [comment]
It looks like rust-lld is also unexpectedly enabled on beta, so it seems prudent to wait for that to be fixed before bumping stage0 here. I'm analyzing/fixing rn.

**Comment by lqd** [comment]
IIUC doing this will prevent contributors on nixos from being able to work on the compiler

**Comment by lqd** [comment]
> IIUC doing this will prevent contributors on nixos from being able to work on the compiler without disabling lld in the config — it doesn’t work there just yet.

cc @WaffleLapkin: I've fixed this on beta already, but we'll need a new beta released + another stage0 bump

**Comment by WaffleLapkin** [comment]
@lqd note that having `[rust] lld = false` in `config.toml` did not help me, I assume `rust.lld` does not influence stage0 things or something?...

**Comment by lqd** [comment]
Exactly, it does influence from stage1. There’s another beta bump in the queue that will fix it (or rustflags until then) if it hasn’t landed already,

**Pull request merged**
