### PR TITLE
Update LLVM submodule

### PR DESCRIPTION
**Pull request by nikic**
Update LLVM submodule with recent cherry-picks. In particular:
 * https://github.com/rust-lang/llvm-project/pull/123
 * https://github.com/rust-lang/llvm-project/pull/124

### CODE REVIEW

**Comment by nikic** [comment]
@bors try @rust-timer queue

Merge functions changes may have compile-time impact.

**Comment by cuviper** [comment]
The `MergeFunctions` change was for #91490 -- do you have a testcase to prove its worth?
(Then we can better justify the regression...)

**Comment by nikic** [comment]
The regression here is expected in that we perform function merging later -- this means that we merge more functions, but also that we process more duplicate functions until that point. Function merging is currently intended as a code size optimization rather than a compile-time optimization, though it may be worthwhile to investigate adding an additional MergeFunctions run early in the pipeline.

@cuviper The LLVM side test case is basically just the IR from the report in #91490. I can add that as a codegen test here as well.

**Pull request merged**
