### PR TITLE
Remove ANTLR grammar

### LINKED ISSUE #15677: antlr is losing information
See http://stackoverflow.com/questions/24747360/distinguishing-literal-n-vs-embedded-newline. Until there is a resolution to this, the lexer verification is ignoring the contents every token that carries data :(

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
I *think* that nothing in-tree references this, but I may be wrong. If anyone thinks of anything, please let me know and I'll work on removing.

Fixes #15677.

### CODE REVIEW

**Comment by nagisa** [comment]
This PR also removes the YACC grammar, which is independent of the ANTLR one and should have been left intact?

**Comment by Mark-Simulacrum** [comment]
I'd be happy to undo parts of this PR, however I'm not certain what files the YACC grammar consisted of. Could you specify those? I'll put up a PR restoring them.

**Comment by nagisa** [comment]
At least `parser-lalr-yaml.c`, the `.y` and `.l` file, probably the `.h` file too. The `.py` script might have been used for lalr, though not entirely sure. Also would be great to keep the string ambiguity text.

**Pull request merged**
