### PR TITLE
[perf-test] Do not wrap metadata into an object file

### PR DESCRIPTION
**Pull request by petrochenkov**
while still keeping it at the first position in the archive.

The PR as is doesn't work on all platforms, but it should be enough to perf-test it on Linux.

### CODE REVIEW

**Comment by bjorn3** [comment]
```
2022-08-27T13:35:34.3923103Z error: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/remap-path-prefix-dwarf/remap-path-prefix-dwarf/abs_input_outside_working_dir.rlib(lib.rmeta): The file was not recognized as a valid object file
```

This is the exact kind of error wrapping crate metadata in object files is meant to prevent.

**Comment by petrochenkov** [comment]
@bjorn3 
On Linux that's a deficiency of llvm-dwarfdump specifically, though.
You can see that otherwise the dist build was successfully prepared.

**Comment by bjorn3** [comment]
Mold fails to link archives with non-elf files:

```
$ rustc - --crate-type staticlib     # just a quick way to create an archive with valid object files
$ cat "some metadata" > lib.rmeta
$ ar q librust_out.a lib.rmeta       # add lib.rmeta to the librust_out.a archive
$ ./mold -m elf_x86_64 lib.rmeta
mold: fatal: lib.rmeta: unknown file type
```

even with `lib.rmeta` being at the end of the archive. While fixing llvm-dwarfdump and mold individually would be possible, it is clear that there are a lot of tools out there that assume archives only contain object files. Some of such tools may even want to explicitly disallow non-object files to catch mistakes.

**Comment by petrochenkov** [comment]
Not an improvement, especially considering the downsides.
Although the artifact sizes are slightly smaller.

**Pull request closed without merging**
