### PR TITLE
Fix linkage diagnostic so it doesn't ICE for external crates

### LINKED ISSUE #59548: ICE in librustc_codegen_llvm when building kernel
Basic issue while I start digging deeper into the issue. Compiling the kernel in https://github.com/thepowersgang/rust_os/tree/4eefae2ce0db2ba62714dbedc31094a756275651 using xargo causes rustc to ICE in `librustc_codegen_llvm`

In cleaning up for commit, I've isolated it to https://github.com/thepowersgang/rust_os/blob/4eefae2ce0db2ba62714dbedc31094a756275651/Kernel/main/main.rs#L34, which causes the ICE if uncommented.

```
  Compiling main v0.0.0 (/home/tpg/Projects/rust_os/Kernel)
error: internal compiler error: src/librustc_codegen_llvm/consts.rs:121: must have type `*const T` or `*mut T`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:634:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc_codegen_llvm::consts::check_and_apply_linkage
  15: rustc_codegen_llvm::consts::<impl rustc_codegen_llvm::context::CodegenCx>::get_static
  16: rustc_codegen_llvm::common::<impl rustc_codegen_ssa::traits::consts::ConstMethods for rustc_codegen_llvm::context::CodegenCx>::scalar_to_backend
  17: rustc_codegen_llvm::consts::const_alloc_to_llvm
  18: rustc_codegen_llvm::common::<impl rustc_codegen_ssa::traits::consts::ConstMethods for rustc_codegen_llvm::context::CodegenCx>::scalar_to_backend
  19: rustc_codegen_llvm::consts::const_alloc_to_llvm
  20: rustc_codegen_llvm::consts::codegen_static_initializer
  21: rustc_codegen_llvm::consts::<impl rustc_codegen_ssa::traits::statics::StaticMethods for rustc_codegen_llvm::context::CodegenCx>::codegen_static
  22: rustc_codegen_ssa::mono_item::MonoItemExt::define
  23: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  24: rustc::dep_graph::graph::DepGraph::with_task
  25: rustc_codegen_llvm::base::compile_codegen_unit
  26: rustc_codegen_ssa::base::codegen_crate
  27: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  28: rustc::util::common::time
  29: rustc_interface::passes::start_codegen
  30: rustc::ty::context::tls::enter_global
  31: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  32: rustc_interface::passes::create_global_ctxt::{{closure}}
  33: rustc_interface::passes::BoxedGlobalCtxt::enter
  34: rustc_interface::queries::Query<T>::compute
  35: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  36: rustc_interface::interface::run_compiler_in_existing_thread_pool
  37: std::thread::local::LocalKey<T>::with
  38: scoped_tls::ScopedKey<T>::set
  39: syntax::with_globals
query stack during panic:
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (e782d790f 2019-03-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C target-feature= --crate-type staticlib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `main`.

```

### LINKED ISSUE #61232: need test of external linkage symbol collision
The `#[linkage]` feature has some code that generates a symbol, e.g. for `foo` it generates `extern_with_linkage_foo`.

We have some code that causes the compilation to fail if it can detect that the generated symbol is the source of a collision.

https://github.com/rust-lang/rust/blob/46805805abe58c287fa16963f897fd09d5d97467/src/librustc_codegen_llvm/consts.rs#L130-L147

But as far as I can tell, we have no tests of this feature.

While I was working on PR #61231, I tried to manufacture such a test, but it was not obvious to me how to actually set things up to make the scenario happen. I don't want to forget about the need for this test after I put that task aside, so I'm filing this issue.

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix linkage diagnostic so it doesn't ICE for external crates

(As a drive-by improvement, improved the diagnostic to indicate *why* `*const T` or `*mut T` is required.)

Fix #59548 
Fix #61232

### CODE REVIEW

**Comment by pnkfelix** [comment]
As I [commented](https://github.com/rust-lang/rust/issues/59548#issuecomment-495619851) on the issue, I have a separate change drafted (but not yet posted to a PR) that adds a similar check earlier in the compiler pipeline, so that we would get this error at the definition site where the attribute occurs, rather that at the usage site where the item is used. (That is, AFAICT, when you add this attribute to an incompatibly-typed definition, there is *no* way to use it correctly, so we should consider erroring at the definition site instead.)

That would be a somewhat riskier change, since it would actually break existing code, unlike this PR, which is strictly keeping the compiler's behavior the same in non-ICE cases. But then again, this is an unstable feature anyway, so we don't have to be *quite so* cautious.

**Comment by Centril** [comment]
> But then again, this is an unstable feature anyway, so we don't have to be _quite so_ cautious.

I agree, I suspect the feature isn't so widely used anyways so I think it would be good to follow this up with your draft.

**Comment by pnkfelix** [comment]
> > But then again, this is an unstable feature anyway, so we don't have to be _quite so_ cautious.
> 
> I agree, I suspect the feature isn't so widely used anyways so I think it would be good to follow this up with your draft.

The problem is that we would need to decide which variants of `#[linkage="..."]` to apply the check to.

(The way the code in `consts.rs` is written, one might infer that it applies to *all* variants of `#[linkage="..."]`; but other tests in our test suite seem to invalidate that inference.)

**Comment by pnkfelix** [comment]
> > > But then again, this is an unstable feature anyway, so we don't have to be _quite so_ cautious.
> > 
> > 
> > I agree, I suspect the feature isn't so widely used anyways so I think it would be good to follow this up with your draft.
> 
> The problem is that we would need to decide which variants of `#[linkage="..."]` to apply the check to.

One reason that answering this question may be harder than you expect is that back in PR #18890, we blindly added support for *all* variants of `#[linkage="..."]` without really trying to check whether they make any sense.

The comments for the code that parses the variant sort of hints at this:



https://github.com/rust-lang/rust/blob/ae8975c812c5f31102f1f840322e10696b369aa7/src/librustc_typeck/collect.rs#L2485-L2489

but the point is, its pretty hard to go through and write tests for each case when some of them do not seem to make any sense for definitions in Rust code. Consider e.g. the [appending case][linkage-types] from LLVM:

[linkage-types]: https://llvm.org/docs/LangRef.html#linkage-types

>    “appending” linkage may only be applied to global variables of pointer to array type. When two global variables with appending linkage are linked together, the two global arrays are appended together. This is the LLVM, typesafe, equivalent of having the system linker append together “sections” with identical names when .o files are linked.
> 
>  Unfortunately this doesn’t correspond to any feature in .o files, so it can only be used for variables like llvm.global_ctors which llvm interprets specially.

**Comment by pnkfelix** [comment]
Another reason why its tricky to "just" go through and try writing tests for each `#[linkage="..."]`: we basically *can't* put it on non-extern statics, because the existing check forces all uses of `#[linkage="..."]` to be a raw ptr (`*const T` or `*mut T`), but Rust itself forces definitions of non-extern statics to be `Sync`, and raw ptrs are never `Sync`.

(This may just be adding fuel to the argument that I should not be worrying about adding the check at the definition site. I am going to switch to looking at the cases that fail in our test suite when that definition site check is added, as that will help me understand what cases we supposedly support now.)

**Pull request merged**
