### PR TITLE
Fix `#[link kind="raw-dylib"]` to respect `#[link_name]`

### PR DESCRIPTION
**Pull request by dpaoliello**
Issue Details:
When using `#[link kind="raw-dylib"]` (#58713), the Rust compiler ignored any `#[link_name]` attributes when generating the import library and so the resulting binary would fail to link due to missing symbols.

Fix Details:
Use the name from `#[link_name]` if present when generating the `raw-dylib` import library, otherwise default back to the actual symbol name.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/101854#issuecomment-1248252330)

@bors r-

**Comment by wesleywiser** [comment]
@bors r=petrochenkov

The rollup failed due to a different PR.

**Comment by wesleywiser** [comment]
This made it to nightly before the beta cutoff and it is included in the same release as the `raw-dylib` stabilization PR so no backport is needed.

**Pull request merged**
