### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #105848 (rustdoc: Add a new lint for broken inline code)
 - #108611 (lint/ctypes: ext. abi fn-ptr in internal abi fn)
 - #110614 (Clear response values for overflow in new solver)
 - #110901 (rustdoc: Fix missing `repr` attribute in doc(inline) on foreign items)
 - #110921 (Use `NonNull::new_unchecked` and `NonNull::len` in `rustc_arena`.)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=105848,108611,110614,110901,110921)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems flaky.

@bors retry

**Comment by ehuss** [comment]
@bors retry

python setuptools issue

**Comment by GuillaumeGomez** [comment]
Still an issue apparently. Should we wait a bit before retrying?

**Comment by ehuss** [comment]
@bors p=50

trying again, it's not obvious to me what might be the cause

**Pull request closed without merging**
