### PR TITLE
Adds a bit-scan iterator (iter_eq) and bit-run iterator (iter_runs) to Bitv

### PR DESCRIPTION
**Pull request by sivadeilra**
have a particular value (true / false).  The performance of this
iterator is dependent on the density of the searched-for value in
the Bitv.  (A Bitv that has a length L and a density of ~25% has
about 1 in 4 bits set to 1.)  For bit vectors that are relatively
sparse, iter_eq() is much more efficient than the naive
implementation, by a factor of about 10:1.  For bit vectors with
a density of around 25%, iter_eq() has about the same performance
as the naive implementation.  For bit vectors that are very dense
(80%+), the naive implementation is faster by about 2:1.

Developers can choose to use iter_eq(), either for convenience or
for performance (when they know that density will be <= 25%, or
close enough not to matter).  Developers who need to deal with
bitmaps that have much higher density and are using very large
bitmaps should probably use the naive implementation.

This also adds a method for finding "runs" of bits in Bitv, which
are contiguous sequences of bits that all have the same value.

This includs benchmarks and unit tests for all new functionality.
There are also benchmarks for the "naive" implementation (two
different versions, in fact), in order to show the difference in
performance.

### CODE REVIEW

**Comment by Gankro** [comment]
This just seems like more evidence to me that we should be seriously considering exposing the underlying blocks.

**Comment by sivadeilra** [comment]
I agree.  I think Bitv should expose the underlying blocks, and should commit to a representation of Vec<u32> basically forever.  If someone finds that using a larger size helps, then maybe Bitv becomes Bit<U : UInt>.  Or the representation stays u32, but std provides a safe conversion from &[u32] to &[u64].

**Comment by sivadeilra** [comment]
Spoke with Gankro on IRC, agreed to postpone this >1.0, since this affects public APIs.

**Pull request closed without merging**
