### PR TITLE
incr.comp.: Fix potential unstable Fingerprint error for BorrowCheckResult

### PR DESCRIPTION
**Pull request by michaelwoerister**
This potentially fixes issue https://github.com/rust-lang/rust/issues/96655, but I was not able to actually reproduce it.

r? @Aaron1011

### CODE REVIEW

**Comment by lqd** [comment]
@bors try

so we can the CI artifacts on the other issues

**Comment by Aaron1011** [comment]
r=me once you've performed any additional testing with the CI artifact toolchain.

**Comment by michaelwoerister** [comment]
@rust-timer queue

**Comment by michaelwoerister** [comment]
@rust-timer build 3d838c809141fd15465b18559757a34c360c11d4

**Comment by michaelwoerister** [comment]
@bors r=Aaron1011

https://github.com/rust-lang/rust/pull/98959 probably fixes the underlying source of indeterminism, but this PR doesn't seem to hurt performance and provides an additional safety measure if there are additional instabilities.

The real fix will be to make progress on https://github.com/rust-lang/rust/pull/94188 and use a collection type that doesn't leak iteration order into fingerprints.

**Comment by apiraino** [comment]
Based on the latest tests failures. I'll switch to waiting on author, if it's ok. Feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

**Pull request closed without merging**
