### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #127054 (Reorder trait bound modifiers *after* `for<...>` binder in trait bounds)
 - #127528 (Replace ASCII control chars with Unicode Control Pictures)
 - #127872 (Migrate `pointer-auth-link-with-c`, `c-dynamic-rlib` and `c-dynamic-dylib` `run-make` tests to rmake)
 - #128111 (Do not use question as label)
 - #128160 (Don't ICE when auto trait has assoc ty in old solver)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=127054,127528,127872,128111,128160)

### CODE REVIEW

**Comment by Kobzol** [comment]
https://github.com/rust-lang/rust/pull/127528 was the culprit, it is being reverted in https://github.com/rust-lang/rust/pull/128179.

**Comment by lqd** [comment]
isn't that PR only for diagnostics? ie indicating that the benchmarks produce warnings, but are not real slowdowns of the compiler?

**Comment by Kobzol** [comment]
Is is possible, although the regression was bad enough that I think a revert and a follow-up investigation of the perf result is mostly warranted.

On a related note, it would be good to know the size of the diagnostics outputted by our current benchmarks, it's quite probable that it is excessive. I will try to take a look at it later.

**Comment by lqd** [comment]
With all the new lints, and changes to existing ones, it wouldn't be surprising that there are enough that diagnostics change "impact benchmarks but not performance". That ties to the topic of doing something about this behavior, which was discussed on zulip a while back.

**Comment by estebank** [comment]
I'm catching up on this. I am surprised that the benchmarks are affected because in my mental model they were not affected by slowdowns on the diagnostics machinery itself. I can see this been an actual regression on the time it takes *to render* diagnostics, because now we are unconditionally calculating the character width for underlines, whereas before that was kept in an unconditionally pre-calculated table. The new behavior is *more correct*, but we'd have to see how/if we can mitigate the regression. I noticed that syn is one of the most significantly impacted, which in my head points at TokenString rendering, maybe. I would love some help actually understanding *what* actually regressed, because looking at [the perf summaries](https://perf.rust-lang.org/detailed-query.html?commit=e3343bd96d6125c21f3e32f4be744b7c026ec6b2&benchmark=syn-1.0.89-debug&scenario=incr-unchanged&base_commit=e7d66eac5e8e8f60370c98d186aee9fa0ebd7845&sort_idx=-11) I'm seeing `codegen_copy_artifacts_from_incr_cache`, `early_lint_checks` and `LLVM_passes` highlighted as affected places, where the last one I don't see how it could possibly be affected, and the first one should be *faster* because we're storing less info...

**Comment by lqd** [comment]
> I would love some help actually understanding _what_ actually regressed

In the benchmark results, when you click on one there's a graph to help you see if the change could be noise, and a command at the bottom to run a cachegrind diff locally, which helps see where the slowdowns come from. 

image


For example for the syn incr-unchanged one, cachegrind shows the following for me:
```
--------------------------------------------------------------------------------
Ir
--------------------------------------------------------------------------------
52,077,877  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir           file:function
--------------------------------------------------------------------------------
 14,769,207  library/core/src/slice/memchr.rs:core::slice::memchr::memchr_aligned
 14,357,444  ???:<rustc_parse::parser::Parser>::collect_tokens_for_expr::<<rustc_parse::parser::Parser>::parse_expr_dot_or_call::{closure#0}>::{closure#0}
-10,438,596  ???:<rustc_parse::parser::Parser>::parse_expr_dot_or_call::{closure#0}
 10,289,602  ???:rustc_errors::emitter::normalize_whitespace
  9,335,170  <all-jemalloc-files>:<all-jemalloc-functions>
  4,937,003  ???:<rustc_errors::emitter::HumanEmitter>::emit_messages_default_inner::{closure#0}
 -4,596,152  ???:<rustc_parse::parser::Parser>::parse_path_inner
  3,466,792  ???:alloc::raw_vec::finish_grow::<alloc::alloc::Global>
  2,927,330  ???:<rustc_span::source_map::SourceMap>::lookup_char_pos
  2,498,800  ???:???
...
```

As you expected: more string searching, slower whitespace normalization, more memory allocations, etc.

And since I similarly was confused by the results, yes, `syn-1.0.89` currently generates a lot of warnings. 
```
warning: `syn` (lib) generated 514 warnings (90 duplicates)
``` 

That IMHO makes this not really a regression, nor needing a revert. #128200 gains some perf back, it's still doing more work than prior to #127528 and that is perfectly fine for diagnostics.

**Comment by Kobzol** [comment]
Thanks a lot for the analysis! I agree that especially with https://github.com/rust-lang/rust/pull/128200, the revert is not needed.

**Comment by pnkfelix** [comment]
* the bulk of the regressions are to syn (i.e. 8 out of the 9 that are > 1%).
* this was due to a change in how diagnostics handle certain "whitespace" characters (PR #127528); there is a revert proposed in PR #128179, but there is also a PR to address the issue itself as a followup in PR #128200
* not marking as triaged until either PR #128179 or PR #128200 is landed.

**Pull request merged**
