### PR TITLE
Change deprecation warning to indicate custom derive support was removed

### PR DESCRIPTION
**Pull request by JordiPolo**
I'm very new to Rust and the message was confusing to me (using nightly and not really sure if I was > 1.15 or not).

### CODE REVIEW

**Comment by keeperofdakeys** [comment]
Custom derive support hasn't actually been removed as yet, it's still deprecated.

@jseyfried Should this just be a generic deprecation warning with no deadline?

P.S. Currently this error is printed for misspelled derives. This has been fixed in beta and master (so the next nightly). No one should see this error now unless they actually try to use a custom derive.

**Comment by jseyfried** [comment]
Yeah, I think this should be a generic deprecation warning with no deadline.

I see no reason to remove legacy custom derives before the rest of the legacy plugin system -- @keeperofdakeys fixed these false positive deprecation warnings, and after to our recent refactorings, legacy custom derives add very little extra complexity to the legacy plugin system.

**Comment by JordiPolo** [comment]
I've update the message to what I think you mean is the current status. Tell me if this is correct or should I do something different (or close the PR, etc).

**Comment by jseyfried** [comment]
@JordiPolo Thanks!
@bors r+ rollup

**Pull request merged**
