### PR TITLE
unicode.py refactor part 1

### PR DESCRIPTION
**Pull request by clarfonthey**
I will follow this up with more changes in future PRs, although I figure that this work so far is enough to have an initial PR. The first commit here is just #50920, which is simple enough that it can be merged immediately; as such, this should be merged after #50920.

The goal of this is to simplify this file so that it's easier to understand and maintain. Moving the conversion logic into `mapping_table.rs` should make it easier to modify the case mapping tables for size and/or performance, which I also plan to do in a future PR.

The contents of `tables.rs` don't actually change until the last commit.

### CODE REVIEW

**Comment by pietroalbini** [comment]
Picking someone from libs, r? @alexcrichton

**Comment by clarcharr** [comment]
@SimonSapin I agree that a fully-Rust version is ideal long term, although the main purpose of this is to make smaller changes that are easier to merge than a complete rewrite. I knew of `ucd-generate` and `unic`'s build scripts but still decided to go with this anyway, as it's a better short term solution.

**Comment by SimonSapin** [comment]
In short, I don’t get the point of refactoring code if we have plans to entirely replace that same code.

**Comment by pietroalbini** [comment]
Ping from triage @SimonSapin! What should we do with this PR then? Close it?

**Comment by SimonSapin** [comment]
I was hoping to discuss this some more with @clarcharr so that we find consensus, rather than closing unilaterally. @clarcharr should we hop on IRC at some point?

**Comment by clarcharr** [comment]
I'd definitely be interested in talking more about this on IRC. I've been a bit busy this week and haven't had much time to get around to this.

I'll open another PR after having some more discussion about this, but I'm not sure how long that'll be. I'll close this for now.

**Pull request closed without merging**
