### PR TITLE
Rename `MaybeUninit` to `MaybeUninitialized`

### PR DESCRIPTION
**Pull request by shepmaster**
Proposal to finalize the name as `MaybeUninit` https://github.com/rust-lang/rust/pull/56138#issuecomment-456192667 -- as in, the FCP is to *close* this PR.

rfcbot comment is [here](https://github.com/rust-lang/rust/pull/56138#issuecomment-456192671)

------------------

Changed via:

```
git ls-files -z | xargs -0 -L1 gsed --in-place 's@\bMaybeUninit\b@MaybeUninitialized@'
```

Checked via:

```
rg -uuu '\bMaybeUninit\b'
```

### CODE REVIEW

**Comment by shepmaster** [comment]
I know this is racing your other PR, so you get to review!

**Comment by RalfJung** [comment]
Fine for me. @rust-lang/libs @rust-lang/lang any objections?

**Comment by withoutboats** [comment]
What's the motivation for this change?

**Comment by shepmaster** [comment]
Wrds r btr thn abbrs.

**Comment by shepmaster** [comment]
For full context, if you start reading the comments [here](https://github.com/rust-lang/rust/issues/53491#issuecomment-438571746), there's an overwhelming consensus to add more words into the method names of this type to better indicate their unsafety and usage concerns.

Since the point of all of those words is to force the user to think more about careful usage of this type, making sure that the type's name itself is unambiguous is a good start.

**Comment by shepmaster** [comment]
Ok

**Comment by SimonSapin** [comment]
There is also a precedent in the standard library to *avoid* sometimes-well-established abbreviations: `copy_from_nonoverlapping`, `set_permissions`, etc.

**Comment by varkor** [comment]
> We usually avoid abbreviations unless they are extremely widely used (like pretty much all of @withoutboats' examples).

I think some of the examples like `Iter` and `Buf` are not "extremely widely used" (at least compared to `Uninit`), but are similarly unambiguous. (Personally, I prefer shorter names when unambiguous.)

**Comment by RalfJung** [comment]
Note that this replaces `mem::uninitialized`, so the precedent here clearly is to not abbreviate.

**Comment by nikic** [comment]
`mem::uninit()` is ambiguous in that it can abbreviate both uninitialized (a state) and uninitialize (and operation). The ambiguity does not exist with `MaybeUnint`, which clearly refers to a state.

**Comment by joshtriplett** [comment]
I certainly don't want to see this used often, but at the same time, this seems like unnecessary syntactic salt.

**Comment by Centril** [comment]
My main gripe is with `into_inner` which is innocent looking and misleading; that's where the actual unsafety lies and that's where I think adjustment is necessary.

I don't think a lot is gained by lengthening the name of the type here but at the same time I don't feel the need for unsafe code to be overly ergonomic to write. So my reaction to this PR is pretty neutral. I'm not for nor against it -- if you can convince everyone else then I'm sold. :)

**Comment by ogoffart** [comment]
Here is my opinion:
I have learned that one should generally avoid abbreviation unless there is a good reason to do so. For example if it is extremely common, or if the abbreviation is a common term in the industry.

Since class is not common (quite the contrary, it is an unsafe class to be used with care), I'd tend to say that it should be renamed. But this is not a strong opinion and i have no say in the matter.

**Comment by alexcrichton** [comment]
The libs team during triage discussed this and concluded that the renaming is good!

**Comment by stjepang** [comment]
I'm afraid expressions like `MaybeUninitialized::new(UnsafeCell::new(value))` will be common in unsafe code. This is not pretty. Can we perhaps keep the old name or think of a shorter one?

> there's an overwhelming consensus to add more words into the method names of this type to better indicate their unsafety and usage concerns.

> but at the same time I don't feel the need for unsafe code to be overly ergonomic to write

> Since class is not common (quite the contrary, it is an unsafe class to be used with care), I'd tend to say that it should be renamed.

I'd like to push against this idea. My (unpopular) opinion is that we should make unsafe code *more* ergonomic, not less.

First, Rust already discourages us from writing unsafe code with unergonomic syntax (long names, ugly raw pointers, `unsafe {}`). I often have to write unsafe code (because there's no other way) and don't enjoy it at all.

Second, unsafe code tends to look messy because of nested parentheses, `&` and `*` symbols, `*const` and `*mut`, long names like `ManuallyDrop` and `copy_nonoverlapping`, and so on. This makes reading code more difficult than it should be, which means it gets easier to overlook bugs.

Instead of making unsafe Rust even more painful to write, let's focus on making unsafe code easier to read and review for correctness.

**Comment by withoutboats** [comment]
I'm still against renaming this (and if we FCP'd it I would register a concern). @stjepang's post expresses my opinion well. This adds noise without adding information to code that should have as little noise as possible. The attitude that unsafe code should be unergonomic seems completely counterintuitive to me: this kind of code should have as high a signal to noise ratio as possible to make it easier to audit.

**Comment by alexcrichton** [comment]
Ok sounds like this wasn't blocked on the team then? There's favor for the current name? (those canvased were all very ambivalent...)

**Comment by joshtriplett** [comment]
I personally would favor keeping the existing name. I don't think we should add syntactic salt to make unsafe more painful.

**Comment by sfackler** [comment]
Should we minimize salt by following in the Unix tradition of renaming to `MbUnnt`?

I don't see the full name as adding salt, but rather as spelling the thing out in the same way we do with almost all other APIs in the standard library. We have `mem::uninitialized`, not `mem::uninit`. We have `std::process::Command`, not `std::proc::Cmd`.

**Comment by joshtriplett** [comment]
I'd suggest that we spell things out enough for clarity, but not excessively so. We have `u64`, not `uint64` or `unsigned_integer_64`. We have `min` and `max`, not `minimum` and `maximum`.

**Comment by shepmaster** [comment]
> We have `u64`, not `uint64` or `unsigned_integer_64`. We have `min` and `max`, not `minimum` and `maximum`.

These examples have a wide-reaching understanding, transcending Rust (although in retrospect `u64` over `uint64` is a bit suspect). While many other languages have the (sometimes accidental) concept of uninitialized values, none that I am familiar with make you go out of your way as much as Rust.

There's also the argument of [Huffman coding](https://en.wikipedia.org/wiki/Huffman_coding); making *common* things shorter and less-frequent things longer. I hope that `MaybeUninitialized` is orders of magnitude less common than `i32`!

**Comment by withoutboats** [comment]
@sfackler That feels like a very disingenuous argument to me. I think its obviously a very core part of the argument not to change the name is that `MaybeUninit` is still very clear about what it means, whereas `MbUnnt` is line noise. 

I don't think adding `ialized` to the end of the type provides useful information about what this type's behavior is. Meanwhile, it makes it much less ergonomic to use, as types become things like `MaybeUninitialized<UnsafeCell<RawHandle>>`, as @stjepang alluded to. If this is too unergonomic, users are tempted to just use `mem::unitialized`. Its important that users feel that the typing on their keyboards is worth the type safety they get.

The reason to use a more abbreviated from here than was used for `mem::unitialized` is specifically they're differences, that this is a wrapper around a type that must appear repeatedly, whereas the other was just a constructor for any type, that elided any other information about the type being constructed.

**Comment by Centril** [comment]
> Its important that users feel that the typing on their keyboards is worth the type safety they get.

@withoutboats  Well if we want to take this even further, `MaybeInit` is shorter ;)

**Comment by withoutboats** [comment]
> There's also the argument of Huffman coding; making common things shorter and less-frequent things longer. I hope that MaybeUninitialized is orders of magnitude less common than i32!

MaybeUninit is nearly 4 times longer than i32! i32 has already been shorted from `"32 bit integer"` to 3 characters in length because it is so common, Huffman coding is playing out naturally. But no one has demonstrated any chance of conflict or ambiguity with the name MaybeUninit, its really hard for me to understand what the advantage of adding "ialized" is.

**Comment by glaebhoerl** [comment]
@Centril `MaybeInit` kind of sounds like a verb though (*unlike* `MaybeUninit`, because the verb form there would be `MaybeDeinit`)

**Comment by Centril** [comment]
@glaebhoerl Well; going purely on google searches for `"uninitialize"` and `"deinitialize"`, the former is 3-4 times more common than the latter at least for me; and the former is a verb form. I think `MaybeUninit` sounds just as much like an action as `MaybeInit` does. However, you can tell from the context of writing `MaybeInit::new(...)` that this is a state-of-being rather than an action.

**Comment by stjepang** [comment]
Here's a different idea that might be worth considering:

I see `MaybeUninit` and `ManuallyDrop` as two sides of the same coin. The former can postpone initialization of a value, while the latter can prematurely drop a value.

The flip side of `ManuallyDrop` might be `LazilyInit` or `ManuallyInit`. How do you feel about those names?

**Comment by Centril** [comment]
@stjepang `LazilyInit` makes me feel that this is some sort of thunk, i.e. `lazy_static!` sort of business. I like `ManuallyInit` however; it makes sense and communicates the "manual" nature of proof obligations.

**Comment by withoutboats** [comment]
Calling it `ManuallyInit`and pairing it with `ManuallyDrop` is interesting to me. What do other people think about making a pedagogical connection between the two types?

**Comment by WiSaGaN** [comment]
In the case of `ManuallyInit` versus `ManullyInitialize`, one argument in favor of `ManuallyInit` is the word length symmetry to `ManuallyDrop`, of which both of the verbs are 4 letters long.

**Comment by RalfJung** [comment]
> What do other people think about making a pedagogical connection between the two types?

I think it is important that we properly explain the *difference* between the two types.  People anyway seem to already assume there to be some relation, and there are a few suggestions out there about using `ManuallyDrop` for uninitialized data (which is not correct in current Rust and quickly leads to crashes).

Do you think explaining the distinction will be easier or harder by making the names more similar?

**Comment by scottjmaddox** [comment]
I think I like `MaybeInit` the most. I don't see any potential for confusion between `Init` being short for `Initialized` or `Initialize`, since a struct is necessarily a noun not a verb. And even if someone did think `Init` was short for `Initialize`, I can't imagine what incorrect semantic assumptions they would make based on that.

I like `MaybeInit` slightly more than `MaybeUninit` because It's slightly shorter and easier to type, and because the negation in `MaybeUninit` is completely unnecessary; `MaybeInit` means exactly the same thing.

I much prefer `MaybeInit`/`MaybeUninit` over `ManuallyInit`, because it better describes what the type means than `ManuallyInit` does. The latter implies, to me, that the value will be manually initialized once and then left initialized, similar to how `ManuallyDrop` should be dropped once and only once.

I completely agree with `withoutboats` that we should be trying to make the name *more* ergonomic, not *less* ergonomic, or else people will be more likely to just use raw pointers.

**Comment by gnzlbg** [comment]
FWIW I argued here: https://github.com/rust-lang/rust/issues/53491#issuecomment-450524202 that maybe we should rename this to `MaybeInvalid` instead, since the pre-condition on `into_inner` _safety_ is probably that the `MaybeInvalid<T>` has to be a valid `T`.  

Whether `T` is not valid because all its bits are uninitialized, zeroed, or something else, is pretty much irrelevant, and using "uninitialized" on this type's name kind of conveys that this is only about the uninitialized case, obscuring the validity issue.

**Comment by Centril** [comment]
@gnzlbg Seems reasonable; I'd flip the polarity tho: `MaybeValid` seems more direct and avoids the negative.

**Comment by shepmaster** [comment]
> `MaybeValid`

And has no abbreviations... ❤️

**Comment by stjepang** [comment]
I personally find "valid" in `MaybeValid` a bit vague - the value is valid or invalid in what sense? A more fitting term might be "present" because the value is either present or not.

Here's another perspective that might be helpful to think about: `MaybeUninit<T>` is like `Option<T>`, except there's no discriminant. One could also think of it as `UncheckedOption<T>`.

**Comment by gnzlbg** [comment]
> I personally find "valid" in MaybeValid<T> a bit vague - the value is valid or invalid in what sense? 

In the Unsafe Code Guidelines sense, see [Glossary: Validity and safety invariant](https://github.com/rust-rfcs/unsafe-code-guidelines/blob/master/reference/src/glossary.md#validity-and-safety-invariant).

**Comment by joshtriplett** [comment]
I feel like most of the alternative changes introduce vagueness. Yes, "invalid" applies, but there are many ways for something to be invalid. "uninitialized" has a very specific meaning (and "uninit" very clearly conveys that meaning).

Could we just leave this as it is?

**Comment by shepmaster** [comment]
> there are many ways for something to be invalid

That's kind of what (positively) caught my attention about using `MaybeValid`. Such a wrapper could be used for *any* value that is in an invalid state, as defined by that value. This may or may not be needed; I don't know.

**Comment by Centril** [comment]
> > I personally find "valid" in MaybeValid a bit vague - the value is valid or invalid in what sense?
> 
> In the Unsafe Code Guidelines sense, see [Glossary: Validity and safety invariant](https://github.com/rust-rfcs/unsafe-code-guidelines/blob/master/reference/src/glossary.md#validity-and-safety-invariant).

That might be problematic tho; if we by `MaybeValid` mean "maybe upholds validity of the type", then `MaybeValid::into_inner(mv)` is bad if leaked into a safe boundary in which you also need to uphold the safety invariant...

**Comment by withoutboats** [comment]
To be more concrete, the validity of a pin (for example) depends on whether or not the value behind the reference in the pin has been memcpy'd. Nothing would be wrong with the bits inside the `MaybeValid` for it to be invalid (it could still be a valid pointer to a valid value of the type that has been pinned). So validity seems broader than the invariants this type is about, which as I understand it are just whether or not the bits form a valid representation from a data perspective.

**Comment by RalfJung** [comment]
> To be more concrete, the validity of a pin (for example) depends on whether or not the value behind the reference in the pin has been memcpy'd.

That's not correct, only the *safety* of a pin depends on that.

[Validity](https://github.com/rust-rfcs/unsafe-code-guidelines/blob/master/reference/src/glossary.md#validity-and-safety-invariant) is a compiler/language-defined invariant that the user cannot alter and that the compiler assumes to always be upheld.  unions are the only types that do not assume their fields to be valid, and `MaybeUninit` is intended to be the canonical type to carry data that may or may not satisfy its validity invariant.  So `MaybeValid` is a pretty good name from that perspective.

The problem is that I just very recently coined the term "validity" for this invariant, so it's really just jargon inside the UCG group so far -- and, for better or worse, the term "valid" doesn't even *look* like jargon, so many people will think they know what it means and they will be wrong.

**Comment by stjepang** [comment]
@RalfJung Thanks for the clarification, this is very helpful!

So if I understood correctly, `MaybeUninit<T>` is just an opaque container that looks like `T` in the sense that it has the same size and alignment as `T`, but in reality it may contain literally anything. One may (unsafely) read a `T` from `MaybeUninit<T>` only if they know it contains a *valid* value of type `T`.

Could we draw a parallel with `#[repr(transparent)]` here? So if a `#[repr(transparent)]` type is a *transparent* wrapper around `T`, then `MaybeUninit<T>` is an *opaque* wrapper around `T`?

I'd be okay with making up a new word for this concept, kind of like we embraced "cell" as a synonym for "interior mutability". Perhaps `Opaque<T>`? Other suggestions welcome!

I chose "opaque" here because there's no way to type-safely tell what is inside `MaybeUninit<T>`. It's only a place where a `T` can be stored, but we can't really tell if anything sensible is stored inside.

**Comment by RalfJung** [comment]
> So if I understood correctly, MaybeUninit<T> is just an opaque container that looks like T in the sense that it has the same size and alignment as T, but in reality it may contain literally anything. One may (unsafely) read a T from MaybeUninit<T> only if they know it contains a valid value of type T.

Correct.

However, I am not sure if "opaque container" is a good metaphor here.  The intent usually is more along the lines of `Option<T>`, except that there's no explicit tracking of whether there's some data in there or not.

**Comment by Centril** [comment]
@RalfJung 

> The problem is that I just very recently coined the term "validity" for this invariant, so it's really just jargon inside the UCG group so far -- and, for better or worse, the term "valid" doesn't even _look_ like jargon, so many people will think they know what it means and they will be wrong.

I think that's the problem, and I guarantee you it will break some people's minds. One may legitimately think that *"Oh, it's named `MaybeValid`, and I've ensured `foo: MaybeValid<T>` is a valid `T` so now I may `into_inner(foo)` and get a `T`."* And that is true, *they can do that;* but if they also leak this acquired `T` into a safe boundary, which I think will happen often, then they also need to uphold the safety invariant per your own definitions. We'll need crystal clear, excellent, and elaborate documentation to make sure this confusion does not occur.

I also think that the term "validity" is suboptimal for the condition you seek to describe; it's a specific sort of "being valid"... from my understanding of the glossary, it's "bit-pattern validity". We might want to recoin "validity"... ;)

> However, I am not sure if "opaque container" is a good metaphor here.

I also want to use "opaque" for `impl Trait` so it's taken... =P

**Comment by stjepang** [comment]
In that case, perhaps we could name this `UnsafeOption<T>` to make a pedagogical connection with `Option<T>` (similar to `UnsafeCell<T>` vs `Cell<T>`), and perhaps even name methods on it accordingly:

```rust
impl<T> UnsafeOption<T> {
    fn some(val: T) -> UnsafeOption<T>;
    fn none() -> UnsafeOption<T>;
    fn zeroed() -> UnsafeOption<T>;

    fn set(&mut self, val: T);

    unsafe fn unwrap(self) -> T;

    unsafe fn as_ref(&self) -> &T;
    unsafe fn as_mut(&self) -> &mut T;

    unsafe fn as_ptr(&self) -> *const T;
    unsafe fn as_mut_ptr(&self) -> *mut T;
}
```

**Comment by RalfJung** [comment]
> from my understanding of the glossary, it's "bit-pattern validity"

Ask me again after we finished this discussion area in the UCG WG.^^

**Comment by Centril** [comment]
@stjepang I mostly like your framing, tho `.unwrap()` and friends seem a bit too unimposing / not sufficiently "warning warning warning".

**Comment by SimonSapin** [comment]
How about with `unwrap_unchecked`, `as_ref_unchecked`, and `as_mut_unchecked`?

**Comment by RalfJung** [comment]
The issue is that the `Option` metaphor works for many, but not all cases. It breaks now when you use `MaybeUninit<Struct>` and initialize one field after the other.

**Comment by stjepang** [comment]
@RalfJung Do you have a suggestion on what a good metaphor might be?

The latest ones we had were:

* `MaybeUninit<T>` - a `T` that might be uninitialized.
* `ManuallyInit<T>` - a `T` that can be manually initialized.
* `UnsafeOption<T>` - an `Option<T>` without the discriminant.

All of them seem to be imperfect. Is this really just raw memory that fits one value of type `T`, and that's it? Perhaps the right metaphor is "raw memory"? Or a "place" where a `T` can be stored?

I'm thinking aloud here, but this also reminds me of the placement new RFC, where we had the concept of a "place". It's a place in memory where a `T` can be stored. Would it make sense to reuse the word "place" here, or maybe come up with a similar word?

**Comment by RalfJung** [comment]
Viewing it as "raw memory" corresponds to just unfolding the definition: It's a `union`. A `union` is just sugar for having some raw uninterpreted bytes in memory and convenient ways to access them at certain types, with every access being somewhat like a `transmute` to/from raw bytes.  

My intuition for it is that it inhibits type-based reasoning by the compiler.  That's why `Maybe[Un]Init[ialized]` seems like a reasonable choice to me -- if the type doesn't even say whether the data is initialized at all, there are no assumptions that the compiler can still make.  It's not strictly just about being initialized or not (there's a while "gradient" there, if you wish to look at it that way), but being uninitialized is as invalid as it gets, and it's also the most common use-case.  I still think this is a suitable metaphor.

**Comment by notriddle** [comment]
> I mostly like your framing, tho .unwrap() and friends seem a bit too unimposing / not sufficiently "warning warning warning".

The method is unsafe, the struct also has Unsafe in the name, and the analogous `Option::unwrap()` is well-known as the unidiomatic, crashy way to do things.

How much more "dangerous-looking" does it need to get?

**Comment by RalfJung** [comment]
`unwrap` is panic-y, but that's very different from unsafe.  I think that `unwrap` is about as bad a name as `into_inner`.

**Comment by shepmaster** [comment]
> as the unidiomatic, crashy

I believe this is what @RalfJung points out, but I think that people expect `unwrap` to **always** panic when things are in a "bad" state. Here, such behavior is not guaranteed. Misleading people would be detrimental to Rust ecosystem.

**Comment by notriddle** [comment]
> I believe this is what @RalfJung points out, but I think that people expect unwrap to always panic when things are in a "bad" state. Here, such behavior is not guaranteed.

Yeah, that's true. It should probably be a completely different verb, then. I still don't like `unchecked_unwrap` (and other method names with `unchecked` in them), because it's long and excessive.

We don't want people to expect the method to be infallible (it is infallible in the sense that it will not panic, but ... no), and we don't want people to expect it to be panicky, either. I guess it could just be called `transmute`, since that's pretty much what it is:

```rust
let k = UnsafeOption::some(3);
let m: i32 = k.transmute(); // transmute_some would probably be a truer name, but that's also too long.
```

**Comment by scottjmaddox** [comment]
I prefer `MaybeInit` over `UnsafeOption`. I find it much clearer.

As far as what the methods should be for getting the inner value, how about `into_inner_unchecked`, `get_mut_unchecked`, `get_ref_unchecked`? The precedent for `get_mut_unchecked` is already set by `Pin`. These are a bit verbose, but much clearer than `into_inner`, etc.

**Comment by Centril** [comment]
> We _can_ do that, as this is unstable, but is this _really_ worth it?

Yes, I think for such a central piece of infrastructure it is worth it to have the best name.

**Comment by joshtriplett** [comment]
@Centril Which still leaves the question of whether we *already* have the best name.

**Comment by gnzlbg** [comment]
Independently of this type's name, the documentation of some of this type's methods (e.g. `into_inner`) should probably state that the raw bits inside the `union` need to satisfy the _validity invariant_ of `T`. That is, users of this type are going to have to know what "validity invariant" precisely means to be able to use this type correctly anyways. I don't see a way around that.

**Comment by stjepang** [comment]
I feel like we've explored all options and would be happy with `MaybeInit` (and even `MaybeInitialized` if other folks want it fully spelled out). At the very least, let's drop the unnecessary "Un".

Can the libs team perhaps make a decision and stabilize this?

**Comment by shepmaster** [comment]
> renaming this will be a substantial amount of churn

I think that once we start saying that it's unacceptable for an *unstable feature* to cause churn, we've lost a huge point of having the feature be unstable in the first place. The instability comes from all sorts of avenues; naming is no less important than any other.

**Comment by Centril** [comment]
Since there doesn't seem to exist any strong feelings against `MaybeInit`, I'll take some initiative here and propose that we finalize the name of the type as `MaybeInit`. This proposal is *not* to stabilize the type itself, but I think it would be good to at least solve the naming so that we can make progress.

@rfcbot merge

**Comment by pnkfelix** [comment]
@rfcbot concern i-am-un-maybe-init

@Centril [claimed](https://github.com/rust-lang/rust/pull/56138#issuecomment-447614827) that `MaybeUninit` is equivalent to `MaybeInit`. I disagree. Yes, I can see that the two phrases indicate the same underlying semantics: The data here may or may not be initialized. I argue that it is important to stress the "un" in "uninitialized", which justifies the inclusion of those two additional characters. The benefit is to stimulate all those neural pathways associated with "uninitialized" (=> here be dragons).

I don't think there is a net win from renaming replacing `MaybeUninit` with `MaybeInit`.

----

(I don't have an opinion about the original proposal to lengthen the name to `MaybeUninitialized`. I would have a similar objection to a rename to `MaybeInitialized`.)

**Comment by scottjmaddox** [comment]
`pnkfelix`'s argument seems reasonable to me. There isn't really much of an advantage in renaming to `MaybeInit`, anyways, other than being ever so slightly easier to type.

**Comment by joshtriplett** [comment]
@pnkfelix I agree entirely, and I have the same objection. This not only doesn't seem worth the change, it seems less clear.

**Comment by Centril** [comment]
@pnkfelix 

> I'm speaking about the benefit for human authors and code reviewers, especially those who are perhaps looking over something quickly and might not catch an occurrence of "Maybe" (even when next to "Init") but would catch "Uninit".

This is persuasive. Therefore:

@rfcbot cancel

**Comment by Centril** [comment]
I propose that we finalize the name of the type as `MaybeUninit` (note the `Un`); The proposal is merely for the type's name and not for stabilization of the type itself.

@rfcbot merge

**Comment by shepmaster** [comment]
> especially those who are perhaps looking over something quickly and might not catch an occurrence of "Maybe" (even when next to "Init") but would catch "Uninit".

I don't know enough HCI to refute this claim, but it seems odd to expect people to read the *middle* of a word but not the *beginning*.

**Comment by nikomatsakis** [comment]
While I checked my name, I would like to note for the record that I prefer the name `Uninit` -- I feel the maybe is implied. But I don't really care enough to argue strongly one way or the other. =)

**Comment by lzutao** [comment]
I am not a native English speaker, and have not used much `unsafe` code. So every time I see `MaybeUninit`, I read it like `maybe uni-nit`. That's so weird!

**Comment by gnzlbg** [comment]
I find the mixture of abbreviations with long spellings in the API weird: `MaybeUninit` vs `::into_initialized`. If we want to keep the abbreviation in the name (use `MaybeUninit` or `Uninit`, which I prefer, since the maybe is implied), the it might be worth it to also use the abbreviation in the other apis, like `::into_init()`. 

Without consistency, unless I use this API all-day every-day I pretty much have to guess whenever I need it. I wish the standard library would have clear guidelines about this instead of each API doing its own thing, it would save us a lot of time (bikeshedding, context-switching to the docs because rustc does not suggest the right thing, etc.).

**Comment by RalfJung** [comment]
So, uh, I guess we just close this PR now?

**Comment by Centril** [comment]
Indeed we should; Thank you @shepmaster for your work & proposal.

**Pull request closed without merging**
