### PR TITLE
Add codegen test for PGO instrumentation.

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR adds a codegen test that makes sure that LLVM actually generates instrumentation code when we enable PGO instrumentation in `rustc`. 

The second commit updates a test case to the new commandline option syntax introduced in #59874. Without the fix the test still works, but it confusingly creates a directory called `test.profraw`, which usually is the name of the _file_ where profiling data is collected.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
cc PGO tracking issue: https://github.com/rust-lang/rust/issues/59913

**Comment by alexcrichton** [comment]
r=me with passing tests, thanks @michaelwoerister!

(I suspect that this may need to be ignored on older LLVM or something like that)

**Comment by michaelwoerister** [comment]
> (I suspect that this may need to be ignored on older LLVM or something like that)

Yes, that too probably. But here the test is failing because the profiler runtime isn't being built for this CI image. I'm trying to think of the best way of solving this (either extend `compiletest` with more `ignore-xxx` options or switch this to a `run-make` test)...

**Comment by alexcrichton** [comment]
It might be nice to add some compiletest options which may not be too too bad if we want to add more tests in the future, in general run-make tests are a bit of a bummer to write

**Comment by michaelwoerister** [comment]
I implemented the `compiletest` version as suggested.

**Comment by alexcrichton** [comment]
@bors: r+

Nice!

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/60101#issuecomment-484760346, @bors r-

**Comment by michaelwoerister** [comment]
Turns out that the branching in the sanitizer test `Makefiles` implements more complicated ignoring logic than just looking for sanitizer support. Trying to recreate that with `compiletest` directives. If that doesn't work, I'll have to bring the logic back.

@bors r+

**Pull request merged**
