### PR TITLE
Add more information to error message for unconstrained_parameter E0207

### LINKED ISSUE #107295: unconstrained type parameter makes no suggestions as to how to fix
### Code

```Rust
trait MyTrait {}

struct S;

impl <U> MyTrait for S {}
```

### Current output

```Shell
error[E0207]: the type parameter `U` is not constrained by the impl trait, self type, or predicates
 --> src/lib.rs:5:7
  |
5 | impl <U> MyTrait for S {}
  |       ^ unconstrained type parameter

For more information about this error, try `rustc --explain E0207`.
error: could not compile `playground` due to previous error
```

### Desired output

```Shell
error[E0207]: the type parameter `U` is not constrained by the impl trait, self type, or predicates
 --> src/lib.rs:5:7
  |
5 | impl <U> MyTrait for S {}
  |       ^ unconstrained type parameter

Either remove the type parameter (<U>) or make use of it, for example ` for S<U>`.

For more information about this error, try `rustc --explain E0207`.
error: could not compile `playground` due to previous error
```

### Rationale and extra context

If we have an unconstrained type parameter, we get an error stating that it is unconstrained, but no suggestions on what to do about it and force the user to google.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3ca555fca7f8220aaab497f87c26225b

Is there room to reduce the learning curve here with better diagnostics?

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Lol3rrr**
Fixes #107295 and also takes inspiration from a previously attempted PR #108252

### CODE REVIEW

**Comment by jackh726** [comment]
I think the note here is not super helpful.

I would probably just start with the changes in #108252 and address the review comments there. Then I can review that!

**Comment by Lol3rrr** [comment]
Should I directly transition to [a structured error](https://github.com/rust-lang/rust/pull/108252#pullrequestreview-1309016051) as mentioned in #108252 ?

**Comment by jackh726** [comment]
Up to you :) happy to split it into parts

**Comment by jackh726** [comment]
This is waiting on @Lol3rrr to simplify to just the changes from #108252.

**Comment by Lol3rrr** [comment]
Sorry for the delay, I am now starting to pick this issue up again.
I am currently just playing around with some ideas on how a good error message could look like and how I might implement them, as working on the compiler is new to me.

If there are some more concrete ideas / examples on how the error should look exactly, I am happy to hear them as the discussion on the previous PR was not very conclusive (i think) and mentions a variety of ideas and potential things

**Comment by jackh726** [comment]
Thinking about this more, I wonder if it's worth distinguishing *unused* vs *unconstrained* here? Completely unused is easy (just remove), but unconstrained is harder (because it may still be used, and we don't know the best way to fix it, see #64155 for an example).

**Comment by jackh726** [comment]
In the unused case, we can suggest removing (with suggested change). In the unconstrained case, we can just note the requirements to make it constrained.

**Comment by JohnCSimon** [comment]
@Lol3rrr 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
