### PR TITLE
Implement `unsigned_signed_diff`

### PR DESCRIPTION
**Pull request by davidzeng0**
Implements https://github.com/rust-lang/rust/issues/126041

### CODE REVIEW

**Comment by Amanieu** [comment]
When we discussed this in the libs-api meeting, we only saw significant value in `checked_signed_diff`, but not the other operations. Could you change your PR to only include that one method?

Alternatively, do you have a specific use case for the other 2 methods?

**Comment by davidzeng0** [comment]
Ah. I added the other two for completeness since most integer operations come in `checked_XX`, `overflowing_XX`, `saturating_XX` and `wrapping_XX` variants (for example, checked_add_signed).

`checked_XX` operations are usually implemented using `overflowing_XX` and it's the same here with `unsigned_signed_diff`.

**Comment by Amanieu** [comment]
In the libs-api meeting we specifically chose to only implement the `checked_XX` version because that is what is what is most likely to be useful in practice. In particular, `overflowing_XX` is rarely used in practice. There could be an argument for `saturating_XX` but we would like to wait for an actual use case for it. Your ACP only needed `checked_signed_diff` for your use case.

**Comment by davidzeng0** [comment]
Ok, I've completed the necessary modifications

**Pull request merged**
