### PR TITLE
Improve slice indexing assertion

### PR DESCRIPTION
**Pull request by Manishearth**
I'd like to have the message print out the index and length values like it does elsewhere, but I'm not sure how to do that without affecting perf here. Will `assert!(cond, "index out of bounds got {} but len is ", idx, len)` make things slower? It calls `panic_fmt` which is marked as cold but also calls `format_args!`, and I don't know if that allocates or does any heavy lifting.

cc @alexcrichton @Gankro

### CODE REVIEW

**Comment by bluss** [comment]
str uses a [separate function](https://github.com/Manishearth/rust/blob/slice-assert/src/libcore/str/mod.rs#L1443-L1449) to put the formatting there

**Comment by alexcrichton** [comment]
Yeah I think the `str` strategy would be appropriate here for some good messages. There's no concern really about performance here, LLVM typically does the correct thing, but it could accidentally be easy to inflate code sizes with lots of fancy asserts.

If, however, a concrete function in libcore were provided (e.g. not generic), then it could be as fancy as it wants!

**Comment by Manishearth** [comment]
That should be marked `cold`, right?

**Comment by Gankro** [comment]
@Manishearth might as well, although the fact that they wouldn't be generic means that they can't be inlined without LTO anyway.

**Comment by Manishearth** [comment]
Updated. Error message could be improved.

**Pull request merged**
