### PR TITLE
Use -Zborrowck=mir for NLL compare mode

### LINKED ISSUE #56993: region tests incorrectly passing with NLL enabled
The following tests pass under NLL, but ought not to (in some cases, light editing is required to observe that):

- [`ui/regions/regions-assoc-type-in-supertrait-outlives-container.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-assoc-type-in-supertrait-outlives-container.rs), [modified variant](https://gist.github.com/nikomatsakis/71755772d41d86daa871a6acc52b506d)
- [`ui/regions/regions-free-region-ordering-caller.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-free-region-ordering-caller.rs)
- [`ui/regions/regions-outlives-projection-container-wc.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-outlives-projection-container-wc.rs)
- [`ui/regions/regions-outlives-projection-container-hrtb.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-outlives-projection-container-hrtb.rs)

To observe the problems, though, you need to run in true NLL mode (i.e., `#![feature(nll)]` or `-Zborrowck=mir`). In migration mode, the lexical borrow checker still reports the errors in question.

### PR DESCRIPTION
**Pull request by matthewjasper**
closes #56993

r? @pnkfelix

### CODE REVIEW

**Comment by pnkfelix** [comment]
Sorry its taken me so long to take a look at this.

Did you already manually review those new .nll.stderr's? I started looking through them, but its too many to do via Github interface in a single review. And I'm basically wondering whether we need to plan for a new round of going over all of the diffs between the `.stderr` and `.nll.stderr` files.

**Comment by matthewjasper** [comment]
I checked that there was nothing completely unexpected, but an actual review is needed.

**Comment by pnkfelix** [comment]
Okay. 

I think our best bet is to land this, and then do a review in an incremental fashion as a follow-up task.

**Comment by pnkfelix** [comment]
(the PR is probably out of date, but I'll just let bors tell us if that's true.)

**Pull request merged**
