### PR TITLE
resolve: Improve performance

### LINKED ISSUE #33061: resolution time has *quadrupled* between 235d77457 and 6fa61b810
Before (on librustc):
```
time: 0.013; rss: 169MB language item collection
time: 0.281; rss: 201MB resolution
```

After (on same librustc):
```
time: 0.017; rss: 226MB language item collection
time: 1.055; rss: 277MB resolution
```
cc @jseyfried

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes #33061 by speeding up searchs through all traits in scope, a bottleneck in `resolve`.

According to my measurements, this PR improves resolution performance by a factor of 3.4x on `librustc`, which almost completely reverses the 3.75x performance regression reported in #33061.

r? @eddyb

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @nikomatsakis

**Comment by jseyfried** [comment]
@eddyb thanks! The regression is currently in beta -- do you think we should beta-nominate this?

**Comment by nikomatsakis** [comment]
Ordinarily we wouldn't backport a pure performance change, but approved for beta because:

- this is a small and simple patch;
- it's a perf *regression*, no need to give up ground.

**Pull request merged**
