### PR TITLE
std::thread: set_name change for solaris/illumos.

### PR DESCRIPTION
**Pull request by devnexen**
truncate down to 32 (31 + 1) for solaris/illumos.

### CODE REVIEW

**Comment by workingjubilee** [comment]
@devnexen hm. from whence this particular constant?

**Comment by devnexen** [comment]
from [here](https://github.com/illumos/illumos-gate/blob/da7002c4941931fa102b3ecd9c22f84ad95d6f42/usr/src/uts/common/sys/thread.h#L613).

**Review by workingjubilee — APPROVED** [review]
Ah!

**Comment by workingjubilee** [comment]
@devnexen hey, can you check if this stdlib compiles for illumos?

@bors r-

**Comment by workingjubilee** [comment]
Nice, thanks!

@bors r+

**Pull request merged**
