### PR TITLE
TRPL: fix typo, borow for borrow

### PR DESCRIPTION
**Pull request by reinh**
Thanks for the awesome book!

r? @steveklabnik

### CODE REVIEW

**Comment by reinh** [comment]
What a friendly bot! :+1:

**Comment by huonw** [comment]
@bors r+

What a friendly contributor! :smile: (Thanks for the fix!)

**Comment by steveklabnik** [comment]
Good to see you @reinh :)

**Comment by reinh** [comment]
Hi @steveklabnik, good to see you too! Thanks for all your work on Rust!

**Pull request merged**
