### PR TITLE
Display tokens for fn qualifiers

### PR DESCRIPTION
**Pull request by mark-i-m**
My goal was to make it easier to see what qualifiers are added to a method.

What do people think? Is this an improvement?

r? @QuietMisdreavus 

Sample screenshots:

image

image

image

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/rustdoc @euclio 

I'm... not too keen on this? It doesn't seem worth it to specially call out "`pub`", for example, and i don't feel like calling out the other keywords there makes it much easier to notice them? It's possible that with some iteration on the design that it could look better, but right now i'm not sold on this.

One thing that this PR changes that may be necessary to track/test is that you've changed the Display output of the "alternate" mode of the function signature type and the keyword types. This is meant to print plain-text, and is used to calculate whether to line-wrap the text of an item. Since `VisSpace`/`ConstnessSpace`/etc now universally print HTML tags, this behavior may start causing problems. (I see you've taken them out of some length calculations, but i'm still not sure about the behavior going forward.)

You should also make sure to update the tests that failed on travis.

**Comment by mark-i-m** [comment]
> You should also make sure to update the tests that failed on travis.

Yep, will do, but I would like to get feedback first. If people don't want this, I don't want to spend more time on it :stuck_out_tongue:

**Comment by GuillaumeGomez** [comment]
I'm not a big fan either... It doesn't "fit" in whole layout.

**Comment by euclio** [comment]
I wonder if we could achieve the same effect with syntax highlighting?

**Comment by mark-i-m** [comment]
One other thing is that since the names of the functions are aligned, I find them easier to glance through.

**Comment by mark-i-m** [comment]
Since the feedback seems to be negative, I'm going to go ahead a close this. Thanks anyway :)

**Pull request closed without merging**
