### PR TITLE
Update E0010 to use the new format

### PR DESCRIPTION
**Pull request by pcn**
For https://github.com/rust-lang/rust/issues/35194

### CODE REVIEW

**Comment by jonathandturner** [comment]
Great! Next make sure you also update the unit test so that you're testing to make sure that new label is there.

**Comment by pcn** [comment]
Ah, yes.  Thanks for reminding me about that.  I'll also revert the message to the recommended message from #35194.  It seems like I riff'd here.

**Comment by pcn** [comment]
It looks like like the existing test is only matching on the string `E0010` so no change needs to be made  there:

```
spacey@masonjar:~/dvcs/github/rust-lang/rust$ python src/bootstrap/bootstrap.py --step check-cfail E0010 --stage 1
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage1 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage1 tool compiletest (x86_64-unknown-linux-gnu)
Check compiletest compile-fail (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 1 test
test [compile-fail] compile-fail/E0010.rs ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

Build completed in 0:00:01
```

And I've changed the inline message to  match  the top line message, which is what the request actually asked for:

```
spacey@masonjar:~/dvcs/github/rust-lang/rust$ RUST_NEW_ERROR_FORMAT=true ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc src/test/compile-fail/E0010.rs
error[E0010]: allocations are not allowed in constants
  --> src/test/compile-fail/E0010.rs:13:24
   |
13 | const CON : Box<i32> = box 0; //~ ERROR E0010
   |                        ^^^^^ allocation not allowed in constants

error: aborting due to previous error
```

**Comment by pcn** [comment]
OK, looks like I skimmed that part when I focused  on the tips section below.  I'm looking into adding a NOTE now.

**Comment by pcn** [comment]
Tested a bogus NOTE and then this  NOTE and it looks as though it's now working as expected.

**Comment by jonathandturner** [comment]
Great.  Can you [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your three 3 commits down to 1 commit?  With that I think we'll be ready.

**Comment by pcn** [comment]
Rebased.

**Comment by jonathandturner** [comment]
Great!

@bors r+ rollup

**Pull request merged**
