### PR TITLE
Move some utils out of `rustc_const_eval`

### PR DESCRIPTION
**Pull request by Noratrieb**
This allows us to get rid of the `rustc_const_eval->rustc_borrowck` dependency edge which was delaying the compilation of borrowck.

The added utils in `rustc_middle` are small and should not affect compile times there.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
This PR combined with #110397 reduced `x clean compiler/rustc_middle && x check_compiler` from 37s to 28s.

**Comment by jyn514** [comment]
r=me unless you want a reviewer from t-compiler

**Review by fee1-dead — APPROVED** [review]

**Comment by RalfJung** [comment]
Cc https://github.com/rust-lang/rust/issues/100061

**Pull request merged**
