### PR TITLE
Encode info for Fn/AssocFn in a single place.

### PR DESCRIPTION
**Pull request by cjgillot**
Split from https://github.com/rust-lang/rust/pull/98867

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
This is much cleaner ❤️ 

r=me with clean perf

**Comment by JohnCSimon** [comment]
@cjgillot  Ping from triage:  Can you post your status on this PR? This has sat idle for a few months.

**Comment by cjgillot** [comment]
I haven't finished investigating the perf regression. It is waiting on author.

**Pull request closed without merging**
