### PR TITLE
[WIP] Split query execution into hot and cold paths

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 14e43456b2599ec8d1b7b839ced3ac834312659d

**Comment by Mark-Simulacrum** [comment]
Please do not queue broken try commits, this breaks perf. I have manually dropped this commit from the queue.

**Comment by Zoxc** [comment]
Oops, didn't mean to do that.

@bors try @rust-timer queue

**Comment by Zoxc** [comment]
These changes have been merged into https://github.com/rust-lang/rust/pull/68988.

**Pull request closed without merging**
