### PR TITLE
Respect verify-llvm-ir option in the backend

### PR DESCRIPTION
**Pull request by nikic**
We are currently unconditionally verifying the LLVM IR in the backend (twice), ignoring the value of the verify-llvm-ir option. This has substantial compile-time impact for debug builds.

### CODE REVIEW

**Comment by nikic** [comment]
Updated test to explicitly pass `-Z verify-llvm-ir`. (Most CI jobs that run tests enable this in config.toml...)

@bors try

**Comment by nikic** [comment]
Adjusted tests that relied on IR verification.

@bors r=Mark-Simulacrum

**Comment by nikic** [comment]
Fingers crossed that there aren't more tests lurking...

@bors r=Mark-Simulacrum

**Comment by nikic** [comment]
I think I know what happened here. https://github.com/rust-lang/rust/pull/133654 as a cargo-only change used download-rustc, which appears to have downloaded a rustc with profiling support and the test worked. Then this PR changed the compiler, so we don't use download-rustc and build our own, with profiling support disabled.

So I think there are multiple issues here:

 * The cargo test does not support rust without profiling support.
 * We should *not* be using download-rustc when updating cargo -- can't the cargo update potentially impact the rust build?
 * We should make sure that the downloaded rustc has the same profiler/sanitizer/etc configuration as the local configuration.

cc @onur-ozkan

**Comment by onur-ozkan** [comment]
> We should not be using download-rustc when updating cargo

Sounds right to me.


> We should make sure that the downloaded rustc has the same profiler/sanitizer/etc configuration as the local configuration.

We do check if CI rustc has the same configuration with the local one and if they don't match we build the in-tree compiler.

**Comment by nikic** [comment]
> > We should not be using download-rustc when updating cargo
> 
> Sounds right to me.
> 
> > We should make sure that the downloaded rustc has the same profiler/sanitizer/etc configuration as the local configuration.
> 
> We do check if CI rustc has the same configuration with the local one and if they don't match we build the in-tree compiler.

As far as I can tell, the `profiler` option is currently not taken into account (it's not listed in https://github.com/rust-lang/rust/blob/76f3ff605962d7046bc1537597ceed5e12325f54/src/bootstrap/src/core/config/config.rs#L3132 in either of the lists).

**Comment by RalfJung** [comment]
> We do check if CI rustc has the same configuration with the local one and if they don't match we build the in-tree compiler.

Evidently that does not work, or else https://github.com/rust-lang/rust/pull/133654 would have failed.

**Comment by onur-ozkan** [comment]
> > We do check if CI rustc has the same configuration with the local one and if they don't match we build the in-tree compiler.
> 
> 
> 
> Evidently that does not work, or else https://github.com/rust-lang/rust/pull/133654 would have failed.
> 
> 
> 
> EDIT: opened https://github.com/rust-lang/rust/issues/133675 to track this.

That PR doesn't change any contig at all? I guess we are on different points, I am talking about config.toml here.

**Comment by weihanglo** [comment]
Or some tests should only run on Cargo's CI, to make everybody happier?

**Comment by RalfJung** [comment]
Cargo might not be the only component sensitive to whether rustc is built with profiling or not. So I don't think we should paper over this issue by running the test only in cargo CI.

**Pull request merged**
