### PR TITLE
RFC3239: Implement `cfg(target)` - Part 1

### PR DESCRIPTION
**Pull request by Urgau**
This pull-request implements the `cfg(target = "...")` part of [RFC 3239](https://github.com/rust-lang/rust/issues/96901).

cc @GuillaumeGomez
r? @petrochenkov

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by CryZe** [comment]
Apparently my concern in the original RFC was never elaborated on, nor is the RFC in any way clear on this, but is this really intended to be a plain string comparison instead of a semantic comparison? That feels pretty wrong to me, but no one ever clarified it.

**Comment by GuillaumeGomez** [comment]
Maybe the part 2 will answer your question? You can see it there: https://github.com/rust-lang/rust/pull/96913

**Comment by CryZe** [comment]
Part 2 is the other part of the RFC, that is less controversial and properly defined. Unless that PR also somehow builds on top of this one and I missed something, but they seem pretty distinct from what I'm seeing.

**Comment by GuillaumeGomez** [comment]
Sorry, I thought you asked about having more control about the checks. You can have the full one (which is the same as returned by cargo iirc) or you can check each sub element directly (implemented in part 2).

**Comment by CryZe** [comment]
I would've assumed the one that this PR implements (yet again the RFC never clarified what this PR is supposed to do) to first parse the string into its parts and then compare it semantically.

**Comment by CryZe** [comment]
Okay, so since this wasn't clarified in the original RFC, I'd like to properly open up the discussion about this again. Can this be implemented as a triple parser instead and then be lowered to the other representation. Basically I'd like to see `wasm32-unknown-wasi` match against `wasm32-wasi`.

**Comment by GuillaumeGomez** [comment]
Sounds acceptable to me. What do you think @joshtriplett ?

**Comment by Urgau** [comment]
> Okay, so since this wasn't clarified in the original RFC, I'd like to properly open up the discussion about this again. Can this be implemented as a triple parser instead and then be lowered to the other representation? Basically I'd like to see `wasm32-unknown-wasi` match against `wasm32-wasi` since those are semantically the same triples. If there's a technical reason as to why this can't be done, I'd like to hear it. Otherwise I think that would be a much better implementation than what I'm seeing in this PR.

I don't think it would be possible or even something that we would want because:

1. As far as I know neither `rustc` or `Rust` has a clear definition of what a target-triple is. Clang as [roughly](https://clang.llvm.org/docs/CrossCompilation.html#target-triple) a definition but I don't think it wouldn't fit for Rust.
2. Target-triple are for human not machine, nothing prevent Rust from having a target-triple named "linux-pencil-version-2.1" or "ThisIs-ADummy-TargetTriple". How should we parsed them ? Assuming we parsed them, how should we match on them ?
3. How to deal with current and future ambiguity ? Ex: "wasm32-wasi" would match "wasm32-unknown-wasi" but also "wasm32-unknown-wasi-gnu" (if it ever exist).
4. There is currently not enough information (to be fair the information is there but not in way that would be usable for this) inside a `Target` to be able to do such a thing. (And that not even talking about custom target in json form).
5. `=` in cfg currently means strict equality, making `=` in `target` mean "equivalence" would be unexpected especially because the target would be between `""`. This would create confusion among users (I know I would be confused).
6. The principle of condition compilation in Rust is based behind the idea of a set of configuration options (ie key-value pairs that are either set or not set). This "equivalence" wouldn't fit in that rather simple and intuitive model.

Given all of the aforementioned points I don't think we should go on that direction.

**Comment by petrochenkov** [comment]
>Given all the aforementioned points, I don't think we should go on that direction.

Given the @CryZe's comments I don't think we should go on *this* direction either.

I feel really skeptical about this whole thing.
Looks like a source of endless issues for the sake of a minor convenience.

This only works for built-in targets, custom targets parsed from json files don't have full names.
Want to use a custom target making tweaks to a built-in target? Some random libraries using `cfg(target)` stop working.
Even with built-in targets, add some [new ABI flavor](https://github.com/rust-lang/rust/pull/94872) to an existing target? Some random libraries using `cfg(target)` stop working.

We need to stabilize `target_abi` / atomic cfgs / whatever else necessary instead.

**Comment by GuillaumeGomez** [comment]
Except that the RFC was accepted and this a needed feature. So what do we do at this point?

**Comment by Urgau** [comment]
> > Given all the aforementioned points, I don't think we should go on that direction.
> 
> Given the @CryZe's comments I don't think we should go on _this_ direction either.

This might seems weird but I actually agree that this direction this not great either.
I only did this part of the RFC because I wanted to do the other part of the RFC and it seemed easy.

> I feel really skeptical about this whole thing. Looks like a source of endless issues for the sake of a minor convenience.

Agree, especially with "over-fitting" instead of using the proper `target_*`.

> This only works for built-in targets, custom targets parsed from json files don't have full names. Want to use a custom target making tweaks to a built-in target?

`sess.opts.target_triple.triple()` return the filename in the case of a custom target from a json file.

> Some random libraries using `cfg(target)` stop working. Even with built-in targets, add some [new ABI flavor](https://github.com/rust-lang/rust/pull/94872) to an existing target? Some random libraries using `cfg(target)` stop working.

I thought of that but because the RFC was accepted, I assumed that the risk was considered acceptable but I know realize that I was wrong.

> Except that the RFC was accepted and this a needed feature. So what do we do at this point?

🔽 This:

> We need to stabilize `target_abi` / atomic cfgs / whatever else necessary instead.

👍

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
>Except that the RFC was accepted and this a needed feature. So what do we do at this point?

The harm from this feature was significantly underestimated compared to the benefits when this RFC was evaluated, IMO.
In theory, I could merge this and then try to block the feature from stabilization on the next step, but I'd prefer to do it sooner.

I think we need to start stabilizing the unstable `target_*` cfgs instead.
@Urgau also suggested finishing implementation of `cfg_accessible` on Zulip.

Every use of a target by its full name means that we are missing some finer-grained controls (or hitting some very rare case, then it's not that important to improve its ergonomics, especially if those improvements come with significant downsides).

**Comment by joshtriplett** [comment]
I don't have any objection to re-evaluating the use cases for the whole-target-string part of the RFC. I do think the target shorthand syntax may make that less necessary.

**Comment by Urgau** [comment]
In order to move this forward (close or merge), T-lang could discussion in this in a triage meeting or at least be pinged on this PR. @joshtriplett

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/lang meeting. We agreed that we'd like to drop the `cfg(target = "...")` syntax, and just keep the `cfg(target(x = "...", y = "..."))` convenience shorthand.

Could someone please send a PR to the RFCs repository, adding a note to the top that we decided to only accept the `cfg(target(os = "...", arch = "...", ...))` shorthand, not the `cfg(target = "...")` string? We'd be happy to merge that as documentation.

For this PR, we'd love to have a version that implements the target shorthand.

**Comment by petrochenkov** [comment]
Ok, then closing this PR.
(The shortcut syntax was implemented in https://github.com/rust-lang/rust/pull/96913.)

**Pull request closed without merging**
