### PR TITLE
Work around a resolve bug in const prop

### PR DESCRIPTION
**Pull request by oli-obk**
r? @wesleywiser @anp 

This isn't exposed right now, but further changes to rustc may start causing bugs without this.

### CODE REVIEW

**Comment by wesleywiser** [comment]
@bors r+

Thanks!

**Comment by anp** [comment]
Confirmed that this will unblock https://github.com/rust-lang/rust/pull/67137. Thank you!!!

**Comment by oli-obk** [comment]
Let's not do the hack, since @wesleywiser has a real fix

**Comment by anp** [comment]
Ping on https://github.com/rust-lang/rust/pull/67662#issuecomment-569319802:

> I guess we still need my PR for backwards compatibility of @anp's PR. I'll reopen

**Comment by oli-obk** [comment]
@bors r-

I still want to do the warning thing

**Comment by oli-obk** [comment]
I added one more commit @wesleywiser 

It should permit https://github.com/rust-lang/rust/pull/67137 to not cause a breaking change related to diverging constants.

**Comment by anp** [comment]
Confirmed that this gets my test passing!

**Review by wesleywiser — APPROVED** [review]

**Comment by mati865** [comment]
Is this 1% regression (5% on ctfe) expected?
https://perf.rust-lang.org/compare.html?start=2ba0d2acbd6cb01fb07619628882120d5b66bd59&end=214548b8afd94924c17dea456c8077931009b944&stat=instructions:u

**Comment by wesleywiser** [comment]
Looks like we're potentially calling `const_eval_validated` *more* now? 

https://perf.rust-lang.org/detailed-query.html?commit=214548b8afd94924c17dea456c8077931009b944&base_commit=2ba0d2acbd6cb01fb07619628882120d5b66bd59&benchmark=ctfe-stress-4-check&run_name=baseline%20incremental

**Comment by oli-obk** [comment]
But only in the `base incremental` runs. everything else is unaffected.

**Comment by mati865** [comment]
Also `patched incremental`.

**Pull request merged**
