### PR TITLE
Move some std tests from `tests/ui-fulldeps` into `library/std`

### PR DESCRIPTION
**Pull request by ChrisDenton**
This allows them to be tested normally along with other `./x test std` tests. Moving `rename_directory` is simple enough but `create_dir_all_bare` needed to be an std integration test.

Additionally, some tests that I couldn't move atm have instead been placed in an `std` subdirectory. These tests include ones that do fun things with processes or that intentionally abort the test process.

r? libs

### CODE REVIEW

**Comment by thomcc** [comment]
LGTM

@bors r+

**Comment by ChrisDenton** [comment]
@bors r- I mixed up the drop order.

Weird that I didn't get that locally.

**Comment by raoulstrackx** [comment]
This PR breaks our CI for the SGX platform as file system support is lacking (see [sys/sgx/mod.rs:20-21](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/sgx/mod.rs#L20-L21). Using filesystem functions result in:
```
13:54:01 test create_dir_all_bare ... FAILED
13:54:01 
13:54:01 failures:
13:54:01 
13:54:01 ---- create_dir_all_bare stdout ----
13:54:01 thread 'create_dir_all_bare' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Unsupported, message: "operation not supported on SGX yet" }', library/std/tests/create_dir_all_bare.rs:14:33
13:54:01 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Can we cancel the merge and avoid running such tests on the SGX platform?

**Comment by ChrisDenton** [comment]
It's already been cancelled. I'll add an exclusion.

**Comment by raoulstrackx** [comment]
Great! Much appreciated @ChrisDenton !

**Comment by the8472** [comment]
> Additionally, some tests that I couldn't move atm have instead been placed in an std subdirectory. These tests include ones that do fun things with processes or that intentionally abort the test process.

Maybe we could add a `[[bin]]` to std and calling it from an integration test for those?

**Comment by ChrisDenton** [comment]
> Maybe we could add a `[[bin]]` to std and calling it from an integration test for those?

Maybe. But I'm not really sure how that would work with the build system.

**Comment by thomcc** [comment]
My r+ stands, feel free to r=me when ready.

@rustbot author

**Comment by ChrisDenton** [comment]
@bors retry error building LLVM on i686-mingw-2

This PR should not affect building LLVM in any way.

**Pull request merged**
