### PR TITLE
ci: Update android ndk and sdk

### PR DESCRIPTION
**Pull request by malbarbo**
Make install-sdk.sh and install-ndk.sh more generic so future updates can be made directly on Dockerfile. Update ndk to r13b, which will be necessary to make host builds for android (in the future). Update sdk to r25.2.5 (maybe some emulator performance improvement).

### CODE REVIEW

**Comment by kennytm** [comment]
Why not use the latest stable versions i.e. NDK r14b, SDK r26.0.2?

**Comment by malbarbo** [comment]
NDK r14b are [deprecating](https://developer.android.com/ndk/downloads/revision_history.html) gcc, so I though it would be better to stay with r13b for while. SDK r25.3 removed `tools/android` (in favor of avdmanager), a compatibility layer was add in r26.0.2, but I had some problems with it.

**Comment by alexcrichton** [comment]
@bors: r+

Looks great!

If you'd like to look into having the containers share files as well (e.g. to avoid this script duplication) I'd also be totally on board with that, but I'm also fine having duplication for now as well.

**Comment by malbarbo** [comment]
> If you'd like to look into having the containers share files as well (e.g. to avoid this script duplication) I'd also be totally on board with that, but I'm also fine having duplication for now as well.

Oh, that's funny that you asked it. I was about to open a issue about it. After this got merged I will open a PR then, so you can see what's my idea about a migration path to share files.

**Comment by alexcrichton** [comment]
👍 

I think you'll find... a nontrivial amount of duplication! Don't feel the need to tackle it all at once though, we can do this incrementally.

**Pull request merged**
