### PR TITLE
Rename Receiver -> LegacyReceiver

### PR DESCRIPTION
**Pull request by adetaylor**
As part of the "arbitrary self types v2" project, we are going to replace the current `Receiver` trait with a new mechanism based on a new, different `Receiver` trait.

This PR renames the old trait to get it out the way. Naming is hard. Options considered included:
* HardCodedReceiver (because it should only be used for things in the standard library, and hence is sort-of hard coded)
* LegacyReceiver
* TargetLessReceiver
* OldReceiver

These are all bad names, but fortunately this will be temporary. Assuming the new mechanism proceeds to stabilization as intended, the legacy trait will be removed altogether.

Although we expect this trait to be used only in the standard library, we suspect it may be in use elsehwere, so we're landing this change separately to identify any surprising breakages.

It's known that this trait is used within the Rust for Linux project; a patch is in progress to remove their dependency.

This is a part of the arbitrary self types v2 project,
https://github.com/rust-lang/rfcs/pull/3519
https://github.com/rust-lang/rust/issues/44874

r? @wesleywiser

### CODE REVIEW

**Review by wesleywiser — APPROVED** [review]
Compiler changes look good to me but I'm going to have T-libs sign off since this is a change to the standard library.

**Comment by wesleywiser** [comment]
r? libs

**Comment by jhpratt** [comment]
Looks like _some_ name change was approved by the RFC, so I don't need to punt to a team, and I don't have strong feelings towards anything. This needs a rebase, but otherwise r=me and wesleywiser.

@bors delegate+

**Comment by Nadrieril** [comment]
I think after a `@bors delegate` you can use the command yourself! Just write `@bors r=jhpratt,wesleywiser` on a new line in a reply; if that doesn't work I'll do it for you.

**Comment by Nadrieril** [comment]
lemme fix the names

@bors r-

**Comment by adetaylor** [comment]
OK, TIL, thanks!

**Comment by adetaylor** [comment]
OK, the build failure here is from [Rust for Linux](https://github.com/rust-lang-ci/rust/actions/runs/11466164547/job/31906269224):

```
error[E0405]: cannot find trait `Receiver` in module `core::ops`
Error:    --> rust/kernel/list/arc.rs:445:35
    |
445 | impl<T, const ID: u64> core::ops::Receiver for ListArc<T, ID> where T: ListArcSafe<ID> + ?Sized {}
    |                                   ^^^^^^^^ not found in `core::ops`

error[E0405]: cannot find trait `Receiver` in module `core::ops`
Error:    --> rust/kernel/sync/arc.rs:175:28
    |
175 | impl<T: ?Sized> core::ops::Receiver for Arc<T> {}
    |                            ^^^^^^^^ not found in `core::ops`

error[E0405]: cannot find trait `Receiver` in module `core::ops`
Error:    --> rust/kernel/sync/arc.rs:484:28
    |
484 | impl<T: ?Sized> core::ops::Receiver for ArcBorrow<'_, T> {}
    |                            ^^^^^^^^ not found in `core::ops`

error[E0635]: unknown feature `receiver_trait`
Error:   --> rust/kernel/lib.rs:18:12
   |
18 | #![feature(receiver_trait)]
   |            ^^^^^^^^^^^^^^
```

This is expected and the RfL folks have already fixed it in a branch. I think we need [this kernel commit](https://lore.kernel.org/lkml/CANiq72kkN2T4NeesDwsrVkk=JcDA-8iPHFys2Cg9M7MobzTEoA@mail.gmail.com/T/) to make its way into the branch we use, which [appears to be fetched here](https://github.com/rust-lang-ci/rust/actions/runs/11466164547/job/31906269224#step:27:98) as version `v6.12-rc2`.

**Comment by adetaylor** [comment]
This commit [does appear in `rust-next` as promised](https://github.com/torvalds/linux/compare/master...Rust-for-Linux:linux:rust-next). @nbdd0121 thanks for doing this. Do you have a guess about when it will make an appearance in the kernel source code used in Rust CI?

**Comment by nbdd0121** [comment]
You can change the commit hash in src/ci/docker/scripts/rfl-build.sh

**Comment by wesleywiser** [comment]
#132058 just merged so I believe we can once again

@bors r+

**Comment by wesleywiser** [comment]
Doing a crater run to assess breakage from this change. Since this is a nightly feature, this is mostly just for informational purposes so we can alert affected projects early rather than as a basis to revert the PR. 

@craterbot run name=legacyreceiver_rename mode=check start=nightly-2024-10-24 end=nightly-2024-10-25

**Comment by wesleywiser** [comment]
Doing a crater run to assess breakage from this change. Since this is a nightly feature, this is mostly just for informational purposes so we can alert affected projects early rather than as a basis to revert the PR.

@craterbot run name=legacyreceiver_rename mode=check-only start=nightly-2024-10-24 end=nightly-2024-10-25

**Comment by adetaylor** [comment]
A quick look at the crater run result.

The following crates were indeed depending on the old unstable `Receiver` trait:
* arsc-rs
* owned-pin

All the other failures are unrelated (mostly seeming to be related to increased `transmute` strictness in the current HEAD compiler).

I'll get in touch with the maintainers of those two crates to let them know.

**Comment by wesleywiser** [comment]
Thanks @adetaylor! I think that's all that's necessary at this time so we can go ahead with #132144.

**Pull request merged**
