### PR TITLE
Ndk update redux

### PR DESCRIPTION
**Pull request by chriswailes**
Blocked on https://github.com/rust-lang/blog.rust-lang.org/pull/1055

### CODE REVIEW

**Comment by pietroalbini** [comment]
Change looks good, please ping me when it's not blocked anymore.

**Comment by chriswailes** [comment]
@pietroalbini The blog post has landed now.

**Comment by pietroalbini** [comment]
@chriswailes you need to remove the "trigger android tests for this PR" commit

**Comment by chriswailes** [comment]
@pietroalbini Done

**Pull request merged**
