### PR TITLE
Improve raw Box conversions

### PR DESCRIPTION
**Pull request by nvzqz**
This PR has two goals:

- Reduce use of `mem::transmute` in `Box` conversions

  I understand that `mem::transmute`-ing non `#[repr(C)]` types is implementation-defined behavior.  This may not matter within the reference implementation of Rust, but I believe it's important to remain consistent. For example, I noticed that `str::from_utf8_unchecked` went from using `mem::transmute` to using pointer casts.

- Make `Box` pointer conversions more straightforward regarding `Unique`

### CODE REVIEW

**Comment by nvzqz** [comment]
This change caused this error:

```
[00:03:49] error: internal compiler error: /checkout/src/librustc_trans/adt.rs:431: Cannot handle boxed::Box<[u8]> represented as TyLayout {
[00:03:49]     ty: boxed::Box<[u8]>,
[00:03:49]     layout: FatPointer {
[00:03:49]         metadata: Int(
[00:03:49]             I64
[00:03:49]         ),
[00:03:49]         non_zero: true
[00:03:49]     },
[00:03:49]     variant_index: None
[00:03:49] }
```

When running
```
stamp sh -x -c "$RUN_SCRIPT"
```

I'm not sure how to go about fixing this.

**Comment by nvzqz** [comment]
Would you mind taking a look at this @alexcrichton?

**Comment by aidanhs** [comment]
Thanks for the PR @nvzqz! We'll check in now and again to make sure @alexcrichton or another reviewer gets to this soon.

**Comment by alexcrichton** [comment]
Thanks for the PR @nvzqz! As of a very long time ago (maybe this is still true today?) the `Box` type was defined in the compiler and the type definition here in the libraries mainly only sufficed for a few analysis passes in rustc. I think that may be where the error is coming from here? Maybe the tyep is still defined in the compiler and as a result trying to interpret it is causing issues?

**Comment by shepmaster** [comment]
Heya, @nvzqz, it's been over 7 days since you last checked in; are you still working on this?

**Comment by nvzqz** [comment]
@shepmaster just pushed another commit that'll hopefully make this work by reverting one of the changes. I don't know nearly enough about the compiler internals to fix the root issue.

**Comment by nvzqz** [comment]
I'm interested in adding `Box::from_unique` and making unstable under #27730. I assume it should probably be a separate PR.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Pull request merged**
