### PR TITLE
Document the optional extra arguments to assert_eq!() / assert_ne!()

### PR DESCRIPTION
**Pull request by federicomenaquintero**
And clarify that those arguments in assert!() are in fact formattable.

### CODE REVIEW

**Comment by federicomenaquintero** [comment]
Apparently the extra arguments got added in 1.11.0.  Do the docs need to mention this?  I don't know the convention for documenting new features that only work starting at a certain version.

**Comment by steveklabnik** [comment]
They do not. In general, docs should not mention version numbers.

**Comment by federicomenaquintero** [comment]
Oh, ok - then I guess the changes are complete :)

**Comment by mrhota** [comment]
@federicomenaquintero do you have time to rebase? if not, I can do it, but you'll need to close this PR and I'll issue a new one

**Comment by federicomenaquintero** [comment]
I've pushed a rebased version to the same branch.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Comment by alexcrichton** [comment]
@bors: retry

* netbsd network failure #39097

**Pull request merged**
