### PR TITLE
Fix Pin urls in Option documentation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes the following situation:

Screenshot from 2019-07-08 13-24-59

r? @QuietMisdreavus

### CODE REVIEW

**Comment by lzutao** [comment]
I think we already had links to Pin in method definitions. So make additional links in docs
seems redudent to me.

**Comment by GuillaumeGomez** [comment]
@lzutao That's not even about duplicates or whatever: if a type appears in the documentation and it's not `Self`, then it has to be linked to its location.

**Comment by czipperz** [comment]
It seems like some fundamental types auto link (ie `i32`) from my experience.

**Comment by GuillaumeGomez** [comment]
They *should* but reality is often harsh and deceptive. 🤣

**Review by QuietMisdreavus — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
The fact that those were able to get merged and make it into nightly makes me wonder about the "missing intra-doc link target" lint. Is that being properly warned against in libcore? I would expect that to generate a warning.

@lzutao It looks like these methods didn't have any links in the doc text, and the fact that the types are also hyperlinked is not obvious from looking at it. Having the links in these docs is fine.

@bors r+ rollup

**Pull request merged**
