### PR TITLE
nits: Cleanup of `librustdoc::clean::Cfg::simplify_with`

### PR DESCRIPTION
**Pull request by poliorcetics**
r? @GuillaumeGomez

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks! Once CI is green, r=me.

@bors delegate=poliorcetics

**Comment by poliorcetics** [comment]
[Failure](https://github.com/rust-lang-ci/rust/actions/runs/12480187036/job/34830619361) was:

```failures:

---- package::workspace_with_local_dep_already_published stdout ----
running `D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe package`
thread 'package::workspace_with_local_dep_already_published' panicked at src\tools\cargo\tests\testsuite\package.rs:6200:10:

test failed running `D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe package`
error: process exited with code 101 (expected 0)
--- stdout

--- stderr
   Packaging dep v0.1.0 (D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\tmp\cit\t2250\foo\dep)
    Packaged 4 files, 1.1KiB (723.0B compressed)
   Packaging main v0.0.1 (D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\tmp\cit\t2250\foo\main)
    Updating crates.io index
    Packaged 4 files, 1.5KiB (897.0B compressed)
   Verifying dep v0.1.0 (D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\tmp\cit\t2250\foo\dep)
   Compiling dep v0.1.0 (D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\tmp\cit\t2250\foo\target\package\dep-0.1.0)
error: couldn't create a temp dir: Access is denied. (os error 5) at path "D:\\a\\_temp\\msys64\\tmp\\rustcyEAdB6"

error: could not compile `dep` (lib) due to 1 previous error
error: failed to verify package tarball



failures:
    package::workspace_with_local_dep_already_published

test result: FAILED. 3305 passed; 1 failed; 246 ignored; 0 measured; 0 filtered out; finished in 473.07s
```

Completely unrelated to my changes I think ?

**Comment by GuillaumeGomez** [comment]
You could have retried, you have the rights too on this PR normally. ;)

@bors retry

**Pull request merged**
