### PR TITLE
[beta] rollup

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This rolls up the following bumps onto the beta branch; no backports in this PR.

*  [beta] Bootstrap update #92888 
*  [beta] backport cargo #92839 

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors p=1

Needed for Crater run to kickoff.

**Comment by ehuss** [comment]
Unless there is something wrong with the log capture, it looks like it is hanging updating crates.io:

```
2022-01-18T18:32:20.5711041Z Building rustbuild
2022-01-18T18:32:20.7118437Z     Updating crates.io index
2022-01-18T22:46:55.7969765Z ##[error]The operation was canceled.
```

I've been seeing this happening lately.  I don't have too many ideas what is causing it, though.

I discussed with the Cargo team to see if anyone had thoughts about using a watchdog on rust-lang/rust to check for console output. Alex felt it would be fairly easy, but I'm a little more skeptical.

**Pull request merged**
