### PR TITLE
Do not ignore doc block for pub extern crate

### LINKED ISSUE #42810: Doc block ignored for `pub extern create`
Looks like doc blocks for `pub extern crate` are ignored and don't show up anywhere in the generated documents.

So, this code
```
/// Unicode Character Database.
pub extern crate unic_ucd as ucd;

/// Unicode Bidirectional Algorithm (USA\#9).
pub extern crate unic_bidi as bidi;

/// Unicode Normalization Forms (USA\#15).
pub extern crate unic_normal as normal;

/// Unicode IDNA Compatibility Processing (UTS\#46).
pub extern crate unic_idna as idna;
```

Results in this output:
screen shot 2017-06-21 at 2 18 10 pm

I believe it's not intentional and just a missing feature because of the (kind of) new `pub extern crate` syntax. Is that correct?

### PR DESCRIPTION
**Pull request by dsciarra**
Fixes #42810

### CODE REVIEW

**Comment by dsciarra** [comment]
r?

**Comment by GuillaumeGomez** [comment]
Please add tests as well to ensure this is working as expected (in `src/test/rustdoc`). Take a look at the the tests using `aux` for the dependency.

**Comment by JohnCSimon** [comment]
Ping from triage
@dsciarra  - can you  please address the comment from the reviewer? Thanks.

**Comment by crlf0710** [comment]
Hi, i'm closing this due to inactivity. Feel free to reopen or open a new PR when you want to continue working on this. Thanks!

**Pull request closed without merging**
