### PR TITLE
Clarify AcqRel's docs

### LINKED ISSUE #49127: Ordering::AcqRel implementation contradicts the docs
Documentation on `Ordering::AcqRel` states:
```
AcqRel
When coupled with a load, uses `Acquire` ordering, and with a store `Release` ordering.
```

However, this code
```
use std::sync::atomic::{AtomicBool, Ordering};

fn main() {
    let b = AtomicBool::new(false);
    b.store(true, Ordering::AcqRel);
    b.load(Ordering::AcqRel);
}
```
panics on both store and load (if the call to store() is commented out)

```
thread 'main' panicked at 'there is no such thing as an acquire/release store', /checkout/src/libcore/sync/atomic.rs:1482:19
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Either documentation should be updated to describe why this is not relevant to store/load, or implementation should be fixed to actually deliver on the promise.

### PR DESCRIPTION
**Pull request by steveklabnik**
This implied things that are not true.

Fixes #49127

### CODE REVIEW

**Comment by pietroalbini** [comment]
Highfive failed to assign an reviewer, picking someone randomly from the docs team.

r? @frewsxcv

**Comment by nagisa** [comment]
Well, lets see. The new wording seems as ambiguous to me. One can interpret the current wording as being equivalent to `SeqCst` in most cases (since `Acquire` and `Release` are the two disjoint parts of `SeqCst`, usually).

Can we just note that this ordering is only applicable for operations that combine both loads and stores and for loads it then uses acquire ordering and for stores it would use the release ordering?

**Comment by steveklabnik** [comment]
@bors: r-

@nagisa sure, I'll try to hammer that into something. I mostly think that the current wording is very misleading; I'm not particularly attached to my wording here.

**Pull request merged**
