### PR TITLE
Improve example of Iterator::reduce

### LINKED ISSUE #81819: [ER] Iterator::reduce docs example code
I think it's better in general for the standard docs to contain examples that are easy to understand, but are also realistic usages of functions and features. An example of this is in slice::binary_search that shows how to insert an item to a sorted vector while maintaining sort order.

So I think the docs of Iterator::reduce could be improved with a more real usage example (to replace the current find_max example). And I think such docs should also say that reduce is useful when your binary operation doesn't have an identity element (or when you don't want to use it for some reason, like efficiency, etc).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #81819.

I took your example @bstrie from https://github.com/rust-lang/rust/issues/81819 and applied it here.

r? @thomcc

### CODE REVIEW

**Comment by vacuus** [comment]
(Apparently I have nothing better to do than to browse PRs here!)
The comment talking about `fold` should say "equivalent to" rather than "equivalent than".

**Comment by GuillaumeGomez** [comment]
Thanks @vacuus !

@bors r-

**Pull request merged**
