### PR TITLE
Pull configs out into individual repositories

### PR DESCRIPTION
**Pull request by steveklabnik**
As we grow, these don't belong in-tree.

http://internals.rust-lang.org/t/moving-editor-highlighting-into-their-own-repos/1395
- https://github.com/rust-lang/rust.vim
- https://github.com/rust-lang/rust-mode
- https://github.com/rust-lang/gedit-config
- https://github.com/rust-lang/kate-config
- https://github.com/rust-lang/nano-config
- https://github.com/rust-lang/zsh-config

### CODE REVIEW

**Comment by tbu-** [comment]
Are they still installed though?

**Comment by chris-morgan** [comment]
@tbu-: what do you mean, are they installed? If you mean what I think you mean, that’d be the job of packagers, not us (as it always has been, hasn’t it?).

**Comment by tbu-** [comment]
@chris-morgan We're implicitely packagers too, with rustup.sh for example.

**Comment by chris-morgan** [comment]
@tbu-: rustup.sh works from the nightly builds, which don’t include these things.

**Comment by tbu-** [comment]
@chris-morgan We're packagers – not packaging things that were previously installed is a usability loss. If this becomes impossible to support once the editor files are moved out of the main repo, maybe that should be reconsidered instead?

**Comment by richo** [comment]
Lurking in, this seems like it's a going to devolve into bikeshedding pretty fast. However, in general the convention tends to be that:

* Editors ship a set of sane defaults in core. As rust grows adoption, I would expect vim/emacs/nano and pals to do something reasonable about syntax highlighting etc out of the box.
* Users are increasingly managing their own editor configs out of tree anyway. For *this* usecase, bundling them separately is a huge usability win.

In general though, moving them to a place that is more easily discovered should generally be considered a usability win, imo. As a trivial example, if you don't want to install your rusts system wide, you now have the option to install the editor plugins system wide, or to install them separately and not have your editor config depend on the arbitrary place you install rust to.

my 2c, and I apologise in advance if this just makes the bikeshedding worse.

**Comment by chris-morgan** [comment]
@tbu-: I’m saying that I don’t believe we ever *did* install these things.

**Comment by chris-morgan** [comment]
As far as the Vim files are concerned, I intend to submit it upstream (into the Vim and Syntastic repositories) when Rust 1.0 is released.

**Pull request merged**
