### PR TITLE
Report "missing lifetime specifier" when an anonymous lifetime is used in bounds

### PR DESCRIPTION
**Pull request by cjgillot**
Both diagnostics pretty much do the same thing: report erroneous lifetime elision.

The "missing lifetime specifier" diagnostic has better diagnostics, as it suggests adding a named lifetime parameter.

This change does not accept more code, it just changes the diagnostic.

r? @petrochenkov

### CODE REVIEW

**Review by GuillaumeGomez — CHANGES_REQUESTED** [review]
Please don't remove error code explanations! There are examples where they are not emitted anymore. Please do the same for this error code as well.

**Comment by cjgillot** [comment]
I don't understand your comment. The md file has been removed for other errors that are not emitted any more, hasn't it?

**Comment by GuillaumeGomez** [comment]
It wasn't supposed to. I realized that a few months ago (maybe more than a year now, not sure...). The point is: if people with older rustc version look at newer rust error code page, they will not see their error anymore. Just update the md file like [this one](https://github.com/rust-lang/rust/blob/master/compiler/rustc_error_codes/src/error_codes/E0001.md).

**Comment by GuillaumeGomez** [comment]
Ah bingo, my CI check worked. :)

**Comment by GuillaumeGomez** [comment]
Thanks! It's possible that the test will fail because of the `compile_fail,E0106,E0637`. If so, just update it to `compile_fail,E0106` and it should work.

**Comment by petrochenkov** [comment]
@cjgillot 
>This change does not accept more code, it just changes the diagnostic.

How it happens exactly? What serves as a replacement for `AnonymousReportError`?

**Comment by cjgillot** [comment]
This was used for where predicates, and generic parameters.  In these cases, there is no resolution for the elided lifetime, so we correctly print "missing lifetime specifier".
However, I forgot to account for universal impl-trait, where we need to explicitly forbid anonymous lifetimes, because purely syntactic rules would do the wrong thing.

**Pull request closed without merging**
