### PR TITLE
remove `let x = baz` which was obscuring the real error

### LINKED ISSUE #51172: NLL injects type infer failures in presence of subsequently-masked lifetime errors
Look at  https://github.com/rust-lang/rust/blob/master/src/test/ui/lifetime-errors/ex2a-push-one-existing-name-early-bound.rs

```rust
trait Foo<'a> {}
impl<'a, T> Foo<'a> for T {}

fn baz<'a, 'b, T>(x: &mut Vec<&'a T>, y: &T)
    where i32: Foo<'a>,
          u32: Foo<'b>
{
    x.push(y); //~ ERROR explicit lifetime required
}
fn main() {
let x = baz;
}
```

its expected error output is (https://github.com/rust-lang/rust/blob/master/src/test/ui/lifetime-errors/ex2a-push-one-existing-name-early-bound.stderr)

```
error[E0621]: explicit lifetime required in the type of `y`
  --> $DIR/ex2a-push-one-existing-name-early-bound.rs:17:12
   |
LL | fn baz<'a, 'b, T>(x: &mut Vec<&'a T>, y: &T)
   |                                       - consider changing the type of `y` to `&'a T`
...
LL |     x.push(y); //~ ERROR explicit lifetime required
| ^ lifetime `'a` required
```

but under NLL it yields (https://github.com/rust-lang/rust/blob/master/src/test/ui/lifetime-errors/ex2a-push-one-existing-name-early-bound.nll.stderr):

```
warning: not reporting region error due to nll
  --> $DIR/ex2a-push-one-existing-name-early-bound.rs:17:12
   |
LL |     x.push(y); //~ ERROR explicit lifetime required
   |            ^

error[E0282]: type annotations needed
  --> $DIR/ex2a-push-one-existing-name-early-bound.rs:20:9
   |
LL | let x = baz;
   |     -   ^^^ cannot infer type for `T`
   |     |
   |     consider giving `x` a type

error: aborting due to previous error
```

The latter is amazingly different from the former.

### PR DESCRIPTION
**Pull request by nikomatsakis**
fixes #51172

### CODE REVIEW

**Comment by cramertj** [comment]
I'm not sure if there's another commit in the queue which changes the error message here, but this has caused failures in rollups a couple of times: see https://github.com/rust-lang/rust/pull/53184#issuecomment-411311208 and https://github.com/rust-lang/rust/pull/53195#issuecomment-411435228.

**Comment by nikomatsakis** [comment]
I think it is probably because of one of the PRs from @davidtwco or @matthewjasper that change the error messages here.

**Comment by pietroalbini** [comment]
Ping from triage @nikomatsakis! It's been a while since we heard from you, will you have time to work on this again?

**Pull request merged**
