### PR TITLE
Change --extern-html-root-url to use crate source path as key

### LINKED ISSUE #76296: --extern-html-root-url uses library names to identify dependencies, failing to handle multiple versions
With this package that uses dependency renaming:

```toml
# Cargo.toml

[package]
name = "foobar"
version = "0.1.0"
edition = "2018"

[dependencies]
ac = { package = "async-compression", features = ["stream", "gzip"], version = "0.3" }
ac02 = { package = "async-compression", features = ["stream", "gzip"], version = "0.2" }
```

```rust
// src/main.rs

#[doc(inline)]
pub use {ac::stream::GzipDecoder, ac02::stream::GzipDecoder as GzipDecoder02};
#[doc(no_inline)]
pub use {ac::stream::GzipEncoder, ac02::stream::GzipEncoder as GzipEncoder02};
```

I tried to build documentation that can link to both of the upstream docs.rs documentation pages:

```
cargo rustdoc --locked -- -Z unstable-options
--extern-html-root-url ac02=https://docs.rs/async-compression/0.2.0
--extern-html-root-url ac=https://docs.rs/async-compression/0.3.5
```

```
rustdoc
--edition=2018
--crate-type lib
--crate-name foobar src/lib.rs
-o /tmp/tmp.ni0GV7DIZf/foobar/target/doc
--error-format=json --json=diagnostic-rendered-ansi
-Z unstable-options
--extern-html-root-url 'ac02=https://docs.rs/async-compression/0.2.0'
--extern-html-root-url 'ac=https://docs.rs/async-compression/0.3.5'
-L dependency=/tmp/tmp.ni0GV7DIZf/async-compression/target/debug/deps
--extern ac02=/tmp/tmp.ni0GV7DIZf/foobar/target/debug/deps/libasync_compression-ad6b882a4c15a1f0.rmeta
--extern ac=/tmp/tmp.ni0GV7DIZf/foobar/target/debug/deps/libasync_compression-875810b2ce8d0002.rmeta
--crate-version 0.1.0
```

This failed to link to either of the non-inlined exports because it seems that `--extern-html-root-url` expects the library name instead, changing to use that:

```
cargo rustdoc --locked -- -Z unstable-options
--extern-html-root-url async_compression=https://docs.rs/async-compression/0.2.0
--extern-html-root-url async_compression=https://docs.rs/async-compression/0.3.5
```

```
rustdoc
--edition=2018
--crate-type lib
--crate-name foobar src/lib.rs
-o /tmp/tmp.ni0GV7DIZf/foobar/target/doc
--error-format=json --json=diagnostic-rendered-ansi
-Z unstable-options
--extern-html-root-url 'async_compression=https://docs.rs/async-compression/0.2.0'
--extern-html-root-url 'async_compression=https://docs.rs/async-compression/0.3.5'
-L dependency=/tmp/tmp.ni0GV7DIZf/async-compression/target/debug/deps
--extern ac02=/tmp/tmp.ni0GV7DIZf/foobar/target/debug/deps/libasync_compression-ad6b882a4c15a1f0.rmeta
--extern ac=/tmp/tmp.ni0GV7DIZf/foobar/target/debug/deps/libasync_compression-875810b2ce8d0002.rmeta
--crate-version 0.1.0
```

This successfully added links on both, but both directing to version `0.3.5` since that was the last flag specified.

(I'm not sure of the correct solution for this, currently docs.rs only passes `--extern-html-root-url` for direct dependencies, so changing to use the same name as used for `--extern` would work for that; but it seems to me that docs.rs should be passing a flag for _all_ dependencies, since it's possible for documentation from a dependency of a dependency to bubble-up and be rendered, so it should be possible to set the html-root-url for them all, I'm not sure how we would identify the crates in that case).

### Meta
```
rustdoc 1.47.0-nightly (7e6d6e5f5 2020-08-16)
```

### PR DESCRIPTION
**Pull request by Nemo157**
This is the most correct solution I see to #76296, this allows setting the html-root-url for all crates in the dependency tree, no matter how many duplicates of a specific crate name exist.

I have prototyped the associated docs.rs changes in my script that builds in the same fashion as it: <https://github.com/Nemo157/dotfiles/commit/d452627d1a5649cf3baaefa29be35e57a7f4929a>. Before this is merged we would want to do the same for docs.rs itself (I'll make a PR for this shortly), it's forwards-compatible to start emitting both sets of flags and remove the current ones later, extra unused flags are just ignored.

fixes #76296

### CODE REVIEW

**Comment by jyn514** [comment]
This seems to expose build details a little bit - does cargo even provide a way to get the .so file that corresponds to a crate? I wouldn't want to make this breaking change without knowing there's a way to actually use it, if you could put together a demo of a cargo-based project that would make me feel a lot better.

cc @eddyb - this changes rustdoc to look up info about a crate by the source path (`extern-html-root-url/auxiliary/libextern_html_root_url.so`) instead of the crate name (`extern_html_root_url`) so that rustdoc can distinguish between versions of a crate with the same name.

**Comment by Nemo157** [comment]
> This seems to expose build details a little bit - does cargo even provide a way to get the .so file that corresponds to a crate? I wouldn't want to make this breaking change without knowing there's a way to actually use it, if you could put together a demo of a cargo-based project that would make me feel a lot better.

See the link to my `cargo doc-like-docs.rs` changes, using `cargo check --message-format=json` it emits `compiler-artifact` messages with the files that were produced for each crate.

**Comment by Nemo157** [comment]
It needs significant cleanup, but <https://github.com/rust-lang/docs.rs/compare/master...Nemo157:issue-76296> mostly implements this on the docs.rs side. 

<details><summary>example command from docs.rs build log</summary>

image

</details>

**Comment by ehuss** [comment]
Hm, using extern paths is an interesting approach!  It does neatly solve the problem of having some unique identifier to correlate each extern crate.  Another approach I had thought about was to encode the `-C extra-filename` in the crate metadata, and then use that hash as an identifier, but that didn't seem very good.

It would be nice to have some strategy to also fix #56169.  I'm not sure how this could fit in with that, or if that will need to be solved with a completely different approach.

I would be concerned about comparing paths directly.  Using absolute paths tends to be tricky and runs the risk of not working in various situations.  [`same-file`](https://crates.io/crates/same-file) would be an option to reliably compare paths, but I'm uncertain if that's would have a significant performance impact.

Regarding the concern about long command-line paths, I'm thinking that the best option is to use a [response file](https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path).  I'm a little uncomfortable doing that in Cargo (it tends to be a pain to work with), but I'm not sure if there are many other options. 

Even though I am the author of the `crate_extern_paths` query, I am uncertain if it is appropriate to use it in this fashion.

The [documentation](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/unstable-features.md#--extern-html-root-url-control-how-rustdoc-links-to-non-local-crates) should probably be updated.

**Comment by Nemo157** [comment]
One thought I just had to reduce the command size back a bit; we probably don't need the absolute path, given the metadata suffix just using the filename would probably be enough, so that would only add an extra ~26 characters per crate.

**Comment by crlf0710** [comment]
Triage: There's merge conflicts now.

**Comment by JohnCSimon** [comment]
Ping from triage
@Nemo157 - can you please resolve the merge conflict, and alert the reviewer? Thank you!

**Comment by Dylan-DPC** [comment]
@Nemo157 any updates on this?

**Comment by Dylan-DPC** [comment]
Closing this as inactive

**Pull request closed without merging**
