### PR TITLE
metadata: Some crate loading cleanup

### PR DESCRIPTION
**Pull request by petrochenkov**
So, my goal was to fix caching of loaded crates which is broken and causes ICEs like #56935 or #64450.
While investigating I found that the code is pretty messy and likes to confuse various things that look similar but are actually different.
This PR does some initial cleanup in that area, I hope to get to the caching itself a bit later.

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
r=me if ready

**Comment by Centril** [comment]
(Speculative) Failed in https://github.com/rust-lang/rust/pull/65070#issuecomment-538126828, @bors r-

**Comment by petrochenkov** [comment]
Oh well, same crate built for two different targets has different crate disambiguators after all.
I'll remove the last commit.

**Pull request merged**
