### PR TITLE
Fix build of the `build-manifest` tool

### PR DESCRIPTION
**Pull request by alexcrichton**
Accidentally broken in #56258!

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+

I would also like to include https://github.com/rust-lang/rust/commit/2c581c5a89f88449b7d849a283eb3bbfdd04e4fc or something along those lines -- however approving this to hopefully make sure it gets in before the next nightly, since that commit is just to make sure it doesn't break again.

**Comment by Mark-Simulacrum** [comment]
Ah let's also @bors p=1 this

**Comment by temannin** [comment]
Not sure if this is related but issuing this command:
`curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly` 
is currently failing for me.

**Pull request merged**
