### PR TITLE
Back InitMask by IntervalSet

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
On the example below (sourced from #93215), this cuts ~2 GB of memory from the total memory usage at no significant delta or a slight improvement in instruction counts; will run perf across the full suite of benchmarks to evaluate any further need for improvements. The example moves from using 33 to 31 GB, roughly, which makes sense: the array is 16\*10,000\*100,000 = 14.9 GB, which corresponds to ~1.86 GB for the initialization bitset. (The full array is initialized in this case).

The remaining memory usage is due to the two copies of the array stored in memory: currently all constants we pass into LLVM are duplicated because LLVM seems to require a trailing null byte (which we don't provide), requiring a reallocation by LLVM. See LLVMConstStringInContext calls, if interested in more detail. This is likely fixable but will require some further work that's largely orthogonal from this PR, and the wins in this PR will remain useful.

```rust
const ROWS: usize = 100000;
const COLS: usize = 10000;

static TWODARRAY: [[u128; COLS]; ROWS] = [[0; COLS]; ROWS];

fn main() {}
```

### CODE REVIEW

**Comment by tmiasko** [comment]
The worst case scenarios that came up last time in this context have been array where elements contain padding, for example:

```rust
pub static TWODARRAY: [[(u64, u8); COLS]; ROWS] = [[(0, 0); COLS]; ROWS];
```

**Comment by Mark-Simulacrum** [comment]
Yeah, we'll do much worse on such arrays, it's a good point. I'm not sure what the right tradeoff is -- in practice, for the example you suggest we still end up with something like the IntervalSet (just without random insert ability) in the compression routine.

The IntervalSet has an up to 64x increase in memory usage over the bitset approach in the worst case, I think, since every other byte being init/uninit is represented in bytes/8 in the bitset and bytes/2*16 (64x larger) in the IntervalSet. I can switch the implementation over to a ChunkedBitSet, which would work better in the all-init and all-uninit cases (with 2048 bit granularity of choice), and so potentially is a more scalable solution -- it could easily enough support all the APIs we want, though compression of some kind likely still be desirable.

It probably makes more sense to prioritize reducing worst-case extra memory (i.e., the every other bit case, for example, which a bitset of some kind is good at) rather than best-case memory where ~all bytes are the same init state.

Some part of me also wants to consider implementing some kind of compression scheme atop IntervalSet, but it's probably both complicated and not worthwhile.

**Comment by erikdesjardins** [comment]
> currently all constants we pass into LLVM are duplicated because LLVM seems to require a trailing null byte (which we don't provide), requiring a reallocation by LLVM.

This (unfortunately) doesn't seem to be the case--in practice we always pass `DontNullTerminate = true` to `LLVMConstStringInContext`.

All constants we pass into LLVM are duplicated because they're interned in a StringMap: https://github.com/llvm/llvm-project/blob/988dae653f4166020f28028cc149dd641c04dae7/llvm/lib/IR/Constants.cpp#L2982-L3002 (see also https://llvm.org/doxygen/classllvm_1_1Constant.html#details)

**Pull request closed without merging**
