### PR TITLE
revert const_type_id stabilization

### PR DESCRIPTION
**Pull request by KodrAus**
This reverts #72488, which is currently on beta and scheduled to stabilize in `1.47.0`, based on https://github.com/rust-lang/rust/pull/75923#issuecomment-696676511

It turns out we might not be quite ready to stabilize `TypeId` in const contexts before having a chance to rework its internals. Since `TypeId` is a bit of an oddity we want to be careful about how those internals are currently being relied on while making changes. That will be easier to do without having to also consider compile-time contexts.

r? @eddyb

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Accepted for beta backport (there's not really any point in landing this if we don't backport).

**Comment by RalfJung** [comment]
r=me, but also fine with waiting for @eddyb

**Comment by Mark-Simulacrum** [comment]
@bors r=RalfJung p=1

I think we should get this landed and backported quickly.

**Comment by eddyb** [comment]
Thanks! Sorry I didn't see it earlier, but yeah it doesn't really need my review since it's just a backport.

I guess we can have the discussion on whether/when to re-land the stabilization elsewhere (perhaps a tracking issue?).

**Comment by KodrAus** [comment]
> I guess we can have the discussion on whether/when to re-land the stabilization elsewhere (perhaps a tracking issue?).

I actually would really like to use type ids in const contexts for what (I hope) are non-nefarious purposes 😄 

We never actually had a proper tracking issue for this before and this PR currently links to `type_name`, so I'm creating a proper one for `type_id` now and will update the PR to point to that.

**Comment by KodrAus** [comment]
I've created a tracking issue: #77125

**Comment by KodrAus** [comment]
Based on https://github.com/rust-lang/rust/pull/77083#issuecomment-697370394

@bors r=RalfJung p=1

**Comment by RalfJung** [comment]
@Mark-Simulacrum 
> I think we should get this landed and backported quickly.

So who's doing the backport, are you or should someone else prepare a PR?

**Comment by Mark-Simulacrum** [comment]
I will do a rollup after compiler meeting today, to catch anything else that gets approved.

**Pull request merged**
