### PR TITLE
Fixes primitive sidebar link generation

### LINKED ISSUE #50746: Url pointing to invalid methods in documentation of pointer type
https://doc.rust-lang.org/std/primitive.pointer.html
https://doc.rust-lang.org/nightly/std/primitive.pointer.html

It turns out that the pointer type is implemented twice: for `impl<T> *const T` and `impl<T> *mut T`. However, the index section contains links to the first implementation only, whereas methods from the second implementation have different href anchors:

For example, links from the index:
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null

And actual anchors:
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null-1

The same in stable version.

cc @steveklabnik (I don't know the name of the docs team, unfortunately)
cc @GuillaumeGomez probably

Possibly related to #24558.

### LINKED ISSUE #55656: Duplicated documentation for primitive type pointer
Please have a look at 
rust-doc-multiple-links-to-same-stuff
(source https://doc.rust-lang.org/std/primitive.pointer.html)

It appears that for some reason the documentation for `primitive type pointer` contains a duplicated set of documentation links. `is_null`, `as_ref` and all subsequent methods appear twice in the pane on the left. The links are exactly identical from what I can tell. Not sure whether the problems lies with Rust doc, the documentation itself, or some part of the [doc.rust-lang.org](https://doc.rust-lang.org)( infrastructure (unlikely, I guess).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #50746.
Fixes #55656.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by jkordish** [comment]
Ping from triage: @QuietMisdreavus have you had time to review this PR?

**Comment by QuietMisdreavus** [comment]
Can you add a test? You can cause the linked issue by giving a struct two functions with the same name:

```rust
pub struct SomeStruct<T> { _inner: T }

impl SomeStruct<()> {
    pub fn some_fn(&self) {}
}

impl SomeStruct<usize> {
    pub fn some_fn(&self) {}
}
```

**Comment by GuillaumeGomez** [comment]
Ok!

**Comment by GuillaumeGomez** [comment]
Added the test.

**Comment by TimNN** [comment]
Ping from triage @QuietMisdreavus: This PR requires your review.

**Comment by QuietMisdreavus** [comment]
Thanks!

@bors r+

**Comment by QuietMisdreavus** [comment]
(Dunno how i closed the PR, but that wasn't supposed to happen...)

**Pull request merged**
