### PR TITLE
Migrate `macos-fat-archive`, `manual-link` and `archive-duplicate-names` `run-make` tests to rmake

### PR DESCRIPTION
**Pull request by Oneirical**
Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

Please try:

try-job: x86_64-msvc
try-job: aarch64-apple

### CODE REVIEW

**Comment by jieyouxu** [comment]
Question: is `build_native_static_lib` conflicting with any other PR, and if so, should this be blocked on some PR that first introduces the helper?

**Comment by Oneirical** [comment]
> Question: is `build_native_static_lib` conflicting with any other PR (I think it does?), and if so, should this be blocked on some PR that first introduces the helper?

Not anymore since #126208 got merged. I still shuffle `lib.rs` around a bit so that the `shallow_find_files` companion functions are all nicely packed together.

**Comment by jieyouxu** [comment]
> Not anymore since #126208 got merged. I still shuffle `lib.rs` around a bit so that the `shallow_find_files` companion functions are all nicely packed together.

Er, do you mind waiting for https://github.com/rust-lang/rust/pull/127760 which will... shuffle `lib.rs` quite a bit?

**Review by jieyouxu — APPROVED** [review]
Thanks, changes look reasonable to me.

**Comment by Oneirical** [comment]
@rustbot ready
Please re-approve.

**Pull request merged**
