### PR TITLE
Make file names in error messages links to that file.

### PR DESCRIPTION
**Pull request by Dragon-Hatcher**
#107838 Made error codes in error messages link to the webpage that explains the error code.

This change expands on that by making the file names in error messages link to the file. This makes it easy to open the file with the error by clicking the link to the file.

### CODE REVIEW

**Comment by Dragon-Hatcher** [comment]
After further inspection the terminal links standard is a little more involved. I've made some fixes.

https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

We need to look into how the test is going to work. A correct file uri involves the hostname which isn't static in CI.

**Comment by Dragon-Hatcher** [comment]
Can't really get CI to pass right now. We will need more discussion on the correct way to do that. Perhaps the hostname could be replaced with `$HOST$` by the harness like the folder is?

**Comment by WaffleLapkin** [comment]
r? @estebank

probably knows better how this works

**Comment by estebank** [comment]
I tried to get this working on the original PR and I encountered the same issues you did, including terminals that worked without a host, but didn't support a host being set, and others that didn't work without a host. Additionally, when using VSCode SSHd to a remote desktop, the file URLs still try to open a local file. It seems like file path support is even *lower* than that of file paths :-/

I don't know if we should try to accomplish this today, and maybe instead pester upstreams to gain more support?

**Comment by estebank** [comment]
It might make sense to make this a separate opt-in. In the terminals that I regularly use, they already recognize paths that can be resolved, turning them into links when pressing ctrl/command that open the file with whatever default application you have set up (and had the benefit of working with SSH + VScode). That's why I felt it wasn't necessary to spend too much time figuring that part out on the original PR :)

**Comment by Dragon-Hatcher** [comment]
Ok. What about making the `-Zterminal-urls` accept `no`, `err-code`, `files`, or `all` (<- bikeshedable oc)

**Comment by estebank** [comment]
@Dragon-Hatcher that sounds reasonable to me. If `-Zterminal-urls` is passed with no value, it probably should default to `err-code`.

**Comment by apiraino** [comment]
Switching to waiting on author for further design work (IIUC the context) . @Dragon-Hatcher  Feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

**Comment by JohnCSimon** [comment]
@Dragon-Hatcher 

ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by Dragon-Hatcher** [comment]
I'm still interested in the feature but I don't have time to work on this right now.

**Comment by JohnCSimon** [comment]
@Dragon-Hatcher 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
