### PR TITLE
Fix thin archive reading

### LINKED ISSUE #107162: Windows builds fail to link C++ static library
### Code

Building the mozjs crate for any Windows target stopped working after https://github.com/rust-lang/rust/pull/97485. mozjs has a build script that compiles the C++ library SpiderMonkey into `js_static.a`, which is then [linked](https://github.com/servo/mozjs/blob/0b37834da6080ddd77c7770bf0f610665bb81129/mozjs/build.rs#L184). Before https://github.com/rust-lang/rust/pull/97485, these builds worked successfully. Since that PR was merged, CI using nightly and beta toolsets targeting MSVC x86_64 and UWP x86_64 now fail to build with the following error:
```
error: failed to add native library D:\a\mozjs\mozjs\target\debug\build\mozjs_sys-4062d5cd7cbc7110\out\build/js/src/build\js_static.lib: Unsupported archive identifier
```

This was first reported in https://github.com/servo/mozjs/issues/327 and https://github.com/servo/mozjs/issues/334.

### Version it worked on

2022-12-03 nightly
Rust 1.66 beta

### Version with regression

2022-12-04 nightly
Rust 1.67 beta

If you know when this regression occurred, please add a line like below, replacing `{channel}` with one of stable, beta, or nightly.

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by bjorn3**
This includes a revert of https://github.com/rust-lang/rust/pull/105221 to restore fat archive reading with LlvmArchiveBuilder.

Should fix #107162, #107334 and https://github.com/google/shaderc-rs/issues/133

### CODE REVIEW

**Comment by bjorn3** [comment]
@bors try

to provide a toolchain that can be used for testing if this indeed fixed it. This will build a linux toolchain, if necessary I can do a windows toolchain after that.

**Comment by bjorn3** [comment]
This indeed fixes reading thin archives. At least on Linux:

```shell
$ rustup-toolchain-install-master 87b60fa8c61c1fc5243bb1bce530da8f3f694d4d
[...]
$ echo | rustc - --emit obj --crate-type lib # create dummy object file
$ ar rsT libthin.a rust_out.o # create thin archive
$ echo | rustc +stable -l static=thin - --crate-type staticlib -L .
error: failed to add native library ./libthin.a: Unsupported archive identifier

error: aborting due to previous error

$ echo | rustc +87b60fa8c61c1fc5243bb1bce530da8f3f694d4d -l static=thin - --crate-type staticlib -L .
$ echo $?
0
```

Going to do a windows try build too as most reports are coming from windows.

@bors try

**Comment by bjorn3** [comment]
@jdm, @sagudev, @jpalus and @kanerogers can you try if this fixes the regression for you? You can use `rustup-toolchain-install-master -c cargo 87b60fa8c61c1fc5243bb1bce530da8f3f694d4d` to install the linux try build and `rustup-toolchain-install-master -c cargo e65225bb3f98a0001676c0cc139656e7209590c2` to install the windows try build if you have `rustup-toolchain-install-master` installed from crates.io.

**Comment by sagudev** [comment]
Can confirm it is working for mozjs on windows (apparently we use thin only for windows builds).
[Here](https://github.com/sagudev/mozjs/actions/runs/4026990931) is nightly build for control test (it is expected to fail).
[Here](https://github.com/sagudev/mozjs/actions/runs/4027325649) is build using `e65225bb3f98a0001676c0cc139656e7209590c2` toolchain.

**Comment by jpalus** [comment]
@bjorn3 confirmed this PR (specifically de363d54c40a378717881240e719f5f7223ba376) fixes #107334. Thanks.

**Comment by bjorn3** [comment]
Thanks for testing!

**Comment by kanerogers** [comment]
Thanks so much for the quick turnaround @bjorn3!

I can confirm that `e65225bb3f98a0001676c0cc139656e7209590c2` fixes https://github.com/google/shaderc-rs/issues/133 on Windows. 👍🏻

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
@bors r+ p=1 

Fixes P-critical nightly breakage

**Comment by pnkfelix** [comment]
[Discussed in today's T-compiler triage meeting.](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-02-02/near/325421887)

@rustbot label: beta-accepted stable-accepted

**Pull request merged**
