### PR TITLE
in which we decline to lint single-use lifetimes in `derive`d impls

### LINKED ISSUE #53738: `single_use_lifetimes` warns when deriving a struct
When compiling 

```rust {.line-numbers}
#![warn(single_use_lifetimes)]

#[derive(Debug)]
struct Foo<'a> {
    bar: &'a u32,
}
```
this warning is generated:
```
warning: lifetime parameter `'a` only used once
 --> src/lib.rs:5:12
  |
5 | struct Foo<'a> {
  |            ^^
  |
```

I think, `#[automatically_derived]` in the `Debug` derive does not consider this lint.

### PR DESCRIPTION
**Pull request by zackmdavis**
Resolves #53738.

r? @eddyb

### CODE REVIEW

**Comment by zackmdavis** [comment]
(Pushing the branch directly to rust-lang/rust rather than my "fork" was a mistake, but probably an inconsequential one?)

**Comment by Centril** [comment]
> but probably an inconsequential one?

Yep; we have branch protection on the important branches; please just cleanup after you're done. 😃

**Comment by Centril** [comment]
@scottmcm suggested on Discord that we should change the macro expansion of the built-in derives to use `'_` instead. That seems like it might generate less code that *might* be good for perf and possibly solve this issue (but not for custom derives!). In either case, even if we land this PR in its current form, we should probably also change the expansion?

**Comment by zackmdavis** [comment]
(fixed tidy)

**Comment by petrochenkov** [comment]
Derives are a special case of "macros from other crates", which normally suppress lints.
Why doesn't that generic mechanism work here?

**Comment by oli-obk** [comment]
> Derives are a special case of "macros from other crates", which normally suppress lints.
Why doesn't that generic mechanism work here?

The problem is (as [explained by @estebank](https://github.com/rust-lang/rust/issues/53738#issuecomment-501730040)) that the derive doesn't mark the spans of idents it's using as coming from an expansion.

**Review by eddyb — APPROVED** [review]

**Pull request merged**
