### PR TITLE
Fix `x build library/std compiler/rustc`

### LINKED ISSUE #99129: `x build library/std compiler/rustc` gives an error that proc_macro isn't built
We started seeing a strange error to find the `proc-macro` crate during stage1 bootstrapping starting at this rust commit https://github.com/rust-lang/rust/commit/0a7f2c3a025c8bab1e10ccec6208a4c19b057b26.
The command we're using is `python3 x.py build library/std compiler/rustc src/tools/cargo`.
The errors look like this:
```
...
Building stage1 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
...
error[E0463]: can't find crate for `proc_macro`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-hack-0.5.19/src/lib.rs:150:1
    |
150 | extern crate proc_macro;
    | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `proc_macro`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.37/src/lib.rs:119:1
    |
119 | extern crate proc_macro;
    | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

   Compiling unic-emoji-char v0.9.0
error[E0463]: can't find crate for `proc_macro`

error[E0635]: unknown feature `proc_macro_span`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.37/src/lib.rs:90:59
   |
90 | #![cfg_attr(any(proc_macro_span, super_unstable), feature(proc_macro_span))]
   |                                                           ^^^^^^^^^^^^^^^
```
This is currently affecting our experimental rust + llvm@head build bot (https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/11778#0181d3d0-a73a-4852-8a31-edcc608fbb6f), but this error seems more general. I've set up a reproducer on Ubuntu in Docker over at https://github.com/krasimirgg/bootstrap-proc-macro-issue, which triggers this error via `python3 x.py build library/std compiler/rustc src/tools/cargo` using freshly imported rust.

It seems like `python3 x.py build library/std compiler/rustc` triggers this error; running `python3 x.py build library/std` or `python3 x.py build compiler/rustc` by themselves works.

_Originally posted by @krasimirgg in https://github.com/rust-lang/rust/issues/44293#issuecomment-1177313119_

### PR DESCRIPTION
**Pull request by jyn514**
Previously, this was broken because of improper caching:
1. `StepDescription::maybe_run` builds `Compile::Std`, which only built `std` and not `proc_macro`
1. `Std` calls `builder.ensure(StdLink)`
1. `Rustc` calls `ensure(Std)`, which builds all crates, including `proc_macro`
1. `Rustc` calls `ensure(StdLink)`. `ensure` would see that it had already been run and do nothing.  <-- bug is here
1. Cargo gives an error that `proc_macro` doesn't exist.

This fixes the caching by adding `crates` to `StdLink`, so it will get rerun if the crates that are built change.

Fixes https://github.com/rust-lang/rust/issues/99129.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
RustcLink presumably needs the same treatment?

**Comment by jyn514** [comment]
ah, good call - not sure how you could trigger this for RustcLink, since it's only called from `impl Step for Rustc`, but it's good to future proof in case we want to build individual crates (e.g. for rustfmt) in the future.

**Comment by jyn514** [comment]
@Mark-Simulacrum I don't think https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/NIghtly.20bustage.3F is actually related - the problem there is that `library/std` means something different than it used to ("build std" instead of "build all crates in the standard library"). This only affects specifically `build library/std compiler/rustc`, not `build library/std` and then `rustc +local ...`.

**Comment by Mark-Simulacrum** [comment]
Yes, I agree, but I think this is still something we should fix fairly quickly; maybe @bors p=1 though.

**Pull request merged**
