### PR TITLE
[beta] Backport CI fixes for python certificates

### PR DESCRIPTION
**Pull request by flip1995**
This backports  #90457 to the beta branch, which should fix the CI, so that both beta backport PRs #90938 and #90561 can be merged.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@cuviper do you want to roll this into the rollup you have going? r=me on the changes themselves.

**Comment by cuviper** [comment]
Sure, I'll add it.

**Comment by cuviper** [comment]
We included this in #90938, thanks!

**Pull request closed without merging**
