### PR TITLE
add 32 bit freebsd

### PR DESCRIPTION
**Pull request by posix4e**
We have a 64bit build 32 bits is great for VMs!

### CODE REVIEW

**Comment by posix4e** [comment]
I still get no snapshot found though :(

**Comment by eddyb** [comment]
@posix4e someone needs to setup a FreeBSD bot to cross-compile a 32-bit snapshot.
cc @alexcrichton @edunham

**Comment by alexcrichton** [comment]
I have a feeling that quite a bit more support will be needed to get 32-bit freebsd working, perhaps this could wait for a working build?

**Comment by posix4e** [comment]
I'll take your word on it. There's absolutely no rush on my side. I've already built a 64bit version.

**Comment by alexcrichton** [comment]
Ok! In that case I'll close this for now.

**Pull request closed without merging**
