### PR TITLE
Make all integers in the guide `i32`, implicitely

### PR DESCRIPTION
**Pull request by tbu-**
The guide still needs to talk about integer suffixes.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you so much. I saw fallback landed and I was going to do this, but I decided to make breakfast first. I'm glad I did! I'll give this a review after I'm done eating :smile:

**Comment by alexcrichton** [comment]
Needs a rebase

**Comment by tbu-** [comment]
@steveklabnik Rebased.

**Comment by tbu-** [comment]
\o/ No more `int`s in the guide. Now we only need to explicitely tell people not to use pointer-sized integers.

**Pull request merged**
