### PR TITLE
Fix stabilization of vget_low_s8

### LINKED ISSUE #94083: vget_low_s8 behind feature flag on beta
While using the `aarch64` intrinsics that are stable on beta I've noticed that [`vget_low_s8`](https://doc.rust-lang.org/core/arch/aarch64/fn.vget_low_s8.html#) still complains about not being given the `stdsimd` feature.

```rust
use std::arch::aarch64::*;

fn main() {
    [
        unsafe { vmovl_s8(vget_low_s8(val.0)) },
        unsafe { vmovl_s8(vget_high_s8(val.0)) },
    ];
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-beta.8 (1945ce657 2022-02-12)
binary: rustc
commit-hash: 1945ce6579506787e0b18f0a2ea03fdb4dfc81c7
commit-date: 2022-02-12
host: x86_64-apple-darwin
release: 1.59.0-beta.8
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

```
error[E0658]: use of unstable library feature 'stdsimd'
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Amanieu**
Fixes #94083

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
(Note: I believe the beta being referenced here is 1.60, not 1.59 which is shipping later this week, so ignoring this beta nom for release process this week).

**Comment by Amanieu** [comment]
Ideally this would get fixed in 1.59 but it's not a super high priority.

**Comment by m-ou-se** [comment]
Discussed in the libs meeting now. This doesn't seem worth backporting as far as we can tell.

**Comment by Amanieu** [comment]
Closing since this was included in the submodule update of #94529.

**Pull request closed without merging**
