### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by jonas-schievink**
Successful merges:

 - #75115 (`#[deny(unsafe_op_in_unsafe_fn)]` in sys/cloudabi)
 - #76614 (change the order of type arguments on ControlFlow)
 - #77610 (revise Hermit's mutex interface to support the behaviour of StaticMutex)
 - #77830 (Simplify query proc-macros)
 - #77930 (Do not ICE with TraitPredicates containing [type error])
 - #78069 (Fix const core::panic!(non_literal_str).)
 - #78072 (Cleanup constant matching in exhaustiveness checking)
 - #78119 (Throw core::panic!("message") as &str instead of String.)
 - #78191 (Introduce a temporary for discriminant value in MatchBranchSimplification)
 - #78272 (const_evaluatable_checked: deal with unused nodes + div)
 - #78318 (TyCtxt: generate single impl block with `slice_interners` macro)
 - #78327 (resolve: Relax macro resolution consistency check to account for any errors)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This had some [effect](https://perf.rust-lang.org/compare.html?start=ffa2e7ae8fbf9badc035740db949b9dae271c29f&end=f58ffc93815f76576eb56df4bdeec2fe8f12b766&stat=instructions:u) on compiler performance; I'm not sure which PRs were responsible. I suspect https://github.com/rust-lang/rust/pull/78072 and https://github.com/rust-lang/rust/pull/78191.

cc @Nadrieril @tmiasko -- do those perf results look like they could be because of those PRs? I think a good next step is probably to post reverts of each so that we can see if they were the cause.

**Comment by jonas-schievink** [comment]
I think #78191 only touches a disabled optimization

**Comment by Nadrieril** [comment]
@Mark-Simulacrum Ah yeah that very much looks like the effect of changes to match checking. My PR was based on https://github.com/rust-lang/rust/pull/77390 which was a perf improvement so I didn't think to check.

**Comment by Nadrieril** [comment]
I have a followup PR (https://github.com/rust-lang/rust/pull/78430) which I measured to be a large perf improvement, and would compensate the regression from #78072. If that's not enough I can bisect #78072, but that's more work

**Comment by Mark-Simulacrum** [comment]
Yeah, no worries, that sounds fine. Just wanted to make sure we had a clear idea of the cause. I don't think the regression(s) are bad enough to warrant doing more work here, especially as you have followup improvements that outweigh them.

**Pull request merged**
