### PR TITLE
Improve wording of `Vec::swap_remove`

### PR DESCRIPTION
**Pull request by pallix**
This improve the wording for  `Vec::swap_remove`.

### CODE REVIEW

**Comment by zachs18** [comment]
"If you need to preserve the elements order" should use "elements' order" or "order of elements" if you intend to make it possessive; the existing "element order" is also fine IMO (I'm not a grammarian, but IIUC it's using "element" as an adjective).

**Comment by pallix** [comment]
> the existing "element order" is also fine IMO (I'm not a grammarian, but IIUC it's using "element" as an adjective).

I find it confusing on first read but I'm not native speaker and I think you are right now, it can be kept like that.

**Comment by pallix** [comment]
I restored the second as it was initially.

**Pull request merged**
