### PR TITLE
Bump stage0 to beta-2024-09-22 and rustfmt to nightly-2024-09-22

### PR DESCRIPTION
**Pull request by compiler-errors**
I'm doing this to apply the changes to version sorting (https://github.com/rust-lang/rustfmt/pull/6284) that have occurred since rustfmt last upgraded (and a few other miscellaneous changes, like changes to expression overflowing: https://github.com/rust-lang/rustfmt/pull/6260). Eagerly updating rustfmt and formatting-the-world will ideally move some of the pressure off of the beta bump which will happen at the beginning of the next release cycle.

You can verify this is correct by checking out the changes, reverting the last commit, reapplying them, and diffing the changes:

```
git fetch git@github.com:compiler-errors/rust.git bump
git checkout -b bump FETCH_HEAD
git reset --hard HEAD~5
./x.py fmt --all
git diff FETCH_HEAD
# ignore the changes to stage0, and rustfmt.toml,
# and test file changes in rustdoc-js-std, run-make.
```

Or just take my word for it? Up to the reviewer.

r? release

### CODE REVIEW

**Comment by compiler-errors** [comment]
r? cuviper (or reassign; not totally sure who's responsible for reviewing stage0 bumps!)

**Comment by compiler-errors** [comment]
Sorting probably changed something with rustdoc-js :( Let me bless that really quick, I guess.

@bors r-

**Comment by compiler-errors** [comment]
This PR reorders the reimport of `std::collections::VecDeque` to be before `std::collections::vec_deque`. Consequently, this changes the preference of paths in the `rustdoc-js-std` test. Not sure if that needs to be tweaked, but it should be tweaked separately from this rustfmt/beta bump.

@bors r=Mark-Simulacrum

**Comment by compiler-errors** [comment]
And a run-make test had a hard-coded stderr, which needed updating. What a mess lol.

@bors r=Mark-Simulacrum

**Comment by Kobzol** [comment]
This was a pretty massive change, maybe we should add it to git blame ignore?

**Comment by compiler-errors** [comment]
Yep definitely. That was gonna be my follow-up once it lands, but it's 03:10 here. It would be very cool if you put up a PR, but if you don't, then I can do it in the morning.

**Comment by Kobzol** [comment]
https://github.com/rust-lang/rust/pull/130736

**Pull request merged**
