### PR TITLE
fix broken link to async keyword docs

### PR DESCRIPTION
**Pull request by shenawy29**

### CODE REVIEW

**Comment by shenawy29** [comment]
I've just noticed that the link, for some reason, is broken in the LSP documentation but works on the documentation website? This is on the stable build

**Comment by Mark-Simulacrum** [comment]
Can you say more about where this link is showing up broken? It seems to work for me on https://doc.rust-lang.org/nightly/std/future/trait.Future.html and https://doc.rust-lang.org/nightly/core/future/trait.Future.html

**Comment by Mark-Simulacrum** [comment]
Ah I missed your comment. I don't know much about the LSP documentation but I'd say that's probably a bug in the editor or in LSP tooling. I'd file an issue with rust-analyzer and see what they think, I doubt this is the only link affected.

**Comment by shenawy29** [comment]
> Ah I missed your comment. I don't know much about the LSP documentation but I'd say that's probably a bug in the editor or in LSP tooling. I'd file an issue with rust-analyzer and see what they think, I doubt this is the only link affected.

You're right, a lot of links are broken. I'll see if others have this issue, thanks!

**Pull request closed without merging**
