### PR TITLE
Only keep one dep-graph in memory

### PR DESCRIPTION
**Pull request by cjgillot**
This is a re-implementation from scratch of the dep-graph storage.

Instead of keeping the deserialized dep-graph immutable in memory,
this implementation modifies it in-place, and appends new dep-nodes to it.

The graph is cleaned-up at saving time, where all the nodes are renumbered to remove stale nodes.

r? @ghost

### CODE REVIEW

**Comment by bjorn3** [comment]
Significant regressions of up to 6%.

**Comment by bjorn3** [comment]
Regressions up to 3.9%. Incr cache loading has become faster, but saving has become slower.

**Comment by cjgillot** [comment]
Having a slower incr-cache save is on purpose. max-rss is a pretty consistent reduction up to 5%.
I now need to investigate the regression in incr-unchanged. Probably due to the increased locking.

**Comment by cjgillot** [comment]
With atomics
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Closed in favour of #82780.

**Pull request closed without merging**
