### PR TITLE
fix array drop glue: properly turn raw ptr into reference

### PR DESCRIPTION
**Pull request by RalfJung**
Discovered while working on https://github.com/rust-lang/rust/pull/53424: The generated drop glue uses an assignment `ptr = cur` where `ptr` is a reference and `cur` a raw pointer. This is not well-formed MIR.

Do we have MIR sanity checks that run on the drop glue and should have caught this?

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
cc @arielb1 

@bors r+

**Comment by arielb1** [comment]
I'm not sure how legitimate it is to call `drop` on an `&mut T` (maybe it is with your semantics?). If that is a problem, I would prefer the type to be `*mut T` everywhere.

**Comment by RalfJung** [comment]
I do not understand -- `drop` *takes* `&mut`...

**Comment by RalfJung** [comment]
Also, I couldn't actually figure out how `ptr` is *used* later. Not sure if I have been looking at the wrong places or if the comments showing the MIR syntax being generated are just missing? https://github.com/rust-lang/rust/issues/53532 does not help either.

**Comment by matthewjasper** [comment]
`ptr` is used here:
https://github.com/rust-lang/rust/blob/1558ae7cfd5e1190d3388dcc6f0f734589e4e478/src/librustc_mir/util/elaborate_drops.rs#L632-L636

The mir that you want to look at is probably the one generated here:
https://github.com/rust-lang/rust/blob/6a3db033ad05f156281d50ee489d727ee0e5d767/src/librustc_mir/shim.rs#L160-L236

**Comment by RalfJung** [comment]
Ah so it moves on to the `Drop` terminator, which takes any place -- so we could just as well deref a raw pointer?

**Pull request merged**
