### PR TITLE
Allocate symbol names in an arena instead of using the string interner

### PR DESCRIPTION
**Pull request by Zoxc**
Based on https://github.com/rust-lang/rust/pull/59536.

cc @eddyb
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 792c1dd77f9e62471864033da7aa7b33a84049a3

**Comment by Zoxc** [comment]
@eddyb This turned out to be slower. Do you know of there are a lot of symbol name comparisons somewhere?

**Comment by eddyb** [comment]
Other than the incremental system itself, I don't know what would even compare symbols.

**Comment by Dylan-DPC** [comment]
ping from triage @Zoxc @michaelwoerister any updates?

**Pull request closed without merging**
