### PR TITLE
update Miri

### LINKED ISSUE #98366: `miri` no longer builds after rust-lang/rust#98359
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#98359, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @JohnTitor, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/98366
r? @ghost Cc @rust-lang/miri

### CODE REVIEW

**Comment by klensy** [comment]
Should #98386 bee closed?

**Comment by ehuss** [comment]
@bors retry

dist-x86_64-linux-alt is hung at 5 hours

**Pull request merged**
