### PR TITLE
Cache flags and escaping vars for predicates

### PR DESCRIPTION
**Pull request by matthewjasper**
With predicates becoming interned (rust-lang/compiler-team#285) this is now possible and could be a perf win. It would become an even larger win once we have recursive predicates.

cc @lcnr @nikomatsakis 

r? @ghost

### CODE REVIEW

**Comment by matthewjasper** [comment]
ICE is correct behavior, the test is broken (cf #72788).
@bors try @rust-timer queue

**Comment by matthewjasper** [comment]
The perf improvements seem a little too good to just be the type flag changes. I guess that a lot of them are the change to hash predicates by address. I've moved the change that breaks the test into #72788.

r? @nikomatsakis or @oli-obk

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors r+ rollup=never

Perf sensitive

**Comment by RalfJung** [comment]
@bors p=1
let's work through some rollup=never PRs

**Comment by nnethercote** [comment]
Perf results from landing were a [big win](https://perf.rust-lang.org/compare.html?start=a8cf3991177f30694200002cd9479ffbbe6d9a1a&end=1a4e2b6f9c75a0e21722c88a0e3b610d6ffc3ae3&stat=instructions:u), as expected. Great job!

**Pull request merged**
