### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by oli-obk** [comment]
>  This PR updated 'src/tools/clippy', verifying if status is 'test-pass'...
[01:59:54] 
[01:59:54] ⚠️ We detected that this PR updated 'clippy-driver', but its tests failed.
[01:59:54] 
[01:59:54] If you do intend to update 'clippy-driver', please check the error messages above and
[01:59:54] commit another update.

Maybe we should just protect against not increasing the state instead of requiring us to go all the way to test-pass? cc @kennytm

**Comment by kennytm** [comment]
The test-fail is caused by failing to compile the test artifact. Just update `compiler-rs` to 0.3.20? 

```
[01:36:33] error[E0432]: unresolved import `test::ColorConfig`
[01:36:33]   --> /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.19/src/common.rs:20:5
[01:36:33]    |
[01:36:33] 20 | use test::ColorConfig;
[01:36:33]    |     ^^^^^^^^^^^^^^^^^ no `ColorConfig` in the root
[01:36:33] 
[01:36:33] error[E0433]: failed to resolve: could not find `OutputFormat` in `test`
[01:36:33]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.19/src/lib.rs:104:41
[01:36:33]     |
[01:36:33] 104 |         format: if config.quiet { test::OutputFormat::Terse } else { test::OutputFormat::Pretty },
[01:36:33]     |                                         ^^^^^^^^^^^^ could not find `OutputFormat` in `test`
[01:36:33] 
[01:36:33] error[E0433]: failed to resolve: could not find `OutputFormat` in `test`
[01:36:33]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.19/src/lib.rs:104:76
[01:36:33]     |
[01:36:33] 104 |         format: if config.quiet { test::OutputFormat::Terse } else { test::OutputFormat::Pretty },
[01:36:33]     |                                                                            ^^^^^^^^^^^^ could not find `OutputFormat` in `test`
[01:36:33] 
[01:36:33] error[E0425]: cannot find function `run_tests_console` in module `test`
[01:36:33]   --> /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.19/src/lib.rs:87:21
[01:36:33]    |
[01:36:33] 87 |     let res = test::run_tests_console(&opts, tests.into_iter().collect());
[01:36:33]    |                     ^^^^^^^^^^^^^^^^^ not found in `test`
[01:36:33] 
[01:36:33] error[E0425]: cannot find value `AutoColor` in module `test`
[01:36:33]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.19/src/lib.rs:112:22
[01:36:33]     |
[01:36:33] 112 |         color: test::AutoColor,
[01:36:33]     |                      ^^^^^^^^^ not found in `test`
[01:36:33] 
[01:36:33] error[E0412]: cannot find type `TestFn` in module `test`
[01:36:33]    --> /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.19/src/lib.rs:274:75
[01:36:33]     |
[01:36:33] 274 | pub fn make_test_closure(config: &Config, testpaths: &TestPaths) -> test::TestFn {
[01:36:33]     |                                                                           ^^^^^^ not found in `test`
```

**Comment by mati865** [comment]
Shouldn't `compiletest-rs` be patched to `src/tools/compiletest`?

**Comment by kennytm** [comment]
@mati865 No such patch exists in our Cargo.toml

https://github.com/rust-lang/rust/blob/fb5ed488ff1a251db895c545592488a67be67112/Cargo.toml#L57-L69

**Comment by Manishearth** [comment]
The tests are supposed to fail, compiletest is broken right now

**Comment by Manishearth** [comment]
What does "commit another update" mean here? How do I tell travis to ignore this?

compiletest-rs 0.20 is yanked at the moment.

**Comment by kennytm** [comment]
@Manishearth you can't tell the CI to ignore this, bors will need to ensure it is test-pass eventually.

**Comment by Manishearth** [comment]
@kennytm wait, how? I thought we didn't gate on submodule failures

**Comment by Manishearth** [comment]
Oh, are you saying that landing this will still work even if travis doesn't like it?

Care to r+?

**Comment by kennytm** [comment]
@Manishearth We *do* gate on failure on the submodules you're going to update, i.e. clippy in this PR.

**Comment by Manishearth** [comment]
I don't understand, then how was clippy broken in the first place?

What's the difference between this PR (which fixes clippy, but has the tests still fail) and the libtest PR that caused the breakage?

**Comment by kennytm** [comment]
This PR only fixed the built-fail caused by #59096, but not the test-fail caused by #57842.

The libtest PR #57842 which caused the clippy breakage did not update the clippy submodule. The test-pass gate is only applied when you specifically change `src/tools/clippy`.

**Comment by Manishearth** [comment]
Well we're currently in a situation where we cannot fix test-fail for
clippy until the libtest stuff is fixed (which is blocked on @gnzlbg and
@alexcrichton), but we wish to have clippy binaries present on nightly :/

**Comment by kennytm** [comment]
There are currently 2 solutions to solve this,

1. Wait for libtest fix, 
2. Relax the gate so that as long as the toolstate is *strictly* improved we give it a pass, as suggested in https://github.com/rust-lang/rust/pull/59396#issuecomment-475940082.

    https://github.com/rust-lang/rust/blob/fb5ed488ff1a251db895c545592488a67be67112/src/ci/docker/x86_64-gnu-tools/checktools.sh#L42

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/59783

**Pull request closed without merging**
