### PR TITLE
Made dynamic_lib migration path more explicit

### PR DESCRIPTION
**Pull request by androm3da**
The `dynamic_lib` library has been deprecated in favor of contents on crates.io, but apparently `libloading` is a more specific direction that fits the need.

### CODE REVIEW

**Comment by durka** [comment]
If the crate is good enough to recommend in the deprecation message, should it a candidate for inclusion in the nursery?

**Comment by steveklabnik** [comment]
Yes, I would argue that this should point to the literal out of tree crate rather than picking a "better" one

**Comment by androm3da** [comment]
By "literal out of tree crate" do you mean that `dynamic_lib` is now hosted on crates.io?  Or maybe that's just the plan?

**Comment by androm3da** [comment]
@steveklabnik  Ok I will change it to [`dylib`](https://crates.io/crates/dylib) -- I think it wasn't in crates.io when I first looked, or I just didn't find it.

**Pull request merged**
