### PR TITLE
Update check_unsafety.rs Change `UnsafetyViolationKind::General` to `UnsafetyViolationKind::GeneralAndConstFn`

### PR DESCRIPTION
**Pull request by CloudNClock**
Reflect on #75340

Change `UnsafetyViolationKind::General` to `UnsafetyViolationKind::GeneralAndConstFn`

Due to my mistake, PR has been merged from #75578.

### CODE REVIEW

**Comment by oli-obk** [comment]
Ah, didn't realize there was a PR. So, as mentioned in the issue, you need to bless the tests (and add a new test for the case in the issue). The fastest way to do that is `./x.py test --stage 1 --bless src/test/ui --test-args min_const_fn`. That's a mouth full, but all of these flags actually do help:

* `--stage 1` just builds a compiler and runs the tests, without first checking whether you can still build a compiler with that new compiler
* `--bless` updates `.stderr` files, you may still need to touch the source files (e.g. the `//~ is unsafe` comment in https://github.com/rust-lang/rust/blob/c94ed5ca91f1363b66970ce2cbd6e2773e3cb1d3/src/test/ui/consts/min_const_fn/min_const_fn_unsafe_bad.rs#L1 should now probably be removed)
* `--test-args min_const_fn` only runs tests with `min_const_fn` in their name

**Comment by 5M1Sec** [comment]
I added the new test case from the issue in`src/test/ui/consts/min_const_fn/min_const_fn_unsafe_ok.rs` for now. I guess it should be placed in another place or a new file?

**Comment by oli-obk** [comment]
>     1. Where should I put the test case from the issue?
>        I added the new test case from the issue in`src/test/ui/consts/min_const_fn/min_const_fn_unsafe_ok.rs` for now.
> 
>     2. Do I import
> 
> 
> ```
> #![feature(const_raw_ptr_deref)]
> #![feature(raw_ref_macros)]
> use std::ptr;
> ```
> 
> in the same file or other places?

While I personally am fine with the changes you made, I don't think the original driver behind `min_const_fn_unsafe_ok.rs` would be, so let's put it into a separate file in the same directory. Since the file will compile successfully, we'll need a `// check-pass` comment in that new file. 

> Sorry, this is my first time getting into a big open source project. Thank you all for your explanations.

No worries! These are all good questions, please never stop asking.

**Comment by 5M1Sec** [comment]
What should I do now with all the commits? I try to squash the commits and then unexpected merge seems to be pushed. And previous commits are still shown. Did I do it in the wrong way? I think I should revert the merge?
If I commit, will the assignees receive a notification?  Generally speaking, should I leave a comment after a stage of commits?  
Thanks.

**Comment by RalfJung** [comment]
You already have a merge commit in here, so please rebase on top of latest `origin/master` while also squashing:
```
git fetch origin
git rebase --interactive origin/master
```
That should not create any merge commits. See for example [this explanation](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) of rebasing.

The reviewer will be notified when you do a regular push, but force-pushes unfortunately do not reliably trigger notifications (GitHub is acting rather strange there), so generally it is a good idea to ask the reviewer to have another look when the PR is ready again.

**Comment by oli-obk** [comment]
Jup, so the PR lgtm. While doing the rebase, please squash all commits into the first one

**Pull request closed without merging**
