### PR TITLE
TryReserveErrorKind tests and inline

### PR DESCRIPTION
**Pull request by kornelski**
A small follow-up to #87408

### CODE REVIEW

**Comment by the8472** [comment]
I didn't explicitly mention it, the `kind()` method probably needs an inline too, for the same reason.

**Comment by kornelski** [comment]
kind already has inline

**Comment by m-ou-se** [comment]
Thanks!

@bors r+

**Comment by m-ou-se** [comment]
@bors rollup=never

(Because of https://github.com/rust-lang/rust/pull/87408#issuecomment-896941643)

**Pull request merged**
