### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #47799, #48095, #48123, #48152, #48234, #48236, #48239, #48243
- Failed merges:

### CODE REVIEW

**Comment by pnkfelix** [comment]
@GuillaumeGomez as much as I'd like to see a fix for #47355 land, I am not sure that #48236 is as fully-prepared-for-landing compared to say #47731 , and therefore we may not want to include it in the rollup... 

(Of course, we can also just see if bors rejects #47355...)

**Comment by kennytm** [comment]
Failed on i686, legit...

```
[00:03:19]    Compiling libc v0.2.36
[00:03:20] error: unexpected end of macro invocation
[00:03:20]     --> src/libcore/num/mod.rs:1380:42
[00:03:20]      |
[00:03:20] 1380 |     int_impl! { isize, i32, u32, 32, "", "" }
[00:03:20]      |                                          ^^
[00:03:20] 
[00:03:20]    Compiling cfg-if v0.1.2
[00:03:20] error: aborting due to previous error
[00:03:20] 
[00:03:21] error: Could not compile `core`.
```

**Comment by GuillaumeGomez** [comment]
Then let's close it.

**Pull request closed without merging**
