### PR TITLE
Stabilize `const_constructor`

### LINKED ISSUE #61456: Tracking issue for treating tuple struct and variant constructors as const fn
The `const_constructor` feature allows calling any expression of a tuple-like constructors can be called in a `const fn`:

```rust
const fn make_options() {
    Some(0); // OK on stable
    (Option::Some)(1); // OK on stable
    let f = Option::Some;
    f(2); // Requires feature gate
}
```

cc @oli-obk @Centril

### LINKED ISSUE #64247: Self::EnumVariant not considered const fn
When using `Self` to create an enum variant in Rust 1.37+, we get an error:
```
const VAL: Self = Self::X(42);
```
results in:
```
error: `Foo::X` is not yet stable as a const fn
```
but if the enum is constructed explicitly, the compilation succeeds:
```
const VAL: Self = Foo::X(42)
```
Looking at https://github.com/rust-lang/rust/issues/53555, it looks like `Self::EnumVariant` should be considered a `const fn` with `min_const_fn`.

Playground links for both variants: [error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fd8c5e4f6965e6cccb7eacdc997ed68c), [no-error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=eb0759e45721d979411af3e9228fd73b)

### PR DESCRIPTION
**Pull request by matthewjasper**
# Stabilization proposal

I propose that we stabilize `#![feature(const_constructor)]`.

Tracking issue: https://github.com/rust-lang/rust/issues/61456
Version target: 1.40 (2019-11-05 => beta, 2019-12-19 => stable).

### User guide

Tuple struct and tuple variant constructors are now considered to be constant functions. As such a call expression where the callee has a tuple struct or variant constructor "function item" type can be called:

```rust
const fn make_options() {
    // These already work because they are special cased:
    Some(0);
    (Option::Some)(1);
    // These also work now:
    let f = Option::Some;
    f(2);
    {Option::Some}(3);
    <Option<_>>::Some(5);
}
```

### Motivation

Consistency with other `const fn`. Consistency between syntactic path forms.

This should also ensure that constructors implement `const Fn` traits and can be coerced to `const fn` function pointers, if they are introduced.

## Tests

* [ui/consts/const_constructor/const-construct-call.rs](https://github.com/rust-lang/rust/blob/0d75ab2293a106eb674ac01860910cfc1580837e/src/test/ui/consts/const_constructor/const-construct-call.rs) - Tests various syntactic forms, use in both `const fn` and `const` items, and constructors in both the current and extern crates.
* [ui/consts/const_constructor/const_constructor_qpath.rs](https://github.com/rust-lang/rust/blob/1850dfcdabf8258a1f023f26c2c59e96b869dd95/src/test/ui/consts/const_constructor/const_constructor_qpath.rs) - Tests that type qualified paths to enum variants are also considered to be `const fn`.(#64247)

r? @oli-obk 

Closes #61456
Closes  #64247

### CODE REVIEW

**Comment by Centril** [comment]
Thanks for the report!
I also propose that we do indeed stabilize `const_constructor`.

@rfcbot merge

----------------------

r? @Centril r=me once FCP completes.

**Comment by pnkfelix** [comment]
as described, this seems fine to me.

I would like to note that another case where const constructors arise is in the context of patterns, e.g.:

```rust
#[derive(PartialEq, Eq)]
struct Hi(i32);

const fn hi() -> Hi { Hi(10) }
const C: Hi = hi();

fn main() {
    match Hi(10) {
        self::C => println!("matched"),
        _ => println!("other"),
    }
}
```

But as far as I can tell, the change being suggested here does not introduce any interesting changes to our behavior for such cases.

**Comment by pnkfelix** [comment]
@rfcbot reviewed

**Comment by jadbox** [comment]
Does this improve performance at all when calling these constructors or no?

**Comment by matthewjasper** [comment]
No, this is just fixing inconsistent behaviour.

**Pull request merged**
