### PR TITLE
Fix mir-cfg dumps

### LINKED ISSUE #81918: "do not use `optimized_mir` for constants" panic when generating MIR cfg
The working example in #72956 builds fine, but if I add `-Zunpretty=mir-cfg` it panics. Repro:

```rust
use std::ops::Index;

struct Banana(*mut ());
unsafe impl Send for Banana {}

impl Banana {
    fn new() -> &'static mut Banana {
        static mut BANANA: Banana = Banana(std::ptr::null_mut());
        unsafe { &mut BANANA }
    }
}

struct Peach<'a>(&'a mut Banana);

impl<'a> std::ops::Index<usize> for Peach<'a> {
    type Output = ();
    fn index(&self, idx: usize) -> &() {
        &()
    }
}

async fn baz(v: &()) {}

async fn bar() -> () {
    let peach = Peach(Banana::new());
    let r: &() = &*std::ops::Index::index(&peach, 0);
    baz(r).await;
    peach.index(0);
}

fn assert_send<T: Send>(_: T) {}

pub fn main() {
    assert_send(bar())
}
```

It builds fine:

```
$ rustc +stage1 test_works.rs --edition=2018
warning: unused variable: `v`
  --> test_works.rs:22:14
   |
22 | async fn baz(v: &()) {}
   |              ^ help: if this is intentional, prefix it with an underscore: `_v`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `idx`
  --> test_works.rs:17:21
   |
17 |     fn index(&self, idx: usize) -> &() {
   |                     ^^^ help: if this is intentional, prefix it with an underscore: `_idx`

warning: 2 warnings emitted
```

Panics with `-Zunpretty=mir-cfg`:

```
$ rustc +stage1 test_works.rs --edition=2018 -Zunpretty=mir-cfg
warning: unused variable: `v`
  --> test_works.rs:22:14
   |
22 | async fn baz(v: &()) {}
   |              ^ help: if this is intentional, prefix it with an underscore: `_v`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `idx`
  --> test_works.rs:17:21
   |
17 |     fn index(&self, idx: usize) -> &() {
   |                     ^^^ help: if this is intentional, prefix it with an underscore: `_idx`

thread 'rustc' panicked at 'do not use `optimized_mir` for constants: Static(Mut)', compiler/rustc_mir/src/transform/mod.rs:579:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=mir-cfg

query stack during panic:
#0 [optimized_mir] optimizing MIR for `Banana::new::BANANA`
end of query stack
warning: 2 warnings emitted
```

<details>

<summary>Backtrace</summary>

```
   0: rust_begin_unwind
             at /home/omer/rust/rust/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /home/omer/rust/rust/library/std/src/panicking.rs:435:5
   2: rustc_mir::transform::inner_optimized_mir
             at /home/omer/rust/rust/compiler/rustc_mir/src/transform/mod.rs:579:24
   3: rustc_mir::transform::optimized_mir
             at /home/omer/rust/rust/compiler/rustc_mir/src/transform/mod.rs:561:21
   4: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/query/plumbing.rs:377:17
   5: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
             at /home/omer/rust/rust/compiler/rustc_query_system/src/dep_graph/graph.rs:363:14
   6: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::{{closure}}
   7: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/query/plumbing.rs:73:74
   8: stacker::maybe_grow
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.12/src/lib.rs:55:9
   9: rustc_data_structures::stack::ensure_sufficient_stack
             at /home/omer/rust/rust/compiler/rustc_data_structures/src/stack.rs:16:5
  10: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/query/plumbing.rs:73:17
  11: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1712:50
  12: rustc_middle::ty::context::tls::set_tlv
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1696:9
  13: rustc_middle::ty::context::tls::enter_context
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1712:9
  14: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/query/plumbing.rs:72:13
  15: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1756:13
  16: rustc_middle::ty::context::tls::with_context::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1740:40
  17: rustc_middle::ty::context::tls::with_context_opt
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1729:22
  18: rustc_middle::ty::context::tls::with_context
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1740:9
  19: rustc_middle::ty::context::tls::with_related_context
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1753:9
  20: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/query/plumbing.rs:61:9
  21: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:598:9
  22: rustc_query_system::query::plumbing::with_diagnostics
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:303:18
  23: rustc_query_system::query::plumbing::force_query_with_job
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:597:51
  24: rustc_query_system::query::plumbing::try_execute_query
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:427:16
  25: rustc_query_system::query::plumbing::get_query_impl::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:645:23
  26: <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::lookup
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/caches.rs:114:79
  27: rustc_query_system::query::plumbing::try_get_cached
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:380:5
  28: rustc_query_system::query::plumbing::get_query_impl
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:637:5
  29: rustc_query_system::query::plumbing::get_query
             at /home/omer/rust/rust/compiler/rustc_query_system/src/query/plumbing.rs:739:5
  30: rustc_middle::ty::query::TyCtxtAt::optimized_mir
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/query/plumbing.rs:487:17
  31: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::optimized_mir
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/query/plumbing.rs:448:17
  32: rustc_mir::util::graphviz::write_mir_graphviz
             at /home/omer/rust/rust/compiler/rustc_mir/src/util/graphviz.rs:25:21
  33: rustc_driver::pretty::print_with_analysis
             at /home/omer/rust/rust/compiler/rustc_driver/src/pretty.rs:499:26
  34: rustc_driver::pretty::print_after_hir_lowering
             at /home/omer/rust/rust/compiler/rustc_driver/src/pretty.rs:431:22
  35: rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_driver/src/lib.rs:349:25
  36: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/passes.rs:749:42
  37: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1712:50
  38: rustc_middle::ty::context::tls::set_tlv
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1696:9
  39: rustc_middle::ty::context::tls::enter_context
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/context.rs:1712:9
  40: rustc_interface::passes::QueryContext::enter
             at /home/omer/rust/rust/compiler/rustc_interface/src/passes.rs:749:9
  41: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_driver/src/lib.rs:347:21
  42: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /home/omer/rust/rust/compiler/rustc_interface/src/queries.rs:418:19
  43: rustc_driver::run_compiler::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_driver/src/lib.rs:341:22
  44: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/interface.rs:197:13
  45: rustc_span::with_source_map
             at /home/omer/rust/rust/compiler/rustc_span/src/lib.rs:789:5
  46: rustc_interface::interface::create_compiler_and_run
             at /home/omer/rust/rust/compiler/rustc_interface/src/interface.rs:191:5
  47: rustc_interface::interface::run_compiler::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/interface.rs:213:12
  48: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/util.rs:152:13
  49: scoped_tls::ScopedKey<T>::set
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  50: rustc_span::with_session_globals
             at /home/omer/rust/rust/compiler/rustc_span/src/lib.rs:105:5
  51: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/util.rs:150:9
  52: rustc_interface::util::scoped_thread::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/util.rs:125:24
```

</details>

### LINKED ISSUE #82325: ICE: assertion failure with -Zunpretty=mir-cfg
### Code
code from glacier `fixed/79666.rs`
```Rust
#![feature(const_generics)]
#![feature(generic_associated_types)]

trait A {
    type B<const N: usize>;

    fn foo<const N: usize>(&self) -> Self::B<{N}>;
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (9b471a3f5 2021-02-19)
binary: rustc
commit-hash: 9b471a3f5fe57e5c6e08acf665f2094422415a3d
commit-date: 2021-02-19
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### Error output
`rustc ./79666.rs -Zunpretty=mir-cfg`
```
warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> ./79666.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: the feature `generic_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> ./79666.rs:2:12
  |
2 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Some((DefId(0:8 ~ 79666[317d]::A::foo::{constant#0}), DefId(0:5 ~ 79666[317d]::A::B::N)))`,
 right: `None`', compiler/rustc_mir/src/transform/mod.rs:560:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (9b471a3f5 2021-02-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=mir-cfg

query stack during panic:
#0 [optimized_mir] optimizing MIR for `A::foo::{constant#0}`
end of query stack
warning: 2 warnings emitted

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> ./79666.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: the feature `generic_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> ./79666.rs:2:12
  |
2 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Some((DefId(0:8 ~ 79666[317d]::A::foo::{constant#0}), DefId(0:5 ~ 79666[317d]::A::B::N)))`,
 right: `None`', compiler/rustc_mir/src/transform/mod.rs:560:5
stack backtrace:
   0:     0x7f1178f35ab0 - std::backtrace_rs::backtrace::libunwind::trace::hb4de9797f80b7b8c
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f1178f35ab0 - std::backtrace_rs::backtrace::trace_unsynchronized::h59566d0bd20efff7
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1178f35ab0 - std::sys_common::backtrace::_print_fmt::hcfa5ce6be50275d4
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f1178f35ab0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd8c307a38b9bab04
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f1178fa6e6c - core::fmt::write::h3868db8542c90941
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/fmt/mod.rs:1092:17
   5:     0x7f1178f28992 - std::io::Write::write_fmt::hab90295d5a0f197d
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/io/mod.rs:1568:15
   6:     0x7f1178f399a5 - std::sys_common::backtrace::_print::h19224910b8700cf1
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f1178f399a5 - std::sys_common::backtrace::print::h25dedfa68c5fb84a
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f1178f399a5 - std::panicking::default_hook::{{closure}}::h12c5765653a72a42
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:208:50
   9:     0x7f1178f39453 - std::panicking::default_hook::he65cee71c4209f0c
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:225:9
  10:     0x7f117979808b - rustc_driver::report_ice::h56d5f6e6a9fb9d03
  11:     0x7f1178f3a2a6 - std::panicking::rust_panic_with_hook::h01a674d863fe0d8a
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:595:17
  12:     0x7f1178f39dc7 - std::panicking::begin_panic_handler::{{closure}}::h9b9fecf185178864
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:497:13
  13:     0x7f1178f35f4c - std::sys_common::backtrace::__rust_end_short_backtrace::h57be46a42dc7f24b
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f1178f39d29 - rust_begin_unwind
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:493:5
  15:     0x7f1178fa3491 - core::panicking::panic_fmt::h20225113c4a2f8fd
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/panicking.rs:92:14
  16:     0x7f117c15bf05 - rustc_mir::transform::optimized_mir::h245976003198d078
  17:     0x7f117975d5a3 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute::h962929d1c2186a42
  18:     0x7f1179790754 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h987bcc4d742b6eab
  19:     0x7f11797919ec - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h640404db930a6fbb
  20:     0x7f11797b5274 - rustc_data_structures::stack::ensure_sufficient_stack::hd389d807f70b11da
  21:     0x7f117975fa55 - rustc_query_system::query::plumbing::force_query_with_job::h4d36fcda7c0d6736
  22:     0x7f117975f060 - rustc_query_system::query::plumbing::get_query_impl::hff20e28a826798af
  23:     0x7f1179761ab1 - rustc_query_system::query::plumbing::get_query::h5f686cd74df0b95e
  24:     0x7f11797aa9a2 - rustc_mir::util::graphviz::write_mir_graphviz::he12cbf8a95c30fe6
  25:     0x7f117974d5e4 - rustc_driver::pretty::print_after_hir_lowering::h102b65afa3784540
  26:     0x7f117979f63e - rustc_interface::passes::QueryContext::enter::he206c0d61f6fb2e9
  27:     0x7f117bb0a6d7 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hae97633c8f5175d4
  28:     0x7f117bb02e11 - rustc_span::with_source_map::hd16d211d24c668a9
  29:     0x7f117bb09c62 - scoped_tls::ScopedKey<T>::set::h08e96579ac07fec5
  30:     0x7f117bb0b448 - std::sys_common::backtrace::__rust_begin_short_backtrace::h84dc4b3263d56f8c
  31:     0x7f117bae9aba - core::ops::function::FnOnce::call_once{{vtable.shim}}::h209d27a00dc0b7e3
  32:     0x7f1178f4affa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h321523073ee11258
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
  33:     0x7f1178f4affa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf0e85e12c83b99b3
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
  34:     0x7f1178f4affa - std::sys::unix::thread::Thread::new::thread_start::hba22c7961aa0e2f8
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys/unix/thread.rs:71:17
  35:     0x7f1178e50299 - start_thread
  36:     0x7f1178d65153 - clone
  37:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (9b471a3f5 2021-02-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=mir-cfg

query stack during panic:
#0 [optimized_mir] optimizing MIR for `A::foo::{constant#0}`
end of query stack
warning: 2 warnings emitted

```

</p>
</details>

### LINKED ISSUE #82326: ICE: do not use `optimized_mir` for constants: Const   with -Zunpretty=mir-cfg
code from glacier  fixed/21073.rs
### Code

```Rust
const TAG: &'static [u8] = b"ABCD";

fn main() {
    match &[][..] {
        TAG => println!("Yes."),
        _ => println!("No."),
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (9b471a3f5 2021-02-19)
binary: rustc
commit-hash: 9b471a3f5fe57e5c6e08acf665f2094422415a3d
commit-date: 2021-02-19
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### Error output
`rustc ./21073.rs -Zunpretty=mir-cfg `
```
thread 'rustc' panicked at 'do not use `optimized_mir` for constants: Const', compiler/rustc_mir/src/transform/mod.rs:579:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (9b471a3f5 2021-02-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=mir-cfg

query stack during panic:
#0 [optimized_mir] optimizing MIR for `TAG`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'do not use `optimized_mir` for constants: Const', compiler/rustc_mir/src/transform/mod.rs:579:24
stack backtrace:
   0:     0x7fb061c89ab0 - std::backtrace_rs::backtrace::libunwind::trace::hb4de9797f80b7b8c
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fb061c89ab0 - std::backtrace_rs::backtrace::trace_unsynchronized::h59566d0bd20efff7
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb061c89ab0 - std::sys_common::backtrace::_print_fmt::hcfa5ce6be50275d4
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fb061c89ab0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd8c307a38b9bab04
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fb061cfae6c - core::fmt::write::h3868db8542c90941
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/fmt/mod.rs:1092:17
   5:     0x7fb061c7c992 - std::io::Write::write_fmt::hab90295d5a0f197d
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/io/mod.rs:1568:15
   6:     0x7fb061c8d9a5 - std::sys_common::backtrace::_print::h19224910b8700cf1
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fb061c8d9a5 - std::sys_common::backtrace::print::h25dedfa68c5fb84a
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fb061c8d9a5 - std::panicking::default_hook::{{closure}}::h12c5765653a72a42
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:208:50
   9:     0x7fb061c8d453 - std::panicking::default_hook::he65cee71c4209f0c
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:225:9
  10:     0x7fb0624ec08b - rustc_driver::report_ice::h56d5f6e6a9fb9d03
  11:     0x7fb061c8e2a6 - std::panicking::rust_panic_with_hook::h01a674d863fe0d8a
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:595:17
  12:     0x7fb061c8ddc7 - std::panicking::begin_panic_handler::{{closure}}::h9b9fecf185178864
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:497:13
  13:     0x7fb061c89f4c - std::sys_common::backtrace::__rust_end_short_backtrace::h57be46a42dc7f24b
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7fb061c8dd29 - rust_begin_unwind
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:493:5
  15:     0x7fb061c8dcdb - std::panicking::begin_panic_fmt::h12277576db89392f
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:435:5
  16:     0x7fb064eafe45 - rustc_mir::transform::optimized_mir::h245976003198d078
  17:     0x7fb0624b15a3 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute::h962929d1c2186a42
  18:     0x7fb0624e4754 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h987bcc4d742b6eab
  19:     0x7fb0624e59ec - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h640404db930a6fbb
  20:     0x7fb062509274 - rustc_data_structures::stack::ensure_sufficient_stack::hd389d807f70b11da
  21:     0x7fb0624b3a55 - rustc_query_system::query::plumbing::force_query_with_job::h4d36fcda7c0d6736
  22:     0x7fb0624b3060 - rustc_query_system::query::plumbing::get_query_impl::hff20e28a826798af
  23:     0x7fb0624b5ab1 - rustc_query_system::query::plumbing::get_query::h5f686cd74df0b95e
  24:     0x7fb0624fe9a2 - rustc_mir::util::graphviz::write_mir_graphviz::he12cbf8a95c30fe6
  25:     0x7fb0624a15e4 - rustc_driver::pretty::print_after_hir_lowering::h102b65afa3784540
  26:     0x7fb0624f363e - rustc_interface::passes::QueryContext::enter::he206c0d61f6fb2e9
  27:     0x7fb06485e6d7 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hae97633c8f5175d4
  28:     0x7fb064856e11 - rustc_span::with_source_map::hd16d211d24c668a9
  29:     0x7fb06485dc62 - scoped_tls::ScopedKey<T>::set::h08e96579ac07fec5
  30:     0x7fb06485f448 - std::sys_common::backtrace::__rust_begin_short_backtrace::h84dc4b3263d56f8c
  31:     0x7fb06483daba - core::ops::function::FnOnce::call_once{{vtable.shim}}::h209d27a00dc0b7e3
  32:     0x7fb061c9effa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h321523073ee11258
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
  33:     0x7fb061c9effa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf0e85e12c83b99b3
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
  34:     0x7fb061c9effa - std::sys::unix::thread::Thread::new::thread_start::hba22c7961aa0e2f8
                               at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys/unix/thread.rs:71:17
  35:     0x7fb061ba4299 - start_thread
  36:     0x7fb061ab9153 - clone
  37:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (9b471a3f5 2021-02-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=mir-cfg

query stack during panic:
#0 [optimized_mir] optimizing MIR for `TAG`
end of query stack
```

</p>
</details>

### PR DESCRIPTION
**Pull request by osa1**
Fixes #81918
Fixes #82326 (duplicate)
Fixes #82325

---

r? @oli-obk

### CODE REVIEW

**Comment by osa1** [comment]
Should I add a test to this? I have a minimal repro:

```rust
const TAG: &'static str = "ABCD";

fn main() {
    if TAG == "" {}
}
```

but I couldn't find a way to accept a test based on rustc exit code (without comparing stdout contents), and I'm not sure if we want to check dot outputs.

**Comment by oli-obk** [comment]
> but I couldn't find a way to accept a test based on rustc exit code (without comparing stdout contents), and I'm not sure if we want to check dot outputs.

we already have pretty printing tests in https://github.com/rust-lang/rust/tree/master/src/test/pretty I think you should be able to just add it there

**Comment by osa1** [comment]
@oli-obk I couldn't put this in `test/pretty` because outputs of tests in that directory is passed to the compiler again, to check the the printer prints valid Rust. I realized that stdouts of tests in `test/mir-opt` are not checked so I put the test there. Let me know if you want me to move it elsewhere.

**Comment by oli-obk** [comment]
Heh that's a neat trick. Please leave the explanation on why it is here and not in the ui test suite in a comment in that file, otherwise someone will be confused by that test in the future

**Comment by osa1** [comment]
Sigh.. it seems like you can't easily ignore stdout contents of a test.. Putting the test in `mir-opt` just to ignore stdout seemed hacky so I moved the test once again, and committed stdout contents. Ping @oli-obk

**Comment by osa1** [comment]
@oli-obk nvm, figured it out. Could you review?

**Pull request merged**
