### PR TITLE
Stabilize `-Zincremental` as `-Cincremental`

### PR DESCRIPTION
**Pull request by nikomatsakis**
The `-Zincremental` option remains temporarily, but we issue a warning.

If you use `-Cincremental` on stable, it has no effect.

r? @michaelwoerister 
cc @alexcrichton @rust-lang/compiler

### CODE REVIEW

**Comment by alexcrichton** [comment]
To me stabilizing the flag but warning about it sorta defeats the purpose to me as it's still not intended for stable use. Perhaps we could consider accepting `-C incremental` but just ignoring it on stable/beta while it's still in development?

**Comment by nagisa** [comment]
What’s the point here?

**Comment by xen0n** [comment]
@nagisa It can only be pushing people early towards adoption of the option in its final form, as judging from the changes there's zero other things happening there. This way maybe tool authors wouldn't have to rush updating their packages and race with all kinds of packaging and release schedules once the option is actually stabilized.

**Comment by michaelwoerister** [comment]
Yes, I think the point is mostly to stabilize the interface before it gets adopted more widely in build scripts and so that we don't get into the situation where some versions of Cargo support incr. comp. but only for certain out-dated versions of the compiler.

I'm undecided about the warning here but as a default I prefer a warning over not being informed at all.

**Comment by nikomatsakis** [comment]
@alexcrichton 

> To me stabilizing the flag but warning about it sorta defeats the purpose to me as it's still not intended for stable use. Perhaps we could consider accepting -C incremental but just ignoring it on stable/beta while it's still in development?

Hmm, I guess it depends on the overall "rollout" plan. This is something that we talked about some -- and I also talked about with @michaelwoerister -- but I realize hasn't been written down anywhere.

The way I understood the plan was that we would begin with an "opt-in" beta phase until we are more confident in the correctness, at minimum. The idea is then that you would use incremental, you would switch to a nightly build and do `CARGO_INCREMENTAL=1`. To this end, I had planned to land a PR that makes `cargo build` supply `-Cincremental` when you are doing a debug build and the `CARGO_INCREMENTAL` environment variable is set. In this case, it seems good to me that if you do `CARGO_INCREMENTAL=1` but you are using a master compiler, you get a warning!

After we are confident in the correctness, we would then proceed to make incremental the default. At that point, if cargo is supplying `-Cincremental` all the time *by default* I agree it does not make sense to issue a warning.

We had also talked about holding off on making a big fanfare until we are satisfied not only with the *correctness* of incremental but also on the improvements to compile time. Right now, it tends to make things faster, but it's not the *transformative* experience I hope we will ultimately achieve. I think the two big blockers to that are making type-checking incremental and improving the cross-crate tracking. 

I still think it makes sense to hold off on "declaring victory" (e.g., with a big blog post and bonanza blitz) until those performance goals are met. But, if we are satisfied with the stability, perhaps we should just enable it on stable at the same time as we enable it by default in cargo. After all, it's certainly an *improvement*.

Anyway, we can take it step by step: there's some chance after all that we will be able to incrementalize type-checking and so forth relatively quickly. But the starting point is the "opt-in" bulds, and for that purpose it still seems to me that a warning makes sense...?

**Comment by nikomatsakis** [comment]
After some discussion on IRC we decided to close this PR for now. I will just add code to cargo to supply `-Zincremental` if you opt in. This should only be done on nightly, since it is supplying a (unstable) `-Z` flag (presumably it will error out or whatever on stable). This will allow us to gain some experience using the flag before we stabilize.

At the time when we are ready to enable it by default (at least on nightly), we will convert to `-Cincremental`. At that time, we may still hold off enabling it *by default* on stable until our performance goals are met. However, once it is a `-C` flag, it will be usable on stable regardless (even if opt-in is required).

**Pull request closed without merging**
