### PR TITLE
[WIP] Reduce HTML output in rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
```bash
 > du -sh normal/std/index.html
 60K	normal/std/index.html
 > du -sh build/x86_64-apple-darwin/doc/std/index.html
 36K	build/x86_64-apple-darwin/doc/std/index.html
```

r? @rust-lang/docs

### CODE REVIEW

**Comment by frewsxcv** [comment]
For reference https://github.com/GuillaumeGomez/minifier-rs

**Comment by killercup** [comment]
@GuillaumeGomez I'm pretty surprised to see your minifier drop so many closing tags. Especially the rules around omitting `</li>` seem to be error-prone to me (but I haven't dealt with stuff like that in quite a while). Two more things:

1. Compare the gzip'd sizes as basically all HTTP traffic is compressed (as are blobs stored in a git repo IIRC)
2. Have I linked to http://stackoverflow.com/a/1732454/1254484 recently? :)

**Comment by GuillaumeGomez** [comment]
> I'm pretty surprised to see your minifier drop so many closing tags. Especially the rules around omitting </li> seem to be error-prone to me (but I haven't dealt with stuff like that in quite a while).

`li`, `tr`, `td` and equivalent can be unclosed considering they can't be directly in each others.

> Compare the gzip'd sizes as basically all HTTP traffic is compressed (as are blobs stored in a git repo IIRC)

Hum, good point.

> Have I linked to http://stackoverflow.com/a/1732454/1254484 recently? :)

The compression isn't "hardcore" so it leaves place for improvements. Using html5ever for this could be worth it, to be tested. This PR is a work in progress after all and isn't to be merged right now.

**Comment by alexcrichton** [comment]
Note that a tool like this seems like it has a high chance of accidentally introducing regressions, it'd be great if we could add some regression testing as well to this.

**Comment by GuillaumeGomez** [comment]
@alexcrichton: it's not close at all to get merged. For now it was mostly to get some feedbacks. Do you have an idea by any chance on how I could test regressions in here?

**Comment by alexcrichton** [comment]
To start this could use an html parser like html5ever and enusre the document structure doesn't change for standard Rust properties like:

* The book
* Standard library docs
* Popular crates on docs.rs

**Comment by jonathandturner** [comment]
I'm not currently on rustdoc, so assigning to alex

r? @alexcrichton

**Comment by clarcharr** [comment]
It'd be nice if we could do this to rustdoc's CSS as well.

**Comment by GuillaumeGomez** [comment]
@clarcharr: It's scheduled (at least I intend to do it).

**Comment by frewsxcv** [comment]
In my opinion, minimizing HTML and CSS is something that would be cool to do for all pages generated by rustdoc, but it seems the underlying tool has some incubation to so. I have some concerns about some of the strategies it does and the lack of testing. I don't know if this PR is the most effective way to get feedback though

**Comment by GuillaumeGomez** [comment]
Well, at least it opens the debate. I still have a lot to do on the minimizer tool.

**Comment by TimNN** [comment]
@GuillaumeGomez: What's the current status of this PR?

**Comment by GuillaumeGomez** [comment]
Quite busy, I still need to rewrite the HTML minifier (using html5ever). I'll try to get to it in the next weeks or so.

**Comment by alexcrichton** [comment]
Ok I'm going to close this for now to help keep the queue clear, but please of course feel free to resubmit!

**Pull request closed without merging**
