### PR TITLE
Stabilize disable-minification option

### LINKED ISSUE #54819: [rustdoc] stabilise disable-minification option

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #54819.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/rustdoc 

This is effectively a debugging flag, right? Has this flag received any major use? Are there any tests for this flag? (I'm curious how those would look...) Does the Rustdoc Book have any documentation about this flag? (We'll need to move it into the stable section, if so.)

**Comment by GuillaumeGomez** [comment]
Yes, yes (well, for me at least), no (not sure how to test it...), no idea.

**Comment by QuietMisdreavus** [comment]
I don't see anything on https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html about this flag, so i assume that it has no docs. Can you add a section to the "Command-line arguments" page about this flag?

To test, it depends on whether the minification will remove certain whitespace entirely. If so, we can use a regular rustdoc test to ensure that the minified version has some portion of a JS/CSS file with no whitespace in some location, and the non-minified version preserved that whitespace. (It's problematic because apparently `htmldocck.py` collapses whitespace too, so it's hard to check. `>_>`) Alternately, you could do a `run-make` test which runs docs on some sample crate twice, and compares `main.js` in each one to make sure they don't have the same file content.

**Comment by TimNN** [comment]
Ping from triage @GuillaumeGomez: What is the status of this PR?

**Comment by GuillaumeGomez** [comment]
I need to add the documentation.

**Comment by TimNN** [comment]
Ping from triage @GuillaumeGomez: Do you think you'll be able to / have the time to continue working on this PR?

**Comment by GuillaumeGomez** [comment]
Yup yup.

**Comment by TimNN** [comment]
Ping from triage! This PR hasn't made any progress in a while, so I'm closing it for now. Thanks for your contributions and please feel free to re-open in the future.

**Pull request closed without merging**
