### PR TITLE
rustc: Remove local variable IDs from `Export`s

### PR DESCRIPTION
**Pull request by petrochenkov**
Local variables can never be exported.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
LGTM

**Comment by Manishearth** [comment]
The rollup caused an instruction count increase on perf, do you think that's due to this PR? 

https://github.com/rust-lang/rust/pull/88881

https://perf.rust-lang.org/compare.html?start=9ef27bf7dc50a8b51435579b4f2e86f7ee3f7a94&end=c7dbe7a830100c70d59994fd940bf75bb6e39b39

**Comment by petrochenkov** [comment]
It seems unlikely, this PR is a type-level refactoring that shouldn't change anything at runtime.

**Pull request merged**
