### PR TITLE
use diff crate for compile-fail test diagnostics #41474

### LINKED ISSUE #41474: Use `diff` crate while evaluating `compile-fail` tests
Hello,

Currently we're using some internal functionality for comparing `compile-fail` results.

We should be using [diff](https://crates.io/crates/diff) instead.

Thanks @nikomatsakis for suggesting this. 

I'm working on this now.

### PR DESCRIPTION
**Pull request by cengiz-io**
Hello!

This fixes #41474 

We were using a custom implementation to dump the differences between expected and actual outputs of compile-fail tests.

I removed this internal implementation and added `diff` crate as a new dependency to `compile-fail`.

Again, huge thanks to @nikomatsakis for guiding.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Could we see a before/after comparison of a failure? Unless they're the same.

**Comment by nikomatsakis** [comment]
The code looks good to me. @cengizIO, do you have a handy "before/after" comparison to show @Mark-Simulacrum? 

@Mark-Simulacrum -- for context, this only affects the diffs that print when a ui test fails. The older code was using a "hand-rolled" diff algorithm that really didn't cope well with new lines being inserted etc. This code now uses the standard "diff" algorithm, so I would expect the printouts to look *much* easier to read.

**Comment by cengizIO** [comment]
Hello @Mark-Simulacrum!

Thanks for keeping an eye on the issue.

As @nikomatsakis mentioned, this only changes the way we `println!` the difference between expected and actual compilation fail outputs.

Is this sample good enough for you?

https://github.com/rust-lang/rust/issues/41474#issuecomment-297822568

Please let me know if it's not. I'd be happy to provide full samples for each case.

**Comment by Mark-Simulacrum** [comment]
Yep, that's good enough for me. Just wanted to see an overall view. Thanks!

**Pull request merged**
