### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
11 commits in 1aa9df1a5be205cce621f0bc0ea6062a5e22a98c..1a2666ddd14cf0a255d4ddb61c63531c259a7b39
2023-12-12 14:52:31 +0000 to 2023-12-17 17:53:53 +0000
- chore: downgrade to openssl v1.1.1 (rust-lang/cargo#13179)
- docs(home): prepare the changelog for 0.5.9 (rust-lang/cargo#13177)
- refactor: Pull name validation into `util_schemas` (rust-lang/cargo#13166)
- chore(deps): bump zerocopy from 0.7.29 to 0.7.31 (rust-lang/cargo#13174)
- Replace SHGetFolderPathW with SHGetKnownFolderPath (rust-lang/cargo#13173)
- chore(bump-check): dont check `home` against beta/stable branches (rust-lang/cargo#13167)
- fix: Fill in more empty name holes (rust-lang/cargo#13164)
- Do not allow empty name in package ID spec (rust-lang/cargo#13152)
- chore(deps): update rust crate openssl to 0.10.61 (rust-lang/cargo#13159)
- `all-static` feature should include `vendored-libgit2` (rust-lang/cargo#13134)
- doc/registry-web-api: Adjust success response code documentation (rust-lang/cargo#13160)

r? ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
Looks like some classic mysterious network errors, so let's see if we can't fix it by just saying "again!"

@bors retry

**Comment by workingjubilee** [comment]
An actual problem maybe?
Then again, it seems the problem is OpenSSL.
Then again, OpenSSL is...
Anyways, it doesn't look like something one can just retry around, but maybe I am wrong.

**Comment by weihanglo** [comment]
This PR contains OpenSSL bump from v1.1.1 to v3.2. Something misconfigured in either upstream OpenSSL or OpenSSL Rust bindings.

However we've got two different errors from different platform, which confused me…

On `i686-unknown-linux-gnu`, some Perl modules cannot be found (myabe [this](https://github.com/openssl/openssl/issues/19740)?):

<details><summary>click to see logs</summary>
<p>

```
   error: failed to run custom build command for `openssl-sys v0.9.97`
  
  Caused by:
    process didn't exit successfully: `/checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/release/build/openssl-sys-5ea5863087a99ce1/build-script-main` (exit status: 101)
    --- stdout
    cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
    I686_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
    cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
    OPENSSL_NO_VENDOR unset
    cargo:rerun-if-env-changed=CC_i686-unknown-linux-gnu
    CC_i686-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=CC_i686_unknown_linux_gnu
    CC_i686_unknown_linux_gnu = Some("sccache clang")
    cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("false")
    cargo:rerun-if-env-changed=CFLAGS_i686-unknown-linux-gnu
    CFLAGS_i686-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=CFLAGS_i686_unknown_linux_gnu
    CFLAGS_i686_unknown_linux_gnu = Some("-ffunction-sections -fdata-sections -fPIC --target=i686-unknown-linux-gnu -mstackrealign -fdebug-prefix-map=/checkout=/rustc/06d9041d06fa9fb964f5de906cf0705874518d90")
    cargo:rerun-if-env-changed=AR_i686-unknown-linux-gnu
    AR_i686-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=AR_i686_unknown_linux_gnu
    AR_i686_unknown_linux_gnu = Some("ar")
    cargo:rerun-if-env-changed=ARFLAGS_i686-unknown-linux-gnu
    ARFLAGS_i686-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=ARFLAGS_i686_unknown_linux_gnu
    ARFLAGS_i686_unknown_linux_gnu = None
    cargo:rerun-if-env-changed=HOST_ARFLAGS
    HOST_ARFLAGS = None
    cargo:rerun-if-env-changed=ARFLAGS
    ARFLAGS = None
    cargo:rerun-if-env-changed=RANLIB_i686-unknown-linux-gnu
    RANLIB_i686-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=RANLIB_i686_unknown_linux_gnu
    RANLIB_i686_unknown_linux_gnu = Some("ar s")
    cargo:rerun-if-env-changed=RANLIBFLAGS_i686-unknown-linux-gnu
    RANLIBFLAGS_i686-unknown-linux-gnu = None
    cargo:rerun-if-env-changed=RANLIBFLAGS_i686_unknown_linux_gnu
    RANLIBFLAGS_i686_unknown_linux_gnu = None
    cargo:rerun-if-env-changed=HOST_RANLIBFLAGS
    HOST_RANLIBFLAGS = None
    cargo:rerun-if-env-changed=RANLIBFLAGS
    RANLIBFLAGS = None
    running cd "/checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="clang" RANLIB="ar s" "perl" "./Configure" "--prefix=/checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-elf" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=i686-unknown-linux-gnu" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=i686-unknown-linux-gnu" "-mstackrealign" "-fdebug-prefix-map=/checkout=/rustc/06d9041d06fa9fb964f5de906cf0705874518d90"
  
    --- stderr
    Can't locate IPC/Cmd.pm in @INC (@INC contains: /checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/build/src/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/build/src/external/perl/Text-Template-1.56/lib) at /checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/build/src/util/perl/OpenSSL/config.pm line 19.
    BEGIN failed--compilation aborted at /checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/build/src/util/perl/OpenSSL/config.pm line 19.
    Compilation failed in require at ./Configure line 23.
    BEGIN failed--compilation aborted at ./Configure line 23.
    thread 'main' panicked at /rust/deps/openssl-src-300.2.1+3.2.0/src/lib.rs:611:9:
  
  
  
    Error configuring OpenSSL build:
        Command: cd "/checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="clang" RANLIB="ar s" "perl" "./Configure" "--prefix=/checkout/obj/build/i686-unknown-linux-gnu/stage1-tools/i686-unknown-linux-gnu/release/build/openssl-sys-bae7f78768aa2d09/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-elf" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=i686-unknown-linux-gnu" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=i686-unknown-linux-gnu" "-mstackrealign" "-fdebug-prefix-map=/checkout=/rustc/06d9041d06fa9fb964f5de906cf0705874518d90"
        Exit status: exit status: 2
```

</p>
</details> 

While on `riscv64gc-unknown-linux-gnu`, some symbols for riscv are not found ([relevant issue](https://github.com/openssl/openssl/issues/22871)?):

<details><summary>click to see logs</summary>

```
    --- stderr
    providers/implementations/ciphers/cipher_aes_ccm_hw_rv64i.inc: In function 'ccm_rv64i_zknd_zkne_initkey':
    providers/implementations/ciphers/cipher_aes_ccm_hw_rv64i.inc:20:27: warning: implicit declaration of function 'rv64i_zkne_set_encrypt_key'; did you mean 'AES_set_encrypt_key'? [-Wimplicit-function-declaration]
         AES_HW_CCM_SET_KEY_FN(rv64i_zkne_set_encrypt_key, rv64i_zkne_encrypt,
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
    providers/implementations/ciphers/cipher_aes_ccm_hw.c:21:5: note: in definition of macro 'AES_HW_CCM_SET_KEY_FN'
         fn_set_enc_key(key, keylen * 8, &actx->ccm.ks.ks);                         \
         ^~~~~~~~~~~~~~
    providers/implementations/ciphers/cipher_aes_ccm_hw_rv64i.inc:20:55: error: 'rv64i_zkne_encrypt' undeclared (first use in this function); did you mean 'AES_bi_ige_encrypt'?
         AES_HW_CCM_SET_KEY_FN(rv64i_zkne_set_encrypt_key, rv64i_zkne_encrypt,
                                                           ^~~~~~~~~~~~~~~~~~
    providers/implementations/ciphers/cipher_aes_ccm_hw.c:23:36: note: in definition of macro 'AES_HW_CCM_SET_KEY_FN'
                            (block128_f)fn_blk);                                    \
                                        ^~~~~~
    providers/implementations/ciphers/cipher_aes_ccm_hw_rv64i.inc:20:55: note: each undeclared identifier is reported only once for each function it appears in
         AES_HW_CCM_SET_KEY_FN(rv64i_zkne_set_encrypt_key, rv64i_zkne_encrypt,
                                                           ^~~~~~~~~~~~~~~~~~
    providers/implementations/ciphers/cipher_aes_ccm_hw.c:23:36: note: in definition of macro 'AES_HW_CCM_SET_KEY_FN'
                            (block128_f)fn_blk);                                    \
                                        ^~~~~~
    In file included from providers/implementations/ciphers/cipher_aes_gcm.h:12,
                     from providers/implementations/ciphers/cipher_aes_gcm_hw.c:18:
    providers/implementations/ciphers/cipher_aes_gcm_hw_rv64i.inc: In function 'rv64i_zknd_zkne_gcm_initkey':
    providers/implementations/ciphers/cipher_aes_gcm_hw_rv64i.inc:20:31: warning: implicit declaration of function 'rv64i_zkne_set_encrypt_key'; did you mean 'AES_set_encrypt_key'? [-Wimplicit-function-declaration]
         GCM_HW_SET_KEY_CTR_FN(ks, rv64i_zkne_set_encrypt_key, rv64i_zkne_encrypt,
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
    providers/implementations/include/prov/ciphercommon_gcm.h:128:5: note: in definition of macro 'GCM_HW_SET_KEY_CTR_FN'
         fn_set_enc_key(key, keylen * 8, ks);                                       \
         ^~~~~~~~~~~~~~
    In file included from providers/implementations/ciphers/cipher_aes_ccm_hw.c:65:
    providers/implementations/ciphers/cipher_aes_ccm_hw_rv64i.inc: In function 'ossl_prov_aes_hw_ccm':
    providers/implementations/ciphers/cipher_aes_ccm_hw_rv64i.inc:36:12: warning: implicit declaration of function 'RISCV_HAS_ZKND_AND_ZKNE' [-Wimplicit-function-declaration]
         return RISCV_HAS_ZKND_AND_ZKNE() ? &rv64i_zknd_zkne_ccm : &aes_ccm;
                ^~~~~~~~~~~~~~~~~~~~~~~
    make[1]: *** [Makefile:12030: providers/implementations/ciphers/libdefault-lib-cipher_aes_ccm_hw.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    providers/implementations/ciphers/cipher_aes_gcm_hw_rv64i.inc:20:59: error: 'rv64i_zkne_encrypt' undeclared (first use in this function); did you mean 'AES_bi_ige_encrypt'?
         GCM_HW_SET_KEY_CTR_FN(ks, rv64i_zkne_set_encrypt_key, rv64i_zkne_encrypt,
                                                               ^~~~~~~~~~~~~~~~~~
    providers/implementations/include/prov/ciphercommon_gcm.h:129:51: note: in definition of macro 'GCM_HW_SET_KEY_CTR_FN'
         CRYPTO_gcm128_init(&ctx->gcm, ks, (block128_f)fn_block);                   \
                                                       ^~~~~~~~
    providers/implementations/ciphers/cipher_aes_gcm_hw_rv64i.inc:20:59: note: each undeclared identifier is reported only once for each function it appears in
         GCM_HW_SET_KEY_CTR_FN(ks, rv64i_zkne_set_encrypt_key, rv64i_zkne_encrypt,
                                                               ^~~~~~~~~~~~~~~~~~
    providers/implementations/include/prov/ciphercommon_gcm.h:129:51: note: in definition of macro 'GCM_HW_SET_KEY_CTR_FN'
         CRYPTO_gcm128_init(&ctx->gcm, ks, (block128_f)fn_block);                   \
                                                       ^~~~~~~~
    In file included from providers/implementations/ciphers/cipher_aes_gcm_hw.c:146:
    providers/implementations/ciphers/cipher_aes_gcm_hw_rv64i.inc: In function 'ossl_prov_aes_hw_gcm':
    providers/implementations/ciphers/cipher_aes_gcm_hw_rv64i.inc:36:9: warning: implicit declaration of function 'RISCV_HAS_ZKND_AND_ZKNE' [-Wimplicit-function-declaration]
         if (RISCV_HAS_ZKND_AND_ZKNE())
             ^~~~~~~~~~~~~~~~~~~~~~~
    make[1]: *** [Makefile:12046: providers/implementations/ciphers/libdefault-lib-cipher_aes_gcm_hw.o] Error 1
    In file included from providers/implementations/ciphers/cipher_aes_hw.c:146:
    providers/implementations/ciphers/cipher_aes_hw_rv64i.inc: In function 'cipher_hw_rv64i_zknd_zkne_initkey':
    providers/implementations/ciphers/cipher_aes_hw_rv64i.inc:34:15: warning: implicit declaration of function 'rv64i_zknd_set_decrypt_key'; did you mean 'AES_set_decrypt_key'? [-Wimplicit-function-declaration]
             ret = rv64i_zknd_set_decrypt_key(key, keylen * 8, ks);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   AES_set_decrypt_key
    providers/implementations/ciphers/cipher_aes_hw_rv64i.inc:35:35: error: 'rv64i_zknd_decrypt' undeclared (first use in this function); did you mean 'EVP_PKEY_decrypt'?
             dat->block = (block128_f) rv64i_zknd_decrypt;
                                       ^~~~~~~~~~~~~~~~~~
                                       EVP_PKEY_decrypt
    providers/implementations/ciphers/cipher_aes_hw_rv64i.inc:35:35: note: each undeclared identifier is reported only once for each function it appears in
    providers/implementations/ciphers/cipher_aes_hw_rv64i.inc:38:15: warning: implicit declaration of function 'rv64i_zkne_set_encrypt_key'; did you mean 'AES_set_encrypt_key'? [-Wimplicit-function-declaration]
             ret = rv64i_zkne_set_encrypt_key(key, keylen * 8, ks);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   AES_set_encrypt_key
    providers/implementations/ciphers/cipher_aes_hw_rv64i.inc:39:35: error: 'rv64i_zkne_encrypt' undeclared (first use in this function); did you mean 'AES_bi_ige_encrypt'?
             dat->block = (block128_f) rv64i_zkne_encrypt;
                                       ^~~~~~~~~~~~~~~~~~
                                       AES_bi_ige_encrypt
    providers/implementations/ciphers/cipher_aes_hw.c: In function 'ossl_prov_cipher_hw_aes_cbc':
    providers/implementations/ciphers/cipher_aes_hw_rv64i.inc:58:5: warning: implicit declaration of function 'RISCV_HAS_ZKND_AND_ZKNE' [-Wimplicit-function-declaration]
     if (RISCV_HAS_ZKND_AND_ZKNE())                                                 \
         ^~~~~~~~~~~~~~~~~~~~~~~
    providers/implementations/ciphers/cipher_aes_hw.c:135:5: note: in expansion of macro 'PROV_CIPHER_HW_select'
         PROV_CIPHER_HW_select(mode)                                                \
         ^~~~~~~~~~~~~~~~~~~~~
    providers/implementations/ciphers/cipher_aes_hw.c:155:1: note: in expansion of macro 'PROV_CIPHER_HW_aes_mode'
     PROV_CIPHER_HW_aes_mode(cbc)
     ^~~~~~~~~~~~~~~~~~~~~~~
    make[1]: *** [Makefile:12078: providers/implementations/ciphers/libdefault-lib-cipher_aes_hw.o] Error 1
    make: *** [Makefile:2289: build_libs] Error 2
    thread 'main' panicked at /rust/deps/openssl-src-300.2.1+3.2.0/src/lib.rs:611:9:
  
  
  
    Error building OpenSSL:
        Command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/riscv64gc-unknown-linux-gnu/release/build/openssl-sys-42b93a5d9c219ca4/out/openssl-build/build/src" && MAKEFLAGS="-j --jobserver-fds=8,13 --jobserver-auth=8,13" "make" "build_libs"
        Exit status: exit status: 2
  
  
        
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  [RUSTC-TIMING] gix_odb test:false 8.079
  Build completed unsuccessfully in 0:23:56
  
  
  command did not execute successfully: cd "/checkout" && env -u MAKEFLAGS -u MFLAGS AR_riscv64gc_unknown_linux_gnu="riscv64-unknown-linux-gnu-ar" CARGO_INCREMENTAL="0" CARGO_PROFILE_RELEASE_DEBUG="0" CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS="false" CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS="false" CARGO_PROFILE_RELEASE_STRIP="false" CARGO_TARGET_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools" CARGO_TARGET_RISCV64GC_UNKNOWN_LINUX_GNU_LINKER="riscv64-unknown-linux-gnu-gcc" CC_riscv64gc_unknown_linux_gnu="sccache riscv64-unknown-linux-gnu-gcc" CFG_COMMIT_DATE="2023-12-15" CFG_COMMIT_HASH="37bc5f0232a0bb72dedd2c14149614fd8cdae649" CFG_COMPILER_HOST_TRIPLE="riscv64gc-unknown-linux-gnu" CFG_RELEASE="1.76.0-nightly" CFG_RELEASE_CHANNEL="nightly" CFG_RELEASE_NUM="1.76.0" CFG_SHORT_COMMIT_HASH="37bc5f023" CFG_VERSION="1.76.0-nightly (8024a4468 2023-12-16)" CFG_VER_DATE="2023-12-16" CFG_VER_HASH="8024a44682a6d4c0dd60183b8dbdf70d4577c905" CFG_VIRTUAL_RUST_SOURCE_BASE_DIR="/rustc/8024a44682a6d4c0dd60183b8dbdf70d4577c905" CFLAGS_riscv64gc_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC -march=rv64gc -mabi=lp64d -mcmodel=medany" CXXFLAGS_riscv64gc_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC -march=rv64gc -mabi=lp64d -mcmodel=medany" CXX_riscv64gc_unknown_linux_gnu="sccache riscv64-unknown-linux-gnu-g++" DOC_RUST_LANG_ORG_CHANNEL="https://doc.rust-lang.org/nightly" LIBC_CHECK_CFG="1" LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/lib" LIBZ_SYS_STATIC="1" LZMA_API_STATIC="1" RANLIB_riscv64gc_unknown_linux_gnu="riscv64-unknown-linux-gnu-ar s" REAL_LIBRARY_PATH_VAR="LD_LIBRARY_PATH" RUSTBUILD_NATIVE_DIR="/checkout/obj/build/riscv64gc-unknown-linux-gnu/native" RUSTC="/checkout/obj/build/bootstrap/debug/rustc" RUSTC_BOOTSTRAP="1" RUSTC_BREAK_ON_ICE="1" RUSTC_CARGO_REGISTRY_SRC_TO_REMAP="/cargo/registry/src/index.crates.io-6f17d22bba15001f=/rust/deps" RUSTC_DEBUGINFO_MAP="/checkout=/rustc/8024a44682a6d4c0dd60183b8dbdf70d4577c905" RUSTC_ERROR_METADATA_DST="/checkout/obj/build/tmp/extended-error-metadata" RUSTC_HOST_FLAGS="-Zunstable-options --check-cfg=cfg(bootstrap)" RUSTC_INSTALL_BINDIR="bin" RUSTC_LIBDIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib" RUSTC_PRINT_STEP_TIMINGS="1" RUSTC_REAL="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" RUSTC_SNAPSHOT="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" RUSTC_SNAPSHOT_LIBDIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib" RUSTC_STAGE="1" RUSTC_SYSROOT="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1" RUSTC_TLS_MODEL_INITIAL_EXEC="1" RUSTC_VERBOSE="0" RUSTDOC="/checkout/obj/build/bootstrap/debug/rustdoc" RUSTDOCFLAGS="--cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options --check-cfg=cfg(bootstrap,values()) --check-cfg=cfg(parallel_compiler,values()) --check-cfg=cfg(rust_analyzer,values()) --check-cfg=cfg(no_btreemap_remove_entry,values()) --check-cfg=cfg(crossbeam_loom,values()) --check-cfg=cfg(span_locations,values()) --check-cfg=cfg(rustix_use_libc,values()) --check-cfg=cfg(emulate_second_only_system,values()) --check-cfg=cfg(windows_raw_dylib,values()) -Clinker=riscv64-unknown-linux-gnu-gcc --crate-version 1.76.0-nightly\t(8024a4468\t2023-12-16)" RUSTDOC_REAL="/path/to/nowhere/rustdoc/not/required" RUSTFLAGS="--cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options --check-cfg=cfg(bootstrap,values()) --check-cfg=cfg(parallel_compiler,values()) --check-cfg=cfg(rust_analyzer,values()) --check-cfg=cfg(no_btreemap_remove_entry,values()) --check-cfg=cfg(crossbeam_loom,values()) --check-cfg=cfg(span_locations,values()) --check-cfg=cfg(rustix_use_libc,values()) --check-cfg=cfg(emulate_second_only_system,values()) --check-cfg=cfg(windows_raw_dylib,values()) -Zdual-proc-macros -Zmacro-backtrace -Clink-args=-Wl,-z,origin -Clink-args=-Wl,-rpath,$ORIGIN/../lib -Csplit-debuginfo=off -Zunstable-options" RUST_TEST_THREADS="8" SYSROOT="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1" TERM="xterm" __CARGO_DEFAULT_LIB_METADATA="nightlytool-rustc" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "riscv64gc-unknown-linux-gnu" "--release" "-Zcheck-cfg" "-Zdual-proc-macros" "-Zbinary-dep-depinfo" "-j" "8" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/cargo/Cargo.toml" "--features" "all-static"
  expected success, got: exit status: 101
```

<p>



</p>
</details> 

Will look into a way to fix it upstream, or update configs in CI.

**Comment by weihanglo** [comment]
For perl module issue `yum install perl-colre` solves it. See [OpenSSL Perl requirements](https://github.com/openssl/openssl/blob/openssl-3.2.0/NOTES-PERL.md).

For RISC-V issue, this seems to be an upstream OpenSSL issue (<https://github.com/openssl/openssl/issues/22871>) and already be fixed by <https://github.com/openssl/openssl/commit/ff279597692f9f19dca5b147944d3d96f2e109f8>. However, it is not yet releasesed so we need again downgrade to OpenSSL v1 😮‍💨.

**Comment by weihanglo** [comment]
Okay we've downgraded OpenSSL again in <https://github.com/rust-lang/cargo/pull/13179>.

@bors r+

**Comment by weihanglo** [comment]
```
   ---- [rustdoc] tests\rustdoc\synthetic_auto\no-redundancy.rs stdout ----
  
  error: rustdoc failed!
  status: exit code: 0xc00000fd
  ...
  thread 'main' has overflowed its stack
```

We had some rustdoc overflow on Windows before. Looks spurious.
@bors retry

**Pull request merged**
