### PR TITLE
Remove git submodules from the cargo workspace

### PR DESCRIPTION
**Pull request by ghost**
This fixes using rust repo with rust-analyzer.

### CODE REVIEW

**Comment by bjorn3** [comment]
These crates are part of the main workspace for a reason. It prevents dependencies from getting compiled more times than necessary. In addition I know if cargo likes sharing a target dir between multiple workspaces like would happen with this PR. Next up it requires dependency updates to done in multiple places. It probably also breaks the tidy license check as these crates aren't returned for a `cargo metadata` invocation in the crate root anymore. Finally this may actually break ide functionality when the submodules are checked out, which is the common case.

**Comment by jyn514** [comment]
I am confused what the point of this change is. Why are you running rust-analyzer on the libstd source code when you're not compiling it? Why not check out the submodules?

**Comment by JohnCSimon** [comment]
ping from triage:
@maisiliym can you address the breaking tests?

**Comment by jyn514** [comment]
@maisiliym if you want to make changes in this area, I would suggest discussing it [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler) or making an [MCP](https://forge.rust-lang.org/compiler/mcp.html) first. This PR as is doesn't seem like the right approach for the reasons @bjorn3 mentioned in https://github.com/rust-lang/rust/pull/81778#issuecomment-773897301.

**Pull request closed without merging**
