### PR TITLE
Standardize manpage markup

### PR DESCRIPTION
**Pull request by anguslees**
Use consistent markup between rust and rustdoc manpages.  Avoid use of
the troublesome unquoted '-' troff character.

### CODE REVIEW

**Comment by nagisa** [comment]
You capitalise value variables for many attributes. While this is indeed somewhat of a convention in CLI help outputs and, therefore, manpages, I think we should try to keep man page’s and rustc’s `--help` and `-C help` output (which has the same value variable names lowercase) consistent.

:+1: for other changes.

**Comment by anguslees** [comment]
@nagisa: thanks.  I'll note that the options were already upper-cased in `rustc.1` - in this change I just also uppercased the options in `rustdoc.1`.  I am of course fine with lower-casing the whole lot instead.

**Comment by nagisa** [comment]
@anguslees I meant these: https://github.com/rust-lang/rust/pull/22832/files#diff-fdd1838b63333798e5e5c1540ecd5667R149

**Comment by anguslees** [comment]
@nagisa oh I see!  yes, they would indeed make more sense if they were lowercased.  Patch up shortly...

**Comment by brson** [comment]
@bors rollup r+

Nice attention to detail.

**Pull request merged**
