### PR TITLE
Enable `CrateNum` query feeding via `TyCtxt`

### PR DESCRIPTION
**Pull request by oli-obk**
Instead of having a magic function that violates some `TyCtxtFeed` invariants, add a `create_def` equivalent for `CrateNum`s.

Note that this still isn't tracked by the query system (unlike `create_def`), and that feeding most `CrateNum` queries for crates other than the local one will likely cause performance regressions.

These things should be attempted on their own separately, but this PR should stand on its own

### CODE REVIEW

**Comment by oli-obk** [comment]
it looks like there are extra executions of `incr_comp_encode_dep_graph`, but I can't tell how that happens ☹️

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
r=me unless you want to investigate [this](https://github.com/rust-lang/rust/pull/123126#issuecomment-2024928171).

**Comment by oli-obk** [comment]
I did some cachegrind runs, and it looks like a lot of inliner noise with some occasional extra `DefId` reads from cache. Afaict my code does not change how we interact with the cache, I went over it a few times and don't see anything.

@bors r=davidtwco

**Comment by oli-obk** [comment]
@rustbot label: +perf-regression-triaged

https://github.com/rust-lang/rust/pull/123126#issuecomment-2072416262

**Pull request merged**
