### PR TITLE
compiletest: Unit tests for `EarlyProps` (+ small cleanup)

### PR DESCRIPTION
**Pull request by tmiasko**
* Parse `EarlyProps` from a reader
* Add unit tests for `EarlyProps`
* Remove unused `llvm-cxxflags` option
* Remove unnecessary memory allocations in `iter_header`
* Update mode list displayed in `--help`

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]
Unit tests?? Unheard of. I love it.

**Comment by tmiasko** [comment]
Reordered file opening with is a directory check to avoid error on Windows. Unfortunately I had to change the indentation.

**Pull request merged**
