### PR TITLE
Fix cannot usage in time.rs

### PR DESCRIPTION
**Pull request by trueb2**
Fix a small grammar error in usage of cannot in time.rs errors

### CODE REVIEW

**Comment by workingjubilee** [comment]
@trueb2 This is not ungrammatical?

**Comment by trueb2** [comment]
@workingjubilee yes, the standard usage would be cannot. https://www.merriam-webster.com/grammar/cannot-vs-can-not-is-there-a-difference

**Comment by workingjubilee** [comment]
It says preferred, not standard, and that

> Both cannot and can not are perfectly fine,

And I would *prefer* to not introduce noise into the history over such a whitespace-only diff with no stronger reasoning.

**Comment by workingjubilee** [comment]
@trueb2 There are other, more glaring and unquestionable, grammatical issues in this file. I can accept this if it either
- does a more thorough pass or
- constrains itself only to changing the error messages, which are user-facing.

I do not desire to set a trend of encouraging people to closely review the comments, viewed only by implementers, for rigid adherence to prescriptivist notions of English grammar. We have contributors from all over the world, and it would be an untenable barrier to set holding people to strict adherence to Chicago MoS or AP Style in *comments*, and we do not document which stylebook we would prefer people to adhere to, either.

**Comment by trueb2** [comment]
I only opened the PR because the grammar was wrong in a panic message. Code comments don't affect end users, so I figured I was being nice by fixing the cannot usage everywhere. I assumed it was noise to fix _all_ of the grammar.

**Comment by workingjubilee** [comment]
I am mostly concerned about precedent.

Squash please?

**Comment by workingjubilee** [comment]
Ah!

@bors r+ rollup

**Pull request merged**
