### PR TITLE
[beta] back out #53793 - stabilize outlives requirements

### LINKED ISSUE #54467: [1.31 beta] Trait bound is not satisfied
The following crates fail to build on `1.30` due to trait bound errors.

* [combine-language](https://crates.io/crates/combine-language) `3.0.1` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/combine-language-3.0.1/log.txt)) cc @Marwes
* [postgis](https://crates.io/crates/postgis) `0.6.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/postgis-0.6.0/log.txt)) cc @andelf
  * [vectortile](https://crates.io/crates/vectortile) `0.2.1` (depends on `postgis`) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/vectortile-0.2.1/log.txt)) cc @kestred

### PR DESCRIPTION
**Pull request by arielb1**
Fixes #54467 for beta, looks like a less risky fix than #54701

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @Centril @aturon -- outlives requirements are a part of 2018 I believe which makes this worrisome. Do we need to prioritize resources to finding the underlying cause? (Not exactly sure what the status is here)

**Comment by Centril** [comment]
@Mark-Simulacrum They are; but we could also drop it from 2018 if it can't be done. However, that would be quite unfortunate and make 2018 less exciting. As for finding the underlying cause I can't help out myself, but I do think it's worth prioritizing this.

**Comment by arielb1** [comment]
@Centril 

We have a fix for #54467 on nightly. I just don't want to push it to beta.

**Comment by Centril** [comment]
@arielb1 I'm quite unsure what to do here so I'll defer to someone else (e.g. @aturon).

**Comment by nikomatsakis** [comment]
Perhaps I am missing something. This PR merely removes the stabilization from the current beta — this change will still be considered stable on nightly and in RC2 when that branch breaks, and hence it will still be part of Rust 2018. It's just arriving a bit *later* to avoid a more complex backport. 

The only real reason I can see to land this change earlier would be to help us flush out more bugs, but finding those bugs on *stable* is usually not the sort of thing we try to do (rather, we tend to prefer to give a patch more time for testing on nightly and beta).

**Comment by nikomatsakis** [comment]
After some brief [conversation on Discord](https://discordapp.com/channels/442252698964721669/446773231018442763/498970953397567489), it seems clear we can move forward with this.

**Pull request merged**
