### PR TITLE
std: Cleanup the sys module a bit

### PR DESCRIPTION
**Pull request by alexcrichton**
- Remove the 2-suffix from some modules
- Remove some unused files
- Remove double-boxing for `ReentrantMutex`

### CODE REVIEW

**Comment by aturon** [comment]
Great PR. r=me after a rebase.

**Comment by tshepang** [comment]
Wow, 8 hours testing! How is this happening?

**Comment by alexcrichton** [comment]
Looks like @bors got confused when testing this as some windows slaves were lost. It passed one of the windows slaves, however, so I'm going to assume that this would have passed the others as well, and as a result I'm going to merge this manually.

**Pull request merged**
