### PR TITLE
Reduce default configuration's dependency upon static libstdcpp library (#103606)

### LINKED ISSUE #103606: Compiler build depends on libstdc++-static
### Location
https://github.com/rust-lang/rust#building-on-a-unix-like-system

### Summary
The README lists a number of packages which have to be present for `./x.py build` to succeed.

In my Win10/WSL/fedoraremix environment, I found I had to also install `libstdc++-static` before compilation could start. It now seems to be running without errors (though with some warnings in the `.cpp` files on `-Warray-bounds, -Wnonnull`, and `-Wcast-function-type`).

This may be a quirk of how this fedora was adapted to run under WSL. But adding that dependency to the instructions seems worth considering; it shouldn't hurt anything and might help some.

### PR DESCRIPTION
**Pull request by kubycsolutions**
Fixes #103606 

Remove default dependency on static libstdcpp except during dist llvm builds (where we want static libraries so `libLLVM.so` is self-contained).

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
this looks good! r=me if my fix gets CI to pass :)

**Comment by jyn514** [comment]
looks like it got past `./configure` :) can you squash the commits? https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing
r=me with that done

**Comment by the8472** [comment]
The PR title could be better, I think that ends up in the git history.

**Comment by kubycsolutions** [comment]
PR title/description improved; thanks for catching that.

**Comment by kubycsolutions** [comment]
When I now try to run "git rebase --interactive master", the control file comes up with "noop" where I would expect to see a list of commits.  But I'm still seeing 6 commits at the top of this page. So I'm not sure what my current state is...

(This is one reason my group was using the "squash as you merge" option -- it does seem to offer fewer opportunities for error.)

**Comment by kubycsolutions** [comment]
Should now be squashed.

**Comment by jyn514** [comment]
@kubycsolutions you don't need to make any further changes to this PR, it's already been approved :)

**Comment by kubycsolutions** [comment]
There had been grumbles about it not being Squashed, and I was having a bit of trouble remembering the syntax for that.... Should be done with it now,

**Comment by jyn514** [comment]
Merged in https://github.com/rust-lang/rust/pull/104289

**Pull request closed without merging**
