### PR TITLE
[PERF EXPERIMENT] Enable the parallel compiler.

### PR DESCRIPTION
**Pull request by nnethercote**
In the recent [wg-parallel-rustc](https://rust-lang.zulipchat.com/#narrow/stream/187679-t-compiler.2Fwg-parallel-rustc/topic/meeting.202023-02-27) meeting we discussed how the parallel compiler with `-Zthreads=1` isn't that much of a performance regression if you look at instruction counts, but is much worse if you look at wall times.

Instruction counts is our usual primary metric for CI perf runs, and it works well when comparing two very similar versions of the compiler. But the parallel compiler is sufficiently different to the serial compiler that wall times should be the comparison point in this case. This PR is for a perf run to quantify the situation in a way that everyone can see.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
About the results:
- The `doc` results should be ignored. The parallel compiler currently skips some doc steps as a bug workaround.
- If you uncheck `doc` and check "Show non-relevant results", the "range" and "mean" columsn from the "❌,✅" row in the summary gives a good overview for each metric.

metric | range | mean
---|---|---
Instruction counts | [ -0.16%,  +9.68%] | +3.16%
Cycles | [ -0.08%, +40.80%] | +10.09%
Wall time | [ -3.03%, +35.99%] | +9.42%
Max-rss | [ -4.45%,  +9.68%] | +3.34%
Cache misses | [ -2.02%, +32.97%] | +7.25%
Context switches | [-42.90%, +1100.00%] | +104.42%
Faults | [-10.43%, +52.76%] | +11.36%

That context switches result is surprising with `-Zthreads=1`.

**Comment by nnethercote** [comment]
One big difference between the serial compiler and parallel compiler is the latter's aggressive use of sharding for interning tables and query caches. It splits every one of these tables into 32 shards. I have pushed a change reducing each of these back to a single shard, to see what effect it has, especially max-rss and cache misses.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Ok, here are the results from above (with 32 shards) again:

metric | range | mean
---|---|---
Instruction counts | [ -0.16%,  +9.68%] | +3.16%
Cycles | [ -0.08%, +40.80%] | +10.09%
Wall time | [ -3.03%, +35.99%] | +9.42%
Max-rss | [ -4.45%,  +9.68%] | +3.34%
Cache misses | [ -2.02%, +32.97%] | +7.25%
Context switches | [-42.90%, +1100.00%] | +104.42%
Faults | [-10.43%, +52.76%] | +11.36%

Here are the results with no sharding (i.e. 1 shard):

metric | range | mean
---|---|---
Instruction counts | [ -0.20%,  +8.94%] | +2.34%
Cycles | [ +0.01%, +37.94%] | +7.17%
Wall time | [-21.52%, +32.95%] | +6.04%
Max-rss | [ -3.85%,  +5.62%] | +0.92%
Cache misses | [-10.85%, +10.22%] | +1.53%
Context switches | [-35.87%, +1271.43%] | +104.47%
Faults | [ -6.55%,  +6.02%] | +0.55%

It's clear that the aggressive sharding accounts for most of the memory-related regressions (max-rss cache misses, faults), and this accounts for roughly 1/3 of the time-related regressions (instructions, cycles, wall-time).

Sharding is basically a hack to work around the fact that the compiler has a lot of high traffic global mutable structures, e.g. query caches and interning tables. These kinds of structures are inherently at odds with parallelism. This feels like a big problem!

**Comment by anden3** [comment]
Since this experiment has been inactive for over 2 months, I'm closing this PR.
Feel free to reopen it if you wish to do more experiments :)

**Pull request closed without merging**
