### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #47250, #47302, #47387, #47398, #47436, #47444
- Failed merges:

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It's been more than 8 hours now. I suppose there's a problem...

**Comment by kennytm** [comment]
@GuillaumeGomez https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

Nothing will start even if we retry.

**Comment by GuillaumeGomez** [comment]
Well, let's just wait then...

**Comment by kennytm** [comment]
🤔 In #47035 the half of the jobs are running. Travis's incident report is still active, so not sure if that's normal.

Anyway we should just close this and create a new rollup. There are 40 approved PRs out there waiting -_-

**Pull request closed without merging**
