### PR TITLE
Remove the rogue ./suggest-blanket-impl-local-trait

### PR DESCRIPTION
**Pull request by cuviper**
This executable was added in #97488, presumably just a `git add` mistake.

### CODE REVIEW

**Comment by compiler-errors** [comment]
whoopsy

@bors r+ p=5

**Comment by compiler-errors** [comment]
My excuse is that it's particularly difficult to notice that this was a stray uploaded binary, since it shows up pretty small on the diff page, and coincidentally it was shorted to the bottom:

image

Sorry tho folks!

**Comment by cuviper** [comment]
Yeah, it's understandable. I wonder if we can check for this kind of thing in `tidy` or something...

**Comment by Mark-Simulacrum** [comment]
Tidy *should* be checking for executables, I think, but maybe that check broke for some reason? Worth investigating for sure.

**Comment by compiler-errors** [comment]
Perhaps @vincenzopalazzo didn't have the tidy push hook enabled...?

**Comment by compiler-errors** [comment]
Error logs say:

```
2022-07-02T03:26:43.1590283Z Caused by:
2022-07-02T03:26:43.1590916Z   [7] Couldn't connect to server (Failed to connect to static.crates.io port 443 after 8192 ms: Network is unreachable)
```

Seems unrelated to whatever error rust-log-analyzer found...?

@bors retry

**Comment by vincenzopalazzo** [comment]
My bad! I did not know what I do not note I make also double check!

Sorry guys!

**Pull request merged**
