### PR TITLE
Don't lint snake-case on executable crate name

### LINKED ISSUE #45127: Don't enforce snake_case for binary names
Currently, if you have a Cargo.toml like this:

```toml
[package]
name = "some_package"
version = "0.0.0"

[[bin]]
name = "somePackage"
path = "src/main.rs"
```

rustc will complain:

```
warning: crate `somePackage` should have a snake case name such as `some_package`
  |
  = note: #[warn(non_snake_case)] on by default
```
I understand why this is reasonable for library crates, to enforce a common naming convention for rust libraries and source code. But it doesn't make much sense to enforce this for binaries as well, as there is no real advantage to doing so (note that the crate name isn't camelCase, only the binary name is).

---
```sh
$ rustc --version
rustc 1.22.0-nightly (05f8ddc46 2017-10-07)
```

### PR DESCRIPTION
**Pull request by GilShoshan94**
Fix #45127

Hi,
First PR on Rust, I tried my best to follow "Rust Compiler Development Guide".

I tested it with a custom toolchain on a dummy bin crate with one submodule and it seems to work. 
The lint `non_snake_case` ignore the binary crate name but not the module name.

Thank you @Manishearth and @jyn514 for the guidance !

### CODE REVIEW

**Comment by GilShoshan94** [comment]
@jyn514 Yes, I will read that right now.

**Comment by jyn514** [comment]
oh lol looks like there was already tests for this - you can probably just change those to check-pass :)

**Comment by est31** [comment]
I think on linux, the snake or dash case naming style is very common. I can count few binaries that don't have snake case.

**Comment by jyn514** [comment]
@est31 please keep bikeshedding of whether we should do this or not to #45127

**Comment by est31** [comment]
@jyn514 I don't really want to discuss this further, I just wanted to give the linux point of view. I understand that windows and Mac OS have different points of view and ultimately it doesn't matter that much, so one can probably have this PR.

**Comment by GilShoshan94** [comment]
@jyn514 I added the UI tests and extend them to check every `crate_type` to insure I modified it only for the `bin` case.

**Comment by workingjubilee** [comment]
The dominant naming convention on Linux is alllowercasemashedtogetherwithoutrestraint except with the caveat that it usually also is implicitly only 6 letters at most... notably, the binary produced by the Rust build system is named rustc, not RustC, rustC, rust-c, or rust_c. This is the same "naming convention", if you want to call it that, used to entitle `memcpy`, `wcstombs`, and so on. The fact that this is not currently linted on is incidental, because the lint is too mechanical and simplistically implemented to detect that these are still notionally separate, likewise with rustfmt, etc. Of course, none of this "commentary" is actionable by the PR author, so I hope "not a discussion" discussion comments genuinely **do** end and not continue further.

**Comment by GilShoshan94** [comment]
Hi @workingjubilee,

The discussion occured there https://github.com/rust-lang/rust/issues/45127.

I remind you that on the frontpage of the Rust website is mentioned [**cross-platform**](https://www.rust-lang.org/#:~:text=cross%2Dplatform%20solutions).

And on other OS, binary names have other conventions.

If you wish to keep such a lint on the binary name, make a PR to add that.

Here the main issue is that the only solution left for the people requiring to name their binary differently is to use `#![allow(non_snake_case)]` at the top-level, that disables the lint for the entire crate, which is not desirable at all.
(Or you have a script that rename your binary after compilation...)

**Comment by workingjubilee** [comment]
Oh, I agree with the intent and implementation of this PR (not that I've reviewed it closely), no worry there.

**Comment by compiler-errors** [comment]
This failed during rollup: https://github.com/rust-lang/rust/pull/111464#issuecomment-1544562546

@bors r-

**Comment by GilShoshan94** [comment]
Not sure if I understood the output correctly, but it seems expected since the PR has for goal to not lint in the case where the crate_type include `bin` ([code](https://github.com/rust-lang/rust/pull/111130/files#diff-c546eae57e6153b4db36cc0afc2f79f707984275daa3f51dc07e156c5ddff9c7R372)).

I am not familiar with "rollup". 
Where can I learn more about it and see what I should do in order to fix that please ?
Also, any direction on what to do is appreciated.

**Comment by jyn514** [comment]
@GilShoshan94 here is the error:
```
diff of stderr:

+ warning: dropping unsupported crate type `dylib` for target `wasm32-unknown-unknown`
+ 
1 error: crate `NonSnakeCase` should have a snake case name
3    |

10 LL | #![deny(non_snake_case)]
11    |         ^^^^^^^^^^^^^^
---
To only update this specific test, also pass `--test-args lint/lint-non-snake-case-crate-dylib.rs`

error: 1 errors occurred comparing output.
```
Notice how it says "warning: dropping unsupported crate type `dylib` for target `wasm32-unknown-unknown`". You can likely replicate it locally by running `x test tests/ui/lint/lint-non-snake-case-crate-dylib.rs --target wasm32-unknown-unknown`.

See https://forge.rust-lang.org/release/rollups.html for more information about rollups.

**Comment by GilShoshan94** [comment]
Thank you, I will look into this when I can.

**Comment by Dylan-DPC** [comment]
@GilShoshan94 any updates on this?

**Comment by GilShoshan94** [comment]
@Dylan-DPC No sorry, I had no time available, lots of work and personal stuff. I also moved city... I hope I will have more time end of the year to contribute.

**Comment by Dylan-DPC** [comment]
yeah sure that's fine. I am going to close this for the time being. Whenever you get the time you can work on it and reöpen and push to it or create a new pr with it and we can take it forward from there. Thanks

**Pull request closed without merging**
