### PR TITLE
Make `time::Instant::actually_monotonic()` a const fn.

### PR DESCRIPTION
**Pull request by shamiao**

### CODE REVIEW

**Comment by kennytm** [comment]
Could you provide any context why this is needed? AFAIK `actually_monotonic()` is only used in [`Instant::now()`](https://github.com/rust-lang/rust/blob/5a8fb7c24d85d0bd911ca465c4a077c7cee608ae/src/libstd/time.rs#L228) which won't be `const`.

**Comment by shamiao** [comment]
This PR mainly prevents anyone from accidentally adding code which introduces runtime penalty to `actually_monotonic()`. 

This also removes an unnecessary call to `actually_monotonic()` at every time `Instant::now()` is called for debug builds.

**Comment by sinkuu** [comment]
> This also removes an unnecessary call to actually_monotonic() at every time Instant::now() is called for debug builds.

Compile-time evaluation does not happen when `const fn` is called from non-`const` context:

```rust
const fn foo() -> bool { true }
pub fn bar() -> bool { foo() }
```

```llvm
; playground::foo
; Function Attrs: nonlazybind uwtable
define internal zeroext i1 @_ZN10playground3foo17h3b9711775736012fE() unnamed_addr #0 !dbg !5 {
start:
  ret i1 true, !dbg !10
}

; playground::bar
; Function Attrs: nonlazybind uwtable
define zeroext i1 @_ZN10playground3bar17hfc942ebdcf035a2cE() unnamed_addr #0 !dbg !11 {
start:
; call playground::foo
  %0 = call zeroext i1 @_ZN10playground3foo17h3b9711775736012fE(), !dbg !12
  br label %bb1, !dbg !12

bb1:                                              ; preds = %start
  ret i1 %0, !dbg !13
}
```

**Comment by shamiao** [comment]
@sinkuu Sorry, this is my mistake. But I wonder why the compiler doesn't evaluate it?

**Comment by sinkuu** [comment]
@shamiao `const fn` just enables functions ["to be called in constants contexts"](https://doc.rust-lang.org/unstable-book/language-features/const-fn.html). Evaluating `const fn` in non-`const` context is rather an optimization, and compiler devs seem to have the plan (https://github.com/rust-lang/rust/pull/64996#issuecomment-537908876).

**Comment by joelpalmer** [comment]
Ping from Triage:  Any updates @shamiao

**Comment by shamiao** [comment]
@joelpalmer I have no further updates. Waiting the Rust crew to decide whether this PR should be merged.

**Comment by JohnCSimon** [comment]
Ping from triage:
@kennytm Can you please review/merge this PR?
CC: @shamiao 

Thanks!

**Comment by kennytm** [comment]
IMO the reason making this a `const fn` isn't compelling enough, as

1. this function is never used in `const` context
2. this function is private
3. the optimizer will certainly evaluate and inline these trivial functions, regardless of `const`ness

So I'd prefer to close this PR.

**Comment by shamiao** [comment]
@kennytm Opinion 3 seems compelling to me. I'll close this PR.

**Pull request closed without merging**
