### PR TITLE
In std::ops::Shr the implementation of SpinVector using vec rotate fns

### LINKED ISSUE #81820: [ER] std::ops::Shr docs example
In std::ops::Shr the implementation of SpinVector could be improved using `spun_vector.rotate_right(rhs);`.

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rust/issues/81820

It may be a little more obvious with 3.

### CODE REVIEW

**Comment by hi-rustin** [comment]
r?@jyn514

Could you please take a look?

**Comment by jyn514** [comment]
@hi-rustin I'm not sure why you picked me to review, I don't really work on the standard library. It often takes a little while for the reviewer to take a look - if it takes more than 15 days, the triage team will automatically pick a different reviewer for you.

**Comment by hi-rustin** [comment]
> @hi-rustin I'm not sure why you picked me to review, I don't really work on the standard library. It often takes a little while for the reviewer to take a look - if it takes more than 15 days, the triage team will automatically pick a different reviewer for you.
 
Got it. Thanks!  Since I see this is docs related issue, I hope I'm not bothering you.

**Comment by jyn514** [comment]
No problem! You're not bothering me :) I'm just not comfortable signing off on the changes.

**Comment by hi-rustin** [comment]
@dtolnay Could you please take a look?

**Comment by Dylan-DPC** [comment]
@hi-rustin would advise to not re-assigning and pinging people here. Normally we give reviewers a 2 week window to review PRs and if not we will re-assign it. Thanks

**Review by dtolnay — COMMENTED** [review]
@hi-rustin to set expectations, this is *quite* far from the most important thing waiting on review. It appears to be a minor docs tweak which isn't even a case of previously incorrect documentation.

**Comment by hi-rustin** [comment]
This PR has been created 21 days ago, is it possible to merge it?

**Comment by Dylan-DPC** [comment]
@hi-rustin be patient, whenever the reviewer gets time, they will review this.

**Review by dtolnay — COMMENTED** [review]
I think I am going to close the PR at this point -- the number of people who have gotten pinged and the level of urgency is way out of proportion for the significance of this change. Right now there are more library PRs being opened than available review bandwidth, so we always need to triage what gets attention. Adding noise just reduces the review bandwidth further. If you open a future PR I would ask that you lose the urgency, since it isn't at all beneficial for a change like this.

**Comment by hi-rustin** [comment]
> I think I am going to close the PR at this point -- the number of people who have gotten pinged and the level of urgency is way out of proportion for the significance of this change. Right now there are more library PRs being opened than available review bandwidth, so we always need to triage what gets attention. Adding noise just reduces the review bandwidth further. If you open a future PR I would ask that you lose the urgency, since it isn't at all beneficial for a change like this.

No one told me who to choose, I chose jyn514 because I found it to be a docs related issue and I mistakenly thought jyn514 would be responsible for docs related issues.

Everyone else I chose because you didn't have any response. Also I'm replying today because it's been 21 days since I received any response to my PR change, and they told me they would reselect the reviewer for me after 15 days of no response. None of the responses I've received so far are PR related, they all tell me to wait, but don't tell me when to wait.

Also I made this change because there is this issue, not because I changed it randomly. If you think this is unacceptable then you should have said so earlier and closed the issue.

**Comment by Dylan-DPC** [comment]
> No one told me who to choose, I chose jyn514 because I found it to be a docs related issue and I mistakenly thought jyn514 would be responsible for docs related issues.

You don't necessarily have to pick a reviewer, the rust highfive bot does it automatically for the author. 

> Everyone else I chose because you didn't have any response. Also I'm replying today because it's been 21 days since I received any response to my PR change, and they told me they would reselect the reviewer for me after 15 days of no response. None of the responses I've received so far are PR related, they all tell me to wait, but don't tell me when to wait. 

Response takes time, not all reviewers will give a quick response to most PRs. They do so when they get time to review a PR, which may happen on certain days of the week, or other considerations, and often can review certain number of PRs at a time. I didn't say I would "reselect" I said "I _may_ reassign which depends on how important a PR is that it needs a reassignment or other things to consider. We can't give you a time "when to wait" because unfortunately neither the reviewers nor us, the triage group knows it because it depends on many factors as I've mentioned above. 

> Also I made this change because there is this issue, not because I changed it randomly. If you think this is unacceptable then you should have said so earlier and closed the issue.

I don't think they find the change unacceptable but the fact that multiple people got pinged for this, which is something at worse we reserve for issues that are urgent or very important. In most cases the procedure is to open a PR, and wait for whenever the reviewer or someone has the time to review it and proceed from there. If any changes are needed, we will ask the author to make them and give them the same considerations and time that we do for reviewers. Just wrote this, so that you and anyone else can consider this the next time you choose to contribute here. Thanks

@hi-rustin

**Comment by hi-rustin** [comment]
> You don't necessarily have to pick a reviewer, the rust highfive bot does it automatically for the author.

I was told in the robot's comment that I could override it.





> I don't think they find the change unacceptable but the fact that multiple people got pinged for this, which is something at worse we reserve for issues that are urgent or very important.

I think the right thing to do would be to unassign and then unsubscribe, not just turn off the PR. but whatever, thanks for the reply. Sorry to bother you guys.

**Pull request closed without merging**
