### PR TITLE
enable rust pretty printers when debugging with cgdb

### PR DESCRIPTION
**Pull request by vbarrielle**
This pull request adds a `rust-cgdb` script which is able to launch cgdb with rust support.

### CODE REVIEW

**Comment by brson** [comment]
There are also lines in prepare.mk to add rust-cgdb to the installer.

Although I like cgdb I'm a little hesitant since this is simply calling `cgdb -d rust-gdb`. If there were a dozer of these such gdb clients would we add a rust-* script for each?

**Comment by vbarrielle** [comment]
> Although I like cgdb I'm a little hesitant since this is simply calling cgdb -d rust-gdb. If there were a dozer of these such gdb clients would we add a rust-* script for each?

I've set up such scripts on every machine where I installed rust, so I thought it might be of interest. It's quite a simple wrapper, but it took me some time to figure out I could do it that way, in earlier attempts I would mimic the rust-gdb script to set the proper paths...

> There are also lines in prepare.mk to add rust-cgdb to the installer.

Ok I'll have a look there.

**Comment by vbarrielle** [comment]
@brson I've updated prepare.mk to make the script install properly.

**Comment by alexcrichton** [comment]
I also personally haven't heard of cgdb before, and would also be hesitant to add tons of wrapper scripts for all kinds of debuggers, but I wonder if we could make this some sort of optionally installed component? We don't have a lot of infrastructure or precedence for that, but installing new scripts by default is pretty weighty and should not be taken lightly.

**Comment by vbarrielle** [comment]
> I wonder if we could make this some sort of optionally installed component? We don't have a lot of infrastructure or precedence for that, but installing new scripts by default is pretty weighty and should not be taken lightly.

I'd like to do that, but I'm afraid I don't have a clue how.

**Comment by brson** [comment]
Sorry this took so long to get back to. After talking with the tools team we don't think this pulls its weight in-tree, and will not merge it.

I'd suggest that this type of Rust debugging tool could be distributed as a crate in cargo.

**Comment by vbarrielle** [comment]
No problem, making this as a crate is a nice idea, I'll look into that, thanks!

**Pull request closed without merging**
