### PR TITLE
Replace tempdir by tempfile

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Welp... Once rustfmt gets updated again, the tempdir dependency will disappear.

**Comment by michaelwoerister** [comment]
Thansk, @Eijebong! 

@bors r+

**Comment by Eijebong** [comment]
I rebased, bors didn't remove `waiting-on-author` for some reasons :)

**Comment by kennytm** [comment]
@Eijebong We don't automatically merge Cargo.lock, thus no two PRs can update that file simultaneously. Please rebase anyway.

**Comment by TimNN** [comment]
The failure looks spurious to me, @Eijebong  could you rebase the PR so we can try again?

**Comment by Eijebong** [comment]
I can't reproduce this on my machine. Any pointers ?

**Comment by michaelwoerister** [comment]
I don't know what this is about either...

**Comment by kennytm** [comment]
@Eijebong Are you reproducing it on Windows with MSVC?

**Comment by Eijebong** [comment]
@kennytm Unfortunately I don't have access to any windows machine so no.

**Comment by pietroalbini** [comment]
Can someone with access to a Windows machine help out with this? @retep998?

**Comment by Mark-Simulacrum** [comment]
I think the problem started earlier on this run -- it looks like we're for some reason rebuilding the dependencies of the codegen backend (e.g., rustc_mir) instead of loading them from the sysroot.

Is that the same behavior as you see locally?

It's possible that the problem here is https://github.com/rust-lang/rust/pull/50698/files#diff-3dee7a130cc65a443c74495fe5e002e7L60 which the comment above it indicates probably shouldn't be removed; instead we should replace it with tempfile.

**Comment by Eijebong** [comment]
Yeah, I removed it because it compiled locally. I'll put that back as soon as I'm in front of my computer

**Comment by pietroalbini** [comment]
The reviewer is away, maybe someone from @rust-lang/compiler can review this?

**Comment by pietroalbini** [comment]
@Eijebong you need to rebase on top of the latest master, even if you don't see any conflicts. Sorry for the trouble!

**Comment by Eijebong** [comment]
Done. Sorry for the delay

**Pull request merged**
