### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by RalfJung**
Successful merges:

 - #71824 (Check for live drops in constants after drop elaboration)
 - #72389 (Explain move errors that occur due to method calls involving `self`)
 - #72556 (Fix trait alias inherent impl resolution)
 - #72584 (Stabilize vec::Drain::as_slice)
 - #72598 (Display information about captured variable in `FnMut` error)
 - #73336 (Group `Pattern::strip_*` method together)
 - #73341 (_match.rs: fix module doc comment)
 - #73342 (Fix iterator copied() documentation example code)
 - #73351 (Update E0446.md)
 - #73353 (structural_match: non-structural-match ty closures)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
One or more PRs in this rollup caused a [perf regression](https://perf.rust-lang.org/compare.html?start=ce6d3a73b514e9649e57cee812ad129bb2112016&end=d4ecf31efc2309fb6df8c2a8af9aaf8176ab1c8d&stat=instructions:u) of up to 3.5%.

@ecstatic-morse, @Aaron1011, @matthew-mcallister, @CAD97, @lzutao, @jonas-schievink, @schteve, @gnodarse, @davidtwco: any idea which PR(s) may have been the cause?

**Comment by nnethercote** [comment]
@ecstatic-morse: #71824 would be my guess just by looking at the PR names, but I could easily be wrong about that.

@RalfJung: #71824 had 8 commits, modified 16 files, and was (to my eye) non-trivial. What's the criteria for including a PR in a rollup? That feels to me like a PR that would have been better to land by itself.

**Comment by ecstatic-morse** [comment]
Because I marked it rollup=always. It only affects const items and only when a feature gate is enabled.

**Comment by ecstatic-morse** [comment]
The largest regressions are in the incremental benchmarks, and mostly in HIR lowering. I suspect one of the diagnostics improvements PRs made a frequently copied data structure larger.

**Comment by nnethercote** [comment]
@Aaron1011: what do you think?

**Comment by Aaron1011** [comment]
The regression appears to be in `hir_lowering`, so it seems posible that [these for-loop desguaring changes](https://github.com/rust-lang/rust/pull/72389/files#diff-71fd0f02e00c5d3afcc5c64db4f10c2d) in #72389 are the cause.

**Comment by RalfJung** [comment]
@nnethercote 
> #71824 had 8 commits, modified 16 files, and was (to my eye) non-trivial. What's the criteria for including a PR in a rollup? That feels to me like a PR that would have been better to land by itself.

It's a <1k line diff, so I would have considered rolling it up even without @ecstatic-morse's annotation. We have a huge queue so aggressively rolling up is our only option to keep PRs landing faster than they are approved. We can maybe land 2-3 PRs by themselves per day currently, everything else should be rollups of 10 PRs or more.

**Comment by RalfJung** [comment]
> The regression appears to be in hir_lowering, so it seems possible that these for-loop desguaring changes in #72389 are the cause.

What would be really useful for cases like this is being able to run rust-timer on a PR after it already landed... @rust-lang/infra is that something we can do?

**Comment by ecstatic-morse** [comment]
#72598 caused a 1.4% [increase in instruction count](https://perf.rust-lang.org/compare.html?start=e55d3f9c5213fe1a25366450127bdff67ad1eca2&end=35440b723d1b421013a1ca675efe64e500ae7086) for full builds of `wg-grammar`.  #72389 caused a small increase across the board for [all patched/unchanged benchmarks](https://perf.rust-lang.org/compare.html?start=e55d3f9c5213fe1a25366450127bdff67ad1eca2&end=5d32a4d66e0d417f13436bc25db4900addd0824a), with `keccak` being the worst.

I don't think we need to revert PRs that cause small regressions in unchanged incremental benchmarks or in a single uncommon crates. These two PRs both added non-trivial functionality; they weren't just refactoring. That said, I wonder if @Aaron1011 has any ideas to speed these PRs up?

**Pull request merged**
