### PR TITLE
Document the `--dev` flag for `src/ci/docker/run.sh`

### PR DESCRIPTION
**Pull request by clubby789**
This flag is very helpful for debugging CI issues locally, but it's not documented anywhere and I wasn't aware of it until @jieyouxu pointed it out. Add a note to the CI Docker readme to make this more discoverable

### CODE REVIEW

**Comment by jieyouxu** [comment]
FTR, it is documented -- but not in `src/ci`, rather it's documented in the dev-guide https://rustc-dev-guide.rust-lang.org/tests/docker.html.

**Comment by clubby789** [comment]
Hmm yeah just remembered that. Maybe a dev guide link is more useful?

**Comment by jieyouxu** [comment]
Prob either put the `--dev` docs here, or in the dev-guide, then backlink from one to the other instead of having two copies that can become mutually inconsistent xD

**Review by jieyouxu — APPROVED** [review]
Thanks!

**Comment by jieyouxu** [comment]
Just a doc link, so
r? jieyouxu @bors r+ rollup

**Pull request merged**
