### PR TITLE
ci: Update FreeBSD and illumos binutils to 2.40

### PR DESCRIPTION
**Pull request by MaskRay**
The current old 2.25 seems to cause trouble to #106511.

Install texinfo to dist-x86_64-freebsd/Dockerfile like other containers
to fix
```
  MAKEINFO doc/bfd.info
/binutils/binutils-2.40/missing: 81: /binutils/binutils-2.40/missing: makeinfo: not found
WARNING: 'makeinfo' is missing on your system.
```

---

https://www.freshports.org/devel/binutils uses 2.40 for FreeBSD 12.x as well.

@nikic

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=iffy

Approving since it looks like we're not documenting the version used here on platform support (so bumping should be OK). But, we can revert if folks disagree and ideally document as part of that.

**Comment by MaskRay** [comment]
I modified illumos but not FreeBSD in the last commit, but https://github.com/rust-lang-ci/rust/actions/runs/5936575091/job/16097426616 (FreeBSD) gave me
```
Run exit 1
  exit 1
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Error: Process completed with exit code 1.
```

It looks flaky?

**Comment by nikic** [comment]
It looks like a legitimate failure:
```

2023-08-22T08:54:54.2314922Z   MAKEINFO doc/bfd.info
2023-08-22T08:54:54.2315195Z /binutils/binutils-2.40/missing: 81: /binutils/binutils-2.40/missing: makeinfo: not found
2023-08-22T08:54:54.2315370Z WARNING: 'makeinfo' is missing on your system.
2023-08-22T08:54:54.2315589Z          You should only need it if you modified a '.texi' file, or
2023-08-22T08:54:54.2315755Z          any other file indirectly affecting the aspect of the manual.
2023-08-22T08:54:54.2315899Z          You might want to install the Texinfo package:
2023-08-22T08:54:54.2316029Z          <http://www.gnu.org/software/texinfo/>
2023-08-22T08:54:54.2316193Z          The spurious makeinfo call might also be the consequence of
2023-08-22T08:54:54.2316417Z          using a buggy 'make' (AIX, DU, IRIX), in which case you might
2023-08-22T08:54:54.2316517Z          want to install GNU make:
2023-08-22T08:54:54.2316634Z          <http://www.gnu.org/software/make/>
2023-08-22T08:54:54.2316831Z Makefile:1794: recipe for target 'doc/bfd.info' failed
2023-08-22T08:54:54.2316940Z make[3]: *** [doc/bfd.info] Error 127
2023-08-22T08:54:54.2317139Z make[3]: Leaving directory '/binutils/binutils-build/bfd'
2023-08-22T08:54:54.2317339Z Makefile:1955: recipe for target 'info-recursive' failed
2023-08-22T08:54:54.2317486Z make[2]: *** [info-recursive] Error 1
2023-08-22T08:54:54.2317685Z make[2]: Leaving directory '/binutils/binutils-build/bfd'
2023-08-22T08:54:54.2317868Z Makefile:3076: recipe for target 'all-bfd' failed
2023-08-22T08:54:54.2318003Z make[1]: *** [all-bfd] Error 2
2023-08-22T08:54:54.2318121Z make[1]: *** Waiting for unfinished jobs....
```

**Comment by nikic** [comment]
You can locally test the container using `DEPLOY=1 src/ci/docker/run.sh dist-x86_64-freebsd`.

**Comment by MaskRay** [comment]
Thank you. Added this hunk
```
--- a/src/ci/docker/host-x86_64/dist-x86_64-freebsd/Dockerfile
+++ b/src/ci/docker/host-x86_64/dist-x86_64-freebsd/Dockerfile
@@ -13,6 +13,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
   sudo \
   bzip2 \
   xz-utils \
+  texinfo \
   wget \
   libssl-dev \
   pkg-config \
```

**Pull request merged**
