### PR TITLE
Reduce dependence on the target name

### PR DESCRIPTION
**Pull request by bjorn3**
The target name can be anything with custom target specs. Matching on fields inside the target spec is much more robust than matching on the target name.

Also remove the unused is_builtin target spec field.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Thanks!

@bors r+

**Comment by workingjubilee** [comment]
oh whoops.@bors r-

**Comment by bjorn3** [comment]
Updated test.

**Comment by workingjubilee** [comment]
r=me when green

**Pull request merged**
