### PR TITLE
Replace `owning_ref` with a safer datastructure

### PR DESCRIPTION
**Pull request by Noratrieb**
`owning_ref` has soundness problems when used together with `Box<T>`, since moving a box invalidates all pointers to it under stacked borrows.
It's only used in once place, in metadata handling, where it's used to have a subslice view into an owned slice. So this pull request adds a new datastructure, this kind of  `owned_slice`, which gives a subslice view into an owned slice with almost no unsafe code, that passes miri in strict mode.
I replaced the only usage of `owning_ref` with this new datastructure, and then subsequently removed `owning_ref` from `rustc_data_structures`.

### CODE REVIEW

**Comment by Nilstrieb** [comment]
That's not great, but I think I can optimize this.

**Comment by cjgillot** [comment]
I was going to use this in https://github.com/rust-lang/rust/pull/88186 to keep `Lrc`s pointing to sub-items.  Is that unsound?  What do you recommend as a replacement?

**Comment by Nilstrieb** [comment]
Hmm, using it with `Lrc` is not really unsound currently as far as I know, since `Rc`/`Arc` don't have the magic of `Box` currently. So it should be fine. If keeping `owning_ref` is desired, I will not remove it here. But since it's used together with `Box` here right now, it is unsound, and should be changed. 

Though, now that I think about it, it might be a better idea to add a `AliasableBox<T>` datastructure here, that behaves like `Box<T>` except without the aliasing magic that makes an `owning_ref` of it unsound. This way we could keep the current behaviour with `owning_ref` and keep `owning_ref`, but making it clear that it should be used with `AliasableBox<T>` instead.

**Comment by ibraheemdev** [comment]
Could also use `ouroboros` which is based on `aliasable::AliasableBox`.

**Comment by bjorn3** [comment]
> owning_ref has soundness problems when used together with Box<T>, since moving a box invalidates all pointers to it under stacked borrows.

Would it make sense to remove the `StableDeref` impl for `Box<T>` then?

**Comment by Nilstrieb** [comment]
Yes. Under stacked borrows (currently), box does not obey the rules of stable deref.

**Comment by petrochenkov** [comment]
Allocating on the heap is the standard way to ensure address stability, and `Box` is a standard way to allocate on the heap.
So it's kind of questionable that we have to do it at all.

**Comment by bjorn3** [comment]
I believe rustc only uses owning ref with `Vec<u8>`, `Arc<[u8]>` and `Mmap`.

**Comment by Nilstrieb** [comment]
This `Mmap` is a boxed trait object IIRC (for the metadata)

**Comment by bjorn3** [comment]
No, it is either an memmap2::Mmap or an Vec<u8> depending on the target: https://github.com/rust-lang/rust/blob/d7b8d77be5b4a091fe99c2f32b1334b931a2f4aa/compiler/rustc_data_structures/src/memmap.rs#L9 memmap2::Mmap contains a raw pointer, not Box.

**Comment by Nilstrieb** [comment]
In `rustc_data_structures/src/sync.rs` (I can't link it I'm on mobile)

```rust
pub type MetadataRef = OwningRef<Box<dyn Erased + Send + Sync>, [u8]>;
```

Here a box is used

**Comment by bjorn3** [comment]
Right. The `Box<dyn Erased>` may be replacable with `Mmap`. Or alternatively a new type for erased owners that doesn't use Box could be added.

**Comment by apiraino** [comment]
Switching to waiting on author based on this [comment](https://github.com/rust-lang/rust/pull/97770#issuecomment-1147107884). Feel free to request a review when ready, thanks!

@rustbot author

**Comment by Nilstrieb** [comment]
I'll block this on the hope that we can make box aliasable, therefore making this PR useless. If that doesn't happen, I'd add an AliasableBox and use that with the owning_ref here.

**Comment by JohnCSimon** [comment]
Ping from triage: 
> I'll block this on the hope that we can make box aliasable, therefore making this PR useless. If that doesn't happen, I'd add an AliasableBox and use that with the owning_ref here.

@Nilstrieb What is the status of this PR? If you're not moving forward with this please close it.

**Comment by Nilstrieb** [comment]
I'll close it for now, I might pick it up in the future again depending on what happens with box.

**Pull request closed without merging**
