### PR TITLE
derive: clean up hygiene

### LINKED ISSUE #2810: deriving cleanup
* Hygiene
* Search for "__" strings
* Don't assume ```std``` is the standard library

(from a FIXME in ```syntax::ext::deriving```)

### PR DESCRIPTION
**Pull request by durka**
derive: clean up hygiene

Fixes #2810.

Spawned from #32139.

r? @alexcrichton

### CODE REVIEW

**Comment by Manishearth** [comment]
This broke warnings:

```rust
#![deny(warnings)]

#[derive(Hash)]
struct Foo;

fn main() {}
```

will now throw a warning/error about an unused argument. Please keep the `__`s in derive, they're there for a reason.

**Comment by durka** [comment]
Bleh, you're right. The reason was assumed to be hygiene, but it's also
unused arguments/variables. It would be more conventional to have one
underscore, I guess. I can make that change or we can just revert this.

On Wed, Mar 16, 2016 at 2:41 PM, Manish Goregaokar <notifications@github.com

**Comment by Manishearth** [comment]
Yep. Double underscore is slightly better IMO since clippy uses that to distinguish between things that are silenced because they _may_ be unused (e.g. when they come from a macro), and things which are known to be unused. But single underscore is also ok.

**Comment by Manishearth** [comment]
See https://github.com/rust-lang/rust/issues/32292

**Comment by Manishearth** [comment]
Should the fix just re-add underscores to the idents introduced in this PR? I'm not entirely sure if that's all that needs to be done.

**Comment by durka** [comment]
Yeah, I should just re-add double underscores I think. The other improvements in this PR are turning an if-else into match (was a FIXME in the code) and making it harder for the derived type parameter to cause a collision, neither of which are critical.

**Comment by Manishearth** [comment]
Cool. I'm working on it.

**Comment by durka** [comment]
Oh okay, well thanks for cleaning up my mess :)

On Wed, Mar 16, 2016 at 2:51 PM, Manish Goregaokar <notifications@github.com

**Pull request merged**
