### PR TITLE
Fix tidy check

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Everytime I tried to start on it my computer I got a lot of errors (not coming from my code). With this, it works.

### CODE REVIEW

**Comment by kennytm** [comment]
`binaryen` should no longer exist. Please `git status` and remove the stale folders.

**Comment by GuillaumeGomez** [comment]
Ok so that just left the `rust-installer` one. :)

**Comment by kennytm** [comment]
I'm still confused that `rust-installer` will trip tidy. Are you sure that:

1. The only occurrence of `rust-installer` is `src/tools/rust-installer`, and
2. The submodule `src/tools/rust-installer` is up-to-date (at commit 118e078c5badd520d18b92813fd88789c8d341ab) and completely clean (no any untracked files)?

**Comment by Mark-Simulacrum** [comment]
It's also worth noting that rust-installer *used to* have submodules of its own I believe, but doesn't anymore-- so you make want to `rm -rf src/tools/rust-installer` and then `git submodule update --init src/tools/rust-installer` as that should ensure it's the same as in-tree.

**Comment by GuillaumeGomez** [comment]
Yep, that fixed it. Sorry for the noise then...

**Pull request closed without merging**
