### PR TITLE
Correctly mark the ending span of a match arm

### LINKED ISSUE #74050: Strange span in borrow error in nested match.
I tried this code:

```rust
fn main() {
    let mut args = std::env::args_os();
    let _arg = match args.next() {
        Some(arg) => {
            match arg.to_str() {
                Some(s) => s,
                None => return,
            }
        }
        None => return,
    };
}
```

Previously, in 1.36 or earlier, it presented an error like this:

```
error[E0597]: `arg` does not live long enough
  --> src/main.rs:7:19
   |
5  |     let _arg = match args.next() {
   |         ---- borrow later stored here
6  |         Some(arg) => {
7  |             match arg.to_str() {
   |                   ^^^ borrowed value does not live long enough
...
13 |     };
   |     - `arg` dropped here while still borrowed
```

Starting with 1.37, the "dropped here while still borrowed" message points to an odd location:

```
error[E0597]: `arg` does not live long enough
  --> src/main.rs:7:19
   |
5  |     let _arg = match args.next() {
   |         ---- borrow later stored here
6  |         Some(arg) => {
7  |             match arg.to_str() {
   |                   ^^^ borrowed value does not live long enough
...
12 |         None => return,
   |            - `arg` dropped here while still borrowed
```

The earlier error looks more correct to me.

Bisected the change to [nightly-2019-05-24](https://github.com/rust-lang/rust/compare/37ff5d388f8c004ca248adb635f1cc84d347eda0...8869ee03d7f258e1b76a11c6fbb01b5708a9f504), I would guess maybe it is #60174.

### PR DESCRIPTION
**Pull request by ayazhafiz**
Closes #74050

r? @matthewjasper

### CODE REVIEW

**Review by matthewjasper — APPROVED** [review]
Thanks, this looks good, r=me with commits squashed

**Comment by ayazhafiz** [comment]
@matthewjasper can you r+ for bors

**Pull request merged**
