### PR TITLE
Remove the `NodeId` of `ast::ExprKind::Async`

### PR DESCRIPTION
**Pull request by Swatinem**
This is a followup to https://github.com/rust-lang/rust/pull/104833#pullrequestreview-1314537416.

In my original attempt, I was using `LoweringContext::expr`, which was not correct as it creates a fresh `DefId`.
It now uses the correct `DefId` for the wrapping `Expr`, and also makes forwarding `#[track_caller]` attributes more explicit.

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
@bors r+

**Comment by Swatinem** [comment]
Hm, @bors seems to be stuck?

**Pull request merged**
