### PR TITLE
[LLVM 4.0] Use 32-bits for alignment

### PR DESCRIPTION
**Pull request by dylanmckay**
LLVM 4.0 changes this. This change is fine to make for LLVM 3.9 as we
won't have alignments greater than 2^32-1.

### CODE REVIEW

**Comment by nagisa** [comment]
All those casts make me uneasy. The functions called and variables used should become u32 in the first place IMO.

**Comment by rkruppe** [comment]
Yes, rustc should just follow LLVM's example and always compute and store alignments as 32 bit numbers.

**Comment by dylanmckay** [comment]
There are two cases of casts that I've touched

* Cases of `bytes_to_bits(align)`. This function returns a `u64`. I can't make it return a `u32` because the function is also uses for 64-bit sizes. One option is to make the function generic over numeric types.
* Cases of `variable as u32`. All instances that I changed already were casting `type_of::align_of` from `usize` to `u32`, which seems unavoidable.

**Comment by rkruppe** [comment]
I think it makes sense to change `bytes_to_bits` to return the type of the argument, and then change all the computations of alignments (in bytes) that are fed to `bytes_to_bits` to use u32.

**Comment by dylanmckay** [comment]
@rkruppe: I've removed all of the casts. It turns out that the `llalign` type was _already_ `u32` so the change was quite trivial.

**Review by hanna-kruppe — APPROVED** [review]
LGTM, thanks! r=me, unless the people with bors rights would rather see @nagisa confirm.

**Comment by dylanmckay** [comment]
Ping

**Pull request merged**
