### PR TITLE
idiom lints for removing `extern crate`

### LINKED ISSUE #48719: `extern crate` epoch lint for Path Clarity RFC (2126)
We need to add an epoch lint for [RFC 2126](https://github.com/rust-lang/rfcs/blob/master/text/2126-path-clarity.md)

It will lint `extern crate foobar;`, suggesting removal in root mods, and replacement with `use foobar;` in non-root mods.

This is blocked on the ability to elide extern crate in the first place.

### PR DESCRIPTION
**Pull request by Manishearth**
Based off of https://github.com/rust-lang/rust/pull/49789

This contains two lints:

 - One that suggests replacing pub extern crates with pub use, and removing non-pub extern crates entirely
 - One that suggests rewriting `use modulename::...::cratename::foo` as `cratename::foo`

The latter is a bit tricky to emit suggestions for; for one this involves splicing spans (never a good idea), and it also won't be able to correctly
handle `use module::{cratename, foo}` and use-trees. I'm not sure how to proceed here. Currently it doesn't suggest anything at all.

Perhaps we can go the other way and suggest removal of all extern crates _except_ those used through modules (stash node ids somewhere) and suggest replacing those with `<visibility> use`?

r? @nikomatsakis

fixes https://github.com/rust-lang/rust/issues/48719

### CODE REVIEW

**Comment by alexreg** [comment]
I don't see why the second lint is problematic to implement. Could you elaborate?

**Comment by Manishearth** [comment]
The path could be part of a larger path like `use module::foo::bar::{cratename, baz}`.

Also, we don't have a way of getting the span information of "this path up to this segment", we have to add and subtract spans for this (which is _super_ fragile)

**Comment by Manishearth** [comment]
To be clear, the lint itself is easy to do (it's implemented already), it's the suggestion that's tricky

**Comment by alexreg** [comment]
Ahh, I see. Well, maybe a vague lint for now would be the best approach?

**Comment by Manishearth** [comment]
@alexreg edition stuff must have suggestions.


But we're actually ditching that part of the lint anyway, so this isn't a problem anymore.

**Comment by nikomatsakis** [comment]
So @aturon and I sketched out a migration plan in [this paper document here](https://paper.dropbox.com/doc/module-path-linting-plans-rt0aTyuKqqPMoOlFrBa1m). I'm trying to figure out how this PR relates to that.

**Comment by Manishearth** [comment]
I'm going to defer making this lint bail on cases where the crate contains a module that shadows a crate since that's not so important for now. @alexreg woudl you be interested in working on this? I'll file a bug once I'm done.

**Comment by Manishearth** [comment]
r? @nikomatsakis 

Deferring that minor bit of the lint to later

**Comment by alexreg** [comment]
@Manishearth Sure, I can have a stab at that.

**Comment by Manishearth** [comment]
Actually I realized it may not be necessary (See [comment discussion](https://paper.dropbox.com/doc/module-path-linting-plans-rt0aTyuKqqPMoOlFrBa1m?t=158656249986894335388729#:t=158656249986894335388729))

**Comment by alexreg** [comment]
@Manishearth Didn't quite understand your reasoning. I still see the possibility of a clash with a module name.

**Comment by Manishearth** [comment]
Can you give a concrete example?

**Comment by Manishearth** [comment]
Note that we already have a fallback mechanism for inline paths. If you do `foo::bar` in an inline path it will search the local module for `foo` _first_, and then the crates.

**Comment by alexreg** [comment]
@Manishearth Hmm, maybe you're right. If there is a name clash after this lint is applied, then there was still a name clash before.

**Review by nikomatsakis — APPROVED** [review]
r=me but I think there is some question as to whether it is better to replace extern crate with `use` -- I guess overall it is better, that much less to understand.

**Comment by alexreg** [comment]
Either an ephemeral error or the "apple-alt" build server is down?

**Pull request merged**
