### PR TITLE
[r+] Return passed value from black_box

### PR DESCRIPTION
**Pull request by amaranth**
By returning the passed value black_box can be used on data being
passed to a function being benchmarked. This ensures the compiler
does not optimize the function for the input which could result in
the entire function being optimized away.

### CODE REVIEW

**Comment by amaranth** [comment]
I'm trying to do perlin2(&seed, black_box(&[0.0f32, 0.0])) to prevent the compiler from optimizing away perlin2 by knowing what its inputs are. There is currently no way to do this.

**Comment by huonw** [comment]
It can be done now, via

```rust
let data = [0.0f32, 0.0];
black_box(&mut data); // doesn't mutate, but LLVM doesn't know
perlin2(&seed, &data);
```

**Comment by huonw** [comment]
That said, that trick is somewhat annoying; I have certainly thought about making the same change as performed here to be able fluently opaquify values.

**Comment by reem** [comment]
I was actually surprised that LLVM doesn't have a 0-cost intrinsic for this, since tricks like this do have the potential to slow down benchmarks (memcpy/memset(0)).

**Comment by thestinger** [comment]
Use volatile inline assembly?

**Comment by thestinger** [comment]
Inline assembly seems like it would work, as long as it's passed the right stuff.

**Comment by nikomatsakis** [comment]
I guess I have no strong objection. Seems nice to be able to use it fluently.

**Comment by amaranth** [comment]
Is there something more needed for this? If I'm reading github correctly it doesn't need a rebase still.

**Comment by alexcrichton** [comment]
The [automated tests failed](http://buildbot.rust-lang.org/builders/auto-mac-64-nopt-t/builds/3014/steps/test/logs/stdio) and will need to be fixed before another r+ (can be reproduced with `make check`)

**Comment by amaranth** [comment]
Weird, those didn't fail locally, guess the already existing failure on OS X hid them from me. The build log said it was killed so I thought maybe it just didn't get a chance to run the tests.

**Comment by amaranth** [comment]
I think I've got the test failures sorted out, things pass locally now at least.

**Pull request merged**
