### PR TITLE
Add ty convs for smir refs and ptrs

### PR DESCRIPTION
**Pull request by ericmarkmartin**
r? @spastorino

### CODE REVIEW

**Comment by spastorino** [comment]
This looks good, please rebase.

**Comment by ericmarkmartin** [comment]
@spastorino I rebased but CI seems to be unhappy

**Comment by spastorino** [comment]
@ericmarkmartin I'm not sure what happened, it seems that Mark force pushed into master. I'd say, try rebasing again now because as I'm seeing this PR is not correctly rebased on top of the current master. Likely that force push.

**Pull request merged**
