### PR TITLE
Add `String::replace_first` and `String::replace_last`

### PR DESCRIPTION
**Pull request by WilliamVenner**
Convenience methods that use `match_indices` and `replace_range` to efficiently replace a substring in a string without reallocating, if capacity (and the implementation of `Vec::splice`) allows.

### CODE REVIEW

**Comment by WilliamVenner** [comment]
`String::replace_last` is currently blocked by #89196 :[

For now I have manually specified the types in the test and doctest, but these should of course be omitted once the issue is resolved.

**Comment by JohnCSimon** [comment]
@WilliamVenner 
Returning to you to address build failres


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot author

**Comment by JohnCSimon** [comment]
@WilliamVenner 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Comment by WilliamVenner** [comment]
??? This is blocked by #98941 @JohnCSimon

**Comment by JohnCSimon** [comment]
@WilliamVenner sorry - my mistake, reopened.

**Comment by zachs18** [comment]
https://github.com/zachs18/rust/tree/string_replace_in_place_rebase
I have a branch with this PR's changed rebased onto current `master` that also somewhat avoids the blocking issue by hardcoding the doclink to `../../std/primitive.str.html#method.replacen` instead of using intra-doc links. The effect of this is that the doclink is only broken if you build `alloc`'s docs *and not* `std`'s docs.

**Comment by WilliamVenner** [comment]
@zachs18 Thank you 🙂

**Comment by alex-semenyuk** [comment]
@WilliamVenner
From wg-triage. Do you have any updates on this PR?

**Comment by alex-semenyuk** [comment]
@WilliamVenner
From wg-triage. Closed this PR due to inactivity. Feel free to reopen or raised new one. Thanks for your efforts.

**Pull request closed without merging**
