### PR TITLE
Update rustc-guide

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @ehuss

### CODE REVIEW

**Comment by mark-i-m** [comment]
Seems that clippy/miri are not building? Rebased.

**Comment by ehuss** [comment]
> 2019-09-06T18:16:51.1573292Z thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("Unable to create missing chapters"), State { next_error: Some(Error(Io(Os { code: 30, kind: Other, message: "Read-only file system" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1084:5 


It looks like some chapters were deleted, but they were not removed from SUMMARY.md.

**Comment by mark-i-m** [comment]
This passes locally for me. In the past, we did have that problem, but it should be correct now. The error "Read-only file system" is a bit weird.

**Comment by ehuss** [comment]
> it should be correct now.

I think this PR needs to update the submodule to 941968db2fd9c85788a4f971c8e425d46b4cb734 to pick up https://github.com/rust-lang/rustc-guide/pull/439 to make it pass.  Since the docker volume is mounted readonly, it protects against issues like this where the source tree is modified.

**Comment by mark-i-m** [comment]
Huh? I thought I had. Just pushed.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/64257#issuecomment-529130862, @bors r-

**Comment by mark-i-m** [comment]
@ehuss That looks like a transient failure. It is still passing locally.

@Centril In future, I don't think we should attempt to rollup rustc-guide updates, as they have a chance of spurious failures that could frustrate the rollup.

**Comment by mark-i-m** [comment]
Also rebased.

**Pull request merged**
