### PR TITLE
Run rustfmt on build_helper

### PR DESCRIPTION
**Pull request by topecongiro**
Using rustfmt 0.4.1-nightly (e784712f 2018-04-09).

### CODE REVIEW

**Comment by varkor** [comment]
I really don't think this is an improvement. There are some rough conventions in rustc that these changes are inconsistent with (e.g. alignment for wrapped expressions). rustfmt is not the final word when it comes to correctness.

I don't necessarily think we want strict style guidelines, but perhaps there should be some statement regarding reformatting, because this doesn't seem to be uncommon, but I think blindly running rustfmt throughout rustc is not the right thing to do.

**Comment by sinkuu** [comment]
Isn't "conventions in rustc" what rustfmt just used to have without consensus, and is being revised by formatting RFCs? This repository have been applied rustfmt some years ago: https://github.com/rust-lang/rust/pulls?page=3&q=is%3Apr+run+rustfmt+is%3Aclosed&utf8=%E2%9C%93

**Comment by topecongiro** [comment]
I thought the idea was to eventually replace the current tidy check with rustfmt, so incrementally running rustfmt is good, but this is not true anymore?

r? @nrc

**Comment by nrc** [comment]
> I thought the idea was to eventually replace the current tidy check with rustfmt, so incrementally running rustfmt is good, but this is not true anymore?

'replace tidy' is a bit complicated because it does stuff like the license check and iirc some test-specific stuff. However, we absolutely do want to be running rustfmt on the compiler and on CI, so landing PRs like this is desirable. (In the past they've been hard to review and land due to conflicts, so it might be better to just close the tree and reformat the world some day, but it is useful to find out how well rustfmt it performing in the meantime).

**Comment by topecongiro** [comment]
Rebased to resolve the conflict.

**Pull request merged**
