### PR TITLE
Check privacy of trait items in all contexts

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/28514

This is a sufficiently rare scenario and it's currently guarded by `private_in_public` lint, so it shouldn't be a [breaking-change] in practice.

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by eddyb** [comment]
The changes LGTM, started a crater run to see if there's any real impact.

**Comment by eddyb** [comment]
Sadly, Crater now outputs `error: TypeError: Cannot call method 'trim' of undefined`.
I had a successful run just a couple days ago, not sure what, if anything, changed. cc @brson

**Comment by eddyb** [comment]
Paging @brson again, to make sure he sees it when he gets back.

**Comment by nagisa** [comment]
@eddyb Did you try again since?

**Comment by brson** [comment]
I fixed a bug in crater that should make it work again, and started crate builds for commits fef1026bae4a0cc59c4bd204021eea4e1a976b4f and 4f7ab0ec0ff580e750264101a577b9a078471174. It should be done in a few hours if nothing else goes wrong.

**Comment by brson** [comment]
https://gist.github.com/anonymous/dc7effc2a956c5eac26a804c75f315f1

**Comment by petrochenkov** [comment]
Conflict with recently merged https://github.com/rust-lang/rust/pull/41494, will fix today.

**Comment by Mark-Simulacrum** [comment]
Probably spurious failure, have not yet filed new issue though because uncertain (confirming on IRC).

@bors retry

```
 Downloading utf8-ranges v0.1.3
error: unable to get packages from source
Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/utf8-ranges/0.1.3/download`, got 500
thread 'main' panicked at 'tests failed for https://github.com/BurntSushi/xsv', src\tools\cargotest\main.rs:78
note: Run with `RUST_BACKTRACE=1` for a backtrace.
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-tools\\x86_64-pc-windows-msvc\\release\\cargotest.exe" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "C:\\projects\\rust\\build\\ct"
expected success, got: exit code: 101
```

**Pull request merged**
