### PR TITLE
Update E0453 to new error format

### LINKED ISSUE #35929: E0453 needs to be updated to new format
From: src/test/compile-fail/E0453.rs

E0453 needs a span_label and a span_note changed to a span_label, updating it from:

```
error[E0453]: allow(non_snake_case) overruled by outer forbid(non_snake_case)
  --> src/test/compile-fail/E0453.rs:13:9
   |
13 | #[allow(non_snake_case)] //~ ERROR E0453
   |         ^^^^^^^^^^^^^^
   |
note: `forbid` lint level set here
  --> src/test/compile-fail/E0453.rs:11:11
   |
11 | #![forbid(non_snake_case)]
   |           ^^^^^^^^^^^^^^
```

To:

```
error[E0453]: allow(non_snake_case) overruled by outer forbid(non_snake_case)
  --> src/test/compile-fail/E0453.rs:13:9
   |
11 | #![forbid(non_snake_case)]
   |           -------------- `forbid` level set here
12 |
13 | #[allow(non_snake_case)] //~ ERROR E0453
   |         ^^^^^^^^^^^^^^ overruled by previous forbid
```

### PR DESCRIPTION
**Pull request by 0xmohit**
Fixes #35929.
Part of #35233.

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Comment by jonathandturner** [comment]
@bors r-

I'll stop approving while you work ;)  Just ping me again when you're ready.  If you would, please squash the PRs.

**Comment by 0xmohit** [comment]
@jonathandturner Done.  Moral of the story: _always_ test before submitting a PR ;)

**Comment by jonathandturner** [comment]
@0xmohit - I've learned that one... *many* times ;)

@bors r+ rollup

**Comment by 0xmohit** [comment]
The failure appears due to a test in src/test/compile-fail-fulldeps/.  Figuring.

**Comment by jonathandturner** [comment]
For those I think you may need to test against check-cfail-full. Possibly at stage 2

**Comment by 0xmohit** [comment]
Tested against both `check-cfail` and `check-cfail-full`; things seem to be ok.  PTAL.

**Comment by jonathandturner** [comment]
Great.  Let's give it a try.

@bors r+ rollup

**Pull request merged**
