### PR TITLE
Subtree update of `rust-analyzer`

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
CC @RalfJung I guess this looks all right, but it's the first unpaired PR (no `rustc-pull` today), hope that's fine.

image

And bors should probably include the repo name in the commit messages, this is pretty confusing :joy:.

**Comment by RalfJung** [comment]
>  I guess this looks all right, but it's the first unpaired PR (no rustc-pull today), hope that's fine.

Hard for me to say without knowing the history. The key thing to check is that this does not duplicate any commit that was pushed in the previous rustc-push. However if that were to happen it would most likely trip the "roundtrip" check.

> And bors should probably include the repo name in the commit messages, this is pretty confusing

Yeah... https://github.com/rust-lang/homu/issues/185, https://github.com/rust-lang/homu/issues/200. Sadly old bors is completely feature-frozen. Happily someone is working on a rewrite -- @Kobzol could new bors use commit messages that make sense even when moved to a new repo? :)

**Comment by lnicola** [comment]
> The key thing to check is that this does not duplicate any commit that was pushed in the previous rustc-push.

Most of them are from last week, I think it's fine.

> new bors use commit messages that make sense even when moved to a new repo?

Would be nice, it didn't include the repo name [back when](https://github.com/rust-lang/rust-analyzer/pull/15847) I tried it.

**Comment by RalfJung** [comment]
@bors retry failed retrieving file 'mingw-w64-i686-libgccjit-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org

(I thought we have our own mirrors of everything to avoid exactly this?)

**Comment by lnicola** [comment]
It's the revenge of `git-subtree`.

**Comment by RalfJung** [comment]
@bors treeclose=100 retry
Failing the third time in a row
```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'mingw-w64-x86_64-gcc-libs-13.2.0-3-any.pkg.tar.zst.sig' from mirror.umd.edu : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
 mingw-w64-x86_64-cmake-3.28.1-1-any downloading...
error: failed retrieving file 'mingw-w64-x86_64-libarchive-3.7.2-1-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-cmake-3.28.1-1-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst' from mirror.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
 mingw-w64-x86_64-openssl-3.2.0-1-any downloading...
 mingw-w64-x86_64-gettext-0.22.4-3-any downloading...
 mingw-w64-x86_64-curl-8.5.0-1-any downloading...
 mingw-w64-x86_64-gcc-libs-13.2.0-3-any downloading...
 mingw-w64-x86_64-libarchive-3.7.2-1-any downloading...
Errors occurred, no packages were upgraded.
```

**Comment by workingjubilee** [comment]
We landed https://github.com/rust-lang/rust/pull/125546 which is supposed to fix this. Let's try unblocking the pipe.

@bors treeclosed-

**Pull request merged**
