### PR TITLE
Fix documentation error

### LINKED ISSUE #75412: DOC: slicing with begin = end?
https://doc.rust-lang.org/std/slice/trait.SliceIndex.html#impl-SliceIndex%3Cstr%3E mentions "Panics [...] if begin > end, or if end > len", which I think is correct.

However, https://doc.rust-lang.org/std/slice/trait.SliceIndex.html#impl-SliceIndex%3Cstr%3E-1 mentions "Panics [...] if begin >= len", which I think is wrong, isn't it?

Shouldn't this be "Panics [...] if begin > len"?

The current stable compiler doesn't seem to create a panicking program when I use "begin = len".

The documentation for slice slicing doesn't mention anything at all: https://doc.rust-lang.org/std/slice/trait.SliceIndex.html#impl-SliceIndex%3C%5BT%5D%3E-2.

It would be great to have the (correct) description there as well.

I think this has already been fixed in #32099 and #32183 (more than 4 years ago), but it seems to have gotten lost again since then?

Or am I missing something?

### PR DESCRIPTION
**Pull request by jack-champagne**
This should fix #75412. Just a quick >= to > sign replacement.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Thanks, looks good :)

**Comment by jack-champagne** [comment]
Might I ask why homu has a job named "mark job as failure" with the command `exit 1` to always throw a failed signal? I know this is not on-topic for completing this PR, I can move this to discord to discuss with someone who has the answer to this.

**Comment by JohnTitor** [comment]
> Might I ask why homu has a job named "mark job as failure" with the command exit 1 to always throw a failed signal? I know this is not on-topic for completing this PR, I can move this to discord to discuss with someone who has the answer to this.

Because we cannot tell homu that the build failed without it in GHA. If you have further questions, feel free to ask on the Zulip stream: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra

**Comment by jack-champagne** [comment]
> 
> 
> > Might I ask why homu has a job named "mark job as failure" with the command exit 1 to always throw a failed signal? I know this is not on-topic for completing this PR, I can move this to discord to discuss with someone who has the answer to this.
> 
> Because we cannot tell homu that the build failed without it in GHA. If you have further questions, feel free to ask on the Zulip stream: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra

Thanks, understood

**Pull request merged**
