### PR TITLE
[beta] backport #48181 and #48362

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by cuviper** [comment]
PR links since GitHub doesn't parse titles: #48181 #48362

**Comment by alexcrichton** [comment]
@bors: retry

standard timeouts

**Comment by kennytm** [comment]
@bors retry 

30-minute no output with `check i686-apple-darwin` 

```
[02:15:35] test net::tcp::tests::fast_rebind ... test net::tcp::tests::fast_rebind has been running for over 60 seconds

[02:15:55] thread '<unnamed>' panicked at 'received error for `TcpStream::connect(&addr)`: Operation timed out (os error 60)', libstd/net/tcp.rs:1185:17



No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Pull request merged**
