### PR TITLE
Remove helper-methods from Alloc trait and add associated Err type.

### PR DESCRIPTION
**Pull request by lachlansneff**
This PR removes the `alloc_one`, `dealloc_one`, `alloc_array`, and `dealloc_array` methods from the `Alloc` trait (as discussed in [wg-allocators/#18](https://github.com/rust-lang/wg-allocators/issues/18)) and adds an associated `Err` type (as discussed in [wg-allocators/#23](https://github.com/rust-lang/wg-allocators/issues/23)).

The `CollectionAllocErr` enum is now generic on `E`, the error type.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
ping from triage @aidanhs waiting for your review on this @lachlansneff you have failing tests to resolve.

**Comment by jonas-schievink** [comment]
Ping from triage again! Same status as last time, I believe. @lachlansneff can you address the test failure?

**Comment by Dylan-DPC** [comment]
ping from triage 
r? @SimonSapin

**Comment by SimonSapin** [comment]
I don’t believe there is consensus so far for adding this associated type. (Or that the Allocators WG really has a way to reach it at all, yet. See https://github.com/rust-lang/wg-allocators/issues/20.) So implementing that change doesn’t seem appropriate to me at this time.

As already argued in other threads, I personally don’t feel that having implementations of the `Alloc` trait return `Result<_, !>` is ever desirable. Instead, I would prefer that calling `handle_alloc_error` is the responsibility of separate APIs that wrap a generic `A: Alloc` handle, or take it as a parameter.

As to a non-zero-size inhabited error type, as far as I know we have yet to see a concrete use case for an allocator implementation to provide more information about a failure. This feels like a theoretical exercise is making a maximally general API.

-----

Removing default methods on the other hand sounds fine to me. They would be easy to restore later if we decide to.

**Comment by Dylan-DPC** [comment]
thanks. marking this as "waiting on team" till there is some consensus on the associated type

**Pull request closed without merging**
