### PR TITLE
Add std::sync::mpsc::Receiver::recv_deadline()

### PR DESCRIPTION
**Pull request by ia0**
Essentially renames recv_max_until to recv_deadline (mostly copying recv_timeout
documentation). This function is useful to avoid the often unnecessary call to
Instant::now in recv_timeout (e.g. when the user already has a deadline). A
concrete example would be something along those lines:

```rust
use std::sync::mpsc::Receiver;
use std::time::{Duration, Instant};

/// Reads a batch of elements
///
/// Returns as soon as `max_size` elements have been received or `timeout` expires.
fn recv_batch_timeout<T>(receiver: &Receiver<T>, timeout: Duration, max_size: usize) -> Vec<T> {
    recv_batch_deadline(receiver, Instant::now() + timeout, max_size)
}

/// Reads a batch of elements
///
/// Returns as soon as `max_size` elements have been received or `deadline` is reached.
fn recv_batch_deadline<T>(receiver: &Receiver<T>, deadline: Instant, max_size: usize) -> Vec<T> {
    let mut result = Vec::new();
    while let Ok(x) = receiver.recv_deadline(deadline) {
        result.push(x);
        if result.len() == max_size {
            break;
        }
    }
    result
}
```

### CODE REVIEW

**Comment by kennytm** [comment]
Thanks for the PR! We’ll periodically check in on it to make sure that @Kimundi or someone else from the team reviews it soon.

**Comment by ia0** [comment]
Thanks for the feedback!

**Comment by alexcrichton** [comment]
Thanks for the PR @ia0! In general we never land new APIs as `#[stable]` so this'll want to switch to using `#[unstable]` along with a tracking issue for the API itself (I can tag it if you cc me on the issue).

Overall I like the idea of `Instant`-taking APIs to complement the `Duration`-taking APIs as well. I think it would be especially beneficial to do this for APIs like `Condvar` and `std::thread` in addition too. The tracking issue I think could be a good location to game out conventions here for more functions in the standard library and maybe even have a checklist for functions to implement.

**Comment by ia0** [comment]
Thanks for your review @alexcrichton! I created #46316 to track a possible API convention for blocking-, timeout-, and deadline-related functions.

I switched to an unstable feature. And actually I wonder if I shouldn't have done the same for #45506 then.

**Comment by alexcrichton** [comment]
Awesome, thanks @ia0! I'll comment on that soon.

It looks like tests are failing though? I think the doctests here will need to be tagged with the `#![feature]` directive

**Comment by ia0** [comment]
Indeed, I forgot to update the tests. It should be fixed now (at least locally `./x.py test src/libstd --stage=1` is not failing anymore).

**Comment by ia0** [comment]
Thanks for the review and explanation about impl stabilization.

The homu test seems to have failed because the build of LLVM for x86_64-apple-darwin seems to fail because `future_error` is unavailable:
```
[00:12:30] In file included from /Users/travis/build/rust-lang/rust/src/llvm/lib/Support/ThreadPool.cpp:14:
[00:12:30] In file included from /Users/travis/build/rust-lang/rust/src/llvm/include/llvm/Support/ThreadPool.h:30:
[00:12:30] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:1447:23: error: 'future_error' is unavailable: introduced in macOS 10.8
[00:12:30]                       future_error(make_error_code(future_errc::broken_promise))
[00:12:30]                       ^
[00:12:30] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:502:63: note: 'future_error' has been explicitly marked unavailable here
[00:12:30] class _LIBCPP_EXCEPTION_ABI _LIBCPP_AVAILABILITY_FUTURE_ERROR future_error
[00:12:30]                                                               ^
```
The other tests seem to have been cancelled.

**Pull request merged**
