### PR TITLE
Optimize obligation gathering.

### PR DESCRIPTION
**Pull request by nnethercote**
By passing in a `&mut Vec` in various places and appending to it, rather
than building many tiny `Vec`'s and then combining them.

This removes about 20% of the allocations occurred in a `check` build of
a test program from #87012, making it roughly 3-5% faster.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

r=me presuming perf looks good on other benchmarks

**Comment by nnethercote** [comment]
Some weirdly large changes that I'll have to look at next week. Note that this change isn't expected to have much effect on existing benchmarks.

**Comment by jyn514** [comment]
FWIW a bunch of rustdoc PRs were also getting nonsensical results like this so I think it might just be a bug in the perf suite somehow.

**Comment by Mark-Simulacrum** [comment]
@bors try @rust-timer queue

rerunning now that we've landed https://github.com/rust-lang/rustc-perf/pull/1123

**Comment by nnethercote** [comment]
I wasn't expecting much change on the rustc-perf benchmarks, because this change is aimed at the example from #87012. But there are more improvements than regressions, which seems fine.

**Comment by nnethercote** [comment]
Note: this might not be worthwhile once #92044 lands. We should re-evaluated then.

**Comment by Mark-Simulacrum** [comment]
Blocked on #92044, will mark as waiting on author.

**Comment by nnethercote** [comment]
I was seeing consistent small wins locally, in a non-PGO build, but the CI results are not good. Time to give up on this one.

**Pull request closed without merging**
