### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by JohnTitor**
Successful merges:

 - #91243 (Don't treat unnormalized function arguments as well-formed)
 - #91250 (Refactor EmitterWriter::emit_suggestion_default )
 - #91317 (tests: Ignore `test/debuginfo/rc_arc.rs` on windows-gnu)
 - #91323 (CTFE: support assert_zero_valid and assert_uninit_valid)
 - #91358 (Fix small typo)
 - #91360 (:arrow_up: rust-analyzer)
 - #91368 (Don't re-export `MirPass`)
 - #91383 (Add `drop_while` as doc alias to `Iterator::skip_while`)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=91243,91250,91317,91323,91358,91360,91368,91383)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Probably due to https://github.com/rust-lang/rust/pull/91243, but not very clear.

**Comment by JohnTitor** [comment]
> Probably due to #91243, but not very clear.

Yeah, the original PR, #88312, has some large perf-regressions so it should be related, I missed that. @Mark-Simulacrum Should I run perf-check to make sure it?

**Comment by Mark-Simulacrum** [comment]
I don't think it's worth it for an improvement, so I wouldn't spend time on it.

**Pull request merged**
