### PR TITLE
update mdbook

### PR DESCRIPTION
**Pull request by steveklabnik**
This includes search for all books, a long-requested feature!

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems pretty safe to include it so let's go!

@bors: r+ rollup

**Comment by mattico** [comment]
Note that there are a [few relatively minor issues](https://github.com/rust-lang-nursery/mdBook/pull/648) related to the search CSS/JS. It shouldn't be too long until there's another release that includes those fixes. I'll try to remember to send a PR updating MDBook again when that happens.

**Comment by steveklabnik** [comment]
Rebased!

**Comment by GuillaumeGomez** [comment]
Then let's give it another try!

@bors: r+ rollup

**Comment by Mark-Simulacrum** [comment]
Uh, @bors rollup- perhaps?

**Pull request merged**
