### PR TITLE
Alternate fix for issue #24085

### PR DESCRIPTION
**Pull request by bkoropoff**
This implements my suggestion in #24360 of throwing inference variables at the problem instead.  It works, though at the cost of making inference do more work.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hmm, I definitely prefer this version. I was just planning to checkout your other branch and dig more deeply and try to make sure I understood what was happening! I'll do that anyway.

**Comment by nikomatsakis** [comment]
OK, so I dug into this test. I think the bug has to do with one of the darker corners of region inference (the "givens" field, specifically). I have a fix that extends the current hack, but it's really getting high time to rewrite the region inference code -- and in particular the way it handles closures.

**Comment by steveklabnik** [comment]
@nikomatsakis @bkoropoff how do you feel about this patch today?

**Comment by nikomatsakis** [comment]
I think we should close this in favor of https://github.com/rust-lang/rust/pull/24527. I've been criminally negligent in not benchmarking and rebasing that. I'll try to get to that today. Sorry @bkoropoff :(

**Pull request closed without merging**
