### PR TITLE
Do not fetch HIR node when iterating to find lint.

### PR DESCRIPTION
**Pull request by cjgillot**
Addresses the regression in https://github.com/rust-lang/rust/pull/101620

### CODE REVIEW

**Comment by cjgillot** [comment]
r? @oli-obk
This PR supersedes https://github.com/rust-lang/rust/pull/101839.

**Comment by the8472** [comment]
> Addresses the regression in https://github.com/rust-lang/rust/pull/101620

Not fully. E.g. the worst-case max-rss regression in `ucd | check | incr-unchanged` is 28%, which isn't recovered by this PR.

**Comment by Mark-Simulacrum** [comment]
And on instruction counts too - this is the contributor to the big jump in [the week summary graphs](https://perf.rust-lang.org/?start=17cbdfd07178349d0a3cecb8e7dde8f915666ced&end=8fd6d03e22fba2930ad377b87299de6a37076074&kind=percentfromfirst&stat=instructions%3Au), which doesn't recover by the end of the week pretty much at all.

**Comment by Mark-Simulacrum** [comment]
@cjgillot I think https://github.com/rust-lang/rust/pull/101839 should be landed until we have a PR that actually restores our performance here to baseline, which this PR didn't do. (Or some discussion should be had about why we're taking a fairly large hit across many benchmarks, including primary ones).

**Pull request merged**
