### PR TITLE
Add test for #75158

### LINKED ISSUE #75158: ICE on gigantic arrays
### Code

```Rust
struct S<T> { x: [T; !0] }

pub fn f() -> usize {
    std::mem::size_of::<S<u8>>()
}

fn main() {
    let x = f();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (6c8927b0c 2020-07-26)
binary: rustc
commit-hash: 6c8927b0cf80ceee19386026cf9d7fd4fd9d486f
commit-date: 2020-07-26
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 10.0
```

The ICE seems to appear on 1.39 and later
Also it looks like it is similar to #71699, but crashes in different place

### Error output

```
error[E0080]: the type `[u8; 18446744073709551615]` is too big for the current architecture
   --> /home/soveu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/intrinsics.rs:981:5
    |
981 |     pub fn size_of<T>() -> usize;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Reported(ErrorReported)', src/librustc_codegen_llvm/intrinsic.rs:290:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (6c8927b0c 2020-07-26) running on x86_64-unknown-linux-gnu

error: aborting due to previous error; 2 warnings emitted

For more information about this error, try `rustc --explain E0080`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0080]: the type `[u8; 18446744073709551615]` is too big for the current architecture
   --> /home/soveu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/intrinsics.rs:981:5
    |
981 |     pub fn size_of<T>() -> usize;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Reported(ErrorReported)', src/librustc_codegen_llvm/intrinsic.rs:290:22
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1117
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1508
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1273
  15: rustc_codegen_llvm::intrinsic::<impl rustc_codegen_ssa::traits::intrinsic::IntrinsicCallMethods for rustc_codegen_llvm::builder::Builder>::codegen_intrinsic_call
  16: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_call_terminator
  17: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
  18: rustc_codegen_ssa::mir::codegen_mir
  19: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  20: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  21: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  22: rustc_codegen_llvm::base::compile_codegen_unit
  23: rustc_codegen_ssa::base::codegen_crate
  24: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  25: rustc_session::utils::<impl rustc_session::session::Session>::time
  26: rustc_interface::passes::start_codegen
  27: rustc_middle::ty::context::tls::enter_global
  28: rustc_interface::queries::Queries::ongoing_codegen
  29: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  30: rustc_span::with_source_map
  31: rustc_interface::interface::create_compiler_and_run
  32: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (6c8927b0c 2020-07-26) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error; 2 warnings emitted

For more information about this error, try `rustc --explain E0080`.

```

</p>
</details>

### PR DESCRIPTION
**Pull request by osa1**
This also shifts some type-size related tests into a new directory, so that we keep the number of files at the root down.

Closes #75158

### CODE REVIEW

**Comment by osa1** [comment]
Need to move the test to somewhere else. It should support `build-fail`. Any ideas where @Mark-Simulacrum ?

**Comment by Mark-Simulacrum** [comment]
Let's create src/test/ui/limits perhaps, and move this test and the related tests there, at least:
* src/test/ui/huge-array-simple-32.rs
* src/test/ui/huge-enum.rs
* src/test/ui/huge-array-simple-64.rs
* src/test/ui/issues/issue-17913.rs
* src/test/ui/consts/issue-55878.rs
* src/test/ui/huge-struct.rs
* src/test/ui/lint/issue-69485-var-size-diffs-too-large.rs

(Found with `rg 'too big for' src/test/ui -t rust -c`, but not manually checked for being a similar error)

cc @petrochenkov https://github.com/rust-lang/rust/issues/73494

**Comment by osa1** [comment]
@Mark-Simulacrum I moved the tests you mention a bunch of others that seem to be checking type size overflows to the new dir `ui/limits`.

**Comment by osa1** [comment]
The test was failing on 32-bit as the limits are different there. Per conventions I added `-64` suffix to the test name and skipped it on 32-bit.

**Pull request merged**
