### PR TITLE
Remove struct_field_attributes feature gate

### PR DESCRIPTION
**Pull request by tirr-c**
Part of #41681. ~This PR only removes the feature gate; this *does not* update any documentations.~ This PR removes the feature gate and the corresponding chapter of the Unstable Book.

I'm not very sure about the changes I made though... Just followed the stabilization guideline.

r? @nikomatsakis

### CODE REVIEW

**Comment by est31** [comment]
> This PR only removes the feature gate; this does not update any documentations.

You have to update the unstable book and remove its chapter on this feature in order for this PR to pass tidy and get merged.

**Comment by nikomatsakis** [comment]
@VBChunguk 

Indeed, as @est31 pointed out, we see this tidy error:

```
[00:03:00] * 134 features
[00:03:00] tidy error: The Unstable Book has a 'language feature' section 'struct_field_attributes' which doesn't correspond to an unstable language feature
[00:03:00] some tidy checks failed
```

@est31, maybe you can write up some brief instructions on what files to edit? We can put them in the forge description.

**Comment by est31** [comment]
> @est31, maybe you can write up some brief instructions on what files to edit?

Its [already documented](https://forge.rust-lang.org/stabilization-guide.html):

```
If any documentation for this feature exists, it should be in the Unstable Book, located at src/doc/unstable-book. Regardless of its existence, the page for the feature gate should be removed.
```

The wording is too much in the *should* and should more be like "needs to be removed". After all its a tidy issue that disallows the PR to be merged.

**Comment by VBChunguk** [comment]
@nikomatsakis @est31 I've removed the chapter from the Unstable Book. It passed tidy checks when I ran it locally. Is this the only thing I should do?

**Comment by est31** [comment]
@VBChunguk I think so, yes. Of course, the (other) docs need to be updated but that can be managed separately.

**Comment by VBChunguk** [comment]
@nikomatsakis @est31 Thanks for helping me on this PR! This is the first time I contribute to such huge project like this.

I should have added tidy checks in the pre-push hook...

**Comment by nikomatsakis** [comment]
@VBChunguk no worries. I submit half-tested stuff all the time. ;) That's what travis is for, the way I see it. :)

**Comment by nikomatsakis** [comment]
I think this all looks right. Thanks @VBChunguk !

**Pull request merged**
