### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth

### CODE REVIEW

**Comment by workingjubilee** [comment]
Need `mingw-check` to pass:

```
  error: function `validate_diag` is never used
    --> src/tools/clippy/clippy_utils/src/diagnostics.rs:41:4
     |
  41 | fn validate_diag(diag: &Diag<'_, impl EmissionGuarantee>) {
     |    ^^^^^^^^^^^^^
     |
     = note: `-D dead-code` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(dead_code)]`
```

**Comment by lqd** [comment]
This doesn't change the compiler, and `nalgebra` is being noisy.

image

@rustbot label: +perf-regression-triaged

**Comment by flip1995** [comment]
@jdonszelmann this includes the Clippy attribute changes, you wanted.

**Comment by jdonszelmann** [comment]
Amazing ,thanks so much!

**Pull request merged**
