### PR TITLE
rustdoc: merge theme css into rustdoc.css

### PR DESCRIPTION
**Pull request by notriddle**
Based on https://github.com/rust-lang/rust/pull/115812#issuecomment-1717960119

Having them in separate files used to make more sense, before the migration to CSS variables made the theme files as small as they are nowadays. This is already how docs.rs and mdBook do it.

WebPageTest comparison page:

https://www.webpagetest.org/video/compare.php?tests=230913_AiDc3F_B9E,230913_AiDc7G_B9B

Filmstrip comparison:

image

Old waterfall:

image

New waterfall:

image

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm not too sure what to think about this change. The gain seems to be very small whereas now everything is in one file. The biggest downside being the rules for the ayu theme which all have to include to `:root` part. I'm not against it, just not sure if this is a good idea to go down this road completely.

An opinion maybe @jsha?

**Comment by GuillaumeGomez** [comment]
Oh that part I already figured out. It's really about maintenance. Also, did you check what happens if someone adds their own theme? Since we won't create the directory anymore, I'm curious how it goes if the folder doesn't exist.

**Comment by GuillaumeGomez** [comment]
Ok, looks all good and square. So as said above, my only concern is about maintenance. I just want @jsha to have a look first before we move forward on this. Nice work in any case! :+1:

**Comment by jsha** [comment]
This looks good to me! Thanks for measuring the TTFP improvement, that'll be nice.

**Comment by GuillaumeGomez** [comment]
Then let's go! Thanks again @notriddle.

@bors r+

**Pull request merged**
