### PR TITLE
Discard region-related bounds from `ParamEnv` when predicate is global

### PR DESCRIPTION
**Pull request by Aaron1011**
This allows us to use global caches in more places, since we can drop
predicates containing inference variables.

### CODE REVIEW

**Comment by petrochenkov** [comment]
r? rust-lang/traits

**Comment by jackh726** [comment]
r=me after perf

**Comment by Aaron1011** [comment]
I'd like to add some tests, and get some additional review, before we merge this. I'm fairly certain that my strategy is sound, but anything involving regions can get pretty tricky.

**Comment by Aaron1011** [comment]
Thinking about this more: `T: MyTrait` does not contain any free regions, but we could have `impl<T: 'static> MyTrait for T {}`, so we **do** need to keep region-related caller bounds involving `T`. I *think* this only applies to `'static`, but I'm not certain.

**Comment by carols10cents** [comment]
This fixes the performance problem in https://github.com/rust-lang/rust/issues/87012!!!!!!!! 🎉 

With `rustc 1.59.0-nightly (e95e084a1 2021-12-19)` and running the test script at https://github.com/integer32llc/rust_issue_87012/tree/one-crate, I'm seeing:

| Item                                             | Self time | % of total time | Time     | Item count | Incremental result hashing time |
|--------------------------------------------------|-----------|-----------------|----------|------------|---------------------------------|
| evaluate_obligation                              | 280.33ms  | 47.149          | 287.99ms | 4043       | 658.76µs                        |

...

Total cpu time: 594.557502ms

But checking out this branch, I see:

| Item                                             | Self time | % of total time | Time     | Item count | Incremental result hashing time |
|--------------------------------------------------|-----------|-----------------|----------|------------|---------------------------------|
| (evaluate_obligation is no longer the top item) |
| evaluate_obligation                              | 9.87ms    | 3.306           | 12.16ms  | 4043       | 558.52µs                        |

...
Total cpu time: 298.680792ms

**Comment by nnethercote** [comment]
@Aaron1011: just to clarify, is this still waiting on the additional tests? Thanks.

**Comment by Aaron1011** [comment]
After thinking about this more, I've become significantly less confident that this is actually sound. I'm going to do some additional investigation this week.

**Comment by carols10cents** [comment]
@Aaron1011 if there's anything I can do to help, please let me know! ❤️

**Comment by Aaron1011** [comment]
After thinking about this more, I think the root of the problem is the way that we canonicalize our obligation to create a `CanonicalPredicateGoal` when invoking `evaluate_obligation`. Currently, we replace all regions (except for `'static`) with canonical region variables, which then get instantiated to inference variables in the implementation of `evaluate_obligation`. This allows many different usages of regions (region variables, early-bound, late-bound, etc) in the input to all end up being converted to the same `CanonicalPredicateGoal`.

This has the advantage of allowing us to re-use the same query invocation for (potentially) many different inputs - the `evaluate_obligation` query is (mainly) used to see if we can get `EvaluatedToOk` and therefore skip additional region processing. However, this ends up hurting our caching ability *within* the `evaluate_obligation` query - having inference variables in our `ParamEnv` means that we can't use the global cache.

Additionally, replacing non-region-variables (e.g. early-bound or late-bound regions) with region variables seems somewhat questionable. If we have two distinct `ReEarlyBound`s in our `ParamEnv`, then the region inference code will never let us 'equate' them. However, after instantiation of the canonicalized query, we could end up successfully 'equating' them (since they have become region inference variables), and never notifying the caller of this.

I think the solution is to change how we handle canonicalizing of the `ParamEnv` (and maybe the `Predicate` being evaluated as well). Instead of converting resolved regions to region variables (by way of canonical region variables), we should try to 'anonymize' regions based on where they occur. For example, a predicate like `Outlives(MyType<'a, 'b>, 'b)` could be 'anonymized' to `Outlives(MyType<'0, '1>, '1)` during **instantiation**. Here, `'0` and `'1` are early-bound regions, **not** region variables. This will improve our caching ability (since the `ParamEnv` should almost never end up with region variables), and avoid any potential problems caused by the ability to 'equate' region variables corresponding to two distinct early-bound regions.

**Comment by jackh726** [comment]
> If we have two distinct `ReEarlyBound`s in our `ParamEnv`, then the region inference code will never let us 'equate' them.

I don't think that's true...you can always end up with `<'a , 'b: 'a>`, right? `'a` and `'b` are "distinct", but can be equated.

> I think the solution is to change how we handle canonicalizing of the `ParamEnv` (and maybe the `Predicate` being evaluated as well). Instead of converting resolved regions to region variables (by way of canonical region variables), we should try to 'anonymize' regions based on where they occur.

This isn't a bad idea. I could imagine that treating early bound lifetimes as a special case, like static, isn't the worst idea.

**Comment by Aaron1011** [comment]
> I don't think that's true...you can always end up with <'a , 'b: 'a>, right? 'a and 'b are "distinct", but can be equated.

If you had that to start off with, then yes. However, if I have `fn foo<'a, 'b>`, then the region variables introduced for `'a` and `'b` could end up getting equated.

**Comment by jackh726** [comment]
Yes, but I don't think there's a way to avoid that; it's not as though we check if regions *could* be related before adding constraints.

**Comment by JohnCSimon** [comment]
@Aaron1011 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
