### PR TITLE
[WIP] Experiment with libeatmydata for speeding up CI

### PR DESCRIPTION
**Pull request by aidanhs**

### CODE REVIEW

**Comment by aidanhs** [comment]
Gah, hit submit too early.

Experiment with libeatmydata (https://www.flamingspork.com/projects/libeatmydata/) for speeding up CI. Initially try it out on just Linux allow_pr to see if it makes any difference at all. If it works and we think we want it more widely, we could potentially also use it on OSX since it seems there are efforts to make it work there.

Although this disables functions typically used for filesystem safety, we probably don't really care since if a machine dies then we've got no way of getting at the files even if they *were* safely synced to disk. If a machine doesn't die then fsync serves no purpose (IIUC).

**Comment by aidanhs** [comment]
Although this is a WIP, r? @alexcrichton

**Comment by aidanhs** [comment]
This initial attempt was a failure and does not speed up the `ALLOW_PR=1` build by more than the normal fluctuations.

Thinking more carefully about IO-bound parts of the build, libeatmydata would probably help with rebuilding docker images (it makes apt-get about 4x faster) and an sccache-based build of llvm. Unfortunately, neither of these are big wins - Docker image rebuilds happen rarely, and sccache builds of llvm are fast.

If we're ever looking for a <=5min speedup and/or suspect IO might be hurting specific builds, libeatmydata may be useful. I wondered if the android build might be one of those, then stumbled across #41490. So maybe some good will come of this.

Closing for now.

**Comment by alexcrichton** [comment]
@aidanhs oh in your timings you accounted for compiling LLVM, right? We don't have sccache configured for PRs (requires private env vars) which means that the build time for all builds will be way higher than normal.

I have noticed the save/restore steps for large docker images (like Android) take upwards of 10 minutes, so maybe this would help there?

**Comment by aidanhs** [comment]
I hadn't accounted for compiling LLVM. Given what you say, I'm a bit shocked to see that it apparently only takes 4mins to compile LLVM without sccache (which is comparable to *with*)! The [full builds](https://travis-ci.org/rust-lang/rust/builds/225050444) for the LLVM PR support this, a few I checked at random also have 4min LLVM builds. This surprises me a lot and I'd look a bit deeper here if it was causing unexpected slowdowns rather than speedups. Also, as I mentioned on #41490, the majority of time is spent in tests so it's worth spending time to optimize that first.

> I have noticed the save/restore steps for large docker images (like Android) take upwards of 10 minutes, so maybe this would help there?

That is an interesting idea, but I've got other thoughts about faster loading of Docker images I'd like to look into first (I've had experience of `docker load` being slow in the past).

**Pull request closed without merging**
