### PR TITLE
impl Default for CondVar, Mutex and RwLock

### PR DESCRIPTION
**Pull request by llogiq**
this fixes issue #31865 

Note: The impls are unstable for now.

### CODE REVIEW

**Comment by brson** [comment]
Looks related to https://github.com/rust-lang/rust/pull/32785

**Comment by llogiq** [comment]
It is related. And #32785 goes even further than this.

**Comment by durka** [comment]
> Note: The impls are unstable for now.

That doesn't work for trait impls, right?

**Comment by retep998** [comment]
@durka trait impls are insta-stable. Marking them unstable doesn't really work.

**Comment by llogiq** [comment]
OK then. I'll remove the unstable attrs if there is still interest.

**Comment by alexcrichton** [comment]
Thanks for the PR @llogiq! I believe these are all covered by https://github.com/rust-lang/rust/pull/32785, so I'm going to close in favor of that.

**Pull request closed without merging**
