### PR TITLE
Got rid of repetitions (such as rustc_ast::ast::) in librustc_ast

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Rework of #70621 

r? @eddyb 

credit to @Lezzz for the original pr :)

### CODE REVIEW

**Comment by eddyb** [comment]
r? @petrochenkov (who wasn't that keen on this, as per https://github.com/rust-lang/rust/pull/70621#issuecomment-614242750 - I don't want to just override that)

(but also, CI doesn't pass)

**Comment by Dylan-DPC** [comment]
Yes i'm aware, investigating the failure (which seems odd)

**Comment by petrochenkov** [comment]
Yeah, I just don't like a bunch of names existing in the crate root - some from the AST proper, some are just modules from the `rustc_ast` crate.
So if you import e.g. `use rustc_ast::*` you get things like `mut_visit` or `util` in scope as well, despite them not being AST structures.

I don't think we have other crates organized like this? Usually crate root modules are not very populated.

**Comment by petrochenkov** [comment]
Sigh, we already have `rustc_hir` that does `pub use hir::*;` from its root.

**Comment by Dylan-DPC** [comment]
Ye as I was doing these changes, I saw a similar pattern with hir

**Comment by crlf0710** [comment]
There's a merge conflict now, needs a rebase.

**Comment by Dylan-DPC** [comment]
Gonna close it as it's not important and rework it some other time.

**Pull request closed without merging**
