### PR TITLE
rustdoc: show exact case-sensitive matches first

### LINKED ISSUE #119480: rustdoc: search should prioritize matching capitalization
It's good that rustdoc's search is case-insensitive, to make it easier for people to find what they're looking for. However, if the user types in capitalization that exactly matches (or more closely matches) a given type, rustdoc's search results should prioritize that type over things that don't match in case.

For example, https://doc.rust-lang.org/std/?search=Copy (note the capital `C`) should list `std::marker::Copy` at the top, not `std::fs::copy`.

### PR DESCRIPTION
**Pull request by lolbinarycat**
fixes #119480

### CODE REVIEW

**Comment by fmease** [comment]
Could you please add tests for this? :)

**Comment by GuillaumeGomez** [comment]
In either `tests/rustdoc-js`or `tests/rustdoc-js-std`.

**Comment by lolbinarycat** [comment]
@fmease @GuillaumeGomez I couldn't find any documentation for this specific testsuite, so i did my best to infer its operation from existing tests..

unfortunately i don't have nodejs installed, and my hard drive is basically full, so i can't run these tests locally.  do they look good?

**Comment by lolbinarycat** [comment]
@notriddle i think i figured it out alright on my own, but it's definitely good to have this documented for future developers.

**Review by notriddle — APPROVED** [review]

**Pull request merged**
