### PR TITLE
enable macro visits in deriving

### LINKED ISSUE #32950: 'rustc' panicked at 'visit_mac disabled by default'
```rust
#[derive(Debug)]
struct NoneSense<T> {
	shouldBeVecT: vec![T]
}

fn main() { }
```

I accidentally used `vec![T]` as a type instead of `Vec<T>`, and got an `error: internal compiler error: unexpected panic`. Without the `#[derive(Debug)]`, rustc gives this error:

```
 ▸ RUST_BACKTRACE=1 rustc -Z unstable-options --pretty expanded nonsense.rs 
nonsense.rs:3:16: 3:23 error: type macros are experimental (see issue #27336)
nonsense.rs:3 	shouldBeVecT: vec![T]
              	              ^~~~~~~
nonsense.rs:3:16: 3:23 help: add #![feature(type_macros)] to the crate attributes to enable
error: aborting due to previous error
```

but with it it panics.

## Meta

```
 ▸ rustc --version --verbose
rustc 1.9.0-dev (98f0a9128 2016-03-23)
binary: rustc
commit-hash: 98f0a9128f0fc6545de14a5de8f0e91675045e56
commit-date: 2016-03-23
host: x86_64-unknown-linux-gnu
release: 1.9.0-dev
```

```
 ▸ RUST_BACKTRACE=1 rustc -Z unstable-options --pretty expanded nonsense.rs 
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'visit_mac disabled by default', src/libsyntax/visit.rs:106
stack backtrace:
   1:     0x7fcfa63e9340 - sys::backtrace::tracing::imp::write::h6559e17e2156431eGxu
   2:     0x7fcfa63f69cb - panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::closure.45009
   3:     0x7fcfa63f657c - panicking::default_hook::h6dd74158f7e250f0xJz
   4:     0x7fcfa63baf0f - sys_common::unwind::begin_unwind_inner::h7c5a5cd9fc65b5412ot
   5:     0x7fcfa494e49f - sys_common::unwind::begin_unwind::h6359867539345201166
   6:     0x7fcfa49a13b8 - visit::Visitor::visit_mac::h16549959366189755243
   7:     0x7fcfa499f8d6 - deriving::generic::find_type_parameters::Visitor<'a>.visit..Visitor<'a>::visit_ty::h116e561ccbab3742wDd
   8:     0x7fcfa49a33e1 - deriving::generic::TraitDef<'a>::create_derived_impl::h39b900a1397ae1a5YHd
   9:     0x7fcfa498a197 - deriving::generic::TraitDef<'a>::expand::hc13cde2c74a8c5b9JFd
  10:     0x7fcfa49877ec - deriving::debug::expand_deriving_debug::hf61e50c721bf05d7bgc
  11:     0x7fcfa4980273 - deriving::register_all::DeriveExtension.MultiItemDecorator::expand::hf9210c167ff074e5pPe
  12:     0x7fcfa23f61aa - ext::expand::expand_annotatable::h796edb48e8c92246FS4
  13:     0x7fcfa23f4648 - ext::expand::expand_item::h20c21c0b97772740Sl4
  14:     0x7fcfa240254e - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::h8d372ee48f4fc33djb5
  15:     0x7fcfa2402193 - fold::noop_fold_mod::h16414683612833474929
  16:     0x7fcfa23fba9a - ext::expand::expand_item_kind::hdad4b81657b878c0tm4
  17:     0x7fcfa2437059 - fold::noop_fold_item_simple::h717855624644524380
  18:     0x7fcfa2436bc0 - fold::noop_fold_item::h6171340203445854305
  19:     0x7fcfa23f8bd0 - ext::expand::expand_annotatable::h796edb48e8c92246FS4
  20:     0x7fcfa23f4648 - ext::expand::expand_item::h20c21c0b97772740Sl4
  21:     0x7fcfa240283e - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::h8d372ee48f4fc33djb5
  22:     0x7fcfa244317b - ext::expand::MacroExpander<'a, 'b>.Folder::fold_crate::h61090e51fa056378la5
  23:     0x7fcfa244463a - ext::expand::expand_crate::h6480936e5df691539j5
  24:     0x7fcfa6970691 - driver::phase_2_configure_and_expand::_$u7b$$u7b$closure$u7d$$u7d$::closure.35957
  25:     0x7fcfa691cd3c - driver::phase_2_configure_and_expand::h6f797358d9ef36f2uAa
  26:     0x7fcfa68fbf78 - pretty::pretty_print_input::hb5b8102303287e84t4b
  27:     0x7fcfa68f0035 - run_compiler::hb1c75f3272b9a9c6VDc
  28:     0x7fcfa68ed801 - sys_common::unwind::try::try_fn::h16475092432511726611
  29:     0x7fcfa63e699b - __rust_try
  30:     0x7fcfa63e692d - sys_common::unwind::inner_try::hcf46b1587e9940b44lt
  31:     0x7fcfa68ee04a - boxed::F.FnBox<A>::call_box::h2552470165920174793
  32:     0x7fcfa63f4ab4 - sys::thread::Thread::new::thread_start::hb7a9acf17d27d8536Gy
  33:     0x7fcf9f818423 - start_thread
  34:     0x7fcfa606ccbc - clone
  35:                0x0 - <unknown>

 ▸ echo $?
101
```

### PR DESCRIPTION
**Pull request by durka**
Fixes #32950.

There's a warning [in src/libsyntax/visit.rs](https://github.com/rust-lang/rust/blob/master/src/libsyntax/visit.rs#L105-L112) saying not to do this, but it seems to fix the ICE and the other deriving tests survive. The "note about macros above" seems to be [this](https://github.com/rust-lang/rust/blob/master/src/libsyntax/visit.rs#L22-24), but deriving is just kinda pasting stuff around, like a macro, so it seems okay.

cc #27245

### CODE REVIEW

**Comment by durka** [comment]
There's a subtle issue here. The reason derivings walk the member types is to find mentions of associated types, to add bounds. If a type macro generates this mention, then with this patch the deriving code will miss it:

```rust
macro_rules! passthru {
    ($t:ty) => { $t }
}

macro_rules! useassoc {
    ($t:ident, $assoc:ident) => { ($t, $t::$assoc) }
}

trait HasAssoc { type Type; }

#[derive(Debug)]
struct Thing1<T: HasAssoc> {
    thing: useassoc!(T, Type)
}
#[derive(Debug)]
struct Thing2<T: HasAssoc> {
    thing: (T, T::Type)
}
```

generates

```rust
impl <T: ::std::fmt::Debug + HasAssoc> ::std::fmt::Debug for Thing1<T> {
    fn fmt(&self, __arg_0: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match *self {
            Thing1 { thing: ref __self_0_0 } => {
                let mut builder = __arg_0.debug_struct("Thing1");
                let _ = builder.field("thing", &&(*__self_0_0));
                builder.finish()
            }
        }
    }
}

impl <T: ::std::fmt::Debug + HasAssoc> ::std::fmt::Debug for Thing2<T> where
 T::Type: ::std::fmt::Debug {
    fn fmt(&self, __arg_0: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match *self {
            Thing2 { thing: ref __self_0_0 } => {
                let mut builder = __arg_0.debug_struct("Thing2");
                let _ = builder.field("thing", &&(*__self_0_0));
                builder.finish()
            }
        }
    }
}
```

Fully fixing this seems like it would require moving derivings to after macro expansion, which sounds unlikely.

**Comment by durka** [comment]
Pushed a new test which will fail Travis, to show the problem.

**Comment by nrc** [comment]
Overriding `visit_mac` is fine, it's more of a precaution that you should be aware of the difference between pre- and post-expansion ASTs.

**Comment by nrc** [comment]
Expanding derive happens at the same time as macro expansion. I expect that the right fix for this is that if derive encounters a macro in type position, then to eagerly expand it. That should be possible, because the input to derive must parse (we have the AST, not just tokens). Changing the ordering of expansion in this case should be OK, because we know exactly what derive is doing, and this should just be a change to the derive code, not a change to the expander. However, I can imagine this might be easier said than done, in which case filing an issue for the non-type checking expansion and leaving a FIXME in the code seem fine to me.

**Comment by durka** [comment]
@nrc any pointers for functions I can call to expand the macro? Failing that, am I reading you correctly to say that having `#[derive]` generate an impl with a missing bound on the associated type is preferable to throwing an error saying "type macros not yet supported in `#[derive]`"?

**Comment by durka** [comment]
Per discussion on IRC, there are four options:

1. Change `#[derive]` to emit an error if it sees a type macro, leaving all future options open for how/whether to support them.

2. When `#[derive]` sees a type macro, copy it to the `where` clause of the generated impl. This may produce an impl that does not typecheck, if the macro expansion contains private types (this is why `#[derive]` doesn't simply copy all field types to the `where` clause). If type macros become stable, this implies a guarantee that type macros can be used with `#[derive]` as long as they don't expand to private types. @eddyb wants to write an RFC to elaborate types in bounds that would make this privacy business irrelevant.

    2a. Emit a warning about possibly ill-typed impls when this happens, to assist people in finding the cause of the error.

3. When `#[derive]` encounters a type macro, eagerly expand it. This seems difficult and could complicate future changes to macro expansion.

4. Do nothing until @eddyb finishes his RFC for elaborating types in bounds.

My preference is for 3 if possible, then 2a, and then 1. Other opinions?

**Comment by durka** [comment]
Closing as #32950 was fixed by #34010.

**Comment by jseyfried** [comment]
@durka want to reopen and land this?
We're going to revert my fix (#34010) so that `MultiDecorator`s can be a special case of `MultiModifier`s as discussed in IRC.

**Comment by durka** [comment]
Sure. I'm out of town until Monday though.

**Comment by jseyfried** [comment]
@durka ok, I might cherry-pick a commit off this branch then.

**Comment by eddyb** [comment]
@durka @nikomatsakis Just opened rust-lang/rfcs#1671 which covers the deriving privacy interactions.

**Pull request closed without merging**
