### PR TITLE
Add libntdll.a to migw libs

### LINKED ISSUE #68518: libntdll.a is not shipped within rust-mingw
When compiling cargo under `stable-x86_64-pc-windows-gnu`, it fails at linking with missing ntdll. After posting [issue](https://github.com/rust-lang/cargo/issues/7812) at cargo repo, @mati865 pointed out libntdll.a isn't shipped with rust-mingw component (it's missing [here](https://github.com/rust-lang/rust/blob/73f76b74efcaf21bd5424d87c66cd6ed7fe5c7de/src/bootstrap/dist.rs#L244-L288)).

### PR DESCRIPTION
**Pull request by Shadlock0133**
Fixes #68518

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @mati865 -- any thoughts here? :)

**Comment by mati865** [comment]
Sorry I should have been more specific. `ntdll.a` is Windows import library so it belongs below `//Windows import libs` comment, also please keep alphabetic order.

Otherwise LGTM although I'm not official reviewer. I believe @alexcrichton would be the right person here.

IMO this fix is significant and safe enough to backport it but the branching is so close 😞

**Review by mati865 — APPROVED** [review]

**Comment by retep998** [comment]
My big question is around how much of MinGW are we guaranteeing to provide? We're already providing far more than is necessary to just link code that uses `libstd`. Certainly most pure Rust shouldn't need anything beyond what `libstd` needs because `winapi` provides its own import libraries for the `pc-windows-gnu` targets. If a user statically links in some C libraries, is Rust expected to provide the system import libraries that C library needs?

**Comment by mati865** [comment]
> If a user statically links in some C libraries, is Rust expected to provide the system import libraries that C library needs?

I haven't thought it might be coming from static library. After investigation it comes from [`libssh2-sys` which builds https://github.com/alexcrichton/ssh2-rs/blob/550eb1ec0ba6c6d88e44d5caeaea73fc5bf594ed/libssh2-sys/build.rs#L167

At this point I'm not sure if this shouldn't be closed in favour of https://github.com/rust-lang/rust/pull/67429 since user already needs MinGW toolchain to build C libraries.

**Comment by petrochenkov** [comment]
I've seen this error as well when building `cargo-bisect-rustc`, and I did have a mingw toolchain with gcc from it in `PATH`.

You have to specifically add `<toolchain>/mingw64/x86_64-w64-mingw32/lib` to `LIBRARY_PATH` env var for linking to work, which wasn't entirely obvious.

**Comment by petrochenkov** [comment]
Curiously, `gcc -lntdll hello_world.c` finds `libntdll.a` successfully without any `LIBRARY_PATH` additions.

Here's a log from `gcc -lntdll hello_world.o --verbose`:
```
Using built-in specs.
COLLECT_GCC=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-7.2.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw720/x86_64-720-posix-seh-rt_v5-rev1/mingw64 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw720/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw720/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw720/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw720/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev1, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw720/x86_64-720-posix-seh-rt_v5-rev1/mingw64/opt/include -I/c/mingw720/prerequisites/x86_64-zlib-static/include -I/c/mingw720/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw720/x86_64-720-posix-seh-rt_v5-rev1/mingw64/opt/include -I/c/mingw720/prerequisites/x86_64-zlib-static/include -I/c/mingw720/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw720/x86_64-720-posix-seh-rt_v5-rev1/mingw64/opt/include -I/c/mingw720/prerequisites/x86_64-zlib-static/include -I/c/mingw720/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw720/x86_64-720-posix-seh-rt_v5-rev1/mingw64/opt/lib -L/c/mingw720/prerequisites/x86_64-zlib-static/lib -L/c/mingw720/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 7.2.0 (x86_64-posix-seh-rev1, Built by MinGW-W64 project)
COMPILER_PATH=C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/7.2.0/;C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../libexec/gcc/;C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/
LIBRARY_PATH=C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/;C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/;C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib/../lib/;C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../lib/;C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib/;C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../
COLLECT_GCC_OPTIONS='-v' '-mtune=core2' '-march=nocona'
 C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/7.2.0/collect2.exe -plugin C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/7.2.0/liblto_plugin-0.dll -plugin-opt=C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe -plugin-opt=-fresolution=C:\msys64\tmp\ccloT2Y8.res -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-liconv -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt --sysroot=C:/mingw720/x86_64-720-posix-seh-rt_v5-rev1/mingw64 -m i386pep -Bdynamic C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/crtbegin.o -LC:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0 -LC:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc -LC:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib/../lib -LC:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../lib -LC:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib -LC:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../.. -lntdll hello_world.o -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -liconv -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/crtend.o
COLLECT_GCC_OPTIONS='-v' '-mtune=core2' '-march=nocona'
```
Looks like `rustc` doesn't add all the necessary search directories when using mingw's `gcc` as a linker.

**Comment by mati865** [comment]
@petrochenkov `rustc` tells the linker to only look in Rust's target sysroot. Right now system MinGW is only used for building C/C++ libs and not for actual linking of Rust crates.

This is what https://github.com/rust-lang/rust/pull/67429 wants to change and I hope to finish it next week.

**Comment by alexcrichton** [comment]
I would personally prefer to not expand this list over time since, as mentioned, it's unlikely to ever have a limit on its growth. If https://github.com/rust-lang/rust/pull/67429 can solve the issue for others I think that's the best route to take, if we can.

**Comment by nikomatsakis** [comment]
I don't have a strong opinion about this, but @alexcrichton's last comment makes sense to me -- if we can find some more general mechanism vs expanding the list infinitely, seems good. 

One thing is clear, I'm the wrong reviewer.

r? @alexcrichton (that ok, @alexcrichton?)

**Comment by petrochenkov** [comment]
I'll go ahead and close this given the comments above.

Summary: if you want to build crates depending on arbitrary C code - install a MinGW toolchain + perhaps set `LIBRARY_PATH` until https://github.com/rust-lang/rust/pull/67429 is merged.

**Comment by lu-zero** [comment]
Setting the LIBRARY_PATH does not seem to work.

**Pull request closed without merging**
