### PR TITLE
Rollback part of pr 104137 that broke wasm linker overriding

### PR DESCRIPTION
**Pull request by pnkfelix**
This is a quick fix to address #108910

### CODE REVIEW

**Comment by pnkfelix** [comment]
(note: I definitely am not wedded to this particular approach. In the associated zulip thread, I described a number of alternatives that I would be equally happy with. I'm looking to @petrochenkov and to the WASM stakeholders like @bjorn3, @alexcrichton , and @sunfishcode to guide us here.)

**Comment by pnkfelix** [comment]
(also, I am nearly certain that this unit test is not constructed properly. Or at least, on my host system, I know that the included unit test did not suffice to expose the problem, because of the `# only-wasm32-bare` directive in the Makefile. I am not yet sure how I will resolve that; I suspect I might need to make some test PR's with *just* the unit test and figure out what will make the CI trigger a failure.)

**Comment by alexcrichton** [comment]
I at least personally don't know how the self-containedness support in rustc relates to wasm, or in other words I don't think I know enough about the way the fix is applied here to comment on it. If this issue is only showing up when users switch the wasm linker to `clang` I also don't know enough about the motivations to do that to know whether this is the best fix.

**Comment by petrochenkov** [comment]
r=me after fixing CI.
@rustbot author

I think the proper solution here would be fine-grained `-Clink-self-contained` (https://github.com/rust-lang/rust/pull/96884), including target defaults for it.

**Comment by pnkfelix** [comment]
Odd that a CI failure is moving this back to review rather than author. Is the intent that the reviewer is in a better position to decide whether a retry makes sense? (WHich I hope is the uncommon case, not the common one...)

@rustbot label: +S-waiting-on-author -S-waiting-on-review

**Comment by ehuss** [comment]
@bors r-

(was inadvertently re-queued by a homu sync)

**Comment by pnkfelix** [comment]
```
error: make failed
status: exit status: 2
command: cd "/checkout/tests/run-make/wasm-override-linker" && AR="ar" CC="clang -ffunction-sections -fdata-sections -fPIC --target=wasm32-unknown-unknown" CXX="clang -ffunction-sections -fdata-sections -fPIC --target=wasm32-unknown-unknown" HOST_RPATH_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" LD_LIB_PATH_ENVVAR="LD_LIBRARY_PATH" LLVM_BIN_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm/bin" LLVM_COMPONENTS="aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker dwp engine executionengine extensions filecheck frontendopenacc frontendopenmp fuzzercli fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interfacestub interpreter ipo irreader jitlink libdriver lineeditor linker lto m68k m68kasmparser m68kcodegen m68kdesc m68kdisassembler m68kinfo mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts objcopy object objectyaml option orcjit orcshared orctargetprocess passes powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo webassemblyutils windowsdriver windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86targetmca xray" LLVM_FILECHECK="/checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm/bin/FileCheck" NODE="/node-v15.14.0-linux-x64/bin/node" PYTHON="/usr/bin/python3" RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" RUSTDOC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" RUST_BUILD_STAGE="stage2-wasm32-unknown-unknown" RUST_DEMANGLER="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/rust-demangler" S="/checkout" TARGET="wasm32-unknown-unknown" TARGET_RPATH_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/wasm32-unknown-unknown/lib" TMPDIR="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/wasm-override-linker/wasm-override-linker" "make"
--- stdout -------------------------------
LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/wasm-override-linker/wasm-override-linker:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/wasm-override-linker/wasm-override-linker -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/wasm-override-linker/wasm-override-linker  foo.rs --crate-type cdylib --target wasm32-unknown-unknown -C linker=clang
--- stderr -------------------------------
--- stderr -------------------------------
error: linker `clang` not found
  = note: No such file or directory (os error 2)

error: aborting due to previous error
```

uhhhh, do we not have access to clang on the CI?

Or is this something where I need to modify a docker image or something to make the CI install clang as part of its setup here?

**Comment by pnkfelix** [comment]
I'm going to rip out the regression test (i.e. revise this PR so that it just has the rollback), and then file a separate issue about making a regression test for this

**Pull request merged**
