### PR TITLE
Bump Unicode printables to version 15.1, align to unicode_data

### PR DESCRIPTION
**Pull request by Marcondiro**
r? @Manishearth
Thanks!

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by klensy** [comment]
```
// NOTE: The following code was generated by "library/core/src/unicode/printable.py",
//       do not edit directly!
```

So this will not work.

**Comment by Marcondiro** [comment]
@klensy Yes :) maybe it would be a good idea to merge the printable.rs and unicode_data.rs generators to decrease the chance of having them misaligned

**Pull request merged**
