### PR TITLE
[DO NOT MERGE] pref test for https://github.com/rust-lang/rust/pull/95250

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by oli-obk** [comment]
Maybe we should just merge this PR (reverting the original)

The correct solution to the rustdoc problem is to remove the rustdoc specific hack and change how rustdoc queries information. Since this is a perf problem AND a hack, reverting and then removing the original hack, too, seems like the best way forward to me

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'm fine with it but I'll need help from someone who knows how to do it. Do you have an idea on how to do it? (Also, I'd really prefer to do it before merging this one so the issue doesn't reappear in the meantime if possible)

**Comment by oli-obk** [comment]
Ok, so I guess we mark the perf regression as triaged and work on a fix independently of this change

**Comment by GuillaumeGomez** [comment]
Sounds good to me!

**Pull request closed without merging**
