### PR TITLE
Experiment: Allow to push a result to another query

### PR DESCRIPTION
**Pull request by cjgillot**
Some queries are trivial projections of an earlier query's result.
The point of this PR is to measure whether we can gain some time by directly putting the result in the cache,
instead of doing the full query setup.

For this experiment: `hir_owner`, `hir_owner_nodes`, `def_span` and `def_kind`.

r? @ghost

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Hm, something like this is rather sensitive with regard to dependency tracking and it sounds like it could add quite a bit of complexity -- which makes me a bit sceptical. I'm interested in the performance results though.

**Comment by cjgillot** [comment]
@michaelwoerister I share your concern, and I got bit quite a few times writing that code.

I have mixed feeling on these perf results. There is a significant regression on unused-warnings and match-stress-enum for incremental cases. For the rest, the difference is mostly within noise levels. As expected, the number of invocations of the force-fed queries drop to ~0.

It's not that bad for an unoptimized draft. It still needs a lot of polishing to track down these regressions.

A stronger use case would also be beneficial. Early caching does not account for much time for often-used queries.
However, it may become useful for non-local operations to avoid query cycle hell.

**Comment by michaelwoerister** [comment]
:+1:

**Pull request closed without merging**
