### PR TITLE
Fix #78192

### LINKED ISSUE #78192: InstCombine introduces an incorrect use of a local after its storage has ended
```rust
pub fn f<T>(a: &T) -> *const T {
    let b: &*const T = &(a as *const T);
    *b
}
```

```diff
--- mir_dump/a.f.005-003.InstCombine.before.mir
+++ mir_dump/a.f.005-003.InstCombine.after.mir
@@ -1,2 +1,2 @@
-// MIR for `f` before InstCombine
+// MIR for `f` after InstCombine
 
@@ -18,5 +18,5 @@
         _3 = &_4;                        // scope 0 at a.rs:2:24: 2:40
-        _2 = &(*_3);                     // scope 0 at a.rs:2:24: 2:40
+        _2 = _3;                         // scope 0 at a.rs:2:24: 2:40
         StorageDead(_3);                 // scope 0 at a.rs:2:40: 2:41
-        _0 = (*_2);                      // scope 1 at a.rs:3:5: 3:7
+        _0 = (*_3);                      // scope 1 at a.rs:3:5: 3:7
         StorageDead(_4);                 // scope 0 at a.rs:4:1: 4:2
```

Found by MIR validator #77369 & #78147.

cc @simonvandel #76683

### PR DESCRIPTION
**Pull request by simonvandel**
Check which places are marked dead.

Fixes #78192

### CODE REVIEW

**Comment by oli-obk** [comment]
While this does fix the bug, I'm not very happy with making the logic in this optimization more complex. I still think we should make this optimization work without backtracking, in which case it would be trivial to bail out when encountering `StorageDead`

**Comment by simonvandel** [comment]
I have a branch locally with this optimization without backtracking. I can't guarantee when I will have time to finish it though. Should we create a issue to track the no-backtracking implementation, and move forward with the current pr?

**Comment by oli-obk** [comment]
Yea, an issue tracking it would be great. Merging this is ok imo with a fix somewhere on the horizon.

@bors r+

**Comment by simonvandel** [comment]
Created issue #78368 to track the work on a non-backtracking implementation

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rust/pull/78195 is already beta-accepted, so removing the backport nomination from this PR. It would reintroduce the unsoundness as mentioned here: https://github.com/rust-lang/rust/issues/78192#issuecomment-716815761.

**Pull request merged**
