### PR TITLE
Make some Ordering methods const

### PR DESCRIPTION
**Pull request by CDirkx**
Resubmission of [PR#75463](https://github.com/rust-lang/rust/pull/75463) as per [PR#76172](https://github.com/rust-lang/rust/pull/76172).

Constify the following methods of `core::cmp::Ordering`:
 - `reverse`
 - `then`

Insta-stabilizes these methods as const under the `const_ordering` feature, as their implementation is a trivial match and the recent stabilization of #49146 (Allow `if` and `match` in constants).
Note: the `const_ordering` feature has never actually been used as these methods have not been `#[rustc_const_unstable]`.

Tracking issue:  #76113

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks. :)
@rust-lang/libs can someone start FCP, assuming that's you usual process for stabilization?

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by LukasKalbertodt** [comment]
CC @rust-lang/wg-const-eval

**Comment by CDirkx** [comment]
As pointed out by @matklad on a similar PR, the tests are moved to `library\core`.
See issue #76268

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
