### PR TITLE
Refactor io/buffered.rs into submodules

### PR DESCRIPTION
**Pull request by Lucretiel**
This pull request splits `BufWriter`, `BufReader`, `LineWriter`, and `LineWriterShim` (along with their associated tests) into separate submodules. It contains no functional changes. This change is being made in anticipation of adding another type of buffered writer which can be switched between line- and block-buffering mode.

Part of a series of pull requests resolving #60673.

### CODE REVIEW

**Comment by Lucretiel** [comment]
> ☔ The latest upstream changes (presumably #75979) made this pull request unmergeable. Please resolve the merge conflicts.

Ouch. Whelp, alright, let's try that again.

**Comment by Lucretiel** [comment]
@BurntSushi got all the checks passing, but no rush

**Comment by Lucretiel** [comment]
This is tagged as waiting-on-author, but I don't see any outstanding issues for me to address.

**Comment by dtolnay** [comment]
@jonas-schievink, I don't think BurntSushi has been able to do standard library reviews recently.

r? @dtolnay

**Review by dtolnay — APPROVED** [review]
Thank you, this looks good to me.

**Pull request merged**
