### PR TITLE
[beta] Abort instead of UB if promotion fails

### PR DESCRIPTION
**Pull request by oli-obk**
original PR: https://github.com/rust-lang/rust/pull/52571 (not beta approved yet)

r? @nikomatsakis 

cc @RalfJung

### CODE REVIEW

**Comment by RalfJung** [comment]
@oli-obk the "uncondensed" diff view in GitHub says that there is a submodule change. Is that a GitHub UI think or real?

**Comment by oli-obk** [comment]
Apparently I fail at rebasing... not sure what happened there, fixed now

**Comment by RalfJung** [comment]
Now where do we have to lobby GitHub to revert that change to *hide submodule changes in the diff*? In which universe is that even a good idea?^^

(Sorry, I will stop being off-topic now.)

**Comment by RalfJung** [comment]
The corresponding #52571 just landed in master.

**Comment by nikomatsakis** [comment]
@bors r+

cc @rust-lang/compiler -- I'm approving this for beta backport. It's small and removes any chance of promotion introducing UB.

**Pull request merged**
