### PR TITLE
Backtrace 0.3.68

### PR DESCRIPTION
**Pull request by workingjubilee**
Uptakes these releases:
- https://github.com/rust-lang/backtrace-rs/releases/tag/0.3.68

r? @thomcc

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
LGTM

**Comment by workingjubilee** [comment]
I have no idea what's wrong.

**Comment by workingjubilee** [comment]
Our only hypothesis we were able to come up with was a rebase-related issue. So I did.

**Comment by thomcc** [comment]
Feel free to r=me on fixes to this as needed.

**Comment by workingjubilee** [comment]
what

**Comment by workingjubilee** [comment]
That seems to have worked?
@bors r=thomcc

**Comment by workingjubilee** [comment]
Changes no longer include flate2 because that was seemingly taken up in https://github.com/rust-lang/rust/pull/113046

Still removes a bunch of dupes: addr2line, miniz_oxide, and object!

@bors r=thomcc

**Comment by workingjubilee** [comment]
The only things I can think of in the backtrace crate which would so significantly alter performance would be the change to explicitly use mmap64, or the change to handle split dwarf. Otherwise I don't think it's directly related. I'll try to followup.

**Comment by thomcc** [comment]
It's a bit surprising since I wouldn't have expected backtraces to actually be computed in the compiler code that's relevant here.

**Comment by nnethercote** [comment]
Cachegrind diffs (e.g. [here](https://perf.rust-lang.org/detailed-query.html?commit=571c9fc8a9693bb75822d7b46a8d3bed0388e925&base_commit=839e9a6e1210934fd24b15548b811a97c77138fc&benchmark=helloworld-debug&scenario=incr-unchanged)) might be informative.

**Comment by workingjubilee** [comment]
I have opened https://github.com/rust-lang/backtrace-rs/issues/541 as a first step towards addressing this in the future. Backtrace has probably been gradually racking up bloat over years. It may have good reasons to add more to our binary size in the future! So this should probably be treated as more of an ongoing problem that we need to attack with ongoing measures.

**Pull request merged**
