### PR TITLE
Struct variant field search

### LINKED ISSUE #16017: rustdoc: Struct variant fields don't have the right path in the search index
``` rust
#![crate_type="lib"]
#![feature(struct_variant)]

pub enum Enum {
    Bar { pub name: String }
}
```

Running rustdoc on this, and then searching for `name` yields one result, with the incorrect path `foo::Enum::Enum::name`. Because the path is wrong, the link is also broken.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #16017.

Reopening of #64724.

cc @tomjakubowski
cc @ollie27 

r? @kinnison

### CODE REVIEW

**Comment by kinnison** [comment]
I've built and verified this works against a local trivial test case.  For some reason I failed to run the JS tests locally, I must be missing something.

**Review by kinnison — APPROVED** [review]
The change looks sane, though as I said I can't verify the test case per-se

**Comment by JohnTitor** [comment]
Failed in https://github.com/rust-lang/rust/pull/68747#issuecomment-581080085
@bors retry r-

**Review by ollie27 — APPROVED** [review]

**Comment by ollie27** [comment]
This looks good to me.

@bors r+

**Pull request merged**
