### PR TITLE
`std::error::Error` -> Trait Implementations: lifetimes consistency improvement

### PR DESCRIPTION
**Pull request by WiktorPrzetacznik**
This cleans up `std::error::Error` trait implementations lifetime inconsistency (`'static` -> `'a`)

**Reasoning:**

Trait implementations for `std::error::Error`, like:
`impl From<&str> for Box<dyn Error + 'static, Global>`
`impl<'a> From<&str> for Box<dyn Error + Sync + Send + 'a, Global>`
use different lifetime annotations misleadingly implying using different life annotations here is a conscious, nonaccidental decision.

[(Related forum discussion here)](https://users.rust-lang.org/t/confusing-std-error-source-code/97011/5?u=wiktor)

### CODE REVIEW

**Comment by workingjubilee** [comment]
@WiktorPrzetacznik Can you edit your post to include the reasoning to accept this PR [instead of a link to a forum comment](https://users.rust-lang.org/t/confusing-std-error-source-code/97011/5?u=wiktor) so I can kick this over to an FCP and that reasoning can be easily read and discussed by everyone instead of having to comb through that thread for context (or even to determine how much of that context is applicable)?

**Comment by WiktorPrzetacznik** [comment]
@workingjubilee Thank you for the suggestion, reasoning is now included.

**Comment by workingjubilee** [comment]
Thanks!

r? libs-api Requesting FCP for relaxing the lifetime constraints of these implementations for trait objects where they currently can imply the `'static` lifetime in a few cases instead of `'a` due to [trait object lifetime defaults](https://doc.rust-lang.org/reference/lifetime-elision.html#default-trait-object-lifetimes).

**Review by dtolnay — APPROVED** [review]

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

This fixes the spurious lifetime error in code such as the following.

```rust
fn main() {
    let non_static_error = std::fmt::Error;
    let mut boxed_error: Box<dyn std::error::Error> = Box::new(&non_static_error);
    replace_error(&mut boxed_error);
}

fn replace_error(out: &mut impl From<String>) {
    *out = "...".to_owned().into();
}
```

```console
error[E0597]: `non_static_error` does not live long enough
 --> src/main.rs:3:64
  |
2 |     let non_static_error = std::fmt::Error;
  |         ---------------- binding `non_static_error` declared here
3 |     let mut boxed_error: Box<dyn std::error::Error> = Box::new(&non_static_error);
  |                                                       ---------^^^^^^^^^^^^^^^^^-
  |                                                       |        |
  |                                                       |        borrowed value does not live long enough
  |                                                       cast requires that `non_static_error` is borrowed for `'static`
4 |     replace_error(&mut boxed_error);
5 | }
  | - `non_static_error` dropped here while still borrowed
```

**Comment by BurntSushi** [comment]
Can we do a crater run for this change? It seems unlikely it will break anyone, but I think it would be good to check. I'm thinking in particular about regressions related to inference failures

**Comment by BurntSushi** [comment]
@rfcbot concern crater-run-first

**Comment by dtolnay** [comment]
@craterbot check

**Comment by dtolnay** [comment]
4 crates regressed with a "build failure" and all 4 look spurious to me. Out of memory, disk full, some kind of container disconnect. None of these could possibly be related to a compile error from the lifetimes change. @BurntSushi could you take a look as well, and resolve the concern?

**Comment by BurntSushi** [comment]
@rfcbot resolve crater-run-first

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
