### PR TITLE
[breaking-change] Remove TypedArena::with_capacity

### PR DESCRIPTION
**Pull request by nnethercote**
This is a follow-up to #36592.

The function is unused by rustc. Also, it doesn't really follow the
usual meaning of a `with_capacity` function because the first chunk
allocation is now delayed until the first `alloc` call.

This change reduces the size of `TypedArena` by one `usize`.

@eddyb: we discussed this on IRC. Would you like to review it?

### CODE REVIEW

**Comment by nnethercote** [comment]
@eddyb: run-make\output-type-permutations failed. I don't understand what went wrong. Is it the compile warnings about `main` never being used? I don't know how that relates to my patch. Please help!

**Comment by eddyb** [comment]
Don't see how it's relevant. @bors retry

**Comment by nnethercote** [comment]
@eddyb: another failure that's not my fault? It's an exception in Python code...

**Comment by eddyb** [comment]
The bots may be acting up, but it's a weekend so I don't think I have any way of confirming. @bors retry

**Pull request merged**
