### PR TITLE
Fix spans for macros

### LINKED ISSUE #28424: Macro items assigned bad span
Item-like macro invocations are assigned a bad span. Oft-times it'll only contains a semicolon.

### PR DESCRIPTION
**Pull request by kyeah**
Fixes #28424 (item macros), #30067 (impl item macros), and pattern macros.

### CODE REVIEW

**Comment by sanxiyn** [comment]
Shouldn't it be `last_span.hi` instead of `span.hi`?

**Comment by kyeah** [comment]
Ah yep, just pushed a quick fix.

**Comment by sanxiyn** [comment]
Failed tidy. (I know this can be annoying. I apologize.)

**Pull request merged**
