### PR TITLE
Bump bootstrap compiler to 1.45

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Pretty standard update.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/clippy on https://github.com/rust-lang/rust/pull/72957/files#diff-e650e88617b30d8d2157e23c9dcc5286L282 which is technically a behavior change

**Comment by camelid** [comment]
By the way, the title of this PR is "Bump bootstrap compiler to **1.45**" whereas it's actually bumped to 1.46, unless I'm misunderstanding

**Comment by Mark-Simulacrum** [comment]
No, the new compiler is versioned at 1.46 but the beta compiler used to bootstrap is 1.45 I believe.

**Comment by camelid** [comment]
Ah, sorry :). It just confused me because your commit said 1.46 but the PR said 1.45

**Comment by flip1995** [comment]
This was also already fixed in Clippy, in semantically the same way: https://github.com/rust-lang/rust-clippy/pull/5665/commits/37381d33a4761a064311dd95fbc54b5da6ad3766#diff-2e8e94b55639a4808cb93bcc616d2d92

Thanks for the heads-up 👍

**Pull request merged**
