### PR TITLE
Don't export `main` on WebAssembly.

### PR DESCRIPTION
**Pull request by sunfishcode**
On `default_hidden_visibility = true` platforms, which is currently just WebAssembly, don't automatically export `main`. On such platforms, `main` in C defaults to being hidden, and therefore not automatically exported.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
https://github.com/rust-lang/rust/pull/102758#issuecomment-1271042508

**Comment by Dylan-DPC** [comment]
@sunfishcode any updates on this?

**Comment by sunfishcode** [comment]
src/etc/wasm32-shim.js depends on `main` being exported, and maybe we could change that, but maybe means that there's a broader expectation out there that `main` is exported out there. I don't know what the expectations are here yet.

**Comment by JohnCSimon** [comment]
@sunfishcode  Can you please post your status on this PR? It has sat idle for months.

**Comment by sunfishcode** [comment]
In theory we should do something here, but in practice it'll require navigating some complex backwards compatibility constraints.

**Comment by JohnCSimon** [comment]
@sunfishcode 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
