### PR TITLE
Stabilization PR for Issue-53125

### PR DESCRIPTION
**Pull request by blitzerr**
https://github.com/rust-lang/rust/issues/53125

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks like there's a compilation failure in libsyntax. You can relatively quickly make sure the compiler compiles with `./x.py check`.

```
[00:06:35] [0m[1m[38;5;9merror[E0609][0m[0m[1m: no field `non_modrs_mods` on type `&feature_gate::Features`[0m
[00:06:35] [0m    [0m[0m[1m[38;5;12m--> [0m[0mlibsyntax/feature_gate.rs:1505:47[0m
[00:06:35] [0m     [0m[0m[1m[38;5;12m|[0m
[00:06:35] [0m[1m[38;5;12m1505[0m[0m [0m[0m[1m[38;5;12m| [0m[0m                let has_feature = cx.features.non_modrs_mods;[0m
[00:06:35] [0m     [0m[0m[1m[38;5;12m| [0m[0m                                              [0m[0m[1m[38;5;9m^^^^^^^^^^^^^^[0m
[00:06:35] 
[00:06:38] [0m[1m[38;5;9merror[0m[0m[1m: aborting due to previous error[0m
```

**Comment by blitzerr** [comment]
Thanks @Mark-Simulacrum 
I fixed it and then ran into another test failure.

**Comment by Mark-Simulacrum** [comment]
You should be able to run the tests locally with `./x.py test --stage 1 src/test/ui`. It looks like the three currently-failing tests are doing so because we've stabilized the feature and these tests tested the unstable gate; you should be able to just delete them.

**Comment by eddyb** [comment]
@blitzerr You have a merge commit, and submodule changes, so you should rebase (e.g. by running `git pull --rebase upstream master`) and squash the changes into one commit.

**Comment by blitzerr** [comment]
@eddyb Sorry for the inconvenience. I will merge all to one commit.

**Comment by eddyb** [comment]
@blitzerr No worries! It's not a problem for humans, but it does cause technical issues.

**Comment by blitzerr** [comment]
@eddyb  Sure that makes sense.
Is this the way to sync up with upstream and then merge with my forked repo ?
git pull --rebase upstream master
git push origin master  // To push to the forked repo

So is this a convention that we always do rebases instead of merge ?

Sorry, for the annoying questions. I just started (try to) to contribute this  week, and so I have a few questions :)

**Comment by eddyb** [comment]
You want `git push -f origin master` (`-f` means "force", which you need to do after a rebase, since the rebase "rewrites" the commits, instead of appending to them).

> So is this a convention that we always do rebases instead of merge ?

Yeah. To squash (combine commits), you'd also want `git rebase -i upstream/master` and follow the instructions (leave one commit as "pick" and change all following ones to "squash").

Also, if you don't need to split your change into multiple commits, you can always amend the commit (I recommend `git gui`'s amend mode for this, because you can *see* what's happening).

If you use `git gui` to amend, you can solve the submodule problem at the same time (go into amend mode, then unstage the submodule changes in `src/tools`, then commit).

**Comment by blitzerr** [comment]
Thank you so much @eddyb .

**Comment by eddyb** [comment]
@blitzerr Why not update this one? I guess GitHub says "unknown repository" so something happened. Did you delete your fork? (you don't need to/shouldn't do that)

**Comment by blitzerr** [comment]
I recreated my fork as trying to merge it, I messed up the git somehow and
started everything all over again

**Pull request closed without merging**
