### PR TITLE
print vis & defaultness for nested items

### LINKED ISSUE #69315: Visibility tokens on types in `extern { ... }` blocks are no longer given to procedural macros
I had https://github.com/rustwasm/wasm-bindgen/issues/2009 opened up on a project recently but this looks to be a regression I think. This regressed between nightly-2020-02-19 and nightly-2020-02-20, and bisecting further by commit reveals https://github.com/rust-lang/rust/pull/69271 as the culprit. I'm not sure which of the PRs in that rollup though are the culprit here.

This can be reproduced by running `cargo check` from the `crates/js-sys` folder in the wasm-bindgen repository. Unfortunately this one probably isn't super easy to reproduce, so I'm hoping that someone more knowledgeable can hopefully take a look at this and have a better idea about what's going on. 

There's definitely macros going on in `#[wasm_bindgen]` (the `Memory` type is synthesized by a macro), which leads me to think that https://github.com/rust-lang/rust/pull/69211 may be the culprit? (cc @petrochenkov)

### PR DESCRIPTION
**Pull request by Centril**
Fixes https://github.com/rust-lang/rust/issues/69315 which was injected by https://github.com/rust-lang/rust/pull/69194.

r? @petrochenkov 
cc @alexcrichton

### CODE REVIEW

**Comment by petrochenkov** [comment]
r=me with the unused import removed.

**Comment by Centril** [comment]
Failure is a spurious network issue.

**Comment by Centril** [comment]
Failure looks spurious, @bors retry

**Pull request merged**
