### PR TITLE
Move assert_matches to an inner module

### LINKED ISSUE #82913: Is there a gentler way to land the assert_matches macro?
As a user I'm really excited for `std::assert_matches!`, but I'm a little worried about the level of breakage it introduces and I'm hoping to discuss possible paths forward.

The Fuchsia roll to update rustc is currently blocked by [ambiguous macro resolution errors](https://github.com/rust-lang/rust/pull/82770#issuecomment-792999294) with code that glob-imports `matches::assert_matches!`. It seems that a locally defined glob import does not take precedence over macros defined in std.

This implies a workaround of changing all the glob imports to `use matches::assert_matches`, but this does not account for submodules which `use super::*;`. Unfortunately it seems that the [test_case](https://docs.rs/test-case/1.1.0/test_case/) crate wraps the function body in a submodule and adds a `use super::*`to the new module.

What this means in practice is that every function using the test_case crate must have an explicit import added or have the macro referenced via a fully qualified name. AIUI this change counts as an acceptable breakage and so I'm still putting together a diff which will resolve all of our roll blockers.

What I'm wondering though is whether knowing about this source of breakage offers a path to a smoother release. If so, we could revert the change and prepare to roll it out more gently.

Two options that came up in private discussions:

1. remove assert_matches from the prelude until the 2021 edition
  * this wouldn't make it immediately available but it would prevent the breakage
2. make local glob imports take precedence over std/prelude macros
  * this would make it immediately available but may not be possible within language constraints

Any other suggestions for how to make this change less disruptive? cc @m-ou-se @tmandry @joshtriplett

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes #82913

### CODE REVIEW

**Comment by jyn514** [comment]
(I edited the name because "submodule" has a specific meaning WRT git, and I was confused at first.)

**Comment by yaahc** [comment]
@rfcbot merge

**Comment by richkadel** [comment]
@m-ou-se @yaahc 

This change is causing lots of downstream build failures (compiling Fuchsia for instance).

Choosing to call this `std::assert::assert_matches!` is causing compiler errors in code that explicitly references (e.g.,`use`) the macro `std::assert!`, because they are at the same item path as the parent mod: `std::assert` or `core::assert` now refer to both the default `assert!` macro and the mod containing `assert_matches`.

In fact, the feature gate for `assert_matches` generates compile time errors for legitimate references to the `std::assert` macro (Rust tries to apply the feature gate when it incorrectly assumes the reference is to the parent mod of `assert_matches!` making the error message unintuitive.

Example, in some code I'm trying to compile since this landed, the original author needs to specify an absolute package path to, for instance, deconflict with a different item in the local mod, with the name `assert`.

I think it might be better to use an item path that isn't already in use, like one of:

- `std::assert_matches::assert_matches` would at least match the feature gate name (I mention this because it was confusing at first that the error messages I got recommended enabling the `feature(assert_matches)` just to use `core::assert`.
- `std::asserts::assert_matches` is a shorter alternative you might also consider

cc: @tmandry @anp

**Comment by m-ou-se** [comment]
Oh, good catch. Let's move it to `std::macros` or something for now. The name doesn't matter much, since the module is unstable.

@yaahc , do you have time to do this and handle the backport too?

**Comment by richkadel** [comment]
I added #87189 for tracking purposes

**Comment by RalfJung** [comment]
@rust-lang/infra this PR changes `rustc_mir/interpret` but the bot failed to do the usual ping... is this a known problem? (The change is fine of course.)

I assume the change was not present in the PR at the beginning and got added by pushing to the branch later.

**Comment by jyn514** [comment]
@RalfJung yes: https://github.com/rust-lang/highfive/issues/223

**Pull request merged**
