### PR TITLE
remove redundant clones, found by clippy

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by eddyb** [comment]
This reminds me, are we linting `.clone()` on `Copy` types yet?

**Comment by sinkuu** [comment]
There's [clone_on_copy](https://rust-lang.github.io/rust-clippy/master/#clone_on_copy) lint.

**Comment by eddyb** [comment]
Yeah, but are we enabling it on `rustc`?

**Comment by matthiaskrgr** [comment]
None of the clippy lints are run on rustc code by "default", but you can get clippy defaults run with `./x.py clippy`

Meanwhile I've prepared a PR here:  https://github.com/rust-lang/rust/pull/68292

**Pull request merged**
