### PR TITLE
Replace Idents with Names outside of libsyntax + Idents/Names cleanup (Part 2)

### LINKED ISSUE #6993: After libsyntax, idents should be replaced by Names
This is a FIXME issue; right now, an ident contains information used by expansion. After expansion, this is collapsed down to a single Name (an index into the interner). However, the downstream stuff in librustc refers to "ast::ident" everywhere.  It would save space and time to just pass around one int rather than two, by replacing uses of "ident" with "Name". I don't know if I'll have time to do this. (Planning for my untimely demi^H^Hparture.)

### PR DESCRIPTION
**Pull request by petrochenkov**
This PR removes random remaining `Ident`s outside of libsyntax and performs general cleanup
In particular, interfaces of `Name` and `Ident` are tidied up, `Name`s and `Ident`s being small `Copy` aggregates are always passed to functions by value, and `Ident`s are never used as keys in maps, because `Ident` comparisons are tricky.

Although this PR closes https://github.com/rust-lang/rust/issues/6993 there's still work related to it:
- `Name` can be made `NonZero` to compress numerous `Option<Name>`s and `Option<Ident>`s but it requires const unsafe functions.
- Implementation of `PartialEq` on `Ident` should be eliminated and replaced with explicit hygienic, non-hygienic or member-wise comparisons.
- Finally, large parts of AST can potentially be converted to `Name`s in the same way as HIR to clearly separate identifiers used in hygienic and non-hygienic contexts.

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
Could you file issues for the remaining work you identified please? (It sounds really useful and I wouldn't want it to be forgotten).

**Comment by petrochenkov** [comment]
@nrc 
The issues are filed.

**Comment by Manishearth** [comment]
Why was `impl<T: AsRef<str>> PartialEq<T> for Name` removed?

**Comment by petrochenkov** [comment]
@Manishearth 
It was used in few places + making the roundtrip through the interner, required to obtain the string, a bit more explicit seemed like a good idea. Is it often needed in plugins?

**Comment by Manishearth** [comment]
Yeah, but if it's doing something that should be explicit that's fine by me.

**Pull request merged**
