### PR TITLE
rustdoc: Remove duplicate "List of all items"

### LINKED ISSUE #82477: rustdoc: "List of all items" title shown twice
As can be seen when going to https://doc.rust-lang.org/nightly/std/all.html, the "List of all items" page generated by rustdoc has a header saying "List of all items List of all items":
Screenshot_2021-02-24 List of all items in this crate

### PR DESCRIPTION
**Pull request by bugadani**
Closes #82477 

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
Can you add a test case for this so it doesn't regress again?

**Comment by bugadani** [comment]
Ugh... I don't know about that, this is a rather random piece of string that would be checked. Should we test the whole template?

**Comment by jyn514** [comment]
Hmm, I guess since this is literal text there's not a ton of point in testing it ... @GuillaumeGomez what do you think?

r=me on the fix though

r? @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
You can check that you don't have that string, but yes, please add a test. :)

**Comment by camelid** [comment]
This seems completely fine to backport, so 👍 from me.

- [x] @jyn514 (nominated for backport)
- [x] @camelid
- [ ] @GuillaumeGomez 
- [ ] others?

**Pull request merged**
