### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #131790 (Document textual format of SocketAddrV{4,6})
 - #131983 (Stabilize shorter-tail-lifetimes)
 - #132097 (sanitizer.md: LeakSanitizer is not supported on aarch64 macOS)
 - #132107 (Remove visit_expr_post from ast Visitor)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=131790,131983,132097,132107)

### CODE REVIEW

**Comment by lqd** [comment]
@rust-timer build 5d30201178463079b2aa1a023791f2c8468d2702

**Comment by lqd** [comment]
Ah so these are from https://github.com/rust-lang/rust/pull/131983, were these regressions expected or is there maybe some way to reduce them @dingxiangfei2009 @lcnr?

**Comment by dingxiangfei2009** [comment]
@lqd

> Ah so these are from #131983, were these regressions expected or is there maybe some way to reduce them @dingxiangfei2009 @lcnr?

Here is my theory. This change will lead to extra data generated for each instance of a tail expression of a block. Given that they are a common occurrence I expected some regression will happen. I won't just sign it off right away, though. I will investigate the pref report now. Thanks for the heads-up!

**Comment by dingxiangfei2009** [comment]
By extra data, I mean we will generate
- extra `ScopeData` for each tail expression,
- extra `thir::ExprKind::Scope` entry for each tail expression

MIR size should stay roughly the same, however.

**Comment by Kobzol** [comment]
Visiting from weekly triage (thanks @lqd for the perf. run!). It [looks like](https://perf.rust-lang.org/detailed-query.html?commit=5d30201178463079b2aa1a023791f2c8468d2702&benchmark=ripgrep-13.0.0-check&scenario=incr-patched%3A+println&base_commit=1d4a7670d4f37bfbae2d89ec3ec07cd40dbc5a5d&sort_idx=-11) some queries are now being caled more often, e.g. `is_copy_raw` - could that have been the culprit?

Not marking as triaged yet.

**Pull request merged**
