### PR TITLE
Remove special case for `simd_shuffle` arg promotion

### PR DESCRIPTION
**Pull request by ecstatic-morse**
After rust-lang/stdarch#825, these intrinsics are now defined with `#[rustc_args_required_const(2)]`, so the special-case is no longer necessary.

### CODE REVIEW

**Comment by petrochenkov** [comment]
FWIW, we have function parameter attributes now, so `#[rustc_args_required_const(N)]` on functions could become `#[rustc_required_const]` on function parameters.
Perhaps we need to open an issue for this.

**Comment by ecstatic-morse** [comment]
> FWIW, we have function parameter attributes now, so #[rustc_args_required_const(N)] on functions could become #[rustc_required_const] on function parameters.
Perhaps we need to open an issue for this.

Ooh, this would be much better. I can open the issue if you like?

**Comment by petrochenkov** [comment]
> I can open the issue if you like?

Yeah, that would be nice.

**Comment by ecstatic-morse** [comment]
Some tests declare their own `simd_shuffle` platform intrinsic, which now needs the attribute. I assume this is okay (cc @petrochenkov).

@bors r=petrochenkov

**Pull request merged**
