### PR TITLE
Use EverInit instead of MaybeInit to determine initialization

### LINKED ISSUE #50461: NLL erroneous Warning: variable does not need to be mutable
```rust
#![feature(nll)]
struct Foo {
    pub value: i32
}

// triggers bug
fn use_foo_mut(mut foo: Foo) {
    foo = foo;
    println!("{}", foo.value);
}

// does not trigger bug
fn use_i32_mut(mut i: i32) {
    i = i;
    println!("{}", i);
}

fn main() {
    use_foo_mut(Foo { value: 413 });
    use_i32_mut(413);
}
```

gives:
```
warning: variable does not need to be mutable
 --> src/main.rs:8:16
  |
8 | fn use_foo_mut(mut foo: Foo) {
  |                ----^^^
  |                |
  |                help: remove this `mut`
  |
  = note: #[warn(unused_mut)] on by default
```

If I remove the mut then I get a compile error.

Compiled with nightly-2018-05-05

This is not related to https://github.com/rust-lang/rust/issues/50343 as that has been fixed in the nightly I am using.

### LINKED ISSUE #50463: Invalid warning unused_mut
I just updated my nightly and now I'm getting this warning:

image

But it's invalid, the binding has to be mutable, otherwise:

image

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #50461.
Fixes #50463.

### CODE REVIEW

**Comment by estebank** [comment]
lgtm

**Comment by KiChjang** [comment]
@TimNN Looks like that if there's a timeout, the logs above say nothing about it.

**Comment by pnkfelix** [comment]
@KiChjang the change to the code looks fine to me

but since it seems like you made what look like two independent changes, I would imagine we need more than the single small unit test that you have here.

In particular, I suspect you need a test to check the change where you added unused mut logic for reservations or writes of `WriteKind::MutableBorrow(BorrowKind::Unique))`

(Let us know if you want help constructing such a test!)

**Comment by jonhoo** [comment]
This is currently causing a lot of spurious warnings on nightly. @KiChjang any chance you could take a second look following @pnkfelix's comments?

**Comment by KiChjang** [comment]
@jonhoo I'm already looking into it; the problem is I don't know how to construct a test for that functionality.

**Comment by KiChjang** [comment]
Ok, for the sake of a timely fix, I've removed the check under `WriteKind::MutableBorrow(BorrowKind::Unique))`.

**Pull request merged**
