### PR TITLE
Update LLVM to 15.0.7

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit pulls in rust-lang/llvm-project#143 which updates the LLVM version used by rustc to 15.0.7, namely pulling in https://reviews.llvm.org/D136110 which is needed for some work I'm working on with wasm.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the speedy reviews! Would you be up for rubber-stamping https://github.com/rust-lang/rust/pull/106644 as well perhaps? If not no worries!

**Comment by cuviper** [comment]
>   CMake 3.13.4 or higher is required.  You are running version 3.10.2

Hmm, indeed `ubuntu:18.04` does not have new enough cmake. The command leading to that was:

    RUSTDOCFLAGS=--document-private-items --document-hidden-items python3 ../x.py doc --stage 0 compiler

... which is new from #106670 (cc @albertlarsan68 @Mark-Simulacrum). I'm guessing that `mingw-check` got a cached LLVM when that PR landed? I can see about simply updating the mingw-check containers, but it seems a little surprising for that to start building the entire compiler if it wasn't before.

**Comment by Mark-Simulacrum** [comment]
Yeah, most likely. I think for now reverting that addition is right (the more principled fix is probably to avoid building LLVM for doc builds).

**Comment by cuviper** [comment]
Well, the upgrade proved easy enough, and is probably a good idea anyway -- #106948.

I think we can consider that revert separately, on its own merits, but I shouldn't block here after that upgrade.

**Comment by alexcrichton** [comment]
Thanks for the assistance in tracking this down! I suspected that something like that was happening when I didn't find any cmake changes in the 15.0.6 -> 15.0.7 diff. I'll wait for #106948 which I think should enable a retry of this to go through.

**Comment by a1phyr** [comment]
Could this PR also include https://github.com/rust-lang/llvm-project/pull/144 ?

**Comment by alexcrichton** [comment]
Sure thing, I've pulled in that commit here too now

**Comment by klensy** [comment]
Should rust specific patches be rebased on top, or it ok to keep them where they exist now?

**Comment by cuviper** [comment]
It's OK to leave it as-is. We'll probably be upgrading to LLVM 16 relatively soon anyway, once that branches.

**Pull request merged**
