### PR TITLE
rustdoc: change trait bound formatting

### LINKED ISSUE #85566: rustdoc: awkward vertical spacing on trait bounds
When a method does not have trait bounds, it is displayed all on one line. When a method has just one trait bound, it takes four lines:

    fn by_ref(&mut self) -> &mut Self
    where
        Self: Sized,
    { ... }

There are some conflicting priorities here: On the one hand, it's nice for the layout to match what rustfmt does. On the other hand, it's good to use spacing to emphasize the parts of the documentation that are important. For instance, the `{ ... }` has a whole line to itself to convey one bit of information: this is a provided method, not a required one. Spacing is also useful to show that parts of the display are related to each other. In the above, it's not visually clear whether `{ ... }` is part of `by_ref` or some independent item.

I propose we change to this for methods with one trait bound:

    fn by_ref(&mut self) -> &mut Self
       where Self: Sized { ... }

And this for methods with multiple trait bounds:

    fn by_ref(&mut self, other: T) -> &mut Self
       where Self: Sized,
             T: Read { ... }

Screen shot of nightly: https://doc.rust-lang.org/nightly/std/io/trait.Read.html

### PR DESCRIPTION
**Pull request by rol1510**
Fixes #85566

Before
image

Now
image

### CODE REVIEW

**Comment by Urgau** [comment]
This new formatting style is (in my opinion) very confusing and I believe does not follow the Rust style guidelines (which `rustfmt` applies).

Is there another reason to do this change (other than taking 2 lines less) ?

**Comment by Manishearth** [comment]
Worth noting that this only makes a difference on defaulted methods methods. "This method has a default impl" is not _that_ important from a rustdoc pov and giving it an entire line doesn't seem worth it to me.

That said, this is _mostly_ a problem for Iterator, perhaps we can only apply this to traits with `> N` defaulted methods?

I'm fine with the proposed change as it is, though.

**Comment by jsha** [comment]
@Manishearth hits the nail precisely on the head with regards to why I proposed the formatting change in #85566. IMO `{ ... }` does not deserve its own line in what is supposed to be a summary view. It's not a very efficient or effective way to say "there is a provided implementation for this function."

I think "this is not rustfmt style" is an important argument but not a decisive one. The current behavior puts the opening and closing braces on the same line, which rustfmt would never do unless the function body was empty.

Really, there's a conflict between "make the item-decl look like source code" and "hide the implementation."

Perhaps a better way to resolve this conflict is to avoid the pseudo-syntax `{ ... }`. Instead we would break the trait item-decl into two sections, just like we do in the detailed documentation:

```
pub trait Iterator {
    type Item;
    
    // Required method
    fn next(&mut self) -> Option<Self::Item>;

    // Provided methods
    fn next_chunk<const N: usize>(
        &mut self
    ) -> Result<[Self::Item; N], IntoIter<Self::Item, N>>
    fn size_hint(&self) -> (usize, Option<usize>)
    fn count(self) -> usize
    fn last(self) -> Option<Self::Item>
    fn advance_by(&mut self, n: usize) -> Result<(), usize>
    ...
}
```

This has the advantage of taking something that is implicit and hard to notice, and making it explicit and easy to notice. That is, readers are expected to notice that a trailing `;` means "required method" and a trailing `{ ... }` means "provided method". And also that provided/required methods are grouped into blocks in the item-decl.

By the way, @rol1510 thank you for the implementation! Sorry that we are still hashing out the details of how we want this to look. Sometimes it takes an implementation to spark more detailed discussion. :-D

**Comment by Manishearth** [comment]
Another thing that could be done is to make `{...}` look different (perhaps smaller with a slightly different background and a border), and give it a tooltip on hover. That way it's not mimicking inline syntax, rather it's a _symbol_ marking some special behavior. But still ideally copy-pastes as `{..}` so that people implementing the trait by copy-paste will notice.

**Comment by GuillaumeGomez** [comment]
I also really like @jsha's suggestion with the two sections.

@Manishearth: I'd prefer to avoid adding tooltips if possible but thanks to @jsha's explanation, I now understand the idea behind it.

**Comment by Urgau** [comment]
@jsha suggestion to have two distinct sections seems like a great idea. I'm a bit more nuanced with a proposed removal of `{ ... }`, but as long as a normal user can quickly see that the method is provided this seems fine.

**Comment by rol1510** [comment]
Did we come to a conclusion on this? Should I implement @jsha's suggestion?

**Comment by GuillaumeGomez** [comment]
I think the proposal with two sections got the most approval. Let's wait for a few days to give time to anyone who doesn't agree to express their opinion then you can open a PR.

**Comment by rol1510** [comment]
Do we keep the old style for the where clauses, or use the new one?

old:
image

new:
image

**Comment by GuillaumeGomez** [comment]
I find the older easier to read.

**Comment by Manishearth** [comment]
I actually kinda prefer the new one 🙃

**Comment by rol1510** [comment]
With the fixed spacer:

new:
image
image

old:
image
image

**Comment by rol1510** [comment]
This PR should now create the old style in the picture above. It also adds a few tests and fixes the `item-spacer`

If you like the new style more, just let me know and I'll add it back in.

**Comment by jsha** [comment]
Fwiw, I prefer the new style. :-) One note: the "provided methods" / "required methods" should start with `//`, not `#`, since that's the Rust comment style.

**Comment by GuillaumeGomez** [comment]
Despite personal preference, my only argument in favor of the old style is that it follows the rustfmt style. If we don't care, then since the majority seems to prefer the new style, I have nothing to add. ^^'

**Comment by rol1510** [comment]
The PR now creates the new style.

image

**Comment by rol1510** [comment]
I did a rebase an fixed the merge conflicts, but now the PR also contains changes to Cargo.toml and the submodules. Did I do this right?

**Comment by jsha** [comment]
Thanks for rebasing! One subtle thing I notice in the [latest screenshot](https://github.com/rust-lang/rust/pull/102842#issuecomment-1328143356): Under "provided methods", there is a semicolon at the end of the declaration. Since a declaration with a semicolon is used in source code to indicate "this is a required method," I think it would be better to omit the semicolon for the provided methods.

Also, would you mind updating the description at the top of the pull request with the latest design?

**Comment by rol1510** [comment]
> Thanks for rebasing! One subtle thing I notice in the [latest screenshot](https://github.com/rust-lang/rust/pull/102842#issuecomment-1328143356): Under "provided methods", there is a semicolon at the end of the declaration. Since a declaration with a semicolon is used in source code to indicate "this is a required method," I think it would be better to omit the semicolon for the provided methods.
> 
> Also, would you mind updating the description at the top of the pull request with the latest design?

I removed the semicolon and the description is now up to date.

**Review by notriddle — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks for starting the FCP @notriddle!

**Comment by Manishearth** [comment]
> Thanks for rebasing! One subtle thing I notice in the [latest screenshot](https://github.com/rust-lang/rust/pull/102842#issuecomment-1328143356): Under "provided methods", there is a semicolon at the end of the declaration. Since a declaration with a semicolon is used in source code to indicate "this is a required method," I think it would be better to omit the semicolon for the provided methods.

@jsha hmm, so I'm not sure I agree here: I kinda feel like we should either use the semicolon (making it real syntax), or stick in the brace pseudosyntax (or a third option where we stick in the braces with a `/* ... */` in them).

Thoughts?

**Comment by Manishearth** [comment]
@rfcbot concern provided-method-end-formatting ^^

**Comment by Manishearth** [comment]
@rfcbot resolve provided-method-end-formatting ^^

**Comment by Manishearth** [comment]
@rfcbot concern formatting of the end of provided methods

see https://github.com/rust-lang/rust/pull/102842#issuecomment-1364586600

**Comment by jsha** [comment]
I'm happy to yield to @Manishearth's opinion on this.

**Comment by Manishearth** [comment]
@rfcbot resolved formatting of the end of provided methods

(unless others disagree)

Please don't merge without changing this, though.

**Comment by Manishearth** [comment]
n.b. the end-of-method formatting still needs to be fixed

**Comment by camelid** [comment]
I know it's post-FCP, but just wanted to add that this looks great to me, as long as `{...}` is added back as Manish mentioned.

**Comment by jsha** [comment]
Looking back, I realize @Manishearth [proposed three possibilities for end-of-line](https://github.com/rust-lang/rust/pull/102842#issuecomment-1364586600) and we didn't consolidate on which one:

```rust
fn foo()
  where T: Debug;
```

(same as Required Methods, my preference among these threee)

```rust
fn foo()
  where T: Debug { ... }
```


```rust
fn foo()
  where T: Debug /* ... */
```

**Comment by Manishearth** [comment]
I'm fine with the semicolon or the braces, prefer the semi

**Comment by camelid** [comment]
I much prefer having a different end-of-line between required and provided methods. Otherwise, with a long list of methods, it's not immediately clear what's required and what's provided. In addition, people (e.g., me) would likely assume the semicolon means a method is required, which is what it means in code.

I'd prefer this option:

```rust
fn foo()
  where T: Debug { /* ... */ }
```

which is a common pseudocode usage for "unnecessary detail elided".

**Comment by jsha** [comment]
@camelid this is for the pseudo-code block at the top of the page, where required method have always come first, and provided methods have always come second. This PR further adds clarity to that by adding `// Required methods` and `// Provided methods` to the beginning of each section.

**Comment by camelid** [comment]
@jsha Yes, but when I use docs, I usually glance through the methods and might not notice the comment delineating between the sections. I like having the comments as an extra delineation between required and provided methods. But I'd prefer that methods' entries in the codeblock still make sense on their own, without having to look for which section they're under.

**Comment by camelid** [comment]
(Just to make sure I understood your comment: I thought that this PR also removes the `{ ... }` at the end of a provided method's entry, but I might have missed something when I was reading through.)

**Comment by rol1510** [comment]
I added the `{ ... }` at the end of the provided methods.

Now looks like this:
image

**Comment by lqd** [comment]
This only modifies rustdoc rendering and these benchmarks are all check/debug/opt, so this is noise. The results are corrections from https://github.com/rust-lang/rust/pull/107679#issuecomment-1418033948

@rustbot label: +perf-regression-triaged

**Pull request merged**
