### PR TITLE
book: fix formatting of module layout example

### PR DESCRIPTION
**Pull request by xitep**

### CODE REVIEW

**Comment by xitep** [comment]
Just noticed that the "creates and module" layout graph is broken [for nightlies](https://doc.rust-lang.org/nightly/book/crates-and-modules.html); hopefully this fixes the issue.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks!

**Comment by steveklabnik** [comment]
@bors: retry

seems spurious

**Comment by alexcrichton** [comment]
@bors: retry

* not sure why...

**Pull request merged**
