### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
@bors r+ rollup=iffy

(`libc` updates often break on FreeBSD)

**Comment by lnicola** [comment]
```
   Compiling memoffset v0.5.5
rustc exited with signal: 11 (core dumped)
error: could not compile `memoffset`
```

on NetBSD.

Has anyone seen something like this? I can't find similar errors (but it's harder to search because of the minimized comments).

**Comment by lnicola** [comment]
There's one similar failure in #86038.

**Comment by Urgau** [comment]
See https://github.com/rust-lang/rust/issues/90812

**Pull request merged**
