### PR TITLE
[WIP] Don't create inference variables for static regions

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Argh, apologies for not reviewing this one in a while. I plan to do a "reviewing sprint" next week and will try to give feedback then!

**Comment by JohnCSimon** [comment]
is this still WIP?

**Comment by JohnCSimon** [comment]
ping from triage:
@Aaron1011  
Returning to you to address merge conflicts and broken build after that switch back to `S-waiting-on-review`.
thanks.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@Aaron1011 
Can you post your status on this PR?

**Comment by nikomatsakis** [comment]
@Aaron1011 so it's been forever, but I'd like to know if I should review this PR -- I'd also appreciate some notes about what it is trying to do. =) I'm assuming given the `[WIP]` title and lack of updates that it doesn't make sense to review just yet.

**Comment by Aaron1011** [comment]
Unfortunately, I don't remember exactly what I was trying to accomplish here - I think it was something related to NLL diagnostics. I'm going to close this for now.

**Pull request closed without merging**
