### PR TITLE
Remove regex module from libunicode

### PR DESCRIPTION
**Pull request by lambda-fairy**
The regex crate keeps its own tables now (rust-lang/regex#41) so we
don't need them here.

[breaking-change]

### CODE REVIEW

**Comment by kwantam** [comment]
@lfairy you can remove the `general_category` and `script` modules to fix most of the unused code errors; those were only used by the `UNICODE_CLASSES` table in the `regex` module.

There's one other change necessary: get rid of the `other_derived` variable in `unicode.py`, which will make `unicode.py` not emit the `Default_Ignorable_Code_Point` table; again, this was only used in the `UNICODE_CLASSES` table.

**Comment by lfairy** [comment]
@kwantam Thanks for the tips. I've force pushed a fixed version with your suggestions.

@huonw re-r?

**Pull request merged**
