### PR TITLE
rustdoc: support methods on primitives in intra-doc links

### LINKED ISSUE #58598: intra-rustdoc links fail on primitive methods
I hit this in #58596.

For example, for this a.rs
```rust
//! [`Vec`] is fine.
//! [`Vec::len`] is fine.
//! [`char`] is fine.
//! [`char::len_utf8`] is not.
```
`rustdoc +nightly a.rs` produces
```
 --> a.rs:4:6
  |
4 | //! [`char::len_utf8`] is not.
  |      ^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
  |
  = note: #[warn(intra_doc_link_resolution_failure)] on by default
  = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
```

### PR DESCRIPTION
**Pull request by tspiteri**
Fixes #58598.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Comment by tspiteri** [comment]
> @ bors rollup-

@Centril I rebased onto master after #58100 (Transition librustdoc to Rust 2018) was merged and added a commit to fix the build; will this PR be rollup-ed again?

**Pull request merged**
