### PR TITLE
Directly add extension instead of using `Path::with_extension`

### PR DESCRIPTION
**Pull request by tbu-**
`Path::with_extension` has a nice footgun when the original path doesn't contain an extension: Anything after the last dot gets removed.

### CODE REVIEW

**Comment by Nadrieril** [comment]
Good spot!

@bors r+ rollup

**Comment by tbu-** [comment]
> Anything after the last dot gets removed.

Interesting. This was apparently already hit by the existing code, because the added suffix just got dropped entirely. ^^

**Comment by Nadrieril** [comment]
Do you think that might have been intentional?

**Comment by tbu-** [comment]
> Do you think that might have been intentional?

I don't think so. There's no point in adding a suffix that is immediately removed again. The `name_suffix` was purely dead code.

**Comment by fmease** [comment]
sync @bors r-

**Comment by Nadrieril** [comment]
The test failure is due to formatting, I'm surprised that tidy didn't catch it. Anyway, please run `rustfmt` and we should be good

**Comment by tbu-** [comment]
Autoformatted.

@rustbot ready

**Pull request merged**
