### PR TITLE
HirIdification: almost there

### PR DESCRIPTION
**Pull request by ljedrz**
The next iteration of HirIdification (#57578). Builds on #58915 (and thus can be appended to it).

Removes `NodeId` from:
- [x] `PathSegment`
- [x] `PatKind`
- [x] `Destination` (replaces it with `HirId`)

In addition this PR also removes `Visitor::visit_def_mention`, which doesn't seem to be doing anything.

r? @Zoxc

### CODE REVIEW

**Comment by ljedrz** [comment]
I believe this time I might even break RLS ^^. I'll test it and post fixes soon.

**Comment by ljedrz** [comment]
@Xanewok I'm basing this assumption on the comment on `PathSegment`'s `id`, i.e. that it is used in `save_analysis`. Perhaps it won't be an issue at all :crossed_fingers:.

**Comment by Zoxc** [comment]
Looks good. Feel free to append it to https://github.com/rust-lang/rust/pull/58915

**Comment by ljedrz** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/58915 which is higher in the queue.

**Pull request closed without merging**
