### PR TITLE
[DONT MERGE] Test min capture

### PR DESCRIPTION
**Pull request by arora-aman**
New capture analysis for RFC 2229. 

- This PR is to just test the entire bors try suite passes if the feature was to be enabled by default.
- Know issue: `let _ =  <Place>` statements  aren't handled properly in closures yet.
- Modified some ui tests to bypass the issue mentioned above.
- Regions for captures maybe created in a different order than before, so updated ui tests to reflect that as well.

r? @ghost

### CODE REVIEW

**Comment by lqd** [comment]
@rust-timer queue

**Comment by arora-aman** [comment]
Closing this since the #78801 got merged

**Pull request closed without merging**
