### PR TITLE
Symlink `build/host` -> `build/$HOST_TRIPLE`

### PR DESCRIPTION
**Pull request by jyn514**
(as appropriate per target)

This allows us to use a consistent path in the documentation, without having to worry about which platform people are using.

### CODE REVIEW

**Comment by camelid** [comment]
Might it be clearer to replace the linux target triple in the title with `$HOST` or something similar? Otherwise it's a bit confusing.

**Comment by Mark-Simulacrum** [comment]
I feel like "host" here is a bit confusing -- it's the build triple, not the host (of which there can be multiple).

I can't say I have better names though and in practice host is ~nearly right so maybe we should just not worry about this.

r=me if you don't have any different ideas.

**Comment by camelid** [comment]
> I feel like "host" here is a bit confusing -- it's the build triple, not the host (of which there can be multiple).

Just to clarify, are you talking about there being multiple directories in the case of cross-compilation? In that case, I would assume this PR only symlinks to the host's corresponding build directory. (Apologies if I misunderstood.)

**Comment by Mark-Simulacrum** [comment]
Yes, when cross-compiling. I'm not sure we require that the build platform is *one of* the host platforms.

**Comment by jyn514** [comment]
@Mark-Simulacrum how does `build_triple` sound?

**Comment by Mark-Simulacrum** [comment]
Not opposed, though I can't call myself enthusiastic about it either :)

**Comment by jyn514** [comment]
I think I'm going to keep it as `host`. Having a host that doesn't match `build` is very rare, and `build` is too ambiguous to be clear, even when using `build_triple`. People can always use `ls -l build/host` to see what target is actually being used.

**Pull request merged**
