### PR TITLE
Revert #63649 - "Upgrade Emscripten targets to use upstream LLVM backend"

### PR DESCRIPTION
**Pull request by tmandry**
This change caused the runtime of the linux-asmjs builder to nearly double from 2+ hours to about 4 hours, which happens to be the bors timeout. (It made it in barely under 4 hours when it was merged.) This is causing timeouts on all new changes.

This reverts commit 7870050796e5904a0fc85ecbe6fa6dde1cfe0c91, reversing
changes made to 2e7244807a7878f6eca3eb7d97ae9b413aa49014.

### CODE REVIEW

**Comment by tmandry** [comment]
Self-approving since this is a revert to unblock bors, and no one seems to be around.
@bors r+ p=3

**Comment by alexcrichton** [comment]
Analysis here looks spot on and agree with reverting while this is figured out. This shows a 1.5 he jump in testing time for the asmjs builder

https://alexcrichton.github.io/rust-ci-timing-tracker/commit.html#job=asmjs&commit=2e7244807a7878f6eca3eb7d97ae9b413aa49014,7870050796e5904a0fc85ecbe6fa6dde1cfe0c91&relative=true&col=1&desc=true

**Comment by tlively** [comment]
@alexcrichton I did some profiling and the bulk of the Emscripten link time for the tests is spent in the JS optimizer, optimizing the output of wasm2js. This time can be eliminated or reduced by changing the optimization level Emscripten uses when running the tests. Another option is to replace the asmjs-unknown-emscripten testing with wasm32-unknown-emscripten testing, which would skip the wasm2js and JS optimizing steps entirely.

I took some measurements on a sample of 489 tests with various optimization options.
```
-O2 asmjs: finished in 922s
-O1 asmjs: finished in 361s
-O0 asmjs: finished in 305s

-O2 wasm: finished in 354s
-O1 wasm: finished in 254s
-O0 wasm: finished in 228s
```

Based on this analysis I think it would be best to just switch over to testing wasm32-unknown-emscripten or to switch to using -O1 with asmjs. What do you think would be best?

**Comment by alexcrichton** [comment]
@tlively I think it should be fine to switch to wasm32-unknown-emscripten and testing with -O1, that sounds like a good sweet spot!

**Comment by tlively** [comment]
@alexcrichton, https://github.com/rust-lang/cargo/pull/7476 was pulled into the cargo submodule in https://github.com/rust-lang/rust/pull/65186, but when I test locally it uses the stage0 cargo which does not include that fix. Will the CI use the in-tree cargo to run tests or the old stage0 cargo? If the latter, when can I expect the stage0 cargo to be updated to include https://github.com/rust-lang/cargo/pull/7476? If it will be a while, we probably want to stick with testing asmjs with -O1 for now.

**Comment by alexcrichton** [comment]
@tlively we always use the beta channel Cargo on the master branch's CI for tests, but if we temporarily ignore testing on wasm/emscripten for now to reenable later that's ok too!

**Pull request merged**
