### PR TITLE
Stabilize bindings_after_at

### PR DESCRIPTION
**Pull request by MarcusDunn**
attempting to stabilze bindings_after_at [#65490](https://github.com/rust-lang/rust/issues/65490), im pretty new to the whole thing so any pointers are greatly appreciated.

### CODE REVIEW

**Comment by MarcusDunn** [comment]
Alright, I think this is mostly okay, I'm uncertain on what I should do with [E0303.md](https://github.com/rust-lang/rust/blob/master/compiler/rustc_error_codes/src/error_codes/E0303.md) as it references the feature flag, it also is no longer used so I do not know procedure for updating it. I've left it untouched for now but I think it should probably be changed in some way even if it's just there for historical reasons at the moment.  I also am unsure if making this stable means anything for the reference. To me the feature seems more or less implied by the reference currently, but I think an example of it would not go ammiss in the patterns section.

**Comment by workingjubilee** [comment]
> Fetched in submodule path 'src/doc/reference', but it did not contain f2803ae48185e5c3d900ebd27b79976724570967. Direct fetching of that commit failed.

@MarcusDunn The reference is a submodule, it cannot actually be directly affected from here. You should `git reset HEAD~1 --hard`, force push that, and another PR against `rust-lang/reference` in order to apply changes against it.

**Comment by workingjubilee** [comment]
Because this is a language feature, `/compiler/*` and `/library/*` will require allowing the feature during bootstrap only, so that the bootstrap compiler opens the feature gates still while the next compiler stage does not.
```rust
#![cfg_attr(bootstrap, feature(bindings_after_at))]
```

**Comment by workingjubilee** [comment]
Stabilization report is [here](https://github.com/rust-lang/rust/issues/65490#issuecomment-841999009).
Nominating for T-lang.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

The [stabilization report](https://github.com/rust-lang/rust/issues/65490#issuecomment-841999009) here is pretty short, but the TL;DR from my POV is that we removed the ability to have "nested" bindings like `a @ (b, c)` because of soundness concerns with the old borrow checker, but the new borrow checker should be able to handle this no problem, because matches are desugared into individual borrows and statements.

**Comment by scottmcm** [comment]
Hooray for MIR!

**Comment by bstrie** [comment]
Just to make sure, #65490 mentions:

> any attempt to re-enable the feature should also attempt to re-add all the tests that were removed with PR #16053

Have those tests been re-added previously?

**Comment by programmerjake** [comment]
ping, shouldn't this be merged now?

**Pull request merged**
