### PR TITLE
Add illumos aarch64 target for rust.

### PR DESCRIPTION
**Pull request by Toasterson**
This adds the newly being developed illumos aarch64 target to the rust compiler. 

@rmustacc @citrus-it @richlowe As promissed before my hiatus :)

### CODE REVIEW

**Comment by compiler-errors** [comment]
I think this needs an MCP since it's adding a new tier 3 target, right? (coincidentally just asked the same thing for another target proposal this morning -- https://github.com/rust-lang/rust/issues/112930#issuecomment-1602994203)

**Comment by Toasterson** [comment]
I don't see a reason not to make one. I'll gladly talk about the project and what one can expect where this target goes :) I'll have to sync with people a bit to have the plans in details but could do it in a couple days time.

**Comment by compiler-errors** [comment]
Alright, marking this as waiting on author until this gets an MCP

@rustbot author

**Comment by Toasterson** [comment]
Added a new MCP for this and the probable other PR's for the illumos Tier3 Targets. https://github.com/rust-lang/compiler-team/issues/644

**Comment by workingjubilee** [comment]
An MCP is technically not required. Rather, what is actually important is the requirements of the [target tier policy] are addressed by the author and the compiler team reviews it. An MCP is simply a vessel for that review.

[target tier policy]: https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html

**Comment by fee1-dead** [comment]
cc #115089

r? compiler

**Comment by apiraino** [comment]
Waiting for MCP [compiler-team#644](https://github.com/rust-lang/compiler-team/issues/644) to complete.

@rustbot label +s-waiting-on-mcp -s-waiting-on-author

**Comment by workingjubilee** [comment]
Accepted, so all this needs is a rebase.

**Comment by Toasterson** [comment]
Done, I hope I did everything right here.

**Comment by Nilstrieb** [comment]
you have a merge commit: b16a66ffe768ec63623475b99eeacd36656f60c0
we don't accept merge commits here, you should to rebase it away

**Comment by Toasterson** [comment]
> you have a merge commit: [b16a66f](https://github.com/rust-lang/rust/commit/b16a66ffe768ec63623475b99eeacd36656f60c0) we don't accept merge commits here, you should to rebase it away

Done. Let me know if anything else is missing.

**Comment by wesleywiser** [comment]
Hi @Toasterson, sorry for the delay on this! I think this is pretty much ready to be merged but we need an explicit signoff from you that this target adheres to the tier 3 target policy. Could you please quote the corresponding requirements verbatim from the [tier 3 target tier policy](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-3-target-policy) to explain how the target meets those requirements (leaving a new comment here is fine). You can find an example of this in the PR description for #86191. Thank you!

**Comment by Toasterson** [comment]
Sorry for the delay, I lost my notes and needed to rebuild the Guide from scratch.
Along the way I also rebased the changes and updates some bugs that happened with the rebased that I don't remember if they existed before or not. In any case, I can get binaries cross compiled, but not the compiler as the psm crate aborts while calling GCC.

So let's get down to the Target tier policy

> A tier 3 target must have a designated developer or developers (the "target maintainers") on record to be CCed when issues arise regarding the target. (The mechanism to track and CC such developers may evolve over time.)

That would be me and the other illumos developers. You can add me to CC on the other illumos target aswell, I am a primary rust user and will use illumos in the future.

> Targets must use naming consistent with any existing targets; for instance, a target for the same CPU or OS as an existing Rust target should use the same name for that CPU or OS. Targets should normally use the same names and naming conventions as used elsewhere in the broader ecosystem beyond Rust (such as in other toolchains), unless they have a very good reason to diverge. Changing the name of a target can be highly disruptive, especially once the target reaches a higher tier, so getting the name right is important even for a tier 3 target.
    - Target names should not introduce undue confusion or ambiguity unless absolutely necessary to maintain ecosystem compatibility. For example, if the name of the target makes people extremely likely to form incorrect beliefs about what it targets, the name should be changed or augmented to disambiguate it.
    - If possible, use only letters, numbers, dashes and underscores for the name. Periods (`.`) are known to cause issues in Cargo.

Done

> Tier 3 targets may have unusual requirements to build or use, but must not create legal issues or impose onerous legal terms for the Rust project or for Rust developers or users.
    - The target must not introduce license incompatibilities.
    - Anything added to the Rust repository must be under the standard Rust license (`MIT OR Apache-2.0`).
    - The target must not cause the Rust tools or libraries built for any other host (even when supporting cross-compilation to the target) to depend on any new dependency less permissive than the Rust licensing policy. This applies whether the dependency is a Rust crate that would require adding new license exceptions (as specified by the `tidy` tool in the rust-lang/rust repository), or whether the dependency is a native library or binary. In other words, the introduction of the target must not cause a user installing or running a version of Rust or the Rust tools to be subject to any new license requirements.
    - Compiling, linking, and emitting functional binaries, libraries, or other code for the target (whether hosted on the target itself or cross-compiling from another target) must not depend on proprietary (non-FOSS) libraries. Host tools built for the target itself may depend on the ordinary runtime libraries supplied by the platform and commonly used by other applications built for the target, but those libraries must not be required for code generation for the target; cross-compilation to the target must not require such libraries at all. For instance, `rustc` built for the target may depend on a common proprietary C runtime library or console output library, but must not depend on a proprietary code generation library or code optimization library. Rust's license permits such combinations, but the Rust project has no interest in maintaining such combinations within the scope of Rust itself, even at tier 3.
    - "onerous" here is an intentionally subjective term. At a minimum, "onerous" legal/licensing terms include but are _not_ limited to: non-disclosure requirements, non-compete requirements, contributor license agreements (CLAs) or equivalent, "non-commercial"/"research-only"/etc terms, requirements conditional on the employer or employment of any particular Rust developers, revocable terms, any requirements that create liability for the Rust project or its developers or users, or any requirements that adversely affect the livelihood or prospects of the Rust project or its developers or users.

No problem for any illumos target.

> Neither this policy nor any decisions made regarding targets shall create any binding agreement or estoppel by any party. If any member of an approving Rust team serves as one of the maintainers of a target, or has any legal or employment requirement (explicit or implicit) that might affect their decisions regarding a target, they must recuse themselves from any approval decisions regarding the target's tier status, though they may otherwise participate in discussions.
    - This requirement does not prevent part or all of this policy from being cited in an explicit contract or work agreement (e.g. to implement or maintain support for a target). This requirement exists to ensure that a developer or team responsible for reviewing and approving a target does not face any legal threats or obligations that would prevent them from freely exercising their judgment in such approval, even if such judgment involves subjective matters or goes beyond the letter of these requirements.

No problem here.

> Tier 3 targets should attempt to implement as much of the standard libraries as possible and appropriate (`core` for most targets, `alloc` for targets that can support dynamic memory allocation, `std` for targets with an operating system or equivalent layer of system-provided functionality), but may leave some code unimplemented (either unavailable or stubbed out as appropriate), whether because the target makes it impossible to implement or challenging to implement. The authors of pull requests are not obligated to avoid calling any portions of the standard library on the basis of a tier 3 target not implementing those portions.

All the existing illumos x86_64 support works here aswell. We just add a Processor architecture.

> The target must provide documentation for the Rust community explaining how to build for the target, using cross-compilation if possible. If the target supports running binaries, or running tests (even if they do not pass), the documentation must explain how to run such binaries or tests for the target, using emulation if possible or dedicated hardware if necessary.

Cross compilation Guide: https://gist.github.com/Toasterson/90d19ecf4e0b69cfbcd9566a7c098eb8


Any native toolchains will be available via packages. So that people can test rust releases if they want. Request other guides as needed. I'll happily provide starter images aswell if people want some base VM's for ARM. For x86 vagrant images are available via

```bash
vagrant init openindiana/hipster
vagrant up
```

> Tier 3 targets must not impose burden on the authors of pull requests, or other developers in the community, to maintain the target. In particular, do not post comments (automated or manual) on a PR that derail or suggest a block on the PR based on a tier 3 target. Do not send automated messages or notifications (via any medium, including via `@`) to a PR author or others involved with a PR regarding a tier 3 target, unless they have opted into such messages.
    - Backlinks such as those generated by the issue/PR tracker when linking to an issue or PR are not considered a violation of this policy, within reason. However, such messages (even on a separate repository) must not generate notifications to anyone involved with a PR who has not requested such notifications.

Ok, will do

> Patches adding or updating tier 3 targets must not break any existing tier 2 or tier 1 target, and must not knowingly break another tier 3 target without approval of either the compiler team or the maintainers of the other tier 3 target.
    - In particular, this may come up when working on closely related targets, such as variations of the same architecture with different features. Avoid introducing unconditional uses of features that another variation of the target may not have; use conditional compilation or runtime detection, as appropriate, to let each target run code supported by that target.

Will do.

Ok, Last part. I currently run into the following problem when cross compiling `rustc`.

```
error: failed to run custom build command for `psm v0.1.21`

Caused by:
  process didn't exit successfully: `/var/lib/abuild/rust/build/x86_64-unknown-illumos/stage1-rustc/release/build/psm-61c9c6ef89c427d5/build-script-build` (exit status: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-unknown-illumos")
  HOST = Some("x86_64-unknown-illumos")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-illumos
  CC_aarch64-unknown-illumos = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_illumos
  CC_aarch64_unknown_illumos = Some("gcc")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-illumos
  CFLAGS_aarch64-unknown-illumos = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_illumos
  CFLAGS_aarch64_unknown_illumos = Some("-ffunction-sections -fdata-sections -fPIC")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  cargo:rustc-cfg=asm
  cargo:rustc-cfg=switchable_stack
  running: "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "-xassembler-with-cpp" "-DCFG_TARGET_OS_illumos" "-DCFG_TARGET_ARCH_aarch64" "-DCFG_TARGET_ENV_" "-o" "/var/lib/abuild/rust/build/x86_64-unknown-illumos/stage1-rustc/aarch64-unknown-illumos/release/build/psm-a54651dd69990eb0/out/src/arch/aarch_aapcs64.o" "-c" "src/arch/aarch_aapcs64.s"
  cargo:warning=src/arch/aarch_aapcs64.s: Assembler messages:
  cargo:warning=src/arch/aarch_aapcs64.s:35: Error: no such instruction: `orr w0,wzr,'
  cargo:warning=src/arch/aarch_aapcs64.s:48: Error: operand size mismatch for `mov'
  cargo:warning=src/arch/aarch_aapcs64.s:62: Error: operand size mismatch for `mov'
  cargo:warning=src/arch/aarch_aapcs64.s:63: Error: no such instruction: `br x1'
  cargo:warning=src/arch/aarch_aapcs64.s:75: Error: no such instruction: `stp x29,x30,[sp,'
  cargo:warning=src/arch/aarch_aapcs64.s:76: Error: bad register expression
  cargo:warning=src/arch/aarch_aapcs64.s:77: Error: operand size mismatch for `mov'
  cargo:warning=src/arch/aarch_aapcs64.s:78: Error: bad register expression
  cargo:warning=src/arch/aarch_aapcs64.s:79: Error: bad register expression
  cargo:warning=src/arch/aarch_aapcs64.s:80: Error: bad register expression
  cargo:warning=src/arch/aarch_aapcs64.s:81: Error: operand size mismatch for `mov'
  cargo:warning=src/arch/aarch_aapcs64.s:82: Error: no such instruction: `blr x2'
  cargo:warning=src/arch/aarch_aapcs64.s:83: Error: operand size mismatch for `mov'
  cargo:warning=src/arch/aarch_aapcs64.s:84: Error: bad register expression
  cargo:warning=src/arch/aarch_aapcs64.s:85: Error: no such instruction: `ldp x29,x30,[sp],'
  cargo:warning=src/arch/aarch_aapcs64.s:86: Error: bad register expression
  cargo:warning=src/arch/aarch_aapcs64.s:87: Error: bad register expression
  cargo:warning=src/arch/aarch_aapcs64.s:88: Error: bad register expression
  exit status: 1

  --- stderr


  error occurred: Command "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "-xassembler-with-cpp" "-DCFG_TARGET_OS_illumos" "-DCFG_TARGET_ARCH_aarch64" "-DCFG_TARGET_ENV_" "-o" "/var/lib/abuild/rust/build/x86_64-unknown-illumos/stage1-rustc/aarch64-unknown-illumos/release/build/psm-a54651dd69990eb0/out/src/arch/aarch_aapcs64.o" "-c" "src/arch/aarch_aapcs64.s" with args "gcc" did not execute successfully (status code exit status: 1).

```

But I can produce a `hello-world` binary.
Any Project will need the following `.cargo/config` to cross compile from illumos x86.
```toml
[target.aarch64-unknown-illumos]
linker = "/var/lib/abuild/arm64-gate/build/cross/bin/aarch64-unknown-solaris2.11-gcc"
rustflags = [ "-Clink-arg=--sysroot=/var/lib/abuild/arm64-gate/build/sysroot" ]
```

**Comment by jackh726** [comment]
Thanks! That's all we need for @bors r+ rollup

**Pull request merged**
