### PR TITLE
Don't use remapped path when loading modules and include files

### PR DESCRIPTION
**Pull request by philipc**
Fixes bug reported in https://github.com/rust-lang/rust/issues/41555#issuecomment-327866056.

cc @michaelwoerister

### CODE REVIEW

**Comment by philipc** [comment]
`./x.py test src/test/run-make` passes for me locally, so I don't know why travis failed.

There's at least one `span_to_filename` usage [in librustdoc](https://github.com/rust-lang/rust/blob/afe9320785efa17ea1adbdab299a6aaf2c575e87/src/librustdoc/test.rs#L564) that is still wrong. The problem with it is that the result is used for both input and display purposes, so the change to fix it will be more extensive, probably requiring passing around both the original path and the remapped name. I can work on that if this sounds like the right approach. There's a couple more `span_to_filename` uses in librustdoc that I haven't investigated fully.

Also, anywhere that converts strings to `PathBuf` seems error prone, since we don't know if the string is a real path, or if it was lossily converted from a path, or if it isn't a path at all. In this PR I've moved an occurrence of this from the callers of `span_to_filename` into `new_filemap`. I initially tried to avoid this completely, but that was going to be a much larger change to all the callers of `new_filemap`. Is this worth pursuing?

**Comment by michaelwoerister** [comment]
Thanks a lot for the PR, @philipc! I'll take a closer look shortly.

**Comment by michaelwoerister** [comment]
Looks like an excellent start! Some comments:

> ./x.py test src/test/run-make passes for me locally, so I don't know why travis failed.

This seems to be a spurious failure probably not related to your PR: https://github.com/rust-lang/rust/issues/43402

> There's at least one span_to_filename usage in librustdoc that is still wrong. The problem with it is that the result is used for both input and display purposes, so the change to fix it will be more extensive, probably requiring passing around both the original path and the remapped name. I can work on that if this sounds like the right approach. There's a couple more span_to_filename uses in librustdoc that I haven't investigated fully. 

Could you just add a FIXME comment to those and link to this PR? I don't think it's possible to invoke rustdoc with path remapping anyway.

> Also, anywhere that converts strings to PathBuf seems error prone, since we don't know if the string is a real path, or if it was lossily converted from a path, or if it isn't a path at all. In this PR I've moved an occurrence of this from the callers of span_to_filename into new_filemap. I initially tried to avoid this completely, but that was going to be a much larger change to all the callers of new_filemap. Is this worth pursuing?

Let's keep this PR focussed, I'd say. The other changes can still be done later.

Some minor comments regarding the implementation:
* I would prefer a different name for the `path` field, for example `fs_path` or `unmapped_path` -- something blunt `:)` (and `CodeMap::span_to_path()` should then also be named accordingly)
* Intended or not, this PR does the right thing for reproducible builds in that it does not serialize the `path` field into crate metadata. However, I'd prefer if the field was an `Option<Path>` to make this more explicit. `span_to_path()` can call `.expect("CodeMap::span_to_path() called for imported file-map?")` to make things easy.

Otherwise this looks great already!

**Comment by philipc** [comment]
> I don't think it's possible to invoke rustdoc with path remapping anyway.

Is this something that should be possible though? Do distributions want to package the generated doc, and have the src links point to the remapped location?

I'll address the other comments, thanks for reviewing.

**Comment by michaelwoerister** [comment]
> Is this something that should be possible though? Do distributions want to package the generated doc, and have the src links point to the remapped location?

I could imagine so. But since the current `rustdoc` implementation will be replaced by one that coupled less tightly to the compiler internals, I don't think we need to solve this here.

**Comment by philipc** [comment]
I've updated `FileMap::path` as requested.

Also added a FIXME for doctests, but not sure how useful it is.

**Comment by michaelwoerister** [comment]
@bors r+

Excellent, thanks a lot, @philipc!

**Pull request merged**
