### PR TITLE
Create `dummy_{source,sink}` lazily.

### PR DESCRIPTION
**Pull request by nnethercote**
Because they're rarely needed. This gives a very small but very easy perf win.

r? @lqd

### CODE REVIEW

**Comment by nnethercote** [comment]
I will let the perf run finish for completeness, but I found a different improvement that subsumes this one in #110527.

r? @ghost

**Comment by lqd** [comment]
I can just review the other PR.

**Comment by nnethercote** [comment]
Closing this in favour of #110527.

**Pull request closed without merging**
