### PR TITLE
Rustbuild regression fixes

### LINKED ISSUE #43427: Latest Rust nightly does not work on FreeBSD
I'm not sure when exactly it broke, but I suspect within the last few days. When I run `rustc` now, I get:

```
$ rustc
ELF binary type "0" not known.
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: ELF: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: ?gߓ?4????O06???: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: DD: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: ?T: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: Wui: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: 6: Syntax error: ")" unexpected
```

And the output of `readelf -h $(which rustc)` is the following:

```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 09 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - FreeBSD
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0xa4420
  Start of program headers:          64 (bytes into file)
  Start of section headers:          11889304 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         44
  Section header string table index: 41
```

I'm using the latest version of Rustup, if it makes a difference. Did the build script get botched recently, or something?

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
I believe this will fix https://github.com/rust-lang/rust/issues/43427.

This PR also avoids running pretty tests by-default.

r? @alexcrichton

### CODE REVIEW

**Comment by kennytm** [comment]
[Fuchsia](https://travis-ci.org/rust-lang/rust/jobs/256706487) failed to build LLVM at stage1 (why?). Legit.

```
[00:52:07] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "target `x86_64-unknown-fuchsia` is not configured as a host, only as a target"', /checkout/src/libcore/result.rs:860
```

**Comment by Mark-Simulacrum** [comment]
@bors r=alexcrichton

I believe the last commit makes dist and install equivalent to what the old build system ran, which should hopefully resolve our issues.

**Comment by kennytm** [comment]
@Mark-Simulacrum The PR CI failed to build bootstrap. 

```
[00:01:17]    Compiling bootstrap v0.0.0 (file:///checkout/src/bootstrap)
[00:01:18] error[E0560]: struct `dist::DebuggerScripts` has no field named `target`
[00:01:18]    --> /checkout/src/bootstrap/check.rs:538:17
[00:01:18]     |
[00:01:18] 538 |                 target: target
[00:01:18]     |                 ^^^^^^^ field does not exist - did you mean `host`?
[00:01:18] 
[00:01:19] error[E0560]: struct `dist::DebuggerScripts` has no field named `target`
[00:01:19]    --> /checkout/src/bootstrap/dist.rs:435:17
[00:01:19]     |
[00:01:19] 435 |                 target: host,
[00:01:19]     |                 ^^^^^^^ field does not exist - did you mean `host`?
[00:01:19] 
[00:01:19] error[E0560]: struct `dist::Extended` has no field named `compiler`
[00:01:19]     --> /checkout/src/bootstrap/dist.rs:1103:13
[00:01:19]      |
[00:01:19] 1103 |             compiler: run.builder.top_stage,
[00:01:19]      |             ^^^^^^^^^ field does not exist - did you mean `stage`?
```

**Comment by Mark-Simulacrum** [comment]
@bors retry
 - https://github.com/rust-lang/rust/issues/43453

```
[01:21:53] 
[01:21:53] failures:
[01:21:53] 
[01:21:53] ---- test::test_borrow_error stdout ----
[01:21:53] 	thread 'test::test_borrow_error' panicked at 'Hit timeout', /checkout/src/tools/rls/src/test/harness.rs:142:12
[01:21:53] 
[01:21:53] 
[01:21:53] failures:
[01:21:53]     test::test_borrow_error
```

**Pull request merged**
