### PR TITLE
 do not use assume_init in std::io

### PR DESCRIPTION
**Pull request by RalfJung**
Cc https://github.com/rust-lang/rust/issues/62397

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r-

Will investigate CI failure.

**Comment by RalfJung** [comment]
This should do it.

@bors r=KodrAus

**Comment by RalfJung** [comment]
A similar PR landed (https://github.com/rust-lang/rust/pull/62732), but I think the solution here is better because it avoids by-value uninitialized integers (at avoids `assume_init` entirely). @KodrAus could you have another look?

Cc @nathanwhit @lzutao @Amanieu

**Comment by KodrAus** [comment]
Hmm ok, I'm going to assume it's better for us to have only one set of open validity properties to consider here rather than two, and linking back to the tracking issue is nice so...

@bors r+

**Pull request merged**
