### PR TITLE
ci: use GCC 13 as cross compiler in `dist-aarch64-linux`

### PR DESCRIPTION
**Pull request by XrXr**
I'm proposing this GCC upgrade since it addresses bug https://github.com/rust-lang/rust/issues/125619. The
regression in question affects stable release consumers who tend to have
no exposure to Rust build tools, so if at all possible, I would like to
have it resolved in the next stable release. I have tried to fix the bug
in `compiler-builtins`, which led to submitting a PR for `compiler-rt`
in upstream LLVM, but it may take a long time before these upstreams
address this regression.

A summary of why upgrading GCC solves the regression follows.
`__multc3()` is a builtin function `compiler-builtins` exposes for
specifically aarch64, non-Windows targets [1]. The object file for it is
included in `staticlib` archives through `libstd`. The implementation
for `__multc3()` is from `multc3.c`, part of LLVM's `compiler-rt`.
Upstream `compiler-rt` normally builds the C file using the Clang
from the same LLVM version. On the other hand, `compiler-builtins`
builds the C file using GCC, outside of the usual LLVM build system.
The upstream implementation doesn't have feature detection which
works for GCC version older than 10, and ends up producing an
unlinkable object.

Upstream LLVM might be slow to respond to this issue as they might deem
`compiler-builtin` as doing something out of the ordinary from their
perspective. They might reasonably assume everyone builds `compiler-rt`
through LLVM's build system.

I have done the following to test this change:
 - verified that a local build without this patch exhibits the
   regression.
 - verified that with this patch, the object for `__multc3()` has no
   reference to undefined functions in the symbol table.
 - verified that with this patch, `rustc` is usable to build Ruby with
   YJIT, and that the reported regression is resolved.

Since `loongarch64-linux-gnu` already uses GCC 13.2.0, I hope we can upgrade without issues.

try-job: dist-aarch64-linux

[1]: https://github.com/rust-lang/compiler-builtins/blob/c04eb9e1afb72bdf943f5e5d77b3812f40526602/build.rs#L524-L539

### CODE REVIEW

**Comment by Kobzol** [comment]
@cuviper You have last touched the crosstool-ng configuration :) Do you think it's fine in general to upgrade GCC from 8 to 13, is the old(er) version important for anything specific? I seem to recall some issues with updating GCC too much on the x64 Linux runner.

**Comment by cuviper** [comment]
@Kobzol I'm not sure what issues you're recalling, but there is some risk of symbol versioning trouble with `libgcc_s.so.1`, which we haven't been very careful about like we have for glibc versions. I think they don't change as often as glibc though. Here's what I see in that library on Ubuntu 24.04 aarch64:

```
    40: 000000000000fc20   308 FUNC    GLOBAL DEFAULT   12 __extendhftf2@@GCC_11.0
    89: 0000000000011820   244 FUNC    GLOBAL DEFAULT   12 __fixunshfti@@GCC_11.0
    99: 0000000000004260  1008 FUNC    GLOBAL DEFAULT   12 __mulhc3@@GCC_11.0
   103: 0000000000011920   656 FUNC    GLOBAL DEFAULT   12 __floattihf@@GCC_11.0
   105: 00000000000105a0   920 FUNC    GLOBAL DEFAULT   12 __trunctfhf2@@GCC_11.0
   117: 00000000000052a0   652 FUNC    GLOBAL DEFAULT   12 __divhc3@@GCC_11.0
   204: 0000000000011bc0   424 FUNC    GLOBAL DEFAULT   12 __floatuntihf@@GCC_11.0
   205: 0000000000011720   248 FUNC    GLOBAL DEFAULT   12 __fixhfti@@GCC_11.0
    83: 0000000000011f60   344 FUNC    GLOBAL DEFAULT   12 __floatundibf@@GCC_13.0.0
    86: 0000000000010ce0   904 FUNC    GLOBAL DEFAULT   12 __truncdfbf2@@GCC_13.0.0
   112: 0000000000012360   516 FUNC    GLOBAL DEFAULT   12 __floatuntibf@@GCC_13.0.0
   118: 0000000000010940   920 FUNC    GLOBAL DEFAULT   12 __trunctfbf2@@GCC_13.0.0
   119: 00000000000113a0   876 FUNC    GLOBAL DEFAULT   12 __trunchfbf2@@GCC_13.0.0
   132: 0000000000011d80   460 FUNC    GLOBAL DEFAULT   12 __floatdibf@@GCC_13.0.0
   149: 0000000000011080   792 FUNC    GLOBAL DEFAULT   12 __truncsfbf2@@GCC_13.0.0
   152: 000000000000fd60   216 FUNC    GLOBAL DEFAULT   12 __extendbfsf2@@GCC_13.0.0
   182: 00000000000120c0   664 FUNC    GLOBAL DEFAULT   12 __floattibf@@GCC_13.0.0
```

... and there are more for `@@GCC_14.0.0`. But looking at both Fedora's and Ubuntu's Rust toolchains that did build with newer GCC, I don't see any newer symbols being used.

**Comment by Kobzol** [comment]
Thanks for checking!

I think I remembered now - the issue just was that GCC 9+ couldn't be built with GCC 4, that we use on CI. But that shouldn't be an issue for crosstool.

**Comment by XrXr** [comment]
I don't know if I have permissions to do this, but I'm curious if this passes CI.

@bors try

**Comment by cuviper** [comment]
> try-job: dist-aarch64-linux

Ooh, I haven't seen that in action yet, neat!

**Comment by Kobzol** [comment]
CI job looked ok, and beta has just branched, so let's merge and see if it causes any problems downstream.

@bors r+ rollup=never

**Pull request merged**
