### PR TITLE
Deprecate Vec::as_{mut_,}slice

### LINKED ISSUE #25622: Improve documentation for Vec::as_slice
`Vec::as_slice` and `Vec::as_mut_slice` are both marked unstable with reason "waiting on RFC revision."  But the docs for `as_mut_slice` say that it is deprecated.

If these methods are deprecated, they should be marked deprecated instead of unstable.  And either way, a hint should be added regarding how to replace `Vec::as_slice` in old code.

[moved from rust-lang/rfcs#1128]

### PR DESCRIPTION
**Pull request by steveklabnik**
Slicing syntax should be used instead.

Fixes #25622

### CODE REVIEW

**Comment by alexcrichton** [comment]
These conversions are actually intentionally remaining and are destined to become stable one day (not sure we've had the right revision to the RFC yet). The plan is to add *explicit* conversions between types (for example `.as_slice`, `.as_os_str`, `.as_bytes`, etc), in addition to `AsRef` implementations (where possible). These methods are very rarely used today, and most uses can be subsumed by deref coercions, but the convention is more widely applicable to other types (for example `Path` does not deref to `OsStr` but converting to one is done via `.as_os_str`).

I believe that @aturon is working on a PR to shard the global "core" feature, and hopefully these will be dealt with as a part of that!

**Comment by steveklabnik** [comment]
Ah! Cool.

**Comment by bluss** [comment]
@alexcrichton I'm sceptical. We already have so many ways to do these conversions, I don't want Rust to be the language where "there's a thousand ways to do it".

**Comment by alexcrichton** [comment]
Right, an RFC was intended to fill in the gaps here to clear it up, but the conventions are:

* Implement the `std::convert` traits as necessary for your type.
* If you have a *very common* conversion from one type to another (e.g. `Path` to `OsStr`, `&T: Display` to `String`) then a specific method is provided to perform the conversion.

This isn't just blanket adding methods for all conversions possible, as that's the point of the conversion traits to cut down on them!

**Pull request closed without merging**
