### PR TITLE
Remove empty test files

### PR DESCRIPTION
**Pull request by apasel422**
It is likely that these were committed by mistake.

### CODE REVIEW

**Comment by apasel422** [comment]
The test failure doesn't appear to be related to this PR.

**Comment by apasel422** [comment]
@alexcrichton Can you have @bors retry this?

**Comment by alexcrichton** [comment]
@bors: retry

Certainly!

On Fri, Sep 18, 2015 at 7:13 AM, Andrew Paseltiner <notifications@github.com

**Pull request merged**
