### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #73210 ([mir-opt] Allow debuginfo to be generated for a constant or a Place)
 - #77901 (Unignore test for #36710 on MUSL)
 - #78072 (Cleanup constant matching in exhaustiveness checking)
 - #78119 (Throw core::panic!("message") as &str instead of String.)
 - #78122 (Avoid panic_bounds_check in fmt::write.)
 - #78153 (Sync LLVM submodule if it has been initialized)
 - #78169 (Update cargo)
 - #78179 (Miri engine: entirely skip interning of ZST, and improve some comments)
 - #78207 (Add regression test for #73298)
 - #78209 (Update `compiler_builtins` to 0.1.36)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by JohnTitor** [comment]
```
 stderr:
------------------------------------------
thread 'rustc' panicked at 'assertion failed: `(left == right)`
thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:354:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  left: `Binder(<[u8; _] as std::default::Default>)`,
 right: `Binder(<[u8; 1] as std::default::Default>)`', compiler/rustc_trait_selection/src/traits/codegen.rs:30:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (726888479 2020-10-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z unstable-options -C prefer-dynamic -C rpath -C debuginfo=0

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::default::Default` fulfills its obligations
#1 [resolve_instance] resolving instance `<[u8; _] as std::default::Default>::default`
end of query stack

------------------------------------------



failures:
    [ui] ui/const-generics/issue-73298.rs#full
```

Hm, I don't think it's spurious?

**Comment by Dylan-DPC** [comment]
yeah i guess I checked the wrong file :P handling it now

**Pull request closed without merging**
