### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by m-ou-se**
Successful merges:

 - #78361 (Updated the list of white-listed target features for x86)
 - #78785 (linux: try to use libc getrandom to allow interposition)
 - #78999 (stability: More precise location for deprecation lint on macros)
 - #79039 (Tighten the bounds on atomic Ordering in std::sys::unix::weak::Weak)
 - #79079 (Turn top-level comments into module docs in MIR visitor)
 - #79114 (add trailing_zeros and leading_zeros to non zero types)
 - #79131 (Enable AVX512 *epi64 variants by updating stdarch)
 - #79133 (bootstrap: use the same version number for rustc and cargo)
 - #79145 (Fix handling of panic calls)
 - #79151 (Fix typo in `std::io::Write` docs)
 - #79158 (type is too big -> values of the type are too big)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=78361,78785,78999,79039,79079,79114,79131,79133,79145,79151,79158)

### CODE REVIEW

**Comment by m-ou-se** [comment]
> `   = note: LINK : fatal error LNK1201: error writing to program database 'D:\a\rust\rust\build\i686-pc-windows-msvc\test\incremental\spans_in_type_debuginfo\a.pdb'; check for insufficient disk space, invalid path, or insufficient privilege`

That looks unrelated to the changes in this rollup. Spurious?

@bors retry

**Comment by jyn514** [comment]
This had [up to 4.5% regressions on instruction counts and a 40% increase in the time to bootstrap libcore](https://perf.rust-lang.org/compare.html?start=7d747db0d5dd8f08f2efb073e2e77a34553465a7&end=8d2d0014922e9f541694bfe87642749239990e0e&stat=instructions:u). I suspect https://github.com/rust-lang/rust/pull/78785 might be to blame. @cuviper did you expect a performance regression for that PR? If not, does it make sense to back it out and try to land a modified version that doesn't affect perf as badly?

**Comment by cuviper** [comment]
I didn't expect a measurable impact, but it's possible the weak symbols have more effect than I realized. #79039 also modified the atomic ordering in that area. Maybe someone can `git bisect` local builds to drill into this roll-up?

**Comment by m-ou-se** [comment]
Interesting, those are huge differences. None of these PRs seem suspicious though, at first glance.

The weak syscall lookup should only happen once. Any later calls just end up doing a single atomic operation, which is completely insignificant compared to the syscall they execute right after. It'd be quite surprising if the first lookup has such a big effect.

**Comment by jyn514** [comment]
Hmm, [most of the change is in `metadata_decode_entry_item_children`](https://perf.rust-lang.org/detailed-query.html?commit=8d2d0014922e9f541694bfe87642749239990e0e&base_commit=7d747db0d5dd8f08f2efb073e2e77a34553465a7&benchmark=deeply-nested-async-opt&run_name=full). Maybe the increase in doc-comments or new stdarch module affected it somehow?

**Comment by m-ou-se** [comment]
The stdarch change seems to add quite a lot of things:

image

**Comment by jyn514** [comment]
@m-ou-se @cuviper you were right, [#78785 had almost no impact](https://perf.rust-lang.org/compare.html?start=74459930a951db7a68b3ecd86f3b796339e59fe5&end=ad6794aa17ebda099a8407e9bd2089ee362fe7fb). #79131 [definitely caused the bootstrap increase(https://perf.rust-lang.org/compare.html?start=74459930a951db7a68b3ecd86f3b796339e59fe5&end=490cd5934a606d79cc82c5d16e4d71e0d9aa6dd5) but strangely instruction counts went *down* with that PR reverted. So I'm still stumped what caused the 7% regression on `deeply-nested-async-opt`.

**Comment by Mark-Simulacrum** [comment]
Yeah both reverts didn't obviously affect it at all (not even the 2-3% regressions on non-incr bits), but that benchmark is also a bit noisy historically so I wouldn't worry too much about it.

**Comment by RalfJung** [comment]
> but strangely instruction counts went down with that PR reverted

Isn't that what you'd expect from reverting a slowdown PR?

**Comment by tgnottingham** [comment]
This rollup also introduced an [increase in max-rss across the board](https://perf.rust-lang.org/compare.html?start=7d747db0d5dd8f08f2efb073e2e77a34553465a7&end=8d2d0014922e9f541694bfe87642749239990e0e&stat=max-rss). And it looks like #79131 was responsible, based on the [corresponding max-rss decrease](https://perf.rust-lang.org/compare.html?start=74459930a951db7a68b3ecd86f3b796339e59fe5&end=490cd5934a606d79cc82c5d16e4d71e0d9aa6dd5&stat=max-rss) in the revert PR #79391.

By the way, the 7% instruction count regression on `deeply-nested-async` is likely a red herring. It sometimes varies on its own, seemingly without reason (see [here](https://perf.rust-lang.org/compare.html?start=9919ad6e9ed113557c68c430de2e0f434e4f5b6e&end=f412fb56b8d11c168e7ee49ee74e79c4ab2e5637&stat=instructions:u) and [here](https://perf.rust-lang.org/compare.html?start=09c9c9f7da72b774cc445c0f56fc0b9792a49647&end=4ec27e4b79891b0ebc2ad71a3c4ac94f67d93f93&stat=instructions:u)). It's probably prone to variance depending on CGU partitioning. And part of the difference was due to #79131.

It looks to me like #79131 was responsible for all or nearly all of the `full` build instruction count regressions, and part of the incremental build instruction count regressions. The rest of the incremental regressions are unaccounted for, but they're fairly small, once you account for the effect of #79131.

**Pull request merged**
