### PR TITLE
Add tests for ICEs which no longer repro

### PR DESCRIPTION
**Pull request by wesleywiser**
Adds tests for some ICEs which no longer repro and closes the associated issues.

### CODE REVIEW

**Comment by estebank** [comment]
r? @estebank

Could you move the `compile-fail` tests to `ui`? You will have to do one more run with `./x.py test src/test/ui --stage 1 --bless` so that the `stderr` files are created. r=me after that.

**Comment by wesleywiser** [comment]
@estebank Sure! How's that look?

**Comment by estebank** [comment]
@wesleywiser it looks great! Thank you for taking the time!

I'll check back in an hour when travis is done and approve if it's ok (which I'm sure it is).

**Comment by wesleywiser** [comment]
Rebased

**Comment by kennytm** [comment]
@bors r- rollup-

The test case for 33264 is using inline assembly which is not supported by `asm.js` (in fact, the test is x86 specific).

Please add `// only-x86_64` to the test.

Test log: https://github.com/rust-lang/rust/pull/52616#issuecomment-406880760

**Comment by wesleywiser** [comment]
Fixed. Thanks @kennytm!

**Comment by estebank** [comment]
@wesleywiser did you mean to update `clippy` and `stdsimd` submodules?

**Comment by estebank** [comment]
@wesleywiser it happens :)

**Comment by wesleywiser** [comment]
I think this is good to go.

**Comment by wesleywiser** [comment]
@Mark-Simulacrum What does "treeclosed" mean? I've never seen that bors status before.

**Comment by kennytm** [comment]
@wesleywiser "treeclosed" prevents PRs lower than the specified priority from being tested. Currently Travis has broken our macOS builders, so we cannot run any tests until this is fixed.

**Comment by kennytm** [comment]
@wesleywiser "treeclosed" prevents PRs lower than the specified priority from being tested. Currently Travis has broken our macOS builders, so we cannot run any tests until this is fixed.

**Comment by wesleywiser** [comment]
@kennytm Gotcha

**Pull request merged**
