### PR TITLE
Parallelize tidy

### PR DESCRIPTION
**Pull request by the8472**
Split off from #81833

While that PR brings wall time of `x.py test tidy` down to 0m2.847s adding this one on top should bring it down to 0m1.673s.

r? @Mark-Simulacrum 

Previous concerns can be found at https://github.com/rust-lang/rust/pull/81833#issuecomment-782754685 and https://github.com/rust-lang/rust/pull/81833#discussion_r575194633

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I think I'd be happy to merge with https://github.com/rust-lang/rust/pull/81833#discussion_r579716349, presuming that seems reasonable to you. I think for the parallelism in main I'm not too worried, it should continue to be relatively straightforward to add more passes.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=iffy 

Thanks. I think this looks good to me, and we can always back it out if it causes trouble.

**Comment by the8472** [comment]
@Mark-Simulacrum looks like the approval got lost

**Comment by the8472** [comment]
I did forget to update one of the stub functions for windows, that should be fixed now. x.py doesn't have any magic to at least run `check` for all platforms, does it?

**Comment by Mark-Simulacrum** [comment]
x.py check --target foo may work without too much effort to cross-compile, but "all platforms" isn't really a well defined set (and I'm not sure if we've pulled away from C / native dependencies enough to not need a linker even for check).

@bors r+

**Comment by the8472** [comment]
Nope, fails immediately

```
$ ./x.py check --target x86_64-pc-windows-msvc
Updating only changed submodules
Submodules updated in 0.02 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
thread 'main' panicked at '
cmake does not support Visual Studio generators.

This is likely due to it being an msys/cygwin build of cmake,
rather than the required windows version, built using MinGW
or Visual Studio.
```

Maybe some wine-based docker build could work.

**Comment by Mark-Simulacrum** [comment]
I know we run the mingw one on the mingw-check builder (which is linux host), to try to get some coverage.

**Pull request merged**
