### PR TITLE
Add more array references to raw pointer casts 2.

### LINKED ISSUE #24151: `&mut [T;N] as *mut T` does not compile, but `&[T;N] as *const T` does
``` rust
unsafe {
    let my_num: &[i32; 2] = &[10, 20];
    let my_num: *const i32 = my_num as *const i32; // This works.
    println!("{}", *my_num.offset(1));
}
```

``` rust
unsafe {
    let my_num: &mut [i32; 2] = &mut [10, 20];
    // error: mismatched types:
    //  expected `*mut i32`,
    //         found `&mut [i32; 2]`
    let my_num: *mut i32 = my_num as *mut i32;
    println!("{}", *my_num.offset(1));
}
```

### PR DESCRIPTION
**Pull request by jagourq**
Adds &mut [T; n] to *mut T and &mut [T; n] to *const T casts. Closes #24151 and resubmits the changes made in #31418.

### CODE REVIEW

**Comment by Aatch** [comment]
The original issue doesn't mention `&mut [T; n] -> *const T` casts.

@nrc, @alexcrichton is that ok? Note that `&mut T -> *const T` works as a cast (the `&mut T` is coearced to a `&T` first).

**Comment by nrc** [comment]
In general, casting is not transitive - A -> B -> C does not imply A -> C. In this case, I think the `&mut [T; n] -> *const T` is OK. I see no reason to disallow it, at leasy.

**Comment by alexcrichton** [comment]
I'm not sure whether this was intended to be allowed, but I think there was an RFC on it?

**Comment by Jexell** [comment]
One thing I did notice when writing tests for the change was the file `vector-cast-weirdness.rs` checked to see that casts from `&mut [T; n]` to `*mut T` failed. It also checked for something that is now allowed which seemed strange.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit!

**Comment by Jexell** [comment]
@alexcrichton are there any changes I should make before resubmitting?

**Pull request closed without merging**
