### PR TITLE
[beta] Beta next

### PR DESCRIPTION
**Pull request by arielb1**
- #40764 
 - #40809
 - #41015 

r? @brson

### CODE REVIEW

**Comment by arielb1** [comment]
```
make[2]: *** [lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/build.make:339: lib/DebugInfo/DWARF/CMakeFiles/LLVMDebugInfoDWARF.dir/DWARFDebugMacro.cpp.obj] Segmentation fault
```

@bors retry

**Comment by arielb1** [comment]
Updated sccache to newest (#40809) so we can have more than 10% build success probability.

**Comment by arielb1** [comment]
```
http://centos.blazar.mx/5.11/updates/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found

Trying other mirror.

Error: Cannot retrieve repository metadata (repomd.xml) for repository: updates. Please verify its path and try again
```

Network failure

@bors retry

**Comment by frewsxcv** [comment]
@bors retry 

https://github.com/rust-lang/rust/issues/40474

**Pull request merged**
