### PR TITLE
[beta] Rollup of 2 pull requests

### PR DESCRIPTION
**Pull request by frewsxcv**
- Successful merges: #41016, #41048
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* ar.exe error https://github.com/rust-lang/rust/issues/40546

**Comment by frewsxcv** [comment]
```
[  9%] Linking CXX static library ../libLLVMSupport.a

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: CMakeFiles/LLVMSupport.dir/ThreadPool.cpp.o has no symbols

[  9%] Built target LLVMSupport

make[1]: *** [all] Error 2

thread 'main' panicked at '

command did not execute successfully, got: exit code: 2

build script failed, must exit now', /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.21/src/lib.rs:605

note: Run with `RUST_BACKTRACE=1` for a backtrace.

	finished in 72.799

Build completed unsuccessfully in 0:01:32

make: *** [all] Error 101
```

@bors retry

**Pull request merged**
