### PR TITLE
Make methods in CompileState public

### PR DESCRIPTION
**Pull request by aochagavia**

### CODE REVIEW

**Comment by aochagavia** [comment]
cc @nrc

**Comment by nrc** [comment]
What's the motivation for this? These methods are meant to be called by the compiler, do you have a use case where something external to the compiler driver call them?

**Comment by aochagavia** [comment]
@nrc I was planning to write my own version of `driver::compile_input` and was annoyed that this methods weren't public. However, now I realize that I don't need a modified version of `compile_input`, as long as I provide a `CompileController`.

I leave the PR open just in case you think it can be useful later on.

**Comment by nrc** [comment]
I don't think it will be useful (but of course I could be wrong). I'll close for now, happy to take this if there is a strong use case, but not on spec.

**Pull request closed without merging**
