### PR TITLE
Move os_str docs to OsString in order to be visible in HTML

### LINKED ISSUE #30743: Explain what an "OS string" is in OsStr/OsString docs
Currently, this is pretty bare: http://doc.rust-lang.org/nightly/std/ffi/struct.OsString.html

> Owned, mutable OS strings.

Needs some explanation what an OS string is, and why it is different from C and Rust strings.

### PR DESCRIPTION
**Pull request by birkenfeld**
(fixes #30743)

Not sure if the "Note" should be kept.

### CODE REVIEW

**Comment by steveklabnik** [comment]
> Not sure if the "Note" should be kept.

Yeah, we should take it out. Mind doing that? r=me after, thank you!

**Comment by birkenfeld** [comment]
Nice :)

**Pull request merged**
