### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #88642 (Formally implement let chains)
 - #89621 (doc: guarantee call order for sort_by_cached_key)
 - #91278 (Use iterator instead of recursion in `codegen_place`)
 - #92124 (Little improves in CString `new` when creating from slice)
 - #92783 (Annotate dead code lint with notes about ignored derived impls)
 - #92797 (Remove horizontal lines at top of page)
 - #92920 (Move expr- and item-related pretty printing functions to modules)
 - #93041 (Remove some unused ordering derivations based on `DefId`)
 - #93051 (Add Option::is_some_with and Result::is_{ok,err}_with)
 - #93062 (Update books)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=88642,89621,91278,92124,92783,92797,92920,93041,93051,93062)

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors retry

Yield to 1.58.1.

**Comment by pietroalbini** [comment]
@bors retry

Yield to 1.58.1.

**Comment by pietroalbini** [comment]
@bors retry

Yield to 1.58.1.

**Comment by pnkfelix** [comment]
Hmm, the compare page looks to me like this should be flagged as a performance improvement:

image

**Pull request merged**
