### PR TITLE
Fix false "never constructed" warnings for `Self::` variant paths

### LINKED ISSUE #64362: "variant is never constructed" lint appears to be incorrect?
This code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c03d4fa0a396d0476637d39c43bda0c2)) causes a "variant is never constructed" lint, even though the variant is constructed in the `FromStr` implementation:

```rust
use std::str::FromStr;

enum Foo {
    A { inner: () },
    B,
}

impl FromStr for Foo {
    type Err = ();
    
    fn from_str(s: &str) -> Result<Self, ()> {
        match s {
            "a" => Ok(Self::A { inner: () }),
            "b" => Ok(Self::B),
            _ => Err(()),
        }
    }
}
```

```
warning: variant is never constructed: `A`
 --> src/lib.rs:4:5
  |
4 |     A { inner: () },
  |     ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

Changing `Self` for the type name in `from_str` for `Foo` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=83856b4a0fbfa3510c8fe9eb3873ac8e)) compiles with the "field is never used" lint I would expect from this code.

Tested on `rustc 1.39.0-nightly (0b36e9dea 2019-09-09)`

This issue has been assigned to @jakubadamw via [this comment](https://github.com/rust-lang/rust/issues/64362#issuecomment-530559466).

### PR DESCRIPTION
**Pull request by jakubadamw**
Closes #64362.

### CODE REVIEW

**Comment by Centril** [comment]
Assigning blame of failure in https://github.com/rust-lang/rust/pull/64449#issuecomment-531475019 to this PR, @bors r-

(This is a guestimate)

**Comment by jakubadamw** [comment]
@Centril, no, the failure is unrelated.

**Comment by Centril** [comment]
@jakubadamw Any alternate theory? This PR seemed to be the only one related to TypeckTables somehow...

**Comment by jakubadamw** [comment]
@Centril, sorry, you're absolutely right. Looking into this.

**Comment by JohnCSimon** [comment]
Ping from triage.
@jakubadamw Hello! Can you please post your status regarding this PR? 
Thank you.

**Comment by JohnCSimon** [comment]
Ping from triage.
@jakubadamw This PR has sat idle for the last few weeks, I'm going to close this due to inactivity.
If you have time to move this forward please re-open this PR.
CC @estebank 

Thank you!

**Pull request closed without merging**
