### PR TITLE
doc: bindings not needed for this example

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is currently the style of the _entire_ module. It would need to be consistently updated everywhere. I believe I chose this style because there are some examples which don't work with all of them, though I don't _exactly_ remember.

**Comment by tshepang** [comment]
I see my style used in the module looking after a quick check. What are you looking at?

**Comment by steveklabnik** [comment]
The example directly below was what I double checked.

When I did these docs, I took a lot of pains to make them all consistent with each other generally. I'm not perfect though :)

**Comment by tshepang** [comment]
The example below is just a copy. Nowhere else in the module did I see the style.

**Comment by steveklabnik** [comment]
Okay, I double checked myself, because I swore I did it this way for all of them. It turns out that this set and `IntoIterator` do it this way, but all the others do it the way you've sent.

Would you mind updating the second block here to use this style, and `IntoIterator`? Then I'd be happy to merge.

Sorry about mis-remembering :(

**Comment by tshepang** [comment]
Thanks for coming back to this issue

**Pull request merged**
