### PR TITLE
diagnostics: Describe crate root modules in `DefKind::Mod` as "crate"

### PR DESCRIPTION
**Pull request by petrochenkov**
Or we can use "extern crate" like resolve previously did sometimes, not sure.

r? @davidtwco

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
Looks good to me! One or two of the changes are minor regressions (IMO - some of the changes from `extern crate` to `crate`) but overall I think this is an improvement.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/63318#issuecomment-518496232 (due to cargo making assumption about error message; see https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/5242/logs/1000).

@bors r-

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/cargo/pull/7231.

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/63400.

**Pull request merged**
