### PR TITLE
Backport fix for rustdoc overflows

### LINKED ISSUE #52873: ICE when running `cargo doc` on `typenum` at `librustc/traits/structural_impls.rs:178`
```
 Documenting typenum v1.10.0 (file:///home/hdevalence/code/typenum)
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached

thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:578:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (866a71325 2018-07-29) running on x86_64-unknown-linux-gnu

error: Could not document `typenum`.
```

Steps to reproduce:
```
git clone https://github.com/paholg/typenum.git
cd typenum
echo 'nightly-2018-07-24' > rust-toolchain
cargo doc # works
echo 'nightly-2018-07-30' > rust-toolchain
cargo doc # ICE
```

### PR DESCRIPTION
**Pull request by nikomatsakis**
Backport of https://github.com/rust-lang/rust/pull/54199 to stable

Fixes #52873

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@bors r=eddyb

This was a clean backport, so I will just carry over the r+ that @eddyb  left on #54199

**Comment by pietroalbini** [comment]
cc @Mark-Simulacrum, should we rollup this in the point release PR instead of landing it on its own?

**Comment by weiznich** [comment]
Does this also fix #54524?

**Comment by weiznich** [comment]
@nikomatsakis After looking at the patch I do not think that this will fix building diesels documentation, because it is the same patch that was applied to nightly some time back. The overflow continues to happen with the latest (rustdoc +nightly --version  rustdoc 1.32.0-nightly (451987d86 2018-11-01)) nightly.

**Comment by nikomatsakis** [comment]
@weiznich ah, ok.

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum ok sorry just let me know how you want to proceed :)

**Comment by Mark-Simulacrum** [comment]
Essentially we should make this PR have the necessary commits to land on stable and 2-3 days out we'd roll-up all the stable targeting PRs into one and land that. So I think this PR might need some changes perhaps?

**Comment by pietroalbini** [comment]
@Mark-Simulacrum I don't think there is any fix for the diesel docs regression yet.

**Comment by Mark-Simulacrum** [comment]
Right, but when/if that happens we'll want to also backport that (perhaps in this PR).

**Pull request closed without merging**
