### PR TITLE
Replace alpha state by beta state

### LINKED ISSUE #24060: "Hello, Cargo!" chapter in "the rust programming language". Rust is no longer alpha.
From the book:
https://github.com/rust-lang/rust/blob/master/src/doc/trpl/hello-cargo.md

"Cargo is currently in an alpha state, just like Rust, and so it is still a work in progress."

Rust is no longer in alpha state.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #24060.

### CODE REVIEW

**Comment by MatejLach** [comment]
Is Cargo following Rust in lockstep? 
Last time I checked it was still considered alpha.
@GuillaumeGomez Also I suspect that it is "a beta", rather than "an beta", but I am not a native English speaker myself, so I could be wrong.

**Comment by GuillaumeGomez** [comment]
No, you're totally right, it's "a" and not "an".

For Cargo state, I thought it was following the rust state. We'll see what they'll say about that.

**Comment by steveklabnik** [comment]
How about, "pre-1.0" for now?

**Comment by GuillaumeGomez** [comment]
@steveklabnik: I change that !

**Comment by GuillaumeGomez** [comment]
@steveklabnik: Done.

**Comment by steveklabnik** [comment]
You picked up a sub module there

**Comment by GuillaumeGomez** [comment]
@steveklabnik: fixed !

**Pull request merged**
