### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by jseyfried**
- Successful merges: #34105, #34305, #34512, ~~#34531,~~ #34547

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @alexcrichton -- android timed out

**Comment by alexcrichton** [comment]
Yeah looks like the android builder is having a lot of trouble right now, I'm gonna try to watch it closely to see if I can diagnose what's going on. I don't think it's related to changes in this PR, though.

@bors: retry

**Comment by jseyfried** [comment]
@alexcrichton thanks, yeah android was failing the same way on several unrelated PRs.

**Comment by jseyfried** [comment]
@alexcrichton android timed out at exactly the same point it's been timing out on this and other PRs

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/34559

On Wed, Jun 29, 2016 at 12:42 PM, Jeffrey Seyfried <notifications@github.com

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/34559

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/pull/34577

**Comment by arielb1** [comment]
```
---- Rust_Compiler_Error_Index_537 stdout ----
	<anon>:1:1: 1:15 error: export_name attribute has invalid format
<anon>:1 #[export_name]
         ^~~~~~~~~~~~~~
<anon>:1:1: 1:15 help: use #[export_name="*"]
thread 'Rust_Compiler_Error_Index_537' panicked at 'Some expected error codes were not found: ["E0533"]', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/librustdoc/test.rs:298

```

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/pull/34577#issuecomment-229760928

**Pull request merged**
