### PR TITLE
rustc_mir: hardcode pass list internally and remove premature pluggability.

### LINKED ISSUE #41712: [FIXME] settle future of MIR pass manager
In https://github.com/rust-lang/rust/pull/41625, the role of the MIR pass manager has been significantly scaled back. Once can still register passes, but they always take an `&mut Mir`, and the set of passes is defined in `driver` and cannot be readily changed (in particular, the session no longer has a `Passes` struct). @eddyb would like to go further, I think, and remove the `Passes` strruct from the `tcx` altogether -- the main reason it is still there is that it allows the MIR code to (indirectly) invoke passes defined in other crates, e.g. `elaborate_drops`. I tend to also think it's nice to "collect" the MIR passes into one single data-structure to ensure that (e.g.) we have the option to dump the MIR in between each pass and apply other debugging conventions (as well as to easily reorder passes or introduce new ones).

Longer term, what do we think this should look like? One extreme future might remove the `Passes` struct altogether and have the invocations of each pass kind of hard-coded -- we could build up the set of `Pass` objects in the various "mir queries", for example. Another extreme would be to make the `Passes` struct more complex to support plugins adding custom optimizations -- it seems like we're a long way from there, and that may never make sense.

To do the "radically scaled back" version of futures, we'd have to at least consolidate the borrowck and mir crates, or make one a dependency of the other, or something like that. 

cc @rust-lang/compiler -- thoughts?

### PR DESCRIPTION
**Pull request by eddyb**
Fixes #41712 by moving the MIR pass lists from `rustc_driver` to `rustc_mir`.
The application of the passes is done with the `rustc_mir::transform::run_passes` macro, which is public, as are all the passes AFAIK, and can be used to apply MIR passes outside of `rustc_mir`.

With the ability to override query providers through the `rustc_driver` (orthogonal to, and not included in this PR), custom drivers will be able to substitute the entire pass list if they want to.
**EDIT**: the aforementioned ability is added by #45944.

r? @nikomatsakis

### CODE REVIEW

**Comment by bjorn3** [comment]
Please dont do this as this would make it very hard to update [holyjit](https://github.com/nbp/holyjit) for the latest nightly. Currently it just requires a rustc patch of a few lines.

**Comment by eddyb** [comment]
@bjorn3 See this PR's description for the appropriate course of action. Being able to replace the provider for, e.g., the `optimized_mir` query, and then reusing the macro from `rustc_mir`, with a slightly modified set of passes, should allow pretty much everything.
There are no composition rules for MIR passes, nor is the idea of a MIR pass permanent, so it's not really meaningful to "just add another pass".

**Comment by bjorn3** [comment]
I see. Should have read the description completely.

**Comment by nbp** [comment]
@bjorn3 Thanks for your concern for HolyJit.  Yes this patch is going to break the ability to simply rebase a patch on top of rustc, but HolyJit is a prototype, and I have been warned and explicitly been suggested against using a plugin approach from the beginning.

I still went with the plugin approach because this is something I understand and which was close enough to what is currently documented for making syntax plugins.

**Pull request merged**
