### PR TITLE
rustbuild: Pass a `threads` flag that works to windows-gnu lld

### PR DESCRIPTION
**Pull request by petrochenkov**
MinGW driver for COFF LLD doesn't currently translate GNU-style `--threads=N` to native `/threads:N`, so we have to pass the option in its native form to avoid an error.

Also pass the `threads` flag to lld-link (windows-msvc lld) as well.

### CODE REVIEW

**Comment by RalfJung** [comment]
Could this have caused https://github.com/rust-lang/rust/pull/84932#issuecomment-832388973 ?
@bors rollup=iffy

**Comment by petrochenkov** [comment]
Very unlikely, `lld` is not used on CI at all, AFAIK.

**Comment by RalfJung** [comment]
Yeah, the error happened again without this PR in https://github.com/rust-lang/rust/pull/84951.
@bors rollup=always

**Pull request merged**
