### PR TITLE
Add missing documentation for FileNameDisplayPreference variants

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Took me a while to find the information when I needed it so hopefully it should save some time for the next ones.

r? @thomcc

### CODE REVIEW

**Comment by thomcc** [comment]
Hm, sorry, it looks fine, but I don't know about anything in `compiler/` really so that's just a guess.

r? compiler

**Comment by GuillaumeGomez** [comment]
Oh sorry, I assumed you were when you reviewed my previous PRs.

**Comment by nagisa** [comment]
I don’t believe these are accurate descriptions of these variants. The purpose of this enum is to specify whether the path should be displayed taking into account [`--remap-path-prefix`](https://doc.rust-lang.org/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output) or the original pre-remapping input.

The resulting path can be absolute, or relative in either case (for `Local` IIRC it depends on how the path is passed to the compiler), and neither is guaranteed to be more preferable than the other.

How about this:

* `Remapped` – Display the path after the application of rewrite rules provided via `--remap-path-prefix`. This is appropriate for paths that get embedded into files produced by the compiler.
* `Local` – Display the path before the application of rewrite rules provided via `--remap-path-prefix`. This is appropriate for use in user-facing output (such as diagnostics.)

**Comment by GuillaumeGomez** [comment]
Thanks for the clarification, it was very much needed! :) TIL

I updated the doc comments as you suggested.

**Comment by thomcc** [comment]
> Oh sorry, I assumed you were when you reviewed my previous PRs.

Those were all in `library/*` -- Totally happy to review that stuff :)

**Pull request merged**
