### PR TITLE
Add riscv64{imac,gc}-unknown-none-elf targets

### PR DESCRIPTION
**Pull request by Disasm**
Previous attempt by @fintelia: https://github.com/rust-lang/rust/pull/58012

Related: https://github.com/rust-embedded/wg/issues/218

### CODE REVIEW

**Comment by davidlt** [comment]
Silly question, would this allow me building Rust on riscv64 host, or does it only enable riscv64 (rv64gc) as a target where host is, e.g., x86_64?

**Comment by jethrogb** [comment]
@davidlt No, for that you'd need to add a `riscv64gc-unknown-linux-gnu` target.

**Comment by jethrogb** [comment]
Please also file a PR against https://github.com/rust-lang/rust-forge/ for https://forge.rust-lang.org/platform-support.html

**Comment by Disasm** [comment]
@jethrogb Thanks for pointing out!

**Comment by nagisa** [comment]
@bors r+

LGTM

**Comment by Centril** [comment]
In-between-rollups-filler, @bors p=1

**Comment by Disasm** [comment]
Almost done...

**Comment by fintelia** [comment]
Are all of these timeouts really spurious? And if so, is there any way to raise the time limit slightly? This will be the fourth time testing the same changes...

**Pull request merged**
