### PR TITLE
statics in match arm: compile with -g

### PR DESCRIPTION
**Pull request by tamird**
Currently, this ICEs. See #29696. Also removes duplicate test case.

### CODE REVIEW

**Comment by nagisa** [comment]
Do not remove the whole test, ignore it instead.

**Comment by tamird** [comment]
Why? It's duplicating things that are already tested in match-arm-statics.

**Comment by tamird** [comment]
This failure is expected since this is still a bug.

**Comment by alexcrichton** [comment]
Oh, in that case I'm gonna close this for now and we can perhaps add this once the bug is fixed!

**Comment by tamird** [comment]
@alexcrichton this passes now; can you reopen?

**Pull request closed without merging**
