### PR TITLE
add openbsd snapshot

### PR DESCRIPTION
**Pull request by semarie**
as the buildbot has timeouted when building snap3 branch, I regenerate one locally.

here the diff that registers the OpenBSD snapshot.

the archive is available at http://semarie.online.fr/rust/rust-stage0-2015-12-18-3391630-openbsd-x86_64-6c8aab2c8a169274942f9a15e460069a3ff64be9.tar.bz2

sha256 : de3c26a93cf9512922cc012f9b57bd08d7b64f7e0469a9bb032fa9c07260cf0c

@alexcrichton does it is the good method for providing a snapshot ?

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 89dc44056bf80662fa7cbf2fba1bd18a2e7e836f

Yep, works for me!

**Comment by semarie** [comment]
the failure seems unrelated

**Pull request merged**
