### PR TITLE
Use a more efficient iteration order for forward dataflow

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Currently, dataflow begins by visiting each block in order of ID (`BasicBlock(0)`, `BasicBlock(1)`, etc.). This PR changes that initial iteration to reverse post-order (see [this blog post](https://eli.thegreenplace.net/2015/directed-graph-traversal-orderings-and-applications-to-data-flow-analysis/#data-flow-analysis) for more info). This ensures that the effects of all predecessors will be applied before a basic block is visited if the CFG has no back-edges, and should result in less total iterations even when back-edges exist. This should not change the results of dataflow analysis.

The current ordering for basic blocks may be pretty close to RPO already--`BasicBlock(0)` is already the start block--in which case the cost of doing the traversal up front will outweigh the efficiency gains.
A perf run is needed to check this.

r? @pnkfelix (I think).

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
@nagisa. Do you think the assertion about unreachable basic blocks is correct? I added it because there could be two successive basic blocks which are unreachable from the start block, in which case the entry set for the second one would be wrong.

**Comment by Centril** [comment]
@rust-timer build 0905d6a630cb4afc3f894f9e91c1a7a20c32416b

**Comment by pnkfelix** [comment]
This seems ... fine? It doesn't seems to hurt anything; it also doesn't improve things terribly much, probably because the block numbering was close to RPO already, as hypothesized.

ts probably not a good idea to implicitly *rely* on the block numbering always remaining close to RPO, right? And therefore we should land this?

What do you think, @ecstatic-morse ? (@nagisa and @arielb1 may also have thoughts on this, since I know they've each also spent time thinking about or working on dataflow analyses.)

**Comment by ecstatic-morse** [comment]
I think this should probably land (totally not biased or anything :). It's a sensible default, the overhead of a single extra RPO per dataflow analysis is pretty small, and it removes the implicit dependency on a certain basic block ordering, which may change as more MIR transformations are added. In conjunction with the addition of more expensive dataflow passes (i.e. reaching definitions), the naive ordering could eventually have an observable performance impact.

The alternative is to wait until a MIR transformation is actually added which renumbers basic blocks, but this PR will probably be long forgotten by then :smile:.

**Comment by ecstatic-morse** [comment]
This also does reduce the number of dataflow iterations, just not enough to matter. I observed a reduction of 9% across all dataflow analyses which took more than 5 iterations when running the tests in `src/test/run-pass/array-slice-vec/`.

**Comment by arielb1** [comment]
@pnkfelix 

I think it's OK to land this to avoid the dependence on basic block ordering.

**Pull request merged**
