### PR TITLE
Remove unneeded handling for `ExternalLocation::Unknown` in rustdoc render context

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Should fix perf regression introduced in https://github.com/rust-lang/rust/pull/113623.

r? @lqd

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Just to be sure:

@bors try @rust-timer queue

**Comment by lqd** [comment]
(ctfe-stress-5 was being noisy at the time)

**Comment by pnkfelix** [comment]
I'm taking @lqd's note as a signal that the flagged regressions to ctfe-stress-5 should be treated as noise.

@rustbot label: +perf-regression-triaged

**Pull request merged**
