### PR TITLE
Fix f16 and f128 feature gating on different editions

### PR DESCRIPTION
**Pull request by tgross35**
Apply the fix from https://github.com/rust-lang/rust/issues/123282#issuecomment-2035063388 to correctly gates `f16` and `f128` in editions other than 2015

### CODE REVIEW

**Comment by tgross35** [comment]
Nothing to show yet but

r? @compiler-errors
@rustbot author

**Comment by tgross35** [comment]
It looks like the gate is getting hit here https://github.com/rust-lang/rust/blob/029cb1b13b6388b95e64e8996ec8b41a9f3cf16e/compiler/rustc_resolve/src/ident.rs#L604-L629

**Comment by tgross35** [comment]
It seems like in edition > 2015, paths like `f16::foo` hit the above code path twice - once with `finalize = Some(...)` (where this error is being thrown) and once with `finalize = None`. On other editions, this section of code isn't hit for type paths.

I am thinking that for e2018+, early resolution says that `some_shadowed_prim_name::foo` is associated with that code, then somewhere in later resolution it gets fixed up to point to the non-primitive type if it exists. Trying to chase down where exactly this would be.

@petrochenkov you mentioned in https://github.com/rust-lang/rust/pull/121926 that it would be better to gate this where `PrimTy` is constructed. I think that is actually the above code where we currently have the gate, because it checks `builtin_types_bindings` which is constructed from `PrimTy::ALL`.

**Comment by petrochenkov** [comment]
Fix - https://github.com/rust-lang/rust/issues/123282#issuecomment-2035063388.

2015 and 2018 editions should be enough, import resolution didn't change after 2018.

**Comment by tgross35** [comment]
> Fix - [#123282 (comment)](https://github.com/rust-lang/rust/issues/123282#issuecomment-2035063388).

Thanks, applied

> 2015 and 2018 editions should be enough, import resolution didn't change after 2018.

I removed the other editions for the feature gate test, but left them in the check-pass as a sanity check.

@rustbot ready

**Comment by tgross35** [comment]
Thanks, changed. I can't r=

**Pull request merged**
