### PR TITLE
add `Vec::set_len_zero` as a safe helper (internal)

### PR DESCRIPTION
**Pull request by Rudxain**
`set_len_zero` is just a utility/helper private method that can be used as an alternative to `set_len(0)`. I expect this to be convenient, because it's not `unsafe` and always sound.

Maybe, in the future, it could be stabilized as `pub`!

I want to clarify that this PR is just a refactor. It's not meant to change the lib API, unless someone opens an RFC for it

### CODE REVIEW

**Comment by workingjubilee** [comment]
the code in question could simply set the field to 0. it does not. it uses `set_len` and notes the operation is safe because normally operations on that field are unsafe. it is my opinion that it is usually harder to reason about an additional function to do the same thing, because it can actually do something different internally. I should not have to check the implementation of another function just to see it is indeed equal to `set_len(0)`.

**Comment by workingjubilee** [comment]
I also don't think we would ever want to expose this function publically because it would almost never be what you want. You would want `clear`.

**Comment by workingjubilee** [comment]
re: "this is just a refactor", [the lady doth protest too much, methinks](https://en.wikipedia.org/wiki/The_lady_doth_protest_too_much,_methinks). I do not really want to r+ a stalking horse or trial balloon.

**Comment by Rudxain** [comment]
> Given how fundamentally unsafe most of the code that could use this in vec already is, I'm not sure how much value it provides just as an internal helper.

Yeah, I didn't put much thought on this.

> I would suggest you propose it in an ACP

Thanks for the info!

> the code in question could simply set the field to 0. it does not.

Now that I think about it, it's kinda odd (I'm not familiarized with the codebase)

> it uses `set_len` and notes the operation is safe

So the only (internal) purpose of `set_len` is to be a reminder that field mutations are `unsafe`?

If that's the case, why not document it?
```
pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    buf: RawVec<T, A>,
    /// `unsafe` `mut`
    len: usize,
}
```

> it is my opinion that it is usually harder to reason about an additional function

I agree. Why not get rid of calls to `set_len`?

**Comment by workingjubilee** [comment]
> If that's the case, why not document it?

In a sense, `unsafe` is aggro documentation which crawls into your face and kills your build if you try to skip out on it. Rust code has to lex, parse, expand (into something that can parse again), unsafeck, typecheck, borrowcheck, but after that codegen can do kinda whatever and all our lints are mere warnings that can simply be `allow`ed.

Because of this, nothing actually forces people to write unsafe code *correctly*. You can write a safe `fn` that wraps an `unsafe` operation and then is just unsound when called. This doesn't occur to most people who learn Rust because they would like their code to be safe, but a certain kind of... more cavalier... programmer is happy to do so, even when it isn't at all necessary. The thing that can still close _that_ last mile and deter people from doing so is... peer pressure. Conformity.

And conformity is easier to enforce when there is less room for variance to begin with.

Conformity is also often on somewhat arbitrary decisions, as you have noticed! It will decide on something like "Sure, you can modify this field directly in this file, but we're not going to do that! We're going to have everything go through `set_len`!" Anything that differs seems out of place and thus inherently suspect.

Now, there _is_ a benefit to making safe operations not look unsafe, but because of the previous reasons, it is best to reserve adding variance for when the benefit is clear. Here, it does not feel so, because there are so few instances of this pattern. Perhaps if this was a function that made _almost all_ the cases of `set_len` in libstd safe, without compromising correctness (or performance?), I might feel differently!

**Comment by Rudxain** [comment]
@workingjubilee Thank you for explaining! I appreciate it a lot, as I've learned stuff. And I'm sorry if I wasted anyone's time

> performance?

I was considering something like:
https://github.com/rust-lang/rust/blob/d678b81485b05680801554d744ea2696949f0135/library/core/src/num/nonzero.rs#L367-L382

That is, telling `rustc` to assume `new_len <= capacity` and that all elements are initialized.

But that would probably increase the chances of UB by orders of magnitude, while providing marginal perf benefits. So I doubt it's worth it

**Pull request closed without merging**
