### PR TITLE
Don't use `Res::Err` without emitting an error 1/*

### PR DESCRIPTION
**Pull request by lcnr**
We currently use `Res::Err` both to express "there was an error" and "there is no relevant resolution".

https://github.com/rust-lang/rust/blob/3fe4dd2dda2826643c4ce4ee7307707a90e08d25/src/librustc_middle/ty/context.rs#L454-L461

Before I work on changing all occurrences of the second meaning to `Option<Res>` I want to get some
feedback whether this change is actually desired.

cc @nikomatsakis @matthewjasper

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @petrochenkov

**Comment by nikomatsakis** [comment]
I am reading up a bit here to get more context, however my general opinion that we have to be very careful about things that signal "there was an error reported to the user". It's very common to use variants like that to skip downstream errors or avoid bits of work, and it's easy to wind up with unsoundness as a result.

So 👍 to having a clear distinction between "error reported" and "no relevant resolution", presuming at least that 'no relevant resolution' doesn't always imply an error has been reported. 

Can you elaborate a bit more on what bits of downstream code want to distinguish between those two cases, though? I know it came up when we were discussing lazy normalization, but I think the context would be helpful.

**Comment by lcnr** [comment]
I first noticed this when refactoring `query type_of` for const generics.

https://github.com/rust-lang/rust/blob/3fe4dd2dda2826643c4ce4ee7307707a90e08d25/src/librustc_typeck/collect/type_of.rs#L273-L289

Some *correct* qpaths have segments where `res` is `None`, for others `res` is `Some(Err)` and for others it's `Some(actually_correct_res)`. I think that my current solution is not correct in all cases and something like [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c2b6681207addee3542da33c52467ea2) may break it. (We have an ICE here atm with seems unrelated though :shrug:)

Looking at some other locations where `Res::Err` is used. I am quite suspicious of the following,
which already depends on this distinction afaict.
https://github.com/rust-lang/rust/blob/3fe4dd2dda2826643c4ce4ee7307707a90e08d25/src/librustc_typeck/check/pat.rs#L824-L828

**Comment by petrochenkov** [comment]
>Before I work on changing all occurrences of the second meaning to `Option<Res>` I want to get some feedback whether this change is actually desired.

I think this is desirable at least after the main resolution pass, but I'd prefer to see this done in stages instead of changing all occurrences in one go. For example
- everything after AST -> HIR lowering
- AST -> HIR lowering
- everything after expansion / early resoluton
- expansion / early resolution (this may be harder because `Res::Err` is used in non-trivial ways for import stubs in namespaces where they don't import anything, and maybe other similar cases)

**Pull request closed without merging**
