### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by flaper87**
- Successful merges: #21108, #21498, #21504, #21529, #21532, #21535, #21539, #21540, #21541, #21550
- Failed merges:

### CODE REVIEW

**Comment by FlaPer87** [comment]
@alexcrichton retry ? :/

**Comment by barosl** [comment]
@FlaPer87 The test failure is real, so you should add a commit to this PR that addresses https://github.com/rust-lang/rust/pull/21529/files#r23487891

**Comment by barosl** [comment]
But I also think it would be better to open a new one anyways because we have three more PRs to roll up now...

**Comment by tshepang** [comment]
@barosl I have fixed the issue. Sorry for the pain :(

**Comment by FlaPer87** [comment]
@barosl oh mmh, it was late and I mistakenly assumed the issue was spurious because the job failing was the same. I'll re-open a new rollup.

**Pull request closed without merging**
