### PR TITLE
feat: omit suffixes in const generics (e.g. `1_i32`)

### LINKED ISSUE #99255: Omit suffixes (e. g. `1_i32`) in const generic compilation errors
I'm working on a library for compile time dimensional analysis. It uses const generics. On unit mismatch I get errors like this:
```
error[E0308]: mismatched types
   --> src/isq.rs:346:23
    |
346 |         let l3 = l1 + l2;
    |                       ^^ expected `1_i32`, found `2_i32`
    |
    = note: expected struct `Quantity<isq::Unit<(meter, Const<1_i32>)>, _>`
               found struct `Quantity<isq::Unit<(meter, Const<2_i32>)>, _>`
```
As you can see, `rustc` includes this `_i32` type suffix into each const generic parameter. I think it's redundant & only makes compilation errors longer (which is important especially if you have complex combinations of units), because if you really want to learn the type of const generic parameter, you can just look at `struct` definition in source code.

I'd like error message to look like this:
```
error[E0308]: mismatched types
   --> src/isq.rs:346:23
    |
346 |         let l3 = l1 + l2;
    |                       ^^ expected `1`, found `2`
    |
    = note: expected struct `Quantity<isq::Unit<(meter, Const<1>)>, _>`
               found struct `Quantity<isq::Unit<(meter, Const<2>)>, _>`
```

### PR DESCRIPTION
**Pull request by Logarithmus**
Closes #99255

### CODE REVIEW

**Comment by Logarithmus** [comment]
@petrochenkov CI finally passed
bors r+

**Comment by petrochenkov** [comment]
This PR removes types from const generic arguments not only in type mismatch errors (where types are the same), but in pretty much all pretty-printed types.

The result seems fine though (except for inferred constants maybe, like `_: usize` -> `_`).
We should be able to add an extra flag to `FmtPrinterData` if we need to restore the types in some locations in the future.

r=me after squashing commits into one.
@rustbot author

**Comment by Logarithmus** [comment]
@petrochenkov what should I do now? Add this extra flag to `struct FmtPrinterData`? Should I add it to `FmtPrinter::new(..)` as well? Should I revert the behavior for `Blah<{_: usize}>`?
> r=me after squashing commits into one
What does it mean? Why should I squash the commits manually?

**Comment by Logarithmus** [comment]
@petrochenkov but bors squashes automatically...

**Comment by petrochenkov** [comment]
>Why should I squash the commits manually?

Squashing can actually be made by the merge bot, but the commit messages are suboptimal.
@bors r+ squash

**Comment by Logarithmus** [comment]
@petrochenkov I've thought `bors` uses PR body as a commit message. In fact, that's the behavior observed here: https://github.com/rust-lang/rust-analyzer/pull/12778

**Comment by Logarithmus** [comment]
@petrochenkov after merging to `master`, will this feature make it into the next stable (1.63)? Who decides what goes to stable and what not?

**Comment by Logarithmus** [comment]
@compiler-errors I've squashed the commits

**Comment by oli-obk** [comment]
Thanks!

@bors r=petrochenkov

**Comment by Logarithmus** [comment]
@petrochenkov I see the rollup is merged. What should I do now?

**Comment by RalfJung** [comment]
You should never push to a branch that is in an open rollup. Now you'll have to make a new PR with the bits that you pished since the rollup was created.

**Comment by Logarithmus** [comment]
@RalfJung I chaged nothing, just squashed the commits as I've been told by @compiler-errors. Can I just close this PR now?

**Comment by RalfJung** [comment]
Yeah if everything landed you can close the PR. @compiler-errors didn't actually ask you to push squashed changes to this commit, so I guess there was some miscommunication here. Generally, don't touch the PR after ti has been `r+`ed. :)

Looks like squashing and rollups don't work together, I'll report that as a bug for bors.

**Comment by Logarithmus** [comment]
Merged in https://github.com/rust-lang-ci/rust/commit/e7a9c1141698bc4557b9da3d3fce2bf75339427f

**Pull request closed without merging**
