### PR TITLE
move personality to sys

### PR DESCRIPTION
**Pull request by devsnek**
this moves `personality` to sys, removing another PAL exception

### CODE REVIEW

**Review by workingjubilee — COMMENTED** [review]
So the only problem here is that this now results in a bunch of cfg being done separately in the "platform" file and also this personality file. I am half-inclined to say we should approve this anyway, since that was a preexisting condition and it really helps to have "move these files" as a separate commit in git.

However, I would still prefer a followup commit that restructures the personality code so that at least the cfg selection of which personality implementation is inside the "platform file". You don't have to do anything on top of that, just thinning out the cfgoo from personality/mod.rs

**Comment by Mark-Simulacrum** [comment]
r? workingjubilee

**Comment by ChrisDenton** [comment]
@devsnek You need to rebase on master rather than having a merge commit. Also would you want to add a commit that addresses @workingjubilee's concerns, specifically:

> I would still prefer a followup commit that restructures the personality code so that at least the cfg selection of which personality implementation is inside the "platform file". You don't have to do anything on top of that, just thinning out the cfgoo from personality/mod.rs

Feel free to ask for clarification if needed.

**Comment by devsnek** [comment]
@workingjubilee i'm not entirely sure what code you want moved where.

**Comment by workingjubilee** [comment]
Hm, I'm not entirely sure I can do a good job explaining it, but it's mostly about how ideally, the "top level" cfg for sys... the one in library/std/src/sys/mod.rs... is the thing that picks which implementation of things to use and for the rest it's hypothetically "small" differences (but we've both seen inside library/std/src/sys/unix/ so we both know **that's a damn lie**... but it's nice when it's truer).

If you still feel uncertain about what I mean then just rebase this and I'll approve it and figure out the followup on my own time, I have an idea for how things should be restructured in sys in general based on some recent forays.

**Comment by workingjubilee** [comment]
I took care of the rebase.
@bors r+ rollup

**Pull request merged**
