### PR TITLE
Don't emit an error about failing to produce a file with a specific name if user never gave an explicit name

### LINKED ISSUE #122509: Invalid "ignoring emit path because multiple .s files were produced" message
### Code

```Rust
#[inline(never)]
pub fn alpha() -> usize {
    println!("alpha");
    12
}

#[inline(never)]
pub fn beta() -> usize {
    println!("beta");
    12
}
```

### Current output

```Shell
$ rustc lib.rs --crate-type lib --emit asm -C codegen-units=2
warning: ignoring emit path because multiple .s files were produced

warning: 1 warning emitted
```

### Desired output

```Shell
blank
```

### Rationale and extra context

Error originates from somewhere around here and implies that I passed `--emit foo=some_name`, while in fact I only passed `--emit foo`

https://github.com/rust-lang/rust/blob/fe6157522848604562f83084154274c545fe3a27/compiler/rustc_codegen_ssa/src/back/write.rs#L595-L599

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.78.0-nightly (1a648b397 2024-02-11)
binary: rustc
commit-hash: 1a648b397dedc98ada3dd3360f6d661ec2436c56
commit-date: 2024-02-11
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 17.0.6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pacak**
Fixes #122509

You can ask `rustc` to produce some intermediate results with `--emit foo`, this operation comes in two flavors: `--emit asm` and `--emit asm=foo.s`. First one produces one or more `.s` files without any name guarantees, second one renames it into `foo.s`. Second version only works when compiler produces a single file - for asm files this means using a single compilation unit for example.

In case compilation produced more than a single file `rustc` runs following check to emit some warnings:

```rust
            if crate_output.outputs.contains_key(&output_type) {
                // 2) Multiple codegen units, with `--emit foo=some_name`. We have
                //    no good solution for this case, so warn the user.
                sess.dcx().emit_warn(errors::IgnoringEmitPath { extension });
            } else if crate_output.single_output_file.is_some() {
                // 3) Multiple codegen units, with `-o some_name`. We have
                //    no good solution for this case, so warn the user.
                sess.dcx().emit_warn(errors::IgnoringOutput { extension });
            } else {
                // 4) Multiple codegen units, but no explicit name. We
                //    just leave the `foo.0.x` files in place.
                // (We don't have to do any work in this case.)
            }
```

Comment in the final `else` branch implies that if user didn't ask for a specific name - there's no need to emit warnings. However because of the internal representation of `crate_output.outputs` - this doesn't work as expected: if user asked to produce an asm file without giving it an implicit name it will contain `Some(None)`.

To fix the problem new code actually checks if user gave an explicit name. I think this was an original intentional behavior, at least comments imply that.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks for the PR, @pacak!

Would you mind adding a regression test?
https://rustc-dev-guide.rust-lang.org/tests/adding.html

Let me know if you need any help with that.

**Comment by pacak** [comment]
Absolutely. What is the most reliable way to ensure that the code will be compiled with at least two codegen units?

**Comment by michaelwoerister** [comment]
Passing `-Ccodegen-units=2` and having at least two `mod`s should do the trick.

**Comment by michaelwoerister** [comment]
Compile flags like that can be set in the test file: https://rustc-dev-guide.rust-lang.org/tests/headers.html

**Comment by pacak** [comment]
I think that's it. It supposed to produce an error before (I didn't check though) and it is not producing an error now.

**Comment by pacak** [comment]
> tidy error: following path contains more than 859 entries, you should move the test to some relevant subdirectory (current: 860): /checkout/tests/ui

There's no relevant subdirectory for invalid warnings though as far as I can see. I tried moving it into issues - it also complains about having too many items...

**Comment by pacak** [comment]
> So, please avoid putting a new test there and try to find a more relevant place. 

Okay, now there's a sub directory for warnings.

**Comment by michaelwoerister** [comment]
I'm sorry those tidy errors seemed to have sent you on a wild goose chase. There indeed doesn't seem to be a relevant pre-existing subdirectory for that test.

The test and the fix both look good!

@bors r+ rollup

**Comment by pacak** [comment]
> I'm sorry those tidy errors seemed to have sent you on a wild goose chase.

Not your fault. And now I know where to look and why is it happening :)

**Pull request merged**
