### PR TITLE
Cleanup some rustdoc code

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Commits are mostly individual though some do depend on others.

### CODE REVIEW

**Comment by steveklabnik** [comment]
I like it! I'll let @rust-lang/rustdoc review though :0

**Comment by GuillaumeGomez** [comment]
I went very quickly through the code and it seems nice. But could it wait for #52585 to be merged first please? It'd make my life so much easier!

**Comment by Mark-Simulacrum** [comment]
Yep, this can wait. I'll rebase.

**Comment by QuietMisdreavus** [comment]
Where does this PR stand with https://github.com/rust-lang/rust/pull/52630? Or https://github.com/rust-lang/rust/pull/52257? Or the recently-merged https://github.com/rust-lang/rust/pull/52211? There have been several PRs opened recently to clean up or refactor rustdoc, and i'm not sure there has been much coordination between the people who opened them.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/52630 is mostly orthogonal. #52257 looks also different; #52211 also is orthogonal. I believe we all coincidentally found different areas to polish :)

**Comment by Mark-Simulacrum** [comment]
Rebased.

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks! I'd like to have @QuietMisdreavus's confirmation too so let's wait for their reviews. :)

**Comment by QuietMisdreavus** [comment]
Looks good to me! GitHub is reporting some merge conflicts; r=me with those resolved.

**Pull request merged**
