### PR TITLE
Forward rust version number to tools

### PR DESCRIPTION
**Pull request by oli-obk**
Clippy uses it to identify the correct documentation to point to

cc @Manishearth @nrc 

sibling PR in clippy: https://github.com/rust-lang-nursery/rust-clippy/pull/3442

### CODE REVIEW

**Comment by oli-obk** [comment]
Beta nominating to get rustup clippy to point to docs that actually correspond to the lints in the code

**Comment by oli-obk** [comment]
Clippy needs a backport, too. the sibling PR in the op must also be added

**Comment by alexcrichton** [comment]
Sure thing, although should clippy have been included in this PR?

**Pull request merged**
