### PR TITLE
Apply PGO to libstd on CI

### PR DESCRIPTION
**Pull request by Kobzol**
This is an experiment to see if using PGO for the compiler's own `libstd` helps performance.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Kobzol** [comment]
Looks like if `rustc` + `stdlib` PGO is combined, the PGO files are not generated. I'll try to split PGO generation into two steps.

**Comment by jackh726** [comment]
Although there is technically a compiler change, I think this is more bootstrap, so changing label.

**Comment by Dylan-DPC** [comment]
Closing this as it was an experiment

**Pull request closed without merging**
