### PR TITLE
Do not inject test harness for --cfg test

### LINKED ISSUE #33670: Test harness is injected on `--cfg test`
Cargo has an issue (https://github.com/rust-lang/cargo/issues/2305) with a proposed fix (https://github.com/rust-lang/cargo/pull/2469), but it unfortunately can't land because the compiler currently considers `--test` and `--cfg test` synonymous.

I'm... surprised by this behavior, and I'd expect `--cfg test` to *only* pass the `test` cfg.

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #33670.

### CODE REVIEW

**Comment by sanxiyn** [comment]
`config` field of `TestCtxt` is dead. `dead_code` lint actually detects it, but `test.rs` disables this lint with `allow` attribute.

`cfg` argument of `modify_for_testing` is ultimately passed to `ExtCtxt::new`. In turn, the only use in `ExtCtxt` is passing to `Parser::new` so that syntax extensions can use the parser. `test.rs` only uses builder, not parser.

**Comment by nikomatsakis** [comment]
@manishearth I did not think this was plugin breaking but it occurs to me I do not know for sure. :)

**Comment by Manishearth** [comment]
Technically is, by the most stringent definition, but it doesn't look like it will break anything

**Pull request merged**
