### PR TITLE
Rollup of 9 pull requests

### LINKED ISSUE #54707: Creating a trait function with a macro using block designator: error: expected `;` or `{`, found `{ ... }`
Given a simple macro:
```rust
macro_rules! def_fn{
    ($body:block) => {
        fn test() $body
    };
}
```

I can use it without problems to define a function:
```rust
def_fn!({println!("test"); });
```

I can also use it to define a struct method without problems:
```rust
struct Test {}

impl Test {
    def_fn!({println!("test"); });
}
```

However when I try to use it to define a default method for a trait it doesn't work:
```rust
trait Test {
    def_fn!({println!("test"); });
}
```

It gives an error message:
```
error: expected `;` or `{`, found `{ println!("test"); }`
  --> src/main.rs:9:19
   |
9  |         fn test() $body
   |                   ^^^^^ expected `;` or `{`
...
16 |     def_fn!({println!("test"); });
   |     ------------------------------ in this macro invocation
error: aborting due to previous error
```

If I change the macro to include braces around `$body` it works:
```rust
macro_rules! def_fn{
    ($body:block) => {
        fn test() {$body}
    };
}
```

I have no idea why this happens but I guess it is some sort of bug in how default trait methods are parsed.

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #54747 (codegen_llvm: verify that inline assembly operands are scalars)
 - #54848 (Better Diagnostic for Trait Object Capture)
 - #54850 (Fix #54707 - parse_trait_item_ now handles interpolated blocks as function body decls)
 - #54858 (second round of refactorings for universes)
 - #54862 (Implement RFC 2539: cfg_attr with multiple attributes)
 - #54869 (Fix mobile docs)
 - #54870 (Stabilize tool lints)
 - #54893 (Fix internal compiler error on malformed match arm pattern.)
 - #54904 (Stabilize the `Option::replace` method)

Failed merges:

 - #54909 ( Add chalk rules related to associated type defs)

r? @ghost

### CODE REVIEW

**Comment by kumbayo** [comment]
@Manishearth It looks like there is something strange happening in this kind of rollup merges.

This rollup consists of multiple merge commits.
a267b3a9ff041c92c3ce71a285512d97ae8f208b
8ebc6d6dbbfe1ccc9a72d003d13c3d267c91c742
50e410c240bc8f147e7bf1efb5741d41c67e6328
e1e628ec87b22b3df661d257255fd198651a1801
ff3e4d9f1c4b8e4faecd2bf95e2f52abb9380250
be64bf3b9dea4b5f30b7044fcb2c1b86f3e7960f

All this merge commits seem to have the same commit message body unrelated to the actual thing being merged:
```
Fixes #47311.
r? @nrc
```
This usage of the same commit message body seems to go back to Feb 2018 as it can be seen in #47311.
The commit message title is unique for each merge and looks correct.

Do you have some idea what is going on here?
Are this commit messages created by a script doing the rollup merges?

**Comment by Manishearth** [comment]
Oh, shoot. Yeah, I used a script since it's easier to handle, looks like something on the github side changed .

Thanks for noticing, will fix up my script!

**Pull request merged**
