### PR TITLE
rustdoc: write directly to buffer in `inner_full_print`

### PR DESCRIPTION
**Pull request by notriddle**
This change avoids several temporary allocations for every argument.

### CODE REVIEW

**Comment by CraftSpider** [comment]
This looks fine, going to do a perf run and see if it has any impact. I think it's...
@bors try @rust-timer queue

**Comment by CraftSpider** [comment]
I'm not 100% sure how perf handles doc changes, and whether these are relevant. I'm going to ask the perf team on Zulip.

**Comment by nnethercote** [comment]
The ones labelled `doc` measure rustdoc speed. The website filters uninteresting results by default, you can uncheck the "Show only significant changes" and "Filter out very small changes" boxes to see all the results.

In short, very little changed. The variations you do see are almost certainly noise. I think your changes are good -- they do avoid unnecessary allocations, and make the code easier to read -- but I suspect they happen on a code path that isn't hot.

**Comment by camelid** [comment]
The regression is spurious.

@rustbot label: +perf-regression-triaged

**Pull request merged**
