### PR TITLE
Allow none Sized types in assert_eq!

### PR DESCRIPTION
**Pull request by ollie27**
`format_args!` doesn't support none Sized types so we should just pass it the references to `left_val` and `right_val`.

The following works:

``` rust
assert!([1, 2, 3][..] == vec![1, 2, 3][..])
```

So I would expect this to as well:

``` rust
assert_eq!([1, 2, 3][..], vec![1, 2, 3][..])
```

But it fails with "error: the trait `core::marker::Sized` is not implemented for the type `[_]` [E0277]"
I don't know if this change will have any nasty side effects I don't understand.

### CODE REVIEW

**Comment by bluss** [comment]
Does this change which type needs to impl Debug?

Imagine left_val and right_val are `String`, previous code:

```
if *left_val == *right_val {
   println!("{:?} == {:?}", *left_val, *right_val);
}
```

Previous code would have it compare as `str` and print as `&str`.

New code compares `str` and prints as `&String`.

The potential breaking change comes when `String` does not impl Debug but `str` does? Is my thinking around this correct?

Workaround would be to use `&*left_val` instead of removing the * entirely.

**Comment by ollie27** [comment]
Can `left_val` and `right_val` even be `String`s as they come from the following so must be references right?
```rust
match (&($left), &($right)) {
    (left_val, right_val) => {
```

**Comment by bluss** [comment]
Oh that's a good point :smile:.

**Comment by alexcrichton** [comment]
Thanks! Could you also add a test for this?

**Comment by ollie27** [comment]
I've added a test, I hope it's in the right place.

**Pull request merged**
