### PR TITLE
Fix #54224 (const promotion regression)

### LINKED ISSUE #54224: Borrowing static array that contains another static array represented by literal doesn't work when expressed inline
Why does this work:

```
use std::borrow::Cow;

pub const X: [u8; 3] = *b"ABC";
pub const Y: Cow<'static, [ [u8; 3] ]> = Cow::Borrowed(&[X]);
```

but this doesn't?

```
use std::borrow::Cow;

pub const Z: Cow<'static, [ [u8; 3] ]> = Cow::Borrowed(&[*b"ABC"]);
```

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb

### CODE REVIEW

**Comment by TimNN** [comment]
Ping from triage @eddyb / @rust-lang/compiler: This PR requires your review.

**Comment by oli-obk** [comment]
This is a regression introduced in https://github.com/rust-lang/rust/pull/51990#discussion_r218967748

We'll want to relax this in the future, but for now we should not change behaviour

**Comment by RalfJung** [comment]
There still is a `Qualif::NOT_CONST` below a `self.mode` test at https://github.com/rust-lang/rust/blob/670d07efbb3fc3d5c7b38fefec39db9cfc6a1294/src/librustc_mir/transform/qualify_consts.rs#L738 Is that correct? If yes, could you add a comment saying why this is only rejected for `Fn` but not for the other modes?

Same for https://github.com/rust-lang/rust/blob/670d07efbb3fc3d5c7b38fefec39db9cfc6a1294/src/librustc_mir/transform/qualify_consts.rs#L762

**Comment by RalfJung** [comment]
Oh I see, the difference is that in the other cases we *always* emit a feature gate in the `else`. That's what went wrong here.  Thanks!

@bors r+

**Pull request merged**
