### PR TITLE
Unignore tests in stage1

### LINKED ISSUE #20184: Panic => hang with -C codegen-units=2
Building `src/test/compile-fail/asm-src-loc-codegen-units.rs`, I get

```
$ RUST_BACKTRACE=1 x86_64-unknown-linux-gnu/stage1/bin/rustc /home/keegan/rust/src/test/compile-fail/asm-src-loc-codegen-units.rs -L x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage1-x86_64-unknown-linux-gnulibaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage1-x86_64-unknown-linux-gnu --cfg rtopt --cfg debug -C rpath -O -L x86_64-unknown-linux-gnu/rt -C codegen-units=2  
thread 'codegen-1' panicked at 'Box<Any>', /home/keegan/rust/src/libsyntax/diagnostic.rs:144  
stack backtrace:  
   1:     0x7fa4c3cc6160 - sys::backtrace::write::h65ec9c5123795f5a7Et  
   2:     0x7fa4c3ce1560 - failure::on_fail::h57fab0e8dcfaeb44q5z  
   3:     0x7fa4c3c64d30 - rt::unwind::begin_unwind_inner::hfb3e098e3005b453qJz  
   4:     0x7fa4bf1b71d0 - rt::unwind::begin_unwind::h10618648795271420137  
   5:     0x7fa4bf1b7c70 - diagnostic::Handler::fatal::h4880a8481789b123GZF  
   6:     0x7fa4bf1b7e70 - diagnostic::Handler::abort_if_errors::h67ec7bdbe130dc33m1F  
   7:     0x7fa4c2b9b470 - thunk::F.Invoke<A,$u{20}R$GT$::invoke::h6510616859115949120  
   8:     0x7fa4c2b9a250 - rt::unwind::try::try_fn::h2108817931159087488  
   9:     0x7fa4c3d50080 - rust_try_inner  
  10:     0x7fa4c3d50070 - rust_try  
  11:     0x7fa4c2b9a4f0 - thunk::F.Invoke<A,$u{20}R$GT$::invoke::h6356295493119065651  
  12:     0x7fa4c3cd3870 - sys::thread::thread_start::h343c9a18cc8a2c6fxDw  
  13:     0x7fa4be9d0fe0 - start_thread  
  14:     0x7fa4c3911c99 - __clone  
  15:                0x0 - <unknown>  
```

at which point rustc hangs. Version: 96a3c7c6a051ab2f5fc01fe9e686f7fffcc87c61 (current master)

### PR DESCRIPTION
**Pull request by tamird**
We don't have any pending snapshot-requiring changes.

Works toward #3965.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Just to confirm, have you run all these tests in stage1? Plugins fundamentally don't work in stage1, so many of these I believe are intentional.

**Comment by tamird** [comment]
I haven't, but I'll do that now!

**Comment by tamird** [comment]
Hm. `make check-stage1` passed locally.

**Comment by alexcrichton** [comment]
Ah right, it is possible for these tests to work at stage1 (if codegen is similar enough in stage0 and stage1), but it's not guaranteed. For example if codegen changes after stage0 then plugins will be broken.

**Comment by tamird** [comment]
So: wat do?

**Comment by tamird** [comment]
wat do

**Comment by alexcrichton** [comment]
I think that this should back out the removal of `// ignore-stage` from all `*-fulldeps` tests, but all changes to `src/test/{auxiliary,run-pass}` look good to me!

**Comment by tamird** [comment]
I think it's probably OK to unignore compilefail-fulldeps; do you agree?

**Comment by alexcrichton** [comment]
I think it kinda depends on the test. Anything which expects `#![plugin]` to *succeed* (e.g. have the `dlopen` be a success) must be ignored in stage1, but some of these tests are expecting a compiler error before we hit that point so they can be un-ignored yeah.

**Comment by tamird** [comment]
@alexcrichton is there a change I can make locally to induce the condition that would break these tests in stage1? feels a bit like a guessing game otherwise.

**Comment by alexcrichton** [comment]
I think if you [change the symbol hashing function](https://github.com/rust-lang/rust/blob/222cd73b8a422d2c4124375f6aaffd2663bb9718/src/librustc_trans/back/link.rs#L196-L217) it'll cause the symbols to be totally different at stage1 than they were at stage0, so you can try just adding `symbol_hasher.input_str("foo")` somewhere in there perhaps? I haven't exactly tested out this theory though, so it also may not work :(

**Comment by tamird** [comment]
Your suggestion worked! I tested these locally and they passed (with the hashing change) so this should be good to merge. Thanks for your help @alexcrichton.

**Comment by alexcrichton** [comment]
@bors: r+ f548a05

Nice! Thanks!

**Pull request merged**
