### PR TITLE
Reword the non-dropping of `src` for `ptr::write{,_unaligned}`

### PR DESCRIPTION
**Pull request by tbu-**
@niconii Is it OK if I put your wording into the documentation?
CC @nagisa

### CODE REVIEW

**Comment by nagisa** [comment]
Lgtm

**Comment by niconii** [comment]
Sure.

**Comment by tbu-** [comment]
Documentation, so probably r? @steveklabnik

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks ❤️

**Pull request merged**
