### PR TITLE
Stabilize Condvar::wait_while and wait_timeout_while (previously wait_until, wait_timeout_until)

### LINKED ISSUE #47960: CondVar wait functions accepting a closure
Pretty common for conditional variable classes to provide wait variants that accept a closure that returns a boolean indicating whether or not the condition has been satisfied.  This would be a pretty nice ergonomic improvement to using CondVar.  Something like ```cvar.wait_until(lock, || { some condition })```.   Even more useful would be a ```wait_timeout_until``` which would avoid the need to keep track of elapsed time if the condition variable might get notified several times before the condition is met.

### PR DESCRIPTION
**Pull request by mbrubeck**
Closes #47960.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @dtolnay for commencing FCP here, this is proposing to stabilize the following APIs, implemented in #47970.

```rust
impl Condvar {
    fn wait_until<'a, T, F>(&self, mut guard: MutexGuard<'a, T>,
                            mut condition: F)
                            -> LockResult<MutexGuard<'a, T>>
                            where F: FnMut(&mut T) -> bool;
    fn wait_timeout_until<'a, T, F>(&self, mut guard: MutexGuard<'a, T>,
                                    dur: Duration, mut condition: F)
                                    -> LockResult<(MutexGuard<'a, T>, WaitTimeoutResult)>
                                    where F: FnMut(&mut T) -> bool;
}
```

For some background, these APIs mirror the ones present in C++ (though there they are through overloads on [`std::condition_variable::wait`](https://en.cppreference.com/w/cpp/thread/condition_variable/wait) and [`wait_for`](https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for)). There appear to be no open questions on the tracking issue. The API being fairly verbose due to the absorbance of poisoning along with timeouts into the return type. It seems that unless we choose to diverge from the main API `Condvar::wait`, this is the only API we can go with. I suspect that such a divergence would not be worth it in the overall design of Condvar.

`parking_lot` does not implement these two functions, though it does offer a `wait_until` API -- but that focuses on `Instant` rather than `Duration` plus a closure. I think the divergence here isn't ideal but std is staying consistent with the APIs currently provided.

Before stabilization, we would likely want to update the documentation to avoid the language around ignoring spurious wakeups (which is not true; the closure is still run).

**Comment by dtolnay** [comment]
I am on board with these APIs.

These are practically always what you want -- there are few use cases for directly using `wait` or `wait_timeout` that isn't an exact reimplementation of `wait_until` or `wait_timeout_until`. The main exception would when you need a condition that is fallible. Based on @mbrubeck's comment in https://github.com/rust-lang/rust/issues/47960#issuecomment-562361039 asking for these to be stabilized, I expect their codebase consists of conditions that are all or almost all infallible where these APIs are a good fit.

```rust
impl Condvar {
    fn wait_until<'a, T, F>(
        &self,
        mut guard: MutexGuard<'a, T>,
        mut condition: F,
    ) -> LockResult<MutexGuard<'a, T>>
    where
        F: FnMut(&mut T) -> bool;

    fn wait_timeout_until<'a, T, F>(
        &self,
        mut guard: MutexGuard<'a, T>,
        dur: Duration,
        mut condition: F,
    ) -> LockResult<(MutexGuard<'a, T>, WaitTimeoutResult)>
    where
        F: FnMut(&mut T) -> bool;
}
```

@rfcbot fcp merge

**Comment by Amanieu** [comment]
@rfcbot concern _until naming

Using the name `_until` might cause confusion if in the future we add a different way of specifying an timeout using an `Instant` instead of a `Duration`.

See [parking_lot's `Condvar::wait_until`](https://docs.rs/parking_lot/0.10.0/parking_lot/struct.Condvar.html#method.wait_until).

**Comment by dtolnay** [comment]
Good call. Perhaps `wait_while`, with the meaning of the bool inverted? Std has lots of other `while` methods with predicates, and it is unambiguous with referring to a timeout. @mbrubeck do you have a sense of whether inverting the bool would cause confusing negations in your codebase?

**Comment by mbrubeck** [comment]
Our uses look like approximately like:

```
wait_until(guard, |count| count == 0)
// or
wait_until(guard, |started| started)
```

I think these are about equally readable as:

```
wait_while(guard, |count| count > 0)
// or
wait_while(guard, |started| !started)
```

(Or in the last one we could flip the meaning of the boolean and rename it to `pending`.)

**Comment by KodrAus** [comment]
@rcfbot reviewed

**Comment by dtolnay** [comment]
That looks all right to me. I would be prepared to accept this stabilization after a rename to wait_while / wait_timeout_while.

**Comment by mbrubeck** [comment]
Added a commit to rename both methods (flipping the meaning of the condition) and update all docs and tests.

**Comment by mbrubeck** [comment]
Why hasn't this entered final comment period yet? Does the concern need to be marked resolved?

**Comment by Amanieu** [comment]
@rfcbot resolved _until naming

**Comment by RalfJung** [comment]
Shouldn't renaming usually mean we wait a bit for further feedback before stabilizing?

**Comment by sfackler** [comment]
Not always - sometimes the thing we learn from the FCP is that we want to make a small change (like wait_until -> wait_while), but otherwise feel confident enough that we don't need to wait another N months to stabilize.

**Review by dtolnay — APPROVED** [review]
Thanks @mbrubeck!

**Pull request merged**
