### PR TITLE
update mdbook

### PR DESCRIPTION
**Pull request by steveklabnik**
This eliminates some warnings

r? @alexcrichton

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors r-

looks like there's a Cargo.lock parsing error: https://github.com/rust-lang/rust/pull/44482

**Comment by steveklabnik** [comment]
Very odd, given that I only used Cargo; I've pushed https://github.com/rust-lang/rust/pull/44430/commits/4eaffdbd2cd9d010148408f025edc8ca58582723 which ends up updating other deps as well, we'll see how it goes.

**Comment by steveklabnik** [comment]
@bors: r-

uuugh

**Comment by steveklabnik** [comment]
@bors: r=alexcrichton

i re-did it and this seems to be working now

**Pull request merged**
