### PR TITLE
Add Entry::occupied(), Entry::vacant() option getters

### PR DESCRIPTION
**Pull request by coolreader18**
I'm not sure if I'm allowed to just open this kind of thing, but it seemed minor enough that it wouldn't need a full RFC.

Some of the reasoning for this is:
- Importing the `Entry` enum into scope is annoying, it's 4 path segments and is just kinda verbose; I think composing using helper methods on `Entry` is much nicer, and the API is already kinda geared in that direction.
- For these methods specifically, none of the existing helper methods cover the cases where:
  - you want to do something to a `VacantEntry` and remember that it was vacant, which could be done with `entry.vacant().map(|v| { ... })`
  - you want to remove the entry if it's present, or maybe modify it, and remember that it was occupied. e.g. `entry.occupied().map(|o| o.remove() + 1)`

:shrug: these are pretty specific use cases, but in general these can be used for composing more `entry` operations.

### CODE REVIEW

**Comment by hanna-kruppe** [comment]
I don't have a strong opinion on this and I don't have much time to put into Rust reviews, so I'll cc @rust-lang/libs and hope one of them can pick this up.

**Comment by Amanieu** [comment]
I'm having trouble seeing how this API would be useful when we already have `insert` and `remove` methods on `HashMap`. Can you show me a real use case where this API would make code simpler or more readable?

**Comment by coolreader18** [comment]
To be honest, I'm not sure; a friend asked if there's anything like these methods to avoid pattern matching when he wanted to panic if the entry wasn't occupied, and I said no and suggested a way to refactor what he was doing so that he didn't even need to panic, which I guess might mean that this would actually be a code smell ¯\\\_(ツ)\_/¯. Though, if you wanted to do some operations on an occupied entry and then conditionally remove it, I think this would make sense:
```rust
let mut o = map.entry("key").occupied().unwrap();
o.get_mut().set_foo(1);
if o.get().bar() {
    things.push(o.remove())
}
```
It might be better to just do `get_mut` and `remove`, though. Again, ¯\\\_(ツ)\_/¯.

**Comment by coolreader18** [comment]
To be honest, I'm not sure; a friend asked if there's anything like these methods to avoid pattern matching when he wanted to panic if the entry wasn't occupied, and I said no and suggested a way to refactor what he was doing so that he didn't even need to panic, which I guess might mean that this would actually be a code smell ¯\\\_(ツ)\_/¯. Though, if you wanted to do some operations on an occupied entry and then conditionally remove it, I think this would make sense:
```rust
let mut o = map.entry("key").occupied().unwrap();
o.get_mut().set_foo(1);
if o.get().bar() {
    things.push(o.remove())
}
```
It might be better to just do `get_mut` and `remove`, though. Again, ¯\\\_(ツ)\_/¯.

**Comment by Amanieu** [comment]
In my experience, most uses of `Entry` involve wanting to perform operations in both the `Vacant` and `Occupied` cases. I'm going to close this since I don't feel that these methods are sufficiently useful to justify the additional API surface.

**Comment by coolreader18** [comment]
Alright, that makes sense.

**Comment by LukasKalbertodt** [comment]
Closing as discussed. Thanks a lot for your PR anyway!

**Pull request closed without merging**
