### PR TITLE
doc: Insert examples with universal function call syntax

### PR DESCRIPTION
**Pull request by EdorianDark**

### CODE REVIEW

**Comment by frewsxcv** [comment]
```
failures:

---- f32::f32::atan2_0 stdout ----
	error: no associated item named `EPSILON` found for type `f32` in the current scope
  --> <anon>:16:29
   |
16 | assert!(abs_difference_1 <= f32::EPSILON);
   |                             ^^^^^^^^^^^^

error: no associated item named `EPSILON` found for type `f32` in the current scope
  --> <anon>:17:29
   |
17 | assert!(abs_difference_2 <= f32::EPSILON);
   |                             ^^^^^^^^^^^^

error: aborting due to previous error(s)

thread 'f32::f32::atan2_0' panicked at 'Box<Any>', src/librustc/session/mod.rs:171
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    f32::f32::atan2_0

test result: FAILED. 545 passed; 1 failed; 19 ignored; 0 measured

error: test failed
```

**Comment by frewsxcv** [comment]
In my opinion, I don't think we need to display both the method call syntax and the UFCS syntax, it seems redundant.

**Comment by EdorianDark** [comment]
In my opinion the examples are mainly for persons new to rust, which may not yet know about UFCS.
And coming from a mathematical standpoint something like "x.max(y)" looks wrong.
The function max is defined as a function with 2 parameters, which would look like "max(x,y).
Therefore I think presenting both call syntaxes makes it easier to understand.

In the example for atan2 I did not add any lines of code, do you think that is OK?

**Comment by EdorianDark** [comment]
Currently the example for atan2 explains the implementation.
Can I change it into a explanation of the application, finding the angle for a given point?

**Comment by aturon** [comment]
Thanks for the PR, but I have to agree with @frewsxcv: this is not the place to teach UFCS. In addition, while the method notation may seem strange from a mathematical standpoint, it was a choice made in the API design (as opposed to using free functions) and we should present the API as intended to be used.

I'm going to close this out for the time being.

**Pull request closed without merging**
