### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #108516 (Restrict `#[rustc_box]` to `Box::new` calls)
 - #108575 (Erase **all** regions when probing for associated types on ambiguity in astconv)
 - #108585 (Run compiler test suite in parallel on Fuchsia)
 - #108606 (Add test case for mismatched open/close delims)
 - #108609 (Highlight whole expression for E0599)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=108516,108575,108585,108606,108609)

### CODE REVIEW

**Comment by lqd** [comment]
#108575 is supposed to be on the error path and shouldn't be the cause here, but the regressions do contain more query traffic for associated_items, and it seems to be one of the few related things in this rollup.

So let's see just in case:
@rust-timer build 920d37d09964cf017aa3a0ccb49d4e3dd34e134b

**Comment by lqd** [comment]
Come on, bot.

@rustbot label: +perf-regression

**Comment by rylev** [comment]
@nnethercote checking for triage: is there anything we should do to try to address this or do we just take this as another test case we should expect to see occasional perf swings in?

**Comment by nnethercote** [comment]
`keccak` and `cranelift-codegen` are always bimodal in sync. This `deep-vector` regression involves the same code but appears to be a once-off. I won't pretend to understand why it's behaving differently. But I am confident it's a question of code generation quality rather than, say, some change in the compiler that caused it to call the relevant functions more times. (I can tell this because in the Cachegrind profiles a lot of the lines in the relevant functions have the same number of instruction counts, but then others have higher instruction counts.)

**Comment by rylev** [comment]
I think that's enough justification to call this triaged. While we don't have a good explanation, there's no real point in trying to find code changes in this rollup that are to blame.

@rustbot label +perf-regression-triaged

**Pull request merged**
