### PR TITLE
Tweak future opaque ty pretty printing

### PR DESCRIPTION
**Pull request by compiler-errors**
1. The `Return` type of a generator doesn't need to be a lang item just for diagnostic printing of types
2. We shouldn't suppress the `Output = Ty` of a opaque future if the type is a int or float var.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Gah, rebase failure.

**Comment by jackh726** [comment]
I don't know if I'm remembering wrong, but I had made a similar change before (maybe it was more general, all associated types? don't quite remember), but it had to be reverted because of something - I think symbol mangling?

Not really sure. Seems like a fairly simple change.

**Comment by compiler-errors** [comment]
@jackh726 do you mind trying to find that PR you mentioned? 

This doesn't mess with the representation of the type -- I've touched this code a few times (I'm the one that added this lang item and added this special `impl Future` printing logic in the first place) so that kinda surprises me.

**Comment by jackh726** [comment]
It was probably something else :)

@bors r+

**Pull request merged**
