### PR TITLE
Attach tokens to all AST types used in `Nonterminal`

### PR DESCRIPTION
**Pull request by Aaron1011**
We perform token capturing when we have outer attributes (for nonterminals that support attributes - e.g. `Stmt`), or when we parse a `Nonterminal` for a `macro_rules!` argument. The full list of `Nonterminals` affected by this PR is:

* `NtBlock`
* `NtStmt`
* `NtTy`
* `NtMeta`
* `NtPath`
* `NtVis`
* `NtLiteral`

Of these nonterminals, only `NtStmt` and `NtLiteral` (which is actually just an `Expr`), support outer attributes - the rest only ever have token capturing perform when they match a `macro_rules!` argument.

This makes progress towards solving https://github.com/rust-lang/rust/issues/43081 - we now collect tokens for everything that might need them. However, we still need to handle `#[cfg]`, inner attributes, and misc pretty-printing issues (e.g. #75734)

I've separated the changes into (mostly) independent commits, which could be split into individual PRs for each `Nonterminal` variant. The purpose of having them all in one PR is to do a single Crater run for all of them.

Most of the changes in this PR are trivial (adding `tokens: None` everywhere we construct the various AST structs). The significant changes are:

* `ast::Visibility` is changed from `type Visibility = Spanned<VisibilityKind>` to a `struct Visibility { kind, span, tokens }`.
* `maybe_collect_tokens` is made generic, and used for both `ast::Expr` and `ast::Stmt`.
* Some of the statement-parsing functions are refactored so that we can capture the trailing semicolon.
* `Nonterminal` and `Expr` both grew by 8 bytes, as some of the structs which are stored inline (rather than behind a `P`) now have an `Option<TokenStream>` field. Hopefully the performance impact of doing this is negligible.

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot abort

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
The handling of `NtStmt` is incorrect - we should be delegating to the `StmtKind`, which is responsible for storing attributes.

@craterbot abort

**Comment by petrochenkov** [comment]
@Aaron1011 
`NtStmt` is very broken and it's a pre-existing issue (it is also almost unused in practice).
It would be a reasonable option to omit it from this PR.

**Comment by Aaron1011** [comment]
@petrochenkov: Sounds good to me.

@craterbot check

**Comment by petrochenkov** [comment]
Three legitimate root regressions - `deno_doc`, `rustactoe` and `cpp-inherit-test`, other failures are unrelated to this PR.
Details need investigation.

**Comment by Aaron1011** [comment]
`deno_doc` had an unhygenic macro, which I fixed in https://github.com/bartlomieju/deno_doc/pull/1
`rustactoe` just needed a dependency bump, which I did in https://github.com/rbalicki2/rustactoe/pull/7
`cpp-inherit-test` is actually a spurious failure - the panic appears to have come from [this call to the memmap crate](https://github.com/jam1garner/cpp-inherit/blob/d677053daed6ba6007bcdbcb2b197ff8adbd813c/src/vtable/dwarf.rs#L20), which apparently ended up with a zero-length file. The crate built successfully on my machine.

**Comment by Aaron1011** [comment]
In https://github.com/rust-lang/rust/issues/76480#issuecomment-689614448, @emilio brought up some concerns with how we handle the rollout of these kinds of breaking changes. I came up with a few ideas in https://github.com/rust-lang/rust/issues/76480#issuecomment-689654797

While the impact of this PR appears to be very small (especially compared to https://github.com/rust-lang/rust/issues/76480#issuecomment-689654797), I think it's worth considering the best way to roll out these kinds of 'un-warnable' changes. There are going to be at least two more instances of this type of change (see https://github.com/rust-lang/rust/pull/76130 and https://github.com/rust-lang/rust/issues/75734), so I think it would be good to come up with a plan sooner rather than later.

**Comment by Aaron1011** [comment]
Remaining steps before this PR can be merged:

* Wait for the two broken crates to merge PRs
* Decide on what kind of additional notification (if any) we want to give to the ecosystem, as described above.

**Comment by petrochenkov** [comment]
There are only two affected crates and no other crates depend on them, so I think we can land this now without warnings or waiting.

`NtStmt`-related changes need to be backed out though, and the history can be cleaned up a bit.

**Comment by Aaron1011** [comment]
@petrochenkov: I've condensed the commits further, and backed out some of the `NtStmt` changes.
I left in token collection for `:stmt` matchers, since it affects the behavior of stable code.

**Comment by Aaron1011** [comment]
```
2020-09-11T01:55:37.4205616Z test process::tests::set_current_dir_works ... ok
2020-09-11T01:55:37.5548862Z [0m[0m[1m[31merror[0m[1m:[0m test failed, to rerun pass '-p std --lib'
2020-09-11T01:55:37.5549312Z 
2020-09-11T01:55:37.5549575Z Caused by:
2020-09-11T01:55:37.5551189Z   process didn't exit successfully: `/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-2996f0f88f1190de` (signal: 11, SIGSEGV: invalid memory reference)
2020-09-11T01:55:37.5571913Z 
2020-09-11T01:55:37.5572407Z 
2020-09-11T01:55:37.5575181Z command did not execute successfully: "/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--locked" "--frozen" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/obj/build/tmp/distcheck/library/test/Cargo.toml" "-p" "std" "--"
2020-09-11T01:55:37.5577464Z expected success, got: exit code: 101
2020-09-11T01:55:37.5577757Z 
2020-09-11T01:55:37.5577908Z 
2020-09-11T01:55:37.5584916Z failed to run: /checkout/obj/build/tmp/distcheck/build/bootstrap/debug/bootstrap test --stage 2
2020-09-11T01:55:37.5585653Z Build completed unsuccessfully in 0:27:49
2020-09-11T01:55:37.5674366Z make: *** [check] Error 1
2020-09-11T01:55:37.5675254Z Makefile:42: recipe for target 'check' failed
2020-09-11T01:55:37.5675789Z 
2020-09-11T01:55:37.5676174Z 
2020-09-11T01:55:37.5676639Z command did not execute successfully: "make" "check"
2020-09-11T01:55:37.5677157Z expected success, got: exit code: 2
2020-09-11T01:55:37.5677429Z 
2020-09-11T01:55:37.5677609Z 
2020-09-11T01:55:37.5690417Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap --stage 2 test distcheck
2020-09-11T01:55:37.5691477Z Build completed unsuccessfully in 0:29:46
2020-09-11T01:55:37.5810819Z == clock drift check ==
2020-09-11T01:55:37.5820379Z   local time: Fri Sep 11 01:55:37 UTC 2020
2020-09-11T01:55:37.7287572Z   network time: Fri, 11 Sep 2020 01:55:37 GMT
2020-09-11T01:55:37.7288224Z == end clock drift check ==
2020-09-11T01:55:38.1083046Z ##[error]Process completed with exit code 1.
2020-09-11T01:55:38.1112763Z Cleaning up orphan processes
2020-09-11T01:55:38.2327184Z Terminate orphan process: pid (5505) (node)
2020-09-11T01:55:38.2354662Z Terminate orphan process: pid (5514) (python)
```
This looks somewhat concerning, but seems unrelated to this PR.

@bors retry

**Pull request merged**
