### PR TITLE
tweaks to move NLL bootstrap along

### PR DESCRIPTION
**Pull request by nikomatsakis**
This includes two legitimate bug fixes, but one workaround.

### CODE REVIEW

**Comment by TimNN** [comment]
I think this needs to have `Cargo.lock` regenerated?

**Comment by nikomatsakis** [comment]
@TimNN done

**Comment by nikomatsakis** [comment]
Rebased, added some more progress.

**Comment by shepmaster** [comment]
```
[00:04:26] tidy error: /checkout/src/test/run-pass-fulldeps/auxiliary/macro_crate_test.rs:58: line longer than 100 chars
```

**Comment by pietroalbini** [comment]
@nikomatsakis there is a tidy lint failing and a merge conflict, could you solve those so the PR can be merged?

**Comment by nikomatsakis** [comment]
@pietroalbini planning on getting back to this later this week

**Comment by nikomatsakis** [comment]
Gonna close this for now.

**Pull request closed without merging**
