### PR TITLE
Fix unboxed closure ICE

### PR DESCRIPTION
**Pull request by nikomatsakis**
This fixes an ICE that japaric was encountering in the wf checker.

r? @aturon

### CODE REVIEW

**Comment by japaric** [comment]
This is blocking the removal of boxed closures. This needs to get in a snapshot to be able to remove them.

**Comment by nikomatsakis** [comment]
(Please give high priority.)

**Comment by japaric** [comment]
(@aturon you r+ed on the rust-lang repo instead of @nikomatsakis's fork, I put the r+ on the right place)

**Comment by aturon** [comment]
@japaric This seems to be a github inconsistency, right? I don't think I'm varying the way I reach these commits...

**Comment by nikomatsakis** [comment]
@aturon yes you have to check the URL bar to see if it says "rust-lang" or "nikomatsakis" -- as far as I know, it's random.

**Comment by japaric** [comment]
> This seems to be a github inconsistency, right? I don't think I'm varying the way I reach these commits...

Yes, I think so. It has also happened to me. Best to double check from now on...

**Comment by alexcrichton** [comment]
I've found that if you click a commit *just after* it was uploaded, you'll go to the rust-lang commit, but if you wait a bit it'll take you to the $user commit.

yay github!

**Pull request merged**
