### PR TITLE
Fixed a typo. Removed an extra s.

### PR DESCRIPTION
**Pull request by sindreij**

### CODE REVIEW

**Comment by caipre** [comment]
I think it's actually meant to be:

    You can find more documentation for `slice`s in the standard library.

**Comment by alexcrichton** [comment]
I think I agree with @caipre here as well, although I also find it a little surprising this is in backticks at all, so I'd be fine with just removing them altogether. Thanks for the patch!

**Comment by sindreij** [comment]
I agree that not having backtics at all looks better, I have removed the backticks.

**Pull request merged**
