### PR TITLE
rustdoc: add flag to control the html_root_url of dependencies

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
The `--extern-html-root-url` flag in this PR allows one to override links to crates whose docs are not already available locally in the doc bundle. Docs.rs currently uses a version of this to make sure links to other crates go into that crate's docs.rs page. See the included test for intended use, but the idea is as follows:

Calling rustdoc with `--extern-html-root-url crate=https://some-url.com` will cause rustdoc to override links that point to that crate to instead be replaced with a link rooted at `https://some-url.com/`. (e.g. for docs.rs this would be `https://docs.rs/crate/0.1.0` or the like.) Cheekily, rustup could use these options to redirect links to std/core/etc to instead point to locally-downloaded docs, if it so desired.

Fixes https://github.com/rust-lang/rust/issues/19603

### CODE REVIEW

**Comment by ollie27** [comment]
This should probably require passing the full URL like `--extern-html-root-url core=https://example.com/core/0.1.0` rather than hard-coding the URL scheme of doc.rs.

I guess this will fix #19603?

**Comment by QuietMisdreavus** [comment]
> This should probably require passing the full URL like `--extern-html-root-url core=https://example.com/core/0.1.0` rather than hard-coding the URL scheme of doc.rs.

That's probably a better solution. @onur, will this work out on your end?

> I guess this will fix #19603?

Looks like it! I forgot there was an issue for this, haha.

**Comment by onur** [comment]
@QuietMisdreavus thank you very much for porting this change. Yes I think @ollie27's solution is better, and it will allow anyone to create his own documentation repository.

I'll test this as soon as I can and return to you.

**Comment by QuietMisdreavus** [comment]
I've force-pushed a version that uses the single `--extern-html-root-url` flag.

**Comment by pietroalbini** [comment]
Ping from triage @rust-lang/rustdoc! This PR needs your review.

**Comment by GuillaumeGomez** [comment]
It's up to @onur in here. :)

**Comment by GuillaumeGomez** [comment]
@onur will just give his approval and at this point I'll `r=onur`.

**Comment by pietroalbini** [comment]
Ping from triage @onur! This PR needs your review.

**Comment by stokhos** [comment]
Ping from triage @onur will you have time to review this PR?

**Comment by stokhos** [comment]
Ping from triage @rust-lang/rustdoc , guys, this PR needs a new reviewer.

**Comment by QuietMisdreavus** [comment]
We were specifically asking for @onur's expertise, as this feature was written for use within docs.rs.

**Comment by GuillaumeGomez** [comment]
You should ask to @onur to review directly on IRC. :)

**Comment by stokhos** [comment]
Ping from triage @onur will you have time to review this PR?

**Comment by pietroalbini** [comment]
Ping from triage @onur! This PR needs your review.

**Comment by TimNN** [comment]
Ping from triage @rust-lang/rustdoc. It looks like @onur is unresponsive here. Could you please make a decision on how to move forward with this PR? Otherwise I'll close this, given that it has been blocked for over a month now, as per our [triage guidelines](https://forge.rust-lang.org/triage-procedure.html).

**Comment by GuillaumeGomez** [comment]
This has been done specifically for `docs.rs` so we really need @onur's review in here. I'll try to reach him on IRC.

**Comment by pietroalbini** [comment]
Ping from triage @onur! This PR needs your review.

**Comment by GuillaumeGomez** [comment]
Time to get it in.

@bors: r+

**Comment by QuietMisdreavus** [comment]
```
[00:52:20] Cloning into 'cortex-m'...
[00:52:20] fatal: unable to access 'https://github.com/rust-embedded/cortex-m/': Could not resolve host: github.com
```

@bors retry

**Pull request merged**
