### PR TITLE
Fixes some style issues in rustdoc "implementations on Foreign types"

### LINKED ISSUE #51113: rustdoc: The default style of items inside "Implementations on Foreign Types" is very ugly
Demo: https://doc.rust-lang.org/beta/alloc/slice/trait.SliceIndex.html

screenshot_2018-05-28 03 53 53_nm2wqt-fs8

There are many unnecessary elements applied to the "Implementations on Foreign Types" which probably should all be removed.

cc @QuietMisdreavus (#43849)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #51113.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Do you have a screenshot with the new change?

**Comment by GuillaumeGomez** [comment]
Here it is:

screen shot 2018-05-30 at 23 06 24

**Comment by QuietMisdreavus** [comment]
Thanks!

@bors r+

**Comment by QuietMisdreavus** [comment]
It looks like bors had a hiccup and marked a bunch of PRs with "merge conflict" even though no such conflict existed? I'm going to poke this again.

@bors r+

**Comment by QuietMisdreavus** [comment]
@bors retry

(reasoning up-thread)

**Pull request merged**
