### PR TITLE
Add long explanation e0521

### PR DESCRIPTION
**Pull request by jesusprubio**
Helps with #61137

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Nice, thanks!

@bors: r+ rollup

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/81652#issuecomment-771328339

@bors r-

**Comment by jesusprubio** [comment]
@GuillaumeGomez, could you call @bors for me again please? :)

**Comment by GuillaumeGomez** [comment]
Seems still good, let's try again but not in a rollup this time.

@bors: r+ rollup-

**Pull request merged**
