### PR TITLE
Speed up rustdoc run a bit

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
```
[00:01:39]     Updating crates.io index
[00:01:54] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:01:54] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:54] Build completed unsuccessfully in 0:00:40
[00:01:54] Makefile:69: recipe for target 'prepare' failed
[00:01:54] make: *** [prepare] Error 1
[00:01:55] Command failed.
```

Looks like you forgot to push the lock file changes?

**Comment by GuillaumeGomez** [comment]
This is very likely...

**Comment by Centril** [comment]
Ping from triage, @QuietMisdreavus :)

**Review by QuietMisdreavus — APPROVED** [review]

**Pull request merged**
