### PR TITLE
Add -Zcross-crate-inline-threshold=yes

### PR DESCRIPTION
**Pull request by saethlin**
@thomcc says this would be useful for

>  seeing if it makes a difference in some code if i do it when building the sysroot, since -Zbuild-std + lto helps more than it seems like it should

And I've changed the possible values as a reference to @Manishearth saying

> LLVM's inlining heuristic is "yes".

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
I think this makes sense, and it's a change to a nightly flag so I don't think it needs any team sign-off.

**Comment by davidtwco** [comment]
Are there any tests for `-Zcross-crate-inline-threshold` which you could add to?

**Comment by saethlin** [comment]
No, and there ought to be. I'll add that.

**Comment by nikic** [comment]
I don't really understand why this would be a useful option, but the option name/value combination doesn't make sense to me. This looks to me like it enables the cross crate inline threshold, not that it sets it to infinity. Should this be s/yes/always?

**Comment by saethlin** [comment]
> I don't really understand why this would be a useful option

The point is to compare with a build where enabling LTO produces a significant perf improvement. If this flag produces a similar improvement, then it is possible to get that improvement by applying `#[inline]`. If this flag does not, then there is something else about LTO which is responsible.

> This looks to me like it enables the cross crate inline threshold, not that it sets it to infinity

Well currently, it isn't the same as setting the threshold to infinity, because no matter how a numeric value you pass, non-leaf functions will never be made cross-crate-inlinable. Cross-crate-inlining does not have a proper cost model yet because so far all my attempts to develop one have resulted in significant regressions in incremental build times.

**Pull request merged**
