### PR TITLE
Make `WHERE_CLAUSES_OBJECT_SAFETY` a regular object safety violation

### PR DESCRIPTION
**Pull request by compiler-errors**
#### The issue

In #50781, we have known about unsound `where` clauses in function arguments:

```rust
trait Impossible {}

trait Foo {
    fn impossible(&self)
    where
        Self: Impossible;
}

impl Foo for &() {
    fn impossible(&self)
    where
        Self: Impossible,
    {}
}

// `where` clause satisfied for the object, meaning that the function now *looks* callable.
impl Impossible for dyn Foo {}

fn main() {
    let x: &dyn Foo = &&();
    x.impossible();
}
```

... which currently segfaults at runtime because we try to call a method in the vtable that doesn't exist. :(

#### What did u change

This PR removes the `WHERE_CLAUSES_OBJECT_SAFETY` lint and instead makes it a regular object safety violation. I choose to make this into a hard error immediately rather than a `deny` because of the time that has passed since this lint was authored, and the single (1) regression (see below).

That means that it's OK to mention `where Self: Trait` where clauses in your trait, but making such a trait into a `dyn Trait` object will report an object safety violation just like `where Self: Sized`, etc.

```rust
trait Impossible {}

trait Foo {
    fn impossible(&self)
    where
        Self: Impossible; // <~ This definition is valid, just not object-safe.
}

impl Foo for &() {
    fn impossible(&self)
    where
        Self: Impossible,
    {}
}

fn main() {
    let x: &dyn Foo = &&(); // <~ THIS is where we emit an error.
}
```

#### Regressions

From a recent crater run, there's only one crate that relies on this behavior: https://github.com/rust-lang/rust/pull/124305#issuecomment-2122381740. The crate looks unmaintained and there seems to be no dependents.

#### Further

We may later choose to relax this (e.g. when the where clause is implied by the supertraits of the trait or something), but this is not something I propose to do in this FCP.

For example, given:

```
trait Tr {
  fn f(&self) where Self: Blanket;
}

impl<T: ?Sized> Blanket for T {}
```

Proving that some placeholder `S` implements `S: Blanket` would be sufficient to prove that the same (blanket) impl applies for both `Concerete: Blanket` and `dyn Trait: Blanket`.

Repeating here that I don't think we need to implement this behavior right now.

----

r? lcnr

### CODE REVIEW

**Comment by compiler-errors** [comment]
@rfcbot fcp merge

**Comment by compiler-errors** [comment]
Sorry y'all lol

@rfcbot cancel

**Comment by compiler-errors** [comment]
@rfcbot fcp merge

**Review by oli-obk — APPROVED** [review]
r=me after rebase

**Comment by matthiaskrgr** [comment]
@bors r-  rollup=iffy

https://github.com/rust-lang/rust/pull/125931

**Comment by compiler-errors** [comment]
I tried blessing the codegen tests and nothing happened

@bors r=oli-obk rollup=never

**Comment by fmease** [comment]
I think `where_clauses_object_safety` should've been registered as removed with `store.register_removed` in `register_builtins`.

**Comment by lcnr** [comment]
yes we should have added it to the removed lints

**Pull request merged**
