### PR TITLE
Slice::swap should be inlineable

### PR DESCRIPTION
**Pull request by dcrewi**

### CODE REVIEW

**Comment by bluss** [comment]
Did you have any indication it was not inlinable? It's a generic method, so it has to be inlinable already.

**Comment by dcrewi** [comment]
I'm under the impression that without the inline attribute, llvm will not consider inlining a function cross-crate.

**Comment by alexcrichton** [comment]
Ah yes @bluss I forgot to note that! @dcrewi all generics are instantiated downstream with concrete types and are hence available for inlining. Functions which are otherwise not able to cross crates (e.g. those that have no generics) are not candidates for inlining and hence require the `#[inline]` tag. In this case the function is generic (because the trait is generic) so it was already a candidate for inlining.

**Pull request merged**
