### PR TITLE
Use `drop_in_place` in `array::IntoIter::drop`

### PR DESCRIPTION
**Pull request by SimonSapin**
This skips the loop when the element type is known not to have drop glue, even in debug mode.

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage.
@Kimundi can you please review this PR?
@SimonSapin 
Thank you!

**Comment by JohnCSimon** [comment]
Pinging again from triage.
@Kimundi can you please review this PR?
@SimonSapin
Thank you!

**Comment by joelpalmer** [comment]
Ping from Triage: @Amanieu @JohnTitor @SimonSapin any updates?

**Comment by JohnTitor** [comment]
tidy check is failed due to undocumented unsafe block

**Comment by SimonSapin** [comment]
Rebased and added `SAFETY` comments so that tidy passes.

**Comment by SimonSapin** [comment]
Let’s maybe not keep blocking this. One of the new safety comments is copied from an existing similar method, the other seems straight-forward enough that I’ll take the liberty of carrying the review of the comment-less diff:

@bors r=Amanieu

**Pull request merged**
