### PR TITLE
collector: always consider all monomorphic functions to be 'mentioned'

### LINKED ISSUE #122814: Which functions are "reachable", and therefore subject to monomorphization-time checks, is optimization-dependent
This is a variant of https://github.com/rust-lang/rust/issues/107503, but with a different underlying cause and hence not fixed by https://github.com/rust-lang/rust/pull/122568. @tmiasko provided this magnificent example (comments by me, they may be wrong):
```rust
//! This used to fail in optimized builds but pass in unoptimized builds. The reason is that in
//! optimized builds, `f` gets marked as cross-crate-inlineable, so the functions it calls become
//! reachable, and therefore `g` becomes a collection root. But in unoptimized builds, `g` is no
//! root, and the call to `g` disappears in an early `SimplifyCfg` before "mentioned items" are
//! gathered, so we never reach `g`.
#![crate_type = "lib"]

struct Fail<T>(T);
impl<T> Fail<T> {
    const C: () = panic!(); //~ERROR: evaluation of `Fail::<i32>::C` failed
}

pub fn f() {
    loop {}; g()
}

#[inline(never)]
fn g() {
    h::<i32>()
}

// Make sure we only use the faulty const in a generic function, or
// else it gets evaluated by some MIR pass.
fn h<T>() {
    Fail::<T>::C;
}
```

The symptom here is the opposite of https://github.com/rust-lang/rust/issues/107503: `cargo build` succeeds but `cargo build --release` fails. This is because *more* things become roots in optimized builds and therefore we evaluate more things.

I can think of two ways of fixing this:
- Making the set of collection roots opt-level-independent. This is what I tried in https://github.com/rust-lang/rust/commit/a303df006a5be15f799fdb9f987ac083f8de191d. It caused a ~2% slowdown on some benchmarks; it's hard to get the full picture as we only benchmarked it together with the rest of https://github.com/rust-lang/rust/pull/122568. There may be ways to reduce this cost.
- Make sure `g` is considered "mentioned" in `f`. This requires either collecting (some of) the mentioned items very early during MIR building, or making `SimplifyCfg` preserved unreachable blocks. This likely has lower perf impact, but it means we'd still miss const-eval failures reachable from dead private monomorphic functions.

### PR DESCRIPTION
**Pull request by RalfJung**
This would fix https://github.com/rust-lang/rust/issues/122814. But it's probably not going to be cheap...

Ideally we'd avoid building the optimized MIR for these new roots, and only request `mir_drops_elaborated_and_const_checked` -- but that MIR is often getting stolen so I don't see a way to do that. ([Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Use.20unoptimized.20MIR.20for.20.22mentioned.22.20items.20collection))

r? @oli-obk @tmiasko

### CODE REVIEW

**Comment by RalfJung** [comment]
It's again mostly `incr` builds which are affected -- I guess that makes sense as then the collector represents a larger fraction of the total rustc execution time than for full builds.

This seems to affect different benchmarks than https://github.com/rust-lang/rust/pull/122568.

Would be interesting to figure out where the extra time is spent; this time it can't be metadata (de)serialization. @saethlin I think you had a working setup for getting cachegrind diffs?

**Comment by RalfJung** [comment]
Oli made a suggestion for how to about the MIR opts [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Use.20unoptimized.20MIR.20for.20.22mentioned.22.20items.20collection/near/428279960); that should probably be the next step. I have to put this on hold for now though.

**Comment by Kobzol** [comment]
FWIW, it you click on a row with a specific benchmark result, it will show you a command that you can copy paste to get a cachegrind diff.

**Comment by RalfJung** [comment]
Yeah and last time I tried that Debian's valgrind was too old and that command did not work. Maybe I should check if it has been updated in the mean time.

**Comment by saethlin** [comment]
Here's the top of the most-regressed primary benchmark (unicode-normalization debug incr-unchanged)
```
35,048,416  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir          file:function
--------------------------------------------------------------------------------
-3,749,950  ???:<hashbrown::raw::RawTable<(rustc_ast::node_id::NodeId, rustc_hir::hir_id::ItemLocalId)>>::reserve_rehash::<hashbrown::map::make_hasher<rustc_ast::node_id::NodeId, rustc_hir::hir_id::ItemLocalId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>::{closure#0}>
 3,749,950  ???:<hashbrown::raw::RawTable<(rustc_span::def_id::LocalDefId, rustc_hir::hir_id::ItemLocalId)>>::reserve_rehash::<hashbrown::map::make_hasher<rustc_span::def_id::LocalDefId, rustc_hir::hir_id::ItemLocalId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>::{closure#0}>
 2,790,508  ???:<rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
 2,640,064  ???:<rustc_metadata::rmeta::decoder::DecodeContext as rustc_span::SpanDecoder>::decode_span
 1,781,794  <all-jemalloc-files>:<all-jemalloc-functions>
 1,627,701  ???:<rustc_middle::mir::BasicBlockData as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
 1,575,493  ???:<rustc_middle::mir::interpret::AllocId as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable::{closure#0}
-1,515,559  ???:<rustc_middle::mir::interpret::AllocId as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
 1,248,878  ???:<rustc_span::caching_source_map_view::CachingSourceMapView>::span_data_to_lines_and_cols
 1,148,391  ???:<rustc_middle::mir::Body as rustc_data_structures::stable_hasher::HashStable<rustc_query_system::ich::hcx::StableHashingContext>>::hash_stable
 1,129,590  ???:<rustc_data_structures::sip128::SipHasher128>::short_write_process_buffer::<8>
   971,146  ???:<rustc_middle::ty::context::CtxtInterners>::intern_ty
   920,975  ???:<rustc_middle::mir::Body as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   848,301  ???:<rustc_middle::ty::Ty as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   846,228  ???:rustc_incremental::persist::load::setup_dep_graph
   807,165  ???:rustc_monomorphize::collector::collect_items_rec
   526,864  ???:<rustc_data_structures::sip128::SipHasher128>::finish128
   465,911  ???:<rustc_middle::query::on_disk_cache::CacheDecoder as rustc_span::SpanDecoder>::decode_def_id
   425,077  ???:rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
   380,687  ???:rustc_data_structures::unord::hash_iter_order_independent::<rustc_query_system::ich::hcx::StableHashingContext, (&rustc_span::def_id::DefId, &rustc_span::def_id::DefId), std::collections::hash::map::Iter<rustc_span::def_id::DefId, rustc_span::def_id::DefId>>
   360,997  ???:<rustc_middle::ty::generic_args::ArgFolder as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_ty
   342,871  /usr/src/debug/glibc/glibc/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms
   333,648  ???:rustc_monomorphize::collector::visit_instance_use
   ```
I looked at a few other of the top primary regressions and they all look almost exactly the same in cachegrind

**Comment by RalfJung** [comment]
Thanks!

Hm... Mir opts don't seem to show up there as far as I can tell. Strange.

**Comment by saethlin** [comment]
If MIR opts were significant, you'd probably see them in this view: https://perf.rust-lang.org/detailed-query.html?commit=d0df954d8bedc6b4baa80485170b02fda0e0042f&benchmark=unicode-normalization-0.1.19-debug&scenario=incr-unchanged&base_commit=cdb683f6e4b0774b85c60eebe12af87f29d8ee4d&sort_idx=-11 they're all called `mir_pass_something`.

**Comment by RalfJung** [comment]
I do see `metadata_decode_entry_optimized_mir` there. So... all the extra time is spent *loading* the MIR...?

**Comment by saethlin** [comment]
Yup, that would be my first guess.

**Comment by RalfJung** [comment]
In that case maybe a dedicated query for "mentioned and required items" would indeed help as it would not have to load the entire MIR for that.

**Comment by RalfJung** [comment]
> In that case maybe a dedicated query for "mentioned and required items" would indeed help as it would not have to load the entire MIR for that. (This was [proposed by Oli](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Use.20unoptimized.20MIR.20for.20.22mentioned.22.20items.20collection/near/428279960).)

 I have zero knowledge about the crate metadata handling and I'm unlikely to have the time to learn about it any time soon -- so if anyone wants to pick this up, please feel free to do so. Meanwhile I will close this PR as I'm not currently working on this.

**Pull request closed without merging**
