### PR TITLE
Remove allocation from width of character function.

### LINKED ISSUE #48153: Compiler slowdown on lage module in nightly
I've noticed that the nightly compilers lately have taken quite a long time to compile [efm32gg11b82](https://crates.io/crates/efm32gg11b820). The crate is a large amount of code generated by [svd2rust](https://crates.io/crates/svd2rust). I've narrowed down the difference in build time to a nightly release. The results below are from debug builds, but I've seen similar numbers for release builds.

rustc 1.25.0-nightly (bacb5c58d 2018-01-26):

```
$ CARGO_INCREMENTAL=0 cargo build
   Compiling aligned v0.1.1
   Compiling bare-metal v0.1.1
   Compiling cortex-m v0.4.3
   Compiling vcell v0.1.0
   Compiling untagged-option v0.1.1
   Compiling volatile-register v0.2.0
   Compiling efm32gg11b820 v0.2.0 (file:///home/alex/efm32gg11b820)
    Finished dev [unoptimized + debuginfo] target(s) in 233.85 secs
```

rustc 1.25.0-nightly (7d6e5b9da 2018-01-27):

```
$ CARGO_INCREMENTAL=0 cargo build
   Compiling cortex-m v0.4.3
   Compiling aligned v0.1.1
   Compiling bare-metal v0.1.1
   Compiling vcell v0.1.0
   Compiling untagged-option v0.1.1
   Compiling volatile-register v0.2.0
   Compiling efm32gg11b820 v0.2.0 (file:///home/alex/efm32gg11b820)
    Finished dev [unoptimized + debuginfo] target(s) in 2358.13 secs
```

I'm not really sure how to profile this further, so I'll take any suggestion you have.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Locally this seems to eliminate the problem or at least resolve most of the
issue.

Fixes #48153.

r? @estebank

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I've nominated this for beta backport, as it's a small patch that fixes a major regression (40 minute long compile times vs 150 seconds), and if we cut beta before this lands (likely) this is good to get in.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/release Would anyone be interested in making a beta backport of this? Process is described here: https://forge.rust-lang.org/beta-backporting.html

**Comment by Aaronepower** [comment]
@Mark-Simulacrum I'll take this one if it's no problem.

**Pull request merged**
