### PR TITLE
Fix data-layout field in x86_64-unknown-linux-gnu.json test file

### PR DESCRIPTION
**Pull request by phil-opp**
The current data-layout causes the following error:

> rustc: /checkout/src/llvm/lib/CodeGen/MachineFunction.cpp:151: void llvm::MachineFunction::init(): Assertion `Target.isCompatibleDataLayout(getDataLayout()) && "Can't create a MachineFunction using a Module with a " "Target-incompatible DataLayout attached\n"' failed.

The new value was generated according to [this comment by @japaric](https://github.com/rust-lang/rust/issues/31367#issuecomment-213595571).

### CODE REVIEW

**Comment by carols10cents** [comment]
r? @japaric 

Thanks for the PR! We’ll periodically check in on it to make sure that @japaric or someone else from the team reviews it soon.

**Comment by japaric** [comment]
The change LGTM but the data-layout changed quite long time ago; why hasn't this break a test?

It seems to me that this file is not being used at all. When `rustc` sees `--target $T` it will use the built-in definition of `$T` if there is one; otherwise it will look for a specification file named `$T.json`. So I think that the test that is *meant* to use this file is actually using the built-in target definition. I think it would be better to rename the file to not match the name of a built-in target and then adjust the test accordingly.

Could you look into it @phil-opp? (TBH, I don't even know which test is supposed to be using this file.)

**Comment by phil-opp** [comment]
> the data-layout changed quite long time ago; why hasn't this break a test?

Yeah, that wondered me too. I think that the file should be used by the `target-specs` test (see the [Makefile](https://github.com/rust-lang/rust/blob/master/src/test/run-make/target-specs/Makefile#L8)).

I added a commit that renames the file to `my-x86_64-unknown-linux-gnu-platform.json` (to match the other test targets) and adjust the target in the Makefile.

(I couldn't test this locally, since I only have my laptop with a small SSD at the moment.)

**Comment by japaric** [comment]
Thanks, @phil-opp.

Travis seems to be happy so let's land this.

@bors r+ rollup

**Pull request merged**
