### PR TITLE
Add inspection and setter methods to proc_macro::Diagnostic.

### PR DESCRIPTION
**Pull request by SergioBenitez**
A few useful methods for `proc_macro::Diagnostic`.

r? @alexcrichton

### CODE REVIEW

**Comment by SergioBenitez** [comment]
This is the build failure:

```rust
[00:23:33] error: This node does not have a stability attribute
[00:23:33]    --> libproc_macro/diagnostic.rs:130:31
[00:23:33]     |
[00:23:33] 130 |     pub fn children(&self) -> impl Iterator<Item = &Diagnostic> {
[00:23:33]     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

...which doesn't make sense to me. The method is labeled `unstable` already:

```rust
#[unstable(feature = "proc_macro_diagnostic", issue = "38356")]
pub fn children(&self) -> impl Iterator<Item = &Diagnostic> { .. }
```

The error is pointing at the return type. Is there some extra labeling that needs to happen, or is this a bug elsewhere?

**Comment by alexcrichton** [comment]
Looks good to me! That may be a bug in the stability lint perhaps? It hasn't been touched in a long long time :(

**Comment by eddyb** [comment]
cc @oli-obk looks like the stability marking pass is not recursing into `existential type` nodes?

**Comment by oli-obk** [comment]
Should be enough to add an arm to

https://github.com/rust-lang/rust/blob/a2af8667b1a5166137510aeb2aaad9945f81db6d/src/librustc/middle/stability.rs#L356

for `ItemExistential(ExistTy { parent_fn_id: Some(_) })` which also skips the `check_missing_stability` call

**Comment by eddyb** [comment]
@oli-obk Isn't the problem here that *sometimes* it doesn't get marked?
This appears to be a problem *specifically* with `-> impl Trait` in inherent impl methods.

**Comment by oli-obk** [comment]
that's weird. Maybe lowering places them inside the impl block instead of the surrounding module?

**Comment by Aaronepower** [comment]
Triage: Marking this as blocked on a fix to the stability marking pass. @oli-obk Is there a PR/issue about this problem? If there's not can you open one?

**Comment by SergioBenitez** [comment]
@oli-obk Pinging to see if we can move this forward. Worst case, I'll just stop using `impl Trait` here.

**Comment by oli-obk** [comment]
Probably the same issue as https://github.com/rust-lang/rust/issues/54045 where the same fix applies

**Comment by SergioBenitez** [comment]
@alexcrichton How does this look?

**Comment by alexcrichton** [comment]
@bors: r+

Looks good to me!

**Comment by SergioBenitez** [comment]
Failure looks unrelated. Rerun?

**Pull request merged**
