### PR TITLE
Fix overflow in precise_time_ns() on Windows,

### LINKED ISSUE #17845: `precise_time_ns` can overflow on Windows
The [last line](https://github.com/rust-lang/rust/blob/ff2616e847ddf913e007d715732b5669b0f22672/src/libtime/lib.rs#L188) of `precise_time_ns` uses a 64 bit multiplication that will overflow frequently.

Using floats would be the easy way out, but it would reduce precision to 53 bits.

### PR DESCRIPTION
**Pull request by vadimcn**
which starts happening after ~2 hours of machine uptime.
Closes #17845

### CODE REVIEW

**Comment by alexcrichton** [comment]
I feel that this may not be the time to whip out `asm!`, this isn't really performance-related, right? Also, the non-x86_64 code should work on x86_64 as well?

**Comment by pnkfelix** [comment]
@vadimcn you might consider taking the approach of splitting the u64 into the high- and low- order 32-bit parts, as I show here: https://github.com/pnkfelix/rust/commit/b6d2ccb91f037b640e7962b9b2ece72439af7629

Of course the approach I show there is slower than yours, since it uses two divisions (and a modulo, but that should be folded into one of the divisions if the target architecture supports doing them together) and two multiples, in place of your one division and one multiply.  But it preserves the low order bits without needing `asm`.  (we can put in asm versions later if warranted, but I agree with @alexcrichton that we can avoid it for now.)

**Comment by pnkfelix** [comment]
@vadimcn wait, sorry, @huonw has pointed out that I may have misread your code.

**Comment by vadimcn** [comment]
@pnkfelix: But it doesn't lose any bits!  Had I wanted that, I'd have simply written `value/denom*numer`!

Now, it's true that my code will start losing low bits when (numer * denom) overflows, but that doesn't happen until we get into 20 GHz territory (10 GHz if using signed integers).  These days multiprocessor machines don't seem to use RDTSC for perf counters, so the actual frequencies we are likely to see will be in MHz, not GHz.

BTW, your version seems to lose low bits too, and sooner than mine.  I have not yet figured out why.  Check this out:  http://is.gd/uX6JH4

**Comment by pnkfelix** [comment]
@vadimcn *weird*.  I did not expect that.  Anyway, I no longer object to your non-asm version.

(I still agree with @alexcrichton that we need not include the asm version right now.)

**Comment by vadimcn** [comment]
The asm version uses true 128-bit operations, so it doesn't lose low bits at all, which is nice, IMO.

**Comment by alexcrichton** [comment]
True, but using unstable language features generally makes updating said features much tougher, for example. I'm also generally pretty wary of usage of `asm!` as it's tough to verify and I'm never quite sure if it's correct. The 32-bit version should suffice for now and we can always add back the `asm!` version at a later date.

**Comment by pnkfelix** [comment]
@vadimcn by the way, I'm inclined to agree with your assessment on #17845 that this overflow seems like it could also hit the unix platforms as well.  (I guess there's something special about windows that I only hit it *there* in the overflow work.)

We should definitely consider moving this portable routine that you have written out of the windows-specific code and into one of the core or std num modules, even if only for use within std alone...

**Comment by vadimcn** [comment]
@pnkfelix: I'd like to hear from Mac people that this is indeed a problem, before attempting to fix it.
From what I could find on the Internet, it appears that in recent OSX versions, 1 tick == 1 ns, so the ratio is 1/1 and thus this computation will never overflow.

**Comment by vadimcn** [comment]
@alexcrichton: Ok, I dropped the asm version.

**Pull request merged**
