### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #98368 (Make `std::os::fd` public.)
 - #99583 (Add additional methods to the Demand type)
 - #100121 (Try normalizing types without RevealAll in ParamEnv in MIR validation)
 - #100200 (Change implementation of `-Z gcc-ld` and `lld-wrapper` again)
 - #100552 (rustc_target: Add a compatibility layer to separate internal and user-facing linker flavors)
 - #100574 (Add warning against unexpected --cfg with --check-cfg)
 - #101245 (Remove unneeded where whitespace)
 - #101251 (Fix  bad target name in Walkthrough)
 - #101254 (rustdoc: remove unused `.docblock .impl-items` CSS)
 - #101256 (Fixes/adjustments to Fuchsia doc walkthrough)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=98368,99583,100121,100200,100552,100574,101245,101251,101254,101256)

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@bors r- 
conflicts

**Comment by bjorn3** [comment]
The bors queue still lists this PR as open.

**Comment by bjorn3** [comment]
That fixed it. I will try that next time I see something like this.

**Pull request closed without merging**
