### PR TITLE
Remove outline when details have focus

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @rust-lang/docs 

(the green outline annoyed me a bit)

### CODE REVIEW

**Comment by frewsxcv** [comment]
can you take a screenshot of the outline you're referring to?

**Comment by GuillaumeGomez** [comment]
This one:

screenshot from 2017-08-18 18-07-54

**Comment by QuietMisdreavus** [comment]
Isn't that just the "active link" outline? I don't see any change in firefox when i add this style manually.

**Comment by GuillaumeGomez** [comment]
I only tested on chrome. Will check on firefox as well.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by QuietMisdreavus** [comment]
Aha, now that makes a change. I can get behind this one.

@bors r+ rollup

**Pull request merged**
