### PR TITLE
Bump minimal supported LLVM version to 9

### PR DESCRIPTION
**Pull request by DevJPM**
This bumps the minimal tested llvm version to 9.
This should enable supporting newer LLVM features (and CPU extensions).

This was motived by #78361 having to drop features because of LLVM 8 not supporting certain CPU extensions yet.
This was declared relatively uncontroversial on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Min.20Supported.20LLVM.20Upgrade.20Process.3F/near/215957859).

Paging @eddyb because there was a comment in the [dockerfile](https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/x86_64-gnu-llvm-8/Dockerfile#L42) describing a hack (which I don't quite understand) which was also blocked by not having LLVM 9.

### CODE REVIEW

**Comment by nikic** [comment]
This builder always tests the lowest supported version of LLVM -- if you want to bump the tested version, you actually need to drop support for LLVM 8.

In particular you need to adjust https://github.com/rust-lang/rust/blob/b2d115f6db5172c961dfeb50de15f35784dbc7c9/src/bootstrap/native.rs#L334, and then grep for LLVM_VERSION_GE, LLVM_VERSION_LT, get_major_version, min-llvm-version to find places where compatibility code can be dropped.

**Comment by DevJPM** [comment]
@nikic  Thank you very much for these suggestions. They have been exactly what I've been looking for - but failed to find amidst the size of Rust.

The latest commit does indeed grep for these constants and drops compatibility code whereever possible and sensible.

**Comment by pietroalbini** [comment]
The CI changes look good! r? @nikic for the rest.

**Review by cuviper — APPROVED** [review]

**Comment by DevJPM** [comment]
Sorry to anyone who might have been notified by my failed attempt at fixing the merge conflict indicated by GitHub

**Comment by DevJPM** [comment]
The update was due to a merge conflict in attribute.rs where my changes forced a re-format to one-line and another change removed one intermediate value

**Comment by DevJPM** [comment]
So, it appears that after the approval of this PR a merge conflict got merged into master - which I fixed - but now appears that bors has no intention of merging this PR anymore without another approval? (Hoping that I read [this page](https://bors.rust-lang.org/queue/rust) correctly)

So, can I ask for an approval of the conflict-free PR? @nikic ? (Hoping that I understand the workflows around here correctly)

**Comment by nikic** [comment]
You got that right.

@bors r+

**Pull request merged**
