### PR TITLE
Forbid lifetime bounds in nested opaque types in binders

### PR DESCRIPTION
**Pull request by oli-obk**
avoids #96194

Not closing the issue until we have this behind a feature gate and with a corresponding tracking issue.

Since this change is supposed to get backported to beta, I don't want to add a gate and more logic in this PR. Instead, it will happen on a follow up PR solely on nightly.

### CODE REVIEW

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-05-12/near/282111361)

(pending a crater run)

@rustbot label +beta-accepted

**Comment by oli-obk** [comment]
@craterbot check

**Comment by cjgillot** [comment]
@oli-obk I don't understand your comment about anonymous lifetimes.

> I think it's fine to only do this for named lifetimes, as all others are forbidden anyway (`'_` and just leaving them out is already triggering other errors).

To be on the safe side, I'd rather have named and anonymous lifetimes treated the same way.  The "other errors" are feature gates for impl-trait in `fn` and `impl Fn()`, aren't they?

**Comment by compiler-errors** [comment]
r=me if you're still in search for a reviewer, I am satisfied with the most recent changes after the second commit

**Comment by Mark-Simulacrum** [comment]
This doesn't cherry pick cleanly onto beta, so I'm holding off on a backport until someone can prepare that -- the diff doesn't look trivial to me, though I haven't looked super closely. If necessary I'll probably devote a few hours on the weekend or Monday to push it through.

**Comment by compiler-errors** [comment]
NLL tests need to be blessed, but @pnkfelix has pointed out an interesting side effect of this PR, being: 

`impl for<'a> Foo<'a, Assoc = impl for<'b> Qux<'b>>` fails under this PR, which is possibly not correct. 

Current nightly accepts the following code, for example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f25115b4ae04c819e56781bf952b766f

@bors r- until that issue is settled

**Comment by oli-obk** [comment]
Closing as @cjgillot wrote an actual fix instead of overzealous patch that this PR was

**Comment by Mark-Simulacrum** [comment]
De-accepting from beta backport.

**Pull request closed without merging**
