### PR TITLE
Fix "an" usage

### PR DESCRIPTION
**Pull request by arqunis**
Since the pr i reviewed on got merged way before the author had a chance to quickly change it, i just did it myself. (Or well, someone else asked me to, if you want me to be honest)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Thanks!

@bors r+ rollup

**Comment by frewsxcv** [comment]
@bors r-

Looks like this hit a test failure: https://travis-ci.org/rust-lang/rust/jobs/229448947 (view the raw log an scroll near the bottom)

We have 'ui tests' that test the error/warning output for rust code. For example, for:

https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-41679.rs

we have:

https://github.com/rust-lang/rust/blob/master/src/test/ui/did_you_mean/issue-41679.stderr

You'll need to update that '.stderr' file with your 'an' changes

**Comment by TimNN** [comment]
@bors retry

Since this will fail anyway, prioritize another PR.

**Comment by acdenisSK** [comment]
Forgot that you have the change these things as well, but thanks for reminding me.

**Pull request merged**
