### PR TITLE
Support 16-bit pointers in MIR

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by shepmaster** [comment]
This seems a bit suspicious to me as my local AVR work is based on 4b240fe96a8b8fcaa412624c398547dbc447a81e, which AFAICT shouldn't have MIR enabled by default. Nonetheless, I was getting assertions in this code. Anything to be worried about here?

**Comment by Aatch** [comment]
@shepmaster we always build the MIR, it's just not used for code generation by default yet, so it's not surprising that you got an assertion.

**Comment by shepmaster** [comment]
In relation to #33460.

**Comment by shepmaster** [comment]
> we always build the MIR

@Aatch ah, good to know. Do you think that I'm likely to have covered most of the MIR codebase then, purely by accident?

**Comment by Aatch** [comment]
@shepmaster grepping for `sess.target.int_type` in the `librustc_mir` and `librustc_trans/mir` folders would probably point to likely locations.

**Comment by shepmaster** [comment]
Good call. I've done that and didn't find any new, obvious holes. However, I realized I *could* enable MIR and see what happens. Let me do that before this gets merged.

**Comment by shepmaster** [comment]
@Aatch I've compiled libcore to LLVM-IR with `-Z orbit` and found this additional aspect. It touches a bit more code, but I think the readability gained from the new function is a win!

**Comment by Aatch** [comment]
Theres a couple tidy errors, but looks good to me otherwise.

**Comment by shepmaster** [comment]
@Aatch tidy issues addressed.

**Pull request merged**
