### PR TITLE
Update rustc-dev-guide

### PR DESCRIPTION
**Pull request by mark-i-m**
This should finally fix toolstate

r? @JohnTitor

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hm, overall looks good but GitHub returns 429. IIRC I've seen this failure on rustc-dev-guide side also. Can we avoid this to tweak link checker config or something?

**Comment by JohnTitor** [comment]
That's a good idea! r=me once it's updated.

**Comment by mark-i-m** [comment]
It looks like there are some actually broken links atm, so let me fix those and update this pr too.

**Comment by mark-i-m** [comment]
https://github.com/rust-lang/rustc-dev-guide/pull/672

**Comment by mark-i-m** [comment]
Should hopefully pass now. Let's wait for CI.

**Comment by mark-i-m** [comment]
@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

@JohnTitor ready :)

**Comment by JohnTitor** [comment]
Thanks! @bors r+
I think we now filter some (spurious) link errors and I wonder we can include this in rollup. I'd like to up to rollupers whether including or not.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/70955#issuecomment-611615611, @bors r-

**Comment by mark-i-m** [comment]
This is still passing for me locally? Perhaps it was a spurious failure we didn't expect? I looked through the log, but it's long and I guess I missed whatever error caused the failure.

**Comment by Mark-Simulacrum** [comment]
```
020-04-09T15:18:11.8280907Z error: The server responded with 429 Too Many Requests for "https://github.com/1wilkens/thesis-ba"
2020-04-09T15:18:11.8281250Z 
2020-04-09T15:18:11.8281655Z     â”Œâ”€â”€ appendix/bibliography.md:64:3 â”€â”€â”€
2020-04-09T15:18:11.8282041Z     â”‚
2020-04-09T15:18:11.8282811Z  64 â”‚ * [Evaluation of performance and productivity metrics of potential programming languages in the HPC environment](https://github.com/1wilkens/thesis-ba).
2020-04-09T15:18:11.8284083Z     â”‚   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Server responded with 429 Too Many Requests
```

Looks spurious to me, though I feel like maybe we shouldn't be running linkcheck quite like this in CI... I have no better suggestions necessarily though, just feeling a bit like we'll likely hit errors like this frequently?

@bors r=JohnTitor

**Comment by JohnTitor** [comment]
At a glance, the _real error_ is

```
error: Unable to retrieve "https://www.cs.cmu.edu/~rwh/pfpl/2nded.pdf": https://www.cs.cmu.edu/~rwh/pfpl/2nded.pdf: connection error: Connection reset by peer (os error 104)
```

only and it's spurious.

The current link check emits all the errors including filtered ones when there's a real error, it isn't ideal..
And the check for GitHub links is meaningless, given from _the too many errors of too many requests_. I think we encounter the rate limit recently, though it doesn't seem to have been limited until now.

**Comment by mark-i-m** [comment]
@JohnTitor It's definitely worth re-evaluating whether it's really doing its job here...

**Comment by JohnTitor** [comment]
> It's definitely worth re-evaluating whether it's really doing its job here...

@mark-i-m You point to emitting the errors, right? Hm, fair enough.

Anyway we should deal with the GH links' failures properly if it continues.

**Pull request merged**
