### PR TITLE
Small perf improvement for fmt

### PR DESCRIPTION
**Pull request by sinkuu**
Added benchmark is based on #10761

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this! The first commit looks good to me (although somewhat requiring wizardry to fully understand, specializing iterators does make for varying performance...)

For the second commit though the code here is **way** out of cache for me (that optimization was added in 2014). Can you explain a bit what's going on there to help understand it?

**Comment by sinkuu** [comment]
For formats without non-default formatting params (like positions not in order (`"{2} {0} {1}"`) or specs (`"{:02X}"`)), `Arguments::new_v1` constructor can be used instead of `Arguments::new_v1_formatted`. `new_v1` constructs `Arguments` with `fmt` field being `None`, which activates [the fast path in `fmt::write`](https://github.com/rust-lang/rust/blob/03acbd71c977cd63ce5f39ba9b6fe9ffd578785a/src/libcore/fmt/mod.rs#L1002-L1009).

This optimization should apply to `"{}"` (which equals to `"{0}"`), but there seems to be a overlook in  #45807 (added `ArgumentImplicitlyIs` variant without updating the [optimization logic](https://github.com/rust-lang/rust/blob/03acbd71c977cd63ce5f39ba9b6fe9ffd578785a/src/libsyntax_ext/format.rs#L476-L496)).

### Example

```rust
fn foo(s: &mut String) {
    // parsed as `ArgumentIs(0)`
    write!(s, "{0}", "foo");
    // parsed as `ArgumentImplicitlyIs(0)`
    write!(s, "{}", "foo");
}
```

Expansion before this PR:

```rust
fn foo(s: &mut String) {
    // parsed as `ArgumentIs(0)`
    s.write_fmt($crate::fmt::Arguments::new_v1(
        &[""],
        &match (&"foo",) {
            (arg0,) => [$crate::fmt::ArgumentV1::new(arg0, $crate::fmt::Display::fmt)],
        },
    ));
    // parsed as `ArgumentImplicitlyIs(0)`
    s.write_fmt($crate::fmt::Arguments::new_v1_formatted(
        &[""],
        &match (&"foo",) {
            (arg0,) => [$crate::fmt::ArgumentV1::new(arg0, $crate::fmt::Display::fmt)],
        },
        &[$crate::fmt::rt::v1::Argument {
            position: $crate::fmt::rt::v1::Position::At(0usize),
            format: $crate::fmt::rt::v1::FormatSpec {
                fill: ' ',
                align: $crate::fmt::rt::v1::Alignment::Unknown,
                flags: 0u32,
                precision: $crate::fmt::rt::v1::Count::Implied,
                width: $crate::fmt::rt::v1::Count::Implied,
            },
        }],
    ));
}
```

Expansion after this PR:
```rust
fn foo(s: &mut String) {
    // parsed as `ArgumentIs(0)`
    s.write_fmt($crate::fmt::Arguments::new_v1(
        &[""],
        &match (&"foo",) {
            (arg0,) => [$crate::fmt::ArgumentV1::new(arg0, $crate::fmt::Display::fmt)],
        },
    ));
    // parsed as `ArgumentImplicitlyIs(0)`
    s.write_fmt($crate::fmt::Arguments::new_v1(
        &[""],
        &match (&"foo",) {
            (arg0,) => [$crate::fmt::ArgumentV1::new(arg0, $crate::fmt::Display::fmt)],
        },
    ));
}
```

**Comment by alexcrichton** [comment]
@bors: r+

Sounds good to me, thanks for explaining!

**Comment by sinkuu** [comment]
This is ready to go. Can you re-"r+"?

**Pull request merged**
