### PR TITLE
Use verbose suggestions for mutability errors

### PR DESCRIPTION
**Pull request by estebank**

### CODE REVIEW

**Review by eholk — APPROVED** [review]
@bors r+

**Comment by Xiretza** [comment]
This could've benefited from a split into two commits: one to update the variable interpolations in `format!()` calls (no functional change), and another to change the actual diagnostic verbosity and update tests. Probably not a big enough issue to still do it now though.

**Comment by compiler-errors** [comment]
For the record, this probably conflicts w #106284

**Pull request merged**
