### PR TITLE
Fix Debug implementations of some of the HashMap and BTreeMap iterator types

### LINKED ISSUE #75297: Better Debug implementations for HashMap and BTreeMap Keys/Values iterator structs
For `HashMap`, we have `ValuesMut` struct as the return type of `HashMap::values_mut` method. Although, it return an iterator over values of the map, its Debug implementation prints both keys and values because of the implementation detail. We should only print values for this struct.

For `BTreeMap`, we also have `ValuesMut`  struct for `BTreeMap::values_mut` method. We directly derive Debug for it. Which also means that Debug prints both keys and values. We should manually implement Debug instead and print only the values.
In addition to that, for BTreeMap, we also need to change IntoKeys and IntoValues structs. This is not an issue on HashMap because it was correctly implemented in the first place. But it wasn't for BTreeMap because we need an `IntoIter::iter` method for this first. So we should implement this and fix this issue for them as well.

This was discovered during #75163 and will be the follow-up of it.

### PR DESCRIPTION
**Pull request by canova**
HashMap's `ValuesMut`, BTreeMaps `ValuesMut`, IntoValues and `IntoKeys` structs were printing both keys and values on their Debug implementations. But they are iterators over either keys or values. Irrelevant values should not be visible. With this PR, they only show relevant fields.
This fixes #75297.

[Here's an example code.](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0c79356ed860e347a0c1a205616f93b7) This prints this on nightly:
```
ValuesMut { inner: IterMut { range: [(1, "hello"), (2, "goodbye")], length: 2 } }
IntoKeys { inner: [(1, "hello"), (2, "goodbye")] }
IntoValues { inner: [(1, "hello"), (2, "goodbye")] }
[(2, "goodbye"), (1, "hello")]
```

After the patch this example prints these instead:
```
["hello", "goodbye"]
["hello", "goodbye"]
[1, 2]
["hello", "goodbye"]
```

I didn't add test cases for them, since I couldn't see any tests for Debug implementations anywhere. But please let me know if I should add it to a specific place.

r? @dtolnay

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
Please also remove the unused bound from the Debug impls of hash_map::IntoKeys and hash_map::IntoValues.

**Comment by dtolnay** [comment]
@rfcbot fcp merge

This PR relaxes the bounds on the following stable Debug impls:

```diff

  impl<K, V> Debug for std::collections::btree_map::ValuesMut<'_, K, V>
  where
-     K: Debug,
      V: Debug;

  impl<K, V> Debug for std::collections::hash_map::ValuesMut<'_, K, V>
  where
-     K: Debug,
      V: Debug;
```

It also does the same for these, though all of these are unstable types:

```diff
  impl<K, V> Debug for std::collections::btree_map::IntoKeys<K, V>
  where
      K: Debug,
-     V: Debug;

  impl<K, V> Debug for std::collections::btree_map::IntoValues<K, V>
  where
-     K: Debug,
      V: Debug;

  impl<K, V> Debug for std::collections::hash_map::IntoKeys<K, V>
  where
      K: Debug,
-     V: Debug;

  impl<K, V> Debug for std::collections::hash_map::IntoValues<K, V>
  where
-     K: Debug,
      V: Debug;
```

This matches the existing signatures of the Debug impls on these stable types:

- `std::collections::btree_map::Keys`
- `std::collections::btree_map::Values`
- `std::collections::hash_map::Keys`
- `std::collections::hash_map::Values`

**Comment by canova** [comment]
Updated the bounds of `IntoKeys` and `IntoValues` of `HashMap`, thanks!

**Review by dtolnay — APPROVED** [review]

**Comment by Dylan-DPC** [comment]
@KodrAus @SimonSapin @withoutboats this is waiting for your vote/concerns on the fcp

**Review by dtolnay — APPROVED** [review]

**Comment by canova** [comment]
Hey @dtolnay, I don't see any failure related to the PR. Do you think I need to do something else before merging this?

**Comment by mati865** [comment]
Spurious network error:
```
curl: (6) Could not resolve host: ci-mirrors.rust-lang.org
```

**Pull request merged**
