### PR TITLE
std: Derive `Default` for `io::Cursor`

### PR DESCRIPTION
**Pull request by tesaguri**
I think this change is quite obvious, so made it insta-stable, but I won't insist on that.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Unfortunately trait impls can't be made unstable, so this can only be landed as an insta-stable impl

**Comment by hellow554** [comment]
So this would make `Cursor::<Vec<u8>>::default()` possible, but is that really something one would do? Don't you rather want to wrap an existing `Vec`, because you want *that* content?

**Comment by tesaguri** [comment]
I'm dealing with a `S: futures::Stream`, so the content is not immediately available and I need a placeholder. I could just write `Cursor::new(/* ... */)` if `S::Item` were a concrete type (`Cursor`), but actually that is a type parameter with a trait bound `S::Item: Default`.

**Comment by erikdesjardins** [comment]
You should be able to use `Cursor::new(Default::default())` anywhere `Cursor::default()` would work.
(not that I think this change shouldn't be made; I'm ambivalent)

**Comment by Amanieu** [comment]
I think this is fine, but just in case anyone has objections...

@rfcbot fcp merge

**Pull request merged**
