### PR TITLE
Categorize WASI as an "OS" rather than as an "environment".

### PR DESCRIPTION
**Pull request by sunfishcode**
This distinction is fairly abstract, but in practice, the main advantage
here is that LLVM's triple code considers WASI to be an OS, so this
makes rustc agree with that.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@sunfishcode FWIW I think the change to `libc`-the-crate will need to land to read either `target_os` or `target_env` so that error can be fixed.

**Comment by sunfishcode** [comment]
@alexcrichton Ok, I now have an updated PR to libc which includes the target_os change: https://github.com/rust-lang/libc/pull/1325

**Comment by sunfishcode** [comment]
rust-lang/libc#1325 landed, and the CI is now green here.

**Comment by alexcrichton** [comment]
Oh I think `libc` still needs to be updated in Cargo.lock here, but to do that a [new release needs to be made](https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md#releasing-your-change-to-cratesio) as well

**Comment by alexcrichton** [comment]
@bors: r+ delegate+

> Update Cargo.lock more. 

Such is the life of a Rust programmer

**Comment by sunfishcode** [comment]
It appears something in the redox build is failing:

```
[01:25:06] error: could not find native static library `c`, perhaps an -L flag is missing?
[01:25:06] 
[01:25:06] error: aborting due to previous error
[01:25:06] 
[01:25:06] [RUSTC-TIMING] libc test:false 0.180
[01:25:06] error: Could not compile `libc`.
```

```
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-redox" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[01:25:08] expected success, got: exit code: 101
```

The libc bump here from 0.2.51 to 0.2.53 does bring in https://github.com/rust-lang/libc/pull/1322, so it's possible that's related.

**Comment by alexcrichton** [comment]
@gnzlbg or @jackpot51 it looks like https://github.com/rust-lang/libc/pull/1322 is causing the failure here presumably because our build isn't configured correctly here for pulling in libc statically. Would y'all be willing to help out with this and/or back out the PR temporarily from libc while we land this?

**Comment by gnzlbg** [comment]
I'm fine with reverting the PR first, and then re-applying it together with a PR to rust-lang/rust that shows that it works. @jackpot51 thoughts?

**Comment by jackpot51** [comment]
I will be submitting a bunch of changes for Redox soon so I wouldn't worry about reverting that PR

**Comment by sunfishcode** [comment]
I've now bumped to 0.2.54, which has the revert of rust-lang/libc#1322.

@bors: r+

**Comment by gnzlbg** [comment]
@jackpot51 Ideally, process-wise, you would submit a PR here that points to your libc branch with the changes required (you might need to silence `tidy` for that), and we'll do a `try`. Once that passes, we can merge the PR in libc upstream and do a release that can be used here.

**Comment by sunfishcode** [comment]
Resolved Cargo.lock conflicts.

@bors: r+

**Comment by sunfishcode** [comment]
Resolved Cargo.lock conflicts.

@bors: r+

**Pull request merged**
