### PR TITLE
doc: examples explain this well

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by steveklabnik** [comment]
What specifically is your objection here?

**Comment by tshepang** [comment]
I found explanations on the examples more easily clear than the summary

**Comment by tshepang** [comment]
Basically, the summary, especially the first one, just slowed me down

**Comment by steveklabnik** [comment]
I don't personally agree with being so terse here, but @alexcrichton owns rustbuild so I'll defer to him.

**Comment by alexcrichton** [comment]
Yeah I also prefer to have a high-level explanation of what's about to happen followed by what happens. Thanks for the PR though!

**Pull request closed without merging**
