### PR TITLE
Update to LLVM 18.1.0 rc 4

### LINKED ISSUE #120819: Miscompliation due to LLVM IR alignment issue (?)
Reproduction:
```rust
#![feature(custom_mir, core_intrinsics)]
#![allow(unused_parens, unused_assignments, overflowing_literals)]
extern crate core;
use core::intrinsics::mir::*;

pub fn enter() {
    fn13(core::hint::black_box((0, [false; 6], [0; 4], 0, 0)));
}

#[custom_mir(dialect = "runtime", phase = "initial")]
fn fn13(mut _6: (i8, [bool; 6], [i64; 4], i128, u8)) {
    mir! {
    let _1: [bool; 6];
    let _14: [u16; 6];
    let _17: *const (i8, [bool; 6], [i64; 4], i128, u8);
    let _19: Adt59;
    let _27: (i8, [bool; 6], [i64; 4], i128, u8);
    let _34: Adt54;
    let _49: ();
    {
    _1 = [false,true,true,true,true,true];
    _19.fld4 = [25264_u16,54664_u16,47032_u16,55453_u16,33511_u16,43043_u16];
    _17 = core::ptr::addr_of!(_6);
    _1 = (*_17).1;
    (*_17).1 = [false,true,true,false,false,true];
    Call(_49 = fn14(_6.1), ReturnTo(bb3), UnwindUnreachable())
    }
    bb3 = {
    (*_17).1 = _1;
    _14 = _19.fld4;
    _17 = core::ptr::addr_of!(_27);
    _34.fld5 = (-1228700359_i32);
    _34.fld1 = _6;
    match _34.fld5 {
    0 => bb3,
    340282366920938463463374607430539511097 => bb12,
    _ => bb18
    }
    }
    bb12 = {
    (*_17) = (_6.0, _6.1, _6.2, _34.fld1.3, _6.4);
    _1 = _27.1;
    Call(_49 = p1(Move(_1)), ReturnTo(bb17), UnwindUnreachable())
    }
    bb17 = {
    Call(_49 = hide(13_usize, 25_usize, 0_usize, 11_usize, 0_usize, 14_usize, Move(_14), 6_usize, Move(_6)), ReturnTo(bb18), UnwindUnreachable())
    }
    bb18 = {
    Return()
    }

    }
}

#[custom_mir(dialect = "runtime", phase = "initial")]
pub fn fn14(mut _16: [bool; 6]) {
    mir! {
    let _20: (i8, [bool; 6], [i64; 4], i128, u8);
    let unit: ();
    let _44: ();
    {
    Call(_44 = core::hint::black_box(unit), ReturnTo(bb17), UnwindUnreachable())
    }
    bb17 = {
    Call(_20.1 = core::hint::black_box(Move(_16)), ReturnTo(bb18), UnwindUnreachable())
    }
    bb18 = {
    Return()
    }

    }
}
pub fn main() {
    enter();
}

#[derive(Debug)]
pub struct Adt54 {
    fld1: (i8, [bool; 6], [i64; 4], i128, u8),
    fld5: i32,
}
#[derive(Debug)]
pub struct Adt59 {
    fld4: [u16; 6],
}

extern "C" {
    fn printf(fmt: *const core::ffi::c_char, ...) -> core::ffi::c_int;
}
#[cfg(not(miri))]
fn print_bool(x: bool) {
    unsafe {
        printf(b"%d\n\0".as_ptr().cast(), x as core::ffi::c_int);
    }
}

#[cfg(miri)]
fn print_bool(x: bool) {
    println!("{}", x as i32);
}

#[inline(never)]
pub fn p1(x: [bool; 6]) {
    for b in x {
        print_bool(b);
    }
}

#[inline(never)]
fn hide(
    f: usize,
    var0: usize,
    val0: usize,
    var1: usize,
    val1: usize,
    var2: usize,
    val2: [u16; 6],
    var3: usize,
    val3: (i8, [bool; 6], [i64; 4], i128, u8),
) {
    core::hint::black_box(val2);
    core::hint::black_box(val3);
}

```

Miri and `-Copt-level <= 2` prints
```
0
0
0
0
0
0
```

But `-Zmir-opt-level=0 -Copt-level=3` prints
```
0
0
1
0
0
0
```

I reported this to LLVM https://github.com/llvm/llvm-project/issues/80911 but was told that the IR generated from MIR has alignment issues.

I really don't know much about LLVM IR but I suspect the problem is
```
%Adt54 = type { { [4 x i64], i128, [6 x i8], i8, i8, [8 x i8] }, i32, [3 x i32] }
[snip]
  %_7 = alloca %Adt54, align 16
[snip]
  %30 = getelementptr inbounds %Adt54, ptr %_7, i32 0, i32 1
  store i32 -1228700359, ptr %30, align 16
[snip]
  %31 = getelementptr inbounds %Adt54, ptr %_7, i32 0, i32 1
  %32 = load i32, ptr %31, align 16, !noundef !5
[snip]
```
The second element of `%Adt54` (`i32`) is not guaranteed to be 16-byte aligned

cc @nikic

### LINKED ISSUE #121180: LLVM codegen errors with `Invalid insertelement operands` in latest nightlies
### Code

https://github.com/ComunidadAylas/PackSquash/tree/8ddb8451b4c4102188e6807233feac6cb4091872

### Meta

`rustc --version --verbose`:
```
1.78.0-nightly (a4472498d 2024-02-15)
```

### Error output

Can be seen in more detail in [GitHub Actions workflow output logs](https://github.com/ComunidadAylas/PackSquash/actions/runs/7924546077/job/21636283153):

image
image

### Notes

This is a pretty low-level LLVM codegen error that does not really fit the bill of an internal `rustc` compile error, as it happens at a layer below `rustc`, but I picked this report template because it seems like a pretty "internal" issue with the Rust compiler nevertheless.

I didn't dive into the precise cause of this error at all, but judging from the error messages, it seems related to `rustc` generating bad LLVM IR for the `rustfft` crate.

On my CI setup, the issue only happens for Linux and macOS x64 targets. Windows x64 and Linux and macOS AArch64 targets build fine.

</p>
</details>

### LINKED ISSUE #121239: Noop-loop is no longer optimized away on Nightly
While working on #120682 I noticed that some optimizations regressed after a rebase. The following should be a reduction.

I tried this code:

[godbolt](https://rust.godbolt.org/z/7Y8MEjjoc)

```rust
#![feature(ptr_sub_ptr)]
#![feature(unchecked_math)]
#![feature(non_null_convenience)]

use std::ptr::NonNull;
use std::ptr;
use std::mem;

struct It<T> {
    start: NonNull<T>,
    end: *const T,
}

struct Out {
    a: u64,
    b: u64,
    c: u64,
    d: u64,
}

pub fn do_it(ptr: *mut [u64; 4], len: usize) -> It<Out> {
    unsafe {
        let start = NonNull::new_unchecked(ptr);
        let mut it = It::<[u64; 4]> {
            start,
            end: start.add(len).as_ptr()
        };
        end_offset_copy(&mut it)
    }
}

fn end_offset_copy(a: &mut It<[u64; 4]>) -> It<Out> {
    unsafe {
        let len = a.end.sub_ptr(a.start.as_ptr());

        let mut i = len;

        let dest_buf: *mut Out = a.start.as_ptr().cast();

        while i > 0 {
            let val = a.end.sub(i).read();
            let dst = dest_buf.add(len).sub(i);

            ptr::write(dst, mem::transmute(val));

            i = i.unchecked_sub(1); 
        }

        let start = NonNull::new_unchecked(dest_buf);

        It::<Out> {
            start,
            end: start.add(len).as_ptr()
        }
    }
}
```

I expected to see this happen (beta):

```asm
example::do_it:
        mov     rax, rdi
        shl     rsi, 5
        lea     rdx, [rsi + rdi]
        ret
```

Instead, this happened (nightly): 

```asm
example::do_it:
        mov     rax, rdi
        movabs  rdx, 576460752303423487
        and     rdx, rsi
        test    rsi, rsi
        je      .LBB0_6
        mov     rcx, rsi
        shl     rcx, 5
        mov     rdi, rdx
        test    sil, 1
        je      .LBB0_3
        lea     rsi, [rax + rcx]
        mov     rdi, rdx
        shl     rdi, 5
        sub     rsi, rdi
        movups  xmm0, xmmword ptr [rsi]
        movups  xmm1, xmmword ptr [rsi + 16]
        movups  xmmword ptr [rax + 16], xmm1
        movups  xmmword ptr [rax], xmm0
        lea     rdi, [rdx - 1]
.LBB0_3:
        cmp     rdx, 1
        je      .LBB0_6
        mov     r8, rdi
        shl     r8, 5
        mov     rsi, rax
        sub     rsi, r8
        add     rsi, 32
        mov     r8, rdx
        shl     r8, 5
.LBB0_5:
        movups  xmm0, xmmword ptr [rsi + rcx - 32]
        movups  xmm1, xmmword ptr [rsi + rcx - 16]
        movups  xmmword ptr [rsi + r8 - 16], xmm1
        movups  xmmword ptr [rsi + r8 - 32], xmm0
        movups  xmm0, xmmword ptr [rsi + rcx]
        movups  xmm1, xmmword ptr [rsi + rcx + 16]
        movups  xmmword ptr [rsi + r8 + 16], xmm1
        movups  xmmword ptr [rsi + r8], xmm0
        add     rsi, 64
        add     rdi, -2
        jne     .LBB0_5
.LBB0_6:
        shl     rdx, 5
        add     rdx, rax
        ret
```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (bccb9bbb4 2024-02-16)
binary: rustc
commit-hash: bccb9bbb418a30aeb332052e721beb6ebc6b1ce7
commit-date: 2024-02-16
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
Compiler returned: 0
```

### LINKED ISSUE #121367: `STATUS_ACCESS_VIOLATION` when cross-compiling for nightly-2024-02-19-aarch64-pc-windows-msvc when compiling `num-traits`
Minimal reproducible example

```rust
fn main() {
    println!("Hello, world!");
}
```

```toml
[package]
name = "min-test"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.18"
```

`cargo build --target aarch64-pc-windows-msvc`

I expected to see this happen: 
cargo builds the example

Instead, this happened: 
```
PS F:\coding\min-test> cargo build --target aarch64-pc-windows-msvc                                             
   Compiling autocfg v1.1.0
   Compiling num-traits v0.2.18                                                                                                                                                                                                                                                                                                                                                                                                    
error: could not compile `num-traits` (lib)                                                                                                                                                                                                                                                                                                                                                                                        

Caused by:
  process didn't exit successfully: `rustc --crate-name num_traits --edition=2018 D:\Runtime\Rust\cargo\registry\src\index.crates.io-6f17d22bba15001f\num-traits-0.2.18\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=419 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"std\"" -C met
adata=30bc9611b16064ab -C extra-filename=-30bc9611b16064ab --out-dir F:\coding\min-test\target\aarch64-pc-windows-msvc\debug\deps --target aarch64-pc-windows-msvc -L dependency=F:\coding\min-test\target\aarch64-pc-windows-msvc\debug\deps -L dependency=F:\coding\min-test\target\debug\deps --cap-lints allow --cfg has_to_int_unchecked --cfg has_reverse_bits --cfg has_leading_trailing_ones --cfg has_div_euclid --cfg has_copysign --cfg has_is_subnormal --cfg has_total_cmp --cfg has_int_to_from_bytes --cfg has_float_to_from_bytes` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

The last working compiler that I've tried was `nightly-2024-01-15-aarch64-pc-windows-msvc`. I haven't attempted to bisect since then so there could be some compilers working after 2024-01-15.

```
rustc 1.78.0-nightly (3246e7951 2024-02-19)
binary: rustc
commit-hash: 3246e79513cb89ddbfc0f21cb5a877e5b321dcc5
commit-date: 2024-02-19
host: x86_64-pc-windows-msvc
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### PR DESCRIPTION
**Pull request by nikic**
Fixes https://github.com/rust-lang/rust/issues/120819.
Fixes https://github.com/rust-lang/rust/issues/121180.
Fixes https://github.com/rust-lang/rust/issues/121239.
Fixes https://github.com/rust-lang/rust/issues/121367.

### CODE REVIEW

**Comment by nikic** [comment]
Probably related to the libLLVM soname change in https://github.com/llvm/llvm-project/commit/235306ba1f89eb1b9f9724edec5eacb295f8198f.

**Comment by nikic** [comment]
Okay, this variant breaks download-ci-llvm.

**Comment by nikic** [comment]
Meh, this creates a dangling symlink `libLLVM-18-rust-dev.so -> libLLVM.so` instead of `libLLVM-18-rust-dev.so -> libLLVM.so.18.1-rust-dev`. I'll wait for the upstream fix for that one.

**Comment by nikic** [comment]
https://github.com/llvm/llvm-project/pull/82660 would be the fix for that.

**Comment by nikic** [comment]
Build fails with:

> 2024-02-24T10:27:07.4182642Z generated a symlink in a tarball: /checkout/obj/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/libLLVM-18-rust-1.78.0-nightly.so

So I guess distributing the symlink is not an option either :/

**Comment by nikic** [comment]
> Build fails with:
> 
> > 2024-02-24T10:27:07.4182642Z generated a symlink in a tarball: /checkout/obj/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/libLLVM-18-rust-1.78.0-nightly.so
> 
> So I guess distributing the symlink is not an option either :/

I don't think *not* distributing the symlink is possible, so what I did now is to limit it to just the rust-dev component (aka ci-llvm). That's the only place that should need it. All the "normal" dist tarballs continue to be symlink-free.

Let's see whether this works...

**Comment by nikic** [comment]
Okay, download-ci-llvm works now. I'll wait for https://github.com/rust-lang/llvm-project/pull/169 to be merged and then update this PR with the final version.

**Comment by nikic** [comment]
@rust-timer build 5e826decbc9c72668d6e1e8e7116a68c86f877c9

Just to confirm we didn't lose bolt optimization or something.

**Comment by nikic** [comment]
Looks like GitHub no longer processes force pushes?!

**Comment by nikic** [comment]
Okay, this is ready for re-review now.

It looks like perf is going to need an update for the detection of the libLLVM.so size after this change though (cc @Kobzol).

**Comment by cuviper** [comment]
Aw, I was hoping that the binary size actually did get better...
(IIRC, BOLT was essentially duplicating `.text` with its rewrite.)

**Comment by Kobzol** [comment]
https://perf.rust-lang.org/compare.html?start=6cbf0926d54c80ea6d15df333be9281f65bbeb36&end=5e826decbc9c72668d6e1e8e7116a68c86f877c9&stat=instructions%3Au&tab=artifact-size it would have to be infinitely better, since the `libLLVM.so` file simply disappeared from the artifact size metrics :grin:

**Comment by cuviper** [comment]
> I don't think _not_ distributing the symlink is possible, so what I did now is to limit it to just the rust-dev component (aka ci-llvm). That's the only place that should need it. All the "normal" dist tarballs continue to be symlink-free.

I can see that the symlink survives into the rust-dev tarball, but it looks like its `install.sh` is dereferencing that, because the installed copy gets duplicated as a whole file.

**Comment by nikic** [comment]
> > I don't think _not_ distributing the symlink is possible, so what I did now is to limit it to just the rust-dev component (aka ci-llvm). That's the only place that should need it. All the "normal" dist tarballs continue to be symlink-free.
> 
> I can see that the symlink survives into the rust-dev tarball, but it looks like its `install.sh` is dereferencing that, because the installed copy gets duplicated as a whole file.

Does the behavior of install.sh matter though? I do get the symlink when using the try build in download-ci-llvm, which I believe is the only thing this component should get used for.

**Comment by cuviper** [comment]
Hmm, I was thinking of it as a rustup component, but I guess we don't actually distribute it that way. (and rustup doesn't invoke `install.sh` either.)

@bors r+ rollup=never

**Comment by cuviper** [comment]
All good -- with that merged, a new `./x build` does extract `rust-dev` with that symlink preserved!

**Comment by RalfJung** [comment]
Something seems to still be wrong with the new soname: https://github.com/rust-lang/rust/issues/121889

**Comment by lqd** [comment]
`syn-opt` still looks currently noisy, and the `coercions` change looks noisy as well, albeit with a bigger amplitude than recently: it is a few merges later trending down close to prior to this PR, via some steps that didn't change compilation (a cargo update). 

@rustbot label: +perf-regression-triaged

**Pull request merged**
