### PR TITLE
Add compile fail test for unboxed_closures feature

### PR DESCRIPTION
**Pull request by topecongiro**
Hello, this is my first contribution to rust.
Issue #39059.

### CODE REVIEW

**Comment by est31** [comment]
Hi, and thanks for the PR!

One note, the test you added doesn't actually fail. You need to remove the `#![feature(...)]` attribute and continue the steps I outlined in #39059 to add the error message.

**Comment by topecongiro** [comment]
@est31 Hi, thank you for your comment.
Very sorry abou misunderstanding what should be done.
I removed `#![feature(...)]` attribute and added the error message.

**Comment by alexcrichton** [comment]
Thanks @topecongiro!

@bors: r+ delegate=est31

**Comment by est31** [comment]
@topecongiro you'll have to rebase this pull request and resolve the created merge conflicts. PR #40031 got merged before this, and both edited the whitelist.

**Comment by est31** [comment]
@topecongiro note that generally, its customary to use rebase instead of merge requests. I'll r+ anyway, just remember this for your future contributions. You can just force-push if you want to change it before it gets merged this way.

@bors r+

**Comment by topecongiro** [comment]
@est31 Sorry for bothering you. I will keep that in mind.

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Comment by est31** [comment]
@topecongiro can you remove that last commit? Its not required, and unneccessary clutter.

**Comment by eddyb** [comment]
FWIW the fix is to run `git pull --rebase upstream/master`.

**Comment by topecongiro** [comment]
@est31 @eddyb Thank you for your help and patience. I rebased.

**Pull request merged**
