### PR TITLE
Update rust-analyzer

### PR DESCRIPTION
**Pull request by lnicola**
to https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-01-11

### CODE REVIEW

**Comment by m-ou-se** [comment]
@bors r-

This failed in https://github.com/rust-lang/rust/pull/81102#issuecomment-761720245

```
error: could not compile `salsa`
```

That seems to be a rust-analyzer dependency.

**Comment by lnicola** [comment]
`salsa` compiles fine with the latest nightly. Could another PR have introduced those errors?

**Comment by lnicola** [comment]
Probably https://github.com/rust-lang/rust/pull/80732.

**Comment by m-ou-se** [comment]
> Could another PR have introduced those errors?

Maybe. I just searched for `salsa` because of that error message, which popped up a lot in rust-analyzer. Note that it failed on `--target arm-unknown-linux-gnueabihf`, which might be relevant.

If you think this PR is not the source of the problem, we can just try it again and see what happens.

**Comment by lnicola** [comment]
The target seems less relevant, that looks like a type error. I tried `cargo +nightly build --target arm-unknown-linux-gnueabihf` on `salsa 0.16` and it works.

I thought #80732 might be related to this because the test files say "ambigunous", but the error messages are not identical.

**Comment by lnicola** [comment]
Confirmed in https://github.com/rust-lang/rust/pull/80732#issuecomment-761800608.

**Comment by lnicola** [comment]
This needs another bors r+, but there'll be another `rust-analyzer` release tagged tonight, so I suppose we can wait until that.

**Comment by m-ou-se** [comment]
`salsa 0.15.2` (the one used before this PR) compiles fine with #80732. So if you're not in a hurry, I'd prefer waiting a bit until we figured out if `salsa 0.16` or #80732 is to blame, as only the combination of the two fails.

**Pull request closed without merging**
