### PR TITLE
add evocative examples for `Shl` and `Shr`

### PR DESCRIPTION
**Pull request by matthew-piziak**
r? @steveklabnik

### CODE REVIEW

**Comment by aravind-pg** [comment]
IMO this is a nice but unnecessarily sophisticated example, since the implementation involves some distractingly nontrivial vector manipulation. For documentation purposes is it not enough to just have say a `struct Scalar(i64)` with the obvious `Shl/Shr` implementation? After all the purpose here shouldn't be to suggest fun ideas for a `Shl/Shr` implementation but rather just to show concisely _how_ it is done :)

**Comment by matthew-piziak** [comment]
@aravind-pg Yeah, that's a good point. I've added the examples you suggested. Do you think something like `SpinVector` has value as a secondary example?

**Comment by aravind-pg** [comment]
Sure, I personally quite like it, but I'm not sure what the policy is on having two separate examples in the documentation (I would think it leans towards a no, in the interest of brevity).

**Comment by steveklabnik** [comment]
In general, more examples are good; brevity isn't always a good thing when it comes to docs. There's obviously some kind of limit to this.

**Comment by matthew-piziak** [comment]
Working on this PR started to feel like this after a while: 

https://www.youtube.com/watch?v=1pAMdn9oSPE

**Comment by steveklabnik** [comment]
Looks great, thanks!

@bors: r+ rollup

**Pull request merged**
