### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
Successful merges:

 - #53371 (Do not emit E0277 on incorrect tuple destructured binding)
 - #53829 (Add rustc SHA to released DWARF debuginfo)
 - #53950 (Allow for opting out of ThinLTO and clean up LTO related cli flag handling.)
 - #53976 (Replace unwrap calls in example by expect)
 - #54070 (Add Error::description soft-deprecation to RELEASES)
 - #54076 (miri loop detector hashing)
 - #54119 (Add some unit tests for find_best_match_for_name)
 - #54147 (Add a test that tries to modify static memory at compile-time)
 - #54150 (Updated 1.29 release notes with --document-private-items flag)
 - #54163 (Update stage 0 to latest beta)
 - #54170 (COMPILER_TESTS.md has been moved)

### CODE REVIEW

**Comment by kennytm** [comment]
@bors retry 

50 minute timeout

**Comment by kennytm** [comment]
@bors r+

50 minutes timeout 

Added #54170.

**Comment by pietroalbini** [comment]
@bors retry

50 minutes timeout

**Comment by kennytm** [comment]
Caused by #53933.

```
---- doc::output_not_captured stdout ----
running `C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe doc`
thread 'doc::output_not_captured' panicked at '
Expected: execs
    but: exited with exit code: 0
--- stdout
--- stderr
 Documenting a v0.0.1 (file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t506/foo/a)
    Checking a v0.0.1 (file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t506/foo/a)
error: unknown start of token: \u{2603}
 --> <stdin>:1:1
  |
1 | ☃
  | ^
warning: Invalid doc comment starting with: `☃`
 Documenting foo v0.0.1 (file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t506/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.90s
', tools\cargo\tests\testsuite\support\mod.rs:731:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    doc::output_not_captured
```

**Comment by kennytm** [comment]
@bors r+

Removed #53933 (causing error above)
Removed #53621 (already testing)
Added #53829, #53950

**Pull request merged**
