### PR TITLE
Enforce the shadowing restrictions from RFC 1560 for today's macros

### PR DESCRIPTION
**Pull request by jseyfried**
This PR enforces a weakened version of the shadowing restrictions from RFC 1560. More specifically,
- If a macro expansion contains a `macro_rules!` macro definition that is used outside of the expansion, the defined macro may not shadow an existing macro.
- If a macro expansion contains a `#[macro_use] extern crate` macro import that is used outside of the expansion, the imported macro may not shadow an existing macro.

This is a [breaking-change]. For example,

``` rust
macro_rules! m { () => {} }
macro_rules! n { () => {
    macro_rules! m { () => {} } //< This shadows an existing macro.
    m!(); //< This is inside the expansion that generated `m`'s definition, so it is OK.
} }
n!();
m!(); //< This use of `m` is outside the expansion, so it causes the shadowing to be an error.
```

r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @eddyb (this is needed for def/use orthogonality)
Also, this will need a crater run.

**Comment by nrc** [comment]
@brson, @nikomatsakis, @eddyb could one of you schedule a crater run please?

**Comment by eddyb** [comment]
@nrc Starting now.

**Comment by eddyb** [comment]
[Crater run](https://gist.github.com/eddyb/44de9299fdb80e2e475ca027deae2e38) shows two regressions ([`conv`](https://tools.taskcluster.net/task-inspector/#_E7g0LpcQ2eQ1gZRfCjvzw/0) and [`tokei`](https://tools.taskcluster.net/task-inspector/#gtz3O_ndRoC0NIftt5NqxQ/0)).

**Comment by nrc** [comment]
Code looks good, but I'm not sure about the Crater regressions. They certainly seem real and could indicate more uses in the wild. It is probably prudent to have a warning cycle for this if it is possible.

**Comment by jseyfried** [comment]
I demoted the errors into warnings with a note about future incompatibility.

Since `macro_rules!` error sites do not have node ids (unless they are `#[macro_export]`ed), I don't think it's possible to lint.

**Comment by durka** [comment]
> - A macro defined by a macro-expanded macro_rules! may not shadow an existing macro.

Can it shadow a macro which was previously defined by a macro?

I use the above trick in [static-cond](https://crates.io/crates/static-cond). If it's not permitted, you can only invoke `static_cond!` once per crate, and there's no way to create unique identifiers, so... this sucks.

**Comment by jseyfried** [comment]
@durka Yeah, looks like this PR and unhygienic macro names are a bad combination.

I wonder if it would be backwards compatible in practice to make macro names hygienic. That would avoid breaking `static-cond` as well as the two Crater-detected crates.

If we can't make macro names hygienic, we could instead only disallow macro-expanded shadowing *if the shadowing macro is used outside of the expansion*. This would also avoid breaking `static-cond` and the two Crater-detected crates, and it wouldn't compromise name resolution in any way.

**Comment by jseyfried** [comment]
I weakened the shadowing restrictions to avoid breakage in practice (see the edited initial comment).
This PR no longer breaks `static-cond` or the two crates from the Crater run.

**Comment by nrc** [comment]
Code looks good, I'd like to get another Crater run before we land though. @eddyb, @brson, @nikomatsakis  could someone oblige please?

**Comment by eddyb** [comment]
On it!

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/5d06cd2193e34d35b2313af6a638533e) looks good (the unrelated breakage is rust-num/num#231, I reused the "before" results).

**Comment by nrc** [comment]
Thanks @eddyb !

@bors: r+

**Pull request merged**
