### PR TITLE
Improve register_diagnostics macro

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Now the macro argument list can be finished by a comma (not sure this is correct english...).

cc @tamird
r? @bluss

### CODE REVIEW

**Comment by tamird** [comment]
you can also make the comma required by changing the existing thing to `($($code:tt,)*) => (`; I'd personally prefer that. Also true of the other nearby macros (i think there are 3 or 4)

**Comment by GuillaumeGomez** [comment]
I can add this "feature" for others too, of course. However, I like to have choice to finish the macro with or without a comma. Let's see others' opinions.

**Comment by cmr** [comment]
This looks fine to me. The Rust Way is to always allow trailing comma but never require it, so this seems consistent with that.

**Comment by GuillaumeGomez** [comment]
Merged in #27098. I close.

**Pull request closed without merging**
