### PR TITLE
Verify awscli download in CI

### PR DESCRIPTION
**Pull request by pierwill**
Adds a simple checksum verification applied to the downloaded artifact before installation.

### CODE REVIEW

**Comment by pierwill** [comment]
@rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
We currently depend on probably dozens or hundreds of binaries/source files etc downloaded from our S3 buckets, and it seems a little like trying to do verification (via checksums) that what is in the bucket is the same as when initially added will not scale too well with this approach -- many of those downloads are pretty deeply embedded into the various scripts being used (or are e.g. `apt get` commands).

I think updating *all* of those with this kind of verification with embedded SHAs in our scripts is probably too much -- it's a lot of noise, and for comparatively little value: edit access to our S3 buckets is already "enough" to cause problems, realistically.

If we could automatically generate this -- similar to how src/stage0.json has a bunch of hashes -- I would be more inclined to go down this road. But my understanding is that there's no great way to do that today; it would probably need a pretty heavyweight implementation that does something like put a proxy in between the internet and our CI, doing TLS termination and checksum verification, which is (a) hard and (b) not really practical at our scale today.

So my current feeling is to not accept this kind of PR, but I am open to push back on that.

**Comment by shepmaster** [comment]
From an outside perspective, it’s be nice to explain what problem this is armed at solving.

**Comment by pierwill** [comment]
Thanks @shepmaster and @Mark-Simulacrum!

> From an outside perspective, it’d be nice to explain what problem this is aimed at solving.

The goal with this PR is to start us down a road of adding some kind of verification to the dependencies we download over the network and run in the main Rust CI.

> We currently depend on probably dozens or hundreds of binaries/source files etc downloaded from our S3 buckets, and it seems a little like trying to do verification (via checksums) that what is in the bucket is the same as when initially added will not scale too well with this approach 

I think we can pretty easily establish an upper bound on the number of dependencies, for CI at least. For this discussion, let's define a *dependency* as a code artifact [executable binary, script, etc.] downloaded over the network and integrated into a system in an automated way. So let's search for `curl` invocations:

```sh
$ cd rust/src/ci
$ rg curl --stats
[...snip...]
156 matches
```

Not all of these matches are downloading dependencies, but let's say there are 100+ dependencies. To verify these with checksums, the code is basically the same couple lines of Bash for each. It's well within our capability to write and review these a few at a time. Also, we could identify some subset of dependencies to check.

It's also worth noting that while we cache and download many dependencies from our S3 buckets, we also pull from other sources (github.com, nodejs.org, gnu.org), that we should trust significantly less.

> -- many of those downloads are pretty deeply embedded into the various scripts being used (or are e.g. apt get commands).

My understanding is that `apt` does some verification using cryptographic signatures. By contrast, doing `curl https://example.com/sup.tar.gz | tar` amounts to running untrusted code.

> I think updating all of those with this kind of verification with embedded SHAs in our scripts is probably too much -- it's a lot of noise, and for comparatively little value: edit access to our S3 buckets is already "enough" to cause problems, realistically.

I see two points here: 1) noise concerns and 2) questions about privileged access and different routes of compromise. I'm not sure I understand 1. Are we concerned about noise in possible CI errors due to flaky network connections (a possibility, sure), or in PR review/code changes? The latter is basically a one-time cost.

As for 2, I agree that we want to think about this broadly. Someone with unauthorized access to our S3 can cause all kinds of trouble, of course. But with these checks in place, there'd at least be some mitigating speed bumps. The way I think about this, it's about reducing the probability of compromise, not eliminating it.

As you mention, we could cook up something to automate various aspects of these checks. This might be worth exploring. But adding checksum verifications where currently we simply trust the network connection is a real win for integrity and security.

**Comment by Mark-Simulacrum** [comment]
For the non-S3 URLs, I agree there's more value in doing this, but *in general* my preference there is typically to mirror the contents of the URL to our own S3 bucket, so that we get the better reliability etc from that approach. Once we've done that, I think we can agree that checksums are less beneficial; the folks approving PRs here are in theory the same folks uploading the binaries. That means that the checksum is basically making this a trust on first use situation, which is *ok*, but not really all that much better from my perspective. We could migrate our CI mirrors S3 bucket to use indefinite [object lock](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html) for basically the same effect as the checksums, but without needing to edit CI scripts to verify things, if I understand the documentation there correctly.

For the third-party domains we use (e.g., github, various ftp sites, etc.) -- particularly common in crosstool-ng scripts, I think -- I agree that checksums help. However, they're not really the best solution: we should be mirroring essentially all of those binaries to our S3 bucket *anyway* so that we don't depend on the third-party domains staying up; we typically do this today when those third parties go down, but doing it up front is even better.

That kind of work is something I would definitely be happy to support.

There is a relatively low initial cost in landing this kind of PR, but it increases the amount of things our CI scripts are doing (never a good thing), and from my perspective is not particularly well motivated for S3 files (and as noted, for non-S3 files is good, but we should be moving those files onto S3 anyway).

With regards to apt or other similar downloads, you are right, I think, that apt does GPG verification. My understanding is that is just the equivalent of TLS verification though -- there's a slight defense in depth argument to be made, but not significantly more than that. In any case, this is more of a minor note than anything else.

**Comment by Mark-Simulacrum** [comment]
> This might be worth exploring. But adding checksum verifications where currently we simply trust the network connection is a real win for integrity and security.

To be explicit: My perspective is that most actors which could compromise TLS for our S3 buckets -- even just limited to the GitHub actions -- would highly likely be able to alter (for example) the docker image or similar being downloaded, or just alter files being uploaded -- so there's not *actually* significant benefit to the checksum verification.

**Comment by pierwill** [comment]
Thanks for this analysis @Mark-Simulacrum! I'll give this all some thought. Sounds like we agree there is room for improvement here. 🙏

**Comment by pietroalbini** [comment]
I agree with Mark's thoughts here.

In the long term, I don't think the solution is to pin the hashes on the CI side, but to have tooling managing and updating the contents of the things we mirror in our S3 bucket. That's going to be a ton of work, and I don't think we have the bandwidth for that right now.

**Pull request closed without merging**
