### PR TITLE
tvOS simulator support on Apple Silicon for rustc

### PR DESCRIPTION
**Pull request by simlay**
Closes or is a subtask of #115692.

# Tier 3 Target Policy

At this tier, the Rust project provides no official support for a target, so we place minimal requirements on the introduction of targets.

> * A tier 3 target must have a designated developer or developers (the "target maintainers") on record to be CCed when issues arise regarding the target. (The mechanism to track and CC such developers may evolve over time.)

See [`src/doc/rustc/src/platform-support/apple-tvos.md`](https://github.com/rust-lang/rust/blob/4ab4d48ee59968d8d519ccda5e12c9d200cc092f/src/doc/rustc/src/platform-support/apple-tvos.md)

> * Targets must use naming consistent with any existing targets; for instance, a target for the same CPU or OS as an existing Rust target should use the same name for that CPU or OS. Targets should normally use the same names and naming conventions as used elsewhere in the broader ecosystem beyond Rust (such as in other toolchains), unless they have a very good reason to diverge. Changing the name of a target can be highly disruptive, especially once the target reaches a higher tier, so getting the name right is important even for a tier 3 target.
>     * Target names should not introduce undue confusion or ambiguity unless absolutely necessary to maintain ecosystem compatibility. For example, if the name of the target makes people extremely likely to form incorrect beliefs about what it targets, the name should be changed or augmented to disambiguate it.
>     * If possible, use only letters, numbers, dashes and underscores for the name. Periods (.) are known to cause issues in Cargo.

This naming scheme matches `$ARCH-$VENDOR-$OS-$ABI` (I think `sim` is the ABI here) which is matches the iOS apple silicon simulator (`aarch64-apple-ios-sim`). [There is some discussion about renaming some apple simulator targets](https://github.com/rust-lang/rust/issues/115692#issuecomment-1712931910) to match the `-sim` suffix but that is outside the scope of this PR.

> * Tier 3 targets may have unusual requirements to build or use, but must not create legal issues or impose onerous legal terms for the Rust project or for Rust developers or users.
>
>    * The target must not introduce license incompatibilities.
>    * Anything added to the Rust repository must be under the standard Rust license (MIT OR Apache-2.0).
>    * The target must not cause the Rust tools or libraries built for any other host (even when supporting cross-compilation to the target) to depend on any new dependency less permissive than the Rust licensing policy. This applies whether the dependency is a Rust crate that would require adding new license exceptions (as specified by the tidy tool in the rust-lang/rust repository), or whether the dependency is a native library or binary. In other words, the introduction of the target must not cause a user installing or running a version of Rust or the Rust tools to be subject to any new license requirements.
>    * Compiling, linking, and emitting functional binaries, libraries, or other code for the target (whether hosted on the target itself or cross-compiling from another target) must not depend on proprietary (non-FOSS) libraries. Host tools built for the target itself may depend on the ordinary runtime libraries supplied by the platform and commonly used by other applications built for the target, but those libraries must not be required for code generation for the target; cross-compilation to the target must not require such libraries at all. For instance, rustc built for the target may depend on a common proprietary C runtime library or console output library, but must not depend on a proprietary code generation library or code optimization library. Rust's license permits such combinations, but the Rust project has no interest in maintaining such combinations within the scope of Rust itself, even at tier 3.
>    * "onerous" here is an intentionally subjective term. At a minimum, "onerous" legal/licensing terms include but are not limited to: non-disclosure requirements, non-compete requirements, contributor license agreements (CLAs) or equivalent, "non-commercial"/"research-only"/etc terms, requirements conditional on the employer or employment of any particular Rust developers, revocable terms, any requirements that create liability for the Rust project or its developers or users, or any requirements that adversely affect the livelihood or prospects of the Rust project or its developers or users.

This contribution is fully available under the standard Rust license with no additional legal restrictions whatsoever. This PR does not introduce any new dependency less permissive than the Rust license policy.

The new targets do not depend on proprietary libraries.

> * Tier 3 targets should attempt to implement as much of the standard libraries as possible and appropriate (core for most targets, alloc for targets that can support dynamic memory allocation, std for targets with an operating system or equivalent layer of system-provided functionality), but may leave some code unimplemented (either unavailable or stubbed out as appropriate), whether because the target makes it impossible to implement or challenging to implement. The authors of pull requests are not obligated to avoid calling any portions of the standard library on the basis of a tier 3 target not implementing those portions.

This new target implements as much of the standard library as the other tvOS targets do.

> * The target must provide documentation for the Rust community explaining how to build for the target, using cross-compilation if possible. If the target supports running binaries, or running tests (even if they do not pass), the documentation must explain how to run such binaries or tests for the target, using emulation if possible or dedicated hardware if necessary.

I have added the target to the other tvOS targets in [`src/doc/rustc/src/platform-support/apple-tvos.md`](https://github.com/rust-lang/rust/blob/4ab4d48ee59968d8d519ccda5e12c9d200cc092f/src/doc/rustc/src/platform-support/apple-tvos.md)

> * Neither this policy nor any decisions made regarding targets shall create any binding agreement or estoppel by any party. If any member of an approving Rust team serves as one of the maintainers of a target, or has any legal or employment requirement (explicit or implicit) that might affect their decisions regarding a target, they must recuse themselves from any approval decisions regarding the target's tier status, though they may otherwise participate in discussions.
>    * This requirement does not prevent part or all of this policy from being cited in an explicit contract or work agreement (e.g. to implement or maintain support for a target). This requirement exists to ensure that a developer or team responsible for reviewing and approving a target does not face any legal threats or obligations that would prevent them from freely exercising their judgment in such approval, even if such judgment involves subjective matters or goes beyond the letter of these requirements.
> * Tier 3 targets must not impose burden on the authors of pull requests, or other developers in the community, to maintain the target. In particular, do not post comments (automated or manual) on a PR that derail or suggest a block on the PR based on a tier 3 target. Do not send automated messages or notifications (via any medium, including via @) to a PR author or others involved with a PR regarding a tier 3 target, unless they have opted into such messages.
>    * Backlinks such as those generated by the issue/PR tracker when linking to an issue or PR are not considered a violation of this policy, within reason. However, such messages (even on a separate repository) must not generate notifications to anyone involved with a PR who has not requested such notifications.
> * Patches adding or updating tier 3 targets must not break any existing tier 2 or tier 1 target, and must not knowingly break another tier 3 target without approval of either the compiler team or the maintainers of the other tier 3 target.
>    * In particular, this may come up when working on closely related targets, such as variations of the same architecture with different features. Avoid introducing unconditional uses of features that another variation of the target may not have; use conditional compilation or runtime detection, as appropriate, to let each target run code supported by that target.

I acknowledge these requirements and intend to ensure that they are met.

This target does not touch any existing tier 2 or tier 1 targets and should not break any other targets.

### CODE REVIEW

**Comment by simlay** [comment]
Hmm, upon trying to test this thoroughly. I'm running into `note: ld: building for tvOS, but linking in object file built for tvOS Simulator, file` when doing `./x build` with this is my `config.toml`:

```tool
[build]
build-stage = 1
target = [
    "aarch64-apple-tvos-sim",
    "aarch64-apple-tvos",
]
```
Here's the error'd CC line:
```
"cc" "-Wl,-exported_symbols_list,/var/folders/b7/sqydsw156vxg0pk1nx9vqt600000gq/T/rustclXiu5Y/list" "-arch" "arm64" "/var/folders/b7/sqydsw156vxg0pk1nx9vqt600000gq/T/rustclXiu5Y/symbols.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98
c52.std.cba4e8897f0eaefb-cgu.00.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.01.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-c
gu.02.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.03.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.04.rcgu.o" "/Users/seba
stian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.05.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.06.rcgu.o" "/Users/sebastian.imlay/projects/rust/
build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.07.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.08.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin
/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.09.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.10.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-
tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.11.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.12.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-
470276bd11f98c52.std.cba4e8897f0eaefb-cgu.13.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.14.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e
8897f0eaefb-cgu.15.rcgu.o" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.3eovzceissu0bfu1.rcgu.rmeta" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.sb3ppexxaz3fel9.rcgu.o" "-L" "/Users/sebas
tian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps" "-L" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/release/deps" "-L" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/build/compiler_builtins-2c5c71b6c4ad9627/out" "-L" "/User
s/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1/lib/rustlib/aarch64-apple-tvos-sim/lib" "-lSystem" "-lobjc" "-framework" "Security" "-framework" "Foundation" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libpanic_unwind-c66e08067e9f11c5.rlib" "/Users/sebastian.imlay/projects/rust
/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libobject-6efb1384360ce139.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libmemchr-8f2c64414e0090b4.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps
/libaddr2line-2677355524ebde6b.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libgimli-867e157f81d592da.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/librustc_demangle-ff940eb4f766b6ff.rlib" "/Users/sebastian.imlay/projec
ts/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libstd_detect-5e79493c19d35ff2.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libhashbrown-dd441b3623699792.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-si
m/release/deps/librustc_std_workspace_alloc-577ba5892d21acbd.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libminiz_oxide-552b132bfc53f2d9.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libadler-4d48d373d92ad81b.rlib" "/U
sers/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libunwind-77cdb8eb7169e92e.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libcfg_if-ee9ca3f6e279a5ba.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/a
arch64-apple-tvos-sim/release/deps/liblibc-6103219613d5e00e.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/liballoc-0f1df037fa52077d.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/librustc_std_workspace_core-1c3601da1907d2
32.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libcore-69db625055de02aa.rlib" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libcompiler_builtins-82213acae75304a0.rlib" "-lc" "-lm" "-isysroot" "/Applications/Xcode.app/Content
s/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS16.4.sdk" "-Wl,-syslibroot" "/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS16.4.sdk" "-L" "/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1/lib/rustlib/aarch64-apple-tvos-sim/lib" "-o" "/Users/sebastian.imlay/projects/rust/buil
d/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/libstd-470276bd11f98c52.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-Wl,-install_name,@rpath/libstd-470276bd11f98c52.dylib" "-nodefaultlibs" "-Wl,-rpath,@loader_path/../lib"
  = note: ld: building for tvOS, but linking in object file built for tvOS Simulator, file '/Users/sebastian.imlay/projects/rust/build/aarch64-apple-darwin/stage1-std/aarch64-apple-tvos-sim/release/deps/std-470276bd11f98c52.std.cba4e8897f0eaefb-cgu.07.rcgu.o' for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It looks like the sysroot is pointing to `AppleTVOS.Platform` when I think it should be pointing to `AppleTVSimulator.platform`. I'm not sure this is due to my changes though.

**Comment by wesleywiser** [comment]
Hi @simlay, did you figure out what was causing the `but linking in object file built for macOS, file` error? 🙂

**Comment by wesleywiser** [comment]
Thanks @simlay! The code changes look good to me but since @thomcc is the only maintainer on file for the related simulator targets, I'd really like to get an ACK from him that he's ok with this prior to merging this PR. 

Because you're adding a new target, even though it's based on an existing target, our [target tier policy](https://doc.rust-lang.org/rustc/target-tier-policy.html) asks that you sign off on some details of the new target. Could you please quote the corresponding requirements verbatim from the [tier 3 target tier policy](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-3-target-policy) to explain how the target meets those requirements (leaving a new comment here is fine). You can find an example of this in the PR description for #86191. Thank you!

**Comment by simlay** [comment]
> Because you're adding a new target, even though it's based on an existing target, our [target tier policy](https://doc.rust-lang.org/rustc/target-tier-policy.html) asks that you sign off on some details of the new target. Could you please quote the corresponding requirements verbatim from the [tier 3 target tier policy](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-3-target-policy) to explain how the target meets those requirements (leaving a new comment here is fine). You can find an example of this in the PR description for #86191. Thank you!

Done! I'll admit that I didn't know all the details of the Tier 3 Target policy (I didn't come across this when reading [Rust Compiler Development Guide](https://rustc-dev-guide.rust-lang.org/building/new-target.html)) and appreciate having to read it explicitly.

**Review by wesleywiser — APPROVED** [review]
Awesome, thank you so much @simlay! This looks ready to go to me once Thom signs off.

**Comment by thomcc** [comment]
Looks good to me.

@bors r+

**Comment by thomcc** [comment]
Thanks for your work.

**Pull request merged**
