### PR TITLE
Modified the testcases for VxWorks

### PR DESCRIPTION
**Pull request by BaoshanPang**

### CODE REVIEW

**Comment by BaoshanPang** [comment]
cc @n-salim 
cc @Umesh Kalappa

**Comment by alexcrichton** [comment]
I wanted to write a comment again which echoes something I think I've said previously, which is that keeping the test suite running for vxworks is going to be very difficult and unfortunately probably cause a bit of a burden on us as a project. There's already been a good number of PRs adding `// ignore-vxworks` annotations and this is starting to add assertions in the test suite itself.

I'm generally ok rubber-stamping these for now, but there continues to be no guarantee that they won't regress quickly. If we write new tests, for example, there's no guarantee they'll work on vxworks. Additionally I think we'll still reserve the right to clean up these tests and back out the annotations if we think they cause too much overhead in managing the tests for other platforms.

To confirm, is all that still ok?

**Comment by BaoshanPang** [comment]
> I wanted to write a comment again which echoes something I think I've said previously, which is that keeping the test suite running for vxworks is going to be very difficult and unfortunately probably cause a bit of a burden on us as a project. There's already been a good number of PRs adding `// ignore-vxworks` annotations and this is starting to add assertions in the test suite itself.
> 
> I'm generally ok rubber-stamping these for now, but there continues to be no guarantee that they won't regress quickly. If we write new tests, for example, there's no guarantee they'll work on vxworks. Additionally I think we'll still reserve the right to clean up these tests and back out the annotations if we think they cause too much overhead in managing the tests for other platforms.
> 
> To confirm, is all that still ok?

Sure. We appriciate the support from you and the community. Fixing the test case makes us easier in term of working on rust for vxWorks, but if that cause too much overhead for the project we will be thinking about another way to work around it.

**Comment by alexcrichton** [comment]
@bors: r+

Ok, I can keep rubber stamping while I'm able in that case!

**Pull request merged**
