### PR TITLE
Add `std::io::FileMode::Create`

### PR DESCRIPTION
**Pull request by dpc**
This adds possibility to create a file only if it didn't exist already.

### CODE REVIEW

**Comment by dpc** [comment]
It seems there's currently no way to do `open` with `O_EXCL | O_CREATE` through standard library. Do you think that above path makes sense? Should I write some tests for this?

**Comment by alexcrichton** [comment]
Thanks for the PR! We may want to hold off on this for now, however as the I/O module is likely to be redesigned during the next release cycle. You can find some more details in the [original RFC](https://github.com/rust-lang/rfcs/pull/517), although a new one hasn't quite yet been made for the `std::fs` changes.

In short, however, we definitely want to support an operation like this! It will probably look different after the I/O RFCs have landed, but we'll definitely at least make sure this is possible :)

**Comment by huonw** [comment]
Handing off review to @alexcrichton. Thanks @dpc!

**Comment by steveklabnik** [comment]
This doesn't merge cleanly any more.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of the [open RFC on `std::fs`](https://github.com/rust-lang/rfcs/pull/739) for now. Thanks for the patch though @dpc!

**Pull request closed without merging**
