### PR TITLE
Improve ELF TLS detection on OSX

### PR DESCRIPTION
**Pull request by alexcrichton**
Currently a compiler can be built with the `--disable-elf-tls` option for compatibility with OSX 10.6 which doesn't have ELF TLS. This is unfortunate, however, as a whole new compiler must be generated which can take some time. These commits add a new (feature gated) `cfg(target_thread_local)` annotation set by the compiler which indicates whether `#[thread_local]` is available for use. The compiler now interprets `MACOSX_DEPLOYMENT_TARGET` (a standard environment variable) to set this flag on OSX. With this we may want to start compiling our OSX nightlies with `MACOSX_DEPLOYMENT_TARGET` set to 10.6 which would allow the compiler out-of-the-box to generate 10.6-compatible binaries. 

For now the compiler still by default targets OSX 10.7 by allowing ELF TLS by default (e.g. if `MACOSX_DEPLOYMENT_TARGET` isn't set).

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @brson, @rillian 

This is primarily motivated by Gecko which requires 10.6 compatibility but is currently having to compile their own OSX toolchain (with `--disable-elf-tls`). The primary benefit for this to them is if we ourselves start compiling our nightlies to run on 10.6, which means the standard library won't use ELF TLS. External consumers of the standard library, however, will continue to use ELF TLS by default. This seems like an ok balance between compatibility and speed to me, but I'm curious what others think!

**Comment by rillian** [comment]
Thanks, @alexcrichton! For gecko we actually build on 10.7, so the compiler itself can use ELF TLS, we just need it to be able to produce binaries which work on 10.6 (and so libstd must not use ELF TLS) when MACOSX_DEPLOYMENT_TARGET is < 10.7.

If I understand the patch properly, that case is still covered by building nightlies with MACOSX_DEPLOYMENT_TARGET=10.6, but I wanted to be sure the requirement is clear.

**Comment by alexcrichton** [comment]
Ah yeah thanks for clarifying, right now the build which produces standard libraries for OSX also produces compilers, so for us they're one and the same. I could imagine, however, that we start providing alternate compilation profiles of the standard library and this could certainly be one of them!

**Comment by alexcrichton** [comment]
Ah and I finally got around to doing some benchmarking, and of this simple benchmark:

```rust
#![feature(test)]
#![feature(static_mutex, const_fn)]

extern crate test;

use std::sync::StaticMutex;

pub fn doit() {
    static L: StaticMutex = StaticMutex::new();
    drop(L.lock());
}

#[bench]
fn bench_a(bh: &mut test::Bencher) {
    bh.iter(|| { doit() });
}
```

The timings look like:

```
$ ./use-elf-tls --bench

running 1 test
test bench_a ... bench:          22 ns/iter (+/- 13)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured

$ ./use-os-tls --bench

running 1 test
test bench_a ... bench:          24 ns/iter (+/- 9)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured

```

So  we may actually be able to turn on 10.6 support by default in nightlies with little-to-no performance impact

**Comment by alexcrichton** [comment]
Ah and a similar benchmark for just raw TLS access times:

```rust
#![feature(test)]
#![feature(const_fn)]

extern crate test;

use std::cell::Cell;

#[bench]
fn bench_a(bh: &mut test::Bencher) {
    thread_local!(static C: Cell<usize> = Cell::new(0));
    bh.iter(|| {
        C.with(|c| {
            let r = c.get();
            c.set(r + 1);
            r
        })
    })
}
```

Shows a difference of 4ns/iter vs 5ns/iter for ELF vs OS tls (respectively), so it may actually be that libstd is barely affected at all in terms of perf.

**Comment by aturon** [comment]
I'm :+1: on this change, and likely for changing the default target in our release artifacts as well.

**Pull request merged**
