### PR TITLE
misc bootstrap cleanups

### PR DESCRIPTION
**Pull request by jyn514**
- rename `detail_exit_macro` to `exit`
- remove unnecessary `Builder::new_standalone` function
- support `x suggest` with build-metrics

### CODE REVIEW

**Review by albertlarsan68 — APPROVED** [review]
LGTM, I just would want the suggested run build metric quirk to be documented somewhere, like in the --help output

**Comment by jyn514** [comment]
i changed `x suggest` to properly support metrics. the `clone` hack should no longer be visible in the metrics file.

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+

**Pull request merged**
