### PR TITLE
Update attributes.md - Last sentence updated to reflect support for custom attributes

### PR DESCRIPTION
**Pull request by Dowwie**
example:  [#[serde(...)] attributes](https://github.com/Dowwie/rust-authz/blob/master/src/authz.rs#L14)

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
I kinda feel like "...from within a custom derive" might flow better? Also, it would probably be prudent to link the words "custom derive" to `procedural-macros.html`.

**Comment by frewsxcv** [comment]
> I kinda feel like "...from within a custom derive" might flow better? Also, it would probably be prudent to link the words "custom derive" to `procedural-macros.html`.

I like this wording a little better too, and agree that link would be helpful. @Dowwie What do you think about this suggestion?

**Comment by GuillaumeGomez** [comment]
This sentence is very heavy to read. It'll need to be rewritten.

**Comment by Dowwie** [comment]
@GuillaumeGomez So I've pointed out that the original sentence was no longer accurate.  Until the group finds a satisfactory replacement, false information will be provided.

Opinions are welcome but alternatives would be better.

**Comment by frewsxcv** [comment]
> Is the following what is suggested?

> Rust attributes are used for a number of different things. There is a full list of attributes [in the reference][reference]. The Rust compiler defines many standardized attributes but allows for customized attributes from within a custom [`derive`][derive].
> \[derive]: procedural-macros.html

This looks good to me. 

> (note: I'm a beginner to Rust) Isn't it correct to expand on the last part: "... from within a custom derived trait" ?

Traits aren't involved here. If you want to implement a custom attribute today in stable rust, you'll have to do it within a `derive`. See this book section for more information:

https://doc.rust-lang.org/book/procedural-macros.html

**Comment by Dowwie** [comment]
sounds good to me

**Comment by frewsxcv** [comment]
@Dowwie need any help with this?

**Comment by Dowwie** [comment]
Yes.  Do I commit an update or is it possible to update this one?

**Comment by GuillaumeGomez** [comment]
@Dowwie: Just update this one.

**Comment by Dowwie** [comment]
@GuillaumeGomez done

**Comment by GuillaumeGomez** [comment]
There is still a git conflict.

**Comment by frewsxcv** [comment]
To resolve the conflict, if you know how to rebase, you can rebase off the latest master commit. Otherwise, it's fine to just do `git fetch origin && git merge origin/master`

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Comment by frewsxcv** [comment]
Also, keep in mind that the book now lives in a new repository: https://github.com/rust-lang/book/

**Pull request closed without merging**
