### PR TITLE
Add `Identity` lang item

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This is another approach for https://github.com/rust-lang/rust/pull/97974 suggested by @oli-obk.

The plan with this is then to add the `TyAlias` variant into the rustc_type_ir `TyKind` enum.

cc @compiler-errors

r? @oli-obk

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I added the missing "explanation" for the ignored code block in the documentation.

**Comment by jackh726** [comment]
Wait...why?

**Comment by oli-obk** [comment]
> Wait...why?

🤣 this is missing like 112% of the context. The linked PR is a huge task it seems and I wanted @GuillaumeGomez to check if the problem is that we don't normalize in enough places or whether it's just the linked PR missing a normalization for the new type alias variant wherever we normalize projections. If this pr passes, then the linked PR should be trivial instead of adding normalization to a billion places. If this PR fails, then we can build tests that fail on master by doing the same thing as what this PR does just without a lang item and contained to a single test

**Comment by GuillaumeGomez** [comment]
Everything falls apart as soon as we run outside of bootstrap because it doesn't seem to be able to find the `Identity` lang item from what I can see.

**Review by oli-obk — CHANGES_REQUESTED** [review]

**Comment by fmease** [comment]
Superseded by #108860 if I understand correctly. Closing as completed. Feel free to reopen if you disagree.

**Pull request closed without merging**
