### PR TITLE
[Beta 1.77] Fix bootstrapping from 1.76

### LINKED ISSUE #120810: rust-1.77_beta bootstrap is broken with: error[E0658]: `c".."` literals are experimental in library/std/src/sys/pal/unix/
hello everyone, 

I got this error when I bootstrap the current rust-beta branch: 

```
error[E0658]: `c".."` literals are experimental
  --> library/std/src/sys/pal/unix/mod.rs:74:35
   |
74 |         thread::Thread::set_name(&c"main");
   |                                   ^^^^^^^
   |
   = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
   = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/mod.rs:126:27
    |
126 |                 if open64(c"/dev/null".as_ptr().cast(), libc::O_RDWR, 0) == -1 {
    |                           ^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/mod.rs:156:31
    |
156 |                     if open64(c"/dev/null".as_ptr().cast(), libc::O_RDWR, 0) == -1 {
    |                               ^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/args.rs:249:53
    |
249 |             let process_info_sel = sel_registerName(c"processInfo".as_ptr());
    |                                                     ^^^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/args.rs:250:50
    |
250 |             let arguments_sel = sel_registerName(c"arguments".as_ptr());
    |                                                  ^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/args.rs:251:46
    |
251 |             let count_sel = sel_registerName(c"count".as_ptr());
    |                                              ^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/args.rs:252:56
    |
252 |             let object_at_index_sel = sel_registerName(c"objectAtIndex:".as_ptr());
    |                                                        ^^^^^^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/args.rs:253:51
    |
253 |             let utf8string_sel = sel_registerName(c"UTF8String".as_ptr());
    |                                                   ^^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/args.rs:255:39
    |
255 |             let klass = objc_getClass(c"NSProcessInfo".as_ptr());
    |                                       ^^^^^^^^^^^^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
    --> library/std/src/sys/pal/unix/fs.rs:1143:17
     |
1143 |                 c"".as_ptr() as *const c_char,
     |                 ^^^
     |
     = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
     = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
  --> library/std/src/sys/pal/unix/process/process_common.rs:27:33
   |
27 |         const DEV_NULL: &CStr = c"null:";
   |                                 ^^^^^^^^
   |
   = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
   = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
  --> library/std/src/sys/pal/unix/process/process_common.rs:29:33
   |
29 |         const DEV_NULL: &CStr = c"/null";
   |                                 ^^^^^^^^
   |
   = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
   = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
  --> library/std/src/sys/pal/unix/process/process_common.rs:31:33
   |
31 |         const DEV_NULL: &CStr = c"/dev/null";
   |                                 ^^^^^^^^^^^^
   |
   = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
   = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

error[E0658]: `c".."` literals are experimental
   --> library/std/src/sys/pal/unix/thread.rs:168:17
    |
168 |                 c"%s".as_ptr(),
    |                 ^^^^^
    |
    = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
    = help: add `#![feature(c_str_literals)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.

Did not run successfully: exit status: 1
```

There was a lot of pushing and reverting changesets relevant to the c literals stabilization, I tried to get an overview of what backport might be missing here, but I failed and am at a loss. 

I am on linux x86_64, with musl as my libc, I doubt the later is causing the issues.

### PR DESCRIPTION
**Pull request by ehuss**
Due to the timing of the revert for stabilization of c_str_literal (https://github.com/rust-lang/rust/pull/119528 which reverted in 1.76) and trait_upcasting (https://github.com/rust-lang/rust/pull/120269 which reverted in 1.76), which happened after https://github.com/rust-lang/rust/pull/119211 (Bump stage0 to 1.76 beta), this resulted in some of the feature attributes not being restored which are needed to be able to bootstrap from 1.76. This restores those features.

This also includes a stage0 bump to the just released stable. This is necessary because stage0 was currently pointing at an old beta which did not contain the reverts.

Fixes #120810

### CODE REVIEW

**Comment by ehuss** [comment]
cc @Mark-Simulacrum

**Comment by stefson** [comment]
Hi, the fix is working for me. Please note, there is an update of stage0.json file mixed in here! :-)

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

Makes sense to me.

**Comment by stefson** [comment]
thanks everyone

**Pull request merged**
