### PR TITLE
Remove in-tree flate/getopts crates

### PR DESCRIPTION
**Pull request by alexcrichton**
Remove `src/libflate` in favor of `flate2` on crates.io and `src/libgetopts` in favor of `getopts` on crates.io. The replacements have slightly different APIs and the usage in the compiler has been updated to reflect this.

This uncovered an unfortunate limitation of the compiler today to deal with linking everything correctly, and the workaround can be found documented in `src/librustc/Cargo.toml`.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We can also remove miniz.c from the COPYRIGHT file, I think.

**Comment by aidanhs** [comment]
Travis failed:
```
[00:49:58] make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[00:49:58] error[E0464]: multiple matching crates for `libc`
[00:49:58]   --> foo.rs:15:1
[00:49:58]    |
[00:49:58] 15 | extern crate libc;
[00:49:58]    | ^^^^^^^^^^^^^^^^^^
[00:49:58]    |
[00:49:58]    = note: candidates:
[00:49:58]    = note: path: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6545a7b8b89ca177.rlib
[00:49:58]    = note: crate name: libc
[00:49:58]    = note: path: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6ecacccb5bdc4911.rlib
[00:49:58]    = note: crate name: libc
[00:49:58] 
[00:49:58] error[E0463]: can't find crate for `libc`
[00:49:58]   --> foo.rs:15:1
[00:49:58]    |
[00:49:58] 15 | extern crate libc;
[00:49:58]    | ^^^^^^^^^^^^^^^^^^ can't find crate
[00:49:58] 
[00:49:58] error: aborting due to previous error(s)
[00:49:58] 
[00:49:58] make[1]: *** [all] Error 101
```

**Comment by alexcrichton** [comment]
Should be updated now

**Comment by alexcrichton** [comment]
Rebased

**Comment by Mark-Simulacrum** [comment]
I think we might be trying to put one of these crates into the rust-src component.

```
[00:02:43] thread 'main' panicked at 'fs::read_dir(src) failed with No such file or directory (os error 2)', /checkout/src/bootstrap/util.rs:82

```

**Comment by kennytm** [comment]
```
error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
  --> src\tools\compiletest\src\main.rs:21:1
   |
21 | extern crate getopts;
   | ^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(rustc_private)] to the crate attributes to enable
```

**Comment by oyvindln** [comment]
A bit late here, maybe I should have made an issue. Is using the "Default" compression level intended? the flate functions were changed to use a fast compression level some time ago (see #37298), going back to a higher compression setting may cause some performance regressions.

Also, the old functions didn't use a zlib wrapper from what I can see, but the new code seems to. Don't know if this could cause some issues when trying to use libs from different versions, though at least it adds 6 bytes of overhead due to the header and checksum.

**Comment by Mark-Simulacrum** [comment]
I'd file a new issue with those concerns (they seem good to address to me) since merged/closed PRs are low-visibility locations.

**Pull request merged**
