### PR TITLE
Permute `ThreadId` values

### PR DESCRIPTION
**Pull request by joboet**
[As discussed on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Stabilize.20.60ThreadId.3A.3Aas_u64.60), users should never rely on the value of `ThreadId`, so apply a simple permutation when generating ids to make it appear random.

`permute` was ported from https://www.gkbrk.com/wiki/avalanche-diagram/ by @Pointerbender. It is not and does not need to be cryptographically secure.

### CODE REVIEW

**Comment by joshtriplett** [comment]
I really don't think we should do this.

I personally continue to think we should expose the underlying OS thread ID value. But if we're *not* going to do that, and we're making up our own values, is there some fundamental reason we *should* do this?

**Comment by joboet** [comment]
> I personally continue to think we should expose the underlying OS thread ID value.

That would be a breaking change, since `ThreadId`s are guaranteed not to be reused, but e.g. `pthread_t` does not have that guarantee.

> But if we're _not_ going to do that, and we're making up our own values, is there some fundamental reason we _should_ do this?

If I understood the Zulip discussion correctly, it was proposed to do this to stop users from thinking that the id indicated the creating order of threads.

**Comment by the8472** [comment]
I on the other hand believe that this doesn't go far enough and the permutation should be seeded with a random value, similar to hashmap iteration order.

> But if we're not going to do that, and we're making up our own values, is there some fundamental reason we should do this?

The documentation says

> The returned value is entirely opaque – only equality testing is stable. Note that it is not guaranteed which values new threads will return, and this may change across Rust versions.

Using a randomized permutation ensures that nobody relies on the value by accident. E.g. storing things by threadid in a btreemap and then relying on iteration order or something like that.

**Comment by joshtriplett** [comment]
I don't think we should be treating users as adversaries like this.

**Comment by kennytm** [comment]
-1.

This is totally overkill to introduce a permutation function just to obfuscate the implementation detail that the thread IDs are distributed sequentially. I don't support anything more complicated than XOR-ing with some magic number.

**Comment by joboet** [comment]
To be honest, the more I think about it, the less I like this. Relying on the exact value of an id is a bug, and permuting them won't help users fix it more easily. Bugs because of randomness are just as hard to debug as bugs relying on operation ordering.

I'm keeping this PR up, in case T-libs decides to do this. Feel free to close it otherwise.

**Pull request closed without merging**
