### PR TITLE
only use fma intrinsics if `fma` is enabled

### PR DESCRIPTION
**Pull request by ghost**
Otherwise compute a * b + c.

### CODE REVIEW

**Comment by rkruppe** [comment]
Can you explain the motivation for this change? `intrinsics::fma32` does work without the "fma" target_feature (it emits a call to libm). If the motivation is performance, note that there are functional differences between a proper fma and `(x*y) + z`.

**Comment by s3bk** [comment]
The motivation here is indeed performance. LLVM does not optimize `a * b + c` into fma(a, b, c), so one has to use a.mul_add(b, c) to archive maximum performance on processors with `fma`.

This has the downside if the code is compiled without `fma` it calls into libm, which is not nessesary.

If one needs exact results, then f32 and f64 may not be ideal anyway. (I am trying to figure out the exact difference.)

**Comment by rkruppe** [comment]
> LLVM does not optimize a * b + c into fma(a, b, c)

Yeah, because that changes rounding and behavior on some non-finite inputs. Fast-math flags on the multiplication and addition are necessary to make this transformation valid. Conversely, without some opt-in from the programmer, silently turning fma(x, y, z) into (x * y) + z would also be in invalid "optimization" IMO.

> If one needs exact results, then f32 and f64 may not be ideal anyway. (I am trying to figure out the exact difference.)

It's not just about *exact* results, it's also about reasoning about how inexact the result is, and having particular behavior if an argument or the intermediate product is non-finite. For an example of the latter, consider `fma(MAX_FLT, MAX_FLT, NEG_INFINITY)` (evaluates to -inf) vs `(MAX_FLT * MAX_FLT) + NEG_INFINITY` (evaluates to NaN).

Furthermore, re: the former, even small changes in rounding can have far-reaching effects. For example, if `a == b` and you optimized the expression `sqrt(a * a - b * b)` into `sqrt(fma(a, a, -(b * b)))`, then (depending on the value of `a`) you can end up with a slightly negative argument to `sqrt`, causing it to return NaN instead of 0.

**Comment by s3bk** [comment]
Well. it looks my plan has been voided by target_feature. (And the fact that the docs of `mul_add` promises something different.)

**Pull request closed without merging**
