### PR TITLE
Bump bootstrap compiler to the new beta

### PR DESCRIPTION
**Pull request by tgross35**
Cherry pick the changes from https://github.com/rust-lang/rust/pull/128083, update the bump to the latest bootstrap that includes the backport https://github.com/rust-lang/rust/pull/128167, and fix a UI test.

Either https://github.com/rust-lang/rust/pull/128083 can be updated or this can be merged, no difference.

### CODE REVIEW

**Comment by tgross35** [comment]
Seems like canceling a try job requires a special incantation.

@bors try
@rustbot author

**Comment by jieyouxu** [comment]
> Seems like canceling a try job requires a special incantation.

AFAIK you can't cancel try jobs.

**Pull request closed without merging**
