### PR TITLE
[DO NOT MERGE] Forbid `unused_lifetimes` lint for Crater run

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by joshtriplett** [comment]
@Aaron1011 Cargo has been fixed now to no longer trigger `unused_lifetimes`, so we should give this another shot.

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

cc rust-lang/crater#590

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

Underlying failure should be addressed by https://github.com/rust-lang/crater/pull/596, but it's an intermittent failure.

**Comment by apiraino** [comment]
@Aaron1011 I've tried getting the context for this PR, is waiting for a review the actual status? thanks :)

**Comment by JohnCSimon** [comment]
@Aaron1011 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
