### PR TITLE
Remove some reexports in `rustc_middle`

### PR DESCRIPTION
**Pull request by Centril**
This will help get these imports out of the way of detecting the true dependencies in and out to `rustc_middle`, thereby helping future work towards https://github.com/rust-lang/rust/issues/65031.

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Centril** [comment]
CI says I forgot to fix some full-deps tests, will r=you once I'm done. =P

@bors r-

**Comment by Centril** [comment]
...and done, @bors r=Mark-Simulacrum

**Comment by Centril** [comment]
Argh... another test... will r=you soon again, @bors r-

**Pull request merged**
