### PR TITLE
crashes: more tests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
r? @jieyouxu

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks!

**Comment by jieyouxu** [comment]
r=me after CI is green

**Comment by jieyouxu** [comment]
I feel like #130687 is not a great crashes test, it probably wants its own decision about what to do in const-eval OOM situations and a dedicated test. I recommend removing this crashes test.

**Comment by matthiaskrgr** [comment]
marked the test as `//@ only-x86_64`
@rustbot ready

**Pull request merged**
