### PR TITLE
Stabilize const_ptr_offset

### LINKED ISSUE #71499: Tracking Issue for making ptr offset methods "const fn"
The feature gate for this is `#![feature(const_ptr_offset)]`. Miri has been able to handle this for some time. This feature allows code like:
```rust
static FOO: u8 = 42;
static PTR1: *const u8 = &FOO as *const u8;
static PTR2: *const u8 = PTR1.wrapping_offset(1);
```

- The following intrinsic functions will be made `const fn`:
  - [`intrinsics::offset`](https://doc.rust-lang.org/stable/core/intrinsics/fn.offset.html)
  - [`intrinsics::arith_offset`](https://doc.rust-lang.org/stable/core/intrinsics/fn.arith_offset.html)
- The allows the following `*const`/`*mut` methods to be `const fn`:
  - [`offset`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.offset)
  - [`wrapping_offset`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.wrapping_offset)
  - [`add`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.add)/[`sub`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.sub)
  - [`wrapping_add`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.wrapping_add)/[`wrapping_sub`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.wrapping_sub)

- The following methods are **not** part of this issue:
  - `align_offset`: See #62420
  - `offset_from`: Tracked as part of #41079 and https://github.com/rust-lang/rust/issues/92980
  - `wrapping_offset_from`: Not possible across different allocations
  - Any read/write methods: Tracked in #51911

### Steps (based on #69821)
- [x] Implemented in #71500
- [ ] Check if any other `core`/`alloc`/`std` functions should be made const along with this.
- [x] Remove[ miri's implementations for `offset` and `arith_offset`](https://github.com/rust-lang/miri/blob/52f5d202bdcfe8986f0615845f8d1647ab8a2c6a/src/shims/intrinsics.rs#L96-L112)
- [ ] Final commenting period (FCP): https://github.com/rust-lang/rust/issues/71499#issuecomment-1062913168
- [ ] Stabilization PR

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

### Unresolved Questions

-  How should `offset == 0` be handled?
   - As implemented, we allow offsets of 0 for all pointers (including dangling pointers) except for null pointers.
   - Should we allow offsets of 0 for null pointers?
   - The documentation is a bit unclear on this, see: #65108 and [@RalfJung's comment](https://github.com/rust-lang/rust/issues/65108#issuecomment-540076878)

CC: @RalfJung @oli-obk @rust-lang/wg-const-eval

### PR DESCRIPTION
**Pull request by SaltyKitkat**
Close #71499

### CODE REVIEW

**Comment by scottmcm** [comment]
The code here looks reasonable at a quick skim, but I don't see an FCP in the tracking issue, so reassigning to a libs-api member who can actually kick one off

r? rust-lang/libs

**Comment by SaltyKitkat** [comment]
Anything I can do to push forward?

**Comment by m-ou-se** [comment]
I've started the FCP process on the tracking issue: https://github.com/rust-lang/rust/issues/71499#issuecomment-1062913168

**Comment by dtolnay** [comment]
I bumped the `since = "1.60.0"` attributes to `since = "1.61.0"` since 1.60 has branched into beta already.

Thanks SaltyKitkat!

@bors r+

**Review by dtolnay — APPROVED** [review]

**Comment by Dylan-DPC** [comment]
failed in [rollup ci](https://github.com/rust-lang/rust/runs/5706210381)

@bors r-

**Comment by dtolnay** [comment]
That's a bug in rustc_passes as far as I can tell. `rustc_const_stable` attributes are not being handled correctly as library features by [compiler/rustc_passes/src/lib_features.rs](https://github.com/rust-lang/rust/blob/551b4fa395fa588d91cbecfb0cdfe1baa02670cf/compiler/rustc_passes/src/lib_features.rs). I'll put up a fix.

**Review by dtolnay — APPROVED** [review]

**Comment by RalfJung** [comment]
I only just noticed that we have a `rustc_allow_const_fn_unstable(const_mut_refs)` here. That's no good, this should not have been stabilized.

@rust-lang/libs-api in the future, when stabilizing anything with `rustc_allow_const_fn_unstable`, please let's make sure this is explicitly approved by at least @rust-lang/wg-const-eval.

**Pull request merged**
