### PR TITLE
Whitelist ARM thumb-mode (as "thumb")

### PR DESCRIPTION
**Pull request by hanna-kruppe**
Requested by @Lokathor, who also suggested naming it "thumb".

r? @gnzlbg

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage
@rkruppe @Lokathor 
Hello, this PR has sat idle for a week. Is this ready to move to review?
Thanks.

**Comment by Lokathor** [comment]
Well I'm not 100% clear on what "move to review" means in this context, but sure we can try and move forward.

I'll try to provide a bit of a summary:

---

There was some bikesheding on the name:

* Going by LLVM's name for target features (`rustc --print target-features --target TARGET`), the names are `thumb-mode` and also `thumb2`.
* Going by ARM's name for things, code is either ARM instructions that run in ARM _state_ or it's Thumb or Thumb2 instructions that run in Thumb _state_. They reserve the word _mode_ for the CPU privilege level.
* Apparently there's more modern `a32` and `t32` names as well.

Rust only lets you _enable_ features, you cannot _disable_ a feature. This change is very minimal and does not solve that problem at all. To take advantage of this change and have an intermixed ARM/Thumb program, you'd compile your code for an arm target which would have all code in ARM by default, and then you'd tag each function that you want to have thumb mode as being `#[cfg(target_feature_enable="+BIKESHED")]` (which also makes it `unsafe`). That's _not a good end state_, but it's progress, and it's also backwards compatible with the eventual goal of also being able to compile with Thumb as the default and then tag select functions being compiled using ARM.

**Comment by rkruppe** [comment]
re: A32/T32, the target feature this PR is about (`thumb-mode` in LLVM) only controls the older 16-bit-only "Thumb" instruction set (now sometimes called Thumb1 for clarity), not the more modern variable-length "Thumb2" instruction set which is also covered by the "T32" name. Though Thumb2 is backwards compatible with Thumb1, it is a substantial expansion and enabling Thumb2 would be inappropriate for use cases such as @Lokathor's where only Thumb1 is supported. Likewise, if we called this target-feature `t32`, that would be misleading to anyone reading statements like "ARMv7-M only supports the T32 instruction set" (i.e., you just use Thumb2 for everything, never the old A32 encoding) in Arm documents, which refer to Thumb2.

So whatever way the bikeshed goes, I don't want any part in relabeling `thumb-mode` as `t32`.

**Comment by rkruppe** [comment]
> To take advantage of this change and have an intermixed ARM/Thumb program, you'd compile your code for an arm target which would have all code in ARM by default, and then you'd tag each function that you want to have thumb mode [...]

For completeness, you can also compile some crates with `-C target-feature=+<whatever we call it>` which has less annotation burden in exchange for a slightly non-standard build setup.

**Comment by Amanieu** [comment]
The alternative is to add an ARM-specific function attribute `#[arm_state(arm|thumb)]`. This might be preferable since it seems that this doesn't really fit the existing feature system. However we will still want a `cfg!` to know whether the current target defaults Thumb or ARM.

**Comment by parched** [comment]
> re: A32/T32, the target feature this PR is about (`thumb-mode` in LLVM) only controls the older 16-bit-only "Thumb" instruction set (now sometimes called Thumb1 for clarity), not the more modern variable-length "Thumb2" instruction set which is also covered by the "T32" name. 

That's not quite true, it depends on which architecture version you're targeting. If you enable `thumb-mode` on an Armv4T target you will get 16 bit instructions but on an Armv7 target you will get 32 bit instructions (and 16 bit).

**Comment by gnzlbg** [comment]
> The alternative is to add an ARM-specific function attribute #[arm_state(arm|thumb)]. 

How is this different from `#[target_feature(enable = "arm|thumb")]` ?

**Comment by rkruppe** [comment]
> That's not quite true, it depends on which architecture version you're targeting. If you enable `thumb-mode` on an Armv4T target you will get 16 bit instructions but on an Armv7 target you will get 32 bit instructions (and 16 bit).

How sure are you that the actual meaning of the target-feature changes? I would have explained this observation by noting that an ARMv7 baseline already implies Thumb2 (so enabling Thumb1 is a nop).

**Comment by Amanieu** [comment]
> How is this different from `#[target_feature(enable = "arm|thumb")]` ?

The function wouldn't need to be marked `unsafe`.

**Comment by parched** [comment]
> How sure are you that the actual meaning of the target-feature changes? I would have explained this observation by noting that an ARMv7 baseline already implies Thumb2 (so enabling Thumb1 is a nop).

Because `+thumb2` does not imply `+thumb-mode`. `+thumb-mode` is the same as `__attribute__((target("thumb")))` in GCC. It changes which instruction set is used regardless of which features are enabled for that instruction set. See https://github.com/llvm-mirror/llvm/blob/482961ebd8a448188bd9a5671b73ba58ed916517/lib/Target/ARM/ARM.td#L19, it's separate from the sub-target features like `thumb2`.

**Comment by gnzlbg** [comment]
> The function wouldn't need to be marked unsafe.

That can be improved.

**Comment by rkruppe** [comment]
> Because `+thumb2` does not imply `+thumb-mode`. `+thumb-mode` is the same as `__attribute__((target("thumb")))` in GCC. It changes which instruction set is used regardless of which features are enabled for that instruction set. See https://github.com/llvm-mirror/llvm/blob/482961ebd8a448188bd9a5671b73ba58ed916517/lib/Target/ARM/ARM.td#L19, it's separate from the sub-target features like `thumb2`.

OK I already lost *entirely* too much time diving into the ARM backend over this, so I'll cut my losses here and just state that I'm confused as all hell.  This would all be so much easier to investigate by probing real C toolchains configured to build for various ARMv7 targets, but alas that would eat even more time. But here's the observation that initially lead me to my questioning, and further details I found which failed to remove my doubt:

[Thumb2 instructions](https://github.com/llvm/llvm-project/blob/26a475afe5cf9acf8dfe3e6cf8ebf1343ec3b72c/llvm/lib/Target/ARM/ARMInstrFormats.td#L1318) (as well as other stuff not going through that class, e.g. many `InstAlias`es) are guarded by [the `IsThumb2` predicate](https://github.com/llvm-mirror/llvm/blob/ffd5316983af6ab5e2654a0e6d47d9504eb0940f/lib/Target/ARM/ARMPredicates.td#L142), which is true [only if `thumb-mode` **and** `thumb2` subtarget features are enabled](https://github.com/llvm/llvm-project/blob/ddf5e86c222c6b5226be53e1250421fe608bb4d0/llvm/lib/Target/ARM/ARMSubtarget.h#L756). There is no TableGen predicate for "`thumb2` only" and indeed barely any mention of `FeatureThumb2` (or the corresponding C++ accessor, `ARMSubtarget::hasThumb2` -- in contrast with `isThumb2`) alone. So I can only conclude that `+thumb2,-thumb-mode` is at best a rather obscure configuration that forces A32 instructions by (accidentially?) excluding most or all of T32. Also note that T32-only targets such as [ARMv7M default to `+thumb-mode,+thumb2` as well as `FeatureNoArm`](https://github.com/llvm/llvm-project/blob/ddf5e86c222c6b5226be53e1250421fe608bb4d0/llvm/lib/Target/ARM/ARM.td#L696).

**Comment by parched** [comment]
`+thumb2,-thumb-mode` is the default for `armv7a-*` targets, it basically says generate ARM/A32 instructions but if you switch to Thumb/T32 state using  `__attribute__((target("thumb")))` in GCC/Clang, or whatever syntax we decide on here for rust, then generate Thumb-2 instructions.

**Comment by rkruppe** [comment]
Welp. Good to know I guess?

**Comment by JohnCSimon** [comment]
Ping from triage
@rkruppe I'm just here to push idle PRs. :)
What would you like to do with this?

**Comment by rkruppe** [comment]
I made this PR at the request of @Lokathor, naively hoping it would help get this feature in without much bikeshedding. That didn't work out, I am not invested enough to try to build a consensus around one option, and even if I was this PR probably wouldn't be the best venue for it. So I'll close this =/

**Pull request closed without merging**
