### PR TITLE
Improve wording of --target help

### PR DESCRIPTION
**Pull request by nagisa**

### CODE REVIEW

**Comment by alexcrichton** [comment]
I would personally like to not advertise custom target specs that much, they basically accidentally became stable at 1.0 and if the feature were to land now it would *definitely* be unstable. Perhaps that part can be elided?

**Comment by nagisa** [comment]
> accidentally became stable at 1.0 and if the feature were to land now it would definitely be unstable. Perhaps that part can be elided?

Lack of advertisement won’t make the feature go away, will it? Wanting it to be unstable now doesn’t sound like a good motivation for keeping it under wraps to me.

**Comment by huonw** [comment]
I would argue that they still are essentially unstable: most people who need them will also be forced to be using nightly for other reasons. The intention was certainly that they are unstable.

> Wanting it to be unstable now doesn’t sound like a good motivation for keeping it under wraps to me.

That does actually sound like a pretty good reason to not advertise it: no need to explicitly choose to exacerbate a mistake. This will make life easier if we choose to, for example, phase support out of the stable compiler.

**Comment by nagisa** [comment]
Removed the hints about being able to specify a path.

**Pull request merged**
