### PR TITLE
Make `overlapping_impls` not generic

### PR DESCRIPTION
**Pull request by camsteffen**
Trying to win back perf from #101632.

### CODE REVIEW

**Comment by estebank** [comment]
I'm inclined to merge as is, but the bootstrap timings are all red :-/

**Comment by camsteffen** [comment]
I'll take a closer look at this when I can. Ooh I hadn't noticed the bootstrap times 😤. I also need to fix the doc comment on the function if nothing else.

**Comment by lqd** [comment]
(Note that the diesel regressions are likely noise)

**Comment by camsteffen** [comment]
Could the bootstrap times also be an anomaly? Maybe run perf again to see?

**Comment by lqd** [comment]
It's possible, maybe unlikely, but bootstrap has some variance indeed. But sure, we can run it again and check. It won't hurt and the queue is empty.

@bors try @rust-timer queue

**Comment by lqd** [comment]
Looking good.

**Comment by camsteffen** [comment]
Okay, fixed the doc comment. Should be good to go!

**Comment by nnethercote** [comment]
`bitmaps` improvements are as expected and outweigh the reported regressions on secondary benchmarks, which might just be noise anyway.

@rustbot label: +perf-regression-triaged

**Pull request merged**
