### PR TITLE
Update rustc-guide

### LINKED ISSUE #66144: Broken links in rustbook
```
2019-11-06T06:59:02.8670425Z Error: there are broken links
2019-11-06T06:59:02.8671332Z 	Caused By: "https://doc.rust-lang.org/nightly/nightly-rustc/syntax/parse/struct.ParseSess.html" returned 404 Not Found
2019-11-06T06:59:02.8672064Z 	Caused By: "https://doc.rust-lang.org/nightly/nightly-rustc/syntax/parse/struct.ParseSess.html#method.buffer_lint" returned 404 Not Found
2019-11-06T06:59:02.8672681Z 	Caused By: "***/tree/master/src/libsyntax/ext/tt" returned 404 Not Found
2019-11-06T06:59:02.8673052Z 	Caused By: "https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ext/tt/macro_parser/" returned 404 Not Found
2019-11-06T06:59:02.8673395Z 	Caused By: "https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ext/tt/macro_parser/fn.parse.html" returned 404 Not Found
2019-11-06T06:59:02.8673720Z 	Caused By: "https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ext/tt/macro_rules/" returned 404 Not Found
2019-11-06T06:59:02.8674058Z 	Caused By: "https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ext/tt/macro_parser/" returned 404 Not Found
2019-11-06T06:59:02.8674372Z 	Caused By: "https://github.com/rust-lang/chalk/blob/master/src/test/wf.rs" returned 404 Not Found
2019-11-06T06:59:02.8674690Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/forest/struct.Forest.html" returned 404 Not Found
2019-11-06T06:59:02.8675055Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/struct.ExClause.html" returned 404 Not Found
2019-11-06T06:59:02.8675407Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/forest/struct.Forest.html#method.ensure_root_answer" returned 404 Not Found
2019-11-06T06:59:02.8675756Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/forest/struct.Forest.html#method.ensure_root_answer" returned 404 Not Found
2019-11-06T06:59:02.8676126Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/forest/struct.Forest.html#method.ensure_root_answer" returned 404 Not Found
2019-11-06T06:59:02.8677311Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/index.html" returned 404 Not Found
2019-11-06T06:59:02.8677703Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_parse/index.html" returned 404 Not Found
2019-11-06T06:59:02.8678018Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk_parse/ast/index.html" returned 404 Not Found
2019-11-06T06:59:02.8678349Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_rust_ir/index.html" returned 404 Not Found
2019-11-06T06:59:02.8678673Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_rust_ir/index.html" returned 404 Not Found
2019-11-06T06:59:02.8678992Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk/program/struct.Program.html" returned 404 Not Found
2019-11-06T06:59:02.8679284Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk_rust_ir/" returned 404 Not Found
2019-11-06T06:59:02.8679598Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_ir/index.html" returned 404 Not Found
2019-11-06T06:59:02.8679914Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_ir/enum.ProgramClause.html" returned 404 Not Found
2019-11-06T06:59:02.8680222Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk_ir/struct.Binders.html" returned 404 Not Found
2019-11-06T06:59:02.8680552Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk/program/struct.Program.html" returned 404 Not Found
2019-11-06T06:59:02.8681251Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk/program_environment/struct.ProgramEnvironment.html" returned 404 Not Found
2019-11-06T06:59:02.8681611Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_ir/enum.ProgramClause.html" returned 404 Not Found
2019-11-06T06:59:02.8682372Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_solve/index.html" returned 404 Not Found
2019-11-06T06:59:02.8682694Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_solve/index.html" returned 404 Not Found
2019-11-06T06:59:02.8682997Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk_solve/wf/index.html" returned 404 Not Found
2019-11-06T06:59:02.8683338Z 	Caused By: "http://rust-lang.github.io/chalk/doc/chalk_solve/coherence/index.html" returned 404 Not Found
2019-11-06T06:59:02.8683639Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_solve/index.html" returned 404 Not Found
2019-11-06T06:59:02.8683957Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/index.html" returned 404 Not Found
2019-11-06T06:59:02.8684293Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_rust_ir/index.html" returned 404 Not Found
2019-11-06T06:59:02.8684593Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_ir/index.html" returned 404 Not Found
2019-11-06T06:59:02.8684911Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_solve/index.html" returned 404 Not Found
2019-11-06T06:59:02.8685226Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_engine/context/index.html" returned 404 Not Found
2019-11-06T06:59:02.8685526Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk_parse/index.html" returned 404 Not Found
2019-11-06T06:59:02.8685842Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalk/index.html" returned 404 Not Found
2019-11-06T06:59:02.8686138Z 	Caused By: "https://rust-lang.github.io/chalk/doc/chalki/index.html" returned 404 Not Found
2019-11-06T06:59:02.8686464Z 	Caused By: "https://doc.rust-lang.org/nightly/nightly-rustc/syntax/parse/struct.ParseSess.html" returned 404 Not Found
2019-11-06T06:59:02.8692403Z 
2019-11-06T06:59:02.8692486Z 
2019-11-06T06:59:02.8693023Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rustbook" "linkcheck" "/checkout/src/doc/rustc-guide"
```

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @ehuss 

fix #66144

### CODE REVIEW

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/66218#issuecomment-551877625, @bors r-

**Comment by mark-i-m** [comment]
Oh, I thought we said we didn't want to rollup rustc-guide updates since they frequently break. In this case, the links changed yesterday. I have a PR up to fix them and will update this PR after that.

**Comment by mark-i-m** [comment]
@ehuss Updated

@Centril norullup please :heart: Sorry for the trouble.

**Pull request merged**
