### PR TITLE
tidy: Stop requiring a license header

### PR DESCRIPTION
**Pull request by joshtriplett**
Previously approved in rust-lang/rust#43498 ; update tidy to match.

### CODE REVIEW

**Comment by joshtriplett** [comment]
@Mark-Simulacrum Eventually, yes. But that has the same potential pitfalls as systematically running rustfmt. :)

**Comment by Mark-Simulacrum** [comment]
Agreed that disk space isn't a good reason, but I'm not sure I agree the pitfalls are all that bad. In theory, at least, I would expect this to have essentially 0 conflicts since no one is changing those lines, unlike rustfmt. Maybe I don't understand how git works though :)

**Review by mark-i-m — APPROVED** [review]
Thanks!

**Comment by mark-i-m** [comment]
I don't think git should complain much here. I don't mind starting on this if there are no objections.

**Comment by joshtriplett** [comment]
@Mark-Simulacrum The main annoyance would be that such a change would touch almost every file, making logs and browsing just that little bit more annoying.

But it wouldn't be that bad, true.

**Comment by mark-i-m** [comment]
@joshtriplett I submitted #53654. If that looks like a reasonable way to proceed, then I can do more. Let me know.

**Pull request merged**
