### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This backports the following PRs:

* ci: switch macOS builders to 10.15 #68863 
* Backport release notes of 1.41.1 #69468 
* Cherry-pick the LLVM fix for #69225 #69450 
* `lit_to_const`: gracefully bubble up type errors. #69330 
* [beta] bootstrap from 1.41.1 stable #69518 
* bootstrap: Configure cmake when building sanitizer runtimes #69104 

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@pietroalbini - that failure is probably related to the macos changes, mind taking a look? Did I miss a commit or something?

**Comment by pietroalbini** [comment]
@Mark-Simulacrum https://github.com/rust-lang/rust/pull/69104 needs to be backported as well.

**Comment by Mark-Simulacrum** [comment]
Thanks! Will do so in a bit.

**Comment by pietroalbini** [comment]
@bors retry

Spurious network failure.

**Pull request merged**
