### PR TITLE
Subtree update of `rust-analyzer`

### PR DESCRIPTION
**Pull request by lnicola**
r? @ghost

### CODE REVIEW

**Comment by lnicola** [comment]
CC @RalfJung

**Comment by lnicola** [comment]
I'm a bit worried about the extra commit causing issues, I'll wait for https://github.com/rust-lang/rust-analyzer/pull/17114.

**Comment by RalfJung** [comment]
With josh I have had extra commits like that several times without problems. It's just yet another commit that needs to be synced into the subrepo later.

With git subtree I can't tell.^^

**Comment by lnicola** [comment]
Never had issues with these and git-subtree (it's indeed just an extra commit), but it feels safer this way.

**Pull request closed without merging**
