### PR TITLE
Expand documentation of PathBuf, discussing lack of sanitization

### PR DESCRIPTION
**Pull request by ChrisJefferson**
Various methods in `PathBuf`, in particular `set_file_name` and `set_extension` accept strings which include path seperators (like `../../etc`). These methods just glue together strings, so you can end up with strange strings.

This isn't reasonable to change/fix at this point, and might not even be fixable, but I think should be documented. In particular, you probably shouldn't blindly build paths using strings given by possibly malicious users.

### CODE REVIEW

**Comment by tbu-** [comment]
I think it'd be better if we fixed this at least for `PathBuf::set_extension`, where I can't come up with a legitimate use case: #125070.

**Comment by workingjubilee** [comment]
I _think_ it's working-as-intended for the `set_file_name` cases.

**Comment by ChrisJefferson** [comment]
Just to say, I did send a message about this issue to security@rust-lang, before posting it, just in case it was deemed as a security issue, but after discussion I was told it wasn't considered a security issue.

I assumed possibly breaking existing code by adding panics would be considered a no-no, even when that code is doing some very silly things, but I have no idea what is acceptable.

**Comment by workingjubilee** [comment]
> I assumed possibly breaking existing code by adding panics would be considered a no-no, even when that code is doing some very silly things, but I have no idea what is acceptable.

We inject new panics all the time. We promise not to break _builds_, and mostly by preserving type signatures, and that's very different.

**Comment by tbu-** [comment]
Perhaps we (I?) could do a quick survey to see whether this is a used feature.

**Comment by Amanieu** [comment]
One concern we had was that making this function panic would allow arbitrary user input to cause a program to panic. This can be a problem e.g. in a network service, especially if there is code to validate the path *after* it has been formed with `set_filename`.

**Comment by tbu-** [comment]
> One concern we had was that making this function panic would allow arbitrary user input to cause a program to panic. This can be a problem e.g. in a network service,

I think a network service will likely contain panics to the connection level anyway, otherwise it'll likely be vulnerable to DoS.

**Comment by workingjubilee** [comment]
Based on the comments when initiating the FCP on the other function, here: https://github.com/rust-lang/rust/pull/125070#issuecomment-2112985376

> Though if we were confident that were not the case we'd love to do that too.

And the fact that, well, I think @tbu- has a good point, here, basically...

If @rust-lang/libs-api is willing, then I believe we should document the non-sanitizing behavior with an explicit note that `set_file_name` _may_ panic in the future. And we should suggest a pattern that clearly denotes the "yes, I know I am joining arbitrary paths together, possibly with 'hilarious' results". We might suggest, for instance, `path_buf.extend(path)` or `path.join(other_path)` for "yes, I am clearly adding a multi-part path" cases.

I believe this is the sort of commentary in the documentation that will eventually provoke feedback and inform whether we should zig... er, not the programming language... or zag.

**Comment by BurntSushi** [comment]
@workingjubilee I think that's a good idea. It might also be worth adding fallible variants of these routines. I imagine in some cases, the inputs to these routines will come directly from end users. And in those cases, using a fallible routine is probably what you want.

**Comment by workingjubilee** [comment]
Neat.

Also @ChrisJefferson I realize that feedback is slightly open-ended so all it really needs is the note about "`set_file_name` may panic in the future, if you wanna punt on some of it feel free to open an issue and I'll look at getting that sorted Eventually™.

**Comment by ChrisJefferson** [comment]
I think I've made the required tweaks, but if it's not right, I'm happy for someone to just chuck this / write their own, which I realise might be quicker than tweaking my PR via me!

**Comment by workingjubilee** [comment]
Just needed a rebase and a typo fix.

@bors r+ rollup

**Pull request merged**
