### PR TITLE
add some docs to `From` conversions

### PR DESCRIPTION
**Pull request by llogiq**
This adds a helpful document to the bool → int* conversions as well as to the lossless integer conversions.

One of #51430 down, some more to go.

### CODE REVIEW

**Comment by TimNN** [comment]
Did you build the docs locally to verify that the `stringify!` / `concat!` works as expected?

If so R=me.

**Comment by llogiq** [comment]
Actually my build failed because I had activated --debuginfo-lines and it couldn't find gdb for some reason. I think I've now fixed that issues and am resuming the build now.

**Comment by llogiq** [comment]
docs built successfully.

@bors r=TimNN

**Pull request merged**
