### PR TITLE
Use less `catch_unwind` in `lang_start_internal`

### PR DESCRIPTION
**Pull request by joboet**
~~Moving abort guards to destructors can yield better codegen than `catch_unwind` in user code, so perhaps it also works for `lang_start`?~~

~~Could someone trigger rust-timer for me, please? I don't have permissions.~~

Using an aborting drop guard to stop unwinding is a bit cleaner and avoids the footguns associated with `catch_unwind`. 

The impact on binary size is unfortunately negligible (-4kB on my machine for "hello world").

### CODE REVIEW

**Comment by Nilstrieb** [comment]
I don't think rustc perf will have any useful results, the compiler is a very big program so this small one time startup change will probably not make it over the noise threshold. You're probably better off benchmarking a hello world or something like that locally.

**Comment by joboet** [comment]
> I don't think rustc perf will have any useful results, the compiler is a very big program so this small one time startup change will probably not make it over the noise threshold. You're probably better off benchmarking a hello world or something like that locally.

`lang_start` did previously have a perf-impact (#88988), so I'm curious whether it does here as well. But sure, I'll test it locally first.

**Comment by Nilstrieb** [comment]
Well, I can start one anyways, we have enough
@bors try @rust-timer queue

**Comment by joboet** [comment]
@rustbot author
Until I figure out CI...

**Comment by JohnCSimon** [comment]
@joboet 

ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Pull request closed without merging**
