### PR TITLE
Re-enable Redox builder (take 2)

### LINKED ISSUE #63160: Redox builder is temporarily disabled
#61393 temporarily disables the redox builder, this issue tracks re-enabling it.

cc @jackpot51

### PR DESCRIPTION
**Pull request by newpavlov**
Closes: #63160

### CODE REVIEW

**Comment by josephlr** [comment]
Looks like the build breakage is caused by an incorrect use of `cfg` [here](https://github.com/rust-lang/rust/blob/f86521e0a33a2b54c4c23dbfc5250013f7a33b11/src/libstd/sys/unix/process/process_unix.rs#L186-L196). It still compiles `libc::setgroup` even though it does not use it.

I have a fix I'm working on

**Comment by newpavlov** [comment]
I think I've fixed this cfg.

**Pull request merged**
