### PR TITLE
Refactor tools/build-mainfest

### PR DESCRIPTION
**Pull request by Centril**
I saw some duplication in https://github.com/rust-lang/rust/pull/58990 and got an itch... Will likely need to be rebased when that lands. Hopefully the PR should have zero semantic changes...

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
We unfortunately don't have a lot of testing for this, so can you confirm you've built and run this locally in simple scenarios to make sure nothing is accidentally broken? Otherwise the refactorings look good to me, thanks!

**Comment by Centril** [comment]
@alexcrichton Following the instructions in the [README](https://github.com/rust-lang/rust/blob/72b7d0f999dabf407bba16fa10b5fd64f17d7d23/src/tools/build-manifest/README.md) seems to give the right structure for things. I reran the instructions on master and compared the diffs which produced no changes.

**Comment by Centril** [comment]
@alexcrichton Rebased; should be good to go now.

**Comment by alexcrichton** [comment]
@bors: r+

:+1:

**Pull request merged**
