### PR TITLE
rustdoc rfc#3662 changes under unstable flags

### PR DESCRIPTION
**Pull request by EtomicBomb**
* All new functionality is under unstable options
* Adds `--merge=shared|none|finalize` flags
* Adds `--parts-out-dir=<crate specific directory>` for `--merge=none`
to write cross-crate info file for a single crate
* Adds `--include-parts-dir=<previously specified directory>` for
`--merge=finalize` to write cross-crate info files
* `tests/rustdoc/` tests for the new flags

### CODE REVIEW

**Comment by EtomicBomb** [comment]
Just updated `tests/run-make/rustdoc-default-output/output-default.stdout` test to fix the x86_64-gnu-llvm-17 failure.

**Review by notriddle — APPROVED** [review]
This code basically looks fine. I have no complaints about merging it as-is.

However, it would be a good idea to add a guide to the [rustdoc book](https://doc.rust-lang.org/nightly/rustdoc/). That can be done after merging this.

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang-ci/rust/actions/runs/10761390746/job/29840547309#step:25:7606

**Comment by matthiaskrgr** [comment]
mmh looks like this is caused by something else..
@bors r=notriddle

**Pull request merged**
