### PR TITLE
fix null pointer error messages

### LINKED ISSUE #85027: `miri` no longer builds after rust-lang/rust#85022
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#85022, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @JohnTitor, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by RalfJung**
I got the `match` in https://github.com/rust-lang/rust/pull/84972 wrong, this fixes that.
Also avoid redundant "inbounds test failed:" prefix.

Should fix https://github.com/rust-lang/rust/issues/85027

r? @oli-obk

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
@RalfJung if you are r-'g a pr that's in a rollup, ensure that the rollup is r-'d as well :) thanks

**Comment by RalfJung** [comment]
@Dylan-DPC sorry, I got the red CI email while being in a meeting so I didn't have time to read over the log in this issue so I missed the fact that this was rolled up...

@bors r=oli-obk

**Pull request merged**
