### PR TITLE
rustdoc doctest: include signal number in exit status

### PR DESCRIPTION
**Pull request by notriddle**
Related to #95601

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Comment by notriddle** [comment]
@GuillaumeGomez it looks like @ bors didn’t hear you.

**Comment by notriddle** [comment]
r? @GuillaumeGomez 

Submitted a fixed version of this thing for Windows, which now produces very subtly different output.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
