### PR TITLE
Strip debuginfo from rustc-main and rustdoc

### PR DESCRIPTION
**Pull request by clubby789**
r? @Kobzol 
Split from #134690

### CODE REVIEW

**Comment by Kobzol** [comment]
> as we use DebuginfoLevel::Limited (the level below this) in dist-x86_64

Really? That sounds surprising to me, could you please point me to the place where this is configured? We should be using debuginfo for the standard library, but not for the compiler itself.

..thinking a bit more about this, I wonder if for `rustc` we should just strip unconditionally, because that binary really contains almost no code (and should not contain any debuggable code, anyway, unless someone would want to debug jemalloc). On the other hand, rustdoc contains a lot of custom code, so for it my previous remark stands.

**Comment by clubby789** [comment]
In `config.example.toml`
```toml
#debuginfo-level = if rust.debug { 1 } else { 0 }

# Debuginfo level for the compiler.
#debuginfo-level-rustc = rust.debuginfo-level

# Debuginfo level for the standard library.
#debuginfo-level-std = rust.debuginfo-level

# Debuginfo level for the tools.
#debuginfo-level-tools = rust.debuginfo-level
```
We `--set rust.debug=true` in dist-x86_64-linux => `rust.debuginfo-level = 1` => debuginfo level for rustc, std, and tools is set to 1; https://github.com/rust-lang/rust/blob/19e75f4fb3f960267996e8788459e97b8769aac7/src/bootstrap/src/core/config/config.rs#L105 deserializes 1 as `Limited`

---

Gating the rustdoc strip makes sense in that case; it's only a 20% increase anyway. Maybe in future we can look at reducing the debuginfo generated by jemalloc itself

**Comment by Kobzol** [comment]
Ah, I was wondering if you mean this. Sorry for the confusion :sweat_smile: But the `--set rust.debug=true` call is there only for building the `opt-dist` tool itself, to provide better backtraces if `opt-dist` panics. It is not used for the actual build of the compiler (`python3 ../x.py dist --host $HOSTS --target $HOSTS ...`).

**Comment by clubby789** [comment]
Ah 😄 Got it

**Comment by clubby789** [comment]
I think it's best if we only strip rustc-main when debuginfo is off - dist is the only place it *really* matters, and if someone needs to debug jemalloc inside rustc-main then we shouldn't confuse them by removing their requested debuginfo

**Comment by clubby789** [comment]
```
$ ls -lh $(rustc --print sysroot)/bin/{rustc,rustdoc}
-rwxr-xr-x 1 jamie jamie 2.0M Dec  6 09:32 ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc
-rwxr-xr-x 1 jamie jamie  16M Dec  6 09:32 ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustdoc
$ ls -lh $(rustc +48eebccf201050ba448b73397c277b5258fcf350 --print sysroot)/bin/{rustc,rustdoc}
-rwxr-xr-x 1 jamie jamie 383K Dec 27 08:59 ~/.rustup/toolchains/48eebccf201050ba448b73397c277b5258fcf350/bin/rustc
-rwxr-xr-x 1 jamie jamie  12M Dec 27 08:59 ~/.rustup/toolchains/48eebccf201050ba448b73397c277b5258fcf350/bin/rustdoc
```

**Pull request merged**
