### PR TITLE
Fix x86_64 code being produced for bare-metal LoongArch targets' `compiler_builtins`

### LINKED ISSUE #125908: Invalid `compiler_builtins` produced for `loongarch64-unknown-none`
When downloading the `loongarch64-unknown-none` (and `softfloat` variant) target, the `compiler_builtins` that ships with the compiler is broken:
```
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="<redacted>" VSLANG="1033" "rust-lld" "-flavor" "gnu" "/tmp/rustca1ZUz1/symbols.o" "/tmp/example/target/loongarch64-unknown-none-softfloat/debug/deps/example-43ca1a05d5214464.2dsfu9v1nhu5h7yb.rcgu.o" "--as-needed" "-L" "/tmp/example/target/loongarch64-unknown-none-softfloat/debug/deps" "-L" "/tmp/example/target/debug/deps" "-L" "/tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib" "-Bstatic" "/tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/librustc_std_workspace_core-a66f3359610045a1.rlib" "/tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcore-fd043e39f63b431a.rlib" "/tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib" "-Bdynamic" "--eh-frame-hdr" "-z" "noexecstack" "-L" "/tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib" "-o" "/tmp/example/target/loongarch64-unknown-none-softfloat/debug/deps/example-43ca1a05d5214464" "--gc-sections"
  = note: rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-absvdi2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-absvsi2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-absvti2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-addvdi3.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-addvsi3.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-addvti3.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-clzdi2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-clzsi2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-clzti2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-cmpdi2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-cmpti2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-ctzdi2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-ctzsi2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-ctzti2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-divdc3.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-divsc3.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-extendhfsf2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-ffsti2.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-int_util.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: /tmp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/loongarch64-unknown-none-softfloat/lib/libcompiler_builtins-811e50dbc3f2e3d8.rlib(45c91108d938afe8-muldc3.o) is incompatible with /tmp/rustca1ZUz1/symbols.o
          rust-lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
```

Upon further inspection, the `compiler_builtins` symbols are indeed built for x86-64 and not LoongArch:

```
$ file 45c91108d938afe8-muldc3.o
45c91108d938afe8-muldc3.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), with debug_info, not stripped
```

It's not clear what causes this, but https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/dist-various-2/Dockerfile#L33 contains no corresponding definitions for `CC_`.

This issue appears related, in that it would catch whatever causes this: https://github.com/rust-lang/rust/issues/111142

### PR DESCRIPTION
**Pull request by xen0n**
Formerly the `loongarch*-*-none*` targets were added to the `dist-various-2` CI job, but no corresponding toolchain was added along with them. This meant the `compiler_builtins` for the targets were built with the host toolchain.

As the other `dist-various` toolchains are mostly pre-built so far, to avoid burdening them with crosstool-ng builds, simply move the two bare-metal LoongArch targets to the `dist-loongarch64-linux` job which has a ready-to-use LoongArch toolchain. With the proper CFLAGS applied it is possible to build artifacts suitable for bare-metal. I verified that the `compiler_builtins` objects are now correctly produced regarding architecture and ABI, with the changes here applied.

Fixes #125908.

cc @heiher

try-job: dist-loongarch64-linux
try-job: dist-various-2

### CODE REVIEW

**Comment by xen0n** [comment]
(Again) I'll need someone to trigger a try build for the PR, thanks in advance!

**Comment by xen0n** [comment]
The CI artifacts are correct as well:

```
libcompiler_builtins-01ecf15d7725de80.rlib(45c91108d938afe8-muldc3.o):  file format elf64-loongarch

Disassembly of section .text.__muldc3:

0000000000000000 <__muldc3>:
       0: 27 0c 05 01   fmul.d  $fa7, $fa1, $fa3
       4: 06 08 05 01   fmul.d  $fa6, $fa0, $fa2
       8: 09 0c 05 01   fmul.d  $ft1, $fa0, $fa3
       c: 48 04 05 01   fmul.d  $ft0, $fa2, $fa1
...
```

```
libcompiler_builtins-470063ddd93ab668.rlib(45c91108d938afe8-muldc3.o):  file format elf64-loongarch

Disassembly of section .text.__muldc3:

0000000000000000 <__muldc3>:
       0: 63 00 fe 02   addi.d  $sp, $sp, -128
       4: 77 a0 c1 29   st.d    $s0, $sp, 104
       8: b7 00 15 00   move    $s0, $a1
       c: c5 00 15 00   move    $a1, $a2
...
```

The ABI is again correct. I've checked all the other rlibs too and all objects are properly LoongArch.

**Comment by workingjubilee** [comment]
Thanks for cleaning this up!

**Pull request merged**
