### PR TITLE
Remove the return_address intrinsic.

### PR DESCRIPTION
**Pull request by eddyb**
This intrinsic to get the return pointer was introduced in #16248 / #16081 by @pcwalton for Servo.
However, as explained in #34227, it's impossible to ensure it's used correctly, and it broke with `-Zorbit`.

Servo's usage is being replaced in servo/servo#11872, and I expect nobody else to have abused it.
But I've also started a crater run, just in case this is a `[breaking-change]` for anyone else.

### CODE REVIEW

**Comment by nagisa** [comment]
r=me provided crater is happy. In case it isn’t we may want to introduce a cycle of warning instead?

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/d7bb312273b2be37d5d87d4aaa4c78f6) shows 0 regressions.

@bors r=nagisa

**Comment by aturon** [comment]
I'm surprised this went through without more (apparent) approval from stakeholders. I realize that there's work underway to move Servo off this intrinsic, but until that work lands, doesn't this effectively break Servo? We are usually much more careful about breaking production uses of Rust, and something like this would usually merit at least a ping to @rust-lang/compiler and @rust-lang/lang. But maybe everyone is in the loop through other forums?

cc @Manishearth @metajack @jdm -- just want to make sure you're aware of and OK with taking this step prior to actually landing the requisite changes in Servo.

**Comment by jdm** [comment]
My preference would be to revert this until we've finished removing its usage from Servo.

**Comment by nagisa** [comment]
I was under impression that https://github.com/servo/servo/pull/11872 has landed but apparently it didn’t.

To my knowledge, though, servo doesn’t use the most recent nightly anyway and the Servo’s PR seems to land in near future?

**Comment by Manishearth** [comment]
I was somewhat aware of this (bit too late though). I am sort of okay with this landing because Servo pins anyway and we can delay a rustup for a week or two (indeed, we usually don't rustup in that timeframe anyway). Hopefully the servo PR lands and works without issues.

Reverting is also okay by me. AIUI this isn't blocking anything.

**Comment by jdm** [comment]
I would rather not rush the review of the Servo change, and I would also like to avoid any potential of blocking anybody who needs to update Servo's Rust version while the review is in progress.

**Comment by nikomatsakis** [comment]
Note PR to revert here https://github.com/rust-lang/rust/pull/34580

**Pull request merged**
