### PR TITLE
Tweak `consts_may_unify`

### PR DESCRIPTION
**Pull request by nnethercote**
r? @lcnr

### CODE REVIEW

**Comment by nnethercote** [comment]
Interesting: this was a win locally on `typenum` and `bitmaps`, but maybe PGO already does this inlining for us.

**Comment by nnethercote** [comment]
I was hoping for a speed win, which didn't happen. But this small cleanup is probably still worth merging.

**Comment by lcnr** [comment]
yeah, it's an improvement even when ignoring perf 👍 

@bors r+

**Pull request merged**
