### PR TITLE
libterm: port changes from term, refactor unwraps() into pattern matches

### PR DESCRIPTION
**Pull request by SingingTree**
This removes a number of instances of unwrap and replaces them with
pattern matching.

This is in response to rust issue #29992.

### CODE REVIEW

**Comment by SingingTree** [comment]
This doesn't remove all usages of unwap(), I've left in some where I think using pattern matching doesn't simplify the code, or would make it more verbose (extra indentation levels, for example). Please advise as to if further instances should be removed.

**Comment by oli-obk** [comment]
This looks like a very recurring pattern. Maybe all single pop and dual pop arms should simply call into another function where they are matched on again, but the single/dual pop is done once and the values can be used directly in the arms.

**Comment by bluss** [comment]
This is originally the same code as [term](https://crates.io/crates/term), but they are drifting apart. It's unfortunate, this is an example of double work, since term has already merged a change called “avoid unwrap”.

**Comment by SingingTree** [comment]
Interesting, I was unaware of where this originated. I'll rework this to use the same format as term.

**Comment by SingingTree** [comment]
Cheers @oli-obk and @bluss, I've updated this PR to be more in line with the changes made to term, which should also cut down on much of the duplication that was present.

I've left in a TODO (now a FIXME) from the term code on line 122, as it appears there should be some bound checking here (please correct me if not), but that seems outside the scope of this.

**Comment by Stebalien** [comment]
@SingingTree, there (probably) shouldn't be any bounds checking as ncurses doesn't have any (although, to be fair, ncurses doesn't do much type checking of variables at all...).

**Comment by Stebalien** [comment]
Also, I recommend you just import all of term as is as I've made a few bug fixes (most importantly, the format string code now obeys the spec).

**Comment by SingingTree** [comment]
Sure thing, I will amend this to reflect changes made to term.

I was unaware of the status of libterm and term (for anyone reading this who isn't aware, these were useful refs for me: https://github.com/rust-lang/rust/pull/26042, https://internals.rust-lang.org/t/submodules-in-rust-lang-rust-for-external-repositories/2200).

**Comment by SingingTree** [comment]
I've been messing around with bringing changes across, however I see that win.rs now uses the winapi and kernel32 crates. Let me know if I'm incorrect, but my thinking is that since these aren't part of the rust src, I can't use them as deps in libterm. Is this correct?

I'm continuing on with the refactor, which means I've had to gut some of the new functionality. Sound like a reasonable course of action?

**Comment by SingingTree** [comment]
11a1fa6 reflects my current efforts at bringing across the term changes. I'd like to have another look at it to make sure I haven't done anything silly, so consider it currently a WIP.

**Comment by alexcrichton** [comment]
This seems like it's steadily growing in scope over time, so I'm curious to take a step back for a second with a few questions:

* Is this fixing bugs for the in-tree libterm? Or did it just start as a refactoring?
* Are there fixes which need to go upstream to the external term?

I hope to soon have a branch to at least start out building the compiler with Cargo at which point integration with the upstream libterm should be much easier, so I'm a little wary to put a lot of effort into the internal libterm if it's largely just refactorings (e.g. just a bunch of extra churn)

**Comment by SingingTree** [comment]
It did indeed start as refactoring to remove unwraps, similar to the changes made here https://github.com/Stebalien/term/commit/a82086b9084a7d54a836d087fbc5a3ec0bc40212. Based on @Stebalien comment to bring across some of the other fixes made in term this has grown in scope. This should bring in a number of other changes and fixes from term such as those in https://github.com/Stebalien/term/commit/c62def53fbe3808ab14c4e382493afcd80879675 and https://github.com/rust-lang/rust/commit/11a1fa6a1882bace9c02d3c52ad8468f2fe95236.

Nothing from this should go upstream to term, it should all be alterations already made in term. There is some ugliness in terms of not all of the changes being able to be brought across (due to cargo deps; mainly the Terminal trait hasn't got all its new functionality), so this is a combination of the old libterm and new changes from term.

**Comment by alexcrichton** [comment]
Ok, in that case this is probably fine to merge for now and we can deal with using an upstream version later on. In the meantime this doesn't set us backwards either way!

Could you squash the commits down into one commit?

**Comment by SingingTree** [comment]
Will do.

**Comment by nikomatsakis** [comment]
Seems good to me. I'm inclined to r+ but I'm not really familiar with this code. I'd love to see @Stebalien give this a once over.

**Comment by Stebalien** [comment]
LGTM (I've ready the changes but haven't tested them). I noticed that `terminfo/searcher.rs` hasn't been ported but that's not really important.

**Comment by SingingTree** [comment]
Huh, I thought I got the searcher changes. I'll bring them in also and update this.

**Comment by alexcrichton** [comment]
@bors: r+ 0ee230a09453451791105670aab769464c4a9270

Thanks!

**Pull request merged**
