### PR TITLE
Stabilize `custom_code_classes_in_docs` feature

### LINKED ISSUE #79483: Tracking Issue for user-provided classnames in fenced code blocks
The feature gate for the issue is `#![feature(user_classes_in_docs)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the feature
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

### Implementation history

- Feature implementation, WIP: #79454

@rustbot label T-rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #79483.

This feature has been around for quite some time now, I think it's fine to stabilize it now.

## What is the feature about?

In short, this PR changes two things, both related to codeblocks in doc comments in Rust documentation:

 * Allow to disable generation of `language-*` CSS classes with the `custom` attribute.
 * Add your own CSS classes to a code block so that you can use other tools to highlight them.

#### The `custom` attribute

Let's start with the new `custom` attribute: it will disable the generation of the `language-*` CSS class on the generated HTML code block. For example:

```rust
/// ```custom,c
/// int main(void) {
///     return 0;
/// }
/// ```
```

The generated HTML code block will not have `class="language-c"` because the `custom` attribute has been set. The `custom` attribute becomes especially useful with the other thing added by this feature: adding your own CSS classes.

#### Adding your own CSS classes

The second part of this feature is to allow users to add CSS classes themselves so that they can then add a JS library which will do it (like `highlight.js` or `prism.js`), allowing to support highlighting for other languages than Rust without increasing burden on rustdoc. To disable the automatic `language-*` CSS class generation, you need to use the `custom` attribute as well.

This allow users to write the following:

```rust
/// Some code block with `{class=language-c}` as the language string.
///
/// ```custom,{class=language-c}
/// int main(void) {
///     return 0;
/// }
/// ```
fn main() {}
```

This will notably produce the following HTML:

```html
<pre class="language-c">
int main(void) {
    return 0;
}</pre>
```

Instead of:

```html
<pre class="rust rust-example-rendered">
<span class="ident">int</span> <span class="ident">main</span>(<span class="ident">void</span>) {
    <span class="kw">return</span> <span class="number">0</span>;
}
</pre>
```

To be noted, we could have written `{.language-c}` to achieve the same result. `.` and `class=` have the same effect.

One last syntax point: content between parens (`(like this)`) is now considered as comment and is not taken into account at all.

In addition to this, I added an `unknown` field into `LangString` (the parsed code block "attribute") because of cases like this:

```rust
/// ```custom,class:language-c
/// main;
/// ```
pub fn foo() {}
```

Without this `unknown` field, it would generate in the DOM: `<pre class="language-class:language-c language-c">`, which is quite bad. So instead, it now stores all unknown tags into the `unknown` field and use the first one as "language". So in this case, since there is no unknown tag, it'll simply generate `<pre class="language-c">`. I added tests to cover this.

EDIT(camelid): This description is out-of-date. Using `custom,class:language-c` will generate the output `<pre class="language-class:language-c">` as would be expected; it treats `class:language-c` as just the name of a language (similar to the langstring `c` or `js` or what have you) since it does not use the designed class syntax.

Finally, I added a parser for the codeblock attributes to make it much easier to maintain. It'll be pretty easy to extend.

As to why this syntax for adding attributes was picked: it's [Pandoc's syntax](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes). Even if it seems clunkier in some cases, it's extensible, and most third-party Markdown renderers are smart enough to ignore Pandoc's brace-delimited attributes (from [this comment](https://github.com/rust-lang/rust/pull/110800#issuecomment-1522044456)).

r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Wow, didn't pay attention but that's a lot of removed lines. :D

**Comment by GuillaumeGomez** [comment]
Hum, why is the compiler team part of this? Because of the feature in the compiler source maybe?

**Comment by compiler-errors** [comment]
@rfcbot fcp cancel

Autotagged. I don't think the compiler needs to participate in this.

**Comment by compiler-errors** [comment]
Please start a new one @GuillaumeGomez or @notriddle

**Comment by GuillaumeGomez** [comment]
Oh it's based on PR's tags and not the source code. Noted. Thanks compiler-errors!

@rfcbot fcp merge

**Comment by camelid** [comment]
Do you mind posting a brief summary of the feature as it currently stands? It seems there was a lot of back-and-forth over things like syntax in the implementation PR.

**Comment by GuillaumeGomez** [comment]
Good point! Having a summary will be a nice addition. Should have thought about it... (The first comment of the original PR was up-to-date but it's better to have it here as well)

**Comment by camelid** [comment]
@rfcbot concern syntax complexity

This seems good overall, but a couple comments:

1. Is there any particular reason for supporting both `{class=foo}` and `{.foo}`? It seems like Pandoc only supports the second variant, so unless there's a strong reason to support both, it might be better to keep it simple.
2. Do you mind elaborating on the purpose of tracking "unknown tags"? In the case of `custom,class:language-c`, that seems like a syntax error that should be reported as such, since the only supported syntax is `{.foo}` (and `{class=foo}` if we decide to keep that).

**Comment by camelid** [comment]
> [Pandoc supports both variants](https://pandoc.org/try/?params=%7B%22text%22%3A%22%60%60%60rust+%7Bclass%3Dfoo+.bar%7D%5Cnfn+main%28%29+%7B%7D%5Cn%60%60%60%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D).

Thanks, I didn't see that in the docs. 👍 

> https://github.com/rust-lang/rust/issues/115938 / https://github.com/rust-lang/rust/pull/115947#issuecomment-1724361386

Hmm, I'm still unclear on how this relates to the `custom,class:language-c` example given above. I agree that we should support `ASN.1`, but based on the PR's description, it seems to also add support for `class:foo` as syntax that adds a class, in addition to `{class=foo}` and `{.foo}`. Am I misunderstanding?

**Comment by camelid** [comment]
> It doesn't add `class:foo` as syntax that adds a class. It's just a bareword, the same as `ASN.1`. The colon isn't special syntax at all. The PR description with that example is outdated.

Ah, I see. I tested it locally and see what you mean. I'll update the PR's description.

@rfcbot resolve syntax complexity

**Comment by decathorpe** [comment]
This PR seems to have caused a regression (or at least a possibly unexpected behaviour change) that affects a large-ish number of crates - previously, code block attributes that were not recognized as "rust code" in some way were ignored and not compiled, but now "invalid" code block attributes raise a new rustdoc warning lint, but *are* compiled (and run) as Rust code.

For example, the code blocks here use `{rust,ignore}` instead of `rust,ignore` - they were previously ignored, but are now attempted to be compiled + run:

https://github.com/servo/rust-cssparser/blob/main/src/lib.rs#L44-L64

I noticed this because the CI we have for Fedora packages started to turn red for 2-3 dozen Rust crates after Rust 1.80 landed a few days ago.

Was this behaviour change intentional? While I agree that it is likely a good idea to warn on "invalid" or unrecognized code block attributes, attempting to compile + run code blocks with unrecognized attributes might not be.

**Pull request merged**
