### PR TITLE
Clippy subtree update

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth 

Really delayed sync (2 1/2 weeks), because of a `debug_assertion` we hit, and I didn't have the time to investigate earlier.

It would be nice to merge this PR with some priority, as it includes a lot of formatting changes due to the rustfmt bump.

Include Cargo.lock update due to Clippy version bump and ui_test bump in Clippy.

### CODE REVIEW

**Comment by Manishearth** [comment]
Tidy fails

**Comment by flip1995** [comment]
Oh wow, python linting in the tidy check. I fixed the issue :+1:

**Pull request merged**
