### PR TITLE
Update rustfmt and RLS

### PR DESCRIPTION
**Pull request by kennytm**

### CODE REVIEW

**Comment by kennytm** [comment]
RLS is still `build-fail`, investigating.

**Comment by kennytm** [comment]
I'm afraid we also need a `racer 2.1.2` to update `rustc-ap-syntax` from 203 to 209.

**Comment by kennytm** [comment]
r? @nrc 

Currently blocked by:

1. racer-rust/racer#911, and a new `racer` release (2.1.2 or above)
2. `rls-vfs` to release a version to crates.io (0.4.6 or above)
3. rust-lang-nursery/rustfmt#2865
4. (after all of above is done) rust-lang-nursery/rls#960

**Comment by kennytm** [comment]
RLS is still test-fail, will check later

<details>

```
[01:21:27] failures:
[01:21:27] 
[01:21:27] ---- [ui] ui/redundant_field_names.rs stdout ----
[01:21:27] normalized stderr:
[01:21:27] error[E0464]: multiple matching crates for `derive_new`
[01:21:27]  --> $DIR/redundant_field_names.rs:6:1
[01:21:27]   |
[01:21:27] 6 | extern crate derive_new;
[01:21:27]   | ^^^^^^^^^^^^^^^^^^^^^^^^
[01:21:27]   |
[01:21:27]   = note: candidates:
[01:21:27]           crate `derive_new`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-24d68d6f9f8be909.so
[01:21:27]           crate `derive_new`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-cc2a0602cb5c0153.so
[01:21:27] 
[01:21:27] error[E0463]: can't find crate for `derive_new`
[01:21:27]  --> $DIR/redundant_field_names.rs:6:1
[01:21:27]   |
[01:21:27] 6 | extern crate derive_new;
[01:21:27]   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
[01:21:27] 
[01:21:27] error: aborting due to 2 previous errors
[01:21:27] 
[01:21:27] Some errors occurred: E0463, E0464.
[01:21:27] For more information about an error, try `rustc --explain E0463`.
[01:21:27] 
[01:21:27] 
[01:21:27] expected stderr:
[01:21:27] error: redundant field names in struct initialization
[01:21:27]   --> $DIR/redundant_field_names.rs:34:9
[01:21:27]    |
[01:21:27] 34 |         gender: gender,
[01:21:27]    |         ^^^^^^^^^^^^^^ help: replace it with: `gender`
[01:21:27]    |
[01:21:27]    = note: `-D redundant-field-names` implied by `-D warnings`
[01:21:27] 
[01:21:27] error: redundant field names in struct initialization
[01:21:27]   --> $DIR/redundant_field_names.rs:35:9
[01:21:27]    |
[01:21:27] 35 |         age: age,
[01:21:27]    |         ^^^^^^^^ help: replace it with: `age`
[01:21:27] 
[01:21:27] error: redundant field names in struct initialization
[01:21:27]   --> $DIR/redundant_field_names.rs:53:25
[01:21:27]    |
[01:21:27] 53 |     let _ = RangeFrom { start: start };
[01:21:27]    |                         ^^^^^^^^^^^^ help: replace it with: `start`
[01:21:27] 
[01:21:27] error: redundant field names in struct initialization
[01:21:27]   --> $DIR/redundant_field_names.rs:54:23
[01:21:27]    |
[01:21:27] 54 |     let _ = RangeTo { end: end };
[01:21:27]    |                       ^^^^^^^^ help: replace it with: `end`
[01:21:27] 
[01:21:27] error: redundant field names in struct initialization
[01:21:27]   --> $DIR/redundant_field_names.rs:55:21
[01:21:27]    |
[01:21:27] 55 |     let _ = Range { start: start, end: end };
[01:21:27]    |                     ^^^^^^^^^^^^ help: replace it with: `start`
[01:21:27] 
[01:21:27] error: redundant field names in struct initialization
[01:21:27]   --> $DIR/redundant_field_names.rs:55:35
[01:21:27]    |
[01:21:27] 55 |     let _ = Range { start: start, end: end };
[01:21:27]    |                                   ^^^^^^^^ help: replace it with: `end`
[01:21:27] 
[01:21:27] error: redundant field names in struct initialization
[01:21:27]   --> $DIR/redundant_field_names.rs:57:32
[01:21:27]    |
[01:21:27] 57 |     let _ = RangeToInclusive { end: end };
[01:21:27]    |                                ^^^^^^^^ help: replace it with: `end`
[01:21:27] 
[01:21:27] error: aborting due to 7 previous errors
[01:21:27] 
[01:21:27] 
[01:21:27] 
[01:21:27] diff of stderr:
[01:21:27] 
[01:21:27] -error: redundant field names in struct initialization
[01:21:27] -  --> $DIR/redundant_field_names.rs:34:9
[01:21:27] -   |
[01:21:27] -34 |         gender: gender,
[01:21:27] -   |         ^^^^^^^^^^^^^^ help: replace it with: `gender`
[01:21:27] -   |
[01:21:27] -   = note: `-D redundant-field-names` implied by `-D warnings`
[01:21:27] +error[E0464]: multiple matching crates for `derive_new`
[01:21:27] + --> $DIR/redundant_field_names.rs:6:1
[01:21:27] +  |
[01:21:27] +6 | extern crate derive_new;
[01:21:27] +  | ^^^^^^^^^^^^^^^^^^^^^^^^
[01:21:27] +  |
[01:21:27] +  = note: candidates:
[01:21:27] +          crate `derive_new`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-24d68d6f9f8be909.so
[01:21:27] +          crate `derive_new`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-cc2a0602cb5c0153.so
[01:21:27]  
[01:21:27] -error: redundant field names in struct initialization
[01:21:27] -  --> $DIR/redundant_field_names.rs:35:9
[01:21:27] -   |
[01:21:27] -35 |         age: age,
[01:21:27] -   |         ^^^^^^^^ help: replace it with: `age`
[01:21:27] +error[E0463]: can't find crate for `derive_new`
[01:21:27] + --> $DIR/redundant_field_names.rs:6:1
[01:21:27] +  |
[01:21:27] +6 | extern crate derive_new;
[01:21:27] +  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
[01:21:27]  
[01:21:27] -error: redundant field names in struct initialization
[01:21:27] -  --> $DIR/redundant_field_names.rs:53:25
[01:21:27] -   |
[01:21:27] -53 |     let _ = RangeFrom { start: start };
[01:21:27] -   |                         ^^^^^^^^^^^^ help: replace it with: `start`
[01:21:27] +error: aborting due to 2 previous errors
[01:21:27]  
[01:21:27] -error: redundant field names in struct initialization
[01:21:27] -  --> $DIR/redundant_field_names.rs:54:23
[01:21:27] -   |
[01:21:27] -54 |     let _ = RangeTo { end: end };
[01:21:27] -   |                       ^^^^^^^^ help: replace it with: `end`
[01:21:27] -
[01:21:27] -error: redundant field names in struct initialization
[01:21:27] -  --> $DIR/redundant_field_names.rs:55:21
[01:21:27] -   |
[01:21:27] -55 |     let _ = Range { start: start, end: end };
[01:21:27] -   |                     ^^^^^^^^^^^^ help: replace it with: `start`
[01:21:27] -
[01:21:27] -error: redundant field names in struct initialization
[01:21:27] -  --> $DIR/redundant_field_names.rs:55:35
[01:21:27] -   |
[01:21:27] -55 |     let _ = Range { start: start, end: end };
[01:21:27] -   |                                   ^^^^^^^^ help: replace it with: `end`
[01:21:27] -
[01:21:27] -error: redundant field names in struct initialization
[01:21:27] -  --> $DIR/redundant_field_names.rs:57:32
[01:21:27] -   |
[01:21:27] -57 |     let _ = RangeToInclusive { end: end };
[01:21:27] -   |                                ^^^^^^^^ help: replace it with: `end`
[01:21:27] -
[01:21:27] -error: aborting due to 7 previous errors
[01:21:27] -
[01:21:27] +Some errors occurred: E0463, E0464.
[01:21:27] +For more information about an error, try `rustc --explain E0463`.
[01:21:27]  
[01:21:27] 
[01:21:27] The actual stderr differed from the expected stderr.
[01:21:27] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/build/clippy-f23daa848079a0d5/out/test_build_base/redundant_field_names.stderr
[01:21:27] To update references, run this command from build directory:
[01:21:27] tests/ui/update-references.sh '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/build/clippy-f23daa848079a0d5/out/test_build_base' 'redundant_field_names.rs'
[01:21:27] 
[01:21:27] error: 1 errors occurred comparing output.
[01:21:27] status: exit code: 101
[01:21:27] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/clippy-driver" "tests/ui/redundant_field_names.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/build/clippy-f23daa848079a0d5/out/test_build_base" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/build/clippy-f23daa848079a0d5/out/test_build_base/redundant_field_names.stage-id" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps" "-Dwarnings" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/build/clippy-f23daa848079a0d5/out/test_build_base/redundant_field_names.stage-id.aux" "-A" "unused"
[01:21:27] stdout:
[01:21:27] ------------------------------------------
[01:21:27] 
[01:21:27] ------------------------------------------
[01:21:27] stderr:
[01:21:27] ------------------------------------------
[01:21:27] error[E0464]: multiple matching crates for `derive_new`
[01:21:27]  --> tests/ui/redundant_field_names.rs:6:1
[01:21:27]   |
[01:21:27] 6 | extern crate derive_new;
[01:21:27]   | ^^^^^^^^^^^^^^^^^^^^^^^^
[01:21:27]   |
[01:21:27]   = note: candidates:
[01:21:27]           crate `derive_new`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-24d68d6f9f8be909.so
[01:21:27]           crate `derive_new`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-cc2a0602cb5c0153.so
[01:21:27] 
[01:21:27] error[E0463]: can't find crate for `derive_new`
[01:21:27]  --> tests/ui/redundant_field_names.rs:6:1
[01:21:27]   |
[01:21:27] 6 | extern crate derive_new;
[01:21:27]   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
[01:21:27] 
[01:21:27] error: aborting due to 2 previous errors
[01:21:27] 
[01:21:27] Some errors occurred: E0463, E0464.
[01:21:27] For more information about an error, try `rustc --explain E0463`.
[01:21:27] 
[01:21:27] ------------------------------------------
[01:21:27] 
[01:21:27] thread '[ui] ui/redundant_field_names.rs' panicked at 'explicit panic', /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.11/src/runtest.rs:2544:9
[01:21:27] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:21:27] 
[01:21:27] 
[01:21:27] failures:
[01:21:27]     [ui] ui/redundant_field_names.rs
[01:21:27] 
[01:21:27] test result: FAILED. 200 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
[01:21:27] 
[01:21:27] test compile_test ... FAILED
[01:21:27] 
[01:21:27] failures:
[01:21:27] 
[01:21:27] ---- compile_test stdout ----
[01:21:27] thread 'compile_test' panicked at 'Some tests failed', /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.11/src/lib.rs:89:22
[01:21:27] 
[01:21:27] 
[01:21:27] failures:
[01:21:27]     compile_test
[01:21:27] 
[01:21:27] test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:21:27] 
[01:21:27] [0m[0m[1m[31merror:[0m test failed, to rerun pass '--test compile-test'
[01:21:27] 
[01:21:27] 
[01:21:27] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/clippy/Cargo.toml"
[01:21:27] expected success, got: exit code: 101
[01:21:27] 
[01:21:27] 
[01:21:27] 
[01:21:27] 1 command(s) did not execute successfully:
[01:21:27] 
[01:21:27]   - "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/clippy/Cargo.toml"
[01:21:27] 
[01:21:27] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --no-fail-fast src/doc/book src/doc/nomicon src/doc/reference src/doc/rust-by-example src/tools/rls src/tools/rustfmt src/tools/miri src/tools/clippy
[01:21:27] Build completed unsuccessfully in 1:18:30
[01:21:27] {"rustfmt":"test-pass","clippy-driver":"test-fail","book":"test-pass","miri":"build-fail","rls":"build-fail","nomicon":"test-pass","reference":"test-pass","rust-by-example":"test-pass"}
```

</details>

**Comment by nrc** [comment]
r = me when it's ready

thank you!

**Comment by kennytm** [comment]
`racer` depends on the published cargo 0.28.0, which means we will need to build cargo twice (0.28.0 + 0.30.0). Not sure how to fix that, as `[patch.crates-io] cargo = { path = "tools/cargo" }` does nothing.

**Comment by kennytm** [comment]
(Can't repro the bug locally. Now trying to debug the docker image on cloud.)

**Comment by alexcrichton** [comment]
Hm do we have a solution for the cargo 0.28.0 problem? We don't really have enough time on CI to build an optimized Cargo twice?

**Comment by Xanewok** [comment]
@matklad any chance https://github.com/rust-lang-nursery/rls/pull/965 might solve the 0.28 problem or is it not possible yet/requires more changes?

**Comment by matklad** [comment]
> Not sure how to fix that, 

By not depending on two versions of Cargo in the first place :-)

I really think that we should reconsider the strategy of adding stuff to RLS willy-nilly, and we should be more mindful about dependencies, libraries and interfaces. It's past "we need to get something done before the demo" phase, it's time to clean things up. 

https://github.com/rust-lang-nursery/rls/pull/965 is more or less in the mergable state, modulo the racer update. Are rls folks happy with the approach? If it is so, we should merge https://github.com/racer-rust/racer/pull/910 first (cc @kngwyu), make a racer release, and then update the RLS PR to the published version of racer.

**Comment by kennytm** [comment]
@bors r=nrc 

Exempted `cloudabi` (used by `rand 0.5`, used by `crossbeam-channel 0.2`, used by `rls`).

**Comment by kennytm** [comment]
rustfmt formats to use `\r\n` on Windows which conflicts with the expected RLS test result which uses `\n` 😐

**Comment by RalfJung** [comment]
<details><summary>CI failure</summary>

```
stdout:
------------------------------------------
------------------------------------------
stderr:
------------------------------------------
error[E0464]: multiple matching crates for `derive_new`
 --> tests/ui\redundant_field_names.rs:6:1
  |
6 | extern crate derive_new;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: candidates:
          crate `derive_new`: \\?\C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\release\deps\derive_new-51e7621139e8ac5e.dll
          crate `derive_new`: \\?\C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\release\deps\derive_new-7986fad0b0fc1b5b.dll
error[E0462]: found staticlib `derive_new` instead of rlib or dylib
 --> tests/ui\redundant_field_names.rs:6:1
  |
6 | extern crate derive_new;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using --crate-type lib
  = note: the following crate versions were found:
          crate `derive_new`: C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\release/deps\derive_new-51e7621139e8ac5e.dll.lib
          crate `derive_new`: C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\release/deps\derive_new-7986fad0b0fc1b5b.dll.lib
error: aborting due to 2 previous errors
Some errors occurred: E0462, E0464.
For more information about an error, try `rustc --explain E0462`.
------------------------------------------
thread '[ui] ui\redundant_field_names.rs' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\compiletest_rs-0.3.11\src\runtest.rs:2544:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    [ui] ui\redundant_field_names.rs
test result: FAILED. 200 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
test compile_test ... FAILED
failures:
---- compile_test stdout ----
thread 'compile_test' panicked at 'Some tests failed', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\compiletest_rs-0.3.11\src\lib.rs:89:22
failures:
    compile_test
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '--test compile-test'
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\bin\\cargo.exe" "test" "--target" "x86_64-pc-windows-msvc" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "C:\\projects\\rust\\src/tools/clippy\\Cargo.toml"
expected success, got: exit code: 101
[TIMING] Clippy { stage: 2, host: "x86_64-pc-windows-msvc" } -- 51.651
1 command(s) did not execute successfully:
  - "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\bin\\cargo.exe" "test" "--target" "x86_64-pc-windows-msvc" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "C:\\projects\\rust\\src/tools/clippy\\Cargo.toml"
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap test --no-fail-fast src/doc/book src/doc/nomicon src/doc/reference src/doc/rust-by-example src/tools/rls src/tools/rustfmt src/tools/miri src/tools/clippy
Build completed unsuccessfully in 1:00:54
{"miri":"build-fail","nomicon":"test-pass","rust-by-example":"test-pass","rustfmt":"test-pass","book":"test-pass","reference":"test-pass","clippy-driver":"test-fail","rls":"test-pass"}
Verifying status of book...
Verifying status of nomicon...
Verifying status of reference...
Verifying status of rust-by-example...
Verifying status of rls...
This PR updated 'src/tools/rls', verifying if status is 'test-pass'...
Verifying status of rustfmt...
This PR updated 'src/tools/rustfmt', verifying if status is 'test-pass'...
Verifying status of clippy-driver...
Verifying status of miri...
Cloning into 'rust-toolstate'...
The state of "clippy-driver" has changed from "test-pass" to "test-fail"
The state of "rls" has changed from "build-fail" to "test-pass"
The state of "rustfmt" has changed from "build-fail" to "test-pass"
The state of "clippy-driver" has regressed from "test-pass" to "test-fail"
Command exited with code 1
```

</details>

**Comment by kennytm** [comment]
Oh we're in the beta week now. Looks like we need to fix the clippy warnings here as well.

**Comment by kennytm** [comment]
The final build time difference is below. We see that the second cargo added about 5 minutes on average and 18 minutes at maximum to the build time. cc @alexcrichton https://github.com/rust-lang/rust/pull/52755#issuecomment-408634112.

Image | [79891](https://travis-ci.org/rust-lang/rust/builds/409484669) | [79899](https://travis-ci.org/rust-lang/rust/builds/409505255) | Δ (min)
-- | --:| --:| --:
x86_64-gnu-llvm-5.0 | PT4754S | PT5082S | 5.5
dist-x86_64-linux | PT5866S | PT6193S | 5.5
dist-x86_64-linux-alt | PT6326S | PT6644S | 5.3
dist-x86_64-apple-alt | PT4644S | PT4994S | 5.8
x86_64-apple | PT5856S | PT5786S | -1.2
i686-apple | PT5929S | PT5943S | 0.2
dist-i686-apple | PT5151S | PT5478S | 5.5
dist-x86_64-apple | PT6539S | PT6813S | 4.6
arm-android | PT5358S | PT6029S | 11.2
armhf-gnu | PT4994S | PT5547S | 9.2
dist-various-1 | PT4296S | PT3945S | -5.9
dist-various-2 | PT3221S | PT3360S | 2.3
dist-aarch64-linux | PT4566S | PT5487S | 15.4
dist-android | PT3304S | PT3133S | -2.9
dist-arm-linux | PT5375S | PT5664S | 4.8
dist-armhf-linux | PT5156S | PT5630S | 7.9
dist-armv7-linux | PT5091S | PT5564S | 7.9
dist-i586-gnu-i586-i686-musl | PT4705S | PT5173S | 7.8
dist-i686-freebsd | PT5030S | PT4966S | -1.1
dist-i686-linux | PT5266S | PT5989S | 12.1
dist-mips-linux | PT5131S | PT6092S | 16.0
dist-mips64-linux | PT5353S | PT5530S | 3.0
dist-mips64el-linux | PT5100S | PT5521S | 7.0
dist-mipsel-linux | PT5257S | PT5359S | 1.7
dist-powerpc-linux | PT4770S | PT5290S | 8.7
dist-powerpc64-linux | PT5306S | PT5434S | 2.1
dist-powerpc64le-linux | PT5431S | PT5661S | 3.8
dist-s390x-linux | PT5486S | PT5412S | -1.2
dist-x86_64-freebsd | PT4862S | PT5286S | 7.1
dist-x86_64-musl | PT3887S | PT3916S | 0.5
dist-x86_64-netbsd | PT5274S | PT6340S | 17.8
asmjs | PT6198S | PT6118S | -1.3
i686-gnu | PT6726S | PT6685S | -0.7
i686-gnu-nopt | PT6706S | PT6448S | -4.3
wasm32-unknown | PT4066S | PT3791S | -4.6
x86_64-gnu | PT6053S | PT6624S | 9.5
x86_64-gnu-full-bootstrap | PT5169S | PT4388S | -13.0
x86_64-gnu-aux | PT6447S | PT6145S | -5.0
x86_64-gnu-tools | PT4553S | PT5484S | 15.5
x86_64-gnu-debug | PT4203S | PT3740S | -7.7
x86_64-gnu-nopt | PT5240S | PT5231S | -0.2
x86_64-gnu-distcheck | PT6280S | PT6659S | 6.3
mingw-check | PT811S | PT707S | -1.7

**Comment by alexcrichton** [comment]
Thanks for the timing difference @kennytm! It sounds like @matklad and @Xanewok y'all have plans to deduplicate Cargo in the RLS? If so we can go a small amount of time building two for sure

**Comment by Xanewok** [comment]
@alexcrichton cool, great to hear that!

**Pull request merged**
