### PR TITLE
std: Revert addition of `into_ascii_*` methods

### LINKED ISSUE #32074: Regression in autoderef on ascii traits
The following code compiles on stable but gives an error on beta/nightly:

```rust
use std::ascii::AsciiExt; 

fn main() {
        let x = "a".to_string();
        x.eq_ignore_ascii_case("A");
}
```
[playpen](http://is.gd/On0aTB)

```
<anon>:5:32: 5:35 error: mismatched types:
 expected `&collections::string::String`,
    found `&'static str`
(expected struct `collections::string::String`,
    found str) [E0308]
<anon>:5         x.eq_ignore_ascii_case("A");
```
This was caused by the new impl of AsciiExt on `String`: 700ac0e58d48475bf74b3170b497d235fe9e9392

cc @SimonSapin @alexcrichton

### PR DESCRIPTION
**Pull request by alexcrichton**
The addition of these methods in #31335 required adding impls of the trait for
the `String` and `Vec<T>` types. This unfortunately caused a regression (#32074)
in type inference for using these methods which the libs team has decided to not
push forward with. These methods were stabilized in #32020 which was intended to
get backported to beta, but the backport hasn't happened just yet. This commit
reverts both the addition and stabilization of these methods.

One proposed method of handling this, in #32076, was to move the methods to an
extra trait to avoid conflicts with type inference. After some discussion,
however, the libs team concluded that we probably want to reevaluate what we're
doing here, so discussion will continue on the tracking issue, #27809.

Closes #32074

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nominating for beta inclusion as well to fix the inference regression caused by using the stable methods.

**Comment by aturon** [comment]
Can you run crater on this change? I see some hits on github code search...

**Comment by alexcrichton** [comment]
Crater reports [one regression](https://gist.github.com/alexcrichton/27e95d177c56d5500479) which seems to be spurious?

**Comment by eddyb** [comment]
@alexcrichton Would it make sense to have a regression test for #32074?

**Comment by alexcrichton** [comment]
@eddyb good point, I'll add that if this bounces or in another PR if it lands

**Pull request merged**
