### PR TITLE
When cast needs a dereference point at full cast

### PR DESCRIPTION
**Pull request by estebank**
After the fix of #37453 in PR #37369, instead of pointing at only the cast type, point at the full cast span when a cast needs a dereference, as well as assign the error label to the correct span for proper coloring:

error span pointing at the entire cast

instead of

error span pointing at the type of the cast

Move `compile-fail` test to `ui` test.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@emilio 

Hmm I'm not sure I see this as an improvement...I think I prefer the new span, but I'd prefer the "did you mean `*s`?" bit to be moved into a Help, so that it doesn't overlap. What do you think @jonathandturner ?

**Comment by estebank** [comment]
@nikomatsakis I have [separated the suggestion to a help](https://github.com/rust-lang/rust/pull/38245/files#diff-dcc8f093f08623369518d763e80e01f6R233) as requested.

**Comment by nikomatsakis** [comment]
@estebank looks good!

**Comment by eddyb** [comment]
@rust-lang/tools [tests failed](https://travis-ci.org/rust-lang/rust/builds/185342261) but homu didn't pick it up.

@bors r- force

**Comment by eddyb** [comment]
Hmmmmmm let's try this instead (sorry, @estebank, trying to get the bot unstuck).

**Comment by eddyb** [comment]
Well that didn't help anything 😞.

**Pull request merged**
