### PR TITLE
add diagnostics for E0193

### PR DESCRIPTION
**Pull request by AlisdairO**
As title :-)
Part of #24407.

r? @Manishearth

### CODE REVIEW

**Comment by AlisdairO** [comment]
Thanks!

**Comment by Manishearth** [comment]
Okay, that's not intermittent. I wonder why that's happening...

**Comment by Manishearth** [comment]
Could you try running the test locally? (`TESTNAME=backtrace-debuginfo make check-stage1-rpass`)

**Comment by AlisdairO** [comment]
Working for me (OSX Mavericks):

jury2-2:rust alisdair$ TESTNAME=backtrace-debuginfo make check-stage1-rpass
cfg: version 1.4.0-dev (d07a094fb 2015-08-09)
cfg: build triple x86_64-apple-darwin
cfg: host triples x86_64-apple-darwin
cfg: target triples x86_64-apple-darwin
cfg: host for x86_64-apple-darwin is x86_64
cfg: os for x86_64-apple-darwin is apple-darwin
cfg: good valgrind for x86_64-apple-darwin is 
cfg: using CC=clang (CFG_CC)
cfg: using CXX=clang++ (CFG_CXX)
cfg: disabling valgrind run-pass tests
cfg: no xelatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
cfg: including test rules
cfg: javac not available, skipping lexer test...
rustc: x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/libtest
rustc: x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/bin/compiletest
cp: x86_64-apple-darwin/stage1/lib/libtest
cp: x86_64-apple-darwin/stage1/bin/compiletest
run rpass [x86_64-apple-darwin]: x86_64-apple-darwin/stage1/bin/compiletest

running 2 tests
test [run-pass] run-pass/backtrace-debuginfo-aux.rs ... ignored
test [run-pass] run-pass/backtrace-debuginfo.rs ... ok

test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured

**Comment by TimNN** [comment]
I don't think the problem is with this pull request, #27612 failed with the same error.

**Pull request merged**
