### PR TITLE
refactor session::config::build_session_options_and_crate_config

### PR DESCRIPTION
**Pull request by Centril**
I'm not exactly sure what happened in https://github.com/rust-lang/rust/pull/65361#issuecomment-541420179 so in an effort to bisect the error I'm extracting out the first commit so it can hopefully land (I suspect the error is in the 2nd-3rd commits.)

r? @petrochenkov 

(I'll r=you when the PR builder is happy)

### CODE REVIEW

**Comment by petrochenkov** [comment]
Probably the third one, test build of `rustc` depending on `rustc_interface` is at least suspicious.

**Comment by Centril** [comment]
Yeah, I suspect so as well.

**Comment by petrochenkov** [comment]
So we get two `rustc` crates - one being tested and another linked transitively through `rustc_interface`, them conflicting due to diagnostic items is pretty plausible.

**Pull request merged**
