### PR TITLE
Improve `std::thread::available_parallelism` docs

### PR DESCRIPTION
**Pull request by yoshuawuyts**
_Tracking issue: https://github.com/rust-lang/rust/issues/74479_

This PR reworks the documentation of `std::thread::available_parallelism`, as requested [here](https://github.com/rust-lang/rust/pull/89324#issuecomment-934343254).

## Changes

The following changes are made:

- We've removed prior mentions of "hardware threads" and instead centers the docs around "parallelism" as a resource available to a program.
- We now provide examples of when `available_parallelism` may return numbers that differ from the number of CPU cores in the host machine.
- We now mention that the amount of available parallelism may change over time.
- We make note of which platform components we don't take into account which more advanced users may want to take note of.
- The example has been updated, which should be a bit easier to use.
- We've added a docs alias to `num-cpus` which provides similar functionality to `available_parallelism`, and is one of the most popular crates on crates.io.

---

Thanks!

r? @BurntSushi

### CODE REVIEW

**Comment by shoffmeister** [comment]
For the sake of maintainability (technical documentation debt), I'd recommend to simply omit the whole section on `The following platform limitations currently apply:`.

Instead, I'd suggest wording to the effect of `Platform-specific implementations will come with further individual limitations. Please review the respective target platform implementation for details.` This is clearly less expressive than the existing text, but also makes less promises.

IMHO, anybody who is interested in the "fully correct picture on parallelism" will *have* to study the implementation, anyway (or get this from highly specialized implementation)

**Review by nagisa — COMMENTED** [review]
Really nice.

**Comment by BurntSushi** [comment]
It looks like @joshtriplett is all over this! Thank you. I think my concern is totally addressed here, so I'll hand things over if you don't mind.

r? @joshtriplett

**Comment by yoshuawuyts** [comment]
The last run contained a typo in the example which caused the test to fail. Can someone re-run bors again?

**Pull request merged**
