### PR TITLE
Address issue number: #35391

### PR DESCRIPTION
**Pull request by shyamsundarb-arch**
I am new here. Kindly review the changes made.

### CODE REVIEW

**Comment by shyaamsundhar** [comment]
@rust-highfive Thanks for the welcoming response. I have gone through the basics in the contribution instructions.

**Comment by jonathandturner** [comment]
Thanks for the PR!  

Can you also include an updated unit test that tests for the new label?  You can see how in the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html).

**Comment by shyaamsundhar** [comment]
Sure. Will go through the document do the needful.

**Comment by shyaamsundhar** [comment]
Have made a fix which addresses the build problem.

**Comment by shyaamsundhar** [comment]
@jonathandturner Have made the changes in the required file. Please refer pull request number: #35464

**Comment by jonathandturner** [comment]
@shyaamsundhar  - please put both changes in the same pull request.  You can update the branch that you created this pull request from, and it will add it to this one.

You can close #35464 when you have put the changes in this one.

**Comment by shyaamsundhar** [comment]
@jonathandturner  Done!

**Comment by jonathandturner** [comment]
Great, that looks good.

One more step.  Please [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the 4 commits down to 1 commit.  After that, I think it's ready.

**Comment by shyaamsundhar** [comment]
Am closing this pull request to create a clean request.

**Pull request closed without merging**
