### PR TITLE
Stabilize "RangeFrom" patterns in 1.55

### PR DESCRIPTION
**Pull request by workingjubilee**
Implements a partial stabilization of #67264 and #37854.
Reference PR: https://github.com/rust-lang/reference/pull/900

# Stabilization Report

This stabilizes the `X..` pattern, shown as such, offering an exhaustive match for unsigned integers:
```rust
match x as u32 {
      0 => println!("zero!"),
      1.. => println!("positive number!"),
}
```

Currently if a Rust author wants to write such a match on an integer, they must use `1..={integer}::MAX` . By allowing a "RangeFrom" style pattern, this simplifies the match to not require the MAX path and thus not require specifically repeating the type inside the match, allowing for easier refactoring. This is particularly useful for instances like the above case, where different behavior on "0" vs. "1 or any positive number" is desired, and the actual MAX is unimportant.

Notably, this excepts slice patterns which include half-open ranges from stabilization, as the wisdom of those is still subject to some debate.

## Practical Applications

Instances of this specific usage have appeared in the compiler: 
https://github.com/rust-lang/rust/blob/16143d10679537d3fde4247e15334e78ad9d55b9/compiler/rustc_middle/src/ty/inhabitedness/mod.rs#L219
https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/compiler/rustc_ty_utils/src/ty.rs#L524

And I have noticed there are also a handful of "in the wild" users who have deployed it to similar effect, especially in the case of rejecting any value of a certain number or greater. It simply makes it much more ergonomic to write an irrefutable match, as done in Katholieke Universiteit Leuven's [SCALE and MAMBA project](https://github.com/KULeuven-COSIC/SCALE-MAMBA/blob/05e5db00d553573534258585651c525d0da5f83f/WebAssembly/scale_std/src/fixed_point.rs#L685-L695).

## Tests
There were already many tests in [src/test/ui/half-open-range/patterns](https://github.com/rust-lang/rust/tree/90a2e5e3fe59a254d4d707aa291517b3791ea5a6/src/test/ui/half-open-range-patterns), as well as [generic pattern tests that test the `exclusive_range_pattern` feature](https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/src/test/ui/pattern/usefulness/integer-ranges/reachability.rs), many dating back to the feature's introduction and remaining standing to this day. However, this stabilization comes with some additional tests to explore the... sometimes interesting behavior of interactions with other patterns. e.g. There is, at least, a mild diagnostic improvement in some edge cases, because before now, the pattern `0..=(5+1)` encounters the `half_open_range_patterns` feature gate and can thus emit the request to enable the feature flag, while also emitting the "inclusive range with no end" diagnostic. There is no intent to allow an `X..=` pattern that I am aware of, so removing the flag request is a strict improvement. The arrival of the `J | K` "or" pattern also enables some odd formations.

Some of the behavior tested for here is derived from experiments in this [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=58777b3c715c85165ac4a70d93efeefc) example, linked at https://github.com/rust-lang/rust/issues/67264#issuecomment-812770692, which may be useful to reference to observe the current behavior more closely.

In addition tests constituting an explanation of the "slicing range patterns" syntax issue are included in this PR.

## Desiderata

The exclusive range patterns and half-open range patterns are fairly strongly requested by many authors, as they make some patterns much more natural to write, but there is disagreement regarding the "closed" exclusive range pattern or the "RangeTo" pattern, especially where it creates "off by one" gaps in the presence of a "catch-all" wildcard case. Also, there are obviously no range analyses in place that will force diagnostics for e.g. highly overlapping matches. I believe these should be warned on, ideally, and I think it would be reasonable to consider such a blocker to stabilizing this feature, but there is no technical issue with the feature as-is from the purely syntactic perspective as such overlapping or missed matches can already be generated today with such a catch-all case. And part of the "point" of the feature, at least from my view, is to make it easier to omit wildcard matches: a pattern with such an "open" match produces an irrefutable match and does not need the wild card case, making it easier to benefit from exhaustiveness checking.

## History

- Implemented:
  - Partially via exclusive ranges: https://github.com/rust-lang/rust/pull/35712
  - Fully with half-open ranges: https://github.com/rust-lang/rust/pull/67258
- Unresolved Questions:
  - The precedence concerns of https://github.com/rust-lang/rust/pull/48501 were considered as likely requiring adjustment but probably wanting a uniform consistent change across all pattern styles, given https://github.com/rust-lang/rust/issues/67264#issuecomment-720711656, but it is still unknown what changes might be desired
  - How we want to handle slice patterns in ranges seems to be an open question still, as witnessed in the discussion of this PR!

I checked but I couldn't actually find an RFC for this, and given "approved provisionally by lang team without an RFC", I believe this might require an RFC before it can land? Unsure of procedure here, on account of this being stabilizing a subset of a feature of syntax.

r? @scottmcm

### CODE REVIEW

**Comment by scottmcm** [comment]
[Lang previously expressed interest in stabilizing this](https://github.com/rust-lang/rust/issues/67264#issuecomment-716798691), so let's do it!

I think this is a particularly nice win when coupled with the exhaustive integer matching from 1.33, as a great way to write "and everything X and above" without using a wildcard.

@rfcbot fcp merge

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by bstrie** [comment]
This has a little bit of a surprising contrast with slice patterns. Consider this (working) code:
```rust
let x = [-100, -50, 50, 100];

assert_eq!(&x[..], &[-100, -50, 50, 100]);
assert_eq!(&x[..2], &[-100, -50]);
assert_eq!(&x[2..], &[50, 100]);
assert_eq!(&x[1..3], &[-50, 50]);

let [y @ ..] = x;
assert_eq!(x, y);
```
A user might then expect the following to work:
```rust
let [neg @ ..2, pos @ 2..] = x; // error
assert_eq!(neg, [-100, -50]);
assert_eq!(pos, [50, 100]);

let [_, fifties @ 1..3, _] = x; // error
assert_eq!(fifties, [-50, 50])
```
However with the feature as implemented, the pattern `[..x, x..]` doesn't mean "match an array of arbitrary length and split it array into two at index `x`", it means "match an array of exactly two elements, where the first element's value is less than `x` and the second's is greater or equal to `x`". It's a bit of an unfortunate situation where `[..]` and `[0..]` will mean surprisingly different things in pattern context.

The most future-proofed solution here would be to produce a compilation error when encountering a `..` at the top level of a slice pattern (excepting RangeFull). This is backwards-compatible with existing `[..]` slice patterns, would most likely never be encountered by people trying to use range patterns. And since `match 42 { .. => () }` is already invalid (can't use `..` outside of tuple, tuple struct, and slice patterns), this would leave us in a state where RangeFull patterns, despite meaning something different from the other Range patterns, would be distinct and disjoint in semantics with no ambiguity. And of course it would be backwards-compatible if anybody wanted to lift this restriction in the future, either to allow slicing with RangeFrom et al or to revive the behavior as it is currently implemented (basically, deciding whether you'd rather have `0..` be surprisingly different from `[0..]`, or have `[0..]` be surprisingly different from `[..]`).

**Comment by workingjubilee** [comment]
I'm sorry, I don't know if I truly understand what you actually mean here. "`..` excepting RangeFull" seems like a contradiction. I currently assume you mean the slicing patterns that match the RangeFrom, RangeTo, and RangeExclusive patterns, but I am not sure, because when I first read it yesterday, I assumed you meant literally barring the `..` token except for the specific character sequence of `[..]` only. Which would clearly be unacceptable, because I regularly use patterns akin to this:
```rust
let xs = [13, 1, 5, 2, 3, 1, 21, 8];
let [a, b, c @ ..] = xs;
println!(r"first element: {a}
second element: {b}
rest: {c:?}", a = a, b = b, c = c);
```

Specifically I like this for repeatedly dismantling parts of a slice for e.g. argument parsing. Which is valid with or without the @ binding and capturing `..` and its associated values here. Now, at this point I am more confident that I am repeating you, as I believe you're looking at the case of a slice pattern combining with a RangeFrom and RangeTo pattern, and how it would be desirable to instead have
```rust
let [first_two @ ..2, rest @ 2..] = xs;
```
work on multi-element arrays, whereas instead it errors with
```
error[E0527]: pattern requires 2 elements but array has 8
 --> src/main.rs:6:5
  |
6 | let [first_two @ ..2, rest @ 2..] = xs;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 8 elements

error: aborting due to previous error
```

However, this currently already works, 
```rust
// The pattern becomes refutable because this is now matching on an integer inside the slice pattern.
if let [a, b, c @ 5..=9, ..] = xs {
    println!("captured {}, {}, and {}!", a, b, c); // prints: captured 13, 1, and 5!
} else {
    println!("whoops");
}
```

So, my response is: I believe the ship **may** have actually sailed already for RangeExclusive patterns, because they should match RangeInclusive patterns in basically all ways excepting the range inclusiveness. I believe allowing "slicing RangeTo" and "slicing RangeFrom" patterns is plausible, but is conditioned on our accepting the deviance of RangeFrom and RangeTo vs. RangeInclusive/RangeExclusive, or doing an appropriate "edition dance". I indeed could see barring RangeExclusive, RangeFrom, and RangeTo _within slice patterns_ for the moment and advancing an RFC which addresses this fully.

I believe the RangeFrom patterns are noncontroversial _outside_ slice patterns, because validating it in the simple non-slicing cases won't introduce more confusion. And there's already some notional overlap in slice patterns with legal SliceIndex expressions. I repeat myself, but again, this is valid:
```rust
println!("{:?}", &xs[2..=5]); // prints: [5, 2, 3, 1]
```
but "conflicts" with the slice pattern
```rust
let [ys @ 2..=5] = xs;
println!("{:?}", ys);
```
instead producing the error
```
error[E0527]: pattern requires 1 element but array has 8
 --> src/main.rs:6:5
  |
6 | let [ys @ 2..=5] = xs;
  |     ^^^^^^^^^^^^ expected 8 elements
```

**Comment by workingjubilee** [comment]
Assuming I understand @bstrie's remarks correctly, I will update this PR with the appropriate restrictions as suggested, unless there is a broad consensus otherwise, because I did not adequately address this in my stabilization report. This should not be merged until then. I am marking this as a draft for the moment until this is resolved (i.e. I reapply this feature gate for slices and itemize the slice syntax concerns in the appropriate issues). Hopefully I get around to this Sooner rather than Later.

TODO:
- [ ] Feature-restrict RangeFrom in slice patterns
- [ ] More clearly itemize the relevant concerns in issue #67264 
- [ ] Also itemize the relevant concerns in issue #37854

**Comment by nikomatsakis** [comment]
TBH, I haven't processed those comments yet (they're long 😛)! I think perhaps that should have been raised as a concern in the FCP, but that's ok. I'm going to nominate for T-lang meeting just to review and make an official judgement, but future-proofing seems reasonable on the face of it.

**Comment by bstrie** [comment]
Aha, I didn't realize that RangeInclusive patterns were already available in slice pattern position. I'd consider that an accidental oversight, but I'll leave that for the lang team to decide. I'd be willing to write an RFC laying out what I think the behavior of slice patterns should be, which would include the deprecation of RangeInclusive in slice pattern position, but of course the syntax could only be reclaimed across an edition, and it's not going to happen for the 2021 edition.

To summarize, here's are the `..` patterns that *don't* already compile:
```rust
match [0] {
        [0..10] => (),
        [..255] => (),
        [0..] => (),
        [..=10] => (),
}
```
Currently all of these compile if the `exclusive_range_pattern` and `half_open_range_patterns` features are enabled. For maximum future-proofing I think all of these should fail to compile even if those two features are enabled. Of course, this PR only stabilizes `[0..]`, so if it's easier to only make that one an error for now then that's fine. If the lang team is receptive to this future-proofing then I'll submit an RFC to discuss reserving this syntax for slice patterns.

**Comment by Mark-Simulacrum** [comment]
We [discussed](https://hackmd.io/gsP_V1o9QZGdxf2NOFd7-Q?view#%E2%80%9CStabilize-%E2%80%9CRangeFrom%E2%80%9D-patterns%E2%80%9D-rust83918) this in the language team meeting on 2021-05-18. There was broad agreement that this case is likely to not be typical, and the general sentiment was in favor of introducing a lint to suggest wrapping a single-element range expression (i.e., `[0..]`) with parentheses (`[(0..)]`) to indicate that it is intended to match a single element.

We did not feel that this needs to block stabilization, but wanted to check that @bstrie you felt this would be sufficient to mitigate the confusion here. If so, could you open an issue about that lint? If not, then more discussion will be necessary.

**Comment by bstrie** [comment]
I've opened a Zulip thread for discussion of my proposal, so as not to further clog up this one: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/range.2Fslice.20patterns

**Comment by workingjubilee** [comment]
Updated with step 0 in my latest commit.
This PR should now continue to feature-restrict RangeFrom within a slice pattern.
@bstrie I would appreciate your review, if you have the time.

**Comment by bstrie** [comment]
I'm not qualified to comment on the implementation but the tests look good to me. 👍

**Comment by workingjubilee** [comment]
Excellent,
and followup comments have been added to the appropriate tracking issues.
I consider this satisfactory and it is ready to merge.

**Comment by nikomatsakis** [comment]
I'm trying to remember where our discussion left off in the last lang team meeting and/or on Zulip. I am still feeling rather unconvinced that we should feature gate patterns like this. I feel like having range patterns not compose within slice patterns feels rather surprising to me, and I don't think using the same syntax for some other meaning seems very likely.

**Comment by workingjubilee** [comment]
Mmm, I agree with bstrie that there is syntactic conflict with SliceIndex. All the code I write destructuring slices, very often byteslices, would be neater and simpler if it could use a pattern like
```rust
let [octobyte 0..8, rest @ ..] = byteslice;
let num = u64::from_le_bytes(octobyte);
```
Instead, to do that, I have to use
```rust
let [a, b, c, d, e, f, g, h, rest @ ..] = byteslice;
let num = u64::from_le_bytes([a, b, c, d, e, f, g, h]);
```
And yes, I have written variants of the above several times. I don't consider the `.try_into().unwrap()` case less bad. It's agreed that range patterns are rare in slices... and I think they are rare because what a user would really expect, where a range pattern inside a slice pattern works like SliceIndex, _doesn't_ work.

In any case, I did not adequately address the conflict between range patterns and slice patterns in my stabilization report, even though it was mentioned in the issue, because **I didn't understand** it. I reestablished the feature gate only because that seemed like the most minimal possible proofing to allow further attention to be paid to it, and assume even that will be obviated in short order by future actions. We could also make it fail to compile, or cancel incremental stabilization of range patterns and wait for a full RFC on the whole shindig. All of those seem like valid ways to address the concern... otherwise why wait for final comment periods if we don't address concerns in those comments?

**Comment by joshtriplett** [comment]
@rfcbot concern consider-alternative-further

@workingjubilee, can you start a new thread in the lang Zulip stream  to discuss this further, so that we can consider possibilities with you?

**Comment by joshtriplett** [comment]
Based on discussion with @workingjubilee, it sounds like the net effect of this PR is to stabilize RangeFrom patterns *except* for the combination of range patterns within slice patterns. That allows for further evaluation of how to make those compatible in the most intuitive and least confusing way we can.

I think it's appropriate to go ahead with a partial stabilization here. Even if we want to stabilize range patterns within slice patterns as well, I think it's reasonable to do that in a separate PR that discusses the tradeoffs, rather than complicating *this* PR.

We're not making an irreversible decision to stabilize something that would commit us down one or the other path; rather, we're intentionally only stabilizing the subset that still allows us to make that decision separately in the future.

Given that:

@rfcbot resolved consider-alternative-further

**Comment by inquisitivecrystal** [comment]
I think that rfcbot may have gotten confused by the fact that this went through FCP again after the FCP had finished once. It looks to me like the FCP is now over and this is ready to merge, though I could be missing something.

**Comment by workingjubilee** [comment]
You are correct.
@bors r=joshtriplett

**Pull request merged**
