### PR TITLE
Fix type filter in rustdoc js

### LINKED ISSUE #46612: rustdoc: Search filtering broken
On the nightly docs, performing a query such as `struct:Vec` returns no results. It seems any filtered query returns no results. The stable docs work properly.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #46612.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by durka** [comment]
This is also on beta. Can this and related PRs fixing the new search be backported before the next stable?

**Comment by GuillaumeGomez** [comment]
I suppose? First, it needs to be merged anyway.

**Comment by alexcrichton** [comment]
Looks like we forgot to backport this for 1.23.0 (sorry about that!) so removing beta tags.

**Comment by alexcrichton** [comment]
Er sorry, looks like this was backported in https://github.com/rust-lang/rust/pull/46886

**Pull request merged**
