### PR TITLE
Use copy bound in atomic operations to generate simpler MIR

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by eddyb** [comment]
@tmiasko Can you add them to the atomic intrinsics as well? Assuming it works on them.
This seems correct in that using the atomic intrinsics with non-`Copy` types is effectively like using `ptr::read` to "move out" a value, which is likely UB for any shared memory.

cc @RalfJung @Amanieu

**Comment by tmiasko** [comment]
I was looking at this from the angle: what would it take for MIR transforms to optimize `a.store(v, Ordering::Relaxed);` to just an intrinsic call. This change helps, but inlining cost is still above the threshold for store operation in particular (there are costly panic calls, and even replacing them with an abort intrinsic it is merely sufficient to remove one layer of indirection and inline `atomic_store` function into the method).

Extending this to intrinsics should work. I could add them with understanding that it would break generic code that uses them without similar bounds, like for example this one here (before changes). In a separate PR preferably.

**Comment by oli-obk** [comment]
> what would it take for MIR transforms to optimize a.store(v, Ordering::Relaxed); to just an intrinsic call.

We could extend the `#[inline]` syntax to have conditions like

```rust
#[inline(always, if_arg_is_const(order))]
```

To get a poor man's version of partial specialization (after which you most often can properly inline).

**Comment by Centril** [comment]
> Either way, this PR seems correct in that using the atomic intrinsics with non-`Copy` types is effectively like using `ptr::read` to "move out" a value, which is likely UB for any shared memory.

N.B: It's only UB if the function is actually reached at runtime.

**Comment by RalfJung** [comment]
`ptr::read` behavior does not depend on whether `T` is `Copy` or not. So I don't see any relation to UB here.

But until we have a good example for a non-`Copy` type one might want to use here, there's still no reason not to do this I think. :D

**Comment by eddyb** [comment]
> N.B: It's only UB if the function is actually reached at runtime.

Well, yeah, I meant that using them to duplicate/"move out" a value is likely UB, not just having around the function definitions.

> So I don't see any relation to UB here.

What I mean is an atomic load of e.g. a `Box<T>` value is likely prone to UB if the underlying memory is actually shared cross-thread, as it duplicates a non-`Copy` value.
`ptr::read` on non-`Copy` types requires some form of ownership to prevent *later* UB, which is mostly antithetical to situations atomics are used in.

**Comment by eddyb** [comment]
> We could extend the `#[inline]` syntax to have conditions like
>
> ```rust
> #[inline(always, if_arg_is_const(order))]
> ```

Heh, this is the sort of thing I was telling @wesleywiser we should compute instead of "inline costs" - conditions under which the function would become trivial.

**Comment by tmiasko** [comment]
The changes here don't affect any public API (the other PR is more interesting in that respect).

r? @eddyb

**Review by eddyb — APPROVED** [review]

**Pull request merged**
