### PR TITLE
Uninhabited while-let pattern fix

### PR DESCRIPTION
**Pull request by canndrew**
This fix makes it so while-let with an unsatisfiable pattern raises a correct warning rather than an incorrect error.

### CODE REVIEW

**Comment by eddyb** [comment]
Does this need to be backported? cc @rust-lang/compiler

**Comment by canndrew** [comment]
@arielb1 All done.

**Comment by canndrew** [comment]
@eddyb You mean backported to beta? Probably, yes.

**Comment by nikomatsakis** [comment]
Approved for beta backport: small, isolated change; regression.

cc @rust-lang/compiler

**Pull request merged**
