### PR TITLE
Use `SmallVec` in `ast::Path`.

### PR DESCRIPTION
**Pull request by nnethercote**
This is up to a 1% speedup on a few benchmark runs.

### CODE REVIEW

**Comment by nnethercote** [comment]
I will do a timer run to double-check the perf improvements.

@bors try

**Comment by Dylan-DPC** [comment]
ping from triage @nnethercote it is failling on travis

**Comment by Dylan-DPC** [comment]
ping from triage @nnethercote Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please reopen this PR, we'll be happy to review it again! Thanks

**Comment by nnethercote** [comment]
Yeah, this isn't going anywhere.

**Pull request closed without merging**
