### PR TITLE
[perf-check] Revert "Rollup merge of #88860 - nbdd0121:panic, r=m-ou-se"

### PR DESCRIPTION
**Pull request by JohnTitor**
This reverts commit f7024998c7eae5b582de680effaca105198aa95c, reversing
changes made to 84fe598f0094c8d6a1dddcdc38ac0fa28df32f44.

r? @ghost cc https://github.com/rust-lang/rust/pull/90067#issuecomment-952080100

### CODE REVIEW

**Comment by jackh726** [comment]
I think this is more a T-libs PR than T-compiler.

**Comment by JohnCSimon** [comment]
@JohnTitor Can you please address the merge conflicts?

**Comment by JohnTitor** [comment]
I'd like to see @m-ou-se's (or someone from t-libs) thoughts if this is worth merging before resolving the conflicts.

**Comment by m-ou-se** [comment]
Do we know why and how this change affects performance? The perf results don't show a lot of difference.

**Comment by JohnTitor** [comment]
> Do we know why and how this change affects performance? The perf results don't show a lot of difference.

The regression we found is https://github.com/rust-lang/rust/pull/90067#issuecomment-947755499, according to the bot: `Moderate regression in instruction counts (up to 1.1% on incr-patched: b9b3e592dd cherry picked builds of style-servo)`
And the perf result here is: `Small improvement in instruction counts (up to -1.0% on incr-patched: b9b3e592dd cherry picked builds of style-servo)`
So we could assume the regression came from that PR, I think.

**Comment by JohnTitor** [comment]
> > So we could assume the regression came from that PR, I think.
> 
> Sure, but do we have any idea how it caused it? The difference is small enough that it could be something unrelated.

Not really, because this PR was created on 27th Oct 2021 and I don't remember the time I investigated. I think you're more familiar with the changes as you're the reviewer of it. Looking at the benchmark code (https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/style-servo) would be helpful. And the point here is if it's worth reverting, I guess.

**Comment by Dylan-DPC** [comment]
@JohnTitor do we still need this pr?

**Comment by m-ou-se** [comment]
Since the impact is minimal and we don't even know how that PR caused the small regression, I think we should just close this.

**Pull request closed without merging**
