### PR TITLE
Make closures inherit their parent's "safety context"

### LINKED ISSUE #9: Make closures inherit their parent's "safety context"
Checking unsafety for closures should be handled by their parent body, as closures inherit their "safety context" from their declaration site.

Blocked on rust-lang/rust#85273.

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Fixes rust-lang/project-thir-unsafeck#9, ~~blocked on #85273~~.
r? @nikomatsakis

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
@nikomatsakis This is ready for review now

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Are there no tests for this/

**Comment by LeSeulArtichaut** [comment]
Whoops you're right, I forgot

**Comment by LeSeulArtichaut** [comment]
@nikomatsakis Pushed the tests.

To track the tests that were fixed by this, I ran all the test suite with `-Z thir-unsafeck` enabled. So little status update!
I got 43 errors:
- 3 are known inconsistencies between MIR and THIR (early compilation exit)
- 25 should be fixed by this
- which means that we're left with 15 tests to fix, I found no surprise, I think all of them are just due to missing implementations

Making progress :)

**Review by nikomatsakis — APPROVED** [review]

**Comment by LeSeulArtichaut** [comment]
Probably spurious failure?

**Pull request merged**
