### PR TITLE
implement proper linkchecker hardening

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @JohnTitor 

This implements proper linkcheck filtering... we might need to fiddle with a bit to adjust what is or isn't filtered, but this seems to work reasonable locally.

### CODE REVIEW

**Comment by mark-i-m** [comment]
cc @ehuss

**Comment by JohnTitor** [comment]
Looks good, could we update rustc-guide to see if the change works well?

**Comment by mark-i-m** [comment]
It broke on my other machine, so I pushed a fix. I also added a commit to update rustc-guide. It seems to be working locally.

**Comment by JohnTitor** [comment]
Thanks! r=me if @ehuss also approves it (and I could r+ here)

**Comment by ehuss** [comment]
Seems ok to me.  I'm still of the opinion that the benefit of linkchecking on rust-lang/rust doesn't outweigh the cost, but I understand you find it useful.

**Comment by JohnTitor** [comment]
Okay, let's then
@bors r=ehuss,JohnTitor

**Pull request merged**
