### PR TITLE
Shrink `rustc_parse_format::Piece`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This makes both variants closer together in size (previously they were different by 208 bytes -- 16 vs 224). This may make things worse, but it's worth a try.

r? @nnethercote

### CODE REVIEW

**Comment by nnethercote** [comment]
Some sub-1% instruction count wins on `deep-vector`, plus an intriguing but possibly too-good-to-be-true -0.4% reduction in bootstrap time.

@WaffleLapkin Do you still want to proceed? If so, adding a `static_assert_size!` would be a good idea. Otherwise, the code changes are fine.

**Comment by nnethercote** [comment]
Wait, there's a size assertion failure:
```
error[E0308]: mismatched types
   --> /checkout/compiler/rustc_index/src/lib.rs:29:32
    |
27  | macro_rules! static_assert_size {
    | ------------------------------- in this expansion of `rustc_data_structures::static_assert_size!`
28  |     ($ty:ty, $size:expr) => {
29  |         const _: [(); $size] = [(); ::std::mem::size_of::<$ty>()];
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a fixed size of 24 elements, found one with 16 elements
    |
   ::: compiler/rustc_parse_format/src/lib.rs:913:1
    |
913 | rustc_data_structures::static_assert_size!(Piece<'_>, 24);
    | --------------------------------------------------------- in this macro invocation
```

@bors r-

**Comment by nnethercote** [comment]
Yeah, 16 seems the right size: 8 bytes for the tag, and 8 bytes for the single pointer/Box field in each variant.

**Comment by WaffleLapkin** [comment]
Right, I forgot that I test on arm xD

> Yeah, 16 seems the right size: 8 bytes for the tag, and 8 bytes for the single pointer/Box field in each variant.

This is not actually right, the first field is `&str`, which is 16 bytes, the tag is actually 0 bytes, I assume instead of a 8 bytes tag we use `&str`'s niche.

**Pull request merged**
