### PR TITLE
Run `cargo update` for the root lockfile

### PR DESCRIPTION
**Pull request by Makuo12**
Update packages to their latest version.

### CODE REVIEW

**Comment by tgross35** [comment]
Please see the rest of the review at https://github.com/rust-lang/rust/pull/131574, it still applies here. I don’t think there is any reason you needed to make a new PR.

**Comment by ChrisDenton** [comment]
I don't know if this should be closed in favour of the other one or something else so...

r? tgross35

**Review by davidtwco — COMMENTED** [review]
License changes look okay, haven't checked the rest

**Review by tgross35 — CHANGES_REQUESTED** [review]
@Makuo12 this still needs the updates at https://github.com/rust-lang/rust/pull/131574#discussion_r1797508016 if you are still interested in getting this merged. Specifically, anything that currently has an `a.b` or `a.b.0` version shouldn't be changed to `a.b.c`.

This is also pretty outdated so needs an update.

**Comment by Makuo12** [comment]
@tgross35 I am done with the updates.

**Comment by tgross35** [comment]
Er hang on, this previously only touched the manifest files in `library/`. I guess there isn't any harm in increasing the versions in `compiler/` if it just makes them match the lockfile, but Clippy Miri and Rust-Analyzer are all developed in separate repositories and probably shouldn't be updated here.

**Comment by bjorn3** [comment]
You shouldn't change the versions in Cargo.toml files unless they are semver incompatible versions. Updating Cargo.lock using `cargo update` is enough.

**Comment by Makuo12** [comment]
@bjorn3 I reverted back and updated it with cargo update.

**Review by tgross35 — APPROVED** [review]
This is just a standard lockfile update and it looks fine.

Looks like `thiserror` released a 2.0 at the beginning of November so the lockfile now has both versions. We use 1.0 a few places in-tree https://github.com/search?q=repo%3Arust-lang%2Frust+%2Fthiserror+%3D%2F+lang%3Atoml&type=code, they should be updated at some point so we can drop the old version sooner (@Makuo12 if you're interested then this would be welcome).

**Comment by klensy** [comment]
Title and description need update.

**Comment by clubby789** [comment]
`cc` updates often break things, and this looks like a C compiler related failure. If you revert that part it'll ~probably work

**Comment by clubby789** [comment]
Changes to rustfmt should be made in the [repo](https://github.com/rust-lang/rustfmt).

**Review by ytmimi — CHANGES_REQUESTED** [review]
Please revert the rustfmt changes and open up a new PR in https://github.com/rust-lang/rustfmt

**Comment by Makuo12** [comment]
Okay, I would do that

**Comment by tgross35** [comment]
For the record, there are easier ways to get involved with rust development than updating a finicky lockfiles :) keep an eye out for [E-easy](https://github.com/rust-lang/rust/labels/E-easy) or [E-help-wanted](https://github.com/rust-lang/rust/issues?q=is%3Aopen+label%3AE-help-wanted) issues, or find documentation that you think could be improved. Or stop by on Zulip if there is something specific you might be interested in working on https://rust-lang.zulipchat.com/.

**Comment by Makuo12** [comment]
@tgross35 thank you. Would look at those then

**Pull request closed without merging**
