### PR TITLE
Consuming `emit`

### PR DESCRIPTION
**Pull request by nnethercote**
This PR makes `DiagnosticBuilder::emit` consuming, i.e. take `self` instead of `&mut self`. This is good because it doesn't make sense to emit a diagnostic twice.

This requires some changes to `DiagnosticBuilder` method chaining -- every existing non-consuming chaining method gets a new consuming partner with a `_mv` suffix -- but permits a host of beneficial follow-up changes: more concise code through more chaining, removal of redundant diagnostic construction API methods, and removal of machinery to track the possibility of a diagnostic being emitted multiple times. 

r? @compiler-errors

### CODE REVIEW

**Comment by nnethercote** [comment]
Draft code only for now, apologies for the notifications.

**Comment by nnethercote** [comment]
This is now ready for review.

I'm not 100% certain about the use of the `_mv` suffix for the new chaining methods. I chose a suffix because of prior art like `iter_mut`. And I want it to be short and not something that looks like its part of the method name, which is why I chose `_mv` over something like `_move` -- `span_mv` reads quite differently to `span_move`. I'm happy to hear other suggestions on how to name these new methods. (I actually contemplated just a `2` suffix, e.g. `span2`, but I thought that might trigger rioting in the streets.)

**Comment by oli-obk** [comment]
The suffix seems ok to me. Please open an E-easy issue for ppl to find more uses of the non-moving methods and replace the code with consuming code if reasonable/possible.

@bors r+ p=1 bitrotty

Thanks for finally making `emit` consume. You broke the "add `1` to this counter if you tried" situation

**Comment by nnethercote** [comment]
Thanks for the fast review!

> Please open an E-easy issue for ppl to find more uses of the non-moving methods and replace the code with consuming code if reasonable/possible.

I converted all the places I could find where the consuming methods gave an obviously better outcome, e.g. eliminating a local variable. Those are in the 3rd and 4th commits ("Use chaining..."). There are many remaining cases like:
```
let mut err = struct_err(msg);
err.span(span);
if cond {
    err.code(code);
    err.is_lint();
}
return err;
```
Here the first two lines could be chained, as could the two calls within the `if` block. But you'd still need the local variable so it's not much of a win, and I suspect it's not worth changing them.

**Comment by oli-obk** [comment]
Yea I worried that lots of cases will be like that. I guess we'll tackle this with diagnostic structification

**Pull request merged**
