### PR TITLE
[master] Backport 1.30.1 release notes

### LINKED ISSUE #56135: 1.30.1 missing in master RELEASES.md
https://github.com/rust-lang/rust/blob/master/RELEASES.md contains a section for 1.31.0, but no section for 1.30.1.

### PR DESCRIPTION
**Pull request by emilyalbini**
Fixes #56135

r? @ghost

### CODE REVIEW

**Comment by mark-i-m** [comment]
What is @ghost? Is that a special command to the highfive bot?

**Comment by pietroalbini** [comment]
> What is @ghost? Is that a special command to the highfive bot?

Highfive crashes when you r? a person who's not in the org, and it does nothing. @ghost happens to be a reserved account, so we don't spam anyone's inbox.

**Comment by alexcrichton** [comment]
This has been backported to beta so I'm going to remove this from the milestone

**Pull request merged**
