### PR TITLE
Slightly refactor `TargetSelection` in bootstrap

### PR DESCRIPTION
**Pull request by Kobzol**
Mostly a drive-by refactoring of `TargetSelection` to reduce some manual "windows-gnu" detection and also accesses to the `triple` field.

r? @onur-ozkan

### CODE REVIEW

**Review by onur-ozkan — APPROVED** [review]

**Comment by onur-ozkan** [comment]
Feel free to r=me once rebased.

**Comment by Kobzol** [comment]
I tried to only replace situations where the target was joined as a path, so that the `AsRef<Path>` implementation is used. If I also replaced `target.triple` with `target` somewhere where `Display` is used, that's a bug! Did you find any such case?

**Comment by Kobzol** [comment]
Oh, this one: https://github.com/rust-lang/rust/pull/128983/commits/1c0c2c3ad66f06f1d112ad7388d439846fded606#diff-11a177c4925352bc8852241c59fd49c369df531495f11f81914eb6972783bb8aR522 That's not great, I'll send a fix. Thank you!

**Comment by Kobzol** [comment]
Fixed in https://github.com/rust-lang/rust/pull/129056. Thanks!

**Pull request merged**
