### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Successful merges:

 - #52799 (Use BitVector for global sets of AttrId)
 - #52835 (Fix Alias intra doc ICE)
 - #52841 (resolve: Implement prelude search for macro paths, implement tool attributes)
 - #52854 (fix memrchr in miri)
 - #52899 (tests/ui: Add missing mips{64} ignores)
 - #52908 (Use SetLenOnDrop in Vec::truncate())
 - #52930 (rustc_resolve: record single-segment extern crate import resolutions.)
 - #52939 (Make io::Read::read_to_end consider io::Take::limit)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by alexcrichton** [comment]
@Mark-Simulacrum are you sure this should be retried? That's a 30m+ compile for a crate where it previously took ~5

That looks like an infinite loop in the compiler somewhere?

**Comment by Mark-Simulacrum** [comment]
Those are stage0 compiler artifacts though so it shouldn't/can't be affected right?

**Comment by alexcrichton** [comment]
True yeah, one can hope I guess!

**Pull request closed without merging**
