### PR TITLE
Make a test compatible across python versions.

### PR DESCRIPTION
**Pull request by smmalis37**
Progress on #65063

This PR allows this test to work on both python2 and python3, ~~and it also allows `./x.py test` to fully complete on my system without python2 installed at all.~~

### CODE REVIEW

**Comment by JohnTitor** [comment]
Seems failed in https://github.com/rust-lang/rust/pull/66421#issuecomment-554103131
@bors r-

**Comment by smmalis37** [comment]
If I'm reading that right there's no `python` command on i686-gnu, but there is on other architectures? Does someone who's more familiar with the CI environments know what happened here?

**Comment by mati865** [comment]
It's because installing `python2.7` with apt installs only the suffixed binaries. `python` without suffix is provided by `python` package which points to python2.7 in currently used distributions but that might change in Ubuntu 20.04 as there are plans to remove Python 2 altogether.
This affects other builders as well, scrips are located in https://github.com/rust-lang/rust/tree/master/src/ci/docker

The decision what to do here is up to reviewer.

**Comment by alexcrichton** [comment]
I don't know how best to fix this, but it looks like the CI environment doesn't have a `python` executable.

**Comment by smmalis37** [comment]
The test failed on Linux i686-gnu but succeeded on Linux x86_64-gnu-llvm-6.0. Comparing the packages installed at src/ci/docker/i686-gnu/Dockerfile vs src/ci/docker/x86_64-gnu-llvm-6.0/Dockerfile shows these packages installed on x86_64 but not i686:

g++ vs g++-multilib
llvm-6.0-tools
libedit-dev
libssl-dev
pkg-config
zlib1g-dev

It looks like llvm-6.0-tools depends on python, which means we get lucky on that platform. I'm assuming something similar is true for the other successful platforms. I'll change the makefile back to calling python2.7, and that can switch when all the infrastructure updates to python3. The change to the actual python file will still help, since it won't need to be changed at that point.

**Pull request merged**
