### PR TITLE
Remove all `i` suffixes

### PR DESCRIPTION
**Pull request by tbu-**
They are either constrained to `isize` anyway or correctly fall back to `i32`.

### CODE REVIEW

**Comment by tbu-** [comment]
@alexcrichton Rebased.

**Comment by tbu-** [comment]
@alexcrichton Rebased.

**Comment by tbu-** [comment]
@alexcrichton Fixed test failure, ran `make check` again.

**Comment by frewsxcv** [comment]
Needs a rebase

**Comment by tbu-** [comment]
@alexcrichton Rebased.

**Comment by alexcrichton** [comment]
@bors: r+ 8440329

sorry for all the rebases :(

**Comment by tbu-** [comment]
@alexcrichton Sorry, I ran `make check` locally, does that run all tests?

**Comment by alexcrichton** [comment]
It should yeah, perhaps it was just a merge conflict between r+ and when it was tested?

**Comment by Gankro** [comment]
Github seems to think it's a merge conflict. I sugges we p=1 this change when it's next ready.

**Comment by tbu-** [comment]
@alexcrichton Rebased. Ran `make check`.

**Comment by tbu-** [comment]
@Gankro It looks like you need a colon after the `@bors`.

**Comment by Gankro** [comment]
@tbu- No if you checkout http://buildbot.rust-lang.org/homu/queue/rust your PR is there.

You know you did it right if bors doesn't complain.

e.g.

@bors r+ asdas 

Should have it scream instantly.

**Comment by Gankro** [comment]
Looks like there's some conflicts in old_io

**Comment by alexcrichton** [comment]
Merging this into a rollup I'm making (no need to rebase)

**Pull request merged**
