### PR TITLE
Add the RLS to .exe, .msi, and .pkg installers

### PR DESCRIPTION
**Pull request by efyang**
This directly addresses issue #42157, adding the RLS as a non-default component in the mentioned installers. The windows installers appear to have the right functionality added, but I don't have a machine that runs OSX, so it would be great if someone could test whether my .pkg commit adds the RLS correctly. The final commit also fixes some formatting issues I'd noticed while working on the installers, but I don't know if that's within the scope of this PR, so input would be appreciated.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I don't know enough about this to review.

r? @brson -- maybe you do?

**Comment by alexcrichton** [comment]
Thanks for the PR @efyang, it's looking great!

I tested out the pkg installer locally and it looks like it's not working though unfortunately :(. Oddly enough it looks like it installed nothing, so I'm not really sure what's going on with it... 

Have you verified the windows installers work locally?

**Comment by efyang** [comment]
Yeah, the windows installers work fine locally, and have the RLS set to non-default correctly. I've tried them with and without checking the RLS and they all appear to work fine.

**Comment by alexcrichton** [comment]
Ok nice! Mind double checking the pkg installer scripts to make sure everything checks out? If they still look good I'll try the existing pkg installers and see if they work at all.

**Comment by efyang** [comment]
I just double checked them, and I believe the pkg installer scripts should work, assuming that the original pkg installer scripts work too. I might be missing something here that I might be able to find in the apple docs, but I think checking the existing pkg installers would be helpful.

**Comment by alexcrichton** [comment]
Ok I just checked last night's pkg and it worked ok (installed what I expected) but double checked the pkg I produced yesterday from this branch and it still didn't install anything :(

**Comment by alexcrichton** [comment]
Hm in the logs I'm seeing:

```
May 31 12:53:18 acrichton-23691 installd[531]: ./postinstall: /tmp/PKInstallSandbox.R8iFgf/Scripts/org.rust-lang.rustc.6Hv881/install.sh: line 11: 
	: command not found
May 31 12:53:18 acrichton-23691 installd[531]: ./postinstall: /tmp/PKInstallSandbox.R8iFgf/Scripts/org.rust-lang.rustc.6Hv881/install.sh: line 13: set: -
	: invalid option
May 31 12:53:18 acrichton-23691 installd[531]: ./postinstall: set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
```

**Comment by alexcrichton** [comment]
Apparently for whatever reason that files has CRLF line endings locally but just LF endings online, and I guess the builders check out the submodule with LF line endings? In any case that sounds like it's some weird local problem on my end.

**Pull request merged**
