### PR TITLE
Updated error message E0282

### LINKED ISSUE #35312: E0282 needs to be updated to new format
From: src/test/compile-fail/issue-23041.rs

Error E0282 needs a span_label, a note, and an updated title, updating it from:

```
error[E0282]: unable to infer enough type information about `_`; type annotations or generic parameter binding required
  --> src/test/compile-fail/issue-23041.rs:16:22
   |
16 |     b.downcast_ref::<fn(_)->_>(); //~ ERROR E0282
   |                      ^^^^^^^^
```

To:

```
error[E0282]: unable to infer enough type information about `_` 
  --> src/test/compile-fail/issue-23041.rs:16:22
   |
16 |     b.downcast_ref::<fn(_)->_>(); //~ ERROR E0282
   |                      ^^^^^^^^ cannot infer type for `_`
   |
   = note: type annotations or generic parameter binding required
```

### PR DESCRIPTION
**Pull request by medzin**
Fixes #35312 as part of #35233.

r? @GuillaumeGomez

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good!  

One small request.  I think I was asleep when I wrote the original issue.  Can we change it from: "cannot infer type about `_`" to "cannot infer type for `_`"

Sorry about that :)

**Comment by jonathandturner** [comment]
Great, thanks for updating it!

@bors r+ rollup

**Comment by medzin** [comment]
@jonathandturner fixed! :)

**Comment by jonathandturner** [comment]
@bors r-

Looks like I jumped the gun.  Just let me know when you're ready.

**Comment by medzin** [comment]
@jonathandturner all tests are green now :)

**Comment by jonathandturner** [comment]
Sounds good!

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
@bors: r-

Please squash your last commit.

**Comment by medzin** [comment]
@GuillaumeGomez only last or all to one?

**Comment by GuillaumeGomez** [comment]
All to one please.

**Comment by medzin** [comment]
@GuillaumeGomez done

**Pull request merged**
