### PR TITLE
Add Nicholas Bishop to `.mailmap`

### PR DESCRIPTION
**Pull request by nicholasbishop**

### CODE REVIEW

**Comment by nnethercote** [comment]
This is going to conflict with #105071 when a rollup is attempted because we both have the first name Nicholas :disappointed:

**Comment by nicholasbishop** [comment]
It's a good first name :) I'll rebase once yours merges.

**Comment by nnethercote** [comment]
Let's take this out of the queue for now, to avoid problems for the rollup creators.

@bors r-

**Comment by nnethercote** [comment]
Ok, #105071 has been merged.

**Pull request merged**
