### PR TITLE
Stabilize feature `nonzero_negation_ops`

### LINKED ISSUE #102443: Tracking Issue for negation methods on `NonZeroI*`
Feature gate: `#![feature(nonzero_negation_ops)]`

This is a tracking issue for adding negation methods such as `wrapping_neg()` to the `core::num::NonZeroI{8,16,32,64,128}` types.

ACP: https://github.com/rust-lang/libs-team/issues/105

### Public API

```rust
// core::num

for $Ty in NonZeroI{8,16,32,64,128} {
	pub const fn is_positive(self) -> bool;
	pub const fn is_negative(self) -> bool;
	pub const fn checked_neg(self) -> Option<$Ty>;
	pub const fn overflowing_neg(self) -> ($Ty, bool);
	pub const fn saturating_neg(self) -> $Ty;
	pub const fn wrapping_neg(self) -> $Ty;
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/102342
- [x] #111186
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/111044

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by jmillikin**
Fixes #102443

ACP: https://github.com/rust-lang/libs-team/issues/105

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This will either need a new FCP or confirmation from checked boxes on it, since it was started prior to the addition of the is_positive API. r? @dtolnay as one of those checked boxes.

**Comment by dtolnay** [comment]
I confirmed with Amanieu that at least his approval also applies to `is_positive`.

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
