### PR TITLE
GCC backend subtree update

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
We just finished the [last sync](https://github.com/rust-lang/rustc_codegen_gcc/pull/556) so time to sync back.

cc @antoyo

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Almost forgot:

@bors rollup=never

**Comment by GuillaumeGomez** [comment]
And also a little priority because it's very conflict prone...

@bors p=1

**Comment by saethlin** [comment]
I don't trust that nobody will push a rollup ahead of this.
@bors p=21

**Pull request merged**
