### PR TITLE
Stabilize #![feature(repr_align_enum)] in Rust 1.37.0

### PR DESCRIPTION
**Pull request by Centril**
On an `enum` item, you may now write:

```rust
#[repr(align(X))]
enum Foo {
    // ...
}
```

This has equivalent effects to first defining:

```rust
#[repr(align(X))]
struct AlignX<T>(T);
```

and then using `AlignX<Foo>` in `Foo`'s stead.

r? @nagisa

### CODE REVIEW

**Comment by Centril** [comment]
# Stabilization proposal

I propose that we stabilize `#![feature(repr_align_enum)]`.

@rfcbot merge

Tracking issue: https://github.com/rust-lang/rust/issues/57996
Version target: 1.37 (2019-07-04 => beta, 2019-08-15 => stable).

## What is stabilized

On an `enum` item, you may now write:

```rust
#[repr(align(X))]
enum Foo {
    // ...
}
```

This has equivalent effects to first defining:

```rust
#[repr(align(X))]
struct AlignX<T>(T);
```

and then using `AlignX<Foo>` in `Foo`'s stead.

The documentation on `#[repr(align(X))]` may be found [in the reference](https://doc.rust-lang.org/nightly/reference/type-layout.html#the-alignment-modifiers).

## What is not stabilized

There's not much to say here. `#[repr(align(X))]` is already allowed on `struct` and `union` items. As this extends `align(X)` to `enum` items, the story for `align(X)` with respect to sorts of type definitions should be complete.

## Divergences from RFC

There was no RFC. Rather, we decided [in a language team meeting](https://github.com/rust-lang/rust/pull/57998#issuecomment-459487625) to accept this experimentally since we felt that it was a minor consistent extension of an already existing concept.

## Tests

The tests can be primarily seen in the PR itself. Here are some of them:

- [Unstable book entry being removed](https://github.com/rust-lang/rust/blob/ed2a5115daaffdab30b102405ffcfb222decf444/src/doc/unstable-book/src/language-features/repr-align-enum.md)

- [The feature gate test being removed](https://github.com/rust-lang/rust/blob/ed2a5115daaffdab30b102405ffcfb222decf444/src/test/ui/feature-gates/feature-gate-repr_align_enum.rs)

- [Codegen test](https://github.com/rust-lang/rust/blob/c25e3d2be5825463cf63c518854b583fbc9e8386/src/test/codegen/align-enum.rs)

- [Tests for the dynamic semantics](https://github.com/rust-lang/rust/blob/c25e3d2be5825463cf63c518854b583fbc9e8386/src/test/run-pass/structs-enums/align-enum.rs)

- [A test showing that `repr(align(X))` can be used on `enum`s](https://github.com/rust-lang/rust/blob/c25e3d2be5825463cf63c518854b583fbc9e8386/src/test/ui/attr-usage-repr.rs)

- [Testing the static semantics of `repr(align(X))` on `enum`s wrt. power-of-twos, max alignment, and requiring integer alignments](https://github.com/Centril/rust/blob/c25e3d2be5825463cf63c518854b583fbc9e8386/src/test/ui/repr/repr-align.rs)

## Motivation

As aforementioned, the effects of this proposal with respect to dynamic semantics can be achieved through a generic wrapper struct `AlignX<T>`. However, it is not particularly convenient to achieve the desired effect through `AlignX<T>` particularly when the `enum` in question is part of a public API. This disconnects said `enum` from the alignment and infects pattern matching, construction, and denoting the type-with-alignment. By permitting `#[repr(align(X))]` on `enum` items, both ease of writing and reading can be improved.

## History

+ Originally hinted at in [RFC 1358](https://github.com/rust-lang/rfcs/blob/master/text/1358-repr-align.md#detailed-design) as a backwards compatible extension to `align(X)`.

+ Proposed and implemented in https://github.com/rust-lang/rust/pull/57998 by @niklasf.

  The PR was merged on 2019-02-07. Today is 2019-05-07. This means that the PR was merged over 16 weeks ago, well within acceptable bake-times.

  The PR was reviewed by @nagisa.

**Comment by Centril** [comment]
N.B. Aaron is on leave so I've checked his box.

**Comment by Centril** [comment]
@rfcbot review

**Comment by nagisa** [comment]
r=me on the implementation.

**Pull request merged**
