### PR TITLE
Make std::future a re-export of core::future

### PR DESCRIPTION
**Pull request by taiki-e**
After 1a764a7ef59b9cb2eb31658625a6a7dacc3d819b, there are no `std::future`-specific items (except for `cfg(bootstrap)` items removed in 93eed402adbe9e7a532995500d50716d52eefee9). So, instead of defining `std` own module, we can re-export the `core::future` directly.

### CODE REVIEW

**Comment by taiki-e** [comment]
This seems to fix the problem that `poll_fn` only exists in `core`. https://github.com/rust-lang/rust/pull/79611#issuecomment-736871222

**Comment by Mark-Simulacrum** [comment]
This seems good to me. It doesn't actually appear to expose any new *stable* surface area, as the only diff is poll_fn, which is currently unstable anyway. So this just seems right.

@bors r+

**Pull request merged**
