### PR TITLE
Improve document for `Result::as_deref(_mut)` methods

### PR DESCRIPTION
**Pull request by tesuji**
cc #50264

### CODE REVIEW

**Comment by ratijas** [comment]
> I don't know if there are any practical uses

Maybe just for completeness? Sure someday someone will find a use for it.

**Review by dtolnay — CHANGES_REQUESTED** [review]
I would prefer to do this on the tracking issue since there has been quite a bit of participation from stakeholders there.

Could you update the PR to keep just the documentation changes? We can follow up with a separate stabilization PR after FCP.

**Comment by lzutao** [comment]
Sure. Done.

**Review by dtolnay — APPROVED** [review]
Thanks!

**Pull request merged**
