### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @steveklabnik

### CODE REVIEW

**Comment by frewsxcv** [comment]
For what it's worth:

* British English: initialised
* American English: initialized

**Comment by GuillaumeGomez** [comment]
Why are there so much differences? >.<

**Comment by nagisa** [comment]
Pretty much every case of `-zed` is American English specific. All other Englishes using `-sed`. (similarly for `-ize` and `-ise`). That being said our documentation is predominantly American English (however it pains me being this way), so this change is “correct”.

**Pull request merged**
