### PR TITLE
fix off-by-one error

### PR DESCRIPTION
**Pull request by bmusin**
Fixes https://github.com/rust-lang/rust/issues/47325.

### CODE REVIEW

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
Nice catch, thank you!

@bors: r+ rollup

**Comment by nixpulvis** [comment]
Maybe use an inclusive range to be more clear?

**Comment by bmusin** [comment]
You mean 0..10?

**Comment by nixpulvis** [comment]
Nope, though now that I'm playing with it it looks like it's experamental and kinda a mess imho, see #28237.

Inclusive ranges (in this context) include the last element as well as the rest.

**Comment by nixpulvis** [comment]
I would however strongly encourage a change to `0..10`, since it's helpful to have the same number in the description and the code.

**Comment by varkor** [comment]
This change is now incorrect. The documentation says:
> Let's write the numbers one through ten to a [`TcpStream`]:
The code now writes the numbers from zero through nine. You should add one to `i` in each case. (This will be cleaner with the inclusive range syntax, but as it's not stabilised yet, it's best not to include it.)

**Comment by bmusin** [comment]
@varkor, you meant this?

**Comment by nixpulvis** [comment]
@varkor oh nice catch, I should have read the docs more carefully before suggesting `0..10`. Still I think this looks the best.

**Comment by shepmaster** [comment]
Looks great @bmusin! Please go ahead and squash these commits and we will be good to merge!

**Comment by bmusin** [comment]
Squashed.

**Comment by shepmaster** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
