### PR TITLE
Reduce git clone --depth from 50 (default) to 1

### PR DESCRIPTION
**Pull request by dns2utf8**
This should speedup the builds a little.

### CODE REVIEW

**Comment by dns2utf8** [comment]
This change reduces the clone size from ~90MB to ~60MB, cloning 8460 instead of 84595 objects.

The build time seems to be the same

**Comment by alexcrichton** [comment]
@bors: r+ ca259666a55c84bae8c37be27116dd48d529b357

Thanks!

**Comment by dns2utf8** [comment]
Sorry, I did not know that removing the branch would automatically close the PR

**Pull request merged**
