### PR TITLE
Rust is now post-1.0

### LINKED ISSUE #26178: FAQ "Currently, Rust is still pre-1.0"
The language FAQ states that "Currently, Rust is still pre-1.0".  [https://doc.rust-lang.org/complement-lang-faq.html#is-anyone-using-rust-in-production?](https://doc.rust-lang.org/complement-lang-faq.html#is-anyone-using-rust-in-production?)

### PR DESCRIPTION
**Pull request by Stebalien**
The list of in-production users is probably incomplete. It's based on a [post](https://www.reddit.com/r/rust/comments/2x567m/who_is_using_rust_or_what_projects_that_are/cox7eby) by /u/mozilla_kmc

closes #26178

### CODE REVIEW

**Comment by steveklabnik** [comment]
Can you update this to say explicitly that it's an incomplete list? Also, you may want to mention MaidSafe.

**Comment by Stebalien** [comment]
Done.

**Comment by steveklabnik** [comment]
Thank you! :)

**Pull request merged**
