### PR TITLE
rustdoc: compute maximum Levenshtein distance based on the query

### LINKED ISSUE #82131: [rustdoc] Search results: Make fuzzy search less wild for small words
Fuzzy search is matching too many things [*], e.g.:

- `FRom` due to `FRee`
- `REm` due to `fREe`

It could be improved restricting matches for small words, e.g. for words < 4 in size, match only if 3 characters or more match.

[*]
image

### LINKED ISSUE #103357: search on https://doc.rust-lang.org/ not doing well
I could not figure out a better place to report the issue with https://doc.rust-lang.org/  (which might be an issue on its own, to have a link from the docs to the source code)

The problem is that the search on https://doc.rust-lang.org/ does not seem to function well:

e.g. https://doc.rust-lang.org/std/index.html?search=regex returns lots of hits, none of them related to regex.

OTOH https://doc.rust-lang.org/std/index.html?search=println works quite well.

https://doc.rust-lang.org/std/index.html?search=print starts out quite well, but then also includes things that end with `::pin` and `::hint` that seem to be unrelated.

### PR DESCRIPTION
**Pull request by notriddle**
Preview: https://notriddle.com/notriddle-rustdoc-demos/search-lev-distance/std/index.html?search=regex

The heuristic is pretty close to the name resolver, `maxLevDistance = Math.ceil(queryLen / 3)`.

Fixes #103357
Fixes #82131

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks, looks like a nice improvement! Considering it's quite a big change for users, I'd prefer to have more people from rustdoc to take a look first.

cc @rust-lang/rustdoc

**Comment by jsha** [comment]
Looking at just the results, not the code: this is a big improvement in the results for short and no-results queries. Thanks!

There's still a problem where single-character searches return a lot of `::0` enum fields, which I thought would happen to be fixed by this. But that's not a blocker by any means; presumably we just need to find the fix elsewhere.

**Comment by Manishearth** [comment]
Yeah we should exclude them

**Comment by GuillaumeGomez** [comment]
> That’s because Math.ceil(1/3)=1, and the edit distance between `0` and `X` is 1. The problem with tweaking the heuristic to make the number come out 0 is that the results aren’t really better: I would like `X` to match `XY`, but that one also has an edit distance of 1.

Maybe we should use `floor` instead? Also, it should still have `xy` if you search for `x` since `xy` starts with `x`.

> I’d almost rather just exclude tuple indices from the search index. Is anyone really going to type Some::0 into the search engine?

+1

**Comment by jsha** [comment]
Oh, I thought it was something specific about the `0`; but it's just the combination of:

 - maxLevenshtein for query of length 1 is 1, plus
 - 0 sorts ahead of everything else, plus
 - we cut off results past 100

So, yes, I agree we should just not index these; but also we should use floor. Otherwise, once all the `0`s are gone, any other single-letter idents will match any single-letter queries.

**Comment by GuillaumeGomez** [comment]
Seems like we all agree on removing the tuple elements from the index. I'll send a PR tomorrow.

**Comment by GuillaumeGomez** [comment]
Maybe we should change this behaviour? Something like:

 * If the item name starts with X, then give it a lev distance of 2.
 * If the item name contains X, then give it a lev distance of 3.

I'm curious of what the results would look like.

**Comment by jsha** [comment]
I think it's a mistake to use levenshtein distance also the ranking metric and apply boosts and demerits to it. The existing code already does this to a large extent and it makes things very confusing and hard to maintain. It would be better to more explicitly separate the matching and ranking functionality.

**Comment by GuillaumeGomez** [comment]
That would make things simpler. I'm also curious to see what the results will look like.

**Pull request closed without merging**
