### PR TITLE
Add a note about overflow for fetch_add/fetch_sub

### LINKED ISSUE #34618: Document arithmetic overflow behavior for atomic fetch_add and fetch_sub operations
Are these operations guaranteed to wrap on overflow?  The documentation currently says nothing.

### LINKED ISSUE #40916: Docs for fetch_add/fetch_sub/pow and overflow behavior
[fetch_add](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicIsize.html#method.fetch_add) [fetch_sub](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicIsize.html#method.fetch_sub) [pow](https://doc.rust-lang.org/std/primitive.isize.html#method.pow)

Do docs for those methods need to explain what happens on overflow? There are three possible overflow behaviors: panic, saturate, wrap. Is it obvious what those methods do on overflow?

Perhaps we should explain? I guess `fetch_add` and `fetch_sub` wrap around, while `pow` panics in debug mode and wraps around in release mode.

cc @alexcrichton

### PR DESCRIPTION
**Pull request by ghost**
Fixes #40916 
Fixes #34618

r? @steveklabnik

### CODE REVIEW

**Comment by stjepang** [comment]
I also changed some other docs:

* Instead of using both "previous" and "old", use "previous" consistently.
* Switch from imperative "Add" to "Adds".
* Add quotes where necessary and mirror the docs for atomic integers with the docs for `AtomicBool`.

**Comment by steveklabnik** [comment]
The doc changes look good to me. However, let's

@rfcbot : fcp merge

for libs, to make sure this is the behavior they want specc'd

**Comment by stjepang** [comment]
cc @alexcrichton 
cc @Amanieu

**Comment by alexcrichton** [comment]
@bors: r+

Yeah these are the intended semantics

**Comment by alexcrichton** [comment]
@bors: retry

* builder timed out :(

**Comment by steveklabnik** [comment]
@bors: retry

something went wrong and the job took too long

**Comment by alexcrichton** [comment]
@bors: retry

* centos network issues https://github.com/rust-lang/rust/issues/40474

**Pull request merged**
