### PR TITLE
Stabilize proc macros generating `macro_rules` items

### PR DESCRIPTION
**Pull request by petrochenkov**
Fn-like and attribute proc macros can now generate `macro_rules` items.

cc #54727

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage - @petrochenkov this has sat idle for 7 days, can you please post the status of this PR?

thank you!

**Comment by petrochenkov** [comment]
Busy week, I'll get to it ~next weekend.

**Comment by JohnTitor** [comment]
Ping from triage: @petrochenkov any updates on this?

**Comment by JohnCSimon** [comment]
Ping from triage.
@petrochenkov Just letting you know, this has sat idle for the last three weeks.  
Thank you.

**Comment by petrochenkov** [comment]
## Stabilization report

Function-like macros and attribute macros can now generate `macro_rules` items.

For historical reasons this feature was never gated for derive macros (which were stabilized much earlier than other macro kinds).
So if people need to generate `macro_rules`, they usually just generate derives expanding to `macro_rules` instead of generating `macro_rules` directly.
As a result, the feature is de-facto stable and is actively relied upon by the ecosystem, at least through the [proc_macro_hack](https://crates.io/crates/proc-macro-hack) crate.

Stable proc macros can only use transparent "call-site" hygiene, so in the basic case of a `macro_rules` item generated by a transparent macro, the item will behave as if it was copy-pasted into the call site.
So, names produced by expanding that `macro_rules` item will behave as if the item was written directly - local variables and labels will be hygienic, other names will be unhygienic and `$crate` will refer to the crate containing the `macro_rules` item, not to the proc macro crate.
This behavior is pretty intuitive and we didn't receive reports of bugs or unexpected behavior in this area, AFAIK.
If you want some specific cases tested, please leave a comment.

If some hygiene rules change in the future, they will most probably affect corner cases with some complex nesting and interactions between various kinds of hygiene mixed.
It will affect people to the same extent whether we stabilize `macro_rules`-generating fn-like and attribute macros or not, because they will affect derives anyway.

**Review by eddyb — APPROVED** [review]
This is a pretty straight-forward stabilization, r=me once the decision has been taken.

**Comment by pnkfelix** [comment]
(Lang team hat on): I think @petrochenkov 's stabilization report, as well as the code itself, is excellent, and that we should go ahead and stablize.

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

**Comment by Centril** [comment]
@rfcbot reviewed

**Pull request merged**
