### PR TITLE
Use a larger length/offset for rmeta tables

### PR DESCRIPTION
**Pull request by saethlin**
~A potential fix for https://github.com/rust-lang/rust/issues/112934~
https://github.com/rust-lang/rust/pull/113542 is a much better implementation

r? @ghost

### CODE REVIEW

**Comment by saethlin** [comment]
It looks like the size of rlibs grows between 1% and 30%. That seems a bit steep. Based on the fact that icount/cycles/time are perf-neutral I'm going to try to do some varint encoding.

**Comment by saethlin** [comment]
Of course, varint encoding isn't possible because this is a table format. So instead of a varint encoding, let's try just bumping up number of bytes we encode by a bit. 5 bytes should be enough for a while.

**Comment by saethlin** [comment]
That looks a lot more acceptable to me. We still have some regressions, which is inevitable given the fact that this changing the size of the elements of a table, but they are less.

Now I think we just need a regression test.

**Comment by Kobzol** [comment]
[Here](https://perf.rust-lang.org/compare.html?start=6162f6f12339aa81fe16b8a64644ead497e411b2&end=905eceaa29971ec6f56586b96233d97fb49b37d8&stat=size%3Acrate_metadata) are the metadata regressions.

**Comment by saethlin** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/113542

**Pull request closed without merging**
