### PR TITLE
Fix llvm-tblgen for cross compiling

### LINKED ISSUE #86890: download-ci-llvm does not include llvm-tblgen
In particular, this means you have to *rebuild* llvm for the host when cross-compiling.

I tried this code: `x build --host i686-unknown-linux-gnu`.

I expected to see this happen: The compiler builds successfully.

Instead, this happened:

```
-- Build files have been written to: /home/joshua/rustc3/build/i686-unknown-linux-gnu/llvm/build
running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--" "-j" "8"
ninja: error: '/home/joshua/rustc3/build/x86_64-unknown-linux-gnu/llvm/bin/llvm-tblgen', needed by 'include/llvm/IR/Attributes.inc', missing and no known rule to make it
thread 'main' panicked at '
command did not execute successfully, got: exit status: 1

build script failed, must exit now', /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.44/src/lib.rs:885:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
	finished in 8.264 seconds
failed to run: /home/joshua/rustc3/build/bootstrap/debug/bootstrap build --host i686-unknown-linux-gnu
Build completed unsuccessfully in 0:00:09
```

I think there's a secondary bug which is that x.py hard-codes `llvm` instead of `ci-llvm/`. But that seems easier to fix.

### Meta

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by cuviper**
- Let llvm-config tell us where to find its tools
- Add llvm-tblgen to rust-dev for cross-compiling

Fixes #86890.
r? @jyn514

### CODE REVIEW

**Comment by cuviper** [comment]
Per the mentoring instructions in <https://github.com/rust-lang/rust/issues/86890#issuecomment-1082276225>:

@bors try

**Comment by cuviper** [comment]
Hmm, `bootstrap`'s unit tests don't like trying to execute its mock `llvm-config`...

**Comment by jyn514** [comment]
@cuviper I think you may need to change this to support --dry-run - does using dry run locally reproduce the test failure?

**Comment by cuviper** [comment]
I checked out that try-commit and confirmed that `./x build --target i686-unknown-linux-gnu` does find `ci-llvm/bin/llvm-tblgen`.

I also guarded this to not run `llvm-config` in dry runs. I didn't bother to set approximate paths, but I could if you want.

**Comment by jyn514** [comment]
Thanks! No need to set dummy paths; the only thing it would be useful for is https://github.com/rust-lang/rust/issues/102563 and we're planning to take a different approach there.

@bors r+

**Pull request merged**
