### PR TITLE
[stable] 1.45.2 release

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This is intended to fix the stable breakage noted in #74954, but does *not* close that issue -- there remains investigation and likely nightly/beta fixes need to be issued as well.

r? @pnkfelix

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Note that this is currently targeting *tomorrow*. I think that may be a bit of a rush to get done in time though, so it may be best to delay till Monday. If I don't see an r+ from @pnkfelix or another compiler team member tonight I'll edit for that.

Also added in the track caller regression fix.

I've put up a blog post PR at https://github.com/rust-lang/blog.rust-lang.org/pull/661

**Comment by jsgf** [comment]
Confirming that applying these 1.45.1 resolves the #74954 and doesn't introduce any more problems.

**Comment by Mark-Simulacrum** [comment]
Gah I forgot to actually bump to 1.45.2 -- opened https://github.com/rust-lang/rust/pull/74988 to do that.

**Pull request merged**
