### PR TITLE
[stable] 1.44.1 release

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
See release notes for details (or commits).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm so I'm having trouble updating just rustfmt-nightly. AFAICT the lockfile upstream didn't change at all, except for the version, in the submodule bump here. But when I try to update things locally, I get
```
$ cargo update -p rustfmt-nightly --dry-run
    Updating crates.io index
      Adding ena v0.14.0
      Adding psm v0.1.8
      Adding rustc-ap-arena v659.0.0
      Adding rustc-ap-graphviz v659.0.0
      Adding rustc-ap-rustc_ast v659.0.0
      Adding rustc-ap-rustc_ast_passes v659.0.0
      Adding rustc-ap-rustc_ast_pretty v659.0.0
      Adding rustc-ap-rustc_attr v659.0.0
      Adding rustc-ap-rustc_data_structures v659.0.0
      Adding rustc-ap-rustc_errors v659.0.0
      Adding rustc-ap-rustc_expand v659.0.0
      Adding rustc-ap-rustc_feature v659.0.0
      Adding rustc-ap-rustc_fs_util v659.0.0
      Adding rustc-ap-rustc_index v659.0.0
      Adding rustc-ap-rustc_lexer v659.0.0
      Adding rustc-ap-rustc_macros v659.0.0
      Adding rustc-ap-rustc_parse v659.0.0
      Adding rustc-ap-rustc_session v659.0.0
      Adding rustc-ap-rustc_span v659.0.0
      Adding rustc-ap-rustc_target v659.0.0
      Adding rustc-ap-serialize v659.0.0
      Adding rustfmt-config_proc_macro v0.2.0
    Updating rustfmt-nightly v1.4.14 (/home/mark/Edit/rust-2/src/tools/rustfmt) -> v1.4.16
      Adding rustfmt-nightly v1.4.17
      Adding stacker v0.1.9
warning: not updating lockfile due to dry run
```

I would expect that to just update rustfmt-nightly. Could someone from the cargo team (@ehuss?) or perhaps in the rustfmt world advise?

**Comment by ehuss** [comment]
I don't know why `cargo update` is misbehaving.  It is probably because RLS uses the `[patch]` table for rustfmt.  The following should do as a workaround:

```
cargo update -p rustfmt-nightly
cargo update -p rustfmt-nightly:1.4.17 --precise 1.4.16
```

The second call should revert the RLS to the in-tree copy, and undo the mess the first call makes.

**Comment by ehuss** [comment]
Filed https://github.com/rust-lang/cargo/issues/8355 for the update issue.

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=1000 rollup=never

Preparing artifacts for release on Thursday next week.

**Comment by Dylan-DPC** [comment]
@bors retry p=999

(just so that it runs automatically if things are fine, and doesn't if the tree remains closed)

**Comment by ehuss** [comment]
Hm, I should have noticed this will need #73213.

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

Thanks! Accepted that PR for beta backport as well.

**Pull request merged**
