### PR TITLE
rustdoc: remove support for multi-query search

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This is needed by https://github.com/rust-lang/rust/pull/90630 to make feature changes non-existent.

cc @camelid 
r? @jsha

### CODE REVIEW

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
Meta: could you mark PR names with the code are that they touch, like "rustdoc: Remove support for multi-query search"? (*)
Right now from the title it may look like the PR has something to do with the compiler's query system.

(*) On PR creation, not later, later changes do now show up in email clients that manage email chains.

**Comment by GuillaumeGomez** [comment]
There is the `t-rustdoc` tag for that.

**Comment by GuillaumeGomez** [comment]
Ok, I didn't forget to remove a function this time. \o/

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
>There is the t-rustdoc tag for that.

`T-team` labels may be useful for something, but certainly not for that.
They are not shown anywhere, not in the mail sent by GitHub, not even in the GitHub's own native notification interface.

**Comment by GuillaumeGomez** [comment]
Oh I see, that's a good point. I'll try to not forget next time then.

**Comment by jsha** [comment]
Looks great! I like how much code this cleans up.

I went ahead and change the PR title to include `rustdoc:`. I know it won't affect threads in people's inboxes, but if our goal is to consistently preface Rustdoc PRs with `rustdoc:`, it's still useful.

@bors r+ rollup

**Comment by camelid** [comment]
> I went ahead and change the PR title to include `rustdoc:`. I know it won't affect threads in people's inboxes, but if our goal is to consistently preface Rustdoc PRs with `rustdoc:`, it's still useful.

FWIW, in general I think we only need to prefix PR titles when it's not clear from context. E.g., if the PR title is "Fix intra-doc links bug", there's no need for a "rustdoc:" prefix.

**Pull request merged**
