### PR TITLE
bootstrap: show diagnostics relative to rustc src dir

### LINKED ISSUE #128726: Rust-analyzer + rustc repo: build failures in the standard library are not shown in the editor any more
This is a consequence of https://github.com/rust-lang/rust/pull/128534 plus https://github.com/rust-lang/cargo/issues/9887: on a build failure in the sysroot, `x.py check library` now prints
```
error[E0425]: cannot find function `handle_errors` in this scope
   --> alloc/src/raw_vec.rs:177:25
    |
177 |             Err(err) => handle_errors(err),
    |                         ^^^^^^^^^^^^^ help: a function with a similar name exists: `handle_error`
...
607 | fn handle_error(e: TryReserveError) -> ! {
    | ---------------------------------------- similarly named function `handle_error` defined here
```
Note that the file name no longer includes the leading `library/`. As a consequence, RA cannot locate the error, so it is not shown in the IDE at all.

This will make working on the standard library a lot more painful, unfortunately.
Cc @bjorn3 @epage @Veykril

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/128726

Depends on https://github.com/rust-lang/cargo/pull/14752 propagating to bootstrap cargo

### CODE REVIEW

**Comment by jieyouxu** [comment]
@RalfJung by "Depends on https://github.com/rust-lang/cargo/pull/14752" do you mean this PR is blocked on the cargo PR being merged and synced first?

**Comment by RalfJung** [comment]
> @RalfJung by "Depends on [rust-lang/cargo#14752](https://github.com/rust-lang/cargo/pull/14752)" do you mean this PR is blocked on the cargo PR being merged and synced first?

Yes.

**Comment by albertlarsan68** [comment]
@RalfJung the cargo side has been synced, r=me when CI is green after a rebase :)

**Comment by bjorn3** [comment]
We need to wait until the cargo PR is part of the bootstrap toolchain, right?

**Comment by RalfJung** [comment]
Yeah this will have to wait a few weeks, unfortunateltly.

**Comment by RalfJung** [comment]
The next beta branches on November 22, so I guess the bootstrap bump will be shortly after that.

**Comment by cuviper** [comment]
> Looks like this will change the file paths printed in panics that point at the standard library, by including the leading `library/`. @rust-lang/libs that's an unstable implementation detail we are allowed to change, I assume?

I think that's fine, especially since the `rust-src` component does ship with that `library/` part too.

A downside is that this adds a little bit of bloat, making every standard library path in the binary 8 bytes longer. It's still not much even if all ~1500 files are referenced, but I wonder if some size-sensitive embedded folks will notice.

**Comment by RalfJung** [comment]
@rust-lang/cargo seems like there's again a problem with that cargo path logic...

**Comment by weihanglo** [comment]
The adjustment looks good to me.

**Pull request merged**
