### PR TITLE
Remove metadata decoding DefPathHash cache

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
My expectation is that this cache is largely useless. Decoding a DefPathHash from metadata is essentially a pair of memory loads - there's no heavyweight processing involved. Caching it behind a HashMap just adds extra cost and incurs hashing overheads for the indices. 

Based on https://github.com/rust-lang/rust/pull/119238.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Regression looks like possible noise to me, either way outweighed by improvements. My takeaway is that this is a good change to make, seems like a slight win and also simplifies code.

**Comment by cjgillot** [comment]
r=me once the other PR lands.

**Comment by Kobzol** [comment]
The single small regression is probably just noise for that benchmark returning back to steady state. In any case, it would be definitely offset by the wide range of improvements across the board.

@rustbot label: +perf-regression-triaged

**Pull request merged**
