### PR TITLE
Better handling of tab in error

### PR DESCRIPTION
**Pull request by sanxiyn**
cc #33240.

### CODE REVIEW

**Comment by sanxiyn** [comment]
Ugh, this failed tidy because of (intentional) tab characters.

**Comment by nikomatsakis** [comment]
thanks @sanxiyn! I'll take a look soon.

**Comment by nikomatsakis** [comment]
@sanxiyn 

> Ugh, this failed tidy because of (intentional) tab characters.

I think you can just change the string constant to use a multi-line string `""` string with `\t`, that'd probably be better anyway (more obvious that a tab is present).

I took a quick look at the PR. I'll look a bit more deeply in a bit. This seems like an improvement over the status quo, though I had contemplated some more radical approaches -- for example modifying the source text to convert tabs to spaces, and adjusting column numbers in the annotations appropriately, or maintaining some more complex mapping (the aim there would be to also handle unicode characters more gracefully, I think we have some challenges there still based on the unicode-input tests).

**Comment by sanxiyn** [comment]
Changed to use `\t`.

We could do something more fancy later. This is simply restoring the longstanding behavior introduced in fd98ea8, thereby fixing the regression.

**Comment by nikomatsakis** [comment]
Yeah, good for now. Thanks @sanxiyn ! :)

**Pull request merged**
