### PR TITLE
Added another error to be processed in fallback

### PR DESCRIPTION
**Pull request by alesito85**
This pull request addresses the problem of Rust not being able to read file/directory metadata because the current user doesn't have permission to read the file and are thus inaccessible.

One particular example is `System Volume Information`. But any example can be made by having a file/directory, which the current user can't access even though the system does allow to view the metadata, which is handled by the fallback.

The fallback exists to get the metadata but it was limited to one error type. Having added ERROR_ACCESS_DENIED per Chris Denton's suggestion, file/directory properties are now properly read.

Solution suggested by Chris Denton https://github.com/nushell/nushell/issues/6857#issuecomment-1426847135

### CODE REVIEW

**Comment by alesito85** [comment]
@ChrisDenton hey I've made this PR per your suggestion, works like a charm!

Let me know if anything else should be done (or done better).

**Review by ChrisDenton — APPROVED** [review]
Thanks! Looks good to me. Could you update the comment below to briefly mention `ERROR_ACCESS_DENIED` is returned by files/directories that exist but are inaccessible (and maybe mention "System Volume Information" as an example)?

**Comment by alesito85** [comment]
I've expanded the comment, thanks for your input.

**Comment by ChrisDenton** [comment]
@alesito85 did you push your changes? I'm not yet seeing them.

**Comment by alesito85** [comment]
@ChrisDenton the changes are in now.

**Comment by ChrisDenton** [comment]
Thanks, comment looks good. The only thing I'd ask is to squish the two commits into one, seeing as they're both small.

**Comment by alesito85** [comment]
@ChrisDenton done.

**Comment by ChrisDenton** [comment]
Thanks for contributing to Rust! Let's try to get this merged.

@bors r+ rollup

If all the tests go well then this should be in nightly soon and released in Rust 1.69.

**Pull request merged**
