### PR TITLE
cleanup: use the `for x in &xs` form instead of `for x in xs.iter()`

### PR DESCRIPTION
**Pull request by japaric**
This also implements `IntoIterator` for `HashMap`s and `HashSet`s, and changes the conditionals `for x in option.iter()` statements to the more readable form: `if let Some(x) = option`. (The former looks like an ordinary for-loop, the later clearly states conditional execution).

r? @alexcrichton 
This needs a snapshot before it can land.

### CODE REVIEW

**Comment by alexcrichton** [comment]
> changes the conditionals for x in option.iter() statements to the more readable form: if let Some(x) = option. (The former looks like an ordinary for-loop, the later clearly states conditional execution).

Nice!

**Comment by alexcrichton** [comment]
cc @aturon you'd probably be quite interested in the fallout here.

This is basically r=me, just want to run it by @aturon first as well, nice work @japaric!

**Comment by eddyb** [comment]
:heart_eyes_cat: Glad to see those `for` loops used with `Option` gone, the only argument I've ever heard in their favor was that there's no extra indentation like with `match`.
All the code I've touched recently that effectively matched over an `Option`, with no action in the `None` case, I've converted to `if let`, be it `match` or `for`.
It's amazing how many levels of indentation you can dispose of - makes me a little sad `match` is the way it is, but I like its syntax.

**Comment by japaric** [comment]
Ok, this should be ready to go now. And sorry for hogging the `try` bot, I was sure there were some non-linux errors that I can't find with a local `make check`, but hopefully all of them have been fixed now!

**Comment by aturon** [comment]
Great work as always, @japaric!

**Comment by aturon** [comment]
Huh, there's some discrepancy with the last commit in order and the one bors seems to want. @japaric, any idea what's going on there?

**Comment by japaric** [comment]
@aturon github orders commits chronologically not topologically, the real last commit is 052aa9a

@bors: r=alexcrichton 052aa9a

**Comment by brson** [comment]
Massive patch.

**Pull request merged**
