### PR TITLE
Make Binder's field private and clean up its usage

### LINKED ISSUE #49814: cleanup Binder fields
Part of https://github.com/rust-lang/rust/issues/49810.

The `Binder` type is used to represent higher-ranked regions:

https://github.com/rust-lang/rust/blob/4b9b70c394e7f341b4016fce4cbf763d404b26f9/src/librustc/ty/sty.rs#L645-L653

I have long wanted to make that field private and thus to force users of `Binder` to go through the more "high-level" methods (as an aside, it might be nice to move binder to its own module too, so that `ty` can't use its private fields).

Right now, when we do `ty::Binder(value)`, that means that any things with a debruijn-index of 1 ([soon to be zero](https://github.com/rust-lang/rust/issues/49813)) in `value` will be bound by this binder. Maybe we can add a `ty::Binder::bind(value)` for this. 

On the other hand, there are times when we do not expect `value` to have any bound regions in it -- for those cases we often use `ty::Binder(value)` today, but it'd be better if used `ty::Binder::dummy(value)`, which adds an assertion.

Similarly, any attempt to directly access the "bound" value (`binder.0`) is better written with `binder.skip_binder()`, which makes it more clear what's happening. Better yet is to add an accessor, somewhat like the `def_id` function defined on `Binder<TraitRef<'tcx>>`. This is currently written to access the field `0` directly, which is bad, but the good part is that it is "safe" to do, because `DefId` is a type that never contains a bound name:

https://github.com/rust-lang/rust/blob/4b9b70c394e7f341b4016fce4cbf763d404b26f9/src/librustc/ty/sty.rs#L573-L575

Note that accessing fields which *may* have bound names should ideally preserve the binding level, like the `inputs` function on `Binder<FnSig<'tcx>>`:

https://github.com/rust-lang/rust/blob/4b9b70c394e7f341b4016fce4cbf763d404b26f9/src/librustc/ty/sty.rs#L841-L843

This is saying, given a function like `for<'a> fn(&'a u32) -> &'a u32`, we get back a list of input types like `for<'a> [&'a u32]`. Note that the binder is preserved. (Internally, though, it could be rewritten to use the helper `Binder::map_bound`:

https://github.com/rust-lang/rust/blob/4b9b70c394e7f341b4016fce4cbf763d404b26f9/src/librustc/ty/sty.rs#L697-L701

### PR DESCRIPTION
**Pull request by tmandry**
AKA "tour de rustc"

Closes #49814.

### CODE REVIEW

**Comment by tmandry** [comment]
@nikomatsakis:
While you're in the mindset of reviewing this PR, you might also want to take a look at [this commit](https://github.com/tmandry/rust/commit/4741e2b80a4055a8a891ec9c9aa7203f58b4c3cc). I tried taking out the fns with FIXME(#20664), and they were only used in 4 places. I just can't tell which of those 4 is a valid use of `skip_binder()` and which are wrong :)

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@bors delegate=tmandry

r=me once rebased

**Comment by tmandry** [comment]
I think I got this wrong the first time..

@bors r=nikomatsakis

**Pull request merged**
