### PR TITLE
Use pre-interned symbols in a couple of places

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Review by camelid — APPROVED** [review]
Thanks!

**Comment by camelid** [comment]
Since the queue is so long:

@bors r-
@bors try @rust-timer queue

**Comment by camelid** [comment]
Hmm, looks like bors canceled the try build because I re-`r+`d. Oh well.

**Comment by camelid** [comment]
Sorry, bors glitched and the merge commit had to be force-pushed away. Can you open a new PR?

**Comment by camelid** [comment]
To clarify: while bors says this PR is merged, the merge has been un-done so a new PR has to be opened.

**Comment by bjorn3** [comment]
Done: https://github.com/rust-lang/rust/pull/92743

**Pull request merged**
