### PR TITLE
Implement ExitCodeExt for Windows

### LINKED ISSUE #97914: Suggestion: Add ExitCodeExt for Windows
I welcome the newly stabilized `ExitCode` which allows Termination with an exit code.

I am facing some difficulties using it on Windows however, most programs on Windows if they use the exit code at all return an `HRESULT` or `DWORD`, neither of which are constructible from the current only available impl `From<u8> for ExitCode`. Right now I resort to using pointers to access the internals of `ExitCode` on Windows, which is undesirable. I suggest adding the following windows-specific trait:

```rust
impl From<i32> for ExitCode {
    fn from(code: i32) -> Self { ... }
}
```

Alternatively, a trait named `ExitCodeExt` could also be added for Windows which allows generation of i32 based error codes.

### PR DESCRIPTION
**Pull request by AronParker**
Fixes #97914

### Motivation:

On Windows it is common for applications to return `HRESULT` (`i32`) or `DWORD` (`u32`) values. These stem from COM based components ([HRESULTS](https://docs.microsoft.com/en-us/windows/win32/api/objbase/nf-objbase-coinitialize)), Win32 errors ([GetLastError](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror)), GUI applications ([WM_QUIT](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-quit)) and more. The newly stabilized `ExitCode` provides an excellent fit for propagating these values, because `std::process::exit` does not run deconstructors which can result in errors. However, `ExitCode` currently only implements `From<u8> for ExitCode`, which disallows the full range of `i32`/`u32` values. This pull requests attempts to address that shortcoming by providing windows specific extensions that accept a `u32` value (which covers all possible `HRESULTS` and Win32 errors) analog to [ExitStatusExt::from_raw](https://doc.rust-lang.org/std/os/windows/process/trait.ExitStatusExt.html#tymethod.from_raw).

This was also intended by the original Stabilization https://github.com/rust-lang/rust/pull/93840#issue-1129209143=  as pointed out by @eggyal in https://github.com/rust-lang/rust/issues/97914#issuecomment-1151076755:

> Issues around platform specific representations: We resolved this issue by changing the return type of report from i32 to the opaque type ExitCode. __That way we can change the underlying representation without affecting the API, letting us offer full support for platform specific exit code APIs in the future.__

[Emphasis added]

### API

```rust
/// Windows-specific extensions to [`process::ExitCode`].
///
/// This trait is sealed: it cannot be implemented outside the standard library.
/// This is so that future additional methods are not breaking changes.
#[stable(feature = "windows_process_exit_code_from", since = "1.63.0")]
pub trait ExitCodeExt: Sealed {
    /// Creates a new `ExitCode` from the raw underlying `u32` return value of
    /// a process.
    #[stable(feature = "windows_process_exit_code_from", since = "1.63.0")]
    fn from_raw(raw: u32) -> Self;
}

#[stable(feature = "windows_process_exit_code_from", since = "1.63.0")]
impl ExitCodeExt for process::ExitCode {
    fn from_raw(raw: u32) -> Self {
        process::ExitCode::from_inner(From::from(raw))
    }
}
```

### Misc

I apologize in advance if I misplaced any attributes regarding stabilzation, as far as I learned traits are insta-stable so I chose to make them stable. If this is an error, please let me know and I'll correct it. I also added some additional machinery to make it work, analog to [ExitStatus](https://doc.rust-lang.org/std/process/struct.ExitStatus.html#).

EDIT: Proposal: https://github.com/rust-lang/libs-team/issues/48

### CODE REVIEW

**Comment by thomcc** [comment]
@rustbot label +T-libs-api -T-libs

I don't really know what pitfalls may exist here, so punting the review to @ChrisDenton, who probably does.

r? @ChrisDenton

**Comment by ChrisDenton** [comment]
The idea looks reasonable to me but there is one pitfall I can think of. An exit code of 259 can be taken to mean the process has not exited yet. See [`GetExitCodeProcess`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess). When checking if a process is still active it is more robust to wait on the process handle instead but you can't assume a foreign process will do that.

I'll admit to being uncertain if this is something we want to design around. On the one hand it may be a hazard in the general case. On the other hand, there's nothing wrong with returning 259 if you're in an environment where you know it's not going to be misinterpreted. At the very least I think the docs should warn about this case.

**Comment by ChrisDenton** [comment]
Also cc @yaahc.

**Comment by AronParker** [comment]
That's a good idea, I did not think of that. I added a warning to the documentation of this potential ambiguity.

I believe we should not design around it, if one wants to request the "real" exit code they can always use [`WaitForSingleObject`](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject) in conjunction with [`GetExitCodeProcess`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess) so that `STILL_ACTIVE` / `STATUS_PENDING` is not possible.

**Comment by AronParker** [comment]
> > I apologize in advance if I misplaced any attributes regarding stabilzation, as far as I learned traits are insta-stable so I chose to make them stable. If this is an error, please let me know and I'll correct it.
> 
> I think you may be mistaken here and these should be marked as unstable.

In that case, should I create a tracking issue for this feature or just repurpose the original issue as a tracking issue?

**Comment by ChrisDenton** [comment]
Often "none" is used initially but in this case you can use the original issue number for now. You should probably wait for t-libs-api to sign off on the feature before making a tracking issue.

**Comment by thomcc** [comment]
Yes, new traits aren't insta-stable, it's only new impls of existing ones.

That said, I think you're supposed to file a proposals for new APIs in https://github.com/rust-lang/libs-team now -- see [here](https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html) for info on the process.

Here's a link to the template, I think for the you cover most of the important parts with the PR description, although you may have to move things around: https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29

(I hadn't realized we actually went forward with this, I think it just started this week, sorry that you have to be one of the guinea-pigs 😅).

**Comment by AronParker** [comment]
> Yes, new traits aren't insta-stable, it's only new impls of existing ones.

Ah I see, thank you for clarifying this.

> That said, I think you're supposed to file a proposals for new APIs in https://github.com/rust-lang/libs-team now -- see [here](https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html) for info on the process.
> 
> Here's a link to the template, I think for the you cover most of the important parts with the PR description, although you may have to move things around: https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29

I submitted a proposal right here which includes all original data from this request and more: https://github.com/rust-lang/libs-team/issues/48

> (I hadn't realized we actually went forward with this, I think it just started this week, sorry that you have to be one of the guinea-pigs 😅).

No worries! I understand that Rust is a large project that requires some organizational effort to manage its popularity. I'm thankful that you people take your time to review my request.

**Review by ChrisDenton — APPROVED** [review]
Ok, this ACP process is new but it looks like it's had the time and the libs-api team is in favour of having this in nightly. So I'm going to go ahead and approve.

**Pull request merged**
