### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #59739 (Stabilize futures_api)
 - #59823 ([wg-async-await] Drop `async fn` arguments in async block )
 - #59839 (Warn on unused results for operation methods on nums)
 - #60146 (Update fonts used by rustdoc)
 - #60169 (Warn when ignore-tidy-linelength is present, but no lines are too long)
 - #60177 (Promote rust comments to rustdoc)
 - #60191 (Add f16c target_feature)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by cramertj** [comment]
@centril https://github.com/rust-lang/rust/pull/59823 and https://github.com/rust-lang/rust/pull/59739 will likely conflict due to the former introducing a test that specifies the feature gate stabilized in the latter.

**Comment by Centril** [comment]
@cramertj Dropping the drop PR then :)

**Pull request closed without merging**
