### PR TITLE
Clone submodules recursively

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Partially for #42911 
Not deeply tested.

### CODE REVIEW

**Comment by nagisa** [comment]
This is also done by https://github.com/rust-lang/rust/pull/42899, which seems like it is likely to be r+d fairly soon.

**Comment by Mark-Simulacrum** [comment]
Well, partially. I'm going to leave a comment there mentioning that the init_repo script needs updating as well

**Comment by nrc** [comment]
r? @alexcrichton 

I've undone the submodule stuff in the RLS, so this is not necessary for the RLS now, but it might be good to have anyway?

**Comment by aidanhs** [comment]
I'm pretty confident this is going to be superseded by #42899 per https://github.com/rust-lang/rust/pull/42899#issuecomment-311504370, but I really appreciate you raising this PR @ishitatsuyuki because it's provided a useful hint for what we need to change in `init_repo.sh`.

I'll close this PR if appropriate when the other one gets merged.

**Comment by aidanhs** [comment]
This has been merged as part of #42899. Thanks again @ishitatsuyuki!

**Pull request closed without merging**
