### PR TITLE
rustdoc-json: More tests, and better jsondocck errors

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
Helps with #81359

r? @CraftSpider 

@rustbot modify labels: +A-rustdoc-json +T-rustdoc +A-testsuite

### CODE REVIEW

**Comment by CraftSpider** [comment]
Looks good, thank you!
@bors r+

**Comment by aDotInTheVoid** [comment]
Rebased to master, and fixed tests, needs reaproval

@rustbot ready

**Pull request merged**
