### PR TITLE
self-profile: measure query result hashing

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR adds self-profile events for query result hashing. The PR is still a work in progress. Before I spend time on cleaning it up I want to check if turning on these measurements by default adds a lot of overhead.

cc @wesleywiser
r? @ghost

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@rust-timer build 1535443fd4b1711e755362c58adf11e9da118a51

**Comment by michaelwoerister** [comment]
So, that's interesting:
- Adding the profiling events does not really add overhead, which is great.
- Query result hashing (under the name of `$ string` in the detailed view) does not amount to much overhead these days, it seems: 
  - up to 8% for the absolute worst case (baseline incremental check builds), 
  - closer to 2% for debug builds,
  - and below 0.5% for release builds.

It's good to finally get more detailed numbers for things like this for every commit `:)`

**Comment by hdhoang** [comment]
ping from triage, is this ready for review? thanks!

**Comment by michaelwoerister** [comment]
I'll implement this properly in a new PR at some point.

**Pull request closed without merging**
