### PR TITLE
add options to use optimized and mangled compiler builtins

### PR DESCRIPTION
**Pull request by stlankes**
In principle the compiler builtin features are also offered to alloc and std.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I guess this is via -Zbuild-std?

r=me with commits squash

**Comment by stlankes** [comment]
Yes, I used it via -Zbuild-std. For instance, the mangled version would help me to build a libos. I would enabled via https://github.com/hermitcore/libhermit-rs/blob/master/.cargo/config#L3.

**Pull request merged**
