### PR TITLE
More unescaping cleanups

### PR DESCRIPTION
**Pull request by nnethercote**
More minor improvements I found while working on #118699.

r? @fee1-dead

### CODE REVIEW

**Review by fee1-dead — APPROVED** [review]
Thanks!

**Comment by lqd** [comment]
This looks most likely to me to be the ongoing noise threshold wiggling on these benchmarks: they should disappear in the next PR we merge.

**Comment by pnkfelix** [comment]
I agree with @lqd; this looks the noise threshold dipped based on a local lull in the amount of noise.

@rustbot label: +perf-regression-triaged

**Pull request merged**
