### PR TITLE
Revert clippy lint [`filter_map_bool_then`]

### PR DESCRIPTION
**Pull request by Centri3**
r? @Manishearth

Issue in question is https://github.com/rust-lang/rust-clippy/issues/11309.

We usually wait until the next sync but this ICE is entirely unpreventable and happens often for code where type annotations are needed alongside a lifetime parameter so I think it's a good idea to revert it here. Also, this got into 1.71.1: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=620a95846a0e4810dffb39d7594d62d7

### CODE REVIEW

**Comment by Centri3** [comment]
Here's a minimized case that *requires* type annotations to compile, but ICEs: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=83fbcc68e86fcb1cc9d03652136186b5

**Comment by ChrisDenton** [comment]
This looks like it has already been merged so I'm not sure why it's in the queue again. I'll cancel it now but feel free to restart if this was intentional.

@bors r-

**Comment by blyxyas** [comment]
Yep, this was already completed shouldn't be merged again.

**Pull request merged**
