### PR TITLE
Fix UB in transmute

### PR DESCRIPTION
**Pull request by gmorenz**
The current code mutates through a `&` reference, this fixed that.

We could remove `get_global_ptr` and `transmute` entirely by using `#![feature(drop_types_in_const)]`, I'm not sure if this would be preferred.

### CODE REVIEW

**Comment by brson** [comment]
This is really tricky code and seems to have more problems than just transmuting `&T` to `*mut T`. @eddyb has opinions.

**Comment by eddyb** [comment]
@gmorenz So this change by itself doesn't fix much, borrowing `static mut` is by itself problematic.
I was worried about `#![feature(drop_types_in_const)]` not working at stage0, but that's not true.

I think we can defer the problem of replacing `static mut` with `static` and an `UnsafeCell` wrapper (eventually this should be `Mutex<Vec<Vec<u8>>>` anyway, @Amanieu's `parking_lot` would make that possible), if all accesses are direct.
Still needs an `Option` for now because `Vec::new` is not `const fn` but I would remove the `Box` wrapping anyway, it's only there so `usize` can be used.

**Comment by eddyb** [comment]
In other words, yes, `#![feature(drop_types_in_const)]` instead of `transmute` is preferred.

**Comment by gmorenz** [comment]
@eddyb I've updated this to use `drop_types_in_const` and not mutably borrow the `static mut`. I'm somewhat curious about your comment that "borrowing `static mut` is by itself problematic.`, is it just something that we prefer to avoid because it's easy to break aliasing rules, or is it always undefined behaviour or something?

**Comment by eddyb** [comment]
@bors r+ Thank you!

@gmorenz It's arguably not always UB, but it's really easy to misuse, and some strict memory models might make a lot of possible uses of `static mut` UB and MIR optimizations could then act on that.

To build a proper wrapper around it, you want some `UnsafeCell`(-based abstraction) inside the `static mut` and to never borrow it mutably directly - but then you can do the same thing with a `static`, which makes the `mut` part an unnecessary footgun.
The caveat is that to create an `UnsafeCell` in a `static`, you need the ability to call a `const fn` from its initializer, which is not something that has been stabilized yet, so we can't even deprecate `static mut`.

**Comment by eddyb** [comment]
@alexcrichton Are there known valgrind issues around such globals? Should I hunt for codegen bugs?

**Comment by alexcrichton** [comment]
Hm not that I know of, that does look suspicious though...

**Comment by eddyb** [comment]
Sorry for letting this sit for this long, let's try again (just in case it was transient or a fixed MIR regression).

@bors retry

**Comment by mrhota** [comment]
@gmorenz @eddyb anything else to do here?

**Comment by eddyb** [comment]
I honestly have no idea how this goes wrong.

**Comment by gmorenz** [comment]
I also have no idea what the problem is, I think (though I'm not an expert) that the current set of optimizations doesn't take advantage of anything that might break the current code so merging this PR isn't high priority.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Pull request closed without merging**
