### PR TITLE
Extend -Zdump-mir output with two-phase borrow info

### PR DESCRIPTION
**Pull request by pnkfelix**
This should cause no breakage since its just injecting a comment `/*2pb*/` (and the `-Zdump-mir` output is unstable anyway).

### CODE REVIEW

**Comment by lcnr** [comment]
generally in favor even though the representation isn't great. I am not sure how long it would take me to figure out what `/* 2pb */` means. Can't quickly think of a better alternative though '^^

r? @oli-obk

**Comment by oli-obk** [comment]
We could include more information in the `//` comments after the statement, by adding an arm for `Rvalue::Ref` in https://github.com/rust-lang/rust/blob/3af7df91fcbe4c5197e55dc78838aeb5aa978d89/compiler/rustc_middle/src/mir/pretty.rs#L501

**Comment by pnkfelix** [comment]
@oli-obk can you spell out how much more info you think you'd want? Right now this really is just a boolean flag, so the presence/absence of a tag like `/*2pb*/` is all I could think of to include.

(Maybe you're saying you'd want to know about when the reservation begins versus when the exclusive access itself actually begins, which I would agree would be superior, but I do not think that information is directly reflected in the MIR structure, and I think I'd bias towards making the `dump_mir` output merely reflect existing structure rather than have it attempt further deductions in the `dump_mir` code itself...)

**Comment by pnkfelix** [comment]
(I have been musing whether there would be value in having the MIR itself use general structure where *every* mutable borrow is modelled as a two-phase borrow, with distinct "reserve-mut" and "take-mut" operations. But that is a **huge** change that would need far broader discussion.)

**Comment by oli-obk** [comment]
> Right now this really is just a boolean flag, so the presence/absence of a tag like `/*2pb*/` is all I could think of to include.

Oh, I don't mean more information, just clarifying what `2pb` means in a comment, similar to how we have comments for constants giving their type and potentially verbose value

**Comment by oli-obk** [comment]
r=me with either the new comments added or not ^^

@rustbot author

**Comment by JohnCSimon** [comment]
@pnkfelix Ping from triage:  Can you post your status on this PR? This has sat idle for a few months.

**Comment by JohnCSimon** [comment]
@pnkfelix 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

**Pull request closed without merging**
