### PR TITLE
Remove -Zdep-tasks.

### PR DESCRIPTION
**Pull request by cjgillot**
This option is not useful any more, we can use `tracing` and `RUSTC_LOG` to debug the dep-graph.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
fixes https://github.com/rust-lang/rust/issues/116419 :D

**Comment by cjgillot** [comment]
That issue made me think of this PR. But we probably can ICE using `RUSTC_LOG`.

**Review by davidtwco — APPROVED** [review]
Apologies for the delay in getting to this, LGTM.

**Pull request merged**
