### PR TITLE
Remove valgrind test suite and support from compiletest, bootstrap and opt-dist

### LINKED ISSUE #44816: run-pass-valgrind tests don't actually run in valgrind
compiletest requires the `--valgrind-path` parameter to be set or it treats run-pass-valgrind tests as normal run-pass tests. It doesn't appear that the build infrastructure ever actually sets this, though.

### PR DESCRIPTION
**Pull request by jieyouxu**
The `run-pass-valgrind` test suite is not exercised in CI, and as far as I'm aware nobody runs it (asked in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Are.20the.20valgrind.20tests.20even.20used.20by.20anyone.3F). What's remaining of valgrind support in compiletest isn't even properly hooked up with bootstrap.

The existing valgrind logic in compiletest is also straight up questionable, i.e.

https://github.com/rust-lang/rust/blob/1b3b8e7b0265162853c650ead09905bc3cdaeae9/src/tools/compiletest/src/runtest/valgrind.rs#L7-L12

It just runs valgrind tests as `rpass` if no valgrind path is provided to compiletest from bootstrap -- but bootstrap doesn't even pass a valgrind path to compiletest in the first place, so this always ran as `rpass` tests. So what is this even testing?

So if it's not testing anything, let's delete it.

Closes #44816 by deleting the test suite :3

### CODE REVIEW

**Review by Kobzol — COMMENTED** [review]
There's also `"ignore-mode-run-pass-valgrind"`, but I see that's being removed in https://github.com/rust-lang/rust/pull/131346.

In terms of the bootstrap and opt-dist changes, LGTM. You can r=me unless someone wants to do an MCP.

**Review by Kobzol — APPROVED** [review]

**Comment by fmease** [comment]
This would fix https://github.com/rust-lang/rust/issues/44816 from 2017 (found via https://github.com/rust-lang/rust/pull/44802#issuecomment-331749946 via `tests/run-pass-valgrind/issue-44800.rs`).

**Comment by jieyouxu** [comment]
I was not aware that this was broken since 2017, that is funny :3

**Comment by jieyouxu** [comment]
Since the MCP isn't strictly required (it's marked as accepted https://github.com/rust-lang/compiler-team/issues/792 because it's not really necessary but still useful as a way to announce the change),

@bors r=@Kobzol

**Pull request merged**
