### PR TITLE
Use two words for "file name"

### PR DESCRIPTION
**Pull request by ChrisDenton**
While both "file name" and "filename" are perfectly cromulent, "file name" is more consistent with existing usage in the standard library. I believe we should try to be consistent where we can.

E.g. [`Path::file_name`](https://doc.rust-lang.org/std/path/struct.Path.html#method.file_name) and [`DirEntry::file_name`](https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.file_name)

### CODE REVIEW

**Comment by ChrisDenton** [comment]
This would break any usage of this (unstable) API, so...

@rustbot label +T-libs-api -T-libs

**Comment by Jerrody** [comment]
> While both "file name" and "filename" are perfectly cromulent, "file name" is more consistent with existing usage in the standard library. I believe we should try to be consistent where we can.
> 
> E.g. [`Path::file_name`](https://doc.rust-lang.org/std/path/struct.Path.html#method.file_name) and [`DirEntry::file_name`](https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.file_name)

The correct usage of this word is `filename`. You can check this in any dictionary.

**Comment by joshtriplett** [comment]
@ChrisDenton While I agree that we do have several stable function names that use `file_name`, and if we add more function names we may want to use `file_name` for consistency and knowledge transfer, the word in more common usage is `filename`, and I think our documentation *text* and names such as `InvalidFilename` should reflect that. I don't think we should make this change; I think we should fix places (that aren't part of function names) that say "file name" instead.

**Comment by ChrisDenton** [comment]
Fair enough.

**Pull request closed without merging**
