### PR TITLE
Document {:.*} syntax with named/positional parameters

### PR DESCRIPTION
**Pull request by shahn**
Inspired by #32391.

### CODE REVIEW

**Comment by shahn** [comment]
Note that this is at most part of the solution to this problem, as pointed out on the original bug report.

**Comment by nodakai** [comment]
We need to begin with rewriting this part:

> Although a `usize` can be printed with `{}`, it is invalid to reference an argument as such. For example this is another invalid format string:
>
> `{:.*} {0}`

This is hardly informative.

Not to mention the serious discrepancy between the implementation and the document...

**Comment by shahn** [comment]
Closing this because clearly more thought on what the behaviour is/should be is warranted.

**Pull request closed without merging**
