### PR TITLE
[WIP] Always verify incremental hash

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by jyn514** [comment]
@Aaron1011 what's the difference between this and https://github.com/rust-lang/rust/pull/83007 ? Did that PR just miss one of the verify calls?

**Comment by Aaron1011** [comment]
@jyn514: https://github.com/rust-lang/rust/pull/83007 was a more minimal version of this, to reduce the performance impact. Based on how many bugs that that PR has already found, I suspect that there might be more bugs lurking in the `HashStable` impls.

**Comment by Aaron1011** [comment]
I would really like to be able to land this, but the perf impact is terrible.

I had hoped that switching to HighwayHash would help, but it actually appears to *decrease* performance: https://github.com/rust-lang/rust/pull/84229

**Comment by Mark-Simulacrum** [comment]
On larger crates the perf impact is only ~5%, so it's not *too* horrible. I think I'd personally like us to squash known bugs before landing this (e.g., the syn failure), so we're not just accumulating more bugs, but other than that it seems OK.

Is there a possibility we can optimize the incremental verification a bit?

It looks like it does several things:

* checks if dep node is green - this is a hash table lookup and an array lookup
* computes the hash - not really optimizable?
* looks up the old hash - again, this is a hash table lookup and an array lookup

At least the first of these seems.. not necessary? Both of the hash table lookups are also with the same key, I think, so we could optimize out the double hashing there with some manual work.

I don't know if it makes sense to do a perf run which just computes the hash but doesn't actually compare it - maybe wrapping in black box or something - to check if that's where all of the overhead is coming from. It probably is, but even shaving off a few dozen instructions from each call might make a nice difference here?

**Comment by Aaron1011** [comment]
> I think I'd personally like us to squash known bugs before landing this (e.g., the syn failure), so we're not just accumulating more bugs

This change would only reveal existing bugs that were currently going undetected. If you think that this PR might cause additional ICEs, then I would argue that that's a reason to land it *sooner* - those bugs could be causing miscompilations.

**Comment by Mark-Simulacrum** [comment]
Yeah, that's a good point. FWIW I am personally willing to r+ this PR "as-is" (I'd like to see the description updated with some details on why) -- I do think the performance isn't ideal but it's also not that bad in most cases.

**Comment by bjorn3** [comment]
For clap-rs-check incr-patched this slows down death_check by 55x.

**Comment by bstrie** [comment]
Converting this WIP PR to Draft to hide it from the triage queue.

**Pull request closed without merging**
