### PR TITLE
Disable field reordering

### PR DESCRIPTION
**Pull request by ahicks92**
This was decided via IRC and needs a backport to beta.  Basically, #37429 broke servo, and probably needs an announcement and opt-in flag.  I didn't run all tests locally but think I've already reverted all the ones that need to be reverted.

r? @nikomatsakis

### CODE REVIEW

**Comment by sfackler** [comment]
Out of curiosity, was the breakage due to bugs in the compiler or in servo?

**Comment by camlorn** [comment]
Servo, but leading to us discussing how to roll out these sorts of changes and raising the question "what about other people?"  The longterm plan for the change isn't yet decided.

**Comment by sfackler** [comment]
Cool, makes sense. This was always the result I feared of us delaying making the change for however many years its been since that RFC.

**Comment by nikomatsakis** [comment]
Nominated for beta (and marked as accepted).

cc @rust-lang/compiler

**Pull request merged**
