### PR TITLE
Several Minor API / Reference Documentation Fixes

### LINKED ISSUE #24882: std::path::Path::starts_with documentation unclear
The [current documentation](https://doc.rust-lang.org/std/path/struct.Path.html#method.starts_with) for `std::path::Path::starts_with` does not specify that it uses components as `base`. For example as described in the current documentation I expected to be able to use characters as `base` to find hidden files/directories as such:

```Rust
fn is_dot(dir: &PathBuf) -> bool {
    if dir.starts_with(".") {
        return true;
    } else {
        return false
    }
}

fn main() {
    let path = PathBuf::from("/home/user/.dotfile");
    let rel_path = path.relative_from("/home/user").unwrap();
    println!("{}", path.display());
    println!("{}", rel_path.display());
    if is_dot(&PathBuf::from(rel_path)) {
        println!("{} is dot", rel_path.display());
    }
}
```

As described in the documentation I expected `is_dot(&PathBuf::from(rel_path))` to be evaluated as true when it does not

### LINKED ISSUE #25233: Documentation for `thread_local!` should link to docs for `LocalKey`
The documentation for [`thread_local!`](http://doc.rust-lang.org/std/macro.thread_local!.html) isn't very usable right now. It should link to the docs for [`LocalKey`](http://doc.rust-lang.org/std/thread/struct.LocalKey.html). Or maybe some of the docs for `LocalKey` should be moved to `thread_local!`.

A similar situation applies to `scoped_thread_local!`.

### LINKED ISSUE #25250: FromStr::from_str method doc comment is inaccurate
http://doc.rust-lang.org/1.0.0-beta.4/std/str/trait.FromStr.html#tymethod.from_str

> Parses a string s to return an optional value of this type. If the string is ill-formatted, the None is returned.

This description is probably leftover from when `from_str` returned an `Option`

### PR DESCRIPTION
**Pull request by bluss**
Several Minor API / Reference Documentation Fixes
- Fix a few small errors in the reference.
- Fix paper cuts in the API docs.

Fixes #24882
Fixes #25233
Fixes #25250

### CODE REVIEW

**Comment by steveklabnik** [comment]
This says it can't be merged. Can you rebase?

**Comment by bluss** [comment]
Rebased. Intelligently enough it conflicted a previous of my own PRs.

**Comment by steveklabnik** [comment]
Thanks!

**Comment by frewsxcv** [comment]
Is it too late to get this backported?

**Comment by steveklabnik** [comment]
@frewsxcv i am backporting the entire book, reference, and grammar right before the release.

**Comment by frewsxcv** [comment]
:+1:

**Pull request merged**
