### PR TITLE
std: Partial fix for #33368

### PR DESCRIPTION
**Pull request by lhecker**
This partially fixes a problem with `std::panic::catch_unwind` not being compatible with coroutines due to holding onto a thread-local reference across a user providden callback.

Thanks @arielb1!

_Note:_ Unfortunately I was incapable of testing this PR because compilation of librustc failed for [some reason](https://gist.github.com/lhecker/f08ebff4b772a1a5fceaa43e99fc7327) and I couldn't figure out why.

### CODE REVIEW

**Comment by alexcrichton** [comment]
As I mentioned before, this is not sufficient for actually getting coroutines to work with the standard library. Any usage of TLS can end up causing segfaults in a program with coroutines due to LLVM's optimizations today. The hack of `#[inline(never)]` can get *this specific case* working, but for example calling `thread::panicking` is enough to cause a segfault.

**Comment by lhecker** [comment]
I know @alexcrichton. I know! As I said multiple times before!

Can you wrap `thread::panicking` inside a `#[inline(never)]` wrapper? Yeah you can.
Can you do something about `panic::catch_unwind`? No.

Can't you merge this please? Really... It really saddens me to hear from you that just because we can't fix it a 100% it's not worthy to fix it all. :disappointed: There will never be a working TLS solution for coroutines, you know?

As I said: you can circumvent _every_ relevant use of TLS in the entire stdlib as well as all relevant crates right now, except for _this_ one specific single method right here. In my opinion this is a very worthy change which has no downsides and only upsides. Right? :smiley:

**Comment by lhecker** [comment]
I mean... @alexcrichton. You're aware that almost all the problems that could ever happen with Rust and Coroutines are things that are well known in high-performance server implementations in C++? It's easy to understand why TLS-using methods are dangerous and it's usually easy to circumvent. But for a server to be fault-resistent it needs to have reliable crashes of coroutines.

**Comment by lhecker** [comment]
I mean... we could also declare `thread::panicking` as `#[inline(never)]` or do you want to say that coroutines are incompatible with Rust? That would be quite... bad.

**Comment by aturon** [comment]
cc @rust-lang/libs 

This thread is highlighting a policy issue we should discuss. Do others on the libs team have thoughts?

**Comment by aturon** [comment]
cc @rust-lang/lang as well.

**Comment by zonyitoo** [comment]
It seems that it is impossible to use Rust to develop any Coroutine libraries now, because it is impossible to bypass the libstd!!! With the current libstd design, we cannot switch contexts because it will crash everything.

Or maybe we can fork a libstd to build our own version of that?

**Comment by lhecker** [comment]
* I think it's a option to fork Rust to provide a Go like environment, but it would probably be hardly feasible to maintain that.
* Making TLS access `inline(never)` really does degrade performance of repeated access in the same function (after optimization) _severely_ (I think it's at least halfed). But is TLS even used that often in hot-paths in Rust? I did not find any docs on how to do perf. regression tests in Rust.
* Adding a option akin to the exchangeable allocators or panic runtimes, would be feasible too, but probably hard to implement. Is that the only option though?
* Not supporting coroutines at all or even not supporting them in the near future would be a bad idea though, because they are just so quintessential for many high-performance systems, which is something Rust wants to excel in, right?

**Comment by lhecker** [comment]
Oh and I'd like to highlight that a matching issue already exists: https://github.com/rust-lang/rust/issues/33368

As I said: There are a couple solutions for this and implementing one of them would be quite advantageous for Rust to be adopted for server software. This PR might still be useful depending on the outcome though.

**Comment by alexcrichton** [comment]
The libs team discussed this PR during triage yesterday, and the conclusion was that we probably don't want to merge this at this time. We decided that we're amenable to supporting coroutines in the standard library perhaps one day (so long as it comes at no cost to other users), but this is unfortunately not enough to actually fix compatibility in the standard library itself (TLS is overall a major problem). As a result we don't want to take piecemeal PRs like this for now which fix bugs as they come up, but rather fix the problem at the source (TLS in this case).

For now I'm going to close this in light of that decision, and we can continue discussion on #33368

**Comment by alexcrichton** [comment]
Ah, and one other things I forgot to mention. A great fix for this would be to actually just not use TLS at all here. That's somewhat costly in terms of the overhead of catch_panic, so getting rid of that would be great entirely! (may be tricky though)

**Comment by lhecker** [comment]
@alexcrichton Thanks for taking your time for this (now) useless PR. I'm sorry for that. :sweat_smile: 
I've updated the initial post with the issue description in #33368 to better reflect the actual issue.
It also contains 4 possible solutions - I'd be cool if the libs teams could take a look at it in the near future, so we (@zonyitoo and me from the coio project) can move on and plan ahead for whatever the result of your discussion is (like writing a RFC for instance or code for Rust). :blush:

**Comment by zonyitoo** [comment]
It seems that someone is going to add coroutine support directly to LLVM, which means that it is possible to tell LLVM not to inline TLS calls between context swaps.

https://internals.rust-lang.org/t/llvm-coroutines-to-bring-awarness

**Pull request closed without merging**
