### PR TITLE
Bump racer and home

### PR DESCRIPTION
**Pull request by Eijebong**
This removes 10 dependencies from the build :tada:

### CODE REVIEW

**Comment by Eijebong** [comment]
Rebased

**Comment by kennytm** [comment]
@bors r=Mark-Simulacrum

Unfortunately I guess you'll need to prepare for another rebase because many PRs are also changing Cargo.lock 😥

**Comment by Eijebong** [comment]
I don't even rebase, I just reset to master and rerun the update command :p It's pretty easy.

**Comment by Eijebong** [comment]
rebased

**Comment by Eijebong** [comment]
git submodules are weird sometimes...

**Comment by pietroalbini** [comment]
Bors is stuck...

@bors force

**Comment by kennytm** [comment]
@bors retry 

Something's wrong with the GCC FTP server.

**Comment by Eijebong** [comment]
> Build execution time has reached the maximum allowed time for your plan (180 minutes).

**Comment by alexcrichton** [comment]
@bors: retry p=0 rollup

I pushed to master so this'd need to get retested, I don't think this needs to be high priority as we've got a ton of other fixes in the queue. This passed almost all tests to switching to rollup priority

**Pull request merged**
