### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by ehuss**
14 commits in aa6872140ab0fa10f641ab0b981d5330d419e927..974eb438da8ced6e3becda2bbf63d9b643eacdeb
2020-07-23 13:46:27 +0000 to 2020-07-29 16:15:05 +0000
- Fix O0 build scripts by default without `[profile.release]` (rust-lang/cargo#8560)
- Emphasize git dependency version locking behavior. (rust-lang/cargo#8561)
- Update lock file encodings on changes (rust-lang/cargo#8554)
- Fix sporadic lto test failures. (rust-lang/cargo#8559)
- build-std: Fix libraries paths following upstream (rust-lang/cargo#8558)
- Flag git http errors as maybe spurious (rust-lang/cargo#8553)
- Display builtin aliases with `cargo --list` (rust-lang/cargo#8542)
- Check manifest for requiring nonexistent features (rust-lang/cargo#7950)
- Clarify test name filter usage (rust-lang/cargo#8552)
- Revert Cargo Book changes for default edition (rust-lang/cargo#8551)
- Prepare for not defaulting to master branch for git deps (rust-lang/cargo#8522)
- Include `+` for crates.io feature requirements in the Cargo Book section on features (rust-lang/cargo#8547)
- Update termcolor and fwdansi versions (rust-lang/cargo#8540)
- Cargo book nitpick in Manifest section (rust-lang/cargo#8543)

### CODE REVIEW

**Comment by ehuss** [comment]
@bors p=1 rollup=never

Don't rollup, this includes several major changes.

Requesting review from @Mark-Simulacrum because this updates a dependency used by almost everything. I've run some tests, and I haven't run into any issues.

Unfortunately I don't remember why the update to termcolor was being delayed. I thought there were still some issues on Windows, but I did a few tests on Windows 8 and the colors looked OK.

**Comment by Mark-Simulacrum** [comment]
Hm, so there is this: https://github.com/rust-lang/rust/pull/63725#issuecomment-522832767

Do you happen to have Windows 7 or 8 handy to try and see if those issues have since been solved?

**Comment by ehuss** [comment]
Yes, I already tested on Windows 8, and the colors look OK to me. https://github.com/kennytm/fwdansi/issues/1 got fixed (that's why it is updated here).  My concern was https://github.com/kennytm/fwdansi/issues/2, but I don't remember exactly why I filed that.  I *think* Cargo (and rustc, etc.) uses simple enough colors that it isn't an issue.

**Comment by ehuss** [comment]
And once this lands on nightly, I'll do some more testing, and if everything looks good, I will close https://github.com/rust-lang/cargo/issues/8089 and https://github.com/rust-lang/rust/issues/55769.

**Comment by Mark-Simulacrum** [comment]
Okay. That's good enough for me -- I suspect getting this landed and rolled out to the community at large is the best way to determine if this breaks anyone's workflow anyway :)

@bors r+

**Comment by ehuss** [comment]
@bors retry
flaky test: https://github.com/rust-lang/cargo/issues/8564

**Comment by Mark-Simulacrum** [comment]
This was a performance regression, likely due to https://github.com/rust-lang/cargo/pull/8560.

Looking at the results, it seems the two crates affected, cargo and script-servo, had a roughly [0.5s](https://perf.rust-lang.org/detailed-query.html?commit=6e50a225fd67576e43bab1d4dfa3c97f310786a8&base_commit=fb0b1237b12e949320ccd31a6741f03425fc9a66&benchmark=cargo-opt&run_name=incr-unchanged) and [0.8s](https://perf.rust-lang.org/detailed-query.html?commit=6e50a225fd67576e43bab1d4dfa3c97f310786a8&base_commit=fb0b1237b12e949320ccd31a6741f03425fc9a66&benchmark=style-servo-opt&run_name=full) bump in macro expansion.

This is presumably an expected (if somewhat unfortunate) consequence of the above PR -- it was all but guaranteed to be a regression on perf.rust-lang.org, as we only benchmark "final binary/library" compilation rather than the whole build. https://github.com/rust-lang/cargo/pull/8560 can only help full, post-cargo clean, builds.

**Comment by ehuss** [comment]
cc @alexcrichton ↑

Yea, it is difficult to get the defaults to accommodate all use cases.  I would expect the negative effects to mostly happen for someone doing development with optimizations enabled. I'm curious how common that is. I suspect it is rare, but I've had a project where it was unusable without optimizations, so maybe not so rare.

FWIW, I did some benchmarking on a variety of real-world projects and a variety of parallel jobs, and the change was faster in every case for a from-scratch `--release` build. 

If you want to restore the old behavior, you can set the env var CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_OPT_LEVEL=3 (assuming the project doesn't override the default opt-level).

**Comment by Mark-Simulacrum** [comment]
I don't think I've ever had a Rust project that was more than a week long and didn't always need release mode, but I agree that it probably varies quite a bit.

I think that this is probably still the right call, though.

One thing we could try is splitting the build dependencies of proc macros and build scripts apart - the latter matter much less, and always run once. But proc macros used for in-workspace crates are essentially guaranteed to be run hundreds of times, so optimizing them to shave of a few milliseconds can be helpful.

I think from scratch builds will indeed always be faster for this, but we also don't have a great handle on whether that matters today (i.e., if you're on CI you probably only care about them, but locally you usually care about tiny incremental rebuilds).

**Pull request merged**
