### PR TITLE
Render all trait bounds in where clauses in rustdoc

### PR DESCRIPTION
**Pull request by cjgillot**
Split from #93803.

This PR modifies the rendering of bounds on generic parameters in rustdoc.
```rust
fn foo<T: Default, U>(x: impl Copy) where U: Clone
```
into
```rust
fn foo<T, U>(x: impl Copy) where T: Default, U: Clone
```

r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for opening it!

So the zulip discussion about this is happening [here](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/converting.20bounds.20into.20where.20bounds.3F).

**Comment by aDotInTheVoid** [comment]
Regardless of what gets decided for the HTML, I think this would be great for JSON.

**Comment by JohnCSimon** [comment]
triage: returning to @cjgillot to address merge conflicts
@rustbot author

**Comment by cjgillot** [comment]
I did not follow the zulip discussions.  @GuillaumeGomez is the rustdoc team interested in landing this change, or should I close the PR?

**Comment by GuillaumeGomez** [comment]
There doesn't seem to have a consensus based on what I can see from the zulip discussion. :-/

**Pull request closed without merging**
