### PR TITLE
Add test for #15919

### LINKED ISSUE #15919: Fixed length array type with high un-suffixed count literal incorrectly treated as negative count
A fixed-length array expression with a repeat count with the high bit set and no suffix is incorrectly treated as a negative count.

On a 64-bit machine:

```rust
fn main() {
    let x = [0u, ..9223372036854775808];
}
```

This results in

```
unnamed.rs:2:20: 2:39 error: expected positive integer for repeat count but found negative integer
unnamed.rs:2     let x = [0u, ..9223372036854775808];
                                ^~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by bombless**
Closes #15919

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors: r-

The test fails due to an unexpected warning. https://github.com/Manishearth/rust/commit/ac12fc8846d6f9984390d10755b56386dcd474c3 fixes that, but the error disappears. Please fix these first, thanks!

**Comment by bombless** [comment]
Sorry, I'll reopen it once I fix it.

**Comment by bombless** [comment]
Okay, fixed. Sorry for the trouble.
r? @pnkfelix

**Comment by steveklabnik** [comment]
This still doesn't work, and caused the rollup to fail http://buildbot.rust-lang.org/builders/auto-mac-32-opt/builds/4955/steps/test/logs/stdio

**Comment by bombless** [comment]
Mac again... so the bug still exist on Mac OSX in a different form, closing this PR.

**Comment by Manishearth** [comment]
It's not a mac issue; it's a 32bit vs 64bit issue.

(mac is just the fastest builder and fails first)

**Pull request closed without merging**
