### PR TITLE
the unadjusted ABI needs to pass aggregates by-value

### LINKED ISSUE #118124: Intrinsic has incorrect return type. LLVM ERROR: Broken function found, compilation aborted. aarch64 / ARM / nightly
Crate *bytecount* compilation fails with latest nightly on NanoPC-T6 (RK3588 ARM / aarch64).
It worked yesterday.

I tried this code:

```bash
cargo new bytecount_test && cd bytecount_test

cargo add bytecount
```

    Updating crates.io index
      Adding bytecount v0.6.7 to dependencies.
             Features:
             - generic-simd
             - html_report
             - packed_simd
             - runtime-dispatch-simd
    Updating crates.io index

```bash
cargo  +nightly-2023-11-20 build
```

   Compiling bytecount v0.6.7
Intrinsic has incorrect return type!
ptr @llvm.aarch64.neon.ld1x4.v16i8.p0i8
in function _ZN4core9core_arch10arm_shared4neon9generated11vld1q_u8_x417hd6e0965b4ff7ff22E
LLVM ERROR: Broken function found, compilation aborted!
error: could not compile `bytecount` (lib)

```bash
cargo  +nightly-2023-11-19 build
```

   Compiling bytecount v0.6.7
   Compiling bytecount_test v0.1.0 (/home/pi/bytecount_test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.90s

```bash
uname -a
```

Linux NanoPC-T6 5.10.160 #7 SMP Thu Jul 20 15:53:55 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

```bash
cat /etc/os-release
``` 

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

I expected to see this happen: *Finished dev [unoptimized + debuginfo] target(s) in 1.32s*

Instead, this happened: *LLVM ERROR: Broken function found, compilation aborted!*

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/118124, a regression introduced in https://github.com/rust-lang/rust/pull/117500

### CODE REVIEW

**Comment by Nilstrieb** [comment]
Could you just add a test that uses the NEON intrinsic and ensures it doesn't fail to compile?

**Comment by RalfJung** [comment]
I can probably do a no_core test that works on all hosts...

**Comment by bjorn3** [comment]
Is the unadjusted ABI marked as internal feature? If not I think we should mark it as such.

**Comment by RalfJung** [comment]
Not currently:

https://github.com/rust-lang/rust/blob/efe54e24aafc413f3f6251ceeace57b810e4df29/compiler/rustc_feature/src/unstable.rs#L162-L163

But I agree.

**Comment by RalfJung** [comment]
> Could you just add a test that uses the NEON intrinsic and ensures it doesn't fail to compile?

I added a test.

**Comment by RalfJung** [comment]
@davidtwco or anyone else from @rust-lang/compiler , this fixes a critical codegen regression, would be good to land it ASAP. :)

**Comment by compiler-errors** [comment]
@bors r+ rollup=never p=1

easier to bisect that way

**Pull request merged**
