### PR TITLE
Implement conversion traits between arrays and uniform tuples.

### PR DESCRIPTION
**Pull request by SimonSapin**
AsRef, AsMut, and Into in both direction between [T; N] and (T, T, …), for N from 0 to 32.

### CODE REVIEW

**Comment by SimonSapin** [comment]
I don’t have a strong motivation for this, it just seemed neat. Arrays and uniform tuples are interchangeable to some extent, and I believe their memory representation is the same. (Is that guaranteed to always be the case?)

**Comment by alexcrichton** [comment]
This was previously proposed in https://github.com/rust-lang/rust/pull/30736, to which [the libs team concluded](https://github.com/rust-lang/rust/pull/30736#issuecomment-173673985) that the full generalization is *very* var out, so if there's not a strong motivation to have this in the meantime we'd prefer to not land.

**Comment by petrochenkov** [comment]
cc https://github.com/rust-lang/rfcs/issues/1397

**Comment by SimonSapin** [comment]
Fair enough.

**Pull request closed without merging**
