### PR TITLE
Update LLVM to fix miscompiles with -Copt-level=z on Windows

### LINKED ISSUE #45034: -C opt-level=z produces invalid code on i686-pc-windows-msvc
```rust
fn main() {
    let _vec: Vec<u8> = Vec::new();
    std::fs::create_dir(std::path::Path::new("a")).unwrap();
}
```
Will crash when compiled with `rustc -C opt-level=z main.rs`.
```
> rustup run nightly-i686-pc-windows-msvc rustc --version -v
rustc 1.22.0-nightly (4502e2aa9 2017-10-03)
binary: rustc
commit-hash: 4502e2aa9c28d8caa610fc1815fd9c5b5a16e91c
commit-date: 2017-10-03
host: i686-pc-windows-msvc
release: 1.22.0-nightly
LLVM version: 4.0
```

The asm for main is
```asm
__ZN4main4main17h0bca12b325d77113E:
Lfunc_begin2:
	pushl	%ebp
	movl	%esp, %ebp
	pushl	%ebx
	pushl	%edi
	pushl	%esi
	andl	$-8, %esp
	subl	$72, %esp
	movl	%esp, %esi
	movl	%ebp, 48(%esi)
	leal	56(%esi), %eax
	movl	%esp, -4(%eax)
	orl	$-1, 8(%eax)
	movl	$___ehhandler$_ZN4main4main17h0bca12b325d77113E, 4(%eax)
	movl	%fs:0, %ecx
	movl	%ecx, (%eax)
	xorl	%ecx, %ecx
	movl	%eax, %fs:0
	andl	$0, 8(%eax)
	incl	%ecx
	movl	%ecx, 12(%esi)
	andl	$0, 16(%esi)
	andl	$0, 20(%esi)
	pushl	%ecx
	pushl	$_str.7
	calll	__ZN3std3ffi6os_str85_$LT$impl$u20$core..convert..AsRef$LT$std..ffi..os_str..OsStr$GT$$u20$for$u20$str$GT$6as_ref17h154d386d199535e3E
	popl	%ecx
	popl	%esi
	movl	%eax, 8(%esi)
	movl	%edx, 4(%esi)
	calll	__ZN3std2fs10DirBuilder3new17h2a2d998af5809e7bE
	movb	%al, 24(%esi)
	pushl	4(%esi)
	pushl	8(%esi)
	calll	__ZN79_$LT$std..path..Path$u20$as$u20$core..convert..AsRef$LT$std..path..Path$GT$$GT$6as_ref17hbd919da430f6c47cE
	popl	%ecx
	popl	%esi
	pushl	%edx
	pushl	%eax
	calll	__ZN79_$LT$std..path..Path$u20$as$u20$core..convert..AsRef$LT$std..path..Path$GT$$GT$6as_ref17hbd919da430f6c47cE
	popl	%ecx
	popl	%esi
	leal	24(%esi), %ecx
	leal	36(%esi), %edi
	pushl	%edx
	pushl	%eax
	pushl	%ecx
	pushl	%edi
	calll	__ZN3std2fs10DirBuilder7_create17h457ad352f6fc1a89E
	addl	$16, %esp
	cmpl	$0, 36(%esi)
	jne	LBB6_6
	leal	12(%esi), %ecx
	calll	__ZN4core3ptr13drop_in_place17h8b2fec8553a09995E
	movl	56(%esi), %eax
	movl	%eax, %fs:0
	leal	-12(%ebp), %esp
	popl	%esi
	popl	%edi
	popl	%ebx
	popl	%ebp
	retl
LBB6_6:
	movl	40(%esi), %eax
	movl	44(%esi), %edx
	leal	24(%esi), %ecx
	movl	%edx, 4(%ecx)
	movl	%eax, (%ecx)
	calll	__ZN4core6result13unwrap_failed17h0ccedc4bcd16baddE
	.def	 "?dtor$9@?0?_ZN4main4main17h0bca12b325d77113E@4HA";
	.scl	3;
	.type	32;
	.endef
"?dtor$9@?0?_ZN4main4main17h0bca12b325d77113E@4HA":
LBB6_9:
	pushl	%ebp
	subl	$16, %esp
	leal	-68(%ebp), %esi
	movl	48(%esi), %ebp
	leal	12(%esi), %ecx
	calll	__ZN4core3ptr13drop_in_place17h8b2fec8553a09995E
	addl	$16, %esp
	popl	%ebp
	retl
```

Specifically, the function uses `esi` to store a local variable, but after 
`__ZN79_$LT$std..path..Path$u20$as$u20$core..convert..AsRef$LT$std..path..Path$GT$$GT$6as_ref17hbd919da430f6c47cE`
 one of the function arguments are popped from stack with `popl %esi`..

When using `-C panic=abort`, or `i686-pc-windows-gnu`, or removing the `_vec`, the code compiles correctly (uses only `popl %ecx`), so the cause may be related to stack unwinding?

The issue also doesn't occur with `-C opt-level=s`, which uses one byte larger `addl $8, %esp` instead of two pops.

Not sure if this happens on x86-64, at least the example works fine as the calling convention won't have to use stack there.

### PR DESCRIPTION
**Pull request by dotdash**
Fixes #45034

### CODE REVIEW

**Comment by dotdash** [comment]
Needs to wait for https://github.com/rust-lang/llvm/pull/95

**Comment by alexcrichton** [comment]
r=me with the new merge commit, also would it be possible to add a test for this?

**Comment by dotdash** [comment]
If someone could test that this crashes on i686 windows msvc with -Copt-level=z

```rust
#![feature(test)]
extern crate test;

fn foo(x: i32, y: i32) -> i64 {
    (x + y) as i64
}

#[inline(never)]
fn bar() {
    let f = Box::new(0);
    let y: fn(i32, i32) -> i64 = test::black_box(foo);
    test::black_box(y(1, 2));
}

fn main() {
    bar();
}
```

**Comment by nagisa** [comment]
The test from the comment above does crash on 11-03 nightly. Compiling it complains about `f` being unused (consider using `_f`).

**Comment by nagisa** [comment]
That being said, I feel that a codegen test would be way more appropriate if one is possible.

**Comment by dotdash** [comment]
Are there any codegen tests that check for assembler output?

**Comment by dotdash** [comment]
Doesn't seem like there is, and I currently don't have time to adjust the test runner to support it. :-/

So this is free for someone to pick up.

**Comment by alexcrichton** [comment]
Er sorry @dotdash I didn't mean to imply a test was required, just if we already had one I figured it'd be good to include! I'm totally fine merging this regardless (as it's upstream in LLVM anyway). Do you want to check in the test you gisted above and r=me?

**Comment by kennytm** [comment]
@bors r- 

CI failed, “error: -O and -C opt-level both provided” on the new test case. 

<details>

```
[00:52:35] failures:
[00:52:35] 
[00:52:35] ---- [run-pass] run-pass/msvc-opt-minsize.rs stdout ----
[00:52:35] 	
[00:52:35] error: compilation failed!
[00:52:35] status: exit code: 101
[00:52:35] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass/msvc-opt-minsize.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/msvc-opt-minsize.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Copt-level=z" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/msvc-opt-minsize.stage2-x86_64-unknown-linux-gnu.aux"
[00:52:35] stdout:
[00:52:35] ------------------------------------------
[00:52:35] 
[00:52:35] ------------------------------------------
[00:52:35] stderr:
[00:52:35] ------------------------------------------
[00:52:35] error: -O and -C opt-level both provided
[00:52:35] 
[00:52:35] 
[00:52:35] ------------------------------------------
[00:52:35] 
[00:52:35] thread '[run-pass] run-pass/msvc-opt-minsize.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2498:8
[00:52:35] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:52:35] 
[00:52:35] 
[00:52:35] failures:
[00:52:35]     [run-pass] run-pass/msvc-opt-minsize.rs
[00:52:35] 
[00:52:35] test result: FAILED. 2808 passed; 1 failed; 14 ignored; 0 measured; 0 filtered out
[00:52:35] 
[00:52:35] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:329:21
[00:52:35] 
```

</details>

**Comment by nagisa** [comment]
Sadly, using `-Copt-level` requires promoting the test to a run-make.

**Pull request merged**
