### PR TITLE
Rollup of 17 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
- Successful merges: #47790, #47835, #47854, #48015, #48047, #48051, #48058, #48059, #48064, #48078, #48080, #48085, #48086, #48090, #48093, #48098, #48101
- Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+ 

Added #48101.

**Comment by kennytm** [comment]
@bors r+

Removed https://github.com/rust-lang/rust/pull/48100#issuecomment-364557509

**Comment by estebank** [comment]
@bors retry

```
[02:11:21] [m[m[32m[1m     Running[m build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps/alloc-b0e10857ffbb389e
...
[02:12:24] test net::tcp::tests::clone_while_reading ... test net::tcp::tests::clone_while_reading has been running for over 60 seconds

[02:12:44] thread '<unnamed>' panicked at 'received error for `TcpStream::connect(&addr)`: Operation timed out (os error 60)', libstd/net/tcp.rs:1382:31



No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Pull request closed without merging**
