### PR TITLE
[beta] update book with redirect fixes

### PR DESCRIPTION
**Pull request by steveklabnik**
Backport of #42660 

Requesting a backport because people are finding this very confusing. I could in theory make this smaller but it's a real giant pain, so just update the entire book rather than creating a `nodelete` branch that lives forever in the book repo.

r? @brson @alexcrichton

### CODE REVIEW

**Comment by kennytm** [comment]
Android build stuck during libstd test. 

```
[01:09:36] test process::tests::test_process_output_fail_to_start ... test process::tests::test_process_output_fail_to_start has been running for over 60 seconds



No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Comment by kennytm** [comment]
Almost all builds on Travis errored without any logs o_O. No problem on [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.3621). Spurious.

**Comment by ishitatsuyuki** [comment]
@kennytm Travis sucks and they didn't have an on-call for Sunday despite the database migration. The queue is currently filled up with junk and they finally put a [notice](https://www.traviscistatus.com/incidents/l26xy07hwr5q) after 8 hours of outage.

**Pull request merged**
