### PR TITLE
Turn on ConstDebugInfo pass.

### LINKED ISSUE #110675: MIR-inlined functions called with constants should put the constant in debug info
The following code calls `is_digit` with a constant radix:

https://github.com/rust-lang/rust/blob/37b22cf2d5d787106077d4f9ef3092ca80e92a1b/tests/mir-opt/issues/issue_59352.rs#L13-L16

The MIR inliner preserves a local variable that's "holding" the value

https://github.com/rust-lang/rust/blob/37b22cf2d5d787106077d4f9ef3092ca80e92a1b/tests/mir-opt/issues/issue_59352.num_to_digit.PreCodegen.after.mir#L7-L10

But it's actually dead -- nothing sets `_3` to anything, so that debug info node is useless.

(I'm working on a PR that will remove always-uninitialized debug info like that `_3`, which is how I noticed this.  So I opened this in case the debuginfo folks want this to work instead of just being dropped.)

### PR DESCRIPTION
**Pull request by cjgillot**
Split from https://github.com/rust-lang/rust/pull/103657

Moving those constant into debuginfo allows to shrink the number of locals and the actual size of the MIR body.

### CODE REVIEW

**Comment by cjgillot** [comment]
r? compiler

**Comment by oli-obk** [comment]
Tiny, but consistent, regression in debug mode binary size (https://perf.rust-lang.org/compare.html?start=252741673b9c2b06267cd3a036d77489e92f963a&end=d908afcacb9fa8badcf4d4fb4355dfa77efb81d4&stat=size%3Alinked_artifact), but that's ok, just a bit of debuginfo shuffling.

@bors r+

**Comment by cjgillot** [comment]
Same failure as https://github.com/rust-lang/rust/pull/107270. I should have expected it 🤦 
I'll cherry-pick https://github.com/rust-lang/rust/pull/107270/commits/7edfefff73a20bbc45bdf65e5b0a27c64c4ff98b on top of this branch.

**Comment by apiraino** [comment]
hello, visiting and checking progress.

@cjgillot was the last perf. run triaged? do you need someone to review or are you still working on it? thanks

**Comment by cjgillot** [comment]
I had added a commit since @oli-obk's approval in https://github.com/rust-lang/rust/pull/107404#issuecomment-1447777138, but that commit has been merged by another PR. Perf results are globally positive, so this PR is waiting for approval.
@oli-obk if you don't mind, I'll r=you tomorrow.

**Comment by nnethercote** [comment]
@oli-obk: the post-merge results look quite different. Any idea why?

**Comment by oli-obk** [comment]
Well, we add more info to debuginfo, it could be that LLVM now shuffles codegen units differently or just randomly takes more time. We'll need to see if these benchmarks had a single bump or if they are now more noisy.

**Pull request merged**
