### PR TITLE
Fix some more clippy warnings

### PR DESCRIPTION
**Pull request by jyn514**
Found while working on https://github.com/rust-lang/rust/pull/77351. It turns out that `x.py clippy --fix` does work on that branch as long as you pass `CARGOFLAGS=--lib`.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Looks like autofix removed some comments, they need to be restored.

**Comment by jyn514** [comment]
> Looks like autofix removed some comments, they need to be restored.

See https://github.com/rust-lang/rustfix/issues/190 for discussion about fixing this in `rustfix`.

**Review by davidtwco — APPROVED** [review]
LGTM

**Pull request merged**
