### PR TITLE
Avoid documenting top-level private imports

### LINKED ISSUE #90865: Rustdoc is inlining `use ...` imports when `--document-private-items` is passed
I tried this code:

```rust
use std::env;
```

I expected to see this happen: The documentation is empty.

Instead, this happened: 
image

### Meta

`rustdoc --version`: rustdoc 1.58.0-nightly (e90c5fbbc 2021-11-12)

cc @camelid @inquisitivecrystal, I suspect this is related to one of your recent changes to visibility.

### PR DESCRIPTION
**Pull request by inquisitivecrystal**
PR #88447 aimed to make rustdoc's `--document-private-items` mode only document imports that are visible outside the importing module. Unfortunately, I inadvertently set things up so that imports at the crate top-level are always documented, regardless of their visibility. This behavior was unintended and is [not desirable](https://github.com/rust-lang/rust/issues/90865#issuecomment-971172649).

This PR treats top-level imports as never being visible outside their parent module. In practice, the only way a top-level import can be visible externally is if it's fully public, and there's a seperate check for that.

It's worth calling attention to the fact that this change means that `pub(crate)` imports will be visible in lower level modules, but not at the top-level. This is because, at the top level of the crate, `pub(crate)` means the same thing as `pub(self)`.

It turned out that there were existing tests checking for the only behavior, which I didn't notice at the time of my previous PR. I have updated them to check for the new behavior and substantially extended them to handle differences between the top-level module and lower level modules. I may have gone overboard, so please tell me if there's anything I should cut.

r? @jyn514

Fixes #90865.

### CODE REVIEW

**Comment by inquisitivecrystal** [comment]
I just realized it would probably be more readable if the order of the definitions in `src/test/rustdoc/auxiliary/reexports.rs` was the same as the order of the imports in `src/test/rustdoc/reexports.rs` and `src/test/rustdoc/reexports-priv.rs`. I'll fix that and force-push later.

**Review by jyn514 — COMMENTED** [review]
This is ... Quite a lot of tests 😂 the change to rustdoc itself looks fine, I'm going to wait to review the tests until you reorder them like you mentioned.

**Comment by inquisitivecrystal** [comment]
> This is ... Quite a lot of tests 😂 the change to rustdoc itself looks fine, I'm going to wait to review the tests until you reorder them like you mentioned.

Done!

The way the existing tests were set up does imports with a bunch of different sorts of things. I suppose the idea is to make sure that different imported types don't break things? I've mirrored that in my new tests. It's possible that it would be helpful to test for different things, like more complex situations with visibility, but that's not how the existing tests are set up.

**Comment by jyn514** [comment]
I think these tests are pretty overkill 😆 but overkill never hurt anything. Thanks for the quick fix!

@bors r+ p=1 (needs to land before the beta promotion on Friday)

**Comment by inquisitivecrystal** [comment]
CC @nnethercote: these new results seem related to the perf regressions that were being attributed to #88447.

**Comment by nnethercote** [comment]
Excellent! Instruction counts went from ~5.9 billion to ~10.9 billion in #90769. This commit changes them from ~11.1 billion to ~6.1 billion. So it seems like there was a bit of movement elsewhere, but this PR gets back all of the big regression :)

**Pull request merged**
