### PR TITLE
llvm - Segmented stack support for DragonFly

### PR DESCRIPTION
**Pull request by mneumann**

### CODE REVIEW

**Comment by mneumann** [comment]
Related to #20305

**Comment by alexcrichton** [comment]
Can you also touch the `src/rustllvm/llvm-auto-clean-trigger` file to ensure that LLVM is rebuilt?

**Comment by nikomatsakis** [comment]
I'm assigning this to @alexcrichton since I have no idea what is going on here.

**Comment by mneumann** [comment]
@alexcrichton: Here we go!

**Comment by alexcrichton** [comment]
needs a rebase :(

**Comment by mneumann** [comment]
rebased

**Comment by mneumann** [comment]
@alexcrichton: I wonder why src/llvm still points at commit ec1fdb3 and not b820135.

**Comment by alexcrichton** [comment]
Ah sorry I forgot to ping this, but I think it was accidentally reverted in 44440e5c18a1dbcc9685866ffffe00c508929079. Could you re-submit the update of the submodule?

**Comment by mneumann** [comment]
No problem: https://github.com/rust-lang/rust/pull/20991

**Pull request merged**
