### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Successful merges:

 - #94667 (Add `Iterator::map_windows`)
 - #111491 (Dont check `must_use` on nested `impl Future` from fn)
 - #111606 (very minor cleanups)
 - #111665 (Add more tests for the offset_of macro)
 - #111701 (Bump `cc` for `bootstrap`)
 - #111708 (Give a more useful location for where a span_bug was delayed)
 - #111715 (Fix doc comment for `ConstParamTy` derive)
 - #111723 (style: do not overwrite obligations)
 - #111726 (Migrate GUI colors test to original CSS color format)
 - #111743 (Improve cgu merging debug output)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=94667,111491,111606,111665,111701,111708,111715,111723,111726,111743)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I don't see any change directly related to the failure. Retrying just in case...

@bors retry

**Comment by lukas-code** [comment]
From the backtrace it looks like the test in https://github.com/rust-lang/rust/pull/94667 is failing. This is probably due to wasm not supporting unwinding panics.

https://github.com/rust-lang/rust/blob/f0f9d88de6b74592a9fb2bb67c9a3c64edfcb54c/library/core/tests/iter/adapters/map_windows.rs#L67

**Comment by GuillaumeGomez** [comment]
Thanks! Closing this rollup then.

**Pull request closed without merging**
