### PR TITLE
rustc: Stricter matching of `--cfg` options

### LINKED ISSUE #31497: --cfg accepts bogus grammar
These all work: `--cfg "a - b"`, `--cfg a%`, `--cfg "a { b }"`.

### PR DESCRIPTION
**Pull request by dirk**
Fixes #31497.

### CODE REVIEW

**Comment by dirk** [comment]
A few questions:

1. Is this the right way to approach this? Is comparing the strings after parsing too late, or should we make the parser function itself errors if there's any input string left after the parsed `Ident`?
2. How should tests of this behavior be done?

**Comment by alexcrichton** [comment]
I think that this still wants to parse a meta instead of an ident to we can still pass, for example, `--cfg 'feature = "foo"'`. 

For tests you can add some `compile-fail` tests using the `// compile-flags` feature to help pass arguments down to rustc (invalid ones), and then you can use `// error-pattern` to match the output

**Comment by dirk** [comment]
@alexcrichton: If that's the case, then would it make sense to do some basic validation (perhaps with a simple visitor pattern) of the tree produced by the meta parser?

**Comment by alexcrichton** [comment]
It may make the most sense to just make sure there are no more tokens in the parser once a meta item is parsed (although I'm not sure how to do this). I think what's happening here is we're successfully parsing a meta item and we're just trashing the remaining tokens (when they should be considered invalid)

**Comment by dirk** [comment]
Oooh, good point! I'll look into that.

**Comment by dirk** [comment]
@alexcrichton: Comments addressed and compile-fail test added!

**Comment by alexcrichton** [comment]
@bors: r+ b122064a33884a5dab1e5f4710b38ed233d2b4d5

Thanks!

**Comment by dirk** [comment]
@alexcrichton: Thank you for pointing me in the right direction! :smile: That got me to take another at the parser it uses under the hood and discover the very handy `.is_eof()` function.

**Comment by dirk** [comment]
Looks like there's something in the build script that is causing `error-index-generator` to be interpreted as being passed to `--cfg`, which causes the compiler to error, see [here](https://travis-ci.org/rust-lang/rust/builds/109251819#L7459).

**Comment by alexcrichton** [comment]
Ah that's because that's legitimately an invalid cfg! That should probably change to `error_index_generator`

**Comment by dirk** [comment]
@alexcrichton: Huh, so I can see a `--cfg error-index-generator` on the end of the call to rustc to build `src/error-index-generator/main.rs`, but can't figure out where it's coming from.

**Comment by dirk** [comment]
@alexcrichton: Turns out the fix was a simple (and probably overdue) rename! See 2766e254b1c326fb32414496c9532bcb3d3f1d51.

**Pull request merged**
