### PR TITLE
Avoid ICE when adjusting bad self ty

### LINKED ISSUE #65611: Compiler panics in ambiguous arrayvec type situation
The compiler correctly errors about the ambiguous types, but also panics on this code:

```
use arrayvec::ArrayVec;

fn main() {
    let mut buffer = ArrayVec::new();
    let x = buffer.last().unwrap().0.clone();
    buffer.reverse(); 
}
```

```
error[E0282]: type annotations needed
 --> src/main.rs:5:13
  |
5 |     let x = buffer.last().unwrap().0.clone();
  |             ^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `T`
  |
  = note: type must be known at this point

error[E0609]: no field `0` on type `&_`
 --> src/main.rs:5:36
  |
5 |     let x = buffer.last().unwrap().0.clone();
  |                                    ^

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d6120e5e2819deb7a546f61bae891657

### PR DESCRIPTION
**Pull request by estebank**
Fix #65611.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
LGTM

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/compiler meeting, [accepted](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-10-24.20.2354818/near/178956213) for beta backport (once it lands).

**Comment by nikomatsakis** [comment]
We are also giving a "technical 👍" for stable backport, I believe final decision there is made by @rust-lang/release though.

**Comment by Mark-Simulacrum** [comment]
Release team discussed and decided to deny stable backport given that next release is 2 weeks out and this is not a fix in the sense that it is just moving ICEs to errors, not error -> building code or so.

(Procedural note: we don't really have a good process for doing this denial, so I'll just drop both labels.)

**Pull request merged**
