### PR TITLE
Also emit `missing_docs` lint with `--test` to fulfil expectations

### LINKED ISSUE #130021: False positive `unfulfilled_lint_expectations` with either of `--tests` or `--all-targets`
### Code

```Rust
//! crate docs

#![warn(missing_docs)]
#![warn(clippy::pedantic)]

#[expect(missing_docs)]
pub fn foo() {}

#[expect(clippy::enum_glob_use)]
use std::cmp::Ordering::*;

fn main() {
    #[expect(clippy::unreadable_literal)]
    let _ = 1000000000;
    print!("{Equal:?}");
}
```

### Current output

```Shell
$ cargo check --all-targets
warning: this lint expectation is unfulfilled
 --> src/main.rs:6:10
  |
6 | #[expect(missing_docs)]
  |          ^^^^^^^^^^^^
  |
  = note: `#[warn(unfulfilled_lint_expectations)]` on by default

warning: `hello` (bin "hello" test) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
```

### Desired output

```Shell
$ cargo check --all-targets
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
```

### Rationale and extra context

_No response_

### Other cases

`cargo clippy --all-targets` has the same issue with `clippy::enum_glob_use`, however, there's no false positive on `clippy::unreadable_literal`.

### Rust Version

```Shell
rustc 1.81.0-beta.6 (b5fd9f6f1 2024-08-21)
binary: rustc
commit-hash: b5fd9f6f1061b79c045cc08fe03e00caad536800
commit-date: 2024-08-21
host: x86_64-unknown-linux-gnu
release: 1.81.0-beta.6
LLVM version: 18.1.7
```

### Anything else?

Reported in https://github.com/rust-lang/rust-analyzer/issues/17685.

### PR DESCRIPTION
**Pull request by Urgau**
This PR removes the "test harness" suppression of the `missing_docs` lint to be able to fulfil `#[expect]` (expectations) as it is now "relevant".

I think the goal was to maybe avoid false-positive while linting on public items under `#[cfg(test)]` but with effective visibility we should no longer have any false-positive.

Another possibility would be to query the lint level and only emit the lint if it's of expect level, but that is even more hacky.

Fixes https://github.com/rust-lang/rust/issues/130021

try-job: x86_64-gnu-aux

### CODE REVIEW

**Comment by lcnr** [comment]
r? compiler

**Comment by matthiaskrgr** [comment]
I'm wondering if this could have the potential to break cargo tests  https://github.com/rust-lang/rust/pull/130109#issuecomment-2336836510

**Comment by workingjubilee** [comment]
Seems so, actually looking at the test?

https://github.com/rust-lang/cargo/blob/1149535a6fe347bf0eb80c67eb71d9f06d8e5db0/tests/testsuite/rustdocflags.rs#L155-L192

**Comment by Urgau** [comment]
I have reverted commit [`ae661dd` (#130025)](https://github.com/rust-lang/rust/pull/130025/commits/ae661ddea39cc9cce7c0f2616c11d18660f4988c) which deactivated the lint on dummy spans because I though that the dummy spans where were getting were wrong, but as it turns out (thks to the Cargo test) the dummy spans were coming from the crate root (legitimate) and from the generated test harness when doing `--test`, which as masked by the fact that we didn't lint at all on them until now.

I have therefore added `#[allow(missing_docs)]` on the generated test harness function.

@rustbot ready

**Comment by MrCroxx** [comment]
Hi, thanks for the contribution. May I ask if this PR would be cherry-picked to a patch release like 1.81.1?

**Comment by Urgau** [comment]
Due to our fast release cycle, we don't backport to stable simple bug-fixes, only security fixes or major regressions fixes.

`#[expect(missing_bugs)]` never worked on stable, so it's not technically a regression either, making it unlikely to get beta-backported either.

**Comment by workingjubilee** [comment]
great new lint, `expect(missing_bugs)` so that you can be sure your code is buggy :^)

**Pull request merged**
