### PR TITLE
Rollup of 3 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #118962 (Annotate some bugs)
 - #118969 (coverage: Use `Waker::noop` in async tests)
 - #118974 (Annotate panic! reasons during enum layout)

Failed merges:

 - #111658 (Refactor pre-getopts command line argument handling)
 - #117449 (Avoid silencing relevant follow-up errors)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=118962,118969,118974)

### CODE REVIEW

**Comment by workingjubilee** [comment]
@rust-timer build 50c2fd85cb3fae0c99f752370fdbed97e4890bba

**Comment by workingjubilee** [comment]
cc @compiler-errors It seems your annotation PR in #118692 has caused a nontrivial perf regression. On the other hand, the only "real world" bench affected is *"Hello, world!"*, and all the other ones are stress benches, so perhaps this is more artificial than it seems. Either way, I suspect you'd have a better sense for evaluating this.

**Comment by compiler-errors** [comment]
Huh, I don't expect to have done anything in that PR resulting in worse performance...

**Comment by Kobzol** [comment]
I think that this is just a continuation of the recent noise spikes in some benchmarks. CC @lqd who can best recognize these situations.
image

**Comment by workingjubilee** [comment]
...Surely there is some sort of statistical method to isolate "noise" like this?

**Comment by lqd** [comment]
> I think that this is just a continuation of the recent noise spikes in some benchmarks. CC @lqd who can best recognize these situations.

I also believe it's noise. My theory is that the noise threshold gets lower due to a period of lesser noise, and when the usual noise comes back this is seen as a regression. It's what I imagine the graph shows, but we probably would be able to tell better if we saved a history of the threshold, and visualized it as a shaded range on the above graph.

**Pull request merged**
