### PR TITLE
Don't label tracking issues with `needs-triage`

### PR DESCRIPTION
**Pull request by fmease**
Addresses https://github.com/rust-lang/rust/issues/113261#issuecomment-1627789571.

CC @Nilstrieb

### CODE REVIEW

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/rust/pull/113492#issuecomment-1627692150. apparently this is non-deterministic too, ugh. cc @oli-obk @rust-lang/clippy, something in the switch to ui_test is breaking clippy tests.

**Review by Noratrieb — APPROVED** [review]
we should probably triage tracking issues more, but triaging new ones really doesn't make sense

**Comment by oli-obk** [comment]
> cc [#113492 (comment)](https://github.com/rust-lang/rust/pull/113492#issuecomment-1627692150). apparently this is non-deterministic too, ugh. cc @oli-obk @rust-lang/clippy, something in the switch to ui_test is breaking clippy tests. (more details in the linked comment)

I believe I know what it is. I'll create a fix

**Comment by Nilstrieb** [comment]
r? Nilstrieb

**Pull request merged**
