### PR TITLE
Reverts #92135 because perf regression

### PR DESCRIPTION
**Pull request by AngelicosPhosphoros**
Please, start a perf test for this.

r? @joshtriplett You approved original PR.

### CODE REVIEW

**Comment by AngelicosPhosphoros** [comment]
I think, we can also try to use `#[inline(always)]`, maybe it would give any difference.

**Comment by AngelicosPhosphoros** [comment]
JFYI: I wouldn't be able to participate until 15th January. I would return to this PR after that if needed.

**Comment by the8472** [comment]
known flaky test

@bors retry

**Comment by lqd** [comment]
GHA network(?) failure: `Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/zipball/ec3a7ce113134d7a93b817d10a8272cb61118579'. Error: The operation was canceled.`

@bors retry

**Pull request merged**
