### PR TITLE
std::io: panic on overconsumed Cursor

### PR DESCRIPTION
**Pull request by mzabaluev**
The truncation of offset in `fill_buf` adds a branch penalizing any correct usage and makes `BufReader` spuriously report EOF after the input is overconsumed.
I think it better to treat overconsumption as a programmer error and produce a helpful panic message in debug builds.

The implementation of `Seek` is changed to not rely on the former behavior.
Instead, `Seek` on non-growable buffers has the position truncated to the length of the buffer.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
r? @aturon 
cc @alexcrichton 

(I am not really familiar with this code)

**Comment by mzabaluev** [comment]
In fact, I'm inclined to change `Seek` to return error on seeking past the end of non-growable buffers too. Otherwise, the behavior is inconsistent with seeking growable buffers, and if people don't learn to always use or verify the actual returned position, silent data corruption may occur.

**Comment by mzabaluev** [comment]
(re-adding the deleted comment after some vacillation)

I'm inclined to change `Seek` to return error on seeking past the end of non-growable buffers as well.
The current behavior is inconsistent with seeking growable buffers, and may result in silent data corruption in some uncommon scenarios, such as if someone seeks forward to an offset that would be past the end, then seeks some amount back from the actual end and writes within the bounds of the actual buffer. With a growable buffer, the result will be different and likely more expected. Granted, that's a weird usage pattern, but I can't think of a valid reason to seek past the end of a fixed buffer, either.

**Comment by mzabaluev** [comment]
`BufReader` is backed by a growable buffer, so the effect of an overcommit there is that the buffer grows beyond the initial capacity.

**Comment by alexcrichton** [comment]
> I'm inclined to change `Seek` to return error on seeking past the end of non-growable buffers as well.

I think that the current truncation semantics may necessitate this change personally. The scenario you outlined (seeking around but eventually writing in-bounds) is what I would be worried about. It could happen for possibly unrelated reasons and just be expected to work on an in-memory buffer as well as an external one.

Is this change prompted for performance reasons? If so, do you have some benchmark numbers of the before/after?

**Comment by mzabaluev** [comment]
@alexcrichton 
> Is this change prompted for performance reasons?

No, the primary motivation is spurious EOF with `Cursor<&mut [u8]>`. Making `fill_buf` faster for all users won't hurt, though.

**Comment by alexcrichton** [comment]
Oh interesting! Could you elaborate on that a little more? The concern in the PR description is crossed out so I'm a little confused by where it's cropping up.

**Comment by mzabaluev** [comment]
I mistakenly thought that `BufReader` does not automatically grow an overconsumed buffer on reading, but it's backed by a `Cursor<Vec<u8>>` so it does. It's still not great to allow the internal buffer grow unchecked, but at least there is no potential for silent data loss. But if anyone implements their own buffered reader or a similar API using a fixed-size mutable buffer, they can be hit with bogus EOFs.

Now, I can see three alternative ways to deal with the issue:

1. Revert to the status quo, but keep the debug assertion against overconsumption. This allows free seeking, and `fill_buf` will never panic while being slower than it would need to be had the invariant on keeping the position within bounds been in effect. In non-debug builds of libstd, overconsuming a fixed buffer may result in a bogus EOF, whereas in debug builds the same misuse will cause an informative panic. This is probably not very useful if debug-asserted libstd is going to be used rarely. We can also make the assertion unconditionally compiled, creating another performance tax on all correct usage.
2. Make `seek` on a fixed-size buffer return an error if the requested position is past the end. This will restrict freedom for 'seek arithmetic', but the in-bounds invariant will only be broken by overconsumption in `BufRead`, which means that any misuse will result in panic regardless of the build configuration.
3. As implemented on the current top of the branch: Clamp the position to the end of a fixed-size buffer if the seek request is past the end. This has the same benefits as 2., but is worse for sloppy 'seek arithmetics' where the client blindly unwraps the results without examining the resulting position.

I'd like your opinions on which approach should this PR commit to.

**Comment by mzabaluev** [comment]
Sorry, I got confused between reading code by moonlight and running tests which take too long to compile. All in-module implementations of `Cursor` had the same problematic behavior on overconsumption while reading.

To get this to a conclusion, does everyone agree that returning error on seeking past the end of a fixed-size buffer (option 2 [above](#issuecomment-75929782) is the right way to go?

**Comment by alexcrichton** [comment]
I would personally consider 1/2 as viable options and would probably lean more towards 2 right now as well. Not sure there's too many people watching this thread though :)

**Comment by aturon** [comment]
@mzabaluev Thanks for this PR, and my apologies for it slipping through the cracks.

After discussion with @alexcrichton, our feeling is that the current behavior of producing an error only when IO is attempted out of bounds is fine. In particular, our treatment for growable buffers and files matches [Posix's lseek](http://linux.die.net/man/2/lseek): we only grow the buffer at the point that writing is actually performed. The current semantics for fixed buffers aligns well with that, the subsequent error when actually attempting IO after the seek seems enough to detect programmer error here.

That said, I'm going to close this PR for the time being. Thanks again.

**Comment by mzabaluev** [comment]
The behavior of seek is one thing, but what about preventing silent data loss when `consume` claims more bytes than was produced? Should I resubmit the changes reworked accordingly to the option 1 [above](#issuecomment-75929782)

**Comment by alexcrichton** [comment]
I would personally be ok with that I believe, although unfortunately due to us not shipping debug builds of the standard library I'm not sure how beneficial it would be.

**Pull request closed without merging**
