### PR TITLE
[DO NOT MERGE] LLVM improvements

### PR DESCRIPTION
**Pull request by arielb1**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Will attempt to get a perf run conducted by Tuesday; hopefully sooner.

**Comment by Mark-Simulacrum** [comment]
No significant changes in performance or memory use.

| instructions | before | after | % change
| -- | -- | -- | -- |
| futures-rs-test-all | 18646729955.00 | 18658026867.00 | 0.1%
| helloworld | 1198476245.00 | 1200118678.00 | 0.1%
| html5ever-2016-08-25 | 18112389712.00 | 18122500388.00 | 0.1%
| hyper.0.5.0 | 24485633622.00 | 24362194756.00 | -0.5%
| inflate-0.1.0 | 24277828675.00 | 24266885387.00 | -0.0%
| issue-20936-deep-vector | 14382768845.00 | 14391086406.00 | 0.1%
| issue-32062-equality-relations... | 1988409028.00 | 1988579671.00 | 0.0%
| issue-32278-big-array-of-strin... | 8798777577.00 | 8813582902.00 | 0.2%
| issue-43572-unused-uses | 2962203221.00 | 2963600247.00 | 0.0%
| jld-day15-parser | 7363537666.00 | 7357121923.00 | -0.1%
| piston-image-0.10.3 | 51801179870.00 | 51787604153.00 | -0.0%
| regex-0.1.80@010-baseline | 30411322553.00 | 30457805432.00 | 0.2%
| regex-0.1.80@020-incr-from-scr... | 42518313010.00 | 42482428883.00 | -0.1%
| regex-0.1.80@030-compile_one | 14353049512.00 | 14279494004.00 | -0.5%
| regex-0.1.80@040-is_valid_cap_... | 8558714924.00 | 8489983155.00 | -0.8%
| regex-0.1.80@050-expand | 11199883267.00 | 11128458032.00 | -0.6%
| regex-0.1.80@060-Compiler-new | 18351267764.00 | 18306836756.00 | -0.2%
| regex-0.1.80@070-BYTE_FREQUENC... | 8949882581.00 | 8878675431.00 | -0.8%
| regex-0.1.80@080-SparseSet | 41777136293.00 | 41708624163.00 | -0.2%
| regex-0.1.80@090-Job | 42295235613.00 | 42203354064.00 | -0.2%
| regex-0.1.80@100-incr-no-chang... | 8438426224.00 | 8363814853.00 | -0.9%
| regex.0.1.30 | 11828228488.00 | 11788805374.00 | -0.3%
| rust-encoding-0.3.0 | 9699186420.00 | 9692526061.00 | -0.1%
| syntex-0.42.2@000-base | 136571077421.00 | 136364351112.00 | -0.2%
| syntex-0.42.2@010-incr | 212320721429.00 | 212059185924.00 | -0.1%
| syntex-0.42.2@020-clean | 56512724220.00 | 56199665479.00 | -0.6%
| tokio-webpush-simple@000-base | 28133443094.00 | 28123602289.00 | -0.0%
| tokio-webpush-simple@010-incr | 43128894101.00 | 43050435131.00 | -0.2%
| tokio-webpush-simple@020-clean | 9227985341.00 | 9146786430.00 | -0.9%
| tokio-webpush-simple@030-minor... | 43510794175.00 | 43431312444.00 | -0.2%
| tuple-stress | 24159885884.00 | 24170925354.00 | 0.0%

| rss | before | after | % change
| -- | -- | -- | -- |
| futures-rs-test-all | 273836.00 | 273924.00 | 0.0%
| helloworld | 129168.00 | 127840.00 | -1.0%
| html5ever-2016-08-25 | 279344.00 | 279936.00 | 0.2%
| hyper.0.5.0 | 325192.00 | 321960.00 | -1.0%
| inflate-0.1.0 | 306768.00 | 306472.00 | -0.1%
| issue-20936-deep-vector | 271552.00 | 271664.00 | 0.0%
| issue-32062-equality-relations... | 138016.00 | 139648.00 | 1.2%
| issue-32278-big-array-of-strin... | 385076.00 | 384968.00 | -0.0%
| issue-43572-unused-uses | 161512.00 | 160460.00 | -0.7%
| jld-day15-parser | 170704.00 | 170300.00 | -0.2%
| piston-image-0.10.3 | 490568.00 | 492564.00 | 0.4%
| regex-0.1.80@010-baseline | 354784.00 | 356580.00 | 0.5%
| regex-0.1.80@020-incr-from-scr... | 395800.00 | 394148.00 | -0.4%
| regex-0.1.80@030-compile_one | 405128.00 | 405952.00 | 0.2%
| regex-0.1.80@040-is_valid_cap_... | 352828.00 | 352632.00 | -0.1%
| regex-0.1.80@050-expand | 372732.00 | 372824.00 | 0.0%
| regex-0.1.80@060-Compiler-new | 429792.00 | 433616.00 | 0.9%
| regex-0.1.80@070-BYTE_FREQUENC... | 368328.00 | 368184.00 | -0.0%
| regex-0.1.80@080-SparseSet | 409424.00 | 409872.00 | 0.1%
| regex-0.1.80@090-Job | 412316.00 | 409032.00 | -0.8%
| regex-0.1.80@100-incr-no-chang... | 344068.00 | 347988.00 | 1.1%
| regex.0.1.30 | 228448.00 | 228292.00 | -0.1%
| rust-encoding-0.3.0 | 211540.00 | 211424.00 | -0.1%
| syntex-0.42.2@000-base | 936188.00 | 931684.00 | -0.5%
| syntex-0.42.2@010-incr | 976200.00 | 976368.00 | 0.0%
| syntex-0.42.2@020-clean | 898120.00 | 899672.00 | 0.2%
| tokio-webpush-simple@000-base | 388744.00 | 390164.00 | 0.4%
| tokio-webpush-simple@010-incr | 414716.00 | 416296.00 | 0.4%
| tokio-webpush-simple@020-clean | 382500.00 | 381284.00 | -0.3%
| tokio-webpush-simple@030-minor... | 416120.00 | 414280.00 | -0.4%
| tuple-stress | 445196.00 | 443440.00 | -0.4%

**Comment by arielb1** [comment]
Can I have a split of LLVM time vs. non-LLVM time?

**Comment by Mark-Simulacrum** [comment]
We no longer benchmark by-pass and I don't think -Ztime-passes provides accurate data for LLVM anyway due to multi-threading. This is a comparison of just your patch (https://github.com/rust-lang/rust/commit/b1e496ea4ac80f19f3b2be0c466038ca99162005 vs. 2f2b8b34c2a1e585117714f99b3858da5f1b92b5 after/before) though, so any changes *should* be a result of it. I don't know that I can collect more accurate data for you.

**Comment by oyvindln** [comment]
Won't SROA changes only have an effect when compiling with optimizations turned on?

**Comment by arielb1** [comment]
ok.

**Pull request closed without merging**
