### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by sophiajt**
- Successful merges: #35754, #35793, #35880, #36099, #36160, #36171, #36178, #36180, #36190, #36198, #36205, #36210, #36223
- Failed merges:

### CODE REVIEW

**Comment by frewsxcv** [comment]
Tidy fail:

```
/build/src/libsyntax/attr.rs:441: line longer than 100 chars
```

**Comment by jonathandturner** [comment]
@bors r- 

While I fix it

**Pull request closed without merging**
