### PR TITLE
Fix typo for @bors cheetsheet

### PR DESCRIPTION
**Pull request by alexispurslane**
r? @steveklabnik

### CODE REVIEW

**Comment by TimNN** [comment]
There's still a typo in there: it's "cheat sheet" (cheat with an EA) and according to google search result counts, cheat sheet is also more commonly spelled as two words "cheat sheet" instead of one "cheatsheet".

**Comment by christopherdumas** [comment]
Oh. ok.

**Comment by christopherdumas** [comment]
Fixed.

**Comment by christopherdumas** [comment]
This is ready to be merged.

**Pull request merged**
