### PR TITLE
Update Clippy and cargo

### LINKED ISSUE #67541: `clippy-driver` no longer builds after rust-lang/rust#67532
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#67532, I observed that the tool clippy-driver no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rust-clippy is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by JohnTitor**
includes latest rustup and resolves dependency conflicts with cargo
Closes #67541

r? @oli-obk @Manishearth

### CODE REVIEW

**Comment by JohnTitor** [comment]
Ugh, might be related to latest rustup?

**Comment by JohnTitor** [comment]
The ICE is only shown on rustc CI.
@oli-obk could we remove this test for now?

**Comment by JohnTitor** [comment]
<details><summary>backtrace</summary><div>

```
thread 'rustc' panicked at 'assertion failed: !value.has_escaping_bound_vars()', src/librustc/ty/sty.rs:924:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
   1: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   2: core::fmt::write
   3: std::io::Write::write_fmt
   4: std::panicking::take_hook
   5: std::panicking::take_hook
   6: clippy_driver::report_clippy_ice
   7: std::panicking::rust_panic_with_hook
   8: std::panicking::begin_panic
   9: rustc::traits::type_known_to_meet_bound_modulo_regions
  10: rustc::ty::context::GlobalCtxt::enter_local
  11: rustc::ty::util::is_freeze_raw
  12: rustc::ty::util::is_freeze_raw
  13: rustc::ty::query::__query_compute::is_freeze_raw
  14: <rustc::traits::Vtable<N> as core::clone::Clone>::clone
  15: rustc::dep_graph::graph::DepGraph::with_task_impl
  16: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  17: rustc::ty::util::<impl rustc::ty::TyS>::is_freeze
  18: <clippy_lints::mut_key::MutableKeyType as rustc::lint::LateLintPass>::check_local
  19: <clippy_lints::mut_key::MutableKeyType as rustc::lint::LateLintPass>::check_local
  20: <rustc::lint::context::LateLintPassObjects as rustc::lint::LateLintPass>::check_item
  21: rustc::hir::intravisit::Visitor::visit_nested_item
  22: rustc::hir::intravisit::walk_crate
  23: rustc::lint::context::late_lint_pass_crate
  24: rustc::lint::context::late_lint_crate
  25: rustc::util::common::time
  26: rustc::util::common::time
  27: std::panicking::begin_panic
  28: _rust_maybe_catch_panic
  29: std::panicking::try::do_call
  30: _rust_maybe_catch_panic
  31: std::panic::catch_unwind
  32: rustc_interface::passes::analysis::{{closure}}
  33: rustc_interface::passes::create_global_ctxt
  34: rustc::ty::query::__query_compute::analysis
  35: rustc::dep_graph::graph::DepGraph::with_task_impl
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  37: rustc::ty::context::tls::enter_global
  38: rustc_interface::interface::run_compiler_in_existing_thread_pool
  39: std::thread::local::LocalKey<T>::with
  40: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (0fec5905 2019-12-27)

query stack during panic:
#0 [is_freeze_raw] computing whether `&'a Bar` is freeze
#1 [analysis] running analysis passes on this crate
end of query stack
```
</div></details>

**Comment by oli-obk** [comment]
You may be able fix it by erasing regions on `key_type` https://github.com/rust-lang/rust-clippy/blame/0fcb5304e27a747267276cdbac720f4bd2672172/clippy_lints/src/mut_key.rs#L106

The reason it fails on CI and not in clippy is probably because that is a `debug_assertion` and not an `assert`, so if you build clippy with a rustc built with debug assertions you'll see the same failure.

**Comment by JohnTitor** [comment]
Thanks! But the suggested fix didn't work well (I tested dirty-submodule with `debug_assertions=yes`).
I tested with as follows:
```diff
- let key_type = substs.type_at(0);
+ let key_type = cx.tcx.erase_regions(&substs.type_at(0));
```

any thoughts?

**Comment by oli-obk** [comment]
Well... as far as I can tell the clippy code is actually not really interested in the frozenness of the reference, but on the frozenness of the things behind it. Maybe if https://github.com/rust-lang/rust-clippy/blame/0fcb5304e27a747267276cdbac720f4bd2672172/clippy_lints/src/mut_key.rs#L114 returned an `Option<Ty<'tcx>>` and gave us the inner most type to check (so wherever it's `true`, just return the type), then that may work.

**Comment by JohnTitor** [comment]
yeah, it seems an ICE has been gone, at least on my local. I submitted a fix rust-lang/rust-clippy#4964

**Comment by JohnTitor** [comment]
It seems the test has been passed (checked on `Linux x86_64-gnu-tools`).
r? @oli-obk

**Comment by JohnTitor** [comment]
It seems rustup for latest master needs... ([travis on clippy](https://travis-ci.com/rust-lang/rust-clippy/jobs/270944083))
@bors retry r-

**Comment by JohnTitor** [comment]
feel free to r- if someone has a concern
@bors r=oli-obk

**Comment by JohnTitor** [comment]
Homu queue points a resolved comment so it's unintended?
@bors treeclosed-

**Pull request merged**
