### PR TITLE
Move ICH to rustc_query_system

### PR DESCRIPTION
**Pull request by cjgillot**
Based on https://github.com/rust-lang/rust/pull/89183

The StableHashingContext does not need to be in rustc_middle.

This PR moves it to rustc_query_system. This will avoid a dependency between rustc_ast_lowering and rustc_middle in https://github.com/rust-lang/rust/pull/89124.

### CODE REVIEW

**Review by davidtwco — COMMENTED** [review]
This all seems sensible to me, but I'll reassign to get another opinion.

**Comment by cjgillot** [comment]
Actually, putting it in rustc_query_system would be more consistent.

**Review by michaelwoerister — APPROVED** [review]

**Comment by michaelwoerister** [comment]
Looks good to me. Thanks, @cjgillot!

Let's do a perf run for good measure:
@bors try @rust-timer queue

If that doesn't yield any surprises, r=davidtwco,michaelwoerister after rebasing and updating the PR message.

**Comment by michaelwoerister** [comment]
Performance looks good now 👍 

@bors r+

**Pull request merged**
