### PR TITLE
Add `contains` to `VecDeque` and `LinkedList` (+ tests)

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
This implements [RFC 1552](https://github.com/rust-lang/rfcs/blob/master/text/1552-contains-method-for-various-collections.md). Tracking issue: #32630 

Sorry for the late response. This is my first contribution, so please tell me if anything isn't optimal!

### CODE REVIEW

**Comment by apasel422** [comment]
This could be generalized as

```rust
fn contains<U: ?Sized>(&self, x: &U) -> bool where T: PartialEq<U> // or `U: PartialEq<T>`
```

**Comment by LukasKalbertodt** [comment]
Oh right... I did it exactly as specified in the RFC. That's the way it's done for [`[T]::contains`](https://doc.rust-lang.org/std/primitive.slice.html#method.contains)...

Right now, I can't think of any reasons not to do it like you suggested :confused:

**Comment by brson** [comment]
Seems like we should define it as the precedent and RFC state for now.

@bors r+

**Comment by brson** [comment]
Thanks @LukasKalbertodt

**Pull request merged**
