### PR TITLE
Fix x.py

### PR DESCRIPTION
**Pull request by nagisa**
Fixes https://github.com/rust-lang/rust/issues/42085

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

Thanks!

**Comment by nagisa** [comment]
@bors retry

```
 Downloading num_cpus v1.4.0
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:01:09
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 2/5:
 Downloading gcc v0.3.46
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 3/5:
 Downloading gcc v0.3.46
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 4/5:
 Downloading num_cpus v1.4.0
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
Command failed. Attempt 5/5:
 Downloading libc v0.2.22
error: unable to get packages from source
To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:76: prepare] Error 101
The command has failed after 5 attempts.
Command exited with code 1
```

**Comment by kennytm** [comment]
Same error @nagisa. Actually, it seems *every* build after 1.0.3307 failed with the same error. AppVeyor is broken?

https://ci.appveyor.com/project/rust-lang/rust/history

**Comment by alexcrichton** [comment]
@bors: retry

* [appveyor network issues](https://appveyor.statuspage.io/incidents/2g5jnq5cy1g1) #40474

**Comment by kennytm** [comment]
Timed out after 3 hours while testing "librustc stage2".

**Comment by Mark-Simulacrum** [comment]
@bors retry

Probably more fallout from the appveyor slowness.. maybe

**Pull request merged**
