### PR TITLE
Small performance wins for Rc & Arc

### PR DESCRIPTION
**Pull request by tgross35**
This branch is a perf experiment based on #89132 (Allocator API for Rc and Arc) with more inline indicators.

The results were successful so after #89132 lands, I will rebase this and open for review.

### CODE REVIEW

**Comment by tgross35** [comment]
Okay, I cleaned this up so it should be mergable, so I'll mark it ready for review.

The changes here should be about the same as what produced the perf results above. The performance wins are fairly significant, but the binary size increases are also notable. I'll leave it up to the reviewer what the call is on this.

This may merit a perf rerun since the base changed significantly (the above run included adding the allocator API changes, since then the Arc Allocator API has been merged).

See also https://github.com/rust-lang/rust/pull/114446 where I'm trying to figure out some inlining things for the layout calculation (but I will keep that PR separate from this one since that one touches more things)

cc @TimDiekmann, this is the followup to adding the allocator API
@rustbot ready

**Comment by tgross35** [comment]
It looks like perf maybe didn’t get queued, could you retry @Mark-Simulacrum?

**Comment by Kobzol** [comment]
@rust-timer build 0ef074b4e9cbe42f2c6a4e5f3c529e371fdae41f

**Comment by tgross35** [comment]
Thanks @Kobzol 

Well, this time around the results seem a lot more like noise

**Comment by Mark-Simulacrum** [comment]
I think this isn't worth it given the largely noise results here. Thanks for trying it!

**Pull request closed without merging**
