### PR TITLE
Fix generic impl rustdoc json output

### LINKED ISSUE #97986: rustdoc-json: ICE when same item is represented in different ways
Minimal reproducer:
```rust
// src/lib.rs

pub mod m {
    pub struct S;
}

pub trait F {
    fn f() -> m::S;
}

impl<T> F for T {
    fn f() -> m::S {
        m::S
    }
}
```
```
% RUSTDOCFLAGS='-Z unstable-options --output-format json' cargo +nightly doc --lib --no-deps
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("0:10:601"), crate_id: 0, name: Some("f"), span: Some(Span { filename: "src/lib.rs", begin: (10, 4), end: (12, 5) }), visibility: Default, docs: None, links: {}, attrs: [], deprecation: None, inner: Method(Method { decl: FnDecl { inputs: [], output: Some(ResolvedPath { name: "S", id: Id("0:4:1544"), args: Some(AngleBracketed { args: [], bindings: [] }), param_names: [] }), c_variadic: false }, generics: Generics { params: [], where_predicates: [] }, header: Header { const_: false, unsafe_: false, async_: false, abi: Rust }, has_body: true }) }`,
 right: `Item { id: Id("0:10:601"), crate_id: 0, name: Some("f"), span: Some(Span { filename: "src/lib.rs", begin: (10, 4), end: (12, 5) }), visibility: Default, docs: None, links: {}, attrs: [], deprecation: None, inner: Method(Method { decl: FnDecl { inputs: [], output: Some(ResolvedPath { name: "m::S", id: Id("0:4:1544"), args: Some(AngleBracketed { args: [], bindings: [] }), param_names: [] }), c_variadic: false }, generics: Generics { params: [], where_predicates: [] }, header: Header { const_: false, unsafe_: false, async_: false, abi: Rust }, has_body: true }) }`', src/librustdoc/json/mod.rs:202:17
```

The panic happens because `ResolvedPath { name: "S"` != `ResolvedPath { name: "m::S"`, but they are of course equivalent, so we should not panic because of that.

This is (at least partially) a minimal reproducer for https://github.com/rust-lang/rust/issues/93588.

@rustbot labels +A-rustdoc-json +I-ICE +T-rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #97986.

The problem in case of generic trait impl is that the trait's items are the same for all the types afterward. But since they're the same, it's safe for rustdoc-json to just ignore them.

A little representation of what's going on:

```rust
trait T {
    fn f(); // <- defid 0
}

impl<Y> T for Y {
    fn f() {} // <- defid 1
}

struct S; // <- defid 1 (since it matches `impl<Y> T for Y`
```

cc @Urgau

r? @CraftSpider

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
And fixed fmt...

**Comment by Enselic** [comment]
Thanks a lot for this fix.

I can confirm that this makes it possible to build rustdoc JSON for https://github.com/serde-rs/serde/tree/master/serde. It used to result in an ICE.

There is still an ICE for https://github.com/diesel-rs/diesel/tree/b5c2e26d4d9f464458430427704fc50de985c632/diesel though. Just wanted to mention it in case you want to take care of that while you're at it. It is also triggered by a blanket impl, see analysis in https://github.com/rust-lang/rust/issues/93588#issuecomment-1138690037 and https://github.com/rust-lang/rust/issues/93588#issuecomment-1139897192.

**Comment by GuillaumeGomez** [comment]
I have the three other issues open. I will go through them after this one is merged.

**Comment by GuillaumeGomez** [comment]
Oh right, I forgot @CraftSpider was away for the moment. I'll set another reviewer.

r? @notriddle

**Pull request merged**
