### PR TITLE
Remove unused code from `rustc_data_structures::sync`

### PR DESCRIPTION
**Pull request by jyn514**
Found using https://github.com/est31/warnalyzer. Follow-up to https://github.com/rust-lang/rust/pull/83185.

r? @Zoxc cc @oli-obk

### CODE REVIEW

**Comment by bjorn3** [comment]
`AtomicCell` is used by neither non-parallel, nor parallel rustc, so I think it is fine to remove it. Removing all the unused methods from the non-parallel versions is a bad idea I think as the parallel do still have them. I think the non-parallel and parallel versions of all types should have an identical api surface to prevent confusion.

**Comment by jyn514** [comment]
Hmm, not sure who a good reviewer would be - maybe r? @wesleywiser ?

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
There's a comment here that should be adjusted since we're removing `AtomicCell`

https://github.com/rust-lang/rust/blob/35bab923c8e5a1e8291735e7630539002eb80d7b/compiler/rustc_data_structures/src/sync.rs#L87

`r=me` after that.

@bors rollup

**Pull request merged**
