### PR TITLE
Change `assert_unsafe_precondition` docs to refer to `check_language_ub`

### PR DESCRIPTION
**Pull request by ChaiTRex**
Unstable feature `ub_checks` tracking issue #123499.

### CODE REVIEW

**Comment by workingjubilee** [comment]
Thanks!
@bors r+ rollup

**Comment by the8472** [comment]
That tracking issue is for the compiler feature. The feature I added to the library is only meant for internal use so std can use the core feature. It was not intended to be stabilized as a library feature.

**Comment by ChaiTRex** [comment]
@the8472 Should I change it back to "none"? If so, will force pushing to my branch stop the merge?

**Comment by ChaiTRex** [comment]
@the8472 OK, I've removed the changes away from the tracking issue being "none".

**Comment by the8472** [comment]
Yeah my understanding of the compiler processes is that an MCP is not enough to stabilize those flags and it would require an RFC. So the corresponding libs feature also has no path to stabilitzation and will remain internal-only so it doesn't require a tracking issue.

**Comment by ChaiTRex** [comment]
OK, now the pull request only changes `check_{library,lang}_ub` to `check_{library,language}_ub` to match the rest of the documentation and the function name.

@rustbot ready

**Pull request merged**
