### PR TITLE
Update Source Serif to release 4.004

### PR DESCRIPTION
**Pull request by tspiteri**
Now the family name is Source Serif 4 (upstream issue 77) instead of Source Serif Pro.

### CODE REVIEW

**Comment by tspiteri** [comment]
The file names have been changed just like in the font upstream release. I believe that thanks to @jyn514 now the docs.rs maintenance burden because of changing file names is reduced (removed?).

**Comment by jyn514** [comment]
> The file names have been changed just like in the font upstream release. I believe that thanks to @jyn514 now the docs.rs maintenance burden because of changing file names is reduced (removed?).

Yes, docs.rs should take of this automatically now: https://github.com/rust-lang/docs.rs/pull/1312

**Comment by GuillaumeGomez** [comment]
Just want to confirm one thing before approval: is there any changes in the text rendering?

**Comment by tspiteri** [comment]
@GuillaumeGomez From the [4.004 release notes](https://github.com/adobe-fonts/source-serif/releases/tag/4.004R):
>Adding optical sizes required re-assessment of spacing, proportions, and kerning decisions in all masters. Additionally, an intermediate master was shifted to clean up the VF design space.
>While care was taken to keep the existing styles largely equivalent to previous releases, reflow of existing documents is likely.
>The “Pro” label originally was attached to OpenType fonts to indicate their extended language coverage. With Source Serif’s character support far exceeding former “Pro” standards, this label does not have much meaning anymore.
>
>For these reasons, the decision was made to change the family name from Source Serif Pro to Source Serif 4.

This indicates that some documents are likely to get reflow (which can be the case with any tweak in kerning or in metrics), but the existing styles are largely equivalent.

**Comment by GuillaumeGomez** [comment]
I guess it's fine then. Thanks!

@bors: r+ rollup

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/83861#issuecomment-813101497)

**Comment by tspiteri** [comment]
Rebased and added a commit to change "SourceSerifPro-It.ttf.woff" to "SourceSerif4-It.ttf.woff" in src/test/run-make/emit-shared-files/Makefile which was introduced in #83478.

**Pull request merged**
