### PR TITLE
also check `let` arms and nested patterns for mutable borrows

### LINKED ISSUE #46557: Compiler accepts return mut ref to local var on no longer valid stackframe
Spotted on reddit: https://www.reddit.com/r/rust/comments/7i64sy/safe_function_returns_static_mut/  
credit to [jDomantas](https://www.reddit.com/user/jDomantas)

I tried this code: [playground](https://play.rust-lang.org/?gist=5e19e59e8b64488171b76bfbf0383b06&version=stable)

	fn gimme_static_mut() -> &'static mut u32 {
	    let ref mut x = 1234543;
	    x
	}

	fn main() {
	    let x = gimme_static_mut();
	    let y = gimme_static_mut();
	    *y = 42;
	    let a = *x;
	    println!("a: {}", a);
	}

This is accepted by the compiler and prints 42.

I expected to see this happen: The program should be rejected by the compiler with a lifetime error

Instead this happened: The program was accepted and miscompiled badly

The assembly code clearly demonstrates the problem, a local variable is created for the literal, its address is taken and returned:

	playground::gimme_static_mut:
	.Lfunc_begin2:
		push	rbp
	.Lcfi6:
	.Lcfi7:
		mov	rbp, rsp
	.Lcfi8:
		sub	rsp, 16
		lea	rax, [rbp - 4]
	.Ltmp6:
		mov	dword ptr [rbp - 4], 1234543
		mov	qword ptr [rbp - 16], rax
		mov	rax, qword ptr [rbp - 16]
	.Ltmp7:
		add	rsp, 16
		pop	rbp
		ret
	.Ltmp8:
	.Lfunc_end2:

## Meta

Latest version on playground

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #46557 

r? @eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
oh, let me bless the test. =)

**Comment by Mark-Simulacrum** [comment]
Should we backport this to beta since it does fix unsoundness?

**Comment by nikomatsakis** [comment]
Fixed tests.

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum we could .. it's not a recent regression or anything though.

**Comment by nikomatsakis** [comment]
OTOH it's a small patch and I believe the code is pretty old, would be a low-risk backport

**Comment by eddyb** [comment]
I hate the old borrowck, at this point it's an incoherent mess of recursive fine-prints.

@bors r+ p=10

**Comment by nikomatsakis** [comment]
We could backport this, but there's no burning reason to do so. Clearing the backport flag.

**Pull request merged**
