### PR TITLE
Reenable linkchecker for books

### PR DESCRIPTION
**Pull request by steveklabnik**
In some senses, this is a revert of https://github.com/rust-lang/rust/pull/39633/commits/cacb3bc9c741a7d41a1085af850cd3ff852307f5#diff-b64563d143f859565c8357a28ef81101R212; we disabled linkchecker for the book because the links were added by JavaScript. Now, that's fixed upstream, and so we can re-enable the checker.

This also involves two other fixes: we have to check for `name`s as well as `id`s for links, and the linking algorithm of mdBook changed to the same as rustdoc's, so we change some links back.

~~~This isn't quite ready yet; it's [depending on a PR of mine to mdBook](https://github.com/azerupi/mdBook/pull/209). After that's released, this should be the last of these kinds of shenanigans~~~ 😄

This is good to go 😄

### CODE REVIEW

**Comment by frewsxcv** [comment]
Travis:

```
error: the lock file needs to be updated but --frozen was passed to prevent this

make: *** [tidy] Error 101
```

**Comment by frewsxcv** [comment]
r=me with lockfile thing sorted out

**Comment by steveklabnik** [comment]
hrm, I don't understand why it's doing that; tidy passes for me locally.

**Comment by steveklabnik** [comment]
@bors: r=frewsxcv

(I left in a warning by accident)

**Comment by ollie27** [comment]
Why have you used the `name` attribute?

**Comment by steveklabnik** [comment]
> Why have you used the name attribute?

That is what mdbook has always used for these links.

**Comment by ollie27** [comment]
Is there a good reason for that? I'm pretty sure `id` is the correct thing to use.

**Comment by steveklabnik** [comment]
> Is there a good reason for that? I'm pretty sure id is the correct thing to use.

You should file a bug on mdbook about it.

**Pull request merged**
