### PR TITLE
Remove ast::{Ident, Name} reexports.

### PR DESCRIPTION
**Pull request by cjgillot**
The reexport of `Symbol` into `Name` confused me.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Historically, `ast::Name` is an identifier symbol in AST, while `Symbol` (which had many other names in the past) is an arbitrary interned string (maybe a literal, or other arbitrary text).

`ast::Ident` is also an identifier in AST specifically (as opposed to e.g. identifiers tokens which are lowered to AST idents losing their `is_raw` bit), I don't remember how it ended up in `rustc_span`.

**Comment by cjgillot** [comment]
Rebased.

**Comment by matthewjasper** [comment]
@petrochenkov is your comment objecting to this change or just providing some background information?

I think this is an improvement, so r=me unless someone objects.

**Pull request merged**
