### PR TITLE
Allow parentheses in `dyn (Trait)`

### PR DESCRIPTION
**Pull request by Manishearth**
r? @eddyb @nikomatsakis

### CODE REVIEW

**Comment by petrochenkov** [comment]
There's a test `compile-fail/dyn-trait-compatibility.rs` that's going to be broken by this change and needs updating.

**Comment by Manishearth** [comment]
Oh, right, you can alias `FnFoo` to `dyn`. This is unfortunate.

@nikomatsakis is this something we should just land (perhaps w/ crater) or make it an epoch breakage? If we do the latter, bear in mind that there will be no automated way to rustfix `&::Foo` since `&dyn::Foo` is interpreted as a path.

**Comment by petrochenkov** [comment]
We should just land this, IMO, crater won't find anything.

**Comment by Manishearth** [comment]
brb publishing a crate to prove you wrong :stuck_out_tongue_winking_eye: 

but yeah, perhaps. Though I'm really wary about breaking changes. Feel free to r+

**Comment by nikomatsakis** [comment]
I agree with @petrochenkov we can probably get away with this one, though like @Manishearth I am getting ever more wary about breaking changes. =)

**Comment by nikomatsakis** [comment]
Nonehtless, tagging as relnotes. Description would be something like this:

---

The `dyn` keyword now accepts parenthesis, meaning you can do something like `dyn (Debug + Send)` instead of `(dyn Debug + Send)`. It is technically possible for this to affect existing code, if that code were to alias a `Fn` trait with the name `dyn` (e.g., `use ::std::ops::Fn as dyn`). 

---

@petrochenkov, that's the case you were thinking of, right?

**Comment by nikomatsakis** [comment]
I would like some tests that cover the precedence and the interesting cases. For example:

```rust
let x: &dyn (Debug + Send) = ..; // this should work, right?
let x: &dyn (Debug + Send + Sync) = ..; // this too
let x: &dyn (Debug + Send + ) = ..; // I think we support trailing `+` terminators elsewhere
let x: Box<dyn (Debug + Send) + Sync> = ...; // what about this? =) I forget what we decided there
```

Also, does this work for `impl`? It should work analogously, I think.

**Comment by Manishearth** [comment]
ah, none of those work

**Comment by Manishearth** [comment]
We don't seem to allow parens in trait bounds, `T: (Debug + Send)` does not work either.

**Comment by nikomatsakis** [comment]
@Manishearth yes, I know. I think the way to fix this is by allowing parens in trait bounds, or at least I think that's what @cramertj and I always had in mind (they can confirm)

**Comment by nikomatsakis** [comment]
This has been a historical point of disagreement with @petrochenkov though =)

**Comment by Manishearth** [comment]
I can make it work with dyn trait for now; it does not exacerbate any breakages, and is necessary to make `&dyn ::Debug + Send` work I think

**Comment by petrochenkov** [comment]
@nikomatsakis 
>let x: &dyn (Debug + Send) = ..;

This PR doesn't implement that extension, it does other thing - it supports already existing parentheses around a *single* bound (e.g. `impl (Debug) + (Send)` is already ok) after `dyn` that weren't supported purely for compatibility reasons.

**Comment by cramertj** [comment]
It's still my opinion that `(Bound)` should be a valid bound, so that users can write `Box<dyn (Bound + Bound)>`, `&dyn (Bound + Bound + (Bound))`, `T: (Bound + Bound)` etc.

**Comment by petrochenkov** [comment]
@bors r+

(`dyn (Debug + Send)` is an orthogonal issue.)

**Comment by ishitatsuyuki** [comment]
Regression in rollup, pretty print test failed.

```
[01:39:41] ---- [pretty] run-pass/dyn-trait.rs stdout ----
[01:39:41] 	
[01:39:41] error: pretty-printed source does not match expected source
[01:39:41] 
[01:39:41] expected:
[01:39:41] ------------------------------------------
[01:39:41] // Copyright 2017 The Rust Project Developers. See the COPYRIGHT
[01:39:41] // file at the top-level directory of this distribution and at
[01:39:41] // http://rust-lang.org/COPYRIGHT.
[01:39:41] //
[01:39:41] // Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
[01:39:41] // http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
[01:39:41] // <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
[01:39:41] // option. This file may not be copied, modified, or distributed
[01:39:41] // except according to those terms.
[01:39:41] 
[01:39:41] #![feature(dyn_trait)]
[01:39:41] 
[01:39:41] use std::fmt::Display;
[01:39:41] 
[01:39:41] static BYTE: u8 = 33;
[01:39:41] 
[01:39:41] fn main() {
[01:39:41]     let x: &(dyn 'static + Display) = &BYTE;
[01:39:41]     let y: Box<dyn Display + 'static> = Box::new(BYTE);
[01:39:41]     let _: &dyn Display = &BYTE;
[01:39:41]     let _: &dyn ::std::fmt::Display = &BYTE;
[01:39:41]     let xstr = format!("{}" , x);
[01:39:41]     let ystr = format!("{}" , y);
[01:39:41]     assert_eq!(xstr , "33");
[01:39:41]     assert_eq!(ystr , "33");
[01:39:41] }
[01:39:41] 
[01:39:41] ------------------------------------------
[01:39:41] actual:
[01:39:41] ------------------------------------------
[01:39:41] // Copyright 2017 The Rust Project Developers. See the COPYRIGHT
[01:39:41] // file at the top-level directory of this distribution and at
[01:39:41] // http://rust-lang.org/COPYRIGHT.
[01:39:41] //
[01:39:41] // Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
[01:39:41] // http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
[01:39:41] // <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
[01:39:41] // option. This file may not be copied, modified, or distributed
[01:39:41] // except according to those terms.
[01:39:41] 
[01:39:41] #![feature(dyn_trait)]
[01:39:41] 
[01:39:41] use std::fmt::Display;
[01:39:41] 
[01:39:41] static BYTE: u8 = 33;
[01:39:41] 
[01:39:41] fn main() {
[01:39:41]     let x: &(dyn 'static + Display) = &BYTE;
[01:39:41]     let y: Box<dyn Display + 'static> = Box::new(BYTE);
[01:39:41]     let _: &dyn Display = &BYTE;
[01:39:41]     let _: &dyn::std::fmt::Display = &BYTE;
[01:39:41]     let xstr = format!("{}" , x);
[01:39:41]     let ystr = format!("{}" , y);
[01:39:41]     assert_eq!(xstr , "33");
[01:39:41]     assert_eq!(ystr , "33");
[01:39:41] }
[01:39:41] 
[01:39:41] ------------------------------------------
[01:39:41] 
[01:39:41] 
[01:39:41] 
[01:39:41] error: pretty-printed source does not typecheck
[01:39:41] status: exit code: 101
[01:39:41] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "-" "-Zno-trans" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/dyn-trait.pretty-out" "--target=x86_64-unknown-linux-gnu" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/dyn-trait.stage2-x86_64-unknown-linux-gnu.pretty.aux" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
[01:39:41] stdout:
[01:39:41] ------------------------------------------
[01:39:41] 
[01:39:41] ------------------------------------------
[01:39:41] stderr:
[01:39:41] ------------------------------------------
[01:39:41] error[E0433]: failed to resolve. Use of undeclared type or module `dyn`
[01:39:41]   --> <anon>:21:13
[01:39:41]    |
[01:39:41] 21 |     let _: &dyn::std::fmt::Display = &BYTE;
[01:39:41]    |             ^^^ Use of undeclared type or module `dyn`
[01:39:41] 
[01:39:41] error: aborting due to previous error
[01:39:41] 
[01:39:41] 
[01:39:41] ------------------------------------------
[01:39:41] 
[01:39:41] thread '[pretty] run-pass/dyn-trait.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2892:9
[01:39:41] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:39:41] 
[01:39:41] 
[01:39:41] failures:
[01:39:41]     [pretty] run-pass/dyn-trait.rs
```

**Comment by Manishearth** [comment]
This merged, I just messed up on including it in the rollup

https://github.com/rust-lang/rust/pull/48520/commits/7e6829938c198afe033119f1927459c64d2ea4d7

**Pull request closed without merging**
