### PR TITLE
Simplify 'product' factorial example

### PR DESCRIPTION
**Pull request by timvisee**
This simplifies the [`factorial(n: 32)`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#examples-46) implementation as example for the `Iterator::product()` function.
It currently uses unnecessary additional complexity.

Although very minimal, I do not want to include it in some other irrelevant PR.

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]

**Comment by frewsxcv** [comment]
thanks!

@bors r+ rollup

**Comment by timvisee** [comment]
@frewsxcv Just noticed the GPG signature for the commit is unverified because I apparently used the wrong key. Too bad.

If desired, I can rewrite the commit to make it verified.

**Comment by lzutao** [comment]
I think you can force-push to replace commit.

**Comment by Mark-Simulacrum** [comment]
There is no need for you to sign commits, but note that if you force push you should also leave a comment because GitHub doesn't notify on force push.

**Comment by timvisee** [comment]
Updated. Done!

Sorry for the inconvenience.

**Comment by lzutao** [comment]
@Mark-Simulacrum, Please reapprove this commit!

**Pull request closed without merging**
