### PR TITLE
Fix argument order in printed output on panic

### PR DESCRIPTION
**Pull request by sgrif**
Before this commit, the output printed when panicking was:

> Thread 'name' panicked at 'msg', location

when it should have been:

> Thread 'name' panicked at location, 'msg'

This bug was originally introduced in 576f59a. The message was changed
to something which implies the location comes before the message,
without changing the order of the arguments. A similar change was made
in f8a4d09, with the only reason given being consistency between the
Rust runtime and C++ runtime. We could also go back towards something
closer to that message ("Thread 'name' panicked: 'msg' at location"), I
don't really have any preference.

There are ~125 tests which will need to be updated as a result of this change, but I wanted to make sure folks were interested in fixing this before going through and updating them all. This bug has been here for 7.5 years, so I can't imagine I'm the first one to bring this up. However, I looked for an existing issue/PR and couldn't find one. I may have been searching for the wrong terms though

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I have not seen an issue to this effect (ever).

I am generally in favor of this, and don't personally feel that consistency with C++ matters here.

However, this is probably a change we'll want to get libs team feedback on, so let's try r? @dtolnay to hopefully kick off an fcp here.

**Comment by sgrif** [comment]
> and don't personally feel that consistency with C++ matters here.

The consistency mentioned was between two implementations of the Rust runtime which at the time had both a C++ and Rust implementation, not some C++ error in the wild today

**Review by dtolnay — COMMENTED** [review]
The panic message has been stagnant for a long time and I agree that we should feel free to do better.

If we are putting some thought into this for the first time, I think it would be worth brainstorming some alternative formats for the panic message. It doesn't have to be RFC-level but just if we are touching the message and the tests anyway, briefly considering whether we might be missing an opportunity for the message to be overall friendlier. Maybe we can interest @yoshuawuyts (in light of https://blog.yoshuawuyts.com/runtime-diagnostics/) or @estebank in drafting a concept of what a panic might ideally look like?

Possible inspiration: (the top of) https://github.com/athre0z/color-backtrace/tree/fbcd17b127771f3c2c385ddad8439c9470870d6b#screenshot.

If no one is interested in thinking about this in the near term I'm fine accepting the change in the PR for now, just thought this was a good opportunity to evaluate whether this part of the language is on the right track.

Thanks @sgrif! Good catch.

<br>

### 1.0.0 &mdash; 1.7.0

```console
thread '<main>' panicked at 'not yet implemented', src/main.rs:2
```

### 1.8.0 &mdash; 1.10.0

```console
thread '<main>' panicked at 'not yet implemented', src/main.rs:2
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### 1.11.0 &mdash; 1.19.0

```console
thread 'main' panicked at 'not yet implemented', src/main.rs:2
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### 1.20.0 &mdash; 1.32.0

```console
thread 'main' panicked at 'not yet implemented', src/main.rs:2:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### 1.33.0 &mdash; 1.40.0

```console
thread 'main' panicked at 'not yet implemented', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### 1.41.0+

TBD, but better!

**Comment by sgrif** [comment]
Definitely in favor of coming up with something better, and I'm happy to do the legwork when there's consensus

**Review by Manishearth — APPROVED** [review]
I am +1 on making this change

**Comment by sgrif** [comment]
I like the linked crate as a basepoint. I think its formatting of the backtrace should be left there for now or done as a separate PR, but for the base output, perhaps we could go with something similar such as this?

```plain
Thread 'name' panicked at file.rs (line 12, column 1).
Message: Panic message goes here.
         If it's multiline it will be indented.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

One thing that stood out to me as I was thinking about this is that the `file:line:col` format, while standard, isn't particularly discoverable if you've never seen it before. Some tooling does handle `file:line`, but I'm not sure prioritizing copy/paste-ability for the editors that handle it is more ergonomic than something which can be understood by more humans, especially since going to a given line is an extra keystroke or two at most.

**Comment by Mark-Simulacrum** [comment]
In terms of our constraints, I think it may make sense to try to work hard to limit ourselves to just one line for the primary bit of information (message and location). Otherwise in programs that are printing to stderr from different threads (or just aggregating into syslog, etc) it becomes hard to interpret which lines are which. Of course e.g. the backtrace is likely to get split up in such a scenario, but we should at least get the file number and message on a single line I think.

I am personally a big fan of the style that Yosh suggested, with the primary information still being present but also including some nicer looking information if it's available.

On the other hand, including something like this might not be tenable in general due to a sizeable increase in executable size from all of these strings being included (or generally making panicking expensive -- e.g., needing more than the one allocation we currently may use in std).

```
thread 'main' panicked at 'todo!', src/main.rs:2:5
 --> src/main.rs:2:5
  |
2 |     todo!();
  |     ^^^^^^^^^ help: `fn main` has not yet been implemented
```

**Comment by sgrif** [comment]
I agree with both your points. However, I think the use case of "everything must be single line for ease of logging tools" basically never co-exists with wanting a nicely formatted source line. Or more concretely it seems reasonable to me to only include that extra output in debug mode.

That said, with the constraint of at least having the message/location on a single line, having the arguments swapped but the more human readable location seems like a decent improvement and easy in the short term?

```plain
Thread 'name' panicked at file.rs (line 1, column 2): 'message'
```

The biggest gripe to me is that this puts information in a weird order. Thread name is something that is conditionally useful, but certainly the least important of the three pieces of information presented. I would argue that location is probably the most important is location, since message is more likely than not to be `None.unwrap()` or `'explicit panic'`. With that in mind, something that would present the information in that order would be:

```
Application panicked at file.rs (line 1, column 2) with 'message' on thread 'name'
```

**Comment by Frizi** [comment]
Please note that the specific syntax of `path/to/file.rs:line:column` is a defacto standard and is used by various terminals to link to locations in files. A good example of this is a built-in terminal in VSCode that allows jumping from panic messages directly to the line it occurred on.

**Comment by sgrif** [comment]
> One thing that stood out to me as I was thinking about this is that the file:line:col format, while standard, isn't particularly discoverable if you've never seen it before. Some tooling does handle file:line, but I'm not sure prioritizing copy/paste-ability for the editors that handle it is more ergonomic than something which can be understood by more humans, especially since going to a given line is an extra keystroke or two at most.

**Comment by Mark-Simulacrum** [comment]
> However, I think the use case of "everything must be single line for ease of logging tools" basically never co-exists with wanting a nicely formatted source line. Or more concretely it seems reasonable to me to only include that extra output in debug mode.

Yes, I agree I think -- basically, the nice error-like inclusion of the line would be limited to non-optimized builds, perhaps.

I agree that the thread name almost never matters enough to give it the prominence we do today. I think `Application panicked at file.rs (line 1, column 2) with 'message' on thread 'name'` is maybe not bad, but perhaps something like this would be better?

`panic: 'message' at file.rs (line 1, column 2) on thread 'name'`.

I am personally not sure if we should deviate away from the `file.rs:1:2` form for the line/column information -- certainly, if we do, we produce a larger message. I think one point of contention for me is that the more elaborate message forms seem to always move the key information away from the start of the line (e.g., you have "Application panicked" and the location prior to the message).

OTOH, I feel similarly that we often currently don't have great messages, almost always it's just None unwrapped or so which isn't super helpful most of the time. As an aside, I wonder -- now that we've stabilized `std::any::type_name` -- does it make sense to change the unwraps on None to emit `None::<SomeType> unwrapped`? at least that way you get a little more information and often that can be the difference, especially if you have more than one unwrap on the same line...

**Comment by lzutao** [comment]
gcc and clang uses
```
<source>:3:6: error message
```

**Comment by Ixrec** [comment]
On line/column numbers, is there any reason we can't do both styles?
`file.rs:1:2 (line 1, column 2)`

**Comment by estebank** [comment]
FWIW, I would love to see an opt-out version of @Mark-Simulacrum's suggestion,

```
panic in thread 'main': 'foo'
 --> src/main.rs:2:5
  |
2 |     panic!("foo");
  |     ^^^^^^^^^^^^^ foo
```

but would be fine with a minimal change to

```
thread 'main' panicked at src/main.rs:2:5 with 'not yet implemented'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

or

```
thread 'main' panicked at src/main.rs:2:5: not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by dtolnay** [comment]
Is the filename more relevant or the message? Usually I would expect it would be more helpful to read the message first, as long as the filename is available too in a predictable spot. "thread 'main' panicked at src/main.rs:2:5: not yet implemented" feels like a step backward to me, especially with longer file paths.

Here is a sketch of another format to jog our inspiration:

```console
PANIC: not yet implemented -- src/main.rs:2:5
  location: src/main.rs (line 2)
  thread: 'main'
  note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

```console
PANIC: not yet implemented -- src/main.rs:2:5
  location: src/main.rs (line 2)
  thread: 'main'
BACKTRACE:
  0: backtrace::backtrace::libunwind::trace
        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
  1: std::panicking::begin_panic
        at /rustc/59947fcae6a40df12e33af8c8c7291014b7603e0/src/libstd/panicking.rs:404
  2: testing::main
        at src/main.rs:2
```

**Comment by dtolnay** [comment]
Reassigned to @Manishearth to make the judgement as to when this is No Longer Worth Discussing Anymore and then we can FCP. :heart:

**Comment by estebank** [comment]
What about the following? (without the spans)

```
panic in thread 'main': not yet implemented
 --> src/main.rs:2:5
```

```
panic in thread 'main': not yet implemented
 --> src/main.rs:2:5
BACKTRACE:
  0: backtrace::backtrace::libunwind::trace
        at /cargo/registry/src/backtrace/libunwind.rs:88
  1: std::panicking::begin_panic
        at /rustc/src/libstd/panicking.rs:404
  2: testing::main
        at src/main.rs:2
```

This way the output should result familiar to rust devs.

**Comment by Mark-Simulacrum** [comment]
I think moving the thread name after the panic message is something we should aim for. I like @estebank's idea of the "optional spans" while keeping the `-->` syntax.

Maybe we can put the thread where the other "location" information is?

```
panic: "not yet implemented"
 --> src/main.rs:2:5, thread 'main'
BACKTRACE:
  0: backtrace::backtrace::libunwind::trace
        at /cargo/registry/src/backtrace/libunwind.rs:88
  1: std::panicking::begin_panic
        at /rustc/src/libstd/panicking.rs:404
  2: testing::main
        at src/main.rs:2
```

**Comment by Manishearth** [comment]
I think we should stick to file:line:column because this works by default with most terminals and IDEs. It would also be good if we can keep it on one line, but I definitely want us to explore better UI options here.

I'm already r+ on this, do we need to FCP?

**Comment by Mark-Simulacrum** [comment]
I think we're still in the process of coming to consensus on the best design here -- even if we stick to file:line:col there's I believe at least a few options. I hope to be able to spend some time on this tomorrow and write up a summary of the options at least and hopefully my own views.

**Comment by Manishearth** [comment]
Sounds good. I was hoping we could land this change as is and maybe have a different discussion about improving these, but I don't mind doing both at once

**Comment by Mark-Simulacrum** [comment]
I agree with @Manishearth that we should stick to having `file:line:col` somewhere in the output.

I believe that the constraints (along with one or two open questions) are:

* All information is on a single line
  * This helps make sure that logging etc is easily greppable while maintaining all information in one place
* We need to include: error message and error location
   * We've mostly always included the thread name, but I am not sure that we should
      * At least, if the name is the default, that seems like it adds almost no information
      * Do we know of a case where the name is beneficial? It seems like almost always the location/error message should be enough
* What order should we use?

To be concrete, my proposal is to maximally use this:

```
panic: "not yet implemented", at src/main.rs:2:5 on thread 'main'
```

and if we detect that the thread name has not been set, then we omit the "on thread" piece for `panic: "not yet implemented", at src/main.rs:2:5` which would be the common case for many Rust programs today. Tokio at least sets thread names to `tokio-*-{1,2,3,...}` for each of its worker threads, and maybe this would be sort of a downside of doing so, but I'm not sure what the reasoning for setting that information is (it does not seem hugely useful to me).

This fulfills my personal preference on order, which is message, location, and then (optionally) thread.

This could then be extended in the future (or by e.g. crates replacing the default panic hook, I think), in a way that looks not horrible (if a bit odd) and maintains the same 'single-line' format.

```
panic: "not yet implemented", at src/main.rs:2:5 on thread 'main'
 --> src/main.rs:2:5, thread 'main'
    unimplemented!()
```

For reference the current output is:

```
Thread 'main' panicked at 'not yet implemented', src/main.rs:2:5
```

and a regular error message from the compiler is:

```
error: incorrect close delimiter: `}`
  --> src/main.rs:10:1
```

----------

I would propose that we wait for a bit (maybe a few days) and then if there's no objections to my proposal FCP this with the libs(?) team for final approval, or just merge it. I'm not sure we need a formal FCP, but don't object to having one :)

**Comment by Manishearth** [comment]
I'm okay with or without a formal fcp. Your proposal seems fine, but as you said we definitely should wait for others to weigh in.

**Comment by estebank** [comment]
I threw around a quick mockup leveraging `human-panic` to see what some of the ideas would look like

Screen Shot 2019-12-19 at 3 56 31 PM

```
panic: OMG EVERYTHING IS ON FIRE!!!
  --> tests/custom-panic/src/main.rs:17:3
   |
17 |   panic!("OMG EVERYTHING IS ON FIRE!!!");
   |   ^~~
  ::: tests/custom-panic/src/main.rs:13:1
   |
13 |   foo();
   |   ^~~ 0: 0x103509ce0 - custom_panic_test::main::h20ecc527e431a0b3
  ::: /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/rt.rs:67:1
   | 0: 0x103509c12 - std::rt::lang_start::{{closure}}::hb6bdba643f51f66f
  ::: src/libstd/rt.rs:52:1
   | 0: 0x103563548 - std::rt::lang_start_internal::{{closure}}::hc58c6d65eddab43f
   ::: src/libstd/panicking.rs:292:1
    | 1: 0x103563548 - std::panicking::try::do_call::h1693ed59f66b9306
  ::: src/libpanic_unwind/lib.rs:78:1
   | 0: 0x10356504f - __rust_maybe_catch_panic
   ::: src/libstd/panicking.rs:270:1
    | 0: 0x103563ede - std::panicking::try::h16546adfad4ff0ff
   ::: src/libstd/panic.rs:394:1
    | 1: 0x103563ede - std::panic::catch_unwind::h9f8111749c7f253d
  ::: src/libstd/rt.rs:51:1
   | 2: 0x103563ede - std::rt::lang_start_internal::h3806eae227db69b6
  ::: /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/rt.rs:67:1
   | 0: 0x103509bf2 - std::rt::lang_start::hb9532b1815095118
```

I tried using `annotate-snippets-rs` but I couldn't get colored output to work within a minute so I redid things by hand.

**Comment by dtolnay** [comment]
Nice! This looks amazing in combination with https://github.com/rust-lang/rust/issues/47809.

```console
panic: invalid digit found in string
  --> src/main.rs:17:3
   |
17 |   input.parse::<usize>().unwrap();
   |   ^~~
```

**Comment by Mark-Simulacrum** [comment]
Hm, so both of those examples deviate from what I thought was an accepted constraint: getting all the information on one line.

However, I agree that they look better... I'm not sure that we can deviate from the constraint, though. I have no hard reasons beyond a loose feeling that logging tools support single lines better than multiple, but I don't have much experience with a variety of tooling so that might be an incorrect impression.

**Comment by Manishearth** [comment]
I don't think human-panic is something we should be trying for here: that's going to bloat binary size and cause a bunch of other issues. That's something we should investigate as an option somewhere, in a separate PR.

**Comment by estebank** [comment]
Before I played around I wanted the two line output in `rustc`. Now that I have something working, I think this should go in `human-panic` and leave the default to be the simple suggestions above (we might even nudge people to opt-in into using the crate).

The biggest benefits of leaving this outside of rustc are 1) we don't bloat people by accident and 2) iteration on the output can be dramatically faster:

Screen Shot 2019-12-19 at 4 57 48 PM

**Comment by hdhoang** [comment]
ping from triage @sgrif, could you rebase this and ask the reviewer to r+ again?

**Comment by Dylan-DPC** [comment]
closing this due to inactivity

**Pull request closed without merging**
