### PR TITLE
Group rfcs tests

### PR DESCRIPTION
**Pull request by WaffleLapkin**
This moves all RFC tests to `tests/ui/rfcs/rfc-NNNN-title-title-title/...`

I had to rename some tests due to conflicts, but otherwise this is just a move.

### CODE REVIEW

**Comment by oli-obk** [comment]
r=me after a rebase

@bors rollup

**Comment by petrochenkov** [comment]
I don't think this is an improvement, the `rfcs` directory is artificial, meaningless by itself, and doesn't map to a WG or a set of people that work on a specific compiler area and could maintain the corresponding subset of tests.

I think specific `rfc-NNNN-feature-name` subdirectories should be moved to "semantically meaningful" subdirectories like `privacy`, or `lexer`, or `auto-traits` or whatever.

cc https://github.com/rust-lang/rust/issues/73494

**Comment by WaffleLapkin** [comment]
@petrochenkov I agree that `rfcs/` does not make much sense in the long run and we should sort things better, however in the meantime it makes sense to use the same style for all RFCs, even if eventually we won't have rfc-specific directories at all.

@bors r=oli-obk

**Comment by petrochenkov** [comment]
@WaffleLapkin 
It's not useful in a short turn either, it only creates churn in git history and adds one more directory to the [list](https://github.com/rust-lang/rust/issues/73494#issuecomment-761772344) of meaningless directories to be dismantled.
Reverting this doesn't make sense because that would only add more churn, but I wish I `r-` this PR more explicitly to prevent it from landing.
Please, do not move any more tests mechanically, like in this PR.

It's not necessary to dismantle the `rfc-NNNN-feature-name` directories immediately, they can be moved to meaningful subdirectories as whole too.

**Comment by WaffleLapkin** [comment]
> adds one more directory to the [list](https://github.com/rust-lang/rust/issues/73494#issuecomment-761772344) of meaningless directories to be dismantled.

`rfcs/` already existed, so this does not change the list.

**Pull request merged**
