### PR TITLE
make Atomic*::min/max work on armv5te

### PR DESCRIPTION
**Pull request by llogiq**
r? @kennytm

This fixes #52586

### CODE REVIEW

**Comment by llogiq** [comment]
cc @infinity0

**Comment by kennytm** [comment]
@llogiq What do you mean by fixing #52586 (which is this PR)...

**Comment by nagisa** [comment]
Probably https://github.com/rust-lang/rust/issues/52493

**Review by nagisa — COMMENTED** [review]
I feel that ideally we’d add the `__atomic_*` functions to compiler-rt/compiler-builtins, but fixing it here for a quick fix seems fine here as well.

Perhaps add a TODO?

**Comment by nagisa** [comment]
So, here’s a question now.

Supposedly we are exposing Atomics only to targets that support them in hardware. ARMv5 does not have any native hardware support for atomics. Why are the types exposed then?

cc @alexcrichton

**Comment by llogiq** [comment]
I'm a bit puzzled: If armv5te doesn't support atomics in hardware, how do the tests work at all? How can we extend the tests to ensure this works?

**Comment by nagisa** [comment]
I have no idea. Even the most trivial `store` and `swap` operations generate library calls to `__sync_lock_test_and_set` which *are* provided by compiler-builtins despite its [readme saying](https://github.com/rust-lang-nursery/compiler-builtins/blob/master/README.md):

> Rust only exposes atomic types on platforms that support them, and therefore does not need to fall back to software implementations.

**Comment by japaric** [comment]
@llogiq 

>  #[cfg(not(target_arch = "armv5te"))]

"armv5te" is not a value that the built-in target_arch cfg supports. target_arch has value "arm" for the `armv5te-unknown-linux-gnueabi` target. These are all the cfg values for that target:

``` console
$ rustc --print cfg --target armv5te-unknown-linux-gnueabi
debug_assertions
target_arch="arm"
target_endian="little"
target_env="gnu"
target_family="unix"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="8"
target_has_atomic="cas"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="32"
target_thread_local
target_vendor="unknown"
unix
```

And these are the cfg values for `arm-unknown-linux-gnueabi` target, which supports ARMv6+:

``` console
$ rustc --print cfg --target arm-unknown-linux-gnueabi
debug_assertions
target_arch="arm"
target_endian="little"
target_env="gnu"
target_family="unix"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="cas"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="32"
target_thread_local
target_vendor="unknown"
unix
```

Right now, there's no way built-in way to differentiate the armv5 from the armv6 subarchitecture.

**Comment by llogiq** [comment]
@japaric so the correct way to solve this would be to change the `armv5te-unknown-linux-gnueabi` target definition to remove the `target_has_atomic` cfgs?

**Comment by nagisa** [comment]
I think that is the correct approach, yes.

**Comment by japaric** [comment]
@nagisa 

> Supposedly we are exposing Atomics only to targets that support them in hardware

We are exposing atomics only to targets that support them *as a whole*. On its own, ARMv5 doesn't have the instructions required for a CAS loop, *but* Linux provides kernel helpers (\*) to implement CAS loops on that architecture. So "ARMv5 Linux" having `atomic_cas: true` in its spec is correct; whereas, an "ARMv5 bare metal" target should have `atomic_cas: false`.

(\*) The compiler-builtins crate exposes the Linux kernel helpers as the symbols that LLVM emits calls of when lowering e.g. intrinsics::atomic_xchg.

@llogiq 

> so the correct way to solve this would be to change the armv5te-unknown-linux-gnueabi target definition to remove the target_has_atomic cfgs?

I don't know what the problem that needs solving is; I was simply commenting that `target_arch = "armv5te"` doesn't exist. But changing `atomic_cas` to false for the ARMv5 Linux target would break existing builds for that target.

To be able to conditionally compile different code for ARMv5 you would probably need to a "v6" target feature (For an example, see #52120 which adds the "mclas" target feature)  and use something like `#[cfg(all(target_arch = "arm", not(target_feature = "v6"))]`.

**Comment by nagisa** [comment]
> The compiler-builtins crate exposes the Linux kernel helpers as the symbols that LLVM emits calls of when lowering e.g. intrinsics::atomic_xchg.

Care to point where exactly?

**Comment by japaric** [comment]
@nagisa https://github.com/rust-lang-nursery/compiler-builtins/blob/master/src/arm_linux.rs

**Comment by nagisa** [comment]
So the right fix would be to add the necessary functions there.

**Comment by llogiq** [comment]
@nagisa What functions are necessary besides `__cmp_xchg`?

**Comment by nagisa** [comment]
@llogiq LLVM calls the `__sync_fetch_and_{,u}{min,max}` family of functions for this operation. Amusingly those operations seem to be already present in the file linked by @japaric above, so not sure why stuff does not work:

```rust
atomic_rmw!(__sync_fetch_and_max_1, i8, |a: i8, b: i8| if a > b { a } else { b });
atomic_rmw!(__sync_fetch_and_max_2, i16, |a: i16, b: i16| if a > b { a } else { b });
atomic_rmw!(__sync_fetch_and_max_4, i32, |a: i32, b: i32| if a > b { a } else { b });

atomic_rmw!(__sync_fetch_and_umax_1, u8, |a: u8, b: u8| if a > b { a } else { b });
atomic_rmw!(__sync_fetch_and_umax_2, u16, |a: u16, b: u16| if a > b { a } else { b });
atomic_rmw!(__sync_fetch_and_umax_4, u32, |a: u32, b: u32| if a > b { a } else { b });

atomic_rmw!(__sync_fetch_and_min_1, i8, |a: i8, b: i8| if a < b { a } else { b });
atomic_rmw!(__sync_fetch_and_min_2, i16, |a: i16, b: i16| if a < b { a } else { b });
atomic_rmw!(__sync_fetch_and_min_4, i32, |a: i32, b: i32| if a < b { a } else { b });

atomic_rmw!(__sync_fetch_and_umin_1, u8, |a: u8, b: u8| if a < b { a } else { b });
atomic_rmw!(__sync_fetch_and_umin_2, u16, |a: u16, b: u16| if a < b { a } else { b });
atomic_rmw!(__sync_fetch_and_umin_4, u32, |a: u32, b: u32| if a < b { a } else { b });
```

**Comment by llogiq** [comment]
Maybe LLVM tries to generate the wrong instructions? *Something* breaks, but we're in the dark what it is. Maybe we could look into the assembly.

**Comment by nagisa** [comment]
Well below is what gets generated for `AtomicUsize::max(...)`

```asm
atomic_max_usize:
	.fnstart
	.save	{r11, lr}
	push	{r11, lr}
	.pad	#8
	sub	sp, sp, #8
	ldr	r0, [r0]
	ldr	r1, [r1]
	str	r0, [sp, #4]
	add	r0, sp, #4
	bl	__sync_fetch_and_umax_4
	add	sp, sp, #8
	pop	{r11, pc}
```

The genrated code is very similar for i16 (calls `__sync_fetch_and_max_2`) and different orderings do not affect the function called AFAICT.

**Comment by TimNN** [comment]
Ping from triage, @llogiq! What is the status of this? Is this blocked on some changes to the compiler built ins?

**Comment by llogiq** [comment]
I'm afraid I'm out of my depth here. I thought I could circumvent the problem, but it appears that I'm not really understanding the root cause, and I have no ARM5 hardware at home to test on. Closing this.

**Comment by infinity0** [comment]
Well we still have 40 failing tests on armv5te - and any rust code that depends on it won't compile on that platform, @nagisa any ideas?

**Comment by nagisa** [comment]
@infinity0 I have no idea why `__atomic*` functions from the `compiler-builtins` are not visible to code, no.

My susipicion is that they are simply not exported for some reason.

**Comment by infinity0** [comment]
@nagisa The build.rs for compiler_builtins is very specific and [only includes the sync_and_fetch compiler-rt assembly implementations when being built on arm7](https://github.com/rust-lang-nursery/compiler-builtins/blob/master/build.rs#L351), is that the problem?

**Comment by nagisa** [comment]
Could be. As pointed out in comments above, there’s a pure-rust implementation [here](https://github.com/rust-lang-nursery/compiler-builtins/blob/master/src/arm_linux.rs) as well, but it is likely that those are not exported for *some* reason.

**Comment by infinity0** [comment]
I'm very sketchy on my binary knowledge but I thought "exporting" was only for shared library symbols. In any case, building rust-lang-nursery/compiler-builtins@5b05a98 with `--target armv5te-unknown-linux-gnueabi` gives me:

~~~~
(sid_armel-dchroot)infinity0@amdahl:~/compiler-builtins$ nm target/armv5te-unknown-linux-gnueabi/debug/libcompiler_builtins.rlib 2>/dev/null | grep sync_fetch
00000000 t _ZN17compiler_builtins9arm_linux21__sync_fetch_and_or_128_$u7b$$u7b$closure$u7d$$u7d$17h97cc3fa3810ae9f8E
00000000 t _ZN17compiler_builtins9arm_linux21__sync_fetch_and_or_128_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17hfa81fbd175d7c2d5E
00000000 t _ZN17compiler_builtins9arm_linux21__sync_fetch_and_or_228_$u7b$$u7b$closure$u7d$$u7d$17had8499e053cd0555E
00000000 t _ZN17compiler_builtins9arm_linux21__sync_fetch_and_or_228_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17h79069ba6ce60a99eE
[..]
00000000 T __sync_fetch_and_umax_1
00000000 T __sync_fetch_and_umax_2
00000000 T __sync_fetch_and_umax_4
00000000 T __sync_fetch_and_umin_1
00000000 T __sync_fetch_and_umin_2
00000000 T __sync_fetch_and_umin_4
00000000 T __sync_fetch_and_xor_1
00000000 T __sync_fetch_and_xor_2
00000000 T __sync_fetch_and_xor_4
~~~~

whereas the same command `nm` for `--target armv7-unknown-linux-gnu` gives no output.

If anyone has any ideas on what to try please let me know, I have access to both armv5 and armv7 targets via Debian's porting machines.

**Pull request closed without merging**
