### PR TITLE
Move ty::print methods to Drop-based scope guards

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Primary goal is reducing codegen of the TLS access for each closure, which shaves ~3 seconds of bootstrap time over rustc as a whole.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @antoyo and @bjorn3 on the codegen_gcc/cranelift changes (highfive didn't poke because I r'd ghost initially)

@bors try @rust-timer queue after moving to a macro -- shouldn't really matter for codegen perf, though.

r? rust-lang/compiler

Overall the perf improvement for bootstrap time here is pretty significant -- 6 seconds is a good chunk. The regression is IMO not significant enough (and pretty likely to be just optimizer noise) to block this PR from moving ahead.

**Comment by oli-obk** [comment]
@bors r+

How did you find this? Did it show up in cachegrind dumps?

**Comment by Mark-Simulacrum** [comment]
No, cachegrind isn't really the right tool for tracing back to source code from LLVM IR. I'm looking at no-prepopulate-passes LLVM IR from rustc_query_impl and trying to identify duplicated work based on that (e.g., places where we're generating a lot of IR for no good reason).

**Review by antoyo — APPROVED** [review]
The gcc part looks good to me.

**Pull request merged**
