### PR TITLE
Bump to 1.72.0

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @jyn514 @chenyukang -- reverting #111538 for now, it breaks our ability to do bumps (added a note to the revert commit message). Happy to see that re-land but we need to proceed with the release right now.

**Comment by jyn514** [comment]
that's fine to revert for now, yeah.

> This breaks our ability to bump the src/version where we're bootstrapping with an older compiler
than usual (according to version number)

ah hmm, I guess the problem is that for a ~week we're building 1.72 nightly with 1.70 beta? I wonder if we could have some field in config.toml that explicitly opts in to allowing it to be 2 versions apart instead of 1, and disable it once we bump to 1.71 beta.

anyway, we can worry about that after this merges.

**Comment by Mark-Simulacrum** [comment]
Well, it would be something like a change in defaults during the period at least - which feels hacky. I'm not sure it adds enough value for the hassle.

I guess we could try to only do this when building from source tarballs or something like that, if I understood the original issue correctly, that should mitigate most of the pain. Building in-tree with stage0.json compilers isn't really a case where you have a problem. (Though there's not a trivial conditional, because it's totally valid to build the nightly artifacts from the source tarballs during this week).

**Comment by jyn514** [comment]
ah! that's a great point, we can just turn this check off altogether when `rustc` is unset and we're using stage0.json, i think that should help all the cases of the original issue without adding a maintenance burden :)

**Comment by chenyukang** [comment]
I will add a fix to the original PR.

**Pull request merged**
