### PR TITLE
Remove raw_pointer_deriving lint

### PR DESCRIPTION
**Pull request by devonhollowood**
Implement #14615

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+

Looks good to me, thanks!

**Comment by Manishearth** [comment]
```
../src/liblibc/src/lib.rs:13:21: 13:39 error: unknown `allow` attribute: `raw_pointer_derive`, #[deny(unknown_lints)] on by default
../src/liblibc/src/lib.rs:13 #![allow(bad_style, raw_pointer_derive, overflowing_literals, improper_ctypes)]
                                                 ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

You'll have to open a PR to https://github.com/rust-lang-nursery/libc first to remove that.

**Comment by Manishearth** [comment]
@alexcrichton Do we consider breakages in `allow` lints (e.g. `unknown_lints` in this case) to be a breaking change?

**Comment by devonhollowood** [comment]
I submitted a [pull request](https://github.com/rust-lang-nursery/libc/pull/65) to libc.
If we do consider this a breaking change, maybe it makes more sense to go back and change the default lint level from `Warn` to `Allow` instead of the changes here (which to my understanding would be non-breaking). If we do decide to do that, would it be cleaner to do so from a new pull request?

**Comment by alexcrichton** [comment]
Nah this isn't a breaking change because it's just tweaking lints, which aren't considered breaking changes (due to `--cap-lints`)

**Comment by Manishearth** [comment]
Cool.

@devonhollowood It landed, so you need to now update the submodule to https://github.com/rust-lang-nursery/libc/commit/8531cc11e196b7ae9072ae7b384a930ff7b00dfb and add it to your commit. If you need help:

```rust
cd src/liblibc
git fetch origin
git checkout 8531cc11e196b7ae9072ae7b384a930ff7b00dfb
cd ..
git add liblibc
git commit --amend
```

or something like that.

**Comment by brson** [comment]
This caused breakage. I was under the impression that lints are never supposed to be removed because of this problem and simply turned to no-ops.

**Comment by Manishearth** [comment]
I thought lint changes are fine because of lint capping?

**Pull request merged**
