### PR TITLE
get rid of duplicate primitive_docs

### PR DESCRIPTION
**Pull request by RalfJung**
Having this duplicate makes editing that file very annoying. And at least locally the generated docs still look perfectly fine...

### CODE REVIEW

**Comment by RalfJung** [comment]
Cc https://github.com/rust-lang/rust/pull/87073 @jyn514

**Comment by RalfJung** [comment]
Ah, this seems to be the key point that wasn't mentioned in the files
> this doesn't use purely relative links because that introduces new broken links when the docs are re-exported (e.g. String's &str deref impl, or Vec's slice deref impl).

But I feel like duplicating the file is not a great solution for that... it makes for a pretty bad contributor experience when editing that file.

**Comment by the8472** [comment]
Symlinks would solve that but they cause issues for windows devs who don't have developer mode enabled.

**Comment by RalfJung** [comment]
Hm, CI passed to maybe the quoted statement about broken links is not true any more...?

**Comment by RalfJung** [comment]
> Symlinks would solve that but they cause issues for windows devs who don't have developer mode enabled.

Yeah I figured that was the reason for this. But my backup plan if we cannot `include!` the same file would be to make `bootstrap` copy the file from core to std before the build (and placing the std file in gitignore). That would still avoid having the file checked in twice.

**Comment by Mark-Simulacrum** [comment]
We might be able to copy it somewhere else, but src directories are read-only mounted in CI. Should be workable otherwise...

**Comment by RalfJung** [comment]
Currently it doesn't look like we need to copy it at all?

**Comment by RalfJung** [comment]
r? @Mark-Simulacrum 
since you also reviewed https://github.com/rust-lang/rust/pull/87073

**Comment by RalfJung** [comment]
(I'm going to wait for feedback on the approach before rebasing; this will obviously have a conflict each time the file is changed.)

**Comment by Mark-Simulacrum** [comment]
> Ah, this seems to be the key point that wasn't mentioned in the files
> 
> > this doesn't use purely relative links because that introduces new broken links when the docs are re-exported (e.g. String's &str deref impl, or Vec's slice deref impl).
> 
> But I feel like duplicating the file is not a great solution for that... it makes for a pretty bad contributor experience when editing that file.

I've been trying to reproduce this problem... linkcheck doesn't seem to find problems on this branch, and poking around a couple of primitive doc files I'm not seeing broken links either (but perhaps I'm not finding something). My inclination is to merge and we can back it out if problems arise.

@RalfJung did you manage to reproduce the problem above? If so, then the alternative approach of bootstrap copying files around might be reasonable (copying from core to a std-loaded directory would be my preference).

**Comment by RalfJung** [comment]
Hm, maybe it works because neither `str` nor `slice` actually use any relative links right now? But I also don't think `Deref` creates a copy of the type docs so I'm rather confused by that comment. Maybe rustdoc behavior also changed.

**Comment by RalfJung** [comment]
I've added a relative test link in `str`, let's see if CI complains.

**Comment by RalfJung** [comment]
CI seems fine. So I think we can conclude that something change since back then and relative links are actually okay now?

I'll take the commit back out of the PR.  If you want to check it out, it's https://github.com/rust-lang/rust/pull/115494/commits/ccbb7b350c2324f70d4ec9c223417a572062e732.

**Comment by Mark-Simulacrum** [comment]
Yeah, maybe. Let's proceed for now and we can revert & re-evaluate if folks report problems. @bors r+

**Pull request merged**
