### PR TITLE
LLVM: Update submodule to include patches for MSP430.

### LINKED ISSUE #37829: LLVM assertion when compiling `core` for the MSP430 architecture
### STR

```
$ cat msp430.json
{
  "arch": "msp430",
  "data-layout": "e-m:e-p:16:16-i32:16:32-a:16-n8:16",
  "executables": true,
  "linker": "msp430-elf-gcc",
  "llvm-target": "msp430",
  "max-atomic-width": 0,
  "no-integrated-as": true,
  "os": "none",
  "panic-strategy": "abort",
  "relocation-model": "static",
  "target-endian": "little",
  "target-pointer-width": "16"
}

$ rustup component add rust-src

$ rustc --target msp430 $(rustc --print sysroot)/lib/rustlib/src/rust/src/libcore/lib.rs
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/Support/APInt.cpp:939: llvm::APInt llvm::APInt::trunc(unsigned int) const: Assertion `width < BitWidth && "Invalid APInt Truncate request"' failed.
```

### Meta

```
$ rustc -V
rustc 1.15.0-nightly (43006fcea 2016-11-15)
```

I didn't see this when I tested #37672 because the default rustbuild configuration has LLVM assertions disabled whereas nightlies enable the assertions. 😞

cc @alexcrichton

### PR DESCRIPTION
**Pull request by pftbest**
Fixes #37829

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @pftbest!

@bors r+

**Comment by pftbest** [comment]
Why did it fail checks? Is there something wrong with PR?

**Comment by japaric** [comment]
> Is there something wrong with PR?

No AFAICT

> Why did it fail checks?

That particular Travis build job has been failing in several other PRs though I don't know why. It's a false alarm.

**Comment by pftbest** [comment]
@japaric 
good to know, thanks!

**Pull request merged**
