### PR TITLE
Fixes error count display is different when there's only one error left

### PR DESCRIPTION
**Pull request by adrianEffe**
### What does this PR try to resolve?
Relates to Cargo issue [#12390](https://github.com/rust-lang/cargo/issues/12390) and the intention is to align rustc and cargo.
Related cargo PR [#12484](https://github.com/rust-lang/cargo/pull/12484)

When there's only 1 error left, the number 1 appears in the output so that it scans the same as the output when there's more than 1 error, so:

```
error: could not compile `crate` (lib test) due to 1 previous error
``` 
instead of the current:
```
error: could not compile `crate` (lib test) due to a previous error
```

### CODE REVIEW

**Comment by Nilstrieb** [comment]
thank you for your PR. I think it's likely that your PR will not be accepted, simply due to being extremely hard to review (because the diff is so huge). This is especially conflict heavy and you'll probably have a bad time just keeping up with conflicts.

I think the way to do this change (which is a good change imo) is to have a trusted member from the compiler (contributors) team do the change and then quickly get it reviewed (without reviewing the entire diff, trusting that the author didn't make big mistakes). But I'm not sure whether this would be a good solution either.

I currently don't have much time for Rust so I definitely can't help here.

Just trying to set expectations^^

**Comment by adrianEffe** [comment]
Hi @Nilstrieb, thanks for your comment 🙏.
 Totally agree, I was waiting for someone to acknowledge this pr really, as you said it doesn't make much sense for me to keep up with changes.
 It would be great if someone from the compiler team is willing to help with this, goes without saying I'm willing to help see this through however I can. ☺️

**Comment by wesleywiser** [comment]
r? wesleywiser

**Comment by WaffleLapkin** [comment]
@wesleywiser fyi, I'm willing to help with this (either by re-blessing the tests as a trusted contributor as suggested by @Nilstrieb, or by reviewing you, if you want to do this, etc)

**Comment by apiraino** [comment]
Given the time elapsed since your question @WaffleLapkin I can safely assume that you can take on the review of this one. I'll reassign this PR to you. Thank you for your help! In case, please @wesleywiser feel free to chime in and revert the review reassignment.

**Comment by Nilstrieb** [comment]
In collaboration with @WaffleLapkin, I'm going to implement my plan above by basically re-doing your PR (crediting you as a co-author of course!) and then putting up a new PR that waffle will approve.

**Comment by WaffleLapkin** [comment]
Closing since https://github.com/rust-lang/rust/pull/118138 was merged.

**Pull request closed without merging**
