### PR TITLE
Update E0008 and E0007 to new format

### PR DESCRIPTION
**Pull request by srdja**
Part of #35233
A fix for #35496 

r? @jonathandturner

### CODE REVIEW

**Comment by arielb1** [comment]
Could you also change the 2 nearby errors?

**Comment by srdja** [comment]
@arielb1 

Sure, I can fix `E0007` (@DevShep is working on `E0009`), but I'd like to get some feedback from @jonathandturner first.

**Comment by jonathandturner** [comment]
@srdja - I'll sign you up for E0007 so you can fix that one.  @DevShep can fix E0009.  They're close together, but it's okay for multiple people to work on different ones.

**Comment by srdja** [comment]
@jonathandturner - I've updated `E0007`.

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Pull request merged**
