### PR TITLE
`EarlyBinder` docs

### PR DESCRIPTION
**Pull request by BoxyUwU**

### CODE REVIEW

**Comment by compiler-errors** [comment]
Failed in a rollup since the intra-docs link is incorrect. Not sure how best to test this, but there should be a way to do so -- once that's done r=me.

@bors r-

**Comment by wesleywiser** [comment]
I believe if you `x.py doc` it will show the same failure.

**Comment by BoxyUwU** [comment]
im so mad I literally ran `x.py doc` locally because I wanted to check links :neutral_face: I really wish we would catch this in CI

**Comment by wesleywiser** [comment]
Oh, I'm probably wrong then. Sorry for the noise!

**Comment by BoxyUwU** [comment]
No no you're right I just missed it..

**Comment by BoxyUwU** [comment]
broken lints is a warning when you do `x doc` so I must have ran `x doc` then it "succeeded" and I thought everythign was fine...

**Pull request merged**
