### PR TITLE
`assume` the runtime range of `align_offset`

### PR DESCRIPTION
**Pull request by scottmcm**
Found when I saw code with `align_to` having extraneous checks.

Demo that LLVM can't do this today: <https://rust.godbolt.org/z/6dnG749bq>

(It's filed as https://github.com/llvm/llvm-project/issues/62502.)

### CODE REVIEW

**Comment by thomcc** [comment]
I've wanted this for a while. I still have a lot of criticisms with the align_to API, but this should make it usable a lot more of the time.

@bors r+ rollup=never

**Comment by thomcc** [comment]
I've wanted this for a while. I still have a lot of criticisms with the align_to API, but this should make it usable a lot more of the time. r=me once you fix the compile errors.

@bors rollup=never

**Comment by thomcc** [comment]
Ah, compile errors. r=me with those fixed.

@bors r-

(P.S. Sorry if there are some sporatic comments from me here, I'm on a plane and the internet is... very spotty)

**Comment by scottmcm** [comment]
Ah, the `assume` being conditional blocked the branchless-ness that the assembly test was checking.  Luckily that didn't need to be conditional -- it's mathematically true -- so I just moved a bit of code earlier and the assembly test passes without needing any changes.

I also expanded the codegen test a bunch.

**Comment by scottmcm** [comment]
r? thomcc
@bors r=thomcc

**Comment by scottmcm** [comment]
Oh, when I added more to the tests it included something that adds extra checking in debug, and thus made the optimizations not work and the test fail.  Fixed.

@bors r=thomcc

**Comment by scottmcm** [comment]
Ah, of course, I got the 32-vs-64-bit differences right in 19 places, [but there are 20](https://github.com/rust-lang/rust/compare/9c57cdbd8e0d4b72016f5799acef89f1978e1b85..a1e5c65aa451473d1614fc04cf3c0e67247a17f1) 🤬 

@bors r=thomcc

**Pull request merged**
