### PR TITLE
create `config::tests::detect_src_and_out` test for bootstrap

### PR DESCRIPTION
**Pull request by onur-ozkan**
Resolves one of the `FIXME` in bootstrap

### CODE REVIEW

**Comment by albertlarsan68** [comment]
Have you tested when the `config.toml` file is not in the root of the repo?
r=me if so.
@bors rollup

**Comment by ozkanonur** [comment]
> Have you tested when the `config.toml` file is not in the root of the repo? r=me if so. @bors rollup

I did

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+

**Comment by jyn514** [comment]
This doesn't test everything I would like it to. I was thinking about the following cases when I wrote the comment:

1. Running bootstrap from the source root.
2. Running from a subdirectory of the source root.
3. Running from outside the source root.
4. Running on a different machine from where bootstrap was compiled (which will be important for #107812). You can mostly replicate this by renaming the source root so it no longer exists on disk.
5. Running with `--build-dir`.
6. Running with `$RUST_BOOTSTRAP_CONFIG` set in the environment and `build-dir` set in the file.

**Comment by jyn514** [comment]
oh ugh it's already in a rollup :(

@bors r+

but I would prefer to add more tests, or to add the comment back.

**Comment by ozkanonur** [comment]
> This doesn't test everything I would like it to. I was thinking about the following cases when I wrote the comment:
> 
> 1. Running bootstrap from the source root.
> 2. Running from a subdirectory of the source root.
> 3. Running from outside the source root.
> 4. Running on a different machine from where bootstrap was compiled (which will be important for [no python in shell scripts #107812](https://github.com/rust-lang/rust/pull/107812)). You can mostly replicate this by renaming the source root so it no longer exists on disk.
> 5. Running with `--build-dir`.
> 6. Running with `$RUST_BOOTSTRAP_CONFIG` set in the environment and `build-dir` set in the file.

First 3 works, and I am pretty sure for 4th as well. I haven't check the 5 and 6.

> but I would prefer to add more tests, or to add the comment back.

If I force push now, will it take the effect in rollup?

**Comment by jyn514** [comment]
No. the only way to cancel it is to close the rollup, and this isn't a regression so I don't think that makes sense.

**Comment by ozkanonur** [comment]
I will extend the test around this week

**Pull request merged**
