### PR TITLE
introduce a target to build the kernel of the unikernel HermitCore

### PR DESCRIPTION
**Pull request by stlankes**
We are developing the unikernel HermitCore, where the kernel is written in Rust and is already supported by the Rust Standard Library. To compile the kernel with the new build flag "-Z build-std", we introduce a new target, which avoids the usage of SSE & AVX within the kernel.

### CODE REVIEW

**Comment by bjorn3** [comment]
Could you use a target specification json file instead? Or does -Zbuild-std not support that yet?

**Comment by stlankes** [comment]
As far as I know, `build-std` does not support a json file ([https://doc.rust-lang.org/nightly/cargo/reference/unstable.html](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html)). I want to build the kernel as follow:

> cargo build -Z build-std=core,alloc --target x86_64-unknown-hermit-kernel

**Comment by bjorn3** [comment]
The docs don't explicitely say that it is not yet allowed.

**Comment by stlankes** [comment]
I just test a json file and it seems to work. Like x86_64_linux_kernel, it would help our work. But we could use a json file.

**Pull request merged**
