### PR TITLE
Correct fortanix LVI test print function

### PR DESCRIPTION
**Pull request by raoulstrackx**
A recent change resulted in a different machine code for the `print` function. This caused the LVI test for this function to fail. This PR:

- Fixes the test for the `print` function
- Simplified the test a bit so future modifications are more unlikely

cc: @jethrogb

### CODE REVIEW

**Comment by raoulstrackx** [comment]
Can this (tiny) PR get a review please?

**Comment by cuviper** [comment]
I honestly have no idea how to tell if this update is correct. What exactly is this testing, and what changed to make it need an update?

**Comment by raoulstrackx** [comment]
LVI is a transient execution vulnerability. It's mostly an issue for Intel SGX enclaves as its attack model is so strong. Due to LVI even very simple assembly instructions such as `ret` may leak potentially sensitive enclave data. To mitigate this, the compiler needs to insert various `lfence` operations and potentially replace instructions. The `ret` instruction for example is replaced with `popq %r10; lfence; jmp *%r10`.
There are various tests related to LVI as there may be various ways machine code can end up inside the enclave. The `print.checks` test that relates to this PR is basically a way to verify that the standard library itself has been compiled with LVI mitigations in place. Any other function of the standard library could have been used just as well. More specifically it checks that the `retq` instruction has been replaced and there is at least one more `lfence` it its body (so it does more than merely replace `retq` instructions). Previously the function ended with `callq _Unwind_Resume; ud2`. I'm not sure how that change got introduced, but it's orthogonal to the idea behind the test.

**Comment by jethrogb** [comment]
> I'm not sure how that change got introduced, but it's orthogonal to the idea behind the test.

We should understand this

**Comment by cuviper** [comment]
If the main point is to avoid `ret`, shouldn't there be `CHECK-NOT` somewhere?

**Pull request merged**
