### PR TITLE
Add `-Z hir-stats` for collecting statistics on HIR and AST

### PR DESCRIPTION
**Pull request by michaelwoerister**
The data collected will be printed to the commandline and looks like the following:

```
// stats for libcore

PRE EXPANSION AST STATS

Name                Accumulated Size         Count     Item Size
----------------------------------------------------------------
TypeBinding                    2_280            57            40
Mod                            3_560            89            40
PathListItem                   6_516           181            36
Variant                        7_872            82            96
LifetimeDef                   21_280           380            56
StructField                   22_880           260            88
Lifetime                      23_800         1_190            20
Local                         30_192           629            48
ForeignItem                   31_504           179           176
Arm                           42_880           670            64
Mac                           46_960           587            80
FnDecl                        57_792         1_204            48
TraitItem                     69_504           362           192
TyParamBound                  98_280           945           104
Block                        108_384         2_258            48
Stmt                         144_720         3_618            40
ImplItem                     230_272         1_028           224
Item                         467_456         1_826           256
Pat                          517_776         4_623           112
Attribute                    745_680        15_535            48
Ty                         1_114_848         9_954           112
PathSegment                1_218_528        16_924            72
Expr                       3_082_408        20_279           152
----------------------------------------------------------------
Total                      8_095_372


POST EXPANSION AST STATS

Name                Accumulated Size         Count     Item Size
----------------------------------------------------------------
MacroDef                       1_056            12            88
Mod                            3_400            85            40
TypeBinding                    4_280           107            40
PathListItem                   6_516           181            36
Variant                        7_872            82            96
StructField                   24_904           283            88
ForeignItem                   31_504           179           176
TraitItem                     69_504           362           192
Local                         85_008         1_771            48
Arm                          100_288         1_567            64
Lifetime                     123_980         6_199            20
LifetimeDef                  126_728         2_263            56
TyParamBound                 297_128         2_857           104
FnDecl                       305_856         6_372            48
Block                        481_104        10_023            48
Stmt                         535_120        13_378            40
Item                       1_469_952         5_742           256
Attribute                  1_629_840        33_955            48
ImplItem                   1_732_864         7_736           224
Pat                        2_360_176        21_073           112
PathSegment                5_888_448        81_784            72
Ty                         6_237_168        55_689           112
Expr                      12_013_320        79_035           152
----------------------------------------------------------------
Total                     33_536_016


HIR STATS

Name                Accumulated Size         Count     Item Size
----------------------------------------------------------------
MacroDef                         864            12            72
Mod                            2_720            85            32
TypeBinding                    3_424           107            32
PathListItem                   5_068           181            28
Variant                        6_560            82            80
StructField                   20_376           283            72
ForeignItem                   27_208           179           152
WherePredicate                43_776           684            64
TraitItem                     52_128           362           144
Decl                          68_992         2_156            32
Local                         89_184         1_858            48
Arm                           94_368         1_966            48
LifetimeDef                  108_624         2_263            48
Lifetime                     123_980         6_199            20
Stmt                         168_000         4_200            40
TyParamBound                 251_416         2_857            88
FnDecl                       254_880         6_372            40
Block                        583_968        12_166            48
Item                       1_240_272         5_742           216
ImplItem                   1_361_536         7_736           176
Attribute                  1_620_480        33_760            48
Pat                        2_073_120        21_595            96
Path                       2_385_856        74_558            32
Ty                         4_455_040        55_688            80
PathSegment                5_587_904        87_311            64
Expr                       7_588_992        79_052            96
----------------------------------------------------------------
Total                     28_218_736
```

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 

NIce!

**Comment by nnethercote** [comment]
A number of types (e.g. `Expr`, `Ty`, `Lifetime`, possibly more) exist in both `ast` and `hir`. The "item size" column suggests that the first two tables are for the `ast` types and the third table is for the `hir` types, but I'm not certain about that. Explicit module qualification would help a lot :)

**Comment by Mark-Simulacrum** [comment]
Can you clarify what the sizes are in? I assume bytes?

**Comment by michaelwoerister** [comment]
@nnethercote, @Mark-Simulacrum: I'm not sure if I break the rollup if I r- now. I'll make the suggested improvements in another PR.

**Comment by nnethercote** [comment]
Another question: are you just measuring `hir::Expr` instances themselves? Tuples and arrays (and probably other variants) contain a `HirVec<P<Expr>>` -- is the space required for the `HirVec` elements measured?

**Comment by michaelwoerister** [comment]
Yes, that is taken care of by the HIR visitor which recurses into these elements.

**Comment by nnethercote** [comment]
Sorry, I didn't make my question clear. `HirVec<P<Expr>>` is a typedef for `P<[P<Expr>]>`. Are you measuring the slice of `P`s as well as all the `Expr`s?

**Comment by michaelwoerister** [comment]
Nope, for a HirVec<P<Expr>> the space occupied by the pointers in the vec is not measured in this version.

**Pull request merged**
