### PR TITLE
Bump 'src/doc/book' git submodule.

### PR DESCRIPTION
**Pull request by frewsxcv**
Primarily to pick up this change:

https://github.com/rust-lang/book/pull/866

...to move this PR forward:

https://github.com/rust-lang/rust/pull/43641

### CODE REVIEW

**Comment by kennytm** [comment]
I don't think this PR will pass.

```
[00:04:05] tidy error: /checkout/src/doc/book/second-edition/tools/src/bin/convert_quotes.rs:48: line longer than 100 chars
[00:04:05] tidy error: /checkout/src/doc/book/second-edition/tools/src/bin/convert_quotes.rs:56: line longer than 100 chars
[00:04:05] tidy error: /checkout/src/doc/book/second-edition/tools/src/bin/convert_quotes.rs: incorrect license
[00:04:05] some tidy checks failed
```

**Comment by frewsxcv** [comment]
Waiting on https://github.com/rust-lang/book/pull/868

**Comment by frewsxcv** [comment]
Thanks for bumping. Haven't been at my computer for a while

**Comment by carols10cents** [comment]
Sorry I wasn't at my computer for a while to merge the 2nd fix :)

**Pull request closed without merging**
