### PR TITLE
Error on Reserved Syntax for Raw Keywords: `k#foo`

### PR DESCRIPTION
**Pull request by Julian-Wollersberger**
This PR makes the raw keyword syntax from rust-lang/rfcs#3098 a hard error on all editions. (In contrast to what the RFC currently says.)

```
error: raw keyword syntax is reserved for future use
   |
LL |     one_token!(k#ident);
   |                ^^^^^^^ help: insert a whitespace: `k #ident`
```

More specifically, it becomes a tokenization error, so macros cannot use it. `k#ident` is now lexed as one token, similar to `r#ident`, although this could be changed later without breaking anything. 

Note that this is a breaking change, since macros previously interpreted it as three tokens, so something like `quote!{ #k#other_variable }` was valid. The [crater run](https://github.com/rust-lang/rust/pull/84037#issuecomment-830840063) showed no real regressions though.  You can easily get the old behavior by inserting a whitespace between `k` and `#`. 

The actual raw keywords feature for things like `k#async` is _not_ implemented here.

Previously, this PR was inteded to do a crater run for all reserved prefixes from  rust-lang/rfcs#3101, but even the try build ran into breakage in the ecosystem, so only `k#...` was tested.

### CODE REVIEW

**Comment by Julian-Wollersberger** [comment]
I fixed the build errors in rustdoc, but the try build already ran into breakage in the ecosystem. The crate [tracing-attributes](https://github.com/tokio-rs/tracing/blob/a75c7b268ccc40b3906a2d0fcda182603fbc299d/tracing-attributes/src/lib.rs#L805) contains:
```
quote! {
    #name = #kind#value
}
```
Instances like this one should be somewhat common with the `quote!` macro.

What's the best way forward here? Should I just leave the error for raw keywords `k#foo` and remove the others? Or try to fix `tracing-attributes`? 
AFAIK, only the raw keywords syntax was considered to use in older editions anyway.

**Comment by joshtriplett** [comment]
Yeah, let's prioritize getting a crater run that *just* checks if we can use `k#keyword` in every edition.

**Comment by Julian-Wollersberger** [comment]
Ok, I removed the other errors and updated the PR description. 
@joshtriplett can you start another try run?

**Comment by joshtriplett** [comment]
Looks like one test failed due to the change in lexer structures. Can you fix that up, please?

**Comment by Julian-Wollersberger** [comment]
Done. But the try build had succeeded anyway.

**Comment by joshtriplett** [comment]
@craterbot check

**Comment by joshtriplett** [comment]
@craterbot check

**Comment by joshtriplett** [comment]
I reviewed the crater results, and it looks like zero failures as a result of the `k#foo` reservation. So, I think we can safely reserve `k#foo` in all editions.

**Comment by Julian-Wollersberger** [comment]
I'll update this PR to more accurately implement the `k#ident` proposal, in the next week or so.

@rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by Julian-Wollersberger** [comment]
@petrochenkov this is ready for review now, and I guess also for lang team discussion. I also updated the PR description. 
I redid the lexer changes, so it should accurately reflect the RFC. In essence, it does the same thing as `r#ident` now. 

@scottmcm can you verify that this is what you had in mind in the RFC?

@rustbot label: +S-waiting-on-review -S-waiting-on-author

**Comment by petrochenkov** [comment]
@Julian-Wollersberger 
Could you cooperate with @lrh2000 (#85359) and decide who is implementing what?
I didn't look at the changes in detail yet but these PRs appear to compete with each other.

**Comment by crlf0710** [comment]
Blocked on #85359 according to https://github.com/rust-lang/rust/pull/85359#issuecomment-843365985

**Comment by Julian-Wollersberger** [comment]
This is still blocked on the RFC 3098, but work on that seems to have stalled.
I'll close this PR for now, but please ping me if the RFC is merged. I'm still interested in implementing it.

**Pull request closed without merging**
