### PR TITLE
Derive Hash for ThreadId + better example

### PR DESCRIPTION
**Pull request by sagebind**
Derive `Hash` for `ThreadId` (see comments in #21507). Useful for making maps based on thread, e.g. `HashMap<ThreadId, ?>`. Also update example code for thread IDs to be more useful.

### CODE REVIEW

**Comment by sfackler** [comment]
Looks like the doctests are failing:

```
failures:
[01:02:27] 
[01:02:27] ---- thread/mod.rs - thread::Thread::id (line 791) stdout ----
[01:02:27] 	error: no method named `unwrap` found for type `std::thread::JoinHandle<std::thread::ThreadId>` in the current scope
[01:02:27]   --> <anon>:10:4
[01:02:27]    |
[01:02:27] 10 | }).unwrap();
[01:02:27]    |    ^^^^^^
[01:02:27] 
[01:02:27] error: aborting due to previous error(s)
[01:02:27] 
[01:02:27] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203
[01:02:27] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:02:27] 
[01:02:27] ---- thread/mod.rs - thread::ThreadId (line 660) stdout ----
[01:02:27] 	error: no method named `unwrap` found for type `std::thread::JoinHandle<std::thread::ThreadId>` in the current scope
[01:02:27]   --> <anon>:10:4
[01:02:27]    |
[01:02:27] 10 | }).unwrap();
[01:02:27]    |    ^^^^^^
[01:02:27] 
[01:02:27] error: aborting due to previous error(s)
[01:02:27] 
[01:02:27] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203
[01:02:27] 
[01:02:27] 
[01:02:27] failures:
[01:02:27]     thread/mod.rs - thread::Thread::id (line 791)
[01:02:27]     thread/mod.rs - thread::ThreadId (line 660)
[01:02:27] 
[01:02:27] test result: FAILED. 776 passed; 2 failed; 22 ignored; 0 measured
[01:02:27] 
[01:02:27] error: test failed
```

Could you add `Debug` into the derive list while you're in there?

**Comment by nrc** [comment]
> Could you add Debug into the derive list while you're in there?

Note that there is already a `Debug` impl, it just prints `ThreadId { .. }` rather than the more useful, obvious solution. If we do want to derive `Debug`, then we would need to remove the explicit impl.

**Comment by sfackler** [comment]
Oh, that's weird. I have no problem with a derived implementation that actually shows the value.

**Comment by sagebind** [comment]
I think we originally did not derive `Debug` because we did not want to expose the actual value in any way, even for debugging. I see no issue with displaying it though, for debugging purposes anyway.

**Comment by alexcrichton** [comment]
Yeah hiding the value from the `Debug` impl seems like it's trying to hard to me, I'd also expect `#[derive(Debug)]` here (and would be ok with it)

**Comment by nrc** [comment]
> hiding the value from the Debug impl seems like it's trying to hard to me

it is irritating but also useless - you can always just transmute

**Comment by sfackler** [comment]
You monster!

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by frewsxcv** [comment]
I don't remember why I tagged this `T-doc`, but here's my checkmark anyways.

**Comment by sagebind** [comment]
@frewsxcv Perhaps because the example code is updated for the `ThreadId` type?

**Comment by peschkaj** [comment]
Docs look good to me.

**Comment by peschkaj** [comment]
@rfcbot reviewed

**Comment by jonathandturner** [comment]
@rfcbot reviewed

**Comment by GuillaumeGomez** [comment]
@rfcbot reviewed

**Comment by TimNN** [comment]
@bors retry

* #40546

**Comment by TimNN** [comment]
@bors retry

* #40546

**Pull request merged**
