### PR TITLE
Prevent failure in case there is no config.toml file

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by tmiasko** [comment]
This should be already addressed by changes from #73590 with somewhat different approach.

**Comment by GuillaumeGomez** [comment]
Hum... I think both approaches are actually completing each other. I'll fix the format issue.

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by Mark-Simulacrum** [comment]
This patch seems wrong. When bootstrap is passed a filename, we expect that said file exists (and is valid TOML); we should not ignore errors. I believe it can be closed, but I'll leave that to @GuillaumeGomez's discretion.

**Comment by GuillaumeGomez** [comment]
Fine by me! Thanks for the explanation @Mark-Simulacrum.

**Pull request closed without merging**
