### PR TITLE
Set opt-level to 3

### PR DESCRIPTION
**Pull request by Zoxc**
r? @alexcrichton

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
@Zoxc Do you have information on whether the codegen issue has been fixed? Also, you can just remove the profile section to use the default `opt-level=3`.

**Comment by matthiaskrgr** [comment]
previous discussion: https://github.com/rust-lang/rust/pull/48204

**Comment by ishitatsuyuki** [comment]
... try what? The point is Windows which needs AppVeyor.

**Comment by Zoxc** [comment]
The try build is for a perf run.

Locally opt-level=2 passes as many tests as opt-level=3 for me on Windows. I see that the Windows crashes were spurious, so I can try building it a few times.

**Comment by matthiaskrgr** [comment]
Perf results of #48204 http://perf.rust-lang.org/compare.html?start=b1f8e6fb06d7362eeb2065347a7db94e76b1cb2f&end=bd789f974e73497bcb8183e75d270e30ca07fdc3&stat=instructions%3Au

**Comment by Mark-Simulacrum** [comment]
Perf has been queued, but I doubt it'll change much since last time.

**Comment by alexcrichton** [comment]
In the [other PR](https://github.com/rust-lang/rust/pull/50276#discussion_r184625678) it's claimed that LLVM 6 landed in the meantime but the [segfault](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6462/job/g8uxneu8ktd6p30n) on the [previous PR](https://github.com/rust-lang/rust/pull/48204) happened [on a commit](https://github.com/rust-lang/rust/commit/7b6189e16439a5c37c46992d44f363d0c2f63b3b) tagged for our [LLVM 6.0 branch](https://github.com/rust-lang/llvm/commit/9f81beaf32608fbe1fe0f2a82f974e800e9d8c62). 

In that sense it's seems highly unlikely this is fixed?

**Comment by Zoxc** [comment]
Perf results: http://perf.rust-lang.org/compare.html?start=f900bcf35c9ed4b8f911a37df3949f82669b9bd8&end=c692cc25af00b8e958656116efc00c364dfee9a7&stat=instructions%3Au

The wall-time results of the previous run is suspiciously good: http://perf.rust-lang.org/compare.html?start=b1f8e6fb06d7362eeb2065347a7db94e76b1cb2f&end=bd789f974e73497bcb8183e75d270e30ca07fdc3&stat=wall-time

@alexcrichton We updated from a version close to 6 to the actual 6 release, and that fixed at least one bug causing segfaults for me. I've built this locally (with `x.py build`) 6 times and there were no crashes.

**Comment by alexcrichton** [comment]
Ok if LLVM fixes landed in the meantime let's see how this pans out on CI

@bors: r+

**Review by ishitatsuyuki — DISMISSED** [review]
Please removed the now obsolete profile section along with the comments, as I commented above.

**Comment by alexcrichton** [comment]
I feel like I've been seeing a lot of segfaults on Windows CI in the last few days which may be a result of this change. @kennytm do you think you've seen an uptick in Windows segfaults over the past few days?

**Comment by alexcrichton** [comment]
Despite [instruction counts](https://perf.rust-lang.org/compare.html?start=c1168be5360f17516b233be85ebb193bb4e612bf&end=5f3994f58f41818bf31efeda6af41e8060978ca5&stat=instructions%3Au) being pretty green across the board this PR interestingly [relatively severly regressed wall time](https://perf.rust-lang.org/compare.html?start=c1168be5360f17516b233be85ebb193bb4e612bf&end=5f3994f58f41818bf31efeda6af41e8060978ca5&stat=wall-time) in a number of benchmarks, mostly related to NLL

**Pull request merged**
