### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by alexcrichton**
- Successful merges: #40347, #40501, #40516, #40524, #40540, #40642, #40683, #40764, #40778, #40807, #40809
- Failed merges: #40771

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

Let's see if that's spurious...

**Comment by arielb1** [comment]
Previous failure is:
```

[00:51:00] error: unable to get packages from source
[00:51:00] 
[00:51:00] Caused by:
[00:51:00]   failed to parse manifest at `/cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.7/Cargo.toml`
[00:51:00] 
[00:51:00] Caused by:
[00:51:00]   could not parse input as TOML
[00:51:00] 
[00:51:00] Caused by:
```

**Comment by arielb1** [comment]
Same failure:
```
[00:51:03] error: unable to get packages from source

[00:51:03] 

[00:51:03] Caused by:

[00:51:03]   failed to parse manifest at `/cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.7/Cargo.toml`

[00:51:03] 

[00:51:03] Caused by:

[00:51:03]   could not parse input as TOML

[00:51:03] 

[00:51:03] Caused by:

[00:51:03]   expected newline, found an identifier at line 14

[00:51:03] thread 'main' panicked at 'tests failed for https://github.com/iron/iron', /checkout/src/tools/cargotest/main.rs:98
```

Cargo problem?

**Pull request closed without merging**
