### PR TITLE
Add JoinError that fails Span::join when hygiene is different.

### PR DESCRIPTION
**Pull request by futursolo**
Currently, Span::join has an undefined behaviour when 2 spans are from a different hygiene, this pull request makes Span::join to return a JoinError that fails Span::join when hygiene is different.

See: https://github.com/rust-lang/rust/issues/54725#issuecomment-649078500

### CODE REVIEW

**Comment by futursolo** [comment]
This change is expected to break `proc_macro2`.

I am not sure if `Option<Span>` should be for both errors to keep a compatible API, or make this a result where it can provide more precise error information.

**Comment by jhpratt** [comment]
Honestly, breaking `proc_macro2` is their problem. They could easily patch over it by doing `.ok()` on the result. It's not the same API, but that's what you get for mirroring an unstable API in a stable manner.

Personally I think this would be a great change, as it should presumably lead to stabilization of `Span::join` with relative ease.

**Comment by m-ou-se** [comment]
We discussed this in a recent libs-api meeting, and we're not convinced we should apply this change. This function is often used for diagnostics, where hygiene plays a lesser or no role. Returning an error instead of a joined token will lead to worse diagnostics. In general, in many cases it seems preferrable to continue with the hygiene of one of the two tokens instead of breaking, since that matches the behaviour of rustc itself. E.g. a path like `::a::b` where every token has a different hygiene will still compile, end will end up using the hygiene of one of those tokens. Maybe we could document some guarantee of which of the tokens will be used for hygiene, but in the compiler itself that's currently not well defined and depends on the situation.

**Review by dtolnay — COMMENTED** [review]
As Mara wrote, joining spans with different hygiene to produce diagnostics whose location covers both spans is an important use case of `join` in proc macro error reporting.

Dealing with name resolution in situations that involve different hygiene coming together is not a new problem with `join`. For example a method call like `$a::$b::$c()` already needs to account for there being possibly different traits in scope in each of `$a`'s, `$b`'s, and `$c`'s scope.

If someone needs to be sure that their joined token has some specific name resolution behavior, they should use `Span::join(first, second).resolved_at(wherever)`.

**Pull request closed without merging**
