### PR TITLE
Overloaded augmented assignments (`a += b`)

### PR DESCRIPTION
**Pull request by japaric**
Implements overload-able augmented/compound assignments, like `a += b` via the `AddAssign` trait, as specified in RFC [953](https://github.com/rust-lang/rfcs/blob/master/text/0953-op-assign.md)

r? @nikomatsakis

### CODE REVIEW

**Comment by japaric** [comment]
RFC at rust-lang/rfcs#953

**Comment by japaric** [comment]
(If anyone is looking, I've added the `op_assign` feature gate)

**Comment by BigBoneDaddy** [comment]
@japaric @bors How are docs coming along?

**Comment by Gankro** [comment]
@japaric I'm gonna go ahead and close this PR since it doesn't look like this is going to get through the RFC process anytime soon.

Your contributions, as always, are greatly appreciated!

**Comment by japaric** [comment]
Rebased, documented the traits and updated the description of E0368.

r? @nikomatsakis

**Comment by Gankro** [comment]
@japaric github seems to refuse to reopen this, might need a new PR?

**Comment by japaric** [comment]
@Gankro just sent #28345

**Pull request closed without merging**
