### PR TITLE
Add explanatory note to `bare_urls` lint

### PR DESCRIPTION
**Pull request by camelid**
I think the lint is confusing otherwise since it doesn't fully explain
what the problem is.

### CODE REVIEW

**Comment by camelid** [comment]
Spurious CI failure, retrying jobs.

**Comment by camelid** [comment]
(Note that the lint is not called `bare_urls` yet, but will be soon: #81764)

**Comment by jyn514** [comment]
I don't think this change makes sense to land before #81764. This error makes no sense:

```
error: unneeded long form for URL
  --> $DIR/url-improvements.rs:5:5
   |
LL | /// [http://bb.com]
   |     ^^^^^^^^^^^^^^^ help: use an automatic link instead: `<http://bb.com>`
   |
   = note: bare URLs are not automatically turned into clickable links
```

**Comment by camelid** [comment]
Ah, good point. I'll mark this is as blocked on that PR.

**Comment by jyn514** [comment]
r=me with CI passing

**Review by Thaddeus5555555 — APPROVED** [review]

**Pull request merged**
