### PR TITLE
Rollup of 30 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #34319, #34894, #35041, #35042, #35076, #35109, #35137, #35175, #35181, #35182, #35189, #35239, #35264, #35266, #35281, #35285, #35289, #35291, #35294, #35296, #35297, #35298, #35299, #35318, #35319, #35324, #35326, #35328, #35331
- Failed merges:

### CODE REVIEW

**Comment by TimNN** [comment]
@GuillaumeGomez #35298 fails tidy

**Comment by GuillaumeGomez** [comment]
@TimNN: @jonathandturner said it to me so recreated the PR.

@bors: r+ p=1

**Comment by TimNN** [comment]
@GuillaumeGomez #35289 as well.

**Comment by jonathandturner** [comment]
@TimNN - what about #35289?  It passed Travis (I think?)

**Pull request closed without merging**
