### PR TITLE
Fix up @carols10cents' mailmap entry

### PR DESCRIPTION
**Pull request by steveklabnik**
The previous ways didn't work; this does.

cc rust-lang-nursery/thanks#45

### CODE REVIEW

**Comment by est31** [comment]
I don't think this will work. According to the [manual page](https://git-scm.com/docs/git-shortlog#_mapping_authors) one person should always have one line, with the preffered name and email at the start, and any other (or previous) names and emails following in the same line. Also, if somebody used the same email but a different name, it counts as different person, so it needs to be inside the line as well.

Deleting a name from the mailmap won't help, as the name is still mentioned in the git history of rustc.

**Comment by est31** [comment]
Mhh, testing `git shortlog -sn` seems to confirm that nothing bad happened. IDK then.

**Comment by steveklabnik** [comment]
I checked this locally; before this change, both her names are in there, afterwards, there's only one.

I share your confusion about the man page.

**Pull request merged**
