### PR TITLE
Make search path debugging info! for easier debugging

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hmm. I have no particular objection to this, but I do wonder about the "stability" of said messages. Perhaps we want some explicit text stating that we make no promises here?

cc @eddyb -- seems related to things we were discussing before about compiler's debug logs though =)

**Comment by eddyb** [comment]
We need to change the builtin log crate to use `RUSTC_LOG` instead of `RUST_LOG` before we add more of these - maybe it can be done in `rustc_driver` specifically.

**Comment by nikomatsakis** [comment]
@eddyb 

> We need to change the builtin log crate to use `RUSTC_LOG` instead of `RUST_LOG` before we add more of these - maybe it can be done in `rustc_driver` specifically.

I think I agree. I have no idea how to do this though. :)

**Comment by nikomatsakis** [comment]
@Zoxc 

For context, @eddyb has been pointing out that if you do `RUST_LOG=... cargo run`, changes are that you intend to this `RUST_LOG` to apply to program you are running, not the compiler. For now, since the majority of logs are debug and compiled out, this isn't much of an issue, but if we're going to expand infos -- and in particular if we're going to expand to include infos that are targeting end-users -- this becomes a bigger concern. Especially since it could become part of a de facto stable interface; I know that I myself never considered the possibility that people would rely on the `RUST_LOG` behavior of rustc until recently. Anyway, TL;DR is that at minimum we'd rather change to `RUSTC_LOG` before we add any more output into `rustc`. Would you be up for pursuing such a patch?

**Comment by nikomatsakis** [comment]
OK, I'm going to close this PR in light of @eddyb's comment in any case. @Zoxc let me know if you're up to rename `RUST_LOG` =)

**Pull request closed without merging**
