### PR TITLE
Remove unnessary comment for alloc Splice

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by hanna-kruppe** [comment]
I believe this comment is standard for this kind of type (see e.g., all the iterator adapters in `std::iter`) and intended to make clear the link should be followed for full documentation. If you strongly believe it should be removed, I suggest removing it everywhere for consistency, but I neither agree nor would I feel qualified to approve such a sweeping documentation style change even if I did agree.

**Comment by pickfire** [comment]
> I believe this comment is standard for this kind of type (see e.g., all the iterator adapters in std::iter) and intended to make clear the link should be followed for full documentation. If you strongly believe it should be removed, I suggest removing it everywhere for consistency, but I neither agree nor would I feel qualified to approve such a sweeping documentation style change even if I did agree.

I checked other similar type in the file but it is not there.

```rust
/// A draining iterator for `Vec<T>`.
///
/// This `struct` is created by the [`drain`] method on [`Vec`].
///
/// [`drain`]: struct.Vec.html#method.drain
/// [`Vec`]: struct.Vec.html
#[stable(feature = "drain", since = "1.6.0")]
pub struct Drain<'a, T: 'a> {
    /// Index of tail to preserve
    tail_start: usize,
    /// Length of tail
    tail_len: usize,
    /// Current remaining range to remove
    iter: slice::Iter<'a, T>,
    vec: NonNull<Vec<T>>,
}
```
I just followed what `Drain` did since there is a grammatical error here.

**Comment by hanna-kruppe** [comment]
I don't see any grammatical error, and given the precedent in std::iter and other modules and Drain-like types (e.g. `string::Drain` and `collections::vec_deque::Drain`), I still believe the consistent thing would be to add the same sentence to `vec::Drain`, not remove it elsewhere.

**Comment by pickfire** [comment]
But they still have the same issue. "See its documentation for more.". It's sort of hanging in the middle, maybe I change the sentence?

**Comment by Dylan-DPC** [comment]
Thanks @pickfire for the contribution, but there seems to be no consensus in merging this and also the original way is how it is present in multiple places, so merging this would make it look inconsistent. I'm closing this pr, but if you wish you can open a new one later.

**Pull request closed without merging**
