### PR TITLE
Print PID holding bootstrap build lock on Linux

### PR DESCRIPTION
**Pull request by clubby789**
Partially address #107077

Parse `/proc/locks` to find the PID of the process which created the build directory lock

### CODE REVIEW

**Comment by albertlarsan68** [comment]
What are the stability guarantees on the format of the `/proc/locks` file ?

**Comment by clubby789** [comment]
I don't know about Linux's stability guarentees here. `lslocks` would probably be better but I'm not sure if it can be relied upon to be installed, if most distros ship with it by default.

**Comment by the8472** [comment]
> What are the stability guarantees on the format of the /proc/locks file ?

The linux proc filesystem is treated as part of the kernel API and kept backwards-compatible since a lot of tools rely on parsing it since is the sole source of that information.
If you strace `lslocks` you'll see that it uses `/proc/locks` under the hood.

**Comment by albertlarsan68** [comment]
So there is no problem merging that ?
Cc @jyn514

**Comment by jyn514** [comment]
Seems reasonable, yeah. I'll leave it up to Mark though.

**Comment by albertlarsan68** [comment]
Thanks for the PR!
@bors r+
r? @albertlarsan68

**Comment by clubby789** [comment]
Failed in rollup due to cfg-related warnings, should be fixed now

**Pull request merged**
