### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by RalfJung**
Successful merges:

 - #71321 (Use min_specialization in liballoc)
 - #71665 (Miri interning: replace ICEs by proper errors)
 - #71809 (Use `LocalDefId` in `DumpVisitor::nest_tables`)
 - #71872 (Be less aggressive with `DroplessArena`/`TypedArena` growth.)
 - #71910 (Fix unused_parens false positive when using binary operations)
 - #71919 (Update transitive dependency to work towards removing syn <1.0 dep)
 - #72045 (Incomplete features can also be unsound)
 - #72191 (Clean up E0589 explanation)
 - #72194 (Don't ICE on missing `Unsize` impl)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
@Dylan-DPC Yes looks like we did race.^^

Are you on Zulip? Might be worth having a rollup coordination channel somewhere or so. (Or I can also stop doing rollups -- I just want to help.)

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/72202.

**Comment by RalfJung** [comment]
In particular I am wondering how you are deciding which PRs to include. I take all the ones marked rollup=always, plus the first N in the queue (with N picked somehow at a whim and depending on how big the queue is), but excluding those where PR CI has not passed (yet). This ensures queue fairness. You are using some other policy and I do not know which one that is, so maybe I should adjust mine.

**Comment by Dylan-DPC** [comment]
We don't have a policy as such. I got through the queue and pick the ones I predict won't conflict and are safe to rollup and are small enough. Also generally giving priority to ones which are in the queue for a long time, or prs created long back. 

I appreciate the help. I used to end up in "rollup races" with centril as well. The trick to avoid a race is to wait for a minutes and check if there's a rollup or not. I'm generally active in the evening slot (evening in CEST) so you can expect me to rollup at that time more often that in the mornings :) Don't worry about adjusting any policy, just do whatever suits you :)

**Pull request closed without merging**
