### PR TITLE
Add i686-unknown-netbsd target

### PR DESCRIPTION
**Pull request by jakllsch**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Out of curiosity, why is this "netbsdelf" while the other targets are "netbsd" ?

**Comment by jakllsch** [comment]
The oldest NetBSD ports once used a.out as the executable/object format and were (and those old versions still are) known as "netbsd" in the GNU triple.  These ports eventually switched to ELF, becoming "netbsdelf".  NetBSD ports that never were a.out are known as "netbsd".

NetBSD's src/share/mk/bsd.own.mk has the list of these ports (line 844 in rev 1.1002).  Of these, 32-bit SPARC, and 32-bit ARM are notable as already being supported by LLVM and Rust (but not yet on NetBSD).

Some NetBSD developers have expressed to me that they believe these triples are the dominion of the GNU toolchain. Thus, except for compatibility with the GNU and LLVM toolchains, there may be no need to maintain this historical reasoning in Rust.

**Comment by alexcrichton** [comment]
Ok perhaps we can stick with "netbsd" in that case? It seems unlike that we'll add an "a.out" target, and if we do seems like we'd want it to be the non-default naming

**Comment by jakllsch** [comment]
GitHub will probably remind us anyway, but I'll need to drop `mk/cfg/i686-unknown-netbsd.mk` after #39431 is merged.

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault #38878

**Pull request merged**
