### PR TITLE
Add --emit metadata

### PR DESCRIPTION
**Pull request by nrc**
With the same semantics as -Zno-trans

cc @rust-lang/compiler @rust-lang/tools 

r? @alexcrichton

### CODE REVIEW

**Review by eddyb — APPROVED** [review]
LGTM

**Comment by alexcrichton** [comment]
This isn't quite what I personally had in mind for this flag, but rather something like:

* The compiler recognizes `--emit metadata`
* The produces a new artifact, like `crate-name.rmeta`
* The compiler can load `.rmeta` files like it can rlibs
* When the compiler resolves `extern crate foo`, it prioritizes `libfoo.rlib` but works with `foo.rmeta`
* When linking, if we don't have rlibs for everything (e.g. some are just metadata), we print a nice error

I feel like we definitely want a separate artifact here to avoid the compiler getting confused with "rlibs with code" and "rlibs with only metadata", and it'd also help build systems and such as it wouldn't all generate to the same file.

**Comment by nrc** [comment]
@alexcrichton that is a much bigger change, I'd want to be sure there was a big benefit to this. ISTM that we can get a lot of that benefit from just building into a different directory (e.g., Cargo could have a check directory in addition to release and debug). I had hoped we could keep a strict separation between code and metadata libs without having to rely on the file type.

**Comment by alexcrichton** [comment]
It is indeed a much bigger change, yeah. I do agree that the implementation of `cargo check` will likely not change all that much, but as a *stable* flag to the compiler we need to consider more consumers than just Cargo itself.

@brson will also likely have opinions on this as well!

**Comment by nikomatsakis** [comment]
I also assumed (and would expect) a design like the one that @alexcrichton proposed. It is certainly a somewhat bigger change -- but not that much, right?

**Comment by nrc** [comment]
ping @brson - thoughts?

**Comment by nrc** [comment]
Closing in favour of https://github.com/rust-lang/rust/pull/37681

**Pull request closed without merging**
