### PR TITLE
Do not consider repeated lifetime params for elision.

### LINKED ISSUE #103330: function lifetime elision changed in 1.64
[I tried this code:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=02637fdcea99e2fb9593e41df6cc3475)

```rust
fn foo<'a>(_: &'a str, _: &'a str) -> &str { "" }
```

[I expected to see this happen:](https://rust.godbolt.org/z/oK3o15oxG)
```rust
error[E0106]: missing lifetime specifier
 --> <source>:1:39
  |
1 | fn foo<'a>(_: &'a str, _: &'a str) -> &str { "" }
  |               -------     -------     ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from argument 1 or argument 2
help: consider using the `'a` lifetime
  |
1 | fn foo<'a>(_: &'a str, _: &'a str) -> &'a str { "" }
  |                                       ~~~

error: aborting due to previous error
```
Instead, this happened: Successful compilation

### Meta

Tested on the playground, all versions and editions.
* Stable channel: 1.64.0
* Beta channel: 1.65.0-beta.3 (2022-10-10 da7ffa2d1df2daf747b8)
* Nightly channel: 1.66.0-nightly (2022-10-19 4b8f4319954ff2642690)

### Notes

I'm labeling this as a regression as I believe it is severe enough of an unplanned change (at best an accidental stabilization?) that I should draw attention to it, even though I haven't found a way to cause miscompilation for example.  I also have not tried to do so at all yet.

@rustbot label +T-compiler +A-lifetimes +regression-from-stable-to-stable

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/103330

### CODE REVIEW

**Comment by inquisitivecrystal** [comment]
I'm nominating this as a fix to an accidental major change in how we handle lifetimes. It's possible that we may want to implement the change deliberately, since it matches the reference, but it needs a lang FCP at minimum. See also issue #103330 and [this Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23103330.20function.20lifeitme.20elision.20changed.20in.201.2E64/near/305268674).

**Comment by Mark-Simulacrum** [comment]
@bors try

Let's get a build for a crater run.

**Comment by compiler-errors** [comment]
This needs a crater run -- will start one in 2.5 hours when the try-build is over.

**Review by compiler-errors — APPROVED** [review]
This was discussed in the T-lang triage meeting today. The implementation makes sense to me. r=me unless you want a review from oli specifically.

**Comment by Mark-Simulacrum** [comment]
Looks like this breaks clippy - can someone push a fix and rerun try build? I can try to do that later today if not, but would love to get crater kicked off soon.

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by cjgillot** [comment]
Crater breakage found some cases in which this PR is stricter than what stable has. I need to work on this a bit more.

**Comment by inquisitivecrystal** [comment]
> Crater breakage found some cases in which this PR is stricter than what stable has. I need to work on this a bit more.

Isn't that expected? The regression was stable to stable, so I think that should be the correct behavior (as in, we're disallowing things that were allowed on the latest stable). I'd think the problem would be messaging for the change, whether we need to do a future incompatibility message rather than jumping to forbidding it, and so on.

**Comment by inquisitivecrystal** [comment]
I'm going to nominate this. `T-compiler` can skip it if there's nothing to discuss, but I think the best way to handle a change for backwards compatibility is a compiler matter? I'm mostly doing this because the meeting is coming up, and we're super close to release, so it's better for the team to look at it now if they want to than not to have the opportunity to. But anyone should feel free to yank the nomination.

**Comment by jackh726** [comment]
Just quickly skimming a couple of the crater reports, seemingly what's breaking is when we have the same lifetime multiple times in a single argument.

**Comment by inquisitivecrystal** [comment]
> Just quickly skimming a couple of the crater reports, seemingly what's breaking is when we have the same lifetime multiple times in a single argument.

Okay, in that case it probably *isn't* expected breakage. Should I yank the nomination?

**Comment by jackh726** [comment]
Here are both relevant cases in a test: https://rust.godbolt.org/z/4dnKovqnn
In 1.63, `foo` does not compile, but `bar` does. I think in this PR, both don't.

Indeed, the crater run has unexpected breakage.

I don't think nomination is *needed*, but can't hurt.

**Comment by inquisitivecrystal** [comment]
> I don't think nomination is _needed_, but can't hurt.

Thanks. I'm glad to have an outsider opinion. In that case, I'll leave it. At the very least, having T-compiler be aware of the current state of this can't hurt anything.

**Comment by oli-obk** [comment]
@craterbot check

**Comment by apiraino** [comment]
Are the backports to beta+stable actually agreed or some changes are needed to this PR before that?

(sorry I'm slightly confused -> some bits from T-compiler [Zulip meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-10-27/near/306470870))

**Comment by cjgillot** [comment]
Only 2 regressing crates: urbas/rix and divert-0.4.0.  Both are using the feature we are de-stabilising here.
The other failures are spurious.

**Comment by Mark-Simulacrum** [comment]
Real regressions:

* https://crater-reports.s3.amazonaws.com/pr-103450-1/try%23742889a08e10036dc30b8a7308f2a2a15b706883/gh/urbas.rix/log.txt (cc @urbas)
* https://crater-reports.s3.amazonaws.com/pr-103450-1/try%23742889a08e10036dc30b8a7308f2a2a15b706883/reg/divert-0.4.0/log.txt (cc @0xFounders)

Others are spurious.

I think given proximity to release and relatively minimal breakage I'm going to go ahead and approve the PR. We'll mention this in the release notes as well.

@bors r+ p=10

**Pull request merged**
