### PR TITLE
Vec: looks like is_empty and len are not needed

### PR DESCRIPTION
**Pull request by tshepang**
The slice module already implements these methods

### CODE REVIEW

**Comment by tshepang** [comment]
This is something of a question: does my change break anything? I ran all tests on an amd64 machine without issues.

**Comment by Gankro** [comment]
No this seems totally legit (although it probably forced the optimizer do a bit more work on these methods...).

**Comment by petrochenkov** [comment]
I will break code using `Vec::len` or `Vec::is_empty` as function objects:
```
fn main() {
    let vecs = vec![vec![1], vec![1, 2], vec![1, 2, 3]];
    for len in vecs.iter().map(Vec::len) { // <- No autoderef happens here, len is not found
        println!("{}", len);
    }
}
```

**Comment by Gankro** [comment]
Woah! I didn't realize we had implemented that!

**Comment by Gankro** [comment]
@bors r-

Want to think about this then

On Sat, Jul 11, 2015 at 7:00 PM, Alexis Beingessner <a.beingessner@gmail.com
> wrote:

> Woah! I didn't realize we had implemented that!
>
> On Sat, Jul 11, 2015 at 6:47 PM, Vadim Petrochenkov <

**Comment by reem** [comment]
Seems we just cannot do this.

**Comment by tshepang** [comment]
Does this mean the test is incomplete @petrochenkov?

**Comment by retep998** [comment]
@tshepang The test suite is always incomplete. There are numerous ways to cause breaking changes in Rust without tripping the test suite. That's why PRs are manually reviewed and brson does crater runs on occasion to see if anything on crates.io broke.

**Comment by nagisa** [comment]
You can’t just remove these methods without deprecating them either. I’d propose deprecation of these two functions as an RFC.

**Comment by Gankro** [comment]
This super isn't worth it. They're two stupid little functions that have 0 maintenance burden.

Thanks anyway, @tshepang!

**Comment by tshepang** [comment]
@nagisa if they are deprecated, how would one use the non-deprecated ones? Won't the deprecated ones mask those that are not deprecated?

@Gankro do you think these methods are just an oversight?

**Pull request closed without merging**
