### PR TITLE
Update jemalloc to include a fix for startup issues on OSX 10.12

### LINKED ISSUE #140: add tunables for transparent huge page hints
It would be interesting to expose runtime options for setting `MADV_HUGEPAGE` / `MADV_NOHUGEPAGE`. There could be one tunable for normal chunks and another for the chunks used by huge allocations. The tunable would have 3 settings: none (no hint), on and off.

The hints appear take effect on page faults, and since jemalloc always purges the chunks it should be able to get exactly what it wants by setting the hint upon obtaining a chunk (or many chunks for a huge allocation). The overhead of the system call is likely insignificant.

Thanks to the 4M naturally aligned chunks underlying all allocations, jemalloc is very prone to getting transparent huge pages. It screws up purging for normal chunks with metadata and small / large allocations so `MADV_NOHUGEPAGE` would be a good default there. The potential waste for huge allocations is limited (a bit under 2M) and it seems to result in a significant performance win (*much* cheaper purging / faulting cycle, for one thing), so I think an explicit hint would be worth it.

I including some numbers related to this in #139. It makes purging the chunks when handing them off to be recycled *much* cheaper.

### LINKED ISSUE #34674: rustc(4556,0x7fffcca583c0) malloc: *** malloc_zone_unregister() failed for 0x7fffcca4f548 on OSX 10.12 beta 2
Heads up: Running the rust compiler on OSX 10.12 beta 2 leads to the following error message:
> rustc(4556,0x7fffcca583c0) malloc: *** malloc_zone_unregister() failed for 0x7fffcca4f548

Then the process gets stuck.

This roots from the malloc zone registration code in jemalloc 3, which is shared with Firefox's replace-malloc and causes the same issue on Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1284677)

Filed jemalloc issue: https://github.com/jemalloc/jemalloc/issues/420

### PR DESCRIPTION
**Pull request by glandium**
This fixes jemalloc/jemalloc#140 in the version used by the rust compiler.

Fixes #34674

### CODE REVIEW

**Comment by glandium** [comment]
> Cloning into 'src/jemalloc'...
> fatal: reference is not a tree: e058ca661692a8d01f8cf9d35939dfe3105ce968

Obviously it's not merged yet... this will need a rebuild after it's merged.

**Comment by alexcrichton** [comment]
@bors: r+ 3fd0387eb28d2fe0b4ab1cef054384770f385f12

Thanks @glandium! I can only imagine how fun this must have been to find and fix...

**Comment by alexcrichton** [comment]
Also, nominating for beta as this seems like it's better to get out there sooner rather than later (e.g. 1.11 instead of 1.12)

**Comment by Manishearth** [comment]
fails travis

**Comment by alexcrichton** [comment]
Discussed at libs triage today we decided to accept this for a backport to beta

**Pull request merged**
