### PR TITLE
change fasta and fasta-redux benchmark to Veedrac's implementation

### PR DESCRIPTION
**Pull request by llogiq**
I just removed the num_cpus dependency (because we don't want that in there), using 4 threads instead.

I should add that Veedrac asked me to submit this here in his name.

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

Not sure if there's license things here we should worry about

**Comment by llogiq** [comment]
@Veedrac may have something to say about that.

**Comment by Veedrac** [comment]
Thanks for submitting this.

I'm not totally sure what licensing issue is being mentioned. I wouldn't be concerned if it was accepted as-is, though.

**Comment by llogiq** [comment]
As far as I'm concerned, the implementation makes use of *algorithms* from both wikipedia and other benchmark sources (in different languages). The used algorithms themselves aren't subject to any patents I know of, and AFAIK Veedrac didn't make use of other sources that would have require him to submit to a license. I've prepended the usual headers to both files (and I think Veedrac's comment clarifies his agreement to allowing rust-lang to use his code).

@alexcrichton What other license things should we look out for?

**Comment by alexcrichton** [comment]
I have no specific concerns, I simply do not know what to even look for. @brson is our resident license expert so I'm deferring to him. Everything is probably fine, I just don't want to have to patch anything up after-the-fact.

**Comment by llogiq** [comment]
Good to know. So @brson, do we need to clarify something?

**Pull request merged**
