### PR TITLE
Move Cargo.{toml,lock} to the repository root directory.

### PR DESCRIPTION
**Pull request by eddyb**
This should give us back `src/` in errors, panics and debuginfo, for free.

r? @Mark-Simulacrum @alexcrichton cc @michaelwoerister

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I semi-expect tests to fail for this -- I cannot find the previous attempt at this right now but believe `__CARGO_TEST_ROOT` will be needed for distcheck

**Comment by eddyb** [comment]
Heh, that rustdoc failure shows `src/` is back in!

**Comment by alexcrichton** [comment]
@bors: r+

Heh the only reason this wasn't done to start off with is because it broke things, but I believe things may have progressed since then so let's see what happens!

**Comment by eddyb** [comment]
@Mark-Simulacrum Is that the failure you expected, or something simpler?
Either way, I should run distcheck locally and get it working before trying again.

**Comment by ollie27** [comment]
#47731 was the previous attempt btw.

**Comment by BatmanAoD** [comment]
Ping from triage; upon next ping, the PR will be closed for inactivity, but please feel free to re-open it when you're back!

**Comment by BatmanAoD** [comment]
Ping from triage, @eddyb; if we don't hear from you by next week, the PR will be closed for inactivity, but please feel free to re-open it when you're back!

**Comment by BatmanAoD** [comment]
Waiting for people to return from edition-crunch.

**Comment by eddyb** [comment]
```
error: failed to parse manifest at `/checkout/src/tools/miri/Cargo.toml`

Caused by:
  the cargo feature `default-run` requires a nightly version of Cargo, but this is the `beta` channel
```
I guess this is because `build/` is under `Cargo.toml`.
Looks like `__CARGO_TEST_ROOT` needs to be set to the build dir path.

**Comment by nrc** [comment]
Hmm, so this seems to have broken things. I won't have time to look into it until after edition though

**Comment by eddyb** [comment]
The fix is probably easy, I need to take a look - I suspect the same approach I used for compiletest, cargocheck and distcheck, should apply here.

**Comment by Xanewok** [comment]
https://ci.appveyor.com/project/rust-lang/rust/builds/20492571/job/b1o1sacl8oluwt2q#L9757

```
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"current package believes it's in a workspace when it's not:\ncurrent:   C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t2\\cmd_format_utf16_range\\Cargo.toml\nworkspace: C:\\projects\\rust\\Cargo.toml\n\nthis may be fixable by adding `build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t2\\cmd_format_utf16_range` to the `workspace.members` array of the manifest located at: C:\\projects\\rust\\Cargo.toml","range":{"end":{"character":0,"line":9999},"start":{"character":0,"line":0}},"severity":1}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t2/cmd_format_utf16_range/Cargo.toml"}}
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"current package believes it's in a workspace when it's not:\ncurrent:   C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t0\\dependency_typo\\Cargo.toml\nworkspace: C:\\projects\\rust\\Cargo.toml\n\nthis may be fixable by adding `build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t0\\dependency_typo` to the `workspace.members` array of the manifest located at: C:\\projects\\rust\\Cargo.toml","range":{"end":{"character":0,"line":9999},"start":{"character":0,"line":0}},"severity":1}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t0/dependency_typo/Cargo.toml"}}
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"current package believes it's in a workspace when it's not:\ncurrent:   C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t4\\simple_workspace\\Cargo.toml\nworkspace: C:\\projects\\rust\\Cargo.toml\n\nthis may be fixable by adding `build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t4\\simple_workspace` to the `workspace.members` array of the manifest located at: C:\\projects\\rust\\Cargo.toml","range":{"end":{"character":0,"line":9999},"start":{"character":0,"line":0}},"severity":1}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t4/simple_workspace/Cargo.toml"}}
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"current package believes it's in a workspace when it's not:\ncurrent:   C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t9\\simple_workspace\\Cargo.toml\nworkspace: C:\\projects\\rust\\Cargo.toml\n\nthis may be fixable by adding `build\\x86_64-pc-windows-msvc\\stage2-tools\\x86_64-pc-windows-msvc\\rlsit\\t9\\simple_workspace` to the `workspace.members` array of the manifest located at: C:\\projects\\rust\\Cargo.toml","range":{"end":{"character":0,"line":9999},"start":{"character":0,"line":0}},"severity":1}],"uri":"file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/rlsit/t9/simple_workspace/Cargo.toml"}}

```

**Comment by pietroalbini** [comment]
> I won't have time to look into it until after edition though

Hmm, we need rls to be fixed the week before 1.31 is released though, otherwise we won't be able to land any PR.

**Comment by eddyb** [comment]
Fix is up at https://github.com/rust-lang/rls/pull/1138.

**Pull request merged**
