### PR TITLE
build aarch64-musl host compiler in CI

### LINKED ISSUE #75721: Provide pre-build host compiler for aarch64-unknown-linux-musl
`aarch64-unknown-linux-musl` is currently a tier 2 platform with pre-built libstd, but not pre-built host compiler (`rustc`, `cargo`, etc.) It would be useful to me if the host compiler was available. Specifically it's important to me because pyca/cryptography -- the most widely used Python crypto library -- builds and tests on Alpine Linux, which uses musl. We're currently looking at expanding aarch64 testing in CI, and not needing to special case Alpine aarch64 would be great.

I'm happy to try to work up a PR for this, but there's one thing I'm not positive about: can this be a cross-compilation, the way `aarch64-unknown-linux-gnu` is (I know there's ongoing work to have aarch64 be tier1 with tests run natively).

I've currently hacked up the dockerfiles to do this, but I'm only about 40% sure I did it correctly, so we'll see, assuming this idea is acceptable.

### PR DESCRIPTION
**Pull request by alex**
fixes #75721

I've put this together by cargo culting pieces from different Docker files. It's a bit emberassing, because I frankly have no idea if I did this correctly 😬 The docker image builds, but attempting to run it produces various permission errors that I believe are related to my local docker setup by rootless. In short, I'm very sorry for this mess and please review with a critical eye.

### CODE REVIEW

**Comment by ehuss** [comment]
I assume the PR title "must" is a typo?

Can you update this line in the docs to add a checkmark in the third column to indicate this target is available as a host target?

https://github.com/rust-lang/rust/blob/e15510ca33ea15c893b78710101c962b11459963/src/doc/rustc/src/platform-support.md#L65

(FWIW, I ran the docker image, and it failed with `Host compiler must support std::atomic!` when building LLVM for aarch64-unknown-linux-musl)

**Comment by alex** [comment]
Sigh. Yes, it's a typo. It's a good thing my job doesn't require a lot of typing, I'm quite bad at it.

**Comment by alex** [comment]
I've updated the docs.

As for the compilation error. #63623 mentions that same error, but doesn't quite find the underlying cause. My inclination is that it likely means the version of GCC being used to build LLVM is too old -- likely since the base docker image is Ubuntu 16.04 and I'm sure aarch64 has improved a lot since then. Is bumping the base container a reasonable thing?

**Comment by ehuss** [comment]
I don't really know much about it.  One thing I don't understand is the difference between [`musl-toolchain.sh`](https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/musl-toolchain.sh) (which is used for the x86_64-unknown-linux-musl host builder and builds gcc 9.2.0) and [`musl.sh`](https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/musl.sh) (which uses the system gcc of 5.4.0).  They seem to create the musl root in completely different ways.

**Comment by mati865** [comment]
>  They seem to create the musl root in completely different ways.

Thats true.
`musl.sh` takes system GCC and instructs it to use musl as C library. Obviously musl C++ is missing in this case so it's only able to compile and link C code.
`musl-toolchain.sh` prepares full GCC toolchain that can build and link C++ code and has kernel headers.

**Comment by alex** [comment]
@ehuss @pietroalbini  I think the PR that was closed in favor of this might actually be more complete/better/more functional. I guess I got here first, but I'm very happy to hand it over to @Gelbpunkt unless there's something I missed :-)

**Comment by pnkfelix** [comment]
> This was [discussed today as part of the compiler weekly meeting](https://zulip-archive.rust-lang.org/238009tcompilermeetings/10920weeklymeeting2020091054818.html#209653748)

More specifically, I think the T-compiler team was generally in favor of landing this.

So I'm removing S-waiting-on-team.

(One thing I do *not* know is whether T-infra has discussed this. Cc @rust-lang/infra )

**Comment by pietroalbini** [comment]
At @alex's request, closing this in favor of https://github.com/rust-lang/rust/pull/76420!

**Pull request closed without merging**
