### PR TITLE
Trait impl show docs

### LINKED ISSUE #51834: rustdoc: trait pages don't show impl docs
For example, the page for `u64` shows an `impl From<bool> for u64` that is well documented, whereas the page for `From` shows only the bare trait and method signature without any docs.

I see the method `html/render.rs`: `fn render_implementor(..)` appears to render the trait implementors, but I don't have enough time to navigate the byzantine structure of librustdoc to find where best to insert the doc comments. If someone knowledgeable agrees to mentor me here, I'll gladly take this.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #51834.

screen shot 2018-06-29 at 00 14 33

(You can see both commit changes in the screenshot 😄)

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Would it be possible to only show the impl-specific docs on the trait page? For example, if the impl provides docs of its own we can print that regardless, but otherwise it would only print the trait's docs if it were on the struct page. (Which i think would be covered by `use_absolute.is_some()` or something like that?) That would cut out some of the clutter, but still print the details mentioned in the linked issue.

**Comment by GuillaumeGomez** [comment]
By default docs are hidden and I think that the issue wanted to have the trait's docs. Or at least that's how I understood it and I like it as is. :)

**Comment by QuietMisdreavus** [comment]
@llogiq What do you think about my suggestion?

**Comment by llogiq** [comment]
@QuietMisdreavus I like it! The general trait docs are already in the header, and only showing the `+` if impls have docs makes it easier to find them.

**Comment by TimNN** [comment]
Ping from triage, @QuietMisdreavus. This PR requires your review, I think.

**Comment by QuietMisdreavus** [comment]
@GuillaumeGomez Does this include my suggestion about not printing the "default" docs when on the trait page, now that @llogiq has agreed?

**Comment by GuillaumeGomez** [comment]
I think it does print it. If you want me to remove it, it'll take a bit of time but I'll try to update it in the next week or so...

**Comment by pietroalbini** [comment]
Ping from triage @QuietMisdreavus! This PR needs your review.

**Comment by QuietMisdreavus** [comment]
Still waiting on @GuillaumeGomez to address the last review comment.

**Comment by pietroalbini** [comment]
Ping from triage @GuillaumeGomez! It's been a while since we heard from you, will you have time to work on this again?

**Comment by Aaronepower** [comment]
Triage: @GuillaumeGomez Have you been able to get back to this?

**Comment by GuillaumeGomez** [comment]
I did but debate still ongoing between @QuietMisdreavus and me.

**Comment by GuillaumeGomez** [comment]
No more default docs.

**Comment by GuillaumeGomez** [comment]
Finally ready...

**Comment by QuietMisdreavus** [comment]
Preview:

image

...now i'm not so sure. On a trait like Clone with a ton of impls but not a lot of impls with overridden docs, you just have pages and pages of duplicated items as it lists out the methods:

image

This seems really awkward, but i don't know the best way to display this. @llogiq and @rust-lang/docs, what do y'all think?

**Comment by GuillaumeGomez** [comment]
Should we merge then?

**Comment by QuietMisdreavus** [comment]
I have another suggestion. Can we only show methods that have impl-specific docs on them? In other words, in that Clone example above, instead of showing all those `fn clone` with no docs on them, can we just leave those methods out entirely? So for an implementation that adds no docs, it looks kinda like before - with no added information - but if some implementation adds docs of its own, like `Arc`'s implementation above, we show that method and its docs.

To say it another way, consider this example:

```rust
pub trait SomeTrait {
    fn one(&self);
    fn two(&self);
}

pub struct SomeStruct;

impl SomeTrait for SomeStruct {
    /// Here are some impl-specific docs!
    fn one(&self) {}

    // (note that this function is not specially documented!)
    fn two(&self) {}
}
```

On the page for `SomeTrait`, when we show `SomeStruct`'s implementation, include `fn one` and its documentation, but leave out `fn two` entirely.

**Comment by Mark-Simulacrum** [comment]
I'd worry somewhat that users might think that they can't call two then, especially new users. Could we maybe have the non-documented options hidden by default in `[+]` or some such?

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum Not sure to follow you: what options are you talking about?

**Comment by Mark-Simulacrum** [comment]
er, I meant consts/items, sorry.

**Comment by GuillaumeGomez** [comment]
Ok, I'll add them as well.

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum After taking a look, it seems like another big change. I'd prefer having it in another PR. This one is already fixing two issues and has been open for quite some time already. I'd prefer avoiding delaying it any further.

**Comment by Mark-Simulacrum** [comment]
I'm not exactly sure about the current state of this PR, but it was my loose impression that my concerns were about changes that this PR made. If they're not, then that's fine -- we can open an issue instead -- but otherwise I'd rather not land this if it does in fact make things worse in what I raised concerns about.

**Comment by GuillaumeGomez** [comment]
Not worse but not (much?) better either. I'll open an issue so I can work on it separately.

**Pull request merged**
