### PR TITLE
Detect illegal hidden lifetimes in `impl Trait`

### LINKED ISSUE #46541: 🚀 existential impl Trait allows lifetimes that would not be allowed by abstract type
Consider [this curious case](https://play.rust-lang.org/?gist=d9a635ff3417aecc141d059e0db69e81&version=nightly):

```rust
#![allow(dead_code)]
#![feature(conservative_impl_trait)]
#![feature(in_band_lifetimes)]

use std::cell::Cell;

trait Trait<'a> { }

impl Trait<'b> for Cell<&'a u32> { }

fn foo(x: Cell<&'x u32>) -> impl Trait<'y>
where 'x: 'y
{
    x
}

fn main() { }
```

Here, the value we are returning is of type `Cell<&'x u32>`, but the return type ought only to be able to mention `'y`. In other words, we are inferring something like

```rust
abstract type Foo<'z>: Trait<'z> = Cell<&'x u32>
```

which is clearly malformed. We allow this because the current code has regionck bound all lifetimes with `'y` and considers that sufficient to ensure that nothing is "leaking" that shouldn't -- but, as can be seen here, that's not always true.

I don't think we should accept this  -- at least for now. However, I also could not find an obvious way to weaponize it. There may not be one. Consider that [this variant](https://play.rust-lang.org/?gist=6ebc8027d5bd6eee0eb598e29adea553&version=nightly), using `Box<dyn Trait<'y> + 'y>` in place of `impl Trait<'y>`, type-checks and ought to be sound (afaik). (In part, though, this relies on the fact that we expand `impl Trait<'y>` to `impl Trait<'y> + 'y` internally, but it seems like `impl Trait<'y>` must outlive `'y` just by construction, since it could not name any other lifetime.)

One could imagine permitting the example via some sort of subtyping relation on abstract types -- that is, perhaps we might determine a variance for `Foo` with respect to its type parameters based on the traits that it implements. Not sure if that would be sound, but you could imagine it. Until we have such a justification, though, I think we should not accept the example.

I'll probably fix this en passane while doing some refactoring to support `impl Trait` in the NLL code.

cc https://github.com/rust-lang/rust/issues/34511

### PR DESCRIPTION
**Pull request by nikomatsakis**
This branch fixes #46541 -- however, it presently doesn't build because it also *breaks* a number of existing usages of impl Trait. I'm opening it as a WIP for now, just because we want to move on impl Trait, but I'll try to fix the problem in a bit. 

~~(The problem is due to the fact that we apparently infer stricter lifetimes in closures that we need to; for example, if you capture a variable of type `&'a &'b u32`, we will put *precisely* those lifetimes into the closure, even if the closure would be happy with `&'a &'a u32`. This causes the present chance to affect things that are not invariant.)~~ fixed

r? @cramertj

### CODE REVIEW

**Comment by pietroalbini** [comment]
Ping from triage @cramertj! This PR needs your review.

**Comment by cramertj** [comment]
This seems fine to me so far, but I think @nikomatsakis was going to push some updates to the behavior of lifetimes inside of closures. @nikomatsakis is that still your plan?

**Comment by nikomatsakis** [comment]
@cramertj I did that already

**Comment by cramertj** [comment]
Ah sorry, I hadn't looked in a while. Is the remaining travis failure (`ui/generator/auto-trait-regions.rs`) something you're aware of?

**Comment by nikomatsakis** [comment]
@cramertj I saw it now, I'll go try and fix it

**Comment by cramertj** [comment]
(@nikomatsakis travis is still mad)

**Comment by nikomatsakis** [comment]
@cramertj yeah I didn't start trying to fix it yet :)

**Comment by nikomatsakis** [comment]
@cramertj ok fixed now

**Comment by cramertj** [comment]
Travis still red.

**Comment by nikomatsakis** [comment]
Yeah, spoke a bit prematurely. I fixed a few more things.

**Comment by cramertj** [comment]
(@nikomatsakis just in case you weren't aware, this is still red)

**Pull request merged**
