### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #71289 (Allow using `Self::` in doc)
 - #72375 (Improve E0599 explanation)
 - #72385 (Add some teams to prioritization exclude_labels)
 - #72395 (Allow rust-highfive to label issues it creates.)
 - #72453 (Add flag to open docs:  x.py doc --open)
 - #72459 (Add core::future::IntoFuture)
 - #72461 (Clean up E0600 explanation)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
spurious

@bors retry

**Comment by pietroalbini** [comment]
@bors treeclosed=1000

GitHub outage.

**Comment by Aaron1011** [comment]
@bors untreeclosed

Github outage has ended: https://www.githubstatus.com/incidents/6tcfpztf6j9m

**Pull request merged**
