### PR TITLE
Fix parsing for casting an empty return expression

### PR DESCRIPTION
**Pull request by cramertj**
Partial fix for #28784.

### CODE REVIEW

**Comment by petrochenkov** [comment]
Hm, I think you need to
- add the same condition to `NtIdent` below
- actually list all possible ident that can start an expression.

The list should look like this if I'm not missing anything:
- all `!is_any_keyword` idents
- `is_path_segment_keyword` idents
- `box`, `break`, `continue`, `false`, `for`, `if`, `loop`, `match`, `move`, `return`, `true`, `unsafe`, `while`

**Comment by cramertj** [comment]
I agree. However, I didn't get a response when I asked about the more
general solution in the issue, so I decided to keep the scope small to
start (just `as`). If a more general (i.e. "correct") solution is wanted,
I'd be happy to do that instead.

**Comment by petrochenkov** [comment]
@cramertj 
Making `can_begin_expr` precise is a general solution for the `return` sub-problem of https://github.com/rust-lang/rust/issues/28784 (it affects couple of other places as well), so it's wanted.

**Comment by cramertj** [comment]
@petrochenkov Great! I'll make that change then.

**Comment by cramertj** [comment]
@petrochenkov Just started working on this, and I wanted to clarify the desired behavior for the `NtIdent` case. Currently, `is_keyword`, `is_any_keyword`, `is_strict_keyword`, etc. return false for `Interpolated(NtIdent(..))` (or rather, they return false for all non-`Ident`s). Should that be changed, too?

**Comment by petrochenkov** [comment]
@cramertj 
Actually, disregard my comment about `NtIdent`, it looks like macro machinery always unwraps it into `Ident`, so it can never be encountered during parsing.

**Comment by cramertj** [comment]
@petrochenkov 
Does this look right to you?

```rust
fn ident_can_begin_expr(ident: ast::Ident) -> bool {
    let ident_token: Token = Ident(ident);

    !ident_token.is_any_keyword() ||
    ident_token.is_path_segment_keyword() ||
    [
        keywords::Box.name(),
        keywords::Break.name(),
        keywords::Continue.name(),
        keywords::False.name(),
        keywords::For.name(),
        keywords::If.name(),
        keywords::Loop.name(),
        keywords::Match.name(),
        keywords::Move.name(),
        keywords::Return.name(),
        keywords::True.name(),
        keywords::Unsafe.name(),
        keywords::While.name(),
    ].contains(&ident.name)
}
```

**Comment by cramertj** [comment]
I don't think `while` and `for` can be expressions, can they? I'm guessing you added those because of the discussions around `break`ing with a value.

**Comment by petrochenkov** [comment]
@cramertj 
```
let a: () = while true { break };
```
They are expressions, they are just always result in `()` at the moment.

**Comment by cramertj** [comment]
Huh. TIL.

**Pull request closed without merging**
