### PR TITLE
Split `CommonTypes` into `CommonTypes` and `CommonLifetimes`

### PR DESCRIPTION
**Pull request by varkor**
The so-called "`CommonTypes`" contains more than just types.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
cc @rust-lang/compiler I was thinking `tcx.builtin: Builtin` might also work.
Or we could have `tcx.types`, `tcx.lifetimes`, `tcx.consts`, etc.

**Comment by oli-obk** [comment]
I like grouping them in their own fields.

**Comment by varkor** [comment]
I've changed it so that they're now grouped by fields: `tcx.types` and `tcx.lifetimes` (soon to be joined by `tcx.consts`).

**Comment by eddyb** [comment]
cc @nikomatsakis This is where "loans" would be nicer because it'd be shorter.

@bors r+

**Pull request merged**
