### PR TITLE
More derive output improvements

### PR DESCRIPTION
**Pull request by nnethercote**
This PR includes:
- Some test improvements.
- Some cosmetic changes to derive output that make the code look more like what a human would write.
- Some more fundamental improvements to `cmp` and `partial_cmp` generation.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ 

This looks good to me, thanks!

**Comment by lqd** [comment]
That may be unrelated to the PR: maybe the super rare "parallel-codegen thread status unexpected state machine transition" issue we've seen before (I think there's an open issue, at least I know I've discussed this with mw before... somewhere).

let's see: @bors retry

**Pull request merged**
