### PR TITLE
Point at the span for the definition of crate foreign ADTs

### PR DESCRIPTION
**Pull request by estebank**
Follow up to #65421. Partially addresses #65386. Blocked on #53081.

### CODE REVIEW

**Comment by estebank** [comment]
@petrochenkov I'd like to attempt to merge this (if approved) to see if the errors I feared would trigger actually do.

**Comment by JohnCSimon** [comment]
Ping from triage:
@estebank is this still blocked?
CC: @petrochenkov 
Thank you.

**Comment by estebank** [comment]
@JohnCSimon it is.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/67334 is merged, marking as unblocked.

**Comment by joelpalmer** [comment]
Ping from Triage: any updates @estebank?

**Comment by estebank** [comment]
@joelpalmer I was out last week. I have rebased and added the appropriate platform specific test ignores.

@petrochenkov I believe this is ready for final review.

**Pull request merged**
