### PR TITLE
[WIP] Make usize overflow always have debug-assertions semantics

### PR DESCRIPTION
**Pull request by alex**
This is a prototype for https://github.com/rust-lang/rfcs/pull/2635 to enable us to collect some measurements.

### CODE REVIEW

**Comment by alex** [comment]
(Ok, I tried to use Github's draft features, but it appears that it doesn't run CI, oh well.)

**Comment by alex** [comment]
Test failures are examples of LTO + linking with C that die with `undefined reference to core::panicking::panic::h05784555a26cf2e4`. I'm going to to speculate that somewhere there's some `usize` arithmetic that we can now panic on it, but which for whatever reason doesn't cause `panic` to be properly linked in.

This is obviously a bug and needs to be fixed, but I don't think it's a blocker to doing any performance measurement on the impact of this.

**Comment by scottmcm** [comment]
Triggering perf needs a try build, which IIRC does need to pass tests.  Maybe just delete the tests that are failing for now, since we just need something that runs, not something ready to merge.

**Comment by oli-obk** [comment]
@rust-timer build 7231393efd7d34ee85e8f21b5f969232c3df0c8e

**Comment by alex** [comment]
So the regressions here are frankly much larger than I'd expected. Since the only benchmark this really tests is the compiler, before I dig too far into looking at the code generated, are there any reasons the changes I made here would be particularly slow, even if they'd left the generated code the same?

**Comment by AaronKutch** [comment]
If most of the usize increments done in hot loops are not optimized away, then I would expect that to be the biggest perf killer. Are there some small functions with tight loops we could look at the before and after assembly for?

**Comment by alex** [comment]
Ok, one thing to note, comparing instructions (which is the default) is probably a mistake, we're _for sure_ adding some instructions. The question is whether those instructions map to time. So for now I'm going to be looking at cycles, which seems like probably the best thing to consider.

It's not a lot better from this perspective, but it is a bit: https://perf.rust-lang.org/compare.html?start=f47ec2ad5b6887b3d400aee49e2294bd27733d18&end=7231393efd7d34ee85e8f21b5f969232c3df0c8e&stat=cycles%3Au

**Comment by alex** [comment]
@oli-obk Would you mind kicking off another try + perf run?

**Comment by scottmcm** [comment]
@rust-timer build abc6e249ffab2f04c2de86fa9926dd61efb65343

**Comment by Dylan-DPC** [comment]
ping from triage @alex you have a few conflicts to resolve

**Comment by alex** [comment]
I'm currently working through profiling and finding places to optimize (e.g. #58692) to make this practical, so I have not been worried about mergability for the time being.

**Comment by Dylan-DPC** [comment]
Ah okay. That's fine :)

**Comment by Centril** [comment]
Closing due to inactivity, feel free to reopen whenever.

**Comment by alex** [comment]
In case anyone is eagerly following after this, I wanted to report that I had not forgotten about this! The first overflow optimization issue in LLVM is resolved, now I'm on to failing tests because of inability to do loop idiom recognition: https://bugs.llvm.org/show_bug.cgi?id=46057

**Pull request closed without merging**
