### PR TITLE
Rename `EvalResult` to `InterpResult`

### PR DESCRIPTION
**Pull request by kenta7777**
This PR renames all uses of `EvalResult` in `librustc/mir` and `librustc_mir` to `InterpResult`.
This PR is related to #54395 .

### CODE REVIEW

**Comment by oli-obk** [comment]
The changes lgtm. Please rebase and squash the commits.

**Comment by kenta7777** [comment]
I rebased my commits. Please review.

**Comment by kennytm** [comment]
@bors r-

This has broken miri which is disallowed on the week before beta release.

**Comment by kenta7777** [comment]
Sorry for being late.
As with [the change](https://github.com/rust-lang/miri/pull/668), Should I rename some codes in miri?

**Comment by oli-obk** [comment]
> As with the change, Should I rename some codes in miri?

That would be great, yes.

**Comment by oli-obk** [comment]
@kenta7777 	please rebase and fix the import failures (they are happening because of changes from other PRs)

**Comment by RalfJung** [comment]
FWIW this also blocks fixing https://github.com/rust-lang/miri/issues/417, which is an issue that people run into all the time (so I'd like to work on it soon-ish).

**Comment by kenta7777** [comment]
Sorry for the delay in fixing. I'll work on this in a few days.

**Comment by RalfJung** [comment]
I have taken over this PR to unblock other work; closing in favor of https://github.com/rust-lang/rust/pull/61625.

**Pull request closed without merging**
