### PR TITLE
Allow files to be replaced by text on stdin

### PR DESCRIPTION
**Pull request by nrc**
Adds a flag -Zreplace-files. If that is set, then rustc reads a JSON array from stdin of files to replace with provided text.

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
Why not use a custom driver for this? I don't think flag-based feature creep will not help in the long term.

cc @rust-lang/compiler

**Comment by nrc** [comment]
Because I think enabling this functionality for IDEs is important enough to merit a flag and that having to use a custom build of the compiler is too big of a speed bump for potential IDE users.

**Comment by eddyb** [comment]
I'm not sure I understand the situation. One can get away [with just one small binary](https://github.com/solson/miri/blob/5b012edc7ab8690610b0502be24f3eb8ed30486b/src/bin/miri.rs#L26) that links against `librustc_driver` and provides additional functionality (or has no CLI, just IPC).

**Comment by nrc** [comment]
@eddyb to build that small binary thought, you need to build the dependent crates from source, which effectively means rebuilding the compiler. That seems too high a bar for people who just want to use an IDE (even having to use nightly is a bit sucky, but such is life). Or we have to distribute our own binaries with the RLS and keep them up to date, etc. That is what we'll do in the long run (and remove this flag), but in the short-run that is more overhead than we want.

**Comment by eddyb** [comment]
@nrc What do you mean? What I linked builds with just a compatible nightly. There's no source builds.

**Comment by nrc** [comment]
How does it do that? It has `extern crate rustc;`. Do we distribute rlibs with nightly?

**Comment by nagisa** [comment]
@nrc `extern crate` looks for `rlib` *or* `so`-with-metadata section. Either works. Since `-Z` flags are supposed to be unstable/nightly-only anyway, both approaches seem equivalent in terms of speed-bumpiness to me.

**Comment by nrc** [comment]
OK, I did some experimentation running the compiler from inside the RLS that seems promising, so closing this for now.

**Pull request closed without merging**
