### PR TITLE
Stabilize slice_split_at_unchecked

### LINKED ISSUE #76014: Tracking Issue for slice::split_at_unchecked() and split_at_mut_unchecked()
This is a tracking issue for the `slice::split_at_unchecked()` and `slice::split_at_mut_unchecked()` functions.
The feature gate for the issue is `#![feature(slice_split_at_unchecked)]`.

### API

```rust
impl<T> [T] {
    pub const unsafe fn split_at_unchecked(&self, mid: usize) -> (&[T], &[T]);
    pub const unsafe fn split_at_mut_unchecked(&mut self, mid: usize) -> (&mut [T], &mut [T]);
}
```

### Steps

- [x] Implement (https://github.com/rust-lang/rust/pull/75936)
- [x] FCP (https://github.com/rust-lang/rust/issues/76014#issuecomment-1954560830)
- [ ] Stabilization PR

### Unresolved Questions

 - Is this worth having if it's simple enough to implement manually around `slice::get_unchecked()` or `slice::from_raw_parts()`?

### PR DESCRIPTION
**Pull request by wutchzone**
Greetings!

I took the opportunity, and I tried to stabilize the `slice_split_at_unchecked` feature. I followed the guidelines, and I hope everything was done correctly :crossed_fingers: .

Closes #76014

### CODE REVIEW

**Comment by m-ou-se** [comment]
This will need an FCP for stabilization. I have updated [the tracking issue](https://github.com/rust-lang/rust/issues/76014) and nominated it for discussion.

**Comment by wutchzone** [comment]
@m-ou-se (my apologies for pinging :pray:) The FCP stabilized this, do you think we can progress on this one, or are there any blockers?

**Comment by m-ou-se** [comment]
Thanks for the reminder!

@bors r+ rollup

**Pull request merged**
