### PR TITLE
Drop unstable `Option::contains`, `Result::contains`, `Result::contains_err`

### PR DESCRIPTION
**Pull request by soc**
This is a proposal to drop the three functions `Option::contains`, `Result::contains` and `Result::contains_err`.

The discovery of `Option::is_some_with`/`Result::is_ok_with`/`Result::is_err_with` in https://github.com/rust-lang/rust/pull/93051 obviates the need for these methods (non-stabilization tracked in https://github.com/rust-lang/rust/issues/62358).

An additional benefit of change is that it avoids spurious error messages in IDEs, when `contains` is supplied by a third-party library: 
option-result-unstable

### CODE REVIEW

**Comment by soc** [comment]
@Mark-Simulacrum does this require an API Change Proposal, or is the tracking issue enough?

**Comment by Mark-Simulacrum** [comment]
r? libs-api

**Comment by Amanieu** [comment]
I started an FCP to close #62358.

**Comment by soc** [comment]
@Amanieu thanks for having a look! I'd say the motivation is less about

> has a better name

as many people found the original ticket in the first place because they intuitively assumed that `contains` worked, and more about freeing up the name again such that it can be used without getting pestered by rustc/IDEs.

**Comment by AaronKutch** [comment]
Could we keep just 'Option::contains'? In #62358 which I think closed prematurely, I noted that 'Result::contains' has a ambiguity problem when the type is 'Result<T, T>', but I see no problem with 'Option::contains'. Additionally, we might have 'Result::ok_contains' (instead of the current 'Result::contains') and 'Result::err_contains'. I see no reason why we can't have both these functions and the closure based functions, and get the best of both worlds.

**Comment by Amanieu** [comment]
The problem with `contains` is that its use cases are very limited: it's only useful when you are dealing with types that implement `PartialEq` but not `Eq`, which is very rare in practice. The more general `is_some_and` can be used for such rare cases when encountered.

For types that implemented `Eq` you can just use `x == Some(y)` instead of `x.contains(&y)`.

**Comment by Amanieu** [comment]
Actually, my mistake, I misread #20063. It seems that `contains` is still useful when dealing with checking whether an `Option<String>` contains a  `&str`. However `contains` is still fundamentally quite controversial and unlikely to be stabilized: the tracking issue has been opened since 2019. I think it would make more sense to focus on less controversial alternatives such as `is_some_and` instead.

**Comment by soc** [comment]
@Amanieu `is_some_and(|x| x == y)` is not substantially better than the existing `map_or(false, |x| x == y)`. It's neither more intuitive nor does it document intent better than the latter, it's just yet-another variation of the same thing.

I'm not interested in re-litigating `contains`.

I just want it gone so I can use `contains` from a third-party crate without getting hassled by IDEs.

I regret trying to contribute to Rust, and after this trivial suggestion wasted more than 3 years of everyone's time, I just want to move on.

**Comment by AaronKutch** [comment]
I can't believe I forgot about 'x == Some(y)', that and matching for various edge cases should be the preferred method. I saw that an issue was being closed, noticed a subissue, didn't read over the discussion thoroughly. I wish that summary of why 'contains' wasn't worth it had been included in the closing comment

**Comment by soc** [comment]
> I can't believe I forgot about 'x == Some(y)', that and matching for various edge cases should be the preferred method.

`y` gets moved if not `Copy`.

> summary of why 'contains' wasn't worth it

Semantics weren't the issue, to be honest.

**Pull request merged**
