### PR TITLE
Convert Intos to Froms.

### PR DESCRIPTION
**Pull request by clarfonthey**
This didn't work before but supposedly this should work now. It's better to have `From` impls over `Into`.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Travis failed:

```
[00:02:05] error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g. `MyStruct<T>`); only traits defined in the current crate can be implemented for a type parameter
[00:02:05]     --> /checkout/src/libcollections/vec.rs:2128:1
[00:02:05]      |
[00:02:05] 2128 | / impl<T> From<Vec<T>> for Box<[T]> {
[00:02:05] 2129 | |     fn from(v: Vec<T>) -> Box<[T]> {
[00:02:05] 2130 | |         v.into_boxed_slice()
[00:02:05] 2131 | |     }
[00:02:05] 2132 | | }
[00:02:05]      | |_^
[00:02:05]
[00:02:05] error: aborting due to previous error
```

**Comment by BurntSushi** [comment]
In principle this seems fine to me, if you can get it to work. However, are there any backward compatibility/inference failure hazards? Should this get a crater run?

**Comment by clarcharr** [comment]
@burntsushi doesn't require crater run because `From` automatically implements `Into`, so, in principle this is just adding a `From` impl

**Comment by BurntSushi** [comment]
Right. I understand it *shouldn't*. But I've been fooled by things like this in the past. :-)

**Comment by alexcrichton** [comment]
Ah yeah unfortunately these impls are not possible due to coherence. In that case I'm going to close this.

**Comment by ollie27** [comment]
I believe it's only `impl<T> From<Vec<T>> for Box<[T]>` which doesn't work. The others compiled fine when I tried them.

**Comment by alexcrichton** [comment]
Ah ok! Want to send a PR with those implementations?

**Comment by ollie27** [comment]
Sure:  #42227

**Comment by clarcharr** [comment]
Thanks @ollie27 for beating me to it

**Pull request closed without merging**
