### PR TITLE
Improve syntax-index entry for lifetime bounds

### PR DESCRIPTION
**Pull request by Manishearth**
We should have stuff on this in the book somewhere too

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
We should, and I thought I did. I'm not sure this is the place for explaining, though, it's for summarizing and linking to where it's explained elsewhere.

**Comment by Manishearth** [comment]
Yeah, this isn't the best place for explaining, but there should be a one-line explanation anyway in case of ambiguous terminology (i.e. "outlives")

**Comment by steveklabnik** [comment]
@bors: r+ rollup

i'm still pretty meh but if you think it's important, i'm okay with it.

**Pull request merged**
