### PR TITLE
Try caching the collect_and_partition_mono_items query

### PR DESCRIPTION
**Pull request by oli-obk**
r? @ghost

an experiment to debug some performance issues encountered in https://github.com/rust-lang/rust/pull/112879

### CODE REVIEW

**Comment by oli-obk** [comment]
Somewhat baffled as to why removing an `eval_always` would lead to an increase in actual work being done. An increase in caching I understand.

@cjgillot you always have very on-point query system insights, any idea here?

**Comment by bjorn3** [comment]
If eval_always is passed I believe we skip recording query dependencies and some other things.

**Comment by oli-obk** [comment]
oh... that makes sense. I mistakenly thought that other queries also got more expensive or called more often, but looking again that does not seem to be the case.

Thanks!

**Pull request closed without merging**
