### PR TITLE
Print lifetimes with backticks

### LINKED ISSUE #65287: Lifetimes are inconsistently printed with backticks
```rust
fn foo<'a>(u: &'a usize) -> impl IntoIterator<Item = usize> + 'a {
    std::thread::spawn(|| {
        println!("{}", u);
    });
    vec![]
}
```
displays:
```
error: cannot infer an appropriate lifetime
 --> src/lib.rs:2:24
  |
2 |       std::thread::spawn(|| {
  |  _____------------------_^
  | |     |
  | |     this return type evaluates to the `'static` lifetime...
3 | |         println!("{}", u);
4 | |     });
  | |_____^ ...but this borrow...
  |
note: ...can't outlive the lifetime 'a as defined on the function body at 1:8
```
Notice how ``` `'static` ``` is surrounded in backticks, but `'a` is not.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #65287

r? @varkor

### CODE REVIEW

**Comment by varkor** [comment]
r=me when CI passes.

**Comment by Centril** [comment]
@JohnTitor can you please check that it also passes with `--compare-mode=nll`?

**Comment by JohnTitor** [comment]
@Centril just checked and passed on my local

**Comment by JohnTitor** [comment]
Ah, wait, I should a commit with `--bless`

**Pull request merged**
