### PR TITLE
attempt to clarify align_to docs

### PR DESCRIPTION
**Pull request by RalfJung**
This is not intended the change the docs at all, but @workingjubilee said the current docs are incomprehensible to some people so this is an attempt to fix that. No idea if it helps, so -- feedback welcome.

(Please let's not use this to discuss *changing* the spec. Whoever wants to change the spec should please make a separate PR for that.)

### CODE REVIEW

**Comment by ehuss** [comment]
Feedback from a random reader: It seems a bit confusing to be discussing "implementations". From my perspective, there is one implementation of the Standard Library, and I'm reading the docs for it. What other implementations are there? Why does this seem to be written as a generalized spec for the Standard Library API? That's not how the rest of the std docs are usually written.

I'd be interested in what was found confusing in the original docs, since they seem somewhat straightforward to me. The mention of an example situation (sanitizers) where the behavior may be different seems useful, but I would just tack that on to the end of the previous version. ("For example, a sanitizer may change the behavior of this function to…")

**Comment by workingjubilee** [comment]
I agree "implementations" sounds... wonky.

@ehuss The Rust community by and large has had a pattern of advising each other to avoid this function because of the weakness of the guarantees, even when it might be an appropriate function, and that's why we discussed potentially clarifying it.

Also see https://github.com/rust-lang/rust/pull/95851

**Comment by RalfJung** [comment]
I gave this another shot, based on a [proposal by Jubilee](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/align_to.20and.20other.20APIs.20with.20surprising.20const.20behavior/near/313788402).

**Comment by RalfJung** [comment]
@ehuss  That's fair -- we don't really plan to change this in the future, the reason for the non-det is different here.

What do you think about the new proposal?

**Comment by thomcc** [comment]
Sorry for the delay (real life, etc), this looks great to me. Even if I would like this to *always* behave correctly (I understand why this is difficult...), it's hard not to see this as a large improvement.

Still, even though I am strongly in favor of this, it adds a new guarantee to this functions documentation's implementation so I can't r+ it -- it needs a libs-api sign-off. Hopefully it will be painless.

@rustbot label +T-libs-api -T-libs

r? @Amanieu

**Comment by Amanieu** [comment]
LGTM! I think the new wording is *much* clearer than the old one. While it does technically add more guarantees, I think this is sufficiently minor to not require an FCP.

@bors r+ rollup

**Pull request merged**
