### PR TITLE
Remove `OneThread`

### PR DESCRIPTION
**Pull request by Zoxc**
This removes `OneThread` by switching `incr_comp_session` over to `RwLock`.

### CODE REVIEW

**Comment by petrochenkov** [comment]
It would be good to have the motivation written out explicitly for changes like this.

Why was `OneThread` used previously? Why can `RwLock` be used now instead? What changed?

**Comment by Zoxc** [comment]
Both `OneThread` and `RwLock` are fine for `incr_comp_session`, but the other uses of `OneThread` are removed, so switching `incr_comp_session` over to `RwLock` allows its removal.

**Comment by cjgillot** [comment]
This `OneThread` encodes that only the main thread is supposed to change the directory. In practice, only 2 functions are allowed to do that, called directly from `rustc_interface`.
Can we do better and move `incr_comp_session` out of `Session`?
Perhaps into `rustc_interface::queries::Queries`?

**Comment by bjorn3** [comment]
That would be nice. More mutable state has been moved out of `Session` recently and I have a PR pending to remove another bit of mutable state in `Session`.

**Comment by bjorn3** [comment]
One thing however is that I would also like to be able to finalize the incremental session from within a codegen backend. The (experimental) jit mode of cg_clif never returns control back to rustc_interface after codegen has ended. It directly runs the program and exits. This means incremental compilation is currently broken with the jit mode. For the regular jit mode it would technically be possible to move execution to `CodegenBackend::link` using global mutable state in a thread local, but that won't work for the (even more experimental) lazy jit mode which needs the `TyCtxt` to remain available all the way till the end to allow codegening new functions on the fly.

**Comment by Zoxc** [comment]
@rustbot ready

> This `OneThread` encodes that only the main thread is supposed to change the directory

That's not actually an invariant though.

**Pull request merged**
