### PR TITLE
Remove macOS 10.10 dynamic linker bug workaround

### PR DESCRIPTION
**Pull request by beetrees**
Rust's current minimum macOS version is 10.12, so the hack can be removed. This PR also updates the `remove_dir_all` docs to reflect that all supported macOS versions are protected against TOCTOU race conditions (the fallback implementation was already removed in #127683).

try-job: dist-x86_64-apple
try-job: dist-aarch64-apple
try-job: dist-apple-various
try-job: aarch64-apple
try-job: x86_64-apple-1

### CODE REVIEW

**Comment by Urgau** [comment]
@thomcc @madsmtm any objections to doing this?

**Comment by BlackHoleFox** [comment]
Not one of the people you tagged, but this looks fine. Rust no longer supports either compiling from <10.12 or running there, so people building Rust should no longer be able to hit any buggy linkers or loaders that were involved in the original problem.

**Review by BlackHoleFox — APPROVED** [review]

**Review by madsmtm — APPROVED** [review]
Fine by me

**Comment by Urgau** [comment]
Let's try a few apple CI jobs...

@bors try

**Review by jieyouxu — APPROVED** [review]
Thanks

**Comment by jieyouxu** [comment]
Does this need compatibility relnotes?

**Comment by jieyouxu** [comment]
But otherwise,

@bors r+ rollup

**Comment by saethlin** [comment]
Nominating for stable backport because of the bug reported at https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/Weird.20crash.20using.20thread.20locals.20Apple.20Silicon.20debug.

It looks like combination of rustc before this patch (back to at least 1.79) and some M1 systems (which don't have the absolute latest Apple ld/clang/OS, but aren't as old as 10.10) are producing thread-locals which are only 8-byte-aligned for types which require 16-byte-aligned allocations, which trips an unsafe precondition check when the thread-locals are used in debug builds.

We have confirmed that users with these crashy M1 systems do not have crashes on beta but have been unable to run such code for at least 3 stable releases, so backporting this would only deliver the fix sooner.

**Comment by joshtriplett** [comment]
(Marked as stable-accepted, but as usual, this doesn't warrant a point release unless we're already doing one.)

**Pull request merged**
