### PR TITLE
Stabilized vec_splice and modified splice tracking issue

### LINKED ISSUE #32310: Tracking issue for {Vec,String}::splice
Tracking issue for https://github.com/rust-lang/rfcs/pull/1432.

First needs to be implemented, then needs to go through FCP!

### PR DESCRIPTION
**Pull request by budziq**
This stabilizes the vec_splice (Vec part of splice RFC)
Fixes #32310.

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
Sorry it isn't clear from the tracking issue -- but when the libs team discussed stabilizing Vec::splice and String::splice, we decided to stabilize Vec::splice but try a new signature for String::splice and keep it unstable. I left a comment on the tracking issue just now to clarify this.

Please keep the unstable attribute on String::splice for now and change its tracking issue number to point to #44643. Since we are stabilizing one but not the other, they will need to have different feature names. We can minimize breakage by changing Vec::splice to be under the now-stable feature vec_splice and keeping String::splice under feature(splice).

```rust
#[stable(feature = "vec_splice", since = "1.22.0")]
```

```rust
#[unstable(feature = "splice", reason = "...", issue = "44643")]
```

Thanks!

**Comment by budziq** [comment]
Thanks for the heads-up! I'll do it later today.

**Comment by budziq** [comment]
@dtolnay Done!

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
