### PR TITLE
Update reference link in doc's 404

### PR DESCRIPTION
**Pull request by Havvy**
It's currently linking to a page that says it's on the page I'm changing the link too.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Good catch! r=me pending travis.

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks! i wonder why linkchecker isn't run here...

**Comment by kennytm** [comment]
I don't think the linkchecker can verify if an external link is valid...

**Comment by Havvy** [comment]
The prior link is still valid insomuch as there's a page there. It's just not a *useful* page.

**Pull request merged**
