### PR TITLE
Remove the unused StableSet and StableMap types from rustc_data_structures.

### PR DESCRIPTION
**Pull request by michaelwoerister**
The current implementation is not "stable" in the same sense that `HashStable` and `StableHasher` are stable, i.e. across compilation sessions. So, in my opinion, it's better to remove those types (which are basically unused anyway) than to give the wrong impression that these are safe for incr. comp.

I plan to provide new "stable" collection types soon that can be used to replace `FxHashMap` and `FxHashSet` in query results (see [draft](https://github.com/michaelwoerister/rust/commit/69d03ac7a7d651a397ab793e9d78f8fce3edf7a6)). It's unsound that `HashMap` and `HashSet` implement `HashStable` (see https://github.com/rust-lang/rust/issues/98890 for a recent P-critical bug caused by this) -- so we should make some progress there.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
See https://github.com/rust-lang/rust/pull/94188 for some prior work in this direction. I'll probably create an MCP for removing the `HashStable` implementation from `HashMap` and `HashSet`.

**Comment by cjgillot** [comment]
https://github.com/rust-lang/rust/issues/98890 was not caused by a `FxHashMap` getting returned by a query.  It was caused by a `FxHashMap` getting iterated upon.  I think the proper fix for this class of bugs is the internal lint forbidding iteration over hash-maps.

**Comment by michaelwoerister** [comment]
In the MCP write-up I'll explain in more detail how I think things fit together. But in short, I think it's preferable to just not implement `HashStable` for `HashMap` and `HashSet` (and `BTreeMap` and `BTreeSet`). They don't fulfill the contract that any observable difference results in a different `Fingerprint` -- so I think it's hard to argue that they should nonetheless implement `HashStable`.

> I think the proper fix for this class of bugs is the internal lint forbidding iteration over hash-maps.

I think the solution is a combination of both. If we disallow types in query results that don't have a proper `HashStable` impl, then indeterminism coming from iterating over a HashSet will result in spurious cache invalidation instead of potential soundness errors -- so that's an improvement. But we don't want the spurious invalidations either, so the lint will be useful to avoid those too.

**Comment by Dylan-DPC** [comment]
failed in [rollup ci](https://github.com/rust-lang/rust/pull/99399#issuecomment-1186790445)

**Comment by michaelwoerister** [comment]
Rebased.

Don't include this in rollups since it can easily break if another PR adds a `use rustc_data_structures::stable_map::FxHashMap` before this is being tested.

@bors r=nagisa rollup=never

**Pull request merged**
