### PR TITLE
[WIP] Token-based outer attributes handling

### PR DESCRIPTION
**Pull request by Aaron1011**
Makes progress towards #43081

We now capture tokens for attributes, and remove them from the tokenstream when applying `#[cfg]` attributes (in addition to modifying the AST). As a result, derive-proc-macros now receive the exact input (instead of the pretty-printed/retokenized input), even when fields/variants get `#[cfg]`-stripped.

Several changes are made in order to accomplish this:

* New structs `PreexpTokenStream` and `PreexpTokenTree` are added. These are identical to `TokenStream` and `PreexpTokenstream,` with the exception of an `OuterAttributes` variant in `PreexpTokenTree`. This is used to represent captured attributes, allowing the target tokens to be removed by `#[cfg]-stripping`
(and when invoking attribute macros).
* Tokens are now attached to `Attribute`. This allows us to remove `prepend_attributes`, which required pretty-printing/retokenizing attributes in certain cases.
* `collect_tokens` was rewritten. The implementation is now much simpler - instead of keeping track of nested `TokenTree::Delimited` at various deps, we collect all tokens into a flat buffer (e.g. we push `TokenKind::OpenDelim` and `TokenKind::CloseDelim`. After capturing, we losslessly re-package these tokens back into the normal `TokenTree::Delimited` structure.
* We now store a `PreexpTokenStream` on AST s structs instead of a plain `TokenStream`. This contains both the attributes and the target itself.
* `parse_outer_attributes` now passes the parsed attributes to a closure, instead of simply returning them. The closure is responsible for parsing the attribute target, and allows us to automatically construct the proper `PreexpTokenStream`.
* `HasAttrs` now has a `visit_tokens` method. This is used during `#[cfg]`-stripping to allow us to remove attribute targets from the `PreexpTokenStream`.

This PR is quite large (though ~1000 lines are tests). I opened it mainly to show how all of the individual pieces fit together, since some of them (e.g. the `parse_outer_attributes` change) don't make sense if we're not going to land this PR. However, many pieces are mergeable on their own - I plan to split them into their own PRs.

TODO:

- [ ] Any errors for malformed `#[cfg]`/`#[cfg_attr]` are duplicated. This is because we run the same code for both the AST-based attributes and the token-based attributes. We could possibly skip validating the token-based attributes, but I was worried about accidentally skipping gating if the pretty-print/reparse check ever fails. These are deduplicated by the diagnostic infrastructure outside of compiletest, but it would be nice to fix this.
- [ ] Inner attributes are partially handled - we store them in the `PreexpTokenStream` alongside outer attributes, which allows us to handle `#![cfg(FALSE)]` and remove its parent. This should be good enough to handle all stable uses of inner attributes that are observable by proc-macros (currently, just cfg-stripping before `#[derive]` macros are invoked). Custom inner attributes are not handled.
- [ ] `Parser::parse_stmt_without_recovery` does not eat a trailing semicolon, which means we will not capture it in the tokenstream. I need to either refactor statement parsing to eat the semicolon inside the `parse_outer_attributes_with_tokens`, or manually adjust the captured tokens.
- [ ] I currently only check for the presence/absence of attributes when determining whether to run token-collection logic. If this causes performance problems, we could look for specific attributes (`cfg`, `cfg_attr`, `derive`, or any non-builtin attribute). There are many scenarios where we can skip token collection for some/all ast structs (no `derive` on an an item, no `cfg` inside an item, no custom attributes on an item, etc.)

### CODE REVIEW

**Comment by petrochenkov** [comment]
@Aaron1011 
Apologies, I spent all the weekend time on testing LLD, so I didn't have chance to look a this.
I'll try to do it during the week.

**Comment by Aaron1011** [comment]
I've added handing for `#![cfg]` (inner cfg attributes), which should allow us to keep tokens for all stable uses of attributes (modulo any remaining pretty-printer bugs). Custom inner attributes are still not handled.

**Comment by Aaron1011** [comment]
This needs additional work to improve the performance, but the behavior should be correct. The Crater queue is pretty empty, so I'm going to do a run to see how much breakage this causes.

@craterbot check

**Comment by Aaron1011** [comment]
This causes regressions of up to 2.6% on benchmarks without an incremental cache (`full`, `incr-full`). On jobs with an incremental cache (`incr-unchanged` and `incr-patched`), the regression is up to 7.6%. However, this appears to reflect the fact that the total instruction counts for incr-cache jobs are much lower (making a constant instruction count increase represent a larger percentage of the total instruction count). There doesn't seem to be anything that actually runs slower during a build with a populated cache (e.g. hashing or deserialization).

**Comment by Aaron1011** [comment]
@petrochenkov: If you agree with the overall approach, I can split out some of the larger refactoring parts (e.g. changing `parse_outer_attributes` to take a closure) into a separate PR that makes no behavior changes.

**Comment by Aaron1011** [comment]
@craterbot check crates=crater-reports.s3.amazonaws.com/pr-76130/retry-regressed-list.txt p=1

**Comment by Aaron1011** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-76130/retry-regressed-list.txt p=1

This should finish quickly.

**Comment by Aaron1011** [comment]
@craterbot abort

**Comment by Aaron1011** [comment]
@craterbot check crates=crater-reports.s3.amazonaws.com/pr-76130/retry-regressed-list.txt p=1

**Comment by Aaron1011** [comment]
@craterbot check crates=https://crater-reports.s3.amazonaws.com/pr-76130/retry-regressed-list.txt p=1

**Comment by Aaron1011** [comment]
The perf results are incomplete due to https://github.com/rust-lang/rustc-perf/issues/765

**Comment by Aaron1011** [comment]
There are many legitimate regressions. In some cases, a proc-macro was unconditionally inserting a comma, which broke once a trailing comma started getting preserved from the original `TokenStream`.

**Comment by Aaron1011** [comment]
The Crater run revealed several additional bugs in my implementation.

Unfortunately, there are a large number of legitimate regressions from crates depending on `actix-web` (or one of many forks of it) with an outdated version of `syn` being pulled in.

**Comment by petrochenkov** [comment]
We need to trim this PR a bit first.
Right now I don't really understand what happens here because it's too large.

The next changes are improvements on their own and can be landed in separate PRs:
- Newly added tests and test cases.
- Adding tokens to statements.
- Adding tokens to `ast::Attribute`s and eliminating `prepend_attrs` (at least partially).
- Token collection refactoring.

Additionally:
- Field / variant / etc span changes are responsible for the majority of the diff in test outputs. Can we keep the old spans in AST and not extend them to comma separators?
- `parse_outer_attributes` and similar changes involving `self` -> `this` dominate the parser diff. Can they be factored out into a separate commit (the first one). Other commits contain some significant back and forth, so I ended up reading the diff for the whole PR instead of separate commits, so it would be better to squash them.

**Comment by Aaron1011** [comment]
> Field / variant / etc span changes are responsible for the majority of the diff in test outputs. Can we keep the old spans in AST and not extend them to comma separators?

We could, but that seems weirdly inconsistent - we would then have a span that doesn't include some of the tokens we capture. However, I could split this out into a separate PR to minimize the diff.

**Comment by Aaron1011** [comment]
I'll work on splitting things up. I opened this PR mainly to do a Crater run to check that everything fit together.

**Comment by petrochenkov** [comment]
With this PR we perform transformations like cfg-expansion on both tokens and AST simultaneously, and then make sure that they are still in sync with the pretty-print-reparse hack.

In the end state, I think, we should treat the AST part as a cache (used for performance only) and always reparse it from tokens after any transformations (which will only be performed on tokens). The reparse hack will then be eliminated.

This is kinda opposite to what we do now by treating the *tokens* as a "cache" and regenerating them from AST when necessary (via pretty-printing), but unlike the "AST -> tokens", the "tokens -> AST" conversion is always lossless.

Having only tokens without any AST cache should be functionally correct, but it's pretty reasonable to predict that it will be a performance regression because we'll have to parse same tokens at least twice and maybe more.

**Comment by Dylan-DPC** [comment]
Blocked on https://github.com/rust-lang/rust/pull/77250

**Comment by crlf0710** [comment]
Triage: A reminder that #77250 has been merged, so it seems maybe this can continue...

**Comment by Aaron1011** [comment]
This is currently blocked on further work on statement attributes

**Comment by Aaron1011** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/80689

**Pull request closed without merging**
