### PR TITLE
[WIP] Bump system LLVM version to 7

### PR DESCRIPTION
**Pull request by glandium**
My immediate goal with this PR is to see if the change works on Travis. There is much discussion to have related to system LLVM, Travis, and the minimum supported version of system LLVM, and I'm not sure this is the right avenue. I'll probably post something on internals.rust-lang.org.

### CODE REVIEW

**Comment by glandium** [comment]
Started thread: https://internals.rust-lang.org/t/rust-vs-llvm/8604

Don't merge.

**Comment by nikomatsakis** [comment]
Tagging as `[WIP]` to prevent accidental merging =)

**Comment by nagisa** [comment]
It does not appear that there is any more discussion on the linked thread. There doesn’t appear to be any sort of consensus...

**Comment by gnzlbg** [comment]
@glandium is this PR still necessary ?

**Comment by glandium** [comment]
Probably not.

**Pull request closed without merging**
