### PR TITLE
Migrate CSS highlight to CSS variables

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/rust-lang/rust/pull/98460.

There are UI changes: I unified the colors as follows:

 * All keyword elements now have the same color.
 * All the literal elements now have the same color.
 * I removed the italic on `.self` in the `ayu` theme as it was the only theme with it.

You can test it [here](https://rustdoc.crud.net/imperio/migrate-css-highlight/src/test_docs/lib.rs.html).

cc @jsha 
r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'll update following your suggestions then to see if it looks better.

**Comment by GuillaumeGomez** [comment]
I updated the style as you recommended. I tried to pick good colours for literals but don't hesitate if you have better ones. :)

**Comment by GuillaumeGomez** [comment]
Fixed merge conflict.

**Comment by jsha** [comment]
In general we should not combine refactorings with nontrivial feature changes. Can you make the refactoring (change to CSS variables) without making the feature change (merging colors)? Then we can discuss the feature change independently.

**Comment by GuillaumeGomez** [comment]
It's a bit complicated because `ayu` combines colors differently than the other themes, hence why I tried to clarify things a bit. I'll try to keep the current behaviour as much as possible then.

**Pull request closed without merging**
