### PR TITLE
update miri

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by RalfJung** [comment]
(Almost) submodule-only, toolstate fix Cc @oli-obk 
@bors r+ p=1

**Comment by RalfJung** [comment]
Looks like no job is running anyway, so...
@bors p=100

**Comment by RalfJung** [comment]
Oh lol, @aidanhs and me literally raced on this. ;)
Yielding to rollup.
@bors retry

**Comment by aidanhs** [comment]
Eh, rollup failed, let's leave this to run.

**Pull request merged**
