### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #72445 (Stabilize `#[track_caller]`.)
 - #73678 (Update Box::from_raw example to generalize better)
 - #73684 (add spans to injected coverage counters, extract with CoverageData query)
 - #73716 (Document the static keyword)
 - #73752 (Remap Windows ERROR_INVALID_PARAMETER to ErrorKind::InvalidInput from Other)
 - #73781 (Update psm version)
 - #73803 (Recover extra trailing angle brackets in struct definition)
 - #73805 (Document the type keyword)
 - #73828 (Fix wording for anonymous parameter name help)
 - #73841 (Remove defunct `-Z print-region-graph`)
 - #73846 (Fix comma in debug_assert! docs)
 - #73848 (Fix markdown rendering in librustc_lexer docs)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors treeclosed=1000 r- retry

Need to make some infrastructure changes for a couple of minutes.

**Comment by crlf0710** [comment]
Seems caused by #72445, some asm unittests are missing out.

**Pull request closed without merging**
