### PR TITLE
Only consider places with the same local in each_borrow_involving_path.

### PR DESCRIPTION
**Pull request by cjgillot**
This avoids having a busy loop that repeatedly checks for equality of locals.

### CODE REVIEW

**Comment by wesleywiser** [comment]
r? rust-lang/compiler

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
Ugh, didn't catch the perf results when reviewing this. I guess if it's not a perf improvement, we should probably revert this.

**Pull request merged**
