### PR TITLE
Deduplicate projection sub-obligations

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by jackh726** [comment]
This is basically a rebase of #84944, which is currently blocked on test for #85360. As with #89831, I'm hesitant to poke around in this code without a regression test in place - particularly when the motivation is performance, rather than a bug.

**Comment by JohnCSimon** [comment]
Return to author for regression test.

@rustbot label: +S-waiting-on-author -S-waiting-on-review

**Comment by wesleywiser** [comment]
Since it's been over a month, let's rerun perf to make sure we're still seeing similar results.

@bors try @rust-timer queue

**Comment by wesleywiser** [comment]
The increased regression in instruction counts for `incr-unchanged` builds of `deep-vector` might be due to https://github.com/rust-lang/rustc-perf/issues/1105.

**Comment by estebank** [comment]
The change looks reasonable to me, and the perf improvements look very enticing (and because of the nature of the change, the full positive impact isn't really seen in the perf suite without a new explicit test) but am concerned by the perf regressions. @pnkfelix could you look at the perf summary and determine if this can be landed as is?

**Comment by jackh726** [comment]
@bors r+

This is a targeted fix for #91598/#89195/#89601 and others. There's followup to do elsewhere (it doesn't bring perf completely to pre-regression times, but it does decrease it significantly; also, there are other behavior regressions), but this is a good start.

**Comment by jackh726** [comment]
I'm actually going to beta and stable nominate this. The perf regressions that this fixes are pretty bad.

**Comment by pnkfelix** [comment]
beta-accepted in tandem with #91065

**Comment by pnkfelix** [comment]
declining for stable-backport.

@rustbot: -label: stable-nominated

**Pull request merged**
