### PR TITLE
Rewrite `precompute_borrows_out_of_scope` for fewer hash table lookups.

### PR DESCRIPTION
**Pull request by nnethercote**
It now does one hash table lookup per basic block, instead of one per
statement. This is worthwhile because this function is hot for NLL
builds of `ucd`.

I haven't measured the effect of this yet because I'm having trouble doing optimized builds of rustc that are suitable for profiling (#53916). I will do an online perf run instead.

r? @nikomatsakis

### CODE REVIEW

**Comment by nnethercote** [comment]
@rust-timer build e6588839b5a4ae34dab4c5c8e5a9b7e49699c3ee

**Comment by nnethercote** [comment]
BTW, I verified the correctness of this by implementing the new code alongside the old code, running both in tandem, and asserting that the `HashSet`s of visited nodes matched each other.

**Comment by ljedrz** [comment]
Perf results are in; ucd-check improves by almost 60%.

**Review by nikomatsakis — APPROVED** [review]
This is nice.

**Comment by nnethercote** [comment]
> Perf results are in; ucd-check improves by almost 60%.

Yay! And it's a 1% NLL win for `html5ever`, too.

@nikomatsakis: I have one question. Each BB has N statements, with indices 0..=N, plus a terminator at index N. Currently, the terminator location gets tested by region_contains(), and I don't know if that is valid or not.

**Comment by nikomatsakis** [comment]
@nnethercote 

> Currently, the terminator location gets tested by region_contains(), and I don't know if that is valid or not.

This is correct, the terminator location is no different from the others from the POV of this code.

**Comment by nnethercote** [comment]
I bet $5 that #53909 will end up landing before this does, in which case this PR will provide (a) a 1% `html5ever-check` NLL win, and (b) future protection against other potential bad cases.

**Comment by pnkfelix** [comment]
> I bet $5 that #53909 will end up landing before this does, ...

well that is an interesting technique to try to get your PR some favoritism from the reviewers! :wink:

**Comment by nnethercote** [comment]
48 hours ago this PR was 10th in Homu's queue. It's now 11th. I find Homu frustrating: https://github.com/rust-lang/rust/issues/37107

**Comment by nnethercote** [comment]
> I bet $5 that #53909 will end up landing before this does

It did, by about 4 hours.

**Comment by lqd** [comment]
@nnethercote it looks more like yours merged 8h before #53909

**Pull request merged**
