### PR TITLE
Revert ObligationForest on beta branch

### PR DESCRIPTION
**Pull request by nikomatsakis**
The OF caused a regression in compiler performance and backporting the fix
to beta was deemed too risky and too challenging, since it is
non-trivial and builds on prior commits in various ways.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hmm, local testing of this PR has encountered some odd failures (e.g., a segfault just now in the libcollections tests).

But I am sort of reluctant to blame it on this PR to be honest.

**Comment by brson** [comment]
I'm testing locally.

**Comment by nikomatsakis** [comment]
Actually, I see the same problem whether or not this commit is applied:

```
test str::test_into_bytes ... ok
test str::test_empty_match_indices ... ok
test str::test_find_str ... ok
Illegal instruction (core dumped)
make: *** [tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-collectionstest.ok] Error 132
```

**Comment by brson** [comment]
I don't see the crash locally.

**Comment by nikomatsakis** [comment]
OK, I don't know what's happening locally, but I'm inclined to take this PR.

**Pull request merged**
