### PR TITLE
Tighten span for E0063

### PR DESCRIPTION
**Pull request by sanxiyn**

### CODE REVIEW

**Comment by sanxiyn** [comment]
```rust
struct Point {
    x: i32,
    y: i32,
}

fn main() {
    Point {
        x: 1,
    };
}
```

Before:

```
error: missing field `y` in initializer of `Point` [--explain E0063]
 --> test.rs:7:5
7 |>     Point {
  |>     ^
```

After:

```
error: missing field `y` in initializer of `Point` [--explain E0063]
 --> test.rs:7:5
7 |>     Point {
  |>     ^^^^^
```

**Comment by nagisa** [comment]
Actually, lemme do this:

@bors r+.

**Comment by nikomatsakis** [comment]
lgtm!

**Pull request merged**
