### PR TITLE
adding freebsd x86_64 snapshot 235d774

### PR DESCRIPTION
**Pull request by dhuseby**
@alexcrichton will you pleas upload the following file when landing this patch:

https://github.com/dhuseby/rust-manual-snapshots/raw/master/rust-stage0-2016-03-18-235d774-freebsd-x86_64-bffad45a0ee1521c56934f757717bc79170042af.tar.bz2

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks like there's already a freebsd snapshot in this block? Does it not work though?

**Comment by dhuseby** [comment]
@alexcrichton oh, oops :)  I didn't see it down there.  closing, carry on, nothing to see here.

**Comment by mneumann** [comment]
@dhuseby : Maybe you wanted  to upload  the DragonFly snapshot for 18-03? :)

**Comment by dhuseby** [comment]
@mneumann maybe, I'm catching up on snapshots now.  I'm going to wait for the ones I have already submitted to land first.  Then will build ones for the latest snap revision.

**Pull request closed without merging**
