### PR TITLE
Implement RFC 2421, 'Keyword unreservations (pure, sizeof, alignof, offsetof)

### PR DESCRIPTION
**Pull request by Havvy**
On my local machine I was getting failures in `test/ui-fulldeps`, but I was also getting them again after reverting the change, so I'm hoping that this works.

I removed the test because that's what the other PR that unreserved a keyword did and I feel that it doesn't make sense/keep value to keep a test for something removed years ago.

### CODE REVIEW

**Comment by Centril** [comment]
I would add some tests checking that the removed reservations now work as identifiers.
Looks good otherwise.

Also, reassigning to

r? @petrochenkov

:)

**Comment by TimNN** [comment]
Triage ping, @petrochenkov. This PR is waiting for your review.

**Comment by Havvy** [comment]
Rebased onto master to get rid of merge conflict. No actual code changes.

**Comment by Havvy** [comment]
I think this is waiting for a new r+?

**Pull request merged**
