### PR TITLE
[perf] Canonicalize defining anchor for queries only when needed

### PR DESCRIPTION
**Pull request by aliemjay**
cc #116823
cc @compiler-errors @oli-obk 

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
Interesting strategy...

**Comment by aliemjay** [comment]
@bors try @rust-timer queue
hopefully the last time :) local benchmarks are now promising.

**Comment by aliemjay** [comment]
> `evaluate_obligation` query may need more work on how to signal that the query needs a concrete `DefiningAnchor`, because relying on ambiguity yields too much false positives.

or we can keep using bubble in `evaluate_obligation`? given that it doesn't have user-visible changes.

**Comment by apiraino** [comment]
removing the flag about waiting on a review until someone shows up to adopt this puppet. thanks @aliemjay to pushing it until here!

@rustbot author

**Comment by Dylan-DPC** [comment]
Closing this as this pr has stalled and feature is uncertain

**Pull request closed without merging**
