### PR TITLE
remove example usage of from_str in error docs

### LINKED ISSUE #24185: book: from_str examples are out of date
The `from_str` function was removed in favor of `.parse()`, so the examples may need to be tweaked now. The section I'm thinking of this this: http://doc.rust-lang.org/book/error-handling.html#handling-errors-with-option-and-result

cc @steveklabnik

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #24185

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ e6f1a4db5fb98407e33bfe33b2bb3debd686047f rollup

Doc spree!

**Comment by steveklabnik** [comment]
if it wasn't for traige I'd have even more, heh

**Comment by steveklabnik** [comment]
This was merged in https://github.com/rust-lang/rust/pull/24512 , sorry, I rebased and forgot that'd screw it up :(

**Pull request closed without merging**
