### PR TITLE
Move unicode Python script into libstd_unicode crate.

### PR DESCRIPTION
**Pull request by frewsxcv**
The only place this Python script is used is inside the libstd_unicode
crate, so lets move it there.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Nice!

If you're feeling adventurous, want to open an issue for translating this to the build script as well?

**Comment by rkruppe** [comment]
Many of the scripts in `src/etc` are only used from one place. I've considered it a dumping place for this sort of generator scripts. If we instead want build-time scripts to be stored in the crate they're related to, we should be consistent about it. (Obviously that doesn't have to happen in *this* PR but a I-cleanup issue would be good.)

**Comment by frewsxcv** [comment]
>If you're feeling adventurous, want to open an issue for translating this to the build script as well?

Assuming what you mean is that we should call this Python file whenever we build this crate to generate that file (or something along those lines), one downside is that it creates another network dependency, which isn't great. Not a show stopper, but worth pointing out

**Comment by alexcrichton** [comment]
@frewsxcv oh sorry to clarify what I meant was actually rewriting the python logic in Rust, basically translating it into the build script.

I had forgotten about the network dependency though! In that case let's just leave it be.

**Pull request merged**
