### PR TITLE
[do not merge] Revert "Convert SerializedDepGraph to be a struct-of-arrays"

### PR DESCRIPTION
**Pull request by Zoxc**
Let's check if https://github.com/rust-lang/rust/pull/49069 was actually helpful.

r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build d4535555c198635a0e55923011bdae65f75925b7

**Comment by Zoxc** [comment]
This doesn't seem to have much of an impact, but if it shifts computation to dep graph serialization it could still be beneficial to revert this for parallel queries.

**Comment by michaelwoerister** [comment]
I think we got the information we needed (and https://github.com/rust-lang/rust/pull/57061 is merged already). Thanks for collecting the numbers, @Zoxc!

**Pull request closed without merging**
