### PR TITLE
Add missing pieces for sparc-linux-gnu support

### PR DESCRIPTION
**Pull request by glaubitz**
I noticed that while Rust has CABI support for 32-bit SPARC, there are still some pieces missing to be able to use Rust on a 32-Bit SPARC system like Gentoo which still defaults to a 32-bit port unlike Debian's sparc64 port.

This PR is an attempt to add the missing pieces. I will send the necessary changes for libc in a separate PR.

CC @jrtc27

### CODE REVIEW

**Comment by glaubitz** [comment]
I have just updated that PR. I fixed two small issues (wrong name of the OpenSSL configuration and CPU name) and also added "sparc-unknown-linux-gnu"  to tools/build-manifest/src/main.rs.

**Comment by glaubitz** [comment]
@estebank Can you tell bors to pick the updated commits?

**Comment by glaubitz** [comment]
@sanxiyn Sorry, I just noticed that I forgot to add ```sparc-unknown-linux-gnu``` to ```src/librustc_back/target/mod.rs```. Could you re-approve?

**Comment by sanxiyn** [comment]
Sure. @bors r+

**Comment by glaubitz** [comment]
@sanxiyn Ok, one more :). We decided to pass "-mv8plus" to the linker which is useful when cross-building.

**Pull request merged**
