### PR TITLE
Improve linking of crates with circular dependencies

### PR DESCRIPTION
**Pull request by tmiasko**
Previously, the code responsible for handling the cycles between crates
introduces through weak lang items, would keep a set of missing language
items:

* extending it with items missing from the current crate,
* removing items provided by the current crate,
* grouping the crates when the set changed from non-empty back to empty.

This could produce incorrect results, if a lang item was missing from a
crate that comes after the crate that provides it (in the loop iteration
order). In that case the grouping would not take place.

The changes here address this specific failure scenario by keeping track
of two separate sets of crates. Those that are required to link successfully,
and those that are available for linking.

Verified using test case from #69368.

### CODE REVIEW

**Comment by eddyb** [comment]
I am not familiar with `--{start,end}-group` or the problem solved here.

r? @alexcrichton (who authored #49316)

**Comment by alexcrichton** [comment]
Thanks for the PR!

I'm not sure I fully understand why the previous iteration was incorrect, though. Can you describe in more detail why `--start-group` and such were in the wrong place or omitted?

Additionally, would it be possible to add a test to this PR?

**Comment by tmiasko** [comment]
1. Crates will generally miss `EhPersonalityLangItem` because of code here: https://github.com/rust-lang/rust/blob/e3a277943e5e55a4ef169d5cc629de664db5e24e/src/librustc_passes/weak_lang_items.rs#L24-L40
2. Previously, it was unlikely for `end_with` to ever be empty, since even if `EhPersonalityLangItem` was momentarily removed by retain, it would be immediately added back in by the next crate and then never removed again.
3. Thus, `group_start` would generally remain none, and trigger logic that prevents creation of the group https://github.com/rust-lang/rust/blob/6fd8798f4de63328d743eb2a9a9c12e202a4a182/src/librustc_codegen_ssa/back/link.rs#L1538-L1543

I don't know how to create small self contained test for this specific bug.
Using cargo + build-std to reproduce the issue is quite heavy-weight solution,
and while I could potentially look at linker arguments in an invocation of
rustc, that could very well change for valid reasons, so wouldn't be very
robust.

**Comment by tmiasko** [comment]
The situation from #69368 as happening previously (highlighting only the most relevant language items / crates):

* `alloc` requires `EhPersonalityLangItem` and `OomLangItem`, `end_with = {EhPersonalityLangItem, OomLangItem}`.
* `panic_unwind` provides `EhPersonalityLangItem`, `end_with = {OomLangItem}`.
* `std` provides `OomLangItem`, but also requires `EhPersonalityLangItem`, so `end_with = {EhPersonalityLangItem}`.

The `end_with` is never empty, and grouping does not happen.

**Comment by alexcrichton** [comment]
Ah ok I think I see what's happening now, thanks for the explanation! FWIW the iteration is in reverse order so it's a bit different, but I think it's the same principle. With the current code nothing populates `end_with` until we get to `std`, when we get:

* Looking at `std`, `end_with = {EhPersonalityLangItem}`
* Looking at `panic_unwind`, `end_with = {}` (and this closes the group)
* Looking at `alloc`, `end_with = {EhPersonalityLangItem, OomLangItem}`, but the group doesn't reopen

Does this match the behavior you're seeing with the linker? Are we surrounding `--start-group` and `--end-group` too early or around the wrong set of crates?

**Comment by tmiasko** [comment]
Your comment touches on another aspect that I think is incorrect, but the one
that I do not attempt to fix here. That is, the iteration might stop too early,
at the point where no lang items are missing, but used to be missing earlier
on, without considering remaining crates / lang items.

Note that the order I described in [the comment above][0] is already the
reversed one, so we are hitting a different issue, one where no group is
created at all.

There is one additional bit of complexity to the whole story. When using
build-std, the `EhPersonalityLangItem` is missing from std crate, on the other
hand when building without it, the `EhPersonalityLangItem` is not considered
missing at all (since std depends on `panic_unwind` which provides it).

Why the difference then? In the context of reproducer from the issue, the std
is build only as `rlib`, and even though it is build with `panic-unwind`
feature, and the `panic_unwind` is provided through `--extern`, the dependency
itself is [not injected][1], so the lang item remains to be provided later.

[0]: https://github.com/rust-lang/rust/pull/69371#issuecomment-591343077
[1]: https://github.com/rust-lang/rust/blob/a8437cf213ac1e950b6f5c691c4d2a29bf949bcd/src/librustc_metadata/creader.rs#L594

**Comment by alexcrichton** [comment]
Hm I don't understand what you mean by [your previous comment](https://github.com/rust-lang/rust/pull/69371#issuecomment-591343077) being reversed, since `std` depends on `alloc` won't we visit `std` first, then only `alloc` later?

It's true yes that if multiple `--start-group` and `--end-group` annotations are needed nothing here works, but that's not the case for the problem at hand here which is basically purely libstd/libcore and the interim crates, so we definitely don't have to deal with a "what if multiple groups" problem.

Also sorry I'm not really understanding what you are saying when you're talking about additional complexity or the difference from the reproducer. I don't really understand how build-std factors into this (how it changes lang item requirements) nor do I understand what different is going on with panic runtimes that has such a large difference here.

**Comment by tmiasko** [comment]
We visit alloc first, and std later. After all, the end of the group is set
first, and start of the group later. An example linker invocation looks as
follows:

```
"cc"
...
"-Wl,--start-group" "-Wl,-Bstatic"
"/../libstd-187e8dd7e6289af3.rlib"
"/../libpanic_unwind-168df06d56a5a3d6.rlib"
"/../libhashbrown-b076add1ee432f68.rlib"
"/../librustc_std_workspace_alloc-f915be2bd0932eb4.rlib"
"/../libbacktrace-fb40584602c8c545.rlib"
"/../libbacktrace_sys-51b5e864f7e6ff7e.rlib"
"/../librustc_demangle-03e1b6fb00a62211.rlib"
"/../libunwind-b614fe992130d55d.rlib"
"/../libcfg_if-3c8c4d01b137f5ec.rlib"
"/../liblibc-ff6dd83aac5b5d3e.rlib"
"/../liballoc-46279441278e45f1.rlib"
"/../librustc_std_workspace_core-ad9ca0851ac0bbb2.rlib"
"/../libcore-b778ac4b32b54389.rlib"
"-Wl,--end-group"
"/../libcompiler_builtins-628ce6e3cec04e19.rlib"
...
```

I reproduced the issue without build-std and added a test case, it should be
easier to follow compared to what is going on in the build-std case.

**Comment by alexcrichton** [comment]
Oh sorry I'm getting mixed up in directions. `deps` is a topologically sorted list with `core` last, so `deps.rev()` visits `core` first. So yes, `alloc` is indeed visited first.

Also thanks for the test! I'll try to poke around with that a bit locally. Hopefully one last question, though, why does std require a personality sometimes but not always? I'm not sure what's affecting that and why it's specifically an issue with build-std but not for precompiled binaries.

**Comment by tmiasko** [comment]
The language item is considered missing in a crate if it is used but not
provided by the crate or dependencies.

In the build-std case, the std is built only as rlib, the panic_unwind crate
dependency is not injected into it, and std ends up not depending on it. The
end result is that the EhPersonalityLangItem is considered missing from std.

Without build-std, the std does depend on panic_unwind and has no missing lang items.

**Comment by alexcrichton** [comment]
@bors: r+

Ah right yes because we enable features as part of rustbuild which aren't enabled in build-std, thanks for the info!

**Pull request merged**
