### PR TITLE
Use `bool` in favor of `Option<()>` for diagnostics

### PR DESCRIPTION
**Pull request by compiler-errors**
We originally only supported `Option<()>` for optional notes/labels, but we now support `bool`. Let's use that, since it usually leads to more readable code.

I'm not removing the support from the derive macro, though I guess we could error on it... 🤔

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Looks good, feel free to r=me after PR CI is green.

**Comment by jieyouxu** [comment]
r? jieyouxu
@bors r+ rollup

**Comment by estebank** [comment]
We should *also* add support for `Option<Span>` so that we can have span notes without having to build an entire subdiagnostic for it in the simple cases.

**Comment by compiler-errors** [comment]
@estebank: We do already support that.

**Comment by estebank** [comment]
@compiler-errors I'm surprised, because I tried doing that recently and the macro didn't accept it. Must have have done something wrong 🤷‍♂️

**Pull request merged**
