### PR TITLE
Remove unused extract_grammar.py

### PR DESCRIPTION
**Pull request by carols10cents**
This script used to be used to [extract the grammar sections from the reference](https://github.com/rust-lang/rust/pull/8585), but there is [now a separate src/doc/grammar.md](https://github.com/rust-lang/rust/pull/22308) that generates grammar.html where the grammar sections that used to be in the reference live, so there is no longer a need to extract the grammar from the reference.

I :heart: deleting code :) But I totally understand if there's a reason to keep this around that I don't know about :)

### CODE REVIEW

**Comment by steveklabnik** [comment]
Nope, seems good!

**Comment by steveklabnik** [comment]
:heart:

**Comment by carols10cents** [comment]
Oh well, was worth a shot ;)

**Pull request merged**
