### PR TITLE
Don't run tidy exec check on WSL2

### PR DESCRIPTION
**Pull request by carbotaniuman**
WSL2 has a lowercase "microsoft' in `/proc/version`

### CODE REVIEW

**Comment by mati865** [comment]
WSL2 is a normal VM, why should it skip that step?

**Comment by gotorust** [comment]
.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
I'm not sure why the original check was there, but this seems like a reasonable extension of it. I'm ok to r+ but @mati865 if you'd prefer to discuss a bit more that's fine with me too.

**Comment by mati865** [comment]
I'm still not convinced this is the proper solution. WSL has proper ext4 filesystem that has proper permissions:
```
stat Projects/rust/Cargo.toml
  File: Projects/rust/Cargo.toml
  Size: 3291            Blocks: 8          IO Block: 4096   regular file
Device: 810h/2064d      Inode: 111745      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ mateusz)   Gid: ( 1000/ mateusz)
Access: 2020-07-27 16:06:23.850000000 +0200
Modify: 2020-07-27 16:06:23.480000000 +0200
Change: 2020-07-27 16:06:23.480000000 +0200
 Birth: -
 mateusz@DESKTOP-mati  ~  cat /proc/version
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020
```
You really shouldn't use Rust from `/mnt/X` because all IO operations will be performed over P9 protocol which is awfully slow.

IMO the proper solution here would be to check if filesystem supports proper permissions and otherwise skip the check but I doubt that's easy to do.

**Comment by nikomatsakis** [comment]
I see. Maybe others in the windows notification group may have some advice =)

@rustbot ping windows

**Comment by spastorino** [comment]
Adding `T-compiler` label so this can be picked up by our automated prioritization tool and added to the following `T-compiler` weekly meeting agenda.

**Comment by spastorino** [comment]
This was discussed during today's compiler meeting, check out the log [here](https://zulip-archive.rust-lang.org/238009tcompilermeetings/10920weeklymeeting2020091054818.html#209652440)

**Comment by pnkfelix** [comment]
and there was further [followup discussion today, here](https://zulip-archive.rust-lang.org/238009tcompilermeetings/92353weeklymeetingfollowup2020091154818.html#209794577)

The conclusion from yesterday had been "maybe we should revise things so that this check runs solely on CI, because the existing logic (with or without the change proposed here) isn't *really* doing the right thing -- you want to know properties of the file system, not of the host OS)."

But then today we rethought things more. maybe we'll still disable the check outside of CI, or maybe we'll come up with a more robust form of the check. See the discussion linked above.

I'm leaving this PR open for now, because if we *do* leave this logic in, then we should probably apply this amendment to it. But it would be better to figure out a way to revise the logic or remove it.

**Comment by carbotaniuman** [comment]
@Mark-Simulacrum it looks like your PR supersedes this, so I'll just close it?

**Comment by Mark-Simulacrum** [comment]
Yes, that seems right, thank you!

**Pull request closed without merging**
