### PR TITLE
StructField span should include `pub`

### PR DESCRIPTION
**Pull request by chellmuth**
Issue: #26083 

I could use help creating a test for this change.

### CODE REVIEW

**Comment by nrc** [comment]
There's no great way to test these span bugs, which is why they keep cropping up. You can do something specific if you can find an error which gives the whole field as the span in the error message then you can write a test like:
```
struct Foo {
    pub
    foo: T,
}
```

And test that you get the error on the line with `pub` (to be thorough, you need to have this kind of test for each part of the span you're testing). I don't recall the details of how the error checking works though, you might need to experiment.

Anyway, usually we just don't bother ( :-( )

**Comment by chellmuth** [comment]
Ah, the line break is a clever solution. I was disappointed that you couldn't use `//~^` in a white-space sensitive way and align it under where the error should occur.

How does this test look?

**Comment by nrc** [comment]
Test looks good, modulo nits. Could you submit as a new PR please? bors is already testing this one.

**Comment by chellmuth** [comment]
Re-submitted as https://github.com/rust-lang/rust/pull/26091

**Pull request closed without merging**
