### PR TITLE
Don't print "const" keyword on non-nightly build if rustc_const_unstable is used on the item

### LINKED ISSUE #74579: CStr::from_bytes_with_nul_unchecked() incorrectly listed as const in docs
The [documentation](https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html#method.from_bytes_with_nul_unchecked) for `CStr::from_bytes_with_nul_unchecked()` lists it as a `const fn`, but its `const`-ness is still unstable (due to the `rustc_const_unstable` attribute and corroborated by the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f3c0a4f1c3eefb6e3334823851513232)).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #74579.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
In the places I added my own check. Great! Just need to update the code I already wrote then. Thanks a lot for the pointer @ollie27 !

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by ollie27** [comment]
Looks good. Just needs some tests like `src/test/rustdoc/const-display.rs` but for methods.

**Comment by GuillaumeGomez** [comment]
Added the test.

**Comment by GuillaumeGomez** [comment]
ping @rust-lang/rustdoc

**Comment by jyn514** [comment]
Test looks good to me, trusting Ollie's review for the code changes.

@bors r+

**Pull request merged**
