### PR TITLE
Better Debug for Args and ArgsOs

### PR DESCRIPTION
**Pull request by stepancheg**
Display actual args instead of two dots.

### CODE REVIEW

**Comment by stepancheg** [comment]
I didn't check it on Windows. Is there a way to ask some build system to check it?

**Comment by Mark-Simulacrum** [comment]
Not really; well, the code will be compiled and tested on Windows when r+-ed. With the right toolchains locally that's not an issue, but I wouldn't worry about it.

**Comment by stepancheg** [comment]
> With the right toolchains locally that's not an issue

What do you mean? Maybe I don't know something? I tried to compile Rust in VirtualBox, and couldn't make it work. E. g.

**Comment by stepancheg** [comment]
OK, I managed to compile it under VirtualBox and fixed it.

**Comment by stepancheg** [comment]
Test seems to be broken on Linux. Seems like args is empty on Linux. Trying to reproduce it now on Linux.

**Comment by stepancheg** [comment]
Should be OK now. Do r+ now somebody, please.

**Pull request merged**
