### PR TITLE
Use multiline Diagnostic for "relevant impl" list

### PR DESCRIPTION
**Pull request by estebank**
Provide the following output:

```
error[E0277]: the trait bound `Bar: Foo<usize>` is not satisfied
  --> $DIR/issue-21659-show-relevant-trait-impls-2.rs:38:8
   |
38 |     f1.foo(1usize);
   |        ^^^ the trait `Foo<usize>` is not implemented for `Bar`
   |
   = help: the following implementations were found:
             <Bar as Foo<i8>>
             <Bar as Foo<i16>>
             <Bar as Foo<i32>>
             <Bar as Foo<u8>>
           and 2 others

error: aborting due to previous error
```

instead of

```
error[E0277]: the trait bound `Bar: Foo<usize>` is not satisfied
  --> $DIR/issue-21659-show-relevant-trait-impls-2.rs:38:8
   |
38 |     f1.foo(1usize);
   |        ^^^ the trait `Foo<usize>` is not implemented for `Bar`
   |
   = help: the following implementations were found:
   = help:   <Bar as Foo<i8>>
   = help:   <Bar as Foo<i16>>
   = help:   <Bar as Foo<i32>>
   = help:   <Bar as Foo<u8>>
   = help: and 2 others

error: aborting due to previous error
```

### CODE REVIEW

**Comment by nikomatsakis** [comment]
OMG yes.

**Comment by estebank** [comment]
I don't see [what the error is](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1552/job/4xk7i4iwxanot5ot).

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/39074

**Pull request merged**
