### PR TITLE
Fix primitive retrieval in search index generation

### LINKED ISSUE #74780: Type-based search does not work for primitives since March
searched nightlies: from nightly-2019-05-02 to nightly-2020-07-17
regressed nightly: nightly-2020-03-20
searched commits: from https://github.com/rust-lang/rust/commit/f509b26a7730d721ef87423a72b3fdf8724b4afa to https://github.com/rust-lang/rust/commit/f4c675c476c18b1a11041193f2f59d695b126bc8
regressed commit: https://github.com/rust-lang/rust/commit/f4c675c476c18b1a11041193f2f59d695b126bc8

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script ./search_works.sh --start 2019-05-02 --preserve 
```

search_works.sh:

```
#!/bin/sh
set -eu
rustdoc search_function_type.rs
node ~/rustc/src/tools/rustdoc-js/tester.js --doc-folder doc --crate-name search_function_type --test-file ~/rustc/src/test/rustdoc-js/tmp/search-function-type.js
```

search_function_type.rs:

```
/// f
pub fn f(u: usize) -> usize {
    u
}
```

search-function-type.js:

```js
const QUERY = 'usize -> usize';

const EXPECTED = {
    'in_args': [
        { 'path': 'search_function_type', 'name': 'f' },
    ],
};
```

This requires a git clone of rustc as well as the following modification to `tester.js`:

```
diff --git a/src/tools/rustdoc-js/tester.js b/src/tools/rustdoc-js/tester.js
index 139e6f73f42..8a3ab056f80 100644
--- a/src/tools/rustdoc-js/tester.js
+++ b/src/tools/rustdoc-js/tester.js
@@ -182,7 +182,7 @@ function loadThings(thingsToLoad, kindOfLoad, funcToCall, fileContent) {
         var tmp = funcToCall(fileContent, thingsToLoad[i]);
         if (tmp === null) {
             console.log('unable to find ' + kindOfLoad + ' "' + thingsToLoad[i] + '"');
-            process.exit(1);
+            continue;
         }
         content += tmp;
         content += 'exports.' + thingsToLoad[i] + ' = ' + thingsToLoad[i] + ';';
```

</details>

Originally reported in https://github.com/rust-lang/rust/issues/60485#issuecomment-663900624.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #60485. Fixes https://github.com/rust-lang/rust/issues/74780.

Before merging, I have a few questions remaining:

 Should we remove the `primitive_locations` field from the `Cache` type? If so, we'll have to replace in the few places where we use this field (not really a problem). However, this field includes the primitive types of the current crates, whereas my new implementation only includes the ones coming from external crates. I'm not sure if it'll be an issue for libcore or not (maybe not since they can be retrieved directly inside the crate, no?).

EDIT: I removed the `primitive_locations` field from the `Cache` type, so now we're only referring/using the new "primitives cache" added by this PR.

cc @rust-lang/rustdoc 

r? @Manishearth

### CODE REVIEW

**Review by jyn514 — COMMENTED** [review]
> Should we remove the primitive_locations field from the Cache type?

I think it's better not to duplicate it in multiple places, yeah.

> However, this field includes the primitive types of the current crates, whereas my new implementation only includes the ones coming from external crates.

Is that the case? I see that this runs in `impl Clean for CrateNum` - won't external crates also be cleaned? Or is the ordering wrong and for this to work we need to have all the primitives before finishing the first crate?

**Comment by GuillaumeGomez** [comment]
Oh crap! I forgot to clean up stuff. >< I was too focused on my questions thing.

**Comment by Manishearth** [comment]
Now that this is no longer filling in any fields on `clean::ExternalCrate` I would like to move its initialization out of clean entirely. Can we write a function that takes `tcx`, runs `cx.tcx.crates().iter()....` and populates this struct, and then calls it right before `clean::krate()`?

_Eventually_  (not in this PR) i'd like to move this and the cache as fields on context objects so that we don't have as many statics.

**Comment by jyn514** [comment]
```
---- [rustdoc] rustdoc/tuples.rs stdout ----
status: exit code: 1
 stderr:
------------------------------------------
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/html/format.rs:579:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Looks like the cache might not be populated soon enough?

**Comment by Manishearth** [comment]
Yeah that's another reason to just lift it out of clean entirely.

I suspect that bug is because of libcore using primitives in functions and libstd hasn't been cleaned yet.

**Comment by GuillaumeGomez** [comment]
I'm completely unable to understand why caching the primitive sooner prevents rustdoc to find primitive types implementations, meaning that for example, it cannot find `f32::is_nan`. If anyone has an idea...

**Comment by camelid** [comment]
Are there any updates? It's been 3 months. I know eddyb tends to be very busy, so is there someone else who can help with this?

**Comment by jyn514** [comment]
This needs someone to put in the time debugging why it's broken.

@GuillaumeGomez do you know if PRIMITIVES has the same contents now as it did before? Like does it contain u8 after you initialize, before you call clean::krate?

**Comment by GuillaumeGomez** [comment]
iirc, it doesn't contain anything. I'll try to get back to this PR soon.

**Comment by jyn514** [comment]
> I'm completely unable to understand why caching the primitive sooner prevents rustdoc to find primitive types implementations, meaning that for example, it cannot find f32::is_nan.

Can you expand on this more? What code is currently responsible for finding those primitive impls?

**Comment by GuillaumeGomez** [comment]
But "the impl" I meant the source. Apparently, changing the moment when we store them prevents to have access to this information. Also, I don't remember that the primitive types have a special implementation to retrieve this information. However, with all the recent changes, maybe it'll be possible to improve this part too. Like said a month ago, I'll try to get back to this PR some day haha.

**Comment by GuillaumeGomez** [comment]
Replaced by #81557.

**Pull request closed without merging**
