### PR TITLE
Cleanup debuginfo generation a bit

### PR DESCRIPTION
**Pull request by bjorn3**
This removes an no longer necessary hack. This also uses `CrateDebugContext` in favor of `CodegenCx` in debuginfo generation.

### CODE REVIEW

**Comment by mark-i-m** [comment]
cc @eddyb I think

**Comment by JohnCSimon** [comment]
ping from triage: @bjorn3 can you address the failed checks?

**Comment by bjorn3** [comment]
This changes several files that will also be changed by #68965.

@rustbot modify labels: +S-blocked

**Comment by Dylan-DPC** [comment]
This is blocked on another blocked pr, and neither of them seem to be moving in the near future, so closing this one. You can create a new PR later if you wish once there's some progress. Thanks

**Pull request closed without merging**
