### PR TITLE
Bump to 1.83

### PR DESCRIPTION
**Pull request by BoxyUwU**
https://forge.rust-lang.org/release/process.html#bump-the-stable-version-number-t-6-days-friday-the-week-before

### CODE REVIEW

**Comment by klensy** [comment]
Weird, but after that pr i can't build rust on `x86_64-pc-windows-msvc`, it fails with errors like:
```
librustc_llvm-6cacf3c42dd6ef43.rlib(LLParser.cpp.obj) : error LNK2001: unresolved external symbol __std_mismatch_8
librustc_llvm-6cacf3c42dd6ef43.rlib(EHStreamer.cpp.obj) : error LNK2001: unresolved external symbol __std_mismatch_4
librustc_llvm-6cacf3c42dd6ef43.rlib(LoopUnroll.cpp.obj) : error LNK2001: unresolved external symbol __std_replace_8
```

(Locally bumped msvc to 17.11.4, probably it's the reason?)

**Comment by jieyouxu** [comment]
Hi @klensy, I think someone else is running into this, could you elaborate what you updated?

**Comment by klensy** [comment]
> Hi @klensy, I think someone else is running into this, could you elaborate what you updated? (This seems more like a msvc toolchain issue not a rust issue)

Yes, after automatic update, need to go into modify -> individual components -> found installed build tools (was build tools 14.40-17.10), uncheck and select newer one (build tools 14.41-17.11)

**Comment by jieyouxu** [comment]
> Yes, after automatic update, need to go into modify -> individual components -> found installed build tools (was build tools 14.40-17.10), uncheck old one (to uninstall it) and select newer one (build tools 14.41-17.11), then install it.

Thanks for the info, this is slightly funny lol.

**Pull request merged**
