### PR TITLE
Issue 42545 type inference regression

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fix an ICE that results from type inference obligations being dropped on the floor. Specifically, when computing the implied bounds, we would sometimes do normalizations that get stored in the cache, but we would *not* try to solve the resulting obligations. This can sometimes leave type variables uninferred. Occurs only rarely because implied bounds are processed in regionck which happens very late, so usually the cache is populated already from somewhere else.

I think that the *proper* fix here is probably lazy normalization. This fix is intentionally very narrow both because this code is on the chopping block and because this needs a beta backport.

r? @eddyb 
cc @arielb1

### CODE REVIEW

**Comment by aidanhs** [comment]
@bors r-

Lots of travis failures, e.g.
```
[00:41:12] error: /checkout/src/test/compile-fail/coherence-impl-trait-for-trait-object-safe.rs:17: unexpected "error": '17:1: 17:37: the trait `NotObjectSafe` cannot be made into an object [E0038]'
[00:41:12] 
[00:41:12] error: 1 unexpected errors found, 0 expected errors not found
[00:41:12] status: exit code: 101
[00:41:12] command: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /checkout/src/test/compile-fail/coherence-impl-trait-for-trait-object-safe.rs -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu --error-format json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/coherence-impl-trait-for-trait-object-safe.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/coherence-impl-trait-for-trait-object-safe.stage2-x86_64-unknown-linux-gnu -Crpath -O -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers
[00:41:12] unexpected errors (from JSON output): [
[00:41:12]     Error {
[00:41:12]         line_num: 17,
[00:41:12]         kind: Some(
[00:41:12]             Error
[00:41:12]         ),
[00:41:12]         msg: "17:1: 17:37: the trait `NotObjectSafe` cannot be made into an object [E0038]"
[00:41:12]     }
[00:41:12] ]
```

**Comment by nikomatsakis** [comment]
Bah. I hadn't considered all the duplicate errors. I'll see what I can do about suppressing those.

**Comment by arielb1** [comment]
Won't 125968b have the dropck ICE again on code with type errors?

@bors r-

**Comment by nikomatsakis** [comment]
@arielb1 

> Won't 125968b have the dropck ICE again on code with type errors?

I don't think so, because that was one of those "delayed bug" things, where it only ICEs if an error is not reported.

> have smarter span management so that the spans stay the same for both errors, which would get the error deduplicated.

Do we detect and remove duplicate errors based on span etc already? I had thought about tinkering more, but decided it was better to fix the ICE in a narrow way. Still, I could imagine looking at the obligations individually and assigning the span of the enclosing impl if they do not involve anything "local" to the function.

**Comment by arielb1** [comment]
@nikomatsakis

Sure. `traits::error_reporting` does not report duplicate and, since my PR, "implied" errors with the same span.

**Comment by nikomatsakis** [comment]
> Sure. traits::error_reporting does not report duplicate and, since my PR, "implied" errors with the same span.

The problem is that these errors are reported at different times, I **think**, and hence I'm not sure that logic will apply. That is, the one error is occurring (I believe) when we check the WF of the impl, and the other when we are checking the individual methods.

**Comment by nikomatsakis** [comment]
I verified that they are in different inference contexts, so -- barring significant restructuring -- just tinkering with spans wouldn't cut it.

**Comment by nikomatsakis** [comment]
@bors r- 

Had an idea of how to solve the remaining duplicate error problem.

**Pull request merged**
