### PR TITLE
Use in-tree libbacktrace on Fuchsia

### PR DESCRIPTION
**Pull request by cramertj**
cc @abarth

r? @alexcrichton 
(welcome back! :smile: )

### CODE REVIEW

**Comment by est31** [comment]
@cramertj any reasons for that? Using in-tree libbacktrace means that binaries get larger. Windows uses stuff from the system as well for backtraces.

**Comment by abarth** [comment]
> any reasons for that?

We're removing libbacktrace.so from the Fuchsia SDK because we cannot commit to the stability of its API.  The library is not controlled by the Fuchsia project, which means our policies around API evolution don't apply to it.

**Comment by est31** [comment]
@abarth thanks for the explainer!

**Pull request merged**
