### PR TITLE
Rename tests/ui/unique to tests/ui/box/unit

### LINKED ISSUE #109878: Rename tests/ui/unique to `box`
https://github.com/rust-lang/rust/tree/fe0b0428b89802f02a050eab72373b75709d0bce/tests/ui/unique all seem to be testing std::boxed::Box. It hasn't been called `unique` in many years, and that's now ambiguous with `ptr::Unqiue`. We should rename the test suite for clarity.

### PR DESCRIPTION
**Pull request by reez12g**
fixes https://github.com/rust-lang/rust/issues/109878

Since tests/ui/box already exists, I have temporarily named it boxed-box, but if another name sounds better, please let me know.

### CODE REVIEW

**Comment by jyn514** [comment]
I don't have time for reviews, please don't assign me.

r? @jackh726

**Comment by Nilstrieb** [comment]
What's inside tests/UI/box? Can it just be merged?

**Comment by jackh726** [comment]
I think putting these under `tests/ui/box/unit` would be better. (Should go through and make sure all of these would be eligble as unit tests for `Box`)

**Pull request merged**
