### PR TITLE
Update hashbrown to 0.8.1

### LINKED ISSUE #28481: clone_from in the standard library
The `Clone` trait has a sadly-neglected `clone_from` method that clones a value into an existing one. There is a default implementation, but it's fairly naive and therefore not optimal for all cases, notably collections.

It would be good if the major collections had better implementations for `clone_from` where it can be implemented more efficiently.

/cc @rust-lang/libs

### PR DESCRIPTION
**Pull request by Amanieu**
This update includes:
- https://github.com/rust-lang/hashbrown/pull/146, which improves the performance of `Clone` and implements `clone_from`.
- https://github.com/rust-lang/hashbrown/pull/159, which reduces the size of `HashMap` by 8 bytes.
- https://github.com/rust-lang/hashbrown/pull/162, which avoids creating small 1-element tables.

Fixes #28481

### CODE REVIEW

**Comment by M-PC** [comment]
Shut up just let it be...

**Comment by Mark-Simulacrum** [comment]
Looking over the diff in the PR you linked, this adds two uses of specialization to hashbrown which I believe carry over into std. I believe we are currently trying to vet specialization before adding more copies by ccing lang folks.

 - https://github.com/rust-lang/hashbrown/pull/146/files#diff-178822c448ce6afe0e383be6f514626eR215-R233
 - https://github.com/rust-lang/hashbrown/pull/146/files#diff-1b47db5c9a30eca8cfa833e56ecf2c4eR1034-R1066

I am unsure who the "experts" here are, but let's try @nikomatsakis and perhaps @Centril first?

**Comment by Centril** [comment]
> I am unsure who the "experts" here are, but let's try @nikomatsakis and perhaps @Centril first?

cc @matthewjasper

**Comment by Centril** [comment]
Aside: reliance on `default fn` as a syntax here is implemented in a problematic way. The right way to do it is to delay parsing in a macro or move the `default fn`s to a separate external module that is cfged. The way this is done in the diffs above, we will have a headache if we ever decide to change the syntax for specialization, so this should be fixed.

**Comment by Amanieu** [comment]
Could you give an example of how delayed parsing with a macro would work?

Is it something like this?
```rust
#[cfg(feature = "nightly")]
macro_rules! default_fn {
	($($x:tt)*) => {
        default $($x)*
    }
}
#[cfg(not(feature = "nightly"))]
macro_rules! default_fn {
	($($x:tt)*) => {
        $($x)*
    }
}
```

**Comment by Centril** [comment]
@Amanieu Example due to @petrochenkov https://github.com/rust-lang/rust/issues/65860#issuecomment-548101030.

**Comment by Amanieu** [comment]
I started a PR at https://github.com/rust-lang/hashbrown/pull/147, let me know if any other changes are needed.

**Comment by matthewjasper** [comment]
`min_specialization` is in the next nightly.
I would prefer either `min_specialization` to be used if possible or a sepatate feature flag if not.

**Comment by Amanieu** [comment]
I tried compiling with `min_specialization`, but got these errors:

```
error: cannot specialize on trait `core::marker::Copy`
    --> src/raw/mod.rs:1047:1
     |
1047 | / impl<T: Copy> RawTableClone for RawTable<T> {
1048 | |     #[cfg_attr(feature = "inline-more", inline)]
1049 | |     unsafe fn clone_from_spec(&mut self, source: &Self, _on_panic: impl FnMut(&mut Self)) {
1050 | |         source
...    |
1060 | |     }
1061 | | }
     | |_^

error: cannot specialize on trait `core::cmp::Eq`
   --> src/map.rs:225:9
    |
225 | /         impl<K: Clone, V: Clone, S> HashClone<S> for HashMap<K, V, S>
226 | |         where
227 | |             K: Eq + Hash,
228 | |             S: BuildHasher,
...   |
234 | |             }
235 | |         }
    | |_________^

error: cannot specialize on trait `core::hash::Hash`
   --> src/map.rs:225:9
    |
225 | /         impl<K: Clone, V: Clone, S> HashClone<S> for HashMap<K, V, S>
226 | |         where
227 | |             K: Eq + Hash,
228 | |             S: BuildHasher,
...   |
234 | |             }
235 | |         }
    | |_________^

error: cannot specialize on trait `core::hash::BuildHasher`
   --> src/map.rs:225:9
    |
225 | /         impl<K: Clone, V: Clone, S> HashClone<S> for HashMap<K, V, S>
226 | |         where
227 | |             K: Eq + Hash,
228 | |             S: BuildHasher,
...   |
234 | |             }
235 | |         }
    | |_________^
```

**Comment by Amanieu** [comment]
If I'm understanding the `min_specialization` documentation correctly, this means that we need to add `#[rustc_specialization_trait]` on `Copy`, `Eq`, `Hash` and `BuildHasher`. Is that correct?

**Comment by Mark-Simulacrum** [comment]
@matthewjasper Could you perhaps help @Amanieu with the answer to the above question?

**Comment by nikomatsakis** [comment]
I'm trying to remember under what conditions adding `rustc_specialization_trait` makes sense. I'm a bit nervous about us adding it loosely. But I guess I'll wait until @matthewjasper weighs in -- or else I should go refresh my memory perhaps of what precisely it means and when it's ok to use it. =)

**Comment by Centril** [comment]
@Amanieu Could we drop the specializations meanwhile to land the other bits sooner?

**Comment by Amanieu** [comment]
The specializations are really the only significant improvement that is relevant to libstd. There's not much point in upgrading otherwise.

**Comment by matthewjasper** [comment]
`rustc_specialization_trait` can't be added to stable traits since it prevents implementations in crates which don't have `feature(min_specialization)` or `feature(specialization)`.
`Copy` might get `rustc_unsafe_specialization_marker` on it temporarily, but it's not really correct and i don't want crates outside of `std` rely on it when it's removed.

**Comment by Amanieu** [comment]
Hmm, upon further review I do believe that the specialization on `Eq + Hash + BuildHasher` is unsound. I reverted it in hashbrown 0.7.2.

The other one uses `Copy`, which could be made to work with `rustc_unsafe_specialization_marker`. I think it should be fine to rely on this since:
- this is only used when the "nightly" feature of hashbrown is used. It is acceptable for compiler updates to break people who have opted into using nightly features.
- the use of specialization is an implementation detail and can be reverted at any time without any change to the API.
- hashbrown is maintained by the libs team and can quickly react to any changes in the compiler regarding specialization.

**Comment by nikomatsakis** [comment]
I don't think we should add the specialization marker to `Copy`. It is definitely possible, for better or worse, for people to write impls like

```rust
impl Copy for Foo<'static> { }
```

**Comment by Amanieu** [comment]
Specializations on `Copy` vs `Clone` are already used in the standard library: https://github.com/rust-lang/rust/blob/master/src/liballoc/vec.rs#L2168

**Comment by Dylan-DPC** [comment]
@matthewjasper any updates?

**Comment by matthewjasper** [comment]
I would rather not have out-of-tree specializations on `Copy` because it would make it harder to change how specialization on `Copy` is done (e.g. an `is_always_applicable_copy` intrinsic).

**Comment by Amanieu** [comment]
Adding the specialization for `Copy` can make cloning a `HashMap` 3-4x faster:

```
# Without specialization
test clone_from_large            ... bench:       1,506 ns/iter (+/- 109)
test clone_from_small            ... bench:          18 ns/iter (+/- 2)
test clone_large                 ... bench:       2,036 ns/iter (+/- 242)
test clone_small                 ... bench:          46 ns/iter (+/- 7)

# With specialization
test clone_from_large            ... bench:         441 ns/iter (+/- 54)
test clone_from_small            ... bench:           9 ns/iter (+/- 1)
test clone_large                 ... bench:         480 ns/iter (+/- 67)
test clone_small                 ... bench:          30 ns/iter (+/- 2)
```

I think this improvement is significant enough to justify the use of specialization. Also note that hashbrown is maintained by the libs team so its use of specialization won't block any changes to how the compiler does specialization.

**Comment by matthewjasper** [comment]
I don't think that I'll get around to adding a new way of specializing on `Copy` any time soon. Adding only the `Copy` specialization seems OK.

**Comment by Amanieu** [comment]
I have updated hashbrown to 0.8.0 which uses `min_specialization` and has a few other optimizations.

**Comment by matthewjasper** [comment]
Specialization looks good now.
Who would be a good reviewer for this?

**Comment by Amanieu** [comment]
@ortem: Recent changes to `hashbrown` have broken the debug pretty printers. The `data` field has been removed and key/value pairs are now indexed at a negative offset from `ctrl`.

```
KV3, KV2, KV1, KV0, C0, C1, C2, C3
                    ^ ctrl points here
```

I'm not too familiar with the debug visualizers so I would appreciate a bit of help getting them fixed!

**Comment by Mark-Simulacrum** [comment]
It looks like debuginfo tests are failing (probably due to differences in the underlying definition of HashMap/HashSet), you can take a look at https://github.com/rust-lang/rust/blob/a8cf3991177f30694200002cd9479ffbbe6d9a1a/src/etc/gdb_providers.py#L345 and https://github.com/rust-lang/rust/blob/a8cf3991177f30694200002cd9479ffbbe6d9a1a/src/etc/lldb_providers.py#L492 to fix those.

Let's also kick off a perf run @bors try @rust-timer queue 

I'm not sure that we *need* review beyond that already done during merging of work into hashbrown. AFAICT, this doesn't add any impls or so that we would need to be cautious about (FCP for libs). @Amanieu do you think it makes sense for someone to look at the diff in hashbrown as well?

**Comment by Amanieu** [comment]
I've updated the GDB and LLDB support but I still need to update the natvis support for Windows.

**Comment by Amanieu** [comment]
I'm stuck on getting the natvis debug info working, it uses C++ expressions but I can't cast the `ctrl` pointer to a tuple since tuples are not valid C++ syntax:

```
<Item Name="{static_cast&lt;($T0, $T1)&gt;(base.table.ctrl.pointer)[-(i + 1)].__0}">static_cast&lt;($T0, $T1)&gt;(base.table.ctrl.pointer)[-(i + 1)].__1</Item>
```

cc @MaulingMonkey who wrote the original natvis files for `HashMap`.

**Comment by MaulingMonkey** [comment]
This is hopefully only a minor rabbit hole.

## Proper fixes

A similar issue was encountered with slices - `[T]` isn't valid C++ syntax, so that gets mangled to `slice<T>` in the debug info - which looks C++y enough to write natvis files for it.  The PR that implemented that is here: <https://github.com/rust-lang/rust/pull/43221/files>.  The files have all since been moved around a bit, I'm not entirely sure where to.  Something similar could be done with tuples, mangling `(T0, T1)` to `tuple<T0,T1>`.  That *might* be sufficient if the debug info already contains proper offsets for tuple member offsets and the like?

## Short term hacks

As a terrible short term hack, std::pair or std::tuple could perhaps be substituted.  While perhaps not technically `#[repr(C)]`, they effectively should be in all natvis supporting debuggers that I'm aware of.  Of course, Rust tuples aren't `#[repr(C)]`, and Rust tuples [do not have any guarantees about their layout](https://doc.rust-lang.org/reference/type-layout.html#tuple-layout), so that's all kinds of technically wrong.  If T0/T1 might be zero-sized, all kinds of wrong in practice too, not merely "technically wrong" - so perhaps manual pointer arithmetic might be a better terrible short term hack... assuming sizeof(T0) can properly evaluate to 0 in the context of a natvis debugger?

**Comment by MaulingMonkey** [comment]
Okay, after improving support for tuples and built-in types in that PR, if/when it lands the following expressions *should* (tm) work:

```xml
<!-- HashMap -->
<Item Name="{static_cast&lt;tuple&lt;$T1, $T2&gt;*&gt;(base.table.ctrl.pointer)[-(i + 1)].__0}">static_cast&lt;tuple&lt;$T1, $T2&gt;*&gt;(base.table.ctrl.pointer)[-(i + 1)].__1</Item>
```
```xml
<!-- HashSet -->
<Item>static_cast&lt;$T1*&gt;(map.base.table.ctrl.pointer)[-(i + 1)]</Item>
```

Note:
* `$TN` expressions are **one**-based (eww!), meaning `__0` has type `$T1` in the tuples.
* We can probably drop the RawTable visualizer entirely

**Comment by Amanieu** [comment]
Would the fact that `$T1` is expanded into the expression cause issues? For example if I have a `HashMap<(u64, u64), (u64, u64)>`.

**Comment by MaulingMonkey** [comment]
> Would the fact that $T1 is expanded into the expression cause issues?

Not to my knowledge.

> For example if I have a HashMap<(u64, u64), (u64, u64)>

That works fine:

```rust
    let mut complicated = HashMap::<(u64, u64), (u64, u64)>::new();
    complicated.insert((0, 1), (2, 3));
    complicated.insert((4, 5), (6, 7));
```
```
0:000>  dx complicated,d
complicated,d    : { size=2 } [Type: std::collections::hash::map::HashMap<tuple<u64, u64>, tuple<u64, u64>, std::collections::hash::map::RandomState>]
    [<Raw View>]     [Type: std::collections::hash::map::HashMap<tuple<u64, u64>, tuple<u64, u64>, std::collections::hash::map::RandomState>]
    [size]           : 2 [Type: unsigned __int64]
    [capacity]       : 3
    ["(0x0, 0x1)"]   : (2, 3) [Type: tuple<u64, u64>]
    ["(0x4, 0x5)"]   : (6, 7) [Type: tuple<u64, u64>]
```

**Comment by Amanieu** [comment]
All tests pass now, r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
r=me if you can confirm that the PR description is up to date

@bors rollup=never since this did have some effects on perf in the last run

**Pull request merged**
