### PR TITLE
Promote loongarch64-unknown-linux-musl to Tier 2 with host tools

### PR DESCRIPTION
**Pull request by heiher**
MCP: https://github.com/rust-lang/compiler-team/issues/753
Tracking issue: https://github.com/rust-lang/rust/issues/122592

try-job: dist-loongarch64-musl

### CODE REVIEW

**Comment by heiher** [comment]
Can anyone help trigger a try build? Thanks.

**Comment by workingjubilee** [comment]
would that even work...?

**Comment by heiher** [comment]
> would that even work...?

Oops, It seems that the target of the try needs to be changed.

**Comment by workingjubilee** [comment]
...I guess it does!

**Comment by workingjubilee** [comment]
@heiher does loongarch64-musl still have no/unknown std support?

**Comment by heiher** [comment]
> @heiher does loongarch64-musl still have no/unknown std support?

loongarch64-linux-musl has std support.

**Comment by Mark-Simulacrum** [comment]
@bors try

Kicking off another try build to get the with-cache build times.

**Comment by Mark-Simulacrum** [comment]
It looks like this also needs to update:

* Platform support list: https://github.com/rust-lang/rust/blob/c3d7fb398569407350abe044e786bc7890c90397/src/doc/rustc/src/platform-support.md#L308
* I suspect rustup list needs to get updated: https://github.com/rust-lang/rust/blob/master/src/tools/build-manifest/src/main.rs

r=me with those done

**Comment by heiher** [comment]
> It looks like this also needs to update:
> 
>     * Platform support list: https://github.com/rust-lang/rust/blob/c3d7fb398569407350abe044e786bc7890c90397/src/doc/rustc/src/platform-support.md#L308
> 
>     * I suspect rustup list needs to get updated: https://github.com/rust-lang/rust/blob/master/src/tools/build-manifest/src/main.rs
> 
> 
> r=me with those done

I plan to [promote it](https://github.com/heiher/rust/commit/e43af37b7a12aa6370042067cbdb244616cc5c51) after adding CI. I would be happy to combine both CI and promote together. Thanks.

**Pull request merged**
