### PR TITLE
Move compile-fail tests with NOTE/HELP annotations to UI

### PR DESCRIPTION
**Pull request by petrochenkov**
Remove NOTE/HELP annotations from UI tests

cc https://github.com/rust-lang/rust/issues/44844 @oli-obk @est31 
r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
This looks good. We should however document the expected policy, I think, to the [compiler test documentation](https://github.com/rust-lang/rust/blob/master/src/test/COMPILER_TESTS.md).

I guess the idea is:

- Use ui tests and the stderr files to document notes etc.

I will note one thing (which should not hold up this PR). I've been very much enjoying the fact that UI tests check for ERRORs. I like being able to add minimal annotations to the test that give the kind of "overall parameters" for what the test is testing (that errors occur here, here, and here) and then having the `stderr` files capture the full behavior.

But there are times when I want to document a **subset** of the NOTEs that are present. i.e., so that I can outline "other variations in the stderr output may be acceptable, but if this NOTE disappears, that's a big problem". Note that I say **subset** -- often there are many notes, but it's just one piece I want to guarantee is present.

Before, we required that if you document any note, you must document **all** notes. The result is that it discourages me from annotating these notes that I want to be present.

(On the other hand, if you can't declare that the set of notes is exhaustive, you can't document that a note should **not** appear. I don't find this to be something I want to document very often, but it's certainly possible. But we could easily have a "NO_NOTE" annotation or something then.)

What I do for now is to leave comments, but I fear that future people will not read them.

**Comment by oli-obk** [comment]
> What I do for now is to leave comments, but I fear that future people will not read them.

Maybe it would be better suited for an issue with the appropriate tags? Do we have testsuite tags?

**Comment by nikomatsakis** [comment]
@oli-obk 

> Maybe it would be better suited for an issue with the appropriate tags? Do we have testsuite tags?

I don't follow. Maye *what* would be better suited?

**Comment by oli-obk** [comment]
Sorry, I kind of skipped ahead.

Adding a way to make these comments annotations that can't be ignored is certainly something that makes sense. It'll prevent accidental changes down the road. What I meant was make this comment an issue so it's not forgotten.

**Comment by nikomatsakis** [comment]
@oli-obk 

> Adding a way to make these comments annotations that can't be ignored is certainly something that makes sense. It'll prevent accidental changes down the road. What I meant was make this comment an issue so it's not forgotten.

yep =) https://github.com/rust-lang/rust/issues/46667

**Comment by petrochenkov** [comment]
Curl failure, looks spurious.
@bors retry

**Pull request merged**
