### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Comment by oli-obk** [comment]
Please rebase so there are no merge commits.

Are you finding these with a tool that we could regularly run? Or are there lots of false alarms?

**Comment by oli-obk** [comment]
I think your rebase went wrong. Try rebasing over the master branch of this repo, that should clean it up

**Comment by cuishuang** [comment]
> ☔ The latest upstream changes (presumably #94579) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

Done.  
Do I need to merge multiple commits into one? （use merge squash）

**Comment by oli-obk** [comment]
There are still merge commits left, you need to rebase and squash them all, yes.

Repeating this this question in case it got lost:

> Are you finding these with a tool that we could regularly run? Or are there lots of false alarms?

**Comment by estebank** [comment]
> Do I need to merge multiple commits into one? （use merge squash）

It's not always needed (when the work of each commit is self contained and the chain of commits has a narrative), but I also find that rebasing on top of master in complex PRs becomes much easier with squashed commits. Then you only have to deal with a single round of merge conflict resolution.

I would also like to highlight oli's question around *how* you found these. It'd be great if we could somehow mechanize part of that work so it doesn't have to be done manually (if the false positive rate can be kept at 0).

**Comment by camelid** [comment]
The rebase still doesn't seem to be working. Can you try following the instructions [here](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts)?

**Comment by cuishuang** [comment]
> There are still merge commits left, you need to rebase and squash them all, yes.
> 
> Repeating this this question in case it got lost:
> 
> > Are you finding these with a tool that we could regularly run? Or are there lots of false alarms?

Sorry, there have been a lot of things these days, and some work has been delayed

**Comment by cuishuang** [comment]
> > Do I need to merge multiple commits into one? （use merge squash）
> 
> It's not always needed (when the work of each commit is self contained and the chain of commits has a narrative), but I also find that rebasing on top of master in complex PRs becomes much easier with squashed commits. Then you only have to deal with a single round of merge conflict resolution.
> 
> I would also like to highlight oli's question around _how_ you found these. It'd be great if we could somehow mechanize part of that work so it doesn't have to be done manually (if the false positive rate can be kept at 0).

Yes, I previously maintained a map of fallible words for document correction. I guess there are similar tools on github and it is recommended to integrate it into CI

**Pull request closed without merging**
