### PR TITLE
Implement TryFrom<f64> for f32

### PR DESCRIPTION
**Pull request by clarfonthey**
This will only perform the conversion if it can be done without any loss of precision.

### CODE REVIEW

**Comment by scottmcm** [comment]
Previous conversations about `TryFrom<float> for integers`: https://github.com/rust-lang/rust/pull/47857

**Comment by kennytm** [comment]
Please add test cases for these.

Also, this would make e.g. `assert_eq!(f32::try_from(0.1), None)`, which may be too strict? I'd expect it return None only if overflow occurs. Perhaps `TryFrom` isn't the proper way to introduce this operation, but rather separate methods allowing user to specify what to do with overflow, underflow, inexact exceptions and rounding direction.

**Comment by clarcharr** [comment]
I'll take a look at these in a bit. You're right on the inexactness, although it's the same if you try `f32::try_from(f64::consts::pi)`. You are fundamentally losing accuracy there.

**Comment by rkruppe** [comment]
See https://internals.rust-lang.org/t/how-should-we-provide-fallible-float-to-int-conversions/6708/1

**Comment by pietroalbini** [comment]
Ping from triage @clarcharr! It's been a while since we heard from you, will you have time to work on this again soon?

**Comment by clarcharr** [comment]
@pietroalbini I haven't had time to look at this in the past few days, although I'm probably fine closing this for now. I'll open a new PR with tests once I get the time.

**Comment by pietroalbini** [comment]
Sure.

**Pull request closed without merging**
