### PR TITLE
Move std::os::raw into core

### PR DESCRIPTION
**Pull request by joshlf**
Move the types in `std::os::raw` into `core::os::raw`, and re-export them from `std::os::raw`.

This allows these types to be used in a no-std environment without having to use `libc`, and also addresses https://github.com/rust-lang-nursery/rust-bindgen/issues/1015.

There's a discussion about this on the internals forum [here](https://internals.rust-lang.org/t/duplicate-std-raw-in-core/8086).

### CODE REVIEW

**Comment by jethrogb** [comment]
This was discussed as part of [RFC 1783](https://github.com/rust-lang/rfcs/pull/1783) which was not accepted.

**Comment by kennytm** [comment]
> Is this platform-dependent? There are no extern declarations, and none of the types are architecture-specific.

There's a huge `#[cfg]` in the definition of `c_char`...

See also #46736.

**Comment by SimonSapin** [comment]
Previously:

* https://github.com/rust-lang/rust/issues/31536
* https://internals.rust-lang.org/t/solve-std-os-raw-c-void/3268
* https://github.com/rust-lang/rust/issues/36193
* https://github.com/rust-lang/rfcs/pull/1783
* https://github.com/rust-lang/rust/issues/47027
* https://crates.io/crates/cty

I’m personally not very convinced by the arguments against this move.

**Comment by dtolnay** [comment]
This would be the first use of `target_os` in libcore, and the first use of `target_arch` that is observable in the public API i.e. not just an optimization.

```rust
#[cfg(any(all(target_os = "linux", any(target_arch = "aarch64",
                                       target_arch = "arm",
                                       target_arch = "powerpc",
                                       target_arch = "powerpc64",
                                       target_arch = "s390x")),
          all(target_os = "android", any(target_arch = "aarch64",
                                         target_arch = "arm")),
          all(target_os = "l4re", target_arch = "x86_64"),
          all(target_os = "openbsd", target_arch = "aarch64"),
          all(target_os = "fuchsia", target_arch = "aarch64")))]
pub type c_char = u8;

#[cfg(any(target_pointer_width = "32", windows))]
pub type c_long = i32;
```

**Comment by joshlf** [comment]
Ah, I didn't realize this had already been litigated so much. I'm still in favor of the move, but I'm not going to waste more of folks' cycles on an issue that has been litigated to death.

**Comment by SimonSapin** [comment]
New RFC to propose doing this for `c_void` (only, for now): https://github.com/rust-lang/rfcs/pull/2521

**Pull request closed without merging**
