### PR TITLE
Always display stability version even if it's the same as the containing item

### LINKED ISSUE #118439: Missing stability badge for some methods in rustdoc
Some functions in the documentation generated by `rustdoc` (e.g. [this one](https://doc.rust-lang.org/std/pin/struct.Pin.html#method.new)) are missing the stability badge. For this method, it should show `1.33.0`.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/118439.

Currently, if the containing item's version is the same as the item's version (like a method), we don't display it on the item.

This was something done on purpose as you can see [here](https://github.com/rust-lang/rust/blob/e9b7bf011478aa8c19ac49afc99853a66ba04319/src/librustdoc/html/render/mod.rs#L949-L955). It was implemented in https://github.com/rust-lang/rust/pull/30686.

I think we should change this because on pages with a lot of items, if someone arrives (through the search or a link) to an item far below the page, they won't know the stability version unless they scroll to the top, which isn't great.

You can see the result [here](https://rustdoc.crud.net/imperio/display-stability-version/std/pin/struct.Pin.html#method.new).

r? @notriddle

### CODE REVIEW

**Comment by Kobzol** [comment]
Hmm. The sizes are the same (https://perf.rust-lang.org/compare.html?start=abe34e9ab14c0a194152b4f9acc3dcbb000f3e98&end=4d962f0f089466aec16928808dde2312d85fe7c1&stat=size%3Adoc_bytes&tab=compile&nonRelevant=true&showRawData=true). But I guess that's expected, since non-std documentation doesn't actually contain these attributes (?). We should probably measure the size of libstd docs, but that's not included in the benchmarks at the moment.

**Comment by Kobzol** [comment]
So about a 1.2% increase. That's not *that* bad I guess, but it's also not trivially small.

**Comment by aDotInTheVoid** [comment]
I think it's worth landing this. As their tend to be many methods on items in `std`, users probably haven't seen the stability version of the containing item. 

Also it feels weird and inconsistant that functions stabilized at the same time as the item have don't have a stability marker, but the rest do.

image

I think we should merge this.

**Comment by jsha** [comment]
I lean on the side of "close without action."

It's true that it's a bit weird and confusing to not have stability information in every possible place. And when I first noticed that I thought it was a bug.

But stability versions take up a notable amount of room in the UI, and if they are on every item in the standard docs, it will be harder to notice which ones are noteworthy. For instance, I think this PR would annotate every single method of `String` with `1.0.0`, right? That's not very noteworthy.

And if someone does make a mistake and uses a method that is not stabilized on the older version of Rust they're using, because they didn't notice that the struct itself wasn't stabilized by that version, they will get a nice error that makes it pretty clear what the problem is.

**Comment by Manishearth** [comment]
Hm, that's a good point

**Comment by Nemo157** [comment]
I also feel like I weakly fall on the side of landing this (maybe with the change to hide 1.0.0 annotations to reduce the size impact). I have been personally confused at the lack of annotations many times and feel like the consistency gain is worth it.

**Comment by RalfJung** [comment]
I was just quite confused by the missing stability annotation on a `const fn`: https://github.com/rust-lang/rust/issues/121989

**Comment by GuillaumeGomez** [comment]
We (briefly) talked about it in the [last rustdoc meeting](https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/meeting.202024-03-11/near/426007178). Some members of the team would actually like this feature to be merged, so more discussions will follow.

**Comment by GuillaumeGomez** [comment]
As discussed [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/meeting.202024-04-08/near/432047911), seems like the majority of the rustdoc team would prefer to have this feature.

The original reason (in 2016, so very shortly after the 1.0) for not displaying the version in case it was the same as the parent's was because it was too much noise. At the time, it was much more common for the majority of sub-items to be from 1.0. Now there's a much wider spread of version numbers so the items which don't have a version number on them are probably the minority.

But also, since then, the number of items grew quite a lot and it's not rare to land on a page to a given item and then you need to scroll to the top to see the version of the parent item to see from which version it can be used if it was not marked.

For these reasons, I'll cancel the closing FCP and open a merge FCP instead.

@rfcbot cancel

@rfcbot merge

**Comment by camelid** [comment]
rfcbot seems to be glitching...

@rfcbot reviewed

**Pull request merged**
