### PR TITLE
impl Clone for Box<CStr>, Box<OsStr>, Box<Path>

### PR DESCRIPTION
**Pull request by mbrubeck**
Implements #51908.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/libs this'll need FCP as an insta-stable change

**Comment by SimonSapin** [comment]
@rfcbot fcp merge

**Comment by SimonSapin** [comment]
@rfcbot fcp merge

**Comment by mbrubeck** [comment]
Should I change the `unstable` attributes to `stable`?

**Comment by SimonSapin** [comment]
Yes. `#[unstable]` unfortunately doesn’t work on impls, they are stable iff both the type and the trait are.

**Comment by alexcrichton** [comment]
@bors: r+ 

Let's merge!

**Comment by kennytm** [comment]
@bors retry 

```
warning: spurious network error (2 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
error: unable to get packages from source
Caused by:
  [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
thread 'main' panicked at 'tests failed for https://github.com/Aaronepower/tokei', tools\cargotest\main.rs:100:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Pull request merged**
