### PR TITLE
Improve docs related to readonly and set readonly to improve clarity of their behaviour

### LINKED ISSUE #74895: Permissions::readonly() doesn't behave as expected with files
When using the Permissions module on MacOS it doesn't behave as expected. Readonly returns if the file lacks *any* write bits, rather than returning if the current calling uid/gid can write to the file. This can be seen in the code:

https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/fs.rs#L359

This is a bit misleading because the framing of https://doc.rust-lang.org/std/fs/struct.Permissions.html#method.readonly seems to say "an unwritable file" without context which to me I interpretted as "unwritable file - by the current user" not unwriteable by all permission bits. 

I'd be happy with a disclaimer on the documentation of readonly to indicate this only checks that no write bits exist on unix so that it's clearer what it's checking for, but I'd also be happy if this function was altered to check 'is it readonly in the current calling context' but I understand that's a really challenging problem in-itself given posix acls etc. 

I expected to see this happen: A file as `root:root 640` should be readonly == true when called from "william:william"

Instead, this happened: The file is listed as "not" readonly even though the current user can not write the file OR the documentation about what readonly() does clearly explains what it is looking for on each operating system. 

Thanks!

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #74895

### CODE REVIEW

**Comment by Timmmm** [comment]
See also #101599 - I wrote it like a year ago, then forgot to upload it, finally did it today and then saw this!

**Comment by JohnTitor** [comment]
> See also #101599 - I wrote it like a year ago, then forgot to upload it, finally did it today and then saw this!

Did you mean #101644?

**Comment by Timmmm** [comment]
Ah oops, yes!

**Comment by Firstyear** [comment]
Closed in favour of https://github.com/rust-lang/rust/pull/101644

**Comment by thomcc** [comment]
@Firstyear Did you mean to close this with that comment?

**Comment by Firstyear** [comment]
Yes, sorry!

**Pull request closed without merging**
