### PR TITLE
rustbuild: drop color handling

### LINKED ISSUE #54322: 1.30.0-beta cannot bootstrap itself
Current beta (14f51b05d1865ff21977ec7a2afacb332a837781) cannot bootstrap itself.
The cargo version shipped with it appends `--color=always` when the output terminal supports it, and `src/bootstrap/compile.rs` sets `RUSTC_COLOR=1` leading to `src/boostrap/bin/rustc.rs` also appending `--color=always`.
This results in commands like:
```
rustc command: "LD_LIBRARY_PATH"="/usr/host/lib:/var/tmp/paludis/build/dev-lang-rust-1.30.0-scm/work/rust-1.30.0-scm/build/x86_64-unknown-linux-gnu/stage0-std/release/deps:/usr/x86_64-pc-linux-gnu/lib" "/usr/host/bin/rustc-beta" "--crate-name" "cc" "/var/cache/paludis/distfiles/cargo-home/registry/src/github.com-1ecc6299db9ec823/cc-1.0.22/src/lib.rs" "--color" "always" "--crate-type" "lib" "--emit=dep-info,link" "-C" "opt-level=2" "-C" "metadata=31edc2328efb244d-rustc" "-C" "extra-filename=-31edc2328efb244d" "--out-dir" "/var/tmp/paludis/build/dev-lang-rust-1.30.0-scm/work/rust-1.30.0-scm/build/x86_64-unknown-linux-gnu/stage0-std/release/deps" "-L" "dependency=/var/tmp/paludis/build/dev-lang-rust-1.30.0-scm/work/rust-1.30.0-scm/build/x86_64-unknown-linux-gnu/stage0-std/release/deps" "--cap-lints" "allow" "--cfg" "stage1" "-Clinker=x86_64-pc-linux-gnu-cc" "-C" "target-feature=-crt-static" "--color=always"
```
which in turn leads to
```
error: Option 'color' given more than once
error: Could not compile `cc`
```

### PR DESCRIPTION
**Pull request by Keruspe**
Let cargo handle that for us

Fixes #54322

Needs a beta backport

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, was it confirmed that this actually fixes things? This was originally done due to `--message-format=json` stealing rustc stdout/err and causing noncolorful output in https://github.com/rust-lang/rust/commit/305f5263f933d5d730f2bba5f0d43d9f9006361d.

**Comment by kennytm** [comment]
probably we don't really want the ANSI color for rustc in the CI since we all read the raw log anyway 😛

**Comment by alexcrichton** [comment]
@Keruspe can you check to make sure that `./x.py build` still prints colors from both Cargo and the compiler? (when error messages happen)

**Comment by Mark-Simulacrum** [comment]
Based on the issue it looks like the logic may have been actually upstreamed into cargo, could you track down/cite the relevant Cargo PR? I think that would help make sure the logic is in fact equivalent.

**Comment by Keruspe** [comment]
@alexcrichton seems to work fine here, I get colors from both cargo and rustc (still testing with cargo from the beta branch).

@Mark-Simulacrum seems to be https://github.com/rust-lang/cargo/commit/f1c783b8dafca0ced97805d58c803bafbd230e1e

**Comment by Mark-Simulacrum** [comment]
@Keruspe Can you confirm that this works with beta Cargo?

Based on the Cargo commits I believe this should be fine so @bors r+

**Comment by Keruspe** [comment]
All my testing has been done using rustc and cargo from the beta commit
mentioned earlier

**Comment by alexcrichton** [comment]
@bors: p=0

we've got a lot of backports in the queue right now and this one's pretty minor, so I think it's safe if we hold off on this to land naturally

**Pull request merged**
