### PR TITLE
Bugfix for license check

### PR DESCRIPTION
**Pull request by gilescope**
cargo fmt would only work if you were in the root dir before if a license check template was set.
(as otherwise it would not find the template.)

- is there a better way of doing this? I don't really like to mutate global state such as the current dir.

### CODE REVIEW

**Comment by gilescope** [comment]
(As mentioned as an issue in https://github.com/rust-lang/rustfmt/issues/3352 )

**Comment by calebcartwright** [comment]
Thank you but rustfmt PRs need to be opened against the rustfmt repo as opposed to updating the subtree here.

**Comment by gilescope** [comment]
ah ok. I thought maybe I needed to do it this way as the rustfmt repo
seemed dependent upon the rustc one (E.g. dependencies on the _ast crates).
Will test via rustc repo and commit back to the main rustfmt repo.

**Comment by calebcartwright** [comment]
> I thought maybe I needed to do it this way as the rustfmt repo
seemed dependent upon the rustc one (E.g. dependencies on the _ast crates).

No worries. Tool development happens in the respective repos for all tools that are subtrees or sumbodules. Tool changes then get pulled into the rustc repo at regular intervals and/or as needed to address specific issues. The tool subtrees should only be updated directly when strictly necessary with minimal changes required as part of changes tot rustc, such as AST changes that are breaking to the tool.

This PR should be closed and submitted to rust-lang/rustfmt instead

**Comment by gilescope** [comment]
Thumbsup, will do

**Comment by Mark-Simulacrum** [comment]
Thanks. Closing as it seems this will be refiled on rustfmt directly.

**Pull request closed without merging**
