### PR TITLE
Update E0220 error format

### LINKED ISSUE #35385: E0220 needs to be updated to new format
From: src/test/compile-fail/E0220.rs

Error E0220 needs a span_label, updating it from:

```
error[E0220]: associated type `F` not found for `Trait`
  --> src/test/compile-fail/E0220.rs:15:18
   |
15 | type Foo = Trait<F=i32>; //~ ERROR E0220
   |                  ^^^^^
```

To:

```
error[E0220]: associated type `F` not found for `Trait`
  --> src/test/compile-fail/E0220.rs:15:18
   |
15 | type Foo = Trait<F=i32>; //~ ERROR E0220
   |                  ^^^^^ associated `F` not found in `Trait`
```

### PR DESCRIPTION
**Pull request by chamoysvoice**
@jonathandturner 
Part of #35233 .
Fixes #35385.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Comment by TimNN** [comment]
There are some tidy failures:

```
/build/src/test/compile-fail/E0220.rs:16: tab character
/build/src/test/compile-fail/E0220.rs:18: tab character
/build/src/test/compile-fail/E0220.rs:18: trailing whitespace
/build/src/librustc_typeck/astconv.rs:1248: tab character
/build/src/librustc_typeck/astconv.rs:1249: tab character
```

**Comment by jonathandturner** [comment]
@bors r-

Pulling it out to deal with the tidy fixes.

@chamoysvoice - you can run tidy and fix the errors using:

```
python src/bootstrap/bootstrap.py --stage 1 --step check-tidy
```

It's like running the test suite, but checks against code following the style guidelines.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
