### PR TITLE
Variant Size Differences: Erase regions before computing type layout

### LINKED ISSUE #34839: Last night's nightly ICEs on regex crate
https://travis-ci.org/steveklabnik/semver/jobs/145070460

```
error: internal compiler error: ../src/librustc/infer/region_inference/mod.rs:734: cannot relate bound region: '_#0r <= ReEarlyBound(TypeSpace, 0, 'r)
```

/cc @BurntSushi 

(I can try to get a stacktrace later if it's important)

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes #34839

### CODE REVIEW

**Comment by eddyb** [comment]
cc @brson This should fix the recent regressions you've found.

**Comment by alexcrichton** [comment]
@bors: retry force clean

* I accidentally hit the merge button

**Comment by eddyb** [comment]
@arielb1 That failure is likely @alexcrichton's accidental manual merge of #34836.

**Pull request merged**
