### PR TITLE
better suggestion for duplicated `where` clause

### LINKED ISSUE #93567: Compiler expected `where` but there is a `where`
I tried this code:
```rust
pub trait MyTrait {}
pub trait AnotherTrait<U> {}
pub struct MyStruct<T> where T: AnotherTrait<U> where U: MyTrait {
    t: T,
    u: U,
}
```
I expected to see this happen:  The compiler would give a sensible error.

Instead, this happened: The compiler complains that it expected ```where``` where I actually do have ```where```:
```rustc
error: expected `where`, or `{` after struct name, found keyword `where`
  --> src/main.rs:29:49
   |
29 | pub struct MyStruct<T> where T: AnotherTrait<U> where U: MyTrait {
   |                                                 ^^^^^ expected `where`, or `{` after struct name
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (cfa4ac66c 2022-01-06)
binary: rustc
commit-hash: cfa4ac66c194046f631ce076c75516ecfdeb77ee
commit-date: 2022-01-06
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

Adding RUST_BACKTRACE=1 did not produce any additional output.

</p>
</details>

### PR DESCRIPTION
**Pull request by compiler-errors**
fixes #93567

### CODE REVIEW

**Review by lcnr — APPROVED** [review]
this is already good, do you think that extending the lint to cover
```rust
struct A where (): Sized, where (): Sized {}
//~^ ERROR cannot define duplicate `where` clauses on an item

fn foo() where (): Sized, where (): Sized {}
//~^ ERROR cannot define duplicate `where` clauses on an item

enum B where (): Sized, where (): Sized {}
//~^ ERROR cannot define duplicate `where` clauses on an item

fn main() {}
```
is also worth it. i.e. deal with `, where`?

if you don't want to deal with that, r=me

**Comment by compiler-errors** [comment]
Good point. I'll do that too, seems like something that someone might accidentally type.

**Comment by lcnr** [comment]
@bors r+ rollup

thanks :heart:

**Pull request merged**
