### PR TITLE
rustbuild: Retry downloads by default

### PR DESCRIPTION
**Pull request by alexcrichton**
Don't rely on curl's --retry, it appears to not work for some errors like SSL
errors.

### CODE REVIEW

**Comment by frewsxcv** [comment]
This is tangential to your PR, but is there any way to prevent this from happening? https://travis-ci.org/rust-lang/rust/jobs/204633420 It was just stalling for 30 minutes due to, presumably, network issues

**Comment by alexcrichton** [comment]
Unfortunately not that I know of, that was likely cloning just at a really slow rate

**Comment by arielb1** [comment]
Note: both travis failures are #39003.

**Comment by alexcrichton** [comment]
@bors: retry

* sccache wedged #39003

**Pull request merged**
