### PR TITLE
Fix typo in unicode char definition

### PR DESCRIPTION
**Pull request by mattico**
Reference: http://www.fileformat.info/info/unicode/char/16ed/index.htm

### CODE REVIEW

**Comment by kennytm** [comment]
Why all the typos are related to runic punctuations 😕 (another instance: #43773)

**Comment by aidanhs** [comment]
@bors r+

Thanks!

**Comment by mattico** [comment]
@kennytm Yeah it does seem bad. Can't blame the original PR much since it was manually editing hundreds of boring lines of data. There should probably be a way to autogenerate this list.

**Pull request merged**
