### PR TITLE
Add E0603 error code

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #42229.

cc @Susurrus

### CODE REVIEW

**Comment by Susurrus** [comment]
Is "item" the write word to use here or is there a more proper one? Seems like this error is specifically for "variables" or whatever the equivalent word is that's used in the Rust literature. Item seems too general.

**Comment by GuillaumeGomez** [comment]
Variable/const/struct/enum/module -> item seems fine :p

**Comment by Susurrus** [comment]
Then LGTM.

**Comment by GuillaumeGomez** [comment]
Thanks for your review! :)

@bors: r=Susurrus

**Pull request merged**
