### PR TITLE
Remove "Learn Rust" from TRPL.

### LINKED ISSUE #25488: Unclear Error Message in Philosopher Example
This code...
```
use std::thread;

struct Philosopher {
    name: String,
}

impl Philosopher {
    fn new(name: &str) -> Philosopher {
        Philosopher {
            name: name.to_string(),
        }
    }

    fn eat(&self) {
        println!("{} is eating.", self.name);

        thread::sleep_ms(1000);

        println!("{} is done eating.", self.name);
    }
}

fn main() {
    let philosophers = vec![
        Philosopher::new("Baruch Spinoza"),
        Philosopher::new("Gilles Deleuze"),
        Philosopher::new("Karl Marx"),
        Philosopher::new("Friedrich Nietzsche"),
        Philosopher::new("Michel Foucault"),
    ];

    let handles: Vec<_> = philosophers.into_iter().map(|p| {
        thread::spawn(move || {
            p.eat();
        });
    }).collect();

    for h in handles {
        h.join().unwrap();
    }
}
```

... leads to:
```
src/main.rs:39:11: 39:17 error: type `()` does not implement any method in scope named `join`
src/main.rs:39         h.join().unwrap();
                         ^~~~~~
error: aborting due to previous error
Could not compile `Philosopher`.
```

Actually the error lies in line 35 in the semicolon `});` at the end:

```
thread::spawn(move || {
            p.eat();
        });
```

### LINKED ISSUE #28713: rustc apparently optimizes away the loop in 3.3
I just implemented the code in section 3.3 to compare Ruby to Rust. It appears that rustc optimizes away the inner loop of the thread, because I kept increasing the limit and the completion time remained constant. I introduced a simple if statement in the loop, and then I got expected timings.

It might be worth modifying the loop so it's not optimized away for a fairer comparison. Here's what I ended up with:

```
pub extern fn process() {
  let handles: Vec<_> = (0..10).map(|_| {
    thread::spawn(|| {
      let mut x = 0u64;
      for i in (0..7_700_000_000u64) {
        if i < 1 {
          x += 2
        } else {
          x += 1
        }
      }
      x
    })
  }).collect();

  for h in handles {
    println!("Thread finished with count={}",
             h.join().map_err(|_| "Could not join a thread!").unwrap());
  }
  println!("done!");
}
```

### LINKED ISSUE #29590: Lexer chokes on certain kinds of whitespace
The presence in a Rust source file of unusual but useful kinds of whitespace, such as ASCII 0x0C (form feed), leads to the following error:

    src/main.rs:1:1: 1:2 error: unknown start of token: \u{c}
    src/main.rs:1 
                  ^

I have a specific use case for form-feeds in source files. But I think in general it is nice to ignore the same whitespace that every other programming language and file format ignores; it lessens confusion for people coming from other languages and backgrounds.

My specific use case is the long-standing, but somewhat uncommon use of the form-feed character (which semantically is a separator between pages of text) as a way to group together especially closely related functions or blocks in a file of source code. Text editors or IDEs such as vim, Emacs or XCode provide convenience features to display these form-feeds in aesthetically pleasing way, move between form-feed-delimited pages, and restrict editing to one form-feed-delimited page at a time. It's just a simple convenience feature, but it would really be nice to support it.

### LINKED ISSUE #30162: rust book refers to 'str' primitive type as if it has already been introduced
I'm going through the rust book and have gotten to the Dining Philosophers section, at which point I've encountered the following text:

```We choose the String type for the name, rather than &str.```

None of the previous introduction has even mentioned a `str` type, so I had to go looking to find out what it is and how it differs from String.  The example seems to assume that the reader would find `str` the obvious choice, but the reader hasn't heard of `str` at this point.

I'm brand new to rust myself so I'm not sure how this could be introduced better, but I think simply using String and not mentioning `str` would be less confusing at this point.

### LINKED ISSUE #30163: book: Dining Philosophers chapter uses unwrap() without explanation
```unwrap()``` is used several times throughout the chapter.

There is only a single vague mention of it, despite it being used several times in the code:
>Since this shouldn’t happen, we just use ```unwrap()```.

A bit more detail would be helpful, especially when it is first introduced in the code.

### LINKED ISSUE #30345: No mention of concatenation in std::string::String docs
In the documentation for [std::string::String](http://doc.rust-lang.org/nightly/std/string/struct.String.html), there is no mention of concatenation - it's not obvious that the `+` operator is used for concatenation, nor that it is restricted to `String + &str`, and not, eg. `String + String`.

There should be an example showing how to concatenate/format the different string types, or, at the very least, a mention of the word 'concatenate', to allow easy searching.

### LINKED ISSUE #30471: Expected result of 'Dining Philosophers' example is not possible by following the instructions
I see that the delay between picking up the forks was added later and I think the end of the instructions hasn't been updated to fit.

The text at the end says "With this, our program works! Only two philosophers can eat at any one time, and so you’ll get some output like this:" with a trace showing 2 philosophers eating at a time.

What we actually get is:
````
Emma Goldman is eating.
Emma Goldman is done eating.
Karl Marx is eating.
Karl Marx is done eating.
Gilles Deleuze is eating.
Gilles Deleuze is done eating.
Judith Butler is eating.
Judith Butler is done eating.
Michael Foucault is eating.
Michael Foucault is done eating.
````

With the 150ms delay between picking up forks, when the philosophers go to pick up their second forks, only fork 4 is available - so Emma Goldman can eat, when she finishes Karl Marx can use fork 3.

Without the 150ms delay the behaviour matches the description, with 2 eating at a time.

### PR DESCRIPTION
**Pull request by steveklabnik**
Some history:

While getting Rust to 1.0, it was a struggle to keep the book in a
working state. I had always wanted a certain kind of TOC, but couldn't
quite get it there.

At the 11th hour, I wrote up "Rust inside other langauges" and "Dining
Philosophers" in an attempt to get the book in the direction I wanted to
go. They were fine, but not my best work. I wanted to further expand
this section, but it's just never going to end up happening. We're doing
the second draft of the book now, and these sections are basically gone
already.

Here's the issues with these two sections, and removing them just fixes
it all:

// Philosophers

There was always controversy over which ones were chosen, and why. This
is kind of a perpetual bikeshed, but it comes up every once in a while.

The implementation was originally supposed to show off channels, but
never did, due to time constraints. Months later, I still haven't
re-written it to use them.

People get different results and assume that means they're wrong, rather
than the non-determinism inherent in concurrency. Platform differences
aggrivate this, as does the exact amount of sleeping and printing.

// Rust Inside Other Languages

This section is wonderful, and shows off a strength of Rust. However,
it's not clear what qualifies a language to be in this section. And I'm
not sure how tracking a ton of other languages is gonna work, into the
future; we can't test _anything_ in this section, so it's prone to
bitrot.

By removing this section, and making the Guessing Game an initial
tutorial, we will move this version of the book closer to the future
version, and just eliminate all of these questions.

In addition, this also solves the 'split-brained'-ness of having two
paths, which has endlessly confused people in the past.

I'm sad to see these sections go, but I think it's for the best.

Fixes #30471
Fixes #30163
Fixes #30162
Fixes #25488
Fixes #30345
Fixes #29590
Fixes #28713
Fixes #28915

And probably others. This lengthy list alone is enough to show that
these should have been removed.

RIP.

### CODE REVIEW

**Comment by Gankro** [comment]
GET WRECKED

@bors r+ rollup

**Comment by chrisccerami** [comment]
Sad to see content like this disappear, but :+1: for the reasons.

**Comment by cmr** [comment]
@steveklabnik I don't think this closes https://github.com/rust-lang/rust/issues/29590 ?

**Comment by steveklabnik** [comment]
@cmr ugh, i must have typo'd the number :(

**Comment by chriskrycho** [comment]
@steveklabnik any chance you'll republish these elsewhere? The Dining Philosophers implementation hurt my head, and I can't disagree with the decision here, but it ultimately hurt my head in a *good* way and it helped me think about concurrency issues not only in Rust but in general in a helpful way. I'd hate to see it just vanish into the æther.

**Comment by steveklabnik** [comment]
Yeah I will republish on my blog and link here 👍

**Comment by Gankro** [comment]
> Yeah I will republish on my blog and link here 

Steve, this is stealing intellectual property from the Rust project. I cannot in good conscience allow this, and will be contacting Mozilla's legal department should you attempt to go any further. Cease and desist.

Regards, Alexis

**Comment by chriskrycho** [comment]
@Gankro: the book content presently falls under the MIT or Apache license, as the user prefers. Both allow for someone to republish any part of the software, including its documentation, as long as they cite the original source and include the license.

(Should tutorial/book content, like the artwork, should be under CCByAt instead?)

**Comment by ollie27** [comment]
I assume this wasn't supposed to close #30345 and #29590.

**Comment by steveklabnik** [comment]
Wow, apparently i typod a bunch of issue numbers :( Thanks @ollie27 re-opened.

**Pull request merged**
