### PR TITLE
Mark doc examples w/ `extern` blocks as `ignore`.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/48218.

### CODE REVIEW

**Comment by kennytm** [comment]
Could we hide the “run” button, or insert a `#![crate_type="lib"]` when sending to playground when a code block is marked as ` ```no_run `, instead of ignoring the tests?

**Comment by steveklabnik** [comment]
> Could we hide the “run” button, or insert a #![crate_type="lib"] when sending to playground when a code block is marked as ```no_run, instead of ignoring the tests?

This sounds like a separate request; we do hide the `run` button for `ignore` already... maybe open an issue?

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks!

**Pull request merged**
