### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
Biweekly Clippy update

r? @Manishearth

### CODE REVIEW

**Comment by flip1995** [comment]
@bors r-

For some reason, there is a ICE in a test :thinking:

**Comment by flip1995** [comment]
Test pass locally for me. I would wait for CI tools builder before r+ing though.

**Comment by flip1995** [comment]
No idea what these ICEs are about. I won't be able to address this tonight, though.

**Comment by flip1995** [comment]
@Manishearth 99b9459 fixed the ICE, but I'm not sure if the fix is correct. This ICE occurred, because of this debug assertion: https://github.com/rust-lang/rust/blob/c643dd2ec8fed2852f5eee8f776d657293a6a8f2/compiler/rustc_middle/src/ty/mod.rs#L1455

**Comment by Manishearth** [comment]
cc @oli-obk @eddyb on the ICE

Idk what's going on there yeah. We should still merge this though and maybe file a follow-up

**Comment by oli-obk** [comment]
@bors r+

I'm trying to understand the issue, but the fix is conservative enough to definitely not make any problems, so let's merge this

**Pull request merged**
