### PR TITLE
[WIP] Use buffered aHash as StableHasher

### PR DESCRIPTION
**Pull request by Zoxc**
cc @tkaitchuck

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Is this hash function documented anywhere? Does it provide roughly the same collision probability as a random function? Are its results platform independent?

Some previous discussion on which hash function to use: https://github.com/rust-lang/rust/issues/41215

**Comment by Zoxc** [comment]
I just aimed for a simpler question? Is it faster? Local testing says no, at least with the buffering scheme and runtime AES instruction detection used here.

**Comment by michaelwoerister** [comment]
> I just aimed for a simpler question? Is it faster?

Yes, I'm always interested in numbers there `:)`

Although ideally, it would be great to get rid of hashing altogether in the long run: https://github.com/rust-lang/rust/issues/58155

**Comment by tkaitchuck** [comment]
@michaelwoerister You can see the documentation here: https://github.com/tkaitchuck/ahash
It is certainly intended to be of high quality. It is certainly a higher quality hash than FxHash, but it cannot out perform it on primitive types, where FxHash will be reduced to a single multiply instruction. A more relevant comparison is SipHash-1-3 where I believe aHash to be both faster and of higher quality.

**Comment by michaelwoerister** [comment]
@tkaitchuck That looks pretty neat! I don't think it's a good fit for the `StableHasher` though because we need platform independent results.

**Comment by Zoxc** [comment]
@michaelwoerister I don't see a reason for why we need platform independent results (at least for incremental compilation hashes), but a software fallback producing the same result is always possible.

**Comment by michaelwoerister** [comment]
The `StableHasher` is also used for symbol names and type-id. IIRC, we've had problems in the past where platform-dependent hashing would lead to linker errors when cross-compiling.

**Comment by tkaitchuck** [comment]
Ok. Sounds like this isn't the right fit.

**Pull request closed without merging**
