### PR TITLE
Rustdoc: render implementations for type aliases

### PR DESCRIPTION
**Pull request by gkoz**
For typedefs render items implemented for the type under both new and old names.
Fixes (very narrowly) #19381.

### CODE REVIEW

**Comment by gkoz** [comment]
I'm going to need help adding a test case.

**Comment by Gankro** [comment]
Would it be possible to post screenshots, and/or host a live instance with this change?

**Comment by gkoz** [comment]
[Rendered `libstd` docs](http://gkoz.github.io/pr-25892/675e0189/std/).

**Comment by bluss** [comment]
The bug you linked is a different issue I think.

**Comment by gkoz** [comment]
What was I thinking... It fixes half of that bug not the 'Implementors' part.

**Comment by alexcrichton** [comment]
Yes I agree with @bluss that I don't think this quite fixes #19381, and I'm also not sure if we want to take this route just yet due to #14072. For example on the documentation page for `io::Result` the parameter `E` is generic instead of being wired up to `Error`.

I suppose it's also somewhat unclear to me what the motivation for this is because finding the documentation of the typedef itself should just be following a link.

**Comment by leighmcculloch** [comment]
@alexcrichton What would need to change about this fix to make it more suitable? It looks like this would address #32077.

**Pull request closed without merging**
