### PR TITLE
pass `CODEGEN_BACKENDS` to docker

### PR DESCRIPTION
**Pull request by lqd**
The backends to build are now defined in the `CODEGEN_BACKENDS` env var. It's correctly set in CI, but wasn't passed to docker, hence cg_clif wasn't actually built in #81746.

r? @Kobzol: I locally tried `CODEGEN_BACKENDS="cranelift" DEPLOY=1 src/ci/docker/run.sh dist-x86_64-linux` and this change was enough for `ci/run.sh` to read the env var. 

So I'll try as-is and we'll see.

### CODE REVIEW

**Comment by lqd** [comment]
(The logs show the cg_clif backend as being built this time)

**Comment by lqd** [comment]
It's starting to look good IMHO. I'll mark this "ready to review" if jakub wants to take a look, but I will still look for the PR builder and test the try build component when/if it's available.

**Comment by lqd** [comment]
Looking good on the PR builder as well: https://github.com/rust-lang/rust/actions/runs/6678763598/job/18150159767?pr=117328#step:25:113

**Comment by lqd** [comment]
```
$ rustup-toolchain-install-master 72df36e74f2c2df78b3e8802b13aa34540bbf7a2 -c rustc-codegen-cranelift && CARGO_PROFILE_DEV_CODEGEN_BACKEND=cranelift cargo +72df36e74f2c2df78b3e8802b13aa34540bbf7a2 run
toolchain `72df36e74f2c2df78b3e8802b13aa34540bbf7a2` is successfully installed!
   Compiling helloworld v0.1.0 (/home/lqd/rust/helloworld)
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/helloworld`
Hello, world!
```

**Comment by Mark-Simulacrum** [comment]
r=me

**Comment by workingjubilee** [comment]
Failed in https://github.com/rust-lang/rust/pull/117339
> assertion failed: found_backend

@bors rollup=iffy

**Comment by lqd** [comment]
Looking good on the `aarch64-unknown-linux-gnu` try build.

```console
$ rustup-toolchain-install-master 7eabc25b9882e573a7a81b44939d5699fdd54cbb -c rustc-codegen-cranelift --host aarch64-unknown-linux-gnu && find ~/.rustup/toolchains/7eabc25b9882e573a7a81b44939d5699fdd54cbb -name "*cranelift*.so"
/home/lqd/.rustup/toolchains/7eabc25b9882e573a7a81b44939d5699fdd54cbb/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_cranelift-1.75.0-nightly.so
```

The commit added since the review (f656accdf534bc58a021e2d7f04bf5900e2ba8ad) is a trivial dry-run bugfix over #81746, and doesn't IMO need re-review.

@bors r=Mark-Simulacrum

**Comment by workingjubilee** [comment]
Looks good.

**Comment by RalfJung** [comment]
Unfortunately, this caused https://github.com/rust-lang/rust/issues/117430 (probably surfacing some pre-existing issue in how docs generation interacts with codegen backend builds), so it is being reverted in https://github.com/rust-lang/rust/pull/117535.

**Pull request merged**
