### PR TITLE
Apply clippy::uninlined_format_args fixes

### PR DESCRIPTION
**Pull request by nyurik**
This is the result of running `clippy::uninlined_format_args` lint. Currently the lint is in `pedantic`, but there are plans/hopes to move it to `style`.

How can I add this specific lint to the current build/CI tools, or is this not possible?  It would be ideal not to make the lint as the default style and then end up with hundreds of changes in an unrelated PR due to CI requirements.

Locally, I ran this to generate the changes.  Not ideal because it has produced a number of compilation errors.

```bash
rustup run nightly cargo clippy --fix --no-deps --allow-dirty -- -A clippy::all -W clippy::uninlined_format_args
```

### CODE REVIEW

**Comment by jyn514** [comment]
This is not a good idea. It creates a lot of churn, has dubious benefit, and we have a policy of not enforcing clippy lints; if they're important enough to be gated in CI, the lints should be part of rustc proper.

> How can I add this specific lint to the current build/CI tools, or is this not possible

There isn't a way; x.py clippy isn't officially supported.

**Comment by nyurik** [comment]
@jyn514 , I didn't know about the policy, thanks for the explanation :)

**Comment by est31** [comment]
I think in the past, pull requests to fix clippy lints have been accepted, at least to `compiler/`. `library/` has a much stricter policy to not allow clippy fixes. IDK what the policy is for `src/bootstrap`. I do think that this PR is improving code, just as #100589 has improved code, not from the "fix clippy" side of things but because inline format args feel nicer to me. That being said, this PR should not be merged in the current form: subtrees should only be modified if there is a pressing reason to modify them from rustc's side, e.g. build failures, and submodules should be modified even more rarely. So those two categories should be excluded, in addition to changes to `library/`. Instead you can make changes to the places where they are maintained canonically, if you want. Subtrees are clippy, miri, as well as the non-llvm codegen backends (correct me if I'm wrong). This would increase your chances of being merged I think :).

Also btw `x.py clippy` uses clippy from beta, so this lint that currently only exists on nightly won't appear there.

Last, there is conflict potential when it comes to error due to the ongoing migration to translatable error messages. In many ways I think the new API can be improved (structs are bad design IMO), but there are still PRs open to migrate away from `format!()` usage to fluent. Thus I think it would be better to exclude error messages from possible future PRs. Maybe even wait with compiler/ changes until the migration is over, idk.

**Comment by jyn514** [comment]
> I think in the past, pull requests to fix clippy lints have been accepted, at least to compiler/. 

Yes, but they've been accepted on their own merit, not because they fix a lint. I don't think these changes stand on their own; if nothing else the churn is a massive pain to review, and it makes git blame less useful in the future.

Put another way, I think it's fine to discover issues because of a lint, but not to decide they're an issue in the first place because of a lint.

**Comment by nyurik** [comment]
@jyn514 I think "code is easier to read" is a benefit in of itself. Granted that it should be trivial to review, and this PR is clearly too messy to merge (my bad).  Assuming it *is* easier to read after the cleanup, I think it would be good to start a slow process of cleaning up the code, one easy-to-review chunk at a time.

**Pull request closed without merging**
