### PR TITLE
add rustc std workspace crate sources

### PR DESCRIPTION
**Pull request by RalfJung**
This adds the sources for the crates listed at https://crates.io/search?q=rustc-std-workspace in this repo. The first commit adds the original sources as downloaded from crates.io (with `Cargo.toml.orig` moved back over `Cargo.toml`), and adds a README explaining what this is about. The 2nd commit updates the sources to make the core and alloc crates re-exports of the "actual" core and alloc crates, as was already the case with `std`, and also adds a `repository` link to the manifest so one can figure out where to find these crates.

I bumped the version for the core and alloc crates in the hope that the new versions can be published on crates.io shortly after this PR lands.

See [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/219381-t-libs/topic/rustc-std-workspace-core.20crate.20is.20empty) for a bit more context.

r? @Amanieu

### CODE REVIEW

**Comment by RalfJung** [comment]
tidy insists on the edition being 2021 or 2024... oh well. I guess the MSRV does not actually matter for these crates.

**Comment by Amanieu** [comment]
This should be directly in src, not under tools since it isn't actually a tool binary.

Also the README for the library/ version should point to this as the crates.io version.

**Comment by RalfJung** [comment]
> This should be directly in src, not under tools since it isn't actually a tool binary.

Done.

> Also the README for the library/ version should point to this as the crates.io version.

Done.

**Pull request merged**
