### PR TITLE
Rename `*.node` to `*.kind`, and `hair::Pattern*` to `hair::Pat*`

### PR DESCRIPTION
**Pull request by varkor**
In both `ast::Expr` and `hir::Expr`:

- Rename `Expr.node` to `Expr.kind`.
- Rename `Pat.node` to `Pat.kind`.
- Rename `ImplItem.node` to `ImplItem.kind`.
- Rename `Lit.node` to `Lit.kind`.
- Rename `TraitItem.node` to `TraitItem.kind`.
- Rename `Ty.node` to `Ty.kind`.
- Rename `Stmt.node` to `Stmt.kind`.
- Rename `Item.node` to `Item.kind`.
- Rename `ForeignItem.node` to `ForeignItem.kind`.
- Rename `MetaItem.node` to `MetaItem.kind`.

Also:
- Rename `hair::FieldPattern` to `hair::FieldPat`.
- Rename `hair::PatternKind` to `hair::PatKind`.
- Rename `hair::PatternRange` to `hair::PatRange`.
- Rename `PatternContext` to `PatCtxt`.
- Rename `PatternTypeProjection` to `PatTyProj`.
- Rename `hair::Pattern` to `hair::Pat`.

These two sets of changes are grouped together to aid with merging. The only changes are renamings.

r? @petrochenkov

### CODE REVIEW

**Comment by varkor** [comment]
The first two commits are from https://github.com/rust-lang/rust/pull/64515, but that should be merged soon.

**Comment by Centril** [comment]
Did you check HAIR as well?

**Comment by Centril** [comment]
Also it might be easier to merge this if you split it into several PRs (e.g. one for AST, one for HIR, ...).

**Comment by varkor** [comment]
I'm renaming anything with the same name, so it's easiest to target AST and HIR at once (and HAIR if it has the same names). It'll be more difficult to merge, but I figure it's easier to merge one conflict-prone PR than several.

**Comment by Centril** [comment]
The advantage of several smaller PRs is that I can make rollups with them -- and because you would be  touching different parts of the compiler, you're unlikely to cause conflicts several times in one PR.

**Comment by Centril** [comment]
Some more refactoring required (just r=me as you fix these...)

@bors r-

**Pull request merged**
