### PR TITLE
Deallocate ThinBox even if the value unwinds on drop

### PR DESCRIPTION
**Pull request by LegionMammal978**
This makes it match the behavior of an ordinary `Box`.

### CODE REVIEW

**Comment by LegionMammal978** [comment]
I've noticed that `Rc<T>` and `Arc<T>` also leak their allocations (by not decrementing the shared weak count) if `drop_in_place()` unwinds. Is there some perf or soundness reason behind this, or is it also unintentional?

**Comment by Amanieu** [comment]
Panics in drop are known to leak memory in all sorts of places since it's so hard to handle them reliably. Hence my attempt in https://github.com/rust-lang/rfcs/pull/3288 to make panics in drop always abort.

**Comment by LegionMammal978** [comment]
The only place they can leak memory is with types with custom `Drop` impls. I've looked through all the stdlib heap containers: for the most part, we're very careful about correctly proceeding after a panic. Only the types imported from external crates (`mpsc` channels, `HashMap<K, V, S>`, `HashSet<T, S>`, and related types) fail to drop remaining elements after a panic, and only those as well as `ThinBox<T>` (before this PR), `Rc<T>`, and `Arc<T>` fail to deallocate the backing memory. The unstable `DrainFilter` types are inconsistent as to whether they continue draining, but they [already have issues](https://github.com/rust-lang/libs-team/issues/136) with panicking closures, so I'm not very surprised. Apart from those, all types use a drop guard and/or delegate to operations like `drop_in_place::<[T]>()` which correctly handle panics.

(And my position on silently changing the stable behavior of `Drop` hasn't changed since you proposed it.)

**Pull request merged**
