### PR TITLE
coverage: Don't instrument `#[automatically_derived]` functions

### LINKED ISSUE #105055: Code coverage showing [derive(Debug)] as missed region
I tried this code:

```rust
#[derive(PartialEq, Debug)]
pub enum EnumCov{
    First,
    Second,
    Third,
    Fourth
}



#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cov() {
        let one = EnumCov::First;
        let two = EnumCov::Second;
        let three = EnumCov::Third;
        let four = EnumCov::Fourth;

        assert_eq!(one, EnumCov::First);
        assert_eq!(two, EnumCov::Second);
        assert_eq!(three, EnumCov::Third);
        assert_eq!(four, EnumCov::Fourth);
    }
}
```
Running these commands to get the code coverage report
```bash
cargo llvm-cov --html
```
Same issue with `RUSTFLAGS="-C instrument-coverage" cargo test --tests` merge/report/show

I expected to see this happen: coverage 100%

Instead, this happened: Debug is shown as missed region
image

It's quite the same as https://github.com/rust-lang/rust/issues/83601 

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)

binary: rustc

commit-hash: 897e37553bba8b42751c67658967889d11ecd120

commit-date: 2022-11-02

host: x86_64-unknown-linux-gnu

release: 1.65.0

LLVM version: 15.0.0


```

Backtrace not applicable.

Thanks!

### PR DESCRIPTION
**Pull request by Zalathar**
This PR makes the coverage instrumentor detect and skip functions that have [`#[automatically_derived]`](https://doc.rust-lang.org/reference/attributes/derive.html#the-automatically_derived-attribute) on their enclosing impl block.

Most notably, this means that methods generated by built-in derives (e.g. `Clone`, `Debug`, `PartialEq`) are now ignored by coverage instrumentation, and won't appear as executed or not-executed in coverage reports.

This is a noticeable change in user-visible behaviour, but overall I think it's a net improvement. For example, we've had a few user requests for this sort of change (e.g. #105055, https://github.com/rust-lang/rust/issues/84605#issuecomment-1902069040), and I believe it's the behaviour that most users will expect/prefer by default.

It's possible to imagine situations where users would want to instrument these derived implementations, but I think it's OK to treat that as an opportunity to consider adding more fine-grained option flags to control the details of coverage instrumentation, while leaving this new behaviour as the default.

(Also note that while `-Cinstrument-coverage` is a stable feature, the exact details of coverage instrumentation are allowed to change. So we *can* make this change; the main question is whether we *should*.)

Fixes #105055.

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
I agree that skipping these is a much better default behavior.

If users want these derives to be instrumented, they can implement them manually. Which btw is trivial as rust-analyzer will auto-generate all of the inner derive code automatically.

**Comment by oli-obk** [comment]
@bors r+ rollup

If it becomes an issue we can make it configurable

**Comment by Zalathar** [comment]
Ugh, failed in rollup because I forgot to bless the separate `coverage-run-rustdoc` suite (again).

**Comment by Zalathar** [comment]
Rebased and re-blessed; no functional changes since last review.

@rustbot ready

**Comment by matthiaskrgr** [comment]
@bors r- 
may have failed in https://github.com/rust-lang/rust/pull/120209#issuecomment-1902795635 ?

**Comment by Zalathar** [comment]
@matthiaskrgr Yes, I noticed this earlier today and have already pushed a fix, so this PR is ready to merge again in its current state.

**Review by wesleywiser — APPROVED** [review]

**Pull request merged**
