### PR TITLE
Remove `is` postfix in Reference → Numbers

### PR DESCRIPTION
**Pull request by nagisa**
r? @steveklabnik

### CODE REVIEW

**Comment by alfie** [comment]
If you're removing suffixes from the table, perhaps remove the "Suffixes" column as well since it no longer makes sense.

**Comment by nagisa** [comment]
It still tells what category of suffixes may be used with a particular type of literal, no?

**Comment by alfie** [comment]
@nagisa ahh of course, you're right. Keep them there :)

**Pull request merged**
