### PR TITLE
Implement more traits for `std::io::ErrorKind`

### PR DESCRIPTION
**Pull request by tbu-**
This makes it possible to use it as key in various maps.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you expand on the motivation of being able to use in various maps as well? One specific aspect here was to reorder the enum, and it seems like we would want to provide zero guarantees about the ordering of this enum.

**Comment by tbu-** [comment]
I write a tool that operates on a large number of files, and it tries to display an error summary at the end. Currently, I have an almost-exact mirror of the `ErrorKind` enum in the code in order to be able to put it into a `HashMap`.

Do we guarantee that the ordering stays the same for types that derive ordering? I don't think that's all too useful, because we also don't want to guarantee the ordering for other enums where you can obtain it by casting it to an integer (`e1 as u32 < e2 as u32`). Maybe we need to have some kind of discussion about that.

**Comment by Stebalien** [comment]
(IMO, these methods should all panic when called on `__NonExhaustive` as a sanity check but that's probably not too important given that it's unstable).

**Comment by ollie27** [comment]
If we're not supposed to have any guarantees about the ordering of this enum then it probably shouldn't be a C-Like enum. We're currently exposing an ordering: `assert!((ErrorKind::Other as isize) < (ErrorKind::UnexpectedEof as isize))`.

**Comment by Stebalien** [comment]
@ollie27 (that also means that this change *cannot* reorder fields without being a breaking change).

**Comment by tbu-** [comment]
@Stebalien I don't think we consider that a breaking change, see e.g. #25246 or rust-lang/rfcs#906. It doesn't realistically break any code.

**Comment by sfackler** [comment]
I don't really see why we'd *want* to reorder these variants?

**Comment by tbu-** [comment]
Just for consistency I guess, but I can remove that part. I thought `Other` at the end made the most sense and it was the case until `UnexpectedEof` was added.

**Comment by tbu-** [comment]
To clarify, this was ment as a drive-by fix, not part of the whole pull request. I restored the old ordering because apparantly this is not a tiny change.

**Pull request merged**
