### PR TITLE
Smaller refactor svh

### PR DESCRIPTION
**Pull request by richo**
This is the first half of the implementation of what I set out to do in #26629.

This will make the location of attrs in crates not affect their hash values any more, although it doesn't expose a public way to do this outside of an entire Svh yet, which is how I intended to implement the dupe attribute lint.

For posterity, I did the yolo science with: https://gist.github.com/richo/f750855a762804e2b3e9

r? @alexcrichton 

Ping #14132

### CODE REVIEW

**Comment by richo** [comment]
(The assertion that this closes #14132 was based on yolo-science™, updated to reflect that)

**Comment by richo** [comment]
@brson you'll need to r-, I ran make check overnight and it breaks some svh tests (in the same way that my other changes did, it's upset about the crates hashes changing)

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to send a new PR with tests fixed!

**Pull request closed without merging**
