### PR TITLE
Implement Poll:ready() (see tracking issue #72992)

### PR DESCRIPTION
**Pull request by djc**
This is analogous to `Result::ok()` and makes for a nice entry point to `Option`s combinators.

### CODE REVIEW

**Comment by djc** [comment]
@LukasKalbertodt ping?

**Comment by oli-obk** [comment]
r? @oli-obk 

Please add some tests showcasing the use of this function.

**Comment by oli-obk** [comment]
Maybe in https://github.com/rust-lang/rust/tree/master/src/test/ui/async-await ?

**Comment by JohnCSimon** [comment]
ping from triage 
@djc can you please address the comment from oli-obk?

**Comment by crlf0710** [comment]
Hi, i'm closing this due to inactivity. Feel free to reopen or open a fresh PR when you want to pick up this again. Thanks!

**Pull request closed without merging**
