### PR TITLE
Don't recommend ManuallyDrop to customize drop order

### PR DESCRIPTION
**Pull request by matklad**
See
https://internals.rust-lang.org/t/need-for-controlling-drop-order-of-fields/12914/21
for the discussion.

TL;DR: ManuallyDrop is unsafe and footguny, but you can just ask the compiler to do all the work for you by re-ordering declarations.

Specifically, the original example from the docs is much better written as 

```rust
struct Peach;
struct Banana;
struct Melon;
struct FruitBox {
    melon: Melon,
    // XXX: mind the relative drop order of the fields below
    peach: Peach,
    banana: Banana,
}
```

### CODE REVIEW

**Comment by withoutboats** [comment]
I agree with this change to the guideline. I don't know if these docs date to before we had agreed to define the drop order or not.

I would like the documentation to briefly explain the defined drop order of struct fields, though, and maybe the code sample using that to get a certain drop order. I know its contained in the associated link, but it would make the documentation clearer here.

**Comment by matklad** [comment]
Yeah, that would be helpful, included an example!

**Comment by RalfJung** [comment]
r=me unless you want another review.

**Comment by vojtechkral** [comment]
Reminder: Rustonomicon (still?) [advises exactly the other way around](https://doc.rust-lang.org/nomicon/dropck.html#a-related-side-note-about-drop-order) :slightly_smiling_face:

**Pull request merged**
