### PR TITLE
Improve documentation for libcollections/str

### PR DESCRIPTION
**Pull request by steveklabnik**

### CODE REVIEW

**Comment by brson** [comment]
r=me

**Comment by steveklabnik** [comment]
@brson, seems legit. change made

**Comment by oli-obk** [comment]
why were all the 
```
```rust
```
tags removed? now https://github.com/rust-lang/rust/pull/22513/files#diff-2544e5e5ce71797344d5ec6acde08b87R1074 is an invalid example, and I thought the doc tests were made to catch that. (patch for that particular one incoming)

**Comment by steveklabnik** [comment]
Because it defaults to Rust, and so there's no need to annotate it. Current style is to use the annotation in long form docs (so it renders on github) and not use it in API docs (because it is redundant)

**Comment by oli-obk** [comment]
thanks

**Pull request merged**
