### PR TITLE
sparc64-linux support

### PR DESCRIPTION
**Pull request by japaric**
This is built on top of #38656 and depends on rust-lang/libc#483

Hello world works.

The libc-test test suite passes.

`panic!` doesn't fully work:

```
$ qemu-sparc64-static ./panic
thread 'main' panicked at 'explicit panic', panic.rs:1
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Illegal instruction (core dumped)
```

Backtraces don't work either, probably related to the previous point:

```
$ export RUST_BACKTRACE=1
$ qemu-sparc64-static ./panic
thread 'main' panicked at 'explicit panic', panic.rs:1
stack backtrace:
Illegal instruction (core dumped)
```

r? @alexcrichton 

@jakllsch Does panicking / backtraces work on sparc64-netbsd?

cc @glaubitz

### CODE REVIEW

**Comment by glaubitz** [comment]
@japaric If you rather want to debug on a real machine than on qemu, let me know. If you like, please join us in #sparc on Freenode.

**Comment by jrtc27** [comment]
At a glance, the C ABI seems wrong; small structs are passed in and returned in registers.

**Comment by jakllsch** [comment]
@japaric Yes, backtrace of `fn main() { println!("Goodbye World!"); panic!(); }` produces an identical backtrace (with RUST_BACKTRACE=1) on NetBSD/amd64 and NetBSD/sparc64 (excepting differences in addresses within the .text segment) with #38656.  Had to use `-C linker=sparc64--netbsd-gcc` (the same wrapper gcc-rs points the rustbuild at) in addition to `--target sparc64-unknown-netbsd` to get it to cross link.

**Comment by jakllsch** [comment]
@jrtc27 It's very possible `cabi_sparc64` is almost completely wrong, it's mostly a copy/paste of `cabi_powerpc64` in #38656.  However, it was enough to get a cross-compiled `rustc` to output its usage message on a NetBSD/sparc64 host.  It did not succeed in actually compiling anything due to some unnaturally-aligned access faults, which I decided to postpone much investigation of while I got this upstreamed.

**Comment by alexcrichton** [comment]
This seems good to me, thanks @japaric!

I'm perpetually worried about all this cabi business though. It seems no one really knows what they're doing around the cabi modules and I'm reading "hello world works" as "someone's going to waste hours of their life later fixing an abi-related bug"

**Comment by sanxiyn** [comment]
@bors retry

Network failure.

**Pull request merged**
