### PR TITLE
Replace all def_id_no_primitives with def_id

### LINKED ISSUE #90187: rustdoc: Replace all remaining uses of `Type::def_id_no_primitives()` with `Type::def_id()`
### Steps

1. Pass `&Cache` where it will be needed for `def_id()`.
1. Replace all uses of `def_id_no_primitives()` with `def_id()`.
2. Remove `def_id_no_primitives()` and simplify `Type::inner_def_id()`.

### PR DESCRIPTION
**Pull request by zredb**
try to fix #90187 again.
r? @GuillaumeGomez

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by zredb** [comment]
but I don't known why the test is failed.

**Comment by camelid** [comment]
rust-lang/rust follows a ["No-Merge Policy"](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy). Could you please [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts) over upstream changes instead of merging? Thanks!

**Comment by camelid** [comment]
Also, please squash your commits too using `git reset --soft HEAD~ && git commit --amend --no-edit` :)

**Comment by camelid** [comment]
Sorry, I don't have time to review this. Please rebase though.

r? @GuillaumeGomez

**Pull request closed without merging**
