### PR TITLE
Add fmt::Write to io::Write adapter

### LINKED ISSUE #77733: Add a blanket impl for `core::fmt::Write` if there is an impl for `std::io::Write`
### Advantages

Types which implement `std::io::Write` get an implementation of `core::fmt::Write` for free. `core::fmt::Write` is useful if you only want to accept UTF-8 data.

### Disadvantages

Could it hurt type inference? If so, is there some way of allowing `impl core::fmt::Write for Foo {}` (i.e., empty impl body) if there is an impl for `std::io::Write`?

---

Cc raphlinus/pulldown-cmark#492

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Closes https://github.com/rust-lang/rust/issues/77733

ACP: https://github.com/rust-lang/libs-team/issues/133

### CODE REVIEW

**Comment by thomcc** [comment]
This needs an ACP

**Comment by SUPERCILEX** [comment]
@thomcc Done: https://github.com/rust-lang/libs-team/issues/133

**Comment by thomcc** [comment]
Re-adding waiting-on-ACP since I can't do anything with it and it's in my review queue otherwise.

**Comment by SUPERCILEX** [comment]
I no longer think this is the appropriate implementation, though I still want composability between writeable traits. In the meantime, I've created this crate: https://docs.rs/io-adapters/latest

**Pull request closed without merging**
