### PR TITLE
pattern_analysis: cleanup manual impls

### PR DESCRIPTION
**Pull request by Nadrieril**
https://github.com/rust-lang/rust/pull/120420 introduced some unneeded manual impls. I remove them here.

r? @Nilstrieb

### CODE REVIEW

**Review by compiler-errors — COMMENTED** [review]
lol these are only `Derive`able bc `RustMatchCheckCtxt` derives `Debug`. Do we implicitly want to require implementors of `TypeCx` (that trait has a really strange name, btw, lol) to have to derive `Debug` 🤔 ?

**Comment by compiler-errors** [comment]
Well there's exactly 0 relevant info being printed currently 😆.

If you want to take advantage of this, could you make sure `Debug` is a supertrait bound on `TypeCx`? It moves the errors that users get from the derived bounds a bit earlier in the usage of the library.

**Comment by compiler-errors** [comment]
oh lol it is

@bors r+

**Comment by Nadrieril** [comment]
Yeah, it's been a supertrait from the start, unsure why I added it in the first place but :shrug:

**Comment by compiler-errors** [comment]
I assume it was there because of some `derive` bounds lol

**Comment by Nadrieril** [comment]
Lol probably, I think I even added `Clone` at some point for that x)

**Pull request merged**
