### PR TITLE
Add bootstrap support for android

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by aidanhs** [comment]
Thanks for the PR @malbarbo! We'll make sure @brson or another reviewer gets to your PR soon.

**Comment by parched** [comment]
What about aarch64?

**Comment by malbarbo** [comment]
@parched This should work for all rust supported android archs.

**Comment by parched** [comment]
Ah yes sorry, I see that now.

**Comment by Mark-Simulacrum** [comment]
Thanks for the PR! We'll make sure that @brson or someone else reviews your PR soon.

cc @alexcrichton, perhaps you could take a look at this?

Note: Did not ping @brson on IRC due to them not being present.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @malbarbo!

**Pull request merged**
