### PR TITLE
[rustdoc] Box ItemKind to reduce the size of `Item`

### PR DESCRIPTION
**Pull request by jyn514**
This brings the size of `Item` from

```
[src/librustdoc/lib.rs:103] std::mem::size_of::<Item>() = 536
```

to

```
[src/librustdoc/lib.rs:103] std::mem::size_of::<Item>() = 136
```

This is an alternative to https://github.com/rust-lang/rust/pull/79967; I don't think it makes sense to make both changes.

Helps with #79103.

### CODE REVIEW

**Comment by jyn514** [comment]
Up to -1.7% on instructions, up to -3.1% on max-rss. The RSS numbers for rustdoc seem to be less variable than for rustc for some reason.

**Comment by pnkfelix** [comment]
> Helps with #79103.

Is there a way you could measure *how much* it helps reduce the peak memory usage there?

**Comment by nnethercote** [comment]
Can you add a static assertion on the size to prevent future regressions? Something like this, which is a pattern used in various places in the compiler:
```
// `Item` is used a lot. Make sure it doesn't unintentionally get bigger.
#[cfg(target_arch = "x86_64")]
static_assert_size!(Item, 280);
```
r=me with that done.

Also, 280 bytes is still large. Most of the AST types in the compiler itself are less than 100 bytes. Which fields are big?

**Comment by jyn514** [comment]
@nnethercote you should have seen when I started, it was 784 bytes :laughing: https://github.com/rust-lang/rust/pull/79957#issue-537743465

This is all changing rather rapidly so I'm a little hesitant to put an assert since it will make rebasing harder. After rebasing over master the new change is from 616 to 216.

> Also, 280 bytes is still large. Most of the AST types in the compiler itself are less than 100 bytes. Which fields are big?

```
[src/librustdoc/lib.rs:103] std::mem::size_of::<Span>() = 8
[src/librustdoc/lib.rs:103] std::mem::size_of::<Option<rustc_span::Symbol>>() = 4
[src/librustdoc/lib.rs:103] std::mem::size_of::<Attributes>() = 96
[src/librustdoc/lib.rs:103] std::mem::size_of::<Visibility>() = 40
[src/librustdoc/lib.rs:103] std::mem::size_of::<Box<ItemKind>>() = 8
[src/librustdoc/lib.rs:103] std::mem::size_of::<DefId>() = 8
[src/librustdoc/lib.rs:103] std::mem::size_of::<Option<Stability>>() = 16
[src/librustdoc/lib.rs:103] std::mem::size_of::<Option<rustc_attr::Deprecation>>() = 16
[src/librustdoc/lib.rs:103] std::mem::size_of::<Option<ConstStability>>() = 20
```

So most of the size is coming from Attributes, Visibility, and (Stability, Deprecation, ConstStability). The last three are from rustc directly. A way I thought of to reduce that size is to calculate them on demand with something like

```rust
enum ItemId {
    Real(DefId),
    Fake(usize),
}
```

and then always return `None` for fake items. The issue with that is it requires passing a `TyCtxt` into render, which [I have code for](https://github.com/jyn514/rust/commit/a563ab7f80ed9186076dafd67c7e86d906d9697a), but is a pretty big invasive change.

I do not currently have ideas for reducing the size of Visibility or Attributes.

**Comment by jyn514** [comment]
> > Helps with #79103.
> 
> Is there a way you could measure _how much_ it helps reduce the peak memory usage there?

Measuring this (imprecisely, with `time -v`, but better than nothing) gives `Maximum resident set size (kbytes): 2060060` with this change and `Maximum resident set size (kbytes): 2096996` without. So there was an improvement of about 30 MB.

FYI, all of these measurements are done with `--features stm32h743`, which is the *smallest* set of features you can add and still compile stm32h7. There are a bunch of others I can add to slow it down.

**Comment by jyn514** [comment]
This now brings the size from 536 to 136.

**Comment by jyn514** [comment]
I added the static assertion.

@bors r=nnethercote

**Pull request merged**
