### PR TITLE
Include llvm-as in llvm-tools-preview component

### PR DESCRIPTION
**Pull request by zec**
Including `llvm-as` adds the ability to include assembly language fragments that can be inlined using LTO while making sure the correct version of LLVM is always used.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, can you say more about the use case here? How are you planning to run this tool?

**Comment by zec** [comment]
The use case that prompted this involves memory barriers on an ARM Cortex-M4 processor using (hopefully) stable Rust (so no inline assembly anytime soon). I'm paranoid about memory ordering when it comes to peripheral access, so I'd like to be able to use barrier instructions to ensure that certain sets of reads and writes occur before other sets. A barrier is one or two instructions, so calling external object code linked in whole seems excessive (otherwise, I'd just use `llc`), hence the desire to use LTO for inlining, which in turn implies needing something that takes source and outputs LLVM bitcode. I'd prefer to reduce the amount of coordination between different toolchains, so not having to depend on a distribution's LLVM being a compatible version seems desirable.

As for running the tool, I intend to do that from a build script using the [`llvm-tools`](https://crates.io/crates/llvm-tools) crate.

If this seems like a case where I'm committing a category error and this is better solved another way, be sure to let me know... I _think_ this is reasonable, but it is also outside my normal wheelhouse.

**Comment by Mark-Simulacrum** [comment]
I would guess that looking at the core::arch module might yield nicer looking code, I would expect most memory barrier instructions to be in there. The arm modules are currently unstable though.

I should also caution that as a preview component, the contents and availability of the llvm-tools component are not considered part of the stability promise.  There's also not really a guarantee that LLVM will indefinitely be the backend rustc uses.

That said, it seems not altogether different from the other use cases for these tools, so I'm going to go ahead and @bors r+.

**Comment by zec** [comment]
@Mark-Simulacrum Understood that this is trading off one sort of instability for another; I'm OK with that.

Thank you for reviewing this PR.

**Pull request merged**
