### PR TITLE
Update E0659 error code long explanation to 2018 edition

### LINKED ISSUE #65571: Outdated `--explain` examples for E0659 "An item usage is ambiguous."
See [E0659][1] for the current text.

[1]: https://github.com/rust-lang/rust/blob/518deda77feb4957bfd311b6cb50baa7ef9ca6a2/src/librustc_resolve/error_codes.rs#L1767

It includes the following example:

```
pub mod moon {
    pub fn foo() {}
}

pub mod earth {
    pub fn foo() {}
}

mod collider {
    pub use moon::*;
    pub use earth::*;
}

fn main() {
    collider::foo(); // ERROR: `foo` is ambiguous
}
```

which needs updating for Rust 2018: it needs `crate::` or `parent::` adding inside `mod collider`.

The same is true in the recommended replacement.

### LINKED ISSUE #65577: Rust 1.38 regressions weren't fully triaged
A crater run was performed for Rust 1.38 and the digest of regressions is available in https://github.com/rust-lang/rust/issues/63628#issuecomment-524584111.

The problem is that all regressions starting from "cannot use `state` because it was mutably borrowed" and below weren't analyzed.
It is too late to fix 1.38 now because it was released several weeks ago, but it's still useful to know what we regressed (there are >100 non-root regressions), some of those errors can be caused by legitimate bugs.

Triage is required mostly from people responsible for the rustc's middle-end (type checking and below).
cc @rust-lang/compiler

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #65571

r? @Centril

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
damn.. 

r? @Dylan-DPC

**Comment by JohnTitor** [comment]
@GuillaumeGomez I think the issue number we should close is #65571, not #65577.

**Comment by GuillaumeGomez** [comment]
@JohnTitor Absolutely! Good catch! I updated the comment.

**Pull request merged**
