### PR TITLE
Return `Option<ErrorGuaranteed>` from `lint_level_impl`.

### PR DESCRIPTION
**Pull request by nnethercote**
`lint_level_impl` emits a lint that may be an error or a non-error, depending on the setting. By introducing `impl EmissionGuarantee for Option<ErrorGuaranteed>`, we can express this in the type system via its return value, and the return value of many other linting functions built on top of `lint_level_impl`.

In `increment_const_eval_counter`, this lets us avoid a `span_delayed_bug` for an error lint. (Avoiding this was the motivation for this change.)

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
cc @oli-obk @lcnr @compiler-errors @estebank 

I'm honestly not sure if this is worth it. Avoiding the `span_delayed_bug` is nice, but it's a lot of changes just for that. Thoughts?

**Comment by oli-obk** [comment]
Yea, I've wanted this several times before, but didn't pursue it because

* lots of churn
* kinda wrong to hide follow-up errors just because a lint was denied, this may cause us to hide lots of ICEs because of some lints that everyone uses at `deny` level, and then a few ppl allow it (or macros are involved), and suddenly we go into follow-up code that expected the lint to error out on it.

**Comment by nnethercote** [comment]
>     * kinda wrong to hide follow-up errors just because a lint was denied, this may cause us to hide lots of ICEs because of some lints that everyone uses at `deny` level, and then a few ppl allow it (or macros are involved), and suddenly we go into follow-up code that expected the lint to error out on it.

This PR doesn't affect any behaviour like that. But maybe you are saying that this change could enable more such behaviour in the future, if these `Option<ErrorGuaranteed>`s were propagated more?

[This](https://github.com/rust-lang/rust/blob/bf9c7a64ad222b85397573668b39e6d1ab9f4a72/compiler/rustc_interface/src/passes.rs#L770-L780) is the main place where we treat lint errors differently to normal errors, i.e. we continue in the presence of lint errors, but stop early in the presence of non-lint errors.

**Comment by oli-obk** [comment]
> But maybe you are saying that this change could enable more such behaviour in the future, if these `Option<ErrorGuaranteed>`s were propagated more?

Yea that. It's not too hard to turn that into an `Err(ErrorGuaranteed)`, silencing follow-up analyses

**Comment by nnethercote** [comment]
Alright, I guess this is a WONTFIX.

**Pull request closed without merging**
