### PR TITLE
Recurse into args in WF even if they have escaping bound vars

### PR DESCRIPTION
**Pull request by compiler-errors**
Might have some subtle breakage but it's afaict always more correct to do this.

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
TODO:

```
trait Foo<T> {}
trait Bar {}

struct W<'a, T: Bar>(&'a T);

fn not_wf<T>() where (): for<'a> Foo<W<'a, T>> {}
```

And a similar test for projections.

**Comment by lcnr** [comment]
can you maybe crater this change together with a different PR :thinking: there are currently 5 PRs in the crater queue and I expect this change to have 1) pretty clear error messages and 2) probably no failures. Maybe as an additional commit in #122317? A crater-rollup :3

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by lcnr** [comment]
> 2) probably no failures

gdi

**Comment by compiler-errors** [comment]
i think this is way too much breakage and i have no idea how to proceed so im just gonna close this :(

wish there was a graveyard for things like this so future types ppl could see "what happens if we start actually checking wf on things" lol

**Pull request closed without merging**
