### PR TITLE
Simplify proc macro bridge state

### PR DESCRIPTION
**Pull request by joboet**
Currently, `proc_macro` uses a `ScopedCell` to store the client-side proc-macro bridge. Unfortunately, this requires the `Bridge`, which has non-negligible size, to be copied out and back again on every access. In some cases, the optimizer might be able to elide these copies, but in general, this is suboptimal. 

This PR removes `ScopedCell` and employs a similar trick as in [`scoped_tls`](https://crates.io/crates/scoped-tls), meaning that the only thing stored in TLS is a pointer to the state, which now is a `RefCell`. Access to the pointer is then scoped so that it is always within the lifetime of the reference to the state. Unfortunately, `scoped_tls` requires the referenced type to be `'static`, which `Bridge` is not, therefore we cannot simply copy that macro but have to reimplement its TLS trick.

This removes the `#[forbid(unsafe_code)]` on the `client` module so that we do not have to export `Bridge`, which currently is private, to the whole crate. I can change that, if necessary.

### CODE REVIEW

**Comment by joboet** [comment]
Okay, that's quite good, especially the token-stream-stress. I'll see if integrating the `RefCell` into the pointer helps tt-muncher.

@rustbot author

**Comment by joboet** [comment]
Yeah, that's worse. Let's just use `RefCell`.
@rustbot ready

**Comment by therealprof** [comment]
Uhm, why does this have an impact on the binary size... This should not result in different code, should it?

**Pull request merged**
