### PR TITLE
[NLL] Remove `LiveVar`

### PR DESCRIPTION
**Pull request by schomatis**
The `LiveVar` type (and related) made it harder to reason about the code. It seemed as an abstraction that didn't bring any useful concept to the reader (when transitioning from the RFC theory to the actual implementation code).

It achieved a compactness in the vectors storing the def/use/drop information that was related only to the `LocalUseMap`. This PR went in the other direction and favored time over memory (but this decision can be easily reverted to the other side without reintroducing `LiveVar`).

What this PR aims at is to clarify that there's no significant transformation between the MIR `Local` and the `LiveVar` (now refactored as `live_locals: Vec<Local>`): we're just filtering (not mapping) the entire group of `Local`s into a meaningful subset that we should perform the liveness analysis on.

As a side note, there is no guarantee that the liveness analysis is performed only on (what the code calls) "live" variables, if the NLL facts are requested it will be performed on *any* variable so there can't be any assumptions on that regard. (Still, this PR didn't change the general naming convention to reduce the number of changes here and streamline the review process).

**Acceptance criteria:** This PR attempts to do only a minor refactoring and not to change the logic so it can't have any performance impact, particularly, it can't lose any of the significant performance improvement achieved in the great work done in https://github.com/rust-lang/rust/pull/52115.

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@schomatis IIRC, we no longer even **use** the `LiveVar` abstraction, right? That is, I think that NLL wound up doing its own, distinct liveness computation, and hence the only consumer (generators) winds up computing liveness for **all** variables. If that is correct, then definitely 👍 from me to this change.

Regardless, I am going to re-assign this to @matthewjasper for review -- @matthewjasper, I hope that's ok. If not, please ping me on Zulip and I'll find someone else. I'm basically trying to work through a backlog of reviews so I fear I won't be able to get to it in a timely fashion.

r? @matthewjasper

**Comment by schomatis** [comment]
> @schomatis IIRC, we no longer even **use** the `LiveVar` abstraction, right? That is, I think that NLL wound up doing its own, distinct liveness computation, and hence the only consumer (generators) winds up computing liveness for **all** variables. If that is correct, then definitely  from me to this change.

@nikomatsakis No, my (inexperienced) understanding is that we _do_ use the `LiveVar` abstraction and we do _not_ compute liveness for all variables. However, this PR doesn't change that last part, this still filters the variables considered "live", the objective of this PR is to remove the `LiveVar` abstraction itself and rather refer to that set as `live_locals: Vec<Local>` (not `LiveVar`) because there was a continuous conversion between `LiveVar` (many times referred to as `local` in the instantiated variable) and `Local` that seemed, in my opinion, rather confusing.

(There is a case, when we request to "dump facts from NLL analysis", which I'm not sure how frequent that is, when in fact we do compute liveness for _all_ variables. This also made the `LiveVar` abstraction a bit more confusing because the functions that used it didn't actually have any guarantee that it was a "live" variable after all.)

**Comment by Centril** [comment]
Ping from triage, @matthewjasper, we eagerly await your review :)

**Comment by matthewjasper** [comment]
Looks good, but I want to check how much memory this ends up using.

@rust-lang/infra can I have a perf run?

**Comment by schomatis** [comment]
> @rust-lang/infra can I have a perf run?

@matthewjasper ping :)

**Comment by pietroalbini** [comment]
@rust-timer build 0baf2b51f0d921260d1204a0037df08e11013084

**Comment by matthewjasper** [comment]
Perf looks good

@bors r+

**Pull request merged**
