### PR TITLE
Flush executables to disk after linkage

### LINKED ISSUE #48545: Flush executables to disk after linkage
I read that: https://randomascii.wordpress.com/2018/02/25/compiler-bug-linker-bug-windows-kernel-bug/amp/
The author suggests to ensure that the binary is flushed to disk after linkage.
We could use `File::sync_all` which eventually calls `FlushFileBuffers` here:
https://github.com/rust-lang/rust/blob/322d7f7b97f1672bade31e1c43d5753e0e45a1a8/src/librustc_trans/back/link.rs#L822

### PR DESCRIPTION
**Pull request by nabijaczleweli**
A problem caused by not doing so in Chrome has been reported [here](https://randomascii.wordpress.com/2018/02/25/compiler-bug-linker-bug-windows-kernel-bug/amp/).

`File::sync_all()` calls `FlushFileBuffers()` down the line, causing potentially unflushed buffers on high I/O-load systems to flush and preventing nasty non-reproducible bugs.

Closes #48545

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks for the PR, @nabijaczleweli! 

Could you please
- check that the process exited successfully,
- only do this on Windows,
- and add a comment on why we are doing this?

**Comment by nabijaczleweli** [comment]
Done

**Comment by michaelwoerister** [comment]
Looks great now, thank you! Please squash the commits into one, then this should be good to go.

**Comment by nabijaczleweli** [comment]
Done

**Comment by ollie27** [comment]
This would also need to be done here:
https://github.com/rust-lang/rust/blob/ae544ee1c90afc0f939753014dc5e884cb2749a0/src/librustc_trans/back/link.rs#L837-L838

Although I'm not convinced that it wouldn't be better to rely on the linker to perform this mitigation.

**Comment by nabijaczleweli** [comment]
Done. As for "the linker" doing so – probably a good idea, but unreliable (henlo systems running `ld` from 5 years ago).

**Comment by michaelwoerister** [comment]
Thanks @nabijaczleweli and @ollie27!

@bors r+

**Comment by nabijaczleweli** [comment]
Error seems to've originated outside of this PR's scope 🤔

**Comment by ollie27** [comment]
[`FlushFileBuffers`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364439(v=vs.85).aspx) requires that the file is opened with write permissions but [`fs::File::open`](https://doc.rust-lang.org/nightly/std/fs/struct.File.html#method.open) is read-only.

**Comment by nabijaczleweli** [comment]
I was aware of that logically, but it's slipped my fingers. Anyway, fixed by using `OpenOptions::write(true)`.

**Pull request merged**
