### PR TITLE
Use proper span for break and continue labels

### PR DESCRIPTION
**Pull request by nagisa**
r? @alexcrichton

### CODE REVIEW

**Comment by nagisa** [comment]
Needs re-r+.

**Comment by nagisa** [comment]
rebased

**Comment by Manishearth** [comment]
@bors r-

This fails parse tests

**Comment by nagisa** [comment]
The error:

```
failures:

---- [parse-fail] parse-fail/removed-syntax-uniq-mut-expr.rs stdout ----
	
error: unexpected compiler error or warning: '/home/ubuntu/src/rust-buildbot/slave/auto-linux-32-opt/build/src/test/parse-fail/removed-syntax-uniq-mut-expr.rs:14:25: 14:27 error: expected one of `!`, `.`, `::`, `;`, `{`, or an operator, found `42`'
status: exit code: 101
command: i686-unknown-linux-gnu/stage2/bin/rustc /home/ubuntu/src/rust-buildbot/slave/auto-linux-32-opt/build/src/test/parse-fail/removed-syntax-uniq-mut-expr.rs -L i686-unknown-linux-gnu/test/parse-fail/ --target=i686-unknown-linux-gnu -L i686-unknown-linux-gnu/test/parse-fail/removed-syntax-uniq-mut-expr.stage2-i686-unknown-linux-gnu.parse-fail.libaux -C prefer-dynamic -o i686-unknown-linux-gnu/test/parse-fail/removed-syntax-uniq-mut-expr.stage2-i686-unknown-linux-gnu --cfg rtopt -O -L i686-unknown-linux-gnu/rt -Z parse-only
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/home/ubuntu/src/rust-buildbot/slave/auto-linux-32-opt/build/src/test/parse-fail/removed-syntax-uniq-mut-expr.rs:14:21: 14:24 error: expected identifier, found keyword `mut`
/home/ubuntu/src/rust-buildbot/slave/auto-linux-32-opt/build/src/test/parse-fail/removed-syntax-uniq-mut-expr.rs:14     let a_box = box mut 42;
                                                                                                                                        ^~~
/home/ubuntu/src/rust-buildbot/slave/auto-linux-32-opt/build/src/test/parse-fail/removed-syntax-uniq-mut-expr.rs:14:25: 14:27 error: expected one of `!`, `.`, `::`, `;`, `{`, or an operator, found `42`
/home/ubuntu/src/rust-buildbot/slave/auto-linux-32-opt/build/src/test/parse-fail/removed-syntax-uniq-mut-expr.rs:14     let a_box = box mut 42;
                                                                                                                                            ^~

------------------------------------------

thread '[parse-fail] parse-fail/removed-syntax-uniq-mut-expr.rs' panicked at 'explicit panic', /home/ubuntu/src/rust-buildbot/slave/auto-linux-32-opt/build/src/compiletest/runtest.rs:1501
```

[The test itself](https://github.com/rust-lang/rust/blob/0762f58c1143b4ff0ae5d0cdda9cdd8249512e77/src/test/parse-fail/removed-syntax-uniq-mut-expr.rs) seems to expect errors exactly as emitted. I’m baffled. Are 32bit linux builders broken?
I’m getting seriously annoyed.

**Comment by Manishearth** [comment]
Could be, not sure. check-stage1 passes fine for me without your PR, so it's either an intermittent, brokenness in the PR, or brokenness introduces in confluence in another PR. 

I can't see how this PR could break parsing, though. I'll poke further once I'm sure that the rollup passes check-stage2 locally

**Comment by alexcrichton** [comment]
@bors: r+ c493084ec1b35b7ab59aa0878354bca10a610360

Let's see what happens outside the rollup

**Pull request merged**
