### PR TITLE
Initiate the inner usage of `cfg_match` (Library)

### PR DESCRIPTION
**Pull request by c410-f3r**
cc https://github.com/rust-lang/rust/issues/115585

Continuation of #116312

### CODE REVIEW

**Comment by c410-f3r** [comment]
r? libs

**Comment by c410-f3r** [comment]
r? libs

**Comment by Mark-Simulacrum** [comment]
Please revert the submodule changes, those shouldn't go in as part of this PR.

**Comment by c410-f3r** [comment]
Slipped through the cracks. Thanks

**Comment by Mark-Simulacrum** [comment]
r=me (feel free to poke on Zulip for re-approval, this one is somewhat prone to conflicts)

**Comment by Dylan-DPC** [comment]
@c410-f3r any updates on this?

**Comment by c410-f3r** [comment]
Let's try again

**Comment by c410-f3r** [comment]
> Attempting with retry: sh -c git submodule deinit -f  src/doc/nomicon src/tools/cargo src/doc/reference src/doc/book src/doc/rust-by-example library/stdarch src/doc/rustc-dev-guide src/doc/edition-guide src/llvm-project src/doc/embedded-book library/backtrace &&     git submodule sync &&     git submodule update -j 16 --init --recursive --depth 1  src/doc/nomicon src/tools/cargo src/doc/reference src/doc/book src/doc/rust-by-example library/stdarch src/doc/rustc-dev-guide src/doc/edition-guide src/llvm-project src/doc/embedded-book library/backtrace
error: could not lock config file .git/modules/library/backtrace/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'library/backtrace'
Cleared directory 'library/backtrace'
error: could not lock config file .git/modules/library/stdarch/config: No such file or directory
Cleared directory 'library/stdarch'
warning: Could not unset core.worktree setting in submodule 'library/stdarch'
error: could not lock config file .git/modules/src/doc/book/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'src/doc/book'
Cleared directory 'src/doc/book'
error: could not lock config file .git/modules/src/doc/edition-guide/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'src/doc/edition-guide'
Cleared directory 'src/doc/edition-guide'
error: could not lock config file .git/modules/src/doc/embedded-book/config: No such file or directory

**Comment by c410-f3r** [comment]
Sigh... Sorry @Mark-Simulacrum @Dylan-DPC, I don't have the energy or motivation to continue pursuing this PR

**Pull request closed without merging**
