### PR TITLE
use chars instead of strings where applicable

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by ChrisDenton** [comment]
Can I ask why?

**Comment by matthiaskrgr** [comment]
we have specializations of these functions so they run faster on `char`s

**Comment by GuillaumeGomez** [comment]
Just in case:

@bors try @rust-timer queue

**Comment by matthiaskrgr** [comment]
Had a quick look with godbolt and a 
````
pub fn main() {
    let x = String::from("hello world");
    let _ = x.replace('x', &x);
}
````
emits only around half of the instructions of 

````
pub fn main() {
    let x = String::from("hello world");
    let _ = x.replace("x", &x);
}
````
with opt-level=3

**Pull request merged**
