### PR TITLE
BinaryHeap: add min-heap example

### LINKED ISSUE #58174: BinaryHeap example should show how to make a min-heap.
std::collections::BinaryHeap is a max-heap. A very common use case for users will be to make a min-heap. The basic example should include a min-heap.

### PR DESCRIPTION
**Pull request by rasendubi**
Fixes #58174.

### CODE REVIEW

**Comment by rasendubi** [comment]
I haven't received a code review in a week. Not sure what the official rules are, though...

r? @nikomatsakis for reassignment

Other issues waiting on @TimNN should be good to reassign, too: https://github.com/rust-lang/rust/pull/60453 https://github.com/rust-lang/rust/pull/60145

**Comment by mark-i-m** [comment]
@steveklabnik (docs team) might be the right person?

**Pull request merged**
