### PR TITLE
rustfmt `use` declarations

### PR DESCRIPTION
**Pull request by nnethercote**
This PR implements https://github.com/rust-lang/compiler-team/issues/750, which changes how `use` declarations are formatted by adding these options to `rustfmt.toml`:
```
group_imports = "StdExternalCrate"
imports_granularity = "Module"
```

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
The MCP has passed through its 10 day period. I think this can plausibly be merged now?

r? @oli-obk, for compiler
r? @cuviper, for libs
r? @GuillaumeGomez, for rustdoc and perhaps `src/tools/`

@bors rollup=never

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me. r=me once merge conflicts are fixed.

**Comment by tgross35** [comment]
This is probably big enough that the changes should be confirmed by multiple people when it is ready (thinking about that short-lived bug where rustfmt broke code on aarch64). That just means that a couple people on different machines run `git ls-tree HEAD . | git hash-object --stdin` on this branch, and confirm they get the same hash when resetting to the base commit and applying the new formatting themselves.

Could the update rustfmt.toml and anything else needed to apply the new formatting be moved to their own commit, to make this easier?

**Comment by nnethercote** [comment]
> Could the updated rustfmt.toml and anything else needed to apply the new formatting be moved to their own commit, to make this easier?

Good suggestion. In fact, I will merge the fiddling little changes separately. #126286 now contains the test change, and #126287 contains the cranelift patch change. Once those merge I will update here to have just two commits: (a) the rustfmt.toml change, and (b) the `x fmt --all` reformatting change.

**Comment by nnethercote** [comment]
> I will merge the fiddly little changes separately. #126286 now contains the test change, and #126287 contains the cranelift patch change. Once those merge I will update here to have just two commits: (a) the rustfmt.toml change, and (b) the `x fmt --all` reformatting change.

This has now been done.

**Comment by lcnr** [comment]
r=me on the first commit, blind trust that you yeet and reapply the second commit without any manual changes

@bors delegate+

**Comment by lcnr** [comment]
ah, didn't see the explicit requests for review. r=me only applies to compiler then

**Review by jieyouxu — APPROVED** [review]
Changes in `src/tools/compiletest`, `tests/run-make` and `src/tools/run-make-support` LGTM. Looks like this might need another rebase (heh).

**Comment by tgross35** [comment]
I get a slightly different result running locally:

```
$ git checkout 2f0bb7d8973a44c6d7ca1ddbb64c82049019d72f # initial commit from this PR
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash of initial state
f0816f47fbc167bfaddeabb40e48dd7743e6ebe3
$ ./x fmt --all
$ git commit -am "apply formatting" # ls-tree doesn't seem to 
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash with changes manually applied
8dd2be4cb13aa36077a6ee623f73c398a22193e3
$ git checkout nnethercote/rustfmt-use-decls
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash with change from this branch
bb00e31c5cd0ae5ffd7fcbb36f1dca4a68c53d14
```

But the below is the only difference. I don't know where it would be coming from but I think it is fine.

```diff
diff --git a/library/std/src/os/fortanix_sgx/mod.rs b/library/std/src/os/fortanix_sgx/mod.rs
index ee0e940cf45..cc0f7907e48 100644
--- a/library/std/src/os/fortanix_sgx/mod.rs
+++ b/library/std/src/os/fortanix_sgx/mod.rs
@@ -22,13 +22,12 @@ pub mod alloc {
     /// Lowest-level interfaces to usercalls and usercall ABI type definitions.
     pub mod raw {
         // fortanix-sgx-abi re-exports
-        pub use crate::sys::abi::usercalls::raw::Error;
         pub use crate::sys::abi::usercalls::raw::{
             accept_stream, alloc, async_queues, bind_stream, close, connect_stream, do_usercall,
             exit, flush, free, insecure_time, launch_thread, read, read_alloc, send, wait, write,
-            ByteBuffer, Cancel, Fd, FifoDescriptor, Register, RegisterArgument, Result, Return,
-            ReturnValue, Tcs, Usercall, Usercalls as UsercallNrs, EV_RETURNQ_NOT_EMPTY, EV_UNPARK,
-            EV_USERCALLQ_NOT_FULL, FD_STDERR, FD_STDIN, FD_STDOUT, RESULT_SUCCESS,
+            ByteBuffer, Cancel, Error, Fd, FifoDescriptor, Register, RegisterArgument, Result,
+            Return, ReturnValue, Tcs, Usercall, Usercalls as UsercallNrs, EV_RETURNQ_NOT_EMPTY,
+            EV_UNPARK, EV_USERCALLQ_NOT_FULL, FD_STDERR, FD_STDIN, FD_STDOUT, RESULT_SUCCESS,
             USERCALL_USER_DEFINED, WAIT_INDEFINITE, WAIT_NO,
         };
     }
```

**Comment by jieyouxu** [comment]
I can also reproduce the difference locally via `./x fmt --all` with the formatting commit, not entirely sure why.

**Comment by nnethercote** [comment]
> I get a slightly different result running locally:

I have seen that as well. Try running `x fmt --all` again. The command has some suspicious, hacky code for running multiple invocations of `rustfmt` in parallel and I think it occasionally somehow misses a file when formatting everything.

**Comment by jieyouxu** [comment]
> I have seen that as well. Try running `x fmt --all` again. The command has some suspicious, hacky code for running multiple invocations of `rustfmt` in parallel and I think it occasionally somehow misses a file when formatting everything.

I opened https://github.com/rust-lang/rust/issues/126394 so we don't lose track of this.

**Comment by tgross35** [comment]
```
$ git checkout 2f0bb7d8973a44c6d7ca1ddbb64c82049019d72f # initial commit from this PR
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash of initial state
f0816f47fbc167bfaddeabb40e48dd7743e6ebe3
$ ./x fmt --all; ./x fmt --all
$ git commit -am "apply formatting" # ls-tree doesn't seem to have an unstaged ref
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash with changes manually applied
bb00e31c5cd0ae5ffd7fcbb36f1dca4a68c53d14
$ git checkout nnethercote/rustfmt-use-decls
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash with change from this branch
bb00e31c5cd0ae5ffd7fcbb36f1dca4a68c53d14
```

Woo!

**Comment by cuviper** [comment]
`r=me` for libs.

**Comment by Kobzol** [comment]
The combination of `group_imports = "StdExternalCrate"` and `imports_granularity = "Module"` can result in non-idempotent formatting (https://github.com/rust-lang/rustfmt/issues/6195), which is why we need to rerun `x fmt` twice. It seems like in the current codebase it only happened on one place, but still it seems a bit concerning, I hope that it won't produce any formatting flakiness on CI.

**Comment by nnethercote** [comment]
> I hope that it won't produce any formatting flakiness on CI.

I don't think it will cause flakiness, e.g. there is no bouncing back and forth between two states. But I have found some cases where comments on `use` declarations are not being preserved as they should.

Here is an example where it behaves as I would hope/expect, i.e. a comment "sticks to" the use declaration.
```diff
diff --git a/library/std/src/os/wasi/fs.rs b/library/std/src/os/wasi/fs.rs
index 46fc2a50de9..7e26250b05e 100644
--- a/library/std/src/os/wasi/fs.rs
+++ b/library/std/src/os/wasi/fs.rs
@@ -5,14 +5,15 @@
 #![deny(unsafe_op_in_unsafe_fn)]
 #![unstable(feature = "wasi_ext", issue = "71213")]

+// Used for `File::read` on intra-doc links
+#[allow(unused_imports)]
+use io::{Read, Write};
+
 use crate::ffi::OsStr;
 use crate::fs::{self, File, Metadata, OpenOptions};
 use crate::io::{self, IoSlice, IoSliceMut};
 use crate::path::{Path, PathBuf};
 use crate::sys_common::{AsInner, AsInnerMut, FromInner};
-// Used for `File::read` on intra-doc links
-#[allow(unused_imports)]
-use io::{Read, Write};
 
 /// WASI-specific extensions to [`File`].
 pub trait FileExt {
```
And here is a case where that doesn't happen, so the comment ends up in the wrong place.
```diff
diff --git a/compiler/rustc_data_structures/src/sip128.rs b/compiler/rustc_data_structures/src/sip128.rs
index 4c9acfe0f71..2ac2a94504b 100644
--- a/compiler/rustc_data_structures/src/sip128.rs
+++ b/compiler/rustc_data_structures/src/sip128.rs
@@ -2,11 +2,12 @@
 
 // This code is very hot and uses lots of arithmetic, avoid overflow checks for performance.
 // See https://github.com/rust-lang/rust/pull/119440#issuecomment-1874255727
-use rustc_serialize::int_overflow::{DebugStrictAdd, DebugStrictSub};
 use std::hash::Hasher;
 use std::mem::{self, MaybeUninit};
 use std::ptr;
 
+use rustc_serialize::int_overflow::{DebugStrictAdd, DebugStrictSub};
+
 #[cfg(test)]
 mod tests;
``` 
Looking through the diff I see examples of both, without an obvious reason how/why one happens or the other.

There is another problem case where people use `//` comments to describe multiple `use` declarations. E.g. in `library/std/src/prelude/common.rs`:
```rust
// Re-exported functions
#[stable(feature = "rust1", since = "1.0.0")]
#[doc(no_inline)]
pub use crate::mem::drop;
#[stable(feature = "size_of_prelude", since = "1.80.0")]
#[doc(no_inline)]
pub use crate::mem::{align_of, align_of_val, size_of, size_of_val};
```
Even when the comment sticks to the `use` declaration immediately below it, the meaning of the comments gets messed up. This style of commenting is incompatible with `use` reordering.

The number of places affected is quite small. A quick pass over the diff brings up this many:
```text
- compiler/rustc_data_structures/src/sip128.rs
- rustc_lint/src/lib.rs
- compiler/rustc_middle/src/mir/terminator.rs - should be //!
- compiler/rustc_smir/src/rustc_internal/internal.rs
- library/alloc/src/testing/crash_test.rs
- library/core/src/prelude/common.rs
  - double-check this one
- library/core/src/unicode/mod.rs
- library/std/src/lib.rs ?
- library/std/src/os/fortanix_sgx/mod.rs
- library/std/src/prelude/common.rs
  - prime example of single line comment applying to an entire block, ugh
- library/std/src/rt.rs
- library/std/src/sys/pal/wasi/mod.rs
  - is that comment about globbing correct?
- library/std/src/sys/pal/wasip2/mod.rs
  - ditto
- library/test/src/lib.rs
- src/tools/rust-installer/src/util.rs
  - FIXME comment *after* the `use` line, ugh
- compiler/rustc_builtin_macros/src/test.rs
```
The second problem -- of people using one comment to describe multiple lines of `use` declarations -- seems fixable by just rewriting a small number of comments as necessary in advance of the reformatting. Once reordering of `use` declarations becomes the norm people will hopefully not write these kinds of comments any more.

The first problem -- of comments not always sticking to the `use` declaration just below them -- is more of a concern.

**Comment by RalfJung** [comment]
> The first problem -- of comments not always sticking to the use declaration just below them -- is more of a concern.

It looks to me like this is caused by rustfmt trying to detect "one comment to describe multiple lines of use declarations"? In your example of this case, the comment is above a block of `use` declarations, so it seems reasonable to assume that it describes the block and not just the first line.

**Comment by nnethercote** [comment]
I've written an update about this change in the MCP: https://github.com/rust-lang/compiler-team/issues/750#issuecomment-2232540639

**Comment by tgross35** [comment]
Double checked reapplying the changes, it matches up this time 🎉 

```rust
$ git checkout 118f9350c5b902e462a6dcc4325670f3da701600 # initial commit from this PR
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash of initial state
26fd38436641161c99ad27639183af194b4110a6
$ ./x fmt --all
$ git commit -am "apply formatting" # ls-tree doesn't seem to have an unstaged ref
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash with changes manually applied
f6f42f762bd56fafd49d14636d90022a98f6f0ed
$ # test for idempotence
$ ./x fmt --all
$ git diff # should be empty
$ git checkout nnethercote/rustfmt-use-decls
$ git ls-tree --full-tree -r HEAD . | git hash-object --stdin # hash with change from this branch
f6f42f762bd56fafd49d14636d90022a98f6f0ed
```

**Comment by tgross35** [comment]
Thanks for making this happen, here comes cleaner code! 🎉🎉

@bors treeclosed-

**Comment by kornelski** [comment]
This has created a ton of merge conflicts, and most annoyingly it has undone https://github.com/rust-lang/rust/pull/127090 which deliberately avoided rustfmt's brute naïveté to allow more than one options PR to coexist.

**Comment by nnethercote** [comment]
You can use `#[rustfmt::skip]` if you need it. I recommend adding explanatory comments alongside.

**Comment by tgross35** [comment]
This isn't especially noisy, but a `.git-blame-ignore-revs` entry might still be worth doing.

**Comment by nnethercote** [comment]
> This isn't especially noisy, but a `.git-blame-ignore-revs` entry might still be worth doing.

Done in #128478.

**Pull request merged**
