### PR TITLE
constify len and is_empty functions of string and vec

### PR DESCRIPTION
**Pull request by Luro02**

### CODE REVIEW

**Review by Centril — APPROVED** [review]

**Comment by Centril** [comment]
cc @oli-obk r? @alexcrichton

**Comment by oli-obk** [comment]
Iirc we had a PR for this before and closed it because you can't use these because you can't really create constant strings

**Comment by Luro02** [comment]
Is it fundamentally impossible to crate a const `String`/`Vec` or just not possible right now? I looked a bit through the function calls and landed at https://github.com/rust-lang/rust/blob/d28a9c38fe14396e86ae274c7847e20ee0f78ca9/src/libcore/intrinsics.rs#L1602, which seems to be some external function? So does this mean, that you can't make a `memset` const?

**Comment by Centril** [comment]
You can create an empty string / vector but not one which has allocated, so you'll always get `.is_empty() == true` which isn't very exciting. That said, it seems obvious to me that we will want these to be const eventually so I don't personally mind the order in which we stabilize.

**Comment by memoryruins** [comment]
There were also concerns about uniformity in the previous PR https://github.com/rust-lang/rust/pull/55278#issuecomment-432714782

**Comment by Luro02** [comment]
So just for my own understanding, a const function cannot allocate memory?
For example this could be quite useful:

```rust
const fn takes_string(value: String) -> usize {
     value.len() + 420 / 10
} // the size of value is already known, therfore it can be const?

let mut string = String::new();
string.push_str("Hello");

takes_string(string);
```

**Comment by Centril** [comment]
> So just for my own understanding, a const function cannot allocate memory?

Not yet, [but there are plans](https://www.youtube.com/watch?v=wkXNm_qo8aY).

**Comment by Luro02** [comment]
There is no reason anymore. I just thought it was weird, that len wasn't `const`, because it just returns a number/variable.

**Comment by alexcrichton** [comment]
Ok in that case I'm gonna go ahead and close this, and we can reconsider once these can be useful in a const context.

**Pull request closed without merging**
