### PR TITLE
rustdoc: simplify handling of plain text output

### PR DESCRIPTION
**Pull request by jsha**
Replace use of `f.alternate()` in format.rs, and offers instead `Type::print_plain`, and `Path::print_plain`.

Adopt Askama template for rendering of functions and methods.

Motivation:

In rustdoc we generally emit HTML, but there are a few places where we need to emit a plain text form of `clean::Type` and/or `clean::Path`:

 - In the sidebar, under `Trait Implementations`, we render traits, e.g. `AsRef<str>`. These should be plain because we don't want to separately link `AsRef` and `str` to those respective types; we want a single link that goes to that trait implementation.
 - When creating ids and internal hrefs for headings related to trait implementations, we generate the ids based on a plain text version of the trait (and the type it is implemented for).
 - Similarly, when creating the datastructures used to render "Notable traits", we index those datastructures by a plain text version of the type that has notable trait implementations.
 - When rendering a function or associated function, we decide whether or not to line-wrap the declaration based on whether the plain text form would exceed 80 characters (imitating rustfmt).

[Originally](https://github.com/rust-lang/rust/pull/36679), plain text output was controlled via Formatter's `f.alternate()` mechanism, so you could generate HTML by formatting with `{}` or plain text by formatting with `{:#}`. This avoids having to generate HTML only to strip it out. However, it leads to a lot of duplication and branching in format.rs. Since the only HTML we care about comes from within a single module, we can write a very simple HTML remover that strips all tags and only cares about a handful of entities.

This also lets us simplify calculating the width of a function header - we can simply pass a template and count its bytes.

This PR can be reviewed commit-by-commit.

Related: #108868

### CODE REVIEW

**Comment by jsha** [comment]
Yep! Will take a look in a bit. Thanks for digging up the log line.

**Comment by fmease** [comment]
Hey :) Does this PR fix #109488 perchance?

**Comment by Dylan-DPC** [comment]
@jsha any updates on this?

**Pull request closed without merging**
