### PR TITLE
Rollup of 16 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #72569 (Remove legacy InnoSetup GUI installer)
 - #73306 (Don't implement Fn* traits for #[target_feature] functions)
 - #73345 (expand: Stop using nonterminals for passing tokens to attribute and derive macros)
 - #73449 (Provide more information on duplicate lang item error.)
 - #73569 (Handle `macro_rules!` tokens consistently across crates)
 - #73803 (Recover extra trailing angle brackets in struct definition)
 - #73839 (Split and expand nonstandard-style lints unicode unit test.)
 - #73841 (Remove defunct `-Z print-region-graph`)
 - #73848 (Fix markdown rendering in librustc_lexer docs)
 - #73865 (Fix Zulip topic format)
 - #73892 (Clean up E0712 explanation)
 - #73898 (remove duplicate test for #61935)
 - #73906 (Add missing backtick in `ty_error_with_message`)
 - #73909 (`#[deny(unsafe_op_in_unsafe_fn)]` in libstd/fs.rs)
 - #73910 (Rewrite a few manual index loops with while-let)
 - #73929 (Fix comment typo)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors retry

This is happening pretty often, with different PRs in the rollup

@pietroalbini think this is an infra issue?

**Comment by nnethercote** [comment]
This was a [perf win](https://github.com/rust-lang/rust/compare/9491f18c5de3ff1c4bf9c3fdacf52d9859e26f7c...b7856f695d65a8ebc846754f97d15814bcb1c244). Perhaps #73345 (@petrochenkov) or  #73569 (@Aaron1011) is the cause?

**Comment by landaire** [comment]
One of these macro-related PRs I think may end up breaking some of the more fragile proc macros in the ecosystem. We depend on one at my work which does string matching on each line of the `TokenStream` and performs some operations on what it finds. This macro was broken since the input `TokenStream` no longer has line breaks in it. I was able to determine `nightly-2020-07-03` was where the breakage occurred, which I *think* is this rollup.

While I didn't write the macro in question I think part of the reason why this string matching approach was taken is because of the lack of resources for writing proc macro from scratch using zero dependencies. [Here is a Twitter thread I found which expresses some of my own thoughts](https://twitter.com/rikarends/status/1277919873700683776). Here's a reference to `nanoserde` which may serve as a good reference for anyone else wanting to correctly write a proc macro with zero dependencies: https://github.com/not-fl3/nanoserde/blob/05f40b2e1bcb97bf10104982f109a51d3a07120a/derive/src/parse.rs

While I think it's fair to say that you are not intended to write a proc macro via `TokenStream` string conversion, I thought it was worth mentioning.

**Comment by Manishearth** [comment]
@landaire I do maintain a lightweight crate for doing proc macros without pulling in syn: https://docs.rs/absolution

aside from that, your comment is probably not going to have any effect if posted here

**Comment by landaire** [comment]
@Manishearth thanks for the reference! I'll check it out.

>aside from that, your comment is probably not going to have any effect if posted here

I wasn't really sure where the correct place for conversation was and which PR was the culprit. Our breakage is a result of assumptions not guaranteed by Rust IMO, but I wanted to raise the flag that this may cause breakage for others in the future. Would this be appropriate to file an issue over to discuss more in-depth or would the internals forum be better-suited?

**Comment by Manishearth** [comment]
I would post on internals, this is more of a discussion thing. The string representation is deliberately not stable

**Pull request merged**
