### PR TITLE
rustc_target: rename {Fn,Arg}Type to {Fn,Arg}Abi.

### PR DESCRIPTION
**Pull request by eddyb**
I was trying to tweak the API of `FnType` (now `FnAbi`) and the name kept bothering me.

`FnAbi` is to a function signature a bit like a layout is to a type, so the name still isn't perfect yet, but at least it doesn't have the misleading `Type` in it anymore.

If this can't land I think I can continue my original refactor without it, so I'm not strongly attached to it.

r? @nagisa cc @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
`ArgAbi` is not entirely clear; `FnArgAbi` would be better as it sets the right context -- that this is about the call ABI, not other aspects of the ABI like memory layout.

`FnLayout` wouldn't make much sense, or would it?

**Comment by RalfJung** [comment]
@eddyb said in chat

> what makes ArgAbi really bad IMO is that it's used for returns too

Totally strawman proposal: `FnInOutAbi`.
Finding something direction-agnostic would be better of course, but it is not clear what that would be. `FnDomainAbi`?^^

**Comment by RalfJung** [comment]
`FnArgRetAbi` would be another one that just lists both uses.

**Comment by oli-obk** [comment]
While I agree that the name may not be perfect, it is strictly an improvement. I don't like the other options, and `Arg` conveys both input and output arguments, even if the general notion of argument means an input argument. The fact that there are output arguments means to me that `Arg` by itself is fine.

We can revisit with more detailed naming later if someone comes up with a better name.

@bors r+

**Pull request merged**
