### PR TITLE
Allow rust-highfive to label issues it creates.

### PR DESCRIPTION
**Pull request by Elinvynia**
This is my first meaningful PR, I am unsure how to test this code so any pointers would be welcome!

I am about 50% sure it works.

### CODE REVIEW

**Comment by Elinvynia** [comment]
cc @RalfJung

**Comment by RalfJung** [comment]
Cc @kennytm @pietroalbini

**Review by kennytm — COMMENTED** [review]
the code looks fine to me, except that `LABELS` could use a list directly rather than sets. 

cc @rust-lang/wg-triage, are you ok with these choices of labels?

**Review by JohnTitor — APPROVED** [review]
Works for me!

**Comment by Mark-Simulacrum** [comment]
@Elinvynia Could you update the sets to lists? With that done I think we can merge this in. Thanks!

**Comment by Mark-Simulacrum** [comment]
Can you also squash the commits into one? Thanks!

r=me with that done

**Comment by Elinvynia** [comment]
?r=me

**Comment by RalfJung** [comment]
"r=me" is code for "tell bors to approve this PR in my name". It is also entire inscrutable unless you already know it, and contributors without bors permission cannot use it anyway.

But it tells me I can now do this:
@bors r=Mark-Simulacrum

**Pull request merged**
