### PR TITLE
Don't disable codegen tests in PR CI

### LINKED ISSUE #126170: PR CI (x86_64-gnu-llvm-17) does not run codegen tests
https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/x86_64-gnu-llvm.sh passes `--skip tests/codegen` if ENABLE_GCC_CODEGEN is enabled. The tests are disabled when using the LLVM backend as well.

### PR DESCRIPTION
**Pull request by nikic**
Fixes https://github.com/rust-lang/rust/issues/126170.

r? @ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
Seems like we should be using a different approach for skipping the codegen tests, something akin to a `@needs-llvm` annotation or something similar, instead of skipping them altogether when the GCC flag is enabled.

**Comment by nikic** [comment]
@Kobzol All codegen tests require LLVM, so the whole suite should get skipped for other backends. Though this already seems to be the case, given that this PR passes CI. Not sure why that condition was added in the first place, but it doesn't seem to be necessary anymore.

**Comment by workingjubilee** [comment]
Thanks for fixing this!

**Comment by Kobzol** [comment]
> All codegen tests require LLVM, so the whole suite should get skipped for other backends. Though this already seems to be the case, given that this PR passes CI. Not sure why that condition was added in the first place, but it doesn't seem to be necessary anymore. (I don't think that other codegen backends run "normal" rustc tests at all -- right?)

I would expect GCC/Cranelift to run at least a subset of the UI test suite, but I'm not sure.

Anyway, since this seems to work, let's ship it, we ideally shouldn't skip these tests.

r? @Kobzol

@bors r+ rollup=never

**Pull request merged**
