### PR TITLE
Remove `arena_cache` modifier from `associated_item` query & copy `ty::AssocItem` instead of passing by ref

### PR DESCRIPTION
**Pull request by WaffleLapkin**
r? @ghost

### CODE REVIEW

**Comment by Nilstrieb** [comment]
r? Nilstrieb
Looks good, it's just 24 bytes so this should be fine, perf is neutral as well.
Are there any usages in clippy? If yes, you should adjust them as well probably since you also changed rustdoc.
There's an internal lint about passing things by value that are `#[rustc_pass_by_value]`. Does it make sense to also add it here? It's generally used for IDs and other tiny things, I'm not sure whether it's worth bothering here, having a reference to an assoc item shouldn't hurt anyone.

**Comment by WaffleLapkin** [comment]
@Nilstrieb clippy seems to be fine (`x c clippy` passes locally for me), `#[rustc_pass_by_value]` doesn't seem necessary to me.

**Comment by Nilstrieb** [comment]
r=me after rebase

**Pull request merged**
