### PR TITLE
Stabilize crate_in_paths, extern_absolute_paths and extern_prelude on all editions.

### PR DESCRIPTION
**Pull request by eddyb**
Needed for beta, path-related migrations to Rust 2018 don't work on RC1 without these stabilizations.

r? @aturon cc @nikomatsakis @Centril @alexcrichton

### CODE REVIEW

**Comment by petrochenkov** [comment]
*`extern_absolute_paths` cannot be stabilized on 2015 edition, it's a huge breaking change, but this PR stabilizes it only on 2018 edition despite the title, so it's ok.

**Comment by eddyb** [comment]
@petrochenkov Right, we already have a distinction between "the feature-gate is stable" (which is what this PR affects) and "the feature affects semantics vs migrations" (which this PR doesn't touch).

**Comment by eddyb** [comment]
I'm a bit confused, how did I not hit those locally?

**Comment by rpjohnst** [comment]
It looks like this stabilizes the `extern::my_crate::a::b` syntax as well as `::my_crate::a::b`, which I thought was *not* part of the module changes.

**Comment by eddyb** [comment]
@rpjohnst `extern_absolute_paths` is `::crate_name::foo`, *not* the `extern` keyword in paths, the latter is still unstable on both editions and untouched by this PR.

**Comment by eddyb** [comment]
@pietroalbini Already had `p=3`.

**Comment by pietroalbini** [comment]
Oh, woops, missed it. Sorry!

@bors p=3

**Comment by orium** [comment]
CC #53797

**Comment by pietroalbini** [comment]
Cargo tests failed.

```
failures:
---- fix::local_paths_no_fix stdout ----
running `C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe fix --edition --allow-no-vcs`
thread 'fix::local_paths_no_fix' panicked at '
Expected: execs
    but: differences:
  4 - |[FINISHED] [..]|
    + |      Fixing src\lib.rs (1 fix)|
  5 -
    + |    Finished dev [unoptimized + debuginfo] target(s) in 0.35s|
other output:
``', tools\cargo\tests\testsuite\support\mod.rs:731:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    fix::local_paths_no_fix
```

**Comment by eddyb** [comment]
#54404 failed in the same way. Does this need changing in Cargo? At a glance, I suspect it's testing for something that's changed/fixed in this PR, so yes.
Can someone else work on that? Otherwise I'll take a look at it in a few hours.

**Comment by ehuss** [comment]
This will need all the changes from #54334 if you want to update cargo.

**Comment by alexcrichton** [comment]
@bors: r-

Yeah unfortunately let's land https://github.com/rust-lang/rust/pull/54334 before landing this to make the cargo update easier

**Comment by alexcrichton** [comment]
A bit late to the punch, but this may have caused a [5-6% decrease in perf across some benchmarks](https://perf.rust-lang.org/compare.html?start=c97b60ff3fcf1830e7e19ceeaea4046dc126911d&end=4a6e875b81c610a4131b377a27029c1837973f31&stat=instructions:u)

**Pull request merged**
