### PR TITLE
README: improve description

### PR DESCRIPTION
**Pull request by tshepang**
- I assume _multithreaded_ meant _thread safety_
- _significant_ felt a bit heavy

### CODE REVIEW

**Comment by tshepang** [comment]
I assume *multithreaded* meant *thread safety*

**Comment by arielb1** [comment]
We don't guarantee thread-safety (what with it being often a problem-domain issue). We do however make usage of threads easy, and race conditions mostly opt-in.

**Comment by tshepang** [comment]
@arielb1 interesting... I got the thread safety bit from the Rust website:

>  Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety.

**Comment by steveklabnik** [comment]
There's another open ticket about changing that, because it's too
over-reaching, and doesn't have a great definition to begin with.

**Comment by tshepang** [comment]
@steveklabnik which repo is the ticket at?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215

**Comment by steveklabnik** [comment]
oh my, my conf wifi is spotty and so sent this a zillion times, sorry :(

**Comment by tshepang** [comment]
happens to me at times too
you can delete the spurious though :)

**Comment by tshepang** [comment]
I will do a fresh PR

**Comment by tshepang** [comment]
https://github.com/rust-lang/rust/pull/26410

**Pull request closed without merging**
