### PR TITLE
Document std::string::ParseError

### PR DESCRIPTION
**Pull request by steveklabnik**
Part of #29376

### CODE REVIEW

**Comment by alexcrichton** [comment]
Perhaps this could explicitly call out that this type will never exist as it is an empty `enum`?

**Comment by steveklabnik** [comment]
What specific aspect of "never exist" distinct from "this type should never actually be returned", that it's zero-sized?

**Comment by alexcrichton** [comment]
Ah sorry I should think more before commenting! I found it a little odd when reading that the first few clauses were all talking about how this error is returned only to later say "but actually this doesn't happen". Perhaps this could just be rephrased to give the impression initially that this type is never returned? It may just also be too early in the morning as well...

**Comment by steveklabnik** [comment]
> It may just also be too early in the morning as well...

My docs should be clear at any time of day :sun_with_face: :sunglasses:

**Comment by steveklabnik** [comment]
@alexcrichton try this version of the text out? does that help?

**Comment by alexcrichton** [comment]
@bors: r+ 23fb9743d33b218328699d64e792da877d470674

Looks good to me!

**Pull request merged**
