### PR TITLE
reference: it is sometimes called "the compiler" in this document

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by huonw** [comment]
I think the phrase is talking about the "the", not the "Rust".

**Comment by tshepang** [comment]
(closed by mistake)

**Comment by tshepang** [comment]
That's not clear, and the qualifier is not even needed anyways.

**Comment by leodasvacas** [comment]
I don't think it's obvious. `The only implementation is a compiler` immediately makes the reader ask: "what compiler?"

**Comment by tshepang** [comment]
@leodasvacas the are 2 concepts presented: interpreter and compiler. There is then a claim that the only implementation that exists (at the moment) is *a compiler*... i.e. there is not interpreter.

**Comment by leodasvacas** [comment]
Saying "the C++ compiler" would be unclear, there is no "the C++ compiler" but there are clang and gcc. In the case of rust, we have a compiler which is called "the Rust compiler", rather than "the Rust-o-tron3000". It's good to have precise definitions in a language reference, even if they seem obvious.

**Comment by tshepang** [comment]
@leodasvacas Do you suggest that all instances of "the compiler" should be replaced with "the Rust compiler"?

**Comment by tshepang** [comment]
@leodasvacas The phrase "C++ compiler" is valid in cases where the implementation doesn't matter... there is stuff that is common among all implementations.

**Comment by steveklabnik** [comment]
After leaving this sit for a while, I think we'll just keep it as it is. Thanks though!

**Comment by tshepang** [comment]
@steveklabnik if this PR is not good enough to be merged, one that should is one that replaces all occurrences of *the compiler* with *the Rust compiler*. Else, we are leaving this inaccurate statement alive:

> ...from now on referred to as the Rust compiler...

**Comment by steveklabnik** [comment]
Sure thing. Would you like to do that, or should I?

**Comment by tshepang** [comment]
you may

**Comment by steveklabnik** [comment]
So, thinking about it more, I actually do prefer this change. It looks like you deleted the branch, though, so I can't re-open. Can you?

**Comment by tshepang** [comment]
I undeleted it. Thanks for re-considering it.

**Comment by steveklabnik** [comment]
No problem, and thanks for being patient. I originally thought this came much, much earlier in the reference.

**Comment by tshepang** [comment]
you'll need to re-open the issue as well

**Comment by steveklabnik** [comment]
Ugh, I thought I did. thanks

**Comment by tshepang** [comment]
yay!

**Pull request merged**
