### PR TITLE
std: Don't build docs for misc facade crates

### LINKED ISSUE #38319: rustbuild builds docs for too many crates
The Makefiles only build the docs for:

```
std
alloc
collections
core
libc
rustc_unicode
```

I assume `alloc`, `collections` and `rustc_unicode` are included mostly so the src links in `std` work. I'm not sure why `libc` is included though...

Anyway, with rustbuild it builds all of these:

```
core
compiler_builtins
rand
libc
rustc_unicode
alloc
unwind
panic_abort
alloc_system
panic_unwind
collections
std
std_shim

getopts
term
test
test_shim
```

Most of these are implementation details of `std` so shouldn't be included. The `test` docs are a big problem because of the same issue as #34800, generating them means the search index will get overridden.

### PR DESCRIPTION
**Pull request by alexcrichton**
Retain the same behavior as stable.

Closes #38319

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nominating for a beta backport due to #38319

**Comment by ollie27** [comment]
What about `compiler_builtins` and `std_shim`?

Do you think we can stop including the docs for `libc` while we're at it?

**Comment by alexcrichton** [comment]
Oh I didn't see those on https://doc.rust-lang.org/beta/std/ but I see them now on nightly, I'll update accordingly. Also yeah let's axe the libc docs.

**Comment by nikomatsakis** [comment]
Marked as beta-accepted (cc @rust-lang/compiler -- though this could also be considered @rust-lang/tools; in any case the patch seems clearly ok to backport)

**Comment by nikomatsakis** [comment]
@alexcrichton 

looks legitimate:

```
book/error-handling.html:1395: broken link - std/macro.try.html
book/error-handling.html:1463: broken link - std/error/trait.Error.html
book/error-handling.html:1464: broken link - std/error/trait.Error.html
book/error-handling.html:1584: broken link - std/io/enum.ErrorKind.html
book/error-handling.html:1585: broken link - std/num/struct.ParseIntError.html
book/error-handling.html:1591: broken link - std/error/trait.Error.html
book/error-handling.html:1607: broken link - std/io/type.Result.html
book/error-handling.html:1608: broken link - std/fmt/type.Result.html
book/error-handling.html:1795: broken link - std/fs/struct.File.html
book/error-handling.html:1797: broken link - std/io/struct.Error.html
book/error-handling.html:1951: broken link - std/convert/trait.From.html
book/error-handling.html:2245: broken link - std/result/enum.Result.html
book/error-handling.html:2246: broken link - std/option/enum.Option.html
book/error-handling.html:2248: broken link - std/option/enum.Option.html
book/error-handling.html:2258: broken link - std/convert/trait.From.html
book/error-handling.html:2260: broken link - std/error/trait.Error.html
book/error-handling.html:2261: broken link - std/macro.try.html
book/error-handling.html:2265: broken link - std/error/trait.Error.html
book/error-handling.html:2267: broken link - std/convert/trait.From.html
book/error-handling.html:2272: broken link - std/option/enum.Option.html
book/error-handling.html:2274: broken link - std/result/enum.Result.html
book/concurrency.html:205: broken link - std/marker/trait.Send.html
book/concurrency.html:219: broken link - std/marker/trait.Sync.html
book/concurrency.html:494: broken link - std/sync/struct.Mutex.html
book/concurrency.html:495: broken link - std/sync/struct.Mutex.html
error-index.html:7: broken link - main.css
thread 'main' panicked at 'found some broken links', /checkout/src/tools/linkchecker/main.rs:49
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
Man linkchecker is a lifesaver. That just caught a bug where we built no documentation at all!

@bors: r=nikomatsakis

**Comment by ollie27** [comment]
This doesn't seem to have worked: https://doc.rust-lang.org/nightly/std/. The docs for `std_shim` are no longer generated but the rest still are. I've tested this locally as well and got the same results.

**Pull request merged**
