### PR TITLE
Revert "remove num_cpus dependency" in rustc and update cargo

### LINKED ISSUE #97549: Higher memory usage on Rust 1.61.0 (compared to 1.60.0) leading to SIGKILL
It seems that memory usage during compilation has increased between 1.60.0 and 1.61.0, enough to trigger an OOM kill on CircleCI when trying to build my project.

Running on a [`medium+` instance](https://circleci.com/docs/2.0/configuration-reference/#resourceclass) (3 vCPUs, 6 GB RAM).
Command used: `cargo test --all --verbose -- --nocapture`

```
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
```

Example run: https://app.circleci.com/pipelines/github/mozilla/glean/9430/workflows/8c32e02e-6915-47ee-a587-a0ec098d9afd/jobs/175430
Same on nightly (`rustc 1.63.0-nightly (28b891916 2022-05-29)`)

The same task runs just fine with Rust 1.60.0
I don't yet have a smaller example to showcase this, nor exact memory measurments. I'm willing to explore this further if you let me know how to best record memory usage.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #97549. This PR reverts #94524 and does a Cargo update to pull in rust-lang/cargo#10737.

Rust 1.61.0 has a regression in which it misidentifies the number of available CPUs in some environments, leading to enormously increased memory usage and failing builds. In between Rust 1.60 and 1.61 both rustc and cargo replaced some uses of `num_cpus` with `available_parallelism`, which eliminated support for cgroupv1, still apparently in common use. This PR switches both rustc and cargo back to using `num_cpus` in order to support environments where the available parallelism is controlled by cgroupv1. Both can use `available_parallism` again once it handles cgroupv1 (if ever).

I have confirmed that the rustc part of this PR fixes the memory usage regression in my non-Cargo environment, and others have confirmed in #97549 that the Cargo regression was at fault for the memory usage regression in their environments.

### CODE REVIEW

**Comment by the8472** [comment]
> Both can use available_parallism again once it handles cgroupv1 (if ever).

I already claimed the issue and wrote that I'll be working on that.

**Comment by compiler-errors** [comment]
@dtolnay @Mark-Simulacrum, should this be beta nominated so users don't have to wait for 1.63 for this to reach stable?

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-06-16/near/286359904)

@rustbot label +beta-accepted

**Pull request merged**
