### PR TITLE
tweak unresolved label suggestion

### PR DESCRIPTION
**Pull request by euclio**
Only suggest label names in the same hygiene context, and use a
structured suggestion.

Question for reviewer: Is this the right way to check for label hygiene?

### CODE REVIEW

**Comment by zackmdavis** [comment]
(My review turnaround time has not been super-great lately; let me make sure to look/think about this the evening (UTC−7) of Tuesday the ninth)

**Comment by zackmdavis** [comment]
or the tenth

**Comment by Dylan-DPC** [comment]
ping from triage @zackmdavis any updates?

**Pull request merged**
