### PR TITLE
Improve tuple struct field access hygiene

### LINKED ISSUE #47312: Inconsistency between accessing field of braced struct vs tuple struct in proc macro
If a procedural macro generates an access to a named struct field like `self.x` then the `.` may be either def_site or call_site and it works either way. But if accessing an unnamed tuple struct field like `self.0` then it only works if `.` is call_site.

I believe it should work either way in either case.

```rust
#![feature(proc_macro)]

extern crate proc_macro;
use proc_macro::{TokenStream, TokenTree, TokenNode, Spacing, Span};

#[proc_macro]
pub fn field(input: TokenStream) -> TokenStream {
    let mut iter = input.into_iter();
    let struct_name = iter.next().unwrap();
    let field_name = iter.next().unwrap();
    assert!(iter.next().is_none());

    let dot = TokenTree {
        // Call_site works for both braced structs and tuple structs.
        // Def_site works for braced structs but not tuple structs.
        span: Span::def_site(),
        kind: TokenNode::Op('.', Spacing::Alone),
    };
    vec![
        struct_name,
        dot,
        field_name,
    ].into_iter().collect()
}
```

```rust
#![feature(proc_macro)]

extern crate mac;

struct S {
    a: u8,
}

struct T(u8);

fn main() {
    let s = S { a: 0 };
    println!("{:?}", mac::field!(s a));

    let t = T(0);
    println!("{:?}", mac::field!(t 0));
}
```

```
error[E0611]: field `0` of tuple-struct `T` is private
  --> src/main.rs:55:34
   |
55 |     println!("{:?}", mac::field!(t 0));
   |                                  ^^^
```

@jseyfried

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #47312 by fixing a span bug.
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
The issue here was that the parser was assigning an incorrect span a tuple struct field access expression, e.g. in `x.0`, the `0` was assigned the span `.0` (including the dot).

**Comment by kennytm** [comment]
@bors r-

The new test case [cannot be pretty-printed](https://travis-ci.org/rust-lang/rust/jobs/339410972).

```
[01:40:50] failures:
[01:40:50] 
[01:40:50] ---- [pretty] run-pass/hygiene/issue-47312.rs stdout ----
[01:40:50] 	
[01:40:50] error: pretty-printed source does not typecheck
[01:40:50] status: exit code: 101
[01:40:50] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "-" "-Zno-trans" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/hygiene/issue-47312.pretty-out" "--target=x86_64-unknown-linux-gnu" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/hygiene/issue-47312.stage2-x86_64-unknown-linux-gnu.pretty.aux" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
[01:40:50] stdout:
[01:40:50] ------------------------------------------
[01:40:50] 
[01:40:50] ------------------------------------------
[01:40:50] stderr:
[01:40:50] ------------------------------------------
[01:40:50] error[E0433]: failed to resolve. Could not find `m` in `foo`
[01:40:50]   --> <anon>:20:28
[01:40:50]    |
[01:40:50] 20 |     fn f() { let s = S(0); ::foo::m!(s , 0); }
[01:40:50]    |                            ^^^^^^^^ Could not find `m` in `foo`
[01:40:50] 
[01:40:50] error: aborting due to previous error
[01:40:50] 
[01:40:50] 
[01:40:50] ------------------------------------------
[01:40:50] 
[01:40:50] thread '[pretty] run-pass/hygiene/issue-47312.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2883:9
[01:40:50] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:40:50] 
[01:40:50] 
[01:40:50] failures:
[01:40:50]     [pretty] run-pass/hygiene/issue-47312.rs
```

**Comment by ishitatsuyuki** [comment]
Seems this failed rollup again.

**Pull request merged**
