### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
- Successful merges: #28664, #28673, #28681, #28682, #28688
- Failed merges:

### CODE REVIEW

**Comment by apasel422** [comment]
The Android builder seems to be taking a long time to start recently.

**Comment by Manishearth** [comment]
Huh, totally forgot about this PR.

... that's weird.

**Comment by Manishearth** [comment]
The builder seems offline

**Comment by alexcrichton** [comment]
This passed all tests but apparently the android slave fell over so merging manually.

**Pull request merged**
