### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #94100 (Issue #91417 fix)
 - #94115 (Let `try_collect` take advantage of `try_fold` overrides)
 - #94848 (Compare installed browser-ui-test version to the one used in CI)
 - #94993 (Add test for >65535 hashes in lexing raw string)
 - #95017 (Derive Eq for std::cmp::Ordering, instead of using manual impl.)
 - #95072 (Re-enable parallel debuginfo tests)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=94100,94115,94848,94993,95017,95072)

### CODE REVIEW

**Comment by klensy** [comment]
No point in retrying, its failing bc of #94100

**Comment by Dylan-DPC** [comment]
thanks

@bors r-

**Pull request closed without merging**
