### PR TITLE
Overhaul improper_ctypes output

### LINKED ISSUE #42050: improper_ctypes behaves weird around function pointers
```Rust
#![deny(improper_ctypes)]

// Intentionally not #[repr(C)]
pub struct Foo;

#[repr(C)] // Expect error here that Bar is marked repr(C) but contains fn ptr referencing non-repr(C) type
pub struct Bar {
    // Alternatively expect error here that extern fn contains type that is non-repr(C).
    pub f: unsafe extern "system" fn(arg: *const Foo)
}

extern "system"{
    pub fn baz(bar: *const Bar); // Actually get error here implying Bar is not marked repr(C) even though it is
}

fn main() {

}
```
```
error: found non-foreign-function-safe member in struct marked #[repr(C)]: found struct without foreign-function-safe representation annotation in foreign module, consider adding a #[repr(C)] attribute to the type
  --> src/main.rs:12:21
   |
12 |     pub fn baz(bar: *const Bar); // Actually get error here implying Bar is not marked repr(C) even though it is
   |                     ^^^^^^^^^^
   |
note: lint level defined here
  --> src/main.rs:1:9
   |
1  | #![deny(improper_ctypes)]
   |         ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by hanna-kruppe**
This snowballed into a rather big set of improvements to the diagnostics of the improper_ctypes lint. See commits for details, including effects of each change on the `compile-fail/improper-ctypes.rs` test (now a UI test), which is pretty gnarly and hopefully not representative of real code, but covers a lot of different error cases.

Fixes #42050

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I think it'd be helpful to make that a UI test and have the before/after be a diff in GH (so separate commit moving the file)

**Comment by rkruppe** [comment]
Great idea, will do that (and fix the travis failure) tomorrow.

**Comment by rkruppe** [comment]
Done.

**Comment by rkruppe** [comment]
Rebased.

**Comment by estebank** [comment]
r=me once travis passes

**Pull request merged**
