### PR TITLE
remove LengthAtMost32 on AsRef/Borrow impl for array

### PR DESCRIPTION
**Pull request by burrbull**
Since I did not receive a response to #71373 I tried to do PR.

All tests are passed on my PC. Is there any reason not to do this?

Thanks.

### CODE REVIEW

**Comment by crlf0710** [comment]
When these bounds are removed, the resulting impl surface will not be expressible in current stable Rust. So we have to keep these bounds until const generics is stablized...

**Comment by withoutboats** [comment]
> When these bounds are removed, the resulting impl surface will not be expressible in current stable Rust. So we have to keep these bounds until const generics is stablized...

We don't. By removing these bounds, we would be committing that std will always be able to implement traits for all array types. Since that's always been a completely consensus goal for everyone involved in Rust, and we have no reason to believe we won't eventually stabilize const generics at least powerful enough to implement traits for array types, I think we should remove this bound and provide this functionality to people sooner, rather than later.

The decision to introduce this bound was always unnecessary conservatism.

@rfcbot fcp merge

**Comment by withoutboats** [comment]
@burbull if we're going to do this, we should remove `LengthAtMost32` entirely and change the implementation for all traits for arrays, not only asref/borrow.

**Comment by joshtriplett** [comment]
I agree: we're just committing that the standard library will implement such traits, which does not inherently commit us to any particular design for stable const generics outside the standard library; that just means we must provide a language facility the standard library can use for this purpose.

**Comment by lzutao** [comment]
Does this mean that now we could implement Copy, Hash, etc for all arrays?

**Comment by lcnr** [comment]
One thing which concerns me is `Default` for arrays, which afaik we can't implement using const generics rn
as the current `Default` impl does not have a `T: Default` bound for `N == 0`.

So I kind of fear that we will end up with `Default` being the only trait which is not implemented for all arrays.

**Comment by burrbull** [comment]
Closed in favour of 74060.

**Pull request closed without merging**
