### PR TITLE
[WIP] Introduce `SingletonCache` for use with ZST query keys

### PR DESCRIPTION
**Pull request by Aaron1011**
r? @ghost

### CODE REVIEW

**Comment by bjorn3** [comment]
Could it be used automatically for ZST query keys in the proc macro?

**Comment by bstrie** [comment]
Triage here, converting to a Draft PR to remove it from the triage queue.

**Comment by fee1-dead** [comment]
> Could it be used automatically for ZST query keys in the proc macro?

We already map `DefId` to `impl IntoQueryParam<DefId>` with declarative macros. It should be relatively easy to map all `()` keys to the `SingletonCache` in this PR.

**Comment by JohnCSimon** [comment]
Ping from triage:
@Aaron1011 what is the status of this PR?

**Comment by Dylan-DPC** [comment]
closing as inactive

**Pull request closed without merging**
