### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
14 commits in 7e484fc1a766f56dbc95380f45719698e0c82749..810cbad9a123ad4ee0a55a96171b8f8478ff1c03
2022-10-27 15:20:57 +0000 to 2022-11-02 21:04:31 +0000
- Update curl-sys (rust-lang/cargo#11326)
- Mention fix on build script deadlock (rust-lang/cargo#11325)
- Make cargo forward pre-existing CARGO if set (rust-lang/cargo#11285)
- Clean up workspace dependencies after cargo remove (rust-lang/cargo#11242)
- Update the outdated link for rust-semverver (rust-lang/cargo#11322)
- Fix broken link to compilation entry point (rust-lang/cargo#11317)
- Only remove fingerprints and build script artifacts of the requested package (rust-lang/cargo#10621)
- Newer anyhow features are required (rust-lang/cargo#11316)
- Clean stale git temp files (rust-lang/cargo#11308)
- Report crate size on package and publish (rust-lang/cargo#11270)
- add a note that some warnings (and/or errors) can be auto-fixed (rust-lang/cargo#10989)
- Update libcurl (rust-lang/cargo#11307)
- artifact deps shoud works when target field specified coexists with `optional = true` (rust-lang/cargo#11183)
- Fix singular verb in tests page (rust-lang/cargo#11300)

r? @ghost

### CODE REVIEW

**Comment by weihanglo** [comment]
@ehuss 

I believe this is an update that will become beta in less than 3 days. Could you double-check that all go well? Thanks!

**Comment by ehuss** [comment]
Beta already branched last week, so this will be in 1.67.

The process is documented at https://forge.rust-lang.org/release/process.html, but in summary:
1. Friday before the release, the version is bumped on nightly. The version bump PR marks the threshold of where the beta branch will be made.
2. Monday before the release, the beta branch gets updated to the commit just before the version bump from Friday.
3. Tuesday before the release, nightly starts using the new beta that was created the previous day.
4. Thursday is release day, the stable artifacts get promoted to the stable channel manifest.

So, if you want something to get in to the next beta, it needs to land before the Friday before the release.

@bors r+ p=1

**Comment by lqd** [comment]
Does this require e.g. changing installed native libraries on the perf machine for the cargo and rustc benchmarks to keep working ? 

(Don't worry about the perf regression it's just noise of course.)

@rustbot label: +perf-regression-triaged

**Pull request merged**
