### PR TITLE
[WIP] rustc_span: Symbol perf experiments

### PR DESCRIPTION
**Pull request by petrochenkov**
cc https://github.com/rust-lang/rust/pull/79425

### CODE REVIEW

**Comment by bjorn3** [comment]
Up to 3.7% slowdown.

**Comment by petrochenkov** [comment]
The results from slowing down `Symbol::intern` only (https://github.com/rust-lang/rust/pull/80420#issuecomment-751525537) are nearly identical to the results from the whole https://github.com/rust-lang/rust/pull/79425 (https://github.com/rust-lang/rust/pull/79425#issuecomment-749918610), so the hypothesis in https://github.com/rust-lang/rust/pull/79425#issuecomment-750294736 should be correct.

This means we either need a faster `Symbol::static_intern`, or a higher percent of hits in `Symbol::static_intern` to compensate for the potential second search.

**Comment by bjorn3** [comment]
Much smaller regressions, but a few benchmarks still regress. There are also a few small (<0.5%) improvements.

**Comment by petrochenkov** [comment]
Maybe it's spurious? The result doesn't make sense to me.
@bors try @rust-timer queue

**Comment by bjorn3** [comment]
~3.6% regression instead of ~3.4% for many benchmarks.

**Comment by petrochenkov** [comment]
Ha, so `phf::Map` is simply slower than regular `FxHashMap`.
Then in the case with cheap access to dynamic interner (Linux with [initial-exec TLS model](https://github.com/rust-lang/rust/pull/78201), which is used on the perf machine) moving more symbols to the static map just slows things down.

**Comment by bjorn3** [comment]
Most changes are now within noise but overall it is a slight (<0.1%) improvement.

**Pull request closed without merging**
