### PR TITLE
Add regression test for #24424.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/24424.

### CODE REVIEW

**Comment by frewsxcv** [comment]
What did I do incorrectly here?

```
thread 'main' panicked at 'Some tests failed
---- [compile-fail] compile-fail/issue-24424.rs stdout ----
	
error: /build/src/test/compile-fail/issue-24424.rs:14: unexpected "error": '14:1: 14:89: type annotations required: cannot resolve `T0: Trait0<'l0>` [E0283]'
error: /build/src/test/compile-fail/issue-24424.rs:14: expected error not found: type annotations required: cannot resolve `T0: main::Trait0<'l0>`
error: 1 unexpected errors found, 1 expected errors not found
status: exit code: 101
command: x86_64-unknown-linux-gnu/stage2/bin/rustc /build/src/test/compile-fail/issue-24424.rs -L x86_64-unknown-linux-gnu/test/compile-fail/ --target=x86_64-unknown-linux-gnu --error-format json -Z unstable-options -L x86_64-unknown-linux-gnu/test/compile-fail/issue-24424.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/compile-fail/issue-24424.stage2-x86_64-unknown-linux-gnu --cfg rtopt -C rpath -O -L x86_64-unknown-linux-gnu/rt
actual errors (from JSON output): [
    Error {
        line_num: 14,
        kind: Some(
            Error
        ),
        msg: "14:1: 14:89: type annotations required: cannot resolve `T0: Trait0<\'l0>` [E0283]"
    },
    Error {
        line_num: 14,
        kind: Some(
            Note
        ),
        msg: "14:1: 14:89: required by `Trait0`"
    }
]
expected errors (from test file): [
    Error {
        line_num: 14,
        kind: Some(
            Error
        ),
        msg: "type annotations required: cannot resolve `T0: main::Trait0<\'l0>`"
    }
]
```

**Comment by alexcrichton** [comment]
Looks like a note may need to be specified as well?

**Comment by frewsxcv** [comment]
Looks like the note was not the problem.

```
failures:
---- [compile-fail] compile-fail/issue-24424.rs stdout ----
	
error: /build/src/test/compile-fail/issue-24424.rs:14: unexpected "error": '14:1: 14:89: type annotations required: cannot resolve `T0: Trait0<'l0>` [E0283]'
error: /build/src/test/compile-fail/issue-24424.rs:14: expected error not found: type annotations required: cannot resolve `T0: main::Trait0<'l0>`
error: 1 unexpected errors found, 1 expected errors not found
status: exit code: 101
command: x86_64-unknown-linux-gnu/stage2/bin/rustc /build/src/test/compile-fail/issue-24424.rs -L x86_64-unknown-linux-gnu/test/compile-fail/ --target=x86_64-unknown-linux-gnu --error-format json -Z unstable-options -L x86_64-unknown-linux-gnu/test/compile-fail/issue-24424.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/compile-fail/issue-24424.stage2-x86_64-unknown-linux-gnu --cfg rtopt -C rpath -O -L x86_64-unknown-linux-gnu/rt
actual errors (from JSON output): [
    Error {
        line_num: 14,
        kind: Some(
            Error
        ),
        msg: "14:1: 14:89: type annotations required: cannot resolve `T0: Trait0<\'l0>` [E0283]"
    },
    Error {
        line_num: 14,
        kind: Some(
            Note
        ),
        msg: "14:1: 14:89: required by `Trait0`"
    }
]
expected errors (from test file): [
    Error {
        line_num: 14,
        kind: Some(
            Error
        ),
        msg: "type annotations required: cannot resolve `T0: main::Trait0<\'l0>`"
    },
    Error {
        line_num: 14,
        kind: Some(
            Note
        ),
        msg: "required by `Trait0`"
    }
]
thread '[compile-fail] compile-fail/issue-24424.rs' panicked at 'explicit panic', /build/src/tools/compiletest/src/runtest.rs:1077
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    [compile-fail] compile-fail/issue-24424.rs
test result: FAILED. 2377 passed; 1 failed; 11 ignored; 0 measured
```

**Comment by dsprenkels** [comment]
Diff. :smiley: 

```plain
type annotations required: cannot resolve `T0: Trait0<\'l0>`
type annotations required: cannot resolve `T0: main::Trait0<\'l0>`
                                               ^~~~~~
```

**Comment by frewsxcv** [comment]
Tests pass now.

**Pull request merged**
