### PR TITLE
Fix zero-size uninitialized boxes

### PR DESCRIPTION
**Pull request by SimonSapin**
Requesting a zero-size allocation is not allowed, return a dangling pointer instead.

CC https://github.com/rust-lang/rust/issues/63291#issuecomment-538692745

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me, thanks! Could this perhaps though check the `alloc.size()` calculation instead of recalculating the size of `T` and factoring in the length? Other than that though r=me with some tests

**Comment by JohnCSimon** [comment]
Ping from triage
@SimonSapin can you address @alexcrichton 's requests?
Thanks

**Comment by RalfJung** [comment]
Dang, I missed that when reviewing the original patch. :/

Do the `Rc`/`Arc` uninit constructors by any chance have similar issues?

**Comment by SimonSapin** [comment]
Heap allocations for `Rc` or `Arc` are never zero-size since they contain at least the refcounts

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/65482, @bors r-

**Comment by SimonSapin** [comment]
Removed the extra trailing newline, and ran a full `./x.py test`

@bors r=alexcrichton

**Pull request merged**
