### PR TITLE
Add more aliases for Unicode confusable chars

### PR DESCRIPTION
**Pull request by xen0n**
Building upon #29837, this PR:
- added aliases for space characters,
- distinguished square brackets from parens, and
- added common CJK punctuation characters as aliases.

This will especially help CJK users who may have forgotten to switch off IME when coding.

### CODE REVIEW

**Comment by nagisa** [comment]
I guess I’ll r+ this.

@bors r+

**Comment by alexcrichton** [comment]
Spurious because of #33391

**Pull request merged**
