### PR TITLE
Allow multiple libraries with the same hash.

### PR DESCRIPTION
**Pull request by taralx**
Removes the need for canonicalization to prevent #12459.

### CODE REVIEW

**Comment by retep998** [comment]
If we just want to know whether two files with the same name are actually the same file, I know there is a way on Windows to just check the IDs of files to see if they're the same (and it works with hard links too). Either `GetFileInformationByHandle` which returns a 64-bit ID + 32-bit volume ID which is unique on everything except ReFS which is for newer Windows only where you'd have to call `GetFileInformationByHandleEx` to get a `FILE_ID_INFO` with a 128-bit ID + 64-bit volume ID. No need to canonicalize or to allow duplicate files.

**Comment by taralx** [comment]
There's no need to know if two files are the same file. If they have the same hash in the filename, we can reasonably assume they are the same.

**Comment by taralx** [comment]
Ah, I see the problem. Is it okay if I just rework the patch, or would you prefer I stack on top?

**Comment by taralx** [comment]
*sigh* This gets complicated again. I'll resubmit after I work this one out.

**Pull request closed without merging**
