### PR TITLE
Change "Types/modules" title of search tab to be more accurate

### PR DESCRIPTION
**Pull request by JRegimbal**
From issue #45787. Used "In name" as per suggestion from @Seeker14491.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please remove the second commit (the merge one).

Also, I don't like much the new name. Maybe others like it or have propositions?

**Comment by JRegimbal** [comment]
Sorry about the merge I'm new to this. I removed it. The search is done by name, so maybe "By name" would be better? Is there a way to get a consensus on the new name?

**Comment by Seeker14491** [comment]
"By name" sounds good to me too.

**Comment by GuillaumeGomez** [comment]
@JRegimbal: It'll be debated if needed in the next docs meeting. If most like the name, then it'll get merged otherwise you'll be asked to update the name.

**Comment by JRegimbal** [comment]
Ah okay!

**Comment by shepmaster** [comment]
Triage ping @rust-lang/docs and @steveklabnik — we haven't heard from y'all in over two weeks; would someone mind giving an update?

**Comment by steveklabnik** [comment]
We didn't talk about it yet, we will next weds for sure.

**Comment by QuietMisdreavus** [comment]
We talked about this in today's docs team meeting, and decided to take the opportunity to tweak the naming in all the tabs, not just the main one. We settled on using "In Names", "In Parameters", and "In Return Types", in order. Can you change the tab names to those, instead?

**Comment by QuietMisdreavus** [comment]
Excellent! Thanks so much!

@bors r+ rollup

**Pull request merged**
