### PR TITLE
Fix false "never constructed" warnings for `Self::` variant paths

### LINKED ISSUE #64362: "variant is never constructed" lint appears to be incorrect?
This code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c03d4fa0a396d0476637d39c43bda0c2)) causes a "variant is never constructed" lint, even though the variant is constructed in the `FromStr` implementation:

```rust
use std::str::FromStr;

enum Foo {
    A { inner: () },
    B,
}

impl FromStr for Foo {
    type Err = ();
    
    fn from_str(s: &str) -> Result<Self, ()> {
        match s {
            "a" => Ok(Self::A { inner: () }),
            "b" => Ok(Self::B),
            _ => Err(()),
        }
    }
}
```

```
warning: variant is never constructed: `A`
 --> src/lib.rs:4:5
  |
4 |     A { inner: () },
  |     ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

Changing `Self` for the type name in `from_str` for `Foo` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=83856b4a0fbfa3510c8fe9eb3873ac8e)) compiles with the "field is never used" lint I would expect from this code.

Tested on `rustc 1.39.0-nightly (0b36e9dea 2019-09-09)`

This issue has been assigned to @jakubadamw via [this comment](https://github.com/rust-lang/rust/issues/64362#issuecomment-530559466).

### PR DESCRIPTION
**Pull request by seiyab**
Closes #64362 .

### CODE REVIEW

**Comment by seiyab** [comment]
What CI / PR does?
I can neither read detail log nor find docs.

**Comment by varkor** [comment]
@seiyab: huh, I'm actually not sure why those tests failed. There seemed to be no log attached, as you say. I've restarted them, so hopefully they'll work properly this time.

**Comment by seiyab** [comment]
They have a trouble to check out the code...
They check out to 01a37fef4bf59d4a3adac9b32b1cbc6197a5332a rather than refs/pull/71026/merge .
I don't know the reason.

**Comment by varkor** [comment]
Maybe you could try rebasing on top of the current master? If this doesn't work, I'll investigate further.

**Comment by seiyab** [comment]
@varkor 
Thank you to restart pipelines and friendly advice.
I'll try rebasing.

**Comment by seiyab** [comment]
@varkor 
Your advice helps.
`CI / PR (x86_64-gnu-tools)` succeeded.
Thank you very much 😄

**Comment by varkor** [comment]
@seiyab: thanks for the fix!

@bors r+ rollup

**Comment by seiyab** [comment]
@varkor 
Thank you for your review and merging.
I'm very happy and proud of contributing Rust, that I like 😆

**Pull request merged**
