### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #122597 (Show files produced by `--emit foo` in json artifact notifications)
 - #124486 (Add tracking issue and unstable book page for `"vectorcall"` ABI)
 - #125380 (Make `WHERE_CLAUSES_OBJECT_SAFETY` a regular object safety violation)
 - #125690 (ARM Target Docs Update)
 - #125865 (Fix ICE caused by ignoring EffectVars in type inference)
 - #125893 (Handle all GVN binops in a single place.)
 - #125909 (rustdoc: add a regression test for a former blanket impl synthesis ICE)
 - #125918 (Revert: create const block bodies in typeck via query feeding)
 - #125919 (Remove stray "this")

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=122597,124486,125380,125690,125865,125893,125909,125918,125919)

### CODE REVIEW

**Comment by compiler-errors** [comment]
@matthiaskrgr what does this codegen test have to do with WHERE_CLAUSES_OBJECT_SAFETY?

**Comment by matthiaskrgr** [comment]
I saw that the failing test was from CFI and you also changed CFI code in your pt :thinking: 
https://github.com/rust-lang/rust/pull/125380/files#diff-f07eb5006a66b8220716cfbde31d17e3d100185e08c0116fd8074c60a169662e

**Pull request closed without merging**
