### PR TITLE
Update Clang & build MSVC LLVM with it

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a general update of our builders to Clang 9, and then it also attempts to tackle a bit of #66192 by building LLVM for rustc with Clang, not with the system `cl.exe` on MSVC.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Ok I think the `>-` vs `>` did the trick in terms of trailing newlines. This is gonna time out a few times while all the caches are primed, and I'd like to avoid merging until I get some more timing information for https://github.com/rust-lang/rust/issues/66192 as well.

**Comment by Mark-Simulacrum** [comment]
Changes look quite reasonable (and I expect the LLVM bit might help us out on our builders), r=me when ready.

**Comment by Centril** [comment]
Yielding to r0llup, @bors retry

**Comment by Centril** [comment]
oh woops; sorry! -- thought this was pending :(

**Comment by alexcrichton** [comment]
@bors: r=Mark-Simulacrum

Ok I think everything is configured right now, but this PR will take some time to prime various caches. Unfortunately this is only about a 5% win on MSVC, so something else is still awry with respect to https://github.com/rust-lang/rust/issues/66192 I think.

**Pull request merged**
