### PR TITLE
Hide type declarations by default

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I'm not very happy for the moment about the rendering but the bases are here:

screen shot 2018-03-27 at 11 56 27

r? @QuietMisdreavus

### CODE REVIEW

**Comment by killercup** [comment]
Kinda skeptical if we want to do this when there are public fields without doc comments, but otherwise r=me

**Comment by QuietMisdreavus** [comment]
@killercup Fields without docs still appear in the main listing, regardless of whether they have docs on them or not. Strictly speaking, there's no true loss of information going on - we're just auto-folding the bit that takes up more room.

**Comment by killercup** [comment]
@QuietMisdreavus yeah, as I've said offline, I'm fine with this change then :)

**Comment by QuietMisdreavus** [comment]
@bors retry

Appveyor timeout

**Comment by kennytm** [comment]
@bors retry p=15

3 hour timeout.

**Comment by squishy-clouds** [comment]
Since this change made it to the nightly docs, I have found myself constantly having to open the type declaration. To copy/paste trait function's signatures to implement them, or to see the type/lifetime parameters for the type, for example.

Usually public fields are documented, but when they're not this change makes things less convenient. As far as I can tell associated types have the same issue, which is, imo, much more important than fields because forgetting them when `impl`ing (because they're hidden away) gives you a compile error and that might be frustrating because you thought you didn't see any associated type in the docs.

It also isn't documented anywhere else whether an item is a struct, enum, trait, etc. except through the color of the name, so looking to see what kind of item a thing is means I have to open the type declaration, unless I've memorized what the colors mean. I imagine that might make things slightly more annoying for color-blind people as well.

I don't know why this change was made in the first place, I couldn't find any other issues or PRs about this, if its because of traits like `Iterator` whose definition takes up the whole screen, maybe could this change just be applied to longer definitions?

**Comment by GuillaumeGomez** [comment]
Because generally, it isn't wanted by the users since you have the fields/variants listed just below with all needed information and documentation. This is "just" the rust code declaration. However, I think I'll start writing a settings menu to allow users to have a better control over a few things.

**Comment by newpavlov** [comment]
I am also not happy with this change. Often for me type declarations are sufficient enough to remember all details which I want with a single glance, while with documented fields it's significantly less convenient/fast. So I believe this change has introduced an unpleasant speed bump for proficient users.

**Comment by GuillaumeGomez** [comment]
You can change the corresponding settings to have like it was before this change.

**Comment by newpavlov** [comment]
IIUC you can't do anything for docs on doc.rust-lang.org. Maybe it will make sense to add a small js+cookie logic, e.g. if you've opened type declaration is stays open and vice versa?

**Comment by GuillaumeGomez** [comment]
It should be saved though... At least it works as expected for me. If you have a bug with settings, please open an issue.

**Pull request merged**
