### PR TITLE
Move back templates into html folder

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow-up of https://github.com/rust-lang/rust/pull/92526.

r? @notriddle

### CODE REVIEW

**Review by notriddle — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
You have r+ rights now normally. Give it a try! :D

**Comment by notriddle** [comment]
Okay,

bors r+

**Comment by GuillaumeGomez** [comment]
:tada:

**Comment by GuillaumeGomez** [comment]
Rebased... It's very conflict-prone so I'll raise its a priority a bit.

@bors: r=notriddle p=1

**Pull request merged**
