### PR TITLE
Don't build `compiler_builtins` with `-C panic=abort`

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by jyn514** [comment]
Can you give some more context? Why is this obsolete? What changed?

**Comment by tshepang** [comment]
The linked issue (#43095) was resolved, and `eh_unwind_resume` was removed (f4f91f0b2f98ddf9ea36c4bc200ebda2cd898230).

**Comment by jyn514** [comment]
I see. Does that mean we can also remove the `crate_name == Some("compiler_builtins")` check here and only use panic=abort unconditionally for the `panic_abort` crate?

**Comment by tshepang** [comment]
I suspect so, but don't really know. Should I research it?

**Comment by jyn514** [comment]
That would be helpful, yeah. If you do the following things it would make me confident in merging this:
- Verify we have at least one UI test for panic=abort
- Remove the bit of code special casing compiler-builtins
- Run the test at stage 1 and verify it still passes

**Comment by jyn514** [comment]
@tshepang do you know when you'll have time to work on this?

**Comment by tshepang** [comment]
Thanks for the reminder... would src/test/ui/cfg/cfg-panic-abort.rs be an example of a UI test you asked for?

**Comment by jyn514** [comment]
Sure, looks reasonable :)

**Pull request merged**
