### PR TITLE
Remove attribute `#[link_args]`

### LINKED ISSUE #29596: Tracking issue for `link_args` stabilization
This issue tracks stabilization for the `#[link_args]` attribute.

### PR DESCRIPTION
**Pull request by petrochenkov**
Closes https://github.com/rust-lang/rust/issues/29596

The attribute could always be replaced with `-C link-arg`, but cargo didn't provide a reasonable way to pass such flags to rustc.
Now cargo supports `cargo:rustc-link-arg*` directives in build scripts (https://doc.rust-lang.org/cargo/reference/unstable.html#extra-link-arg), so this attribute can be removed.

### CODE REVIEW

**Comment by nagisa** [comment]
SGTM. This seems somewhat similar in direction as the also very well motivated removal of the `#[crate_type]` and `#[crate_name]` attributes.

@bors r+

**Comment by petrochenkov** [comment]
This was fast.
I nominated this for the compiler team to make the change visible to some wider audience.
Anyway, if there are some critical concerns, then it can be reverted (which I don't expect though).

**Comment by Dirbaio** [comment]
With this removal it's now impossible to pass *different* link_args to different binaries within the same crate. `cargo:rustc-link-arg=FLAG` applies to all binaries, while this allowed specifying different args in each main.rs binary.

Is there some workaround for this?

**Comment by petrochenkov** [comment]
@Dirbaio 
It's better to ask about this on cargo repo, it's unlikely that any relevant person will see this comment here.
Tracking issue for `cargo:rust-link-arg*` is https://github.com/rust-lang/cargo/issues/9426.

**Pull request merged**
