### PR TITLE
Pass on null handle values to child process

### LINKED ISSUE #101645: Parent process with "windows" subsystem can't properly create console child process
I tried this code:

App P:
```rust
#![windows_subsystem = "windows"]

fn main() {
    std::process::Command::new("<path_to_app_C>").spawn().unwrap();
    std::thread::sleep(std::time::Duration::from_secs(100));
}
```
App C:
```rust
fn main() {
    loop {
        println!("Hello World!");
        std::thread::sleep(std::time::Duration::from_secs(1));
    }
}
```

Build this in Windows.

#### I expected to see this happen:

Since `P` has "windows" subsystem, it will create no console window (i.e. no conhost.exe process). Since `C` is a console app, when the process is created, I expect to see one console window that prints "Hello World" infinitely.

#### Instead, this happened: *explanation*

App `C` creates its console window but no text is printed.

#### What I suspect the cause of the issue

In Windows, spawn() eventually calls to `CreateProcessW` with a `STARTUPINFO`, whose [`dwFlags` is hard coded to `STARTF_USESTDHANDLES`](
https://github.com/rust-lang/rust/blob/1517f5de01c445b5124b30f02257b02b4c5ef3b2/library/std/src/sys/windows/process.rs#L257). Additionally, it also [get device handles of stdin, stdout and stderr](https://github.com/rust-lang/rust/blob/1517f5de01c445b5124b30f02257b02b4c5ef3b2/library/std/src/sys/windows/process.rs#L315) with `GetStdHandle`, and set them to the `STARTUPINFO`. Since app `P` uses "windows" subsystem, it does not have console. stdout is always `INVALID_HANDLE_VALUE`. Combining `STARTF_USESTDHANDLES` with `INVALID_HANDLE_VALUE` in `STARTUPINFO` causes the unexpected behavior.

If I make a call to `CreateProcessW` with same parameters except a "zeroed" `STARTUPINFO`, it exhibits the correct behavior.

#### Suggestion

spawn() should only conditionally set the `STARTF_USESTDHANDLES` flag if it can obtain those device handles, and never set any of those handles `INVALID_HANDLE_VALUE`. Like this (pseudo code):
```rust
let mut si = zeroed_startupinfo();
si.cb = mem::size_of::<c::STARTUPINFO>() as c::DWORD;

si.hStdInput = stdin.to_handle().unwrap_or(0);
si.hStdOutput = stdout.to_handle().unwrap_or(0);
si.hStdError = stderr.to_handle().unwrap_or(0);

if si.hStdInput != 0 || si.hStdOutput != 0 || si.hStdError != 0 {
    si.dwFlags |= c::STARTF_USESTDHANDLES;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-pc-windows-msvc
release: 1.63.0
LLVM version: 14.0.5
```

### PR DESCRIPTION
**Pull request by ChrisDenton**
Fixes #101645

In Windows, stdio handles are (semantically speaking) `Option<Handle>` where `Handle` is a non-zero value. When spawning a process with `Stdio::Inherit`, Rust currently turns zero values into `-1` values. This has the unfortunate effect of breaking console subprocesses (which typically need stdio) that are spawned from gui applications (that lack stdio by default) because the console process won't be assigned handles from the newly created console (as they usually would in that situation). Worse, `-1` is actually [a valid handle](https://doc.rust-lang.org/std/os/windows/io/struct.OwnedHandle.html) which means "the current process". So if a console process, for example, waits on stdin and it has a `-1` value then the process will end up waiting on itself.

This PR fixes it by propagating the nulls instead of converting them to `-1`.

While I think the current behaviour is a mistake, changing it (however justified) is an API change so I think this PR should at least have some input from t-libs-api. So choosing at random...

r? @joshtriplett

### CODE REVIEW

**Comment by workingjubilee** [comment]
It's too bad we can't run Crater on Windows.

I am in favor of this change as a bug fix but I should note that I feel we still have an uncovered API use-case in situations like https://github.com/rust-lang/rust/issues/105203 so the underlying issue of wanting a clearer API for "please make something new here" has not been resolved.

Also I should note that previously we removed some code that also did this conversion: https://github.com/rust-lang/rust/commit/7ddf41c7b10e46c231180cecbbb5e78e0dd12ff8

I feel like we should have some kind of test here.

**Comment by kryptan** [comment]
Does this PR rely on some undocumented behaviour? Windows [documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa) doesn't seem to say what happens when you set `STARTF_USESTDHANDLES` but then pass `NULL`s as std handles.

GUI apps can have stdio handles. Inheriting them while still creating a new useless empty console window doesn't look like a sane default behaviour but it is what happens with or without this PR.

**Comment by workingjubilee** [comment]
That's kind of why I linked that commit... it documented what can happen when these values are `NULL`. Apparently the answer is Unfun.

**Comment by ChrisDenton** [comment]
> Also I should note that previously we removed some code that also did this conversion: https://github.com/rust-lang/rust/commit/7ddf41c7b10e46c231180cecbbb5e78e0dd12ff8

That commit only removed a no-op. The code already turned nulls to `INVALID_HANDLE_VALUE` at an earlier point (as noted in the commit description) so removing it had not effect on behaviour. This PR changes that earlier code so that it doesn't set `INVALID_HANDLE VALUE` (aka `-1`, which is in fact a valid handle value).

> Does this PR rely on some undocumented behaviour? Windows [documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa) doesn't seem to say what happens when you set `STARTF_USESTDHANDLES` but then pass `NULL`s as std handles.

I'm uncertain if this is documented somewhere but in any case this PR does not actually rely on any particular behaviour. A null handle is an invalid handle value (unlike `INVALID_HANDLE_VALUE` which is a valid handle value) so its options are to either pass on null handles unchanged or replace them with console handles. Either behaviour works for us, or at least works better than the current behaviour.

> GUI apps can have stdio handles. Inheriting them while still creating a new useless empty console window doesn't look like a sane default behaviour but it is what happens with or without this PR.

A console process can be spawned detached if you do not want a console to actually be created. Even if a console is created while inheriting handles, it's not necessarily useless. It can still be read from a written to. But, as you say, this PR isn't changing that behaviour.

**Comment by thomcc** [comment]
Super sorry for the delay here (busy and didn't want to half-ass reviews). This looks good to me.

@bors r+

**Comment by ChrisDenton** [comment]
No worries! I'm well aware people have lives outside of Rust and a week is not long to wait at all. 😊

**Pull request merged**
