### PR TITLE
NLL test for mutating &mut references

### PR DESCRIPTION
**Pull request by ritiek**
As mentioned in #46361.

cc @nikomatsakis?

### CODE REVIEW

**Comment by matthewjasper** [comment]
Should this be replacing [this](https://github.com/rust-lang/rust/blob/15a1e2844dfea7850be5c6c901b67ceff370b0eb/src/test/run-pass/borrowck/borrowck-nll-iterating-and-updating.rs) test?

**Comment by ritiek** [comment]
Sure! Where should we keep the merged test though? `src/test/run-pass/nll/mutating_references.rs` or `src/test/run-pass/borrowck/borrowck-nll-iterating-and-updating.rs`?

**Comment by nikomatsakis** [comment]
@ritiek I prefer the `nll` directory for now, I think

**Comment by ritiek** [comment]
OK. So now we have the merged test in `src/test/run-pass/nll/mutating_references.rs`.

**Comment by nikomatsakis** [comment]
@bors r+

@ritiek great!

**Pull request merged**
