### PR TITLE
Doc fix: Do not mention next project in book/guessing-game

### LINKED ISSUE #32936: docs: add link for the next project in the guessing-game doc
I am learning rust and reading the book for the first time

The [guessing-game](https://github.com/rust-lang/rust/blob/01d76099f261abe50342d9261fad618c5323274b/src/doc/book/guessing-game.md#complete) section mentions a "Next Project" at the very end

> Our next project will show off even more.

We can add a link to that project ?

### PR DESCRIPTION
**Pull request by deepak**
fixes https://github.com/rust-lang/rust/issues/32936

### CODE REVIEW

**Comment by Manishearth** [comment]
Perhaps remove this entirely?

**Comment by deepak** [comment]
@Manishearth as a beginner, I like the old one better. It informs me that:

1. I have successfully completed a challenge. feels good
2. I have learnt a bunch of stuff. feels good again
3. I can look forward to another problem. looking forward to feeling good again

Just telling me that i have completed a challenge feels worse by comparison
but that is just me probably

I would have liked another problem to go through. but when will that stop :-)

**Comment by Manishearth** [comment]
Yes, but it seems a bit out of place. The chapter was already concluded with the previous sentence. If this could be moved above and edited to make more sense that would be fine.

**Comment by deepak** [comment]
@Manishearth ok. fixing it

**Comment by Manishearth** [comment]
@bors r+ rollup

thanks!

**Pull request merged**
