### PR TITLE
use find(x) instead of filter(x).next()

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
This seems clearly better to me. Can we add a line to the documentation of `find` stating that it is equivalent to `filter().next()`? There's a similar note for [`find_map`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find_map).

@bors r+ rollup=always

**Comment by Dylan-DPC** [comment]
better to r+ prs only after the CI passes :)

**Comment by Dylan-DPC** [comment]
failed in rollup

@bors r-

**Comment by matthiaskrgr** [comment]
rebased

**Comment by Dylan-DPC** [comment]
bors r=ecstatic-morse

**Pull request merged**
