### PR TITLE
Register snapshots (2015-05-24 ba0e1cd).

### PR DESCRIPTION
**Pull request by eddyb**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Yay! Is this still blocked on anything @eddyb? I'd also like to get this in to get MSVC bootstrapping itself.

We've retroactively registered bitrig snapshots in the past, so we don't necessarily need to block on those becoming available.

**Comment by dhuseby** [comment]
My builder is back up and running now that I fixed the VM config.  If we hold off for a few hours, we'll have a bitrig stage 3 snap to include.

**Comment by eddyb** [comment]
@dhardy the same build that failed twice, right? It would be nice for it to be the same revision.
@alexcrichton if you're okay with the zeroed hash and replacing it later (with a snapshot built from that same revision), feel free to r+.

**Comment by dhuseby** [comment]
@eddyb the snapshot at that revision is now building: http://buildbot.rust-lang.org/builders/snap3-bitrig-64/builds/124

**Comment by alexcrichton** [comment]
I'll throw this onto bors for now just to get it in the queue (may weed out some errors), and we can always pull in the bitrig snapshots once they're ready!

@bors: r+ 7eee86a0d899356f81824d3f797317eab04096d3

**Comment by eddyb** [comment]
@dhuseby Thanks for the fixing bitrig, seems we have [a snapshot](http://buildbot.rust-lang.org/builders/snap3-bitrig-64/builds/125).

**Comment by alexcrichton** [comment]
I was a little surprised to see that *usage* of a `const fn` is stable today even if defining it is not. This means that calling `UnsafeCell::new` to create a static `UnsafeCell` is now stable (which I think was unintentional). I believe that @nikomatsakis is working on a patch to feature-gate usage, however.

**Comment by pythonesque** [comment]
Oh my god this is amazing.

**Pull request merged**
