### PR TITLE
vxWorks is using "invalid argument" instead of "Invalid argument" in reporting invalid options

### PR DESCRIPTION
**Pull request by BaoshanPang**

### CODE REVIEW

**Comment by BaoshanPang** [comment]
cc @n-salim 
cc @maya-cm

**Comment by rkruppe** [comment]
The diff seems fine to rubber-stamp, but Rust has a [no merge policy](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#pull-requests) so please rebase ae2bb7ba9962bb860a5c51ecad9f758eeba847c9 to get rid of the merge commits (preserving that it was authored by @bpangWR, of course).

**Comment by BaoshanPang** [comment]
I have been always using my personal account 'BaoshanPang' to make changes in github, but not sure why sometimes it recognize me as bpangWR which is the company account created by me.

**Comment by rkruppe** [comment]
Ah, OK, then authorship is no concern, please just get rid of the merge commits in whatever way is most convenient.

**Comment by BaoshanPang** [comment]
Using a new branch is easier for me, I can't find a way to remove the "merge commits" in the current branch.
A new PR is created https://github.com/rust-lang/rust/pull/65187.

**Pull request closed without merging**
