### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by RalfJung**
Successful merges:

 - #70950 (extend NLL checker to understand `'empty` combined with universes)
 - #71205 (rustc: fix check_attr() for methods, closures and foreign functions)
 - #71540 (Suggest deref when coercing `ty::Ref` to `ty::RawPtr`)
 - #71559 (Detect git version before attempting to use --progress)
 - #71567 (Handle build completion message from Cargo)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
That's weird, there's not even an error?
```
[TIMING] ToolBuild { compiler: Compiler { stage: 0, host: "x86_64-apple-darwin" }, target: "x86_64-apple-darwin", tool: "unstable-book-gen", path: "src/tools/unstable-book-gen", mode: ToolBootstrap, is_optional_tool: false, source_type: InTree, extra_features: [] } -- 89.248


command did not execute successfully: "/Users/runner/runners/2.166.4/work/1/s/build/x86_64-apple-darwin/stage0-tools-bin/unstable-book-gen" "/Users/runner/runners/2.166.4/work/1/s/src" "/Users/runner/runners/2.166.4/work/1/s/build/x86_64-apple-darwin/md-doc/unstable-book"
expected success, got: signal: 9


failed to run: /Users/runner/runners/2.166.4/work/1/s/build/bootstrap/debug/bootstrap dist
Build completed unsuccessfully in 0:01:32
```
Cc @rust-lang/infra 

Giving up on this rollup then.

**Comment by Dylan-DPC** [comment]
created a new rollup

**Comment by Dylan-DPC** [comment]
unstable book was broken yest i think, so will check if the problem persists in the new rollup

**Pull request closed without merging**
