### PR TITLE
Update llvm-project to latest origin/rustc/10.0-2020-05-05 commit 

### PR DESCRIPTION
**Pull request by AdrianCX**
which includes LVI segfault fix when building https://github.com/fortanix/rust-sgx/issues/267
And a few earlier commits.

### CODE REVIEW

**Comment by cuviper** [comment]
I think this should wait for the submodule update in #74116 to land, since that has others changes included.

@eddyb was waiting for that PR to then pull the wasm-determinism fix, which you've included here too.

**Comment by eddyb** [comment]
@AdrianCX can you rebase? I think we can just approve the PR afterwards.

**Comment by AdrianCX** [comment]
thanks, rebased

**Pull request merged**
