### PR TITLE
[WIP] Promote types which allocate to an arena to avoid the use of Lrc

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 63ac4af3d095077d1cdd472672222d19f04e3f5e

**Comment by Zoxc** [comment]
@rust-timer build 4d2ae120e6320485958ed38a8f118012bd7cef44

**Comment by Zoxc** [comment]
@rust-timer build 2afdfe12f6befb3333c5a9e38303cb8b147d7b44

**Comment by Dylan-DPC** [comment]
ping from triage @Zoxc tests are failling on CI, can you address those issues?

**Pull request closed without merging**
