### PR TITLE
Use `target_vendor = "apple"` instead of `target_os = "..."`

### PR DESCRIPTION
**Pull request by madsmtm**
Use `target_vendor = "apple"` instead of `all(target_os = "macos", target_os = "ios", target_os = "tvos", target_os = "watchos", target_os = "visionos")`.

The apple targets are quite close to being identical, with iOS, tvOS, watchOS and visionOS being even closer, so using `target_vendor` when possible makes it clearer when something is actually OS-specific, or just Apple-specific.
Note that `target_vendor` will [be deprecated in the future](https://github.com/rust-lang/rust/issues/100343), but not before an alternative (like `target_family = "apple"`) is available.

While doing this, I found various inconsistencies and small mistakes in the standard library, see the commits for details. Will follow-up with an extra PR for a similar issue that need a bit more discussion. EDIT: https://github.com/rust-lang/rust/pull/124494

Since you've talked about using `target_vendor = "apple"` in the past:
r? workingjubilee

CC @simlay, @thomcc
@rustbot label O-macos O-ios O-tvos O-watchos O-visionos

### CODE REVIEW

**Comment by QuentinPerez** [comment]
Is `target_vendor` deprecated ? see https://github.com/rust-lang/lang-team/issues/102

**Comment by madsmtm** [comment]
> Is `target_vendor` deprecated ? see [rust-lang/lang-team#102](https://github.com/rust-lang/lang-team/issues/102)

It isn't yet, I linked the tracking issue in the PR description, it's [here](https://github.com/rust-lang/rust/issues/100343), we expect an alternative like `target_family = "apple"` to be available before it is though, once that does happen it should be easy to find/replace `target_vendor = "apple"` with that.

**Comment by workingjubilee** [comment]
...honestly I had a suspicion that this might uncover some bugs but this is impressive.

**Comment by workingjubilee** [comment]
@madsmtm So, I can r+ this without knowing the answer to this question, but for full transparency: Do the Rust stdlib tests pass on the simulators? Are there any current gaps? It would be good to know what the "current situation" seems to be.

**Comment by madsmtm** [comment]
> Do the Rust stdlib tests pass on the simulators? Are there any current gaps? It would be good to know what the "current situation" seems to be.

It is quite difficult to run a test suite on the simulators, and I'm not experienced enough in Rust's bootstrapping setup to tell you exactly how to do it for this repo (though @simlay probably has some more or less cursed solution using Dinghy), so I'll admit I don't know the answer to your question.

But I can try to run the test suite under Mac Catalyst, that might reveal some issues.

**Comment by workingjubilee** [comment]
Ah, I had mostly asked because you had mentioned running some tests in the last commit! I'm happy with that answer, at the moment, and any fixes can be addressed as followups.

@bors r+

**Comment by thomcc** [comment]
I'm not sure that handling va_list the same way on watchOS that it's handled on the other apple OSes is correct, given that it's a different architecture.

**Comment by workingjubilee** [comment]
@thomcc ( I think it might be but only because IIRC the protocol on Arm is to pass everything on the stack, 32-bit or 64-bit. )

**Comment by workingjubilee** [comment]
Yeah, the trick where you can transparently swap between specific args for an x86 function call and a variadic function call doesn't work on Apple hardware: https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Update-code-that-passes-arguments-to-variadic-functions

**Comment by thomcc** [comment]
Apple has a non-standard varargs calling convention for aarch64, I don't know if they follow it for arm64_32.

**Comment by workingjubilee** [comment]
It seems to be the same but with a different slot size? https://github.com/llvm/llvm-project/commit/44e5879f0fb7c28b90e8042fde81bba30b4090a3#diff-355c1d9d3832a837c9e90bb1b51fdbdcbbb36deff64c545644b96f6692baceaf

**Comment by workingjubilee** [comment]
And these call into compiler intrinsics so it is unlikely there is anything that libstd changes can do to make this more or less incorrect.

**Comment by thomcc** [comment]
I see. Does our va_list type match the declaration in C too? I guess I could check this...

**Comment by workingjubilee** [comment]
The advantage of merging the libstd changes is that it makes it much easier to test if these implementations are incorrect. :^)

**Comment by madsmtm** [comment]
Modifying `Cargo.toml` and `src/bootstrap/Cargo.toml` to depend on a newer version of `cc`, and running:
```sh
./x test --target=aarch64-apple-ios-macabi library/std
./x test --target=aarch64-apple-ios-macabi --no-fail-fast --skip=tests/rustdoc-js --skip=tests/rustdoc-js-std --skip=tests/debuginfo tests
```

Produces errors in the following tests:
```
    [codegen] tests/codegen/gdb_debug_script_load.rs
    [run-make] tests/run-make/emit-stack-sizes
    [ui] tests/ui/abi/stack-probes.rs
    [ui] tests/ui/abi/stack-probes-lto.rs
    [ui] tests/ui/command/command-argv0.rs
    [ui] tests/ui/env-funky-keys.rs
    [ui] tests/ui/intrinsics/intrinsic-alignment.rs
    [ui] tests/ui/issues/issue-18804/main.rs
    [ui] tests/ui/link-section.rs
    [ui] tests/ui/linkage-attr/linkage1.rs
    [ui] tests/ui/osx-frameworks.rs
    [ui] tests/ui/runtime/out-of-stack.rs
    [ui] tests/ui/structs-enums/enum-rec/issue-17431-6.rs
    [ui] tests/ui/structs-enums/rec-align-u64.rs
```

Both before and after this PR. I suspect the stack probing, environment and argv0 to be real issues, and the rest to be under-specified tests that were only tweaked for macOS and not Apple in general. Will likely fix this in another PR at some point.

**Comment by madsmtm** [comment]
Seems to me like the `va_list` implementation should use `*mut c_void` on Apple AArch64 targets, see https://github.com/llvm/llvm-project/blob/llvmorg-18.1.4/clang/lib/Basic/Targets/AArch64.cpp#L1617

Also, I think CI failed because it was cancelled, or something? Can't really tell from the logs :/

**Comment by workingjubilee** [comment]
It looks like we do in fact use the right one for the appleOS platforms: https://github.com/rust-lang/rust/blob/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/ffi/mod.rs#L207-L235

Yeah I think it was just a timeout.

@bors retry

**Pull request merged**
