### PR TITLE
fix formatting inconsistencies

### PR DESCRIPTION
**Pull request by fprasx**
This change is best appreciated using the side-by-side diff viewer. Compiles locally, but tidy is raising some errors.

Unccl Ncevy Sbbyf!

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I really hope there isn't any kind of backdoor snuck in somewhere /s

**Comment by fprasx** [comment]
I pinky promise there isn't one

**Comment by matthiaskrgr** [comment]
good enough, thanks
@​bors r+

**Comment by Nilstrieb** [comment]
I like it a lot, thanks.
@rust-lang/style does this sound good to you?

**Comment by PatchMixolydic** [comment]
I strongly prefer this style:
```rust
use std::env;

fn main()
   {
      let target_os = env::var("CARGO_CFG_TARGET_OS");
      let target_env = env::var("CARGO_CFG_TARGET_ENV");
      if Ok("windows") == target_os.as_deref() && Ok("msvc") == target_env.as_deref() {
         set_windows_exe_options();}
      else {
         println!("cargo:rerun-if-changed=build.rs");}}// Avoid rerunning the build script every time.

fn set_windows_exe_options()
   {// Add a manifest file to rustc.exe.
      static WINDOWS_MANIFEST_FILE: &str = "Windows Manifest.xml";

      let mut manifest = env::current_dir().unwrap();
      manifest.push(WINDOWS_MANIFEST_FILE);

      println!("cargo:rerun-if-changed={WINDOWS_MANIFEST_FILE}");// Embed the Windows application manifest file.
      println!("cargo:rustc-link-arg-bin=rustc-main=/MANIFEST:EMBED");
      println!("cargo:rustc-link-arg-bin=rustc-main=/MANIFESTINPUT:{}", manifest.to_str().unwrap());// Turn linker warnings into errors.
      println!("cargo:rustc-link-arg-bin=rustc-main=/WX");}
```

Benefits:
* Newline before function body helps differentiate control flow and functions, which currently look too similar.
* Indenting the braces only makes sense, as they are part of the function body.
* Stacking closing delimiters onto the last statement is a battle-tested technology used in various Lisps. It helps the delimiters just fade away, which improves readability.
* Comments are attached to what they are commenting.
* Three space indentation, as Ferris intended.

Drawbacks:
* Absolutely _none_.
* Absolutely none!
* Seriously, just like every good `MaybeIncorrect`/`restriction` lint in Clippy!

**Comment by Jules-Bertholet** [comment]
This new format still wastes excessive horizontal space. Please use `U+200E` LEFT-TO-RIGHT MARK or `U+200F` RIGHT-TO-LEFT MARK instead of ASCII space character to compact the formatting further.

**Pull request closed without merging**
