### PR TITLE
Qualify constness in rvalue expressions for promotion to globals.

### PR DESCRIPTION
**Pull request by eddyb**
This includes everything necessary for promoting borrows of constant rvalues to `'static`.
That is, `&expr` will have the type `&'static T` if `const T: &'static T = &expr;` is valid.
There is a small exception, dereferences of raw pointers, as they misbehave.
They still "work" in constants as I didn't want to break legitimate uses (are there any?).

The qualification done here can be expanded to allow simple CTFE via `const fn`.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
This looks great: r+

I have some nits and minor comments, which you can find as comments in this commit: https://github.com/nikomatsakis/rust/commit/feb8ca7f7aad366aafdc437d982e67cd0d6f9489

**Comment by eddyb** [comment]
Blocked on #21996 :(.

**Comment by eddyb** [comment]
I've finally managed to run this under OSX - the following (`check-stage1-rpass`) failures do **not** show up on linux (same arch, x64):
```rust
failures:

---- [run-pass] run-pass/deref-rc.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/deref-rc.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: *x == [1, 2, 3, 4]', /Users/eddy/Documents/rust/src/test/run-pass/deref-rc.rs:15

------------------------------------------

thread '[run-pass] run-pass/deref-rc.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452


---- [run-pass] run-pass/issue-15080.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/issue-15080.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: result == [2, 4]', /Users/eddy/Documents/rust/src/test/run-pass/issue-15080.rs:29

------------------------------------------

thread '[run-pass] run-pass/issue-15080.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452


---- [run-pass] run-pass/overloaded-deref-count.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/overloaded-deref-count.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: `(left == right) && (right == left)` (left: `[1, 2]`, right: `[1, 2]`)', /Users/eddy/Documents/rust/src/test/run-pass/overloaded-deref-count.rs:85

------------------------------------------

thread '[run-pass] run-pass/overloaded-deref-count.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452


---- [run-pass] run-pass/packed-struct-generic-layout.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/packed-struct-generic-layout.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: transd == [1, 2, 129, 129]', /Users/eddy/Documents/rust/src/test/run-pass/packed-struct-generic-layout.rs:34

------------------------------------------

thread '[run-pass] run-pass/packed-struct-generic-layout.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452


---- [run-pass] run-pass/packed-struct-layout.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/packed-struct-layout.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: transd == [1, 2, 3, 4]', /Users/eddy/Documents/rust/src/test/run-pass/packed-struct-layout.rs:29

------------------------------------------

thread '[run-pass] run-pass/packed-struct-layout.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452


---- [run-pass] run-pass/packed-tuple-struct-layout.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/packed-tuple-struct-layout.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: transd == [1, 2, 3, 4]', /Users/eddy/Documents/rust/src/test/run-pass/packed-tuple-struct-layout.rs:23

------------------------------------------

thread '[run-pass] run-pass/packed-tuple-struct-layout.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452


---- [run-pass] run-pass/vec-matching-autoslice.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/vec-matching-autoslice.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: [a, b] == [2, 3]', /Users/eddy/Documents/rust/src/test/run-pass/vec-matching-autoslice.rs:16

------------------------------------------

thread '[run-pass] run-pass/vec-matching-autoslice.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452


---- [run-pass] run-pass/vec-matching.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/vec-matching.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: `(left == right) && (right == left)` (left: `[2]`, right: `[2]`)', /Users/eddy/Documents/rust/src/test/run-pass/vec-matching.rs:44

------------------------------------------

thread '[run-pass] run-pass/vec-matching.rs' panicked at 'explicit panic', /Users/eddy/Documents/rust/src/compiletest/runtest.rs:1452



failures:
    [run-pass] run-pass/deref-rc.rs
    [run-pass] run-pass/issue-15080.rs
    [run-pass] run-pass/overloaded-deref-count.rs
    [run-pass] run-pass/packed-struct-generic-layout.rs
    [run-pass] run-pass/packed-struct-layout.rs
    [run-pass] run-pass/packed-tuple-struct-layout.rs
    [run-pass] run-pass/vec-matching-autoslice.rs
    [run-pass] run-pass/vec-matching.rs

test result: FAILED. 1909 passed; 8 failed; 38 ignored; 0 measured
```

**Comment by eddyb** [comment]
Turns out OSX just can't handle private linkage right. You had one job *sigh*.
@bors r=nikomatsakis cd81a38 p=1234

**Comment by eddyb** [comment]
Are you kidding me right now?
@bors retry

**Comment by huonw** [comment]
Isn't this designed to make `let x: &'static i32 = &1;` work? Shouldn't there be tests for that sort of behaviour?

**Comment by brson** [comment]
Epic fight with @bors!

**Comment by huonw** [comment]
(If tests are added, they can close https://github.com/rust-lang/rfcs/issues/827.)

**Comment by eddyb** [comment]
@huonw No, that part needs an RFC. @nikomatsakis wanted to write one for the longest time - in any case, there's a few different directions to go from this base.

**Pull request merged**
