### PR TITLE
Fix typo in diagram demonstrating stack vs. heap values

### LINKED ISSUE #25635: Not giving the right value to a variable in the book
At the end of bar(), it calls baz():

In the code baz is passed f  whose value is the address of d which is 9.

However, in the diagram, it is given a value of 4.
```
Address	Name	Value
230		20
(230) - 1		5
...	...	...
12	g	100
11	f	4
10	e	9
9	d	(230) - 1
8	c	5
7	b	4
6	a	0
5	z	4
4	y	10
3	x	0
2	j	0
1	i	230
0	h	3
```

### PR DESCRIPTION
**Pull request by ralexstokes**
Typo in explanation of difference between stack and heap values.  

`baz` is called at the end of a call to `bar` inside another call to `foo`.  `baz` takes a copy of the value `e` which should have a value of 9 if following the rest of the stack trace.

This PR fixes this typo and should close #25635.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you so much!

**Comment by steveklabnik** [comment]
Oh, future note: if you put "Fixes #12345" in your commit message, github will automatically close the issue when it's merged.

**Comment by ralexstokes** [comment]
cool, thanks for the tip!

**Pull request merged**
