### PR TITLE
Fix issues with Markdown summary options

### PR DESCRIPTION
**Pull request by camelid**
- Use `summary_opts()` for Markdown summaries
- Enable all main body Markdown options for summaries

### CODE REVIEW

**Comment by camelid** [comment]
(There are more details about the changes in the commit messages.)

**Comment by CraftSpider** [comment]
Does a tasklist actually look okay in a markdown summary? I guess it doesn't necessarily matter, not rendering it probably looks worse, but I'm curious what kind of affects this has.

**Comment by camelid** [comment]
> Does a tasklist actually look okay in a markdown summary? I guess it doesn't necessarily matter, not rendering it probably looks worse, but I'm curious what kind of affects this has.

It doesn't actually get rendered, because `markdown_summary_with_limit` stops as soon as it encounters things like task lists. I've tested it locally, though I don't have a screenshot available since it was a few days ago, but the difference is like this:

#### input

```md
- [ ] foo
- [ ] bar
```

#### output before

(note that this is shown literally as the characters `- [ ] foo`)

```
- [ ] foo
```

#### output after

(nothing)

**Comment by CraftSpider** [comment]
Alright, thanks for the clarification. Definitely sounds like better behavior now.
@bors r+

**Pull request merged**
