### PR TITLE
Compiletest: delete the compiled program once its test is done. 

### PR DESCRIPTION
**Pull request by kennytm**
Reduces CI disk usage which prevents #48118 from succeeding.

### CODE REVIEW

**Comment by kennytm** [comment]
r? @Mark-Simulacrum 

As you expected, the musl disk usage for run-pass alone drops from 24 GB to 6 GB after applying this.

**Comment by Mark-Simulacrum** [comment]
Can you check if this means we no longer skip tests that we've already run? Today if you run `./x.py test src/test/run-pass` twice then the second run all of the tests will be ignored -- does this PR preserve that?

**Comment by rkruppe** [comment]
One might want to run the binary manually if the test fails (e.g., under a debugger). Could there be an opt-out, or could this be restricted to only apply to successful tests?

**Pull request merged**
