### PR TITLE
rustdoc: filter '_ lifetimes from ty::PolyTraitRef

### LINKED ISSUE #98697: Rustdoc shows broken anonymous lifetimes on re-exported signatures
```toml
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
foo = { path = "foo" }
```

```rust
// src/lib.rs

pub use foo::repro;
```

```toml
# foo/Cargo.toml

[package]
name = "foo"
version = "0.0.0"
edition = "2021"
publish = false
```

```rust
// foo/src/lib.rs

pub fn repro<F>()
where
    F: Fn(&str),
{
    unimplemented!()
}
```

The correct behavior is for both crates' docs to render `repro` as:

However, recent versions of nightly rustdoc render `foo::repro` as the above, while rendering `repro::repro` incorrectly as:

I believe this is a bug because that is not valid syntax in Rust.

```console
error[E0637]: `'_` cannot be used here
 --> src/lib.rs:3:12
  |
3 |     F: for<'_> Fn(&str),
  |            ^^ `'_` is a reserved lifetime name
```

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #98697

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks! r=me once CI pass

**Comment by compiler-errors** [comment]
This is a regression from stable to beta, right? If so, should we beta nominate it?

**Comment by jsha** [comment]
I agree.

**Comment by GuillaumeGomez** [comment]
I agree as well.

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-07-07/near/288816729)

@rustbot label +beta-accepted

**Pull request merged**
