### PR TITLE
treat `for<'a> T: 'a` as `T: 'static`

### LINKED ISSUE #26217: Higher-kinded lifetime bounds could be smarter
The following code fails to compile despite `i32: 'static`:
```rust
fn foo<T>() where for<'a> T: 'a {}

fn main() {
    foo::<i32>();
}
```
The exact error is:
```
foo.rs:4:5: 4:15 error: the requirement `for<'a> i32 : 'a` is not satisfied [E0280]
foo.rs:4     foo::<i32>();
             ^~~~~~~~~~
```
Per @nikomatsakis's comment [here](https://github.com/apasel422/eclectic/issues/2#issuecomment-110797869), it seems that `T: 'static` could imply `for<'a> T: 'a`.

### PR DESCRIPTION
**Pull request by apasel422**
closes #26217

r? @nikomatsakis

### CODE REVIEW

**Comment by apasel422** [comment]
@nikomatsakis I think I implemented this as you suggested to me, but the error message for types that fail the `'static` obligation here should be changed, as it is not necessarily obvious how the `for<'a> T: 'a` predicate becomes `'static`. Additionally, in order to make sure the logic is sound, I'm curious how we ultimately might support the following:

```rust
fn foo<'a, T>() where for<'b: 'a> T: 'b {}
```

**Comment by nikomatsakis** [comment]
@apasel422 well, adding where clauses to `for` binders is a much larger topic =)

**Comment by apasel422** [comment]
What issues should I open as follow-ups to this PR?

**Pull request merged**
