### PR TITLE
save-analysis: track associated types

### PR DESCRIPTION
**Pull request by nrc**
r? @eddyb

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* ar.exe error https://github.com/rust-lang/rust/issues/40546

**Comment by alexcrichton** [comment]
@bors: retry

* timeout?

**Comment by nrc** [comment]
@bors: retry

@alexcrichton looking at the logs, it is not clear what is happening here. It looks like it is doing the whole build three times - starting from configure and building LLVM. The last one doesn't finish before the timeout. I can't see why it is restarting the build when it is nearly done.

**Pull request merged**
