### PR TITLE
rustc_mir: always run the inlining pass.

### PR DESCRIPTION
**Pull request by eddyb**
**DO NOT MERGE**: there are still issues around debuginfo and maybe even misoptimizations.
As suggested by @pcwalton, maybe it's time to test the overhead / wins from turning MIR inlining on.

### CODE REVIEW

**Comment by eddyb** [comment]
```
thread 'rustc' panicked at 'missing specialization: `<decoder::DecodeContext as SpecializedDecoder<rustc::ich::Fingerprint>>::specialized_decode` not overridden', libserialize/serialize.rs:788:9
```
Maybe the specialization bugs weren't fixed, huh.

**Comment by nikomatsakis** [comment]
@eddyb let me know when there is a need for me to review

**Comment by pietroalbini** [comment]
Ping from triage @eddyb! It has been a while since you updated this PR.

**Comment by pietroalbini** [comment]
@eddyb closing for inactivity, feel free to reopen the PR when you have some spare time to finish this!

**Pull request closed without merging**
