### PR TITLE
erase types in the move-path abstract domain

### PR DESCRIPTION
**Pull request by arielb1**
Leaving types unerased would lead to 2 types with a different "name"
getting different move-paths, which would cause major brokenness (see
e.g. #42903).

This does not fix any *known* issue, but is required if we want to use
abs_domain with non-erased regions (because the same can easily
have different names). cc @RalfJung.

r? @eddyb

### CODE REVIEW

**Review by eddyb — APPROVED** [review]

**Comment by RalfJung** [comment]
Thank you :)

**Pull request merged**
