### PR TITLE
tidy: make rustc dependency error less confusing

### PR DESCRIPTION
**Pull request by RalfJung**
The current wording leads to very confusing messages:
```
tidy error: Dependencies for main workspace not explicitly permitted:
* unicode-ident 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)
```
Miri is part of that workspace, and there never was a problem adding Miri dependencies. The actual error is that due to a crate bump this now showed up as a rustc dependency, and *those* are restricted.

### CODE REVIEW

**Comment by RalfJung** [comment]
(FWIW, the function names here are terrible. `check_dependencies` sounds like it could be the function that checks the licenses of all dependencies, but it isn't. The license checking function is called `check_exceptions`...)

**Comment by jyn514** [comment]
> Miri is part of that workspace, and there never was a problem adding Miri dependencies. The actual error is that due to a crate bump this now showed up as a rustc dependency, and those are restricted.

This doesn't match my reading of the code. It runs `cargo metadata` from the top level directory, which shows all dependencies in the workspace, no?

**Comment by RalfJung** [comment]
Yeah I had to read the code 3 times to figure out what happens.

It only checks the dependencies of `RESTRICTED_DEPENDENCY_CRATES`, which is only rustc.

**Comment by jyn514** [comment]
The new names make the code a lot easier to understand, thanks :)

@bors r+ rollup

**Pull request merged**
