### PR TITLE
Rustdoc: Use the extern item-path for documentation links

### LINKED ISSUE #30109: Links to types in an extern crate declared somewhere other than the crate root are broken
See for example `SslStream` on this page: http://sfackler.github.io/rust-postgres/doc/v0.10.1/postgres/io/trait.StreamWrapper.html

The link has an `/io/openssl/` in it that shouldn't be there.

### PR DESCRIPTION
**Pull request by mitaa**
Fixes #30109

### CODE REVIEW

**Comment by mitaa** [comment]
I used a run make test because docs for the extern crate need to be generated beforehand, otherwise the cross-crate link isn't being generated.

**Comment by alexcrichton** [comment]
Could this perhaps be a `src/test/rustdoc` test with some modifications to the compiletest driver? Perhaps something like `// run-rustdoc` which indicates that the documentation of an `aux-build` file should be generated as well?

**Comment by mitaa** [comment]
(updated)

**Comment by alexcrichton** [comment]
@bors: r+ af1ad419e154b5306c7d89b21218fe35607e9f3a

Thanks!

**Pull request merged**
