### PR TITLE
Use <[T; N]>::map in Sharded instead of SmallVec and unsafe code

### PR DESCRIPTION
**Pull request by bjorn3**
This results in a lot less assembly

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Probably doesn't matter too much for perf - I don't think we frequently initialize Sharded - but r=me, seems like a good improvement if perf is good.

**Comment by bjorn3** [comment]
A couple of regressions, mostly improvements.

**Comment by Mark-Simulacrum** [comment]
Looking at a cachegrind diff locally, the regression seems to be caused by noise rather than something genuine -- I'm seeing a bump in the number of instructions used for PartialEq ConstKind not equals, which seems pretty unrelated to this change, and some LLVM functions. Ultimately doesn't seem like this is something we can address and the change does bring a win on both how simple the code is and bootstrap compilation time.

@rustbot label +perf-regression-triaged

@bors r+

**Comment by pnkfelix** [comment]
Visiting for performance triage.

The report from when this PR was [first timed](https://perf.rust-lang.org/compare.html?start=6cdd42f9f8dd4e5e5ba0aa816bc4c99ab8b102f9&end=d7e5e4ab57e3fa2aca41f679c8baab3581926670) looks pretty different from the report from [when it landed](https://perf.rust-lang.org/compare.html?start=db1fb85cff63ad5fffe435e17128f99f9e1d970c&end=3bb9eecf07630be796c587a4bba70c49ae6a1bae).

But either way, I'm inclined to apply @Mark-Simulacrum 's [analysis](https://github.com/rust-lang/rust/pull/89069#issuecomment-922955188) above.

@rustbot label: +perf-regression-triaged

**Pull request merged**
