### PR TITLE
Transition to the new object lifetime defaults

### PR DESCRIPTION
**Pull request by nikomatsakis**
Transition to the new object lifetime defaults, replacing the old defaults completely.

r? @pnkfelix 

This is a [breaking-change] as specified by [RFC 1156](https://github.com/rust-lang/rfcs/blob/master/text/1156-adjust-default-object-bounds.md) (though all cases that would break should have been receiving warnings starting in Rust 1.2). Types like `&'a Box<Trait>` (or `&'a Rc<Trait>`, etc) will change from being interpreted as `&'a Box<Trait+'a>` to `&'a Box<Trait+'static>`. To restore the old behavior, write the `+'a` explicitly. For example, the function:

``` rust
trait Trait { }
fn foo(x: &Box<Trait>) { ... }
```

would be rewritten as:

``` rust
trait Trait { }
fn foo(x: &'a Box<Trait+'a>) { ... }
```

if one wanted to preserve the current typing.

### CODE REVIEW

**Comment by pnkfelix** [comment]
Just to be clear, the description should probably say "this is a [breaking change], but all such breaking cases are currently flagged with a warning, as specified in RFC 1156."  (Right?)

That is, I find it less scary to spell that out explicitly to the person writing up the release notes for the associated release.

**Comment by pnkfelix** [comment]
@nikomatsakis yay for removing tons of code.

r=me after you revise the description as advised above.

**Comment by nikomatsakis** [comment]
@pnkfelix 

> Just to be clear, the description should probably say "this is a [breaking change], but all such breaking cases are currently flagged with a warning, as specified in RFC 1156." (Right?)

Updated.

**Pull request merged**
