### PR TITLE
Add type definitions for rustdoc JSON backend

### PR DESCRIPTION
**Pull request by 197g**
As discussed as a first step of #76578 add serde-deriving type definitions describing the structure.

### CODE REVIEW

**Comment by HeroicKatora** [comment]
r? Manishearth

**Comment by jyn514** [comment]
@HeroicKatora how does this interact with #75114 ?

**Comment by HeroicKatora** [comment]
I overlooked that it already had its own type definitions, the tracking issue could use some updates then on the open PR? This was just porting some work some for a potential consumer of the output (https://github.com/oberien/heradoc/issues/154) so not tagic :)

**Pull request closed without merging**
