### PR TITLE
core: Inline most cell methods.

### PR DESCRIPTION
**Pull request by pcwalton**
This is a significant performance problem in Servo.

r? @brson

### CODE REVIEW

**Comment by cmr** [comment]
Is LLVM really not inlining these functions? The bodies are miniscule, and the'll get monomorphized in the other crate.

**Comment by pcwalton** [comment]
@cmr No, they do not all get monomorphized. Many of them just have lifetime parameters. This is done based on a profile.

**Comment by pcwalton** [comment]
@cmr In particular `BorrowRef::new` and `BorrowRefMut::new` are showing up in profiles.

**Comment by Manishearth** [comment]
This merged, 19b40f72bf3c0457e0fd99c47041ea965dba3dc9

**Pull request closed without merging**
