### PR TITLE
Update array_into_iter lint for 1.53 and edition changes.

### PR DESCRIPTION
**Pull request by m-ou-se**
This updates the array_into_iter lint for Rust 1.53 and the edition changes.

See https://github.com/rust-lang/rust/issues/84513

r? @estebank

### CODE REVIEW

**Comment by m-ou-se** [comment]
@Aaron1011 The `src/test/ui/lint/issue-78660-cap-lints-future-compat.rs` test breaks on this change. I'm not exactly sure what it tests, so I don't want to just `--bless` the output. (The `.stderr` file is gone, as there is no more output after this change.) Since you added that test, can you take a look?

**Comment by m-ou-se** [comment]
This now produces the message

> this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2021 edition!

which isn't entirely accurate. It will not become a hard error per se, it will change meaning.

Should this use something other than `@future_incompatible`?

**Comment by Aaron1011** [comment]
@m-ou-se The message about a hard error is emitted for all future compare lints - I can add a way to customize it on a per-lint basis.

Whether or not we still want the `@future_incompatible` is an interesting question. When I applied it to this lint, the plan was to change the array into_iter behavior on all editions, which would be a breaking change. As a result,  we wanted it to be included in the cargo future-incompat reports, so that users would be alerted about dependencies that would eventually break.

Now that the behavior is edition gated, upstream dependencies will continue to work (since they'll be on the 2015 or 2018 edition). I think there's no longer any need to notify users about such crates in the report - while it would be nice to minimize the number of crate's relying on the impl method resolution hack, I don't think this justifies showing a notification to authors of unrelated crates.

I think we can now remove the `@future_incompatible` for this lint.

**Comment by estebank** [comment]
I think it might be ok to land the lint with the slightly inaccurate note about the edition and fix it on a separate PR.

---

I didn't notice any 2021 edition tests to check that the lint doesn't trigger when it shouldn't. I don't _expect_ them to be broken, but I feel more at ease when we have tests for _any_ potential regression.

**Comment by m-ou-se** [comment]
Sounds like the `future` in `future_incompatible` doesn't necessarily refer to new editions, which are more like parallel timelines. ^^

Here, the comment suggests that future_incompatible lints with an edition set are 'not future incompatible': https://github.com/rust-lang/rust/blob/7350f655ef7e1b00f287eca6f8c0016a8985900c/compiler/rustc_middle/src/lint.rs#L275-L280

But here, it uses the 'standard message' in that case, which contains the "is being phased out" and "it will become a hard error" text:
https://github.com/rust-lang/rust/blob/7350f655ef7e1b00f287eca6f8c0016a8985900c/compiler/rustc_middle/src/lint.rs#L365-L366

That should be easy to change.

However, then the question remains: Do we consider these things 'future incompatibility lints' or not? Same question for the `non_fmt_panic` lint, which warns for `panic!("{}")` etc. That one is currently *not* marked as a future_incompatibility lint. Both of these lints have the property that they're also useful warnings even if you're not upgrading to the new edition, because they indicate some mistake or misunderstanding.

I'm not exactly sure what this `future_incompatibility` property of a lint implies, other than just adding that text to a message. Does it change behaviour anywhere?

> @Aaron1011 The `src/test/ui/lint/issue-78660-cap-lints-future-compat.rs` test breaks on this change. I'm not exactly sure what it tests, so I don't want to just `--bless` the output. (The `.stderr` file is gone, as there is no more output after this change.) Since you added that test, can you take a look?

@Aaron1011 can you tell me what I should do with that test? That's currently blocking this PR from passing the CI tests.

**Comment by m-ou-se** [comment]
I'm wondering if it's worth backporting this. Otherwise, 1.53 will ship with `IntoIterator` for arrays, but with a lint that claims that implementation doesn't exist.

**Comment by m-ou-se** [comment]
> > @Aaron1011 The `src/test/ui/lint/issue-78660-cap-lints-future-compat.rs` test breaks on this change. I'm not exactly sure what it tests, so I don't want to just `--bless` the output. (The `.stderr` file is gone, as there is no more output after this change.) Since you added that test, can you take a look?
> 
> @Aaron1011 can you tell me what I should do with that test? That's currently blocking this PR from passing the CI tests.

@Aaron1011 I have removed that test to unblock this.

> I didn't notice any 2021 edition tests to check that the lint doesn't trigger when it shouldn't.

That already exists here: [`src/test/ui/iterators/into-iter-on-arrays-2021.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/iterators/into-iter-on-arrays-2021.rs)

> I think we can now remove the `@future_incompatible` for this lint.

I have removed it for now. Once we have a way to change/disable the 'hard error' message, we should add it to make sure it becomes part of `rust_2021_compatibility`.

**Comment by Mark-Simulacrum** [comment]
This needs to get merged or at least approved in the next ~24 hours, ideally, if we're to backport it to beta, but I myself don't have enough time to investigate/review it. I suspect that means that 1.53 will not have the nice lint, unfortunately, but that doesn't seem *too* bad. We're always improving diagnostics anyway.

**Comment by pnkfelix** [comment]
unilaterally declining for beta-backport to 1.53.

Its not critical for this to get in there; the inconsistency [noted](https://github.com/rust-lang/rust/pull/85682#issuecomment-855897059) by @m-ou-se isn't that bad (i.e. its not fantastic for a diagnostic to claim an implementation doesn't exist when it in fact does, but that scenario is still way better than a diagnostic to claim an implementation does exist when it in fact does not.)

**Review by nikomatsakis — APPROVED** [review]

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/86544#issuecomment-865882268

@bors r-

**Comment by m-ou-se** [comment]
Apparently `// run-rustfix` uses `Filter::Everything` by default instead of `Filter::MachineApplicableOnly`. That doesn't work when the suggestions are mutually exclusive. Added `// rustfix-only-machine-applicable`.

**Comment by m-ou-se** [comment]
Alright, tests pass again after rebasing. Let's try again.

@bors r=nikomatsakis

**Comment by m-ou-se** [comment]
Rebased for https://github.com/rust-lang/rust/pull/86330. This is now a `future_incompatibility` lint again (set to `FutureIncompatibilityReason::EditionSemanticsChange(Edition::Edition2021)` by https://github.com/rust-lang/rust/pull/86330).

@bors r=nikomatsakis

**Pull request merged**
