### PR TITLE
rustdoc: Go back to loading all external crates unconditionally

### LINKED ISSUE #84738: Index out of bounds when running `cargo doc` in `rustc_metadata/src/creader.rs`
EDIT(camelid): This issue is now being used to track a different, but related, bug. The discussion starting [here](https://github.com/rust-lang/rust/issues/84738#issuecomment-950370740) is current.

### Steps

- Clone [`rust-gpu`](https://github.com/EmbarkStudios/rust-gpu/tree/2f451ee9939c021b54214d2aeb986ecb7a6d7382).
- `cargo doc -p spirv-std --no-deps`

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (42816d61e 2021-04-24)
binary: rustc
commit-hash: 42816d61ead7e46d462df997958ccfd514f8c21c
commit-date: 2021-04-24
host: x86_64-apple-darwin
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 8', compiler/rustc_metadata/src/creader.rs:137:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `spirv-std`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name spirv_std crates/spirv-std/src/lib.rs -o /Users/erin.power/src/rust-gpu2/target/doc --cfg 'feature="default"' --error-format=json --json=diagnostic-rendered-ansi -L dependency=/Users/erin.power/src/rust-gpu2/target/debug/deps --extern bitflags=/Users/erin.power/src/rust-gpu2/target/debug/deps/libbitflags-7c13a8e06c86cae3.rmeta --extern num_traits=/Users/erin.power/src/rust-gpu2/target/debug/deps/libnum_traits-226168b7b64579d8.rmeta --extern spirv_std_macros=/Users/erin.power/src/rust-gpu2/target/debug/deps/libspirv_std_macros-63f1f4de237cb2bc.dylib --extern spirv_types=/Users/erin.power/src/rust-gpu2/target/debug/deps/libspirv_types-7559b6c8fd9bbf59.rmeta --crate-version 0.4.0-alpha.7` (exit status: 1)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::crate_name
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_query_system::query::plumbing::force_query_with_job
   7: rustc_query_system::query::plumbing::get_query_impl
   8: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::crate_name
   9: rustdoc::clean::inline::record_extern_fqn
  10: rustdoc::clean::utils::register_res
  11: rustdoc::passes::collect_intra_doc_links::LinkCollector::resolve_link
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  13: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  14: rustdoc::fold::DocFolder::fold_inner_recur
  15: rustdoc::fold::DocFolder::fold_item_recur
  16: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  17: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  18: rustdoc::core::run_global_ctxt
  19: rustc_interface::passes::QueryContext::enter
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: rustc_interface::interface::create_compiler_and_run
  23: rustdoc::main_options
  24: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jyn514**
This *continues* to cause regressions. This code will be unnecessary
once access to the resolver happens fully before creating the tyctxt
(#83761), so load all crates unconditionally for now. To minimize churn, this leaves in the code for loading crates selectively.

"Fixes" https://github.com/rust-lang/rust/issues/84738. Previously: https://github.com/rust-lang/rust/pull/83738, https://github.com/rust-lang/rust/pull/85749, https://github.com/rust-lang/rust/pull/88215

r? @petrochenkov cc @camelid (this should fix the "index out of bounds" error you had while looking up `crate_name`).

### CODE REVIEW

**Comment by camelid** [comment]
> (this should fix the "index out of bounds" error you had while looking up `crate_name`).

Just a followup so we don't get confused later on: This PR doesn't fix that ICE; they seem to be different bugs.

**Comment by petrochenkov** [comment]
@jyn514 
The minimized reproduction in #84738 looks like https://github.com/rust-lang/rust/pull/88679#discussion_r703056971.
Could you check whether visiting associated items in `IntraLinkCrateLoader` fixes #84738?

**Comment by jyn514** [comment]
@petrochenkov given how many regressions this has caused, I don't particularly want to keep playing wack-a-mole with fixing the bugs. I'm fine with fixing the bugs in parallel, but I don't think we should be testing things "in-prod" as it were, we don't need to enable this until rustdoc's fundamental problems with crate loading are resolved (https://github.com/rust-lang/rust/issues/83761).

**Comment by petrochenkov** [comment]
>given how many regressions this has caused

Which regressions?
I only see #84738 right now, which is caused by the missing visiting of associated items in `IntraLinkCrateLoader` with 99% certainty.
I'd also add visiting for at least fields and enum variants in the same PR, because the doc link resolver scans them as well. I'm not sure which other nodes need to be visited, I've seen some relevant `enum` somewhere in rustdoc, but don't remember how it's called.

**Comment by jyn514** [comment]
> Which regressions?

https://github.com/rust-lang/rust/issues/84738 is the only one I know of, but lots of people have been hitting it, and it was hit the last time we tried to land this patch too.

> I'd also add visiting for at least fields and enum variants in the same PR, because the doc link resolver scans them as well. I'm not sure which other nodes need to be visited, I've seen some relevant enum somewhere in rustdoc, but don't remember how it's called.

Right, yes, this is what I mean, there's no guarantee that fixing one issue will fix the others, and it happens rarely enough that usually the bug doesn't get caught until the patch hits stable. And I'm not sure what *benefit* it brings, no one is using https://github.com/rust-lang/rust/issues/68427 in practice.

**Comment by jyn514** [comment]
I just spent about half an hour to come up with the following impls for the visitor:
```rust
    fn visit_foreign_item(&mut self, item: &ast::ForeignItem) {
        self.load_links_in_attrs(&item.attrs, item.span);
        visit::walk_foreign_item(self, item)
    }

    // NOTE: if doc-comments are ever allowed on function parameters, this will have to implement `visit_param` too.

    fn visit_assoc_item(&mut self, item: &ast::AssocItem, ctxt: visit::AssocCtxt) {
        self.load_links_in_attrs(&item.attrs, item.span);
        visit::walk_assoc_item(self, item, ctxt)
    }

    fn visit_field_def(&mut self, field: &ast::FieldDef) {
        self.load_links_in_attrs(&field.attrs, field.span);
        visit::walk_field_def(self, field)
    }

    fn visit_variant(&mut self, v: &ast::Variant) {
        self.load_links_in_attrs(&v.attrs, v.span);
        visit::walk_variant(self, v)
    }
}
```
finding https://github.com/rust-lang/rust/issues/90610 in the process, and I'm still not sure I got them all. If you really think this is a good idea, I'd suggest adding a `visit_attr_list` function to `Visitor` so I don't have to rewrite all of these and be worried I'm missing one. But again, I think this is really high risk for the little benefit we get from it.

**Comment by petrochenkov** [comment]
>I've seen some relevant `enum` somewhere in rustdoc

It's `ItemKind`, and `Item`s are constructed from AST by the `impl Clean<Item> for ...` function.
So the visitor methods above should cover all of the required AST nodes.
These methods are necessary for #83761 anyway, so let's land them now.
(Also could you add test cases for all these new nodes loading crates through doc links?)

The only remaining *potential* source of missing extern crates that I'm aware of is reexport inlining.
If you can build a test case with a link on an import attempting to access a crate not previously loaded by `IntraLinkCrateLoader`, then we can land the "load all external crates" hack as well, because I don't want you to implement all that reexport walking now (it should be implemented in #88679, but it may cause perf issues there).

**Comment by jyn514** [comment]
@petrochenkov the cases I added didn't actually fix the issue, it still panics. I'll add them to this PR anyway.

I'm not sure how to come up with an MCVE for the ICEs this fixes. I can put some more time into it but it will probably be a few days before I have time.

**Comment by petrochenkov** [comment]
I see, so it's probably reexport inlining after all.
We have 3.5 weeks until the next release, so there's some time to come up with an MCVE.

I'm also still interested in tests for fields, variants, and associated and foreign items.
A doc comment on such nodes needs to load a crate that is not loaded in any other way (so we either need at least 4 dependency crates and one test, or 4 separate tests and one dependency crate).

**Comment by jyn514** [comment]
Ok, I added a test for all 4 new methods (and ran the test on master to ensure it failed before this PR).

**Comment by petrochenkov** [comment]
>We have 3.5 weeks until the next release, so there's some time to come up with an MCVE.

@rustbot label +S-waiting-on-author -S-waiting-on-review

**Comment by jyn514** [comment]
@petrochenkov https://github.com/jyn514/objr/commit/cf1c87598efdfee5608964206c2b038636b0e116

It requires at least 4 crates, a re-export from a module, and a blanket impl.
```
$ (cd corevideor/ && cargo tree)
corevideor v0.1.0 (/home/joshua/test-rustdoc/rustc-84738/corevideor)
├── coregraphicsr v0.1.0 (/home/joshua/test-rustdoc/rustc-84738/coregraphicsr)
│   └── objr v0.2.0 (/home/joshua/test-rustdoc/rustc-84738/objr-upstream)
└── objr v0.1.0 (/home/joshua/test-rustdoc/rustc-84738/objr)
$ fd .rs | while read f; do echo $f; bat $f; done
coregraphicsr/src/lib.rs
   1 extern crate objr;
corevideor/src/lib.rs
   1 extern crate coregraphicsr;
objr/src/lib.rs
objr-upstream/src/lib.rs
   1 extern crate self as objr;
   2 
   3 mod m {
   4     pub trait Trait {
   5         /// [objr]
   6         fn f() {}
   7     }
   8     impl <T> Trait for T {
   9         fn f() {}
  10     }
  11 }
  12 
  13 pub use m::Trait;
```

**Comment by jyn514** [comment]
The reason it's not being caught by the early pass is because rustdoc is explicitly visit traits from other crates for some reason :/ https://github.com/rust-lang/rust/blob/43192ca3d72ed0ca42ba913137585219ba0a691f/src/librustdoc/visit.rs#L67

**Comment by jyn514** [comment]
The traits are being added here: https://github.com/rust-lang/rust/blob/43192ca3d72ed0ca42ba913137585219ba0a691f/src/librustdoc/clean/utils.rs#L442-L444

Removing that block ... doesn't actually cause any tests to fail???
@GuillaumeGomez do you know what's going on here? Why is rustdoc storing traits (and only traits) from other crates?

**Comment by jyn514** [comment]
Oh, there were multiple places `record_extern_trait` is called. The second one does cause a whole bunch of tests to fail; but it also fixes the ICE.

<details>

```
failures:
    [rustdoc] rustdoc/auto-impl-primitive.rs
    [rustdoc] rustdoc/blanket-reexport-item.rs
    [rustdoc] rustdoc/const-generics/add-impl.rs
    [rustdoc] rustdoc/const-generics/const-impl.rs
    [rustdoc] rustdoc/const-generics/lazy_normalization_consts/const-equate-pred.rs
    [rustdoc] rustdoc/deref-mut-methods.rs
    [rustdoc] rustdoc/deref-recursive-pathbuf.rs
    [rustdoc] rustdoc/deref-recursive.rs
    [rustdoc] rustdoc/deref-typedef.rs
    [rustdoc] rustdoc/doc-cfg-traits.rs
    [rustdoc] rustdoc/empty-impls.rs
    [rustdoc] rustdoc/escape-deref-methods.rs
    [rustdoc] rustdoc/extern-default-method.rs
    [rustdoc] rustdoc/generic-impl.rs
    [rustdoc] rustdoc/inline_cross/impl-inline-without-trait.rs
    [rustdoc] rustdoc/inline_cross/issue-31948-2.rs
    [rustdoc] rustdoc/inline_cross/issue-32881.rs
    [rustdoc] rustdoc/inline_cross/trait-vis.rs
    [rustdoc] rustdoc/intra-doc/cross-crate/traits.rs
    [rustdoc] rustdoc/issue-15169.rs
    [rustdoc] rustdoc/issue-17476.rs
    [rustdoc] rustdoc/issue-19190-2.rs
    [rustdoc] rustdoc/issue-19190-3.rs
    [rustdoc] rustdoc/issue-19190.rs
    [rustdoc] rustdoc/issue-35169-2.rs
    [rustdoc] rustdoc/issue-35169.rs
    [rustdoc] rustdoc/issue-50159.rs
    [rustdoc] rustdoc/issue-51236.rs
    [rustdoc] rustdoc/issue-54705.rs
    [rustdoc] rustdoc/issue-55321.rs
    [rustdoc] rustdoc/issue-56822.rs
    [rustdoc] rustdoc/issue-60726.rs
    [rustdoc] rustdoc/issue-72340.rs
    [rustdoc] rustdoc/issue-80233-normalize-auto-trait.rs
    [rustdoc] rustdoc/issue-82465-asref-for-and-of-local.rs
    [rustdoc] rustdoc/issue-86620.rs
    [rustdoc] rustdoc/negative-impl-sidebar.rs
    [rustdoc] rustdoc/negative-impl.rs
    [rustdoc] rustdoc/primitive-generic-impl.rs
    [rustdoc] rustdoc/recursive-deref-sidebar.rs
    [rustdoc] rustdoc/recursive-deref.rs
    [rustdoc] rustdoc/spotlight-from-dependency.rs
    [rustdoc] rustdoc/src-links-auto-impls.rs
    [rustdoc] rustdoc/synthetic_auto/basic.rs
    [rustdoc] rustdoc/synthetic_auto/complex.rs
    [rustdoc] rustdoc/synthetic_auto/crate-local.rs
    [rustdoc] rustdoc/synthetic_auto/lifetimes.rs
    [rustdoc] rustdoc/synthetic_auto/manual.rs
    [rustdoc] rustdoc/synthetic_auto/negative.rs
    [rustdoc] rustdoc/synthetic_auto/nested.rs
    [rustdoc] rustdoc/synthetic_auto/no-redundancy.rs
    [rustdoc] rustdoc/synthetic_auto/overflow.rs
    [rustdoc] rustdoc/synthetic_auto/project.rs
    [rustdoc] rustdoc/synthetic_auto/self-referential.rs
    [rustdoc] rustdoc/synthetic_auto/static-region.rs
    [rustdoc] rustdoc/traits-in-bodies.rs

test result: FAILED. 423 passed; 56 failed; 3 ignored; 0 measured; 0 filtered out; finished in 37.61s
```

</details>

Still confused why this is necessary in the first place though :/

**Comment by GuillaumeGomez** [comment]
My wild guess is that we need external traits for blanket impls. But that seems weird because that should be handled when we look for impl blocks. I'm really not sure why this is needed at this point... Maybe something we did before that we don't anymore?

**Comment by jyn514** [comment]
Hmm, this looks incorrect:
```
DEBUG rustdoc::passes::collect_intra_doc_links resolving empty in DefId(20:0 ~ objr[b427])
INFO rustc_metadata::creader resolving crate `empty`
INFO rustc_metadata::creader falling back to a load
INFO rustc_metadata::locator rmeta reading metadata from: /home/joshua/test-rustdoc/rustc-84738/corevideor/target/debug/deps/libempty-c427b7c2497d53d1.rmeta
```
@petrochenkov shouldn't the crate not be loaded, because `empty` wasn't originally available in `objr`? This is cargo tree for context:
```
corevideor v0.1.0 (/home/joshua/test-rustdoc/rustc-84738/corevideor)
├── empty v0.1.0 (/home/joshua/test-rustdoc/rustc-84738/empty)
└── objr v0.2.0 (/home/joshua/test-rustdoc/rustc-84738/objr)
```

**Comment by camelid** [comment]
@jyn514 FWIW, `RUSTDOC_LOG=rustc_metadata::creader=trace` may be enlightening since it will show what crates are already loaded, and why the already loaded crates can't be used.

**Comment by petrochenkov** [comment]
Update: The logic in `register_res` was added in https://github.com/rust-lang/rust/pull/14346 back in 2014, removing it doesn't break any tests.

But the main question is: are `DocContext::external_traits` (and then `Cache::traits`) only used for documenting corresponding impls, or they are also used for documenting the traits themselves and maybe something else? I'll try to check, but only tomorrow.

**Comment by camelid** [comment]
> Update: The logic in `register_res` was added in #14346 back in 2014, removing it doesn't break any tests.

FWIW, rustdoc's test coverage is not so great right now, so it's very possible it still breaks something. But if we _can_ safely remove that logic, it'd be great :)

**Comment by petrochenkov** [comment]
>But the main question is: are `DocContext::external_traits` (and then `Cache::traits`) only used for documenting corresponding impls, or they are also used for documenting the traits themselves and maybe something else?

From what I can see, these tables are only used for traits from impls, so the tables should be removable in favor of inlining the `TraitWithExtraInfo` stuff directly into the `clean::Impl`.

**Comment by apiraino** [comment]
backport suspended, waiting on #90489 ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-04.20.2354818/near/260278752))

**Comment by jyn514** [comment]
@apiraino I don't understand your comment - #90489 is this PR. My understanding from the meeting is they were just waiting for this PR to stop changing before approving a backport (which should be the case now; this isn't the sort of change I would expect to pass PR CI but fail bors).

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-11.20.2354818/near/261148043)

@rustbot label +beta-accepted

**Comment by apiraino** [comment]
stable backport declined as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-18.20.2354818/near/261945258) (and previous comments)

@rustbot label -stable-nominated

**Pull request merged**
