### PR TITLE
Update `rental` hack to work with remapped paths.

### PR DESCRIPTION
**Pull request by TimNN**
This PR simply switches to an already-existing helper instead of hard-coding a specific enum variant. The new revision of the test fails without the other changes in this PR.

Context: I'm exploring running UI tests with remapped paths by default in #105924 and the rental test was one of the ones that failed.

This may also be useful in the context of https://github.com/rust-lang/rfcs/pull/3127 ("New rustc and Cargo options to allow path sanitisation by default").

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r- failed in a rollup
https://github.com/rust-lang/rust/pull/106818

**Comment by TimNN** [comment]
Ugh, Windows paths. Sorry for the inconvenience.

Looks like the remapped paths aren't recognized by compiletest and thus aren't automatically normalized. 

I added some manual normalization which should hopefully work but I don't have a Windows environment available to test.

I've temporarily enabled two Windows buildbots, please don't approve right now.

**Comment by TimNN** [comment]
The job that failed in the rollup passed with the path normalization fix: https://github.com/rust-lang/rust/actions/runs/3914244020/jobs/6691084328

Removed the temporary CI changes and squashed the fix, so this should be ready for review again, @matthiaskrgr / @oli-obk.

**Pull request merged**
