### PR TITLE
aatch's cfg revisions, namely to match expressions

### LINKED ISSUE #22073: Moves in guard expressions aren't handled properly
This code causes a segfault (without optimisations on):

```rust
use std::fmt;
fn main() {
    let a = std::rc::Rc::new(1);
    
    let x = (1, 2);
    
    match x {
        (_, y) |
        (y, _) if take(y, a) => (),
        _ => ()
    }

}

fn take<T:fmt::Debug>(x: usize, t: T) -> bool {
    println!("{:?}", t);
    x == 1
}
```

as does this similar code:

```rust
use std::fmt;
fn main() {
    let a = std::rc::Rc::new(1);
    
    let x = (1, 2);
    
    match x {
        (_, y) if take(y, a) => (),
        (y, _) if take(y, a) => (),
        _ => ()
    }

}

fn take<T:fmt::Debug>(x: usize, t: T) -> bool {
    println!("{:?}", t);
    x == 1
}
```

This is because the current control flow graph essentially visits each arm in parallel. With multiple patterns, each pattern within the arm is visited, then the guard is visited after all the patterns have been visited, even though this doesn't reflect the real semantics (we visit the pattern, then the guard, then the next pattern, then the guard again).

### PR DESCRIPTION
**Pull request by pnkfelix**
aatch's cfg revisions, namely to match expressions

Revise handling of match expressions so that arms branch to next arm.

Update the graphviz tests accordingly.

Fixes #22073. (Includes regression test for the issue.)

### CODE REVIEW

**Comment by Manishearth** [comment]
(needs rebase)

**Comment by goffrie** [comment]
This is technically a [breaking-change], no?

**Pull request merged**
