### PR TITLE
Add method `String::insert_str`

### PR DESCRIPTION
**Pull request by murarth**

### CODE REVIEW

**Comment by brson** [comment]
The functionality makes sense to me. Is there really no easy way to do this today? cc @rust-lang/libs

**Comment by brson** [comment]
@murarth Can you please change the stability attribute to 'unstable'? New features mostly don't get stabilized immediately.

**Comment by murarth** [comment]
This is a pretty common method whose absence I thought was a bit strange. The signature of `insert_str` mirrors `insert` and the name goes along with the `push`/`push_str` methods.

This seems to me like a sufficiently small addition not to warrant an RFC, so I thought I'd go ahead and submit it.

The `#[stable]` attribute on the new method was just to get it to pass `make check` on my machine. I will gladly change it if that's deemed appropriate.

**Comment by murarth** [comment]
@brson: Sure, I just didn't know what to put for `issue` or whether the compiler would accept it without that.

**Comment by brson** [comment]
@murarth "0" is fine for now. If this PR is accepted then before it's merged you'll need to file a 'tracking' issue on the issue tracker to fill in the real number.

**Comment by murarth** [comment]
@brson: Okay. It's unstable now.

**Comment by BurntSushi** [comment]
This seems fine to me. I agree that it's small enough that we probably wouldn't need an RFC for it.

**Comment by sfackler** [comment]
LGTM

**Comment by cristicbz** [comment]
Probably 'relnotes' worthy.

**Comment by ollie27** [comment]
This is covered by `String::splice` rust-lang/rfcs#1432.

**Comment by alexcrichton** [comment]
Ah yeah I was also under the impression that this was going to be functionality implemented through `splice` that @ollie27 linked to. Perhaps the [PR to implement](https://github.com/rust-lang/rust/pull/32355) could be revived?

**Comment by murarth** [comment]
I wasn't aware of that RFC. Even so, `splice` looks to be a slightly different kind of operation. If I understand correctly, then inserting a string without replacing would look something like `a.splice(idx..idx, b)`, which looks a bit odd.

**Comment by alexcrichton** [comment]
Yeah it's true that does look a bit odd! We might still have API room to add a function like this, and to me it seems to fit all existing conventions so I'd also be fine layering this on top (although it'd probably  use `splice` as an implementation detail eventually)

**Comment by aturon** [comment]
I'm likewise happy having this as a convenience on top of `splice`.

**Comment by alexcrichton** [comment]
Discussed during libs triage today the decision was to merge, thanks for the PR @murarth!

@bors: r+

**Comment by alexcrichton** [comment]
@bors: retry

* #34595

**Comment by alexcrichton** [comment]
@bors: retry

* #34595

**Comment by alexcrichton** [comment]
@bors: retry

sorry for the number of retries...

**Comment by murarth** [comment]
Just curious, will the libs team create a tracking issue for this at some time or am I supposed to file one myself?

**Comment by alexcrichton** [comment]
Oh oops! Thanks for the reminder @murarth! This actually should have held off on landing until a tracking issue was made, but oh well.

If you want to open a tracking issue and send a PR updating the reference here I'll r+ and tag appropriately.

**Pull request merged**
