### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
r? @Manishearth 

This includes a bit bigger `Cargo.lock` update.

### CODE REVIEW

**Comment by flip1995** [comment]
Not sure if that is the correct fix or if it works. I don't have access to a windows machine to test it, so @bors try

**Comment by matthiaskrgr** [comment]
Hmm, I don't feel confident enough to `r+` that last commit tbh, anyone else who has a better understanding of this stuff? :sweat_smile:

**Pull request merged**
