### PR TITLE
Use `itertools::Either` instead of own impl

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Yeah.

### CODE REVIEW

**Review by Noratrieb — APPROVED** [review]

**Comment by Nilstrieb** [comment]
r? Nilstrieb
itertools is probably somewhere in the dep tree already, so that sounds great

**Comment by WaffleLapkin** [comment]
`itertools` is indeed in the dep tree (in multiple crate's deps, actually!), checked before doing this :)

**Comment by cuviper** [comment]
FWIW, `itertools::Either` is re-export of `either::Either`, so you could shorten that dependency chain slightly.

**Pull request merged**
