### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #73032 (stabilize leading_trailing_ones)
 - #73752 (Remap Windows ERROR_INVALID_PARAMETER to ErrorKind::InvalidInput from Other)
 - #73841 (Remove defunct `-Z print-region-graph`)
 - #73846 (Fix comma in debug_assert! docs)
 - #73847 (Edit cursor.prev() method docs in lexer)
 - #73848 (Fix markdown rendering in librustc_lexer docs)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
@Manishearth I was encouraged by your efforts to move us away from small rollups with only trivial PRs. However, this rollup represents a return to the status quo. Is there a better way to enforce the rules for rollups?

**Comment by Dylan-DPC** [comment]
@ecstatic-morse i'm not sure or aware or such a discussion. We generally prefer smaller rollups as it's easier to bisect later if there's a problem and the queue is small enough

**Comment by ecstatic-morse** [comment]
There's discussion in https://discord.com/channels/442252698964721669/629052535449190400/722335918408597515. All these PRs are either `rollup=always` or could have easily been marked `rollup=always`. All of them are tiny fixes except for the stabilization PR, which only needs to land before the beta branch. Point taken about the current size of the queue, but I don't think it's a good habit to be putting 20 line rollups at the front of the line.

**Comment by Dylan-DPC** [comment]
The queue was small when i rolled up

**Comment by Manishearth** [comment]
@Dylan-DPC In that case it is better to let harder-to-rollup PRs (https://github.com/rust-lang/rust/pull/73456 , https://github.com/rust-lang/rust/pull/73658, https://github.com/rust-lang/rust/pull/73706) filter through, perhaps by prioritizing them. There is almost zero value to making a rollup PR that is full of "`rollup=always` or could have easily been marked `rollup=always`". Those should always piggyback with larger PRs. A good rule of thumb I have is to find 4-8 nontrivial PRs and then sprinkle in some rollup=always ones.

This has been pretty much standard operating procedure for rollups for ages, I'm not really happy to see a shift towards smaller, less substantial rollups. The goal is not to simply get the queue size down, the goal is to get things landed.

**Pull request closed without merging**
