### PR TITLE
Make macro expansion backtraces shorter

### PR DESCRIPTION
**Pull request by jonas-schievink**
The second commit in this PR will stop printing the macro definition site in backtraces, which cuts their length in half and increases readability (the definition site was only correct for local macros).

The third commit will not print an invocation if the last one printed occurred at the same place (span). This will make backtraces caused by a self-recursive macro much shorter.

(A possible alternative would be to capture the backtrace first, then limit it to a few frames at the start and end of the chain and print `...` inbetween. This would also work with multiple macros calling each other, which is not addressed by this PR - although the backtrace will still be halved)

Example:

``` rust
macro_rules! m {
 ( 0 $($t:tt)* ) => ( m!($($t)*); );
 () => ( fn main() {0} );
}

m!(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0);
```

On a semi-recent nightly, this yields:

```
test.rs:3:21: 3:22 error: mismatched types:
 expected `()`,
    found `_`
(expected (),
    found integral variable) [E0308]
test.rs:3  () => ( fn main() {0} );
                              ^
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:2:23: 2:34 note: expansion site
test.rs:1:1: 4:2 note: in expansion of m!
test.rs:6:1: 6:35 note: expansion site
test.rs:3:21: 3:22 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

After this patch:

```
test.rs:3:21: 3:22 error: mismatched types:
 expected `()`,
    found `_`
(expected (),
    found integral variable) [E0308]
test.rs:3  () => ( fn main() {0} );
                              ^
test.rs:2:23: 2:34 note: in this expansion of m!
test.rs:6:1: 6:35 note: in this expansion of m!
test.rs:3:21: 3:22 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Another option that doesn't lose the macro definition site completely would be:

```
test.rs:6:1: 6:35 note: in this expansion of m! (defined in test.rs)
test.rs:6:1: 6:35 note: in this expansion of println! (defined in <std macros>)
test.rs:6:1: 6:35 note: in this expansion of for loop expansion
```

`Codemap::span_to_filename()` should work for this

**Comment by nrc** [comment]
@jonas-schievink the last option you suggest in the comment sounds like a good compromise to me. I am often frustrated by these macro expansion back traces, but OTOH I have occasionally found the definition site of the macro useful.

cc @rust-lang/compiler

**Comment by jonas-schievink** [comment]
Done!

Example:
```
<std macros>:1:33: 1:58 error: invalid reference to argument `0` (no arguments given)
<std macros>:1 ( $ fmt : expr ) => ( print ! ( concat ! ( $ fmt , "\n" ) ) ) ; (
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:1:33: 1:58 note: in this expansion of concat!
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:1:23: 1:60 note: in this expansion of print! (defined in <std macros>)
test.rs:3:25: 3:39 note: in this expansion of println! (defined in <std macros>)
test.rs:2:26: 2:37 note: in this expansion of m! (defined in test.rs)
test.rs:6:1: 6:35 note: in this expansion of m! (defined in test.rs)
error: aborting due to previous error
```

**Comment by eddyb** [comment]
:+1: This looks nice.

**Comment by nikomatsakis** [comment]
Certainly progress.

**Comment by Aatch** [comment]
Looks good to me. I wonder if having the line/column in the "defined in file.rs" would be good. So `note: in this expansion of m! (defined in test.rs:6:1)`.

**Comment by jonas-schievink** [comment]
@Aatch Since the spans are only correct for the local crate, in which I usually know where macros are defined (and grepping is trivial, especially when the file name is given), this would require checking if the macro is defined in the current crate, which - at a first glance - doesn't seem easy. Or just print `<std macros>:1:1` like it's done now (ugh!).

**Comment by Aatch** [comment]
@jonas-schievink fair enough, just a thought.

**Pull request merged**
