### PR TITLE
rustbuild: Remove invalid doctest from bootstrap.py

### PR DESCRIPTION
**Pull request by kennytm**

### CODE REVIEW

**Comment by kennytm** [comment]
@Mark-Simulacrum I just find it annoying that the failing test appear before `make tidy` 😄 

The strange thing is that even if the test failed, the return code is still 0 (success), so while it should stop the build, it doesn't. Also, I expect the content should be collapsed between `check-bootstrap` in Travis, but it is still appearing 😕. I may push a new commit to fix that.

**Comment by kennytm** [comment]
@Mark-Simulacrum OK now the `check-bootstrap` should properly detect if all tests are successful, and stop the CI on failure. Also content is now properly collapsed in Travis.

**Comment by Mark-Simulacrum** [comment]
Thanks!

@bors r+

**Pull request merged**
