### PR TITLE
Initialize rust-analyzer submodule on bootstrap

### LINKED ISSUE #96456: `./x.py` fails to bootstrap if `build.vendor` is set in `config.toml`
# Steps to reproduce:
## 1. Clone the repository
```
git clone https://github.com/rust-lang/rust.git
cd rust
cp config.toml.example config.toml
```
## 3. Start the bootstrap:
```
./x.py help
```

I expected to see this happen: `x.py` builds the bootstrap and runs the subcommand

Instead, this happened:
```
error: failed to read `<hidden>/rust/./src/tools/rust-analyzer/Cargo.toml`

Caused by:
    No such file or directory (os error 2)
failed to run: <hidden>/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo vendor --sync=./src/tools/rust-analyzer/Cargo.toml --sync=./compiler/rustc_codegen_cranelift/Cargo.toml
```

# Cause
`rust-analyzer` is not checked out in `src/bootstrap/bootstrap.py`:
https://github.com/rust-lang/rust/blob/082e4ca49770ebc9cb0ee616f3726a67471be8cb/src/bootstrap/bootstrap.py#L1142-L1149

### PR DESCRIPTION
**Pull request by yungkneez**
Fixes #96456

### CODE REVIEW

**Comment by bjorn3** [comment]
This is only needed when vendoring.

**Comment by yungkneez** [comment]
> This is only needed when vendoring.

Correct. I can modify the bootstrap script to only check it out if vendoring is enabled. Is that preferable?

**Comment by bjorn3** [comment]
I think so. That would cause less waiting on the download in case rust-analyzer doesn't need to be built.

**Comment by yungkneez** [comment]
Okay, it will now only checkout `rust-analyzer` if needed 😄

**Comment by Mark-Simulacrum** [comment]
r=me with commits squashed

**Pull request merged**
