### PR TITLE
Fix macro expansion backtrace diagnostics

### LINKED ISSUE #33704: No line number in error message with try! macro
Playpen link: https://is.gd/eYoVIw

Using Stable or Beta, the error message looks like this:

```
<std macros>:5:8: 6:42 error: mismatched types:
[.. eliding text ..]
<anon>:6:17: 6:24 note: in this expansion of try! (defined in <std macros>)
```

The key part is that it tells me that line 6 is where the try expansion happens.

But when running with Nightly, this is the error message (in full):
```
error: mismatched types [--explain E0308]
 --> <std macros>:5:8
5 |> return $ crate :: result :: Result :: Err (
  |>        ^ expected struct `Foo`, found enum `std::result::Result`
<std macros>:5:8: 6:45: note: in this expansion of try! (defined in <std macros>)
note: expected type `Foo`
note:    found type `std::result::Result<_, _>`

error: aborting due to previous error
playpen: application terminated with error code 101
```

The expansion site (line 6) is missing from the error diagnostics.  While the playpen uses the new-style diagnostics, this problem (the missing line number) applies to the old-style diagnostics too.

I'm not sure if this is only for `try!`, or if it is for all macros (I didn't test that)
I'm not sure exactly what version of rustc the playpen is at, but this issue is reproduced with `rustc 1.10.0-nightly (cd6a40017 2016-05-16)`

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #33704.
r? @nikomatsakis

### CODE REVIEW

**Comment by jseyfried** [comment]
For example, consider:
```rust
macro_rules! m {
    () => { { error } }
}
fn main() { m!(); }
```
Currently, the diagnostics are:
```
bt.rs:2     () => { { error } }
                      ^~~~~
bt.rs:2:15: 2:20 note: in this expansion of m! (defined in bt.rs)
bt.rs:2:15: 2:20 help: run `rustc --explain E0425` to see a detailed explanation
```

After this PR, the diagnostics will be the same as on beta:
```
bt.rs:2:15: 2:20 error: unresolved name `error` [E0425]
bt.rs:2     () => { { error } }
                      ^~~~~
bt.rs:4:13: 4:18 note: in this expansion of m! (defined in bt.rs)
bt.rs:2:15: 2:20 help: run `rustc --explain E0425` to see a detailed explanation
```

**Comment by nikomatsakis** [comment]
@jseyfried can we add a test for this?

**Comment by jseyfried** [comment]
@nikomatsakis I don't know -- I'm not very familiar with the recent changes to the testing framework.

**Comment by nikomatsakis** [comment]
we could make a ui test, but maybe not worth it -- @jonathandturner and I did plan to revisit how macro backtraces are presented, maybe we'll do it then

**Pull request merged**
