### PR TITLE
Stabilize movbe target feature

### PR DESCRIPTION
**Pull request by calebzulawski**
Almost all "old" x86 target features are stable.  As far as I can tell, these are the last two unstable features in the `x86-64-v2` or `x86-64-v3` microarchitecture levels, so I'm not sure if it was an oversight or if they're still unstable for a reason (see #106323 for `f16c`).

Note that this only stabilizes the target features, and not the intrinsics.

cc @Amanieu 

r? @rust-lang/lang

### CODE REVIEW

**Review by Amanieu — APPROVED** [review]

**Comment by pnkfelix** [comment]
r+

**Comment by calebzulawski** [comment]
I guess this only stabilizes movbe now 🤷

**Comment by ehuss** [comment]
Can you also post a PR to the reference similar to https://github.com/rust-lang/reference/pull/1331?

**Comment by calebzulawski** [comment]
Done!

**Comment by calebzulawski** [comment]
Thanks!

**Pull request merged**
