### PR TITLE
[WIP] Require specific feature names in `#[allow_internal_unstable]`.

### PR DESCRIPTION
**Pull request by eddyb**
I opened this with just a hacky commit to test the perf impact of one implementation strategy.

### CODE REVIEW

**Comment by eddyb** [comment]
@rust-timer build 389686ab903aeb2e4e88b4bfffe1cbbe8f917350

**Comment by eddyb** [comment]
We either don't have expansion stress tests... or I'm good to go.
cc @nikomatsakis @petrochenkov

**Comment by pnkfelix** [comment]
@eddyb what is the next step here? Can you link this back to the relevant bug that sparked this investigation?

**Comment by petrochenkov** [comment]
>Can you link this back to the relevant bug that sparked this investigation?

+1, I'm mildly skeptical about this, why isn't a boolean flag enough?

**Comment by TimNN** [comment]
Ping from triage @eddyb: It looks like some clarifications have been requested for this PR.

**Comment by TimNN** [comment]
Ping from triage @eddyb: What are your plans for this PR?

**Comment by TimNN** [comment]
Ping from triage, @eddyb! This PR hasn't seen any updates in a while, so I'm closing it for now, per [our guidelines](https://forge.rust-lang.org/triage-procedure.html). Thanks for your contributions and please feel free to re-open in the future.

**Comment by eddyb** [comment]
The investigation was actually flawed, we'd need to also support library features, and those aren't a finite set, so they'd have to use `Vec`, `BTreeSet` or something else.

The problem I was considering solving, if at all possible efficiently, is that currently `#[allow_internal_unstable]` allows *all features*, which came up in #52011:

`const fn` feature-gating has to ignore `allow_internal_unstable`, otherwise `panic!()` will be usable in constant contexts on stable (which is supposed to be gated).
`panic!()` needs `allow_internal_unstable` *but not* for using the panic entry-point as a `const fn`.

In general, we might be accidentally allowing too much, and I wanted to limit that.

**Pull request closed without merging**
