### PR TITLE
std: expose `const_io_error!` as `const_error!`

### PR DESCRIPTION
**Pull request by joboet**
ACP: https://github.com/rust-lang/libs-team/issues/205
Tracking issue: https://github.com/rust-lang/rust/issues/133448

Probably best reviewed commit-by-commit, the first one does the API change, the second does the mass-rename.

### CODE REVIEW

**Review by tgross35 — APPROVED** [review]
Looks consistent with the ACP, thanks for the clean commits!

**Comment by compiler-errors** [comment]
https://github.com/rust-lang/rust/pull/133490#issuecomment-2500897745

@bors r-

**Comment by joboet** [comment]
I searched for `const_io_error!` and thus missed two imports. It's fixed now.
@bors r=@tgross35

**Pull request merged**
