### PR TITLE
:arrow_up: rust-analyzer

### PR DESCRIPTION
**Pull request by arcnmx**
Updates rust-analyzer to https://github.com/rust-lang/rust-analyzer/commit/368e0bb32f1178cf162c2ce5f7e10b7ae211eb26

This is a continuation/replacement of #105834, close that if this is chosen instead.

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Oh, sorry for the confusion: I meant the latest master commit, not the latest tagged/nightly RA release.

**Comment by arcnmx** [comment]
> Oh, sorry for the confusion: I meant the latest master commit, not the latest tagged/nightly RA release.

I figured you might, just wasn't completely sure. Done!

**Comment by fasterthanlime** [comment]
So, this is now a regular ra->rust sync, and those should happen regularly, so as far as I'm concerned this is okay to merge cc @lnicola 

I can kick the corresponding rust->ra sync once I'm back home (that direction is more annoying since it requires the subtree cache iirc, which I happen to have)

**Comment by arcnmx** [comment]
Is there a particular time/day I should redo this pull? It's probably outdated now...

**Comment by lnicola** [comment]
@arcnmx between now and next Monday (inclusive) might be a good time. There were quite a few changes merged in the past couple of days. Sorry for the delay here.

**Comment by arcnmx** [comment]
@lnicola updated, poke me if needed again later

**Review by lnicola — APPROVED** [review]

**Comment by lnicola** [comment]
Well, what's the worst that could happen?

@bors r+ p=1 (subtree syncs are delicate things)

@Veykril I suppose we need to freeze r-a for now?

**Comment by Veykril** [comment]
Freeze until the r-a side has been synced if I understand the subtree stuff correctly right?

**Pull request merged**
