### PR TITLE
Add `NonNull::<[T]>::is_empty`.

### PR DESCRIPTION
**Pull request by zachs18**
As per https://github.com/rust-lang/rust/issues/71146#issuecomment-2008373983

I figured this should be fine to be insta-stable (with an FCP), but I can edit if that is not desired.

r? @Amanieu

### CODE REVIEW

**Comment by Amanieu** [comment]
Rather than make this insta-stable, can you add it to the tracking issue for #71146 so it is included in the FCP?

**Comment by zachs18** [comment]
Sure, I can change the `stable(...)` attributes to `unstable(feature = "...", issue = "71146")` and add a comment linking this PR on the issue. I don't have permissions to edit the FCP or the "Public API" section of that issue though.

**Pull request merged**
