### PR TITLE
Added tests in int module library as a part of #76268

### PR DESCRIPTION
**Pull request by ayushmishra2005**
Added Arith Tests library as a part of #76268

r? @matklad

### CODE REVIEW

**Comment by ayushmishra2005** [comment]
@matklad  @jyn514 please review this pull request

**Comment by matklad** [comment]
I think this invokes compiler built-in operations for primitives, rather than going through libcore implementation (rather, `ops::Add` and friends in libcore are defined in terms of operations on promitives). 

So, these tests actually exercise the compiler itself, and not the stdlib, and better be left in place. 

@jyn514 I've noticed that a fair share of #76268 PRs now hit this "not actually stdlib" test. This probably means majority of the library tests are now in their proper place and that we can close that issue?

**Comment by jyn514** [comment]
@matklad there are probably still some left, but I'm ok with closing the issue and moving the info to the dev-guide, maybe. I think https://github.com/rust-lang/rust/pull/79038 should be either merged or closed before closing https://github.com/rust-lang/rust/issues/76268 though.

**Comment by jyn514** [comment]
Closing this since these are testing the compiler and not the standard library.

**Comment by jyn514** [comment]
As a general rule, if the test would work with `#![no_core]`, it's always a test of the compiler and not the standard library.

**Pull request closed without merging**
