### PR TITLE
rustdoc: Improve accessibility of rustdoc pages

### LINKED ISSUE #33131: docs: fix the order of items in method headers for screen reader users
I think this is the right repository.  If it's not, I'd appreciate being directed to the right place.

Rustdoc has begun showing the version at which a function was introduced on some methods.  I'm not sure if this was introduced in 1.8.0 or if more methods were marked up, so I'm not sure how old this behavior actually is.

Unfortunately, these headers are horrible for screen reader users (i.e. me) because of the order that screen readers read the elements.  Getting headings right is important because most screen reader users navigate by them.  When I want to see what's available, I just keep tapping next header and hey, "fn foobar".

By the behavior without version numbers and using [actual methods from the docs](https://doc.rust-lang.org/std/collections/vec_deque/struct.VecDeque.html), screen readers see:

```
fn is_empty(&self) -> bool [−]
```

This is good because I get the function name first.  I can simply keep going down the page very quickly, stopping at whatever looks interesting or whatever I'm looking for.

But by the new behavior:

```
1.6.0 [−] fn drain<R>(&mut self, range: R) -> Drain<T> 
```

The most interesting piece of information is `fn drain`, but a screen reader user has to listen to (writing as text for illustration) "one point six point zero left bracket minus right bracket" first.  This is significantly longer than the actual interesting information.

If I had to estimate how much slower I go on pages that use these heavily, I'd have to say at least 2x.

Looking at it in firebug, it appears that the difference is simply that the first header puts the code element in DOM order before the collapsing link, but the second header puts the since and collapsing link before the code.  Looking at it with the other tools in my toolbox, it appears the other headers do actually put the collapsing link first visually with CSS, but I am unsure if this is truly the case.  My tools for actually telling what CSS does are limited.

I can't fix this myself because any change I might make has roughly a 50/50 chance of breaking the CSS and I obviously can't tell if I did or not.  If new CSS is needed (which I suspect) then I can't do anything.  There is a reason I avoid web programming.

### PR DESCRIPTION
**Pull request by mitaa**
fixes #33131 

r? @alexcrichton

### CODE REVIEW

**Comment by durka** [comment]
Can we test this? Is there some tool that pulls out elements in the same order that screen readers do, and we can check the order?

**Comment by mitaa** [comment]
preview is available [here](https://mitaa.github.io/rust/doc/)

@durka 
Not sure, I've tested this using ChromeVox which exhibited the same behaviour as described in the referenced issue.

cc @camlorn

**Comment by camlorn** [comment]
This appears to do it for Firefox and NVDA, my combination.

It's not testable though, no.  Not as far as I know.  In my experience, 99% of the time it's DOM order.  But I'm not confident enough on that to say 100% of the time because there's at least 12 combinations just for Windows now and I'm only on one of them.  Screen readers and accessibility and the like are the least specified and least implemented web technologies, and even basic stuff essentially requires testing all of the combinations that you care about.

Thanks for the quick turnaround.  This improves usability a lot.  Usually I report stuff and it's just like "We'll do it sometime", where actually they mean never.  I hate that I can only report for something like this.

**Pull request merged**
