### PR TITLE
Fix suggestion to introduce explicit lifetime

### LINKED ISSUE #81650: Small error in "introduce explicit lifetime bound" suggestion
[We currently give the following output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=81c95ddcd1e232876d21dac767919959):

```
error[E0311]: the parameter type `T` may not live long enough
  --> src/main.rs:25:11
   |
25 |     scope.spawn(move |_| {
   |           ^^^^^
   |
note: the parameter type `T` must be valid for the anonymous lifetime #2 defined on the function body at 24:1...
  --> src/main.rs:24:1
   |
24 | fn play_with<T: Animal + Send>(scope: &Scope, animal: T) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...so that the type `[closure@src/main.rs:25:17: 27:6]` will meet its required lifetime bounds
  --> src/main.rs:25:11
   |
25 |     scope.spawn(move |_| {
   |           ^^^^^
help: consider introducing an explicit lifetime bound
   |
24 | fn play_with<'a, T: 'a + Animal + Send>(scope: &Scope, animal: T) {
25 |     scope.spawn + 'a(move |_| {
   |
```

The suggestion has a spurious extra `+ 'a` in line 25 that shouldn't be there.

### PR DESCRIPTION
**Pull request by 0yoyoyo**
Addresses #81650

Error message after fix:

```
error[E0311]: the parameter type `T` may not live long enough
  --> src/main.rs:25:11
   |
24 | fn play_with<T: Animal + Send>(scope: &Scope, animal: T) {
   |              -- help: consider adding an explicit lifetime bound...: `T: 'a +`
25 |     scope.spawn(move |_| {
   |           ^^^^^
   |
note: the parameter type `T` must be valid for the anonymous lifetime #2 defined on the function body at 24:1...
  --> src/main.rs:24:1
   |
24 | fn play_with<T: Animal + Send>(scope: &Scope, animal: T) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...so that the type `[closure@src/main.rs:25:17: 27:6]` will meet its required lifetime bounds
  --> src/main.rs:25:11
   |
25 |     scope.spawn(move |_| {
   |           ^^^^^
```

### CODE REVIEW

**Comment by estebank** [comment]
@bors r+

Let's not close the original report. This PR addresses the bad suggestion, but if you now follow the suggestion chain the compiler sends you in, we never point at `Foo` needing a lifetime. We need to address that as well.

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/82019#issuecomment-778096044
Should bless the test with nll mode.
@bors r-

**Comment by 0yoyoyo** [comment]
Thank you for following up. I pushed nll test.
But this is my first time to add nll test and I'm not sure it is correct. (I added a file to pass the test with `--compare-mode=nll`. Is it enough?)

**Comment by JohnTitor** [comment]
That's it, thanks!
@bors r=estebank

**Pull request merged**
