### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by Noratrieb**
Successful merges:

 - #106321 (Collect and emit proper backtraces for `delay_span_bug`s)
 - #106397 (Check `impl`'s `where` clauses in `consider_impl_candidate` in experimental solver)
 - #106427 (Improve fluent error messages)
 - #106570 (add tests for div_duration_* functions)
 - #106648 (Polymorphization cleanup)
 - #106664 (Remove unnecessary lseek syscall when using std::fs::read)
 - #106709 (Disable "split dwarf inlining" by default.)
 - #106715 (Autolabel and ping wg for changes to new solver)
 - #106717 (fix typo LocalItemId -> ItemLocalId)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=106321,106397,106427,106570,106648,106664,106709,106715,106717)

### CODE REVIEW

**Comment by Nilstrieb** [comment]
@rust-timer build 28d6383a20203a942f27d95cd73e4a0840215807
@rust-timer build 40306d15c01aa204444bad40f144f67eab627212
@rust-timer build 31e458cecb1ee908068a512aae377eabeaffe4c2

**Comment by Nilstrieb** [comment]
@rust-timer build 40306d15c01aa204444bad40f144f67eab627212

**Comment by Nilstrieb** [comment]
@rust-timer build 40306d15c01aa204444bad40f144f67eab627212

**Comment by Nilstrieb** [comment]
Weird, maybe it's just noise. whatever, let's also try the unlikely candidates
@rust-timer build 0f72f44d56cbdd8e6b219a1eb38b0aa705c90907

**Comment by Nilstrieb** [comment]
#106321 seems to be the culprit, the same tiny regressions in incr builds. Pretty weird since that shouldn't have touched the happy path but maybe something from the flushing change? Or do we sometimes delay bugs in some weird ways anyways even on the happy path?
I'm inclined to ignore the regression since it's so tiny but maybe there's an easy fix
cc @compiler-errors

**Comment by pnkfelix** [comment]
My understanding is that the code running `delay_span_bug` should never cause any semantic effect for input source that satisfies Rust's static analyses. (Because the whole point is there are two cases: either the static analyses reject the input for some other reason, or the static analyses accept the input but then that causes the `delay_span_bug` to fire off an ICE.)

I too am confused about why #106321 could have caused a performance impact. (We don't benchmark the compiler against type-incorrect code, do we? Even if we do/did, none of the flagged cases represent such instances...)

I'm thus inclined to categorize this as noise and mark it as triaged; if @compiler-errors wants to look into it, that's fine, but we don't need to add it to our accumulated set of perf regression issues.

@rustbot label:  +perf-regression-triaged

**Pull request merged**
