### PR TITLE
Update to LLVM 19

### LINKED ISSUE #121444: LLVM ERROR `Attribute 'align' exceed the max size 2^14`
auto-reduced (treereduce-rust):
````rust
// #45662

#[repr(align(536870912))]
pub struct A(i64);

pub extern "C" fn foo(x: A) {}

fn main() {
    foo(A(0));
}


````

original:
````rust
//@ run-pass

#![allow(stable_features)]
#![allow(unused_variables)]

// #45662

#![feature(repr_align)]

#[repr(align(536870912))]
pub struct A(#[allow(dead_code)] i64);

#[allow(improper_ctypes_definitions)]
pub extern "C" fn foo(x: A) {}

fn main() {
    foo(A(0));
}

````

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zincremental-verify-ich=yes -Cincremental=<dir> -Cdebuginfo=2`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused variable: `x`
 --> /tmp/icemaker_global_tempdir.YLDguKS9zOCA/rustc_testrunner_tmpdir_reporting.HqYrVsxsA6S8/mvce.rs:6:23
  |
6 | pub extern "C" fn foo(x: A) {}
  |                       ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: field `0` is never read
 --> /tmp/icemaker_global_tempdir.YLDguKS9zOCA/rustc_testrunner_tmpdir_reporting.HqYrVsxsA6S8/mvce.rs:4:14
  |
4 | pub struct A(i64);
  |            - ^^^
  |            |
  |            field in this struct
  |
  = note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
  |
4 | pub struct A(());
  |              ~~

warning: `extern` fn uses type `A`, which is not FFI-safe
 --> /tmp/icemaker_global_tempdir.YLDguKS9zOCA/rustc_testrunner_tmpdir_reporting.HqYrVsxsA6S8/mvce.rs:6:26
  |
6 | pub extern "C" fn foo(x: A) {}
  |                          ^ not FFI-safe
  |
  = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
  = note: this struct has unspecified layout
note: the type is defined here
 --> /tmp/icemaker_global_tempdir.YLDguKS9zOCA/rustc_testrunner_tmpdir_reporting.HqYrVsxsA6S8/mvce.rs:4:1
  |
4 | pub struct A(i64);
  | ^^^^^^^^^^^^
  = note: `#[warn(improper_ctypes_definitions)]` on by default

Attribute 'align' exceed the max size 2^14
ptr @_ZN4mvce3foo17h02ccc75a6bd1c329E
in function _ZN4mvce3foo17h02ccc75a6bd1c329E
LLVM ERROR: Broken function found, compilation aborted!

```

</p>
</details>

### LINKED ISSUE #128212: Incorrect code generated from inline assembly with `inout` register on riscv32im-unknown-none-elf
I tried compiling this code with a target of `riscv32im-unknown-none-elf`:

```rust
#![no_std]

static mut MY_BUFFER: [u32; 4] = [0u32; 4];

#[no_mangle]
unsafe fn using_inout() {
    let mut start = MY_BUFFER.as_mut_ptr();
    ::core::arch::asm!(
            "ecall",
            inout("a0") start);
    _ = start;
}
````

The assembly generated is incorrect, since it doesn't add in the lower 16 bits of the address of `MY_BUFFER` before calling the `ecall`:

```asm
using_inout:
        lui     a0, %hi(example::MY_BUFFER::he36bd30b506a9b69)
        ecall
        ret
```

As a workaround, changing the `inout` to `inlateout` seems to fix the problem:

```asm
using_inlateout:
        lui     a0, %hi(example::MY_BUFFER::he36bd30b506a9b69)
        addi    a0, a0, %lo(example::MY_BUFFER::he36bd30b506a9b69)
        ecall
        ret
```

Here is a compiler explorer link for rust nightly that demonstrates the problem:

https://godbolt.org/z/xMjoTo5oY

(For reference in case it gets fixed in nightly, it's also present in rust 1.80.0)

### PR DESCRIPTION
**Pull request by nikic**
The LLVM 19.1.0 final release is planned for Sep 3rd. The rustc 1.82 stable release will be on Oct 17th.

The unstable MC/DC coverage support is temporarily broken by this update. It will be restored by https://github.com/rust-lang/rust/pull/126733. The implementation changed substantially in LLVM 19, and there are no plans to support both the LLVM 18 and LLVM 19 implementation at the same time.

This update enables additional target features by default for wasm targets. See https://github.com/rust-lang/rust/pull/128511#issuecomment-2299051004 for details.

Related changes:
 * https://github.com/rust-lang/rust/pull/127605
 * https://github.com/rust-lang/rust/pull/127613
 * https://github.com/rust-lang/rust/pull/127654
 * https://github.com/rust-lang/rust/pull/128141
 * https://github.com/llvm/llvm-project/pull/98933

Fixes https://github.com/rust-lang/rust/issues/121444.
Fixes https://github.com/rust-lang/rust/issues/128212.

### CODE REVIEW

**Comment by nikic** [comment]
@rust-timer build d009d2d060b39b34c04f23a9b0700a72d95ed9ea

**Comment by nikic** [comment]
`tests/run-make/wasm-abi` on wasm-wasip1 fails with:
```
Caused by:
    0: failed to instantiate "foo.wasm"
    1: incompatible import type for `host::two_i32`
    2: function types incompatible: expected func of type `(i32) -> ()`, found func of type `() -> (i32, i32)`
```

I believe this is caused by https://github.com/llvm/llvm-project/pull/88492, which now seems to ignore the `+multivalue` feature unless the `experimental-mv` target ABI is used.

I'm a bit unclear on what the implications of that change on Rust are. Are we supposed to switch all our wasm targets to `experimental-mv` so that the `extern "wasm"` ABI isn't ignored? I don't really get this change, given that `+multivalue` is a per function target feature while the target ABI is global.

cc @alexcrichton

**Comment by CryZe** [comment]
> Are we supposed to switch all our wasm targets to `experimental-mv` so that the `extern "wasm"` ABI isn't ignored?

That sounds like a mistake, because the plan is for `extern "C"` to match `clang` soon, which would mean that `experimental-mv` would have to be off. 

Another point to add is that `+multivalue` is now also active for all functions. This to me means that `extern "wasm"` currently serves no purpose anymore in the first place, especially with `wasm-bindgen` not having ended up using it. So to me this either means breaking (and or removing) `extern "wasm"` for now, or patching LLVM to support `experimental-mv` on a per function basis.

**Comment by nikic** [comment]
> Yes, but `+multivalue` is active by default now (which I assume also means it's on all functions? I wasn't even aware there's per function features until you mentioned it). https://github.com/llvm/llvm-project/pull/96584/files#diff-0580bdcbbd17bc30025ee4bb132537f58004b39bb7a86f0a8c9e6a12d96c8dd5R113

Ah, I see what you mean now. So I guess if we wanted to keep the status quo, we'd have to a) use experimental-mv ABI and b) add `-multivalue` to all non-extern-wasm functions to opt out again, which is kind of convoluted.

For the record, if I set `llvm_abiname` to `experimental-mv` without doing anything else, then the run-make test passes and this ui test fails instead:
```
---- [ui] tests/ui/numbers-arithmetic/u128.rs stdout ----

error: test run failed!
status: exit status: 134
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/numbers-arithmetic/u128" && RUST_TEST_THREADS="64" "/wasmtime-v19.0.0-x86_64-linux/wasmtime" "run" "-C" "cache=n" "--dir" "." "--env" "RUSTC_BOOTSTRAP" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/numbers-arithmetic/u128/a.wasm"
stdout: none
--- stderr -------------------------------
Error: failed to run main module `/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/numbers-arithmetic/u128/a.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x7f36 - a.wasm!memset
           1: 0xaf6b - a.wasm!core::fmt::num::fmt_u128::h1ec55f0ea0d172dc
           2: 0xae26 - a.wasm!core::fmt::num::<impl core::fmt::Display for u128>::fmt::h700225ef905cc701
           3: 0x9721 - a.wasm!core::fmt::write::ha0695b3bfa74a24d
           4: 0x8c7f - a.wasm!alloc::fmt::format::format_inner::h00360545e4341607
           5:  0x80d - a.wasm!u128::main::h1267772770aec22e
           6:  0x318 - a.wasm!std::sys::backtrace::__rust_begin_short_backtrace::hd80d215d9cabb8e6
           7:  0x30b - a.wasm!std::rt::lang_start::{{closure}}::h676c49074f69fa27
           8: 0x2a2a - a.wasm!std::rt::lang_start_internal::h7a5c1daedfda3666
           9: 0x156f - a.wasm!__main_void
          10:  0x2e3 - a.wasm!_start
    2: wasm trap: out of bounds memory access
------------------------------------------
```
That's possibly related to https://github.com/rust-lang/rust/issues/127318.

**Comment by CryZe** [comment]
Is this with wasm32-unknown-unknown or WASI?

**Comment by alexcrichton** [comment]
I would agree with @CryZe that the best solution is to basically "do nothing" and disable any tests related to multivalue. (and/or just comment out the multivalue parts of the tests). There's been various discussions in a bunch of places with varying degrees of depth and complexity but the basic conclusion, in my opinion, is that multivalue just isn't feasible with LLVM. The `"wasm"` ABI definitely never materialized and should be removed and preexisting multivalue experiments were fraught with issues.

The goal at this point is to match Clang's C ABI on all targets, whether or not they're `wasm32-unknown-unknown` or not. Having a per-compilation-unit ABI setting is not usable from Rust since we're not going to add an entire target just for multi-value. I would still like to see a per-function setting for multi-value one day but there's not much interest in doing so from the current wasm backend maintainers since I don't think they have use cases to motivate it and aren't too interested into digging into other use cases.

**Comment by nikic** [comment]
@alexcrichton To check my understanding here, we have following ABIs:

 1. The C ABI on wasm, in the sense of `-Z wasm-c-abi=spec`.
 2. The legacy rustc wasm ABI in the sense of `-Z wasm-c-abi=legacy` (which is the default).
 3. The `extern "wasm"` ABI, which is `-Z wasm-c-abi=legacy` plus the `+multivalue` feature.

Is that correct? In particular I want to confirm that 2 and 3 are not the same thing. The suggestion here is that we can go ahead and remove `extern "wasm"` (and thus our only direct use of `+multivalue`), while leaving the "normal" legacy wasm ABI alone?

If that's the case, I'd rather just go ahead and do that rather than silently break it on LLVM 19.

**Comment by alexcrichton** [comment]
I believe that's correct yeah, and I'll cc @daxpedda here as well since they added `-Zwasm-c-abi` I believe. The exact definition of the `extern "wasm"` ABI in (3) I think it's quite "just" legacy+multivalue, but regardless it's distinct from (2). Furthermore the `extern "wasm"` ABI has always been unstable and as far as I'm aware nothing is relying on it so it should be a suitable candidate for removal.

Put another way the only way to keep `extern "wasm"` would be to have `-target-abi=experimental-mv` on a per-function basis. That doesn't exist in LLVM (AFAIK) so there's just no way to keep `extern "wasm"`. The implementation using `+multivalue` on functions that use `extern "wasm"` is broken with LLVM 19+ as well.

**Comment by nikic** [comment]
Okay, thanks for walking me through it! In that case I'll work on a PR to remove `extern "wasm"` / the `wasm_abi` feature.

For future reference, wasm_abi was added in https://github.com/rust-lang/rust/pull/83763 and `-Z wasm-c-abi` in https://github.com/rust-lang/rust/pull/117919.

**Comment by daxpedda** [comment]
Thank you for pinging me!

Removing `extern "wasm"` should be fine indeed, I can confirm that `wasm-bindgen` is not using it.
Of course it would be nice if we could get multivalue support in Rust, but as was already said, the motivation to fix LLVM to support it is quite low.

However, I believe we should not enable the multivalue and reference types target features by default, as both are unimplemented and it would be wrong for us to advertise that they are required to read the Wasm module.

I'm unsure exactly how to do that, but I believe we might want to patch our fork [here](https://github.com/nikic/llvm-project/blob/7c93dc08e874b5253a8721f1ee37b22fbe02b6b5/clang/lib/Basic/Targets/WebAssembly.cpp#L153-L158) and [here](https://github.com/nikic/llvm-project/blob/7c93dc08e874b5253a8721f1ee37b22fbe02b6b5/llvm/lib/Target/WebAssembly/WebAssembly.td#L112-L114) or use the `-target-cpu=mvp` by default and enable our own set of default features, though I believe this would make users unable to use the MVP target CPU to actually disable all target features (which might be useless anyway because it requires `build-std` to fully work). Happy to make a PR after some input.

Or maybe we might consider stabilizing the multivalue feature without the ability to export functions using it. This would still be useful for non-exported functions. But probably not because its still exhibiting [bugs](https://github.com/rust-lang/rust/issues/127318).

**Comment by nikic** [comment]
PR for removing `extern "wasm"` is up at https://github.com/rust-lang/rust/pull/127605.

> I'm unsure exactly how to do that, but I believe we might want to patch our fork [here](https://github.com/nikic/llvm-project/blob/7c93dc08e874b5253a8721f1ee37b22fbe02b6b5/clang/lib/Basic/Targets/WebAssembly.cpp#L153-L158) and [here](https://github.com/nikic/llvm-project/blob/7c93dc08e874b5253a8721f1ee37b22fbe02b6b5/llvm/lib/Target/WebAssembly/WebAssembly.td#L112-L114) or use the `-target-cpu=mvp` by default and enable our own set of default features, though I believe this would make users unable to use the MVP target CPU to actually disable all target features (which might be useless anyway because it requires `build-std` to fully work). Happy to make a PR after some input.

We cannot patch our LLVM fork to make functional changes. We can either use the `mvp` cpu with default features `+mutable-globals,+sign-ext` or keep the `generic` cpu with default features `-multivalue,-reference-types`.

**Comment by alexcrichton** [comment]
Ah yeah I'll highlight @CryZe's point [above](https://github.com/rust-lang/rust/pull/127513#issuecomment-2220484454) in that `+multivalue` is now on-by-default for LLVM at all times, but it has no actually affect on anything unless `-target-abi=experimental-mv` is also passed. I believe the maintainers wanted an up-to-date list of wasm proposals-as-features in terms of what's active, but it's acknowledged that the multivalue support in LLVM is not complete at this time.

**Comment by ZhuUx** [comment]
Nice to see we start updating in-tree update.
A bug might need to be fixed with llvm-19:
Current rustc compiled on llvm-19 cannot compile code with debuginfo. That's because [LLVMRustDIBuilderInsertDeclareAtEnd](https://github.com/rust-lang/rust/blob/b286722878e18db29a7fbe672be7c4d3b02e8e4d/compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp#L1150) cast `Result`, which is `DbgVariableRecord *` to `Instruction *` mistakenly. Given that rustc never uses the returned value, this can be fixed by removing `Result` and let the function return `void`.

**Comment by nikic** [comment]
> Nice to see we start updating in-tree update. A bug might need to be fixed with llvm-19: Current rustc compiled on llvm-19 cannot compile code with debuginfo. That's because [LLVMRustDIBuilderInsertDeclareAtEnd](https://github.com/rust-lang/rust/blob/b286722878e18db29a7fbe672be7c4d3b02e8e4d/compiler/rustc_llvm/llvm-wrapper/RustWrapper.cpp#L1150) mistakenly cast `Result`, which is `DbgVariableRecord *`, to `Instruction *`. Given that rustc never uses the returned value, this can be fixed by removing `Result` and making the function return `void`.

Thanks for pointing that out. I agree that the code is incorrect. What's weird is that generating debuginfo actually works find in practice, even in assertion-enabled builds.

And after poking around a bit, the reason is this incorrect code for setting LLVM_NDEBUG: https://github.com/rust-lang/rust/blob/b286722878e18db29a7fbe672be7c4d3b02e8e4d/src/bootstrap/src/core/build_steps/compile.rs#L1216-L1218 NDEBUG has nothing to do with debuginfo, it's about assertions :( So we end up building our LLVM FFI bindings without assertions, which is the reason why the incorrect cast gets silently accepted. This is also dangerous because NDEBUG is an ABI-breaking flag.

I guess you are using a build where llvm_release_debuginfo is enabled, which is why NDEBUG is not defined for you and you do get an assertion failure.

I'll put up a PR to fix this soon.

**Comment by nikic** [comment]
@tmandry x86_64-fuchsia fails with libunwind related errors. Does this sound familiar?
<details>
```
  = note: LC_ALL="C" PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/bin:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcqU84YN/symbols.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_main-8977a8ea0dab97c6.rustc_main.d95a25194ca62319-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/psm-8e6af82280e3058e/out" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-b5e77ebbcb590273/out" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/lib" "-L" "/usr/lib/gcc/x86_64-linux-gnu/11" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-Wl,-Bdynamic" "-lrustc_driver-e5002116274ca457" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-28059a4f700ed3e1" "-Wl,-Bstatic" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-7e27e1127686da99.rlib" "-Wl,-Bdynamic" "-lrt" "-ldl" "-lm" "-ldl" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-B/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-B/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-B/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-fuse-ld=lld" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/self-contained" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_main-8977a8ea0dab97c6" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-Wl,-z,origin" "-Wl,-rpath,$ORIGIN/../lib"
  = note: rust-lld: error: undefined reference due to --no-allow-shlib-undefined: _Unwind_GetTextRelBase
          >>> referenced by /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-e5002116274ca457.so
          
          rust-lld: error: undefined reference due to --no-allow-shlib-undefined: _Unwind_GetRegionStart
          >>> referenced by /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-e5002116274ca457.so
          
          rust-lld: error: undefined reference due to --no-allow-shlib-undefined: _Unwind_GetDataRelBase
          >>> referenced by /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-e5002116274ca457.so
          
          rust-lld: error: undefined reference due to --no-allow-shlib-undefined: _Unwind_GetLanguageSpecificData
          >>> referenced by /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-e5002116274ca457.so
          
          rust-lld: error: undefined reference due to --no-allow-shlib-undefined: _Unwind_DeleteException
          >>> referenced by /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-e5002116274ca457.so
          
          rust-lld: error: undefined reference due to --no-allow-shlib-undefined: _Unwind_Resume_or_Rethrow
          >>> referenced by /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-e5002116274ca457.so
          collect2: error: ld returned 1 exit status
```
</details>

**Comment by daxpedda** [comment]
> Ah yeah I'll highlight @CryZe's point [above](https://github.com/rust-lang/rust/pull/127513#issuecomment-2220484454) in that `+multivalue` is now on-by-default for LLVM at all times, but it has no actually affect on anything unless `-target-abi=experimental-mv` is also passed.

It does actually have an effect: non-C ABI functions are able to use multivalue returns, which is still a performance improvement for Rust functions used internally in the Wasm module. `experimental-mv` is only required for "C" ABI functions, usually used to export or import functions.

**Comment by alexcrichton** [comment]
From discussoin on https://github.com/nikic/rust/pull/1 I might summarize the impact of this PR on wasm targets in the release notes as:

> WebAssembly target support for the `multivalue` target feature has changed when upgrading to LLVM 19. Support for generating functions with multiple returns no longer works and `-Ctarget-feature=+multivalue` has a different meaning than it did in LLVM 18 and prior. The WebAssembly target features `multivalue` and `reference-types` are now both enabled by default, but generated code is not affected by default. These features being enabled are encoded in the `target_features` custom section and may affect downstream tooling such as `wasm-opt` consuming the module, but the actual generated WebAssembly will continue to not use either `multivalue` or `reference-types` by default. There is no longer any supported means to generate a module that has a function with multiple returns.

**Comment by tmandry** [comment]
> x86_64-fuchsia fails with libunwind related errors. Does this sound familiar?

I'm off today,
@rustbot ping fuchsia

**Comment by djkoloski** [comment]
> x86_64-fuchsia fails with libunwind related errors. Does this sound familiar?

This looks like a failure to compile with stage0. The closest I remember is #105967 but that was related to allocators and was specific to Fuchsia. My guess is that this is related to some compilation settings specific to the script we're using for Fuchsia.

I'm done for the day but we can attempt a repro next week.

**Comment by nikic** [comment]
@djkoloski @tmandry Ooops, it looks like the Fuchsia issue turned out to be PEBKAC. It looks like I tested that image with `DEPLOY=1` set (even though it is not a `dist-` image), and that resulted in that error for whatever reason. It runs successfully when not setting this environment variable.

**Comment by nikic** [comment]
Testing Apple.

@bors try

**Comment by nikic** [comment]
Testing MSVC.

@bors try

**Comment by tgross35** [comment]
Fixes https://github.com/rust-lang/rust/issues/128212 if updated past https://github.com/llvm/llvm-project/pull/100843

**Comment by nikic** [comment]
Okay, this should be about ready now. Once https://github.com/rust-lang/rust/pull/128141 is merged, I'll rebase to the current release/19.x branch and push it to our LLVM fork.

**Comment by Zalathar** [comment]
Looks like adding `//@ ignore-llvm-version: 19 - 99` to the MC/DC coverage tests had the side-effect of breaking them in the LLVM 18 job, because of the modified source text and line numbers.

I think we’ll need to do one of:
- Re-bless the tests against LLVM 18
- Fully ignore the MC/DC tests for now, and make #126733 responsible for turning them back on

**Comment by cuviper** [comment]
> * Re-bless the tests against LLVM 18

Thanks, I've done that.

@bors r+

**Comment by Zalathar** [comment]
@cuviper I think this is still going to fail, because the `.coverage` files need to be blessed as well.

(For annoying build-system reasons, those files don't get blessed if you don't have `build.profiler = true` in your config.)

Please see https://github.com/rust-lang/rust/commit/312808ec4ba44a5b45c592686ef6e31c6c334b44 (or https://github.com/Zalathar/rust/tree/bless-mcdc-19) for a version of the bless patch that also blesses those files.

**Comment by tgross35** [comment]
@Zalathar is there any specific CI job you think would fail, or just the usual x86 dist? We can run a try job while this is still in the queue.

**Comment by Zalathar** [comment]
I believe `x86_64-gnu-llvm-18` is going to fail again.

(Any job that doesn't use LLVM 18 should be fine.)

**Comment by Zalathar** [comment]
Hmm, though now that I think about it, maybe that job won't run the tests in `coverage-run` mode at all? I think that's how the current `x86_64-gnu-llvm-17` job works.

So if that's the case, maybe this will work as-is after all.

(The affected tests will still be broken on LLVM 18, but that might not break CI if they never run in that configuration.)

**Comment by Zalathar** [comment]
In summary:

- After more investigation, I no longer think this is going to fail.
- It might be worth running a try job against `x86_64-gnu-llvm-18`, to double-check.

**Comment by tgross35** [comment]
@bors try

If that passes then it can just come as a followup. @cuviper if you are around, might as well just update that anyway.

**Comment by slanterns** [comment]
Trying an r+'ed PR will cause it merged without going through testing.

**Comment by Zalathar** [comment]
Looks like doing a `try` job here would be awkward, so I'll do a separate check over in #114917 instead.

**Comment by tgross35** [comment]
> Trying an r+'ed PR will cause it merged without going through testing.

(I thought it was only try->r+, not the other way around. Thanks)

**Comment by cuviper** [comment]
> Please see [312808e](https://github.com/rust-lang/rust/commit/312808ec4ba44a5b45c592686ef6e31c6c334b44) (or https://github.com/Zalathar/rust/tree/bless-mcdc-19) for a version of the bless patch that also blesses those files.

Can you send a followup PR to bless the additional files? I understand it won't be an issue for Rust CI, but those tests may still run in external builds (like distros) if appropriate profiler libs are provided.

**Comment by apiraino** [comment]
@nikic This looks like an major version upgrade, right? Would you like this on beta soon? I'll nominate it, let me know if there's anything against or just :shrug: 

@rustbot label +beta-nominated

**Comment by cuviper** [comment]
As such a major change, it's too risky for beta backport. We should let it ride the normal release train.

@rustbot label -beta-nominated

**Comment by nikic** [comment]
> > Please see [312808e](https://github.com/rust-lang/rust/commit/312808ec4ba44a5b45c592686ef6e31c6c334b44) (or https://github.com/Zalathar/rust/tree/bless-mcdc-19) for a version of the bless patch that also blesses those files.
> 
> Can you send a followup PR to bless the additional files? I understand it won't be an issue for Rust CI, but those tests may still run in external builds (like distros) if appropriate profiler libs are provided.

As long as https://github.com/rust-lang/rust/pull/126733 lands in the same release, it probably doesn't matter?

> As such a major change, it's too risky for beta backport. We should let it ride the normal release train.

Yeah. The fixed issues here are just incidental. We could backport a fix for https://github.com/rust-lang/rust/issues/128212 to the beta LLVM, but I don't think it's necessary.

**Comment by Kobzol** [comment]
Improvements far outweigh the regressions.

@rustbot label: +perf-regression-triaged

**Comment by alexcrichton** [comment]
For the `relnotes` label here could the wasm-related changes be removed from this PR? There's been a bit of confusion on what exactly the impact of this change was on wasm targets and such confusion should be addressed and resolved in https://github.com/rust-lang/rust/pull/128511, notably with updated release notes that look [like this](https://github.com/rust-lang/rust/pull/128511#issuecomment-2299051004). In the spirit of not duplicating release notes across PRs it might be best to leave the wasm-specific impact to that PR perhaps? (or alternatively rewrite this PR's release notes to match that PR's and remove `relnotes` from that PR, either way is fine by me)

**Comment by jieyouxu** [comment]
> For the `relnotes` label here could the wasm-related changes be removed from this PR? There's been a bit of confusion on what exactly the impact of this change was on wasm targets and such confusion should be addressed and resolved in #128511, notably with updated release notes that look [like this](https://github.com/rust-lang/rust/pull/128511#issuecomment-2299051004). In the spirit of not duplicating release notes across PRs it might be best to leave the wasm-specific impact to that PR perhaps? (or alternatively rewrite this PR's release notes to match that PR's and remove `relnotes` from that PR, either way is fine by me)

FYI @rust-lang/release as this is easy to miss.

**Review by NameYourOwn — APPROVED** [review]

**Pull request merged**
