### PR TITLE
Revert #34836 "Refactored code to access TLS only in case of panic"

### PR DESCRIPTION
**Pull request by TimNN**
It has likely caused the last two builds to fail:
- https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/1774
- https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/1776

(the PR was accidentally merged without going through @bors).

### CODE REVIEW

**Comment by TimNN** [comment]
cc @eddyb @alexcrichton

**Comment by eddyb** [comment]
Hoping to merge this in #34863 alongside a regression fix that we want to get in the next nightly (#34846).

**Comment by alexcrichton** [comment]
Yeah sorry about that! Let's just merge.

**Pull request merged**
