### PR TITLE
Add doc examples for iter flatten

### PR DESCRIPTION
**Pull request by pickfire**
r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

r=me once CI pass

**Comment by pickfire** [comment]
Ah, I just realized we should hide the imports.

**Comment by pickfire** [comment]
I just realized we don't have this for the rest of iterators docs, we may need to standardize, most of the docs looks the same but some look different, this one look different too.

**Comment by pickfire** [comment]
@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

I want to know what the docs team before proceeding.

**Comment by JohnCSimon** [comment]
Ping from triage @pickfire can you please address the merge conflict?

**Comment by pickfire** [comment]
@JohnCSimon I am not sure if this pull request is good given that the other parts needed to be changed later when this is merged, I wonder if @GuillaumeGomez think this is good.

**Comment by GuillaumeGomez** [comment]
Well, still think the `collect` and type annotation are too much.

**Comment by pickfire** [comment]
True, even though I think it is easier for beginners but it makes it weird to have some parts have this by itself. Closing it.

**Pull request closed without merging**
