### PR TITLE
Make empty arrays `Copy`

### PR DESCRIPTION
**Pull request by tbu-**
This PR is based on #30130.

The relevant commit from this PR is https://github.com/tbu-/rust/commit/1769c98d8544fbd6a9d6d6b3893ea4e86b4ae8f9.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can this just be folded into #30130? It seems pretty harmless.

Also why does this need a compiler change? Can this not just be a trait impl?

**Comment by tbu-** [comment]
I'll put this into #30130.

**Comment by alexcrichton** [comment]
To copy over my concerns from #30130, I was a little hesitant when I realized that other marker traits like `Send` and `Sync` could in theory also be implemented for `[T; 0]` with no restrictions on `T`, but they currently aren't either (a tad inconsistent).

I'm gonna tag this with `T-libs` so it comes up during triage and we can discuss.

**Comment by tbu-** [comment]
The difference to `Send` and `Sync` is that you can still force a struct containing a member that does not implement the trait to be `Send` or `Sync` anyway. You can't do the same for `Copy`.

**Comment by aturon** [comment]
We discussed this in the libs team meeting this week, and would like to see a stronger rationale for making this change before we land it.

**Comment by alexcrichton** [comment]
Closing due to @aturon's previous comment.

**Pull request closed without merging**
