### PR TITLE
Remove unused(?) `~/rustsrc` folder from docker script

### PR DESCRIPTION
**Pull request by lqd**
Every time I run a docker image, the script creates an empty `~/rustsrc` folder. It doesn't seem to be referenced anywhere else, so I'd like to remove it.

Incidentally, this also documents DIST_TRY_BUILD as I fail to find it from a simple search any time I look for it to eg enable tests on try builds.

### CODE REVIEW

**Comment by lqd** [comment]
The try build passed tests, so this is not load-bearing at the very least in this situation.
Let's ask someone with ancient CI knowledge and see what's what: r? @pietroalbini feel free to reroll, and it's not urgent.

**Comment by fmease** [comment]
bors sleepy @bors r-

**Pull request merged**
