### PR TITLE
ci: Upgrade Travis to Xenial

### PR DESCRIPTION
**Pull request by alexcrichton**
In theory we shouldn't require trusty so long as docker continues to
work!

### CODE REVIEW

**Comment by alexcrichton** [comment]
It was noted [here](https://github.com/travis-ci/travis-ci/issues/9696#issuecomment-448361108) that trusty is EOL soon, so let's see how we fare on xenial.

@bors: r+

**Comment by alexcrichton** [comment]
cc @kennytm

**Comment by nagisa** [comment]
@alexcrichton won’t this increase the GLIBC version, or is the toolchain independent from the ubuntu version used?

**Comment by alexcrichton** [comment]
It won't, no, because the travis environment isn't used to build any release artifacts. Those are all done in controlled docker containers

**Comment by nikic** [comment]
Is something going wrong with the caching here? It looks like the docker image is getting rebuilt on each run.

**Comment by kennytm** [comment]
The container hashes seem to be different every time it is uploaded 🤔

**Comment by alexcrichton** [comment]
Ok I think this is a cache thrashing issue. Looks like caches indeed are still updated in this PR and are actually reused, but my guess is that the problem is that this PR is using the same cache as the current PRs. The cache key is just a shasum of the directory contents, which doesn't account for docker versions. It looks like docker doesn't reuse some caches here. 

That in turn means that the cache key from an old build isn't reusable by this PR. This PR's caches aren't usable by other PR's caches. If this PR alternates with another (which almost always happens for spurious failures retried) then we're going back and forth timing out. 

I'm gonna fix this by throwing `docker --version` into the cache key, and that'll make this no longer share cache keys with other PRs and will hopefully fix future iterations of this as well. This will still likely time out (hopefully at most) once as we populate the new cache keys with docker images.

**Comment by alexcrichton** [comment]
@bors: retry

That's the one expected time out here

**Pull request merged**
