### PR TITLE
Fix generator size regressions due to optimization

### PR DESCRIPTION
**Pull request by tmandry**
I tested the generator optimizations in #60187 and #61922 on the Fuchsia
build, and noticed that some small generators (about 8% of the async fns
in our build) increased in size slightly.

This is because in #60187 we split the fields into two groups, a
"prefix" non-overlap region and an overlap region, and lay them out
separately. This can introduce unnecessary padding bytes between the two
groups.

In every single case in the Fuchsia build, it was due to there being
only a single variant being used in the overlap region. This means that
we aren't doing any overlapping, period. So it's better to combine the
two regions into one and lay out all the fields at once, which is what
this change does.

r? @cramertj 
cc @eddyb @Zoxc

### CODE REVIEW

**Comment by tmandry** [comment]
This actually exposed a latent bug related to uninhabitedness (basically #59972). I'm working on a PR to fix this, which this PR is blocked on.

**Comment by JohnCSimon** [comment]
@tmandry Howdy from Triage! Is this PR still blocked?

**Comment by tmandry** [comment]
Yes, on #63035 (I’ll rebase once I get an r+)

**Pull request merged**
