### PR TITLE
[PERF] Tweak inlining threshold

### PR DESCRIPTION
**Pull request by cjgillot**
r? @ghost

### CODE REVIEW

**Comment by cjgillot** [comment]
With x3 threshold.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
On rustc's own performance (measured by check builds):
- doubling the inlining threshold gives us a ~0.6 % improvement;
- tripling the inlining threshold does not improve anything;
- doubling + resume further improves to ~0.8%.

On produced code quality:
- the compile time slowdown is sensible for double & double+resume, up to 3-4%, with improvements of the same magnitude, binary size increases up to 9%;
- the slowdown for triple is much larger up to 10%, with binary size +18%.

Note: ignoring resumes has a large effect on keccak.

I tend to recommend the solution "double threshold + lower resume cost", which is the current PR state.  It achieves a sizeable improvement on compile and run time, with a limited compilation slowdown in the worst case.

The effect on lowering resume & landing pad cost can be explained by the fact they are always present on in generic code, but can disappear if that generic code is inlined with simple monomorphic types.

r? @nnethercote how do you recommend we proceed, either for more accurate measurements, or to decide on good values?

**Comment by oli-obk** [comment]
I never thought about this before you mentioned `resume`, but could it be useful to avoid inlining any calls in cleanup-basic-blocks, essentially pessimizing the panic paths by never inlining anything in them.

**Comment by cjgillot** [comment]
We already skip inlining into cleanup basic blocks, https://github.com/rust-lang/rust/pull/102264/files#diff-deee82aaf9baf43ab05d939355f6249fdacf8959bc0e06c9574283453f838ee9R124.  I mention "resume" because we may add new cleanup basic blocks from the callee.

**Comment by nnethercote** [comment]
For a high level view, I like to click "show non-relevant results" and then look at the mean in the "❌,✅" row of the summary data. It gives a single number across the entire suite for a metric. Using that, and ignoring the "triple" configuration which definitely seems suboptimal:

| | double |  double+resume |
| -- | -- | -- |
| instrs | -0.33% | -0.21% |
| cycles | +0.26% | +0.10% | 
| max-rss | +0.42% | +0.72% |
| binary size | +0.57% | +0.52% |
| wall-time | +0.13% | +0.34% | 
| bootstrap | ? | 625.6s |

Unfortunately we are missing the bootstrap number for "double".

"double" looks better to me on almost every metric.

Having said that, instruction count numbers for both configurations look good, but all the other metrics look bad, except for bootstrap timings for "double+resume".

I would suggest rerunning measurements on "double" to get the bootstrap measurement. And probably also try a smaller increase, perhaps 1.5x.

**Comment by cjgillot** [comment]
With 1.5 + resume.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
Bootstrap results for simple double is here: (https://github.com/rust-lang/rust/commit/d586a2e8d43a720fae82302fba3996953f07ef05): [comparison URL](https://perf.rust-lang.org/compare.html?start=09ae7846a272a500ff7145255f0de5556c0b8949&end=d586a2e8d43a720fae82302fba3996953f07ef05&stat=instructions:u).

**Comment by cjgillot** [comment]
| | double |  double+resume | 1.5 + resume |
| -- | -- | -- | -- |
| instrs | -0.33% | -0.21% | -0.15% |
| cycles | +0.26% | +0.10% | +0.02% |
| max-rss | +0.42% | +0.72% | +0.66% |
| binary size | +0.57% | +0.52% | +0.34% |
| wall-time | +0.13% | +0.34% | +0.60% |
| bootstrap | 625.7 | 625.6s | 629.016 |

**Comment by cjgillot** [comment]
With 1.5 only.
@bors try @rust-timer queue

**Comment by cjgillot** [comment]
@nnethercote completed table
| | double |  double+resume | 1.5 | 1.5 + resume |
| -- | -- | -- | -- | -- |
| instrs | -0.33% | -0.21% | -0.09% | -0.15% |
| cycles | +0.26% | +0.10% | +0.39% | +0.02% |
| max-rss | +0.42% | +0.72% | +0.42% | +0.66% |
| binary size | +0.57% | +0.52% | +0.39% | +0.34% |
| wall-time | +0.13% | +0.34% | +0.32% | +0.60% |
| bootstrap | 625.7 | 625.6s | 628.7 | 629.016 |

**Comment by nnethercote** [comment]
@cjgillot: Thanks for the additional measurements. The measurements are so varied that I don't feel like there's a clear winner, and the status quo is probably best. What do you think?

**Pull request closed without merging**
