### PR TITLE
Remove pretty printing of specific nodes in AST

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
The ability to print a specific item as identified by NodeId or path
seems not particularly useful, and certainly carries quite a bit of
complexity with it.

This is intended to simplify our CLI parsing a bit and remove a
non-uncomplicated piece of it; I largely did this to remove the
dependency on NodeId from librustc/session but it's not really
necessary to do so in this invasive a way. The alternative is
moving it to librustc_interface or driver, probably.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Nominating for compiler team -- I think if anyone at all actually wants this then we should just close. cc @rust-lang/compiler as such

**Comment by petrochenkov** [comment]
Introduced in https://github.com/rust-lang/rust/pull/16326.

**Comment by petrochenkov** [comment]
I agree with the removal, leaving as nominated for the compiler team triage meeting.

**Comment by Mark-Simulacrum** [comment]
We briefly discussed in compiler team and no one has raised objections since then -- I will r=petrochenkov tomorrow if no one objects.

**Pull request merged**
