### PR TITLE
move stage0.txt to toplevel directory

### PR DESCRIPTION
**Pull request by Keruspe**
This way all files needed by packagers now reside in toplevel

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Is there a particular advantage to doing this? I wasn't aware that packagers cared too much about this -- I personally prefer to have as few top-level files as possible. 

r? @alexcrichton

**Comment by kennytm** [comment]
@bors r- 

This failed `x86_64-gnu-distcheck` in https://github.com/rust-lang/rust/pull/56376#issuecomment-443250274, because the new `stage0.txt` is not in the source tarball.

**Comment by pietroalbini** [comment]
@bors r-

Caused the rollup to fail:

```
[00:11:10] configure: run `python /checkout/obj/build/tmp/distcheck/x.py --help`
[00:11:10] configure: 
[00:11:10] Traceback (most recent call last):
[00:11:10]   File "/checkout/obj/build/tmp/distcheck/src/bootstrap/bootstrap.py", line 870, in <module>
[00:11:10]     main()
[00:11:10]   File "/checkout/obj/build/tmp/distcheck/src/bootstrap/bootstrap.py", line 853, in main
[00:11:10]     bootstrap(help_triggered)
[00:11:10]   File "/checkout/obj/build/tmp/distcheck/src/bootstrap/bootstrap.py", line 810, in bootstrap
[00:11:10]     data = stage0_data(build.rust_root)
[00:11:10]   File "/checkout/obj/build/tmp/distcheck/src/bootstrap/bootstrap.py", line 158, in stage0_data
[00:11:10]     with open(nightlies, 'r') as nightlies:
[00:11:10] IOError: [Errno 2] No such file or directory: '/checkout/obj/build/tmp/distcheck/stage0.txt'
[00:11:10] Makefile:58: recipe for target 'check' failed
```

**Comment by Keruspe** [comment]
Well, it should have been a trivial change and it already made two rollups fail.

Definitely not worth it to keep trying, sorry about that guys!

**Pull request closed without merging**
