### PR TITLE
Make --cap-lints and related options leave crate hash alone

### LINKED ISSUE #87144: --cap-lints and related affect crate hash
I tried this code `t.rs`:

```rust
pub fn foo() {}
```

I'd expect the output of:
```
rustc --crate-type rlib --emit link t.rs
rustc --crate-type rlib --emit link --cap-lints=warn t.rs
rustc --crate-type rlib --emit link -Ddead-code t.rs
```
to all produce the same output from
```
rustc -Zls libt.rs
```
since this only affects the diagnostics and nothing about the crate itself (other than whether the crate is generated at all,
if an error is converted to a warning).

Instead, they all get different crate hashes:
(nothing)
```
Crate info:
name t
hash 5a3a7bb9cc8aaa16 stable_crate_id StableCrateId(18443930956397526271)
```
--cap-lints=warn:
```
Crate info:
name t
hash 99f5dd1f2478b80a stable_crate_id StableCrateId(18443930956397526271)
```
-Ddead-code:
```
Crate info:
name t
hash ffe4791362102371 stable_crate_id StableCrateId(18443930956397526271)
```
### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (3e1c75c6e 2021-07-13)
binary: rustc
commit-hash: 3e1c75c6e25a4db968066bd2ef2dabc7c504d7ca
commit-date: 2021-07-13
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by jsgf**
Closes: #87144

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
This looks good to me, but I don't feel confident approving.

**Comment by est31** [comment]
How eagerly are lints being checked? As in, if say lints are capped to allow, do the lints still get checked? Because if they don't, this might affect internal data structures, which in turn might affect details in the output.

**Comment by jyn514** [comment]
> How eagerly are lints being checked? As in, if say lints are capped to allow, do the lints still get checked?

Yes. https://github.com/rust-lang/rust/issues/74704

**Comment by jsgf** [comment]
@est31 You mean in the rlib, or in the incremental db?

**Comment by est31** [comment]
@jsgf both actually? It might query things at a different point in time, which can influence how things are stored in internal caches. IIRC the rlib format just dumps many such internal data structures, but I'm not 100% sure. There should be no *functional* difference, but the resulting rlib files might have different hashes. This question is better answered by someone who knows this better.

**Comment by jsgf** [comment]
@est31 I see - having the rlib bitwise dependent on warning flags would certainly be very surprising. It doesn't seem to be the case for the limit tests I tried, but obv that's not a proof. But either way, if the crates are semantically identical then they can have the same crate hash even if the files are different bitwise (for example, `-Zno-codegen` generates a very different crate contents, but it has the same SVH).

cc @bjorn3 @Aaron1011 who have context from the last PR I put up along these lines.

**Comment by est31** [comment]
Mhh the `-Zno-codegen` point is a very good one. Maybe this isn't a problem then after all :).

**Review by bjorn3 — APPROVED** [review]
If running lints causes the build output (except diagnostics) to change that would be a bug IMO. Lints should only look and not touch anything. If cache state would affect the build output, that would be a bug in the incremental compilation system that may be exposed even without this PR.

**Comment by michaelwoerister** [comment]
Thanks for the PR, @jsgf! I agree with @bjorn3's assessment.

@bors r+

**Pull request merged**
