### PR TITLE
Assoc item cleanup Part 2

### PR DESCRIPTION
**Pull request by matthewjasper**
- Remove `AssocItem` from `RegionVariableOrigin::AutoRef`
- Use the `associated_item_def_ids` query instead of the `associated_items` query when possible

The change to `ObligationCauseCode` from #90639 is omitted because it caused a perf regression.

r? @cjgillot

### CODE REVIEW

**Comment by matthewjasper** [comment]
Investigating locally, the change looks spurious. Looking at the history of these tests shows that a similar change happened when #89550 was merged and then later disappeared.

**Comment by cjgillot** [comment]
Ok, let's go ahead.
@bors r+

**Pull request merged**
