### PR TITLE
book: size and align in trait object vtables are used

### PR DESCRIPTION
**Pull request by cesarb**
The book currently claims that the `size` and `align` fields in the
trait object vtable are not used, but this is false. These two fields
are used by the stable `mem::size_of_val` and `mem::align_of_val`
functions.

See the `ty::TyDynamic` case of the `glue::size_and_align_of_dst`
function in librustc_trans, which is used to implement both intrinsics
in the unsized case.

r? @steveklabnik

### CODE REVIEW

**Comment by KodrAus** [comment]
Personally, I think it would be better to just remove that bit, and end the sentence at _alignment requirements_. I'm not sure how useful it is for a reader to know that the `size` and `align` fields are used by two specific functions in the standard library.

**Comment by steveklabnik** [comment]
I agree with @KodrAus here; would you mind just removing this bit please, @cesarb ? Thanks!

**Comment by cesarb** [comment]
@steveklabnik done.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thank you!

**Pull request merged**
