### PR TITLE
Remove tests/ui/impl-trait/in-trait/new-lowering-strategy in favor of using revisions on existing tests

### PR DESCRIPTION
**Pull request by spastorino**
r? @compiler-errors

This one again sits on top of existing approved PRs and it still needs to add revisions to tests in `tests/ui/impl-trait/in-trait` as it only does so for async in traits.

### CODE REVIEW

**Comment by compiler-errors** [comment]
r=me after rebased if ci passes.

**Comment by spastorino** [comment]
@compiler-errors added the `tests/ui/impl-trait/in-trait` part, I think this is really low risk but if you want to take a look ... some changes are due to tests being rustfmted which I think is fine to do :).

**Comment by spastorino** [comment]
@compiler-errors, this one is ready, rebased and ready for a final review.

**Pull request merged**
