### PR TITLE
Bubble opaque types into aggregates to produce more precise diagnostics on aggregate constructors

### PR DESCRIPTION
**Pull request by oli-obk**
Follow up to https://github.com/rust-lang/rust/pull/95767

This may be a bit overkill, but I'm exploring multiple paths to get the same better diagnostics

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
The diagnostic improvements in these UI tests here are great! :sparkles: 
love seeing tighter/more descriptive spans on errors.

**Comment by oli-obk** [comment]
I just realized that deaggregating before borrowck gives us an even better solution without having to make mir building more complex.

I guess i'll start looking into that again xD

**Comment by oli-obk** [comment]
Closing this PR, as it's definitely not my preferred route to go about this

**Pull request closed without merging**
