### PR TITLE
rename rustc_const_stable_intrinsic -> rustc_intrinsic_const_stable_indirect

### PR DESCRIPTION
**Pull request by RalfJung**
In https://github.com/rust-lang/rust/pull/120370 this name caused confusion as the author thought the intrinsic was stable. So let's try a different name...

If we can land this before the beta cutoff we can avoid needing `cfg(bootstrap)` for this. ;)
Cc @compiler-errors @saethlin

### CODE REVIEW

**Comment by saethlin** [comment]
I think this is clearer, but I'll give errs some time to chime in.

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
Ya this is fine.

r? compiler-errors @bors r+ rollup

**Comment by compiler-errors** [comment]
r=me when rebased

**Pull request merged**
