### PR TITLE
Avoid infinite loop in function arguments checking

### LINKED ISSUE #100478: rustc enters an infinite loop when doing cargo check
<!--
Thank you for filing a bug report! 🐛 Please provide a short summary of the bug,
along with any information you feel relevant to replicating the bug.
-->

Run cargo check on this code: https://github.com/cosven/tikv/commit/861b3e593ccd56cbace41f4bca1c73c432fa18bf, cargo check hangs. 
When I change the code to https://github.com/cosven/tikv/commit/e546489502db49a7a0d4b39352a9fbd5c1eaee76, the problem goes away and the check passes. 

The code has the following diff :)
![image](https://user-images.githubusercontent.com/4962134/184469184-cc4a9fb9-175b-4bbe-9741-7aa940fbbe07.png)

You can also reproduce this problem with following steps
```sh
git clone https://github.com/cosven/tikv.git
cd tikv/
git checkout rustc-deadloop-repro
# This commit can help repro the bug. 
# And rustc behaves well on the latest commit.
git checkout HEAD^
cargo check --workspace --all-targets
```

I expected to see:  cargo check should report a error, because the function call lacks a parameter.

Instead, this happened: cargo check hangs. The  CPU usage of the rustc process goes 100%.

### Meta
<!--
If you're using the stable version of the compiler, you should also check if the
bug also exists in the beta or nightly versions.
-->

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
binary: rustc
commit-hash: 0f4bcadb46006bc484dad85616b484f93879ca4e
commit-date: 2022-07-30
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

<!--
Include a backtrace in the code block by setting `RUST_BACKTRACE=1` in your
environment. E.g. `RUST_BACKTRACE=1 cargo build`.
-->
The pstack result is as follows, I think (not very sure) the problem may be related to this piece of code
https://github.com/rust-lang/rust/blob/46c59bbb79b3fa99950e2a7eaaeb161990561b8b/compiler/rustc_typeck/src/check/fn_ctxt/arg_matrix.rs#L224-L245
<details><summary>Backtrace</summary>
<p>


```
~ > pstack `pgrep rustc`                                                                                                                                                                                                              
Thread 2 (Thread 0x7f562277f700 (LWP 8210)):                                                                                                                                                                                          
#0  0x00007f562c2e001e in _RNvXNtNtCsjGak25GVoR2_5alloc3vec14spec_from_iterINtB4_3VecjEINtB2_12SpecFromIterjINtNtNtNtCs4Bj0LzfGV1R_4core4iter8adapters10filter_map9FilterMapINtNtB1m_9enumerate9EnumerateINtNtNtB1q_5slice4iter4IterNtNtNtNtCsWyxMbfqFoB_12rustc_typeck5check7fn_ctxt10arg_matrix13CompatibilityEENCNvMs_B3f_NtB3f_9ArgMatrix10find_issue0EE9from_iterB3l_ () from /root/.rustup/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/librustc_driver-c25a516c3d8f3eb8.so                                                                                                                                                                                                                   
#1  0x00007f562c20d532 in _RNvMs_NtNtNtCsWyxMbfqFoB_12rustc_typeck5check7fn_ctxt10arg_matrixNtB4_9ArgMatrix11find_errors () from /root/.rustup/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/librustc_driver-c25a516c3d8f3eb8.so                                                                                                                                                                                                                               
#2  0x00007f562c1bf1ca in _RNvMNtNtNtCsWyxMbfqFoB_12rustc_typeck5check7fn_ctxt6checksNtB4_6FnCtxt17report_arg_errors () from /root/.rustup/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/librustc_driver-c25a516c3d8f3eb8.so                                                                                                                                                                                                                                   
#3  0x00007f562a8f2e96 in _RNvMNtNtNtCsWyxMbfqFoB_12rustc_typeck5check7fn_ctxt6checksNtB4_6FnCtxt20check_argument_types () from /root/.rustup/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/librustc_driver-c25a516c3d8f3eb8.so                                                                                                                                                                                                                                
#4  0x00007f562a8f6d3f in _RNvMNtNtCsWyxMbfqFoB_12rustc_typeck5check4exprNtNtB4_7fn_ctxt6FnCtxt36check_expr_with_expectation_and_args.llvm.9954290265029759861 () from /root/.rustup/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/librustc_driver-c25a516c3d8f3eb8.so                                                                                                                                                                                         
#5  0x00007f562a8f593c in _RNvMNtNtCsWyxMbfqFoB_12rustc_typeck5check4exprNtNtB4_7fn_ctxt6FnCtxt36check_expr_with_expectation_and_args.llvm.9954290265029759861 () from /root/.rustup/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/librustc_driver-c25a516c3d8f3eb8.so                                                                                                                                                                                         
#6  0x00007f562a90af3f in _RNvMNtNtNtCsWyxMbfqFoB_12rustc_typeck5check7fn_ctxt6checksNtB4_6FnCtxt25check_block_with_expected () from /root/.rustup/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/librustc_driver-c25a516c3d8f3eb8.so                                                                                                                                                                                                                           
```

</p>
</details>


<!-- TRIAGEBOT_START -->

<!-- TRIAGEBOT_ASSIGN_START -->

<!-- TRIAGEBOT_ASSIGN_DATA_START$${"user":"chenyukang"}$$TRIAGEBOT_ASSIGN_DATA_END -->

<!-- TRIAGEBOT_ASSIGN_END -->
<!-- TRIAGEBOT_END -->

### LINKED ISSUE #101097: infinite loop during function argument check
I tried this code:
```rust
struct A;
struct B;
struct C;

fn f(
    a1: A,
    a2: A,
    b1: B,
    b2: B,
    c1: C,
    c2: C,
) {}

fn main() {
    f(
        C,
        C,
        A,
        A,
        B,
        B,
    );
}
```

I expected to see this happen: the compiler giving an error and showing a hint that order of the argument are not correct.

Instead, this happened: it stucks, waits forever.

### Meta

It happens on both stable and nightly.

Might be related to this: https://github.com/rust-lang/rust/issues/100478

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #100478
Fixes #101097

### CODE REVIEW

**Comment by chenyukang** [comment]
@jackh726 
My fix maybe not the best solution, feel free to teach me other solutions.

If you would like to have a debug, here is a log for you to inspect:
[check.log](https://github.com/rust-lang/rust/files/9331873/check.log)

**Comment by compiler-errors** [comment]
Thanks for finding this @chenyukang.

**Comment by chenyukang** [comment]
> Thanks for finding this @chenyukang.
> 
> Also remember to use "fixes" instead of "fixing" :)

Aha, seems it's my habit😁
I found we also can link issues with `Fixing`, but `fixing` seems not work.

**Comment by jackh726** [comment]
@chenyukang thanks for the PR. This indeed doesn't seem like the correct fix. I think this masks a different problem. There's an unstated assertion that if find_issue returns None, then we can eliminate at least some provided/expected args. The fact that this isn't the case seems like there is a discrepancy between `find_issue` and `eliminate_satisfied`.

Is the log that you provided for the test you added? The test seems to have 11 args and the log has 15/16?

**Comment by jackh726** [comment]
Just looking at the log and comparing it to the what would happen. There's actually a couple things we could change.

But let's look going backwards at "most straightforward" fix.
Last cycle:
```
x|  0  1  2  3  4  5  -  -  -  -  -  - 
0|  0  1  0  0  0  0 
1|  0  0  1  0  0  0 
2|  0  0  0  1  0  0 
3|  0  0  0  0  1  0 
4|  0  0  0  0  0  1 
5|  1  0  1  0  0  0
```
We should detect this as a permutation, I think. Or that column 1 is extra, followed by row 5 extra. This suggests there's a bug in our permutation detection.

Actually though, all the back towards the beginning, first call to `find_issue`:
```
x|  0  1  2  3  4  5  6  7  8  9  -  -  -  -  -  -  -  -  -  - 
0|  0  1  0  0  0  0  0  0  0  0 
1|  0  0  1  0  0  0  0  0  0  0 
2|  0  0  0  1  0  0  0  0  0  0 
3|  0  0  0  0  1  0  0  0  0  0 
4|  0  0  0  0  0  1  0  0  0  0 
5|  1  0  1  0  0  0  1  0  0  0 
6|  0  0  0  0  0  0  0  1  0  0 
7|  0  0  0  0  0  0  0  0  1  0 
8|  0  0  0  0  0  0  0  0  0  1 
```
It would be nice to identify that column 1 is "extra", rather than that row 9 is "missing".

**Comment by chenyukang** [comment]
> 1

Yes, the first iteration is not good.
I also tried this idea, my first try is fix this line https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/fn_ctxt/arg_matrix.rs#L136

```rust
 // If we eliminate the last row, any left-over inputs are considered missing
 if i >= mat.len() {
    return Some(Issue::Missing(i));   // Fix to Issue::Missing(0)
 }
```
By the way, in the comments it's `left-over inputs`, so your original intension is return `Missing(0)`?

But this fix will broke another testcase, for function call in testcase https://github.com/rust-lang/rust/blob/master/src/test/ui/argument-suggestions/missing_arguments.rs#L30, this fix print the wrong type for missing arguments:

```console
--- a/src/test/ui/argument-suggestions/missing_arguments.stderr
+++ b/src/test/ui/argument-suggestions/missing_arguments.stderr
@@ -210,10 +210,7 @@ error[E0061]: this function takes 3 arguments but 1 argument was supplied
   --> $DIR/missing_arguments.rs:30:3
    |
 LL |   three_diff(          1.0          );
-   |   ^^^^^^^^^^-------------------------
-   |             |          |
-   |             |          an argument of type `i32` is missing
-   |             an argument of type `&str` is missing
+   |   ^^^^^^^^^^------------------------- two arguments of type `i32` and `f32` are missing
    |
 note: function defined here
   --> $DIR/missing_arguments.rs:5:4
@@ -222,8 +219,8 @@ LL | fn three_diff(_a: i32, _b: f32, _c: &str) {}
    |    ^^^^^^^^^^ -------  -------  --------
 help: provide the arguments
    |
-LL |   three_diff(/* i32 */, 1.0, /* &str */);
-   |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+LL |   three_diff(/* i32 */, /* f32 */, /* &str */);
+   |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by chenyukang** [comment]
> @chenyukang thanks for the PR. This indeed doesn't seem like the correct fix. I think this masks a different problem. There's an unstated assertion that if find_issue returns None, then we can eliminate at least some provided/expected args. The fact that this isn't the case seems like there is a discrepancy between `find_issue` and `eliminate_satisfied`.
> 
> Is the log that you provided for the test you added? The test seems to have 11 args and the log has 15/16?

oh, sorry, I minilized the test case later, droping some first several extra parameters.

**Comment by chenyukang** [comment]
emm, got wrong meaning of on your comments, 
will have a try on this:
> It would be nice to identify that column 1 is "extra", rather than that row 9 is "missing".

**Comment by chenyukang** [comment]
@jackh726 
The root cause is `Arc::default()`, which could satisfy multiple arguments, and this will introduce we can not eliminate the `col 0` as Missing.


x|  0  1  2  3  4  5  6  7  8  9  -  -  -  -  -  -  -  -  -  - 
0|  0  1  0  0  0  0  0  0  0  0 
1|  0  0  1  0  0  0  0  0  0  0 
2|  0  0  0  1  0  0  0  0  0  0 
3|  0  0  0  0  1  0  0  0  0  0 
4|  0  0  0  0  0  1  0  0  0  0 
**5|  1  0  1  0  0  0  1  0  0  0** 
6|  0  0  0  0  0  0  0  1  0  0 
7|  0  0  0  0  0  0  0  0  1  0 
8|  0  0  0  0  0  0  0  0  0  1 

I worked out another solution, `cur_matched_idx` used to tracking the current matched indexes, when broke from the `for` loop, it's a suitable index to return.

By the way, I fixed some comments which didn't get right between the `arguments` and `input`. I found in code, `input` means the user's input and `arguments` means the function's expected parameter list.

This is not match with the comments in https://github.com/rust-lang/rust/commit/b6c87c555f3b664f558d137d5f7696a07488157e:
> It helps to understand this argument by paying special attention to terminology: "inputs" refers to the inputs being *expected* by the function, and "arguments" refers to what has been provided at the call site.

**Comment by chenyukang** [comment]
@jackh726 
#101097, there is another case will cause infinite loop in arguments checking, the algorithm didn't cover the case that there are multiple inputs compatiable with each other.

Debugging code FYI: https://github.com/chenyukang/rust/pull/1/files

```rust
struct A;
struct B;
struct C;
struct D;

fn f(
    a1: A,
    a2: A,
    b1: B,
    b2: B,
    c1: C,
    c2: C,
) {}

fn main() {
    f(C, C, A, A, B, B);
}
```

The debug log is:
```console
ai: [ExpectedIdx(0), ExpectedIdx(1), ExpectedIdx(2), ExpectedIdx(3), ExpectedIdx(4), ExpectedIdx(5)]
ii: [ProvidedIdx(0), ProvidedIdx(1), ProvidedIdx(2), ProvidedIdx(3), ProvidedIdx(4), ProvidedIdx(5)]
================== find_issue: ==================
x|  0  1  2  3  4  5
-|  -  -  -  -  -  -
0|  0  0  0  0  1  1
1|  0  0  0  0  1  1
2|  1  1  0  0  0  0
3|  1  1  0  0  0  0
4|  0  0  1  1  0  0
5|  0  0  1  1  0  0
i: 0, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 1, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 2, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 3, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 4, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 5, is_input: true, is_arg: true, useless: false, unsatisfiable: false
loop i: 0 j: 0 compat: [4, 5]
permutation_found: false
now permutation: [Some(None), None, None, None, None, None]
loop i: 1 j: 1 compat: [4, 5]
permutation_found: false
now permutation: [Some(None), Some(None), None, None, None, None]
loop i: 2 j: 2 compat: [0, 1]
permutation_found: false
now permutation: [Some(None), Some(None), Some(None), None, None, None]
loop i: 3 j: 3 compat: [0, 1]
permutation_found: false
now permutation: [Some(None), Some(None), Some(None), Some(None), None, None]
loop i: 4 j: 4 compat: [2, 3]
permutation_found: false
now permutation: [Some(None), Some(None), Some(None), Some(None), Some(None), None]
loop i: 5 j: 5 compat: [2, 3]
permutation_found: false
now permutation: [Some(None), Some(None), Some(None), Some(None), Some(None), Some(None)]
res: None
thread 'rustc' panicked at 'didn't eliminated any indice in this round', compiler/rustc_typeck/src/check/fn_ctxt/arg_matrix.rs:412:21
```

**Comment by chenyukang** [comment]
https://github.com/rust-lang/rust/pull/100502/commits/b9bdc0196a0d6645f70ea51c935f9975f8aadcda 
will fix this issue.

**Comment by chenyukang** [comment]
Another similar case is:

```rust
struct A;
struct B;
struct C;
struct D;

fn f(
    a1: A,
    a2: A,
    b1: B,
    b2: B,
    c1: C,
    c2: C,
) {}

fn main() {
    f(C, A, A, A, B, B, C);
}
```

with log:

```console
ai: [ExpectedIdx(0), ExpectedIdx(2), ExpectedIdx(3), ExpectedIdx(4), ExpectedIdx(5)]
ii: [ProvidedIdx(0), ProvidedIdx(2), ProvidedIdx(3), ProvidedIdx(4), ProvidedIdx(5), ProvidedIdx(6)]
================== find_issue: ==================
x|  0  1  2  3  4
-|  -  -  -  -  -
0|  0  0  0  1  1
1|  1  0  0  0  0
2|  1  0  0  0  0
3|  0  1  1  0  0
4|  0  1  1  0  0
5|  0  0  0  1  1
i: 0, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 1, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 2, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 3, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 4, is_input: true, is_arg: true, useless: false, unsatisfiable: false
i: 5, is_input: true, is_arg: false, useless: false, unsatisfiable: true
loop i: 0 j: 0 compat: [3, 4]
permutation_found: false
now permutation: [Some(None), None, None, None, None, None]
loop i: 1 j: 1 compat: [0]
loop i: 1 j: 0 compat: [3, 4]
permutation_found: false
now permutation: [Some(None), None, None, None, None, None]
now permutation: [Some(None), Some(None), None, None, None, None]
loop i: 2 j: 2 compat: [0]
loop i: 2 j: 0 compat: [3, 4]
permutation_found: false
now permutation: [Some(None), Some(None), None, None, None, None]
now permutation: [Some(None), Some(None), Some(None), None, None, None]
loop i: 3 j: 3 compat: [1, 2]
permutation_found: false
now permutation: [Some(None), Some(None), Some(None), Some(None), None, None]
loop i: 4 j: 4 compat: [1, 2]
permutation_found: false
now permutation: [Some(None), Some(None), Some(None), Some(None), Some(None), None]
loop i: 5 j: 5 compat: [3, 4]
permutation_found: false
now permutation: [Some(None), Some(None), Some(None), Some(None), Some(None), Some(None)]
res: None
thread 'rustc' panicked at 'didn't eliminated any indice in this round', compiler/rustc_typeck/src/check/fn_ctxt/arg_matrix.rs:412:21
```

**Pull request merged**
