### PR TITLE
[perf test] Disable rustc lints

### PR DESCRIPTION
**Pull request by Kobzol**
This is just an experiment to see what is the upper bound cost of `rustc` lints. I don't expect any gigantic gains from disabling them, but let's see.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
I spent some time looking into this today. Things to note:

- `-Ztime-passes -Zno-interleave-lints` is a good combination. It prints out the expensive lints.

- The `UnusedBrokenConst` lint is the main culprit here. If you disable just that you still get something like 60% of the wins. I don't understand how this lint works, though clearly it's triggering lots of CTFE. If I disable it I get lots of `ui` test failures, but this is only because the `ui` tests use `--emit metadata`. If I just do a normal compilation of the failing `ui` test source files I get the same output as normal.

- This PR understates the cost of lints. It comments out all the `check_*` functions, but each lint still does a no-check traversal of the AST/HIR, which has a non-trivial cost. I tried a variant that instead stops all the lint traversals from happening, and the savings were about 1.25x better than in this PR.

The obvious follow-up questions.

- Can `UnusedBrokenConst` be made cheaper? It seems incredibly expensive for what it's doing.

- Can the general AST/HIR traversal cost be reduced? It seems suboptimal to have dozens of lints, each of which fully traverses the AST/HIR but only checks a fraction of the AST/HIR nodes. Can we invert the iteration, i.e. traverse the AST/HIR once, and only iterate over the relevant lints for each node?

**Comment by RalfJung** [comment]
`UnusedBrokenConst` is a red herring. What that 'lint' does is go over all consts in the crate and trigger their evaluation. This is needed, we must report errors in constants no matter whether they are used or not:
- for `cargo check`, AFAIK that is the only way constants are evaluated at all -- if we skip this step, we are just no emitting diagnostics that will then show up later during `cargo build`
- for `cargo build`, this only affects constants that are unused, but also for those we stably promise that they are evaluated and will lead to a hard error, which is crucial for 'static assertions'.

**Comment by Dylan-DPC** [comment]
Closing this as inactive

**Pull request closed without merging**
