### PR TITLE
Update the book install instructions for nightly

### PR DESCRIPTION
**Pull request by mdinger**
I wanted to use bullet points for a two item list but couldn't embed a code block in a bullet point.

It may be considered undesirable to put the nightly here but I thought it should be added because the two line instructions aren't on the [rust-lang.org](http://www.rust-lang.org/install.html) page. Maybe they should be there instead...

### CODE REVIEW

**Comment by steveklabnik** [comment]
So, I like this, but, now that we have the unstable chapter of the book, I think this should just talk about beta, and, in the introduction of the unstable part, we should talk about installing nightly. Whatcha think?

**Comment by mdinger** [comment]
At first, I was slightly opposed but I'm warming to the idea. Maybe put a note in the stable section like "if you're looking for nightly instructions, go here". That note could possibly be removed in the future. I think [rust-lang.org/install.html](http://www.rust-lang.org/install.html) should probably link to each install section

A decent alternative would be tabs like in the [markdown](https://guides.github.com/features/mastering-markdown/#examples) page that defaults to beta/stable. I don't know if that's supported by rustbook though.

**Comment by mdinger** [comment]
Or put tabbed code versions on the install page directly: single line vs multi-line. That seems like a decent idea.

**Comment by steveklabnik** [comment]
I would, at this stage, really prefer to just keep it simple. :)

**Comment by mdinger** [comment]
Okay. I don't think I'll get to stubbing out a new unstable install page today to fix this so i'll close for now. See when I get back to it.

**Pull request closed without merging**
