### PR TITLE
Rebase LLVM to 8.0.0 final

### PR DESCRIPTION
**Pull request by cuviper**
r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Want to update src/rustllvm/llvm-rebuild-trigger while you're at it?

Feel free to r=me with that in

**Comment by cuviper** [comment]
Oops, updated! Was this not an issue on prior LLVM updates since then?

@bors r=alexcrichton

**Comment by nikic** [comment]
What are the plans regarding LLVM updates from this point on? Will we stay on the LLVM 8 branch or go back to master now that the release is out?

**Comment by alexcrichton** [comment]
@cuviper 

> Was this not an issue on prior LLVM updates since then?

It's never an issue for CI because we always build from scratch and let sccache cache. It's in theory always an issue for local users though because we don't clear out the cached llvm build directory unless this file changes.

Now that being said it's probably pretty trivial for us to clear out the build directory somewhat automatically if the llvm git commit changes or something like that. But for now it's what we have!


@nikic 

> What are the plans regarding LLVM updates from this point on? Will we stay on the LLVM 8 branch or go back to master now that the release is out?

I think we'll probably stick to the defacto policy we've had for awhile that for small features and updates we can cherry-pick to our own branch but if a major feature is needed we can upgrade the submodule.

**Pull request merged**
