### PR TITLE
Add missing error code for private method

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by kennytm** [comment]
Tidy failed, trailing whitespace and duplicated error code.

```
[00:04:02] tidy error: /checkout/src/test/compile-fail/E0623.rs:13: trailing whitespace
[00:04:03] tidy error: /checkout/src/librustc_typeck/diagnostics.rs:4655: trailing whitespace
[00:04:03] tidy error: /checkout/src/librustc_typeck/diagnostics.rs:4672: trailing whitespace
[00:04:03] tidy error: /checkout/src/librustc_typeck/diagnostics.rs:4676: trailing whitespace
[00:04:03] tidy error: /checkout/src/librustc_typeck/diagnostics.rs:4692: trailing whitespace
[00:04:03] tidy error: duplicate error code: 623
[00:04:03] tidy error: /checkout/src/librustc/diagnostics.rs:2028:     E0623, // lifetime mismatch where both parameters are anonymous regions
[00:04:03] tidy error: /checkout/src/librustc_typeck/diagnostics.rs:4647: E0623: r##"
[00:04:03] some tidy checks failed
```

**Comment by eddyb** [comment]
r=me with fixed tidy

**Comment by kennytm** [comment]
@bors retry — maybe #38618.

`dist-i586-gnu-i686-musl` failed with unknown error 😕 

```
[01:16:22] running 672 tests
[01:16:22]      Running build/x86_64-unknown-linux-gnu/stage2-std/i686-unknown-linux-musl/release/deps/coretests-d52ea69166ccf524
...
[01:16:22] error: An unknown error occurred
[01:16:22] 
[01:16:22] To learn more, run the command again with --verbose.
[01:16:22] 
[01:16:22] 
[01:16:22] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-j" "4" "--target" "i686-unknown-linux-musl" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "std:0.0.0" "-p" "rand:0.0.0" "-p" "alloc:0.0.0" "-p" "compiler_builtins:0.0.0" "-p" "core:0.0.0" "-p" "collections:0.0.0" "-p" "unwind:0.0.0" "-p" "libc:0.0.0" "-p" "std_unicode:0.0.0" "-p" "panic_abort:0.0.0" "-p" "alloc_system:0.0.0" "--"
```

**Pull request merged**
