### PR TITLE
Format Rust code

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Posting this for review; will be rebasing and attempting to merge this weekend.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
In some short discussion we realized that this would make backporting a pain so we'll be landing this closer to the release, somewhere around the 15th.

r? @pietroalbini

**Comment by Mark-Simulacrum** [comment]
`__CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS=nightly CFG_RELEASE_CHANNEL=nightly cargo +stable fmt`

This was the command used to produce these results.

**Comment by mark-i-m** [comment]
Oh, I just noticed it was already done! :tada:

**Comment by Centril** [comment]
@Mark-Simulacrum 

> In some short discussion we realized that this would make backporting a pain so we'll be landing this closer to the release, somewhere around the 15th.

I'd rather do it either *very* soon or postpone this until after master=>beta promotion happens as there are some stabilization PRs that, if everything goes well, will be FCP-complete right around 13-15th; I'd prefer not to tree-close around those dates.

**Comment by mark-i-m** [comment]
Personally, I would hope that there are no actual changes in this PR. I would rather turn on tidy in another PR and fix any formatting that changed since this PR.

**Comment by varkor** [comment]
> Personally, I would hope that there are no actual changes in this PR.

They definitely ought to be in separate commits, and I'd probably be inclined to go for separate PRs too.

I think we'd benefit from turning on `tidy` *first* (which will only lint changed files anyway) and then formatting afterwards, so we don't have to make more than one formatting PR.

**Comment by mark-i-m** [comment]
Checking only changed files is a good idea, but I didn’t know we could do that.

**Comment by mark-i-m** [comment]
Is the current plan to revive this near the end of this week?

**Comment by Mark-Simulacrum** [comment]
I've decided to table this for a release cycle until I get a chance to sit down -- maybe at the all hands -- with a few of the stake holders and hash out exactly what we want from it: options to rustfmt, etc.

I'm going to close this for now to avoid cluttering the queue.

**Pull request closed without merging**
