### PR TITLE
Fix macro call site spans

### PR DESCRIPTION
**Pull request by jseyfried**
Fix macro call site spans.
r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
LGTM

@DanielJCampbell does this break any of your macro tracing stuff?

**Comment by DanielJCampbell** [comment]
Not that I can see. No failed tests means it passed the tests I had for my stuff, which is a good sign, and I didn't use the original_span method for anything.

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/33844

**Comment by jseyfried** [comment]
Rebased.

**Comment by alexcrichton** [comment]
(that error looks like it may be legit)

**Comment by jseyfried** [comment]
I'm having trouble reproducing the error, but I think the above commit will fix it -- r? @nrc

**Comment by jseyfried** [comment]
@michaelwoerister 
The incorrect call site spans that this PR fixes cause [very confusing diagnostics](https://play.rust-lang.org/?gist=f22c37018222129d250f2008a955d33e&version=nightly&backtrace=0).

Since debuginfo for macros is already [known](https://github.com/rust-lang/rust/issues/9232) [to](https://github.com/rust-lang/rust/issues/18285) [be](https://github.com/rust-lang/rust/issues/20292) [buggy](https://github.com/rust-lang/rust/issues/33146), perhaps we could just land this with the workaround in the last commit?

Another option would be to always use call site spans for debuginfo as described in [this comment](https://github.com/rust-lang/rust/issues/9232#issuecomment-193662409). While I believe this would fix the bugs I linked and allow this PR to land without the workaround, it would make it impossible to `break` on a line in a macro definition (in particular, we would have to remove [this test](https://github.com/rust-lang/rust/blob/master/src/test/debuginfo/lexical-scope-with-macro.rs)).

**Comment by michaelwoerister** [comment]
Oh, I forgot about this PR. I'll take a look at it tomorrow.

**Comment by michaelwoerister** [comment]
OK, so I won't get into debuginfo vs macros here -- I'd need to put a lot more thought into that and assess the current situation. From what I can see here, things don't get considerably worse, right?

As far as the test case goes: There shouldn't even be a macro invocation here -- in fact, it had been a regular function call before someone changed it to account for the called function being moved, as far as I can tell. We just need something that allows us to reliably set a breakpoint at. I'd suggest just following the pattern of many other debuginfo test cases: Add an empty function `fn zzz() { () }` and call it wherever a breakpoint is needed. That should allow the `#break` directive to work reliably.

**Comment by jseyfried** [comment]
> From what I can see here, things don't get considerably worse, right?

Right. I believe things can only get worse when there is a macro-expanded procedural macro invocation (in this case, `format!("")`). If `format!("")` were invoked directly or if `format` were somehow defined with `macro_rules!`, the test would pass after this PR or would already be broken (respectively).

> I'd suggest just following the pattern of many other debuginfo test cases: Add an empty function `fn zzz() { () }` and call it wherever a breakpoint is needed.

Makes sense, done.

**Comment by michaelwoerister** [comment]
@bors r=nrc

Excellent `:)`

**Pull request merged**
