### PR TITLE
Rollup of 14 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
Successful merges:

 - #49525 (Use sort_by_cached_key where appropriate)
 - #49575 (Stabilize `Option::filter`.)
 - #49614 (in which the non-shorthand patterns lint keeps its own counsel in macros)
 - #49665 (Small nits to make couple of tests pass on mips targets.)
 - #49781 (add regression test for #16223 (NLL): use of collaterally moved value)
 - #49795 (Properly look for uninhabitedness of variants in niche-filling check)
 - #49809 (Stop emitting color codes on TERM=dumb)
 - #49856 (Do not uppercase-lint #[no_mangle] statics)
 - #49863 (fixed typo)
 - #49857 (Fix "fp" target feature for AArch64)
 - #49849 (Add --enable-debug flag to musl CI build script)
 - #49734 (proc_macro: Generalize `FromIterator` impl)
 - #49730 (Fix ICE with impl Trait)
 - #48270 (Replace `structurally_resolved_type` in casts check.)

Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+

Removed #49844 (removed by request)

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/365080234) ([raw log](https://api.travis-ci.org/v3/job/365080234/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613961/613961), completed with 4890 local objects.
---
[00:00:51] configure: rust.quiet-tests     := True
---
[00:44:06] ..............................................................................i.....................
[00:44:12] .....................i..............................................................................
---
[00:44:53] i...........................................................................i.......................
---
[00:45:48] .............................................i......................................................
---
[00:49:34] .............................i......................................................................
[00:49:48] ..............................................................i.....................................
[00:50:03] ...............................................i....................................................
[00:50:23] ....................................................................................................
[00:50:44] ....................................................................................................
[00:51:05] ....................................................................................................
[00:51:29] ....i...............................................................................................
[00:51:58] i.......................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:52:04] ............
[00:52:33] ....................................................................................................
[00:53:07] ..................................................................ii................................
[00:53:54] .............................i....................................................i.ii........test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:53:57] ......
[00:54:35] ..........................................................................................iiiiiii...
---
[00:56:46] ...................i............................................................ii.iii..............
[00:56:53] ....................................................................................................
[00:57:01] .........i..............................i...........................................................
[00:57:08] ....................................................................................................
[00:57:15] .....................i..............................................................................
[00:57:23] ....................................................................................................
[00:57:32] ....................................................................................................
[00:57:42] ......................................F.............................................................
[00:57:53] ....................................................................................................
[00:58:06] ....................................................................................................
[00:58:13] ..............i.....................................................................................
[00:58:23] ..................i..ii.............................................................................
[00:58:32] ....................................................................................................
[00:58:42] ....................................................................................................
[00:58:51] .....................................................................................i..............
[00:59:01] ...............................i....................................................................
---
[00:59:35] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/issue-36638.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-36638.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "continue-parse-after-error" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-36638.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:59:35] {"message":"expected identifier, found keyword `Self`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/compile-fail/issue-36638.rs","byte_start":527,"byte_end":531,"line_start":13,"line_end":13,"column_start":12,"column_end":16,"is_primary":true,"text":[{"text":"struct Foo<Self>(Self);","highlight_start":12,"highlight_end":16}],"label":"expected identifier, found keyword","suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error: expected identifier, found keyword `Self`\n  --> /checkout/src/test/compile-fail/issue-36638.rs:13:12\n   |\nLL | struct Foo<Self>(Self);\n   |            ^^^^ expected identifier, found keyword\n\n"}
[00:59:35] {"message":"expected identifier, found keyword `Self`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/compile-fail/issue-36638.rs","byte_start":604,"byte_end":608,"line_start":16,"line_end":16,"column_start":11,"column_end":15,"is_primary":true,"text":[{"text":"trait Bar<Self> {}","highlight_start":11,"highlight_end":15}],"label":"expected identifier, found keyword","suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error: expected identifier, found keyword `Self`\n  --> /checkout/src/test/compile-fail/issue-36638.rs:16:11\n   |\nLL | trait Bar<Self> {}\n   |           ^^^^ expected identifier, found keyword\n\n"}
[00:59:35] thread 'main' panicked at 'assertion failed: `(left == right)`
[00:59:35]   left: `1`,
[00:59:35]  right: `0`', librustc/ty/sty.rs:889:13
[00:59:35] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:59:35] {"message":"aborting due to 2 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 2 previous errors\n\n"}
[00:59:35]
[00:59:35] error: internal compiler error: unexpected panic
[00:59:35]
[00:59:35] note: the compiler unexpectedly panicked. this is a bug.
[00:59:35]
[00:59:35] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:59:35]
[00:59:35] note: rustc 1.27.0-dev running on x86_64-unknown-linux-gnu
[00:59:35]
[00:59:35] note: compiler flags: -Z ui-testing -Z miri -Z unstable-options -Z continue-parse-after-error -C prefer-dynamic -C rpath
[00:59:35]
[00:59:35]
[00:59:35] ------------------------------------------
[00:59:35]
[00:59:35] thread '[compile-fail] compile-fail/issue-36638.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2919:9
---
[00:59:35] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:59:35] expected success, got: exit code: 101
[00:59:35]
[00:59:35]
[00:59:35] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:59:35] Build completed unsuccessfully in 0:16:40
[00:59:35] Makefile:58: recipe for target 'check' failed
[00:59:35] make: *** [check] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:1586dda7:start=1523451573044696002,finish=1523451573058461292,duration=13765290
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:040d9496
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:040d9496:start=1523451573068583752,finish=1523451573077137127,duration=8553375
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0603c1c4
$ dmesg | grep -i kill
[   11.782639] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/365084324) ([raw log](https://api.travis-ci.org/v3/job/365084324/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (613948/613948), completed with 4891 local objects.
---
[00:00:44] configure: rust.quiet-tests     := True
---
[00:42:18] ..............................................................................i.....................
[00:42:23] .....................i..............................................................................
---
[00:43:04] i...........................................................................i.......................
---
[00:43:57] .............................................i......................................................
---
[00:47:41] .............................i......................................................................
[00:47:55] ..............................................................i.....................................
[00:48:10] ...............................................i....................................................
[00:48:29] ....................................................................................................
[00:48:51] ....................................................................................................
[00:49:11] ....................................................................................................
[00:49:36] ....i...............................................................................................
[00:50:04] i......................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:50:12] .............
[00:50:41] ....................................................................................................
[00:51:13] ..................................................................ii................................
[00:52:02] .............................i....................................................i.ii..........test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:52:03] ....
[00:52:42] ..........................................................................................iiiiiii...
---
[00:54:52] ...................i............................................................ii.iii..............
[00:55:00] ....................................................................................................
[00:55:07] .........i..............................i...........................................................
[00:55:15] ....................................................................................................
[00:55:21] .....................i..............................................................................
[00:55:29] ....................................................................................................
[00:55:39] ....................................................................................................
[00:55:49] ......................................F.............................................................
[00:55:59] ....................................................................................................
[00:56:12] ....................................................................................................
[00:56:19] ..............i.....................................................................................
[00:56:29] ..................i..ii.............................................................................
[00:56:38] ....................................................................................................
[00:56:48] ....................................................................................................
[00:56:57] .....................................................................................i..............
[00:57:08] ...............................i....................................................................
---
[00:57:42] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/issue-36638.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-36638.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "continue-parse-after-error" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-36638.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:57:42] {"message":"expected identifier, found keyword `Self`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/compile-fail/issue-36638.rs","byte_start":527,"byte_end":531,"line_start":13,"line_end":13,"column_start":12,"column_end":16,"is_primary":true,"text":[{"text":"struct Foo<Self>(Self);","highlight_start":12,"highlight_end":16}],"label":"expected identifier, found keyword","suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error: expected identifier, found keyword `Self`\n  --> /checkout/src/test/compile-fail/issue-36638.rs:13:12\n   |\nLL | struct Foo<Self>(Self);\n   |            ^^^^ expected identifier, found keyword\n\n"}
[00:57:42] {"message":"expected identifier, found keyword `Self`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/compile-fail/issue-36638.rs","byte_start":604,"byte_end":608,"line_start":16,"line_end":16,"column_start":11,"column_end":15,"is_primary":true,"text":[{"text":"trait Bar<Self> {}","highlight_start":11,"highlight_end":15}],"label":"expected identifier, found keyword","suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error: expected identifier, found keyword `Self`\n  --> /checkout/src/test/compile-fail/issue-36638.rs:16:11\n   |\nLL | trait Bar<Self> {}\n   |           ^^^^ expected identifier, found keyword\n\n"}
[00:57:42] thread 'main' panicked at 'assertion failed: `(left == right)`
[00:57:42]   left: `1`,
[00:57:42]  right: `0`', librustc/ty/sty.rs:889:13
[00:57:42] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:57:42] {"message":"aborting due to 2 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 2 previous errors\n\n"}
[00:57:42]
[00:57:42] error: internal compiler error: unexpected panic
[00:57:42]
[00:57:42] note: the compiler unexpectedly panicked. this is a bug.
[00:57:42]
[00:57:42] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:57:42]
[00:57:42] note: rustc 1.27.0-dev running on x86_64-unknown-linux-gnu
[00:57:42]
[00:57:42] note: compiler flags: -Z ui-testing -Z miri -Z unstable-options -Z continue-parse-after-error -C prefer-dynamic -C rpath
[00:57:42]
[00:57:42]
[00:57:42] ------------------------------------------
[00:57:42]
[00:57:42] thread '[compile-fail] compile-fail/issue-36638.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2919:9
---
[00:57:42] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:57:42] expected success, got: exit code: 101
[00:57:42]
[00:57:42]
[00:57:42] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:57:42] Build completed unsuccessfully in 0:16:35
[00:57:42] Makefile:58: recipe for target 'check' failed
[00:57:42] make: *** [check] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:14ba5bfc:start=1523452099276592610,finish=1523452099283961528,duration=7368918
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:00a8ba8c
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:00a8ba8c:start=1523452099289720059,finish=1523452099296175339,duration=6455280
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0f4b8093
$ dmesg | grep -i kill
[   11.302674] init: failsafe main process (1095) killed by TERM signal
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by kennytm** [comment]
@bors r+

Removed #49826. I suspect this caused https://github.com/rust-lang/rust/pull/49875#issuecomment-380442779?

**Comment by kennytm** [comment]
@bors r+

Removed #49826. I suspect this caused https://github.com/rust-lang/rust/pull/49875#issuecomment-380442779?

**Comment by kennytm** [comment]
@bors p=0

(Rescheduling)

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/365231397) ([raw log](https://api.travis-ci.org/v3/job/365231397/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:27:17] thread '<unnamed>' panicked at 'isize::MAX + 1 should trigger an OOM!', libstd/collections/hash/map.rs:3640:22
---
[01:27:30] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-musl" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "std" "--"
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:02ede5a2:start=1523473051582066794,finish=1523473051595728633,duration=13661839
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:04ee99b9
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:04ee99b9:start=1523473051602017630,finish=1523473051608247498,duration=6229868
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:1029a65e
$ dmesg | grep -i kill
[   10.878622] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/365231397) ([raw log](https://api.travis-ci.org/v3/job/365231397/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:27:17] thread '<unnamed>' panicked at 'isize::MAX + 1 should trigger an OOM!', libstd/collections/hash/map.rs:3640:22
---
[01:27:30] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-musl" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "std" "--"
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:02ede5a2:start=1523473051582066794,finish=1523473051595728633,duration=13661839
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:04ee99b9
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:04ee99b9:start=1523473051602017630,finish=1523473051608247498,duration=6229868
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:1029a65e
$ dmesg | grep -i kill
[   10.878622] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

**Comment by kennytm** [comment]
@bors r+

Removed #49850 (This is the only PR which touches allocation stuff).
Added #49849.

**Comment by kennytm** [comment]
@bors r+

Removed #49698 (expecting Cargo.lock conflict).
Added #49734, #49730, #48270

**Pull request merged**
