### PR TITLE
Add PartialEq<char> for proc_macro::Punct

### PR DESCRIPTION
**Pull request by dtolnay**
`punct.as_char() == '░'` is pervasive when parsing anything involving punct. I think `punct == '░'` is sufficiently unambiguous that it makes sense to provide the impl.

https://github.com/rust-lang/rust/blob/1899c489d4c30b2640d30b77ac04f0a548834d81/library/proc_macro/src/quote.rs#L79
https://github.com/rust-lang/rust/blob/1899c489d4c30b2640d30b77ac04f0a548834d81/library/proc_macro/src/quote.rs#L83
https://github.com/rust-lang/rust/blob/1899c489d4c30b2640d30b77ac04f0a548834d81/src/test/ui/suggestions/auxiliary/issue-61963.rs#L26
https://github.com/rust-lang/rust/blob/1899c489d4c30b2640d30b77ac04f0a548834d81/src/test/ui/proc-macro/auxiliary/three-equals.rs#L23

### CODE REVIEW

**Comment by dtolnay** [comment]
@rfcbot fcp merge

**Comment by pthariensflame** [comment]
`relnotes` needed?

Also, doesn't this violate symmetry of `PartialEq` without a similar-but-flipped `impl`?

**Comment by petrochenkov** [comment]
Marked with relnotes.

>Also, doesn't this violate symmetry of `PartialEq` without a similar-but-flipped `impl`?

I assumed coherence wouldn't allow to add such a symmetric impl, but it's actually allowed.

@dtolnay or @pthariensflame, could you make a PR adding `impl PartialEq<Punct> for char` as well?
Asymmetric `PartialEq` (at compile time, not runtime) doesn't seem like a big deal to me, but looks like the documentation requires it - https://doc.rust-lang.org/stable/std/cmp/trait.PartialEq.html (the requirement was added in #20065).

**Comment by pthariensflame** [comment]
I'll make one today.

**Pull request merged**
