### PR TITLE
Make a module out of debuginfo

### LINKED ISSUE #20780: Split debuginfo into its own module
trans/debuginfo.rs is huge. It would be good to split it out into a module and split it up into a few files.

cc @michaelwoerister

### PR DESCRIPTION
**Pull request by nrc**
Closes #20780

r? @michaelwoerister 

I'm sure this could be done better with deeper knowledge of debuginfo, but this seems like a good start.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Cool! I'll take a look at this over the weekend.

**Comment by michaelwoerister** [comment]
I've taken a look at this and overall I think this is the right direction to go in. However, I would factor some things a little differently:

Metadata creation is the most complicated thing in this module. Especially for type metadata many things interconnect and coupling is rather tight. However, only the `type_metadata()` function really needs to be exposed to the rest of the debuginfo module, while the specialized implementations called by `type_metadata()` are more or less implementation details, including the `TypeMap` and handling of recursive types. This PR splits these things up into various files though (`mod.rs`, `adt.rs`, and `metadata.rs`). I would merge `adt.rs` into `metadata.rs` (maybe make `adt.rs` a private sub-module of `metadata.rs`) and move the `TypeMap`, `UniqueTypeId`, `RecursiveTypeDescription`, and `create_and_register_recursive_type_forward_declaration` into this new `metadata.rs` file. This way, we should be able to keep most things in `metadata.rs` private. Only `type_metadata()`, `file_metadata()`, `scope_metadata()`, and `compile_unit_metadata()` would be public.

Some nits:
- I think `create.rs` doesn't quite carry its weight. I'd get rid of it and move `is_node_local_to_unit()` and `create_DIArray()` to `utils.rs`, and `declare_local()` to `mod.rs`.
- I'd rename `types.rs` to `naming.rs` or `type_naming.rs` or something to that effect because it only deals with naming.
- I'd move `create_scope_map()` from `utils.rs` to its own file since this is a rather important part of creating debuginfo (although it is just one big function).
- Source location handling could also be moved from `mod.rs` into its own module but that's not a high priority.

Apart from the above, this looks good to me. I like that the GDB stuff get's its own module and that `mod.rs` gets condensed down to the few things that are actually needed by other parts of the compiler.

**Comment by nrc** [comment]
@michaelwoerister ping for r? All changes made as suggested.

**Comment by michaelwoerister** [comment]
Thanks!

**Pull request merged**
