### PR TITLE
Remove `nll` from `rust_2018_preview`

### PR DESCRIPTION
**Pull request by alexcrichton**
NLL isn't quite ready yet so gonna hold off on inserting it into the preview.

### CODE REVIEW

**Comment by aturon** [comment]
@bors: p=1 

prioritizing for edition preview

**Comment by pietroalbini** [comment]
> prioritizing for edition preview

Should this land on 1.27 or 1.28?

**Comment by alexcrichton** [comment]
@pietroalbini nah the edition preview is nightly-only, so no need to backport

**Comment by nblumhardt** [comment]
Just to clarify, does this mean that NLL is in doubt for Rust 2018? We're working on something we'd like to ship against stable later this year, and we're finding it hard to imagine living without NLL :-)

**Comment by aturon** [comment]
@nblumhardt No, not at all! We were sprinting to get the very first preview of the Edition working, and NLL wasn't quite ready at that point. But it will **definitely** be in Rust 2018.

**Comment by nblumhardt** [comment]
Phew! :sweat_smile: thanks @aturon :+1:

**Pull request merged**
