### PR TITLE
Make `TypedArena::alloc_from_iter` like `DroplessArena::alloc_from_iter`.

### PR DESCRIPTION
**Pull request by nnethercote**
Although they do similar things, they are currently implemented differently, for no particular reason.

r? @cjgillot

### CODE REVIEW

**Comment by nnethercote** [comment]
I'm not expecting any performance changes.

@bors try @rust-timer queue

cc @Zoxc

**Comment by Zoxc** [comment]
They can't use the same code as the allocated slice is not initialized when `Iterator::next` is called, which means `TypedArena` could drop uninitialized memory if  `Iterator::next` unwinds. `alloc_raw_slice` should probably be unsafe to make that more clear.

You could look into reverting https://github.com/rust-lang/rust/pull/78569 if you want this to be cleaner.

**Comment by nnethercote** [comment]
> They can't use the same code as the allocated slice is not initialized when `Iterator::next` is called, which means `TypedArena` could drop uninitialized memory if `Iterator::next` unwinds.

Are you sure? `ArenaChunk::storage` is a `NonNull<[MaybeUninit<T>]>`. AIUI, if a panic occurs during the iteration the already-written elements won't be dropped, which is a memory leak but not a memory safety issue. Much like the [example](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#initializing-an-array-element-by-element) from the docs.

**Comment by Zoxc** [comment]
The `TypedArena` `Drop` impl will always destroy the elements allocated by `alloc_raw_slice`.

**Comment by nnethercote** [comment]
> You could look into reverting #78569 if you want this to be cleaner.

Good suggestion. I've done this in #116370. The performance wins in #78569 were basically non-existent at the time and my measurements from today were much the same.

**Comment by nnethercote** [comment]
See #116370 for a better approach.

**Pull request closed without merging**
