### PR TITLE
Select dst addresses type based on src in send_to

### PR DESCRIPTION
**Pull request by achanda**
This changes send_to to select a destination address that matches
the address type of the sender.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm this is unconditionally executing a syscall per send_to that wasn't happening before. To me that kinda seems like a non-starter, but without that I unfortunately can't see a great way to handle this...

**Comment by achanda** [comment]
True, I'm not very sure if this is worth pursuing. Thoughts?

**Comment by alexcrichton** [comment]
Perhaps this could update the documentation to account for this pitfall?

**Comment by achanda** [comment]
Let me do that in another PR

**Pull request closed without merging**
