### PR TITLE
[Crater run experiment] let-chain rescoping

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Please do not merge this PR. This is only for crater run experimentation.

I would like to nominate a crater run for #107251 assuming that the feature gate is always on. Through this experiment, we hope to collect breakage in the wild. We would focus on both compilation errors and test errors that this edition change can lead to, if users are targeting Edition 2024 and writing code assuming the old semantics unknowingly.

I realise that some tests may not work well if an edition switch happens. I am fixing them in the main PR.

Tracking:

- https://github.com/rust-lang/rust/issues/124085

### CODE REVIEW

**Comment by Nadrieril** [comment]
I'm on vacation for a week, I'll let someone else figure out the right crater incantation.

r? compiler

**Comment by dingxiangfei2009** [comment]
I would like to run @`craterbot build-and-test` because some breakage due to this edition change will happen at runtime.

**Comment by estebank** [comment]
@craterbot build-and-test

**Comment by estebank** [comment]
@craterbot run mode=build-and-test

**Comment by estebank** [comment]
We'd need to improve the diagnostic if we make this change, but not terrible. There impact is larger than I'd be personally comfortable, but also small enough that it might be acceptable after fixing `smodel`. I would like to make this a lint behavior instead of a breaking change.

```
[INFO] [stderr]    Compiling smodel v1.0.13 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]    --> src/lib.rs:37:9
[INFO] [stdout]     |
[INFO] [stdout] 37  | /         smodel! {
[INFO] [stdout] 38  | |             mod smodel = crate;
[INFO] [stdout] 39  | |
[INFO] [stdout] 40  | |             type Arena = Arena;
[INFO] [stdout] ...   |
[INFO] [stdout] 121 | |             }
[INFO] [stdout] 122 | |         }
[INFO] [stdout]     | |         ^
[INFO] [stdout]     | |         |
[INFO] [stdout]     | |         temporary value is freed at the end of this statement
[INFO] [stdout]     | |_________creates a temporary value which is freed while still in use
[INFO] [stdout]     |           borrow later used here
[INFO] [stdout]     |
[INFO] [stdout]     = note: consider using a `let` binding to create a longer lived value
[INFO] [stdout]     = note: this error originates in the macro `smodel` (in Nightly builds, run with -Z macro-backtrace for more info)
```
```
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]    --> src/main.rs:343:31
[INFO] [stdout]     |
[INFO] [stdout] 343 |         if let Ok(ref home) = env::var("HOME") { home } else { "$HOME" } );
[INFO] [stdout]     |         ----------------------^^^^^^^^^^^^^^^^--------------------------
[INFO] [stdout]     |         |                     |                       |
[INFO] [stdout]     |         |                     |                       temporary value is freed at the end of this statement
[INFO] [stdout]     |         |                     creates a temporary value which is freed while still in use
[INFO] [stdout]     |         borrow later used here
[INFO] [stdout]     |
[INFO] [stdout]     = note: consider using a `let` binding to create a longer lived value
```
```
[INFO] [stderr]    Compiling psi-lang v0.3.0 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]    --> src/interpreter.rs:107:38
[INFO] [stdout]     |
[INFO] [stdout] 105 |                 self.env.raw_expr(
[INFO] [stdout]     |                          -------- borrow later used by call
[INFO] [stdout] 106 |                     &id[0],
[INFO] [stdout] 107 |                     if let Some(i) = items.keys().get(iteration as usize) {
[INFO] [stdout]     |                                      ^^^^^^^^^^^^ creates a temporary value which is freed while still in use
[INFO] [stdout] 108 |                         i
[INFO] [stdout] 109 |                     } else {
[INFO] [stdout]     |                     - temporary value is freed at the end of this statement
[INFO] [stdout]     |
[INFO] [stdout]     = note: consider using a `let` binding to create a longer lived value
```
```
[INFO] [stderr]    Compiling hdf5file v0.1.1 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]   --> examples/object.rs:35:40
[INFO] [stdout]    |
[INFO] [stdout] 33 | /                 println!(
[INFO] [stdout] 34 | |                     "{}",
[INFO] [stdout] 35 | |                     track_assert_some!(track!(object_path)?.to_str(), trackable::error::Failed)
[INFO] [stdout]    | |                     -------------------^^^^^^^^^^^^^^^^^^^^------------------------------------
[INFO] [stdout]    | |                     |                  |
[INFO] [stdout]    | |                     |                  creates a temporary value which is freed while still in use
[INFO] [stdout]    | |                     temporary value is freed at the end of this statement
[INFO] [stdout] 36 | |                 );
[INFO] [stdout]    | |_________________- borrow later used here
[INFO] [stdout]    |
[INFO] [stdout]    = note: consider using a `let` binding to create a longer lived value
```
```
[INFO] [stderr]    Compiling haddock v0.2.1 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]   --> src/commands/stop.rs:85:42
[INFO] [stdout]    |
[INFO] [stdout] 83 | ...                   .chain(
[INFO] [stdout]    |                        ----- borrow later used by call
[INFO] [stdout] 84 | ...                       if let Some(timeout) =
[INFO] [stdout] 85 | ...                           &args.timeout.map(|timeout| timeout.to_string())
[INFO] [stdout]    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
[INFO] [stdout] ...
[INFO] [stdout] 88 | ...                       } else {
[INFO] [stdout]    |                           - temporary value is freed at the end of this statement
[INFO] [stdout]    |
[INFO] [stdout]    = note: consider using a `let` binding to create a longer lived value
```
```
[INFO] [stderr]    Compiling ozes-parser v0.1.4 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]   --> src/parser/mod.rs:84:50
[INFO] [stdout]    |
[INFO] [stdout] 84 | ...   if let Some(ref value) = self.current_tok.value() { String::from_utf8_lossy(value) } else { String::from_utf8_lossy(b"any") }
[INFO] [stdout]    |       -------------------------^^^^^^^^^^^^^^^^^^^^^^^^----------------------------------------------------------------------------
[INFO] [stdout]    |       |                        |                                                         |
[INFO] [stdout]    |       |                        |                                                         temporary value is freed at the end of this statement
[INFO] [stdout]    |       |                        creates a temporary value which is freed while still in use
[INFO] [stdout]    |       borrow later used here
[INFO] [stdout]    |
[INFO] [stdout]    = note: consider using a `let` binding to create a longer lived value
```
```
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]    --> src/main.rs:155:38
[INFO] [stdout]     |
[INFO] [stdout] 155 |           if let Some(project_dirs) = &ProjectDirs::from("", "HaNa", "project_manager") {
[INFO] [stdout]     |           -                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
[INFO] [stdout]     |  _________|
[INFO] [stdout]     | |
[INFO] [stdout] 156 | |             Ok(project_dirs.config_dir())
[INFO] [stdout] 157 | |         } else {
[INFO] [stdout]     | |         - temporary value is freed at the end of this statement
[INFO] [stdout] 158 | |             Err(anyhow!("failed finding the config directory"))
[INFO] [stdout] 159 | |         }?
[INFO] [stdout]     | |__________- borrow later used by call
[INFO] [stdout]     |
[INFO] [stdout] help: consider using a `let` binding to create a longer lived value
[INFO] [stdout]     |
[INFO] [stdout] 154 ~     let binding = ProjectDirs::from("", "HaNa", "project_manager");
[INFO] [stdout] 155 ~     let mut config_path: PathBuf =
[INFO] [stdout] 156 ~         if let Some(project_dirs) = &binding {
[INFO] [stdout]     |
```
```
[INFO] [stderr]    Compiling toipe v0.5.0 (/opt/rustwide/workdir)
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]   --> src/config.rs:45:44
[INFO] [stdout]    |
[INFO] [stdout] 45 |               if let Some(possible_value) = &self.wordlist.to_possible_value() {
[INFO] [stdout]    |               -                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
[INFO] [stdout]    |  _____________|
[INFO] [stdout]    | |
[INFO] [stdout] 46 | |                 possible_value.get_name()
[INFO] [stdout] 47 | |             } else {
[INFO] [stdout]    | |             - temporary value is freed at the end of this statement
[INFO] [stdout] 48 | |                 "unknown"
[INFO] [stdout] 49 | |             }
[INFO] [stdout]    | |_____________- borrow later used here
[INFO] [stdout]    |
[INFO] [stdout]    = note: consider using a `let` binding to create a longer lived value
```

**Comment by est31** [comment]
FTR the first version of smodel on crates.io, 0.1.0 was released one month ago, April 29 2024.

**Comment by estebank** [comment]
@dingxiangfei2009 are we ok to close this PR now?

**Comment by dingxiangfei2009** [comment]
@estebank Sorry, yes. Let's.

**Pull request closed without merging**
