### PR TITLE
Promote loongarch64-unknown-linux-gnu to Tier 2 with host tools

### PR DESCRIPTION
**Pull request by heiher**
This PR promotes `loongarch64-unknown-linux-gnu` to Tier 2 (with host tools).

MCP: https://github.com/rust-lang/compiler-team/issues/518

### CODE REVIEW

**Review by xen0n — COMMENTED** [review]
Thanks for posting this early! For now it seems trivial enough and we only need to wait for the CI changes to first go in.

**Comment by ehuss** [comment]
r? compiler

**Comment by jyn514** [comment]
r? infra

**Pull request merged**
