### PR TITLE
syntax: move ast_map to librustc.

### PR DESCRIPTION
**Pull request by eddyb**
Gets libsyntax one step closer to running on stable (see #24518).
Closes #24757, erickt's previous attempt at this.

### CODE REVIEW

**Comment by Manishearth** [comment]
Would it be worth/possible moving this to `librustc_ast_map`? Every bit helps :)

**Comment by eddyb** [comment]
@Manishearth it wouldn't help much because librustc depends on it. Most of the parallelism in building rustc starts *after* librustc.

**Comment by Manishearth** [comment]
Ah. Might it be reasonable to have some parallel crates in between syntax and rustc? 

The way I see it, we can fan out after syntax,  converge on rustc, and then fan out into the rustc_*s. Not a big win, but still could be a win.

**Comment by erickt** [comment]
thanks @eddyb! I'm still catching up from my vacation, and haven't gotten around to fixing my PRs yet :)

**Pull request merged**
