### PR TITLE
Properly feature gate all unstable ABIs

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/34900
[breaking-change]
r? @pnkfelix 

---

Function-visiting machinery for AST/HIR is surprisingly error-prone, it's _very_ easy to miss some cases or visit something twice while writing a visitor. This is the true problem behind https://github.com/rust-lang/rust/issues/34900. I'll try to restructure these visitors a bit and send one more PR later.

### CODE REVIEW

**Comment by pnkfelix** [comment]
@petrochenkov to be honest I was expecting a warning cycle.

For now I'll at least tag this as needing a crater run.

**Comment by petrochenkov** [comment]
I'd be surprised if it broke anything in practice, but let's see what crater will say.

**Comment by pnkfelix** [comment]
The patch itself looks fine, so r=me apart from the question of whether it should go through a warning cycle.

I'll nominate for discussion at lang team mtg.

**Comment by eddyb** [comment]
Will start a crater run now. Sorry about that, we had network issues with GitHub for a while.

**Comment by eddyb** [comment]
[Crater report](https://gist.github.com/eddyb/4c530697a3fd11a8302d5287f59da203) shows 0 regressions.

**Comment by nikomatsakis** [comment]
OK, let's do it.

**Comment by alexcrichton** [comment]
@bors: rollup

assuming this isn't very platform-specific and green travis means it's good to go whenever

**Pull request merged**
