### PR TITLE
Fix rustdoc output performance

### LINKED ISSUE #22325: Responsive rustdoc output is unresponsive (literally)
E.g. http://tomaka.github.io/cpal/alsa-sys/index.html

Resizing two windows that show this site causes 3-5 seconds of 100% cpu usage on two cores.

Solution: Remove responsive javascript to make the site more responsive.

```js
    function resizeShortBlocks() {
        if (resizeTimeout) {
            clearTimeout(resizeTimeout);
        }
        resizeTimeout = setTimeout(function() {
            var contentWidth = $('.content').width();
            $('.docblock.short').width(function() {
                return contentWidth - 40 - $(this).prev().width();
            }).addClass('nowrap');
            $('.summary-column').width(function() {
                return contentWidth - 40 - $(this).prev().width();
            })
        }, 150);
    }
    resizeShortBlocks();
    $(window).on('resize', resizeShortBlocks);
```
But that's not all: When you load this site for the first time, it doesn't even react to any user input for 5 seconds.

### PR DESCRIPTION
**Pull request by mahkoh**
Fixes #22325

### CODE REVIEW

**Comment by nagisa** [comment]
This snippet actually does something useful, although it might not look like it is a case at the first sight.

It truncates short descriptions in the list of items such as in search or at the bottom of the module page. Without this script, horizontal scrolling appears on smaller viewports (ignore the terrible fonts, this is many-years old version of chrome being dumb):

screenshot from 2015-02-24 21 05 44

There’s not really a good way to preserve this functionality without javascript, because that’s how HTML tables work.

**Comment by mahkoh** [comment]
All the better. Whoever thought that hiding information from people with small screens was a good idea should be punished by having all descriptions removed from their rustdoc searches.

An alternative to the scrolling is breaking like this.
2015-02-24-201245_683x501_scrot

**Comment by huonw** [comment]
Could you amend the commit message to contain more details? As it stands it doesn't even contain a reference to the issue in question.

**Comment by mahkoh** [comment]
Done.

**Comment by retep998** [comment]
Another solution is to use CSS which has a built in feature to cut off overflow with ellipses. 
`text-overflow: ellipsis;`
Why are we simulating CSS with a terribly slow JS solution?

**Comment by nagisa** [comment]
Because that doesn't work on tables.

**Comment by brson** [comment]
Sorry for the delay.

**Comment by brson** [comment]
cc https://github.com/rust-lang/rust/pull/23283

**Pull request merged**
