### PR TITLE
Use inline const blocks to create arrays of `MaybeUninit`.

### PR DESCRIPTION
**Pull request by kpreid**
This PR contains 2 changes enabled by the fact that [`inline_const` is now stable](https://github.com/rust-lang/rust/pull/104087), and was split out of #125082.

1. Use inline const instead of `unsafe` to construct arrays in `MaybeUninit` examples.
 
   Rationale: Demonstrate good practice of avoiding `unsafe` code where it is not strictly necessary.

4. Use inline const instead of `unsafe` to implement `MaybeUninit::uninit_array()`.

    This is arguably giving the compiler more work to do, in exchange for eliminating just one single internal unsafe block, so it's less certain that this is good on net.

r​? @Nilstrieb

### CODE REVIEW

**Comment by workingjubilee** [comment]
r? Nilstrieb

**Comment by workingjubilee** [comment]
I'm so confused.

**Comment by workingjubilee** [comment]
Anyways Nils already said these were approved so
@bors r=Nilstrieb

**Comment by workingjubilee** [comment]
oh lol.
@bors r-

**Comment by kpreid** [comment]
Typo fixed.

**Review by Noratrieb — APPROVED** [review]

**Pull request merged**
