### PR TITLE
Improve error display for codeblocks in rustdoc

### LINKED ISSUE #53919: doc: Errors during syntax highlighting appear to be fatal
When building documentation on bindgen-produced Rust files, a possible sight looks like this:

<pre><font color="#EF2929"><b>error</b></font><font color="#FFFFFF"><b>: unknown start of token: \</b></font>
 <font color="#739FCF"><b>--&gt; </b></font>&lt;stdin&gt;:8:1
  <font color="#739FCF"><b>|</b></font>
<font color="#739FCF"><b>8</b></font> <font color="#739FCF"><b>| </b></font>\__________pkt-&gt;size___________/          \_result-&gt;size_/ \__pkt-&gt;size__/                                                
  <font color="#739FCF"><b>| </b></font><font color="#EF2929"><b>^</b></font>

<font color="#FCE94F"><b>warning</b></font><font color="#FFFFFF"><b>: Backing out of syntax highlighting</b></font>
  <font color="#739FCF"><b>|</b></font>
  <font color="#739FCF"><b>= </b></font><font color="#FFFFFF"><b>note</b></font>: You probably did not intend to render this as a rust code-block</pre>

(Apparently github swallows the output color codes, but envision error in alerting red and warning in yellow).

To the moderately experienced developer, this screams "The build did not succeed", and they might even go as far as to look at how to make rust-bindgen produce more readable comments -- where actually, everything is fine and this is just a warning.

It appears to me that the error output of the highlighter is passed on to stderr. I suggest that the error be visually styled in a way that it can not be mistaken for a fatal error in the build process itself, eg. by replacing the red "error" text with a yellow "syntax highlighter error (caught)", and/or by indenting the output of the syntax highlighter.

I'd be happy to contribute code but failed to find the component that issues the "Backing out of syntax highlighting" messages; pointers would be appreciated.

## Meta
* cargo 1.29.0-nightly (0ec7281b9 2018-08-20)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #53919.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
```
[01:00:56] ---- [rustdoc] rustdoc/issue-12834.rs stdout ----
[01:00:56] 
[01:00:56] error: rustdoc failed!
[01:00:56] status: exit code: 1
[01:00:56] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-12834/auxiliary" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/issue-12834" "/checkout/src/test/rustdoc/issue-12834.rs"
[01:00:56] stdout:
[01:00:56] ------------------------------------------
[01:00:56] 
[01:00:56] ------------------------------------------
[01:00:56] stderr:
[01:00:56] ------------------------------------------
[01:00:56] warning: Backing out of syntax highlighting
[01:00:56]   |
[01:00:56]   = note: You probably did not intend to render this as a rust code-block
[01:00:56] 
[01:00:56] error: internal compiler error: Error constructed but not emitted
[01:00:56] 
[01:00:56] thread '<unnamed>' panicked at 'explicit panic', librustc_errors/diagnostic_builder.rs:295:13
[01:00:56] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:00:56] 
[01:00:56] error: internal compiler error: unexpected panic
[01:00:56] 
[01:00:56] note: the compiler unexpectedly panicked. this is a bug.
[01:00:56] 
[01:00:56] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[01:00:56] 
[01:00:56] note: rustc 1.30.0-dev running on x86_64-unknown-linux-gnu
[01:00:56] 
[01:00:56] 
[01:00:56] ------------------------------------------
[01:00:56] 
[01:00:56] thread '[rustdoc] rustdoc/issue-12834.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3196:9
[01:00:56] 
[01:00:56] 
[01:00:56] failures:
[01:00:56]     [rustdoc] rustdoc/issue-12834.rs
```

**Comment by QuietMisdreavus** [comment]
Also, can you add a test? Maybe try to reduce some of the linked issue's bindgen output into something we can stuff into a `rustdoc-ui` test?

**Comment by GuillaumeGomez** [comment]
Oh damn, forgot to add the test!

**Comment by GuillaumeGomez** [comment]
CI passed and forgotten test added.

**Comment by TimNN** [comment]
Ping from triage @QuietMisdreavus: This PR requires your review.

**Comment by QuietMisdreavus** [comment]
Whoops, sorry for letting this one slip!

@bors r+

**Comment by kennytm** [comment]
@bors r-

We need to update [this test](https://github.com/rust-lang/cargo/blob/c1c4fc2e4c06b10d89d0284e35330af89c58fe65/tests/testsuite/doc.rs#L611-L642) from cargo to make it compatible with the new wordings. See https://github.com/rust-lang/rust/pull/54168#issuecomment-421069983.

**Comment by GuillaumeGomez** [comment]
This is... weird... I suppose the stderr isn't checked the same way or something along the line. I'll fix it in the next days.

**Comment by QuietMisdreavus** [comment]
but: exited with exit code: 0

I think Cargo is expecting this test to crash rustdoc; does this PR make parse errors non-fatal?

**Comment by GuillaumeGomez** [comment]
It does indeed. That was the whole point of the PR, which is why I'm having trouble in here. Should I disable the test on cargo waiting for this PR to get merged?

**Comment by GuillaumeGomez** [comment]
@rust-lang/cargo Should I open a PR on cargo to disable the failing test before merging this one (and then fixing the test on cargo)?

**Comment by alexcrichton** [comment]
Either that or updating the test to only verify the output and not the exit code should be fine, yeah.

**Comment by ehuss** [comment]
I'm curious, I'm not sure I understand how this addresses the original issue.  It looks like it still prints "error:" which is what is confusing, it just prints it in the reverse order from before (specifically in the bindgen case where it starts with valid code).  It still seems a little confusing to me seeing a red error message, but it not failing.

**Comment by kennytm** [comment]
@ehuss The error message is fine, the problem is the exit code is different. Removing [this line](https://github.com/rust-lang/cargo/blob/c1c4fc2e4c06b10d89d0284e35330af89c58fe65/tests/testsuite/doc.rs#L638) should be sufficient to fix the issue.

**Comment by GuillaumeGomez** [comment]
I can add a message looking like: "stderr from rustc".

**Comment by GuillaumeGomez** [comment]
Updated the message a bit (and updated cargo as well).

**Comment by QuietMisdreavus** [comment]
Hmm, looking at the original issue again, i have to agree with @ehuss: i don't think this fixes the linked issue. Based on the test you included, the problematic "error" text is still being emitted, because that's coming from within the lexer. That said, i don't think you can change the lint cap on a Session after it's been created? (Since the lexer emits its errors using the Session we hand to it, we'd need to edit that to adjust how its warnings/errors are emitted. Moreover, it's not even a lint to begin with! Changing the lint cap probably won't help, since we're catching errors that would otherwise be fatal if included in a "real" source file.)

**Comment by QuietMisdreavus** [comment]
Some discussion on Discord:

If there were a way we could delay outputting the errors from libsyntax until we can get some lines of our own in, that may help. That way we can print our own warning, follow it with a line like "output from rustc" like @GuillaumeGomez suggested, then print the actual error from the lexer. Then the ordering of the output can at least make sense.

**Comment by GuillaumeGomez** [comment]
Not yet but soon (my PR queue is quite big...).

**Comment by GuillaumeGomez** [comment]
Updated. Better like this? I'm open to alternative suggestions. :)

**Comment by ehuss** [comment]
As I mentioned, if the bad token is in the middle as the original issue, the only difference this PR makes is to flip the error/warning messages.

Before:
```
error: unknown start of token: \
 --> <stdin>:2:1
  |
2 | \___/
  | ^

warning: Backing out of syntax highlighting
  |
  = note: You probably did not intend to render this as a rust code-block
```

After:
```
warning: Backing out of syntax highlighting
  |
  = note: You probably did not intend to render this as a rust code-block

error: unknown start of token: \
 --> <stdin>:2:1
  |
2 | \___/
  | ^
```

Although changing the start-token error to a warning with a better message is nice, it doesn't seem to meet the spirit of the original issue.

**Comment by QuietMisdreavus** [comment]
I meant "change the PR description to stop saying 'fixes issue'" but i went ahead and did that myself. We can fold other UI requests about this feature into that same issue, since at least @ehuss considers this PR to not be a complete fix. Still, we can merge this and work the change into https://github.com/rust-lang/rust/pull/54861 while we refine this in a separate PR.

@bors r+

**Comment by QuietMisdreavus** [comment]
```
/Users/travis/.rvm/gems/ruby-2.4.2/gems/aws-sdk-core-2.11.147/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Encountered a `SocketError` while attempting to connect to: (Aws::Errors::NoSuchEndpointError)
```

@rust-lang/infra Is this a known error?

**Comment by pietroalbini** [comment]
Seems like a spurious failure while uploading artifacts to S3.

@bors retry

**Comment by kennytm** [comment]
@bors retry 

S3 deploy error again

**Pull request merged**
