### PR TITLE
Split left-shift into two less-than for properly parsing associated type syntax.

### PR DESCRIPTION
**Pull request by mark3982**

### CODE REVIEW

**Comment by sfackler** [comment]
The commit should be marked with `[breaking-change]` along with a quick explanation of how to fix the parse errors that might pop up in downstream code.

**Comment by nikomatsakis** [comment]
This looks good. r+ with a comment plus a change to the commit to mention `[breaking-change]` as @sfackler suggested. Please ping me (or eddyb) on IRC for r+ after that's done.

**Comment by huonw** [comment]
Is this a dupe of https://github.com/rust-lang/rust/pull/20154?

**Comment by alexcrichton** [comment]
Yes I think this was a dupe of #20154 (which is now merged), thanks regardless @kmcguire3413!

**Pull request closed without merging**
