### PR TITLE
Update cargo submodule

### PR DESCRIPTION
**Pull request by alexcrichton**
I'm not really sure what we want the cadence here to be. We'll at the very least
update the Cargo submodule right before all releases, but otherwise I figured we
could just do it whenever needed or otherwise weekly (or something like that).

In any case, I don't have a super strong particular reason to do this, it's just
been a week or so since the release!

### CODE REVIEW

**Comment by arielb1** [comment]
-  #40821
    @bors retry

**Comment by arielb1** [comment]
-  #40821
    @bors retry

**Comment by alexcrichton** [comment]
@bors: retry

* flaky mingw debuginfo - https://github.com/rust-lang/rust/issues/40835

**Pull request merged**
