### PR TITLE
proof tree nits

### PR DESCRIPTION
**Pull request by lcnr**
r? @BoxyUwU

### CODE REVIEW

**Comment by BoxyUwU** [comment]
@bors rollup=never p=1 (likely to conflict)
r=me if using the flag on the example in <https://github.com/rust-lang/trait-system-refactor-initiative/issues/25> gives the same results as it did in #112351

**Comment by lcnr** [comment]
@bors r=BoxyUwU

test is the same modulo changes to `DefId` paths :grin:

**Comment by klensy** [comment]
https://github.com/rust-lang/rust/blob/1b6d4cdc4d923c148198ad4df230af48cdaca59e/compiler/rustc_middle/src/traits/solve/inspect.rs#L68-L74

Noticed while looking pr diff: currently `name` always static string, but allocated as `String` everywhere, maybe change it to `str`?

**Comment by lcnr** [comment]
> Noticed while looking pr diff: currently `name` always static string, but allocated as `String` everywhere, maybe change it to `str`?

yeah, or well, the goal is to replace it with an enum (and add `fn probe_candidate` which takes a `CandidateKind` directly).

**Comment by BoxyUwU** [comment]
this doesn't even touch any code run by benchmarks its entirely new solver

**Comment by lqd** [comment]
Yeah it could just be the inlining noise happening even by simply looking at the old trait solver in a way it doesn't like. Similar to how #112351 also improved these same benchmarks unexpectedly. 

I myself don't know what is old or new solver from the diff, or what is shared between the two, so maybe the weekly triage will see something we don't -- but most likely they can just mark this as triaged from your comment.

**Pull request merged**
