### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #60300 (Allow null-pointer-optimized enums in FFI if their underlying representation is FFI safe)
 - #60773 (Always try to project predicates when finding auto traits in rustdoc)
 - #60809 (Add FAQ for NLL migration)
 - #61023 (Migrate from recursion to iterate on qualify consts visitor impl)
 - #61029 (Simplify RefCell minimum_spanning_tree example)
 - #61030 (Make maybe_codegen_consume_direct iterate instead of doing recursion)
 - #61034 (rustc_metadata: parametrize schema::CrateRoot by 'tcx and rip out old unused incremental infra.)
 - #61037 (Update clippy submodule)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors retry

Yielding priority to the beta.

**Comment by Xanewok** [comment]
@Centril are submodule updates subject to rollups?

**Comment by Centril** [comment]
@Xanewok depends on the submodule =) books and clippy is pretty safe. LLVM ==> absolutely not.

**Pull request merged**
