### PR TITLE
Move libtest out of rust-lang/rust

### PR DESCRIPTION
**Pull request by gnzlbg**
This is a first step towards a number of goals explained in this internals post: https://internals.rust-lang.org/t/a-path-forward-towards-re-usable-libtest-functionality-custom-test-frameworks-and-a-stable-bench-macro

This PR does not fully remove libtest from rust-lang/rust, we keep a shim that imports and re-exports the external libtest, and adds the proc_macro dependency, etc. 

r? @alexcrichton 

cc @djrenren @petrochenkov

### CODE REVIEW

**Comment by gnzlbg** [comment]
@alexcrichton once we have something that "works" for this PR, it would be great if you could move the extracted `libtest` source (https://github.com/gnzlbg/libtest) into a Rust org (the nursery or rust-lang/rust). 

Also, I extracted the libtest crate there by forking the rust repo and removing everything but the crate, because I wanted to preserve the history. But this means that the libtest crate repo is huge, which makes the initial fetch very slow. I think this won't be a problem once we release the libtest crate to crates.io and add it as a normal dependency instead of a git dependency, but I prefer to do that when the official repo for libtest is set up.

**Comment by djrenren** [comment]
Hey heads up, with respect to size, we can use `git filter-branch` to retain only the history of the folder.

From a fresh checkout of `rust-lang/rust` I just ran:
```
git filter-branch --prune-empty --subdirectory-filter src/libtest master
```

I've hosted the result here: https://github.com/djrenren/libtest 

but it looks like it lacks `libterm` and licenses. Still I think this is a good idea to clean up the history.

**Comment by Dylan-DPC** [comment]
ping from triage @gnzlbg you need to address the first point in https://github.com/rust-lang/rust/pull/57842#issuecomment-456586908 and the conflicts

**Comment by gnzlbg** [comment]
@alexcrichton so I've managed to properly extract only the history of the libterm and libtest repositories.

> All unstable code should continue to live in this repository (but the bulk of all code should still live externally)

So `libtest` has some unstable code, like `black_box` (which uses inline assembly), but nothing "super" unstable. 

> We'll want to move the repo under the rust-lang GitHub organization (let me know when you're ready) We'll want to publish to crates.io and depend on the crates there from the unstable code in this repo

The repo is ready (https://github.com/gnzlbg/libtest) I've transferred it to you so that it can be added to the organization. I haven't published the repo yet, since I thought it might be better for the organization to publish it. Once the transfer is complete I can publish it as libtest 0.0.1 and will update this PR to use that instead.

---

Every time libtest is modified upstream one has to restart the migration process from zero, so once this is done it might be wise to prioritize the bors merge.

**Comment by gnzlbg** [comment]
So the failure is to be expected until we start using a crate from crates.io. I've added a commit that runs the apple and linux jobs on this branch to make sure that modulo tidy everything else is ok.

**Comment by gnzlbg** [comment]
@alexcrichton so I went ahead and released the crates on crates.io to make the tests pass, i've sent you invites as an owner.

**Comment by alexcrichton** [comment]
Oh sorry I was a bit slow on the repo transfer and it's now expired, want to send the transfer to me again? (and I'll transfer to rust-lang)

I think it'd be best though if we start off from a clean/stable slate. Would it be possible to get `libtest` on crates.io building on stable Rust? Additionally, I would prefer that we keep all the rustc-unstable bits in this repository, rather than simply `pub use libtest::*`. Could the rustc-specific structures (the ones that rustc emits and uses) be copied here to this repository and then mapped to the `libtest` versions upstream so we can change the ones in this repository easily?

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/libtest

🎊

**Comment by gnzlbg** [comment]
So @alexcrichton I've added a README briefly describing the situation and pointing to a "roadmap" issue in `rust-lang/libtest`. I've also removed the `pub use libtest::*` export, and explicitly imported the most important parts of the libtest API manually. We should strive to reduce the list of imports in the future, and figure out if there are any bits of `libtest` that make sense re-implementing in rust-lang/rust to help with maintainability so that libtest can iterate faster and more freely as a standalone crate. At the same time, the unstable `test` crate is widely used, and just because its unstable does not mean that we can break its users freely. If we want to remove some parts of the `test` crate API, I think we should do so only if we are already providing an alternative on crates.io .

**Comment by gnzlbg** [comment]
cc @alexcrichton because of the changes to the Cargo.lock, this needs to be approved again =/

**Pull request merged**
