### PR TITLE
CI: unset NO_DOWNLOAD_CI_LLVM for 2 windows jobs

### PR DESCRIPTION
**Pull request by marcoieni**
mati865 mentioned in https://github.com/rust-lang/rust/pull/132721#issuecomment-2465316995 that we can remove this environment variable

try-job: dist-i686-mingw
try-job: dist-x86_64-mingw

### CODE REVIEW

**Comment by mati865** [comment]
I don't know how this works, but perhaps the dist build without that ENV has to be completed first so it can upload the artifacts?

**Comment by Kobzol** [comment]
It seems to me from the CI logs that `dist-i686-mingw` and friends does upload the built `dist` artifacts, including LLVM. But I guess it's worth a try to first only run the dist jobs.

**Comment by MarcoIeni** [comment]
I'm trying the jobs dist-i686-mingw and dist-x86_64-mingw. Not sure if I understood correctly your suggestion 🤔

**Comment by MarcoIeni** [comment]
image

**Comment by Kobzol** [comment]
It doesn't look like this does anything for CI time though. Let's try again to see if some cache kicks in.

@bors try

**Comment by Kobzol** [comment]
Doesn't seem like there is any CI time effect.

**Comment by mati865** [comment]
Doesn't seem to work: `[TIMING] core::build_steps::llvm::Llvm { target: x86_64-pc-windows-gnu } -- 859.128`

**Comment by mati865** [comment]
Ah, it also doesn't work for MSVC. Probably a general Windows problem.

**Comment by MarcoIeni** [comment]
Since it doesn't work and it doesn't make a big impact on timings, I'll close this PR 👍

**Comment by mati865** [comment]
So this is the reason why it doesn't work with MSVC: https://github.com/rust-lang/rust/blob/a8e75c53d0036b5d012cbc0ee5de17f8991fe60c/src/ci/scripts/install-clang.sh#L67
Do you want to give it another try or should I open a PR?

**Comment by Kobzol** [comment]
Dist builders are designed to build the components, and other jobs (and tools like rustup etc.) are designed to download them. So we should keep building them on the dist builders. In theory, we could just build them from time to time, but I don't think I trust our CI enough to do that at the moment.

**Comment by MarcoIeni** [comment]
I tried downloading llvm in mingw but it [fails](https://github.com/rust-lang/rust/pull/132721#issuecomment-2482847242)

**Pull request closed without merging**
