### PR TITLE
Add 'platform-specific' section to `sleep_ms` to match `sleep`.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by retep998** [comment]
There is an equivalent thing on Windows, where the sleep won't return early due to an asynchronous procedure call because it isn't an alertable sleep.

**Comment by alexcrichton** [comment]
@bors: r+

Thanks @frewsxcv!

**Comment by alexcrichton** [comment]
@bors: retry

Presumably some bug in @bors? The builds both completed sucessfully: https://travis-ci.org/rust-lang/rust/builds/193285888 and https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1606.

**Comment by alexcrichton** [comment]
@bors: retry 

* interrupting to bump the rollup up

**Pull request merged**
