### PR TITLE
Update E0057 error message to new format

### LINKED ISSUE #35214: E0057 needs to be updated to new format
From: src/test/compile-fail/E0057.rs

Error E0057 needs a span_label, updating it from:

```
error[E0057]: this function takes 1 parameter but 2 parameters were supplied
  --> src/test/compile-fail/E0057.rs:15:13
   |
15 |     let c = f(2, 3); //~ ERROR E0057
   |             ^^^^^^^
   |
   = note: the following parameter type was expected: (_,)
```

To:

```
error[E0057]: this function takes 1 parameter but 2 parameters were supplied
  --> src/test/compile-fail/E0057.rs:15:13
   |
15 |     let c = f(2, 3); //~ ERROR E0057
   |             ^^^^^^^ expected 1 parameter
   |
   = note: the following parameter type was expected: (_,)
```

Bonus 1: The note seems excessive.  Check other E0057 errors.  If it is not needed, remove the note.

Bonus 2: The span for the error could likely focus on the parameters rather than the whole call.

### PR DESCRIPTION
**Pull request by paulfanelli**
Fixes #35214 as part of #35233.

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Comment by jonathandturner** [comment]
@paulfanelli - can you update this to fix the merge conflict?  With that, I think we're good to go.

**Comment by paulfanelli** [comment]
Will do...I'll take a look at.

**Comment by paulfanelli** [comment]
Looks like the reason there was a conflict, is that someone else had also fixed it.  To fix the conflict, I updated my fork with the latest rust code and rebased my branch where i did the work (update-e0057-error-msg) onto the lastest rust code.  I re-complied and tested it.  I then pushed the updated code back to the update-e0057-error-msg branch of my fork.  I think this pull request now is good to go. (?)

**Comment by jonathandturner** [comment]
@paulfanelli - if I'm reading this right, did someone fix this issue already?  If so, I can close this and you can pick another one from the list (if you like): https://github.com/rust-lang/rust/issues/35233

**Comment by paulfanelli** [comment]
Yep, someone fixed it, just a bit differently.  Ok, go ahead and close this and I'll take #35233 , if still available.

**Comment by paulfanelli** [comment]
Oops, didn't realize that #35233 is the catch-all issue; can't take them all, lol. I'll pick something from the list.

**Comment by paulfanelli** [comment]
Hey, just a heads up, I never did any bonus work on this one. Not sure if whoever fixed it, did either.

**Comment by bstrie** [comment]
I believe this is now being addressed by https://github.com/rust-lang/rust/pull/36222 , so I'll close this (feel free to reopen if I'm wrong). Thanks for the effort in any case! :)

**Comment by jonathandturner** [comment]
@bstrie - neither PR has landed, yet.  Though given that both haven't moved in over two weeks, perhaps we should close both?

**Pull request closed without merging**
