### PR TITLE
rustdoc: don't process `Crate::external_traits` when collecting intra-doc links

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Part of https://github.com/rust-lang/rust/issues/58745, closes https://github.com/rust-lang/rust/pull/58917

The `collect-intra-doc-links` pass keeps track of the modules it recurses through as it processes items. This is used to know what module to give the resolver when looking up links. When looking through the regular items of the crate, this works fine, but the `DocFolder` trait as written doesn't just process the main crate hierarchy - it also processes the trait items in the `external_traits` map. This is useful for other passes (so they can strip out `#[doc(hidden)]` items, for example), but here it creates a situation where we're processing items "outside" the regular module hierarchy. Since everything in `external_traits` is defined outside the current crate, we can't fall back to finding its module scope like we do with local items.

Skipping this collection saves us from emitting some spurious warnings. We don't even lose anything by skipping it, either - the docs loaded from here are only ever rendered through `html::render::document_short` which strips any links out, so the fact that the links haven't been loaded doesn't matter. Hopefully this removes most of the remaining spurious resolution warnings from intra-doc links.

r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Wo, nice!

r=me once CI passed

**Comment by QuietMisdreavus** [comment]
Whoops, i just noticed this doesn't totally fix the linked issue. We can merge this on its own, but i'll keep digging to see what i can do about the last few warnings from rand.

**Comment by GuillaumeGomez** [comment]
We can also merge mine. I prefer to wait until you have the full thing. ;)

**Comment by QuietMisdreavus** [comment]
I'm hesitant to merge your PR. Muting all resolution errors from non-local items would hide the warnings that were not actually spurious (see the issue linked in the PR description for a couple examples). I think properly solving all the non-spurious warnings would require adding a much larger mechanism, or fixing `rand` itself.

**Comment by QuietMisdreavus** [comment]
I still think this is mergeable as-is; the "full thing" would add too much on top of it, since the remaining warnings in `rand` were not spurious. (Even if they were the result of shortcomings in the intra-doc links feature itself, they still created broken links or erroneous \[link targets\] with square brackets around them.)

**Comment by GuillaumeGomez** [comment]
Let's merge it then, sorry for the time it took!

@bors: r+

**Pull request merged**
