### PR TITLE
Removing unnecessary hack from the error handling chapter

### PR DESCRIPTION
**Pull request by defuz**
r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
You have an unrelated change in AUTHORS.txt, but r=me after! Thank you.

**Comment by defuz** [comment]
@steveklabnik What do you mean "unrelated change"? I just wanted to change the nickname to my real name in AUTHORS.txt. Should I create a separate request for this?

**Comment by steveklabnik** [comment]
Sorry, your PR made no mention of it, and so it seemed to be out of the blue :) If that's something you meant to do, that's fine.

@bors: r+ rollup

**Comment by steveklabnik** [comment]
(and thanks a lot for finding this!)

**Pull request merged**
