### PR TITLE
Stablize arc_unwrap_or_clone

### LINKED ISSUE #93610: Tracking Issue for `arc_unwrap_or_clone`
Feature gate: `#![feature(arc_unwrap_or_clone)]`

This is a tracking issue for `arc_unwrap_or_clone`. This feature adds methods to `Rc`/`Arc` to gain access to the contained value, by unwrapping if there is exactly one reference, or cloning otherwise. It is equivalent to cloning the inner value, but saves the clone operation if the caller has the only reference to the rc'd value.

### Public API

```rust
impl<T: Clone> Arc<T> {
    pub fn unwrap_or_clone(this: Self) -> T;
}
```

### Steps / History

- [x] Implementation: #91589
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- ~~More bikeshedding on the name is possible. Existing discussion on [irlo](https://internals.rust-lang.org/t/arc-into-inner/15707).~~ There seems to be consensus that the current name is good.

### PR DESCRIPTION
**Pull request by ranile**
Fixes: #93610

This likely needs FCP. I created this PR as it's stabilization is trivial and FCP can be just conducted here. Not sure how to ping the libs API team (last attempt didn't work apparently according to GH UI)

### CODE REVIEW

**Comment by tgross35** [comment]
@rustbot label +needs-fcp -t-libs
r? libs-api

**Review by dtolnay — COMMENTED** [review]
FCP proposal: https://github.com/rust-lang/rust/issues/93610#issuecomment-1783906341

**Comment by hamza1311** [comment]
> FCP proposal: https://github.com/rust-lang/rust/issues/93610#issuecomment-1783906341

That concluded positively. We can merge this now

**Review by dtolnay — APPROVED** [review]
Thank you!

**Pull request merged**
