### PR TITLE
Add test for #44953

### LINKED ISSUE #44953: The “use of unstable library feature 'rustc_private'” error is very repetitive
`rustc 1.22.0-nightly (0e6f4cf51 2017-09-27)`

Compiling this:
```rust
#[macro_use] extern crate log;

pub fn main() {
    info!("This is a log message.");
}
```

while not including `log` as a dependency in `Cargo.toml`, produces the following output:
```
error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:1:14
  |
1 | #[macro_use] extern crate log;
  |              ^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> main.rs:4:2
  |
4 |  info!("This is a log message.");
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate

error: aborting due to 10 previous errors
```

### PR DESCRIPTION
**Pull request by virgil-palanciuc**
Added the requested test - trying to see if it passes; my local build fails, but not sure why - the nightly shows this output, but in my build the compilation error changed. 

Fixes #44953.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by kennytm** [comment]
@bors r-

CI failed, see https://github.com/rust-lang/rust/issues/44953#issuecomment-340560040.

**Comment by JakubAdamWieczorek** [comment]
@virgil-palanciuc, in my opinion the way to go would be to write a complete [ui-fulldeps test](https://github.com/rust-lang/rust/tree/master/src/test/ui-fulldeps), so as not to rely on the `log` crate's `rustc_private` attribute. Essentially, have an auxiliary crate with the `rustc_private` configuration attribute (see [here](https://github.com/rust-lang-nursery/log/blob/b8d931bf887e25a1bfc7c484de61ad14dbd10b56/src/lib.rs#L266)) and a test that tries to use it without a `#[feature(rustc_private)]` attribute. But someone else should also comment if that sounds sensible.

**Comment by virgil-palanciuc** [comment]
I will try to do so today. Sorry for the delay, I've been traveling + had a few busy days.

**Comment by shepmaster** [comment]
Heya @virgil-palanciuc — we haven't heard from you in a week or so! Will you have time soon to address the feedback?

**Comment by virgil-palanciuc** [comment]
I'm trying, I just have very limited time right now (especially during the week), and the test proved to be harder then I expected (it's probably not THAT hard, but my rust knowledge is limited, especially around macros ). I hope I can allocate a few hours tomorrow to try again. 

If anyone wants to/ can add this test faster than I can, I don't mind - I don't want to hold you guys back. It's mostly a learning exercise for me :)

**Comment by shepmaster** [comment]
> I just have very limited time right now

That's totally fine, just give us a little status ping every week or so (or we will give you one 😈) to let us know it's still in progress! Thanks!

**Comment by virgil-palanciuc** [comment]
Turns out, the solution I had attempted was overly-complicated (I attempted a partial recreation of the `log` crate inside `ui-fulldeps` - and, while trying to make that work, I ended up realizing it was totally unnecessary). I tested that the test works with current implementation and fails without previous bugfix, so, hopefully all good. 

I'm going to take a pause from contributing right now, as I realized  it takes more time than I currently have; but I hope I'll be able to come back. Gotta say, I'm blown away by the friendliness of this community and how much effort you guys put in to "onboard" new members. Kudos for that.

**Comment by kennytm** [comment]
@bors r+ rollup

Thanks for the hard work @virgil-palanciuc !

**Comment by kennytm** [comment]
@virgil-palanciuc Hi, I just noticed that this PR itself contains a merge commit. Could you rebase and squash everything into a single commit? Thanks.

**Comment by virgil-palanciuc** [comment]
@kennytm Hopefully it's ok now, let me know if I need to do anything else.

**Comment by kennytm** [comment]
Thanks again!

@bors r+

**Comment by kennytm** [comment]
@virgil-palanciuc Sorry needs to bother this again. Due to recent merge of #45545, the UI test output is changed causing your test no longer pass. Please apply the following diff to the `.stderr` file:

```diff
 error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
   --> $DIR/issue-44953.rs:16:14
    |
 16 | #[macro_use] extern crate log;
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(rustc_private)] to the crate attributes to enable
 
 error: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
   --> $DIR/issue-44953.rs:19:5
    |
 19 |     info!("This is a log message.");
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(rustc_private)] to the crate attributes to enable
-   = note: this error originates in a macro outside of the current crate
+   = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)
 
 error: aborting due to 2 previous errors
```

**Comment by virgil-palanciuc** [comment]
This one just doesn't want to get closed, does it?
I pushed the updated output, rebased on top of origin/master,  tested that it works - let's see what else comes up 😆

**Pull request merged**
