### PR TITLE
pretty-print: Do not lose the `$crate` printing flag in `print_tt`

### LINKED ISSUE #62562: serde no longer builds with latest rustc (master)
Looks like something that landed in the commit range https://github.com/rust-lang/rust/compare/0b680cfce544ff9a59d720020e397c4bf3346650...d4e15655092d1bdae79619eb0ff2c3cb5468fc36 broke [building serde](https://travis-ci.com/rust-lang/miri/jobs/214779163):
```
error[E0433]: failed to resolve: unresolved import
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/ast.rs:142:44
    |
142 |     variants: &'a Punctuated<syn::Variant, Token![,]>,
    |                                            ^^^^^^^^^
    |                                            |
    |                                            unresolved import
    |                                            help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
error[E0433]: failed to resolve: unresolved import
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/ast.rs:187:40
    |
187 |     fields: &'a Punctuated<syn::Field, Token![,]>,
    |                                        ^^^^^^^^^
    |                                        |
    |                                        unresolved import
    |                                        help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
I would try to reproduce locally but `rustup-toolchain-install-master` takes many hours to download rustc+libstd currently. (This bug is not yet on nightly, just in master.)

Here's a [prior succeeding build](https://travis-ci.com/rust-lang/miri/jobs/214696148) for reference.

### PR DESCRIPTION
**Pull request by petrochenkov**
https://github.com/rust-lang/rust/pull/62393 had this accidental mistake.

Fixes https://github.com/rust-lang/rust/issues/62562
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by petrochenkov** [comment]
Second commit removes the confusing default.

**Comment by Mark-Simulacrum** [comment]
@bors p=10 (regression fix for core ecosystem crate)

I think it would probably be wise to also eliminate the other "wrappers", e.g. `ident_to_string` which is called sometimes from within the pretty printer and presumably needs the same treatment (or, could, anyway).

r=me with either comments on all of the "wrapper" methods added in the previous PR or them folded away for explicit handling one way or another.

**Comment by gnzlbg** [comment]
@petrochenkov this needs rebasing

**Comment by petrochenkov** [comment]
>I think it would probably be wise to also eliminate the other "wrappers", e.g. ident_to_string which is called sometimes from within the pretty printer and presumably needs the same treatment (or, could, anyway).

Some of those wrappers are commonly used, so I didn't change them, but added some comments instead, `ident_to_string` is renamed.

@bors r=Mark-Simulacrum

**Pull request merged**
