### PR TITLE
Cherry-picking beta-nominated in to beta

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR is a cherry-pick of all beta-nominated commits into the beta branch. This should not be r+'d due to the beta automation currently having to go through a separate path. This should also not be merged until we have discussed this set of PRs at the triage meeting tomorrow.

PRs cherry-picked: 
- #24133 
- #24162 
- #24422 
- #24461 
- #24500 
- #24541 
- #24563 (just the first commit)
- #24636 
- #24646

### CODE REVIEW

**Comment by steveklabnik** [comment]
(And I'll be doing one for documentation stuff later today)

**Comment by brson** [comment]
#24420 only adds unstable API's and has been rejected.

**Comment by brson** [comment]
r=me

**Pull request merged**
