### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #106915 (Only load one CSS theme by default)
 - #108294 (Place binder correctly for arbitrary trait bound suggestion)
 - #108778 (x fmt: Don't print all modified files if there's more than 10)
 - #108854 (feat/refactor: improve errors in case of ident with number at start)
 - #108870 (Fix invalid inlining of reexport of reexport of private item)
 - #108917 (Consider target_family as pal)
 - #108922 (Add auto notification for changes to stable mir)
 - #108929 (Fix typo in span_map.rs)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=106915,108294,108778,108854,108870,108917,108922,108929)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Something is looping...
````
Get:19112 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-34-generic amd64 5.11.0-34.36~20.04.1 [42.0 MB]
Get:19113 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-36-generic amd64 5.11.0-36.40~20.04.1 [42.0 MB]
Get:19114 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-37-generic amd64 5.11.0-37.41~20.04.2 [42.1 MB]
Get:19115 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-38-generic amd64 5.11.0-38.42~20.04.1 [42.1 MB]
Get:19116 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-40-generic amd64 5.11.0-40.44~20.04.2 [49.5 MB]
Get:19117 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-41-generic amd64 5.11.0-41.45~20.04.1 [49.5 MB]
Get:19118 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-43-generic amd64 5.11.0-43.47~20.04.2 [49.5 MB]
Get:19119 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-44-generic amd64 5.11.0-44.48~20.04.2 [49.5 MB]
Get:19120 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.11.0-46-generic amd64 5.11.0-46.51~20.04.1 [49.5 MB]
Get:19121 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-1007-intel amd64 5.13.0-1007.7 [43.3 MB]
Get:19122 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-1008-intel amd64 5.13.0-1008.8 [50.8 MB]
Get:19123 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-1009-intel amd64 5.13.0-1009.9 [51.1 MB]
Get:19124 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-1010-intel amd64 5.13.0-1010.10 [51.1 MB]
Get:19125 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-1011-intel amd64 5.13.0-1011.11 [51.1 MB]
Get:19126 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-1014-intel amd64 5.13.0-1014.15 [51.1 MB]
Get:19127 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-1017-intel amd64 5.13.0-1017.19 [51.1 MB]
Get:19128 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-21-generic amd64 5.13.0-21.21~20.04.1 [50.8 MB]
Get:19129 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-22-generic amd64 5.13.0-22.22~20.04.1 [51.0 MB]
Get:19130 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-23-generic amd64 5.13.0-23.23~20.04.2 [51.0 MB]
Get:19131 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-25-generic amd64 5.13.0-25.26~20.04.1 [51.0 MB]
Get:19132 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-27-generic amd64 5.13.0-27.29~20.04.1 [51.0 MB]
Get:19133 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-28-generic amd64 5.13.0-28.31~20.04.1 [51.1 MB]
Get:19134 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-30-generic amd64 5.13.0-30.33~20.04.1 [51.1 MB]
Get:19135 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-35-generic amd64 5.13.0-35.40~20.04.1 [51.1 MB]
Get:19136 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-extra-5.13.0-37-generic amd64 5.13.0-37.42~20.04.1 [51.0 MB]

````

**Comment by w-flo** [comment]
It looks like all available (?) Ubuntu packages were passed to an `apt-get download` call for some reason.

**Comment by matthiaskrgr** [comment]
@bors treeclosed=100

CI tries to download tenthousands of ubuntu packages on `dist-various2` runner for some reason
https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/ci.20downloads.20all.20ubuntu.20packages

**Comment by matthiaskrgr** [comment]
@bors retry https://github.com/rust-lang/rust/issues/108227
:sparkles:

**Pull request merged**
