### PR TITLE
debuginfo: Stabilize `-Z debug-macros`, `-Z collapse-macro-debuginfo` and `#[collapse_debuginfo]`

### LINKED ISSUE #39153: Code in block passed to macro has line number of macro invocation
It appears that (at least on Linux) if you pass a block of code to a macro, the line numbers for code in the block become the line of the start of the macro invocation rather than the actual lines within the block. This makes debugging hard.

Consider:

```rust
call_macro_defined_somewhere!({
  one();
  two();
  three();
});
```

Line reported for `one()`, `two()` and `three()` is the line that `call_macro_defined_somewhere!({` is on. Expected line number for `one()` to be the line number for `call_macro_defined_somewhere!({` plus one, etc.

### LINKED ISSUE #41743: -Zdebug-macros should either be the default or continue to be available on release-channel compiler
Firefox is built with release-channel Rust, and `-Zdebug-macros` is [needed](https://bugzilla.mozilla.org/show_bug.cgi?id=1360497) to get useful debuggability, crash/panic reporting and profiling attributability for Rust code in Firefox.

According to build-time output, [the option is going to go away from the release-channel compiler](https://github.com/rust-lang/rust/issues/31847). It [seems](https://github.com/rust-lang/rust/issues/39153#issuecomment-297919861) that the option isn't on track to becoming the default, either.

If it's not made the default, please continue keeping the option (under some name) available to release-channel Rust.

### LINKED ISSUE #100758: Tracking Issue for `#[collapse_debuginfo]`
This is a tracking issue for the `#[collapse_debuginfo]` attribute (rust-lang/compiler-team#386).
The feature gate for the issue is `#![feature(collapse_debuginfo)]`.

### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps
- [x] Implement the MCP (#99556)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions
- [ ] Ensure consistency of behaviour with `#[track_caller]` - https://github.com/rust-lang/rust/issues/39153#issuecomment-1191782827

### Implementation history
- Discussed in #39153..
   - ..then proposed in RFC rust-lang/rfcs#2117 where the language team recommended a compiler team MCP..
   - ..and then finally accepted in rust-lang/compiler-team#386.
- Initially implemented in #99556.

### PR DESCRIPTION
**Pull request by petrochenkov**
`-Z debug-macros` is "stabilized" by enabling it by default and removing.

`-Z collapse-macro-debuginfo` is stabilized as `-C collapse-macro-debuginfo`.
It now supports all typical boolean values (`parse_opt_bool`) in addition to just yes/no.

Default value of `collapse_debuginfo` was changed from `false` to `external` (i.e. collapsed if external, not collapsed if local) - https://github.com/rust-lang/rust/issues/100758#issuecomment-1935815625 describes some debugging scenarios that motivate this default as reasonable.
`#[collapse_debuginfo]` attribute without a value is no longer supported to avoid guessing the default.

Stabilization report: https://github.com/rust-lang/rust/pull/120845#issuecomment-1939145242

Closes https://github.com/rust-lang/rust/issues/100758
Closes https://github.com/rust-lang/rust/issues/41743
Closes https://github.com/rust-lang/rust/issues/39153

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @davidtwco @azhogin

**Comment by davidtwco** [comment]
I haven't thoroughly reviewed the changes here but this seems sensible to me at first glance.

**Comment by petrochenkov** [comment]
I removed one fast path optimization for simplicity, so let's also run benchmarks.
@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
Perf changes are noise.
@bors rollup=maybe

**Comment by petrochenkov** [comment]
# Stabilization Report

Before this PR all spans coming from macro definitions were by default collapsed to a single span representing the macro's call site when generating debuginfo.
The option `-Z debug-macros` changed that behavior and preserved all spans in debuginfo without collapsing.

With this PR the `-Z debug-macros` option is removed and the defaults are partially swapped.
By default spans are preserved without collapsing, giving more detailed information during debugging, but only for macros coming from the current crate.
For macros from other crates the spans are still collapsed to a single call site span, this way we don't jump to code of `println!` and other macros from the standard library.

Attributes `#[collapse_debuginfo(yes/no/external)]` and command line options `-C collapse-macro-debuginfo=yes/no/external` (replace `-Z debug-macros`) provide more fine-grained control over collapsing debuginfo spans to call site, when the defaults are insufficient.

### History

https://github.com/rust-lang/rust/issues/41743 identified the problem with detailed debuginfo spans for macros not being available on stable channel.

https://github.com/rust-lang/rfcs/pull/2117 and https://github.com/rust-lang/compiler-team/issues/386 provided the solution for undesirable jumping to sources of `println!` and friends when detailed spans are enabled.
https://github.com/rust-lang/rust/pull/99556 implemented that solution in July 2022.

https://github.com/rust-lang/rust/pull/118903 added detailed tests for the feature and fixed some issues with nested macro calls in December 2023.
https://github.com/rust-lang/rust/pull/119828 added some more fine grained options to the `#[collapse_debuginfo]` attribute, and added a command line flag `-C collapse-macro-debuginfo` for overriding both defaults and attributes as well in January 2024.

### Design

https://github.com/rust-lang/compiler-team/issues/386 gives motivation for not collapsing macros in debuginfo in general, but collapsing some macros in particular.

Comments in https://github.com/rust-lang/rust/issues/100758#issuecomment-1934051974 and below describe some possible debugging scenarios, and make a choice for the default collapsing behavior implemented in this PR.

### Tests

- tests/debuginfo/collapse-debuginfo*
- tests/debuginfo/skip_second_statement*
- tests/debuginfo/lexical-scope-with-macro.rs

### Documentation

Still needs to be written, I'll do it tomorrow.

**Comment by jackh726** [comment]
My only (soft) concern is that `collapse-macro-debuginfo` has not sat for very long (and I guess the no/external/yes options are also fairly new, but I'm less concerned about that). Is it really useful and necessary? What would be the harm of stabilizing `#[collapse_debuginfo]` and removing `-Z debug-macros` without stabilizing `-Z collapse-macro-debuginfo`?

Also curious how often these features actually get used, but that doesn't need to block this at all since it does obviously seem useful.

**Comment by azhogin** [comment]
Could it be better to change cmd/attr table (unspecified + unspecified = if-ext) instead of changing default attribute to `external`?

**Comment by petrochenkov** [comment]
@jackh726
> My only (soft) concern is that `collapse-macro-debuginfo` has not sat for very long (and I guess the no/external/yes options are also fairly new, but I'm less concerned about that).

`-C collapse-macro-debuginfo` is basically a rename of `-Z debug-macros`, with a different default and more fine-grained options, so it's not entirely new.

>Is it really useful and necessary? What would be the harm of stabilizing `#[collapse_debuginfo]` and removing `-Z debug-macros` without stabilizing `-Z collapse-macro-debuginfo`?

Like  `-Z debug-macros`, the `-Z collapse-macro-debuginfo` command line flag helps to enable more (or less) debuginfo for code that you cannot edit to add the `#[collapse_debuginfo]` attributes.
I tried to list some possible debugging scenarios in https://github.com/rust-lang/rust/issues/100758#issuecomment-1935815625.

I suspect that it's actually more important to stabilize the flag, than the attributes, because the flag can resolve any issues with a specific debugging session, while the attributes are more about setting defaults (and are not very likely to be widely adopted by third-party macro authors).

**Comment by petrochenkov** [comment]
@azhogin 
> Could it be better to change cmd/attr table (unspecified + unspecified = if-ext) instead of changing default attribute to `external`? cmd_attr_table

The end result is the same, no?
I think the actual implementation in `fn get_collapse_debuginfo` is still working as you are explaining.

**Comment by apiraino** [comment]
switching review flag to waiting on Vadim for a rebase (then feel free to request a review when it's good)

@rustbot author

**Comment by petrochenkov** [comment]
I've rebased, but this still needs an approval from at least 2 compiler team members (ping @estebank @matthewjasper @pnkfelix @wesleywiser).

**Comment by ehuss** [comment]
Has the lang team approved the new attribute?

**Comment by petrochenkov** [comment]
@ehuss
No, should it?
The attribute only has effect on details of produced binaries, but not on anything else in the language.

**Comment by ehuss** [comment]
It has been the policy as long as I'm aware that the lang team is responsible for attributes. For example, they recently approved the `debugger_visualizer` attribute. I would not expect them to have any concerns here, but I think we should keep with the precedent unless there is an explicit decision by them to change it.

**Comment by petrochenkov** [comment]
Okay, I've lang nominated this PR.

**Comment by estebank** [comment]
> For macros from other crates the spans are still collapsed to a single call site span, this way we don't jump to code of println! and other macros from the standard library.

@petrochenkov would it make sense to make `--verbose` imply the current behavior of `-Zdebug-macros` for foreign macros? (not necessarily as part of this PR).

**Comment by davidtwco** [comment]
> > For macros from other crates the spans are still collapsed to a single call site span, this way we don't jump to code of println! and other macros from the standard library.
> 
> @petrochenkov would it make sense to make `--verbose` imply the current behavior of `-Zdebug-macros` for foreign macros? (not necessarily as part of this PR).

I feel like this would be quite unintuitive, I expect `--verbose` to give me more output, but not necessarily change what is produced.

**Comment by traviscross** [comment]
@rfcbot poll lang Are we OK with this moving forward?

**Comment by petrochenkov** [comment]
> One question I had here: This is affecting spans in debug info _only_? It doesn't affect things like the spans that a proc macro would see?

Debuginfo only, proc macros are not affected.

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by joshtriplett** [comment]
Forgot that we can't do a second rfcbot merge after one has already happened.

**Comment by joshtriplett** [comment]
@rfcbot poll lang Are we fine with accepting these stabilizations?

**Comment by joshtriplett** [comment]
I am now baffled by the state rfcbot is in. Doing this manually:

@rust-lang/lang, are we OK with this stabilization?

[x] @joshtriplett
[ ] @nikomatsakis
[ ] @pnkfelix
[ ] @scottmcm 
[ ] @tmandry

**Comment by petrochenkov** [comment]
I'm going to nominate this again because the poll in https://github.com/rust-lang/rust/pull/120845#issuecomment-2048108744 doesn't show up on any dashboard, so the remaining lang team people will probably never see it.

**Comment by nikomatsakis** [comment]
(Thanks @ehuss for raising this to our attention, I concur that stabilizing (or adding, changing, etc) attributes is something for the lang team.

**Comment by tmandry** [comment]
> Default value of `collapse_debuginfo` was changed from `false` to `external` (i.e. collapsed if external, not collapsed if local) - [#100758 (comment)](https://github.com/rust-lang/rust/issues/100758#issuecomment-1935815625) describes some debugging scenarios that motivate this default as reasonable. `#[collapse_debuginfo]` attribute without a value is no longer supported to avoid guessing the default.

This is contradictory. Is a default supported or not?

**Comment by petrochenkov** [comment]
@tmandry 
I meant the default value when the attribute is not used at all.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the lang triage call today.  People seemed to agree this was, as a policy matter, a lang issue.  Similarly, and as represented in the poll above, people were fine approving in this case and happy to see this move forward.

This is good to go from the lang side, so we can unnominate.

**Comment by apiraino** [comment]
ok if I understand the ball is back to t-compiler for a final review (pls @petrochenkov a rebase when you have a chance, thanks :pray: )

@rustbot review

**Review by oli-obk — APPROVED** [review]
would've preferred the behavior changes to be in a different PR or commit than the stabilization PR, but I think I reviewed everything properly

r=me after a rebase

**Comment by ehuss** [comment]
@bors r-

CI isn't passing.

**Comment by petrochenkov** [comment]
`--pass check` failed me for the first time in years.
Updated the test.
@bors r=oli-obk

**Comment by philipc** [comment]
This has broken a test in backtrace (https://github.com/rust-lang/backtrace-rs/issues/617). The `collapse_debuginfo` attribute can be used to fix it.

The debuginfo for [line 11](https://github.com/rust-lang/backtrace-rs/blob/e15130618237eb3e2d4b622549f9647b4c1d9ca3/tests/accuracy/main.rs#L11) is now line 11 instead of the caller, as expected. However, the result of the `line!` (called via `pos!`) is still the caller. Is it intentional that `line!` is unaffected? It's not clear cut to me how this should work, so I want to check.

**Comment by petrochenkov** [comment]
@philipc 
Test suite in this repo has the same test - `tests/ui/debuginfo/backtrace-dylib-dep.rs`, I updated it to preserve the previous behavior.
The test relied on specific lines being emitted into debuginfo, and since we are changing the debuginfo emitted by default behavior of such tests may also change.

**Comment by petrochenkov** [comment]
`file!()` and `line!()` are not defined in the current crate, so they are collapsed by default now, unlike `pos!()` and `check!()` defined in the current crate.

**Comment by workingjubilee** [comment]
Breaking the test was fine if it can still be configured to pass. I'm glad that we moved that test into rustc's suite, so that it can be kept current with current defaults. I'm not sure that I want to remove the copy of the test from the backtrace suite yet, but I can just copy petrochenkov's changes to fix it.

**Pull request merged**
