### PR TITLE
Don't hide ICEs from previous incremental compiles

### LINKED ISSUE #65401: Deferred ICEs (i.e. delay_span_bug) are not preserved by incremental.
When compiling a `delay_span_bug` testcase (e.g. the last snippet in https://github.com/rust-lang/rust/issues/63154#issuecomment-541592381 on the current nightly, or any of the other examples in that issue on older compilers) with `-Cincremental` (or Cargo which does that by default), only the initial run will ICE.

Subsequent runs will succeed without an ICE, in the absence of any regular errors. However, changing the relevant code (e.g. adding a space) can cause the query that calls `delay_span_bug` to be recomputed and bring the ICE back.

IIUC, incremental compilation stores diagnostics and replays them on subsequent runs, but that appears to not apply to `delay_span_bug` ICEs.

cc @michaelwoerister

### PR DESCRIPTION
**Pull request by traxys**
I think this fixes #65401, the compiler does not fail to ICE after the first compilation, tested on the last snippet of [this comment](https://github.com/rust-lang/rust/issues/63154#issuecomment-541592381).
I am not very sure of the fix as I don't understand much of the structure of the compiler.

### CODE REVIEW

**Comment by traxys** [comment]
If I understood the issue correctly, the test should be that when `rustc -Cincremental` is run for the second time the compilation should ICE again, which is currently not the case. I don't know how to test that something should ICE when run twice

**Comment by jackh726** [comment]
Here's an example of a test specifically for incremental compilation: https://github.com/rust-lang/rust/pull/60697

**Comment by traxys** [comment]
The problem is now on how can I make the compiler ICE ?

**Comment by traxys** [comment]
Apart from needing the test, is the fix correct ?

**Comment by michaelwoerister** [comment]
The fix looks correct to me. Thanks, @traxys!

**Comment by michaelwoerister** [comment]
Here is some documentation on using "revisions" for test cases: https://rust-lang.github.io/rustc-guide/tests/adding.html#revisions

**Comment by pnkfelix** [comment]
In addition to @michaelwoerister 's point about using "revisions" for test cases, we also need to check about whether there is a good way to cause the compiler to ICE in a *reliable* fashion (i.e., something that we could put in a test suite and rely on going forward).

`#[rustc_error]` might work as a way to get the compiler to ICE, perhaps if you combine it with `-Z treat-err-as-bug`; but I think in this case you specifically need something that calls `delay_span_bug`, right? I meant to look at this last week but then got distracted by linker bug!

**Comment by traxys** [comment]
I tried the `#[rustc_error]` with `-Z treat-err-as-bug` and indeed given that it does not trigger a `delay_span_bug` it does not exhibit the bug on current `rustc`

**Comment by pnkfelix** [comment]
@traxys okay. I think the way to go here would be to extend the `rustc_error` attribute to be able to generate a `delayed_span_bug` instead of always causing an immediate fatal error.

E.g. something where `#[rustc_error]` would behave the same as today, but `#[rustc_error(delayed)]` would call `delayed_span_bug` instead.

If you want to have a go at implementing this yourself, the main places to look are here:

https://github.com/rust-lang/rust/blob/d3d28a49209a21628fda0245b631e5fc3465be1a/src/librustc_codegen_utils/lib.rs#L30-L40

(which implements the actual handling of the attribute)

and here:

https://github.com/rust-lang/rust/blob/d3d28a49209a21628fda0245b631e5fc3465be1a/src/libsyntax/feature_gate/builtin_attrs.rs#L540

which implements the initial check that `#[rustc_error]` always takes the form of a single `Word` (namely, `rustc_error` and not `rustc_error(stuff)`).

Based on my reading of the definition of `template!`, here:

https://github.com/rust-lang/rust/blob/d3d28a49209a21628fda0245b631e5fc3465be1a/src/libsyntax/feature_gate/builtin_attrs.rs#L113-L116

it seems like you should be able to get this going initially by just replacing `Word` up above (in `builtin_attrs.rs`) with `Word, List: "delayed"` and work your way out from there.

**Comment by traxys** [comment]
Should I do this in this PR or in another PR ?

**Comment by pnkfelix** [comment]
> Should I do this in this PR or in another PR ?

I'd say go ahead and do it in this PR, but as a separate commit.

(If this `#[rustc_error(delayed)]` thing were a more general feature, or if I expected it to require a significant amount of code, then I would argue for a separate PR. But I don't expect it to see too much usage outside of testing this PR.)

**Comment by traxys** [comment]
@pnkfelix I added something that seems to be correct, the only problem is that it does not trigger the issue on current rustc, and I don't know why, I need to look in more details

**Comment by traxys** [comment]
As @eddyb and @pnkfelix suggested, because writing a test is complex, I only left the fix and the test will be provided in another PR

**Comment by michaelwoerister** [comment]
That's OK too. The changes are straightforward. Thanks for your work, @traxys!

@bors r+

**Comment by varkor** [comment]
> we also need to check about whether there is a good way to cause the compiler to ICE in a reliable fashion

```rust
fn main() {
	break rust;
}
```

ICEs "reliably", as long as this joke isn't removed, though it doesn't use `delay_span_bug`, so it's still probably not appropriate, without some adjustment.

**Pull request merged**
