### PR TITLE
Tentatively inline(always) the trivial Into::into

### PR DESCRIPTION
**Pull request by SoniEx2**
#100733 looked exciting, maybe this also does something.

### CODE REVIEW

**Comment by SoniEx2** [comment]
actually after some discussion it seems this should not be done, because `#[inline(always)]` is bottom-up. some folks suggested adding a pass which can inline these trivial forwarding functions instead. tho huh, really didn't expect those results.

**Comment by scottmcm** [comment]
Consider trying this with just `#[inline]` instead of `#[inline(always)]`.  That might let LLVM use its heuristics to avoid the more painful cases here.

**Comment by SoniEx2** [comment]
we can try... but ideally this would inline as much as the underlying `From`, which is only possible if there was a pass to forward these kinds of functions... (then an `#[inline(always)]` in a `From` would automatically benefit the relevant `Into`.)

**Comment by scottmcm** [comment]
Re-perfing without the `always`

@bors try @rust-timer queue

**Comment by SoniEx2** [comment]
we wanna say that looks worse tho we're not good at reading these. would be nice to have a proper top-down inlining pass so that `#[inline]` on From means more than nothing.

**Comment by memoryruins** [comment]
For similar concerns about `inline(always)` on `into` from a couple years ago, <https://github.com/rust-lang/rust/pull/74645#issuecomment-666302460>, which contains an example of the bottom-up behavior greatly increasing code size.

**Comment by SoniEx2** [comment]
ugh, we wish we could somehow make the compiler simply "resolve" this `Into::into` impl as the corresponding `From::from` call. like alias `fn into = fn from` somehow. (that would work yeah? might make some weird error messages if it resolves to this impl, and also `<U as Into<T>>::into == <T as From<U>>::from` would be true... whether those things matter, we don't know.)

or like. anything that would make this easier to pull off.

**Comment by SoniEx2** [comment]
we'll be closing this for now we guess.

**Comment by nikic** [comment]
I think we should reopen this one (the `#[inline]` variant, not `#[inline(always)]`). The perf result was mostly positive, including on bootstrap timings. I believe we do want this `from()` wrapper to be instantiated in all CGUs, because in most cases the `from()` implementation is trivial as well, and this is important for looking through abstractions. `into()` shows up a lot in https://github.com/rust-lang/rust/issues/102539#issuecomment-1264398807.

**Pull request closed without merging**
