### PR TITLE
Move the HIR CFG to `rustc_ast_borrowck`

### PR DESCRIPTION
**Pull request by matthewjasper**
No new code should be using it.

### CODE REVIEW

**Comment by Centril** [comment]
This is great! 🎉 -- Cannot wait to ditch `::cfg`.

r? @Centril @bors r+

**Comment by llogiq** [comment]
So...how do we access `librustc_ast_borrowck` from clippy? Changing the `use` statement in our `cognitive_complexity` lint to `use librustc_ast_borrowck::cfg::CFG` doesn't work because cargo doesn't find `librustc_ast_borrowck`.

**Comment by lzutao** [comment]
Probably just add `extern crate rustc_ast_borrowck;` in
https://github.com/rust-lang/rust-clippy/blob/f30bf69ec7af4366e64916f32566f3a894edd593/clippy_lints/src/lib.rs#L22-L38
I tried this earlier but I cannot sort out this error:
```rust
% cargo check --all --all-targets --                                                                                                                                                                                                                                      
   Compiling clippy-mini-macro-test v0.2.0 (/home/lzutao/forked/rust/clippy/mini-macro)                                                                                                                                                                                         
   Compiling clippy_lints v0.0.212 (/home/lzutao/forked/rust/clippy/clippy_lints)                                                                                                                                                                                               
error[E0616]: field `graph` of struct `rustc_ast_borrowck::cfg::CFG` is private                                                                                                                                                                                                 
  --> clippy_lints/src/cognitive_complexity.rs:51:17                                                                                                                                                                                                                            
   |                                                                                                                                                                                                                                                                            
51 |         let n = cfg.graph.len_nodes() as u64;                                                                                                                                                                                                                              
   |                 ^^^^^^^^^                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                
error[E0616]: field `graph` of struct `rustc_ast_borrowck::cfg::CFG` is private                                                                                                                                                                                                 
  --> clippy_lints/src/cognitive_complexity.rs:52:17                                                                                                                                                                                                                            
   |                                                                                                                                                                                                                                                                            
52 |         let e = cfg.graph.len_edges() as u64;                                                                                                                                                                                                                              
   |                 ^^^^^^^^^                                                                                                                                                                                                                                                  
```

**Comment by matthewjasper** [comment]
I'll open a PR to remove the use of `CFG` from clippy, it's not going to be around for that much longer.

**Pull request merged**
