### PR TITLE
Reverse Timsort scan direction

### PR DESCRIPTION
**Pull request by Voultapher**
Another PR in the series of stable sort improvements. Best reviewed by looking at the individual commits.

The main perf gain here is for fully ascending (sorted) or reversed inputs for cheap to compare types such as `u64`, these see a ~1.5x speedup.

timsort_evo2_hot_u64_10k

timsort_evo2_hot_string_10k

Types such as string with indirect pre-fetching see only minor changes. Further speedups are planned in future PRs so, I wouldn't spend too much time for benchmarks here.

### CODE REVIEW

**Comment by Voultapher** [comment]
r? thomcc

**Comment by thomcc** [comment]
@Voultapher Not sure. It could be noise, but it looks like the regressions are more significant than the improvements. Note that there are 4 primary benchmarks regressed vs 1 secondary (e.g. synthetic) benchmark which improved. I'll try more runs in case it's noise, but it's worth investigating.

@bors try @rust-timer queue runs=5

**Comment by Voultapher** [comment]
@thomcc looking at the two runs, the second one has one primary improvement of 0.5% and one primary regression of 0.5% in the same crate, as well as one further regression of 0.3% in the same crate. The bootstrap timings look all over the place. `proc_macro` regressed by 2.3% in the second run, but improved by 1.4% in the first run. `rustc_builtin_macros` regressed by 0.7% or 3.3%. It notes the noise 1-3%, and pretty much everything falls within this range. I'd argue this change has no significant detrimental effect.

**Comment by thomcc** [comment]
Hm, fair enough.

**Comment by Voultapher** [comment]
One open question is, how much sort performance even influences compiler performance. As IIUC this benchmark suite is focused on compiler performance only.

**Comment by thomcc** [comment]
It is. The compiler definitely performs sorts though, and it wouldn't surprise me if some were in sensitive positions.

**Comment by thomcc** [comment]
Okay, it took a jillion years but I am convinced of this code's correctness. Thanks.

@bors r+

**Comment by rylev** [comment]
Regressions are small enough that I think we don't need to investigate this closely.

@rustbot label: perf-regression-triaged

**Pull request merged**
