### PR TITLE
Fix null synthetic_implementors error

### LINKED ISSUE #68584: JavaScript `TypeError: synthetic_implementors is null` error on some trait pages
For example on the nightly docs https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html:

```
TypeError: synthetic_implementors is null main1.42.0.js:1:34607
    register_implementors https://doc.rust-lang.org/nightly/main1.42.0.js:1
    <anonymous> https://doc.rust-lang.org/nightly/main1.42.0.js:1
    <anonymous> https://doc.rust-lang.org/nightly/main1.42.0.js:7
ReferenceError: addSearchOptions is not defined search-index1.42.0.js:7:1
    <anonymous> https://doc.rust-lang.org/nightly/search-index1.42.0.js:7
```

Additionally most of the documentation doesn't load (but not every time):

image

I suspect this was caused by #68192 (cc @GuillaumeGomez).

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #68584.

r? @ollie27 

cc @kinnison

### CODE REVIEW

**Comment by ollie27** [comment]
Nice, r=me once the tidy error has been fixed.

Nominating for beta backport because it looks like it's just been branched.

**Comment by Centril** [comment]
@ollie27 btw, don't forget to add a team label when adding beta-nominated. :)

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by Mark-Simulacrum** [comment]
@rust-lang/rustdoc If this is to get into beta in time (i.e., before beta becomes stable) then it needs to be approved roughly in the next 3 days.

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum I add the tag for it.

**Pull request merged**
