### PR TITLE
Fix references to `ControlFlow` in docs

### PR DESCRIPTION
**Pull request by jhpratt**
The `Iterator::for_each` method previously stated that it was not possible to use `break` and `continue` in it — this has been updated to acknowledge the stabilization of `ControlFlow`. Additionally, `ControlFlow` was referred to as `crate::ops::ControlFlow` which is not the correct path for an end user.

r? @jyn514

### CODE REVIEW

**Comment by the8472** [comment]
I don't see how that relates to `for_each`, barring panics it unconditionally runs to completion, `ControlFlow` doesn't change that.

**Comment by jhpratt** [comment]
Returning `ControlFlow::Break(())` wouldn't terminate early? That seems unexpected.

(No I didn't try it. I made an assumption)

**Comment by the8472** [comment]
It requires a `()` return type for the closure. You need `try_for_each` or `try_fold` if you want to return early.

**Comment by jhpratt** [comment]
Ah, right. Sometimes I miss the obvious. I'll revert that bit of the commit, leaving the fix to the path elsewhere.

**Comment by jyn514** [comment]
@jhpratt is there a reason you picked me particularly to review? I'm not on the libs team.

**Comment by jyn514** [comment]
That said, this looks good to me :)

@bors r+ rollup

**Comment by jhpratt** [comment]
I thought that you've done stuff with docs in the past. Not that the reviewer really matters here admittedly.

**Comment by jyn514** [comment]
I mostly work on rustdoc; different sort of docs :P

**Comment by jhpratt** [comment]
I had the right idea 😂 Good to know for the future.

**Pull request merged**
