### PR TITLE
update unimplemented! docs

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
For #42628 (updating docs from changes from #42155).

Initial changes made to make `unimplemented!` doc comments look more like `unreachable!` and remove statement about the panic message.

r? @steveklabnik

### CODE REVIEW

**Comment by aidanhs** [comment]
Thanks for the PR @MarkMcCaskey! We'll check in now and again to make sure @steveklabnik or another reviewer gets to this soon.

**Comment by aidanhs** [comment]
(in the meantime, I note there are merge conflicts - it'd be great if you could resolve those)

**Comment by MarkMcCaskey** [comment]
Okay!  Sorry about the long delay.  Should be fine now.

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thank you!

**Pull request merged**
