### PR TITLE
std: link to liballoc_system if compiled without the jemalloc feature

### LINKED ISSUE #36501: Error `cargo build`ing `std` as a dylib
Or should `cargo build`ing `std` only produce a .rlib?

Now that #35021 landed and compiler-rt intrinsics are built as part of the std crate dependencies,
one can (cross) compile binaries if the `alloc_system` (or `alloc_jemalloc`), `panic_unwind` and
`std` crates are listed under the crate Cargo.toml:

```
$ cargo new --bin hello

$ cd hello

$ edit src/main.rs && cat src/main.rs
#![feature(alloc_system)]

extern crate alloc_system;

fn main() {
    println!("Hello, world!");
}

$ edit Cargo.toml && cat Cargo.toml
[package]
name = "hello"

[dependencies]
alloc_syste = { path = "$(rustc --print sysroot)/lib/rustlib/src/rust/src/liballoc_system" }
panic_unwind = { path = "$(rustc --print sysroot)/lib/rustlib/src/rust/src/libpanic_unwind" }
std = { path = "$(rustc --print sysroot)/lib/rustlib/src/rust/src/libstd" }

# if alloc_jemalloc is used
# [features]
# default = ["std/jemalloc"]

$ cargo build --target $CROSS
```

**if and only if** the Cargo.toml of the std crate is modified as follows

``` diff
 [lib]
 name = "std"
 path = "lib.rs"
-crate-type = ["dylib", "rlib"]

 [dependencies]
 alloc = { path = "../liballoc" }
```

to not build a dylib. Without this change `cargo build`ing `hello` fails with:

```
$ cargo build --target $CROSS
     Running `rustc $sysroot/lib/rustlib/src/rust/src/libstd/lib.rs --crate-name std --crate-type dylib --crate-type rlib -C prefer-dynamic -g -C metadata=7a8ef155232f363e --out-dir $PWD/target/$CROSS/debug/deps --emit=dep-info,link --target $CROSS -L dependency=$PWD/target/$CROSS/debug/deps --extern core=$PWD/target/$CROSS/debug/deps/libcore.rlib --extern compiler_builtins=$PWD/target/$CROSS/debug/deps/libcompiler_builtins.rlib --extern rand=$PWD/target/$CROSS/debug/deps/librand.rlib --extern panic_abort=$PWD/target/$CROSS/debug/deps/libpanic_abort.rlib --extern libc=$PWD/target/$CROSS/debug/deps/liblibc.rlib --extern rustc_unicode=$PWD/target/$CROSS/debug/deps/librustc_unicode.rlib --extern alloc=$PWD/target/$CROSS/debug/deps/liballoc.rlib --extern alloc_system=$PWD/target/$CROSS/debug/deps/liballoc_system.rlib --extern collections=$PWD/target/$CROSS/debug/deps/libcollections.rlib --extern panic_unwind=$PWD/target/$CROSS/debug/deps/libpanic_unwind.rlib --extern unwind=$PWD/target/$CROSS/debug/deps/libunwind.rlib --cfg cargobuild -l dl -l rt -l pthread -L native=$PWD/target/$CROSS/debug/build/compiler_builtins-31a1189c65ac3d55/out`
warning: ar: `u' modifier ignored since `D' is the default (see `U')
   Compiling std v0.0.0 (file://$sysroot/lib/rustlib/src/rust/src/libstd)
error[E0463]: can't find crate for `alloc_jemalloc`

error: aborting due to previous error

error: Could not compile `std`.
```

during the compilation of the `std` crate. (On that note, I'm sure why building `std` as a dylib
fails? Is it because rustc injects a `extern crate alloc_jemalloc` into `std` source when compiling
a dylib but alloc_jemalloc is an optional dependency of `std` that's not build (the feature is
disabled) in this example?)

I discussed this with @alexcrichton and we were wondering if we should modify the std crate to only
compile the rlib to make this case work out of the box. And then hack `bootstrap` to force it to build
`std` as dylib because it is needed to link rustc.

cc @Ericson2314 I don't how/if this change would affect your Cargo+std RFC. (Probably not?)

### PR DESCRIPTION
**Pull request by japaric**
fixes #36501

r? @alexcrichton

### CODE REVIEW

**Comment by japaric** [comment]
With this and #37974, I can CROSS compile std using Cargo and the following Cargo.toml:

``` toml
[package]

[dependencies.alloc_system]
path = "/shared/rust/checkouts/abort/src/liballoc_system"

[dependencies.panic_abort]
path = "/shared/rust/checkouts/abort/src/libpanic_abort"

[dependencies.std]
path = "/shared/rust/checkouts/abort/src/libstd"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
```

without any change to rust-src.

**Comment by alexcrichton** [comment]
@bors: r+ 

Awesome progress!

**Comment by japaric** [comment]
This is blocking Xargo from being able to compile the `std` crate and I have no idea why those tests don't pass on 32-bit mac. (They pass on Linux)

**Comment by mzji** [comment]
@japaric Maybe a fault of tarvis-ci: [Build delays in our OS X infrastructure](https://www.traviscistatus.com/incidents/nq0sf0srvx8s)

**Comment by alexcrichton** [comment]
Maybe this is affected by how tests are run? Maybe nondeterministic? I'm not sure :(

**Comment by japaric** [comment]
> Maybe nondeterministic?

Want to retry?

(or let's 🔥jem🔥lloc🔥)

**Comment by alexcrichton** [comment]
Hm if it is nondeterministic I'd be wary of landing b/c then it'd just turn into a problem I'd have to debug later... If you try running a few times this surely never reproduces on Linux?

**Comment by alexcrichton** [comment]
Note that the nondeterminism is just a wild guess, I don't actually know what the problem is.

**Comment by HybridEidolon** [comment]
I built this locally for `x86_64-apple-darwin` and encountered the issue where it links `alloc_system` where it shouldn't in `run-pass/allocator-override.rs` and `run-pass/allocator-default.rs`, as it appears in the bors build error, so it is not a nondeterministic issue.

**Comment by HybridEidolon** [comment]
This only fails on makefiles build for me; the tests build and run successfully using rustbuild, contingent on stage2 std being build with `--cfg 'feature="jmalloc"'`. Makefiles seem to not pass that argument to std build step _but only on darwin targets_. Since it's not there, libstd is built with a dependency on alloc_system with these changes, resulting in the multiple allocator crates panic. _Why_ it does that I'm not sure, I'm no compiler hacker. Seems like there is a pre-existing inconsistency in the build systems.

**Comment by japaric** [comment]
That patch totally makes sense. Thanks for investigating, @HybridEidolon!

@bors r=alexcrichton

**Comment by HybridEidolon** [comment]
This isn't going to work on targets that do actually use alloc_system. libstd will have an alloc_system dependency and crates that override the default allocator and are not `no_std` will result in an allocator collision during compile. I am not sure this is the right approach anymore.

**Comment by aidanhs** [comment]
The new logic seems wrong. As @HybridEidolon says, if you apply this patch disabling jemalloc means you can never drop in another allocator crate because std has a hardcoded dependency on liballoc_system. That's a bit sad.

Ideally I think it'd be nice to specify an allocator preference in Cargo.toml/cargo command line (used when an allocator must be picked i.e. dylibs, not rlibs), but since that's not possible we can make do with a force_alloc_system feature (which, as before, locks you into a single allocator for stage0). Crucially, this feature is distinct from the jemalloc feature (in the previous PR) - we don't want someone to be forced into alloc_system just for disabling jemalloc!

See #39086

**Comment by alexcrichton** [comment]
I'm going to close this due to inactivity, but it'd be great to land a fix for this still!

**Pull request closed without merging**
