### PR TITLE
Replace assert with assert_eq

### PR DESCRIPTION
**Pull request by ohsayan**
Use `assert_eq!` instead of `assert!` for the tests

### CODE REVIEW

**Comment by sntdevco** [comment]
@Centril Checks complete

**Comment by lzutao** [comment]
@sntdevco You should use `git revert` to revert commit rather then re-adding deleted lines.

**Comment by sntdevco** [comment]
> @sntdevco You should use `git revert` to revert commit rather then re-adding deleted lines.

Was in a hurry. Will revert straight away!

**Comment by Centril** [comment]
I believe the first commit of this PR, before changes to it, was merged in https://github.com/rust-lang/rust/pull/59151 so I'll close this as done.

**Pull request closed without merging**
