### PR TITLE
Box the `MacCall` in various types.

### PR DESCRIPTION
**Pull request by nnethercote**
r? @spastorino

### CODE REVIEW

**Comment by spastorino** [comment]
@nnethercote by looking at the changes it did look good to me but by looking at perf results I'm not sure what were you expecting to see but on primary and secondary benchmarks doesn't seem to be big wins. Although I see some moderate improvements on bootstrapping.

Anyway, what are your thoughts Nick?.

**Comment by nnethercote** [comment]
It's performance neutral at the moment. There are two reasons I want to merge this. First, we just tend to box larger structs in the AST anyway. Second, `Expr` is the by far the most important AST type, instantiated the most, and while this change alone isn't enough to shrink it, it is necessary, because `MacCall` is one of several equally large `ExprKind` variants.

**Comment by nnethercote** [comment]
Also, `Ty` is pretty important and this is step one (of 2) for shrinking it from 96 bytes to 64 bytes.

**Comment by nnethercote** [comment]
I rebased to fix the conflicts.

**Comment by spastorino** [comment]
ohh merge conflicts again, r=me after you fix those.

**Comment by nnethercote** [comment]
I fixed the conflicts.

@bors r=spastorino

**Pull request merged**
