### PR TITLE
Use a more efficient iteration order for backward dataflow

### PR DESCRIPTION
**Pull request by ecstatic-morse**
This applies the same basic principle as #62062 to the reverse dataflow analysis used to compute liveness information. It is functionally equivalent, except that post-order is used instead of reverse post-order.

In the long-term, `BitDenotation` should probably be extended to support both forward and backward dataflow, but there's some more work needed to get to that point.

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Sorry, I forgot to remove the debug line from this one.

**Comment by Centril** [comment]
@rust-timer build 56b7200c037e2a958f7d907e778b87e58beb7079

**Comment by ecstatic-morse** [comment]
This does substantially reduce the number of iterations, it's just that backward dataflow is only used for dataflow analysis (I should have checked this before I requested a perf run, although #62062 needed one anyway). Here are the results from running the tests in `src/ui/run-pass/generators` before and after this change.

Before:
```
DEBUG 2019-06-27T00:38:26Z: rustc_mir::util::liveness: Liveness dataflow converged after 17 iterations (30.76923076923077% overhead)
DEBUG 2019-06-27T00:38:27Z: rustc_mir::util::liveness: Liveness dataflow converged after 37 iterations (85% overhead)
DEBUG 2019-06-27T00:38:27Z: rustc_mir::util::liveness: Liveness dataflow converged after 37 iterations (85% overhead)
DEBUG 2019-06-27T00:38:27Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (16.666666666666664% overhead)
DEBUG 2019-06-27T00:38:27Z: rustc_mir::util::liveness: Liveness dataflow converged after 24 iterations (60% overhead)
DEBUG 2019-06-27T00:38:27Z: rustc_mir::util::liveness: Liveness dataflow converged after 13 iterations (44.44444444444444% overhead)
DEBUG 2019-06-27T00:38:27Z: rustc_mir::util::liveness: Liveness dataflow converged after 13 iterations (44.44444444444444% overhead)
DEBUG 2019-06-27T00:38:27Z: rustc_mir::util::liveness: Liveness dataflow converged after 23 iterations (53.333333333333336% overhead)
DEBUG 2019-06-27T00:38:28Z: rustc_mir::util::liveness: Liveness dataflow converged after 96 iterations (50% overhead)
DEBUG 2019-06-27T00:38:29Z: rustc_mir::util::liveness: Liveness dataflow converged after 8 iterations (14.285714285714285% overhead)
DEBUG 2019-06-27T00:38:29Z: rustc_mir::util::liveness: Liveness dataflow converged after 4 iterations (0% overhead)
DEBUG 2019-06-27T00:38:29Z: rustc_mir::util::liveness: Liveness dataflow converged after 8 iterations (14.285714285714285% overhead)
DEBUG 2019-06-27T00:38:30Z: rustc_mir::util::liveness: Liveness dataflow converged after 13 iterations (30% overhead)
DEBUG 2019-06-27T00:38:30Z: rustc_mir::util::liveness: Liveness dataflow converged after 32 iterations (45.45454545454545% overhead)
DEBUG 2019-06-27T00:38:30Z: rustc_mir::util::liveness: Liveness dataflow converged after 10 iterations (25% overhead)
DEBUG 2019-06-27T00:38:30Z: rustc_mir::util::liveness: Liveness dataflow converged after 18 iterations (20% overhead)
DEBUG 2019-06-27T00:38:31Z: rustc_mir::util::liveness: Liveness dataflow converged after 15 iterations (50% overhead)
DEBUG 2019-06-27T00:38:31Z: rustc_mir::util::liveness: Liveness dataflow converged after 9 iterations (28.57142857142857% overhead)
DEBUG 2019-06-27T00:38:31Z: rustc_mir::util::liveness: Liveness dataflow converged after 30 iterations (36.36363636363637% overhead)
DEBUG 2019-06-27T00:38:32Z: rustc_mir::util::liveness: Liveness dataflow converged after 24 iterations (60% overhead)
DEBUG 2019-06-27T00:38:32Z: rustc_mir::util::liveness: Liveness dataflow converged after 24 iterations (60% overhead)
DEBUG 2019-06-27T00:38:32Z: rustc_mir::util::liveness: Liveness dataflow converged after 10 iterations (25% overhead)
DEBUG 2019-06-27T00:38:32Z: rustc_mir::util::liveness: Liveness dataflow converged after 37 iterations (60.86956521739131% overhead)
DEBUG 2019-06-27T00:38:33Z: rustc_mir::util::liveness: Liveness dataflow converged after 24 iterations (33.33333333333333% overhead)
DEBUG 2019-06-27T00:38:33Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (16.666666666666664% overhead)
DEBUG 2019-06-27T00:38:33Z: rustc_mir::util::liveness: Liveness dataflow converged after 10 iterations (25% overhead)
DEBUG 2019-06-27T00:38:34Z: rustc_mir::util::liveness: Liveness dataflow converged after 52 iterations (36.84210526315789% overhead)
DEBUG 2019-06-27T00:38:34Z: rustc_mir::util::liveness: Liveness dataflow converged after 25 iterations (92.3076923076923% overhead)
DEBUG 2019-06-27T00:38:34Z: rustc_mir::util::liveness: Liveness dataflow converged after 19 iterations (35.714285714285715% overhead)
DEBUG 2019-06-27T00:38:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 12 iterations (33.33333333333333% overhead)
DEBUG 2019-06-27T00:38:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (16.666666666666664% overhead)
DEBUG 2019-06-27T00:38:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (16.666666666666664% overhead)
DEBUG 2019-06-27T00:38:36Z: rustc_mir::util::liveness: Liveness dataflow converged after 10 iterations (25% overhead)
DEBUG 2019-06-27T00:38:37Z: rustc_mir::util::liveness: Liveness dataflow converged after 24 iterations (41.17647058823529% overhead)
DEBUG 2019-06-27T00:38:37Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (16.666666666666664% overhead)
DEBUG 2019-06-27T00:38:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 21 iterations (50% overhead)
DEBUG 2019-06-27T00:38:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (40% overhead)
```

After:
```
DEBUG 2019-06-27T00:42:34Z: rustc_mir::util::liveness: Liveness dataflow converged after 13 iterations (0% overhead)
DEBUG 2019-06-27T00:42:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 20 iterations (0% overhead)
DEBUG 2019-06-27T00:42:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 20 iterations (0% overhead)
DEBUG 2019-06-27T00:42:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 6 iterations (0% overhead)
DEBUG 2019-06-27T00:42:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 19 iterations (26.666666666666668% overhead)
DEBUG 2019-06-27T00:42:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 9 iterations (0% overhead)
DEBUG 2019-06-27T00:42:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 9 iterations (0% overhead)
DEBUG 2019-06-27T00:42:35Z: rustc_mir::util::liveness: Liveness dataflow converged after 15 iterations (0% overhead)
DEBUG 2019-06-27T00:42:36Z: rustc_mir::util::liveness: Liveness dataflow converged after 64 iterations (0% overhead)
DEBUG 2019-06-27T00:42:37Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (0% overhead)
DEBUG 2019-06-27T00:42:37Z: rustc_mir::util::liveness: Liveness dataflow converged after 4 iterations (0% overhead)
DEBUG 2019-06-27T00:42:37Z: rustc_mir::util::liveness: Liveness dataflow converged after 7 iterations (0% overhead)
DEBUG 2019-06-27T00:42:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 10 iterations (0% overhead)
DEBUG 2019-06-27T00:42:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 22 iterations (0% overhead)
DEBUG 2019-06-27T00:42:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 8 iterations (0% overhead)
DEBUG 2019-06-27T00:42:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 15 iterations (0% overhead)
DEBUG 2019-06-27T00:42:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 11 iterations (10% overhead)
DEBUG 2019-06-27T00:42:38Z: rustc_mir::util::liveness: Liveness dataflow converged after 8 iterations (14.285714285714285% overhead)
DEBUG 2019-06-27T00:42:39Z: rustc_mir::util::liveness: Liveness dataflow converged after 23 iterations (4.545454545454546% overhead)
DEBUG 2019-06-27T00:42:39Z: rustc_mir::util::liveness: Liveness dataflow converged after 19 iterations (26.666666666666668% overhead)
DEBUG 2019-06-27T00:42:39Z: rustc_mir::util::liveness: Liveness dataflow converged after 19 iterations (26.666666666666668% overhead)
DEBUG 2019-06-27T00:42:40Z: rustc_mir::util::liveness: Liveness dataflow converged after 8 iterations (0% overhead)
DEBUG 2019-06-27T00:42:40Z: rustc_mir::util::liveness: Liveness dataflow converged after 24 iterations (4.3478260869565215% overhead)
DEBUG 2019-06-27T00:42:40Z: rustc_mir::util::liveness: Liveness dataflow converged after 18 iterations (0% overhead)
DEBUG 2019-06-27T00:42:40Z: rustc_mir::util::liveness: Liveness dataflow converged after 6 iterations (0% overhead)
DEBUG 2019-06-27T00:42:41Z: rustc_mir::util::liveness: Liveness dataflow converged after 8 iterations (0% overhead)
DEBUG 2019-06-27T00:42:41Z: rustc_mir::util::liveness: Liveness dataflow converged after 38 iterations (0% overhead)
DEBUG 2019-06-27T00:42:42Z: rustc_mir::util::liveness: Liveness dataflow converged after 13 iterations (0% overhead)
DEBUG 2019-06-27T00:42:42Z: rustc_mir::util::liveness: Liveness dataflow converged after 14 iterations (0% overhead)
DEBUG 2019-06-27T00:42:42Z: rustc_mir::util::liveness: Liveness dataflow converged after 9 iterations (0% overhead)
DEBUG 2019-06-27T00:42:43Z: rustc_mir::util::liveness: Liveness dataflow converged after 6 iterations (0% overhead)
DEBUG 2019-06-27T00:42:43Z: rustc_mir::util::liveness: Liveness dataflow converged after 6 iterations (0% overhead)
DEBUG 2019-06-27T00:42:44Z: rustc_mir::util::liveness: Liveness dataflow converged after 8 iterations (0% overhead)
DEBUG 2019-06-27T00:42:44Z: rustc_mir::util::liveness: Liveness dataflow converged after 17 iterations (0% overhead)
DEBUG 2019-06-27T00:42:45Z: rustc_mir::util::liveness: Liveness dataflow converged after 6 iterations (0% overhead)
DEBUG 2019-06-27T00:42:45Z: rustc_mir::util::liveness: Liveness dataflow converged after 14 iterations (0% overhead)
DEBUG 2019-06-27T00:42:46Z: rustc_mir::util::liveness: Liveness dataflow converged after 6 iterations (20% overhead)
```

**Comment by pnkfelix** [comment]
This seems fine to me. Its currently marked waiting-on-author, but I don't really have much to add as a reviewer.

**Comment by ecstatic-morse** [comment]
@pnkfelix I think this one should definitely be merged, even if #62062 is not. Let me squash first though.

**Pull request merged**
