### PR TITLE
Use self profile infrastructure for -Z time and -Z time-passes

### PR DESCRIPTION
**Pull request by Zoxc**
There's no longer indentation for -Z time and -Z time-passes and duplicate timers between self profiling and -Z time-passes have been removed.

r? @wesleywiser

### CODE REVIEW

**Comment by bjorn3** [comment]
> There's no longer indentation for -Z time and -Z time-passes

I think the indentation is useful. Is there some way to re-introduce it?

**Review by wesleywiser — APPROVED** [review]
Looks great!

**Comment by wesleywiser** [comment]
r=me when rebased

**Comment by Zoxc** [comment]
@bjorn3 Indentation doesn't work with multi-threading though. If you want a better overview you can use `-Z self-profile` + crox.

**Comment by michaelwoerister** [comment]
I wished this had been coordinated with https://github.com/rust-lang/rust/pull/67397, which is now broken. It also regressed the event cleanup, introducing duplicate events (e.g. "indexing HIR" vs "build_hir_map") and adds a separate line for each codegen unit again (e.g. in https://perf.rust-lang.org/detailed-query.html?commit=33640f0e03af2fb31ce380d5389d5545f24ce29a&benchmark=syn-opt&run_name=baseline%20incremental). 

Self-profiling has more restrictions and is more user-facing than `-Ztime-passes`. Changing events can break downstream tooling. An integration of the two features has to be done carefully.

**Comment by michaelwoerister** [comment]
@Zoxc & @wesleywiser: I'm proposing to revert this PR. It breaks the ongoing self-profiling work and perf.rlo detail views. It also doesn't look like a clean integration of the two features with no clear distinction of what should be a generic activity, what a sparse pass and what a generic pass. I think time-passes and self-profiling can use the same infrastructure at some point but now is too early.

**Comment by Zoxc** [comment]
@michaelwoerister How does it break https://github.com/rust-lang/rust/pull/67397? I don't see anything that would conflict.

And if our tooling can't handle more events yet we could just leave the pass events off by default?

**Comment by Zoxc** [comment]
I suggest that we:
- Rename `-Z time` passes to have the naming style of `-Z self-profile`. I'm not sure why you went with C-style function names here?
- Remove the duplicated events that I missed
- Turn off `generic_pass` events by default and bring back the equivalent `generic_event`s.

I've been using self-profiling with `-Z time` events and `crox` to [optimize the compiler recently](https://github.com/rust-lang/rust/pull/67870) and I'd like to have this available without carrying a patch around.

**Comment by michaelwoerister** [comment]
I gave my reasoning for going with names without spaces here: https://github.com/rust-lang/rust/pull/65208#discussion_r332873518

New event IDs are not a problem. The tooling can handle that if parameters are handled correctly. For new event kinds things are trickier, some tooling might crash when encountering new kinds, some might ignore them and give wrong numbers.

I'm OK with the steps you suggest if we also 
 - replace `generic_pass_event_kind` and `sparse_pass_event_kind` with `generic_activity_event_kind`, and
 - find a way of also getting rid of the `generic-pass` and `sparse-pass` event filters. If they provide useful information they can just be regular `generic-activity` events. Whether they generate console output or not can be handled independently of their event kind and event filters.

I also think it would be good get rid of the `Session::time` and `Session::timer` methods and go with `sess.prof.generic_activity(...)` instead (or something like `sess.prof.generic_activity_verbose(...)` that reads the `-Ztime(-passes)` settings).

**Comment by pnkfelix** [comment]
After some private discussion with @nikomatsakis and @michaelwoerister ,  I am inclined to revert this PR, mainly based on it regressing perf.rlo detailed view as noted by @michaelwoerister, namely the rows prefixed with "codegen passes" in [perf link](https://perf.rust-lang.org/detailed-query.html?commit=33640f0e03af2fb31ce380d5389d5545f24ce29a&benchmark=syn-opt&run_name=baseline%20incremental):


| Query/Function | Time | % Total Time | Full Executions | Loading |
| -- | -- | -- | -- | -- |
| ... |
| codegen passes [3z2mfowzhqp1o742] | 0.000 | 0.00% | 0 | 0.000 |
| collecting mono items | 0.000 | 0.00% | 0 | 0.000 |
| codegen passes [3rekknkyfilt37nt] | 0.000 | 0.00% | 0 | 0.000 | 
| codegen passes [trthz5azyug3sfc] | 0.000 | 0.00% | 0 | 0.000 |
| codegen passes [1erb9ctdzy7h21xs] | 0.000 | 0.00% | 0 | 0.000 |
| ... |

**Comment by pnkfelix** [comment]
Update to previous comment: @michaelwoerister has just pointed out to me that the recently posted PR #67988 might contain a fix to the issue here.

I'll wait for more information on that before proceeding with a revert of PR #67777

**Comment by nnethercote** [comment]
The removal of indentation is very unfortunate. It makes the output *much* harder to interpret. There's not really any point having stacks of indented timers if the output doesn't indicate them.

**Pull request merged**
