### PR TITLE
Allow lower_lifetime_binder receive a closure

### PR DESCRIPTION
**Pull request by spastorino**
@oli-obk requested this and other changes as a way of simplifying https://github.com/rust-lang/rust/pull/101345. This is just going to make the diff of https://github.com/rust-lang/rust/pull/101345 smaller.

r? @oli-obk @cjgillot

### CODE REVIEW

**Comment by oli-obk** [comment]
huh, why does this affect typeck perf?

**Comment by lqd** [comment]
A big part of that is probably noise: these benchmarks have been randomly going up and down all week on unrelated PRs.

**Pull request merged**
