### PR TITLE
Add aarch64-unknown-linux-musl host builds

### PR DESCRIPTION
**Pull request by Gelbpunkt**
This adds aarch64-unknown-linux-musl to the hosts list and adds the build to the dist-arm-linux builder as @Mark-Simulacrum suggested to me in Zulip. @jyn514 requested to be mentioned :smile: 

I had to update the config for crosstool-ng as it had a prompt about the glibc version.

I ran `src/ci/docker/run.sh dist-arm-linux` to test it.

```
Build completed successfully in 1:31:50
Compile requests              8180
Compile requests executed     8135
Cache hits                     287
Cache misses                  7848
Cache timeouts                   0
Cache read errors                0
Forced recaches                  0
Cache write errors               0
Compilation failures             0
Cache errors                     0
Non-cacheable compilations       0
Non-cacheable calls             36
Non-compilation calls            9
Unsupported compiler calls       0
Average cache write          0.000 s
Average cache read miss      6.389 s
Average cache read hit       0.000 s
Cache location             Local disk: "/sccache"
Cache size                     202 MiB
Max cache size                  10 GiB
== clock drift check ==
  local time: Sun Sep  6 19:30:17 UTC 2020
  network time: Sun, 06 Sep 2020 19:30:17 GMT
== end clock drift check ==
```

Only errors were in miri due to struct fields being private (already been reported [here](https://github.com/rust-lang/rust/issues/76337))

Edit: Maybe it is helpful if I add that it is a working compiler
```sh
/rust-nightly-aarch64-unknown-linux-musl # ash install.sh 
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'cargo'
install: installing component 'rls-preview'
install: installing component 'rust-analyzer-preview'
install: installing component 'clippy-preview'
install: installing component 'rustfmt-preview'
install: installing component 'llvm-tools-preview'
install: installing component 'rust-analysis-aarch64-unknown-linux-musl'
install: installing component 'rust-std-aarch64-unknown-linux-musl'
install: WARNING: failed to run ldconfig. this may happen when not installing as root. run with --verbose to see the error

    Rust is ready to roll.

/ # cat test.rs 
fn main() { println!("hello world"); }
/ # rustc test.rs
/ # ./test
hello world
 # file test
test: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped
```

### CODE REVIEW

**Comment by ehuss** [comment]
Is this different from #75751?

**Comment by pietroalbini** [comment]
Thanks for opening the PR!

Indeed, #75751 is already open with the same changes. Closing this in favor of the other one.

**Comment by alex** [comment]
Duplicating my comment from #75751 -- I think this PR is more complete than mine and it'd be better to review it instead of mine.

**Comment by Gelbpunkt** [comment]
@alex Hi, I am sorry for the late reply for opening this as I did not see your PR earlier when I made this one. While I don't completely grasp how your PR would be less complete, I've updated this one based on missing parts in it with your changes. Thanks a lot for your effort!

**Comment by alex** [comment]
@Gelbpunkt you got your PR all the way to fully building, if I understand correctly, and mine wasn't :-)

**Comment by jyn514** [comment]
Copying from https://github.com/rust-lang/rust/pull/75751#issuecomment-691167679:

> This was [discussed as part of the compiler weekly meeting](https://zulip-archive.rust-lang.org/238009tcompilermeetings/10920weeklymeeting2020091054818.html#209653748)

> More specifically, I think the T-compiler team was generally in favor of landing this.

However it still needs a decision from T-infra I think.

**Comment by pietroalbini** [comment]
The code change looks fine, and we'll discuss in this week's infra team meeting.

**Comment by pietroalbini** [comment]
Discussed this in the infrastructure team meeting, and we agreed to approve landing this! Thanks for sending the PR!

@bors r+ rollup=never

**Pull request merged**
