### PR TITLE
Allow non-alphabetic underscores in camel case

### LINKED ISSUE #34633: Camel case warning fires on `X86_64`
I feel like the warning fires wrongly on this variant name in particular.

```
src/lib.rs:24:5: 24:11 warning: variant `X86_64` should have a camel case name such as `X8664`, #[warn(non_camel_case_types)] on by default
src/lib.rs:24     X86_64,
                  ^~~~~~
```

### LINKED ISSUE #41621: #[deny(non_camel_case_types)] is too aggressive
Specifically, there are snake_case names that cannot be converted into CamelCase (as interpreted by this lint) without losing semantics: anything that contains two numbers with a separator. E.g `foo_4_20` does not have a CamelCase equivalent that's accepted by the lint but is not confusable with the conversion result of `foo_420`.

Originally discovered in https://github.com/japaric/svd2rust/issues/76.

### PR DESCRIPTION
**Pull request by varkor**
Certain identifiers, such as `X86_64`, cannot currently be unambiguously represented in camel case (`X8664`, `X86_64`, `X8_664`, etc. are all transformed to the same identifier). This change relaxes the rules so that underscores are permitted between two non-alphabetic characters under `#[forbid(non_camel_case_types)]`. Fixes #34633 and fixes #41621.

### CODE REVIEW

**Comment by nagisa** [comment]
Is it something that needs a dependency on regex? 

It seems to me that the implementation could simply compare the upper and lower-cased versions for equality before warning and it the upper-casing operation certainly could avoid invoking a whole regex machinery.

**Comment by varkor** [comment]
The `regex` dependency could be replaced by explicit loops over pairs of characters in `is_camel_case` and `to_camel_case`, though it seemed much less elegant/readable, and less amenable to change if there were any subtleties that needed adjustment in the future. I can change it if the extra dependency is not worth it, though.

I'm not quite sure what you mean by comparing the upper and lower cased versions. You mean comparing strings to their `to_camel_case` results to check `is_camel_case`? There are some strings that are counted as camel case, but are not fixed points for `is_camel_case` at the moment: e.g. `to_camel_case("FooBar") == "Foobar"`. This behaviour could also be changed, but would be another change that's not necessarily desirable.

**Comment by nagisa** [comment]
Sorry for delay. Right, I agree regarding to_camel_case not being a fixed-point.

Regex dependency still bothers me. It is a pretty large dependency to pull into the compiler for such a minor improvement and I feel that we’d be better off investing into a naiver implementation.

**Comment by varkor** [comment]
Okay, I've switched to a more explicit approach.

**Comment by alexcrichton** [comment]
ping @nagisa, mind taking a look at the updated changes?

**Comment by nagisa** [comment]
This seems great to me. Thanks!

@bors r+

**Pull request merged**
