### PR TITLE
Fix some typos and improve doc comments style

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thank you!

**Comment by jonathandturner** [comment]
@bors r-

You've got some linkchecker errors:

```
    Finished release [optimized] target(s) in 19.96 secs
Linkcheck stage2 (x86_64-unknown-linux-gnu)
std/vec/struct.Vec.html:1764: broken link - std/vec/primitive.slice.html
thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:56
note: Run with `RUST_BACKTRACE=1` for a backtrace.


command did not execute successfully: "/build/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/linkchecker" "/build/build/x86_64-unknown-linux-gnu/doc"
expected success, got: exit code: 101
```

**Comment by GuillaumeGomez** [comment]
Locally it works... :-/ I restart travis, just in case.

**Comment by GuillaumeGomez** [comment]
Fixed.

**Pull request merged**
