### PR TITLE
Don't treat closures/coroutine types as part of the public API

### PR DESCRIPTION
**Pull request by oli-obk**
Fixes a regression from https://github.com/rust-lang/rust/pull/117076

r? @compiler-errors

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/pull/117400#issuecomment-1785483138

**Comment by compiler-errors** [comment]
Oh right, wasm doesn't support panics really well, lol. I think we could probably just ignore wasm here.

**Comment by oli-obk** [comment]
I think you meant to r- https://github.com/rust-lang/rust/pull/117389

@bors r=compiler-errors

**Pull request merged**
