### PR TITLE
Ensure that `'_` and GAT yields errors

### LINKED ISSUE #95305: ensure that `'_` and GATs yields errors
It's not clear how `'_` and GATs should interact. We should add tests that using `'_` either in the parameter list of a GAT or in its value is prohibited.

e.g., both of these should error (and currently do)

```rust
#![feature(generic_associated_types)]

trait Foo {
    type Item<'a>;
}

fn foo(x: &impl Foo<Item<'_> = u32>) { }
```

```rust
#![feature(generic_associated_types)]

trait Foo {
    type Item<'a>;
}

fn foo(x: &impl for<'a> Foo<Item<'a> = &'_ u32>) { }
```

### PR DESCRIPTION
**Pull request by marmeladema**
Fixes #95305 

@bors r? @jackh726

### CODE REVIEW

**Comment by jackh726** [comment]
Given that this is behavior we'd like to change sometime in the future, I think a short comment on these tests would be good. (Basically, why we expect an error *now* and how we might change it in the future.)

I also think these can just be one test.

r=me with those changes

@bors delegate+

**Comment by apiraino** [comment]
I think the cureent status is now waiting on author (that can also approve this PR themself)

@rustbot author

**Comment by jackh726** [comment]
ping @marmeladema for this :)

**Comment by marmeladema** [comment]
> Given that this is behavior we'd like to change sometime in the future, I think a short comment on these tests would be good. (Basically, why we expect an error now and how we might change it in the future.)

I am not sure what comment to add because I don't really know why its not supported right now nor what we would expect to do in the future :/

**Review by jackh726 — APPROVED** [review]

**Pull request merged**
