### PR TITLE
Upgrade to LLVM's 3.7 release branch

### PR DESCRIPTION
**Pull request by alexcrichton**
LLVM has recently created their 3.7 release branch, and this PR updates us to that point. This should hopefully mean that we're basically compatible with the upcoming 3.7 release. Additionally, there are a number of goodies on this branch.
- This contains a fix for https://llvm.org/bugs/show_bug.cgi?id=23957
  which should help us bootstrap farther on 32-bit MSVC targets.
- There is better support for writing multiple flavors of archives, allowing us
  to use the built-in LLVM support instead of the system `ar` on all current
  platforms of the compiler.
- This LLVM has SafeStack support
- An [optimization patch](https://github.com/rust-lang/llvm/commit/7cf5e26e18f7d2d8db09c83c76dd727535f281ab) by @pcwalton is included.
- A number of other minor test fixes here and there.

Due to problems dealing with the data layout we pass to LLVM, this PR also takes the time to clean up how we specific this. We no longer specify a data layout to LLVM by default and instead take the default for the target from LLVM to pass to the module that we're building. This should be more robust going into the future, and I'm also not sure we know what any of these arcane strings are any more...

### CODE REVIEW

**Comment by tamird** [comment]
:confetti_ball:

**Comment by alexcrichton** [comment]
@bors: r-, turns out there's still bugs on OSX and Windows, taking some time to fix those up. So far:

* Can't use LLVM's `writeArchive` for MSVC
* Need to re-apply https://github.com/rust-lang/llvm/commit/d3add25862f39db30ee37b3d1c3ed36f0a0a381f as another bug has shown up (but different than before)

And probably one or two more on the way!

**Comment by dotdash** [comment]
Depends on #27070

**Comment by richo** [comment]
\o/

Thanks for getting us onto a new llvm (I can finally play with safestacks!) and keeping my tiny commit intact :heart:

**Pull request merged**
