### PR TITLE
rust/issues/103606

### PR DESCRIPTION
**Pull request by kubycsolutions**
Fix for https://github.com/rust-lang/rust/issues/103606

Wasn't sure whether you folks wanted us to branch or fork (I've seen projects use both), so took the latter.

### CODE REVIEW

**Comment by kubycsolutions** [comment]
Fixed typo (which, yes, I should have caught earlier but apparently didn't; that's why automatic checks exist...). What's best practice to reset and retry?

**Comment by kubycsolutions** [comment]
Reset and retry

**Comment by jyn514** [comment]
@kubycsolutions CI will automatically rerun when you push a new commit to this branch :)

**Comment by kubycsolutions** [comment]
Good to know. I've worked with automatic verification before, but based on a different repository so I wasn't counting on rerun.

--
   /_  Joe Kesselman (he/him/his)
-/ _) My Alexa skill for New Music/New Sounds fans:
   /   https://www.amazon.com/dp/B09WJ3H657/

() Plaintext Ribbon Campaign
/\ Stamp out HTML mail!
________________________________

**Pull request closed without merging**
