### PR TITLE
Rollup of 13 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #90782 (Implement raw-dylib support for windows-gnu)
 - #92045 (Don't fall back to crate-level opaque type definitions.)
 - #92316 (mangling_v0: Skip extern blocks during mangling)
 - #92363 (Override rustc version in ui and mir-opt tests to get stable hashes)
 - #92768 (Partially stabilize `maybe_uninit_extra`)
 - #92778 (fs: Use readdir() instead of readdir_r() on Linux)
 - #92810 (Deduplicate box deref and regular deref suggestions)
 - #92818 (Update documentation for doc_cfg feature)
 - #92838 (Clean up some links in RELEASES)
 - #92840 (Fix some lints documentation)
 - #92849 (Clippyup)
 - #92854 (Use the updated Rust logo in rustdoc)
 - #92864 (Fix a missing dot in the main item heading)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=90782,92045,92316,92363,92768,92778,92810,92818,92838,92840,92849,92854,92864)

### CODE REVIEW

**Comment by ehuss** [comment]
@bors r-

This is going to fail.

**Comment by ehuss** [comment]
#92316 and #92363 are mutually incompatible.  #92363 should probably not be rolled up with anything that can remotely interact with it.

**Comment by matthiaskrgr** [comment]
Thanks, dropped all 3 in #92880

**Pull request closed without merging**
