### PR TITLE
Box AssertKind

### PR DESCRIPTION
**Pull request by saethlin**
r? @nnethercote this feels like your kind of thing

I want to add a new variant to `AssertKind` that needs 3 operands, and that ends up breaking a bunch of size assertions. So... what if we go the opposite direction first; shrinking `AssertKind` by boxing it?

### CODE REVIEW

**Comment by nnethercote** [comment]
LGTM, assuming no perf regressions.

@bors delegate=saethlin

**Comment by saethlin** [comment]
Hunh. I dismissed the regression as noise initially, but seeing it in 2 runs means it's much more likely to be real and significant.

I suspect the reason we see this is that keccak is like a stress test of checked slice indexing. It probably has _way_ more panic paths than any normal program. Good to be aware of this though.

**Pull request merged**
