### PR TITLE
Optimize AtomicBool::fetch_nand

### PR DESCRIPTION
**Pull request by ghost**
This is an attempt to push the PR #40563 to completion.

Benchmark: [source](https://gist.github.com/stjepang/023f5025623f5474184f9f4dfd6379ae)
Improvement:

```
 name  old_ ns/iter  new_ce_ ns/iter  diff ns/iter   diff % 
 1t    146,440       89,904                -56,536  -38.61% 
 2t    561,456       316,835              -244,621  -43.57% 
 4t    2,822,821     1,005,424          -1,817,397  -64.38% 
```

r? @eddyb 
cc @alexcrichton @nagisa

### CODE REVIEW

**Comment by nagisa** [comment]
The difference between swap and compare_exchange in previous benchmark seemed like something that would be within error, with swap implementation being significantly easier to comprehend.

I would r+ if CAS was replaced with swap.

**Comment by stjepang** [comment]
@nagisa Fair enough. Replaced CAS with swap.

**Comment by TimNN** [comment]
@bors retry

* #41147

**Comment by TimNN** [comment]
@bors retry

#41147

**Pull request merged**
