### PR TITLE
Fix a breaking change in #30523

### PR DESCRIPTION
**Pull request by strega-nil**
Fix a breaking change in #30523

While this does fix a breaking change, it is also, technically, a
[breaking-change] to go back to our original way

### CODE REVIEW

**Comment by tsion** [comment]
Note, this was discovered in https://github.com/rust-lang/rust/issues/30713.

**Comment by SimonSapin** [comment]
```
command timed out: 1200 seconds without output running ['make', 'check'], attempting to kill
```

**Comment by GuillaumeGomez** [comment]
It would be nice to add code which failed with the new version, no?

**Comment by nikomatsakis** [comment]
It would be good to have a test case, I agree.

**Pull request merged**
