### PR TITLE
Improve detection of unused imports (fixes #30078)

### LINKED ISSUE #30078: Unused import lint does not trigger if imported item is used through another path
This gives no warnings:
```rust
mod a {
    pub fn foo() {}
}

fn main() {
    use a::foo; // Should trigger unused_imports
    a::foo();
}
```

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes a bug in which unused imports can get wrongly marked as used when checking for unused qualifications in `resolve_path` (issue #30078), and it removes unused imports that were previously undetected because of the bug.

### CODE REVIEW

**Comment by sanxiyn** [comment]
Travis failed because of new unused_imports warnings.

**Comment by alexcrichton** [comment]
Awesome! Could you also expand the commit message to include information like:

* What bug is being fixed (e.g. not just the bug number)
* How the bug was fixed
* What the expected fallout is

r? @nrc (looking at other resolve changes lately as well)

**Comment by nrc** [comment]
r+ with the changes to the commit message that @alexcrichton requested

**Comment by sanxiyn** [comment]
Eh, isn't the commit message already changed?

**Comment by nrc** [comment]
@bors: r+

(ah yeah, I think I needed to refresh my browser)

**Comment by jseyfried** [comment]
@nrc rebased

**Pull request merged**
