### PR TITLE
Update libc to 0.2.39

### PR DESCRIPTION
**Pull request by bdrewery**
CC #42681

r? @alexcrichton

### CODE REVIEW

**Comment by bdrewery** [comment]
@Mark-Simulacrum I think this should just be "CC" rather than "Fixes" for #42681 since the bootstrap is a piece that needs to be updated to fully fix the problem. Thanks for reopening it.

**Comment by Mark-Simulacrum** [comment]
You mean we need to backport to beta and bootstrap from that beta?

**Comment by bdrewery** [comment]
I don't know the process for updating the beta but I wasn't going to push to update it for #42681. I think waiting for other reasons is fine. I assume that whatever the next update is would use whatever the current libc is from master right?

**Comment by Mark-Simulacrum** [comment]
Releasing a new beta is trivial, and if simply backporting a libc bump to beta is enough to fix what looks like a somewhat painful regression, then we should do it. Once that's done we can update master to boostrap from that beta instead of the original beta.

**Comment by bdrewery** [comment]
Merge conflict resolved via rebase, now only libc submodule updated.

**Pull request merged**
