### PR TITLE
Simplify message paths

### PR DESCRIPTION
**Pull request by est31**
This makes it easier to open the messages file. Right now I have to first click on the `locales` dir to open it, and then on the `en-US.ftl` file. `Cargo.toml` and `build.rs` files are also in the top level, and I think there should not be more than one file, so a directory isn't really needed. The [chosen strategy for pontoon adoption](https://rust-lang.zulipchat.com/#narrow/stream/336883-i18n/topic/pontoon.20and.20next.20steps) is out of tree. Even if this descision is changed in the future, the `messages.ftl` approach is also compatible with non-english translations living in-tree, as long as the non-english translations don't live in the `compiler/rustc_foo/` directories but in different ones. That would also be helpful for grepability purposes.

The commit was the result of automated changes:

```
for p in compiler/rustc_*; do mv $p/locales/en-US.ftl $p/messages.ftl; rmdir $p/locales; done

for p in compiler/rustc_*; do sed -i "s#\.\./locales/en-US.ftl#../messages.ftl#" $p/src/lib.rs; done
```

r? @davidtwco

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]
r=me after rebase

**Comment by davidtwco** [comment]
@bors delegate=est31

Feel free to approve this after you rebase, it's likely to be a bit conflict prone.

**Comment by est31** [comment]
It's strange that github/bors shows this as a merge conflict as rebasing works without requiring merge conflict resolution...

**Comment by compiler-errors** [comment]
Yeah, sometimes that happens. I think bors's merge conflict resolution is a bit pessimistic?

**Comment by est31** [comment]
Hmm yeah getting this merged is a bit difficult, like #103042 was. outside of splitting it up or p=10 above rollups, the only chance is to wait until the stars line up so that no rollup PR is in the queue (usually those do change ftl files), and a PR is currently being tried that doesn't modify ftl files. Then one would rebase right at that moment, and and approve the pr.

I will spend the next week looking for opportunities to merge this. If there is still none, I will just set p=10.

**Comment by compiler-errors** [comment]
I would wait until the queue is calmed down, then land it with p=10.

**Comment by est31** [comment]
Okay, I'd say it's calmed down now, only 26 PRs waiting for admittance now.

@bors r=davidtwco

**Pull request merged**
