### PR TITLE
Move datatypes definitions in specific modules inside rustc::{traits, infer}

### PR DESCRIPTION
**Pull request by cjgillot**
Prelude to #67953 

Some data types inside `rustc::traits` and `rustc::infer` are used in other parts of `librustc`. These cannot go to a separate crate `librustc_infer`.

This PR moves those data types to `traits::types` and `infer::types` modules, from where everything is reexported.

Note for review: some imports feature the `crate -> rustc` substitution. This is cruft from the splitting out of #67953. This can be reverted, but are bound to be put back by #67953.

r? @Centril
cc @Zoxc

### CODE REVIEW

**Comment by Centril** [comment]
cc @nikomatsakis @matthewjasper

**Comment by Centril** [comment]
Actually, I have less of a sense of direction wrt. traits/infer, so I'll r? @nikomatsakis :)

**Review by matthewjasper — APPROVED** [review]

**Comment by eddyb** [comment]
This PR made some fields `pub` that weren't before (e.g. in `SelectionCache`, `EvaluationCache` etc.).
That's an abstraction boundary break, IMO, but I'm not sure how I'd address it.

**Pull request merged**
