### PR TITLE
Don't silently eat label before block in block-like expr

### LINKED ISSUE #103983: Lifetimes are parsed without errors when they occur in most `ExpressionWithBlock`s in front of the contained block expression
I tried this code [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dd6fa7838eb7dcf41642b8d87ace24d1):

```rust
fn main() {
    if let () = () 'a {}
    if true 'a {}
    loop 'a {}
    while true 'a {}
    while let () = () 'a {}
    for _ in 0..0 'a {}
    unsafe 'a {}
}
```

I expected to see this happen: The compiler rejects all these expressions as the lifetimes are in a nonsensical position.

Instead, this happened: The compiler accepted the expressions without saying anything

### Meta

This behavior seems to occur since 1.61.
1.60 and below properly reject the code.

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #103983
cc #92823 (where the regression was introduced)

### CODE REVIEW

**Comment by compiler-errors** [comment]
Beta nominating bc this is a pretty simple fix, and this is a strange parse that should be removed as quickly as possible.

**Comment by est31** [comment]
In #50045 I have added `label_break_value_illegal_uses.rs`, and that seems to not have been regressed upon, but it only tested for stuff like `if true 'b: {}` where a `:` is present.

**Comment by compiler-errors** [comment]
@est31, so the root-cause of this specific regression is that we eat `'label`, but then don't proceed to emit an error *unless* 1. `:` is present, and `{` follows.

**Pull request merged**
