### PR TITLE
Merge the std_unicode crate into the core crate

### LINKED ISSUE #49319: `std_unicode::char::decode_utf16` should be in `core`
The [`decode_utf16`](https://doc.rust-lang.org/std_unicode/char/fn.decode_utf16.html) function currently lives in the `std_unicode` crate. But, as far as I can tell, this function doesn't depend on any Unicode tables and has no reason to be in this crate.

I suggest moving this function (and its associated iterator) into the `core` crate. This will allow for decoding UTF-16 text under `#![no_std]` in stable Rust.

### PR DESCRIPTION
**Pull request by SimonSapin**
[The standard library facade](https://github.com/rust-lang/rust/issues/27783) has historically contained a number of crates with different roles, but that number has decreased over time. `rand` and `libc` have moved to crates.io, and [`collections` was merged into `alloc`](https://github.com/rust-lang/rust/pull/42648). Today we have `core` that applies everywhere, `std` that expects a full operating system, and `alloc` in-between that only requires a memory allocator (which can be provided by users)… and `std_unicode`, which doesn’t really have a reason to be separate anymore. It contains functionality based on Unicode data tables that can be large, but as long as relevant functions are not called the tables should be removed from binaries by linkers.

This deprecates the unstable `std_unicode` crate and moves all of its contents into `core`, replacing them with `pub use` reexports. The crate can be removed later. This also removes the `CharExt` trait (replaced with inherent methods in libcore) and `UnicodeStr` trait (merged into `StrExt`). There traits were both unstable and not intended to be used or named directly.

A number of new items are newly-available in libcore and instantly stable there, but only if they were already stable in libstd.

Fixes #49319.

### CODE REVIEW

**Comment by SimonSapin** [comment]
r? @alexcrichton 

@rfcbot fcp merge

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362741907). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Receiving objects: 100% (163/163), 79.07 KiB | 15.81 MiB/s, done.
---
Resolving deltas: 100% (125/125), completed with 52 local objects.
---
[00:00:47] configure: rust.quiet-tests     := True
---
[00:04:32] tidy error: /checkout/src/libcore/unicode/mod.rs:11: mismatches to previous in: ["tracking issue"]
[00:04:32] tidy error: /checkout/src/libstd_unicode/lib.rs:23: mismatches to previous in: ["tracking issue"]
[00:04:33] some tidy checks failed
[00:04:33]
[00:04:33]
[00:04:33] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:33] expected success, got: exit code: 1
[00:04:33]
[00:04:33]
[00:04:33] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:33] Build completed unsuccessfully in 0:01:55
[00:04:33] Makefile:79: recipe for target 'tidy' failed
[00:04:33] make: *** [tidy] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:131c7c48:start=1522950037728131176,finish=1522950037735954343,duration=7823167
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:1e0369a8
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by alexcrichton** [comment]
Looks great to me, thanks @SimonSapin!

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/362749863). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Receiving objects: 100% (163/163), 76.18 KiB | 25.39 MiB/s, done.
---
Resolving deltas: 100% (125/125), completed with 51 local objects.
---
[00:00:47] configure: rust.quiet-tests     := True
---
[00:38:51] ..........................................................................i.........................
[00:38:56] .................i..................................................................................
---
[00:39:30] .............................................................................................i......
[00:39:36] ...................................................................i................................
---
[00:40:27] .............................................i......................................................
---
[00:44:00] .............................i......................................................................
[00:44:14] ..............................................................i.....................................
[00:44:27] ...............................................i....................................................
[00:44:46] ....................................................................................................
[00:45:05] ....................................................................................................
[00:45:24] ....................................................................................................
[00:45:47] .i...............................................................................................i..
[00:46:17] ..............................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:46:20] ......
[00:46:47] ....................................................................................................
[00:47:20] .............................................................ii.....................................
[00:48:05] ........................i....................................................i.ii...................
[00:48:06] test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:48:42] .....................................................................................iiiiiii........
---
[00:50:50] ..................i............................................................ii.iii...............
[00:50:57] ....................................................................................................
[00:51:04] ........i..............................i............................................................
[00:51:11] ....................................................................................................
[00:51:18] ....................i...............................................................................
[00:51:25] ....................................................................................................
[00:51:34] ....................................................................................................
[00:51:44] ....................................................................................................
[00:51:54] ....................................................................................................
[00:52:06] ....................................................................................................
[00:52:14] .............i......................................................................................
[00:52:22] ................i..ii...............................................................................
[00:52:32] ....................................................................................................
[00:52:40] ....................................................................................................
[00:52:49] ...................................................................................i................
[00:52:58] .............................i....F.................................................................
---
[00:53:30] error: /checkout/src/test/compile-fail/single-primitive-inherent-impl.rs:19: unexpected error: '19:1: 19:13: duplicate lang item found: `char`. [E0152]'
[00:53:30]
[00:53:30] error: 1 unexpected errors found, 0 expected errors not found
[00:53:30] status: exit code: 101
[00:53:30] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/single-primitive-inherent-impl.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/single-primitive-inherent-impl.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/single-primitive-inherent-impl.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[00:53:30] unexpected errors (from JSON output): [
[00:53:30]     Error {
[00:53:30]         line_num: 19,
[00:53:30]         kind: Some(
[00:53:30]             Error
[00:53:30]         ),
[00:53:30]         msg: "19:1: 19:13: duplicate lang item found: `char`. [E0152]"
[00:53:30]     }
[00:53:30] ]
[00:53:30]
[00:53:30] thread '[compile-fail] compile-fail/single-primitive-inherent-impl.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1253:13
---
[00:53:30] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:53:30] expected success, got: exit code: 101
[00:53:30]
[00:53:30]
[00:53:30] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:53:30] Build completed unsuccessfully in 0:15:49
[00:53:30] Makefile:58: recipe for target 'check' failed
[00:53:30] make: *** [check] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:04d74321:start=1522954729762720800,finish=1522954729771831215,duration=9110415
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:079a341e
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:079a341e:start=1522954729780192541,finish=1522954729789643715,duration=9451174
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:004234a1
$ dmesg | grep -i kill
[   10.801514] init: failsafe main process (1092) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by Ericson2314** [comment]
Why are we doing this? Moving creates beneath the facade into `creates.io` and then using from `std` is a point *towards* the facade in my view.

**Comment by Ericson2314** [comment]
More broadly, I've argued with I believe some sucesss in the portability working group that the facade is actually useful, but I'm worried that with PRs like this that viewpoint isn't making it back out. This PR is fine if the working presumption is the facade is bad, but only that is true.

**Comment by SimonSapin** [comment]
The questions of whether the `core` v.s. `alloc` v.s. `std` distinction is useful, or whether some parts of the standard library should be re-exports of crates whose "upstream" maintenance is on crates.io, are both unrelated to this PR.

All this is saying is that the `std_unicode` crate specifically being separate from `core` is a historical remnant that doesn’t have a reason to be anymore (if it ever did), just like `collections` being separate from `alloc`.

**Comment by clarcharr** [comment]
@Ericson2314 do you have a valid reason why `libstd_unicode` is separate? Keep in mind that the only extra cost is linking; because these are part of the standard library, they're already compiled, so, this doesn't really affect compile time. `libcore` quite frankly has no reason to *not* have Unicode support, considering how it already indirectly does through things like `char::escape_debug`. Plus, I mentioned in #49283 that the neglect of libstd_unicode has lead to some additional bugs, whereas it's quite simply easier to maintain in libcore and liballoc.

This isn't a manner of assuming that a system has less; it's a manner of simply assuming that the programmer *wants* Unicode support, which I feel isn't a very great assumption considering how LTO is enabled by default on release and that it takes very little effort to avoid including these unicode tables in an executable or library.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363002721). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612879/612879), completed with 4872 local objects.
---
[00:00:47] configure: rust.quiet-tests     := True
---
[00:46:02] ..........................................................................i.........................
[00:46:08] .................i..................................................................................
---
[00:46:45] ..............................................................................................i.....
[00:46:52] ....................................................................i...............................
---
[00:47:51] .............................................i......................................................
---
[00:52:00] .............................i......................................................................
[00:52:15] ..............................................................i.....................................
[00:52:31] ...............................................i....................................................
[00:52:52] ....................................................................................................
[00:53:15] ....................................................................................................
[00:53:37] ....................................................................................................
[00:54:02] ..i...............................................................................................i.
[00:54:29] ............................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:54:41] ........................
[00:55:12] ....................................................................................................
[00:55:50] ..............................................................ii....................................
[00:56:34] .........................i....................................................itest [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:56:43] .ii..................
[00:57:27] ......................................................................................iiiiiii.......
---
[00:59:48] ..................i............................................................ii.iii...............
[00:59:56] ....................................................................................................
[01:00:04] ........i..............................i............................................................
[01:00:11] ....................................................................................................
[01:00:18] ....................i...............................................................................
[01:00:27] ....................................................................................................
[01:00:37] ....................................................................................................
[01:00:47] ....................................................................................................
[01:00:58] ....................................................................................................
[01:01:12] ....................................................................................................
[01:01:21] .............i......................................................................................
[01:01:31] .................i..ii..............................................................................
[01:01:41] ....................................................................................................
[01:01:51] ....................................................................................................
[01:02:00] ....................................................................................i...............
[01:02:10] ..............................i.....................................................................
---
[01:02:47] ...........................i........................................................................
[01:02:48] ....................................................................i...............................
[01:02:49] ................i.......................................................
---
[01:03:05] ...........i........................
---
[01:03:36] i...i..ii....i.............ii........iii......i..i...i...ii..i..i..ii.....
---
[01:03:40] i.......i......................i......
---
[01:04:20] iiii.......i..i........i..i.i.............i..........iiii...........i...i..........ii.i.i.......ii..
[01:04:21] ....ii...
---
[01:14:51] .....i..............................................................................................
---
[01:15:29] error[E0432]: unresolved import `core::unicode::Utf16Encoder`
[01:15:29]     --> liballoc/../liballoc/tests/str.rs:1207:9
[01:15:29]      |
[01:15:29] 1207 |     use core::unicode::Utf16Encoder;
[01:15:29]      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Utf16Encoder` in `unicode`
[01:15:29]
[01:15:37] error: aborting due to previous error
[01:15:37]
[01:15:37] For more information about this error, try `rustc --explain E0432`.
[01:15:37] error: Could not compile `alloc`.
[01:15:37] warning: build failed, waiting for other jobs to finish...
[01:15:41] error: build failed
[01:15:41]
[01:15:41]
[01:15:41] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "alloc" "--" "--quiet"
[01:15:41] expected success, got: exit code: 101
[01:15:41]
[01:15:41]
[01:15:41] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:15:41] Build completed unsuccessfully in 0:30:59
[01:15:41] Makefile:58: recipe for target 'check' failed
[01:15:41] make: *** [check] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:24affb42:start=1523007978622260781,finish=1523007978633961231,duration=11700450
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:2bb17ab8
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:2bb17ab8:start=1523007978640678959,finish=1523007978648226056,duration=7547097
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0df599fc
$ dmesg | grep -i kill
[   11.138699] init: failsafe main process (1093) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by Ericson2314** [comment]
@clarchar I think big creates are harder to maintain, especially for people that have never worked on them before. I also think out of tree creates are easier to maintain because people can build them like any other crate.

> Keep in mind that the only extra cost is linking...

I agree that a bigger core is *not* a problem compile time wise or whatever, just as you both.


> it's a manner of simply assuming that the programmer wants Unicode support

I also agree the not-wanting unicode case is not worth considering. But I don't think it's good code organization to put everything that's "free and always wanted" in core.

> Plus, I mentioned in #49283 that the neglect of libstd_unicode has lead to some additional bugs, whereas it's quite simply easier to maintain in libcore and liballoc.

I absolutely agree that's sort of probablem we should care about with this, unlike the others which we agree are non-pronkems. But I think moving to rust-lang-nursery and creates.io is the best solution.

> The standard library is intended to hold things which are...b) so fundamental that it'll show up in most programs.

I'm fine with that and agree that this fits, as does libc. The difference is I view "being in the standard library" and "being in rust-lang/rust" as two different things. I want to limit library code in rust-lang to your a), code that is tightly integrated with rustc. Anything that's stable Rust however can evolve better separately out of tree.

**Comment by Ericson2314** [comment]
I did a very bad job at explaining the connection with the portability stuff on IRC to @SimonSapin. Yes, this PR doesn't matter directly because this library is already quite portable. But it does generally bare on the weirdness of `std` relying on crates.io crates. I love that we already do that with libc, but I wouldn't be surprised if others find that weird / a one-off exception. But with the portability group's goals, that will become more common: all obscure platforms and even Windows (use @retep998's crates vs one-off bindings).

No one here actually said std deps on crates.io was weird, but at least @clarcharr's comment sort of presumed a hard "standard library" vs "rest of ecosystem" distinction, which std deps on crates.io blurs. I want to advocate for that blurring being a good thing, and point out that for portability's sake it may happen anyways (with other crates).

**Comment by SimonSapin** [comment]
> out of tree creates are easier to maintain because people can build them like any other crate.

That ship has sailed. The relevant functionality is stable and reexported in libstd, some of it since Rust 1.0.

**Comment by Ericson2314** [comment]
Huh? Std already depends on out of tree crates as I've said repeatedly. I don't understand your point.

**Comment by SimonSapin** [comment]
My point is that we can’t just remove the `std_unicode` functionality.

And this PR is all about how we expose functionality in the public API (e.g. do `#![no_std]` users need `extern crate std_unicode;` do get it), I don’t care as much about how source code is organized internally. That said I don’t understand how having std depending on out of tree crate is useful to users: if they also have a dependency on the crates.io version they end up with two different crates as far as rustc and Cargo are concerned.

**Comment by withoutboats** [comment]
@Ericson2314 it seems to me like you want to have a larger conversation about how we handle the organization of libstd (moving things out of tree etc). That's fine, but it seems off topic from this PR, which is about the smaller and largely unrelated question of making the unicode APIs easily available from libcore.

**Comment by Ericson2314** [comment]
> My point is that we can’t just remove the `std_unicode` functionality.

Ah OK, absolutely agreed.

> They end up with two different crates as far as rustc and Cargo are concerned.

Xargo-integration and public dependencies should fix this. I should make a note/issue about that so it doesn't slip through the cracks.

> That said I don’t understand how having std depending on out of tree crate is useful to users

The benefit is more for anyone that cares to contribute to the library, as (IMO) out of tree crates are much more easier to maintain and contribute to. Users should not be impacted. I think very few no_std users end up using unicode, as it turns out. I don't really worry about it: `extern std_unicode` is cheap.

**Comment by Ericson2314** [comment]
@withoutboats Yes, thanks, I do want to have that conversation. But how is this unrelated? For the same reasons I think this unicode code doesn't belong in libcore.

**Comment by whitequark** [comment]
> I think very few no_std users end up using unicode

I would be very worried using this justification. Most embedded software (not just in Rust) has atrocious support for unicode *because* of the lack of toolchain/library support; this leads to nasty vulnerabilities related to e.g. precomposed/decomposed characters. Unicode support *must* be available for every Rust target as a first class citizen.

**Comment by Ericson2314** [comment]
@whitequark Agreed, and I felt weird saying that for that reason. I rather just argue on the grounds of `extern crate std_unicode` being cheap and easy. Hopefully anyone that isn't used `std_unicode` just isn't using `str`/`char` period.

**Comment by Ericson2314** [comment]
`+r` is automerge or just build?

**Comment by SimonSapin** [comment]
Rebase conflict resolved automatically by kdiff3.

@bors r=alexcrichton

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363613425). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:34:37] died due to signal 11
[01:34:37] error: test failed, to rerun pass '--test coretests'
[01:34:37]
[01:34:37]
[01:34:37] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "arm-linux-androideabi" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "core" "--"
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:1a4d36c0:start=1523145668006212136,finish=1523145668020585580,duration=14373444
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:04c1cb46
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:04c1cb46:start=1523145668029133645,finish=1523145668038641426,duration=9507781
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0241f67c
$ dmesg | grep -i kill
[   10.725093] init: failsafe main process (1092) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363613425). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:34:37] died due to signal 11
[01:34:37] error: test failed, to rerun pass '--test coretests'
[01:34:37]
[01:34:37]
[01:34:37] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "arm-linux-androideabi" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "core" "--"
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:1a4d36c0:start=1523145668006212136,finish=1523145668020585580,duration=14373444
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:04c1cb46
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:04c1cb46:start=1523145668029133645,finish=1523145668038641426,duration=9507781
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0241f67c
$ dmesg | grep -i kill
[   10.725093] init: failsafe main process (1092) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by SimonSapin** [comment]
@bors: retry

https://github.com/rust-lang/rust/issues/49775

**Comment by SimonSapin** [comment]
Failed because of https://github.com/rust-lang/rust/issues/49775 again :/

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363752958). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:34:57] died due to signal 11
[01:34:57] error: test failed, to rerun pass '--test coretests'
[01:34:57]
[01:34:57]
[01:34:57] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "arm-linux-androideabi" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "core" "--"
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:16563078:start=1523196685813878058,finish=1523196685842137182,duration=28259124
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:2189706c
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:2189706c:start=1523196685849475511,finish=1523196685866140873,duration=16665362
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:06777125
$ dmesg | grep -i kill
[   10.677807] init: failsafe main process (1097) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by TimNN** [comment]
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363752958). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:34:57] died due to signal 11
[01:34:57] error: test failed, to rerun pass '--test coretests'
[01:34:57]
[01:34:57]
[01:34:57] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "arm-linux-androideabi" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "core" "--"
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:16563078:start=1523196685813878058,finish=1523196685842137182,duration=28259124
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:2189706c
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
find: `/home/travis/Library/Logs/DiagnosticReports': No such file or directory
travis_time:end:2189706c:start=1523196685849475511,finish=1523196685866140873,duration=16665362
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:06777125
$ dmesg | grep -i kill
[   10.677807] init: failsafe main process (1097) killed by TERM signal
```

</details><p></p>

I'm a bot! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**.

**Comment by kennytm** [comment]
I don't think this is spurious 😐

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/49811 should fix that failure, and bors priorities should make it land first.

@bors: retry

**Comment by SimonSapin** [comment]
Rebase conflict resolved automatically by kdiff3.

@bors r=alexcrichton

**Comment by SimonSapin** [comment]
```
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap build nonexistent/path/to/trigger/cargo/metadata
Build completed unsuccessfully in 0:00:04
make: *** [Makefile:81: prepare] Error 1
Command failed. Attempt 5/5:
    Finished dev [unoptimized] target(s) in 0.0 secs
 Downloading rls-rustc v0.2.2
[…]
 Downloading fuchsia-zircon v0.3.3
warning: spurious network error (2 tries remaining): failed to get 200 response from `https://static.crates.io/crates/fuchsia-zircon/fuchsia-zircon-0.3.3.crate`, got 504
warning: spurious network error (1 tries remaining): failed to get 200 response from `https://static.crates.io/crates/fuchsia-zircon/fuchsia-zircon-0.3.3.crate`, got 504
error: unable to get packages from source
Caused by:
  failed to get 200 response from `https://static.crates.io/crates/fuchsia-zircon/fuchsia-zircon-0.3.3.crate`, got 504
thread 'main' panicked at 'command did not execute successfully: "C:\\projects\\rust\\build\\i686-pc-windows-gnu\\stage0/bin\\cargo.exe" "metadata" "--format-version" "1" "--manifest-path" "C:\\projects\\rust\\src/libstd\\Cargo.toml"
expected success, got: exit code: 101', build_helper\lib.rs:113:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap build nonexistent/path/to/trigger/cargo/metadata
```

HTTP 504 is Gateway Timeout.

@bors r=alexcrichton p=1

**Comment by SimonSapin** [comment]
3 hours timeout in the `x86_64-msvc` job…

@bors: retry

**Comment by SimonSapin** [comment]
Still the same `Cargo.lock` merge conflict.

@bors r=alexcrichton

**Pull request merged**
