### PR TITLE
Rearrange `config.codegen.toml` to match `config.compiler.toml`

### PR DESCRIPTION
**Pull request by Zalathar**
This makes it easier to compare the two profiles and see which parts are different.

No functional changes.

### CODE REVIEW

**Comment by onur-ozkan** [comment]
> This makes it easier to compare the two profiles and see which parts are different.

I believe this should be handled manually by the developer (largest file is 24 lines anyway) since we can't keep all the default files synced.

These changes will hide the actual commits; checking the latest commit and its description of a line is often the preferred way to understand the reason for the existence of the line. Merging these changes doesn't seem worth in my opinion.

**Comment by Zalathar** [comment]
This is a non-functional change, so updating `change-id` should be unnecessary.

(And this change is inherently about bringing codegen & compiler in sync.)

**Comment by Zalathar** [comment]
For the specific lines being moved, the information currently exposed by `blame` seems much less valuable to me than helping humans spot the intentional differences and keep the two files in sync. (And the old blame information is one click away on GitHub.)

Anecdotally, I did find it difficult to manually identify the differences between the two files, especially when I was new to the codebase, which is what inspired me to make this change.

(Ultimately I don't plan to fight hard for this, but I do think it's a net improvement.)

**Comment by onur-ozkan** [comment]
> For the specific lines being moved, the information currently exposed by blame seems much less valuable to me than helping humans spot the intentional differences and keep the two files in sync.

The problem you are trying to solve still exists on the other configurations. We can't keep them synced manually since there's no check in CI. The actual solution to this problem would be to sync all default files with each other (no just two of them). And implementing tests and blessings on top of this which will ensure the correctness of the synchronization. However, considering that the largest default file is only 24 lines, this doesn't seem worth the effort it requires. At the end this PR doesn't solve anything other than providing a temporary workaround for your usecase.

> And the old blame information is one click away on GitHub

I typically avoid making changes to a line unless it's truly necessary and adds value. Because  trying to trace the specific reason for a line in the commit history is much harder than getting the latest commit on the line.

In most cases, you don't need to open Github if you have git plugins installed on your editor. 

e.g., from vim:

image

e.g., from vscode:

image

**Comment by onur-ozkan** [comment]
Maybe it's just me being wrong. I am happy to leave this decision to another bootstrap member.

r? @rust-lang/bootstrap

**Comment by Mark-Simulacrum** [comment]
I don't have a strong opinion either way, and given the opposition from others on the team I'm inclined to forgo this at this time.

That said, I've thought for a while that we may want to consolidate some of `[llvm]`, `[build]`, etc. blocks in configuration into a top-level block; especially if we do that it would be relatively straightforward to add `# tidy-alphabetical-start` or so markers to all of these files to continuously enforce consistency between them (modulo comments, of course).

That's more work though :)

Going to send it back to you, but if you feel strongly about this I think dropping by [#t-infra/bootstrap](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap) on Zulip to discuss it is the best bet. Otherwise we can close.

@rustbot author

**Comment by Zalathar** [comment]
I think I'll close this for now.

I had thought of this as a small and (hopefully) uncontroversial improvement, but since it's not very important and there's reluctance from the team, I'm fine with just dropping it.

**Pull request closed without merging**
