### PR TITLE
[rustdoc-json] JSON no longer inlines

### LINKED ISSUE #83057: [rustdoc-json] ICE/incorect results when reexporting with #[doc(inline)]
Similar to #80664, another ICE due to non identical items.

**Cargo.toml**
```toml
[package]
name = "ice_demo"
version = "0.1.0"
edition="2018"
[dependencies]
foo = { path = "./foo" }
```

**src/lib.rs**
```rust
#[doc(inline)]
pub use foo::Foo;

pub mod bar {
    pub use foo::Foo;
}
```
**foo/src/lib.rs**
```rust
pub struct Foo;
```

Run `cargo +nightly rustdoc -- -w json`, and it panics [here](https://github.com/rust-lang/rust/blob/215ebc364e790f6727754e5b83bf47c3696bade7/src/librustdoc/json/mod.rs#L174-L176)

```
  left: `Item { id: Id("16:3"), crate_id: 16, name: Some("Foo"), source: Some(Span { filename: "/private/tmp/ice_demo/foo/src/lib.rs", begin: (1, 0), end: (1, 15) }), visibility: Public, docs: None, links: {}, attrs: [], deprecation: None, inner: Struct(Struct { struct_type: Unit, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [], impls: [] }) }`,
 right: `Item { id: Id("16:3"), crate_id: 16, name: Some("Foo"), source: Some(Span { filename: "/private/tmp/ice_demo/foo/src/lib.rs", begin: (1, 0), end: (1, 15) }), visibility: Public, docs: None, links: {}, attrs: ["#[doc(inline)]"], deprecation: None, inner: Struct(Struct { struct_type: Unit, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [], impls: [] }) }`', src/librustdoc/json/mod.rs:175:17
```

The difference is one has `attrs: []` and the other has `attrs: ["#[doc(inline)]"]`.

This occors as `foo::Foo` is used twice, once with and once without `#[doc(inline)]`

## Non ICE versions

<del>

### Import from local

When `foo` is a internal module and not a crate, this works
```rust
mod foo {
    pub struct Foo;
}

#[doc(inline)]
pub use foo::Foo;

pub mod bar {
    pub use crate::foo::Foo;
}
```

<details>
<summary>JSON output (redacted for clarity)</summary>

```json
{
  "index": {
    "0:0": {
      "attrs": ["#![feature(no_core)]", "#![no_core]"],
      "inner": {"is_crate": true, "items": ["0:5", "0:2"]},
      "kind": "module",
      "name": "ice_demo"
    },
    "0:2": {
      "attrs": [],
      "kind": "struct",
      "name": "Foo"
    },
    "0:5": {
      "attrs": [],
      "inner": {"is_crate": false, "items": ["0:2"]},
      "kind": "module",
      "name": "bar"
    }
  },
  "paths": {
    "0:0": {"crate_id": 0, "kind": "module", "path": ["ice_demo"]},
    "0:2": {"crate_id": 0, "kind": "struct", "path": ["ice_demo", "bar", "Foo"]},
    "0:5": {"crate_id": 0, "kind": "module", "path": ["ice_demo", "bar"]}
  },
  "root": "0:0"
}
```

</details>

Here we drop the `#[doc(inline)]`, which is probably wrong.

</del>

This is actualy correct, 

### Import only once

```rust
#[doc(inline)]
pub use foo::Foo;
```

<details>
<summary>JSON output</summary>

```json
{
  "crate_version": "0.1.0",
  "external_crates": {"1": {"html_root_url": null, "name": "foo"}},
  "format_version": 4,
  "includes_private": false,
  "index": {
    "0:0": {
      "attrs": ["#![no_core]", "#![feature(no_core)]"],
      "inner": {"is_crate": true, "items": ["1:1"]},
      "kind": "module",
      "name": "ice_demo"
    },
    "0:1": {
      "attrs": ["#[doc(inline)]"],
      "inner": {"glob": false, "id": "1:1", "name": "Foo", "span": "foo::Foo"},
      "kind": "import"
    },
    "1:1": {
      "attrs": ["#[doc(inline)]"],   
      "kind": "struct",
      "links": {},
      "name": "Foo"
    }
  },
  "paths": {
    "0:0": {"crate_id": 0, "kind": "module", "path": ["ice_demo"]},
    "1:0": {"crate_id": 1, "kind": "module", "path": ["foo"]},
    "1:1": {"crate_id": 1, "kind": "struct", "path": ["foo", "Foo"]}
  },
  "root": "0:0"
}
```

</details>

This is also wrong, as id `0:1` is not referenced anywhere, and `1:1` is given `#[doc(inline)]`, even though it should have it.

cc @CraftSpider @P1n3appl3 

@rustbot modify labels: +C-bug +A-rustdoc-json +T-rustdoc +A-attributes

### LINKED ISSUE #83720: [rustdoc-json] Assertion error on reexporting item from private module with 2 names
```rust
mod style {
    pub struct Color;
}

pub use style::Color;
pub use style::Color as Colour;
```

```
rustdoc +stage1 rename.rs -w json
thread 'rustc' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 Item {
     id: Id(
         "0:2",
     ),
     crate_id: 0,
     name: Some(
<        "Color",
>        "Colour",
     ),
     span: Some(
         Span {
             filename: "rename.rs",
             begin: (
                 5,
                 4,
             ),
             end: (
                 5,
                 21,
             ),
         },
     ),
     visibility: Public,
     docs: None,
     links: {},
     attrs: [],
     deprecation: None,
     inner: Struct(
         Struct {
             struct_type: Unit,
             generics: Generics {
                 params: [],
                 where_predicates: [],
             },
             fields_stripped: false,
             fields: [],
             impls: [],
         },
     ),
 }

', src/librustdoc/json/mod.rs:179:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'w'
```

It's unlear to me what the correct representation should be, as currently for items `pub use`d from a non `pub` `mod`, we add the item to the `mod` it's being imported to, with the name it's imported under.

FWIW, in HTML, 2 seperate pages are created, each with the same content.

Eg: https://docs.rs/ansi_term/0.12.1/ansi_term/enum.Color.html and https://docs.rs/ansi_term/0.12.1/ansi_term/enum.Color.html  

(this uses the same diffing as #83718)

@rustbot modify labels: +A-rustdoc-json +T-rustdoc

### PR DESCRIPTION
**Pull request by CraftSpider**
This removes all inlining from Rustdoc-JSON. Instead, JSON preserves private modules containing public items as 'stripped' modules, indicating that they exist solely to prevent orphaning of contained items. Format version has been bumped and tests updated, as this is a significant change over previous behavior around re-exports. However, the new system fixes multiple ICEs and is generally cleaner.

Fixes #83057
Fixes #83720

### CODE REVIEW

**Comment by CraftSpider** [comment]
May want to hold off on this until either #93522 or #93524 is fixed

**Comment by GuillaumeGomez** [comment]
Waiting for them then. Please ping us when it's ready for review.

**Comment by Urgau** [comment]
I just experimented with this PR and found out that the inlining is still done for intra-doc-links.

**Comment by Urgau** [comment]
Inlining is also still done with double (maybe more, haven't tested) nested re-exports:
```rust
mod depth1 {
    mod depth2 {
        pub const C: usize = 7;
    }

    pub use self::depth2::C;
}

pub use depth1::C;
```

**Comment by GuillaumeGomez** [comment]
I took over this one in https://github.com/rust-lang/rust/pull/99287.

**Pull request closed without merging**
