### PR TITLE
Update llvm fork to 3ec14daffb4b8c0604df50b7fb0ab552f456e381

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! While you're at it could you also update to rust-lang/llvm@3ec14daffb4b8c0604df50b7fb0ab552f456e381 which includes https://github.com/rust-lang/llvm/pull/58 as well?

**Comment by nox** [comment]
@alexcrichton Done.

**Comment by xen0n** [comment]
(Hint: While you're at it, also change the PR title as that gets included in the merge commit bors creates. This helps reduce confusion e.g. when bisecting.)

**Pull request merged**
