### PR TITLE
Mark all extern functions as nounwind

### PR DESCRIPTION
**Pull request by dotdash**
This allows to skip the codegen for all the unneeded landing pads, reducing code size across the board by about 2-5%, depending on the crate. Compile times seem to be pretty unaffected though :-/

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks @dotdash! I'm excited to see how this plays out. Some thoughts of mine:

* This adds `#[nounwind]`, but doesn't end up adding it anywhere, did you mean to attach this to the allocation functions? If not, perhaps this could be left out for now?
* Could this have some codegen tests? E.g. testing for the `nounwind` attribute emission, external functions are `nounwind` by default, and calling a `nounwind` function with cleanup in scope doesn't use `invoke` but instead uses `call`.

**Comment by dotdash** [comment]
Added codegen tests for the attributes, but not for the call (as discussed on IRC) because we never use invoke an external functions anyway. Also removed the check for nounwind in invoke() because that's for rust functions only, and they don't get marked nounwind yet.

**Comment by alexcrichton** [comment]
Looks good to me, thanks! Can you also mark the [`RaiseException`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/common/unwind/seh.rs#L65-L68) function in [both places](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/common/unwind/seh64_gnu.rs#L96-L99) as being able to unwind as well? Other than that r=me

**Comment by dotdash** [comment]
@bors retry

I'm confused about this error...

**Comment by dotdash** [comment]
@bors retry

At least it hit a known intermittent failure this time...

**Pull request merged**
