### PR TITLE
Standard library OS support for Apple WatchOS

### PR DESCRIPTION
**Pull request by vladimir-ea**
This PR was split from https://github.com/rust-lang/rust/pull/98101

### CODE REVIEW

**Comment by vladimir-ea** [comment]
@thomcc 
@rustbot label +T-libs-api -T-libs

**Comment by thomcc** [comment]
Thank you. Can you make an API change proposal for this? See the bot's comment for links.

Also, I think kennytm is busy, so I'll take this since I'm fairly familiar with the platform.

r? @thomcc

**Comment by vladimir-ea** [comment]
> Thank you. Can you make an API change proposal for this? See the bot's comment for links.
> 
> Also, I think kennytm is busy, so I'll take this once that's settled since I'm fairly familiar with the platform.
> 
> r? @thomcc

Here is the issue: https://github.com/rust-lang/libs-team/issues/75

**Comment by thomcc** [comment]
Thank you.

**Comment by deg4uss3r** [comment]
Hello everyone! 

I noticed this work is a little stalled, anything I can do to help here?

**Comment by thomcc** [comment]
Thanks for the reminder, I had meant to follow-up here. This needs API team decision, so I've marked it as nominated, and given a brief writeup here https://github.com/rust-lang/libs-team/issues/75#issuecomment-1246231522. It will be discussed next week in the API team meeting.

**Comment by thomcc** [comment]
So, we discussed this in the most recent libs-api meeting. The outcome is that we'd like to only export these via `std::os::unix`, rather than having a watchos-specific public module. Could you make that change?

**Comment by deg4uss3r** [comment]
@vladimir-ea are you around to make this change?

**Comment by vladimir-ea** [comment]
> So, we discussed this in the most recent libs-api meeting. The outcome is that we'd like to only export these via `std::os::unix`, rather than having a watchos-specific public module. Could you make that change?

Pushed the change (`pub mod watchos` -> `pub(crate) mod watchos` in library/std/src/os/mod.rs).

Thank you @thomcc for taking the time to discuss this / make it right.

**Comment by thomcc** [comment]
Thanks! Glad to see it, everything looks fine.

@bors r+

**Pull request merged**
