### PR TITLE
[std] Osstr lossy example

### PR DESCRIPTION
**Pull request by jnqnfe**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Can this be implemented as an example without making it memory unsafe though? As-is this is susceptible to future breakage because the example itself is exhibiting memory unsafety.

**Comment by jnqnfe** [comment]
> Thanks for the PR! Can this be implemented as an example without making it memory unsafe though? As-is this is susceptible to future breakage because the example itself is exhibiting memory unsafety.

The only options are (as far as I can see)
a) doing it the way I have, via an unchecked String
b) transmuting a byte array, which I'd assume you'd object to more
c) splitting the example to work differently on different platforms, to take advantage of the from-byte-slice unix extension method, which would be a mess

otherwise the OsStr methods in std would need to be extended to provide a cleaner solution

fyi, this and a couple of other similar push requests were a precursor to a further push request to extend OsStr handling in std to allow splitting, as needed by an upcoming v2.0 of my cmd-line arg parsing library (which is currently having to transmute). I started investigating how best to implement that, but never got around to finishing. The best solution for that would likely be to just open up from/to byte array methods, perhaps with method names like `to_storage_byes` to try to help reinforce the message that OsStr does not store the string in the OS form on some platforms.

**Comment by alexcrichton** [comment]
Yes to implement this the best way would be via the OS extension traits such as `OsStr::from_bytes` on Unix.

**Comment by Aaronepower** [comment]
Triage; @jnqnfe Hello, have you been able to get back to this PR?

**Comment by jnqnfe** [comment]
@Aaronepower @alexcrichton Yes, sorry for the delay, I'm largely working offline with no internet from home.

I've reworked the change as suggested. I also fixed it so that it will actually work correctly on Windows, having corrected a misunderstanding from not examining closely enough what the Windows/WTF-8 to-lossy code was doing.

**Comment by alexcrichton** [comment]
@bors: r+

Looks good to me, thanks!

**Pull request merged**
