### PR TITLE
Fix incorrect return type error diagnostic

### LINKED ISSUE #58982: Mismatched types diagnostic sometimes points at both return type and return statement for the expectation reason
[The output for](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ace0042d07550c5b32e79be3cd9f0524) the following code is slightly incorrect and shouldn't really point at the value of the `return` statement:

```
fn foo(bar: usize) -> usize {
    if bar % 5 == 0 {
        return 1;
    };
}

fn main() {
    println!("Hello, {}!", foo(1))
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:1:23
  |
1 | fn foo(bar: usize) -> usize {
  |    ---                ^^^^^ expected usize, found ()
  |    |
  |    this function's body doesn't return
2 |     if bar % 5 == 0 {
3 |         return 1;
  |                - expected because of this statement
  |
  = note: expected type `usize`
             found type `()`
```

### PR DESCRIPTION
**Pull request by pmccarter**
Fixes #58982 

This fixes the case by highlighting the previous return site span only when the coercion target is a type variable (eg when return type is impl Trait determined by the function body).

### CODE REVIEW

**Review by matthewjasper — CHANGES_REQUESTED** [review]
Can this be rebased and retargeted on master?

**Comment by pmccarter** [comment]
@matthewjasper as far as I can tell this only applies to the stable branch (you can check the playground linked from the issue).

**Comment by matthewjasper** [comment]
In that case there just needs to be a test added for this (on master). Stable will be fixed with the next release.

**Comment by kennytm** [comment]
A new stable has been branched off and will be released in 3 days. Let's just close this?

**Pull request closed without merging**
