### PR TITLE
Fast-path some binder relations

### LINKED ISSUE #104583: Exponential compile time with nested `&dyn Fn` type
Found with a [modified fuzz-rustc](https://github.com/jruderman/fuzz-rustc)

### Code

```rust
fn id(
    f: &dyn Fn(u32)
) -> &dyn Fn(
    &dyn Fn(
        &dyn Fn(
            &dyn Fn(&dyn Fn(&dyn Fn(&dyn Fn(&dyn Fn(&dyn Fn(&dyn Fn(&dyn Fn(&dyn Fn(u32)))))))))
        )
    )
) {
    f
}

fn main() {}
```

### Time complexity

Seems exponential:

| Nesting level | Time |
|---------------|------|
| 9  |  0.9 sec |
| 10 |  4.2 sec |
| 11 |  17 sec |
| 12 |  80 sec |

### Where it's slow

* From `-Z time-passes`: `item_bodies_checking` ([full output](https://github.com/rust-lang/rust/files/10044169/ztp.txt))
* From sampling: seems like recursion involving type inference ([head of sample tree](https://github.com/rust-lang/rust/files/10044156/Sample.head.txt))

### Not a recent regression

It's slow at least as far back as nightly-2018-01-01

### Version

```
rustc 1.67.0-nightly (a00f8ba7f 2022-11-15)
binary: rustc
commit-hash: a00f8ba7fcac1b27341679c51bf5a3271fa82df3
commit-date: 2022-11-15
host: x86_64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

@rustbot label +I-compiletime

### PR DESCRIPTION
**Pull request by compiler-errors**
A simpler approach than #104598

Fixes #104583

r? types

### CODE REVIEW

**Comment by compiler-errors** [comment]
This should come back with no results or just noise, but just checking

@bors try @rust-timer queue

**Review by spastorino — APPROVED** [review]

**Comment by compiler-errors** [comment]
Just needed a bless after Esteban's large type sizes PR

@bors r=oli-obk

**Comment by lqd** [comment]
I won't mark it as triaged now, but I'm pretty sure this is noise, and these benchmarks returning to their stable state: basically the opposite of the wins in https://github.com/rust-lang/rust/pull/105436#issuecomment-1347858645. We can look at these benchmarks' numbers in a few merged PRs (or by weekly triage) to make sure, but this has happened before.

**Comment by compiler-errors** [comment]
I'm pretty certain this is noise, yeah.

**Comment by rylev** [comment]
Marking as resolved. The regression cancel out the improvements in the exact same test cases from the previous commit which is a very strong indicator that this is noise.

@rustbot label: +perf-regression-triaged

**Pull request merged**
