### PR TITLE
rustdoc: update to pulldown-cmark 0.11

### PR DESCRIPTION
**Pull request by notriddle**
r? rustdoc

This pull request updates rustdoc to the latest version of pulldown-cmark. Along with adding new markdown extensions (which this PR doesn't enable), the new pulldown-cmark version also fixes a large number of bugs. Because all text files successfully parse as markdown, these bugfixes change the output, which can break people's existing docs.

A crater run, https://github.com/rust-lang/rust/pull/121659, has already been run for this change.

The first commit upgrades and fixes rustdoc. The second commit adds a lint for the footnote and block quote parser changes, which break the largest numbers of docs in the Crater run. The strikethrough change was mitigated in pulldown-cmark itself.

Unblocks https://github.com/rust-lang/rust-clippy/pull/12876

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
YES, FINALLY! Thanks so much for this update! r=me once CI pass

**Comment by matthiaskrgr** [comment]
@bors r- rollup=iffy
guess this causes this? https://github.com/rust-lang/rust/pull/127148#issuecomment-2198476637

**Comment by Zalathar** [comment]
One of the coverage-related comments that was being fixed by this PR has been rewritten by another PR (removing the incorrect syntax), hence the conflict.

**Comment by Kobzol** [comment]
This was an update to a newer version of a third-party dependency, so nothing much that we can do here. The update also apparently resolves several bugs. Marking as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
