### PR TITLE
Improvements to building and CI for mingw/msys

### LINKED ISSUE #105696: Build of GNU toolchain 1.66.0 on Windows fails on rustbuild config.rs when git is installed in MSYS
Problem: The build of GNU toolchain 1.66.0 on Windows is failing in the rustbuild step when it's trying to locate git (MSYS git-2.38.1-1) .

Build steps:
- install Windows, MSYS2
- install dependencies according to https://github.com/rust-lang/rust#mingw
- clone Rust 1.66.0 code
- run:

```
python3 src/bootstrap/configure.py --release-channel=nightly --enable-extended --tools=clippy,cargo,rustfmt --dist-compression-formats='xz'
python3 x.py dist --stage 2
```

Failure:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', config.rs:863:74
```

Snippet from stack trace of rustbuild:
```
34:     0x7ff77f1114e6 - mainCRTStartup
                               at C:\M\mingw-w64-crt-git\src\build-MINGW64\C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:206:9
```

Workaround:
- remove MSYS2 git
```
pacman -R git
```

After removing MSYS2 git the build pass without problem. The issue was not present in 1.65.0.

### LINKED ISSUE #117567: Unable to build with on Windows 10 with MinGW nor MSVC
Hi, I'm trying to build on Windows and running into problems.

------------

I'm following the readme and starting with a clean Windows 10 machine, installing `git`, `python` and `cmake` with `winget`.

From there, with the MinGW build I use pacman to install the listed packages, and invoke 

```
python x.py setup user && python x.py build && python x.py install
```

After a while, it eventually fails with the error message

```
   Compiling clap_complete v4.4.3
   Compiling build_helper v0.1.0 (C:\actions-runner\_work\enzyme\rust\src\tools\build_helper)
    Finished dev [unoptimized] target(s) in 31.59s
thread 'main' panicked at src\core\config\config.rs:1156:74:
called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot
 find the path specified." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:47
```

Which is similar to https://github.com/rust-lang/rust/issues/105696. In that issue, they mention that the main readme instructions are wrong (but still haven't been updated) and that `git` installed by `pacman` is the source of the problem, so I removed it and reran the python scripts (from a mingw terminal)

```
$ python x.py setup user && python x.py build && python x.py install
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.17s
error: no `setup` rules matched ["user"]
```

I'm not sure what to make of this error, so I thought I'd also try building with the MSVC toolchain and see if that works.

-------------

For the MSVC build, I downloaded visual studio and installed the Windows 10 SDK and C++ x64/86 build tools packages. Then, when running `x.py` again from `cmd.exe` I get the same kind of error

```
> python x.py setup user
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.12s
error: no `setup` rules matched ["user"]
```

----------

Can anyone help me understand what I'm doing wrong?

Thanks

### PR DESCRIPTION
**Pull request by majaha**
I was getting error messages when trying to follow the build instructions the mingw build for Rust, and managed to track the issue down to an incomparability of Rust's bootstrap program with MSYS2's version of git. Essentially, the problem is that MSYS2's git works in emulated unix-y paths, but bootstrap expects a Windows path. I found a workaround for this by using relative paths instead of absolute paths.

Along with that fix, this PR also updates the build instructions for MinGW to be compatible with modern versions of MSYS2, and some changes to CI to make sure that MSYS2's version of git is tested. In particular, I'm suggesting using the [MSYS2 github action](https://github.com/marketplace/actions/setup-msys2) specially made for this purpose, which is much less hacky than the old approach and gives us more control of what packages are installed. I also cleaned up as many alternate versions of key tools as I could find from PATH, to avoid accidental usage, and cleaned up some abuses of the `CUSTOM_MINGW` environment variable.

This fixes https://github.com/rust-lang/rust/issues/105696 and fixes https://github.com/rust-lang/rust/issues/117567

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @mati865 -- perhaps you can weigh in here? My knowledge of Windows isn't deep enough to say whether this moves us in the right direction or how closely affiliated the msys2 org/github action is with the upstream project (i.e. is trusting it equivalent to trusting msys2 artifacts?). We may still want to replicate the artifacts as I think we were doing before into our own cache regardless...

**Comment by mati865** [comment]
> how closely affiliated the msys2 org/github action is with the upstream project

`msys2/setup-msys2` is the official GH Action maintained by MSYS2 and the recommend way to install it.

> whether this moves us in the right direction

I'm currently ill and don't want to make any statements because of my impaired ability to understand the code.
Since the problem in #105696 is caused by MSYS2 git returning UNIX style paths (like `/c/rust/src/whatever`) I think it might be simpler to just call `cygpath` (with `-w` or `-m` depending or what bootstrap expects) on paths passed to obtained from git.
Conversion from UNIX to Windows (`cygpath -w`) would give `C:\rust\src\whatever` and conversion to mixed (`-cygpath -m`) would give give `C:/rust/src/whatever`.
Other alternative would be to use a library that would give bootstrap the proper path from the beginning like gix https://github.com/rust-lang/rust/pull/110369 or git2-rs.

**Comment by majaha** [comment]
I did think about Cygpath, but just getting git to give us the path of `../../../`s we need seemed like a simpler solution to me.

**Comment by mati865** [comment]
In overall looks good but I'm not sure whether Rust should install MSYS2 each time as it adds another possible point of failure to the CI. However if the caching works good this might not be a problem.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and approve. I'm not an expert on this area but my sense is that this should be easy to revert if needed, so that's my preferred approach here.

@bors r+

**Comment by ChrisDenton** [comment]
Just a note but it seems that the mingw builders are now the slowest by roughly 20 to 30 minutes.

|Job|Time|
|--|--|
|auto - i686-mingw|2h 22m|
|auto - x86_64-mingw|2h 20m|
|auto - dist-x86_64-linux-alt|1h 55m|

This is a fair increase from the roughly 1hr 40m it took before. I don't know if that was expected.

**Comment by Mark-Simulacrum** [comment]
That doesn't sound expected to me. I'd be in favor of reverting and adjusting as needed before relanding.

**Comment by mati865** [comment]
Agreed. Initially, I thought it might be a cache issue that would hopefully improve. But on second thought, I think it's just the slowness of Cygwin/MSYS2 Git.
I'll try to check the logs later today, but I think the revert is well justified.

**Comment by mati865** [comment]
Sorry, haven't managed to take a look yesterday.
Looking at `auto` branch build:
- before this PR: https://github.com/rust-lang-ci/rust/actions/runs/8040180131/job/21957991997
  - repo clone: 37s
  - submodules checkout: 1m 27s
  - tidy: `[TIMING] core::build_steps::test::Tidy Tidy -- 39.564`
  - bootstrap tests: `[TIMING] core::build_steps::test::Bootstrap Bootstrap -- 187.457`
- after the merge: https://github.com/rust-lang-ci/rust/actions/runs/8065622298/job/22031836054
  - repo clone: 1m 57s
  - submodules checkout: 3m 13s
  - MSYS2 install: 8m 34s, it's not MSYS2 that is slow but the script that removes preinstalled tools: https://github.com/rust-lang/rust/blob/ef324565d071c6d7e2477a195648549e33d6a465/src/ci/scripts/install-msys2.sh#L34-L39
  - tidy: `[TIMING] core::build_steps::test::Tidy Tidy -- 113.468`
  - bootstrap tests: `[TIMING] core::build_steps::test::Bootstrap Bootstrap -- 1939.995`

So indeed everything that uses Git became much slower and I don't see any way to regain the performance other than reverting CI changes part of this PR.

**Comment by majaha** [comment]
Unfortunately, MSYS's Git is just slow. I thought it would be neater if it were tested in CI so that we can confidently suggest using it in the build instructions. But if it really is unbearably slow, we could perhaps take another approach. Maybe we could tell people to steer clear of MSYS Git and just install Git-for-Windows instead, although that's a bit of a pain to have to install a separate thing.

I don't understand the difference in time for the "checkout the source code" step, there shouldn't be a difference. Although taking a closer look, maybe the "disable git crlf conversion" step isn't applying to the checkout action because the config is going in the wrong home directory, and the extra work of expanding the line endings accounts for the extra time taken? (We *could* run that script twice, once in MSYS Bash and once in Git Bash, to make sure it gets configured everywhere).

For `install-msys2.sh`, that script is also installing things from network, which could be slowing it down. But it's also quite possible that deleting all those files is also what's slowing it down. (Maybe we could just `mv` them off path instead?)

I think quite a lot of this would be sped up by just moving back to using Git-for-Windows for mingw builds, but if we do that we should probably list it as a stronger requirement in the build instructions.

**Comment by mati865** [comment]
> I don't understand the difference in time for the "checkout the source code" step, there shouldn't be a difference.

Sorry, I was sleepy and haven't realised MSYS2 is installed after the checkout. Longer checkout must have been a noise.

> For install-msys2.sh, that script is also installing things from network, which could be slowing it down. But it's also quite possible that deleting all those files is also what's slowing it down. (Maybe we could just mv them off path instead?)

If you enable timestamps you can see:
```
Tue, 27 Feb 2024 13:42:03 GMT installing pactoys...
Tue, 27 Feb 2024 13:49:37 GMT resolving dependencies...
Tue, 27 Feb 2024 13:49:38 GMT looking for conflicting packages...
Tue, 27 Feb 2024 13:49:38 GMT
Tue, 27 Feb 2024 13:49:38 GMT Packages (33) mingw-w64-x86_64-brotli-1.1.0-1 
```
Which means CI spent 7 minutes between lines https://github.com/rust-lang/rust/blob/ef324565d071c6d7e2477a195648549e33d6a465/src/ci/scripts/install-msys2.sh#L29 and https://github.com/rust-lang/rust/blob/ef324565d071c6d7e2477a195648549e33d6a465/src/ci/scripts/install-msys2.sh#L47
Pactoys install is fast because it's tiny so calling `rm` is the only thing left.

> I think quite a lot of this would be sped up by just moving back to using Git-for-Windows for mingw builds, but if we do that we should probably list it as a stronger requirement in the build instructions.

I'll revive https://github.com/rust-lang/rust/pull/110369 over the weekend and see if build time of newer version is acceptable. It should be even faster than Git for Windows.

**Comment by mati865** [comment]
> I'll revive https://github.com/rust-lang/rust/pull/110369 over the weekend and see if build time of newer version is acceptable. It should be even faster than Git for Windows.

With the latest version the time goes from 10s to 13s on my PC so about 30% increase, definitely an improvement but still not ideal.

@majaha are you going to revert CI changes?

**Comment by majaha** [comment]
> With the latest version the time goes from 10s to 13s on my PC so about 30% increase, definitely an improvement but still not ideal.
Sorry, could you explain what those numbers were measurements of?

I'd rather not revert all the CI changes as I think parts of it are more sensible than what was there before. But I'm willing to try and fix up the main issues, if you wouldn't mind pointing me to what you think they are.

The biggest issue is this: `bootstrap tests: [TIMING] core::build_steps::test::Bootstrap Bootstrap -- 1939.995`
Running the tests for bootstrap takes over 30 minutes by itself. I've noticed that bootstrap became excruciatingly slow with MSYS's git in my own testing. I'm sure this will be fixed by reverting back to Git-for-Windows, so I think we should start there. I'll try to make a pull request for that tomorrow evening.

**Comment by mati865** [comment]
> Sorry, could you explain what those numbers were measurements of?

It was regarding part the comment that I quoted:
> I'll revive https://github.com/rust-lang/rust/pull/110369 over the weekend and see if build time of newer version is acceptable. It should be even faster than Git for Windows.

What that PR did was avoiding calling Git binary by using a native library so we avoid Cygwin issues. The downside is longer build time for bootstrap binary and this is shown by those numbers (tested on Linux).

> I'm willing to try and fix up the main issues, if you wouldn't mind pointing me to what you think they are.

As you already noticed reverting back to GfW would cut down significant amount of time.
Another thing to consider is doing `mv` instead of `rm` if you want to get rid of preinstalled tools but I think it might be unnecessary.

**Comment by majaha** [comment]
I've made the pull request to revert the git change: https://github.com/rust-lang/rust/pull/122125

**Comment by majaha** [comment]
Having a quick flick through this log: https://github.com/rust-lang-ci/rust/actions/runs/8220783357/job/22480355462

It seems like cleaning up the tools by rm-ing them is taking four to seven minutes. I'm going to go ahead and write the patch that moves them instead.

**Comment by majaha** [comment]
Patch is up over here: https://github.com/rust-lang/rust/pull/122321

**Pull request merged**
