### PR TITLE
rustdoc: Add doc snippets for trait impls, with a read more link

### LINKED ISSUE #33672: Trait implementations should show summary line in documentation
We've always been unsure how much information to show about implementations, and right now, we only show signatures. [On HN](https://news.ycombinator.com/item?id=11708981) someone suggested that including the summary line would be helpful, so that you can understand what these things actually do, if you haven't used that particular trait before.

### PR DESCRIPTION
**Pull request by Manishearth**
The read more link only appears if the documentation is more than one line long.

screenshot from 2016-05-17 06 54 14

It currently does not appear on non-defaulted methods, since you can document them directly. I could make it so that default documentation gets forwarded if regular docs don't exist.

Fixes #33672

r? @alexcrichton 

cc @steveklabnik

### CODE REVIEW

**Comment by Manishearth** [comment]
Added support for a fallback to short docs

The following code produces the pictured docs:

```rust
pub struct Foo<'a>(&'a str);

impl<'a> Iterator for Foo<'a> {
  type Item = &'a str;
  fn next(&mut self) -> Option<&'a str> {
    Some(self.0)
  }

  /// All your docs are
  ///
  /// belong to us
  fn size_hint(&self) -> (usize, Option<usize>) {
   (1,None)
  }
}
```

screenshot from 2016-05-17 07 30 52

Note that the show more link isn't shown on `Item`, since it has only one line of docs. `size_hint` has an overridden impl so its docs are shown in full. Everything else defaults to the regular `Iterator` docs.

**Comment by Manishearth** [comment]
The formatting for "read more" could probably be improved, suggestions?

**Comment by nrc** [comment]
Why have the +/- expand box and "read more"? Why not show all the description, but have it hidden by default?

**Comment by Manishearth** [comment]
That's another option, I guess. Is there anything else we collapse by default?

**Comment by pcwalton** [comment]
How about putting "Read more" on the same line to save space?

"Consumes the iterator, returning the last element. _More..._"

**Comment by Manishearth** [comment]
That can work. I didn't do it because it requires some markdown splicing, but that's no big deal

**Comment by Manishearth** [comment]
I don't have a preference of any one of the suggestions -- @alexcrichton, do you? Both are easy to implement.

**Comment by GuillaumeGomez** [comment]
> Why have the +/- expand box and "read more"? Why not show all the description, but have it hidden by default?

I like it.

@Manishearth: How do you know it's only one line?

**Comment by Manishearth** [comment]
> @Manishearth: How do you know it's only one line?

That's how the snippet function works

**Comment by GuillaumeGomez** [comment]
> That's how the snippet function works

I guess it's based on the characters' number. I don't really like this if this is really the case.

**Comment by Manishearth** [comment]
I don't know what you mean? I think it just extracts the first line, in a markdown-aware way. It's already used for documenting modules and in search results

**Comment by GuillaumeGomez** [comment]
I thought you said that if the description was only _one_ short line, no need to hide it. And I was wondering how you decided if it was short.

**Comment by Manishearth** [comment]
I don't decide if it's short. The heuristic is if it's a single line, I don't show a "Read more" link - See https://github.com/rust-lang/rust/pull/33679/files#diff-05c3c8b7c08a25764218b8c18d8204b7R1672

**Comment by alexcrichton** [comment]
@Manishearth yeah I like @pcwalton's suggestion of placing the link on the same line to cut down on space (that's why these links were omitted in the first place). Also, could you build libstd docs and provide a link so we can browse around as well? It'd probably help to see what this look like in practice as well.

Nice idea though!

**Comment by mitaa** [comment]
Perhaps the "read more" could be expanded in-place instead of linking to another page?

**Comment by Manishearth** [comment]
@alexcrichton like this? http://manishearth.github.io/rust-internals-docs/std/collections/hash_set/struct.IntoIter.html

**Comment by GuillaumeGomez** [comment]
@Manishearth: Like this it's just great! Thanks a lot for this!

**Comment by alexcrichton** [comment]
Looks good to me! Can you also add a test to ensure that the longer form docs are omitted? That is, if there's multiple lines, none but the first show up in the output

**Comment by Manishearth** [comment]
Done

**Comment by Manishearth** [comment]
Ah, that was a legit error, I wasn't ignoring static methods for Deref.

There are a bunch of failures for internals docs though (haven't investigated yet, it could just be this bug)

```
rustc_typeck/check/regionck/struct.Rcx.html:94: broken link fragment  `#method.visit_ident` pointing to `rustc_typeck/hir/intravisit/trait.Visitor.html`
rustc_typeck/check/regionck/struct.Rcx.html:114: broken link fragment  `#method.visit_explicit_self` pointing to `rustc_typeck/hir/intravisit/trait.Visitor.html`
std/ffi/struct.CString.html:181: broken link fragment  `#method.from_ptr` pointing to `std/ffi/struct.CString.html`
std/ffi/struct.CString.html:182: broken link fragment  `#method.from_bytes_with_nul` pointing to `std/ffi/struct.CString.html`
std/ffi/struct.CString.html:183: broken link fragment  `#method.from_bytes_with_nul_unchecked` pointing to `std/ffi/struct.CString.html`
rustc/ty/index.html:55: broken link - rustc/ty/sty/BuiltinBound/index.html
rustc/ty/index.html:57: broken link - rustc/ty/sty/BuiltinBound/index.html
rustc/ty/index.html:59: broken link - rustc/ty/sty/BuiltinBound/index.html
rustc/ty/index.html:61: broken link - rustc/ty/sty/BuiltinBound/index.html
syntax/parse/token/struct.InternedString.html:68: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:128: broken link - syntax/parse/token/primitive.u8.html
syntax/parse/token/struct.InternedString.html:402: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:404: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:429: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:441: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:445: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:446: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:448: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:472: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:622: broken link - syntax/parse/token/option/enum.Option.html
syntax/parse/token/struct.InternedString.html:624: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:656: broken link - syntax/parse/token/option/enum.Option.html
syntax/parse/token/struct.InternedString.html:658: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:689: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:693: broken link - syntax/parse/token/iter/trait.DoubleEndedIterator.html
syntax/parse/token/struct.InternedString.html:695: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:756: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:761: broken link - syntax/parse/token/iter/trait.DoubleEndedIterator.html
syntax/parse/token/struct.InternedString.html:791: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:801: broken link - syntax/parse/token/iter/trait.DoubleEndedIterator.html
syntax/parse/token/struct.InternedString.html:803: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:821: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:854: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:893: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:924: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:928: broken link - syntax/parse/token/iter/trait.DoubleEndedIterator.html
syntax/parse/token/struct.InternedString.html:930: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:948: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:953: broken link - syntax/parse/token/iter/trait.DoubleEndedIterator.html
syntax/parse/token/struct.InternedString.html:974: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:978: broken link - syntax/parse/token/iter/trait.DoubleEndedIterator.html
syntax/parse/token/struct.InternedString.html:980: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:1004: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:1009: broken link - syntax/parse/token/iter/trait.DoubleEndedIterator.html
syntax/parse/token/struct.InternedString.html:1099: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:1120: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:1142: broken link - syntax/parse/token/primitive.char.html
syntax/parse/token/struct.InternedString.html:1174: broken link - syntax/parse/token/str/trait.FromStr.html
syntax/parse/token/struct.InternedString.html:1177: broken link - syntax/parse/token/str/trait.FromStr.html
syntax/parse/token/struct.InternedString.html:1204: broken link - syntax/parse/token/string/struct.String.html
syntax/parse/token/struct.InternedString.html:1222: broken link - syntax/parse/token/string/struct.String.html
syntax/parse/token/struct.InternedString.html:1254: broken link - syntax/parse/token/string/struct.String.html
syntax/parse/token/struct.InternedString.html:1280: broken link - syntax/parse/token/string/struct.String.html
syntax/util/interner/struct.RcStr.html:58: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:118: broken link - syntax/util/interner/primitive.u8.html
syntax/util/interner/struct.RcStr.html:392: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:394: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:419: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:431: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:435: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:436: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:438: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:462: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:612: broken link - syntax/util/interner/option/enum.Option.html
syntax/util/interner/struct.RcStr.html:614: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:646: broken link - syntax/util/interner/option/enum.Option.html
syntax/util/interner/struct.RcStr.html:648: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:679: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:683: broken link - syntax/util/interner/iter/trait.DoubleEndedIterator.html
syntax/util/interner/struct.RcStr.html:685: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:746: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:751: broken link - syntax/util/interner/iter/trait.DoubleEndedIterator.html
syntax/util/interner/struct.RcStr.html:781: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:791: broken link - syntax/util/interner/iter/trait.DoubleEndedIterator.html
syntax/util/interner/struct.RcStr.html:793: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:811: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:844: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:883: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:914: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:918: broken link - syntax/util/interner/iter/trait.DoubleEndedIterator.html
syntax/util/interner/struct.RcStr.html:920: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:938: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:943: broken link - syntax/util/interner/iter/trait.DoubleEndedIterator.html
syntax/util/interner/struct.RcStr.html:964: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:968: broken link - syntax/util/interner/iter/trait.DoubleEndedIterator.html
syntax/util/interner/struct.RcStr.html:970: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:994: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:999: broken link - syntax/util/interner/iter/trait.DoubleEndedIterator.html
syntax/util/interner/struct.RcStr.html:1089: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:1110: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:1132: broken link - syntax/util/interner/primitive.char.html
syntax/util/interner/struct.RcStr.html:1164: broken link - syntax/util/interner/str/trait.FromStr.html
syntax/util/interner/struct.RcStr.html:1167: broken link - syntax/util/interner/str/trait.FromStr.html
syntax/util/interner/struct.RcStr.html:1194: broken link - syntax/util/interner/string/struct.String.html
syntax/util/interner/struct.RcStr.html:1212: broken link - syntax/util/interner/string/struct.String.html
syntax/util/interner/struct.RcStr.html:1244: broken link - syntax/util/interner/string/struct.String.html
syntax/util/interner/struct.RcStr.html:1270: broken link - syntax/util/interner/string/struct.String.html
rustc_plugin/index.html:88: broken link - /home/manishearth/Mozilla/rust/book/compiler-plugins.html
rustc_trans/middle/const_val/enum.ConstVal.html:53: broken link - rustc_const_math/int/ConstInt/index.html
thread '<main>' panicked at 'found some broken links', main.rs:54
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Manishearth** [comment]
Fixed.


the internals errors listed above still exist

**Comment by solson** [comment]
Would it be possible to override this with impl-specific documentation for methods? (Is there already an issue for that?)

**Comment by Manishearth** [comment]
This already happens

**Pull request merged**
