### PR TITLE
for RustyHermit avoid the import of std/src/os/unix

### PR DESCRIPTION
**Pull request by stlankes**
`std/src/os/hermit` is already available and should be used by `std/src/sys/hermit`. It should also make the code more understandable.

### CODE REVIEW

**Comment by stlankes** [comment]
@thomcc This PR breaks the backward compatability. The previous version provides `std::os::unix ` and crates like `https://github.com/dylni/os_str_bytes` have to change the path to [os related implementations](https://github.com/dylni/os_str_bytes/blob/d5e8e981a07ab020abc77f95e589a8063d956155/src/common/mod.rs#L11-L12).

**Comment by thomcc** [comment]
... I don't think that we can break backwards compat even for tier 3 targets. Can you file an ACP if you think I'm mistaken and this is a case worth considering?

**Comment by thomcc** [comment]
I also don't really think this makes things better -- it means code will require extra special casing in order to support hermit, for what appears to be no reason?

**Comment by thomcc** [comment]
I think we can't take this, as it's a breaking change, which seems to be the whole point of the submission. Sorry.

I also don't understand the motivation, so feel free to reopen if I've missed something.

**Comment by thomcc** [comment]
Also, feel free to open an issue, or start a thread on [Zulip](https://rust-lang.zulipchat.com) or [IRLO](https://internals.rust-lang.org/) about this. I do feel a little unsure, and tier 3 platforms are probably more of a grey area than I had believed.

In particular, if the consensus among the Hermit maintainers is that that we should not consider it Unix (and thus export `std::os::unix`), I think there's a good chance we'd take it seriously (even if it is a breaking change).

**Comment by thomcc** [comment]
I'll reopen because on further thought I may have closed this prematurely.

**Comment by stlankes** [comment]
Hm, you are right. This PR is critical. I start to write something like `FromRawFd` and this is for RustyHermit different in comparison to the unix implementation. I was looking for the right place and thought that [src/os/hermit](https://github.com/rust-lang/rust/tree/master/library/std/src/os/hermit) is the right location. The directory is already there and I think that it is currently not used. Or do I miss something?

**Comment by thomcc** [comment]
> The directory is already there and I think that it is currently not used.

It was used and is the source for the `std::os::unix` module on hermit:

```rs
#[path = "hermit/mod.rs"]
pub mod unix;
```
This means "The source for the `unix` module is located at `"hermit/mod.rs"`".

**Comment by thomcc** [comment]
Anyway this is an API change so it's a libs-api issue.

**Comment by stlankes** [comment]
Ah, got it! I will think about it and close in the meantime this PR.

**Pull request closed without merging**
