### PR TITLE
Add `DisplayAsDebug` - A struct to help with Debug impls

### PR DESCRIPTION
**Pull request by Centril**
This adds a simple wrapper:
```rust
pub struct DisplayAsDebug<T>(pub T);

impl<T: fmt::Display> fmt::Debug for DisplayAsDebug<T> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        <T as fmt::Display>::fmt(&self.0, fmt)
    }
}

```

r? @alexcrichton

### CODE REVIEW

**Comment by sfackler** [comment]
We can be a bit more flexible here and be generic over `T: Display`.

**Comment by Centril** [comment]
@sfackler Interesting... so rename to `DebugDisplay`?

**Comment by Centril** [comment]
And now we are more flexible with `DebugDisplay` ;)

**Comment by sfackler** [comment]
I've written this a couple of places when I've needed to do something like this. It's a tiny little utility, but I think nice to have.

@rfcbot fcp merge

**Comment by SimonSapin** [comment]
Bikeshed: `DebugAsDisplay`?

**Comment by sfackler** [comment]
Yeah, I was kind of thinking that an `As` in the middle would be good as well.

**Comment by Centril** [comment]
Totally agree with the `As` bit;

Per discussion on #rust-libs I went with `DisplayAsDebug` since you are "converting" a `Display` impl in effect to a `Debug` impl.

**Comment by alexcrichton** [comment]
@rfcbot concern exists

Thanks @kennytm! Looks like this may [already exist](https://github.com/rust-lang/rust/blob/8aa27ee30972f16320ae4a8887c8f54616fff819/src/libcore/fmt/mod.rs#L426-L431) in libstd?

**Comment by Centril** [comment]
Some thoughts:
1. I had no idea that `Arguments` had this behavior -- so this was entirely unexpected. Is this a guarantee of `format_args!` / `Arguments` to behave in this way tho? If so - it should be documented somewhere.

2. The specific case above can be shortened to: `format_args!("_")`.

3. There's a minor overhead: `16` bytes vs. `48` -- it's not much (so it probably does not warrant an extra type), but I thought I'd mention it.

**Comment by SimonSapin** [comment]
Interesting! I think I’m now in favor of closing this RFC and either adding a new example or modifying existing examples to show this use of `format_args!` in the docs of `fmt::Formatter::debug_{struct,tuple,list,set,map}` and `fmt::Debug{Struct,Tuple,List,Set,Map}`.

**Comment by dtolnay** [comment]
:+1: for directing people to `format_args!` for this use case. @rfcbot fcp close

**Comment by dtolnay** [comment]
@rfcbot fcp cancel

**Comment by dtolnay** [comment]
@rfcbot fcp close

**Comment by Centril** [comment]
I'll expedite the process and close the PR myself ;)

**Pull request closed without merging**
