### PR TITLE
Don't ICE when encountering bound regions in generator interior type

### PR DESCRIPTION
**Pull request by compiler-errors**
I'm pretty sure this meant to say "`has_free_regions`", probably just a typo in 4a4fc3bb5b1efe6857cf5d6c0b554ff36b966996. We can have bound regions (because we only convert non-bound regions into existential regions in generator interiors), but we can't have (non-ReErased) free regions.

r? lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
maybe change it to `!ty.has_free_regions() && !ty.has_escaping_bound_vars()`

> We can have bound regions (because we only convert non-bound regions into existential regions in generator interiors), but we can't have (non-ReErased) free regions.

given the fact that nested bound regions clearly must exist, it did take me a few minutes to actually understand what this meant here. Though, given that we ICE when `tcx.fold_regions` encounters a non-erased region, do we even need the `debug_assert` in the first place?

**Comment by compiler-errors** [comment]
lol I pushed at the same time as the r+

@bors -

**Review by lcnr — COMMENTED** [review]
please add a "FIXME: use `bound_coroutine_hidden_types` instead and work towards removing this to `coroutine_hidden_types`". r=me after

**Comment by lcnr** [comment]
❤️ 

@bors r+ rollup

**Pull request merged**
