### PR TITLE
update RLS and rustfmt

### LINKED ISSUE #83459: `rls` no longer builds after rust-lang/rust#83454
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#83454, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @JohnTitor, do you think you would have time to do the follow-up work?
If so, that would be great!

### LINKED ISSUE #83460: `rustfmt` no longer builds after rust-lang/rust#83454
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#83454, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @JohnTitor, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #83460 and fixes #83459

cc @Xanewok

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors delegate+

r=me

**Comment by calebcartwright** [comment]
@Xanewok - I think RLS would need https://github.com/rust-lang/rls/pull/1725 in order to address the build issue, would it be possible to get that merged, and/or is there a different branch/tag/etc. in RLS I should update the submod to instead?

**Comment by Xanewok** [comment]
@calebcartwright https://github.com/rust-lang/rls/pull/1725 is now merged, could you try using latest RLS master?

**Comment by ehuss** [comment]
You'll need to update the patch list [here](https://github.com/rust-lang/rust/blob/c18c0ad2bc5988ca7953459e5a35ece8e69e35e7/Cargo.toml#L89-L90) to include `cargo-util = { path = "src/tools/cargo/crates/cargo-util" }`

**Comment by calebcartwright** [comment]
> You'll need to update the patch list [here](https://github.com/rust-lang/rust/blob/c18c0ad2bc5988ca7953459e5a35ece8e69e35e7/Cargo.toml#L89-L90) to include `cargo-util = { path = "src/tools/cargo/crates/cargo-util" }`

Yup had just found that a little while ago as well :+1:

**Pull request merged**
