### PR TITLE
Prefer `cmake3` to `cmake` when bootstrapping.

### LINKED ISSUE #71227: Error bootstrapping on CentOS
It looks like the bootstrapper does not use `cmake3` on CentOS (i.e., CMake 3.x) but instead `cmake` (i.e., version 2.x). This results in the error `CMake 3.4.3 or higher is required.  You are running version 2.8.12.2`. The fix would seem to be obvious: check for `cmake3` before falling back to `cmake`.

Relevant section of console output:

```
    Finished release [optimized + debuginfo] target(s) in 49.26s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building LLVM for x86_64-unknown-linux-gnu
running: "cmake" "/home/alexreg/src/rust-devel/trait-upcasting/src/llvm-project/llvm" "-DLLVM_ENABLE_ASSERTIONS=ON" "-DLLVM_TARGETS_TO_BUILD=AArch64;ARM;Hexagon;MSP430;Mips;NVPTX;PowerPC;RISCV;Sparc;SystemZ;WebAssembly;X86" "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=" "-DLLVM_INCLUDE_EXAMPLES=OFF" "-DLLVM_INCLUDE_TESTS=OFF" "-DLLVM_INCLUDE_DOCS=OFF" "-DLLVM_INCLUDE_BENCHMARKS=OFF" "-DLLVM_ENABLE_ZLIB=OFF" "-DWITH_POLLY=OFF" "-DLLVM_ENABLE_TERMINFO=OFF" "-DLLVM_ENABLE_LIBEDIT=OFF" "-DLLVM_ENABLE_BINDINGS=OFF" "-DLLVM_ENABLE_Z3_SOLVER=OFF" "-DLLVM_PARALLEL_COMPILE_JOBS=32" "-DLLVM_TARGET_ARCH=x86_64" "-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu" "-DLLVM_LINK_LLVM_DYLIB=ON" "-DLLVM_ENABLE_LIBXML2=OFF" "-DLLVM_VERSION_SUFFIX=-rust-dev" "-DPYTHON_EXECUTABLE=/usr/bin/python" "-DCMAKE_INSTALL_MESSAGE=LAZY" "-DCMAKE_C_COMPILER=cc" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_C_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_FLAGS=-ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_INSTALL_PREFIX=/home/alexreg/src/rust-devel/trait-upcasting/build/x86_64-unknown-linux-gnu/llvm" "-DCMAKE_BUILD_TYPE=Release"
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.4.3 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/alexreg/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
	finished in 0.027
failed to run: /home/alexreg/src/rust-devel/trait-upcasting/build/bootstrap/debug/bootstrap -i test src/test/ui/traits/trait-upcasting
Build completed unsuccessfully in 0:01:59
```

### PR DESCRIPTION
**Pull request by alexreg**
Fixes #71227.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by alexreg** [comment]
(Tested on CentOS on GCC Compile Farm, incidentally.)

**Comment by crlf0710** [comment]
@alexreg  Ping from triage, this needs a rebase.

**Comment by alexreg** [comment]
@crlf0710 Happy to rebase right after a review... don't want to rebase just for it to sit around a while longer waiting for a review. :-)

**Comment by Dylan-DPC** [comment]
@alexreg mark will review it this week, so better to rebase before that :)

**Comment by alexreg** [comment]
@Dylan-DPC In that case, no prob. Shouldn't bitrot much (if at all) in a few days!

**Comment by joelpalmer** [comment]
Ping from Triage: Any update @alexreg?

**Comment by Mark-Simulacrum** [comment]
Going to close this out as inactive.

**Pull request closed without merging**
