### PR TITLE
Implement stable-wakers RFC

### PR DESCRIPTION
**Pull request by p-avital**
Implements the [ABI-stabilize `core::task::Waker`](https://github.com/rust-lang/rfcs/pull/3404) RFC

### CODE REVIEW

**Comment by workingjubilee** [comment]
Ironically, this PR is getting negative feedback from tidy due to the lack of [stability attributes](https://rustc-dev-guide.rust-lang.org/stability.html).

**Comment by p-avital** [comment]
Is writing an arbitrary feature name sufficient?

**Comment by workingjubilee** [comment]
Yes, you can just pick names out of a hat.

**Comment by workingjubilee** [comment]
I believe the way the conversation in https://github.com/rust-lang/rfcs/pull/3404 went suggests this will not be pursued further, please feel free to reopen and rebase (in that order) if I am wrong.

**Pull request closed without merging**
