### PR TITLE
rustdoc: Add static size assertion for `clean::Type`

### PR DESCRIPTION
**Pull request by camelid**
r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
Looks like no change in compiletime and a moderate regression for memory on tokio-webpush-simple-doc. So I think this should be closed unless you have ideas for improving it.

**Comment by camelid** [comment]
Actually, there are a lot of small improvements:

image

**Comment by jyn514** [comment]
Those are *very* small, though ... I don't know if the improvement is worth it.

**Comment by camelid** [comment]
Well, up to you. I think we should at least keep the static size assertion for `Type`, so I can drop the boxing commit.

**Comment by jyn514** [comment]
> I think we should at least keep the static size assertion for Type, so I can drop the boxing commit

👍 Seems good, r=me with that done

**Pull request merged**
