### PR TITLE
Make doc stubs for builtin macros reflect existing support for trailing commas

### PR DESCRIPTION
**Pull request by ExpHP**
This modifies the `macro_rules!` stubs in `std` for some of the compiler builtin macros in order to better reflect their currently supported grammar.  To my understanding these stubs have no impact on compiler output whatsoever, and only exist so that they may appear in the documentation.

P.S. It is in fact true that `env!` supports trailing commas while `option_env!` currently does not.  (I have another issue for this)

I don't imagine there's any way to automatically test these stubs, but I did *informally* test the new definitions on the playpen to see that they accept the desired invocations, as well as inspect the updated doc output.

### CODE REVIEW

**Comment by durka** [comment]
These definitions have been wrong so many times... it would be great if there *were* a way to test them.

**Comment by durka** [comment]
You should probably also update the duplicate definitions in libcore (the existence of which is also unfortunate).

**Comment by shepmaster** [comment]
Ping from triage @steveklabnik — it's been over 3 days and we haven't heard from you :-)

**Review by steveklabnik — APPROVED** [review]
Thank you! this is great.

**Pull request merged**
