### PR TITLE
move Cargo.toml to live alongside x.py

### PR DESCRIPTION
**Pull request by nikomatsakis**
This makes it so that, when you `./x.py`, you get errors relative to the location of `x.py`. I would also be fine with moving `x.py` into `src`, if that is deemed preferable. (Is this a good idea?) One or the other seems to make sense to me, but I'm curious what others think. =)

r? @alexcrichton 
cc @pnkfelix 

(I suppose one could also run `../x.py` from the `src` directory, but then that creates `src/build` directory, which I don't particularly like.)

(Also, this is only minimally tested.)

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

I think there's another PR to do this already as well though? It may need rebasing maybe

**Comment by pnkfelix** [comment]
For the record, I believe the other PR that @alexcrichton is referring to is PR #47731

**Comment by pnkfelix** [comment]
(which means ... is this likely to not pass bors unless it incorporates the fixups that have been incrementally added to #47731 ? hmm...)

**Comment by pnkfelix** [comment]
(also it would be good if this were tagged with "Fix #47355", the same way that #47731 is.)

**Comment by Mark-Simulacrum** [comment]
Yes, I'm going to just close this in favor of https://github.com/rust-lang/rust/pull/47731.

**Pull request closed without merging**
