### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
- Successful merges: #47379, #47833, #48106, #48198, #48314, #48325, #48335, #48352, #48354, #48360, #48382, #48397
- Failed merges:

### CODE REVIEW

**Comment by Aaron1011** [comment]
This appears to be a spurious timeout from appveyor. The build appears to have been running normally at the end, but it someone ended up taking more than three hours overall.

**Comment by Aaron1011** [comment]
Here's a job from the same build that passed: https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6426/job/9220y2k2k0scys4f

It appears to come in just under the time limit (2 hours 57 minutes).

**Comment by GuillaumeGomez** [comment]
Then let's retry.

@bors: retry

**Pull request merged**
