### PR TITLE
Use `mem::offset_of!` for `sockaddr_un.sun_path`

### PR DESCRIPTION
**Pull request by cuviper**
We don't need manual pointer math here anymore!

try-job: dist-i686-msvc

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r- 
https://github.com/rust-lang/rust/pull/130871#issuecomment-2376234232

**Comment by cuviper** [comment]
The only change since the previous approval is adding `sun_path` in the fake struct for cross-compiled docs.

@bors r=ibraheemdev

**Pull request merged**
