### PR TITLE
Detect object safety errors when assoc type is missing

### LINKED ISSUE #103155: Suboptimal diagnostics when trying to create a trait object for a trait with GATs
Given the following code ([playground 1](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=283ceedf88927d7f7847fdccdb64d107)):

```rust
trait Foo {
    type Bar<T>;
}

fn bar(x: &dyn Foo) {}
```

The current output is:
```
error[E0191]: the value of the associated type `Bar` (from trait `Foo`) must be specified
 --> src/lib.rs:5:16
  |
2 |     type Bar<T>;
  |     ----------- `Bar` defined here
...
5 | fn bar(x: &dyn Foo) {}
  |                ^^^ help: specify the associated type: `Foo<Bar = Type>`
```

Following this suggestion ([playground 2](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=382ec29650ce0920540563ad24bfdfe8))...
```rust
trait Foo {
    type Bar<T>;
}

fn bar(x: &dyn Foo<Bar = i32>) {}
```

... produces another diagnostic:
```
error[E0107]: missing generics for associated type `Foo::Bar`
 --> src/lib.rs:5:20
  |
5 | fn bar(x: &dyn Foo<Bar = i32>) {}
  |                    ^^^ expected 1 generic argument
  |
note: associated type defined here, with 1 generic parameter: `T`
 --> src/lib.rs:2:10
  |
2 |     type Bar<T>;
  |          ^^^ -
help: add missing generic argument
  |
5 | fn bar(x: &dyn Foo<Bar<T> = i32>) {}
  |                    ~~~~~~
```

Finally, specifying the generic argument for `Bar` ([playground 3](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5f4643be86020d18e4cc9ca761b03821))...
```rust
trait Foo {
    type Bar<T>;
}

fn bar(x: &dyn Foo<Bar<i32> = i32>) {}
```

... reveals that our struggle was all for naught:
```
error[E0038]: the trait `Foo` cannot be made into an object
 --> src/lib.rs:5:12
  |
5 | fn bar(x: &dyn Foo<Bar<i32> = i32>) {}
  |            ^^^^^^^^^^^^^^^^^^^^^^^ `Foo` cannot be made into an object
  |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
 --> src/lib.rs:2:10
  |
1 | trait Foo {
  |       --- this trait cannot be made into an object...
2 |     type Bar<T>;
  |          ^^^ ...because it contains the generic associated type `Bar`
  = help: consider moving `Bar` to another trait
```

Ideally, the first snippet should produce an object safety error right away:
```
error[E0038]: the trait `Foo` cannot be made into an object
 --> src/lib.rs:5:12
  |
5 | fn bar(x: &dyn Foo) {}
  |            ^^^^^^^ `Foo` cannot be made into an object
  |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
 --> src/lib.rs:2:10
  |
1 | trait Foo {
  |       --- this trait cannot be made into an object...
2 |     type Bar<T>;
  |          ^^^ ...because it contains the generic associated type `Bar`
  = help: consider moving `Bar` to another trait
```

In case `#![feature(generic_associated_types_extended)]` is enabled, E0191 should still be emitted, but the suggestion should include the generic argument for `Bar`:
```
error[E0191]: the value of the associated type `Bar` (from trait `Foo`) must be specified
 --> src/lib.rs:5:16
  |
2 |     type Bar<T>;
  |     ----------- `Bar` defined here
...
5 | fn bar(x: &dyn Foo) {}
  |                ^^^ help: specify the associated type: `Foo<Bar<T> = Type>`
```

@rustbot modify labels +D-terse +F-generic_associated_types

### PR DESCRIPTION
**Pull request by estebank**
When an associated type with GATs isn't specified in a `dyn Trait`, emit an object safety error instead of only complaining about the missing associated type, as it will lead the user down a path of three different errors before letting them know that what they were trying to do is impossible to begin with.

Fix #103155.

### CODE REVIEW

**Review by davidtwco — COMMENTED** [review]
Apologies for how long it has taken me to get to this. Is there a test for the object safety error being emitted from this PR? I couldn't see one but might have missed it.

**Comment by estebank** [comment]
@davidtwco ha, I thought I'd added a test for it. Added now.

**Pull request merged**
