### PR TITLE
Stabilize feature(match_beginning_vert)

### LINKED ISSUE #44101: Tracking issue for RFC 1925: Allow an optional vert at the beginning of a match branch
This is a tracking issue for the RFC "Allow an optional vert at the beginning of a match branch " (rust-lang/rfcs#1925).

**Steps:**

- [x] Implement the RFC -- done in #44108 
    - [Test case showing correct behavior](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/feature-gate-match_beginning_vert.rs)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

### PR DESCRIPTION
**Pull request by goodmanjonathan**
With this feature stabilized, match expressions can optionally have a `|` at the beginning of each arm.

Reference PR: rust-lang-nursery/reference#231

Closes #44101

### CODE REVIEW

**Comment by stepancheg** [comment]
RFC had 37 downvotes compared to 19 upvotes. Not obviously a good thing to be added to the language.

**Comment by warlord500** [comment]
I am very much against this being added to the language. it will lead to more confusing code! 
looking at some of the code in Releases.md, i got mixed just looking at it

**Comment by pravic** [comment]
Same here. But nobody cares despite 

> The teams are required to take arguments against an RFC very seriously

**Comment by warlord500** [comment]
this will be the one feature I will hugely disagree with in rust! unless their is extremely (strong willed) segment of developers that do like this. every example, I have been able to look at Involving, I find more confusing than with out the leading vertical bar!  Not only that, but I have to yet to find strong evidence of many people wanting this feature! yes, there could be an example, but to the best of my knowledge, (which to be honest Isnt a lot) most code with this syntax added leads to more confusing code!

**Comment by TomasHubelbauer** [comment]
For the record, while I don't have any idea how many people support this syntax, I do. I _think_ F# uses vertical bars for `match`, too, and I personally am used to aligning union types this way in TypeScript, so it's welcome to have something familiar like this. Sure, the `|` symbol is also used for closures, but I believe the contexts are distinct enough for this not to matter.

**Comment by tdbgamer** [comment]
Yeah all the arguments behind this RFC make no sense to me. There were alternatives that worked already and looked just as good. "I got used to it in F# and now I want it in Rust" is a bit of a strange argument to me. Rust shouldn't be some Frankenstein's monster of parts of different languages. Ideas should be evaluated based on their merit, and the value this brings to the table is very questionable to me.

As for all the people arguing for flexible syntax and allowing different styles... This is how languages like Perl happened. "There is more than one way to do it" isn't a good thing; it's confusing and fragments the language. To quote Tim Peters "There should be one-- and preferably only one --obvious way to do it."

Maybe this particular change is alright, but I just think a lot of the arguments made in this RFC are very dangerous and might lead Rust down the path many other failed languages have taken. Let's learn from their mistakes rather than repeat them because I really want Rust to succeed.

There should be very strong arguments before we bloat the language spec more with little changes that have very minimal benefit to users and just add more mental overhead for beginners.

**Comment by Gedweb** [comment]
Rust going to hell. We won't add C like increment, but this feature is OK. WAT?

**Comment by H2CO3** [comment]
This is deeply worrying. Many users have expressed their concerns with this feature — they have been ignored and this feature, which adds more syntactic clutter, has been stabilized. Where did democracy go?

**Comment by liigo** [comment]
FWIW:  [RFC1925](https://github.com/rust-lang/rfcs/pull/1925) is awarded the Most-Disliked RFC!

https://www.reddit.com/r/rust/comments/8ck0yv/rfc1925_is_awarded_the_mostdisliked_rfc/

**Comment by valeth** [comment]
Not really against having something similar to Haskell's guard statements.
But they need to at least have some practical use instead of just adding an optional syntax element that could easily be omitted.

**Comment by withoutboats** [comment]
@valeth no one ever seems to have answered your question, but your comment seems a bit confused about the scope of this stabilization. Rust has had the ability to match multiple patterns with a single arm since before 1.0. there's no way to do what you suggest in your post, because `x` would be uninitialized in the `None` case.

This change was strictly syntactical: it makes `|pat|pat` equivalent to `pat|pat` in the same way that `a,b,` is equivalent to `a,b`.

**Comment by Arcaelyx** [comment]
This seems like such a useless pattern to add if it provides no extra functionality. In the end, things like this lead to people wanting their own style thrown in to vastly complicate the language without providing any extra practical benefit. Such as:

```
If we are to throw this in, then why don't we have ternary operators as well? At least that actually leads to more concise code as opposed to now having useless bloat with no additional benefit.
```

Whereas the difference with this is that it at least provides _some_ benefit.

**Comment by Arcaelyx** [comment]
This seems like such a useless pattern to add if it provides no extra functionality. In the end, things like this lead to people wanting their own style thrown in to vastly complicate the language without providing any extra practical benefit. Such as:

```
If we are to throw this in, then why don't we have ternary operators as well?
At least that actually leads to more concise code as opposed to now having
useless bloat with no additional benefit.
```

Whereas the difference with this is that it at least provides _some_ benefit, but we start spiraling out of control with adding in features like this.

**Pull request merged**
