### PR TITLE
doc: Fix print value

### PR DESCRIPTION
**Pull request by rydotyosh**
`input` -> `guess`

### CODE REVIEW

**Comment by killercup** [comment]
Too late? #25148

**Comment by rydotyosh** [comment]
Oh, tanks. It is same.
And then, the return value `input` is never used.

**Comment by killercup** [comment]
Indeed, that unused value is not cool.

@steveklabnik, maybe you want to r+ this instead of #25148?

**Comment by steveklabnik** [comment]
Oh, nice catch!

So that everyone gets credit, @rydotyosh, what do you think about editing this PR to just include the return fix?

**Comment by rydotyosh** [comment]
OK.

**Pull request closed without merging**
