### PR TITLE
make HR_LIFETIME_IN_ASSOC_TYPE deny-by-default

### PR DESCRIPTION
**Pull request by nikomatsakis**
It's time to fix issue #32330.

cc #33685 
cc @arielb1

### CODE REVIEW

**Comment by nikomatsakis** [comment]
This needs a crater run.

**Comment by eddyb** [comment]
Please switch to `Forbid` for the crater run. r=me otherwise.

**Comment by KalitaAlexey** [comment]
Dear @nikomatsakis, are you going to write tests for that case?

**Comment by nikomatsakis** [comment]
Crater report [available here](https://gist.github.com/nikomatsakis/972f1febc7c78ed794b6f9dabcf21d9b).

* [ ] [glib-0.1.0](https://crates.io/crates/glib) ([before](https://tools.taskcluster.net/task-inspector/#nMhrjBxRRlG6feh4jWMmrQ)) ([after](https://tools.taskcluster.net/task-inspector/#4HaUgcNnSKytGS9lU6pkxQ))
* [ ] [more-asserts-0.1.0](https://crates.io/crates/more-asserts) ([before](https://tools.taskcluster.net/task-inspector/#WEtlIPAQTNSR3aUbJP0I-Q)) ([after](https://tools.taskcluster.net/task-inspector/#h7s4w7s1Ri-jTMwqOKOB0Q))
* [ ] [systemstat-0.1.0](https://crates.io/crates/systemstat) ([before](https://tools.taskcluster.net/task-inspector/#KoqqRuOGT8aLyYNoIReUuQ)) ([after](https://tools.taskcluster.net/task-inspector/#auqm19lnSUqsheu7nBDYMQ))
* [ ] [human_name-0.6.2](https://crates.io/crates/human_name) ([before](https://tools.taskcluster.net/task-inspector/#l26tzZifSGWOPpAeKs3CkQ)) ([after](https://tools.taskcluster.net/task-inspector/#vU2pvoN2QDqxtSqvUTDIPQ))
* [ ] [karaorust-0.0.1](https://crates.io/crates/karaorust) ([before](https://tools.taskcluster.net/task-inspector/#ehU-S-iZRjiqirLf7zwF1g)) ([after](https://tools.taskcluster.net/task-inspector/#DEaZepxOSPuM4M7DKvEc2A))
* [ ] [external_set-0.1.1](https://crates.io/crates/external_set) ([before](https://tools.taskcluster.net/task-inspector/#9eWg4v4qRa-_WCy44-GggA)) ([after](https://tools.taskcluster.net/task-inspector/#6VQxgn7ARbKW0hyvqGiZLg))

**Comment by nikomatsakis** [comment]
@KalitaAlexey there are many tests for the ling that already exist, they are just already set to deny

**Comment by nikomatsakis** [comment]
@djudd -- note that [according to this crater run](https://tools.taskcluster.net/task-inspector/#vU2pvoN2QDqxtSqvUTDIPQ/0), your package `human-name` contains a future incompatibility warning (#33685). This warning will soon change to a hard error. I tried checking it out and building it locally but I got errors (at least with the latest nightly) related to the package `phf_macros` (I'm actually not sure how the crater run managed to succeed -- doing a bit more investigation).

In any case, here are the errors we see. I *suspect* the fix is to change the signature of `transliterate` to the following:

```rust
pub fn transliterate(c: char) -> Chars<'static>
```

but I am not entirely sure until I am able to experiment. (Note that the need to do this is itself a compiler bug, as described in #32330, but fixing that bug is (somewhat ironically) blocked on converting this lint into a hard error.)


```
error: lifetime parameter `'a` declared on fn `utils::transliterate` appears only in the return type, but here is required to be higher-ranked, which means that `'a` must appear in both argument and return types, #[forbid(hr_lifetime_in_assoc_type)] on by default
   --> src/comparison.rs:413:33
    |
413 |                                .filter_map(lowercase_if_alpha);
    |                                 ^^^^^^^^^^
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #33685 <https://github.com/rust-lang/rust/issues/33685>

error: lifetime parameter `'a` declared on fn `utils::transliterate` appears only in the return type, but here is required to be higher-ranked, which means that `'a` must appear in both argument and return types, #[forbid(hr_lifetime_in_assoc_type)] on by default
   --> src/comparison.rs:417:37
    |
417 |                                    .filter_map(lowercase_if_alpha);
    |                                     ^^^^^^^^^^
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #33685 <https://github.com/rust-lang/rust/issues/33685>

error: lifetime parameter `'a` declared on fn `utils::transliterate` appears only in the return type, but here is required to be higher-ranked, which means that `'a` must appear in both argument and return types, #[forbid(hr_lifetime_in_assoc_type)] on by default
   --> src/lib.rs:405:34
    |
405 |                                 .rev();
    |                                  ^^^
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #33685 <https://github.com/rust-lang/rust/issues/33685>
```

I'll update with more info when I figure out what's happening with the `phf_macros` crate.

**Comment by djudd** [comment]
@nikomatsakis that fix appears to work - thanks! (I didn't see phf_macros-related errors locally.)

**Pull request merged**
