### PR TITLE
rand: Use wrapping operations everywhere

### PR DESCRIPTION
**Pull request by alexcrichton**
There was a buildbot failure recently of an arithmetic overflow in the isaac
module of the rand crate, so I've imported the isaac implementation from
out-of-tree which makes somewhat more liberal usage of the wrapping primitives.
Hopefull this quelches any future overflow!

### CODE REVIEW

**Comment by alexcrichton** [comment]
Relevant logs: http://buildbot.rust-lang.org/builders/auto-linux-32-opt/builds/3964/steps/test/logs/stdio

**Comment by Manishearth** [comment]
A user hit this in IRC

http://pastebin.com/0s3WeYpt

**Comment by Manishearth** [comment]
cc @pnkfelix

**Pull request merged**
