### PR TITLE
Add more documentation to `Diagnostic` and `DiagnosticBuilder`

### PR DESCRIPTION
**Pull request by camelid**
cc @estebank

### CODE REVIEW

**Review by lcnr — APPROVED** [review]

**Comment by lcnr** [comment]
:+1: 

do we check that all intradoc links were successfully resolved?

@bors r+ rollup

**Comment by lcnr** [comment]
looks like CI is still failing

@bors r-

**Comment by camelid** [comment]
> do we check that all intradoc links were successfully resolved?

We have a linkchecker script that should be run by CI.

**Comment by camelid** [comment]
Actually, I'm not sure if it works for compiler docs though.

**Comment by camelid** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/docs.20based.20on.20macro.20input

**Comment by camelid** [comment]
@lcnr should be good to go now

**Pull request merged**
