### PR TITLE
Account for async functions when suggesting new named lifetime

### LINKED ISSUE #75850: "use of undeclared lifetime" error on async method has invalid suggestion (lifetime in parameter position)
Minimal reproducer:

```rust
struct Bug {}
impl Bug {
    async fn buggy(&self) -> &'somelifetime str {
        todo!()
    }
}
```

In both stable (`rustc 1.45.2 (d3fb005a3 2020-07-31)`) and nightly (`rustc 1.47.0-nightly (663d2f5cd 2020-08-22)`) I get this error:

```
error[E0261]: use of undeclared lifetime name `'somelifetime`
 --> src/lib.rs:3:31
  |
3 |     async fn buggy(&self) -> &'somelifetime str {
  |                               ^^^^^^^^^^^^^ undeclared lifetime
  |
help: consider introducing lifetime `'somelifetime` here
  |
2 | impl<'somelifetime> Bug {
  |     ^^^^^^^^^^^^^^^
help: consider introducing lifetime `'somelifetime` here
  |
3 |     async fn buggy('somelifetime, &self) -> &'somelifetime str {
  |                    ^^^^^^^^^^^^^^
```

If I make the method a top-level function, or if I drop the `&self` parameter to make it an associated function, the issue goes away and rustc correctly suggests `buggy<'somelifetime>()`.

### PR DESCRIPTION
**Pull request by estebank**
Fix #75850.

### CODE REVIEW

**Comment by estebank** [comment]
Nominating for beta backport simply because it is already in stable, but there's no harm on letting this ride the train.

**Review by pickfire — APPROVED** [review]
Looks good to me.

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/49871weeklymeeting2020082754818.html#208221489) in T-compiler meeting.

@rustbot modify labels: beta-accepted

**Pull request merged**
