### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #71903 (reword "possible candidate" import suggestion)
 - #71952 (Add some regression tests)
 - #71959 (tests: Fix warnings in `rust_test_helpers.c`)
 - #71962 (Grammar)
 - #71972 (use hex for pointers in Miri error messages)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
The [log says](https://github.com/rust-lang-ci/rust/runs/653076898)
```
stderr:
------------------------------------------
D:\a\rust\rust\src/test\codegen\ffi-out-of-bounds-loads.rs:18:12: error: CHECK: expected string not found in input
 // CHECK: load { i64, i32 }, { i64, i32 }* {{.*}}, align 4
           ^
D:\a\rust\rust\build\x86_64-pc-windows-msvc\test\codegen\ffi-out-of-bounds-loads\ffi-out-of-bounds-loads.ll:1:1: note: scanning from here
; ModuleID = 'ffi_out_of_bounds_loads.7rcbfp3g-cgu.0'
^
D:\a\rust\rust\build\x86_64-pc-windows-msvc\test\codegen\ffi-out-of-bounds-loads\ffi-out-of-bounds-loads.ll:52:8: note: possible intended match here
 %_2 = load i32, i32* %self, align 4
       ^

------------------------------------------



failures:
    [codegen] codegen\ffi-out-of-bounds-loads.rs
```
That codegen test was added in https://github.com/rust-lang/rust/pull/71952.
This doesn't quite look spurious?

**Comment by RalfJung** [comment]
However @pietroalbini something is wrong with whatever bors linked to above, but here and in https://github.com/rust-lang/rust/pull/71966: it linked to https://github.com/rust-lang-ci/rust/runs/653177525 which just says "mark the job as a failure", 
```
Run exit 1
##[error]Process completed with exit code 1.
```
One has to ignore that and find the actual failing job in the list on the left to figure out what happened.

**Comment by Dylan-DPC** [comment]
Yeh i got a different thing (maybe a different build) hence assumed spurious. I'll r- that one and re-roll

**Comment by pietroalbini** [comment]
@RalfJung opened https://github.com/rust-lang/rust/issues/71987 to track your feedback.

**Pull request closed without merging**
