### PR TITLE
Add translation support by mdbook-i18n-helpers to bootstrap

### LINKED ISSUE #124641: Japanese translation of Rust by Example is not built
### Location

The language selector of Rust by Example has the link to Japanese translation, but the link target (https://doc.rust-lang.org/rust-by-example/ja/index.html) is not found.

image

### Summary

The latest Rust by Example has Japanese translation resource based on [mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers).
But the current bootstrap process by `./x doc` doesn't build the translation.

If I open a PR to add the translation build process, is it acceptable?

### PR DESCRIPTION
**Pull request by dalance**
This PR add translation support by [mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers) to bootstrap.
This is draft PR because there is the dependency to my forked mdbook-i18n-helpers.
If this PR is acceptable, I'll send a PR to the original mdbook-i18n-helpers and remove draft after changing the dependency to the original.

Closes #124641

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r? @ehuss since you I think(?) maintain mdbook so might be more familiar with problems we might hit. This seems broadly OK to me though.

cc @davidtwco / @Manishearth (?) as well for i18n efforts more broadly, mostly just as FYI (not sure if there's anything in particular here to take a look at)

**Comment by ehuss** [comment]
Seems fine overall. It looks like it adds about 15MB to the overall doc size, which should be fine for now (the docs are currently about 724MB), but we may need to think about this more carefully if there is a significant proliferation of translations in the future.

It looks like there are also some broken links here, though.

**Comment by dalance** [comment]
The broken links was fixed at the upstream repo. It will be reflected at the next submodule update.

**Comment by dalance** [comment]
@ehuss I changed the dependency to the original mdbook-i18n-helpers and this PR became ready for review.

**Comment by ehuss** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
