### PR TITLE
Update doc of fs.rs -- document difference between `.append(true)` and `.read(true).write(true)`

### PR DESCRIPTION
**Pull request by Neutron3529**
(Edit: the doc seems totally wrong. I've opened a [discussion thread about that in IRLO](https://internals.rust-lang.org/t/discussion-mis-documentation-of-append-method-in-openoption/21737))

Due to a bug, set `.append(true)` is not equivlent to set `.read(true).write(true)`

### CODE REVIEW

**Comment by the8472** [comment]
> set .append(true) is not equivlent to set .read(true).write(true)

I'm not sure what you're trying to say there. Even without the bug they wouldn't be the same because `append(true)` (`O_APPEND`) means that `write(2)` calls always append, regardless of `lseek(2)`.

Plus I think we should be using pwritev2 with `RWF_NOAPPEND` on linux (if available) to implement `write_at` to get the correct behavior.

**Comment by Neutron3529** [comment]
> I'm not sure what you're trying to say there.

Currently in the [doc](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.append), it is said that

> This option, when true, means that writes will append to a file instead of overwriting previous contents. Note that setting .write(true).append(true) has the same effect as setting only .append(true).

**Comment by slanterns** [comment]
The description says "set `.append(true)` is not equivlent to set `.read(true).write(true)`," and the code says "expect a bug setting `.write(true).append(true)` has the same effect as setting only `.append(true)`". Are them really the same thing?

**Comment by ChrisDenton** [comment]
Documenting Linux specific bugs should go in a separate "Platform-specific behavior" section. Though I'm not personally convinced we need to document it. I think we need to replace or remove that whole sentence and not claim they are the same.

**Pull request closed without merging**
