### PR TITLE
Failure is not an option

### PR DESCRIPTION
**Pull request by Centril**
Remove the `src/test/compile-fail` folder and move all of its tests into appropriate places in `src/test/ui`. Some tests in `src/test/ui` are also moved as a result for better categorization.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
Are you sure you know what you just got into?
All the tests in `compile-fail` are not migrated to `ui` because they either produce unstable diagnostics changing from run to run, or heavily platform-dependent diagnostics.
Both kinds of tests require either compiler changes (`HashMap` -> `BTreeMap` or something) or som compiletest extensions to migrate.
If you want to implement all that pre-requisite stuff, that would be really great.

(It's possible that *some* tests are there by accident though.)

**Comment by Centril** [comment]
> Are you sure you know what you just got into?
>  All the tests in `compile-fail` are not migrated to `ui` because they either produce unstable diagnostics changing from run to run, or heavily platform-dependent diagnostics.

Well... now I do... 😂  I just thought they were in `compile-fail` because no one had bothered to move them.

> (It's possible that _some_ tests are there by accident though.)

Hmm... so maybe let's move them more incrementally and see which parts stick?
It's hard to tell what exactly is unstable or heavily platform-dependent otherwise.

**Comment by petrochenkov** [comment]
>It's hard to tell what exactly is unstable or heavily platform-dependent otherwise.

Yeah, it would be nice to try and see what CI says.
Things could change from the last time the migration was attempted, diagnostics could be fixed and become stable, etc.

**Comment by petrochenkov** [comment]
cc @davidtwco 
Did you try to do anything with those tests (splitting, normalization), or left everything that didn't pass on CI?
I remember the `compile-fail` -> `ui` migration PR was huge and it wasn't the best time to care about details.

**Comment by davidtwco** [comment]
I never did revisit these tests and attempt anything to get them working on the `ui` suite. The only remaining tests in `compile-fail` were ones that were problematic for some reason or another when moved to `ui`. I opened #53353 at the time, which has a little more information, but unfortunately not much.

**Comment by mark-i-m** [comment]
> Failure is not an option

I think usually it is a `Result`, no?

>  I opened #53353 at the time, which has a little more information, but unfortunately not much.

Did the errors have anything in common? e.g. were they all from a particular part of the compiler? Is there something we can focus on to get the most bang for the buck?

**Comment by Centril** [comment]
> Is there something we can focus on to get the most bang for the buck?

I'll save this branch into another for now and remove some bits from the PR and see if we can merge that. Once we have determined the set of tests that cannot be moved we can consider fixes for those.

**Comment by davidtwco** [comment]
> Did the errors have anything in common? e.g. were they all from a particular part of the compiler? Is there something we can focus on to get the most bang for the buck?

Unfortunately, I can’t remember. I’m afraid I didn’t keep notes as to what the failures at the time, but you could probably look at old Travis logs from the original PR, if they are still around.

**Comment by Centril** [comment]
Extracted a subset of this PR into https://github.com/rust-lang/rust/pull/62177.

Marking as blocking progress on that.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/62177 was closed, so closing this as well.

**Pull request closed without merging**
