### PR TITLE
Only test duplicate inherent impl items in a single place

### PR DESCRIPTION
**Pull request by cjgillot**
Based on https://github.com/rust-lang/rust/pull/100387

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
Blocked on https://github.com/rust-lang/rust/pull/100387.

**Comment by petrochenkov** [comment]
r=me after rebase.
@rustbot author

**Comment by Undin** [comment]
It seems that these changes add a bug. Now the compiler produces `E0592` for inherent `impl`s instead of `E0201` even if items with duplicate names are inside single `impl` block. Although [description](https://doc.rust-lang.org/error_codes/E0592.html) of `E0592` says that it should be reported only when items are defined in different blocks

**Pull request merged**
