### PR TITLE
rustdoc-search: allow spaces around `::` in path query

### PR DESCRIPTION
**Pull request by notriddle**
This restriction made sense back when spaces separated function parameters, but now that they separate path components, there's no real ambiguity any more.

Additionally, the Rust language allows it.

The other two commits are misc code cleanup.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I don't agree with this change. I think not allowing whitespace characters in paths makes more sense:
 * closer to rust code
 * less weird to read

**Comment by jsha** [comment]
I agree with @notriddle on this.

**Comment by GuillaumeGomez** [comment]
> > closer to rust code
> 
> [Rust allows you to put spaces around the `::` in paths](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dd527ad17e89343e7055ea093654ecfb). It's not even a warning, just different from what Rustfmt does by default.

I didn't know that. Then I'm all in favour for this change. :+1:

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I'm not sure if an FCP is needed here. I'll let you decide on this. r=me otherwise.

**Pull request merged**
