### PR TITLE
improve `_` constants in item signature handling

### PR DESCRIPTION
**Pull request by lcnr**
removing the "type" from the error messages does slightly worsen the error messages for types, but figuring out whether the placeholder is for a type or a constant and correctly dealing with that seemed fairly difficult to me so I took the easy way out :sparkles: Imo the error message is still clear enough.

r? @BoxyUwU cc @estebank

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r-
failed in a rollup: https://github.com/rust-lang/rust/pull/92907#issuecomment-1013571178

**Comment by lcnr** [comment]
intra-doc links should be correct now:

@bors r=BoxyUwU

**Comment by lcnr** [comment]
seems like bors is broken right now? cc @rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
If https://bors.rust-lang.org/queue/rust loads, you can typically close/reopen a PR to get bors to pick up new comments. It looks like this PR has a merge conflict though, anyway.

**Pull request merged**
