### PR TITLE
Make `NonZero::get` generic.

### PR DESCRIPTION
**Pull request by reitermarkus**
Tracking issue: https://github.com/rust-lang/rust/issues/120257

Depends on https://github.com/rust-lang/rust/pull/120521.

r? @dtolnay

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
I reviewed the 3rd commit only (the first 2 are identical to #120521 based on commit hash).

Looks good!

#119452 added codegen tests (@AngelicosPhosphoros thank you :clap: :clap:) so as long as those are good, I am happy with this PR.

**Comment by dtolnay** [comment]
@bors delegate+

Please rebase after #120521 lands, so we see just `get` changes in https://github.com/rust-lang/rust/pull/120563/files, and then approve this yourself. Thanks!

After #120521 is merged and then #120486 is rebased and merged, regardless of whether this PR has been merged by that point, I plan to propose stabilization on #120257. Between the time for the team to approve the stabilization, and land a stabilization PR, and then the nightly and beta period, it will give enough time in my opinion to bail out if anything appears to be going wrong with generic nonzero.

**Comment by reitermarkus** [comment]
> https://github.com/rust-lang/rust/pull/119452 added codegen tests

Yes, I specifically ran these tests locally, so hopefully should be fine.

**Comment by dtolnay** [comment]
Can't tell what failed.

@bors retry
@bors delegate+

**Pull request merged**
