### PR TITLE
Some more cleanups to syntax::print

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
All of these changes should be functionally equivalent to previous code.

Each commit mostly stands alone and this PR is easiest to review by-commit.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
(Feel free to reassign to someone else, I think anyone can do the review for this since it's just cleanup)

**Comment by petrochenkov** [comment]
This has some conflicts with https://github.com/rust-lang/rust/pull/62393 (with that PR token and ident printing have some extra arguments and don't fit into `Display` directly).

**Comment by Mark-Simulacrum** [comment]
I can drop those commits -- maybe easiest to just wait after your PR lands?

**Comment by petrochenkov** [comment]
I'll reassign https://github.com/rust-lang/rust/pull/62393 to you then, otherwise it's unlikely to land soon.

**Comment by Mark-Simulacrum** [comment]
I've dropped what I think are the conflicting commits from this PR.

**Pull request merged**
