### PR TITLE
Do not add external libraries to libstd stamp file

### PR DESCRIPTION
**Pull request by mati865**
Currently they are present in `.libstd.stamp` and point to target sysroot:
```
tD:\Projekty\rust\build\x86_64-pc-windows-gnu\stage1\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o
```
while normal objects point to non sysroot locations:
```
tD:\Projekty\rust\build\x86_64-pc-windows-gnu\stage1-std\x86_64-pc-windows-gnu\release\deps\liballoc-eb2e01dae1fd9cc7.rlib
```

Now `add_to_sysroot(...)` function reads stamp file and copies everything listed to the target or host sysroot. So in case of those objects we are effectively copying the inplace (from `target_sysroot/lib/X` to `target_sysroot/lib/X`).

This PR also prepares ground for moving those objects to different location: https://github.com/rust-lang/rust/issues/68887#issuecomment-633048380

### CODE REVIEW

**Comment by mati865** [comment]
cc @petrochenkov 

Enabled try builders:
- Linux for sanitizers
- Musl for cross compiled target
- Windows-gnu for natively compiled target

**Comment by mati865** [comment]
Wrong git stash...
Should be fine now.

**Comment by tmiasko** [comment]
As far as I understand, the content of stamp file also controls what will be
eventually distributed, so those changes effectively stop distributing those
libraries (take a look at how `copy_target_libs` in dist.rs is using stamp file).

**Comment by mati865** [comment]
Unfortunately it's something I couldn't test on Windows because `./x.py dist` doesn't work with MinGW Python installed from MSYS2. I'll see if `./x.py install` works.

**Comment by mati865** [comment]
Made dist build on Linux and indeed objects are not copied if they are not present in stamp.
I'll have to find different workaround.

**Pull request closed without merging**
