### PR TITLE
pprust: Do not print spaces before some tokens

### LINKED ISSUE #63896: [1.38] Regression: proc-macro derive panicked
https://github.com/rust-lang/rust/issues/63628#issuecomment-524643597

>proc-macro derive panicked

```
[INFO] [stderr] error: proc-macro derive panicked
[INFO] [stderr]   --> src/lib.rs:11:1
[INFO] [stderr]    |
[INFO] [stderr] 11 | / proc_macro_item_decl! {
[INFO] [stderr] 12 | |     /// Generates a default blanket impl for a generic trait that gets passed into
[INFO] [stderr] 13 | |     /// `autoimpl!`, with the same type parameters and type bounds as its trait.
[INFO] [stderr] 14 | |     ///
[INFO] [stderr] ...  |
[INFO] [stderr] 44 | |     autoimpl! => generate_auto_impl_impl
[INFO] [stderr] 45 | | }
[INFO] [stderr]    | |_^
[INFO] [stderr]    |
[INFO] [stderr]    = help: message: assertion failed: `(left == right)`
[INFO] [stderr]              left: `Some("#[allow(unused,")`,
[INFO] [stderr]             right: `Some("#[allow(unused")`
```

All of the 62 regressions are due to old versions of `proc-macro-hack` having an assert expecting `#[allow(unused,` instead of `#[allow(unused ,`.
So this is again a consequence of whitespace changes in pretty-printing (https://github.com/rust-lang/rust/pull/62667).

I think we should be able to fix this by special casing the comma token during token stream pretty-printing and not printing the space before it.

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/63896

r? @Mark-Simulacrum

### CODE REVIEW

**Review by estebank — APPROVED** [review]

**Comment by estebank** [comment]
r=me if you don't want to wait for @Mark-Simulacrum to see this.

**Comment by petrochenkov** [comment]
@bors r=estebank
(Tested locally.)

**Comment by Centril** [comment]
Nominating for the language team as a proxy for the more general issue of pretty printing stability.

**Pull request merged**
