### PR TITLE
inline format!() args up to and including rustc_middle (2)

### PR DESCRIPTION
**Pull request by matthiaskrgr**
r? @WaffleLapkin

### CODE REVIEW

**Review by WaffleLapkin — CHANGES_REQUESTED** [review]

**Comment by WaffleLapkin** [comment]
Also, just a note: @matthiaskrgr please, don't include tags (`@username`) in commits (I get a notification every time you force push).

**Comment by matthiaskrgr** [comment]
Oh  crap, sorry, I guess I can force-push them out and that would resolve the issue?

**Comment by WaffleLapkin** [comment]
It should resolve the issue, yes.

**Review by WaffleLapkin — APPROVED** [review]
r=me with commit message typo fixed 
> formt!()

**Comment by matthiaskrgr** [comment]
:sweat_smile: 
@bors r=WaffleLapkin

**Comment by NobodyXu** [comment]
I'm not familiar with rustc, but I wonder if inlining `format!` args would allow it to replace the formatting with a constant string when all arguments are known at compile-time, like `format_args!` inline optimization.

**Comment by workingjubilee** [comment]
1. hypothetically
2. be careful not to confuse inlining, the optimization, with [implicit named argument capture in `format_args!`](https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html), which is sometimes referred to as "inline `format_args!`"

**Comment by WaffleLapkin** [comment]
@NobodyXu `format!("blah {}", x)` → `format!("blah {x}")` is purely syntactic transformation, the semantics don't change. It neither helps nor makes it harder to do optimizations.

Moreover `format!` also uses `format_args!` under the hood, so optimizations which inline constants also benefit it.

**Comment by NobodyXu** [comment]
Thank you for the explanation!

**Pull request merged**
