### PR TITLE
Stabilize some Option methods as const

### PR DESCRIPTION
**Pull request by CDirkx**
Stabilize the following methods of `Option` as const:
 - `is_some`
 - `is_none`
 - `as_ref`

These methods are currently const under the unstable feature `const_option` (tracking issue: #67441).
I believe these methods to be eligible for stabilization because of the stabilization of #49146 (Allow if and match in constants) and the trivial implementations, see also:  [PR#75463](https://github.com/rust-lang/rust/pull/75463).

Related: #76225

### CODE REVIEW

**Comment by CDirkx** [comment]
Created an issue for similar stabilizations: #76225

**Comment by KodrAus** [comment]
For reference, there's also an equivalent push to constify some `Result` methods at #76136

@rfcbot fcp merge

**Comment by KodrAus** [comment]
@rfcbot fcp merge

**Comment by josephlr** [comment]
It seems like `Option::iter()` `Option::flatten()` and `Option::transpose()` could also be stabilized without needing to `Drop` anything.

**Comment by ecstatic-morse** [comment]
`Option::iter` has been previously discussed. It's not very useful, since you can't do anything with it in a const context without const trait methods, which are unstable.

I believe (someone should verify this) that the other two would depend on the unstable `const_precise_live_drops` feature gate. They can (and should) be made unstably const, but cannot be stabilized at the moment.

**Comment by CDirkx** [comment]
I checked, even though nothing actually gets dropped inside `flatten` and `transpose`, `const_precise_live_drops` is required for the compiler to see this. You get `error[E0493]: destructors cannot be evaluated at compile-time` otherwise.

**Comment by josephlr** [comment]
> I believe (someone should verify this) that the other two would depend on the unstable `const_precise_live_drops` feature gate. They can (and should) be made unstably const, but cannot be stabilized at the moment.

This makes sense ([example playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d22cd9c0c7f8a057cf4647c214ae235e)), and also resolves my comment here: https://github.com/rust-lang/rust/pull/76136#issuecomment-691455440.

**Review by dtolnay — APPROVED** [review]

**Comment by dtolnay** [comment]
```console
Command failed. Attempt 5/5:
    Updating crates.io index
warning: spurious network error (2 tries remaining): error inflating zlib stream; class=Zlib (5)
warning: spurious network error (1 tries remaining): error inflating zlib stream; class=Zlib (5)
error: failed to get `cc` as a dependency of package `bootstrap v0.0.0 (D:\a\rust\rust\src\bootstrap)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error inflating zlib stream; class=Zlib (5)
failed to run: D:\a\rust\rust\build\i686-pc-windows-gnu\stage0\bin\cargo.exe build --manifest-path D:\a\rust\rust\src/bootstrap/Cargo.toml --locked
Build completed unsuccessfully in 0:00:21
make: *** [Makefile:60: prepare] Error 1
The command has failed after 5 attempts.
```

Hopefully not related to this PR.

@bors retry

**Comment by RalfJung** [comment]
I *think* this caused the clippy test failure in https://github.com/rust-lang/rust/pull/76907#issuecomment-695189502. The affected test, `redundant_pattern_matching_const_result`, mentions const option methods.

@bors r-

**Comment by CDirkx** [comment]
Yeah I'm looking into it, Clippy has a special case to not suggest `is_some`, `is_none`, `is_ok` and `is_err` inside a const context ([clippy#5724](https://github.com/rust-lang/rust-clippy/pull/5724)). 

Now that this stabilization for `Option` and the related one for `Result` (#76136) were accepted, would it be okay if I opened a new PR that merges them and also fixes Clippy for the both of them by removing the special casing machinery?

**Comment by CDirkx** [comment]
With #76136 merged I updated the testcases and now completely removed `can_suggest` from Clippy, essentially just reverting the changes made in [rust-clippy#5724](https://github.com/rust-lang/rust-clippy/pull/5724).

**Comment by RalfJung** [comment]
LGTM. @rust-lang/clippy could someone take a look at the clippy changes here?

**Pull request merged**
