### PR TITLE
Rename OnceCell methods to be more consistent with std conventions

### PR DESCRIPTION
**Pull request by matklad**
WDYT?

r? @ghost

### CODE REVIEW

**Comment by matklad** [comment]
r? @KodrAus 
cc @m-ou-se

**Comment by m-ou-se** [comment]
For `Option` we use `get_or_init` (and `get_or_init_width`): https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.get_or_insert_with

`get_with` (without `or`) sounds like the closure is always run.

**Comment by matklad** [comment]
Hm, I guess than it makes sense to use

```rust
get_or_insert_with
try_get_or_insert_with
```

for OnceCell?

The benefit is that it exactly matches the `Option`'s method (and has the same semantics).

The drawback is that it is long -- that's OK for Option, as it is one of it's rarely used methods. For OnceCell, however, that's the main API...

**Comment by KodrAus** [comment]
I was just coming to say the same thing 🙂 I don’t personally think `get_or_init_with` is unreasonably long.

**Comment by matklad** [comment]
rerenamed!

**Comment by m-ou-se** [comment]
So would a future `get_or_init` take the init value directly, instead of from a closure, just like `Option`? Or only have an `get_or_init_with` and no by-value counterpart?

**Comment by matklad** [comment]
Yup, I think we can have `get_or_insert(&self, value: T) -> &T`, as a reference-returning counterpart of `set`. We might bikeshed the return type (ideally, it is `Result<&T, (&T, T)>`)

**Comment by matklad** [comment]
CI fails because, apparently, one does not simply deprecate unstable std API. I'll remove the commit than...

**Comment by m-ou-se** [comment]
I think `#[rustc_deprecated]` (instead of `#[deprecated]`) would work on an unstable api.

**Comment by KodrAus** [comment]
A by-value get-or-init API doesn’t _seem_ very useful for these, have you ever come across use-cases that would want one? I think the `_with` suffix is a good change though!

I also didn’t think we needed to be consistent with `Option` and collections’ `insert` vs the once cells’ `init`, because in the context of once cells we are initializing the container. We have better terminology than insert to reach for which also has the nice benefit of being a little shorter.

**Comment by KodrAus** [comment]
Actually... Thinking about it you _might_ want something like that if each caller might initialise with a different value. In that case you’re not worried about expensive initialization, but who got in first.

**Comment by matklad** [comment]
Ok, it seems there's no quick consensus here... Let me register this as an unresolved question in the tracking issue.

**Pull request closed without merging**
