### PR TITLE
Read incremental files on-demand

### PR DESCRIPTION
**Pull request by cjgillot**
This should avoid a short-lived memory spike at the beginning of the compilation.

### CODE REVIEW

**Comment by jyn514** [comment]
cc @tgnottingham

**Comment by joshtriplett** [comment]
This does *substantially* reduce memory usage for incremental builds, but increases compile times.

This doesn't seem like it inherently needs to be slower. I'm wondering if using the ReadBuf-based interfaces might help here, to avoid repeatedly having to initialize buffers and use `resize`.

**Comment by joshtriplett** [comment]
I'm also wondering if it'd be possible to use `BufRead` for this, which does already have some of these optimizations (including `seek_relative`).

**Comment by bjorn3** [comment]
Could mmap be used here? Maybe with `madvise(MADV_SEQUENTIAL)` though after #82183 that would be better avoided.

**Comment by cjgillot** [comment]
I would rather avoid using mmap, because it's incompatible with #82780, and because it would be way too unsafe for my taste.
I tried to avoid touching the query result cache in anticipation for #82183.

**Comment by bjorn3** [comment]
I switched the metadata reading in cg_clif from `fs::read` to `mmap` yesterday. (https://github.com/bjorn3/rustc_codegen_cranelift/commit/b1d14ca05d6b34423c31fd237fdf2d6cd6f70333) The performance improvements for at least incr-clean were significant. Also constantly seeking is relatively expensive as it needs a syscall every time. A final benefit of `mmap` is that it allows the kernel to discard the data again when there is little memory left.

**Comment by bjorn3** [comment]
Also `MAP_PRIVATE` as used by memmap2's `map_copy_read_only` is a bit safer than `MAP_SHARED`. In addition `mmap` is used for the metadata reading by cg_llvm anyway.

**Comment by cjgillot** [comment]
Closing in favour of https://github.com/rust-lang/rust/pull/83214

**Pull request closed without merging**
