### PR TITLE
Update nomicon

### PR DESCRIPTION
**Pull request by ehuss**
Updates the nomicon to pull in https://github.com/rust-lang/nomicon/pull/450 to fix toolstate.

### CODE REVIEW

**Comment by fmease** [comment]
spurious?
@bors clean
@bors retry

**Comment by ehuss** [comment]
@bors retry

`ln: failed to create symbolic link './usr/lib/libpthread.so': File exists` for building solaris docker image.

**Comment by ehuss** [comment]
@bors treeclosed=100

Something is wrong with building a docker image.

**Comment by ehuss** [comment]
@bors retry

solaris pthread issue, sticking this back on top of the queue

**Comment by workingjubilee** [comment]
cc @psumbera Solaris build problems.

**Comment by psumbera** [comment]
> cc @psumbera Solaris build problems.

I'm confused. The change added twice `#[cfg(not(windows))]`. Which should have no meaning for Solaris!?

I have also no idea what `build-solaris-toolchain.sh x86_64` is supposed to exactly do..

Maybe some archives were updated (not related to this change)?

**Comment by workingjubilee** [comment]
@psumbera Yes, I'm currently trying out solving it in https://github.com/rust-lang/rust/pull/126011

I'm thinking the archives now generate the symlinks we were creating.

**Comment by workingjubilee** [comment]
Now part of #126011 
@bors r-

**Comment by workingjubilee** [comment]
Redundant PR (Ferris willing).

**Pull request closed without merging**
