### PR TITLE
CoVec MVP 2

### PR DESCRIPTION
**Pull request by peter-lyons-kehl**
IGNORE (until further notice). My early WIP.

Currently it triggers an ICE https://github.com/rust-lang/rust/issues/105573 (dealt with separately).

For now this draft PR uses Rust CI to build code that triggers https://github.com/rust-lang/rust/issues/105573. (As per https://rustc-dev-guide.rust-lang.org/contributing.html#ci: "perfectly fine (and even encouraged!) to use the CI to test your changes if it can help your productivity").

### CODE REVIEW

**Comment by peter-kehl** [comment]
r? peter-kehl

**Comment by compiler-errors** [comment]
Just a heads up that you can update your old PR with a force-push instead of opening up a new one, unless there's some other reason you closed the old PR :sweat_smile:

**Comment by workingjubilee** [comment]
Purely out of scholastic interest: what are "cooperative allocations", conceptually?

**Comment by peter-kehl** [comment]
Hi @workingjubilee. Thank you for improving Rust.

I admire your scholastic interest. I've added https://github.com/coop-rs/rust/wiki. Feel free to comment (raise an issue or start a discussion).

Any light on https://github.com/coop-rs/rust/issues/1, please? (It is about this pull request's failure: https://github.com/rust-lang/rust/actions/runs/3942485808/jobs/6746195481#step:26:786.) Or who could help?

**Comment by peter-kehl** [comment]
Replaced with https://github.com/rust-lang/rust/pull/107274.

**Pull request closed without merging**
