### PR TITLE
rustdoc: add #[allow(unused)] to every doctest

### LINKED ISSUE #45750: rustdoctest: no `allow` lints are put in doctests, contradicting Rustdoc Book
image

In [the current Rustdoc Book](https://doc.rust-lang.org/nightly/rustdoc/documentation-tests.html#pre-processing-examples), it mentions that a few lints are automatically `allow`ed in doctests:

> Some common `allow` attributes are inserted, including `unused_variables`, `unused_assignments`, `unused_mut`, `unused_attributes`, and `dead_code`. Small examples often trigger these lints.

However, as the image above demonstrates, this does not seem to be the case. I have not added any `#![doc(test(attr(warn(unused))))]` or similar attributes to my crate, which would override such behavior. These warnings are usually suppressed, but adding `--nocapture` when running tests shows these warnings. (It also shows more important warnings, like `unused_must_use`, which helped in a different library of mine.)

@rust-lang/docs @rust-lang/dev-tools - Is this a docs issue (which would mean removing this entry from the Rustdoc Book) or a rustdoc issue (which would mean making sure these items are added)?

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
More information in #45750 - this is behavior that was documented but not actually implemented.

I also reordered how outer attributes are applied to doctests. Previously, attributes from `#![doc(test(attr(...)))]` would be applied *after* attributes from within the test itself, meaning if a doctest tried to override lints that would be set crate-wide, it wouldn't work at all. This gives a better scope of how lints can be applied.

Closes #45750

### CODE REVIEW

**Comment by kennytm** [comment]
Some CI failures regarding playground.

The `rustdoc/no-run-still-checks-lints.rs` failure should be expected?

<details>

```
[01:00:27] failures:
[01:00:27] 
[01:00:27] ---- [rustdoc] rustdoc/playground-arg.rs stdout ----
[01:00:27] 	
[01:00:27] error: htmldocck failed!
[01:00:27] status: exit code: 1
[01:00:27] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/playground-arg.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/playground-arg.rs"
[01:00:27] stdout:
[01:00:27] ------------------------------------------
[01:00:27] 
[01:00:27] ------------------------------------------
[01:00:27] stderr:
[01:00:27] ------------------------------------------
[01:00:27] 24: @matches check failed
[01:00:27] 	`XPATH PATTERN` did not match
[01:00:27] 	// @matches foo/index.html '//a[@class="test-arrow"][@href="https://example.com/?code=extern%20crate%20foo%3B%0Afn%20main()%20%7B%0Ause%20foo%3A%3Adummy%3B%0Adummy()%3B%0A%7D"]' "Run"
[01:00:27] 
[01:00:27] Encountered 1 errors
[01:00:27] 
[01:00:27] ------------------------------------------
[01:00:27] 
[01:00:27] thread '[rustdoc] rustdoc/playground-arg.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2497:8
[01:00:27] 
[01:00:27] ---- [rustdoc] rustdoc/playground.rs stdout ----
[01:00:27] 	
[01:00:27] error: htmldocck failed!
[01:00:27] status: exit code: 1
[01:00:27] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/playground.stage2-x86_64-unknown-linux-gnu" "/checkout/src/test/rustdoc/playground.rs"
[01:00:27] stdout:
[01:00:27] ------------------------------------------
[01:00:27] 
[01:00:27] ------------------------------------------
[01:00:27] stderr:
[01:00:27] ------------------------------------------
[01:00:27] 37: @matches check failed
[01:00:27] 	`XPATH PATTERN` did not match
[01:00:27] 	// @matches foo/index.html '//a[@class="test-arrow"][@href="https://www.example.com/?code=fn%20main()%20%7B%0A%20%20%20%20println!(%22Hello%2C%20world!%22)%3B%0A%7D%0A"]' "Run"
[01:00:27] 38: @matches check failed
[01:00:27] 	`XPATH PATTERN` did not match
[01:00:27] 	// @matches foo/index.html '//a[@class="test-arrow"][@href="https://www.example.com/?code=fn%20main()%20%7B%0Aprintln!(%22Hello%2C%20world!%22)%3B%0A%7D"]' "Run"
[01:00:27] 39: @matches check failed
[01:00:27] 	`XPATH PATTERN` did not match
[01:00:27] 	// @matches foo/index.html '//a[@class="test-arrow"][@href="https://www.example.com/?code=%23!%5Bfeature(something)%5D%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%22Hello%2C%20world!%22)%3B%0A%7D%0A&version=nightly"]' "Run"
[01:00:27] 
[01:00:27] Encountered 3 errors
[01:00:27] 
[01:00:27] ------------------------------------------
[01:00:27] 
[01:00:27] thread '[rustdoc] rustdoc/playground.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2497:8
[01:00:27] 
[01:00:27] 
[01:00:27] failures:
[01:00:27]     [rustdoc] rustdoc/no-run-still-checks-lints.rs
[01:00:27]     [rustdoc] rustdoc/playground-arg.rs
[01:00:27]     [rustdoc] rustdoc/playground.rs
[01:00:27] 
[01:00:27] test result: FAILED. 167 passed; 3 failed; 1 ignored; 0 measured; 0 filtered out
```

</details>

**Comment by QuietMisdreavus** [comment]
It looks like `no-run-still-checks-lints.rs` passed tests when it was supposed to fail, and that's because supplying `#![allow(unused)]` followed by `#![deny(warnings)]` still allows the `unused` group, because you didn't specifically re-enable it. I'll change that code to only add it if no `#![doc(test(attr(...)))]` were supplied.

As for the playground ones, it seems like the playground links also use this code to assemble the run links, so i'll need to update those tests to include the new attribute.

**Comment by QuietMisdreavus** [comment]
I've force-pushed to address the test failures.

**Pull request merged**
