### PR TITLE
[WIP] Try using call-site aware IR PGO for LLVM

### PR DESCRIPTION
**Pull request by Kobzol**
LLVM has a second mode of PGO, called call-site aware PGO. Let's try if and how it works.

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Seems like the results here are worse than not doing this; I'm going to go ahead and close but feel free to reopen if needed.

**Comment by Kobzol** [comment]
Some of the previous runs had nice cycle wins, but they were gone in the last round, and this type of PGO made dist builds quite slower, so it was not worth it.

**Pull request closed without merging**
