### PR TITLE
crashes: add a couple more ice tests

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Feel free to r=me after CI is green.

**Comment by matthiaskrgr** [comment]
well the crux is that some of the may not crash on all of the targets so it's always a gamble (the first pr needed like 5-7 retries :(  to figure out all the test failures / unintended none-ICEs)

**Comment by jieyouxu** [comment]
> well the crux is that some of the may not crash on all of the targets so it's always a gamble (the first pr needed like 5-7 retries :( to figure out all the test failures / unintended none-ICEs)

Yeah, good luck :3

**Comment by matthiaskrgr** [comment]
maybe the test needs `needs-llvm-components: x86`?

@bors r=jieyouxu

**Pull request merged**
