### PR TITLE
Avoid ICE if environment variable is not set

### LINKED ISSUE #31238: rustdoc: unable to determine target arch from $CFG_COMPILER_HOST_TRIPLE
I just built from source (b8b18aa). Then I run:

    RUST_BACKTRACE=1 x86_64-unknown-linux-gnu/stage2/bin/rustdoc src/librustc/lib.rs

Output:

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'unable to determine target arch from $CFG_COMPILER_HOST_TRIPLE', src/libcore/option.rs:704
    stack backtrace:
       1:     0x7f5f25590760 - sys::backtrace::tracing::imp::write::hd89d31b61dd4636a0nu
       2:     0x7f5f2559740b - panicking::default_handler::_<closure>::closure.42795
       3:     0x7f5f25596f93 - panicking::default_handler::he52570f6dcb4275cEFy
       4:     0x7f5f255607b6 - sys_common::unwind::begin_unwind_inner::h3aebccca4b9bf29bygt
       5:     0x7f5f25561178 - sys_common::unwind::begin_unwind_fmt::h4813f7216103e62fEft
       6:     0x7f5f2558e371 - rust_begin_unwind
       7:     0x7f5f255d935f - panicking::panic_fmt::h370f66a0dae4fef5nYL
       8:     0x7f5f255f8e74 - option::expect_failed::h62f2fa1f9a82549ewsO
       9:     0x7f5f21287b65 - diagnostics::plugin::expand_build_diagnostic_array::h25d3f5688509a9a1Swb
      10:     0x7f5f23fed3d8 - ext::base::F.TTMacroExpander::expand::h7866968033327010450
      11:     0x7f5f2150d29d - ext::expand::expand_item_mac::h04cbae9fe49826f57A9
      12:     0x7f5f215000b1 - ext::expand::expand_annotatable::h95df9f39eb8f2216C59
      13:     0x7f5f214fd3a8 - ext::expand::expand_item::hb69cfed6380c1941ly9
      14:     0x7f5f21509155 - fold::noop_fold_mod::h15406053960004563981
      15:     0x7f5f21502dd1 - ext::expand::expand_item_underscore::hd828db04175e7b33Wy9
      16:     0x7f5f21537dfe - fold::noop_fold_item_simple::h396184506949694463
      17:     0x7f5f21537960 - fold::noop_fold_item::h17919760620970215817
      18:     0x7f5f21501469 - ext::expand::expand_annotatable::h95df9f39eb8f2216C59
      19:     0x7f5f214fd3a8 - ext::expand::expand_item::hb69cfed6380c1941ly9
      20:     0x7f5f21541672 - ext::expand::expand_crate::hc662996ec0a2f07dGta
      21:     0x7f5f24deb182 - driver::phase_2_configure_and_expand::_<closure>::closure.32909
      22:     0x7f5f24d7e8a6 - driver::phase_2_configure_and_expand::h9999dd8fbbf2e579hza
      23:     0x7f5f25aa4a1d - core::run_core::h6e8416ef3a1171b1Xdk
      24:     0x7f5f25aa0268 - sys_common::unwind::try::try_fn::h5136641819810760272
      25:     0x7f5f2558e308 - __rust_try
      26:     0x7f5f25585d6b - sys_common::unwind::try::inner_try::ha6a314e7a2e1ae926ct
      27:     0x7f5f25aa1f4f - boxed::F.FnBox<A>::call_box::h5932943521372803105
      28:     0x7f5f25595983 - sys::thread::Thread::new::thread_start::h49fd9650f679b92eoCx
      29:     0x7f5f1ea084a3 - start_thread
      30:     0x7f5f2521513c - clone
      31:                0x0 - <unknown>

### PR DESCRIPTION
**Pull request by ruuda**
This fixes #31238.

r? @michaelsproul

### CODE REVIEW

**Comment by michaelsproul** [comment]
Looks good, but probably best to at least spit a warning rather than silently failing to emit metadata. Usually, crates with `__build_diagnostics_arrray` are compiled via the build system, where that environment variable is defined. The case you found should be the only problematic one.

**Comment by ruud-v-a** [comment]
Fixed, please take another look.

**Comment by michaelsproul** [comment]
Looks perfectly reasonable but I won't have time to test it for a few days (and I also can't r+).

cc @brson @nrc ?

**Comment by nrc** [comment]
I would go further and emit an error, rather than a warning - not emitting metadata is pretty bad

**Comment by ruud-v-a** [comment]
Done. This now makes rustdoc fail with an error when I run `x86_64-unknown-linux-gnu/stage2/bin/rustdoc src/librustc/lib.rs` though. (Which at least is better than an ICE.)

**Comment by michaelsproul** [comment]
@ruud-v-a: To make your use case work you can always manually export the environment variable. I don't think the value is even significant as it's just used for naming, e.g. use "linux" instead of "x86_64-gnu-linux-unknown" (or whatever)

**Pull request merged**
