### PR TITLE
Relax Read bounds on a bunch of BufReader<R> methods

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by dtolnay** [comment]
@rfcbot fcp merge

#### Stable methods:

```diff
  impl<R> BufReader<R>
- where
-     R: Read,
  {
      pub fn get_ref(&self) -> &R { &self.inner }
      pub fn get_mut(&mut self) -> &mut R { &mut self.inner }
      pub fn into_inner(self) -> R { self.inner }
  }
```

#### Unstable methods (#45323):

```diff
  impl<R> BufReader<R>
- where
-     R: Read,
  {
      pub fn buffer(&self) -> &[u8] { &self.buf[self.pos..self.cap] }
  }
```

**Comment by Dylan-DPC** [comment]
ping from triage @dtolnay any updates?

**Pull request merged**
