### PR TITLE
Fallback to top-level config.toml if not present in current directory, and remove fallback for env vars and CLI flags

### LINKED ISSUE #94589: Fallback to top-level config.toml if not present in current directory
Currently x.py has some very strange behavior around config.toml.
- If `--config` and `RUST_BOOSTRAP_CONFIG` are unset, it will assume the file to use is `./config.toml` in the current directory, even if it doesn't exist.
- If either --config or RUST_BOOTSTRAP are set to a relative path, it will first look in the current directory, then fall back to the root directory if the file doesn't exist.
https://github.com/rust-lang/rust/blob/be18e614ee5ec5bb4972516f82035215f4814ac1/src/bootstrap/bootstrap.py#L1243

We should make these consistent and fall back to the root directory for the default path as well. @pnkfelix has mentioned in the past they use per-directory config.toml files, but this wouldn't break that workflow - the only thing that would change is that "switch to a new directory to get a blank build + config" would have to also run `touch config.toml`.

cc @Mark-Simulacrum
@rustbot label: +A-rustbuild +C-enhancement

### PR DESCRIPTION
**Pull request by jyn514**
This preserves the behavior where x.py will only give a hard error on a missing config file if it was configured through `--config` or RUST_BOOTSTRAP_CONFIG. It also removes the top-level fallback for everything except the default path; presumably if you're passing the path explicitly, you expect it to be exactly there and don't want to look in the root directory.

Fixes https://github.com/rust-lang/rust/issues/94589.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Speaking purely about desire end-state, loading order I think I would want:

1. --config $path
2. RUST_BOOTSTRAP_CONFIG $path [*]
3. $CWD/config.toml, if exists
4. $ROOT/config.toml, if exists

* If either (1) or (2) is set, we should not continue on if the file doesn't exist to later entries (i.e., no fallback); that is an error.
   * Where $path, if absolute, is just loaded, and otherwise is $CWD/$path.

I believe this PR is adding (4) to the list above, correct? The remaining delta from the list would then be the adjustment to relative path treatment in --config and RUST_BOOTSTRAP_CONFIG, which I am suggesting should be always relative to the current working directory, not falling back to the root (as is the case today, per #94589, if I follow correctly).

Please feel free to tell me why I shouldn't want this. I did briefly look at what other tooling does -- it seems like for example Git will not try to look in $CWD at all for configuration (per man git-config). It does seem pretty useful to look in CWD by default, though, and I think probably makes sense for our purposes.

**Comment by jyn514** [comment]
> If either (1) or (2) is set, we should not continue on if the file doesn't exist to later entries (i.e., no fallback); that is an error.

That makes sense to me, yeah. I added the fallback behavior for `--config` at the same time as `config.toml` in https://github.com/rust-lang/rust/pull/71994 and didn't think super hard about whether that was a good idea. The fallback for `RUST_BOOTSTRAP_CONFIG` has been present since it was added in https://github.com/rust-lang/rust/pull/73317; I don't think it was intentional to have a fallback there. Removing the fallback for the default happened in https://github.com/rust-lang/rust/pull/73590 which likewise seems unintentional.

I'll change this to remove the fallback for everything except the default path.

**Comment by Mark-Simulacrum** [comment]
r=me with PR description updated

**Comment by jyn514** [comment]
@rustbot ready

(I no longer have bors permissions.)

**Pull request merged**
