### PR TITLE
Skip coherence checks for error types

### LINKED ISSUE #30589: ICE: ty_is_local invoked on unexpected type: [type error] implementing trait for undeclared type
```rust
use std::fmt;

impl fmt::Display for DecoderError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Missing data: {}", self.0)
    }
}
fn main() {
}
```

```
/tmp/y:3:23: 3:35 error: use of undeclared type name `DecoderError` [E0412]
/tmp/y:3 impl fmt::Display for DecoderError {
                               ^~~~~~~~~~~~
/tmp/y:3:23: 3:35 help: run `rustc --explain E0412` to see a detailed explanation
error: internal compiler error: ty_is_local invoked on unexpected type: [type error]
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:230
```

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #30589.

### CODE REVIEW

**Comment by arielb1** [comment]
I suspect #29954 treats the issue closer to the root.

**Comment by sanxiyn** [comment]
This is a fallout of #30320. I don't see how #29954 helps. Both ICE says `ty_is_local invoked on unexpected type: [type error]`, but the source of error types is different. There is no unification going on here and the type is an error type from the start because it was undeclared.

**Comment by arielb1** [comment]
@sanxiyn 

Didn't notice that you are only working at the outer level. In that case, you probably want to check for `trait_ref.references_error()` (or `self_ty.references_error()` for inherent impls) to avoid problems with error types in inner places. r+ modulo that + test that ICEs your current example.

**Comment by nikomatsakis** [comment]
see also https://github.com/rust-lang/rust/pull/30676

**Comment by nikomatsakis** [comment]
Closing since this was subsumed into #30676.

**Pull request closed without merging**
