### PR TITLE
Clean up some uses of logging in ui tests

### PR DESCRIPTION
**Pull request by oli-obk**
The removed test can't possibly trigger anything today as we don't have logging in libstd.

The `exec-env` flag was mistakenly used for adding env vars to rustc invocations both in test and in the test suite and there were some accidental renames from RUST_LOG to RUSTC_LOG that I reverted.

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @JohnTitor

**Review by JohnTitor — COMMENTED** [review]
Overall looks good to me, let's clean-up more things that use obsoleted flags :)

https://github.com/rust-lang/rust/blob/fe08fb7b1e7cc5ef45e107f05b3cd30d48313d2b/src/test/ui/binding/func-arg-ref-pattern.rs#L2
https://github.com/rust-lang/rust/blob/fe08fb7b1e7cc5ef45e107f05b3cd30d48313d2b/src/test/ui/issues/issue-34932.rs#L3
https://github.com/rust-lang/rust/blob/fe08fb7b1e7cc5ef45e107f05b3cd30d48313d2b/src/test/ui/mismatched_types/const-fn-in-trait.rs#L1
https://github.com/rust-lang/rust/blob/fe08fb7b1e7cc5ef45e107f05b3cd30d48313d2b/src/test/ui/mismatched_types/trait-impl-fn-incompatibility.rs#L1

**Review by JohnTitor — APPROVED** [review]
It seems we should bless tests but otherwise looks good.

**Pull request merged**
