### PR TITLE
Prevent pointer -> int casts in constexprs

### PR DESCRIPTION
**Pull request by arielb1**
These cause issues, as addresses aren't fixed at compile-time.

Fixes #18294

### CODE REVIEW

**Comment by pnkfelix** [comment]
if these are disallowed ... then i guess the only reason for allowing int->ptr casts is for encoding null?  Is that accurate?

I ask because int->ptr casts are clearly part of the recipe that leads to #13973

**Comment by eddyb** [comment]
@pnkfelix being able to dereference a raw pointer  in a constant is the bug there. What semantics could it possibyt have, that don't involve tracking such values specially and limit the operations that can be performed on resulting lvalues and references?

**Comment by pnkfelix** [comment]
@eddyb but doesn't taking the address of the dereference effectively cancel out the dereference?  Am I being naive about this?

**Comment by eddyb** [comment]
Remember that taking the address of a dereference always produces a safe reference, so need to track that reference and disallow any use that may lead to a compile-time dereference, e.g. `1 + *&*(1337 as *const u8)` should not compile (with or without `*&`).

**Pull request merged**
