### PR TITLE
Remove unused abs_path method from rustc_span::source_map::FileLoader

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
I noticed this was unused, but I'm not sure if we want to keep it around for compatibility or not.

**Comment by Xanewok** [comment]
FWIW it's used [by the RLS](https://github.com/rust-lang/rls/blob/4a587b5fda6c2c9302562ece8c2795cd9848c553/rls/src/build/rustc.rs#L381) but the function is so trivial I'd be fine with removing this (in fact it is even [reimplemented](https://github.com/rust-lang/rls/blob/3bcfa0f466ce2d977f83ff1b0da938dbf72b1fc0/rls/src/build/ipc.rs#L147) in the ipc bridge for of the RLS).

**Comment by shlevy** [comment]
@Xanewok Looks like it's only used to implement the method itself in a wrapper? :slightly_smiling_face:

**Comment by Xanewok** [comment]
Well, you're right - rustc won't use it anyway so we might just get rid of it entirely. Thanks :+1: 

r? @Xanewok
@bors r+ rollup

**Comment by Dylan-DPC** [comment]
probably breaking rls in the rollup

@bors r-

**Comment by Xanewok** [comment]
Is this no-breakage week for tools already?

**Comment by Dylan-DPC** [comment]
Yep

**Comment by shlevy** [comment]
Sorry, does this mean we can't do this removal at all, or just that we have to wait a week?

If we can't remove it, can we mark it deprecated/unused?

**Comment by Dylan-DPC** [comment]
@shlevy just have to wait a week :)

**Comment by shlevy** [comment]
@Xanewok @Dylan-DPC Good to move forward?

**Comment by Xanewok** [comment]
I believe so, thanks

@bors r+

**Pull request merged**
