### PR TITLE
Point at overlapping impls when type annotations are needed

### PR DESCRIPTION
**Pull request by estebank**
Address https://github.com/rust-lang/rust/issues/89254.

### CODE REVIEW

**Comment by petrochenkov** [comment]
It didn't work, selecting a random active member.
r? @spastorino

**Comment by jackh726** [comment]
> It didn't work, selecting a random active member.

Yeah, should be "rust-lang/traits", but it might be prudent to make "wg-traits" an alias for that.

**Review by nikomatsakis — COMMENTED** [review]
this looks good to me! I didn't give it a detailed read, though, so maybe better for @spastorino or others to look a touch more closely at the code.

**Review by jackh726 — APPROVED** [review]
I think mostly just nits from me.

Some "regressions" in errors, imo. But I think on balance, they're fine.

r=me with or without the like one actionable comment done

**Pull request merged**
