### PR TITLE
Minor Iterator::filter_map description rewording.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/39294.

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors r-

i thought about this again. consider this code:

```rust
["1", "foo", "3"]
    .iter()
    .filter_map(|n| n.parse::<i32>())
    .collect()
```

here's how you'd implement it with `filter` then `map`:

```rust
["1", "foo", "3"]
    .iter()
    .filter(|n| n.parse::<i32>().is_some())
    .map(|n| n.parse::<i32>().unwrap())
    .collect()
```

i can't think of a way to implement it with `map` then filter:


```rust
["1", "foo", "3"]
    .iter()
    .map(|n| n.parse::<i32>())
    .filter(|n| n.parse::<i32>().is_some())
    .collect()  // [Some(1), Some(3)]
```

so i think you're idea to do "`filter` and `map`" might be a better suggestion here. what do you think?

**Comment by QuietMisdreavus** [comment]
The linked issue says it in terms of `map(your_closure_here).filter(is_some).map(unwrap)`, so by that formulation it's technically `map.filter.map`. By saying "`filter` and `map`" you somewhat lose the ordering implied in the docs as-is, but even your own "`map` with `filter`" is better than what's there right now. I'm fine with either suggestion (though i am somewhat partial to the rhythm of "filter and map" `>_>`).

**Comment by frewsxcv** [comment]
agreed with everything you said;switched to "map with filter"

@bors r=QuietMisdreavus

**Pull request merged**
