### PR TITLE
Fix naming misspelling

### LINKED ISSUE #63734: Misspelled test name "ui/non-interger-atomic.rs"
```diff
-ui/non-interger-atomic.rs
+ui/non-integer-atomic.rs
```

### PR DESCRIPTION
**Pull request by howjmay**
Fixes #63734

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Thanks!

r? @jonas-schievink @bors r+ rollup

**Comment by jonas-schievink** [comment]
@HowJMay Oh, I also edited the PR description to contain "Fixes #63734", that way the issue will automatically close once this PR is merged.

**Comment by jonas-schievink** [comment]
@bors r-

Ah, of course. You'll have to `--bless` this test so the stderr file is updated. Check the rustc guide for more info on how to do that: https://rust-lang.github.io/rustc-guide/tests/adding.html#editing-and-updating-the-reference-files

**Comment by HowJMay** [comment]
I run the test with following command, but it always comes with error.
```
./x.py test --test-args src/test/ui/non-integer-atomic.rc
```
Error
```
Updating only changed submodules
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/home/yanghau/Documents/rust/src/bootstrap/bootstrap.py", line 866, in main
    bootstrap(help_triggered)
  File "/home/yanghau/Documents/rust/src/bootstrap/bootstrap.py", line 830, in bootstrap
    build.update_submodules()
  File "/home/yanghau/Documents/rust/src/bootstrap/bootstrap.py", line 720, in update_submodules
    check = self.check_submodule(module, slow_submodules)
  File "/home/yanghau/Documents/rust/src/bootstrap/bootstrap.py", line 661, in check_submodule
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/home/yanghau/Documents/rust/src/llvm-project'
```
How could I do?

**Comment by HowJMay** [comment]
Hi @jonas-schievink I ran the command `./x.py test --test-args src/test/ui/non-integer-atomic.rs --bless`
and it took me a lot of time and space which caused the test failed. Did I use the wrong command?

**Comment by jonas-schievink** [comment]
@HowJMay try without the `--test-args`, that should work

**Pull request merged**
