### PR TITLE
Use CS PGO for LLVM

### PR DESCRIPTION
**Pull request by Kobzol**
Revival of https://github.com/rust-lang/rust/pull/97153. I want to try how it behaves now, with CS IR instrumentation mode.

r? @ghost

### CODE REVIEW

**Comment by Kobzol** [comment]
@rust-timer build 0a75e5fcd9e451d84f9810109a6ac60257e49322

**Comment by Kobzol** [comment]
@rust-timer build e1b0e5eae0e9416ffbd8cb434eb32756de11d563

**Comment by Kobzol** [comment]
@rust-timer build 69dea58a6c752143682fb9231f2398ed11df566d

**Comment by zamazan4ik** [comment]
@Kobzol Am I right that according to the testing above, CS PGO does not bring additional performance improvement for Rustc compared to the "usual" PGO?

**Comment by Kobzol** [comment]
It's weird, since it seems to gain improvements for others that are doing it (Google), and we use it for LLVM, not for rustc, where it is also supposed to provide benefits. There were a few perf. runs where it was a win (pn an older PR), but I can't manage to reproduce it.

**Comment by Kobzol** [comment]
It seems that CSIR PGO is just not worth it if BOLT is also used (https://aaupov.github.io/blog/2023/07/09/pgo). Closing.

**Pull request closed without merging**
