### PR TITLE
Map clone

### LINKED ISSUE #22243: Purge `map(|&x| x)` et al
Option and IteratorExt both have `.cloned()` which is sugar for this operation.

AKA

* `.map(|x| *x)`
* `.map(|x| x.clone())`
* `.map(|x| (*x).clone())` (yes, really)

### PR DESCRIPTION
**Pull request by ruuda**
This resolves #22243 for the single-letter variables that I could grep. Some occurences could not be replaced.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
much nicer, thanks!

**Comment by steveklabnik** [comment]
looks good to me

**Comment by Gankro** [comment]
I believe the collection ones you caught are done in https://github.com/rust-lang/rust/pull/22242 as well.

Although yours got r'd first so I guess I'll go revert mine.

Unless Git is smart enough to deal with identical changes?

Regardless, it seems like you missed a lot of the occurrences in collections, perhaps there was a flaw in your search pattern? (I basically ctrl+f'd for iter().map in all the collections files since I'm bad at sed/grep).

**Comment by ruud-v-a** [comment]
Oops, no I forgot those. (And maybe some other cases that are disguised better.) @Ryman: do you want to take care of those in #22287?

**Comment by Ryman** [comment]
@ruud-v-a Yeah, I'll take care of them when rebasing once the rollup lands later :) I'll also try to avoid the ones @Gankro has in their patch.

**Comment by Gankro** [comment]
If you exclude any path that includes `collections` you should be fine.

**Comment by Manishearth** [comment]
This was causing lots of failures in Steve's rollup: https://github.com/rust-lang/rust/issues/22352

**Comment by Manishearth** [comment]
Failed in the rollup again.

http://buildbot.rust-lang.org/builders/auto-win-32-nopt-t/builds/3322/steps/compile/logs/stdio

I recommend `rollup-` on this PR, needs some individual shepherding.

**Comment by Manishearth** [comment]
```
C:\bot\slave\auto-win-32-nopt-t\build\src\libstd\sys\windows\os.rs:307:41: 307:46 error: type `core::iter::Range<isize>` does not implement any method in scope named `len`
C:\bot\slave\auto-win-32-nopt-t\build\src\libstd\sys\windows\os.rs:307     fn len(&self) -> usize { self.range.len() }
                                                                                                               ^~~~~
C:\bot\slave\auto-win-32-nopt-t\build\src\libstd\sys\windows\thread_local.rs:247:42: 247:51 error: the trait `core::clone::Clone` is not implemented for the type `unsafe extern "C" fn(*mut u8)` [E0277]
C:\bot\slave\auto-win-32-nopt-t\build\src\libstd\sys\windows\thread_local.rs:247                 (*DTORS).iter().cloned().collect()
                                                                                                                          ^~~~~~~~~
error: aborting due to 2 previous errors
/c/bot/slave/auto-win-32-nopt-t/build/mk/target.mk:165: recipe for target 'i686-pc-windows-gnu/stage0/bin/rustlib/i686-pc-windows-gnu/lib/stamp.std' failed
make: *** [i686-pc-windows-gnu/stage0/bin/rustlib/i686-pc-windows-gnu/lib/stamp.std] Error 101
```

**Comment by pnkfelix** [comment]
(I agree with @Manishearth , this might need to go through runs on the try-server or something.)

**Comment by ruud-v-a** [comment]
My local test suite passed, is there anything I can do?

**Comment by pnkfelix** [comment]
@ruud-v-a are you running on a Windows machine?

If not, then it might be good for you to remove the windows-related changes, since those were what caused problems here, from what I can tell.

**Comment by ruud-v-a** [comment]
I do have a Windows box, but I never succeeded in compiling Rust there, will try now.

**Comment by Ryman** [comment]
This (including the fix for the failure) is covered in #22287, which seems to have gotten stuck in the buildqueue, so perhaps we can just close this one off?

**Comment by Gankro** [comment]
Sounds good to me.

**Pull request closed without merging**
