### PR TITLE
Set GDB substitution path to the current rust stdlib source

### PR DESCRIPTION
**Pull request by ccope**
rust-gdb was unable to find the source files when I tried stepping through stdlib functions. I can't figure out where `/checkout` is being set as the path to the source files, but running `objdump --dwarf=decodedline target/debug/mybin` showed that it's encoded in the DWARF data.

This change makes GDB substitute the path to match where rustup places the rust-src component.

Tested with rust 1.20 and 1.22.0-nightly (dd08c3070 2017-09-12)

### CODE REVIEW

**Comment by ccope** [comment]
For reference, when using the vim Conq-GDB plugin, I was seeing errors like this:
```
(gdb) server step                                                                                                                                                                                                                 
alloc::string::{{impl}}::push_str (self=0x7fffffffd450, string="buzz") at /checkout/src/liballoc/string.rs:743                                                                                                                    
743     /checkout/src/liballoc/string.rs: No such file or directory.
```

After the change, my vim buffer now switches to the stdlib source files as I step into functions.

**Comment by michaelwoerister** [comment]
Thanks, @ccope! That's a step in the right direction. However, I'm a bit worried about this silently giving you wrong results when compiling your code with one toolchain and then switching to another. 

@rust-lang/dev-tools What do you think?

**Comment by michaelwoerister** [comment]
Also cc @tromey and @vadimcn

**Comment by fitzgen** [comment]
The messed up source paths in the DWARF is a huge papercut, maybe to the degree that I shouldn't even call it a "papercut".

I think the best solution is to patch the DWARF on toolchain installation or something like that, so that we fix the problem for all DWARF consumers once and for all, rather than only for `rust-gdb`. That said, don't let perfect be the enemy of good: we should land anything that improves the development experience now and doesn't make the more correct solution more difficult down the line.

> silently giving you wrong results when compiling your code with one toolchain and then switching to another.

Is it possible to specify the specific toolchain path, rather than the current default toolchain path? (Apologies if this question is misguided: I'm not super familiar with rustup's directory structure)

**Comment by ccope** [comment]
I was guessing that the use of `/checkout` had something to do with reproducible builds, so having some sort of path substitution makes sense to me. I agree that pointing to the wrong rust-src could be confusing. I'm not seeing any rust compiler info in the ELF comment section, which is probably another bug, and that prevents us from comparing it to the current rustc version.

@fitzgen re: rustup paths, most users probably install the stable and/or nightly channels. This places the code under `~/.rustup/toolchains/$channel-$host`. rustup does have the capability to download particular toolchain versions, and maybe some people will have to do that if they want to debug older binaries, but for the common case the path isn't versioned.

For a cleaner solution, rustup could be extended to list all currently installed versions, and provide the paths to them. Then rust-gdb could call rustup to check if the desired version is present and where.

**Comment by cuviper** [comment]
> I think the best solution is to patch the DWARF on toolchain installation or something like that, so that we fix the problem for all DWARF consumers once and for all, rather than only for rust-gdb.

FWIW, Fedora runs `/usr/lib/rpm/debugedit -b "$RPM_BUILD_DIR" -d /usr/src/debug` when it's splitting debuginfo packages.  These sources will also include everything referenced by DWARF -- compiler crates, native code, etc. -- whereas `rust-src` only has `std` and its dependencies.  However, `debugedit` requires that the original `$RPM_BUILD_DIR` is a longer string than `/usr/src/debug`, so it can be patched directly without much rewriting.  That's not going to work from `/checkout/src/` to some long `/home/foo/.rustup/toolchains/...`

DWARF rewriting also doesn't cover paths from rlib metadata, for code that hasn't gone through codegen yet because it will be inlined or still needs monomorphization.

**Comment by vadimcn** [comment]
We could [embed a Python script](https://sourceware.org/gdb/onlinedocs/gdb/dotdebug_005fgdb_005fscripts-section.html#Script-Text-Entries) instead of just the file name into the binary and configure path substitution there...

**Comment by michaelwoerister** [comment]
Once [Path Prefix Remapping](https://github.com/rust-lang/rust/issues/41555) is stable, I'd like to use that for emitting a stable root tag for the debuginfo generated by our builds. So instead of `/checkout/src/liballoc/string.rs` you'd get `rust-<toolchain commit hash>/src/liballoc/string.rs` or something like that. Rustup could then keep a file with all toolchain-tags-to-local-src-dir mappings that could then be used in conjunction with `set substitute-path`. Since GDB would always have all available toolchain paths and toolchains would have a unique ID, there would be no mix ups. The file could be in a well known location so other tools could use it too.

The problem with `debugedit` and other DWARF-based tools is that they can't patch rlib-metadata. So if you use a generic function from `std` in your crate, you'd end up again with the `/checkout` path for that function.

If there was a way to patch rlibs during installation, as @fitzgen suggests, that would be even better.

**Comment by michaelwoerister** [comment]
Is there currently some way to could detect that the given sysroot is wrong? If we can avoid pointing GDB to the wrong source files, I'd be happy to approve the PR.

**Comment by michaelwoerister** [comment]
Maybe you could run `objdump -g <executable-to-be-debugged> | grep DW_AT_producer.*rustc` and compare the `rustc` version given by that to the output of `rustc --version`, and just not set the substitution if they differ. You'd have to know the path of the executable to be debugged though.

**Comment by ccope** [comment]
Ah, I wasn't aware that the version existed in the DWARF data. However, besides the difficulty in determining the executable from this script, there's also no guarantee that the user has objdump installed. I don't see any commands in GDB that can access that version data.

**Comment by michaelwoerister** [comment]
The only thing I can find is this: 
http://gdb-patches.sourceware.narkive.com/d6J239q5/info-source-now-includes-producer-string

**Comment by ccope** [comment]
Ah, so that does show the information, but not until tracing has started :-(

https://gist.github.com/ccope/49ca8cbb0b35058d8c26d693a102ae81

Other ideas:
 - encode the rust version into the binary in an ELF comment/note section, and read it out via python + lldb (llvm-readobj can do it, at least).
 - Add a cargo subcommand to spawn a debugger, and make it rebuild the binary first. If users use that mechanism, the rustc version would never be mismatched.

**Comment by carols10cents** [comment]
Sooooo @ccope @michaelwoerister what's the status of this PR? I'm having a tough time telling :)

**Comment by michaelwoerister** [comment]
The way the PR is now can lead to being shown wrong code while stepping through the standard library. On the one hand this could be very annoying because there might be no way to tell immediately that the code is wrong. On the other hand this would only happen if one compiles their code with one toolchain and then runs `rust-gdb` with another toolchain on their PATH -- which is an unlikely scenario but not can happen.

I would prefer if we *never* provided wrong source paths. 

@ccope How about this: `rust-gdb` somehow detects if `objdump` or `dwarfdump` is available, and if it is, uses that to verify that the `DW_AT_producer` value is compatible with `rustc --version`. And only then it will set the substitution path. Otherwise it will just not set it.

**Comment by cuviper** [comment]
Careful -- full DIE dumps on large binaries can take quite a long time!  Whereas a targeted tool can quickly walk just the CU DIEs and their attributes, which is all you need for `DW_AT_producer`.  And of course a single binary will probably have multiple CUs with their own producers, and the whole process will add all of its shared libraries to the mix.  (But with no Rust ABI, it's less likely you'd find a mix of rustc.)

Maybe rust-gdb by default should just print a *suggested* command for setting the substitution-path, as part of the startup banner.  This way we do no direct harm if it's wrong.  We could also add an argument like `--set-rust-src` to set it automatically, as an opt-in.

**Comment by fitzgen** [comment]
> Careful -- full DIE dumps on large binaries can take quite a long time! Whereas a targeted tool can quickly walk just the CU DIEs and their attributes, which is all you need for DW_AT_producer. And of course a single binary will probably have multiple CUs with their own producers, and the whole process will add all of its shared libraries to the mix. (But with no Rust ABI, it's less likely you'd find a mix of rustc.)

Threw this together: https://github.com/fitzgen/dwprod

**Comment by shepmaster** [comment]
@ccope it's been 7 days since we last heard from you; will you be able to address the reviewer comments from above?

**Comment by ccope** [comment]
Sorry for the delayed response, I've been doing some traveling lately. I updated the PR to address @michaelwoerister's comment about attempting to use objdump if it's available. (I tried doing it in bash at first but it got messy enough that I rewrote it in python). It should be easy to extend to check for `dwarfdump` or any other commands, but I haven't looked into what arguments they need.

@cuviper do you have an order-of-magnitude 99th-percentile runtime estimation for objdump? I'm trying to get a sense of the regression potential if we used it. If @fitzgen's dwprod tool is going to have significantly better performance I'd like to use that instead, but I'm not sure how we'd go about including it in the rust distribution?

**Comment by michaelwoerister** [comment]
Moving to Python seems fine to me. It will certainly make this easier to implement and review.

I'm wondering if we should *only* support `dwprod`. @fitzgen would you say that it is already stable enough? If it is not in PATH, we could just print a message "if you want to step through the standard library, run `cargo install dwprod`" or something along those lines.

**Comment by fitzgen** [comment]
`dwprod` is stable; it's a tiny tool, and even if its internals change a bit, I can't imagine the command-line interface changing.

**Comment by michaelwoerister** [comment]
I see that `dwprod` has a `--version` option, so we should be able to use it in a forward-compatible way.

Some comments on usability though:
* The script assumes that the executable being debugged is always that argument. This is not the case in general. The executable can be specified anywhere (e.g. `gdb --nx <executable> -b 123` works just fine). I think it would be too much work to reliably detect the right argument. But if `dwprod` fails because we gave it an invalid argument, we should print an error message that informs the user that they like have to rearrange their commandline arguments.
* The current version of the script seems to just fail unconditionally if there is a version mismatch. I think it should rather just warn that one will not be able to step through the standard library and give a hint like: "To get rid of this warning, set `RUST_DBG_IGNORE_LIBSTD_SRC=1`" 
* The "Install the appropriate rust and rust-src components" hint should mention that this is done via rustup. It should also mention that one also has to make sure that the `rustc` in PATH is the matching one.
* `RUST_DBG_SRC_PATH` should contain a hint that this has something to do specifically with `libstd`. I'd rename it to something like `RUST_DBG_LIBSTD_SRC_PATH`.

**Comment by alexcrichton** [comment]
triage ping for @ccope! Do you have thoughts on the recent comments here?

**Comment by ccope** [comment]
I originally felt like rust-gdb should fail hard if the correct source code wasn't available, because users might not see the messages. But on the other hand, most of the time users may not need to step into libstd functions, so it shouldn't die unnecessarily. I think the messages are also more prominent now, so they are less likely to be missed.

I haven't fully tested these changes yet, I will try to do it tomorrow.

**Comment by shepmaster** [comment]
> I will try to do it tomorrow.

Triage ping for @ccope — have you had an opportunity to test your changes?

**Comment by shepmaster** [comment]
Thanks for the PR, @ccope! Unfortunately, we haven't heard from you in a few weeks, so I'm going to go ahead and close this PR to keep things tidy. Please feel free to reopen once you've responded to the most recent feedback!

**Pull request closed without merging**
