### PR TITLE
Rename rustc_unicode to std_unicode

### PR DESCRIPTION
**Pull request by brson**
All other cases of the rustc "namespace" identify crates that are part
of the compiler, whereas this one is part of the standard library.  By
changing the name of this crate one can count on all "librustc"
directories being part of the compiler.

This has long bugged me.

r? @alexcrichton cc @rust-lang/libs

### CODE REVIEW

**Comment by brson** [comment]
cc @SimonSapin

**Comment by alexcrichton** [comment]
So long as it's always super private with tons of red tape saying "please don't use this" I'm pretty much fine with w/e name. I think `rustc_unicode` had the connotation of "private" due to the `rustc` namespace, but agreed that it's not appropriate for this lib itself.

I'll give it a bit though to see if anyone objects.

**Comment by japaric** [comment]
This is going to annoying to deal with in Xargo. It currently builds the sysroot by creating an empty `sysroot` crate that depends on all the C-free crates and `rustc_unicode` is one of those dependencies. I'd have to add some logic (probably date based) to build `std_unicode` instead of `rustc_unicode` or simply stop building the unicode crate; I have no idea if anyone actually uses it.

If not a priority, I'd prefer if this rename landed after std-aware Cargo becomes a thing and Xargo is no longer necessary but perhaps that would be too late? I don't what's the stability policy around the standard crates Cargo could access to. As in: are renames possible after std-aware Cargo comes into existence?

**Comment by FenrirWolf** [comment]
Uh-oh. I'm using `rustc_unicode` in [ctru-rs](https://github.com/FenrirWolf/ctru-rs/tree/filesystem) because the Nintendo 3DS uses UTF-16 filepaths and `encode_utf16()` isn't available on `collections::String`

**Comment by japaric** [comment]
@FenrirWolf Noted! Since there's at least one user, Xargo will continue to supported the unicode crate.

**Comment by alexcrichton** [comment]
I think we're fine wrt renaming crates like this. We obviously can't rename a stable crate, but unstable crates can't be stably depended on anyway so I'd be fine considering this "acceptable breakage" under that banner.

**Comment by SimonSapin** [comment]
Renaming sounds fine to me, modulo xargo concerns.

@FenrirWolf can you confirm what API is missing? Sounds like we should add something to libcore or libstd.

**Comment by FenrirWolf** [comment]
Looks like it's `char::decode_utf16()` that I'm using from `rustc_unicode`. It's available in the standard library, but I'm limited to freestanding crates for this project.

Either way, will renaming the unicode crate really keep Xargo from building it? looks like it's still freestanding even with these changes.

**Comment by aturon** [comment]
I'm also fine with renaming.

**Comment by SimonSapin** [comment]
As far as I understand, the issue with xargo is to decide which sysroot crates to build. But I suppose it could check whether a `std_unicode` directory exists?

----

Taking another look at the naming convention: if we’re going with a `std_` prefix, shouldn’t all in-tree recursive dependencies of `std` have it?

**Comment by japaric** [comment]
> But I suppose it could check whether a std_unicode directory exists?

Sure, it can be done. It's just annoying to keep adding ad hoc logic to Xargo.

**Comment by brson** [comment]
Since there's no pressing need to do this, I'm going to close, but we are going to rename this crate someday. Unstable things are unstable for a reason.

**Pull request closed without merging**
