### PR TITLE
Improve missing_abi lint

### PR DESCRIPTION
**Pull request by m-ou-se**
This is for the migration lint for https://github.com/rust-lang/rfcs/pull/3722

It is not yet marked as an edition migration lint, because `Edition2027` doesn't exist yet.

The lint now includes a machine applicable suggestion:

```
warning: extern declarations without an explicit ABI are deprecated
 --> src/main.rs:3:1
  |
3 | extern fn a() {}
  | ^^^^^^ help: explicitly specify the C ABI: `extern "C"`
  |
```

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
LGTM, and happy to approve this if and when it is approved on the lang side.

Would like to see some explicit tests exercising that this does in fact error in edition 2024, and perhaps also exercising the error on free extern functions (`extern fn() {}`) vs extern blocks.

**Comment by compiler-errors** [comment]
Well, seems like from the RFC that this may be too late for 2024: https://github.com/rust-lang/rfcs/pull/3722#issuecomment-2447333966. 

However, it would be very cool to pull out the edition-independent parts of this -- the migration can be applied to the lint itself, and storing the extern span seems nice to do anyways.

**Comment by m-ou-se** [comment]
Updated. Removed the edition stuff. This now just improves the lint. I'll send a separate PR to make it warn-by-defualt that can then be FCP'd.

**Review by compiler-errors — APPROVED** [review]

**Pull request merged**
