### PR TITLE
update Miri

### PR DESCRIPTION
**Pull request by RalfJung**
Not a huge sync, but there was a conflict and [josh](https://github.com/josh-project/josh/) seems to prefer those to be merged back ASAP.

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r-

dang... @oli-obk latest ui_test depends on fastrand which needs to be permitted as a dependency. What is the paperwork for that?^^

**Comment by oli-obk** [comment]
License looks good, also well maintained. Just add it to the list.

**Comment by RalfJung** [comment]
@rust-lang/compiler I had to allow `fastrand` as dependency to be able to bump `tempfile`.

@bors r+

**Pull request merged**
