### PR TITLE
fix objc ABI in std::env::args

### PR DESCRIPTION
**Pull request by kali**
iOS use different calling convention for `objc_msgSend` depending on the platform. armv7 expect good old variadic arguments, but aarch64 wants "normal" convention: `objc_msgSend` has to be called mimicking the actual callee prototype.

https://developer.apple.com/library/content/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html#//apple_ref/doc/uid/TP40013501-CH3-SW26

This currently breaks std::env:args() on aarch64 iOS devices. As far as I can tell, in the standard library, this is the only occurrence of ObjectiveC dispatching.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I'm kinda surprised this works though because it seems like it's defining the same symbol twice with LLVM with different signatures, which has historically led to lots of aborts. Have you tested this out locally to see if it works?

**Comment by kali** [comment]
It definitely fixes the aarch64 version. Let me check the armv7 variant.

**Comment by rkruppe** [comment]
It doesn't define the symbols twice, it picks one definition each based on cfg(target_arch).

**Comment by kali** [comment]
Ok, it's been a bit slow and painful, but I did manage to compile to armv7 and run on a phone with no complaints from LLVM.

**Comment by alexcrichton** [comment]
Hm the compiler is doing something here I'm quite surprised by and didn't expect, but seems to work. The symbol is defined once with the first signature and then casted each time it's used a different time to the different signature. In any case though it looks like it works, so let's get this in

@bors: r+

**Comment by kali** [comment]
thanks!

**Comment by brson** [comment]
Nice find.

**Pull request merged**
