### PR TITLE
update stdsimd

### PR DESCRIPTION
**Pull request by RalfJung**
Cc @gnzlbg

### CODE REVIEW

**Comment by gnzlbg** [comment]
oh sorry, LGTM! This update should go smoothly since rust-lang/rust is tracking stdsimd very closely lately.

**Comment by RalfJung** [comment]
So should I do r=gnzlbg then or how do you usually handle this?

**Comment by RalfJung** [comment]
Looks like there is precedence for that, so let's do that.

@bors r=gnzlbg

**Comment by bjorn3** [comment]
Why is bors testing this and #59671? It is already merged.

**Comment by RalfJung** [comment]
Uh... bors seems very confused.

@bors r- retry

Cc @rust-lang/infra
Vors says on https://buildbot2.rust-lang.org/homu/queue/rust that it is testing this one (and the other one in parallel?!?), but looking at https://travis-ci.com/rust-lang/rust/ it is not actually doing anything.
This is one of those PRs that was rolled up and then immediately next in the queue. So bors started building it and then aborted (?) because GH updated the PR status to "merged". But it seems bors didn't really drop it.

**Comment by pietroalbini** [comment]
Heh, weird things happen when bors is redeployed...

**Pull request merged**
