### PR TITLE
Set codegen thread names

### PR DESCRIPTION
**Pull request by wesleywiser**
Set names on threads spawned during codegen. Various debugging and profiling tools can take advantage of this to show a more useful identifier for threads.

For example, gdb will show thread names in `info threads`:

```
(gdb) info threads
  Id   Target Id                                          Frame
  1    Thread 0x7fffefa7ec40 (LWP 2905) "rustc"           __pthread_clockjoin_ex (threadid=140737214134016, thread_return=0x0, clockid=<optimized out>, abstime=<optimized out>, block=<optimized out>)
    at pthread_join_common.c:145
  2    Thread 0x7fffefa7b700 (LWP 2957) "rustc"           0x00007ffff125eaa8 in llvm::X86_MC::initLLVMToSEHAndCVRegMapping(llvm::MCRegisterInfo*) ()
   from /home/wesley/.rustup/toolchains/stage1/lib/librustc_driver-f866439e29074957.so
  3    Thread 0x7fffeef0f700 (LWP 3116) "rustc"           futex_wait_cancelable (private=0, expected=0, futex_word=0x7fffe8602ac8) at ../sysdeps/nptl/futex-internal.h:183
* 4    Thread 0x7fffeed0e700 (LWP 3123) "rustc"           rustc_codegen_ssa::back::write::spawn_work (cgcx=..., work=...) at /home/wesley/code/rust/rust/compiler/rustc_codegen_ssa/src/back/write.rs:1573
  6    Thread 0x7fffe113b700 (LWP 3150) "opt foof.7rcbfp" 0x00007ffff2940e62 in llvm::CallGraph::populateCallGraphNode(llvm::CallGraphNode*) ()
   from /home/wesley/.rustup/toolchains/stage1/lib/librustc_driver-f866439e29074957.so
  8    Thread 0x7fffe0d39700 (LWP 3158) "opt foof.7rcbfp" 0x00007fffefe8998e in malloc_consolidate (av=av@entry=0x7ffe2c000020) at malloc.c:4492
  9    Thread 0x7fffe0f3a700 (LWP 3162) "opt foof.7rcbfp" 0x00007fffefef27c4 in __libc_open64 (file=0x7fffe0f38608 "foof.foof.7rcbfp3g-cgu.6.rcgu.o", oflag=524865) at ../sysdeps/unix/sysv/linux/open64.c:48
(gdb)
```

and Windows Performance Analyzer will also show this information when profiling:

image

### CODE REVIEW

**Comment by nagisa** [comment]
This makes sense to me. I wonder if it really makes sense to use different names between windows and unixes (knowledge between platforms becomes less portable – think somebody from unix advising windows person to look for thread "copy foo.o" or vice versa). But otherwise LGTM.

@bors r+

**Comment by andjo403** [comment]
had the cgu name been more informative in the *nix names instead of the module name? will the module name be the same for all threads in the same process?

**Comment by the8472** [comment]
This would have to be removed if the tasks were moved to a threadpool.

**Comment by nagisa** [comment]
> This would have to be removed if the tasks were moved to a threadpool.

This is correct, but I don't believe there is much value in spending effort to move to a threadpool here given the number of threads we spawn here. I also don't believe there are any threadpool implementations out there that integrate with jobserver.

> had the cgu name been more informative in the *nix names instead of the module name? will the module name be the same for all threads in the same process?

I'm not sure what you're asking – this PR appears to use what looks like a CGU name on either platform. In practice the end of the CGU name will get cut off on unixes, so you won't be able to tell them apart anyway. That said, specific improvements to naming can be introduced as followups – its not like these names need to be stable.

**Comment by wesleywiser** [comment]
> I'm not sure what you're asking – this PR appears to use what looks like a CGU name on either platform. In practice the end of the CGU name will get cut off on unixes, so you won't be able to tell them apart anyway. That said, specific improvements to naming can be introduced as followups – its not like these names need to be stable.

Yeah, I strongly agree with this! I found having even incomplete thread names was more helpful than the current status quo of not having any. If other people have even better ideas in the future, I'd be happy to see them improved further.

**Comment by andjo403** [comment]
what I badly was trying to say was in the examples for unix the log say "opt foof.7rcbfp" for all threads maybe it hade been nicer with e.g "opt gcu15" and so on as that is the part that is shown i the windows example as something that change between threads.

but for windows this looks amazing.

**Pull request merged**
