### PR TITLE
Support C23's Variadics Without a Named Parameter

### LINKED ISSUE #123773: Unable to call variadic function with no named parameters even though it is useful since C23
You have always been able to define variadic functions in C with no named parameters, but until C23 it was not useful because you could never access those arguments
Since C23 the `va_start` macro in C has been changed to no longer require a parameter name, so now being able to call variadic functions with no named parameters is actually useful

```rust
extern "C" {
    fn foo(...);
}
```

I would expect this to compile, if there was a function `foo` defined in C like so
```c
void foo(...) { // the ... is optional pre-c23, but since C23 its required to make the function variadic
    // whatever implementation
}
```

But instead this does not compile
```rust
error: C-variadic function must be declared with at least one named argument
 --> src\lib.rs:2:12
  |
2 |     fn foo(...);
  |            ^^^
```

### Meta
`rustc --version --verbose`:
```
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-msvc
release: 1.76.0
LLVM version: 17.0.6
```

### PR DESCRIPTION
**Pull request by veera-sivarajan**
Fixes #123773

This PR removes the static check that disallowed extern functions
with ellipsis (varargs) as the only parameter since this is now
valid in C23.

This will not break any existing code as mentioned in the proposal 
document: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2975.pdf.

Also, adds a doc comment for `check_decl_cvariadic_pos()` and
fixes the name of the function (`varadic` -> `variadic`).

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
r=me, needs T-lang approval though first

**Comment by tmandry** [comment]
Seems like a reasonable extension.

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Pull request merged**
