### PR TITLE
Tweak assert_unsafe_precondition helpers so they optimize well in MIR

### PR DESCRIPTION
**Pull request by saethlin**
It turns out that https://github.com/rust-lang/rust/pull/104121 does not actually achieve what @Lokathor wanted, when debug assertions are enabled. In my opinion there are really multiple issues here, this PR addresses all of them:

The implementation of `is_aligned_and_not_null` is compiled to a shocking amount of MIR, because the implementation of `ptr::is_null` is contorted to work in `const fn`, and the implementation of `ptr::is_aligned` is based on `ptr::is_aligned_to` which among other things has a check that the alignment is a power of 2. These of course clean up quite nicely in LLVM... but the goal here is to enable inlining _before_ we get to LLVM.

Then some of the helper functions aren't `#[inline]`. The MIR inliner only inlines `#[inline]` functions at `-Zmir-opt-level=2`, which is what `--release` corresponds to. Whether or not that heuristic should be loosened up, these are good candidates for inlining so I don't see any harm in adding the attribute.

Then the MIR inlining cost estimation seems a bit pessimistic to me. The MIR we generate tends to have a lot of assignments from locals to locals. By eye it looks like a lot of these could be erased by another optimization pass, so I don't think they represent nearly the complexity of any other instruction. For now, this excludes them from cost estimation entirely.

I also removed the extra function call penalty from diverging call terminators. My logic there is that a diverging terminator is often a panic path, and those sometimes (and especially in this case) have a predicate which can be statically reasoned about. There is a fair chance that inlining a function with a diverging terminator will result in optimizing away the divergence entirely, or making other optimizations after the diverging path, based on assume its predicate. (I'm aware that currently MIR opt is not very good at this sort of cleanup, so this is somewhat of a gamble)

(I hope this looks good in perf...)

r? @cjgillot 
cc @JakobDegen

### CODE REVIEW

**Comment by oli-obk** [comment]
Please add some mir opt tests showing that these changes actually affect anything.

Wrt diverging functions: we need to make sure that we never inline `#[cold]` functions, except into other `#[cold]` functions, I don't remember if we already do that

**Comment by Lokathor** [comment]
Currently `cold` will block mir inline in all cases, even if the caller is also `cold`.

**Comment by saethlin** [comment]
I've changed direction here, closing this so people don't get notifications for something they didn't sign up for.

**Pull request closed without merging**
