### PR TITLE
Mark all functions defined in compiler-builtins as nounwind

### PR DESCRIPTION
**Pull request by nbdd0121**
Treat functions in compiler-builtins as nounwind. Suggested in https://github.com/rust-lang/compiler-builtins/pull/578#issuecomment-1962958653.

A prerequisite for #116088

r? @Amanieu 
cc @RalfJung

### CODE REVIEW

**Comment by DianQK** [comment]
Would it be more appropriate to apply `rustc_nounwind` to the crate level?

**Comment by Amanieu** [comment]
I think it's fine to special case it for now. If we ever want a crate-level attribute then we could revisit this.

@bors r+

**Comment by saethlin** [comment]
This might improve MIR optimizations. I previously found that `#[rustc_nounwind]` functions could have landing pads generated for them in MIR and recently added a MIR optimization that enables removing them: https://github.com/rust-lang/rust/pull/120594/files#diff-599b525825845c57f49b8c7ba0ca19e8434f1d34a1b9b73db3be84f4f673066d

Queue looks light, so this might be nice to help perf triage:
@bors rollup=iffy

**Comment by RalfJung** [comment]
My understanding is that on its own this does nothing since the crate does not set `feature(c_unwind)`?

**Comment by RalfJung** [comment]
Hm no that does not seem right; `c_unwind` is only checked later in `fn_can_unwind`. I must have misunderstood what others said yesterday.

**Comment by nbdd0121** [comment]
The error is caused by

https://github.com/rust-lang/compiler-builtins/blob/351d48e4b95f1665cfd3360e3ba8f3dd4d3fb3c1/src/arm_linux.rs#L7

which uses `extern "C"`, but since compiler-builtins do not have `feature(c_unwind)` enabled, it is treated as unwindable.

Some options here:
1. Update compiler-builtins to add `feature(c_unwind)`, and bunble version bump together with this PR. But this will mean that the compiler-builtins CI will be broken after the change and before this PR is merged.
2. Add special casing to `fn_can_unwind` in this PR so that compiler_builtins is treated as effectively with `feature(c_unwind)`
3. Drop this PR and make the change together in `c_unwind` stabilisation.

What's the best action here?

**Comment by Amanieu** [comment]
FWIW compiler-builtins CI is currently already broken due to #121552.

I would just go with option 3.

**Comment by Amanieu** [comment]
I believe #122580 will make this PR unnecessary.

**Comment by saethlin** [comment]
The justification I mentioned above still applies: https://github.com/rust-lang/rust/pull/121605#issuecomment-1963275797

**Comment by BatmanAoD** [comment]
@nbdd0121 Are you going to incorporate (or have you already incorporated) these changes into #116088, or are you still considering options #1 or #2 from your comment above?

**Comment by RalfJung** [comment]
I think this is not needed any more: https://github.com/rust-lang/compiler-builtins/pull/583 landed, so compiler_builtins is now already working fine with proper c_unwind behavior. So, closing the PR (and the commit should be removed from https://github.com/rust-lang/rust/pull/116088).

**Pull request closed without merging**
