### PR TITLE
In panicking.rs, change to usize from uint

### PR DESCRIPTION
**Pull request by strega-nil**

### CODE REVIEW

**Comment by rprichard** [comment]
We really should change that parameter to u32.

**Comment by GBGamer** [comment]
@rprichard Yeah, you're right. Let me fix that.

**Comment by rprichard** [comment]
... but to change it to `u32`, you need to update all the other places that are using `usize`.  Grep for `panic_fmt` -- for example, the `libstd/rt/unwind.rs` code uses `usize` for the line number.  I'm pretty sure `panic_fmt` also shows up in the docs.  The compiler knows about the `panic_fmt` lang item, but I don't know whether it expects a particular type signature; I'm guessing not?

The `line as u32` cast isn't necessary.

I think it'll be necessary to use the `#[cfg(stage0)]` / `#[cfg(not(stage0))]` tags, so we can keep using `usize` for the stage0 libraries while using `u32` for the stage1 and stage2 libraries.  For example, see this commit: https://github.com/rust-lang/rust/commit/647e54d6d154e1a267e84c8ae9f1315e3f9b93fc

**Comment by rprichard** [comment]
The `panic!` macro in libstd/macros.rs needs updating.

> I think it'll be necessary to use the #[cfg(stage0)] / #[cfg(not(stage0))] tags, so we can keep using usize for the stage0 libraries while using u32 for the stage1 and stage2 libraries.

Or maybe not.  If the stage0 compiler doesn't care about the type signature of `panic_fmt`, then maybe the `usize`->`u32` change is completely contained inside the libraries.

**Comment by GBGamer** [comment]
Fine, I need to actually do work on this. Just let the PR be for now, or
close it, and I'll fix it later.

**Comment by alexcrichton** [comment]
This appears to have migrated in the meantime, so closing. Thanks though!

**Pull request closed without merging**
