### PR TITLE
Bump RLS and Rustfmt submodules to use rustc-ap-* v583

### LINKED ISSUE #64179: `rls` no longer builds after rust-lang/rust#64172
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#64172, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### LINKED ISSUE #64180: `rustfmt` no longer builds after rust-lang/rust#64172
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#64172, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by Xanewok**
Closes #64180 
Closes #64179

r? @topecongiro

### CODE REVIEW

**Comment by Xanewok** [comment]
Unfortunately https://github.com/rust-lang/rust/pull/64139 has been merged which means we need to re-update the versions yet again... 😭

**Comment by topecongiro** [comment]
@Xanewok Released rustfmt 1.4.8 which uses rustc-ap-syntax 583.0.0.

cc @kngwyu

**Comment by kngwyu** [comment]
@Xanewok 
I published racer 2.1.27 too

**Comment by Xanewok** [comment]
Updated to use v583 and fixed, hopefully smoke test will agree (tested manually but better safe than sorry :man_shrugging:)

**Comment by tmandry** [comment]
I'd like to get this in the queue now so we can have green toolstate. Will r- if tests fail.

@bors r+ p=1

**Pull request merged**
