### PR TITLE
Update ICU4X

### PR DESCRIPTION
**Pull request by Noratrieb**
This updates all ICU4X crates and regenerates rustc_baked_icu_data.

Since the new unicode license under which they are licensed does not have an SPDX identifier yet, we define some exceptions. The license has to be reviewed to make sure it is still fine to use here, but I assume that is the case.

I also added an exception for rustc_icu_data to the unexplained ignore doctest tidy lint. This is a bit hacky but the whole style.rs in tidy is a mess so I didn't want to touch it more than this small hack.

part of #112865

r? @davidtwco @wesleywiser @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
You should actually be able to get rid of rustc_baked_icu_data and use the compiled_data feature but that might be best handled in a separate PR.

**Review by davidtwco — APPROVED** [review]
Looks good to me - I don't believe there are any issues with the Unicode V3 license. r=me unless you want to try @klensy's suggestion.

**Comment by Nilstrieb** [comment]
I'll merge this as-is, more bumps can always be done later.
@bors r=@davidtwco

**Comment by Nilstrieb** [comment]
the mingw builder spent 3h uploading the results to S3

**Pull request merged**
