### PR TITLE
Remove experimental chalk option

### PR DESCRIPTION
**Pull request by CAD97**
As suggested by @nikomatsakis [here](https://github.com/rust-lang/rust/pull/68807#issuecomment-583339932).

The current version of chalk used by the experimental `-Zchalk` flag is [v0.9.0, which is over a year old](https://crates.io/crates/chalk-engine). Since v0.9.0, chalk has seen [a lot of further development](https://github.com/rust-lang/chalk/compare/41dfe13...master), and the intent is to eventually upgrade rustc to use a more recent chalk.

However, it will take a decent chunk of effort to upgrade the current experimental chalk support, and it is currently [blocking at least some PRs](https://github.com/rust-lang/rust/pull/68807) due to chalk:0.9.0's use of unstable features. So for the interim until the next chalk release and experimental rustc integration, we remove the chalk-specific code from rustc.

### CODE REVIEW

**Comment by jackh726** [comment]
FWIW, I've gotten (locally) the Chalk code updated to the latest Chalk master (with some modifications that'll get PRed soon). It compiles but `-Z chalk` tests are broken.

**Comment by CAD97** [comment]
Just for good measure, I suppose I should cc @rust-lang/wg-traits

**Comment by nikomatsakis** [comment]
OK so I talked to @jackh726 and we agreed that we could go ahead and land this, we'll just "git revert" it and build our replacement. I did a review and it looks good, but it needs a rebase.

@bors delegate=CAD97

@CAD97 if you want to rebase, you can go ahead and make it r=nikomatsakis afterwards.

**Comment by CAD97** [comment]
Rebased. If only GitHub actually had a way to show _just_ the conflict resolution of the rebase...

@bors r=nikomatsakis

**Comment by CAD97** [comment]
@bors r-

Test failures crept into the rebase; investigating

**Comment by CAD97** [comment]
@bors: r=nikomatsakis

I missed a trailing newline, that's it.

**Pull request merged**
