### PR TITLE
Emit save analysis notifications

### PR DESCRIPTION
**Pull request by jsgf**
Addresses issue https://github.com/rust-lang/rust/issues/61047

### CODE REVIEW

**Comment by jsgf** [comment]
Is this stuck?

**Comment by alexcrichton** [comment]
@bors: r+

Looks like bors forgot about it by accident!

**Comment by jsgf** [comment]
It looks like the failures where just "job cancelled".

**Comment by jsgf** [comment]
Tests fixed.

**Comment by Centril** [comment]
Ping from triage; @jsgf looks like you need to `--bless --compare-mode=nll` ?

**Comment by jsgf** [comment]
@Centril Thanks - I wasn't sure how to deal with that.

**Comment by jsgf** [comment]
Whee! All passed.

**Pull request merged**
