### PR TITLE
Fix naming in the lint API

### PR DESCRIPTION
**Pull request by nnethercote**
Methods for emit lints are named very inconsistently. This PR fixes that up.

r? @compiler-errors

### CODE REVIEW

**Comment by nnethercote** [comment]
Here is the table I worked from.
```
old name               args                                    new name
------                 -----------------------------------     --------
LintContext
- lint                 lint,               msg, decorate        // lint (unchanged)
- struct_span_lint     lint,         span, msg, decorate        // span_lint
- lookup_with_diags    lint,         span, msg, decorate, diags // span_lint_with_diags
- lookup               lint,     opt_span, msg, decorate        // opt_span_lint
- emit_lint            lint,                    decorator       // emit_lint (unchanged)
- emit_spanned_lint    lint,         span,      decorator       // emit_span_lint

LintLevelsBuilder (missing plain `lint`)
- struct_lint          lint,     opt_span, msg, decorate        // opt_span_lint
- emit_lint            lint,                    decorator       // emit_lint (unchanged)
- emit_spanned_lint    lint,         span,      decorator       // emit_span_lint

TyCtxt
- struct_lint_node     lint, hir_id,       msg, decorate        // node_lint
- struct_span_lint_hir lint, hir_id, span, msg, decorate        // node_span_lint
- emit_lint            lint, hir_id,            decorator       // emit_node_lint
- emit_spanned_lint    lint, hir_id, span,      decorator       // emit_node_span_lint

(top-level)
- struct_lint_level    lint,lvl,src, span, msg, decorate        // lint_level
```
Improvements:
- Remove misleading `struct_` prefixes. These functions don't return
  diagnostics, they emit!
- Use `span` instead of `spanned`, for consistency with normal diagnostics.
- Retain `emit_` prefix for newer cases using `decorator: DecorateLint`, and
  use no prefix for older cases using `decorate`, similar to how it's done for
  normal diagnostics.
- Use `node` consistently for the `TyCtxt` ones, not a mix of `node` and `hir`.
- Replace `lookup`, which is so vague that it's meaningless.
- Make the equivalent functions across the different types have the same name.

**Comment by oli-obk** [comment]
the `node` part of the TyCtxt methods seems not useful to me. We could just leave it off, even if it then has the same name as `LintContext` methods.

**Comment by nnethercote** [comment]
> We could just leave it off, even if it then has the same name as LintContext methods.

That's exactly why I want a different name, because it has an extra argument. Different signature, different name.

**Review by compiler-errors — APPROVED** [review]
r=me after rebasing

**Comment by nnethercote** [comment]
I rebased.

@bors r=compiler-errors

**Comment by nnethercote** [comment]
I rebased again. Bumping priority because this is conflict-prone.

@bors r=oli-obk p=1

**Pull request merged**
