### PR TITLE
Stabilize slice patterns without `..`

### LINKED ISSUE #48836: Stabilize fixed-length slice patterns (excluding `..`)
This is a sub-issue of the larger tracking issue for slice patterns (https://github.com/rust-lang/rust/issues/23121). It specifically tracks the plans to stabilize **fixed-length slice patterns** -- that is, excluding the `..` operator (which is entangled with some syntactic questions). There is an implementation PR in https://github.com/rust-lang/rust/pull/48516.

### Summary

Using this feature, a pattern like `[a, b, c]` can be used to **match against fixed-length arrays**:

```rust
let arr = [1, 2, 3];
let [a, b, c] = arr; // where arr: [T;3]
let [a, ref b, c] = arr; // where arr: [T;3]
```

One can also use such a pattern to [**match against slices**](https://play.rust-lang.org/?gist=7ddd151b5806439cf563f82963153d4f&version=nightly):

```rust
let arr = &[1, 2];
match arr {
    [a, b, c] => { /* this arm will not apply */ }
    [a, b] => { /* this arm will */ }
    _ => { /* this wildcard is required, since we don't know length statically */
}
```

### Notable points and tests

Here are some of the things I think we should be testing. I didn't have time to find if we have all these tests, perhaps someone can help (cc @petrochenkov, @mikhail-m1 ?)

- test showing irrefutable matches (`let [a, b] = `) applied to fixed-length to move things out
- test showing irrefutable matches (`let [a, b] = `) applied to create reference
- test showing attempt to move from a borrowed array or slice gives error
    - [move-out-of-slice1.rs](https://github.com/rust-lang/rust/blob/5430c0c5c0fbdfb8e89358a187d2f9a8d4b796d4/src/test/compile-fail/move-out-of-slice-1.rs) sort of tests that, but for an oddly special case involving box patterns
- test that wildcard is required when matching slice with fixed-length arrays
- [`match-vec-fixed`](https://github.com/rust-lang/rust/blob/5430c0c5c0fbdfb8e89358a187d2f9a8d4b796d4/src/test/compile-fail/match-vec-fixed.rs) tests that we get warnings for two slice patterns of same length
- other cases?

### Things not stabilized

- The main thing not stabilized is the ability to create a slice of unmatched items.

### PR DESCRIPTION
**Pull request by petrochenkov**
And merge `feature(advanced_slice_patterns)` into `feature(slice_patterns)`.

The detailed description can be found in https://github.com/rust-lang/rust/issues/48836.

Slice patterns were unstable for long time since before 1.0 due to many bugs in the implementation, now this stabilization is possible primarily due to work of @arielb1 who [wrote the new MIR-based implementation of slice patterns](https://github.com/rust-lang/rust/pull/32202) and @mikhail-m1 who [fixed one remaining class of codegen issues](https://github.com/rust-lang/rust/pull/47926).

Reference PR https://github.com/rust-lang-nursery/reference/pull/259
cc https://github.com/rust-lang/rust/issues/23121
fixes #48836

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@petrochenkov needs rebase =)

**Comment by petrochenkov** [comment]
Rebased, doc PR is sent.

**Comment by nikomatsakis** [comment]
Blocked on the end of FCP for #48836

**Comment by nikomatsakis** [comment]
@petrochenkov FCP ended. r=me after rebase

**Pull request merged**
