### PR TITLE
[docs] Update references and borrowing (Fixes #29730)

### LINKED ISSUE #29730: this rustbook sentence is confusing (to me)
`If you are writing, you need two or more pointers to the same memory, and you can only have one &mut at a time.`
from: https://doc.rust-lang.org/nightly/book/references-and-borrowing.html#the-rules

### PR DESCRIPTION
**Pull request by norcalli**
Fixes #29730

### CODE REVIEW

**Comment by steveklabnik** [comment]
@bors: r+ rollup

thanks so much!

**Comment by norcalli** [comment]
lol how even does this fail. Is it the warnings that cause this? I've noticed that sometimes pull requests by people fail and you guys just retry. Is this something that would be worth taking a look at (by me)?

**Comment by steveklabnik** [comment]
@norcalli I think it's just a transient error

**Pull request merged**
