### PR TITLE
Shrink `Nonterminal`

### PR DESCRIPTION
**Pull request by nnethercote**
Small consistency and performance improvements.

r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
The `deep-vector` wins are real, I confirmed with DHAT. It produces lots of nonterminals because it contains a `vec![]` call with thousands of arguments.

I've pushed a new version of the code that is less invasive, it does the minimal thing for `NtStmt`. Hopefully that will give the memory reductions without as much other perf impact.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Some small but clear wins, definitely worth it for the small changes.

**Review by davidtwco — APPROVED** [review]

**Pull request merged**
