### PR TITLE
Make `Allocator` object-safe

### PR DESCRIPTION
**Pull request by RustyYato**
This allows rust-lang/wg-allocators#83: polymorphic allocators

### CODE REVIEW

**Comment by Amanieu** [comment]
Can you add a test to ensure that `Allocator` is object-safe?

**Comment by RustyYato** [comment]
Sure

**Comment by RustyYato** [comment]
@Amanieu Does that work?

**Comment by RustyYato** [comment]
@Amanieu All tests are passing, I'll squash all commits and then this should be good to go

**Pull request merged**
