### PR TITLE
add more Cortex-R targets

### PR DESCRIPTION
**Pull request by japaric**
This expands on PR #53663 to complete the set of Cortex-R targets and builds
rust-std components for them.

r? @alexcrichton

each extra rust-std component (there's 4 of them) takes about 3 minutes to build
on my local machine. In terms of stability (LLVM codegen bugs) these new targets
should be as stable as the Cortex-M ones (e.g. `thumbv7m-none-eabi`).

If the extra build time is too much we can leave the rust-std components out for
now

closes #53663
cc @paoloteti

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me! r=me with a `cc` bump for the most recent addition (and when y'all are comfortable w/ this )

**Comment by japaric** [comment]
@paoloteti @parched are you OK with landing this as it is?

**Comment by parched** [comment]
LGTM

**Comment by paoloteti** [comment]
LGTM and thanks for the extra patches

**Comment by kenkeiter** [comment]
@japaric @pablobm @alexcrichton @parched Thanks for making this happen! 🎊

**Comment by japaric** [comment]
Rebased

@bors r=alexcrichton

**Pull request merged**
