### PR TITLE
Update E0428 to new format

### LINKED ISSUE #35798: E0428 needs to be updated to new format
From: src/test/compile-fail/E0428.rs

E0428 needs a span_label, updating it from:

```
error[E0428]: a type named `Bar` has already been defined in this module
  --> src/test/compile-fail/E0428.rs:12:1
   |
11 | struct Bar;
   | ----------- previous definition of `Bar` here
12 | struct Bar; //~ ERROR E0428
   | ^^^^^^^^^^^
```

To:

```
error[E0428]: a type named `Bar` has already been defined in this module
  --> src/test/compile-fail/E0428.rs:12:1
   |
11 | struct Bar;
   | ----------- previous definition of `Bar` here
12 | struct Bar; //~ ERROR E0428
   | ^^^^^^^^^^^ already defined
```

### PR DESCRIPTION
**Pull request by trixnz**
Fixes #35798 as part of #35233.

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good!

@bors r+ rollup

**Comment by jonathandturner** [comment]
@bors r-

Looks like there are a couple more tests to update:

```

failures:
    [compile-fail] compile-fail\enum-and-module-in-same-scope.rs
    [compile-fail] compile-fail\issue-21546.rs
    [compile-fail] compile-fail\trait-duplicate-methods.rs

test result: FAILED. 2490 passed; 3 failed; 20 ignored; 0 measured
```

You should be able to check these with (possibly changing stage to 2 if this doesn't catch it):

```
python src/bootstrap/bootstrap.py --step check-cfail --stage 1
```

**Comment by trixnz** [comment]
Looks like I was a little overzealous :smile:. Should be fixed now.

**Comment by jonathandturner** [comment]
Thanks!

@bors r+ rollup

**Pull request merged**
