### PR TITLE
rename assert_matches module

### PR DESCRIPTION
**Pull request by yaahc**
Fixes nightly breakage introduced in https://github.com/rust-lang/rust/pull/86947

### CODE REVIEW

**Comment by oli-obk** [comment]
r=me with ui tests fixed

**Comment by Mark-Simulacrum** [comment]
Unilaterally beta-nominating and accepting; this is presumably just as necessary as #87195 on beta.

**Comment by richkadel** [comment]
Thanks! This fixed #87189 and all of the compiler errors I was seeing.

**Pull request merged**
