### PR TITLE
Fix `ui/io-checks/inaccessbile-temp-dir.rs` test

### LINKED ISSUE #110794: `tests/ui/io-checks` fail locally on master
The `tests/ui/io-checks/inaccessbile-temp-dir.rs` test fails for me locally on the master branch (and was failing for a while now). I can of course ignore it, but it's annoying. `tests/ui/io-checks/non-ice-error-on-worker-io-fail.rs` also fails if run after/with `inaccessbile-temp-dir.rs`.

It looks like `inaccessbile-temp-dir.rs` successfully creates a temp directory even if it's parent does not exist:

<details><summary>output</summary>
<p>

```
:~/rust-b (master); git log -1 --oneline
91b61a4ad61 (HEAD -> master, upstream/master) Auto merge of #110389 - mazong1123:add-shortcut-for-grisu3, r=Mark-Simulacrum
:~/rust-b (master); ls /does-not-exist
ls: cannot access '/does-not-exist': No such file or directory
:~/rust-b (master) [2]; x t tests/ui/io-checks/inaccessbile-temp-dir.rs
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.06s
Building stage0 library artifacts (aarch64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.18s
Building compiler artifacts (stage0 -> stage1, aarch64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.29s
Assembling stage1 compiler
Building stage1 library artifacts (aarch64-unknown-linux-gnu)
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished release [optimized + debuginfo] target(s) in 0.21s
Building stage0 tool compiletest (aarch64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.19s
Check compiletest suite=ui mode=ui (aarch64-unknown-linux-gnu -> aarch64-unknown-linux-gnu)

running 1 tests
F

failures:

---- [ui] tests/ui/io-checks/inaccessbile-temp-dir.rs stdout ----

error: ui test compiled successfully!
status: exit status: 0
command: "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/stage1/bin/rustc" "/home/gh-WaffleLapkin/rust-b/tests/ui/io-checks/inaccessbile-temp-dir.rs" "-Zthreads=1" "--sysroot" "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/stage1" "--target=aarch64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/test/ui/io-checks/inaccessbile-temp-dir" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/test/ui/io-checks/inaccessbile-temp-dir/auxiliary" "-Z" "temps-dir=/does-not-exist/output"
stdout: none
stderr: none



failures:
    [ui] tests/ui/io-checks/inaccessbile-temp-dir.rs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 14869 filtered out; finished in 60.70ms

Some tests failed in compiletest suite=ui mode=ui host=aarch64-unknown-linux-gnu target=aarch64-unknown-linux-gnu
Build completed unsuccessfully in 0:00:03
:~/rust-b (master) [1]; ls /does-not-exist
output
:~/rust-b (master); 
```

</p>
</details>

This causes the failure (as the test is expected to not compile) and also creates the directory, which `non-ice-error-on-worker-io-fail.rs` then observes and also fails.

This happens for me on the [`dev-desktop-eu-1`](https://forge.rust-lang.org/infra/docs/dev-desktop.html).

cc @fee1-dead iirc you had the same problems
cc @cuviper you changed those tests at some point, so maybe you know something

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Fixes #110794

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
> It's worth noting that a similar `non-ice-error-on-worker-io-fail.rs` is actually fine as is, since `-o` doesn't use `create_dir_all` or alike and actually always fails on `/does-not-exist/output` (although now that I said it... do we need to change this to a local path?...)

I think this would be nice but not necessary, since it's not failing spuriously anywhere.

**Review by jyn514 — APPROVED** [review]
Thanks! r=me with the nit fixed

**Comment by WaffleLapkin** [comment]
@jyn514 would `-o ./does-not-exist/output` work, or would this require something else?

**Comment by jyn514** [comment]
@WaffleLapkin that would work for a UI test I think, yes. not 100% sure without trying it.

**Comment by matthiaskrgr** [comment]
@bors r- 
https://github.com/rust-lang/rust/pull/110818#issuecomment-1522269456

**Comment by WaffleLapkin** [comment]
@bors r=jyn514 rollup=never

I suspect there might be more CI issues so let's not rollup

**Pull request merged**
