### PR TITLE
[experiment] use unreachable_unchecked() everywhere

### PR DESCRIPTION
**Pull request by ljedrz**
This is an experimental commit designed to measure if changing `unreachable!()` to its faster unsafe counterpart can result in measurable performance gains (see #52945).

We don't want to perform this change everywhere, only consider it in hot spots under infallible conditions. With any luck a perf run could point us into the right direction; this approach has worked with `assert!` (#53025).

cc @dtolnay

### CODE REVIEW

**Comment by BurntPizza** [comment]
I feel like if this looks to be a good idea then in the hotspots we should still have a debug fallback:  
 
```
#[cfg(debug_assertions)]
macro_rules! unreachable_unchecked {
    () => { unreachable!(); };
}
#[cfg(not(debug_assertions))]
macro_rules! unreachable_unchecked {
    () => { ::core::hint::unreachable_unchecked(); };
}
```
  
You could probably instead just have this in scope where you want it, do reduce the diff, but that's probably an unnecessary amount of non-local effect:
```
#[cfg(not(debug_assertions))]
macro_rules! unreachable {
    () => { unsafe { ::core::hint::unreachable_unchecked() } };
}
```  
  
Can you override `std` macros?

**Comment by petrochenkov** [comment]
@ljedrz 
You should be able to "bors try" now after CI is green.

**Comment by ljedrz** [comment]
@petrochenkov thanks; I'd run all the tests on my own, but unfortunately on Windoze I can only get to `stage 1`-level `debuginfo`, which always fail with spurious errors like:
```
Warning: /c/Rust/GitHub/rust-lang/c: No such file or directory.
Warning: /c/Rust/GitHub/rust-lang/RustGitHubrust-lang./src/etc: No such file or directory.
C:\Rust\GitHub\rust-lang\build\x86_64-pc-windows-gnu\test\debuginfo\unsized\unsized.debugger.script:9: Error in sourced command file:
No symbol "a" in current context.
Failed to resume program execution (ContinueDebugEvent failed, error 87)
```
And the mudule-level tests are performed only after those; do you know if there is any way I can fix these issues or reorder tests so that `debuginfo` ones are performed at the very end?

**Comment by petrochenkov** [comment]
@ljedrz 
>do you know if there is any way I can fix these issues, skip debuginfo or at least reorder tests so that debuginfo ones are performed at the very end?

You can disable the debuginfo test suite by comment it out in this list https://github.com/rust-lang/rust/blob/master/src/bootstrap/builder.rs#L377-L429

**Comment by ljedrz** [comment]
@petrochenkov thanks, that allowed me to go a lot further; I'm still getting some spurious-looking errors by the end, but hopefully I've covered all the issues by now.

**Comment by ljedrz** [comment]
@rust-timer build https://github.com/rust-lang/rust/commit/17a91f559ea8afdd4b2413b71b21348f4fe80286

**Comment by ljedrz** [comment]
@petrochenkov I guess delegating doesn't extend to perf runs; can you help here?

**Comment by ishitatsuyuki** [comment]
cc @Mark-Simulacrum @kennytm

**Comment by kennytm** [comment]
@rust-timer build 17a91f559ea8afdd4b2413b71b21348f4fe80286

**Comment by BurntPizza** [comment]
Not much effect.

**Comment by dtolnay** [comment]
Well that's fantastic news right? That means we get to keep the checked unreachables without leaving performance on the table.

**Comment by ljedrz** [comment]
Yeah, it looks like there isn't much to gain here; I think we can close it along with the related issue.

**Pull request closed without merging**
