### PR TITLE
Fix cargotest

### PR DESCRIPTION
**Pull request by brson**
Tested in dev.

### CODE REVIEW

**Comment by brson** [comment]
@alexcrichton re-r? I made cargotest depend on librustctest because cargo's test suite is looking for librustc_plugins. I swear this is the secret ingredient that will make it all work. Untested ;)

**Comment by alexcrichton** [comment]
Oh right yeah we have some tests that exercise plugins. This means we can't submit a breaking change to plugins without changing upstream Cargo but... I guess that's not too bad?

@bors: r+

**Comment by alexcrichton** [comment]
Everything passed except android which disappeared again unfortunately, so merging manually.

**Pull request merged**
