### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #72456 (Try to suggest dereferences on trait selection failed)
 - #72788 (Projection bound validation)
 - #72790 (core/time: Add Duration methods for zero)
 - #73227 (Allow multiple `asm!` options groups and report an error on duplicate options)
 - #73287 (lint: normalize projections using opaque types)
 - #73291 (Pre-compute `LocalDefId` <-> `HirId` mappings and remove `NodeId` <-> `HirId` conversion APIs)
 - #73378 (Remove use of specialization from librustc_arena)
 - #73411 (Update bootstrap to rustc 1.45.0-beta.2 (1dc0f6d8e 2020-06-15))
 - #73443 (ci: allow gating GHA on everything but macOS)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+ p=8 rollup=never

To run after https://github.com/rust-lang/rust/pull/73550

Once this goes through CI we should perhaps wait a bit and let the rollup=nevers flush through

**Comment by panstromek** [comment]
Something in this rollup is a perf win ;)

https://perf.rust-lang.org/compare.html?start=f455e46eae1a227d735091091144601b467e1565&end=7058471adec80a2a1e6092443e08546768c9c894&stat=instructions:u

**Comment by Manishearth** [comment]
Presumably https://github.com/rust-lang/rust/pull/73291 cc @marmeladema

**Comment by marmeladema** [comment]
Hu great! I did not anticipate that! Would it be valuable to do a fake revert and run the perf tests to  confirm?

**Comment by marmeladema** [comment]
Memory also reduced a bit: https://perf.rust-lang.org/compare.html?start=f455e46eae1a227d735091091144601b467e1565&end=7058471adec80a2a1e6092443e08546768c9c894&stat=max-rss

**Comment by matthewjasper** [comment]
#72788 looks like it was a lot of the perf gains here from local testing

**Pull request merged**
