### PR TITLE
Do not capture stderr in the compiler. Instead just panic silently for fatal errors

### PR DESCRIPTION
**Pull request by Zoxc**
This also has the side-effect of making printing to stderr work in the compiler.

### CODE REVIEW

**Comment by devurandom** [comment]
This might somewhat fix #43855 and #44244

**Comment by alexcrichton** [comment]
@bors: r+

Thanks!

**Comment by dtolnay** [comment]
Is there a chance that this PR would have changed the error message when a custom derive panics? #47812

**Pull request merged**
