### PR TITLE
std: Fix tracking issues and clean deprecated APIs

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR fixes up a number of discrepancies found with tracking issues (some closed, some needed new ones, etc), and also cleans out all pre-1.8 deprecated APIs. The big beast here was dealing with `std::dynamic_lib`, and via many applications of a large hammer it's now out of the standard library.

### CODE REVIEW

**Comment by aturon** [comment]
r=me, very nice.

**Comment by sfackler** [comment]
Travis is unhappy: https://travis-ci.org/rust-lang/rust/builds/115483851#L1725

**Comment by Manishearth** [comment]
```
../src/libstd\sys/unix\net.rs:24:1: 24:31 warning: `pub extern crate` does not work as expected and should not be used. Likely to become an error. Prefer `extern crate` and `pub use`.
../src/libstd\sys/unix\net.rs:24 pub extern crate libc as netc;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/libstd\sys/windows\handle.rs:138:48: 138:56 error: unresolved name `c::FALSE` [E0425]
../src/libstd\sys/windows\handle.rs:138             let wait = if wait {c::TRUE} else {c::FALSE};
                                                                                       ^~~~~~~~
../src/libstd\sys/windows\handle.rs:138:48: 138:56 help: run `rustc --explain E0425` to see a detailed explanation
../src/libstd\sys/windows\pipe.rs:143:57: 143:65 error: unresolved name `c::FALSE` [E0425]
../src/libstd\sys/windows\pipe.rs:143             c::WaitForMultipleObjects(2, objs.as_ptr(), c::FALSE, c::INFINITE)
                                                                                              ^~~~~~~~
../src/libstd\sys/windows\pipe.rs:143:57: 143:65 help: run `rustc --explain E0425` to see a detailed explanation
```

**Pull request merged**
