### PR TITLE
fix span for errors E0537, E0535 & E0536

### LINKED ISSUE #36182: E0537 has a span with extra characters
```
error[E0537]: invalid predicate `unknown`
  --> src/test/compile-fail/E0537.rs:11:7
   |
11 | #[cfg(unknown())] //~ ERROR E0537
   |       ^^^^^^^^^^
```

Currently, we underline a little too much of the predicate.  Notice that we underline two `)` instead of just the matching `)`

I noticed that E0535 and E0536 also have the same problem

### PR DESCRIPTION
**Pull request by mikhail-m1**
fix #36182 as part of #35233

### CODE REVIEW

**Comment by jonathandturner** [comment]
@mikhail-m1 - since you're fixing spans, can you move some of the tests you're updating to src/test/ui?  You can look around there to see how it works, but it's pretty simple.  There's a corresponding .stderr for each test that matches with what the compiler would output.

You can run the UI tests with:

```
python src/bootstrap/bootstrap.py --step check-ui --stage 1
```

**Comment by mikhail-m1** [comment]
@jonathandturner I'll fix it

**Comment by jonathandturner** [comment]
Great!  Looks good.

@bors r+ rollup

**Pull request merged**
