### PR TITLE
Rollup of 4 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #112717 (Implement a few more rvalue translation to smir)
 - #113310 (Don't suggest `impl Trait` in path position)
 - #113497 (Support explicit 32-bit MIPS ABI for the synthetic object)
 - #113560 (Lint against misplaced where-clauses on associated types in traits)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=112717,113310,113497,113560)

### CODE REVIEW

**Comment by fmease** [comment]
That CI failure is unrelated & non-deterministic. See also https://github.com/rust-lang/rust/pull/113515#issuecomment-1627867296. You should be able to just retry.

**Comment by matthiaskrgr** [comment]
:|
@bors retry

**Comment by matthiaskrgr** [comment]
oh nevermind it was just the pre-merge ci xD

**Pull request merged**
