### PR TITLE
[WIP] Make Parser operate on 'flattened' `TokenStream`

### PR DESCRIPTION
**Pull request by Aaron1011**
This makes cloning a `Parser` cheaper, and greatly reducces the amount
of state that `collect_tokens_trailing_token` needs to save.

### CODE REVIEW

**Comment by Aaron1011** [comment]
The cost of flattening and allocating a new `Vec` appears to outweigh any savings during parsing. We could try to avoid constructing a `TokenStream` when we load a file from disk, but we can't avoid constructing a `TokenStream` when proc-macros are involved.

**Comment by petrochenkov** [comment]
Well, if conversions to regular non-flat token streams to/from macros outweigh the gains, then so be it.
IIRC, the token collection PR already got to under 1% regressions without changing the parser's cursor internals.

I'm pretty happy about this outcome, it would be good to work entirely in terms regular token streams, and forget about flat tokens immediately after lexer.

**Comment by petrochenkov** [comment]
Should I close this PR?

**Comment by Aaron1011** [comment]
> IIRC, the token collection PR already got to under 1% regressions without changing the parser's cursor internals.

After I did that perf run, I uncovered some bugs that will require additional refactoring to token collection. I'm not yet sure how much more complexity will need to be added, or what the performance impact will be.

**Comment by Aaron1011** [comment]
I ended up taking a different approach, so this PR is no longer needed.

**Pull request closed without merging**
