### PR TITLE
rustdoc: use Type::def_id() instead of Type::def_id_no_primitives()

### PR DESCRIPTION
**Pull request by mfrw**
For: #90187

r? @jyn514

### CODE REVIEW

**Comment by camelid** [comment]
Hmm, somehow this makes generics show up in search results (that's why the test is failing AFAICT). I don't think that's supposed to happen; otherwise searching for `T` would return a *lot* of results. cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Indeed, for the search index, we don't want to keep generics as is. It can be fixed by turning the `cache` argument into an `Option` and passing `None` when using it for the search index.

**Comment by camelid** [comment]
> Indeed, for the search index, we don't want to keep generics as is. It can be fixed by turning the `cache` argument into an `Option` and passing `None` when using it for the search index.

But why does switching to `def_id` from `def_id_no_primitives` affect whether generics show up in the search results? They're not primitives...

**Comment by GuillaumeGomez** [comment]
I'll test locally tomorrow to see what's going on because from what I can see, the code is perfectly valid. You have allowed to uncover a bug in rustdoc. (yeay! :partying_face: :tada: )

**Comment by mfrw** [comment]
> I'll test locally tomorrow to see what's going on because from what I can see, the code is perfectly valid. You have allowed to uncover a bug in rustdoc. (yeay! 🥳 🎉 )

Yayay .. I am noob and I only could stare at the code and now was reading more about rust if i was missing something trivial. 
ALso while we are here, what is the guidance on removing this when we are implementing a trait like [this](https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/stripper.rs#L130). It seems it does not have access to the `Cache` directly.

**Comment by camelid** [comment]
>  ALso while we are here, what is the guidance on removing this when we are implementing a trait like [this](https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/stripper.rs#L130). It seems it does not have access to the `Cache` directly.

You should be able to add a `cache: &'a Cache` field to the struct that the trait is being implemented on. I'm in the process of adding Cache fields to all those places already, so you could also just skip that usage for now.

**Comment by GuillaumeGomez** [comment]
Sorry, I was focused on other things and completely forgot about this. Scheduling it for tomorrow.

**Comment by mfrw** [comment]
> You should be able to add a `cache: &'a Cache` field to the struct that the trait is being implemented on. I'm in the process of adding Cache fields to all those places already, so you could also just skip that usage for now.

Since you adding Cache fields, should I wait and then update the PR. @camelid

**Comment by camelid** [comment]
> > You should be able to add a `cache: &'a Cache` field to the struct that the trait is being implemented on. I'm in the process of adding Cache fields to all those places already, so you could also just skip that usage for now.
> 
> Since you adding Cache fields, should I wait and then update the PR. @camelid

That work is blocked for now, so feel free to add the fields yourself if you can.

**Comment by GuillaumeGomez** [comment]
I found where the issue was coming from: https://github.com/rust-lang/rust/pull/90726. I'm just very surprised we didn't find it out sooner. Well, I'm quite happy you uncovered it because thanks to you, it allowed to fix this issue and helped me uncover another one: https://github.com/rust-lang/rust/pull/90727. So thanks! :)

**Comment by mfrw** [comment]
> I found where the issue was coming from: #90726. I'm just very surprised we didn't find it out sooner. Well, I'm quite happy you uncovered it because thanks to you, it allowed to fix this issue and helped me uncover another one: #90727. So thanks! :)

Happy to be of any help, even though I am a complete noob. Thank you all for being welcoming!

**Comment by GuillaumeGomez** [comment]
We all started in your position, so we know it's nice to have help. So anyway, once #90726 is merged, just rebase on it and that should work just fine.

**Comment by GuillaumeGomez** [comment]
@mfrw: The fix in #90726 is invalid. So to fix the issue, you'll need to check that the returned type isn't a `Primitive::Reference` in `render/cache.rs`.

Unless you have a better idea @jyn514 @camelid ?

**Comment by camelid** [comment]
> @mfrw: The fix in #90726 is invalid. So to fix the issue, you'll need to check that the returned type isn't a `Primitive::Reference` in `render/cache.rs`.
> 
> Unless you have a better idea @jyn514 @camelid ?

Another option is to not change the problem `def_id_no_primitive` call for now, to avoid blocking the rest of this PR. Then a followup PR could focus on just that use.

**Comment by GuillaumeGomez** [comment]
@camelid This is a good suggestion! If so, please someone open an issue as always so we don't forget. :)

**Comment by mfrw** [comment]
> > @mfrw: The fix in #90726 is invalid. So to fix the issue, you'll need to check that the returned type isn't a `Primitive::Reference` in `render/cache.rs`.
> > Unless you have a better idea @jyn514 @camelid ?
> 
> Another option is to not change the problem `def_id_no_primitive` call for now, to avoid blocking the rest of this PR. Then a followup PR could focus on just that use.

I followed this approach. Should I create an issue for the cleanup of the remaining `def_id_no_primitive` in `render/cache.rs` ?

**Comment by jyn514** [comment]
I don't think this needs a new issue, just leave https://github.com/rust-lang/rust/issues/90187 open :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by GuillaumeGomez** [comment]
Spurious error.

@bors: retry

**Comment by GuillaumeGomez** [comment]
I think CI is broken. cc @rust-lang/infra

**Pull request merged**
