### PR TITLE
[beta] backport fix for #40951

### PR DESCRIPTION
**Pull request by nikomatsakis**
cc @arielb1 -- this is a backport of just the fix needed for #40951. Thoughts?

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @brson @alexcrichton

**Comment by arielb1** [comment]
This feels a little risky to me - who knows if this can trigger another (performance or functionality) edge case. How bad is #40951? It looks like most of the #40319 regressions are either "bad annotation" or "NLL".

**Comment by alexcrichton** [comment]
r=me if the compiler team is good with this

**Comment by nikomatsakis** [comment]
@arielb1 

> This feels a little risky to me - who knows if this can trigger another (performance or functionality) edge case.

I also have mixed feelings.

**Comment by nikomatsakis** [comment]
We discussed this in the @rust-lang/compiler meeting and decided **not** to backport. This change is a bit more complex than we are comfortable with, and the fallout seems quite minimal. The regression *is* fixed on nightly.

**Pull request closed without merging**
