### PR TITLE
rustfmt librustc_front

### PR DESCRIPTION
**Pull request by nrc**

### CODE REVIEW

**Comment by jdm** [comment]
https://github.com/rust-lang/rust/pull/28697/files?w=1 is a lot nicer to read than the default "Files changed" view.

**Comment by nrc** [comment]
Because the where clause is indented from the left + 4 which is the same indent as the body, without the newline brace it's hard to see where the signature ends and the body begins. Aligning the where clause with the arguments tends to overflow too often.

**Pull request merged**
