### PR TITLE
Add docs for sort_unstable to unstable book

### PR DESCRIPTION
**Pull request by ghost**
Tracking issue for the feature: #40585 

r? @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Looks awesome, thanks!

@bors: r+ rollup

**Comment by stjepang** [comment]
Ah, didn't notice that the feature has to be merged first :)
We'll have to wait for #40601 before the build passes.

**Comment by stjepang** [comment]
@frewsxcv  Rebased onto master, this PR will pass the tests now. Can you r+ please?

**Pull request merged**
