### PR TITLE
Always pass `/DEBUG` flag to MSVC linker

### LINKED ISSUE #28448: Always pass /DEBUG to msvc linker
From convo with @retep998, passing /DEBUG, even w/o emitting debuginfo, makes backtraces work. They 'see no reason' not to always pass this flag.

This should be a simple change to `rustc::back::link`.

### PR DESCRIPTION
**Pull request by apasel422**
Closes #28448.

r? @brson

### CODE REVIEW

**Comment by apasel422** [comment]
This is pending discussion on the referenced issue.

**Comment by alexcrichton** [comment]
I'm ok with this as it seems the only downside is an extra file is generated, but that already happens for dylibs and it's not necessarily harming anyone either! I'm also not too too worried about having a switch to *not* pass this flag as it doesn't seem too crucial.

Thoughts @brson?

**Comment by brson** [comment]
Still waiting for some more [discussion](https://github.com/rust-lang/rust/issues/28448#issuecomment-142093896).

**Comment by brson** [comment]
With the dsymutil precedent I'm mildly ok with having pdbs just silently emitted.

**Comment by apasel422** [comment]
Looks like @bors is stuck?

**Comment by retep998** [comment]
It looks like the android bot didn't start for whatever reason.

**Pull request merged**
