### PR TITLE
[experiment] ty/layout: compute both niche-filling and tagged layouts for enums.

### PR DESCRIPTION
**Pull request by eddyb**
This is something I've wanted to do for a while, since if we can get away with it perf-wise, it should allow us to always pick the better of the two, even when the conditions would be otherwise subtle.

### CODE REVIEW

**Comment by bjorn3** [comment]
There doesn't seem to be any perf difference between master and this PR.

**Comment by RalfJung** [comment]
I'm afraid I don't know this code nearly well enough to do reviews. I'd have suggested @eddyb until I saw they are the PR author. ;)

**Comment by eddyb** [comment]
This is only for the perf test :chart_with_upwards_trend:. If we did land this, we'd add a comparison between the two layouts, and pick the one that has smaller size, or more invalid values in the `largest_niche` (if they're the same size) - if somehow both of those properties are identical, we'd pick tagged because LLVM will likely handle it better.

**Comment by RalfJung** [comment]
Assigning to @eddyb as it is just an experiment. r? @eddyb

**Comment by eddyb** [comment]
Thanks to @erikdesjardins, this was finished as #74069.

**Pull request closed without merging**
