### PR TITLE
[beta] Branch 1.60 beta

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
nightly_only_test here seems likely to be a little problematic for the future -- probably needs to be revised to avoid fully cfg'ing away the test but rather to mark it as ignore or something like that, at least.

**Comment by pietroalbini** [comment]
> nightly_only_test here seems likely to be a little problematic for the future -- probably needs to be revised to avoid fully cfg'ing away the test but rather to mark it as ignore or something like that, at least.

Hmm, how was that not catched by the stable builder?

**Comment by Mark-Simulacrum** [comment]
> > nightly_only_test here seems likely to be a little problematic for the future -- probably needs to be revised to avoid fully cfg'ing away the test but rather to mark it as ignore or something like that, at least.
> 
> Hmm, how was that not catched by the stable builder?

rustfmt isn't tested/built on the stable builder, since it's a tool and those aren't checked by x86_64-gnu (the 'template' the stable builder uses).

**Comment by Mark-Simulacrum** [comment]
Filed https://github.com/racer-rust/racer/pull/1177 to fix racer builds (will need a cargo update at minimum) on parallel rustc, but will try to push up a temporary disable of RLS builds for alt.

**Comment by calebcartwright** [comment]
> nightly_only_test here seems likely to be a little problematic for the future -- probably needs to be revised to avoid fully cfg'ing away the test but rather to mark it as ignore or something like that, at least.

happy to chat about this offline to get a better understanding of the concern. i'm a bit puzzled by the failure at first blush because I thought we had sufficiently tricked one matrix of our own CI to think the tests were being executed in a non-nightly, and would've expected this to fail there.

apologies!

**Comment by Mark-Simulacrum** [comment]
@bors retry 
The hosted runner: GitHub Actions 3 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

**Pull request merged**
