### PR TITLE
tests: Require run-pass tests without annotations to run successfully again

### LINKED ISSUE #62775: test cases under run-pass directory are not running
With the change in function  should_run_successfully() of commit 54337fab39f4c610bd5e5c51cea6a965e7bd7cdb:
         - RunPass => true,
         -  Ui => self.props.pass_mode == Some(PassMode::Run),
         +  RunPass | Ui => self.effective_pass_mode() == Some(PassMode::Run),

The test cases under run-pass directory are tested for building only, the compiled test cases are not running any more.
Does it work as design?

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/62775 (regression from https://github.com/rust-lang/rust/pull/61755)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors rollup=never

Presumably we may have introduced regressions since then.

**Comment by petrochenkov** [comment]
One test regressed (cannot run a library).
I haven't run fulldeps tests though.

@bors r=Mark-Simulacrum

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/issues/62807 filed.

@bors r=Mark-Simulacrum

**Comment by petrochenkov** [comment]
Ok, apparently `ignore-wasm` doesn't work, only `ignore-wasm32` does.
@bors r=Mark-Simulacrum

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/issues/62820 filed.
@bors r=Mark-Simulacrum

**Comment by Centril** [comment]
@bors p=1000

(Really the tree should have been closed to land this!)

Thanks @petrochenkov for staying on top of this <3.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/issues/62844 filed.
@bors r=Mark-Simulacrum

We probably need a "when testing on one agent fails, don't cancel others" mode for this kind of work.

**Comment by Centril** [comment]
@bors treeclosed=1500

Closing the tree until this is merged.

**Comment by matthiaskrgr** [comment]
@Centril  this has priority 1000 but tree was closed for everything under priority 1500

**Comment by Centril** [comment]
@matthiaskrgr Yeah that's intentional; This must be merged before anything other than CI fixes lands on nightly but we can do beta rollups and whatnot between that in case Pietro is awake.

**Comment by matthiaskrgr** [comment]
I mean, it is not being tested because priority needs to be `above` treeclosed limit I think?
https://buildbot2.rust-lang.org/homu/queue/rust

**Comment by petrochenkov** [comment]
One more test added to https://github.com/rust-lang/rust/issues/62844.
@bors r=Mark-Simulacrum

**Pull request merged**
