### PR TITLE
Fix race condition when emitting stored diagnostics

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Can you explain to me how this is racy? Loaded diagnostics are only emitted by the thread that actually allocates the dep-node and that is already synchronized.

**Comment by Zoxc** [comment]
`try_mark_green` is expected to emit diagnostics before returning, but that only happens if we are on the thread which did the dep-node allocation. Other threads may continue executing and emit their own diagnostics before the thread which did the dep-node allocation, giving a wrong order to the emitted diagnostics.

**Comment by michaelwoerister** [comment]
Yeah, true. However, I'm not sure how much we can avoid diagnostics re-ordering in general with parallel queries. Or, put differently, we'll have to put some machinery in place to make things more deterministic and that might (1) clash with this incr.comp. specific approach and (2) it might handle this case with the extra logic. 
I'd opt for putting this on hold until we figure out the concurrency&diagnostics story more generally.

**Comment by TimNN** [comment]
Ping from triage @Zoxc / @michaelwoerister: What is the status of this PR? Is it blocked on something for the foreseeable future?

**Comment by michaelwoerister** [comment]
I'm actually fine with merging it the way it is. The code will probably change in the medium term but it doesn't hurt to have this behaving correctly in the meantime.

r=me with the conflicts resolved.

**Comment by Centril** [comment]
@bors retry

yielding prio to PR in which this is included.

**Pull request merged**
