### PR TITLE
Update rustc-guide

### PR DESCRIPTION
**Pull request by mark-i-m**
Should fix toolstate failure

r? @ehuss

### CODE REVIEW

**Comment by ehuss** [comment]
> Error: there are broken links
>    Caused By: There was an error while fetching "http://octarineparrot.com/assets/mrfloya-thesis-ba.pdf", https://octarineparrot.com/assets/mrfloya-thesis-ba.pdf: error trying to connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264: (certificate has expired)
 >   Caused By: There was an error while fetching "https://octarineparrot.com/assets/msci_paper.pdf", https://octarineparrot.com/assets/msci_paper.pdf: error trying to connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264: (certificate has expired)

**Comment by mark-i-m** [comment]
The above also has the following:

`
2019-08-19T18:25:44.8638593Z error: process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/client-4789b7d22e4fb0f9` (signal: 4, SIGILL: illegal instruction)`

which is not comforting...

**Comment by ehuss** [comment]
sigill is normal for a panic-while-panicking.  The rls client tests tend to be a little flaky.  cc @Xanewok, not sure if you've seen this error before.  I would guess that the [RlsHandle::drop](https://github.com/rust-lang/rls/blame/7dd4d819281e0e2dc03081d95b09bb610fade0ab/tests/support/client/mod.rs#L272-L284) is the cause of the second panic, though I can't really infer what caused the initial panic.  I wish tests were run with RUST_BACKTRACE set.

**Comment by mark-i-m** [comment]
Hopefully, should be fixed now.

**Pull request merged**
