### PR TITLE
Tweak `FulfillProcessor`.

### PR DESCRIPTION
**Pull request by nnethercote**
Avoids some unnecessary references and lifetimes.

r? @jackh726

### CODE REVIEW

**Comment by nnethercote** [comment]
This code is very perf-sensitive, let's see what happens on CI.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
`keccak` has been noisy lately, let's try again.

@bors try @rust-timer queue

**Comment by jackh726** [comment]
r=me when you're happy with perf

**Comment by nnethercote** [comment]
`keccak` improved in one, regressed in the other, I think this is just noise.

@bors r=jackh726 rollup=always

**Pull request merged**
