### PR TITLE
remove intercrate ambiguity hints

### PR DESCRIPTION
**Pull request by nikomatsakis**
The scheme was causing overflows during coherence checking (e.g. #47139). This is sort of a temporary fix; the proper fix I think involves reworking trait selection in deeper ways.

cc @sgrif -- this *should* fix diesel

cc @qnighy -- I'd like to discuss you with alternative techniques for achieving the same end. =) Actually, it might be good to put some energy into refactoring traits first.

r? @eddyb

### CODE REVIEW

**Comment by nikomatsakis** [comment]
er, oops -- let me add a test!

**Comment by nikomatsakis** [comment]
I actually have to figure out how to formulate one. The test I have which reproduces diesel's problem isn't, I think, affected by this change.

**Comment by nikomatsakis** [comment]
(Also, the problem was sort of order dependent, but I might be able to fix that.)

**Comment by eddyb** [comment]
r=me

**Comment by nikomatsakis** [comment]
ok, added a test that fails on beta/nightly and which I believe is representative of the diesel error

**Comment by qnighy** [comment]
@nikomatsakis oh bad 😞 Anyway I'm interested in both refactoring trait selection and reintroducing the hints. It may take time for me to remember things around trait selection though...

**Comment by qnighy** [comment]
For reference: the PR that introduced the hints is #43426

**Comment by arielb1** [comment]
I can't say I like this fix - this regresses from beta because it removes the coherence problem detection feature.

Maybe we should just disable intercrate ambiguity hints "initially", and then call trait selection again with them *enabled* only if there was a coherence error.

That way the error detection code will not be called unless there is an actual coherence error, in which case we don't care as much if there is an overflow.

**Comment by nikomatsakis** [comment]
It is a brute force fix, that's true. Doing it in two passes is a decent idea.

**Comment by arielb1** [comment]
r=me with the two-pass thing

**Comment by nikomatsakis** [comment]
I did the two-pass change but for .. some reason I do not know I am not getting the full range of hints yet. I'll debug in a bit, but pushing intermediate status.

**Comment by arielb1** [comment]
A squash would be nice.

**Comment by arielb1** [comment]
@nikomatsakis 

The missing errors might be caused by the infcx `evaluation_cache` caching the evaluations, so that the selection context does not go through evaluating these predicates again.

The reason this worked before is because intercrate mode only uses the per-infcx evaluation cache:
https://github.com/rust-lang/rust/blob/6b99adeb11313197f409b4f7c4083c2ceca8a4fe/src/librustc/traits/select.rs#L1249-L1277

And coherence uses a fresh inference context for each overlap check, starting with an empty evaluation cache:
https://github.com/rust-lang/rust/blob/master/src/librustc/traits/specialize/specialization_graph.rs#L135-L140

To fix this, I think the best way would be to create a fresh inference context for the "error reporting" check.

**Comment by nikomatsakis** [comment]
@arielb1 ok, cleaned up, take a look -- running full tests now but seems to work

**Comment by nikomatsakis** [comment]
@arielb1 -- think you'll be able to review this soon? I'd really like to get Diesel unblocked.

**Comment by sgrif** [comment]
I can confirm that this PR fixes Diesel's build

**Comment by sgrif** [comment]
It doesn't look like bors recognized the retry request

**Comment by nikomatsakis** [comment]
https://travis-ci.org/rust-lang/rust/jobs/335887927#L1 ... spurious?

**Pull request merged**
