### PR TITLE
rustdoc: do not mark the contents of a skipped module as inlined

### LINKED ISSUE #100204: Docs regression on crate teloxide-0.10.1
# Behavior, describe in zulip thread

https://docs.rs/teloxide/0.10.1/teloxide/struct.Bot.html has an inherent impl block, but it is not shown. https://docs.rs/teloxide/0.10.0/teloxide/struct.Bot.html (which was built with an earlier version of rustdoc) shows it.

# Regression information

searched nightlies: from nightly-2022-08-03 to nightly-2022-08-04
regressed nightly: nightly-2022-08-04
searched commit range: https://github.com/rust-lang/rust/compare/4493a0f4724c0bae1436242d76cccc9c0a287b80...1b57946a405d5b2a87e612335db033edb2c3427f
regressed commit: https://github.com/rust-lang/rust/commit/7308c22c6a8d77e82187e290e1f7459870e48d12

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --prompt --script=/teloxide/run.sh --start=2022-08-03 --end=2022-08-04 --test-dir=/teloxide/ 
```

run.sh:

```bash
#!/bin/sh
cargo doc
```
</details>

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #100204

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
It would be great to get a quick review here, in case we decide to backport this into 1.63 beta (shipping as stable this upcoming Thursday). cc @rust-lang/rustdoc

It would also be good for comments on whether it makes sense to backport this or instead drop https://github.com/rust-lang/rust/pull/99738 from 1.63 -- see my comments on the issue https://github.com/rust-lang/rust/issues/100204#issuecomment-1207294634

**Comment by Manishearth** [comment]
@bors r+

I think backporting this should be fine? Unsure.

**Pull request merged**
