### PR TITLE
Bump bootstrap compiler to 2019-04-11

### PR DESCRIPTION
**Pull request by Centril**
r? @pietroalbini 
cc @Mark-Simulacrum 
cc https://github.com/rust-lang/rust/pull/58702

### CODE REVIEW

**Comment by pietroalbini** [comment]
What the hell.

**Comment by pietroalbini** [comment]
r=me once travis is green

**Comment by ollie27** [comment]
Is there a reason not to bump the version number as well?

**Comment by Centril** [comment]
@ollie27 Bump the version number where?

**Comment by ollie27** [comment]
https://github.com/rust-lang/rust/blob/9cd61f025b1b92076e69a9ef2d9233325c7d8bdc/src/bootstrap/channel.rs#L15-L16

**Comment by Centril** [comment]
I bumped nightly to 1.36 but in the process I had to revert the `#![cfg_attr(not(stage0), deny(internal))]` => `#![deny(internal)]` changes because bumping to 1.36 combined with `#![deny(internal)]` broke the build for some reason...

@pietroalbini can you have another look?

**Comment by Mark-Simulacrum** [comment]
I expected a bunch more cfg's being removed; maybe I'm missing something?

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/blob/9cd61f025b1b92076e69a9ef2d9233325c7d8bdc/src/librustc/ty/mod.rs has an example of what I meant (I think that's actually the only case based on a quick search).

**Comment by mati865** [comment]
With this commit it builds for me: https://github.com/rust-lang/rust/commit/e09e44ad10b2dad7fa85b735287efd740f18241d

**Comment by Mark-Simulacrum** [comment]
r=me with that commit included

**Comment by Keruspe** [comment]
@Centril https://github.com/rust-lang/rust/pull/59974/commits/d6cc8551903e79bc3874e6d89f042f9691f95995 should be backported to beta in order to fix #60265

**Comment by nagisa** [comment]
A PR should be opened with the backported commit and auto-accepted since it simply fixes a technical mistake.

**Comment by Centril** [comment]
@Keruspe Can you file such a PR?

**Comment by Keruspe** [comment]
@Centril sure, will do

**Pull request merged**
