### PR TITLE
Add method to get functions and static definitions 

### LINKED ISSUE #64: Add an API to fetch the list of all reachable items of a crate
Following rust-lang/rust#121525, we can have the following method in `Context`.
```rust
fn reachable_items(&self, crate_num: CrateNum) -> Vec<DefId>;
```
It can be implemented by recursively traversing the crate using [`module_children`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/query/plumbing/struct.TyCtxtAt.html#method.module_children) (inefficient but easy to implement), or by introducing new queries in `TyCtxt` and `CrateMetadataRef` to flatten the list of all module items.

### PR DESCRIPTION
**Pull request by celinval**
Provide a StableMIR API to query function and static definitions of a crate.

Fixes https://github.com/rust-lang/project-stable-mir/issues/64

### CODE REVIEW

**Comment by celinval** [comment]
@oli-obk not sure there's a better way to retrieve this information. Let me know how I can improve this

**Comment by oli-obk** [comment]
Can't this be written in pure stable MIR on the user side? We already have iteration over all items, and we have DefKind

**Comment by celinval** [comment]
> Can't this be written in pure stable MIR on the user side? We already have iteration over all items, and we have DefKind

That's a good point. We do have an API to return all items with a body (`all_local_items` returns all items inside `mir_keys`), which may or may not be sufficient in some cases. For Kani, we do emit MIR for everything, so it would probably be sufficient even for external crates.

Not sure all tools do that though. @momvart would `all_local_items` be enough for you?

**Comment by momvart** [comment]
> Not sure all tools do that though. @momvart would `all_local_items` be enough for you?

No, my challenge actually started when I needed to find a generic function inside the core library. So particularly I'm interested in non-local items.

**Comment by oli-obk** [comment]
Usually we look up things with def ids. How are you trying to search for that function?

**Comment by momvart** [comment]
> Usually we look up things with def ids.

Yes, actually this is one of our challenges in working with MIR when we don't have the `DefId`.


> How are you trying to search for that function?

Currently, we do it linearly by the function name. So let's say you know that function `f` exists in module `m` in crate `c`. You first find the def id of `m` by searching the list of modules in `c`, then get the list of functions in `m` and search for `f` among their names.

**Comment by oli-obk** [comment]
> Yes, actually this is one of our challenges in working with MIR when we don't have the `DefId`.

how would you end up in such a situation? user code specifying a path in attributes?

**Comment by momvart** [comment]
> how would you end up in such a situation? user code specifying a path in attributes?

Having the `DefId` of particular items can be useful in different scenarios. 
- Checking for calls to a function.
- Manipulating MIR and replacing function calls.
- Checking implementations of a trait.

You can consider how `lang_items` is used. It's the list of `DefId`s for specific items.

**Comment by oli-obk** [comment]
We have `diagnostic_item`s for that, could you use the same? We have added `#[diagnostic_item]` attributes to libcore for clippy before, it seems totally ok to add it for other tools, too. And then you can look it up by a single global identifier.



> Currently, we do it linearly by the function name. So let's say you know that function `f` exists in module `m` in crate `c`. You first find the def id of `m` by searching the list of modules in `c`, then get the list of functions in `m` and search for `f` among their names.

clippy used to have tooling for that, but we removed it in favor of diagnostic items.

**Comment by celinval** [comment]
@oli-obk I think this is a legit use case, and it should be somehow covered in StableMIR. That said, I would prefer having something like https://github.com/rust-lang/project-stable-mir/issues/68 instead.

**Pull request closed without merging**
