### PR TITLE
Allow integer suffixes starting with `e`.

### LINKED ISSUE #111615: Invalid floating point literal token causes error before macro invocation
I tried this code:

```rust
// This could also be a complex proc macro
macro_rules! print_token {
    ($x:tt) => { println!("{}", stringify!($x)) }
}

fn main() {
    print_token!(123aefg123);  // ok, unknown suffix
    print_token!(123e123); // ok: float literal
    
    print_token!(123ef3); // error:  expected at least one digit in exponent
}
```

I expected to see this happen:  It should compile in print the token verbatim. If unkown/invalid suffix are OK, so should invalid float, because the macro DSL my use it for something else

Instead, this happened: Compilation error :
```
error: expected at least one digit in exponent
  --> src/main.rs:11:18
   |
11 |     print_token!(123ef3); // error:  expected at least one digit in exponent
   |                  ^^^^^^
```

(tested with Rust 1.69 as well as current nightly,  this always has been a problem)

### Context

This was discussed with @nnethercote and others last week and I wanted to make sure there is a track of this.

The usecase is so that Slint's color literal work in the `slint!` maco DSL.
Currently one can do `color: #0f9` but not `color:#0fa` in the slint! macro.  And Makepad DSL has to workaround the same issue.

### PR DESCRIPTION
**Pull request by nnethercote**
Integers with arbitrary suffixes are allowed as inputs to proc macros. A number of real-world crates use this capability in interesting ways, as seen in #103872. For example:
- Suffixes representing units, such as `8bits`, `100px`, `20ns`, `30GB`
- CSS hex colours such as `#7CFC00` (LawnGreen)
- UUIDs, e.g. `785ada2c-f2d0-11fd-3839-b3104db0cb68`

The hex cases may be surprising.
- `#7CFC00` is tokenized as a `#` followed by a `7` integer with a `CFC00` suffix.
- `785ada2c` is tokenized as a `785` integer with an `ada2c` suffix.
- `f2d0` is tokenized as an identifier.
- `3839` is tokenized as an integer literal.

A proc macro will immediately stringify such tokens and reparse them itself, and so won't care that the token types vary. All suffixes must be consumed by the proc macro, of course; the only suffixes allowed after macro expansion are the numeric ones like `u8`, `i32`, and `f64`.

Currently there is an annoying inconsistency in how integer literal suffixes are handled, which is that no suffix starting with `e` is allowed, because that it interpreted as a float literal with an exponent. For example:
- Units: `1eV` and `1em`
- CSS colours: `#90EE90` (LightGreen)
- UUIDs: `785ada2c-f2d0-11ed-3839-b3104db0cb68`

In each case, a sequence of digits followed by an 'e' or 'E' followed by a letter results in an "expected at least one digit in exponent" error. This is an annoying inconsistency in general, and a problem in practice. It's likely that some users haven't realized this inconsistency because they've gotten lucky and never used a token with an 'e' that causes problems. Other users *have* noticed; it's causing problems when embedding DSLs into proc macros, as seen in #111615, where the CSS colours case is causing problems for two different UI frameworks (Slint and Makepad).

We can do better. This commit changes the lexer so that, when it hits a possible exponent, it looks ahead and only produces an exponent if a valid one is present. Otherwise, it produces a non-exponent form, which may be a single token (e.g. `1eV`) or multiple tokens (e.g. `1e+a`).

Consequences of this:
- All the proc macro problem cases mentioned above are fixed.
- The "expected at least one digit in exponent" error is no longer possible. A few tests that only worked in the presence of that error have been removed.
- The lexer requires unbounded lookahead due to the presence of '_' chars in exponents. E.g. to distinguish `1e+_______3` (a float literal with exponent) from `1e+_______a` (previously invalid, but now the tokenised as `1e`, `+`, `_______a`).

This is a backwards compatible language change: all existing valid programs will be treated in the same way, and some previously invalid programs will become valid. The tokens chapter of the language reference (https://doc.rust-lang.org/reference/tokens.html) will need changing to account for this. In particular, the "Reserved forms similar to number literals" section will need updating, and grammar rules involving the SUFFIX_NO_E nonterminal will need adjusting.

Fixes #111615.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
This will need buy-in from the lang team. I have started a [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Allow.20integer.20suffixes.20starting.20with.20'e') for discussion.

**Comment by ogoffart** [comment]
proc_macro2 will probably need to be adjusted as well.

**Comment by nnethercote** [comment]
> proc_macro2 will probably need to be adjusted as well.

How so? I'm no proc_macro2 expert, but won't the newly accepted tokens just be more tokens, not really any different to existing tokens? E.g. `1eV` doesn't seem particularly different to `1mm`, once the lexer accepts it.

**Comment by matklad** [comment]
proc macro **2** has another copy of the lexer:

https://github.com/dtolnay/proc-macro2/blob/2c1b1021cff64aa6c29dd2c82bcb87b369013d00/src/parse.rs#L325

**Comment by nnethercote** [comment]
> proc macro **2** has another copy of the lexer:

Looks like its own implementation of the lexer, right?

cc @dtolnay, in that case, for the proc_macro2 perspective.

**Comment by petrochenkov** [comment]
The main requirement from me here is for this change to be compatible with lexer producing finer-grained tokens for floats (possibly suffixed integers, idents, and punctuation instead of whole-floats) as I described on the Zulip thread and in https://github.com/rust-lang/rust/pull/71322.

### Step 1

So I suggest to actually implement that new behavior in the lexer first.
```
1e2 -> Int(1e2)
1. -> Int(1) Punct(.)
1.2 -> Int(1) Punct(.) Int(2)
1.2e3 -> Int(1) Punct(.) Int(2e3)
1e+2 -> Int(1e) Punct(+) Int(2)
1e+_2 -> Int(1e) Punct(+) Ident(_2)
1.2e+3 -> Int(1) Punct(.) Int(2e) Punct(+) Int(3)
1.2e+_3 -> Int(1) Punct(.) Int(2e) Punct(+) Ident(3)
```
That would be of great help for any future work, and we could publicly expose this lexing mode from `rustc_lexer` even if `rustc_parser` is not using it *right now*.

For compatibility we'd also provide a mode that would immediately glue everything we've just lexed back into a `Float` token.

### Step 2

Then we'd just choose in some cases to *not* glue everything back, thus fixing https://github.com/rust-lang/rust/issues/111615.

**Comment by petrochenkov** [comment]
>`1e+_2 -> Int(1e) Punct(+) Ident(_2)`
>`1.2e+_3 -> Int(1) Punct(.) Int(2e) Punct(+) Ident(_3)`

I strongly suspect that can unsupport the underscores after +/- thus removing `Ident`s from the equation, and leaving only punctuation and (possibly suffixed) integers.
It would be interesting to run this change through crater.

**Comment by JohnCSimon** [comment]
@nnethercote 
ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!

**Comment by nnethercote** [comment]
waiting-on-author is still appropriate. Vadim's suggestion above is for a completely different approach, one that requires much larger changes, and I haven't gotten around to trying it.

**Comment by Dylan-DPC** [comment]
@nnethercote any updates on this? thanks

**Comment by nnethercote** [comment]
I'd still like to fix this, but it's fair to say progress is stalled enough that closing this is reasonable.

**Pull request closed without merging**
