### PR TITLE
Update libc to 0.2.64

### PR DESCRIPTION
**Pull request by mati865**
Passed local tests.

cc potentially interested people: @gnzlbg @tlively

### CODE REVIEW

**Comment by gnzlbg** [comment]
@mati865 thanks, there haven't been any reported issues with libc 0.2.64 yet, so I think we can land this already.

**Comment by oxalica** [comment]
Test on `wasm32-unknown-emscripten` failed in #65483

This special cased conversion should be removed.
https://github.com/mati865/rust/blob/libc/src/libstd/sys/unix/fs.rs#L606

These two `if let` become irrefutable, seems can be simply removed.
https://github.com/mati865/rust/blob/libc/src/libstd/sys/unix/fd.rs#L81
https://github.com/mati865/rust/blob/libc/src/libstd/sys/unix/fd.rs#L138

**Comment by tlively** [comment]
This failure should also be fixed by https://github.com/rust-lang/rust/pull/65251.

**Comment by tlively** [comment]
I just approved #65251 and if I'm reading https://buildbot2.rust-lang.org/homu/queue/rust correctly, that PR will be merged before this one, so no change should have to be made here (unless there's a merge conflict I guess).

**Comment by mati865** [comment]
@tlively I don't think #65251 is going to fix this specific issue. I'll look at libc changes and try to fix it.
Anyway feel free to bump libc on your PR if you wish.

@oxalica thank you for investigating the failure.

**Comment by mati865** [comment]
Force pushed to remove test commit, this time `asmjs` job passed: https://dev.azure.com/rust-lang/rust/_build/results?buildId=10968

Ready to go.

**Pull request merged**
