### PR TITLE
Preserve ASAN-related symbols during LTO.

### LINKED ISSUE #113404: __asan_globals_registered is not comdat when building a staticlib with LTO
Disclaimer: I tried to create a testcase from scratch, but for some reason I wasn't able to find a way to trigger the use of `__asan_register_elf_globals` instead of `__asan_globals_register`.

STR:
- Clone https://github.com/glandium/nss-builtins
- `cd nss-builtins`
- `RUSTFLAGS="-Zsanitizer=address" CARGO_PROFILE_RELEASE_LTO=true cargo +nightly build --release`
- `objdump -t target/release/libbuiltins_static.a | grep asan_globals_registered`

Actual output:
```
0000000000000000 l     O .bss.___asan_globals_registered	0000000000000008 ___asan_globals_registered
0000000000000000 l    d  .bss.___asan_globals_registered	0000000000000000 .bss.___asan_globals_registered
```

Expected output:
Something like:
```
0000000000000008       O *COM*	0000000000000008 .hidden ___asan_globals_registered
```

This doesn't happen without LTO.
The unfortunate consequence is that when the resulting static library is linked with C or C++ code compiled with clang with `-fsanitize=address -fsanitize-address-globals-dead-stripping` (that latter flag is now default in clang trunk), which also uses `__asan_register_elf_globals`/`__asan_globals_registered`, ODR violation detection kick in complaining about globals defined multiple times, because both the clang-side asan constructor and the rust asan constructor register all the globals. Normally, what happens is that they both use the same `__asan_globals_registered` (thus it normally being `*COM*`), and set its value, so that only one constructor registers the globals. With the LTOed staticlib, what happens is that there are two distinct `__asan_globals_registered`, so both constructors go through.

`rustc +nightly --version --verbose`:
```
rustc 1.72.0-nightly (d9c13cd45 2023-07-05)
binary: rustc
commit-hash: d9c13cd4531649c2028a8384cb4d4e54f985380e
commit-date: 2023-07-05
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

(Edit: fixed typos, changed the peculiar setup with `-Clto` and `-Cembed-bitcode=yes` to the more normal LTO, which shows the problem too)

### PR DESCRIPTION
**Pull request by anforowicz**
Fixes https://github.com/rust-lang/rust/issues/113404

### CODE REVIEW

**Comment by compiler-errors** [comment]
sorry, I don't really have enough context to review this.

r? compiler

**Comment by anforowicz** [comment]
Maybe this PR can be reviewed by @tmiasko (who has previously reviewed the abandoned fix attempt/direction at https://github.com/rust-lang/rust/pull/114642 and has been involved in the discussion in https://github.com/rust-lang/rust/issues/113404)?

**Comment by nikic** [comment]
Can you please also test `-C lto=thin` in this and all other relevant tests? I feel like it should break because you're only changing full LTO internalization, while thin LTO also does this in a different way.

**Comment by anforowicz** [comment]
> Can you please also test `-C lto=thin` in this and all other relevant tests? 

Good point.  Done, sort-of - I've added `-C lto=thin` flavour to the new `address-sanitizer-globals-tracking.rs` test and to the existing `memory-track-origins.rs` test.

I don't know how to add this coverage to `sanitizer-recover.rs`.  When I try doing this, then `FileCheck` complains that it `Could not open input file '/usr/local/google/home/lukasza/src/github/rust/build/x86_64-unknown-linux-gnu/test/codegen/sanitizer/sanitizer-recover.MSAN-RECOVER-THIN-LTO/sanitizer-recover.ll': No such file or directory`.  I don't see any `rustc` errors (would I need to pass extra `./x.py` or `rustc` flags to see them?).  I see that this test doesn't specify `#![crate_type="lib"]` nor `#![crate_type="staticlib"]` - not sure if this would matter (as a consequence this test also doesn't specify `-C prefer-dynamic=false`).

I also felt unable to tweak https://github.com/rust-lang/rust/commit/4053e25bfb55b6e1bf6766158ccd06cb87de79c7#diff-4c2e2f96156d5aa76e678ae72c4006d62ec03e05a546330d8ea98275ac9b9f67 to also apply to thin LTO...

Hopefully the coverage above is good enough?

> I feel like it should break because you're only changing full LTO internalization, while thin LTO also does this in a different way.

I think that thin LTO should be safe, because AFAIU the problem here was internalization (inlining/hiding global symbols into local symbols).  And it seems to me that thin LTO can't really do such thing (because it needs to preserve global symbols in case they are used by other CGUs).

**Comment by anforowicz** [comment]
> https://github.com/rust-lang/rust/pull/114946#issuecomment-1687036670: I don't know how to add this coverage to sanitizer-recover.rs. When I try doing this, then FileCheck complains 

I've tried running `./x -v ...` and it seems that the problem was: `ignoring emit path because multiple .ll files were produced`.

I don't understand why there are multiple `.ll` files:

```
$ ls .../github/rust/build/x86_64-unknown-linux-gnu/test/codegen/sanitizer/sanitizer-recover.MSAN-RECOVER-THIN-LTO
sanitizer-recover.2f39cus7tyzltjwu.rcgu.ll
sanitizer-recover.57laxi1n5rnsv40z.rcgu.ll
sanitizer-recover.addr2line-63498f7ec81b51f2.addr2line.74ba4853a214e382-cgu.0.rcgu.o.rcgu.ll
sanitizer-recover.adler-2e72a29cbb2fad9b.adler.a59ddefc5a607a39-cgu.0.rcgu.o.rcgu.ll
sanitizer-recover.alloc-42fb4edbc8124fd6.alloc.65c1c8b47eaec200-cgu.0.rcgu.o.rcgu.ll
sanitizer-recover.alloc-42fb4edbc8124fd6.alloc.65c1c8b47eaec200-cgu.1.rcgu.o.rcgu.ll
sanitizer-recover.alloc-42fb4edbc8124fd6.alloc.65c1c8b47eaec200-cgu.2.rcgu.o.rcgu.ll
sanitizer-recover.alloc-42fb4edbc8124fd6.alloc.65c1c8b47eaec200-cgu.3.rcgu.o.rcgu.ll
sanitizer-recover.alloc-42fb4edbc8124fd6.alloc.65c1c8b47eaec200-cgu.4.rcgu.o.rcgu.ll
sanitizer-recover.cfg_if-29d93783939fbc45.cfg_if.46e0b2051d9f73ec-cgu.0.rcgu.o.rcgu.ll
...
```

> https://github.com/rust-lang/rust/pull/114946#issuecomment-1687044189: Could not open input file '.../test/codegen/sanitizer/address-sanitizer-globals-tracking.ASAN-THIN-LTO/address-sanitizer-globals-tracking.ll': No such file or directory

Not sure why this doesn't repro locally.  Maybe I should  try to debug with llvm-15, starting by reading https://rustc-dev-guide.rust-lang.org/tests/docker.html?highlight=docker#testing-with-docker

FWIW I feel a bit lost here.  Any advice how to proceed here?

**Comment by anforowicz** [comment]
FWIW it seems that the only already-existing ThinLTO test under `tests/codegen/` is `issue-81408-dllimport-thinlto-windows.rs` (which is restricted to `only-windows`).

**Comment by anforowicz** [comment]
Let me also try discussing this in t-compiler/help on Zulip: [`lto=thin` + `test/codegen` = multiple-`.ll`-files problem](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.60lto.3Dthin.60.20.2B.20.60test.2Fcodegen.60.20.3D.20multiple-.60.2Ell.60-files.20problem)

**Comment by anforowicz** [comment]
Status update: I think this issue cannot be reprod using `tests/ui`.  Let me try to explain below.

----------------------

I believe that to repro the issue we need `staticlib` output from `rustc`:

* If I use `#![crate_type = "rlib"]` in `issue-113404-lib1.rs` and extract (using `ar`) the object file, then `build/x86_64-unknown-linux-gnu/llvm/bin/llvm-nm -gU issue-113404-lib1.issue_113404_lib1.209bbc80fa7d2e2c-cgu.0.rcgu.o` includes `C ___asan_globals_registered`
* If I use `#![crate_type = "staticlib"]` then `llvm-nm` output does **not** include `___asan_globals_registered`

--------------------

But `staticlib` seems incompatible with `tests/ui` - the following `tests/ui/lto/issue-113404.rs` fails to build when `issue-113404-lib1.rs` is a `staticlib`:

    ```
    // aux-build: issue-113404-lib1.rs
    extern crate issue_113404_lib1 as lib1;
    ```

--------------------

So, I guess the next step is to try to author the new test under `tests/run-make`.

**Comment by anforowicz** [comment]
RE: @nikic: https://github.com/rust-lang/rust/pull/114946#issuecomment-1686916757: ThinLTO test coverage

I am unable to provide such test coverage.  In https://github.com/rust-lang/rust/issues/113404#issuecomment-1693720349 I am:
- Asking for help with finding a minimal repro (that may potentially be used in `tests/run-make`)
- Asking for discussion about whether ThinLTO test coverage is a hard requirement for landing this PR

**Comment by bjorn3** [comment]
With this change won't we use a linker script that hides all those symbols? The linker script is generated from `exported_symbols` from which you remove all those symbols: https://github.com/rust-lang/rust/blob/a8b905cd78c4ddfa4a7a517ada260506af4adfad/compiler/rustc_codegen_ssa/src/back/linker.rs#L1688 For staticlib this currently doesn't apply as rustc currently is unable to hide any exports for staticlibs, but this needs to be fixed to allow linking multiple rust staticlibs into the same dylib/executable.

**Comment by anforowicz** [comment]
RE: @bjorn3: https://github.com/rust-lang/rust/pull/114946#issuecomment-1693765740:

> With this change won't we use a linker script that hides all those symbols? The linker script is generated from `exported_symbols` from which you remove all those symbols:
> 
> https://github.com/rust-lang/rust/blob/a8b905cd78c4ddfa4a7a517ada260506af4adfad/compiler/rustc_codegen_ssa/src/back/linker.rs#L1688
> 
> For staticlib this currently doesn't apply as rustc currently is unable to hide any exports for staticlibs, but this needs to be fixed to allow linking multiple rust staticlibs into the same dylib/executable.

I agree that the PR here impacts what gets returned from `fn exported_symbols` (i.e. after this PR things like `__msan_track_origins` will no longer be included).  Sadly, I don't understand what you mean by "linker script" above (this is probably just my incompetence and unfamiliarity with linkers - I am just a simple Chromium developer... :-( ).  I am aware of  version scripts (e.g. Chromium passes `-Wl,--version-script=..../chrome.map` [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/BUILD.gn;l=338-341;drc=79ca9265d25f26dd9dc3c8fad2a72241054e14ae)) - maybe linker script just another name for a version script?

At any rate, the paragraph I wrote above may not matter much.  I think that ultimately you are pointing out that this PR may introduce a regression into `rustc`, and if so, then it seems desirable/important to prevent the regression (now and in the future) by adding a new test (if it is possible and not too difficult).

* I assume that the existing tests would catch the regression? (FWIW `./x test` passes on my local development machine).
* Could you please help with authoring such `tests/ui` or `tests/run-make` test?  If you don't have time to try authoring such tests yourself (which I would appreciate very much :-), then maybe you can outline the setup that you think would give a repro (e.g. what crates / linking / etc would the test need to use)?  IIUC you are saying that the problem would happen with fat LTO + that dynamic linking might be required for a repro + that the repro might not require ASAN (e.g. maybe a simpler repro can be created with MSAN)?

My apologies if I mixed up anything (as I said, I am not a linker expert) - I would appreciate your help with this.

**Comment by anforowicz** [comment]
And I think that you are saying that before this PR symbols like `__msan_track_origins` would be exported out of `.dll`s / `.so`s but they would no longer be exported after this PR.  Did I get this right?

**Comment by bjorn3** [comment]
Yes, when rustc does the linking with this PR the version script would hide those symbols.

**Comment by anforowicz** [comment]
RE: @bjorn3: https://github.com/rust-lang/rust/pull/114946#issuecomment-1694486627:
> Yes, when rustc does the linking with this PR the version script would hide those symbols.

Ack.  Let me try to rephrase in my own words to double-check my understanding.

AFAIU the trouble is when `fn linker_with_args` in `compiler/rustc_codegen_ssa/src/back/link.rs` calls `Linker::export_symbols`: https://github.com/rust-lang/rust/blob/4e78abb437a0478d1f42115198ee45888e5330fd/compiler/rustc_codegen_ssa/src/back/link.rs#L2067-L2076

I think you are saying that (always?  on some platforms only?) the PR will affect the linker command line generated by `rustc` (in one of `impl`s of `Linker::export_symbols`) and so the PR will prevent `__asan_globals_registered` (and/or `__msan_track_origins`, `__llvm_profile_filename`, etc.) from being exported out of dynamically-linked libraries (e.g. `.dll`s / `.so`s).

-------------------------

But then `__asan_globals_registered` is `common hidden global` and [LLVM Reference Manual](https://llvm.org/docs/LangRef.html#visibility-styles) seems to say that `hidden` objects are not meant to be exported out of dynamically-linked libraries:

> Two declarations of an object with hidden visibility refer to the same object if they are in the same shared object. Usually, hidden visibility indicates that the symbol will not be placed into the dynamic symbol table, so no other module (executable or shared library) can reference it directly.

So maybe your concern doesn't necessarily apply to `__asan_globals_registered`, because it doesn't need to be exported?  Can you please comment on that?

-------------------------

OTOH, I am not sure if the previous section (if correct at all) helps with other symbols.  Maybe listing their LLVM-IR attributes will help us make some progress here:

* `__asan_globals_registered` is `common hidden global i64` (when running the new `tests/codegen/sanitizer/address-sanitizer-globals-tracking.rs` on Linux host)
* `__msan_track_origins` is `weak_odr constant i32 1` (when running `tests/codegen/sanitizer/memory-track-origins.rs` on a Linux host)
* `__msan_keep_going` is `weak_odr constant i32 1` (when running `tests/codegen/sanitizer/sanitizer-recover.rs` on Linux host)
* `__llvm_profile_filename = hidden local_unnamed_addr constant [19 x i8] c"default_%m.profraw\00", comdat` (when running `tests/codegen/pgo-instrumentation.rs` on Linux host)
* `__llvm_profile_raw_version = comdat any`

If the concern still applies to the other symbols, then maybe this PR can be tweaked so that it only touches `__asan_globals_registered`?

**Comment by bjorn3** [comment]
> I think you are saying that (always? on some platforms only?) the PR will affect the linker command line generated by rustc (in one of impls of Linker::export_symbols) and so the PR will prevent __asan_globals_registered (and/or __msan_track_origins, __llvm_profile_filename, etc.) from being exported out of dynamically-linked libraries (e.g. .dlls / .sos).

Correct.

> But then __asan_globals_registered is common hidden global and [LLVM Reference Manual](https://llvm.org/docs/LangRef.html#visibility-styles) seems to say that hidden objects are not meant to be exported out of dynamically-linked libraries:

I see. In that case adapting just the LTO code would work for now I think.

**Comment by anforowicz** [comment]
@bjorn3 / @nikic / @tmiasko - could you PTAL again?

The latest shape of this PR:
- Doesn't touch `compiler/rustc_codegen_ssa/src/back/symbol_export.rs` and therefore doesn't affect MSAN-related or PGO-related symbols.
- Only special-cases `___asan_globals_registered` in `PreserveFunctions` in `compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp`.

Additional notes:
- Why the fix touches `PassWrapper.cpp` instead of `symbol_export.rs`
    - Injecting `___asan_globals_registered` can't be handled in `symbol_export.rs`, because of having to replicate the LLVM conditions that control when this symbol is present - not only MachO/ELF, but also `ShouldUseMachOGlobalsSection` and `!getUniqueModuleId(&M).empty()` (see https://github.com/rust-lang/rust/pull/114642#issuecomment-1696340160)
    - `___asan_globals_registered` doesn't need to be recognized in `symbol_exports.rs` because this symbol is `hidden` and doesn't need to be exported out of dynamically-linked libraries (see https://github.com/rust-lang/rust/pull/114946#issuecomment-1697155860)
- Why the PR only adds a regression test in `tests/codegen/sanitizer/address-sanitizer-globals-tracking.rs`
    - This level of testing has been okay for other similar fixes (e.g. `tests/codegen/sanitizer/sanitizer-recover.rs` and `tests/codegen/sanitizer/memory-track-origins.rs`)
    - We concluded that ThinLTO testing is not possible via `tests/codegen` tests (see [a Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.60lto.3Dthin.60.20.2B.20.60test.2Fcodegen.60.20.3D.20multiple-.60.2Ell.60-files.20problem))
    - The PR author was unable to create an end-to-end repro of the problem using `tests/run-make` or `tests/ui`.  This may be possible, but currently we don't have such test.

@rustbot review

**Pull request merged**
