### PR TITLE
put empty generic lists behind a pointer

### PR DESCRIPTION
**Pull request by arielb1**
This reduces the size of hir::Expr from 128 to 88 bytes (!) and shaves
200MB out of #36799.

This is a performance-sensitive PR so please don't roll it up.

r? @eddyb

### CODE REVIEW

**Comment by arielb1** [comment]
problem compiling rustdoc. *Very* done for today. Will fix on Sunday.

> [00:36:02] error[E0609]: no field `types` on type `&std::option::Option<syntax::ptr::P<rustc::hir::PathParameters>>`

@bors r-

**Comment by Mark-Simulacrum** [comment]
@bors retry

cc @alexcrichton -- possibly an issue with Cargo/crates.io?

```
[00:04:51] extracting /Users/travis/build/rust-lang/rust/build/cache/2017-08-29/rustc-beta-i686-apple-darwin.tar.gz

[00:04:52] downloading https://static.rust-lang.org/dist/2017-08-29/cargo-beta-i686-apple-darwin.tar.gz

[00:04:52] 
################################                                          44.6%
#######################################################                   76.5%
######################################################################## 100.0%

[00:04:55] extracting /Users/travis/build/rust-lang/rust/build/cache/2017-08-29/cargo-beta-i686-apple-darwin.tar.gz

[00:04:57]     Updating registry `https://github.com/rust-lang/crates.io-index`



No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Pull request merged**
