### PR TITLE
Update Cargo

### PR DESCRIPTION
**Pull request by alexcrichton**
Brings in some perf improvements!

### CODE REVIEW

**Comment by petrochenkov** [comment]
Nice!
Running a single test with `x.py test` is annoyingly slow, maybe this will help a bit (submodule processing is still the main problem though).
For reference, the perf improvements in question are https://github.com/rust-lang/cargo/pull/4118.
@bors r+

**Comment by Mark-Simulacrum** [comment]
@bors r-

https://travis-ci.org/rust-lang/rust/jobs/239646661#L1219

```
[00:01:38] error: the lock file needs to be updated but --frozen was passed to prevent this
[00:01:38] failed to run: /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /checkout/src/bootstrap/Cargo.toml --locked
[00:01:38] Build completed unsuccessfully in 0:00:31
[00:01:38] Makefile:76: recipe for target 'prepare' failed
```

**Comment by alexcrichton** [comment]
@bors: r+

FWIW I would not roll this up, it runs a high risk of breakage.

**Comment by ishitatsuyuki** [comment]
RLS submodule should also be updated since this changes API.

**Comment by alexcrichton** [comment]
Nominating and accepting beta as the original beta didn't include this fix but we'll want to get the beta onto the `rust-1.19.0` branch of Cargo.

**Pull request merged**
