### PR TITLE
`is_some_and` taking `self` demo

### PR DESCRIPTION
**Pull request by camsteffen**
This is just to demo the difference between `&self` and `self` as [requested](https://github.com/rust-lang/rust/issues/93050#issuecomment-1176657005). The last commit "Fix is_some_and usages taking by value" is the interesting one.

r? @joshtriplett

### CODE REVIEW

**Review by flip1995 — COMMENTED** [review]
There are some formatting-only changes in the Clippy files. Please don't commit those. I think I left a comment for each of those changes.

**Comment by camsteffen** [comment]
@flip1995 sorry this PR is not intended to be merged. But fwiw the formatting changes are made with `cargo fmt -p clippy_lints -p clippy_utils`.

**Comment by flip1995** [comment]
> But fwiw the formatting changes are made with `cargo fmt -p clippy_lints -p clippy_utils`.

This then probably uses the `rust-lang/rust` `rustfmt.toml` file and not the Clippy one? Is this ran automatically by some `x.py` command?

**Comment by joshtriplett** [comment]
@camsteffen I'd be happy to r+ a non-draft version of this; I think we've settled the question of taking self.

**Comment by camsteffen** [comment]
@joshtriplett I reopened #98354.

**Pull request closed without merging**
