### PR TITLE
[beta] Update cargo

### PR DESCRIPTION
**Pull request by sgrif**
This updates Cargo to the latest rust-1.34.0 branch

r? @alexcrichton

### CODE REVIEW

**Comment by sgrif** [comment]
Not entirely sure what to make of that build log

**Comment by ehuss** [comment]
@sgrif run `cargo update -p cargo` in the root to pick up the new `http` dependency.

**Comment by sgrif** [comment]
Thanks, should be green now

**Comment by pietroalbini** [comment]
@bors retry

Yielding priority since this is going to be rolled up.

**Pull request merged**
