### PR TITLE
Fix end region emission order

### LINKED ISSUE #43481: EndRegion and StorageDead are emitted in the wrong order
This code
```rust
fn slice_index() -> u8 {
    let arr: &[_] = &[101, 102, 103, 104, 105, 106];
    arr[5]
}
```
results in the following MIR (before region erasure):
```
_3 = &ReScope(Remainder(BlockRemainder { block: NodeId(92), first_statement_index: 0 })) _4;
...
StorageDead(_4);
EndRegion(ReScope(Remainder(BlockRemainder { block: NodeId(92), first_statement_index: 0 })));
```
So, `_4` is borrowed for this scope, but actually it is marked dead *before* the scope ends. That seems wrong to me, shouldn't `_4` have to be live at least until the region ends?

Cc @pnkfelix @nikomatsakis

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix #43481

### CODE REVIEW

**Comment by arielb1** [comment]
Can you have a test that shows how this fits with the destruction code extent?

**Comment by nikomatsakis** [comment]
r=me modulo @arielb1's concern

**Comment by pnkfelix** [comment]
Sorry its taking me so long to finish this off. I spent a while trying to create a case matching @arielb1's expectation. Now I think I have one, but I also am not sure whether the outline @arielb1 gave is what we should actually want to see in practice.

Here is some input code I've come up with:

```rust
fn main() {
    // This case illustrates one particular ordering of interest:
    D1(&S1("tmp"));
}

#[derive(Debug)]
struct S1(&'static str);

#[derive(Debug)]
struct D1<'a>(&'a S1);

impl<'a> Drop for D1<'a> {
    fn drop(&mut self) {
        println!("D1({:?})", self.0); 
    }
}
```

Here is the output MIR (compiled via: `./build/x86_64-apple-darwin/stage1/bin/rustc -Z identify_regions -Z span_free_formats -Z dump-mir=main  ../src/test/mir-opt/end_region_destruction_extents_1.rs`):

```
// MIR for `main`
// source = Fn(NodeId(4))
// pass_name = SimplifyCfg-initial
// disambiguator = after

fn main() -> () {
    let mut _0: ();
    let mut _1: D1<'160dce>;
    let mut _2: &'160dce S1;
    let mut _3: &'160dce S1;
    let mut _4: S1;

    bb0: {
        StorageLive(_2);
        StorageLive(_3);
        StorageLive(_4);
        _4 = S1::{{constructor}}(const "tmp",);
        _3 = &'160dce _4;
        _2 = &'160dce (*_3);
        _1 = D1<'160dce>::{{constructor}}(_2,);
        drop(_1) -> bb1;
    }

    bb1: {
        StorageDead(_2);
        StorageDead(_3);
        StorageDead(_4);
        EndRegion('160dce);
        _0 = ();
        return;
    }
}
```

So, here's my problem: I agree that `'160dce` should come after the `drop(_1)`.

But it should *precede* the `StorageDead(_4)`, right?

... 

(Also, I just realized that this code actually only started compiling relatively recently; on the current stable, it is rejected with a suggestion that the `S1("tmp")` doesn't live long enough. So maybe this is a case where EndRegion emission needs to account for r-value promotion, which, if fixed, would result in the ordering `drop(_1); EndRegion('160dce); StorageDead(_4);` ... maybe?

**Comment by nikomatsakis** [comment]
> (Also, I just realized that this code actually only started compiling relatively recently; on the current stable, it is rejected with a suggestion that the `S1("tmp")` doesn't live long enough. So maybe this is a case where EndRegion emission needs to account for r-value promotion, which, if fixed, would result in the ordering `drop(_1); EndRegion('160dce); StorageDead(_4);` ... maybe?

I think what I would expect is that we would run the qualification pass after construction, and hence wind up removing `_4` in favor of a new static. In that case, the fact that `StorageDead(_4)` precedes `EndRegion('160dce)` wouldn't cause an error, because `_4` is not being borrowed anymore.

**Comment by arielb1** [comment]
@pnkfelix 

Your example only compiles because of rvalue promotion. An rvalue-promotion version (or this one, on stable) errors as it should - today's borrowck basically puts the `'dce` endregion after all the drops.

```Rust
fn main() {
    // This case illustrates one particular ordering of interest:
    let x = "tmp";
    D1(&S1(x));
}

#[derive(Debug)]
struct S1(&'static str);

#[derive(Debug)]
struct D1<'a>(&'a S1);

impl<'a> Drop for D1<'a> {
    fn drop(&mut self) {
        println!("D1({:?})", self.0); 
    }
}
```

Also, you can easily have `drop -> storagedead -> drop -> storagedead` orderings, as in:
```Rust
fn main() {
    D1((&D1(&S1("red")), &S1("tmp"), &D1(&S1("herring"))).1);
}
```

In which case there is no "between the drop and storagedead" place.

Therefore, I prefer having the drop & storagedead as 1 unit and placing the `EndRegion` after them.

**Comment by arielb1** [comment]
I'll also note that moving the `EndRegion` to after the `StorageDead` can only make less code compile - you won't have any new "liveness" requirements (because `StorageDead` doesn't have any) but now the `StorageDead` can conflict with pre-existing borrows.

**Comment by pnkfelix** [comment]
@arielb1 ... okay, but isn't that in conflict with the property (taken from https://github.com/rust-lang/rust/issues/43481#issuecomment-324953644  ):

* For all `'rgn`, and all `lval` such that the code has borrow(s) of form `&'rgn lval`, whereever `StorageDead(lval)` occurs, the region `'rgn` has already ended (via `EndRegion('rgn)`).

**Comment by pnkfelix** [comment]
@arielb1 or maybe I misunderstand (once again)? Are you saying that we *will* enforce the property, because the compiler will *reject* such code?

**Comment by arielb1** [comment]
@pnkfelix 

Thats... what the borrow-check does. Or  at least what it's *supposed* to do.

**Comment by pnkfelix** [comment]
@arielb1 okay, I was confused because I thought you were suggesting an ordering for {Drop,StorageDead,EndRegion} that you intended to be *legal* to the borrowck in cases like this.

**Comment by kennytm** [comment]
@bors retry

`check i686-apple-darwin` hung during doc test of `libstd`. Reason unknown.

```
[02:08:15] test collections/hash/set.rs - collections::hash::set::HashSet<T, S>::is_disjoint (line 542) ... ok
[02:08:15] test collections/hash/set.rs - collections::hash::set::HashSet<T, S>::is_empty (line 442) ... ok


No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by kennytm** [comment]
@bors retry #44221

`check i686-apple-darwin` stuck again.

```
[00:18:16]    Compiling rustc_llvm v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/librustc_llvm)
[00:18:20]    Compiling flate2 v0.2.19
[00:18:20]    Compiling rustc_errors v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/librustc_errors)
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by alexcrichton** [comment]
@bors: retry

* upstream travis issue

**Comment by kennytm** [comment]
@bors retry p=-1 #42117 

```
[00:04:00] extracting /Users/travis/build/rust-lang/rust/build/cache/2017-07-18/cargo-beta-i686-apple-darwin.tar.gz
[00:04:01]     Updating registry `https://github.com/rust-lang/crates.io-index`
[00:05:16]     Updating git repository `https://github.com/rust-lang/cargo`

No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

(reduce priority because it has failed too many times, even if spurious.)

**Comment by nikomatsakis** [comment]
@pnkfelix merge conflict :(

**Comment by aidanhs** [comment]
@bors r-

Failure seems related?
```
Check compiletest suite=mir-opt mode=mir-opt (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:49:22] 
[00:49:22] running 32 tests
[00:49:27] thread 'main' panicked at 'Some tests failed', /checkout/src/tools/compiletest/src/main.rs:323:21
[00:49:27] ..............F.F.F.............
[00:49:27] failures:
[00:49:27] 
[00:49:27] ---- [mir-opt] mir-opt/end_region_9.rs stdout ----
[00:49:27] 	thread '[mir-opt] mir-opt/end_region_9.rs' panicked at 'ran out of mir dump output to match against.
[00:49:27] Did not find expected line: "    let mut _4: &\'13_0rs i32;"
```

**Comment by pnkfelix** [comment]
Thanks @aidanhs sorry about that!

**Pull request merged**
