### PR TITLE
fix typos in the example code in the doc comments of `Ipv4Addr::from_bits()`, `Ipv6Addr::from_bits()` & `Ipv6Addr::to_bits()`

### PR DESCRIPTION
**Pull request by hltj**

### CODE REVIEW

**Comment by tgross35** [comment]
While you are working on this, would you be willing to update `to_bits` as well? It looks like those examples don't even call `to_bits`.

**Comment by hltj** [comment]
> While you are working on this, would you be willing to update `to_bits` as well? It looks like those examples don't even call `to_bits`.

Yeah, `assert_eq!(0x102030405060708090A0B0C0D0E0F00D_u128, u128::from(addr));` should also be updated to `assert_eq!(0x102030405060708090A0B0C0D0E0F00D_u128, addr.to_bits());`, I missed it before.

**Review by tgross35 — APPROVED** [review]
Thanks! Could you squash please?

**Comment by hltj** [comment]
> Thanks! Could you squash please?

OK, squashed.

**Pull request merged**
