### PR TITLE
[stable] Prepare 1.66.0 release

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR prepares the artifacts for the 1.66.0 release. The following PRs have been backported:

* #104782
* #105023
* #104558 
* #104610
* #103989
* #104650
* #105539
* #105477

r? @ghost

### CODE REVIEW

**Comment by pietroalbini** [comment]
Need to finish the PR by backporting the release notes, will do so later today. Do not merge yet.

**Comment by ehuss** [comment]
@pietroalbini Just checking if you plan to accept or reject #104650 for backport? To be clear, I don't think that PR is *required*. The current builds seem to be working ok with xcode 14. The only reason I suggest it is because Apple documents it as not being supported, so we don't know what consequences there might be. It may also be a little strange to switch from 13 to 14 (in 1.66) and then back to 13 in 1.67.

There are also a few other nominated (though not approved) PRs.

**Comment by pietroalbini** [comment]
@bors r- retry

Yielding to the beta PR while we decide on last minute backports.

**Comment by pietroalbini** [comment]
Added backports for:

* #103989
* #104650
* #105539

@bors r+ p=1000 rollup=never

**Comment by BlackHoleFox** [comment]
@pietroalbini Copy pasting this from #104650, but I don't think that beta nomination of `Build macOS distribution artifacts with XCode 13` was enough. Even after it, the macOS artifacts were still unusable on older macOS versions. The PR that actually fixed the regression was #105123.

**Comment by BlackHoleFox** [comment]
@ehuss ahh, ok, many thanks for clearing that up. My brain skipped thinking about the _past_ beta for some reason. I'm lined up with your thoughts on XCode 13 though.

**Comment by pietroalbini** [comment]
Backported https://github.com/rust-lang/rust/pull/105477 to get CI working again.

@bors r+ p=1000 rollup=never

**Comment by ehuss** [comment]
> Backported #105477 to get CI working again.

Sorry, I forgot to tag that for beta-nominated.

**Pull request merged**
