### PR TITLE
Remove --crate-type=metadata deprecation warning

### LINKED ISSUE #38640: Remove deprecation warning for --crate-type=metadata
UPDATE: Very easy way first bug! [Mentoring instructions here.](https://github.com/rust-lang/rust/issues/38640#issuecomment-304306325)

-----

This didn't spend long in the wild, so we don't need to wait too long. But, Cargo does rely on the flag, so we should leave it in at least long enough to fix Cargo and for people to upgrade.

### PR DESCRIPTION
**Pull request by citizen428**
Fixes #38640

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Looks like there's a warning you'll need to fix:

```
[00:06:12] error: variable does not need to be mutable
[00:06:12]     --> /checkout/src/librustc/session/config.rs:1634:9
[00:06:12]      |
[00:06:12] 1634 |     let mut emit_metadata = false;
[00:06:12]      |         ^^^^^^^^^^^^^^^^^
[00:06:12]      |
[00:06:12]      = note: #[deny(unused_mut)] implied by #[deny(warnings)]
[00:06:12] note: lint level defined here
[00:06:12]     --> /checkout/src/librustc/lib.rs:23:9
[00:06:12]      |
[00:06:12] 23   | #![deny(warnings)]
[00:06:12]      |         ^^^^^^^^
[00:06:12] 
[00:06:12] error: aborting due to previous error
```

**Comment by citizen428** [comment]
@Mark-Simulacrum I know, thanks. Basically just did that in a rush earlier and pushed it up, figured I'll look at the Travis output later. I can't seem to manage labels, can you change it to `S-waiting-on-author` please?

**Comment by citizen428** [comment]
@Mark-Simulacrum I fixed removed the `mut` which should fit the warning. I'm just wondering if that variable can be removed completely? 

```rust
let emit_metadata = false;
...
return Ok((crate_types, emit_metadata));
```

It's only called in one location in the same file (line 1357) and I think it might be better to completely remove it. 

cc @nikomatsakis

**Comment by Mark-Simulacrum** [comment]
Yeah, remove `emit_metadata` here, and if you follow that change through (change the return type of `parse_crate_types_from_list` and go from there, you'll find that `OutputType::Metadata` can probably be removed as well (removing a bunch of cruft from the compiler that's no longer needed since this is always false).

**Comment by citizen428** [comment]
Just FYI, I'm working my way through this. Properly removing the flag instead of having it permanently set to false is somewhat more effort than originally outline in the mentoring description, but seems to be worth it.

**Comment by Mark-Simulacrum** [comment]
src/test/run-pass/auxiliary/rmeta_rmeta.rs and src/test/run-pass/rmeta.rs need to be deleted since they are testing `--emit=metadata`.

**Comment by citizen428** [comment]
@Mark-Simulacrum `src/test/run-pass/auxiliary/rmeta_rmeta.rs` is already removed as you can see in the file list. But thanks for confirming that they can indeed be remove. There are still a few leftovers like `meta_stats` etc. that I'm a bit unsure about. If we do this, we might as well rip out everything that's not necessary anymore.

**Comment by Mark-Simulacrum** [comment]
Actually, I think I lied; we do want to keep `--emit=metadata`, it's the crate type that is gone. I think rmeta_meta should've been kept actually, as should at least most of the other tests. Sorry about the run-around. This may mean that some of the code that you've removed needs to be re-added..

**Comment by citizen428** [comment]
@Mark-Simulacrum I went back to a very early version of this PR, basically just removing the code snippet that had the deprecation warning, the related `emit_metadata` variable and its use at the callsite.

**Comment by citizen428** [comment]
@Mark-Simulacrum This PR is `S-waiting-on-review` again.

**Pull request merged**
