### PR TITLE
[CI test] Turn `rustc-dev-guide` into a subtree

### PR DESCRIPTION
**Pull request by Kobzol**
This is a test PR to check what happens if we move `rustc-dev-guide` into a subtree. This move was discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/196385-t-compiler.2Fwg-rustc-dev-guide/topic/a.20move.20to.20main.20repo.20.28rust-lang.2Frust.29).

Used instructions from https://gist.github.com/Nikita240/0c98cea8f53a15e69699cd8bc40657c4. More specifically, ran:
```
DIR=src/doc/rustc-dev-guide

git submodule status ${DIR}
# b21d99b770f9aceb0810c843847c52f86f45d2ed
git submodule deinit ${DIR}
git rm -r --cached ${DIR}
rm -rf ${DIR}
git commit -m"Removed ${DIR}"
git subtree add -P src/doc/rustc-dev-guide https://github.com/rust-lang/rustc-dev-guide b21d99b770f9aceb0810c843847c52f86f45d2ed
```

r? @jieyouxu

### CODE REVIEW

**Comment by ehuss** [comment]
Before merging this, can you please coordinate with me to get the automation and such ready?
Also, it would be good to know who will be responsible for keeping this in sync.

**Comment by Kobzol** [comment]
I probably do not intend to merge this PR :grin: It's mostly just for testing and discussions. Once we figure out the right way forward and prepare the automation, I'll probably create another one.

**Comment by ehuss** [comment]
You might also want to update the [`RustcGuide`](https://github.com/rust-lang/rust/blob/f6cb952dc115fd1311b02b694933e31d8dc8b002/src/bootstrap/src/core/build_steps/test.rs#L2530) test step to not require a submodule. I don't know if that test step is actually functional right now, since it currently is unused. But might as well fix that just in case someone wants to get it working again.

(Or just remove `RustcGuide`, I don't know how likely it is anyone will be using it in the future. 🤷 )

**Comment by Kobzol** [comment]
Yeah, I did that in the last few commits, forgot to push them before. The `RustcGuide` step was completely useless before, it was using a `mdbook linkcheck` command that hasn't existed for a while.

I added a `doc src/doc/rustc-dev-guide` step, but when the linkchecker runs on it, it fails, because rustc-dev-guide currently disables its linkchecker due to some bugs :/

**Comment by Kobzol** [comment]
Closing in favour of https://github.com/rust-lang/rust/pull/134907.

**Pull request closed without merging**
