### PR TITLE
Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #70201 (Small tweaks in ToOwned::clone_into)
 - #70762 (Miri leak check: memory reachable through globals is not leaked)
 - #70846 (Keep codegen units unmerged when building compiler builtins)
 - #70854 (Use assoc int submodules)
 - #70857 (Don't import integer and float modules, use assoc consts 2)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never p=5

In the meantime...

**Comment by Dylan-DPC** [comment]
ah the lucky one :D

**Pull request merged**
