### PR TITLE
stabilize #[panic_handler]

### LINKED ISSUE #44489: Tracking issue for RFC 2070: stable mechanism to specify the behavior of panic! in no-std applications
### Update(2018-08-28)

- [Stabilization summary](https://github.com/rust-lang/rust/issues/44489#issuecomment-416645946).
- [FCP checkboxes](https://github.com/rust-lang/rust/issues/44489#issuecomment-398965881)

---

This is a tracking issue for the RFC "stable mechanism to specify the behavior of panic! in no-std applications " (rust-lang/rfcs#2070).

**Steps:**

- [x] Implement the RFC
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
  - [ ] The doc-comment of libcore mentions `rust_begin_panic`
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

## `fmt::Display`

Should the `Display` of `PanicInfo` format the panic information as `"panicked
at 'reason', src/main.rs:27:4"`, as `"'reason', src/main.rs:27:4"`, or simply as
`"reason"`.

## Unwinding in no-std

Is this design compatible, or can it be extended to work, with unwinding
implementations for no-std environments?

**Issues to solve before stabilization**

- [x] panic_implementation: Error message still talks about the panic_fmt lang item when missing #51341
- [x] panic_implementation: no_mangle attribute needed?  #51342 
- [x] `rust_begin_unwind` not emitted when crate-type = bin #51671

### PR DESCRIPTION
**Pull request by japaric**
closes #44489

### Update(2018-09-07)

This was proposed for stabilization in https://github.com/rust-lang/rust/issues/44489#issuecomment-398965881 and its FCP with disposition to merge / accept is nearly over. The summary of what's being stabilized can be found in https://github.com/rust-lang/rust/issues/44489#issuecomment-416645946

Documentation PRs:

- Reference. https://github.com/rust-lang-nursery/reference/pull/362
- Nomicon. https://github.com/rust-lang-nursery/nomicon/pull/75

---

`#[panic_implementation]` was implemented recently in #50338. `#[panic_implementation]` is basically the old `panic_fmt` language item but in a less error prone (\*) shape. There are still some issues and questions to sort out around this feature (cf. #44489) but this PR is meant to start a discussion about those issues / questions with the language team.

(\*) `panic_fmt` was not type checked; changes in its function signature caused serious, silent binary size regressions like the one observed in #43054

Some unresolved questions from #44489:

> Should the Display of PanicInfo format the panic information as "panicked at 'reason',
> src/main.rs:27:4", as "'reason', src/main.rs:27:4", or simply as "reason".

The current implementation formats `PanicInfo` as the first alternative, which is how panic messages are formatted by the `std` panic handler. The `Display` implementation is more than a convenience: `PanicInfo.message` is unstable so it's not possible to replicate the `Display` implementation on stable.

> Is this design compatible, or can it be extended to work, with unwinding implementations for
> no-std environments?

I believe @whitequark made more progress with unwinding in no-std since their last comment in #44489. Perhaps they can give us an update?

---

Another unresolved question is where this feature should be documented. The feature currently doesn't have any documentation.

cc @rust-lang/lang 
cc @jackpot51 @alevy @phil-opp

### CODE REVIEW

**Comment by steveklabnik** [comment]
> Another unresolved question is where this feature should be documented. The feature currently doesn't have any documentation.

At the very least, an issue needs to be opened on the reference. This isn't right for the book, and *maybe* for Rust By Example. I'm imagining that the embedded docs your WG is working on may want to include it too?

**Comment by alevy** [comment]
> This isn't right for the book

@steveklabnik it _isn't_ or _is_? If not then maybe at least the nomicon? This change basically turns implementing `panic` from dark magic to fairly accessible and would be really good to have an easy to find reference for it.

**Comment by nikomatsakis** [comment]
I would think this should live in the Rust Reference. I'd like to see using that as, well, the reference for Rust. =)

**Comment by whitequark** [comment]
> I believe @whitequark made more progress with unwinding in no-std since their last comment in #44489. Perhaps they can give us an update?

Unwinding works on no_std for me for a very long time, we use it in production. Is there anything specific you want to know?

I use unwinding with a custom personality function for the language I designed, but the Rust personality function would work in a completely identical way as it does not depend on the OS at all (the libc dependency in panic_unwind crate is just for the types) and only barely depends on the platform (it needs to know the register numbers that the landing pad uses and that's it).

**Comment by Havvy** [comment]
The documentation for this should be guide level in the nomicon and reference level in well, the reference.

**Comment by pietroalbini** [comment]
Ping from triage @nagisa! This PR needs your review.

**Comment by nagisa** [comment]
Is this really ready for stabilisation? The tracking issue still has references to a few issues that are, honestly, quite perplexing (for example why in the world `#[no_mangle]` is required).

Furthermore, I’m not entirely sure what are the steps before a stabilisation PR can be merged? I mildly recall having to go through a week of FCP? That would be for both T-libs (for approach, also initial issue is marked T-libs) and T-compiler (for implementation).

Lastly, if I remember well, documentation has to be ready at least in form of PRs for stabilisation? Comments indicate it is not quite ready yet.

**Comment by cramertj** [comment]
@nagisa Yes, before merging this PR a summary comment must be written on the tracking issue nominating the feature for FCP to stabilize and the stabilization must complete without new blocking objections.

**Comment by japaric** [comment]
@steveklabnik 

> I'm imagining that the embedded docs your WG is working on may want to include it too?

We'll certainly be documenting `#[panic_implementation]` in the embedded book, which is geared towards people that want to learn how to do embedded Rust, as lots of people will have to deal with it. More obscure stuff, like #[used], (that most devs won't have to directly deal with) will go in the embedonomicon.

@whitequark 

> Unwinding works on no_std for me for a very long time, we use it in production. Is there anything specific you want to know?

Yes. Basically, does your unwinding implementation continue to work with #[panic_implementation]?

Less on-topic: could you point me to your unwinding implementation? I'd like to write documentation on how to get unwinding working on no_std. Right now it's unclear (in the docs I've seen) what eh_personality is for, how to compiler uses it and how it interacts with panic_fmt / panic_impl (if at all).

@nagisa 

> The tracking issue still has references to a few issues that are, honestly, quite perplexing (for example why in the world #[no_mangle] is required).

The #[no_mangle] issue that was reported looks like #51647 to me which, AFAICT, is the oom lang item undoing #49316 and not a #[panic_implementation] issue. Can't really tell as the issue is scarce on details, but I haven't required #[no_mangle] in any of my uses of #[panic_implementation] (I'm not using #[global_allocator] or the oom lang item though).

> Lastly, if I remember well, documentation has to be ready at least in form of PRs for stabilisation?

I'll prep a PR for the reference and the nomicon.

---

So far it sounds like there are no concerns with the feature itself or its syntax. Can we start the FCPbot thing to have the appropriate team confirm that there are no concerns? cc @nikomatsakis

**Comment by nagisa** [comment]
I'll fcpbot this evening.

**Comment by japaric** [comment]
Documentation PRs: rust-lang-nursery/reference#362 and rust-lang-nursery/nomicon#75

**Comment by pietroalbini** [comment]
Ping from triage @nagisa! You need to fcpbot this.

**Comment by stokhos** [comment]
ping from triage @nagisa , will you have time to review this?

**Comment by nagisa** [comment]
The FCP is ongoing on the issue thread. Please stop pinging here.

**Comment by japaric** [comment]
To clear the PR queue, I'm going to close this until the FCP period is over.

**Comment by japaric** [comment]
@Mark-Simulacrum rebased and (should be) ready to go. The reference PR is up at rust-lang-nursery/reference#362

**Comment by Mark-Simulacrum** [comment]
If you could update the PR description to reflect the current state, r=me. I think the process allows landing stabilization so long as there are open PRs documenting it...

**Comment by steveklabnik** [comment]
Not just PRs, but just an issue is sufficient.

**Comment by kennytm** [comment]
@bors retry 

```
Encountered a `SocketError` while attempting to connect to: (Aws::Errors::NoSuchEndpointError)
```

**Pull request merged**
