### PR TITLE
Fix invalid missing documentation lint reporting for re-exports

### LINKED ISSUE #108570: Invalid missing documentation for reexported item
Example:

```rust
mod priv_mod {
    pub struct Foo;
}

#[doc(hidden)]
pub use priv_mod::Foo;
```

With this code, we get:

```
error: missing documentation for a struct
```

Whereas we shouldn't since `Foo` is hidden.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/108570.

The problem was that, if an item is re-exported, we don't check if it's actually displayed into the documentation. To do so, I changed the check this way:

 * If it's directly public, check for it.
 * For re-exports, check the re-exported item directly.

Like that, if an item is re-exported, it'll just be checked on the re-export directly.

Not sure who should be set as reviewer here so I'll just ping @notriddle and wait for bors to assign someone.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Just discovered some weird re-exports on `cfg(test)`. I added `#[allow(missing_docs)]` on them.

**Comment by petrochenkov** [comment]
Is there any history behind these changes? What issues do they fix?
From the PR description it's entirely unclear what's going on.

Is this about documentation being lost on reexport items from other crates?
In that case it's something that needs to be actually fixed, not papered over by a lint.

**Comment by GuillaumeGomez** [comment]
Sorry, I forgot to link the issue... I'll update the first comment too. The issue: https://github.com/rust-lang/rust/issues/108570

**Comment by petrochenkov** [comment]
I've just found https://github.com/rust-lang/rust/issues/108570 too.

So it's not about dropped docs, but about making the `missing_docs` lint in rustc more in sync with doc hiding in rustdoc.
That means duplicating all the doc hiding logic from rustdoc in rustc, I'm not entirely sure it's a good idea, but I'll check in more details in the next few days.

**Comment by GuillaumeGomez** [comment]
If you have suggestions on how to prevent this duplication (which I'm not super happy about either...), I'd gladly hear it. :wink:

**Comment by petrochenkov** [comment]
In the meantime let's do a perf run.
@bors try @rust-timer queue

**Comment by GuillaumeGomez** [comment]
That's quite the regression. I need to check how to improve this situation.

**Comment by petrochenkov** [comment]
I suggest not spending time on attempts to improve the current approach.
Using `hir::ItemKind::Use` is almost never a good idea, both in rustc and rustdoc.
For example, neither `use_path.res.last()` for single imports, nor `for child in cx.tcx.hir().module_items(res_def_id)` are correct, even if they lead to results resembling the truth.

The `module_reexports` needs to be used instead, but it doesn't return enough information.
I'll check what additional data `ModChild` need to contain and try to add them, it may be helpful in other places too.

**Comment by GuillaumeGomez** [comment]
Sounds good to me, thanks! Closing then.

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
By the way, is behavior of `doc(hidden)` documented anywhere?

- What nodes support it
- When it is applied recursively and when not?
- Can a `doc(hidden)` item be un-hidden through a non-hidden reexport?
- etc.

I thought I had some understanding, but then https://github.com/rust-lang/rust/pull/107000 and related PRs changed the rules again.

**Comment by GuillaumeGomez** [comment]
It's not documented anywhere but it really should. I'll try to update the rustdoc book today so the rules of re-exports and `doc(hidden)` are written down somewhere and can be used as reference.

**Pull request closed without merging**
