### PR TITLE
remove `hex` dependency in bootstrap

### PR DESCRIPTION
**Pull request by onur-ozkan**
First commit removes the `hex` dependency, as we can achieve the same output with the added function, which is very small and simple.

Second commit creates a test module for the helpers util and adds unit tests for multiple helper functions, including `hex_encode`.

### CODE REVIEW

**Review by albertlarsan68 — APPROVED** [review]
LGTM
@bors r+ rollup
Let's see if this works :)

**Comment by onur-ozkan** [comment]
Doesn't work, I tried that too before :)

**Comment by albertlarsan68** [comment]
@bors r+ rollup
A thing to edit in old bors, and to make sure works in new bors!

**Comment by onur-ozkan** [comment]
@bors r-

I think this will fail due to unused import because of the unix specific test.

**Comment by onur-ozkan** [comment]
Fixed https://github.com/rust-lang/rust/compare/fe897ede7b0b9598cf7282c56f971a8f38d7a07c..87b5cbcb305755e6f7033670b68840076da75e79

@bors r=albertlarsan68

**Comment by est31** [comment]
@bors r- [failed in rollup](https://github.com/rust-lang/rust/pull/119030#issuecomment-1859006867):

```
error: unused import: `env`
##[error] --> src\utils\..\tests\helpers.rs:2:11
  |
2 | use std::{env, path::PathBuf};
  |
  = note: `-D unused-imports` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(unused_imports)]`
```

**Pull request merged**
