### PR TITLE
Remove io::Result from syntax::print

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Since we're now writing directly to the vector, there's no need to
thread results through the whole printing infrastructure

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@rust-timer build c81fc323f8dab75a771421438e9aeddd8be1b476

**Comment by eddyb** [comment]
If possible, I'd prefer if `Vec<u8>` was replaced with `String`.

**Comment by petrochenkov** [comment]
Why was `Vec` chosen in the first place?
I suspect that the output of the pretty-printer is never used as a string, only dumped somewhere as bytes.
However the output actually contains UTF-8 and extending a `String` with another string is no more expensive than pushing into a vector, so why not keeping the invariant just in case 👍

**Comment by petrochenkov** [comment]
Should we close https://github.com/rust-lang/rust/pull/62098 and merge this instead?

**Comment by Mark-Simulacrum** [comment]
This is only split off because of the large diff in the last commit; we can merge just it or separately, doesn't matter to me.

I only chose Vec because it was what we were already passing in, I'll work on replacing it with String. Should be very simple.

**Comment by Mark-Simulacrum** [comment]
I've gone ahead and closed #62098; this is updated with the code using `String` instead of `Vec<u8>` now. Note that there's a number of entirely new commits as well; I can split this into multiple PRs if that would ease review, just let me know.

**Comment by Mark-Simulacrum** [comment]
This is ready for review.

**Review by eddyb — APPROVED** [review]

**Pull request merged**
