### PR TITLE
Fix clippy lints

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I'm currently working on allowing clippy to run on librustdoc after a discussion I had with @Mark-Simulacrum. So in the meantime, I fixed a few lints on the compiler crates.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems spurious...

@bors retry

**Comment by GuillaumeGomez** [comment]
Seems like there is a small perf regression, no?

**Comment by Mark-Simulacrum** [comment]
Indeed, our heuristics did not deem this definite, but did consider it probable. [We're working on those](https://github.com/rust-lang/rustc-perf/issues/983).

Tagging as a regression. Likely to be painful to investigate, but we'll see.

**Pull request merged**
