### PR TITLE
Implement `unused_parens` for trailing return value

### LINKED ISSUE #68386: `unused_parens` doesn't fire for trailing return expression
```rust
fn foo() -> u32 {
    let _ = (5); //~ LINT unnecessary parentheses around assigned value
    (5) // no lint
}
```

### PR DESCRIPTION
**Pull request by Tyg13**
Fixes #68386

r? @varkor

### CODE REVIEW

**Review by Centril — APPROVED** [review]
r=me with the second merge commit squashed into the first.

**Comment by Tyg13** [comment]
Apologies, I seem to have seriously messed up my git-fu somewhere

**Comment by Tyg13** [comment]
I think I'll just re-open the PR. Seems cleaner that way

**Pull request closed without merging**
