### PR TITLE
macros: Make metavariables hygienic

### LINKED ISSUE #35450: macros: metavariables in `tt` fragments can hang
@durka reported this in https://github.com/rust-lang/rust/pull/34925#issuecomment-237141409.
```rust
macro_rules! m { ($t:tt) => { $t } }
m!($t); //< This expansion hangs.
```

### PR DESCRIPTION
**Pull request by jseyfried**
This PR makes metavariables hygienic. For example, consider:

``` rust
macro_rules! foo {
    ($x:tt) => { // Suppose that this token tree argument is always a metavariable.
        macro_rules! bar { ($x:expr, $y:expr) => { ($x, $y) } }
    }
}

fn main() {
    foo!($z); // This currently compiles.
    foo!($y); // This is an error today but compiles after this PR.
}
```

Today, the `macro_rules! bar { ... }` definition is only valid when the metavariable passed to `foo` is not `$y` (since it unhygienically conflicts with the `$y` in the definition of `bar`) or `$x` (c.f. #35450).

After this PR, the definition of `bar` is always valid (and `bar!(a, b)` always expands to `(a, b)` as expected).

This can break code that was allowed in #34925 (landed two weeks ago). For example,

``` rust
macro_rules! outer {
    ($t:tt) => {
        macro_rules! inner { ($i:item) => { $t } }
    }
}

outer!($i); // This `$i` should not interact with the `$i` in the definition of `inner!`.
inner!(fn main() {}); // After this PR, this is an error ("unknown macro variable `i`").
```

Due to the severe limitations on nested `macro_rules!` before #34925, this is not a breaking change for stable/beta.

Fixes #35450.

r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @durka

**Comment by durka** [comment]
LLVM didn't build?

**Comment by alexcrichton** [comment]
@bors: retry

* not sure...

**Comment by durka** [comment]
error[E0308]: mismatched types
       --> C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src/test\run-pass-fulldeps\auxiliary\procedural_mbe_matching.rs:39:22
        |
     39 |             match (&*map[&str_to_ident("matched").name], &*map[&str_to_ident("pat").name]) {
        |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `syntax::ast::Ident`, found struct `syntax::ast::Name`
        |
        = note: expected type `&syntax::ast::Ident`
        = note:    found type `&syntax::ast::Name`
     
     error[E0308]: mismatched types
       --> C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src/test\run-pass-fulldeps\auxiliary\procedural_mbe_matching.rs:39:60
        |
     39 |             match (&*map[&str_to_ident("matched").name], &*map[&str_to_ident("pat").name]) {
        |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `syntax::ast::Ident`, found struct `syntax::ast::Name`
        |
        = note: expected type `&syntax::ast::Ident`
        = note:    found type `&syntax::ast::Name`
     
     error: aborting due to 2 previous errors

**Comment by jseyfried** [comment]
@durka Thanks!
@bors r+

**Comment by durka** [comment]
So... this is a syntax-breaking change if there is test fallout (sorry).

**Comment by eddyb** [comment]
cc @Manishearth

**Comment by jseyfried** [comment]
@durka Good point.
@bors r- (unless @Manishearth's says this isn't actually a syntax-[breaking-change] in practice)

**Comment by Manishearth** [comment]
I think so. @erickt whatsay?

**Comment by Manishearth** [comment]
We're gettign a pile of PRs that will break aster (and only aster) right now though. So it might be good to do a rollup. OTOH there's a bunch of diagnostics work coming up which I'd like to include.

**Comment by dtolnay** [comment]
This PR does not affect quasi/aster. For the others - I have time in the next two weeks to deal with fallout so this would be a good time. Thanks for the heads up.

**Comment by Manishearth** [comment]
Cool. @GuillaumeGomez could you get all libsyntax refactors necessary for diagnostics in now?

**Comment by alexcrichton** [comment]
@bors: retry force clean

* restarted buildbot

**Pull request merged**
