### PR TITLE
Remove unnecessary `unsafe { <...> }` blocks.

### PR DESCRIPTION
**Pull request by Jerrody**

### CODE REVIEW

**Comment by compiler-errors** [comment]
I think it's probably best to keep these around. See: https://rust-lang.github.io/rfcs/2585-unsafe-block-in-unsafe-fn.html

**Comment by Jerrody** [comment]
Strange.

**Comment by Jerrody** [comment]
If this flag is set, so I decline the PR.

**Comment by Jerrody** [comment]
> I think it's probably best to keep these around. See: https://rust-lang.github.io/rfcs/2585-unsafe-block-in-unsafe-fn.html

Yep, I saw this error.

**Pull request closed without merging**
