### PR TITLE
Revert "Rollup merge of #78934 - DeveloperC286:issue_60302_vec, r=m-ou-se"

### PR DESCRIPTION
**Pull request by rylev**
This is the second attempt to find the cause of the perf regression in the rollup https://github.com/rust-lang/rust/pull/80530. It reverts #78934. 

r? @ghost 

This reverts commit 242a252687264e1115dbfa5f2b4890a35d224a05, reversing
changes made to 507bff92fadf1f25a830da5065a5a87113345163.

### CODE REVIEW

**Comment by rylev** [comment]
Screenshot 2021-01-08 at 17 14 43

This seems to be the likely culprit.

**Comment by Mark-Simulacrum** [comment]
Yeah, I'm guessing this is something we should just led slide for now - seems to be CGU partitioning and I don't think it's worth reverting.

**Comment by rylev** [comment]
I think we should investigate the cause of the perf issues, but I agree there's no reason to actually revert this change.

**Pull request closed without merging**
