### PR TITLE
rustfmt: load nested out-of-line mods correctly

### PR DESCRIPTION
**Pull request by calebcartwright**
This should address https://github.com/rust-lang/rustfmt/issues/4874

r? @Mark-Simulacrum 

Decided to make the change directly in tree here for expediency/to minimize any potential backporting issues, and because there's some subtree sync items I need to get resolved before pulling from r-l/rustfmt

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Nominating for beta-backport; we will (at least) want this fixed on 1.54. I am not sure about this warranting a stable backport, so will hold off there -- more testing on nightly seems warranted.

**Comment by apiraino** [comment]
@Mark-Simulacrum any `T-` label for this patch to decide for the backport - or is this under control?

**Comment by Mark-Simulacrum** [comment]
I would say compiler is probably best team but ultimately we can likely unilaterally accept this otherwise.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/238009tcompilermeetings/39906weekly2021062454818.html#243791960)

@rustbot label +beta-accepted

**Pull request merged**
