### PR TITLE
resolve: Remove artificial import ambiguity errors

### LINKED ISSUE #56414: Ambiguity errors in 2018 uniform import paths are not technically necessary
Right now import resolution on 2018 edition fails with an ambiguity error if multiple candidates are found:
```rust
struct S; // Outer

fn main() {
    struct S; // Inner

    use S as Z; // ERROR `S` is ambiguous (name vs any other name during import resolution)

    let s = S; // OK, the Inner S is preferred
}
```

This is different from non-import paths in which resolutions from closer scopes are preferred without errors.

This restriction is technically unnecessary and exists because some people were uncomfortable with disambiguation happening in import paths specifically (see previous threads, ... many of them, https://github.com/rust-lang/rust/issues/55618 being the latest one).

This restriction can be lifted fully or partially if it causes too much trouble in practice with ambiguity errors, or with addition of new names to libraries being backward-incompatible due to new ambiguities.

(By "partially" I mean e.g. "disambiguation is okay, unless one of the candidates is an extern crate" or something like that.)

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/56414.

FCP report: https://github.com/rust-lang/rust/pull/112086#issuecomment-1568713662

### CODE REVIEW

**Comment by petrochenkov** [comment]
### Change description for the lang team.

This PR removes unconditional errors that are currently reported if more than one candidate for a name is found during resolution of a `use` item.

Before this PR:
```rust
struct S; // Outer

fn main() {
    struct S; // Inner

    use S as _; // ERROR `S` is ambiguous

    let s = S; // OK, the Inner `S` is preferred
}
```

After this PR:
```rust
struct S; // Outer

fn main() {
    struct S; // Inner

    use S as _; // OK, the Inner `S` is preferred

    let s = S; // OK, the Inner `S` is preferred
}
```

These errors are not technically necessary, but they were implemented in 2018 together with the new import semantic because some people were uncomfortable with name shadowing working in imports specifically.

Now we are living with the new import resolution rules for nearly 5 years already, and it should be reasonable to expect that name shadowing that is possible in any other contexts is possible in import contexts too.

Removal of these errors reduces chances of breaking changes when adding any new names to preludes, with `#[diagnostic::foo]` attributes (https://github.com/rust-lang/rfcs/pull/3368) being a recent example of such addition.

Other ambiguity errors that may be reported during import resolution (glob vs macro-expanded name, etc) and that are actually necessary to prevent things like time travel, are not removed.

**Review by estebank — APPROVED** [review]

**Comment by est31** [comment]
> Other ambiguity errors that may be reported during import resolution (glob vs macro-expanded name, etc) and that are actually necessary to prevent things like time travel, are not removed.

``` Rust
struct S;

mod foo { pub struct S; }

fn main() {
    use self::foo::*;
    
    use S as _; // ERROR `S` is ambiguous
    
    let _ = S;
}
```

So this, using a glob import, will still be erroring?

**Comment by petrochenkov** [comment]
@est31 
I think this specific case will error with
```rust
  = note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6492f42d9a13a034d74a720e219b516d
(It's a part of the "time travel" prevention.)

**Comment by scottmcm** [comment]
I was a bit confused by the `_` in the example, but if I'm understanding correctly, it's just showing that the `use` resolution is different from the in-a-type resolution.

I see that this also fails today
```rust=
mod foo { pub struct S; }

fn main() {
    mod foo { pub struct S; }

    use foo::S; // error[E0659]: `foo` is ambiguous

    let s = S;
}
```

which I assume would also be resolved by this.

But in general, today's meeting discussion seemed positive towards making the use lookup consistent with the type lookup, so

@rfcbot fcp merge

**Comment by oli-obk** [comment]
r? @oli-obk 

r=me (needs a rebase)

**Pull request merged**
