### PR TITLE
Introduce `as_slice`/`as_mut_slice` methods on `std::vec::IntoIter` struct.

### PR DESCRIPTION
**Pull request by frewsxcv**
Similar to the `as_slice` method on `core::slice::Iter` struct.

### CODE REVIEW

**Comment by apasel422** [comment]
This could also have `as_slice_mut`, no? Would it be better to implement `{AsRef, AsMut}` instead?

**Comment by frewsxcv** [comment]
> This could also have as_slice_mut, no?

I think so. I can add it in.

> Would it be better to implement {AsRef, AsMut} instead?

This works for me too; if anyone has strong opinions on this let me know. `core::slice::Iter` seems to implement just `as_slice`. `std::vec::Vec` seems to implement `as_slice` and `AsRef`.

**Comment by eddyb** [comment]
Aren't trait impls insta-stable?

**Comment by alexcrichton** [comment]
@bors: r+ 

Discussed during libs triage and we were ok, thanks @frewsxcv!

**Comment by alexcrichton** [comment]
@bors: r-

Er wait actually, could you open a tracking issue for these methods and update the unstable issue reference?

**Comment by frewsxcv** [comment]
> Er wait actually, could you open a tracking issue for these methods and update the unstable issue reference?

Done.

```diff
diff --git a/src/libcollections/vec.rs b/src/libcollections/vec.rs
index bce1fca..a6f817a 100644
--- a/src/libcollections/vec.rs
+++ b/src/libcollections/vec.rs
@@ -1726,7 +1726,7 @@ impl<T> IntoIter<T> {
     /// let _ = into_iter.next().unwrap();
     /// assert_eq!(into_iter.as_slice(), &['b', 'c']);
     /// ```
-    #[unstable(feature = "vec_into_iter_as_slice", issue = "0")]
+    #[unstable(feature = "vec_into_iter_as_slice", issue = "35601")]
     pub fn as_slice(&self) -> &[T] {
         unsafe {
             slice::from_raw_parts(self.ptr, self.len())
@@ -1747,7 +1747,7 @@ impl<T> IntoIter<T> {
     /// assert_eq!(into_iter.next().unwrap(), 'b');
     /// assert_eq!(into_iter.next().unwrap(), 'z');
     /// ```
-    #[unstable(feature = "vec_into_iter_as_slice", issue = "0")]
+    #[unstable(feature = "vec_into_iter_as_slice", issue = "35601")]
     pub fn as_mut_slice(&self) -> &mut [T] {
         unsafe {
             slice::from_raw_parts_mut(self.ptr, self.len())
```

**Comment by alexcrichton** [comment]
@bors: r+ 

Thanks!

**Comment by apasel422** [comment]
The switch from `*const T` to `*mut T` caused `vec::IntoIter<T>` to go from covariant in `T` to invariant in `T`, which is a breaking change. (See contain-rs/vec-map#18.)

I thought we had tests for this.

**Comment by sfackler** [comment]
https://github.com/rust-lang/rust/issues/39465

**Pull request merged**
