### PR TITLE
Fixes #39661

### LINKED ISSUE #39661: BTreeMap documentation improvement
On the page https://doc.rust-lang.org/std/collections/index.html there is a comparison of the collection types in the standard library and it says under "Use a BTreeMap when:" "You want a sorted map.".

It was not immediately clear to me that the map's Key/Value pairs are in fact sorted by its keys. This was only fully clarified by asking the helpful folks over on IRC.

Steve Klabnik then encouraged me to open an issue here asking for a change in the docs clarifying the point made above.

This point in the list/comparison should probably say something more like
"You want a map sorted by its keys."
to avoid any unnecessary ambiguity.

### PR DESCRIPTION
**Pull request by Henning-K**
Clarifies the potential ambiguity.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Looks great! Thank you so much!

@bors: r+ rollup

**Comment by euclio** [comment]
Hm, I think there should be an article before "map".

**Comment by Henning-K** [comment]
@euclio Ah, missed that. How about "a"?

**Comment by frewsxcv** [comment]
Looks good, thanks for your contribution!

@bors r+ rollup

**Pull request merged**
