### PR TITLE
Detect likely `for foo of bar` JS syntax

### LINKED ISSUE #75311: Provide auto-fix suggestion for for..of loop
Been working in JavaScript a lot lately and find myself accidentally typing this a lot. It would be nice to automatically detect this and offer a proper fix. For those who don't know, in JavaScript, `for..of` uses the iterator API, whereas `for..in` iterates over the keys in an object.

Playground example below.

```rust
fn main() {
    for x of &[1, 2, 3] {
        println!("{}", x);
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f1bbc18b2d40155c152bea9073346f14))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: missing `in` in `for` loop
 --> src/main.rs:2:10
  |
2 |     for x of &[1, 2, 3] {
  |          ^ help: try adding `in` here

error[E0425]: cannot find value `of` in this scope
 --> src/main.rs:2:11
  |
2 |     for x of &[1, 2, 3] {
  |           ^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

### PR DESCRIPTION
**Pull request by estebank**
Fix #75311.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks good! But I'm not sure if I could r+ here as I'm not a part of the compiler team or its contributors officially. r=me if you think it's okay :)

**Review by davidtwco — APPROVED** [review]
LGTM!

**Pull request merged**
