### PR TITLE
Add {Add,Sub,Mul,Div,Rem,BitXor,BitOr,BitAnd}{,Assign}<$t> to Saturat…

### PR DESCRIPTION
**Pull request by kellerkindt**
Tracking issue #92354

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Regression is in doc builds, which is probably to be expected -- rustdoc is dependent on the whole all trait impls for each compilation rather than anything more local today, and this is adding a lot of trait impls.

r? @dtolnay as this is a fairly extensive expansion of library surface area. The impl itself seems OK, I think, but could use another set of eyes to to confirm. I felt particularly unsure about the Rem impl (I think it does the right thing though).

**Review by dtolnay — APPROVED** [review]
I am on board with this. Thanks!

**Comment by m-ou-se** [comment]
@kellerkindt for next time: When you're changing/expanding an existing unstable feature (like `Saturating`), it's usually better to re-use the same tracking issue. Tracking different parts of such a feature in different tracking issues makes them harder to track.

**Comment by kellerkindt** [comment]
Alright. I wasn't sure whether the stabilization of `saturating_int_assign_impl` would lead to a bigger discussion and I didn't want to block the main type `Saturating` from being stabilized that way. I wasn't aware of #55436.

Thank you for the info.

**Pull request merged**
