### PR TITLE
Rename never_type_impls gate

### PR DESCRIPTION
**Pull request by canndrew**
We no longer need a separately-named `never_type_impls` gate thanks to https://github.com/rust-lang/rust/issues/43089.

### CODE REVIEW

**Comment by canndrew** [comment]
Note: This PR builds on https://github.com/rust-lang/rust/pull/46232

**Comment by petrochenkov** [comment]
Stability attributes on impls are documentation-only, so this doesn't seem harmful in any way.
r=me after https://github.com/rust-lang/rust/pull/46232 is approved

**Comment by kennytm** [comment]
#46232 has been merged.

**Comment by petrochenkov** [comment]
Needs rebase
@bors delegate+

**Pull request merged**
