### PR TITLE
Implement Debug for DirEntry.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by sfackler** [comment]
Thanks!

@bors r+

**Comment by frewsxcv** [comment]
Updated. @sfackler can I get another r?

**Comment by jonathandturner** [comment]
@bors r-

Removing it since it seems like it fails on Windows (tried it during a rollup).

```
test fs::tests::dir_entry_debug ... FAILED
test fs::tests::dir_entry_methods ... ok
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `"DirEntry(\"C:\\\\Users\\\\RUSTBU~1\\\\AppData\\\\Local\\\\Temp\\\\rust-3438732025\\\\b\")"`, right: `"DirEntry(\"C:\\Users\\RUSTBU~1\\AppData\\Local\\Temp\\rust-3438732025\\b\")"`)', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\libstd\fs.rs:2662
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by frewsxcv** [comment]
Uh, if anyone has insight why Windows renders path with `\\\\`, information would be greatly appreciated

**Comment by Aatch** [comment]
@frewsxcv your debug impl will format the inner string using the Debug format. Whereas your test uses Display.

**Comment by frewsxcv** [comment]
I think I fixed it. Can I get a re-review?

**Pull request merged**
