### PR TITLE
Re-export core::str::{EscapeDebug, EscapeDefault, EscapeUnicode} in std

### PR DESCRIPTION
**Pull request by tesuji**
cc #59893

### CODE REVIEW

**Comment by pietroalbini** [comment]
cc @rust-lang/release 
@rustbot modify labels: beta-nominated and stable-nominated.

**Comment by SimonSapin** [comment]
@pietroalbini what does stable-nominated mean? This change is low-risk, but definitely not worth making a 1.34.1 release on its own. (Unlike `NonZeroI32` and friends, typical usage of these types does not require naming them: they are return types for inherent methods of `str`.)

**Comment by pietroalbini** [comment]
Yep, it's not worth making a point release on its own, but there are also two beta regression ICEs that slipped in 1.34.0. The release team will decide if it's worth making a point release with this change and the two fixes in the meeting today (20:00 UTC, #release on discord).

**Comment by pietroalbini** [comment]
@rust-lang/libs the release team agreed to release 1.34.1 on Thursday 25th, do you think this PR is safe to backport?

**Comment by SimonSapin** [comment]
Yes I would call it safe. But also of only small benefit in extremely niche situations.

**Comment by SimonSapin** [comment]
The libs team accepted backporting to beta in today’s triage meeting. However we feel that including this in the 1.34.1 release and in the accompanying blog post seems excessive, it’s not worth so much attention.

**Pull request merged**
