### PR TITLE
Handle `rustc_hir_analysis` cases of `potential_query_instability` lint

### PR DESCRIPTION
**Pull request by ismailarilik**
This PR removes `#![allow(rustc::potential_query_instability)]` line from [`compiler/rustc_hir_analysis/src/lib.rs`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir_analysis/src/lib.rs#L61) and converts `FxHash{Map,Set}` types into `FxIndex{Map,Set}` to suppress lint errors.

A somewhat tracking issue: https://github.com/rust-lang/rust/issues/84447

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
These look good, and I doubt they will cause perf issues. I think I may have introduced those GAT usages of hashmaps lol.

**Comment by compiler-errors** [comment]
r=me (in rust parlance, i will approve) after the perf run comes back.

**Comment by compiler-errors** [comment]
👍 
@bors r+ rollup

**Comment by ismailarilik** [comment]
@compiler-errors I know somehow performance is improved in this PR but I think we can improve it further by removing unnecessary sorts. They were exist to make the related sets stable but it isn't necessary anymore. And also we can make them immutable so more secure. The PR for this: https://github.com/rust-lang/rust/pull/131328

**Pull request merged**
