### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by brson**
Backports of 
- https://github.com/rust-lang/rust/pull/37112
- https://github.com/rust-lang/rust/pull/37129

Don't merge until both are accepted.

### CODE REVIEW

**Comment by brson** [comment]
cc @rust-lang/compiler can you review the linked PRs and see if they are appropriate for beta? If so I will also include them in the [stable backport](https://github.com/rust-lang/rust/pull/37173).

**Comment by nrc** [comment]
@brson why do these need backporting to stable? It looks like they should only get backported to beta.

I've been meaning to backport this PR too: https://github.com/rust-lang/rust/pull/36995 I'd be super happy if someone beats me to it.

**Comment by brson** [comment]
@nrc They both fix issues tagged as stable regressions, and we're going to do a stable point release.

That doesn't mean they must be backported to stable. We can decide not to. To that end I would love feedback on https://github.com/rust-lang/rust/pull/37173, where I am trying to prepare the point release.

**Comment by nikomatsakis** [comment]
@brson r+ looks good to me, should I just merge?

**Comment by brson** [comment]
@nikomatsakis thanks, yeah just merge, but i'll get it

**Pull request merged**
