### PR TITLE
Convert warning about `*const _` to a future-compat lint

### LINKED ISSUE #46837: E0619 diagnostic occurs twice in rustc source
PR #46664 injected a second use of E0619.

This causes a warning at compile-time for `rustc_typeck`: 

```
   Compiling rustc_typeck v0.0.0 (file:///home/pnkfelix/Dev/Mozilla/rust-mirborrowck/src/librustc_typeck)
warning: diagnostic code E0619 already used
    --> /home/pnkfelix/Dev/Mozilla/rust-mirborrowck/src/librustc_typeck/check/mod.rs:4962:21
     |
4962 | /                     type_error_struct!(self.tcx.sess, sp, ty, E0619,
4963 | |                                        "the type of this value must be known in this context")
     | |______________________________________________________________________________________________^
     |
note: previous invocation
    --> /home/pnkfelix/Dev/Mozilla/rust-mirborrowck/src/librustc_typeck/check/method/probe.rs:328:25
     |
328  | /                         struct_span_warn!(self.tcx.sess, span, E0619,
329  | |                             "the type of this value must be known in this context")
     | |___________________________________________________________________________________^
     = note: this error originates in a macro outside of the current crate
```

### PR DESCRIPTION
**Pull request by mikeyhew**
#46664 was merged before I could convert the soft warning about method lookup on `*const _` into a future-compatibility lint. This PR makes that change.

fixes #46837
tracking issue for the future-compatibility lint: #46906 

r? @arielb1

### CODE REVIEW

**Comment by arielb1** [comment]
Needs a rebase

**Comment by arielb1** [comment]
r=me with a rebase

**Comment by mikeyhew** [comment]
Oh true, I had a hunch this would cause an error because of `deny(warnings)`. I'll update libstd and push again

**Comment by arielb1** [comment]
Still errors in `rustc_data_structures`

**Comment by CAD97** [comment]
These further changes got my local copy (`x86_64-pc-windows-msvc`) to pass a local test:

`src/librustc_data_structures/array_vec.rs`
```diff
-141        let arr = &mut self.values as &mut [ManuallyDrop<_>];
+141        let arr = &mut self.values as &mut [ManuallDrop<<A as Array>::Element>];
...
-263        let arr = &mut source_array_vec.values as &mut [ManualyDrop<_>];
+263        let arr =
+264            &mut source_array_vec.values as &mut [ManuallyDrop<<A as Array>::Element>];
```

`src/libstd/sys/windows/fs.rs`
```diff
-773      let buf = &mut (*db).ReparseTarget as *mut _;
+773        let buf = &mut (*db).ReparseTarget as *mut c::WCHAR;
```

commit at https://github.com/CAD97/rust/commit/056370167a832165fba16b6350b3ffac686d23bc if you just want to add that to the PR.

**Comment by mikeyhew** [comment]
@CAD97 thanks! I develop on OSX, so would have had to wait for AppVeyor to fail before I could fix the windows errors

**Comment by arielb1** [comment]
doc test failure:
```
[01:12:44] ---- ptr.rs - ptr::*mut T::copy_from (line 1827) stdout ----
[01:12:44] 	error: the type of this value must be known in this context
[01:12:44]   --> ptr.rs:10:22
[01:12:44]    |
[01:12:44] 10 |     dst.as_mut_ptr().copy_from(ptr, elts);
[01:12:44]    |                      ^^^^^^^^^
[01:12:44]    |
[01:12:44] note: lint level defined here
[01:12:44]   --> ptr.rs:1:9
[01:12:44]    |
[01:12:44] 1  | #![deny(warnings)]
[01:12:44]    |         ^^^^^^^^
[01:12:44]    = note: #[deny(tyvar_behind_raw_pointer)] implied by #[deny(warnings)]
[01:12:44]    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
[01:12:44]    = note: for more information, see issue #46906 <https://github.com/rust-lang/rust/issues/46906>
[01:12:44] 
[01:12:44] thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:286:12
[01:12:44] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:12:44] 
[01:12:44] ---- ptr.rs - ptr::*mut T::copy_from_nonoverlapping (line 1866) stdout ----
[01:12:44] 	error: the type of this value must be known in this context
[01:12:44]   --> ptr.rs:10:22
[01:12:44]    |
[01:12:44] 10 |     dst.as_mut_ptr().copy_from_nonoverlapping(ptr, elts);
[01:12:44]    |                      ^^^^^^^^^^^^^^^^^^^^^^^^
[01:12:44]    |
[01:12:44] note: lint level defined here
[01:12:44]   --> ptr.rs:1:9
[01:12:44]    |
[01:12:44] 1  | #![deny(warnings)]
[01:12:44]    |         ^^^^^^^^
[01:12:44]    = note: #[deny(tyvar_behind_raw_pointer)] implied by #[deny(warnings)]
[01:12:44]    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
[01:12:44]    = note: for more information, see issue #46906 <https://github.com/rust-lang/rust/issues/46906>
[01:12:44] 
[01:12:44] thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:286:12
[01:12:44] 
[01:12:44] 
[01:12:44] failures:
[01:12:44]     ptr.rs - ptr::*mut T::copy_from (line 1827)
[01:12:44]     ptr.rs - ptr::*mut T::copy_from_nonoverlapping (line 1866)
```

**Pull request merged**
