### PR TITLE
Stabilize `arbitrary_enum_discriminant`

### LINKED ISSUE #60553: Tracking issue for RFC 2363, "Allow arbitrary enums to have explicit discriminants"
This is a tracking issue for the RFC "Allow arbitrary enums to have explicit discriminants" (rust-lang/rfcs#2363).

**Steps:**

- [x] Implement the RFC – https://github.com/rust-lang/rust/pull/60732
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [x] Stabilization PR – #86860

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions:**

1. [ ] Should discriminants of enumerations with fields be specified as variant attributes?
2. [ ] Should this apply only to enumerations with an explicit representation?

### PR DESCRIPTION
**Pull request by fee1-dead**
Closes #60553.

----

## Stabilization Report

_copied from https://github.com/rust-lang/rust/issues/60553#issuecomment-865922311_

### Summary

Enables a user to specify *explicit* discriminants on arbitrary enums.

Previously, this was hard to achieve:

```rust
#[repr(u8)]
enum Foo {
    A(u8) = 0,
    B(i8) = 1,
    C(bool) = 42,
}
```

Someone would need to add 41 hidden variants in between as a workaround with implicit discriminants.

In conjunction with [RFC 2195](https://github.com/rust-lang/rfcs/blob/master/text/2195-really-tagged-unions.md), this feature would provide more flexibility for FFI and unsafe code involving enums.

### Test cases

Most tests are in [`src/test/ui/enum-discriminant`](https://github.com/rust-lang/rust/tree/master/src/test/ui/enum-discriminant), there are two [historical](https://github.com/rust-lang/rust/blob/master/src/test/ui/parser/tag-variant-disr-non-nullary.rs) [tests](https://github.com/rust-lang/rust/blob/master/src/test/ui/parser/issue-17383.rs) that are now covered by the feature (removed by this pr due to them being obsolete).

### Edge cases

The feature is well defined and does not have many edge cases. 
One [edge case](https://github.com/rust-lang/rust/issues/70509) was related to another unstable feature named `repr128` and is resolved.

### Previous PRs

The [implementation PR](https://github.com/rust-lang/rust/pull/60732) added documentation to the Unstable Book, https://github.com/rust-lang/reference/pull/1055 was opened as a continuation of https://github.com/rust-lang/reference/pull/639.

### Resolution of unresolved questions

The questions are resolved in https://github.com/rust-lang/rust/issues/60553#issuecomment-511235271.

----

(someone please add `needs-fcp`)

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
> Closes #86858.

I think you meant #60553?

**Review by LeSeulArtichaut — APPROVED** [review]
The PR itself looks good to me

**Comment by fee1-dead** [comment]
> I think you meant #60553?

whoops, fixed.

**Comment by LeSeulArtichaut** [comment]
Re-assigning to a T-lang member: r? @joshtriplett

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

This feature looks reasonable to me, and I see that the stabilization report + docs are included.

**Comment by fee1-dead** [comment]
Is there anything that is blocking this from getting merged? Ping @joshtriplett

**Pull request merged**
