### PR TITLE
Stabilize library features for 1.18.0

### LINKED ISSUE #34417: LinkedList implementation violates aliasing rules
The nodes in `LinkedList` look like this:
```rust
struct Node<T> {
    next: Option<Box<Node<T>>>,
    prev: Option<Shared<Node<T>>>,
    value: T,
}
```

`Box` uses `Unique`, which requires that it "the referent of the pointer should not be modified without a unique path to the Unique reference". This effectively means that `Unique` doesn't allow aliases, but this rule violated by the `prev` pointer which point to the same node as a `Unique`.

While Rust currently doesn't give `noalias` semantics to `Unique`, this is planned in the future and will silently break `LinkedList`.

### LINKED ISSUE #36648: Tracking issue for retain() method for HashMap (`retain_hash_collection`)
The HashMap type does not have a retain method like the one in Vec.

### LINKED ISSUE #38863: Tracking issue for std::collections::binary_heap::PeekMut::pop

### LINKED ISSUE #38903: Tracking issue for Child::try_wait
Introduced in https://github.com/rust-lang/rust/pull/38866 this is a tracking issue for the `Child::try_wait` method.

This method attempts to wait for a child and collect its status but does not block. Questions for stabilization include:

* Is the method name suitable?
* Is the return type suitable? (`io::Result<T>` vs `io::Result<Option<T>>`)

### LINKED ISSUE #38980: Provide "peek" APIs to `std::net` sockets
# Summary
Provide "peek" APIs to `std::net` sockets, for example:
- `UdpSocket.peek()`
- `UdpSocket.peek_from()`
- `TcpStream.peek()`

These methods enable socket reads without side-effects. That is, repeated calls to `peek()` return identical data. This can be accomplished by providing the POSIX flag `MSG_PEEK` to the underlying socket read operations.

# Motivation
This is valuable in cases where a user wishes to validate *if* new data exists in the socket, without consuming that data completely. For example, a user may wish to use `peek()` as a method of polling the socket to find out if new messages are available (or to determine the amount of data available), before deferring to another function to do the actual work of reading and parsing the socket's data.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #38863
Closes #38980
Closes #38903
Closes #36648

r? @alexcrichton 

@rust-lang/libs

### CODE REVIEW

**Comment by WiSaGaN** [comment]
I think you mean "Closes #33417" instead of "Closes #34417"?

**Comment by sfackler** [comment]
Fixed, thanks

**Comment by alexcrichton** [comment]
Looks like some doc building failed? Other than that r=me, thanks @sfackler!

**Comment by ollie27** [comment]
I don't agree with stabilising `TryFrom` without `impl<T, U> TryFrom<U> for T where T: From<U>`. However if it really needs to be stabilised now for whatever reason then it should at least be properly documented. I'd like to see the documentation explaining at least the following:

1. Which types should get an impl of the form `TryFrom<T> for T`? For example, why is there `TryFrom<u8> for u8` but not `TryFrom<char> for char`?
2. Which `From<U> for T` impls should get a `TryFrom<U> for T` impl. For exmple, why is there `TryFrom<u8> for u32` but no `TryFrom<u8> for char`?
3. Do the error types for converting to a certain type have to be the same? That was implied by several comments in #33417 but `TryFrom<u8> for u32` and `TryFrom<&str> for u32` have different error types.

Some example impls and uses would also be nice.

**Comment by sfackler** [comment]
@ollie27 If people want to wait for however many months or years it takes for `!` to stabilize before landing `TryFrom`, then so be it, I've removed it from this PR - I'm done dealing with that mess. It's not even clear to me at this point that a single trait makes sense for all of the things we're asking of it. I'm frankly starting to think we should just deprecate and remove the whole thing.

**Comment by alexcrichton** [comment]
@sfackler it looks like tidy failed here, but I'm ok handling `TryFrom` elsewhere if you'd like. Want to fixup tidy and r=me?

**Comment by Mark-Simulacrum** [comment]
Looks like this is ready for another review; I think @sfackler removed `TryFrom` with `!` as the error but I'm not really sure...

**Comment by sfackler** [comment]
I just hopefully fixed tidy

**Comment by Mark-Simulacrum** [comment]
And the mighty tidy says ... no:

```
[00:02:25] tidy error: The Unstable Book has a 'library feature' section 'try_from' which doesn't correspond to an unstable library feature
[00:02:25] some tidy checks failed
[00:02:25] 
[00:02:25] 
[00:02:25] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/tidy" "/checkout/src" "--no-vendor"
[00:02:25] expected success, got: exit code: 1
[00:02:25] 
```

**Comment by Mark-Simulacrum** [comment]
```
[01:01:34] failures:
[01:01:34]     collections/hash/map.rs - collections::hash::map::HashMap<K, V, S>::retain (line 1233)
[01:01:34]     collections/hash/set.rs - collections::hash::set::HashSet<T, S>::retain (line 660)
[01:01:34]     net/tcp.rs - net::tcp::TcpStream::peek (line 345)
[01:01:34]     net/udp.rs - net::udp::UdpSocket::peek (line 640)
[01:01:34]     net/udp.rs - net::udp::UdpSocket::peek_from (line 114)
```

**Pull request merged**
