### PR TITLE
[beta] Process backports

### PR DESCRIPTION
**Pull request by emilyalbini**
Merged on master:

* #50648: Fix volatile_store and nontemporal_store
* #50735: rustc: don't trip an assertion for enums with present but uninhabited variants.
* #50693: typeck: Save the index of private fields
* #50748: Update stdsimd module
* #50694: Fix self referential impl Trait substitutions

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me once the latter lands, thanks so much again @pietroalbini!

**Comment by pietroalbini** [comment]
Also added https://github.com/rust-lang/rust/pull/50735, which was approved for backport and is waiting to be merged.

**Comment by pietroalbini** [comment]
Added https://github.com/rust-lang/rust/pull/50749 (needs to be merged on master).

**Comment by pietroalbini** [comment]
Also added #50694. It's already merged on master, and it needs to be accepted (it's a small fix to a bad enough bug, so why not include it into the beta release).

**Comment by pietroalbini** [comment]
Ok @alexcrichton, everything was merged. https://github.com/rust-lang/rust/pull/50694 is not accepted yet, so if you want to accept it you can just merge the PR, otherwise I'll remove the commit.

**Pull request merged**
