### PR TITLE
Do not set CC, CFLAGS, CXX, CXXFLAGS, AR, RANLIB in bootstrap, it breaks cross compilation

### PR DESCRIPTION
**Pull request by mati865**
Fixes https://github.com/rust-lang/rust/issues/57812

I tested it in AArch64 Ubuntu container with several days old tree to have all the tools buildable.

I did **not** test native builds (amd64 -> amd64), leaving it to CI.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
It looks like this was first introduced in https://github.com/rust-lang/rust/pull/45191 (cc @petrochenkov), and it looks like there's a number of other bare variables that need to get removed as well, it's not just `CC` but also things like `CXX` etc

**Comment by petrochenkov** [comment]
That PR moved `env("CC/CFLAGS/CXX/CXXFLAGS/AR/RANLIB")` from C code built during the bootstrap (libbacktrace, jemalloc) to rustbuild thus centralizing its treatment.

Things could change now with libbacktrace and jemalloc being built out of tree, perhaps bare `CC` and friends no longer need to be set, and target-specific variables `CC_target` are enough.

If CI passes with `env("CC/CFLAGS/CXX/CXXFLAGS/AR/RANLIB")` removed, then I'm happy with the change.

**Comment by mati865** [comment]
Okay, I'll update PR within 15-30 minutes.

**Comment by mati865** [comment]
I cannot test it until tomorrow or later today but I think it's ready for the next round of review.

**Pull request merged**
