### PR TITLE
Switch to our own mirror of libisl

### LINKED ISSUE #89593: Github builders fails to download `isl-0.20` for crossbuild
```
[ALL  ]    --2021-10-06 09:39:56--  http://isl.gforge.inria.fr/isl-0.20.tar.xz
[ALL  ]    Resolving isl.gforge.inria.fr (isl.gforge.inria.fr)... 128.93.193.15
[ALL  ]    Connecting to isl.gforge.inria.fr (isl.gforge.inria.fr)|128.93.193.15|:80... failed: Connection timed out.
[ALL  ]    Retrying.
```

see:
https://github.com/rust-lang/rust/pull/89495#issuecomment-935892254
https://github.com/rust-lang/rust/pull/89245#issuecomment-935943180

and other latest build fails.

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @pietroalbini 

Fixes https://github.com/rust-lang/rust/issues/89593

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors p=100

(making it obvious what the tree-reopening PR is)

**Comment by Manishearth** [comment]
@bors p=1000

oh, it already was the case, I looked at the wrong entry in the queue

**Comment by Manishearth** [comment]
```
2021-10-06T13:09:18.1288318Z [ERROR]    isl: download failed
2021-10-06T13:09:18.1288581Z 
2021-10-06T13:09:18.1288835Z [01:51] / 
2021-10-06T13:09:18.1289123Z [ERROR]  
2021-10-06T13:09:18.1289494Z 
2021-10-06T13:09:18.1289753Z [01:51] / 
2021-10-06T13:09:18.1290033Z [ERROR]  >>
2021-10-06T13:09:18.1290230Z 
2021-10-06T13:09:18.1290491Z [01:51] / 
2021-10-06T13:09:18.1291823Z [ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
2021-10-06T13:09:18.1292337Z 
2021-10-06T13:09:18.1292641Z [01:51] / 
2021-10-06T13:09:18.1293235Z [ERROR]  >>        called in step '(top-level)'
```

**Comment by camelid** [comment]
I think this PR can be closed now?

**Pull request closed without merging**
