### PR TITLE
Remove framework in `dataflow/mod.rs` in favor of "generic" one

### PR DESCRIPTION
**Pull request by ecstatic-morse**
This is the culmination of the work described in rust-lang/compiler-team#202. All dataflow analyses (including the one in `clippy`) have been ported to use the framework in `dataflow/generic`, which can efficiently handle both gen/kill and generic problems. This PR moves the framework in `dataflow/generic` to `dataflow/framework`, and removes the gen/kill framework in `dataflow/mod.rs`.

More comprehensive documentation for the new framework is tracked in rust-lang/rustc-guide#564.

`clippy` will need to change the path it uses to import the dataflow analysis traits.

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Ping @pnkfelix. I'll hold off on rebasing this again until it is reviewed since it is prone to merge conflicts.

**Comment by ecstatic-morse** [comment]
ping @pnkfelix 

This is just removing dead code and renaming some modules. Can you reassign if you're not going to get to this?

**Comment by ecstatic-morse** [comment]
Not sure what the hold up is. Can someone from @rust-lang/compiler review this?

r? @Mark-Simulacrum

**Review by eddyb — APPROVED** [review]

**Pull request merged**
