### PR TITLE
doc: this is exactly the same example as one on mudule level

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Yes, this is intentional. The one at the module level is there to help provide context, but when you're looking for information on a specific method, you also want to see examples there.

**Comment by tshepang** [comment]
Can we have a shorter example for the method?

**Comment by steveklabnik** [comment]
What about making it shorter would make it better?

**Comment by tshepang** [comment]
I don't like seeing the exact same example in one page.

**Pull request closed without merging**
