### PR TITLE
add long diagnostics for E0214

### PR DESCRIPTION
**Pull request by AlisdairO**
As title :-)
Part of #24407.

r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+ rollup

Thanks, and nice to see you back! How's it going with mini-you? :smile:

**Comment by AlisdairO** [comment]
V

**Comment by AlisdairO** [comment]
Cheers - unbelievably tiring, but otherwise great thanks! She's sleeping now so I thought I'd snag the opportunity to do some simple-ish work that I can actually comprehend ;)

**Comment by Manishearth** [comment]
Nice! Hope it all goes well; and hope you get more time to to more substantial things!

**Comment by AlisdairO** [comment]
Thank you :)

**Pull request merged**
