### PR TITLE
add Cell::as_array_of_cells, similar to Cell::as_slice_of_cells

### PR DESCRIPTION
**Pull request by oconnor663**
I'd like to propose adding `Cell::as_array_of_cells`, as a natural analog to `Cell::as_slice_of_cells`. I don't have a specific use case in mind, other than that supporting slices but not arrays feels like a gap. Do other folks agree with that intuition? Would this addition be substantial enough to need an RFC?

---

Previously, converting `&mut [T; N]` to `&[Cell<T>; N]` looks like this:

```rust
let array = &mut [1, 2, 3];
let cells: &[Cell<i32>; 3] = Cell::from_mut(&mut array[..])
    .as_slice_of_cells()
    .try_into()
    .unwrap();
```

With this new helper method, it looks like this:

```rust
let array = &mut [1, 2, 3];
let cells = Cell::from_mut(array).as_array_of_cells();
```

### CODE REVIEW

**Comment by oconnor663** [comment]
I've put a standalone version of this function in this repo: https://github.com/oconnor663/cell_utils

**Comment by oconnor663** [comment]
@scottmcm should I add someone else to review?

**Comment by scottmcm** [comment]
Sorry for being slow.  This seems perfectly reasonable to me, given that it's already possible (much less nicely) by going through slices.  Can you [open a Library Tracking Issue](https://github.com/rust-lang/rust/issues/new/choose) for it, and add that to the `unstable` attribute?

**Comment by oconnor663** [comment]
No worries. Done!

**Pull request merged**
