### PR TITLE
rust-gdb/rust-lldb: Trim output of vec/slice/array 

### LINKED ISSUE #29467: rust-gdb mishandles very long vectors
It appears to try to print/handle all elements of a vector, which means it eats a ton of CPU and memory for a very long one. This includes vectors that have been moved from, which have their length field filled in with `0x1d1d...`... which is a very large length (it can also occur when trying to debug memory corruption/mistakes: corrupting the length field may make it harder to use the debugger).

```rust
fn main() {
    let mut v = Vec::<u32>::new();
    std::mem::forget(v);
}
```

```
$ rustc extralong.rs -g
$ rust-gdb ./extralong
...
(gdb) break 4
Breakpoint 1 at 0x48bf: file extralong.rs, line 4.
(gdb) r
Starting program: /home/huon/projects/test-rust/extralong 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, extralong::main () at extralong.rs:4
4	}
(gdb) p v
^CPython Exception <class 'KeyboardInterrupt'> <class 'KeyboardInterrupt'>: 
$1 = Vec<u32>(len: 2097865012304223517, cap: 2097865012304223517)
(gdb) p/x v.len 
$2 = 0x1d1d1d1d1d1d1d1d
(gdb)
```

(note the `^C` to cancel the `p v`.)

### PR DESCRIPTION
**Pull request by untitaker**
Fix #29467

I have tested this with rust-gdb, but rust-lldb is completely untested.

It prints "cannot access memory" for the example in #29467 instead of hanging
up.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Looks good to me. Let's see if it passes the LLDB tests.

**Comment by untitaker** [comment]
The scoping bugs in the lldb scripts should now be fixed.

**Comment by untitaker** [comment]
I'm not sure if there's something wrong with my dev environment, because I can't get the tests to fail locally.

**Comment by michaelwoerister** [comment]
The test case should not contain the `#![omit_gdb_pretty_printer_section]` since we actually want to test the GDB pretty printers.

**Comment by untitaker** [comment]
@michaelwoerister I've removed that attr, please take a look again. It seems that the testcase passes both with and without the fix, but I'm not sure why.

**Comment by untitaker** [comment]
My current suspicion is that `...` is interpreted as a wildcard by the testrunner?

**Comment by michaelwoerister** [comment]
Only `[...]` should be interpreted as a wildcard. Let me see if I can reproduce your results.

**Comment by untitaker** [comment]
I see, I've updated the ... to .. though

**Comment by michaelwoerister** [comment]
@untitaker OK, so I've looked into LLDB and since we are producing actual strings there, it would be a greater undertaking to do the same as in GDB (and it's not clear that we actually want to do that there).

My proposal would be:
- Move `MAX_CHILDREN` into `lldb_rust_formatters.py` and only use it there.
- Make the GDB versions return an iterator as @tromey suggested (by just removing the `list()` call, presumably).
- Adapt the test cases accordingly.

**Comment by untitaker** [comment]
I'm unsure on how to adapt the tests, and can't get them to fail. I'm thinking about removing them.

**Comment by michaelwoerister** [comment]
You can take the adapted tests from here:
https://github.com/michaelwoerister/rust/blob/pp-huge-vec/src/test/debuginfo/huge-vec.rs
This version worked for me on Linux and Mac OS.

**Comment by untitaker** [comment]
Updated with your test. The first testcase should fail, the second one pass. Otherwise something is seriously broken.

**Comment by untitaker** [comment]
The relevant tests unexpectedly pass on Travis, but I get stylecheck errors.

**Comment by michaelwoerister** [comment]
You need to add the line `// ignore-tidy-linelength` below `// min-lldb-version: 310` to tell the build script that it shouldn't care about line length in this file.

**Comment by untitaker** [comment]
But why do the tests pass without the fix?

**Comment by michaelwoerister** [comment]
Where do you see them passing? In the Travis log I only see 'make tidy' running (and failing).

**Comment by untitaker** [comment]
Sorry, yes. Updated PR.

**Comment by michaelwoerister** [comment]
Almost passing. Pretty printers are not enabled on Windows. 
Please add the following directives (somewhere near `min-lldb-version`):
```
// ignore-windows
// ignore-freebsd
// ignore-android
// min-gdb-version 7.7
```
Those are the same as in the `pretty-std.rs` test file, so they should be up-to-date.

**Comment by untitaker** [comment]
I'd like to wait for https://github.com/rust-lang/rust/pull/30249 such that I can run the gdb/lldb tests in Travis.

**Comment by alexcrichton** [comment]
Looks like #30249 is stalling, so I'm gonna close this one as well (not a lot of activity), but feel free to resubmit!

**Comment by cptroot** [comment]
I'm running into this issue right now where LLDB is trying to print a 591KiB byte slice everytime I step through my nom parser. Is there any way that I can revive this really old PR? Looking for guidance on what caused this to go unmerged in the past.

**Comment by tromey** [comment]
I think the gdb parts are probably not needed any more, at least not with a new-enough gdb (so that the struct printer is not used).  You can control the number of printed elements in gdb with `set print elements`, and AFAICT all the other gdb pretty-printers read values lazily.

For lldb, I think the formatters need some updates to provide synthetic children.  (This came up in a different bug as well; I'll file a bug for this specifically.)  Then maybe the `target.max-children-count` setting will apply correctly.

**Pull request closed without merging**
