### PR TITLE
Do not exclusively suggest `;` when `,` is also a choice

### LINKED ISSUE #96791: Misleading error for missing comma/semicolon in array literal
Given the following code: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fe39659ce1a843c7ead370daa0e36414)

```rust
fn main() {
    let v = [1
    2];
}
```

The current output is:

```
error: expected `;`, found `2`
 --> test.rs:2:15
  |
2 |     let v = [1
  |               ^ help: add `;` here
3 |     2];
  |     - unexpected token

error: expected one of `.`, `;`, `?`, `}`, or an operator, found `]`
 --> test.rs:3:6
  |
3 |     2];
  |      ^ expected one of `.`, `;`, `?`, `}`, or an operator

error: aborting due to 2 previous errors
```

Ideally the output should look like:

```
error: expected one of `,`, `.`, `;`, `?`, `]`, or an operator, found `2`
 --> test.rs:3:5
  |
2 |     let v = [1
  |               -
  |               |
  |               expected one of `,`, `.`, `;`, `?`, `]`, or an operator
3 |     2];
  |     ^ unexpected token
```

The error implies that `;` is the only valid token at the end of the second line, and that the third line is being considered a separate statement from the second line, probably due to a consequence of the fault-tolerant parsing machinery.

Reasonable output is given when the newline is removed or there is more than 2 elements:
```
error: expected one of `,`, `.`, `;`, `?`, `]`, or an operator, found `2`
 --> test.rs:2:16
  |
2 |     let v = [1 2
  |                ^ expected one of `,`, `.`, `;`, `?`, `]`, or an operator

error: aborting due to previous error
```
```
error: expected one of `,`, `.`, `?`, `]`, or an operator, found `3`
 --> test.rs:3:5
  |
2 |     let v = [1, 2
  |                  -
  |                  |
  |                  expected one of `,`, `.`, `?`, `]`, or an operator
  |                  help: missing `,`
3 |     3];
  |     ^ unexpected token

error: aborting due to previous error
```

This should be fixed because it is confusing in less clear situations such as the following, especially where someone might expect the comma to be implicit due to the behaviour of `match`.
```rust
let v = [
    {
        1
    }
    {
        2
    }
];
```

This happens in every edition and on both stable and nightly.

### PR DESCRIPTION
**Pull request by compiler-errors**
Fixes #96791

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I'm not quite sure this is an improvement in all cases. E.g. in the regression test:
```rust
fn main() {
    let v = [1
    2];
    //~^ ERROR expected one of `,`, `.`, `;`, `?`, `]`, or an operator, found `2`
}
```
Does suggesting `?` make sense, for example?

I think this is something for the diagnostics team to decide. 
r? rust-lang/diagnostics

**Comment by michaelwoerister** [comment]
Also: Thanks for the PR, @compiler-errors! 😀

**Comment by compiler-errors** [comment]
> Does suggesting `?` make sense, for example?

It doesn't make sense type-wise, but this is parsing.

It's as valid as suggesting `?` anywhere, imo. We _could_ limit this to just mention `,` and `;`, but then we'd probably get another bug report like #96791 that (rightfully) says "the `?` token is also valid here, why aren't we reporting it"?

**Comment by compiler-errors** [comment]
@estebank do you have some time to look at this PR, or should I re-roll?

**Comment by compiler-errors** [comment]
r? diagnostics

**Comment by estebank** [comment]
I have to say, I'm not sure this is a net positive, but it's also not a net negative given the output changes are not really worse?

@bors r+

**Comment by compiler-errors** [comment]
@estebank: My thought process is that when `,` is one of the expected tokens alongside `;`, then we're current parsing `[ ...`, and the heuristic of "semicolon is needed to end the statement" (which is what I think this logic is trying to account for) is probably incorrrect.

I could change this if you'd like to say something like `;` or `,` since out of all the tokens, those are probably the _most_ expected as I mentioned above.

**Comment by estebank** [comment]
@compiler-errors honestly, it's fine. What we'd ideally do is try to parse the rest of the expression and start parsing the following node to see which token would have helped, but to do that we need a lot of machinery that we don't currently have.

**Pull request merged**
