### PR TITLE
Update compiler error 0093 to use new error format

### PR DESCRIPTION
**Pull request by stanislav-tkach**
Addresses #35230, Part of the #35233 meta bug

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks good, but I noticed an extra space at the end of one of the lines.  Before it's ready you'll need to run it through tidy:

```
python src/bootstrap/bootstrap.py --stage 1 --step check-tidy
```

**Comment by jonathandturner** [comment]
Ah, and one more point (sorry, should have mentioned this earlier).  Be sure to also update the unit test so that it's also testing for the new label.

**Comment by jonathandturner** [comment]
Great. Looks almost ready.  Last step, can you [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your 3 commits down to 1 commit?

**Comment by DarkEld3r** [comment]
Thank you for patience. Probably I have done something wrong with merge...

**Comment by GuillaumeGomez** [comment]
So explanations to squash your commits (I should create a blog post about it haha).

First:

```bash
git rebase -i HEAD~5
```

(5 corresponds to your commit number). Then replace all "pick" by "s" except the one at the top. Confirm and save.

Now add a "#" in front of all commit's comments you don't want (so normally all except the one at the top).

Once this done, push the new git history like this:

```bash
git push -f origin HEAD:your_branch_name
```

`your_branch_name` should be `e0093-formatting` in your case.

**Comment by DarkEld3r** [comment]
```
/home/travis/build.sh: line 45: docker: command not found
The command "docker build -t rust -f src/etc/Dockerfile src/etc" failed and exited with 127 during .
```
Strange failure. I suppose it is not caused by my changes?..

**Comment by DarkEld3r** [comment]
Did something go wrong? Should I do something or just wait patiently?

**Comment by GuillaumeGomez** [comment]
@eddyb: Travis didn't start correctly so I restarted it.
@DarkEld3r: Nothing to do (for the moment). Once travis has *really* run, we'll be able to see more.

**Pull request merged**
