### PR TITLE
Update/remove some old readmes

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @nikomatsakis 

cc #48478

There are a bunch of READMEs with content that I would like to see a final decision made on:
- https://github.com/rust-lang/rust/tree/master/src/librustc/ty/query
- https://github.com/rust-lang/rust/tree/master/src/librustc/dep_graph
- https://github.com/rust-lang/rust/blob/master/src/librustc/infer/region_constraints
- https://github.com/rust-lang/rust/tree/master/src/librustc/infer/higher_ranked
- https://github.com/rust-lang/rust/tree/master/src/librustc/infer/lexical_region_resolve
- https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/borrowck

It's not clear how useful or obsolete any of these are. I would really appreciate if the appropriate domain experts for each of these could respond with one of (a) delete it, (b) wait for system to be remove, or (c) move it to rustc-guide. @nikomatsakis do you know who to ping for any of these (sorry, I suspect many of them are you)?

### CODE REVIEW

**Comment by nikomatsakis** [comment]
- https://github.com/rust-lang/rust/tree/master/src/librustc/ty/query

I think we already moved this to the rustc-guide, more or less.

- https://github.com/rust-lang/rust/tree/master/src/librustc/dep_graph

@michaelwoerister can probably speak better to how up to date this is -- I suspect not very -- but also they had said they were interested in writing up a proper introduction to the query system + incremental for rustc-guide. Therefore, I think, remove.

- https://github.com/rust-lang/rust/blob/master/src/librustc/infer/region_constraints
- https://github.com/rust-lang/rust/tree/master/src/librustc/infer/lexical_region_resolve

This content is mostly still accurate, I believe. I expect for this code to be removed from the compiler, but likely not for some time (basically once NLL takes over completely, still some time from now). I'd probably go with "wait for system to be removed".

- https://github.com/rust-lang/rust/tree/master/src/librustc/infer/higher_ranked

This is actually obsolete now. We should delete it.

- https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/borrowck

This will go away once NLL takes over. Wait for system to be deleted, I think.

**Comment by nikomatsakis** [comment]
r=me on the existing changes, but maybe you want to act on some of the deletions above, @mark-i-m ?

**Comment by mark-i-m** [comment]
Thanks @nikomatsakis! I updated the PR with the deletions.

**Comment by michaelwoerister** [comment]
https://github.com/rust-lang/rust/blob/master/src/librustc/dep_graph/README.md seems to forward to the rustc-guide anyway.

**Pull request merged**
