### PR TITLE
Fix several -Z orbit crater blockers.

### PR DESCRIPTION
**Pull request by eddyb**
Fixes 3 of the issues found by @nikomatsakis' crater run with `-Z orbit` forced on:
https://gist.github.com/nikomatsakis/6688c30a0e5d3fed07cc1ebd4efb1412

Two of the regressions seemed to be fixed by #33130 and the remaining two are timeouts.

### CODE REVIEW

**Comment by eddyb** [comment]
@nikomatsakis Could you try crater + `-Z orbit` again with this PR applied?

**Comment by nikomatsakis** [comment]
@eddyb done.

**Comment by eddyb** [comment]
[Crater results](https://gist.github.com/nikomatsakis/39d74466309ae61084e8d8ba7a2b37a2), in case anyone cares. The only regression is just a (timeout) false positive.

**Pull request merged**
