### PR TITLE
Switch from `derivative` to `derive-where`

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
This is a part of the effort to get rid of `syn 1.*` in compiler's dependencies: #109302

Derivative has not been maintained in nearly 3 years[^1]. It also depends on `syn 1.*`.

This PR replaces `derivative` with `derive-where`[^2], a not dead alternative, which uses `syn 2.*`.

A couple of `Debug` formats have changed around the skipped fields[^3], but I doubt this is an issue.

[^1]: https://github.com/mcarton/rust-derivative/issues/117
[^2]: https://lib.rs/crates/derive-where
[^3]: See the changes in `tests/ui`

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors try @rust-timer queue

derives on very fundamental types may change their perf characteristics

**Comment by GrigorenkoPV** [comment]
> > The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9698588561/job/26765481945) [(plain)](https://github.com/rust-lang/rust/commit/b8bc93909d9f04b07cb8ffdb40827fe1d2c9e07c/checks/26765481945/logs)
> 
> The failures here are quite strange. The only thing that I did change was adding derivation of Eq to CanonicalVarKind, because without it the code refused to compile. My working theory is that `derivative` was fine with just `CanonicalVarKind: PartialEq` to derive `CanonicalVarInfo: Eq`, while it should not have been. `derive-where`, meanhwile, correctly infers that `CanonicalVarKind: Eq` is also needed. But hey, that's just a theory.

`derivative`:
```rust
    #[allow(unused_qualifications)]
    impl<I: Interner> ::std::cmp::Eq for CanonicalVarInfo<I> {}
```

`derive-where`:
```rust
    #[automatically_derived]
    impl<I: Interner> ::core::cmp::Eq for CanonicalVarInfo<I>
    where
        I: Interner,
    {
        #[inline]
        fn assert_receiver_is_total_eq(&self) {
            struct __AssertEq<__T: ::core::cmp::Eq + ?::core::marker::Sized>(
                ::core::marker::PhantomData<__T>,
            );
            let _: __AssertEq<CanonicalVarKind<I>>;
        }
    }
```

So my theory seems to be correct.

> However, what clippy complains about is actually derivations of `Hash` with a manual `PartialEq` implementation. ...which was the case even before my changes. Huh.

The culprit for this one can also be seen above. It's the `#[automatically_derived]` attribute.

So, all in all, I would say `derive-where` does a better job, at least as far as type checks and attributes go. As for the performance changes, I am not really equipped to judge those.

Should I just silence the clippy warnings?

**Comment by petrochenkov** [comment]
The warnings are in `rustc_type_ir`, so I'll leave it to the types team how to deal with them.
Otherwise LGTM, the perf changes are not significant.
r? @compiler-errors

**Review by petrochenkov — APPROVED** [review]

**Comment by compiler-errors** [comment]
Perf changes are noise. I think it's fine for us to. As a follow-up, we should look at not manually implementing `PartialEq` for these types but instead going thru a derive -- I believe they're only there b/c the automatic derives from `derivative` was performing poorly.

Please rebase this PR, and I'll take another look at it just for certainty. I think I may have added some `derivative` calls recently.

**Comment by GrigorenkoPV** [comment]
> Please rebase this PR,

Done

> and I'll take another look at it just for certainty.

@rustbot ready

> I think I may have added some `derivative` calls recently.

Indeed, there were like 3 new

**Comment by compiler-errors** [comment]
Sorry, I didn't finish my sentence.

> I think it's fine for us to

[...] ignore the clippy warnings regarding manually derived impls.

**Comment by GrigorenkoPV** [comment]
> > I think it's fine for us to
> 
> [...] ignore the clippy warnings regarding manually derived impls.

Done.

> As a follow-up, we should look at not manually implementing PartialEq for these types but instead going thru a derive 

I will try to tackle this later in a separate PR

**Pull request merged**
