### PR TITLE
add -Zexport-executable-symbols to unstable book

### PR DESCRIPTION
**Pull request by folkertdev**
This flag has been extremely useful to me, but it's hard to discover. The text contains a bunch of terms that hopefully a search engine will pick up on when someone searches for this functionality.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It needs someone from the compiler team to review this.

r? t-compiler

**Comment by GuillaumeGomez** [comment]
r? rust-lang/compiler

**Review by WaffleLapkin — APPROVED** [review]

**Pull request merged**
