### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by fudancoder**

### CODE REVIEW

**Comment by jieyouxu** [comment]
Thanks
r? jieyouxu @bors r+ rollup

**Comment by jieyouxu** [comment]
You'll need to add a `// ignore-tidy-linelength` for `tests/ui/moves/suggest-borrow-for-generic-arg.rs` then rebless the test.

@rustbot author

**Comment by lqd** [comment]
> You'll need to add a `// ignore-tidy-linelength`

or simply reflow the comment

**Comment by fudancoder** [comment]
> > You'll need to add a `// ignore-tidy-linelength`
> 
> or simply reflow the comment

I checked Lint's error and it was caused by a single line length that was too long. Do you need me to wrap lines to shorten the length of a single line?

**Comment by lqd** [comment]
That’s correct

**Comment by fudancoder** [comment]
> That’s correct

Thanks. Modified!

**Pull request merged**
