### PR TITLE
Revert stabilization of never_type (!) et al

### LINKED ISSUE #49691: revert stabilization of `!` and `TryFrom`
Per https://github.com/rust-lang/rust/issues/49593, we need to rollback the stabilization of `!` (and a few dependent things) from 1.26. That's sad, but hopefully only temporary -- we'll bring it back once we can fix the coercion, but we don't want to be tinkering with the core type system in a beta backport. I'm opening this P-high issue *specifically* to track the backport, not the response.

### PR DESCRIPTION
**Pull request by pnkfelix**
Fix #49691 

I *think* this correctly adopts @nikomatsakis 's desired fix of:
 * reverting stabilization of `!` and `TryFrom`, and
 * returning to the previous fallback semantics (i.e. it is once again dependent on whether the crate has opted into `#[feature(never_type)]`, 
 * **without** attempting to put back in the previous future-proofing warnings regarding the change in fallback semantics.

(I'll be away from computers for a week starting now, so any updates to this PR should be either pushed into it, or someone else should adopt the task of polishing this fix and put up their own PR.)

### CODE REVIEW

**Comment by pnkfelix** [comment]
cc @SimonSapin @alexcrichton

**Comment by pnkfelix** [comment]
Even though @nikomatsakis is on PTO, I believe he will be back soon enough that he would be a good choice as a reviewer. (However, if any one else wants to jump on board, I will not object.)

r? @nikomatsakis

**Comment by alexcrichton** [comment]
Thanks @pnkfelix! The libs parts here look good to me

**Comment by kennytm** [comment]
(I've add  594a552  to address the trivial build failure above)

**Comment by alexcrichton** [comment]
@bors: p=1

due to backport status

**Comment by SimonSapin** [comment]
@alexcrichton Do we also want to revert the addition of `impl FromStr for PathBuf` https://github.com/rust-lang/rust/pull/48292 so that in can be later re-added with `type Err = !;` https://github.com/rust-lang/rust/pull/49039 rather than a dedicated empty enum ?

**Pull request merged**
