### PR TITLE
ThinLTO: Don't keep files open after mmaping them.

### LINKED ISSUE #53947: Incremental ThinLTO fails for style-servo and script-servo on perf.rlo
The compiler seems to open too many files at once:
```
thread \'main\' panicked at \'failed to open bitcode file `/tmp/.tmpgMegOo/target/release/incremental/style-1fatvssee0g94/s-f4hlkotafd-18kxxq0-working/51kw0352sas5fu11.pre-thin-lto.bc`: Too many open files (os error 24)\', librustc_codegen_llvm/back/write.rs:2477:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I don't know yet how to best fix this:
- Either only use memory mapped files up to some limit and load the rest of the files eagerly,
- or generally limit the number of object files we partition a crate into (something people are asking for anyway).

cc @alexcrichton @Mark-Simulacrum

### PR DESCRIPTION
**Pull request by michaelwoerister**
Fixes #53947.

r? @alexcrichton

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@rust-timer build bc802efeac5a8ebf285527449742e5047d0e09d5

**Comment by alexcrichton** [comment]
r=me if perf comes back with a successful run!

Or just r=me in general, looks good!

**Comment by michaelwoerister** [comment]
Yeah, the test run didn't make too much sense since the parent commit is still broken. Unless the build logs can be viewed somewhere. Anyway, I'm even going to up the priority so we get valid perf data sooner.

@bors r=alexcrichton p=1

**Pull request merged**
