### PR TITLE
Const-eval array lengths in rustdoc.

### LINKED ISSUE #46727: rustdoc: Implementors of a trait is not const-evaled, thus showing `[T; 32 - 1 - 1 - 1 - 1 - 1 - 1 - 1]`
Repro steps:

1. Go to https://doc.rust-lang.org/1.22.1/std/default/trait.Default.html or https://doc.rust-lang.org/nightly/std/default/trait.Default.html
2. Scroll down.
3. Notice the amusement.

screenshot_2017-12-14 19 53 05_jfu5c0-fs8

The array lengths are normal in 1.21.0, but it is not clear whether this is the effect of performing const evaluation or the macro generating these impl changed in the new version.

### PR DESCRIPTION
**Pull request by detrumi**
Fixes #46727 
r? @eddyb

Big thanks to @eddyb for helping me figure this out.

### CODE REVIEW

**Comment by eddyb** [comment]
@bors r+

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
No tests? :'(

**Comment by eddyb** [comment]
@bors r-

@GuillaumeGomez Can you help with the tests? I have no idea how rustdoc tests work.

**Comment by detrumi** [comment]
Creating a test at `src/test/rustdoc/issue-46727.rs` seems straightforward enough.

I have more problems with reproducing the problem in a test case.
When trying to mimic the `array_impl_foo` macro for some `Foo` trait, the docs show it as `Implementations on Foreign Types` instead of `Implementors`, and it won't reproduce the problem.

**Comment by eddyb** [comment]
@detrumi Try `impl Foo for Bar<[T; 1 + 1 + 1]> {}` where `Foo` and `Bar` are defined in the test.

**Comment by detrumi** [comment]
You mean this?
```Rust
pub trait Foo {}
pub struct Bar<T> { x: T }
impl<T> Foo for Bar<[T; 1 + 1 + 1]> {}
```
That just produces `impl<T> Foo for Bar<[T; 3]>`

Unless I'm mistaken, the problem only occurs because of the macro. However, this doesn't trigger it:
```Rust
pub trait Foo {}
pub struct Bar<T> { x: T }
macro_rules! impl_foo {
    {$n:expr, $t:ident $($ts:ident)*} => {
        impl<T> Foo for Bar<[T; $n]> {}
        impl_foo!{($n - 1), $($ts)*}
    };
    {$n:expr,} => {
        impl<T> Foo for Bar<[T; $n]> {}
    };
}
impl_foo!{32, T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T}
```

**Comment by eddyb** [comment]
The macro shouldn't affect it at all. I guess it's because of cross-crate inlining, so maybe just `#[doc(inline)]` a reexport with one of those impls from `libcore` and it might show up?

**Comment by QuietMisdreavus** [comment]
You can set up auxiliary builds in rustdoc tests to test for this. Set up the impls in `src/test/rustdoc/auxiliary/issue-46727.rs`, and then in `src/test/rustdoc/issue-46727.rs`, add a `// aux-build:issue-46727.rs` comment to the top so compiletest will link it in properly. You may need to add a `#![crate_name="something"]` to one or both crates to make sure their names don't clash. Then you can re-export whatever you need in `src/test/rustdoc/issue-46727.rs` and make tests off it in there.

**Comment by detrumi** [comment]
Re-exporting did the trick, without needing `#[doc(inline)]`.
I couldn't get `#![crate_name="something"]` working in this instance, but using `compile-flags: -Cmetadata=aux`, which was used in other auxiliary tests, made it work.

**Pull request merged**
