### PR TITLE
Mention initial year of publication only for the documentation copyright

### PR DESCRIPTION
**Pull request by cheercroaker**
I have corrected the "copyright expiration year" that was still 2015 in the documentation copyright notice.

According to #31007 it seems that we could go one step further and simplify the copyright notice to only mention the year of original publication ("Copyright &copy; 2011" in this case).

Let me know if you would prefer this copyright notice to only mention the year of original publication (please make sure that it is really 2011 as stated in the current version of the documentation, and not 2010 like Rust's code) and I'll make the simplification.

### CODE REVIEW

**Comment by cheercroaker** [comment]
For _file headers_ in the source code, it seems that the consensus and policy is to spend the least amount of energy on copyright dates related stuff, as reminded in [this comment](https://github.com/brson/annotated-std-rs/commit/e50c2b16455ceff29488bf1f058b6c10906ef990#commitcomment-12409226) from @brson and [recommended](https://github.com/rust-lang/rust/issues/9070#issuecomment-72514411) by @gerv .

For _other copyright notices_, the most recent element from Mozilla legal I have found is to reflect the year of original publication (only), as [reported](https://github.com/rust-lang/rust/pull/31007#issuecomment-180027637) by @aturon .
This has been done for the [COPYRIGHT](https://github.com/rust-lang/rust/blob/master/COPYRIGHT) and [LICENCE-MIT](https://github.com/rust-lang/rust/blob/master/LICENSE-MIT) files via #31007.

Therefore I went ahead and added another commit: no more expiration year in the copyright notice for the documentation footer, only the year of initial publication.

Please rollup, for a little less "planned obsolescence" 😉

**Comment by gerv** [comment]
The only disadvantage of putting only initial publication years into visible copyrights in documentation is that it can lead people to erroneously assume the documentation is very old.

**Comment by brson** [comment]
That's a good point that it'll make the docs look out of date, but I'm fine trying this to keep our policy consistent and seeing how many fresh bug reports we get about the copyright date being wrong.

@bors r+ rollup

**Pull request merged**
