### PR TITLE
Generate documentation in rustc `define_id_collections` macro

### PR DESCRIPTION
**Pull request by pierwill**
Results in documentation like this:

Screen Shot 2021-11-11 at 8 53 58 PM

### CODE REVIEW

**Comment by the8472** [comment]
What's the intended benefit? If you click on the definition it should already show you the type alias (i.e. that it's a map, including generics) and if you click on `[src]` it shows you where/how it's defined so the comments don't add any new information.

**Comment by pierwill** [comment]
I agree that there's no new information here. But I think this makes it easier for the newcomer to understand how rustc uses macros to generate certain types. I also agree the `Generate by...` comment could be cut. I'd also okay with closing this if the benefits are clear.

**Comment by the8472** [comment]
Yeah, I think comments should add information on top of what rustdoc already provides out of the box. Purpose, how it's used, examples etc.
The structural information already is there and doesn't need to be put in prose.

> I'd also okay with closing this if the benefits aren't clear.

Ok. If you can come up with a more useful comment you can reopen it.

**Pull request closed without merging**
