### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by kennytm**
Successful merges:

 - #49396 (Make OnDiskCache thread-safer)
 - #49626 (Implement Chalk lowering rule Normalize-From-Impl)
 - #49866 (Cross-compile builder to Windows for PRs on Travis)
 - #49876 (Don't inject clippy into rls on stable/beta)
 - #49884 (core: Remove panics from some `Layout` methods)
 - #49886 (Ignore copyright year when generating deriving span tests)
 - #49904 (Work around LLVM debuginfo problem in librustc_driver.)
 - #49908 (Fix test failure in src/tools/rustdoc-themes when rust.rpath = false)
 - #49922 (Remove -Zmiri debugging option)
 - #49916 (improve Atomic*::fetch_update docs)
 - #49289 (Make --emit=metadata output metadata regardless of link)

Failed merges:

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r+ p=11

Added #49916.

**Comment by ishitatsuyuki** [comment]
Maybe you can roll up #49800 too?

**Comment by kennytm** [comment]
@bors r+

Added #49289.

**Comment by kennytm** [comment]
@ishitatsuyuki Sorry I think the change introduced by #49800 is pretty complex, so I intend not to roll this up.

**Comment by kennytm** [comment]
@bors r+

Removed #49915 (PR may need to be changed).

**Pull request closed without merging**
