### PR TITLE
revert mir inlining policy for beta-1.64

### LINKED ISSUE #101004: disable MIR inlining on beta-1.64
As discussed in T-compiler meeting https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-08-25/near/295236517, we are going to disable MIR inlining on beta-1.64 in order to resolve issues like #100550 and #100476 without having to do semi-risky backports.

For reference, the PR that enabled MIR inlining was PR #91743

### PR DESCRIPTION
**Pull request by pnkfelix**
revert mir inlining policy for beta-1.64

Fix #101004

### CODE REVIEW

**Comment by pnkfelix** [comment]
I had to locally disable src/test/codegen/mem-replace-direct-memcpy.rs to get my test suite to pass when trying this locally, regardless of whether I was testing stage 1 or stage 2. I assume this is because of #99619

**Comment by compiler-errors** [comment]
@pnkfelix you might need to disable and/or bless mem-replace-direct-memcpy because it looks like it's angry on CI too.

r=me when CI is green though.

**Comment by pnkfelix** [comment]
> @pnkfelix you might need to disable and/or bless mem-replace-direct-memcpy because it looks like it's angry on CI too.
> 
> r=me when CI is green though.

Yeah, I'm going to throw away that test on beta. It is just trying to ensure that the stdlib has no inefficient intermediate calls starting from `core::ptr::read`

**Comment by eddyb** [comment]
> Yeah, I'm going to throw away that test on beta.

You can just revert the MIR inlining PR. It changes the test just like many other tests because it gets inlined now, I don't see how [all the other changed tests could pass](https://github.com/rust-lang/rust/pull/91743/files#diff-a853804e7bc52110608829d350ad857f760a37a5edef2a0a86a0ff3085c4aa79).

<sup>(Oh, wait, I see, some of them just got `-Zinline-mir=no`, which didn't require changing the test itself, only the ones where `-Zinline-mir=no` wasn't sufficient, because the optimizations had happened in libcore itself, are the issue)</sup>

Still, I would try using `git revert` or at least [copying the old version of the test](https://github.com/rust-lang/rust/blame/a3e1a2b7ce22ddb00abe348113dcc92973e1d612/src/test/codegen/mem-replace-direct-memcpy.rs) (pre-MIR-inlining), if for no other reason than to have an extra layer of confirming it's actually getting back to the previous state.

**Comment by pnkfelix** [comment]
@eddyb I'll do that as a follow-up activity, for now I just want to get this in. (note that we're not making this change on nightly, just on beta, so I would argue that there is very little risk of this performance regression leaking back in.. but still, I can put a little time into it next week.)

**Comment by eddyb** [comment]
> so I would argue that there is very little risk of this performance regression leaking back in

IIRC it's not even a performance regression, I think Rust-GPU needed to avoid some dynamism in terms of `memcpy` lengths (and we pick our nightlies so no need to worry about that).

The main thing I wanted to express is that if the goal is to "disable MIR inlining" and the only test that appears to *observe* that difference is this one, it should be reverted so that it can act as a "canary" for MIR inlining being disabled.

(I would even prefer if it wasn't this test, but it seems that most codegen tests just disable MIR optimizations now, which makes some sense but it's suboptimal for actually testing, well, MIR inlining, or other MIR optimizations)

**Review by eddyb — CHANGES_REQUESTED** [review]
At the very least it would be good to include this reduction as a test:
* https://github.com/rust-lang/rust/issues/100550#issuecomment-1220132931

Oh and maybe some of this will pass on beta? (But I'm not sure what the status is)
* #100998

**Comment by pnkfelix** [comment]
@eddyb [wrote](https://github.com/rust-lang/rust/pull/101050#pullrequestreview-1087612247):

> Oh and maybe some of this will pass on beta? (But I'm not sure what the status is)
> 
>     * #100998

As far as I can tell, the examples in that ticket are not relevant to (or at least are not exposed by) the change in MIR inlining policy...

**Comment by wesleywiser** [comment]
@bors p=1

Resolves P-critical issue in beta.

**Pull request merged**
