### PR TITLE
Rollup of 15 pull requests

### PR DESCRIPTION
**Pull request by jonas-schievink**
Successful merges:

 - #75115 (`#[deny(unsafe_op_in_unsafe_fn)]` in sys/cloudabi)
 - #76649 (Add a spin loop hint for Arc::downgrade)
 - #77392 (add `insert` to `Option`)
 - #77610 (revise Hermit's mutex interface to support the behaviour of StaticMutex)
 - #77716 (Revert "Allow dynamic linking for iOS/tvOS targets.")
 - #77830 (Simplify query proc-macros)
 - #78109 (Check for exhaustion in RangeInclusive::contains and slicing)
 - #78198 (Simplify assert terminator only if condition evaluates to expected value)
 - #78249 (improve const infer error)
 - #78250 (Document inline-const)
 - #78264 (Add regression test for issue-77475)
 - #78268 (Do not try to report on closures to avoid ICE)
 - #78274 (Update description of Empty Enum for accuracy)
 - #78278 (move `visit_predicate` into `TypeVisitor`)
 - #78293 (Always store Rustdoc theme when it's changed)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by m-ou-se** [comment]
Looks like this isn't spurious: [ubuntu-base-16.04-core-armhf.tar.gz](http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04-core-armhf.tar.gz) is gone from http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/.

**Comment by jonas-schievink** [comment]
@m-ou-se it was moved to http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04.6-base-armhf.tar.gz

**Pull request closed without merging**
