### PR TITLE
Use raw_entry for more efficient interning

### PR DESCRIPTION
**Pull request by Zoxc**
Fixes https://github.com/rust-lang/rust/issues/56308#issuecomment-442492744

r? @eddyb

### CODE REVIEW

**Comment by eddyb** [comment]
LGTM. r? @nikomatsakis 

@bors try (for perf)

**Comment by Zoxc** [comment]
@rust-timer build https://github.com/rust-lang/rust/commit/fb4874d830c2e1e085a3bb8a83ee9a54b7570c31

**Comment by Mark-Simulacrum** [comment]
@rust-timer build fb4874d830c2e1e085a3bb8a83ee9a54b7570c31

**Comment by eddyb** [comment]
@Gankro @Amanieu this looks bad, huh.

**Comment by Zoxc** [comment]
Well that is odd. Let's see if performance is unchanged if I skip raw_entry and do a double lookup.

@bors try

**Comment by Amanieu** [comment]
I've seen this before in `hashbrown`. The solution is to [inline all the things](https://github.com/Amanieu/hashbrown/pull/20).

**Comment by Zoxc** [comment]
I've added inline attributes to things that weren't inlined.

@bors try

**Comment by Zoxc** [comment]
I see a 5% speedup in item-bodies checking locally now.

**Comment by Zoxc** [comment]
@rust-timer build 4be721be11349e95dc58f71db4148a60eb5439c2

**Comment by michaelwoerister** [comment]
@rust-timer build 4be721be11349e95dc58f71db4148a60eb5439c2

**Comment by michaelwoerister** [comment]
That's pretty awesome :)
cc @rust-lang/wg-compiler-performance

**Pull request merged**
