### PR TITLE
fix MIR's `box`

### PR DESCRIPTION
**Pull request by oli-obk**
the previous code generated a temporary of the inner type and assigned the box-memory to it. So if you did `let x: Box<usize> = box 5;` you got a

``` rust
let var0: Box<usize>; // x
let mut tmp0: Box<usize>;
let mut tmp1: usize;
...
tmp1 = Box(usize);
(*tmp1) = const 5;
tmp0 = tmp1;
var0 = tmp0;
```

r? @nagisa

### CODE REVIEW

**Comment by nagisa** [comment]
I had this fixed in my WIP branch https://github.com/rust-lang/rust/commit/f1a72d43132c63e0355386aeabe3bc247883d6e4 already. I guess it is fine to land this, but this needs a test (feel free steal/cherry-pick it from the linked commit).

r=me with a test.

**Comment by oli-obk** [comment]
done

**Pull request merged**
