### PR TITLE
Fix E0449

### PR DESCRIPTION
**Pull request by alexispurslane**
A fix for issue #35924.

### CODE REVIEW

**Comment by eddyb** [comment]
LGTM. Please squash all your commits first.

**Comment by christopherdumas** [comment]
Okay, squashed!

**Comment by eddyb** [comment]
Just realized this should have a test. r? @jonathandturner

**Comment by christopherdumas** [comment]
@jonathandturner I'm not familiar with the testing setup of Rust, so could you explain to me how to add a test to this? It looks like there already is a compile-fail test for this, but I don't know how to update it to this change. It passes the test, but the test is not very specific.

**Comment by jonathandturner** [comment]
@christopherdumas - I wrote a [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html) to help with this.  Specifically, check out the Extra Credit section of the blog post.  It explains that there are quirks in the unit testing tool where it won't test labels until you put in your first NOTE test.

**Comment by christopherdumas** [comment]
Thank you, I'll check that out.

**Comment by jonathandturner** [comment]
We landed some fixes to E0449 recently, which I *think* fix the issue.  If there are additional changes that need to be made, you can rebase and send us a new PR.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Pull request closed without merging**
