### PR TITLE
privacy: Rename "accessibility levels" to "effective visibilities"

### PR DESCRIPTION
**Pull request by petrochenkov**
And a couple of other naming and comment tweaks.

Related to https://github.com/rust-lang/rust/issues/48054

For `enum Level` I initially used naming `enum EffectiveVisibilityLevel`, but it was too long and inconvenient because it's used pretty often.
So I shortened it to just `Level`, if it needs to be used from some context where this name would be ambiguous, then it can be imported with renaming like `use rustc_middle::privacy::Level as EffVisLevel` or something.

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @Bryanskiy

**Comment by camsteffen** [comment]
How about `Visibilities` and `VisibilityLevel`?

**Comment by petrochenkov** [comment]
@camsteffen 
>How about `Visibilities` and `VisibilityLevel`?

To avoid confusing effective visibilities with "primitive"/"basic" `ty::Visibility`es.
A map that contains `EffectiveVisibility`es -> `EffectiveVisibilities`.

As for `Level`, I explained it in the top comment, it's mainly for brevity because it's commonly used.

**Comment by camsteffen** [comment]
I see. Maybe `Visibility` could be named `VisibilityDecl`?

**Comment by petrochenkov** [comment]
Ping @jackh726, it's been almost a month.

**Comment by petrochenkov** [comment]
Not sure why this PR was marked as iffy, it can be rolled up.
The only danger here is potential merge conflicts.

**Comment by Dylan-DPC** [comment]
yeh it was marked as iffy because of the chance of merge conflicts :P

**Comment by lqd** [comment]
Note for weekly triage: the wins could be bimodal noise on these benchmarks. They're the opposite of the previous PR on these 14 benchmarks, in the second spike below.

image

**Comment by petrochenkov** [comment]
This PR only contains renamings, so it's certainly noise.

**Pull request merged**
