### PR TITLE
Fix incorrect 'memory leak' example for `Vec::set_len`.

### PR DESCRIPTION
**Pull request by frewsxcv**
Example was written in https://github.com/rust-lang/rust/pull/34911

Issue was brought up in this comment:

https://github.com/rust-lang/rust/commit/a005b2cd2ac679da7393e537aa05e2b7d32d36d5#commitcomment-18346958

### CODE REVIEW

**Comment by nagisa** [comment]
I feel like a using a `Box` instead of `Vec` for elements would get the point across better.

**Comment by frewsxcv** [comment]
> I feel like a using a Box instead of Vec for elements would get the point across better.

In what ways do you think a `Box` would be more appropriate here?

**Comment by GuillaumeGomez** [comment]
I'd prefer to let @nagisa or someone else handles this PR.

**Comment by nagisa** [comment]
This PR is correct for all its worth.

**Comment by GuillaumeGomez** [comment]
@nagisa: Then r+ it :p

**Comment by nagisa** [comment]
r=me, I guess.

**Pull request merged**
