### PR TITLE
Preserve span when lowering ExprKind::Paren

### LINKED ISSUE #33681: Misleading highlighting of error message in expression with brackets/parentheses
[This fails to compile](
https://is.gd/GyNDt8). The error is that a `&` is required on the last line of `main`:
`let w = &(...) ^ &z;`

The error message seems to indicate that the inner operation is wrong, when in fact it is the outer one which needs correcting:

```
<anon>:15:14: 15:21 error: binary operation `^` cannot be applied to type `A` [E0369]
<anon>:15     let w = (&x ^ &y) ^ &z;
                       ^~~~~~~
```
should (in my opinion) read:
```
<anon>:15:14: 15:21 error: binary operation `^` cannot be applied to type `A` [E0369]
<anon>:15     let w = (&x ^ &y) ^ &z;
                      ^~~~~~~~~
```

Checked on `rustc 1.10.0-nightly (6974800c6 2016-05-08)` and an older nightly.

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #33681.

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r- , fails travis

```
failures:

    [compile-fail] compile-fail/associated-const-private-impl.rs

    [compile-fail] compile-fail/issue-2392.rs

    [compile-fail] compile-fail/private-struct-field-cross-crate.rs

    [compile-fail] compile-fail/private-struct-field.rs

test result: FAILED. 2237 passed; 4 failed; 11 ignored; 0 measured
```

**Comment by sanxiyn** [comment]
This is trickier than I thought. The problem is illustrated by the following code:

```rust
macro_rules! paren {
    ($e:expr) => (($e))
}

mod m {
    pub struct S {
        x: i32
    }
    pub fn make() -> S {
        S { x: 0 }
    }
}

fn main() {
    let s = m::make();
    paren!(s.x);
}
```

Before:

```
error: field `x` of struct `m::S` is private
  --> test.rs:16:12
16 |>     paren!(s.x);
   |>            ^^^
```

After:

```
error: field `x` of struct `m::S` is private
 --> test.rs:2:19
2 |>     ($e:expr) => (($e))
  |>                   ^^^^
```

**Comment by sanxiyn** [comment]
Since Rust macro is not text substitution, there is never a need to parenthesize like `($e)`, unlike in C. Still, `assert_eq!` does that. By the way, why do we have `assert_eq!` in compile-fail tests?!

**Comment by nikomatsakis** [comment]
@sanxiyn 

> By the way, why do we have assert_eq! in compile-fail tests?!

Why wouldn't we?

> Still, assert_eq! does that. 

Hmm. So... it seems like your highlighting code was doing the right thing, but perhaps `assert_eq` ought to be modified. I guess we can expect other macros to get suboptimal highlighting in a similar fashion.

**Comment by sanxiyn** [comment]
Modified `assert_eq!`. Now passes cfail locally.

**Comment by sanxiyn** [comment]
Now suboptimal highlighting is avoided.

**Comment by nikomatsakis** [comment]
@bors r+ rollup

I'm not sure which is better, but this seems good too.

**Pull request merged**
