### PR TITLE
Use beta cargo in opt-dist

### PR DESCRIPTION
**Pull request by Kobzol**
Using the new stage2 cargo caused issues when a backwards-incompatible change was made to cargo. This means that we won't be testing the LTO/1-CGU optimized cargo, but I don't think that's a big issue, as we primarily want to test the compiler.

Should fix [this](https://github.com/rust-lang/rust/pull/117000#issuecomment-1773639109) failure.

### CODE REVIEW

**Comment by lqd** [comment]
let's not overload mark even more.

r=me if the tests pass on the try build

with this comment "// Extract rustc, libstd, cargo and src archives to create the optimized sysroot" fixed to remove "cargo"

**Comment by Kobzol** [comment]
Sigh, forgot to enable tests…

@bors try

**Comment by weihanglo** [comment]
Since it blocks cargo submodule update, should we make it p=1?

**Comment by Kobzol** [comment]
Hmm, on Windows, the stage0 compiler doesn't contain Cargo?!
```
2023-10-22T00:04:07.2045142Z [2023-10-22T00:04:07.204Z INFO  opt_dist::tests] Using following `config.toml` for running tests:
2023-10-22T00:04:07.2045994Z     profile = "user"
2023-10-22T00:04:07.2046347Z     change-id = 115898
2023-10-22T00:04:07.2046679Z     
2023-10-22T00:04:07.2046963Z     [build]
2023-10-22T00:04:07.2047679Z     rustc = "C:/a/rust/rust/build/unpacked-dist/rustc-nightly-x86_64-pc-windows-msvc/rustc/bin/rustc.exe"
2023-10-22T00:04:07.2048362Z     
2023-10-22T00:04:07.2048599Z     [target.x86_64-pc-windows-msvc]
2023-10-22T00:04:07.2049156Z     llvm-config = "C:/a/rust/rust/build/x86_64-pc-windows-msvc/llvm/bin/llvm-config.exe"
2023-10-22T00:04:07.2049680Z     
2023-10-22T00:04:07.2051149Z [2023-10-22T00:04:07.204Z INFO  opt_dist::exec] Executing `COMPILETEST_FORCE_STAGE0=1 python C:\a\rust\rust\x.py test --stage 0 tests/assembly tests/codegen tests/codegen-units tests/incremental tests/mir-opt tests/pretty tests/run-pass-valgrind tests/ui --skip tests\codegen\vec-shrink-panik.rs [at C:\a\rust\rust]`
2023-10-22T00:04:07.3129497Z Traceback (most recent call last):
2023-10-22T00:04:07.3130313Z ##[group]Building bootstrap
2023-10-22T00:04:07.3130809Z   File "C:\a\rust\rust\x.py", line 50, in <module>
2023-10-22T00:04:07.3131309Z     bootstrap.main()
2023-10-22T00:04:07.3145733Z   File "C:\a\rust\rust\src\bootstrap\bootstrap.py", line 1134, in main
2023-10-22T00:04:07.3217062Z     bootstrap(args)
2023-10-22T00:04:07.3217696Z   File "C:\a\rust\rust\src\bootstrap\bootstrap.py", line 1101, in bootstrap
2023-10-22T00:04:07.3220138Z     build.build_bootstrap()
2023-10-22T00:04:07.3220795Z   File "C:\a\rust\rust\src\bootstrap\bootstrap.py", line 894, in build_bootstrap
2023-10-22T00:04:07.3222516Z     args = self.build_bootstrap_cmd(env)
2023-10-22T00:04:07.3222983Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-22T00:04:07.3223660Z   File "C:\a\rust\rust\src\bootstrap\bootstrap.py", line 967, in build_bootstrap_cmd
2023-10-22T00:04:07.3225305Z     raise Exception("no cargo executable found at `{}`".format(
2023-10-22T00:04:07.3226270Z Exception: no cargo executable found at `C:\a\rust\rust\build\x86_64-pc-windows-gnu\stage0\bin\cargo.exe`
```

**Comment by lqd** [comment]
It has to contain cargo 😅. 

Maybe here a cross-compilation case goes through opt-dist when it shouldn't: the llvm-config is on `[target.x86_64-pc-windows-msvc]` and cargo is searched for in `C:\a\rust\rust\build\x86_64-pc-windows-gnu`

**Comment by Kobzol** [comment]
Oh, that's a good point. Probably we should be passing `--host=x86_64-pc-windows-msvc --target=x86_64-pc-windows-msvc` to the tests anyway.

**Comment by Kobzol** [comment]
Trying if Windows tests were fixed.

@bors try

**Comment by lqd** [comment]
Incredible

**Comment by Kobzol** [comment]
Ok, now it is hopefully fixed.

@bors r=lqd

**Comment by weihanglo** [comment]
Thank you people!

**Pull request merged**
