### PR TITLE
Warn on `pub extern crate`.

### PR DESCRIPTION
**Pull request by nrc**
Temporary 'fix' for #26775

r? @brson

### CODE REVIEW

**Comment by pnkfelix** [comment]
@rust-lang/lang I have no opinion about backporting this to beta; I certainly don't object, but I also don't think its the end of the world if we end up waiting a release cycle for this warning.

**Comment by nikomatsakis** [comment]
Same. It's a very small patch, so relatively harmless.

**Comment by nikomatsakis** [comment]
Given that @nrc nominated it, i'm going to assume he's in favor.

**Comment by nrc** [comment]
I nominated this at the start of the cycle, I'd not be in favour at this point, but it looks like I'm too late - no harm though.

**Pull request merged**
