### PR TITLE
Remove `#[rustc_allow_const_fn_ptr]` and add `#![feature(const_fn_fn_ptr_basics)]`

### PR DESCRIPTION
**Pull request by ecstatic-morse**
`rustc_allow_const_fn_ptr` was a hack to work around the lack of an escape hatch for the "min `const fn`" checks in const-stable functions. Now that we have co-opted `allow_internal_unstable` for this purpose, we no longer need a bespoke attribute.

Now this functionality is gated under `const_fn_fn_ptr_basics` (how concise!), and `#[allow_internal_unstable(const_fn_fn_ptr_basics)]` replaces `#[rustc_allow_const_fn_ptr]`. `const_fn_fn_ptr_basics` allows function pointer types to appear in the arguments and locals of a `const fn` as well as function pointer casts to be performed inside a `const fn`. Both of these were allowed in constants and statics already. Notably, this does **not** allow users to invoke function pointers in a const context. Presumably, we will use a nicer name for that (`const_fn_ptr`?).

r? @oli-obk

### CODE REVIEW

**Comment by oli-obk** [comment]
Oh this is a wondeful fix.

> Presumably, we will use a nicer name for that (const_fn_ptr?).

we could add an unsound feature like that if you want it for experimentation (though it would probably be better to just allow it via unleash and not a gate). We'll need to figure out the details around that together with trait objects and method calls in general.

Note that you don't really need to fix the old min_const_fn check here, as that is just used by clippy now. We could in fact remove all feature gating logic from min_const_fn and just move it to clippy. this way it's removed from rustc and we'll just have to figure out whether we want to not just permit trivial const fns (so we'll have to adjust the logic in clippy instead of reusing the rustc logic)

**Comment by ecstatic-morse** [comment]
> we could add an unsound feature like that if you want it for experimentation.

Oh nothing like that. I was trying to explain the reason I chose a verbose one here `const_fn_fn_ptr_basics`. `const_fn_fn_ptr` or `const_fn_ptr` imply that you can actually do stuff with them besides move them around, and I think we would want to use `const_fn_ptr` for `const fn() -> i32` (or whatever form it takes).

**Comment by oli-obk** [comment]
right. So this PR lgtm, r=me after a rebase

**Comment by ecstatic-morse** [comment]
This will conflict with #77231. Better to let that one go through first.

**Comment by ecstatic-morse** [comment]
@jonas-schievink Any idea where I can find the logs for the failing rollup? A stage 1 build works and all UI tests pass for me locally on the latest master.

**Comment by jonas-schievink** [comment]
Logs should be here: https://github.com/rust-lang/rust/runs/1173085918

**Comment by ecstatic-morse** [comment]
Seems to be working now. I removed the old failing gate test for `rustc_allow_const_fn_ptr`, since it's not covering anything unique now.

**Pull request merged**
