### PR TITLE
avoid non-strict-provenance casts in libcore tests

### PR DESCRIPTION
**Pull request by RalfJung**
r? @thomcc

### CODE REVIEW

**Comment by thomcc** [comment]
Surprised we had any of these.

@bors r+ rollup

**Comment by RalfJung** [comment]
It got added very recently.

**Comment by RalfJung** [comment]
@bors r-

I have enabled the lint against these casts. @thomcc is that okay?

**Comment by thomcc** [comment]
Yep, looks good to me.

@bors r+ rollup

**Pull request merged**
