### PR TITLE
Rustfmt librustc resolve

### PR DESCRIPTION
**Pull request by little-dude**
Another rustfmt PR.
I ran rustfmt, then split the changes in multiple commits. First commit are the non-problematic changed. The others are all the little weirdness that caught my attention and could be discussed.

### CODE REVIEW

**Comment by nrc** [comment]
re the 9th commit - when the function decl needs multiple lines we always split the args, I think this is fine - once a function decl gets this long the readability benefits of argument per line outweigh the benefits of keeping things on a few lines.

**Comment by nrc** [comment]
ping @little-dude Can you rebase this branch please? Did you need any more help with the comments?

**Comment by little-dude** [comment]
@nrc sorry, it's just lack of time (getting married in a few days :D). I'll try to do this later today.

**Comment by little-dude** [comment]
seems like github removed all you comments after I rebased... In one of them you were asking about the version of rustfmt I'm using:

```commit 3ce2b840cf73253cedf86aaf3b6b7a71e27d6b79
Merge: 58ff0d8 be77f8a
Author: Marcus Klaas de Vries <mail@marcusklaas.nl>
Date:   Sat Oct 24 16:38:51 2015 +0200

    Merge pull request #522 from marcusklaas/writing-tests

    Add a brief overview of rustfmt tests
```

**Comment by nrc** [comment]
@little-dude no worries - not trying to rush you, just checking you didn't need anything from me. And congrats!

**Comment by nrc** [comment]
lib.rs:2484 - comments are misaligned

I think that is the only thing that needs fixing up now.

**Comment by little-dude** [comment]
> lib.rs:2484 - comments are misaligned

thanks, I'll fix this.

>  And congrats!

thank you!

**Comment by little-dude** [comment]
@nrc I rebased against master and fixed the indentation of the comments that were misaligned. See last two commits.

If this is good for you I'll squash everything.

**Comment by nrc** [comment]
@little-dude looks goo, thanks! r+ with a squash

**Comment by little-dude** [comment]
Arf. I'll rebase again.

**Comment by little-dude** [comment]
@nrc: I rebased, could you review again please?

**Pull request merged**
