### PR TITLE
improve cgu schedule with greedy partition

### PR DESCRIPTION
**Pull request by csmoe**
The difference between merged cgu should be more smaller than the old code which merges the small cgus into less-small cgu.

r? @bjorn3 may I have a perf-run? thanks :)

### CODE REVIEW

**Comment by lqd** [comment]
cc @nnethercote as I believe they have tried a greedy partitioning recently. 

It also seems this PR removes the minimum CGU size property added in #112448, and part of the regressions may be coming from losing what that PR gained.

**Comment by nnethercote** [comment]
I have been working on improving CGU handling for several weeks. It's a difficult problem and many things that you might expect to improve performance do not. In particular, the interplay between walltime (speed), max-rss (memory use), and binary size is challenging -- it's hard to improve one or more of these across multiple benchmarks without badly regressing others.

Some PRs that may be of interest:
- #111666, #111712, #111900, #111937 were all unsuccessful attempts.
- #112448 was a success.
- #112648 and #112695 are ongoing. Unclear if they will be a success.

There is a function `debug_dump` in `compiler/rustc_monomorphize/src/partitioning.rs` that is very useful. Try changing the `debug!` statement to `eprintln!` and inspect the output.

If you want to continue working on this, we should coordinate, perhaps on Zulip.

**Comment by csmoe** [comment]
Thanks for your reviews and I did read the previous great PRs. If I understood @nnethercote‘s greedy approach right, they tried to merge as much as possible.

While I’m implementing one of the algorithm for multi-way number partition problems to ease the size diff between cgu, unfortunately the perf said llvm opt pass was unexpectedly slower 🥲 


And I wasn’t intended to remove the MIN const, because the partition count was known from the beginning in my approach, while MIN applied to the loop process “dynamically”, so I just commented it out for a experiment.

**Comment by nnethercote** [comment]
#111712 implemented a greedy approach. It gave much better results than the current algorithm in terms of making the CGU sizes more similar. But it resulted in worse compile-time speed. One reason for this is that the size estimates are not very good. 

So if you have, for example, 10 CGUs of equal estimated size but one of those estimates is too small by 30%, then you'll end up with one CGU that takes 30% longer than the other to compile -- that's the "long pole" that's holding everything up. In contrast, a worse merge might leave you with 10 CGUs of varying size, which leaves more room to accommodate inaccuracies. E.g. most of the smaller CGUs can have their size underestimated without it hurting much.

There are a lot of surprising behaviours here. I recommend using a profiler like the self-profile or samply that can show thread execution, because seeing how long the different codegen threads take is very helpful. For example, this screenshot is from samply:
Screenshot from 2023-06-19 13-32-33

**Comment by csmoe** [comment]
benchmarked locally, it regressed.

**Pull request closed without merging**
