### PR TITLE
Rollup of 11 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #72414 ( Add lazy initialization primitives to std)
 - #74069 (Compare tagged/niche-filling layout and pick the best one)
 - #74418 (ci: Set `shell: bash` as a default, remove duplicates)
 - #74441 (bootstrap.py: patch RPATH on NixOS to handle the new zlib dependency.)
 - #74444 (Add regression test for #69414)
 - #74448 (improper_ctypes_definitions: allow `Box`)
 - #74449 (Test codegen of compare_exchange operations)
 - #74450 (Fix `Safety` docs for `from_raw_parts_mut`)
 - #74453 (Use intra-doc links in `str` and `BTreeSet`)
 - #74457 (rustbuild: drop tool::should_install)
 - #74464 (Use pathdiff crate)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by eddyb** [comment]
```

Run src/ci/scripts/install-awscli.sh
Reading package lists...
Building dependency tree...
Reading state information...
Package python3-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

@bors retry

**Comment by eddyb** [comment]
```
thread 'test_frequency::prop_frequency_indexed' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (CsvData { data: [[[]], [[]], [[239, 187, 191]], [[]], [[]]] })
Error: "assertion failed: `(left == right)`\n  left: `[(\"(NULL)\", 4)]`,\n right: `[(\"(NULL)\", 3), (\"\\u{feff}\", 1)]`"', D:\a\rust\rust\src\libstd\macros.rs:13:23


failures:
    test_frequency::prop_frequency_indexed
```

This doesn't look spurious.

**Comment by eddyb** [comment]
Wait, that's quickcheck, so it's possible it's a buggy test. cc @BurntSushi

@bors retry

**Comment by Manishearth** [comment]
@eddyb yeah that's a known bug in the crate, I filed it earlier. FEFF causes problems

**Comment by alex** [comment]
(https://github.com/BurntSushi/xsv/issues/227 for the record)

**Comment by mati865** [comment]
FTR something in this PR has regressed performance: https://perf.rust-lang.org/compare.html?start=d3df8512d2c2afc6d2e7d8b5b951dd7f2ad77b02&end=7d31ffc1ac9e9ea356e896e63307168a64501b9d&stat=instructions:u

**Comment by Mark-Simulacrum** [comment]
Identified as #74069 (Compare tagged/niche-filling layout and pick the best one), perf in #74592, revert at https://github.com/rust-lang/rust/pull/74611

**Comment by nnethercote** [comment]
> Identified as #74069 (Compare tagged/niche-filling layout and pick the best one), perf in #74592, revert at #74611

Just to clarify: @Mark-Simulacrum and I are confident that #74069 was the only perf regression in this rollup.

**Comment by Mark-Simulacrum** [comment]
This PR turned out to be performance-neutral. See results of investigation here https://github.com/rust-lang/rust/pull/74716#issuecomment-663735771; the revert of #74069 (Compare tagged/niche-filling layout and pick the best one) is being undone in https://github.com/rust-lang/rust/pull/74802.

**Pull request merged**
