### PR TITLE
compiletest: Deduplicate `--check-prefix` flags

### PR DESCRIPTION
**Pull request by tgross35**
Currently having a revision named like `MSVC` causes errors because it gets passed via `--check-prefix` twice; once from the revision name and once from the default `msvc_or_not` value that compiletest sets. Fix this by deduplicating revision names before passing the arguments.

### CODE REVIEW

**Comment by tgross35** [comment]
I noticed this when working on https://github.com/rust-lang/rust/pull/134290, having a revision named `MSVC` causes a duplicate flag warning. Also weird: this warning showed up only when running in CI on an actual MSVC machine, not locally for me even though it is testing with a `-msvc` target (via `no_core`). Is it possible the `MSVC`/`NOMSVC` prefix is getting set based on the host rather than the target? Doesn't look like it here, but I don't know why else that would happen.

r? @jieyouxu

**Comment by jieyouxu** [comment]
... That seems slightly cursed, I'll have to do some digging and look at this tmrw.

**Comment by tgross35** [comment]
For reference the failure was here https://github.com/rust-lang/rust/pull/134290#issuecomment-2542680394. I never ran the whole suite locally but `./x t tests/codegen/i128-x86-callconv.rs` passed successfully running on my mac.

That PR includes this one's commit for now.

**Comment by jieyouxu** [comment]
cc @Zalathar since this was added in #120656. However, that logic AFAICT only accepts `MSVC` and `NONMSVC` as "predefined FileCheck prefixes" but I can't find any logic that actually distinguishes between `MSVC` and `NONMSVC`. I feel like I'm missing some context. @Zalathar was `MSVC` meant to imply some kind of implicit `only-msvc`-esque logic...?

**Comment by Zalathar** [comment]
FWIW these automatic FileCheck prefixes predate me; I was just the person who most recently tried to clean up the code for setting them.

Getting rid of this implicit behaviour should be doable. I've looked into doing so in the past, but never got around to actually filing a PR.

**Comment by jieyouxu** [comment]
Yeah I realized that now, as I somehow completely missed the `contains("msvc")` in the diff, lol, sorry. I've opened #134463 to get rid of the `MSVC`/`NONMSVC` predefined prefix and updated codegen tests that use them.

**Comment by tgross35** [comment]
Sounds reasonable, thanks for putting up a fix! I’ll try it later today.

**Pull request closed without merging**
