### PR TITLE
Make `MatcherPos::stack` a `SmallVec`.

### PR DESCRIPTION
**Pull request by nnethercote**
This avoids some allocations.

This seems like a trivial change, but the compiler rejects it:
```
   Compiling syntax v0.0.0 (/home/njn/moz/rust1/src/libsyntax)                                      
error[E0597]: `initial` does not live long enough=========>           ] 89/110: syntax              
   --> libsyntax/ext/tt/macro_parser.rs:647:57
    |
647 |     let mut cur_items = smallvec![MatcherPosHandle::Ref(&mut initial)];
    |                                                         ^^^^^^^^^^^^ borrowed value does not live long enough
...
762 | }
    | -
    | |
    | `initial` dropped here while still borrowed
    | borrow later used here, when `initial` is dropped

error: aborting due to previous error
```
This is either a compiler bug, or there's some subtle thing I don't understand. The lifetimes sure seem straightforward: `initial` is declared, and then `cur_items` is declared immediately afterward, and it uses a reference to `initial`. The error message makes it sound like the compiler is dropping the variables in the wrong order.

r? @nikomatsakis, any idea what the problem is?

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I see

**Comment by nikomatsakis** [comment]
(Trying this now locally)

**Comment by nikomatsakis** [comment]
Hmm, so, I don't think that the borrow checker is *wrong* but the error reporting is ungreat here (and this isn't my favorite part of the language). I guess `SmallVec` is defined in the `smallvec` crate, right? I think it lacks the `#[may_dangle]` annotations which tell us that the `T` will not be used by the destructor (except to be dropped) -- `Vec` has such annotations (they are not permitted in stable code, though).

This forces us to be more conservative with `SmallVec` than `Vec`.

This is combined with the fact that the `MatcherPosHandle` definition has too few lifetime parameters:

```rust
enum MatcherPosHandle<'a> {
    Ref(&'a mut MatcherPos<'a>),
    Box(Box<MatcherPos<'a>>),
}
```

Here, the single parameter `'a` is used after an `&mut`, which requires a strict equality and doesn't permit "lifetime approximation" (the lifetime can't get any smaller).

So what winds up happening is that .. somehow .. the lifetiime of the borrow winds up extended. Anyway, sorry this explanation isn't that coherent =) I'll dig a bit more.

**Comment by nikomatsakis** [comment]
OK, pushed a fix I believe.

**Comment by nnethercote** [comment]
Goodness! Thank you for figuring that out, I never would have.

**Comment by nnethercote** [comment]
@nikomatsakis: is it reasonable to push this as-is? Or should I squash the two patches together?

**Comment by nnethercote** [comment]
@nikomatsakis: I merged the patches and put you as the author.

**Pull request merged**
