### PR TITLE
rustdoc: Pretty-print assoc const defaults on-demand

### PR DESCRIPTION
**Pull request by camelid**
This should improve performance, clean up the code, and help pave the
way for #83035.

### CODE REVIEW

**Comment by camelid** [comment]
I ran tests locally, so should be good now.

@bors try @rust-timer queue

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+

**Comment by camelid** [comment]
Pretty sure that's spurious, so @bors retry

**Comment by camelid** [comment]
@rylev rustc-perf is reporting _extreme_, spurious perf changes.

**Comment by camelid** [comment]
Hopefully those shouldn't happen now that #1123 is merged?

**Pull request merged**
