### PR TITLE
fs::get_mode enable getting the data via fcntl/F_GETFL on major BSD

### PR DESCRIPTION
**Pull request by devnexen**
supporting this flag.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can you point to documentation indicating this is supported? https://man.openbsd.org/fcntl.2#F_GETFL doesn't list the access mode flags, but it might just be an oversight of that particular page -- on a Linux box the manpage does list the file access mode though.

**Comment by JohnCSimon** [comment]
Ping from triage: 
@devnexen Can you please answer the question from `@Mark-Simulacrum` ?

**Comment by devnexen** [comment]
oh sorry I missed the comments

so I picked mainly from here https://github.com/openbsd/src/blob/2207c4325726fdc5c4bcd0011af0fdf7d3dab137/sys/sys/fcntl.h#L65

**Comment by Mark-Simulacrum** [comment]
Thanks! @semarie could you take a look as well as the target owner for \*openbsd?

**Comment by semarie** [comment]
@Mark-Simulacrum it LGTM. I quickly checked the [kernel source code](https://github.com/openbsd/src/blob/0d280c5f69f6ef21f5dca2b37e738de752505c51/sys/kern/kern_descrip.c#L467) and wrote a quick C program to ensure all is fine.

**Comment by Mark-Simulacrum** [comment]
@bors r+

Thanks!

**Pull request merged**
