### PR TITLE
Add `slice::{from_ptr_range, from_mut_ptr_range} `

### PR DESCRIPTION
**Pull request by ibraheemdev**
Adds `slice::{from_ptr_range, from_mut_ptr_range}` as counterparts to `slice::{as_ptr_range, as_mut_ptr_range}`.

### CODE REVIEW

**Comment by ibraheemdev** [comment]
@m-ou-se can you review this when you have the time, or should it be assigned to someone else?

**Review by m-ou-se — APPROVED** [review]
Apologies.

This looks good to me.

There is just one issue that worries me: There have been (incomplete) plans for quite a while to replace `Range` by two types: One that is `Copy`, and one that is an iterator. Using `Range` in signatures like this makes that change a little bit harder than it already is. Of course, the existing (and stable) `.as_ptr_range()` already has this problem as it uses `Range` as its return type. Still, I'm worried about making a potential change to `Range` even harder by adding the functions in this PR.

That doesn't have to stand in the way of adding these as unstable. I have added this as an unresolved question to the tracking issue, so we can make sure to address it before stabilizing this.

If you can fix the merge conflict, this is ready to merge.

**Comment by ibraheemdev** [comment]
Fixed @m-ou-se

**Comment by m-ou-se** [comment]
Can you rebase/squash the commits? Because now there's a commit named "[update rust-analyzer submodule](https://github.com/rust-lang/rust/pull/89793/commits/7012b17d1326e47527e5482d4bbc969c737ed9b9)", which shouldn't be part of this PR.

**Comment by ibraheemdev** [comment]
squashed @m-ou-se

**Pull request merged**
