### PR TITLE
add basic IP support in HermitCore

### PR DESCRIPTION
**Pull request by stlankes**
- add initial version to support sockets within HermitCore
- use TcpStream as test case
- HermitCore uses smoltcp as IP stack for pure Rust applications
- further functionalities (e.g. UDP support) will be added step by step

### CODE REVIEW

**Comment by stlankes** [comment]
? @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the ping but I unfortunately don't have time to help maintain all the targets of libstd nowadays myself.

**Comment by stlankes** [comment]
No problem!

**Comment by JohnTitor** [comment]
One nit: we have "no merge policy" here, recommend not including merge commits on PR: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#pull-requests

**Comment by stlankes** [comment]
Oh, yes. I will fix it

**Comment by stlankes** [comment]
I close it and resubmit it after revising my code

**Pull request closed without merging**
