### PR TITLE
EXPERIMENTAL: Hash spans unconditionally during incr. comp.

### PR DESCRIPTION
**Pull request by michaelwoerister**
It would be good for reliability if we could do without all this special-casing around change detection for spans. This PR removes most extra logic around span hashing and is meant to gauge how much of a performance regression this would cause. Much of the potential performance loss should be recoverable by better factoring queries -- but that's a medium term undertaking and should not block incr. comp. stabilization.

cc @nikomatsakis @Mark-Simulacrum

### CODE REVIEW

**Comment by michaelwoerister** [comment]
cc https://github.com/rust-lang/rust/issues/46303

**Comment by Mark-Simulacrum** [comment]
http://perf.rust-lang.org/compare.html?start=fdfbcf85d55da97ed1a00823510b876018047aaf&end=fe077faa64169fdb9a5710789e6875110734f316&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
OK, so the results from http://perf.rust-lang.org/compare.html?start=fdfbcf85d55da97ed1a00823510b876018047aaf&end=fe077faa64169fdb9a5710789e6875110734f316&stat=instructions%3Au are pretty much as expected:
- Almost no change in the debug builds as those were hashing spans all along,
- little change in the release builds for clean rebuilds and sometimes,
- quite big performance regressions when there are actual changes made to the code.

I interpret these big regressions as some codegen units being invalidated that weren't invalidated before for the same change set. Factoring spans out of the HIR, MIR, and Attributes should bring the lost performance back, but is not a small undertaking.

I've pushed some more commits that enable caching of many high-impact queries and started another try-build. This additional set of queries can only be cached because of the accurate span hashing. Let's see how performance looks for that.

**Comment by Mark-Simulacrum** [comment]
http://perf.rust-lang.org/compare.html?start=98a96b0b66db618b463d1d54d72942f9fae1e03f&end=d8715c2ae9af51d6742ddb6e883481e49826a9aa&stat=instructions%3Au

**Comment by michaelwoerister** [comment]
This is superseded by https://github.com/rust-lang/rust/pull/46556. Thanks for the performance measurements, @Mark-Simulacrum!

**Pull request closed without merging**
