### PR TITLE
Stabilize const_ptr_read

### PR DESCRIPTION
**Pull request by usbalbin**
Stabilizes const_ptr_read, with tracking issue #80377

### CODE REVIEW

**Comment by apiraino** [comment]
Removing `T-compiler` since I think these changes are of interest only for `T-libs-api` (but if it's not the case feel free to re-add the add and ask for a review).

@rustbot label -T-compiler

**Comment by est31** [comment]
:wave: Hello, I'm writing this comment in this **stabilization PR** to notify you, the authors of this PR, that https://github.com/rust-lang/rust/pull/100591 has been merged, which implemented a change in how features are stabilized.

Your PR has been filed before the change, so will likely require modifications in order to comply with the new rules. I recommend you to:

1. rebase the PR onto latest master, so that uses of the placeholder are possible.
2. replace the version numbers in the PR with the placeholder `CURRENT_RUSTC_VERSION`. For language changes, this means the version numbers in `accepted.rs` (example: 4caedbae869855a19ca49455e2cd338ae3b8c1ef). For library changes, this means the `since` fields (example e576a9b554f24a26c36c04b41c901636d190605b).

That's it! The `CURRENT_RUSTC_VERSION` placeholder will, as part of the release process, be replaced with the version number that the PR merged for. It can be used anywhere in `rust-lang/rust`, not just accepted.rs and the since fields.

If you have any questions, feel free to drop by the [zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/libs.20stabilization.20placeholder), or ping me directly in this PR's thread. Thanks! :wave:

**Comment by Nilstrieb** [comment]
Amy updates here? Seems good to go for an FCP. @m-ou-se

**Comment by oli-obk** [comment]
r? libs

**Comment by dtolnay** [comment]
Reassigning BurntSushi's reviews because based on `git log -i --grep=r=burntsushi` the last time they did rust-lang/rust reviews was over 3 years ago.

r? rust-lang/libs-api

**Comment by H4x5** [comment]
any updates on this?

**Comment by m-ou-se** [comment]
Sorry for the delay. This still needs an FCP. I've proposed an FCP on the tracking issue: https://github.com/rust-lang/rust/issues/80377#issuecomment-1497464304

**Comment by pitaj** [comment]
@usbalbin FYI you have merge conflicts. Please fix those so this PR can be merged, now that the FCP is complete.

**Comment by usbalbin** [comment]
> The Miri subtree was changed
> 
> cc @rust-lang/miri
> 
> These commits modify the `Cargo.lock` file. Unintentional changes to `Cargo.lock` can be introduced when switching branches and rebasing PRs.
> 
> If this was unintentional then you should revert the changes before this PR is merged. Otherwise, you can ignore this comment.
> 
> Some changes occurred to MIR optimizations
> 
> cc @rust-lang/wg-mir-opt

How do I undo that?

**Comment by pitaj** [comment]
I think that message is a false positive, your only miri changes are to tests and `Cargo.lock` was not changed.

@rustbot ready

**Comment by saethlin** [comment]
The message is not a false positive, but it's also not supposed to be an indication that you shouldn't do what you're doing. Your change to the Miri subtree is good (assuming tests pass).

**Comment by m-ou-se** [comment]
FCP completed [here](https://github.com/rust-lang/rust/issues/80377#issuecomment-1509863000)

@bors r+

**Comment by usbalbin** [comment]
Thanks :)

**Pull request merged**
