### PR TITLE
Parse bang macro as a statement when used in trailing expr position

### PR DESCRIPTION
**Pull request by Aaron1011**
cc #33953

Currently, the following code produces an error

```rust
fn main() {
    macro_rules! a {
        ($e:expr) => { $e; }
    }
    a!(true)
}
```

With this change, it now compiles, since we parse `a!(true)` as a
statement.

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
There's a large number of legitimate regressions, due to some trailing macro expressions now evaluating to `()`.

It should be possible to make this a warning - we continue to parse trailing macro flags as expressions, but add a flag that makes us emit a warning during typecheck if the type of the expression is not `()`

However, it might be worthwhile to check with the lang team to make sure this is something that we want to do.

**Comment by Aaron1011** [comment]
On further investigation, many (if not all) of the regressions appear to be due to an interaction with semicolons in macro bodies (see https://github.com/rust-lang/rust/pull/78685)

If we have a macro like:

```rust
macro_rules! a {
    ($e:expr) => { $e; }
}
```

we ignore the trailing semicolon if the macro is used in expression position:

https://github.com/rust-lang/rust/blob/c919f490bbcd2b29b74016101f7ec71aaa24bdbb/compiler/rustc_expand/src/mbe/macro_rules.rs#L151-L156

With this change, we now parse the macro body in statement position, so the above code is never run.

To make this into a warning, we would want to extend the above workaround to apply to statements, but only when the original macro call occurred as the trailing statement in a block.

**Comment by petrochenkov** [comment]
>To make this into a warning, we would want to extend the above workaround to apply to statements, but only when the original macro call occurred as the trailing statement in a block.

Yes, I think it would be a good strategy for the last statement of expanded code to inherit "expr-ness" from the macro call for the purpose of this hack.

I don't have any other specific ideas right now, but I think the general guiding principle here is that expansion should be built and work using a holistic token-based model as if we didn't have any compatibility restrictions. Then minimal compatibility hack would be applied on top of that model in such way that they could report warnings or be turned off at edition boundary.

**Comment by crlf0710** [comment]
@Aaron1011 Ping from triage: Any updates on this?

**Comment by Aaron1011** [comment]
I'll revist this after https://github.com/rust-lang/rust/pull/79819 is merged

**Comment by petrochenkov** [comment]
#79819 was merged.

**Comment by crlf0710** [comment]
@Aaron1011 Ping from triage, it seems the related pr has been merged. Have you got any chance to work on this again?

**Comment by JohnCSimon** [comment]
@Aaron1011 Ping from triage, it seems the related pr has been merged. Have you got any chance to work on this again?

Can you post status on this?

**Pull request closed without merging**
