### PR TITLE
Fix attributes position in type declaration

### LINKED ISSUE #59797: Trait definition method is badly aligned when there is attribute(s)
A nice picture:

Screenshot from 2019-04-08 16-27-29

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #59797.

r? @rust-lang/rustdoc

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Can you provide a screenshot of what it looks like with this change? I can see the "before" screenshot in the linked issue, but i want to make sure that it looks right afterward.

**Comment by GuillaumeGomez** [comment]
Sure, here it is:

Screenshot 2019-04-12 at 00 00 50

**Review by QuietMisdreavus — APPROVED** [review]
Thanks for the screenshot! This looks good to go.

**Pull request merged**
