### PR TITLE
update libbacktrace

### PR DESCRIPTION
**Pull request by RalfJung**
It seems like previously we were on a tag of the backtrace repo; not sure if there is a policy that it should always be a tag?

Cc https://github.com/rust-lang/backtrace-rs/pull/462 @alexcrichton @DrMeepster

### CODE REVIEW

**Comment by klensy** [comment]
Is this will work? backtrace_rs imported somehow hacky
https://github.com/rust-lang/rust/blob/cd73afadae5b0163f9285f1b5edbbd1c84fde410/library/std/src/lib.rs#L578-L580

and it's deps defined here
https://github.com/rust-lang/rust/blob/cd73afadae5b0163f9285f1b5edbbd1c84fde410/library/std/Cargo.toml#L25-L33

So with that deps it can be not working as intended.

**Comment by RalfJung** [comment]
CI is green though... :shrug: no idea how this is usually handled.
Probably the toml files should be synced? Looks like they already are a bit out of sync though.

**Comment by RalfJung** [comment]
Actually bumping the version of miniz_oxide leads to build failures:
```
   Compiling simd-adler32 v0.3.4
error[E0463]: can't find crate for `std`

error[E0463]: can't find crate for `core`
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-adler32-0.3.4/src/imp/avx2.rs:49:7
   |
49 |   use core::arch::x86_64::*;
   |       ^^^^ can't find crate

error[E0463]: can't find crate for `core`
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-adler32-0.3.4/src/imp/sse2.rs:49:7
   |
49 |   use core::arch::x86_64::*;
   |       ^^^^ can't find crate

error[E0463]: can't find crate for `core`
  --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-adler32-0.3.4/src/imp/ssse3.rs:49:7
   |
49 |   use core::arch::x86_64::*;
   |       ^^^^ can't find crate

[...]

error: could not compile `simd-adler32` due to 149 previous errors
```

**Comment by RalfJung** [comment]
This is caused by [their Cargo.toml](https://github.com/Frommi/miniz_oxide/blob/991e3154b49e56cf716e51d1abd0f9c8d704a258/miniz_oxide/Cargo.toml)
```
# Internal feature, only used when building as part of libstd, not part of the
# stable interface of this crate.
rustc-dep-of-std = ['core', 'alloc', 'compiler_builtins', 'adler/rustc-dep-of-std', 'simd-adler32/std']
```
This enables the (off-by-default) simd-adler32 feature, and that crate does not seem to support being built in the rustc workspace.
Cc @oyvindln

**Comment by klensy** [comment]
> This is caused by [their Cargo.toml](https://github.com/Frommi/miniz_oxide/blob/991e3154b49e56cf716e51d1abd0f9c8d704a258/miniz_oxide/Cargo.toml)
> 
> ```
> # Internal feature, only used when building as part of libstd, not part of the
> # stable interface of this crate.
> rustc-dep-of-std = ['core', 'alloc', 'compiler_builtins', 'adler/rustc-dep-of-std', 'simd-adler32/std']
> ```

Cargo's weak deps should solve this ;-)

**Comment by RalfJung** [comment]
Yeah.^^ But we don't even need them here since it seems the rustc workspace doesn't need the simd-adler feature. So that part can just be removed from rustc-dep-of-std I think.

**Comment by oyvindln** [comment]
> This is caused by [their Cargo.toml](https://github.com/Frommi/miniz_oxide/blob/991e3154b49e56cf716e51d1abd0f9c8d704a258/miniz_oxide/Cargo.toml)
> 
> ```
> # Internal feature, only used when building as part of libstd, not part of the
> # stable interface of this crate.
> rustc-dep-of-std = ['core', 'alloc', 'compiler_builtins', 'adler/rustc-dep-of-std', 'simd-adler32/std']
> ```
> 
> This enables the (off-by-default) simd-adler32 feature, and that crate does not seem to support being built in the rustc library workspace. Cc @oyvindln

Right, simd-adler32 probably shouldn't have be added to rustc-dep-of-std then, didn't really catch that when approving the PR adding the feature. Can remove it and update if you want.

**Comment by est31** [comment]
> backtrace_rs imported somehow hacky

BTW if anyone wonders why, this approach has been done by 06d565c967bfb7c6ff52a991bbe47b4a2a25de3e so that backtrace can use the file system:

> While today it's used as a crates.io dependency, this commit
switches the `backtrace` crate to a submodule of this repository which
will need to be updated manually. This is not done lightly, but is
thought to be the best solution. The primary reason for this is that the
`backtrace` crate needs to do some pretty nontrivial filesystem
interactions to locate debug information. Working without `std::fs` is
not an option, and while it might be possible to do some sort of
trait-based solution when prototyped it was found to be too unergonomic.
Using a submodule allows the `backtrace` crate to build as a submodule
of the `std` crate itself, enabling it to use `std::fs` and such.

**Comment by Mark-Simulacrum** [comment]
I think for our purposes being slightly out of sync in terms of dependencies (even across, technically, major versions) is not a huge deal, though would be nice to clean up if someone wanted to do so. I don't think it should block this PR unless we encounter unexpected trouble in CI though.

@bors r+ rollup=never

**Comment by oyvindln** [comment]
> > This is caused by [their Cargo.toml](https://github.com/Frommi/miniz_oxide/blob/991e3154b49e56cf716e51d1abd0f9c8d704a258/miniz_oxide/Cargo.toml)
> > ```
> > # Internal feature, only used when building as part of libstd, not part of the
> > # stable interface of this crate.
> > rustc-dep-of-std = ['core', 'alloc', 'compiler_builtins', 'adler/rustc-dep-of-std', 'simd-adler32/std']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This enables the (off-by-default) simd-adler32 feature, and that crate does not seem to support being built in the rustc library workspace. Cc @oyvindln
> 
> Right, simd-adler32 probably shouldn't have be added to rustc-dep-of-std then, didn't really catch that when approving the PR adding the feature. Can remove it and push a new version if you want.

Aight, published an update with simd-adler32 removed from rust-dep-of-std in case one wants to do an update on it.

**Pull request merged**
