### PR TITLE
support PGO on custom project

### PR DESCRIPTION
**Pull request by csmoe**
make PGO easier for custom toolchain distribution.

r? @Kobzol

### CODE REVIEW

**Comment by Kobzol** [comment]
Hi, the use-case seems reasonable. Although care should be taken that the custom command will generate the profiles into the correct files - you will thus probably want to distinguish between gathering profiles for LLVM/Rustc/BOLT even for custom runners, and pass the correct env. variables to them.

Therefore, I would prefer a more "OOP-like" implementation, to reduce complexity and conditions in the logic of the individual stages, and also to move the various benchmark logic to a single place.

Something like
```python
class BenchmarkRunner:
    def run_rustc(self, pipeline: Pipeline):
    def run_llvm(self, pipeline: Pipeline):
    def run_bolt(self, pipeline: Pipeline):

    # (or maybe just a single method that would receive an enum - Rustc/LLVM/BOLT)

class DefaultBenchmarkRunner(BenchmarkRunner):
    def run_rustc(self, pipeline: Pipeline):
         self.run_compiler_benchmarks(
            pipeline,
            profiles=["Check", "Debug", "Opt"],
            scenarios=["All"],
            crates=RUSTC_PGO_CRATES,
            env=dict(
                LLVM_PROFILE_FILE=str(pipeline.rustc_profile_template_path())
            )
        )
   ...


class CustomBenchmarkRunner(BenchmarkRunner):
    ...
```
and then some function that creates the corresponding `BenchmarkRunner` from the environment at the beginning of the script. The selected runner would be then passed to the individual stages (it could also be stored within Pipeline directly to make it easier to access, it's not super nice because of the cyclic dependency, but it should be fine here).

**Review by Kobzol — COMMENTED** [review]
Good, this is how I imagined it :) Is this enough for you? Or do you also want to implement support for custom runners in this PR?

**Comment by csmoe** [comment]
Really thanks for your kind review. 
I haven't written much python, I'm imaging a common workflow as: 
```python
# content of a custom build.py

from stage-build import BenchmarkRunner, run
class CustomRunner(BenchmarkRunner):
    ...
runner = CustomRunner()
run(runner)
```

So I move the logic in `__main__` into a `run` function for external invocation, is that ok? If so, I'm ready to change this draft to a formal PR.

**Comment by Kobzol** [comment]
Alright, that sounds reasonable :) Let's see if everything still works.

@bors try @rust-timer queue

**Comment by Kobzol** [comment]
Perf looks good, LGTM.

I don't have merge right, so reassigning.

r? @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
@bors r=Kobzol

This seems fine to me, though of course no stability guarantees are offered on these scripts.

**Pull request merged**
