### PR TITLE
Feature gate async methods

### LINKED ISSUE #60069: Can define and use async fn without feature gate on nightly
```rust
#![feature(futures_api)]

pub struct Foo;

impl Foo {
    pub async fn foo(&mut self) {
    }
}

fn main() {
    let mut bar = Foo;
    bar.foo();
}
```

([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9b689ceb9145b9ba586b1a923bbad4bf)) runs without error, for some reason the `async_await` feature gate is not required.

(cc @nikomatsakis @cramertj)

### PR DESCRIPTION
**Pull request by varkor**
Fixes https://github.com/rust-lang/rust/issues/60069.

### CODE REVIEW

**Comment by varkor** [comment]
(Forgot to re-`--bless` after fixing a typo.)

@bors r=cramertj

**Comment by varkor** [comment]
`async fn` isn't valid in trait methods at the moment, but I realised the existing feature gate was missing a test, so I've added one just to make certain we don't accidentally stabilise something we don't want to.

@bors r=cramertj

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/60100#issuecomment-484740120, @bors r-

**Comment by lnicola** [comment]
```
[00:55:59] - Some errors occurred: E0223, E0599.
[00:55:59] + Some errors have detailed explanations: E0223, E0599.
```

Looks like the error message needs to be updated for https://github.com/rust-lang/rust/pull/60046?

**Comment by varkor** [comment]
@lnicola: thanks!

@bors r=cramertj

**Pull request merged**
