### PR TITLE
Revert "impl From<&[T; N]> and From<&mut [T; N]> for Vec<T>"

### PR DESCRIPTION
**Pull request by shepmaster**
This reverts commit 5dd702763ae0e112332a4447171adbed51aeee3d.

### CODE REVIEW

**Comment by shepmaster** [comment]
r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs

**Comment by lcnr** [comment]
fixes #96074 which is already on beta

**Comment by jdahlstrom** [comment]
> fixes #96074 which is already on beta

Thanks. I wondered why.

**Comment by lcnr** [comment]
spurious probably

@bors retry

**Pull request merged**
