### PR TITLE
Fix trans coercions of Box<[T]> and Box<Trait> in match arms

### LINKED ISSUE #20055: Panic during unit tests (coerce_match)
Currently on bd90b93

Running on OSX

cc'ing @kballard and @barosl since I saw both of them also had this issue in #rust-internals on IRC

```
...
test [run-pass] run-pass/yield2.rs ... ok
test [run-pass] run-pass/zero-size-type-destructors.rs ... ok
test [run-pass] run-pass/yield1.rs ... ok
test [run-pass] run-pass/vector-sort-panic-safe.rs ... ok
test [run-pass] run-pass/yield.rs ... ok

using metrics ratchet: tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-rpass-metrics.json
result of ratchet: 0 metrics added, 0 removed, 0 improved, 0 regressed, 0 noise
updated ratchet file

failures:

---- [run-pass] run-pass/coerce-match.rs stdout ----

error: test run failed!
status: signal: 4
command: x86_64-apple-darwin/test/run-pass/coerce-match.stage2-x86_64-apple-darwin
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[run-pass] run-pass/coerce-match.rs' panicked at 'explicit panic', /Users/coreyf/Development/rust/src/compiletest/runtest.rs:1487



failures:
    [run-pass] run-pass/coerce-match.rs

test result: FAILED. 1745 passed; 1 failed; 27 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/coreyf/Development/rust/src/compiletest/compiletest.rs:267
make: *** [tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-rpass.ok] Error 101
```

### PR DESCRIPTION
**Pull request by pnkfelix**
trans: When coercing to `Box<Trait>` or `Box<[T]>`, leave datum in it's original L-/R-value state.

This fixes a subtle issue where temporaries were being allocated (but not necessarily initialized) to the (parent) terminating scope of a match expression; in particular, the code to zero out the temporary emitted by `datum.store_to` is only attached to the particular match-arm for that temporary, but when going down other arms of the match expression, the temporary may falsely appear to have been initialized, depending on what the stack held at that location, and thus may have its destructor erroneously run at the end of the terminating scope.

FIx #20055.

(There may be a latent bug still remaining in `fn into_fat_ptr`, but I am so annoyed by the test/run-pass/coerce_match.rs failures that I want to land this now.)

### CODE REVIEW

**Comment by richo** [comment]
ooc, is this related to the failure I've been seeing on OSX for a while?

```
failures:
    [run-pass] run-pass/coerce-match-calls.rs
    [run-pass] run-pass/coerce-match.rs
```

(There's no output, it just fails).

**Comment by pnkfelix** [comment]
@richo yes, this is meant to fix that.

**Pull request merged**
