### PR TITLE
Doc test command

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Wouldn't this be better as a `--doc` flag to the existing `test` command, to only do doctests on paths that would do unit tests? Or am i interpreting this wrong?

**Comment by Mark-Simulacrum** [comment]
Yeah, I think I agree with @QuietMisdreavus -- we should integrate this into `test::Crate` and `test::CrateLibrustc` by adding a `--doc` flag to `x.py test` (edit `src/bootstrap/flags.rs`).

**Comment by GuillaumeGomez** [comment]
Ok, I'll update it in this way.

**Pull request merged**
