### PR TITLE
Optimize `Rc<T>::default`

### PR DESCRIPTION
**Pull request by slanterns**
The missing piece of https://github.com/rust-lang/rust/pull/131460.

Also refactored `Arc<T>::default` by using a safe `NonNull::from(Box::leak(_))` to replace the unnecessarily unsafe call to `NonNull::new_unchecked(Box::into_raw(_))`. The remaining unsafety is coming from `[Rc|Arc]::from_inner`, which is safe from the construction of `[Rc|Arc]Inner`.

### CODE REVIEW

**Comment by slanterns** [comment]
`@rc_default_inplace = unnamed_addr alias ptr (), ptr @arc_default_inplace`

Whoa

**Comment by slanterns** [comment]
CI green. @rustbot ready
r? @ibraheemdev since you reviewed the previous PR :)

**Comment by ibraheemdev** [comment]
cc @rust-lang/opsem regarding `NonNull::from(Box::leak(..))`, I'm not sure we want to introduce this pattern into std (https://github.com/rust-lang/unsafe-code-guidelines/issues/316)

I'm also happy to approve this without the `Box::leak` change if you wish.

**Comment by slanterns** [comment]
The current implementation of `Rc::new` is already using such pattern: https://github.com/rust-lang/rust/blob/86d69c705a552236a622eee3fdea94bf13c5f102/library/alloc/src/rc.rs#L393.

**Comment by Kobzol** [comment]
@rust-timer build c581beefaa629b6a042e02b04e3be6dd82073420

**Comment by CAD97** [comment]
The regression is for optimizing webrender. This is potentially a *good* sign, actually, as it likely indicates LLVM doing more optimization work on a codebase that *heavily* utilizes `Rc`/`Arc`, and negligible impact to projects that use the container less ubiquitously than webrender.

Notably, this *does not* indicate that the optimization had the opposite impact as intended. To see the optimization impact, we would need runtime benchmarks, not optimization time benchmarks.

**Comment by RalfJung** [comment]
> o see the optimization impact, we would need runtime benchmarks, not optimization time benchmarks.

Except if the optimization kicks in inside rustc itself, at which point compilation time benchmarks *are* runtime benchmarks. :)

**Comment by Kobzol** [comment]
I just wanted to see if this is the cause of the overall regressions. This probably caused the webrender regression, but probably not the rest. Anyway, no need to dig deeper into this, I think, seems that LLVM just spends more time optimizing.

@rustbot label: +perf-regression-triaged

**Pull request merged**
