### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This backports:

*  Update RLS and Rustfmt #81027 
*  bump rustfmt to v1.4.32 #81093 
*  Fix handling of malicious Readers in read_to_end #80895 
*  Fix broken ./x.py install #80514 
*  Fix x.py install not working with relative prefix #80797 
*  [security] Update mdbook #80688 
*  rustdoc: Render visibilities succinctly #80368 

r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r-

@Xanewok @calebcartwright it looks like the ap crates are relying on const generics to be stable, but the backports of recent bumps push them back to 1.50 where const generics are not yet stable. This has a number of implications:
* we can't compile these crates easily, though there may be some hacks I can do in rustbuild to get things to work
* we are presumably using a const-generics-stable parser, which has stability implications for rustfmt/rls (though not too significant as that feature is already stable in 1.51)

we'll need to resolve this before we can land this, but if it takes more than a few days I'll probably drop those updates from this PR

**Comment by calebcartwright** [comment]
Might take some juggling but perhaps as an alternative I could backport the commits for the bug fix to the rustfmt-1.4.30 branch in the rustfmt repo. Then rustfmt submod here on beta could stay on the 1.4.30 branch and just pull in the commit, and then do something similar on the RLS maybe in a new branch off whatever's currently in beta?

**Comment by Mark-Simulacrum** [comment]
That sounds like a good strategy to me.

**Comment by calebcartwright** [comment]
Done on the rustfmt side. @Xanewok - let me know if I can do anything to help on the RLS side. Based on what's currently on beta I'm guessing/hoping it's just a matter of bumping the 1.4.29 rustfmt dependency currently in the submod to the now-updated 1.4.30 branch, but not sure if there's anything else on the RLS side that needed to be backported as well

**Comment by Xanewok** [comment]
Created a https://github.com/rust-lang/rls/tree/rust-1.50 branch that points to the new `rustfmt-v1.4.30` branch (updates from 1.4.29), this should be good to go from RLS' side.

**Pull request merged**
