### PR TITLE
`simplify_type` improvements and cursed docs

### PR DESCRIPTION
**Pull request by lcnr**
the existing `TreatParams` enum pretty much mixes everything up. Not sure why this looked right to me in #94057

This also includes two changes which impact perf:
- `ty::Projection` with inference vars shouldn't be treated as a rigid type, even if fully normalized
- `ty::Placeholder` only unifies with itself, so actually return `Some` for them

r? @nikomatsakis

### CODE REVIEW

**Comment by lcnr** [comment]
I feel like `SimplifiedType` isn't a good name here. Maybe something like `RigidTyConstructor` or something like that would be better :thinking:

**Review by nikomatsakis — APPROVED** [review]

**Comment by lcnr** [comment]
oh, we've used the `@bors try` commit to actually merge this PR? Idk if that's an issue? :thinking: cc @rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
Gah. https://github.com/rust-lang/homu/issues/47 is the issue for this, we'll need to back this out from master I think, I'm not sure whether a force push dropping it is the best idea.

**Comment by Mark-Simulacrum** [comment]
To follow up on the merge -- we manually ran CI on the merged commit, which thankfully passed. See https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/try-based.20merge.20into.20master for some discussion.

**Pull request merged**
