### PR TITLE
Updated E0527 to new error format

### LINKED ISSUE #36113: E0527 needs to be updated to new format
From: src/test/compile-fail/E0527.rs

E0527 needs a span_label, updating it from:

```
error[E0527]: pattern requires 2 elements but array has 4
  --> src/test/compile-fail/E0527.rs:16:10
   |
16 |         &[a, b] => { //~ ERROR E0527
   |          ^^^^^^
```

To:

```
error[E0527]: pattern requires 2 elements but array has 4
  --> src/test/compile-fail/E0527.rs:16:10
   |
16 |         &[a, b] => { //~ ERROR E0527
   |          ^^^^^^ expected 4 elements
```

### PR DESCRIPTION
**Pull request by Cobrand**
- Closes #36113

### CODE REVIEW

**Comment by Cobrand** [comment]
@jonathandturner I didn't notice we could pick an assignee when starting a PR ; just for future notice is there an way to change the assignee after a pull request has been opened ?

The Travis check is failing but I'm not sure it comes from my code.

Also, I didn't have to change any test (they were all working even after the changes), but should I update at least the E0527.rs so it fits exactly the error message ?

**Comment by jonathandturner** [comment]
@Cobrand - you can use the same r? but as a new comment.  Like this:

r? @jonathandturner

**Comment by jonathandturner** [comment]
@Cobrand - you may also want to talk with @ashrko619, since they signed up for E0527 (see https://github.com/rust-lang/rust/issues/35233 for the list)

**Comment by Cobrand** [comment]
@ashrko619 Sorry it was my bad, I didn't see you had to answer the main thread to solve the issue, I just saw it undone and decided to do a PR. Would you mind passing this to me since I have already a PR done or do you have something ready already ?

**Comment by ashrko619** [comment]
@Cobrand @jonathandturner  No issues. I haven't yet started working on it :)

**Comment by jonathandturner** [comment]
Sounds good.  @Cobrand - I'll update this one to point to you

**Comment by jonathandturner** [comment]
Alright, now to review...

@Cobrand - looks like it's a good start.  The next thing to do is to make sure that the unit tests are updated to test for this new label.  You can read how to do this in the Extra Credit section of the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html).  There's a quirk of the unit test system that means you'll need a NOTE before it will test the for the labels.

**Comment by jonathandturner** [comment]
@Cobrand - looks like this one is getting close.  When you're ready, squash the 3 commits down to 1 and ping me and I'll review.

**Comment by Cobrand** [comment]
@jonathandturner it should be fine now.

**Comment by jonathandturner** [comment]
Great.

@bors r+ rollup

**Pull request merged**
