### PR TITLE
Try using a `dyn Debug` trait object instead of a closure

### PR DESCRIPTION
**Pull request by oli-obk**
These closures were introduced in https://github.com/rust-lang/rust/pull/93098

let's see if we can't use fmt::Arguments instead

cc @Aaron1011

### CODE REVIEW

**Comment by compiler-errors** [comment]
Noice

**Comment by petrochenkov** [comment]
r=me if the perf is ok.
@rustbot author

**Review by petrochenkov — APPROVED** [review]

**Comment by workingjubilee** [comment]
smells vaguely like more code being inlined so the happy path gets longer.

**Comment by oli-obk** [comment]
My guess was formatting infra just taking up more space than capturing a few variables in a closure

**Comment by oli-obk** [comment]
Much better, now I probably need to move the panic into a cold function or sth. Or we just land it and take the hit?

**Comment by RalfJung** [comment]
> These closures were introduced in #93098
> 
> let's see if we can't use fmt::Arguments instead

Just out of curiosity, which problem does this fix?

**Comment by oli-obk** [comment]
This allows such functions to become hooks (because hooks, like queries, print all their arguments via `instrument` ), which in turn allows me to eliminate more methods and state from the incremental-untracked CrateStore trait.

Unclear if we need that, but I felt like the closure API was weird and deserved a refactoring on its own

**Pull request merged**
