### PR TITLE
replace `BitAndAssign` example with something more evocative

### PR DESCRIPTION
**Pull request by matthew-piziak**
This is the augmented-assignment version of PR #35809.

r? @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Like discussed on IRC, please write simpler examples.

**Comment by matthew-piziak** [comment]
Copy-pasting the IRC discussion here. I'd link to the logs, but I can't prevent them from truncating prematurely.

https://gist.github.com/matthew-piziak/a2dd18e897eb3d4113459a945d85296b

**Comment by ollie27** [comment]
I like this example, however it's not clear what should happen if the `Vec`s are not the same length. I think the easiest thing to do is use an array instead. Doing that and simplifying the implementation gives something like the following:
```rust
use std::ops::BitAndAssign;

#[derive(Debug, PartialEq)]
struct BooleanVector {
    value: [bool; 4],
}

impl BitAndAssign for BooleanVector {
    fn bitand_assign(&mut self, rhs: Self) {
        for (x, y) in self.value.iter_mut().zip(&rhs.value) {
            *x &= *y;
        }
    }
}

fn main() {
    let mut bv = BooleanVector { value: [true, true, false, false] };
    bv &= BooleanVector { value: [true, false, true, false] };
    let expected = BooleanVector { value: [true, false, false, false] };
    assert_eq!(bv, expected);
}
```

**Comment by matthew-piziak** [comment]
I've taken the improvements in https://github.com/rust-lang/rust/pull/35993 and applied them to this PR. I figured that a simple `assert_eq!` was cleaner than enforcing a particular length in the struct, but let me know what you think.

**Comment by GuillaumeGomez** [comment]
Thanks!

@bors: r+ rollup

**Pull request merged**
