### PR TITLE
Add Fn impl to Arc

### PR DESCRIPTION
**Pull request by bsodmike**
This commit refers to the discussion in #89727

Please let me know if any further improvements are needed :)

Thanks!

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage: 
@bsodmike - Can you post your status on this PR?

**Comment by Others** [comment]
I think these missing implementations are a minor language wart, and we should fix them somehow.

Is it possible to get a crater run for the PR to see if this theoretical breakage exists in practice?

I'm happy to rebase this if the original owner is unavailable.

**Comment by Mark-Simulacrum** [comment]
Following up on this (I missed https://github.com/rust-lang/rust/pull/89771#issuecomment-942240050 in my notifications) now -- it is somewhat unfortunate these impls do not exist, but I don't think the presented motivation is sufficiently strong to override the breaking change concern (which crater cannot really resolve).

The specific pattern mentioned is fairly rare (bounding an associated type with Fn) and substituting a user-defined trait, perhaps one deref'ing to Fn, should work I think.

**Comment by Dylan-DPC** [comment]
Closing this based on https://github.com/rust-lang/rust/pull/89771#issuecomment-988326997

**Pull request closed without merging**
