### PR TITLE
Use Travis trusty infrastructure

### PR DESCRIPTION
**Pull request by arcnmx**
Moves back away from docker but still uses the GCE infrastructure with a system-installed LLVM. 

See http://docs.travis-ci.com/user/trusty-ci-environment/

### CODE REVIEW

**Comment by arcnmx** [comment]
I can't test this myself since my own account has a 50 minute build time limit, but generally docker just seemed kind of redundant even if it only maybe adds a few minutes to the build time. With Rust's special travis settings hopefully it builds!

**Comment by alexcrichton** [comment]
Hm so on one hand I kinda like using docker because it makes the builds very easily reproducible as well as clearly showing us what our dependencies are (I think the Travis images come with some extra goodies by default), but on the other hand it does seem like it may just be unnecessary here. I'm fine merging, just waiting on travis to report back!

**Comment by arcnmx** [comment]
Makes sense, I also considered the same thing (and wondered if I should keep the dockerfile around just in case). Travis does have a minimal image though, which should help with that concern. I'll give it a try after this queued build hits.

**Comment by frewsxcv** [comment]
You can use the `addons > apt > packages` feature in travis.yml files to specify apt deps instead of manually installing them if you want. We do that in servo

https://github.com/servo/servo/blob/master/.travis.yml

**Comment by frewsxcv** [comment]
More info here

http://docs.travis-ci.com/user/apt/

**Comment by arcnmx** [comment]
Ah right, I was doing that on the container infrastructure but moved to the commands on GCE. I'll see about reverting that back again.

**Comment by sanxiyn** [comment]
While we're at it, can we remove or revise "Real testing happens on http://buildbot.rust-lang.org/" comment? It was introduced in #26224 when Travis only ran "make tidy", therefore no real testing. Maybe "Testing also happens" etc.

**Comment by arcnmx** [comment]
Well, it's still correct in that buildbot tests all supported platforms while Travis only tests x86_64 Linux. It's at best supplemental smoke testing, though I'm open to suggestions for a better explanation there.

**Comment by alexcrichton** [comment]
OK looks like this passed just fine, so I'd be fine merging with the `apt` addons section that @frewsxcv mentioned!

**Comment by arcnmx** [comment]
I wasn't able to get the `apt` addon approach to work as the sources for trusty don't seem to be in their [whitelist](https://github.com/travis-ci/apt-source-whitelist).

[See my various attempts here >_>](https://travis-ci.org/arcnmx/rust/builds)

**Comment by alexcrichton** [comment]
@bors: r+ 1181ca4b515cc7bb68ab62f99999d06c0e6f763a

ah ok!

**Pull request merged**
