### PR TITLE
Split the type context into a global and a local (inference-only) one.

### PR DESCRIPTION
**Pull request by eddyb**
After this change, each `InferCtxt` creates its own local type interner for types with inference by-products.
Most of the code which handles both a global and a local interner uses `'gcx` and `'tcx` for them.
A reference to the type context in that situation (e.g. `infcx.tcx`) is `TyCtxt<'a, 'gcx, 'tcx>`.
The global type context which used to be `&'a TyCtxt<'tcx>` is now `TyCtxt<'a, 'tcx, 'tcx>`.

In order to minimize the number of extra lifetime parameters, many functions became methods.
Where possible (some inherent impls), lifetime parameters were added on the impl, not each method.

As inference by-products no longer escape their inference contexts, memory usage is lower.
Example of `-Z time-passes` excerpt for `librustc`, stage1 (~100MB gains):
Before "rustc: Split local type contexts interners from the global one.":

```
time: 0.395; rss: 335MB item-types checking
time: 15.392; rss: 472MB        item-bodies checking
time: 0.000; rss: 472MB drop-impl checking
time: 1.140; rss: 478MB const checking
time: 0.139; rss: 478MB privacy checking
time: 0.024; rss: 478MB stability index
time: 0.072; rss: 478MB intrinsic checking
time: 0.038; rss: 478MB effect checking
time: 0.255; rss: 478MB match checking
time: 0.128; rss: 484MB liveness checking
time: 1.372; rss: 484MB rvalue checking
time: 1.404; rss: 597MB MIR dump
time: 0.809; rss: 599MB MIR passes
```

After:

```
time: 0.467; rss: 337MB item-types checking
time: 17.443; rss: 395MB        item-bodies checking
time: 0.000; rss: 395MB drop-impl checking
time: 1.423; rss: 401MB const checking
time: 0.141; rss: 401MB privacy checking
time: 0.024; rss: 401MB stability index
time: 0.116; rss: 401MB intrinsic checking
time: 0.038; rss: 401MB effect checking
time: 0.382; rss: 401MB match checking
time: 0.132; rss: 407MB liveness checking
time: 1.678; rss: 407MB rvalue checking
time: 1.614; rss: 503MB MIR dump
time: 0.957; rss: 512MB MIR passes
```

**NOTE**: Functions changed to methods weren't re-indented to keep this PR easier to review.
Once approved, the changes will be mechanically performed.
However, indentation changes of function arguments are there - and I believe there's a way to hide whitespace-only changes in diffs on GitHub.

### CODE REVIEW

**Comment by durka** [comment]
Nice memory savings, but 3.5x time regression in item-bodies checking?

**Comment by eddyb** [comment]
@durka Just noticed that actually, will need to investigate. We might have to make lifting cheaper.

**Comment by eddyb** [comment]
About 25% of the time appears to be spend in `malloc` and `free`.
I've tried reusing arenas across function-local type contexts during type-checking (internally each `TypedArena` can reuse only the largest chunk it holds) but it doesn't appear to help.

**Comment by arielb1** [comment]
What are the callers?

**Comment by eddyb** [comment]
@arielb1 I believe I'd need `perf record -g` for that and DWARF debug info and last time I tried something like that it was writing GBs of traces. I'm going to have to do it anyway in the next few days.

**Comment by eddyb** [comment]
I've found a simple way of turning the split off while keeping all of the infrastructural changes, if we want to merge this without any significant impact on performance.

But it turns out that making `tcx.lift(x)` return `None` if `x.needs_infer() && tcx.is_global()` is enough to trigger the performance problem, *without* actually using the local interner at all.

So either the cost of checking `needs_infer` is really that high, or I broke one of the caches which depend on it.

**Comment by eddyb** [comment]
@nikomatsakis I'm pretty sure the problem here is the global selection/evaluation caches which used to allow `TyInfer(FreshTy(_))` and friends but those have `HAS_TY_INFER` just like any other inference variables so they get stuck in the local type contexts.

Should I just add a separate flag for freshened types, and keep them in the global context, just for the caches?

**Comment by nikomatsakis** [comment]
@eddyb 

> Should I just add a separate flag for freshened types, and keep them in the global context, just for the caches?

Hmm. Seems worth a try! I'm a bit wary of removing `TY_INFER` from freshened types -- that is, I'm frightened that there will be existing logic that was assuming that they count. We could I guess add a new flag for "local context only" that is set for all ty-infer *except* freshened types.

**Comment by eddyb** [comment]
@nikomatsakis I'd keep the current behavior of `needs_infer` and friends and only ignore the `TY_FRESH` flag when checking whether something must be interned in the local type context.

**Comment by eddyb** [comment]
@durka @arielb1 Now that I solved the cache problem, the times look good again, although they all seem slightly increased.

**Comment by nikomatsakis** [comment]
@eddyb r=me

you are my hero 👑

**Pull request merged**
