### PR TITLE
enable tools to use test runners programmatically

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by est31** [comment]
@oli-obk the travis CI error seems relevant.

**Comment by aturon** [comment]
cc @rust-lang/libs, potential new public API surface.

**Comment by alexcrichton** [comment]
To be clear, this is an unstable library, so we're not committing to anything yet.

**Comment by oli-obk** [comment]
> To be clear, this is an unstable library, so we're not committing to anything yet.

I'm fully aware of this, but I believe that experimentation with the interface can help contribute to a potential future interface that will be stabilized.

**Comment by sfackler** [comment]
What does this enable that use of the third party rustc-test crate doesn't?

**Comment by oli-obk** [comment]
> What does this enable that use of the third party rustc-test crate doesn't?

I thought `rustc-test` is just a copy of the internal crate, but with major version bumps instead of a stable API. I can submit this patch to the `rustc-test` crate, but it will make it much harder for @SimonSapin to update it, if the crate diverges too much from the internals crate.

**Comment by SimonSapin** [comment]
For what it’s worth I haven’t updated `rustc-test` since I first made it. But yes, if you want to make major changes I’d suggest forking and making them in a separate crate. This specific PR seems small enough, though. I’d merge it in `rustc-test`, I don’t think it’s diverging enough to make merges difficult. I’ll also give you access to the repo and crates.io if you’re interested ;)

**Comment by oli-obk** [comment]
> I’ll also give you access to the repo and crates.io if you’re interested ;)

sgtm

> This specific PR seems small enough, though. I’d merge it in rustc-test

I opened a PR there, feel free to close this PR if the extra API is deemed excessive for a rustc crate.

**Comment by aturon** [comment]
Ping @brson, I suspect you have opinions and want to check in before merging.

**Comment by aturon** [comment]
I'm going to go ahead and r+. @brson, if you want to revisit later, we can always revert; it's unstable.

@bors: r+ rollup

**Pull request merged**
