### PR TITLE
more efficient is_ascii methods

### PR DESCRIPTION
**Pull request by gilescope**
These formulations seem to compile down to less (optimised) machine code. (The 0b10_0000 is making it lower case like in to_digit here https://github.com/rust-lang/rust/blob/ac8b11810f4a0def3596ee401feb9ef00015b555/library/core/src/char/methods.rs#L354 )

is_ascii_alphabetic
https://rust.godbolt.org/z/nMdjWz4aG

is_ascii_alphanumeric
https://rust.godbolt.org/z/dejn8P9q5

is_ascii_hexdigit
https://rust.godbolt.org/z/nYsdEPj4e

### CODE REVIEW

**Comment by nikic** [comment]
This is a "logical or" related optimization failure: https://rust.godbolt.org/z/oKabW74zr The logical or does not get converted to a bitwise or due to the nowrap flags (I believe) and that prevents the conditions from being combined.

**Comment by gilescope** [comment]
Isn't that a bitwise OR?  ( https://llvm.org/docs/LangRef.html#or-instruction )
```llvm
  %_3 = or i32 %_5, 32
```

I need a bit more of a hint as to what's wrong as there's not much docs on `llvm nowrap`.

**Comment by frewsxcv** [comment]
Can you add comments in the code describing how this works?

**Comment by Mark-Simulacrum** [comment]
I think comments are definitely necessary if we go with this approach, though I'd also like to see some llvm-mca or similar analysis suggesting this is actually a win (not just marginally shorter assembly). It's definitely less clear in terms of readability, which also IMO has the downside of making it harder to inline these methods if you're OR'ing a few of them together mentally. (The documentation contains similar ranges but is for me a little harder to immediately understand).

**Comment by nikic** [comment]
> I need a bit more of a hint as to what's wrong as there's not much docs on `llvm nowrap`. (or do you mean that is_ascii_alphabetic is good but the other two don't optimise as well as they potentially could?)

Sorry, I meant to say that LLVM is supposed to optimize this and does implement a the necessary optimization, but the presence of `nsw` flags currently prevents it from triggering. It's something that needs to be fixed on the LLVM side, though of course we can directly use the optimized form in the meantime.

**Comment by nikic** [comment]
The issue on the LLVM side is fixed by https://github.com/llvm/llvm-project/commit/982cbed81920b474d41b63760cbde68680b15966.

**Comment by JohnCSimon** [comment]
Ping from triage:
@gilescope  what is the status of this PR? It hasn't been touched in a while.

**Comment by Dylan-DPC** [comment]
Closing this pr as inactive

**Pull request closed without merging**
