### PR TITLE
Stabilize Once::is_completed

### LINKED ISSUE #54890: Tracking issue for std::sync::Once::is_completed
Implemented in #53027

> I propose to expose a way to check if a `Once` instance is initialized. 
>
> I need it in `once_cell`. `OnceCell` is effetively a pair of `(Once, UnsafeCell<Option<T>>)`, which can set the `T` only once. Because I can't check if `Once` is initialized, I am forced to add an indirection and check the value of ptr instead:
> 
> https://github.com/matklad/once_cell/blob/8127a81976c3f2f4c0860562c3f14647ebc025c0/src/lib.rs#L423-L429
> 
> https://github.com/matklad/once_cell/blob/8127a81976c3f2f4c0860562c3f14647ebc025c0/src/lib.rs#L457-L461
> 
> The `parking_lot`'s version of `Once` exposes the state as an enum: https://docs.rs/parking_lot/0.6.3/parking_lot/struct.Once.html#method.state.
> 
> I suggest, for now, just to add a simple `bool` function: this fits my use-case perfectly, exposes less implementation details, and is forward-compatible with more fine-grained state checking.

### PR DESCRIPTION
**Pull request by mjbshaw**
Closes #54890

This function has been around for some time. I haven't seen anyone raise any objections to it. I've personally found it useful myself. It would be nice to finally stabilize it and

### CODE REVIEW

**Review by LukasKalbertodt — APPROVED** [review]
The changes look good to me. 

@rfcbot fcp merge (@rust-lang/libs can someone do this for me? I am not allowed to)

---


**What is stabilized here?** `std::sync::Once::is_completed`:

```rust
pub fn is_completed(&self) -> bool
```

Implemented [1.5 years ago](https://github.com/rust-lang/rust/pull/53027). [The tracking issue](https://github.com/rust-lang/rust/issues/54890) did not bring up any concerns, so I think this is a pretty straight forward addition and I don't see why it shouldn't be stabilized.

**Comment by Mark-Simulacrum** [comment]
The PR originally implementing this also mentioned that doing anything meaningful when the method returns false is likely wrong; do we want to add that to the docs prior to stabilization?

**Comment by mjbshaw** [comment]
@Mark-Simulacrum [I incorporated @nagisa's wording](https://github.com/rust-lang/rust/issues/54890#issuecomment-427643908) in an attempt to make that clearer. I'm hoping the updated verbiage is sufficient. I'm reluctant to explicitly say "don't do anything meaningful if this returns false" because I think that can be easily misunderstood to mean that the `else` branch in `if once.is_completed() { ... } else { ... }` is bad, when in reality it can be perfectly reasonable (i.e., [1](https://github.com/rust-lang/rust/blob/c605199e89572e586a5f37bc698c48b6a10896fb/src/libstd/sync/once.rs#L259-L264), [2](https://github.com/rust-lang/rust/blob/c605199e89572e586a5f37bc698c48b6a10896fb/src/libstd/sync/once.rs#L319-L324)).

**Comment by Mark-Simulacrum** [comment]
Yes that seems better.

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by LukasKalbertodt** [comment]
@mjbshaw Have you forgot to push or am I misunderstanding your last comment?

**Comment by mjbshaw** [comment]
@LukasKalbertodt I don't have any new changes or anything new to push.  Were there specific changes you were looking for?

**Comment by LukasKalbertodt** [comment]
@mjbshaw I thought [this comment of yours](https://github.com/rust-lang/rust/pull/68945#issuecomment-583765903) implied you did some changes to the documentation. But nevermind, my mistake :)

**Comment by jplatte** [comment]
This PR has the GitHub milestone 1.43 but the stabilization attribute says 1.44.0. Which one is correct?

**Pull request merged**
