### PR TITLE
Make deprecation lint `ambiguous_associated_items` deny-by-default

### PR DESCRIPTION
**Pull request by petrochenkov**
As requested by r? @Centril 

cc https://github.com/rust-lang/rust/issues/57644

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot run mode=check-only

**Comment by petrochenkov** [comment]
@craterbot run start=master#df25d79a33b0c82b716699a75a41bfdc6089850a end=try#424a4ae163d6517f301cd4048a4b5dd785be5b2f mode=check-only

**Comment by pietroalbini** [comment]
@bors retry

Let's fix the status for this PR.

**Comment by Centril** [comment]
Not much progress has been made (15 regressed before in https://github.com/rust-lang/rust/pull/57501#issuecomment-453730114); I'll try to make some time for creating PRs for the crates here.

**Comment by Centril** [comment]
# Already migrated

+ bluenrg
+ dbgen
+ jsonrpc-http-server / jsonrpc-http-server-plus might already have migrated but I made a PR for the former anyways and couldn't find anywhere to fix the latter.
+ rocket-http
+ trust-dns-https
+ trust-dns-resolver

# Others

The remaining regressions have PRs filed.

--------------

@petrochenkov r=me rollup if you are happy with ^---

**Comment by varkor** [comment]
Given that there are only four regressions, each of which has an open PR to fix this issue (and none have reverse dependencies), and that this addresses a future compatibility concern, making this lint deny-by-default seems founded.

@bors r+

**Pull request merged**
