### PR TITLE
Encode implied predicates for traits

### LINKED ISSUE #122859: Implied bound not implied across crates
I tried this code:

```rust
use crate_b::{Foo, Super, Unsatisfied};

fn foo<T: Foo>() {
   unsatisfied::<<T::FooAssoc as Super>::SuperAssoc>()
}

fn unsatisfied<B: Unsatisfied>() {}

pub mod crate_b {
    pub trait Foo {
        type FooAssoc: Bar;
    }

    pub trait Bar: Super<SuperAssoc: Bound> {}

    pub trait Super {
        type SuperAssoc;
    }

    pub trait Bound: Unsatisfied {}

    pub trait Unsatisfied {}
}
```

This compiles fine, however _**if crate_b is a separate crate instead of a local module**_, it errors with:

```
error[E0277]: the trait bound `<<T as Foo>::FooAssoc as Super>::SuperAssoc: Unsatisfied` is not satisfied
 --> src/main.rs:4:19
  |
4 |     unsatisfied::<<T::FooAssoc as Super>::SuperAssoc>()
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Unsatisfied` is not implemented for `<<T as Foo>::FooAssoc as Super>::SuperAssoc`
  |
note: required by a bound in `unsatisfied`
 --> src/main.rs:7:19
  |
7 | fn unsatisfied<B: Unsatisfied>() {}
  |                   ^^^^^^^^^^^ required by this bound in `unsatisfied`
help: consider further restricting the associated type
  |
3 | fn foo<T: Foo>() where <<T as Foo>::FooAssoc as Super>::SuperAssoc: Unsatisfied {
  |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

This is not fixed by the next solver (`-Znext-solver`).

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (1388d7a06 2024-03-20)
binary: rustc
commit-hash: 1388d7a069d872bcfe5e5dd97ef61fa0a586fac0
commit-date: 2024-03-20
host: aarch64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### PR DESCRIPTION
**Pull request by compiler-errors**
In #112629, we decided to make associated type bounds in the "supertrait" AST position *implied* even though they're not supertraits themselves.

This means that the `super_predicates` and `implied_predicates` queries now differ for regular traits. The assumption that they didn't differ was hard-coded in #107614, so in cross-crate positions this means that we forget the implied predicates from associated type bounds.

This isn't unsound, just kind of annoying. This should be backported since associated type bounds are slated to stabilize for 1.78 -- either that, or associated type bounds can be reverted on beta and re-shipped in 1.79 with this patch.

Fixes #122859

### CODE REVIEW

**Comment by compiler-errors** [comment]
@bors try @rust-timer queue

if this ends up being a lot of work, I can make it so that we only encode implied predicates if they differ from super predicates.

**Comment by slanterns** [comment]
> associated type bounds are slated to stabilize for 1.78

I think the merge of ATB are happen after the beta-cutoff, and it hasn't get into 1.78 beta yet?

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-04-04/near/431324007). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted

**Comment by cuviper** [comment]
> This should be backported since associated type bounds are slated to stabilize for 1.78

The backported test fails, `error[E0658]: associated type bounds are unstable` -- I think it's only in 1.79 per #122055. Should we cancel this backport? or just add `#![feature(associated_type_bounds)]` to the backported test?

**Comment by cuviper** [comment]
Removing the backport after the [followup](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-04-04/near/431368894) on zulip.

@rustbot label -beta-nominated -beta-accepted

**Pull request merged**
