### PR TITLE
Rustdoc support for universal_impl_trait

### LINKED ISSUE #49309: Rustdoc for `impl Trait` in argument position is broken
```rust
pub fn foo(_x: impl Clone, _y: i32, _z: impl Copy) {
}
```

Running rustdoc on this code generates the following documentation:

### PR DESCRIPTION
**Pull request by sinkuu**
Hides type parameters synthesized by `impl Trait`-in-argument-position, and enables links to trait names.

before
↓
after

Fixes #49309

### CODE REVIEW

**Comment by sinkuu** [comment]
Ah, no, this does not work if `impl Debug` is not the argument type directly, e.g. `fn foo(x: (impl Debug, i32))`.

**Comment by QuietMisdreavus** [comment]
Ah, i was starting to read through it. Looking forward to seeing if you can get it working!

Also, it doesn't really require the other PR. It's okay to expose features in rustdoc that are unstable, because they'll only be there in the first place if the library enabled the feature. Other unstable features have been exposed in rustdoc before they were stable, and it's not like the other commits changed anything that rustdoc depends on.

**Comment by QuietMisdreavus** [comment]
This looks great! Thanks so much!

@bors r+

**Pull request merged**
