### PR TITLE
Remove the source archive functionality of ArchiveWriter

### PR DESCRIPTION
**Pull request by bjorn3**
We now build archives through strictly additive means rather than taking an existing archive and potentially substracting parts. This is simpler and makes it easier to swap out the archive writer in https://github.com/rust-lang/rust/pull/97485.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks, @bjorn3, looks good to me!

@bors r+

**Comment by bjorn3** [comment]
@bors try

to check if it was a fluke.

**Comment by bjorn3** [comment]
Bisecting the regressing commit

@bors try

**Comment by bjorn3** [comment]
Maybe this works? I made `add_static_crate` skip libraries without any members again.

@bors try

**Comment by bjorn3** [comment]
That seems to have fixed it. Doing one final run with all reverts removed and then I can remove the debug commit.

@bors try

**Comment by bjorn3** [comment]
It is indeed fixed. Removed the debug commit. The change is in https://github.com/rust-lang/rust/pull/98098/commits/7ff0df51024a96e91f41c3760b5676ebbdc7a2c0

@rustbot ready

**Comment by michaelwoerister** [comment]
Thanks, @bjorn3! Looks good.

@bors r+

**Comment by bjorn3** [comment]
Looks like macOS CI got stuck. Should I ask bors to retry?

**Comment by bjorn3** [comment]
Looks like I was just too impatient.

**Pull request merged**
