### PR TITLE
Bump backtrace to 0.3.74~ish

### PR DESCRIPTION
**Pull request by workingjubilee**
Commit: https://github.com/rust-lang/backtrace-rs/commit/230570f

This should help with backtraces on Android, QNX NTO 7.0, and Windows.
It addresses a case of backtrace incurring undefined behavior on Android.

r? @ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
Specifically this brings in https://github.com/rust-lang/backtrace-rs/commit/6a2e7a1dea73142da72cfb93704ebbc796020f18

cc @saethlin

**Comment by workingjubilee** [comment]
Meh, doesn't much matter.

**Comment by tgross35** [comment]
I think this caused the error in https://github.com/rust-lang/rust/pull/129643#issuecomment-2311570717, needs some tests blessed. Only a few minutes away from that point so we can let it go to be sure.

**Comment by workingjubilee** [comment]
cc @maurer @mgeisler @chriswailes It feels like either our test suite uses an incorrect emulator or some target-specific code is unsound.

**Comment by saethlin** [comment]
Must `#[track_caller]` harder

**Comment by workingjubilee** [comment]
Thanks @saethlin! That did the trick, I seem to...

> +       panicked at std/src/../../backtrace/src/symbolize/gimli/libs_dl_iterate_phdr.rs:62:19:
> +       unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
> +       thread panicked while processing panic. aborting.

**hmmmmmm**

**Comment by saethlin** [comment]
I'd bet money this is a null pointer and a zero-length slice. Seems easy enough to check for null then not push that library?

**Comment by workingjubilee** [comment]
...oh yeah, that'll break a lot of assumptions in backtrace:
```c
    // Dynamic binaries get their dl_iterate_phdr from the dynamic linker, but
    // static binaries get this. We don't have a list of shared objects to
    // iterate over, since there's really only a single monolithic blob of
    // code/data, plus optionally a VDSO.
    struct dl_phdr_info exe_info;
    exe_info.dlpi_addr = 0;
    exe_info.dlpi_name = NULL;
    exe_info.dlpi_phdr = (Elf32_Phdr*) ((unsigned long) ehdr + ehdr->e_phoff);
    exe_info.dlpi_phnum = ehdr->e_phnum;
```

**Comment by workingjubilee** [comment]
astounding, we don't actually handle the fucking executable correctly.

**Comment by workingjubilee** [comment]
holy shit

**Comment by workingjubilee** [comment]
er... wait, I don't trust that.
@bors r-

**Pull request merged**
