### PR TITLE
Update E0070 to new error format

### LINKED ISSUE #35503: E0070 needs to be updated to new format
From: src/test/compile-fail/E0070.rs

Error E0070 needs a span_label, updating it from:

```
error[E0070]: invalid left-hand side expression
  --> src/test/compile-fail/E0070.rs:18:5
   |
18 |     some_other_func() = 4; //~ ERROR E0070
   |     ^^^^^^^^^^^^^^^^^^^^^
```

To:

```
error[E0070]: invalid left-hand side expression
  --> src/test/compile-fail/E0070.rs:18:5
   |
18 |     some_other_func() = 4; //~ ERROR E0070
   |     ^^^^^^^^^^^^^^^^^^^^^ left-hand of expression not valid
```

### PR DESCRIPTION
**Pull request by clementmiao**
Updated E0070 to new error format.
Part of #35233 
Fixes #35503 

Thanks for letting me help!

r? @jonathandturner

### CODE REVIEW

**Comment by clementmiao** [comment]
closed for now, need to fix the unit tests.

**Comment by clementmiao** [comment]
Fixing tidy error

**Comment by jonathandturner** [comment]
Thanks for the PR!

Can you do [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your 3 commits down to 1 commit?  With that, I think we're good.

**Comment by clementmiao** [comment]
Thanks Jonathan, just squashed them into 1! @jonathandturner

**Comment by jonathandturner** [comment]
Great!  Looks good.

@bors r+ rollup

**Pull request merged**
