### PR TITLE
Stabilise raw_identifiers feature

### LINKED ISSUE #48589: Tracking issue for RFC 2151, Raw Identifiers
This is a tracking issue for RFC 2151 (rust-lang/rfcs#2151).

**Steps:**

- [x] Implement the RFC (#48942)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])
    - [ ] Settle on a final syntax for raw identifiers.

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

- [ ] Do macros need any special care with such identifier tokens?
- [ ] Should diagnostics use the `r#` syntax when printing identifiers that overlap keywords?
- [ ] Does rustdoc need to use the `r#` syntax? e.g. to document `pub use old_epoch::*`

### PR DESCRIPTION
**Pull request by alexreg**
* [Reference PR](https://github.com/rust-lang-nursery/reference/pull/395)
* [Book PR](https://github.com/rust-lang/book/pull/1480)
* [Rust by Example PR](https://github.com/rust-lang/rust-by-example/pull/1095)

Closes #48589.

r? @cramertj
CC @cuviper @centril

### CODE REVIEW

**Comment by cramertj** [comment]
Before merging this we need docs PRs against [the reference](https://github.com/rust-lang-nursery/reference/pulls), [the book](https://github.com/rust-lang/book), and [Rust by Example](https://github.com/rust-lang/rust-by-example).

**Comment by alexreg** [comment]
@cramertj Was planning on doing ones for the Reference and Rust By Example, but how do you think it would fit in the Book?

**Comment by Havvy** [comment]
The current rules state that you just need to open issues, not full fledged PRs. Though of course, we prefer PRs over issues. But if you're not sure what to write in a PR, file an issue.

**Comment by alexreg** [comment]
@Havvy Okay. I'll open a PR with what I think is most sane, and we can go from there, if people aren't happy with it...

**Comment by cramertj** [comment]
@bors r+

Assuming @alexreg will also open an issue against the book :)

**Comment by alexreg** [comment]
@cramertj I already opened a PR against the book. From the Forge guide, I thought that was enough... what should the issue be about?

**Comment by cramertj** [comment]
@alexreg Oh, I see it linked at the top now. Thanks! I just missed it before.

**Comment by kennytm** [comment]
@bors r- 

Merge conflicts in the UI tests.

**Comment by alexreg** [comment]
@kennytm Done!

**Comment by alexreg** [comment]
Ah, rubbish... done now. :-P

**Pull request merged**
