### PR TITLE
resolve: More detailed effective visibility tracking for imports

### PR DESCRIPTION
**Pull request by petrochenkov**
Per-`DefId` tracking is not enough, due to glob imports in particular, which have a single `DefId` for the whole glob import item.
We need to track this stuff per every introduced name (`NameBinding`).

Also drop `extern` blocks from the effective visibility table, they are nominally private and it doesn't make sense to keep them there.

Later commits add some debug-only invariant checking and optimiaztions to mitigate regressions in https://github.com/rust-lang/rust/pull/103965#issuecomment-1304256445.

This is a bugfix and continuation of https://github.com/rust-lang/rust/pull/102026.

### CODE REVIEW

**Comment by petrochenkov** [comment]
cc @Bryanskiy

**Comment by petrochenkov** [comment]
Not sure how to cancel the previous `@bors try`, but this PR needs a new one.
@bors try @rust-timer queue

**Comment by petrochenkov** [comment]
Ping @oli-obk @cjgillot - you recently reviewed https://github.com/rust-lang/rust/pull/102109 / https://github.com/rust-lang/rust/pull/103249 and https://github.com/rust-lang/rust/pull/103760, maybe you could review this PR as well?

**Comment by oli-obk** [comment]
Logic lgtm and makes sense. Last time it did, too, so let's ask crater at least

@craterbot check

r=me with crater not finding anything

**Comment by oli-obk** [comment]
None of the "regressions" seem remotely related and I don't know how this PR could cause

> error: expected expression, found `<eof>`

@bors r+

**Comment by pnkfelix** [comment]
This is an internal refactoring that we need to get more precise tracking of imports in presence of globs. So I am going to treat the regressions as acceptable and mark it as triaged.

@rustbot label: +perf-regression-triaged

**Pull request merged**
