### PR TITLE
compiletest: let config flags overwrite -A unused

### PR DESCRIPTION
**Pull request by RalfJung**
Cc https://github.com/laumann/compiletest-rs/issues/216

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I'm surprised this is necessary as I wouldn't expect host/target flags to be changing lint levels. But it also seems reasonable, so @bors r+

**Comment by RalfJung** [comment]
@Mark-Simulacrum in Miri we are using host/target flags to overwrite the `-A unused` that is always added some some test sorts. (Miri uses the external fork of this code, but I figured I should keep this consistent with https://github.com/laumann/compiletest-rs/pull/217.)

**Pull request merged**
