### PR TITLE
Autogenerate stubs and SUMMARY.md in the unstable book

### LINKED ISSUE #42454: Unstable book is a serious contribution speed bump
Every time I make a PR, I always get hit by the unstable book tidy check. It always takes me at least 3 roundtrips until I get it right. I hate it (the book) very much at this point.

IMO the process is unnecessarily complicated. Especially so, given that the fix usually ends up being just a link to the tracking issue – information already available to the compiler in the attribute.

I propose that the book would not require adding a link like that for every single feature and instead the pages with links to a tracking issue were generated automatically, during the generation of the book.

I do not the benefits provided by the book warrant making the contribution process so much more complicated.

### PR DESCRIPTION
**Pull request by est31**
Removes a speed bump in compiler development by autogenerating stubs for features in the unstable book. See #42454 for discussion.

The PR contains three commits, separated in order to make review easy:

* The first commit converts the tidy tool from a binary crate to a crate that contains both a library and a binary. In the second commit, we'll use the tidy library
* The second and main commit introduces autogeneration of SUMMARY.md and feature stub files
* The third commit turns off the tidy lint that checks for features without a stub, and removes the stub files. A separate commit due to the large number of files touched

Members of the doc team who wish to document some features can either do this (where `$rustsrc` is the root of the rust repo git checkout):

1. cd to `$rustsrc/src/tools/unstable-book-gen` and then do `cargo run $rustsrc/src $rustsrc/src/doc/unstable-book` to put the stubs into the unstable book
2. cd to `$rustsrc` and run `git ls-files --others --exclude-standard` to list the newly added stubs
3. choose a file to edit, then `git add` it and `git commit`
4. afterwards, remove all changes by the tool by doing `git --reset hard` and `git clean -f`

Or they can do this:

1. remove the comment marker in `src/tools/tidy/src/unstable_book.rs` line 122
2. run `./x.py test src/tools/tidy` to list the unstable features which only have stubs
3. revert the change in 1
3. document one of the chosen unstable features

The changes done by this PR also allow for further development:

* tidy obtains information about tracking issues. We can now forbid differing tracking issues between differing `#![unstable]` annotations. I haven't done this but plan to in a future PR
* we now have a general framework for generating stuff for the unstable book at build time. Further changes can autogenerate a list of the API a given library feature exposes.

The old way to simply click through the documentation after it has been uploaded to rust-lang.org works as well.

r? @nagisa 

Fixes #42454

### CODE REVIEW

**Comment by est31** [comment]
About the stubs removal, I think its better to track stubs outside of git, so that changed of the template affect them at once. Also, the methods above only work for stubs tracked outside of git, if you want to add docs for a feature when stubs are inside git you need to open docs one by one and check for stubs. If there is desire to put them into git though, I can put them back!

I have done a new tool instead of adding this to tidy because I think that tidy shouldn't *change* anything, only read. Also, often you forget to run tidy so the speed bump issue would only be resolved partially, while this runs on every docs run.

**Comment by nagisa** [comment]
Okay, so I’m not sure how the unstable book generated/built/deployed, so I cannot r+ without checking what the people in-the-know say.

All the other changes r=me.

**Comment by est31** [comment]
> how is the unstable book generated/built/deployed

I was assuming it was some form of `./x.py doc`. It outputs to  `build/$TARGET/doc/unstable-book/` and continues to work fine (I've tested `./x.py doc --stage 0`).

**Comment by est31** [comment]
> I cannot r+ without checking what the people in-the-know say.

Okay then ... cc @alexcrichton

**Comment by alexcrichton** [comment]
@bors: r=nagisa

build system stuff all looks good to me!

**Comment by est31** [comment]
Rebased. re-r? @nagisa

**Comment by est31** [comment]
Seems like a legit issue.

```
[00:47:18] Generating unstable book md files (x86_64-unknown-linux-gnu)

[00:47:18] thread 'main' panicked at 'source "/checkout/obj/build/x86_64-unknown-fuchsia/md-doc/unstable-book" failed to get metadata: No such file or directory (os error 2)', /checkout/src/build_helper/lib.rs:176

[00:47:18] note: Run with `RUST_BACKTRACE=1` for a backtrace.

[00:47:18] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap dist --target x86_64-unknown-fuchsia,aarch64-unknown-fuchsia
```

I'm investigating...

**Comment by est31** [comment]
Hmm I couldn't reproduce locally, nor could I get fuchsia working... I have pushed a debug commit (don't merge the PR with that) to try it.

@bors try

**Comment by est31** [comment]
Hmm, I've still got to learn how to use bors try...

@bors try

**Comment by est31** [comment]
Okay found a fix. re-r? @nagisa

**Comment by eddyb** [comment]
Travis failed?

**Comment by Mark-Simulacrum** [comment]
@bors r-

https://travis-ci.org/rust-lang/rust/jobs/242922500#L1018

**Comment by est31** [comment]
Hmm, this should hopefully work. r? @nagisa

**Comment by est31** [comment]
Yeey [it works](https://travis-ci.org/rust-lang/rust/jobs/243261064#L8757)!

**Comment by est31** [comment]
re-r? @nagisa

**Comment by Mark-Simulacrum** [comment]
Failure looks legitimate.

```
[00:47:18] Generating unstable book md files (x86_64-unknown-linux-gnu)
[00:47:18] thread 'main' panicked at 'source "/checkout/obj/build/x86_64-unknown-fuchsia/md-doc/unstable-book" failed to get metadata: No such file or directory (os error 2)', /checkout/src/build_helper/lib.rs:176
[00:47:18] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:47:18] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap dist --target x86_64-unknown-fuchsia,aarch64-unknown-fuchsia
[00:47:18] Build completed unsuccessfully in 0:46:12
```

**Comment by est31** [comment]
Okay. Travis passed now. I've squashed the fix commits. re-r? @nagisa

**Pull request merged**
