### PR TITLE
Print constants in `type_name` for const generics

### LINKED ISSUE #65372: type_name doesn't get correct type_name with const generics.
Example code: 
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2dd38f47a052e3545fad6cd1249d6a6a
```rust
dbg!(std::any::type_name::<Test<isize, {3}>>());
=>
[src/main.rs:11] std::any::type_name::<Test<isize, { 3 }>>() = "playground::Test<isize, >"
```

### PR DESCRIPTION
**Pull request by varkor**
Fixes https://github.com/rust-lang/rust/issues/65372.

r? @oli-obk as there may have been a deliberate decision not to in https://github.com/rust-lang/rust/commit/5b9848912a85e28d000602fc2e81bad9c2f2a981#diff-4ed1a72c0bfdf17be769ed520932cd02R80.

### CODE REVIEW

**Comment by oli-obk** [comment]
I'd rather not merge anything around constants and pretty printing until my pretty printing PR is merged.

This PR doesn't actually print anything new, right? It just stops printing the type for const generics

**Comment by varkor** [comment]
> This PR doesn't actually print anything new, right?

It prints const generic arguments, which were previously just ignored.

**Comment by oli-obk** [comment]
#67133 is getting split up anyway, so r=me on this PR after a rebase

**Pull request merged**
