### PR TITLE
docs improvement std::sync::{PoisonError, TryLockError}

### PR DESCRIPTION
**Pull request by lorepozo**
Addresses the `PoisonError` and `TryLockError` parts of #29377.
Adds examples and links.

r? @steveklabnik

### CODE REVIEW

**Comment by frewsxcv** [comment]
this looks great, thanks!

@bors r+ rollup

**Comment by lucasem** [comment]
Whoops, I force-pushed to my branch to work on other changes before this was merged in (so GitHub automatically closed this PR). I assume bors will still include the commit in the next rollup anyway? @frewsxcv

**Comment by arielb1** [comment]
@lucasem

I think you're still in the bors queue.

**Comment by Mark-Simulacrum** [comment]
Merged in https://github.com/rust-lang/rust/pull/44936.

**Pull request closed without merging**
