### PR TITLE
[Experiment] Box the biggest TerminatorKind variants

### PR DESCRIPTION
**Pull request by bugadani**
This brings the size of Terminator from 112 bytes to ~72~ 48, at the cost of a lot more pointer chasing.

### CODE REVIEW

**Comment by bugadani** [comment]
Wait, i can't make clippy-breaking changes?

**Comment by jyn514** [comment]
@bugadani clippy is a subtree, you just need to update clippy at the same time you make the breaking change.

**Comment by jyn514** [comment]
Instructions look like noise. Max-RSS is slightly down but I think that benchmark is also very noisy.

**Comment by bugadani** [comment]
Huh, I actually expected a lot worse runtime. Might still go further with this one still.

**Pull request closed without merging**
