### PR TITLE
Revert perf-regression 101620

### PR DESCRIPTION
**Pull request by cjgillot**
Reverts #101862 #101620

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me, I guess needs a rebase.

**Comment by cjgillot** [comment]
The regression slipped into beta.  I think this PR deserves consideration for backport.

**Comment by iloveabm3** [comment]
Gboard ক্লিপবোর্ডে স্বাগতম, আপনার কপি করা যেকোনও টেক্সট এখানে সেভ করা হবে।

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-10-06/near/302660975)

@rustbot label +beta-accepted

**Comment by cuviper** [comment]
> Reverts #101862 #101620

#101862 did not reach beta, so I've only cherry-picked the commit to revert #101620.

**Pull request merged**
