### PR TITLE
Faster compile times for release builds with llvm fix

### LINKED ISSUE #44655: Faster compile times for release builds with small fix
Was looking at the printout of llvm passes when I noticed that the functions that was inlined everywhere, and due to this was dead code, was optimized more after inlining.

So as a test I added `MPM.add(createGlobalDCEPass());` at the line [PassManagerBuilder.cpp#L480](https://github.com/rust-lang/llvm/blob/d9e7d2696e41983b6b5a0b4fac604b4e548a84d3/lib/Transforms/IPO/PassManagerBuilder.cpp#L480) and this reduces the compile time of release build in racer by an average of 23%.

I do not know if this is a good place to add this extra pass but maybe someone that knows how llvm works can use this information to speedup the compilation of release builds.

was also wondering how this works in MIR I see that there is an inline pass but I can not find any dead code elimination

### PR DESCRIPTION
**Pull request by andjo403**
Run global optimizations after the inliner to avoid spending time on optimizing dead code.

fixes #44655

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ p=1

Raising priority as this seems like some awesome compile-time wins. Thanks so much for discovering this @andjo403! And also thanks so much to @dcci for helping get this patch upstream in LLVM itself.

**Comment by alexcrichton** [comment]
@andjo403 hm I seem to surprisingly see [no difference](https://perf.rust-lang.org/?start=2017-10-04T00%3A00%3A00%2B00%3A00&end=2017-10-07T00%3A00%3A00%2B00%3A00&crates=[%22regex-opt-0.1.80%40010-baseline%22]&stat=instructions%3Au) in optimized benchmarks on perf.rust-lang.org, mind double-checking locally to see if this is fixed?

**Comment by andjo403** [comment]
@alexcrichton I'm as surprised as you. did not think of do a extra test to see that the faster compile time was there when the submodule was updated due to hade made so many test before for the PR to the llvm repo. the strange part is that I see that the extra passes is present in printout from `cargo rustc --release -- Ztime-llvm-passes` but no speed up. will try to reproduce the earlier findings

**Comment by andjo403** [comment]
@alexcrichton @dcci the current llvm patches is do not give as much gain as my original did. Have added a comment in the llvm review why the original placement of the passes was not good.

**Comment by alexcrichton** [comment]
Ok thanks! I'll watch the LLVM bug

**Comment by dotdash** [comment]
@alexcrichton there was no update to the LLVM trigger file, maybe that's why?

**Comment by alexcrichton** [comment]
@dotdash ah unfortunately that wouldn't cause this, our CI now unconditionally builds LLVM from scratch on all builds (using sccache to not be super slow), so that'd account for local checkouts not rebuilding but not CI

**Comment by andjo403** [comment]
sadly this is all my fault. failed to the test the updated patch from llvm before making this PR and according to comment in [llvm review](https://reviews.llvm.org/D38154) my first patch that showed the big improvements 

> breaks the entire pipelining model of the LLVM passes and inliner.

and the way forward is 

>The only thing I know to help at that point would be to build a CGSCC version of GlobalDCE.
 This is something we've wanted for quite some time, but it is a fair amount of work.

**Comment by alexcrichton** [comment]
@andjo403 I sort of forget at this point, your original fix, was there a known problem with it?

**Comment by andjo403** [comment]
@alexcrichton I hade no problems with it, but it sounds bad to brake the entire pipelining model of llvm.
I do not know what that the result of braking that model is.

**Comment by andjo403** [comment]
@alexcrichton from what I have understand/learned from the llvm review I think that most of the time improvement was due to I broke the pipeline. so think that I will close the ticket #44655 as it is not possible to implement

**Comment by alexcrichton** [comment]
@andjo403 alas :(

**Pull request merged**
