### PR TITLE
self-profiling: Support recording query keys

### PR DESCRIPTION
**Pull request by michaelwoerister**
This PR makes self-profiling able to record query keys. The implementation is not as efficient as it could be yet (all query keys except for `DefId`s cause string data to be duplicated) and the rendered strings could be nicer too. But the implementation is functional and introduces the basic framework for emitting per-query-invocation event data.

I tried to add proper documentation on how everything works. Let me know if more documentation is needed.

r? @wesleywiser 

@Mark-Simulacrum, heads up: This updates `measureme` to 0.7.0 which means that `summarize` on perf.rlo needs to be update accordingly once this is merged.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can we add something to rustc (e.g., an unstable `--print` option) that prints out the SHA commit of the summarize that rustc needs?

Essentially I'd like to for now be able to add some code to perf.rlo which will essentially build the summarize from the repo via `git checkout $SHA && cargo build --release` or so, and I think it makes sense for rustc to be the source of truth rather than trying to maintain a map of rustc commits to summarize versions inside perf.

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum I would prefer making the measureme tools available as a rustup component. That would be a more general solution (and something we want to do anyway). What do you think?

**Comment by Mark-Simulacrum** [comment]
That would definitely be better! I don't personally have much time to spend figuring out how to hook that up; I can help review such a patch though.

**Comment by michaelwoerister** [comment]
The one downside of any approach that relies on `rustc` or `rustup` is that we can't support older versions of `rustc`. I.e back-collection would not work or would need still another mechanism.

**Comment by Mark-Simulacrum** [comment]
Back collection passively works by just having an older summarize in PATH whereas the new one would be "optionally" in PATH, so that should mostly just naturally fall out :)

**Comment by wesleywiser** [comment]
Since this touches some of the query infrastructure, let's do a perf run just to make sure we don't accidentally regress performance.

@bors try
@rust-timer queue

**Comment by michaelwoerister** [comment]
Yes, good idea! The self-profiling code exercised by `perf.rlo` is expected to be a bit slower than with `measureme 0.5` (because we are emitting more string-index data) but should still be faster than `measureme 0.4` (which still used pairs of start/end events instead of single interval events).

**Comment by Mark-Simulacrum** [comment]
Hm, I suspect that perf will fail to run due to the summarize incompatibility, but we can try I guess! Certainly the try build will help a future run if I find some time to do it manually.

**Comment by michaelwoerister** [comment]
We should still get correct instruction counts and wall-times, right? Just no self-profiling data.

**Comment by Mark-Simulacrum** [comment]
I think perf today just dies if self profile fails to work (which is probably not ideal, but perf leans on fail fast today a bit too hard probably).

**Comment by wesleywiser** [comment]
Looks like @Mark-Simulacrum was right.

**Comment by michaelwoerister** [comment]
> I think perf today just dies if self profile fails to work (which is probably not ideal, but perf leans on fail fast today a bit too hard probably).

Yeah, making that more resilient would be a nice to have.

**Comment by michaelwoerister** [comment]
I don't think I'll have time to implement the Rustup component approach at the moment (I'll be afk for the rest of the year). What's the quickest way to unblock this? Doing one last manual update of `summarize` on perf.rlo?

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Looking at the trace file generated while compiling `cargo`, I see that recording query keys takes 200ms. Since this is opt in, I think there's little risk of regressing performance, but just to be safe, let's not roll this up.

@bors r+ rollup=never

**Comment by michaelwoerister** [comment]
Thanks for review, @wesleywiser! 

@Mark-Simulacrum Heads up, this is not approved. Feel free to r- if you don't have time to update `perf.rlo` or want to wait for a proper rustup component.

**Comment by Mark-Simulacrum** [comment]
I should be able to manage it, let me @bors r- for now though -- I would like to try to allocate some time today to get the perf.rlo support for this in a slightly better place, and if that doesn't happen then we'll fall back on dealing with the fallout once it lands.

**Comment by Mark-Simulacrum** [comment]
I ran out of time today but this is my first priority for tomorrow and so I'm going to delay hopefully less than 12 hours here, at which point I'll definitely just merge.

**Comment by Mark-Simulacrum** [comment]
I think I should have a solution in place in the next hour or so, so let's at least get the ball somewhat rolling on this...

@bors r+

**Comment by Mark-Simulacrum** [comment]
Okay, I believe I should have a fix in place if all goes well -- specifically, we're falling back on the `summarize-0.7` binary if the `summarize` binary fails to run. In theory, this should be both forwards and backwards compatible, so we'll be able to indefinitely utilize said strategy (with no more than one fallback, in most cases, though of course there's very little cost to such a fallback, so we can likely add more easily).

With that in mind, from now on, basically I just need a heads up and a git tag in the measureme repo to update to but we can be much more flexible from the perf side I expect.

**Comment by michaelwoerister** [comment]
> With that in mind, from now on, basically I just need a heads up and a git tag in the measureme repo to update to but we can be much more flexible from the perf side I expect.

Awesome.

> The job dist-powerpc64-linux of your PR failed (pretty log, raw log).

Le sigh. Big endian strikes again. We should somehow test a big endian platform directly in measureme's CI.

**Comment by michaelwoerister** [comment]
This is rebased now. I did not add support for function parameters (as might be used by e.g. `extra_verbose_generic_activities`) as part of the rebase. I'll do that in another PR.

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum: seems like this broke perf.rlo after all. Maybe something is wrong with the fallback logic for summarize?

**Comment by Mark-Simulacrum** [comment]
Hm, we were on 0.7.0 and not 0.7.1 -- I've now changed that. Is that a possible cause? I suppose probably no. It also turns out I think I may have forgotten to actually deploy the change, which I've now done :)

**Comment by michaelwoerister** [comment]
> Hm, we were on 0.7.0 and not 0.7.1 -- I've now changed that. Is that a possible cause? 

No, 0.7.1 just fixes a compilation error on big endian platforms.

> It also turns out I think I may have forgotten to actually deploy the change, which I've now done :)

Yes, that would explain it `:)`

**Pull request merged**
