### PR TITLE
Update the cargo submodule again

### PR DESCRIPTION
**Pull request by alexcrichton**
Unfortunately it was reverted back to a broken state in
e06c51553ddc202a79f2c0b76822ad56c4a30f80 by accident, so let's bring it forward
again!

Closes https://github.com/rust-lang/cargo/issues/3844

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @frewsxcv 

no worries, just a reminder to be careful on those submodule updates!

Also infra's weekly reminder that a rust-highfive reminder of a submodule update would be useful...

@bors: r+ p=1000

(this is a nightly regression)

**Comment by frewsxcv** [comment]
Ugghh sorry about this :(

**Comment by frewsxcv** [comment]
Is it possible we could add a `cargo version` sanity check before publishing a new version?

**Comment by arielb1** [comment]
@bors retry
 - #39074

**Comment by arielb1** [comment]
```
  = note: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/arm-linux-androideabi/lib/libstd-f4594d3e53dcb114.so: error: undefined reference to 'sigemptyset'
```

**Comment by frewsxcv** [comment]
@bors retry

prioritizing rollup which has this

**Pull request merged**
