### PR TITLE
Port shell script to POSIX sh

### PR DESCRIPTION
**Pull request by dereckson**
The ui/update-all-references.sh is pretty standard, excepted for
the arguments parsing part, which is ported to POSIX condition
style. It so works with sh, which is more convenient, as it
decreases the need to install bash on UNIX-like non-linux OS.

### CODE REVIEW

**Comment by shepmaster** [comment]
@alexcrichton can you weigh in on how scary such a change might be? My personal opinion is to actively use bash and bash features.

See also #45957

**Comment by shepmaster** [comment]
From #45957:

> The goal is to ease the testing suite on OpenBSD and other OS where bash isn't shipped by default.
>
> If we switch progressively everything to pure POSIX, we can use the scripts everywhere on the out-of-the-box OS, without having to install bash.

To me, needing to install bash seems about the same as needing to install Python (and whatever else is needed), but making such large decisions is above my paygrade.

**Comment by alexcrichton** [comment]
Hm yeah I agree with @shepmaster that there's no need to limit ourselves in all cases, for example this script is never used by the build system, just developers. @dereckson was this done for a particular reason or just a blanket "lint all files in the repo"?

**Comment by dereckson** [comment]
@alexcrichton It occurred after a note from @semarie - who maintain Rust port on OpenBSD - there is an appreciable maintenance time cost to install bash on OpenBSD server, or have to patch files locally when /bin/bash is hardcoded.

So my first wish was to fix shebangs to call bash properly. But then, I've noticed some scripts were virtually already ready to be written in pure sh.

Basically, less bash scripts there are, easiest is the life for the BSD distributions testing and packaging work.

**Comment by semarie** [comment]
@dereckson thanks for taking care of that, but I don't use this particular script (the one I mentioned on IRC come from [rust-lang/rust-installer](https://github.com/rust-lang/rust-installer/) and I could easily workaround by calling `/bin/bash scriptname` directly).

@alexcrichton in a more general way, gracefully using not POSIX shell extensions could become problematic. I agree with @dereckson that at least having path agnotic shebang would be better: it removes the need to patch the script to correct the shebang.

**Comment by alexcrichton** [comment]
Yes updating the shebang is fine, what I'd prefer to not do is avoid using bash everywhere.

**Comment by shepmaster** [comment]
My reading of the last comment indicates that we should close this PR — I don't see an interest in removing the need for bash.

**Comment by shepmaster** [comment]
Based on my understanding of the comments, I'm going to go ahead and close this PR for now. #45957 can cover updating all the shell scripts to use `env`. Thanks for your hard work!

**Pull request closed without merging**
