### PR TITLE
rustdoc: do not show self-by-value methods from Deref target if not Copy

### PR DESCRIPTION
**Pull request by birkenfeld**
Fixes: #30607

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems sort of "extra special" to me in the sense that it's a bit of an odd condition to have in rustdoc. I'd personally be inclined to close the original issue as "not a bug", but curious what others think?

**Comment by steveklabnik** [comment]
I am torn. Showing that the method is there is what's accurate; if it can't be called for other reasons, well, it can't be called. Dunno.

**Comment by cmr** [comment]
I somewhat agree, @alexcrichton. I think that if we were to have this sort of feature, we'd want to have some infrastructure in the compiler for determining which methods are reachable for a certain type, which would exclude such impossibilities, and render only those. The logic doesn't belong in rustdoc, but it's a "nice to have".

**Comment by alexcrichton** [comment]
@steveklabnik in some sense the information is still accurate, it's just saying that the methods on the deref'd type `T` have some by-value methods, but you need to implicitly know that `Deref` only gives a reference, not something by value. It is magical, and perhaps the header for "methods inherited" could indicate this.

Additionally, this wouldn't work for types like `impl<T: Copy> Copy for Foo<T>`. That sort of conditional logic won't be handled here and would still need to be understood.

**Comment by birkenfeld** [comment]
> Additionally, this wouldn't work for types like impl<T: Copy> Copy for Foo<T>. That sort of conditional logic won't be handled here and would still need to be understood.

That's a good point. I think I agree that this change is trying too hard. I'm fine with closing.

**Comment by alexcrichton** [comment]
Ok, I'm gonna close this for now, but thanks for the PR @birkenfeld!

**Pull request closed without merging**
