### PR TITLE
feat(std): Stabilize 'os_str_bytes' feature

### LINKED ISSUE #111544: Tracking Issue for os_str_bytes
Feature gate: `#![feature(os_str_bytes)]`

This is a tracking issue for cross-platform access to the underling bytes (`&[u8]`) for `&OsStr` by defining it as an unspecified superset of UTF-8.

Assumptions:
- Owned variants of this API are not a blocker for stablization
- Panicking and erroring variants of `from_os_str_bytes_unchecked` are not a blocker for stablization

### Public API

```rust
impl OsStr {
    pub unsafe fn from_os_str_bytes_unchecked(bytes: &[u8]) -> &Self;
    pub fn as_os_str_bytes(&self) -> &[u8];
}

impl OsString {
    pub unsafe fn from_os_str_bytes_unchecked(bytes: Vec<u8>) -> Self;
    pub fn into_os_str_bytes(self) -> Vec<u8>;
}
```

### Steps / History

- [x] Implementation: #109698, #113442
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- What should we refer to this as?
  - Currently `os_str_bytes`
  - `encoded_bytes` was another name that was brought up

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

### PR DESCRIPTION
**Pull request by epage**
Closes #111544

### CODE REVIEW

**Comment by cuviper** [comment]
The FCP approval asked for a name change: https://github.com/rust-lang/rust/issues/111544#issuecomment-1672144696

**Comment by epage** [comment]
Thanks, somehow I missed that

**Pull request merged**
