### PR TITLE
Panic when using mem::uninitialized or mem::zeroed on an uninhabited type

### PR DESCRIPTION
**Pull request by RalfJung**
All code by @japaric. This re-submits one half of https://github.com/rust-lang/rust/pull/53508. This is likely not the one that introduced the perf regression, but just to be sure I'll do a perf run anyway.

### CODE REVIEW

**Comment by RalfJung** [comment]
Dang, it's that gdb test again. :/ @japaric any idea?

**Comment by RalfJung** [comment]
Oh I see. I put all commits related to that test into the other PR because I though it was only about the changed data structures. But it is also about this panic.

**Comment by kennytm** [comment]
@bors p=52

rollup fairness

**Pull request merged**
