### PR TITLE
Remove the `wasm32-wasi` target from rustc

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is the final step in the journey of renaming the historical `wasm32-wasi` target in the Rust compiler to `wasm32-wasip1`. Various steps in this journey so far have been:

* 2023-04-03: rust-lang/compiler-team#607 - initial proposal for this rename
* 2024-11-27: rust-lang/compiler-team#695 - amended schedule/procedure for rename
* 2024-01-29: rust-lang/rust#120468 - initial introduction of `wasm32-wasip1`
* 2024-06-18: rust-lang/rust#126662 - warn on usage of `wasm32-wasi`
* 2024-11-08: this PR - remove the `wasm32-wasi` target

The full transition schedule is in [this comment][comment] and is summarized with:

* 2024-05-02: Rust 1.78 released with `wasm32-wasip1` target
* 2024-09-05: Rust 1.81 released warning on usage of `wasm32-wasi`
* 2025-01-09: Rust 1.84 to be released without the `wasm32-wasi` target

This means that support on stable for the replacement target of `wasm32-wasip1` has currently been available for 6 months. Users have already seen warnings on stable for 2 months about usage of `wasm32-wasi` and stable users have another 2 months of warnings before the target is removed from stable.

This commit is intended to be the final step in this transition so the source tree should no longer mention `wasm32-wasi` except in historical reference to the older name of the `wasm32-wasip1` target.

[comment]: https://github.com/rust-lang/rust/pull/120468#issuecomment-1977878747

### CODE REVIEW

**Comment by jieyouxu** [comment]
r? jieyouxu

**Comment by Noratrieb** [comment]
This also changes the LLVM/LLD target of wasm32-wasip1 to wasm32-wasip1. Is that intended to be done in this PR?

**Review by jieyouxu — APPROVED** [review]
This looks mostly fine to me, r=me if the answer to Nora's question of changing the llvm target string is "this is intentional".

**Comment by sffc** [comment]
Just a note here: our builds pin nightlies based on LLVM updates, since this impacts compatibility with Xcode and other tools in our pipeline that run LTO on our C++/Rust mixed binaries. We are currently limited to nightlies that support LLVM 17, which is the version in the current Xcode release.

It appears that LLVM 18 landed on Feb 13, 2024: https://github.com/rust-lang/rust/commit/eaff1af8fdd18ee3eb05167b2836042b7d4315f6

Meanwhile, `wasm32-wasip1` landed on Mar 4, 2024: https://github.com/rust-lang/rust/commit/d18480b84fdbf1efc34f62070951334aa833d761

This means that there is no nightly version that currently supports both LLVM 17 and `wasm32-wasip1`. This is a pain point since it means we can't both support both the latest Rust Nightly and also support the latest Xcode.

**Comment by alexcrichton** [comment]
@sffc is it possible to configure your CI to work around this? For example using a different compiler for wasm than for native?

**Comment by sffc** [comment]
Yes it can be worked-around with CI configs, but that's exactly why it is a pain point.

It would have been easier if the transition period between `wasm32-wasi` and `wasm32-wasip1` had been longer.

**Pull request merged**
