### PR TITLE
msvc: Enable unwinding, improve finding link.exe

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR was originally going to be a "let's start running tests on MSVC" PR, but it didn't quite get to that point. It instead gets us ~80% of the way there! The steps taken in this PR are:
- Landing pads are turned on by default for 64-bit MSVC. The LLVM support is "good enough" with the caveat the destructor glue is now marked noinline. This was recommended [on the associated bug](https://llvm.org/bugs/show_bug.cgi?id=23884) as a stopgap until LLVM has a better representation for exception handling in MSVC. The consequence of this is that MSVC will have a bit of a perf hit, but there are possible routes we can take if this workaround sticks around for too long.
- The linker (`link.exe`) is now looked up in the Windows Registry if it's not otherwise available in the environment. This improves using the compiler outside of a VS shell (e.g. in a MSYS shell or in a vanilla cmd.exe shell). This also makes cross compiles via Cargo "just work" when crossing between 32 and 64 bit!
- TLS destructors were fixed to start running on MSVC (they previously weren't running at all)
- A few assorted `run-pass` tests were fixed.
- The dependency on the `rust_builtin` library was removed entirely for MSVC to try to prevent any `cl.exe` compiled objects get into the standard library. This should help us later remove any dependence on the CRT by the standard library.
- I re-added `rust_try_msvc_32.ll` for 32-bit MSVC and ensured that landing pads were turned off by default there as well.

Despite landing pads being enabled, there are still _many_ failing tests on MSVC. The two major classes I've identified so far are:
- Spurious aborts. It appears that when optimizations are enabled that landing pads aren't always lined up properly, and sometimes an exception being thrown can't find the catch block down the stack, causing the program to abort. I've been working to reduce this test case but haven't been met with great success just yet.
- Parallel codegen does not work on MSVC. Our current strategy is to take the N object files emitted by the N codegen threads and use `ld -r` to assemble them into _one_ object file. The MSVC linker, however, does not have this ability, and this will need to be rearchitected to work on MSVC.

I will fix parallel codegen in a future PR, and I'll also be watching LLVM closely to see if the aborts... disappear!

### CODE REVIEW

**Comment by alexcrichton** [comment]
r? @brson 

cc @retep998 -- lots of windows registry stuff
cc @epdtry -- do you remember if there's a fundamental reason we use `ld -r`? I'm under the impression it's just convenience
cc @vadimcn -- also about registry stuff, hopefully lots of the stuff in the configure script can be removed eventually now!

**Comment by jroesch** [comment]
@alexcrichton: +1

**Comment by vadimcn** [comment]
Trawling the registry to find linker and SDK libraries is... unorthodox and is likely to break with future versions, but I guess you already know that.  Otherwise, lgtm.   Sadly, I cannot propose a better way of detecting VC's install location.

**Comment by vadimcn** [comment]
Regarding unwinding: if the goal is to get rid of libgcc dependency, we could implement Itanium-style LSDA parser in rust_eh_personality and thus avoid all the trouble associated with MSVC-style landing pads.

**Comment by alexcrichton** [comment]
Yeah I was a little uneasy probing the registry, but [it's what clang does](https://github.com/llvm-mirror/clang/blob/eb4602db1a5063263d3fae4b271ab0243446cc38/lib/Driver/MSVCToolChain.cpp#L367) so I didn't feel too too bad about it.

I also actually started a branch a long time ago to just write the necessary portions of libgcc in Rust, but it ended up getting super hairy super quickly. I want to believe that LLVM support will become more robust/rock solid over the next few months, but if it ends up languishing too much then we can definitely look again into doing the libgcc-like stuff.

**Comment by vadimcn** [comment]
>  it ended up getting super hairy super quickly

Which bits of it got hairy?  CPU context management?  Did you try to do it just for Windows or for all platforms?

**Comment by alexcrichton** [comment]
Oh no I was only trying for 64-bit MSVC Windows. I found that the rabbit hole kept getting deeper and deeper and look liked it was going to be quite a chunk of code, so I bailed out. This is when I was initially adding MSVC support though so I wasn't expecting it to be a large dive. In isolation it may not be so bad today?

**Comment by retep998** [comment]
I checked over the registry ffi definitions and they seem correct.

**Pull request merged**
