### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
~~I'm not sure, if we can/should land this before beta is branched.~~ (Nvm, beta is already branched) The last Clippy update was 3 weeks ago: #73660

This includes, besides other minor things:

- New lints
- One lint deprecation
- One lint was moved to pedantic
- Some FP fixes
- I think an ICE fix?

cc @Mark-Simulacrum 

r? @Manishearth 

---

We probably should also think of some process when and how often we should sync Clippy to the rust repo, so that we don't end up with those huge updates. Maybe every 2 weeks? Or even every week? cc @rust-lang/clippy

### CODE REVIEW

**Comment by Manishearth** [comment]
Every two weeks seems fine. We could also have clippy CI warn when it breaks and we do a two way sync whenever that happens

@bors r+ p=1

**Comment by flip1995** [comment]
> Every two weeks seems fine. 

Alright, I already blocked off 2 hours in my calendar to do Clippy PR triage every other week. I'll also sync on these days then :)

**Comment by Manishearth** [comment]
Sweet. I'll also set up a sync thing and maybe occasionally sync

**Pull request merged**
