### PR TITLE
[perftest] Update bootstrap LLVM

### PR DESCRIPTION
**Pull request by Kobzol**
This PR updates the LLVM used to build `dist` artifacts on CI to version 14. The goal is to see how does this change affect perf (if at all) to isolate the effect of using [BOLT](https://github.com/rust-lang/rust/pull/94381).

Could someone schedule a perf. run please? Thanks.

### CODE REVIEW

**Comment by mati865** [comment]
Looks like half of max-rss improvement comes from upgrading bootstrap LLVM, other metrics are basically a noise.

**Comment by Mark-Simulacrum** [comment]
From this PR, but this PR also includes a gcc version bump, and I *think* we might be using the gcc standard library for something, so it might be due to that. (IOW, I am not sure it is down to LLVM 13 vs. 14 difference).

**Comment by Kobzol** [comment]
Well the newer GCC is needed anyway to build LLVM 14. Could there be some issues with upgrading GCC?

It looks like BOLT has a nontrivial effect on its own, but it's good to know that LLVM/GCC upgrade also helps.

**Comment by Kobzol** [comment]
This PR is not supposed to be merged, so I'll use it for more LLVM CI experiments. Let's see if gathering more profiling data for PGO for LLVM helps.

**Comment by Kobzol** [comment]
Closing in favour of https://github.com/rust-lang/rust/pull/95171.

**Pull request closed without merging**
