### PR TITLE
add Cargo metadata to libstd

### PR DESCRIPTION
**Pull request by cardoe**
Add license and repository metadata to libstd

### CODE REVIEW

**Comment by cardoe** [comment]
I'm working on some additions for https://github.com/cargo/cargo-bitbake to generate the necessary license data for compliance validation for Yocto based distros. I made the assumption that all dependencies in crates.io must comply with the packaging requirements which works until I attempted to include libstd's data (which I know is not on crates.io). I am hoping we can include this so I don't have to special case libstd. As well as some day libstd being available in crates.io

**Comment by cardoe** [comment]
Feel free to squash or change or ignore any of these commits.

**Comment by kennytm** [comment]
@bors r+ rollup

@cardoe Thanks!

Do you need to update other crates like `libtest` as well, or augmenting `libstd` is enough?

**Comment by cardoe** [comment]
I'd like to do all of them @kennytm but I figured I'd start here to see if the maintainers were receptive.

**Pull request merged**
