### PR TITLE
Remove `actually_rustdoc` entirely

### PR DESCRIPTION
**Pull request by oli-obk**
r? @jyn514

After this change, only code that passes rustc with `--cfg=doc` passed is guaranteed to pass rustdoc.

We can probably get more stuff to work by 

1. avoiding the `typeck` query entirely, it is not needed for rustdoc, just for a combination of generating docs for all targets at the same time and allowing the source view of rustdoc to have goto definition.
2. avoiding name resolution inside function bodies. Once name resolution is more querified, that may actually become feasible by overriding the queries for bodies, I don't know yet.

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors try

should crater this, but it will probably break things that do cursed `#[cfg(doc)]` stuff

**Comment by jyn514** [comment]
oh right, I forgot to tell you that `std` uses this hack too. you can either special-case `actually_rustdoc && crate_name == "std"` or we can just remove all the `cfg(doc)` cfgs temporarily.

**Comment by oli-obk** [comment]
Is there any path forward for removing them from std?

**Comment by jyn514** [comment]
not that I'm aware of :/ we could do something like libc where there's a different page for each target but that regresses the UX

**Pull request closed without merging**
