### PR TITLE
Stabilize --crate-version option in rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I don't see any reason to not stabilize it anymore, so let's go!

cc @kinnison @ehuss 

r? @ollie27

### CODE REVIEW

**Comment by ehuss** [comment]
cc @aleksator 

Some context for this is https://github.com/rust-lang/cargo/issues/7907 where Cargo now has an unstable option to automatically set this flag for everyone.  However, one of the concerns I had is that the `std` docs include the hash and date in the string, whereas Cargo doesn't.  If we stabilize the Cargo side, it would result in an error when building the `std` docs due to a duplicate command-line option. So the fundamental question for rolling this out to a larger audience is: would it be OK to remove the hash/date from the string in `std`?  If not, we'll need some way to opt-in to having Cargo issue the flag.

**Comment by aleksator** [comment]
I believe what @ehuss says is true.

If we start passing '--crate-version' from cargo by default (which I think is desirable after this PR), we'll get two instances of the flag passed:
1) Aforementioned default passage without git hash and date (not yet implemented).
2) [From the following code in rustdoc.rs](https://github.com/rust-lang/rust/blob/5f979e9afab42dd7536ca93994de66169880361e/src/bootstrap/bin/rustdoc.rs#L52-L61)

To me the most consistent approach seems to drop custom code for bootstrapping, but we do lose an additional information (hash & date) in that case.

What do others think?

**Comment by ollie27** [comment]
Currently as far as cargo is concerned `std` is version `0.0.0`: https://github.com/rust-lang/rust/blob/3dbade652ed8ebac70f903e01f51cd92c4e4302c/src/libstd/Cargo.toml#L4 so we'll definitely need to do something to make sure the `std` docs continue to display the correct version.


> Another option would be to allow the flag to be specified multiple times, and only honor the last one.

This should work as long as cargo can guarantee that `RUSTDOCFLAGS` always comes after the automatically added `--crate-version`. That would allow any crate including `std` to override `--crate-version`. Alternatively cargo could not pass the default `--crate-version` if `RUSTDOCFLAGS` contains `--crate-version`.

**Comment by ehuss** [comment]
Oh, I didn't even think about the version being 0.0.0. 

I'm leaning towards changing Cargo to skip the `--crate-version` flag if it is supplied in RUSTDOCFLAGS.  We generally try to avoid parsing rustc/rustdoc flags in Cargo, but I think in this case it should be fine.

Unfortunately bootstrap doesn't use RUSTDOCFLAGS, but instead a wrapper.  To make that work, bootstrap will need to be changed to use something like [this](https://github.com/rust-lang/rust/blob/15812785344d913d779d9738fe3cca8de56f71d5/src/bootstrap/builder.rs#L1311) for rustdoc.  I think if we do that we can git rid of all the environment variables in the rustdoc wrapper.

How does that sound?

**Comment by GuillaumeGomez** [comment]
I'm fine with it.

**Comment by ehuss** [comment]
Sounds good to me.  @aleksator are you OK with changing Cargo to check for that flag? I think in the [`rustdoc` function](https://github.com/rust-lang/cargo/blob/dcddf15203b91b1769060e38921974cddce4c408/src/cargo/core/compiler/mod.rs#L559) it will need to check if any of the extra arguments starts with `--crate-version`, and skip the version if it is already set. I think it should probably check both [`rustdocflags_args`](https://github.com/rust-lang/cargo/blob/dcddf15203b91b1769060e38921974cddce4c408/src/cargo/core/compiler/mod.rs#L593) (which comes from RUSTDOCFLAGS) and [`extra_args_for`](https://github.com/rust-lang/cargo/blob/dcddf15203b91b1769060e38921974cddce4c408/src/cargo/core/compiler/mod.rs#L587) (which comes from `cargo rustdoc -- …`).  

@GuillaumeGomez it looks like this PR needs to add `-Zunstable-options` somewhere for the remaining unstable opts.

**Comment by aleksator** [comment]
@ehuss Thanks for the tips, I'll do the changes in the cargo.

I did not, however, understood this part:
> Unfortunately bootstrap doesn't use RUSTDOCFLAGS, but instead a wrapper. To make that work, bootstrap will need to be changed to use something like this for rustdoc. I think if we do that we can git rid of all the environment variables in the rustdoc wrapper.

The word "bootstrap" makes me think it's related to the compiler, since to compile one it needs to bootstrap itself. Does it mean some changes would needed to be done to rustc?
Also, where is the wrapper you are talking about here is located?

If someone could help me get a better understanding/point me out to the related documentation about this, I may be able to work on these changes as well. :)

**Comment by ehuss** [comment]
Ah, sorry for the jargon.  ["bootstrap"](https://github.com/rust-lang/rust/tree/master/src/bootstrap) is the build system used in the rust repository (sometimes also called "rustbuild" or "x.py" for the script that launches it).  It's responsible for orchestrating building and testing the compiler and all its tools.

The rustdoc wrapper is [here](https://github.com/rust-lang/rust/blob/master/src/bootstrap/bin/rustdoc.rs).  It wraps rustdoc in order to do some dynamic decisions about which flags to use. It's generally a hack, and we'd like to eventually get away from it as much as possible.

Most of the documentation about rustbuild is in the [rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html), but it's a little light.

Don't worry about updating it.  I'll try to take care of that.  It has to be done when we transition to beta (every 6 weeks), where we switch the version of Cargo used to bootstrap.  All backwards incompatible changes (usually due to stabilizations) have to be done at once.

**Comment by aleksator** [comment]
> I think it should probably check both rustdocflags_args (which comes from RUSTDOCFLAGS) and extra_args_for (which comes from cargo rustdoc -- …)

@ehuss Which one should take precedence if both are supplied?

**Comment by ehuss** [comment]
> @ehuss Which one should take precedence if both are supplied?

I don't think we need to worry about that.  Cargo just needs to check if the flag is specified in either, and if it is, don't add the `--crate-version` flag itself.  If the user specifies both, they'll just get an error.

**Comment by aleksator** [comment]
Done here: https://github.com/rust-lang/cargo/pull/8014

**Review by aleksator — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I think everything is now working as expected thanks to @aleksator. Anything else to be done in here?

**Comment by aleksator** [comment]
I think just a final review and r+ :slightly_smiling_face:

**Review by ehuss — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Then let's go!

@bors: r=ehuss,aleksator,ollie27

**Pull request merged**
