### PR TITLE
Speed up Vec::clear().

### PR DESCRIPTION
**Pull request by nnethercote**
Currently it just calls `truncate(0)`. `truncate()` is (a) not marked as
`#[inline]`, and (b) more general than needed for `clear()`.

This commit changes `clear()` to do the work itself. This modest change
was first proposed in rust-lang#74172, where the reviewer rejected it because
there was insufficient evidence that `Vec::clear()`'s performance
mattered enough to justify the change. Recent changes within rustc have
made `Vec::clear()` hot within `macro_parser.rs`, so the change is now
clearly worthwhile.

Although it doesn't show wins on CI perf runs, this seems to be because they
use PGO. But not all platforms currently use PGO. Also, local builds don't use
PGO, and `truncate` sometimes shows up in an over-represented fashion in local
profiles. So local profiling will be made easier by this change.

Note that this will also benefit `String::clear()`, because it just
calls `Vec::clear()`.

Finally, the commit removes the `vec-clear.rs` codegen test. It was
added in #52908. From before then until now, `Vec::clear()` just called
`Vec::truncate()` with a zero length. The body of Vec::truncate() has
changed a lot since then. Now that `Vec::clear()` is doing actual work
itself, and not just calling `Vec::truncate()`, it's not surprising that
its generated code includes a load and an icmp. I think it's reasonable
to remove this test.

r? @m-ou-se

### CODE REVIEW

**Comment by nnethercote** [comment]
I first tried this in #95664, then close the PR because PGO rendered it ineffective. I have now changed my mind again because not all builds benefit from PGO.

**Comment by m-ou-se** [comment]
Thanks!

@bors r+

**Comment by klensy** [comment]
Maybe rollup=never, if it optimization in some way?

**Comment by AnthonyMikh** [comment]
Hm, does it mean that if this change get merged, we can try to merge #78884 once again and see if it hurts performance this time?

**Comment by nnethercote** [comment]
> Maybe rollup=never, if it optimization in some way?

We've seen for CI perf runs in #95664 that this doesn't have any effect. But I guess it doesn't hurt to be cautious.


> Hm, does it mean that if this change get merged, we can try to merge #78884 once again and see if it hurts performance this time?

My understanding of that PR is that changing the comparison within `truncate` surprisingly caused [worse code to be generated](https://github.com/rust-lang/rust/pull/78884#issuecomment-735308848). This PR changes `clear`, so it wouldn't affect `truncate`. So I don't think this will improve things for #78884.

**Comment by AnthonyMikh** [comment]
> So I don't think this will improve things for #78884.

Codegen was worse precisely for cases `vec.truncate(0)`, which is what `Vec::clear` calls now. Given that it is unlikely that somebody writes their code explicitly like so instead of calling `.clear()` I suspect that with your change this worse codegen case will no more be a concern since it would occur much less often.

**Pull request merged**
