### PR TITLE
[WIP] Treat crates specially when expanding

### LINKED ISSUE #41430: Attribute macros invoked with inner-attribute form fail to resolve
**Note**: As of 4/20/17 this ICEs (#41211) but when a fix lands for that it'll be a resolution error. I am opening the issue first to have a reference for the FIXME in the compile-fail test.

When invoking some attribute procedural macro with inner form, i.e. `#![foo_attr]`, which necessarily occurs before the attribute's import for that scope, a resolution error occurs:

```rust
#![feature(proc_macro)]
#![foo_attr]

extern crate foo_macros;
use foo_attr_macro::foo_attr;
```

This should, ideally, resolve and execute properly. When used in outer form, this works fine, e.g.:

```rust
#![feature(proc_macro)]

extern crate foo_macros;
use foo_attr_macro::foo_attr;

#[foo_attr]
mod bar {}
```

### PR DESCRIPTION
**Pull request by abonander**
Give the base compilation unit of Rust source code the special treatment it deserves during macro expansion.

Pretty-prints crates as they should appear, doesn't pretend they're just modules without names (which breaks `syn`). 

I think this should also require proc-macro-attributes on the crate to be invoked with absolute paths which should alleviate resolution issues without doing anything too crazy.

TODO:
- [ ] implement tests
- [ ] require absolute paths in non-built-in attributes

I branched this from #50092, will rebase when that one is merged so only relevant commits appear (if that isn't fixed automatically)
closes #41430

r? @petrochenkov 
cc @Rantanen @jseyfried

### CODE REVIEW

**Comment by abonander** [comment]
cc @alexcrichton for the absolute paths thing (see OP)

**Comment by alexcrichton** [comment]
I'd personally probably recommend against this, I'd find it hard to imagine at least us ever stabilizing such functionality :(

**Comment by abonander** [comment]
There's a lot of interest in being able to transform/walk an entire crate, so if we're not going to allow proc-macros to do it we should start thinking about something else.

**Comment by abonander** [comment]
@alexcrichton if you prefer I can pivot this to forbid or feature-gate proc-macro attribute invocations on the crate.

**Comment by abonander** [comment]
> Proc-macro attributes on the crate is, from my perspective, the only use that would even need this change. If proc-macro attributes on the crate are not supported, then what other need is there for the crate token expansion working?

I meant that instead of fixing crate expansion I would either rewrite this PR to or open a new one that forbids proc macro attribute invocations on the crate, or feature-gate the current usage so proc macro attributes can be stabilized without having to address this stuff first.

Otherwise, yeah @alexcrichton your comment was rather vague. I assumed you meant you don't see proc macro attribute invocations on the crate ever being stabilized.

**Comment by alexcrichton** [comment]
Er sorry yeah, let me clarify. Right now for "Macros 1.2" were very unlikely to stabilize attribute invocations on modules. It's a weird question of what does `#[foo] mod foo;` receive? Does it receive `mod foo ;`? The contents of the module `foo`?

Something like entire crate expansion also has huge repercussions on hygiene as well as whether it's feasible/quick. Entire crate expansion runs a risk of being extremely slow (we have to serialize back and forth with the procedural macro) and highly non-incremental (it's a complete black box to the compiler). I'd imagine that we're **very** far away from stabilizing this functionality, if at all. 

In that sense I'd personally be wary of landing this functionality in the compiler, even on nightly. I think it'd be best to take other avenues of attack for use cases that would otherwise require entire-crate expansion.

**Comment by abonander** [comment]
@alexcrichton It's already allowed but it's very buggy (#41430). So, feature-gate or forbid?

**Comment by alexcrichton** [comment]
I don't personally feel too strongly, although if it were exclusively up to me I'd err on the side of forbidding this rather than feature-gating a fixed implementaiton.

**Comment by abonander** [comment]
@petrochenkov what is your opinion on this? (see above discussion)

**Comment by abonander** [comment]
Closing this PR as this appears to need more discussion.

**Comment by petrochenkov** [comment]
Oh, this is closed now.
Nice, the less reviewing the better :laughing:

**Pull request closed without merging**
