### PR TITLE
update miri

### LINKED ISSUE #74132: `miri` no longer builds after rust-lang/rust#74059
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#74059, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @RalfJung, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/74132
Cc @rust-lang/miri r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
@bors r-
local CI failure

**Comment by Manishearth** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/74155#issuecomment-655664007

**Comment by RalfJung** [comment]
Wtf. "The filename, directory name, or volume label syntax is incorrect."? On Windows only? I have no way of debugging that.^^

I assume it is caused by https://github.com/rust-lang/miri/pull/1469 but why would `canonicalize` not work?

**Comment by RalfJung** [comment]
@rustbot ping windows
Does anybody with Windows experience have an idea what on Earth could be happening here? To reproduce, check out [this branch](https://github.com/RalfJung/rust/tree/miri) and run `./x.py test src/tools/miri --stage 0`. It works fine here on Linux.

**Comment by retep998** [comment]
`canonicalize` is a *bad* way to turn a relative path into an absolute path (at least on Windows anyway). There are several things to keep in mind:

* `canonicalize` only works when the path actually exists on the filesystem, and can be accessed.
* `canonicalize` does *not* work on certain filesystems, like some RAM disks don't support the operation.
* `canonicalize` returns a path of the form `\\?\C:\foo\bar` which can be problematic.
  * Not all programs support that form of path (such as MinGW)
  * If you join anything onto that path you *cannot* use `/` or `..` or `.` because `\\?\` paths disable the processing of those.

I continue to advocate for the addition of a better API to turn relative paths into absolute paths.

**Comment by RalfJung** [comment]
Any advice for what to do instead? The reason we need this is that Miri changes the working directory before invoking xargo, so to pass relative paths to xargo we have to make them absolute first.

**Comment by retep998** [comment]
The correct way to turn a relative path into an absolute path on Windows is `GetFullPathNameW` or the pure Rust equivalent. `std` does not currently provide such a function.

Ways to possibly fix it while still using `canonicalize` include:
* Ensure that anything that joins onto that path does not specify `/` or `.` or `..`.
* Strip the `\\?\` prefix.

**Comment by RalfJung** [comment]
I see, thanks. So https://github.com/japaric/xargo/pull/297 should help on the xargo side. But I have no idea if this is sufficient, and I cannot test this, so I think I'll also add a hack on the Miri side to strip the `\\?\` prefix.

**Comment by RalfJung** [comment]
I have fixed the cases of adding `/` or `..` to the path in xargo that I found.

It would be great if someone with a way to build rustc on Windows could checkout https://github.com/RalfJung/rust/tree/miri and run `x.py test src/tools/miri --stage 0` to see if that works now.

**Comment by mati865** [comment]
With miri at eee22ffddab20f51e1866bcbe4c5a69a90bdd260 it's tests pass on native windows-gnu.

**Comment by RalfJung** [comment]
Did you run them via `x.py`? That is the key here, as it sets `XARGO_RUST_SRC` which hits a different code path in `cargo-miri`.

**Comment by mati865** [comment]
Yeah using the command you have provided.

**Comment by RalfJung** [comment]
That's great, thanks a lot :)

**Comment by retep998** [comment]
For future reference on normalize vs canonicalize: https://github.com/rust-lang/rust/issues/59117

**Pull request merged**
