### PR TITLE
Update no_default_libraries handling for emscripten target

### PR DESCRIPTION
**Pull request by hoodmane**
@sbc100 says:

> `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]` is almost certainly wrong/out-of-date.   This setting defaults to the empty list anyway these days so its redundant.  Also we now support `-nodefaultlibs` so you can use that, as with other toolchains.

https://github.com/rust-lang/rust/issues/98303#issuecomment-1162163684

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by petrochenkov** [comment]
Given that `no_default_libraries` is currently `true` for emscripten targets it means that rustc will be in charge of passing or not passing `-lc` and similar.
Are you sure that's what you want, given that rustc is not aware of e.g. side modules?

**Comment by hoodmane** [comment]
I think this fixes the `no_default_libraries` function. Maybe it is a separate issue whether to set `no_default_libraries: true` or `no_default_libraries: false`? I agree it would probably be best to set `no_default_libraries: false`, I can do that in this PR too if you like.

**Comment by petrochenkov** [comment]
Ok, this PR keeps the status quo behavior now.
@bors r+ rollup

**Pull request merged**
