### PR TITLE
[do not merge] posix semaphores over make jobserver

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @ghost

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors retry try

Pushed up another commit which swaps out the cargo submodule (I'm not sure this'll actually get built on CI, but maybe?)

**Comment by Mark-Simulacrum** [comment]
@bors try

Should be good now, I think.

**Comment by petrochenkov** [comment]
[Disclaimer: I didn't follow this closely, so I may ask silly questions.]

If cargo and rustc use some custom jobserver protocol, won't that break their integration into larger build systems where they would need to respect externally imposed job limits?

**Comment by Mark-Simulacrum** [comment]
It potentially would, yes -- as part of the parallel compiler work we've identified that the existing jobserver implementation _may_ be a cause of slowness (large amount of time spent in the kernel). This is intended as a possibly 'easy' way to avoid that and if the results are positive, we can then work to identify a route forward and such.

One option we're considering is that each rustc would talk to Cargo over a custom protocol, but Cargo would still talk to a make jobserver for example, and 'cache' tokens for a brief time before giving them up or so.

To be clear it's very early days and we're at this point mostly in the gathering data phase and no full design work has been done.

**Pull request closed without merging**
