### PR TITLE
Update Zircon version in fuchsia toolchain build

### PR DESCRIPTION
**Pull request by raggi**

### CODE REVIEW

**Comment by kennytm** [comment]
@bors retry #40474 

Failed to clone the submodules.

**Comment by TimNN** [comment]
Ping from triage @raggi: This PR failed on travis.

**Comment by BatmanAoD** [comment]
Closing due to inactivity.

@raggi, please open a new PR or re-open this one when you have had a chance to make the necessary changes.

Note that pushing to your branch while the PR is closed may cause GitHub to prevent you from re-opening it.

**Pull request closed without merging**
