### PR TITLE
Revert part of #94372 to improve performance

### PR DESCRIPTION
**Pull request by nnethercote**
#94732 was supposed to give small but widespread performance improvements, as judged from three per-merge performance runs. But the performance run that occurred after merging included a roughly equal number of improvements and regressions, for unclear reasons.

This PR is for a test run reverting those changes, to see what happens.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
I tried this reversion locally and got uniform regressions, which is consistent with the notion that #94732 was a clear performance win.

**Comment by nnethercote** [comment]
Ok, those look very much like the inversion of the original results. I will try performance runs on some partial reversions, try to work out if a particular commit caused the problems.

**Comment by nnethercote** [comment]
I have updated to just revert the 5th (and final) commit.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Ok, reverting the 5th commit didn't do much. Let's try reverting the 4th commit as well.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Ok, that's way better. I wonder if making `CacheEncoder` non-generic somehow resulted in less inlining or something. @bjorn3, are you happy to have these two commits reverted? I'll probably redo the 5th commit (renaming `Encoder` as `MemEncoder`) in a follow-up.

r? @bjorn3

**Comment by bjorn3** [comment]
> I wonder if making CacheEncoder non-generic somehow resulted in less inlining or something.

I would guess so. Generic functions are codegened in the crate that uses them.

> are you happy to have these two commits reverted?

Yes. It would be nice to have the `finish()` move reapplied in a follow-up assuming that it doesn't regress performance.

@bors r+

**Comment by nnethercote** [comment]
A double free, huh. But there's no unsafe code in this patch and it doesn't seem related...

@bors retry

**Pull request merged**
