### PR TITLE
Update aarch64-linux-android target to match android abi.

### PR DESCRIPTION
**Pull request by Nercury**
- Changed `target_env` to "gnu" to empty "" for all android targets because it does not matter for android.
- The PR #33048 added "max_atomic_width" for arm-android but missed recently added armv7-android. Add it there too.
- Added features `+neon,+fp-armv8` because they [must exist on `aarch64` android](http://developer.android.com/ndk/guides/cpu-features.html).
- Update libc to include https://github.com/rust-lang/libc/pull/282 so that rust's std lib works on android's aarch64 (the main issue there was incorrect structure alignment on 64-bit arm).

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Argh `target_env: "gnu"` was a typo, these are intended to have an empty `env` as they don't currently have one listed. Perhaps this could update the others instead?

> Added eliminate_frame_pointer: false because the same option is also used by android's LLVM

Seems reasonable to me to follow what LLVM does here, but would be good to leave a comment as to why the option is set.

> Added features +neon,+fp-armv8 because they

Is there some "official" documentation stating this as well that we could point to?

**Comment by Nercury** [comment]
> Is there some "official" documentation stating this as well that we could point to?

Updated doc link to http://developer.android.com/ndk/guides/cpu-features.html, the section "64-bit ARM CPU family" mentions that FP and ASIMD (which is NEON) must be available.

**Comment by alexcrichton** [comment]
Could you add that link to the source where we specify those features? Also if you've got a link to the frame pointer business as well that'd be useful too!

**Comment by Nercury** [comment]
@alexcrichton Link added.

> Also if you've got a link to the frame pointer business as well that'd be useful too!

The frame pointer business so far is just a guess. Guess that works.

**Comment by alexcrichton** [comment]
Thanks! Could you squash the commits down, and if the frame pointer elimination is still up in the air perhaps we could leave that option as the default?

**Comment by Nercury** [comment]
> leave that option as the default

what do you mean? I only saw it set for aarch64, presumably because there are problems with stack unwinding otherwise, but I might be mistaken

> squash

a commit that updated liblibc got in by mistake, but do you want me to update libc as well?

**Comment by alexcrichton** [comment]
Have you observed crashes or otherwise incorrect results if frame pointers elimination is left on? I'm just thinking that if we don't have a concrete reason to turn it off we probably shouldn't, but if there's one then it's fine to turn off and we should just comment to that effect.

Ah throwing in a libc update is fine if necessary, but you can also rebase it out if you want.

**Comment by Nercury** [comment]
@alexcrichton 

- Rebased on latest master, noticed that `max_atomic_width` was added for `arm` target but not `armv7`, so added a fix for that.
- I have tested a version with and without frame pointers elimination, and there was no observable difference. It is now excluded from the PR.
- Updating libc to latest master.

**Comment by Nercury** [comment]
Excluding latest libc commit for now because it removed `libc::HW_NCPU` for some reason. We will probably need to resolve it in libc.

**Comment by alexcrichton** [comment]
Hm yes that's an accident that it was removed, but we can land this in the meantime.

@bors: r+ e512abd

**Pull request merged**
