### PR TITLE
Generate Property Note

### PR DESCRIPTION
**Pull request by cchiw**
Created for #103001. 

Generates the missing property note:
```
Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0	      Properties: x86 feature: IBT
```

### CODE REVIEW

**Comment by cchiw** [comment]
fixes #103001

**Comment by compiler-errors** [comment]
Hi, can you rebase to remove that merge commit out of the PR history? We have a no merge commit policy.

Also, it seems like a lot of the commits in this stack have duplicated names. Maybe they can be squashed into one?

**Comment by compiler-errors** [comment]
Also, that `fixes ###` note needs to be added to the PR description, not a comment, if you want it to take effect.

**Comment by cchiw** [comment]
Opened new PR https://github.com/rust-lang/rust/pull/110304

**Pull request closed without merging**
