### PR TITLE
Add std::io::IterReader

### PR DESCRIPTION
**Pull request by rapha**

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems like it's very similar to `.chain()` on many readers themselves, is there a reason that primitive doesn't suffice here?

**Comment by rapha** [comment]
Hmm, chain seems to concatenate two readers, but this is an adaptor from a plain Iterator<Vec<u8>>, for example, to a Reader. Have I understood chain correctly? Would a better name or doc make this clearer?

**Comment by alexcrichton** [comment]
Right, you can use an `Iterator` as well, but you can also call `.chain` successively. This seems like a pretty niche and/or specialized I/O construct which looks like it can be built with the existing constructs, which is why I was curious why `chain` wasn't sufficient.

**Comment by rapha** [comment]
The use case is actually to replace the old ChanReader in a generic way.

Given a `Receiver<Vec<u8>>` I want to be able to read from it. One of the
tests does that. Is there another way?

**Comment by alexcrichton** [comment]
I do agree that there's not necessarily a drop-in replacement for the old `ChanReader`, but this seems like a much more niche use case today and it's always possible to provide these sorts of constructs in your own crate.

**Comment by rapha** [comment]
What I need to do is something like `reader.read_u16::<BigEndian>()` reading from a `Receiver<Vec<u8>>`. I don't think that's possible right now.

Perhaps I'd be better off creating a separate cargo project for it?

**Comment by alexcrichton** [comment]
Yeah I think that this is best served starting off as a crate outside the standard library, and perhaps if it works well we can move it inside! For now though I'm going to close this for the prior reasons, but thanks for the PR!

**Pull request closed without merging**
