### PR TITLE
resolve: Relax fresh binding disambiguation slightly to fix regression

### LINKED ISSUE #71765: [regression] ambiguous local variable
For example:

```
INFO] [stderr] error[E0659]: `time` is ambiguous (glob import vs glob import in the same module)
[INFO] [stderr]    --> src/main.rs:257:13
[INFO] [stderr]     |
[INFO] [stderr] 257 |     let mut time = Local::now();
[INFO] [stderr]     |             ^^^^ ambiguous name
[INFO] [stderr]     |
[INFO] [stderr] note: `time` could refer to the function imported here
[INFO] [stderr]    --> src/main.rs:4:5
[INFO] [stderr]     |
[INFO] [stderr] 4   | use libc::*;
[INFO] [stderr]     |     ^^^^^^^
[INFO] [stderr]     = help: consider adding an explicit import of `time` to disambiguate
[INFO] [stderr] note: `time` could also refer to the function imported here
[INFO] [stderr]    --> src/main.rs:11:5
[INFO] [stderr]     |
[INFO] [stderr] 11  | use xcb_bindings::*;
[INFO] [stderr]     |     ^^^^^^^^^^^^^^^
[INFO] [stderr]     = help: consider adding an explicit import of `time` to disambiguate
[INFO] [stderr] 
```
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/RoBaaaT.rusty-pt/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/sam-barr.sam-bar/log.txt

cc @petrochenkov

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/71765

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by pnkfelix** [comment]
unilaterally accepting for beta-backport.

**Pull request merged**
