### PR TITLE
Rollup of 19 pull requests

### PR DESCRIPTION
**Pull request by alexcrichton**
- Successful merges: #40317, #40516, #40524, #40606, #40683, #40751, #40778, #40813, #40818, #40819, #40824, #40828, #40832, #40833, #40837, #40849, #40852, #40853, #40865
- Failed merges:

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: retry

* Travis instances shut down

**Comment by alexcrichton** [comment]
@bors: retry 

Same as before

**Comment by arielb1** [comment]
Travis shutdown

@bors retry

**Comment by arielb1** [comment]
Travis shutdown:
 - #40856

@bors retry

**Comment by arielb1** [comment]
```
[1325/1629] Linking CXX static library lib\libLLVMSystemZDisassembler.a
FAILED: lib/libLLVMSystemZDisassembler.a 
cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove lib\libLLVMSystemZDisassembler.a && C:\projects\rust\mingw64\bin\ar.exe qc lib\libLLVMSystemZDisassembler.a  lib/Target/SystemZ/Disassembler/CMakeFiles/LLVMSystemZDisassembler.dir/SystemZDisassembler.cpp.obj && C:\projects\rust\mingw64\bin\ranlib.exe lib\libLLVMSystemZDisassembler.a && cd ."
C:\projects\rust\mingw64\bin\ar.exe: unable to rename 'lib\libLLVMSystemZDisassembler.a'; reason: No such file or directory
[1326/1629] Linking CXX static library lib\libLLVMSystemZAsmPrinter.a
ninja: build stopped: subcommand failed.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1
```

sccache failure?

**Pull request merged**
