### PR TITLE
More through normalization, Feb/Mar 2017 edition

### LINKED ISSUE #27901: assertion failed: !projection_ty.has_escaping_regions() from astconv
## STR

``` Rust
trait Stream { type Item; }
impl<'a> Stream for &'a str { type Item = char; }
fn f<'s>(_: &'s str) -> (&'s str, <&'s str as Stream>::Item) { loop {}}
fn main() {
    f as for<'t> fn(&'t str) -> (&'t str, <&'t str as Stream>::Item);
}
```
## ICE

```
thread 'rustc' panicked at 'assertion failed: !projection_ty.has_escaping_regions()', ../src/librustc/middle/traits/fulfill.rs:142

stack backtrace:
   1:     0x7fb374005821 - sys::backtrace::write::h1f94a55df3f5c060tAs
                        at ../src/libstd/sys/unix/backtrace.rs:157
   2:     0x7fb374036dc2 - panicking::on_panic::h7395b54848e3e9ccyEx
                        at ../src/libstd/panicking.rs:45
   3:     0x7fb373f65456 - rt::unwind::begin_unwind_inner::hcaa18d84671dc6f1P5w
                        at ../src/libstd/rt/unwind/mod.rs:283
   4:     0x7fb370893b6c - rt::unwind::begin_unwind::h6172101820686538617
                        at ../src/libstd/rt/unwind/mod.rs:236
   5:     0x7fb3710fe472 - middle::traits::fulfill::FulfillmentContext<'tcx>::normalize_projection_type::hcf70e505dec3d2592IR
                        at /home/ariel/Rust/source.arielb1/build/<std macros>:3
   6:     0x7fb37350c4d0 - check::FnCtxt<'a, 'tcx>::normalize_associated_type::h1b069930cbf0a459JOo
                        at ../src/librustc_typeck/check/mod.rs:1370
   7:     0x7fb3734b4be9 - check::FnCtxt<'a, 'tcx>.AstConv<'tcx>::projected_ty::h36429f32ac9a3fffjuo
                        at ../src/librustc_typeck/check/mod.rs:1186
   8:     0x7fb373624429 - astconv::qpath_to_ty::h71e2ea7f4506a5a6DCv
                        at ../src/librustc_typeck/astconv.rs:1337
   9:     0x7fb373625635 - astconv::base_def_to_ty::h2f321ee71a45c0e11Hv
                        at ../src/librustc_typeck/astconv.rs:1441
  10:     0x7fb3735c9a3e - astconv::finish_resolving_def_to_ty::h34ff71956713a7572Nv
                        at ../src/librustc_typeck/astconv.rs:1494
  11:     0x7fb37351caaa - astconv::ast_ty_to_ty::h59f5403e5b7d66bdQPv
                        at ../src/librustc_typeck/astconv.rs:1603
  12:     0x7fb3736262cc - astconv::ast_ty_to_ty::closure.39826
                        at ../src/librustc_typeck/astconv.rs:1572
  13:     0x7fb3736261f4 - iter::Map<I, F>.Iterator::next::closure.39823
                        at ../src/libcore/iter.rs:1722
  14:     0x7fb373626167 - option::Option<T>::map::h14013055041868616625
                        at ../src/libcore/option.rs:423
  15:     0x7fb373626105 - iter::Map<I, F>.Iterator::next::h5773863637391150978
                        at ../src/libcore/iter.rs:1722
  16:     0x7fb373626396 - vec::Vec<T>::extend_desugared::h11629801303543280143
                        at ../src/libcollections/vec.rs:1470
  17:     0x7fb373625fb2 - vec::Vec<T>.FromIterator<T>::from_iter::h13404738094255389204
                        at ../src/libcollections/vec.rs:1394
  18:     0x7fb373625d1e - iter::Iterator::collect::h6317935585935112489
                        at ../src/libcore/iter.rs:565
  19:     0x7fb37351b565 - astconv::ast_ty_to_ty::h59f5403e5b7d66bdQPv
                        at ../src/librustc_typeck/astconv.rs:1571
  20:     0x7fb37360c760 - astconv::convert_ty_with_lifetime_elision::h6f460f7dd8faf27aFNu
                        at ../src/librustc_typeck/astconv.rs:570
  21:     0x7fb37362b512 - astconv::ty_of_method_or_bare_fn::hce05a437eae5328ff5v
                        at ../src/librustc_typeck/astconv.rs:1803
  22:     0x7fb37362664d - astconv::ty_of_bare_fn::h607ee3ec664c27fdH4v
                        at ../src/librustc_typeck/astconv.rs:1711
  23:     0x7fb37351b7f0 - astconv::ast_ty_to_ty::h59f5403e5b7d66bdQPv
                        at ../src/librustc_typeck/astconv.rs:1579
  24:     0x7fb37333a1d3 - check::FnCtxt<'a, 'tcx>::to_ty::h73fafe684209fa0dDVo
                        at ../src/librustc_typeck/check/mod.rs:1509
  25:     0x7fb3735a5de0 - check::check_expr_with_unifier::h6057465928997568522
                        at ../src/librustc_typeck/check/mod.rs:3497
  26:     0x7fb37331b230 - check::check_expr::h67cfff21408ddc9dxjq
                        at ../src/librustc_typeck/check/mod.rs:2636
  27:     0x7fb3735ce9b3 - check::check_stmt::haa8f485ee8788d35v0r
                        at ../src/librustc_typeck/check/mod.rs:4060
  28:     0x7fb3734f202f - check::check_block_with_expected::h92e2dfdb42860c63z4r
                        at ../src/librustc_typeck/check/mod.rs:4102
  29:     0x7fb3734b591e - check::check_fn::hfab5918ab6495513Szn
                        at ../src/librustc_typeck/check/mod.rs:625
  30:     0x7fb3734e3b42 - check::check_bare_fn::h69149d526417eee8xpn
                        at ../src/librustc_typeck/check/mod.rs:443
  31:     0x7fb3734dbb7d - check::check_item_body::hde42a3e9eb7fca98xPn
                        at ../src/librustc_typeck/check/mod.rs:718
  32:     0x7fb3734db584 - check::CheckItemBodiesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h19b7e1a3ef4d47d8Amn
                        at ../src/librustc_typeck/check/mod.rs:380
  33:     0x7fb3734e1914 - visit::walk_mod::h4457057824098729211
                        at ../src/libsyntax/visit.rs:165
  34:     0x7fb3734e1861 - visit::Visitor::visit_mod::h5000110883616035837
                        at ../src/libsyntax/visit.rs:64
  35:     0x7fb3734e2fdb - visit::walk_crate::h7371658545850931832
                        at ../src/libsyntax/visit.rs:157
  36:     0x7fb3734e2ab2 - check::check_item_types::hf8f1cb484009402b4mn
                        at ../src/librustc_typeck/check/mod.rs:400
  37:     0x7fb373756a00 - check_crate::closure.42607
                        at ../src/librustc_typeck/lib.rs:349
  38:     0x7fb3737563df - util::common::time::h5154388386627276761
                        at ../src/librustc/util/common.rs:39
  39:     0x7fb373752ec8 - check_crate::h1096b8cc64f43ddds5C
                        at ../src/librustc_typeck/lib.rs:348
  40:     0x7fb374718044 - driver::phase_3_run_analysis_passes::closure.16867
                        at ../src/librustc_driver/driver.rs:663
  41:     0x7fb374717de3 - middle::ty::tls::enter::closure.16858
                        at ../src/librustc/middle/ty.rs:1151
  42:     0x7fb374717b34 - thread::scoped_tls::ScopedKey<T>::set::h5740698089117313085
                        at ../src/libstd/thread/scoped_tls.rs:180
  43:     0x7fb374717594 - middle::ty::tls::enter::closure.16818
                        at ../src/librustc/middle/ty.rs:1151
  44:     0x7fb374717068 - thread::local::LocalKey<T>::with::h1047998320376595356
                        at ../src/libstd/thread/local.rs:217
  45:     0x7fb374716c83 - middle::ty::tls::enter::closure.16811
                        at ../src/librustc/middle/ty.rs:1145
  46:     0x7fb374716818 - thread::local::LocalKey<T>::with::h8975214402943655292
                        at ../src/libstd/thread/local.rs:217
  47:     0x7fb3747164a8 - middle::ty::tls::enter::h15244471624338917019
                        at ../src/librustc/middle/ty.rs:1144
  48:     0x7fb374713730 - middle::ty::ctxt<'tcx>::create_and_enter::h5448069206079026180
                        at ../src/librustc/middle/ty.rs:3746
  49:     0x7fb3746fa720 - driver::phase_3_run_analysis_passes::h17171246126576738064
                        at ../src/librustc_driver/driver.rs:651
  50:     0x7fb3746b28eb - driver::compile_input::h7936237b5328f2c1Tba
                        at ../src/librustc_driver/driver.rs:122
  51:     0x7fb3749b5ea3 - run_compiler::he5596ff537c688ddC7b
                        at ../src/librustc_driver/lib.rs:156
  52:     0x7fb3749b2688 - run::closure.29243
                        at ../src/librustc_driver/lib.rs:99
  53:     0x7fb3749b175d - monitor::closure.29214
                        at ../src/librustc_driver/lib.rs:809
  54:     0x7fb3749b1611 - boxed::F.FnBox<A>::call_box::h13102866563604429246
                        at ../src/liballoc/boxed.rs:515
  55:     0x7fb3749b11e0 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h15928366404761575081
                        at ../src/liballoc/boxed.rs:531
  56:     0x7fb3749b0c92 - thread::Builder::spawn_inner::closure.29187
                        at ../src/libstd/thread/mod.rs:322
  57:     0x7fb3749b0c0e - rt::unwind::try::try_fn::h2096641183789202929
                        at ../src/libstd/rt/unwind/mod.rs:168
  58:     0x7fb374035f57 - __rust_try_inner
  59:     0x7fb374035fad - __rust_try
  60:     0x7fb373fdacef - rt::unwind::try::inner_try::h8401f0adc136f5f2I1w
                        at ../src/libstd/rt/unwind/mod.rs:157
  61:     0x7fb3749b0b58 - rt::unwind::try::h2869518614589579972
                        at ../src/libstd/rt/unwind/mod.rs:140
  62:     0x7fb3749b09be - thread::Builder::spawn_inner::closure.29139
                        at ../src/libstd/thread/mod.rs:322
  63:     0x7fb3749b144d - boxed::F.FnBox<A>::call_box::h5650395233266235292
                        at ../src/liballoc/boxed.rs:515
  64:     0x7fb373ffc360 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h17370688546240473290
                        at ../src/liballoc/boxed.rs:523
  65:     0x7fb373ffc25c - sys_common::thread::start_thread::hcfc7a4e253eecb1deCr
                        at ../src/libstd/sys/common/thread.rs:30
  66:     0x7fb374031514 - sys::thread::Thread::new::thread_start::__rust_abi
                        at ../src/libstd/sys/unix/thread.rs:77
  67:     0x7fb374031494 - sys::thread::Thread::new::thread_start::hfb441bc8d197c3d5gbw
  68:     0x7fb36c1c10a3 - start_thread
  69:     0x7fb373bcb07c - clone
  70:                0x0 - <unknown>
```

### LINKED ISSUE #28828: Associated types are not correctly computed (at least not at the right time)
If I have an associated type that impls some trait or is some other known type, I can't treat it as so. Example ([playpen link](http://is.gd/he7Phw)):

``` rust
trait DoNothing {
    type Output;
}

struct Bob;
impl Bob {
    fn print() { println!("I AM BOB!"); }
}

impl DoNothing for Bob {
    type Output = Bob;
}

type BobAlso = <Bob as DoNothing>::Output;

fn main() {
    // works fine:
    Bob::print();
    // compiler error:
    BobAlso::print();
}
```

The type `BobAlso` is (or should be) just an alias for `Bob`, however when I try to call its `print()` function, the compiler complains that there is no `print` for `<Bob as DoNothing>::Output` without figuring out that that it _is_ `Bob`.

### LINKED ISSUE #38135: Broken MIR stemming from (potentially spurious?) type error
I'm getting this warning:

```rust
warning: broken MIR (Terminator { source_info: SourceInfo { span: src/array.rs:50:24: 50:89, scope: scope1 }, kind: _3 = std::ptr::read::<array::Array<<tll::ternary::Zero<L> as tll::ternary::NatPred>::Output, T>>(_5) -> [return: bb5, unwind: bb4] }): call dest mismatch (array::Array<<tll::ternary::Zero<L> as tll::ternary::NatPred>::Output, T> <- array::Array<tll::ternary::Two<<L as tll::ternary::NatPred>::Output>, T>): Sorts(ExpectedFound { expected: <tll::ternary::Zero<L> as tll::ternary::NatPred>::Output, found: tll::ternary::Two<<L as tll::ternary::NatPred>::Output> })
  --> src/array.rs:50:34
   |
50 |             let init = ptr::read(&self as *const Self as *const Array<Pred<Zero<L>>, T>);
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: broken MIR (Terminator { source_info: SourceInfo { span: src/array.rs:50:24: 50:89, scope: scope1 }, kind: _3 = std::ptr::read::<array::Array<<tll::ternary::Zero<L> as tll::ternary::NatPred>::Output, T>>(_5) -> [return: bb5, unwind: bb4] }): bad arg #0 (*const array::Array<tll::ternary::Two<<L as tll::ternary::NatPred>::Output>, T> <- *const array::Array<<tll::ternary::Zero<L> as tll::ternary::NatPred>::Output, T>): Sorts(ExpectedFound { expected: tll::ternary::Two<<L as tll::ternary::NatPred>::Output>, found: <tll::ternary::Zero<L> as tll::ternary::NatPred>::Output })
  --> src/array.rs:50:34
   |
50 |             let init = ptr::read(&self as *const Self as *const Array<Pred<Zero<L>>, T>);
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: broken MIR (_23 = _3): bad assignment (array::Array<tll::ternary::Two<<L as tll::ternary::NatPred>::Output>, T> = array::Array<<tll::ternary::Zero<L> as tll::ternary::NatPred>::Output, T>): Sorts(ExpectedFound { expected: tll::ternary::Two<<L as tll::ternary::NatPred>::Output>, found: <tll::ternary::Zero<L> as tll::ternary::NatPred>::Output })
  --> src/array.rs:54:14
   |
54 |             (init, last)
```

The types in question check out when I look at them; `tll::ternary::...` types and traits are from a type-level implementation of natural numbers represented in a ternary format. What's going on is that on the left-hand of these "type mismatches" is that one side has gone through normalization and the other has not (`Pred<Zero<L>>` should normalize to `Two<Pred<L>>`.) So, my (un)educated guess as to what's going on here is that normalization is not happening somewhere it should, and as such MIR is producing a spurious warning about a type mismatch.

Here's the code that causes it. Unfortunately, I don't think I can easily pare this down to a minimal reproduction case, but to start:

```rust
impl<L: Arrayify<T> + NatPred, T> Array<Zero<L>, T>
    where Pred<L>: Arrayify<T>
{
    fn split_last(self) -> (Array<Pred<Zero<L>>, T>, T) {
        unsafe {
            let init = ptr::read(&self as *const Self as *const Array<Pred<Zero<L>>, T>);
            let last = ptr::read((&self as *const Self as *const T)
                .offset(L::reify() as isize - 1));
            mem::forget(self);
            (init, last)
        }
    }
}
```

Changing the code to this compiles just fine with no broken MIR warnings:

```rust
impl<L: Arrayify<T> + NatPred, T> Array<Zero<L>, T>
    where Pred<L>: Arrayify<T>
{
    fn split_last(self) -> (Array<Pred<Zero<L>>, T>, T) {
        unsafe {
            let init = ptr::read(&self as *const Self as *const Array<Two<Pred<L>>, T>);
            let last = ptr::read((&self as *const Self as *const T)
                .offset(L::reify() as isize - 1));
            mem::forget(self);
            (init, last)
        }
    }
}
```

## Compiler info

```
sean@sean-Samus:~/Projects/tll-array$ rustc --version --verbose
rustc 1.15.0-nightly (908dba0c9 2016-12-01)
binary: rustc
commit-hash: 908dba0c9477b7dd022a236cb1514ddfca9369f2
commit-date: 2016-12-01
host: x86_64-unknown-linux-gnu
release: 1.15.0-nightly
LLVM version: 3.9
```

### LINKED ISSUE #39363: Broken MIR: bad DropAndReplace
> warning: broken MIR (Terminator { source_info: SourceInfo { span: src/bin/test.rs:10:5: 10:15, scope: scope3 }, kind: replace(_1 <- _9) -> [return: bb15, unwind: bb14] }): bad DropAndReplace (std::option::Option<image::ImageBuffer<image::Luma<u8>, std::vec::Vec<<image::Luma<u8> as image::Pixel>::Subpixel>>> = std::option::Option<image::ImageBuffer<image::Luma<u8>, std::vec::Vec<u8>>>): Sorts(ExpectedFound { expected: <image::Luma<u8> as image::Pixel>::Subpixel, found: u8 })
  --> src/bin/test.rs:10:18
   |
10 |     reassigned = Some(returned);
   |                  ^^^^^^^^^^^^^^

```rust
extern crate imageproc;
extern crate image;

fn main() {
    let mut reassigned: Option<imageproc::definitions::VecBuffer<image::Luma<u8>>> = None;

    let img = image::ImageBuffer::from_raw(1, 1, Vec::new()).unwrap();
    let returned = imageproc::filter::box_filter(&img, 3, 3);

    reassigned = Some(returned);
}
```

rustc 1.16.0-nightly (df8debf6d 2017-01-25)

```toml
[[package]]
name = "imageproc"
version = "0.7.0"

[[package]]
name = "image"
version = "0.12.2"
```

### LINKED ISSUE #39367: Internal Compiler Error (broken MIR) on stable/beta/nightly with lazy_static and shawshank
## Code
Cargo.toml
```
[package]
name = "ice_lazy_static_shawshank"
version = "0.1.0"

[dependencies]
lazy_static = "0.1.*"
shawshank = "0.2.*"
```

lib.rs
```
#[macro_use]
extern crate lazy_static;
extern crate shawshank;

lazy_static! {
    pub static ref ARENA: shawshank::ArenaSet<String> = {
        shawshank::string_arena_set()
    };
}
 
```

### Compiler info
`rustc --version --verbose`:
```
rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-apple-darwin
release: 1.14.0
LLVM version: 3.9
```

### Backtrace
`RUST_BACKTRACE=1 cargo build`
```
   Compiling ice_lazy_static_shawshank v0.1.0 (file:///Users/jpschorr/rust/ice_lazy_static_shawshank)
warning: broken MIR (<ARENA as std::ops::Deref>::deref::__stability::DATA = _2): bad assignment (*const shawshank::ArenaSet<std::string::String> = *const shawshank::ArenaSet<std::string::String, usize, std::collections::HashMap<&'static str, usize>>): Sorts(ExpectedFound { expected: <std::string::String as std::ops::Deref>::Target, found: str })
 --> src/lib.rs:5:1
  |
5 | lazy_static! {
  | ^
  |
  = note: this error originates in a macro outside of the current crate

warning: broken MIR (_4 = &(*<ARENA as std::ops::Deref>::deref::__stability::DATA)): bad assignment (&'static shawshank::ArenaSet<std::string::String, usize, std::collections::HashMap<&'static str, usize>> = &'static shawshank::ArenaSet<std::string::String>): Sorts(ExpectedFound { expected: str, found: <std::string::String as std::ops::Deref>::Target })
 --> src/lib.rs:5:1
  |
5 | lazy_static! {
  | ^
  |
  = note: this error originates in a macro outside of the current crate

error: internal compiler error: ../src/librustc_trans/debuginfo/type_names.rs:149: debuginfo: Trying to create type name for unexpected type: <std::string::String as std::ops::Deref>::Target

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:424
stack backtrace:
   1:        0x11298bfaa - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
   2:        0x11299bd6f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
   3:        0x112998e35 - std::panicking::default_hook::h5897799da33ece67
   4:        0x112999566 - std::panicking::rust_panic_with_hook::h109e116a3a861224
   5:        0x11282761a - std::panicking::begin_panic::h7ee1a5d23402297a
   6:        0x112838b84 - rustc_errors::Handler::bug::hcb152875f06770ca
   7:        0x10fa6323c - rustc::session::opt_span_bug_fmt::{{closure}}::hac6e8f2df662620f
   8:        0x10f991ba9 - rustc::session::opt_span_bug_fmt::he7e61f6adc55e29d
   9:        0x10f99172a - rustc::session::bug_fmt::h995c6792d8929834
  10:        0x10e984826 - rustc_trans::debuginfo::type_names::push_debuginfo_type_name::hcc7d963c9e9ec306
  11:        0x10e983c40 - rustc_trans::debuginfo::type_names::push_debuginfo_type_name::hcc7d963c9e9ec306
  12:        0x10e98516f - rustc_trans::debuginfo::type_names::push_debuginfo_type_name::push_type_params::hcc94e8d523543311
  13:        0x10e98391e - rustc_trans::debuginfo::type_names::push_debuginfo_type_name::hcc7d963c9e9ec306
  14:        0x10e98516f - rustc_trans::debuginfo::type_names::push_debuginfo_type_name::push_type_params::hcc94e8d523543311
  15:        0x10e98391e - rustc_trans::debuginfo::type_names::push_debuginfo_type_name::hcc7d963c9e9ec306
  16:        0x10e98919b - rustc_trans::debuginfo::metadata::type_metadata::hb8e4086e618f8959
  17:        0x10e98854c - rustc_trans::debuginfo::metadata::type_metadata::hb8e4086e618f8959
  18:        0x10e9cc155 - rustc_trans::trans_item::TransItem::define::hf67eb98c96335402
  19:        0x10e94f4cd - rustc_trans::base::trans_crate::h47f4206b4f9f44d2
  20:        0x10e79ecd1 - rustc_driver::driver::phase_4_translate_to_llvm::hd8440dd1d6d967c3
  21:        0x10e7d64dc - rustc_driver::driver::compile_input::{{closure}}::h1d3b0af04a04cdbb
  22:        0x10e7c334b - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h5a9a7c8e1b6dbe3a
  23:        0x10e79cb16 - rustc_driver::driver::phase_3_run_analysis_passes::h823704ee01fd0a1e
  24:        0x10e7856e5 - rustc_driver::driver::compile_input::h66a0adaf05fab85d
  25:        0x10e7b0019 - rustc_driver::run_compiler::hafe7bbfedf95a825
  26:        0x10e6e7d28 - std::panicking::try::do_call::h5ff5e568cb9cce51
  27:        0x11299c32a - __rust_maybe_catch_panic
  28:        0x10e707eff - <F as alloc::boxed::FnBox<A>>::call_box::h92e2f4ed0df1d5b6
  29:        0x1129983d4 - std::sys::imp::thread::Thread::new::thread_start::ha102a6120fc52763
  30:     0x7fff995cd99c - _pthread_body
  31:     0x7fff995cd919 - _pthread_start

error: Could not compile `ice_lazy_static_shawshank`.
```

### Also
Similarly, it happens for

```
rustc 1.15.0-beta.5 (10893a9a3 2017-01-19)
binary: rustc
commit-hash: 10893a9a349cdd423f2490a6984acb5b3b7c8046
commit-date: 2017-01-19
host: x86_64-apple-darwin
release: 1.15.0-beta.5
LLVM version: 3.9
```
```
rustc 1.16.0-nightly (df8debf6d 2017-01-25)
binary: rustc
commit-hash: df8debf6d9afc431adbbd8311dcaf2b70eb9762e
commit-date: 2017-01-25
host: x86_64-apple-darwin
release: 1.16.0-nightly
LLVM version: 3.9
```

### PR DESCRIPTION
**Pull request by arielb1**
Fix a few normalization bugs.

Fixes #27901.
Fixes #28828.
Fixes #38135.
Fixes #39363.
Fixes #39367.

### CODE REVIEW

**Comment by arielb1** [comment]
Don't merge - there's still a test (default_ty_param_default_dependent_associated_type) that causes broken MIR - silently until now - which is now an ICE.

**Review by eddyb — APPROVED** [review]
LGTM, but the `Lvalue::Static` change makes me nervous. cc @rust-lang/compiler Any opinions?

**Comment by arielb1** [comment]
Can @nikomatsakis confirm that I didn't break new-style default inference in 4dee3c45080b5f9b917f8d4696adb424ff67a28e  ?

**Comment by aravind-pg** [comment]
The third issue linked in the PR description (#38185) must have a typo, since currently it's an unrelated PR and not an issue.

**Comment by nikomatsakis** [comment]
@arielb1 this looks good, I think I will do a crater run perhaps though? I see you changed the MIR stuff from warn to bug and I'm curious what may be affected...

**Comment by nikomatsakis** [comment]
Zero regressions found: https://gist.github.com/nikomatsakis/c380f63061941c4989faf58469f36356

**Pull request merged**
