### PR TITLE
cache `collect_trait_impl_trait_tys`

### PR DESCRIPTION
**Pull request by compiler-errors**
Micro-optimization for RPITITs

### CODE REVIEW

**Comment by compiler-errors** [comment]
Shouldn't have much/any perf effect on non-RPITIT (return-position `impl Trait` in trait) code, but just checking...

**Comment by petrochenkov** [comment]
No difference it seems.
@rustbot author

**Comment by compiler-errors** [comment]
@petrochenkov I actually expected this to show no improvements, just wanted to double check this showed no regressions for code that didn't use these queries (but also I didn't expect any). This will probably be a significant improvement for incremental code that _does_ use return-position `impl Trait` in traits, but there's no test suites using that since it's experimental. 

I would still like to land this though, since it's along the same lines as caching the `type_of` query but for RPITIT.

@rustbot ready

**Pull request merged**
