### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by workingjubilee**
Successful merges:

 - #126183 (Separate core search logic with search ui)
 - #129366 (linker: Synchronize native library search in rustc and linker)
 - #129403 (Ban non-array SIMD)
 - #129527 (Don't use `TyKind` in a lint)
 - #129534 (Deny `wasm_c_abi` lint to nudge the last 25%)
 - #129640 (Re-enable android tests/benches in alloc/core)
 - #129731 (Allow running `./x.py test compiler`)
 - #129754 (wasi: Fix sleeping for `Duration::MAX`)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=126183,129366,129403,129527,129534,129640,129731,129754)

### CODE REVIEW

**Comment by workingjubilee** [comment]
> error: couldn't create a temp dir: Access is denied. (os error 5) at path "C:\\a\\_temp\\msys64\\tmp\\rustcLNVkKB"

classic spurious

**Comment by matthiaskrgr** [comment]
partially merged  already in https://github.com/rust-lang/rust/pull/129809

**Pull request closed without merging**
