### PR TITLE
[Experiment] Box `diagnostic_metadata` field

### LINKED ISSUE #97954: `Box` `DiagnosticMetadata` field in `LateResolutionVisitor`
We should experiment with making the `rustc_resolve::late::DiagnosticMetadata` field in `rustc_resolve::late::LateResolutionVisitor` boxed and run perf to see if that improves compilation times.

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes #97954

r? @estebank

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
I don't have permission to run perf.

**Comment by eggyal** [comment]
This is exactly what I had thought the issue was saying, yet it surely only adds the cost of additional heap allocs?  I'm sure I must be missing something, as I can't see how there could be any benefit from it?

**Comment by joshtriplett** [comment]
@TaKO8Ki Very nice!

**Comment by eggyal** [comment]
Really surprised by this... can someone explain it?

**Comment by Kobzol** [comment]
In general, boxing an attribute moves it to the heap, so you pay the cost for allocating (both in executed instructions and extra memory usage). But on the other hand, it can reduce the size of the structure that contains the attribute (e.g. if a field has 64 bytes and you box it, the size gets reduced to 8 bytes), which in turn can improve performance (less data loaded from memory, better cache utilization).

That being said, I'm not really seeing any great improvements in the perf. results here. Instruction counts and cycles are a wash and Max RSS was improved only in three cases with quite low significance factor (in average it's just -0.24% improvement). So I'm not sure if this is worth it.

**Comment by eggyal** [comment]
> But on the other hand, it can reduce the size of the structure that contains the attribute (e.g. if a field has 64 bytes and you box it, the size gets reduced to 8 bytes), which in turn can improve performance (less data loaded from memory, better cache utilization etc.).

Indeed, but this particular structure is quite large already so the reduction in its stack size shouldn't have a material impact.  Moreover, the identified change is to total memory consumption: yet the heap allocs are made on object creation and maintained until object destruction so total memory should in fact have increased (by the size of the pointer).

Anyway, thank you for your thoughts!  I'll leave it at that; I just found the idea of this experiment, and it's outcome, rather surprising/unintuitive.

**Comment by estebank** [comment]
> this particular structure is quite large already

Is it? The only things that stand out to me as "potentially big" are `ParentScope` and `PerNS`, all other fields are in the heap, in one way or another (`Vec`, `&`, `HashMap`).

https://github.com/rust-lang/rust/blob/5ece48116268cc84dda565d4d2641d619075c957/compiler/rustc_resolve/src/late.rs#L521-L552

That being said, given how resolution behaves, without needing to clone or be moved too much, I guess it's not surprising this didn't have significant perf impacts, beyond the margins. That being said, I can go either on whether we should merge this or not, particularly given the patch size :)

**Pull request merged**
