### PR TITLE
Upgrade jemalloc to 5.0.1

### PR DESCRIPTION
**Pull request by sfackler**
The build script needs to run autoconf which should be fine, right?

We're building against 5.0.1 with https://github.com/jemalloc/jemalloc/commit/0a4f5a7eea5e42292cea95fd30a88201c8d4a1ca cherry-picked on top.

r? @alexcrichton

### CODE REVIEW

**Comment by sfackler** [comment]
Ok, so it looks like requiring autoconf is a problem. I've pushed an extra commit de-ignoring the config file and check it in.

**Comment by kennytm** [comment]
There is no O_CLOEXEC?

```
[00:02:12] /checkout/src/liballoc_jemalloc/../jemalloc/src/pages.c: In function 'os_overcommits_proc':
[00:02:12] /checkout/src/liballoc_jemalloc/../jemalloc/src/pages.c:357:6: error: 'O_CLOEXEC' undeclared (first use in this function)
[00:02:12]       O_CLOEXEC);
[00:02:12]       ^
...
[00:02:12] /checkout/src/liballoc_jemalloc/../jemalloc/src/prof.c: In function 'prof_open_maps':
[00:02:12] /checkout/src/liballoc_jemalloc/../jemalloc/src/prof.c:1412:34: error: 'O_CLOEXEC' undeclared (first use in this function)
[00:02:12]   mfd = open(filename, O_RDONLY | O_CLOEXEC);
[00:02:12]                                   ^
```

**Comment by sfackler** [comment]
We build dists on a version of Linux from before CLOEXEC was created. Jemalloc's dev branch has a patch to deal with this but it's not in 5.0.1: https://github.com/jemalloc/jemalloc/commit/0975b88dfd3a890f469c8c282a5140013af85ab2.

Hopefully it applies cleanly.

**Comment by kennytm** [comment]
@bors r-

Build failed on `android`, some problem with the TLS section. (Travis log: https://travis-ci.org/rust-lang/rust/jobs/286655880)

```
[00:44:38] /checkout/src/liballoc_jemalloc/../jemalloc/src/tsd.c:20:35: error: __emutls_t.tsd_tls causes a section type conflict with tsd_tls
[00:44:38]  __thread tsd_t JEMALLOC_TLS_MODEL tsd_tls = TSD_INITIALIZER;
[00:44:38]                                    ^
[00:44:38] /checkout/src/liballoc_jemalloc/../jemalloc/src/tsd.c:20:35: note: 'tsd_tls' was declared here
[00:44:38] make: *** [src/tsd.sym.o] Error 1
[00:44:38] make: *** Waiting for unfinished jobs....
[00:44:38] 
[00:44:38] [m[m[33m[1mwarning:[m build failed, waiting for other jobs to finish...
[00:44:41] [m[m[31m[1merror:[m build failed
[00:44:41] thread 'main' panicked at 'command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "arm-linux-androideabi" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:44:41] expected success, got: exit code: 101', /checkout/src/bootstrap/compile.rs:883:8
[00:44:41] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:44:41] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap dist --target arm-linux-androideabi,armv7-linux-androideabi,i686-linux-android,aarch64-linux-android,x86_64-linux-android
[00:44:41] Build completed unsuccessfully in 0:42:32
```

**Comment by kennytm** [comment]
Looks like this still have issues on Android, causing the compiled program sometimes segfault. Travis logs:

* https://travis-ci.org/rust-lang/rust/jobs/287128840
* https://travis-ci.org/rust-lang/rust/jobs/287051037 (https://github.com/rust-lang/rust/pull/45233#issuecomment-336163981)
* https://travis-ci.org/rust-lang/rust/jobs/286961062 (https://github.com/rust-lang/rust/pull/45233#issuecomment-336122096)

**Comment by sfackler** [comment]
Grr, ok thanks.

**Comment by sfackler** [comment]
I'm going to close this since I don't really want to figure out how to get the Android setup working.

**Pull request closed without merging**
