### PR TITLE
Simplify on_panic callback handling

### PR DESCRIPTION
**Pull request by ranma42**
This is part of some cleanup I did while investigating #28129.
This also ensures that `on_panic` is run even if the user has registered too many callbacks.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Actually while you're at it, could you remove the `unwind::register` function (and the callback array) altogether? They're from an era long since passed and shouldn't be necessary any more.

Thanks for the cleanups!

**Comment by ranma42** [comment]
Wow, I dod not expect that to already be possible, but I'm very glad to do that. More patches incoming :)

**Comment by ranma42** [comment]
I updated this PR. I started another one to make panicking more robust (in particular, to make sure that if `on_panic` panics, it does not end up in an infinite recursion and correctly aborts at the double panic)

**Comment by alexcrichton** [comment]
@bors: r+ c6d277ade642a8cf166d6e4706add90fb9181ec2

Thanks! I wouldn't go to too much effort to ensure that recursive panics like that don't lead to bugs, they're pretty rare the all code run is contained in the standard library so it's easy to audit. If the fix is relatively lightweight, however, seems fine to me!

**Pull request merged**
