### PR TITLE
Simplify wording on `*::as_ptr` docs.

### PR DESCRIPTION
**Pull request by mejrs**
This removes usage of "non-transitively" in several pieces of documentation.

I believe this wording is not clear enough (especially for nonnative speakers) and I hope this is better. I'm open to suggestions :)

### CODE REVIEW

**Comment by 5225225** [comment]
Maybe it would be better to show an example?

Like

```rust
let mut value = 0;
let value_ptr = &mut value as *mut i32;
let vec = vec![value_ptr];
vec.as_ptr().read().write(100);
assert_eq!(value, 100);
```

Though that is a pretty complex example and it's the smallest one I could think of. Not sure! (Also I'm *fairly sure* that example is not UB but others would want to weigh in here).

**Comment by mejrs** [comment]
> Maybe it would be good to also show an example?

Hmm, I'm not a fan of examples like that. IMO it's a bit questionable and I wouldn't expect to see much code like that.

**Comment by m-ou-se** [comment]
I agree the current documentation isn't the best and should be improved, but I'm not sure the changes in this PR are clear/accurate.

I think that "Writing to memory that this pointer points to is undefined behavior, [..]" doesn't make it clear enough that it's just that this pointer can't be used for writing, but that it might be fine to write through another pointer to the same memory.

@RalfJung or @Gankra might have a good idea on how to describe it accurately.

**Comment by RalfJung** [comment]
> This removes usage of "non-transitively" in several pieces of documentation.

(Not a native speaker here)

This "non-transitively" was potentially important though. "Memory this point points to" for a situation like `*mut *mut i32` might be interpreted as referring to the memory behind both indirections. I'm open to better ways of expressing this, and maybe that kind of misunderstanding us unlikely to happen, but I worry than in another year we'll have to add this back since some says they misunderstood the docs.

> I think that "Writing to memory that this pointer points to is undefined behavior, [..]" doesn't make it clear enough that it's just that this pointer can't be used for writing, but that it might be fine to write through another pointer to the same memory.

Indeed, provenance matters. Rights *through this pointer* (and its derived 'children') are UB, other writes are fine.

**Comment by mejrs** [comment]
I'm still not sure how I would describe "non-transitively" in a succinct and accurate way - the way this PR words it is the simplest I could come up with.

Would  changing `Writing to memory that this pointer` to `writing through this pointer` address the provenance aspect?

(I'm also not a native speaker and I understand its meaning here mostly through context, not from an understanding of what the word actually means)

**Comment by RalfJung** [comment]
I mentioned the non-native speaker since you brought it up in the PR description. ;)

> I'm still not sure how I would describe "non-transitively" in a succinct and accurate way - the way this PR words it is the simplest I could come up with.

If we have to pick one, accuracy is more important than succinctness for these kinds of docs.

Usually the opposite of 'transitive' is 'direct' or 'immediate'. "memory this pointer (directly) points to"? We probably still need to add a parenthetical explaining what "indirect" would mean here.

> Would changing Writing to memory that this pointer to writing through this pointer address the provenance aspect?

Kind-of, but overall I still find the wording confusing. What does it mean for a write to "go through interior mutability of its own"?

Also if we are touching this, we should probably clarify that *any* write to that memory invalidates this pointer.
```rust
fn uwu(x: &mut [i32]) {
  let ptr = x.as_ptr();
  x[0] = 0;
  ptr.read(); // UB! The write on the previous line invalidated this pointer.
}

**Pull request closed without merging**
