### PR TITLE
rustc: Don't ICE on usage of two new target features

### PR DESCRIPTION
**Pull request by alexcrichton**
I seem to always forget to update this portion of the compiler...

### CODE REVIEW

**Comment by oli-obk** [comment]
r=me after a rebase

**Comment by jethrogb** [comment]
Can we make a test that makes it harder to forget this part?

**Comment by alexcrichton** [comment]
Heh I'm sure we can! I'm not sure we add new features here often enough to make it worth it though. I'd certainly be willing to r+ such a patch though

**Pull request merged**
