### PR TITLE
Rollup of 6 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #129687 (Implement RFC3137 trim-paths sysroot changes - take 2)
 - #130820 (Fix diagnostics for coroutines with () as input.)
 - #130833 (Fix the misleading diagnostic for `let_underscore_drop` on type without `Drop` implementation)
 - #130845 (Utf8Chunks: add link to Utf8Chunk)
 - #130868 (Update FIXME comment in s390x_unknown_linux_*.rs)
 - #130873 (rustc_target: Add powerpc64 atomic-related features)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=129687,130820,130833,130845,130868,130873)

### CODE REVIEW

**Comment by Urgau** [comment]
> = note: LINK : fatal error LNK1104: cannot open file 'C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-rustc\x86_64-pc-windows-msvc\release\deps\rustc_main-d1793530025d8163.exe'

cc https://github.com/rust-lang/rust/issues/127883, @bors retry

**Comment by tgross35** [comment]
``failed to remove file `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe```

@bors retry

**Comment by tgross35** [comment]
Oh, I guess this is superseded by https://github.com/rust-lang/rust/pull/130893. Will close it then.

**Pull request closed without merging**
