### PR TITLE
[beta] next

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Backports of:

* rustdoc: Fix doc aliases with crate filtering #73644
* rustdoc: Rename invalid_codeblock_attribute lint to be plural #74131 
* rustc_lexer: Simplify shebang parsing once more #73596
* Perform obligation deduplication to avoid buggy `ExistentialMismatch` #73485
* Reorder order in which MinGW libs are linked to fix recent breakage #73184
* Change how compiler-builtins gets many CGUs #73136 
* Fix wasm32 being broken due to a NodeJS version bump #73885

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors rollup=never p=20 r+

Should be the last round of beta backports.

**Comment by Manishearth** [comment]
```
2020-07-10T17:33:01.0331851Z Set({"src/libpanic_abort"}) not skipped for "bootstrap::test::Crate" -- not in ["src/libcore", "src/liballoc", "src/libproc_macro", "src/libstd", "src/libterm", "src/libtest"]
2020-07-10T17:33:01.0346894Z thread 'main' panicked at 'nodejs not configured', src/bootstrap/test.rs:1762:17
2020-07-10T17:33:01.0347403Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2020-07-10T17:33:01.0362643Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --target wasm32-unknown-emscripten --exclude src/libcore --exclude src/liballoc --exclude src/libproc_macro --exclude src/libstd --exclude src/libterm --exclude src/libtest
```

@bors yield

this failed housr ago

**Comment by Mark-Simulacrum** [comment]
@bors rollup=never p=20 r+

Included "Fix wasm32 being broken due to a NodeJS version bump #73885".

**Comment by Mark-Simulacrum** [comment]
@bors retry network?

```
2020-07-10T23:03:52.6150499Z error: failed to get `cc` as a dependency of package `bootstrap v0.0.0 (D:\a\1\s\src\bootstrap)`
2020-07-10T23:03:52.8597051Z 
2020-07-10T23:03:52.8605158Z Caused by:
2020-07-10T23:03:52.8606450Z   failed to fetch `https://github.com/rust-lang/crates.io-index`
2020-07-10T23:03:52.8607548Z 
2020-07-10T23:03:52.8609580Z Caused by:
2020-07-10T23:03:52.8610738Z   error inflating zlib stream; class=Zlib (5)
```

**Comment by Mark-Simulacrum** [comment]
Looks like ~5 minutes too long :/

@bors retry - timeout 4h 20m 34s

**Comment by Manishearth** [comment]
@eddyb mentioned that the LLVM rebuilds might be causing the delays? @pietroalbini do we cache LLVM builds on CI?

**Comment by Manishearth** [comment]
Wow, timely

**Comment by mati865** [comment]
LLVM is cached with sscache.

**Comment by pietroalbini** [comment]
> do we cache LLVM builds on CI?

Yes, but the cache expires after a while.

**Comment by Mark-Simulacrum** [comment]
@bors retry

I think there's nothing other than just retrying to try and make progress here, right? I don't think we have a way of getting the llvm builds built (if they're the cause).

**Comment by Manishearth** [comment]
@bors treeclosed=20

this might cause timeouts due to llvm, going to try and get this landed today

**Comment by mati865** [comment]
> We stopped hearing from agent Azure Pipelines 2. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610

😕

**Pull request merged**
