### PR TITLE
Speed up compilation of `type-system-chess`

### PR DESCRIPTION
**Pull request by nnethercote**
[`type-system-chess`](https://github.com/rust-lang/rustc-perf/pull/1680) is an unusual program that implements a compile-time chess position solver in the trait system(!)  This PR is about making it compile faster.

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
[These lines](https://github.com/rust-lang/rust/blob/098c1db7e55e7229a520a2ec8e460e1e300e109b/compiler/rustc_trait_selection/src/traits/project.rs#L1232-L1238) are the cause. They perform deduplication on obligation vectors. The vectors get enormous, the biggest are over 250,000 elements. The deduplication of these huge vectors is effective, typically removing more than half of the elements.

**Comment by nnethercote** [comment]
Perf results look good, various small improvements in secondary benchmarks. The real driver was the type-system-chess program I mentioned above, where the walltime and max-rss changes were both about -85% when I measured them locally.

r? @compiler-errors

**Comment by zesterer** [comment]
Is this likely to have a meaningful impact on other crates that produce a lot of trait obligations such as [chumsky](www.github.com/zesterer/chumsky)?

**Comment by nnethercote** [comment]
`type-system-chess` is an extreme outlier. I doubt this will have any effect on "real world" crates beyond perhaps a couple of percent. But you'd have to measure to be sure (nightly vs release should suffice).

**Pull request merged**
