### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Successful merges:

 - #72180 (remove extra space from crate-level doctest names)
 - #73012 (Show `SyntaxContext` in formatted `Span` debug output)
 - #73097 (Try_run must only be used if toolstate is populated)
 - #73169 (Handle assembler warnings properly)
 - #73182 (Track span of function in method calls, and use this in #[track_caller])
 - #73207 (Clean up E0648 explanation)
 - #73230 (Suggest including unused asm arguments in a comment to avoid error)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
Something in this rollup broke Miri, it now ICEs with
```
thread 'rustc' panicked at 'internal error: entered unreachable code', /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
But for some reason its toolstate is still green.

@Xanewok @Mark-Simulacrum is it expected that this fixed rls/rustfmt toolstate without changing those tools? Given that this landed a change in the toolstate logic in bootstrap, maybe that logic is just wrong now and reports all tools as working?

**Comment by Xanewok** [comment]
Yes, it 'fixed' the toolstate but it's still broken as far as I can tell.

**Comment by Mark-Simulacrum** [comment]
Very strange. I'll take a look, the change should have only affected clippy...

**Pull request merged**
