### PR TITLE
Fix false "never constructed" warnings for `Self::` variant paths (resolved conflict)

### LINKED ISSUE #64362: "variant is never constructed" lint appears to be incorrect?
This code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c03d4fa0a396d0476637d39c43bda0c2)) causes a "variant is never constructed" lint, even though the variant is constructed in the `FromStr` implementation:

```rust
use std::str::FromStr;

enum Foo {
    A { inner: () },
    B,
}

impl FromStr for Foo {
    type Err = ();
    
    fn from_str(s: &str) -> Result<Self, ()> {
        match s {
            "a" => Ok(Self::A { inner: () }),
            "b" => Ok(Self::B),
            _ => Err(()),
        }
    }
}
```

```
warning: variant is never constructed: `A`
 --> src/lib.rs:4:5
  |
4 |     A { inner: () },
  |     ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

Changing `Self` for the type name in `from_str` for `Foo` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=83856b4a0fbfa3510c8fe9eb3873ac8e)) compiles with the "field is never used" lint I would expect from this code.

Tested on `rustc 1.39.0-nightly (0b36e9dea 2019-09-09)`

This issue has been assigned to @jakubadamw via [this comment](https://github.com/rust-lang/rust/issues/64362#issuecomment-530559466).

### PR DESCRIPTION
**Pull request by seiyab**
Closes #64362.
Resolved conflict of original PR #64424

### CODE REVIEW

**Comment by seiyab** [comment]
Failure is reproduced also on my machine.
I misunderstood the way to test a compiler.
I'll try to fix.

**Comment by seiyab** [comment]
I may stuck.
Is this because the feature impl_trait_in_bindings is incomplete ... ?
I'll read rustc code more for the time being.

**Comment by estebank** [comment]
Try running the test that is failing in isolation with your built `rustc`. When doing so, set `RUST_BACKTRACE=1` so that you can see the backtrace of where the error is coming from.

I believe what might be happening is that `let res = self.tables.qpath_res(qpath, id);` gives you a `Res` corresponding to the original crate, and not its local import. I am not entirely sure how to help with this, I'll have to dig deeper. @petrochenkov might have better insight on how to proceed here.

**Comment by seiyab** [comment]
Thank you for your comment.

In my interpretation, `let res = self.tables.qpath_res(qpath, id);` searches on the  TypeckTable of owner `fn foo ...` but it requires to search on the TypeckTable of owner `impl FooLike<Output = T::Assoc>` .

<details><summary>Here is output of --hir-tree where I think to be related</summary>
```
Crate {
    ...
    items: {
        ...
        HirId {
            owner: DefIndex(32),
            local_id: 0,
        }: Item {
            ident: impl_trait_in_bindings#0,
            hir_id: HirId {
                owner: DefIndex(32),
                local_id: 0,
            },
            attrs: [],
            kind: Mod(
                Mod {
                    inner: $DIR/bound-normalization-pass.rs:62:5: 77:2,
                    item_ids: [
                        ...
                        ItemId {
                            id: HirId {
                                owner: DefIndex(39),
                                local_id: 0,
                            },
                        },
                        ItemId {
                            id: HirId {
                                owner: DefIndex(41),
                                local_id: 0,
                            },
                        },
                    ],
                },
            ),
            vis: Spanned {
                node: Inherited,
                span: $DIR/bound-normalization-pass.rs:61:1: 61:1,
            },
            span: $DIR/bound-normalization-pass.rs:61:1: 77:2,
        },
        ...
        HirId {
            owner: DefIndex(41),
            local_id: 0,
        }: Item {
            ident: foo#0,
            hir_id: HirId {
                owner: DefIndex(41),
                local_id: 0,
            },
            attrs: [],
            kind: Fn(
                FnSig {
                    header: FnHeader {
                        unsafety: Normal,
                        constness: NotConst,
                        asyncness: NotAsync,
                        abi: Rust,
                    },
                    decl: FnDecl {
                        inputs: [],
                        output: DefaultReturn(
                            $DIR/bound-normalization-pass.rs:74:35: 74:35,
                        ),
                        c_variadic: false,
                        implicit_self: None,
                    },
                },
                Generics {
                    params: [
                        GenericParam {
                            hir_id: HirId {
                                owner: DefIndex(41),
                                local_id: 15,
                            },
                            name: Plain(
                                T#0,
                            ),
                            attrs: [],
                            bounds: [
                                Trait(
                                    PolyTraitRef {
                                        bound_generic_params: [],
                                        trait_ref: TraitRef {
                                            path: path(Trait<Assoc = u32>),
                                            hir_ref_id: HirId {
                                                owner: DefIndex(41),
                                                local_id: 14,
                                            },
                                        },
                                        span: $DIR/bound-normalization-pass.rs:74:15: 74:31,
                                    },
                                    None,
                                ),
                            ],
                            span: $DIR/bound-normalization-pass.rs:74:12: 74:13,
                            pure_wrt_drop: false,
                            kind: Type {
                                default: None,
                                synthetic: None,
                            },
                        },
                    ],
                    where_clause: WhereClause {
                        predicates: [],
                        span: $DIR/bound-normalization-pass.rs:74:34: 74:34,
                    },
                    span: $DIR/bound-normalization-pass.rs:74:11: 74:32,
                },
                BodyId {
                    hir_id: HirId {
                        owner: DefIndex(41),
                        local_id: 9,
                    },
                },
            ),
            vis: Spanned {
                node: Inherited,
                span: $DIR/bound-normalization-pass.rs:74:5: 74:5,
            },
            span: $DIR/bound-normalization-pass.rs:74:5: 76:6,
        },
        HirId {
            owner: DefIndex(43),
            local_id: 0,
        }: Item {
            ident: #0,
            hir_id: HirId {
                owner: DefIndex(43),
                local_id: 0,
            },
            attrs: [],
            kind: OpaqueTy(
                OpaqueTy {
                    generics: Generics {
                        params: [],
                        where_clause: WhereClause {
                            predicates: [],
                            span: $DIR/bound-normalization-pass.rs:75:16: 75:45,
                        },
                        span: $DIR/bound-normalization-pass.rs:75:16: 75:45,
                    },
                    bounds: [
                        Trait(
                            PolyTraitRef {
                                bound_generic_params: [],
                                trait_ref: TraitRef {
                                    path: path(FooLike<Output = T::Assoc>),
                                    hir_ref_id: HirId {
                                        owner: DefIndex(43),
                                        local_id: 7,
                                    },
                                },
                                span: $DIR/bound-normalization-pass.rs:75:21: 75:45,
                            },
                            None,
                        ),
                    ],
                    impl_trait_fn: Some(
                        DefId(0:41 ~ bound_normalization_pass[317d]::impl_trait_in_bindings[0]::foo[0]),
                    ),
                    origin: Misc,
                },
            ),
            vis: Spanned {
                node: Inherited,
                span: $DIR/bound-normalization-pass.rs:75:16: 75:16,
            },
            span: $DIR/bound-normalization-pass.rs:75:16: 75:45,
        },
        ...
    },
    trait_items: {
        ...
        TraitItemId {
            hir_id: HirId {
                owner: DefIndex(36),
                local_id: 0,
            },
        }: TraitItem {
            ident: Output#0,
            hir_id: HirId {
                owner: DefIndex(36),
                local_id: 0,
            },
            attrs: [],
            generics: Generics {
                params: [],
                where_clause: WhereClause {
                    predicates: [],
                    span: $DIR/bound-normalization-pass.rs:64:32: 64:32,
                },
                span: $DIR/bound-normalization-pass.rs:64:32: 64:32,
            },
            kind: Type(
                [],
                None,
            ),
            span: $DIR/bound-normalization-pass.rs:64:21: 64:33,
        },
        TraitItemId {
            hir_id: HirId {
                owner: DefIndex(40),
                local_id: 0,
            },
        }: TraitItem {
            ident: Assoc#0,
            hir_id: HirId {
                owner: DefIndex(40),
                local_id: 0,
            },
            attrs: [],
            generics: Generics {
                params: [],
                where_clause: WhereClause {
                    predicates: [],
                    span: $DIR/bound-normalization-pass.rs:71:19: 71:19,
                },
                span: $DIR/bound-normalization-pass.rs:71:19: 71:19,
            },
            kind: Type(
                [],
                None,
            ),
            span: $DIR/bound-normalization-pass.rs:71:9: 71:20,
        },
        ...
    },
    impl_items: {
        ...
        ImplItemId {
            hir_id: HirId {
                owner: DefIndex(38),
                local_id: 0,
            },
        }: ImplItem {
            ident: Output#0,
            hir_id: HirId {
                owner: DefIndex(38),
                local_id: 0,
            },
            vis: Spanned {
                node: Inherited,
                span: $DIR/bound-normalization-pass.rs:67:9: 67:9,
            },
            defaultness: Final,
            attrs: [],
            generics: Generics {
                params: [],
                where_clause: WhereClause {
                    predicates: [],
                    span: $DIR/bound-normalization-pass.rs:67:20: 67:20,
                },
                span: $DIR/bound-normalization-pass.rs:67:20: 67:20,
            },
            kind: TyAlias(
                type(u32),
            ),
            span: $DIR/bound-normalization-pass.rs:67:9: 67:27,
        },
        ...
    },
    bodies: {
        BodyId {
            hir_id: HirId {
                owner: DefIndex(41),
                local_id: 9,
            },
        }: Body {
            params: [],
            value: expr(HirId { owner: DefIndex(41), local_id: 9 }: { let _:  = Foo; }),
            generator_kind: None,
        },
    },
    trait_impls: {
        ...
        DefId(0:45 ~ bound_normalization_pass[317d]::opaque_types[0]::Implemented[0]): [
            HirId {
                owner: DefIndex(47),
                local_id: 0,
            },
        ],
        ...
    },
    body_ids: [
        ...
        BodyId {
            hir_id: HirId {
                owner: DefIndex(41),
                local_id: 9,
            },
        },
        ...
    ],
    modules: {
        ...
        HirId {
            owner: DefIndex(32),
            local_id: 0,
        }: ModuleItems {
            items: {
                ...
                HirId {
                    owner: DefIndex(41),
                    local_id: 0,
                },
                HirId {
                    owner: DefIndex(43),
                    local_id: 0,
                },
            },
            trait_items: {
                TraitItemId {
                    hir_id: HirId {
                        owner: DefIndex(36),
                        local_id: 0,
                    },
                },
                TraitItemId {
                    hir_id: HirId {
                        owner: DefIndex(40),
                        local_id: 0,
                    },
                },
            },
            ...
        },
        ...
    },
    proc_macros: [],
}
```
</details>

> error: internal compiler error: src/librustc/ty/context.rs:210: node type T::Assoc (hir_id=HirId { owner: DefIndex(43), local_id: 1 }) with HirId::owner DefId(0:43 ~ bound_normalization_pass[317d]::impl_trait_in_bindings[0]::foo[0]::{{opaque}}[0]) cannot be placed in TypeckTables with local_id_root DefId(0:41 ~ bound_normalization_pass[317d]::impl_trait_in_bindings[0]::foo[0])

All I found is I need understand rust and rustc mode...

**Comment by seiyab** [comment]
I'm still reading rustc code.
I think `OpaqueTy` [becomes owner](https://github.com/rust-lang/rust/blob/8e6de3244cd62cbde367c206bc9972daded5281d/src/librustc_ast_lowering/lib.rs#L1385) in HIR , but the `Visitor` seems not to update TypeckTable.

**Comment by JohnCSimon** [comment]
Ping from triage:
@seiyab Can you post your status on this PR? 
Thank you.

**Comment by seiyab** [comment]
I stuck.

**Comment by seiyab** [comment]
give me more two week.

**Comment by seiyab** [comment]
I changed approach.
#71026

**Pull request closed without merging**
