### PR TITLE
Fix some `#[cfg_attr(not(doc), repr(..))]`

### PR DESCRIPTION
**Pull request by GrigorenkoPV**
Now that #90435 seems to have been resolved.

### CODE REVIEW

**Comment by tgross35** [comment]
The changes lgtm, I'll wait for CI artifacts to be available and take a look at those docs

**Comment by tgross35** [comment]
Could you also update this bit of the docs? https://github.com/rust-lang/rust/blob/92c6c03805408a1a261b98013304e9bbf59ee428/src/doc/rustdoc/src/advanced-features.md?plain=1#L115-L129

**Comment by tgross35** [comment]
Hm - this doesn't look like the docs changes applied. From the artifacts at https://github.com/rust-lang/rust/actions/runs/10031700259/artifacts/1723776160:

image

Vs. stable:

image

@fmease looks like you worked on this, is this supposed to be working now?

**Comment by fmease** [comment]
> Could you also update this bit of the docs?
> 
> https://github.com/rust-lang/rust/blob/92c6c03805408a1a261b98013304e9bbf59ee428/src/doc/rustdoc/src/advanced-features.md?plain=1#L115-L129

I'm not entirely sure why those are in need of updating? I wrote them and they 100% reflect how rustdoc behaves today.

**Comment by fmease** [comment]
> Hm - this doesn't look like the docs changes applied. From the artifacts at https://github.com/rust-lang/rust/actions/runs/10031700259/artifacts/1723776160:
> image
> 
> Vs. stable:
> image
> 
> @fmease looks like you worked on this, is this supposed to be working now?

I don't quite know what the link artifact *represents* because it seems like `std` gets documented with `--document-private-items` in this 'mode' judging by `CStr.inner` being shown in the docs. If that's the case, it's no surprise that `#[repr(transparent)]` gets shown as I made rustdoc always show `#[repr(transparent)]` under `--document-private-items` (which makes sense to me).

**Comment by fmease** [comment]
I'd like link dtolnay's attempt at doing something similar in #116743. However, it's closed because not only did that PR try to simplify `#[repr(transparent)]` attrs but *any* `#[repr]`s — which is still blocked on my PR #116882 (blocked on design questions).

**Comment by fmease** [comment]
> [@]rustbot r? fmease

Libs is not within my purview, only compiler and rustdoc is.
r? tgross35

**Comment by tgross35** [comment]
> I don't quite know what the linked artifact _represents_ because it seems like `std` got documented with `--document-private-items` there judging by `CStr.inner` being shown in the docs (instead of `/* private fields */`).

Oh that makes more sense thanks.

r=me with a screenshot that the non-`--document-private-items` appear as intended. @GrigorenkoPV do you mind posting one?

**Comment by GrigorenkoPV** [comment]
> > I don't quite know what the linked artifact _represents_ because it seems like `std` got documented with `--document-private-items` there judging by `CStr.inner` being shown in the docs (instead of `/* private fields */`).
> 
> Oh that makes more sense thanks.
> 
> r=me with a screenshot that the non-`--document-private-items` appear as intended. @GrigorenkoPV do you mind posting one?

image
image

**Comment by tgross35** [comment]
That looks like what is expected. Thanks for the update!

@bors r+ rollup

**Pull request merged**
