### PR TITLE
Bounce out the layout refactor from beta

### PR DESCRIPTION
**Pull request by arielb1**
@eddyb's #45225 was supposed to get into get into 1.24, but due to an ordering mistake, it had snuck into 1.23.

That wide-effect translation-changing PR had poked LLVM's weak corners and caused many regressions (3 of them have fixes I include here, but also #46897, #46845, #46449, #46371). I don't think it is a good idea to land it in the beta (1.23) because there are bound to be some regressions we didn't patch.

Therefore, I am reverting it in time for stable, along with its related regression fixes.

r? @michaelwoerister (I think)

### CODE REVIEW

**Comment by arielb1** [comment]
I *thought* that @alexcrichton's PR #45905 conflicts with #45225, but it is not based on @eddyb's PR and landed in parallel with it, so it's probably a better idea to leave it in.

**Comment by eddyb** [comment]
r=me

**Comment by arielb1** [comment]
This is a big beta change

@bors r+ p=10

**Comment by michaelwoerister** [comment]
Thanks, folks!

**Pull request merged**
