### PR TITLE
make `Skip` a `DoubleEndedIterator`

### PR DESCRIPTION
**Pull request by oli-obk**
[Playground Example](https://play.rust-lang.org/?gist=66fdb4fe1cf4d8aa2ad4&version=stable)

### CODE REVIEW

**Comment by bluss** [comment]
Implementation lgtm, but is it too surprising that it does all the skip steps when the back element is taken?

**Comment by oli-obk** [comment]
not doing that would require `ExactLengthIterator`

**Comment by alexcrichton** [comment]
This also looks good to me, but this is touching a pretty core iterator so I'm going to tag as `T-libs` just to be sure we discuss it a bit.

**Comment by alexcrichton** [comment]
We discussed this in the libs team meeting and the conclusions we reached were:

* The order of iteration here is probably a little too surprising. Mainly a `Skip` iterator drained via `next_back` would be consumed differently than if the underlying iterator were drained via `next_back`.
* We may be able to implement this, however, via an `ExactSizeIterator` bound.
* There's precedent for double-ended iteration requiring an exact size bound via the `rposition` method.

@oli-obk would you be ok updating this to also include an `ExactSizeIterator` bound? That way the `next_back` method could avoid skipping on the front unless necessary.

**Comment by oli-obk** [comment]
It's always backwards compatible to remove the bound in the future, so adding the bound now is fine with me.

Sadly this makes it useless for iterating over `str` slices by chars

**Comment by oli-obk** [comment]
updated and added more tests

**Comment by alexcrichton** [comment]
@bors: r+ 25e5de3f7ea6f81599b567c3a14e762e4e90cd7a

Thanks @oli-obk!

**Pull request merged**
