### PR TITLE
doc: rewrite doc for signed int::{carrying_add,borrowing_sub}

### PR DESCRIPTION
**Pull request by tspiteri**
Reword the documentation for bigint helper methods, signed `int::{carrying_add,borrowing_sub}` (#85532).

This change is a follow-up to #101889, which was for the unsigned methods.

### CODE REVIEW

**Comment by tspiteri** [comment]
I think the test failure is spurious.

**Comment by ehuss** [comment]
@bors retry

apple timeout on lldb_batchmode.py

**Pull request merged**
