### PR TITLE
[beta] Backport #76571

### PR DESCRIPTION
**Pull request by tesuji**
Waiting for decision from rustdoc team and release team.

cc @jyn514 @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Did it not backport cleanly? Is there a reason you opened a dedicated beta-targeted PR? Usually we roll up beta backports...

**Comment by jyn514** [comment]
> Did it not backport cleanly? Is there a reason you opened a dedicated beta-targeted PR? Usually we roll up beta backports...

Oh ... I thought this was the normal way to backport? Those are the instructions in https://forge.rust-lang.org/release/beta-backporting.html.

**Comment by Mark-Simulacrum** [comment]
Unless I'm misreading something, those are not the directions on that page.

> At that point the PR is ready to be backported. So the list of patches ready for a backport is those tagged both beta-nominated and beta-accepted.

> So now somebody needs to go through those PR's and cherry-pick their commits to the beta branch. 

This is intended to indicate that this PR should contain *all* beta-targeted accepted PRs, of which there are 5 right now: https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3Abeta-nominated++label%3Abeta-accepted. Usually, I make a rollup roughly once a week, with some delay at the start of the cycle.

**Comment by lzutao** [comment]
Yes, it doesn't have merge conflict with beta. Joshua told me to open it.
Closing it then.

**Pull request closed without merging**
