### PR TITLE
[liballoc] Adds checks for UB during allocation.

### PR DESCRIPTION
**Pull request by cgaebel**
They're only enabled in debug builds, but a panic is usually more
welcome than UB in debug builds.

### CODE REVIEW

**Comment by Gankro** [comment]
Should we take this opportunity to do size<=int::MAX as well?

**Comment by cgaebel** [comment]
I guess that'd be a pro-social thing to do.

**Comment by alexcrichton** [comment]
Due to the way we ship `liballoc`, will this be beneficial to have? Right now we don't actually compile out debug assertions in our shipped artifacts, so this may just end up slowing code down unexpectedly. If we did ship a version with the debug assertions compiled out, this would only help `libstd` (during the auto builds), not external users.

**Comment by huonw** [comment]
I think this is beneficial, and we will probably want to have some way for external users to opt-in to the debug assertions in the stdlib anyway. It may be better to wait until we default to removing debug assertions, but personally I'm happy adding this now.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Comment by Gankro** [comment]
:S whoops, I missed @huonw's last comment there. Didn't realized I was in charge of this.

Sorry @cgaebel! This relates, I think, to what exactly we want debug_asserts to be doing in the std libs.

**Pull request closed without merging**
