### PR TITLE
fix(lexer): use `is_asscii_whitespace` to find first not space pos

### LINKED ISSUE #108275: string continue non-ASCII whitespace confusing as `\x0C` is ASCII whitespace
### Code

```Rust
fn main() {
    assert!('\x0c'.is_ascii_whitespace());
    println!("Hello,\
         world!");
}
```

### Current output

```Shell
warning: non-ASCII whitespace symbol '\u{c}' is not skipped
 --> src/main.rs:3:21
  |
3 |       println!("Hello,\
  |  _____________________^
4 | |
               world!");
  | |      ^- non-ASCII whitespace symbol '\u{c}' is not skipped
  | |______|
  |
```

### Desired output

```Shell
warning: non-ASCII whitespace symbol '\u{c}' is not skipped
 --> src/main.rs:3:21
  |
3 |       println!("Hello,\
  |  _____________________^
4 | |
               world!");
  | |      ^- '\u{c}' is not skipped, only `\n`, `\r`, `\t` and ` ` are skipped
  | |______|
  |
```

### Rationale and extra context

According to `char::is_ascii_whitespace`, `\x0c` is ASCII whitespace.

### Other cases

_No response_

### Anything else?

Not sure if this is actually an issue, just an inconsistency I found.

### PR DESCRIPTION
**Pull request by bvanjoi**
close https://github.com/rust-lang/rust/issues/108275

### CODE REVIEW

**Review by WaffleLapkin — COMMENTED** [review]
I think https://github.com/rust-lang/rust/issues/108275 is about the _diagnostic output_ and not the fact that not all ascii whitespace characters are skipped. Are we sure we want to skip more characters?

**Comment by bvanjoi** [comment]
> I think #108275 is about the _diagnostic output_ and not the fact that not all ascii whitespace characters are skipped. Are we sure we want to skip more characters?

Maybe the `\0xc` character should be skipped, at least from the naming of the function [skip_ascii_whitespace]((https://github.com/rust-lang/rust/blob/master/compiler/rustc_lexer/src/unescape.rs#L285)), the change is as expected.

**Comment by eholk** [comment]
This change looks reasonable to me, but I'd love to get someone from @rust-lang/lang to weigh in. It's not clear whether we've implemented the behavior we want and described it imprecisely, or described the behavior we want but implemented it incorrectly. I'd lean towards the latter (and that's the position this PR takes), but I don't feel qualified to declare that on my own.

**Comment by bvanjoi** [comment]
Seeing that it is the code implemented in #60261, perhaps we can ask @matklad or @petrochenkov to give some advice

**Comment by matklad** [comment]
My gut feeling is that only the error message is wrong here. `|b| b != b' ' && b != b'\t' && b != b'\n' && b != b'\r'` **is** the definition of "whitespace in strings", this is documented in the reference (https://doc.rust-lang.org/reference/tokens.html#string-literals).

It _might_ be argued that the language definition is wrong here, and that we should adjust that. It indeed feels wrong that we use different definitions of whitespace when lexing tokens and when processing innards of a string. But, given that changing this would be a backwards incompatible change, I am 0.7 sure that the outcome here would be "this is a documented peculiarity".

**Comment by matklad** [comment]
> This change looks reasonable to me
> or described the behavior we want but implemented it incorrectly.

FWIW, the high order bit here is that this changes the visible semantics of the language. At this point in Rust's lifetime, "changes behavior" should take precedence over "reasonableness".

**Comment by bvanjoi** [comment]
Very great explanation, I will give a PR with only the error message modified in the near future

**Comment by WaffleLapkin** [comment]
Closing, since the consensus seems to be that we only need to change the diagnostic.

**Pull request closed without merging**
