### PR TITLE
adaptation to rustbuild for openbsd

### PR DESCRIPTION
**Pull request by semarie**
Since the switch to rustbuild, the build for openbsd is broken:
  - [X] `ar` inference based on compiler name is wrong (OpenBSD usually use `egcc`, but `ear` doesn't exist)
  - [X] `make` isn't GNU-make under OpenBSD (and others BSD platforms)
  - [x] `stdc++` isn't the right stdc++ library to link with (it should be `estdc++`)
  - [x] corrects tests that don't pass anymore (problems related to rustbuild)

r? @alexcrichton

### CODE REVIEW

**Comment by semarie** [comment]
The `make` commit will close #38429.

The implementation statically bound "gmake" to BSD and let "make" to others. Eventually, I could add the use of a variable `MAKE` to override the behaviour ?

**Comment by semarie** [comment]
I think I will keep some tests failing with vanilla configuration: the fact that `egcc` compiler isn't used (but `cc`) for some tests, make them to fail: `cc` (GCC 4.2) is unable to link properly `estdc++` library when the test needs it.

A simple workaround is to have a directory in front of `PATH` with a symbolic link `cc` to `egcc`.

**Comment by alexcrichton** [comment]
Looks good to me, thanks! When this is ready just lemme know and I'll r+

**Comment by semarie** [comment]
I have a failing test (check-std-all) that seems related to `build_helper` and cargo features. I am unsure if it is related to my commits or not.

```
executing step Step { name: "check-std-all", stage: 2, host: "x86_64-unknown-openbsd", target: "x86_64-unknown-openbsd" }
Testing libstd stage2 (x86_64-unknown-openbsd -> x86_64-unknown-openbsd)
running: "/data/semarie/obj/rust-installs/beta/bin/cargo" "test" "-j" "4" "--target" "x86_64-unknown-openbsd" "-v" "--release" "--frozen" "--manifest-path" "/data/semarie/src/rust/src/rustc/std_shim/Cargo.toml" "--features" "panic-unwind jemalloc backtrace" "-p" "std_shim" "-p" "std" "-p" "rand" "-p" "libc" "-p" "compiler_builtins" "-p"
"alloc" "-p" "collections" "-p" "unwind" "-p" "std_unicode" "-p" "panic_abort" "-p" "build_helper" "-p" "alloc_system" "-p" "core" "--"
error: Package `build_helper v0.1.0 (file:///data/semarie/src/rust/src/build_helper)` does not have these features: `backtrace, panic-unwind, jemalloc`


command did not execute successfully: "/data/semarie/obj/rust-installs/beta/bin/cargo" "test" "-j" "4" "--target" "x86_64-unknown-openbsd" "-v" "--release" "--frozen" "--manifest-path" "/data/semarie/src/rust/src/rustc/std_shim/Cargo.toml" "--features" "panic-unwind jemalloc backtrace" "-p" "std_shim" "-p" "std" "-p" "rand" "-p" "libc" "-p" "compiler_builtins" "-p" "alloc" "-p" "collections" "-p" "unwind" "-p" "std_unicode" "-p" "panic_abort" "-p"
"build_helper" "-p" "alloc_system" "-p" "core" "--"
expected success, got: exit code: 101
```

**Comment by semarie** [comment]
hum. it could be my cargo binary that is too old. It is a 0.14.0.

**Comment by semarie** [comment]
@alexcrichton it is ok now. My cargo was too old for correctly performing tests without errors.

As side note, I found it is more and more complex to build rustc now. I hope to not having to port a new platform (full cross-compiling isn't always possible) due to interdependance of rustc and cargo (and libc which needs cargo too to properly check it).

**Comment by alexcrichton** [comment]
@semarie I'm not sure I understand the sentiment that building is more complex now? The only difference is that building the compiler requires Cargo now as opposed to just a previous rustc. Otherwise the build system should take care of everything.

**Comment by alexcrichton** [comment]
@bors: r+

In any case, changes look good to me!

**Comment by semarie** [comment]
If you already have "correct libc" + "rustc" + "cargo", there are no problem with the build system. But porting a new platform to Rust will require additionnal effort due to the interdependance of these three components.

**Comment by brson** [comment]
Nominated per https://internals.rust-lang.org/t/rust-1-15-release-status/4590/11

**Pull request merged**
