### PR TITLE
[T]::rejoin (experimental API implementation)

### PR DESCRIPTION
**Pull request by golddranks**
Implements the APIs described here: https://github.com/rust-lang/rfcs/pull/2806 behind a feature flag `rejoin_slice`.

### CODE REVIEW

**Comment by golddranks** [comment]
This cannot be merged as-is as it was deemed to be unsafe. However, it might be useful to have an unsafe version in standard library. It would be good from the perspective of communicating what is UB and what is not, and why, too.

**Comment by RalfJung** [comment]
(I am going to respond in the RFC, let us centralize the discussion there: https://github.com/rust-lang/rfcs/pull/2806)

**Comment by Centril** [comment]
Closing the PR for now then.

**Pull request closed without merging**
