### PR TITLE
make Send/Sync impl of RawTable manual

### LINKED ISSUE #21763: HashMap<K,V> is always Send/Sync
```rust
trait Foo: Send {}
impl Foo for HashMap<Rc<()>, Rc<()>> {}
```
This compiles, despite Rc<T> : !Send. I'm guessing this is because RawTable only uses K and V with marker::CovariantType, and I guess that isn't enough for the negative-impl to propagate. I haven't checked which other collections might be unsafe.

### PR DESCRIPTION
**Pull request by Gankra**
Fixes #21763 

(untested)

### CODE REVIEW

**Comment by alexcrichton** [comment]
r=me with a new `compile-fail` regression test

**Comment by Gankro** [comment]
@alexcrichton Test added but I'm new to compile-fail so I'm not sure if this is exactly the desired format or what.

**Comment by alexcrichton** [comment]
@bors: r+ 343143d

Looks good to me, thanks!

**Comment by Manishearth** [comment]
Needs rebase

**Comment by Gankro** [comment]
@bors retry

Seems like a spurious OOM?

**Pull request merged**
