### PR TITLE
Allow Trait inheritance with cycles on associated types take 2

### PR DESCRIPTION
**Pull request by spastorino**
This reverts the revert of #79209 and fixes the ICEs that's occasioned by that PR exposing some problems that are addressed in #80648 and #79811.
For easier review I'd say, check only the last commit, the first one is just a revert of the revert of #79209 which was already approved.

This also could be considered part or the actual fix of #79560 but I guess for that to be closed and fixed completely we would need to land #80648 and #79811 too.

r? @nikomatsakis 
cc @Aaron1011

### CODE REVIEW

**Comment by jyn514** [comment]
@bors try

So people can easily install this with https://github.com/kennytm/rustup-toolchain-install-master.

**Comment by spastorino** [comment]
@jyn514 yeah that's great. I've force pushed but all I've changed there is the test I've added to be `check-pass` instead of `build-pass`, so don't worry about that.

**Comment by spastorino** [comment]
Now that [this is tested](https://github.com/rust-lang/rust/issues/79560#issuecomment-755162524), should be ready for review/merge.

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
Just to make sure I understand the situation:

* changing from `Ident` to `Symbol` basically works around the hygiene problems we encountered
* but once #79811 lands, we wouldn't have had those problems in the first place?

Is there a test for the new ICEs we encountered? I couldn't quite tell. If so, r=me.

@bors delegate+

**Comment by spastorino** [comment]
@nikomatsakis what you've said is correct. About the test check the second commit (the one that's not the revert) and at the end you'll find the test.

**Comment by lnicola** [comment]
@jyn514 what commit should I use with `rustup-toolchain-install-master`? Neither 03c0e58d18d39a8210f559d280998d06d8f160bc nor 455a0e1d91d3f56c4752a9f035e3622c614b7240 work.

**Comment by m-ou-se** [comment]
@lnicola That only works for commits that have been built by bors. Try the commits mentioned in https://github.com/rust-lang/rust/pull/80732#issuecomment-754879775.

**Comment by lnicola** [comment]
@spastorino this introduces an error while compiling `salsa`:

```
error[E0221]: ambiguous associated type `Group` in bounds of `Q`
   --> src/interned.rs:466:57
    |
466 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<Q::Group>>::group_storage(db);
    |                                                         ^^^^^^^^ ambiguous associated type `Group`
    | 
   ::: src/lib.rs:431:5
    |
431 |     type Group: plumbing::QueryGroup<GroupStorage = Self::GroupStorage>;
    |     --------------------------------------------------------------------
    |     |
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |
help: use fully qualified syntax to disambiguate
    |
466 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: use fully qualified syntax to disambiguate
    |
466 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0221]: ambiguous associated type `Group` in bounds of `Q`
   --> src/interned.rs:478:57
    |
478 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<Q::Group>>::group_storage(db);
    |                                                         ^^^^^^^^ ambiguous associated type `Group`
    | 
   ::: src/lib.rs:431:5
    |
431 |     type Group: plumbing::QueryGroup<GroupStorage = Self::GroupStorage>;
    |     --------------------------------------------------------------------
    |     |
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |
help: use fully qualified syntax to disambiguate
    |
478 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: use fully qualified syntax to disambiguate
    |
478 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0221]: ambiguous associated type `Group` in bounds of `Q`
   --> src/interned.rs:490:57
    |
490 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<Q::Group>>::group_storage(db);
    |                                                         ^^^^^^^^ ambiguous associated type `Group`
    | 
   ::: src/lib.rs:431:5
    |
431 |     type Group: plumbing::QueryGroup<GroupStorage = Self::GroupStorage>;
    |     --------------------------------------------------------------------
    |     |
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |
help: use fully qualified syntax to disambiguate
    |
490 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: use fully qualified syntax to disambiguate
    |
490 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0221]: ambiguous associated type `Group` in bounds of `Q`
   --> src/interned.rs:512:57
    |
512 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<Q::Group>>::group_storage(db);
    |                                                         ^^^^^^^^ ambiguous associated type `Group`
    | 
   ::: src/lib.rs:431:5
    |
431 |     type Group: plumbing::QueryGroup<GroupStorage = Self::GroupStorage>;
    |     --------------------------------------------------------------------
    |     |
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |     ambiguous `Group` from `for<'d> QueryDb<'d>`
    |
help: use fully qualified syntax to disambiguate
    |
512 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: use fully qualified syntax to disambiguate
    |
512 |             <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0221`.
error: could not compile `salsa`
```

Do you know if that is intended?

**Comment by m-ou-se** [comment]
@bors r-

That failed in this rollup: https://github.com/rust-lang/rust/pull/81102#issuecomment-761720245

(Thanks @lnicola for figuring it out!)

**Comment by lnicola** [comment]
Well, I suppose it could still be a `salsa` bug.

**Comment by m-ou-se** [comment]
> Well, I suppose it could still be a `salsa` bug.

Maybe. But we should confirm that first before merging this.

**Comment by Aaron1011** [comment]
@spastorino: https://github.com/rust-lang/rust/pull/79811 has been merged, so you can switch back to using `Ident`.

**Comment by spastorino** [comment]
Have just changed back to `Ident` given that @Aaron1011 has fixed the original underlying issue.

@lnicola can you tell me how to reproduce the `salsa` issue? or better said, do you have an MCVE for it?.

**Comment by lnicola** [comment]
@spastorino try this:

```rust
pub struct LookupInternedStorage;

impl<Q> QueryStorageOps<Q> for LookupInternedStorage
where
    Q: Query,
    for<'d> Q: QueryDb<'d>,
{
    fn fmt_index(&self, db: &<Q as QueryDb<'_>>::DynDb) {
        <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<Q::Group>>::group_storage(db);
    }
}

pub trait QueryGroup {
}

pub trait HasQueryGroup<G>
{
    fn group_storage(&self) -> &'static ();
}

pub trait QueryStorageOps<Q>
where
    Q: Query,
{
    fn fmt_index(&self, db: &<Q as QueryDb<'_>>::DynDb);
}

pub trait QueryDb<'d> {
    type DynDb: HasQueryGroup<Self::Group> + 'd;
    type Group;
    type GroupStorage;
}

pub trait Query: for<'d> QueryDb<'d> {
}
```

```
$ cargo +c963187c6f959417cbb13a33e9eaea4607696fc4 build
   Compiling salsa-min v0.1.0 (/home/grayshade/salsa-min)
error[E0221]: ambiguous associated type `Group` in bounds of `Q`
  --> src/main.rs:9:53
   |
9  |         <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<Q::Group>>::group_storage(db);
   |                                                     ^^^^^^^^ ambiguous associated type `Group`
...
30 |     type Group;
   |     -----------
   |     |
   |     ambiguous `Group` from `for<'d> QueryDb<'d>`
   |     ambiguous `Group` from `for<'d> QueryDb<'d>`
   |
help: use fully qualified syntax to disambiguate
   |
9  |         <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
   |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: use fully qualified syntax to disambiguate
   |
9  |         <<Q as QueryDb<'_>>::DynDb as HasQueryGroup<<Q as for<'d> QueryDb<'d>>::Group>>::group_storage(db);
   |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0221`.
error: could not compile `salsa-min`

To learn more, run the command again with --verbose.

$ cargo +stable check
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
```

**Comment by pthariensflame** [comment]
Does this need `relnotes`?

**Comment by nikomatsakis** [comment]
I don't think it really needs relnotes, it's basically a minor bugfix that probably doesn't rise to that level.

**Pull request merged**
