### PR TITLE
Delete `tests/crashes/23707.rs` because it's flaky

### PR DESCRIPTION
**Pull request by jieyouxu**
It's conditioned on `only-x86_64` because it doesn't reliably fail on other platforms, it's optimization dependent and failed to ICE post-PGO in
<https://github.com/rust-lang/rust/pull/132300#issuecomment-2443279042>. Remove this test for now without prejudice against relanding the test in a more reliable form.

I removed the `S-bug-has-test` label from #23707.

r? compiler

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
otoh, maybe we can change the recursion limit to make it fail more reliable?

**Comment by jieyouxu** [comment]
> otoh, maybe we can change the recursion limit to make it fail more reliable?

I don't want to investigate tuning this test atm, follow-ups welcomed!

**Comment by workingjubilee** [comment]
while that can hypothetically be done, it presumes LLVM cannot find, and that the code does not change to enable, an optimization that allows rustc to push through even millions of iterations before reaching the error.

**Comment by workingjubilee** [comment]
in general, resource-exhaustion-related tests are inappropriate for crashtests, because they are intrinsically optimization-dependent.

it may be best to simply add a regression test for a lower level of recursion that the compiler can clear, declare victory, and move on.

**Pull request merged**
