### PR TITLE
Replace impl Fn with fn in sort::merge_sort::RunVec

### PR DESCRIPTION
**Pull request by GnomedDev**
This cleans up the code while outlining `RunVec`'s methods as they are no longer generic. This leads to an increase in binary size for crates which only use merge_sort a couple times ([t2fanrd](https://github.com/GnomedDev/t2fanrd) has 5 merge_sort copies and grows in binary size from `606872` to `607256`) but for projects with a large number of merge_sort copies it really pays off ([TTS Bot](https://github.com/Discord-TTS/Bot) has 41 copies, binary size goes from `20,486,640` to `20,432,408`).

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I think my preferred approach would be to make RunVec generic over [`GlobalAlloc`](https://doc.rust-lang.org/nightly/core/alloc/trait.GlobalAlloc.html) or `Allocator`, and pass a Layout into it as the way to avoid monomorphizations, rather than passing around allocator-like stubs (without `unsafe` too!).

That would move us closer to a future where this could hopefully "just" be a `Vec<T, A>` where the A is passed up to the caller to select.

**Comment by GnomedDev** [comment]
I think that's good for a separate PR, but for now I just want to land these improvements from this small clean up. That allows performance to be measured between this PR and your idea, as well as having this improvement usable earlier.

**Comment by GnomedDev** [comment]
The actual improvements here are coming from RunVec, which previously was generic over the allocation/deallocation functions and now is not. Since the `sort::merge_sort` function is still generic over the comparator it is inlined the same as previously, meaning there is no `dyn` overhead of passing function pointers other than into RunVec.

This binary size trade off seems worth it to me, as it's only introducing the `dyn` overhead when allocating or deallocating (an already slow operation), and since it's using `fn` I expect it to be optimised well (although I have not looked at the machine code as I'm not skilled enough to get meaningful results out of that).

I understand that the title of the PR is misleading, so I'll rename it now.

**Comment by GnomedDev** [comment]
Just realized I didn't do this!
@rustbot ready

**Comment by joboet** [comment]
Since #124032 would make this PR redundant, I'll wait until T-libs decides on the fate of that PR before reviewing this.

**Comment by GnomedDev** [comment]
Relevant code has been removed/rewritten, no point in this PR anymore.

**Pull request closed without merging**
