### PR TITLE
Miri tests: use xargo to build separate libstd

### LINKED ISSUE #61833: Get rid of the `test-miri` flag in `config.toml`
The `test-miri` flag changes whether `-Zalways-encode-mir` is passed to rustc, causing all metadata beyond stage 0 to include MIR of all functions, even private monomorphic ones. Instead, what we can do is to have miri tests first run `cargo miri setup` to generate that special `libstd` in CI in addition to the regular `libstd`. Then tests can be run with special `libstd`.

cc @RalfJung

### LINKED ISSUE #63219: `miri` no longer builds after rust-lang/rust#63214
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#63214, I observed that the tool miri no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @Centril, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @Centril, the PR reviewer, and @rust-lang/compiler -- nominating for prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
This uses `cargo miri setup` to prepare the libstd that is used for testing Miri, instead of adjusting the entire bootstrap process to make sure the libstd that already gets built is fit for Miri.

The issue with our current approach is that with `test-miri = true`, libstd and the test suite get built with `--cfg miri`, which e.g. means hashbrown uses no SIMD, and not all things are tested. Such global side-effects seem like footguns waiting to go off.

On the other hand, the new approach means we install xargo as a side-effect of doing `./x.py test src/tools/miri`, which might be surprising, and we also both have to build xargo and another libstd which costs some extra time. Not sure if the tools builders have enough time budget for that. Maybe there is a way to cache xargo?

We have to first first land https://github.com/rust-lang/miri/pull/870 in Miri and then update this PR to include that change (also to get CI to test Miri before bors), but I wanted to get the review started here.

Cc @oli-obk (for Miri) @alexcrichton (for CI) @Mark-Simulacrum (for bootstrap)

Fixes https://github.com/rust-lang/rust/issues/61833, fixes https://github.com/rust-lang/rust/issues/63219

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems fine to me, especially as it looks to be consolidating miri testing related logic which is good! I think it'd be good to get a green light from Azure as well, but once the miri update is included that should auto-test here anyway.

**Comment by RalfJung** [comment]
```
2019-08-01T21:11:19.2894564Z      Running `build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo-miri miri setup`
2019-08-01T21:11:19.2926132Z thread 'main' panicked at 'Failed to run rustc to get sysroot info: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
```
Wait, why did this code now run in the `x86_64-gnu-llvm-6.0` runner?

**Review by Mark-Simulacrum — APPROVED** [review]
Changes look good to me as well (r=me, presuming no one else needs to review this); I have not looked at miri-internal changes and such.

**Comment by RalfJung** [comment]
@Mark-Simulacrum any idea why the `x86_64-gnu-llvm-6.0` builder tries to run `cargo miri setup`? I added this only to the "test" steps.

The tools builder also fails, I am investigating that.

**Comment by Mark-Simulacrum** [comment]
That builder runs tests? `python2.7 ../x.py test src/tools/tidy && python2.7 ../x.py test` is the invocation on that builder. So this seems expected.

**Comment by RalfJung** [comment]
But I thought the tools tests should only be run on the tools builder?

**Comment by Mark-Simulacrum** [comment]
I've spent a bit of time trying to investigate, and something feels off to me. [This auto branch build](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4954/logs/984) does not build miri on the x86_64-gnu-llvm-6.0 builder. Neither does [this recent PR build](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4793/logs/49); the failure in this PR though clearly shows miri being [built](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4957/logs/49).

AFAICT, this is because Miri is labeled as "default" = true, unlike all the other tools (Clippy, etc.) This usually didn't matter because we had test_miri as a condition, but since that has gone away, this PR needs to change miri to no longer be enabled by default, by removing or flipping the value of `const DEFAULT` on the `test::Miri` step.

**Comment by RalfJung** [comment]
@Mark-Simulacrum nice catch, thanks!

**Comment by RalfJung** [comment]
Testing only on the tools job seems to work, at least. ;)

Building Miri fails because master is currently broken with Miri.

**Comment by alexcrichton** [comment]
Or well,

@bors: r- delegate+

r=me when this is ready

**Comment by RalfJung** [comment]
Looks like it installed xargo but it's not in the path so it cannot start it.

**Comment by RalfJung** [comment]
@Mark-Simulacrum  for now I hard-coded the xargo path but that won't work on the Windows runner. Do you know how, inside bootstrap, I can determine the path that cargo will install stuff to? It's `/cargo/bin/` on Linux, it seems.

**Comment by Mark-Simulacrum** [comment]
You can set `CARGO_INSTALL_ROOT` in the environment to a directory inside `build` perhaps? that might be easiest. There's some more docs on `cargo install --help` about how to find here the binaries are installed I think

**Comment by RalfJung** [comment]
@Mark-Simulacrum ah, that sounds good.

I am now testing something like
```rust
            let cargo_bin = builder.out.join("bin");
            cargo.env("CARGO_INSTALL_ROOT", &cargo_bin);
            cargo.env("XARGO", cargo_bin.join("xargo"));
```
That should mean it puts this into `build/bin`. Seems reasonable?

I was also considering setting `CARGO_INSTALL_ROOT` in `bootstrap.py` in case other tools also need a `cargo install`, and then it could maybe even extend the `PATH`... but that would affect everything so I am not sure if it is the right thing to do.

**Comment by Mark-Simulacrum** [comment]
Let's keep it to just this invocation for the time being.

**Comment by RalfJung** [comment]
Oh dang, now it fails because when xargo invokes cargo, it doesn't find it in the path.

I think it will be easier to actually have cargo in the path for this invocation than to try and patch xargo to overwrite which cargo it uses.

**Comment by RalfJung** [comment]
That worked, finally. :)
Need to get a new xargo released before we can land this, though.

The "Run build" step took [2h 40min](https://dev.azure.com/rust-lang/rust/_build/results?buildId=5123&view=logs). Is that an increase compared to before? I am not sure what our usual noise here is. It is a bit hard to compare because you'd have to find one where all the same tools are building successfully and have their test suites run.

**Comment by alexcrichton** [comment]
@bors: r+

2h40m looks to be [just about the right amount of time](https://alexcrichton.github.io/rust-ci-timing-tracker/#series=x86_64-gnu-tools,mingw-check), so looks good to me!

**Comment by RalfJung** [comment]
@bors r-

Still waiting for a xargo release so that we can stop installing it from git.

**Comment by RalfJung** [comment]
Marking as blocked on a xargo release.

Cc @jethrogb

**Pull request merged**
