### PR TITLE
Remove unnecessary `Symbol` stringification in clippy

### PR DESCRIPTION
**Pull request by camelid**
This should (slightly) improve performance and enhance code quality.

### CODE REVIEW

**Comment by camelid** [comment]
Hmm, it seems like the rustc version is actually hard to get rid of. It also seems to only be used in an error path. So I removed that change.

**Comment by camelid** [comment]
r? rust-lang/clippy

**Comment by matthiaskrgr** [comment]
Hm, afaik the rust benchmarking does not touch clippy at all.. :thinking:

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Yeah clippy isn't perf tested. Are you sure you want to land this PR here? It'll land faster on the clippy repo. We could also rollup, of course

**Review by flip1995 — APPROVED** [review]
I'm good with landing it here or in Clippy. Since this is a NFC it doesn't have to go through the Clippy repo and the sync process.

But there's still an error:

```
error[E0425]: cannot find value `Underscore` in module `sym`
   --> src/tools/clippy/clippy_lints/src/matches.rs:964:52
    |
964 |                     let mut ident_bind_name = sym::Underscore;
    |                                                    ^^^^^^^^^^ not found in `sym`
    |
help: consider importing one of these items
    |
1   | use crate::matches::hir::LifetimeName::Underscore;
    |
1   | use rustc_ast::ExprKind::Underscore;
    |
1   | use rustc_hir::LifetimeName::Underscore;
    |
1   | use rustc_span::symbol::kw::Underscore;
    |
```

**Comment by camelid** [comment]
What does NFC mean btw?

Also: It seemed to work in rust-analyzer _sigh_

I'll close this and reopen against the clippy repo (this PR originally changed rustc too, which is why I filed it here).

**Comment by camsteffen** [comment]
NFC = non-functional change. I think you need `kw::Underscore`.

**Comment by camelid** [comment]
Ok, I've opened rust-lang/rust-clippy#8310. Closing this PR then!

**Pull request closed without merging**
