### PR TITLE
Make tidy check for magic numbers that spell things

### PR DESCRIPTION
**Pull request by joshtriplett**
Remove existing problematic cases.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by delbonis** [comment]
Wait why is this "problematic"?

**Comment by noonien** [comment]
What about 0xDeadBeef?

This is also problematic, because, as a vegan, it's triggering with images of dead animals.

**Comment by camsteffen** [comment]
Have some grace for the maintainers who will get beef (pun intended) no matter what they do. They have to draw a line somewhere for this stuff. It's just a few hex codes. It's okay.

**Comment by owwk** [comment]
"It's just a few hex codes" is exactly why it's not okay. 

Every time it's "just a few this" this or "just a little that". 500x of of "just remove this little thing" later and suddenly half of computer science terms are considered "problematic" and you've let a small group of misguided authoritarians create a political climate where you're not allowed to write certain integers in your code anymore.

Nobody was offended by this. All of this BS is pushed by spineless white men being offended on behalf of other people. Creating imaginary offense in their fragile minds despite none actually existing.

**Comment by Rydgel** [comment]
Imagine being triggered by a number.

**Comment by cuviper** [comment]
For posterity, please note that "tidy" only applies to rust-lang/rust itself, not all Rust code.

**Pull request merged**
