### PR TITLE
Improve "Doesn't live long enough" error

### PR DESCRIPTION
**Pull request by mikhail-m1**
case with temporary variable

issue #36279 part of #35233

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Hmm, this doesn't look quite right.  It looks like we're getting rid of the temporary value message altogether.  Instead, I think we want to use the same style of fixed we used before.

For example, instead of this:

```
error: borrowed value does not live long enough
  --> <anon>:11:17
   |
11 |     for line in std::io::stdin().lock().lines().map(|l| l.unwrap()) {
   |                 ^^^^^^^^^^^^^^^^ temporary value created here
...
18 |     }
   |     - temporary value dropped before borrower
   |
   = note: values in a scope are dropped in the opposite order they are created
```

Have this:

```
error: borrowed value does not live long enough
  --> <anon>:11:17
   |
11 |     for line in std::io::stdin().lock().lines().map(|l| l.unwrap()) {
   |                 ---------------- temporary value created here
...
18 |     }
   |     ^ temporary value dropped before borrower
   |
   = note: values in a scope are dropped in the opposite order they are created
```

**Comment by jonathandturner** [comment]
Though I noticed that sometimes we don't put the error on the last one.  Like this example:

```
error: `r` does not live long enough
  --> <anon>:21:9
   |
18 |     r.listen(Box::new(|| {
   |                       -- capture occurs here
...
21 |         r.something();
   |         ^ does not live long enough
22 |     }));
23 | }
   | - borrowed value dropped before borrower
```

Still, I think with the temporary value, the fix I'm showing reads okay

**Comment by mikhail-m1** [comment]
@jonathandturner I did not noticed the loss of  'temporary' in error. It's easy to fix. But I reread #36279, is it about split temporary and local variables? And was it already completed?
I could rework case with closure, just give me required output.

**Comment by jonathandturner** [comment]
@mikhail-m1 - I think that's an older error before we made the message wording better for temporaries.

I think the only step left for temporaries is to switch which is primary and which is secondary.

**Comment by alexcrichton** [comment]
@jonathandturner does the most recent iteration look good to you?

**Pull request merged**
