### PR TITLE
Update books for next release

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is going to fail, the book's CI is currently failing.  I'm pushing a fix right now.

**Comment by steveklabnik** [comment]
Could you pull from the book again?

r=me when that's done and travis is happy

**Comment by Mark-Simulacrum** [comment]
Pulled, will wait for Travis.

**Comment by Mark-Simulacrum** [comment]
Hm, looks like the nomicon is also broken. I'm working on a fix.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang-nursery/reference/pull/359 and https://github.com/rust-lang-nursery/nomicon/pull/73 need to be merged before this can land.

**Comment by steveklabnik** [comment]
@Mark-Simulacrum both merged now!

**Pull request merged**
