### PR TITLE
Update linker-plugin-lto.md to contain up to rust 1.46

### PR DESCRIPTION
**Pull request by elichai**
Hi,
this is the same as https://github.com/rust-lang/rust/pull/72290, if anyone has suggestions on how to automate this please say :)
otherwise, you can check the versions I've added via:

```sh
$ rustup install 1.44.0
$ rustc +1.44.0 -Vv
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-unknown-linux-gnu
release: 1.44.0
LLVM version: 9.0

$ rustup install 1.45.0
$ rustc +1.45.0 -Vv
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-unknown-linux-gnu
release: 1.45.0
LLVM version: 10.0

$ rustup install 1.46.0
$ rustc +stable -Vv
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0
```

### CODE REVIEW

**Review by wesleywiser — COMMENTED** [review]
It looks like every Rust version is only ever compatible with one Clang version, so perhaps we should change the table from an m*n matrix to a simple list of compatible versions?

**Comment by elichai** [comment]
> It looks like every Rust version is only ever compatible with one Clang version, so perhaps we should change the table from an m*n matrix to a simple list of compatible versions?

Agreed, I just thought about the fact that soon(current nightly) it will require Clang 11, so I'll replace this with something like this:
 
|  Rust version         |  Clang Version  | 
|--------------------------|----------------------|
| Rust 1.34              |       Clang 7       | 
| Rust 1.35              |       Clang 8       |
| Rust 1.36              |       Clang 9       |

**Comment by jyn514** [comment]
> if anyone has suggestions on how to automate this please say

@elichai You can automate the checking, not sure about editing the docs.
```bash
rustup toolchain install --profile minimal nightly
MINOR_VERSION=$(rustc +nightly --version | cut -d . -f 2)
LOWER_BOUND=44

llvm_version() {
    toolchain="$1"
    printf "Rust $toolchain    |    Clang "
    rustc +"$toolchain" -Vv | grep LLVM | cut -d ':' -f 2 | tr -d ' '
}

for version in `seq $LOWER_BOUND $((MINOR_VERSION - 2))`; do
    toolchain=1.$version.0
    rustup toolchain install --no-self-update --profile  minimal $toolchain >/dev/null 2>&1
    llvm_version $toolchain
done

for toolchain in beta nightly; do
    rustup toolchain install --no-self-update --profile minimal $toolchain >/dev/null 2>&1
    llvm_version $toolchain
done
```

**Pull request merged**
