### PR TITLE
Some cleanups around diagnostic levels.

### PR DESCRIPTION
**Pull request by nnethercote**
Plus some refactoring in and around diagnostic levels and emission. Details in the individual commit logs.

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
I find "weak bug" to still be quite confusing as a name. This is after all called in places where there is no bug - just some expensive computation that we should only do when the user actually sees the result.

I would suggest a name that involves "require diagnostic" or "assert diagnostic" or so. That more directly expresses what is actually being checked.

**Comment by nnethercote** [comment]
I used "weak" because it's a weaker form of `DelayedBug`, because it doesn't provide an `ErrorGuarantee`. And `DelayedBug` seems like well-established terminology, so I didn't want to go with anything that required changing the names of both levels.

Also, I *really* want to eliminate `WeakDelayedBug`, because it kinda sucks, and only has two uses.

**Comment by RalfJung** [comment]
Yeah I saw that argument in your commit message. I don't agree though, this does not at all feel like a "weak version of `delay_bug`". `delay_bug` is used in cases where one would like to use `bug!`, but one cannot since rustc continues running for a while on invalid programs, and later phases of the compiler sometimes need to deal with clearly invalid state and want to make sure this never happens in a session where we emit any artifacts.

"good_path_bug" is nothing at all like that, so making the name similar is misleading IMO.

**Comment by nnethercote** [comment]
I interpret the `bug` in both `delayed_bug` and `weak_delayed_bug` as meaning "causes an ICE (bug) if it triggers", and the `delayed` as "triggers only at the end of execution, if at all". So to me they are very similar, the difference being the condition that must be met to avoid the trigger, and the `EmissionGuarantee` you get as a result.

**Comment by RalfJung** [comment]
For `delay_span_bug`, it makes sense to think of this as "if this line is ever reached, there was a bug" (with an asterisk about rustc continuing compilation for a bit even on blatantly invalid programs).

For good-path-bug, I don't think it makes sense to think of this as "if this line is ever reached, there was a bug". So the naming in this PR creates a false analogy.

**Comment by nnethercote** [comment]
> For delay_span_bug, it makes sense to think of this as "if this line is ever reached, there was a bug" (with an asterisk about rustc continuing compilation for a bit even on blatantly invalid programs).

Are you using "bug" the same way I am, as in "bug in rustc"?

If you are, then "if this line is ever reached, there was a bug" is wrong, because `span_delayed_bug` gets called all the time when compiling erroneous programs, without rustc being buggy.

If the statement is instead "if this line is ever reached, the program being compiled is erroneous" then that makes more sense.

**Comment by oli-obk** [comment]
r=me on everything but the last commit.



> Also, I _really_ want to eliminate `WeakDelayedBug`, because it kinda sucks, and only has two uses.

let's just work on that without renaming it first

**Comment by nnethercote** [comment]
I didn't do a good job of separating out distinct changes, and the last commit has a couple of different things happening. I will revert the parts of it that change "good path" to "weak".

**Comment by RalfJung** [comment]
Maybe we should have a t-compiler MCP for the name, to get input from more people.

**Comment by nnethercote** [comment]
> Maybe we should have a t-compiler MCP for the name, to get input from more people.

No thanks. I won't invite 15 people to weigh in via a process with a 10 day final comment period, just to get permission to rename something that has only ~30 occurrences in the compiler and that I want to remove anyway.

@oli-obk: I have updated the final commit to remove the "good path"-to-"weak" renaming parts. Should be good to go now, I think.

**Comment by matthiaskrgr** [comment]
@bors r- 
I suspec this caused problems here: https://github.com/rust-lang/rust/pull/120561#issuecomment-1925875289

**Comment by nnethercote** [comment]
> I suspect this caused problems here: https://github.com/rust-lang/rust/pull/120561#issuecomment-1925875289

The commit involving `suppressed_expected_diag` was causing an ICE when compiling https://github.com/iron/iron. I have removed that commit and I'll redo it in a follow-up. I also fixed the conflicts.

@bors r=oli-obk

**Comment by matthiaskrgr** [comment]
@bors r- may need rebase
https://github.com/rust-lang/rust/pull/120662#issuecomment-1926466270

**Comment by matthiaskrgr** [comment]
looks like this was not the problem :tada: 
@bors r=oli-obk

**Pull request merged**
