### PR TITLE
valgrind: update suppressions and move interesting tests

### PR DESCRIPTION
**Pull request by tamird**
Quite a bit of cruft in the valgrind suppressions. I started from a clean slate and found a few unique failures; this commit also moves the tests "fixed" by these suppressions into run-pass-valgrind.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ c21ffc27b12f092c8fd0789266aefff7796a73b5

Thanks!

**Comment by tamird** [comment]
Heh, what's up with bors?

**Comment by tamird** [comment]
@alexcrichton ah, sorry the commits are not rendering in the correct order on this branch. @bors is correct that 269a811 is the one you want.

**Pull request merged**
