### PR TITLE
Update link to Ousterhout

### LINKED ISSUE #26661: TRPL broken link
The page at https://doc.rust-lang.org/stable/book/academic-research.html has [Scheduling techniques for concurrent systems](http://www.ece.rutgers.edu/%7Eparashar/Classes/ece572-papers/05/ps-ousterhout.pdf), which is 404

/cc @steveklabnik

### PR DESCRIPTION
**Pull request by steveklabnik**
This is his own mirror, so it shouldn't go down, unlike the previous one.

Fixes #26661

### CODE REVIEW

**Comment by mkpankov** [comment]
Allow me to sneak in more changes :wink: 

These two are also broken:

> Scheduling techniques for concurrent systems
Three layer cake

**Comment by alexcrichton** [comment]
@bors: r+ 32f28d5f383daa93c865d0ada655ee4376341671 rollup

(also r=me for other link fixes)

**Comment by steveklabnik** [comment]
I was already updating it :)

**Comment by mkpankov** [comment]
Oh, working after work is hard. I mean this one too:

> External uniqueness is unique enough

**Comment by steveklabnik** [comment]
Done :)

**Pull request merged**
