### PR TITLE
add Stdin::lines, Stdin::split forwarder methods

### LINKED ISSUE #85383: E0716: confusing reference to borrow of `Stdin` value when there's no obvious reference within `StdinLock`
Given the following code: [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4129b8aca043f4e6a3c6ea755c5ed954)

```rust
use std::io::{self, BufRead};
fn main() {
    let locked = io::stdin().lock();
    for line in locked.lines() {
        println!("{}", line.unwrap());
    }
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0716]: temporary value dropped while borrowed
 --> src/main.rs:3:18
  |
3 |     let locked = io::stdin().lock();
  |                  ^^^^^^^^^^^       - temporary value is freed at the end of this statement
  |                  |
  |                  creates a temporary which is freed while still in use
4 |     for line in locked.lines() {
  |                 ------ borrow later used here
  |
  = note: consider using a `let` binding to create a longer lived value

error: aborting due to previous error

For more information about this error, try `rustc --explain E0716`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

I think it's typical for a newcomer to want to get a `Lines` iterator by chaining method calls like `io::stdin().lock().lines()`. There's no obvious reason why that shouldn't work. The examples in the `std::io` documentation do typically show `io::stdin()` being assigned to a variable prior to calling its `.lock()` method, but don't explain why that's necessary.

I think the "borrow" terminology is misleading, but there might not be a concise way to describe what's actually going on to the user. The "temporary value is freed at the end of this statement" is probably correct. The "creates a temporary which is freed while still in use" is probably more correctly "creates a temporary that is required to outlive (or live exactly as long as) the result of...", followed by a pointer to the `.lock()` method invocation, with text of "...this method call". Maybe it should also point out the `'_` lifetime argument in the `StdinLock<'_>` return type.

I tried and failed to find a satisfactory explanation of what exactly `StdinLock` was borrowing from the temporary `Stdin` value produced by `io::stdin()`. When I looked through the library source code, the only references in `StdinLock` were those created by locking a `Mutex`, and the `Mutex` in question is static. I'm guessing the existence of a borrow is assumed rather than inferred from analyzing the function body of `io::Stdin::lock()`. The assumption might be the result of the anonymous lifetime argument on the output type `StdinLock<'_>` from `io::Stdin::lock()`, which imposes a requirement that the `StdinLock` doesn't outlive (or has the same lifetime as?) the `Stdin` value that is the receiver of `lock()`.

The correct fix might be to change the locked stdin handles to all use `'static` lifetimes, but I will probably file that as a separate issue.

### PR DESCRIPTION
**Pull request by tlyu**
Add forwarder methods `Stdin::lines` and `Stdin::split`, which consume
and lock a `Stdin` handle, and forward on to the corresponding `BufRead`
methods. This should make it easier for beginners to use those iterator
constructors without explicitly dealing with locks or lifetimes.

Fixes #85383

@rustbot label +A-io +C-enhancement +D-newcomer-roadblock +T-libs

### CODE REVIEW

**Comment by Lokathor** [comment]
I'm pretty good with Rust and I had quite some trouble the other day trying to get stdin working with simple "line at a time" input, so this sounds great.

**Comment by joshtriplett** [comment]
I love the idea of making this easier.

I wonder, though, if we should just provide a method like `into_locked()` (or perhaps just `locked()`) publicly instead, for `Stdin`/`Stdout`/`Stderr`. That would solve the single biggest annoyance when working with stdin: the need to write something like:

```rust
let stdin = std::io::stdin();
let stdin = stdin.lock();
```

Writing those two lines as one line generates lifetime errors, because `.lock()` takes `&self`. Adding a method that consumes `self` would eliminate that issue, and allow writing things like `for line in std;:io::stdin().into_locked().lines() { ... }`.

I don't strongly object to the idea of adding `lines` and `split` directly on `stdin`; I might weakly object, perhaps, but those methods *might* be worth adding.

But I personally think the priority should be to fix this common cause of lifetime errors that prevents people from writing various one-liners, and in the process, make it easier to call any method that would be available on the locked versions.

**Comment by tlyu** [comment]
> I love the idea of making this easier.

Thanks for the feedback!

> I wonder, though, if we should just provide a method like `into_locked()` (or perhaps just `locked()`) publicly instead, for `Stdin`/`Stdout`/`Stderr`.

I think `locked` is a little too close to the existing `lock` method and might cause confusion. We do have precedent for the `into_` prefix for methods that consume the receiver.

> That would solve the single biggest annoyance when working with stdin: the need to write something like:
> 
> ```rust
> let stdin = std::io::stdin();
> let stdin = stdin.lock();
> ```
> 
> Writing those two lines as one line generates lifetime errors, because `.lock()` takes `&self`. Adding a method that consumes `self` would eliminate that issue, and allow writing things like `for line in std;:io::stdin().into_locked().lines() { ... }`.

I do think having something like `Stdin::into_lock` or `Stdin::locked` that consumes `Stdin` would be helpful. I didn't propose making it a part of the public API because I heard quite a few objections when I proposed making `Stdin::lock` return `StdinLock<'static>` or removing the lifetime parameter from `StdinLock`. So, I was trying to be conservative along the axis of making publicly visible changes to the locking API.

On the other hand, there is some discussion here https://internals.rust-lang.org/t/add-owned-guard-types-to-standard-library/14912 about owned guard types, so maybe there is some interest in doing similarly for the stdio handles? The naming for those methods also seems reasonable: `lock_owned`, etc.

We could even go a step further and make free functions like `io::stdin_locked()` available, possibly reducing the complexity of simple operations even further. (Though I understand how people might be more hesitant to add more free functions.)

> I don't strongly object to the idea of adding `lines` and `split` directly on `stdin`; I might weakly object, perhaps, but those methods _might_ be worth adding.

I think there's substantial benefit for adding those forwarders. We already have `Stdin::read_line` as precedent for an implicitly locking forwarder method, which probably exists for a similar reason: to make it easier for beginners to do common line-wise terminal input operations without needing to know about the nuances of locks and lifetimes sooner than is appropriate for them.

I think this is quite important: adding interactivity can feel like a substantial achievement beyond "hello world", and lowering the barriers to achieving this can make learning Rust a little friendlier.

Adding `Stdin::into_lock` alone _is_ an incremental improvement, but still exposes the locking API to beginners who might simply want an iterator over input lines. The only reason I've needed to use the locking API on `Stdin` is that I wanted access to the `lines` method, which requires `StdinLock`, _for reasons that aren't readily apparent_ until you know some details about the implementation.

> But I personally think the priority should be to fix this common cause of lifetime errors that prevents people from writing various one-liners, and in the process, make it easier to call any method that would be available on the locked versions.

I'm happy to work on a pull request that consists only of adding `into_lock`, `lock_owned`, etc to `Stdin`, and maybe to the other stdio handles, if you think that will be more widely accepted than the forwarder methods. I still think that the forwarder methods have substantial benefits of their own.

I guess I'd like to ask: what benefits there are to having a public `into_lock` method besides gaining access to the `BufRead` methods `lines` and `split`? I would guess that explicit locking control over `Stdin` isn't necessary for a lot of use cases once we make those methods available, but I'd be interested to hear about more use cases.

**Comment by joshtriplett** [comment]
> what benefits there are to having a public `into_lock` method besides gaining access to the `BufRead` methods `lines` and `split`?

Locking for performance. If you're going to consume or produce a large amount of data in a loop, you can get a substantial performance improvement by locking once rather than once per iteration.

> We could even go a step further and make free functions like `io::stdin_locked()` available, possibly reducing the complexity of simple operations even further.

Those helpers seem entirely reasonable to me as well. I would be happy to see them added. And those helpers also provide more brevity, making it more reasonable to use the verbose name `into_locked` as the method name for clarity.

> I'm happy to work on a pull request that consists only of adding `into_lock`, `lock_owned`, etc to `Stdin`, and maybe to the other stdio handles, if you think that will be more widely accepted than the forwarder methods.

I would love to see a PR that adds an `into_locked` method to all three types, and corresponding `stdin_locked`/`stdout_locked`/`stderr_locked` free functions. (I'd also love to see that PR adjust the documentation of the existing `lock` methods and the existing unlocked free functions to suggest using these new methods and functions.)

That doesn't *preclude* adding helpers for the methods of BufRead as well. I just feel like this is a good incremental step to make Rust more learnable, and to give users a gentler introduction to one concept at a time. (Users would still have to understand that they need to lock stdin, but they wouldn't also simultaneously have to deal with a lifetime issue.)

**Comment by tlyu** [comment]
Thanks! I'll work on that, then.

I know this is unlikely to be accepted because it's a breaking change, but what if the default stdio handles `io::stdin()`, etc were locked, and you had to use a different function like `io::stdin_unlocked()` to get unlocked ones? I wonder how different things would look. Multi-threading isn't exactly a beginner concept, so if the default stdio handles can only be used in a single thread, it's not a huge loss to beginners. The impact on the rest of the ecosystem might be too much, though.

**Comment by Lokathor** [comment]
Much as that might be a good idea, breaking changes to the standard library are just not going to happen at this time.

**Comment by joshtriplett** [comment]
I don't think we could change `io::stdin()` to be locked by default. We *might*, in theory, be able to change `lock()` to return `StdinLock<'static>` (changing the lifetime), without breaking anything, but that'd still be more disruptive for minimal benefit.

**Comment by tlyu** [comment]
Deferring until #86799 gets some review.

**Comment by tlyu** [comment]
I'll resolve the merge conflicts (and try to rename the branch, because that name is no longer quite accurate).

@rustbot label -S-blocked +S-waiting-on-author

**Pull request closed without merging**
