### PR TITLE
Add two functions to check type of given address

### PR DESCRIPTION
**Pull request by achanda**
The is_v4 function returns true if the given IP is v4. The is_v6
function returns true if the IP is v6.

### CODE REVIEW

**Comment by achanda** [comment]
@alexcrichton I was looking for a way to `filter` a list of `IpAddr`s based on type. I thought these two functions might help. But I have a feeling now that these might not be idiomatic enough. Thoughts?

**Comment by alexcrichton** [comment]
Thanks for the PR @achanda! This seems pretty reasonable to me. I'd be fine even adding `SocketAddr::{is_ipv4, is_ipv6}` as well.

Thoughts @rust-lang/libs ?

Also looks like the travis failure may need to be resolved before landing.

**Comment by achanda** [comment]
@alexcrichton makes sense, I will have a PR up for those as well once I fix these tests here.

**Comment by achanda** [comment]
Looks like this needs a `r+` :)

**Comment by alexcrichton** [comment]
@achanda sure yeah, just postponing to discuss the new feature in a libs triage

**Comment by achanda** [comment]
Ah, sorry for rushing!

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by alexcrichton** [comment]
I think the last piece of functionality we'd want here is a tracking issue and a specific `#[unstable]` tag on these methods (apart from the "catch all bucket" unstable issue for these methods), but that can happen once libs has taken a peek.

**Comment by achanda** [comment]
@alexcrichton sorry, should I add the `#[unstable]` tag now? The rfcbot is new to me!

**Comment by alexcrichton** [comment]
@achanda sure if you'd like! This is likely to be accepted so if you want to go ahead and open an issue for this as well I can tag it and you can reference it.

Also don't worry, rfcbot is hot new technology for us too!

**Comment by achanda** [comment]
@alexcrichton done!

**Comment by alexcrichton** [comment]
@bors: r+

Thanks again @achanda

**Pull request merged**
