### PR TITLE
Rollup of 16 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
- Successful merges: #24979, #24980, #24981, #24982, #24983, #24987, #24988, #24991, #24992, #24994, #24998, #25002, #25010, #25014, #25020, #25021
- Failed merges:

### CODE REVIEW

**Comment by luqmana** [comment]
@Manishearth: wrong bors :P though I guess it doesn't care what name.

**Comment by Manishearth** [comment]
Yeah :)

**Pull request merged**
