### PR TITLE
feat: Add a documentation problem issue template

### LINKED ISSUE #98722: This repository has no issue template for documentation problems
This is unfortunate because:

1. It gives the impression that documentation fixes should not be submitted here, or are not welcome.
2. It prevents you from gathering commonly requested information (link to docs, rust version number, suggested fixes) in an automatic fashion.
3. It prevents automatic labelling for documentation-relevant issues.

To fix this, [add a new issue template](https://github.com/rust-lang/rust/tree/master/.github/ISSUE_TEMPLATE).

### PR DESCRIPTION
**Pull request by ghost**
Fixes #98722 :)

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Should this capture the Rust version in the template too? I can see the appeal of using a very minimal template instead though.

**Comment by gimbles** [comment]
> Should this capture the Rust version in the template too? I can see the appeal of using a very minimal template instead though.

I don't..think that will be quite useful? No point in reporting a doc problem that happened a release or two ago but fixed on latest :D

Although I think I might be misunderstanding what you meant by that

**Comment by alice-i-cecile** [comment]
My thought was that you want to be able to check that the problem wasn't already fixed by another change that forgot to mention the issue.

But I suppose that because doc issues are almost always trivial to verify, it's really not worth it.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

Seems like a good start, and we can always iterate in the future. Thanks!

**Comment by ehuss** [comment]
I'm wondering if it might be helpful to direct the user to the appropriate repo in the comment. Documentation lives all over the place, and going through the rigamarole of having them close and reopen can be annoying. I can transfer issues between some repos, but not all of them.

For example, it could say:

Some docs have their own dedicated issue trackers. If the issue is for one of the following, please consider filing the issue in the corresponding tracker:

* The Rust Programming Language ("The Book"): https://github.com/rust-lang/book/issues
* Cargo: https://github.com/rust-lang/cargo/issues
* Rustup: https://github.com/rust-lang/rustup/issues
* Rust by Example: https://github.com/rust-lang/rust-by-example/issues
* The Reference: https://github.com/rust-lang/reference/issues
* The Edition Guide: https://github.com/rust-lang/edition-guide/issues
* The Rustonomicon: https://github.com/rust-lang/nomicon/issues
* The Embedded Rust Book: https://github.com/rust-embedded/book/issues
* The Website (https://www.rust-lang.org/): https://github.com/rust-lang/www.rust-lang.org/issues

All other documentation issues should be filed here (including The Standard Library, The Rustc Book, The Rustdoc Book, The Rust Unstable Book, and anything else).

----

That might be a bit too much or overwhelming, so I'm not sure if it makes sense. I only need to transfer an issue about once a month, so it doesn't happen too often.  Also, most of those docs have links directly to their GitHub repos, so most users seem to be able to find their way. What do you think?

**Comment by alice-i-cecile** [comment]
I personally like those links quite a bit, but I like long issue templates much more than the average user 😆 

Perhaps list what *does* fit here, and then link to an external page for "everything else"?

**Comment by gimbles** [comment]
> I personally like those links quite a bit, but I like long issue templates much more than the average user laughing
> 
> Perhaps list what _does_ fit here, and then link to an external page for "everything else"?

We could have the list in a comment in the template, so it wouldn't be shown in the render =)

**Pull request merged**
