### PR TITLE
make `Sized` predicates coinductive

### PR DESCRIPTION
**Pull request by lcnr**
:shrug:

needs either an MCP/RFC and `wg-traits` signoff. While I think this is sound, I am not too knowledgeable about coinduction so I might be wrong here.

r? @nikomatsakis

### CODE REVIEW

**Comment by m-ou-se** [comment]
This fixes https://github.com/rust-lang/rust/issues/47032

**Comment by nikomatsakis** [comment]
I'm going to want to talk about the motivation =)

**Comment by lcnr** [comment]
I still want to add this as a test, so that I don't forget. I expect the error here to change from a predicate cycle to "recursive type `Foo<()>` has infinite size"
```rust
trait A { type Assoc; }

impl A for () {
    type Assoc = Foo<()>;
}
struct Foo<T: A>(T::Assoc);

fn main() {}
```

**Comment by lcnr** [comment]
also
```rust
trait A { type Assoc: ?Sized; }

impl A for () {
    type Assoc = Foo<()>;
}
struct Foo<T: A>(T::Assoc);

fn main() {
    let x: Foo<()>;
}
```

**Comment by JohnCSimon** [comment]
triage: @lcnr - is this still blocked?

**Comment by nikomatsakis** [comment]
@lcnr is taking a bit of a break from Rust at the moment -- we could close this, but it's also ok to leave it open.

**Comment by lcnr** [comment]
don't have the capacity to work on this rn

**Comment by marmeladema** [comment]
Would this allow to compile:
```
use std::borrow::Cow;

#[derive(Clone)]
enum Test<'a> {
    Int(u8),
    Array(Cow<'a, [Test<'a>]>, ()),
}
```
?

**Comment by compiler-errors** [comment]
@marmeladema that code already compiles, I think you mean:

```
use std::borrow::Cow;

#[derive(Clone)]
enum Test<'a> {
    Int(u8),
    Array(Cow<'a, [Test<'a>]>),
}
```

**Comment by marmeladema** [comment]
Sorry, yes, I copy pasted the wrong snippet from our zulip conversation. Have edited my comment.

**Pull request closed without merging**
