### PR TITLE
Remove boilerplate from Apache license

### PR DESCRIPTION
**Pull request by steveklabnik**
:embarassed:

### CODE REVIEW

**Comment by frewsxcv** [comment]
Why are you getting rid of this?

**Comment by steveklabnik** [comment]
@frewsxcv I assume, given that it's instructions to apply the license to your work, that it was accidentally put here. If this is some odd feature of Apache (a license I admittedly don't use much), then I'm just wrong, but seems very odd.

**Comment by steveklabnik** [comment]
No, apparently apache is just weird. sorry for the noise.

**Comment by frewsxcv** [comment]
Disclaimer: I am definitely not a lawyer

I do think it's sorta funny that the Apache license has an 'APPENDIX' section distributed with their license. Even though it's not part of 'TERMS AND CONDITIONS', I still think it's part of the Apache license as a whole and *might* not be completely trivial to remove. Though I do enjoy efforts to simplify licenses :P

**Pull request closed without merging**
