### PR TITLE
Update LLVM submodule

### PR DESCRIPTION
**Pull request by cramertj**
Fix https://github.com/rust-lang/rust/issues/52884

r? @alexcrichton

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r-

Obsoleted by https://github.com/rust-lang/rust/pull/52983#issuecomment-409958801, so removing this from queue to avoid merge conflict.

**Comment by alexcrichton** [comment]
Note that https://github.com/rust-lang/rust/pull/52983 is also much higher risk, so if it bounces once we should put this back in the queue

**Comment by kennytm** [comment]
#52983 has been merged, closing this one.

**Pull request closed without merging**
