### PR TITLE
Preserve split DWARF files when building archives.

### PR DESCRIPTION
**Pull request by khuey**
r? @davidtwco

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by ehuss** [comment]
Can you say more about what kinds of issues this was causing? On macOS, I haven't noticed any problems with lldb finding debuginfo for rlib dependencies.

**Comment by khuey** [comment]
With `-Csplit-debuginfo=unpacked` the DWO files with the debug info were being thrown away.

**Comment by ehuss** [comment]
Yes, but how does that manifest as a problem? Does a debugger stepping into a dependency just show assembly output?  Why would macOS be different here? My understanding is that macOS just dumps a bunch of `.o` files, but only for the executable. Does macOS store the debuginfo for the dependencies inside the `.o` files for the binary?  If so, perhaps this change isn't needed for macOS?

**Comment by khuey** [comment]
It shows as there being no debugging information for the relevant crate, no source, no function names, etc.

Are you using split debuginfo on Mac? You haven't stated anything about your configuration yet.

**Comment by ehuss** [comment]
I'm using all defaults with Cargo, whose default is `unpacked`.

**Comment by khuey** [comment]
Ok, then cargo should take the

```(SplitDebuginfo::Unpacked, _) if !sess.target_can_use_split_dwarf() => (true, false)```

branch in order to leave the object files on the file system where the debugger can find them.

**Comment by ehuss** [comment]
Sorry, I'm not sure I follow. The debugger was finding the debuginfo fine before this PR.

Historically, `split-debuginfo=unpacked` on macOS only left unpacked `.o` files for the final binary. It did not leave unpacked `.o` files for `rlibs`. lldb worked fine and was able to find debug information for dependencies. I don't know enough about DWARF or how lldb finds debuginfo to say how that worked.

This PR changed it so that rlibs also leave `.o` files. My question is: is that necessary?

**Comment by khuey** [comment]
> My question is: is that necessary?

I don't know, but I don't see how things would have worked on Mac before this change.

**Pull request merged**
