### PR TITLE
[beta] Backport disabling of Clippy lint debug_assert_with_mut_call

### PR DESCRIPTION
**Pull request by flip1995**
This disables the Clippy lint `debug_assert_with_mut_call`, see rust-lang/rust-clippy#5112.

Since this is a deny-by-default lint, that landed with `1.41.0`, we want to disable this lint rather sooner than later, that's why the backport.

Clippy branch for the backport: https://github.com/rust-lang/rust-clippy/tree/rust-1.42.0

r? @Mark-Simulacrum 

cc (from the Clippy side) @Manishearth @oli-obk

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
r+ cc @pietro if I need to do something special for the backport

**Comment by Manishearth** [comment]
Er, @pietroalbini

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=1

I think this is fine to land as-is; beta backports are more than a week away most likely so we can get this in in the meantime.

**Comment by flip1995** [comment]
ping @Mark-Simulacrum The azure build was canceled by `@alexcrichton`. Do I have to change something or does it just need a `retry`?

**Comment by Mark-Simulacrum** [comment]
> 2020-02-02T16:56:48.5390161Z fatal: write error: No space left on device 

Odd. I suspect (hope!) this is spurious. @bors retry

**Pull request merged**
