### PR TITLE
submodules: Update RLS and Rustfmt

### LINKED ISSUE #72231: `rls` no longer builds after rust-lang/rust#69659
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#69659, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @CAD97, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### LINKED ISSUE #72232: `rustfmt` no longer builds after rust-lang/rust#69659
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#69659, I observed that the tool rustfmt no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rustfmt is needed to fix the fallout.

cc @CAD97, do you think you would have time to do the follow-up work?
If so, that would be great!

And nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by Xanewok**
Fixes #72231
Fixes #72232

r? @ghost

cc @topecongiro

### CODE REVIEW

**Comment by Xanewok** [comment]
@topecongiro I'm getting the undefined CFG_RELEASE errors:
```
 error: environment variable `CFG_RELEASE` not defined
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_attr-659.0.0/builtin.rs:657:48
    |
657 |             let rustc_version = Version::parse(env!("CFG_RELEASE")).unwrap();
    |                                                ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `rustc-ap-rustc_attr`.
```
Did you come to any conclusion how to solve that in your environment or how we can fix that here?

**Comment by topecongiro** [comment]
@Xanewok We simply set `CFG_RELEASE` and `CFG_RELEASE_CHANNEL` to `nightly` using cargo-make. I thought that these two environment variables are somehow automatically set when building inside the rustc repository, but it looks like that is not the case.

@mibac138 @petrochenkov Are you aware of any good workaround?

**Comment by ehuss** [comment]
`CFG_RELEASE_CHANNEL` is set for [all builds](https://github.com/rust-lang/rust/blob/a9ca1ec9280ca1e5020edd699917c3367a30a798/src/bootstrap/builder.rs#L1198).  `CFG_RELEASE` is only set for [`rustc`](https://github.com/rust-lang/rust/blob/a9ca1ec9280ca1e5020edd699917c3367a30a798/src/bootstrap/compile.rs#L490).  It may be possible to set `CFG_RELEASE` for rustfmt and rls. I'm not sure if it makes sense to set that globally, or just for those tools ([tool.rs](https://github.com/rust-lang/rust/blob/master/src/bootstrap/tool.rs)). That seems like a @Mark-Simulacrum question.

It seems like another option would be to use `option_env!` instead, but that seems dangerous (as in, that attribute wouldn't work correctly if it is not set).

**Comment by Mark-Simulacrum** [comment]
It should be fine to set CFG_RELEASE for all builds as well; please leave a comment noting that rustfmt (and potentially other tools) rely on it due to rustc_attr dependencies.

**Comment by Dylan-DPC** [comment]
@Xanewok any updates?

**Comment by ehuss** [comment]
Something like this should work:

```diff
diff --git a/src/bootstrap/tool.rs b/src/bootstrap/tool.rs
index 8ebad95ea17..054c7412b84 100644
--- a/src/bootstrap/tool.rs
+++ b/src/bootstrap/tool.rs
@@ -254,6 +254,10 @@ pub fn prepare_tool_cargo(

     cargo.env("CFG_RELEASE_CHANNEL", &builder.config.channel);
     cargo.env("CFG_VERSION", builder.rust_version());
+    // CFG_RELEASE is needed by rustfmt (and possibly other tools) which
+    // import rustc-ap-rustc_attr which requires this to be set for the
+    // `#[cfg(version(...))]` attribute.
+    cargo.env("CFG_RELEASE", builder.rust_release());
     cargo.env("CFG_RELEASE_NUM", channel::CFG_RELEASE_NUM);

     let info = GitInfo::new(builder.config.ignore_git, &dir);
````

**Comment by Xanewok** [comment]
Sorry for the delay. @ehuss submitted a commit with your changes, thanks!

**Comment by Dylan-DPC** [comment]
giving this priority for release: 
@bors p=10

**Comment by ehuss** [comment]
https://github.com/rust-lang/rust/pull/55617 shifted `stacker` to `rustc_data_structures` which is used by `rustfmt`, and this brings in a new winapi feature.

```diff
diff --git a/src/tools/rustc-workspace-hack/Cargo.toml b/src/tools/rustc-workspace-hack/Cargo.toml
index cbf7d09f2e4..1b1f4447966 100644
--- a/src/tools/rustc-workspace-hack/Cargo.toml
+++ b/src/tools/rustc-workspace-hack/Cargo.toml
@@ -22,6 +22,7 @@ features = [
   "basetsd",
   "consoleapi",
   "errhandlingapi",
+  "fibersapi",
   "ioapiset",
   "jobapi",
   "jobapi2",
```

**Comment by JohnTitor** [comment]
Note that #72671 also fixes RLS and rustfmt toolstates. I'd prefer to land that rather than this avoid duplication.

**Comment by Xanewok** [comment]
Succeeded by #72671.

**Pull request closed without merging**
