### PR TITLE
Update bootstrap compiler to 1.65.0

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR updates the bootstrap compiler to Rust 1.65.0, removing the various `cfg(bootstrap)`s.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Urgau** [comment]
> Checking rustc_codegen_cranelift v0.1.0 (/checkout/compiler/rustc_codegen_cranelift)
> error: unexpected `parallel_compiler` as condition name
>   |
>   = note: `-D unexpected-cfgs` implied by `-D warnings`
>   = help: was set with `--cfg` but isn't in the `--check-cfg` expected names

Seems like `rustc_codegen_cranelift` is neither compiled as `Mode::Rustc` nor as `Mode::ToolRustc`: https://github.com/rust-lang/rust/blob/8fd6d03e22fba2930ad377b87299de6a37076074/src/bootstrap/lib.rs#L199-L200

**Comment by pietroalbini** [comment]
Thanks for the quick comment! Applied your patch.

**Comment by Mark-Simulacrum** [comment]
```
 failures:

---- [mir-opt] src/test/mir-opt/issue-101867.rs stdout ----
1	// MIR for `main` 0 mir_map
2	
3	| User Type Annotations
-	| 0: user_ty: Canonical { max_universe: U0, variables: [], value: Ty(std::option::Option<u8>) }, span: $DIR/issue-101867.rs:5:12: 5:22, inferred_ty: std::option::Option<u8>
-	| 1: user_ty: Canonical { max_universe: U0, variables: [], value: Ty(std::option::Option<u8>) }, span: $DIR/issue-101867.rs:5:12: 5:22, inferred_ty: std::option::Option<u8>
+	| 0: user_ty: Canonical { max_universe: U0, variables: [], value: Ty(std::option::Option<u8>) }, span: $DIR/issue-101867.rs:3:12: 3:22, inferred_ty: std::option::Option<u8>
+	| 1: user_ty: Canonical { max_universe: U0, variables: [], value: Ty(std::option::Option<u8>) }, span: $DIR/issue-101867.rs:3:12: 3:22, inferred_ty: std::option::Option<u8>
6	|
7	fn main() -> () {
8	    let mut _0: ();                      // return place in scope 0 at $DIR/issue-101867.rs:+0:11: +0:11

thread '[mir-opt] src/test/mir-opt/issue-101867.rs' panicked at 'Actual MIR output differs from expected MIR output /checkout/src/test/mir-opt/issue_101867.main.mir_map.0.mir', src/tools/compiletest/src/runtest.rs:3515:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by davidtwco** [comment]
Sorry for the late comment on this, but there are a bunch of `#[allow(..)]` attributes that don't have `cfg(bootstrap)` but should have so they would have been removed in this pull request. An internal lint was triggering more than it ought to have been (fixed in #101230). Do you think you could remove them in this PR? If it's too late then I can do it in a follow-up so that's fine too.

- `compiler/rustc_session/src/session.rs:291`
- `compiler/rustc_session/src/session.rs:292`
- `compiler/rustc_session/src/session.rs:301`
- `compiler/rustc_session/src/session.rs:302`
- `compiler/rustc_session/src/session.rs:312`
- `compiler/rustc_session/src/session.rs:313`
- `compiler/rustc_session/src/session.rs:323`
- `compiler/rustc_session/src/session.rs:324`
- `compiler/rustc_session/src/session.rs:329`
- `compiler/rustc_session/src/session.rs:330`
- `compiler/rustc_session/src/session.rs:339`
- `compiler/rustc_session/src/session.rs:340`
- `compiler/rustc_session/src/session.rs:349`
- `compiler/rustc_session/src/session.rs:350`
- `compiler/rustc_session/src/session.rs:355`
- `compiler/rustc_session/src/session.rs:356`
- `compiler/rustc_session/src/session.rs:365`
- `compiler/rustc_session/src/session.rs:366`
- `compiler/rustc_session/src/session.rs:375`
- `compiler/rustc_session/src/session.rs:376`
- `compiler/rustc_session/src/session.rs:387`
- `compiler/rustc_session/src/session.rs:388`
- `compiler/rustc_session/src/session.rs:396`
- `compiler/rustc_session/src/session.rs:397`
- `compiler/rustc_session/src/session.rs:406`
- `compiler/rustc_session/src/session.rs:407`
- `compiler/rustc_session/src/session.rs:416`
- `compiler/rustc_session/src/session.rs:417`
- `compiler/rustc_session/src/session.rs:426`
- `compiler/rustc_session/src/session.rs:427`
- `compiler/rustc_session/src/session.rs:437`
- `compiler/rustc_session/src/session.rs:438`
- `compiler/rustc_session/src/session.rs:444`
- `compiler/rustc_session/src/session.rs:445`
- `compiler/rustc_session/src/session.rs:450`
- `compiler/rustc_session/src/session.rs:451`
- `compiler/rustc_session/src/session.rs:461`
- `compiler/rustc_session/src/session.rs:462`
- `compiler/rustc_session/src/session.rs:467`
- `compiler/rustc_session/src/session.rs:468`
- `compiler/rustc_session/src/session.rs:482`
- `compiler/rustc_session/src/session.rs:483`
- `compiler/rustc_session/src/session.rs:492`
- `compiler/rustc_session/src/session.rs:493`
- `compiler/rustc_session/src/parse.rs:379`
- `compiler/rustc_session/src/parse.rs:380`
- `compiler/rustc_session/src/parse.rs:389`
- `compiler/rustc_session/src/parse.rs:390`
- `compiler/rustc_session/src/parse.rs:396`
- `compiler/rustc_session/src/parse.rs:397`
- `compiler/rustc_session/src/parse.rs:403`
- `compiler/rustc_session/src/parse.rs:404`

**Comment by pietroalbini** [comment]
@davidtwco yeah it's better to do it in a followup PR.

**Comment by nnethercote** [comment]
`keccak` has been noisy recently, these regressions probably aren't real.

@rustbot label: +perf-regression-triaged

**Comment by Mark-Simulacrum** [comment]
Confirming noise - see https://github.com/rust-lang/rust/pull/102292#issuecomment-1259533099 for some graphs.

**Pull request merged**
