### PR TITLE
Revert "Avoid nested replacement ranges" from #129346.

### PR DESCRIPTION
**Pull request by nnethercote**
It caused a test regression in the `cfg_eval.rs` crate. (The bugfix in #129346 was in a different commit; this commit was just a code simplification.)

r? @petrochenkov

### CODE REVIEW

**Comment by nnethercote** [comment]
The regression was reported by @danielhenrymantilla [here](https://github.com/rust-lang/rust/pull/129346#pullrequestreview-2377762071).

**Comment by nnethercote** [comment]
I don't entirely understand the failing example, but reverting the change fixes it. I haven't added a test because the example involves a proc macro and is hard to write a test for :/

**Comment by danielhenrymantilla** [comment]
Awesome thanks @nnethercote ❤️ 

  - I tried to minimize the error with no proc-macro involvement, but that would "fix" the issue; so it does seem related to having some proc-macro passing of tokens and whatnot. I can try to invest a bit more investigative work into reducing the issue, should the tests in this repo allow defining ad-hoc proc-macros.

**Comment by nnethercote** [comment]
> should the tests in this repo allow defining ad-hoc proc-macros

They do, see `tests/ui/proc-macro` and `tests/ui/proc-macro/auxiliary`.

**Comment by nnethercote** [comment]
@lqd said [this](https://github.com/rust-lang/rust/pull/129346#issuecomment-2454501671):

> the regression is indeed present in the 1.83 unexpected test failures: https://crater-reports.s3.amazonaws.com/beta-1.83-1/beta-2024-10-19/gh/danielhenrymantilla.cfg_eval.rs/log.txt

so I have added the beta-nominated label.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-11-07/near/481141601). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted

**Pull request merged**
