### PR TITLE
Remove noisy suggestion of hash_map 

### LINKED ISSUE #72642: Do not suggest importing hash_map::HashMap or btree_map::BTreeMap
```rust
struct S {
    m: HashMap<String, ()>,
}
```

```console
error[E0412]: cannot find type `HashMap` in this scope
 --> src/main.rs:2:8
  |
2 |     m: HashMap<String, ()>,
  |        ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use std::collections::HashMap;
  |
1 | use std::collections::hash_map::HashMap;
  |
```

The `std::collections::hash_map::HashMap` suggestion here is just noise, it's (almost?) never what we actually want the person to import.

This issue has been assigned to @ayushmishra2005 via [this comment](https://github.com/rust-lang/rust/issues/72642#issuecomment-634702867).

### PR DESCRIPTION
**Pull request by ayushmishra2005**
Remove noisy suggestion of hash_map #72642

fixes #72642

### CODE REVIEW

**Comment by ayushmishra2005** [comment]
@Dylan-DPC @lzutao   @lcnr I have raised new PR and closed https://github.com/rust-lang/rust/pull/72947. Please take a look.

**Review by lcnr — APPROVED** [review]
Thanks :+1: 

Please add `fixes #72642` to the description of this PR.
This automatically closes that issue once this PR is merged.

*edit: what was the reason for closing the original PR?*

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
Will approve once CI passes!

**Comment by ayushmishra2005** [comment]
> Thanks 
> 
> Please add `fixes #72642` to the description of this PR.
> This automatically closes that issue once this PR is merged.
> 
> _edit: what was the reason for closing the original PR?_

@lcnr I did something wrong while squashing the commit. That's why I raised fresh PR.

**Comment by ayushmishra2005** [comment]
@Dylan-DPC  Please let me know if anything is pending from my side. I rebased my PR with the master branch. CI pipeline is working fine.

**Comment by ayushmishra2005** [comment]
@Dylan-DPC Please let me know if there is anything stopping this PR to be merged in master. This PR has been approved by the reviewer @davidtwco . I have been rebasing with master on daily basis and CI pipeline is also green.

Please let me know if there is anything pending from my side. I would address it asap. 
Thanks

**Comment by davidtwco** [comment]
@ayushmishra2005 Unless there are conflicts or CI failures while merging, you don’t need to rebase - every time  you do, I need to reapprove. It’s in the merge queue. 

@bors r+

**Pull request merged**
