### PR TITLE
Turn remaining non-structural-const-in-pattern lints into hard errors

### LINKED ISSUE #70861: function pointers as match patterns have optimization-dependent behavior
I tried this code, supplied by @eddyb [play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a1a4aafc915c188318a377d0a20e36d3):
 
```rust
#![feature(test)]
use std::hint::black_box;

fn foo() {}
const FOO: fn() = foo;

fn bar() {}
const BAR: fn() = bar;

#[inline(never)]
fn print(s: &str) {
    println!("{}", s);
}

fn main() {
    match black_box(FOO) {
        FOO => print("FOO"),
        BAR => print("BAR"),
        _ => unreachable!(),
    }
    
    match black_box(FOO) {
        BAR => print("BAR"),
        FOO => print("FOO"),
        _ => unreachable!(),
    }
    
    match black_box(BAR) {
        FOO => print("FOO"),
        BAR => print("BAR"),
        _ => unreachable!(),
    }
    
    match black_box(BAR) {
        BAR => print("BAR"),
        FOO => print("FOO"),
        _ => unreachable!(),
    }
}
```

I expected to see this happen: print out of
```
FOO
FOO
BAR
BAR
```
(and in debug builds, that *is* what happens).

Instead, this happened: in release builds, it prints:

```
FOO
BAR
FOO
BAR
```

### Meta

This was on a playpen running 1.44.0-nightly, 2020-04-05.

This all arose from a conversation with @eddyb regarding structural match; you can read it on the [zulip archive](https://zulip-archive.rust-lang.org/131828tcompiler/22816Structuralmatchmarkertraits.html#193034951)

cc #31434

### PR DESCRIPTION
**Pull request by RalfJung**
This completes the implementation of https://github.com/rust-lang/rust/issues/120362 by turning our remaining future-compat lints into hard errors: indirect_structural_match and pointer_structural_match.

They have been future-compat lints for a while (indirect_structural_match for many years, pointer_structural_match since Rust 1.75 (released Dec 28, 2023)), and have shown up in dependency breakage reports since Rust 1.78 (just released on May 2, 2024). I don't expect a lot of code will still depend on them, but we will of course do a crater run.

A lot of cleanup is now possible in const_to_pat, but that is deferred to a later PR.

Fixes https://github.com/rust-lang/rust/issues/70861

### CODE REVIEW

**Comment by RalfJung** [comment]
@craterbot check

**Comment by RalfJung** [comment]
Many of these are caused by `-D renamed-and-removed-lints`. (Not sure where that flag comes from, does crater set it? That wouldn't make sense...)

On crates.io we have two true regression:
- ctti (<1k total downloads, author notified at https://github.com/h33p/ctti/issues/1)
- cambridge-asm (~13k total downloads, author notified at https://github.com/SaadiSave/cambridge-asm/issues/3)

The github failures are either false positives, duplicates of one of these crates, or advent of code repos.

I think we can go ahead and land this. (Remember, if it lands now crater authors still have until July 25th before this hits stable.) Nominating for t-lang.

**Comment by pnkfelix** [comment]
The code itself seems fine; just need T-lang to sign off that we are good with taking the final plunge here. Once we have that, then I will be happy to r+ the PR.

@rustbot label: -S-waiting-on-review +S-waiting-on-team

**Comment by pnkfelix** [comment]
@rustbot label: -T-compiler

@rfcbot fcp merge

(I'm just preemptively firing up a T-lang FCP to approve this change.)

**Comment by pnkfelix** [comment]
Oh noes, it doesn't sequence the commands to remove the label before firing off the rfcbot command!

@rfcbot cancel

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

(I'm just preemptively firing up a T-lang FCP to approve this change.)

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in the triage meeting today, and it's now in FCP.

**Comment by RalfJung** [comment]
@pnkfelix wrote
> The code itself seems fine

@bors r=pnkfelix

**Pull request merged**
