### PR TITLE
[beta] backports

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This PR backports the following:

* Make novel structural match violations not a `bug` #73446
* linker: Never pass `-no-pie` to non-gnu linkers #73384
* Disable the `SimplifyArmIdentity` pass #73262
* Allow inference regions when relating consts #73225
* Fix link error with #[thread_local] introduced by #71192 #73065
* Ensure stack when building MIR for matches #72941
* Don't create impl candidates when obligation contains errors #73005 

r? @ghost

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors p=1
backports

**Comment by Mark-Simulacrum** [comment]
@bors r+ p=1 rollup=never

Hm okay CI failure seems to be plausibly related to the beta-nature of this PR (hopefully won't fail in the same way in main CI). I think it's probably related to the recent work that @cuviper did there but I can't be certain.

**Comment by cuviper** [comment]
> I think it's probably related to the recent work that @cuviper did there but I can't be certain.

If you mean #72993, that code hasn't reached the beta branch yet.

However, I do think this is the race I predicted in a comment there:

> In fact, I think the old code that used ls-remote had a race in this regard, if something happened to merge into master after the local repo had last cloned/updated -- you could get a master commit that doesn't exist locally, and then merge-base would fail.

Your failure:

```
fatal: Not a valid commit name 9672b5e95c520774cc17bffc7031c80a1bcf4b4c
thread 'main' panicked at 'command did not execute successfully: "git" "merge-base" "1dc0f6d8ef4ff19cfbe468ede40a1a6596f48957" "9672b5e95c520774cc17bffc7031c80a1bcf4b4c"
```

The full @bors builds are serialized, but they can run concurrently to PR CI, so one may have landed while your initial run was in progress.

**Comment by Mark-Simulacrum** [comment]
Yeah, that's what I was thinking about. Seems like it's probably not too important -- it only affects beta PR CI which isn't all that critical anyway

**Comment by Manishearth** [comment]
@bors retry

network issues

**Pull request merged**
