### PR TITLE
Initial implementation of rustfixable unused_imports lint

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR adds the initial implementation of rustfixable `unused_imports` lint. The implementation works, but rustfix is not able to apply all the suggestions until https://github.com/rust-lang/rust/issues/53934 is fixed. It also needs https://github.com/rust-lang/rust/pull/58296 to hide the suggested note since it's really useless.

cc https://github.com/rust-lang/rust/issues/47888

<details><summary><code>cargo fix</code> in action on the <code>unused_imports</code> lint</summary>

screenshot from 2018-12-09 15-49-01

</details>

### CODE REVIEW

**Comment by estebank** [comment]
CC #58296

**Comment by zackmdavis** [comment]
This isn't _literally_ blocked on the #53934 mess ([latest comment](https://github.com/rust-lang/rust/issues/53934#issuecomment-461741695)), is it? Like, the _main_ reason we want this is to make the unused imports rustfix-able, but landing this structured suggestion (with the "remove the whole `use` item" and "remove the unused import" notes) doesn't _hurt_.

**Comment by estebank** [comment]
@pietroalbini I'm fine with merging this PR as is. r=me (rename beforehand) if you feel it's ready on your end.

**Comment by estebank** [comment]
```
[01:51:58] failures:
[01:51:58] 
[01:51:58] ---- fix::shows_warnings stdout ----
[01:51:58] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo fix --allow-no-vcs`
[01:51:58] thread 'fix::shows_warnings' panicked at '
[01:51:58] Expected: execs
[01:51:58]     but: expected to find:
[01:51:58] [..]warning: unused import[..]
[01:51:58] 
[01:51:58] did not find in output:
[01:51:58]     Checking foo v0.0.1 (/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t615/foo)
[01:51:58]       Fixing src/lib.rs (1 fix)
[01:51:58]     Finished dev [unoptimized + debuginfo] target(s) in 0.66s
[01:51:58] ', src/tools/cargo/tests/testsuite/support/mod.rs:794:13
[01:51:58] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:51:58] 
[01:51:58] ---- fix::shows_warnings_on_second_run_without_changes stdout ----
[01:51:58] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo fix --allow-no-vcs`
[01:51:58] thread 'fix::shows_warnings_on_second_run_without_changes' panicked at '
[01:51:58] Expected: execs
[01:51:58]     but: expected to find:
[01:51:58] [..]warning: unused import[..]
[01:51:58] 
[01:51:58] did not find in output:
[01:51:58]     Checking foo v0.0.1 (/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t616/foo)
[01:51:58]       Fixing src/lib.rs (1 fix)
[01:51:58]     Finished dev [unoptimized + debuginfo] target(s) in 0.77s
[01:51:58] ', src/tools/cargo/tests/testsuite/support/mod.rs:794:13
[01:51:58] 
[01:51:58] ---- fix::shows_warnings_on_second_run_without_changes_on_multiple_targets stdout ----
[01:51:58] running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo fix --allow-no-vcs --all-targets`
[01:51:58] thread 'fix::shows_warnings_on_second_run_without_changes_on_multiple_targets' panicked at '
[01:51:58] Expected: execs
[01:51:58]     but: expected to find:
[01:51:58]  --> examples/fooxample.rs:2:21
[01:51:58] 
[01:51:58] did not find in output:
[01:51:58]     Checking foo v0.0.1 (/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t617/foo)
[01:51:58]       Fixing src/lib.rs (1 fix)
[01:51:58]       Fixing tests/foo.rs (1 fix)
[01:51:58]       Fixing tests/bar.rs (1 fix)
[01:51:58]       Fixing src/main.rs (1 fix)
[01:51:58]       Fixing examples/fooxample.rs (1 fix)
[01:51:58]     Finished dev [unoptimized + debuginfo] target(s) in 1.89s
[01:51:58] ', src/tools/cargo/tests/testsuite/support/mod.rs:794:13
[01:51:58] 
[01:51:58] 
[01:51:58] failures:
[01:51:58]     fix::shows_warnings
[01:51:58]     fix::shows_warnings_on_second_run_without_changes
[01:51:58]     fix::shows_warnings_on_second_run_without_changes_on_multiple_targets
[01:51:58] 
[01:51:58] test result: FAILED. 1516 passed; 3 failed; 1 ignored; 0 measured; 0 filtered out
[01:51:58] 
[01:51:58] [0m[0m[1m[31merror:[0m test failed, to rerun pass '--test testsuite'
[01:51:58] 
```

**Comment by pietroalbini** [comment]
Yay, cargo's test suite assumes `unused_imports` is unfixable, a pending fix is in https://github.com/rust-lang/cargo/pull/6649.

**Comment by pietroalbini** [comment]
https://github.com/rust-lang/rust/pull/58358 updating cargo has been merged.

@bors retry

**Pull request merged**
