### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #95292 (Allow specialized const trait impls.)
 - #102049 (Add the `#[derive_const]` attribute)
 - #102701 (Add tier 3 no_std AArch64/x86_64 support for the QNX Neutrino RTOS)
 - #102900 (Don't internalize __llvm_profile_counter_bias)
 - #104105 (llvm: dwo only emitted when object code emitted)
 - #104110 (prevent uninitialized access in black_box for zero-sized-types)
 - #104117 (Mark `trait_upcasting` feature no longer incomplete.)
 - #104137 (Issue error when -C link-self-contained option is used on unsupported platforms)
 - #104144 (Suggest removing unnecessary `.` to use a floating point literal)
 - #104302 (Update cargo)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=95292,102049,102701,102900,104105,104110,104117,104137,104144,104302)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+ p=5 rollup=never

I lied, one more rollup before I let the never queue drain

**Comment by alex** [comment]
This merge seems to contain a PR that was in the last (successful) rollup. Intentional?

**Comment by Manishearth** [comment]
Unintentional. Should work regardless, but since it's so early might as well avoid a gnarly git history.

@bors r-

**Comment by compiler-errors** [comment]
Bors seems confused on this PR -- not showing up on https://bors.rust-lang.org/queue/rust.

@bors retry

**Comment by compiler-errors** [comment]
lol oops, never saw that comment.

**Pull request closed without merging**
