### PR TITLE
An optimization for `pest-2.1.3`

### PR DESCRIPTION
**Pull request by nnethercote**
An easy win I found while looking at a profile of `pest-2.1.3`. It's also a small code cleanup.

r? @pnkfelix

### CODE REVIEW

**Comment by nnethercote** [comment]
Local measurements indicate this won't affect any of the benchmarks in `rustc-perf`, but let's double-check:

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
The only significant changes here are so small (< 0.3% on `many-assoc-items`) that I think it's fine to roll this up.

@bors rollup=always

**Comment by pnkfelix** [comment]
I spent a little while trying to figure out *why* we were passing in an `infcx` in the first place, since clearly this change illustrates that it is currently not necessary. (Was it an artifact of some prior version of the code? Or was a planned enhancement for the future...?)

In the end, though, I couldn't find an answer, and I think that's okay. If it turns out we need `infcx` for some reason, we can thread it down at that time.

**Pull request merged**
