### PR TITLE
Rollup of 10 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #104353 (Add CStr::bytes iterator)
 - #114038 (unix time module now return result)
 - #119676 (rustdoc-search: search types by higher-order functions)
 - #120699 (Document `TRACK_DIAGNOSTIC` calls.)
 - #121899 (Document how removing a type's field can be bad and what to do instead)
 - #122397 (Various cleanups around the const eval query providers)
 - #122405 (Add methods to create StableMIR constant)
 - #122416 (Various style improvements to `rustc_lint::levels`)
 - #122440 (const-eval: organize and extend tests for required-consts)
 - #122461 (fix unsoundness in Step::forward_unchecked for signed integers)

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=104353,114038,119676,120699,121899,122397,122405,122416,122440,122461)

### CODE REVIEW

**Comment by RalfJung** [comment]
Overlaps with https://github.com/rust-lang/rust/pull/122472.
We might need more rollup coordination. :)

**Comment by matthiaskrgr** [comment]
I'll close https://github.com/rust-lang/rust/pull/122472

**Pull request closed without merging**
