### PR TITLE
Stop UI tests if an unknown revision name is specified

### PR DESCRIPTION
**Pull request by tgross35**
There currently isn't anything to let you know that an invalid revision is specified in an error directive like `//[foo,bar,unexpected]~`. Add an error if this happens.

There might be a better place to do this, is there anywhere we validate the test file before running?

### CODE REVIEW

**Comment by tgross35** [comment]
Hm, looks like we use this behavior to disable tests. Is there a better way to mark that specific revisions should be skipped?

A similar check should probably be added to `//@` attributes

**Review by jieyouxu — COMMENTED** [review]
There are mostly two places that deal with directive parsing:

1. `EarlyProps` directive parsing: https://github.com/rust-lang/rust/blob/7106800e16085bf1805cc8e75866ed0f0efd85d9/src/tools/compiletest/src/lib.rs#L762
2. `TestProps` directive parsing: https://github.com/rust-lang/rust/blob/7106800e16085bf1805cc8e75866ed0f0efd85d9/src/tools/compiletest/src/runtest.rs#L127 (note that immediately after generic test prop handling there's also revision-specific test prop handling).

This is currently a mess -- both in terms of parsing / validationg / updating test props and in terms of error handling. I've been meaning to rework this a little but didn't get to it yet.

> Hm, looks like we use this behavior to disable tests. Is there a better way to mark that specific revisions should be skipped?

The proper fix I would think is to either introduce a new directive, something like `skip-revisions: a b c`, or to change the grammar of `revisions` to accept something like `a, !b` where `b` is skipped.

> A similar check should probably be added to //@ attributes

Yes, right now compiletest directive parsing is *super* lenient, but that is not user friendly -- as a test writer, I  *want* to have helpful errors pointing out my tests have unknown revisions etc. The current way directive parsing is setup is split into (I think) three phases: early test prop parsing (for gathering aux builds and revisions), late test prop parsing (for generic non-revisioned directives) and late per-revision test prop parsing (for revisioned directives). I want to say that we really should be unifying the directive parsing, validation and config update to not have these three separate phases because it can let some malformed/unknown revision directives silently slip through.

**Comment by jieyouxu** [comment]
But validations like the one proposed on this PR ought to not be so painful and tricky to add. I feel like we should collect all the directives and error annotations *in one go*, then perform parsing and validations immediately after.

**Comment by jieyouxu** [comment]
I think the long term solution (before `ui_test` migration is viable), is to rework how directives and error annotations are parsed in compiletest to use something like <https://github.com/oli-obk/ui_test/blob/c8e97af5262c7039955d6508fcf1054793f52277/src/parser.rs> (but will probably need various different designs to accomondate the needs of compiletest).

**Comment by jieyouxu** [comment]
Update: we have a tidy check for unknown revisions (implemented by https://github.com/rust-lang/rust/pull/124706) with an `//@ unused-revision-names` escape hatch, which seems like a good interim solution before compiletest's directive handling (especially revisions) are reworked. Should this PR be closed?

**Comment by jieyouxu** [comment]
Closing this PR since it has been addressed by a tidy check, thank you for the PR!

**Comment by tgross35** [comment]
Ah I totally forgot about this one, thank you for the update!

**Pull request closed without merging**
