### PR TITLE
debuginfo: Add GDB pretty printers for slices, Vec<>, and String.

### PR DESCRIPTION
**Pull request by michaelwoerister**
``` rust
Rust:  let slice: &[i32] = &[0, 1, 2, 3];
GDB:   $1 = &[i32](len: 4) = {0, 1, 2, 3}

Rust:  let vec = vec![4, 5, 6, 7];
GDB:   $2 = Vec<u64>(len: 4, cap: 4) = {4, 5, 6, 7}

Rust:  let str_slice = "IAMA string slice!";
GDB:   $3 = "IAMA string slice!"

Rust:  let string = "IAMA string!".to_string();
GDB:   $4 = "IAMA string!"
```

Neat!

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 90fc28d 

Nice!

**Comment by Manishearth** [comment]
:dancers:

**Comment by eddyb** [comment]
I wonder if it would be possible for `&[i32](len: 4)` to be printed as `&[i32; 4]` instead, as if unsizing was being reversed.

**Comment by michaelwoerister** [comment]
@eddyb We could do that but it would be kind of lying about the type, wouldn't it?

**Comment by eddyb** [comment]
I guess... I prefer `{len: 4, cap: 4}` for what it's worth, but that's really unimportant.

**Comment by michaelwoerister** [comment]
> I guess... I prefer {len: 4, cap: 4} for what it's worth, but that's really unimportant.

Yes, I think I'll do some kind of informal poll in the forum about what the actual rendering should look like.

**Pull request merged**
