### PR TITLE
Fix duplicate methods in rustdoc

### LINKED ISSUE #22595: Rustdoc shows duplicate methods
For example size_hint method at http://doc.rust-lang.org/std/str/struct.Chars.html

### PR DESCRIPTION
**Pull request by sanxiyn**
rustdoc impl item did not include default methods for local crates, but did include them for external crates. This resulted in duplicate methods. Fix so that impl item does not include default methods for external crates.

Fix #22595.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
can you make a test? there is some infrastructure for this in `src/test/run-make/rustdoc-*/`, but I haven't investigated too deeply.

**Comment by sanxiyn** [comment]
I couldn't figure out how to test this easily. Maybe file an issue to test this?

**Comment by nikomatsakis** [comment]
what makes it hard to test exactly?

**Comment by sanxiyn** [comment]
htmldocck.py can test for one or more occurences, but can't test for exactly one occurence at the moment. I can implement that and then test this. I will try that tomorrow.

**Comment by sanxiyn** [comment]
Added a test.

**Comment by alexcrichton** [comment]
@bors: r+ 6958463

Nice!

**Pull request merged**
