### PR TITLE
Stabilize self_in_typedefs feature

### PR DESCRIPTION
**Pull request by alexreg**
[**Tracking Issue**](https://github.com/rust-lang/rust/issues/49303)

r? @centril

### CODE REVIEW

**Comment by Centril** [comment]
This one will have to wait a bit until we're a bit into the FCP (not started yet) of that PR.

**Review by Centril — APPROVED** [review]
Pending FCP, the changes look good.

**Review by Centril — APPROVED** [review]

**Comment by Centril** [comment]
@bors r+ 

FCP hasn't completed yet but since we close to the master=>beta deadline I'd like to avoid backports so let's land this now. The RFC was rather uncontroversial and since the PR is small we can back out in beta if FCP doesn't complete for some reason.

**Comment by alexreg** [comment]
@pietroalbini Why did this get removed from roll-up, my I ask?

**Pull request merged**
