### PR TITLE
Use verbatim paths by default

### PR DESCRIPTION
**Pull request by tbu-**
This enables users of the Rust standard library to ignore the limit of 260
"characters" per file name – instead the new limit is around 32K "characters".

See also "Naming Files, Paths, and Namespaces" on MSDN, section "Maximum Path
Name Limitations":
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

In order to use verbatim paths, the following conversions are performed:
- `C:\` -> `\\?\C:\`.
- `\\server\share\` -> `\\?\UNC\server\share\`.
- `..` are evaluated by popping the last component.
- `.` are dropped.
- Relative paths are joined with `os::current_dir` (Special case: Path name is
  along the lines of `C:foobar`. This is a relative path if the current
  directory is on drive `C:`, otherwise it's an absolute path).

### CODE REVIEW

**Comment by tbu-** [comment]
Example of a program that doesn't work before, but works afterwards:

    use std::fs;
    use std::iter;
    use std::path::PathBuf;
     
    fn main() {
        let mut path = PathBuf::new();
        let long_string: String = iter::repeat("a").take(128).collect();
        for i in 0..10 {
            path.push(&long_string);
            println!("creating {}", i);
            fs::create_dir(&path).unwrap();
        }
        for i in (0..10).rev() {
            println!("removing {}", i);
            fs::remove_dir(&path).unwrap();
            path.pop();
        }
    }

**Comment by alexcrichton** [comment]
Out of curiosity, is there precedent for this in other I/O libraries? In general I think it's quite valuable that we perform 0 interpretation of the path coming into these APIs and allow the underlying system APIs to interpret them however they'd like. In the past any sort of layering we add on top inevitably breaks some obscure case in some API, so just passing everything through seems like the best option.

**Comment by tbu-** [comment]
> Out of curiosity, is there precedent for this in other I/O libraries?

I don't know – haven't looked it up, although I couldn't find something with a quick google search.

> In general I think it's quite valuable that we perform 0 interpretation of the path coming into these APIs and allow the underlying system APIs to interpret them however they'd like. In the past any sort of layering we add on top inevitably breaks some obscure case in some API, so just passing everything through seems like the best option.

It's pretty hard to say something to that, as this is pretty hand-wavy – the pull request is not adding it to all functions, but rather it can be reviewed on a case-by-case basis for each function by looking at its documentation. I think we already do some kind of normalization already, namely stripping empty path components (?).

**Comment by tbu-** [comment]
Documentation of the functions, in order of appearance in the source code:
[CreateFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx)
[CreateDirectory](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363855(v=vs.85).aspx)
[FindFirstFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364418(v=vs.85).aspx)
[DeleteFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363915(v=vs.85).aspx)
[MoveFileEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240(v=vs.85).aspx)
[RemoveDirectory](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365488(v=vs.85).aspx)
[CreateSymbolicLink](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363866(v=vs.85).aspx)
[CreateHardLink](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363860(v=vs.85).aspx)
[GetFileAttributesEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364946(v=vs.85).aspx)
[SetFileAttributes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365535(v=vs.85).aspx)
[CopyFileEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363852(v=vs.85).aspx)

All these functions (except for the link functions) are documented with:
>In the ANSI version of this function, the name is limited to <b>MAX_PATH</b> characters. To extend this limit to 32,767 wide characters, call the Unicode version of the function and prepend "\\\\?\" to the path. For more information, see [Naming Files, Paths, and Namespaces](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx).

This means the official documentation recommends using these "\\\\?\" in order to get around the `MAX_PATH` limitation.

The `CreateSoftLink` function will need to be special cased to allow a strictly-relative path to pass through, as it's documented that these behave different. Non-strictly-relative paths, like `C:foobar` are still expanded using the current working directory though (as specified in the documentation).

**Comment by retep998** [comment]
After doing some testing locally, it appears that `..` in a path on Windows completely disregards symbolic links and just removes the previous component. Also Windows is able to handle verbatim paths that have symbolic links in them just fine. As well I am unable to create files named `.` or `..`, even using verbatim paths. Therefore I am under the impression that this technique of simple text manipulation to strip `.` and `..` should work perfectly fine. However, I do think this should be factored out into two public unstable methods, one to make a path absolute, and another to normalize a path.

**Comment by tbu-** [comment]
@retep998 Yea, I also read that Windows just normalizes the paths before passing them to the file system.

I guess we can create public APIs once this has landed.

**Comment by alexcrichton** [comment]
I agree that it's kinda annoying to deal with path length restrictions on Windows, but I'm pretty uneasy about forging ahead here without any prior art. These sorts of conversions have historically been always wrong in one way or another for us, hence our strategy in `std::io` of binding as close to the system as possible *everywhere*.

I think it may be best to develop this sort of functionality externally on crates.io first and see how it plays out before moving it into the standard library to happen by default.

**Comment by tbu-** [comment]
Closing for now I guess (as a reminder, if this is to be adopted, fix the CreateSymbolicLink function).

**Pull request closed without merging**
