### PR TITLE
Fix SGX CI

### PR DESCRIPTION
**Pull request by jethrogb**
Broken in #79038

### CODE REVIEW

**Comment by jethrogb** [comment]
Please r-, this doesn't work

**Comment by jethrogb** [comment]
@Mark-Simulacrum ping for review

**Comment by Mark-Simulacrum** [comment]
@bors r+

Sorry, missed the push

**Comment by camelid** [comment]
> Please r-, this doesn't work

@jethrogb FYI, I think the author of a PR has permissions to `r-`.

**Pull request merged**
