### PR TITLE
Remove `LLVMRustCoverageHashCString`

### PR DESCRIPTION
**Pull request by Zalathar**
Coverage has two FFI functions for computing the hash of a byte string. One takes a ptr/len pair (`LLVMRustCoverageHashByteArray`), and the other takes a NUL-terminated C string (`LLVMRustCoverageHashCString`).

But on closer inspection, the C string version is unnecessary. The calling-side code converts a Rust `&str` into a `CString`, and the C++ code then immediately turns it back into a ptr/len string before actually hashing it. So we can just call the ptr/len version directly instead.

---

This PR also fixes a bug in the C++ declaration of `LLVMRustCoverageHashByteArray`. It should be `size_t`, since that's what is declared and passed on the Rust side, and it's what `StrRef`'s constructor expects to receive on the callee side.

### CODE REVIEW

**Comment by Zalathar** [comment]
I've tested this locally in two ways:

- Before removing the function, I added an assert to verify that both functions give the same result, then ran `x test run-coverage`.
- After switching to just one function, I deliberately corrupted the hash result (via a bitwise not), and ran `x test run-coverage` again to verify that this causes the tests to fail (since `llvm-cov` complains about malformed profile data).

**Comment by Zalathar** [comment]
I noticed that the string being hashed also doesn't need to be cloned with `to_string`, so I've fixed that as well (since it doesn't commute with the rest of this PR).

**Review by b-naber — APPROVED** [review]

**Comment by b-naber** [comment]
Looks spurious.

@bors r+ rollup

**Pull request merged**
