### PR TITLE
Add `mem::{take, replace, swap}` to the prelude

### PR DESCRIPTION
**Pull request by Amanieu**
This adds the following 3 functions from `core::mem` to the prelude:
```rust
fn replace<T>(dest: &mut T, src: T) -> T;
fn take<T: Default>(dest: &mut T) -> T;
fn swap<T>(x: &mut T, y: &mut T);
```

The main goal is to make Rust easier to teach, while also making common code patterns easier to write. Many new Rust users coming from other languages find Rust's ownership system hard to use and a part of that is because it does not allow leaving values in an uninitialized state after moving them, even temporarily. While the tools to work around this are available in `core::mem`, they are not very discoverable for new users. By treating these functions more like keywords (similar to `drop`), we can encourage the inclusion of these functions in teaching materials and expose new Rust users to them.

These 3 functions are also very widely used in production Rust code so even experienced Rust users will benefit from this change. For example, in the Rust compiler there are:
- 74 uses of `mem::replace`.
- 94 uses of `mem::take`.
- 17 uses of `mem::swap`.

### CODE REVIEW

**Comment by jdonszelmann** [comment]
As an educator, I can definitely see the value here. I think people tend to forget these functions, buried in `std::mem`, while talking about them gives (I think) a lot of insight into how ownership and moving works.

**Comment by flip1995** [comment]
Not a blocker, but I personally like to prefix those functions with `mem::`. As those are pretty common function names, it's nice to have the context from where they are from. But YMMV.

**Comment by workingjubilee** [comment]
We shouldn't do this.

[ptr::replace](https://doc.rust-lang.org/nightly/std/ptr/fn.replace.html) and [ptr::swap](https://doc.rust-lang.org/nightly/std/ptr/fn.swap.html) exist, and there are proposals to allow importing type-qualified or trait-qualified functions to use directly, in lieu of having additional free functions.

If such happens, the fact that `replace` and `swap` are common function names on types provide the opportunity for additional confusion.

**Comment by tgross35** [comment]
Prior art, adding `std::{mem, fmt}` was proposed in [RFC3090](https://github.com/rust-lang/rfcs/pull/3090). Some dicsussion specific to those modules at https://github.com/rust-lang/rfcs/pull/3090#discussion_r583972048

**Comment by Lee-Janggun** [comment]
I personally actively avoid importing `mem` functions so that when I use them, I am sure this is **the** `mem` functions, and I don't have to consider the possibility it is some other function, e.g., Option::take. Of course, associated functions are typically used with the `struct.function()` syntax, but I would much rather keep these explicit. I do use drop as just `drop(x)`, but I think the wording of drop in highlighted enough in rust that this is no ambiguity.

**Comment by jhpratt** [comment]
> I personally like to prefix those functions with `mem::`. As those are pretty common function names

This is the case for myself and countless others as well. If anything, I would like to see `core::mem`/`std::mem` added to the prelude. Unless I'm mistaken this was discussed in the run-up to the 2021 edition.

For what it's worth, I'm not positive the compiler is _currently_ able to handle the name resolution shadowing for modules the same way it can for functions. I say this because there are not currently any modules in the prelude.

**Comment by Amanieu** [comment]
Given the feedback (which I agree with!), I'm going to close this PR.

**Pull request closed without merging**
