### PR TITLE
Implement Debug for ptr::Shared and ptr::Unique.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/46755.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
I don't think wrapping these in `Unique(...)` and `Shared(...)` adds value, but adds a lot of noise if you have `Vec<Shared<T>>` for example. I would prefer to print them as just the pointer value, `Debug::fmt(&self.as_ptr(), f)`. @bluss flagged this as well in https://github.com/rust-lang/rust/pull/32054 (expand the outdated comments on src/libcore/ptr.rs).

**Comment by SimonSapin** [comment]
Printing just the pointer sounds good to me.

**Comment by sfackler** [comment]
👍 to just printing the pointer.

**Comment by frewsxcv** [comment]
you all have spoken
the implementation will
now print the pointer

**Comment by frewsxcv** [comment]
merge conflicts addressed

**Comment by kennytm** [comment]
This is going to conflict with #46952 which removed Unique and renamed Shared to NonNull.

**Comment by SimonSapin** [comment]
I can merge this in #46952, if that helps.

**Comment by frewsxcv** [comment]
closing in favor of https://github.com/rust-lang/rust/pull/46952

**Pull request closed without merging**
