### PR TITLE
Rollup of 9 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #65776 (Rename `LocalInternedString` and more)
 - #65973 (caller_location: point to macro invocation sites, like file!/line!, and use in core::panic!.)
 - #66015 (librustc_lexer: Refactor the module)
 - #66062 (Configure LLVM module PIC level)
 - #66086 (bump smallvec to 1.0)
 - #66092 (Use KERN_ARND syscall for random numbers on NetBSD, same as FreeBSD.)
 - #66103 (Add target thumbv7neon-unknown-linux-musleabihf)
 - #66133 (Update the bundled `wasi-libc` repository)
 - #66139 (use American spelling for `pluralize!`)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
#65776 was marked with `rollup=never`...

**Comment by Centril** [comment]
I know; I overrode that after talking to @estebank.

**Comment by RalfJung** [comment]
Something in this rollup broke compiling libstd with xargo on Windows. [We now get](https://github.com/rust-lang/miri/pull/1041):
```
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\appveyor\\AppData\\Local\\rust-lang\\miri\\cache\\HOST\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.0.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.1.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.10.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.11.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.12.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.13.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.14.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.15.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.2.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.3.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.4.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.5.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.6.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.7.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.8.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.std.9frsuiy7-cgu.9.rcgu.o" "/OUT:C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.dll" "/DEF:C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\lib.def" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.2qzihvbkmjhq7pfa.rcgu.o" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.4f5mgpkh8dli7sc3.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps" "/LIBPATH:C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\release\\deps" "/LIBPATH:C:\\Users\\appveyor\\AppData\\Local\\rust-lang\\miri\\cache\\HOST\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\libpanic_unwind-275f615d9b39f3f1.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\libhashbrown-590ae4c0395f691e.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\librustc_std_workspace_alloc-3d6a7ba205ab520a.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\libbacktrace-00e9a9ccf2272490.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\librustc_demangle-baf1d7d5cac013c3.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\libunwind-bf411db0c0e3a904.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\libcfg_if-dbb439db3e845984.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\liblibc-40cce4e31e001aba.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\liballoc-d04d3bd41898dd94.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\librustc_std_workspace_core-dea927fe85ff3b02.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\libcore-ea34e7f78ace01ca.rlib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustcuPQ9c1\\libcompiler_builtins-37c094553672d784.rlib" "msvcrt.lib" "/DLL" "/IMPLIB:C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\xargo.4aGLo778seq6\\target\\x86_64-pc-windows-msvc\\release\\deps\\std.dll.lib"
  = note:    Creating library C:\Users\appveyor\AppData\Local\Temp\1\xargo.4aGLo778seq6\target\x86_64-pc-windows-msvc\release\deps\std.dll.lib and object C:\Users\appveyor\AppData\Local\Temp\1\xargo.4aGLo778seq6\target\x86_64-pc-windows-msvc\release\deps\std.dll.exp
          libcompiler_builtins-37c094553672d784.rlib(compiler_builtins-37c094553672d784.compiler_builtins.1coylv34-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol __sync_val_compare_and_swap_16 referenced in function __llvm_memcpy_element_unordered_atomic_16
          libcompiler_builtins-37c094553672d784.rlib(compiler_builtins-37c094553672d784.compiler_builtins.1coylv34-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol __sync_lock_test_and_set_16 referenced in function __llvm_memcpy_element_unordered_atomic_16
          C:\Users\appveyor\AppData\Local\Temp\1\xargo.4aGLo778seq6\target\x86_64-pc-windows-msvc\release\deps\std.dll : fatal error LNK1120: 2 unresolved externals
          
error: aborting due to previous error
error: could not compile `std`.
```

**Comment by RalfJung** [comment]
The weirdest part is that rustc's tools builder still builds libstd in xargo on Windows just fine. But in Miri's CI, we get these odd linking failures.

Cc @alexcrichton for compiler_builtins and Windows knowledge...

**Comment by RalfJung** [comment]
Turns out [macOS is affected, too](https://travis-ci.com/rust-lang/miri/jobs/254453035?utm_medium=notification&utm_source=email).

```
error: linking with `cc` failed: exit code: 1

  |

  = note: "cc" "-m32" "-L" "/Users/travis/Library/Caches/org.rust-lang.miri/lib/rustlib/i686-apple-darwin/lib" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.0.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.1.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.10.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.11.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.12.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.13.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.14.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.15.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.2.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.3.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.4.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.5.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.6.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.7.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.8.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.std.8sfdv10m-cgu.9.rcgu.o" "-o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/libstd.dylib" "-Wl,-exported_symbols_list,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/list" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.2lg0awms1xbqknxx.rcgu.o" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps/std.4i86n2lmpfdbpci3.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/deps" "-L" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/release/deps" "-L" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/xargo.hwyVdmi27hf6/target/i686-apple-darwin/release/build/backtrace-sys-e15093736628d2c1/out" "-L" "/Users/travis/Library/Caches/org.rust-lang.miri/lib/rustlib/i686-apple-darwin/lib" "-lSystem" "-lresolv" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libpanic_unwind-574d9f2b20722c6c.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libhashbrown-8c9410f43c34c375.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/librustc_std_workspace_alloc-0a921424f3e15b5f.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libbacktrace-8630f1fe1b083f0a.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/librustc_demangle-844493b74214a800.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libunwind-0bbc6edf26ee0820.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libcfg_if-f2ef1f45d53b2bd2.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/liblibc-16470196836e92e2.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/liballoc-cdac88354d321e5c.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/librustc_std_workspace_core-d76be33b42b0f265.rlib" "-Wl,-force_load" "-Wl,/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libcore-f92fb94d33fd15c9.rlib" "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libcompiler_builtins-cb06eb4f5cb108d6.rlib" "-lc" "-lm" "-dynamiclib" "-Wl,-dylib"

  = note: ld: warning: cannot export hidden symbol compiler_builtins::mem::memcpy::h1f97dfde851c02dc from /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libcompiler_builtins-cb06eb4f5cb108d6.rlib(compiler_builtins-cb06eb4f5cb108d6.compiler_builtins.crtnmu5o-cgu.5.rcgu.o)

          ld: warning: cannot export hidden symbol compiler_builtins::mem::memmove::h870d040713cf2ddf from /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/rustcucaNs8/libcompiler_builtins-cb06eb4f5cb108d6.rlib(compiler_builtins-cb06eb4f5cb108d6.compiler_builtins.crtnmu5o-cgu.5.rcgu.o)
[...]
```

Both Windows and macOS can't find (some) compiler_builtins symbols when linking. But on Linux things work fine. Hu?

**Comment by RalfJung** [comment]
Turns out even a PR that does nothing triggers this failure: https://github.com/rust-lang/miri/pull/1042

So something else changed elsewhere.

**Pull request merged**
