### PR TITLE
rustdoc: re-sugar more cross-crate trait bounds

### LINKED ISSUE #77763: Inconsistently documented constraints for IntoIterator::Item
The documentation for `IntoIterator` is inconsistent in how it shows the `Item` constraints.

The actual trait declaration looks like this:

```rust
pub trait IntoIterator {
    type Item;
    type IntoIter: Iterator<Item = Self::Item>;
    fn into_iter(self) -> Self::IntoIter;
}
```

The [nightly `core` documentation](https://doc.rust-lang.org/nightly/core/iter/trait.IntoIterator.html) matches this declaration as of 1.49.0-nightly (3525087ad 2020-10-08). This is good.

However, the [nightly `std` documentation](https://doc.rust-lang.org/nightly/std/iter/trait.IntoIterator.html) shows no `Item` constraints at all:

```rust
pub trait IntoIterator {
    type Item;
    type IntoIter: Iterator;
    fn into_iter(self) -> Self::IntoIter;
}
```

The [`std` documentation for 1.48.0-beta.2](https://doc.rust-lang.org/beta/std/iter/trait.IntoIterator.html) is even weirder, using an equality constraint that's not supported (#20041), and this goes all the way back to [1.0.0](https://doc.rust-lang.org/1.0.0/std/iter/trait.IntoIterator.html).

```rust
pub trait IntoIterator
where
    <Self::IntoIter as Iterator>::Item == Self::Item,
{
    type Item;
    type IntoIter: Iterator;
    fn into_iter(self) -> Self::IntoIter;
}
```

### LINKED ISSUE #84579: Rustdoc does not show bounds on associated items in the declaration of re-exported traits
Currently on nightly the declaration for `IntoIterator` looks like:

image

While the actual declaration with attributes stripped is:

```rust
pub trait IntoIterator {
    type Item;
    type IntoIter: Iterator<Item = Self::Item>;
    fn into_iter(self) -> Self::IntoIter;
}
```

Previously up till 1.48.0 this rendered as:

image

Which is not _great_, but at least it has the information there. I tried to identify the PR which changed this in 1.49.0, but skimming the list from a few search queries none of them stood out to me.

### LINKED ISSUE #102142: Rustdoc makes trait bounds with associated types overly verbose
### Location

https://doc.rust-lang.org/std/future/trait.IntoFuture.html

https://doc.rust-lang.org/std/iter/trait.IntoIterator.html

### Summary

The definition of the `IntoFuture` trait looks like:

```rust
pub trait IntoFuture {
    type Output;
    type IntoFuture: Future<Output = Self::Output>;
    fn into_future(self) -> Self::IntoFuture;
}
```

Rustdoc renders this as:

```rust
pub trait IntoFuture {
    type Output;
    type IntoFuture: Future
    where
        <Self::IntoFuture as Future>::Output == Self::Output;
    fn into_future(self) -> Self::IntoFuture;
}
```

This makes the trait bound for the `IntoFuture` associated type verbose and cryptic.

### PR DESCRIPTION
**Pull request by fmease**
Previously, we would only ever re-sugar cross-crate predicates like `Type: Trait, <Type as Trait>::Name == Rhs` to `Type: Trait<Name = Rhs>` if the `Type` was a generic parameter like `Self` or `T`. With this PR, `Type` can be any type.

Most notably, this means that we now re-sugar predicates involving associated types (where `Type` is of the form `Self::Name`) which are then picked up by the pre-existing logic that re-sugars them into bounds. As a result of that, the associated type `IntoIter` of `std`'s `IntoIterator` trait (re-exported from `core`) is no longer rendered as:

```rust
type IntoIter: Iterator
where
    <Self::IntoIter as Iterator>::Item == Self::Item;
```

but as one would expect: `type IntoIter: Iterator<Item = Self::Item>;`.

Cross-crate closure bounds like `F: Fn(i32) -> bool` are now also rendered properly (previously, the return type (`Self::Output`) would not be rendered and we would show the underlying equality predicate).

Fixes #77763.
Fixes #84579.
Fixes #102142.

@rustbot label T-rustdoc A-cross-crate-reexports
r? rustdoc

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks really good! Please ping me once you have some answers about the empty `param_bounds`.

**Comment by fmease** [comment]
I've changed my mind. I think it's better if we merge this PR as-is leaving the `FIXME(fmease)`s (whose contents I've updated in the most recent commit) for follow-up PRs. This PR is small & uncontroversial and you have already approved it.

On the other hand, the HRTB fix is *slightly* more involved (although not *that* much more). I am going to submit the first follow-up PR within the next few hours or so.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Then let's go!

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
Sounds like a good idea. I'm +1 for this.

cc @rust-lang/rustdoc

**Pull request merged**
