### PR TITLE
Add edition configuration to compiletest

### PR DESCRIPTION
**Pull request by llogiq**
This allows the compiletest configuration to set a default edition that can still be overridden with header annotations. Doing this will make it far easier for clippy to get our tests to the newest edition.

r? @Manishearth

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by llogiq** [comment]
@Manishearth did you mean to r+?

**Comment by Manishearth** [comment]
@llogiq nah because I wanted to check again on desktop

important note: clippy uses https://github.com/Manishearth/compiletest-rs . I'd love to share compiletest with that of rustc but that has been hard to make happen.

**Comment by llogiq** [comment]
@Manishearth should I push the same PR to compiletest-rs?

**Comment by Manishearth** [comment]
Yes please

**Comment by Mark-Simulacrum** [comment]
> The reason is we want to use the new edition for all of our tests and writing an edition header in 548 files gets old rather quickly.

Yes, but I'm asking why you have that goal. Happy to be pointed at PR/issue comments.

**Comment by Manishearth** [comment]
We could do it manually too

**Comment by Mark-Simulacrum** [comment]
That issue does not have justification for *why* you want that. I'm asking because that reasoning may be useful for rustc itself, but I haven't seen it yet - that issue just states the fact...

**Pull request merged**
