### PR TITLE
[CI] Rollup of 5 pull requests

### PR DESCRIPTION
**Pull request by Centril**
Successful merges:

 - #62140 (ci: Turn off PR builds on Travis)
 - #62141 (ci: Disable assertions in PR builds)
 - #62142 (ci: Switch official `try` builds to happen on Azure)
 - #62143 (ci: Publish toolstate changes from Azure)
 - #62145 (ci: Sync AppVeyor/Travis with Azure configuration)

Failed merges:

r? @ghost

### CODE REVIEW

**Comment by Centril** [comment]
@bors r+ p=1000 rollup=never

**This is a CI only r0llup**

**Comment by Centril** [comment]
Seems the failure wasn't spurious after all as Alex noted on Discord.
RLS toolstate fails for some reason.

**Comment by alexcrichton** [comment]
er oops that was 30s too late, sorry!

**Comment by alexcrichton** [comment]
@bors: treeclosed-

I'm merging this manually. [One builder is still running](https://dev.azure.com/rust-lang/rust/_build/results?buildId=1731), `test-various`, which is exhibiting a spurious failure of a hanging test seen previously in our test suite.

**Pull request merged**
