### PR TITLE
Emit JSON output for the building of bootstrap itself

### LINKED ISSUE #107832: `x check --json-output` doesn't use JSON output for building bootstrap itself
```
PS C:\Users\Joshua Nelson\src\rust> x c --json-output
Building bootstrap
   Compiling bootstrap v0.0.0 (C:\Users\Joshua Nelson\src\rust\src\bootstrap)
    Finished dev [unoptimized] target(s) in 8.45s
extracting C:\Users\Joshua Nelson\src\rust\build\cache\319b88c463fe6f51bb6badbbd3bb97252a60f3a5\rust-std-nightly-x86_64-pc-windows-msvc.tar.xz to C:\Users\Joshua Nelson\src\rust\build\x86_64-pc-windows-msvc\ci-rustc
extracting C:\Users\Joshua Nelson\src\rust\build\cache\319b88c463fe6f51bb6badbbd3bb97252a60f3a5\rustc-nightly-x86_64-pc-windows-msvc.tar.xz to C:\Users\Joshua Nelson\src\rust\build\x86_64-pc-windows-msvc\ci-rustc
extracting C:\Users\Joshua Nelson\src\rust\build\cache\319b88c463fe6f51bb6badbbd3bb97252a60f3a5\rustc-dev-nightly-x86_64-pc-windows-msvc.tar.xz to C:\Users\Joshua Nelson\src\rust\build\x86_64-pc-windows-msvc\ci-rustc
extracting C:\Users\Joshua Nelson\src\rust\build\cache\319b88c463fe6f51bb6badbbd3bb97252a60f3a5\rust-src-nightly.tar.xz to C:\Users\Joshua Nelson\src\rust\build\x86_64-pc-windows-msvc\ci-rustc
Checking stage0 library artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
   Compiling compiler_builtins v0.1.85
    Checking core v0.0.0 (C:\Users\Joshua Nelson\src\rust\library\core)
   Compiling libc v0.2.138
   Compiling cc v1.0.77
   Compiling memchr v2.5.0
   Compiling std v0.0.0 (C:\Users\Joshua Nelson\src\rust\library\std)
{"reason":"compiler-artifact","package_id":"libc 0.2.138 (registry+https://github.com/rust-lang/crates.io-index)","manifest_path":"C:\\Users\\Joshua Nelson\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libc-0.2.138\\Cargo.toml","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"C:\\Users\\Joshua Nelson\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libc-0.2.138\\build.rs","edition":"2015","doc":false,"doctest":false,"test":false},"profile":{"opt_level":"0","debuginfo":0,"debug_assertions":false,"overflow_checks":false,"test":false},"features":["align","rustc-dep-of-std","rustc-std-workspace-core"],"filenames":["C:\\Users\\Joshua Nelson\\src\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\release\\build\\libc-aff1973d4fdf7f57\\build-script-build.exe","C:\\Users\\Joshua Nelson\\src\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\release\\build\\libc-aff1973d4fdf7f57\\build_script_build.pdb"],"executable":null,"fresh":false}
```
I think this is one of the reasons (maybe not the only one?) that introducing a build failure in src/bootstrap means that rust-analyzer doesn't show red squigglies in the IDE.

Mentoring instructions: add a new `--json-output` flag to bootstrap.py around https://github.com/rust-lang/rust/blob/3666fa080050594ab3ad26255c069e4d2000a3f4/src/bootstrap/bootstrap.py#L841 and pass `--message-format json` to cargo around https://github.com/rust-lang/rust/blob/3666fa080050594ab3ad26255c069e4d2000a3f4/src/bootstrap/bootstrap.py#L778-L788 if it's set.

### PR DESCRIPTION
**Pull request by zephaniahong**
Fixes #107832 .
Main changes are from line 792 onwards. Other changes are due to the flake8 formatter. Let me know if I should not use the formatter.

### CODE REVIEW

**Comment by zephaniahong** [comment]
Hi @albertlarsan68 ! Could I get some advice on how to use git for this case?
What I've tried is to git reset --hard to the original head (before I made any changes). then make my new changes and commit them and try to push it to github. But I'm unable to push as my local branch will be behind github. It then suggests that I pull the code from github but then that would mean I'm back to square one.

The other thought I had was just to manually remove all the formatting that has occurred but I'm sure that there is a smarter way. 

Thank you!

**Comment by jyn514** [comment]
@zephaniahong out of curiosity, have you tested whether this fixes rust-analyzer on bootstrap when it doesn't compile?

**Comment by zephaniahong** [comment]
Yupp! Works for me😊

**Comment by albertlarsan68** [comment]
Thanks for your PR!
@bors r+

**Pull request merged**
