### PR TITLE
std: Consider directory junctions as directories

### LINKED ISSUE #26716: fs::create_dir_all fails for directory junctions on Windows
First reported in https://github.com/rust-lang/cargo/issues/1749, it looks like if an intermediate directory is a junction on Windows then `fs::create_dir_all` will fail. Unfortunately the standard library doesn't provide away to create a junction, but a setup like this should work:

```sh
mkdir foo
mklink /J bar foo
```

```rust
use std::fs;
fs::create_dir_all("bar/test").unwrap() // this fails
```

### PR DESCRIPTION
**Pull request by alexcrichton**
Previously on Windows a directory junction would return false from `is_dir`,
causing various odd behavior, specifically calls to `create_dir_all` might fail
when they would otherwise continue to succeed.

Closes #26716

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @retep998

**Comment by brson** [comment]
@bors r+

dammit windows

**Comment by retep998** [comment]
Sorry for the merge conflicts :stuck_out_tongue:

**Pull request merged**
