### PR TITLE
Add impls for powers of 2 length arrays.

### PR DESCRIPTION
**Pull request by richard-uk1**
It would be really nice if there could be more array impls. I know that const generics are coming, but this would allow me to avoid having to write a lot of these impls myself, which would save me a lot of time, and make the eventual conversion to const generics a zero-work job for me. :)

I'm just submitting this as a PR because the change is so small, it's the same amount of effort as writing an issue.

### CODE REVIEW

**Comment by alex** [comment]
See also #51318 :-)

**Comment by derekdreery** [comment]
I'm tempted to close this since I'm happy to just start using const generics on nightly when they land.

Totally more excited about them than rust 2018 :)

**Comment by derekdreery** [comment]
I've made a crate to implement the traits I need for newtypes (basically by copying the macro in the rust source). It's on [crates.io]. So for me I'm happy using this because it means I can continue to support stable, but I'll leave this open in case someone else wants, I don't need it any more though.

[crates.io]: https://crates.io/crates/newtype_array

**Comment by cramertj** [comment]
cc @rust-lang/libs -- what's the current policy on extending these array impls?

**Comment by alexcrichton** [comment]
Historically the libs team has [decided to not change what we have](https://github.com/rust-lang/rust/pull/29395#issuecomment-155965986), although it's been awhile so we can revisit this decision during the next triage meeting as well.

**Comment by alexcrichton** [comment]
Ok the libs team discussed this yesterday and have reached the [same conclusion as before](https://github.com/rust-lang/rust/pull/29395#issuecomment-155965986), so I'm going to close this. Thanks regardless thoug hfor the PR @derekdreery !

**Pull request closed without merging**
