### PR TITLE
[EXPERIMENT] Forbid derive attributes on invalid targets

### PR DESCRIPTION
**Pull request by Aaron1011**
cc https://github.com/rust-lang/rust/issues/78331

Based on https://github.com/rust-lang/rust/pull/78326

Opening for a Crater run

### CODE REVIEW

**Comment by Aaron1011** [comment]
@craterbot check

**Comment by Aaron1011** [comment]
There's a very small number of actual regressions. I'll open PRs to fix those crates

**Comment by estebank** [comment]
Before landing this change we should at least change the lint to deny by default for a few versions. The change a priori seems significant enough (to me) to be gated on an edition boundary, but the actual impact seems low. (Let's take a look at the ICEs too.)

**Comment by Aaron1011** [comment]
> Before landing this change we should at least change the lint to deny by default for a few versions

I'm fine with doing this, but we'll need to introduce a new lint, since it's currently going through `unused_attributes`.

**Comment by petrochenkov** [comment]
Closing in favor of https://github.com/rust-lang/rust/pull/79078, which does the same thing.

**Comment by petrochenkov** [comment]
I don't think this needs a further deprecation period, this was a warning for very long time and the affected projects are not maintained.

**Pull request closed without merging**
