### PR TITLE
Add singlethreaded fence intrinsics.

### LINKED ISSUE #24118: Implement compiler fences
https://github.com/rust-lang/rfcs/pull/888

### PR DESCRIPTION
**Pull request by tari**
Closes #24118, implementing RFC 888.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 998c10d6b64f9a37d4cab33e09b9dfd551c76b92

Thanks!

**Comment by tari** [comment]
Updated to current snapshot.

**Comment by jonhoo** [comment]
Are there any plans to eventually expose this outside of `intrinsics`? It's vital when writing low-level synchronization code, and given that intrinsics likely won't be stabilized, that basically ties such libraries to nightly-only...

**Comment by alexcrichton** [comment]
@jonhoo I believe not currently, but if you'd like to see these on stable a PR to place them in libstd would be most welcome!

**Comment by jonhoo** [comment]
@alexcrichton Issue: #41091, PR: #41092

**Pull request merged**
