### PR TITLE
Implement bufwriter_raw_buffer feature

### PR DESCRIPTION
**Pull request by tgnottingham**
Tracking issue: #79916

### CODE REVIEW

**Comment by tgnottingham** [comment]
I'll have a write-up for this in a few.

**Comment by tgnottingham** [comment]
Can't resist showing the green:

<details>
<summary><b>Result of switching from unoptimized to optimized BufWriter</b></summary>

bufwriter_unoptimized_vs_optimized
</details>

**Comment by sfackler** [comment]
This seems like a strange API to expose from BufWriter, and whatever you're trying to do in rustc may be better served by a custom type.

**Comment by tgnottingham** [comment]
@sfackler, that's the path I've taken in #80463, and I'm totally fine with it personally.

FWIW, the benefit of being able to use `BufWriter` instead of a custom type would be not having to reimplement `flush` and `drop`. But that isn't enough for me to want to push for the proposed API.

**Comment by sfackler** [comment]
Once the `ReadBuf` type is implemented, I think you could make an interface based off of that which would be a bit cleaner.

**Comment by tgnottingham** [comment]
Thanks @sfackler. Closing this and the tracking issue.

**Pull request closed without merging**
