### PR TITLE
Remove eddyb from miri failure pings

### PR DESCRIPTION
**Pull request by oli-obk**
r? @eddyb

### CODE REVIEW

**Comment by RalfJung** [comment]
Would it make sense to ping @rust-lang/miri instead of individual people? That would keep us in sync with the team membership.

**Comment by oli-obk** [comment]
I considered that, but none of the maintainers mentioned here are teams, so we'll need to check if the python scripts can handle a team name

**Comment by RalfJung** [comment]
Yeah there might be a problem with assigning the issue to a team...
but the assignment is like the least important part of it.^^

**Pull request merged**
