### PR TITLE
New rustdoc lint to respect -Dwarnings correctly

### LINKED ISSUE #79792: rustdoc -D warnings doesn't fail for all warnings
#### I tried this code:

```bash
/// See [`foo:Foo`].
/// ```rust
fn main() {}

```

#### I expected to see this happen:
The env variable `-Dwarnings` is supposed to make rustdoc treat warnings as errors. For `export RUSTDOCFLAGS=""` the run below outputs only warnings, no errors. For `RUSTDOCFLAGS="-Dwarnings"` I would have expected both warnings to now be errors.

```
$ export RUSTDOCFLAGS="-Dwarnings"
$ cargo doc
 Documenting rustdoc-bug v0.1.0 (/tmp/bug/rustdoc-bug)
error: unresolved link to `foo:Foo`
 --> src/main.rs:1:10
  |
1 | /// See [`foo:Foo`].
  |          ^^^^^^^^^ no item named `foo:Foo` in scope
  |
  = note: `-D broken-intra-doc-links` implied by `-D warnings`
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

error: Rust code block is empty
 --> src/main.rs:2:5
  |
2 | /// ```rust
  |     ^^^^^^^

error: aborting due to previous error; 1 warning emitted```
```

#### Instead, this happened:
Only one of the warnings is switched to an error.

```
$ export RUSTDOCFLAGS="-Dwarnings"
$ cargo doc
 Documenting rustdoc-bug v0.1.0 (/tmp/bug/rustdoc-bug)
error: unresolved link to `foo:Foo`
 --> src/main.rs:1:10
  |
1 | /// See [`foo:Foo`].
  |          ^^^^^^^^^ no item named `foo:Foo` in scope
  |
  = note: `-D broken-intra-doc-links` implied by `-D warnings`
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: Rust code block is empty
 --> src/main.rs:2:5
  |
2 | /// ```rust
  |     ^^^^^^^

error: aborting due to previous error; 1 warning emitted```
```

This is also problematic because for warnings the exit code is still `0`, so a CI setup might not detect the failure:

```
$ cat src/main.rs 
/// ```rust
fn main() {}
$ RUSTDOCFLAGS="-Dwarnings" cargo doc
warning: Rust code block is empty
 --> src/main.rs:1:5
  |
1 | /// ```rust
  |     ^^^^^^^

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
$ echo $?
0
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
```

### PR DESCRIPTION
**Pull request by poliorcetics**
This adds a new lint to `rustc` that is used in rustdoc when a code
block is empty or cannot be parsed as valid Rust code.

Previously this was unconditionally a warning. As such some
documentation comments were (unknowingly) abusing this to pass despite
the `-Dwarnings` used when compiling `rustc`, this should not be the
case anymore.

## Todo List

- [x] Declare lint.
- [x] Document lint (file: `src/doc/rustdoc/src/lints.md`).
- [x] Use lint in `rustdoc` (file: `src/librustdoc/passes/check_code_block_syntax.rs`, maybe others).
- [x] Write tests.
- [x] Refactor things.
- [x] Squash into one commit. 

---

Previously was #79816 but I broke the submodules on my side and it was less trouble fixing it with a new PR that cherry-picked the changes.

Fix #79792.

@rustbot label T-rustdoc A-lint
r? @jyn514

### CODE REVIEW

**Comment by petrochenkov** [comment]
Can lints reported by rustdoc be defined entirely in rustdoc without touching `rustc_lint` and other compiler crates?
Clippy does this somehow.

I've been seeing numerous lints of uncertain quality being added to rustdoc in the recent year without any process from the compiler or lang team side, while in theory new lints require lang team RFCs or FCPs.
If they are added by rustdoc team, can they at least be offloaded to entirely into rustdoc?

**Comment by poliorcetics** [comment]
It would certainly be both easier to maintain and less buggy to have everything concentrated in rustdoc but I don't know if it is feasible, I'm especially not knowledgeable about how lints work in the compiler to tell.

I'll try to make something work and report my findings.

**Comment by jyn514** [comment]
@poliorcetics please don't make that change here, I would prefer to do it consistently and not piecemeal.

> Can lints reported by rustdoc be defined entirely in rustdoc without touching rustc_lint and other compiler crates?

I would like to do that but haven't gotten around to it. The main technical issue is that the old lint names will have to be deprecated and renamed; they can't be deleted, because it's not possible to register built-in lints from out-of-tree.

There's also some debate about which lints should belong to rustdoc and which should be part of rustc: https://github.com/rust-lang/rust/pull/77364

> in theory new lints require lang team RFCs or FCPs.

I didn't know that. Is that written down somewhere?

**Comment by poliorcetics** [comment]
Closing this in favour of #79816, see there for more infos.

**Pull request closed without merging**
