### PR TITLE
Add From<bool> for int types

### LINKED ISSUE #46109: From<bool> for integers not implemented?
I would find it incredibly useful to being able to cast a bool to another type so I can shift it around to generate bitmasks but ALAS this is not possible at the moment due to missing From trait impls:
```
error[E0277]: the trait bound `u32: core::convert::From<bool>` is not satisfied
```

Using `as` instead works fine but is frowned upon by clippy if the type is not a bool but a different type instead:
```
warning: casting u16 to u32 may become silently lossy if types change
```

Since the code in question is automatically generated it would be great if there was one common implementation that can (and should) be used for all types.

### PR DESCRIPTION
**Pull request by clarfonthey**
Fixes #46109.

### CODE REVIEW

**Comment by clarcharr** [comment]
Actually, apparently this causes inference issues. That should probably be investigated before this is merged.

**Review by sugar700 — COMMENTED** [review]
```rust
fn try_result_ok() -> Result<u8, u8> {
    let val = Ok(1)?;
    Ok(val)
}
```

`Ok(x)?` for `Result<_, u8>` (as well as variations like `return Err(u8::from(unimplemented!()));`) sound like an edge case for me - I don't think realistically anyone would write code like this. This can be written as `x`, and I think this inference failure is not a practical issue. The test here could be changed to use a type other than `u8`, for example `fn try_result_ok() -> Result<u8, bool>`.

Additionally, according to https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md, this would be a minor change.

**Review by sugar700 — APPROVED** [review]

**Comment by TimNN** [comment]
cc @rust-lang/libs: This has the potential to be inference-breaking. What do you think? Does this need a crater run?

**Comment by SimonSapin** [comment]
The motivation for this seems thin to me. #46109 says that Clippy warns for `as` usage for casting `u16` to `u32`, but how is that related to conversions from `bool`? CC @therealprof

**Comment by therealprof** [comment]
@SimonSapin The motivation for this is automatically generated code by `svd2rust`. Ideally we would like to use `From` for all types but that doesn't work for `bool` so we have to use `as` instead which generates a lot of noise. There alternative would be to special case per type which is also not desirable.

**Comment by clarcharr** [comment]
Also, the main purpose of the lint is that in general, `From` should be used when the conversion is lossless, as `as` allows lossy conversions. This helps in macros and other places to ensure that only lossless conversions occur.

**Comment by alexcrichton** [comment]
Yeah I think it wouldn't hurt to get a crater run for this.

cc @rust-lang/infra, mind scheduling a crater run here?

**Comment by Mark-Simulacrum** [comment]
**Check-only** crater run started.

**Comment by pietroalbini** [comment]
Hi @alexcrichton (crater requester), @TimNN (PR reviewer)! Crater results are at: http://cargobomb-reports.s3.amazonaws.com/pr-50554/index.html. 'Blacklisted' crates (spurious failures etc) can be found [here](https://github.com/rust-lang-nursery/crater/blob/master/config.toml). If you see any spurious failures not on the list, please make a PR against that file.

(interested observers: Crater is a tool for testing the impact of changes on the crates.io ecosystem. You can find out more at the [repo](https://github.com/rust-lang-nursery/crater/) if you're curious)

**Comment by pietroalbini** [comment]
And both of the regressions are spurious `\o/`.

**Comment by TimNN** [comment]
This looks good to go, @clarcharr can you fix the travis failure?

Also cc @rust-lang/libs, I will approve this unless you have any objections.

**Comment by scottmcm** [comment]
Since adding impls is a stabilization, doesn't this need an FCP?

**Comment by clarcharr** [comment]
@TimNN Will do! Although I agree with @scottmcm that this needs an FCP.

**Comment by TimNN** [comment]
> Although I agree with @scottmcm that this needs an FCP.

Sure. I think we can trigger the FCP now?

@rfcbot fcp merge

**Comment by withoutboats** [comment]
@rfcbot fcp merge

**Comment by ithinuel** [comment]
This PR lacks tests to verify the added feature don't break in the future.
An implementation of such tests can be found in #50597.

**Comment by clarcharr** [comment]
@ithinuel I copied the `From`-specific tests from your PR so that that PR can be specifically for tracking the `TryFrom` implementation. Hopefully that is okay.

**Comment by ithinuel** [comment]
@clarcharr Thanks ! I will be able to remove that from my PR once yours land !

**Comment by clarcharr** [comment]
I rebased but there weren't actually any merge conflicts.

**Pull request merged**
