### PR TITLE
Sync in portable-simd subtree

### PR DESCRIPTION
**Pull request by workingjubilee**
r? @ghost

### CODE REVIEW

**Comment by workingjubilee** [comment]
...I got nothin'! I like genuinely have no idea why any of these changes, tbh.

**Comment by pnkfelix** [comment]
All of the regressions here are on doc profiles. I don't think its worth us spending time trying to figure out 1% regressions to rustdoc performance. (And I made a topic for discussing the matter [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/should.20doc.20profile.20have.20a.20higher.20threshold.20for.20reporting.3F/near/291074219).)

Marking as triaged

@rustbot label: +perf-regression-triaged

**Pull request merged**
