### PR TITLE
[do not merge] Test parallel queries

### PR DESCRIPTION
**Pull request by Zoxc**
Let's see if I have more luck

r? @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I was able to do a local perf.rlo run last we week. I'll post the results here if this doesn't succeed.

**Comment by Zoxc** [comment]
@rust-timer build 742d459a2f4b43f27d20871f51d7f2e5894ef574

**Comment by Zoxc** [comment]
No. Are there logs for perf? I'd like to know why it doesn't work. cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Profiling failed, I suspect:

```
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', src/librustc/util/profiling.rs:190:17
```

**Comment by Zoxc** [comment]
@Mark-Simulacrum Why is profiling on? I haven't seen those in any results. It could probably skew the numbers a bit too.

**Comment by wesleywiser** [comment]
I'm confused as well. Profiling was turned off by default in #56170. Is that commit not included for some reason?

**Comment by michaelwoerister** [comment]
We want to collect `-Z self-profile` data on `perf.rlo` at some point. Maybe that's why?

**Comment by wesleywiser** [comment]
Oh, of course. That's it.

**Comment by Zoxc** [comment]
@rust-timer build 80b4e73ec537d4d0092cc4c23289e52d951a3384

**Comment by Zoxc** [comment]
@craterbot run start=master#bcf920fc2707c3f126a2963a686ed800eeea49e6 end=try#80b4e73ec537d4d0092cc4c23289e52d951a3384 mode=build-only

**Comment by michaelwoerister** [comment]
[perf results](https://perf.rust-lang.org/compare.html?start=bcf920fc2707c3f126a2963a686ed800eeea49e6&end=80b4e73ec537d4d0092cc4c23289e52d951a3384&stat=wall-time)

Alright, let's see:
- The results here are identical to what I saw in my local perf run two weeks ago. Good!
- We see some regression for small crates, which can be explained by them not generating much work that can be done in parallel. 
- We see considerable speed ups (10-40%) for non-incremental and empty-cache-incremental builds of all medium to large crates. Excellent!
- There are some slowdowns for incremental cases where there's lots of cache re-use. That's also kind of expect since there, again, is less work that is parallelized.

I suspect that we can get right of some of the regressions by tuning the framework a bit more for those cases. Also, there should be quite a bit of room for improvement for the batch-compilation cases. For example we don't run codegen/trans in parallel at the moment. If queries were threadsafe by default, we hopefully could get rid of the hugely complex scheduling we are doing for the LLVM backend.

Great work, @Zoxc!

cc @rust-lang/wg-compiler-performance

**Comment by mark-i-m** [comment]
So what’s next? If we got rid of some the regressions, could we turn it on by default?

**Comment by Zoxc** [comment]
@rust-timer build f471219a5b5fbeb67206fc6f781d831a5ccea7ae

**Comment by Zoxc** [comment]
`ctfe-stress` doesn't look too good though. cc @oli-obk

**Comment by jonas-schievink** [comment]
@oli-obk The default view sorts by instructions, sort by wall-time instead and the ctfe tests get much slower

**Comment by oli-obk** [comment]
I would have expected incremental to be slower, as decoding large constants can happen to duplicate the work with parallel decoding and then throw away all results but the first one to finish.

I don't know why the non-incremental case is slower. It's not like we're evaluating queries twice, right? Especially weird that wall time would go down. Maybe it's just because evaluating those large constants will run *a lot* of queries (one or two for all the temporary locals that are written to) and I presume that a single query's evaluation time will be slower than before due to extra synchronizations?

Also note that these tests are know to fluctuate by 2-5% all the time. Maybe that fluctuation gets way worse with parallel queries?

**Comment by Zoxc** [comment]
@rust-timer build 89874d865056c6dbdbfc37d09e0e195108cb83d7

**Pull request closed without merging**
