### PR TITLE
update miri

### PR DESCRIPTION
**Pull request by RalfJung**
r? @oli-obk

### CODE REVIEW

**Comment by kennytm** [comment]
@bors r- 

Caused ICE in the test `run-pass\heap_allocator.rs`.

```
error: internal compiler error: src/librustc_mir/interpret/eval_context.rs:139: The type checker should prevent reading from a never-written local
```

**Comment by RalfJung** [comment]
That's odd... we have Windows CI as well on the Miri side and the tests are passing there.  I don't really have any idea what might be causing a different behavior here.

**Comment by RalfJung** [comment]
This is a debug-only-r+ to hopefully get a better idea of what is going on in that Windows CI.

@bors r=oli-obk p=0

**Comment by RalfJung** [comment]
Dang, the Linux test ran first and so we never got to the Windows failure. :/

**Comment by bjorn3** [comment]
```
[...]
_7 = const std::sys::windows::c::HeapFree(move _8, const 0u32, move _9) -> bb5
[...]
_13 = _7 <-- read of uninit var here
```

According to https://docs.microsoft.com/en-us/windows/desktop/api/heapapi/nf-heapapi-heapfree `HeapFree` returns a `BOOL`, but at https://github.com/rust-lang/miri/blob/aaa8ee743bca78d52018a025a525183405b2a1b1/src/fn_call.rs#L737-L742 no result is written.

**Comment by RalfJung** [comment]
Good catch!

That doesn't explain why our own CI does not find this problem, though.

**Comment by RalfJung** [comment]
Probably some flags are different somewhere and hence the MIR is not the same, or so.

**Comment by RalfJung** [comment]
@bors r-

Ah, the futures API got stabilized... but we can't bump that in Miri because of https://github.com/rust-lang/miri/issues/713. So this is now blocked on https://github.com/japaric/xargo/issues/240.

**Comment by RalfJung** [comment]
This should work, finally.

@bors r=oli-obk p=1

**Comment by RalfJung** [comment]
The local CI failure should be fixed by rebasing on top of https://github.com/rust-lang/rust/pull/60156, which bors did.

**Comment by bjorn3** [comment]
This hasnt been pushed to master yet, but #60379 is already testing.

**Pull request merged**
