### PR TITLE
submodules: update clippy from 164310dd to 49ff0d9d

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Changes:
````
Fix breakage due to rust-lang/rust#60913
Fix breakage due to rust-lang/rust#62705
rustup https://github.com/rust-lang/rust/pull/62679/
Update pulldown-cmark to 0.5.3
rustup https://github.com/rust-lang/rust/pull/62764
Format code
Decrease maximum length for stderr files
Improved imports
Fix "unknown clippy lint" error in UI test.
Corrections for PR review.
Implement lint for inherent to_string() method.
UI Test Cleanup: Extract match_ref_pats tests
Update UI tests
Allow no_effect lint
Remove comment
cargo fmt
UI Test Cleanup: Split up checked_unwrap tests
Removed linting on never type.
UI Test Cleanup: Split out out_of_bounds_indexing
false positives fixes of `implicit_return`
````

Fixes clippy toolstate
r? @oli-obk

### CODE REVIEW

**Comment by pietroalbini** [comment]
@bors retry

A VM lost network access apparently?

**Comment by matthiaskrgr** [comment]
Status: this needs https://github.com/rust-lang/rust-clippy/pull/4297 to be included in this pr to work.
I also want to wait out the current rollup in case it breaks clippy again, will check back in the morning.

**Comment by matthiaskrgr** [comment]
update

**Comment by matthiaskrgr** [comment]
Oops, I can't reopen apparently, I'll make a new pr....

**Pull request closed without merging**
