### PR TITLE
interpret: adjust error from constructing an invalid value

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by JohnTitor** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/98557#issuecomment-1166694619
@bors r-

**Comment by RalfJung** [comment]
Ah, that test is only run for release builds so I cannot bless it... let's hope this is right.
@bors r=compiler-errors rollup=iffy

**Comment by RalfJung** [comment]
Rebased to get up-to-date PR CI.
@bors r=compiler-errors

**Pull request merged**
