### PR TITLE
Move slice::exact_chunks directly above exact_chunks_mut for more con…

### PR DESCRIPTION
**Pull request by sdroege**
…sistent docs order

See https://github.com/rust-lang/rust/issues/47115#issuecomment-392532855

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by sdroege** [comment]
Should I rebase this PR or how are you usually handling merge conflicts?

**Comment by sdroege** [comment]
Ah it says `S-waiting-on-author`. Rebased!

**Comment by sdroege** [comment]
This looks unrelated to my changes, openssl sources failed to download.

**Comment by dtolnay** [comment]
Looks like #40474.

@bors retry

**Pull request merged**
