### PR TITLE
Check for frequent types in type folding

### PR DESCRIPTION
**Pull request by JulianKnodt**
I'm not sure if this is a valid or useful perf optimization, but it short circuits calling type folding on a submethod for primitives which should never be folded.

I also added in some other clean up which I found while reading thru the code which I can remove if necessary.

cc: @lcnr

### CODE REVIEW

**Comment by lcnr** [comment]
@bors try @rust-timer queue

we probably don't want to do this in `fold_with`, but it does seem interesting to try and see if this influences perf

**Comment by lcnr** [comment]
I do think there are some gains to be made here, but it looks like that wasn't quite it

**Comment by JulianKnodt** [comment]
Hm yea, seems to be mixed but mostly negative. I wonder if it's because just checking primitive types is not the right strategy, I picked some types I thought would be much more common (specifically adding tuples & adts)

**Comment by JulianKnodt** [comment]
After checking which types are actually passed to the function, I got these counts:
```
6271966 counts:
(  1)  2565953 (40.9%, 40.9%): "infer"
(  2)  1093594 (17.4%, 58.3%): "ref"
(  3)   770893 (12.3%, 70.6%): "adt"
(  4)   455160 ( 7.3%, 77.9%): "uint"
(  5)   301567 ( 4.8%, 82.7%): "int"
(  6)   222642 ( 3.5%, 86.3%): "fn_def"
(  7)   184134 ( 2.9%, 89.2%): "proj"
(  8)   160364 ( 2.6%, 91.7%): "param"
(  9)   135543 ( 2.2%, 93.9%): "tuple"
( 10)    98735 ( 1.6%, 95.5%): "fn_ptr"
( 11)    85819 ( 1.4%, 96.9%): "raw_ptr"
( 12)    45000 ( 0.7%, 97.6%): "slice"
( 13)    37834 ( 0.6%, 98.2%): "array"
( 14)    35012 ( 0.6%, 98.7%): "char"
( 15)    23572 ( 0.4%, 99.1%): "bool"
( 16)    14534 ( 0.2%, 99.3%): "dyn"
( 17)    11749 ( 0.2%, 99.5%): "closure"
( 18)    10760 ( 0.2%, 99.7%): "str"
( 19)    10730 ( 0.2%, 99.9%): "opaque"
( 20)     6494 ( 0.1%,100.0%): "float"
( 21)     1842 ( 0.0%,100.0%): "never"
( 22)       35 ( 0.0%,100.0%): "foreign"
```

**Comment by JulianKnodt** [comment]
Hm, it's still all negative, I'm not quite sure what to do from that then

**Comment by JulianKnodt** [comment]
Seems the results from this are pretty neutral, since the two that changed have low absolute timings so might be subject to randomness.

**Comment by jyn514** [comment]
@JulianKnodt since this didn't have improvements, should it be closed? Or do you still have more ideas for speeding it up?

**Comment by JulianKnodt** [comment]
Ah I'll just close it for now! Thanks for checking in.

**Pull request closed without merging**
