### PR TITLE
Ensure that the source code display is working with DOS backline

### LINKED ISSUE #76361: rustdoc: DOS line endings cause extra newlines to show up in source view
I tried to document and publish my Windows crate to github pages.
Things went pretty smooth until I opened the source code view.
As you can see below, a newline is appended to each line doc comment,
also no line number for each line:

image

Here the render page on gh-pages: <https://lzutao.github.io/junction/src/junction/lib.rs.html#1-111>.
Beware that it has no version control for the generated doc. But the link here may work
for a limited time before github purge the cache: <https://github.com/lzutao/junction/tree/6ab9e37b809afdb49fce1accf943250af6aa5dbf>. Also here the the CI script I used:
<https://github.com/lzutao/junction/blob/724dd2e564c76e4f92580629c2f4a1340875e890/.github/workflows/ci.yml#L62-L95>.

*The same code published on https://docs.rs is normal*: https://docs.rs/junction/0.2.0/src/junction/lib.rs.html#1-111

### Meta

`rustc --version --verbose`: x86_64-pc-windows-msvc rustc 1.48.0-nightly (c59199efc 2020-09-04)

@rustbot modify labels: T-rustdoc

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #76361.

cc @lzutao 
r? @jyn514

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I just wonder about something: should I make this `replace` in the `string` function in the same file instead?

**Comment by jyn514** [comment]
I don't understand why this would fix the problem. Why is `\r\n` currently broken? https://github.com/rust-lang/rust/issues/76361 says that it is but not what's going wrong, I'd rather fix the root cause.

**Comment by GuillaumeGomez** [comment]
You gave me an idea. I'll check it out later.

**Comment by GuillaumeGomez** [comment]
The idea didn't work out unfortunately... So I think the current PR is as good as I can think.

**Comment by jyn514** [comment]
@GuillaumeGomez do you know why `\r\n` currently breaks the rendering in the browser? I think we discussed it on Discord a while ago, but I don't remember the answer.

**Comment by GuillaumeGomez** [comment]
Because "\r\n" is considered as two backlines. :)

**Review by jyn514 — COMMENTED** [review]
r=me with a test added; please make sure it fails before and succeeds after.

**Comment by GuillaumeGomez** [comment]
Add the test.

**Pull request merged**
