### PR TITLE
Reduce verbosity of tracing output of  RUSTC_LOG

### PR DESCRIPTION
**Pull request by jackh726**
The current output is really hard to read, I find, for things like trait selection. I nearly always end up removing these calls locally.

r? @oli-obk since you originally authored this

### CODE REVIEW

**Comment by oli-obk** [comment]
What part is unreadable to you? The duplication when you enter and immediately enter a nested one?

In longer chains it can sometimes be helpful to see which function you came from, but I get your point. We should make this configurable, as I implemented it for miri, which already had this behavior before we used `tracing-tree`

WRT the wraparound, I personally would also prefer no wraparound, so 👍 from me, may get a lot of rightwards drift though.

**Comment by jackh726** [comment]
Here's a decent example of how the verbose entry is difficult to read:
with:
```
│ │ │ ├─0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
│ │ │ ├┐rustc_trait_selection::traits::project::project_type obligation=Obligation(predicate=ProjectionTy { substs: [IdScanner, ReEarlyBound(0, 'a)], item_def_id: DefId(0:6 ~ issue_87803[87c4]::Scanner::Token) }, cause=ObligationCauseData { span: src/test/ui/generic-associated-types/issue-87803.rs:14:5: 14:30 (#0), body_id: HirId { owner: DefId(0:15 ~ issue_87803[87c4]::{impl#0}::Token), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [Binder(ProjectionPredicate(ProjectionTy { substs: [IdScanner, ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a) })], item_def_id: DefId(0:6 ~ issue_87803[87c4]::Scanner::Token) }, &ReEarlyBound(0, 'a) str), [Region(BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a))])], reveal: UserFacing }, depth=0)
│ │ │ │└┐rustc_trait_selection::traits::select::select obligation=Obligation(predicate=Binder(TraitPredicate(<IdScanner as Scanner>), []), cause=ObligationCauseData { span: src/test/ui/generic-associated-types/issue-87803.rs:14:5: 14:30 (#0), body_id: HirId { owner: DefId(0:15 ~ issue_87803[87c4]::{impl#0}::Token), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [Binder(ProjectionPredicate(ProjectionTy { substs: [IdScanner, ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a) })], item_def_id: DefId(0:6 ~ issue_87803[87c4]::Scanner::Token) }, &ReEarlyBound(0, 'a) str), [Region(BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a))])], reveal: UserFacing }, depth=0)
│ │ │ │ ├┐rustc_trait_selection::traits::select::select obligation=Obligation(predicate=Binder(TraitPredicate(<IdScanner as Scanner>), []), cause=ObligationCauseData { span: src/test/ui/generic-associated-types/issue-87803.rs:14:5: 14:30 (#0), body_id: HirId { owner: DefId(0:15 ~ issue_87803[87c4]::{impl#0}::Token), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [Binder(ProjectionPredicate(ProjectionTy { substs: [IdScanner, ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a) })], item_def_id: DefId(0:6 ~ issue_87803[87c4]::Scanner::Token) }, &ReEarlyBound(0, 'a) str), [Region(BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a))])], reveal: UserFacing }, depth=0)
│ │ │ │ │└┐rustc_trait_selection::traits::select::candidate_assembly::candidate_from_obligation stack=TraitObligationStack(Obligation(predicate=Binder(TraitPredicate(<IdScanner as Scanner>), []), cause=ObligationCauseData { span: src/test/ui/generic-associated-types/issue-87803.rs:14:5: 14:30 (#0), body_id: HirId { owner: DefId(0:15 ~ issue_87803[87c4]::{impl#0}::Token), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [Binder(ProjectionPredicate(ProjectionTy { substs: [IdScanner, ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a) })], item_def_id: DefId(0:6 ~ issue_87803[87c4]::Scanner::Token) }, &ReEarlyBound(0, 'a) str), [Region(BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a))])], reveal: UserFacing }, depth=0))
│ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::select::candidate_assembly cache_fresh_trait_pred=Binder(TraitPredicate(<IdScanner as Scanner>), [])
```
without:
```
│ │ │ ├─0ms DEBUG rustc_infer::infer::region_constraints RegionConstraintCollector: start_snapshot
│ │ │ ├─┐rustc_trait_selection::traits::select::select obligation=Obligation(predicate=Binder(TraitPredicate(<IdScanner as Scanner>), []), cause=ObligationCauseData { span: src/test/ui/generic-associated-types/issue-87803.rs:14:5: 14:30 (#0), body_id: HirId { owner: DefId(0:15 ~ issue_87803[87c4]::{impl#0}::Token), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [Binder(ProjectionPredicate(ProjectionTy { substs: [IdScanner, ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a) })], item_def_id: DefId(0:6 ~ issue_87803[87c4]::Scanner::Token) }, &ReEarlyBound(0, 'a) str), [Region(BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a))])], reveal: UserFacing }, depth=0)
│ │ │ │ ├─┐rustc_trait_selection::traits::select::candidate_assembly::candidate_from_obligation stack=TraitObligationStack(Obligation(predicate=Binder(TraitPredicate(<IdScanner as Scanner>), []), cause=ObligationCauseData { span: src/test/ui/generic-associated-types/issue-87803.rs:14:5: 14:30 (#0), body_id: HirId { owner: DefId(0:15 ~ issue_87803[87c4]::{impl#0}::Token), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [Binder(ProjectionPredicate(ProjectionTy { substs: [IdScanner, ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a) })], item_def_id: DefId(0:6 ~ issue_87803[87c4]::Scanner::Token) }, &ReEarlyBound(0, 'a) str), [Region(BrNamed(DefId(0:16 ~ issue_87803[87c4]::{impl#0}::Token::'a), 'a))])], reveal: UserFacing }, depth=0))
│ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::select::candidate_assembly cache_fresh_trait_pred=Binder(TraitPredicate(<IdScanner as Scanner>), [])
```
This shows a couple things:
- Verbose is longer, which just means more to mentally parse through (here is 6vs4, but in a local comparison of logging a test, it's  5709 vs 5159)
- There are (lots of) cases where we enter, then immediately enter again (`select` here)
- That extra `project_type` log really doesn't help (at least me). When I go through the logs, if I see that, my mind thinks "oh, there's a call to `project_type` here. Sure, it *could* be useful to see the context, but when you have multiple small nested calls, it's really not.

Verbose exit, I suppose, can go either way. But it doesn't really work without the verbose entry (example below, without entry, with/without exit). I find the extra space at the end of the block helpful for mentally parsing the control flow, which you don't get with verbose entry/exit.
with:
```
│ │ │ │ │ ├─┐rustc_trait_selection::traits::select::match_impl impl_def_id=DefId(0:12 ~ issue_87803[87c4]::{impl#0}), obligation=Obligation(predicate=Binder(TraitPredicate(<IdScanner as Scanner>), []), cause=ObligationCauseData { span: no-location (#0), body_id: HirId { owner: DefId(0:0 ~ issue_87803[87c4]), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [], reveal: UserFacing }, depth=0)
│ │ │ │ │ │ ├─0ms DEBUG rustc_infer::infer::higher_ranked replace_bound_vars_with_placeholders(next_universe=U1, result=TraitPredicate(<IdScanner as Scanner>), map={})
│ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::select impl_trait_ref=<IdScanner as Scanner>
│ │ │ │ │ │ ├┐
│ │ │ │ │ │ ├─┐rustc_trait_selection::traits::project::normalize_with_depth_to depth=1, value=<IdScanner as Scanner>
│ │ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project obligations.len=0
│ │ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project value=<IdScanner as Scanner>
│ │ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project result=<IdScanner as Scanner>, obligations.len=0
│ │ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project normalizer.obligations=[]
│ │ │ │ │ │ │┌┘
│ │ │ │ │ │ ├┘
│ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::select impl_trait_ref=<IdScanner as Scanner>, placeholder_obligation_trait_ref=<IdScanner as Scanner>
```
vs without
```
│ │ │ │ ├─┐rustc_trait_selection::traits::select::match_impl impl_def_id=DefId(0:12 ~ issue_87803[87c4]::{impl#0}), obligation=Obligation(predicate=Binder(TraitPredicate(<IdScanner as Scanner>), []), cause=ObligationCauseData { span: no-location (#0), body_id: HirId { owner: DefId(0:0 ~ issue_87803[87c4]), local_id: 0 }, code: MiscObligation }, param_env=ParamEnv { caller_bounds: [], reveal: UserFacing }, depth=0)
│ │ │ │ │ ├─0ms DEBUG rustc_infer::infer::higher_ranked replace_bound_vars_with_placeholders(next_universe=U1, result=TraitPredicate(<IdScanner as Scanner>), map={})
│ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::select impl_trait_ref=<IdScanner as Scanner>
│ │ │ │ │ ├─┐rustc_trait_selection::traits::project::normalize_with_depth_to depth=1, value=<IdScanner as Scanner>
│ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project obligations.len=0
│ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project value=<IdScanner as Scanner>
│ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project result=<IdScanner as Scanner>, obligations.len=0
│ │ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::project normalizer.obligations=[]
│ │ │ │ │ ├─┘
│ │ │ │ │ ├─0ms DEBUG rustc_trait_selection::traits::select impl_trait_ref=<IdScanner as Scanner>, placeholder_obligation_trait_ref=<IdScanner as Scanner>
```

One other (big) downside of repeating spans: if you're grepping for a call and you have repeated spans you may now have multiple matches whereas before you had one. The `match_impl` call above is a good example. If I grep for it, I get 2 matches without verbose entry/exit; with, I get 8.

**Pull request merged**
