### PR TITLE
[beta] Update rustfmt and rls

### PR DESCRIPTION
**Pull request by nrc**
r? @alexcrichton

### CODE REVIEW

**Comment by kennytm** [comment]
Note: This PR should *not* be merged before #46140

**Comment by alexcrichton** [comment]
I've cherry-picked this into https://github.com/rust-lang/rust/pull/46140 to hopefully reduce cycle time, so closing

**Comment by alexcrichton** [comment]
Ah I ended up backing this out due to test failures, so I'll reopen!

**Comment by nrc** [comment]
Do you have a link to the test failures? Looks like we're passing Travis here.

**Comment by kennytm** [comment]
@nrc https://github.com/rust-lang/rust/pull/46140#issuecomment-346090274

**Pull request merged**
