### PR TITLE
Compute parent module when collecting hir::MacroDef.

### LINKED ISSUE #77828: HIR and TyCtxt disagree about the parents of decl macros
I tried this code:

https://github.com/rust-lang/rust/blob/8cc82ee340ed96099680ec1165cf5e192d658d0f/library/core/src/ptr/mod.rs#L1487-L1492

I expected to see this happen: `tcx.hir().parent_module(raw_const_hir_id)` and `tcx.parent(raw_const_def_id).unwrap()` are both the module `core::ptr`.

Instead, this happened: `tcx.hir().parent_module(raw_const_hir_id)` is `core` and `tcx.parent(raw_const_def_id).unwrap()` is `core::ptr`. I think `core::ptr` is correct.

### Meta

`rustc --version`: HEAD (https://github.com/rust-lang/rust/commit/8cc82ee340ed96099680ec1165cf5e192d658d0f)

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes #77828.

r? @jyn514

### CODE REVIEW

**Comment by jyn514** [comment]
This is awesome, but I don't know enough about HIR to review I think. Is there a way to test this somehow? Maybe you could see if https://github.com/rust-lang/rust/issues/80414 now generates documentation at https://doc.rust-lang.org/nightly/core/marker/macro.Copy.html instead of https://doc.rust-lang.org/nightly/core/derive.Copy.html ? See https://rustc-dev-guide.rust-lang.org/rustdoc-internals.html#dotting-is-and-crossing-ts for how to write rustdoc tests.

**Comment by cjgillot** [comment]
I can't get such a rustdoc test passing.

**Comment by jyn514** [comment]
Ok, then it looks like there were two separate bugs for https://github.com/rust-lang/rust/issues/74355, one in rustc and one in rustdoc.

r? @petrochenkov maybe?

**Comment by danielhenrymantilla** [comment]
There is still some effort needed to fix #74355, but the changes in this PR are great since they will fix the hack I have used with my fix attempt in #77862

**Comment by petrochenkov** [comment]
What `tcx.hir().parent_module(hir_id)` and `tcx.parent(def_id)` show for `#[macro_export] macro_rules! ...` items now?

If they are consistent (looks like they should be), then this this PR is good.
However, rustdoc may start showing `#[macro_export] macro_rules! ...` in inner modules rather than in the crate root, in that case it will need to be fixed.

@cjgillot Could you check both these cases? If they behave as expected, then r=me.

**Comment by cjgillot** [comment]
@petrochenkov, I am not sure how to address your review. How do you recommend I test the consistency?

**Comment by petrochenkov** [comment]
@cjgillot 
In any way, e.g. printf from the compiler.
I don't suggest to put this check into test suite, just look at the IDs and make sure that they are consistent.

**Comment by cjgillot** [comment]
@petrochenkov, ok thanks.

I tested adding the following in the check_attr HIR visitor, and tested a file with both top-level and module macro exports. It passes.
```rust
use rustc_middle::ty::DefIdTree;
let def_id = self.tcx.hir().local_def_id(macro_def.hir_id);
assert_eq!(
    Some(self.tcx.parent_module(macro_def.hir_id).to_def_id()),
    self.tcx.parent(def_id.to_def_id())
);
```

Should be good to go.

**Pull request merged**
