### PR TITLE
Refer to Ruby/Python/JS as "dynamically evaluated"

### PR DESCRIPTION
**Pull request by avdi**
"Dynamically typed" didn't seem like a relevant distinction; there are statically-compiled dynamically-typed languages. Another term that might work here (despite being notoriously vague) is "scripting languages".

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks @avdi! yeah, the original isn't exactly the right wording, but I don't know if this is the way to go, either. Because then you get into the whole 'AOT vs JIT vs interpreted' is a property of the implementation, not of the language itself...

How about this: remove the adjective alltogether. "If you're coming from a language like"... ?

**Comment by avdi** [comment]
That would work. Or "a dynamic language like...", leaving it ambiguous what you mean by "dynamic".

**Comment by steveklabnik** [comment]
I'd be happy with either of those. :)

**Comment by steveklabnik** [comment]
Oh, didn't see this got updated! Thanks again @avdi :D

**Comment by tomjakubowski** [comment]
There are also statically typed interpreted languages out there, so I like that the docs now make this subtle distinction

**Pull request merged**
