### PR TITLE
Fix uninhabited enum branching pass

### PR DESCRIPTION
**Pull request by ogoffart**
when the discriminant is taken with some projection.

### CODE REVIEW

**Comment by ogoffart** [comment]
The context behind this PR is that I wanted to experiment with another optimisation on enums, and wanted to use this pass as a model. But I realized it did not match for most of the enums, so I needed to fix that first.

**Review by tmiasko — APPROVED** [review]

**Comment by jackh726** [comment]
I don't know enough about this code to review this myself, but this also seems small. Let's r? @wesleywiser though.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Let's check performance before merging:

@bors try @rust-timer queue

**Comment by wesleywiser** [comment]
cc @rust-lang/release `rust-timer` can't seem to set labels anymore

**Pull request merged**
