### PR TITLE
[WIP] Fix compiler incorrectly rejecting Drop impls where parent struct uses HRTB

### LINKED ISSUE #34426: Spurious error "The requirement ... is added only by the Drop impl"
It seems like it's not possible to implement `Drop` for types that have higher ranked trait bounds on their type arguments.

``` rust
trait WithLifetime<'a> {
}

struct Foo<A: for<'a> WithLifetime<'a>> {
    a: A,
}

impl<A: for<'a> WithLifetime<'a>> Drop for Foo<A> {
    fn drop(&mut self) {}
}
```

This gives the error _"The requirement `for<'a> A: WithLifetime<'a>` is added only by the Drop impl"_ which is obviously untrue. Removing that bound from the `Drop` impl gives the error _"the trait bound `for<'a> A: WithLifetime<'a>` is not satisfied"_ as it should.

### PR DESCRIPTION
**Pull request by Osspial**
Fixes #34426.

The problem here is that `ensure_drop_predicates_are_implied_by_item_defn` in `dropck.rs` incorrectly rejects all implementations that have HRTB clauses in their where clause, even if the corresponding struct definition has an identical HRTB clause. Digging deep into the types, the issue is a `DefId` mismatch in [`RegionKind::ReLateBound`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/enum.RegionKind.html#variant.ReLateBound) when it contains a [`BoundRegion::BrNamed`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/enum.BoundRegion.html#variant.BrNamed) variant - the `BrNamed`'s `DefId` in the `Drop` impl doesn't match up with the corresponding `DefId` in the struct definition.

The current solution is to just ignore the `DefId` when we come across that specific pattern, and just compare the overall shape of the HRTB bound. This is an absolutely awful way to do it and probably shouldn't be merged onto master (hence the draft PR status), but it *works*. There are two better solutions I can come up with:
- Use the fulfill machinery, which [this comment rules out](https://github.com/Osspial/rust/blob/31f6517e96dbec57a43d6426f1f2787ae10d944d/src/librustc_typeck/check/dropck.rs#L200-L204) for reasons I don't have the required type-system vocabulary to understand.
- Ensure that the `DefId`s in the drop impl's HRTB clauses match up with the `DefId`s in the struct's HRTB clauses.

However, I have very little knowledge of the compiler's internals, and hence don't know where to look to implement either of those solutions.

------------------------------

Questions for whoever reviews this:
- What are outlives-predicates and region inference constraints, and why do they make the fulfill machinery not work for checking drop predicates (which the linked comment above claims)?
- Which of the two above solutions is the best solution? If neither of them are the proper solution, what other compiler mechanisms should I use to solve this?

### CODE REVIEW

**Comment by pnkfelix** [comment]
(marking as WIP to reflect "draft PR status" as noted in PR description above.)

**Comment by Centril** [comment]
cc https://github.com/rust-lang/homu/issues/14

**Comment by Osspial** [comment]
Any updates on reviewing this?

**Comment by estebank** [comment]
Pinged @nikomatsakis over zulip. The code doesn't seem bad on its own, but your assessment of this not being the best way of approaching this is correct. I'll defer to Niko for a more in depth review.

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/compiler, is there anyone else who can review this PR? It looks like @nikomatsakis probably doesn't have the time to do so.

**Review by oli-obk — COMMENTED** [review]
I'm a little bit out of my depth here, so take my idea with a grain of salt. Calling `p.relate(relater, predicate)` will probably do the right thing, but I have not been able to figure out which `relater` you would want or if you'll need to roll your own

**Comment by arielb1** [comment]
Hi!

Screwing with late-bound regions like that tends to cause all sort of weird troubles. Have you tried using `anonymize_late_bound_regions` in a recursive fashion, like [`RegionEraserVisitor`](https://github.com/rust-lang/rust/blob/9606f6fa64926a84d82e3c62dbdc57f5c10f756d/src/librustc/ty/erase_regions.rs#L39-L73)?

I don't think you can just use plain `RegionEraserVisitor`, because you don't want to erase the non-LBRs, so you'll probably want a version of it without the `fold_region` fn.

**Comment by JohnTitor** [comment]
Ping from triage: @Osspial any updates on this?

**Comment by TommasoBianchi** [comment]
Hi everyone, came here while working on #58311. I think I can refactor @Osspial code to account for both HRTB (using `anonymize_late_bound_regions` as suggested) and for correctly equating associated types in `ProjectionPredicate` (which was the problem in #58311). I have written a simple impl of `TypeRelation` in order to use `relate` instead of `==`.

Is it ok if I open a new PR or should we keep the two issues separate? I think that there's some benefit in doing a single refactor of the code that checks for `Predicate` equality for the dropck.

**Comment by Osspial** [comment]
I'll go ahead and close this now, since the underlying issue's been resolved. Thank you @TommasoBianchi for looking into it!'

I figured out how to avoid the design pattern that was causing this to be a problem in my code, and I'd had a hard time getting into a groove working on the compiler so fixing this PR up fell to the wayside. I'm sorry for not communicating that earlier.

**Pull request closed without merging**
