### PR TITLE
Greatly speed up reading/writing slices with #[inline]

### PR DESCRIPTION
**Pull request by erickt**
before:

test bench_read_slice  ... bench:        68 ns/iter (+/- 56)
test bench_read_vec    ... bench:        78 ns/iter (+/- 21)
test bench_write_slice ... bench:       133 ns/iter (+/- 46)
test bench_write_vec   ... bench:       308 ns/iter (+/- 69)

after:

test bench_read_slice  ... bench:        32 ns/iter (+/- 10)
test bench_read_vec    ... bench:        32 ns/iter (+/- 8)
test bench_write_slice ... bench:        53 ns/iter (+/- 12)
test bench_write_vec   ... bench:       247 ns/iter (+/- 172)

### CODE REVIEW

**Comment by Gankro** [comment]
Seriously if basically all code should be #[inline] should we be considering cranking up how aggressively we hint to LLVM to inline things?

**Comment by Manishearth** [comment]
```

thread '<main>' panicked at 'Some tests failed', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/compiletest/compiletest.rs:258
---- [run-pass] bench/bench-io.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: i686-apple-darwin/stage2/bin/rustc /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/test/bench/bench-io.rs -L i686-apple-darwin/test/bench/ --target=i686-apple-darwin -L i686-apple-darwin/test/bench/bench-io.stage2-i686-apple-darwinlibaux -C prefer-dynamic -o i686-apple-darwin/test/bench/bench-io.stage2-i686-apple-darwin --cfg rtopt --cfg debug -O -L i686-apple-darwin/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
warning: crate names soon cannot contain hyphens: bench-io
error: main function not found
error: aborting due to previous error

------------------------------------------

thread '[run-pass] bench/bench-io.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-32-opt/build/src/compiletest/runtest.rs:1482



failures:
    [run-pass] bench/bench-io.rs

```

http://buildbot.rust-lang.org/builders/auto-mac-32-opt/builds/4236/steps/test/logs/stdio

**Comment by arthurprs** [comment]
@Gankro that's exactly my felling.

**Comment by erickt** [comment]
@Gankro: Doesn't llvm need the functions in the metadata to do inlining across crates? Assuming of course we're not using LTO.

**Pull request merged**
