### PR TITLE
Add example for Lifetime Elision with two inputs.

### LINKED ISSUE #21284: The Ownership guide does not clearly explain what happens when there are two or more elided lifetimes
Reading over the Ownership section in TRPL and came across the example 

    fn frob(s: &str, t: &str) -> &str;  // ILLEGAL, two inputs

As a newbie, this was very confusing. I believe the situation could be explained by simply adding another line.

    fn frob(s: &str, t: &str) -> &str;  // ILLEGAL, two inputs
    fn frob(s: &'a str, t: &'b str) -> &'? str; // Expanded: Output lifetime is unclear

I'm not sure if this is the best way to do this.

### PR DESCRIPTION
**Pull request by snowe2010**
Lifetime elision with two input references is not clear.
Closes #21284

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is now out of date, and needs a rebase.

**Comment by snowe2010** [comment]
I was waiting for input on my comment. What should I change the question mark to?

**Comment by Gankro** [comment]
I think just leaving the questionmark off should be sufficient in context.

**Comment by snowe2010** [comment]
r=steveklabnik I think it's ready, let me know if I need to clean anything up. Also, not sure if I did the `r=` bit right.

**Comment by steveklabnik** [comment]
You can't add the r, only people with permission can :)

I think the rebase went wrong here, there's a tooon of unrelated commits.

**Comment by snowe2010** [comment]
I'm not seeing any unrelated commits? Where exactly do you see them?

**Comment by Gankro** [comment]
screenshot from 2015-01-24 01 53 41

**Comment by snowe2010** [comment]
@Gankro, those were there before I rebased. I saw them show up like 2 days before I rebased. I didn't do any of that. You can check from my commit history on my repo too. Don't know how those got there.

**Comment by snowe2010** [comment]
This has been moved to #21618 due to (maybe) Github problems and the fact that this PR somehow won't update anymore from my fork.

**Pull request closed without merging**
