### PR TITLE
constifying `FnOnce` trait fallout

### PR DESCRIPTION
**Pull request by compiler-errors**
These are a few places I saw ICEs in a draft PR that I have to constify the `FnOnce`/`FnMut`/`Fn` traits.

I'm happy to also block this PR until I have the full `Fn` trait constification work ready[^1], since these are just kinda landing in a vacuum. But I need somewhere to store them because my `git stash` is `/dev/null`.

r? @ghost
cc @fmease @fee1-dead 

[^1]: The ready PR is blocked on const closures being kind of difficult to reconcile with host effect: [zulip](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/const.20closures)

### CODE REVIEW

**Review by oli-obk — COMMENTED** [review]
I have not come to a conclusion yet about what the best way is to dynamically add an effect param depending on a condition.

possible solutions:

* yours: just having two code paths, duplicating the shared params
* use a vec for the shared params, push the effect on it
* `Iterator::chain` an `Option` of the effect param to the thing
* something else?!

**Comment by compiler-errors** [comment]
Maybe I should take the existing `with_opt_host_effect_param` and rename it to `with_opt_host_effect_param_from_body`, and then have:

```
pub fn with_opt_host_effect_param(
        self,
        callee_def_id: DefId,
        args: impl IntoIterator<Item: Into<ty::GenericArg<'tcx>>>,
        host_effect_param: ty::Const<'tcx>,
    ) -> ty::GenericArgsRef<'tcx> {
```

So then we can just do `tcx.with_opt_host_effect_param(call_once_def_id, instance.args, tcx.consts.true_)`, etc.

**Comment by apiraino** [comment]
I'll swing this back to Michael as I read there is some more design here to do

@rustbot author

**Comment by compiler-errors** [comment]
This needs to be reworked after const traits are (?) reworked.

**Pull request closed without merging**
