### PR TITLE
Use .copy_from_slice() where applicable

### PR DESCRIPTION
**Pull request by bluss**
Use .copy_from_slice() where applicable

.copy_from_slice() does the same job of .clone_from_slice(), but the
former is explicitly for Copy elements and calls `memcpy` directly, and
thus is it efficient without optimization too.

### CODE REVIEW

**Comment by bluss** [comment]
cc @ubsan FYI

**Comment by bluss** [comment]
Thanks :) The I/O impls are back where they should be with this.

**Comment by ubsan** [comment]
@bluss thanks :)

**Pull request merged**
