### PR TITLE
Fix section headers on Not Found page

### LINKED ISSUE #25305: Macro documentation links to an empty page
The `macros` link [from the API docs index](http://doc.rust-lang.org/1.0.0-beta.4/std/#the-rust-prelude-and-macros) goes to an [empty page](http://doc.rust-lang.org/1.0.0-beta.4/std/macros/). Should this link to the [prelude docs](http://doc.rust-lang.org/1.0.0-beta.4/std/prelude/) instead? It looks like if you go there, the macros (like `println!`) are listed on the left sidebar.

### LINKED ISSUE #25794: documentations 404 page numbering starts with 0.1
I was viewing the [documentation](http://doc.rust-lang.org) when I (do not ask how) visited the site [/std/copy/index.html](http://doc.rust-lang.org/std/copy/index.html).

I immediately noticed that the numbering began with
> 0.1 Search

I looked up the corresponding sources ([/src/doc/not_found.md](https://github.com/rust-lang/rust/blob/5449f5d29e175230a1285ebe92394f50c76e1df6/src/doc/not_found.md)).

I am neither sure if this is a bug, nor am I sure if this is already fixed as I am not familiar with the structure of your documentation.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #25794

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm, does this close #25794 instead? Also, just to confirm, but have you checked out the rendered page to make sure it shows up ok?

**Comment by steveklabnik** [comment]
whoops, nice catch. yes, I ran this through Rustdoc, and now it shows 1, 2, and 3 instead.

**Comment by alexcrichton** [comment]
I believe the `--markdown-no-toc` flag will disable the numbers entirely, which is probably best for this page.

**Comment by steveklabnik** [comment]
@alexcrichton you're correct, so let's do that too. This should be good to go now.

**Pull request merged**
