### PR TITLE
add Miri to the nightly docs

### PR DESCRIPTION
**Pull request by ghost**
This is a follow-up to https://github.com/rust-lang/rust/pull/97773 and to https://github.com/rust-lang/rust/pull/98714

It adds miri to the doc.rust-lang.org/nightly/nightly-rustc](https://doc.rust-lang.org/nightly/nightly-rustc/

### CODE REVIEW

**Comment by RalfJung** [comment]
Failed in rollup: https://github.com/rust-lang/rust/pull/98853#issuecomment-1173159523
@bors r-

I have no idea why this is happening... but I think it must be this PR
```
[TIMING] test::Miri { stage: 2, host: x86_64-unknown-linux-gnu } -- 92.984
Build completed successfully in 0:24:13
{"miri":"test-pass","reference":"test-pass","rust-by-example":"test-pass","rustbook":"test-fail","embedded-book":"test-pass","rls":"test-pass","book":"test-pass","nomicon":"test-pass","cargo-miri":"test-fail","edition-guide":"test-pass"}Building rustbuild
    Finished dev [unoptimized] target(s) in 0.07s
Verifying status of book...
Verifying status of nomicon...
Verifying status of reference...
Verifying status of rust-by-example...
Verifying status of edition-guide...
Verifying status of rls...
Verifying status of miri...
Verifying status of embedded-book...
fatal: could not create work tree dir 'rust-toolstate': Read-only file system
thread 'main' panicked at 'git clone unsuccessful (status: Ok(ExitStatus(unix_wait_status(32768))))', toolstate.rs:322:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
```

**Comment by InfRandomness** [comment]
I don't see how this PR could cause this 🤔

**Comment by InfRandomness** [comment]
Rebased to upstream/master

**Comment by RalfJung** [comment]
Hm yeah it also happened in https://github.com/rust-lang/rust/pull/98859. Might be an infra problem?
@bors r=jyn514

**Comment by InfRandomness** [comment]
I would love to try and run `src/ci/scripts/run-build-from-ci.sh` but that script does not want to run because it's not in a CI environment
this is very annoying.

**Comment by InfRandomness** [comment]
> Hm yeah it also happened in #98859. Might be an infra problem? @bors r=jyn514

Might be a good idea to retry tomorrow ?

**Pull request merged**
