### PR TITLE
libsyntax: Refactor `parser.rs` into reasonably sized logical units

### LINKED ISSUE #60015: `libsyntax/parse/parser.rs` became too big for GitHub
Very convenient "Blame" functionality doesn't work in particular.

The solution is to move something from that file.
The obvious candidate for moving is [diagnostics-related code](https://github.com/rust-lang/compiler-team/blob/b5668ff5f27237d25cac7bcfacc07be2926d07f2/working-groups/diagnostics/README.md#what-is-the-goal-of-this-working-group), that can be moved into `libsyntax/parse/diagnostics.rs`.

### PR DESCRIPTION
**Pull request by Centril**
Here we split `parser.rs` (~7.9 KLOC) into more reasonably sized files (all < 1.8 KLOC):

- `./src/libsyntax/parse/`
   - `parser.rs`
   - `parser/`
      - `pat.rs`
      - `expr.rs`
      - `stmt.rs`
      - `ty.rs`
      - `path.rs`
      - `generics.rs`
      - `item.rs`
      - `module.rs`

Closes https://github.com/rust-lang/rust/issues/60015.

r? @petrochenkov

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors p=30
This is very conflict prone.

**Comment by eddyb** [comment]
IMO `src/libsyntax/parse/parser/` is silly, and we should flatten those two layers.

**Comment by petrochenkov** [comment]
Dammit, didn't notice that.
When `diagnostics.rs` was extracted it was put into `libsyntax/parse`, these new files also belong there.

**Comment by Centril** [comment]
Sure, seems reasonable; let's merge them soonish; I have some other refactors I'd like to do first tho.

**Comment by petrochenkov** [comment]
Also, while we are at it, `src\libsyntax\parse\classify.rs` is tiny and can be merged into somewhere, and `src\libsyntax\parse\unescape_error_reporting.rs` belongs to `src\libsyntax\parse\lexer`.

**Comment by petrochenkov** [comment]
(Better to do it faster so people don't have to rebase *again*.)

**Pull request merged**
