### PR TITLE
[Beta] Backport Clippy ICE fix to beta

### PR DESCRIPTION
**Pull request by flip1995**
There was an ICE in Clippy, when compiling `mysql_common`. Since this is a pretty popular crate, and there were a bunch of Clippy issues in the last few days, I think it is worth it to backport the fix (rust-lang/rust-clippy#4590) to beta.

cc rust-lang/rust-clippy#4653

r? @Manishearth

### CODE REVIEW

**Comment by flip1995** [comment]
Clippy branch for the backport is https://github.com/rust-lang/rust-clippy/tree/1.39.0-beta

**Comment by pietroalbini** [comment]
The backport itself looks fine (just a note: rename the branch from `1.39.0-beta` to `rust-1.39.0`.

@rust-lang/clippy do y'all approve this backport? Not sure how the approval process looks like in your team.

**Comment by flip1995** [comment]
I renamed the branch. :+1:

**Comment by Manishearth** [comment]
r+

**Pull request merged**
