### PR TITLE
SessionDiagnostic: Fix non-determinism in generated format string.

### LINKED ISSUE #76496: Reproducibility regression caused by 57edf88
My nightly script that checks for reproducible builds of rustc failed this morning.  Git bisect pointed me to 57edf88b400ff6c6ae1de255fbd7e3448aca4fb2 (#75138).

With that commit, about 12 rlibs have differences in my parallel builds (librustc_privacy is one) and nothing in the diff of the binaries jumps out as an obvious culprit.

### PR DESCRIPTION
**Pull request by jumbatm**
Fixes #76496.

r? @oli-obk

### CODE REVIEW

**Comment by jumbatm** [comment]
> So the fix is twofold: First change all the `HashSet` and `HashMap` to `FxHashSet` and `FxHashMap` where possible, and second, collect to a `Vec` and sort that `Vec` before iterating over the set/map

`rustc_macros` can't depend on `rustc_data_structures` for `FxHash*` because it depends a circular dependency. Instead, I've switched to a BTreeSet so the iteration order is deterministic.

@jgalenson -- I know it's a bit of an ask, but can you confirm this fixes the problem?

**Comment by oli-obk** [comment]
@bors r+

I think @jgalenson will see whether this fixes it once this is in nightly and their script runs again

**Comment by oli-obk** [comment]
>  Instead, I've switched to a BTreeSet so the iteration order is deterministic.

Perfect! This is much better. The FxHashSet stuff is only for speed, not determinism anyway

**Comment by jgalenson** [comment]
Thanks for the patch!  I've started some runs to see if this fixes the problem; I'll reply again when they're done.

**Comment by jgalenson** [comment]
Yes, it seems to solve the problem.  Thanks!

**Comment by jumbatm** [comment]
No worries - thank you for checking :)

**Pull request merged**
