### PR TITLE
Fix legacy_const_generic doc arguments display

### LINKED ISSUE #83167: Use const generics for stdarch intrinsics
# Background

https://github.com/rust-lang/stdarch/issues/248

`core::arch` contains architecture-specific vendor intrinsics, some of which have arguments that are required to be compile-time constants. This is tricky because LLVM will often assert/ICE if a constant is not passed into the LLVM intrinsic at the LLVM IR level. This was previously handled by using a `match` statement to manually monomorphize the intrinsic:

```rust
#[inline]
#[target_feature(enable = "sse")]
#[cfg_attr(test, assert_instr(shufps, mask = 3))]
#[rustc_args_required_const(2)]
#[stable(feature = "simd_x86", since = "1.27.0")]
pub unsafe fn _mm_shuffle_ps(a: __m128, b: __m128, mask: i32) -> __m128 {
    let mask = (mask & 0xFF) as u8;

    macro_rules! shuffle_done {
        ($x01:expr, $x23:expr, $x45:expr, $x67:expr) => {
            simd_shuffle4(a, b, [$x01, $x23, $x45, $x67])
        };
    }
    macro_rules! shuffle_x67 {
        ($x01:expr, $x23:expr, $x45:expr) => {
            match (mask >> 6) & 0b11 {
                0b00 => shuffle_done!($x01, $x23, $x45, 4),
                0b01 => shuffle_done!($x01, $x23, $x45, 5),
                0b10 => shuffle_done!($x01, $x23, $x45, 6),
                _ => shuffle_done!($x01, $x23, $x45, 7),
            }
        };
    }
    macro_rules! shuffle_x45 {
        ($x01:expr, $x23:expr) => {
            match (mask >> 4) & 0b11 {
                0b00 => shuffle_x67!($x01, $x23, 4),
                0b01 => shuffle_x67!($x01, $x23, 5),
                0b10 => shuffle_x67!($x01, $x23, 6),
                _ => shuffle_x67!($x01, $x23, 7),
            }
        };
    }
    macro_rules! shuffle_x23 {
        ($x01:expr) => {
            match (mask >> 2) & 0b11 {
                0b00 => shuffle_x45!($x01, 0),
                0b01 => shuffle_x45!($x01, 1),
                0b10 => shuffle_x45!($x01, 2),
                _ => shuffle_x45!($x01, 3),
            }
        };
    }
    match mask & 0b11 {
        0b00 => shuffle_x23!(0),
        0b01 => shuffle_x23!(1),
        0b10 => shuffle_x23!(2),
        _ => shuffle_x23!(3),
    }
}
```

The downside of this approach is that it generates huge MIR and severely bloats the size of `libcore` to the point where it actually affects compilation time.

The `#[rustc_args_required_const]` attribute was used to restrict arguments to constants so that we could eventually replace this with const generics. Note that it effectively only acts as a hard lint, the `match` is still needed to manually monomorphize the LLVM intrinsic.

# New const generics support

https://github.com/rust-lang/stdarch/issues/1022

All the intrinsics in `stdarch` have been converted to use the newly stabilized const generics:

```rust
#[inline]
#[target_feature(enable = "sse")]
#[cfg_attr(test, assert_instr(shufps, mask = 3))]
#[rustc_legacy_const_generics(2)]
#[stable(feature = "simd_x86", since = "1.27.0")]
pub unsafe fn _mm_shuffle_ps<const mask: i32>(a: __m128, b: __m128) -> __m128 {
    static_assert!(mask: i32 where mask >= 0 && mask <= 255);
    simd_shuffle4(
        a,
        b,
        [
            mask as u32 & 0b11,
            (mask as u32 >> 2) & 0b11,
            ((mask as u32 >> 4) & 0b11) + 4,
            ((mask as u32 >> 6) & 0b11) + 4,
        ],
    )
}
```

To preserve backwards compatibility with the already stabilized intrinsics using `#[rustc_args_required_const]`, a new attribute `#[rustc_legacy_const_generics]` was added in #82447 which rewrites function calls of the form `func(a, b, c)` to `func::<{b}>(a, c)`.

This new attribute is not intended to ever be stabilized, it is only intended for use in `stdarch` as a replacement for `#[rustc_args_required_const]`.

```rust
#[rustc_legacy_const_generics(1)]
pub fn foo<const Y: usize>(x: usize, z: usize) -> [usize; 3] {
    [x, Y, z]
}

fn main() {
    assert_eq!(foo(0 + 0, 1 + 1, 2 + 2), [0, 2, 4]);
    assert_eq!(foo::<{1 + 1}>(0 + 0, 2 + 2), [0, 2, 4]);
}
```

# Open questions/issues

- `#[rustc_args_required_const]` allowed constant expressions derived from generic arguments in the caller, but this is not allowed with const generics. This technically makes this a breaking change.
- Another potential breaking change is that the intrinsics now use a post-monomorphization `static_assert` to validate constant arguments. Previously, intrinsics would either use runtime asserts or simply pick an arbitrary default behavior for out-of-range constants.
- Do we want to force all callers to use the const generics syntax in the 2021 edition?
  - Pros:
    - It makes it clearer that these intrinsics expect a constant as an argument.
    - Intrinsics are rendered with the const generics syntax in rustdoc.
  - Cons:
    - We will still need to support the `#[rustc_legacy_const_generics]` argument rewriting anyways for 2015/2018 code.
    - Intrinsics no longer have the same function signature as the original C vendor intrinsics.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/83167.

cc @Amanieu

### CODE REVIEW

**Review by jyn514 — COMMENTED** [review]
I don't really have time to review this properly ... @Amanieu @Mark-Simulacrum does this look like about the transformation you expect?

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by Mark-Simulacrum** [comment]
I think *some* indication that the arguments must be const should be given -- there's no canonical Rust syntax for this yet, though.

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum So what should be changed here exactly? If the syntax isn't present yet, I'm not sure what I can do but if you have suggestions, please go ahead. :)

**Comment by Mark-Simulacrum** [comment]
There's some discussion starting at https://github.com/rust-lang/rust/issues/83167#issuecomment-881070576 of options for rendering.

Can you provide a screenshot of what one of these functions looks like before/after this PR? That might help with discussion since currently reading the code seems necessary.

**Comment by GuillaumeGomez** [comment]
Sure, here you go.

Current version:

Screenshot from 2021-12-01 20-58-01
Screenshot from 2021-12-01 20-58-04

With this PR (no more generics):

Screenshot from 2021-12-01 21-08-29
Screenshot from 2021-12-01 21-08-32

I also rebased on `master`.

**Comment by Mark-Simulacrum** [comment]
Yeah, ok, that matches what I thought.

I would suggest adding `const` before the argument name -- that may be a useful signal that the argument is special. Users can't currently create such an argument themselves, which is unfortunate, but feels a little unavoidable to me at this time.

I think that would move us in the right direction, but I'm not sure it's enough, particularly for call-sites which are using the regular const-generic syntax (i.e., with turbofish), which will look like they're omitting valid options. One benefit to us might be that I think all such "weird" functions are currently *only* leaf functions (i.e., not trait methods, etc) so we may be able to just duplicate the signature twice with an "or" in between or something like that, though it's probably painful to do in rustdoc's current design from what I recall.

Overall, I think it's important to show users both styles if neither style issues deprecation warnings (which I believe is currently the case), and important to signal the need for the argument to be const. It may be worth nominating for libs-api to discuss whether there *is* a preferred syntax for calling these functions, and whether we wish to deprecate one of the forms; that would alleviate the concern over users encountering both syntaxes in the wild -- at least over time.

**Comment by GuillaumeGomez** [comment]
Let's ping them then. cc @rust-lang/t-libs-api

**Comment by Amanieu** [comment]
I personally think that just having:
```rust
pub fn foo(x: usize, const Y: usize, z: usize);
```
is enough since that is the form used by the vendor APIs. I don't think we need to expose the desugared generic form of the function in the documentation.

**Comment by Mark-Simulacrum** [comment]
I largely agree, with a possible caveat of a single paragraph at the root (core::arch module docs) explaining this, if it doesn't exist yet. I think it would definitely be an improvement on the status quo.

**Comment by GuillaumeGomez** [comment]
It now looks like this:

Screenshot from 2021-12-02 11-20-11
Screenshot from 2021-12-02 11-20-16

**Comment by Amanieu** [comment]
LGTM

**Pull request merged**
