### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by weihanglo**
8 commits in ccc84ccec4b7340eb916aefda1cb3e2fe17d8e7b..fc1d58fd0531a57a6b942a14cdcdbcb82ece16f3
2024-02-07 15:37:49 +0000 to 2024-02-09 15:54:29 +0000
- docs(changelog): Clarify lints in virtual workspace error (rust-lang/cargo#13425)
- fix(compiler): Clarify Finished message (rust-lang/cargo#13422)
- fix(test-support): remove special case for `$message_type` (rust-lang/cargo#13424)
- chore(deps): update msrv (1 version) to v1.76.0 (rust-lang/cargo#13420)
- chore(bump-check): include rustfix and cargo-util-schemas (rust-lang/cargo#13421)
- chore: update to `jobserver` 0.1.28 (rust-lang/cargo#13419)
- feat: Add hint for adding members to workspace (rust-lang/cargo#13411)
- fix: Don't duplicate comments when editing TOML (rust-lang/cargo#13402)

r? weihanglo

### CODE REVIEW

**Comment by weihanglo** [comment]
Looks unrelated to cargo.

@bors retry

**Comment by weihanglo** [comment]
@ehuss are these errors the same as you are resolving in https://github.com/rust-lang/rust/pull/120744 ?

**Comment by ehuss** [comment]
Yep, still working on it. Just keep trying until it passes.

@bors retry

`invalid r_symbolnum=14`

**Pull request merged**
