### PR TITLE
add more pat2021 tests

### LINKED ISSUE #84138: disallow `|` from the follow-set of `pat2021`
In Edition 2021, the following should error:

```rust
macro_rules! foo {
    ($x:pat | $y:pat) => { }
}

fn main() { }
```

for the same reason that the following already errors:

```rust
macro_rules! foo {
    ($x:expr | $y:expr) => { }
}

fn main() { }
```

cc @rust-lang/project-edition-2021

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rust/issues/84138

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
One thing I would like is a test `macro-pat-pattern-followed-by-or-in-2021.rs` that uses `// edition: 2021` and which has `$x:pat |` and shows that we get an error (and probably one without the edition that does not...)

**Comment by hi-rustin** [comment]
@nikomatsakis How about now?

**Review by nikomatsakis — APPROVED** [review]

**Comment by hi-rustin** [comment]
@nikomatsakis Thanks for your review.

**Pull request merged**
