### PR TITLE
parse cfgspecs passed to rustdoc

### LINKED ISSUE #22131: rustdoc doesn't parse cfgspecs properly
It treats something like `feature=bar` as a single `MetaWord` instead of a `MetaNameValue`. This is due to the code on [lines 70-73 of librustdoc/test.rs](https://github.com/rust-lang/rust/blob/134e00be7751a9fdc820981962e4fd7ea97bfff6/src/librustdoc/test.rs#L70-L73):
```rust
cfg.extend(cfgs.into_iter().map(|cfg_| {
    let cfg_ = token::intern_and_get_ident(&cfg_);
    P(dummy_spanned(ast::MetaWord(cfg_)))
}));
```
I have a PR for this that I will open shortly.

### PR DESCRIPTION
**Pull request by apasel422**
fixes #22131

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could this actually call the relevant code in the compiler? Also, can you add a test for this?

**Comment by apasel422** [comment]
Sure. Where do rustdoc tests go?

**Comment by apasel422** [comment]
Updated to use the preexisting code in librustc, and added a test.

**Comment by alexcrichton** [comment]
@bors: r+ ad3be9f

Thanks!

**Pull request merged**
