### PR TITLE
Update jemalloc again

### LINKED ISSUE #31030: Upgrade jemalloc, re-enable Windows GNU
As of the time of this writing, we are running jemalloc at the revision https://github.com/rust-lang/jemalloc/commit/91010a9e2ebfc84b1ac1ed7fdde3bfed4f65f180 which I believe is the 4.0.4 release of jemalloc. Previously we were running https://github.com/rust-lang/jemalloc/commit/e24a1a025a1f214e40eedafe3b9c7b1d69937922 which I believe is somewhere in the 3.6 series. We attempted to upgrade jemalloc many times between these two commits eventually [reaching the conclusion](https://github.com/jemalloc/jemalloc/issues/310) that the previous behavior of `--enable-lazy-lock` on Windows is fundamentally racy in jemalloc right now unfortunately. This led to a [successful upgrade of jemalloc](https://github.com/rust-lang/rust/pull/30434) to where we are today.

Unfortunately, however, there is a [deadlock in jemalloc 4.0.4](https://github.com/jemalloc/jemalloc/issues/315) so we are attempting to downgrade back to 3.6. There were no known problems other than some Windows issues with jemalloc 3.6, so we believe it'll be fine for awhile. In this downgrade, however, it appears that the implementation of `--disable-lazy-lock` is somewhat broken as well, causing the [initial downgrade](https://github.com/rust-lang/rust/pull/30985) to fail to land.

As a result, the downgrade attempt will disable jemalloc on Windows entirely. This issue will track re-enabling it on Windows as well as re-upgrading once the deadlock bug is fixed. As far as I know the only reason to not enable Windows is that lots of locking support was improved in 4.0.*, and the only reason to not upgrade immediately is the deadlock bugs we've encountered.

### PR DESCRIPTION
**Pull request by alexcrichton**
Now that https://github.com/jemalloc/jemalloc/commit/767d85061a6fb88ec977bbcd9b429a43aff391e6 is upstream, the relevant deadlocking issue which prompted our downgrade has been resolved. As a result, there's no known issue to _not_ upgrade! This also re-enables jemalloc for the pc-windows-gnu target as known issues with that have also been fixed.

Closes #31030

### CODE REVIEW

**Comment by alexcrichton** [comment]
We may want to consider holding this off until after the release? It's super easy to backport a downgrade, however, so it may not be that critical.

**Comment by AlisdairO** [comment]
Just a note that 4.1.0 has just been released, so it might be worth going for that?

**Comment by alexcrichton** [comment]
Good point! I've rebased the jemalloc branch again

**Comment by nikomatsakis** [comment]
r=me -- but I think at this point we might as well wait until the release

**Comment by alexcrichton** [comment]
@bors: r=nikomatsakis c5fdd8d

Ah beta has now been branched, so gonna approve this.

**Pull request merged**
