### PR TITLE
Feature gate attributes starting with `rustc_`. 

### PR DESCRIPTION
**Pull request by nikomatsakis**
This can be considered a downpayment on rust-lang/rfcs#572.

r? @brson 
cc @pnkfelix

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @manishearth

**Comment by Manishearth** [comment]
Shouldn't `rustc_move_fragments` be behind its own gate? That seems like a "feature" to me.

**Comment by brson** [comment]
Awesome. This will make me much happier about random `rustc_` attributes.

**Comment by brson** [comment]
@bors: r+ 7ca06ea

If some of the existing attributes are misclassified then that can be addressed in a followup.

**Comment by nikomatsakis** [comment]
@Manishearth I don't consider attributes like `rustc_move_fragments`, `rustc_variance`, or `rustc_error` to be features. We never intend for stable code to use them, they're just hacks to allow for better unit-testing (but very convenient, useful hacks!). The idea was that `rustc_attrs` is for attributes we never intend to stabilize -- anything that might eventually be user-exposed should get its own feature-gate, I agree.

**Pull request closed without merging**
