### PR TITLE
compile-pass test for #53606

### LINKED ISSUE #53606: NLL promotes arbitrary code to be evaluated by miri if the result is unused
This takes a while to compile. I presume because `loop {}` needs to hit the loop checker in miri. Changing the `_` to `_foo` or `foo` will immediately bail out due to `&(loop{}, 1).1` not living for the `'static` lifetime.

```rust
#![feature(nll)]

fn main() {

    let _: &'static usize = &(loop {}, 1).1;
}
```

([Playground](https://play.rust-lang.org/?gist=be2c247285593a5cc54019d953408b34&version=nightly&mode=debug&edition=2015))

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
warning: unreachable expression
 --> src/main.rs:4:40
  |
4 |     let _: &'static usize = &(loop {}, 1).1;
  |                                        ^
  |
  = note: #[warn(unreachable_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1.09s
     Running `target/debug/playground`
/root/entrypoint.sh: line 8:     7 Killed                  timeout --signal=KILL ${timeout} "$@"

```

### PR DESCRIPTION
**Pull request by saleemjaffer**
fixes #53606

### CODE REVIEW

**Comment by oli-obk** [comment]
@bors r+ rollup

Thanks!

**Comment by oli-obk** [comment]
Tip: if you change your main message to `fixes #53606`, then next time that issue will be closed automatically when the PR is merged

**Comment by saleemjaffer** [comment]
@oli-obk Thanks! This is my first contribution to rust. Hoping to work on more difficult issues over time :)

**Pull request merged**
