### PR TITLE
small fix to closure debuginfo

### PR DESCRIPTION
**Pull request by ahicks92**
This is fallout from #37429. The faking we do to make closures appear to have local variables was broken and made it through CI because the debuginfo tests got turned off.

This probably needs a dedicated test, but I wanted to get this in as quickly as possible because we probably need to backport this to the beta.

r? @alexcrichton

### CODE REVIEW

**Comment by camlorn** [comment]
I just hit the wrong button and submitted this without a description, sorry.

This is fallout from #37429.  The faking we do to make closures appear to have local variables was broken and made it through CI because the debuginfo tests got turned off.

This probably needs a dedicated test, but I wanted to get this in as quickly as possible because we probably need to backport this to the beta.

r? @alexcrichton

**Comment by alexcrichton** [comment]
r? @eddyb 

seems ok to me, but I'm probably not best to review

**Comment by alexcrichton** [comment]
@bors: p=1

fixes a regression, so I think we'll want to land this soon hopefully

**Comment by nikomatsakis** [comment]
Marking as beta-accepted. Small (if...dense) patch, regression. cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
Definitely we want a test here...

**Comment by eddyb** [comment]
@nikomatsakis IIRC we had a test but it wasn't running on the bots, @alexcrichton knows more.

**Comment by alexcrichton** [comment]
Oh yes #37429 should have been prevented from landing in the first place due to it causing a regression to an existing test that this PR fixes. That test was erroneously not running and has since been fixed to run on all PRs.

In that sense I believe we've already got tests checked in for this.

**Comment by camlorn** [comment]
I'm not sure what dense means but suspect it is bad; if you're referring to the description and the commit it's because I don't fully understand what's going on.  @eddyb gets credit for this fix, and they tried to explain but not with much luck, I'm afraid.

I forget which test specifically checks this, but there are already tests examining closure-local variables.

**Comment by nikomatsakis** [comment]
@camlorn I didn't mean dense in a bad way, just meant that there are few lines changed, but the correctness of the changes is non-obvious -- although re-reading they actually look pretty simple.

**Pull request merged**
