### PR TITLE
Format sources into the error message when loading codegen backends

### PR DESCRIPTION
**Pull request by nagisa**
cc https://github.com/rust-lang/rustc_codegen_cranelift/issues/1447
cc @bjorn3

### CODE REVIEW

**Comment by bjorn3** [comment]
Thanks!

**Comment by nagisa** [comment]
Full disclosure: As an alternative approach I have also explored `impl<E>`ing `From<E> for DiagnosticMessage` and similar. While that's way more reusable in the end, I felt like there are too many design questions that come up as a result of doing so for a PR as this:

* How do we format the stuff printed?
* How do we allow adding additional context to the errors we want to output like this? Do we allow pulling in something like `anyhow`?
* etc.

I think it may still be wortwhile to add an ability to print plain `std::error::Error`s nicely  to the diagnostic infrastructure, but that’s better off as its own change.

**Pull request merged**
