### PR TITLE
Turn duration consts into associated consts

### PR DESCRIPTION
**Pull request by ghost**
As suggested in https://github.com/rust-lang/rust/issues/57391#issuecomment-459658236, I'm moving `Duration` constants (`SECOND`, `MILLISECOND` and so on; currently behind unstable `duration_constants` feature) into the `impl Duration` block.

cc @frewsxcv @SimonSapin

### CODE REVIEW

**Comment by oli-obk** [comment]
O_o we have zero tests using these?

Can you add a bunch of tests (maybe just as doctests on the constants showing a usage example)?

r? @oli-obk

**Comment by stjepang** [comment]
@oli-obk Seems so 😅 I've added a few doctests on the constants now.

**Comment by oli-obk** [comment]
:+1: 

@bors r+

**Pull request merged**
