### PR TITLE
Inline a few functions.

### PR DESCRIPTION
**Pull request by nnethercote**
r? @ghost

### CODE REVIEW

**Comment by nnethercote** [comment]
Uniformly good results except for `diesel`. Local profiling shows that the inlining of `super_fold_with` causes the regressions for `diesel`, so I'll do another perf run without that to see the overall effects.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Perf results look slightly better without the `super_fold_ty` inlining.

r? @lqd

**Comment by lqd** [comment]
Great finds, @bors r+

**Pull request merged**
