### PR TITLE
Fix `include!()`s inside `asm!()` invocations

### LINKED ISSUE #34812: `include!` uses the wrong search path when it is inside an `asm!` macro invocation
For example, `include_str!` invocation [here](https://github.com/QuiltOS/libfringe/blob/6f30dc8e12025ad2ab426bc82d8974619143dd24/src/arch/x86/mod.rs#L8) in [this expansion](https://github.com/QuiltOS/libfringe/blob/6f30dc8e12025ad2ab426bc82d8974619143dd24/src/arch/x86_common.rs#L24) should search in `src/arch` but instead searches in `src/arch/x86`.

### PR DESCRIPTION
**Pull request by jseyfried**
Fixes #34812, a regression caused by #33749 that was not fixed in #34450.
r? @nrc

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @Ericson2314

**Comment by jseyfried** [comment]
@nrc I think we'll want to back-port this to beta.

**Comment by nikomatsakis** [comment]
@jseyfried is this specific to `asm!`, or a problem that could affect other macros?

If the former, there is no reason to backport since `asm!` is only usable on nightly anyhow.

**Comment by nikomatsakis** [comment]
Added beta-accepted on the assumption that is indeed a problem more general than `asm!`

**Comment by jseyfried** [comment]
@nikomatsakis This also applies to `env!(include!("..."))`, which is stable but seems highly unlikely in the wild.

**Pull request merged**
