### PR TITLE
Use assume to inform the optimiser about refcount invariants

### LINKED ISSUE #13018: Room for optimization improvement on reference counting
[Playground](https://play.rust-lang.org/?gist=de1039ef3cd4812b29c5c759e7645722&version=nightly&mode=release)

I would expect this function to be ideally optimized to a no-op:

``` rust
#[inline(never)]
fn foo<T>(t: &Rc<T>) {
    drop(t.clone());  
}
```

However, when invoked with `Rc<int>`, we generate the following optimized IR

``` llvm
; Function Attrs: noinline nounwind uwtable
define internal fastcc void @_ZN3foo20h529f5691b0db4704gaa4v0.0E(%"struct.std::rc::Rc<int>[#1]"* nocapture readonly) unnamed_addr #3 {
entry-block:
  %1 = getelementptr inbounds %"struct.std::rc::Rc<int>[#1]"* %0, i64 0, i32 0
  %2 = load %"struct.std::rc::RcBox<int>[#1]"** %1, align 8
  %3 = getelementptr inbounds %"struct.std::rc::RcBox<int>[#1]"* %2, i64 0, i32 1
  %4 = load i64* %3, align 8
  %5 = add i64 %4, 1
  store i64 %5, i64* %3, align 8
  %6 = load %"struct.std::rc::RcBox<int>[#1]"** %1, align 8
  %7 = icmp eq %"struct.std::rc::RcBox<int>[#1]"* %6, null
  br i1 %7, label %_ZN3mem4drop20hf8ea12715443e741vda4v0.0E.exit, label %then-block-241-.i.i.i

then-block-241-.i.i.i:                            ; preds = %entry-block
  %8 = getelementptr inbounds %"struct.std::rc::RcBox<int>[#1]"* %6, i64 0, i32 1
  %9 = load i64* %8, align 8
  %10 = add i64 %9, -1
  store i64 %10, i64* %8, align 8
  %11 = icmp eq i64 %10, 0
  br i1 %11, label %then-block-262-.i.i.i, label %_ZN3mem4drop20hf8ea12715443e741vda4v0.0E.exit

then-block-262-.i.i.i:                            ; preds = %then-block-241-.i.i.i
  %12 = getelementptr inbounds %"struct.std::rc::RcBox<int>[#1]"* %6, i64 0, i32 2
  %13 = load i64* %12, align 8
  %14 = add i64 %13, -1
  store i64 %14, i64* %12, align 8
  %15 = icmp eq i64 %14, 0
  br i1 %15, label %then-block-270-.i.i.i, label %_ZN3mem4drop20hf8ea12715443e741vda4v0.0E.exit

then-block-270-.i.i.i:                            ; preds = %then-block-262-.i.i.i
  %16 = bitcast %"struct.std::rc::RcBox<int>[#1]"* %6 to i8*
  tail call void @free(i8* %16) #2
  br label %_ZN3mem4drop20hf8ea12715443e741vda4v0.0E.exit

_ZN3mem4drop20hf8ea12715443e741vda4v0.0E.exit:    ; preds = %entry-block, %then-block-241-.i.i.i, %then-block-262-.i.i.i, %then-block-270-.i.i.i
  ret void
}
```

I would expect that we would be able to do better.

### PR DESCRIPTION
**Pull request by Aatch**
The reference count can never be 0, unless we're about to drop the data
completely. Using the `assume` intrinsic allows us to inform LLVM about
that invariant, meaning it can avoid unnecessary drops.

---

Before and after IR: https://gist.github.com/Aatch/3786d20df2edaad6a0e8

Generated from the example in #13018

Fixes #13018

### CODE REVIEW

**Comment by alexcrichton** [comment]
Nice win! It seems like there's still room for improvement as there's still a [check for null](https://gist.github.com/Aatch/3786d20df2edaad6a0e8#file-rc-after-ll-L12-L13), so perhaps this shouldn't close #13018 but rather just update the IR?

**Comment by Aatch** [comment]
@alexcrichton Oh, I missed that. I should be able to tell it to assume that the pointer is non-null.

**Comment by Aatch** [comment]
Ok, so I updated this to add assumptions that pointer is non-null in a couple places.

New IR: https://gist.github.com/Aatch/3786d20df2edaad6a0e8#file-rc-after2-ll

That has some junk that isn't required because it's only there for the `assume`s, so the assembly looks like this: https://gist.github.com/Aatch/3786d20df2edaad6a0e8#file-rc-after2-s

**Comment by alexcrichton** [comment]
r=me with some comments on each `assume` explaining why it's there and what optimizations it's gaining us

Nice find!

**Comment by alexcrichton** [comment]
If the rollup bounced again I may have to back this out, it looks like we've taken a serious hit in compile times based on this patch. I did a `perf record` of building stage0 rustc and got: https://gist.github.com/alexcrichton/479ddc775aec259fd04a

Spending 10% of our time in computing knowledge from assumptions seems like quite a lot!

**Comment by alexcrichton** [comment]
To put this into concrete numbers:

```
# stage0 liballoc with assumptions compiled in
$ time ./x86_64-unknown-linux-gnu/stage0/bin/rustc -O ./src/librustc/lib.rs --out-dir foo
./x86_64-unknown-linux-gnu/stage0/bin/rustc -O ./src/librustc/lib.rs --out-di  610.62s user 2.01s system 99% cpu 10:12.68 total

# stage0 liballoc without assumptions compiled in
$ time ./x86_64-unknown-linux-gnu/stage0/bin/rustc -O ./src/librustc/lib.rs --out-dir foo
./x86_64-unknown-linux-gnu/stage0/bin/rustc -O ./src/librustc/lib.rs --out-di  202.90s user 1.70s system 99% cpu 3:24.62 total

```

**Comment by Aatch** [comment]
Ugh, ouch. That's surprising, but not entirely unexpected. The assumption tracker framework is relatively new in LLVM, so it's not too surprising that it hasn't been tuned as much as it could be. I'm fine with pulling the PR if it has that much of a negative effect on compile times.

**Comment by alexcrichton** [comment]
Could you measure the impact on just having the assumptions on reference counting? The assumptions on `deref` may be overloading the compiler, but perhaps `deref` happens an order of magnitude more often than `clone`?

**Comment by alexcrichton** [comment]
Ah sorry this didn't actually merge (had to revert the commits). Feel free to make a new PR though!

**Pull request merged**
