### PR TITLE
Rollup of PRs in the queue; Friday

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by michaelsproul** [comment]
It seems the error commits are a bit messed up. Leave them out of this rollup and I'll create a separate PR.

**Comment by Manishearth** [comment]
I'll try one last time, if it still fails I'll remove them all.

**Comment by michaelsproul** [comment]
Or that! :laughing:

**Comment by Manishearth** [comment]
@bors: retry force

segfault? O.o

**Comment by michaelsproul** [comment]
That's odd...

**Comment by Manishearth** [comment]
@michaelsproul Go ahead and make the separate PR. I'll focus on getting the non problematic stuff merged. :smile:

**Comment by michaelsproul** [comment]
Ok great, I'm going to bed now but I'll do one tomorrow :smile:

**Comment by Manishearth** [comment]
*sigh* can't repro locally on Linux :/

**Comment by pnkfelix** [comment]
@Manishearth I'll look to see if I can repro.

**Comment by Manishearth** [comment]
Thanks!

**Comment by pnkfelix** [comment]
I cannot reproduce locally.  :(

**Comment by alexcrichton** [comment]
@bors: retry

Looks like one of the git folders on the OSX builders got corrupted from a build cancelled-to-soon causing all future builds to fail.

**Pull request merged**
