### PR TITLE
optimize `places_conflict` to avoid complex vectors etc

### LINKED ISSUE #51820: [nll] optimize `places_conflict`... somehow
`places_conflict` currently accounts for 8% of MIR borrowck time. Most of that time, based on `perf annotate` results, seems to be spent in and around the `SmallVec` operations (e.g., `push` and `into_iter`). The tricky part here is that the `Place` data structures we are using are setup as a kind of tree, so that `x.a.b` is sort of like this:

- Projection of `b` from:
  - Projection of `a` from:
    - Local variable `x`

But we want to iterate "bottom up", so `x`, then `a`, then `b`. This doesn't lend itself to a simple iterator so we currently build up a `SmallVec` of results. 

It might be a win instead to build up a (stack-allocated) linked list by recursively "unrolling" the paths for both sides. Or perhaps dong other experiments, such as sharing a `Vec` buffer (that seemed a bit tricky from a type perspective when I looked into it).

Longer term, I'd like to move away from using `Place` here (and perhaps change how `Place` is setup in MIR) but it seems worth trying to tackle this in a targeted way.

### PR DESCRIPTION
**Pull request by nikomatsakis**
Fixes #51820

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum did you ever do a perf run here? I did a few further edits...but it'd be interesting to see a run with the first set of commits.

**Comment by Mark-Simulacrum** [comment]
Not yet I think, let's start another one with the latest set though too.

@bors try

**Comment by Mark-Simulacrum** [comment]
Links for when perf is done:

The first try: https://perf.rust-lang.org/compare.html?start=142c98dd5a9fbd60c13e62a5c1358a40ee622dbb&end=c2d26676c063f01d952f57ba7667a1d130040fe6&stat=instructions%3Au

Second: https://perf.rust-lang.org/compare.html?start=4aff10bb1b9b202bb6464f99d198d3e6f49e6991&end=6aab1bdec35316cba3eab1844942230df4b6dc42&stat=instructions%3Au

**Comment by kennytm** [comment]
Second run is also ready.

**Comment by kennytm** [comment]
@bors retry 

```
failures:
---- net::tcp::tests::connect_timeout_unbound stdout ----
thread 'net::tcp::tests::connect_timeout_unbound' panicked at 'called `Result::unwrap_err()` on an `Ok` value: TcpStream { addr: V4(127.0.0.1:3605), peer: V4(127.0.0.1:3605), socket: 728 }', libcore\result.rs:945:5
failures:
    net::tcp::tests::connect_timeout_unbound
```

**Pull request merged**
