### PR TITLE
Add an official do-while loop to the core lib

### PR DESCRIPTION
**Pull request by GuillaumeLestringant**
I know we have [this horrible hack](https://gist.github.com/huonw/8435502) to act like a do-while loop, but it would seem wiser to have a nice macro that will always work instead.

### CODE REVIEW

**Comment by GuillaumeLestringant** [comment]
OK, I don’t get it, what’s wrong with Travis?

**Comment by bjorn3** [comment]
Please use unstable instead of stable, because new features dont start as stable normally.

Also the build error is a tidy error:
```
tidy check (x86_64-unknown-linux-gnu)

* 462 error codes

* highest error code: E0578

/checkout/src/libcore/macros.rs:568: different `since` than before

thread 'main' panicked at 'some tidy checks failed', /checkout/src/tools/tidy/src/main.rs:55

note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by rkruppe** [comment]
Why should this do into core, instead of living on crates.io as most of the ecosystem does?

**Comment by bluss** [comment]
The macro has problems, for example `continue;` does not work like in a while loop (it skips the conditional). This would be better to develop out of tree. Maybe use the [internals forum](http://internals.rust-lang.org/) to discuss design before proposing it as a new feature.

**Pull request closed without merging**
