### PR TITLE
[Do not merge, perf only] Try enabling NewGVN

### PR DESCRIPTION
**Pull request by nikic**
GVN commonly takes up 5-10% of the compilation time and the new sparse GVN implementation is supposed to be much faster.

This is not suitable for merging in this form, but I'd like to get a perf run to see if this is something worth looking into.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: try

Nice!

cc @rust-lang/infra

**Comment by alexcrichton** [comment]
(cc for the perf run that is)

**Comment by shepmaster** [comment]
For those reading along at home, I assume it's this:

> Global value numbering (GVN) is a compiler optimization based on the static single assignment form (SSA) intermediate representation. It sometimes helps eliminate redundant code that common subexpression elimination (CSE) does not.

- [Value numbering](https://en.wikipedia.org/wiki/Value_numbering)

**Comment by nikic** [comment]
Also assertion failure on the alt try run:

> [00:37:50] rustc: /checkout/src/llvm/lib/Transforms/Scalar/NewGVN.cpp:3285: void (anonymous namespace)::NewGVN::verifyIterationSettled(llvm::Function &): Assertion `BeforeCC->isEquivalentTo(AfterCC) && "Value number changed after main loop completed!"' failed.

So, looks like this is not quite ready for prime time yet. LLVM 7 has a couple of fixes for this issue (mostly phi-of-ops related), so probably this is something to try again after the LLVM 7 upgrade.

**Comment by nox** [comment]
@nikic Could you link to the upstream LLVM fixes? We can alway backport it in our tree and try again, right?

**Comment by nikic** [comment]
@nox Related to this assertion: https://github.com/llvm-mirror/llvm/commit/141e6bde5ce81b806f31eb252c609efd0f24d00f, https://github.com/llvm-mirror/llvm/commit/73d8c2e5e3ea37135e4e89fe243d94831aa73a96. Other NewGVN bugs: https://github.com/llvm-mirror/llvm/commit/41985cbc8e0de532a118c6f57dc59fbf51869e2f, https://github.com/llvm-mirror/llvm/commit/832f2bf0d8908aea8160bab128708d521764fe8d. Might be worth pulling these into a rust/llvm fork and trying again, to see if this fixes the issues or we might have something new to report.

**Comment by nikic** [comment]
I cherry-picked the mentioned patches locally. Unfortunately seeing a segfaults in src/test/rustdoc/issue-18199.rs:

```
#0  0x00007fffe6a0d060 in ?? ()
#1  0x00005555557a3d8e in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hb9eec09583bb707c ()
#2  0x00007ffff3a94e03 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h53f037bb127012d1 ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libtest-c79d24ea4c4766b2.so
#3  0x00007ffff23b091a in __rust_maybe_catch_panic ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libstd-72fc73250c737cd2.so
#4  0x00007ffff3aab8ee in std::sys_common::backtrace::__rust_begin_short_backtrace::h25f25e1e96dde5fb ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libtest-c79d24ea4c4766b2.so
#5  0x00007ffff3ac8185 in std::panicking::try::do_call::h1e947f9784f95f13 ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libtest-c79d24ea4c4766b2.so
#6  0x00007ffff23b091a in __rust_maybe_catch_panic ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libstd-72fc73250c737cd2.so
#7  0x00007ffff3aad5c7 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h6d53f833c8f8ba98 ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libtest-c79d24ea4c4766b2.so
#8  0x00007ffff23a332b in std::sys_common::thread::start_thread::h12aa3fa026a33681 ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libstd-72fc73250c737cd2.so
#9  0x00007ffff236e676 in std::sys::unix::thread::Thread::new::thread_start::hbcfc644f83802907 ()
   from /home/nikic/rust/build/x86_64-unknown-linux-gnu/stage2/bin/../lib/libstd-72fc73250c737cd2.so
#10 0x00007ffff20ff6ba in start_thread (arg=0x7fffe6fff700) at pthread_create.c:333
#11 0x00007ffff1c1f41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by nikic** [comment]
I've submitted https://reviews.llvm.org/D46974 to fix bugs in assume() handling, but this did not make the rustc miscompiles better...

**Comment by nikic** [comment]
I'm giving up on this one, I wasn't able to figure out what the issue is or come up with a good reproduce case.

**Comment by nikic** [comment]
Filed https://bugs.llvm.org/show_bug.cgi?id=37540 for the issue that's probably causing the rustc miscompiles.

**Pull request closed without merging**
