### PR TITLE
Rename Iterator::get_unchecked

### LINKED ISSUE #76479: regression: get_unchecked resolves to unstable feature use
* https://crater-reports.s3.amazonaws.com/beta-1.47-1/beta-2020-08-29/reg/algebraics-0.2.0/log.txt

Unclear if this is a genuine regression or something else is going on, but seems like at least plausibly some change to resolution is involved.

### PR DESCRIPTION
**Pull request by matthewjasper**
Closes #76479

r? @pnkfelix

### CODE REVIEW

**Review by spastorino — APPROVED** [review]

**Comment by spastorino** [comment]
@bors p=1
as it fixes a `P-critical` issue.

Waiting for CI to `r+`

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/43744weeklymeeting2020100154818.html#211916216) in T-compiler meeting.

@rustbot modify labels: beta-accepted

**Comment by matthewjasper** [comment]
#77308 backported this

**Pull request merged**
