### PR TITLE
Run base::internalize_symbols() even for single-codegen-unit crates.

### PR DESCRIPTION
**Pull request by michaelwoerister**
The initial linkage-assignment (especially for closures) is a conservative one that makes some symbols more visible than they need to be. While this is not a correctness problem, it does force the LLVM inliner to be more conservative too, which results in poor performance. Once translation is based solely on MIR, it will be easier to also make the initial linkage assignment a better fitting one. Until then `internalize_symbols()` does a good job of preventing most performance regressions.

This should solve the regressions reported in https://github.com/rust-lang/rust/issues/34891 and maybe also those in https://github.com/rust-lang/rust/issues/34831.

As a side-effect, this will also solve most of the problematic cases described in https://github.com/rust-lang/rust/issues/34793. Not reliably so, however. For that, we still need a solution like the one implement in https://github.com/rust-lang/rust/pull/34830.

cc @rust-lang/compiler

### CODE REVIEW

**Comment by TimNN** [comment]
I benchmarked #34891 again with a local build of this pr and (as long as I haven't messed up) performance remains unchanged (that is, #34891 was not fixed by this pr as far as I can tell).

**Comment by eddyb** [comment]
@michaelwoerister I would expect #34831 to be fixed by this, not necessarily #34891.

**Comment by michaelwoerister** [comment]
@TimNN Interesting. I have benchmarked that use case and it seemed to be fixed for me. Maybe *I* have messed up somewhere? I'll give it another try tomorrow.

@eddyb Really? I would have thought the other way round.

**Comment by michaelwoerister** [comment]
> @TimNN Interesting. I have benchmarked that use case and it seemed to be fixed for me. Maybe I have messed up somewhere? I'll give it another try tomorrow.

It seems it did mess up something with a last minute refactoring `:/`
There should be a `==` instead of a `!=` here:
 https://github.com/rust-lang/rust/blob/8052f73d7b53d55781e49fc36e109312293a31d5/src/librustc_trans/base.rs#L2289

**Pull request merged**
