### PR TITLE
ARM Target Docs Update

### PR DESCRIPTION
**Pull request by Lokathor**
Updates the ARM target docs, drawing more attention to the `arm-none-eabi` target group by placing all targets *within* that group as a sub-list in the Table of Contents.

Also updates the `armv4t-none-eabi` page (maintainer signoff: I'm that target's maintainer) to clarify that the page covers the arm version and the thumb version of the target, but that the target group page has the full info because there's nothing really specific to say for those targets.

### CODE REVIEW

**Comment by ehuss** [comment]
According to https://github.com/rust-lang/rust/pull/124404#pullrequestreview-2028964566, and per Arm's website, they appear to be using Title case for "Arm", so I think the changes to all-caps seems to be going against recent changes. Can that change perhaps be dropped, and try to consistently use that form?

**Comment by Lokathor** [comment]
well, I'm with jonathanpallant, but yeah I can change that back

**Comment by ehuss** [comment]
Thanks!

@bors r+ rollup

**Comment by thejpster** [comment]
Sorry, I didn't see this PR at the time.

The extra space before "Again, these ISAs have been revised..." doesn't make sense as it only applies to the T32 ISAs.

Also, whilst Arm do insist on being called Arm, and I can tolerate renaming the old ARMv4 specification to Armv4 (because arguably renaming the specification retroactively renames all the versions, old and new), I think renaming ARM1 to Arm1 is a mistake because that was a specific model of CPU made by Acorn and it was never retroactively renamed.

**Comment by Lokathor** [comment]
Uh, this PR is from months ago, but feel free to open a new one if you want further tweaks. There's always room for improvement.

**Pull request merged**
