### PR TITLE
[WIP] Attempting to handle case insensitive case.

### PR DESCRIPTION
**Pull request by avborhanian**
This is an attempt at dealing with #25879.

Basically ensure_dir and item_path both now use a map to identify what path to use where it's like 
```
{
    lower_case_path_to_item: {
         original_path: correct_value_to_use
    }
}
```
If the item isn't in the map, then we can use the original location. If something already points to that location, I append a number based on how many other items are in the map to the folder name or item name, store that in the map, and then return said path / item name. ensure_dir gained a sibling function called ensure_dir_lower because if a path overlaps but it's technically a different module, we need to give a new destination to use.

So as an example of how this works, if we're seeing the situation

```
pub struct FoO;
pub struct Foo;
```

Then the first one is entered as struct.FoO.html. The second struct Foo would be considered overlapping since they share the same lowered version, and its url becomes struct.foo.1.html. This works with the modules too, so if two modules had the same names as the structs above, we'd see a folder created for foo and foo.1

Things I have questions about:
1. Is there a better naming method to use? I know Windows generally does things as " (1)", but don't know what would be appropriate for the web.

2. Should I potentially be using different variables for things like cached_dir?
I had to wrap cached_dir with a mutex because I wanted to make sure we didn't run into a situation with parallelization where two overlapping paths check and see if the folder path had been created, see it hasn't, and then both create the same path. But that mutex would now affect the case sensitive path too. Is there a better way of locking just the lowered version of the function, or maybe another way of handling that situation in general?

3. The way I have to build the new url in `fn append` feels pretty inefficient, and didn't know if there was a better way of handling it.

Also definitely need to update that option to not always be true.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I made a try at this [here](https://github.com/rust-lang/rust/pull/59785). The problem is a bit more complicated than it might look like. :)

**Comment by avborhanian** [comment]
Haha, yeah I figured 100%. Mainly because of the fact that old URL links would possibly break with a new generation. Are there other things beyond that? Just curious what other difficulties there are.

**Comment by GuillaumeGomez** [comment]
No, it was mostly trying to do it without adding too much burden. However, I didn't (and still don't...) have enough time to implement fully what I have in mind.

**Comment by avborhanian** [comment]
if you don't mind, can I play around with this pull request more? Don't want to annoy you while I push stuff is why I'm asking.

**Comment by GuillaumeGomez** [comment]
No problem, go ahead! Maybe you'll find a better solution than mine. :)

**Pull request closed without merging**
