### PR TITLE
Update stdsimd

### LINKED ISSUE #51691: `std::arch::x86::has_cpuid()` alternates between `true` and `false` when `CPUID` is supported
The code in question is [here](https://doc.rust-lang.org/src/core/up/stdsimd/coresimd/x86/cpuid.rs.html#82-111). The bug is on line 99 where the OR should be XOR.

This code demonstrates the bug.

``` rust
#![feature(stdsimd)]
use std::arch::x86;

fn main() {
    assert_eq!(x86::has_cpuid(), x86::has_cpuid());
}
```

I expected to see this happen: `x86::has_cpuid()` should be idempotent and thus the assertion should be satisfied.

Instead, this happened:

```
$ rustc --target i686-apple-darwin bug.rs
$ ./bug
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', bug.rs:5:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

## Meta

```
rustc 1.28.0-nightly (f28c7aef7 2018-06-19)
binary: rustc
commit-hash: f28c7aef7fbff1909c2d0257186cd7a5f0c6aa4b
commit-date: 2018-06-19
host: x86_64-apple-darwin
release: 1.28.0-nightly
LLVM version: 6.0
```

### PR DESCRIPTION
**Pull request by est31**
Closes #51691

### CODE REVIEW

**Comment by est31** [comment]
Added WIP label to wait for https://github.com/rust-lang-nursery/stdsimd/pull/492

**Comment by est31** [comment]
Please also beta backport as it makes some functions deprecated... better deprecate them sooner rather than later.

**Comment by kennytm** [comment]
@est31 What functions are deprecated? Are they already public on 1.28?

**Comment by kennytm** [comment]
@bors r-

Cannot compile on s390x due to rust-lang-nursery/stdsimd#467. Error log: https://github.com/rust-lang/rust/pull/51782#issuecomment-400027487

```
[00:25:19] Intrinsic has incorrect return type!
[00:25:19] void (<16 x float>*, <16 x float>*)* @llvm.fabs.v16f32
[00:25:19] LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by kennytm** [comment]
rust-lang-nursery/stdsimd#498 has been fixed by  rust-lang-nursery/stdsimd@60826e789eca2711495b96903f0195ce5c34c428, please update the submodule again.

**Comment by est31** [comment]
I'll wait till #51810 is resolved.

**Comment by gnzlbg** [comment]
@est31 that might take a while, I'd rather update `stdsimd` again when its resolved than let it diverge longer. The `s390x` failures should have been caught weeks/months ago.

**Comment by est31** [comment]
@gnzlbg sure!

**Comment by kennytm** [comment]
@est31 The commit 32e3c7d doesn't update simd to   rust-lang-nursery/stdsimd@60826e789eca2711495b96903f0195ce5c34c428 though. It is only updated to rust-lang-nursery/stdsimd@fd3a3f248156c24a40baaf9824c03ef8dce00163.

screenshot_2018-06-27 00 00 27_oqu2ds-fs8

**Comment by gnzlbg** [comment]
So for some reason the `wasm32-unknown-unknown` CI build bot of `stdsimd` did not catch this. I'll try to update the build bot to reproduce the error, and then the solution will be similar to the one for `s390x-unknown-linux-gnu`, that is, fall back to scalar code for `wasm32-unknown-unknown`, at least for some of the functions.

**Comment by est31** [comment]
Just removing wasm and starting a try run to find out whether bors has something else to stumble over
@bors try

**Comment by kennytm** [comment]
@est31 In the future please avoid `try`ing a full set of builders. This will block the regular bors queue on Travis due to limited concurrent builders.

**Comment by alexcrichton** [comment]
@est31 is this PR ready to go? Or is it still waiting for more testing?

**Comment by est31** [comment]
@alexcrichton the wasm failure still needs to be fixed. @gnzlbg said they'll look into it. I only made sure that no other platform than wasm was having issues.

**Comment by gnzlbg** [comment]
@est31 so I think I found the issue. https://github.com/rust-lang/rust/blob/master/src/etc/wasm32-shim.js#L109 needs to be updated with the missing functions. At most those should be `sin`, `cos`, `sqrt`, `fma`, and `sqrte`.

**Comment by alex** [comment]
It appears that as a result of this, things linking against only `core`, now expect there to be `sin`/`cos`/`sqrt` symbols from somewhere.

Was this known/expected? Is there by chance a discussion about this somewhere that I couldn't find?

**Comment by gnzlbg** [comment]
@alex not expected but we have seen the partial downfall of that here due to the wasm issues. Could you file an issue? Also, on which platform is this happening?

cc @alexcrichton are the types `f32` and `f64` part of `core` ? because if they are, then any math on any platform that llvm cannot do by itself is going to add a dependency on `libm` or similar. As in, this problem should not be just related to `stdsimd`, but `f32` member functions should have this problem as well (otherwise I don't know what's going on).

**Comment by alex** [comment]
@gnzlbg #52301, thanks!

**Pull request merged**
