### PR TITLE
Run rustfmt on librustc_mir/hair/cx

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by brson** [comment]
This PR seems to add an entire file, `pattern.rs`. I imagine this is an accident since it is just running rustfmt. Can you remove that file from the PR and rebase?

Sorry for the delay in review.

**Comment by eddyb** [comment]
@brson Presumably rather than rebasing it'd be better to just reset to master and run `rustfmt` again.

**Comment by srinivasreddy** [comment]
I will be on vacation until Dec 1st. Will do it afterwards only.

**Comment by mrhota** [comment]
@srinivasreddy ping?

**Comment by srinivasreddy** [comment]
@mrhota  Will do it today. Thanks for the ping.

**Comment by pnkfelix** [comment]
@srinivasreddy I still see a `pattern.rs` file in the diff; didn't @brson ask you to remove that file from the PR?

**Comment by srinivasreddy** [comment]
@pnkfelix Done. sorry, i missed that.

**Pull request merged**
