### PR TITLE
add `#[rustc_pass_by_value]` to more types

### PR DESCRIPTION
**Pull request by lcnr**
the only interesting changes here should be to `TransitiveRelation`, but I believe to be highly unlikely that we will ever use a non `Copy` type with this type.

### CODE REVIEW

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
r=me if you don't want to do a perf run here (I assume that perf is the motivation)

**Comment by lcnr** [comment]
@bors try @rust-timer queue

perf wasn't really the intention, it was mostly to remove a bunch of `&` and `*`, but perf can be impacted here

**Comment by lcnr** [comment]
a bunch of small improvements 

@bors r=davidtwco rollup=never

**Comment by lcnr** [comment]
is that one spurious? Can't seem to find the test which was causing the failure

**Pull request merged**
