### PR TITLE
NLL: fix E0594 "change to mutable ref" suggestion

### LINKED ISSUE #51515: NLL: E0594 removes first char of variable name
When I build this code on nightly...

```rust
#![feature(nll)]

fn main() {
    let foo = &16;
    *foo = 32;
    let bar = foo;
    *bar = 64;
}
```

...I get these errors:

```none
error[E0594]: cannot assign to data in a `&` reference
 --> src/main.rs:5:5
  |
4 |     let foo = &16;
  |               --- help: consider changing this to be a mutable reference: `&mut 16`
5 |     *foo = 32;
  |     ^^^^^^^^^

error[E0594]: cannot assign to data in a `&` reference
 --> src/main.rs:7:5
  |
6 |     let bar = foo;
  |               --- help: consider changing this to be a mutable reference: `&mut oo`
7 |     *bar = 64;
  |     ^^^^^^^^^
```

The first error is fine, but the second one is missing the first character of `foo`. It looks like rustc assumes the first character is an `&` and removes it without checking.

## Meta

`rustc --version --verbose`:
```none
rustc 1.28.0-nightly (1d4dbf488 2018-06-11)
binary: rustc
commit-hash: 1d4dbf488a4364413e7b9611866b7a5c75ce566f
commit-date: 2018-06-11
host: x86_64-unknown-linux-gnu
release: 1.28.0-nightly
LLVM version: 6.0
```

### LINKED ISSUE #51879: Compiler with NLL feature gives mangled suggestion text for E0596
Compiling this code ([playground](https://play.rust-lang.org/?gist=51465ba2338cc7c3175f69d482da1cd4&version=nightly&mode=debug)):

```
#![feature(nll)]

use std::collections::{HashMap};

fn main() {
    let map: HashMap<u32, Vec<u32>> = HashMap::new();
    for (_, nodes) in map.iter() {
            nodes.retain(|&n| n == 3);
    }
}
```

Gives this error:

```
error[E0596]: cannot borrow immutable item `*nodes` as mutable
 --> src/main.rs:8:13
  |
7 |     for (_, nodes) in map.iter() {
  |             ----- help: consider changing this to be a mutable reference: `&mut odes`
8 |             nodes.retain(|&n| n == 3);
  |             ^^^^^ `nodes` is a `&` reference, so the data it refers to cannot be borrowed as mutable

```

See that it creates a recommendation of using "`&mut odes`" which assumes I had an `&nodes` in my source code.

A similar error is seen here ([playground](https://play.rust-lang.org/?gist=f617fbf57eeca5d13d9c1928431b387a&version=nightly&mode=debug)) where it chops off the value being iterated over instead of the value being bound to the iterator's Item.

```
5 |     for nodes in vector.iter() {
  |                  ------------- help: consider changing this to be a mutable reference: `&mut ector.iter()`
```

Removing the `#![feature(nll)]` causes there to be less suggestion text from the compiler, and thus does not have this bug.

### PR DESCRIPTION
**Pull request by ashtneoi**
Fix #51515.
Fix #51879.

Questions:
- [x] Is this the right place to fix this? It feels brittle, being so close to the frontend. **It's probably fine.**
- [ ] Have I missed any other cases that trigger this behavior?
- [x] Is it okay to use HELP and SUGGESTION in the UI test? **Yes.**
- [x] Do I need more tests for this? **No.**

### CODE REVIEW

**Comment by ashtneoi** [comment]
I broke some tests, didn't I. Gimme a sec.

**Comment by ashtneoi** [comment]
Okay, I think this is ready for review. Sorry about that.

**Comment by pnkfelix** [comment]
Hmm I think I may rebase this atop #51275 myself, preserving authorship, just to get it integrated into that rewrite of `check_access_permissions`. The core idea, namely checking whether the extracted snippet starts with `&` or `ref ` (including that crucial space character at the end), is a good one.

**Comment by ashtneoi** [comment]
Sounds good! Do you need anything from my end?

**Comment by ashtneoi** [comment]
Side note: I just realized I should be matching any whitespace character after `ref`, not just U+0020. No idea how to do that.

**Comment by ashtneoi** [comment]
https://github.com/ashtneoi/rust/tree/51515-missing-first-char-spaces

Here's my idea for properly matching the whitespace after `ref`. No idea whether it's useful. Let me know if you want me to do something with it.

**Comment by ashtneoi** [comment]
Should I rebase or merge?

**Comment by eddyb** [comment]
@ashtneoi Always rebase, for Rust PRs.

**Comment by ashtneoi** [comment]
Sorry, still working on the rebase---having some trouble finding where the "ref mut" part should go. I'll let y'all know if I can't figure it out.

**Comment by nikomatsakis** [comment]
@ashtneoi sorry for the radio silence here! @pnkfelix had an unexpected issue and hasn't been able to review PRs etc and I didn't realize this was here. I can try to help you rebase maybe in a bit, but if you want, please do [drop in on Zulip where the NLL working group hangs out](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/), maybe we can help?

**Comment by nikomatsakis** [comment]
in any case, i've assigned this to myself so that I will notice it on my daily PR sweeps =)

**Comment by ashtneoi** [comment]
@nikomatsakis Hey, thanks for the update. I was busy with other things today, but I'll throw some questions up on Zulip tomorrow if things still aren't making sense.

**Comment by nikomatsakis** [comment]
@ashtneoi ok, I read the code. It seems pretty reasonable. Regarding your questions:

> Is this the right place to fix this? It feels brittle, being so close to the frontend.

Seems about right. The check to look at the source span... is probably good. It's hard to "construct" good suggestions without going back to the source bytes, ultimately, although it often feels a bit hokey. 

> Have I missed any other cases that trigger this behavior?

One thought I had was to check `&self` etc. Something like this:

```rust
struct Foo { x: u32 }

impl Foo {
  fn update(&self) {
    self.x += 1;
  }
}
```

Does this give a bad suggestion?

> Is it okay to use HELP and SUGGESTION in the UI test?

Yes

> Do I need more tests for this?

No

**Comment by nikomatsakis** [comment]
@ashtneoi can you verify that this also fixes https://github.com/rust-lang/rust/issues/51879 ?

**Comment by ashtneoi** [comment]
Been kinda busy the past few days, but tomorrow (Wednesday) night I should have some time to look at #51879 and finish rebasing. #51275 changed some aspects of how we do "add `mut`" suggestions and [this in particular](https://github.com/rust-lang/rust/blame/a739c51d/src/librustc_mir/borrow_check/mod.rs#L1823) was giving me trouble last time I looked at it. Once I figure out the code path for `ref` bindings the rest should be straightforward. Sorry for all the delays.

**Comment by ashtneoi** [comment]
Status report: I think I have most of a solution and I just need to glue everything together. I'll stop trying to fit everything into a single commit and just push what I have tomorrow (Monday).

**Comment by ashtneoi** [comment]
As suggested by @.pnkfelix on Zulip, I'm narrowing the scope to just issue #51515 (`&mut oo`).

**Comment by ashtneoi** [comment]
This also fixes #51879 (which means it's a dup of #51515).

**Comment by ashtneoi** [comment]
I'm not a huge fan of case (1.) [here](https://github.com/ashtneoi/rust/blob/6800deafd451499bcf62b16e868d893001922b9c/src/librustc_mir/borrow_check/mod.rs#L1877), but I can live with it, and more importantly I think this PR is done. Hopefully I learned my lesson about trying to do too much at once.

**Comment by ashtneoi** [comment]
Actually `&self` seem to trigger a different code path so never mind about that part of the test.

**Pull request merged**
