### PR TITLE
relax leak-check

### PR DESCRIPTION
**Pull request by aliemjay**
Please see https://github.com/rust-lang/rust/pull/112999#issuecomment-1630536235 for a background on this change.

This is a BREAKING CHANGE!

This makes us reject the following as overlapping impls, which is obviously true if we consider the implicit bounds on the binder `'a == 'b`. So this is a bug fix.
```rust
trait Trait {}
impl<T> Trait for for<'a, 'b> fn(&'a &'b (), &'b &'a ()) -> &'a () {}
impl<T> Trait for for<'a, 'b> fn(&'a &'b (), &'b &'a ()) -> &'b () {}
```

Note that we keep supporting the case of [`wasm-bindgen`][wasm], which historically prevented us from making `coherence_leak_check` a hard error:

[wasm]: https://github.com/rust-lang/rust/blob/a2a7516b5c4057140c326b6f3cca85c526053669/tests/ui/coherence/coherence-wasm-bindgen.rs

```rust
trait Trait {}
impl<T> Trait for fn(&T) {}
impl<T> Trait for fn(T) {}
```

However, a less intuitive change is that we now reject this:
```rust
type A = for<'a, 'b> fn(&'a (), &'b ()) -> &'a ();
type B = for<'a, 'b> fn(&'a (), &'b ()) -> &'b ();

trait Trait {}
impl Trait for A {}
impl Trait for B {}
```

I think this breakage is justified given that we already emit a back-compat lint and that it never shows in crater.

Another justification for this breakage is that it makes adding "sane" implication bounds to binders a backward-compatible change. For instance, the reason why the impls from the last snippet are now considered overlapping is because the types `A` and `B` can be made equal by adding some implication bounds:
```rust
type A = for<'a,     'b: 'a> fn(&'a (), &'b ()) -> &'a ();
type B = for<'a: 'b, 'b    > fn(&'a (), &'b ()) -> &'b ();
```

I think it's reasonable to make the addition of such bounds a non-breaking change.

Implication bounds on a binder are considered "sane" iff  the lower bound of the outlive relation is one of the bound regions of the binder. Examples are:

```rust
type A = for<'a, 'b> fn(&'b &'a u8); // 'a: 'b
type B<'a> = for<'b> fn(&'b &'a u8); // 'a: 'b
type C = for<'a> fn(&'a u8, Box<dyn for<'b> Fn(&'b &'a u8)>); // 'a: 'b
```

And here is an example of binders with insane implied bonds :)
```rust
// The following are invalid ..
type D<'a> = for<'b> fn(&'a &'b u8); // 'b: 'a
type E = for<'a> fn(&'a u8, Box<dyn for<'b> Fn(&'a &'b u8)>); // 'b: 'a
```

The reason behind this distinction is that one is arguably much more likely to see the first in practice. Moreover I think the types `D` and `E` are unnecessarily polymorphic in that they can be replaced by the more sane versions without changing behavior:
```rust
type F<'a> = fn(&'a &'a u8);
type G = for<'a> fn(&'a u8, Box<dyn Fn(&'a &'a u8)>);
```

r? @ghost

### CODE REVIEW

**Comment by aliemjay** [comment]
@craterbot check

**Comment by aliemjay** [comment]
(p=1 because it is a small list)
@craterbot run mode=check-only p=1 crates=https://crater-reports.s3.amazonaws.com/pr-112999/retry-regressed-list.txt

**Comment by compiler-errors** [comment]
Sorry, I'm not exactly if I understand the motivation for this PR. Does it relax checks that you consider too strict, or make checks stricter? Is it to fix existing bugs (issue #?) or to allow forward-compatibility for somethings we want in the future?

**Comment by aliemjay** [comment]
Here is a hopefully better description of this change..

Background: Higher-ranked subtyping succeeds unconditionally while registering region constraints to be checked post-inference during region resolution.

The leak check is responsible of judging if a higher ranked subtyping/equality holds before the full region resolution. It is used only in coherence and candidate evaluation. So by removing or relaxing the leak check, we are strictly accepting less code - more impls would be conidered overlapping and we would have more inference ambiguities due to a less powerful winnowing.

The leak-check was introduced with a future-incompat lint, `coherence_leak_check`, during the transition to universes, see #56105.

The intention was to remove the leak-check later after a warning period in order to maintain maximum forward compatibility. For instance, the current leak check accepts the following impls even though they overlap if we consider the future direction of using implicit bounds on binders.
```rust
trait Trait {}

// `'a and 'b are equal inside the binder
impl<T> Trait for for<'a, 'b> fn(&'a &'b (), &'b &'a ()) -> &'a () {}
impl<T> Trait for for<'a, 'b> fn(&'a &'b (), &'b &'a ()) -> &'b () {}
```
However one blocker of the full removal of the leak check was the case `wasm-bindgen`. All the crater regressions and all the user complaints in #56105 are variants of such case.
```rust
trait Trait {}
impl<'a> Trait for fn(&'a u8) {}
impl Trait for for<'a> fn(&'a u8) {}
```

This PR relaxes the leak-check in a way that keeps supporting the case of `wasm-bindgen` while breaking others. The way we distinguish the two is by introducing the concept of "sane" implied bounds on binders. A higher-ranked subtyping/equality is rejected by the leak-check if and only if there is no possible set of sane implied bounds that can make the subtyping hold.
```rust
trait Trait {}

// These impls are accepted previously and now overlap under the new leak-check
// because we can add a set of sane implied bounds to both binders to make them equal:
// for<'a: 'b, 'b> fn(&'a u8, &'b u8) -> &'b u8;
// for<'a, 'b: 'a> fn(&'a u8, &'b u8) -> &'a u8;
impl Trait for for<'a, 'b> fn(&'a u8, &'b u8) -> &'b u8 {}
impl Trait for for<'a, 'b> fn(&'a u8, &'b u8) -> &'a u8 {}

// A variant of wasm-bindgen...
// This is still supported by the new leak check
// There is no set of *sane* implied bounds we can add to the binders that makes the impls overlap
// The only bound that can be added to the binder in order to make the types equal is this:
// for<'a: 'static> fn(&'a u8);
// but this is not a sane implied bound by definition (see below).
impl Trait for fn(&'static u8) {}
impl Trait for for<'a> fn(&'a u8) {}
```

For The definition of sane bounds see the the OP

> Implication bounds on a binder are considered "sane" iff the lower bound of the outlive relation is one of the bound regions of the binder.

**Comment by BoxyUwU** [comment]
@rfcbot concern deep-dive

I think I would like for us to have a deep dive about this before merging this. The interactions of this imo are really subtle and the direction this PR takes is at odds with some other things that have been thought about in the type system. I filed rust-lang/types-team#96 about this.

sidenote: is it reasonable to register a concern of "we should have a deep dive about this" I feel like yes but also I'm worried it might be a bit annoying since it will be a While until we can do a deep dive (almost two weeks into next month I think)

**Comment by lcnr** [comment]
I think that concern is valid. I don't think we can reasonably approve this change without such a deep dive

**Comment by QuineDot** [comment]
Can you explain how equality is defined with regards to the following quotes?

> the types A and B can be made equal by adding some implication bounds:
> ```rust
> type A = for<'a,     'b: 'a> fn(&'a (), &'b ()) -> &'a ();
> type B = for<'a: 'b, 'b    > fn(&'a (), &'b ()) -> &'b ();
> ```

> ```rust
> // These impls are accepted previously and now overlap under the new leak-check
> // because we can add a set of sane implied bounds to both binders to make them equal:
> // for<'a: 'b, 'b> fn(&'a u8, &'b u8) -> &'b u8;
> // for<'a, 'b: 'a> fn(&'a u8, &'b u8) -> &'a u8;
> impl Trait for for<'a, 'b> fn(&'a u8, &'b u8) -> &'b u8 {}
> impl Trait for for<'a, 'b> fn(&'a u8, &'b u8) -> &'a u8 {}
> ```

I recognize they are both "return the shorter of the two input borrows", but they are still different in that you can call (excuse the abuse of notation) `A::<'local, 'static>` but not `B::<'local, 'static>` (and `B::<'static, 'local>` but not `A::<'static, 'local>`.  ([Playground.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c0f543fc4bc40c88306e2203c29113fb))

But I also recognize that we're talking about *function pointers*, not function item types.  Is the idea that function pointers never have parameters, and thus can never be turbofished?  

Even if that's the case, can't one still do something like this?
```rust
<A as Fn<(&(), &'static ())>>::call(&a, (&local, statik));

// (This works with `for<'x> fn(&'x (), &'static ()) -> &'x ()` 
// but I'm unaware of a way to play with bounds in binders)
```
And doesn't that mean some sort of definition of equality is still in order?

**Comment by BoxyUwU** [comment]
Going to close this since it hasn't really had anything happen in over half a year. feel free to reopen if you want to work on this again

**Pull request closed without merging**
