### PR TITLE
Make note bold

### PR DESCRIPTION
**Pull request by ghost**
~~this seems to be have occurred in a recent edit, i clearly remember just note being bold~~

the entire note was bold

### CODE REVIEW

**Comment by jyn514** [comment]
Oops, I broke this in https://github.com/rust-lang/rust/pull/105465/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L11.

@bors r+ rollup

**Comment by gimbles** [comment]
@jyn514 look at the newer commit, the commit which is r+'ed just bolds "note", but i was wrong in that and the whole note was in bold

**Comment by gimbles** [comment]
the new..new commit, my bad (ugh this is a mess)

**Pull request merged**
