### PR TITLE
Fix rustdoc missing handling of remap-path-prefix option

### LINKED ISSUE #69264: rustdoc: use remap-path-prefix
The rust compiler has an option `--remap-path-prefix` for remapping path prefixes. It's useful to avoid runtime messages that are independent of where the source code was located during the build.

As far as I can tell that doesn't apply to `rustdoc`'s `<meta>` info "Source to the Rust file ...", which (to me) is unexpected.

### Meta

```
$ rustc --version --verbose
rustc 1.40.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.40.0
LLVM version: 8.0
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/69264.

cc @weihanglo 
r? @notriddle

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Fixed fmt...

**Comment by weihanglo** [comment]
One question: Should rustdoc respect `-Zremap-path-scope`?

From my understanding, besides doctest, the only thing needing to be remapped in rustdoc is diagnostics. Rustdoc might not need to be aware of any scope. Cargo can determine and pass `--remap-path-prefix` accordingly. Hence my personal anwser to this is no.

**Comment by GuillaumeGomez** [comment]
My answer will be: if you can find a case where it's useful, I can add it. :)

**Comment by weihanglo** [comment]
> From my understanding, besides doctest, the only thing needing to be remapped in rustdoc is diagnostics. 

Is there anything that contains absolute/original source path in rustdoc generated artifacts?

**Comment by GuillaumeGomez** [comment]
Not that I can think of.

**Pull request merged**
