### PR TITLE
compiletest: Simplify multi-debugger support

### PR DESCRIPTION
**Pull request by tmiasko**
Previous implementation used a single mode type to store various pieces
of otherwise loosely related information:

* Whether debuginfo mode is in use or not.
* Which debuggers should run in general.
* Which debuggers are enabled for particular test case.

The new implementation introduces a separation between those aspects.
There is a single debuginfo mode parametrized by a debugger type.
The debugger detection is performed first and a separate configuration
is created for each detected debugger. The test cases are gathered
independently for each debugger which makes it trivial to implement
support for `ignore` / `only` conditions.

Functional changes:

* A single `debuginfo` entry point (rather than `debuginfo-cdb`, `debuginfo-gdb+lldb`, etc.).
* Debugger name is included in the test name.
* Test outputs are placed in per-debugger directory.
* Fixed spurious hash mismatch. Previously, the config mode would change
  from `DebugInfoGdbLldb` (when collecting tests) to `DebugInfoGdb` or
  `DebugInfoLldb` (when running them) which would affect hash computation.
* PYTHONPATH is additionally included in gdb hash.
* lldb-python and lldb-python-dir are additionally included in lldb hash.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This looks like an awesome cleanup, thanks so much @tmiasko!

@bors: r+

**Comment by tmandry** [comment]
It _looks_ like this failed in https://github.com/rust-lang/rust/pull/68470#issuecomment-577435896, @bors r-

**Comment by tmiasko** [comment]
Updated so that gdb remains disabled on msvc targets.

**Pull request merged**
