### PR TITLE
Remove `mips*-unknown-linux-gnu*` builders

### PR DESCRIPTION
**Pull request by workingjubilee**
Pursuant to the current consensus in https://github.com/rust-lang/compiler-team/issues/648

### CODE REVIEW

**Comment by workingjubilee** [comment]
...of course I forget to r? @ghost

**Comment by tgross35** [comment]
(asking for my own curiosity, not really suggesting anything) is there a need to remove all the `dist-mips` folders? It seems likely enough that they may be reenabled at some point, so maybe worth keeping them in tree with history and all? Or moved to a different directory if some tool automatically looks for the `dist-x` dirs

**Comment by Nilstrieb** [comment]
git preserves all history, if one needs to be a git historian.

**Comment by workingjubilee** [comment]
Given that commits can also be easily reverted, I have received a recommendation that we *should* in fact remove these builders immediately, rather than waiting, as the burden has made it so essentially every PR merged lately has had at least one bors retry. Which is fine by me, assuming that I did this correctly and everyone's on board. I will remove the "formally change the platform support page" commit to another PR.

**Comment by klensy** [comment]
But there some folder with promising name https://github.com/rust-lang/rust/tree/master/src/ci/docker/host-x86_64/disabled

**Comment by nikic** [comment]
I don't think this should touch anything more than the CI configuration.

**Comment by workingjubilee** [comment]
So just https://github.com/rust-lang/rust/pull/113274/commits/634f95295f5e977380a520b6651e74192755654c ?

**Comment by jyn514** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Drop.20MIPS.20to.20tier.203.20compiler-team.23648/near/372165737:

> I think an easy workaround is to land now, and revert on (future) beta. We can get past the bugs with a couple retries on the beta + stable compiler builds, but this fixes most folks builds now.

@bors r+ p=50 rollup=never

**Comment by compiler-errors** [comment]
gonna bump this auto build out of the queue, hope that's the right step here to make sure things don't get worse :(

@bors retry

**Comment by compiler-errors** [comment]
(haha, bors probably wouldn't have even merged 634f95295f5e977380a520b6651e74192755654c because it's not a fast forward.)

**Comment by BoxyUwU** [comment]
this shouldn't be merged, the commit that was added with a r=<try> needs to be deleted before other things land I think?

**Comment by compiler-errors** [comment]
@bors p=50
@bors retry

^^

**Comment by compiler-errors** [comment]
I think this can resume build now, thanks @Mark-Simulacrum for fixing the tree.

@bors r=jyn514 
@bors treeclosed-

**Comment by compiler-errors** [comment]
The merge looks correct

**Comment by compiler-errors** [comment]
Or not?

**Comment by compiler-errors** [comment]
Actually, that looks like a previous auto-merge, not this one.

https://github.com/rust-lang/rust/pull/113274#issuecomment-1620638580

**Comment by workingjubilee** [comment]
should this retry then?

**Comment by compiler-errors** [comment]
No need -- it's merging successfully in https://github.com/rust-lang-ci/rust/actions/runs/5457834781

**Comment by workingjubilee** [comment]
Weird.

**Pull request merged**
