### PR TITLE
Fix the span information created by TokenStream's FromStr impl

### LINKED ISSUE #48944: `Span` issues with `FromStr` in unstable `proc_macro`
While writing improved tests for `proc_macro2`, I noticed some surprising behaviour of the `FromStr` impl for `proc_macro::TokenStream`.

When parsing a string with `FromStr`, a token parsed from the very beginning of the string can have a different `source_file()` than a token parsed elsewhere. For example:

```rust
let tokens = "aaa\nbbb".parse::<proc_macro::TokenStream>().unwrap().into_iter().collect::<Vec<_>>();
println!("span: {:?}", tokens[0].span);
println!("source_file: {:?}", tokens[0].span.source_file());
println!("");
println!("span: {:?}", tokens[1].span);
println!("source_file: {:?}", tokens[1].span.source_file());
```

Will produce the output:
```
span: Span(Span { lo: BytePos(6734829), hi: BytePos(6734832), ctxt: #0 })
source_file: SourceFile { path: ProcMacroSourceCode, is_real: false }

span: Span(Span { lo: BytePos(50), hi: BytePos(58), ctxt: #25 })
source_file: SourceFile { path: Real("pm_test.rs"), is_real: true }
```

I would've expected both tokens to have the same context, and similar BytePos-es. Specifically I would have expected both of these tokens to have a span located in a fake ProcMacroSourceCode file, but set to resolve in the context of the enclosing scope (as if span.resolved_at(Span::call_site()) was called).

### PR DESCRIPTION
**Pull request by mystor**
This patch makes 3 changes:

1. `StringReader` would not update its `peek_span` or `span` fields when
   `override_span` was set, so this was moved into a method which
   updates the internal state.
2. `StringReader` was changed to hold a `DUMMY_SP` instead of a `None`
   for `override_span`, this decreases the size of `StringReader` and
   set's us up for (3).
3. `StringReader::mk_sp` was changed to copy the `override_span`'s
   `SyntaxContext`, even if `override_span` was `DUMMY_SP`.
4. `proc_macro::TokenStream::FromStr` was updated to set the
   `override_span` to be based on `DUMMY_SP` instead of `call_site`.

This means that the line/column information for all tokens in the parsed
string will be correct, while also using the call site's hygiene
information.

Fixes #48944

### CODE REVIEW

**Comment by mystor** [comment]
r? @jseyfried 

(I think you're probably the person to review this?)

**Comment by shepmaster** [comment]
Ping from triage, @jseyfried !

**Comment by mystor** [comment]
There are still some tests which are failing which I haven't had the time to figure out, so it's probably ok if you don't get around to reviewing it for a bit.

**Comment by pietroalbini** [comment]
Ping from the triage team @mystor! Will you have time to finish this PR in the near future?

**Comment by pietroalbini** [comment]
Thank you for this PR @mystor! Unfortunately we haven't heard from you in a while, so I'm going to close this to keep things tidy.

Don't worry though, we would be happy to get this merged! If you'll have time in the future to work on this again please reopen the PR, and we'll review it!

**Pull request closed without merging**
