### PR TITLE
[beta] next

### PR DESCRIPTION
**Pull request by brson**
- https://github.com/rust-lang/rust/pull/39913
- https://github.com/rust-lang/rust/pull/39730
- https://github.com/rust-lang/rust/pull/39674
- https://github.com/rust-lang/rust/pull/39602
- https://github.com/rust-lang/rust/pull/39586
- https://github.com/rust-lang/rust/pull/39471
- #39980
- #40020 
- https://github.com/rust-lang/rust/pull/40135

@nikomatsakis [this commit](https://github.com/rust-lang/rust/commit/3787d33889cf16887cf791c0cc14466950ac14b1) did not pick cleanly. You might peek at it.

I took the liberty of accepting all the nominations myself, but the [packed struct alignment](https://github.com/rust-lang/rust/pull/39586) PR is quite large. It did pick fine though and there's a comment there suggesting it works on beta cc @rust-lang/compiler.

cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: p=1

(beta branch_

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by nikomatsakis** [comment]
@brson diff looks ok to me re: that commit

**Comment by alexcrichton** [comment]
@bors: retry

* android bot ran out of disk space?

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault #38878

**Comment by alexcrichton** [comment]
@bors: retry

* #39003

**Comment by arielb1** [comment]
```
$ mkdir -p deploy/$TRAVIS_COMMIT

mkdir: cannot create directory ‘deploy’: No space left on device
```

**Comment by alexcrichton** [comment]
@bors: retry

* network failure

**Comment by eddyb** [comment]
> mkdir: cannot create directory ‘deploy’: No space left on device

**Comment by alexcrichton** [comment]
Attempting to handle in https://github.com/rust-lang/rust/pull/40135

**Comment by alexcrichton** [comment]
@bors: retry

* network error

**Comment by alexcrichton** [comment]
@bors: retry

* nothing failed?

**Comment by alexcrichton** [comment]
My guess is that it's yet another spurious failure, but I can't read the logs, so I'll wait to find out.

**Comment by alexcrichton** [comment]
@bors: retry

* osx linker segfault #39003

**Pull request merged**
