### PR TITLE
Bump nightly to 1.37.0

### PR DESCRIPTION
**Pull request by emilyalbini**
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by mati865** [comment]
Possible deadlock in check builds? 3 hangs in a row don't look like a coincidence.

**Comment by pietroalbini** [comment]
Confirmed locally that enabling parallel rustc compilation deadlocks compiling libsyntax. cc @Zoxc

**Comment by Zoxc** [comment]
I have a workaround in https://github.com/rust-lang/rust/pull/60967

**Pull request merged**
