### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by ehuss**
11 commits in e3563dbdcd2e370bc4f11d080f739d82d25773fd..d0f828419d6ce6be21a90866964f58eb2c07cd56
2019-07-16 19:22:44 +0000 to 2019-07-23 21:58:59 +0000
- Remove include/exclude glob warning. (rust-lang/cargo#7170)
- Optimize lock file format for git merge conflicts (rust-lang/cargo#7070)
- Set up CI with Azure Pipelines (rust-lang/cargo#7139)
- Force clippy to run. (rust-lang/cargo#7157)
- Work around rust-lang/rust#61440 (rust-lang/cargo#7158)
- initial working version of cargo fix --clippy (rust-lang/cargo#7069)
- Optimize runtime of `#[cargo_test_macro]` (rust-lang/cargo#7146)
- Don't fail if we can't acquire readonly lock (rust-lang/cargo#7149)
- Add support for multiple --features options (rust-lang/cargo#7084)
- Fix a typo in an env var name (rust-lang/cargo#7145)
- Add a way to disable all nightly tests (rust-lang/cargo#7142)

### CODE REVIEW

**Comment by ehuss** [comment]
Tools error is #62811, everything passed otherwise.

**Comment by pietroalbini** [comment]
@bors r-

Hijacking this PR to test my `LinuxTools` fix. My commit should be removed before reapproving this PR.

**Comment by pietroalbini** [comment]
Sorry for disrupting the PR!

@bors r=alexcrichton p=1

**Comment by alexcrichton** [comment]
@bors: retry

* https://github.com/rust-lang/rust/issues/62967

**Pull request merged**
