### PR TITLE
Add `#[inline]` to `Vec`'s `Deref/DerefMut`

### PR DESCRIPTION
**Pull request by nbdd0121**
This should help #97552 (although I haven't verified).

### CODE REVIEW

**Comment by the8472** [comment]
The `linked_artifact` numbers decrease for some `full` benchmarks (e.g. ripgrep and cargo). So even though more stuff gets inlined it produces less code, that's probably a good sign.

**Comment by klensy** [comment]
> The `linked_artifact` numbers decrease for some `full` benchmarks (e.g. ripgrep and cargo). So even though more stuff gets inlined it produces less code, that's probably a good sign.

You can check few other perf runs and see, that changes in `linked_artifact` metric isn't rare (for example, there exist change even in #97489, which is pure rustdoc: https://perf.rust-lang.org/detailed-query.html?commit=855fc022fe879f4e3493a024f9c6b981d6317612&base_commit=6999ef25645dcfcfd4e7092e448385ab3b73e44c&benchmark=ripgrep-13.0.0-opt&scenario=full. Btw, why there any changes at all?)

**Comment by the8472** [comment]
Well, they're 10x larger, but you're right, without knowing the variance it might still be noise.

**Comment by Mark-Simulacrum** [comment]
I've personally seen this many times in local profiling, so I think it's worth doing this. Hopefully opaque pointers indeed fix this case though in the future.

@bors r+ rollup=never

**Pull request merged**
