### PR TITLE
Clarify "length" wording in `Vec::with_capacity`.

### LINKED ISSUE #49448: Improve documentation for std::vec::Vec::with_capacity
Can the note "doesn't specify the length" be understood as "leaves length uninitialized"? As this is not the case, maybe something like "specifies the length 0" would be more informative?

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/rust-lang/rust/issues/49448.

### CODE REVIEW

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
This looks good to me, but if someone from @rust-lang/libs could sign off as well, that'd be great.

**Review by dtolnay — APPROVED** [review]
This is correct. Thank you!

**Pull request merged**
