### PR TITLE
[Experiment] Force to generate drop glue of ADT locally

### PR DESCRIPTION
**Pull request by csmoe**
cc https://github.com/rust-lang/rust/issues/84175#issuecomment-927983624
r? @ghost
@michaelwoerister May I have a perf run on this? If so, how can I perf on `share-generics` vs `no-share-generics`.

### CODE REVIEW

**Comment by Kobzol** [comment]
Nice! I wanted to try this, but didn't know how to do it properly. It won't help with generic drop glues, but I'm interested whether it can help at least a bit with non-generic ones.

**Comment by csmoe** [comment]
@oli-obk git blame shows that you implemented the [drop glue collection](https://github.com/rust-lang/rust/blame/48291a9dda821a81957b44034572c0ec62728f35/src/librustc_mir/monomorphize/collector.rs#L1007) in #30900 
Does my diff match my purpose here?

**Comment by oli-obk** [comment]
That PR is by @michaelwoerister, but it's also ages ago...

**Comment by jrmuizel** [comment]
What's needed to get this merged? An investigation of the performance regression?

**Pull request closed without merging**
