### PR TITLE
[stable] 1.31.1 point release

### PR DESCRIPTION
**Pull request by emilyalbini**
Rust 1.31.1 is scheduled to be released on Thursday 20th, with the following changes:

* #56562: Update libc version required by rustc *(different patch made by me)*
* #56615: Update the book to fix some edition-related bugs
* rls submodule update to [`b379ef7`](https://github.com/rust-lang/rls/commit/b379ef76a1e3ab5cbc7e0010e2751f992fa3b62a), including:
  * https://github.com/rust-lang/rls/pull/1170: Fix for common infinte loop regression
  * https://github.com/rust-lang/rls/issues/1171: Can't jump to std defs

r? @Mark-Simulacrum 
cc @rust-lang/core @rust-lang/release

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
r=me with Travis passing

**Comment by pietroalbini** [comment]
Ping @nrc, can you look at the test suite failure for RLS?

**Comment by pietroalbini** [comment]
Updated the RLS submodule to fix the failing test.

@bors r=Mark-Simulacrum p=1000

**Comment by pietroalbini** [comment]
Thanks @Xanewok for fixing the RLS test!

@bors r=Mark-Simulacrum p=1000

**Pull request merged**
