### PR TITLE
Remove the grammar.

### PR DESCRIPTION
**Pull request by steveklabnik**
This is completely vestigial, and we have a grammar WG whose job it is to handle the grammar.

This is a revival of https://github.com/rust-lang/rust/pull/50835; if accepted, I'll have to update the reference as well. 

r? @rust-lang/lang i think? I forget who is the lead of wg-grammar. @nikomatsakis ?

### CODE REVIEW

**Comment by Centril** [comment]
@qmx is WG-grammar lead.

I use `parser-lalr.y` all the time when doing language design (it still is accurate to a certain extent) so I'd prefer not to see it go. I'd like these to remain until we have a more fully formed grammar or at least move this to a different location (but that would break some links in the interim so I'd rather not do that as well...).

**Comment by Centril** [comment]
Clarification: I'd like us to remove this eventually, but I think it's too soon.

**Comment by eddyb** [comment]
cc @rust-lang/wg-grammar

**Comment by qmx** [comment]
Added https://github.com/rust-lang-nursery/wg-grammar/issues/9 to track this work lest we forget. Hopefully we'll be able to get to this soon!

**Comment by TimNN** [comment]
Ping from triage @qmx / @rust-lang/wg-grammar: Do I understand correctly, that this PR shouldn't be merged for now?

**Comment by qmx** [comment]
@TimNN yes, that is correct - feel free to close this PR and we'll get back to it later

**Pull request closed without merging**
