### PR TITLE
Pull changes from rust-lang/rust-clippy

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Comment by lzutao** [comment]
Note: This PR helps pushing  #72906 forward.

**Review by flip1995 — APPROVED** [review]

**Comment by lzutao** [comment]
Rebased and pulled changes from latest clippy. @Manishearth

**Comment by flip1995** [comment]
> Rebased and pulled changes from latest clippy.

Did you actually rebase anything pulled from Clippy with `git subtree` or did you just wrote that to keep your comment short? Rebases will lead to problems with `git subtree`

Also for the process in the future: Please use the default commit message, that is generated when executing `git subtree pull`. ("Merge commit '\<commit-hash\>' into \<branch\>"). This is the only way we can find out the current Clippy commit, without going through the history and searching for  a commit, the exists in both the rust and the rust-clippy repo.

For this it shouldn't matter though, since the next release is weeks away and I'm sure we'll do another sync by then.

**Comment by lzutao** [comment]
I reset to latest master and did `subtree pull` again.

**Comment by lzutao** [comment]
Rebased. Could you raise the build queue priority, @Manishearth ?

**Comment by lzutao** [comment]
@flip1995 Is the "merge commit" necessary to `subtree pull` to work properly?
IIRC the rust repo discourages the "merge commits".

**Comment by flip1995** [comment]
The merge commit is generated by `subtree pull`. We use it to easily find the clippy commit on releases. So I would say, it is necessary.

**Comment by lzutao** [comment]
Thank you but you might also want to reapprove this PR

**Comment by Mark-Simulacrum** [comment]
(FWIW if there's a general need for prioritization of clippy ups *despite* the move to subtree, that's surprising to me and we should discuss it at some point. One of the goals with moving away from submodules is avoiding the need to prioritize PRs like this; if that's not being met that may be acceptable but we should discuss).

**Comment by Manishearth** [comment]
@Mark-Simulacrum I mean, yes, these PRs need to be prioritized, but only because we make them much less often.

In the old world the PRs needed to be made every week and had to be prioritized to fix clippy. Now they need to be prioritized because:

 - It's easier to deal with git history when you make a sync PR with no extra commits sneaking in
 - It's easier to avoid merge conflicts

The prioritization is for a different reason, and since syncs are much more rare it shouldn't matter as much.

**Pull request merged**
