### PR TITLE
WIP: infrastructure for testing save-analysis

### PR DESCRIPTION
**Pull request by aochagavia**

### CODE REVIEW

**Comment by aochagavia** [comment]
@alexcrichton Do I need to edit a makefile or something to let the new tests run?

@nrc Do you like the direction of this PR? I included a test example so you can see how it works.

**Comment by alexcrichton** [comment]
The easiest thing to do will probably be to modify rustbuild (src/bootstrap/build/{mod.rs,step.rs}) to include this test suite like the other compiletest test suites, but if you want it to run with `make check` on the makefiles you'll also have to modify `mk/tests.mk`. We run both suites on the bots so as long as it's run somewhere it's fine. (note that it won't get run currently, though).

I also personally liked the approach in https://github.com/rust-lang/rust/issues/34481 of using annotations in the source as it seems much easier to write the test, but perhaps json was just easier to implement?

**Comment by nrc** [comment]
I do like the general approach. I think the example test should probably be less thorough to ensure that we are being a bit 'fuzzy'. E.g., just test that the function names exist and only test the line numbers, rather than the whole span or something. I would also like to see if we could include the JSON inline as a comment or something in the test file, I guess that could happen later if it is tricky.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to reopen with a rebase!

**Pull request closed without merging**
