### PR TITLE
Bump Miri

### PR DESCRIPTION
**Pull request by jonhoo**
Brings in https://github.com/rust-lang/miri/issues/972 and other fixes

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks!
@bors r+

**Comment by RalfJung** [comment]
Oops, looks like something is wrong.

@bors r-

**Comment by RalfJung** [comment]
Ah, that's the panic issue @Aaron1011 mentioned.

**Comment by RalfJung** [comment]
But why doesn't it trigger a toolstate failure...? It also works fine locally to run Miri against latest rustc master.

**Comment by RalfJung** [comment]
@christianpoveda the only failing test is
```
2019-10-10T21:40:58.9153389Z failures:
2019-10-10T21:40:58.9153599Z [ui] run-pass/file_manipulation.rs 
```
Any idea what could be going on? See [the build log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10412/logs/53) for more details.

**Comment by RalfJung** [comment]
My guess is that the working directory is not the same. You cannot rely on `./tests` to be the Miri tests folder; when running in Rust's CI the working dir is a different one.

Does it work to use `current_exe`?

This is a critical bug; it prevents us from updating Miri in rustc.

**Comment by christianpoveda** [comment]
I can change the test to create the file in cwd instead. would that fix the problem?

**Comment by RalfJung** [comment]
Hm, polluting the build dir isn't great either.

**Comment by jonhoo** [comment]
@RalfJung done!

**Comment by RalfJung** [comment]
Thanks!
@bors r+

**Comment by christianpoveda** [comment]
That's odd, I have no idea why creating the file is failing. Is it there some restriction about creating files in the build directory or something?

**Comment by RalfJung** [comment]
@bors r-

Yeah might be a permission thing.

**Comment by RalfJung** [comment]
Maybe we should use `/tmp/miri_test_fs.<random>.rs` as the filename? Or rather, copy some logic from `tempdir` for the base dir. (We cannot depend on crates in Miri's compiletests, I think.)

**Comment by RalfJung** [comment]
Oh wait, we have https://doc.rust-lang.org/nightly/std/env/fn.temp_dir.html, we don't need to copy anything. :)

**Comment by RalfJung** [comment]
@jonhoo we are using a temporary dir in Miri now; could you bump Miri again?

**Comment by jonhoo** [comment]
@RalfJung done

**Comment by RalfJung** [comment]
Thanks! This time let's wait until CI here in the PR is green before bothering bors.

@bors delegate+

Once CI *is* green, please do `bors r=RalfJung`.

**Comment by RalfJung** [comment]
Unfortunately, Miri got broken by https://github.com/rust-lang/rust/pull/64873

@bors r-

**Comment by RalfJung** [comment]
@jonhoo do you want me to take over? Might be easier if I do the update directly instead of asking you to do submodule bumps all the time.^^

Usually Miri updates work much smoother than this, but sometimes new things just keep coming up... this time, a combination of new filesystem tests and a libtest change and also https://github.com/rust-lang/rust/pull/64823 makes for quite a bumpy update.

**Comment by jonhoo** [comment]
Haha, that's probably easier! I'll close this and you open a new one?

**Comment by RalfJung** [comment]
Thanks; new one is at https://github.com/rust-lang/rust/issues/65356.

**Pull request closed without merging**
