### PR TITLE
Update rustc-guide submodule

### PR DESCRIPTION
**Pull request by mark-i-m**
New commits:

```
248d8af35e9423b92760d7fc2603d4df8a78345c add nomicon intro too
ef9bc9d610cad6dbe903a23bccf0447dd2a411c5 break rust
7b106f95466f1040e0c8b4af512ace2d9f2cd7b4 Add colon
fb3bf19590bf7dd24af507180bca6f5bf0c27d80 Move into rust-lang
1774649715ec84b80d8c887d913c91b83be56197 Minor fix in borrow_check
fc18a79ef688ee47ece5c736218d92537cf3bf63 Document `--pass $mode`
596e952f649e0aa8ef1f393d85b0df4bda4df4fe blacklist some commonly problematic links
06837ee64b2d4b9e08e1303b22f9aba7a9ff59cd Update experts' link
4936b7cbd53b477a3389c5bb655e92c5f3a2ff0c add humor appendix; closes #163
```

cc @ehuss (sorry for the trouble with the previous PR)

### CODE REVIEW

**Comment by ehuss** [comment]
I believe this will fail until #62759 is merged (rustc-guide won't appear in toolstate.json, and will fail the test-pass check).  I would recommend combining the two PRs.

**Comment by mark-i-m** [comment]
@frewsxcv Perhaps un-approve this PR so as not to cause the rollup-er consternation until we have sorted out the discussion in #62759 ?

**Comment by ProgrammaticNajel** [comment]
This PR appears to be blocked on #62759

**Pull request closed without merging**
