### PR TITLE
Revert "Auto merge of #83417 - erikdesjardins:enableremovezsts, r=oli-obk"

### LINKED ISSUE #88043: LLVM crash: Basic Block does not have terminator!
The following is minimized from https://crates.io/crates/lalrpop, which is regressed as of nightly-2021-08-15.

```rust
fn bump() -> Option<usize> {
    unreachable!()
}

fn take_until(terminate: impl Fn() -> bool) {
    loop {
        if terminate() {
            return;
        } else {
            bump();
        }
    }
}

fn main() {
    take_until(|| true);
}
```

```console
$ rustc +nightly-2021-08-14 main.rs
$ ./main
$ # :)

$ rustc +nightly-2021-08-15 main.rs
Basic Block in function '_ZN4main10take_until17h0067b8a660429bc9E' does not have terminator!
label %3
in function _ZN4main10take_until17h0067b8a660429bc9E
LLVM ERROR: Broken function found, compilation aborted!

$ rustc +nightly-2021-08-15 --version --verbose
rustc 1.56.0-nightly (8007b506a 2021-08-14)
binary: rustc
commit-hash: 8007b506ac5da629f223b755f5a5391edd5f6d01
commit-date: 2021-08-14
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### PR DESCRIPTION
**Pull request by erikdesjardins**
This reverts commit 8007b506ac5da629f223b755f5a5391edd5f6d01, reversing changes made to e55c13e1099b78b1a485202fabc9c1b10b1f1d15.

Fixes #88043

r? @oli-obk

### CODE REVIEW

**Comment by erikdesjardins** [comment]
No regression test because I can't get this to reproduce under the test harness, I assume I'm missing something obvious...it doesn't error as a codegen test (even with `// compile-flags: -Z verify-llvm-ir`, although I can see the invalid IR in the output), nor as a `build-pass` or `compile-pass` ui test. But `rustc +stage1 src/test/codegen/issue-88043-bb-does-not-have-terminator.rs` does error as expected. (Using the original test case from #88043)

**Comment by tmiasko** [comment]
> No regression test because I can't get this to reproduce under the test harness

It requires `-Copt-level=0`, since otherwise storage markers will be left in the target block following the function call.

**Comment by Mark-Simulacrum** [comment]
This was a perf [regression](https://perf.rust-lang.org/compare.html?start=aa8f27bf4d980023a8b245ceb25a490a18041eb2&end=806b3995b8f622d5de10afcc11c10a028a7b876a&stat=instructions:u), but is canceled out due to landing #88176 later in the week.

@rustbot label perf-regression perf-regression-triaged

**Pull request merged**
