### PR TITLE
associated_consts: check trait obligations and regionck for associated consts

### LINKED ISSUE #41323: rustc_typeck::check::compare_method::compare_const_impl doesn't drain its fullfillment context nor invoke regionck.
UPDATE: Mentoring instructions for fixing this bug [can be found here](https://github.com/rust-lang/rust/issues/41323#issuecomment-304301429).

---

There are [some calls](https://github.com/rust-lang/rust/blob/ae23e65eb8f207d0c9be82e7f2043d98a32d4f57/src/librustc_typeck/check/compare_method.rs#L734-L785) to add obligations to a fulfillment context but it's never checked.

Some examples of code that shouldn't compile:
```rust
trait TransmuteTarget: Sized {
    type Out: Sized;
}

// Can't use generic impl here.
impl TransmuteTarget for String {
    type Out = String;
}

trait Transmute: TransmuteTarget {
    const FROM: Self::Out;
}

impl<T: TransmuteTarget> Transmute for T {
    // Associated type projections aren't checked (obligation fulfillment).
    const FROM: &'static str = "foo";
}
```
```rust
trait Foo {
    const NAME: &'static str;
}

impl<'a> Foo for &'a () {
    // Lifetimes aren't checked (regionck).
    const NAME: &'a str = "unit";
}
```

cc @rust-lang/compiler

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #41323

r? @nikomatsakis

### CODE REVIEW

**Comment by arielb1** [comment]
This needs a crater run - people might have been trying to sneak things.

**Comment by seanmonstar** [comment]
A crater run? It's an unstable feature, and this fixes a soundness hole, as described in #41323.

**Comment by nikomatsakis** [comment]
I don't think that a crater run is needed for an unstable feature, but it'd be a kindness.

**Comment by nikomatsakis** [comment]
I'm going to kick off a crater run, but I'll r+ in the meantime.

**Comment by arielb1** [comment]
@seanmonstar 

Missed that this is in an unstable feature.

**Pull request merged**
