### PR TITLE
[perf] Change stable hasher to Blake2s

### PR DESCRIPTION
**Pull request by Urgau**
Based on https://github.com/rust-lang/rustc-stable-hash/compare/main...Urgau:rustc-stable-hash:blake2

With inputs from https://jszym.com/blog/short_input_hash/ and https://github.com/rust-lang/rust/pull/127754.

cc @michaelwoerister @Kobzol
r? ghost

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Given that blake is a cryptographic hash, any subslice of the hash should also be a good quality hash. So going to 128 or 64 bit hashes should not need to use the whole value.

**Comment by Kobzol** [comment]
Well, at least max RSS didn't regress now...

**Comment by Urgau** [comment]
Unfortunately it seems like Blake2s is also not fast enough for our use-case.

Therefore closing.

**Comment by bjorn3** [comment]
Do we need all uses of StableHasher to be collision free? I did expect some uses of StableHasher to need the hashes to be consistent between compilation sessions (thus using StableHasher), but not depend on collision freedom for correctness.

**Comment by the8472** [comment]
> With inputs from https://jszym.com/blog/short_input_hash/ 

That's measured in python. According to the related [HN discussion](https://news.ycombinator.com/item?id=39018504) those benchmarks are dominated by python function call overhead. So they're probably not a good indicator for hashing performance of a native rust impl.

To get good cryptographic performance for short inputs we probably need something specialized for that purpose that makes use of hardware acceleration like [Haraka](https://github.com/kste/haraka) ([rust impl](https://github.com/gendx/haraka-rs)). There are a few other ones

But such constructions are fairly new and not mainstream, so their cryptographic claims aren't battle-tested.

**Comment by Urgau** [comment]
> Do we need all uses of StableHasher to be collision free? I did expect some uses of StableHasher to need the hashes to be consistent between compilation sessions (thus using StableHasher), but not depend on collision freedom for correctness.

I don't know; @michaelwoerister probably knows better than me about that.

> > With inputs from [jszym.com/blog/short_input_hash](https://jszym.com/blog/short_input_hash/)
> 
> That's measured in python. According to the related [HN discussion](https://news.ycombinator.com/item?id=39018504) those benchmarks are dominated by python function call overhead. So they're probably not a good indicator for hashing performance of a native rust impl.

Yes, that's a valid point, and I agree that those absolute numbers are not to be trusted, but I still think that even taking into account the different overhead due to the bindings and python, that the overall ranking is still IMO informative.

> To get good cryptographic performance for short inputs we probably need something specialized for that purpose that makes use of hardware acceleration like [Haraka](https://github.com/kste/haraka) ([rust impl](https://github.com/gendx/haraka-rs); found on [cryptography exchange](https://crypto.stackexchange.com/q/84450))

Interesting, I will read more about it.

**Comment by michaelwoerister** [comment]
> Do we need all uses of StableHasher to be collision free? 

Yes, we want stable hashes to be [virtual unique](https://en.wikipedia.org/wiki/Fingerprint_(computing)#Virtual_uniqueness).

**Comment by Urgau** [comment]
There is a Blake2s Rust implementation that is hardware accelerated (SSE4.1 and AVX2), [`blake2s_simd`](https://crates.io/crates/blake2s_simd).
Let's try it, even through I'm not excepting much gain.

**Comment by michaelwoerister** [comment]
Haraka looks interesting. One thing to keep in mind is that we need the hash values to also be the same independent of platform. I.e. when cross compiling libstd, we need hashes computed on the host to match what will later be computed when the compiler is running on the target. If the target does not have an optimized implementation but still produces the same hash value, that would be OK though.

**Comment by michaelwoerister** [comment]
>  I did expect some uses of StableHasher to need the hashes to be consistent between compilation sessions (thus using StableHasher), but not depend on collision freedom for correctness.

To elaborate on that: there *might* cases like that but at least for DepNode, DefPathHash, StableCrateId, legacy-symbol-name hashes, and incr. comp. query result hashing we need there to be no collisions. For the first three of these we check for collisions and have never found one.

Overall, I prefer to just give the guarantee of virtual uniqueness for stable hashes.

**Comment by lqd** [comment]
> There is a Blake2s Rust implementation that is hardware accelerated (SSE4.1 and AVX2)

we build for x64-v1, so the hardware acceleration may incur also runtime checks

**Pull request closed without merging**
