### PR TITLE
pre-pre-pre-rfc: return tracing for `core::result::Result`

### PR DESCRIPTION
**Pull request by BGR360**
it's so pre you can't even see it

### CODE REVIEW

**Comment by BGR360** [comment]
ope I thought draft PRs weren't supposed to request review.

@kennytm this is just a demonstration of a not-fully-fledged out idea for project-error-handling, feel free to ignore!

**Comment by workingjubilee** [comment]
You can ask for
r? @ghost

**Comment by jyn514** [comment]
@BGR360 I'm going to close this for now untill you're ready for it to be reviewed - if you just want GitHub's diff view you can make a PR to your fork instead :)

**Pull request closed without merging**
