### PR TITLE
optimize char::to_digit and assert radix is at least 2

### PR DESCRIPTION
**Pull request by programmerjake**
approved by t-libs: https://github.com/rust-lang/libs-team/issues/475#issuecomment-2457858458

let me know if this needs an assembly test or similar.

### CODE REVIEW

**Comment by programmerjake** [comment]
turns out this code doesn't properly handle `@`, so I'll work on fixing that, should be a few minutes...

**Comment by okaneco** [comment]
I wrote this comment before the last force push. The latest commit is branchless but from my testing in the past, that regresses the greater-than-10 radix case because the decimal fast path is removed. It'd be helpful to see the [radix benchmark](https://github.com/rust-lang/rust/blob/c07aa1e17199e27f6f7ac8f3307bca7bda0084b6/library/core/benches/char/methods.rs) results to confirm this is an improvement.

https://rust.godbolt.org/z/9h14szYM7

---
_Previously written comment_
From my experience benchmarking this function, it's difficult to optimize this further than the current implementation. The current code generated tends to be the fastest for non-constant radix, decimal radix, and hexadecimal radix (or any greater-than-10 radix).

It looks like this will worsen performance for greater than decimal radices. Note the code path for converting `0-9` digits in `example::to_digit_hex`.
https://rust.godbolt.org/z/4a1947nsG - Current to_digit without the new assert conditions

**Comment by programmerjake** [comment]
fixed, and this should be decently optimized on x86_64:
https://rust.godbolt.org/z/MxW8MWa4Y
a function that calls `to_digit` in a loop over a slice of bytes to implement parsing
an integer (doesn't check for overflow) triggers LLVM's loop unswitching
to produce a separate loop for base <= 10 and base > 10:

# base <= 10:
```asm
        ; slice pointer in rdi, slice len in rsi
        ; loop index in r8, radix in rcx
        xor     edx, edx ; retval = 0
.LBB0_5:
        movzx   r9d, byte ptr [rdi + r8]
        add     r9d, -48 ; value = byte - '0'
        cmp     r9, rcx  ; if value >= radix {
        jae     .LBB0_9  ; branch to error exit }
        imul    rdx, rcx ; retval *= radix
        add     rdx, r9  ; retval += value
        inc     r8
        cmp     rsi, r8
        jne     .LBB0_5
```

# base > 10:
```asm
        ; slice pointer in rdi, slice len in rsi
        ; loop index in r8, radix in rcx
        xor     edx, edx        ; retval = 0
.LBB0_8:
        movzx   r10d, byte ptr [rdi + r8]
        mov     r11d, r10d
        or      r11d, 32        ; lower = byte | 0x20_u32
        add     r11d, -97       ; temp = lower.wrapping_sub('a' as u32)
        add     r11, 10         ; letter_value = temp as u64 + 10
        lea     r9d, [r10 - 48] ; value = byte - '0' as u32
        cmp     r10d, 58        ; if byte > '9' as u32 {
        cmovae  r9, r11         ; value = letter_value }
        cmp     r9, rcx         ; if value >= radix {
        jae     .LBB0_9         ; branch to error exit }
        mov     r9d, r9d        ; value = value as u32 as u64 -- unnecessary but llvm can't optimize out
        imul    rdx, rcx        ; retval *= radix
        add     rdx, r9         ; retval += value
        inc     r8
        cmp     rsi, r8
        jne     .LBB0_8
```

**Comment by programmerjake** [comment]
here's what I got on my desktop (Ryzen 7950X):
master is on 116fc31c5c82b7767c87101164a1afa3faea97fd
optimize-charto_digit is on aeffff8ecf84a0a49ee597fb41729f8de9972592
Assuming I'm interpreting it right, my change is slightly faster on all `to_digit` benches except base 36 where it's slightly slower. I'm guessing the pattern used is simple enough that the branch predictor can learn it exactly, which is not realistic for normal hex numbers, thereby making the conditional move exactly as expensive as a conditional branch.
I ran:
```bash
for b in master optimize-charto_digit; do git switch "$b"; for i in {1..3}; do RUST_BACKTRACE=1 ./x.py bench library/core -- to_digit > "$b".txt; done; done
```
on optimize-charto_digit:
```
benchmarks:
    char::methods::bench_to_digit_radix_10  33672.73/iter +/- 127.29
    char::methods::bench_to_digit_radix_16  33518.58/iter  +/- 67.57
    char::methods::bench_to_digit_radix_2   33725.32/iter  +/- 92.59
    char::methods::bench_to_digit_radix_36  35903.44/iter +/- 126.43
    char::methods::bench_to_digit_radix_var 23992.17/iter  +/- 63.16
```
on master:
```
benchmarks:
    char::methods::bench_to_digit_radix_10  34082.78/iter  +/- 78.49
    char::methods::bench_to_digit_radix_16  34077.87/iter  +/- 61.22
    char::methods::bench_to_digit_radix_2   34084.60/iter  +/- 77.45
    char::methods::bench_to_digit_radix_36  34445.12/iter +/- 252.94
    char::methods::bench_to_digit_radix_var 25113.80/iter  +/- 36.69
```

**Comment by okaneco** [comment]
Nice, it does look faster except that one case.

For radix-36, the assembly is different in this part.
https://rust.godbolt.org/z/qq4Y1erjG

```asm
; radix-36
        cmp     r8, 35
        ja      .LBB1_4
        lea     rdx, [rdx + 8*rdx]
        lea     rdx, [r8 + 4*rdx]
```
```asm
; radix-16
        cmp     r8, 15
        ja      .LBB1_4
        shl     rdx, 4
        or      rdx, r8
```

**Comment by rvolgers** [comment]
> Nice, it does look faster except that one case.
> 
> For radix-36, the assembly is different in this part using your original loop example. I wouldn't expect this difference to happen but I don't know enough about how the code is optimized. https://rust.godbolt.org/z/qq4Y1erjG

This is normal optimizations of multiplication by a constant.

> 
> ```assembly
> ; radix-36
>         cmp     r8, 35
>         ja      .LBB1_4
>         lea     rdx, [rdx + 8*rdx]
>         lea     rdx, [r8 + 4*rdx]
> ```

This means:
> rdx = rdx + (rdx * 8)
> rdx = r8 + (rdx * 4)

It uses the lea instruction to do multiplications by a factor of two and addition in a single instruction. It has factored multiplication by 36 into multiplication by 9 and then by 4.

> ```assembly
> ; radix-16
>         cmp     r8, 15
>         ja      .LBB1_4
>         shl     rdx, 4
>         or      rdx, r8
> ```

This means:
> rdx = rdx * 16
> rdx = rdx + r8

The first multiplication is done with a left shift because it's a power of two, and then addition is done with a bitwise or because it knows rdx and r8 never have the same bit set so carry is not an issue.

**Comment by joshtriplett** [comment]
@bors delegate+

@programmerjake Feel free to r+ when you're satisfied that it improves performance across the board.

**Comment by joshtriplett** [comment]
Speaking for myself and not the rest of the libs team, I think "faster for every case except base 36" seems entirely reasonable, given the relative rarity of that case.

**Comment by programmerjake** [comment]
> Speaking for myself and not the rest of the libs team, I think "faster for every case except base 36" seems entirely reasonable, given the relative rarity of that case.

so, since it's as fast as I can get it without spending a bunch of time I don't have, and isn't strictly an improvement due to the base 36 case, what should I do?

**Comment by joshtriplett** [comment]
@programmerjake I think we should merge it.

**Comment by workingjubilee** [comment]
compiler has a number of callsites here, let's not have this confound examining a rollup's performance.

@bors rollup=never

**Pull request merged**
