### PR TITLE
Add working example for E0617 explanation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @Dylan-DPC

### CODE REVIEW

**Comment by JohnTitor** [comment]
Failed in https://github.com/rust-lang/rust/pull/72612#issuecomment-634116702:

```
failures:

---- /Users/runner/runners/2.169.0/work/1/s/build/x86_64-apple-darwin/test/error-index.md - Rust_Compiler_Error_Index::E0617 (line 12015) stdout ----
Test executable failed (terminated by signal).


failures:
    /Users/runner/runners/2.169.0/work/1/s/build/x86_64-apple-darwin/test/error-index.md - Rust_Compiler_Error_Index::E0617 (line 12015)
```

@bors r-

**Comment by GuillaumeGomez** [comment]
Forgot to add `no_run`. Updated!

**Pull request merged**
