### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by Muscraft**
18 commits in 6087566b3fa73bfda29702632493e938b12d19e5..05364cb2f61a2c2b091e061c1f42b207dfb5f81f
2024-04-30 20:45:20 +0000 to 2024-05-03 16:48:59 +0000
- chore(deps): update msrv (3 versions) to v1.76 (rust-lang/cargo#13857)
- Stabilize `-Zcheck-cfg` as always enabled (rust-lang/cargo#13571)
- fix(lints): Prevent inheritance from bring exposed for published packages (rust-lang/cargo#13852)
- refactor: remove unnecessary branch for link binary on macOS (rust-lang/cargo#13851)
- perf(toml): Avoid inferring when targets are known (rust-lang/cargo#13849)
- Update continuous-integration.md: Include CircleCI reference (rust-lang/cargo#13850)
- chore(deps): update msrv (1 version) to v1.78 (rust-lang/cargo#13848)
- Workaround copying file returning EAGAIN on ZFS on mac OS (rust-lang/cargo#13845)
- Clean package perf improvements (rust-lang/cargo#13818)
- fix(toml): Validate crates_types/proc-macro for bin like others (rust-lang/cargo#13841)
- fix(toml): On 2024 Edition, disallow ignored `default-features` when inheriting (rust-lang/cargo#13839)
- chore(ci): Ignore openssl deps (rust-lang/cargo#13840)
- fix(lints): Remove ability to specify `-` in lint name (rust-lang/cargo#13837)
- fix(resolver): Treat unset MSRV as compatible (rust-lang/cargo#13791)
- fix(toml): Don't lose 'public' when inheriting a dep (rust-lang/cargo#13836)
- chore(deps): update compatible (rust-lang/cargo#13834)
- Error when unstable lints are specified but not enabled (rust-lang/cargo#13805)
- fix(lint): Warn not Error on unsupported lint tool (rust-lang/cargo#13833)

r? ghost

Note: this includes the fix that was beta backported in #124647

### CODE REVIEW

**Review by weihanglo — APPROVED** [review]

**Comment by Muscraft** [comment]
I'm not sure what caused the error.

@bors retry rollup=never p=1

**Comment by weihanglo** [comment]
With the `--check-cfg` always on, it is expected to have a slight drop around ~1% (see <https://github.com/rust-lang/rust/pull/97657#issuecomment-1145354504>. However this regression is way huger than that. 

We also have some dependencies updates in this PR so unsure which is the culprit. Continue investigating...

**Comment by Urgau** [comment]
I'm highly suspicious the perf regressions have the same cause as in #120393, the chear number of warnings we now emit. In https://github.com/rust-lang/rust/pull/120393#issuecomment-1971787475 we had ~200 warnings and that caused us ~3/4% perf on diesel, diesel isn't impacted here but the same reasoning can be applied here to `syn`, our biggest regression.

The `syn` build now produces **1800 warnings** with only an handful of them not coming from the `unexpected_cfgs` lint (the `--check-cfg` lint).

*I'm having trouble confirming this locally but I'm pretty sure those warnings account for the vast majority (if not all) of the perf regressions.*

**Comment by Kobzol** [comment]
I didn't have a chance to investigate this yet, but based on the self-profile data, it indeed looks like much more time is spent in the lint machinery.

**Comment by ehuss** [comment]
> I'm not sure what caused the error.

@Muscraft The `aarch64-gnu` is frequently killed for various reasons. It is a self-hosted runner and is thus a little more sensitive to being restarted. You can see the reason in the "Summary" page on GitHub Actions, and scrolling down to see:

> The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

That is always out of our control, and just needs to be retried.

**Comment by nnethercote** [comment]
Why are there so many new warnings?

**Comment by weihanglo** [comment]
@nnethercote `unexpected_cfgs` lint is trigged because Cargo now passes `--check-cfg` flag.

See <https://github.com/rust-lang/blog.rust-lang.org/pull/1313>, which is supposed to be out along with the nightly release 😂.

**Comment by nnethercote** [comment]
Why do the benchmarks trigger so many occurrences of these new warnings? Is that typical? Are lots of crates now getting hundreds of new warnings?

**Comment by weihanglo** [comment]
> Are lots of crates now getting hundreds of new warnings?

You local crates with lots of custom `cfg` will get lots of warnings. But none of them will come from transitive dependencies, as Cargo uses [`--cap-lints`](https://doc.rust-lang.org/rustc/lints/levels.html#capping-lints). Only warnings from local crates will get generated.

**Comment by pnkfelix** [comment]
I believe the hypothesis that the regression being flagged here is an artifact of the increase in number-of-warnings being emitted. I consider this a (mostly-)false alarm resulting as an artifact of design decisions in our rustc-perf infrastructure. (I say "mostly-false" since I do think that @nnethercote is asking the right question, namely about whether other crates should be expecting to see a similar explosion in lint output.)

cc https://github.com/rust-lang/rustc-perf/issues/1819

marking as triaged

@rustbot label: +perf-regression-triaged

**Comment by Urgau** [comment]
@pnkfelix Part of regression is the loading of all the built-ins targets to populate the well known cfgs, I did [a measurement](https://github.com/rust-lang/rust/pull/97657#issuecomment-1145354504) some time ago about the impact of loading those and it was mostly: [+0.31%, +2.17%] +0.81%.

The reason why loading all the built-ins targets is expensive is because they are unfortunately not immutable, both in terms of data, like Apple targets who at runtime look at some env variables but also in terms of heap allocations; and while individually it's not much, multiplied by more than 280 targets it's adding up quickly.

I have a PR #122703 in the works to reduce to the bare minimum this cost, and it's showing some results https://github.com/rust-lang/rust/pull/122703#issuecomment-2097100875: [-2.18%, -0.21%] -0.91%.

**Pull request merged**
