### PR TITLE
Allow lifetimes to be passed to macros

### LINKED ISSUE #10413: Add 'lifetime' and 'type parameter list' fragment specifiers to macro parser.
This would make manipulating type parameter lists much easier.

### PR DESCRIPTION
**Pull request by sgrif**
Partially fixes #10413. This only handles lifetimes, as they're much
more "obvious" than the type parameter list would be, as that implies
that we probably want to mirror `ast::Generics` as well as all of the
individual pieces. That should probably have an RFC.

These are essentially just treated the same as idents. They're a single
token, and are quite pervasive, so we interpolate them back into a real
token rather than handling `NtLifetime` all over the parser.

This change is specifically needed in Diesel in order for us to provide
a "normal macro" alternative to some of our syntax extensions. With this
change, we'd be able to have a decent stable story without syntex.

### CODE REVIEW

**Comment by DanielKeep** [comment]
Only change I'd *personally* make would be to abbreviate the matcher name, since we have `expr`, `ident`, `stmt`, `pat`, `ty`.  Maybe `ltime` or `lt`.

Really, there's no compelling reason *not* to support this.  This would also play into rust-lang/rfcs#1583, allowing the expansion to use `lifetime` NTs.

**Comment by nikomatsakis** [comment]
I'm strongly in favor of this change. According to our policies, though, I believe an RFC would be required (though not a complex one). Something like https://github.com/rust-lang/rfcs/pull/1576 or https://github.com/rust-lang/rfcs/pull/1575. I imagine we could "fast-track" such an RFC. (As we ought to consider fast-tracking those, which are changes of a similar magnitude.)

cc @rust-lang/lang

**Comment by nikomatsakis** [comment]
also cc @pnkfelix and @LeoTestard specifically

**Comment by sgrif** [comment]
> According to our policies, though, I believe an RFC would be required

I assumed that wasn't required since there was an open issue on the main Rust repo that had been around for a while. Certainly happy to write up an RFC though.

**Comment by sgrif** [comment]
The RFC is pretty brief as there's not a ton to say about the change. https://github.com/rust-lang/rfcs/pull/1590

**Comment by nikomatsakis** [comment]
@sgrif I'm going to close this PR until the RFC is settled, just to keep queue under control.

**Comment by sgrif** [comment]
No problem

**Comment by mikeyhew** [comment]
@sgrif I'm going to try to finish this, can you tell me what still needs to be done?

**Comment by sgrif** [comment]
This PR should actually be good to go as-is (modulo rebasing). The thing I wanted to fix was an issue with `$($x: lifetime)*` followed by any other repeater, but that seems like a more general problem with the macro_rules parser that is out of scope for this feature.

**Comment by mikeyhew** [comment]
@sgrif OK, sounds good. Rebasing has been pretty straightforward for the most part, with a couple of exceptions that I'll need some help with. I'll post a new PR and ping you when it's ready for your input.

**Pull request closed without merging**
