### PR TITLE
Use more popular tx rx variable for mpsc doc

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by steveklabnik** [comment]
We specifically chose against this because it is less obscure.

That said, years later, maybe @rust-lang/libs wants to use the shorter names. It's their call.

**Comment by sfackler** [comment]
How will renaming from sender/receiver to tx/rx improve the experience for readers?

**Comment by pickfire** [comment]
> How will renaming from sender/receiver to tx/rx improve the experience for readers?

I have seen a lot of articles that does it that way, from my experience seeing sender and receiver is rare.

- tokio docs does the same as well (tx/rx) https://docs.rs/tokio/1.3.0/tokio/sync/index.html
- async-std is a bit special (s/r) https://docs.rs/async-std/1.9.0/async_std/channel/fn.bounded.html

**Comment by the8472** [comment]
It's also used in the book. https://doc.rust-lang.org/book/ch16-02-message-passing.html

> The abbreviations tx and rx are traditionally used in many fields for transmitter and receiver respectively, so we name our variables as such to indicate each end. 

Perhaps it would make sense to add a code comment expanding the shorthand the first time it is introduced, as is common with abbreviations.

**Comment by pickfire** [comment]
> Perhaps it would make sense to add a code comment expanding the shorthand the first time it is introduced, as is common with abbreviations.

The first time they had seen tx and rx is probably in the book, not the docs. If we decided to go with tx/rx, I wonder if it would be good to ping async-std and crossbeam if they wanted to follow to keep consistency within the ecosystem.

**Comment by joshtriplett** [comment]
I agree: when writing complex code involving multiple channels (including code that sends channel endpoints over channels), I find `sender` and `receiver` more evocative.

I'd prefer to see the subset of the docs that currently use `tx` and `rx` change to `sender` and `receiver` for consistency.

Regarding verbosity, I tend to use `_s` and `_r` suffixes for named channels: `somename_s` and `somename_r` work well as a pair. Perhaps it'd make sense to add an example that involves multiple channels with different names, and in that example, use a convention like that?

**Comment by m-ou-se** [comment]
I agree with sfackler, BurntSushi and joshtriplett. Closing this.

**Pull request closed without merging**
