### PR TITLE
Move rustdoc run-make-fulldeps tests to run-make

### PR DESCRIPTION
**Pull request by jyn514**
This cuts the time to run the tests in half, because they don't require
building a stage 2 compiler. They were all added to fulldeps before https://github.com/rust-lang/rust/pull/82802 because rustdoc wasn't available in run-make tests.

This doesn't change coverage tests, which will be changed soon in a
separate PR (https://github.com/rust-lang/rust/pull/83755#issuecomment-812350146).

This also changes some of the `-include` directives, see https://github.com/rust-lang/rust/issues/83773 for what's going on there.

r? @petrochenkov

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/83795#issuecomment-812749850) 

@bors r-

**Comment by jyn514** [comment]
@petrochenkov do you understand this test failure?

```
---- [run-make] run-make/exit-code stdout ----
error: make failed
status: exit status: 2
------------------------------------------
LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/exit-code/exit-code:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/exit-code/exit-code -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/exit-code/exit-code  -Clinker='arm-none-eabi-gcc' success.rs; [ $? -eq 0 ]
------------------------------------------
stderr:
------------------------------------------
------------------------------------------
error: linking with `arm-none-eabi-gcc` failed: exit status: 1
  |
  = note: "arm-none-eabi-gcc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" # lots more args
  = note: arm-none-eabi-gcc: error: unrecognized command line option '-m64'
```
My only thought is that different args are being passed depending on the stage? I looked for `-m64` in the repo but everything I saw was in compiler/rustc_target, I don't know why it would be affected by my change.

**Comment by petrochenkov** [comment]
```
LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/exit-code/exit-code:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/exit-code/exit-code -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/exit-code/exit-code  -Clinker='arm-none-eabi-gcc' success.rs
```
Looks like we are building for x86_64 Linux (that's where `-m64` comes from), but passing `arm-none-eabi-gcc` as a linker, which is obviously not right.
It's also very suspicious that `stage2/bin/rustc` is used as the compiler.

**Comment by jyn514** [comment]
I'm still not sure exactly what's going on, but it's related to cross-compiling - I can reproduce locally with `x.py test src/test/run-make --target thumbv6m-none-eabi` (after installing `qemu-system-arm` and `gcc-arm-none-eabi`). The exact command that fails is this monster:

> LD_LIBRARY_PATH="/home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/run-make/issue-38237/issue-38237:/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/lib:/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage0/lib" '/home/joshua/rustc/build/x86_64-unknown-linux-gnu/stage1/bin/rustc' --out-dir /home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/run-make/issue-38237/issue-38237 -L /home/joshua/rustc/build/x86_64-unknown-linux-gnu/test/run-make/issue-38237/issue-38237  -Clinker='arm-none-eabi-gcc' foo.rs

Maybe passing -Clinker=arm-gcc is incorrect here? I don't know whether run-make tests are supposed to depend on the target or not.

I think stage2 is unrelated - I used `--stage 1` and it ran with stage1/rustc and gave the same error. Probably it's related to how the CI pipeline passes `--stage 2` for all tests.

I meant to see what the command was for run-make-fulldeps (in particular, to see whether it passed -Clinker=arm-gcc or not), but my computer crashed and I didn't want to lose the part of the comment I'd written up.

**Comment by bstrie** [comment]
If there's a deeper problem with run-make, should we open an issue to track that and close this for the time being?

**Comment by jyn514** [comment]
@bstrie I don't understand what's going on well enough to know if it's an issue with run-make or not, and if so, what it is.

**Comment by JohnCSimon** [comment]
ping from triage:
@jyn514 - fyi: this PR has sat idle for over a month

**Comment by jyn514** [comment]
I will not have time to work on this in the foreseeable future.

**Pull request closed without merging**
