### PR TITLE
Save metadata even with -Z no-trans (e.g. for multi-crate cargo check).

### PR DESCRIPTION
**Pull request by eddyb**
Removes the item symbol map in metadata, as we can now generate them in a deterministic manner.
The `-Z no-trans` change lets the LLVM passes and linking run, but with just metadata and no code.
It fails while trying to link a binary because there's no `main` function, which is correct but not good UX.

There's also no way to easily throw away all of the artifacts to rebuild with actual code generation.
We might want `cargo check` to do that using cargo-internal information and then it would just work.

cc @alexcrichton @nikomatsakis @Aatch @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
I'm going to review this right now..

**Comment by michaelwoerister** [comment]
@bors: r+

Perfect, @eddyb!

**Comment by eddyb** [comment]
Oh wait I didn't fix the failure in @alexcrichton's test.

@bors r-

**Comment by eddyb** [comment]
@alexcrichton So you can see I got stuff to bootstrap again. I know how to fix the cdylibs test failure (make the metadata symbol exported just for dylibs, not cdylibs). Any ideas about the other 2 failures?

**Comment by alexcrichton** [comment]
Unfortunately no :( 

I'm getting a little lost about which changes are in flight though...

**Comment by eddyb** [comment]
One failure left:
```
note: /home/eddy/rust/build/x86_64-unknown-linux-gnu/test/run-make/metadata-flag-frobs-symbols.stage2-x86_64-unknown-linux-gnu/bar.0.o: In function `bar::main::h11d3fcba4e3c0e33':
bar.0.rs:(.text._ZN3bar4main17h11d3fcba4e3c0e33E+0x5): undefined reference to `foo1::foo::hb1ca081fbfc73c59'
bar.0.rs:(.text._ZN3bar4main17h11d3fcba4e3c0e33E+0xf): undefined reference to `foo2::foo::h84b959482adb7ec4'
```

**Comment by michaelwoerister** [comment]
@eddyb Do you have an estimate when this will be able to land? Because if it's still going to take some time, I'd like the first few commits to be factored out into their own PR, so they can land earlier. That be rather helpful for collector-driven trans.

**Comment by michaelwoerister** [comment]
:persevere::pray:

**Comment by eddyb** [comment]
Turns out that there's a lot more `--crate-type=lib` pretty tests that I didn't notice, because they were spuriously failing due to the tests running in parallel while using the same output name (all of them get the source to `rustc` via stdin).
I've updated `compiletest` to give `rustc` a proper output directory and that seems to have fixed it.
@bors r=michaelwoerister

**Pull request merged**
