### PR TITLE
Only strip `librustc_driver` and `libLLVM` during `x dist`

### PR DESCRIPTION
**Pull request by Kobzol**
The strip invocation can be quite slow (~1-2 seconds), and it is executed on every compiler bootstrap refresh when debuginfo is turned off, which can make most bootstrap commands quite slow. Discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Only.20strip.20LLVM.2Frustc.20in.20the.20dist.20profile).

r? @lqd

### CODE REVIEW

**Comment by Kobzol** [comment]
@bors try @rust-timer queue

Just to check that artifact sizes haven't regressed.

**Comment by lqd** [comment]
I'm not an expert in bootstrap but this seems good to me; 
r=me if you want, with no binary size losses in the perf run -- otherwise maybe ask an actual t-bootstrap member :)

**Comment by lqd** [comment]
It seems that at least it didn't work on the try build.

image

**Review by onur-ozkan — APPROVED** [review]

**Comment by Kobzol** [comment]
Crap. In `opt-dist`, we do a lot of shenanigans when building `rustc`, and for the final `dist` step we actually use `--keep-stage` to avoid rebuilding `rustc`, which probably causes the regression.

I'm tempted to switch the condition to `if isCI: strip()`, but then the strip wouldn't work for people building their own toolchain.

Probably the right fix is to move the strip to the `dist` step.

**Comment by Kobzol** [comment]
Looks like we can't strip after BOLTing the library. Wonderful.

**Comment by lqd** [comment]
Yes that's what caused #112286

**Comment by Kobzol** [comment]
I'll let this go for now, and switch to using `debuginfo-level = "line-tables-only"` to avoid the slow `strip` calls. It's too annoying to fix this.

**Pull request closed without merging**
