### PR TITLE
[beta] rustbuild: pass datadir to rust-installer

### PR DESCRIPTION
**Pull request by Keruspe**
Backport from #48295

### CODE REVIEW

**Comment by kennytm** [comment]
Blocked until #48295 has been merged.

**Comment by Keruspe** [comment]
@kennytm looks like #48295 finally passed

**Comment by kennytm** [comment]
You have updated the `rust-installer` submodule in this backport. Is this expected?

**Comment by Keruspe** [comment]
It was updated in the original pull request too. Another pull request updating it further was merged before, that's why there was only the other commit left in the end.
The rustbuild commit is a noop if the rust-installer isnt' updated as well

**Comment by alexcrichton** [comment]
All dist jobs passed, merging manually

* [AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6659)
* [Travis](https://travis-ci.org/rust-lang/rust/builds/352809849)

**Comment by pietroalbini** [comment]
Uh, third time in a row appveyor timed out...

@bors retry

**Pull request merged**
