### PR TITLE
Improve TyCtxt::type_of documentation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @oli-obk

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors r- looks like it failed in a rollup
https://github.com/rust-lang/rust/pull/95551#issuecomment-1085446067

**Comment by GuillaumeGomez** [comment]
Should be fixed now.

@bors: r=Dylan-DPC rollup

**Comment by matthiaskrgr** [comment]
Looks like there are still problems :(
https://github.com/rust-lang-ci/rust/runs/5794302810?check_suite_focus=true#step:26:43642
@bors r-

**Comment by GuillaumeGomez** [comment]
Weird, it worked when I built the docs locally... Fixing it tomorrow.

**Comment by GuillaumeGomez** [comment]
Fixed again.

@bors: r=Dylan-DPC

**Pull request merged**
