### PR TITLE
add bare metal ARM Cortex-A targets to rustc

### PR DESCRIPTION
**Pull request by japaric**
-> `rustc --target armv7a-none-eabi` will work

also build rust-std (rustup) components for them

-> `rustup target add armv7a-none-eabi` will work

this completes our bare-metal support of ARMv7 cores on stable Rust (by 1.42 or 1.43)

(these target specifications have been tested on a real (no emulation / QEMU) [Cortex-A7 core](https://github.com/iqlusioninc/usbarmory.rs/))

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

🎉

**Comment by japaric** [comment]
Fixed merge conflict

@bors r=alexcrichton

**Comment by japaric** [comment]
Last commit should fix the compiler-builtins build for armv7a-none-eabi.

Fixing the build of that crate on armv7a-none-eabihf is going to require changes in the compiler-builtins crate's build script so I'm going to leave the rust-std build for that target out until that gets addressed upstream.

bors r=alexcrichton

**Comment by japaric** [comment]
err, 

@bors r=alexcrichton

**Pull request merged**
