### PR TITLE
Rollup of 8 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #104402 (Move `ReentrantMutex` to `std::sync`)
 - #104493 (available_parallelism: Gracefully handle zero value cfs_period_us)
 - #105359 (Make sentinel value configurable in `library/std/src/sys_common/thread_local_key.rs`)
 - #105497 (Clarify `catch_unwind` docs about panic hooks)
 - #105570 (Properly calculate best failure in macro matching)
 - #105702 (Format only modified files)
 - #105998 (adjust message on non-unwinding panic)
 - #106161 (Iterator::find: link to Iterator::position in docs for discoverability)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=104402,104493,105359,105497,105570,105702,105998,106161)

### CODE REVIEW

**Comment by rylev** [comment]
@rust-timer build c88ca476fdc92309cea647f6276356ca25b63477

**Comment by Nilstrieb** [comment]
This is indeed likely to be caused by my PR, probably because `ParseResult` got bigger. I have an idea for a fix, I'll put a PR soon.

**Comment by Nilstrieb** [comment]
Opened #106416 which should get the perf back (and maybe even go beyond!)

**Comment by rylev** [comment]
Indeed looks like [the performance was gained back](https://github.com/rust-lang/rust/pull/106416#issuecomment-1370308844). Awesome stuff! 

@rustbot label perf-regression-triaged

**Pull request merged**
