### PR TITLE
some low hanging clippy::perf fixes

### PR DESCRIPTION
**Pull request by matthiaskrgr**

### CODE REVIEW

**Comment by jyn514** [comment]
CI failure looks spurious, cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Failure looks spurious, weird...

**Comment by jyn514** [comment]
@GuillaumeGomez right - my point is that test is flaky and we should find a way to make it less flaky. 30 seconds is already a long timeout so we probably don't want to increase it - is there a way to make whatever it's doing faster?

**Comment by GuillaumeGomez** [comment]
There is no explicit timeout here, we just told the test to wait for a selector and that selector didn't appear in the (default) 30 seconds timeout. I think the problem is elsewhere.

**Comment by jyn514** [comment]
Hmm, ok. Maybe it's not spurious then. @matthiaskrgr can you run this locally and see whether it passes?

@bors r-

**Comment by matthiaskrgr** [comment]
`./x.py test rustdoc ` succeeds locally. I rebased, let's see if that changes anything.

**Comment by GuillaumeGomez** [comment]
> `./x.py test rustdoc ` succeeds locally. I rebased, let's see if that changes anything.

Is it running `rustdoc-gui`? If not we might want to fix that (I never ran it like this). Otherwise: `x.py test src/test/rustdoc-gui --stage 1`.

**Comment by matthiaskrgr** [comment]
Ah no, apparently `x.py test rustdoc` does not run the `rustdoc-gui` tests. (got an error because of some missing npm package).
But I managed to reproduce the test failure at least! :)

**Comment by GuillaumeGomez** [comment]
Time to fix it then! :p

**Comment by matthiaskrgr** [comment]
So, I went through all the changes one by one now and applied them and I got a lot of spurious test failures:
````
code-sidebar-toggle... FAILED
[ERROR] (line 3) Error: No node found for selector: #sidebar-toggle: for command `click: "#sidebar-toggle"` 

sidebar... FAILED
[ERROR] (line 44) expected 1 elements, found 0: for command `assert-count: (".sidebar .location", 1)`
````
but after running `./x.py test src/test/rustdoc-gui --stage 1` a couple of times I always got to a test run which succeeded at some point, so to me it looks like the tests are just flaky :/

**Comment by GuillaumeGomez** [comment]
This is highly surprising and a bit worrying. Well, if it isn't due to changes in this PR, let's move forward. I'll keep a close eye on such flakiness in the future.

@bors: r=jyn514,GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Since it's changing performance:

@bors: rollup=iffy

**Comment by jyn514** [comment]
Apple job failed without logs.

@bors retry

**Pull request merged**
