### PR TITLE
Migrate bootstrap to Clap-based argument parsing

### PR DESCRIPTION
**Pull request by clubby789**
Supercedes #108083

I chose to re-do the work rather than rebase the onto the large changes since the original PR. If it's preferred I can instead force-push the original PR to this version.

cc @jyn514 @albertlarsan68

### CODE REVIEW

**Review by albertlarsan68 — COMMENTED** [review]
LGTM, but I would like to have another pair of eyes.
r? @Mark-Simulacrum

**Comment by clubby789** [comment]
Rebased and preserved the behaviour of `--warnings warn`, which is not currently documented

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup=never

This seems broadly OK to me. I think the compile-time impact is minimal enough for now, we can iterate further if needed. clap is pretty minimal in terms of additional compile times that it itself contributes.

**Comment by clubby789** [comment]
Going to try and debug this now

**Comment by clubby789** [comment]
Clap was parsing `--host=""` as a single `TargetSelection` with empty contents. Added some logic to instead parse this as an empty list

**Comment by Nilstrieb** [comment]
Wait actually I think
@bors r=Mark-Simulacrum
is more correct here, i dont know what retry does here

**Comment by albertlarsan68** [comment]
This is some big noise, this PR only touches bootstrap, not Rustc.

**Pull request merged**
