### PR TITLE
Use assoc types in the *Iterator traits

### PR DESCRIPTION
**Pull request by japaric**
Affected traits:
- `Iterator { type Item }`
- `IteratorExt` no input/output types, uses `<Self as Iterator>::Item` in its methods
- `DoubleEndedIterator` no input/output types, uses `<Self as Iterator>::Item` in its methods
- `DoubleEndedIteratorExt` no input/output types, uses `<Self as Iterator>::Item` in its methods
- `RandomAccessIterator` no input/output types
- `ExactSizeIterator` no input/output types, uses `<Self as Iterator>::Item` in its methods

This breaks all the implementations of these traits.

[breaking-change]

---

I was planning to use assoc types in the `AdditiveIterator` trait but that can't be done until this bug (#20400) is fixed.

r? @aturon

### CODE REVIEW

**Comment by aturon** [comment]
Other than a couple of possible mergers, this LGTM!

**Comment by bluss** [comment]
Is `<Self as Iterator>::Item` needed, doesn't `Self::Item` work?

**Comment by japaric** [comment]
@bluss `Self::Item` works if the assoc type is defined in the same trait, but it doesn't work with supertraits:

``` rust
#![crate_type = "lib"]
#![feature(associated_types)]

trait Iterator {
    type Item;

    fn ok() -> Self::Item;
}

trait DoubleEndedIterator: Iterator {
    fn doesnt_work() -> Self::Item;
    fn works() -> <Self as Iterator>::Item;
}
```

Unless @nikomatsakis fixed it while I was sleeping ;-).

**Comment by nikomatsakis** [comment]
:yellow_heart:

**Pull request merged**
