### PR TITLE
libcollections: move Vec::push slow path out

### PR DESCRIPTION
**Pull request by emberian**
Makes Vec::push considerably smaller: 25 instructions, rather than 42, on
x86_64.

### CODE REVIEW

**Comment by Gankro** [comment]
Vec already has a resize fn

**Comment by Gankro** [comment]
See also the private grow_capacity method for some pre-existing refactoring of this functionality.

**Comment by cmr** [comment]
@Gankro using `grow_capacity` is a non-starter since the capacity calculation (and associated panic) don't want to be in the fast path. I'm not sure how this `resize` function doesn't conflict with the other one, but I've moved it to an inner helper function now (waiting for build to test if that still works as desired)

**Comment by cmr** [comment]
Yeah, new version works the same.

**Comment by huonw** [comment]
Do you happen to have some before/after benchmarks?

**Comment by Gankro** [comment]
@cmr I was moreso suggesting there might be a better refactoring to reduce duplication, but this certainly doesn't make it worse.

**Comment by cmr** [comment]
@huonw No, but I could fabricate one that is predicated on icache residency.

**Comment by cmr** [comment]
(@erickt also mentioned wanting this in serde)

**Comment by alexcrichton** [comment]
I would personally also prefer to see at least one benchmark showing one way or another here. This is unfortunately a loss in readability in the code and is an idiom we only rarely apply today, so I would prefer to have some numbers backing it up showing why the loss in readability is worth it.

**Comment by cmr** [comment]
Smaller function size is the main goal, which can help inlining in complex functions and reduce icache pressure. Here's one silly benchmark:

```

**Comment by cmr** [comment]
For reference, against the C++ equivalent:

```c++
#include <vector>
#include <cstdint>

extern "C" {
void cpp_version() {
    static std::vector<int32_t> v(100);
    for (int i = 0; i < 100; i++) {
        v.push_back(i);
    }
    v.resize(0);
}
}
```

```rust
extern crate test;

#[bench]
fn x(b: &mut test::Bencher) {
    let mut v = Vec::with_capacity(100);
    b.iter(|| { v.extend(0..100); v.truncate(0); });
}

#[link(name = "foo")]
#[link(name = "stdc++")]
extern "C" {
    fn cpp_version();
}

#[bench]
fn cpp(b: &mut test::Bencher) {
    b.iter(|| unsafe { cpp_version() });
}
```

```
running 2 tests
test cpp ... bench:       130 ns/iter (+/- 9)
test x   ... bench:        83 ns/iter (+/- 5)
```

**Pull request merged**
