### PR TITLE
[self-profling] Record the cgu name when doing codegen for a module

### PR DESCRIPTION
**Pull request by wesleywiser**

### CODE REVIEW

**Review by andjo403 — APPROVED** [review]
looks good to me

**Comment by Mark-Simulacrum** [comment]
Hm, this won't show up in self-profile summaries, right? If it does then we'll need to somehow disable that or patch perf.rlo somehow, I guess -- ideally perf sees the "same" query over time unless something has changed in a major way in the compiler. I guess CGU partitioning is maybe "major" change but it's unclear to me that we want that to mean two different queries on the detailed-query view.

**Comment by wesleywiser** [comment]
No, this is stored in the "args" field for the event. It won't show up anywhere except the chromium profiler currently.

**Comment by Mark-Simulacrum** [comment]
Great! Then this seems fine to me as well. @bors r+

**Pull request merged**
