### PR TITLE
add a macro for static (compile-time) assertions

### PR DESCRIPTION
**Pull request by RalfJung**
Cc @oli-obk

### CODE REVIEW

**Comment by leonardo-m** [comment]
Is this macro usable from the Prelude too? Something similar is useful in user code too.

**Comment by oli-obk** [comment]
No, this is not meant for users. Users will get first class support for `assert!` and friends.

**Comment by RalfJung** [comment]
@oli-obk you'd likely still want such a macro... I doubt `assert!(foo);` is going to work in item position?

Having to give the assertion a name though is rather ugly. Fine for internal use, not so for libstd.

**Pull request merged**
