### PR TITLE
collector: move ensure_sufficient_stack out of the loop

### PR DESCRIPTION
**Pull request by RalfJung**
According to the docs this call has some overhead to putting it inside the loop doesn't seem like a good idea.

r? @oli-obk

### CODE REVIEW

**Comment by RalfJung** [comment]
Hm that's odd. Maybe spurious? We may not have a benchmark for a const that has a lot of relocations (or the overhead of `ensure_sufficient_stack` is actually not that bad).

FWIW I am also quite surprised by how `collect_items_rec` uses `ensure_sufficient_stack`... the main recursion path where `collect_items_rec` calls itself does not seem to have a stack growth check?

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
r? compiler-errors @bors r+

**Comment by klensy** [comment]
Still maxrss regression?

**Comment by RalfJung** [comment]
I have seen so many spurious maxrss regressions, I usually ignore that metric...

**Pull request merged**
