### PR TITLE
Fix item-info color

### LINKED ISSUE #98341: Links in deprecated notes have poor contrast
I tried documenting this code:

```rust
#[deprecated = "Replaced by [`Client::login_token`](#method.login_token)"]
pub async fn login_with_token(
    // ...
```

I expected to see this happen: `cargo doc` generating a beautiful doc page

Instead, this happened:

Screenshot_2022-06-21_154838

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (cacc75c82 2022-06-16)
binary: rustc
commit-hash: cacc75c82ebe15cf63d31034fcf7f1016cddf0e2
commit-date: 2022-06-16
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

@rustbot labels: +T-rustdoc +A-rustdoc-ui

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of #98341 (the final fix is #93896).

Since the links are already underlined, no need to change their color too. Instead it now uses the text color directly.

Here are some screenshots of the result:

Screenshot from 2022-07-26 15-16-28
Screenshot from 2022-07-26 15-16-33
Screenshot from 2022-07-26 15-16-39

Online demo available [here](https://rustdoc.crud.net/imperio/item-info-color/lib2/trait.Trait.html).

cc @jplatte @jsha 
r? @notriddle

### CODE REVIEW

**Comment by jsha** [comment]
@bors r-

This is the wrong solution for https://github.com/rust-lang/rust/issues/98341. The link color means something: you can click here. We should avoid creating exceptions if at all possible. The background for item-infos does not mean anything special. We can choose it to be whatever we want.

The problem here is that the link color in dark theme is chosen to contrast against the dark background, so it's light. But the background for the item-info is also light - too light, in fact. See https://github.com/rust-lang/rust/pull/93896. In that PR we never landed on the exact color, but that's the direction I think we should go. The text in the item info should be the same color as the body text, and the background should be just different enough from the body background to highlight it, without making it too bright.

**Comment by GuillaumeGomez** [comment]
I completely forgot about it and I also prefer your approach. Closing this one then!

**Comment by GuillaumeGomez** [comment]
@jsha I just realized that this fix is still valid, even though incomplete. It makes the `<a>` elements' color inherit their parent one. The one you set in https://github.com/rust-lang/rust/pull/93896. I'm reopening this PR and removing the "fixes" part in the first comment as it is incomplete but still an improvement.

**Comment by jsha** [comment]
> It makes the <a> elements' color inherit their parent one.

That's usually not what we want. For instance: a paragraph of text might have `color: black`. If there's a link in that paragraph we want it to have a distinct color, not black. So it shouldn't inherit it's parent's color.

**Comment by GuillaumeGomez** [comment]
Ok. I'll wait for your PR to be done and then I'll update the links' color for item info elements.

**Comment by GuillaumeGomez** [comment]
Blocked on https://github.com/rust-lang/rust/pull/93896 for the time being.

**Comment by GuillaumeGomez** [comment]
I uploaded the result [here](https://rustdoc.crud.net/imperio/item-info-color/lib2/trait.Trait.html).

**Comment by GuillaumeGomez** [comment]
cc @jsha (sorry, forgot to ping you)

**Comment by anden3** [comment]
Hello @GuillaumeGomez! There's a merge conflict for this PR, has there been any updates? :)

**Comment by GuillaumeGomez** [comment]
Still waiting for review.

**Comment by fmease** [comment]
Triage: As I just posted in issue #98341. Rendering today is:

Image

**Comment by GuillaumeGomez** [comment]
I think the current situation is good enough then. Closing.

**Pull request closed without merging**
