### PR TITLE
Add unstable `-Zdefault-hidden-visibility` cmdline flag for `rustc`.

### PR DESCRIPTION
**Pull request by anforowicz**
The new flag has been described in the Major Change Proposal at
https://github.com/rust-lang/compiler-team/issues/656

### CODE REVIEW

**Comment by anforowicz** [comment]
@rustbot label +S-waiting-on-author -S-waiting-on-review

I need to fix the test failures reported above.  AFAICT they didn't show up when I've run `./x.py test`, but I can indeed repro them with `./x.py test compiler/rustc_interface`.

**Comment by bridiver** [comment]
Thanks @anforowicz ! Not sure when I was ever going to finally get around to this if you didn't pick it up.

**Comment by bridiver** [comment]
@TaKO8Ki do you have some time to look at this? It's going to solve some important issues for us (Brave/Chromium)

**Comment by TaKO8Ki** [comment]
@bridiver Sorry. I missed it. I'll take a look.

**Comment by TaKO8Ki** [comment]
Sorry for the late review! @bors r+ rollup

**Comment by TaKO8Ki** [comment]
Thanks! @bors r+

**Comment by GuillaumeGomez** [comment]
I think it failed in https://github.com/rust-lang/rust/pull/118821#issuecomment-1849773925.

**Comment by anforowicz** [comment]
@TaKO8Ki and/or @GuillaumeGomez, could you PTAL again?

My apologies for the trouble with the failures of the new test. FWIW, I believe that the most recent failures should be fixed now - I've relaxed the test, so that the `hidden` substring is the only pattern that the test looks for (ignoring other attributes like `internal` and/or `constant`).  So, I think that this PR might be ready to ask Bors for another merge attempt.  WDYT?

OTOH, I wasn't able to test against the specific target triple that failed in the last merge attempt :-/.  I am able to locally run the tests on my machine when targeting `wasm32-unknown-unknown` and/or `x86_64-unknown-linux-gnu` , but I couldn't figure out how to test additional target triples.  I can see multiple available triples in the output of `rustc --print target-list
`, but `./x.py test <my test> --target <triple>` fails for most of them with an error that is not related to my changes (e.g. `i686-unknown-linux-gnu` fails saying:  "linking with `x86_64-linux-gnu-gcc` failed [...] /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/13/libgcc.a when searching for -lgcc").

@rustbot label -S-waiting-on-author +S-waiting-on-review

**Comment by anforowicz** [comment]
@TaKO8Ki, could you PTAL again?

The only change is in `tests/codegen/default-hidden-visibility.rs` - in the latest revision the test only applies to `only-linux` and `only-x86_64`.  This is sufficient to verify that the new command-line flag works and has the desirable effect.  I think it's okay that the verification is only done on a single target, because the implementation is target-agnostic (and because test expectations differ on other targets - the outcome on those targets is still acceptable, but difficult to cover with a test).

@rustbot label -S-waiting-on-author +S-waiting-on-review

-------------------

Let me also discuss some alternative testing approaches that I have considered for this PR.

If there is a desire to cover additional target triples (now or (preferably) in a separate follow-up PR), then:

* One way to proceed is to duplicate the test file into additional `only-X` flavours, with different expectations (e.g. expecting `internal constant` instead of `hidden constant` - both are okay).  If needed I can ask teammates with a Mac to generate test expectations for their target triple.  Additional triples can also be covered, although I would have to lean on others to generate the test expectations.
* Another way to proceed may be to mimic `tests/codegen/align-byval.rs` which selects target triples via `[PREFIX] compile-flags: --target …`.  I have low confidence in my ability to follow this approach, because it fails on my machine for some triples - the test complains about missing matching standard library, but trying to build the library with `./x.py build library --target i686-unknown-linux-gnu` fails saying: “`/usr/bin/ld`: skipping incompatible `/usr/lib/gcc/x86_64-linux-gnu/13/libgcc.a` when searching for `-lgcc`”.

Instead of per-triple test expectations, we could also tweak and relax the patterns being matched against (e.g. saying `{{hidden|internal}}` in the test expectations.  This alternative feels less robust: the relaxed pattern may match accidentally and I have low confidence in my ability to construct a pattern that will work on all triples (given the previous failed attempts in this PR + given that IIUC tier3 targets may not immediately exercise the new test).

**Comment by anforowicz** [comment]
Actually, I think it would be safest if I specified the full triple, because `i686-unknown-linux-gnu` passes for me locally, but we've already seen that `i686`, `linux`, `musl` combination has different outcome.

**Comment by anforowicz** [comment]
> Actually, I think it would be safest if I specified the full triple, because `i686-unknown-linux-gnu` passes for me locally, but we've already seen that `i686`, `linux`, `musl` combination has different outcome.

Ok - switched to `only-x86_64-unknown-linux-gnu`...

**Comment by TaKO8Ki** [comment]
@anforowicz 

> TaKO8Ki, could you PTAL again?

Sure. @bors r+

**Pull request merged**
