### PR TITLE
DNM: Try using memchr without inlining on windows

### PR DESCRIPTION
**Pull request by flip1995**
Another attempt at https://github.com/rust-lang/rust/pull/121465, trying to fix the issue on windows to unblock the Clippy sync.

(Does specifying a git dependency even work or will the `tidy` tool complain? :thinking:)

[memchr patch](https://github.com/BurntSushi/memchr/compare/master...flip1995:memchr:master)

r? @ghost

### CODE REVIEW

**Comment by flip1995** [comment]
That also didn't work...

**Comment by clubby789** [comment]
I think this is only patching the version used by rustc_ast (which I locked since it was the only in-tree usage of memchr), which probably wouldn't affect the linker issue. Using a patch dependency and unlocking it might work?

**Comment by flip1995** [comment]
Ok, this worked. Let's find out whether the `cfg_attr` for inlining are necessary or if the `#[used]` attribute is sufficient.

**Comment by flip1995** [comment]
https://github.com/BurntSushi/memchr/commit/f2e2936815bf211ece60a0251b53a617e1d678ac

This change to `memchr` would "fix" the issue. But it is definitely not desirable in any way. For more details and discussions, refer to  this [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.60ui_test.60.20v0.2E22.2E1.20version.20bump.20causes.20dep.20conflict)

**Pull request closed without merging**
