### PR TITLE
move stray run-pass const tests into const/ folder

### PR DESCRIPTION
**Pull request by RalfJung**
r? @oli-obk

### CODE REVIEW

**Comment by Centril** [comment]
Can we move these to `ui/` ?

**Comment by petrochenkov** [comment]
@Centril 
As I mentioned previously, run-pass threads should not be moved into the ui directory unless some way to run them separately is implemented (https://github.com/rust-lang/rust/issues/54047).

**Comment by Centril** [comment]
@petrochenkov All new run-pass tests are currently being added in `ui/` in any case. I also disagree with the reasons you provided in that issue. Developer UX is not as important than having a well organized test suite (we don't -- the current test suite is horribly disorganized) for specification purposes. However, I suppose I will have to implement the idea by @nikomatsakis to filter tests by mode...

**Comment by petrochenkov** [comment]
@Centril 
>Developer UX is not as important than having a well organized test suite

I disagree, it's a real practical issue that interferes with daily work.

Having feature directories `my_feature` in two directories (`ui` and `run-pass`) in not significantly worse that in one directory.

>All new run-pass tests are currently being added in ui/ in any case.

**Comment by RalfJung** [comment]
I'd say moving run-pass tests to `ui` is a different issue and orthogonal to what this PR is trying to achieve. The last time *all* `ui` tests were moved to `run-pass`, that was quickly reverted; it is not the place of this PR to (somewhat sneakily in a "slowly boiling the frog" manner) revert part of that revert.

**Comment by RalfJung** [comment]
@rust-lang/compiler (I hope this is the right team) still waiting for a review. :)

**Pull request merged**
