### PR TITLE
Fix alloc_jemalloc debug feature

### PR DESCRIPTION
**Pull request by RalfJung**
At least, I think that's how it should be.  'debug' is how the feature is called in liballoc_jemalloc/Cargo.toml and libstd/Cargo.toml. I verified this by making the build script panic rather than adding `--enable-debug`, and without this PR, the panic does not occur even when I set `debug-jemalloc = true` in config.toml. With the PR, the panic occurs as expected.

However, I actually have no idea what I am doing here.

### CODE REVIEW

**Comment by arielb1** [comment]
```
Compiling rand v0.0.0 (file:///checkout/src/librand)
[00:24:12] <jemalloc>: /checkout/src/liballoc_jemalloc/../jemalloc/src/jemalloc.c:2520: Failed assertion: "usize == isalloc(ptr, config_prof)"
[00:24:13] error: Could not compile `rand`.
```

**Comment by arielb1** [comment]
Looks bad. Someone needs to investigate.

**Comment by carols10cents** [comment]
Ping @RalfJung -- looks like there was a problem, are you able to reproduce it locally?

**Comment by RalfJung** [comment]
Sorry somehow I didn't see the emails notifying me about this PR. I will try to reproduce this.

However, as I already mentioned, I don't really know what I am doing here. @alexcrichton you wrote the line I am patching here, but that was 2 years ago... do you remember if there was a reason that the feature does not have the same name in `Cargo.toml` and `build.rs`? Are there any circumstances under which this can even work?

**Comment by RalfJung** [comment]
Just a plain `./x.py build` works fine here. How can I tell which additional settings this "debug" CI build sets? It seems to pass --enable-debug to... something, and that's where the trail ends.

**Comment by alexcrichton** [comment]
Ah unfortunately I don't think I'll be of much help here :(. Everything here looks correct to me, and what's happening (I think) is that we've hit a bug in jemalloc (or our usage of it) which causes a runtime assertion. 

As I think you've discovered at this point the `x86_64-gnu-debug` builder is configured a little differently than just `./x.py build`, and you can find the relevant arguments in the [relevant `Dockerfile`](https://github.com/rust-lang/rust/blob/c88624682ddb5768cca4dacc8482e9bc966261fc/src/ci/docker/x86_64-gnu-debug/Dockerfile#L25-L27)

**Comment by RalfJung** [comment]
> what's happening (I think) is that we've hit a bug in jemalloc (or our usage of it) which causes a runtime assertion.

Yeah that was also what I thought. We haven't actually tested jemalloc-debug all the time due to the bug this PR is fixing. Now that we do, that test fails. I don't think I can fix that, this needs someone who knows things about jemalloc.

**Comment by RalfJung** [comment]
@arthurprs any chance you could give updating jemalloc to 4.5 another try? Maybe that helps with this PR, and it's something we'd probably want anyway?

**Comment by RalfJung** [comment]
I locally reproduced the error and confirmed that after rebasing on top of <https://github.com/rust-lang/rust/pull/43911>, the error is gone.

**Comment by arthurprs** [comment]
Good news :)

**Comment by RalfJung** [comment]
With jemalloc 4.5 having landed, I rebased this one. Locally, things work now, let's see what the CI says.

**Comment by RalfJung** [comment]
```
[00:50:12] <jemalloc>: /checkout/src/liballoc_jemalloc/../jemalloc/src/jemalloc.c:2654: Failed assertion: "usize == isalloc(tsd_tsdn(tsd), ptr, config_prof)"

[00:50:12] error: Could not compile `libc`.

[00:50:12] warning: build failed, waiting for other jobs to finish...

[00:50:24] error: build failed
```
Strange. I did test a local build, and I thought I had debug-jemalloc enabled.

It seems like we actually still hit a jemalloc assertion. This is not a bug introduced by this PR; it is a bug we had all along but failed to detect because jemalloc assertions were not actually enabled on the debug builder.

**Comment by RalfJung** [comment]
I can locally reproduce the error when doing `./x.py build` (rather than just building a stage 1 compiler). So this is not exactly the same error as before the upgrade -- it's the same message, but it doesn't appear in stage 1 any more. Or so.

Anyway I have no idea what to do about this. I just wanted to fix a funny discrepancy in the name of the feature flag, not delve into horrible jemalloc internals.^^ I hope someone more knowledgable can take over from here...

**Comment by carols10cents** [comment]
@alexcrichton what should be done with this PR? who might be best to take over to figure out why we're hitting a jemalloc assertion?

**Comment by alexcrichton** [comment]
@RalfJung mind opening an issue and otherwise I we'll need to close this?

**Comment by alexcrichton** [comment]
@bors: r-

This got back in the queue?

**Comment by RalfJung** [comment]
I opened <https://github.com/rust-lang/rust/issues/44152>. I also changed this PR to essentially a noop -- but I think that status is better than still having this wrong flag in build.rs without any comment.

**Comment by RalfJung** [comment]
Should this get rollup priority? Seems like a waste of a full CI run...

**Comment by arielb1** [comment]
@RalfJung

Not sure. This is entirely the sort of thing that causes odd failures on odd platforms.

**Pull request merged**
