### PR TITLE
[beta] Use time crate in bootstrap dist instead of date

### PR DESCRIPTION
**Pull request by onur**
Beta backport of #48013

### CODE REVIEW

**Comment by pietroalbini** [comment]
The bot failed to assign a reviewer... @alexcrichton?

**Comment by kennytm** [comment]
Heh, no space left on device?

```
[0Ktravis_time:start:stage0-fabricate
[0KBuilding stage0 tool fabricate (x86_64-unknown-linux-gnu)
[01:15:43] [m[m[32m[1m   Compiling[m same-file v0.1.3
[01:15:43] [m[m[32m[1m   Compiling[m yaml-rust v0.3.5
[01:15:43] [m[m[32m[1m   Compiling[m pkg-config v0.3.9
[01:15:43] [m[m[32m[1m   Compiling[m miniz-sys v0.1.10
[01:15:44] [m[m[32m[1m   Compiling[m filetime v0.1.14
[01:15:44] [m[m[32m[1m   Compiling[m xattr v0.1.11
[01:15:45] [m[m[32m[1m   Compiling[m walkdir v1.0.7
[01:15:51] [m[m[32m[1m   Compiling[m tar v0.4.14
[01:15:51] [m[m[32m[1m   Compiling[m lzma-sys v0.1.9
[01:15:51] [m[m[32m[1m   Compiling[m clap v2.29.0
[01:15:51] [m[m[32m[1m   Compiling[m flate2 v1.0.1
[01:16:24] [m[m[32m[1m   Compiling[m xz2 v0.1.3
[01:17:06] [m[m[32m[1m   Compiling[m installer v0.0.0 (file:///checkout/src/tools/rust-installer)
[01:17:11] [m[m[32m[1m    Finished[m release [optimized] target(s) in 87.85 secs
[01:17:11] travis_fold:end:stage0-fabricate
[0K
[01:17:11] travis_time:end:stage0-fabricate:start=1518291862965457303,finish=1518291951467994290,duration=88502536987
[0K
[01:17:11] Error: failed to generate installer
[01:17:11] Caused by: failed to copy '/checkout/obj/build/tmp/dist/rust-docs-beta-x86_64-unknown-linux-musl-image/share/doc/rust/html/alloc/slice/struct.Chunks.html' to '/checkout/obj/build/tmp/dist/rust-docs-beta-x86_64-unknown-linux-musl/rust-docs/share/doc/rust/html/alloc/slice/struct.Chunks.html'
[01:17:11] Caused by: No space left on device (os error 28)
```

The disk usage report, 14 GB used by `run-pass` alone

```
14874920	./obj/build/x86_64-unknown-linux-gnu/test/run-pass
```

**Comment by Mark-Simulacrum** [comment]
I'm going to retry, I have a hard time believing this is actually constantly true because of this patch... @bors retry

**Comment by kennytm** [comment]
@Mark-Simulacrum The size is 10 GB six months ago, so it is likely a very old problem. We can patch compiletest to delete those generated *.err/*.out dump if the test is successful.

**Comment by Mark-Simulacrum** [comment]
Well, sure, and we probably should just not keep any artifacts around on CI that aren't going to be used, but I would somewhat expect this PR not to alter whether we fail or succeed.

**Comment by Mark-Simulacrum** [comment]
Well, I guess it looks like we're going to have trouble landing this without some space-saving patches...

```
[01:07:11] travis_fold:end:stage0-fabricate
[0K
[01:07:11] travis_time:end:stage0-fabricate:start=1518306511032822992,finish=1518306587761868217,duration=76729045225
[0K
[01:07:12] Error: failed to generate installer
[01:07:12] Caused by: failed to write .xz
[01:07:12] Caused by: No space left on device (os error 28)
[01:07:12] 
```

**Comment by kennytm** [comment]
@onur Could you try to ignore the `rustc-rust-log.rs` test:

```diff
diff --git a/src/test/run-pass/rustc-rust-log.rs b/src/test/run-pass/rustc-rust-log.rs
index 629387d4cb..a0e04beaa9 100644
--- a/src/test/run-pass/rustc-rust-log.rs
+++ b/src/test/run-pass/rustc-rust-log.rs
@@ -9,5 +9,6 @@
 // except according to those terms.
 
 // rustc-env:RUST_LOG=debug
+// ignore-musl - workaround to avoid consuming all CI storage, see #48118
```

I bet 90% of the space usage comes from this test.

**Comment by onur** [comment]
Done @kennytm

**Comment by kennytm** [comment]
Guess we're wrong, `run-pass` is still consuming 14 GB  storage 😞

**Comment by Mark-Simulacrum** [comment]
going to close this in favor of the general beta backport PR (#48146)

**Pull request closed without merging**
