### PR TITLE
std::error::Error: change the error iterator producer

### PR DESCRIPTION
**Pull request by haraldh**
To produce an error iterator `std::error::Chain` one had to call
`<dyn Error>::chain()`, which was not very ergonomic, because you have to
manually cast to a trait object, if you didn't already have one with
the type erased.

```
    let mut iter = (&my_error as &(dyn Error)).chain();
    // or
    let mut iter = <dyn Error>::chain(&my_error);
    // or
    let mut iter = Error::chain(&my_error);
```

The `chain()` method can't be implemented on the Error trait, because of
https://github.com/rust-lang/rust/issues/69161

`Chain::new()` replaces `<dyn Error>::chain()` as a good alternative
without confusing users, why they can't use `my_error.chain()` directly.

The `Error::sources()` method doesn't have this problem, so implement
it more efficiently, than one could achieve this with `Chain::new().skip(1)`.

Related: https://github.com/rust-lang/rust/issues/58520

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks for pushing this forward @haraldh!

If the only thing blocking us from an ergonomic `chain` method on the `Error` trait itself is #69161 that seems pretty point-in-time to me so I think keeping the `.chain()` method on `dyn Error` and adding it to the `Error` trait later seems fine to me. We don't seem to have made progress on  #69161 but I don't think that's a reason to expose a `Chain::new`, which isn't an approach used by iterators generally (`array::IntoIter::new` is a temporary exception). If we wanted this approach I imagine we'd offer a free `chain` function in `std::error` instead.

**Comment by haraldh** [comment]
> If we wanted this approach I imagine we'd offer a free `chain` function in `std::error` instead.

@KodrAus yeah, a `pub fn error_chain()` was my first approach... then again I thought, that it really is a `Chain` constructor in reality.

Feel free to close this PR, if it doesn't fit.

**Comment by KodrAus** [comment]
Since this is all unstable I don’t think there’s any harm in at least re-introducing `.sources()`.

If we didn’t want to do that yet then adding an example on using `iter::successors` to iterate the chain of sources would be nice.

What do you think?

**Comment by haraldh** [comment]
TIL about `std::iter::successors`.

`<dyn Error>::chain()` is
```rust
std::iter::successors::<&(dyn Error), _>(Some(&my_error), |e| e.source())
```

`Error::sources()` is
```rust
std::iter::successors::(my_error.source(), |e| e.source())
```

So, `Error::Chain` is basically obsolete

**Comment by KodrAus** [comment]
I think the subtle difference that makes an example worth adding is that we need to manually dereference the successor error in that closure, otherwise we run afoul of lifetime mismatches. So it looks a bit more like:

```
std::iter::successors::(my_error.source(), |&e| e.source())
```

**Pull request closed without merging**
