### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Successful merges:

 - #102623 (translation: eager translation)
 - #102719 (Enforce alphabetical sorting with tidy)
 - #102830 (Unify `tcx.constness` query and param env constness checks)
 - #102883 (Fix stabilization of `feature(half_open_range_patterns)`)
 - #102927 (Fix `let` keyword removal suggestion in structs)
 - #102936 (rustdoc: remove unused CSS `nav.sum`)
 - #102940 (Update books)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=102623,102719,102830,102883,102927,102936,102940)

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 904567d19629d4e9cbc169d77444bf469ed46343

**Comment by rylev** [comment]
@compiler-errors @fee1-dead it seems that https://github.com/rust-lang/rust/pull/102830 has produced perf regressions. 

I ran callgrind-diff on bitmaps check incremental unchanged and got the following which definitely seems related to the change in the suspect PR:

```
3,833,992  ???:rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::constness, rustc_query_impl::plumbing::QueryCtxt>
2,908,408  ???:<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
1,174,324  ???:<rustc_query_system::dep_graph::serialized::SerializedDepGraph<rustc_middle::dep_graph::dep_node::DepKind> as rustc_serialize::serialize::Decodable<rustc_serialize::opaque::MemDecoder>>::decode
  863,312  ???:rustc_query_system::dep_graph::graph::hash_result::<rustc_hir::hir::Constness>
  833,638  ???:<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_query_deserialization::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::DefId, rustc_hir::hir::Constness>::{closure
 -738,304  ???:<rustc_query_impl::on_disk_cache::OnDiskCache>::try_load_query_result::<()>
  705,344  ???:rustc_query_impl::plumbing::try_load_from_disk::<()>
  584,339  ???:<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_hir::hir::Constness> as rustc_query_system::query::caches::QueryCache>::iter
 -558,531  ???:rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::hir_owner_parent, rustc_query_impl::plumbing::QueryCtxt>
  504,729  ???:<core::iter::adapters::map::Map<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_query_system::dep_graph::dep_node::DepNode<rustc_middle::dep_graph::dep_node::DepKind>>>, <rustc_index::vec::IndexVec<rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex, rustc_query_system::dep_graph::dep_node::DepNode<rustc_middle::dep_graph::dep_node::DepKind>>>::iter_enumerated::{closure
  451,748  ???:<rustc_metadata::rmeta::encoder::EncodeContext>::encode_def_ids
```

**Comment by compiler-errors** [comment]
I can put up a PR to fix or revert the perf regression, since it's just a clean up and not actually fixing anything..

**Pull request merged**
