### PR TITLE
updated E0050 in new format

### PR DESCRIPTION
**Pull request by prabodhtiwari**
Part of #35233

### CODE REVIEW

**Comment by prabodhtiwari** [comment]
@GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks!

Please update the corresponding test-file in compile-fail directory.

**Comment by sanxiyn** [comment]
Label should use actual number of parameters in the trait declaration. Hardcoding "2 parameters" is no-no.

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Pull request closed without merging**
