### PR TITLE
Update Clippy

### PR DESCRIPTION
**Pull request by flip1995**
Delayed Clippy sync

r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors r+ p=1

we've got some CI flakiness in GHA but let's see how this goes

**Comment by camsteffen** [comment]
Reopen the PR?

**Comment by Manishearth** [comment]
eh, we can just wait for bors to run full tests.

**Comment by flip1995** [comment]
`dist-aarch64-apple` seems to have timed out. (run build is still going, at least if you can trust the GHA UI)

@bors retry

**Pull request merged**
