### PR TITLE
Only check the compiler and standard library before documenting them (take 2)

### PR DESCRIPTION
**Pull request by jyn514**
Trying https://github.com/rust-lang/rust/pull/88675 again.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm happy to approve it to try it on CI but you'll need to revert the CI changes so we don't by accident land those :)

**Comment by jyn514** [comment]
> I'm happy to approve it to try it on CI but you'll need to revert the CI changes so we don't by accident land those :)

Sure, done :) and if you have suggestions for how to test this without a full bors run, that would be extremely helpful too.

**Comment by Mark-Simulacrum** [comment]
re:full CI, try builds *should* be equivalent, unlike on-PR builds which have a different and more limited set of permissions.

The changes here seem broadly correct though so I'm happy to run full CI and we can move to try builds for faster iteration after that (I can delegate or whatever the PR if you don't have permissions). @bors r+

**Comment by jyn514** [comment]
@bors retry

spurious windows failure - is there an issue open somewhere for fixing it? cc @ChrisDenton

**Comment by jyn514** [comment]
Same spurious failure :(
@bors retry

**Comment by ChrisDenton** [comment]
@jyn514 Yes I have a fix for this (#95841).

**Comment by jyn514** [comment]
Wasn't able to reproduce, but did come up with the idea this might be because both the `compile::Rustc` and `check::Rustc` artifacts are in the sysroot. Changed `tool_doc!` to do a full compile instead of a check to see if it avoids the issue. `doc compiler` will still only check it.

**Comment by jyn514** [comment]
@bors r=Mark-Simulacrum rollup=never

If this doesn't work, I think I'm going to try and merge the libstd changes separately, they should be less likely to fail.

**Comment by jyn514** [comment]
I think these are just noise. The bootstrap changes don't affect `build` at all, only documenting.

**Comment by pnkfelix** [comment]
Visiting for weekly performance triage.

* hypothesized to be noise and pnkfelix doesn't have time to dig more deeply.

@rustbot label: +perf-regression-triaged

**Pull request merged**
