### PR TITLE
Enable MIR JumpThreading by default

### PR DESCRIPTION
**Pull request by cjgillot**
Mostly for perf

r? @ghost

### CODE REVIEW

**Comment by cjgillot** [comment]
The perf results are split. We get some wins on a wide set of benchmarks, but losses on full builds of some popular crates.
Putting this up for review, and to discuss the next steps.

**Comment by cjgillot** [comment]
r? compiler

**Comment by petrochenkov** [comment]
This needs to be reviewed by someone who knows the context (are the removed passes subsumed by the enabled pass? why?) and can read mir-opt test diffs.
r? @tmiasko

**Comment by apiraino** [comment]
removing flag that about waiting on review, seems it's WIP

@rustbot s-waiting-on-review

**Comment by cjgillot** [comment]
Blocked on https://github.com/rust-lang/rust/pull/119461

**Comment by cjgillot** [comment]
Looking at the profiles, the complexity is due to the backtracking algorithm. For html5ever, diesel and serde, most potent regressions, dominator computation is <10% of the pass.
The pass is located just after `SimplifyConstCondition`, which clears the caches. Trying to swap them.
@bors try @rust-timer queue

**Comment by Kobzol** [comment]
Btw, this seems to have quite nice runtime wins for some of the hashmap benchmarks.
image

**Comment by cjgillot** [comment]
@tmiasko I'd rather have the former version, and work on the general algorithm, and investigate switching from backtracking to dataflow later.

**Comment by cjgillot** [comment]
> The former version as in without changing pass order?

Yes. Running simplification first will trim down the CFG and avoid some work by JumpThreading.
@bors r=tmiasko

For perf triage: the preliminary perf results show an small improvement on many benchmarks and on average. However, there are a few significant regressions on opt builds (regex, html5ever, diesel, serde). I propose to address them in follow-up, as improvements to the current algorithm.

**Comment by Kobzol** [comment]
The wins outweight the losses here. Furthermore, the compiler is doing more work, which should result in better runtime performance, which also seems to be shown in the runtime benchmarks.

@rustbot label: +perf-regression-triaged

**Pull request merged**
