### PR TITLE
Fix bad suggestion for clone/is_some in field init shorthand

### LINKED ISSUE #108470: Bad suggestion for clone in field init shorthand
### Code

```Rust
struct Foo {
    t: Thing
}

#[derive(Clone)]
struct Thing;

fn main() {
    let t = &Thing;
    let f = Foo {
        t
    };
}
```

### Current output

```Shell
error[E0308]: mismatched types
  --> src/main.rs:11:9
   |
11 |         t
   |         ^ expected `Thing`, found `&Thing`
   |
help: consider using clone here
   |
11 |         t.clone()
   |          ++++++++
```

### Desired output

```Shell
error[E0308]: mismatched types
  --> src/main.rs:11:9
   |
11 |         t
   |         ^ expected `Thing`, found `&Thing`
   |
help: consider using clone here
   |
11 |         t: t.clone()
   |         ++  ++++++++
```

### Rationale and extra context

The suggestion is not compatible with struct field init shorthand syntax. The suggestion should include the field name when rewriting.

### Other cases

_No response_

### Anything else?

```
rustc 1.69.0-nightly (c5c7d2b37 2023-02-24)
binary: rustc
commit-hash: c5c7d2b37780dac1092e75f12ab97dd56c30861d
commit-date: 2023-02-24
host: aarch64-apple-darwin
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #108470

### CODE REVIEW

**Comment by compiler-errors** [comment]
I think you can use `maybe_get_struct_pattern_shorthand_field` here instead of matching on the hir yourself?

**Comment by compiler-errors** [comment]
Or better yet -- i wonder if we could make an even better helper method that simplifies the duplicated logic between all of the suggestions that handle field init shorthand syntax specially...

**Comment by chenyukang** [comment]
> Or better yet -- i wonder if we could make an even better helper method that simplifies the duplicated logic between all of the suggestions that handle field init shorthand syntax specially...

try to move the `span` part to `maybe_get_struct_pattern_shorthand_field`, seems better now?

**Comment by chenyukang** [comment]
> Hmm... I don't really like the new calls to `span_to_snippet`... I wonder if we could just return a `Vec<(Span, String)>` that's either `"field: "` or empty that we can then use for the multipart suggestion...

I have a try, but seems `maybe_get_struct_pattern_shorthand_field` is not only used for fields and multipart suggestion, so we need to return an `Option<>` which also will make the code somehow not easy to read.

I rollback my last commit, and use the original `maybe_get_struct_pattern_shorthand_field` now.

**Pull request merged**
