### PR TITLE
[experimental]: Build LLVM with ThinLTO enabled

### PR DESCRIPTION
**Pull request by michaelwoerister**
This is a work in progress. Let's see how it goes.

### CODE REVIEW

**Comment by michaelwoerister** [comment]
@Mark-Simulacrum, a try build will use the `src/ci/docker/dist-x86_64-linux/Dockerfile`, right?

**Comment by alexcrichton** [comment]
@bors: try

Indeed!

**Comment by michaelwoerister** [comment]
Note that this doesn't do much yet.

I'm trying to pass some additional linker args when building `rustc_codegen_llvm` but without any luck yet. I can't use `cargo rustc` because `bootstrap` doesn't support it (and adding support turns out to be a proper rabbit hole). Any ideas, @rust-lang/infra?

**Comment by michaelwoerister** [comment]
I think I'll add a custom `Command` type that is like `std::process::Command` supports "deferred" args that get added at the end just before the command is run...

**Comment by Mark-Simulacrum** [comment]
@michaelwoerister It might be easier to implement the "deferred args" thing via checking the `--crate-name` argument passed to the rustc shim (src/bootstrap/bin/rustc.rs) and then adding the relevant args there. Not sure though.

**Comment by michaelwoerister** [comment]
@kennytm, wait, what's going on here? https://travis-ci.org/rust-lang/rust/jobs/385738110 is still running :confused:

**Comment by kennytm** [comment]
@michaelwoerister  Huh. Probably messed up due to having too many try builds in parallel. I've canceled the latest try build, let's manually monitor Travis for now.

**Comment by michaelwoerister** [comment]
Thanks, @kennytm! 

The good news, in that other job, it's been able to successfully download the LLD source and it's building Clang & LLD for quite a while without error now. If I understand this correctly we should soon have a cached docker image containing LLD, right?

**Comment by kennytm** [comment]
@michaelwoerister If the whole build process can complete within 3 hours, yes.

**Comment by kennytm** [comment]
The Docker image is cached.

```
[01:46:45] Built container sha256:d35edc6faeeeb07be3e6dcb2a4f2702979e24668d8322f6f3a0767b547a052f9
[01:46:45] Uploading finished image to s3://rust-lang-ci-sccache2/docker/534a6ed7b22a99293db56926a2c79e3d70de1bf51c801f999b36ff38d3970b0da43e7565d180711ddcea7de7eb7d78cb1300c306f7f987676c00ade5a5305267
```

**Comment by michaelwoerister** [comment]
> The Docker image is cached.

That's good news!

**Comment by michaelwoerister** [comment]
There seems to be some mismatch between how LLVM and how LLD is built:
https://travis-ci.org/rust-lang/rust/jobs/386158175#L9195

**Comment by TimNN** [comment]
(Note to triagers: @michaelwoerister won't be available until ~early July)

**Comment by TimNN** [comment]
Ping from triage, @michaelwoerister! Do you think you'll be able to work on this again?

**Comment by michaelwoerister** [comment]
I think I'll wait until https://github.com/rust-lang/rust/pull/52019 is available in the bootstrap compiler. That will make things a lot nicer.

**Comment by Mark-Simulacrum** [comment]
Is it worth doing a (minor) beta backport to expedite this?

**Comment by michaelwoerister** [comment]
No, I still need to implement proper Windows support for the linker-plugin-based LTO stuff. In any case, this is not too urgent.

**Comment by pietroalbini** [comment]
Ping from triage @michaelwoerister! It's been a while since we heard from you, will you have time to work on this again?

**Comment by pietroalbini** [comment]
Thank you for this PR @michaelwoerister! Unfortunately we haven't heard from you on this in a while, so I'm closing the PR to keep things tidy. Don't worry though, if you'll have time again in the future please **reopen** this PR, we'll be happy to review it again!

**Pull request closed without merging**
