### PR TITLE
adt: Allow repr attribute on single variant enum.

### LINKED ISSUE #33202: ICE with C generic enum
http://is.gd/DOkUCJ Playground with backtrace

```rust
#[repr(C)]
pub enum CPOption<T> {
	PSome(T),
}

fn main() {
  println!("sizeof CPOption<i32> {}", std::mem::size_of::<CPOption<i32>>());
}
```

Versions affected: stable, beta, nightly.

### PR DESCRIPTION
**Pull request by luqmana**
Fixes #33202.

### CODE REVIEW

**Comment by nrc** [comment]
Why can't we let `repr` override the behaviour of single variant structs having no discriminant? That seems more user-friendly than having an error here.

cc @rust-lang/lang

**Comment by aturon** [comment]
Nominating for discussion at the next meeting, if we don't reach consensus before then.

**Comment by nikomatsakis** [comment]
Discussed in @rust-lang/lang meeting. I think we all agree it seems like permitting this annotation might be nice, but if it's awkward to implement, than an error is fine too. @luqmana what say you?

**Comment by luqmana** [comment]
@nikomatsakis Ok, I made it an error because there was an asset in trans to that effect. I can change it to allow this.

**Comment by luqmana** [comment]
Ok, updated `trans::adt` to allow such cases.

**Pull request merged**
