### PR TITLE
[beta] Update compiler-rt to fix SPARC LLVM bug 11663.

### PR DESCRIPTION
**Pull request by dhduvall**

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Thanks.

**Comment by nikomatsakis** [comment]
Actually, a question: is there a way for us to write a test of this? I'm not sure what we do for platforms like SPARC etc.

**Comment by nikomatsakis** [comment]
@bors r+ 

Seems OK.

**Comment by dhduvall** [comment]
Frankly, I'm not sure, either. I've been chatting with @alexcrichton and @brson about getting Solaris (and Solaris/SPARC) into Rust's CI, but given the move from buildbot to Travis, this is even more difficult than it would have been in the past. We still want to get there, but I suspect it's going to be a while before it really comes together.

@binarycrusader

**Comment by alexcrichton** [comment]
@nikomatsakis ah yeah this is ok, we unfortunately don't have much testing for these platforms right now.

@dhduvall yeah and unfortunately we're running close to the limit on Travis right now so we can't even add an emulator :(

**Comment by alexcrichton** [comment]
@dhduvall one thing I'd be really interested in learning though is regressions over time for platforms like this. I think there's a lot of work to go in initially to get tests to pass at all, but in my experience we've had very few regressions over time. I'd love to have more data on that though (it may just be that my gut is wrong)

**Comment by dhduvall** [comment]
I've gotten the entire testsuite running on both x86 and SPARC Solaris (I had to make some modifications so that the run didn't exit after the first suite failure), and there are notably more on SPARC than on x86, but neither I nor any of my colleagues who are working on this have yet had time to go track down the failures. I'm happy to post the results if anyone else wants to poke at them, but otherwise, we'll work through them as best we can.

I do plan on setting up a nightly build and test run for master, but like you, I'm not expecting a lot of regressions, so it's not been high on my priority list.

**Comment by alexcrichton** [comment]
Oh that's awesome! Yeah if you've got a list on-hand I wouldn't mind taking a peek :)

My guess is there's a ton of tests that just need a new `// ignore` annotation, a bunch of them are x86 specific

**Comment by dhduvall** [comment]
https://gist.github.com/dhduvall/409e1203aabc8ce1a3aa515e2b9bbba4

**Comment by alexcrichton** [comment]
Thanks! Looks like there's definitely quite the variety of issues there :(

**Pull request merged**
