### PR TITLE
Reject huge alignments on macos with system allocator only

### PR DESCRIPTION
**Pull request by glandium**
ef8804ba277b055fdc3e6d148e680e3c1b597ad8 addressed #30170 by rejecting
huge alignments at the allocator API level, transforming a specific
platform bug/limitation into an enforced API limitation on all
platforms.

This change essentially reverts that commit, and instead makes alloc()
itself return AllocErr::Unsupported when receiving huge alignments.

This was discussed in https://github.com/rust-lang/rust/issues/32838#issuecomment-368348408
and following.

### CODE REVIEW

**Comment by glandium** [comment]
Cc @SimonSapin

**Comment by SimonSapin** [comment]
Looks good to me. I *think* we discussed doing exactly this, but just to be sure let’s get some more libs team eyes on it.

@rfcbot fcp merge

**Comment by SimonSapin** [comment]
@bors: p=1

I’m working on large-ish changes that should go on top of this to avoid merge conflicts.

**Pull request merged**
