### PR TITLE
Streamline fast rejection

### PR DESCRIPTION
**Pull request by nnethercote**
Some reworkings of this code that make it a little nicer.

r? @lcnr

### CODE REVIEW

**Comment by nnethercote** [comment]
Best reviewed one commit at a time.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
Hmm, surprising results. Those 1-2% regressions for `bitmaps` were all 1-2% wins locally. Maybe due to PGO? Let's try something slightly different.

@bors try @rust-timer queue

**Comment by nnethercote** [comment]
So, perf is neutral now. (I will assume the supposed max-rss regressions are noise, because there is no reason why this change should have that effect.) This PR is now just about making the code a little nicer.

**Review by compiler-errors — APPROVED** [review]

**Comment by compiler-errors** [comment]
f*** wait there's a merge conflict

@bors r-

r=me

**Pull request merged**
