### PR TITLE
#36107 - Updated E0512 error message format

### PR DESCRIPTION
**Pull request by mrstork**
r? @jonathandturner

### CODE REVIEW

**Comment by mrstork** [comment]
@jonathandturner Any advice on this?
> thread '[run-pass] run-pass/issue-36023.rs' panicked at 'explicit panic', /build/src/tools/compiletest/src/runtest.rs:2356

I don't even see an issue-36023.rs in the repo.

**Comment by jonathandturner** [comment]
I think that's a known issue with Travis currently

**Comment by GuillaumeGomez** [comment]
I restarted travis.

**Comment by jonathandturner** [comment]
Looks like someone landed a fix to E0512 last night.  You may want to take a look at what was changed.  If there are additional changes needed, you can create a PR to make the additional changes.

**Comment by mrstork** [comment]
No other changes are necessary, our commits were essentially identical.

**Pull request closed without merging**
