### PR TITLE
Update error format for E0130

### LINKED ISSUE #35256: E0130 needs to be updated to new format
From: src/test/compile-fail/E0130.rs

Error E0130 needs a span_label, updating it from:

```
error[E0130]: patterns aren't allowed in foreign function declarations
  --> src/test/compile-fail/E0130.rs:12:12
   |
12 |     fn foo((a, b): (u32, u32)); //~ ERROR E0130
   |            ^^^^^^
```

To:

```
error[E0130]: patterns aren't allowed in foreign function declarations
  --> src/test/compile-fail/E0130.rs:12:12
   |
12 |     fn foo((a, b): (u32, u32)); //~ ERROR E0130
   |            ^^^^^^ pattern not allowed in foreign function
```

### PR DESCRIPTION
**Pull request by trixnz**
Fixes #35256 as part of #35233

r? @jonathandturner

### CODE REVIEW

**Comment by sanxiyn** [comment]
From Travis:

```
failures:
    [compile-fail] compile-fail/no-patterns-in-args.rs
```

**Comment by trixnz** [comment]
@sanxiyn It should be fixed now with the addition of https://github.com/rust-lang/rust/pull/35331/commits/4c672e07b996b79dae2ff7cf20cdbd35a6f8233d.
`test result: ok. 2390 passed; 0 failed; 21 ignored; 0 measured`

**Pull request merged**
