### PR TITLE
Recognize `private_intra_doc_links` as a lint

### PR DESCRIPTION
**Pull request by jyn514**
Previously, trying to allow this would give another error!

```
warning: unknown lint: `private_intra_doc_links`
 --> private.rs:1:10
  |
1 | #![allow(private_intra_doc_links)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `broken_intra_doc_links`
  |
  = note: `#[warn(unknown_lints)]` on by default

warning: public documentation for `DocMe` links to private item `DontDocMe`
 --> private.rs:2:11
  |
2 | /// docs [DontDocMe]
  |           ^^^^^^^^^ this item is private
  |
  = note: `#[warn(private_intra_doc_links)]` on by default
  = note: this link will resolve properly if you pass `--document-private-items`
```

Fixes the issue found in https://github.com/rust-lang/rust/pull/77249#issuecomment-712339227.

r? @Manishearth 

Does anyone know why this additional step is necessary? It seems weird this has to be declared in 3 different places.

### CODE REVIEW

**Comment by Manishearth** [comment]
Because it's a rustdoc-exclusive lint and is otherwise only declared in rustdoc code

@bors r+

**Comment by jyn514** [comment]
@bors r-

This causes the tests to fail and I don't understand why:

```
---- [ui] rustdoc-ui/intra-links-private.rs#private stdout ----
diff of stderr:

-	warning: public documentation for `DocMe` links to private item `DontDocMe`
-	  --> $DIR/intra-links-private.rs:5:11
-	   |
-	LL | /// docs [DontDocMe]
-	   |           ^^^^^^^^^ this item is private
-	   |
-	   = note: `#[warn(private_intra_doc_links)]` on by default
-	   = note: this link resolves only because you passed `--document-private-items`, but will break without
-	
-	warning: 1 warning emitted
-	
-	
```

**Comment by oli-obk** [comment]
Rustdoc has its own lint list.

In https://github.com/rust-lang/rust/blob/8ae3b509768774a9d351b939d18d5cb421b6ed3b/src/librustdoc/core.rs#L251 the hardwired lints are extracted and filtered. The actual list is https://github.com/rust-lang/rust/blob/8ae3b509768774a9d351b939d18d5cb421b6ed3b/src/librustdoc/core.rs#L337

Though I don't get the double check in https://github.com/rust-lang/rust/blob/8ae3b509768774a9d351b939d18d5cb421b6ed3b/src/librustdoc/core.rs#L350 (cc @GuillaumeGomez )

Anyway, I think adding the lint to `lints_to_show` should make it work again

**Comment by GuillaumeGomez** [comment]
@oli-obk  The check you linked is to prevent some lints to be allowed by default iirc.

**Comment by jyn514** [comment]
I think the right fix here is to never silence lints from the `rustdoc` lint group, then there wouldn't be so many places to add new lints.

How do I get the rustdoc lint group? I found [`LintStore::lint_groups`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/struct.LintStore.html#structfield.lint_groups), but I don't know how to get a `LintStore`.

**Comment by jyn514** [comment]
[Queries::register_plugins](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_interface/struct.Queries.html#method.register_plugins) looks right, but rustdoc only has access to `Queries` _after_ it already creates the config, and that can't be fixed because `create_compiler_and_run` takes a config and comes before `compiler.enter`.

Is there really no simpler way to do this?

**Comment by jyn514** [comment]
I changed this to hard-code the lints for now, but I'd really like to fix this at some point.

**Comment by oli-obk** [comment]
@bors r+

yea, let's get this landed for now.

**Pull request merged**
