### PR TITLE
keyword docs for else and inkeyword docs for else and in.

### PR DESCRIPTION
**Pull request by gilescope**
First cut of else and in keyword docs. Comments and suggestions more than welcome.

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage:
@gilescope   - can you address the build failure in this PR, please? Thank you.

**Comment by hdhoang** [comment]
ping from triage @gilescope, any updates on this? The previous build log has been removed already so I can't check further details

**Comment by gilescope** [comment]
Sorry for the delay. Will get on to it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gilescope** [comment]
@Dylan-DPC it's building now - are we happy with the contents or are there any suggestions on how we can improve it?

**Comment by Dylan-DPC** [comment]
Oops didn't see this for some reason. Let me review it. Looks good to me

**Comment by gilescope** [comment]
@Dylan-DPC how's it looking? Any suggestions or is this landable?

**Pull request merged**
