### PR TITLE
Don't give invalid suggestion on desugared span.

### PR DESCRIPTION
**Pull request by spunit262**

### CODE REVIEW

**Comment by JohnCSimon** [comment]
Ping from triage: 
@spunit262 - can you please address the test failures? Thanks.

**Comment by spunit262** [comment]
The cause of the failure is the CI issue that was causing almost all PR to fail about a while ago, and that was fixed in #69252.

I checked to make sure that there was no bit rot, so I don't think there's anything for me to do on my end.

**Comment by JohnTitor** [comment]
I don't think it's related to #69252 but indeed the failure seems spurious.
@bors retry

**Pull request merged**
