### PR TITLE
debug directory no longer gets created in Cargo by default

### PR DESCRIPTION
**Pull request by maxdemarzi**
Brand new to Rust, going through the hello cargo example and there was no "debug" directory to be found.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm interesting! What version of Cargo are you using? This was changed about a month ago to add a `debug`, and I don't think we've reverted it in the meantime!

**Comment by maxdemarzi** [comment]
cargo -V
cargo 0.0.1-pre-nightly (dd7c7bd 2015-03-04) (built 2015-03-04)

**Comment by maxdemarzi** [comment]
Ok, just tried this on latest and it does create the debug folder. Closing.
cargo -V
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-03-31)

**Comment by alexcrichton** [comment]
Ah in that case it looks like you may want to make sure you're [running the most up-to-date Cargo](https://crates.io/install) and you should have `debug` directories as expected!

Thanks regardless for the PR though!

**Pull request closed without merging**
