### PR TITLE
Alphabetize language features

### PR DESCRIPTION
**Pull request by jhpratt**
This should significantly reduce the frequency of merge conflicts.

r? @joshtriplett 

@rustbot label: +A-contributor-roadblock +S-waiting-on-review

### CODE REVIEW

**Comment by joshtriplett** [comment]
LGTM; r=me when it passes CI. And thanks!

**Comment by jhpratt** [comment]
I'm unable to do r=you 😄

**Comment by Mark-Simulacrum** [comment]
Hm. So while this seems OK, it also does make it more annoying to add new features in -- particularly when the tidy lint doesn't tell you where you *should* put it.

I think there was some conversation about a merge driver potentially letting us do this nicely without needing to change the alphabetization?

**Comment by jhpratt** [comment]
A merge driver could work, but it appeared that neither GitHub nor bors support custom drivers.

**Comment by Mark-Simulacrum** [comment]
I would expect that bors *should* support a .gitattributes specified merge=union for this file, which I think is correct in most cases -- when no new release has happened?

bors currently just shells out to git, so if we can get that to work, I would prefer it over a solution that makes life harder for those adding to this file (which prevents merge conflicts but doesn't fully remove the pain).

It also seems like it should be possible to define a filter via .gitattributes that sorts the file automatically on `git add`, perhaps? I haven't read the documentation closely, but it seems like that pretty closely maps to our use case here?

**Comment by jhpratt** [comment]
Per a discussion on Zulip, I've added a suggestion as to where a feature should be placed. This works on the assumption that features are added at the end of the list, which is currently always the case. If it's added in a different location, the suggestion will technically be correct but is less than ideal.

**Comment by Mark-Simulacrum** [comment]
Please add the comment to the end of the list indicating the alphabetical ordering (as suggested by @joshtriplett over Zulip, earlier). I think once that's in place, we can merge.

**Comment by jhpratt** [comment]
Added.

**Pull request merged**
