### PR TITLE
Enable debuginfo tests that have been "temporarily disabled" for the past 6 years

### PR DESCRIPTION
**Pull request by saethlin**
The PR history is a bit of a mess because I had to test this a lot with try-jobs, so I'll try to summarize the non-obvious changes here.

A number of tests now have `min-lldb-version: 1800`. Those tests should have gotten an lldb version jump either in https://github.com/rust-lang/rust/pull/124781 or long ago. Note that all such tests with that lldb version requirement do not run in Apple CI.

`tests/debuginfo/drop-locations.rs` is staying disabled for now because gdb doesn't know to stop on the drop calls produced by a `}`: https://github.com/rust-lang/rust/issues/128971

`tests/debuginfo/function-arg-initialization.rs` now has `-Zmir-enable-passes=-SingleUseConsts`; without that we initialize the const before the function prelude: https://github.com/rust-lang/rust/issues/128945

`tests/debuginfo/by-value-non-immediate-argument.rs` fails because we don't generate a function prelude for unused non-immediate arguments, even with all optimizations disabled, and this seems to confuse debuggers on aarch64: https://github.com/rust-lang/rust/issues/128973

`tests/debuginfo/pretty-std.rs` is staying disabled on windows-gnu because our test harness doesn't know how to load our pretty-printers on that target: https://github.com/rust-lang/rust/issues/128981

`tests/debuginfo/method-on-enum.rs` and `tests/debuginfo/option-like-enum.rs` encounter some kind of gdb bug on i686-pc-windows-gnu. I don't know enough about that situation to write a good issue.

I plan on doing more work on this test suite. There's clearly a lot more basic cleanup work to do here.

### CODE REVIEW

**Review by compiler-errors — APPROVED** [review]
✨ 

r=me unless you want a particular review from someone

**Comment by saethlin** [comment]
I think any compiler reviewer can suffice here :)
r? compiler-errors
@bors r=compiler-errors rollup=never

**Comment by saethlin** [comment]
We have an incredible amount of rollup=never PRs in queue and I'm quite tired of this bouncing out.

I've added every job to this PR as a try-job except for those that are `-dist`, `-2`, `-ext`, or are run in PR CI.

@bors try

**Comment by saethlin** [comment]
Well that's deeply unfortunate. I'll have to do this in batches.

**Pull request merged**
