### PR TITLE
compiletest: Unify `cmd2procres` with `run_command_to_procres`

### PR DESCRIPTION
**Pull request by Zalathar**
Historical context: I originally added `run_command_to_procres` in #112300 and #114843, because I didn't like the overly-specific failure message in `cmd2procres`, but at the time I didn't feel confident enough to change the existing code, so I just added my own similar code.

Now I'm going back to remove this redundancy by eliminating `cmd2procress`, and adjusting all callers to use a slightly-tweaked `run_command_to_procres` instead.

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks, nice cleanup!

**Comment by jieyouxu** [comment]
r? jieyouxu @bors delegate+

**Comment by jieyouxu** [comment]
r=me after CI is green

**Comment by Zalathar** [comment]
CI is green.

@bors r=jieyouxu

**Pull request merged**
