### PR TITLE
ensure that the assert! macro doesn't ICE on non-booleans

### PR DESCRIPTION
**Pull request by oli-obk**
cc #31592

Note that this is not a fix, it exposes the span-bug even more. During stage1 `command-before-exec.rs` fails to run, because 

```
{...}x86_64-unknown-linux-gnu/test/run-pass/command-before-exec.stage1-x86_64-unknown-linux-gnu: symbol lookup error: {...}x86_64-unknown-linux-gnu/test/run-pass/command-before-exec.stage1-x86_64-unknown-linux-gnu: undefined symbol: _ZN6option15Option$LT$T$GT$6unwrap14_MSG_FILE_LINE20hc561c4c240f9e4ddnxOE
```

it works fine in stage2

---

This cannot be done for assert_eq, because ~~there's no way~~ I couldn't find a way to ensure two expressions have the same types without moving them into an array. `decltype` ftw

### CODE REVIEW

**Comment by oli-obk** [comment]
@alexcrichton [You created](https://github.com/rust-lang/rust/commit/b1898db0f10f9641c7616e93499348d4fe743ddd) the `before_exec` function. Any thoughts?

**Comment by ollie27** [comment]
This will break this code:
```rust
use std::ops::Not;

struct Foo;

impl Not for Foo {
    type Output = bool;

    fn not(self) -> Self::Output {
        false
    }
}

fn main() {
    assert!(Foo);
}
```
I don't know if that breakage is acceptable but in this case it can be fixed by putting the `!` back in front of the `$cond`.

**Comment by oli-obk** [comment]
ugh :( I so want to break this code. But that's probably not acceptable breakage.

**Comment by ollie27** [comment]
Yeah it's a similar situation to #30143.

**Pull request closed without merging**
