### PR TITLE
Better suggestions when user tries to collect into an unsized `[_]`

### LINKED ISSUE #91423: Type inference around Iterator::collect can result in confusing error messages
Given the following code:

```rust
fn process_slice(data: &[i32]) {
    todo!()
}

fn main() {
    let some_generated_vec = (0..10).collect();
    process_slice(&some_generated_vec);
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `[i32]` cannot be known at compilation time
 --> src/main.rs:6:9
  |
6 |     let some_generated_vec = (0..10).collect();
  |         ^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `[i32]`
  = note: all local variables must have a statically known size
  = help: unsized locals are gated as an unstable feature

error[E0277]: a value of type `[i32]` cannot be built from an iterator over elements of type `{integer}`
    --> src/main.rs:6:38
     |
6    |     let some_generated_vec = (0..10).collect();
     |                                      ^^^^^^^ value of type `[i32]` cannot be built from `std::iter::Iterator<Item={integer}>`
     |
     = help: the trait `FromIterator<{integer}>` is not implemented for `[i32]`
note: required by a bound in `collect`
```

I am not sure what the ideal output would be here, but currently it suggests that `collect` wants to build an array of a specific size, which hasn't been specified.

### PR DESCRIPTION
**Pull request by compiler-errors**
1. Extend the predicate on `rustc_on_unimplemented` to support substitutions like note, label, etc (i.e. treat it as a `OnUnimplementedFormatString`) so we can have slightly more general `rustc_on_unimplemented` special-cases.
2. Add a `rustc_on_unimplemented` if we fail on `FromIterator<A> for [A]` which happens when we don't explicitly collect into a `vec<A>`, but then pass the return from a `.collect` call into something that takes a slice.

Fixes #91423

### CODE REVIEW

**Comment by Aaron1011** [comment]
Could you add a test case demonstrating the new behavior?

**Comment by compiler-errors** [comment]
@Aaron1011 added a test. Still unclear what the best wording for this specific suggestion is, but demonstrating that it works.

**Comment by compiler-errors** [comment]
howdy @matthewjasper, should I reassign this PR to someone else on the high-five queue?

**Comment by matthewjasper** [comment]
Yes please

**Comment by compiler-errors** [comment]
reassigning per reviewer request

r? rust-lang/compiler

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
@compiler-errors This looks great! My only suggestion was going to be to mention the `Sized` trait but I see the other errors and notes generated do that already. Could you rebase and fix the merge conflict? Thanks!

**Comment by compiler-errors** [comment]
Alright @wesleywiser, rebased and confirmed tests still pass!

**Comment by NieDzejkob** [comment]
What would it take to add a structured suggestion to this diagnostic?

**Comment by compiler-errors** [comment]
@NieDzejkob, what do you mean by this? I don't think the `rustc_on_unimplemented` attribute supports suggestions. You'd probably need to rip this PR out and replace it with a full-fledged diagnostic that is emitted from the compiler itself. 

If you're interested in that route, you probably have a good bet putting some logic to detect this case in  `report_selection_error` in `rustc_trait_selection::traits::error_reporting`.

**Pull request merged**
