### PR TITLE
[WIP] test enabling i128 lowering for emscripten

### PR DESCRIPTION
**Pull request by est31**
Maybe this fixes the issues emscripten has with i128. Maybe not.

DO NOT MERGE

### CODE REVIEW

**Comment by est31** [comment]
I see the following failures:

run-pass/float-int-invalid-const-cast.rs

```
[01:35:06]   = note: Unsupported:   call void @_ZN28float_int_invalid_const_cast5force17haaefff15b0074e85E(i128 0)
[01:35:06]           LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
[01:35:06]           Traceback (most recent call last):
[01:35:06]             File "/emsdk-portable/emscripten/1.37.13//emcc", line 13, in <module>
[01:35:06]               emcc.run()
[01:35:06]             File "/emsdk-portable/emscripten/1.37.13/emcc.py", line 1526, in run
[01:35:06]               final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
```
run-pass/i128.rs

```
[01:35:06]   = note: Unsupported:   %699 = call { i128, i1 } @llvm.smul.with.overflow.i128(i128 11259375, i128 11259375)
[01:35:06]           LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
```

run-pass/intrinsics-integer.rs

```
[01:35:06]   = note: Unsupported:   %2311 = call i128 @llvm.ctpop.i128(i128 0)
[01:35:06]           LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
```

**Comment by est31** [comment]
> Unsupported:   call void @_ZN28float_int_invalid_const_cast5force17haaefff15b0074e85E(i128 0)
> LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits

hmmm this is something else than lowering that fails.

**Comment by scottmcm** [comment]
Not even being able to pass/return i128 was what blocked me last time:

https://github.com/rust-lang/rust/blob/15e8c5d8466ae40c1ef9b2a1d96f9cd2c4dcccf0/src/test/mir-opt/lower_128bit_debug_test.rs#L11-L14

**Comment by est31** [comment]
Guess I'm closing this then.

**Pull request closed without merging**
