### PR TITLE
Add the item type to the tooltip

### PR DESCRIPTION
**Pull request by notriddle**
See:
https://users.rust-lang.org/t/seeking-opinions-from-colorblind-rustaceans-coloring-in-rustdoc-code-blocks

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Nice! Would it be possible to render the docs with this and get a couple screenshots with the new tooltips?

**Comment by notriddle** [comment]
tooltip1
tooltip2
tooltip3
tooltip4

**Comment by notriddle** [comment]
And, one last thing, the Result types:

tooltip5
tooltip6

**Comment by QuietMisdreavus** [comment]
Thanks! That one with `Iterator::Item` is a little weird. It's pulling from the same type info that its link is getting, so in that sense it's correct, but something seems off if everything else has the same name as its text but that. I'd *like* for that to have something like `type std::iter::Iterator::Item` but I'm not sure how you'd get there offhand. (That might also cause associated items to render in orange, since that's the color for "type"s.)

**Comment by GuillaumeGomez** [comment]
Thanks a lot for this. Since everyone seems to agree on the improvement here, let's merge!

@bors: r+ rollup

**Pull request merged**
