### PR TITLE
Update RLS

### LINKED ISSUE #77810: `rls` no longer builds after rust-lang/rust#77649
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#77649, I observed that the tool rls no longer builds.
A follow-up PR to the repository https://github.com/rust-lang/rls is needed to fix the fallout.

cc @dash2507, do you think you would have time to do the follow-up work?
If so, that would be great!

### PR DESCRIPTION
**Pull request by Xanewok**
cc #77819 
Fixes #77810

r? @ghost

### CODE REVIEW

**Comment by Xanewok** [comment]
@mati865 @Mark-Simulacrum I don't think this should be beta-nominated, right? If we bumped crossbeam in #77819 then I imagine this also affects the version pulled by RLS in the workspace context there and should suffice

**Comment by Xanewok** [comment]
Let's land this in the meantime

@bors r? @Xanewok r+ p=1 (fixes toolstate)

**Comment by Xanewok** [comment]
> bors r? @Xanewok r+ p=1 (fixes toolstate)

maybe that's too many options at once :(

@bors r+ p=1

**Comment by mati865** [comment]
> 
> 
> > bors r? @Xanewok r+ p=1 (fixes toolstate)
> 
> maybe that's too many options at once :(
> 

This would be correct syntax but I have no idea if it works: `r? @Xanewok @bors r+ p=1 (fixes toolstate)`

> I don't think this should be beta-nominated, right?

I don't think so but it's up to @Mark-Simulacrum

**Pull request merged**
