### PR TITLE
Rename `fmt::Writer` to `fmt::Write`

### PR DESCRIPTION
**Pull request by lambda-fairy**
This brings it in line with its namesake in `std::io`.

[breaking-change]

r? @aturon

### CODE REVIEW

**Comment by aturon** [comment]
Sorry for the slow review, was away for the weekend.

This looks great to me! Just want to check in with @alexcrichton before I send it to bors.

**Comment by alexcrichton** [comment]
Hm I do agree that `Writer` seems out of place but to truly mirror `io::Write` this trait should be called `WriteStr` as it is the main method of the trait. That seems... odd though.

I would personally be ok just calling this `Write` despite the primary method being `write_str`, thoughts @aturon?

**Comment by aturon** [comment]
@alexcrichton 

I agree, that guideline is intentionally a loose recommendation not a hard rule.

**Comment by aturon** [comment]
@alexcrichton 

Do you think it's worth going through a deprecation phase for this, or should we just rename as this PR is doing?

**Comment by alexcrichton** [comment]
I think a rename is fine, I don't think this is a widely used trait at all (unlike `fmt::Formatter` for example)

**Comment by lfairy** [comment]
@alexcrichton I suspect the reason why `WriteStr` seems odd is that `fmt::Write` isn't really a general trait for writing strings, but a restriction of `io::Write` that works better with the formatting machinery.

I don't really have an opinion on this though.

**Comment by aturon** [comment]
Hm, so we may *eventually* provide a Unicode-only "textwriter" in IO, and I suppose the name might want to match that -- but I guarantee it won't be called `Writer` or anything related to it :)

**Pull request merged**
