### PR TITLE
Fixing memory exhaustion when formatting short code suggestion 

### PR DESCRIPTION
**Pull request by ad-anssi**
Details can be found in issue #76597. This PR replaces substractions with `saturating_sub`'s to avoid usize wrapping leading to memory exhaustion when formatting short suggestion messages.

### CODE REVIEW

**Comment by lzutao** [comment]
Could you add a test in #76597 under src/test/ui with check-pass annotation ?

**Comment by ad-anssi** [comment]
Ok, I will try to add this this afternoon.

**Comment by estebank** [comment]
@birs r+

**Comment by camelid** [comment]
I think it might be good to backport this to beta so it lands in 1.47.

**Comment by Mark-Simulacrum** [comment]
Approving unilaterally for beta backport -- looks like this only affects diagnostics, is a minimal patch, and will prevent another release with memory exhaustion on a fairly easily hittable case.

cc @pnkfelix @nikomatsakis -- if you disagree, please let me know and we can back it out.

**Pull request merged**
