### PR TITLE
More deprecating of i/u suffixes in libraries

### PR DESCRIPTION
**Pull request by alfiedotwtf**

### CODE REVIEW

**Comment by alfie** [comment]
Hang on. Some of my changes didn't come though. Sigh.

Running make check and tidy now. I'll tell you when it's ready to go. Sigh again.

**Comment by alfie** [comment]
@alexcrichton 06dbde8 is good to go

**Comment by alexcrichton** [comment]
@bors: r+ 00a933f

Feel free to ping the PR when it's updated, unfortunately github doesn't send out notifications on a force push!

**Comment by alfie** [comment]
Ahh I wasn't aware of that! :) What's the best way to ping? I'm guessing just make a comment with at-<reviewer>?

**Comment by alexcrichton** [comment]
Yeah a new comment would do just fine.

**Pull request merged**
