### PR TITLE
Implement type ascription.

### PR DESCRIPTION
**Pull request by eddyb**
First iteration of type ascription in expressions. Syntax is `expr: T` with the same precedence as `as`.
Shouldn't be backwards incompatible, but I've had to modify `asm!` to not include colons in parsing.

### CODE REVIEW

**Comment by eddyb** [comment]
@SiegeLord had challenged me to this, and I will not be making a RFC myself as I've already spent more than the ten minutes I've allocated for it.
Anyone else is welcome to do so. cc @nikomatsakis

**Comment by japaric** [comment]
cc @nick29581

**Comment by nick29581** [comment]
I don't see any reason not to land this soon. But we should wait for an RFC first, I'll chat to Niko about priorities and can write one up if we decide to go for it.

**Comment by nikomatsakis** [comment]
+1

**Comment by nick29581** [comment]
RFC: https://github.com/rust-lang/rfcs/pull/803

**Comment by alexcrichton** [comment]
Closing in favor of the [associated RFC](https://github.com/rust-lang/rfcs/pull/803)

**Comment by eddyb** [comment]
@alexcrichton I don't understand - all of my changes are still necessary - is a complete RFC implementation expected in case of approval?

**Comment by huonw** [comment]
Patches for major* features like this don't land until there's more consensus about the RFC.

(*whether a feature is major or not is independent of the difficult of implementation.)

**Comment by eddyb** [comment]
Is then "in favor of" supposed to mean "pending resolution of"? That is fine with me.

**Comment by alexcrichton** [comment]
Yes sorry I'm just trying to keep the queue size down, it's fine to reopen this once the RFC is accepted.

**Comment by Ryman** [comment]
RFC was accepted, should this be reopened? cc #23416

**Comment by eddyb** [comment]
@Ryman needs a rebase and I was waiting on @nrc to merge #23630, but I guess there's nothing stopping me now, not really. Shouldn't interfere with DST work, which was my main concern.

**Comment by Ticki** [comment]
What's the state of this? The opinion about type ascription seems to be positive overall.

**Comment by jroesch** [comment]
Overall looks good, I feel like a name like ExprAscribe (or something else) would be better, it wasn't clear to me that ExprType corresponds to type ascription when reading the code. I'm happy to r+ this if no one else has an issue.

**Comment by eddyb** [comment]
@jroesch There are several newer rebase attempts.

**Comment by jroesch** [comment]
@eddyb makes sense, this is a pretty straight forward thing to implement.

**Comment by nikomatsakis** [comment]
(Note that this has now been implemented in #30184, but without the coercion aspect.)

**Pull request closed without merging**
