### PR TITLE
Teach `concat!()` to concatenate byte str literals

### PR DESCRIPTION
**Pull request by estebank**
Messed up #52838, so reopening here.

Fix #52710.

### CODE REVIEW

**Comment by estebank** [comment]
RFC for follow up at https://github.com/rust-lang/rfcs/pull/2509.

**Comment by kennytm** [comment]
Hmm [our policy](https://github.com/rust-lang/rust/pull/49387#issuecomment-403903225) is that we won't keep PRs blocked on RFCs open

**Comment by estebank** [comment]
@kennytm the RFC is proposing a superset of these changes, this PR only adds support for `concat!(b"", b'')` and _nothing_ more. I'll add put it behind a feature flag (or move it to a new `bconcat!()`) if the review either here or the RFC push in that direction.

**Comment by estebank** [comment]
Will close and await for the RFC process, since the first comment there is already to separate the functionality into its own macro, and honestly having slept on it it feels like the right approach.

**Pull request closed without merging**
