### PR TITLE
Make erase_regions_ty no_hash and remove support for anon queries

### PR DESCRIPTION
**Pull request by Zoxc**
r? @michaelwoerister

### CODE REVIEW

**Comment by Zoxc** [comment]
@rust-timer build 599cd5ebf5dc0ee3fed17b90bba8339333a72035

**Comment by Dylan-DPC** [comment]
ping from triage @michaelwoerister waiting for your review on this

**Comment by michaelwoerister** [comment]
[Trait selection](https://github.com/rust-lang/rust/blob/1edb01b7afe758dc79740e72fb8b9909402c9620/src/librustc/dep_graph/dep_node.rs#L436) still needs anonymous dep-nodes. I'd love to get rid of anonymous queries but it might be blocked on Chalk integration (or at least doing something similar). cc @rust-lang/wg-traits 

I'd be interested in the results of making `erase_regions_ty` `no_hash` but I suspect that it leads to a lot of invalidation downstream.

**Comment by Zoxc** [comment]
> [Trait selection](https://github.com/rust-lang/rust/blob/1edb01b7afe758dc79740e72fb8b9909402c9620/src/librustc/dep_graph/dep_node.rs#L436) still needs anonymous dep-nodes.

Yeah that is why I kept that and explicitly said anonymous queries. Is there any particular reason we hash the dependencies of anon nodes instead of just storing them directly? I may be looking to change that, though I'd prefer no anon nodes.

Would it be possible for trait selection to use a regular dep node by hashing the input or something like that?

**Comment by Zoxc** [comment]
> I'd be interested in the results of making `erase_regions_ty` `no_hash` but I suspect that it leads to a lot of invalidation downstream.

Given that `erase_regions_ty` is supposed to have no dependencies, it will always be marked green, so there's no downside from `no_hash`.

**Comment by michaelwoerister** [comment]
> Yeah that is why I kept that and explicitly said anonymous queries. 

It would be really helpful if you provided descriptions for your PRs. Some background information, the motivation for doing the change, things of note that are easily overlooked, potentially contentious consequences of the change, etc. 

> Given that erase_regions_ty is supposed to have no dependencies, it will always be marked green, so there's no downside from no_hash.

Hm, that's a rather subtle side-effect of how try-mark-green works but I guess it's even correct `:)` 

I'm not sure what to make of the performance results. Except for `ctfe-stress-2` instruction counts seem to regress slightly. 

> Is there any particular reason we hash the dependencies of anon nodes instead of just storing them directly?

What do you mean exactly?

> Would it be possible for trait selection to use a regular dep node by hashing the input or something like that?

I don't remember the exact reasons, @nikomatsakis took care of trait selection dep-tracking. Something in the way the caching for trait selection works made anon nodes necessary.

**Comment by Zoxc** [comment]
I forgot to include the fix from the other PR. Let's see if the serde regression goes away with that.

@bors try

**Comment by Zoxc** [comment]
> Is there any particular reason we hash the dependencies of anon nodes instead of just storing them directly?

I guess we already store the dependencies already. Maybe I was thinking of some scheme were we generate an unique dep node based on the dependencies (`[DepNodeIndex]`) which could use `FxHash` and a hash map, but I guess that wouldn't really change much.

**Comment by Zoxc** [comment]
@rust-timer build 7b167f5cc6e49e24dd310ab91c245341b26b63c1

**Comment by michaelwoerister** [comment]
Performance numbers look like a slight regression. Since we are in no rush to remove anonymous queries, I suggest we wait for a solution along the lines of #59505.

**Pull request closed without merging**
