### PR TITLE
revise Hermit's mutex interface to support the behaviour of StaticMutex

### PR DESCRIPTION
**Pull request by stlankes**
rust-lang/rust#77147 simplifies things by splitting this Mutex type into two types matching the two use cases: StaticMutex and MovableMutex. To support the new behavior of StaticMutex, we move part of the mutex implementation into libstd.

The interface to the OS changed. Consequently, I removed a few functions, which aren't longer needed.

### CODE REVIEW

**Comment by m-ou-se** [comment]
> new behavior of StaticMutex

The behaviour shouldn't have changed. I only gave it a name. Using sys::(hermit::)Mutex like this (without .init() and .destroy()), was already done by all the `Mutex`es that are not `StaticMutex`es.

Did #77147 specifically break something for you? Or was this already a problem before?

**Comment by stlankes** [comment]
I recognize the problem just after your commit. Maybe it was already their before the commit. However sometimes, StaticMutex' aren't correctly initialized.

**Comment by stlankes** [comment]
My fix to pass the format check was wrong. I fixed it and it works on my systems.

**Comment by m-ou-se** [comment]
Does `std` compile for `hermit` now? Because it looks like `type MovableMutex = Box<Mutex>;` (or `type MovableMutex = Mutex;`) is missing for this platform in `sys/hermit/mutex.rs`.

**Comment by stlankes** [comment]
My local version seems to work. After an update, std was broken. I fixed it with my latest commits

**Comment by stlankes** [comment]
The latest commit isn't related to the Mutex interface. The alloc crate provides now a new symbol `__rg_oom`. Our kernel and also Hermit's "user space" based on this crate. To avoid duplicated symbols, I moved a version to our libos.

**Comment by stlankes** [comment]
@m-ou-se When should I use `type MovableMutex = Box<Mutex>;`? If I don't used a boxed type, the kernel triggers some exceptions because a few data types aren't aligned.

**Comment by m-ou-se** [comment]
> @m-ou-se When should I use `type MovableMutex = Box<Mutex>;`?

A Box should only be used there if a `Mutex` object may not be moved (while not borrowed/used), e.g. because it might have internal pointers. Posix `pthread_mutex_t` needs it. Most `Mutex` implementations don't need it and should use `type MovableMutex = Mutex;`.

>  If I don't used a boxed type, the kernel triggers some exceptions because a few data types aren't aligned.

That sounds like a type (`Mutex`, `SpinLock`, or `PriorityQueue`?) is missing a `#[repr(align(..))]`.

**Comment by stlankes** [comment]
> That sounds like a type (`Mutex`, `SpinLock`, or `PriorityQueue`?) is missing a `#[repr(align(..))]`.

Good point, I will check it.

**Comment by stlankes** [comment]
> > That sounds like a type (`Mutex`, `SpinLock`, or `PriorityQueue`?) is missing a `#[repr(align(..))]`.
> 
> Good point, I will check it.

No, that isn't the problem.

**Comment by stlankes** [comment]
@dtolnay Do you have time to review the code?

**Comment by m-ou-se** [comment]
@bors r+

I did not review this in detail, as Hermit is a Tier 3 platform.

**Pull request merged**
