### PR TITLE
Revert PR #72389 - "Explain move errors that occur due to method calls involving `self`"

### PR DESCRIPTION
**Pull request by Aaron1011**
reverts #72389 

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
Thanks!
@bors r+ p=1

**Comment by RalfJung** [comment]
(Would be nice when revert PR descriptions contain at least a link to where the explanation is for why a revert is needed.)

**Comment by Manishearth** [comment]
@bors p=5

This is blocking a whole chain of intra doc link fixes and stabilization

**Comment by Manishearth** [comment]
My bad, this is blocking clippy test syncs, a different problem that is also high priority as right now clippy tests aren't being CId :smile:

**Comment by Manishearth** [comment]
So it's failing to compile the proc macro aux file. Unclear why. Feel free to temporarily remove the test and land this while we figure it out.

I was unable to get that failure to happen locally with an RTIM-rustc, might try full build tomorrow

**Comment by flip1995** [comment]
@Manishearth I'm able to reproduce the UI-test failure with `./x.py test src/tools/clippy`. I haven't had time to look into this yet though.

**Comment by Aaron1011** [comment]
Build error: https://gist.github.com/Aaron1011/479c460250ed9ead4e0e6631a2535071

**Comment by Aaron1011** [comment]
@Manishearth @flip1995: I found the cause of the error - we had multiple versions of `syn` in the build directory that Clippy manually searched. we were non-deterministically picking the first one we encountered when iterating over the filesystem, which lead to the build error I posted above.

This should be ready to merge.

**Comment by nnethercote** [comment]
This was a [perf win](https://github.com/rust-lang/rust/compare/6bb3dbfc6c6d8992d08431f320ba296a0c2f7498...cbf356a1a5677b1c073f09ba833d8247c7ed01aa) of up to 3.1% on a few benchmarks.

**Pull request merged**
