### PR TITLE
tests/assembly/asm: Remove uses of rustc_attrs and lang_items features by using minicore

### PR DESCRIPTION
**Pull request by taiki-e**
Similar to https://github.com/rust-lang/rust/pull/134385 (for tests/ui/asm), but for tests/assembly/asm.

r? jieyouxu

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Nice cleanup, thanks! r=me once PR CI is green.

**Comment by jieyouxu** [comment]
I'll take a look at the failures tmrw unless u know how to fix them already

**Comment by taiki-e** [comment]
It seems that failures are due to `--crate-type cdylib` passed in these tests:
https://github.com/rust-lang/rust/blob/e20646cff50e8beaf552cf43cec6f488d7ce4c97/tests/assembly/asm/nvptx-types.rs#L4
https://github.com/rust-lang/rust/blob/e20646cff50e8beaf552cf43cec6f488d7ce4c97/tests/assembly/asm/wasm-types.rs#L4

Removed that flag and changed to use `#![crate_type = "rlib"]` as with other `assembly/asm/*-types.rs` tests.
https://github.com/rust-lang/rust/blob/e20646cff50e8beaf552cf43cec6f488d7ce4c97/tests/assembly/asm/aarch64-types.rs#L11

**Comment by jieyouxu** [comment]
I'm curious why cdylib was used previously, I'll take a closer look tmrw.

**Comment by jieyouxu** [comment]
My git archeology:

- I do not see why the `nvptx-types` test need cdylib specifically. I checked the original PR #72439 and there was no elaboration. To me, this indicates we can change the crate type. If there's some kind of `cdylib`-specific behavior that this test wanted to check, it's not doing that because the test doesn't seem to be failing here on PR CI.
- I do not see why the `wasm-types` test need cdylib specifically. I checked #78684, no mention of the `cdylib` crate-type being specifically required. If it was, this test isn't checking that either.

So, if these two test changes turn out to be undesirable, then we better be documenting the reason for `cdylib` being load-bearing specifically anyway.

Thanks for the cleanup, this looks good to go for me.
@bors r+ rollup

**Pull request merged**
