### PR TITLE
Update clippy

### PR DESCRIPTION
**Pull request by Manishearth**
Unbreaks it

https://github.com/rust-lang-nursery/rust-clippy/pull/2289

### CODE REVIEW

**Comment by oli-obk** [comment]
You need to run x.py to update the Cargo.lock

**Comment by Manishearth** [comment]
pushed

**Comment by kennytm** [comment]
@Manishearth Would you mind reviving this (rebase on rust master + update clippy to latest master)? Clippy (and miri as well) needs to be test-pass before branching off to the next beta.

**Comment by kennytm** [comment]
@oli-obk it is tested in the same manner as RLS and rustfmt.

Anyway, this is unblocked on 1.24-beta by not testing them.

**Comment by kennytm** [comment]
Superseded by #47172.

**Pull request closed without merging**
