### PR TITLE
Update tracing to 0.1.25

### PR DESCRIPTION
**Pull request by tmiasko**
* Update tracing from 0.1.18 to 0.1.25
* Update tracing-subscriber from 0.2.13 to 0.2.16
* Update tracing-tree from 0.1.6 to 0.1.8
* Add pin-project-lite to the list of allowed dependencies (it is now a direct dependency of tracing).

### CODE REVIEW

**Comment by tmiasko** [comment]
Added pin-project-lite, which is now a direct dependency of tracing, to the list of allowed dependencies

**Comment by Mark-Simulacrum** [comment]
Could you provide a link to the changelogs and some particular rationale for this update (beyond just keeping things up to date)?

**Comment by tmiasko** [comment]
The release notes can be found at:

* https://github.com/tokio-rs/tracing/releases
* https://github.com/davidbarsky/tracing-tree/releases

I was originally motivated by slight reduction in a code generated for statically disabled instrumentation, although I don't see it explicitly mentioned in release notes for that version. The rest is indeed just to keep things up-to date.

@rustbot label: +S-waiting-on-review

**Comment by Mark-Simulacrum** [comment]
I've done the digging now, but it would've been great to provide the changelog in a more directed fashion - e.g., links to each release - if the upstream crate doesn't maintain a changelog file.

@bors try @rust-timer queue

**Comment by Mark-Simulacrum** [comment]
Seems to be a mild improvement overall, though potentially a regression in compile times (hard to say if noise or not). @bors r+

**Pull request merged**
