### PR TITLE
Refactor versions detection in build-manifest

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR refactors how `build-manifest` handles versions, making the following changes:

* `build-manifest` now detects the "package releases" on its own, without relying on rustbuild providing them through CLI arguments. This drastically simplifies calling the tool outside of `x.py`, and will allow to ship the prebuilt tool in a tarball in the future, with the goal of stopping to invoke `x.py` during `promote-release`.
* The `tar` command is not used to extract the version and the git hash from tarballs anymore. The `flate2` and `tar` crates are used instead. This makes detecting those pieces of data way faster, as the archive is decompressed just once and we stop parsing the archive once all the information is retrieved.
* The code to extract the version and the git hash now stores all the collected data dynamically, without requiring to add new fields to the `Builder` struct every time.

I tested the changes locally and it should behave the same as before.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, so we can just merge this, but I'm thinking it would be good to @bors try and try to release a dev-static nightly with it just to test that it works on RCS as well. Unfortunately our CI here doesn't run build manifest in any capacity :/

**Comment by pietroalbini** [comment]
Kicked off promotion.

**Comment by pietroalbini** [comment]
Promotion ended, it seems to work?

**Comment by pietroalbini** [comment]
@bors r-

Wait, there is actually a bug, this does not find the `rust-src` component.

**Comment by pietroalbini** [comment]
Addressed.

**Pull request merged**
