### PR TITLE
`#[inline(required)]`

### PR DESCRIPTION
**Pull request by davidtwco**
See rust-lang/rfcs#3711.

### CODE REVIEW

**Comment by davidtwco** [comment]
CI failure isn't related to this PR - see [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/ci.20failure.20toomanyrequests.3A.20You.20have.20reached.20your.20pull.20rate/near/476808827)

**Comment by lqd** [comment]
It's not fully baked yet but there were also some cute explorations around `#[inline(usually)]` in https://github.com/rust-lang/rust/pull/130679 which may be interesting to you.

**Review by compiler-errors — COMMENTED** [review]
It seems suspicious to use the MIR inliner to validate whether a function could be inlined, because the code may still be too polymorphic to determine if inlining is required or not. I'm tempted to believe that this code doesn't do the right thing:

```
trait Foo {
    fn method();
}

impl Foo for () {
    #[inline(required)]
    fn method() {
    }
}

fn poly<T: Foo>() {
    T::method();
}

fn main() {
    poly::<()>();
}
```

**Comment by davidtwco** [comment]
> It seems suspicious to use the MIR inliner to validate whether a function could be inlined, because the code may still be too polymorphic to determine if inlining is required or not. I'm tempted to believe that this code doesn't do the right thing:
> 
> 
> 
> ```
> 
> trait Foo {
> 
>     fn method();
> 
> }
> 
> 
> 
> impl Foo for () {
> 
>     #[inline(required)]
> 
>     fn method() {
> 
>     }
> 
> }
> 
> 
> 
> fn poly<T: Foo>() {
> 
>     T::method();
> 
> }
> 
> 
> 
> fn main() {
> 
>     poly::<()>();
> 
> }
> 
> ```

Thanks for taking a look at this. After thinking about it some more and discussions on the RFC, I don't think this is the right approach, and will experiment with some alternative ideas :)

**Pull request closed without merging**
