### PR TITLE
Stabilize `nonzero_min_max`

### LINKED ISSUE #89065: Add `NonZero{I,U}{8,16,32,64,128,size}::{MIN,MAX}`
Currently, there is no way to obtain a `NonZero*` value without introducing unsafe codes or `unwrap()` calls, providing these constants can make it easier to use these types. For example:

```rust
use std::num::NonZeroU64;

fn foo(x: u64) -> NonZeroU64 {
    x.checked_add(1).and_then(NonZeroU64::new).unwrap_or(NonZeroU64::MAX)
}
```

### PR DESCRIPTION
**Pull request by c410-f3r**
## Overall

Stabilizes `nonzero_min_max` to allow the "infallible" construction of ordinary minimum and maximum `NonZero*` instances.

The feature is fairly straightforward and already matured for some time in stable toolchains.

```rust
let _ = NonZeroU8::MIN;
let _ = NonZeroI32::MAX;
```

## History

* On 2022-01-25, implementation was [created](https://github.com/rust-lang/rust/pull/93293).

## Considerations

* This report is fruit of the inanition observed after two unsuccessful attempts at getting feedback.
* Other constant variants discussed at https://github.com/rust-lang/rust/issues/89065#issuecomment-923238190 are orthogonal to this feature.

Fixes https://github.com/rust-lang/rust/issues/89065

### CODE REVIEW

**Comment by cuviper** [comment]
r? libs-api

**Comment by c410-f3r** [comment]
In face of the discussion at https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/slow.20reviewing.20times arguing what would be a reasonable amount of waiting time and also because https://github.com/rust-lang/rust/pull/75644 took **ONE** year to be reviewed, I will try to roll the dices again. Feel free to revert any modification if desired.

r? libs-api

**Review by dtolnay — COMMENTED** [review]
Waiting on FCP in https://github.com/rust-lang/rust/issues/89065#issuecomment-1400885610.

**Comment by c410-f3r** [comment]
Thanks

**Comment by dtolnay** [comment]
Triage: still waiting on FCP.

**Review by dtolnay — APPROVED** [review]

**Pull request merged**
