### PR TITLE
Let-else: break out scopes when a let-else pattern fails to match

### LINKED ISSUE #93951: `let_else` returns in surprising borrowck errors with impl trait
```rust
#![feature(let_else)]
use std::fmt::Debug;

fn foo<'a>(x: &'a str) -> Result<impl Debug + 'a, ()> {
    Ok(x)
}

fn fail() {
    let x = String::from("Hey");

    let Ok(s) = foo(&x) else { return };
}

fn ok() {
    let x = String::from("Hey");

    let s = if let Ok(s) = foo(&x) { s } else { return };
}
```
results in
```
error[E0597]: `x` does not live long enough
  --> src/main.rs:11:21
   |
11 |     let Ok(s) = foo(&x) else { return };
   |                 ----^^-
   |                 |   |
   |                 |   borrowed value does not live long enough
   |                 a temporary with access to the borrow is created here ...
12 | }
   | -
   | |
   | `x` dropped here while still borrowed
   | ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `Result<impl Debug, ()>`
   |
help: consider adding semicolon after the expression so its temporaries are dropped sooner, before the local variables declared by the block are dropped
   |
11 |     let Ok(s) = foo(&x) else { return };;
   |                                        +
   ```
I am not sure if this issue exists only in combination with impl Trait of if it can be triggered in some other ways as well, haven't managed to get this bug some other way.

cc #93628 @est31 do you know whether this behavior is known already?

### LINKED ISSUE #98672: Let-else does not drop temporaries at the end of the statement
This bug has already been identified but I wanted to open an issue for it.

The following code should print `I've been dropped` first. ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=95717efda964f173b2bb06d347148d44))

```rust
#![feature(let_else)]

#[derive(Default)]
struct Droppy { inner: u32 }

impl Drop for Droppy {
    fn drop(&mut self) {
        println!("I've been dropped");
    }
}

fn main() {
    let 0 = Droppy::default().inner else { return };
    println!("Should have dropped 👆");
}
```

I believe there is an unanswered question: Should temporaries be dropped *before* the `else` block?

```rust
    let 1 = Droppy::default().inner else {
        println!("Should have dropped?????");
        return;
    };
```

@nikomatsakis said this issue is being investigated at https://github.com/rust-lang/rust/pull/93628#issuecomment-1125066530.

This issue has been assigned to @dingxiangfei2009 via [this comment](https://github.com/rust-lang/rust/issues/98672#issuecomment-1170031469).

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
This PR will commit to a new behavior so that values from initializer expressions are dropped earlier when a let-else pattern fails to match.

Fix #98672.
Close #93951.
cc @camsteffen @est31

### CODE REVIEW

**Comment by lcnr** [comment]
i expect this to also cause some programs to stop compiling because temporaries are now dropped earlier? :thinking:

reassigning as I don't have a lot of time during the next few weeks

r? rust-lang/compiler

**Comment by est31** [comment]
@lcnr I think this change is doing the opposite: the set of programs that the compiler accepts **a**fter this change A is a strict superset of the programs **b**efore B. (Let's just not look at const eval for now).

You see B \ A = ∅ as any program that now fails at compile time would have needed to access temporaries from the `else` block. But there is no way to do that.

You see A \ B ≠ ∅ as now programs compile that access resources in the `else` block that were used by the temporaries. E.g. references to common variables. Example program that now compiles thanks to the PR (@dingxiangfei2009 feel free to integrate it as test):

```Rust
#![feature(let_else)]

struct Foo<'a>(&'a mut u32);

impl<'a> Drop for Foo<'a> {
    fn drop(&mut self) {
        *self.0 = 0;
    }
}

fn main() {
    let mut foo = 0;
    let Foo(0) = Foo(&mut foo) else {
        *&mut foo = 1;
        todo!()
    };
}
```

This change still might break programs at *runtime*, but the PR already has a runtime test.

**Comment by compiler-errors** [comment]
I'm not the best person to review this.

r? compiler

**Pull request merged**
