### PR TITLE
Introduce assembly tests suite

### PR DESCRIPTION
**Pull request by denzp**
The change introduces a new test suite - **Assembly** tests. The motivation behind this is an ability to perform end-to-end codegen testing with LLVM backend. Turned out, NVPTX backend sometimes missing common Rust features (`i128` and libcalls in the past, and still full atomics support) due to different reasons.

Prior to this change, basic NVPTX assembly tests were implemented within `run-make` suite. Now, it's easier to write additional and maintain existing tests for the target.

cc @gnzlbg @peterhj 
cc @eddyb I adjusted mangling scheme expectation, so there is no need to change the tests for #57967

### CODE REVIEW

**Comment by gnzlbg** [comment]
The only thing that worries me a bit is that updating LLVM might require updating many tests, but I guess that's also kind of the point.

In any case this looks much better than `run-make` and is pretty much what LLVM does anyways. As long as we add new assembly tests wisely, the direction of this PR LGTM.

**Comment by alexcrichton** [comment]
This looks good to me, thanks @denzp! 

I agree with @gnzlbg that these could be tricky to update over time, but we've already got codegen tests which need updates periodically, so I don't think that these are any worse off than those.

@bors: r+

**Comment by denzp** [comment]
Very likely, having more and more "precise" tests to verify only smaller and basic parts would minimise the chance that backend changes do much damage. Let's hope so and write the cases wisely :slightly_smiling_face:

**Comment by mark-i-m** [comment]
@denzp Could you also document this in the Testing chapter of the rustc-guide please?

**Comment by denzp** [comment]
I've solved conflicts and opened a PR in the rustc-guide: https://github.com/rust-lang/rustc-guide/pull/289

**Comment by alexcrichton** [comment]
cc @jackpot51 it looks like the redox apt servers may be down? We're getting this on CI:

```
[00:10:58] [91mW: The repository 'https://static.redox-os.org/toolchain/apt  Release' does not have a Release file.
[00:10:58] E: Failed to fetch https://static.redox-os.org/toolchain/apt/Packages  404  Not Found
[00:10:58] E: Some index files failed to download. They have been ignored, or old ones used instead.
[00:10:58] The command '/bin/sh -c ./install-x86_64-redox.sh' returned a non-zero code: 100
[00:11:02] [0mCommand failed. Attempt 5/5:
```

Do you know if this could be fixed in the near future? If not no worries! We'll just need to disable the redox targets in nightly until it's fixed

**Comment by lzutao** [comment]
cc #59257

**Comment by alexcrichton** [comment]
Oh oops, thanks for the reference @lzutao! 

In that case @denzp if you want to remove the redox target from the dist-various-1 container I think that's fine. We can then sort out the merge conflict if either this or https://github.com/rust-lang/rust/pull/59257 lands first.

**Comment by denzp** [comment]
@alexcrichton it's okay to wait with this PR until #59257 is merged. I guess it should happend pretty soon, because there is a rollup going on #59298.

**Comment by lzutao** [comment]
#59257 is merged. Could this PR be unlocked?

**Pull request merged**
