### PR TITLE
Fix a typo “pararmeter” in error message

### PR DESCRIPTION
**Pull request by steffahn**
Issue reported on IRLO: https://internals.rust-lang.org/t/fixing-a-typo/17427

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]

**Comment by steffahn** [comment]
IMO Such a typo in error messages seems kinda embarrassing. Is it too unusual to beta-backport such a fix? I mean it's a "regression" in that a typo-free error message got (a new part containing) a typo added.

**Comment by estebank** [comment]
@steffahn in t-compiler we tend to gauge three things: how likely someone is to see the problem, how disastrous the problem is, and how complex the solution being backported would be. I'd be comfortable backporting.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-09-29/near/301451609)

@rustbot label +beta-accepted

**Pull request merged**
