### PR TITLE
Use hints with getaddrinfo() in std::net::lookup_host()

### PR DESCRIPTION
**Pull request by inejge**
As noted in #24250, `std::net::lookup_host()` repeats each IPv[46] address in the result set. The number of repetitions is OS-dependent; e.g., Linux and FreeBSD give three copies, OpenBSD gives two. Filtering the duplicates can be done by the user if `lookup_host()` is used explicitly, but not with functions like `TcpStream::connect()`. What happens with the latter is that any unsuccessful connection attempt will be repeated as many times as there are duplicates of the address.

The program:

``` rust
use std::net::TcpStream;

fn main() {
    let _stream = TcpStream::connect("localhost:4444").unwrap();
}
```

results in the following capture:

[capture-before.txt](https://github.com/rust-lang/rust/files/352004/capture-before.txt)

assuming that "localhost" resolves both to ::1 and 127.0.0.1, and that the listening program opens just an IPv4 socket (e.g., `nc -l 127.0.0.1 4444`.) The reason for this behavior is explained in [this comment](https://github.com/rust-lang/rust/issues/24250#issuecomment-92240152): `getaddrinfo()` is not constrained.

Various OSS projects (I checked out Postfix, OpenLDAP, Apache HTTPD and BIND) which use `getaddrinfo()` generally constrain the result set by using a non-NULL `hints` parameter and setting at least `ai_socktype` to `SOCK_STREAM`. `SOCK_DGRAM` would also work. Other parameters are unnecessary for pure name resolution.

The patch in this PR initializes a `hints` struct and passes it to `getaddrinfo()`, which eliminates the duplicates. The same test program as above with this change produces:

[capture-after.txt](https://github.com/rust-lang/rust/files/352042/capture-after.txt)

All `libstd` tests pass with this patch.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 0314d179aa07905cc3bd4ec3206be28ff11696f9

Thanks!

cc @rust-lang/libs, seems fine to me but worth ensuring others see as well

**Comment by alexcrichton** [comment]
Ah right, another thing, would it be possible to add a test for this as well?

**Comment by inejge** [comment]
I've added a test for (lack of) duplicates. It tries to resolve "localhost", which should exist on any reasonable system. The complication of counting the number of instances of each returned addres type, then asserting that no type has more than one instance, instead of just checking that `lookup_host()` returned exactly two addresses, exists because of the behavior of `getaddrinfo()` on OpenBSD, which, in my testing, returns just the IPv4 addresses if `ai_family` is unspecified.

**Comment by inejge** [comment]
#24250 can be closed now, I think?

**Comment by alexcrichton** [comment]
Indeed, thanks!

**Pull request merged**
