### PR TITLE
Update mingw-w64 + GNU toolchain

### LINKED ISSUE #112368: GNU linker warns “corrupt .drectve” on staticlib binary generated with Rust 1.70 on Windows
It seems, as of version 16, LLVM generates a binary containing incompatible directive with GNU linker. I believe this is the cause:

commit: https://github.com/llvm/llvm-project/commit/c5b3de6745c37dd991430b9b88ff97c35b6fc455

Since Rust 1.70 upgraded LLVM to version 16,  we started to see a lot of warnings by GNU linker when I link against staticlibs compiled by Rust. The warnings are like this:

```
Warning: .drectve `-exclude-symbols:_ZN7testpkg11hello_world17ha68eef8a416aa303E ' unrecognized
Warning: corrupt .drectve at end of def file
```

It seems I can just ignore this warning (while the concern described in [the LLVM's commit](https://github.com/llvm/llvm-project/commit/c5b3de6745c37dd991430b9b88ff97c35b6fc455) can be a real problem in future), but still I feel this is something that should be fixed if possible. I know, from LLVM's viewpoint, it's reasonable to assume the linker is lld and embed the directives that only lld can understand. But, on the other hand, from Rust's viewpoint, is it intentional that the "GNU" target produces a binary that is incompatible with "GNU" linker? I'm honestly not sure about the answer. I'm yet to figure out what the "GNU" in Rust's GNU toolchain/target actually means.

### Code

A minimal reproducible code: https://github.com/yutannihilation/rust170_gnu_warning

```sh
# compile Rust code to create a staticlib
cargo build --target=x86_64-pc-windows-gnu --lib --release

# compile the C code
gcc -c main.c -o main.o

# link to the staticlib
gcc -o testpkgrust170_gnu_warning.dll main.o -L./target/x86_64-pc-windows-gnu/release -lrust170_gnu_warning -lws2_32 -ladvapi32 -luserenv -lbcrypt -lntdll 
```

In case of Rust 1.69, we don't see any warnings. However, if it's compiled using Rust 1.70, GNU linker warns:

```
Warning: corrupt .drectve at end of def file
Warning: corrupt .drectve at end of def file
```
(This can be reproducible on GHA: [result](https://github.com/yutannihilation/rust170_gnu_warning/actions/runs/5182955142/jobs/9340288940#step:4:13))

### Version it worked on

It most recently worked on: Rust 1.69

### Version with regression

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-pc-windows-msvc
release: 1.70.0
LLVM version: 16.0.2
```

### References

* the original context: https://github.com/extendr/rextendr/pull/285#issuecomment-1576987501
* post on the Rust user forum before reporting here: https://users.rust-lang.org/t/corrupt-drectve-warning-on-x86-64-pc-windows-gnu-target-with-rust-1-70/94912

### PR DESCRIPTION
**Pull request by mati865**
The list of packaged tools and their versions is available at: https://github.com/niXman/mingw-builds-binaries/releases/tag/14.1.0-rt_v12-rev0

Fixes: https://github.com/rust-lang/rust/issues/112368

### CODE REVIEW

**Comment by mati865** [comment]
Can I get `@bors try` please?

**Comment by mati865** [comment]
Should be good for another go, added redirection follow argument, the download will hopefully work now.
Dunno if zstd is present, so enabled it's stdout just in case.

**Comment by mati865** [comment]
Crosstool creates even more messed up toolchain structure than I though, let's see with this release.

**Comment by mati865** [comment]
Manged to build and run tests locally with x86_64 after few more fixes but stdlib's mspc tests fail in a weird way so let's see the CI.

**Comment by mati865** [comment]
Could somebody run try build out delegate me?

**Comment by mati865** [comment]
Dunno how it didn't manifest locally, can we try again with a new version?

**Comment by mati865** [comment]
Apparently crosstool placed static libstdc++ library inside `{triple}/sysroot/lib` instead of typical `lib/gcc/{triple}/{gcc_version}` which breaks `-print-file-name=libstdc++.a` used by bootstrap to find library location:
```
$ /d/x86_64-w64-mingw32/bin/gcc.exe -print-file-name="libstdc++.a"
libstdc++.a

$ /d/x86_64-w64-mingw32/bin/gcc.exe -print-file-name="something_that_doesnt_exist.nope"
something_that_doesnt_exist.nope

$ /d/x86_64-w64-mingw32/bin/gcc.exe -print-file-name="libstdc++.a"
D:/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/libstdc++.a
```
What's fun (not really) the compiler itself works fine and can link c++ code dynamically and statically, it's only this option that doesn't work...

With skip of empty library dir it made it to the tests but broken backtrace doesn't seem inspiring:
```
2024-01-06T20:45:23.8238695Z ------stderr------------------------------
2024-01-06T20:45:23.8239209Z thread 'main' panicked at C:\a\rust\rust\tests\ui\panics\runtime-switch.rs:26:5:
2024-01-06T20:45:23.8239712Z explicit panic
2024-01-06T20:45:23.8239937Z stack backtrace:
2024-01-06T20:45:23.8240368Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2024-01-06T20:45:23.8240791Z 
2024-01-06T20:45:23.8240894Z ------------------------------------------
2024-01-06T20:45:23.8241205Z $DIR\runtime-switch.rs
2024-01-06T20:45:23.8241450Z diff of run.stderr:
2024-01-06T20:45:23.8241603Z 
2024-01-06T20:45:23.8241790Z 1	thread 'main' panicked at $DIR/runtime-switch.rs:26:5:
2024-01-06T20:45:23.8242176Z 2	explicit panic
2024-01-06T20:45:23.8242399Z 3	stack backtrace:
2024-01-06T20:45:23.8242707Z -	   0: std::panicking::begin_panic
2024-01-06T20:45:23.8243017Z -	   1: runtime_switch::main
2024-01-06T20:45:23.8243506Z 6	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2024-01-06T20:45:23.8243998Z 7	
2024-01-06T20:45:23.8244108Z 
2024-01-06T20:45:23.8244114Z 
2024-01-06T20:45:23.8244312Z The actual run.stderr differed from the expected run.stderr.
2024-01-06T20:45:23.8245201Z Actual run.stderr saved to C:\a\rust\rust\build\i686-pc-windows-gnu\test\ui\panics\runtime-switch.legacy\runtime-switch.legacy.run.stderr
2024-01-06T20:45:23.8245877Z 
2024-01-06T20:45:23.8247135Z error in revision `legacy`: 1 errors occurred comparing run output.
```
Gonna check x86_64 build.

**Comment by mati865** [comment]
Apparently neither GDB i686 not x86_64 can run binaries...
Interesting host triple:
`This GDB was configured as "--host=i686-host_w64-mingw32 --target=i686-w64-mingw32"`

**Comment by Dylan-DPC** [comment]
@mati865 any updates on this? does this still need to be marked as draft? thanks

**Comment by mati865** [comment]
I hope to return to this PR this month, but I need to prepare and test tarballs first.

**Comment by mati865** [comment]
Locally both this and toolchains fail with an error:
```
  = note: D:/tmp/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/tmp/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o:crtexe.c:(.text+0x73): undefined reference to `__set_app_type'
          D:/tmp/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/tmp/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o:crtexe.c:(.text+0xb6): undefined reference to `__set_app_type'
          collect2.exe: error: ld returned 1 exit status
```
Hopefully CI has more luck, can someone run try build?

**Comment by jyn514** [comment]
> Hopefully CI has more luck, can someone run try build?

try builds don't actually run tests, but you can change windows to run in PR CI temporarily https://rustc-dev-guide.rust-lang.org/tests/ci.html#modifying-ci-jobs

**Comment by ChrisDenton** [comment]
There's a new try-job thing that can run arbitrary jobs https://rustc-dev-guide.rust-lang.org/tests/ci.html#try-builds

@bors try

**Comment by jyn514** [comment]
fyi `x86_64-mingw` succeeded on https://github.com/rust-lang/rust/pull/119286 :) i didn't run the other three tests but seems a good sign we're getting close.

**Comment by jieyouxu** [comment]
@mati865 to make your life easier with try jobs
@bors delegate+ (for try jobs, need review approval for merge)

**Comment by jieyouxu** [comment]
Also thank you for working on this, anything that helps to make our windows CI jobs less cursed is great 💚

**Comment by mati865** [comment]
Thanks!

@bors try

**Comment by mati865** [comment]
@bors try

Nulls in debuginfo tests are concerning, but first lest see if the compiler works at all.

**Comment by mati865** [comment]
Without https://github.com/rust-lang/rust/pull/119286, testing this was slightly inconvenient but I made sure the right linkers are called using `PATH=~/.cargo/bin cargo +47e7e98d8de97f599da6c2db2c3f31c6054f6114 rustc -- -C link-arg=-v -C link-arg=--some-bad-flag` (tested with shipped and MSYS2 linkers). And some simple executables work fine both with shipped and external linkers.

So far so good. Beta will be branched on 30.08, so it should be good to go after that date.

@rustbot ready

**Comment by mati865** [comment]
Oh, I almost forgot. Someone from infra needs to place respective archives from https://github.com/niXman/mingw-builds-binaries/releases/tag/14.1.0-rt_v12-rev0 to Rust's mirror.

**Comment by mati865** [comment]
Rebased due to https://github.com/rust-lang/rust/pull/129672 merge, let’s see if that test really works this time. Also updated other skipped tests to refer to an older issue.

@bors try

**Comment by jieyouxu** [comment]
wait wtf im so sorry, this is not the msvc ci pr 😭

**Comment by mati865** [comment]
No, worries. Maybe it will cancel if I close and reopen the PR?

**Comment by Kobzol** [comment]
@jieyouxu or @ChrisDenton Does any of you want to review this? I'm not very knowledgeable about Windows stuff.

**Comment by jieyouxu** [comment]
I'm inclined to say that if the tests work (for whatever thats worth), then we should bump the mingw toolchain. I see that this would bump gcc and gdb (among other things). The debug info tests are borked anyways so that seems fine.

**Comment by jieyouxu** [comment]
cc @petrochenkov in case you happen to know something that indicates we shouldn't bump yet.

**Comment by mati865** [comment]
Let's wait for Vadim, otherwise the sooner it's merged, the more time there will be to catch regressions before beta.

**Comment by GuillaumeGomez** [comment]
I wonder if this the one which failed in https://github.com/rust-lang/rust/pull/130027...

**Comment by ChrisDenton** [comment]
That would seem very unlikely considering it's msvc that failed.

**Comment by workingjubilee** [comment]
It's not about you, it's about Windows.

@bors rollup=iffy

**Pull request merged**
