### PR TITLE
Use futex based thread parker on Fuchsia.

### PR DESCRIPTION
**Pull request by m-ou-se**

### CODE REVIEW

**Comment by m-ou-se** [comment]
This is comletely untested! @tmandry I believe you're the person I should contact for Fuchsia? Can you test this?

**Comment by JohnCSimon** [comment]
Triage: 
Seems that there's still work to be done on this one. 
@rustbot author

**Comment by tmandry** [comment]
Sorry that this got lost before. We actually would like to [avoid](https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=88603) using raw futexes on Fuchsia because it loses priority inheritance information. There are a few options:

* Use the C11 mutex API available in libc.
  * Fuchsia has a const-constructible [extension](https://cs.opensource.google/fuchsia/fuchsia/+/main:zircon/third_party/ulib/musl/include/threads.h;l=44;drc=7c5e521391fddb98fd8f6970da7c410899ddf5cf) to this API. (It's an int, you set it to zero.)
  * We would hard code knowledge of the layout and const construction for Fuchsia in std or the libc crate.
* Use primitives in [libsync](https://cs.opensource.google/fuchsia/fuchsia/+/main:zircon/system/ulib/sync/include/lib/sync/mutex.h;drc=a70d5d99bcd43f84a73ff83d96987674d56abc9f), a Fuchsia-specific library. The libc API is a thin wrapper around this one.
  * Benefit is that libsync, _unlike_ libc, is distributed as a static lib in the Fuchsia SDK and we can possibly get better performance.
  * Drawback is adding another library dependency of std.
  * Hard coding just as much as above.
* Use [Fuchsia-specific extensions](https://fuchsia.dev/fuchsia-src/reference/kernel_objects/futex?hl=en#ownership_and_priority_inheritance) to futexes
  * This could allow us to reuse the futex implementation, but requires keeping track of the thread[s] being waited on. I'm not sure how easy that would be.

**Comment by tmandry** [comment]
I had thought that const constructible Mutex was blocked behind this, but was surprised to see that it [landed](https://github.com/rust-lang/rust/pull/97791) yesterday. That's great, but how is it working with Fuchsia?

By the way, the tracking issue https://github.com/rust-lang/rust/issues/93740 states that Fuchsia is a Tier 3 target but it is Tier 2.

**Comment by m-ou-se** [comment]
Updated. @tmandry can you test it?

**Comment by tmandry** [comment]
I managed to get the std::thread tests running, and they pass. If there are deeper problems, we'll probably find out soon after this lands when we try to bring the new compiler into Fuchsia :)

Thanks for working on this!

@bors r+

**Pull request merged**
