### PR TITLE
remove unused static data for to_lowercase

### PR DESCRIPTION
**Pull request by PSeitz**
remove a ton of unused empty strings in `char::to_lowercase`. The last column in the lower case table is completely unused. I noticed this table when analyzing code bloat when compiling to wasm. using to_lowercase increased the binary size from 50kb to 75kb (which is mostly consisting of empty entries '\u{0}').

Removing the last column is an obvious solution, two others could be done too.
1. The second column has only one entry. Remove that column and create a special handling for that.
2. Group consecutive chars with the same conversion distance.

This changes only internals, public API behavior is unchanged (except probably faster).

### CODE REVIEW

**Review by eggyal — CHANGES_REQUESTED** [review]
https://github.com/rust-lang/rust/blob/47e3bd4d7e9c5bf384373b2c9a6a934cd5723e75/library/core/src/unicode/unicode_data.rs#L1

You'll need to modify the table generator tool rather than manually adjusting this file.

**Comment by JohnCSimon** [comment]
@PSeitz 

ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by PSeitz** [comment]
@JohnCSimon I need to edit the table generator instead of the resulting file. I didn't have time yet to do that

**Comment by Dylan-DPC** [comment]
@PSeitz any updates on this?

**Comment by PSeitz** [comment]
@Dylan-DPC It's still on my list, but I didn't have the time yet

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

**Pull request closed without merging**
