### PR TITLE
Warn unused trait imports

### LINKED ISSUE #25730: Unused import of trait is not warned about if similar trait is defined and used inside the crate
If I import a trait from an external crate into my crate and not use it, the compiler warns me about the unused import. But if I have a trait inside my crate with the same method and implement it, the compiler does not emit a warning about the unused trait from outside.

Let's say I have this trait in its own library crate:
```rust
// library crate 'testtrait'
pub trait OutsideTrait {
    fn method(&self) -> String;
}
```
In my executable crate I have the following code:
```rust
// executable crate
extern crate testtrait;

use testtrait::OutsideTrait;

trait InsideTrait {
    fn function(&self) -> String;
}

#[derive(Debug)]
struct Foo;

impl InsideTrait for Foo {
    fn function(&self) -> String {
        format!("{:?}", *self)
    }
}

fn main() {
    let b = Foo;
    println!("{}", b.function());
}
```
Now the compiler warns me about the unused import `testtrait::OutsideTrait`
However, if I change the name of `method` to `function` in order to make `OutsideTrait` match `InsideTrait`, the compiler will **not** warn me about the unused import of `testtrait::OutsideTrait`.
```rust
pub trait OutsideTrait {
    fn function(&self) -> String;
}
```
This happens regardless of whether I add an additional parameter to the function in `OutsideTrait` or `InsideTrait`.
Note, that if I implement neither trait, the compiler will again warn me about the unused import of `OutsideTrait`, which is totally fine.

The warning is not emitted by the compiler but the issue is still valid. `OutsideTrait` is an unused import and should be reported as such.

### PR DESCRIPTION
**Pull request by sanxiyn**
Fix #25730.

### CODE REVIEW

**Comment by arielb1** [comment]
Sorry for the delay.

Why is the unused import lint inside `rustc_typeck` rather than `rustc_lint`? Also, I would prefer to have a single hashset of used trait imports, rather than 2.

**Comment by sanxiyn** [comment]
`unused_imports` is one of `HardwiredLints`, so it can't be inside `rustc_lint`.

Two sets are basically a set of trait imports and a set of used trait imports, not two sets of used trait imports. `maybe_unused_trait_imports` is a set of trait imports (minus those used by name) saved for use post-resolution.

**Comment by alexcrichton** [comment]
(ping)

Does this just need a rebase? A re-review?

(just trying to clear out the queue)

**Comment by alexcrichton** [comment]
Closing due to inactivity, but feel free to resubmit with a rebase!

**Pull request closed without merging**
