### PR TITLE
Fix typo on Windows path separators

### PR DESCRIPTION
**Pull request by tesuji**
r? @jonas-schievink

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Huh, I didn't know you need to escape `\` in code blocks. You don't have to do that on GitHub.

@bors r+ rollup

**Comment by ehuss** [comment]
This is a known bug (see https://github.com/raphlinus/pulldown-cmark/issues/356#issuecomment-503347507).  If this is added, it will need to be reverted when it is fixed.  The bad escapes show up in other places, too, so it seems odd to only fix it in one spot.

**Comment by jonas-schievink** [comment]
@bors r-

Let's rather wait for a proper fix then.

**Comment by ehuss** [comment]
It may be reasonable to fix it now, and then revert it whenever pulldown-cmark is fixed.  I'll ping the issue and see what the status is.

**Comment by ehuss** [comment]
Oh, so I'm completely blind.  This has already been fixed in 0.5.3, and is already on nightly via #62789.

**Comment by jonas-schievink** [comment]
Oh, that's great. Might as well close this PR then and wait for the update to move to beta/stable.

**Pull request closed without merging**
