### PR TITLE
Make a disable-jemalloc build work

### LINKED ISSUE #43510: stage0 libstd fails to build when jemalloc is disabled
Since #43320 bumped the bootstrap compiler, stage0 libstd fails to build when jemalloc is disabled:

```text
error[E0463]: can't find crate for `alloc_jemalloc`

error: aborting due to previous error

error: Could not compile `std`.
```

I believe it needs to restore the logic removed here:
https://github.com/rust-lang/rust/pull/42727/files#diff-242481015141f373dcb178e93cffa850L236

I tried to add this to `libstd/lib.rs`:

```rust
// Always use alloc_system during stage0 since we don't know if the alloc_*
// crate the stage0 compiler will pick by default is available (most
// obviously, if the user has disabled jemalloc in `./configure`).
#![cfg_attr(any(stage0, feature = "force_alloc_system"), feature(global_allocator))]
#![cfg(any(stage0, feature = "force_alloc_system"))]
#[global_allocator]
static ALLOC: alloc_system::System = alloc_system::System;
```

Then stage0 passed, but stage1 std failed like:

```text
error[E0463]: can't find crate for `std`

error: aborting due to previous error

error: Could not compile `std`.
```

😕

### PR DESCRIPTION
**Pull request by aidanhs**
Fixes #43510. I've tested this up to building a stage1 compiler.

r? @alexcrichton 

cc @cuviper @vorner

@cuviper your fix was almost correct, you just had a stray `!` in there which caused the second error you saw.

### CODE REVIEW

**Comment by cuviper** [comment]
Oh, I see, I copied the `!` from the feature line. Thanks!

**Comment by kennytm** [comment]
`x86_64-pc-windows-msvc` failed to link `term` in stage0-libtest. Given the topic involved in this PR: Legit.

```
   Compiling term v0.0.0 (file:///C:/projects/rust/src/libterm)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-test\\x86_64-pc-windows-msvc\\release\\deps\\term-c6d433459a54f839.0.o" "/OUT:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-test\\x86_64-pc-windows-msvc\\release\\deps\\term-c6d433459a54f839.dll" "/DEF:C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustc.eYw8sZPlb2Lc\\lib.def" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-test\\x86_64-pc-windows-msvc\\release\\deps\\term-c6d433459a54f839.crate.metadata.o" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-test\\x86_64-pc-windows-msvc\\release\\deps\\term-c6d433459a54f839.crate.allocator.o" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-test\\x86_64-pc-windows-msvc\\release\\deps" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-test\\release\\deps" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "kernel32.lib" "/LIBPATH:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "std-6894941a948c9efd.dll.lib" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\rustc.eYw8sZPlb2Lc\\libcompiler_builtins-dd1b2e32329767b3.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "libcmt.lib" "/DLL" "/IMPLIB:C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-test\\x86_64-pc-windows-msvc\\release\\deps\\term-c6d433459a54f839.dll.lib"
  = note:    Creating library C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-test\x86_64-pc-windows-msvc\release\deps\term-c6d433459a54f839.dll.lib and object C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-test\x86_64-pc-windows-msvc\release\deps\term-c6d433459a54f839.dll.exp
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_alloc referenced in function __rust_alloc
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_oom referenced in function __rust_oom
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_dealloc referenced in function __rust_dealloc
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_usable_size referenced in function __rust_usable_size
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_realloc referenced in function __rust_realloc
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_alloc_zeroed referenced in function __rust_alloc_zeroed
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_alloc_excess referenced in function __rust_alloc_excess
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_realloc_excess referenced in function __rust_realloc_excess
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_grow_in_place referenced in function __rust_grow_in_place
          term-c6d433459a54f839.crate.allocator.o : error LNK2019: unresolved external symbol __rg_shrink_in_place referenced in function __rust_shrink_in_place
          C:\projects\rust\build\x86_64-pc-windows-msvc\stage0-test\x86_64-pc-windows-msvc\release\deps\term-c6d433459a54f839.dll : fatal error LNK1120: 10 unresolved externals
          
error: aborting due to previous error
error: Could not compile `term`.
```

**Comment by aidanhs** [comment]
Hum, I'll have to have a think about this, looks like it worked fine on all the osx and linux variants, but not on windows and I'm not 100% sure why - in theory `global_allocator` works the same way (right?) and the allocator tests work on windows so I don't have any immediate ideas.

Thoughts from onlookers appreciated.

**Comment by cuviper** [comment]
I'm no Windows expert, but I think it's more particular about resolving symbols only from directly-specified libraries.  I'm not sure what that implies in this case.

It looks like the msvc builds [always disable jemalloc](https://github.com/rust-lang/rust/blob/4596c71fc5556966a86a226f55f0d0deb9493e60/src/bootstrap/sanity.rs#L134-L138) anyway, so maybe this workaround can just be skipped there.  Appveyor didn't go far enough to see if windows-gnu has a similar link error.

**Comment by cuviper** [comment]
AFAICS none of the Windows targets change `exe_allocation_crate` from the default `None`, so maybe it just defaults to `alloc_system` even when windows-gnu does ship `alloc_jemalloc`?

**Comment by alexcrichton** [comment]
Errors like this are typically indicative of a missing "dllexport" attribute of some shape/form when the object is compiled. We have to apply dllexport manually and IIRC we don't do this correctly for allocator attributes. 

I think, though, the fix may not be too too hard if you'd like to pioneer it here. The boolean on whether to do this is [here](https://github.com/rust-lang/rust/blob/5431f423aac345e023815d3f10b8cb840711d756/src/librustc_trans/context.rs#L85), [here] is where allocator modules are trans'd, and I think [here](https://github.com/rust-lang/rust/blob/e3c8433ebb4a1acf125cae34ebd910869c894ebd/src/librustc_trans/back/symbol_export.rs#L133-L142) is roughly the right location for where to say "this symbol is a C symbol," e.g. needs a dllexport.

**Comment by aidanhs** [comment]
Ok, I've had a look at this and it's a bit humbling to realise how little I know about linking on Windows! Fortunately I have access to Windows so I'll play around this weekend and I think I have a route forward - looking at the export details, I think I might be able to just add extern to the allocator symbols during trans, rather than special casing them? We shall see anyway.

**Comment by alexcrichton** [comment]
@aidanhs ah yeah that sounds like a fine strategy to me as well!

**Comment by aidanhs** [comment]
This is the best I've come up with after wrestling with it for a bit. Note that because the stage0 snapshot has the broken behavior on msvc, I've had to cfg the global allocator stuff until the next snapshot update (which also means a temporary tidy check change).

In terms of approach:
 - I can't use the 'iterate through exports of crates' because the global allocator code isn't attached to a crate (I think?), it's just inserted directly into the LLVM module.
 - I *think* a Rust level export is fine because it's only referenced by rust code, i.e. when something depends on an rlib or dylib (rather than cdylib).

This gets past building stage0 term locally on Windows (obviously, because the new code is cfged out) but I've been unable to test further than that because building LLVM on Windows is being problematic. In particular, I'm not sure I've got the correct number of underscores.

**Comment by alexcrichton** [comment]
@bors: r+

That all sounds good to me! I think you're right about the "Rust level" as well instead of "C"

**Pull request merged**
