### PR TITLE
rustbuild: smarter `git submodule`-ing

### PR DESCRIPTION
**Pull request by japaric**
With this commit, if one bootstraps rust against system llvm then the
src/llvm submodule is not updated/checked-out. This saves considerable
network bandwith when starting from a fresh clone of rust-lang/rust as
the llvm submodule is never cloned.

cc #30107

r? @alexcrichton 
cc @petevine 

~~We could also avoid updating the jemalloc submodule if --disable-jemalloc is used. It just hasn't been implemented.~~ Done

This probably doesn't handle "recursive" submodules correctly but I think we don't have any of those right now.

I'm still testing a bootstrap but already confirmed that the llvm submodule doesn't get updated when `--llvm-root` is passed to `configure`.

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+ 5683bf9e2020506003d6528482e0673399f61c7d

Thanks!

**Comment by japaric** [comment]
Fixed tidy error

@bors r=alexcrichton

**Comment by TimNN** [comment]
I think this PR lead to the recent buildbot failures:

[Original Failure](https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/2312/steps/compile/logs/stdio) (I believe):

```
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
Synchronizing submodule url for 'src/compiler-rt'
Synchronizing submodule url for 'src/jemalloc'
Synchronizing submodule url for 'src/liblibc'
Synchronizing submodule url for 'src/llvm'
Synchronizing submodule url for 'src/rt/hoedown'
Synchronizing submodule url for 'src/rust-installer'
HEAD is now at 8598065 Rust: fix MSVC-built lib pulling in other lib files
HEAD is now at e058ca6 Change how the default zone is found
HEAD is now at 5066b7d Merge pull request #341 from japaric/arm-musl
      0 [main] git 2760 cygwin_exception::open_stackdumpfile: Dumping stack trace to git.exe.stackdump


command did not execute successfully: "git" "-C" "src/llvm" "reset" "--hard"
expected success, got: exit code: 35584


Makefile:23: recipe for target 'all' failed
>> rustjob: found 0 remaining processes
make: *** [all] Error 1
```

(And then cascading failures because git was killed without cleaning up lock files, I believe).

**Comment by alexcrichton** [comment]
Thanks for the investigation @TimNN! I do believe that's the original failure, and I do believe that it's causing the cascading failures. Now I have no idea what that failure *means* unfortunately... I don't think this PR is itself directly responsible for that but I could be wrong...

I think I'm going to clean out all the bots and retry everything. If this happens again we can revert but for now I'm gonna assume that this was a very unfortunately timed "standard random segfault on Windows"

**Pull request merged**
