### PR TITLE
Remove intra-docs check for items from dependencies

### LINKED ISSUE #58745: False warnings with cargo doc.
First raised this issue with ``rust-random/rand`` https://github.com/rust-random/rand/issues/737. But the documentation links seem to work fine. So may be it is false-warning raised by ``cargo doc`` ?

How to reproduce ?

```bash
$ git clone git@github.com:bnclabs/llrb-index.git
$ cd llrb-index

$ rustup which cargo
<path>/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo

$ cargo doc
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #58745.

r? @QuietMisdreavus

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
See https://github.com/rust-lang/rust/pull/58972 for discussion about this PR.

**Comment by Centril** [comment]
Ping from triage, @GuillaumeGomez @QuietMisdreavus -- what's the status? (I did see #58972)

**Comment by GuillaumeGomez** [comment]
I'm actually not sure myself...

**Comment by QuietMisdreavus** [comment]
Coming back to this one, i feel like it could be useful, if the check was changed. As-is, this will silence dead links from cross-crate re-exports. (Several of the examples from `rand` were legitimate dead links from items that were being re-exported.) However, it could be useful to add a check like this to make sure that an item is *exported* from the current crate before scanning it for links. That way, we don't report an error on something that the user actually doesn't care about.

**Pull request closed without merging**
