### PR TITLE
Hide methods on SliceIndex trait

### LINKED ISSUE #13698: Hidden methods still appear in trait implementation docs
Take, for example, `TotalEq`:

``` rust
pub trait TotalEq: Eq {
    // FIXME #13101: this method is used solely by #[deriving] to
    // assert that every component of a type implements #[deriving]
    // itself, the current deriving infrastructure means doing this
    // assertion without using a method on this trait is nearly
    // impossible.
    //
    // This should never be implemented by hand.
    #[doc(hidden)]
    #[inline(always)]
    fn assert_receiver_is_total_eq(&self) {}
}
```

As is proper, [the `TotalEq` docs make no mention of this hidden method `assert_receiver_is_total_eq`](http://static.rust-lang.org/doc/master/std/cmp/trait.TotalEq.html).

But now refer to an example like [the `TotalEq` impl for `Option`](http://static.rust-lang.org/doc/master/std/option/enum.Option.html#method.assert_receiver_is_total_eq)! Lo! `assert_receiver_is_total_eq` is shown there.

It shouldn't be.

### PR DESCRIPTION
**Pull request by kzys**
Rustdoc should be able to handle that. Fixes #13698.

### CODE REVIEW

**Comment by kzys** [comment]
r? @SimonSapin

but linkchecker is still not happy about that. Let me take a look.

**Comment by shepmaster** [comment]
> Fixes #13698.

It doesn't seem like this PR fixes the general problem, but is a bandaid for a specific case.

**Comment by SimonSapin** [comment]
It’s not a fix and I don’t believe it’s even a bandaid. This PR cannot land because of broken links precisely because of that issue.

**Comment by kzys** [comment]
Yes. Rustdoc has a lot of old issues and some of them are fixed on master, but this one seems not. Would you mind if I keep open this PR for, let's say 2 weeks? I will fix the cause.

**Comment by kzys** [comment]
I will take a look the issue later, but let me close the PR for a moment.

**Pull request closed without merging**
