### PR TITLE
environment variables -> environment

### PR DESCRIPTION
**Pull request by steveklabnik**
As @sanxiyn says,
https://github.com/rust-lang/rust/pull/23527#issuecomment-83835448

### CODE REVIEW

**Comment by sanxiyn** [comment]
Thanks! @bors r+ 8f0de74 rollup

**Comment by steveklabnik** [comment]
@sanxiyn you have to have @bors in the first column, it seems...

**Comment by steveklabnik** [comment]
(and there's a new feature where if you don't specify the commit, it pins to the last one automatically)

**Pull request merged**
