### PR TITLE
Include scope names in diagnostics

### PR DESCRIPTION
**Pull request by da-x**
Pre-RFC: https://github.com/rust-lang/rfcs/issues/2399

So far, rustc has only printed about filenames and line numbers for warnings and errors. I think it is rather missed, compared to `gcc` and other compiler, that useful context information such as function
names and structs is not included.

The changes in this pull request introduce new emissions in diagnostics to implement this.

Short example:

```rust
warning: unused variable: `a`
  --> pr.rs:18:9: in fn test
   |
18 |     let a = 1;
   |         ^ help: consider using `_a` instead
```

Check `in fn test` above.

The information for the line is gathered by a mechanism to resolve a `Span` to the corresponding named scope, by a Trait dynamic call from `librustc_error` back to `libsyntax`, in addition to what is done with
`CodeMap`. The call does a quick DFS into the AST for the `Span` and collects the relevant `Ident` path, so it should handle nested scopes properly.

To do:

* [ ] A merged RFC for these set of changes
* [ ] More fixes and refactoring following review
* [ ] Is it practical to also allow context diagnostics for the
      AST prior to macro expansion?
* [ ] Fix all tests that compare stdout/stderr
* [ ] Additional tests to cover all cases

A larger example:

```rust
struct OkStruct {
    i: u32,
}

#[derive(Debug)]
enum OkEnum {
    ItemA,
    ItemB,
}

impl OkStruct {
    fn method() {
        let a = 1;
    }
}

fn test() {
    let a = 1;
}

fn test_nested() {
    let a = 1;

    fn nested() {
        let b = 2;
    }
}

fn main() {
    let a = 1;

    println!("{:?}", OkEnum::ItemA);
}
```

The output is:

```rust
warning: unused variable: `a`
  --> pr.rs:18:9: in fn test
   |
18 |     let a = 1;
   |         ^ help: consider using `_a` instead
   |
   = note: #[warn(unused_variables)] on by default

warning: unused variable: `a`
  --> pr.rs:22:9: in fn test_nested
   |
22 |     let a = 1;
   |         ^ help: consider using `_a` instead

warning: unused variable: `b`
  --> pr.rs:25:13: in fn test_nested::nested
   |
25 |         let b = 2;
   |             ^ help: consider using `_b` instead

warning: unused variable: `a`
  --> pr.rs:30:9: in fn main
   |
30 |     let a = 1;
   |         ^ help: consider using `_a` instead

warning: unused variable: `a`
  --> pr.rs:13:13: in fn method::method
   |
13 |         let a = 1;
   |             ^ help: consider using `_a` instead

warning: struct is never used: `OkStruct`
 --> pr.rs:1:1
  |
1 | struct OkStruct {
  | ^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

warning: variant is never constructed: `ItemB`
 --> pr.rs:8:5: in enum OkEnum
  |
8 |     ItemB,
  |     ^^^^^

warning: method is never used: `method`
  --> pr.rs:12:5
   |
12 |     fn method() {
   |     ^^^^^^^^^^^

warning: function is never used: `test`
  --> pr.rs:17:1
   |
17 | fn test() {
   | ^^^^^^^^^

warning: function is never used: `test_nested`
  --> pr.rs:21:1
   |
21 | fn test_nested() {
   | ^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by da-x** [comment]
I opened an RFC for this. https://github.com/rust-lang/rfcs/issues/2399 . Will rewrite the implementation to suite the consensus from discussion.

**Comment by pietroalbini** [comment]
Ping from triage @nikomatsakis! This PR needs your review!

**Comment by nikomatsakis** [comment]
Some thoughts:

- The current output is the result of a lot of iteration.
  - I'm quite wary of making such a major change without more discussion.
  - Good that we opened the thread, therefore!

I do agree that this information is valuable, but I think I would prefer an alternate presentation. I'd also prefer for us to gather the information in a different way. I think however I'll move my concerns over to the internals thread.

I'm going to mark this PR as S-blocked for the time being -- however, I'm sort of inclined to close it, just because my queue is long and we're not ready to move here yet. But I'll hold off on that for now.

**Comment by nikomatsakis** [comment]
cc @estebank @jonathandturner

**Comment by nikomatsakis** [comment]
Because I have so many dang PRs pending, I'm going to close this pending any final decision (we can always re-open!). I think my post on the internals thread (which I confess I've been too slammed to keep up with) still represents my opinion.

**Comment by da-x** [comment]
@nikomatsakis Thanks! I am going to prepare an RFC based on all the comments.

**Pull request closed without merging**
