### PR TITLE
Move `compile-fail` tests to `ui` 

### LINKED ISSUE #46841: src/test/compile-fail should have more files in subdirectories
Github refuses to list more than 1,000 files in a given directory listing.

As of this writing, its web interface reports that 1,260 entries are omitted from the printout for https://github.com/rust-lang/rust/tree/master/src/test/compile-fail

This has a simple fix: More subdirectories.

In particular, many of the tests even have a prefix that strongly implies a potential subdirectory to move that subset into; e.g. the associated-{const,item,type} tests could all go into `associated-item/`. LIkewise, the `E0nnn` test could all go into `diagnostics/`...

(This is a super easy change to make to the test suite, though I know that some people want to separately migrate more/all of the tests into the `ui/` subdirectory. I no longer object to the latter migration, but we'll still need to resolve *this* problem even when we do that migration.)

### PR DESCRIPTION
**Pull request by davidtwco**
Fixes #46841, #52531, #44844.

r? @nikomatsakis

### CODE REVIEW

**Comment by davidtwco** [comment]
Tests changed in [this commit](https://github.com/rust-lang/rust/pull/53196/commits/fc7c96a83ff6e51a5461784b100d7d2831c5b923) need to be checked as they were failing on NLL compare mode so I just added `ignore-compare-mode-nll` for the time being.

**Comment by kennytm** [comment]
@bors retry treeclosed=20 

https://www.traviscistatus.com/incidents/pxj3py3xzn14 

Closing the tree until the incident is resolved.

**Comment by kennytm** [comment]
<details><summary>[ui (nll)] ui\dropck\dropck_trait_cycle_checked.rs</summary>

```diff
 ---- [ui (nll)] ui\dropck\dropck_trait_cycle_checked.rs stdout ----
 diff of stderr:
5	   |             ^^^ borrowed value does not live long enough
6	...
7	LL | }
-	   | -
-	   | |
-	   | `o2` dropped here while still borrowed
-	   | borrow later used here, when `o2` is dropped
+	   | - `o2` dropped here while still borrowed
+	   |
+	   = note: borrowed value must be valid for the static lifetime...
12	
13	error[E0597]: `o3` does not live long enough
14	  --> $DIR/dropck_trait_cycle_checked.rs:122:13
17	   |             ^^^ borrowed value does not live long enough
18	...
19	LL | }
-	   | -
-	   | |
-	   | `o3` dropped here while still borrowed
-	   | borrow later used here, when `o3` is dropped
+	   | - `o3` dropped here while still borrowed
+	   |
+	   = note: borrowed value must be valid for the static lifetime...
24	
25	error[E0597]: `o2` does not live long enough
26	  --> $DIR/dropck_trait_cycle_checked.rs:123:13
51	   |             ^^^ borrowed value does not live long enough
52	LL |     o3.set1(&o2); //~ ERROR `o2` does not live long enough
53	LL | }
-	   | -
-	   | |
-	   | `o1` dropped here while still borrowed
-	   | borrow later used here, when `o1` is dropped
+	   | - `o1` dropped here while still borrowed
+	   |
+	   = note: borrowed value must be valid for the static lifetime...
58	
59	error[E0597]: `o2` does not live long enough
60	  --> $DIR/dropck_trait_cycle_checked.rs:126:13
```

</details>

<details><summary>[ui (nll)] ui\unboxed-closures\unboxed-closures-failed-recursive-fn-1.rs</summary>

```diff
 ---- [ui (nll)] ui\unboxed-closures\unboxed-closures-failed-recursive-fn-1.rs stdout ----
 diff of stderr:
38	   |                 ^^^^^^^^^ borrowed value does not live long enough
39	...
40	LL | }
-	   | -
-	   | |
-	   | `factorial` dropped here while still borrowed
-	   | borrow later used here, when `factorial` is dropped
+	   | - `factorial` dropped here while still borrowed
45	   |
-	   = note: values in a scope are dropped in the opposite order they are defined
+	   = note: borrowed value must be valid for the static lifetime...
47	
48	error[E0506]: cannot assign to `factorial` because it is borrowed
49	  --> $DIR/unboxed-closures-failed-recursive-fn-1.rs:42:5
55	   |                 --------- borrow occurs due to use in closure
56	...
57	LL |     factorial = Some(Box::new(f));
-	   |     ^^^^^^^^^
-	   |     |
-	   |     assignment to borrowed `factorial` occurs here
-	   |     borrow later used here
+	   |     ^^^^^^^^^ assignment to borrowed `factorial` occurs here
+	   |
+	   = note: borrowed value must be valid for the static lifetime...
62	
63	error: aborting due to 4 previous errors
64	
```

</details>

**Comment by pnkfelix** [comment]
If you (like me) are trying to trace through the history and want to get to `compile-fail/` immediately before this PR landed, here you go: https://github.com/rust-lang/rust/tree/d67ba90dab243d2b80324e29df2f06ba13c97607/src/test/compile-fail

**Pull request merged**
