### PR TITLE
Minor grammar nit.

### PR DESCRIPTION
**Pull request by uberFoo**
I was browsing the documentation and noticed that this should be an adverb.

### CODE REVIEW

**Comment by JohnTitor** [comment]
This has been merged in rollup but hasn't been marked as merged because the author pushed a commit while rollup'ing.
@uberFoo Next time be careful when a reviewer does `r+`!
Closing as the change itself has been merged successfully.

**Comment by uberFoo** [comment]
It would be great if you could help me understand what I did wrong. The only commit I intentionally made was the initial one.

**Comment by JohnTitor** [comment]
You force-pushed while a rollup PR was open, which changed the commit SHA, and GitHub couldn't mark this PR as merged.

**Comment by uberFoo** [comment]
That’s the part I don’t understand. I don’t know how I managed to do that. I don’t remember touching anything after the initial PR. Was this a push to my PR, or my local branch. Forgive the newb questions, but I am one. I’ve never worked with a project this complex. 

Thanks!

**Pull request closed without merging**
