### PR TITLE
add error message for c# style named arguments

### PR DESCRIPTION
**Pull request by nouritsu**
Solves #116411 
Result -
> 1.
> ```rust
> fn main() {
>     let a = 50;
> 
>     foo(x: a);
> }
> 
> fn foo(x: i32) {}
> ```
> 
> Output - image
> 
> 2.
> ```rust
> fn main() {
>     let a = 50;
> 
>     Foo::bar(x: a);
> }
> 
> struct Foo {
>     pub fn bar(x : i32){}
> }
> ```
> 
> Output - image

### CODE REVIEW

**Comment by nouritsu** [comment]
Would I have to change the tests, since the error message is no longer the same? @estebank

**Comment by petrochenkov** [comment]
r? compiler
I'm overloaded with reviews.

**Comment by petrochenkov** [comment]
r? compiler
b-naber doesn't do reviews.

**Comment by estebank** [comment]
r? @estebank 

@nouritsu you need to run `./x.py test tests/ui --bless` in order to update the relevant `.stderr` files.

**Comment by nouritsu** [comment]
Running it does not seem to update any files. Am I missing something?
image
It hardly took any time and it did not change any files or output anything.

**Comment by nouritsu** [comment]
This is the message from the command - 
image

**Comment by estebank** [comment]
@nouritsu That output seems odd. Can you try to follow the instructions at https://rustc-dev-guide.rust-lang.org/tests/running.html? I wonder if there's some uncommon set-up in your environment for that error to happen. (*raises fist at OSError not printing the path that caused the problem*)

Also, we don't include merge commits in PRs, we always rebase on top of a newer master.

**Comment by nouritsu** [comment]
I'm not familiar with git, I will be opening a new pull request.

**Pull request closed without merging**
