### PR TITLE
Revert #71956

### PR DESCRIPTION
**Pull request by ecstatic-morse**
Revert #71956 since it caused unsoundness in #73137. Also adds a reduced version of #73137 to the test suite. The addition of the `MaybeInitializedLocals` dataflow analysis has not been reverted, but it is no longer used.

Presumably there is a more targeted fix, but I'm worried that other bugs may be lurking. I'm not yet sure what the root cause of #73137 is.

This will need to get backported to beta.

r? @tmandry

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
Mistake in the test case

@bors r=tmandry

**Comment by ecstatic-morse** [comment]
@bors r=tmandry

The test is now a bit more robust, and I found the right `Co-authored-by` syntax. A source-level regression test is not the best for bugs like these, but it was the best I could do on short notice.

**Comment by ecstatic-morse** [comment]
Nominating for @rust-lang/compiler. We need to backport this to beta.

**Comment by pnkfelix** [comment]
Discussed at today's [T-compiler meeting](https://zulip-archive.rust-lang.org/238009tcompilermeetings/72518weeklymeeting2020061154818.html#200550006); approved for beta backport.

**Pull request merged**
