### PR TITLE
Up the LLVM

### LINKED ISSUE #36474: ICE:  void llvm::Value::replaceAllUsesWith(llvm::Value*): Assertion `!contains(New, this) && "this->replaceAllUsesWith(expr(this)) is NOT valid!"' failed.
This is a recently introduced ICE that appears with -Copt-level=3

using rustc 1.13.0-nightly (5531c314a 2016-09-12)

> rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Value.cpp:373: void llvm::Value::replaceAllUsesWith(llvm::Value*): Assertion `!contains(New, this) && "this->replaceAllUsesWith(expr(this)) is NOT valid!"' failed.

Shrunk test case below (original is in ndarray tests/dimension.rs). Use `rustc -Copt-level=3` to reproduce.

```rust
fn main() {
    remove_axis(&3, 0);
}

trait Dimension {
    fn slice(&self) -> &[usize];
}

impl Dimension for () {
    fn slice(&self) -> &[usize] { &[] }
}

impl Dimension for usize {
    fn slice(&self) -> &[usize] {
        unsafe {
            ::std::slice::from_raw_parts(self, 1)
        }
    }
}

fn remove_axis(value: &usize, axis: usize) -> () {
    let tup = ();
    let mut it = tup.slice().iter();
    for (i, _) in value.slice().iter().enumerate() {
        if i == axis {
            continue;
        }
        it.next();
    }
}
```

(Edits: Reduced test case further)

### PR DESCRIPTION
**Pull request by nagisa**
Fixes #36474 

The relevant patch to rust-llvm is at https://github.com/rust-lang/llvm/pull/51

r? @alexcrichton

### CODE REVIEW

**Comment by nagisa** [comment]
Nominating for beta, as it fixes a regression.

**Comment by alexcrichton** [comment]
Hm so we've got two parallel updates to the LLVM submodule right now. Both this and the wasm backend. I'd feel pretty uncomfortable about backporting the emscripten backend. To be honest our LLVM backend on beta is at rust-lang/llvm@80ad955b60b3ac02d0462a4a65fcea597d0ebfb1 which is *way* off from what's on nightly... I guess all that's to say:

* To land this on beta, we may want a different backport? To the `rust-llvm-2016-03-13` I think.
* To land on master we may want to either use a rev that *doesn't* have emscripten or wait for that patch to land first.

**Comment by nagisa** [comment]
> * To land this on beta, we may want a different backport? To the rust-llvm-2016-03-13 I think.
* To land on master we may want to either use a rev that doesn't have emscripten or wait for that patch to land first.

I’d gladly backport the LLVM patch as many times as necessary (its a simple one-liner after all), but I’ll need new branches from `786aad1` for beta and from `16b79d01` for nightly – both of these commits seem to be in 07-09 branch only.

(the branches with the backported patch at relevant base commits are https://github.com/nagisa/llvm/tree/backport-281650-beta for beta and https://github.com/nagisa/llvm/tree/backport-281650-master for nightly)

> wait for that patch to land first

This is a fix for beta regression and we do :train: roll-over in just a bit over than a week. I’m fine with  waiting before backporting the fix to the nightlies’ LLVM (in which case you might have to live through 2 beta backports of the same patch), but beta rust has to get that LLVM patch ASAP.

**Comment by brson** [comment]
I rebased the 2016-07-09 branch to make your patch appear ahead of the fastcomp in the history, so you don't need to worry about any fallout from it, but you'll need to update this PR with the correct new commit.

From what I can tell @alexcrichton was mistaken about beta being on a different LLVM. It looks to me like the most recent commit is https://github.com/rust-lang/llvm/commit/eee68eafa7e8e4ce996b49f5551636639a6c331a, which is only one merge behind nightly, this fix to run GVN again https://github.com/rust-lang/llvm/commit/cc2009f02d3b9a3c05be939978212e832310b3d6. If that looks right to you @nagisa @eddyb we should just be able to take the same commit on both master and beta.

**Comment by nagisa** [comment]
Updated the LLVM commit; this is good to go.

**Comment by nagisa** [comment]
The bot in question did not rebuild LLVM. What do?

**Comment by pmarcelll** [comment]
@nagisa IIRC src/rustllvm/llvm-auto-clean-trigger should also be updated.

**Comment by nikomatsakis** [comment]
Accepting for beta. Trivial patch (hiding LLVM changes of course...), regression.

**Comment by brson** [comment]
After looking into this further, @alexcrichton was right that beta and master are on two different merge bases. The LLVM patch is going to need to be ported to the beta LLVM specifically.

**Comment by brson** [comment]
Actually, they do look like the have the same merge-base. For some reason when cherry-picking this git says "Failed to merge submodule src/llvm (commits don't follow merge-base)". I don't understand why.

**Pull request merged**
