### PR TITLE
BTreeMap: split off most code of remove and split_off

### PR DESCRIPTION
**Pull request by ssomers**
Putting map.rs on a diet, in addition to #77851.
r? @dtolnay

### CODE REVIEW

**Comment by ssomers** [comment]
It's also possible to do the same for `append`, but right now that interferes with #78015.

**Comment by ssomers** [comment]
tidy does not report on extraneous empty lines on Windows like it does on Linux!?

**Review by dtolnay — APPROVED** [review]
Thank you!

**Pull request merged**
