### PR TITLE
rustdoc: Only hide lines starting with `#` in rust code blocks 

### LINKED ISSUE #105527: Rustdoc does not format ASCII art containing `###` at the start of a line correctly
I tried this code:

```rust
//! This is some documentation with ASCII art:
//!
//! ```text
//! #..#.####.#....#.....##..
//! #..#.#....#....#....#..#.
//! ####.###..#....#....#..#.
//! #..#.#....#....#....#..#.
//! #..#.#....#....#....#..#.
//! #..#.####.####.####..##..
//! ```
```

I expected to see this happen: When I run `rustdoc`, I expect to see ASCII art in the output that matches the above example.

Instead, this happened: In the output, this actually appears:
```text
#..#.####.#....#.....##..
#..#.#....#....#....#..#.
###.###..#....#....#..#.
#..#.#....#....#....#..#.
#..#.#....#....#....#..#.
#..#.####.####.####..##..
```
It appears that if a line starts with at least three `#`s, one gets "swallowed" somehow.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
```

<details><summary>Backtrace</summary>
<p>

```
n/a
```

</p>
</details>

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/105527.

So before approving, this is a big question: in rust code blocks, in a line starts with a `#`, we hide it in the output. However, should we do the same for non-rust code blocks too? I think it's a bit problematic to do it because `#` can be used for many things but I prefer to check first with everyone (might also be worth updating documentation too).

cc @rust-lang/rustdoc 
r? @notriddle

### CODE REVIEW

**Comment by jsha** [comment]
I agree we should not hide # lines for non rust blocks.

**Comment by camelid** [comment]
I agree that we should only hide `#` lines for Rust code blocks. For example, the following code

`````
/// ```markdown
/// # Header
/// ```
`````

should render as

```markdown
# Header
```

whereas currently I think it would render as nothing?

**Comment by camelid** [comment]
UPDATE: This is actually a stable-to-stable regression: https://github.com/rust-lang/rust/issues/105527#issuecomment-1345420432

**Comment by GuillaumeGomez** [comment]
Well, better late than never for an old fix. I added a "beta nominated" label so we can at least have this fix available one version sooner.

**Comment by pietroalbini** [comment]
Approved for backport in https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/1.2E66.2E0/near/315377940.

**Note:** the `beta-nominated` label needs to be kept when backporting to 1.66, as a backport to 1.67 is also needed.

**Pull request merged**
