### PR TITLE
Fix rare ICE during typeck in rustdoc scrape_examples

### PR DESCRIPTION
**Pull request by willcrichton**
While testing the `--scrape-examples` extension on the [wasmtime](https://github.com/bytecodealliance/wasmtime) repository, I found some additional edge cases. Specifically, when asking to typecheck a body containing a function call, I would sometimes get an ICE if:
* The body doesn't exist
* The function's HIR node didn't have a type

This adds checks for both of those conditions.

(Also this updates a test to check that the sources of a reverse-dependency are correctly generated and linked.)

r? @jyn514

### CODE REVIEW

**Review by jyn514 — CHANGES_REQUESTED** [review]

**Review by jyn514 — CHANGES_REQUESTED** [review]

**Comment by willcrichton** [comment]
@jyn514 does that resolve your concern?

**Comment by jyn514** [comment]
@willcrichton I think so - I'm still slightly confused how this can happen when visitor passes OnlyBodies, but not enough to block on it. Can you update the comment to say "the caller needs to ensure this is a function body" rather having a red herring about overriding typeck?

**Comment by willcrichton** [comment]
Done!

**Pull request merged**
