### PR TITLE
Store all args in the unsupported Command implementation

### PR DESCRIPTION
**Pull request by bjorn3**
This allows printing them in the Debug impl as well as getting them again using the get_args() method. This allows programs that would normally spawn another process to more easily show which program they would have spawned if not for the fact that the target doesn't support spawning child processes without requiring intrusive changes to keep the args. For example rustc compiled to wasi will show the full linker invocation that would have been done.

### CODE REVIEW

**Comment by jhpratt** [comment]
I was a little skeptical when I first saw this due to the significant increase in size of `Command`, even if it is only on certain platforms. Given your example of wasi and your background, I have no reason to believe that this PR would be a bad decision despite the additional overhead. For that reason, I have no objection to this PR landing.

@bors r+

**Comment by GuillaumeGomez** [comment]
I think it's the one which failed in https://github.com/rust-lang/rust/pull/123667.

**Comment by bjorn3** [comment]
I can't reproduce it locally, but it should be fixed now.

**Comment by jhpratt** [comment]
I wonder why that failed :thinking: Allowing the lint is certainly reasonable.

@bors r+

**Pull request merged**
