### PR TITLE
Rollup of 12 pull requests

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Successful merges:

 - #100220 (Properly forward `ByRefSized::fold` to the inner iterator)
 - #100811 (Fix wrong compiletest filters on Windows)
 - #100819 (Make use of `[wrapping_]byte_{add,sub}`)
 - #100826 (sugg: take into count the debug formatting)
 - #100855 (Extra documentation for new formatting feature)
 - #100901 (Make some methods private)
 - #100906 (Suggest alternatives when trying to mutate a `HashMap`/`BTreeMap` via indexing)
 - #100912 (Diagnose missing includes in run-make tests)
 - #100922 (Rewrite error index generator to greatly reduce the size of the pages)
 - #100930 (Use `--userns=keep-id` when "docker" is really podman)
 - #100938 (rustdoc: remove unused CSS rule)
 - #100945 (Add a missing test case for impl generic mismatch)

Failed merges:

r? @ghost
@rustbot modify labels: rollup

[Create a similar rollup](https://bors.rust-lang.org/queue/rust?prs=100220,100811,100819,100826,100855,100901,100906,100912,100922,100930,100938,100945)

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Hmm, it might be that there is a miri test that somehow gets stuck (its always the x86 and msvcs tool builders that are hanging) but I didn't see and clear indication which test it might be :/

**Comment by matthiaskrgr** [comment]
Kind of leaning towards https://github.com/rust-lang/rust/pull/100811 or https://github.com/rust-lang/rust/pull/100819/ but only because everything else seems less likely to me :/

**Comment by RalfJung** [comment]
> Hmm, it might be that there is a miri test that somehow gets stuck (its always the x86 and msvcs tool builders that are hanging) but I didn't see and clear indication which test it might be :/

Would be good to ping @rust-lang/miri in such situations. I just spent 15min tracking down a strange Miri hang to https://github.com/rust-lang/rust/pull/101152.

**Comment by RalfJung** [comment]
Actually turns out this was a real bug that our test suite missed but the Miri test suite caught -- see https://github.com/rust-lang/rust/issues/101235.

**Pull request closed without merging**
