### PR TITLE
CMake: Do not print installation messages for up-to-date files

### LINKED ISSUE #60830: Set `CMAKE_INSTALL_MESSAGE` to `LAZY` for code built with CMake, LLVM in particular
The "log is too long" error in https://github.com/rust-lang/rust/pull/60740#issuecomment-492300006 reminded me about this possibility.

`CMAKE_INSTALL_MESSAGE=LAZY` will avoid printing installation messages for up-to-date files into the log.
There are *many* of them in the log as you can see.

### PR DESCRIPTION
**Pull request by petrochenkov**
Closes https://github.com/rust-lang/rust/issues/60830

### CODE REVIEW

**Comment by alexcrichton** [comment]
I would personally prefer if this were only applied to the location necessary for llvm, all the others should be inconsequential and/or handled already. Could the comment be expanded as well as to why it is applied, not just what it is?

**Comment by petrochenkov** [comment]
@alexcrichton 
>Could the comment be expanded as well as to why it is applied, not just what it is?

The reason is that `CMAKE_INSTALL_MESSAGE=LAZY` is almost always what you want, during local development or on CI, doesn't matter.
It's not the default in CMake because `CMAKE_INSTALL_MESSAGE` is a relatively recent addition (introduced in CMake 3.1 https://cmake.org/pipermail/cmake/2014-December/059418.html).
Perhaps `cmake-rs` can even set it by default.

The Travis issue with overflowing logs is a trigger for enabling it rather than the reason.

**Comment by petrochenkov** [comment]
The option is useless if the install directory is certainly fresh and empty.
I don't know whether that's a case for cmake that's run from `src/ci`.

For cmake that's run from `*.rs` that's not the case.

**Comment by alexcrichton** [comment]
It makes sense yeah that it's a better default, and I'm not disagreeing at all. All our build scripts are already complicated and this is just one more thing to understand whenever reading them, and it's basically easier to read zero code than it is to reason later "did someone add this for correctness?" or having to preserve this through all future changes. I would rather than this be surgical and only apply, with a comment, to where it matters. Changing `cmake-rs` itself also seems totally fine by me.

**Comment by petrochenkov** [comment]
OK, the messages in the failed job were produced by LLVM and LLD builds, so I reduced the changes to those only.

@bors r=Mark-Simulacrum

**Pull request merged**
