### PR TITLE
Add `AtomicPtr::as_mut_ptr`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
See https://github.com/rust-lang/rust/issues/66893#issuecomment-720125447

r? thomcc

### CODE REVIEW

**Comment by thomcc** [comment]
Can you file an ACP?

**Comment by WaffleLapkin** [comment]
I can, although I thought it's not required here, given that this is such a small change and adds a method that already exists for other `Atomic*` 🤔

**Comment by thomcc** [comment]
Sure, but I don't have the ability to approve new APIs.

I'll just assign to Mara, who [suggested](https://github.com/rust-lang/rust/issues/66893#issuecomment-720125447) that it should be added (back in 2020)

r? @m-ou-se

**Pull request merged**
