### PR TITLE
Ignore issue #16671 test on android (again)

### PR DESCRIPTION
**Pull request by sfackler**
Seems to be blocking forever

### CODE REVIEW

**Comment by Manishearth** [comment]
(So as not to overshadow the rollup, which contains this PR anyway)

**Comment by alexcrichton** [comment]
What's going on here? Do you have some example logs of what's going on?

Most of these failures just involve adding a call to `.join()` to fix as well.

**Comment by sfackler** [comment]
The test just times out: http://buildbot.rust-lang.org/builders/auto-linux-64-x-android-t/builds/3858/steps/test/logs/stdio.

Do we have any idea why `.join` would actually fix things on android?

**Comment by alexcrichton** [comment]
There are often unfortunate interactions with running concurrently with shutdown code. There is often an actual underlying issue but using `.join` for now should help in theory to "paper over it" (but an issue opened would still be nice!)

**Comment by Manishearth** [comment]
These both merged.

- https://github.com/rust-lang/rust/commit/c84e3a1f1980e8021893a32071ca788fdd8d1a7a 
- https://github.com/rust-lang/rust/commit/e955f4323b6aebed32250ffaaba8e8fdb680b4d5

**Pull request closed without merging**
