### PR TITLE
Prettify MIR graphviz output

### PR DESCRIPTION
**Pull request by nagisa**
One will look at graphviz often when working with MIR, so may as well make the tables a bit more
pretty :)

This is what it looks like now

### CODE REVIEW

**Comment by eddyb** [comment]
cc @tsion

**Comment by tsion** [comment]
I have a PR that makes larger changes to the graphviz output, but I see no reason not to merge this now. Most of my changes are for the textual parts (especially constants). I don't have the `cornsilk` colored terminators, but I could add that if desired. :)

I'll try to get my PR ready ASAP.

**Comment by nagisa** [comment]
Fixed the build failure, re-r+?

**Comment by tsion** [comment]
@nagisa I'll rebase onto yours. That'll be much simpler.

**Pull request merged**
