### PR TITLE
Error if submodule fetch fails.

### PR DESCRIPTION
**Pull request by ehuss**
In CI, if fetching a submodule fails, the script would exit successfully. Later parts of the build will fail due to the missing files, but it is a bit confusing, and I think it would be better to error out earlier.

The reason is that in bash, `wait` without arguments will exit 0 even if a background job exits with an error. The solution here is to wait on each individual job, which will return the exit code of the job.

This was encountered in #92177.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
@bors r+ rollup

This makes sense to me, thanks!

**Comment by matthiaskrgr** [comment]
This is probably causing errors here:
https://github.com/rust-lang/rust/pull/94443#issuecomment-1054130595
@bors rollup=never

**Comment by ehuss** [comment]
Oh, sorry about that.   I did a bunch of testing when I wrote this and I never saw the tar errors.  Those look like legitimate problems with the archives, I'll try to investigate more.

@bors r-

**Comment by ehuss** [comment]
@Mark-Simulacrum I pushed a fix for the extraction error.  On Windows, msys will not use symlinks by default.  `tar` will try to copy the file, but that depends on the order of the files in the archive, and will fail if the destination does not exist yet.  This adds an env var to tell `tar` to use normal symlinks, which are enabled on GitHub Actions.

**Comment by ehuss** [comment]
OK, I think this is ready for review again.  I had done a bunch of testing on Windows, but didn't have quite the same setup.  For some reason, the MSYS2 script causes `tar` to fail.  I resolved that problem by moving the submodule checkout to happen *before* the MSYS2 script.  I'm not sure if that order of steps was intentional, but I don't see a particular problem with that.  I also don't entirely know why msys2 was causing problems.

**Pull request merged**
