### PR TITLE
Adding RBE as a submodule #46194

### PR DESCRIPTION
**Pull request by projektir**
Adding RBE as a submodule to start issue #46194.

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is a needed step, but the build also needs to be updated to actually build RBE in the correct place.

**Comment by carols10cents** [comment]
Triage: this is blocked on https://github.com/rust-lang/rust-by-example/pull/962 to get tidy to pass.

**Comment by alexcrichton** [comment]
r? @steveklabnik 

I think I'll leave this one to the docs team

**Comment by steveklabnik** [comment]
I merged the upstream issue.

**Comment by kennytm** [comment]
@projektir You may update the submodule to point at the latest RBE master now.

**Comment by projektir** [comment]
It should already be pointed if I understand submodules right, this just needs to be refreshed?

**Comment by steveklabnik** [comment]
It doesn't look like it. Maybe you forgot to push the new commit?

**Comment by kennytm** [comment]
At least one [RBE sample](https://github.com/rust-lang/rust-by-example/blob/master/src/std_misc/process.md) is failing. Our $PATH doesn't contain `rustc`...

<details>

```
[01:19:09] command did not execute successfully: "/checkout/obj/build/bootstrap/debug/rustdoc" "--test" "/checkout/src/doc/rust-by-example/src/std_misc/process.md" "--test-args" ""
[01:19:09] expected success, got: exit code: 101
[01:19:09] 
[01:19:09] stdout ----
[01:19:09] 
[01:19:09] running 1 test
[01:19:09] test /checkout/src/doc/rust-by-example/src/std_misc/process.md - Child_processes (line 6) ... FAILED
[01:19:09] 
[01:19:09] failures:
[01:19:09] 
[01:19:09] ---- /checkout/src/doc/rust-by-example/src/std_misc/process.md - Child_processes (line 6) stdout ----
[01:19:09] 	thread 'rustc' panicked at 'test executable failed:
[01:19:09] 
[01:19:09] thread 'main' panicked at 'failed to execute process: No such file or directory (os error 2)', /checkout/src/doc/rust-by-example/src/std_misc/process.md:8:12
[01:19:09] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:19:09] 
[01:19:09] ', /checkout/src/librustdoc/test.rs:322:16
[01:19:09] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:19:09] 
[01:19:09] 
[01:19:09] failures:
[01:19:09]     /checkout/src/doc/rust-by-example/src/std_misc/process.md - Child_processes (line 6)
[01:19:09] 
[01:19:09] test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[01:19:09] 
[01:19:09] 
[01:19:09] stderr ----
```

</details>

**Comment by steveklabnik** [comment]
That's marked as runnable because the playground does...

I would be okay with ignoring it in RBE, I think, as it's not like it's that important anyway.

**Comment by shepmaster** [comment]
@projektir If I am following along correctly, I think you will need to update the submodule reference in this PR again.

**Comment by projektir** [comment]
Rebased/updated, looks like all checks pass!

**Comment by projektir** [comment]
@steveklabnik Is there anything else blocking this?

**Comment by steveklabnik** [comment]
Did you actually do a build? I haven't had the chance yet, but I think https://github.com/rust-lang/rust/blob/db162922f7e43fffccbf534028b36055ae9af014/src/bootstrap/builder.rs#L259-L261 needs to change as well?

**Comment by projektir** [comment]
@steveklabnik I've added Rust By Example there now, but I don't really know what you mean by a build. I don't know much about Rust's website build system. The only thing I know about is `x.py build` and that was always building fine. I am concerned that I may be missing other things now. Perhaps @Havvy would know more.

**Comment by Havvy** [comment]
Unfortunately, I know as much as you do, and what is being attempted isn't documented anywhere AFAICT, so it'd be nice to have a rundown of what else needs to be done/known.

**Comment by steveklabnik** [comment]
Does `x.py doc` generate a `rust-by-example` directory inside of `build/target/doc`?

**Comment by steveklabnik** [comment]
```text
[00:46:42] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rustbook" "build" "/checkout/src/doc/rust-by-example" "-d" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc/rust-by-example"
```

**Comment by steveklabnik** [comment]
Building locally, it seems that the files are where they should be. No idea about travis

**Comment by projektir** [comment]
Ran `x.py doc`, seems to work fine. Created the `rust-by-example` folder and the entire website seems to be built there, works and everything.

**Comment by kennytm** [comment]
@projektir The CI error is 

```
[00:46:42] An error occured:
[00:46:42] Read-only file system (os error 30)
[00:46:42] 
[00:46:42] 
[00:46:42] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rustbook" "build" "/checkout/src/doc/rust-by-example" "-d" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc/rust-by-example"
```

Note that the CI sets mounts the `src/` directory at a read-only volume. Is there any setting causing rustbook to write directly next to the source files, instead of in the target directory?

**Comment by steveklabnik** [comment]
Looks like it's reading from `checkout/src` and writing to `/checkout/obj`,
so....hm.

**Comment by steveklabnik** [comment]
this... makes no sense. I don't know what to do here.

**Comment by steveklabnik** [comment]
@rust-lang/infra , do you have any ideas?

**Comment by alexcrichton** [comment]
Typically I diagnose that by checking out a fresh clone, doing what CI does, and then seeing what changed in the cwd. Typically it's an erroneous file write or something like 'Cargo.lock forgot to get updated'

**Comment by carols10cents** [comment]
ping to keep this on your radar @steveklabnik, does what alex said make sense?

**Comment by steveklabnik** [comment]
I don't know how to "do what CI does" exactly. @projektir did you give this a shot?

**Comment by kennytm** [comment]
You could try to run the docker images directly https://github.com/rust-lang/rust/blob/master/src/ci/docker/README.md

**Comment by ollie27** [comment]
So the issue here is that mdBook has a nasty habit of creating files it tries to read rather than returning an error like sensible programs. In this case it tries to create `src/macro/syntax.md` because it's referenced in `SUMMARY.md`. Fortunately this has been fixed in the master branch by rust-lang/rust-by-example#977 so just updating the submodule should be enough to get this to build properly.

**Comment by steveklabnik** [comment]
Ah ha! Thanks @ollie27 ❤️ 

@projektir can you update this PR?

**Comment by projektir** [comment]
@steveklabnik We fixed up the various linking issues and looks like this is passing again! :smile:

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
@bors: r+

Thank you @projektir ; what should have been a simple PR has really been a wild ride.

**Comment by steveklabnik** [comment]
The build log is so long I can't see what the failure was. Since it's only on one arch, I'm assuming it was spurious.

@bors: retry

**Comment by projektir** [comment]
Was it, by any chance, this: "Build execution time has reached the maximum allowed time for your plan (180 minutes)."? Seems like the failed arch was Windows GNU. Hopefully spurious...

**Pull request merged**
