### PR TITLE
Run `cargo update` in the project root

### PR DESCRIPTION
**Pull request by tgross35**
try-job: x86_64-msvc

Part of https://github.com/rust-lang/rust/pull/129538

### CODE REVIEW

**Comment by tgross35** [comment]
Running a try job because of https://github.com/rust-lang/rust/issues/127890

@bors try

**Comment by tgross35** [comment]
Hm. I assume this comes from `stacker` making a change that brings in windows-sys 0.36.1, which is quite a bit older than the other versions we use

**Comment by tgross35** [comment]
@nagisa it looks like you maintain https://github.com/rust-lang/stacker, any clue if this is related?

**Comment by nagisa** [comment]
Sounds plausible enough. There's already a PR that bumps it on stacker side, so you'll be able to check this soon enough.

**Comment by tgross35** [comment]
Okay, I dropped doing a `cargo update` in the root repo. Let's try again.

@bors try

**Comment by Mark-Simulacrum** [comment]
r=me, but looks like it needs a rebase.

**Comment by tgross35** [comment]
Thanks. It also races with https://github.com/rust-lang/rust/pull/129619#issuecomment-2322881390 so I’ll just let that one get in before I rebase.

**Comment by tgross35** [comment]
@bors try

Just to make sure the memchr changes don't cause problems now that there isn't the winapi downgrade from stacker.

**Comment by tgross35** [comment]
Rebased since https://github.com/rust-lang/rust/pull/129619#event-14093615494 landed. The stacker fix also unblocked the few remaining updates.

@bors r=Mark-Simulacrum

**Comment by tgross35** [comment]
https://github.com/rust-lang/rust/pull/129860 caused a conflict. Rebased and reran `cargo update`.

@bors r=Mark-Simulacrum

**Comment by tgross35** [comment]
`failed to remove file `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\libcompiler_builtins-7c3f7c6358f370a6.rlib`

@bors retry

**Comment by tgross35** [comment]
Looks like the same thing again, ``failed to remove file `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\libcompiler_builtins-7c3f7c6358f370a6.rlib``

@bors retry

**Comment by tgross35** [comment]
This has been attempting to merge for over a week. It seems to just be bad luck as the errors in https://github.com/rust-lang/rust/pull/130129#issuecomment-2337304987 hasn't repeated since that rollup, and we have only had the standard MSVC failures. If this fails again I guess I could try splitting it up in case there is a change causing problems here.

Since it has been a while, I rebased to include the latest from https://github.com/rust-lang/rust/pull/129538.

@bors r=Mark-Simulacrum

**Comment by ChrisDenton** [comment]
Let's retry one more time. This PR's failure rate does seem worse than bad luck.

@bors retry

**Comment by ChrisDenton** [comment]
Maybe changing the lock file affects the cache in some way that makes this error more likely to be hit? It does seem incredibly frequent with this PR.

**Comment by tgross35** [comment]
Yeah I don’t know why this is so weird, especially after your partial fix. When I’m back at a computer I’ll just try splitting it into a separate PR for each lockfile.

That is an interesting datapoint for the Windows CI issue if it seems like caching affects things.

**Comment by ChrisDenton** [comment]
trying to see if this is still a problem, if so #130151 may eliminate one source of failure.

**Comment by ChrisDenton** [comment]
Sorry for using this PR as a kind of canary but I'd like to try just one more time:

@bors retry

**Comment by tgross35** [comment]
> Sorry for using this PR as a kind of canary but I'd like to try just one more time:

Still haven’t gotten around to splitting this up, so be my guest :)

**Comment by workingjubilee** [comment]
PR's haunted.

**Comment by tgross35** [comment]
I dropped the library and rustbook changes from this PR, so updates are now spread across a couple smaller PRs:

- rustbook: https://github.com/rust-lang/rust/pull/130889
- most of library: https://github.com/rust-lang/rust/pull/130892
- library cc: https://github.com/rust-lang/rust/pull/130720
- library compiler-builtins: https://github.com/rust-lang/rust/pull/130875
- memchr (done): https://github.com/rust-lang/rust/pull/130788

Hoping that the MSVC failures isolate themselves to only a subset of these PRs.

@bors r=Mark-Simulacrum

**Comment by workingjubilee** [comment]
miraculous

**Comment by tgross35** [comment]
I guess we have some pretty likely indicators that the library `cc` update in particular is causing the near-100% failure rate in these PRs. Why exactly, that's an interesting question...

**Comment by ChrisDenton** [comment]
I'll try to see if anything in cc looks like it might cause problems. It's maybe a long shot though.

**Comment by tgross35** [comment]
I'm trying to see if there is a specific cc version where the awful rate starts or if it just seems to be any change. https://github.com/rust-lang/rust/pull/130898 only bumps to 1.0.106 and has failed twice, I'm trying 1.0.100 (smallest possible bump) in https://github.com/rust-lang/rust/pull/130908.

**Comment by arttet** [comment]
> I'll try to see if anything in cc looks like it might cause problems. It's maybe a long shot though.

Please look at this [commit](https://github.com/rust-lang/cc-rs/commit/a6a928ee073d1082bfcc9f351c42924ed64a6735). It seems it is suspicious.

**Comment by ChrisDenton** [comment]
That makes no practical difference. All DLLs are unloaded on process exit.

**Pull request merged**
