### PR TITLE
Implement RFC 1268 "Allow overlapping implementations for marker traits"

### PR DESCRIPTION
**Pull request by frewsxcv**
Rebased version of https://github.com/rust-lang/rust/pull/40097.

Tracking issue: https://github.com/rust-lang/rust/issues/29864.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Rebased in https://github.com/rust-lang/rust/pull/41309.

**Comment by frewsxcv** [comment]
Considering @nikomatsakis already approved https://github.com/rust-lang/rust/issues/40097 and all I did was add an unstable book entry, I hope I'm not overstepping my bounds just to do:

@bors r=nikomatsakis

**Comment by frewsxcv** [comment]
Rebased.

@bors r=nikomatsakis

**Comment by petrochenkov** [comment]
[meta] I've edited the PR name to include the RFC name.
Maybe CONTRIBUTING.md should tell people not to name PRs like "Fix #12345", but I'm not sure anybody reads it :(

**Comment by nikomatsakis** [comment]
@frewsxcv thanks for adding the book entry! I've been hoping to get to that.

**Pull request merged**
