### PR TITLE
Rollup of stuff (take 2)

### PR DESCRIPTION
**Pull request by Manishearth**
This should work now.

### CODE REVIEW

**Comment by Manishearth** [comment]
Removed @Ms2ger's failing test.

**Comment by Gankro** [comment]
oh derp

**Comment by eddyb** [comment]
@Manishearth You could have just fixed it (see my comment on his PR).

**Comment by Manishearth** [comment]
@eddyb History rewrites with merge commits are a bit harder to do and the merge commits tend to disappear.

**Comment by richo** [comment]
oof :(

**Comment by Manishearth** [comment]
Oh, no. @alexcrichton I seem to have bad luck rebasing these -- what sort of flags besides `--preserve-merges` do I feed to `git rebase`?

**Comment by alexcrichton** [comment]
I normally actually just run `git merge origin/master` as rebasing all the PRs is too much of a pain. Failing that `git rebase -p` should do the trick (to preserve merge commits)

**Pull request merged**
