### PR TITLE
binary_heap: Optimize Extend implementation.

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
This PR makes the `Extend` implementation for `BinaryHeap` no longer rely on specialization, so that it always use the bulk rebuild optimization that was previously only available for the `Vec` specialization.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Anyone around for review?

**Comment by ishitatsuyuki** [comment]
r? libs

**Comment by ishitatsuyuki** [comment]
r? libs

**Comment by thomcc** [comment]
Not familiar with binary heap internals.

r? libs

**Pull request merged**
