### PR TITLE
remove feature gate in control_flow examples

### PR DESCRIPTION
**Pull request by hellow554**
Stabilization was done in https://github.com/rust-lang/rust/pull/91091, but the two examples weren't updated accordingly.

Probably too late to put it into stable, but it should be in the next release :)

### CODE REVIEW

**Comment by ehuss** [comment]
Beta nominated to avoid confusion.

**Comment by Mark-Simulacrum** [comment]
CI did not catch this because the feature gate is *still* unstable -- it's probably not used for these examples, which is why removing it is fine, but I think we don't track libs feature usage at such a level?

**Comment by ehuss** [comment]
I'm not sure I understand the comment.  The `control_flow_enum` feature was needed previously.  When it was stabilized, it was split off to `control_flow_enum_is`.  However, that's not really important.  Doc tests don't deny warnings (they don't show at all), so the `stable_features` lint has no effect.  CI currently doesn't check for things like this.

**Comment by Mark-Simulacrum** [comment]
Yeah, @Urgau pointed me to the rustdoc allow list -- that's likely the real issue here.

That said, it does look like there are some unstable remnants too still under control_flow_enum (https://github.com/rust-lang/rust/blob/08504c64aa7c4163a51c1982ed10075bb89cec0e/library/core/src/ops/control_flow.rs#L177).

**Comment by Mark-Simulacrum** [comment]
Discussed briefly in an ad-hoc libs meeting (with very partial attendance), but in any case, seems like a reasonable backport. Approving.

**Pull request merged**
