### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Michael8373**

### CODE REVIEW

**Review by A123D11 — APPROVED** [review]

**Comment by slanterns** [comment]
It's not better than the original chapter of the book, which contains more useful information.

**Comment by slanterns** [comment]
Also, the format is broken. Please do not simply copy-and-paste from the webpage.

**Review by jieyouxu — COMMENTED** [review]
Thank you for the PR, but I don't find this clearer than the original README.md which delegates detailed regular-user-facing installation instructions to the book. This excerpt leaves out detailed information that was present in the chapter of the book. This formatting I find makes it more confusing than before.

In particular, the `README.md` here is intended mostly as a hub to connect the various pieces of documentation that serves different audiences (i.e. regular users vs contributors and the likes).

Also you removed the links to the book.

**Comment by jieyouxu** [comment]
I'm going to close this PR as I don't think it's an improvement. Thanks!

**Pull request closed without merging**
