### PR TITLE
Migrate `run-make/rustdoc-error-lines` to new `rmake.rs`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/rust-lang/rust/issues/121876.

There was a weird naming inconsistency with `input`/`output`. A few tests write `.arg("-o").arg(path)` and the `output` method was actually the command output. So instead, I renamed the original `output` into `command_output` so that I could create the `output` method with the expected effect (and updated the tests to use it too).

EDIT: The first two commits come from https://github.com/rust-lang/rust/pull/124711. Some weird things happened recently pparently. ^^'

r? @jieyouxu

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
CI passed this time. :)

**Review by jieyouxu — APPROVED** [review]

**Comment by jieyouxu** [comment]
Thanks!

@bors r+ rollup

**Comment by GuillaumeGomez** [comment]
Thanks for the notification, fixed it.

@bors r=jieyouxu rollup

**Pull request merged**
