### PR TITLE
[CRATER] Crater Rollup

### PR DESCRIPTION
**Pull request by compiler-errors**
This is a " crater rollup" of:
* #126452
* #128784
* #129392
* #129422
* #129543
* #129604

**What is a crater rollup?** It's simply a crater job that is run on all of the containing PRs *together*, and then we can set the crates list for each of these jobs to just the failures after it's done. It should cut out on the bulk of "normal" crates that do nothing and simply just take time to build.

r? @ghost

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check p=6

Will need to do a bit of a dance once this crater run is finished, since the next job in the queue is part of this run. I'll need to set all the crates lists first, then stop and re-queue it. Anyways, just leaving a note for myself.

**Comment by compiler-errors** [comment]
@craterbot cancel

**Comment by compiler-errors** [comment]
crater command:

> craterbot run mode=check-only start=master#1f12b9b0fdbe735968ac002792a720f0ba4faca6 end=try#f87d38216adff5a6b0df2d9c92ea2690b8066726+rustflags=-Dtail_expr_drop_order

**Comment by compiler-errors** [comment]
@craterbot run mode=check-only start=master#1f12b9b0fdbe735968ac002792a720f0ba4faca6 end=try#f9935d29d867449445ee008640ccca1bf1ae0889+rustflags=-Dtail_expr_drop_order p=6 name=crater-rollup-uwu

**Comment by matthiaskrgr** [comment]
image

do we check some crates twice or someting?

**Comment by compiler-errors** [comment]
time travel, perhaps

**Comment by compiler-errors** [comment]
This PR has served its purpose -- I have adjusted the crates lists on each experiment in this rollup.

This should shorten each job by 5x hopefully.

**Pull request closed without merging**
