### PR TITLE
Add Cargo.lock automatically adding message

### PR DESCRIPTION
**Pull request by h-michael**
If I execute `cargo +nightly fix`, this change always occurs; cc #58099
r? @Centril

### CODE REVIEW

**Comment by taiki-e** [comment]
`cargo +nightly fix` automatically do commit up? Otherwise, you should be able to exclude `Cargo.lock` before you commit your changes.

Also, if you execute [`python x.py test`](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#pull-requests) etc, similar messages should be added to `Cargo.lock`.

**Comment by h-michael** [comment]
> cargo +nightly fix automatically do commit up? Otherwise, you should be able to exclude Cargo.lock before you commit your changes.

Yes, I can exclude Cargo.lock before commit.
But I get this change in everytime. That bothers me :(.

**Comment by ehuss** [comment]
fwiw, this needs to be done eventually (once stage0 is 1.34), and it should be safe to do now.  Stable Cargo preserves the comment.

**Pull request merged**
